v8::base::EmulatedVirtualAddressSubspace Class Reference
Emulates a virtual address subspace.
#include <emulated-virtual-address-subspace.h>
Public Member Functions
EmulatedVirtualAddressSubspace (v8::VirtualAddressSpace *parent_space, Address base, size_t mapped_size, size_t total_size)
~EmulatedVirtualAddressSubspace () override
void SetRandomSeed (int64_t seed) override
Address RandomPageAddress () override
Address AllocatePages (Address hint, size_t size, size_t alignment, PagePermissions permissions) override
void FreePages (Address address, size_t size) override
Address AllocateSharedPages (Address hint, size_t size, PagePermissions permissions, PlatformSharedMemoryHandle handle, uint64_t offset) override
void FreeSharedPages (Address address, size_t size) override
bool SetPagePermissions (Address address, size_t size, PagePermissions permissions) override
bool AllocateGuardRegion (Address address, size_t size) override
void FreeGuardRegion (Address address, size_t size) override
bool CanAllocateSubspaces () override
std::unique_ptr< v8::VirtualAddressSpace > AllocateSubspace (Address hint, size_t size, size_t alignment, PagePermissions max_page_permissions) override
bool RecommitPages (Address address, size_t size, PagePermissions permissions) override
bool DiscardSystemPages (Address address, size_t size) override
bool DecommitPages (Address address, size_t size) override
Private Member Functions
size_t mapped_size () const
size_t unmapped_size () const
Address mapped_base () const
Address unmapped_base () const
bool Contains (Address outer_start, size_t outer_size, Address inner_start, size_t inner_size) const
bool Contains (Address addr, size_t length) const
bool MappedRegionContains (Address addr, size_t length) const
bool UnmappedRegionContains (Address addr, size_t length) const
bool IsUsableSizeForUnmappedRegion (size_t size) const
Private Attributes
const size_t mapped_size_
v8::VirtualAddressSpace * parent_space_
Mutex mutex_
RegionAllocator region_allocator_
RandomNumberGenerator rng_
Detailed Description
Emulates a virtual address subspace.
This class is (optionally) backed by a page allocation and emulates a virtual address space that is potentially larger than that mapping. It generally first attempts to satisfy page allocation requests from its backing mapping, but will also attempt to obtain new page mappings inside the unmapped space through page allocation hints if necessary.
Caveat: an emulated subspace violates the invariant that page allocations in an address space will never end up inside a child space and so does not provide the same security gurarantees.
Definition at line 31 of file emulated-virtual-address-subspace.h.
Constructor & Destructor Documentation
EmulatedVirtualAddressSubspace()
v8::base::EmulatedVirtualAddressSubspace::EmulatedVirtualAddressSubspace (v8::VirtualAddressSpace * parent_space, Address base, size_t mapped_size, size_t total_size)
Definition at line 13 of file emulated-virtual-address-subspace.cc.
    : VirtualAddressSpace(parent_space->page_size(),
                          parent_space->allocation_granularity(), base,
                          total_size, parent_space->max_page_permissions()),
      mapped_size_(mapped_size),
      parent_space_(parent_space),
      region_allocator_(base, mapped_size, parent_space_->page_size()) {
  // For simplicity, we currently require both the mapped and total size to be
  // a power of two. This simplifies some things later on, for example, random
  // addresses can be generated with a simply bitmask, and will then be inside
  // the unmapped space with a probability >= 50% (mapped size == unmapped
  // size) or never (mapped size == total size).
  DCHECK(base::bits::IsPowerOfTwo(mapped_size));
  DCHECK(base::bits::IsPowerOfTwo(total_size));
}
References DCHECK, v8::base::bits::IsPowerOfTwo(), and mapped_size().
 EmulatedVirtualAddressSubspace()
v8::base::EmulatedVirtualAddressSubspace::~EmulatedVirtualAddressSubspace () [override]
Definition at line 31 of file emulated-virtual-address-subspace.cc.
                                                                {
  parent_space_->FreePages(base(), mapped_size_);
}
References v8::VirtualAddressSpace::FreePages(), mapped_size_, and parent_space_.
Member Function Documentation
AllocateGuardRegion()
bool v8::base::EmulatedVirtualAddressSubspace::AllocateGuardRegion (Address address, size_t size) [override]
Definition at line 147 of file emulated-virtual-address-subspace.cc.
                                                                      {
  if (MappedRegionContains(address, size)) {
    MutexGuard guard(&mutex_);
    return region_allocator_.AllocateRegionAt(address, size);
  }
  if (!UnmappedRegionContains(address, size)) return false;
  return parent_space_->AllocateGuardRegion(address, size);
}
References v8::VirtualAddressSpace::AllocateGuardRegion(), v8::base::RegionAllocator::AllocateRegionAt(), MappedRegionContains(), mutex_, parent_space_, region_allocator_, size(), and UnmappedRegionContains().
AllocatePages()
Address v8::base::EmulatedVirtualAddressSubspace::AllocatePages (Address hint, size_t size, size_t alignment, PagePermissions permissions) [override]
Definition at line 46 of file emulated-virtual-address-subspace.cc.
                                                                              {
  if (hint == kNoHint || MappedRegionContains(hint, size)) {
    MutexGuard guard(&mutex_);
    // Attempt to find a region in the mapped region.
    Address address = region_allocator_.AllocateRegion(hint, size, alignment);
    if (address != RegionAllocator::kAllocationFailure) {
      // Success. Only need to adjust the page permissions.
      if (parent_space_->SetPagePermissions(address, size, permissions)) {
        return address;
      }
      // Probably ran out of memory, but still try to allocate in the unmapped
      // space.
      CHECK_EQ(size, region_allocator_.FreeRegion(address));
    }
  }
  // No luck or hint is outside of the mapped region. Try to allocate pages in
  // the unmapped space using page allocation hints instead.
  if (!IsUsableSizeForUnmappedRegion(size)) return kNullAddress;
  static constexpr int kMaxAttempts = 10;
  for (int i = 0; i < kMaxAttempts; i++) {
    // If an unmapped region exists, it must cover at least 50% of the whole
    // space (unmapped + mapped region). Since we limit the size of allocation
    // to 50% of the unmapped region (see IsUsableSizeForUnmappedRegion), a
    // random page address has at least a 25% chance of being a usable base. As
    // such, this loop should usually terminate quickly.
    DCHECK_GE(unmapped_size(), mapped_size());
    while (!UnmappedRegionContains(hint, size)) {
      hint = RandomPageAddress();
    }
    hint = RoundDown(hint, alignment);
    const Address result =
        parent_space_->AllocatePages(hint, size, alignment, permissions);
    if (UnmappedRegionContains(result, size)) {
      return result;
    } else if (result) {
      parent_space_->FreePages(result, size);
    }
    // Retry at a different address.
    hint = RandomPageAddress();
  }
  return kNullAddress;
}
References v8::VirtualAddressSpace::AllocatePages(), v8::base::RegionAllocator::AllocateRegion(), CHECK_EQ, DCHECK_GE, v8::VirtualAddressSpace::FreePages(), v8::base::RegionAllocator::FreeRegion(), IsUsableSizeForUnmappedRegion(), v8::base::RegionAllocator::kAllocationFailure, v8::base::kNullAddress, mapped_size(), MappedRegionContains(), mutex_, parent_space_, RandomPageAddress(), region_allocator_, v8::base::internal::result, RoundDown(), v8::VirtualAddressSpace::SetPagePermissions(), size(), unmapped_size(), and UnmappedRegionContains().
AllocateSharedPages()
Address v8::base::EmulatedVirtualAddressSubspace::AllocateSharedPages (Address hint, size_t size, PagePermissions permissions, PlatformSharedMemoryHandle handle, uint64_t offset) [override]
Definition at line 107 of file emulated-virtual-address-subspace.cc.
                                                        {
  // Can only allocate shared pages in the unmapped region.
  if (!IsUsableSizeForUnmappedRegion(size)) return kNullAddress;
  static constexpr int kMaxAttempts = 10;
  for (int i = 0; i < kMaxAttempts; i++) {
    // See AllocatePages() for why this loop usually terminates quickly.
    DCHECK_GE(unmapped_size(), mapped_size());
    while (!UnmappedRegionContains(hint, size)) {
      hint = RandomPageAddress();
    }
    Address region = parent_space_->AllocateSharedPages(hint, size, permissions,
                                                        handle, offset);
    if (UnmappedRegionContains(region, size)) {
      return region;
    } else if (region) {
      parent_space_->FreeSharedPages(region, size);
    }
    hint = RandomPageAddress();
  }
  return kNullAddress;
}
References v8::VirtualAddressSpace::AllocateSharedPages(), DCHECK_GE, v8::VirtualAddressSpace::FreeSharedPages(), v8::internal::handle(), IsUsableSizeForUnmappedRegion(), v8::base::kNullAddress, mapped_size(), parent_space_, RandomPageAddress(), size(), unmapped_size(), and UnmappedRegionContains().
AllocateSubspace()
std::unique_ptr< v8::VirtualAddressSpace > v8::base::EmulatedVirtualAddressSubspace::AllocateSubspace (Address hint, size_t size, size_t alignment, PagePermissions max_page_permissions) [override]
Definition at line 174 of file emulated-virtual-address-subspace.cc.
                                          {
  UNREACHABLE();
}
References UNREACHABLE.
CanAllocateSubspaces()
bool v8::base::EmulatedVirtualAddressSubspace::CanAllocateSubspaces () [override]
Definition at line 168 of file emulated-virtual-address-subspace.cc.
                                                          {
  // This is not supported, mostly because it's not (yet) needed in practice.
  return false;
}
Contains() [1/2]
bool v8::base::EmulatedVirtualAddressSubspace::Contains (Address addr, size_t length) const [inline], [private]
Definition at line 93 of file emulated-virtual-address-subspace.h.
                                                   {
    return Contains(base(), size(), addr, length);
  }
References v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains(), v8::internal::length, and size().
Contains() [2/2]
bool v8::base::EmulatedVirtualAddressSubspace::Contains (Address outer_start, size_t outer_size, Address inner_start, size_t inner_size) const [inline], [private]
Definition at line 87 of file emulated-virtual-address-subspace.h.
                                         {
    return (inner_start >= outer_start) &&
           ((inner_start + inner_size) <= (outer_start + outer_size));
  }
Referenced by DecommitPages(), DiscardSystemPages(), RecommitPages(), and SetPagePermissions().
DecommitPages()
bool v8::base::EmulatedVirtualAddressSubspace::DecommitPages (Address address, size_t size) [override]
Definition at line 192 of file emulated-virtual-address-subspace.cc.
                                                                {
  DCHECK(Contains(address, size));
  return parent_space_->DecommitPages(address, size);
}
References Contains(), DCHECK, v8::VirtualAddressSpace::DecommitPages(), parent_space_, and size().
DiscardSystemPages()
bool v8::base::EmulatedVirtualAddressSubspace::DiscardSystemPages (Address address, size_t size) [override]
Definition at line 186 of file emulated-virtual-address-subspace.cc.
                                                                     {
  DCHECK(Contains(address, size));
  return parent_space_->DiscardSystemPages(address, size);
}
References Contains(), DCHECK, v8::VirtualAddressSpace::DiscardSystemPages(), parent_space_, and size().
FreeGuardRegion()
void v8::base::EmulatedVirtualAddressSubspace::FreeGuardRegion (Address address, size_t size) [override]
Definition at line 157 of file emulated-virtual-address-subspace.cc.
                                                                  {
  if (MappedRegionContains(address, size)) {
    MutexGuard guard(&mutex_);
    CHECK_EQ(size, region_allocator_.FreeRegion(address));
  } else {
    DCHECK(UnmappedRegionContains(address, size));
    parent_space_->FreeGuardRegion(address, size);
  }
}
References CHECK_EQ, DCHECK, v8::VirtualAddressSpace::FreeGuardRegion(), v8::base::RegionAllocator::FreeRegion(), MappedRegionContains(), mutex_, parent_space_, region_allocator_, size(), and UnmappedRegionContains().
FreePages()
void v8::base::EmulatedVirtualAddressSubspace::FreePages (Address address, size_t size) [override]
Definition at line 96 of file emulated-virtual-address-subspace.cc.
                                                                           {
  if (MappedRegionContains(address, size)) {
    MutexGuard guard(&mutex_);
    CHECK_EQ(size, region_allocator_.FreeRegion(address));
    CHECK(parent_space_->DecommitPages(address, size));
  } else {
    DCHECK(UnmappedRegionContains(address, size));
    parent_space_->FreePages(address, size);
  }
}
References CHECK, CHECK_EQ, DCHECK, v8::VirtualAddressSpace::DecommitPages(), v8::VirtualAddressSpace::FreePages(), v8::base::RegionAllocator::FreeRegion(), MappedRegionContains(), mutex_, parent_space_, region_allocator_, size(), and UnmappedRegionContains().
FreeSharedPages()
void v8::base::EmulatedVirtualAddressSubspace::FreeSharedPages (Address address, size_t size) [override]
Definition at line 135 of file emulated-virtual-address-subspace.cc.
                                                                  {
  DCHECK(UnmappedRegionContains(address, size));
  parent_space_->FreeSharedPages(address, size);
}
References DCHECK, v8::VirtualAddressSpace::FreeSharedPages(), parent_space_, size(), and UnmappedRegionContains().
IsUsableSizeForUnmappedRegion()
bool v8::base::EmulatedVirtualAddressSubspace::IsUsableSizeForUnmappedRegion (size_t size) const [inline], [private]
Definition at line 108 of file emulated-virtual-address-subspace.h.
                                                        {
    return size <= (unmapped_size() / 2);
  }
References size().
Referenced by AllocatePages(), and AllocateSharedPages().
mapped_base()
Address v8::base::EmulatedVirtualAddressSubspace::mapped_base () const [inline], [private]
Definition at line 84 of file emulated-virtual-address-subspace.h.
{ return base(); }
mapped_size()
size_t v8::base::EmulatedVirtualAddressSubspace::mapped_size () const [inline], [private]
Definition at line 81 of file emulated-virtual-address-subspace.h.
{ return mapped_size_; }
Referenced by AllocatePages(), AllocateSharedPages(), and EmulatedVirtualAddressSubspace().
MappedRegionContains()
bool v8::base::EmulatedVirtualAddressSubspace::MappedRegionContains (Address addr, size_t length) const [inline], [private]
Definition at line 97 of file emulated-virtual-address-subspace.h.
                                                               {
    return Contains(mapped_base(), mapped_size(), addr, length);
  }
References v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains(), and v8::internal::length.
Referenced by AllocateGuardRegion(), AllocatePages(), FreeGuardRegion(), and FreePages().
RandomPageAddress()
Address v8::base::EmulatedVirtualAddressSubspace::RandomPageAddress () [override]
Definition at line 40 of file emulated-virtual-address-subspace.cc.
                                                          {
  MutexGuard guard(&mutex_);
  Address addr = base() + (static_cast<uint64_t>(rng_.NextInt64()) % size());
  return RoundDown(addr, allocation_granularity());
}
References mutex_, v8::base::RandomNumberGenerator::NextInt64(), rng_, RoundDown(), and size().
Referenced by AllocatePages(), and AllocateSharedPages().
RecommitPages()
bool v8::base::EmulatedVirtualAddressSubspace::RecommitPages (Address address, size_t size, PagePermissions permissions) [override]
Definition at line 180 of file emulated-virtual-address-subspace.cc.
                                                               {
  DCHECK(Contains(address, size));
  return parent_space_->RecommitPages(address, size, permissions);
}
References Contains(), DCHECK, parent_space_, v8::VirtualAddressSpace::RecommitPages(), and size().
SetPagePermissions()
bool v8::base::EmulatedVirtualAddressSubspace::SetPagePermissions (Address address, size_t size, PagePermissions permissions) [override]
Definition at line 141 of file emulated-virtual-address-subspace.cc.
                                                               {
  DCHECK(Contains(address, size));
  return parent_space_->SetPagePermissions(address, size, permissions);
}
References Contains(), DCHECK, parent_space_, v8::VirtualAddressSpace::SetPagePermissions(), and size().
SetRandomSeed()
void v8::base::EmulatedVirtualAddressSubspace::SetRandomSeed (int64_t seed) [override]
Definition at line 35 of file emulated-virtual-address-subspace.cc.
                                                               {
  MutexGuard guard(&mutex_);
  rng_.SetSeed(seed);
}
References mutex_, rng_, and v8::base::RandomNumberGenerator::SetSeed().
unmapped_base()
Address v8::base::EmulatedVirtualAddressSubspace::unmapped_base () const [inline], [private]
Definition at line 85 of file emulated-virtual-address-subspace.h.
{ return base() + mapped_size_; }
unmapped_size()
size_t v8::base::EmulatedVirtualAddressSubspace::unmapped_size () const [inline], [private]
Definition at line 82 of file emulated-virtual-address-subspace.h.
{ return size() - mapped_size_; }
References size().
Referenced by AllocatePages(), and AllocateSharedPages().
UnmappedRegionContains()
bool v8::base::EmulatedVirtualAddressSubspace::UnmappedRegionContains (Address addr, size_t length) const [inline], [private]
Definition at line 101 of file emulated-virtual-address-subspace.h.
                                                                 {
    return Contains(unmapped_base(), unmapped_size(), addr, length);
  }
References v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains(), and v8::internal::length.
Referenced by AllocateGuardRegion(), AllocatePages(), AllocateSharedPages(), FreeGuardRegion(), FreePages(), and FreeSharedPages().
Member Data Documentation
mapped_size_
const size_t v8::base::EmulatedVirtualAddressSubspace::mapped_size_ [private]
Definition at line 113 of file emulated-virtual-address-subspace.h.
Referenced by ~EmulatedVirtualAddressSubspace().
mutex_
Mutex v8::base::EmulatedVirtualAddressSubspace::mutex_ [private]
Definition at line 121 of file emulated-virtual-address-subspace.h.
Referenced by AllocateGuardRegion(), AllocatePages(), FreeGuardRegion(), FreePages(), RandomPageAddress(), and SetRandomSeed().
parent_space_
v8::VirtualAddressSpace* v8::base::EmulatedVirtualAddressSubspace::parent_space_ [private]
Definition at line 117 of file emulated-virtual-address-subspace.h.
Referenced by AllocateGuardRegion(), AllocatePages(), AllocateSharedPages(), DecommitPages(), DiscardSystemPages(), FreeGuardRegion(), FreePages(), FreeSharedPages(), RecommitPages(), SetPagePermissions(), and ~EmulatedVirtualAddressSubspace().
region_allocator_
RegionAllocator v8::base::EmulatedVirtualAddressSubspace::region_allocator_ [private]
Definition at line 125 of file emulated-virtual-address-subspace.h.
Referenced by AllocateGuardRegion(), AllocatePages(), FreeGuardRegion(), and FreePages().
rng_
RandomNumberGenerator v8::base::EmulatedVirtualAddressSubspace::rng_ [private]
Definition at line 128 of file emulated-virtual-address-subspace.h.
Referenced by RandomPageAddress(), and SetRandomSeed().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/emulated-virtual-address-subspace.h
/mnt/V8SourceCode/src/base/emulated-virtual-address-subspace.cc