v8::internal::wasm::DescriptorsSectionIterator::ImportEntry Class Reference
#include <module-decoder-impl.h>
Public Member Functions
WireBytesRef name ()
Private Member Functions
ImportEntry (DescriptorsSectionIterator *decoder)
Friends
class DescriptorsSectionIterator
Additional Inherited Members
Detailed Description
Definition at line 3113 of file module-decoder-impl.h.
Constructor & Destructor Documentation
ImportEntry()
v8::internal::wasm::DescriptorsSectionIterator::ImportEntry::ImportEntry (DescriptorsSectionIterator * decoder) [inline], [explicit], [private]
Definition at line 3125 of file module-decoder-impl.h.
        : Entry(decoder) {}
Member Function Documentation
name()
WireBytesRef v8::internal::wasm::DescriptorsSectionIterator::ImportEntry::name () [inline]
Definition at line 3115 of file module-decoder-impl.h.
                        {
      DCHECK_EQ(state(), State::kParentOrImport);
      WireBytesRef name = consume_string("import name");
      ProceedToExports();
      return name;
    }
References v8::internal::wasm::DescriptorsSectionIterator::Entry::consume_string(), DCHECK_EQ, v8::internal::wasm::DescriptorsSectionIterator::Entry::kParentOrImport, v8::internal::wasm::DescriptorsSectionIterator::Entry::ProceedToExports(), and v8::internal::wasm::DescriptorsSectionIterator::Entry::state().
Referenced by v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl().
Friends And Related Function Documentation
DescriptorsSectionIterator
friend class DescriptorsSectionIterator [friend]
Definition at line 3123 of file module-decoder-impl.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-decoder-impl.h