v8::internal::maglev::DefineNamedOwnGeneric Class Reference
#include <maglev-ir.h>
Public Member Functions
DefineNamedOwnGeneric (uint64_t bitfield, compiler::NameRef name, const compiler::FeedbackSource &feedback)
compiler::NameRef name () const
compiler::FeedbackSource feedback () const
Input & context ()
Input & object_input ()
Input & value_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes
static constexpr int kContextIndex = 0
static constexpr int kObjectIndex = 1
static constexpr int kValueIndex = 2
Private Types
using Base = FixedInputValueNodeT< 3, DefineNamedOwnGeneric >
Private Attributes
const compiler::NameRef name_
const compiler::FeedbackSource feedback_
Additional Inherited Members
Detailed Description
Definition at line 9584 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::DefineNamedOwnGeneric::Base = FixedInputValueNodeT<3, DefineNamedOwnGeneric> [private]
Definition at line 9586 of file maglev-ir.h.
Constructor & Destructor Documentation
DefineNamedOwnGeneric()
v8::internal::maglev::DefineNamedOwnGeneric::DefineNamedOwnGeneric (uint64_t bitfield, compiler::NameRef name, const compiler::FeedbackSource & feedback) [inline], [explicit]
Definition at line 9589 of file maglev-ir.h.
      : Base(bitfield), name_(name), feedback_(feedback) {}
Member Function Documentation
context()
Input& v8::internal::maglev::DefineNamedOwnGeneric::context () [inline]
Definition at line 9605 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::DefineNamedOwnGeneric::feedback () const [inline]
Definition at line 9600 of file maglev-ir.h.
{ return feedback_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::DefineNamedOwnGeneric::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::DefineNamedOwnGeneric::MaxCallStackArgs () const
name()
compiler::NameRef v8::internal::maglev::DefineNamedOwnGeneric::name () const [inline]
Definition at line 9599 of file maglev-ir.h.
{ return name_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
object_input()
Input& v8::internal::maglev::DefineNamedOwnGeneric::object_input () [inline]
Definition at line 9606 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::DefineNamedOwnGeneric::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8284 of file maglev-ir.cc.
                                                               {
  os << "(" << *name_.object() << ")";
}
References name_, and v8::internal::compiler::NameRef::object().
SetValueLocationConstraints()
void v8::internal::maglev::DefineNamedOwnGeneric::SetValueLocationConstraints ()
value_input()
Input& v8::internal::maglev::DefineNamedOwnGeneric::value_input () [inline]
Definition at line 9607 of file maglev-ir.h.
{ return input(kValueIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
feedback_
const compiler::FeedbackSource v8::internal::maglev::DefineNamedOwnGeneric::feedback_ [private]
Definition at line 9616 of file maglev-ir.h.
kContextIndex
constexpr int v8::internal::maglev::DefineNamedOwnGeneric::kContextIndex = 0 [static], [constexpr]
Definition at line 9602 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::DefineNamedOwnGeneric::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged,
      ValueRepresentation::kTagged}
Definition at line 9595 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::DefineNamedOwnGeneric::kObjectIndex = 1 [static], [constexpr]
Definition at line 9603 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::DefineNamedOwnGeneric::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 9594 of file maglev-ir.h.
kValueIndex
constexpr int v8::internal::maglev::DefineNamedOwnGeneric::kValueIndex = 2 [static], [constexpr]
Definition at line 9604 of file maglev-ir.h.
name_
const compiler::NameRef v8::internal::maglev::DefineNamedOwnGeneric::name_ [private]
Definition at line 9615 of file maglev-ir.h.
Referenced by PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc