v8::internal::FastKeyAccumulator Class Reference
#include <keys.h>
Public Member Functions
FastKeyAccumulator (Isolate *isolate, DirectHandle< JSReceiver > receiver, KeyCollectionMode mode, PropertyFilter filter, bool is_for_in=false, bool skip_indices=false)
FastKeyAccumulator (const FastKeyAccumulator &)=delete
FastKeyAccumulator & operator= (const FastKeyAccumulator &)=delete
bool is_receiver_simple_enum ()
bool has_empty_prototype ()
bool may_have_elements ()
MaybeHandle< FixedArray > GetKeys (GetKeysConversion convert=GetKeysConversion::kKeepNumbers)
Static Public Member Functions
static Handle< FixedArray > InitializeFastPropertyEnumCache (Isolate *isolate, DirectHandle< Map > map, int enum_length, AllocationType allocation=AllocationType::kOld)
Private Member Functions
void Prepare ()
MaybeHandle< FixedArray > GetKeysFast (GetKeysConversion convert)
MaybeHandle< FixedArray > GetKeysSlow (GetKeysConversion convert)
MaybeHandle< FixedArray > GetKeysWithPrototypeInfoCache (GetKeysConversion convert)
MaybeHandle< FixedArray > GetOwnKeysWithUninitializedEnumLength ()
bool MayHaveElements (Tagged< JSReceiver > receiver)
bool TryPrototypeInfoCache (DirectHandle< JSReceiver > receiver)
Private Attributes
Isolate * isolate_
DirectHandle< JSReceiver > receiver_
DirectHandle< Map > first_prototype_map_
DirectHandle< JSReceiver > first_prototype_
DirectHandle< JSReceiver > last_non_empty_prototype_
KeyCollectionMode mode_
PropertyFilter filter_
bool is_for_in_ = false
bool skip_indices_ = false
bool is_receiver_simple_enum_ = false
bool has_empty_prototype_ = false
bool may_have_elements_ = true
bool has_prototype_info_cache_ = false
bool try_prototype_info_cache_ = false
bool only_own_has_simple_elements_ = false
Detailed Description
Definition at line 181 of file keys.h.
Constructor & Destructor Documentation
FastKeyAccumulator() [1/2]
v8::internal::FastKeyAccumulator::FastKeyAccumulator (Isolate * isolate, DirectHandle< JSReceiver > receiver, KeyCollectionMode mode, PropertyFilter filter, bool is_for_in = false, bool skip_indices = false) [inline]
Definition at line 183 of file keys.h.
      : isolate_(isolate),
        receiver_(receiver),
        mode_(mode),
        filter_(filter),
        is_for_in_(is_for_in),
        skip_indices_(skip_indices) {
    Prepare();
  }
References Prepare().
FastKeyAccumulator() [2/2]
v8::internal::FastKeyAccumulator::FastKeyAccumulator (const FastKeyAccumulator &) [delete]
Member Function Documentation
GetKeys()
MaybeHandle< FixedArray > v8::internal::FastKeyAccumulator::GetKeys (GetKeysConversion convert = GetKeysConversion::kKeepNumbers)
Definition at line 454 of file keys.cc.
                                       {
  // TODO(v8:9401): We should extend the fast path of KeyAccumulator::GetKeys to
  // also use fast path even when filter = SKIP_SYMBOLS. We used to pass wrong
  // filter to use fast path in cases where we tried to verify all properties
  // are enumerable. However these checks weren't correct and passing the wrong
  // filter led to wrong behaviour.
  if (filter_ == ENUMERABLE_STRINGS) {
    Handle<FixedArray> keys;
    if (GetKeysFast(keys_conversion).ToHandle(&keys)) {
      return keys;
    }
    if (isolate_->has_exception()) return MaybeHandle<FixedArray>();
  }
  if (try_prototype_info_cache_) {
    return GetKeysWithPrototypeInfoCache(keys_conversion);
  }
  return GetKeysSlow(keys_conversion);
}
References v8::internal::ENUMERABLE_STRINGS, filter_, GetKeysFast(), GetKeysSlow(), GetKeysWithPrototypeInfoCache(), v8::internal::Isolate::has_exception(), isolate_, v8::anonymous_namespace{api.cc}::ToHandle(), and try_prototype_info_cache_.
Referenced by v8::internal::anonymous_namespace{runtime-forin.cc}::Enumerate(), and v8::internal::KeyAccumulator::GetKeys().
GetKeysFast()
MaybeHandle< FixedArray > v8::internal::FastKeyAccumulator::GetKeysFast (GetKeysConversion convert) [private]
Definition at line 475 of file keys.cc.
                                       {
  bool own_only = has_empty_prototype_ || mode_ == KeyCollectionMode::kOwnOnly;
  Tagged<Map> map = receiver_->map();
  if (!own_only || IsCustomElementsReceiverMap(map)) {
    return MaybeHandle<FixedArray>();
  }
  // From this point on we are certain to only collect own keys.
  DCHECK(IsJSObject(*receiver_));
  DirectHandle<JSObject> object = Cast<JSObject>(receiver_);
  // Do not try to use the enum-cache for dict-mode objects.
  if (map->is_dictionary_map()) {
    return GetOwnKeysWithElements<false>(isolate_, object, keys_conversion,
                                         skip_indices_);
  }
  int enum_length = receiver_->map()->EnumLength();
  if (enum_length == kInvalidEnumCacheSentinel) {
    Handle<FixedArray> keys;
    // Try initializing the enum cache and return own properties.
    if (GetOwnKeysWithUninitializedEnumLength().ToHandle(&keys)) {
      if (v8_flags.trace_for_in_enumerate) {
        PrintF("| strings=%d symbols=0 elements=0 || prototypes>=1 ||\n",
               keys->length());
      }
      is_receiver_simple_enum_ =
          object->map()->EnumLength() != kInvalidEnumCacheSentinel;
      return keys;
    }
  }
  // The properties-only case failed because there were probably elements on the
  // receiver.
  return GetOwnKeysWithElements<true>(isolate_, object, keys_conversion,
                                      skip_indices_);
}
References v8::internal::DCHECK(), GetOwnKeysWithUninitializedEnumLength(), has_empty_prototype_, is_receiver_simple_enum_, v8::internal::IsCustomElementsReceiverMap(), isolate_, v8::internal::kInvalidEnumCacheSentinel, v8::internal::kOwnOnly, mode_, v8::internal::PrintF(), receiver_, skip_indices_, v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::v8_flags.
Referenced by GetKeys().
GetKeysSlow()
MaybeHandle< FixedArray > v8::internal::FastKeyAccumulator::GetKeysSlow (GetKeysConversion convert) [private]
Definition at line 599 of file keys.cc.
                                       {
  KeyAccumulator accumulator(isolate_, mode_, filter_);
  accumulator.set_is_for_in(is_for_in_);
  accumulator.set_skip_indices(skip_indices_);
  accumulator.set_last_non_empty_prototype(last_non_empty_prototype_);
  accumulator.set_may_have_elements(may_have_elements_);
  accumulator.set_first_prototype_map(first_prototype_map_);
  accumulator.set_try_prototype_info_cache(try_prototype_info_cache_);
  MAYBE_RETURN(accumulator.CollectKeys(receiver_, receiver_),
               MaybeHandle<FixedArray>());
  return accumulator.GetKeys(keys_conversion);
}
References v8::internal::KeyAccumulator::CollectKeys(), filter_, first_prototype_map_, v8::internal::KeyAccumulator::GetKeys(), is_for_in_, isolate_, last_non_empty_prototype_, may_have_elements_, MAYBE_RETURN, mode_, receiver_, v8::internal::KeyAccumulator::set_first_prototype_map(), v8::internal::KeyAccumulator::set_is_for_in(), v8::internal::KeyAccumulator::set_last_non_empty_prototype(), v8::internal::KeyAccumulator::set_may_have_elements(), v8::internal::KeyAccumulator::set_skip_indices(), v8::internal::KeyAccumulator::set_try_prototype_info_cache(), skip_indices_, and try_prototype_info_cache_.
Referenced by GetKeys().
GetKeysWithPrototypeInfoCache()
MaybeHandle< FixedArray > v8::internal::FastKeyAccumulator::GetKeysWithPrototypeInfoCache (GetKeysConversion convert) [private]
Definition at line 614 of file keys.cc.
                                       {
  Handle<FixedArray> own_keys;
  if (may_have_elements_) {
    MaybeHandle<FixedArray> maybe_own_keys;
    if (receiver_->map()->is_dictionary_map()) {
      maybe_own_keys = GetOwnKeysWithElements<false>(
          isolate_, Cast<JSObject>(receiver_), keys_conversion, skip_indices_);
    } else {
      maybe_own_keys = GetOwnKeysWithElements<true>(
          isolate_, Cast<JSObject>(receiver_), keys_conversion, skip_indices_);
    }
    ASSIGN_RETURN_ON_EXCEPTION(isolate_, own_keys, maybe_own_keys);
  } else {
    own_keys = KeyAccumulator::GetOwnEnumPropertyKeys(
        isolate_, Cast<JSObject>(receiver_));
  }
  Handle<FixedArray> prototype_chain_keys;
  if (has_prototype_info_cache_) {
    prototype_chain_keys =
        handle(Cast<FixedArray>(
                   Cast<PrototypeInfo>(first_prototype_map_->prototype_info())
                       ->prototype_chain_enum_cache()),
               isolate_);
  } else {
    KeyAccumulator accumulator(isolate_, mode_, filter_);
    accumulator.set_is_for_in(is_for_in_);
    accumulator.set_skip_indices(skip_indices_);
    accumulator.set_last_non_empty_prototype(last_non_empty_prototype_);
    accumulator.set_may_have_elements(may_have_elements_);
    accumulator.set_receiver(receiver_);
    accumulator.set_first_prototype_map(first_prototype_map_);
    accumulator.set_try_prototype_info_cache(try_prototype_info_cache_);
    MAYBE_RETURN(accumulator.CollectKeys(first_prototype_, first_prototype_),
                 MaybeHandle<FixedArray>());
    prototype_chain_keys = accumulator.GetKeys(keys_conversion);
  }
  Handle<FixedArray> result = CombineKeys(
      isolate_, own_keys, prototype_chain_keys, receiver_, may_have_elements_);
  if (is_for_in_ && own_keys.is_identical_to(result)) {
    // Don't leak the enumeration cache without the receiver since it might get
    // trimmed otherwise.
    return isolate_->factory()->CopyFixedArrayUpTo(result, result->length());
  }
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::KeyAccumulator::CollectKeys(), v8::internal::anonymous_namespace{keys.cc}::CombineKeys(), v8::internal::Factory::CopyFixedArrayUpTo(), v8::internal::Isolate::factory(), filter_, first_prototype_, first_prototype_map_, v8::internal::KeyAccumulator::GetKeys(), v8::internal::KeyAccumulator::GetOwnEnumPropertyKeys(), v8::internal::handle(), has_prototype_info_cache_, is_for_in_, v8::internal::HandleBase::is_identical_to(), isolate_, last_non_empty_prototype_, may_have_elements_, MAYBE_RETURN, mode_, receiver_, v8::base::internal::result, v8::internal::KeyAccumulator::set_first_prototype_map(), v8::internal::KeyAccumulator::set_is_for_in(), v8::internal::KeyAccumulator::set_last_non_empty_prototype(), v8::internal::KeyAccumulator::set_may_have_elements(), v8::internal::KeyAccumulator::set_receiver(), v8::internal::KeyAccumulator::set_skip_indices(), v8::internal::KeyAccumulator::set_try_prototype_info_cache(), skip_indices_, and try_prototype_info_cache_.
Referenced by GetKeys().
GetOwnKeysWithUninitializedEnumLength()
MaybeHandle< FixedArray > v8::internal::FastKeyAccumulator::GetOwnKeysWithUninitializedEnumLength () [private]
Definition at line 576 of file keys.cc.
                                                          {
  auto object = Cast<JSObject>(receiver_);
  // Uninitialized enum length
  Tagged<Map> map = object->map();
  if (object->elements() != ReadOnlyRoots(isolate_).empty_fixed_array() &&
      object->elements() !=
          ReadOnlyRoots(isolate_).empty_slow_element_dictionary()) {
    // Assume that there are elements.
    return MaybeHandle<FixedArray>();
  }
  int number_of_own_descriptors = map->NumberOfOwnDescriptors();
  if (number_of_own_descriptors == 0) {
    map->SetEnumLength(0);
    return isolate_->factory()->empty_fixed_array();
  }
  // We have no elements but possibly enumerable property keys, hence we can
  // directly initialize the enum cache.
  Handle<FixedArray> keys = GetFastEnumPropertyKeys(isolate_, object);
  if (is_for_in_) return keys;
  // Do not leak the enum cache as it might end up as an elements backing store.
  return isolate_->factory()->CopyFixedArray(keys);
}
References v8::internal::Factory::CopyFixedArray(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{keys.cc}::GetFastEnumPropertyKeys(), is_for_in_, isolate_, and receiver_.
Referenced by GetKeysFast().
has_empty_prototype()
bool v8::internal::FastKeyAccumulator::has_empty_prototype () [inline]
Definition at line 198 of file keys.h.
{ return has_empty_prototype_; }
References has_empty_prototype_.
InitializeFastPropertyEnumCache()
Handle< FixedArray > v8::internal::FastKeyAccumulator::InitializeFastPropertyEnumCache (Isolate * isolate, DirectHandle< Map > map, int enum_length, AllocationType allocation = AllocationType::kOld) [static]
Definition at line 513 of file keys.cc.
                               {
  DCHECK_EQ(kInvalidEnumCacheSentinel, map->EnumLength());
  DCHECK_GT(enum_length, 0);
  DCHECK_EQ(enum_length, map->NumberOfEnumerableProperties());
  DCHECK(!map->is_dictionary_map());
  DirectHandle<DescriptorArray> descriptors(map->instance_descriptors(isolate),
                                            isolate);
  // The enum cache should have been a hit if the number of enumerable
  // properties is fewer than what's already in the cache.
  DCHECK_LT(descriptors->enum_cache()->keys()->length(), enum_length);
  isolate->counters()->enum_cache_misses()->Increment();
  // Create the keys array.
  int index = 0;
  bool fields_only = true;
  Handle<FixedArray> keys =
      isolate->factory()->NewFixedArray(enum_length, allocation);
  for (InternalIndex i : map->IterateOwnDescriptors()) {
    DisallowGarbageCollection no_gc;
    PropertyDetails details = descriptors->GetDetails(i);
    if (details.IsDontEnum()) continue;
    Tagged<Object> key = descriptors->GetKey(i);
    if (IsSymbol(key)) continue;
    keys->set(index, key);
    if (details.location() != PropertyLocation::kField) fields_only = false;
    index++;
  }
  DCHECK_EQ(index, keys->length());
  // Optionally also create the indices array.
  DirectHandle<FixedArray> indices = isolate->factory()->empty_fixed_array();
  if (fields_only) {
    indices = isolate->factory()->NewFixedArray(enum_length, allocation);
    index = 0;
    DisallowGarbageCollection no_gc;
    Tagged<Map> raw_map = *map;
    Tagged<FixedArray> raw_indices = *indices;
    Tagged<DescriptorArray> raw_descriptors = *descriptors;
    for (InternalIndex i : raw_map->IterateOwnDescriptors()) {
      PropertyDetails details = raw_descriptors->GetDetails(i);
      if (details.IsDontEnum()) continue;
      Tagged<Object> key = raw_descriptors->GetKey(i);
      if (IsSymbol(key)) continue;
      DCHECK_EQ(PropertyKind::kData, details.kind());
      DCHECK_EQ(PropertyLocation::kField, details.location());
      FieldIndex field_index = FieldIndex::ForDetails(raw_map, details);
      raw_indices->set(index, Smi::FromInt(field_index.GetLoadByFieldIndex()));
      index++;
    }
    DCHECK_EQ(index, indices->length());
  }
  DescriptorArray::InitializeOrChangeEnumCache(descriptors, isolate, keys,
                                               indices, allocation);
  if (map->OnlyHasSimpleProperties()) map->SetEnumLength(enum_length);
  return keys;
}
References v8::internal::Isolate::counters(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, DCHECK_LT, v8::internal::Isolate::factory(), v8::internal::FieldIndex::ForDetails(), v8::internal::Smi::FromInt(), v8::internal::FieldIndex::GetLoadByFieldIndex(), v8::internal::index, v8::internal::DescriptorArray::InitializeOrChangeEnumCache(), v8::internal::PropertyDetails::IsDontEnum(), v8::internal::kData, v8::internal::key, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::kInvalidEnumCacheSentinel, v8::internal::PropertyDetails::location(), v8::internal::FactoryBase< Impl >::NewFixedArray(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::MapUpdater::ConstructNewMap(), v8::internal::anonymous_namespace{keys.cc}::GetFastEnumPropertyKeys(), and v8::internal::AlwaysSharedSpaceJSObject::PrepareMapWithEnumerableProperties().
is_receiver_simple_enum()
bool v8::internal::FastKeyAccumulator::is_receiver_simple_enum () [inline]
Definition at line 197 of file keys.h.
{ return is_receiver_simple_enum_; }
References is_receiver_simple_enum_.
Referenced by v8::internal::anonymous_namespace{runtime-forin.cc}::Enumerate().
may_have_elements()
bool v8::internal::FastKeyAccumulator::may_have_elements () [inline]
Definition at line 199 of file keys.h.
{ return may_have_elements_; }
References may_have_elements_.
Referenced by v8::internal::anonymous_namespace{runtime-forin.cc}::Enumerate().
MayHaveElements()
bool v8::internal::FastKeyAccumulator::MayHaveElements (Tagged< JSReceiver > receiver) [private]
Definition at line 661 of file keys.cc.
                                                                    {
  if (!IsJSObject(receiver)) return true;
  Tagged<JSObject> object = Cast<JSObject>(receiver);
  if (object->HasEnumerableElements()) return true;
  if (object->HasIndexedInterceptor()) return true;
  return false;
}
Referenced by Prepare().
operator=()
FastKeyAccumulator& v8::internal::FastKeyAccumulator::operator= (const FastKeyAccumulator &) [delete]
Prepare()
void v8::internal::FastKeyAccumulator::Prepare () [private]
Definition at line 343 of file keys.cc.
                                 {
  DisallowGarbageCollection no_gc;
  // Directly go for the fast path for OWN_ONLY keys.
  if (mode_ == KeyCollectionMode::kOwnOnly) return;
  // Fully walk the prototype chain and find the last prototype with keys.
  is_receiver_simple_enum_ = false;
  has_empty_prototype_ = true;
  only_own_has_simple_elements_ =
      !IsCustomElementsReceiverMap(receiver_->map());
  Tagged<JSReceiver> last_prototype;
  may_have_elements_ = MayHaveElements(*receiver_);
  for (PrototypeIterator iter(isolate_, *receiver_); !iter.IsAtEnd();
       iter.Advance()) {
    Tagged<JSReceiver> current = iter.GetCurrent<JSReceiver>();
    if (!may_have_elements_ || only_own_has_simple_elements_) {
      if (MayHaveElements(current)) {
        may_have_elements_ = true;
        only_own_has_simple_elements_ = false;
      }
    }
    bool has_no_properties = CheckAndInitializeEmptyEnumCache(current);
    if (has_no_properties) continue;
    last_prototype = current;
    has_empty_prototype_ = false;
  }
  // Check if we should try to create/use prototype info cache.
  try_prototype_info_cache_ = TryPrototypeInfoCache(receiver_);
  if (has_prototype_info_cache_) return;
  if (has_empty_prototype_) {
    is_receiver_simple_enum_ =
        receiver_->map()->EnumLength() != kInvalidEnumCacheSentinel &&
        !Cast<JSObject>(*receiver_)->HasEnumerableElements();
  } else if (!last_prototype.is_null()) {
    last_non_empty_prototype_ = direct_handle(last_prototype, isolate_);
  }
}
References v8::internal::anonymous_namespace{keys.cc}::CheckAndInitializeEmptyEnumCache(), v8::internal::direct_handle(), has_empty_prototype_, has_prototype_info_cache_, v8::internal::Tagged< HeapObject >::is_null(), is_receiver_simple_enum_, v8::internal::PrototypeIterator::IsAtEnd(), v8::internal::IsCustomElementsReceiverMap(), isolate_, v8::internal::kInvalidEnumCacheSentinel, v8::internal::kOwnOnly, last_non_empty_prototype_, may_have_elements_, MayHaveElements(), mode_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, only_own_has_simple_elements_, receiver_, try_prototype_info_cache_, and TryPrototypeInfoCache().
Referenced by FastKeyAccumulator().
TryPrototypeInfoCache()
bool v8::internal::FastKeyAccumulator::TryPrototypeInfoCache (DirectHandle< JSReceiver > receiver) [private]
Definition at line 669 of file keys.cc.
                                       {
  if (may_have_elements_ && !only_own_has_simple_elements_) return false;
  DirectHandle<JSObject> object = Cast<JSObject>(receiver);
  if (!object->HasFastProperties()) return false;
  if (object->HasNamedInterceptor()) return false;
  if (IsAccessCheckNeeded(*object) &&
      !isolate_->MayAccess(isolate_->native_context(), object)) {
    return false;
  }
  DisallowGarbageCollection no_gc;
  Tagged<HeapObject> prototype = receiver->map(isolate_)->prototype();
  if (prototype.is_null()) return false;
  Tagged<Map> maybe_proto_map = prototype->map(isolate_);
  if (!maybe_proto_map->is_prototype_map()) return false;
  Tagged<PrototypeInfo> prototype_info;
  if (!maybe_proto_map->TryGetPrototypeInfo(&prototype_info)) return false;
  first_prototype_ = direct_handle(Cast<JSReceiver>(prototype), isolate_);
  first_prototype_map_ = direct_handle(maybe_proto_map, isolate_);
  has_prototype_info_cache_ =
      maybe_proto_map->IsPrototypeValidityCellValid() &&
      IsFixedArray(prototype_info->prototype_chain_enum_cache());
  return true;
}
References v8::internal::direct_handle(), first_prototype_, first_prototype_map_, has_prototype_info_cache_, isolate_, may_have_elements_, v8::internal::Isolate::MayAccess(), v8::internal::Isolate::native_context(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, only_own_has_simple_elements_, and v8::internal::prototype.
Referenced by Prepare().
Member Data Documentation
filter_
PropertyFilter v8::internal::FastKeyAccumulator::filter_ [private]
Definition at line 235 of file keys.h.
Referenced by GetKeys(), GetKeysSlow(), and GetKeysWithPrototypeInfoCache().
first_prototype_
DirectHandle<JSReceiver> v8::internal::FastKeyAccumulator::first_prototype_ [private]
Definition at line 232 of file keys.h.
Referenced by GetKeysWithPrototypeInfoCache(), and TryPrototypeInfoCache().
first_prototype_map_
DirectHandle<Map> v8::internal::FastKeyAccumulator::first_prototype_map_ [private]
Definition at line 231 of file keys.h.
Referenced by GetKeysSlow(), GetKeysWithPrototypeInfoCache(), and TryPrototypeInfoCache().
has_empty_prototype_
bool v8::internal::FastKeyAccumulator::has_empty_prototype_ = false [private]
Definition at line 239 of file keys.h.
Referenced by GetKeysFast(), has_empty_prototype(), and Prepare().
has_prototype_info_cache_
bool v8::internal::FastKeyAccumulator::has_prototype_info_cache_ = false [private]
Definition at line 241 of file keys.h.
Referenced by GetKeysWithPrototypeInfoCache(), Prepare(), and TryPrototypeInfoCache().
is_for_in_
bool v8::internal::FastKeyAccumulator::is_for_in_ = false [private]
Definition at line 236 of file keys.h.
Referenced by GetKeysSlow(), GetKeysWithPrototypeInfoCache(), and GetOwnKeysWithUninitializedEnumLength().
is_receiver_simple_enum_
bool v8::internal::FastKeyAccumulator::is_receiver_simple_enum_ = false [private]
Definition at line 238 of file keys.h.
Referenced by GetKeysFast(), is_receiver_simple_enum(), and Prepare().
isolate_
Isolate* v8::internal::FastKeyAccumulator::isolate_ [private]
Definition at line 229 of file keys.h.
Referenced by GetKeys(), GetKeysFast(), GetKeysSlow(), GetKeysWithPrototypeInfoCache(), GetOwnKeysWithUninitializedEnumLength(), Prepare(), and TryPrototypeInfoCache().
last_non_empty_prototype_
DirectHandle<JSReceiver> v8::internal::FastKeyAccumulator::last_non_empty_prototype_ [private]
Definition at line 233 of file keys.h.
Referenced by GetKeysSlow(), GetKeysWithPrototypeInfoCache(), and Prepare().
may_have_elements_
bool v8::internal::FastKeyAccumulator::may_have_elements_ = true [private]
Definition at line 240 of file keys.h.
Referenced by GetKeysSlow(), GetKeysWithPrototypeInfoCache(), may_have_elements(), Prepare(), and TryPrototypeInfoCache().
mode_
KeyCollectionMode v8::internal::FastKeyAccumulator::mode_ [private]
Definition at line 234 of file keys.h.
Referenced by GetKeysFast(), GetKeysSlow(), GetKeysWithPrototypeInfoCache(), and Prepare().
only_own_has_simple_elements_
bool v8::internal::FastKeyAccumulator::only_own_has_simple_elements_ = false [private]
Definition at line 243 of file keys.h.
Referenced by Prepare(), and TryPrototypeInfoCache().
receiver_
DirectHandle<JSReceiver> v8::internal::FastKeyAccumulator::receiver_ [private]
Definition at line 230 of file keys.h.
Referenced by GetKeysFast(), GetKeysSlow(), GetKeysWithPrototypeInfoCache(), GetOwnKeysWithUninitializedEnumLength(), and Prepare().
skip_indices_
bool v8::internal::FastKeyAccumulator::skip_indices_ = false [private]
Definition at line 237 of file keys.h.
Referenced by GetKeysFast(), GetKeysSlow(), and GetKeysWithPrototypeInfoCache().
try_prototype_info_cache_
bool v8::internal::FastKeyAccumulator::try_prototype_info_cache_ = false [private]
Definition at line 242 of file keys.h.
Referenced by GetKeys(), GetKeysSlow(), GetKeysWithPrototypeInfoCache(), and Prepare().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/keys.h
/mnt/V8SourceCode/src/objects/keys.cc