v8::internal::BuiltinsConstantsTableBuilder Class Reference
#include <constants-table-builder.h>
Public Member Functions
BuiltinsConstantsTableBuilder (Isolate *isolate)
BuiltinsConstantsTableBuilder (const BuiltinsConstantsTableBuilder &)=delete
BuiltinsConstantsTableBuilder & operator= (const BuiltinsConstantsTableBuilder &)=delete
uint32_t AddObject (Handle< Object > object)
void PatchSelfReference (DirectHandle< Object > self_reference, Handle< InstructionStream > code_object)
void PatchBasicBlockCountersReference (Handle< ByteArray > counters)
void Finalize ()
Private Types
using ConstantsMap = IdentityMap< uint32_t, FreeStoreAllocationPolicy >
Private Attributes
Isolate * isolate_
ConstantsMap map_
base::Mutex mutex_
Detailed Description
Definition at line 24 of file constants-table-builder.h.
Member Typedef Documentation
ConstantsMap
using v8::internal::BuiltinsConstantsTableBuilder::ConstantsMap = IdentityMap<uint32_t, FreeStoreAllocationPolicy> [private]
Definition at line 55 of file constants-table-builder.h.
Constructor & Destructor Documentation
BuiltinsConstantsTableBuilder() [1/2]
v8::internal::BuiltinsConstantsTableBuilder::BuiltinsConstantsTableBuilder (Isolate * isolate) [explicit]
Definition at line 16 of file constants-table-builder.cc.
    : isolate_(isolate), map_(isolate->heap()) {
  // Ensure this is only called once per Isolate.
  DCHECK_EQ(ReadOnlyRoots(isolate_).empty_fixed_array(),
            isolate_->heap()->builtins_constants_table());
  // And that the initial value of the builtins constants table can be treated
  // as a constant, which means that codegen will load it using the root
  // register.
  DCHECK(RootsTable::IsImmortalImmovable(RootIndex::kEmptyFixedArray));
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::heap(), v8::internal::RootsTable::IsImmortalImmovable(), and isolate_.
BuiltinsConstantsTableBuilder() [2/2]
v8::internal::BuiltinsConstantsTableBuilder::BuiltinsConstantsTableBuilder (const BuiltinsConstantsTableBuilder &) [delete]
Member Function Documentation
AddObject()
uint32_t v8::internal::BuiltinsConstantsTableBuilder::AddObject (Handle< Object > object)
Definition at line 28 of file constants-table-builder.cc.
                                                                       {
#ifdef DEBUG
  // Roots must not be inserted into the constants table as they are already
  // accessibly from the root list.
  RootIndex root_list_index;
  DCHECK(!isolate_->roots_table().IsRootHandle(object, &root_list_index));
  DCHECK_IMPLIES(IsMap(*object),
                 !HeapLayout::InReadOnlySpace(Cast<HeapObject>(*object)));
  // Not yet finalized.
  DCHECK_EQ(ReadOnlyRoots(isolate_).empty_fixed_array(),
            isolate_->heap()->builtins_constants_table());
  // Must be generating embedded builtin code.
  DCHECK(isolate_->IsGeneratingEmbeddedBuiltins());
  // All code objects should be loaded through the root register or use
  // pc-relative addressing.
  DCHECK(!IsInstructionStream(*object));
#endif
  // This method is called concurrently from both the main thread and
  // compilation threads. Constant indices need to be reproducible during
  // builtin generation, so the main thread pre-adds all the constants. A lock
  // is still needed since the map data structure is still being concurrently
  // accessed.
  base::MutexGuard guard(&mutex_);
  if (ThreadId::Current() != isolate_->thread_id()) {
    auto find_result = map_.Find(object);
    DCHECK_NOT_NULL(find_result);
    return *find_result;
  } else {
    auto find_result = map_.FindOrInsert(object);
    if (!find_result.already_exists) {
      DCHECK(IsHeapObject(*object));
      *find_result.entry = map_.size() - 1;
    }
    return *find_result.entry;
  }
}
References v8::internal::ThreadId::Current(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::internal::IdentityMap< V, AllocationPolicy >::Find(), v8::internal::IdentityMap< V, AllocationPolicy >::FindOrInsert(), v8::internal::Isolate::heap(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::Isolate::IsGeneratingEmbeddedBuiltins(), v8::internal::IsHeapObject(), isolate_, v8::internal::RootsTable::IsRootHandle(), map_, mutex_, v8::internal::Isolate::roots_table(), v8::internal::IdentityMapBase::size(), and v8::internal::Isolate::thread_id().
Referenced by v8::internal::MacroAssemblerBase::IndirectLoadConstant().
Finalize()
void v8::internal::BuiltinsConstantsTableBuilder::Finalize ()
Definition at line 111 of file constants-table-builder.cc.
                                             {
  HandleScope handle_scope(isolate_);
  DCHECK_EQ(ReadOnlyRoots(isolate_).empty_fixed_array(),
            isolate_->heap()->builtins_constants_table());
  DCHECK(isolate_->IsGeneratingEmbeddedBuiltins());
  // An empty map means there's nothing to do.
  if (map_.empty()) return;
  DirectHandle<FixedArray> table =
      isolate_->factory()->NewFixedArray(map_.size(), AllocationType::kOld);
  Builtins* builtins = isolate_->builtins();
  ConstantsMap::IteratableScope it_scope(&map_);
  for (auto it = it_scope.begin(); it != it_scope.end(); ++it) {
    uint32_t index = *it.entry();
    Tagged<Object> value = it.key();
    if (IsCode(value) && Cast<Code>(value)->kind() == CodeKind::BUILTIN) {
      // Replace placeholder code objects with the real builtin.
      // See also: SetupIsolateDelegate::PopulateWithPlaceholders.
      // TODO(jgruber): Deduplicate placeholders and their corresponding
      // builtin.
      value = builtins->code(Cast<Code>(value)->builtin_id());
    }
    DCHECK(IsHeapObject(value));
    table->set(index, value);
  }
#ifdef DEBUG
  for (int i = 0; i < map_.size(); i++) {
    DCHECK(IsHeapObject(table->get(i)));
    DCHECK_NE(ReadOnlyRoots(isolate_).undefined_value(), table->get(i));
    DCHECK_NE(ReadOnlyRoots(isolate_).self_reference_marker(), table->get(i));
    DCHECK_NE(ReadOnlyRoots(isolate_).basic_block_counters_marker(),
              table->get(i));
  }
#endif
  isolate_->heap()->SetBuiltinsConstantsTable(*table);
}
References BUILTIN, v8::internal::Isolate::builtins(), v8::internal::Builtins::code(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::IdentityMapBase::empty(), v8::internal::Isolate::factory(), v8::internal::Isolate::heap(), v8::internal::index, v8::internal::Isolate::IsGeneratingEmbeddedBuiltins(), v8::internal::IsHeapObject(), isolate_, v8::internal::kOld, map_, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::Heap::SetBuiltinsConstantsTable(), v8::internal::IdentityMapBase::size(), and v8::internal::value.
Referenced by v8::internal::Isolate::Init().
operator=()
BuiltinsConstantsTableBuilder& v8::internal::BuiltinsConstantsTableBuilder::operator= (const BuiltinsConstantsTableBuilder &) [delete]
PatchBasicBlockCountersReference()
void v8::internal::BuiltinsConstantsTableBuilder::PatchBasicBlockCountersReference (Handle< ByteArray > counters)
Definition at line 100 of file constants-table-builder.cc.
                                {
  CheckPreconditionsForPatching(isolate_, counters);
  uint32_t key;
  if (map_.Delete(ReadOnlyRoots(isolate_).basic_block_counters_marker(),
                  &key)) {
    map_.Insert(counters, key);
  }
}
References v8::internal::anonymous_namespace{constants-table-builder.cc}::CheckPreconditionsForPatching(), v8::internal::IdentityMap< V, AllocationPolicy >::Delete(), v8::internal::IdentityMap< V, AllocationPolicy >::Insert(), isolate_, v8::internal::key, and map_.
PatchSelfReference()
void v8::internal::BuiltinsConstantsTableBuilder::PatchSelfReference (DirectHandle< Object > self_reference, Handle< InstructionStream > code_object)
Definition at line 87 of file constants-table-builder.cc.
                                           {
  CheckPreconditionsForPatching(isolate_, code_object);
  DCHECK_EQ(*self_reference, ReadOnlyRoots(isolate_).self_reference_marker());
  uint32_t key;
  if (map_.Delete(self_reference, &key)) {
    DCHECK(IsInstructionStream(*code_object));
    map_.Insert(code_object, key);
  }
}
References v8::internal::anonymous_namespace{constants-table-builder.cc}::CheckPreconditionsForPatching(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::IdentityMap< V, AllocationPolicy >::Delete(), v8::internal::IdentityMap< V, AllocationPolicy >::Insert(), isolate_, v8::internal::key, and map_.
Member Data Documentation
isolate_
Isolate* v8::internal::BuiltinsConstantsTableBuilder::isolate_ [private]
Definition at line 52 of file constants-table-builder.h.
Referenced by AddObject(), BuiltinsConstantsTableBuilder(), Finalize(), PatchBasicBlockCountersReference(), and PatchSelfReference().
map_
ConstantsMap v8::internal::BuiltinsConstantsTableBuilder::map_ [private]
Definition at line 56 of file constants-table-builder.h.
Referenced by AddObject(), Finalize(), PatchBasicBlockCountersReference(), and PatchSelfReference().
mutex_
base::Mutex v8::internal::BuiltinsConstantsTableBuilder::mutex_ [private]
Definition at line 60 of file constants-table-builder.h.
Referenced by AddObject().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/constants-table-builder.h
/mnt/V8SourceCode/src/builtins/constants-table-builder.cc