v8::internal::RegExpData Class Reference
#include <js-regexp.h>
Classes
class BodyDescriptor
Public Types
enum class Type : uint8_t { ATOM
, IRREGEXP
, EXPERIMENTAL
 }
Public Member Functions
Type type_tag () const
void set_type_tag (Type)
JSRegExp::Flags flags () const
void set_flags (JSRegExp::Flags flags)
int capture_count () const
V8_EXPORT_PRIVATE bool HasCompiledCode () const
OBJECT_CONSTRUCTORS (RegExpData, ExposedTrustedObject)
Static Public Member Functions
static constexpr bool TypeSupportsCaptures (Type t)
Additional Inherited Members
Detailed Description
Definition at line 158 of file js-regexp.h.
Member Enumeration Documentation
Type
enum v8::internal::RegExpData::Type : uint8_t [strong]
Enumerator
ATOM
IRREGEXP
EXPERIMENTAL
Definition at line 160 of file js-regexp.h.
                  : uint8_t {
    ATOM, // A simple string match.
    IRREGEXP, // Compiled with Irregexp (code or bytecode).
    EXPERIMENTAL, // Compiled to use the experimental linear time engine.
  };
Member Function Documentation
capture_count()
int v8::internal::RegExpData::capture_count () const [inline]
Definition at line 88 of file js-regexp-inl.h.
                                    {
  switch (type_tag()) {
    case Type::ATOM:
      return 0;
    case Type::EXPERIMENTAL:
    case Type::IRREGEXP:
      return Cast<IrRegExpData>(*this)->capture_count();
  }
}
References capture_count().
Referenced by capture_count().
flags()
JSRegExp::Flags v8::internal::RegExpData::flags () const [inline]
Definition at line 77 of file js-regexp-inl.h.
                                      {
  Tagged<Smi> value = TaggedField<Smi, kFlagsOffset>::load(*this);
  return JSRegExp::Flags(value.value());
}
References v8::internal::Flags(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::load(), and v8::internal::value.
Referenced by set_flags().
HasCompiledCode()
bool v8::internal::RegExpData::HasCompiledCode () const
Definition at line 376 of file js-regexp.cc.
                                       {
  if (type_tag() != Type::IRREGEXP) return false;
  Tagged<IrRegExpData> re_data = Cast<IrRegExpData>(*this);
  return re_data->has_latin1_code() || re_data->has_uc16_code();
}
References IRREGEXP, and type_tag().
Referenced by v8::internal::IrRegExpData::DiscardCompiledCodeForSerialization().
OBJECT_CONSTRUCTORS()
v8::internal::RegExpData::OBJECT_CONSTRUCTORS (RegExpData , ExposedTrustedObject)
set_flags()
void v8::internal::RegExpData::set_flags (JSRegExp::Flags flags) [inline]
Definition at line 82 of file js-regexp-inl.h.
                                              {
  TaggedField<Smi, kFlagsOffset>::store(*this, Smi::FromInt(flags));
}
References flags(), v8::internal::Smi::FromInt(), and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::store().
set_type_tag()
void v8::internal::RegExpData::set_type_tag (Type type) [inline]
Definition at line 70 of file js-regexp-inl.h.
                                       {
  TaggedField<Smi, kTypeTagOffset>::store(
      *this, Smi::FromInt(static_cast<uint8_t>(type)));
}
References v8::internal::Smi::FromInt(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::store(), and v8::internal::tracing::type.
type_tag()
RegExpData::Type v8::internal::RegExpData::type_tag () const [inline]
Definition at line 65 of file js-regexp-inl.h.
                                          {
  Tagged<Smi> value = TaggedField<Smi, kTypeTagOffset>::load(*this);
  return Type(value.value());
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::load(), and v8::internal::value.
Referenced by v8::internal::IrRegExpData::CanTierUp(), and HasCompiledCode().
TypeSupportsCaptures()
static constexpr bool v8::internal::RegExpData::TypeSupportsCaptures (Type t) [inline], [static], [constexpr]
Definition at line 178 of file js-regexp.h.
                                                     {
    return t == Type::IRREGEXP || t == Type::EXPERIMENTAL;
  }
References EXPERIMENTAL, and IRREGEXP.
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::MatchInfoBackedMatch().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-regexp.h
/mnt/V8SourceCode/src/objects/js-regexp-inl.h
/mnt/V8SourceCode/src/objects/js-regexp.cc