v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope Class Reference
Public Member Functions
ThrowingScope (GraphBuildingNodeProcessor *builder, maglev::NodeBase *throwing_node)
~ThrowingScope ()
Private Member Functions
GraphBuildingNodeProcessor::AssemblerT & Asm ()
Private Attributes
GraphBuildingNodeProcessor & builder_
const maglev::BasicBlock * catch_block_ = nullptr
Detailed Description
Definition at line 5840 of file turbolev-graph-builder.cc.
Constructor & Destructor Documentation
ThrowingScope()
v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope (GraphBuildingNodeProcessor * builder, maglev::NodeBase * throwing_node) [inline]
Definition at line 5857 of file turbolev-graph-builder.cc.
         :
    ThrowingScope(GraphBuildingNodeProcessor* builder,
                  maglev::NodeBase* throwing_node)
        : builder_(*builder) {
      DCHECK_EQ(__ current_catch_block(), nullptr);
      if (!throwing_node->properties().can_throw()) return;
      const maglev::ExceptionHandlerInfo* handler_info =
          throwing_node->exception_handler_info();
      if (!handler_info->HasExceptionHandler() ||
          handler_info->ShouldLazyDeopt()) {
        return;
      }
      catch_block_ = handler_info->catch_block();
      __ set_current_catch_block(builder_.Map(catch_block_));
      // We now need to prepare recording the inputs for the exception phis of
      // the catch handler.
      if (!catch_block_->has_phi()) {
        // Catch handler doesn't have any Phis, no need to do anything else.
        return;
      }
      const maglev::InterpretedDeoptFrame& interpreted_frame =
          throwing_node->lazy_deopt_info()->GetFrameForExceptionHandler(
              handler_info);
      const maglev::CompactInterpreterFrameState* compact_frame =
          interpreted_frame.frame_state();
      const maglev::MaglevCompilationUnit& maglev_unit =
          interpreted_frame.unit();
      builder_.IterCatchHandlerPhis(
          catch_block_, [this, compact_frame, maglev_unit](
                            interpreter::Register owner, Variable var) {
            DCHECK_NE(owner, interpreter::Register::virtual_accumulator());
            const maglev::ValueNode* maglev_value =
                compact_frame->GetValueOf(owner, maglev_unit);
            DCHECK_NOT_NULL(maglev_value);
            while (maglev_value->Is<maglev::Identity>()) {
              maglev_value = maglev_value->input(0).node();
            }
            if (const maglev::VirtualObject* vobj =
                    maglev_value->TryCast<maglev::VirtualObject>()) {
              maglev_value = vobj->allocation();
            }
            DCHECK(!maglev_value->Is<maglev::Identity>());
            DCHECK(!maglev_value->Is<maglev::VirtualObject>());
            V<Any> ts_value = builder_.Map(maglev_value);
            __ SetVariable(var, ts_value);
            builder_.RecordRepresentation(ts_value,
References __, v8::internal::maglev::VirtualObject::allocation(), v8::internal::maglev::OpProperties::can_throw(), v8::internal::maglev::ExceptionHandlerInfo::catch_block(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, DCHECK_NOT_NULL, v8::internal::maglev::NodeBase::exception_handler_info(), v8::internal::maglev::InterpretedDeoptFrame::frame_state(), v8::internal::maglev::LazyDeoptInfo::GetFrameForExceptionHandler(), v8::internal::maglev::CompactInterpreterFrameState::GetValueOf(), v8::internal::maglev::ExceptionHandlerInfo::HasExceptionHandler(), v8::internal::maglev::NodeBase::input(), v8::internal::maglev::NodeBase::Is(), v8::internal::maglev::NodeBase::lazy_deopt_info(), v8::internal::maglev::Input::node(), v8::internal::maglev::NodeBase::properties(), v8::internal::maglev::ExceptionHandlerInfo::ShouldLazyDeopt(), v8::internal::maglev::NodeBase::TryCast(), v8::internal::maglev::InterpretedDeoptFrame::unit(), v8::internal::maglev::ValueNode::value_representation(), and v8::internal::interpreter::Register::virtual_accumulator().
 ThrowingScope()
v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::~ThrowingScope () [inline]
Definition at line 5916 of file turbolev-graph-builder.cc.
                     {
      // Resetting the catch handler. It is always set on a case-by-case basis
      // before emitting a throwing node, so there is no need to "reset the
      // previous catch handler" or something like that, since there is no
      // previous handler (there is a DCHECK in the ThrowingScope constructor
      // checking that the current_catch_block is indeed nullptr when the scope
      // is created).
      __ set_current_catch_block(nullptr);
      if (catch_block_ == nullptr) return;
      if (!catch_block_->has_phi()) return;
      // We clear the Variables that we've set when initializing the scope, in
      // order to avoid creating Phis for such Variables. These are really only
      // meant to be used when translating the Phis in the catch handler, and
      // when the scope is destroyed, we shouldn't be in the Catch handler yet.
      builder_.IterCatchHandlerPhis(
          catch_block_, [this](interpreter::Register, Variable var) {
Member Function Documentation
Asm()
GraphBuildingNodeProcessor::AssemblerT& v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::Asm () [inline], [private]
Definition at line 5939 of file turbolev-graph-builder.cc.
:
    GraphBuildingNodeProcessor::AssemblerT& Asm() { return builder_.Asm(); }
Member Data Documentation
builder_
GraphBuildingNodeProcessor& v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::builder_ [private]
Definition at line 5940 of file turbolev-graph-builder.cc.
catch_block_
const maglev::BasicBlock* v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::catch_block_ = nullptr [private]
Definition at line 5941 of file turbolev-graph-builder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/turbolev-graph-builder.cc