v8::internal::CompilationCacheScriptLookupResult Class Reference
#include <compilation-cache-table.h>
Public Types
using RawObjects = std::pair< Tagged< Script >, Tagged< SharedFunctionInfo > >
Public Member Functions
MaybeHandle< Script > script () const
MaybeHandle< SharedFunctionInfo > toplevel_sfi () const
IsCompiledScope is_compiled_scope () const
RawObjects GetRawObjects () const
Static Public Member Functions
static CompilationCacheScriptLookupResult FromRawObjects (RawObjects raw, Isolate *isolate)
Private Attributes
MaybeHandle< Script > script_
MaybeHandle< SharedFunctionInfo > toplevel_sfi_
IsCompiledScope is_compiled_scope_
Detailed Description
Definition at line 92 of file compilation-cache-table.h.
Member Typedef Documentation
RawObjects
using v8::internal::CompilationCacheScriptLookupResult::RawObjects = std::pair<Tagged<Script>, Tagged<SharedFunctionInfo> >
Definition at line 98 of file compilation-cache-table.h.
Member Function Documentation
FromRawObjects()
CompilationCacheScriptLookupResult v8::internal::CompilationCacheScriptLookupResult::FromRawObjects (CompilationCacheScriptLookupResult::RawObjects raw, Isolate * isolate) [static]
Definition at line 378 of file compilation-cache-table.cc.
                                                                        {
  CompilationCacheScriptLookupResult result;
  if (!raw.first.is_null()) {
    result.script_ = handle(raw.first, isolate);
  }
  if (!raw.second.is_null()) {
    result.is_compiled_scope_ = raw.second->is_compiled_scope(isolate);
    if (result.is_compiled_scope_.is_compiled()) {
      result.toplevel_sfi_ = handle(raw.second, isolate);
    }
  }
  return result;
}
References v8::internal::handle(), and v8::base::internal::result.
Referenced by v8::internal::CompilationCacheTable::LookupScript().
GetRawObjects()
CompilationCacheScriptLookupResult::RawObjects v8::internal::CompilationCacheScriptLookupResult::GetRawObjects () const
Definition at line 365 of file compilation-cache-table.cc.
                                                        {
  RawObjects result;
  if (Handle<Script> script; script_.ToHandle(&script)) {
    result.first = *script;
  }
  if (Handle<SharedFunctionInfo> toplevel_sfi;
      toplevel_sfi_.ToHandle(&toplevel_sfi)) {
    result.second = *toplevel_sfi;
  }
  return result;
}
References v8::base::internal::result, script(), script_, toplevel_sfi(), and toplevel_sfi_.
is_compiled_scope()
IsCompiledScope v8::internal::CompilationCacheScriptLookupResult::is_compiled_scope () const [inline]
Definition at line 96 of file compilation-cache-table.h.
{ return is_compiled_scope_; }
References is_compiled_scope_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript(), and v8::internal::BackgroundMergeTask::SetUpOnMainThread().
script()
MaybeHandle<Script> v8::internal::CompilationCacheScriptLookupResult::script () const [inline]
Definition at line 94 of file compilation-cache-table.h.
{ return script_; }
References script_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::anonymous_namespace{compiler.cc}::CategorizeLookupResult(), GetRawObjects(), v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript(), and v8::internal::BackgroundMergeTask::SetUpOnMainThread().
toplevel_sfi()
MaybeHandle<SharedFunctionInfo> v8::internal::CompilationCacheScriptLookupResult::toplevel_sfi () const [inline]
Definition at line 95 of file compilation-cache-table.h.
{ return toplevel_sfi_; }
References toplevel_sfi_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::anonymous_namespace{compiler.cc}::CategorizeLookupResult(), GetRawObjects(), v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript(), v8::internal::Compiler::GetWrappedFunction(), and v8::internal::BackgroundMergeTask::SetUpOnMainThread().
Member Data Documentation
is_compiled_scope_
IsCompiledScope v8::internal::CompilationCacheScriptLookupResult::is_compiled_scope_ [private]
Definition at line 108 of file compilation-cache-table.h.
Referenced by is_compiled_scope().
script_
MaybeHandle<Script> v8::internal::CompilationCacheScriptLookupResult::script_ [private]
Definition at line 106 of file compilation-cache-table.h.
Referenced by GetRawObjects(), and script().
toplevel_sfi_
MaybeHandle<SharedFunctionInfo> v8::internal::CompilationCacheScriptLookupResult::toplevel_sfi_ [private]
Definition at line 107 of file compilation-cache-table.h.
Referenced by GetRawObjects(), and toplevel_sfi().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/compilation-cache-table.h
/mnt/V8SourceCode/src/objects/compilation-cache-table.cc