v8::internal::SlotDescriptor Class Reference
#include <assembler.h>
Public Member Functions
bool contains_direct_pointer () const
bool contains_indirect_pointer () const
IndirectPointerTag indirect_pointer_tag () const
Static Public Member Functions
static SlotDescriptor ForDirectPointerSlot ()
static SlotDescriptor ForIndirectPointerSlot (IndirectPointerTag tag)
static SlotDescriptor ForTrustedPointerSlot (IndirectPointerTag tag)
static SlotDescriptor ForCodePointerSlot ()
Private Member Functions
SlotDescriptor (IndirectPointerTag tag)
Private Attributes
IndirectPointerTag indirect_pointer_tag_
Detailed Description
Definition at line 280 of file assembler.h.
Constructor & Destructor Documentation
SlotDescriptor()
v8::internal::SlotDescriptor::SlotDescriptor (IndirectPointerTag tag) [inline], [explicit], [private]
Definition at line 316 of file assembler.h.
      : indirect_pointer_tag_(tag) {}
Referenced by ForDirectPointerSlot(), and ForIndirectPointerSlot().
Member Function Documentation
contains_direct_pointer()
bool v8::internal::SlotDescriptor::contains_direct_pointer () const [inline]
Definition at line 282 of file assembler.h.
                                       {
    return indirect_pointer_tag_ == kIndirectPointerNullTag;
  }
References indirect_pointer_tag_, and v8::internal::kIndirectPointerNullTag.
Referenced by v8::internal::MacroAssembler::RecordWrite().
contains_indirect_pointer()
bool v8::internal::SlotDescriptor::contains_indirect_pointer () const [inline]
Definition at line 286 of file assembler.h.
                                         {
    return indirect_pointer_tag_ != kIndirectPointerNullTag;
  }
References indirect_pointer_tag_, and v8::internal::kIndirectPointerNullTag.
Referenced by indirect_pointer_tag(), and v8::internal::MacroAssembler::RecordWrite().
ForCodePointerSlot()
static SlotDescriptor v8::internal::SlotDescriptor::ForCodePointerSlot () [inline], [static]
Definition at line 311 of file assembler.h.
                                             {
    return ForTrustedPointerSlot(kCodeIndirectPointerTag);
  }
References ForTrustedPointerSlot().
Referenced by v8::internal::MacroAssembler::ReplaceClosureCodeWithOptimizedCode().
ForDirectPointerSlot()
static SlotDescriptor v8::internal::SlotDescriptor::ForDirectPointerSlot () [inline], [static]
Definition at line 295 of file assembler.h.
                                               {
    return SlotDescriptor(kIndirectPointerNullTag);
  }
References v8::internal::kIndirectPointerNullTag, and SlotDescriptor().
Referenced by ForTrustedPointerSlot().
ForIndirectPointerSlot()
static SlotDescriptor v8::internal::SlotDescriptor::ForIndirectPointerSlot (IndirectPointerTag tag) [inline], [static]
Definition at line 299 of file assembler.h.
                                                                       {
    return SlotDescriptor(tag);
  }
References SlotDescriptor().
Referenced by ForTrustedPointerSlot().
ForTrustedPointerSlot()
static SlotDescriptor v8::internal::SlotDescriptor::ForTrustedPointerSlot (IndirectPointerTag tag) [inline], [static]
Definition at line 303 of file assembler.h.
                                                                      {
#ifdef V8_ENABLE_SANDBOX
    return ForIndirectPointerSlot(tag);
#else
    return ForDirectPointerSlot();
#endif
  }
References ForDirectPointerSlot(), and ForIndirectPointerSlot().
Referenced by ForCodePointerSlot().
indirect_pointer_tag()
IndirectPointerTag v8::internal::SlotDescriptor::indirect_pointer_tag () const [inline]
Definition at line 290 of file assembler.h.
                                                  {
    DCHECK(contains_indirect_pointer());
    return indirect_pointer_tag_;
  }
References contains_indirect_pointer(), v8::internal::DCHECK(), and indirect_pointer_tag_.
Referenced by v8::internal::MacroAssembler::RecordWrite().
Member Data Documentation
indirect_pointer_tag_
IndirectPointerTag v8::internal::SlotDescriptor::indirect_pointer_tag_ [private]
Definition at line 320 of file assembler.h.
Referenced by contains_direct_pointer(), contains_indirect_pointer(), and indirect_pointer_tag().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/assembler.h