v8::internal::compiler::NodeProperties Class Reference
#include <node-properties.h>
Public Types
enum InferMapsResult { kNoMaps
, kReliableMaps
, kUnreliableMaps
 }
Static Public Member Functions
static int FirstValueIndex (const Node *node)
static int FirstContextIndex (Node *node)
static int FirstFrameStateIndex (Node *node)
static int FirstEffectIndex (Node *node)
static int FirstControlIndex (Node *node)
static int PastValueIndex (Node *node)
static int PastContextIndex (Node *node)
static int PastFrameStateIndex (Node *node)
static int PastEffectIndex (Node *node)
static int PastControlIndex (Node *node)
static Node * GetValueInput (Node *node, int index)
static const Node * GetValueInput (const Node *node, int index)
static Node * GetContextInput (Node *node)
static Node * GetFrameStateInput (Node *node)
static Node * GetEffectInput (Node *node, int index=0)
static Node * GetControlInput (Node *node, int index=0)
static bool IsValueEdge (Edge edge)
static bool IsContextEdge (Edge edge)
static bool IsFrameStateEdge (Edge edge)
static bool IsEffectEdge (Edge edge)
static bool IsControlEdge (Edge edge)
static bool IsCommon (Node *node)
static bool IsControl (Node *node)
static bool IsConstant (Node *node)
static bool IsPhi (Node *node)
static bool IsExceptionalCall (Node *node, Node **out_exception=nullptr)
static Node * FindSuccessfulControlProjection (Node *node)
static bool IsValueIdentity (Node *node, Node **out_value)
static void ReplaceValueInput (Node *node, Node *value, int index)
static void ReplaceContextInput (Node *node, Node *context)
static void ReplaceControlInput (Node *node, Node *control, int index=0)
static void ReplaceEffectInput (Node *node, Node *effect, int index=0)
static void ReplaceFrameStateInput (Node *node, Node *frame_state)
static void RemoveNonValueInputs (Node *node)
static void RemoveValueInputs (Node *node)
static void ReplaceValueInputs (Node *node, Node *value)
static void MergeControlToEnd (TFGraph *graph, CommonOperatorBuilder *common, Node *node)
static void RemoveControlFromEnd (TFGraph *graph, CommonOperatorBuilder *common, Node *node)
static void ReplaceUses (Node *node, Node *value, Node *effect=nullptr, Node *success=nullptr, Node *exception=nullptr)
static void ChangeOp (Node *node, const Operator *new_op)
static void ChangeOpUnchecked (Node *node, const Operator *new_op)
static Node * FindFrameStateBefore (Node *node, Node *unreachable_sentinel)
static Node * FindProjection (Node *node, size_t projection_index)
static void CollectValueProjections (Node *node, Node **proj, size_t count)
static void CollectControlProjections (Node *node, Node **proj, size_t count)
static MachineRepresentation GetProjectionType (Node const *projection)
static bool IsSame (Node *a, Node *b)
static bool Equals (Node *a, Node *b)
static size_t HashCode (Node *node)
static InferMapsResult InferMapsUnsafe (JSHeapBroker *broker, Node *receiver, Effect effect, ZoneRefSet< Map > *maps_out)
static OptionalMapRef GetJSCreateMap (JSHeapBroker *broker, Node *receiver)
static bool NoObservableSideEffectBetween (Node *effect, Node *dominator)
static bool CanBePrimitive (JSHeapBroker *broker, Node *receiver, Effect effect)
static bool CanBeNullOrUndefined (JSHeapBroker *broker, Node *receiver, Effect effect)
static Node * GetOuterContext (Node *node, size_t *depth)
static bool IsTyped (const Node *node)
static Type GetType (const Node *node)
static Type GetTypeOrAny (const Node *node)
static void SetType (Node *node, Type type)
static void RemoveType (Node *node)
static bool AllValueInputsAreTyped (Node *node)
Static Private Member Functions
static bool IsInputRange (Edge edge, int first, int count)
Detailed Description
Definition at line 24 of file node-properties.h.
Member Enumeration Documentation
InferMapsResult
enum v8::internal::compiler::NodeProperties::InferMapsResult
Enumerator
kNoMaps
kReliableMaps
kUnreliableMaps
Definition at line 219 of file node-properties.h.
                       {
    kNoMaps, // No maps inferred.
    kReliableMaps, // Maps can be trusted.
    kUnreliableMaps // Maps might have changed (side-effect).
  };
Member Function Documentation
AllValueInputsAreTyped()
bool v8::internal::compiler::NodeProperties::AllValueInputsAreTyped (Node * node) [static]
Definition at line 684 of file node-properties.cc.
                                                      {
  int input_count = node->op()->ValueInputCount();
  for (int index = 0; index < input_count; ++index) {
    if (!IsTyped(GetValueInput(node, index))) return false;
  }
  return true;
}
References GetValueInput(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), IsTyped(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by v8::internal::compiler::Typer::Decorator::Decorate().
CanBeNullOrUndefined()
bool v8::internal::compiler::NodeProperties::CanBeNullOrUndefined (JSHeapBroker * broker, Node * receiver, Effect effect) [static]
Definition at line 637 of file node-properties.cc.
                                                         {
  if (CanBePrimitive(broker, receiver, effect)) {
    switch (receiver->opcode()) {
      case IrOpcode::kCheckInternalizedString:
      case IrOpcode::kCheckNumber:
      case IrOpcode::kCheckNumberFitsInt32:
      case IrOpcode::kCheckSmi:
      case IrOpcode::kCheckString:
      case IrOpcode::kCheckSymbol:
      case IrOpcode::kJSToLength:
      case IrOpcode::kJSToName:
      case IrOpcode::kJSToNumber:
      case IrOpcode::kJSToNumberConvertBigInt:
      case IrOpcode::kJSToNumeric:
      case IrOpcode::kJSToString:
      case IrOpcode::kToBoolean:
        return false;
      case IrOpcode::kHeapConstant: {
        HeapObjectRef value = HeapObjectMatcher(receiver).Ref(broker);
        OddballType type = value.map(broker).oddball_type(broker);
        return type == OddballType::kNull || type == OddballType::kUndefined;
      }
      default:
        return true;
    }
  }
  return false;
}
References broker(), CanBePrimitive(), v8::internal::compiler::kNull, v8::internal::compiler::kUndefined, v8::internal::compiler::Node::opcode(), v8::internal::tracing::type, and v8::internal::value.
Referenced by v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), and v8::internal::compiler::JSCallReducer::ReduceObjectConstructor().
CanBePrimitive()
bool v8::internal::compiler::NodeProperties::CanBePrimitive (JSHeapBroker * broker, Node * receiver, Effect effect) [static]
Definition at line 612 of file node-properties.cc.
                                                   {
  switch (receiver->opcode()) {
#define CASE(Opcode) case IrOpcode::k##Opcode:
    JS_CONSTRUCT_OP_LIST(CASE)
    JS_CREATE_OP_LIST(CASE)
#undef CASE
    case IrOpcode::kCheckReceiver:
    case IrOpcode::kConvertReceiver:
    case IrOpcode::kJSGetSuperConstructor:
    case IrOpcode::kJSToObject:
      return false;
    case IrOpcode::kHeapConstant: {
      HeapObjectRef value = HeapObjectMatcher(receiver).Ref(broker);
      return value.map(broker).IsPrimitiveMap();
    }
    default: {
      MapInference inference(broker, receiver, effect);
      return !inference.HaveMaps() ||
             !inference.AllOfInstanceTypesAreJSReceiver();
    }
  }
}
References v8::internal::compiler::MapInference::AllOfInstanceTypesAreJSReceiver(), broker(), CASE, v8::internal::compiler::MapInference::HaveMaps(), JS_CONSTRUCT_OP_LIST, JS_CREATE_OP_LIST, v8::internal::compiler::Node::opcode(), and v8::internal::value.
Referenced by CanBeNullOrUndefined(), v8::internal::compiler::JSInliner::ReduceJSCall(), and v8::internal::compiler::JSCallReducer::ReduceObjectConstructor().
ChangeOp()
void v8::internal::compiler::NodeProperties::ChangeOp (Node * node, const Operator * new_op) [static]
Definition at line 203 of file node-properties.cc.
                                                                {
  node->set_op(new_op);
  Verifier::VerifyNode(node);
}
References v8::internal::compiler::Node::set_op(), and v8::internal::compiler::Verifier::VerifyNode().
Referenced by v8::internal::compiler::RawMachineAssembler::AppendPhiInput(), v8::internal::compiler::JSIntrinsicLowering::Change(), v8::internal::compiler::SimplifiedOperatorReducer::Change(), v8::internal::compiler::CommonOperatorReducer::Change(), v8::internal::compiler::RepresentationSelector::ChangeOp(), v8::internal::compiler::SimplifiedLowering::ChangeOp(), v8::internal::compiler::LoopVariableOptimizer::ChangeToInductionVariablePhis(), v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::NodeHashCache::Constructor::Constructor(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::RawMachineAssembler::MakePhiBinary(), v8::internal::compiler::RawMachineAssembler::MarkControlDeferred(), v8::internal::compiler::GraphAssembler::MergeState(), v8::internal::compiler::NodeHashCache::Constructor::MutableNode(), v8::internal::compiler::LoopPeeler::Peel(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::MachineOperatorReducer::Reduce(), v8::internal::compiler::PairLoadStoreReducer::Reduce(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferIsView(), v8::internal::compiler::JSCallReducer::ReduceArrayConstructor(), v8::internal::compiler::JSCallReducer::ReduceArrayIsArray(), v8::internal::compiler::JSCallReducer::ReduceArrayIterator(), v8::internal::compiler::WasmGCOperatorReducer::ReduceAssertNotNull(), v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncFunctionEnter(), v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncFunctionReject(), v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncFunctionResolve(), v8::internal::compiler::JSCallReducer::ReduceBigIntConstructor(), v8::internal::compiler::CommonOperatorReducer::ReduceBranch(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::compiler::JSIntrinsicLowering::ReduceCall(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::TypedOptimization::ReduceCheckBounds(), v8::internal::compiler::JSIntrinsicLowering::ReduceCopyDataPropertiesWithExcludedPropertiesOnStack(), v8::internal::compiler::CommonOperatorReducer::ReduceDeoptimizeConditional(), v8::internal::compiler::JSIntrinsicLowering::ReduceDeoptimizeNow(), v8::internal::compiler::DeadCodeElimination::ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceEagerDeoptimize(), v8::internal::compiler::DeadCodeElimination::ReduceEnd(), v8::internal::compiler::MachineOperatorReducer::ReduceFloat64Compare(), v8::internal::compiler::JSCallReducer::ReduceForInsufficientFeedback(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeHasInstance(), v8::internal::compiler::JSIntrinsicLowering::ReduceGetImportMetaObject(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Add(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt32Sub(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Mul(), v8::internal::compiler::MachineOperatorReducer::ReduceInt64Sub(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSBitwiseNot(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs(), v8::internal::compiler::JSTypedLowering::ReduceJSDecrement(), v8::internal::compiler::JSTypedLowering::ReduceJSEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreInputOrDebugPos(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSTypedLowering::ReduceJSIncrement(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadMessage(), v8::internal::compiler::JSTypedLowering::ReduceJSNegate(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSTypedLowering::ReduceJSResolvePromise(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreMessage(), v8::internal::compiler::JSTypedLowering::ReduceJSToBigIntConvertNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumeric(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::MemoryLowering::ReduceLoadBoundedSize(), v8::internal::compiler::MemoryLowering::ReduceLoadElement(), v8::internal::compiler::MemoryLowering::ReduceLoadExternalPointerField(), v8::internal::compiler::MemoryLowering::ReduceLoadField(), v8::internal::compiler::MemoryLowering::ReduceLoadFromObject(), v8::internal::compiler::MemoryLowering::ReduceLoadMap(), v8::internal::compiler::CommonOperatorReducer::ReduceMerge(), v8::internal::compiler::JSCallReducer::ReduceNumberConstructor(), v8::internal::compiler::JSCallReducer::ReduceNumberParseInt(), v8::internal::compiler::JSCallReducer::ReduceObjectConstructor(), v8::internal::compiler::JSCallReducer::ReduceObjectCreate(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeIsPrototypeOf(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::JSCallReducer::ReducePromiseResolveTrampoline(), v8::internal::compiler::TypedOptimization::ReduceReferenceEqual(), v8::internal::compiler::JSCallReducer::ReduceReflectApply(), v8::internal::compiler::JSCallReducer::ReduceReflectConstruct(), v8::internal::compiler::JSCallReducer::ReduceRegExpPrototypeTest(), v8::internal::compiler::TypedOptimization::ReduceSameValue(), v8::internal::compiler::TypedOptimization::ReduceSelect(), v8::internal::compiler::MemoryLowering::ReduceStore(), v8::internal::compiler::MemoryLowering::ReduceStoreElement(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::compiler::MemoryLowering::ReduceStoreToObject(), v8::internal::compiler::JSCallReducer::ReduceStringConstructor(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::TypedOptimization::ReduceToBoolean(), v8::internal::compiler::JSIntrinsicLowering::ReduceToLength(), v8::internal::compiler::JSIntrinsicLowering::ReduceToObject(), v8::internal::compiler::JSIntrinsicLowering::ReduceToString(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint32Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Div(), v8::internal::compiler::MachineOperatorReducer::ReduceUint64Mod(), v8::internal::compiler::MachineOperatorReducer::ReduceUintNLessThanOrEqual(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmStructOperation(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32And(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Sar(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Equal(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Shl(), v8::internal::compiler::MachineOperatorReducer::ReduceWordNAnd(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::MachineOperatorReducer::SimplifyBranch(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContextNoCell(), v8::internal::compiler::MachineOperatorReducer::SwapBranches(), v8::internal::compiler::DeadCodeElimination::TrimMergeOrPhi(), v8::internal::compiler::MachineOperatorReducer::TryMatchWord32Ror(), v8::internal::compiler::UnrollLoop(), and v8::internal::compiler::MemoryOptimizer::VisitAllocateRaw().
ChangeOpUnchecked()
void v8::internal::compiler::NodeProperties::ChangeOpUnchecked (Node * node, const Operator * new_op) [static]
Definition at line 209 of file node-properties.cc.
                                                                         {
  node->set_op(new_op);
}
References v8::internal::compiler::Node::set_op().
CollectControlProjections()
void v8::internal::compiler::NodeProperties::CollectControlProjections (Node * node, Node ** proj, size_t count) [static]
Definition at line 260 of file node-properties.cc.
                                                                        {
#ifdef DEBUG
  DCHECK_LE(static_cast<int>(projection_count), node->UseCount());
  std::memset(projections, 0, sizeof(*projections) * projection_count);
#endif
  size_t if_value_index = 0;
  for (Edge const edge : node->use_edges()) {
    if (!IsControlEdge(edge)) continue;
    Node* use = edge.from();
    size_t index;
    switch (use->opcode()) {
      case IrOpcode::kIfTrue:
        DCHECK_EQ(IrOpcode::kBranch, node->opcode());
        index = 0;
        break;
      case IrOpcode::kIfFalse:
        DCHECK_EQ(IrOpcode::kBranch, node->opcode());
        index = 1;
        break;
      case IrOpcode::kIfSuccess:
        DCHECK(!node->op()->HasProperty(Operator::kNoThrow));
        index = 0;
        break;
      case IrOpcode::kIfException:
        DCHECK(!node->op()->HasProperty(Operator::kNoThrow));
        index = 1;
        break;
      case IrOpcode::kIfValue:
        DCHECK_EQ(IrOpcode::kSwitch, node->opcode());
        index = if_value_index++;
        break;
      case IrOpcode::kIfDefault:
        DCHECK_EQ(IrOpcode::kSwitch, node->opcode());
        index = projection_count - 1;
        break;
      default:
        continue;
    }
    DCHECK_LT(if_value_index, projection_count);
    DCHECK_LT(index, projection_count);
    DCHECK_NULL(projections[index]);
    projections[index] = use;
  }
#ifdef DEBUG
  for (size_t index = 0; index < projection_count; ++index) {
    DCHECK_NOT_NULL(projections[index]);
  }
#endif
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_LT, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::compiler::Operator::HasProperty(), v8::internal::index, IsControlEdge(), v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::Operator::kNoThrow, v8::internal::wasm::kSwitch, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), use(), v8::internal::compiler::Node::use_edges(), and v8::internal::compiler::Node::UseCount().
Referenced by v8::internal::compiler::CFGBuilder::BuildBlocksForSuccessors(), v8::internal::compiler::CFGBuilder::CollectSuccessorBlocks(), v8::internal::compiler::DeadCodeElimination::ReduceBranchOrSwitch(), v8::internal::compiler::CommonOperatorReducer::ReduceSwitch(), and v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition().
CollectValueProjections()
void v8::internal::compiler::NodeProperties::CollectValueProjections (Node * node, Node ** proj, size_t count) [static]
Definition at line 243 of file node-properties.cc.
                                                                      {
#ifdef DEBUG
  for (size_t index = 0; index < projection_count; ++index) {
    DCHECK_NULL(projections[index]);
  }
#endif
  for (Edge const edge : node->use_edges()) {
    if (!IsValueEdge(edge)) continue;
    Node* use = edge.from();
    DCHECK_EQ(IrOpcode::kProjection, use->opcode());
    projections[ProjectionIndexOf(use->op())] = use;
  }
}
References DCHECK_EQ, DCHECK_NULL, v8::internal::index, IsValueEdge(), v8::internal::compiler::ProjectionIndexOf(), use(), and v8::internal::compiler::Node::use_edges().
Equals()
bool v8::internal::compiler::NodeProperties::Equals (Node * a, Node * b) [static]
Definition at line 709 of file node-properties.cc.
                                            {
  DCHECK_NOT_NULL(a);
  DCHECK_NOT_NULL(b);
  DCHECK_NOT_NULL(a->op());
  DCHECK_NOT_NULL(b->op());
  if (!a->op()->Equals(b->op())) return false;
  if (a->InputCount() != b->InputCount()) return false;
  Node::Inputs aInputs = a->inputs();
  Node::Inputs bInputs = b->inputs();
  auto aIt = aInputs.begin();
  auto bIt = bInputs.begin();
  auto aEnd = aInputs.end();
  for (; aIt != aEnd; ++aIt, ++bIt) {
    DCHECK_NOT_NULL(*aIt);
    DCHECK_NOT_NULL(*bIt);
    if ((*aIt)->id() != (*bIt)->id()) return false;
  }
  return true;
}
References DCHECK_NOT_NULL, v8::internal::compiler::Operator::Equals(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::Node::inputs(), v8::internal::compiler::Node::Inputs(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::NodeHashCache::NodeEquals::operator()(), and v8::internal::compiler::ValueNumberingReducer::Reduce().
FindFrameStateBefore()
Node * v8::internal::compiler::NodeProperties::FindFrameStateBefore (Node * node, Node * unreachable_sentinel) [static]
Definition at line 214 of file node-properties.cc.
                                                                       {
  Node* effect = NodeProperties::GetEffectInput(node);
  while (effect->opcode() != IrOpcode::kCheckpoint) {
    if (effect->opcode() == IrOpcode::kDead ||
        effect->opcode() == IrOpcode::kUnreachable) {
      return unreachable_sentinel;
    }
    DCHECK(effect->op()->HasProperty(Operator::kNoWrite));
    DCHECK_EQ(1, effect->op()->EffectInputCount());
    effect = NodeProperties::GetEffectInput(effect);
  }
  Node* frame_state = GetFrameStateInput(effect);
  return frame_state;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), GetEffectInput(), GetFrameStateInput(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::Operator::kNoWrite, v8::internal::wasm::kUnreachable, v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::JSTypeHintLowering::BuildDeoptIfFeedbackIsInsufficient(), v8::internal::compiler::JSNativeContextSpecialization::ReduceEagerDeoptimize(), and v8::internal::compiler::JSCallReducer::ReduceForInsufficientFeedback().
FindProjection()
Node * v8::internal::compiler::NodeProperties::FindProjection (Node * node, size_t projection_index) [static]
Definition at line 231 of file node-properties.cc.
                                                                        {
  for (auto use : node->uses()) {
    if (use->opcode() == IrOpcode::kProjection &&
        ProjectionIndexOf(use->op()) == projection_index) {
      return use;
    }
  }
  return nullptr;
}
References v8::internal::compiler::ProjectionIndexOf(), use(), and v8::internal::compiler::Node::uses().
Referenced by v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), and v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit().
FindSuccessfulControlProjection()
Node * v8::internal::compiler::NodeProperties::FindSuccessfulControlProjection (Node * node) [static]
Definition at line 78 of file node-properties.cc.
                                                                {
  CHECK_GT(node->op()->ControlOutputCount(), 0);
  if (node->op()->HasProperty(Operator::kNoThrow)) return node;
  for (Edge const edge : node->use_edges()) {
    if (!NodeProperties::IsControlEdge(edge)) continue;
    if (edge.from()->opcode() == IrOpcode::kIfSuccess) {
      return edge.from();
    }
  }
  return node;
}
References CHECK_GT, v8::internal::compiler::Operator::ControlOutputCount(), v8::internal::compiler::Operator::HasProperty(), IsControlEdge(), v8::internal::compiler::Operator::kNoThrow, v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::use_edges().
Referenced by v8::internal::compiler::RepresentationSelector::InsertUnreachableIfNecessary(), and v8::internal::compiler::JSInliner::ReduceJSCall().
FirstContextIndex()
static int v8::internal::compiler::NodeProperties::FirstContextIndex (Node * node) [inline], [static]
Definition at line 32 of file node-properties.h.
{ return PastValueIndex(node); }
Referenced by v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), IsContextEdge(), v8::internal::compiler::JSONGraphWriter::PrintEdge(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreInputOrDebugPos(), and ReplaceContextInput().
FirstControlIndex()
static int v8::internal::compiler::NodeProperties::FirstControlIndex (Node * node) [inline], [static]
Definition at line 35 of file node-properties.h.
{ return PastEffectIndex(node); }
Referenced by v8::internal::compiler::ControlEquivalence::DetermineParticipation(), v8::internal::compiler::Scheduler::GetCoupledControlEdge(), v8::internal::compiler::LoopFinderImpl::IsBackedge(), IsControlEdge(), v8::internal::compiler::SLPTree::IsSideEffectFreeLoad(), v8::internal::compiler::JSONGraphWriter::PrintEdge(), v8::internal::compiler::JSONGraphWriter::PrintNode(), RemoveControlFromEnd(), ReplaceControlInput(), v8::internal::compiler::CFGBuilder::Run(), and v8::internal::compiler::RepresentationSelector::VisitNode().
FirstEffectIndex()
static int v8::internal::compiler::NodeProperties::FirstEffectIndex (Node * node) [inline], [static]
Definition at line 34 of file node-properties.h.
{ return PastFrameStateIndex(node); }
Referenced by IsEffectEdge(), v8::internal::compiler::JSONGraphWriter::PrintEdge(), v8::internal::compiler::RepresentationSelector::ProcessRemainingInputs(), ReplaceEffectInput(), v8::internal::compiler::RepresentationSelector::VisitInputs(), v8::internal::compiler::RepresentationSelector::VisitReturn(), and v8::internal::compiler::RepresentationSelector::VisitUnused().
FirstFrameStateIndex()
static int v8::internal::compiler::NodeProperties::FirstFrameStateIndex (Node * node) [inline], [static]
Definition at line 33 of file node-properties.h.
{ return PastContextIndex(node); }
Referenced by v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), IsFrameStateEdge(), v8::internal::compiler::JSONGraphWriter::PrintEdge(), and ReplaceFrameStateInput().
FirstValueIndex()
static int v8::internal::compiler::NodeProperties::FirstValueIndex (const Node * node) [inline], [static]
Definition at line 31 of file node-properties.h.
{ return 0; }
Referenced by IsValueEdge(), v8::internal::compiler::JSONGraphWriter::PrintEdge(), and ReplaceValueInput().
GetContextInput()
static Node* v8::internal::compiler::NodeProperties::GetContextInput (Node * node) [inline], [static]
Definition at line 74 of file node-properties.h.
                                           {
    CHECK(OperatorProperties::HasContextInput(node->op()));
    return node->InputAt(FirstContextIndex(node));
  }
References CHECK, v8::internal::compiler::OperatorProperties::HasContextInput(), v8::internal::compiler::Node::InputAt(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::JSBinopReduction::context(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::EscapeAnalysisTracker::Scope::ContextInput(), v8::internal::compiler::JSCallReducerAssembler::ContextInput(), v8::internal::compiler::JSInliner::DetermineCallContext(), GetOuterContext(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteration(), v8::internal::compiler::JSIntrinsicLowering::ReduceCreateIterResultObject(), v8::internal::compiler::JSIntrinsicLowering::ReduceCreateJSGeneratorObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionReject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionResolve(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBlockContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCatchContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateWithContext(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorStore(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContext(), and v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContextNoCell().
GetControlInput()
static Node* v8::internal::compiler::NodeProperties::GetControlInput (Node * node, int index = 0) [inline], [static]
Definition at line 90 of file node-properties.h.
                                                          {
    CHECK_LE(0, index);
    CHECK_LT(index, node->op()->ControlInputCount());
    return node->InputAt(FirstControlIndex(node) + index);
  }
References CHECK_LE, CHECK_LT, v8::internal::compiler::Operator::ControlInputCount(), v8::internal::index, v8::internal::compiler::Node::InputAt(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::InductionVariable::AddLowerBound(), v8::internal::compiler::InductionVariable::AddUpperBound(), v8::internal::compiler::CsaLoadElimination::AssertUnreachable(), v8::internal::compiler::CFGBuilder::BuildBlocks(), v8::internal::compiler::JSTypedLowering::BuildGetModuleCell(), v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::CanLoopAllocate(), v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards(), v8::internal::compiler::RepresentationSelector::ChangeToPureOp(), v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::CheckInputsDominate(), v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::CFGBuilder::ConnectBranch(), v8::internal::compiler::CFGBuilder::ConnectCall(), v8::internal::compiler::CFGBuilder::ConnectDeoptimize(), v8::internal::compiler::CFGBuilder::ConnectReturn(), v8::internal::compiler::CFGBuilder::ConnectSwitch(), v8::internal::compiler::CFGBuilder::ConnectTailCall(), v8::internal::compiler::CFGBuilder::ConnectThrow(), v8::internal::compiler::JSBinopReduction::control(), v8::internal::compiler::CommonNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSInliningHeuristic::CreateOrReuseDispatch(), v8::internal::compiler::Scheduler::DecrementUnscheduledUseCount(), v8::internal::compiler::JSInliner::DetermineCallContext(), v8::internal::compiler::RepresentationSelector::DisconnectFromEffectAndControl(), v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::EffectPhiForPhi(), v8::internal::compiler::LoopPeeler::EliminateLoopExit(), v8::internal::compiler::LoopPeeler::EliminateLoopExits(), v8::internal::compiler::FastApiCallReducerAssembler::FastApiCallReducerAssembler(), v8::internal::compiler::CFGBuilder::FindPredecessorBlock(), v8::internal::compiler::ScheduleLateNodeVisitor::GetBlockForUse(), v8::internal::compiler::LinearScheduler::GetEarlySchedulePosition(), v8::internal::compiler::LoopTree::HeaderNode(), v8::internal::compiler::Scheduler::IncrementUnscheduledUseCount(), InferMapsUnsafe(), v8::internal::compiler::PrepareUsesVisitor::InitializePlacement(), v8::internal::compiler::Scheduler::InitializePlacement(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::RepresentationChanger::InsertConversion(), v8::internal::compiler::RepresentationChanger::InsertUnconditionalDeopt(), v8::internal::compiler::RepresentationSelector::InsertUnreachableIfNecessary(), v8::internal::compiler::RawMachineAssembler::MakePhiBinary(), v8::internal::compiler::RawMachineAssembler::MarkControlDeferred(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::ScheduleLateNodeVisitor::ProcessQueue(), v8::internal::compiler::LoopFinderImpl::PropagateBackward(), v8::internal::compiler::DeadCodeElimination::PropagateDeadControl(), v8::internal::compiler::ScheduleEarlyNodeVisitor::PropagateMinimumPositionToNode(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::WasmEscapeAnalysis::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteOffsetAccessor(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::WasmGCOperatorReducer::ReduceAssertNotNull(), v8::internal::compiler::BranchElimination::ReduceBranch(), v8::internal::compiler::DeadCodeElimination::ReduceBranchOrSwitch(), v8::internal::compiler::WasmGCOperatorReducer::ReduceCheckNull(), v8::internal::compiler::JSIntrinsicLowering::ReduceCheckTurboshaftTypeOf(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteration(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeHas(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize(), v8::internal::compiler::JSIntrinsicLowering::ReduceCreateJSGeneratorObject(), v8::internal::compiler::JSCallReducer::ReduceDateNow(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetField(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetTime(), v8::internal::compiler::BranchElimination::ReduceDeoptimizeConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceDeoptimizeConditional(), v8::internal::compiler::JSIntrinsicLowering::ReduceDeoptimizeNow(), v8::internal::compiler::DeadCodeElimination::ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceEagerDeoptimize(), v8::internal::compiler::DeadCodeElimination::ReduceEffectNode(), v8::internal::compiler::CsaLoadElimination::ReduceEffectPhi(), v8::internal::compiler::DeadCodeElimination::ReduceEffectPhi(), v8::internal::compiler::LoadElimination::ReduceEffectPhi(), v8::internal::compiler::RedundancyElimination::ReduceEffectPhi(), v8::internal::compiler::WasmLoadElimination::ReduceEffectPhi(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccessOnString(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::JSCallReducer::ReduceForInsufficientFeedback(), v8::internal::compiler::JSIntrinsicLowering::ReduceGeneratorClose(), v8::internal::compiler::JSIntrinsicLowering::ReduceGeneratorGetResumeMode(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::compiler::WasmGCOperatorReducer::ReduceIf(), v8::internal::compiler::BranchElimination::ReduceIf(), v8::internal::compiler::JSIntrinsicLowering::ReduceIsInstanceType(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionReject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionResolve(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBlockContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCatchContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateWithContext(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContinuation(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreRegister(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorStore(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadModule(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreModule(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::MemoryLowering::ReduceLoadBoundedSize(), v8::internal::compiler::MemoryLowering::ReduceLoadExternalPointerField(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable(), v8::internal::compiler::MemoryLowering::ReduceLoadMap(), v8::internal::compiler::DeadCodeElimination::ReduceLoopExit(), v8::internal::compiler::JSCallReducer::ReduceMapPrototypeGet(), v8::internal::compiler::JSCallReducer::ReduceMathMinMax(), v8::internal::compiler::TypedOptimization::ReduceMaybeGrowFastElements(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), v8::internal::compiler::TypedOptimization::ReducePhi(), v8::internal::compiler::CommonOperatorReducer::ReduceReturn(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIterator(), v8::internal::compiler::BranchElimination::ReduceTrapConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceTrapConditional(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeToStringTag(), v8::internal::compiler::WasmGCOperatorReducer::ReduceTypeGuard(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArraySet(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmStructOperation(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::DeadCodeElimination::RemoveLoopExit(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::RepresentationSelector::ReplaceWithPureNode(), v8::internal::compiler::GraphReducer::ReplaceWithValue(), v8::internal::compiler::LoopVariableOptimizer::Run(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::ShouldUseCallICFeedback(), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), v8::internal::compiler::LoopVariableOptimizer::TakeConditionsFromFirstControl(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::TakeStatesFromFirstControl(), v8::internal::compiler::BranchElimination::TryEliminateBranchWithPhiCondition(), v8::internal::compiler::LoopVariableOptimizer::TryGetInductionVariable(), v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch(), v8::internal::compiler::Scheduler::UpdatePlacement(), v8::internal::compiler::Revectorizer::VectorizeTree(), and v8::internal::compiler::LoopVariableOptimizer::VisitBackedge().
GetEffectInput()
static Node* v8::internal::compiler::NodeProperties::GetEffectInput (Node * node, int index = 0) [inline], [static]
Definition at line 84 of file node-properties.h.
                                                         {
    CHECK_LE(0, index);
    CHECK_LT(index, node->op()->EffectInputCount());
    return node->InputAt(FirstEffectIndex(node) + index);
  }
References CHECK_LE, CHECK_LT, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::index, v8::internal::compiler::Node::InputAt(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::CsaLoadElimination::AssertUnreachable(), v8::internal::compiler::JSTypedLowering::BuildGetModuleCell(), v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards(), v8::internal::compiler::RepresentationSelector::ChangeToPureOp(), v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::CsaLoadElimination::ComputeLoopState(), v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::WasmLoadElimination::ComputeLoopState(), v8::internal::compiler::JSInliner::DetermineCallContext(), v8::internal::compiler::RepresentationSelector::DisconnectFromEffectAndControl(), v8::internal::compiler::JSBinopReduction::effect(), v8::internal::compiler::CommonNodeWrapperBase::effect(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::LoopPeeler::EliminateLoopExit(), FindFrameStateBefore(), InferMapsUnsafe(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::InsertAssertion(), v8::internal::compiler::RepresentationChanger::InsertConversion(), v8::internal::compiler::RepresentationChanger::InsertUnconditionalDeopt(), v8::internal::compiler::anonymous_namespace{checkpoint-elimination.cc}::IsRedundantCheckpoint(), v8::internal::compiler::SLPTree::IsSideEffectFreeLoad(), v8::internal::compiler::VariableTracker::MergeInputs(), NoObservableSideEffectBetween(), v8::internal::compiler::BytecodeGraphBuilder::PrepareEagerCheckpoint(), v8::internal::compiler::CsaLoadElimination::PropagateInputState(), v8::internal::compiler::CsaLoadElimination::Reduce(), v8::internal::compiler::LoadElimination::Reduce(), v8::internal::compiler::SimplifiedOperatorReducer::Reduce(), v8::internal::compiler::EscapeAnalysisReducer::Reduce(), v8::internal::compiler::PairLoadStoreReducer::Reduce(), v8::internal::compiler::WasmEscapeAnalysis::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteOffsetAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::TypedOptimization::ReduceCheckEqualsInternalizedString(), v8::internal::compiler::TypedOptimization::ReduceCheckEqualsSymbol(), v8::internal::compiler::LoadElimination::ReduceCheckMaps(), v8::internal::compiler::TypedOptimization::ReduceCheckMaps(), v8::internal::compiler::RedundancyElimination::ReduceCheckNode(), v8::internal::compiler::CheckpointElimination::ReduceCheckpoint(), v8::internal::compiler::JSIntrinsicLowering::ReduceCheckTurboshaftTypeOf(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteration(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeHas(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize(), v8::internal::compiler::LoadElimination::ReduceCompareMaps(), v8::internal::compiler::JSIntrinsicLowering::ReduceCreateIterResultObject(), v8::internal::compiler::JSIntrinsicLowering::ReduceCreateJSGeneratorObject(), v8::internal::compiler::JSCallReducer::ReduceDateNow(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetField(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetTime(), v8::internal::compiler::BranchElimination::ReduceDeoptimizeConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceDeoptimizeConditional(), v8::internal::compiler::JSIntrinsicLowering::ReduceDeoptimizeNow(), v8::internal::compiler::DeadCodeElimination::ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceEagerDeoptimize(), v8::internal::compiler::DeadCodeElimination::ReduceEffectNode(), v8::internal::compiler::CsaLoadElimination::ReduceEffectPhi(), v8::internal::compiler::DeadCodeElimination::ReduceEffectPhi(), v8::internal::compiler::LoadElimination::ReduceEffectPhi(), v8::internal::compiler::RedundancyElimination::ReduceEffectPhi(), v8::internal::compiler::WasmLoadElimination::ReduceEffectPhi(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccessOnString(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::LoadElimination::ReduceEnsureWritableFastElements(), v8::internal::compiler::JSCallReducer::ReduceForInsufficientFeedback(), v8::internal::compiler::JSIntrinsicLowering::ReduceGeneratorClose(), v8::internal::compiler::JSIntrinsicLowering::ReduceGeneratorGetResumeMode(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::compiler::JSIntrinsicLowering::ReduceIsInstanceType(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionReject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionResolve(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBlockContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCatchContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateIterResultObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreatePromise(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringWrapper(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateWithContext(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContinuation(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreRegister(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorStore(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadModule(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreModule(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToObject(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::MemoryLowering::ReduceLoadBoundedSize(), v8::internal::compiler::LoadElimination::ReduceLoadElement(), v8::internal::compiler::MemoryLowering::ReduceLoadExternalPointerField(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable(), v8::internal::compiler::MemoryLowering::ReduceLoadMap(), v8::internal::compiler::LoadElimination::ReduceMapGuard(), v8::internal::compiler::JSCallReducer::ReduceMapPrototypeGet(), v8::internal::compiler::JSCallReducer::ReduceMathMinMax(), v8::internal::compiler::LoadElimination::ReduceMaybeGrowFastElements(), v8::internal::compiler::TypedOptimization::ReduceMaybeGrowFastElements(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), v8::internal::compiler::JSCallReducer::ReduceObjectGetPrototype(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), v8::internal::compiler::CsaLoadElimination::ReduceOtherNode(), v8::internal::compiler::LoadElimination::ReduceOtherNode(), v8::internal::compiler::WasmLoadElimination::ReduceOtherNode(), v8::internal::compiler::CommonOperatorReducer::ReduceReturn(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberComparison(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberOperation(), v8::internal::compiler::Revectorizer::ReduceStoreChains(), v8::internal::compiler::LoadElimination::ReduceStoreElement(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::CsaLoadElimination::ReduceStoreToObject(), v8::internal::compiler::LoadElimination::ReduceStoreTypedElement(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIterator(), v8::internal::compiler::LoadElimination::ReduceTransitionAndStoreElement(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap(), v8::internal::compiler::TypedOptimization::ReduceTransitionElementsKindOrCheckMap(), v8::internal::compiler::JSIntrinsicLowering::ReduceTurbofanStaticAssert(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeToStringTag(), v8::internal::compiler::DeadCodeElimination::ReduceUnreachableOrIfException(), v8::internal::compiler::JSIntrinsicLowering::ReduceVerifyType(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmLoadElimination::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArraySet(), v8::internal::compiler::WasmGCLowering::ReduceWasmExternConvertAny(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::RepresentationSelector::ReplaceWithPureNode(), v8::internal::compiler::GraphReducer::ReplaceWithValue(), v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleRegion(), v8::internal::compiler::VariableTracker::Scope::Scope(), v8::internal::compiler::anonymous_namespace{memory-optimizer.cc}::SearchAllocatingNode(), v8::internal::compiler::Revectorizer::SetEffectInput(), v8::internal::compiler::RedundancyElimination::TakeChecksFromFirstEffect(), v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch(), v8::internal::compiler::UnrollLoop(), v8::internal::compiler::Revectorizer::UpdateSources(), and v8::internal::compiler::LoadElimination::UpdateStateForPhi().
GetFrameStateInput()
static Node* v8::internal::compiler::NodeProperties::GetFrameStateInput (Node * node) [inline], [static]
Definition at line 79 of file node-properties.h.
                                              {
    CHECK(OperatorProperties::HasFrameStateInput(node->op()));
    return node->InputAt(FirstFrameStateIndex(node));
  }
References CHECK, v8::internal::compiler::OperatorProperties::HasFrameStateInput(), v8::internal::compiler::Node::InputAt(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), FindFrameStateBefore(), v8::internal::compiler::JSCallAccessor::frame_state(), v8::internal::compiler::JSNodeWrapperBase::frame_state(), v8::internal::compiler::JSCallReducerAssembler::FrameStateInput(), v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::GetArgumentsFrameState(), v8::internal::compiler::anonymous_namespace{checkpoint-elimination.cc}::GetFunctionInfo(), v8::internal::compiler::BytecodeGraphBuilder::PrepareEagerCheckpoint(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::JSInliningHeuristic::Reduce(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSIntrinsicLowering::ReduceDeoptimizeNow(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionReject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionResolve(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), and v8::internal::compiler::JSInliningHeuristic::TryReuseDispatch().
GetJSCreateMap()
OptionalMapRef v8::internal::compiler::NodeProperties::GetJSCreateMap (JSHeapBroker * broker, Node * receiver) [static]
Definition at line 382 of file node-properties.cc.
                                                              {
  DCHECK(receiver->opcode() == IrOpcode::kJSCreate ||
         receiver->opcode() == IrOpcode::kJSCreateArray);
  HeapObjectMatcher mtarget(GetValueInput(receiver, 0));
  HeapObjectMatcher mnewtarget(GetValueInput(receiver, 1));
  if (mtarget.HasResolvedValue() && mnewtarget.HasResolvedValue() &&
      mnewtarget.Ref(broker).IsJSFunction()) {
    ObjectRef target = mtarget.Ref(broker);
    JSFunctionRef newtarget = mnewtarget.Ref(broker).AsJSFunction();
    if (newtarget.map(broker).has_prototype_slot() &&
        newtarget.has_initial_map(broker)) {
      MapRef initial_map = newtarget.initial_map(broker);
      if (initial_map.GetConstructor(broker).equals(target)) {
        DCHECK(target.AsJSFunction().map(broker).is_constructor());
        DCHECK(newtarget.map(broker).is_constructor());
        return initial_map;
      }
    }
  }
  return std::nullopt;
}
References broker(), v8::internal::DCHECK(), GetValueInput(), v8::internal::compiler::JSFunctionRef::has_initial_map(), v8::internal::compiler::MapRef::has_prototype_slot(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::initial_map, v8::internal::compiler::JSFunctionRef::initial_map(), v8::internal::compiler::MapRef::is_constructor(), v8::internal::compiler::HeapObjectRef::map(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref().
Referenced by InferMapsUnsafe(), v8::internal::compiler::JSNativeContextSpecialization::InferRootMap(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), and v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray().
GetOuterContext()
Node * v8::internal::compiler::NodeProperties::GetOuterContext (Node * node, size_t * depth) [static]
Definition at line 668 of file node-properties.cc.
                                                               {
  Node* context = NodeProperties::GetContextInput(node);
  while (*depth > 0 &&
         IrOpcode::IsContextChainExtendingOpcode(context->opcode())) {
    context = NodeProperties::GetContextInput(context);
    (*depth)--;
  }
  return context;
}
References GetContextInput(), v8::internal::compiler::IrOpcode::IsContextChainExtendingOpcode(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::GetModuleContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), and v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContextNoCell().
GetProjectionType()
MachineRepresentation v8::internal::compiler::NodeProperties::GetProjectionType (Node const * projection) [static]
Definition at line 312 of file node-properties.cc.
                            {
  size_t index = ProjectionIndexOf(projection->op());
  Node* input = projection->InputAt(0);
  switch (input->opcode()) {
    case IrOpcode::kInt32AddWithOverflow:
    case IrOpcode::kInt32SubWithOverflow:
    case IrOpcode::kInt32MulWithOverflow:
    case IrOpcode::kInt32AbsWithOverflow:
      CHECK_LE(index, static_cast<size_t>(1));
      return index == 0 ? MachineRepresentation::kWord32
                        : MachineRepresentation::kBit;
    case IrOpcode::kInt64AddWithOverflow:
    case IrOpcode::kInt64SubWithOverflow:
    case IrOpcode::kInt64MulWithOverflow:
    case IrOpcode::kInt64AbsWithOverflow:
      CHECK_LE(index, static_cast<size_t>(1));
      return index == 0 ? MachineRepresentation::kWord64
                        : MachineRepresentation::kBit;
    case IrOpcode::kTryTruncateFloat64ToInt32:
    case IrOpcode::kTryTruncateFloat64ToUint32:
      CHECK_LE(index, static_cast<size_t>(1));
      return index == 0 ? MachineRepresentation::kWord32
                        : MachineRepresentation::kBit;
    case IrOpcode::kTryTruncateFloat32ToInt64:
    case IrOpcode::kTryTruncateFloat64ToInt64:
    case IrOpcode::kTryTruncateFloat64ToUint64:
    case IrOpcode::kTryTruncateFloat32ToUint64:
      CHECK_LE(index, static_cast<size_t>(1));
      return index == 0 ? MachineRepresentation::kWord64
                        : MachineRepresentation::kBit;
    case IrOpcode::kCall: {
      auto call_descriptor = CallDescriptorOf(input->op());
      return call_descriptor->GetReturnType(index).representation();
    }
    case IrOpcode::kInt32PairAdd:
    case IrOpcode::kInt32PairSub:
    case IrOpcode::kWord32AtomicPairLoad:
    case IrOpcode::kWord32AtomicPairAdd:
    case IrOpcode::kWord32AtomicPairSub:
    case IrOpcode::kWord32AtomicPairAnd:
    case IrOpcode::kWord32AtomicPairOr:
    case IrOpcode::kWord32AtomicPairXor:
    case IrOpcode::kWord32AtomicPairExchange:
    case IrOpcode::kWord32AtomicPairCompareExchange:
      CHECK_LE(index, static_cast<size_t>(1));
      return MachineRepresentation::kWord32;
    default:
      return MachineRepresentation::kNone;
  }
}
References v8::internal::compiler::CallDescriptorOf(), CHECK_LE, v8::internal::index, v8::internal::compiler::Node::InputAt(), v8::internal::kBit, v8::internal::kNone, v8::internal::kWord32, v8::internal::kWord64, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::ProjectionIndexOf().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::anonymous_namespace{machine-graph-verifier.cc}::MachineRepresentationInferrer::Run().
GetType()
static Type v8::internal::compiler::NodeProperties::GetType (const Node * node) [inline], [static]
Definition at line 260 of file node-properties.h.
                                        {
    DCHECK(IsTyped(node));
    return node->type();
  }
References v8::internal::DCHECK(), and v8::internal::compiler::Node::type().
Referenced by v8::internal::compiler::JSTypedLowering::BuildGetModuleCell(), v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc}::CheckMapsHelper(), v8::internal::compiler::SimplifiedLoweringVerifier::CheckType(), v8::internal::compiler::Verifier::Visitor::CheckTypeIs(), v8::internal::compiler::Verifier::Visitor::CheckTypeMaybe(), v8::internal::compiler::Verifier::Visitor::CheckValueInputIs(), v8::internal::compiler::JSBinopReduction::ConvertPlainPrimitiveToNumber(), v8::internal::compiler::TypedOptimization::ConvertPlainPrimitiveToNumber(), v8::internal::compiler::JSBinopReduction::ConvertToUI32(), v8::internal::compiler::Typer::Decorator::Decorate(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::JSONGraphWriter::GetType(), v8::internal::compiler::SimplifiedLoweringVerifier::GetType(), v8::internal::compiler::RepresentationSelector::GetUpperBound(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc}::InDeadBranch(), v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint(), v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::InsertAssertion(), v8::internal::compiler::LoadElimination::AbstractElements::Kill(), v8::internal::compiler::JSBinopReduction::left_type(), v8::internal::compiler::anonymous_namespace{load-elimination.cc}::MayAlias(), v8::internal::compiler::GraphAssembler::MergeState(), v8::internal::compiler::NodeHashCache::Constructor::MutableNode(), v8::internal::compiler::WasmGCOperatorReducer::ObjectTypeFromContext(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::OffsetOfElementsAccess(), v8::internal::compiler::operator<<(), v8::internal::compiler::RepresentationSelector::PrintNodeFeedbackType(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledNode(), v8::internal::compiler::GraphC1Visualizer::PrintType(), v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::ProcessBlock(), v8::internal::compiler::TypeNarrowingReducer::Reduce(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::WasmGCOperatorReducer::ReduceAssertNotNull(), v8::internal::compiler::TypedOptimization::ReduceCheckBounds(), v8::internal::compiler::TypedOptimization::ReduceCheckEqualsInternalizedString(), v8::internal::compiler::TypedOptimization::ReduceCheckEqualsSymbol(), v8::internal::compiler::TypedOptimization::ReduceCheckHeapObject(), v8::internal::compiler::TypedOptimization::ReduceCheckMaps(), v8::internal::compiler::TypedOptimization::ReduceCheckNotTaggedHole(), v8::internal::compiler::TypedOptimization::ReduceCheckNumber(), v8::internal::compiler::TypedOptimization::ReduceCheckNumberFitsInt32(), v8::internal::compiler::TypedOptimization::ReduceCheckString(), v8::internal::compiler::TypedOptimization::ReduceCheckStringOrStringWrapper(), v8::internal::compiler::TypedOptimization::ReduceConvertReceiver(), v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState(), v8::internal::compiler::JSTypedLowering::ReduceJSBitwiseNot(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs(), v8::internal::compiler::JSTypedLowering::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSTypedLowering::ReduceJSDecrement(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSTypedLowering::ReduceJSIncrement(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadNamed(), v8::internal::compiler::JSTypedLowering::ReduceJSNegate(), v8::internal::compiler::JSTypedLowering::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSTypedLowering::ReduceJSParseInt(), v8::internal::compiler::JSTypedLowering::ReduceJSResolvePromise(), v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual(), v8::internal::compiler::JSTypedLowering::ReduceJSToBigInt(), v8::internal::compiler::JSTypedLowering::ReduceJSToBigIntConvertNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToLength(), v8::internal::compiler::JSTypedLowering::ReduceJSToName(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumberInput(), v8::internal::compiler::TypedOptimization::ReduceJSToNumberInput(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumeric(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSTypedLowering::ReduceJSToStringInput(), v8::internal::compiler::LoadElimination::ReduceLoadElement(), v8::internal::compiler::TypedOptimization::ReduceLoadField(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::TypedOptimization::ReduceMaybeGrowFastElements(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), v8::internal::compiler::TypedOptimization::ReduceNumberFloor(), v8::internal::compiler::TypedOptimization::ReduceNumberRoundop(), v8::internal::compiler::TypedOptimization::ReduceNumberSilenceNaN(), v8::internal::compiler::TypedOptimization::ReduceNumberToUint8Clamped(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), v8::internal::compiler::TypedOptimization::ReducePhi(), v8::internal::compiler::TypedOptimization::ReduceReferenceEqual(), v8::internal::compiler::TypedOptimization::ReduceSameValue(), v8::internal::compiler::TypedOptimization::ReduceSelect(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberAdd(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberBinop(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberComparison(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberComparison(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberOperation(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeToNumber(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::TypedOptimization::ReduceStringComparison(), v8::internal::compiler::TypedOptimization::ReduceToBoolean(), v8::internal::compiler::TypedOptimization::ReduceTransitionElementsKindOrCheckMap(), v8::internal::compiler::TypedOptimization::ReduceTypeOf(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::ValueNumberingReducer::ReplaceIfTypesMatch(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::JSBinopReduction::right_type(), v8::internal::compiler::WasmGraphBuilder::SetType(), v8::internal::compiler::WasmLoadElimination::TruncateAndExtendOrType(), v8::internal::compiler::anonymous_namespace{constant-folding-reducer.cc}::TryGetConstant(), v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCode(), v8::internal::compiler::JSBinopReduction::type(), v8::internal::compiler::RepresentationSelector::TypeOf(), v8::internal::compiler::Typer::Visitor::TypeOrNone(), v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::TypeSubsumes(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::TypesUnrelated(), v8::internal::compiler::RepresentationSelector::UpdateFeedbackType(), v8::internal::compiler::Typer::Visitor::UpdateType(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus(), and v8::internal::compiler::RepresentationSelector::WriteBarrierKindFor().
GetTypeOrAny()
Type v8::internal::compiler::NodeProperties::GetTypeOrAny (const Node * node) [static]
Definition at line 679 of file node-properties.cc.
                                                  {
  return IsTyped(node) ? node->type() : Type::Any();
}
References v8::internal::compiler::turboshaft::Type::Any(), IsTyped(), and v8::internal::compiler::Node::type().
Referenced by v8::internal::compiler::anonymous_namespace{dead-code-elimination.cc}::NoReturn(), v8::internal::compiler::DeadCodeElimination::ReducePhi(), and v8::internal::compiler::RepresentationSelector::SetOutput().
GetValueInput() [1/2]
static const Node* v8::internal::compiler::NodeProperties::GetValueInput (const Node * node, int index) [inline], [static]
Definition at line 68 of file node-properties.h.
                                                                {
    CHECK_LE(0, index);
    CHECK_LT(index, node->op()->ValueInputCount());
    return node->InputAt(FirstValueIndex(node) + index);
  }
References CHECK_LE, CHECK_LT, v8::internal::index, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::ValueInputCount().
GetValueInput() [2/2]
static Node* v8::internal::compiler::NodeProperties::GetValueInput (Node * node, int index) [inline], [static]
Definition at line 62 of file node-properties.h.
                                                    {
    CHECK_LE(0, index);
    CHECK_LT(index, node->op()->ValueInputCount());
    return node->InputAt(FirstValueIndex(node) + index);
  }
References CHECK_LE, CHECK_LT, v8::internal::index, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by v8::internal::compiler::anonymous_namespace{wasm-typer.cc}::AllInputsTyped(), AllValueInputsAreTyped(), v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::JSTypedLowering::BuildGetModuleCell(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::Verifier::Visitor::CheckValueInputIs(), v8::internal::compiler::CsaLoadElimination::ComputeLoopState(), v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::WasmLoadElimination::ComputeLoopState(), v8::internal::compiler::LoadElimination::ComputeLoopStateForStoreField(), v8::internal::compiler::MemoryLowering::AllocationGroup::Contains(), v8::internal::compiler::DeadCodeElimination::DeadValue(), v8::internal::compiler::anonymous_namespace{machine-operator-reducer.cc}::BitfieldCheck::Detect(), v8::internal::compiler::JSCallOrConstructNode::feedback_vector(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::anonymous_namespace{wasm-gc-operator-reducer.cc}::GetAlias(), GetJSCreateMap(), v8::internal::compiler::StringBuilderOptimizer::GetPhiPredecessorsCommonId(), InferMapsUnsafe(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), v8::internal::compiler::anonymous_namespace{js-context-specialization.cc}::IsContextParameter(), IsSame(), v8::internal::compiler::JSBinopReduction::left(), v8::internal::compiler::RawMachineAssembler::MakePhiBinary(), v8::internal::compiler::RepresentationSelector::MaskShiftOperand(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::SLPTree::NewPackNodeAndRecurs(), v8::internal::compiler::WasmGCOperatorReducer::ObjectTypeFromContext(), v8::internal::compiler::Typer::Visitor::Operand(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::CsaLoadElimination::Reduce(), v8::internal::compiler::LoadElimination::Reduce(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::WasmEscapeAnalysis::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteOffsetAccessor(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::WasmGCLowering::ReduceAssertNotNull(), v8::internal::compiler::WasmGCOperatorReducer::ReduceAssertNotNull(), v8::internal::compiler::DeadCodeElimination::ReduceBranchOrSwitch(), v8::internal::compiler::CsaLoadElimination::ReduceCall(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::TypedOptimization::ReduceCheckBounds(), v8::internal::compiler::TypedOptimization::ReduceCheckEqualsInternalizedString(), v8::internal::compiler::TypedOptimization::ReduceCheckEqualsSymbol(), v8::internal::compiler::TypedOptimization::ReduceCheckHeapObject(), v8::internal::compiler::LoadElimination::ReduceCheckMaps(), v8::internal::compiler::TypedOptimization::ReduceCheckMaps(), v8::internal::compiler::TypedOptimization::ReduceCheckNotTaggedHole(), v8::internal::compiler::WasmGCOperatorReducer::ReduceCheckNull(), v8::internal::compiler::TypedOptimization::ReduceCheckNumber(), v8::internal::compiler::TypedOptimization::ReduceCheckNumberFitsInt32(), v8::internal::compiler::TypedOptimization::ReduceCheckString(), v8::internal::compiler::TypedOptimization::ReduceCheckStringOrStringWrapper(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteration(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeHas(), v8::internal::compiler::JSCallReducer::ReduceCollectionPrototypeSize(), v8::internal::compiler::LoadElimination::ReduceCompareMaps(), v8::internal::compiler::MachineOperatorReducer::ReduceConditional(), v8::internal::compiler::MachineOperatorReducer::ReduceConditionalN(), v8::internal::compiler::TypedOptimization::ReduceConvertReceiver(), v8::internal::compiler::JSIntrinsicLowering::ReduceCreateIterResultObject(), v8::internal::compiler::JSIntrinsicLowering::ReduceCreateJSGeneratorObject(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetField(), v8::internal::compiler::JSCallReducer::ReduceDatePrototypeGetTime(), v8::internal::compiler::BranchElimination::ReduceDeoptimizeConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceDeoptimizeConditional(), v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccessOnString(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementLoadFromHeapConstant(), v8::internal::compiler::LoadElimination::ReduceEnsureWritableFastElements(), v8::internal::compiler::JSIntrinsicLowering::ReduceGeneratorClose(), v8::internal::compiler::JSIntrinsicLowering::ReduceGeneratorGetResumeMode(), v8::internal::compiler::WasmGCOperatorReducer::ReduceIf(), v8::internal::compiler::JSIntrinsicLowering::ReduceIsInstanceType(), v8::internal::compiler::WasmGCLowering::ReduceIsNotNull(), v8::internal::compiler::WasmGCLowering::ReduceIsNull(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionEnter(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionReject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAsyncFunctionResolve(), v8::internal::compiler::JSTypedLowering::ReduceJSBitwiseNot(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs(), v8::internal::compiler::JSCreateLowering::ReduceJSCreate(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCatchContext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateIterResultObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringIterator(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringWrapper(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateWithContext(), v8::internal::compiler::JSTypedLowering::ReduceJSDecrement(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreContinuation(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorRestoreRegister(), v8::internal::compiler::JSTypedLowering::ReduceJSGeneratorStore(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetSuperConstructor(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSTypedLowering::ReduceJSIncrement(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), v8::internal::compiler::JSTypedLowering::ReduceJSNegate(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSTypedLowering::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSTypedLowering::ReduceJSParseInt(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSPromiseResolve(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSResolvePromise(), v8::internal::compiler::JSTypedLowering::ReduceJSResolvePromise(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreContextNoCell(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreMessage(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreModule(), v8::internal::compiler::JSTypedLowering::ReduceJSToLength(), v8::internal::compiler::JSTypedLowering::ReduceJSToName(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumeric(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToObject(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::LoadElimination::ReduceLoadElement(), v8::internal::compiler::TypedOptimization::ReduceLoadField(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable(), v8::internal::compiler::LoadElimination::ReduceMapGuard(), v8::internal::compiler::JSCallReducer::ReduceMapPrototypeGet(), v8::internal::compiler::LoadElimination::ReduceMaybeGrowFastElements(), v8::internal::compiler::TypedOptimization::ReduceMaybeGrowFastElements(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::TypedOptimization::ReduceNumberFloor(), v8::internal::compiler::TypedOptimization::ReduceNumberRoundop(), v8::internal::compiler::TypedOptimization::ReduceNumberSilenceNaN(), v8::internal::compiler::TypedOptimization::ReduceNumberToUint8Clamped(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty(), v8::internal::compiler::DeadCodeElimination::ReducePhi(), v8::internal::compiler::TypedOptimization::ReduceReferenceEqual(), v8::internal::compiler::CommonOperatorReducer::ReduceReturn(), v8::internal::compiler::TypedOptimization::ReduceSameValue(), v8::internal::compiler::TypedOptimization::ReduceSelect(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberAdd(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberBinop(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberComparison(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeNumberComparison(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberOperation(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeToNumber(), v8::internal::compiler::LoadElimination::ReduceStoreElement(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::CsaLoadElimination::ReduceStoreToObject(), v8::internal::compiler::WasmGCLowering::ReduceStringAsWtf16(), v8::internal::compiler::TypedOptimization::ReduceStringComparison(), v8::internal::compiler::TypedOptimization::ReduceStringLength(), v8::internal::compiler::WasmGCLowering::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::JSIntrinsicLowering::ReduceToString(), v8::internal::compiler::LoadElimination::ReduceTransitionAndStoreElement(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap(), v8::internal::compiler::TypedOptimization::ReduceTransitionElementsKindOrCheckMap(), v8::internal::compiler::JSIntrinsicLowering::ReduceTurbofanStaticAssert(), v8::internal::compiler::TypedOptimization::ReduceTypedArrayLength(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeToStringTag(), v8::internal::compiler::WasmGCLowering::ReduceTypeGuard(), v8::internal::compiler::WasmGCOperatorReducer::ReduceTypeGuard(), v8::internal::compiler::JSIntrinsicLowering::ReduceVerifyType(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmAnyConvertExtern(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayGet(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmLoadElimination::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCLowering::ReduceWasmArraySet(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructGet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmStructOperation(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::MachineOperatorReducer::ReduceWord32Equal(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons(), v8::internal::compiler::NodeHashCache::Constructor::ReplaceValueInput(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::ResolveAliases(), v8::internal::compiler::JSBinopReduction::right(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::TargetIsClassConstructor(), v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::TryGetStoredValue(), v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCode(), v8::internal::compiler::EscapeAnalysisTracker::Scope::ValueInput(), and v8::internal::compiler::RepresentationSelector::VisitCheckBounds().
HashCode()
size_t v8::internal::compiler::NodeProperties::HashCode (Node * node) [static]
Definition at line 700 of file node-properties.cc.
                                          {
  size_t h = base::hash_combine(node->op()->HashCode(), node->InputCount());
  for (Node* input : node->inputs()) {
    h = base::hash_combine(h, input->id());
  }
  return h;
}
References h(), v8::base::hash_combine(), v8::internal::compiler::Operator::HashCode(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::Node::inputs(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::ValueNumberingReducer::Grow(), v8::internal::compiler::NodeHashCache::NodeHashCode::operator()(), and v8::internal::compiler::ValueNumberingReducer::Reduce().
InferMapsUnsafe()
NodeProperties::InferMapsResult v8::internal::compiler::NodeProperties::InferMapsUnsafe (JSHeapBroker * broker, Node * receiver, Effect effect, ZoneRefSet< Map > * maps_out) [static]
Definition at line 406 of file node-properties.cc.
                               {
  HeapObjectMatcher m(receiver);
  if (m.HasResolvedValue()) {
    HeapObjectRef ref = m.Ref(broker);
    // We don't use ICs for the Array.prototype and the Object.prototype
    // because the runtime has to be able to intercept them properly, so
    // we better make sure that TurboFan doesn't outsmart the system here
    // by storing to elements of either prototype directly.
    //
    // TODO(bmeurer): This can be removed once the Array.prototype and
    // Object.prototype have NO_ELEMENTS elements kind.
    if (!ref.IsJSObject() ||
        !broker->IsArrayOrObjectPrototype(ref.AsJSObject())) {
      if (ref.map(broker).is_stable()) {
        // The {receiver_map} is only reliable when we install a stability
        // code dependency.
        *maps_out = ZoneRefSet<Map>{ref.map(broker)};
        return kUnreliableMaps;
      }
    }
  }
  InferMapsResult result = kReliableMaps;
  while (true) {
#ifdef DEBUG
    InferMapsResult prev_result = result;
    bool write_might_change_aliasing_maps = true;
#define WRITE_CANNOT_CHANGE_ALIASING_MAPS() \
  write_might_change_aliasing_maps = false
#else
// Swallow the semicolon.
#define WRITE_CANNOT_CHANGE_ALIASING_MAPS() ((void)0)
#endif
    switch (effect->opcode()) {
      case IrOpcode::kTypeGuard: {
        DCHECK_EQ(1, effect->op()->EffectInputCount());
        effect = NodeProperties::GetEffectInput(effect);
        continue;
      }
      case IrOpcode::kMapGuard: {
        Node* const object = GetValueInput(effect, 0);
        if (IsSame(receiver, object)) {
          *maps_out = MapGuardMapsOf(effect->op());
          return result;
        }
        break;
      }
      case IrOpcode::kCheckMaps: {
        Node* const object = GetValueInput(effect, 0);
        if (IsSame(receiver, object)) {
          *maps_out = CheckMapsParametersOf(effect->op()).maps();
          return result;
        }
        // This is subtle: CheckMaps with TryMigrateInstance _can_ write maps,
        // but it can only transition away from deprecated maps, which should
        // never be inferable maps, since we eagerly try to find the migration
        // target of deprecated maps when we see them. It could be that a
        // previous CheckMaps or other map inference node contains deprecated
        // maps as of this check, because there could have been a concurrent
        // deprecation, and this means that we can't CHECK this invariant here;
        // but, then compilation would fail during finalization thanks to a
        // CheckNoDeprecatedMaps check.
        WRITE_CANNOT_CHANGE_ALIASING_MAPS();
        break;
      }
      case IrOpcode::kTransitionElementsKindOrCheckMap: {
        Node* const object = GetValueInput(effect, 0);
        if (IsSame(receiver, object)) {
          *maps_out = ZoneRefSet<Map>{
              ElementsTransitionWithMultipleSourcesOf(effect->op()).target()};
          return result;
        }
        // `receiver` and `object` might alias, so
        // TransitionElementsKindOrCheckMaps might change receiver's map.
        result = kUnreliableMaps;
        break;
      }
      case IrOpcode::kJSCreate: {
        if (IsSame(receiver, effect)) {
          OptionalMapRef initial_map = GetJSCreateMap(broker, receiver);
          if (initial_map.has_value()) {
            *maps_out = ZoneRefSet<Map>{initial_map.value()};
            return result;
          }
          // We reached the allocation of the {receiver}.
          return kNoMaps;
        }
        result = kUnreliableMaps; // JSCreate can have side-effect.
        break;
      }
      case IrOpcode::kJSCreatePromise: {
        if (IsSame(receiver, effect)) {
          *maps_out = ZoneRefSet<Map>{broker->target_native_context()
                                          .promise_function(broker)
                                          .initial_map(broker)};
          return result;
        }
        WRITE_CANNOT_CHANGE_ALIASING_MAPS();
        break;
      }
      case IrOpcode::kStoreField: {
        // We only care about StoreField of maps.
        Node* const object = GetValueInput(effect, 0);
        FieldAccess const& access = FieldAccessOf(effect->op());
        if (access.base_is_tagged == kTaggedBase &&
            access.offset == HeapObject::kMapOffset) {
          if (IsSame(receiver, object)) {
            Node* const value = GetValueInput(effect, 1);
            HeapObjectMatcher m2(value);
            if (m2.HasResolvedValue()) {
              *maps_out = ZoneRefSet<Map>{m2.Ref(broker).AsMap()};
              return result;
            }
          }
          // Without alias analysis we cannot tell whether this
          // StoreField[map] affects {receiver} or not.
          result = kUnreliableMaps;
        } else {
          WRITE_CANNOT_CHANGE_ALIASING_MAPS();
        }
        break;
      }
      case IrOpcode::kJSStoreMessage:
      case IrOpcode::kJSStoreModule:
      case IrOpcode::kStoreElement:
      case IrOpcode::kStoreTypedElement: {
        // These never change the map of objects.
        WRITE_CANNOT_CHANGE_ALIASING_MAPS();
        break;
      }
      case IrOpcode::kFinishRegion: {
        // FinishRegion renames the output of allocations, so we need
        // to update the {receiver} that we are looking for, if the
        // {receiver} matches the current {effect}.
        if (IsSame(receiver, effect)) receiver = GetValueInput(effect, 0);
        // This never change the map of objects.
        WRITE_CANNOT_CHANGE_ALIASING_MAPS();
        break;
      }
      case IrOpcode::kEffectPhi: {
        Node* control = GetControlInput(effect);
        if (control->opcode() != IrOpcode::kLoop) {
          DCHECK(control->opcode() == IrOpcode::kDead ||
                 control->opcode() == IrOpcode::kMerge);
          return kNoMaps;
        }
        // Continue search for receiver map outside the loop. Since operations
        // inside the loop may change the map, the result is unreliable.
        effect = GetEffectInput(effect, 0);
        result = kUnreliableMaps;
        continue;
      }
      default: {
        DCHECK_EQ(1, effect->op()->EffectOutputCount());
        if (effect->op()->EffectInputCount() != 1) {
          // Didn't find any appropriate CheckMaps node.
          return kNoMaps;
        }
        if (!effect->op()->HasProperty(Operator::kNoWrite)) {
          // Without alias/escape analysis we cannot tell whether this
          // {effect} affects {receiver} or not.
          result = kUnreliableMaps;
        }
        break;
      }
    }
#undef WRITE_CANNOT_CHANGE_ALIASING_MAPS
#ifdef DEBUG
    if (effect->op()->HasProperty(Operator::kNoWrite) ||
        !write_might_change_aliasing_maps) {
      DCHECK_EQ(result, prev_result);
    } else {
      DCHECK_EQ(result, kUnreliableMaps);
    }
#endif
    // Stop walking the effect chain once we hit the definition of
    // the {receiver} along the {effect}s.
    if (IsSame(receiver, effect)) return kNoMaps;
    // Continue with the next {effect}.
    DCHECK_EQ(1, effect->op()->EffectInputCount());
    effect = NodeProperties::GetEffectInput(effect);
  }
}
References v8::internal::compiler::FieldAccess::base_is_tagged, broker(), v8::internal::compiler::CheckMapsParametersOf(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::ElementsTransitionWithMultipleSourcesOf(), v8::internal::compiler::FieldAccessOf(), GetControlInput(), GetEffectInput(), GetJSCreateMap(), GetValueInput(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::initial_map, v8::internal::compiler::MapRef::is_stable(), IsSame(), v8::internal::HeapObject::kMapOffset, kNoMaps, v8::internal::compiler::Operator::kNoWrite, kReliableMaps, v8::internal::compiler::kTaggedBase, kUnreliableMaps, v8::internal::compiler::HeapObjectRef::map(), v8::internal::compiler::MapGuardMapsOf(), v8::internal::compiler::CheckMapsParameters::maps(), v8::internal::compiler::FieldAccess::offset, v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::base::internal::result, v8::internal::compiler::ElementsTransitionWithMultipleSources::target(), v8::internal::value, and WRITE_CANNOT_CHANGE_ALIASING_MAPS.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::InferHasInPrototypeChain(), v8::internal::compiler::JSNativeContextSpecialization::InferMaps(), and v8::internal::compiler::MapInference::MapInference().
IsCommon()
static bool v8::internal::compiler::NodeProperties::IsCommon (Node * node) [inline], [static]
Definition at line 108 of file node-properties.h.
                                   {
    return IrOpcode::IsCommonOpcode(node->opcode());
  }
References v8::internal::compiler::IrOpcode::IsCommonOpcode(), and v8::internal::compiler::Node::opcode().
IsConstant()
static bool v8::internal::compiler::NodeProperties::IsConstant (Node * node) [inline], [static]
Definition at line 114 of file node-properties.h.
                                     {
    return IrOpcode::IsConstantOpcode(node->opcode());
  }
References v8::internal::compiler::IrOpcode::IsConstantOpcode(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::anonymous_namespace{revectorizer.cc}::AllConstant(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::GetMemoryOffsetValue(), v8::internal::compiler::CsaLoadEliminationHelpers::IsConstantObject(), and v8::internal::compiler::ConstantFoldingReducer::Reduce().
IsContextEdge()
bool v8::internal::compiler::NodeProperties::IsContextEdge (Edge edge) [static]
Definition at line 33 of file node-properties.cc.
                                            {
  Node* const node = edge.from();
  return IsInputRange(edge, FirstContextIndex(node),
                      OperatorProperties::GetContextInputCount(node->op()));
}
References FirstContextIndex(), v8::internal::compiler::Edge::from(), v8::internal::compiler::OperatorProperties::GetContextInputCount(), IsInputRange(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::ReplaceEffectControlUses().
IsControl()
static bool v8::internal::compiler::NodeProperties::IsControl (Node * node) [inline], [static]
Definition at line 111 of file node-properties.h.
                                    {
    return IrOpcode::IsControlOpcode(node->opcode());
  }
References v8::internal::compiler::IrOpcode::IsControlOpcode(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::LinearScheduler::GetEarlySchedulePosition(), v8::internal::compiler::JSONGraphWriter::PrintNode(), and v8::internal::compiler::LinearScheduler::SameBasicBlock().
IsControlEdge()
bool v8::internal::compiler::NodeProperties::IsControlEdge (Edge edge) [static]
Definition at line 57 of file node-properties.cc.
                                            {
  Node* const node = edge.from();
  return IsInputRange(edge, FirstControlIndex(node),
                      node->op()->ControlInputCount());
}
References v8::internal::compiler::Operator::ControlInputCount(), FirstControlIndex(), v8::internal::compiler::Edge::from(), IsInputRange(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), CollectControlProjections(), v8::internal::compiler::LinearScheduler::ComputeControlLevel(), v8::internal::compiler::LoopVariableOptimizer::DetectInductionVariables(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), v8::internal::compiler::LoopPeeler::EliminateLoopExit(), FindSuccessfulControlProjection(), v8::internal::compiler::JSInliner::InlineCall(), IsExceptionalCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::ReplaceEffectControlUses(), ReplaceUses(), v8::internal::compiler::GraphReducer::ReplaceWithValue(), v8::internal::compiler::LoopVariableOptimizer::Run(), and v8::internal::compiler::ControlEquivalence::RunUndirectedDFS().
IsEffectEdge()
bool v8::internal::compiler::NodeProperties::IsEffectEdge (Edge edge) [static]
Definition at line 49 of file node-properties.cc.
                                           {
  Node* const node = edge.from();
  return IsInputRange(edge, FirstEffectIndex(node),
                      node->op()->EffectInputCount());
}
References v8::internal::compiler::Operator::EffectInputCount(), FirstEffectIndex(), v8::internal::compiler::Edge::from(), IsInputRange(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), v8::internal::compiler::MemoryOptimizer::EnqueueUses(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::RepresentationSelector::InsertUnreachableIfNecessary(), v8::internal::compiler::EffectGraphReducer::ReduceFrom(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::ReplaceEffectControlUses(), ReplaceUses(), v8::internal::compiler::GraphReducer::ReplaceWithValue(), v8::internal::compiler::UnrollLoop(), v8::internal::compiler::Revectorizer::UpdateSources(), and v8::internal::compiler::Revectorizer::VectorizeTree().
IsExceptionalCall()
bool v8::internal::compiler::NodeProperties::IsExceptionalCall (Node * node, Node ** out_exception = nullptr) [static]
Definition at line 65 of file node-properties.cc.
                                                                       {
  if (node->op()->HasProperty(Operator::kNoThrow)) return false;
  for (Edge const edge : node->use_edges()) {
    if (!NodeProperties::IsControlEdge(edge)) continue;
    if (edge.from()->opcode() == IrOpcode::kIfException) {
      if (out_exception != nullptr) *out_exception = edge.from();
      return true;
    }
  }
  return false;
}
References v8::internal::compiler::Operator::HasProperty(), IsControlEdge(), v8::internal::compiler::Operator::kNoThrow, v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::use_edges().
Referenced by v8::internal::compiler::CFGBuilder::BuildBlocks(), v8::internal::compiler::JSCallReducer::CheckIfConstructor(), v8::internal::compiler::CFGBuilder::ConnectBlocks(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), v8::internal::compiler::JSTypedLowering::GenerateStringAddition(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeApply(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSGetIterator(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceNamedAccess(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::JSCallReducer::ReduceReflectHas(), and v8::internal::compiler::JSCallReducer::ReduceStringConstructor().
IsFrameStateEdge()
bool v8::internal::compiler::NodeProperties::IsFrameStateEdge (Edge edge) [static]
Definition at line 41 of file node-properties.cc.
                                               {
  Node* const node = edge.from();
  return IsInputRange(edge, FirstFrameStateIndex(node),
                      OperatorProperties::GetFrameStateInputCount(node->op()));
}
References FirstFrameStateIndex(), v8::internal::compiler::Edge::from(), v8::internal::compiler::OperatorProperties::GetFrameStateInputCount(), IsInputRange(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::JSInliner::InlineCall().
IsInputRange()
bool v8::internal::compiler::NodeProperties::IsInputRange (Edge edge, int first, int count) [inline], [static], [private]
Definition at line 693 of file node-properties.cc.
                                                               {
  if (num == 0) return false;
  int const index = edge.index();
  return first <= index && index < first + num;
}
References v8::internal::compiler::Edge::index(), and v8::internal::index.
Referenced by IsContextEdge(), IsControlEdge(), IsEffectEdge(), IsFrameStateEdge(), and IsValueEdge().
IsPhi()
static bool v8::internal::compiler::NodeProperties::IsPhi (Node * node) [inline], [static]
Definition at line 117 of file node-properties.h.
                                {
    return IrOpcode::IsPhiOpcode(node->opcode());
  }
References v8::internal::compiler::IrOpcode::IsPhiOpcode(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::Scheduler::FuseFloatingControl(), v8::internal::compiler::LinearScheduler::GetEarlySchedulePosition(), v8::internal::compiler::LoopFinderImpl::IsBackedge(), v8::internal::compiler::LoopFinderImpl::IsLoopHeaderNode(), v8::internal::compiler::LoopFinderImpl::PropagateBackward(), v8::internal::compiler::SimplifyTFLoops::Reduce(), v8::internal::compiler::DeadCodeElimination::ReduceLoopOrMerge(), v8::internal::compiler::LoopFinderImpl::SetLoopMarkForLoopHeader(), v8::internal::compiler::SLPTree::StackTopIsPhi(), and v8::internal::compiler::UnrollLoop().
IsSame()
bool v8::internal::compiler::NodeProperties::IsSame (Node * a, Node * b) [static]
Definition at line 365 of file node-properties.cc.
                                            {
  for (;;) {
    if (a->opcode() == IrOpcode::kCheckHeapObject ||
        a->opcode() == IrOpcode::kTypeGuard) {
      a = GetValueInput(a, 0);
      continue;
    }
    if (b->opcode() == IrOpcode::kCheckHeapObject ||
        b->opcode() == IrOpcode::kTypeGuard) {
      b = GetValueInput(b, 0);
      continue;
    }
    return a == b;
  }
}
References GetValueInput(), and v8::internal::compiler::Node::opcode().
Referenced by InferMapsUnsafe().
IsTyped()
static bool v8::internal::compiler::NodeProperties::IsTyped (const Node * node) [inline], [static]
Definition at line 259 of file node-properties.h.
{ return !node->type().IsInvalid(); }
References v8::internal::compiler::Type::IsInvalid(), and v8::internal::compiler::Node::type().
Referenced by v8::internal::compiler::anonymous_namespace{wasm-typer.cc}::AllInputsTyped(), AllValueInputsAreTyped(), v8::internal::compiler::SimplifiedLoweringVerifier::CheckAndSet(), v8::internal::compiler::Verifier::Visitor::CheckNotTyped(), v8::internal::compiler::SimplifiedLoweringVerifier::CheckType(), v8::internal::compiler::Typer::Decorator::Decorate(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::JSONGraphWriter::GetType(), v8::internal::compiler::SimplifiedLoweringVerifier::GetType(), GetTypeOrAny(), v8::internal::compiler::GraphAssembler::MergeState(), v8::internal::compiler::WasmGCOperatorReducer::ObjectTypeFromContext(), v8::internal::compiler::operator<<(), v8::internal::compiler::RepresentationSelector::PrintNodeFeedbackType(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::PrintScheduledNode(), v8::internal::compiler::GraphC1Visualizer::PrintType(), v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::ProcessBlock(), v8::internal::compiler::ConstantFoldingReducer::Reduce(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet(), v8::internal::compiler::ValueNumberingReducer::ReplaceIfTypesMatch(), v8::internal::compiler::UntyperPhase::Run(), v8::internal::compiler::WasmGraphBuilder::SetType(), v8::internal::compiler::WasmLoadElimination::TruncateAndExtendOrType(), v8::internal::compiler::Typer::Visitor::TypeOrNone(), v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::TypeSubsumes(), v8::internal::compiler::Typer::Visitor::UpdateType(), and v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode().
IsValueEdge()
bool v8::internal::compiler::NodeProperties::IsValueEdge (Edge edge) [static]
Definition at line 25 of file node-properties.cc.
                                          {
  Node* const node = edge.from();
  return IsInputRange(edge, FirstValueIndex(node),
                      node->op()->ValueInputCount());
}
References FirstValueIndex(), v8::internal::compiler::Edge::from(), IsInputRange(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), CollectValueProjections(), v8::internal::compiler::Revectorizer::DecideVectorize(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::HasHeapNumberInputOrOutput(), v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::IsEscapingAllocationWitness(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::IsSafeArgumentsElements(), v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::IsStore(), v8::internal::compiler::WasmEscapeAnalysis::ReduceAllocateRaw(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInPrepare(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::MachineOperatorReducer::ReduceTruncateInt64ToInt32(), v8::internal::compiler::LateEscapeAnalysis::RemoveAllocation(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::ReplaceEffectControlUses(), v8::internal::compiler::UnrollLoop(), v8::internal::compiler::Revectorizer::UpdateSources(), and v8::internal::compiler::Revectorizer::VectorizeTree().
IsValueIdentity()
static bool v8::internal::compiler::NodeProperties::IsValueIdentity (Node * node, Node ** out_value) [inline], [static]
Definition at line 137 of file node-properties.h.
                                                            {
    switch (node->opcode()) {
      case IrOpcode::kTypeGuard:
        *out_value = GetValueInput(node, 0);
        return true;
      default:
        return false;
    }
  }
References v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::SkipValueIdentities().
MergeControlToEnd()
void v8::internal::compiler::NodeProperties::MergeControlToEnd (TFGraph * graph, CommonOperatorBuilder * common, Node * node) [static]
Definition at line 152 of file node-properties.cc.
                                                   {
  graph->end()->AppendInput(graph->zone(), node);
  graph->end()->set_op(common->End(graph->end()->InputCount()));
}
References v8::internal::compiler::CommonOperatorBuilder::End(), and graph().
Referenced by v8::internal::compiler::GraphAssembler::ConnectUnreachableToEnd(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::WasmGraphAssembler::MergeControlToEnd(), v8::internal::compiler::AdvancedReducer::MergeControlToEnd(), v8::internal::compiler::GraphAssembler::MergeState(), v8::internal::compiler::GraphAssembler::TailCall(), and v8::internal::compiler::UnrollLoop().
NoObservableSideEffectBetween()
bool v8::internal::compiler::NodeProperties::NoObservableSideEffectBetween (Node * effect, Node * dominator) [static]
Definition at line 598 of file node-properties.cc.
                                                                    {
  while (effect != dominator) {
    if (effect->op()->EffectInputCount() == 1 &&
        effect->op()->properties() & Operator::kNoWrite) {
      effect = NodeProperties::GetEffectInput(effect);
    } else {
      return false;
    }
  }
  return true;
}
References v8::internal::compiler::Operator::EffectInputCount(), GetEffectInput(), v8::internal::compiler::Operator::kNoWrite, v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::properties().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey(), and v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty().
PastContextIndex()
static int v8::internal::compiler::NodeProperties::PastContextIndex (Node * node) [inline], [static]
Definition at line 41 of file node-properties.h.
                                          {
    return FirstContextIndex(node) +
           OperatorProperties::GetContextInputCount(node->op());
  }
References v8::internal::compiler::OperatorProperties::GetContextInputCount(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::RepresentationSelector::ProcessRemainingInputs().
PastControlIndex()
static int v8::internal::compiler::NodeProperties::PastControlIndex (Node * node) [inline], [static]
Definition at line 55 of file node-properties.h.
                                          {
    return FirstControlIndex(node) + node->op()->ControlInputCount();
  }
References v8::internal::compiler::Operator::ControlInputCount(), and v8::internal::compiler::Node::op().
Referenced by v8::internal::compiler::ControlEquivalence::DetermineParticipation(), and v8::internal::compiler::CFGBuilder::Run().
PastEffectIndex()
static int v8::internal::compiler::NodeProperties::PastEffectIndex (Node * node) [inline], [static]
Definition at line 51 of file node-properties.h.
                                         {
    return FirstEffectIndex(node) + node->op()->EffectInputCount();
  }
References v8::internal::compiler::Operator::EffectInputCount(), and v8::internal::compiler::Node::op().
PastFrameStateIndex()
static int v8::internal::compiler::NodeProperties::PastFrameStateIndex (Node * node) [inline], [static]
Definition at line 46 of file node-properties.h.
                                             {
    return FirstFrameStateIndex(node) +
           OperatorProperties::GetFrameStateInputCount(node->op());
  }
References v8::internal::compiler::OperatorProperties::GetFrameStateInputCount(), and v8::internal::compiler::Node::op().
PastValueIndex()
static int v8::internal::compiler::NodeProperties::PastValueIndex (Node * node) [inline], [static]
Definition at line 37 of file node-properties.h.
                                        {
    return FirstValueIndex(node) + node->op()->ValueInputCount();
  }
References v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by v8::internal::compiler::RepresentationSelector::ProcessRemainingInputs().
RemoveControlFromEnd()
void v8::internal::compiler::NodeProperties::RemoveControlFromEnd (TFGraph * graph, CommonOperatorBuilder * common, Node * node) [static]
Definition at line 159 of file node-properties.cc.
                                                      {
  int index_to_remove = -1;
  for (int i = 0; i < graph->end()->op()->ControlInputCount(); i++) {
    int index = NodeProperties::FirstControlIndex(graph->end()) + i;
    if (graph->end()->InputAt(index) == node) {
      index_to_remove = index;
      break;
    }
  }
  CHECK_NE(-1, index_to_remove);
  graph->end()->RemoveInput(index_to_remove);
  graph->end()->set_op(common->End(graph->end()->InputCount()));
}
References CHECK_NE, v8::internal::compiler::CommonOperatorBuilder::End(), FirstControlIndex(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::index.
RemoveNonValueInputs()
void v8::internal::compiler::NodeProperties::RemoveNonValueInputs (Node * node) [static]
Definition at line 139 of file node-properties.cc.
                                                    {
  node->TrimInputCount(node->op()->ValueInputCount());
}
References v8::internal::compiler::Node::op(), v8::internal::compiler::Node::TrimInputCount(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by v8::internal::compiler::JSIntrinsicLowering::Change(), and v8::internal::compiler::JSBinopReduction::ChangeToPureOperator().
RemoveType()
static void v8::internal::compiler::NodeProperties::RemoveType (Node * node) [inline], [static]
Definition at line 269 of file node-properties.h.
{ node->set_type(Type::Invalid()); }
References v8::internal::compiler::Type::Invalid(), and v8::internal::compiler::Node::set_type().
Referenced by v8::internal::compiler::JSIntrinsicLowering::ReduceGeneratorClose(), and v8::internal::compiler::UntyperPhase::Run().
RemoveValueInputs()
void v8::internal::compiler::NodeProperties::RemoveValueInputs (Node * node) [static]
Definition at line 145 of file node-properties.cc.
                                                 {
  int value_input_count = node->op()->ValueInputCount();
  while (--value_input_count >= 0) {
    node->RemoveInput(value_input_count);
  }
}
References v8::internal::compiler::Node::op(), v8::internal::compiler::Node::RemoveInput(), and v8::internal::compiler::Operator::ValueInputCount().
ReplaceContextInput()
void v8::internal::compiler::NodeProperties::ReplaceContextInput (Node * node, Node * context) [static]
Definition at line 110 of file node-properties.cc.
                                                                  {
  CHECK(OperatorProperties::HasContextInput(node->op()));
  node->ReplaceInput(FirstContextIndex(node), context);
}
References CHECK, FirstContextIndex(), v8::internal::compiler::OperatorProperties::HasContextInput(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::ReplaceInput().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::BuildLoadNativeContextField(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContext(), v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContextNoCell(), v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContext(), and v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContextNoCell().
ReplaceControlInput()
void v8::internal::compiler::NodeProperties::ReplaceControlInput (Node * node, Node * control, int index = 0) [static]
Definition at line 117 of file node-properties.cc.
                                                                             {
  CHECK_LE(0, index);
  CHECK_LT(index, node->op()->ControlInputCount());
  node->ReplaceInput(FirstControlIndex(node) + index, control);
}
References CHECK_LE, CHECK_LT, v8::internal::compiler::Operator::ControlInputCount(), FirstControlIndex(), v8::internal::index, v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::ReplaceInput().
Referenced by v8::internal::compiler::JSCallReducer::CheckIfConstructor(), v8::internal::compiler::JSCallReducerAssembler::CopyNode(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), v8::internal::compiler::JSTypedLowering::GenerateStringAddition(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::DeadCodeElimination::ReduceEffectPhi(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), and v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally().
ReplaceEffectInput()
void v8::internal::compiler::NodeProperties::ReplaceEffectInput (Node * node, Node * effect, int index = 0) [static]
Definition at line 125 of file node-properties.cc.
                                                                           {
  CHECK_LE(0, index);
  CHECK_LT(index, node->op()->EffectInputCount());
  return node->ReplaceInput(FirstEffectIndex(node) + index, effect);
}
References CHECK_LE, CHECK_LT, v8::internal::compiler::Operator::EffectInputCount(), FirstEffectIndex(), v8::internal::index, v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::ReplaceInput().
Referenced by v8::internal::compiler::JSCallReducerAssembler::CopyNode(), v8::internal::compiler::JSInliner::DetermineCallContext(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), v8::internal::compiler::JSTypedLowering::GenerateStringAddition(), v8::internal::compiler::anonymous_namespace{revectorizer.cc}::InsertAfter(), v8::internal::compiler::anonymous_namespace{add-type-assertions-reducer.cc}::AddTypeAssertionsImpl::InsertAssertion(), v8::internal::compiler::RepresentationChanger::InsertConversion(), v8::internal::compiler::RepresentationChanger::InsertUnconditionalDeopt(), v8::internal::compiler::RawMachineAssembler::MakeReschedulable(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread(), v8::internal::compiler::DeadCodeElimination::ReduceEffectPhi(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeCall(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::CommonOperatorReducer::ReduceReturn(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeIndexOfIncludes(), v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSBinopReduction::update_effect(), v8::internal::compiler::Revectorizer::UpdateSources(), and v8::internal::compiler::Revectorizer::VectorizeTree().
ReplaceFrameStateInput()
void v8::internal::compiler::NodeProperties::ReplaceFrameStateInput (Node * node, Node * frame_state) [static]
Definition at line 133 of file node-properties.cc.
                                                                         {
  CHECK(OperatorProperties::HasFrameStateInput(node->op()));
  node->ReplaceInput(FirstFrameStateIndex(node), frame_state);
}
References CHECK, FirstFrameStateIndex(), v8::internal::compiler::OperatorProperties::HasFrameStateInput(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::ReplaceInput().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::PrepareEagerCheckpoint(), v8::internal::compiler::JSCallReducer::ReduceBigIntConstructor(), and v8::internal::compiler::JSCallReducer::ReduceNumberConstructor().
ReplaceUses()
void v8::internal::compiler::NodeProperties::ReplaceUses (Node * node, Node * value, Node * effect = nullptr, Node * success = nullptr, Node * exception = nullptr) [static]
Definition at line 176 of file node-properties.cc.
                                                                 {
  // Requires distinguishing between value, effect and control edges.
  for (Edge edge : node->use_edges()) {
    if (IsControlEdge(edge)) {
      if (edge.from()->opcode() == IrOpcode::kIfSuccess) {
        DCHECK_NOT_NULL(success);
        edge.UpdateTo(success);
      } else if (edge.from()->opcode() == IrOpcode::kIfException) {
        DCHECK_NOT_NULL(exception);
        edge.UpdateTo(exception);
      } else {
        DCHECK_NOT_NULL(success);
        edge.UpdateTo(success);
      }
    } else if (IsEffectEdge(edge)) {
      DCHECK_NOT_NULL(effect);
      edge.UpdateTo(effect);
    } else {
      DCHECK_NOT_NULL(value);
      edge.UpdateTo(value);
    }
  }
}
References DCHECK_NOT_NULL, IsControlEdge(), IsEffectEdge(), v8::internal::compiler::Node::use_edges(), and v8::internal::value.
Referenced by v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::LoopPeeler::EliminateLoopExit(), v8::internal::compiler::JSInliner::InlineCall(), v8::internal::compiler::JSInliner::ReduceJSCall(), and v8::internal::compiler::MemoryOptimizer::ReplaceUsesAndKillNode().
ReplaceValueInput()
void v8::internal::compiler::NodeProperties::ReplaceValueInput (Node * node, Node * value, int index) [static]
Definition at line 91 of file node-properties.cc.
                                                                         {
  CHECK_LE(0, index);
  CHECK_LT(index, node->op()->ValueInputCount());
  node->ReplaceInput(FirstValueIndex(node) + index, value);
}
References CHECK_LE, CHECK_LT, FirstValueIndex(), v8::internal::index, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::value, and v8::internal::compiler::Operator::ValueInputCount().
Referenced by v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::RawMachineAssembler::OptimizeControlFlow(), v8::internal::compiler::PairLoadStoreReducer::Reduce(), v8::internal::compiler::JSCallReducer::ReduceArrayConstructor(), v8::internal::compiler::MachineOperatorReducer::ReduceConditional(), v8::internal::compiler::CommonOperatorReducer::ReduceDeoptimizeConditional(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSInstanceOf(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeIsPrototypeOf(), v8::internal::compiler::DeadCodeElimination::ReducePhi(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeCatch(), v8::internal::compiler::JSCallReducer::ReducePromisePrototypeFinally(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberComparison(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberOperation(), v8::internal::compiler::NodeHashCache::Constructor::ReplaceValueInput(), v8::internal::compiler::BranchElimination::SimplifyBranchCondition(), v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike(), and v8::internal::compiler::Revectorizer::VectorizeTree().
ReplaceValueInputs()
void v8::internal::compiler::NodeProperties::ReplaceValueInputs (Node * node, Node * value) [static]
Definition at line 99 of file node-properties.cc.
                                                               {
  int value_input_count = node->op()->ValueInputCount();
  CHECK_GT(value_input_count, 0);
  node->ReplaceInput(0, value);
  while (--value_input_count > 0) {
    node->RemoveInput(value_input_count);
  }
}
References CHECK_GT, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::value, and v8::internal::compiler::Operator::ValueInputCount().
Referenced by v8::internal::compiler::JSCallReducer::ReduceBigIntConstructor(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceNumberConstructor(), and v8::internal::compiler::JSCallReducer::ReduceObjectConstructor().
SetType()
static void v8::internal::compiler::NodeProperties::SetType (Node * node, Type type) [inline], [static]
Definition at line 265 of file node-properties.h.
                                             {
    DCHECK(!type.IsInvalid());
    node->set_type(type);
  }
References v8::internal::DCHECK(), v8::internal::compiler::Node::set_type(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::CommonOperatorReducer::CommonOperatorReducer(), v8::internal::compiler::NodeHashCache::Constructor::Constructor(), v8::internal::compiler::DeadCodeElimination::DeadCodeElimination(), v8::internal::compiler::DeadCodeElimination::DeadValue(), v8::internal::compiler::Typer::Decorator::Decorate(), v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::GraphReducer::GraphReducer(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::LowerCompareMapsWithoutLoad(), v8::internal::compiler::VariableTracker::MergeInputs(), v8::internal::compiler::GraphAssembler::MergeState(), v8::internal::compiler::NodeHashCache::Constructor::MutableNode(), v8::internal::compiler::EscapeAnalysisReducer::ObjectIdNode(), v8::internal::compiler::TypeNarrowingReducer::Reduce(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::compiler::DeadCodeElimination::ReduceDeoptimizeOrReturnOrTerminateOrTailCall(), v8::internal::compiler::DeadCodeElimination::ReduceEffectNode(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSHasInPrototypeChain(), v8::internal::compiler::JSTypedLowering::ReduceJSToBigIntConvertNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumeric(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), v8::internal::compiler::JSTypedLowering::ReduceObjectIsArray(), v8::internal::compiler::TypedOptimization::ReducePhi(), v8::internal::compiler::TypedOptimization::ReduceSelect(), v8::internal::compiler::ValueNumberingReducer::ReplaceIfTypesMatch(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::RepresentationSelector::RunVerifyPhase(), v8::internal::compiler::WasmGraphBuilder::SetType(), v8::internal::compiler::WasmGCOperatorReducer::SetType(), v8::internal::compiler::WasmLoadElimination::TruncateAndExtendOrType(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::TypeNode(), and v8::internal::compiler::Typer::Visitor::UpdateType().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/node-properties.h
/mnt/V8SourceCode/src/compiler/node-properties.cc