v8::String::ExternalOneByteStringResource Class Reference
An ExternalOneByteStringResource is a wrapper around an one-byte string buffer that resides outside V8's heap.
#include <v8-primitive.h>
Public Member Functions
~ExternalOneByteStringResource () override=default
Override the destructor to manage the life cycle of the underlying buffer.
virtual const char * data () const =0
The string data from the underlying buffer.
virtual size_t length () const =0
The number of Latin-1 characters in the string.
const char * cached_data () const
Returns the cached data from the underlying buffer.
void UpdateDataCache ()
Update {cached_data_} with the data from the underlying buffer.
Protected Member Functions
ExternalOneByteStringResource ()=default
Private Member Functions
void CheckCachedDataInvariants () const
Private Attributes
const char * cached_data_ = nullptr
Additional Inherited Members
Detailed Description
An ExternalOneByteStringResource is a wrapper around an one-byte string buffer that resides outside V8's heap.
Implement an ExternalOneByteStringResource to manage the life cycle of the underlying buffer. Note that the string data must be immutable and that the data must be Latin-1 and not UTF-8, which would require special treatment internally in the engine and do not allow efficient indexing. Use String::New or convert to 16 bit data for non-Latin1.
Definition at line 444 of file v8-primitive.h.
Constructor & Destructor Documentation
 ExternalOneByteStringResource()
v8::String::ExternalOneByteStringResource::~ExternalOneByteStringResource () [override], [default]
Override the destructor to manage the life cycle of the underlying buffer.
ExternalOneByteStringResource()
v8::String::ExternalOneByteStringResource::ExternalOneByteStringResource () [protected], [default]
Member Function Documentation
cached_data()
const char* v8::String::ExternalOneByteStringResource::cached_data () const [inline]
Returns the cached data from the underlying buffer.
If the resource is uncacheable or if UpdateDataCache() was not called before, it has undefined behaviour.
Definition at line 467 of file v8-primitive.h.
                                    {
      CheckCachedDataInvariants();
      return cached_data_;
    }
CheckCachedDataInvariants()
void v8::String::ExternalOneByteStringResource::CheckCachedDataInvariants () const [private]
Definition at line 6106 of file api.cc.
                                                                          {
  DCHECK(IsCacheable() && cached_data_ != nullptr);
}
References DCHECK.
data()
virtual const char* v8::String::ExternalOneByteStringResource::data () const [pure virtual]
The string data from the underlying buffer.
If the resource is cacheable then data() must return the same value for all invocations.
Implemented in v8::ExternalOwningOneByteStringResource, and v8::anonymous_namespace{api.cc}::ExtensionResource.
Referenced by v8::String::MakeExternal(), v8::internal::String::MakeExternal(), and v8::String::NewExternalOneByte().
length()
virtual size_t v8::String::ExternalOneByteStringResource::length () const [pure virtual]
The number of Latin-1 characters in the string.
Implemented in v8::ExternalOwningOneByteStringResource, and v8::anonymous_namespace{api.cc}::ExtensionResource.
Referenced by v8::internal::String::MakeExternal(), v8::String::NewExternalOneByte(), v8::internal::Factory::NewExternalStringFromOneByte(), and v8::internal::ExternalOneByteString::SetResource().
UpdateDataCache()
void v8::String::ExternalOneByteStringResource::UpdateDataCache ()
Update {cached_data_} with the data from the underlying buffer.
This can be called only for cacheable resources.
Definition at line 6101 of file api.cc.
                                                          {
  DCHECK(IsCacheable());
  cached_data_ = data();
}
References DCHECK.
Member Data Documentation
cached_data_
const char* v8::String::ExternalOneByteStringResource::cached_data_ = nullptr [private]
Definition at line 484 of file v8-primitive.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc