v8::internal::PreparseDataBuilder Class Reference
#include <preparse-data.h>
Classes
class ByteData
class DataGatheringScope
Public Member Functions
PreparseDataBuilder (Zone *zone, PreparseDataBuilder *parent_builder, std::vector< void * > *children_buffer)
~PreparseDataBuilder ()
PreparseDataBuilder (const PreparseDataBuilder &)=delete
PreparseDataBuilder & operator= (const PreparseDataBuilder &)=delete
PreparseDataBuilder * parent () const
void SaveScopeAllocationData (DeclarationScope *scope, Parser *parser)
void Bailout ()
bool bailed_out () const
bool HasInnerFunctions () const
bool HasData () const
bool HasDataForParent () const
Static Public Member Functions
static bool ScopeNeedsData (Scope *scope)
Private Member Functions
Handle< PreparseData > Serialize (Isolate *isolate)
Handle< PreparseData > Serialize (LocalIsolate *isolate)
ZonePreparseData * Serialize (Zone *zone)
void FinalizeChildren (Zone *zone)
void AddChild (PreparseDataBuilder *child)
void SaveDataForScope (Scope *scope)
void SaveDataForVariable (Variable *var)
void SaveDataForInnerScopes (Scope *scope)
bool SaveDataForSkippableFunction (PreparseDataBuilder *builder)
void CopyByteData (Zone *zone)
Private Attributes
PreparseDataBuilder * parent_
ByteData byte_data_
xx xx xx xx xx xx xx xx xx
union {
 ScopedPtrList< PreparseDataBuilder > children_buffer_
 base::Vector< PreparseDataBuilder * > children_
};
DeclarationScope * function_scope_
int function_length_
int num_inner_functions_
int num_inner_with_data_
bool bailed_out_: 1
bool has_data_: 1
Friends
class BuilderProducedPreparseData
Additional Inherited Members
Detailed Description
Definition at line 96 of file preparse-data.h.
Constructor & Destructor Documentation
PreparseDataBuilder() [1/2]
v8::internal::PreparseDataBuilder::PreparseDataBuilder (Zone * zone, PreparseDataBuilder * parent_builder, std::vector< void * > * children_buffer) [explicit]
Definition at line 92 of file preparse-data.cc.
    : parent_(parent_builder),
      byte_data_(),
      children_buffer_(children_buffer),
      function_scope_(nullptr),
      function_length_(-1),
      num_inner_functions_(0),
      num_inner_with_data_(0),
      bailed_out_(false),
      has_data_(false) {}
 PreparseDataBuilder()
v8::internal::PreparseDataBuilder::~PreparseDataBuilder () [inline]
Definition at line 103 of file preparse-data.h.
{}
PreparseDataBuilder() [2/2]
v8::internal::PreparseDataBuilder::PreparseDataBuilder (const PreparseDataBuilder &) [delete]
Member Function Documentation
AddChild()
void v8::internal::PreparseDataBuilder::AddChild (PreparseDataBuilder * child) [private]
Definition at line 252 of file preparse-data.cc.
                                                             {
  DCHECK(!finalized_children_);
  children_buffer_.Add(child);
}
References children_buffer_, and v8::internal::DCHECK().
Referenced by v8::internal::PreparseDataBuilder::DataGatheringScope::Close().
bailed_out()
bool v8::internal::PreparseDataBuilder::bailed_out () const [inline]
Definition at line 194 of file preparse-data.h.
{ return bailed_out_; }
Bailout()
void v8::internal::PreparseDataBuilder::Bailout () [inline]
Definition at line 187 of file preparse-data.h.
                 {
    bailed_out_ = true;
    // We don't need to call Bailout on existing / future children: the only way
    // to try to retrieve their data is through calling Serialize on the parent,
    // and if the parent is bailed out, it won't call Serialize on its children.
  }
Referenced by v8::internal::PreParser::BuildParameterInitializationBlock().
CopyByteData()
void v8::internal::PreparseDataBuilder::CopyByteData (Zone * zone) [private]
FinalizeChildren()
void v8::internal::PreparseDataBuilder::FinalizeChildren (Zone * zone) [private]
Definition at line 257 of file preparse-data.cc.
                                                     {
  DCHECK(!finalized_children_);
  base::Vector<PreparseDataBuilder*> children =
      CloneVector(zone, children_buffer_.ToConstVector());
  children_buffer_.Rewind();
  children_ = children;
#ifdef DEBUG
  finalized_children_ = true;
#endif
}
References children_, children_buffer_, v8::internal::CloneVector(), and v8::internal::DCHECK().
Referenced by v8::internal::PreparseDataBuilder::DataGatheringScope::Close().
HasData()
bool v8::internal::PreparseDataBuilder::HasData () const
Definition at line 246 of file preparse-data.cc.
{ return !bailed_out_ && has_data_; }
References bailed_out_, and has_data_.
Referenced by v8::internal::BuilderProducedPreparseData::BuilderProducedPreparseData(), HasDataForParent(), v8::internal::PreParser::PreParseFunction(), SaveDataForSkippableFunction(), and Serialize().
HasDataForParent()
bool v8::internal::PreparseDataBuilder::HasDataForParent () const
Definition at line 248 of file preparse-data.cc.
                                                 {
  return HasData() || function_scope_ != nullptr;
}
References function_scope_, and HasData().
HasInnerFunctions()
bool v8::internal::PreparseDataBuilder::HasInnerFunctions () const
Definition at line 242 of file preparse-data.cc.
                                                  {
  return !children_.empty();
}
References children_.
Referenced by SaveScopeAllocationData().
operator=()
PreparseDataBuilder& v8::internal::PreparseDataBuilder::operator= (const PreparseDataBuilder &) [delete]
parent()
PreparseDataBuilder* v8::internal::PreparseDataBuilder::parent () const [inline]
Definition at line 107 of file preparse-data.h.
{ return parent_; }
Referenced by v8::internal::PreParser::BuildParameterInitializationBlock(), and v8::internal::PreparseDataBuilder::DataGatheringScope::Close().
SaveDataForInnerScopes()
void v8::internal::PreparseDataBuilder::SaveDataForInnerScopes (Scope * scope) [private]
Definition at line 413 of file preparse-data.cc.
                                                             {
  // Inner scopes are stored in the reverse order, but we'd like to write the
  // data in the logical order. There might be many inner scopes, so we don't
  // want to recurse here.
  for (Scope* inner = scope->inner_scope(); inner != nullptr;
       inner = inner->sibling()) {
    if (inner->IsSkippableFunctionScope()) {
      // Don't save data about function scopes, since they'll have their own
      // PreparseDataBuilder where their data is saved.
      DCHECK_NOT_NULL(inner->AsDeclarationScope()->preparse_data_builder());
      continue;
    }
    if (!ScopeNeedsData(inner)) continue;
    SaveDataForScope(inner);
  }
}
References DCHECK_NOT_NULL, v8::internal::Scope::inner_scope(), SaveDataForScope(), ScopeNeedsData(), and v8::internal::Scope::sibling().
Referenced by SaveDataForScope().
SaveDataForScope()
void v8::internal::PreparseDataBuilder::SaveDataForScope (Scope * scope) [private]
Definition at line 356 of file preparse-data.cc.
                                                       {
  DCHECK_NE(scope->end_position(), kNoSourcePosition);
  DCHECK(ScopeNeedsData(scope));
#ifdef DEBUG
  byte_data_.Reserve(kUint8Size);
  byte_data_.WriteUint8(scope->scope_type());
#endif
  uint8_t scope_data_flags =
      ScopeSloppyEvalCanExtendVarsBit::encode(
          scope->is_declaration_scope() &&
          scope->AsDeclarationScope()->sloppy_eval_can_extend_vars()) |
      InnerScopeCallsEvalField::encode(scope->inner_scope_calls_eval()) |
      NeedsPrivateNameContextChainRecalcField::encode(
          scope->is_function_scope() &&
          scope->AsDeclarationScope()
              ->needs_private_name_context_chain_recalc()) |
      ShouldSaveClassVariableIndexField::encode(
          scope->is_class_scope() &&
          scope->AsClassScope()->should_save_class_variable());
  byte_data_.Reserve(kUint8Size);
  byte_data_.WriteUint8(scope_data_flags);
  if (scope->is_function_scope()) {
    Variable* function = scope->AsDeclarationScope()->function_var();
    if (function != nullptr) SaveDataForVariable(function);
  }
  for (Variable* var : *scope->locals()) {
    if (IsSerializableVariableMode(var->mode())) SaveDataForVariable(var);
  }
  SaveDataForInnerScopes(scope);
}
References v8::internal::Scope::AsClassScope(), v8::internal::Scope::AsDeclarationScope(), byte_data_, v8::internal::DCHECK(), DCHECK_NE, v8::internal::Scope::end_position(), v8::internal::DeclarationScope::function_var(), v8::internal::Scope::inner_scope_calls_eval(), v8::internal::Scope::is_class_scope(), v8::internal::Scope::is_declaration_scope(), v8::internal::Scope::is_function_scope(), v8::internal::IsSerializableVariableMode(), v8::internal::kNoSourcePosition, v8::internal::PreparseByteDataConstants::kUint8Size, v8::internal::Scope::locals(), v8::internal::DeclarationScope::needs_private_name_context_chain_recalc(), v8::internal::PreparseDataBuilder::ByteData::Reserve(), SaveDataForInnerScopes(), SaveDataForVariable(), v8::internal::Scope::scope_type(), ScopeNeedsData(), v8::internal::ClassScope::should_save_class_variable(), v8::internal::DeclarationScope::sloppy_eval_can_extend_vars(), and v8::internal::PreparseDataBuilder::ByteData::WriteUint8().
Referenced by SaveDataForInnerScopes(), and SaveScopeAllocationData().
SaveDataForSkippableFunction()
bool v8::internal::PreparseDataBuilder::SaveDataForSkippableFunction (PreparseDataBuilder * builder) [private]
Definition at line 286 of file preparse-data.cc.
                                  {
  DeclarationScope* function_scope = builder->function_scope_;
  // Start position is used for a sanity check when consuming the data, we could
  // remove it in the future if we're very pressed for space but it's been good
  // at catching bugs in the wild so far.
  byte_data_.WriteVarint32(function_scope->start_position());
  byte_data_.WriteVarint32(function_scope->end_position());
  bool has_data = builder->HasData();
  bool length_equals_parameters =
      function_scope->num_parameters() == builder->function_length_;
  uint32_t has_data_and_num_parameters =
      HasDataField::encode(has_data) |
      LengthEqualsParametersField::encode(length_equals_parameters) |
      NumberOfParametersField::encode(function_scope->num_parameters());
  byte_data_.WriteVarint32(has_data_and_num_parameters);
  if (!length_equals_parameters) {
    byte_data_.WriteVarint32(builder->function_length_);
  }
  byte_data_.WriteVarint32(builder->num_inner_functions_);
  uint8_t language_and_super =
      LanguageField::encode(function_scope->language_mode()) |
      UsesSuperField::encode(function_scope->uses_super_property());
  byte_data_.WriteQuarter(language_and_super);
  return has_data;
}
References byte_data_, v8::internal::Scope::end_position(), function_length_, function_scope_, HasData(), v8::internal::Scope::language_mode(), num_inner_functions_, v8::internal::DeclarationScope::num_parameters(), v8::internal::Scope::start_position(), v8::internal::DeclarationScope::uses_super_property(), v8::internal::PreparseDataBuilder::ByteData::WriteQuarter(), and v8::internal::PreparseDataBuilder::ByteData::WriteVarint32().
Referenced by SaveScopeAllocationData().
SaveDataForVariable()
void v8::internal::PreparseDataBuilder::SaveDataForVariable (Variable * var) [private]
Definition at line 392 of file preparse-data.cc.
                                                           {
#ifdef DEBUG
  // Store the variable name in debug mode; this way we can check that we
  // restore data to the correct variable.
  const AstRawString* name = var->raw_name();
  byte_data_.Reserve(kUint32Size + (name->length() + 1) * kUint8Size);
  byte_data_.WriteUint8(name->is_one_byte());
  byte_data_.WriteUint32(name->length());
  for (int i = 0; i < name->length(); ++i) {
    byte_data_.WriteUint8(name->raw_data()[i]);
  }
#endif
  uint8_t variable_data = VariableMaybeAssignedField::encode(
                              var->maybe_assigned() == kMaybeAssigned) |
                          VariableContextAllocatedField::encode(
                              var->has_forced_context_allocation());
  byte_data_.Reserve(kUint8Size);
  byte_data_.WriteQuarter(variable_data);
}
References byte_data_, v8::internal::Variable::has_forced_context_allocation(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kMaybeAssigned, v8::internal::PreparseByteDataConstants::kUint32Size, v8::internal::PreparseByteDataConstants::kUint8Size, v8::internal::Variable::maybe_assigned(), v8::internal::name, v8::internal::Variable::raw_name(), v8::internal::PreparseDataBuilder::ByteData::Reserve(), v8::internal::PreparseDataBuilder::ByteData::WriteQuarter(), and v8::internal::PreparseDataBuilder::ByteData::WriteUint8().
Referenced by SaveDataForScope().
SaveScopeAllocationData()
void v8::internal::PreparseDataBuilder::SaveScopeAllocationData (DeclarationScope * scope, Parser * parser)
Definition at line 315 of file preparse-data.cc.
                                                                  {
  if (!has_data_) return;
  DCHECK(HasInnerFunctions());
  byte_data_.Start(parser->preparse_data_buffer());
#ifdef DEBUG
  // Reserve Uint32 for scope_data_start debug info.
  byte_data_.Reserve(kUint32Size);
  byte_data_.WriteUint32(0);
#endif
  byte_data_.Reserve(children_.size() * kSkippableFunctionMaxDataSize);
  DCHECK(finalized_children_);
  for (const auto& builder : children_) {
    // Keep track of functions with inner data. {children_} contains also the
    // builders that have no inner functions at all.
    if (SaveDataForSkippableFunction(builder)) num_inner_with_data_++;
  }
  // Don't save incomplete scope information when bailed out.
  if (!bailed_out_) {
#ifdef DEBUG
  // function data items, kSkippableMinFunctionDataSize each.
  CHECK_GE(byte_data_.length(), kPlaceholderSize);
  CHECK_LE(byte_data_.length(), std::numeric_limits<uint32_t>::max());
  byte_data_.SaveCurrentSizeAtFirstUint32();
  // For a data integrity check, write a value between data about skipped
  // inner funcs and data about variables.
  byte_data_.Reserve(kUint32Size * 3);
  byte_data_.WriteUint32(kMagicValue);
  byte_data_.WriteUint32(scope->start_position());
  byte_data_.WriteUint32(scope->end_position());
#endif
  if (ScopeNeedsData(scope)) SaveDataForScope(scope);
  }
  byte_data_.Finalize(parser->factory()->zone());
}
References bailed_out_, byte_data_, CHECK_GE, CHECK_LE, children_, v8::internal::DCHECK(), v8::internal::Scope::end_position(), v8::internal::PreparseDataBuilder::ByteData::Finalize(), has_data_, HasInnerFunctions(), v8::internal::PreparseByteDataConstants::kPlaceholderSize, v8::internal::PreparseByteDataConstants::kSkippableFunctionMaxDataSize, v8::internal::PreparseByteDataConstants::kUint32Size, v8::internal::PreparseDataBuilder::ByteData::length(), num_inner_with_data_, v8::internal::Parser::preparse_data_buffer(), v8::internal::PreparseDataBuilder::ByteData::Reserve(), SaveDataForScope(), SaveDataForSkippableFunction(), ScopeNeedsData(), v8::internal::PreparseDataBuilder::ByteData::Start(), and v8::internal::Scope::start_position().
ScopeNeedsData()
bool v8::internal::PreparseDataBuilder::ScopeNeedsData (Scope * scope) [static]
Definition at line 268 of file preparse-data.cc.
                                                     {
  if (scope->is_function_scope()) {
    // Default constructors don't need data (they cannot contain inner functions
    // defined by the user). Other functions do.
    return !IsDefaultConstructor(scope->AsDeclarationScope()->function_kind());
  }
  if (!scope->is_hidden()) {
    for (Variable* var : *scope->locals()) {
      if (IsSerializableVariableMode(var->mode())) return true;
    }
  }
  for (Scope* inner = scope->inner_scope(); inner != nullptr;
       inner = inner->sibling()) {
    if (ScopeNeedsData(inner)) return true;
  }
  return false;
}
References v8::internal::Scope::AsDeclarationScope(), v8::internal::DeclarationScope::function_kind(), v8::internal::Scope::inner_scope(), v8::internal::Scope::is_function_scope(), v8::internal::Scope::is_hidden(), v8::internal::IsDefaultConstructor(), v8::internal::IsSerializableVariableMode(), v8::internal::Scope::locals(), and v8::internal::Scope::sibling().
Referenced by v8::internal::BaseConsumedPreparseData< Data >::RestoreDataForScope(), SaveDataForInnerScopes(), SaveDataForScope(), and SaveScopeAllocationData().
Serialize() [1/3]
Handle< PreparseData > v8::internal::PreparseDataBuilder::Serialize (Isolate * isolate) [private]
Definition at line 451 of file preparse-data.cc.
                                                                    {
  DCHECK(HasData());
  DCHECK(!ThisOrParentBailedOut());
  Handle<PreparseData> data =
      byte_data_.CopyToHeap(isolate, num_inner_with_data_);
  int i = 0;
  DCHECK(finalized_children_);
  for (const auto& builder : children_) {
    if (!builder->HasData()) continue;
    DirectHandle<PreparseData> child_data = builder->Serialize(isolate);
    data->set_child(i++, *child_data);
  }
  DCHECK_EQ(i, data->children_length());
  return data;
}
References byte_data_, children_, v8::internal::PreparseDataBuilder::ByteData::CopyToHeap(), v8::internal::DCHECK(), DCHECK_EQ, HasData(), and num_inner_with_data_.
Serialize() [2/3]
Handle< PreparseData > v8::internal::PreparseDataBuilder::Serialize (LocalIsolate * isolate) [private]
Definition at line 467 of file preparse-data.cc.
                                                                         {
  DCHECK(HasData());
  DCHECK(!ThisOrParentBailedOut());
  Handle<PreparseData> data =
      byte_data_.CopyToLocalHeap(isolate, num_inner_with_data_);
  int i = 0;
  DCHECK(finalized_children_);
  for (const auto& builder : children_) {
    if (!builder->HasData()) continue;
    DirectHandle<PreparseData> child_data = builder->Serialize(isolate);
    data->set_child(i++, *child_data);
  }
  DCHECK_EQ(i, data->children_length());
  return data;
}
References byte_data_, children_, v8::internal::PreparseDataBuilder::ByteData::CopyToLocalHeap(), v8::internal::DCHECK(), DCHECK_EQ, HasData(), and num_inner_with_data_.
Serialize() [3/3]
ZonePreparseData * v8::internal::PreparseDataBuilder::Serialize (Zone * zone) [private]
Definition at line 483 of file preparse-data.cc.
                                                           {
  DCHECK(HasData());
  DCHECK(!ThisOrParentBailedOut());
  ZonePreparseData* data = byte_data_.CopyToZone(zone, num_inner_with_data_);
  int i = 0;
  DCHECK(finalized_children_);
  for (const auto& builder : children_) {
    if (!builder->HasData()) continue;
    ZonePreparseData* child = builder->Serialize(zone);
    data->set_child(i++, child);
  }
  DCHECK_EQ(i, data->children_length());
  return data;
}
References byte_data_, children_, v8::internal::ZonePreparseData::children_length(), v8::internal::PreparseDataBuilder::ByteData::CopyToZone(), v8::internal::DCHECK(), DCHECK_EQ, HasData(), num_inner_with_data_, v8::internal::ZonePreparseData::Serialize(), and v8::internal::ZonePreparseData::set_child().
Friends And Related Function Documentation
BuilderProducedPreparseData
friend class BuilderProducedPreparseData [friend]
Definition at line 211 of file preparse-data.h.
Member Data Documentation
union { ... } [private]
bailed_out_
bool v8::internal::PreparseDataBuilder::bailed_out_ [private]
Definition at line 240 of file preparse-data.h.
Referenced by HasData(), and SaveScopeAllocationData().
byte_data_
ByteData v8::internal::PreparseDataBuilder::byte_data_ [private]
Definition at line 228 of file preparse-data.h.
Referenced by v8::internal::PreparseDataBuilder::ByteData::Add(), v8::internal::PreparseDataBuilder::ByteData::Finalize(), v8::internal::PreparseDataBuilder::ByteData::Reserve(), SaveDataForScope(), SaveDataForSkippableFunction(), SaveDataForVariable(), SaveScopeAllocationData(), Serialize(), v8::internal::PreparseDataBuilder::ByteData::Start(), and v8::internal::PreparseDataBuilder::ByteData::WriteQuarter().
children_
base::Vector<PreparseDataBuilder*> v8::internal::PreparseDataBuilder::children_
Definition at line 231 of file preparse-data.h.
Referenced by FinalizeChildren(), HasInnerFunctions(), SaveScopeAllocationData(), and Serialize().
children_buffer_
ScopedPtrList<PreparseDataBuilder> v8::internal::PreparseDataBuilder::children_buffer_
Definition at line 230 of file preparse-data.h.
Referenced by AddChild(), and FinalizeChildren().
function_length_
int v8::internal::PreparseDataBuilder::function_length_ [private]
Definition at line 235 of file preparse-data.h.
Referenced by SaveDataForSkippableFunction().
function_scope_
DeclarationScope* v8::internal::PreparseDataBuilder::function_scope_ [private]
Definition at line 234 of file preparse-data.h.
Referenced by HasDataForParent(), and SaveDataForSkippableFunction().
has_data_
bool v8::internal::PreparseDataBuilder::has_data_ [private]
Definition at line 241 of file preparse-data.h.
Referenced by HasData(), and SaveScopeAllocationData().
num_inner_functions_
int v8::internal::PreparseDataBuilder::num_inner_functions_ [private]
Definition at line 236 of file preparse-data.h.
Referenced by SaveDataForSkippableFunction().
num_inner_with_data_
int v8::internal::PreparseDataBuilder::num_inner_with_data_ [private]
Definition at line 237 of file preparse-data.h.
Referenced by SaveScopeAllocationData(), and Serialize().
parent_
PreparseDataBuilder* v8::internal::PreparseDataBuilder::parent_ [private]
Definition at line 227 of file preparse-data.h.
Referenced by v8::internal::PreparseDataBuilder::DataGatheringScope::Close().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/preparse-data.h
/mnt/V8SourceCode/src/parsing/preparse-data.cc