v8::internal::HandlerBuiltinsAssembler Class Reference
Public Member Functions
HandlerBuiltinsAssembler (compiler::CodeAssemblerState *state)
Protected Types
using ElementsKindSwitchCase = std::function< void(ElementsKind)>
using ElementsKindTransitionSwitchCase = std::function< void(ElementsKind, ElementsKind)>
Protected Member Functions
void Generate_KeyedStoreIC_SloppyArguments ()
void DispatchByElementsKind (TNode< Int32T > elements_kind, const ElementsKindSwitchCase &case_function, bool handle_typed_elements_kind)
void DispatchForElementsKindTransition (TNode< Int32T > from_kind, TNode< Int32T > to_kind, const ElementsKindTransitionSwitchCase &case_function)
void Generate_ElementsTransitionAndStore (KeyedAccessStoreMode store_mode)
void Generate_StoreFastElementIC (KeyedAccessStoreMode store_mode)
Additional Inherited Members
Detailed Description
Definition at line 18 of file builtins-handler-gen.cc.
Member Typedef Documentation
ElementsKindSwitchCase
using v8::internal::HandlerBuiltinsAssembler::ElementsKindSwitchCase = std::function<void(ElementsKind)> [protected]
Definition at line 30 of file builtins-handler-gen.cc.
ElementsKindTransitionSwitchCase
using v8::internal::HandlerBuiltinsAssembler::ElementsKindTransitionSwitchCase = std::function<void(ElementsKind, ElementsKind)> [protected]
Definition at line 36 of file builtins-handler-gen.cc.
Constructor & Destructor Documentation
HandlerBuiltinsAssembler()
v8::internal::HandlerBuiltinsAssembler::HandlerBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 20 of file builtins-handler-gen.cc.
      : CodeStubAssembler(state) {}
Member Function Documentation
DispatchByElementsKind()
void v8::internal::HandlerBuiltinsAssembler::DispatchByElementsKind (TNode< Int32T > elements_kind, const ElementsKindSwitchCase & case_function, bool handle_typed_elements_kind) [protected]
Definition at line 235 of file builtins-handler-gen.cc.
                                     {
  Label next(this), if_unknown_type(this, Label::kDeferred);
  int32_t elements_kinds[] = {
#define ELEMENTS_KINDS_CASE(KIND) KIND,
      ELEMENTS_KINDS(ELEMENTS_KINDS_CASE)
#undef ELEMENTS_KINDS_CASE
  };
#define ELEMENTS_KINDS_CASE(KIND) Label if_##KIND(this);
  ELEMENTS_KINDS(ELEMENTS_KINDS_CASE)
#undef ELEMENTS_KINDS_CASE
  Label* elements_kind_labels[] = {
#define ELEMENTS_KINDS_CASE(KIND) &if_##KIND,
      ELEMENTS_KINDS(ELEMENTS_KINDS_CASE)
#undef ELEMENTS_KINDS_CASE
  };
  static_assert(arraysize(elements_kinds) == arraysize(elements_kind_labels));
  // TODO(mythria): Do not emit cases for typed elements kind when
  // handle_typed_elements is false to decrease the size of the jump table.
  Switch(elements_kind, &if_unknown_type, elements_kinds, elements_kind_labels,
         arraysize(elements_kinds));
#define ELEMENTS_KINDS_CASE(KIND) \
  BIND(&if_##KIND); \
  { \
    if (!handle_typed_elements_kind && \
        IsTypedArrayOrRabGsabTypedArrayElementsKind(KIND)) { \
      Unreachable(); \
    } else { \
      case_function(KIND); \
      Goto(&next); \
    } \
  }
  ELEMENTS_KINDS(ELEMENTS_KINDS_CASE)
#undef ELEMENTS_KINDS_CASE
  BIND(&if_unknown_type);
  Unreachable();
  BIND(&next);
}
References arraysize, ELEMENTS_KINDS, ELEMENTS_KINDS_CASE, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::compiler::CodeAssembler::Switch(), and v8::internal::compiler::CodeAssembler::Unreachable().
Referenced by Generate_StoreFastElementIC().
DispatchForElementsKindTransition()
void v8::internal::HandlerBuiltinsAssembler::DispatchForElementsKindTransition (TNode< Int32T > from_kind, TNode< Int32T > to_kind, const ElementsKindTransitionSwitchCase & case_function) [protected]
Definition at line 93 of file builtins-handler-gen.cc.
                                                           {
  static_assert(sizeof(ElementsKind) == sizeof(uint8_t));
  Label next(this), if_unknown_type(this, Label::kDeferred);
  int32_t combined_elements_kinds[] = {
#define ELEMENTS_KINDS_CASE(FROM, TO) (FROM << kBitsPerByte) | TO,
      ELEMENTS_KIND_TRANSITIONS(ELEMENTS_KINDS_CASE)
#undef ELEMENTS_KINDS_CASE
  };
#define ELEMENTS_KINDS_CASE(FROM, TO) Label if_##FROM##_##TO(this);
  ELEMENTS_KIND_TRANSITIONS(ELEMENTS_KINDS_CASE)
#undef ELEMENTS_KINDS_CASE
  Label* elements_kind_labels[] = {
#define ELEMENTS_KINDS_CASE(FROM, TO) &if_##FROM##_##TO,
      ELEMENTS_KIND_TRANSITIONS(ELEMENTS_KINDS_CASE)
#undef ELEMENTS_KINDS_CASE
  };
  static_assert(arraysize(combined_elements_kinds) ==
                arraysize(elements_kind_labels));
  TNode<Int32T> combined_elements_kind =
      Word32Or(Word32Shl(from_kind, Int32Constant(kBitsPerByte)), to_kind);
  Switch(combined_elements_kind, &if_unknown_type, combined_elements_kinds,
         elements_kind_labels, arraysize(combined_elements_kinds));
#define ELEMENTS_KINDS_CASE(FROM, TO) \
  BIND(&if_##FROM##_##TO); \
  { \
    case_function(FROM, TO); \
    Goto(&next); \
  }
  ELEMENTS_KIND_TRANSITIONS(ELEMENTS_KINDS_CASE)
#undef ELEMENTS_KINDS_CASE
  BIND(&if_unknown_type);
  Unreachable();
  BIND(&next);
}
References arraysize, ELEMENTS_KIND_TRANSITIONS, ELEMENTS_KINDS_CASE, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::kBitsPerByte, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::compiler::CodeAssembler::Switch(), v8::internal::compiler::CodeAssembler::Unreachable(), v8::internal::compiler::CodeAssembler::Word32Or(), and v8::internal::compiler::CodeAssembler::Word32Shl().
Referenced by Generate_ElementsTransitionAndStore().
Generate_ElementsTransitionAndStore()
void v8::internal::HandlerBuiltinsAssembler::Generate_ElementsTransitionAndStore (KeyedAccessStoreMode store_mode) [protected]
Definition at line 141 of file builtins-handler-gen.cc.
                                     {
  using Descriptor = StoreTransitionDescriptor;
  auto receiver = Parameter<JSObject>(Descriptor::kReceiver);
  auto key = Parameter<Object>(Descriptor::kName);
  auto value = Parameter<Object>(Descriptor::kValue);
  auto map = Parameter<Map>(Descriptor::kMap);
  auto slot = Parameter<Smi>(Descriptor::kSlot);
  auto vector = Parameter<FeedbackVector>(Descriptor::kVector);
  auto context = Parameter<Context>(Descriptor::kContext);
  Comment("ElementsTransitionAndStore: store_mode=", store_mode);
  Label miss(this);
  if (v8_flags.trace_elements_transitions) {
    // Tracing elements transitions is the job of the runtime.
    Goto(&miss);
  } else {
    // TODO(v8:8481): Pass from_kind and to_kind in feedback vector slots.
    DispatchForElementsKindTransition(
        LoadElementsKind(receiver), LoadMapElementsKind(map),
        [=, this, &miss](ElementsKind from_kind, ElementsKind to_kind) {
          TransitionElementsKind(receiver, map, from_kind, to_kind, &miss);
          EmitElementStore(receiver, key, value, to_kind, store_mode, &miss,
                           context, nullptr);
        });
    Return(value);
  }
  BIND(&miss);
  TailCallRuntime(Runtime::kElementsTransitionAndStoreIC_Miss, context,
                  receiver, key, value, map, slot, vector);
}
References v8::internal::compiler::CodeAssembler::Comment(), DispatchForElementsKindTransition(), v8::internal::CodeStubAssembler::EmitElementStore(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::key, v8::internal::anonymous_namespace{ic.cc}::kName, v8::internal::CodeStubAssembler::LoadElementsKind(), v8::internal::CodeStubAssembler::LoadMapElementsKind(), v8::internal::compiler::CodeAssembler::Return(), v8::internal::compiler::CodeAssembler::TailCallRuntime(), v8::internal::CodeStubAssembler::TransitionElementsKind(), v8::internal::v8_flags, and v8::internal::value.
Generate_KeyedStoreIC_SloppyArguments()
void v8::internal::HandlerBuiltinsAssembler::Generate_KeyedStoreIC_SloppyArguments () [protected]
Definition at line 403 of file builtins-handler-gen.cc.
                                                                     {
  using Descriptor = StoreWithVectorDescriptor;
  auto receiver = Parameter<JSObject>(Descriptor::kReceiver);
  auto key = Parameter<Object>(Descriptor::kName);
  auto value = Parameter<JSAny>(Descriptor::kValue);
  auto slot = Parameter<Smi>(Descriptor::kSlot);
  auto vector = Parameter<HeapObject>(Descriptor::kVector);
  auto context = Parameter<Context>(Descriptor::kContext);
  Label miss(this);
  SloppyArgumentsStore(receiver, key, value, &miss);
  Return(value);
  BIND(&miss);
  TailCallRuntime(Runtime::kKeyedStoreIC_Miss, context, value, slot, vector,
                  receiver, key);
}
References v8::internal::key, v8::internal::anonymous_namespace{ic.cc}::kName, v8::internal::compiler::CodeAssembler::Return(), v8::internal::compiler::CodeAssembler::TailCallRuntime(), and v8::internal::value.
Generate_StoreFastElementIC()
void v8::internal::HandlerBuiltinsAssembler::Generate_StoreFastElementIC (KeyedAccessStoreMode store_mode) [protected]
Definition at line 284 of file builtins-handler-gen.cc.
                                     {
  using Descriptor = StoreWithVectorDescriptor;
  auto receiver = Parameter<JSObject>(Descriptor::kReceiver);
  auto key = Parameter<Object>(Descriptor::kName);
  auto value = Parameter<Object>(Descriptor::kValue);
  auto slot = Parameter<Smi>(Descriptor::kSlot);
  auto vector = Parameter<HeapObject>(Descriptor::kVector);
  auto context = Parameter<Context>(Descriptor::kContext);
  Comment("StoreFastElementStub: store_mode=", store_mode);
  Label miss(this);
  // For typed arrays maybe_converted_value contains the value obtained after
  // calling ToNumber. We should pass the converted value to the runtime to
  // avoid doing the user visible conversion again.
  TVARIABLE(Object, maybe_converted_value, value);
  // TODO(v8:8481): Pass elements_kind in feedback vector slots.
  DispatchByElementsKind(
      LoadElementsKind(receiver),
      [=, this, &miss, &maybe_converted_value](ElementsKind elements_kind) {
        EmitElementStore(receiver, key, value, elements_kind, store_mode, &miss,
                         context, &maybe_converted_value);
      },
      StoreModeSupportsTypeArray(store_mode));
  Return(value);
  BIND(&miss);
  TailCallRuntime(Runtime::kKeyedStoreIC_Miss, context,
                  maybe_converted_value.value(), slot, vector, receiver, key);
}
References v8::internal::compiler::CodeAssembler::Comment(), DispatchByElementsKind(), v8::internal::CodeStubAssembler::EmitElementStore(), v8::internal::key, v8::internal::anonymous_namespace{ic.cc}::kName, v8::internal::CodeStubAssembler::LoadElementsKind(), v8::internal::compiler::CodeAssembler::Return(), v8::internal::StoreModeSupportsTypeArray(), v8::internal::compiler::CodeAssembler::TailCallRuntime(), and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-handler-gen.cc