v8::internal::EvacuationWeakObjectRetainer Class Reference
Public Member Functions
Tagged< Object > RetainAs (Tagged< Object > object) override
Detailed Description
Definition at line 5040 of file mark-compact.cc.
Member Function Documentation
RetainAs()
Tagged<Object> v8::internal::EvacuationWeakObjectRetainer::RetainAs (Tagged< Object > object) [inline], [override], [virtual]
Implements v8::internal::WeakObjectRetainer.
Definition at line 5042 of file mark-compact.cc.
                                                          {
    if (object.IsHeapObject()) {
      Tagged<HeapObject> heap_object = Cast<HeapObject>(object);
      MapWord map_word = heap_object->map_word(kRelaxedLoad);
      if (map_word.IsForwardingAddress()) {
        return map_word.ToForwardingAddress(heap_object);
      }
    }
    return object;
  }
References v8::internal::MapWord::IsForwardingAddress(), v8::internal::InstanceTypeChecker::IsHeapObject(), v8::kRelaxedLoad, and v8::internal::MapWord::ToForwardingAddress().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc