v8::internal::compiler::turboshaft::ScopeCounter Class Reference
#include <value-numbering-reducer.h>
Public Member Functions
void enter ()
void leave ()
bool is_active ()
Private Attributes
int scopes_ {0}
Detailed Description
Definition at line 80 of file value-numbering-reducer.h.
Member Function Documentation
enter()
void v8::internal::compiler::turboshaft::ScopeCounter::enter () [inline]
Definition at line 82 of file value-numbering-reducer.h.
{ scopes_++; }
References scopes_.
Referenced by v8::internal::compiler::turboshaft::DisableValueNumbering::DisableValueNumbering().
is_active()
bool v8::internal::compiler::turboshaft::ScopeCounter::is_active () [inline]
Definition at line 84 of file value-numbering-reducer.h.
{ return scopes_ > 0; }
References scopes_.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::is_disabled().
leave()
void v8::internal::compiler::turboshaft::ScopeCounter::leave () [inline]
Definition at line 83 of file value-numbering-reducer.h.
{ scopes_--; }
References scopes_.
Referenced by v8::internal::compiler::turboshaft::DisableValueNumbering::~DisableValueNumbering().
Member Data Documentation
scopes_
int v8::internal::compiler::turboshaft::ScopeCounter::scopes_ {0} [private]
Definition at line 87 of file value-numbering-reducer.h.
Referenced by enter(), is_active(), and leave().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/value-numbering-reducer.h