v8::internal::Sweeper::ConcurrentMajorSweeper Class Reference
Public Member Functions
ConcurrentMajorSweeper (Sweeper *sweeper)
bool ConcurrentSweepSpace (AllocationSpace identity, JobDelegate *delegate)
void Finalize ()
Private Attributes
Sweeper *const sweeper_
LocalSweeper local_sweeper_
Detailed Description
Definition at line 51 of file sweeper.cc.
Constructor & Destructor Documentation
ConcurrentMajorSweeper()
v8::internal::Sweeper::ConcurrentMajorSweeper::ConcurrentMajorSweeper (Sweeper * sweeper) [inline], [explicit]
Definition at line 53 of file sweeper.cc.
      : sweeper_(sweeper), local_sweeper_(sweeper_) {}
Member Function Documentation
ConcurrentSweepSpace()
bool v8::internal::Sweeper::ConcurrentMajorSweeper::ConcurrentSweepSpace (AllocationSpace identity, JobDelegate * delegate) [inline]
Definition at line 56 of file sweeper.cc.
                                                                             {
    DCHECK(IsValidSweepingSpace(identity));
    DCHECK_NE(NEW_SPACE, identity);
    while (!delegate->ShouldYield()) {
      PageMetadata* page = sweeper_->GetSweepingPageSafe(identity);
      if (page == nullptr) return true;
      local_sweeper_.ParallelSweepPage(page, identity,
                                       SweepingMode::kLazyOrConcurrent);
    }
    TRACE_GC_NOTE("Sweeper::ConcurrentMajorSweeper Preempted");
    return false;
  }
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::Sweeper::GetSweepingPageSafe(), v8::internal::Sweeper::IsValidSweepingSpace(), v8::internal::Sweeper::kLazyOrConcurrent, local_sweeper_, v8::internal::NEW_SPACE, v8::internal::Sweeper::LocalSweeper::ParallelSweepPage(), v8::JobDelegate::ShouldYield(), sweeper_, and TRACE_GC_NOTE.
Referenced by v8::internal::Sweeper::MajorSweeperJob::RunImpl().
Finalize()
void v8::internal::Sweeper::ConcurrentMajorSweeper::Finalize () [inline]
Definition at line 70 of file sweeper.cc.
{}
Member Data Documentation
local_sweeper_
LocalSweeper v8::internal::Sweeper::ConcurrentMajorSweeper::local_sweeper_ [private]
Definition at line 74 of file sweeper.cc.
Referenced by ConcurrentSweepSpace().
sweeper_
Sweeper* const v8::internal::Sweeper::ConcurrentMajorSweeper::sweeper_ [private]
Definition at line 73 of file sweeper.cc.
Referenced by ConcurrentSweepSpace().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/sweeper.cc