v8::FuzzerMonitor Class Reference
#include <d8.h>
Static Public Member Functions
static void SimulateErrors ()
Static Private Member Functions
static void ControlFlowViolation ()
static void DCheck ()
static void Fatal ()
static void ObservableDifference ()
static void UndefinedBehavior ()
static void UseAfterFree ()
static void UseOfUninitializedValue ()
Detailed Description
Definition at line 882 of file d8.h.
Member Function Documentation
ControlFlowViolation()
V8_NOINLINE void v8::FuzzerMonitor::ControlFlowViolation () [static], [private]
Definition at line 4769 of file d8.cc.
                                                     {
  // Control flow violation caught by CFI.
  void (*func)() = (void (*)()) & Dummy;
  func();
}
References v8::Dummy(), and v8::internal::wasm::void().
DCheck()
V8_NOINLINE void v8::FuzzerMonitor::DCheck () [static], [private]
Definition at line 4775 of file d8.cc.
                                       {
  // Caught in debug builds.
  DCHECK(false);
}
References DCHECK.
Fatal()
V8_NOINLINE void v8::FuzzerMonitor::Fatal () [static], [private]
Definition at line 4780 of file d8.cc.
                                      {
  // Caught in all build types.
  FATAL("Fake error.");
}
References FATAL.
ObservableDifference()
V8_NOINLINE void v8::FuzzerMonitor::ObservableDifference () [static], [private]
Definition at line 4785 of file d8.cc.
                                                     {
  // Observable difference caught by differential fuzzing.
  printf("___fake_difference___\n");
}
SimulateErrors()
V8_NOINLINE void v8::FuzzerMonitor::SimulateErrors () [static]
Definition at line 4741 of file d8.cc.
                                               {
  // Initialize a fresh RNG to not interfere with JS execution.
  std::unique_ptr<base::RandomNumberGenerator> rng;
  int64_t seed = i::v8_flags.random_seed;
  if (seed != 0) {
    rng = std::make_unique<base::RandomNumberGenerator>(seed);
  } else {
    rng = std::make_unique<base::RandomNumberGenerator>();
  }
  double p = rng->NextDouble();
  if (p < 0.1) {
    ControlFlowViolation();
  } else if (p < 0.2) {
    DCheck();
  } else if (p < 0.3) {
    Fatal();
  } else if (p < 0.4) {
    ObservableDifference();
  } else if (p < 0.5) {
    UndefinedBehavior();
  } else if (p < 0.6) {
    UseAfterFree();
  } else if (p < 0.7) {
    UseOfUninitializedValue();
  }
}
References cppgc::internal::Fatal(), and v8::internal::v8_flags.
Referenced by v8::Shell::OnExit().
UndefinedBehavior()
V8_NOINLINE void v8::FuzzerMonitor::UndefinedBehavior () [static], [private]
Definition at line 4790 of file d8.cc.
                                                  {
  // Caught by UBSAN.
  int32_t val = -1;
  USE(val << val);
}
References USE.
UseAfterFree()
V8_NOINLINE void v8::FuzzerMonitor::UseAfterFree () [static], [private]
Definition at line 4796 of file d8.cc.
                                             {
  // Use-after-free caught by ASAN.
#if defined(__clang__) // GCC-12 detects this at compile time!
  std::vector<bool>* storage = new std::vector<bool>(3);
  delete storage;
  USE(storage->at(1));
#endif
}
References USE.
UseOfUninitializedValue()
V8_NOINLINE void v8::FuzzerMonitor::UseOfUninitializedValue () [static], [private]
Definition at line 4805 of file d8.cc.
                                                        {
// Use-of-uninitialized-value caught by MSAN.
#if defined(__clang__)
  int uninitialized[1];
  if (uninitialized[0]) USE(uninitialized);
#endif
}
References USE.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/d8/d8.h
/mnt/V8SourceCode/src/d8/d8.cc