v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder Class Reference
Public Member Functions
MaglevFrameTranslationBuilder (LocalIsolate *local_isolate, MaglevAssembler *masm, FrameTranslationBuilder *translation_array_builder, IdentityMap< int, base::DefaultAllocationPolicy > *protected_deopt_literals, IdentityMap< int, base::DefaultAllocationPolicy > *deopt_literals)
void BuildEagerDeopt (EagerDeoptInfo *deopt_info)
void BuildLazyDeopt (LazyDeoptInfo *deopt_info)
Private Member Functions
constexpr int DeoptStackSlotIndexFromFPOffset (int offset)
int DeoptStackSlotFromStackSlot (const compiler::AllocatedOperand &operand)
void BuildBeginDeopt (DeoptInfo *deopt_info)
void RecursiveBuildDeoptFrame (const DeoptFrame &frame, const InputLocation *&current_input_location, const VirtualObjectList &virtual_objects)
void BuildSingleDeoptFrame (const InterpretedDeoptFrame &frame, const InputLocation *&current_input_location, const VirtualObjectList &virtual_objects, interpreter::Register result_location, int result_size)
void BuildSingleDeoptFrame (const InterpretedDeoptFrame &frame, const InputLocation *&current_input_location, const VirtualObjectList &virtual_objects)
void BuildSingleDeoptFrame (const InlinedArgumentsDeoptFrame &frame, const InputLocation *&current_input_location, const VirtualObjectList &virtual_objects)
void BuildSingleDeoptFrame (const ConstructInvokeStubDeoptFrame &frame, const InputLocation *&current_input_location, const VirtualObjectList &virtual_objects)
void BuildSingleDeoptFrame (const BuiltinContinuationDeoptFrame &frame, const InputLocation *&current_input_location, const VirtualObjectList &virtual_objects)
void BuildDeoptStoreRegister (const compiler::AllocatedOperand &operand, ValueRepresentation repr)
void BuildDeoptStoreStackSlot (const compiler::AllocatedOperand &operand, ValueRepresentation repr)
int GetDuplicatedId (intptr_t id)
void BuildHeapNumber (Float64 number)
void BuildConsString (const VirtualObject *object, const InputLocation *&input_location, const VirtualObjectList &virtual_objects)
void BuildFixedDoubleArray (uint32_t length, compiler::FixedDoubleArrayRef array)
void BuildNestedValue (const ValueNode *value, const InputLocation *&input_location, const VirtualObjectList &virtual_objects)
void BuildVirtualObject (const VirtualObject *object, const InputLocation *&input_location, const VirtualObjectList &virtual_objects)
void BuildDeoptFrameSingleValue (const ValueNode *value, const InputLocation *&input_location, const VirtualObjectList &virtual_objects)
void BuildDeoptFrameValues (const MaglevCompilationUnit &compilation_unit, const CompactInterpreterFrameState *checkpoint_state, const ValueNode *closure, const InputLocation *&input_location, const VirtualObjectList &virtual_objects, interpreter::Register result_location, int result_size)
int GetProtectedDeoptLiteral (Tagged< TrustedObject > obj)
int GetDeoptLiteral (Tagged< Object > obj)
int GetDeoptLiteral (compiler::HeapObjectRef ref)
Private Attributes
LocalIsolate * local_isolate_
MaglevAssembler * masm_
FrameTranslationBuilder * translation_array_builder_
IdentityMap< int, base::DefaultAllocationPolicy > * protected_deopt_literals_
IdentityMap< int, base::DefaultAllocationPolicy > * deopt_literals_
std::vector< intptr_t > object_ids_
Static Private Attributes
static const int kNotDuplicated = -1
Detailed Description
Definition at line 1151 of file maglev-code-generator.cc.
Constructor & Destructor Documentation
MaglevFrameTranslationBuilder()
v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::MaglevFrameTranslationBuilder (LocalIsolate * local_isolate, MaglevAssembler * masm, FrameTranslationBuilder * translation_array_builder, IdentityMap< int, base::DefaultAllocationPolicy > * protected_deopt_literals, IdentityMap< int, base::DefaultAllocationPolicy > * deopt_literals) [inline]
Definition at line 1153 of file maglev-code-generator.cc.
      : local_isolate_(local_isolate),
        masm_(masm),
        translation_array_builder_(translation_array_builder),
        protected_deopt_literals_(protected_deopt_literals),
        deopt_literals_(deopt_literals),
        object_ids_(10) {}
Member Function Documentation
BuildBeginDeopt()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildBeginDeopt (DeoptInfo * deopt_info) [inline], [private]
Definition at line 1217 of file maglev-code-generator.cc.
                                              {
    object_ids_.clear();
    auto [frame_count, jsframe_count] = GetFrameCount(&deopt_info->top_frame());
    deopt_info->set_translation_index(
        translation_array_builder_->BeginTranslation(
            frame_count, jsframe_count,
            deopt_info->feedback_to_update().IsValid()));
    if (deopt_info->feedback_to_update().IsValid()) {
      translation_array_builder_->AddUpdateFeedback(
          GetDeoptLiteral(*deopt_info->feedback_to_update().vector),
          deopt_info->feedback_to_update().index());
    }
  }
References v8::internal::maglev::DeoptInfo::feedback_to_update(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::anonymous_namespace{maglev-code-generator.cc}::GetFrameCount(), v8::internal::compiler::FeedbackSource::index(), v8::internal::compiler::FeedbackSource::IsValid(), v8::internal::maglev::DeoptInfo::set_translation_index(), v8::internal::maglev::DeoptInfo::top_frame(), and v8::internal::compiler::FeedbackSource::vector.
BuildConsString()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildConsString (const VirtualObject * object, const InputLocation *& input_location, const VirtualObjectList & virtual_objects) [inline], [private]
Definition at line 1463 of file maglev-code-generator.cc.
                                                                 {
    auto cons_string = object->cons_string();
    translation_array_builder_->StringConcat();
    BuildNestedValue(cons_string.first(), input_location, virtual_objects);
    BuildNestedValue(cons_string.second(), input_location, virtual_objects);
  }
BuildDeoptFrameSingleValue()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameSingleValue (const ValueNode * value, const InputLocation *& input_location, const VirtualObjectList & virtual_objects) [inline], [private]
Definition at line 1557 of file maglev-code-generator.cc.
                                                                            {
    while (value->Is<Identity>()) {
      value = value->input(0).node();
    }
    DCHECK(!value->Is<VirtualObject>());
    if (const InlinedAllocation* alloc = value->TryCast<InlinedAllocation>()) {
      VirtualObject* vobject = virtual_objects.FindAllocatedWith(alloc);
      if (vobject && alloc->HasBeenElided()) {
        DCHECK(alloc->HasBeenAnalysed());
        BuildVirtualObject(vobject, input_location, virtual_objects);
        return;
      }
    }
    if (input_location->operand().IsConstant()) {
      translation_array_builder_->StoreLiteral(
          GetDeoptLiteral(*value->Reify(local_isolate_)));
    } else {
      const compiler::AllocatedOperand& operand =
          compiler::AllocatedOperand::cast(input_location->operand());
      ValueRepresentation repr = value->properties().value_representation();
      if (operand.IsAnyRegister()) {
        BuildDeoptStoreRegister(operand, repr);
      } else {
        BuildDeoptStoreStackSlot(operand, repr);
      }
    }
    input_location++;
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), v8::internal::maglev::VirtualObjectList::FindAllocatedWith(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::maglev::ValueLocation::operand(), and v8::internal::value.
BuildDeoptFrameValues()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptFrameValues (const MaglevCompilationUnit & compilation_unit, const CompactInterpreterFrameState * checkpoint_state, const ValueNode * closure, const InputLocation *& input_location, const VirtualObjectList & virtual_objects, interpreter::Register result_location, int result_size) [inline], [private]
Definition at line 1588 of file maglev-code-generator.cc.
                                                            {
    // TODO(leszeks): The input locations array happens to be in the same
    // order as closure+parameters+context+locals+accumulator are accessed
    // here. We should make this clearer and guard against this invariant
    // failing.
    // Closure
    BuildDeoptFrameSingleValue(closure, input_location, virtual_objects);
    // Parameters
    {
      int i = 0;
      checkpoint_state->ForEachParameter(
          compilation_unit, [&](ValueNode* value, interpreter::Register reg) {
            DCHECK_EQ(reg.ToParameterIndex(), i);
            if (LazyDeoptInfo::InReturnValues(reg, result_location,
                                              result_size)) {
              translation_array_builder_->StoreOptimizedOut();
            } else {
              BuildDeoptFrameSingleValue(value, input_location,
                                         virtual_objects);
            }
            i++;
          });
    }
    // Context
    ValueNode* context_value = checkpoint_state->context(compilation_unit);
    BuildDeoptFrameSingleValue(context_value, input_location, virtual_objects);
    // Locals
    {
      int i = 0;
      checkpoint_state->ForEachLocal(
          compilation_unit, [&](ValueNode* value, interpreter::Register reg) {
            DCHECK_LE(i, reg.index());
            if (LazyDeoptInfo::InReturnValues(reg, result_location,
                                              result_size))
              return;
            while (i < reg.index()) {
              translation_array_builder_->StoreOptimizedOut();
              i++;
            }
            DCHECK_EQ(i, reg.index());
            BuildDeoptFrameSingleValue(value, input_location, virtual_objects);
            i++;
          });
      while (i < compilation_unit.register_count()) {
        translation_array_builder_->StoreOptimizedOut();
        i++;
      }
    }
    // Accumulator
    {
      if (checkpoint_state->liveness()->AccumulatorIsLive() &&
          !LazyDeoptInfo::InReturnValues(
              interpreter::Register::virtual_accumulator(), result_location,
              result_size)) {
        ValueNode* value = checkpoint_state->accumulator(compilation_unit);
        BuildDeoptFrameSingleValue(value, input_location, virtual_objects);
      } else {
        translation_array_builder_->StoreOptimizedOut();
      }
    }
  }
References v8::internal::maglev::CompactInterpreterFrameState::accumulator(), v8::internal::compiler::BytecodeLivenessState::AccumulatorIsLive(), v8::internal::maglev::CompactInterpreterFrameState::context(), DCHECK_EQ, DCHECK_LE, v8::internal::maglev::CompactInterpreterFrameState::ForEachLocal(), v8::internal::maglev::CompactInterpreterFrameState::ForEachParameter(), v8::internal::interpreter::Register::index(), v8::internal::maglev::CompactInterpreterFrameState::liveness(), v8::internal::maglev::MaglevCompilationUnit::register_count(), v8::internal::interpreter::Register::ToParameterIndex(), v8::internal::value, and v8::internal::interpreter::Register::virtual_accumulator().
BuildDeoptStoreRegister()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptStoreRegister (const compiler::AllocatedOperand & operand, ValueRepresentation repr) [inline], [private]
Definition at line 1391 of file maglev-code-generator.cc.
                                                         {
    switch (repr) {
      case ValueRepresentation::kIntPtr:
        translation_array_builder_->StoreIntPtrRegister(operand.GetRegister());
        break;
      case ValueRepresentation::kTagged:
        translation_array_builder_->StoreRegister(operand.GetRegister());
        break;
      case ValueRepresentation::kInt32:
        translation_array_builder_->StoreInt32Register(operand.GetRegister());
        break;
      case ValueRepresentation::kUint32:
        translation_array_builder_->StoreUint32Register(operand.GetRegister());
        break;
      case ValueRepresentation::kFloat64:
        translation_array_builder_->StoreDoubleRegister(
            operand.GetDoubleRegister());
        break;
      case ValueRepresentation::kHoleyFloat64:
        translation_array_builder_->StoreHoleyDoubleRegister(
            operand.GetDoubleRegister());
        break;
    }
  }
References v8::internal::compiler::LocationOperand::GetDoubleRegister(), v8::internal::compiler::LocationOperand::GetRegister(), and v8::internal::anonymous_namespace{ic.cc}::kIntPtr.
BuildDeoptStoreStackSlot()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildDeoptStoreStackSlot (const compiler::AllocatedOperand & operand, ValueRepresentation repr) [inline], [private]
Definition at line 1417 of file maglev-code-generator.cc.
                                                          {
    int stack_slot = DeoptStackSlotFromStackSlot(operand);
    switch (repr) {
      case ValueRepresentation::kIntPtr:
        translation_array_builder_->StoreIntPtrStackSlot(stack_slot);
        break;
      case ValueRepresentation::kTagged:
        translation_array_builder_->StoreStackSlot(stack_slot);
        break;
      case ValueRepresentation::kInt32:
        translation_array_builder_->StoreInt32StackSlot(stack_slot);
        break;
      case ValueRepresentation::kUint32:
        translation_array_builder_->StoreUint32StackSlot(stack_slot);
        break;
      case ValueRepresentation::kFloat64:
        translation_array_builder_->StoreDoubleStackSlot(stack_slot);
        break;
      case ValueRepresentation::kHoleyFloat64:
        translation_array_builder_->StoreHoleyDoubleStackSlot(stack_slot);
        break;
    }
  }
References v8::internal::anonymous_namespace{ic.cc}::kIntPtr.
BuildEagerDeopt()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildEagerDeopt (EagerDeoptInfo * deopt_info) [inline]
Definition at line 1165 of file maglev-code-generator.cc.
                                                   {
    BuildBeginDeopt(deopt_info);
    const InputLocation* current_input_location = deopt_info->input_locations();
    const VirtualObjectList& virtual_objects =
        deopt_info->top_frame().GetVirtualObjects();
    RecursiveBuildDeoptFrame(deopt_info->top_frame(), current_input_location,
                             virtual_objects);
  }
References v8::internal::maglev::DeoptFrame::GetVirtualObjects(), v8::internal::maglev::DeoptInfo::input_locations(), and v8::internal::maglev::DeoptInfo::top_frame().
BuildFixedDoubleArray()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildFixedDoubleArray (uint32_t length, compiler::FixedDoubleArrayRef array) [inline], [private]
Definition at line 1472 of file maglev-code-generator.cc.
                                                                {
    translation_array_builder_->BeginCapturedObject(length + 2);
    translation_array_builder_->StoreLiteral(
        GetDeoptLiteral(*local_isolate_->factory()->fixed_double_array_map()));
    translation_array_builder_->StoreLiteral(
        GetDeoptLiteral(Smi::FromInt(length)));
    for (uint32_t i = 0; i < length; i++) {
      Float64 value = array.GetFromImmutableFixedDoubleArray(i);
      if (value.is_hole_nan()) {
        translation_array_builder_->StoreLiteral(
            GetDeoptLiteral(ReadOnlyRoots(local_isolate_).the_hole_value()));
      } else {
        BuildHeapNumber(value);
      }
    }
  }
References v8::internal::Smi::FromInt(), v8::internal::compiler::FixedDoubleArrayRef::GetFromImmutableFixedDoubleArray(), v8::internal::length, and v8::internal::value.
BuildHeapNumber()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildHeapNumber (Float64 number) [inline], [private]
Definition at line 1456 of file maglev-code-generator.cc.
                                       {
    DirectHandle<Object> value =
        local_isolate_->factory()->NewHeapNumberFromBits<AllocationType::kOld>(
            number.get_bits());
    translation_array_builder_->StoreLiteral(GetDeoptLiteral(*value));
  }
References v8::internal::Float64::get_bits(), v8::internal::kOld, and v8::internal::value.
BuildLazyDeopt()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildLazyDeopt (LazyDeoptInfo * deopt_info) [inline]
Definition at line 1175 of file maglev-code-generator.cc.
                                                 {
    BuildBeginDeopt(deopt_info);
    const InputLocation* current_input_location = deopt_info->input_locations();
    const VirtualObjectList& virtual_objects =
        deopt_info->top_frame().GetVirtualObjects();
    if (deopt_info->top_frame().parent()) {
      // Deopt input locations are in the order of deopt frame emission, so
      // update the pointer after emitting the parent frame.
      RecursiveBuildDeoptFrame(*deopt_info->top_frame().parent(),
                               current_input_location, virtual_objects);
    }
    const DeoptFrame& top_frame = deopt_info->top_frame();
    switch (top_frame.type()) {
      case DeoptFrame::FrameType::kInterpretedFrame:
        return BuildSingleDeoptFrame(
            top_frame.as_interpreted(), current_input_location, virtual_objects,
            deopt_info->result_location(), deopt_info->result_size());
      case DeoptFrame::FrameType::kInlinedArgumentsFrame:
        // The inlined arguments frame can never be the top frame.
        UNREACHABLE();
      case DeoptFrame::FrameType::kConstructInvokeStubFrame:
        return BuildSingleDeoptFrame(top_frame.as_construct_stub(),
                                     current_input_location, virtual_objects);
      case DeoptFrame::FrameType::kBuiltinContinuationFrame:
        return BuildSingleDeoptFrame(top_frame.as_builtin_continuation(),
                                     current_input_location, virtual_objects);
    }
  }
References v8::internal::maglev::DeoptFrame::as_builtin_continuation(), v8::internal::maglev::DeoptFrame::as_construct_stub(), v8::internal::maglev::DeoptFrame::as_interpreted(), v8::internal::maglev::DeoptFrame::GetVirtualObjects(), v8::internal::maglev::DeoptInfo::input_locations(), v8::internal::maglev::DeoptFrame::parent(), v8::internal::maglev::LazyDeoptInfo::result_location(), v8::internal::maglev::LazyDeoptInfo::result_size(), v8::internal::maglev::DeoptInfo::top_frame(), v8::internal::maglev::DeoptFrame::type(), and v8::internal::UNREACHABLE().
BuildNestedValue()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildNestedValue (const ValueNode * value, const InputLocation *& input_location, const VirtualObjectList & virtual_objects) [inline], [private]
Definition at line 1490 of file maglev-code-generator.cc.
                                                                  {
    if (IsConstantNode(value->opcode())) {
      translation_array_builder_->StoreLiteral(
          GetDeoptLiteral(*value->Reify(local_isolate_)));
      return;
    }
    // Special nodes.
    switch (value->opcode()) {
      case Opcode::kArgumentsElements:
        translation_array_builder_->ArgumentsElements(
            value->Cast<ArgumentsElements>()->type());
        // We simulate the deoptimizer deduplication machinery, which will give
        // a fresh id to the ArgumentsElements. For that, we need to push
        // something object_ids_ We push -1, since no object should have id -1.
        object_ids_.push_back(-1);
        break;
      case Opcode::kArgumentsLength:
        translation_array_builder_->ArgumentsLength();
        break;
      case Opcode::kRestLength:
        translation_array_builder_->RestLength();
        break;
      case Opcode::kVirtualObject:
        UNREACHABLE();
      default:
        BuildDeoptFrameSingleValue(value, input_location, virtual_objects);
        break;
    }
  }
References v8::internal::maglev::IsConstantNode(), v8::internal::maglev::ArgumentsElements::type(), v8::internal::UNREACHABLE(), and v8::internal::value.
BuildSingleDeoptFrame() [1/5]
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame (const BuiltinContinuationDeoptFrame & frame, const InputLocation *& current_input_location, const VirtualObjectList & virtual_objects) [inline], [private]
Definition at line 1330 of file maglev-code-generator.cc.
                                                                       {
    BytecodeOffset bailout_id =
        Builtins::GetContinuationBytecodeOffset(frame.builtin_id());
    int literal_id = GetDeoptLiteral(frame.GetSharedFunctionInfo());
    int height = frame.parameters().length();
    constexpr int kExtraFixedJSFrameParameters =
        V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL ? 4 : 3;
    if (frame.is_javascript()) {
      translation_array_builder_->BeginJavaScriptBuiltinContinuationFrame(
          bailout_id, literal_id, height + kExtraFixedJSFrameParameters);
    } else {
      translation_array_builder_->BeginBuiltinContinuationFrame(
          bailout_id, literal_id, height);
    }
    // Closure
    if (frame.is_javascript()) {
      translation_array_builder_->StoreLiteral(
          GetDeoptLiteral(frame.javascript_target()));
    } else {
      translation_array_builder_->StoreOptimizedOut();
    }
    // Parameters
    for (ValueNode* value : frame.parameters()) {
      BuildDeoptFrameSingleValue(value, current_input_location,
                                 virtual_objects);
    }
    // Extra fixed JS frame parameters. These at the end since JS builtins
    // push their parameters in reverse order.
    if (frame.is_javascript()) {
      DCHECK_EQ(Builtins::CallInterfaceDescriptorFor(frame.builtin_id())
                    .GetRegisterParameterCount(),
                kExtraFixedJSFrameParameters);
      static_assert(kExtraFixedJSFrameParameters ==
                    3 + (V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL ? 1 : 0));
      // kJavaScriptCallTargetRegister
      translation_array_builder_->StoreLiteral(
          GetDeoptLiteral(frame.javascript_target()));
      // kJavaScriptCallNewTargetRegister
      translation_array_builder_->StoreLiteral(
          GetDeoptLiteral(ReadOnlyRoots(local_isolate_).undefined_value()));
      // kJavaScriptCallArgCountRegister
      translation_array_builder_->StoreLiteral(GetDeoptLiteral(
          Smi::FromInt(Builtins::GetStackParameterCount(frame.builtin_id()))));
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
      // kJavaScriptCallDispatchHandleRegister
      translation_array_builder_->StoreLiteral(
          GetDeoptLiteral(Smi::FromInt(kInvalidDispatchHandle.value())));
#endif
    }
    // Context
    ValueNode* value = frame.context();
    BuildDeoptFrameSingleValue(value, current_input_location, virtual_objects);
  }
References v8::internal::maglev::BuiltinContinuationDeoptFrame::builtin_id(), v8::internal::Builtins::CallInterfaceDescriptorFor(), v8::internal::maglev::BuiltinContinuationDeoptFrame::context(), DCHECK_EQ, v8::internal::Smi::FromInt(), v8::internal::Builtins::GetContinuationBytecodeOffset(), v8::internal::CallInterfaceDescriptor::GetRegisterParameterCount(), v8::internal::maglev::DeoptFrame::GetSharedFunctionInfo(), v8::internal::Builtins::GetStackParameterCount(), v8::internal::maglev::BuiltinContinuationDeoptFrame::is_javascript(), v8::internal::maglev::BuiltinContinuationDeoptFrame::javascript_target(), v8::internal::kInvalidDispatchHandle(), v8::internal::maglev::BuiltinContinuationDeoptFrame::parameters(), V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL, v8::base::StrongAlias< TagType, UnderlyingType >::value(), and v8::internal::value.
BuildSingleDeoptFrame() [2/5]
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame (const ConstructInvokeStubDeoptFrame & frame, const InputLocation *& current_input_location, const VirtualObjectList & virtual_objects) [inline], [private]
Definition at line 1315 of file maglev-code-generator.cc.
                                                                       {
    translation_array_builder_->BeginConstructInvokeStubFrame(
        GetDeoptLiteral(frame.GetSharedFunctionInfo()));
    // Implicit receiver
    BuildDeoptFrameSingleValue(frame.receiver(), current_input_location,
                               virtual_objects);
    // Context
    BuildDeoptFrameSingleValue(frame.context(), current_input_location,
                               virtual_objects);
  }
References v8::internal::maglev::ConstructInvokeStubDeoptFrame::context(), v8::internal::maglev::DeoptFrame::GetSharedFunctionInfo(), and v8::internal::maglev::ConstructInvokeStubDeoptFrame::receiver().
BuildSingleDeoptFrame() [3/5]
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame (const InlinedArgumentsDeoptFrame & frame, const InputLocation *& current_input_location, const VirtualObjectList & virtual_objects) [inline], [private]
Definition at line 1293 of file maglev-code-generator.cc.
                                                                       {
    translation_array_builder_->BeginInlinedExtraArguments(
        GetDeoptLiteral(frame.GetSharedFunctionInfo()),
        static_cast<uint32_t>(frame.arguments().size()),
        frame.GetBytecodeArray().parameter_count());
    // Closure
    BuildDeoptFrameSingleValue(frame.closure(), current_input_location,
                               virtual_objects);
    // Arguments
    // TODO(victorgomes): Technically we don't need all arguments, only the
    // extra ones. But doing this at the moment, since it matches the
    // TurboFan behaviour.
    for (ValueNode* value : frame.arguments()) {
      BuildDeoptFrameSingleValue(value, current_input_location,
                                 virtual_objects);
    }
  }
References v8::internal::maglev::InlinedArgumentsDeoptFrame::arguments(), v8::internal::maglev::InlinedArgumentsDeoptFrame::closure(), v8::internal::maglev::DeoptFrame::GetBytecodeArray(), v8::internal::maglev::DeoptFrame::GetSharedFunctionInfo(), v8::internal::compiler::BytecodeArrayRef::parameter_count(), and v8::internal::value.
BuildSingleDeoptFrame() [4/5]
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame (const InterpretedDeoptFrame & frame, const InputLocation *& current_input_location, const VirtualObjectList & virtual_objects) [inline], [private]
Definition at line 1274 of file maglev-code-generator.cc.
                                                                       {
    // Returns offset/count is used for updating an accumulator or register
    // after a lazy deopt -- this function is overloaded to allow them to be
    // passed in.
    const int return_offset = 0;
    const int return_count = 0;
    translation_array_builder_->BeginInterpretedFrame(
        frame.bytecode_position(),
        GetDeoptLiteral(frame.GetSharedFunctionInfo()),
        GetProtectedDeoptLiteral(*frame.GetBytecodeArray().object()),
        frame.unit().register_count(), return_offset, return_count);
    BuildDeoptFrameValues(frame.unit(), frame.frame_state(), frame.closure(),
                          current_input_location, virtual_objects,
                          interpreter::Register::invalid_value(), return_count);
  }
References v8::internal::maglev::InterpretedDeoptFrame::bytecode_position(), v8::internal::maglev::InterpretedDeoptFrame::closure(), v8::internal::maglev::InterpretedDeoptFrame::frame_state(), v8::internal::maglev::DeoptFrame::GetBytecodeArray(), v8::internal::maglev::DeoptFrame::GetSharedFunctionInfo(), v8::internal::interpreter::Register::invalid_value(), v8::internal::compiler::BytecodeArrayRef::object(), v8::internal::maglev::MaglevCompilationUnit::register_count(), and v8::internal::maglev::InterpretedDeoptFrame::unit().
BuildSingleDeoptFrame() [5/5]
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame (const InterpretedDeoptFrame & frame, const InputLocation *& current_input_location, const VirtualObjectList & virtual_objects, interpreter::Register result_location, int result_size) [inline], [private]
Definition at line 1257 of file maglev-code-generator.cc.
                                              {
    int return_offset = frame.ComputeReturnOffset(result_location, result_size);
    translation_array_builder_->BeginInterpretedFrame(
        frame.bytecode_position(),
        GetDeoptLiteral(frame.GetSharedFunctionInfo()),
        GetProtectedDeoptLiteral(*frame.GetBytecodeArray().object()),
        frame.unit().register_count(), return_offset, result_size);
    BuildDeoptFrameValues(frame.unit(), frame.frame_state(), frame.closure(),
                          current_input_location, virtual_objects,
                          result_location, result_size);
  }
References v8::internal::maglev::InterpretedDeoptFrame::bytecode_position(), v8::internal::maglev::InterpretedDeoptFrame::closure(), v8::internal::maglev::InterpretedDeoptFrame::ComputeReturnOffset(), v8::internal::maglev::InterpretedDeoptFrame::frame_state(), v8::internal::maglev::DeoptFrame::GetBytecodeArray(), v8::internal::maglev::DeoptFrame::GetSharedFunctionInfo(), v8::internal::compiler::BytecodeArrayRef::object(), v8::internal::maglev::MaglevCompilationUnit::register_count(), and v8::internal::maglev::InterpretedDeoptFrame::unit().
BuildVirtualObject()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildVirtualObject (const VirtualObject * object, const InputLocation *& input_location, const VirtualObjectList & virtual_objects) [inline], [private]
Definition at line 1522 of file maglev-code-generator.cc.
                                                                    {
    if (object->type() == VirtualObject::kHeapNumber) {
      return BuildHeapNumber(object->number());
    }
    int dup_id =
        GetDuplicatedId(reinterpret_cast<intptr_t>(object->allocation()));
    if (dup_id != kNotDuplicated) {
      translation_array_builder_->DuplicateObject(dup_id);
      object->ForEachNestedRuntimeInput(virtual_objects,
                                        [&](ValueNode*) { input_location++; });
      return;
    }
    switch (object->type()) {
      case VirtualObject::kHeapNumber:
        // Handled above.
        UNREACHABLE();
      case VirtualObject::kConsString:
        return BuildConsString(object, input_location, virtual_objects);
      case VirtualObject::kFixedDoubleArray:
        return BuildFixedDoubleArray(object->double_elements_length(),
                                     object->double_elements());
      case VirtualObject::kDefault:
        translation_array_builder_->BeginCapturedObject(object->slot_count() +
                                                        1);
        DCHECK(object->has_static_map());
        translation_array_builder_->StoreLiteral(
            GetDeoptLiteral(*object->map().object()));
        object->ForEachInput([&](ValueNode* node) {
          BuildNestedValue(node, input_location, virtual_objects);
        });
    }
  }
References v8::internal::maglev::VirtualObject::allocation(), v8::internal::DCHECK(), v8::internal::maglev::VirtualObject::double_elements(), v8::internal::maglev::VirtualObject::double_elements_length(), v8::internal::maglev::VirtualObject::has_static_map(), v8::internal::maglev::VirtualObject::map(), v8::internal::maglev::VirtualObject::number(), v8::internal::compiler::MapRef::object(), v8::internal::maglev::VirtualObject::slot_count(), v8::internal::maglev::VirtualObject::type(), and v8::internal::UNREACHABLE().
DeoptStackSlotFromStackSlot()
int v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::DeoptStackSlotFromStackSlot (const compiler::AllocatedOperand & operand) [inline], [private]
Definition at line 1212 of file maglev-code-generator.cc.
                                                                           {
    return DeoptStackSlotIndexFromFPOffset(
        masm_->GetFramePointerOffsetForStackSlot(operand));
  }
DeoptStackSlotIndexFromFPOffset()
constexpr int v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::DeoptStackSlotIndexFromFPOffset (int offset) [inline], [constexpr], [private]
Definition at line 1208 of file maglev-code-generator.cc.
                                                            {
    return 1 - offset / kSystemPointerSize;
  }
References v8::internal::kSystemPointerSize.
GetDeoptLiteral() [1/2]
int v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::GetDeoptLiteral (compiler::HeapObjectRef ref) [inline], [private]
Definition at line 1679 of file maglev-code-generator.cc.
                                                 {
    return GetDeoptLiteral(*ref.object());
  }
References v8::internal::compiler::HeapObjectRef::object().
GetDeoptLiteral() [2/2]
int v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::GetDeoptLiteral (Tagged< Object > obj) [inline], [private]
Definition at line 1670 of file maglev-code-generator.cc.
                                          {
    IdentityMapFindResult<int> res = deopt_literals_->FindOrInsert(obj);
    if (!res.already_exists) {
      DCHECK_EQ(0, *res.entry);
      *res.entry = deopt_literals_->size() - 1;
    }
    return *res.entry;
  }
References v8::internal::IdentityMapFindResult< T >::already_exists, DCHECK_EQ, and v8::internal::IdentityMapFindResult< T >::entry.
GetDuplicatedId()
int v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::GetDuplicatedId (intptr_t id) [inline], [private]
Definition at line 1442 of file maglev-code-generator.cc.
                                   {
    for (int idx = 0; idx < static_cast<int>(object_ids_.size()); idx++) {
      if (object_ids_[idx] == id) {
        // Although this is not technically necessary, the translated state
        // machinery assign ids to duplicates, so we need to push something to
        // get fresh ids.
        object_ids_.push_back(id);
        return idx;
      }
    }
    object_ids_.push_back(id);
    return kNotDuplicated;
  }
GetProtectedDeoptLiteral()
int v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::GetProtectedDeoptLiteral (Tagged< TrustedObject > obj) [inline], [private]
Definition at line 1660 of file maglev-code-generator.cc.
                                                          {
    IdentityMapFindResult<int> res =
        protected_deopt_literals_->FindOrInsert(obj);
    if (!res.already_exists) {
      DCHECK_EQ(0, *res.entry);
      *res.entry = protected_deopt_literals_->size() - 1;
    }
    return *res.entry;
  }
References v8::internal::IdentityMapFindResult< T >::already_exists, DCHECK_EQ, and v8::internal::IdentityMapFindResult< T >::entry.
RecursiveBuildDeoptFrame()
void v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::RecursiveBuildDeoptFrame (const DeoptFrame & frame, const InputLocation *& current_input_location, const VirtualObjectList & virtual_objects) [inline], [private]
Definition at line 1231 of file maglev-code-generator.cc.
                                                                          {
    if (frame.parent()) {
      // Deopt input locations are in the order of deopt frame emission, so
      // update the pointer after emitting the parent frame.
      RecursiveBuildDeoptFrame(*frame.parent(), current_input_location,
                               virtual_objects);
    }
    switch (frame.type()) {
      case DeoptFrame::FrameType::kInterpretedFrame:
        return BuildSingleDeoptFrame(frame.as_interpreted(),
                                     current_input_location, virtual_objects);
      case DeoptFrame::FrameType::kInlinedArgumentsFrame:
        return BuildSingleDeoptFrame(frame.as_inlined_arguments(),
                                     current_input_location, virtual_objects);
      case DeoptFrame::FrameType::kConstructInvokeStubFrame:
        return BuildSingleDeoptFrame(frame.as_construct_stub(),
                                     current_input_location, virtual_objects);
      case DeoptFrame::FrameType::kBuiltinContinuationFrame:
        return BuildSingleDeoptFrame(frame.as_builtin_continuation(),
                                     current_input_location, virtual_objects);
    }
  }
References v8::internal::maglev::DeoptFrame::as_builtin_continuation(), v8::internal::maglev::DeoptFrame::as_construct_stub(), v8::internal::maglev::DeoptFrame::as_inlined_arguments(), v8::internal::maglev::DeoptFrame::as_interpreted(), v8::internal::maglev::DeoptFrame::parent(), and v8::internal::maglev::DeoptFrame::type().
Member Data Documentation
deopt_literals_
IdentityMap<int, base::DefaultAllocationPolicy>* v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::deopt_literals_ [private]
Definition at line 1687 of file maglev-code-generator.cc.
kNotDuplicated
const int v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::kNotDuplicated = -1 [static], [private]
Definition at line 1689 of file maglev-code-generator.cc.
local_isolate_
LocalIsolate* v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::local_isolate_ [private]
Definition at line 1683 of file maglev-code-generator.cc.
masm_
MaglevAssembler* v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::masm_ [private]
Definition at line 1684 of file maglev-code-generator.cc.
object_ids_
std::vector<intptr_t> v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::object_ids_ [private]
Definition at line 1690 of file maglev-code-generator.cc.
protected_deopt_literals_
IdentityMap<int, base::DefaultAllocationPolicy>* v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::protected_deopt_literals_ [private]
Definition at line 1686 of file maglev-code-generator.cc.
translation_array_builder_
FrameTranslationBuilder* v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::translation_array_builder_ [private]
Definition at line 1685 of file maglev-code-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-code-generator.cc