v8::internal::maglev::Graph Class Reference
#include <maglev-graph.h>
Public Types
using SmallAllocationVector = SmallZoneVector< InlinedAllocation *, 2 >
Public Member Functions
Graph (MaglevCompilationInfo *info)
BasicBlock * operator[] (int i)
const BasicBlock * operator[] (int i) const
int num_blocks () const
ZoneVector< BasicBlock * > & blocks ()
BlockConstIterator begin () const
BlockConstIterator end () const
BlockConstReverseIterator rbegin () const
BlockConstReverseIterator rend () const
BasicBlock * last_block () const
void Add (BasicBlock *block)
void set_blocks (ZoneVector< BasicBlock * > blocks)
void RemoveUnreachableBlocks ()
uint32_t tagged_stack_slots () const
uint32_t untagged_stack_slots () const
uint32_t max_call_stack_args () const
uint32_t max_deopted_stack_size () const
void set_tagged_stack_slots (uint32_t stack_slots)
void set_untagged_stack_slots (uint32_t stack_slots)
void set_max_call_stack_args (uint32_t stack_slots)
void set_max_deopted_stack_size (uint32_t size)
int total_inlined_bytecode_size () const
void add_inlined_bytecode_size (int size)
int total_peeled_bytecode_size () const
void add_peeled_bytecode_size (int size)
compiler::ZoneRefMap< compiler::HeapObjectRef, Constant * > & constants ()
ZoneMap< RootIndex, RootConstant * > & root ()
ZoneMap< int, SmiConstant * > & smi ()
ZoneMap< int, TaggedIndexConstant * > & tagged_index ()
ZoneMap< int32_t, Int32Constant * > & int32 ()
ZoneMap< uint32_t, Uint32Constant * > & uint32 ()
ZoneMap< intptr_t, IntPtrConstant * > & intptr ()
ZoneMap< uint64_t, Float64Constant * > & float64 ()
compiler::ZoneRefMap< compiler::HeapObjectRef, TrustedConstant * > & trusted_constants ()
ZoneVector< InitialValue * > & osr_values ()
ZoneVector< InitialValue * > & parameters ()
ZoneVector< MaglevCallSiteInfo * > & inlineable_calls ()
ZoneVector< Node * > & node_buffer ()
ZoneMap< InlinedAllocation *, SmallAllocationVector > & allocations_escape_map ()
ZoneMap< InlinedAllocation *, SmallAllocationVector > & allocations_elide_map ()
RegList & register_inputs ()
ZoneVector< OptimizedCompilationInfo::InlinedFunctionHolder > & inlined_functions ()
bool has_recursive_calls () const
void set_has_recursive_calls (bool value)
bool is_osr () const
uint32_t min_maglev_stackslots_for_unoptimized_frame_size ()
uint32_t NewObjectId ()
void set_has_resumable_generator ()
bool has_resumable_generator () const
void set_may_have_unreachable_blocks (bool value=true)
bool may_have_unreachable_blocks () const
compiler::OptionalScopeInfoRef TryGetScopeInfo (ValueNode *context)
void record_scope_info (ValueNode *context, compiler::OptionalScopeInfoRef scope_info)
SmiConstant * GetSmiConstant (int constant)
TaggedIndexConstant * GetTaggedIndexConstant (int constant)
Int32Constant * GetInt32Constant (int32_t constant)
IntPtrConstant * GetIntPtrConstant (intptr_t constant)
Uint32Constant * GetUint32Constant (uint32_t constant)
Float64Constant * GetFloat64Constant (double constant)
Float64Constant * GetFloat64Constant (Float64 constant)
RootConstant * GetRootConstant (RootIndex index)
RootConstant * GetBooleanConstant (bool value)
ValueNode * GetConstant (compiler::ObjectRef ref)
ValueNode * GetTrustedConstant (compiler::HeapObjectRef ref, IndirectPointerTag tag)
Zone * zone () const
compiler::JSHeapBroker * broker () const
BasicBlock::Id max_block_id () const
bool has_graph_labeller () const
MaglevGraphLabeller * graph_labeller () const
Static Public Member Functions
static Graph * New (MaglevCompilationInfo *info)
Private Member Functions
template<typename NodeT , typename... Args>
NodeT * CreateNewConstantNode (Args &&... args) const
template<typename NodeT , typename T >
NodeT * GetOrAddNewConstantNode (ZoneMap< T, NodeT * > &container, T constant)
compiler::OptionalScopeInfoRef TryGetScopeInfoForContextLoad (ValueNode *context, int offset)
template<typename Function >
void IterateGraphAndSweepDeadBlocks (Function &&is_dead)
Private Attributes
MaglevCompilationInfo * compilation_info_
uint32_t tagged_stack_slots_ = kMaxUInt32
uint32_t untagged_stack_slots_ = kMaxUInt32
uint32_t max_call_stack_args_ = kMaxUInt32
uint32_t max_deopted_stack_size_ = kMaxUInt32
ZoneVector< BasicBlock * > blocks_
ZoneVector< InitialValue * > osr_values_
ZoneMap< RootIndex, RootConstant * > root_constants_
ZoneMap< int, SmiConstant * > smi_constants_
ZoneMap< int, TaggedIndexConstant * > tagged_index_constants_
ZoneMap< int32_t, Int32Constant * > int32_constants_
ZoneMap< uint32_t, Uint32Constant * > uint32_constants_
ZoneMap< intptr_t, IntPtrConstant * > intptr_constants_
ZoneMap< uint64_t, Float64Constant * > float64_constants_
ZoneVector< InitialValue * > parameters_
ZoneVector< MaglevCallSiteInfo * > inlineable_calls_
ZoneMap< InlinedAllocation *, SmallAllocationVector > allocations_escape_map_
ZoneMap< InlinedAllocation *, SmallAllocationVector > allocations_elide_map_
RegList register_inputs_
compiler::ZoneRefMap< compiler::HeapObjectRef, Constant * > constants_
compiler::ZoneRefMap< compiler::HeapObjectRef, TrustedConstant * > trusted_constants_
ZoneVector< OptimizedCompilationInfo::InlinedFunctionHolder > inlined_functions_
ZoneVector< Node * > node_buffer_
bool has_recursive_calls_ = false
int total_inlined_bytecode_size_ = 0
int total_peeled_bytecode_size_ = 0
uint32_t object_ids_ = 0
bool has_resumable_generator_ = false
bool may_have_unreachable_blocks_ = false
ZoneUnorderedMap< ValueNode *, compiler::OptionalScopeInfoRef > scope_infos_
BasicBlock::Id max_block_id_ = 0
std::unique_ptr< MaglevGraphLabeller > graph_labeller_ = {}
Detailed Description
Definition at line 28 of file maglev-graph.h.
Member Typedef Documentation
SmallAllocationVector
using v8::internal::maglev::Graph::SmallAllocationVector = SmallZoneVector<InlinedAllocation*, 2>
Definition at line 151 of file maglev-graph.h.
Constructor & Destructor Documentation
Graph()
v8::internal::maglev::Graph::Graph (MaglevCompilationInfo * info) [inline], [explicit]
Definition at line 35 of file maglev-graph.h.
      : compilation_info_(info),
        blocks_(zone()),
        osr_values_(zone()),
        root_constants_(zone()),
        smi_constants_(zone()),
        tagged_index_constants_(zone()),
        int32_constants_(zone()),
        uint32_constants_(zone()),
        intptr_constants_(zone()),
        float64_constants_(zone()),
        parameters_(zone()),
        inlineable_calls_(zone()),
        allocations_escape_map_(zone()),
        allocations_elide_map_(zone()),
        register_inputs_(),
        constants_(zone()),
        trusted_constants_(zone()),
        inlined_functions_(zone()),
        node_buffer_(zone()),
        scope_infos_(zone()) {
    node_buffer_.reserve(32);
  }
References node_buffer_, and v8::internal::ZoneVector< T >::reserve().
Member Function Documentation
Add()
void v8::internal::maglev::Graph::Add (BasicBlock * block) [inline]
Definition at line 72 of file maglev-graph.h.
                              {
    if (block->has_id()) {
      // The inliner adds blocks multiple times.
      DCHECK(v8_flags.maglev_non_eager_inlining ||
             v8_flags.turbolev_non_eager_inlining);
    } else {
      block->set_id(max_block_id_++);
    }
    blocks_.push_back(block);
  }
References blocks_, v8::internal::DCHECK(), v8::internal::maglev::BasicBlock::has_id(), max_block_id_, v8::internal::ZoneVector< T >::push_back(), v8::internal::maglev::BasicBlock::set_id(), and v8::internal::v8_flags.
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction().
add_inlined_bytecode_size()
void v8::internal::maglev::Graph::add_inlined_bytecode_size (int size) [inline]
Definition at line 115 of file maglev-graph.h.
                                           {
    total_inlined_bytecode_size_ += size;
  }
References size(), and total_inlined_bytecode_size_.
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction().
add_peeled_bytecode_size()
void v8::internal::maglev::Graph::add_peeled_bytecode_size (int size) [inline]
Definition at line 120 of file maglev-graph.h.
                                          {
    total_peeled_bytecode_size_ += size;
  }
References size(), and total_peeled_bytecode_size_.
allocations_elide_map()
ZoneMap<InlinedAllocation*, SmallAllocationVector>& v8::internal::maglev::Graph::allocations_elide_map () [inline]
Definition at line 160 of file maglev-graph.h.
                                                                              {
    return allocations_elide_map_;
  }
References allocations_elide_map_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInitializeStore(), and v8::internal::maglev::MaglevGraphBuilder::CanTrackObjectChanges().
allocations_escape_map()
ZoneMap<InlinedAllocation*, SmallAllocationVector>& v8::internal::maglev::Graph::allocations_escape_map () [inline]
Definition at line 155 of file maglev-graph.h.
                                                                               {
    return allocations_escape_map_;
  }
References allocations_escape_map_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInitializeStore().
begin()
BlockConstIterator v8::internal::maglev::Graph::begin () const [inline]
Definition at line 65 of file maglev-graph.h.
{ return blocks_.begin(); }
References v8::internal::ZoneVector< T >::begin(), and blocks_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), and v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi().
blocks()
ZoneVector<BasicBlock*>& v8::internal::maglev::Graph::blocks () [inline]
Definition at line 63 of file maglev-graph.h.
{ return blocks_; }
References blocks_.
Referenced by RemoveUnreachableBlocks(), set_blocks(), and v8::internal::maglev::MaglevInliner::TruncateGraphAt().
broker()
compiler::JSHeapBroker* v8::internal::maglev::Graph::broker () const [inline]
Definition at line 250 of file maglev-graph.h.
{ return compilation_info_->broker(); }
References v8::internal::maglev::MaglevCompilationInfo::broker(), and compilation_info_.
Referenced by v8::internal::maglev::MaglevInliner::broker(), v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), TryGetScopeInfo(), and TryGetScopeInfoForContextLoad().
constants()
compiler::ZoneRefMap<compiler::HeapObjectRef, Constant*>& v8::internal::maglev::Graph::constants () [inline]
Definition at line 124 of file maglev-graph.h.
                                                                    {
    return constants_;
  }
References constants_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters().
CreateNewConstantNode()
template<typename NodeT , typename... Args>
NodeT* v8::internal::maglev::Graph::CreateNewConstantNode (Args &&... args) const [inline], [private]
Definition at line 300 of file maglev-graph.h.
                                                     {
    static_assert(IsConstantNode(Node::opcode_of<NodeT>));
    NodeT* node = NodeBase::New<NodeT>(zone(), std::forward<Args>(args)...);
    static_assert(!NodeT::kProperties.can_eager_deopt());
    static_assert(!NodeT::kProperties.can_lazy_deopt());
    static_assert(!NodeT::kProperties.can_throw());
    static_assert(!NodeT::kProperties.can_write());
    if (has_graph_labeller()) graph_labeller()->RegisterNode(node);
    if (v8_flags.trace_maglev_graph_building) {
      std::cout << " " << node << " "
                << PrintNodeLabel(graph_labeller(), node) << ": "
                << PrintNode(graph_labeller(), node) << std::endl;
    }
    return node;
  }
References v8::base::args, graph_labeller(), has_graph_labeller(), v8::internal::maglev::IsConstantNode(), v8::internal::compiler::anonymous_namespace{node.cc}::PrintNode(), v8::internal::maglev::MaglevGraphLabeller::RegisterNode(), v8::internal::v8_flags, and zone().
end()
BlockConstIterator v8::internal::maglev::Graph::end () const [inline]
Definition at line 66 of file maglev-graph.h.
{ return blocks_.end(); }
References blocks_, and v8::internal::ZoneVector< T >::end().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters().
float64()
ZoneMap<uint64_t, Float64Constant*>& v8::internal::maglev::Graph::float64 () [inline]
Definition at line 135 of file maglev-graph.h.
{ return float64_constants_; }
References float64_constants_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters().
GetBooleanConstant()
RootConstant* v8::internal::maglev::Graph::GetBooleanConstant (bool value) [inline]
Definition at line 239 of file maglev-graph.h.
                                               {
    return GetRootConstant(value ? RootIndex::kTrueValue
                                 : RootIndex::kFalseValue);
  }
References GetRootConstant(), and v8::internal::value.
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetBooleanConstant().
GetConstant()
ValueNode * v8::internal::maglev::Graph::GetConstant (compiler::ObjectRef ref) [inline]
Definition at line 459 of file maglev-graph.h.
                                                   {
  if (ref.IsSmi()) {
    return GetSmiConstant(ref.AsSmi());
  }
  compiler::HeapObjectRef constant = ref.AsHeapObject();
  if (IsThinString(*constant.object())) {
    constant = MakeRefAssumeMemoryFence(
        broker(), Cast<ThinString>(*constant.object())->actual());
  }
  auto root_index = broker()->FindRootIndex(constant);
  if (root_index.has_value()) {
    return GetRootConstant(*root_index);
  }
  return GetOrAddNewConstantNode(constants_, ref.AsHeapObject());
}
References broker(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::compiler::MakeRefAssumeMemoryFence(), and v8::internal::compiler::HeapObjectRef::object().
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetConstant().
GetFloat64Constant() [1/2]
Float64Constant* v8::internal::maglev::Graph::GetFloat64Constant (double constant) [inline]
Definition at line 226 of file maglev-graph.h.
                                                       {
    return GetFloat64Constant(
        Float64::FromBits(base::double_to_uint64(constant)));
  }
References v8::base::double_to_uint64(), and v8::internal::Float64::FromBits().
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), and v8::internal::maglev::MaglevGraphBuilder::GetFloat64Constant().
GetFloat64Constant() [2/2]
Float64Constant* v8::internal::maglev::Graph::GetFloat64Constant (Float64 constant) [inline]
Definition at line 231 of file maglev-graph.h.
                                                        {
    return GetOrAddNewConstantNode(float64_constants_, constant.get_bits());
  }
References float64_constants_, v8::internal::Float64::get_bits(), and GetOrAddNewConstantNode().
GetInt32Constant()
Int32Constant* v8::internal::maglev::Graph::GetInt32Constant (int32_t constant) [inline]
Definition at line 214 of file maglev-graph.h.
                                                    {
    return GetOrAddNewConstantNode(int32_constants_, constant);
  }
References GetOrAddNewConstantNode(), and int32_constants_.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::ConvertTaggedPhiTo(), and v8::internal::maglev::MaglevGraphBuilder::GetInt32Constant().
GetIntPtrConstant()
IntPtrConstant* v8::internal::maglev::Graph::GetIntPtrConstant (intptr_t constant) [inline]
Definition at line 218 of file maglev-graph.h.
                                                       {
    return GetOrAddNewConstantNode(intptr_constants_, constant);
  }
References GetOrAddNewConstantNode(), and intptr_constants_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetIntPtrConstant().
GetOrAddNewConstantNode()
template<typename NodeT , typename T >
NodeT* v8::internal::maglev::Graph::GetOrAddNewConstantNode (ZoneMap< T, NodeT * > & container, T constant) [inline], [private]
Definition at line 317 of file maglev-graph.h.
                                                                            {
    auto it = container.find(constant);
    if (it == container.end()) {
      NodeT* node = CreateNewConstantNode<NodeT>(0, constant);
      container.emplace(constant, node);
      return node;
    }
    return it->second;
  }
Referenced by GetFloat64Constant(), GetInt32Constant(), GetIntPtrConstant(), GetRootConstant(), GetSmiConstant(), GetTaggedIndexConstant(), and GetUint32Constant().
GetRootConstant()
RootConstant* v8::internal::maglev::Graph::GetRootConstant (RootIndex index) [inline]
Definition at line 235 of file maglev-graph.h.
                                                 {
    return GetOrAddNewConstantNode(root_constants_, index);
  }
References GetOrAddNewConstantNode(), v8::internal::index, and root_constants_.
Referenced by GetBooleanConstant(), and v8::internal::maglev::MaglevGraphBuilder::GetRootConstant().
GetSmiConstant()
SmiConstant* v8::internal::maglev::Graph::GetSmiConstant (int constant) [inline]
Definition at line 204 of file maglev-graph.h.
                                            {
    DCHECK(Smi::IsValid(constant));
    return GetOrAddNewConstantNode(smi_constants_, constant);
  }
References v8::internal::DCHECK(), GetOrAddNewConstantNode(), v8::internal::Smi::IsValid(), and smi_constants_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::FromInt32ToTagged(), and v8::internal::maglev::MaglevGraphBuilder::GetSmiConstant().
GetTaggedIndexConstant()
TaggedIndexConstant* v8::internal::maglev::Graph::GetTaggedIndexConstant (int constant) [inline]
Definition at line 209 of file maglev-graph.h.
                                                            {
    DCHECK(TaggedIndex::IsValid(constant));
    return GetOrAddNewConstantNode(tagged_index_constants_, constant);
  }
References v8::internal::DCHECK(), GetOrAddNewConstantNode(), v8::internal::TaggedIndex::IsValid(), and tagged_index_constants_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetTaggedIndexConstant().
GetTrustedConstant()
ValueNode * v8::internal::maglev::Graph::GetTrustedConstant (compiler::HeapObjectRef ref, IndirectPointerTag tag) [inline]
Definition at line 478 of file maglev-graph.h.
                                                             {
#ifdef V8_ENABLE_SANDBOX
  auto it = trusted_constants_.find(ref);
  if (it == trusted_constants_.end()) {
    TrustedConstant* node = CreateNewConstantNode<TrustedConstant>(0, ref, tag);
    trusted_constants_.emplace(ref, node);
    return node;
  }
  SBXCHECK_EQ(it->second->tag(), tag);
  return it->second;
#else
  return GetConstant(ref);
#endif
}
References SBXCHECK_EQ.
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetTrustedConstant().
GetUint32Constant()
Uint32Constant* v8::internal::maglev::Graph::GetUint32Constant (uint32_t constant) [inline]
Definition at line 222 of file maglev-graph.h.
                                                       {
    return GetOrAddNewConstantNode(uint32_constants_, constant);
  }
References GetOrAddNewConstantNode(), and uint32_constants_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetUint32Constant().
graph_labeller()
MaglevGraphLabeller* v8::internal::maglev::Graph::graph_labeller () const [inline]
Definition at line 257 of file maglev-graph.h.
                                              {
    return compilation_info_->graph_labeller();
  }
References compilation_info_, and v8::internal::maglev::MaglevCompilationInfo::graph_labeller().
Referenced by CreateNewConstantNode(), v8::internal::maglev::MaglevGraphBuilder::graph_labeller(), v8::internal::maglev::MaglevPhiRepresentationSelector::graph_labeller(), v8::internal::maglev::StraightForwardRegisterAllocator::graph_labeller(), and v8::internal::maglev::MaglevPhiRepresentationSelector::RegisterNewNode().
has_graph_labeller()
bool v8::internal::maglev::Graph::has_graph_labeller () const [inline]
Definition at line 254 of file maglev-graph.h.
                                  {
    return compilation_info_->has_graph_labeller();
  }
References compilation_info_, and v8::internal::maglev::MaglevCompilationInfo::has_graph_labeller().
Referenced by CreateNewConstantNode(), v8::internal::maglev::MaglevGraphBuilder::graph_labeller(), v8::internal::maglev::MaglevGraphBuilder::has_graph_labeller(), v8::internal::maglev::StraightForwardRegisterAllocator::has_graph_labeller(), and v8::internal::maglev::MaglevPhiRepresentationSelector::RegisterNewNode().
has_recursive_calls()
bool v8::internal::maglev::Graph::has_recursive_calls () const [inline]
Definition at line 170 of file maglev-graph.h.
{ return has_recursive_calls_; }
References has_recursive_calls_.
has_resumable_generator()
bool v8::internal::maglev::Graph::has_resumable_generator () const [inline]
Definition at line 187 of file maglev-graph.h.
{ return has_resumable_generator_; }
References has_resumable_generator_.
inlineable_calls()
ZoneVector<MaglevCallSiteInfo*>& v8::internal::maglev::Graph::inlineable_calls () [inline]
Definition at line 144 of file maglev-graph.h.
                                                      {
    return inlineable_calls_;
  }
References inlineable_calls_.
Referenced by v8::internal::maglev::MaglevInliner::ChooseNextCallSite(), and v8::internal::maglev::MaglevInliner::Run().
inlined_functions()
ZoneVector<OptimizedCompilationInfo::InlinedFunctionHolder>& v8::internal::maglev::Graph::inlined_functions () [inline]
Definition at line 167 of file maglev-graph.h.
                      {
    return inlined_functions_;
  }
References inlined_functions_.
Referenced by v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), and v8::internal::maglev::MaglevCodeGenerator::RecordInlinedFunctions().
int32()
ZoneMap<int32_t, Int32Constant*>& v8::internal::maglev::Graph::int32 () [inline]
Definition at line 132 of file maglev-graph.h.
{ return int32_constants_; }
References int32_constants_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters().
intptr()
ZoneMap<intptr_t, IntPtrConstant*>& v8::internal::maglev::Graph::intptr () [inline]
Definition at line 134 of file maglev-graph.h.
{ return intptr_constants_; }
References intptr_constants_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters().
is_osr()
bool v8::internal::maglev::Graph::is_osr () const [inline]
Definition at line 173 of file maglev-graph.h.
                      {
    return compilation_info_->toplevel_compilation_unit()->is_osr();
  }
References compilation_info_, v8::internal::maglev::MaglevCompilationUnit::is_osr(), and v8::internal::maglev::MaglevCompilationInfo::toplevel_compilation_unit().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::MaglevGraphBuilder::bailout_for_entrypoint(), v8::internal::maglev::MaglevCodeGenerator::EmitCode(), v8::internal::maglev::MaglevGraphBuilder::EndPrologue(), v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForEntryStackCheck(), v8::internal::maglev::MaglevGraphBuilder::MaglevGraphBuilder(), min_maglev_stackslots_for_unoptimized_frame_size(), v8::internal::maglev::MaglevPhiRepresentationSelector::ProcessPhi(), v8::internal::maglev::MaglevGraphBuilder::ShouldEmitOsrInterruptBudgetChecks(), v8::internal::maglev::StraightForwardRegisterAllocator::StraightForwardRegisterAllocator(), and TryGetScopeInfo().
IterateGraphAndSweepDeadBlocks()
template<typename Function >
void v8::internal::maglev::Graph::IterateGraphAndSweepDeadBlocks (Function && is_dead) [inline], [private]
Definition at line 347 of file maglev-graph.h.
                                                          {
    auto current = blocks_.begin();
    auto last_non_dead = current;
    while (current != blocks_.end()) {
      if (is_dead(*current)) {
        (*current)->mark_dead();
      } else {
        if (current != last_non_dead) {
          // Move current to last non dead position.
          *last_non_dead = *current;
        }
        ++last_non_dead;
      }
      ++current;
    }
    if (current != last_non_dead) {
      blocks_.resize(blocks_.size() - (current - last_non_dead));
    }
  }
References v8::internal::ZoneVector< T >::begin(), blocks_, v8::internal::ZoneVector< T >::end(), v8::internal::ZoneVector< T >::resize(), and v8::internal::ZoneVector< T >::size().
Referenced by RemoveUnreachableBlocks().
last_block()
BasicBlock* v8::internal::maglev::Graph::last_block () const [inline]
Definition at line 70 of file maglev-graph.h.
{ return blocks_.back(); }
References v8::internal::ZoneVector< T >::back(), and blocks_.
max_block_id()
BasicBlock::Id v8::internal::maglev::Graph::max_block_id () const [inline]
Definition at line 252 of file maglev-graph.h.
{ return max_block_id_; }
References max_block_id_.
Referenced by RemoveUnreachableBlocks().
max_call_stack_args()
uint32_t v8::internal::maglev::Graph::max_call_stack_args () const [inline]
Definition at line 89 of file maglev-graph.h.
{ return max_call_stack_args_; }
References max_call_stack_args_.
max_deopted_stack_size()
uint32_t v8::internal::maglev::Graph::max_deopted_stack_size () const [inline]
Definition at line 90 of file maglev-graph.h.
{ return max_deopted_stack_size_; }
References max_deopted_stack_size_.
may_have_unreachable_blocks()
bool v8::internal::maglev::Graph::may_have_unreachable_blocks () const [inline]
Definition at line 191 of file maglev-graph.h.
                                           {
    return may_have_unreachable_blocks_;
  }
References may_have_unreachable_blocks_.
Referenced by RemoveUnreachableBlocks().
min_maglev_stackslots_for_unoptimized_frame_size()
uint32_t v8::internal::maglev::Graph::min_maglev_stackslots_for_unoptimized_frame_size () [inline]
Definition at line 176 of file maglev-graph.h.
                                                              {
    DCHECK(is_osr());
    if (osr_values().size() == 0) {
      return InitialValue::stack_slot(0);
    }
    return osr_values().back()->stack_slot() + 1;
  }
References v8::internal::DCHECK(), is_osr(), osr_values(), size(), and v8::internal::maglev::InitialValue::stack_slot().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::StraightForwardRegisterAllocator().
New()
static Graph* v8::internal::maglev::Graph::New (MaglevCompilationInfo * info) [inline], [static]
Definition at line 30 of file maglev-graph.h.
                                                 {
    return info->zone()->New<Graph>(info);
  }
References v8::internal::Zone::New(), and v8::internal::maglev::MaglevCompilationInfo::zone().
Referenced by v8::internal::maglev::MaglevCompiler::Compile().
NewObjectId()
uint32_t v8::internal::maglev::Graph::NewObjectId () [inline]
Definition at line 184 of file maglev-graph.h.
{ return object_ids_++; }
References object_ids_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::NewObjectId().
node_buffer()
ZoneVector<Node*>& v8::internal::maglev::Graph::node_buffer () [inline]
Definition at line 148 of file maglev-graph.h.
{ return node_buffer_; }
References node_buffer_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::node_buffer().
num_blocks()
int v8::internal::maglev::Graph::num_blocks () const [inline]
Definition at line 62 of file maglev-graph.h.
{ return static_cast<int>(blocks_.size()); }
References blocks_, and v8::internal::ZoneVector< T >::size().
operator[]() [1/2]
BasicBlock* v8::internal::maglev::Graph::operator[] (int i) [inline]
Definition at line 59 of file maglev-graph.h.
{ return blocks_[i]; }
References blocks_, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
operator[]() [2/2]
const BasicBlock* v8::internal::maglev::Graph::operator[] (int i) const [inline]
Definition at line 60 of file maglev-graph.h.
{ return blocks_[i]; }
References blocks_, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
osr_values()
ZoneVector<InitialValue*>& v8::internal::maglev::Graph::osr_values () [inline]
Definition at line 141 of file maglev-graph.h.
{ return osr_values_; }
References osr_values_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildRegisterFrameInitialization(), min_maglev_stackslots_for_unoptimized_frame_size(), and v8::internal::maglev::StraightForwardRegisterAllocator::StraightForwardRegisterAllocator().
parameters()
ZoneVector<InitialValue*>& v8::internal::maglev::Graph::parameters () [inline]
Definition at line 142 of file maglev-graph.h.
{ return parameters_; }
References parameters_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::Build().
rbegin()
BlockConstReverseIterator v8::internal::maglev::Graph::rbegin () const [inline]
Definition at line 67 of file maglev-graph.h.
{ return blocks_.rbegin(); }
References blocks_, and v8::internal::ZoneVector< T >::rbegin().
record_scope_info()
void v8::internal::maglev::Graph::record_scope_info (ValueNode * context, compiler::OptionalScopeInfoRef scope_info) [inline]
Definition at line 199 of file maglev-graph.h.
                                                                  {
    scope_infos_[context] = scope_info;
  }
References scope_infos_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::Build().
register_inputs()
RegList& v8::internal::maglev::Graph::register_inputs () [inline]
Definition at line 164 of file maglev-graph.h.
{ return register_inputs_; }
References register_inputs_.
RemoveUnreachableBlocks()
void v8::internal::maglev::Graph::RemoveUnreachableBlocks () [inline]
Definition at line 404 of file maglev-graph.h.
                                    {
  DCHECK(may_have_unreachable_blocks());
  std::vector<bool> reachable_blocks(max_block_id(), false);
  std::vector<BasicBlock*> worklist;
  DCHECK(!blocks().empty());
  BasicBlock* initial_bb = blocks().front();
  worklist.push_back(initial_bb);
  reachable_blocks[initial_bb->id()] = true;
  DCHECK(!initial_bb->is_loop());
  while (!worklist.empty()) {
    BasicBlock* current = worklist.back();
    worklist.pop_back();
    for (auto handler : current->exception_handlers()) {
      if (!handler->HasExceptionHandler()) continue;
      if (handler->ShouldLazyDeopt()) continue;
      BasicBlock* catch_block = handler->catch_block();
      if (!reachable_blocks[catch_block->id()]) {
        reachable_blocks[catch_block->id()] = true;
        worklist.push_back(catch_block);
      }
    }
    current->ForEachSuccessor([&](BasicBlock* succ) {
      if (!reachable_blocks[succ->id()]) {
        reachable_blocks[succ->id()] = true;
        worklist.push_back(succ);
      }
    });
  }
  // Sweep dead blocks and remove unreachable predecessors.
  IterateGraphAndSweepDeadBlocks([&](BasicBlock* bb) {
    if (!reachable_blocks[bb->id()]) return true;
    // If block doesn't have a merge state, it has only one predecessor, so
    // it must be the reachable one.
    if (!bb->has_state()) return false;
    if (bb->is_loop() && !reachable_blocks[bb->backedge_predecessor()->id()]) {
      // If the backedge predecessor is not reachable, we can turn the loop
      // into a regular block.
      bb->state()->TurnLoopIntoRegularBlock();
    }
    for (int i = bb->predecessor_count() - 1; i >= 0; i--) {
      if (!reachable_blocks[bb->predecessor_at(i)->id()]) {
        bb->state()->RemovePredecessorAt(i);
      }
    }
    return false;
  });
  set_may_have_unreachable_blocks(false);
}
References v8::internal::maglev::BasicBlock::backedge_predecessor(), blocks(), v8::internal::DCHECK(), v8::internal::maglev::BasicBlock::exception_handlers(), v8::internal::anonymous_namespace{json-stringifier.cc}::for(), v8::internal::maglev::BasicBlock::ForEachSuccessor(), v8::internal::ZoneVector< T >::front(), v8::internal::maglev::BasicBlock::has_state(), v8::internal::maglev::BasicBlock::id(), v8::internal::if(), v8::internal::maglev::BasicBlock::is_loop(), IterateGraphAndSweepDeadBlocks(), max_block_id(), may_have_unreachable_blocks(), and v8::internal::maglev::BasicBlock::predecessor_count().
rend()
BlockConstReverseIterator v8::internal::maglev::Graph::rend () const [inline]
Definition at line 68 of file maglev-graph.h.
{ return blocks_.rend(); }
References blocks_, and v8::internal::ZoneVector< T >::rend().
root()
ZoneMap<RootIndex, RootConstant*>& v8::internal::maglev::Graph::root () [inline]
Definition at line 127 of file maglev-graph.h.
{ return root_constants_; }
References root_constants_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters().
set_blocks()
void v8::internal::maglev::Graph::set_blocks (ZoneVector< BasicBlock * > blocks) [inline]
Definition at line 83 of file maglev-graph.h.
{ blocks_ = blocks; }
References blocks(), and blocks_.
set_has_recursive_calls()
void v8::internal::maglev::Graph::set_has_recursive_calls (bool value) [inline]
Definition at line 171 of file maglev-graph.h.
{ has_recursive_calls_ = value; }
References has_recursive_calls_, and v8::internal::value.
set_has_resumable_generator()
void v8::internal::maglev::Graph::set_has_resumable_generator () [inline]
Definition at line 186 of file maglev-graph.h.
{ has_resumable_generator_ = true; }
References has_resumable_generator_.
set_max_call_stack_args()
void v8::internal::maglev::Graph::set_max_call_stack_args (uint32_t stack_slots) [inline]
Definition at line 101 of file maglev-graph.h.
                                                     {
    DCHECK_EQ(kMaxUInt32, max_call_stack_args_);
    DCHECK_NE(kMaxUInt32, stack_slots);
    max_call_stack_args_ = stack_slots;
  }
References DCHECK_EQ, DCHECK_NE, v8::internal::kMaxUInt32, and max_call_stack_args_.
set_max_deopted_stack_size()
void v8::internal::maglev::Graph::set_max_deopted_stack_size (uint32_t size) [inline]
Definition at line 106 of file maglev-graph.h.
                                                 {
    DCHECK_EQ(kMaxUInt32, max_deopted_stack_size_);
    DCHECK_NE(kMaxUInt32, size);
    max_deopted_stack_size_ = size;
  }
References DCHECK_EQ, DCHECK_NE, v8::internal::kMaxUInt32, max_deopted_stack_size_, and size().
set_may_have_unreachable_blocks()
void v8::internal::maglev::Graph::set_may_have_unreachable_blocks (bool value = true) [inline]
Definition at line 188 of file maglev-graph.h.
                                                          {
    may_have_unreachable_blocks_ = value;
  }
References may_have_unreachable_blocks_, and v8::internal::value.
set_tagged_stack_slots()
void v8::internal::maglev::Graph::set_tagged_stack_slots (uint32_t stack_slots) [inline]
Definition at line 91 of file maglev-graph.h.
                                                    {
    DCHECK_EQ(kMaxUInt32, tagged_stack_slots_);
    DCHECK_NE(kMaxUInt32, stack_slots);
    tagged_stack_slots_ = stack_slots;
  }
References DCHECK_EQ, DCHECK_NE, v8::internal::kMaxUInt32, and tagged_stack_slots_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::StraightForwardRegisterAllocator().
set_untagged_stack_slots()
void v8::internal::maglev::Graph::set_untagged_stack_slots (uint32_t stack_slots) [inline]
Definition at line 96 of file maglev-graph.h.
                                                      {
    DCHECK_EQ(kMaxUInt32, untagged_stack_slots_);
    DCHECK_NE(kMaxUInt32, stack_slots);
    untagged_stack_slots_ = stack_slots;
  }
References DCHECK_EQ, DCHECK_NE, v8::internal::kMaxUInt32, and untagged_stack_slots_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::StraightForwardRegisterAllocator().
smi()
ZoneMap<int, SmiConstant*>& v8::internal::maglev::Graph::smi () [inline]
Definition at line 128 of file maglev-graph.h.
{ return smi_constants_; }
References smi_constants_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters().
tagged_index()
ZoneMap<int, TaggedIndexConstant*>& v8::internal::maglev::Graph::tagged_index () [inline]
Definition at line 129 of file maglev-graph.h.
                                                     {
    return tagged_index_constants_;
  }
References tagged_index_constants_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters().
tagged_stack_slots()
uint32_t v8::internal::maglev::Graph::tagged_stack_slots () const [inline]
Definition at line 87 of file maglev-graph.h.
{ return tagged_stack_slots_; }
References tagged_stack_slots_.
total_inlined_bytecode_size()
int v8::internal::maglev::Graph::total_inlined_bytecode_size () const [inline]
Definition at line 112 of file maglev-graph.h.
                                          {
    return total_inlined_bytecode_size_;
  }
References total_inlined_bytecode_size_.
Referenced by v8::internal::maglev::MaglevCodeGenerator::BuildCodeObject(), and v8::internal::maglev::MaglevInliner::Run().
total_peeled_bytecode_size()
int v8::internal::maglev::Graph::total_peeled_bytecode_size () const [inline]
Definition at line 119 of file maglev-graph.h.
{ return total_peeled_bytecode_size_; }
References total_peeled_bytecode_size_.
trusted_constants()
compiler::ZoneRefMap<compiler::HeapObjectRef, TrustedConstant*>& v8::internal::maglev::Graph::trusted_constants () [inline]
Definition at line 137 of file maglev-graph.h.
                      {
    return trusted_constants_;
  }
References trusted_constants_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters().
TryGetScopeInfo()
compiler::OptionalScopeInfoRef v8::internal::maglev::Graph::TryGetScopeInfo (ValueNode * context) [inline]
Definition at line 368 of file maglev-graph.h.
                                                                      {
  auto it = scope_infos_.find(context);
  if (it != scope_infos_.end()) {
    return it->second;
  }
  compiler::OptionalScopeInfoRef res;
  if (auto context_const = context->TryCast<Constant>()) {
    res = context_const->object().AsContext().scope_info(broker());
    DCHECK(res->HasContext());
  } else if (auto load =
                 context->TryCast<LoadTaggedFieldForContextSlotNoCells>()) {
    compiler::OptionalScopeInfoRef cur =
        TryGetScopeInfoForContextLoad(load->input(0).node(), load->offset());
    if (cur.has_value()) res = cur;
  } else if (auto load_script =
                 context->TryCast<LoadTaggedFieldForContextSlot>()) {
    compiler::OptionalScopeInfoRef cur = TryGetScopeInfoForContextLoad(
        load_script->input(0).node(), load_script->offset());
    if (cur.has_value()) res = cur;
  } else if (context->Is<InitialValue>()) {
    // We should only fail to keep track of initial contexts originating from
    // the OSR prequel.
    // TODO(olivf): Keep track of contexts when analyzing OSR Prequel.
    DCHECK(is_osr());
  } else {
    // Any context created within a function must be registered in
    // graph()->scope_infos(). Initial contexts must be registered before
    // BuildBody. We don't track context in generators (yet) and around eval
    // the bytecode compiler creates contexts by calling
    // Runtime::kNewFunctionInfo directly.
    DCHECK(context->Is<Phi>() || context->Is<GeneratorRestoreRegister>() ||
           context->Is<RegisterInput>() || context->Is<CallRuntime>());
  }
  return scope_infos_[context] = res;
}
References broker(), v8::internal::DCHECK(), v8::internal::maglev::NodeBase::Is(), is_osr(), scope_infos_, v8::internal::maglev::NodeBase::TryCast(), and TryGetScopeInfoForContextLoad().
Referenced by v8::internal::maglev::MaglevGraphBuilder::CheckContextExtensions(), v8::internal::maglev::MaglevGraphBuilder::ContextMayAlias(), v8::internal::maglev::MaglevGraphBuilder::StoreAndCacheContextSlot(), and TryGetScopeInfoForContextLoad().
TryGetScopeInfoForContextLoad()
compiler::OptionalScopeInfoRef v8::internal::maglev::Graph::TryGetScopeInfoForContextLoad (ValueNode * context, int offset) [inline], [private]
Definition at line 327 of file maglev-graph.h.
                                      {
    compiler::OptionalScopeInfoRef cur = TryGetScopeInfo(context);
    if (offset == Context::OffsetOfElementAt(Context::EXTENSION_INDEX)) {
      return cur;
    }
    CHECK_EQ(offset, Context::OffsetOfElementAt(Context::PREVIOUS_INDEX));
    if (cur.has_value()) {
      cur = (*cur).OuterScopeInfo(broker());
      while (!cur->HasContext() && cur->HasOuterScopeInfo()) {
        cur = cur->OuterScopeInfo(broker());
      }
      if (cur->HasContext()) {
        return cur;
      }
    }
    return {};
  }
References broker(), CHECK_EQ, v8::internal::Context::EXTENSION_INDEX, v8::internal::Context::OffsetOfElementAt(), v8::internal::Context::PREVIOUS_INDEX, and TryGetScopeInfo().
Referenced by TryGetScopeInfo().
uint32()
ZoneMap<uint32_t, Uint32Constant*>& v8::internal::maglev::Graph::uint32 () [inline]
Definition at line 133 of file maglev-graph.h.
{ return uint32_constants_; }
References uint32_constants_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters().
untagged_stack_slots()
uint32_t v8::internal::maglev::Graph::untagged_stack_slots () const [inline]
Definition at line 88 of file maglev-graph.h.
{ return untagged_stack_slots_; }
References untagged_stack_slots_.
zone()
Zone* v8::internal::maglev::Graph::zone () const [inline]
Definition at line 249 of file maglev-graph.h.
{ return compilation_info_->zone(); }
References compilation_info_, and v8::internal::maglev::MaglevCompilationInfo::zone().
Referenced by CreateNewConstantNode(), v8::internal::maglev::MaglevInliner::zone(), and v8::internal::maglev::MaglevPhiRepresentationSelector::zone().
Member Data Documentation
allocations_elide_map_
ZoneMap<InlinedAllocation*, SmallAllocationVector> v8::internal::maglev::Graph::allocations_elide_map_ [private]
Definition at line 280 of file maglev-graph.h.
Referenced by allocations_elide_map().
allocations_escape_map_
ZoneMap<InlinedAllocation*, SmallAllocationVector> v8::internal::maglev::Graph::allocations_escape_map_ [private]
Definition at line 279 of file maglev-graph.h.
Referenced by allocations_escape_map().
blocks_
ZoneVector<BasicBlock*> v8::internal::maglev::Graph::blocks_ [private]
Definition at line 267 of file maglev-graph.h.
Referenced by Add(), begin(), blocks(), end(), IterateGraphAndSweepDeadBlocks(), last_block(), num_blocks(), operator[](), rbegin(), rend(), and set_blocks().
compilation_info_
MaglevCompilationInfo* v8::internal::maglev::Graph::compilation_info_ [private]
Definition at line 262 of file maglev-graph.h.
Referenced by broker(), graph_labeller(), has_graph_labeller(), is_osr(), and zone().
constants_
compiler::ZoneRefMap<compiler::HeapObjectRef, Constant*> v8::internal::maglev::Graph::constants_ [private]
Definition at line 282 of file maglev-graph.h.
Referenced by constants().
float64_constants_
ZoneMap<uint64_t, Float64Constant*> v8::internal::maglev::Graph::float64_constants_ [private]
Definition at line 276 of file maglev-graph.h.
Referenced by float64(), and GetFloat64Constant().
graph_labeller_
std::unique_ptr<MaglevGraphLabeller> v8::internal::maglev::Graph::graph_labeller_ = {} [private]
Definition at line 297 of file maglev-graph.h.
has_recursive_calls_
bool v8::internal::maglev::Graph::has_recursive_calls_ = false [private]
Definition at line 289 of file maglev-graph.h.
Referenced by has_recursive_calls(), and set_has_recursive_calls().
has_resumable_generator_
bool v8::internal::maglev::Graph::has_resumable_generator_ = false [private]
Definition at line 293 of file maglev-graph.h.
Referenced by has_resumable_generator(), and set_has_resumable_generator().
inlineable_calls_
ZoneVector<MaglevCallSiteInfo*> v8::internal::maglev::Graph::inlineable_calls_ [private]
Definition at line 278 of file maglev-graph.h.
Referenced by inlineable_calls().
inlined_functions_
ZoneVector<OptimizedCompilationInfo::InlinedFunctionHolder> v8::internal::maglev::Graph::inlined_functions_ [private]
Definition at line 286 of file maglev-graph.h.
Referenced by inlined_functions().
int32_constants_
ZoneMap<int32_t, Int32Constant*> v8::internal::maglev::Graph::int32_constants_ [private]
Definition at line 272 of file maglev-graph.h.
Referenced by GetInt32Constant(), and int32().
intptr_constants_
ZoneMap<intptr_t, IntPtrConstant*> v8::internal::maglev::Graph::intptr_constants_ [private]
Definition at line 274 of file maglev-graph.h.
Referenced by GetIntPtrConstant(), and intptr().
max_block_id_
BasicBlock::Id v8::internal::maglev::Graph::max_block_id_ = 0 [private]
Definition at line 296 of file maglev-graph.h.
Referenced by Add(), and max_block_id().
max_call_stack_args_
uint32_t v8::internal::maglev::Graph::max_call_stack_args_ = kMaxUInt32 [private]
Definition at line 265 of file maglev-graph.h.
Referenced by max_call_stack_args(), and set_max_call_stack_args().
max_deopted_stack_size_
uint32_t v8::internal::maglev::Graph::max_deopted_stack_size_ = kMaxUInt32 [private]
Definition at line 266 of file maglev-graph.h.
Referenced by max_deopted_stack_size(), and set_max_deopted_stack_size().
may_have_unreachable_blocks_
bool v8::internal::maglev::Graph::may_have_unreachable_blocks_ = false [private]
Definition at line 294 of file maglev-graph.h.
Referenced by may_have_unreachable_blocks(), and set_may_have_unreachable_blocks().
node_buffer_
ZoneVector<Node*> v8::internal::maglev::Graph::node_buffer_ [private]
Definition at line 287 of file maglev-graph.h.
Referenced by Graph(), and node_buffer().
object_ids_
uint32_t v8::internal::maglev::Graph::object_ids_ = 0 [private]
Definition at line 292 of file maglev-graph.h.
Referenced by NewObjectId().
osr_values_
ZoneVector<InitialValue*> v8::internal::maglev::Graph::osr_values_ [private]
Definition at line 268 of file maglev-graph.h.
Referenced by osr_values().
parameters_
ZoneVector<InitialValue*> v8::internal::maglev::Graph::parameters_ [private]
Definition at line 277 of file maglev-graph.h.
Referenced by parameters().
register_inputs_
RegList v8::internal::maglev::Graph::register_inputs_ [private]
Definition at line 281 of file maglev-graph.h.
Referenced by register_inputs().
root_constants_
ZoneMap<RootIndex, RootConstant*> v8::internal::maglev::Graph::root_constants_ [private]
Definition at line 269 of file maglev-graph.h.
Referenced by GetRootConstant(), and root().
scope_infos_
ZoneUnorderedMap<ValueNode*, compiler::OptionalScopeInfoRef> v8::internal::maglev::Graph::scope_infos_ [private]
Definition at line 295 of file maglev-graph.h.
Referenced by record_scope_info(), and TryGetScopeInfo().
smi_constants_
ZoneMap<int, SmiConstant*> v8::internal::maglev::Graph::smi_constants_ [private]
Definition at line 270 of file maglev-graph.h.
Referenced by GetSmiConstant(), and smi().
tagged_index_constants_
ZoneMap<int, TaggedIndexConstant*> v8::internal::maglev::Graph::tagged_index_constants_ [private]
Definition at line 271 of file maglev-graph.h.
Referenced by GetTaggedIndexConstant(), and tagged_index().
tagged_stack_slots_
uint32_t v8::internal::maglev::Graph::tagged_stack_slots_ = kMaxUInt32 [private]
Definition at line 263 of file maglev-graph.h.
Referenced by set_tagged_stack_slots(), and tagged_stack_slots().
total_inlined_bytecode_size_
int v8::internal::maglev::Graph::total_inlined_bytecode_size_ = 0 [private]
Definition at line 290 of file maglev-graph.h.
Referenced by add_inlined_bytecode_size(), and total_inlined_bytecode_size().
total_peeled_bytecode_size_
int v8::internal::maglev::Graph::total_peeled_bytecode_size_ = 0 [private]
Definition at line 291 of file maglev-graph.h.
Referenced by add_peeled_bytecode_size(), and total_peeled_bytecode_size().
trusted_constants_
compiler::ZoneRefMap<compiler::HeapObjectRef, TrustedConstant*> v8::internal::maglev::Graph::trusted_constants_ [private]
Definition at line 284 of file maglev-graph.h.
Referenced by trusted_constants().
uint32_constants_
ZoneMap<uint32_t, Uint32Constant*> v8::internal::maglev::Graph::uint32_constants_ [private]
Definition at line 273 of file maglev-graph.h.
Referenced by GetUint32Constant(), and uint32().
untagged_stack_slots_
uint32_t v8::internal::maglev::Graph::untagged_stack_slots_ = kMaxUInt32 [private]
Definition at line 264 of file maglev-graph.h.
Referenced by set_untagged_stack_slots(), and untagged_stack_slots().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph.h