v8::internal::JSAPIObjectWithEmbedderSlots::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > object)
Additional Inherited Members
Detailed Description
Definition at line 172 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::JSAPIObjectWithEmbedderSlots::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 176 of file objects-body-descriptors-inl.h.
                                                                    {
    IterateJSAPIObjectWithEmbedderSlotsHeader(map, obj, object_size, v);
    IterateJSAPIObjectWithEmbedderSlotsTail<
        JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor>(
        map, obj, object_size, v);
  }
References v8::internal::JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor::IterateJSAPIObjectWithEmbedderSlotsHeader(), and v8::internal::JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor::IterateJSAPIObjectWithEmbedderSlotsTail().
Referenced by v8::internal::ScavengeVisitor::VisitJSApiObject().
SizeOf()
static int v8::internal::JSAPIObjectWithEmbedderSlots::BodyDescriptor::SizeOf (Tagged< Map > map, Tagged< HeapObject > object) [inline], [static]
Definition at line 184 of file objects-body-descriptors-inl.h.
                                                                       {
    return map->instance_size();
  }
Referenced by v8::internal::ScavengeVisitor::VisitJSApiObject().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h