v8_inspector::V8ConsoleMessage Class Reference
#include <v8-console-message.h>
Public Member Functions
~V8ConsoleMessage ()
V8MessageOrigin origin () const
void reportToFrontend (protocol::Console::Frontend *) const
void reportToFrontend (protocol::Runtime::Frontend *, V8InspectorSessionImpl *, bool generatePreview) const
ConsoleAPIType type () const
void contextDestroyed (int contextId)
int estimatedSize () const
Static Public Member Functions
static std::unique_ptr< V8ConsoleMessage > createForConsoleAPI (v8::Local< v8::Context > v8Context, int contextId, int groupId, V8InspectorImpl *inspector, double timestamp, ConsoleAPIType, v8::MemorySpan< const v8::Local< v8::Value >> arguments, const String16 &consoleContext, std::unique_ptr< V8StackTraceImpl >)
static std::unique_ptr< V8ConsoleMessage > createForException (double timestamp, const String16 &detailedMessage, const String16 &url, unsigned lineNumber, unsigned columnNumber, std::unique_ptr< V8StackTraceImpl >, int scriptId, v8::Isolate *, const String16 &message, int contextId, v8::Local< v8::Value > exception, unsigned exceptionId)
static std::unique_ptr< V8ConsoleMessage > createForRevokedException (double timestamp, const String16 &message, unsigned revokedExceptionId)
Private Types
using Arguments = std::vector< std::unique_ptr< v8::Global< v8::Value > >>
Private Member Functions
V8ConsoleMessage (V8MessageOrigin, double timestamp, const String16 &message)
std::unique_ptr< protocol::Array< protocol::Runtime::RemoteObject > > wrapArguments (V8InspectorSessionImpl *, bool generatePreview) const
std::unique_ptr< protocol::Runtime::RemoteObject > wrapException (V8InspectorSessionImpl *, bool generatePreview) const
void setLocation (const String16 &url, unsigned lineNumber, unsigned columnNumber, std::unique_ptr< V8StackTraceImpl >, int scriptId)
std::unique_ptr< protocol::DictionaryValue > getAssociatedExceptionData (V8InspectorImpl *inspector, V8InspectorSessionImpl *session) const
Private Attributes
V8MessageOrigin m_origin
double m_timestamp
String16 m_message
String16 m_url
unsigned m_lineNumber
unsigned m_columnNumber
std::unique_ptr< V8StackTraceImpl > m_stackTrace
int m_scriptId
int m_contextId
ConsoleAPIType m_type
unsigned m_exceptionId
unsigned m_revokedExceptionId
int m_v8Size = 0
Arguments m_arguments
String16 m_detailedMessage
String16 m_consoleContext
Detailed Description
Definition at line 48 of file v8-console-message.h.
Member Typedef Documentation
Arguments
using v8_inspector::V8ConsoleMessage::Arguments = std::vector<std::unique_ptr<v8::Global<v8::Value> >> [private]
Definition at line 82 of file v8-console-message.h.
Constructor & Destructor Documentation
 V8ConsoleMessage()
v8_inspector::V8ConsoleMessage::~V8ConsoleMessage () [default]
V8ConsoleMessage()
v8_inspector::V8ConsoleMessage::V8ConsoleMessage (V8MessageOrigin origin, double timestamp, const String16 & message) [private]
Definition at line 194 of file v8-console-message.cc.
    : m_origin(origin),
      m_timestamp(timestamp),
      m_message(message),
      m_lineNumber(0),
      m_columnNumber(0),
      m_scriptId(0),
      m_contextId(0),
      m_type(ConsoleAPIType::kLog),
      m_exceptionId(0),
      m_revokedExceptionId(0) {}
Referenced by createForConsoleAPI(), createForException(), and createForRevokedException().
Member Function Documentation
contextDestroyed()
void v8_inspector::V8ConsoleMessage::contextDestroyed (int contextId)
Definition at line 538 of file v8-console-message.cc.
                                                     {
  if (contextId != m_contextId) return;
  m_contextId = 0;
  if (m_message.isEmpty()) m_message = "<message collected>";
  Arguments empty;
  m_arguments.swap(empty);
  m_v8Size = 0;
}
References v8_inspector::String16::isEmpty(), m_arguments, m_contextId, m_message, and m_v8Size.
createForConsoleAPI()
std::unique_ptr< V8ConsoleMessage > v8_inspector::V8ConsoleMessage::createForConsoleAPI (v8::Local< v8::Context > v8Context, int contextId, int groupId, V8InspectorImpl * inspector, double timestamp, ConsoleAPIType type, v8::MemorySpan< const v8::Local< v8::Value >> arguments, const String16 & consoleContext, std::unique_ptr< V8StackTraceImpl > stackTrace) [static]
Definition at line 443 of file v8-console-message.cc.
                                                {
  v8::Isolate* isolate = v8::Isolate::GetCurrent();
  std::unique_ptr<V8ConsoleMessage> message(
      new V8ConsoleMessage(V8MessageOrigin::kConsole, timestamp, String16()));
  if (stackTrace && !stackTrace->isEmpty()) {
    message->m_url = toString16(stackTrace->topSourceURL());
    message->m_lineNumber = stackTrace->topLineNumber();
    message->m_columnNumber = stackTrace->topColumnNumber();
  }
  message->m_stackTrace = std::move(stackTrace);
  message->m_consoleContext = consoleContext;
  message->m_type = type;
  message->m_contextId = contextId;
  for (v8::Local<v8::Value> arg : arguments) {
    std::unique_ptr<v8::Global<v8::Value>> argument(
        new v8::Global<v8::Value>(isolate, arg));
    argument->AnnotateStrongRetainer(kGlobalConsoleMessageHandleLabel);
    message->m_arguments.push_back(std::move(argument));
    message->m_v8Size += v8::debug::EstimatedValueSize(isolate, arg);
  }
  bool sep = false;
  for (v8::Local<v8::Value> arg : arguments) {
    if (sep) {
      message->m_message += String16(" ");
    } else {
      sep = true;
    }
    message->m_message += V8ValueStringBuilder::toString(arg, v8Context);
  }
  v8::Isolate::MessageErrorLevel clientLevel = v8::Isolate::kMessageInfo;
  if (type == ConsoleAPIType::kDebug || type == ConsoleAPIType::kCount ||
      type == ConsoleAPIType::kTimeEnd) {
    clientLevel = v8::Isolate::kMessageDebug;
  } else if (type == ConsoleAPIType::kError ||
             type == ConsoleAPIType::kAssert) {
    clientLevel = v8::Isolate::kMessageError;
  } else if (type == ConsoleAPIType::kWarning) {
    clientLevel = v8::Isolate::kMessageWarning;
  } else if (type == ConsoleAPIType::kInfo) {
    clientLevel = v8::Isolate::kMessageInfo;
  } else if (type == ConsoleAPIType::kLog) {
    clientLevel = v8::Isolate::kMessageLog;
  }
  if (type != ConsoleAPIType::kClear) {
    inspector->client()->consoleAPIMessage(
        groupId, clientLevel, toStringView(message->m_message),
        toStringView(message->m_url), message->m_lineNumber,
        message->m_columnNumber, message->m_stackTrace.get());
  }
  return message;
}
References v8_inspector::V8InspectorImpl::client(), v8_inspector::V8InspectorClient::consoleAPIMessage(), v8::debug::EstimatedValueSize(), v8::Isolate::GetCurrent(), v8_inspector::kAssert, v8_inspector::kClear, v8_inspector::kConsole, v8_inspector::kCount, v8_inspector::kDebug, v8_inspector::kError, v8_inspector::anonymous_namespace{v8-console-message.cc}::kGlobalConsoleMessageHandleLabel, v8_inspector::kInfo, v8_inspector::kLog, v8::Isolate::kMessageDebug, v8::Isolate::kMessageError, v8::Isolate::kMessageInfo, v8::Isolate::kMessageLog, v8::Isolate::kMessageWarning, v8_inspector::kTimeEnd, v8_inspector::kWarning, v8_inspector::toString16(), v8_inspector::toStringView(), type(), and V8ConsoleMessage().
Referenced by v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::reportCall(), and v8_inspector::anonymous_namespace{custom-preview.cc}::reportError().
createForException()
std::unique_ptr< V8ConsoleMessage > v8_inspector::V8ConsoleMessage::createForException (double timestamp, const String16 & detailedMessage, const String16 & url, unsigned lineNumber, unsigned columnNumber, std::unique_ptr< V8StackTraceImpl > stackTrace, int scriptId, v8::Isolate * isolate, const String16 & message, int contextId, v8::Local< v8::Value > exception, unsigned exceptionId) [static]
Definition at line 505 of file v8-console-message.cc.
                                                      {
  std::unique_ptr<V8ConsoleMessage> consoleMessage(
      new V8ConsoleMessage(V8MessageOrigin::kException, timestamp, message));
  consoleMessage->setLocation(url, lineNumber, columnNumber,
                              std::move(stackTrace), scriptId);
  consoleMessage->m_exceptionId = exceptionId;
  consoleMessage->m_detailedMessage = detailedMessage;
  if (contextId && !exception.IsEmpty()) {
    consoleMessage->m_contextId = contextId;
    consoleMessage->m_arguments.push_back(
        std::unique_ptr<v8::Global<v8::Value>>(
            new v8::Global<v8::Value>(isolate, exception)));
    consoleMessage->m_v8Size +=
        v8::debug::EstimatedValueSize(isolate, exception);
  }
  return consoleMessage;
}
References v8::debug::EstimatedValueSize(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8_inspector::kException, and V8ConsoleMessage().
Referenced by v8_inspector::V8InspectorImpl::exceptionThrown().
createForRevokedException()
std::unique_ptr< V8ConsoleMessage > v8_inspector::V8ConsoleMessage::createForRevokedException (double timestamp, const String16 & message, unsigned revokedExceptionId) [static]
Definition at line 529 of file v8-console-message.cc.
                                 {
  std::unique_ptr<V8ConsoleMessage> message(new V8ConsoleMessage(
      V8MessageOrigin::kRevokedException, timestamp, messageText));
  message->m_revokedExceptionId = revokedExceptionId;
  return message;
}
References v8_inspector::kRevokedException, and V8ConsoleMessage().
Referenced by v8_inspector::V8InspectorImpl::exceptionRevoked().
estimatedSize()
int v8_inspector::V8ConsoleMessage::estimatedSize () const [inline]
Definition at line 75 of file v8-console-message.h.
                            {
    return m_v8Size + static_cast<int>(m_message.length() * sizeof(UChar));
  }
References v8_inspector::String16::length(), m_message, and m_v8Size.
getAssociatedExceptionData()
std::unique_ptr< protocol::DictionaryValue > v8_inspector::V8ConsoleMessage::getAssociatedExceptionData (V8InspectorImpl * inspector, V8InspectorSessionImpl * session) const [private]
Definition at line 407 of file v8-console-message.cc.
                                                                       {
  if (m_arguments.empty() || !m_contextId) return nullptr;
  DCHECK_EQ(1u, m_arguments.size());
  v8::Isolate* isolate = inspector->isolate();
  v8::HandleScope handles(isolate);
  v8::MaybeLocal<v8::Value> maybe_exception = m_arguments[0]->Get(isolate);
  v8::Local<v8::Value> exception;
  if (!maybe_exception.ToLocal(&exception)) return nullptr;
  return inspector->getAssociatedExceptionDataForProtocol(exception);
}
References DCHECK_EQ, v8_inspector::V8InspectorImpl::getAssociatedExceptionDataForProtocol(), v8_inspector::V8InspectorImpl::isolate(), m_arguments, m_contextId, and v8::MaybeLocal< T >::ToLocal().
Referenced by reportToFrontend().
origin()
V8MessageOrigin v8_inspector::V8ConsoleMessage::origin () const
Definition at line 438 of file v8-console-message.cc.
{ return m_origin; }
References m_origin.
Referenced by v8_inspector::V8ConsoleAgentImpl::reportMessage().
reportToFrontend() [1/2]
void v8_inspector::V8ConsoleMessage::reportToFrontend (protocol::Console::Frontend * frontend) const
Definition at line 228 of file v8-console-message.cc.
                                             {
  DCHECK_EQ(V8MessageOrigin::kConsole, m_origin);
  String16 level = protocol::Console::ConsoleMessage::LevelEnum::Log;
  if (m_type == ConsoleAPIType::kDebug || m_type == ConsoleAPIType::kCount ||
      m_type == ConsoleAPIType::kTimeEnd)
    level = protocol::Console::ConsoleMessage::LevelEnum::Debug;
  else if (m_type == ConsoleAPIType::kError ||
           m_type == ConsoleAPIType::kAssert)
    level = protocol::Console::ConsoleMessage::LevelEnum::Error;
  else if (m_type == ConsoleAPIType::kWarning)
    level = protocol::Console::ConsoleMessage::LevelEnum::Warning;
  else if (m_type == ConsoleAPIType::kInfo)
    level = protocol::Console::ConsoleMessage::LevelEnum::Info;
  std::unique_ptr<protocol::Console::ConsoleMessage> result =
      protocol::Console::ConsoleMessage::create()
          .setSource(protocol::Console::ConsoleMessage::SourceEnum::ConsoleApi)
          .setLevel(level)
          .setText(m_message)
          .build();
  if (m_lineNumber) result->setLine(m_lineNumber);
  if (m_columnNumber) result->setColumn(m_columnNumber);
  if (!m_url.isEmpty()) result->setUrl(m_url);
  frontend->messageAdded(std::move(result));
}
References DCHECK_EQ, v8::internal::torque::Error(), v8_inspector::String16::isEmpty(), v8_inspector::kAssert, v8_inspector::kConsole, v8_inspector::kCount, v8_inspector::kDebug, v8_inspector::kError, v8_inspector::kInfo, v8_inspector::kTimeEnd, v8_inspector::kWarning, m_columnNumber, m_lineNumber, m_message, m_origin, m_type, m_url, and v8::base::internal::result.
Referenced by v8_inspector::V8ConsoleAgentImpl::reportMessage(), and v8_inspector::V8RuntimeAgentImpl::reportMessage().
reportToFrontend() [2/2]
void v8_inspector::V8ConsoleMessage::reportToFrontend (protocol::Runtime::Frontend * frontend, V8InspectorSessionImpl * session, bool generatePreview) const
Definition at line 314 of file v8-console-message.cc.
                                                                    {
  int contextGroupId = session->contextGroupId();
  V8InspectorImpl* inspector = session->inspector();
  // Protect against reentrant debugger calls via interrupts.
  v8::debug::PostponeInterruptsScope no_interrupts(inspector->isolate());
  if (m_origin == V8MessageOrigin::kException) {
    if (!inspector->hasConsoleMessageStorage(contextGroupId)) return;
    v8::HandleScope scope(inspector->isolate());
    auto maybeScriptOrigin =
        v8::debug::GetScriptOrigin(inspector->isolate(), m_scriptId);
    const bool isSharedCrossOrigin =
        maybeScriptOrigin ? maybeScriptOrigin->Options().IsSharedCrossOrigin()
                          : false;
    std::unique_ptr<protocol::Runtime::RemoteObject> exception =
        isSharedCrossOrigin ? wrapException(session, generatePreview) : nullptr;
    const bool includeException = isSharedCrossOrigin && exception;
    std::unique_ptr<protocol::Runtime::ExceptionDetails> exceptionDetails =
        protocol::Runtime::ExceptionDetails::create()
            .setExceptionId(m_exceptionId)
            .setText(includeException
                         ? m_message
                         : (m_detailedMessage.length() ? m_detailedMessage
                                                       : m_message))
            .setLineNumber(m_lineNumber ? m_lineNumber - 1 : 0)
            .setColumnNumber(m_columnNumber ? m_columnNumber - 1 : 0)
            .build();
    if (m_scriptId)
      exceptionDetails->setScriptId(String16::fromInteger(m_scriptId));
    if (!m_url.isEmpty()) exceptionDetails->setUrl(m_url);
    if (m_stackTrace) {
      exceptionDetails->setStackTrace(
          m_stackTrace->buildInspectorObjectImpl(inspector->debugger()));
    }
    if (m_contextId) exceptionDetails->setExecutionContextId(m_contextId);
    if (includeException) {
      exceptionDetails->setException(std::move(exception));
    }
    std::unique_ptr<protocol::DictionaryValue> data =
        getAssociatedExceptionData(inspector, session);
    if (data) exceptionDetails->setExceptionMetaData(std::move(data));
    frontend->exceptionThrown(m_timestamp, std::move(exceptionDetails));
    return;
  }
  if (m_origin == V8MessageOrigin::kRevokedException) {
    frontend->exceptionRevoked(m_message, m_revokedExceptionId);
    return;
  }
  if (m_origin == V8MessageOrigin::kConsole) {
    std::unique_ptr<protocol::Array<protocol::Runtime::RemoteObject>>
        arguments = wrapArguments(session, generatePreview);
    if (!inspector->hasConsoleMessageStorage(contextGroupId)) return;
    if (!arguments) {
      arguments =
          std::make_unique<protocol::Array<protocol::Runtime::RemoteObject>>();
      if (!m_message.isEmpty()) {
        std::unique_ptr<protocol::Runtime::RemoteObject> messageArg =
            protocol::Runtime::RemoteObject::create()
                .setType(protocol::Runtime::RemoteObject::TypeEnum::String)
                .build();
        messageArg->setValue(protocol::StringValue::create(m_message));
        arguments->emplace_back(std::move(messageArg));
      }
    }
    std::optional<String16> consoleContext;
    if (!m_consoleContext.isEmpty()) consoleContext = m_consoleContext;
    std::unique_ptr<protocol::Runtime::StackTrace> stackTrace;
    if (m_stackTrace) {
      switch (m_type) {
        case ConsoleAPIType::kAssert:
        case ConsoleAPIType::kError:
        case ConsoleAPIType::kTrace:
        case ConsoleAPIType::kWarning:
          stackTrace =
              m_stackTrace->buildInspectorObjectImpl(inspector->debugger());
          break;
        default:
          stackTrace =
              m_stackTrace->buildInspectorObjectImpl(inspector->debugger(), 0);
          break;
      }
    }
    frontend->consoleAPICalled(
        consoleAPITypeValue(m_type), std::move(arguments), m_contextId,
        m_timestamp, std::move(stackTrace), std::move(consoleContext));
    return;
  }
  UNREACHABLE();
}
References v8_inspector::anonymous_namespace{v8-console-message.cc}::consoleAPITypeValue(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8_inspector::V8InspectorImpl::debugger(), v8_inspector::String16::fromInteger(), getAssociatedExceptionData(), v8::debug::GetScriptOrigin(), v8_inspector::V8InspectorImpl::hasConsoleMessageStorage(), v8_inspector::V8InspectorSessionImpl::inspector(), v8_inspector::String16::isEmpty(), v8_inspector::V8InspectorImpl::isolate(), v8_inspector::kAssert, v8_inspector::kConsole, v8_inspector::kError, v8_inspector::kException, v8_inspector::kRevokedException, v8_inspector::kTrace, v8_inspector::kWarning, v8_inspector::String16::length(), m_columnNumber, m_consoleContext, m_contextId, m_detailedMessage, m_exceptionId, m_lineNumber, m_message, m_origin, m_revokedExceptionId, m_scriptId, m_stackTrace, m_timestamp, m_type, m_url, UNREACHABLE, wrapArguments(), and wrapException().
setLocation()
void v8_inspector::V8ConsoleMessage::setLocation (const String16 & url, unsigned lineNumber, unsigned columnNumber, std::unique_ptr< V8StackTraceImpl > stackTrace, int scriptId) [private]
Definition at line 209 of file v8-console-message.cc.
                                                 {
  const char* dataURIPrefix = "data:";
  if (url.substring(0, strlen(dataURIPrefix)) == dataURIPrefix) {
    m_url = String16();
  } else {
    m_url = url;
  }
  m_lineNumber = lineNumber;
  m_columnNumber = columnNumber;
  m_stackTrace = std::move(stackTrace);
  m_scriptId = scriptId;
  if (!m_scriptId && m_stackTrace && !m_stackTrace->frames().empty()) {
    m_scriptId = m_stackTrace->frames()[0].scriptId;
  }
}
References m_columnNumber, m_lineNumber, m_scriptId, m_stackTrace, m_url, and v8_inspector::String16::substring().
type()
ConsoleAPIType v8_inspector::V8ConsoleMessage::type () const
Definition at line 440 of file v8-console-message.cc.
{ return m_type; }
References m_type.
Referenced by createForConsoleAPI().
wrapArguments()
std::unique_ptr< protocol::Array< protocol::Runtime::RemoteObject > > v8_inspector::V8ConsoleMessage::wrapArguments (V8InspectorSessionImpl * session, bool generatePreview) const [private]
Definition at line 255 of file v8-console-message.cc.
                                                            {
  V8InspectorImpl* inspector = session->inspector();
  int contextGroupId = session->contextGroupId();
  int contextId = m_contextId;
  if (m_arguments.empty() || !contextId) return nullptr;
  InspectedContext* inspectedContext =
      inspector->getContext(contextGroupId, contextId);
  if (!inspectedContext) return nullptr;
  v8::Isolate* isolate = inspectedContext->isolate();
  v8::HandleScope handles(isolate);
  v8::Local<v8::Context> context = inspectedContext->context();
  auto args =
      std::make_unique<protocol::Array<protocol::Runtime::RemoteObject>>();
  v8::Local<v8::Value> value = m_arguments[0]->Get(isolate);
  if (value->IsObject() && m_type == ConsoleAPIType::kTable &&
      generatePreview) {
    v8::MaybeLocal<v8::Array> columns;
    if (m_arguments.size() > 1) {
      v8::Local<v8::Value> secondArgument = m_arguments[1]->Get(isolate);
      if (secondArgument->IsArray()) {
        columns = secondArgument.As<v8::Array>();
      } else if (secondArgument->IsString()) {
        v8::TryCatch tryCatch(isolate);
        v8::Local<v8::Array> array = v8::Array::New(isolate);
        if (array->Set(context, 0, secondArgument).IsJust()) {
          columns = array;
        }
      }
    }
    std::unique_ptr<protocol::Runtime::RemoteObject> wrapped =
        session->wrapTable(context, value.As<v8::Object>(), columns);
    inspectedContext = inspector->getContext(contextGroupId, contextId);
    if (!inspectedContext) return nullptr;
    if (wrapped) {
      args->emplace_back(std::move(wrapped));
    } else {
      args = nullptr;
    }
  } else {
    for (size_t i = 0; i < m_arguments.size(); ++i) {
      std::unique_ptr<protocol::Runtime::RemoteObject> wrapped =
          session->wrapObject(context, m_arguments[i]->Get(isolate), "console",
                              generatePreview);
      inspectedContext = inspector->getContext(contextGroupId, contextId);
      if (!inspectedContext) return nullptr;
      if (!wrapped) {
        args = nullptr;
        break;
      }
      args->emplace_back(std::move(wrapped));
    }
  }
  return args;
}
References v8::base::args, v8::Local< T >::As(), v8_inspector::InspectedContext::context(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), v8::internal::compiler::turboshaft::Get(), v8_inspector::V8InspectorImpl::getContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8_inspector::V8InspectorSessionImpl::inspector(), v8::Value::IsArray(), v8_inspector::InspectedContext::isolate(), v8::Value::IsString(), v8_inspector::kTable, m_arguments, m_contextId, m_type, v8::Array::New(), v8::Object::Set(), v8::internal::value, v8_inspector::V8InspectorSessionImpl::wrapObject(), and v8_inspector::V8InspectorSessionImpl::wrapTable().
Referenced by reportToFrontend().
wrapException()
std::unique_ptr< protocol::Runtime::RemoteObject > v8_inspector::V8ConsoleMessage::wrapException (V8InspectorSessionImpl * session, bool generatePreview) const [private]
Definition at line 422 of file v8-console-message.cc.
                                                            {
  if (m_arguments.empty() || !m_contextId) return nullptr;
  DCHECK_EQ(1u, m_arguments.size());
  InspectedContext* inspectedContext =
      session->inspector()->getContext(session->contextGroupId(), m_contextId);
  if (!inspectedContext) return nullptr;
  v8::Isolate* isolate = inspectedContext->isolate();
  v8::HandleScope handles(isolate);
  // TODO(dgozman): should we use different object group?
  return session->wrapObject(inspectedContext->context(),
                             m_arguments[0]->Get(isolate), "console",
                             generatePreview);
}
References v8_inspector::InspectedContext::context(), v8_inspector::V8InspectorSessionImpl::contextGroupId(), DCHECK_EQ, v8_inspector::V8InspectorImpl::getContext(), v8_inspector::V8InspectorSessionImpl::inspector(), v8_inspector::InspectedContext::isolate(), m_arguments, m_contextId, and v8_inspector::V8InspectorSessionImpl::wrapObject().
Referenced by reportToFrontend().
Member Data Documentation
m_arguments
Arguments v8_inspector::V8ConsoleMessage::m_arguments [private]
Definition at line 106 of file v8-console-message.h.
Referenced by contextDestroyed(), getAssociatedExceptionData(), wrapArguments(), and wrapException().
m_columnNumber
unsigned v8_inspector::V8ConsoleMessage::m_columnNumber [private]
Definition at line 98 of file v8-console-message.h.
Referenced by reportToFrontend(), and setLocation().
m_consoleContext
String16 v8_inspector::V8ConsoleMessage::m_consoleContext [private]
Definition at line 108 of file v8-console-message.h.
Referenced by reportToFrontend().
m_contextId
int v8_inspector::V8ConsoleMessage::m_contextId [private]
Definition at line 101 of file v8-console-message.h.
Referenced by contextDestroyed(), getAssociatedExceptionData(), reportToFrontend(), wrapArguments(), and wrapException().
m_detailedMessage
String16 v8_inspector::V8ConsoleMessage::m_detailedMessage [private]
Definition at line 107 of file v8-console-message.h.
Referenced by reportToFrontend().
m_exceptionId
unsigned v8_inspector::V8ConsoleMessage::m_exceptionId [private]
Definition at line 103 of file v8-console-message.h.
Referenced by reportToFrontend().
m_lineNumber
unsigned v8_inspector::V8ConsoleMessage::m_lineNumber [private]
Definition at line 97 of file v8-console-message.h.
Referenced by reportToFrontend(), and setLocation().
m_message
String16 v8_inspector::V8ConsoleMessage::m_message [private]
Definition at line 95 of file v8-console-message.h.
Referenced by contextDestroyed(), estimatedSize(), and reportToFrontend().
m_origin
V8MessageOrigin v8_inspector::V8ConsoleMessage::m_origin [private]
Definition at line 93 of file v8-console-message.h.
Referenced by origin(), and reportToFrontend().
m_revokedExceptionId
unsigned v8_inspector::V8ConsoleMessage::m_revokedExceptionId [private]
Definition at line 104 of file v8-console-message.h.
Referenced by reportToFrontend().
m_scriptId
int v8_inspector::V8ConsoleMessage::m_scriptId [private]
Definition at line 100 of file v8-console-message.h.
Referenced by reportToFrontend(), and setLocation().
m_stackTrace
std::unique_ptr<V8StackTraceImpl> v8_inspector::V8ConsoleMessage::m_stackTrace [private]
Definition at line 99 of file v8-console-message.h.
Referenced by reportToFrontend(), and setLocation().
m_timestamp
double v8_inspector::V8ConsoleMessage::m_timestamp [private]
Definition at line 94 of file v8-console-message.h.
Referenced by reportToFrontend().
m_type
ConsoleAPIType v8_inspector::V8ConsoleMessage::m_type [private]
Definition at line 102 of file v8-console-message.h.
Referenced by reportToFrontend(), type(), and wrapArguments().
m_url
String16 v8_inspector::V8ConsoleMessage::m_url [private]
Definition at line 96 of file v8-console-message.h.
Referenced by reportToFrontend(), and setLocation().
m_v8Size
int v8_inspector::V8ConsoleMessage::m_v8Size = 0 [private]
Definition at line 105 of file v8-console-message.h.
Referenced by contextDestroyed(), and estimatedSize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-console-message.h
/mnt/V8SourceCode/src/inspector/v8-console-message.cc