v8::internal::SpaceIterator Class Reference
#include <spaces.h>
Public Member Functions
SpaceIterator (Heap *heap)
virtual ~SpaceIterator ()
bool HasNext ()
Space * Next ()
Private Attributes
Heap * heap_
int current_space_
Additional Inherited Members
Detailed Description
Definition at line 228 of file spaces.h.
Constructor & Destructor Documentation
SpaceIterator()
v8::internal::SpaceIterator::SpaceIterator (Heap * heap) [explicit]
Definition at line 43 of file spaces.cc.
    : heap_(heap), current_space_(FIRST_MUTABLE_SPACE) {}
 SpaceIterator()
v8::internal::SpaceIterator::~SpaceIterator () [virtual], [default]
Member Function Documentation
HasNext()
bool v8::internal::SpaceIterator::HasNext ()
Definition at line 48 of file spaces.cc.
                            {
  while (current_space_ <= LAST_MUTABLE_SPACE) {
    Space* space = heap_->space(current_space_);
    if (space) return true;
    ++current_space_;
  }
  // No more spaces left.
  return false;
}
References current_space_, heap_, v8::internal::LAST_MUTABLE_SPACE, space, and v8::internal::Heap::space().
Referenced by v8::internal::Heap::Available(), v8::internal::Heap::CommittedPhysicalMemory(), v8::internal::MemoryChunkIterator::HasNext(), v8::internal::HeapObjectIterator::HeapObjectIterator(), v8::internal::HeapObjectIterator::NextObject(), and v8::internal::Heap::SizeOfObjects().
Next()
Space * v8::internal::SpaceIterator::Next ()
Definition at line 59 of file spaces.cc.
                           {
  DCHECK_LE(current_space_, LAST_MUTABLE_SPACE);
  Space* space = heap_->space(current_space_++);
  DCHECK_NOT_NULL(space);
  return space;
}
References current_space_, DCHECK_LE, DCHECK_NOT_NULL, heap_, v8::internal::LAST_MUTABLE_SPACE, space, and v8::internal::Heap::space().
Referenced by v8::internal::MemoryChunkIterator::HasNext(), v8::internal::HeapObjectIterator::HeapObjectIterator(), and v8::internal::HeapObjectIterator::NextObject().
Member Data Documentation
current_space_
int v8::internal::SpaceIterator::current_space_ [private]
Definition at line 238 of file spaces.h.
Referenced by HasNext(), and Next().
heap_
Heap* v8::internal::SpaceIterator::heap_ [private]
Definition at line 237 of file spaces.h.
Referenced by HasNext(), and Next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/spaces.h
/mnt/V8SourceCode/src/heap/spaces.cc