v8::internal::Displacement Class Reference
#include <assembler-ia32.h>
Public Types
enum Type { UNCONDITIONAL_JUMP
, CODE_RELATIVE
, OTHER
, CODE_ABSOLUTE
 }
Public Member Functions
int data () const
Type type () const
void next (Label *L) const
void link_to (Label *L)
Displacement (int data)
Displacement (Label *L, Type type)
void print ()
Private Types
using TypeField = base::BitField< Type, 0, 2 >
using NextField = base::BitField< int, 2, 32 - 2 >
Private Member Functions
void init (Label *L, Type type)
Private Attributes
int data_
Detailed Description
Definition at line 342 of file assembler-ia32.h.
Member Typedef Documentation
NextField
using v8::internal::Displacement::NextField = base::BitField<int, 2, 32 - 2> [private]
Definition at line 367 of file assembler-ia32.h.
TypeField
using v8::internal::Displacement::TypeField = base::BitField<Type, 0, 2> [private]
Definition at line 366 of file assembler-ia32.h.
Member Enumeration Documentation
Type
enum v8::internal::Displacement::Type
Enumerator
UNCONDITIONAL_JUMP
CODE_RELATIVE
OTHER
CODE_ABSOLUTE
Definition at line 344 of file assembler-ia32.h.
{ UNCONDITIONAL_JUMP, CODE_RELATIVE, OTHER, CODE_ABSOLUTE };
Constructor & Destructor Documentation
Displacement() [1/2]
v8::internal::Displacement::Displacement (int data) [inline], [explicit]
Definition at line 354 of file assembler-ia32.h.
{ data_ = data; }
References data(), and data_.
Displacement() [2/2]
v8::internal::Displacement::Displacement (Label * L, Type type) [inline]
Definition at line 356 of file assembler-ia32.h.
{ init(L, type); }
References init(), v8::internal::L, and type().
Member Function Documentation
data()
int v8::internal::Displacement::data () const [inline]
Definition at line 346 of file assembler-ia32.h.
{ return data_; }
References data_.
Referenced by v8::internal::Assembler::disp_at_put(), Displacement(), and v8::internal::Assembler::emit_disp().
init()
void v8::internal::Displacement::init (Label * L, Type type) [private]
Referenced by Displacement(), and link_to().
link_to()
void v8::internal::Displacement::link_to (Label * L) [inline]
Definition at line 352 of file assembler-ia32.h.
{ init(L, type()); }
References init(), v8::internal::L, and type().
next()
void v8::internal::Displacement::next (Label * L) const [inline]
Definition at line 348 of file assembler-ia32.h.
                            {
    int n = NextField::decode(data_);
    n > 0 ? L->link_to(n) : L->Unuse();
  }
References data_, v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::L.
print()
void v8::internal::Displacement::print () [inline]
Definition at line 358 of file assembler-ia32.h.
               {
    PrintF("%s (%x) ", (type() == UNCONDITIONAL_JUMP ? "jmp" : "[other]"),
           NextField::decode(data_));
  }
References data_, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::PrintF(), type(), and UNCONDITIONAL_JUMP.
type()
Type v8::internal::Displacement::type () const [inline]
Definition at line 347 of file assembler-ia32.h.
{ return TypeField::decode(data_); }
References data_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by Displacement(), link_to(), and print().
Member Data Documentation
data_
int v8::internal::Displacement::data_ [private]
Definition at line 364 of file assembler-ia32.h.
Referenced by data(), Displacement(), next(), print(), and type().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/ia32/assembler-ia32.h