v8::internal::compiler::JSDefineKeyedOwnPropertyNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSDefineKeyedOwnPropertyNode (Node *node)
const PropertyAccess & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1331 of file js-operator.h.
Constructor & Destructor Documentation
JSDefineKeyedOwnPropertyNode()
constexpr v8::internal::compiler::JSDefineKeyedOwnPropertyNode::JSDefineKeyedOwnPropertyNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1333 of file js-operator.h.
      : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSDefineKeyedOwnProperty, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const PropertyAccess& v8::internal::compiler::JSDefineKeyedOwnPropertyNode::Parameters () const [inline]
Definition at line 1338 of file js-operator.h.
                                           {
    return PropertyAccessOf(node()->op());
  }
References v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::PropertyAccessOf().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineKeyedOwnProperty().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h