v8::internal::maglev::StoreFloat64 Class Reference
#include <maglev-ir.h>
Public Member Functions
StoreFloat64 (uint64_t bitfield, int offset)
int offset () const
Input & object_input ()
Input & value_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::CanWrite()
static constexpr Base::InputTypes kInputTypes
static constexpr int kObjectIndex = 0
static constexpr int kValueIndex = 1
Private Types
using Base = FixedInputNodeT< 2, StoreFloat64 >
Private Attributes
const int offset_
Additional Inherited Members
Detailed Description
Definition at line 8975 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::StoreFloat64::Base = FixedInputNodeT<2, StoreFloat64> [private]
Definition at line 8976 of file maglev-ir.h.
Constructor & Destructor Documentation
StoreFloat64()
v8::internal::maglev::StoreFloat64::StoreFloat64 (uint64_t bitfield, int offset) [inline], [explicit]
Definition at line 8979 of file maglev-ir.h.
      : Base(bitfield), offset_(offset) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::StoreFloat64::GenerateCode (MaglevAssembler * , const ProcessingState &)
object_input()
Input& v8::internal::maglev::StoreFloat64::object_input () [inline]
Definition at line 8990 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
offset()
int v8::internal::maglev::StoreFloat64::offset () const [inline]
Definition at line 8986 of file maglev-ir.h.
{ return offset_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::StoreFloat64::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8224 of file maglev-ir.cc.
                                                                          {
  os << "(0x" << std::hex << offset() << std::dec << ")";
}
References offset().
SetValueLocationConstraints()
void v8::internal::maglev::StoreFloat64::SetValueLocationConstraints ()
value_input()
Input& v8::internal::maglev::StoreFloat64::value_input () [inline]
Definition at line 8991 of file maglev-ir.h.
{ return input(kValueIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::StoreFloat64::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kFloat64}
Definition at line 8983 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::StoreFloat64::kObjectIndex = 0 [static], [constexpr]
Definition at line 8988 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::StoreFloat64::kProperties = OpProperties::CanWrite() [static], [constexpr]
Definition at line 8982 of file maglev-ir.h.
kValueIndex
constexpr int v8::internal::maglev::StoreFloat64::kValueIndex = 1 [static], [constexpr]
Definition at line 8989 of file maglev-ir.h.
offset_
const int v8::internal::maglev::StoreFloat64::offset_ [private]
Definition at line 8998 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc