v8::internal::compiler::LoopFinder Class Reference
#include <loop-analysis.h>
Static Public Member Functions
static LoopTree * BuildLoopTree (TFGraph *graph, TickCounter *tick_counter, Zone *temp_zone)
static bool HasMarkedExits (LoopTree *loop_tree, const LoopTree::Loop *loop)
Detailed Description
Definition at line 175 of file loop-analysis.h.
Member Function Documentation
BuildLoopTree()
LoopTree * v8::internal::compiler::LoopFinder::BuildLoopTree (TFGraph * graph, TickCounter * tick_counter, Zone * temp_zone) [static]
Definition at line 536 of file loop-analysis.cc.
                                                {
  LoopTree* loop_tree =
      graph->zone()->New<LoopTree>(graph->NodeCount(), graph->zone());
  LoopFinderImpl finder(graph, loop_tree, tick_counter, zone);
  finder.Run();
  if (v8_flags.trace_turbo_loop) {
    finder.Print();
  }
  return loop_tree;
}
References graph(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::LoopPeelingPhase::Run().
HasMarkedExits()
bool v8::internal::compiler::LoopFinder::HasMarkedExits (LoopTree * loop_tree, const LoopTree::Loop * loop) [static]
Definition at line 705 of file loop-analysis.cc.
                                                          {
  // Look for returns and if projections that are outside the loop but whose
  // control input is inside the loop.
  Node* loop_node = loop_tree->GetLoopControl(loop);
  for (Node* node : loop_tree->LoopNodes(loop)) {
    for (Node* use : node->uses()) {
      if (!loop_tree->Contains(loop, use)) {
        bool unmarked_exit;
        switch (node->opcode()) {
          case IrOpcode::kLoopExit:
            unmarked_exit = (node->InputAt(1) != loop_node);
            break;
          case IrOpcode::kLoopExitValue:
          case IrOpcode::kLoopExitEffect:
            unmarked_exit = (node->InputAt(1)->InputAt(1) != loop_node);
            break;
          default:
            unmarked_exit = (use->opcode() != IrOpcode::kTerminate);
        }
        if (unmarked_exit) {
          if (v8_flags.trace_turbo_loop) {
            PrintF(
                "Cannot peel loop %i. Loop exit without explicit mark: Node %i "
                "(%s) is inside loop, but its use %i (%s) is outside.\n",
                loop_node->id(), node->id(), node->op()->mnemonic(), use->id(),
                use->op()->mnemonic());
          }
          return false;
        }
      }
    }
  }
  return true;
}
References v8::internal::compiler::LoopTree::Contains(), v8::internal::compiler::LoopTree::GetLoopControl(), v8::internal::compiler::Node::id(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::LoopTree::LoopNodes(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::PrintF(), use(), v8::internal::compiler::Node::uses(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::LoopPeeler::CanPeel().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/loop-analysis.h
/mnt/V8SourceCode/src/compiler/loop-analysis.cc