v8::internal::JumpTableInfoWriter Class Reference
#include <jump-table-info.h>
Public Member Functions
V8_EXPORT_PRIVATE void Add (uint32_t pc_offset, int32_t target)
void Emit (Assembler *assm)
size_t entry_count () const
uint32_t size_in_bytes () const
Private Attributes
std::vector< JumpTableInfoEntry > entries_
Detailed Description
Definition at line 41 of file jump-table-info.h.
Member Function Documentation
Add()
void v8::internal::JumpTableInfoWriter::Add (uint32_t pc_offset, int32_t target)
Definition at line 14 of file jump-table-info.cc.
                                                                {
  entries_.emplace_back(pc_offset, target);
}
References entries_.
Emit()
void v8::internal::JumpTableInfoWriter::Emit (Assembler * assm)
Definition at line 24 of file jump-table-info.cc.
                                              {
  for (auto i = entries_.begin(); i != entries_.end(); ++i) {
    static_assert(JumpTableInfoEntry::kPCOffsetSize == kUInt32Size);
    assm->dd(i->pc_offset);
    static_assert(JumpTableInfoEntry::kTargetSize == kInt32Size);
    assm->dd(i->target);
    static_assert(JumpTableInfoEntry::kSize ==
                  JumpTableInfoEntry::kPCOffsetSize +
                      JumpTableInfoEntry::kTargetSize);
  }
}
References v8::internal::Assembler::dd(), entries_, v8::internal::kInt32Size, v8::internal::JumpTableInfoEntry::kPCOffsetSize, v8::internal::JumpTableInfoEntry::kSize, v8::internal::JumpTableInfoEntry::kTargetSize, and v8::internal::kUInt32Size.
entry_count()
size_t v8::internal::JumpTableInfoWriter::entry_count () const
Definition at line 18 of file jump-table-info.cc.
{ return entries_.size(); }
References entries_.
Referenced by size_in_bytes().
size_in_bytes()
uint32_t v8::internal::JumpTableInfoWriter::size_in_bytes () const
Definition at line 20 of file jump-table-info.cc.
                                                  {
  return static_cast<uint32_t>(entry_count() * JumpTableInfoEntry::kSize);
}
References entry_count(), and v8::internal::JumpTableInfoEntry::kSize.
Member Data Documentation
entries_
std::vector<JumpTableInfoEntry> v8::internal::JumpTableInfoWriter::entries_ [private]
Definition at line 50 of file jump-table-info.h.
Referenced by Add(), Emit(), and entry_count().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/jump-table-info.h
/mnt/V8SourceCode/src/codegen/jump-table-info.cc