v8::internal::ExternalReference Class Reference
#include <external-reference.h>
Public Types
enum Type {
BUILTIN_CALL
, BUILTIN_CALL_PAIR
, BUILTIN_COMPARE_CALL
, BUILTIN_FP_FP_CALL
,
BUILTIN_FP_CALL
, BUILTIN_FP_INT_CALL
, BUILTIN_FP_POINTER_CALL
, BUILTIN_INT_FP_CALL
,
DIRECT_API_CALL
, DIRECT_GETTER_CALL
, FAST_C_CALL
 }
Public Member Functions
ExternalReference ()
bool IsIsolateFieldId () const
Address raw () const
V8_EXPORT_PRIVATE Address address () const
int32_t offset_from_root_register () const
Static Public Member Functions
static V8_EXPORT_PRIVATE ExternalReference address_of_pending_message (LocalIsolate *local_isolate)
static ExternalReference Create (const SCTableReference &table_ref)
static ExternalReference Create (StatsCounter *counter)
static V8_EXPORT_PRIVATE ExternalReference Create (ApiFunction *ptr, Type type)
static V8_EXPORT_PRIVATE ExternalReference Create (Isolate *isolate, ApiFunction *ptr, Type type, Address *c_functions, const CFunctionInfo *const *c_signatures, unsigned num_functions)
static ExternalReference Create (const Runtime::Function *f)
static ExternalReference Create (IsolateAddressId id, Isolate *isolate)
static ExternalReference Create (Runtime::FunctionId id)
static ExternalReference Create (IsolateFieldId id)
static V8_EXPORT_PRIVATE ExternalReference Create (Address address, Type type=ExternalReference::BUILTIN_CALL)
template<typename SubjectChar , typename PatternChar >
static ExternalReference search_string_raw ()
static V8_EXPORT_PRIVATE ExternalReference FromRawAddress (Address address)
static V8_EXPORT_PRIVATE ExternalReference isolate_address ()
static V8_EXPORT_PRIVATE ExternalReference address_of_code_pointer_table_base_address ()
static V8_EXPORT_PRIVATE ExternalReference jslimit_address ()
V8_EXPORT_PRIVATE static V8_NOINLINE ExternalReference runtime_function_table_address_for_unittests (Isolate *isolate)
static V8_EXPORT_PRIVATE ExternalReference address_of_load_from_stack_count (const char *function_name)
static V8_EXPORT_PRIVATE ExternalReference address_of_store_to_stack_count (const char *function_name)
static ExternalReference invoke_function_callback (CallApiCallbackMode mode)
static Address Redirect (Address external_function, Type type=ExternalReference::BUILTIN_CALL)
static Address UnwrapRedirection (Address redirection_trampoline)
Static Public Attributes
static constexpr int kExternalReferenceCountIsolateIndependent
static constexpr int kExternalReferenceCountIsolateDependent
Private Member Functions
ExternalReference (Address address)
ExternalReference (void *address)
ExternalReference (IsolateFieldId id)
Private Attributes
Address raw_
Detailed Description
Definition at line 538 of file external-reference.h.
Member Enumeration Documentation
Type
enum v8::internal::ExternalReference::Type
Enumerator
BUILTIN_CALL
BUILTIN_CALL_PAIR
BUILTIN_COMPARE_CALL
BUILTIN_FP_FP_CALL
BUILTIN_FP_CALL
BUILTIN_FP_INT_CALL
BUILTIN_FP_POINTER_CALL
BUILTIN_INT_FP_CALL
DIRECT_API_CALL
DIRECT_GETTER_CALL
FAST_C_CALL
Definition at line 541 of file external-reference.h.
            {
    // Builtin call.
    // Address f(v8::internal::Arguments).
    BUILTIN_CALL, // default
    // Builtin call returning object pair.
    // ObjectPair f(v8::internal::Arguments).
    BUILTIN_CALL_PAIR,
    // TODO(mslekova): Once FAST_C_CALL is supported in the simulator,
    // the following four specific types and their special handling
    // can be removed, as the generic call supports them.
    // Builtin that takes float arguments and returns an int.
    // int f(double, double).
    BUILTIN_COMPARE_CALL,
    // Builtin call that returns floating point.
    // double f(double, double).
    BUILTIN_FP_FP_CALL,
    // Builtin call that returns floating point.
    // double f(double).
    BUILTIN_FP_CALL,
    // Builtin call that returns floating point.
    // double f(double, int).
    BUILTIN_FP_INT_CALL,
    // Builtin call that returns floating point.
    // double f(Address tagged_ptr).
    BUILTIN_FP_POINTER_CALL,
    // Builtin call that takes a double and returns an int.
    // int f(double).
    BUILTIN_INT_FP_CALL,
    // Direct call to API function callback.
    // void f(v8::FunctionCallbackInfo&)
    DIRECT_API_CALL,
    // Direct call to accessor getter callback.
    // void f(Local<Name> property, PropertyCallbackInfo& info)
    DIRECT_GETTER_CALL,
    // C call, either representing a fast API call or used in tests.
    // Can have arbitrary signature from the types supported by the fast API.
    FAST_C_CALL
  };
Constructor & Destructor Documentation
ExternalReference() [1/4]
v8::internal::ExternalReference::ExternalReference () [inline]
Definition at line 601 of file external-reference.h.
: raw_(kNullAddress) {}
Referenced by address_of_load_from_stack_count(), address_of_pending_message(), address_of_store_to_stack_count(), Create(), FromRawAddress(), v8::internal::FUNCTION_REFERENCE(), v8::internal::FUNCTION_REFERENCE_WITH_TYPE(), invoke_function_callback(), isolate_address(), jslimit_address(), and search_string_raw().
ExternalReference() [2/4]
v8::internal::ExternalReference::ExternalReference (Address address) [inline], [explicit], [private]
Definition at line 675 of file external-reference.h.
                                              : raw_(address) {
    CHECK(!IsIsolateFieldId());
  }
References CHECK.
ExternalReference() [3/4]
v8::internal::ExternalReference::ExternalReference (void * address) [inline], [explicit], [private]
Definition at line 679 of file external-reference.h.
      : raw_(reinterpret_cast<Address>(address)) {
    CHECK(!IsIsolateFieldId());
  }
References CHECK.
ExternalReference() [4/4]
v8::internal::ExternalReference::ExternalReference (IsolateFieldId id) [inline], [explicit], [private]
Definition at line 684 of file external-reference.h.
      : raw_(static_cast<Address>(id)) {}
Member Function Documentation
address()
Address v8::internal::ExternalReference::address () const
Definition at line 220 of file external-reference.cc.
                                         {
  // If this CHECK triggers, then an ExternalReference gets created with an
  // IsolateFieldId where the root register is not available, and therefore
  // IsolateFieldIds cannot be used, or ExternalReferences with IsolateFieldIds
  // don't get supported yet and support should be added.
  CHECK(!IsIsolateFieldId());
  return raw_;
}
References CHECK, IsIsolateFieldId(), and raw_.
Referenced by Create(), FromRawAddress(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateCCall(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateCCallWithStackBuffer(), v8::internal::maglev::MaglevGraphBuilder::gvn_hash_value(), v8::internal::MacroAssemblerBase::IsAddressableThroughRootRegister(), v8::internal::WasmCapiFunction::New(), v8::internal::Operand::Operand(), v8::internal::operator<<(), v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReference(), v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReferenceTableEntry(), and v8::internal::Runtime::RuntimeFunctionTable().
address_of_code_pointer_table_base_address()
static V8_EXPORT_PRIVATE ExternalReference v8::internal::ExternalReference::address_of_code_pointer_table_base_address () [static]
address_of_load_from_stack_count()
ExternalReference v8::internal::ExternalReference::address_of_load_from_stack_count (const char * function_name) [static]
Definition at line 913 of file external-reference.cc.
                               {
  return ExternalReference(
      Isolate::load_from_stack_count_address(function_name));
}
References ExternalReference(), and v8::internal::Isolate::load_from_stack_count_address().
Referenced by v8::internal::compiler::CodeGenerator::IncrementStackAccessCounter().
address_of_pending_message()
ExternalReference v8::internal::ExternalReference::address_of_pending_message (LocalIsolate * local_isolate) [static]
Definition at line 860 of file external-reference.cc.
                      {
  return ExternalReference(isolate->pending_message_address());
}
References ExternalReference().
Referenced by v8::internal::compiler::JSGraphAssembler::ClearPendingMessage(), v8::internal::CodeStubAssembler::GetPendingMessage(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadMessage(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreMessage(), and v8::internal::CodeStubAssembler::SetPendingMessage().
address_of_store_to_stack_count()
ExternalReference v8::internal::ExternalReference::address_of_store_to_stack_count (const char * function_name) [static]
Definition at line 919 of file external-reference.cc.
                               {
  return ExternalReference(
      Isolate::store_to_stack_count_address(function_name));
}
References ExternalReference(), and v8::internal::Isolate::store_to_stack_count_address().
Referenced by v8::internal::compiler::CodeGenerator::IncrementStackAccessCounter().
Create() [1/9]
ExternalReference v8::internal::ExternalReference::Create (Address address, Type type = ExternalReference::BUILTIN_CALL) [static]
Definition at line 278 of file external-reference.cc.
                                                                      {
  return ExternalReference(Redirect(address, type));
}
References address(), ExternalReference(), Redirect(), and v8::internal::tracing::type.
Create() [2/9]
ExternalReference v8::internal::ExternalReference::Create (ApiFunction * ptr, Type type) [static]
Definition at line 246 of file external-reference.cc.
                                                                       {
  return ExternalReference(Redirect(fun->address(), type));
}
References v8::ApiFunction::address(), ExternalReference(), Redirect(), and v8::internal::tracing::type.
Create() [3/9]
ExternalReference v8::internal::ExternalReference::Create (const Runtime::Function * f) [static]
Definition at line 272 of file external-reference.cc.
                                                                    {
  return ExternalReference(
      Redirect(f->entry, BuiltinCallTypeForResultSize(f->result_size)));
}
References v8::internal::BuiltinCallTypeForResultSize(), v8::internal::Runtime::Function::entry, ExternalReference(), Redirect(), and v8::internal::Runtime::Function::result_size.
Create() [4/9]
ExternalReference v8::internal::ExternalReference::Create (const SCTableReference & table_ref) [static]
Definition at line 420 of file external-reference.cc.
                                                                             {
  return ExternalReference(table_ref.address());
}
References v8::internal::SCTableReference::address(), and ExternalReference().
Referenced by v8::internal::ExternalReferenceTable::AddBuiltins(), v8::internal::ExternalReferenceTable::AddRuntimeFunctions(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::compiler::WasmGraphBuilder::BuildCallToRuntimeWithContext(), v8::internal::MacroAssembler::CallRuntime(), v8::internal::wasm::WasmGraphBuilderBase::CallRuntime(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallRuntimeImpl(), v8::internal::compiler::CodeAssembler::CallRuntimeImpl(), Create(), v8::internal::CodeStubAssembler::DecrementCounter(), v8::internal::MacroAssembler::EmitDecrementCounter(), v8::internal::MacroAssembler::EmitIncrementCounter(), v8::internal::compiler::MachineGraph::ExternalConstant(), v8::internal::MacroAssembler::ExternalReferenceAsOperand(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::Builtins::Generate_Adaptor(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry(), v8::internal::Generate_JSEntryTrampolineHelper(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_JSEntryVariant(), v8::internal::MicrotaskQueueBuiltinsAssembler::GetCurrentContext(), v8::internal::CodeStubAssembler::IncrementCounter(), v8::internal::compiler::CodeAssembler::IsolateField(), v8::internal::compiler::GraphAssembler::IsolateField(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::IsolateField(), v8::internal::MacroAssembler::LoadIsolateField(), v8::internal::WasmCapiFunction::New(), v8::internal::MacroAssembler::PopStackHandler(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::PropagateException(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::MacroAssembler::PushStackHandler(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::Runtime::RuntimeFunctionTable(), v8::internal::CodeStubAssembler::SetCounter(), v8::internal::MicrotaskQueueBuiltinsAssembler::SetCurrentContext(), v8::internal::MacroAssembler::TailCallRuntime(), v8::internal::compiler::CodeAssembler::TailCallRuntimeImpl(), v8::internal::AccessorAssembler::TryProbeStubCacheTable(), v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi(), and v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::WrapFastCall().
Create() [5/9]
ExternalReference v8::internal::ExternalReference::Create (Isolate * isolate, ApiFunction * ptr, Type type, Address * c_functions, const CFunctionInfo *const * c_signatures, unsigned num_functions) [static]
Definition at line 251 of file external-reference.cc.
                                                                      {
#ifdef V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
  isolate->simulator_data()->RegisterFunctionsAndSignatures(
      c_functions, c_signatures, num_functions);
#endif // V8_USE_SIMULATOR_WITH_GENERIC_C_CALLS
  return ExternalReference(Redirect(fun->address(), type));
}
References v8::ApiFunction::address(), ExternalReference(), Redirect(), and v8::internal::tracing::type.
Create() [6/9]
ExternalReference v8::internal::ExternalReference::Create (IsolateAddressId id, Isolate * isolate) [static]
Definition at line 414 of file external-reference.cc.
                                                              {
  return ExternalReference(isolate->get_address_from_id(id));
}
References ExternalReference(), and v8::internal::Isolate::get_address_from_id().
Create() [7/9]
ExternalReference v8::internal::ExternalReference::Create (IsolateFieldId id) [static]
Definition at line 267 of file external-reference.cc.
                                                             {
  return ExternalReference(id);
}
References ExternalReference().
Create() [8/9]
ExternalReference v8::internal::ExternalReference::Create (Runtime::FunctionId id) [static]
Definition at line 262 of file external-reference.cc.
                                                                {
  return Create(Runtime::FunctionForId(id));
}
References Create(), and v8::internal::Runtime::FunctionForId().
Create() [9/9]
ExternalReference v8::internal::ExternalReference::Create (StatsCounter * counter) [static]
Definition at line 408 of file external-reference.cc.
                                                                 {
  return ExternalReference(
      reinterpret_cast<Address>(counter->GetInternalPointer()));
}
References ExternalReference(), and v8::internal::StatsCounter::GetInternalPointer().
FromRawAddress()
ExternalReference v8::internal::ExternalReference::FromRawAddress (Address address) [static]
Definition at line 1618 of file external-reference.cc.
                                                                   {
  if (address <= static_cast<Address>(kNumIsolateFieldIds)) {
    return ExternalReference(static_cast<IsolateFieldId>(address));
  }
  return ExternalReference(address);
}
References address(), ExternalReference(), and v8::internal::kNumIsolateFieldIds.
Referenced by v8::internal::compiler::Constant::ToExternalReference().
invoke_function_callback()
ExternalReference v8::internal::ExternalReference::invoke_function_callback (CallApiCallbackMode mode) [static]
Definition at line 1087 of file external-reference.cc.
                              {
  switch (mode) {
    case CallApiCallbackMode::kGeneric:
      return invoke_function_callback_generic();
    case CallApiCallbackMode::kOptimized:
      return invoke_function_callback_optimized();
    case CallApiCallbackMode::kOptimizedNoProfiling:
      return ExternalReference();
  }
}
References ExternalReference(), v8::internal::kGeneric, v8::internal::kOptimized, v8::internal::kOptimizedNoProfiling, and mode().
IsIsolateFieldId()
bool v8::internal::ExternalReference::IsIsolateFieldId () const
Definition at line 216 of file external-reference.cc.
                                               {
  return (raw_ > 0 && raw_ <= static_cast<Address>(kNumIsolateFieldIds));
}
References v8::internal::kNumIsolateFieldIds, and raw_.
Referenced by address(), v8::internal::MacroAssembler::ExternalReferenceAsOperand(), v8::internal::MacroAssemblerBase::IsAddressableThroughRootRegister(), v8::internal::MacroAssembler::li(), offset_from_root_register(), v8::internal::operator<<(), and v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReference().
isolate_address()
ExternalReference v8::internal::ExternalReference::isolate_address () [static]
Definition at line 282 of file external-reference.cc.
                                                                     {
  return ExternalReference(isolate);
}
References ExternalReference().
Referenced by v8::internal::compiler::CodeGenerator::AssembleReturn(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::BuildAllocateJSExternalObject(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildSwitchBackFromCentralStack(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::BuildSwitchToTheCentralStack(), v8::internal::CollectionsBuiltinsAssembler::CallGetHashRaw(), v8::internal::CollectionsBuiltinsAssembler::CallGetOrCreateHashRaw(), v8::internal::RegExpMacroAssemblerRISCV::CallIsCharacterInRangeArray(), v8::internal::ArrayBuiltinsAssembler::CallJSArrayArrayJoinConcatToSequentialString(), v8::internal::StringBuiltinsAssembler::CallSearchStringRaw(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CheckEqualsInternalizedString(), v8::internal::RegExpMacroAssemblerRISCV::CheckNotBackReferenceIgnoreCase(), v8::internal::wasm::LiftoffAssembler::CheckStackShrink(), v8::internal::CodeStubAssembler::ComputeSeededHash(), v8::internal::WeakCollectionsBuiltinsAssembler::CreateIdentityHash(), v8::internal::compiler::turboshaft::FastApiCallLoweringReducer< Next >::FastApiCall(), v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector(), v8::internal::DateBuiltinsAssembler::Generate_DatePrototype_GetField(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry(), v8::internal::WriteBarrierCodeStubAssembler::GenerateEphemeronKeyBarrier(), v8::internal::RegExpMacroAssemblerRISCV::GetCode(), v8::internal::CodeStubAssembler::GetCoverageInfo(), v8::internal::CodeStubAssembler::LoadNameRawHash(), v8::internal::wasm::LiftoffAssembler::LoadOldFramePointer(), v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector(), v8::internal::CodeStubAssembler::RefillMathRandom(), v8::internal::RegExpBuiltinsAssembler::RegExpExecAtom(), v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal(), v8::internal::compiler::turboshaft::GrowableStacksReducer< Next >::Return(), v8::internal::CodeStubAssembler::SmiLexicographicCompare(), v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchStacks(), v8::internal::TF_BUILTIN(), v8::internal::CodeStubAssembler::TryInternalizeString(), and v8::internal::CodeStubAssembler::TryToName().
jslimit_address()
ExternalReference v8::internal::ExternalReference::jslimit_address () [static]
Definition at line 290 of file external-reference.cc.
                                                     {
  return ExternalReference(IsolateFieldId::kJsLimitAddress);
}
References ExternalReference().
offset_from_root_register()
int32_t v8::internal::ExternalReference::offset_from_root_register () const
Definition at line 229 of file external-reference.cc.
                                                           {
  CHECK(IsIsolateFieldId());
  return static_cast<int32_t>(
      IsolateData::GetOffset(static_cast<IsolateFieldId>(raw_)));
}
References CHECK, v8::internal::IsolateData::GetOffset(), IsIsolateFieldId(), and raw_.
Referenced by v8::internal::MacroAssembler::ExternalReferenceAsOperand(), v8::internal::MacroAssembler::li(), and v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReference().
raw()
Address v8::internal::ExternalReference::raw () const [inline]
Definition at line 654 of file external-reference.h.
{ return raw_; }
Referenced by v8::internal::hash_value(), v8::internal::ImmediateInitializer< ExternalReference >::immediate_for(), v8::internal::operator<<(), and v8::internal::compiler::turboshaft::ConstantOp::operator==().
Redirect()
Address v8::internal::ExternalReference::Redirect (Address external_function, Type type = ExternalReference::BUILTIN_CALL) [static]
Definition at line 575 of file external-reference.cc.
                                                                        {
#ifdef USE_SIMULATOR
  return SimulatorBase::RedirectExternalReference(external_function, type);
#else
  return external_function;
#endif
}
References v8::internal::tracing::type.
Referenced by Create(), v8::internal::FUNCTION_REFERENCE(), v8::internal::FUNCTION_REFERENCE_WITH_TYPE(), v8::internal::FunctionTemplateInfo::init_callback_redirection(), v8::internal::AccessorInfo::init_getter_redirection(), and search_string_raw().
runtime_function_table_address_for_unittests()
V8_EXPORT_PRIVATE static V8_NOINLINE ExternalReference v8::internal::ExternalReference::runtime_function_table_address_for_unittests (Isolate * isolate) [static]
search_string_raw()
template<typename SubjectChar , typename PatternChar >
MutableBigInt_AbsoluteCompare MutableBigInt_AbsoluteMulAndCanonicalize MutableBigInt_AbsoluteModAndCanonicalize MutableBigInt_BitwiseAndNegNegAndCanonicalize MutableBigInt_BitwiseOrPosPosAndCanonicalize MutableBigInt_BitwiseOrPosNegAndCanonicalize MutableBigInt_BitwiseXorNegNegAndCanonicalize MutableBigInt_LeftShiftAndCanonicalize MutableBigInt_RightShiftAndCanonicalize template ExternalReference v8::internal::ExternalReference::search_string_raw< const uint8_t, const uint8_t > () [static]
Definition at line 1292 of file external-reference.cc.
                                                       {
  auto f = SearchStringRaw<SubjectChar, PatternChar>;
  return ExternalReference(Redirect(FUNCTION_ADDR(f)));
}
References ExternalReference(), FUNCTION_ADDR, and Redirect().
UnwrapRedirection()
Address v8::internal::ExternalReference::UnwrapRedirection (Address redirection_trampoline) [static]
Definition at line 584 of file external-reference.cc.
                                                                           {
#ifdef USE_SIMULATOR
  return SimulatorBase::UnwrapRedirection(redirection_trampoline);
#else
  return redirection_trampoline;
#endif
}
Member Data Documentation
kExternalReferenceCountIsolateDependent
constexpr int v8::internal::ExternalReference::kExternalReferenceCountIsolateDependent [static], [constexpr]
Initial value:
=
      EXTERNAL_REFERENCE_LIST_WITH_ISOLATE(COUNT_EXTERNAL_REFERENCE)
Definition at line 594 of file external-reference.h.
kExternalReferenceCountIsolateIndependent
constexpr int v8::internal::ExternalReference::kExternalReferenceCountIsolateIndependent [static], [constexpr]
Initial value:
=
      EXTERNAL_REFERENCE_LIST(COUNT_EXTERNAL_REFERENCE)
Definition at line 592 of file external-reference.h.
raw_
Address v8::internal::ExternalReference::raw_ [private]
Definition at line 687 of file external-reference.h.
Referenced by address(), IsIsolateFieldId(), and offset_from_root_register().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/external-reference.h
/mnt/V8SourceCode/src/codegen/external-reference.cc