v8::internal::IncrementalStringBuilder Class Reference
#include <string-builder.h>
Public Member Functions
IncrementalStringBuilder (Isolate *isolate)
String::Encoding CurrentEncoding ()
template<typename SrcChar , typename DestChar >
void Append (SrcChar c)
void AppendCharacter (uint8_t c)
template<int N>
void AppendCStringLiteral (const char(&literal)[N])
template<typename SrcChar >
void AppendCString (const SrcChar *s)
void AppendString (std::string_view str)
void AppendInt (int i)
bool CurrentPartCanFit (int length)
int EscapedLengthIfCurrentPartFits (int length)
void AppendString (DirectHandle< String > string)
MaybeDirectHandle< String > Finish ()
bool HasOverflowed () const
int Length () const
void ChangeEncoding ()
Isolate * isolate ()
Private Member Functions
Factory * factory ()
DirectHandle< String > accumulator ()
void set_accumulator (DirectHandle< String > string)
DirectHandle< String > current_part ()
void set_current_part (DirectHandle< String > string)
void Accumulate (DirectHandle< String > new_part)
void Extend ()
bool HasValidCurrentIndex () const
void ShrinkCurrentPart ()
void AppendStringByCopy (DirectHandle< String > string)
bool CanAppendByCopy (DirectHandle< String > string)
Private Attributes
Isolate * isolate_
String::Encoding encoding_
bool overflowed_
int part_length_
int current_index_
DirectHandle< String > accumulator_
DirectHandle< String > current_part_
Static Private Attributes
static const int kInitialPartLength = 32
static const int kMaxPartLength = 16 * 1024
static const int kPartLengthGrowthFactor = 2
static const int kIntToStringViewBufferSize = sizeof(`-2147483648`) - 1
Detailed Description
Definition at line 79 of file string-builder.h.
Constructor & Destructor Documentation
IncrementalStringBuilder()
v8::internal::IncrementalStringBuilder::IncrementalStringBuilder (Isolate * isolate) [explicit]
Definition at line 244 of file string-builder.cc.
    : isolate_(isolate),
      encoding_(String::ONE_BYTE_ENCODING),
      overflowed_(false),
      part_length_(kInitialPartLength),
      current_index_(0) {
  // Create an accumulator handle starting with the empty string.
  accumulator_ =
      DirectHandle<String>::New(ReadOnlyRoots(isolate).empty_string(), isolate);
  current_part_ =
      factory()->NewRawOneByteString(part_length_).ToHandleChecked();
}
References accumulator_, current_part_, factory(), isolate(), v8::internal::DirectHandle< T >::New(), v8::internal::FactoryBase< Impl >::NewRawOneByteString(), and part_length_.
Member Function Documentation
Accumulate()
void v8::internal::IncrementalStringBuilder::Accumulate (DirectHandle< String > new_part) [private]
Definition at line 265 of file string-builder.cc.
                                                                       {
  DirectHandle<String> new_accumulator;
  if (accumulator()->length() + new_part->length() > String::kMaxLength) {
    // Set the flag and carry on. Delay throwing the exception till the end.
    new_accumulator = factory()->empty_string();
    overflowed_ = true;
  } else {
    new_accumulator =
        factory()
            ->NewConsString(indirect_handle(accumulator(), isolate_),
                            indirect_handle(new_part, isolate_))
            .ToHandleChecked();
  }
  set_accumulator(new_accumulator);
}
References accumulator(), factory(), v8::internal::indirect_handle(), isolate_, v8::internal::String::kMaxLength, v8::internal::length, v8::internal::FactoryBase< Impl >::NewConsString(), overflowed_, and set_accumulator().
Referenced by AppendString(), Extend(), and Finish().
accumulator()
DirectHandle<String> v8::internal::IncrementalStringBuilder::accumulator () [inline], [private]
Definition at line 123 of file string-builder.h.
{ return accumulator_; }
References accumulator_.
Referenced by Accumulate(), and Finish().
Append()
template<typename SrcChar , typename DestChar >
void v8::internal::IncrementalStringBuilder::Append (SrcChar c) [inline]
Definition at line 63 of file string-builder-inl.h.
                                               {
  DCHECK_EQ(encoding_ == String::ONE_BYTE_ENCODING, sizeof(DestChar) == 1);
  if (sizeof(DestChar) == 1) {
    DCHECK_EQ(String::ONE_BYTE_ENCODING, encoding_);
    Cast<SeqOneByteString>(*current_part_)
        ->SeqOneByteStringSet(current_index_++, c);
  } else {
    DCHECK_EQ(String::TWO_BYTE_ENCODING, encoding_);
    Cast<SeqTwoByteString>(*current_part_)
        ->SeqTwoByteStringSet(current_index_++, c);
  }
  if (current_index_ == part_length_) Extend();
  DCHECK(HasValidCurrentIndex());
}
References current_index_, current_part_, v8::internal::DCHECK(), DCHECK_EQ, encoding_, Extend(), HasValidCurrentIndex(), v8::internal::String::ONE_BYTE_ENCODING, part_length_, and v8::internal::String::TWO_BYTE_ENCODING.
Referenced by v8::internal::anonymous_namespace{builtins-regexp.cc}::RegExpEscapeImpl().
AppendCharacter()
void v8::internal::IncrementalStringBuilder::AppendCharacter (uint8_t c) [inline]
Definition at line 78 of file string-builder-inl.h.
                                                                  {
  if (encoding_ == String::ONE_BYTE_ENCODING) {
    Append<uint8_t, uint8_t>(c);
  } else {
    Append<uint8_t, base::uc16>(c);
  }
}
References encoding_, and v8::internal::String::ONE_BYTE_ENCODING.
Referenced by v8::internal::CircularStructureMessageBuilder::AppendConstructorName(), AppendCStringLiteral(), v8::internal::anonymous_namespace{messages.cc}::AppendErrorString(), v8::internal::anonymous_namespace{call-site-info.cc}::AppendFileLocation(), v8::internal::CircularStructureMessageBuilder::AppendKey(), v8::internal::anonymous_namespace{call-site-info.cc}::AppendMethodCall(), AppendString(), v8::internal::anonymous_namespace{messages.cc}::BuildDefaultCallSite(), v8::internal::BUILTIN(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), v8::internal::anonymous_namespace{call-site-info.cc}::FormatEvalOrigin(), v8::internal::SharedFunctionInfo::GetSourceCodeHarmony(), v8::internal::String::GetSubstitution(), v8::internal::Object::NoSideEffectsToMaybeString(), v8::internal::Object::NoSideEffectsToString(), v8::internal::CallPrinter::Print(), v8::internal::Isolate::PrintCurrentStackTrace(), v8::internal::anonymous_namespace{builtins-regexp.cc}::RegExpEscapeImpl(), v8::internal::anonymous_namespace{call-site-info.cc}::SerializeJSStackFrame(), v8::internal::JSFunction::SetName(), v8::internal::Name::ToFunctionName(), and v8::internal::MessageFormatter::TryFormat().
AppendCString()
template<typename SrcChar >
void v8::internal::IncrementalStringBuilder::AppendCString (const SrcChar * s) [inline]
Definition at line 106 of file string-builder-inl.h.
                                                                       {
  if (encoding_ == String::ONE_BYTE_ENCODING) {
    while (*s != '\0') Append<SrcChar, uint8_t>(*s++);
  } else {
    while (*s != '\0') Append<SrcChar, base::uc16>(*s++);
  }
}
References encoding_, and v8::internal::String::ONE_BYTE_ENCODING.
Referenced by v8::internal::CircularStructureMessageBuilder::AppendClosingLine(), AppendCStringLiteral(), v8::internal::CircularStructureMessageBuilder::AppendEllipsis(), v8::internal::CircularStructureMessageBuilder::AppendNormalLine(), v8::internal::CircularStructureMessageBuilder::AppendStartLine(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), v8::internal::CallPrinter::Print(), and v8::internal::MessageFormatter::TryFormat().
AppendCStringLiteral()
template<int N>
void v8::internal::IncrementalStringBuilder::AppendCStringLiteral (const char(&) literal[N]) [inline]
Definition at line 87 of file string-builder-inl.h.
                              {
  // Note that the literal contains the zero char.
  const int length = N - 1;
  static_assert(length > 0);
  if (length == 1) return AppendCharacter(literal[0]);
  if (encoding_ == String::ONE_BYTE_ENCODING && CurrentPartCanFit(N)) {
    const uint8_t* chars = reinterpret_cast<const uint8_t*>(literal);
    Cast<SeqOneByteString>(*current_part_)
        ->SeqOneByteStringSetChars(current_index_, chars, length);
    current_index_ += length;
    if (current_index_ == part_length_) Extend();
    DCHECK(HasValidCurrentIndex());
    return;
  }
  return AppendCString(literal);
}
References AppendCharacter(), AppendCString(), current_index_, current_part_, CurrentPartCanFit(), v8::internal::DCHECK(), encoding_, Extend(), HasValidCurrentIndex(), v8::internal::length, v8::internal::N, v8::internal::String::ONE_BYTE_ENCODING, and part_length_.
Referenced by v8::internal::CircularStructureMessageBuilder::AppendClosingLine(), v8::internal::CircularStructureMessageBuilder::AppendEllipsis(), v8::internal::anonymous_namespace{messages.cc}::AppendErrorString(), v8::internal::anonymous_namespace{call-site-info.cc}::AppendFileLocation(), v8::internal::CircularStructureMessageBuilder::AppendKey(), v8::internal::anonymous_namespace{call-site-info.cc}::AppendMethodCall(), v8::internal::CircularStructureMessageBuilder::AppendNormalLine(), v8::internal::CircularStructureMessageBuilder::AppendStartLine(), v8::internal::anonymous_namespace{messages.cc}::BuildDefaultCallSite(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), v8::internal::anonymous_namespace{call-site-info.cc}::FormatEvalOrigin(), v8::internal::ErrorUtils::FormatStackTrace(), v8::debug::GetFunctionDescription(), v8::internal::SharedFunctionInfo::GetSourceCodeHarmony(), v8::internal::anonymous_namespace{js-function.cc}::NativeCodeFunctionSourceString(), v8::internal::anonymous_namespace{objects.cc}::NoSideEffectsErrorToString(), v8::internal::Object::NoSideEffectsToMaybeString(), v8::internal::Object::NoSideEffectsToString(), v8::internal::anonymous_namespace{builtins-regexp.cc}::RegExpEscapeImpl(), v8::internal::anonymous_namespace{call-site-info.cc}::SerializeJSStackFrame(), and v8::internal::ErrorUtils::ToString().
AppendInt()
void v8::internal::IncrementalStringBuilder::AppendInt (int i) [inline]
Definition at line 131 of file string-builder-inl.h.
                                                        {
  char buffer[kIntToStringViewBufferSize];
  std::string_view str = IntToStringView(i, base::ArrayVector(buffer));
  AppendString(str);
}
References AppendString(), v8::base::ArrayVector(), v8::internal::IntToStringView(), and kIntToStringViewBufferSize.
Referenced by v8::internal::anonymous_namespace{call-site-info.cc}::AppendFileLocation(), v8::internal::anonymous_namespace{call-site-info.cc}::FormatEvalOrigin(), and v8::internal::anonymous_namespace{call-site-info.cc}::SerializeJSStackFrame().
AppendString() [1/2]
void v8::internal::IncrementalStringBuilder::AppendString (DirectHandle< String > string)
Definition at line 347 of file string-builder.cc.
                                                                       {
  if (CanAppendByCopy(string)) {
    AppendStringByCopy(string);
    return;
  }
  ShrinkCurrentPart();
  part_length_ = kInitialPartLength; // Allocate conservatively.
  Extend(); // Attach current part and allocate new part.
  Accumulate(string);
}
References Accumulate(), AppendStringByCopy(), CanAppendByCopy(), Extend(), kInitialPartLength, part_length_, and ShrinkCurrentPart().
AppendString() [2/2]
void v8::internal::IncrementalStringBuilder::AppendString (std::string_view str) [inline]
Definition at line 114 of file string-builder-inl.h.
                                                                        {
  uint32_t length = static_cast<uint32_t>(str.length());
  if (encoding_ == String::ONE_BYTE_ENCODING && CurrentPartCanFit(length)) {
    Cast<SeqOneByteString>(*current_part_)
        ->SeqOneByteStringSetChars(current_index_,
                                   reinterpret_cast<const uint8_t*>(str.data()),
                                   length);
    current_index_ += str.length();
    if (current_index_ == part_length_) Extend();
    DCHECK(HasValidCurrentIndex());
  } else {
    for (size_t i = 0; i < str.length(); i++) {
      AppendCharacter(str[i]);
    }
  }
}
References AppendCharacter(), current_index_, current_part_, CurrentPartCanFit(), v8::internal::DCHECK(), encoding_, Extend(), HasValidCurrentIndex(), v8::internal::length, v8::internal::String::ONE_BYTE_ENCODING, and part_length_.
Referenced by v8::internal::CircularStructureMessageBuilder::AppendConstructorName(), v8::internal::anonymous_namespace{messages.cc}::AppendErrorString(), v8::internal::anonymous_namespace{call-site-info.cc}::AppendFileLocation(), AppendInt(), v8::internal::CircularStructureMessageBuilder::AppendKey(), v8::internal::anonymous_namespace{call-site-info.cc}::AppendMethodCall(), v8::internal::CircularStructureMessageBuilder::AppendSmi(), v8::internal::anonymous_namespace{messages.cc}::BuildDefaultCallSite(), v8::internal::BUILTIN(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), v8::internal::anonymous_namespace{call-site-info.cc}::FormatEvalOrigin(), v8::internal::ErrorUtils::FormatStackTrace(), v8::debug::GetFunctionDescription(), v8::internal::SharedFunctionInfo::GetSourceCodeHarmony(), v8::internal::String::GetSubstitution(), v8::internal::temporal::ISODateTimeToString(), v8::internal::anonymous_namespace{js-function.cc}::NativeCodeFunctionSourceString(), v8::internal::anonymous_namespace{objects.cc}::NoSideEffectsErrorToString(), v8::internal::Object::NoSideEffectsToMaybeString(), v8::internal::Object::NoSideEffectsToString(), v8::internal::CallPrinter::Print(), v8::internal::Isolate::PrintCurrentStackTrace(), v8::internal::anonymous_namespace{builtins-regexp.cc}::RegExpEscapeImpl(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpReplace(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{call-site-info.cc}::SerializeJSStackFrame(), v8::internal::JSFunction::SetName(), v8::internal::temporal::TemporalDateToString(), v8::internal::temporal::TemporalDurationToString(), v8::internal::temporal::TemporalInstantToString(), v8::internal::temporal::TimeRecordToString(), v8::internal::Name::ToFunctionName(), v8::internal::ErrorUtils::ToString(), and v8::internal::MessageFormatter::TryFormat().
AppendStringByCopy()
void v8::internal::IncrementalStringBuilder::AppendStringByCopy (DirectHandle< String > string) [private]
Definition at line 323 of file string-builder.cc.
                                                                             {
  DCHECK(CanAppendByCopy(string));
  {
    DisallowGarbageCollection no_gc;
    if (encoding_ == String::ONE_BYTE_ENCODING) {
      String::WriteToFlat(
          *string,
          Cast<SeqOneByteString>(current_part())->GetChars(no_gc) +
              current_index_,
          0, string->length());
    } else {
      String::WriteToFlat(
          *string,
          Cast<SeqTwoByteString>(current_part())->GetChars(no_gc) +
              current_index_,
          0, string->length());
    }
  }
  current_index_ += string->length();
  DCHECK(current_index_ <= part_length_);
  if (current_index_ == part_length_) Extend();
}
References CanAppendByCopy(), current_index_, current_part(), v8::internal::DCHECK(), encoding_, Extend(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::String::ONE_BYTE_ENCODING, part_length_, v8::internal::string, and v8::internal::String::WriteToFlat().
Referenced by AppendString().
CanAppendByCopy()
bool v8::internal::IncrementalStringBuilder::CanAppendByCopy (DirectHandle< String > string) [private]
Definition at line 315 of file string-builder.cc.
                                                                          {
  const bool representation_ok =
      encoding_ == String::TWO_BYTE_ENCODING ||
      (string->IsFlat() && String::IsOneByteRepresentationUnderneath(*string));
  return representation_ok && CurrentPartCanFit(string->length());
}
References CurrentPartCanFit(), encoding_, v8::internal::String::IsOneByteRepresentationUnderneath(), v8::internal::string, and v8::internal::String::TWO_BYTE_ENCODING.
Referenced by AppendString(), and AppendStringByCopy().
ChangeEncoding()
void v8::internal::IncrementalStringBuilder::ChangeEncoding () [inline]
Definition at line 151 of file string-builder-inl.h.
                                              {
  DCHECK_EQ(String::ONE_BYTE_ENCODING, encoding_);
  ShrinkCurrentPart();
  encoding_ = String::TWO_BYTE_ENCODING;
  Extend();
}
References DCHECK_EQ, encoding_, Extend(), v8::internal::String::ONE_BYTE_ENCODING, ShrinkCurrentPart(), and v8::internal::String::TWO_BYTE_ENCODING.
Referenced by v8::internal::anonymous_namespace{builtins-regexp.cc}::RegExpEscapeImpl().
current_part()
DirectHandle<String> v8::internal::IncrementalStringBuilder::current_part () [inline], [private]
Definition at line 129 of file string-builder.h.
{ return current_part_; }
References current_part_.
Referenced by AppendStringByCopy(), Extend(), Finish(), and ShrinkCurrentPart().
CurrentEncoding()
String::Encoding v8::internal::IncrementalStringBuilder::CurrentEncoding () [inline]
Definition at line 83 of file string-builder.h.
{ return encoding_; }
References encoding_.
CurrentPartCanFit()
bool v8::internal::IncrementalStringBuilder::CurrentPartCanFit (int length) [inline]
Definition at line 99 of file string-builder.h.
                                               {
    return part_length_ - current_index_ > length;
  }
References current_index_, v8::internal::length, and part_length_.
Referenced by AppendCStringLiteral(), AppendString(), CanAppendByCopy(), and EscapedLengthIfCurrentPartFits().
EscapedLengthIfCurrentPartFits()
int v8::internal::IncrementalStringBuilder::EscapedLengthIfCurrentPartFits (int length) [inline]
Definition at line 137 of file string-builder-inl.h.
                {
  if (length > kMaxPartLength) return 0;
  // The worst case length of an escaped character is 6. Shifting the remaining
  // string length right by 3 is a more pessimistic estimate, but faster to
  // calculate.
  static_assert((kMaxPartLength << 3) <= String::kMaxLength);
  // This shift will not overflow because length is already less than the
  // maximum part length.
  int worst_case_length = length << 3;
  return CurrentPartCanFit(worst_case_length) ? worst_case_length : 0;
}
References CurrentPartCanFit(), v8::internal::String::kMaxLength, kMaxPartLength, and v8::internal::length.
Extend()
void v8::internal::IncrementalStringBuilder::Extend () [private]
Definition at line 281 of file string-builder.cc.
                                      {
  DCHECK_EQ(current_index_, current_part()->length());
  Accumulate(current_part());
  if (part_length_ <= kMaxPartLength / kPartLengthGrowthFactor) {
    part_length_ *= kPartLengthGrowthFactor;
  }
  DirectHandle<String> new_part;
  if (encoding_ == String::ONE_BYTE_ENCODING) {
    new_part = factory()->NewRawOneByteString(part_length_).ToHandleChecked();
  } else {
    new_part = factory()->NewRawTwoByteString(part_length_).ToHandleChecked();
  }
  // Reuse the same handle to avoid being invalidated when exiting handle scope.
  set_current_part(new_part);
  current_index_ = 0;
}
References Accumulate(), current_index_, current_part(), DCHECK_EQ, encoding_, factory(), kMaxPartLength, kPartLengthGrowthFactor, v8::internal::length, v8::internal::FactoryBase< Impl >::NewRawOneByteString(), v8::internal::FactoryBase< Impl >::NewRawTwoByteString(), v8::internal::String::ONE_BYTE_ENCODING, part_length_, and set_current_part().
Referenced by Append(), AppendCStringLiteral(), AppendString(), AppendStringByCopy(), and ChangeEncoding().
factory()
Factory * v8::internal::IncrementalStringBuilder::factory () [inline], [private]
Definition at line 158 of file string-builder-inl.h.
                                                     {
  return isolate_->factory();
}
References v8::internal::Isolate::factory(), and isolate_.
Referenced by Accumulate(), Extend(), Finish(), and IncrementalStringBuilder().
Finish()
MaybeDirectHandle< String > v8::internal::IncrementalStringBuilder::Finish ()
Definition at line 298 of file string-builder.cc.
                                                           {
  ShrinkCurrentPart();
  Accumulate(current_part());
  if (overflowed_) {
    THROW_NEW_ERROR(isolate_, NewInvalidStringLengthError());
  }
  if (isolate()->serializer_enabled()) {
    return factory()->InternalizeString(
        indirect_handle(accumulator(), isolate_));
  }
  return accumulator();
}
References Accumulate(), accumulator(), current_part(), factory(), v8::internal::indirect_handle(), v8::internal::Factory::InternalizeString(), isolate(), isolate_, overflowed_, ShrinkCurrentPart(), and THROW_NEW_ERROR.
Referenced by v8::internal::anonymous_namespace{messages.cc}::BuildDefaultCallSite(), v8::internal::BUILTIN(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), v8::internal::CircularStructureMessageBuilder::Finish(), v8::internal::anonymous_namespace{call-site-info.cc}::FormatEvalOrigin(), v8::internal::ErrorUtils::FormatStackTrace(), v8::debug::GetFunctionDescription(), v8::internal::SharedFunctionInfo::GetSourceCodeHarmony(), v8::internal::String::GetSubstitution(), v8::internal::temporal::ISODateTimeToString(), v8::internal::anonymous_namespace{js-function.cc}::NativeCodeFunctionSourceString(), v8::internal::anonymous_namespace{objects.cc}::NoSideEffectsErrorToString(), v8::internal::Object::NoSideEffectsToMaybeString(), v8::internal::Object::NoSideEffectsToString(), v8::internal::CallPrinter::Print(), v8::internal::Isolate::PrintCurrentStackTrace(), v8::internal::anonymous_namespace{builtins-regexp.cc}::RegExpEscapeImpl(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpReplace(), v8::internal::RUNTIME_FUNCTION(), v8::internal::SerializeCallSiteInfo(), v8::internal::JSFunction::SetName(), v8::internal::temporal::TemporalDateToString(), v8::internal::temporal::TemporalDurationToString(), v8::internal::temporal::TemporalInstantToString(), v8::internal::temporal::TimeRecordToString(), v8::internal::Name::ToFunctionName(), v8::internal::ErrorUtils::ToString(), and v8::internal::MessageFormatter::TryFormat().
HasOverflowed()
bool v8::internal::IncrementalStringBuilder::HasOverflowed () const [inline]
Definition at line 111 of file string-builder.h.
{ return overflowed_; }
References overflowed_.
HasValidCurrentIndex()
bool v8::internal::IncrementalStringBuilder::HasValidCurrentIndex () const [private]
Definition at line 261 of file string-builder.cc.
                                                          {
  return current_index_ < part_length_;
}
References current_index_, and part_length_.
Referenced by Append(), AppendCStringLiteral(), and AppendString().
isolate()
Isolate* v8::internal::IncrementalStringBuilder::isolate () [inline]
Definition at line 118 of file string-builder.h.
{ return isolate_; }
References isolate_.
Referenced by v8::internal::CircularStructureMessageBuilder::AppendConstructorName(), Finish(), and IncrementalStringBuilder().
Length()
int v8::internal::IncrementalStringBuilder::Length () const
Definition at line 257 of file string-builder.cc.
                                           {
  return accumulator_->length() + current_index_;
}
References accumulator_, and current_index_.
Referenced by v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), and v8::internal::anonymous_namespace{objects.cc}::NoSideEffectsErrorToString().
set_accumulator()
void v8::internal::IncrementalStringBuilder::set_accumulator (DirectHandle< String > string) [inline], [private]
Definition at line 125 of file string-builder.h.
                                                              {
    accumulator_.SetValue(*string);
  }
References accumulator_.
Referenced by Accumulate().
set_current_part()
void v8::internal::IncrementalStringBuilder::set_current_part (DirectHandle< String > string) [inline], [private]
Definition at line 131 of file string-builder.h.
                                                               {
    current_part_.SetValue(*string);
  }
References current_part_.
Referenced by Extend(), and ShrinkCurrentPart().
ShrinkCurrentPart()
void v8::internal::IncrementalStringBuilder::ShrinkCurrentPart () [inline], [private]
Definition at line 162 of file string-builder-inl.h.
                                                           {
  DCHECK(current_index_ < part_length_);
  set_current_part(SeqString::Truncate(
      isolate_, indirect_handle(Cast<SeqString>(current_part()), isolate_),
      current_index_));
}
References current_index_, current_part(), v8::internal::DCHECK(), v8::internal::indirect_handle(), isolate_, part_length_, set_current_part(), and v8::internal::SeqString::Truncate().
Referenced by AppendString(), ChangeEncoding(), and Finish().
Member Data Documentation
accumulator_
DirectHandle<String> v8::internal::IncrementalStringBuilder::accumulator_ [private]
Definition at line 160 of file string-builder.h.
Referenced by accumulator(), IncrementalStringBuilder(), Length(), and set_accumulator().
current_index_
int v8::internal::IncrementalStringBuilder::current_index_ [private]
Definition at line 159 of file string-builder.h.
Referenced by Append(), AppendCStringLiteral(), AppendString(), AppendStringByCopy(), CurrentPartCanFit(), Extend(), HasValidCurrentIndex(), Length(), and ShrinkCurrentPart().
current_part_
DirectHandle<String> v8::internal::IncrementalStringBuilder::current_part_ [private]
Definition at line 161 of file string-builder.h.
Referenced by Append(), AppendCStringLiteral(), AppendString(), current_part(), IncrementalStringBuilder(), and set_current_part().
encoding_
String::Encoding v8::internal::IncrementalStringBuilder::encoding_ [private]
Definition at line 156 of file string-builder.h.
Referenced by Append(), AppendCharacter(), AppendCString(), AppendCStringLiteral(), AppendString(), AppendStringByCopy(), CanAppendByCopy(), ChangeEncoding(), CurrentEncoding(), and Extend().
isolate_
Isolate* v8::internal::IncrementalStringBuilder::isolate_ [private]
Definition at line 155 of file string-builder.h.
Referenced by Accumulate(), factory(), Finish(), isolate(), and ShrinkCurrentPart().
kInitialPartLength
const int v8::internal::IncrementalStringBuilder::kInitialPartLength = 32 [static], [private]
Definition at line 149 of file string-builder.h.
Referenced by AppendString().
kIntToStringViewBufferSize
const int v8::internal::IncrementalStringBuilder::kIntToStringViewBufferSize = sizeof(`-2147483648`) - 1 [static], [private]
Definition at line 153 of file string-builder.h.
Referenced by AppendInt().
kMaxPartLength
const int v8::internal::IncrementalStringBuilder::kMaxPartLength = 16 * 1024 [static], [private]
Definition at line 150 of file string-builder.h.
Referenced by EscapedLengthIfCurrentPartFits(), and Extend().
kPartLengthGrowthFactor
const int v8::internal::IncrementalStringBuilder::kPartLengthGrowthFactor = 2 [static], [private]
Definition at line 151 of file string-builder.h.
Referenced by Extend().
overflowed_
bool v8::internal::IncrementalStringBuilder::overflowed_ [private]
Definition at line 157 of file string-builder.h.
Referenced by Accumulate(), Finish(), and HasOverflowed().
part_length_
int v8::internal::IncrementalStringBuilder::part_length_ [private]
Definition at line 158 of file string-builder.h.
Referenced by Append(), AppendCStringLiteral(), AppendString(), AppendStringByCopy(), CurrentPartCanFit(), Extend(), HasValidCurrentIndex(), IncrementalStringBuilder(), and ShrinkCurrentPart().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/strings/string-builder.h
/mnt/V8SourceCode/src/strings/string-builder-inl.h
/mnt/V8SourceCode/src/strings/string-builder.cc