cppgc::internal::PersistentNode Class Reference
#include <persistent-node.h>
Public Member Functions
PersistentNode ()=default
PersistentNode (const PersistentNode &)=delete
PersistentNode & operator= (const PersistentNode &)=delete
void InitializeAsUsedNode (void *owner, TraceRootCallback trace)
void InitializeAsFreeNode (PersistentNode *next)
void UpdateOwner (void *owner)
PersistentNode * FreeListNext () const
void Trace (RootVisitor &root_visitor) const
bool IsUsed () const
void * owner () const
Private Attributes
xx xx xx xx xx xx xx xx xx
union {
 void * owner_ = nullptr
 PersistentNode * next_
};
TraceRootCallback trace_ = nullptr
Detailed Description
Definition at line 27 of file persistent-node.h.
Constructor & Destructor Documentation
PersistentNode() [1/2]
cppgc::internal::PersistentNode::PersistentNode () [default]
PersistentNode() [2/2]
cppgc::internal::PersistentNode::PersistentNode (const PersistentNode &) [delete]
Member Function Documentation
FreeListNext()
PersistentNode* cppgc::internal::PersistentNode::FreeListNext () const [inline]
Definition at line 50 of file persistent-node.h.
                                       {
    CPPGC_DCHECK(!IsUsed());
    return next_;
  }
References CPPGC_DCHECK, IsUsed(), and next_.
Referenced by cppgc::internal::PersistentRegionBase::Iterate(), and cppgc::internal::PersistentRegionBase::TryAllocateNodeFromFreeList().
InitializeAsFreeNode()
void cppgc::internal::PersistentNode::InitializeAsFreeNode (PersistentNode * next) [inline]
Definition at line 40 of file persistent-node.h.
                                                  {
    next_ = next;
    trace_ = nullptr;
  }
References next_, and trace_.
Referenced by cppgc::internal::PersistentRegionBase::FreeNode().
InitializeAsUsedNode()
void cppgc::internal::PersistentNode::InitializeAsUsedNode (void * owner, TraceRootCallback trace) [inline]
Definition at line 34 of file persistent-node.h.
                                                                  {
    CPPGC_DCHECK(trace);
    owner_ = owner;
    trace_ = trace;
  }
References CPPGC_DCHECK, owner(), owner_, and trace_.
Referenced by cppgc::internal::PersistentRegionBase::TryAllocateNodeFromFreeList().
IsUsed()
bool cppgc::internal::PersistentNode::IsUsed () const [inline]
Definition at line 60 of file persistent-node.h.
{ return trace_; }
References trace_.
Referenced by FreeListNext(), cppgc::internal::PersistentRegionBase::FreeNode(), owner(), Trace(), cppgc::internal::PersistentRegionBase::TryAllocateNodeFromFreeList(), and UpdateOwner().
operator=()
PersistentNode& cppgc::internal::PersistentNode::operator= (const PersistentNode &) [delete]
owner()
void* cppgc::internal::PersistentNode::owner () const [inline]
Definition at line 62 of file persistent-node.h.
                      {
    CPPGC_DCHECK(IsUsed());
    return owner_;
  }
References CPPGC_DCHECK, IsUsed(), and owner_.
Referenced by InitializeAsUsedNode(), and UpdateOwner().
Trace()
void cppgc::internal::PersistentNode::Trace (RootVisitor & root_visitor) const [inline]
Definition at line 55 of file persistent-node.h.
                                              {
    CPPGC_DCHECK(IsUsed());
    trace_(root_visitor, owner_);
  }
References CPPGC_DCHECK, IsUsed(), owner_, and trace_.
UpdateOwner()
void cppgc::internal::PersistentNode::UpdateOwner (void * owner) [inline]
Definition at line 45 of file persistent-node.h.
                                {
    CPPGC_DCHECK(IsUsed());
    owner_ = owner;
  }
References CPPGC_DCHECK, IsUsed(), owner(), and owner_.
Referenced by cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=(), and cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=().
Member Data Documentation
union { ... } [private]
next_
PersistentNode* cppgc::internal::PersistentNode::next_
Definition at line 73 of file persistent-node.h.
Referenced by FreeListNext(), and InitializeAsFreeNode().
owner_
void* cppgc::internal::PersistentNode::owner_ = nullptr
Definition at line 72 of file persistent-node.h.
Referenced by InitializeAsUsedNode(), owner(), Trace(), and UpdateOwner().
trace_
TraceRootCallback cppgc::internal::PersistentNode::trace_ = nullptr [private]
Definition at line 75 of file persistent-node.h.
Referenced by InitializeAsFreeNode(), InitializeAsUsedNode(), IsUsed(), and Trace().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/cppgc/internal/persistent-node.h