v8::internal::JSRelativeTimeFormat Class Reference
#include <js-relative-time-format.h>
Public Types
enum class Numeric { ALWAYS
, AUTO
 }
Public Member Functions
Handle< String > NumericAsString (Isolate *isolate) const
void set_numeric (Numeric numeric)
Numeric numeric () const
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSRelativeTimeFormat > New (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT DirectHandle< JSObject > ResolvedOptions (Isolate *isolate, DirectHandle< JSRelativeTimeFormat > format_holder)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< String > Format (Isolate *isolate, Handle< Object > value_obj, Handle< Object > unit_obj, DirectHandle< JSRelativeTimeFormat > format)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSArray > FormatToParts (Isolate *isolate, Handle< Object > value_obj, Handle< Object > unit_obj, DirectHandle< JSRelativeTimeFormat > format)
static V8_EXPORT_PRIVATE const std::set< std::string > & GetAvailableLocales ()
Detailed Description
Definition at line 35 of file js-relative-time-format.h.
Member Enumeration Documentation
Numeric
enum v8::internal::JSRelativeTimeFormat::Numeric [strong]
Enumerator
ALWAYS
AUTO
Definition at line 70 of file js-relative-time-format.h.
                     {
    ALWAYS, // numerical descriptions are always used ("1 day ago")
    AUTO // numerical descriptions are used only when no more specific
             // version is available ("yesterday")
  };
Member Function Documentation
Format()
MaybeDirectHandle< String > v8::internal::JSRelativeTimeFormat::Format (Isolate * isolate, Handle< Object > value_obj, Handle< Object > unit_obj, DirectHandle< JSRelativeTimeFormat > format) [static]
Definition at line 488 of file js-relative-time-format.cc.
                                               {
  return FormatCommon<String>(isolate, format, value_obj, unit_obj,
                              "Intl.RelativeTimeFormat.prototype.format",
                              FormatToString);
}
References v8::internal::format, and v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatToString().
Referenced by v8::internal::BUILTIN().
FormatToParts()
MaybeDirectHandle< JSArray > v8::internal::JSRelativeTimeFormat::FormatToParts (Isolate * isolate, Handle< Object > value_obj, Handle< Object > unit_obj, DirectHandle< JSRelativeTimeFormat > format) [static]
Definition at line 496 of file js-relative-time-format.cc.
                                               {
  return FormatCommon<JSArray>(
      isolate, format, value_obj, unit_obj,
      "Intl.RelativeTimeFormat.prototype.formatToParts", FormatToJSArray);
}
References v8::internal::format, and v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatToJSArray().
Referenced by v8::internal::BUILTIN().
GetAvailableLocales()
const std::set< std::string > & v8::internal::JSRelativeTimeFormat::GetAvailableLocales () [static]
Definition at line 504 of file js-relative-time-format.cc.
                                                                   {
  // Since RelativeTimeFormatter does not have a method to list all
  // available locales, work around by calling the DateFormat.
  return Intl::GetAvailableLocalesForDateFormat();
}
References v8::internal::Intl::GetAvailableLocalesForDateFormat().
Referenced by v8::internal::BUILTIN(), and New().
New()
MaybeDirectHandle< JSRelativeTimeFormat > v8::internal::JSRelativeTimeFormat::New (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 69 of file js-relative-time-format.cc.
                                        {
  // 1. Let requestedLocales be ? CanonicalizeLocaleList(locales).
  Maybe<std::vector<std::string>> maybe_requested_locales =
      Intl::CanonicalizeLocaleList(isolate, locales);
  MAYBE_RETURN(maybe_requested_locales, DirectHandle<JSRelativeTimeFormat>());
  std::vector<std::string> requested_locales =
      maybe_requested_locales.FromJust();
  // 2. Set options to ? CoerceOptionsToObject(options).
  DirectHandle<JSReceiver> options;
  const char* service = "Intl.RelativeTimeFormat";
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, options, CoerceOptionsToObject(isolate, input_options, service));
  // 4. Let opt be a new Record.
  // 5. Let matcher be ? GetOption(options, "localeMatcher", "string", «
  // "lookup", "best fit" », "best fit").
  // 6. Set opt.[[localeMatcher]] to matcher.
  Maybe<Intl::MatcherOption> maybe_locale_matcher =
      Intl::GetLocaleMatcher(isolate, options, service);
  MAYBE_RETURN(maybe_locale_matcher, MaybeDirectHandle<JSRelativeTimeFormat>());
  Intl::MatcherOption matcher = maybe_locale_matcher.FromJust();
  // 7. Let _numberingSystem_ be ? GetOption(_options_, `"numberingSystem"`,
  // `"string"`, *undefined*, *undefined*).
  std::string numbering_system_str;
  Maybe<bool> maybe_numberingSystem =
      Intl::GetNumberingSystem(isolate, options, service, numbering_system_str);
  // 8. If _numberingSystem_ is not *undefined*, then
  // a. If _numberingSystem_ does not match the
  // `(3*8alphanum) *("-" (3*8alphanum))` sequence, throw a *RangeError*
  // exception.
  MAYBE_RETURN(maybe_numberingSystem,
               MaybeDirectHandle<JSRelativeTimeFormat>());
  // 9. Set _opt_.[[nu]] to _numberingSystem_.
  // 10. Let localeData be %RelativeTimeFormat%.[[LocaleData]].
  // 11. Let r be
  // ResolveLocale(%RelativeTimeFormat%.[[AvailableLocales]],
  // requestedLocales, opt,
  // %RelativeTimeFormat%.[[RelevantExtensionKeys]], localeData).
  Intl::ResolvedLocale r;
  if (!Intl::ResolveLocale(isolate, JSRelativeTimeFormat::GetAvailableLocales(),
                           requested_locales, matcher, {"nu"})
           .To(&r)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  UErrorCode status = U_ZERO_ERROR;
  icu::Locale icu_locale = r.icu_locale;
  if (maybe_numberingSystem.FromJust()) {
    auto nu_extension_it = r.extensions.find("nu");
    if (nu_extension_it != r.extensions.end() &&
        nu_extension_it->second != numbering_system_str) {
      icu_locale.setUnicodeKeywordValue("nu", nullptr, status);
      DCHECK(U_SUCCESS(status));
    }
  }
  // 12. Let locale be r.[[Locale]].
  Maybe<std::string> maybe_locale_str = Intl::ToLanguageTag(icu_locale);
  MAYBE_RETURN(maybe_locale_str, MaybeDirectHandle<JSRelativeTimeFormat>());
  // 13. Set relativeTimeFormat.[[Locale]] to locale.
  DirectHandle<String> locale_str =
      isolate->factory()->NewStringFromAsciiChecked(
          maybe_locale_str.FromJust().c_str());
  // 14. Set relativeTimeFormat.[[NumberingSystem]] to r.[[nu]].
  if (maybe_numberingSystem.FromJust() &&
      Intl::IsValidNumberingSystem(numbering_system_str)) {
    icu_locale.setUnicodeKeywordValue("nu", numbering_system_str, status);
    DCHECK(U_SUCCESS(status));
  }
  // 15. Let dataLocale be r.[[DataLocale]].
  // 16. Let s be ? GetOption(options, "style", "string",
  // «"long", "short", "narrow"», "long").
  Maybe<Style> maybe_style = GetStringOption<Style>(
      isolate, options, "style", service,
      std::to_array<const std::string_view>({"long", "short", "narrow"}),
      std::array{Style::LONG, Style::SHORT, Style::NARROW}, Style::LONG);
  MAYBE_RETURN(maybe_style, MaybeDirectHandle<JSRelativeTimeFormat>());
  Style style_enum = maybe_style.FromJust();
  // 17. Set relativeTimeFormat.[[Style]] to s.
  // 18. Let numeric be ? GetOption(options, "numeric", "string",
  // «"always", "auto"», "always").
  Maybe<Numeric> maybe_numeric = GetStringOption<Numeric>(
      isolate, options, "numeric", service,
      std::to_array<const std::string_view>({"always", "auto"}),
      std::array{Numeric::ALWAYS, Numeric::AUTO}, Numeric::ALWAYS);
  MAYBE_RETURN(maybe_numeric, MaybeDirectHandle<JSRelativeTimeFormat>());
  Numeric numeric_enum = maybe_numeric.FromJust();
  // 19. Set relativeTimeFormat.[[Numeric]] to numeric.
  // 23. Let relativeTimeFormat.[[NumberFormat]] be
  // ? Construct(%NumberFormat%, « nfLocale, nfOptions »).
  icu::NumberFormat* number_format =
      icu::NumberFormat::createInstance(icu_locale, UNUM_DECIMAL, status);
  if (U_FAILURE(status)) {
    // Data build filter files excluded data in "rbnf_tree" since ECMA402 does
    // not support "algorithmic" numbering systems. Therefore we may get the
    // U_MISSING_RESOURCE_ERROR here. Fallback to locale without the numbering
    // system and create the object again.
    if (status == U_MISSING_RESOURCE_ERROR) {
      delete number_format;
      status = U_ZERO_ERROR;
      icu_locale.setUnicodeKeywordValue("nu", nullptr, status);
      DCHECK(U_SUCCESS(status));
      number_format =
          icu::NumberFormat::createInstance(icu_locale, UNUM_DECIMAL, status);
    }
    if (U_FAILURE(status) || number_format == nullptr) {
      delete number_format;
      THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
    }
  }
  if (number_format->getDynamicClassID() ==
      icu::DecimalFormat::getStaticClassID()) {
    icu::DecimalFormat* decimal_format =
        static_cast<icu::DecimalFormat*>(number_format);
    decimal_format->setMinimumGroupingDigits(-2);
  }
  // Change UDISPCTX_CAPITALIZATION_NONE to other values if
  // ECMA402 later include option to change capitalization.
  // Ref: https://github.com/tc39/proposal-intl-relative-time/issues/11
  std::shared_ptr<icu::RelativeDateTimeFormatter> icu_formatter =
      std::make_shared<icu::RelativeDateTimeFormatter>(
          icu_locale, number_format, toIcuStyle(style_enum),
          UDISPCTX_CAPITALIZATION_NONE, status);
  if (U_FAILURE(status) || icu_formatter == nullptr) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  DirectHandle<String> numbering_system_string =
      isolate->factory()->NewStringFromAsciiChecked(
          Intl::GetNumberingSystem(icu_locale).c_str());
  DirectHandle<Managed<icu::RelativeDateTimeFormatter>> managed_formatter =
      Managed<icu::RelativeDateTimeFormatter>::From(isolate, 0,
                                                    std::move(icu_formatter));
  DirectHandle<JSRelativeTimeFormat> relative_time_format_holder =
      Cast<JSRelativeTimeFormat>(
          isolate->factory()->NewFastOrSlowJSObjectFromMap(map));
  DisallowGarbageCollection no_gc;
  relative_time_format_holder->set_flags(0);
  relative_time_format_holder->set_locale(*locale_str);
  relative_time_format_holder->set_numberingSystem(*numbering_system_string);
  relative_time_format_holder->set_numeric(numeric_enum);
  relative_time_format_holder->set_icu_formatter(*managed_formatter);
  // 25. Return relativeTimeFormat.
  return relative_time_format_holder;
}
References ALWAYS, ASSIGN_RETURN_ON_EXCEPTION, AUTO, v8::internal::Intl::CanonicalizeLocaleList(), v8::internal::CoerceOptionsToObject(), v8::internal::DCHECK(), v8::internal::Intl::ResolvedLocale::extensions, v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), v8::Maybe< T >::FromJust(), GetAvailableLocales(), v8::internal::Intl::GetLocaleMatcher(), v8::internal::Intl::GetNumberingSystem(), v8::internal::Intl::ResolvedLocale::icu_locale, v8::internal::Intl::IsValidNumberingSystem(), MAYBE_RETURN, v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Intl::ResolveLocale(), v8::internal::status, v8::internal::string, THROW_NEW_ERROR, v8::internal::anonymous_namespace{js-relative-time-format.cc}::toIcuStyle(), and v8::internal::Intl::ToLanguageTag().
numeric()
JSRelativeTimeFormat::Numeric v8::internal::JSRelativeTimeFormat::numeric () const [inline]
Definition at line 38 of file js-relative-time-format-inl.h.
                                                                       {
  return NumericBit::decode(flags());
}
References v8::internal::flags.
Referenced by NumericAsString().
NumericAsString()
Handle< String > v8::internal::JSRelativeTimeFormat::NumericAsString (Isolate * isolate) const
Definition at line 273 of file js-relative-time-format.cc.
                                                                           {
  switch (numeric()) {
    case Numeric::ALWAYS:
      return isolate->factory()->always_string();
    case Numeric::AUTO:
      return isolate->factory()->auto_string();
  }
  UNREACHABLE();
}
References ALWAYS, AUTO, v8::internal::Isolate::factory(), numeric(), and v8::internal::UNREACHABLE().
ResolvedOptions()
DirectHandle< JSObject > v8::internal::JSRelativeTimeFormat::ResolvedOptions (Isolate * isolate, DirectHandle< JSRelativeTimeFormat > format_holder) [static]
Definition at line 250 of file js-relative-time-format.cc.
                                                                        {
  Factory* factory = isolate->factory();
  icu::RelativeDateTimeFormatter* formatter =
      format_holder->icu_formatter()->raw();
  DCHECK_NOT_NULL(formatter);
  DirectHandle<JSObject> result =
      factory->NewJSObject(isolate->object_function());
  DirectHandle<String> locale(format_holder->locale(), isolate);
  DirectHandle<String> numberingSystem(format_holder->numberingSystem(),
                                       isolate);
  JSObject::AddProperty(isolate, result, factory->locale_string(), locale,
                        NONE);
  JSObject::AddProperty(
      isolate, result, factory->style_string(),
      StyleAsString(isolate, fromIcuStyle(formatter->getFormatStyle())), NONE);
  JSObject::AddProperty(isolate, result, factory->numeric_string(),
                        format_holder->NumericAsString(isolate), NONE);
  JSObject::AddProperty(isolate, result, factory->numberingSystem_string(),
                        numberingSystem, NONE);
  return result;
}
References v8::internal::JSObject::AddProperty(), DCHECK_NOT_NULL, v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::fromIcuStyle(), v8::internal::Factory::NewJSObject(), v8::internal::NONE, v8::base::internal::result, and v8::internal::anonymous_namespace{js-relative-time-format.cc}::StyleAsString().
Referenced by v8::internal::BUILTIN().
set_numeric()
void v8::internal::JSRelativeTimeFormat::set_numeric (Numeric numeric) [inline]
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-relative-time-format.h
/mnt/V8SourceCode/src/objects/js-relative-time-format-inl.h
/mnt/V8SourceCode/src/objects/js-relative-time-format.cc