v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer Class Reference
Classes
struct MemoryRegion
Static Public Member Functions
static void Serialize (Isolate *isolate, SnapshotByteSink *sink, const std::vector< MemoryRegion > &unmapped_regions)
Private Types
using Bytecode = ro::Bytecode
Private Member Functions
ReadOnlyHeapImageSerializer (Isolate *isolate, SnapshotByteSink *sink)
void SerializeImpl (const std::vector< MemoryRegion > &unmapped_regions)
uint32_t IndexOf (const ReadOnlyPageMetadata *page)
void EmitAllocatePage (const ReadOnlyPageMetadata *page, const std::vector< MemoryRegion > &unmapped_regions)
void SerializePage (const ReadOnlyPageMetadata *page, const std::vector< MemoryRegion > &unmapped_regions)
void EmitSegment (const ReadOnlySegmentForSerialization *segment)
void EmitReadOnlyRootsTable ()
Private Attributes
Isolate *const isolate_
SnapshotByteSink *const sink_
ObjectPreProcessor pre_processor_
Detailed Description
Definition at line 323 of file read-only-serializer.cc.
Member Typedef Documentation
Bytecode
using v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::Bytecode = ro::Bytecode [private]
Definition at line 336 of file read-only-serializer.cc.
Constructor & Destructor Documentation
ReadOnlyHeapImageSerializer()
v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::ReadOnlyHeapImageSerializer (Isolate * isolate, SnapshotByteSink * sink) [inline], [private]
Definition at line 338 of file read-only-serializer.cc.
      : isolate_(isolate), sink_(sink), pre_processor_(isolate) {}
Member Function Documentation
EmitAllocatePage()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitAllocatePage (const ReadOnlyPageMetadata * page, const std::vector< MemoryRegion > & unmapped_regions) [inline], [private]
Definition at line 366 of file read-only-serializer.cc.
                                                                         {
    if (V8_STATIC_ROOTS_BOOL) {
      sink_->Put(Bytecode::kAllocatePageAt, "fixed page begin");
    } else {
      sink_->Put(Bytecode::kAllocatePage, "page begin");
    }
    sink_->PutUint30(IndexOf(page), "page index");
    sink_->PutUint30(
        static_cast<uint32_t>(page->HighWaterMark() - page->area_start()),
        "area size in bytes");
    if (V8_STATIC_ROOTS_BOOL) {
      auto page_addr = page->ChunkAddress();
      sink_->PutUint32(V8HeapCompressionScheme::CompressAny(page_addr),
                       "page start offset");
    }
  }
References v8::internal::MemoryChunkMetadata::area_start(), v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressAny(), v8::internal::MemoryChunkMetadata::HighWaterMark(), v8::internal::ro::kAllocatePage, v8::internal::ro::kAllocatePageAt, and V8_STATIC_ROOTS_BOOL.
EmitReadOnlyRootsTable()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitReadOnlyRootsTable () [inline], [private]
Definition at line 429 of file read-only-serializer.cc.
                                {
    sink_->Put(Bytecode::kReadOnlyRootsTable, "read only roots table");
    if (!V8_STATIC_ROOTS_BOOL) {
      ReadOnlyRoots roots(isolate_);
      for (size_t i = 0; i < ReadOnlyRoots::kEntriesCount; i++) {
        RootIndex rudi = static_cast<RootIndex>(i);
        Tagged<HeapObject> rudolf = Cast<HeapObject>(roots.object_at(rudi));
        ro::EncodedTagged encoded = Encode(isolate_, rudolf);
        sink_->PutUint32(encoded.ToUint32(), "read only roots entry");
      }
    }
  }
References v8::internal::anonymous_namespace{read-only-serializer.cc}::Encode(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ReadOnlyRoots::kEntriesCount, v8::internal::ro::kReadOnlyRootsTable, v8::internal::ReadOnlyRoots::object_at(), v8::internal::ro::EncodedTagged::ToUint32(), and V8_STATIC_ROOTS_BOOL.
EmitSegment()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitSegment (const ReadOnlySegmentForSerialization * segment) [inline], [private]
Definition at line 412 of file read-only-serializer.cc.
                                                                   {
    sink_->Put(Bytecode::kSegment, "segment begin");
    sink_->PutUint30(IndexOf(segment->page), "page index");
    sink_->PutUint30(static_cast<uint32_t>(segment->segment_offset),
                     "segment start offset");
    sink_->PutUint30(static_cast<uint32_t>(segment->segment_size),
                     "segment byte size");
    sink_->PutRaw(segment->contents.get(),
                  static_cast<int>(segment->segment_size), "page");
    if (!V8_STATIC_ROOTS_BOOL) {
      sink_->Put(Bytecode::kRelocateSegment, "relocate segment");
      sink_->PutRaw(segment->tagged_slots.data(),
                    static_cast<int>(segment->tagged_slots.size_in_bytes()),
                    "tagged_slots");
    }
  }
References v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::contents, v8::internal::ro::BitSet::data(), v8::internal::ro::kRelocateSegment, v8::internal::ro::kSegment, v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::page, v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::segment_offset, v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::segment_size, v8::internal::ro::BitSet::size_in_bytes(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::tagged_slots, and V8_STATIC_ROOTS_BOOL.
IndexOf()
uint32_t v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::IndexOf (const ReadOnlyPageMetadata * page) [inline], [private]
Definition at line 361 of file read-only-serializer.cc.
                                                     {
    ReadOnlySpace* ro_space = isolate_->read_only_heap()->read_only_space();
    return static_cast<uint32_t>(ro_space->IndexOf(page));
  }
References v8::internal::ReadOnlySpace::IndexOf().
Serialize()
static void v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::Serialize (Isolate * isolate, SnapshotByteSink * sink, const std::vector< MemoryRegion > & unmapped_regions) [inline], [static]
Definition at line 330 of file read-only-serializer.cc.
                                                                         {
    ReadOnlyHeapImageSerializer{isolate, sink}.SerializeImpl(unmapped_regions);
  }
SerializeImpl()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::SerializeImpl (const std::vector< MemoryRegion > & unmapped_regions) [inline], [private]
Definition at line 341 of file read-only-serializer.cc.
                                                                      {
    DCHECK_EQ(sink_->Position(), 0);
    ReadOnlySpace* ro_space = isolate_->read_only_heap()->read_only_space();
    // Allocate all pages first s.t. the deserializer can easily handle forward
    // references (e.g.: an object on page i points at an object on page i+1).
    for (const ReadOnlyPageMetadata* page : ro_space->pages()) {
      EmitAllocatePage(page, unmapped_regions);
    }
    // Now write the page contents.
    for (const ReadOnlyPageMetadata* page : ro_space->pages()) {
      SerializePage(page, unmapped_regions);
    }
    EmitReadOnlyRootsTable();
    sink_->Put(Bytecode::kFinalizeReadOnlySpace, "space end");
  }
References DCHECK_EQ, v8::internal::ro::kFinalizeReadOnlySpace, and v8::internal::ReadOnlySpace::pages().
SerializePage()
void v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::SerializePage (const ReadOnlyPageMetadata * page, const std::vector< MemoryRegion > & unmapped_regions) [inline], [private]
Definition at line 384 of file read-only-serializer.cc.
                                                                      {
    Address pos = page->area_start();
    // If this page contains unmapped regions split it into multiple segments.
    for (auto r = unmapped_regions.begin(); r != unmapped_regions.end(); ++r) {
      // Regions must be sorted and non-overlapping.
      if (r + 1 != unmapped_regions.end()) {
        CHECK(r->start < (r + 1)->start);
        CHECK(r->start + r->size < (r + 1)->start);
      }
      if (base::IsInRange(r->start, pos, page->HighWaterMark())) {
        size_t segment_size = r->start - pos;
        ReadOnlySegmentForSerialization segment(isolate_, page, pos,
                                                segment_size, &pre_processor_);
        EmitSegment(&segment);
        pos += segment_size + r->size;
      }
    }
    // Pages are shrunk, but memory at the end of the area is still
    // uninitialized and we do not want to include it in the snapshot.
    size_t segment_size = page->HighWaterMark() - pos;
    ReadOnlySegmentForSerialization segment(isolate_, page, pos, segment_size,
                                            &pre_processor_);
    EmitSegment(&segment);
  }
References v8::internal::MemoryChunkMetadata::area_start(), CHECK, and v8::internal::MemoryChunkMetadata::HighWaterMark().
Member Data Documentation
isolate_
Isolate* const v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::isolate_ [private]
Definition at line 442 of file read-only-serializer.cc.
pre_processor_
ObjectPreProcessor v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::pre_processor_ [private]
Definition at line 444 of file read-only-serializer.cc.
sink_
SnapshotByteSink* const v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::sink_ [private]
Definition at line 443 of file read-only-serializer.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/read-only-serializer.cc