v8::internal::wasm::WasmFunctionCoverageData Class Reference
#include <wasm-code-coverage.h>
Public Member Functions
WasmFunctionCoverageData (base::Vector< const WasmCodeRange > code_ranges)
const base::Vector< const WasmCodeRange > code_ranges () const
const base::Vector< uint32_t > counters () const
Private Attributes
base::OwnedVector< const WasmCodeRange > code_ranges_
base::OwnedVector< uint32_t > counts_
Detailed Description
Definition at line 37 of file wasm-code-coverage.h.
Constructor & Destructor Documentation
WasmFunctionCoverageData()
v8::internal::wasm::WasmFunctionCoverageData::WasmFunctionCoverageData (base::Vector< const WasmCodeRange > code_ranges) [inline], [explicit]
Definition at line 39 of file wasm-code-coverage.h.
                                                   {
    counts_ = base::OwnedVector<uint32_t>::New(code_ranges.size());
    code_ranges_ = base::OwnedCopyOf(code_ranges);
  }
References code_ranges(), code_ranges_, counts_, v8::base::OwnedVector< T >::New(), and v8::base::OwnedCopyOf().
Member Function Documentation
code_ranges()
const base::Vector<const WasmCodeRange> v8::internal::wasm::WasmFunctionCoverageData::code_ranges () const [inline]
Definition at line 45 of file wasm-code-coverage.h.
                                                            {
    return base::VectorOf(code_ranges_);
  }
References code_ranges_, and v8::base::VectorOf().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LiftoffCompiler(), and WasmFunctionCoverageData().
counters()
const base::Vector<uint32_t> v8::internal::wasm::WasmFunctionCoverageData::counters () const [inline]
Definition at line 49 of file wasm-code-coverage.h.
                                              {
    return base::VectorOf(counts_);
  }
References counts_, and v8::base::VectorOf().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LiftoffCompiler().
Member Data Documentation
code_ranges_
base::OwnedVector<const WasmCodeRange> v8::internal::wasm::WasmFunctionCoverageData::code_ranges_ [private]
Definition at line 54 of file wasm-code-coverage.h.
Referenced by code_ranges(), and WasmFunctionCoverageData().
counts_
base::OwnedVector<uint32_t> v8::internal::wasm::WasmFunctionCoverageData::counts_ [private]
Definition at line 55 of file wasm-code-coverage.h.
Referenced by counters(), and WasmFunctionCoverageData().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-code-coverage.h