v8::internal::TrustedManaged< CppType > Class Template Reference
#include <managed.h>
Public Member Functions
TrustedManaged ()
TrustedManaged (Address ptr)
constexpr TrustedManaged (Address ptr, SkipTypeCheckTag)
TrustedManaged * operator-> ()
const TrustedManaged * operator-> () const
CppType * raw ()
const std::shared_ptr< CppType > & get ()
Static Public Member Functions
static DirectHandle< TrustedManaged< CppType > > From (Isolate *isolate, size_t estimated_size, std::shared_ptr< CppType > shared_ptr, bool shared)
Private Member Functions
std::shared_ptr< CppType > * GetSharedPtrPtr ()
Friends
class Tagged< TrustedManaged >
Additional Inherited Members
Detailed Description
template<class CppType>
class v8::internal::TrustedManaged< CppType >
Definition at line 142 of file managed.h.
Constructor & Destructor Documentation
TrustedManaged() [1/3]
template<class CppType >
v8::internal::TrustedManaged< CppType >::TrustedManaged () [inline]
Definition at line 144 of file managed.h.
: TrustedForeign() {}
TrustedManaged() [2/3]
template<class CppType >
v8::internal::TrustedManaged< CppType >::TrustedManaged (Address ptr) [inline], [explicit]
Definition at line 145 of file managed.h.
: TrustedForeign(ptr) {}
TrustedManaged() [3/3]
template<class CppType >
constexpr v8::internal::TrustedManaged< CppType >::TrustedManaged (Address ptr, SkipTypeCheckTag) [inline], [constexpr]
Definition at line 146 of file managed.h.
      : TrustedForeign(ptr, SkipTypeCheckTag{}) {}
Member Function Documentation
From()
template<class CppType >
DirectHandle< TrustedManaged< CppType > > v8::internal::TrustedManaged< CppType >::From (Isolate * isolate, size_t estimated_size, std::shared_ptr< CppType > shared_ptr, bool shared) [static]
Definition at line 52 of file managed-inl.h.
                                                    {
  auto destructor = new ManagedPtrDestructor(
      estimated_size, new std::shared_ptr<CppType>{std::move(shared_ptr)},
      detail::Destructor<CppType>);
  destructor->external_memory_accounter_.Increase(
      reinterpret_cast<v8::Isolate*>(isolate), estimated_size);
  DirectHandle<TrustedManaged<CppType>> handle =
      Cast<TrustedManaged<CppType>>(isolate->factory()->NewTrustedForeign(
          reinterpret_cast<Address>(destructor), shared));
  IndirectHandle<Object> global_handle =
      isolate->global_handles()->Create(*handle);
  destructor->global_handle_location_ = global_handle.location();
  GlobalHandles::MakeWeak(destructor->global_handle_location_, destructor,
                          &ManagedObjectFinalizer,
                          v8::WeakCallbackType::kParameter);
  isolate->RegisterManagedPtrDestructor(destructor);
  return handle;
}
References v8::internal::GlobalHandles::Create(), v8::internal::ManagedPtrDestructor::external_memory_accounter_, v8::internal::Isolate::factory(), v8::internal::Isolate::global_handles(), v8::internal::handle(), v8::ExternalMemoryAccounter::Increase(), v8::kParameter, v8::internal::HandleBase::location(), v8::internal::GlobalHandles::MakeWeak(), v8::internal::ManagedObjectFinalizer(), v8::internal::Factory::NewTrustedForeign(), and v8::internal::Isolate::RegisterManagedPtrDestructor().
Referenced by v8::internal::WasmTrustedInstanceData::New().
get()
template<class CppType >
const std::shared_ptr<CppType>& v8::internal::TrustedManaged< CppType >::get () [inline]
Definition at line 158 of file managed.h.
{ return *GetSharedPtrPtr(); }
GetSharedPtrPtr()
template<class CppType >
std::shared_ptr<CppType>* v8::internal::TrustedManaged< CppType >::GetSharedPtrPtr () [inline], [private]
Definition at line 171 of file managed.h.
                                            {
    auto destructor =
        reinterpret_cast<ManagedPtrDestructor*>(foreign_address());
    return reinterpret_cast<std::shared_ptr<CppType>*>(
        destructor->shared_ptr_ptr_);
  }
operator->() [1/2]
template<class CppType >
TrustedManaged* v8::internal::TrustedManaged< CppType >::operator-> () [inline]
Definition at line 151 of file managed.h.
{ return this; }
operator->() [2/2]
template<class CppType >
const TrustedManaged* v8::internal::TrustedManaged< CppType >::operator-> () const [inline]
Definition at line 152 of file managed.h.
{ return this; }
raw()
template<class CppType >
CppType* v8::internal::TrustedManaged< CppType >::raw () [inline]
Definition at line 155 of file managed.h.
{ return GetSharedPtrPtr()->get(); }
Friends And Related Function Documentation
Tagged< TrustedManaged >
template<class CppType >
friend class Tagged< TrustedManaged > [friend]
Definition at line 162 of file managed.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/managed.h
/mnt/V8SourceCode/src/objects/managed-inl.h