v8::internal::ObjectCacheIndexMap Class Reference
#include <serializer.h>
Public Member Functions
ObjectCacheIndexMap (Heap *heap)
ObjectCacheIndexMap (const ObjectCacheIndexMap &)=delete
ObjectCacheIndexMap & operator= (const ObjectCacheIndexMap &)=delete
bool LookupOrInsert (Tagged< HeapObject > obj, int *index_out)
bool LookupOrInsert (DirectHandle< HeapObject > obj, int *index_out)
bool Lookup (Tagged< HeapObject > obj, int *index_out) const
DirectHandle< FixedArray > Values (Isolate *isolate)
int size () const
Private Attributes
IdentityMap< int, base::DefaultAllocationPolicy > map_
int next_index_
Detailed Description
Definition at line 143 of file serializer.h.
Constructor & Destructor Documentation
ObjectCacheIndexMap() [1/2]
v8::internal::ObjectCacheIndexMap::ObjectCacheIndexMap (Heap * heap) [inline], [explicit]
Definition at line 145 of file serializer.h.
: map_(heap), next_index_(0) {}
ObjectCacheIndexMap() [2/2]
v8::internal::ObjectCacheIndexMap::ObjectCacheIndexMap (const ObjectCacheIndexMap &) [delete]
Member Function Documentation
Lookup()
bool v8::internal::ObjectCacheIndexMap::Lookup (Tagged< HeapObject > obj, int * index_out) const [inline]
Definition at line 164 of file serializer.h.
                                                            {
    int* index = map_.Find(obj);
    if (index == nullptr) {
      return false;
    }
    *index_out = *index;
    return true;
  }
References v8::internal::index, and map_.
LookupOrInsert() [1/2]
bool v8::internal::ObjectCacheIndexMap::LookupOrInsert (DirectHandle< HeapObject > obj, int * index_out) [inline]
Definition at line 160 of file serializer.h.
                                                                    {
    return LookupOrInsert(*obj, index_out);
  }
References LookupOrInsert().
LookupOrInsert() [2/2]
bool v8::internal::ObjectCacheIndexMap::LookupOrInsert (Tagged< HeapObject > obj, int * index_out) [inline]
Definition at line 152 of file serializer.h.
                                                              {
    auto find_result = map_.FindOrInsert(obj);
    if (!find_result.already_exists) {
      *find_result.entry = next_index_++;
    }
    *index_out = *find_result.entry;
    return find_result.already_exists;
  }
References map_, and next_index_.
Referenced by LookupOrInsert(), and v8::internal::RootsSerializer::SerializeInObjectCache().
operator=()
ObjectCacheIndexMap& v8::internal::ObjectCacheIndexMap::operator= (const ObjectCacheIndexMap &) [delete]
size()
int v8::internal::ObjectCacheIndexMap::size () const [inline]
Definition at line 175 of file serializer.h.
{ return next_index_; }
References next_index_.
Values()
DirectHandle< FixedArray > v8::internal::ObjectCacheIndexMap::Values (Isolate * isolate)
Definition at line 1447 of file serializer.cc.
                                                                     {
  if (size() == 0) {
    return isolate->factory()->empty_fixed_array();
  }
  DirectHandle<FixedArray> externals =
      isolate->factory()->NewFixedArray(size());
  DisallowGarbageCollection no_gc;
  Tagged<FixedArray> raw = *externals;
  IdentityMap<int, base::DefaultAllocationPolicy>::IteratableScope it_scope(
      &map_);
  for (auto it = it_scope.begin(); it != it_scope.end(); ++it) {
    raw->set(*it.entry(), it.key());
  }
  return externals;
}
References v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope::begin(), v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope::end(), v8::internal::Isolate::factory(), v8::internal::Serializer::isolate(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and size().
Member Data Documentation
map_
IdentityMap<int, base::DefaultAllocationPolicy> v8::internal::ObjectCacheIndexMap::map_ [private]
Definition at line 178 of file serializer.h.
Referenced by Lookup(), and LookupOrInsert().
next_index_
int v8::internal::ObjectCacheIndexMap::next_index_ [private]
Definition at line 179 of file serializer.h.
Referenced by LookupOrInsert(), and size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/serializer.h
/mnt/V8SourceCode/src/snapshot/serializer.cc