v8::internal::JSBoundFunction Class Reference
#include <js-function.h>
Static Public Member Functions
static MaybeHandle< String > GetName (Isolate *isolate, DirectHandle< JSBoundFunction > function)
static Maybe< int > GetLength (Isolate *isolate, DirectHandle< JSBoundFunction > function)
static DirectHandle< String > ToString (Isolate *isolate, DirectHandle< JSBoundFunction > function)
Detailed Description
Definition at line 45 of file js-function.h.
Member Function Documentation
GetLength()
Maybe< int > v8::internal::JSBoundFunction::GetLength (Isolate * isolate, DirectHandle< JSBoundFunction > function) [static]
Definition at line 472 of file js-function.cc.
                                                                              {
  int nof_bound_arguments = function->bound_arguments()->length();
  while (IsJSBoundFunction(function->bound_target_function())) {
    function = direct_handle(
        Cast<JSBoundFunction>(function->bound_target_function()), isolate);
    // Make sure we never overflow {nof_bound_arguments}, the number of
    // arguments of a function is strictly limited by the max length of an
    // JSAarray, Smi::kMaxValue is thus a reasonably good overestimate.
    int length = function->bound_arguments()->length();
    if (V8_LIKELY(Smi::kMaxValue - nof_bound_arguments > length)) {
      nof_bound_arguments += length;
    } else {
      nof_bound_arguments = Smi::kMaxValue;
    }
  }
  if (IsJSWrappedFunction(function->bound_target_function())) {
    DirectHandle<JSWrappedFunction> target(
        Cast<JSWrappedFunction>(function->bound_target_function()), isolate);
    int target_length = 0;
    MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, target_length, JSWrappedFunction::GetLength(isolate, target),
        Nothing<int>());
    int length = std::max(0, target_length - nof_bound_arguments);
    return Just(length);
  }
  // All non JSFunction targets get a direct property and don't use this
  // accessor.
  DirectHandle<JSFunction> target(
      Cast<JSFunction>(function->bound_target_function()), isolate);
  int target_length = target->length();
  int length = std::max(0, target_length - nof_bound_arguments);
  return Just(length);
}
References v8::internal::direct_handle(), v8::internal::JSWrappedFunction::GetLength(), v8::Just(), v8::internal::Smi::kMaxValue, v8::internal::length, MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, and V8_LIKELY.
Referenced by v8::internal::JSWrappedFunction::GetLength().
GetName()
MaybeHandle< String > v8::internal::JSBoundFunction::GetName (Isolate * isolate, DirectHandle< JSBoundFunction > function) [static]
Definition at line 441 of file js-function.cc.
                                                              {
  Handle<String> prefix = isolate->factory()->bound__string();
  Handle<String> target_name = prefix;
  Factory* factory = isolate->factory();
  // Concatenate the "bound " up to the last non-bound target.
  while (IsJSBoundFunction(function->bound_target_function())) {
    ASSIGN_RETURN_ON_EXCEPTION(isolate, target_name,
                               factory->NewConsString(prefix, target_name));
    function = direct_handle(
        Cast<JSBoundFunction>(function->bound_target_function()), isolate);
  }
  if (IsJSWrappedFunction(function->bound_target_function())) {
    DirectHandle<JSWrappedFunction> target(
        Cast<JSWrappedFunction>(function->bound_target_function()), isolate);
    Handle<String> name;
    ASSIGN_RETURN_ON_EXCEPTION(isolate, name,
                               JSWrappedFunction::GetName(isolate, target));
    return factory->NewConsString(target_name, name);
  }
  if (IsJSFunction(function->bound_target_function())) {
    DirectHandle<JSFunction> target(
        Cast<JSFunction>(function->bound_target_function()), isolate);
    Handle<String> name = JSFunction::GetName(isolate, target);
    return factory->NewConsString(target_name, name);
  }
  // This will omit the proper target name for bound JSProxies.
  return target_name;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::JSFunction::GetName(), v8::internal::JSWrappedFunction::GetName(), v8::internal::name, and v8::internal::FactoryBase< Impl >::NewConsString().
Referenced by v8::Function::GetName(), v8::internal::JSWrappedFunction::GetName(), and v8::internal::Object::NoSideEffectsToMaybeString().
ToString()
DirectHandle< String > v8::internal::JSBoundFunction::ToString (Isolate * isolate, DirectHandle< JSBoundFunction > function) [static]
Definition at line 509 of file js-function.cc.
                                                              {
  return isolate->factory()->function_native_code_string();
}
References v8::internal::Isolate::factory().
Referenced by v8::internal::BUILTIN(), v8::debug::GetFunctionDescription(), and v8::internal::Object::NoSideEffectsToMaybeString().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-function.h
/mnt/V8SourceCode/src/objects/js-function.cc