v8::internal::compiler::BasicBlockInstrumentor Class Reference
#include <basic-block-instrumentor.h>
Static Public Member Functions
static BasicBlockProfilerData * Instrument (OptimizedCompilationInfo *info, TFGraph *graph, Schedule *schedule, Isolate *isolate)
Detailed Description
Definition at line 25 of file basic-block-instrumentor.h.
Member Function Documentation
Instrument()
BasicBlockProfilerData * v8::internal::compiler::BasicBlockInstrumentor::Instrument (OptimizedCompilationInfo * info, TFGraph * graph, Schedule * schedule, Isolate * isolate) [static]
Definition at line 58 of file basic-block-instrumentor.cc.
                      {
  // Basic block profiling disables concurrent compilation, so handle deref is
  // fine.
  AllowHandleDereference allow_handle_dereference;
  // Skip the exit block in profiles, since the register allocator can't handle
  // it and entry into it means falling off the end of the function anyway.
  size_t n_blocks = schedule->RpoBlockCount();
  BasicBlockProfilerData* data = BasicBlockProfiler::Get()->NewData(n_blocks);
  // Set the function name.
  data->SetFunctionName(info->GetDebugName());
  // Capture the schedule string before instrumentation.
  if (v8_flags.turbo_profiling_verbose) {
    std::ostringstream os;
    os << *schedule;
    data->SetSchedule(os);
  }
  // Check whether we should write counts to a JS heap object or to the
  // BasicBlockProfilerData directly. The JS heap object is only used for
  // builtins.
  bool on_heap_counters = isolate && isolate->IsGeneratingEmbeddedBuiltins();
  // Add the increment instructions to the start of every block.
  CommonOperatorBuilder common(graph->zone());
  MachineOperatorBuilder machine(graph->zone());
  Node* counters_array = nullptr;
  if (on_heap_counters) {
    // Allocation is disallowed here, so rather than referring to an actual
    // counters array, create a reference to a special marker object. This
    // object will get fixed up later in the constants table (see
    // PatchBasicBlockCountersReference). An important and subtle point: we
    // cannot use the root handle basic_block_counters_marker_handle() and must
    // create a new separate handle. Otherwise
    // MacroAssemblerBase::IndirectLoadConstant would helpfully emit a
    // root-relative load rather than putting this value in the constants table
    // where we expect it to be for patching.
    counters_array = graph->NewNode(common.HeapConstant(Handle<HeapObject>::New(
        ReadOnlyRoots(isolate).basic_block_counters_marker(), isolate)));
  } else {
    counters_array = graph->NewNode(PointerConstant(&common, data->counts()));
  }
  Node* zero = graph->NewNode(common.Int32Constant(0));
  Node* one = graph->NewNode(common.Int32Constant(1));
  BasicBlockVector* blocks = schedule->rpo_order();
  size_t block_number = 0;
  for (BasicBlockVector::iterator it = blocks->begin(); block_number < n_blocks;
       ++it, ++block_number) {
    BasicBlock* block = (*it);
    if (block == schedule->end()) continue;
    // Iteration is already in reverse post-order.
    DCHECK_EQ(block->rpo_number(), block_number);
    data->SetBlockId(block_number, block->id().ToInt());
    // It is unnecessary to wire effect and control deps for load and store
    // since this happens after scheduling.
    // Construct increment operation.
    int offset_to_counter_value = static_cast<int>(block_number) * kInt32Size;
    if (on_heap_counters) {
      offset_to_counter_value +=
          OFFSET_OF_DATA_START(ByteArray) - kHeapObjectTag;
    }
    Node* offset_to_counter =
        graph->NewNode(IntPtrConstant(&common, offset_to_counter_value));
    Node* load =
        graph->NewNode(machine.Load(MachineType::Uint32()), counters_array,
                       offset_to_counter, graph->start(), graph->start());
    Node* inc = graph->NewNode(machine.Int32Add(), load, one);
    // Branchless saturation, because we've already run the scheduler, so
    // introducing extra control flow here would be surprising.
    Node* overflow = graph->NewNode(machine.Uint32LessThan(), inc, load);
    Node* overflow_mask = graph->NewNode(machine.Int32Sub(), zero, overflow);
    Node* saturated_inc =
        graph->NewNode(machine.Word32Or(), inc, overflow_mask);
    Node* store =
        graph->NewNode(machine.Store(StoreRepresentation(
                           MachineRepresentation::kWord32, kNoWriteBarrier)),
                       counters_array, offset_to_counter, saturated_inc,
                       graph->start(), graph->start());
    // Insert the new nodes.
    static const int kArraySize = 10;
    Node* to_insert[kArraySize] = {
        counters_array, zero, one, offset_to_counter,
        load, inc, overflow, overflow_mask,
        saturated_inc, store};
    // The first three Nodes are constant across all blocks.
    int insertion_start = block_number == 0 ? 0 : 3;
    NodeVector::iterator insertion_point = FindInsertionPoint(block);
    block->InsertNodes(insertion_point, &to_insert[insertion_start],
                       &to_insert[kArraySize]);
    // Tell the scheduler about the new nodes.
    for (int i = insertion_start; i < kArraySize; ++i) {
      schedule->SetBlockForNode(block, to_insert[i]);
    }
    // The exit block is not instrumented and so we must ignore that block
    // count.
    if (block->control() == BasicBlock::kBranch &&
        block->successors()[0] != schedule->end() &&
        block->successors()[1] != schedule->end()) {
      data->AddBranch(block->successors()[0]->id().ToInt(),
                      block->successors()[1]->id().ToInt());
    }
  }
  return data;
}
References v8::internal::BasicBlockProfilerData::AddBranch(), v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::BasicBlock::control(), v8::internal::BasicBlockProfilerData::counts(), DCHECK_EQ, v8::internal::compiler::Schedule::end(), v8::internal::compiler::FindInsertionPoint(), v8::internal::BasicBlockProfiler::Get(), v8::internal::OptimizedCompilationInfo::GetDebugName(), graph(), v8::internal::compiler::CommonOperatorBuilder::HeapConstant(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::BasicBlock::InsertNodes(), v8::internal::compiler::MachineOperatorBuilder::Int32Add(), v8::internal::compiler::CommonOperatorBuilder::Int32Constant(), v8::internal::compiler::MachineOperatorBuilder::Int32Sub(), v8::internal::compiler::IntPtrConstant(), v8::internal::Isolate::IsGeneratingEmbeddedBuiltins(), v8::internal::compiler::BasicBlock::kBranch, v8::internal::kHeapObjectTag, v8::internal::kInt32Size, v8::internal::compiler::kNoWriteBarrier, v8::internal::kWord32, v8::internal::compiler::MachineOperatorBuilder::Load(), v8::internal::BasicBlockProfiler::NewData(), OFFSET_OF_DATA_START, one, v8::internal::overflow, v8::internal::compiler::PointerConstant(), v8::internal::compiler::BasicBlock::rpo_number(), v8::internal::compiler::Schedule::rpo_order(), v8::internal::compiler::Schedule::RpoBlockCount(), v8::internal::compiler::Schedule::SetBlockForNode(), v8::internal::BasicBlockProfilerData::SetBlockId(), v8::internal::BasicBlockProfilerData::SetFunctionName(), v8::internal::BasicBlockProfilerData::SetSchedule(), v8::internal::compiler::MachineOperatorBuilder::Store(), store(), v8::internal::compiler::BasicBlock::successors(), v8::internal::compiler::BasicBlock::Id::ToInt(), v8::internal::MachineType::Uint32(), v8::internal::compiler::MachineOperatorBuilder::Uint32LessThan(), v8::internal::v8_flags, v8::internal::compiler::MachineOperatorBuilder::Word32Or(), and v8::internal::zero.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/basic-block-instrumentor.h
/mnt/V8SourceCode/src/compiler/basic-block-instrumentor.cc