v8::internal::SourcePosition Class Reference
#include <source-position.h>
Public Member Functions
SourcePosition (int script_offset=kNoSourcePosition, int inlining_id=kNotInlined)
bool IsKnown () const
bool isInlined () const
bool IsExternal () const
bool IsJavaScript () const
int ExternalLine () const
int ExternalFileId () const
std::vector< SourcePositionInfo > InliningStack (Isolate *isolate, Tagged< Code > code) const
std::vector< SourcePositionInfo > InliningStack (Isolate *isolate, OptimizedCompilationInfo *cinfo) const
SourcePositionInfo FirstInfo (Isolate *isolate, Tagged< Code > code) const
void Print (std::ostream &out, Tagged< Code > code) const
void PrintJson (std::ostream &out) const
int ScriptOffset () const
int InliningId () const
void SetIsExternal (bool external)
void SetExternalLine (int line)
void SetExternalFileId (int file_id)
void SetScriptOffset (int script_offset)
void SetInliningId (int inlining_id)
int64_t raw () const
Static Public Member Functions
static SourcePosition External (int line, int file_id)
static SourcePosition Unknown ()
static SourcePosition FromRaw (int64_t raw)
Static Public Attributes
static const int kNotInlined = -1
Private Types
using IsExternalField = base::BitField64< bool, 0, 1 >
using ExternalLineField = base::BitField64< int, 1, 20 >
using ExternalFileIdField = base::BitField64< int, 21, 10 >
using ScriptOffsetField = base::BitField64< int, 1, 30 >
using InliningIdField = base::BitField64< int, 31, 16 >
Private Member Functions
SourcePosition (int line, int file_id, int inlining_id)
void Print (std::ostream &out, Tagged< SharedFunctionInfo > function) const
Private Attributes
uint64_t value_
Detailed Description
Definition at line 45 of file source-position.h.
Member Typedef Documentation
ExternalFileIdField
using v8::internal::SourcePosition::ExternalFileIdField = base::BitField64<int, 21, 10> [private]
Definition at line 145 of file source-position.h.
ExternalLineField
using v8::internal::SourcePosition::ExternalLineField = base::BitField64<int, 1, 20> [private]
Definition at line 144 of file source-position.h.
InliningIdField
using v8::internal::SourcePosition::InliningIdField = base::BitField64<int, 31, 16> [private]
Definition at line 152 of file source-position.h.
IsExternalField
using v8::internal::SourcePosition::IsExternalField = base::BitField64<bool, 0, 1> [private]
Definition at line 141 of file source-position.h.
ScriptOffsetField
using v8::internal::SourcePosition::ScriptOffsetField = base::BitField64<int, 1, 30> [private]
Definition at line 148 of file source-position.h.
Constructor & Destructor Documentation
SourcePosition() [1/2]
v8::internal::SourcePosition::SourcePosition (int script_offset = kNoSourcePosition, int inlining_id = kNotInlined) [inline], [explicit]
Definition at line 47 of file source-position.h.
      : value_(0) {
    SetIsExternal(false);
    SetScriptOffset(script_offset);
    SetInliningId(inlining_id);
  }
References SetInliningId(), SetIsExternal(), and SetScriptOffset().
Referenced by External(), and Unknown().
SourcePosition() [2/2]
v8::internal::SourcePosition::SourcePosition (int line, int file_id, int inlining_id) [inline], [private]
Definition at line 132 of file source-position.h.
                                                         : value_(0) {
    SetIsExternal(true);
    SetExternalLine(line);
    SetExternalFileId(file_id);
    SetInliningId(inlining_id);
  }
References SetExternalFileId(), SetExternalLine(), SetInliningId(), and SetIsExternal().
Member Function Documentation
External()
static SourcePosition v8::internal::SourcePosition::External (int line, int file_id) [inline], [static]
Definition at line 57 of file source-position.h.
                                                        {
    return SourcePosition(line, file_id, kNotInlined);
  }
References kNotInlined, and SourcePosition().
Referenced by v8::internal::compiler::RawMachineAssembler::SetCurrentExternalSourcePosition().
ExternalFileId()
int v8::internal::SourcePosition::ExternalFileId () const [inline]
Definition at line 76 of file source-position.h.
                             {
    DCHECK(IsExternal());
    return ExternalFileIdField::decode(value_);
  }
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), IsExternal(), and value_.
Referenced by v8::internal::compiler::RawMachineAssembler::GetCurrentExternalSourcePosition(), v8::internal::operator<<(), PrintJson(), and v8::internal::EmbeddedFileWriter::WriteBuiltin().
ExternalLine()
int v8::internal::SourcePosition::ExternalLine () const [inline]
Definition at line 71 of file source-position.h.
                           {
    DCHECK(IsExternal());
    return ExternalLineField::decode(value_);
  }
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), IsExternal(), and value_.
Referenced by v8::internal::compiler::RawMachineAssembler::GetCurrentExternalSourcePosition(), v8::internal::operator<<(), PrintJson(), v8::internal::compiler::RawMachineAssembler::SetCurrentExternalSourcePosition(), and v8::internal::EmbeddedFileWriter::WriteBuiltin().
FirstInfo()
SourcePositionInfo v8::internal::SourcePosition::FirstInfo (Isolate * isolate, Tagged< Code > code) const
Definition at line 84 of file source-position.cc.
                                                                      {
  DisallowGarbageCollection no_gc;
  Tagged<DeoptimizationData> deopt_data =
      Cast<DeoptimizationData>(code->deoptimization_data());
  SourcePosition pos = *this;
  if (pos.isInlined()) {
    InliningPosition inl =
        deopt_data->InliningPositions()->get(pos.InliningId());
    DirectHandle<SharedFunctionInfo> function(
        deopt_data->GetInlinedFunction(inl.inlined_function_id), isolate);
    return SourcePositionInfo(isolate, pos, function);
  }
  DirectHandle<SharedFunctionInfo> function(deopt_data->GetSharedFunctionInfo(),
                                            isolate);
  return SourcePositionInfo(isolate, pos, function);
}
References code, v8::internal::InliningPosition::inlined_function_id, InliningId(), isInlined(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
FromRaw()
static SourcePosition v8::internal::SourcePosition::FromRaw (int64_t raw) [inline], [static]
Definition at line 123 of file source-position.h.
                                             {
    SourcePosition position = Unknown();
    DCHECK_GE(raw, 0);
    position.value_ = static_cast<uint64_t>(raw);
    return position;
  }
References DCHECK_GE, raw(), Unknown(), and value_.
Referenced by v8::internal::SourcePositionTableIterator::source_position().
InliningId()
int v8::internal::SourcePosition::InliningId () const [inline]
Definition at line 95 of file source-position.h.
{ return InliningIdField::decode(value_) - 1; }
References v8::base::BitField< T, shift, size, U >::decode(), and value_.
Referenced by FirstInfo(), InliningStack(), isInlined(), v8::internal::V8FileLogger::LogSourceCodeInformation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MaybeSetPositionToParent(), v8::internal::operator<<(), Print(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintInlinedFunctionInfo(), PrintJson(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::V8FileLogger::ProcessDeoptEvent(), and v8::internal::Assembler::RecordDeoptReason().
InliningStack() [1/2]
std::vector< SourcePositionInfo > v8::internal::SourcePosition::InliningStack (Isolate * isolate, OptimizedCompilationInfo * cinfo) const
Definition at line 51 of file source-position.cc.
                                                             {
  SourcePosition pos = *this;
  std::vector<SourcePositionInfo> stack;
  while (pos.isInlined()) {
    const auto& inl = cinfo->inlined_functions()[pos.InliningId()];
    stack.push_back(SourcePositionInfo(isolate, pos, inl.shared_info));
    pos = inl.position.position;
  }
  stack.push_back(SourcePositionInfo(isolate, pos, cinfo->shared_info()));
  return stack;
}
References v8::internal::OptimizedCompilationInfo::inlined_functions(), InliningId(), isInlined(), v8::internal::OptimizedCompilationInfo::shared_info(), and v8::internal::stack.
InliningStack() [2/2]
std::vector< SourcePositionInfo > v8::internal::SourcePosition::InliningStack (Isolate * isolate, Tagged< Code > code) const
Definition at line 64 of file source-position.cc.
                                               {
  Handle<DeoptimizationData> deopt_data(
      Cast<DeoptimizationData>(code->deoptimization_data()), isolate);
  SourcePosition pos = *this;
  std::vector<SourcePositionInfo> stack;
  while (pos.isInlined()) {
    InliningPosition inl =
        deopt_data->InliningPositions()->get(pos.InliningId());
    DirectHandle<SharedFunctionInfo> function(
        deopt_data->GetInlinedFunction(inl.inlined_function_id), isolate);
    stack.push_back(SourcePositionInfo(isolate, pos, function));
    pos = inl.position;
  }
  DirectHandle<SharedFunctionInfo> function(deopt_data->GetSharedFunctionInfo(),
                                            isolate);
  stack.push_back(SourcePositionInfo(isolate, pos, function));
  return stack;
}
References code, v8::internal::InliningPosition::inlined_function_id, InliningId(), isInlined(), v8::internal::InliningPosition::position, and v8::internal::stack.
Referenced by v8::internal::compiler::CodeGenerator::AssembleSourcePosition(), and v8::internal::ProfilerListener::AttachDeoptInlinedFrames().
IsExternal()
bool v8::internal::SourcePosition::IsExternal () const [inline]
Definition at line 68 of file source-position.h.
{ return IsExternalField::decode(value_); }
References v8::base::BitField< T, shift, size, U >::decode(), and value_.
Referenced by v8::internal::SourcePositionTableIterator::Advance(), ExternalFileId(), ExternalLine(), isInlined(), IsJavaScript(), v8::internal::operator<<(), PrintJson(), SetExternalFileId(), and SetExternalLine().
isInlined()
bool v8::internal::SourcePosition::isInlined () const [inline]
Definition at line 63 of file source-position.h.
                         {
    if (IsExternal()) return false;
    return InliningId() != kNotInlined;
  }
References InliningId(), IsExternal(), and kNotInlined.
Referenced by FirstInfo(), InliningStack(), v8::internal::V8FileLogger::LogSourceCodeInformation(), v8::internal::operator<<(), Print(), and v8::internal::compiler::GraphC1Visualizer::PrintSchedule().
IsJavaScript()
bool v8::internal::SourcePosition::IsJavaScript () const [inline]
Definition at line 69 of file source-position.h.
{ return !IsExternal(); }
References IsExternal().
Referenced by v8::internal::SourcePositionTableIterator::Advance(), ScriptOffset(), and SetScriptOffset().
IsKnown()
bool v8::internal::SourcePosition::IsKnown () const [inline]
Definition at line 62 of file source-position.h.
{ return raw() != SourcePosition::Unknown().raw(); }
References raw(), and Unknown().
Referenced by v8::internal::SourcePositionTableBuilder::AddPosition(), v8::internal::compiler::CodeGenerator::AssembleSourcePosition(), v8::internal::ProfilerListener::AttachDeoptInlinedFrames(), v8::internal::compiler::RawMachineAssembler::GetCurrentExternalSourcePosition(), v8::internal::compiler::SourcePositionTable::Scope::Init(), v8::internal::compiler::anonymous_namespace{turbofan-graph-visualizer.cc}::JsonPrintInlinedFunctionInfo(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintInlinedFunctionInfo(), v8::internal::compiler::SourcePositionTable::PrintJson(), v8::internal::compiler::JSONGraphWriter::PrintNode(), v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintNodes(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::V8FileLogger::ProcessDeoptEvent(), v8::internal::Assembler::RecordDeoptReason(), and v8::internal::compiler::InstructionSelector::VisitBlock().
Print() [1/2]
void v8::internal::SourcePosition::Print (std::ostream & out, Tagged< Code > code) const
Definition at line 131 of file source-position.cc.
                                                                   {
  Tagged<DeoptimizationData> deopt_data =
      Cast<DeoptimizationData>(code->deoptimization_data());
  if (!isInlined()) {
    Tagged<SharedFunctionInfo> function(deopt_data->GetSharedFunctionInfo());
    Print(out, function);
  } else {
    InliningPosition inl = deopt_data->InliningPositions()->get(InliningId());
    if (inl.inlined_function_id == -1) {
      out << *this;
    } else {
      Tagged<SharedFunctionInfo> function =
          deopt_data->GetInlinedFunction(inl.inlined_function_id);
      Print(out, function);
    }
    out << " inlined at ";
    inl.position.Print(out, code);
  }
}
References code, v8::internal::InliningPosition::inlined_function_id, InliningId(), isInlined(), v8::internal::InliningPosition::position, and Print().
Referenced by Print(), v8::internal::V8FileLogger::ProcessDeoptEvent(), v8::internal::Deoptimizer::ProcessDeoptReason(), and v8::internal::Deoptimizer::TraceDeoptBegin().
Print() [2/2]
void v8::internal::SourcePosition::Print (std::ostream & out, Tagged< SharedFunctionInfo > function) const [private]
Definition at line 102 of file source-position.cc.
                                                                      {
  Script::PositionInfo pos;
  Tagged<Object> source_name;
  if (IsScript(function->script())) {
    Tagged<Script> script = Cast<Script>(function->script());
    source_name = script->name();
    script->GetPositionInfo(ScriptOffset(), &pos);
  }
  out << "<";
  if (IsString(source_name)) {
    out << Cast<String>(source_name)->ToCString().get();
  } else {
    out << "unknown";
  }
  out << ":" << pos.line + 1 << ":" << pos.column + 1 << ">";
}
References v8::internal::Script::PositionInfo::column, v8::internal::Script::PositionInfo::line, v8::internal::script, and ScriptOffset().
PrintJson()
void v8::internal::SourcePosition::PrintJson (std::ostream & out) const
Definition at line 120 of file source-position.cc.
                                                    {
  if (IsExternal()) {
    out << "{ \"line\" : " << ExternalLine() << ", "
        << " \"fileId\" : " << ExternalFileId() << ", "
        << " \"inliningId\" : " << InliningId() << "}";
  } else {
    out << "{ \"scriptOffset\" : " << ScriptOffset() << ", "
        << " \"inliningId\" : " << InliningId() << "}";
  }
}
References ExternalFileId(), ExternalLine(), InliningId(), IsExternal(), and ScriptOffset().
Referenced by v8::internal::compiler::operator<<(), and v8::internal::compiler::SourcePositionTable::PrintJson().
raw()
int64_t v8::internal::SourcePosition::raw () const [inline]
Definition at line 122 of file source-position.h.
{ return static_cast<int64_t>(value_); }
References value_.
Referenced by v8::internal::SourcePositionTableBuilder::AddPosition(), FromRaw(), IsKnown(), and v8::internal::operator==().
ScriptOffset()
int v8::internal::SourcePosition::ScriptOffset () const [inline]
Definition at line 91 of file source-position.h.
                           {
    DCHECK(IsJavaScript());
    return ScriptOffsetField::decode(value_) - 1;
  }
References v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), IsJavaScript(), and value_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBody(), v8::internal::anonymous_namespace{log.cc}::CodeLinePosEvent(), v8::internal::BytecodeArray::Disassemble(), v8::internal::wasm::anonymous_namespace{wasm-debug.cc}::FindNewPC(), v8::internal::wasm::WasmCode::GetSourceOffsetBefore(), v8::internal::V8FileLogger::LogSourceCodeInformation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::MaybeSetPositionToParent(), v8::internal::BreakIterator::Next(), v8::internal::operator<<(), Print(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintInlinedFunctionInfo(), PrintJson(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::V8FileLogger::ProcessDeoptEvent(), v8::internal::Assembler::RecordDeoptReason(), v8::internal::SourcePositionInfo::SourcePositionInfo(), v8::internal::anonymous_namespace{liveedit.cc}::TranslateSourcePositionTable(), v8::internal::maglev::MaglevGraphBuilder::UpdateSourceAndBytecodePosition(), v8::internal::compiler::WasmGCLowering::UpdateSourcePosition(), and v8::internal::compiler::WasmGCOperatorReducer::UpdateSourcePosition().
SetExternalFileId()
void v8::internal::SourcePosition::SetExternalFileId (int file_id) [inline]
Definition at line 104 of file source-position.h.
                                      {
    DCHECK(IsExternal());
    value_ = ExternalFileIdField::update(value_, file_id);
  }
References v8::internal::DCHECK(), IsExternal(), v8::base::BitField< T, shift, size, U >::update(), and value_.
Referenced by SourcePosition().
SetExternalLine()
void v8::internal::SourcePosition::SetExternalLine (int line) [inline]
Definition at line 100 of file source-position.h.
                                 {
    DCHECK(IsExternal());
    value_ = ExternalLineField::update(value_, line);
  }
References v8::internal::DCHECK(), IsExternal(), v8::base::BitField< T, shift, size, U >::update(), and value_.
Referenced by SourcePosition().
SetInliningId()
void v8::internal::SourcePosition::SetInliningId (int inlining_id) [inline]
Definition at line 114 of file source-position.h.
                                      {
    DCHECK_GE(inlining_id, kNotInlined);
    value_ = InliningIdField::update(value_, inlining_id + 1);
  }
References DCHECK_GE, kNotInlined, v8::base::BitField< T, shift, size, U >::update(), and value_.
Referenced by SourcePosition().
SetIsExternal()
void v8::internal::SourcePosition::SetIsExternal (bool external) [inline]
Definition at line 97 of file source-position.h.
                                    {
    value_ = IsExternalField::update(value_, external);
  }
References v8::base::BitField< T, shift, size, U >::update(), and value_.
Referenced by SourcePosition().
SetScriptOffset()
void v8::internal::SourcePosition::SetScriptOffset (int script_offset) [inline]
Definition at line 109 of file source-position.h.
                                          {
    DCHECK(IsJavaScript());
    DCHECK_GE(script_offset, kNoSourcePosition);
    value_ = ScriptOffsetField::update(value_, script_offset + 1);
  }
References v8::internal::DCHECK(), DCHECK_GE, IsJavaScript(), v8::internal::kNoSourcePosition, v8::base::BitField< T, shift, size, U >::update(), and value_.
Referenced by SourcePosition(), and v8::internal::anonymous_namespace{liveedit.cc}::TranslateSourcePositionTable().
Unknown()
static SourcePosition v8::internal::SourcePosition::Unknown () [inline], [static]
Definition at line 61 of file source-position.h.
{ return SourcePosition(); }
References SourcePosition().
Referenced by v8::internal::compiler::CodeGenerator::AssembleSourcePosition(), v8::internal::ProfilerListener::AttachDeoptInlinedFrames(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Finalize(), FromRaw(), v8::internal::Deoptimizer::GetDeoptInfo(), IsKnown(), v8::internal::maglev::MaglevGraphLabeller::RegisterNode(), and v8::internal::compiler::SourcePositionTable::UnknownSourcePosition().
Member Data Documentation
kNotInlined
const int v8::internal::SourcePosition::kNotInlined = -1 [static]
Definition at line 119 of file source-position.h.
Referenced by v8::internal::maglev::MaglevGraphBuilder::Build(), v8::internal::maglev::MaglevGraphBuilder::BuildInlineFunction(), v8::internal::ProfilerListener::CodeCreateEvent(), External(), v8::internal::CodeEntry::GetInlineStack(), v8::internal::SourcePositionTable::GetTuple(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), isInlined(), v8::internal::wasm::TurboshaftGraphBuildingInterface::OpIndexToSourcePosition(), v8::internal::compiler::GraphBuilderPhase::Run(), and SetInliningId().
value_
uint64_t v8::internal::SourcePosition::value_ [private]
Definition at line 155 of file source-position.h.
Referenced by ExternalFileId(), ExternalLine(), FromRaw(), InliningId(), IsExternal(), raw(), ScriptOffset(), SetExternalFileId(), SetExternalLine(), SetInliningId(), SetIsExternal(), and SetScriptOffset().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/source-position.h
/mnt/V8SourceCode/src/codegen/source-position.cc