v8::internal::ConcurrentMarkingVisitor Class Reference
Public Member Functions
ConcurrentMarkingVisitor (MarkingWorklists::Local *local_marking_worklists, WeakObjects::Local *local_weak_objects, Heap *heap, unsigned mark_compact_epoch, base::EnumSet< CodeFlushMode > code_flush_mode, bool should_keep_ages_unchanged, uint16_t code_flushing_increase, MemoryChunkLiveBytesMap *memory_chunk_live_bytes_map, MemoryChunkTypedSlotsMap *memory_chunk_typed_slots_map)
bool ProcessEphemeron (Tagged< HeapObject > key, Tagged< HeapObject > value)
template<typename TSlot >
void RecordSlot (Tagged< HeapObject > object, TSlot slot, Tagged< HeapObject > target)
void IncrementLiveBytesCached (MutablePageMetadata *chunk, intptr_t by)
Static Public Member Functions
static constexpr bool EnableConcurrentVisitation ()
Private Member Functions
void RecordRelocSlot (Tagged< InstructionStream > host, RelocInfo *rinfo, Tagged< HeapObject > target)
Private Attributes
MemoryChunkLiveBytesMap * memory_chunk_live_bytes_map_
MemoryChunkTypedSlotsMap * memory_chunk_typed_slots_map_
Friends
class MarkingVisitorBase< ConcurrentMarkingVisitor >
Additional Inherited Members
Detailed Description
Definition at line 145 of file concurrent-marking.cc.
Constructor & Destructor Documentation
ConcurrentMarkingVisitor()
v8::internal::ConcurrentMarkingVisitor::ConcurrentMarkingVisitor (MarkingWorklists::Local * local_marking_worklists, WeakObjects::Local * local_weak_objects, Heap * heap, unsigned mark_compact_epoch, base::EnumSet< CodeFlushMode > code_flush_mode, bool should_keep_ages_unchanged, uint16_t code_flushing_increase, MemoryChunkLiveBytesMap * memory_chunk_live_bytes_map, MemoryChunkTypedSlotsMap * memory_chunk_typed_slots_map) [inline]
Definition at line 148 of file concurrent-marking.cc.
      : FullMarkingVisitorBase(local_marking_worklists, local_weak_objects,
                               heap, mark_compact_epoch, code_flush_mode,
                               should_keep_ages_unchanged,
                               code_flushing_increase),
        memory_chunk_live_bytes_map_(memory_chunk_live_bytes_map),
        memory_chunk_typed_slots_map_(memory_chunk_typed_slots_map) {}
Member Function Documentation
EnableConcurrentVisitation()
static constexpr bool v8::internal::ConcurrentMarkingVisitor::EnableConcurrentVisitation () [inline], [static], [constexpr]
Definition at line 165 of file concurrent-marking.cc.
{ return true; }
IncrementLiveBytesCached()
void v8::internal::ConcurrentMarkingVisitor::IncrementLiveBytesCached (MutablePageMetadata * chunk, intptr_t by) [inline]
Definition at line 189 of file concurrent-marking.cc.
                                                                         {
    DCHECK_IMPLIES(V8_COMPRESS_POINTERS_8GB_BOOL,
                   IsAligned(by, kObjectAlignment8GbHeap));
    memory_chunk_live_bytes_map_->Increment(chunk, by);
  }
References DCHECK_IMPLIES, v8::internal::MemoryChunkLiveBytesMap::Increment(), IsAligned(), v8::internal::kObjectAlignment8GbHeap, memory_chunk_live_bytes_map_, and V8_COMPRESS_POINTERS_8GB_BOOL.
Referenced by v8::internal::ConcurrentMarking::RunMajor().
ProcessEphemeron()
bool v8::internal::ConcurrentMarkingVisitor::ProcessEphemeron (Tagged< HeapObject > key, Tagged< HeapObject > value) [inline]
Definition at line 169 of file concurrent-marking.cc.
                                                                          {
    if (marking_state()->IsMarked(key)) {
      const auto target_worklist =
          MarkingHelper::ShouldMarkObject(heap_, value);
      DCHECK(target_worklist.has_value());
      if (MarkObject(key, value, target_worklist.value())) {
        return true;
      }
    } else if (marking_state()->IsUnmarked(value)) {
      local_weak_objects_->next_ephemerons_local.Push(Ephemeron{key, value});
    }
    return false;
  }
References v8::internal::DCHECK(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::heap_, v8::internal::key, v8::internal::MarkingVisitorBase< ConcreteVisitor >::local_weak_objects_, v8::internal::FullMarkingVisitorBase< ConcurrentMarkingVisitor >::marking_state(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::MarkObject(), v8::internal::MarkingHelper::ShouldMarkObject(), and v8::internal::value.
Referenced by v8::internal::ConcurrentMarking::RunMajor().
RecordRelocSlot()
void v8::internal::ConcurrentMarkingVisitor::RecordRelocSlot (Tagged< InstructionStream > host, RelocInfo * rinfo, Tagged< HeapObject > target) [inline], [private]
Definition at line 196 of file concurrent-marking.cc.
                                                  {
    if (!MarkCompactCollector::ShouldRecordRelocSlot(host, rinfo, target)) {
      return;
    }
    MarkCompactCollector::RecordRelocSlotInfo info =
        MarkCompactCollector::ProcessRelocInfo(host, rinfo, target);
    auto& typed_slots = (*memory_chunk_typed_slots_map_)[info.page_metadata];
    if (!typed_slots) {
      typed_slots.reset(new TypedSlots());
    }
    typed_slots->Insert(info.slot_type, info.offset);
  }
References v8::internal::MarkCompactCollector::RecordRelocSlotInfo::offset, v8::internal::MarkCompactCollector::RecordRelocSlotInfo::page_metadata, v8::internal::MarkCompactCollector::ProcessRelocInfo(), v8::internal::MarkCompactCollector::ShouldRecordRelocSlot(), and v8::internal::MarkCompactCollector::RecordRelocSlotInfo::slot_type.
RecordSlot()
template<typename TSlot >
void v8::internal::ConcurrentMarkingVisitor::RecordSlot (Tagged< HeapObject > object, TSlot slot, Tagged< HeapObject > target) [inline]
Definition at line 184 of file concurrent-marking.cc.
                                             {
    MarkCompactCollector::RecordSlot(object, slot, target);
  }
References v8::internal::MarkCompactCollector::RecordSlot().
Friends And Related Function Documentation
MarkingVisitorBase< ConcurrentMarkingVisitor >
friend class MarkingVisitorBase< ConcurrentMarkingVisitor > [friend]
Definition at line 215 of file concurrent-marking.cc.
Member Data Documentation
memory_chunk_live_bytes_map_
MemoryChunkLiveBytesMap* v8::internal::ConcurrentMarkingVisitor::memory_chunk_live_bytes_map_ [private]
Definition at line 214 of file concurrent-marking.cc.
Referenced by IncrementLiveBytesCached().
memory_chunk_typed_slots_map_
MemoryChunkTypedSlotsMap* v8::internal::ConcurrentMarkingVisitor::memory_chunk_typed_slots_map_ [private]
Definition at line 215 of file concurrent-marking.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/concurrent-marking.cc