v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope Class Reference
Public Member Functions
MultipleEntryBlockContextScope (BytecodeGenerator *generator, Scope *scope)
void SetEnteredIf (bool condition)
~MultipleEntryBlockContextScope ()
MultipleEntryBlockContextScope (const MultipleEntryBlockContextScope &)=delete
MultipleEntryBlockContextScope & operator= (const MultipleEntryBlockContextScope &)=delete
Private Member Functions
void EnterScope ()
void ExitScope ()
Private Attributes
BytecodeGenerator * generator_
Scope * scope_
Register inner_context_
Register outer_context_
bool is_in_scope_
std::optional< CurrentScope > current_scope_
std::optional< ContextScope > context_scope_
Detailed Description
Definition at line 983 of file bytecode-generator.cc.
Constructor & Destructor Documentation
MultipleEntryBlockContextScope() [1/2]
v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::MultipleEntryBlockContextScope (BytecodeGenerator * generator, Scope * scope) [inline]
Definition at line 985 of file bytecode-generator.cc.
      : generator_(generator), scope_(scope), is_in_scope_(false) {
    if (scope) {
      inner_context_ = generator->register_allocator()->NewRegister();
      outer_context_ = generator->register_allocator()->NewRegister();
      generator->BuildNewLocalBlockContext(scope_);
      generator->builder()->StoreAccumulatorInRegister(inner_context_);
    }
  }
References v8::internal::interpreter::BytecodeGenerator::builder(), v8::internal::interpreter::BytecodeGenerator::BuildNewLocalBlockContext(), v8::internal::interpreter::BytecodeRegisterAllocator::NewRegister(), v8::internal::interpreter::BytecodeGenerator::register_allocator(), and v8::internal::interpreter::BytecodeArrayBuilder::StoreAccumulatorInRegister().
 MultipleEntryBlockContextScope()
v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::~MultipleEntryBlockContextScope () [inline]
Definition at line 1004 of file bytecode-generator.cc.
{ DCHECK(!is_in_scope_); }
References v8::internal::DCHECK().
MultipleEntryBlockContextScope() [2/2]
v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::MultipleEntryBlockContextScope (const MultipleEntryBlockContextScope &) [delete]
Member Function Documentation
EnterScope()
void v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::EnterScope () [inline], [private]
Definition at line 1012 of file bytecode-generator.cc.
                    {
    DCHECK(inner_context_.is_valid());
    DCHECK(outer_context_.is_valid());
    DCHECK(!is_in_scope_);
    generator_->builder()->LoadAccumulatorWithRegister(inner_context_);
    current_scope_.emplace(generator_, scope_);
    context_scope_.emplace(generator_, scope_, outer_context_);
    is_in_scope_ = true;
  }
References v8::internal::interpreter::BytecodeGenerator::current_scope_, and v8::internal::DCHECK().
ExitScope()
void v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::ExitScope () [inline], [private]
Definition at line 1022 of file bytecode-generator.cc.
                   {
    DCHECK(inner_context_.is_valid());
    DCHECK(outer_context_.is_valid());
    DCHECK(is_in_scope_);
    context_scope_ = std::nullopt;
    current_scope_ = std::nullopt;
    is_in_scope_ = false;
  }
References v8::internal::interpreter::BytecodeGenerator::current_scope_, and v8::internal::DCHECK().
operator=()
MultipleEntryBlockContextScope& v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::operator= (const MultipleEntryBlockContextScope &) [delete]
SetEnteredIf()
void v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::SetEnteredIf (bool condition) [inline]
Definition at line 995 of file bytecode-generator.cc.
                                    {
    RegisterAllocationScope register_scope(generator_);
    if (condition && scope_ != nullptr && !is_in_scope_) {
      EnterScope();
    } else if (!condition && is_in_scope_) {
      ExitScope();
    }
  }
Member Data Documentation
context_scope_
std::optional<ContextScope> v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::context_scope_ [private]
Definition at line 1037 of file bytecode-generator.cc.
current_scope_
std::optional<CurrentScope> v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::current_scope_ [private]
Definition at line 1036 of file bytecode-generator.cc.
generator_
BytecodeGenerator* v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::generator_ [private]
Definition at line 1031 of file bytecode-generator.cc.
inner_context_
Register v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::inner_context_ [private]
Definition at line 1033 of file bytecode-generator.cc.
is_in_scope_
bool v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::is_in_scope_ [private]
Definition at line 1035 of file bytecode-generator.cc.
outer_context_
Register v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::outer_context_ [private]
Definition at line 1034 of file bytecode-generator.cc.
scope_
Scope* v8::internal::interpreter::BytecodeGenerator::MultipleEntryBlockContextScope::scope_ [private]
Definition at line 1032 of file bytecode-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc