v8::base::WindowsTimezoneCache Class Reference
Public Member Functions
WindowsTimezoneCache ()
~WindowsTimezoneCache () override
void Clear (TimeZoneDetection) override
const char * LocalTimezone (double time) override
double LocalTimeOffset (double time, bool is_utc) override
double DaylightSavingsOffset (double time) override
void InitializeIfNeeded ()
const char * GuessTimezoneNameFromBias (int bias)
Private Attributes
bool initialized_
char std_tz_name_ [kTzNameSize]
char dst_tz_name_ [kTzNameSize]
TIME_ZONE_INFORMATION tzinfo_
Static Private Attributes
static const int kTzNameSize = 128
Friends
class Win32Time
Additional Inherited Members
Detailed Description
Definition at line 142 of file platform-win32.cc.
Constructor & Destructor Documentation
WindowsTimezoneCache()
v8::base::WindowsTimezoneCache::WindowsTimezoneCache () [inline]
Definition at line 144 of file platform-win32.cc.
: initialized_(false) {}
 WindowsTimezoneCache()
v8::base::WindowsTimezoneCache::~WindowsTimezoneCache () [inline], [override]
Definition at line 146 of file platform-win32.cc.
{}
Member Function Documentation
Clear()
void v8::base::WindowsTimezoneCache::Clear (TimeZoneDetection) [inline], [override], [virtual]
Implements v8::base::TimezoneCache.
Definition at line 148 of file platform-win32.cc.
{ initialized_ = false; }
References initialized_.
DaylightSavingsOffset()
double v8::base::WindowsTimezoneCache::DaylightSavingsOffset (double time) [override], [virtual]
Implements v8::base::TimezoneCache.
Definition at line 527 of file platform-win32.cc.
                                                              {
  int64_t offset = Win32Time(time).DaylightSavingsOffset(this);
  return static_cast<double>(offset);
}
References time(), and Win32Time.
GuessTimezoneNameFromBias()
const char* v8::base::WindowsTimezoneCache::GuessTimezoneNameFromBias (int bias) [inline]
Definition at line 207 of file platform-win32.cc.
                                                  {
    static const int kHour = 60;
    switch (-bias) {
      case -9*kHour: return "Alaska";
      case -8*kHour: return "Pacific";
      case -7*kHour: return "Mountain";
      case -6*kHour: return "Central";
      case -5*kHour: return "Eastern";
      case -4*kHour: return "Atlantic";
      case 0*kHour: return "GMT";
      case +1*kHour: return "Central Europe";
      case +2*kHour: return "Eastern Europe";
      case +3*kHour: return "Russia";
      case +5*kHour + 30: return "India";
      case +8*kHour: return "China";
      case +9*kHour: return "Japan";
      case +12*kHour: return "New Zealand";
      default: return "Local";
    }
  }
Referenced by InitializeIfNeeded().
InitializeIfNeeded()
void v8::base::WindowsTimezoneCache::InitializeIfNeeded () [inline]
Definition at line 158 of file platform-win32.cc.
                            {
    // Just return if timezone information has already been initialized.
    if (initialized_) return;
    // Initialize POSIX time zone data.
    _tzset();
    // Obtain timezone information from operating system.
    memset(&tzinfo_, 0, sizeof(tzinfo_));
    if (GetTimeZoneInformation(&tzinfo_) == TIME_ZONE_ID_INVALID) {
      // If we cannot get timezone information we fall back to CET.
      tzinfo_.Bias = -60;
      tzinfo_.StandardDate.wMonth = 10;
      tzinfo_.StandardDate.wDay = 5;
      tzinfo_.StandardDate.wHour = 3;
      tzinfo_.StandardBias = 0;
      tzinfo_.DaylightDate.wMonth = 3;
      tzinfo_.DaylightDate.wDay = 5;
      tzinfo_.DaylightDate.wHour = 2;
      tzinfo_.DaylightBias = -60;
    }
    // Make standard and DST timezone names.
    WideCharToMultiByte(CP_UTF8, 0, tzinfo_.StandardName, -1, std_tz_name_,
                        kTzNameSize, nullptr, nullptr);
    std_tz_name_[kTzNameSize - 1] = '\0';
    WideCharToMultiByte(CP_UTF8, 0, tzinfo_.DaylightName, -1, dst_tz_name_,
                        kTzNameSize, nullptr, nullptr);
    dst_tz_name_[kTzNameSize - 1] = '\0';
    // If OS returned empty string or resource id (like "@tzres.dll,-211")
    // simply guess the name from the UTC bias of the timezone.
    // To properly resolve the resource identifier requires a library load,
    // which is not possible in a sandbox.
    if (std_tz_name_[0] == '\0' || std_tz_name_[0] == '@') {
      OS::SNPrintF(std_tz_name_, kTzNameSize - 1,
                   "%s Standard Time",
                   GuessTimezoneNameFromBias(tzinfo_.Bias));
    }
    if (dst_tz_name_[0] == '\0' || dst_tz_name_[0] == '@') {
      OS::SNPrintF(dst_tz_name_, kTzNameSize - 1,
                   "%s Daylight Time",
                   GuessTimezoneNameFromBias(tzinfo_.Bias));
    }
    // Timezone information initialized.
    initialized_ = true;
  }
References dst_tz_name_, GuessTimezoneNameFromBias(), initialized_, kTzNameSize, v8::base::SNPrintF(), std_tz_name_, and tzinfo_.
Referenced by v8::base::Win32Time::InDST(), and v8::base::Win32Time::LocalOffset().
LocalTimeOffset()
double v8::base::WindowsTimezoneCache::LocalTimeOffset (double time, bool is_utc) [override], [virtual]
Implements v8::base::TimezoneCache.
Definition at line 515 of file platform-win32.cc.
                                                                        {
  // Ignore is_utc and time_ms for now. That way, the behavior wouldn't
  // change with icu_timezone_data disabled.
  // Use current time, rounded to the millisecond.
  Win32Time t(OS::TimeCurrentMillis());
  // Time::LocalOffset inlcudes any daylight savings offset, so subtract it.
  return static_cast<double>(t.LocalOffset(this) -
                             t.DaylightSavingsOffset(this));
}
References v8::base::Win32Time::DaylightSavingsOffset(), v8::base::Win32Time::LocalOffset(), and v8::base::OS::TimeCurrentMillis().
LocalTimezone()
const char * v8::base::WindowsTimezoneCache::LocalTimezone (double time) [override], [virtual]
Implements v8::base::TimezoneCache.
Definition at line 509 of file platform-win32.cc.
                                                           {
  return Win32Time(time).LocalTimezone(this);
}
References time(), and Win32Time.
Friends And Related Function Documentation
Win32Time
friend class Win32Time [friend]
Definition at line 235 of file platform-win32.cc.
Referenced by DaylightSavingsOffset(), and LocalTimezone().
Member Data Documentation
dst_tz_name_
char v8::base::WindowsTimezoneCache::dst_tz_name_[kTzNameSize] [private]
Definition at line 233 of file platform-win32.cc.
Referenced by InitializeIfNeeded(), and v8::base::Win32Time::LocalTimezone().
initialized_
bool v8::base::WindowsTimezoneCache::initialized_ [private]
Definition at line 231 of file platform-win32.cc.
Referenced by Clear(), and InitializeIfNeeded().
kTzNameSize
const int v8::base::WindowsTimezoneCache::kTzNameSize = 128 [static], [private]
Definition at line 230 of file platform-win32.cc.
Referenced by InitializeIfNeeded().
std_tz_name_
char v8::base::WindowsTimezoneCache::std_tz_name_[kTzNameSize] [private]
Definition at line 232 of file platform-win32.cc.
Referenced by InitializeIfNeeded(), and v8::base::Win32Time::LocalTimezone().
tzinfo_
TIME_ZONE_INFORMATION v8::base::WindowsTimezoneCache::tzinfo_ [private]
Definition at line 234 of file platform-win32.cc.
Referenced by v8::base::Win32Time::InDST(), InitializeIfNeeded(), and v8::base::Win32Time::LocalOffset().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/platform/platform-win32.cc