v8::Boolean Class Reference
A primitive boolean value (ECMA-262, 4.3.14).
#include <v8-primitive.h>
Public Member Functions
bool Value () const
Static Public Member Functions
static Boolean * Cast (v8::Data *data)
static Local< Boolean > New (Isolate *isolate, bool value)
Static Private Member Functions
static void CheckCast (v8::Data *that)
Detailed Description
A primitive boolean value (ECMA-262, 4.3.14).
Either the true or false value.
Definition at line 35 of file v8-primitive.h.
Member Function Documentation
Cast()
static Boolean* v8::Boolean::Cast (v8::Data * data) [inline], [static]
Definition at line 38 of file v8-primitive.h.
                                               {
#ifdef V8_ENABLE_CHECKS
    CheckCast(data);
#endif
    return static_cast<Boolean*>(data);
  }
CheckCast()
void v8::Boolean::CheckCast (v8::Data * that) [static], [private]
Definition at line 3875 of file api.cc.
                                      {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsBoolean(*obj), "v8::Boolean::Cast",
                  "Value is not a Boolean");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
New()
Local< Boolean > v8::Boolean::New (Isolate * isolate, bool value) [inline], [static]
Definition at line 1087 of file v8-primitive.h.
                                                        {
  return value ? True(isolate) : False(isolate);
}
References v8::False(), v8::True(), and v8::internal::value.
Referenced by v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append().
Value()
bool v8::Boolean::Value () const
Definition at line 6188 of file api.cc.
                          {
  return i::IsTrue(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildDeepSerializedValue(), and v8_inspector::toProtocolValue().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc