v8::internal::OptimizedJSFrame Class Reference
#include <frames.h>
Public Member Functions
void GetFunctions (std::vector< Tagged< SharedFunctionInfo >> *functions) const override
FrameSummaries Summarize () const override
Tagged< DeoptimizationData > GetDeoptimizationData (Tagged< Code > code, int *deopt_index) const
int LookupExceptionHandlerInTable (int *data, HandlerTable::CatchPrediction *prediction) override
virtual int FindReturnPCForTrampoline (Tagged< Code > code, int trampoline_pc) const =0
Static Public Member Functions
static int StackSlotOffsetRelativeToFp (int slot_index)
Protected Member Functions
OptimizedJSFrame (StackFrameIteratorBase *iterator)
Additional Inherited Members
Detailed Description
Definition at line 1067 of file frames.h.
Constructor & Destructor Documentation
OptimizedJSFrame()
v8::internal::OptimizedJSFrame::OptimizedJSFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 303 of file frames-inl.h.
    : JavaScriptFrame(iterator) {}
Member Function Documentation
FindReturnPCForTrampoline()
virtual int v8::internal::OptimizedJSFrame::FindReturnPCForTrampoline (Tagged< Code > code, int trampoline_pc) const [pure virtual]
Implemented in v8::internal::TurbofanJSFrame, and v8::internal::MaglevFrame.
GetDeoptimizationData()
Tagged< DeoptimizationData > v8::internal::OptimizedJSFrame::GetDeoptimizationData (Tagged< Code > code, int * deopt_index) const
Definition at line 3205 of file frames.cc.
                                               {
  DCHECK(is_optimized());
  Address pc = maybe_unauthenticated_pc();
  DCHECK(code->contains(isolate(), pc));
  DCHECK(CodeKindCanDeoptimize(code->kind()));
  if (code->is_maglevved()) {
    MaglevSafepointEntry safepoint_entry =
        code->GetMaglevSafepointEntry(isolate(), pc);
    if (safepoint_entry.has_deoptimization_index()) {
      *deopt_index = safepoint_entry.deoptimization_index();
      return Cast<DeoptimizationData>(code->deoptimization_data());
    }
  } else {
    SafepointEntry safepoint_entry = code->GetSafepointEntry(isolate(), pc);
    if (safepoint_entry.has_deoptimization_index()) {
      *deopt_index = safepoint_entry.deoptimization_index();
      return Cast<DeoptimizationData>(code->deoptimization_data());
    }
  }
  *deopt_index = SafepointEntry::kNoDeoptIndex;
  return {};
}
References code, v8::internal::CodeKindCanDeoptimize(), v8::internal::DCHECK(), v8::internal::SafepointEntryBase::deoptimization_index(), v8::internal::SafepointEntryBase::has_deoptimization_index(), and v8::internal::SafepointEntryBase::kNoDeoptIndex.
Referenced by v8::internal::MaglevFrame::GetBytecodeOffsetForOSR().
GetFunctions()
void v8::internal::OptimizedJSFrame::GetFunctions (std::vector< Tagged< SharedFunctionInfo >> * functions) const [override], [virtual]
Reimplemented from v8::internal::JavaScriptFrame.
Definition at line 3232 of file frames.cc.
                                                            {
  DCHECK(functions->empty());
  DCHECK(is_optimized());
  // Delegate to JS frame in absence of turbofan deoptimization.
  // TODO(turbofan): Revisit once we support deoptimization across the board.
  Tagged<Code> code = LookupCode();
  if (code->kind() == CodeKind::BUILTIN) {
    return JavaScriptFrame::GetFunctions(functions);
  }
  DisallowGarbageCollection no_gc;
  int deopt_index = SafepointEntry::kNoDeoptIndex;
  Tagged<DeoptimizationData> const data =
      GetDeoptimizationData(code, &deopt_index);
  DCHECK(!data.is_null());
  DCHECK_NE(SafepointEntry::kNoDeoptIndex, deopt_index);
  Tagged<DeoptimizationLiteralArray> const literal_array = data->LiteralArray();
  DeoptimizationFrameTranslation::Iterator it(
      data->FrameTranslation(), data->TranslationIndex(deopt_index).value());
  int jsframe_count = it.EnterBeginOpcode().js_frame_count;
  // We insert the frames in reverse order because the frames
  // in the deoptimization translation are ordered bottom-to-top.
  while (jsframe_count != 0) {
    TranslationOpcode opcode = it.SeekNextJSFrame();
    it.NextOperand(); // Skip bailout id.
    jsframe_count--;
    // The second operand of the frame points to the function.
    Tagged<Object> shared = literal_array->get(it.NextOperand());
    functions->push_back(Cast<SharedFunctionInfo>(shared));
    // Skip over remaining operands to advance to the next opcode.
    it.SkipOperands(TranslationOpcodeOperandCount(opcode) - 2);
  }
}
References BUILTIN, code, v8::internal::DCHECK(), DCHECK_NE, v8::internal::DeoptTranslationIterator::EnterBeginOpcode(), v8::internal::JavaScriptFrame::GetFunctions(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::DeoptimizationFrameTranslation::FrameCount::js_frame_count, v8::internal::SafepointEntryBase::kNoDeoptIndex, v8::internal::DeoptTranslationIterator::NextOperand(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::DeoptTranslationIterator::SeekNextJSFrame(), v8::internal::DeoptTranslationIterator::SkipOperands(), and v8::internal::TranslationOpcodeOperandCount().
LookupExceptionHandlerInTable()
int v8::internal::OptimizedJSFrame::LookupExceptionHandlerInTable (int * data, HandlerTable::CatchPrediction * prediction) [override], [virtual]
Reimplemented from v8::internal::CommonFrameWithJSLinkage.
Definition at line 3153 of file frames.cc.
                                                        {
  // We cannot perform exception prediction on optimized code. Instead, we need
  // to use FrameSummary to find the corresponding code offset in unoptimized
  // code to perform prediction there.
  DCHECK_NULL(prediction);
  Tagged<Code> code;
  int pc_offset = -1;
  std::tie(code, pc_offset) = LookupCodeAndOffset();
  HandlerTable table(code);
  if (table.NumberOfReturnEntries() == 0) return -1;
  DCHECK_NULL(data); // Data is not used and will not return a value.
  // When the return pc has been replaced by a trampoline there won't be
  // a handler for this trampoline. Thus we need to use the return pc that
  // _used to be_ on the stack to get the right ExceptionHandler.
  if (CodeKindCanDeoptimize(code->kind())) {
    if (!code->marked_for_deoptimization()) {
      // Lazy deoptimize the function in case the handler table entry flags that
      // it wants to be lazily deoptimized on throw. This allows the optimizing
      // compiler to omit catch blocks that were never reached in practice.
      int optimized_exception_handler = table.LookupReturn(pc_offset);
      if (optimized_exception_handler != HandlerTable::kLazyDeopt) {
        return optimized_exception_handler;
      }
      Deoptimizer::DeoptimizeFunction(
          function(), LazyDeoptimizeReason::kExceptionCaught, code);
    }
    DCHECK(code->marked_for_deoptimization());
    pc_offset = FindReturnPCForTrampoline(code, pc_offset);
  }
  return table.LookupReturn(pc_offset);
}
References code, v8::internal::CodeKindCanDeoptimize(), v8::internal::DCHECK(), DCHECK_NULL, v8::internal::Deoptimizer::DeoptimizeFunction(), v8::internal::HandlerTable::kLazyDeopt, v8::internal::HandlerTable::LookupReturn(), and v8::internal::HandlerTable::NumberOfReturnEntries().
Referenced by v8::internal::Isolate::UnwindAndFindHandler().
StackSlotOffsetRelativeToFp()
int v8::internal::OptimizedJSFrame::StackSlotOffsetRelativeToFp (int slot_index) [static]
Definition at line 3272 of file frames.cc.
                                                                {
  return StandardFrameConstants::kCallerSPOffset -
         ((slot_index + 1) * kSystemPointerSize);
}
References v8::internal::CommonFrameConstants::kCallerSPOffset, and v8::internal::kSystemPointerSize.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue().
Summarize()
FrameSummaries v8::internal::OptimizedJSFrame::Summarize () const [override], [virtual]
Reimplemented from v8::internal::CommonFrameWithJSLinkage.
Definition at line 3029 of file frames.cc.
                                                 {
  DCHECK(is_optimized());
  FrameSummaries summaries;
  // Delegate to JS frame in absence of deoptimization info.
  // TODO(turbofan): Revisit once we support deoptimization across the board.
  DirectHandle<Code> code(LookupCode(), isolate());
  if (code->kind() == CodeKind::BUILTIN ||
      code->kind() == CodeKind::FOR_TESTING) {
    return JavaScriptFrame::Summarize();
  }
  int deopt_index = SafepointEntry::kNoDeoptIndex;
  Tagged<DeoptimizationData> const data =
      GetDeoptimizationData(*code, &deopt_index);
  if (deopt_index == SafepointEntry::kNoDeoptIndex) {
    // Hack: For maglevved function entry, we don't emit lazy deopt information,
    // so create an extra special summary here.
    //
    // TODO(leszeks): Remove this hack, by having a maglev-specific frame
    // summary which is a bit more aware of maglev behaviour and can e.g. handle
    // more compact safepointed frame information for both function entry and
    // loop stack checks.
    if (code->is_maglevved()) {
      DirectHandle<AbstractCode> abstract_code(
          Cast<AbstractCode>(function()->shared()->GetBytecodeArray(isolate())),
          isolate());
      DirectHandle<FixedArray> params = GetParameters();
      FrameSummary::JavaScriptFrameSummary summary(
          isolate(), receiver(), function(), *abstract_code,
          kFunctionEntryBytecodeOffset, IsConstructor(), *params);
      summaries.frames.push_back(summary);
      return summaries;
    }
    CHECK(data.is_null());
    FATAL(
        "Missing deoptimization information for OptimizedJSFrame::Summarize.");
  }
  // Prepare iteration over translation. We must not materialize values here
  // because we do not deoptimize the function.
  TranslatedState translated(this);
  translated.Prepare(fp());
  // We create the summary in reverse order because the frames
  // in the deoptimization translation are ordered bottom-to-top.
  bool is_constructor = IsConstructor();
  for (auto it = translated.begin(); it != translated.end(); it++) {
    if (it->kind() == TranslatedFrame::kUnoptimizedFunction ||
        it->kind() == TranslatedFrame::kJavaScriptBuiltinContinuation ||
        it->kind() ==
            TranslatedFrame::kJavaScriptBuiltinContinuationWithCatch) {
      DirectHandle<SharedFunctionInfo> shared_info = it->shared_info();
      // The translation commands are ordered and the function is always
      // at the first position, and the receiver is next.
      TranslatedFrame::iterator translated_values = it->begin();
      // Get the correct function in the optimized frame.
      CHECK(!translated_values->IsMaterializedObject());
      DirectHandle<JSFunction> function =
          Cast<JSFunction>(translated_values->GetValue());
      translated_values++;
      // Get the correct receiver in the optimized frame.
      CHECK(!translated_values->IsMaterializedObject());
      DirectHandle<Object> receiver = translated_values->GetValue();
      translated_values++;
      // Determine the underlying code object and the position within it from
      // the translation corresponding to the frame type in question.
      DirectHandle<AbstractCode> abstract_code;
      unsigned code_offset;
      if (it->kind() == TranslatedFrame::kJavaScriptBuiltinContinuation ||
          it->kind() ==
              TranslatedFrame::kJavaScriptBuiltinContinuationWithCatch) {
        code_offset = 0;
        abstract_code = Cast<AbstractCode>(isolate()->builtins()->code_handle(
            Builtins::GetBuiltinFromBytecodeOffset(it->bytecode_offset())));
      } else {
        DCHECK_EQ(it->kind(), TranslatedFrame::kUnoptimizedFunction);
        code_offset = it->bytecode_offset().ToInt();
        abstract_code =
            direct_handle(shared_info->abstract_code(isolate()), isolate());
      }
      // Append full summary of the encountered JS frame.
      DirectHandle<FixedArray> params = GetParameters();
      FrameSummary::JavaScriptFrameSummary summary(
          isolate(), *receiver, *function, *abstract_code, code_offset,
          is_constructor, *params);
      summaries.frames.push_back(summary);
      is_constructor = false;
    } else if (it->kind() == TranslatedFrame::kConstructCreateStub ||
               it->kind() == TranslatedFrame::kConstructInvokeStub) {
      // The next encountered JS frame will be marked as a constructor call.
      DCHECK(!is_constructor);
      is_constructor = true;
#if V8_ENABLE_WEBASSEMBLY
    } else if (it->kind() == TranslatedFrame::kWasmInlinedIntoJS) {
      DirectHandle<SharedFunctionInfo> shared_info = it->shared_info();
      DCHECK_NE(isolate()->heap()->gc_state(), Heap::MARK_COMPACT);
      Tagged<WasmExportedFunctionData> function_data =
          shared_info->wasm_exported_function_data();
      Handle<WasmTrustedInstanceData> instance{function_data->instance_data(),
                                               isolate()};
      int func_index = function_data->function_index();
      FrameSummary::WasmInlinedFrameSummary summary(
          isolate(), instance, func_index, it->bytecode_offset().ToInt());
      summaries.frames.push_back(summary);
#endif // V8_ENABLE_WEBASSEMBLY
    }
  }
  if (is_constructor) {
    // If {is_constructor} is true, then we haven't inlined the constructor in
    // the optimized frames and the previous visited frame (top of the inlined
    // frames) is a construct call.
    summaries.top_frame_is_construct_call = true;
  }
  return summaries;
}
References v8::internal::TranslatedState::begin(), BUILTIN, CHECK, code, v8::internal::FrameSummary::code_offset(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::direct_handle(), v8::internal::TranslatedState::end(), FATAL, v8::internal::FrameSummaries::frames, v8::internal::Builtins::GetBuiltinFromBytecodeOffset(), v8::bigint::anonymous_namespace{mul-fft.cc}::GetParameters(), v8::internal::TranslatedValue::GetValue(), heap(), v8::internal::FrameSummary::is_constructor(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::TranslatedValue::IsMaterializedObject(), v8::internal::TranslatedFrame::kConstructCreateStub, v8::internal::TranslatedFrame::kConstructInvokeStub, v8::internal::kFunctionEntryBytecodeOffset, v8::internal::TranslatedFrame::kJavaScriptBuiltinContinuation, v8::internal::TranslatedFrame::kJavaScriptBuiltinContinuationWithCatch, v8::internal::SafepointEntryBase::kNoDeoptIndex, v8::internal::TranslatedFrame::kUnoptimizedFunction, v8::internal::Heap::MARK_COMPACT, v8::internal::TranslatedState::Prepare(), v8::internal::FrameSummary::receiver(), v8::internal::CommonFrameWithJSLinkage::Summarize(), and v8::internal::FrameSummaries::top_frame_is_construct_call.
Referenced by v8::internal::MaglevFrame::GetInnermostFunction().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc