v8::internal::compiler::MachineOperatorBuilder Class Reference
#include <machine-operator.h>
Classes
class AlignmentRequirements
Public Types
enum Flag : unsigned {
kNoFlags = 0u
, kFloat32RoundDown = 1u << 0
, kFloat64RoundDown = 1u << 1
, kFloat32RoundUp = 1u << 2
,
kFloat64RoundUp = 1u << 3
, kFloat32RoundTruncate = 1u << 4
, kFloat64RoundTruncate = 1u << 5
, kFloat32RoundTiesEven = 1u << 6
,
kFloat64RoundTiesEven = 1u << 7
, kFloat64RoundTiesAway = 1u << 8
, kInt32DivIsSafe = 1u << 9
, kUint32DivIsSafe = 1u << 10
,
kWord32ShiftIsSafe = 1u << 11
, kWord32Ctz = 1u << 12
, kWord64Ctz = 1u << 13
, kWord64CtzLowerable = 1u << 14
,
kWord32Popcnt = 1u << 15
, kWord64Popcnt = 1u << 16
, kWord32ReverseBits = 1u << 17
, kWord64ReverseBits = 1u << 18
,
kFloat32Select = 1u << 19
, kFloat64Select = 1u << 20
, kInt32AbsWithOverflow = 1u << 21
, kInt64AbsWithOverflow = 1u << 22
,
kWord32Rol = 1u << 23
, kWord64Rol = 1u << 24
, kWord64RolLowerable = 1u << 25
, kSatConversionIsSafe = 1u << 26
,
kWord32Select = 1u << 27
, kWord64Select = 1u << 28
, kLoadStorePairs = 1u << 29
, kFloat16 = 1u << 30
,
kFloat16RawBitsConversion = 1u << 31
, kAllOptionalOps
 }
using Flags = base::Flags< Flag, unsigned >
Public Member Functions
MachineOperatorBuilder (Zone *zone, MachineRepresentation word=MachineType::PointerRepresentation(), Flags supportedOperators=kNoFlags, AlignmentRequirements alignmentRequirements=AlignmentRequirements::FullUnalignedAccessSupport())
MachineOperatorBuilder (const MachineOperatorBuilder &)=delete
MachineOperatorBuilder & operator= (const MachineOperatorBuilder &)=delete
const Operator * Comment (const char *msg)
const Operator * AbortCSADcheck ()
const Operator * DebugBreak ()
const Operator * Word32And ()
const Operator * Word32Or ()
const Operator * Word32Xor ()
const Operator * Word32Shl ()
const Operator * Word32Shr ()
const Operator * Word32Sar (ShiftKind kind)
const Operator * Word32Sar ()
const Operator * Word32SarShiftOutZeros ()
const OptionalOperator Word32Rol ()
const Operator * Word32Ror ()
const Operator * Word32Equal ()
const Operator * Word32Clz ()
const OptionalOperator Word32Ctz ()
const OptionalOperator Word32Popcnt ()
const OptionalOperator Word64Popcnt ()
const OptionalOperator Word32ReverseBits ()
const OptionalOperator Word64ReverseBits ()
const Operator * Word32ReverseBytes ()
const Operator * Word64ReverseBytes ()
const Operator * Simd128ReverseBytes ()
const OptionalOperator Int32AbsWithOverflow ()
const OptionalOperator Int64AbsWithOverflow ()
bool Word32ShiftIsSafe () const
bool SatConversionIsSafe () const
bool SupportsLoadStorePairs () const
const Operator * Word64And ()
const Operator * Word64Or ()
const Operator * Word64Xor ()
const Operator * Word64Shl ()
const Operator * Word64Shr ()
const Operator * Word64Sar (ShiftKind kind)
const Operator * Word64Sar ()
const Operator * Word64SarShiftOutZeros ()
const OptionalOperator Word64Rol ()
const Operator * Word64Ror ()
const Operator * Word64Clz ()
const OptionalOperator Word64Ctz ()
const OptionalOperator Word64RolLowerable ()
const Operator * Word64RorLowerable ()
const Operator * Word64ClzLowerable ()
const OptionalOperator Word64CtzLowerable ()
const Operator * Word64Equal ()
const Operator * Int32PairAdd ()
const Operator * Int32PairSub ()
const Operator * Int32PairMul ()
const Operator * Word32PairShl ()
const Operator * Word32PairShr ()
const Operator * Word32PairSar ()
const Operator * Int32Add ()
const Operator * Int32AddWithOverflow ()
const Operator * Int32Sub ()
const Operator * Int32SubWithOverflow ()
const Operator * Int32Mul ()
const Operator * Int32MulWithOverflow ()
const Operator * Int32MulHigh ()
const Operator * Int32Div ()
const Operator * Int32Mod ()
const Operator * Int32LessThan ()
const Operator * Int32LessThanOrEqual ()
const Operator * Uint32Div ()
const Operator * Uint32LessThan ()
const Operator * Uint32LessThanOrEqual ()
const Operator * Uint32Mod ()
const Operator * Uint32MulHigh ()
bool Int32DivIsSafe () const
bool Uint32DivIsSafe () const
const Operator * Int64Add ()
const Operator * Int64AddWithOverflow ()
const Operator * Int64Sub ()
const Operator * Int64SubWithOverflow ()
const Operator * Int64Mul ()
const Operator * Int64MulHigh ()
const Operator * Int64MulWithOverflow ()
const Operator * Int64Div ()
const Operator * Int64Mod ()
const Operator * Int64LessThan ()
const Operator * Int64LessThanOrEqual ()
const Operator * Uint64Div ()
const Operator * Uint64LessThan ()
const Operator * Uint64LessThanOrEqual ()
const Operator * Uint64Mod ()
const Operator * Uint64MulHigh ()
const Operator * BitcastTaggedToWord ()
const Operator * BitcastTaggedToWordForTagAndSmiBits ()
const Operator * BitcastMaybeObjectToWord ()
const Operator * BitcastWordToTagged ()
const Operator * BitcastWordToTaggedSigned ()
const Operator * TruncateFloat64ToWord32 ()
const Operator * ChangeFloat32ToFloat64 ()
const Operator * ChangeFloat64ToInt32 ()
const Operator * ChangeFloat64ToInt64 ()
const Operator * ChangeFloat64ToUint32 ()
const Operator * ChangeFloat64ToUint64 ()
const Operator * TruncateFloat64ToInt64 (TruncateKind kind)
const Operator * TruncateFloat64ToUint32 ()
const Operator * TruncateFloat32ToInt32 (TruncateKind kind)
const Operator * TruncateFloat32ToUint32 (TruncateKind kind)
const Operator * TryTruncateFloat32ToInt64 ()
const Operator * TryTruncateFloat64ToInt64 ()
const Operator * TryTruncateFloat32ToUint64 ()
const Operator * TryTruncateFloat64ToUint64 ()
const Operator * TryTruncateFloat64ToInt32 ()
const Operator * TryTruncateFloat64ToUint32 ()
const Operator * ChangeInt32ToFloat64 ()
const Operator * BitcastWord32ToWord64 ()
const Operator * ChangeInt32ToInt64 ()
const Operator * ChangeInt64ToFloat64 ()
const Operator * ChangeUint32ToFloat64 ()
const Operator * ChangeUint32ToUint64 ()
const Operator * TruncateFloat64ToFloat32 ()
const OptionalOperator ChangeFloat16RawBitsToFloat64 ()
const OptionalOperator TruncateFloat64ToFloat16RawBits ()
const Operator * TruncateInt64ToInt32 ()
const Operator * RoundFloat64ToInt32 ()
const Operator * RoundInt32ToFloat32 ()
const Operator * RoundInt64ToFloat32 ()
const Operator * RoundInt64ToFloat64 ()
const Operator * RoundUint32ToFloat32 ()
const Operator * RoundUint64ToFloat32 ()
const Operator * RoundUint64ToFloat64 ()
const Operator * BitcastFloat32ToInt32 ()
const Operator * BitcastFloat64ToInt64 ()
const Operator * BitcastInt32ToFloat32 ()
const Operator * BitcastInt64ToFloat64 ()
const Operator * SignExtendWord8ToInt32 ()
const Operator * SignExtendWord16ToInt32 ()
const Operator * SignExtendWord8ToInt64 ()
const Operator * SignExtendWord16ToInt64 ()
const Operator * SignExtendWord32ToInt64 ()
const Operator * Float32Add ()
const Operator * Float32Sub ()
const Operator * Float32Mul ()
const Operator * Float32Div ()
const Operator * Float32Sqrt ()
const Operator * Float64Add ()
const Operator * Float64Sub ()
const Operator * Float64Mul ()
const Operator * Float64Div ()
const Operator * Float64Mod ()
const Operator * Float64Sqrt ()
const Operator * Float32Equal ()
const Operator * Float32LessThan ()
const Operator * Float32LessThanOrEqual ()
const Operator * Float64Equal ()
const Operator * Float64LessThan ()
const Operator * Float64LessThanOrEqual ()
const Operator * Float64Max ()
const Operator * Float64Min ()
const Operator * Float32Max ()
const Operator * Float32Min ()
const Operator * Float32Abs ()
const Operator * Float64Abs ()
const OptionalOperator Float32RoundDown ()
const OptionalOperator Float64RoundDown ()
const OptionalOperator Float32RoundUp ()
const OptionalOperator Float64RoundUp ()
const OptionalOperator Float32RoundTruncate ()
const OptionalOperator Float64RoundTruncate ()
const OptionalOperator Float64RoundTiesAway ()
const OptionalOperator Float32RoundTiesEven ()
const OptionalOperator Float64RoundTiesEven ()
const OptionalOperator Word32Select ()
const OptionalOperator Word64Select ()
const OptionalOperator Float32Select ()
const OptionalOperator Float64Select ()
const Operator * Float32Neg ()
const Operator * Float64Neg ()
const Operator * Float64Acos ()
const Operator * Float64Acosh ()
const Operator * Float64Asin ()
const Operator * Float64Asinh ()
const Operator * Float64Atan ()
const Operator * Float64Atan2 ()
const Operator * Float64Atanh ()
const Operator * Float64Cos ()
const Operator * Float64Cosh ()
const Operator * Float64Sin ()
const Operator * Float64Sinh ()
const Operator * Float64Tan ()
const Operator * Float64Tanh ()
const Operator * Float64Exp ()
const Operator * Float64Expm1 ()
const Operator * Float64Pow ()
const Operator * Float64Log ()
const Operator * Float64Log1p ()
const Operator * Float64Log2 ()
const Operator * Float64Log10 ()
const Operator * Float64Cbrt ()
const Operator * Float64ExtractLowWord32 ()
const Operator * Float64ExtractHighWord32 ()
const Operator * Float64InsertLowWord32 ()
const Operator * Float64InsertHighWord32 ()
const Operator * Float64SilenceNaN ()
const Operator * I8x16Splat ()
const Operator * I8x16Eq ()
const Operator * I8x16BitMask ()
const Operator * TraceInstruction (uint32_t markid)
const Operator * Load (LoadRepresentation rep)
const Operator * LoadImmutable (LoadRepresentation rep)
const Operator * ProtectedLoad (LoadRepresentation rep)
const Operator * LoadTrapOnNull (LoadRepresentation rep)
const Operator * Store (StoreRepresentation rep)
std::optional< const Operator * > TryStorePair (StoreRepresentation rep1, StoreRepresentation rep2)
const Operator * StoreIndirectPointer (WriteBarrierKind write_barrier_kind)
const Operator * ProtectedStore (MachineRepresentation rep)
const Operator * StoreTrapOnNull (StoreRepresentation rep)
const Operator * UnalignedLoad (LoadRepresentation rep)
const Operator * UnalignedStore (UnalignedStoreRepresentation rep)
const Operator * StackSlot (int size, int alignment=0, bool is_tagged=false)
const Operator * StackSlot (MachineRepresentation rep, int alignment=0)
const Operator * LoadRootRegister ()
const Operator * LoadFramePointer ()
const Operator * LoadParentFramePointer ()
const Operator * StackPointerGreaterThan (StackCheckKind kind)
const Operator * LoadStackCheckOffset ()
const Operator * MemoryBarrier (AtomicMemoryOrder order)
const Operator * Word32AtomicLoad (AtomicLoadParameters params)
const Operator * Word64AtomicLoad (AtomicLoadParameters params)
const Operator * Word32AtomicStore (AtomicStoreParameters params)
const Operator * Word64AtomicStore (AtomicStoreParameters params)
const Operator * Word32AtomicExchange (AtomicOpParameters params)
const Operator * Word64AtomicExchange (AtomicOpParameters params)
const Operator * Word32AtomicCompareExchange (AtomicOpParameters params)
const Operator * Word64AtomicCompareExchange (AtomicOpParameters params)
const Operator * Word32AtomicAdd (AtomicOpParameters params)
const Operator * Word32AtomicSub (AtomicOpParameters params)
const Operator * Word32AtomicAnd (AtomicOpParameters params)
const Operator * Word32AtomicOr (AtomicOpParameters params)
const Operator * Word32AtomicXor (AtomicOpParameters params)
const Operator * Word64AtomicAdd (AtomicOpParameters params)
const Operator * Word64AtomicSub (AtomicOpParameters params)
const Operator * Word64AtomicAnd (AtomicOpParameters params)
const Operator * Word64AtomicOr (AtomicOpParameters params)
const Operator * Word64AtomicXor (AtomicOpParameters params)
const Operator * Word32AtomicPairLoad (AtomicMemoryOrder order)
const Operator * Word32AtomicPairStore (AtomicMemoryOrder order)
const Operator * Word32AtomicPairAdd ()
const Operator * Word32AtomicPairSub ()
const Operator * Word32AtomicPairAnd ()
const Operator * Word32AtomicPairOr ()
const Operator * Word32AtomicPairXor ()
const Operator * Word32AtomicPairExchange ()
const Operator * Word32AtomicPairCompareExchange ()
bool Is32 () const
bool Is64 () const
MachineRepresentation word () const
bool UnalignedLoadSupported (MachineRepresentation rep)
bool UnalignedStoreSupported (MachineRepresentation rep)
const Operator * WordSar (ShiftKind kind=ShiftKind::kNormal)
const Operator * WordSarShiftOutZeros ()
const Operator * TaggedEqual ()
Private Attributes
Zone * zone_
MachineOperatorGlobalCache const & cache_
MachineRepresentation const word_
Flags const flags_
AlignmentRequirements const alignment_requirements_
Detailed Description
Definition at line 376 of file machine-operator.h.
Member Typedef Documentation
Flags
using v8::internal::compiler::MachineOperatorBuilder::Flags = base::Flags<Flag, unsigned>
Definition at line 426 of file machine-operator.h.
Member Enumeration Documentation
Flag
enum v8::internal::compiler::MachineOperatorBuilder::Flag : unsigned
Enumerator
kNoFlags
kFloat32RoundDown
kFloat64RoundDown
kFloat32RoundUp
kFloat64RoundUp
kFloat32RoundTruncate
kFloat64RoundTruncate
kFloat32RoundTiesEven
kFloat64RoundTiesEven
kFloat64RoundTiesAway
kInt32DivIsSafe
kUint32DivIsSafe
kWord32ShiftIsSafe
kWord32Ctz
kWord64Ctz
kWord64CtzLowerable
kWord32Popcnt
kWord64Popcnt
kWord32ReverseBits
kWord64ReverseBits
kFloat32Select
kFloat64Select
kInt32AbsWithOverflow
kInt64AbsWithOverflow
kWord32Rol
kWord64Rol
kWord64RolLowerable
kSatConversionIsSafe
kWord32Select
kWord64Select
kLoadStorePairs
kFloat16
kFloat16RawBitsConversion
kAllOptionalOps
Definition at line 381 of file machine-operator.h.
            : unsigned {
    kNoFlags = 0u,
    kFloat32RoundDown = 1u << 0,
    kFloat64RoundDown = 1u << 1,
    kFloat32RoundUp = 1u << 2,
    kFloat64RoundUp = 1u << 3,
    kFloat32RoundTruncate = 1u << 4,
    kFloat64RoundTruncate = 1u << 5,
    kFloat32RoundTiesEven = 1u << 6,
    kFloat64RoundTiesEven = 1u << 7,
    kFloat64RoundTiesAway = 1u << 8,
    kInt32DivIsSafe = 1u << 9,
    kUint32DivIsSafe = 1u << 10,
    kWord32ShiftIsSafe = 1u << 11,
    kWord32Ctz = 1u << 12,
    kWord64Ctz = 1u << 13,
    kWord64CtzLowerable = 1u << 14,
    kWord32Popcnt = 1u << 15,
    kWord64Popcnt = 1u << 16,
    kWord32ReverseBits = 1u << 17,
    kWord64ReverseBits = 1u << 18,
    kFloat32Select = 1u << 19,
    kFloat64Select = 1u << 20,
    kInt32AbsWithOverflow = 1u << 21,
    kInt64AbsWithOverflow = 1u << 22,
    kWord32Rol = 1u << 23,
    kWord64Rol = 1u << 24,
    kWord64RolLowerable = 1u << 25,
    kSatConversionIsSafe = 1u << 26,
    kWord32Select = 1u << 27,
    kWord64Select = 1u << 28,
    kLoadStorePairs = 1u << 29,
    kFloat16 = 1u << 30,
    kFloat16RawBitsConversion = 1u << 31,
    kAllOptionalOps =
        kFloat32RoundDown | kFloat64RoundDown | kFloat32RoundUp |
        kFloat64RoundUp | kFloat32RoundTruncate | kFloat64RoundTruncate |
        kFloat64RoundTiesAway | kFloat32RoundTiesEven | kFloat64RoundTiesEven |
        kWord32Ctz | kWord64Ctz | kWord64CtzLowerable | kWord32Popcnt |
        kWord64Popcnt | kWord32ReverseBits | kWord64ReverseBits |
        kInt32AbsWithOverflow | kInt64AbsWithOverflow | kWord32Rol |
        kWord64Rol | kWord64RolLowerable | kSatConversionIsSafe |
        kFloat32Select | kFloat64Select | kWord32Select | kWord64Select |
        kLoadStorePairs | kFloat16 | kFloat16RawBitsConversion
  };
Constructor & Destructor Documentation
MachineOperatorBuilder() [1/2]
v8::internal::compiler::MachineOperatorBuilder::MachineOperatorBuilder (Zone * zone, MachineRepresentation word = MachineType::PointerRepresentation(), Flags supportedOperators = kNoFlags, AlignmentRequirements alignmentRequirements = AlignmentRequirements::FullUnalignedAccessSupport()) [explicit]
Definition at line 1839 of file machine-operator.cc.
    : zone_(zone),
      cache_(*GetMachineOperatorGlobalCache()),
      word_(word),
      flags_(flags),
      alignment_requirements_(alignmentRequirements) {
  DCHECK(word == MachineRepresentation::kWord32 ||
         word == MachineRepresentation::kWord64);
}
References v8::internal::DCHECK(), v8::internal::kWord32, v8::internal::kWord64, and word().
MachineOperatorBuilder() [2/2]
v8::internal::compiler::MachineOperatorBuilder::MachineOperatorBuilder (const MachineOperatorBuilder &) [delete]
Member Function Documentation
AbortCSADcheck()
const Operator * v8::internal::compiler::MachineOperatorBuilder::AbortCSADcheck ()
Definition at line 2259 of file machine-operator.cc.
                                                       {
  return &cache_.kAbortCSADcheck;
}
References cache_, and v8::internal::compiler::MachineOperatorGlobalCache::kAbortCSADcheck.
BitcastFloat32ToInt32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::BitcastFloat32ToInt32 ()
BitcastFloat64ToInt64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::BitcastFloat64ToInt64 ()
BitcastInt32ToFloat32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::BitcastInt32ToFloat32 ()
BitcastInt64ToFloat64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::BitcastInt64ToFloat64 ()
BitcastMaybeObjectToWord()
const Operator * v8::internal::compiler::MachineOperatorBuilder::BitcastMaybeObjectToWord ()
Definition at line 2255 of file machine-operator.cc.
                                                                 {
  return &cache_.kBitcastMaybeObjectToWord;
}
References cache_, and v8::internal::compiler::MachineOperatorGlobalCache::kBitcastMaybeObjectToWord.
BitcastTaggedToWord()
const Operator * v8::internal::compiler::MachineOperatorBuilder::BitcastTaggedToWord ()
Definition at line 2251 of file machine-operator.cc.
                                                            {
  return &cache_.kBitcastTaggedToWord;
}
References cache_, and v8::internal::compiler::MachineOperatorGlobalCache::kBitcastTaggedToWord.
BitcastTaggedToWordForTagAndSmiBits()
const Operator* v8::internal::compiler::MachineOperatorBuilder::BitcastTaggedToWordForTagAndSmiBits ()
BitcastWord32ToWord64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::BitcastWord32ToWord64 ()
BitcastWordToTagged()
const Operator * v8::internal::compiler::MachineOperatorBuilder::BitcastWordToTagged ()
Definition at line 2247 of file machine-operator.cc.
                                                            {
  return &cache_.kBitcastWordToTagged;
}
References cache_, and v8::internal::compiler::MachineOperatorGlobalCache::kBitcastWordToTagged.
BitcastWordToTaggedSigned()
const Operator* v8::internal::compiler::MachineOperatorBuilder::BitcastWordToTaggedSigned ()
ChangeFloat16RawBitsToFloat64()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::ChangeFloat16RawBitsToFloat64 ()
Definition at line 1948 of file machine-operator.cc.
                                                                             {
  return OptionalOperator(flags_ & kFloat16RawBitsConversion,
                          &cache_.kChangeFloat16RawBitsToFloat64);
}
References cache_, flags_, v8::internal::compiler::MachineOperatorGlobalCache::kChangeFloat16RawBitsToFloat64, and kFloat16RawBitsConversion.
ChangeFloat32ToFloat64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::ChangeFloat32ToFloat64 ()
Referenced by v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor().
ChangeFloat64ToInt32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::ChangeFloat64ToInt32 ()
Referenced by v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor().
ChangeFloat64ToInt64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::ChangeFloat64ToInt64 ()
Referenced by v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor().
ChangeFloat64ToUint32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::ChangeFloat64ToUint32 ()
Referenced by v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor().
ChangeFloat64ToUint64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::ChangeFloat64ToUint64 ()
Referenced by v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor().
ChangeInt32ToFloat64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::ChangeInt32ToFloat64 ()
Referenced by v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor(), and v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor().
ChangeInt32ToInt64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::ChangeInt32ToInt64 ()
Referenced by v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::CheckSubsumes(), and v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor().
ChangeInt64ToFloat64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::ChangeInt64ToFloat64 ()
Referenced by v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), and v8::internal::compiler::RepresentationChanger::GetTaggedPointerRepresentationFor().
ChangeUint32ToFloat64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::ChangeUint32ToFloat64 ()
Referenced by v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor(), and v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor().
ChangeUint32ToUint64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::ChangeUint32ToUint64 ()
Referenced by v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), and v8::internal::compiler::RepresentationSelector::VisitCheckBounds().
Comment()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Comment (const char * msg)
Definition at line 2267 of file machine-operator.cc.
                                                               {
  return zone_->New<CommentOperator>(msg);
}
References v8::internal::Zone::New(), and zone_.
DebugBreak()
const Operator * v8::internal::compiler::MachineOperatorBuilder::DebugBreak ()
Definition at line 2263 of file machine-operator.cc.
                                                   {
  return &cache_.kDebugBreak;
}
References cache_, and v8::internal::compiler::MachineOperatorGlobalCache::kDebugBreak.
Float32Abs()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float32Abs ()
Float32Add()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float32Add ()
Float32Div()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float32Div ()
Float32Equal()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float32Equal ()
Float32LessThan()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float32LessThan ()
Float32LessThanOrEqual()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float32LessThanOrEqual ()
Float32Max()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float32Max ()
Float32Min()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float32Min ()
Float32Mul()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float32Mul ()
Float32Neg()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float32Neg ()
Float32RoundDown()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Float32RoundDown ()
Float32RoundTiesEven()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Float32RoundTiesEven ()
Float32RoundTruncate()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Float32RoundTruncate ()
Float32RoundUp()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Float32RoundUp ()
Float32Select()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Float32Select ()
Float32Sqrt()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float32Sqrt ()
Float32Sub()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float32Sub ()
Float64Abs()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Abs ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Acos()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Acos ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Acosh()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Acosh ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Add()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Add ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Asin()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Asin ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Asinh()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Asinh ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Atan()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Atan ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Atan2()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Atan2 ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Atanh()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Atanh ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Cbrt()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Cbrt ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Cos()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Cos ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Cosh()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Cosh ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Div()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Div ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Equal()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Equal ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Exp()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Exp ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Expm1()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Expm1 ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64ExtractHighWord32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64ExtractHighWord32 ()
Float64ExtractLowWord32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64ExtractLowWord32 ()
Float64InsertHighWord32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64InsertHighWord32 ()
Float64InsertLowWord32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64InsertLowWord32 ()
Float64LessThan()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64LessThan ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Float64LessThanOrEqual()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64LessThanOrEqual ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Float64Log()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Log ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Log10()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Log10 ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Log1p()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Log1p ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Log2()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Log2 ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Max()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Max ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Min()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Min ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Mod()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Mod ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Mul()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Mul ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Neg()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Neg ()
Float64Pow()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Pow ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64RoundDown()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Float64RoundDown ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor(), and v8::internal::compiler::CodeAssembler::IsFloat64RoundDownSupported().
Float64RoundTiesAway()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Float64RoundTiesAway ()
Float64RoundTiesEven()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Float64RoundTiesEven ()
Referenced by v8::internal::compiler::CodeAssembler::IsFloat64RoundTiesEvenSupported().
Float64RoundTruncate()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Float64RoundTruncate ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor(), and v8::internal::compiler::CodeAssembler::IsFloat64RoundTruncateSupported().
Float64RoundUp()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Float64RoundUp ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor(), and v8::internal::compiler::CodeAssembler::IsFloat64RoundUpSupported().
Float64Select()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Float64Select ()
Float64SilenceNaN()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64SilenceNaN ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Sin()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Sin ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Sinh()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Sinh ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Sqrt()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Sqrt ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Sub()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Sub ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Tan()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Tan ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
Float64Tanh()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Float64Tanh ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor().
I8x16BitMask()
const Operator* v8::internal::compiler::MachineOperatorBuilder::I8x16BitMask ()
I8x16Eq()
const Operator* v8::internal::compiler::MachineOperatorBuilder::I8x16Eq ()
I8x16Splat()
const Operator* v8::internal::compiler::MachineOperatorBuilder::I8x16Splat ()
Int32AbsWithOverflow()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Int32AbsWithOverflow ()
Referenced by v8::internal::compiler::CodeAssembler::IsInt32AbsWithOverflowSupported().
Int32Add()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32Add ()
Referenced by v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::RepresentationChanger::Int32OperatorFor(), v8::internal::compiler::Word32Adapter::IntNAdd(), and v8::internal::compiler::RepresentationChanger::Uint32OperatorFor().
Int32AddWithOverflow()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32AddWithOverflow ()
Int32Div()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32Div ()
Referenced by v8::internal::compiler::RepresentationChanger::Int32OperatorFor().
Int32DivIsSafe()
bool v8::internal::compiler::MachineOperatorBuilder::Int32DivIsSafe () const [inline]
Definition at line 594 of file machine-operator.h.
{ return flags_ & kInt32DivIsSafe; }
Int32LessThan()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32LessThan ()
Referenced by v8::internal::compiler::RepresentationChanger::Int32OperatorFor(), v8::internal::compiler::MachineOperatorReducer::Map64To32Comparison(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons(), v8::internal::compiler::RepresentationChanger::TaggedSignedOperatorFor(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Int32LessThanOrEqual()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32LessThanOrEqual ()
Referenced by v8::internal::compiler::RepresentationChanger::Int32OperatorFor(), v8::internal::compiler::MachineOperatorReducer::Map64To32Comparison(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons(), and v8::internal::compiler::RepresentationChanger::TaggedSignedOperatorFor().
Int32Mod()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32Mod ()
Referenced by v8::internal::compiler::RepresentationChanger::Int32OperatorFor().
Int32Mul()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32Mul ()
Referenced by v8::internal::compiler::RepresentationChanger::Int32OperatorFor(), and v8::internal::compiler::RepresentationChanger::Uint32OperatorFor().
Int32MulHigh()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32MulHigh ()
Int32MulWithOverflow()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32MulWithOverflow ()
Int32PairAdd()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32PairAdd ()
Int32PairMul()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32PairMul ()
Int32PairSub()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32PairSub ()
Int32Sub()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32Sub ()
Referenced by v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::RepresentationChanger::Int32OperatorFor(), and v8::internal::compiler::RepresentationChanger::Uint32OperatorFor().
Int32SubWithOverflow()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int32SubWithOverflow ()
Int64AbsWithOverflow()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Int64AbsWithOverflow ()
Referenced by v8::internal::compiler::CodeAssembler::IsInt64AbsWithOverflowSupported().
Int64Add()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int64Add ()
Referenced by v8::internal::compiler::RepresentationChanger::Int64OperatorFor(), v8::internal::compiler::Word64Adapter::IntNAdd(), and v8::internal::compiler::Revectorizer::VectorizeTree().
Int64AddWithOverflow()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int64AddWithOverflow ()
Int64Div()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int64Div ()
Int64LessThan()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int64LessThan ()
Referenced by v8::internal::compiler::RepresentationChanger::Int64OperatorFor(), v8::internal::compiler::RepresentationChanger::TaggedSignedOperatorFor(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Int64LessThanOrEqual()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int64LessThanOrEqual ()
Referenced by v8::internal::compiler::RepresentationChanger::Int64OperatorFor(), and v8::internal::compiler::RepresentationChanger::TaggedSignedOperatorFor().
Int64Mod()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int64Mod ()
Int64Mul()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int64Mul ()
Referenced by v8::internal::compiler::RepresentationChanger::Int64OperatorFor().
Int64MulHigh()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int64MulHigh ()
Int64MulWithOverflow()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int64MulWithOverflow ()
Int64Sub()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int64Sub ()
Referenced by v8::internal::compiler::RepresentationChanger::Int64OperatorFor(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Int64SubWithOverflow()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Int64SubWithOverflow ()
Is32()
bool v8::internal::compiler::MachineOperatorBuilder::Is32 () const [inline]
Definition at line 1353 of file machine-operator.h.
{ return word() == MachineRepresentation::kWord32; }
References v8::internal::kWord32.
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildChangeIntPtrToInt64(), v8::internal::compiler::CompileWasmJSFastCallWrapper(), v8::internal::compiler::MachineGraph::IntPtrConstant(), v8::internal::compiler::CodeAssembler::Is32(), v8::internal::compiler::MachineGraph::UintPtrConstant(), and v8::internal::compiler::MachineGraph::UniqueIntPtrConstant().
Is64()
bool v8::internal::compiler::MachineOperatorBuilder::Is64 () const [inline]
Definition at line 1354 of file machine-operator.h.
{ return word() == MachineRepresentation::kWord64; }
References v8::internal::kWord64.
Referenced by v8::internal::compiler::WasmGraphAssembler::BuildChangeInt32ToIntPtr(), v8::internal::compiler::WasmGraphAssembler::BuildTruncateIntPtrToInt32(), v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::CheckSubsumes(), v8::internal::compiler::CodeAssembler::Is64(), v8::internal::compiler::WasmGCLowering::ReduceWasmAnyConvertExtern(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), v8::internal::compiler::RepresentationSelector::VisitNode(), and v8::internal::compiler::WasmGraphAssembler::WasmArrayElementOffset().
Load()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Load (LoadRepresentation rep)
Definition at line 1964 of file machine-operator.cc.
                                                                   {
  DCHECK(!rep.IsMapWord());
#define LOAD(Type) \
  if (rep == MachineType::Type()) { \
    return &cache_.kLoad##Type; \
  }
  MACHINE_TYPE_LIST(LOAD)
#undef LOAD
  UNREACHABLE();
}
References v8::internal::DCHECK(), v8::internal::MachineType::IsMapWord(), v8::internal::LOAD, MACHINE_TYPE_LIST, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::WasmGraphBuilder::GetSafeLoadOperator(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::GraphAssembler::LoadUnaligned(), v8::internal::compiler::MemoryLowering::ReduceLoadBoundedSize(), v8::internal::compiler::MemoryLowering::ReduceLoadFromObject(), and v8::internal::compiler::Revectorizer::VectorizeTree().
LoadFramePointer()
const Operator* v8::internal::compiler::MachineOperatorBuilder::LoadFramePointer ()
LoadImmutable()
const Operator * v8::internal::compiler::MachineOperatorBuilder::LoadImmutable (LoadRepresentation rep)
Definition at line 1981 of file machine-operator.cc.
                                                                            {
#define LOAD(Type) \
  if (rep == MachineType::Type()) { \
    return &cache_.kLoadImmutable##Type; \
  }
  MACHINE_TYPE_LIST(LOAD)
#undef LOAD
  UNREACHABLE();
}
References v8::internal::LOAD, MACHINE_TYPE_LIST, and v8::internal::UNREACHABLE().
LoadParentFramePointer()
const Operator* v8::internal::compiler::MachineOperatorBuilder::LoadParentFramePointer ()
LoadRootRegister()
const Operator* v8::internal::compiler::MachineOperatorBuilder::LoadRootRegister ()
LoadStackCheckOffset()
const Operator* v8::internal::compiler::MachineOperatorBuilder::LoadStackCheckOffset ()
LoadTrapOnNull()
const Operator * v8::internal::compiler::MachineOperatorBuilder::LoadTrapOnNull (LoadRepresentation rep)
Definition at line 2001 of file machine-operator.cc.
                                                                             {
#define LOAD(Type) \
  if (rep == MachineType::Type()) { \
    return &cache_.kLoadTrapOnNull##Type; \
  }
  MACHINE_TYPE_LIST(LOAD)
#undef LOAD
  UNREACHABLE();
}
References v8::internal::LOAD, MACHINE_TYPE_LIST, and v8::internal::UNREACHABLE().
MemoryBarrier()
const Operator * v8::internal::compiler::MachineOperatorBuilder::MemoryBarrier (AtomicMemoryOrder order)
Definition at line 2271 of file machine-operator.cc.
                                                                             {
  switch (order) {
    case AtomicMemoryOrder::kSeqCst:
      return &cache_.kSeqCstMemoryBarrier;
    case AtomicMemoryOrder::kAcqRel:
      return &cache_.kAcqRelMemoryBarrier;
    default:
      UNREACHABLE();
  }
}
References cache_, v8::internal::kAcqRel, v8::internal::compiler::MachineOperatorGlobalCache::kAcqRelMemoryBarrier, v8::internal::kSeqCst, v8::internal::compiler::MachineOperatorGlobalCache::kSeqCstMemoryBarrier, and v8::internal::UNREACHABLE().
operator=()
MachineOperatorBuilder& v8::internal::compiler::MachineOperatorBuilder::operator= (const MachineOperatorBuilder &) [delete]
ProtectedLoad()
const Operator * v8::internal::compiler::MachineOperatorBuilder::ProtectedLoad (LoadRepresentation rep)
Definition at line 1991 of file machine-operator.cc.
                                                                            {
#define LOAD(Type) \
  if (rep == MachineType::Type()) { \
    return &cache_.kProtectedLoad##Type; \
  }
  MACHINE_TYPE_LIST(LOAD)
#undef LOAD
  UNREACHABLE();
}
References v8::internal::LOAD, MACHINE_TYPE_LIST, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::Revectorizer::VectorizeTree().
ProtectedStore()
const Operator * v8::internal::compiler::MachineOperatorBuilder::ProtectedStore (MachineRepresentation rep)
Definition at line 2194 of file machine-operator.cc.
                               {
  switch (rep) {
#define STORE(kRep) \
  case MachineRepresentation::kRep: \
    return &cache_.kProtectedStore##kRep;
    MACHINE_REPRESENTATION_LIST(STORE)
#undef STORE
    case MachineRepresentation::kBit:
    case MachineRepresentation::kProtectedPointer:
    case MachineRepresentation::kIndirectPointer:
    case MachineRepresentation::kNone:
    case MachineRepresentation::kFloat16RawBits:
      UNREACHABLE();
  }
}
References v8::internal::kBit, v8::internal::kFloat16RawBits, v8::internal::kIndirectPointer, v8::internal::kNone, v8::internal::kProtectedPointer, MACHINE_REPRESENTATION_LIST, v8::internal::STORE, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::Revectorizer::VectorizeTree().
RoundFloat64ToInt32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::RoundFloat64ToInt32 ()
RoundInt32ToFloat32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::RoundInt32ToFloat32 ()
RoundInt64ToFloat32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::RoundInt64ToFloat32 ()
RoundInt64ToFloat64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::RoundInt64ToFloat64 ()
RoundUint32ToFloat32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::RoundUint32ToFloat32 ()
RoundUint64ToFloat32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::RoundUint64ToFloat32 ()
RoundUint64ToFloat64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::RoundUint64ToFloat64 ()
SatConversionIsSafe()
bool v8::internal::compiler::MachineOperatorBuilder::SatConversionIsSafe () const [inline]
Definition at line 535 of file machine-operator.h.
{ return flags_ & kSatConversionIsSafe; }
SignExtendWord16ToInt32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::SignExtendWord16ToInt32 ()
SignExtendWord16ToInt64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::SignExtendWord16ToInt64 ()
SignExtendWord32ToInt64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::SignExtendWord32ToInt64 ()
SignExtendWord8ToInt32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::SignExtendWord8ToInt32 ()
SignExtendWord8ToInt64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::SignExtendWord8ToInt64 ()
Simd128ReverseBytes()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Simd128ReverseBytes ()
StackPointerGreaterThan()
const Operator * v8::internal::compiler::MachineOperatorBuilder::StackPointerGreaterThan (StackCheckKind kind)
Definition at line 2232 of file machine-operator.cc.
                         {
  switch (kind) {
    case StackCheckKind::kJSFunctionEntry:
      return &cache_.kStackPointerGreaterThanJSFunctionEntry;
    case StackCheckKind::kCodeStubAssembler:
      return &cache_.kStackPointerGreaterThanCodeStubAssembler;
    case StackCheckKind::kWasm:
      return &cache_.kStackPointerGreaterThanWasm;
    case StackCheckKind::kJSIterationBody:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References cache_, v8::internal::compiler::kCodeStubAssembler, v8::internal::compiler::kJSFunctionEntry, v8::internal::compiler::kJSIterationBody, v8::internal::compiler::kWasm, and v8::internal::UNREACHABLE().
StackSlot() [1/2]
const Operator * v8::internal::compiler::MachineOperatorBuilder::StackSlot (int size, int alignment = 0, bool is_tagged = false)
Definition at line 2107 of file machine-operator.cc.
                                                                  {
  DCHECK_LE(0, size);
  DCHECK(alignment == 0 || alignment == 4 || alignment == 8 || alignment == 16);
#define CASE_CACHED_SIZE(Size, Alignment, IsTagged) \
  if (size == Size && alignment == Alignment && is_tagged == IsTagged) { \
    return &cache_.kStackSlotOfSize##Size##OfAlignment##Alignment##IsTagged; \
  }
  STACK_SLOT_CACHED_SIZES_ALIGNMENTS_LIST(CASE_CACHED_SIZE)
#undef CASE_CACHED_SIZE
  return zone_->New<StackSlotOperator>(size, alignment, is_tagged);
}
References CASE_CACHED_SIZE, v8::internal::DCHECK(), DCHECK_LE, v8::internal::Zone::New(), size(), STACK_SLOT_CACHED_SIZES_ALIGNMENTS_LIST, and zone_.
Referenced by StackSlot().
StackSlot() [2/2]
const Operator * v8::internal::compiler::MachineOperatorBuilder::StackSlot (MachineRepresentation rep, int alignment = 0)
Definition at line 2122 of file machine-operator.cc.
                                                                 {
  return StackSlot(1 << ElementSizeLog2Of(rep), alignment);
}
References v8::internal::ElementSizeLog2Of(), and StackSlot().
Store()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Store (StoreRepresentation rep)
Definition at line 2127 of file machine-operator.cc.
                                                                           {
  DCHECK_NE(store_rep.representation(), MachineRepresentation::kMapWord);
  DCHECK_NE(store_rep.representation(),
            MachineRepresentation::kIndirectPointer);
  switch (store_rep.representation()) {
#define STORE(kRep) \
  case MachineRepresentation::kRep: \
    switch (store_rep.write_barrier_kind()) { \
      case kNoWriteBarrier: \
        return &cache_.k##Store##kRep##NoWriteBarrier; \
      case kAssertNoWriteBarrier: \
        return &cache_.k##Store##kRep##AssertNoWriteBarrier; \
      case kMapWriteBarrier: \
        return &cache_.k##Store##kRep##MapWriteBarrier; \
      case kPointerWriteBarrier: \
        return &cache_.k##Store##kRep##PointerWriteBarrier; \
      case kIndirectPointerWriteBarrier: \
        UNREACHABLE(); \
      case kEphemeronKeyWriteBarrier: \
        return &cache_.k##Store##kRep##EphemeronKeyWriteBarrier; \
      case kFullWriteBarrier: \
        return &cache_.k##Store##kRep##FullWriteBarrier; \
    } \
    break;
    MACHINE_REPRESENTATION_LIST(STORE)
#undef STORE
    case MachineRepresentation::kBit:
    case MachineRepresentation::kProtectedPointer:
    case MachineRepresentation::kIndirectPointer:
    case MachineRepresentation::kNone:
    case MachineRepresentation::kFloat16RawBits:
      UNREACHABLE();
  }
}
References DCHECK_NE, v8::internal::kBit, v8::internal::kFloat16RawBits, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, MACHINE_REPRESENTATION_LIST, v8::internal::compiler::StoreRepresentation::representation(), v8::internal::STORE, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::MemoryLowering::ReduceStoreToObject(), v8::internal::compiler::GraphAssembler::StoreUnaligned(), and v8::internal::compiler::Revectorizer::VectorizeTree().
StoreIndirectPointer()
const Operator * v8::internal::compiler::MachineOperatorBuilder::StoreIndirectPointer (WriteBarrierKind write_barrier_kind)
Definition at line 2162 of file machine-operator.cc.
                                         {
  switch (write_barrier_kind) {
    case kNoWriteBarrier:
      return &cache_.kStoreIndirectPointerNoWriteBarrier;
    case kIndirectPointerWriteBarrier:
      return &cache_.kStoreIndirectPointerIndirectPointerWriteBarrier;
    default:
      UNREACHABLE();
  }
}
References cache_, v8::internal::compiler::kIndirectPointerWriteBarrier, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::MachineOperatorGlobalCache::kStoreIndirectPointerIndirectPointerWriteBarrier, v8::internal::compiler::MachineOperatorGlobalCache::kStoreIndirectPointerNoWriteBarrier, and v8::internal::UNREACHABLE().
StoreTrapOnNull()
const Operator * v8::internal::compiler::MachineOperatorBuilder::StoreTrapOnNull (StoreRepresentation rep)
Definition at line 2211 of file machine-operator.cc.
                             {
  switch (rep.representation()) {
#define STORE(kRep) \
  case MachineRepresentation::kRep: \
    if (rep.write_barrier_kind() == kNoWriteBarrier) { \
      return &cache_.kStoreTrapOnNull##kRep##NoWriteBarrier; \
    } \
    DCHECK_EQ(kFullWriteBarrier, rep.write_barrier_kind()); \
    return &cache_.kStoreTrapOnNull##kRep##FullWriteBarrier;
    MACHINE_REPRESENTATION_LIST(STORE)
#undef STORE
    case MachineRepresentation::kBit:
    case MachineRepresentation::kProtectedPointer:
    case MachineRepresentation::kIndirectPointer:
    case MachineRepresentation::kNone:
    case MachineRepresentation::kFloat16RawBits:
      UNREACHABLE();
  }
}
References v8::internal::kBit, v8::internal::kFloat16RawBits, v8::internal::kIndirectPointer, v8::internal::kNone, v8::internal::kProtectedPointer, MACHINE_REPRESENTATION_LIST, v8::internal::compiler::StoreRepresentation::representation(), v8::internal::STORE, and v8::internal::UNREACHABLE().
SupportsLoadStorePairs()
bool v8::internal::compiler::MachineOperatorBuilder::SupportsLoadStorePairs () const [inline]
Definition at line 539 of file machine-operator.h.
                                      {
    return !v8_flags.enable_unconditional_write_barriers &&
           (flags_ & kLoadStorePairs);
  }
References v8::internal::v8_flags.
TaggedEqual()
const Operator* v8::internal::compiler::MachineOperatorBuilder::TaggedEqual () [inline]
Definition at line 1401 of file machine-operator.h.
                                {
    return COMPRESS_POINTERS_BOOL ? Word32Equal() : WordEqual();
  }
References COMPRESS_POINTERS_BOOL, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
TraceInstruction()
const Operator * v8::internal::compiler::MachineOperatorBuilder::TraceInstruction (uint32_t markid)
Definition at line 1958 of file machine-operator.cc.
                                                                        {
  return zone_->New<Operator1<uint32_t>>(
      IrOpcode::kTraceInstruction, Operator::kNoDeopt | Operator::kNoThrow,
      "TraceInstruction", 0, 1, 1, 0, 1, 0, markid);
}
References v8::internal::compiler::Operator::kNoDeopt, v8::internal::compiler::Operator::kNoThrow, v8::internal::Zone::New(), and zone_.
TruncateFloat32ToInt32()
const Operator * v8::internal::compiler::MachineOperatorBuilder::TruncateFloat32ToInt32 (TruncateKind kind)
Definition at line 1922 of file machine-operator.cc.
                       {
  switch (kind) {
    case TruncateKind::kArchitectureDefault:
      return &cache_.kArchitectureDefaultTruncateFloat32ToInt32;
    case TruncateKind::kSetOverflowToMin:
      return &cache_.kSetOverflowToMinTruncateFloat32ToInt32;
  }
}
References cache_, v8::internal::compiler::kArchitectureDefault, v8::internal::compiler::MachineOperatorGlobalCache::kArchitectureDefaultTruncateFloat32ToInt32, v8::internal::compiler::kSetOverflowToMin, and v8::internal::compiler::MachineOperatorGlobalCache::kSetOverflowToMinTruncateFloat32ToInt32.
TruncateFloat32ToUint32()
const Operator * v8::internal::compiler::MachineOperatorBuilder::TruncateFloat32ToUint32 (TruncateKind kind)
Definition at line 1902 of file machine-operator.cc.
                       {
  switch (kind) {
    case TruncateKind::kArchitectureDefault:
      return &cache_.kArchitectureDefaultTruncateFloat32ToUint32;
    case TruncateKind::kSetOverflowToMin:
      return &cache_.kSetOverflowToMinTruncateFloat32ToUint32;
  }
}
References cache_, v8::internal::compiler::kArchitectureDefault, v8::internal::compiler::MachineOperatorGlobalCache::kArchitectureDefaultTruncateFloat32ToUint32, v8::internal::compiler::kSetOverflowToMin, and v8::internal::compiler::MachineOperatorGlobalCache::kSetOverflowToMinTruncateFloat32ToUint32.
TruncateFloat64ToFloat16RawBits()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::TruncateFloat64ToFloat16RawBits ()
Definition at line 1944 of file machine-operator.cc.
                                                        {
  return OptionalOperator(flags_ & kFloat16RawBitsConversion,
                          &cache_.kTruncateFloat64ToFloat16RawBits);
}
References cache_, flags_, kFloat16RawBitsConversion, and v8::internal::compiler::MachineOperatorGlobalCache::kTruncateFloat64ToFloat16RawBits.
Referenced by v8::internal::compiler::CodeAssembler::IsTruncateFloat64ToFloat16RawBitsSupported().
TruncateFloat64ToFloat32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::TruncateFloat64ToFloat32 ()
Referenced by v8::internal::compiler::RepresentationChanger::Float64OperatorFor(), and v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor().
TruncateFloat64ToInt64()
const Operator * v8::internal::compiler::MachineOperatorBuilder::TruncateFloat64ToInt64 (TruncateKind kind)
Definition at line 1912 of file machine-operator.cc.
                       {
  switch (kind) {
    case TruncateKind::kArchitectureDefault:
      return &cache_.kArchitectureDefaultTruncateFloat64ToInt64;
    case TruncateKind::kSetOverflowToMin:
      return &cache_.kSetOverflowToMinTruncateFloat64ToInt64;
  }
}
References cache_, v8::internal::compiler::kArchitectureDefault, v8::internal::compiler::MachineOperatorGlobalCache::kArchitectureDefaultTruncateFloat64ToInt64, v8::internal::compiler::kSetOverflowToMin, and v8::internal::compiler::MachineOperatorGlobalCache::kSetOverflowToMinTruncateFloat64ToInt64.
TruncateFloat64ToUint32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::TruncateFloat64ToUint32 ()
TruncateFloat64ToWord32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::TruncateFloat64ToWord32 ()
Referenced by v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor().
TruncateInt64ToInt32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::TruncateInt64ToInt32 ()
Referenced by v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor().
TryStorePair()
std::optional< const Operator * > v8::internal::compiler::MachineOperatorBuilder::TryStorePair (StoreRepresentation rep1, StoreRepresentation rep2)
Definition at line 2174 of file machine-operator.cc.
                                                                    {
  DCHECK_NE(store_rep1.representation(), MachineRepresentation::kMapWord);
#define STORE(kRep1, kRep2) \
  static_assert(ElementSizeLog2Of(MachineRepresentation::kRep1) == \
                ElementSizeLog2Of(MachineRepresentation::kRep2)); \
  if (MachineRepresentation::kRep1 == store_rep1.representation() && \
      MachineRepresentation::kRep2 == store_rep2.representation()) { \
    if (store_rep1.write_barrier_kind() != kNoWriteBarrier || \
        store_rep2.write_barrier_kind() != kNoWriteBarrier) { \
      return {}; \
    } \
    return &cache_.k##StorePair##kRep1##kRep2##NoWriteBarrier; \
  }
  STORE_PAIR_MACHINE_REPRESENTATION_LIST(STORE);
#undef STORE
  return {};
}
References DCHECK_NE, v8::internal::kMapWord, v8::internal::compiler::StoreRepresentation::representation(), v8::internal::STORE, and STORE_PAIR_MACHINE_REPRESENTATION_LIST.
Referenced by v8::internal::compiler::anonymous_namespace{pair-load-store-reducer.cc}::CanBePaired().
TryTruncateFloat32ToInt64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::TryTruncateFloat32ToInt64 ()
TryTruncateFloat32ToUint64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::TryTruncateFloat32ToUint64 ()
TryTruncateFloat64ToInt32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::TryTruncateFloat64ToInt32 ()
TryTruncateFloat64ToInt64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::TryTruncateFloat64ToInt64 ()
TryTruncateFloat64ToUint32()
const Operator* v8::internal::compiler::MachineOperatorBuilder::TryTruncateFloat64ToUint32 ()
TryTruncateFloat64ToUint64()
const Operator* v8::internal::compiler::MachineOperatorBuilder::TryTruncateFloat64ToUint64 ()
Uint32Div()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Uint32Div ()
Referenced by v8::internal::compiler::RepresentationChanger::Uint32OperatorFor().
Uint32DivIsSafe()
bool v8::internal::compiler::MachineOperatorBuilder::Uint32DivIsSafe () const [inline]
Definition at line 595 of file machine-operator.h.
{ return flags_ & kUint32DivIsSafe; }
Uint32LessThan()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Uint32LessThan ()
Referenced by v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::MachineOperatorReducer::Map64To32Comparison(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons(), v8::internal::compiler::RepresentationChanger::Uint32OperatorFor(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Uint32LessThanOrEqual()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Uint32LessThanOrEqual ()
Referenced by v8::internal::compiler::MachineOperatorReducer::Map64To32Comparison(), v8::internal::compiler::MachineOperatorReducer::ReduceWord64Comparisons(), and v8::internal::compiler::RepresentationChanger::Uint32OperatorFor().
Uint32Mod()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Uint32Mod ()
Referenced by v8::internal::compiler::RepresentationChanger::Uint32OperatorFor().
Uint32MulHigh()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Uint32MulHigh ()
Uint64Div()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Uint64Div ()
Uint64LessThan()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Uint64LessThan ()
Uint64LessThanOrEqual()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Uint64LessThanOrEqual ()
Uint64Mod()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Uint64Mod ()
Uint64MulHigh()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Uint64MulHigh ()
UnalignedLoad()
const Operator * v8::internal::compiler::MachineOperatorBuilder::UnalignedLoad (LoadRepresentation rep)
Definition at line 1851 of file machine-operator.cc.
                                                                            {
#define LOAD(Type) \
  if (rep == MachineType::Type()) { \
    return &cache_.kUnalignedLoad##Type; \
  }
  MACHINE_TYPE_LIST(LOAD)
#undef LOAD
  UNREACHABLE();
}
References v8::internal::LOAD, MACHINE_TYPE_LIST, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::WasmGraphBuilder::GetSafeLoadOperator(), v8::internal::compiler::GraphAssembler::LoadUnaligned(), v8::internal::compiler::MemoryLowering::ReduceLoadBoundedSize(), and v8::internal::compiler::MemoryLowering::ReduceLoadFromObject().
UnalignedLoadSupported()
bool v8::internal::compiler::MachineOperatorBuilder::UnalignedLoadSupported (MachineRepresentation rep) [inline]
Definition at line 1357 of file machine-operator.h.
                                                         {
    return alignment_requirements_.IsUnalignedLoadSupported(rep);
  }
Referenced by v8::internal::compiler::GraphAssembler::LoadUnaligned(), v8::internal::compiler::MemoryLowering::ReduceLoadBoundedSize(), v8::internal::compiler::MemoryLowering::ReduceLoadFromObject(), and v8::internal::compiler::CodeAssembler::UnalignedLoadSupported().
UnalignedStore()
const Operator * v8::internal::compiler::MachineOperatorBuilder::UnalignedStore (UnalignedStoreRepresentation rep)
Definition at line 1861 of file machine-operator.cc.
                                      {
  switch (rep) {
#define STORE(kRep) \
  case MachineRepresentation::kRep: \
    return &cache_.kUnalignedStore##kRep;
    MACHINE_REPRESENTATION_LIST(STORE)
#undef STORE
    case MachineRepresentation::kBit:
    case MachineRepresentation::kProtectedPointer:
    case MachineRepresentation::kIndirectPointer:
    case MachineRepresentation::kNone:
    case MachineRepresentation::kFloat16RawBits:
      UNREACHABLE();
  }
}
References v8::internal::kBit, v8::internal::kFloat16RawBits, v8::internal::kIndirectPointer, v8::internal::kNone, v8::internal::kProtectedPointer, MACHINE_REPRESENTATION_LIST, v8::internal::STORE, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::MemoryLowering::ReduceStoreToObject(), and v8::internal::compiler::GraphAssembler::StoreUnaligned().
UnalignedStoreSupported()
bool v8::internal::compiler::MachineOperatorBuilder::UnalignedStoreSupported (MachineRepresentation rep) [inline]
Definition at line 1361 of file machine-operator.h.
                                                          {
    return alignment_requirements_.IsUnalignedStoreSupported(rep);
  }
Referenced by v8::internal::compiler::MemoryLowering::ReduceStoreToObject(), v8::internal::compiler::GraphAssembler::StoreUnaligned(), and v8::internal::compiler::CodeAssembler::UnalignedStoreSupported().
word()
MachineRepresentation v8::internal::compiler::MachineOperatorBuilder::word () const [inline]
Definition at line 1355 of file machine-operator.h.
{ return word_; }
Referenced by MachineOperatorBuilder().
Word32And()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32And ()
Referenced by v8::internal::compiler::RepresentationChanger::Int32OperatorFor(), and v8::internal::compiler::RepresentationSelector::MaskShiftOperand().
Word32AtomicAdd()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicAdd (AtomicOpParameters params)
Definition at line 2370 of file machine-operator.cc.
                               {
#define OP_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord32AtomicAdd##kType##Kind; \
  }
#define OP(kType) \
  OP_WITH_KIND(kType, Normal) \
  OP_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_TYPE_LIST(OP)
#undef OP_WITH_KIND
#undef OP
  UNREACHABLE();
}
References ATOMIC_TYPE_LIST, v8::internal::OP, and v8::internal::UNREACHABLE().
Word32AtomicAnd()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicAnd (AtomicOpParameters params)
Definition at line 2402 of file machine-operator.cc.
                               {
#define OP_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord32AtomicAnd##kType##Kind; \
  }
#define OP(kType) \
  OP_WITH_KIND(kType, Normal) \
  OP_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_TYPE_LIST(OP)
#undef OP_WITH_KIND
#undef OP
  UNREACHABLE();
}
References ATOMIC_TYPE_LIST, v8::internal::OP, and v8::internal::UNREACHABLE().
Word32AtomicCompareExchange()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicCompareExchange (AtomicOpParameters params)
Definition at line 2354 of file machine-operator.cc.
                               {
#define COMPARE_EXCHANGE_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord32AtomicCompareExchange##kType##Kind; \
  }
#define COMPARE_EXCHANGE(kType) \
  COMPARE_EXCHANGE_WITH_KIND(kType, Normal) \
  COMPARE_EXCHANGE_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_TYPE_LIST(COMPARE_EXCHANGE)
#undef COMPARE_EXCHANGE_WITH_KIND
#undef COMPARE_EXCHANGE
  UNREACHABLE();
}
References ATOMIC_TYPE_LIST, COMPARE_EXCHANGE, and v8::internal::UNREACHABLE().
Word32AtomicExchange()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicExchange (AtomicOpParameters params)
Definition at line 2338 of file machine-operator.cc.
                               {
#define EXCHANGE_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord32AtomicExchange##kType##Kind; \
  }
#define EXCHANGE(kType) \
  EXCHANGE_WITH_KIND(kType, Normal) \
  EXCHANGE_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_TYPE_LIST(EXCHANGE)
#undef EXCHANGE_WITH_KIND
#undef EXCHANGE
  UNREACHABLE();
}
References ATOMIC_TYPE_LIST, EXCHANGE, and v8::internal::UNREACHABLE().
Word32AtomicLoad()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicLoad (AtomicLoadParameters params)
Definition at line 2282 of file machine-operator.cc.
                                 {
#define CACHED_LOAD_WITH_KIND(Type, Kind) \
  if (params.representation() == MachineType::Type() && \
      params.order() == AtomicMemoryOrder::kSeqCst && \
      params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord32SeqCstLoad##Type##Kind; \
  }
#define CACHED_LOAD(Type) \
  CACHED_LOAD_WITH_KIND(Type, Normal) \
  CACHED_LOAD_WITH_KIND(Type, ProtectedByTrapHandler)
  ATOMIC_TYPE_LIST(CACHED_LOAD)
#undef CACHED_LOAD_WITH_KIND
#undef CACHED_LOAD
#define LOAD(Type) \
  if (params.representation() == MachineType::Type()) { \
    return zone_->New<Operator1<AtomicLoadParameters>>(\
        IrOpcode::kWord32AtomicLoad, Operator::kNoProperties, \
        "Word32AtomicLoad", 2, 1, 1, 1, 1, 0, params); \
  }
  ATOMIC_TYPE_LIST(LOAD)
  ATOMIC_TAGGED_TYPE_LIST(LOAD)
#undef LOAD
  UNREACHABLE();
}
References ATOMIC_TAGGED_TYPE_LIST, ATOMIC_TYPE_LIST, CACHED_LOAD, v8::internal::LOAD, and v8::internal::UNREACHABLE().
Word32AtomicOr()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicOr (AtomicOpParameters params)
Definition at line 2418 of file machine-operator.cc.
                               {
#define OP_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord32AtomicOr##kType##Kind; \
  }
#define OP(kType) \
  OP_WITH_KIND(kType, Normal) \
  OP_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_TYPE_LIST(OP)
#undef OP_WITH_KIND
#undef OP
  UNREACHABLE();
}
References ATOMIC_TYPE_LIST, v8::internal::OP, and v8::internal::UNREACHABLE().
Word32AtomicPairAdd()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicPairAdd ()
Definition at line 2639 of file machine-operator.cc.
                                                            {
  return &cache_.kWord32AtomicPairAdd;
}
References cache_.
Word32AtomicPairAnd()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicPairAnd ()
Definition at line 2647 of file machine-operator.cc.
                                                            {
  return &cache_.kWord32AtomicPairAnd;
}
References cache_.
Word32AtomicPairCompareExchange()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicPairCompareExchange ()
Definition at line 2663 of file machine-operator.cc.
                                                                        {
  return &cache_.kWord32AtomicPairCompareExchange;
}
References cache_, and v8::internal::compiler::MachineOperatorGlobalCache::kWord32AtomicPairCompareExchange.
Word32AtomicPairExchange()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicPairExchange ()
Definition at line 2659 of file machine-operator.cc.
                                                                 {
  return &cache_.kWord32AtomicPairExchange;
}
References cache_.
Word32AtomicPairLoad()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicPairLoad (AtomicMemoryOrder order)
Definition at line 2619 of file machine-operator.cc.
                             {
  if (order == AtomicMemoryOrder::kSeqCst) {
    return &cache_.kWord32SeqCstPairLoad;
  }
  return zone_->New<Operator1<AtomicMemoryOrder>>(
      IrOpcode::kWord32AtomicPairLoad, Operator::kNoDeopt | Operator::kNoThrow,
      "Word32AtomicPairLoad", 2, 1, 1, 2, 1, 0, order);
}
References cache_, v8::internal::compiler::Operator::kNoDeopt, v8::internal::compiler::Operator::kNoThrow, v8::internal::kSeqCst, v8::internal::compiler::MachineOperatorGlobalCache::kWord32SeqCstPairLoad, v8::internal::Zone::New(), and zone_.
Word32AtomicPairOr()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicPairOr ()
Definition at line 2651 of file machine-operator.cc.
                                                           {
  return &cache_.kWord32AtomicPairOr;
}
References cache_.
Word32AtomicPairStore()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicPairStore (AtomicMemoryOrder order)
Definition at line 2629 of file machine-operator.cc.
                             {
  if (order == AtomicMemoryOrder::kSeqCst) {
    return &cache_.kWord32SeqCstPairStore;
  }
  return zone_->New<Operator1<AtomicMemoryOrder>>(
      IrOpcode::kWord32AtomicPairStore, Operator::kNoDeopt | Operator::kNoThrow,
      "Word32AtomicPairStore", 4, 1, 1, 0, 1, 0, order);
}
References cache_, v8::internal::compiler::Operator::kNoDeopt, v8::internal::compiler::Operator::kNoThrow, v8::internal::kSeqCst, v8::internal::compiler::MachineOperatorGlobalCache::kWord32SeqCstPairStore, v8::internal::Zone::New(), and zone_.
Word32AtomicPairSub()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicPairSub ()
Definition at line 2643 of file machine-operator.cc.
                                                            {
  return &cache_.kWord32AtomicPairSub;
}
References cache_.
Word32AtomicPairXor()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicPairXor ()
Definition at line 2655 of file machine-operator.cc.
                                                            {
  return &cache_.kWord32AtomicPairXor;
}
References cache_.
Word32AtomicStore()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicStore (AtomicStoreParameters params)
Definition at line 2310 of file machine-operator.cc.
                                  {
#define CACHED_STORE_WITH_KIND(kRep, Kind) \
  if (params.representation() == MachineRepresentation::kRep && \
      params.order() == AtomicMemoryOrder::kSeqCst && \
      params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord32SeqCstStore##kRep##Kind; \
  }
#define CACHED_STORE(kRep) \
  CACHED_STORE_WITH_KIND(kRep, Normal) \
  CACHED_STORE_WITH_KIND(kRep, ProtectedByTrapHandler)
  ATOMIC_REPRESENTATION_LIST(CACHED_STORE)
#undef CACHED_STORE_WITH_KIND
#undef CACHED_STORE
#define STORE(kRep) \
  if (params.representation() == MachineRepresentation::kRep) { \
    return zone_->New<Operator1<AtomicStoreParameters>>(\
        IrOpcode::kWord32AtomicStore, \
        Operator::kNoDeopt | Operator::kNoRead | Operator::kNoThrow, \
        "Word32AtomicStore", 3, 1, 1, 0, 1, 0, params); \
  }
  ATOMIC_REPRESENTATION_LIST(STORE)
  ATOMIC_TAGGED_REPRESENTATION_LIST(STORE)
#undef STORE
  UNREACHABLE();
}
References ATOMIC_REPRESENTATION_LIST, ATOMIC_TAGGED_REPRESENTATION_LIST, CACHED_STORE, v8::internal::STORE, and v8::internal::UNREACHABLE().
Word32AtomicSub()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicSub (AtomicOpParameters params)
Definition at line 2386 of file machine-operator.cc.
                               {
#define OP_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord32AtomicSub##kType##Kind; \
  }
#define OP(kType) \
  OP_WITH_KIND(kType, Normal) \
  OP_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_TYPE_LIST(OP)
#undef OP_WITH_KIND
#undef OP
  UNREACHABLE();
}
References ATOMIC_TYPE_LIST, v8::internal::OP, and v8::internal::UNREACHABLE().
Word32AtomicXor()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32AtomicXor (AtomicOpParameters params)
Definition at line 2434 of file machine-operator.cc.
                               {
#define OP_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord32AtomicXor##kType##Kind; \
  }
#define OP(kType) \
  OP_WITH_KIND(kType, Normal) \
  OP_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_TYPE_LIST(OP)
#undef OP_WITH_KIND
#undef OP
  UNREACHABLE();
}
References ATOMIC_TYPE_LIST, v8::internal::OP, and v8::internal::UNREACHABLE().
Word32Clz()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32Clz ()
Referenced by v8::internal::compiler::RepresentationChanger::Uint32OperatorFor().
Word32Ctz()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Word32Ctz ()
Referenced by v8::internal::compiler::CodeAssembler::IsWord32CtzSupported().
Word32Equal()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32Equal ()
Referenced by v8::internal::compiler::SimplifiedLowering::DoIntegral32ToBit(), v8::internal::compiler::RepresentationChanger::Int32OperatorFor(), v8::internal::compiler::RepresentationChanger::TaggedSignedOperatorFor(), v8::internal::compiler::RepresentationChanger::Uint32OperatorFor(), v8::internal::compiler::RepresentationSelector::VisitNode(), and v8::internal::compiler::Word32Adapter::WordNEqual().
Word32Or()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32Or ()
Referenced by v8::internal::compiler::BasicBlockInstrumentor::Instrument(), and v8::internal::compiler::RepresentationChanger::Int32OperatorFor().
Word32PairSar()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32PairSar ()
Word32PairShl()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32PairShl ()
Word32PairShr()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32PairShr ()
Word32Popcnt()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Word32Popcnt ()
Referenced by v8::internal::compiler::CodeAssembler::IsWord32PopcntSupported().
Word32ReverseBits()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Word32ReverseBits ()
Word32ReverseBytes()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32ReverseBytes ()
Word32Rol()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Word32Rol ()
Word32Ror()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32Ror ()
Word32Sar() [1/2]
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32Sar () [inline]
Definition at line 508 of file machine-operator.h.
{ return Word32Sar(ShiftKind::kNormal); }
References v8::internal::compiler::kNormal, and Word32Sar().
Referenced by Word32Sar().
Word32Sar() [2/2]
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word32Sar (ShiftKind kind)
Definition at line 1884 of file machine-operator.cc.
                                                                {
  switch (kind) {
    case ShiftKind::kNormal:
      return &cache_.kNormalWord32Sar;
    case ShiftKind::kShiftOutZeros:
      return &cache_.kShiftOutZerosWord32Sar;
  }
}
References cache_, v8::internal::compiler::kNormal, v8::internal::compiler::MachineOperatorGlobalCache::kNormalWord32Sar, v8::internal::compiler::kShiftOutZeros, and v8::internal::compiler::MachineOperatorGlobalCache::kShiftOutZerosWord32Sar.
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
Word32SarShiftOutZeros()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32SarShiftOutZeros () [inline]
Definition at line 509 of file machine-operator.h.
                                           {
    return Word32Sar(ShiftKind::kShiftOutZeros);
  }
References v8::internal::compiler::kShiftOutZeros.
Word32Select()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Word32Select ()
Word32ShiftIsSafe()
bool v8::internal::compiler::MachineOperatorBuilder::Word32ShiftIsSafe () const [inline]
Definition at line 530 of file machine-operator.h.
{ return flags_ & kWord32ShiftIsSafe; }
Referenced by v8::internal::compiler::CodeAssembler::Word32ShiftIsSafe().
Word32Shl()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32Shl ()
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
Word32Shr()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32Shr ()
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
Word32Xor()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word32Xor ()
Referenced by v8::internal::compiler::RepresentationChanger::Int32OperatorFor().
Word64And()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word64And ()
Referenced by v8::internal::compiler::RepresentationChanger::Int64OperatorFor(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Word64AtomicAdd()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word64AtomicAdd (AtomicOpParameters params)
Definition at line 2507 of file machine-operator.cc.
                               {
#define OP_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord64AtomicAdd##kType##Kind; \
  }
#define OP(kType) \
  OP_WITH_KIND(kType, Normal) \
  OP_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_U64_TYPE_LIST(OP)
#undef OP_WITH_KIND
#undef OP
  UNREACHABLE();
}
References ATOMIC_U64_TYPE_LIST, v8::internal::OP, and v8::internal::UNREACHABLE().
Word64AtomicAnd()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word64AtomicAnd (AtomicOpParameters params)
Definition at line 2539 of file machine-operator.cc.
                               {
#define OP_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord64AtomicAnd##kType##Kind; \
  }
#define OP(kType) \
  OP_WITH_KIND(kType, Normal) \
  OP_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_U64_TYPE_LIST(OP)
#undef OP_WITH_KIND
#undef OP
  UNREACHABLE();
}
References ATOMIC_U64_TYPE_LIST, v8::internal::OP, and v8::internal::UNREACHABLE().
Word64AtomicCompareExchange()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word64AtomicCompareExchange (AtomicOpParameters params)
Definition at line 2603 of file machine-operator.cc.
                               {
#define OP_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord64AtomicCompareExchange##kType##Kind; \
  }
#define OP(kType) \
  OP_WITH_KIND(kType, Normal) \
  OP_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_U64_TYPE_LIST(OP)
#undef OP_WITH_KIND
#undef OP
  UNREACHABLE();
}
References ATOMIC_U64_TYPE_LIST, v8::internal::OP, and v8::internal::UNREACHABLE().
Word64AtomicExchange()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word64AtomicExchange (AtomicOpParameters params)
Definition at line 2587 of file machine-operator.cc.
                               {
#define OP_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord64AtomicExchange##kType##Kind; \
  }
#define OP(kType) \
  OP_WITH_KIND(kType, Normal) \
  OP_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_U64_TYPE_LIST(OP)
#undef OP_WITH_KIND
#undef OP
  UNREACHABLE();
}
References ATOMIC_U64_TYPE_LIST, v8::internal::OP, and v8::internal::UNREACHABLE().
Word64AtomicLoad()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word64AtomicLoad (AtomicLoadParameters params)
Definition at line 2450 of file machine-operator.cc.
                                 {
#define CACHED_LOAD_WITH_KIND(Type, Kind) \
  if (params.representation() == MachineType::Type() && \
      params.order() == AtomicMemoryOrder::kSeqCst && \
      params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord64SeqCstLoad##Type##Kind; \
  }
#define CACHED_LOAD(Type) \
  CACHED_LOAD_WITH_KIND(Type, Normal) \
  CACHED_LOAD_WITH_KIND(Type, ProtectedByTrapHandler)
  ATOMIC_U64_TYPE_LIST(CACHED_LOAD)
#undef CACHED_LOAD_WITH_KIND
#undef CACHED_LOAD
#define LOAD(Type) \
  if (params.representation() == MachineType::Type()) { \
    return zone_->New<Operator1<AtomicLoadParameters>>(\
        IrOpcode::kWord64AtomicLoad, Operator::kNoProperties, \
        "Word64AtomicLoad", 2, 1, 1, 1, 1, 0, params); \
  }
  ATOMIC_U64_TYPE_LIST(LOAD)
  ATOMIC64_TAGGED_TYPE_LIST(LOAD)
#undef LOAD
  UNREACHABLE();
}
References ATOMIC64_TAGGED_TYPE_LIST, ATOMIC_U64_TYPE_LIST, CACHED_LOAD, v8::internal::LOAD, and v8::internal::UNREACHABLE().
Word64AtomicOr()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word64AtomicOr (AtomicOpParameters params)
Definition at line 2555 of file machine-operator.cc.
                               {
#define OP_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord64AtomicOr##kType##Kind; \
  }
#define OP(kType) \
  OP_WITH_KIND(kType, Normal) \
  OP_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_U64_TYPE_LIST(OP)
#undef OP_WITH_KIND
#undef OP
  UNREACHABLE();
}
References ATOMIC_U64_TYPE_LIST, v8::internal::OP, and v8::internal::UNREACHABLE().
Word64AtomicStore()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word64AtomicStore (AtomicStoreParameters params)
Definition at line 2478 of file machine-operator.cc.
                                  {
#define CACHED_STORE_WITH_KIND(kRep, Kind) \
  if (params.representation() == MachineRepresentation::kRep && \
      params.order() == AtomicMemoryOrder::kSeqCst && \
      params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord64SeqCstStore##kRep##Kind; \
  }
#define CACHED_STORE(kRep) \
  CACHED_STORE_WITH_KIND(kRep, Normal) \
  CACHED_STORE_WITH_KIND(kRep, ProtectedByTrapHandler)
  ATOMIC64_REPRESENTATION_LIST(CACHED_STORE)
#undef CACHED_STORE_WITH_KIND
#undef CACHED_STORE
#define STORE(kRep) \
  if (params.representation() == MachineRepresentation::kRep) { \
    return zone_->New<Operator1<AtomicStoreParameters>>(\
        IrOpcode::kWord64AtomicStore, \
        Operator::kNoDeopt | Operator::kNoRead | Operator::kNoThrow, \
        "Word64AtomicStore", 3, 1, 1, 0, 1, 0, params); \
  }
  ATOMIC64_REPRESENTATION_LIST(STORE)
  ATOMIC64_TAGGED_REPRESENTATION_LIST(STORE)
#undef STORE
  UNREACHABLE();
}
References ATOMIC64_REPRESENTATION_LIST, ATOMIC64_TAGGED_REPRESENTATION_LIST, CACHED_STORE, v8::internal::STORE, and v8::internal::UNREACHABLE().
Word64AtomicSub()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word64AtomicSub (AtomicOpParameters params)
Definition at line 2523 of file machine-operator.cc.
                               {
#define OP_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord64AtomicSub##kType##Kind; \
  }
#define OP(kType) \
  OP_WITH_KIND(kType, Normal) \
  OP_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_U64_TYPE_LIST(OP)
#undef OP_WITH_KIND
#undef OP
  UNREACHABLE();
}
References ATOMIC_U64_TYPE_LIST, v8::internal::OP, and v8::internal::UNREACHABLE().
Word64AtomicXor()
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word64AtomicXor (AtomicOpParameters params)
Definition at line 2571 of file machine-operator.cc.
                               {
#define OP_WITH_KIND(kType, Kind) \
  if (params.type() == MachineType::kType() \
      && params.kind() == MemoryAccessKind::k##Kind) { \
    return &cache_.kWord64AtomicXor##kType##Kind; \
  }
#define OP(kType) \
  OP_WITH_KIND(kType, Normal) \
  OP_WITH_KIND(kType, ProtectedByTrapHandler)
  ATOMIC_U64_TYPE_LIST(OP)
#undef OP_WITH_KIND
#undef OP
  UNREACHABLE();
}
References ATOMIC_U64_TYPE_LIST, v8::internal::OP, and v8::internal::UNREACHABLE().
Word64Clz()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word64Clz ()
Word64ClzLowerable()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word64ClzLowerable ()
Word64Ctz()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Word64Ctz ()
Referenced by v8::internal::compiler::CodeAssembler::IsWord64CtzSupported().
Word64CtzLowerable()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Word64CtzLowerable ()
Word64Equal()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word64Equal ()
Referenced by v8::internal::compiler::RepresentationChanger::Int64OperatorFor(), v8::internal::compiler::RepresentationChanger::TaggedSignedOperatorFor(), and v8::internal::compiler::Word64Adapter::WordNEqual().
Word64Or()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word64Or ()
Referenced by v8::internal::compiler::RepresentationChanger::Int64OperatorFor().
Word64Popcnt()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Word64Popcnt ()
Referenced by v8::internal::compiler::CodeAssembler::IsWord64PopcntSupported().
Word64ReverseBits()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Word64ReverseBits ()
Word64ReverseBytes()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word64ReverseBytes ()
Word64Rol()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Word64Rol ()
Word64RolLowerable()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Word64RolLowerable ()
Word64Ror()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word64Ror ()
Word64RorLowerable()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word64RorLowerable ()
Word64Sar() [1/2]
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word64Sar () [inline]
Definition at line 550 of file machine-operator.h.
{ return Word64Sar(ShiftKind::kNormal); }
References v8::internal::compiler::kNormal, and Word64Sar().
Referenced by Word64Sar().
Word64Sar() [2/2]
const Operator * v8::internal::compiler::MachineOperatorBuilder::Word64Sar (ShiftKind kind)
Definition at line 1893 of file machine-operator.cc.
                                                                {
  switch (kind) {
    case ShiftKind::kNormal:
      return &cache_.kNormalWord64Sar;
    case ShiftKind::kShiftOutZeros:
      return &cache_.kShiftOutZerosWord64Sar;
  }
}
References cache_, v8::internal::compiler::kNormal, v8::internal::compiler::MachineOperatorGlobalCache::kNormalWord64Sar, v8::internal::compiler::kShiftOutZeros, and v8::internal::compiler::MachineOperatorGlobalCache::kShiftOutZerosWord64Sar.
Referenced by v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Word64SarShiftOutZeros()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word64SarShiftOutZeros () [inline]
Definition at line 551 of file machine-operator.h.
                                           {
    return Word64Sar(ShiftKind::kShiftOutZeros);
  }
References v8::internal::compiler::kShiftOutZeros.
Word64Select()
const OptionalOperator v8::internal::compiler::MachineOperatorBuilder::Word64Select ()
Word64Shl()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word64Shl ()
Referenced by v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Word64Shr()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word64Shr ()
Referenced by v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift().
Word64Xor()
const Operator* v8::internal::compiler::MachineOperatorBuilder::Word64Xor ()
Referenced by v8::internal::compiler::RepresentationChanger::Int64OperatorFor().
WordSar()
const Operator* v8::internal::compiler::MachineOperatorBuilder::WordSar (ShiftKind kind = ShiftKind::kNormal) [inline]
Definition at line 1394 of file machine-operator.h.
                                                             {
    return Is32() ? Word32Sar(kind) : Word64Sar(kind);
  }
WordSarShiftOutZeros()
const Operator* v8::internal::compiler::MachineOperatorBuilder::WordSarShiftOutZeros () [inline]
Definition at line 1397 of file machine-operator.h.
                                         {
    return WordSar(ShiftKind::kShiftOutZeros);
  }
References v8::internal::compiler::kShiftOutZeros.
Member Data Documentation
alignment_requirements_
AlignmentRequirements const v8::internal::compiler::MachineOperatorBuilder::alignment_requirements_ [private]
Definition at line 1410 of file machine-operator.h.
cache_
MachineOperatorGlobalCache const& v8::internal::compiler::MachineOperatorBuilder::cache_ [private]
Definition at line 1407 of file machine-operator.h.
Referenced by AbortCSADcheck(), BitcastMaybeObjectToWord(), BitcastTaggedToWord(), BitcastWordToTagged(), ChangeFloat16RawBitsToFloat64(), DebugBreak(), MemoryBarrier(), StackPointerGreaterThan(), StoreIndirectPointer(), TruncateFloat32ToInt32(), TruncateFloat32ToUint32(), TruncateFloat64ToFloat16RawBits(), TruncateFloat64ToInt64(), Word32AtomicPairAdd(), Word32AtomicPairAnd(), Word32AtomicPairCompareExchange(), Word32AtomicPairExchange(), Word32AtomicPairLoad(), Word32AtomicPairOr(), Word32AtomicPairStore(), Word32AtomicPairSub(), Word32AtomicPairXor(), Word32Sar(), and Word64Sar().
flags_
Flags const v8::internal::compiler::MachineOperatorBuilder::flags_ [private]
Definition at line 1409 of file machine-operator.h.
Referenced by ChangeFloat16RawBitsToFloat64(), and TruncateFloat64ToFloat16RawBits().
word_
MachineRepresentation const v8::internal::compiler::MachineOperatorBuilder::word_ [private]
Definition at line 1408 of file machine-operator.h.
zone_
Zone* v8::internal::compiler::MachineOperatorBuilder::zone_ [private]
Definition at line 1406 of file machine-operator.h.
Referenced by Comment(), StackSlot(), TraceInstruction(), Word32AtomicPairLoad(), and Word32AtomicPairStore().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/machine-operator.h
/mnt/V8SourceCode/src/compiler/machine-operator.cc