v8::internal::compiler::Constant Class Reference
#include <instruction.h>
Public Types
enum Type {
kInt32
, kInt64
, kFloat32
, kFloat64
,
kExternalReference
, kCompressedHeapObject
, kHeapObject
, kRpoNumber
 }
Public Member Functions
Constant (int32_t v)
Constant (int64_t v)
Constant (float v)
Constant (Float32 v)
Constant (double v)
Constant (Float64 v)
Constant (ExternalReference ref)
Constant (IndirectHandle< HeapObject > obj, bool is_compressed=false)
Constant (RpoNumber rpo)
Constant (RelocatablePtrConstantInfo info)
Type type () const
RelocInfo::Mode rmode () const
bool FitsInInt32 () const
int32_t ToInt32 () const
int64_t ToInt64 () const
float ToFloat32 () const
Float32 ToFloat32Safe () const
uint32_t ToFloat32AsInt () const
base::Double ToFloat64 () const
ExternalReference ToExternalReference () const
RpoNumber ToRpoNumber () const
IndirectHandle< HeapObject > ToHeapObject () const
IndirectHandle< Code > ToCode () const
Private Attributes
Type type_
RelocInfo::Mode rmode_ = RelocInfo::NO_INFO
int64_t value_
Detailed Description
Definition at line 1212 of file instruction.h.
Member Enumeration Documentation
Type
enum v8::internal::compiler::Constant::Type
Enumerator
kInt32
kInt64
kFloat32
kFloat64
kExternalReference
kCompressedHeapObject
kHeapObject
kRpoNumber
Definition at line 1214 of file instruction.h.
            {
    kInt32,
    kInt64,
    kFloat32,
    kFloat64,
    kExternalReference,
    kCompressedHeapObject,
    kHeapObject,
    kRpoNumber
  };
Constructor & Destructor Documentation
Constant() [1/10]
v8::internal::compiler::Constant::Constant (int32_t v) [explicit]
Definition at line 595 of file instruction.cc.
: type_(kInt32), value_(v) {}
References v8::internal::kInt32.
Constant() [2/10]
v8::internal::compiler::Constant::Constant (int64_t v) [inline], [explicit]
Definition at line 1226 of file instruction.h.
: type_(kInt64), value_(v) {}
References v8::internal::kInt64.
Constant() [3/10]
v8::internal::compiler::Constant::Constant (float v) [inline], [explicit]
Definition at line 1227 of file instruction.h.
      : type_(kFloat32), value_(base::bit_cast<int32_t>(v)) {}
References v8::internal::kFloat32.
Constant() [4/10]
v8::internal::compiler::Constant::Constant (Float32 v) [inline], [explicit]
Definition at line 1229 of file instruction.h.
: type_(kFloat32), value_(v.get_bits()) {}
References v8::internal::kFloat32.
Constant() [5/10]
v8::internal::compiler::Constant::Constant (double v) [inline], [explicit]
Definition at line 1230 of file instruction.h.
      : type_(kFloat64), value_(base::bit_cast<int64_t>(v)) {}
References v8::internal::kFloat64.
Constant() [6/10]
v8::internal::compiler::Constant::Constant (Float64 v) [inline], [explicit]
Definition at line 1232 of file instruction.h.
: type_(kFloat64), value_(v.get_bits()) {}
References v8::internal::kFloat64.
Constant() [7/10]
v8::internal::compiler::Constant::Constant (ExternalReference ref) [inline], [explicit]
Definition at line 1233 of file instruction.h.
      : type_(kExternalReference),
        value_(base::bit_cast<intptr_t>(ref.raw())) {}
Constant() [8/10]
v8::internal::compiler::Constant::Constant (IndirectHandle< HeapObject > obj, bool is_compressed = false) [inline], [explicit]
Definition at line 1236 of file instruction.h.
      : type_(is_compressed ? kCompressedHeapObject : kHeapObject),
        value_(base::bit_cast<intptr_t>(obj)) {}
References v8::internal::compiler::kHeapObject.
Constant() [9/10]
v8::internal::compiler::Constant::Constant (RpoNumber rpo) [inline], [explicit]
Definition at line 1239 of file instruction.h.
: type_(kRpoNumber), value_(rpo.ToInt()) {}
Constant() [10/10]
v8::internal::compiler::Constant::Constant (RelocatablePtrConstantInfo info) [explicit]
Definition at line 597 of file instruction.cc.
                                                  {
  if (info.type() == RelocatablePtrConstantInfo::kInt32) {
    type_ = kInt32;
  } else if (info.type() == RelocatablePtrConstantInfo::kInt64) {
    type_ = kInt64;
  } else {
    UNREACHABLE();
  }
  value_ = info.value();
  rmode_ = info.rmode();
}
References kInt32, v8::internal::compiler::RelocatablePtrConstantInfo::kInt32, kInt64, v8::internal::compiler::RelocatablePtrConstantInfo::kInt64, v8::internal::compiler::RelocatablePtrConstantInfo::rmode(), rmode_, v8::internal::compiler::RelocatablePtrConstantInfo::type(), type_, v8::internal::UNREACHABLE(), v8::internal::compiler::RelocatablePtrConstantInfo::value(), and value_.
Member Function Documentation
FitsInInt32()
bool v8::internal::compiler::Constant::FitsInInt32 () const [inline]
Definition at line 1246 of file instruction.h.
                           {
    if (type() == kInt32) return true;
    DCHECK(type() == kInt64);
    return value_ >= std::numeric_limits<int32_t>::min() &&
           value_ <= std::numeric_limits<int32_t>::max();
  }
References v8::internal::DCHECK(), v8::internal::kInt32, v8::internal::kInt64, v8::internal::tracing::type, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::InstructionSequence::AddImmediate().
rmode()
RelocInfo::Mode v8::internal::compiler::Constant::rmode () const [inline]
Definition at line 1244 of file instruction.h.
{ return rmode_; }
Referenced by v8::internal::compiler::InstructionSequence::AddImmediate(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::IA32OperandConverter::MemoryOperand(), v8::internal::compiler::IA32OperandConverter::NextMemoryOperand(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::IA32OperandConverter::ToImmediate(), v8::internal::compiler::X64OperandConverter::ToImmediate(), and v8::internal::compiler::ArmOperandConverter::ToImmediate().
ToCode()
IndirectHandle< Code > v8::internal::compiler::Constant::ToCode () const
Definition at line 616 of file instruction.cc.
                                            {
  DCHECK_EQ(kHeapObject, type());
  IndirectHandle<Code> value(
      reinterpret_cast<Address*>(static_cast<intptr_t>(value_)));
  DCHECK(IsCode(*value));
  return value;
}
References v8::internal::DCHECK(), DCHECK_EQ, kHeapObject, type(), v8::internal::value, and value_.
Referenced by v8::internal::compiler::InstructionOperandConverter::ToCode().
ToExternalReference()
ExternalReference v8::internal::compiler::Constant::ToExternalReference () const [inline]
Definition at line 1291 of file instruction.h.
                                                {
    DCHECK_EQ(kExternalReference, type());
    return ExternalReference::FromRawAddress(static_cast<Address>(value_));
  }
References DCHECK_EQ, v8::internal::ExternalReference::FromRawAddress(), v8::internal::tracing::type, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::S390OperandConverter::InputImmediate(), v8::internal::compiler::operator<<(), v8::internal::compiler::InstructionOperandConverter::ToExternalReference(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::IA32OperandConverter::ToImmediate(), and v8::internal::compiler::ArmOperandConverter::ToImmediate().
ToFloat32()
float v8::internal::compiler::Constant::ToFloat32 () const [inline]
Definition at line 1266 of file instruction.h.
                          {
    // TODO(ahaas): We should remove this function. If value_ has the bit
    // representation of a signalling NaN, then returning it as float can cause
    // the signalling bit to flip, and value_ is returned as a quiet NaN.
    DCHECK_EQ(kFloat32, type());
    return base::bit_cast<float>(static_cast<int32_t>(value_));
  }
References DCHECK_EQ, v8::internal::kFloat32, v8::internal::tracing::type, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::MipsOperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::compiler::S390OperandConverter::InputImmediate(), v8::internal::compiler::operator<<(), v8::internal::compiler::InstructionOperandConverter::ToFloat32(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::IA32OperandConverter::ToImmediate(), and v8::internal::compiler::ArmOperandConverter::ToImmediate().
ToFloat32AsInt()
uint32_t v8::internal::compiler::Constant::ToFloat32AsInt () const [inline]
Definition at line 1281 of file instruction.h.
                                  {
    DCHECK_EQ(kFloat32, type());
    return base::bit_cast<uint32_t>(static_cast<int32_t>(value_));
  }
References DCHECK_EQ, v8::internal::kFloat32, v8::internal::tracing::type, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleMove().
ToFloat32Safe()
Float32 v8::internal::compiler::Constant::ToFloat32Safe () const [inline]
Definition at line 1276 of file instruction.h.
                                {
    DCHECK_EQ(kFloat32, type());
    return Float32::FromBits(static_cast<uint32_t>(value_));
  }
References DCHECK_EQ, v8::internal::Float32::FromBits(), v8::internal::kFloat32, v8::internal::tracing::type, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
ToFloat64()
base::Double v8::internal::compiler::Constant::ToFloat64 () const [inline]
Definition at line 1286 of file instruction.h.
                               {
    DCHECK_EQ(kFloat64, type());
    return base::Double(base::bit_cast<uint64_t>(value_));
  }
References DCHECK_EQ, v8::internal::kFloat64, v8::internal::tracing::type, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::MipsOperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::compiler::S390OperandConverter::InputImmediate(), v8::internal::compiler::operator<<(), v8::internal::compiler::InstructionOperandConverter::ToDouble(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::IA32OperandConverter::ToImmediate(), v8::internal::compiler::X64OperandConverter::ToImmediate(), and v8::internal::compiler::ArmOperandConverter::ToImmediate().
ToHeapObject()
IndirectHandle< HeapObject > v8::internal::compiler::Constant::ToHeapObject () const
Definition at line 609 of file instruction.cc.
                                                        {
  DCHECK(kHeapObject == type() || kCompressedHeapObject == type());
  IndirectHandle<HeapObject> value(
      reinterpret_cast<Address*>(static_cast<intptr_t>(value_)));
  return value;
}
References v8::internal::DCHECK(), kCompressedHeapObject, kHeapObject, type(), v8::internal::value, and value_.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::compiler::operator<<(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::IA32OperandConverter::ToImmediate(), and v8::internal::compiler::X64OperandConverter::ToImmediate().
ToInt32()
int32_t v8::internal::compiler::Constant::ToInt32 () const [inline]
Definition at line 1253 of file instruction.h.
                          {
    DCHECK(FitsInInt32());
    const int32_t value = static_cast<int32_t>(value_);
    DCHECK_EQ(value_, static_cast<int64_t>(value));
    return value;
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::value, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::InstructionSequence::AddImmediate(), v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleReturn(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::MipsOperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::compiler::S390OperandConverter::InputImmediate(), v8::internal::compiler::InstructionOperandConverter::InputInt32(), v8::internal::compiler::FrameElider::MarkBlocks(), v8::internal::compiler::IA32OperandConverter::MemoryOperand(), v8::internal::compiler::IA32OperandConverter::NextMemoryOperand(), v8::internal::compiler::operator<<(), v8::internal::compiler::CodeGenerator::RecordCallPosition(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::IA32OperandConverter::ToImmediate(), v8::internal::compiler::X64OperandConverter::ToImmediate(), and v8::internal::compiler::ArmOperandConverter::ToImmediate().
ToInt64()
int64_t v8::internal::compiler::Constant::ToInt64 () const [inline]
Definition at line 1260 of file instruction.h.
                          {
    if (type() == kInt32) return ToInt32();
    DCHECK_EQ(kInt64, type());
    return value_;
  }
References DCHECK_EQ, v8::internal::kInt32, v8::internal::kInt64, v8::internal::tracing::type, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::MipsOperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::compiler::S390OperandConverter::InputImmediate(), v8::internal::compiler::InstructionOperandConverter::InputInt64(), v8::internal::compiler::operator<<(), and v8::internal::compiler::Arm64OperandConverter::ToImmediate().
ToRpoNumber()
RpoNumber v8::internal::compiler::Constant::ToRpoNumber () const [inline]
Definition at line 1296 of file instruction.h.
                                {
    DCHECK_EQ(kRpoNumber, type());
    return RpoNumber::FromInt(static_cast<int>(value_));
  }
References DCHECK_EQ, v8::internal::compiler::RpoNumber::FromInt(), v8::internal::tracing::type, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::InstructionSequence::AddImmediate(), v8::internal::compiler::InstructionSequence::InputRpo(), v8::internal::compiler::operator<<(), v8::internal::compiler::CodeGenerator::RecordCallPosition(), and v8::internal::compiler::InstructionOperandConverter::ToRpoNumber().
type()
Type v8::internal::compiler::Constant::type () const [inline]
Definition at line 1242 of file instruction.h.
{ return type_; }
Referenced by v8::internal::compiler::InstructionSequence::AddConstant(), v8::internal::compiler::InstructionSequence::AddImmediate(), v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), v8::internal::compiler::CodeGenerator::AssembleReturn(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::MipsOperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::compiler::S390OperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputOrZeroRegister(), v8::internal::compiler::operator<<(), v8::internal::compiler::CodeGenerator::RecordCallPosition(), ToCode(), ToHeapObject(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::IA32OperandConverter::ToImmediate(), v8::internal::compiler::X64OperandConverter::ToImmediate(), and v8::internal::compiler::ArmOperandConverter::ToImmediate().
Member Data Documentation
rmode_
RelocInfo::Mode v8::internal::compiler::Constant::rmode_ = RelocInfo::NO_INFO [private]
Definition at line 1306 of file instruction.h.
Referenced by Constant().
type_
Type v8::internal::compiler::Constant::type_ [private]
Definition at line 1305 of file instruction.h.
Referenced by Constant().
value_
int64_t v8::internal::compiler::Constant::value_ [private]
Definition at line 1307 of file instruction.h.
Referenced by Constant(), ToCode(), and ToHeapObject().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction.h
/mnt/V8SourceCode/src/compiler/backend/instruction.cc