v8::internal::wasm::LinkageAllocator Class Reference
#include <wasm-linkage.h>
Public Member Functions
template<size_t kNumGpRegs, size_t kNumFpRegs>
constexpr LinkageAllocator (const Register(&gp)[kNumGpRegs], const DoubleRegister(&fp)[kNumFpRegs])
constexpr LinkageAllocator (const Register *gp, int gpc, const DoubleRegister *fp, int fpc)
bool CanAllocateGP () const
bool CanAllocateFP (MachineRepresentation rep) const
int NextGpReg ()
int NextFpReg (MachineRepresentation rep)
int NextStackSlot (MachineRepresentation type)
void SetStackOffset (int offset)
int NumStackSlots () const
void EndSlotArea ()
Private Attributes
const int gp_count_
int gp_offset_ = 0
const Register *const gp_regs_
const int fp_count_
int fp_offset_ = 0
const DoubleRegister *const fp_regs_
AlignedSlotAllocator slot_allocator_
Detailed Description
Definition at line 148 of file wasm-linkage.h.
Constructor & Destructor Documentation
LinkageAllocator() [1/2]
template<size_t kNumGpRegs, size_t kNumFpRegs>
constexpr v8::internal::wasm::LinkageAllocator::LinkageAllocator (const Register(&) gp[kNumGpRegs], const DoubleRegister(&) fp[kNumFpRegs]) [inline], [constexpr]
Definition at line 151 of file wasm-linkage.h.
      : LinkageAllocator(gp, kNumGpRegs, fp, kNumFpRegs) {}
LinkageAllocator() [2/2]
constexpr v8::internal::wasm::LinkageAllocator::LinkageAllocator (const Register * gp, int gpc, const DoubleRegister * fp, int fpc) [inline], [constexpr]
Definition at line 155 of file wasm-linkage.h.
      : gp_count_(gpc), gp_regs_(gp), fp_count_(fpc), fp_regs_(fp) {}
Member Function Documentation
CanAllocateFP()
bool v8::internal::wasm::LinkageAllocator::CanAllocateFP (MachineRepresentation rep) const [inline]
Definition at line 160 of file wasm-linkage.h.
                                                      {
#if V8_TARGET_ARCH_ARM
    switch (rep) {
      case MachineRepresentation::kFloat32: {
        // Get the next D-register (Liftoff only uses the even S-registers).
        int next = fp_allocator_.NextSlot(2) / 2;
        // Only the lower 16 D-registers alias S-registers.
        return next < fp_count_ && fp_regs_[next].code() < 16;
      }
      case MachineRepresentation::kFloat64: {
        int next = fp_allocator_.NextSlot(2) / 2;
        return next < fp_count_;
      }
      case MachineRepresentation::kSimd128: {
        int next = fp_allocator_.NextSlot(4) / 2;
        return next < fp_count_ - 1; // 2 D-registers are required.
      }
      default:
        UNREACHABLE();
        return false;
    }
#else
    return fp_offset_ < fp_count_;
#endif
  }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), fp_count_, fp_offset_, fp_regs_, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kSimd128, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::LinkageLocationAllocator::Next(), and NextFpReg().
CanAllocateGP()
bool v8::internal::wasm::LinkageAllocator::CanAllocateGP () const [inline]
Definition at line 159 of file wasm-linkage.h.
{ return gp_offset_ < gp_count_; }
References gp_count_, and gp_offset_.
Referenced by v8::internal::wasm::LinkageLocationAllocator::Next().
EndSlotArea()
void v8::internal::wasm::LinkageAllocator::EndSlotArea () [inline]
Definition at line 243 of file wasm-linkage.h.
{ slot_allocator_.AllocateUnaligned(0); }
References v8::internal::AlignedSlotAllocator::AllocateUnaligned(), and slot_allocator_.
Referenced by v8::internal::wasm::LinkageLocationAllocator::EndSlotArea().
NextFpReg()
int v8::internal::wasm::LinkageAllocator::NextFpReg (MachineRepresentation rep) [inline]
Definition at line 191 of file wasm-linkage.h.
                                           {
    DCHECK(CanAllocateFP(rep));
#if V8_TARGET_ARCH_ARM
    switch (rep) {
      case MachineRepresentation::kFloat32: {
        // Liftoff uses only even-numbered S-registers, and encodes them using
        // the code of the corresponding D-register. This limits the calling
        // interface to only using the even-numbered S-registers.
        int d_reg_code = NextFpReg(MachineRepresentation::kFloat64);
        DCHECK_GT(16, d_reg_code); // D16 - D31 don't alias S-registers.
        return d_reg_code * 2;
      }
      case MachineRepresentation::kFloat64: {
        int next = fp_allocator_.Allocate(2) / 2;
        return fp_regs_[next].code();
      }
      case MachineRepresentation::kSimd128: {
        int next = fp_allocator_.Allocate(4) / 2;
        int d_reg_code = fp_regs_[next].code();
        // Check that result and the next D-register pair.
        DCHECK_EQ(0, d_reg_code % 2);
        DCHECK_EQ(d_reg_code + 1, fp_regs_[next + 1].code());
        return d_reg_code / 2;
      }
      default:
        UNREACHABLE();
    }
#else
    return fp_regs_[fp_offset_++].code();
#endif
  }
References CanAllocateFP(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), code, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, fp_offset_, fp_regs_, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kSimd128, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::LinkageLocationAllocator::Next().
NextGpReg()
int v8::internal::wasm::LinkageAllocator::NextGpReg () [inline]
Definition at line 186 of file wasm-linkage.h.
                  {
    DCHECK_LT(gp_offset_, gp_count_);
    return gp_regs_[gp_offset_++].code();
  }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), DCHECK_LT, gp_count_, gp_offset_, and gp_regs_.
Referenced by v8::internal::wasm::LinkageLocationAllocator::Next().
NextStackSlot()
int v8::internal::wasm::LinkageAllocator::NextStackSlot (MachineRepresentation type) [inline]
Definition at line 226 of file wasm-linkage.h.
                                                {
    int num_slots =
        AlignedSlotAllocator::NumSlotsForWidth(ElementSizeInBytes(type));
    int slot = slot_allocator_.Allocate(num_slots);
    return slot;
  }
References v8::internal::AlignedSlotAllocator::Allocate(), v8::internal::ElementSizeInBytes(), v8::internal::AlignedSlotAllocator::NumSlotsForWidth(), slot_allocator_, and v8::internal::tracing::type.
Referenced by v8::internal::wasm::LinkageLocationAllocator::Next().
NumStackSlots()
int v8::internal::wasm::LinkageAllocator::NumStackSlots () const [inline]
Definition at line 241 of file wasm-linkage.h.
{ return slot_allocator_.Size(); }
References v8::internal::AlignedSlotAllocator::Size(), and slot_allocator_.
Referenced by v8::internal::wasm::LinkageLocationAllocator::NumStackSlots().
SetStackOffset()
void v8::internal::wasm::LinkageAllocator::SetStackOffset (int offset) [inline]
Definition at line 235 of file wasm-linkage.h.
                                  {
    DCHECK_LE(0, offset);
    DCHECK_EQ(0, slot_allocator_.Size());
    slot_allocator_.AllocateUnaligned(offset);
  }
References v8::internal::AlignedSlotAllocator::AllocateUnaligned(), DCHECK_EQ, DCHECK_LE, v8::internal::AlignedSlotAllocator::Size(), and slot_allocator_.
Member Data Documentation
fp_count_
const int v8::internal::wasm::LinkageAllocator::fp_count_ [private]
Definition at line 250 of file wasm-linkage.h.
Referenced by CanAllocateFP().
fp_offset_
int v8::internal::wasm::LinkageAllocator::fp_offset_ = 0 [private]
Definition at line 256 of file wasm-linkage.h.
Referenced by CanAllocateFP(), and NextFpReg().
fp_regs_
const DoubleRegister* const v8::internal::wasm::LinkageAllocator::fp_regs_ [private]
Definition at line 258 of file wasm-linkage.h.
Referenced by CanAllocateFP(), and NextFpReg().
gp_count_
const int v8::internal::wasm::LinkageAllocator::gp_count_ [private]
Definition at line 246 of file wasm-linkage.h.
Referenced by CanAllocateGP(), and NextGpReg().
gp_offset_
int v8::internal::wasm::LinkageAllocator::gp_offset_ = 0 [private]
Definition at line 247 of file wasm-linkage.h.
Referenced by CanAllocateGP(), and NextGpReg().
gp_regs_
const Register* const v8::internal::wasm::LinkageAllocator::gp_regs_ [private]
Definition at line 248 of file wasm-linkage.h.
Referenced by NextGpReg().
slot_allocator_
AlignedSlotAllocator v8::internal::wasm::LinkageAllocator::slot_allocator_ [private]
Definition at line 260 of file wasm-linkage.h.
Referenced by EndSlotArea(), NextStackSlot(), NumStackSlots(), and SetStackOffset().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-linkage.h