v8::internal::compiler::JSCallReducerAssembler Class Reference
Classes
class ForBuilder0
class ForBuilder1
class TryCatchBuilder0
Public Types
using ConditionFunction1 = std::function< TNode< Boolean >(TNode< Number >)>
using StepFunction1 = std::function< TNode< Number >(TNode< Number >)>
using For1BodyFunction = std::function< void(TNode< Number >, TNode< Object > *)>
Public Member Functions
JSCallReducerAssembler (JSCallReducer *reducer, Node *node, Node *effect=nullptr, Node *control=nullptr)
TNode< Object > ReduceJSCallWithArrayLikeOrSpreadOfEmpty (std::unordered_set< Node * > *generated_calls_with_array_like_or_spread)
TNode< Object > ReduceMathUnary (const Operator *op)
TNode< Object > ReduceMathBinary (const Operator *op)
TNode< String > ReduceStringPrototypeSubstring ()
TNode< Boolean > ReduceStringPrototypeStartsWith ()
TNode< Boolean > ReduceStringPrototypeStartsWith (StringRef search_element_string)
TNode< Boolean > ReduceStringPrototypeEndsWith ()
TNode< Boolean > ReduceStringPrototypeEndsWith (StringRef search_element_string)
TNode< String > ReduceStringPrototypeCharAt (SpeculationMode speculation_mode)
TNode< String > ReduceStringPrototypeCharAt (StringRef s, uint32_t index)
TNode< Number > ReduceStringPrototypeCharCodeAt (SpeculationMode speculation_mode)
TNode< String > ReduceStringPrototypeSlice ()
TNode< Object > ReduceJSCallMathMinMaxWithArrayLike (Builtin builtin)
TNode< Object > TargetInput () const
template<typename T >
TNode< T > ReceiverInputAs () const
TNode< Object > ReceiverInput () const
Node * node_ptr () const
TNode< Number > SpeculativeToNumber (TNode< Object > value, NumberOperationHint hint=NumberOperationHint::kNumberOrOddball)
TNode< Smi > CheckSmi (TNode< Object > value)
TNode< Number > CheckNumber (TNode< Object > value)
TNode< String > CheckString (TNode< Object > value)
TNode< Number > CheckBounds (TNode< Object > value, TNode< Number > limit, CheckBoundsFlags flags={})
TNode< Smi > TypeGuardUnsignedSmall (TNode< Object > value)
TNode< Object > TypeGuardNonInternal (TNode< Object > value)
TNode< Number > TypeGuardFixedArrayLength (TNode< Object > value)
TNode< Object > Call4 (const Callable &callable, TNode< Context > context, TNode< Object > arg0, TNode< Object > arg1, TNode< Object > arg2, TNode< Object > arg3)
TNode< Object > JSCall3 (TNode< Object > function, TNode< Object > this_arg, TNode< Object > arg0, TNode< Object > arg1, TNode< Object > arg2, FrameState frame_state)
TNode< Object > JSCall4 (TNode< Object > function, TNode< Object > this_arg, TNode< Object > arg0, TNode< Object > arg1, TNode< Object > arg2, TNode< Object > arg3, FrameState frame_state)
TNode< Object > CopyNode ()
TNode< JSArray > CreateArrayNoThrow (TNode< Object > ctor, TNode< Number > size, FrameState frame_state)
TNode< JSArray > AllocateEmptyJSArray (ElementsKind kind, NativeContextRef native_context)
TNode< Number > NumberInc (TNode< Number > value)
TNode< Number > LoadMapElementsKind (TNode< Map > map)
template<typename T , typename U >
TNode< T > EnterMachineGraph (TNode< U > input, UseInfo use_info)
template<typename T , typename U >
TNode< T > ExitMachineGraph (TNode< U > input, MachineRepresentation output_representation, Type output_type)
void MaybeInsertMapChecks (MapInference *inference, bool has_stability_dependency)
TNode< Object > ConvertHoleToUndefined (TNode< Object > value, ElementsKind kind)
TryCatchBuilder0 Try (const VoidGenerator0 &try_body)
ForBuilder0 ForZeroUntil (TNode< Number > excluded_limit)
ForBuilder0 Forever (TNode< Number > initial_value, const StepFunction1 &step)
ForBuilder1 For1 (TNode< Number > initial_value, const ConditionFunction1 &cond, const StepFunction1 &step, TNode< Object > initial_arg0)
ForBuilder1 For1ZeroUntil (TNode< Number > excluded_limit, TNode< Object > initial_arg0)
void ThrowIfNotCallable (TNode< Object > maybe_callable, FrameState frame_state)
const FeedbackSource & feedback () const
int ArgumentCount () const
TNode< Object > Argument (int index) const
template<typename T >
TNode< T > ArgumentAs (int index) const
TNode< Object > ArgumentOrNaN (int index)
TNode< Object > ArgumentOrUndefined (int index)
TNode< Number > ArgumentOrZero (int index)
TNode< Context > ContextInput () const
FrameState FrameStateInput () const
CompilationDependencies * dependencies () const
Private Attributes
CompilationDependencies *const dependencies_
Node *const node_
Static Private Attributes
static constexpr bool kMarkLoopExits = true
Additional Inherited Members
Detailed Description
Definition at line 56 of file js-call-reducer.cc.
Member Typedef Documentation
ConditionFunction1
using v8::internal::compiler::JSCallReducerAssembler::ConditionFunction1 = std::function<TNode<Boolean>(TNode<Number>)>
Definition at line 233 of file js-call-reducer.cc.
For1BodyFunction
using v8::internal::compiler::JSCallReducerAssembler::For1BodyFunction = std::function<void(TNode<Number>, TNode<Object>*)>
Definition at line 297 of file js-call-reducer.cc.
StepFunction1
using v8::internal::compiler::JSCallReducerAssembler::StepFunction1 = std::function<TNode<Number>(TNode<Number>)>
Definition at line 234 of file js-call-reducer.cc.
Constructor & Destructor Documentation
JSCallReducerAssembler()
v8::internal::compiler::JSCallReducerAssembler::JSCallReducerAssembler (JSCallReducer * reducer, Node * node, Node * effect = nullptr, Node * control = nullptr) [inline]
Definition at line 60 of file js-call-reducer.cc.
      : JSGraphAssembler(
            reducer->broker(), reducer->JSGraphForGraphAssembler(),
            reducer->ZoneForGraphAssembler(), BranchSemantics::kJS,
            [reducer](Node* n) { reducer->RevisitForGraphAssembler(n); },
            kMarkLoopExits),
        dependencies_(reducer->dependencies()),
        node_(node) {
    InitializeEffectControl(
        effect ? effect : NodeProperties::GetEffectInput(node),
        control ? control : NodeProperties::GetControlInput(node));
    // Finish initializing the outermost catch scope.
    bool has_handler =
        NodeProperties::IsExceptionalCall(node, &outermost_handler_);
    outermost_catch_scope_.set_has_handler(has_handler);
  }
References v8::internal::kJS, and v8::internal::compiler::JSCallReducer::RevisitForGraphAssembler().
Member Function Documentation
AllocateEmptyJSArray()
TNode< JSArray > v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray (ElementsKind kind, NativeContextRef native_context)
Definition at line 900 of file js-call-reducer.cc.
                                                        {
  // TODO(jgruber): Port AllocationBuilder to JSGraphAssembler.
  MapRef map = native_context.GetInitialJSArrayMap(broker(), kind);
  AllocationBuilder ab(jsgraph(), broker(), effect(), control());
  ab.Allocate(map.instance_size(), AllocationType::kYoung, Type::Array());
  ab.Store(AccessBuilder::ForMap(), map);
  Node* empty_fixed_array = jsgraph()->EmptyFixedArrayConstant();
  ab.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
           empty_fixed_array);
  ab.Store(AccessBuilder::ForJSObjectElements(), empty_fixed_array);
  ab.Store(AccessBuilder::ForJSArrayLength(kind), jsgraph()->ZeroConstant());
  for (int i = 0; i < map.GetInObjectProperties(); ++i) {
    ab.Store(AccessBuilder::ForJSObjectInObjectProperty(map, i),
             jsgraph()->UndefinedConstant());
  }
  Node* result = ab.Finish();
  InitializeEffectControl(result, control());
  return TNode<JSArray>::UncheckedCast(result);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), v8::internal::compiler::JSGraphAssembler::broker(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectInObjectProperty(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::MapRef::GetInObjectProperties(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::GraphAssembler::InitializeEffectControl(), v8::internal::compiler::MapRef::instance_size(), v8::internal::compiler::JSGraphAssembler::jsgraph(), v8::internal::kYoung, v8::internal::native_context, v8::base::internal::result, v8::internal::compiler::AllocationBuilder::Store(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter().
Argument()
TNode<Object> v8::internal::compiler::JSCallReducerAssembler::Argument (int index) const [inline]
Definition at line 394 of file js-call-reducer.cc.
                                          {
    return TNode<Object>::UncheckedCast(JSCallNode{node_ptr()}.Argument(index));
  }
References v8::internal::index, node_ptr(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by ArgumentAs(), ArgumentOrNaN(), ArgumentOrUndefined(), ArgumentOrZero(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), ReduceMathBinary(), ReduceMathUnary(), ReduceStringPrototypeSlice(), and ReduceStringPrototypeSubstring().
ArgumentAs()
template<typename T >
TNode<T> v8::internal::compiler::JSCallReducerAssembler::ArgumentAs (int index) const [inline]
Definition at line 399 of file js-call-reducer.cc.
                                       {
    return TNode<T>::UncheckedCast(Argument(index));
  }
References Argument(), v8::internal::index, and v8::internal::TNode< T >::UncheckedCast().
ArgumentCount()
int v8::internal::compiler::JSCallReducerAssembler::ArgumentCount () const [inline]
Definition at line 392 of file js-call-reducer.cc.
{ return JSCallNode{node_ptr()}.ArgumentCount(); }
References node_ptr().
Referenced by ArgumentOrNaN(), ArgumentOrUndefined(), ArgumentOrZero(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), and ReduceStringPrototypeSlice().
ArgumentOrNaN()
TNode<Object> v8::internal::compiler::JSCallReducerAssembler::ArgumentOrNaN (int index) [inline]
Definition at line 403 of file js-call-reducer.cc.
                                         {
    return TNode<Object>::UncheckedCast(
        ArgumentCount() > index ? Argument(index) : NaNConstant());
  }
References Argument(), ArgumentCount(), v8::internal::index, and v8::internal::TNode< T >::UncheckedCast().
Referenced by ReduceMathBinary().
ArgumentOrUndefined()
TNode<Object> v8::internal::compiler::JSCallReducerAssembler::ArgumentOrUndefined (int index) [inline]
Definition at line 408 of file js-call-reducer.cc.
                                               {
    return TNode<Object>::UncheckedCast(
        ArgumentCount() > index ? Argument(index) : UndefinedConstant());
  }
References Argument(), ArgumentCount(), v8::internal::index, v8::internal::TNode< T >::UncheckedCast(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), ReduceStringPrototypeEndsWith(), ReduceStringPrototypeSlice(), ReduceStringPrototypeStartsWith(), and ReduceStringPrototypeSubstring().
ArgumentOrZero()
TNode<Number> v8::internal::compiler::JSCallReducerAssembler::ArgumentOrZero (int index) [inline]
Definition at line 413 of file js-call-reducer.cc.
                                          {
    return TNode<Number>::UncheckedCast(
        ArgumentCount() > index ? Argument(index) : ZeroConstant());
  }
References Argument(), ArgumentCount(), v8::internal::index, and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes(), ReduceStringPrototypeCharAt(), ReduceStringPrototypeCharCodeAt(), and ReduceStringPrototypeStartsWith().
Call4()
TNode< Object > v8::internal::compiler::JSCallReducerAssembler::Call4 (const Callable & callable, TNode< Context > context, TNode< Object > arg0, TNode< Object > arg1, TNode< Object > arg2, TNode< Object > arg3)
Definition at line 837 of file js-call-reducer.cc.
                                                                {
  // TODO(jgruber): Make this more generic. Currently it's fitted to its single
  // callsite.
  CallDescriptor* desc = Linkage::GetStubCallDescriptor(
      graph()->zone(), callable.descriptor(),
      callable.descriptor().GetStackParameterCount(), CallDescriptor::kNoFlags,
      Operator::kEliminatable);
  return TNode<Object>::UncheckedCast(Call(desc, HeapConstant(callable.code()),
                                           arg0, arg1, arg2, arg3, context));
}
References v8::internal::compiler::GraphAssembler::Call(), v8::internal::Callable::code(), v8::internal::Callable::descriptor(), v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::HeapConstant(), v8::internal::compiler::Operator::kEliminatable, v8::internal::compiler::CallDescriptor::kNoFlags, and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes().
CheckBounds()
TNode< Number > v8::internal::compiler::JSCallReducerAssembler::CheckBounds (TNode< Object > value, TNode< Number > limit, CheckBoundsFlags flags = {})
Definition at line 812 of file js-call-reducer.cc.
                                                                          {
  return AddNode<Number>(
      graph()->NewNode(simplified()->CheckBounds(feedback(), flags), value,
                       limit, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), feedback(), v8::internal::flags, v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), ReduceStringPrototypeCharAt(), ReduceStringPrototypeCharCodeAt(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::SafeLoadElement().
CheckNumber()
TNode< Number > v8::internal::compiler::JSCallReducerAssembler::CheckNumber (TNode< Object > value)
Definition at line 802 of file js-call-reducer.cc.
                                                                     {
  return AddNode<Number>(graph()->NewNode(simplified()->CheckNumber(feedback()),
                                          value, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), feedback(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush().
CheckSmi()
TNode< Smi > v8::internal::compiler::JSCallReducerAssembler::CheckSmi (TNode< Object > value)
Definition at line 797 of file js-call-reducer.cc.
                                                               {
  return AddNode<Smi>(graph()->NewNode(simplified()->CheckSmi(feedback()),
                                       value, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), feedback(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), ReduceStringPrototypeCharAt(), ReduceStringPrototypeCharCodeAt(), ReduceStringPrototypeEndsWith(), ReduceStringPrototypeSlice(), ReduceStringPrototypeStartsWith(), and ReduceStringPrototypeSubstring().
CheckString()
TNode< String > v8::internal::compiler::JSCallReducerAssembler::CheckString (TNode< Object > value)
Definition at line 807 of file js-call-reducer.cc.
                                                                     {
  return AddNode<String>(graph()->NewNode(simplified()->CheckString(feedback()),
                                          value, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), feedback(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::simplified(), and v8::internal::value.
Referenced by ReduceStringPrototypeCharAt(), ReduceStringPrototypeCharCodeAt(), ReduceStringPrototypeEndsWith(), ReduceStringPrototypeSlice(), ReduceStringPrototypeStartsWith(), and ReduceStringPrototypeSubstring().
ContextInput()
TNode<Context> v8::internal::compiler::JSCallReducerAssembler::ContextInput () const [inline]
Definition at line 418 of file js-call-reducer.cc.
                                      {
    return TNode<Context>::UncheckedCast(
        NodeProperties::GetContextInput(node_));
  }
References v8::internal::compiler::NodeProperties::GetContextInput(), node_, and v8::internal::TNode< T >::UncheckedCast().
Referenced by CreateArrayNoThrow(), JSCall3(), JSCall4(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor(), v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength(), and ThrowIfNotCallable().
ConvertHoleToUndefined()
TNode<Object> v8::internal::compiler::JSCallReducerAssembler::ConvertHoleToUndefined (TNode< Object > value, ElementsKind kind) [inline]
Definition at line 175 of file js-call-reducer.cc.
                                                                               {
    DCHECK(IsHoleyElementsKind(kind));
    if (kind == HOLEY_DOUBLE_ELEMENTS) {
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
      return AddNode<Number>(graph()->NewNode(
          simplified()->ChangeFloat64OrUndefinedOrHoleToTagged(), value));
#else
      return AddNode<Number>(
          graph()->NewNode(simplified()->ChangeFloat64HoleToTagged(), value));
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    }
    return ConvertTaggedHoleToUndefined(value);
  }
References v8::internal::compiler::JSGraphAssembler::ConvertTaggedHoleToUndefined(), v8::internal::DCHECK(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::IsHoleyElementsKind(), v8::internal::compiler::JSGraphAssembler::simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind().
CopyNode()
TNode< Object > v8::internal::compiler::JSCallReducerAssembler::CopyNode ()
Definition at line 884 of file js-call-reducer.cc.
                                               {
  return MayThrow(_ {
    Node* copy = graph()->CloneNode(node_ptr());
    NodeProperties::ReplaceEffectInput(copy, effect());
    NodeProperties::ReplaceControlInput(copy, control());
    return AddNode<Object>(copy);
  });
}
References _, v8::internal::compiler::TFGraph::CloneNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::MayThrow(), node_ptr(), v8::internal::compiler::NodeProperties::ReplaceControlInput(), and v8::internal::compiler::NodeProperties::ReplaceEffectInput().
Referenced by ReduceJSCallMathMinMaxWithArrayLike(), and ReduceJSCallWithArrayLikeOrSpreadOfEmpty().
CreateArrayNoThrow()
TNode< JSArray > v8::internal::compiler::JSCallReducerAssembler::CreateArrayNoThrow (TNode< Object > ctor, TNode< Number > size, FrameState frame_state)
Definition at line 893 of file js-call-reducer.cc.
                                                                    {
  return AddNode<JSArray>(graph()->NewNode(
      javascript()->CreateArray(1, std::nullopt, feedback()), ctor, ctor, size,
      ContextInput(), frame_state, effect(), control()));
}
References ContextInput(), v8::internal::compiler::GraphAssembler::control(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::CreateArray(), v8::internal::compiler::GraphAssembler::effect(), feedback(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::javascript(), and size().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap().
dependencies()
CompilationDependencies* v8::internal::compiler::JSCallReducerAssembler::dependencies () const [inline]
Definition at line 427 of file js-call-reducer.cc.
{ return dependencies_; }
References dependencies_.
EnterMachineGraph()
template<typename T , typename U >
TNode<T> v8::internal::compiler::JSCallReducerAssembler::EnterMachineGraph (TNode< U > input, UseInfo use_info) [inline]
Definition at line 151 of file js-call-reducer.cc.
                                                               {
    return AddNode<T>(
        graph()->NewNode(common()->EnterMachineGraph(use_info), input));
  }
References v8::internal::compiler::GraphAssembler::common(), and v8::internal::compiler::GraphAssembler::graph().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor().
ExitMachineGraph()
template<typename T , typename U >
TNode<T> v8::internal::compiler::JSCallReducerAssembler::ExitMachineGraph (TNode< U > input, MachineRepresentation output_representation, Type output_type) [inline]
Definition at line 157 of file js-call-reducer.cc.
                                              {
    return AddNode<T>(graph()->NewNode(
        common()->ExitMachineGraph(output_representation, output_type), input));
  }
References v8::internal::compiler::GraphAssembler::common(), and v8::internal::compiler::GraphAssembler::graph().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor().
feedback()
const FeedbackSource& v8::internal::compiler::JSCallReducerAssembler::feedback () const [inline]
Definition at line 387 of file js-call-reducer.cc.
                                         {
    CallParameters const& p = CallParametersOf(node_ptr()->op());
    return p.feedback();
  }
References v8::internal::compiler::CallParametersOf(), v8::internal::compiler::CallParameters::feedback(), and node_ptr().
Referenced by CheckBounds(), CheckNumber(), CheckSmi(), CheckString(), CreateArrayNoThrow(), v8::internal::compiler::FastApiCallReducerAssembler::FastApiCall(), MaybeInsertMapChecks(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), and SpeculativeToNumber().
For1()
ForBuilder1 v8::internal::compiler::JSCallReducerAssembler::For1 (TNode< Number > initial_value, const ConditionFunction1 & cond, const StepFunction1 & step, TNode< Object > initial_arg0) [inline]
Definition at line 359 of file js-call-reducer.cc.
                                                                          {
    return {this, initial_value, cond, step, initial_arg0};
  }
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
For1ZeroUntil()
ForBuilder1 v8::internal::compiler::JSCallReducerAssembler::For1ZeroUntil (TNode< Number > excluded_limit, TNode< Object > initial_arg0) [inline]
Definition at line 364 of file js-call-reducer.cc.
                                                        {
    TNode<Number> initial_value = ZeroConstant();
    auto cond = [=, this](TNode<Number> i) {
      return NumberLessThan(i, excluded_limit);
    };
    auto step = [=, this](TNode<Number> i) {
      return NumberAdd(i, OneConstant());
    };
    return {this, initial_value, cond, step, initial_arg0};
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::JSGraphAssembler::NumberAdd(), and v8::internal::compiler::JSGraphAssembler::NumberLessThan().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter().
Forever()
ForBuilder0 v8::internal::compiler::JSCallReducerAssembler::Forever (TNode< Number > initial_value, const StepFunction1 & step) [inline]
Definition at line 292 of file js-call-reducer.cc.
                                                                              {
    return {this, initial_value,
            [=, this](TNode<Number>) { return TrueConstant(); }, step};
  }
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
ForZeroUntil()
ForBuilder0 v8::internal::compiler::JSCallReducerAssembler::ForZeroUntil (TNode< Number > excluded_limit) [inline]
Definition at line 281 of file js-call-reducer.cc.
                                                         {
    TNode<Number> initial_value = ZeroConstant();
    auto cond = [=, this](TNode<Number> i) {
      return NumberLessThan(i, excluded_limit);
    };
    auto step = [=, this](TNode<Number> i) {
      return NumberAdd(i, OneConstant());
    };
    return {this, initial_value, cond, step};
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::JSGraphAssembler::NumberAdd(), and v8::internal::compiler::JSGraphAssembler::NumberLessThan().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), ReduceStringPrototypeEndsWith(), and ReduceStringPrototypeStartsWith().
FrameStateInput()
FrameState v8::internal::compiler::JSCallReducerAssembler::FrameStateInput () const [inline]
Definition at line 423 of file js-call-reducer.cc.
                                     {
    return FrameState(NodeProperties::GetFrameStateInput(node_));
  }
References v8::internal::compiler::NodeProperties::GetFrameStateInput(), and node_.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), and v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor().
JSCall3()
TNode< Object > v8::internal::compiler::JSCallReducerAssembler::JSCall3 (TNode< Object > function, TNode< Object > this_arg, TNode< Object > arg0, TNode< Object > arg1, TNode< Object > arg2, FrameState frame_state)
Definition at line 851 of file js-call-reducer.cc.
                                                                    {
  JSCallNode n(node_ptr());
  CallParameters const& p = n.Parameters();
  return MayThrow(_ {
    return AddNode<Object>(graph()->NewNode(
        javascript()->Call(JSCallNode::ArityForArgc(3), p.frequency(),
                           p.feedback(), ConvertReceiverMode::kAny,
                           p.speculation_mode(),
                           CallFeedbackRelation::kUnrelated),
        function, this_arg, arg0, arg1, arg2, n.feedback_vector(),
        ContextInput(), frame_state, effect(), control()));
  });
}
References _, v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::compiler::GraphAssembler::Call(), ContextInput(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::JSCallOrConstructNode::feedback_vector(), v8::internal::compiler::CallParameters::frequency(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::javascript(), v8::internal::kAny, v8::internal::compiler::kUnrelated, v8::internal::compiler::JSGraphAssembler::MayThrow(), node_ptr(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), and v8::internal::compiler::CallParameters::speculation_mode().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap().
JSCall4()
TNode< Object > v8::internal::compiler::JSCallReducerAssembler::JSCall4 (TNode< Object > function, TNode< Object > this_arg, TNode< Object > arg0, TNode< Object > arg1, TNode< Object > arg2, TNode< Object > arg3, FrameState frame_state)
Definition at line 867 of file js-call-reducer.cc.
                            {
  JSCallNode n(node_ptr());
  CallParameters const& p = n.Parameters();
  return MayThrow(_ {
    return AddNode<Object>(graph()->NewNode(
        javascript()->Call(JSCallNode::ArityForArgc(4), p.frequency(),
                           p.feedback(), ConvertReceiverMode::kAny,
                           p.speculation_mode(),
                           CallFeedbackRelation::kUnrelated),
        function, this_arg, arg0, arg1, arg2, arg3, n.feedback_vector(),
        ContextInput(), frame_state, effect(), control()));
  });
}
References _, v8::internal::compiler::JSCallOrConstructNode::ArityForArgc(), v8::internal::compiler::GraphAssembler::Call(), ContextInput(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::JSCallOrConstructNode::feedback_vector(), v8::internal::compiler::CallParameters::frequency(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::javascript(), v8::internal::kAny, v8::internal::compiler::kUnrelated, v8::internal::compiler::JSGraphAssembler::MayThrow(), node_ptr(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), and v8::internal::compiler::CallParameters::speculation_mode().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
LoadMapElementsKind()
TNode< Number > v8::internal::compiler::JSCallReducerAssembler::LoadMapElementsKind (TNode< Map > map)
Definition at line 922 of file js-call-reducer.cc.
                                                                        {
  TNode<Number> bit_field2 =
      LoadField<Number>(AccessBuilder::ForMapBitField2(), map);
  return NumberShiftRightLogical(
      NumberBitwiseAnd(bit_field2,
                       NumberConstant(Map::Bits2::ElementsKindBits::kMask)),
      NumberConstant(Map::Bits2::ElementsKindBits::kShift));
}
References v8::internal::bit_field2, v8::internal::compiler::AccessBuilder::ForMapBitField2(), v8::internal::compiler::JSGraphAssembler::NumberBitwiseAnd(), v8::internal::compiler::JSGraphAssembler::NumberConstant(), and v8::internal::compiler::JSGraphAssembler::NumberShiftRightLogical().
Referenced by ReduceJSCallMathMinMaxWithArrayLike().
MaybeInsertMapChecks()
void v8::internal::compiler::JSCallReducerAssembler::MaybeInsertMapChecks (MapInference * inference, bool has_stability_dependency) [inline]
Definition at line 164 of file js-call-reducer.cc.
                                                           {
    // TODO(jgruber): Implement MapInference::InsertMapChecks in graph
    // assembler.
    if (!has_stability_dependency) {
      Effect e = effect();
      inference->InsertMapChecks(jsgraph(), &e, Control{control()}, feedback());
      InitializeEffectControl(e, control());
    }
  }
References v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), feedback(), v8::internal::compiler::GraphAssembler::InitializeEffectControl(), v8::internal::compiler::MapInference::InsertMapChecks(), and v8::internal::compiler::JSGraphAssembler::jsgraph().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
node_ptr()
Node* v8::internal::compiler::JSCallReducerAssembler::node_ptr () const [inline]
Definition at line 105 of file js-call-reducer.cc.
{ return node_; }
References node_.
Referenced by Argument(), ArgumentCount(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseExecutor(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseReject(), v8::internal::compiler::PromiseBuiltinReducerAssembler::ConstructArity(), CopyNode(), feedback(), JSCall3(), JSCall4(), v8::internal::compiler::PromiseBuiltinReducerAssembler::NewTargetInput(), ReceiverInputAs(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), ReduceJSCallMathMinMaxWithArrayLike(), ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor(), v8::internal::compiler::JSCallReducer::ReplaceWithSubgraph(), TargetInput(), and v8::internal::compiler::PromiseBuiltinReducerAssembler::TargetInput().
NumberInc()
TNode<Number> v8::internal::compiler::JSCallReducerAssembler::NumberInc (TNode< Number > value) [inline]
Definition at line 144 of file js-call-reducer.cc.
                                               {
    return NumberAdd(value, OneConstant());
  }
References v8::internal::compiler::JSGraphAssembler::NumberAdd(), and v8::internal::value.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind().
ReceiverInput()
TNode<Object> v8::internal::compiler::JSCallReducerAssembler::ReceiverInput () const [inline]
Definition at line 103 of file js-call-reducer.cc.
{ return ReceiverInputAs<Object>(); }
Referenced by ReduceStringPrototypeCharAt(), ReduceStringPrototypeCharCodeAt(), ReduceStringPrototypeEndsWith(), ReduceStringPrototypeSlice(), ReduceStringPrototypeStartsWith(), and ReduceStringPrototypeSubstring().
ReceiverInputAs()
template<typename T >
TNode<T> v8::internal::compiler::JSCallReducerAssembler::ReceiverInputAs () const [inline]
Definition at line 99 of file js-call-reducer.cc.
                                   {
    return TNode<T>::UncheckedCast(JSCallNode{node_ptr()}.receiver());
  }
References node_ptr(), and v8::internal::TNode< T >::UncheckedCast().
ReduceJSCallMathMinMaxWithArrayLike()
TNode< Object > v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike (Builtin builtin)
Definition at line 1323 of file js-call-reducer.cc.
                     {
  JSCallWithArrayLikeNode n(node_ptr());
  TNode<Object> arguments_list = n.Argument(0);
  auto call_builtin = MakeLabel();
  auto done = MakeLabel(MachineRepresentation::kTagged);
  // Check if {arguments_list} is a JSArray.
  GotoIf(ObjectIsSmi(arguments_list), &call_builtin);
  TNode<Map> arguments_list_map =
      LoadField<Map>(AccessBuilder::ForMap(),
                     TNode<HeapObject>::UncheckedCast(arguments_list));
  TNode<Number> arguments_list_instance_type = LoadField<Number>(
      AccessBuilder::ForMapInstanceType(), arguments_list_map);
  auto check_instance_type =
      NumberEqual(arguments_list_instance_type, NumberConstant(JS_ARRAY_TYPE));
  GotoIfNot(check_instance_type, &call_builtin);
  // Check if {arguments_list} has PACKED_DOUBLE_ELEMENTS.
  TNode<Number> arguments_list_elements_kind =
      LoadMapElementsKind(arguments_list_map);
  auto check_element_kind = NumberEqual(arguments_list_elements_kind,
                                        NumberConstant(PACKED_DOUBLE_ELEMENTS));
  GotoIfNot(check_element_kind, &call_builtin);
  // If {arguments_list} is a JSArray with PACKED_DOUBLE_ELEMENTS, calculate the
  // result with inlined loop.
  TNode<JSArray> array_arguments_list =
      TNode<JSArray>::UncheckedCast(arguments_list);
  Goto(&done, builtin == Builtin::kMathMax
                  ? DoubleArrayMax(array_arguments_list)
                  : DoubleArrayMin(array_arguments_list));
  // Otherwise, call BuiltinMathMin/Max as usual.
  Bind(&call_builtin);
  TNode<Object> call = CopyNode();
  CallParameters const& p = n.Parameters();
  // Set SpeculationMode to kDisallowSpeculation to avoid infinite
  // recursion.
  NodeProperties::ChangeOp(
      call, javascript()->CallWithArrayLike(
                p.frequency(), p.feedback(),
                SpeculationMode::kDisallowSpeculation, p.feedback_relation()));
  Goto(&done, call);
  Bind(&done);
  return done.PhiAt<Object>(0);
}
References v8::internal::compiler::JSCallOrConstructNode::Argument(), v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::NodeProperties::ChangeOp(), CopyNode(), v8::internal::compiler::JSGraphAssembler::DoubleArrayMax(), v8::internal::compiler::JSGraphAssembler::DoubleArrayMin(), v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::CallParameters::feedback_relation(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::AccessBuilder::ForMapInstanceType(), v8::internal::compiler::CallParameters::frequency(), v8::internal::compiler::GraphAssembler::Goto(), v8::internal::compiler::GraphAssembler::GotoIf(), v8::internal::compiler::GraphAssembler::GotoIfNot(), v8::internal::compiler::JSGraphAssembler::javascript(), v8::internal::kDisallowSpeculation, v8::internal::kTagged, LoadMapElementsKind(), v8::internal::compiler::GraphAssembler::MakeLabel(), node_ptr(), v8::internal::compiler::JSGraphAssembler::NumberConstant(), v8::internal::compiler::JSGraphAssembler::NumberEqual(), v8::internal::compiler::JSGraphAssembler::ObjectIsSmi(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::JSCallReducer::ReduceJSCallMathMinMaxWithArrayLike().
ReduceJSCallWithArrayLikeOrSpreadOfEmpty()
TNode< Object > v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty (std::unordered_set< Node * > * generated_calls_with_array_like_or_spread)
Definition at line 5342 of file js-call-reducer.cc.
                                                                        {
  DCHECK_EQ(generated_calls_with_array_like_or_spread->count(node_ptr()), 0);
  JSCallWithArrayLikeOrSpreadNode n(node_ptr());
  CallParameters const& p = n.Parameters();
  TNode<Object> arguments_list = n.LastArgument();
  DCHECK_EQ(static_cast<Node*>(arguments_list)->opcode(),
            IrOpcode::kJSCreateEmptyLiteralArray);
  // Check that arguments_list's prototype is still an array prototype.
  TNode<Map> map = LoadMap(TNode<HeapObject>::UncheckedCast(arguments_list));
  TNode<HeapObject> proto = TNode<HeapObject>::UncheckedCast(
      LoadField(AccessBuilder::ForMapPrototype(), map));
  TNode<HeapObject> initial_array_prototype =
      HeapConstant(broker()
                       ->target_native_context()
                       .initial_array_prototype(broker())
                       .object());
  TNode<Boolean> check = ReferenceEqual(proto, initial_array_prototype);
  CheckIf(check, DeoptimizeReason::kWrongMap, p.feedback());
  // Turn the JSCallWithArrayLike or JSCallWithSpread roughly into:
  //
  // "arguments_list array is still empty?"
  // |
  // |
  // Branch
  // / \
  // / \
  // IfTrue IfFalse
  // | |
  // | |
  // JSCall JSCallWithArrayLike/JSCallWithSpread
  // \ /
  // \ /
  // Merge
  TNode<Number> length = TNode<Number>::UncheckedCast(
      LoadField(AccessBuilder::ForJSArrayLength(NO_ELEMENTS), arguments_list));
  return SelectIf<Object>(NumberEqual(length, ZeroConstant()))
      .Then([&]() {
        TNode<Object> call = CopyNode();
        static_cast<Node*>(call)->RemoveInput(n.LastArgumentIndex());
        NodeProperties::ChangeOp(
            call, javascript()->Call(p.arity() - 1, p.frequency(), p.feedback(),
                                     p.convert_mode(), p.speculation_mode(),
                                     p.feedback_relation()));
        return call;
      })
      .Else([&]() {
        TNode<Object> call = CopyNode();
        generated_calls_with_array_like_or_spread->insert(call);
        return call;
      })
      .ExpectFalse()
      .Value();
}
References v8::internal::compiler::CallParameters::arity(), v8::internal::compiler::JSGraphAssembler::broker(), v8::internal::compiler::GraphAssembler::Call(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::JSGraphAssembler::CheckIf(), v8::internal::compiler::CallParameters::convert_mode(), CopyNode(), DCHECK_EQ, v8::internal::compiler::CallParameters::feedback(), v8::internal::compiler::CallParameters::feedback_relation(), v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::AccessBuilder::ForMapPrototype(), v8::internal::compiler::CallParameters::frequency(), v8::internal::compiler::JSGraphAssembler::HeapConstant(), v8::internal::compiler::JSGraphAssembler::javascript(), v8::internal::compiler::JSCallOrConstructNode::LastArgument(), v8::internal::compiler::JSCallOrConstructNode::LastArgumentIndex(), v8::internal::length, v8::internal::compiler::JSGraphAssembler::LoadField(), v8::internal::compiler::JSGraphAssembler::LoadMap(), v8::internal::NO_ELEMENTS, node_ptr(), v8::internal::compiler::JSGraphAssembler::NumberEqual(), v8::internal::compiler::JSCallNodeBase< kOpcodes >::Parameters(), v8::internal::compiler::JSGraphAssembler::ReferenceEqual(), v8::internal::compiler::CallParameters::speculation_mode(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpread().
ReduceMathBinary()
TNode< Object > v8::internal::compiler::JSCallReducerAssembler::ReduceMathBinary (const Operator * op)
Definition at line 937 of file js-call-reducer.cc.
                                                                         {
  TNode<Object> left = Argument(0);
  TNode<Object> right = ArgumentOrNaN(1);
  TNode<Number> left_number = SpeculativeToNumber(left);
  TNode<Number> right_number = SpeculativeToNumber(right);
  return TNode<Object>::UncheckedCast(
      graph()->NewNode(op, left_number, right_number));
}
References Argument(), ArgumentOrNaN(), v8::internal::compiler::GraphAssembler::graph(), SpeculativeToNumber(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::JSCallReducer::ReduceMathBinary().
ReduceMathUnary()
TNode< Object > v8::internal::compiler::JSCallReducerAssembler::ReduceMathUnary (const Operator * op)
Definition at line 931 of file js-call-reducer.cc.
                                                                        {
  TNode<Object> input = Argument(0);
  TNode<Number> input_as_number = SpeculativeToNumber(input);
  return TNode<Object>::UncheckedCast(graph()->NewNode(op, input_as_number));
}
References Argument(), v8::internal::compiler::GraphAssembler::graph(), SpeculativeToNumber(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::JSCallReducer::ReduceMathUnary().
ReduceStringPrototypeCharAt() [1/2]
TNode< String > v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt (SpeculationMode speculation_mode)
Definition at line 1190 of file js-call-reducer.cc.
                                      {
  TNode<Object> receiver = ReceiverInput();
  TNode<Object> index = ArgumentOrZero(0);
  TNode<String> receiver_string = CheckString(receiver);
  TNode<Number> length = StringLength(receiver_string);
  if (speculation_mode == SpeculationMode::kDisallowBoundsCheckSpeculation) {
    TNode<Number> index_smi = CheckSmi(index);
    return SelectIf<String>(NumberLessThan(index_smi, ZeroConstant()))
        .Then(_ { return EmptyStringConstant(); })
        .Else(_ {
          return SelectIf<String>(NumberLessThan(index_smi, length))
              .Then(_ {
                return StringFromSingleCharCode(
                    TNode<Number>::UncheckedCast(StringCharCodeAt(
                        receiver_string,
                        TypeGuard(Type::Unsigned32(), index_smi))));
              })
              .Else(_ { return EmptyStringConstant(); })
              .ExpectTrue()
              .Value();
        })
        .ExpectFalse()
        .Value();
  }
  DCHECK_EQ(speculation_mode, SpeculationMode::kAllowSpeculation);
  TNode<Number> bounded_index = CheckBounds(index, length);
  return StringFromSingleCharCode(TNode<Number>::UncheckedCast(
      StringCharCodeAt(receiver_string, bounded_index)));
}
References _, ArgumentOrZero(), CheckBounds(), CheckSmi(), CheckString(), DCHECK_EQ, v8::internal::index, v8::internal::kAllowSpeculation, v8::internal::kDisallowBoundsCheckSpeculation, v8::internal::length, v8::internal::compiler::JSGraphAssembler::NumberLessThan(), ReceiverInput(), v8::internal::compiler::JSGraphAssembler::StringCharCodeAt(), v8::internal::compiler::JSGraphAssembler::StringFromSingleCharCode(), v8::internal::compiler::JSGraphAssembler::StringLength(), and v8::internal::compiler::GraphAssembler::TypeGuard().
Referenced by v8::internal::compiler::JSCallReducer::ReduceStringPrototypeCharAt().
ReduceStringPrototypeCharAt() [2/2]
TNode< String > v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt (StringRef s, uint32_t index)
Definition at line 1163 of file js-call-reducer.cc.
                                 {
  DCHECK(s.IsContentAccessible());
  if (s.IsOneByteRepresentation()) {
    OptionalObjectRef elem = s.GetCharAsStringOrUndefined(broker(), index);
    TNode<String> elem_string =
        elem.has_value()
            ? TNode<String>::UncheckedCast(
                  jsgraph()->ConstantNoHole(elem.value(), broker()))
            : EmptyStringConstant();
    return elem_string;
  } else {
    const uint32_t length = static_cast<uint32_t>(s.length());
    if (index >= length) return EmptyStringConstant();
    Handle<SeqTwoByteString> flat = broker()->CanonicalPersistentHandle(
        broker()
            ->local_isolate_or_isolate()
            ->factory()
            ->NewRawTwoByteString(1, AllocationType::kOld)
            .ToHandleChecked());
    flat->SeqTwoByteStringSet(0, s.GetChar(broker(), index).value());
    TNode<String> two_byte_elem =
        TNode<String>::UncheckedCast(jsgraph()->HeapConstantNoHole(flat));
    return two_byte_elem;
  }
}
References v8::internal::compiler::JSGraphAssembler::broker(), v8::internal::compiler::JSHeapBroker::CanonicalPersistentHandle(), v8::internal::DCHECK(), v8::internal::compiler::StringRef::GetChar(), v8::internal::compiler::StringRef::GetCharAsStringOrUndefined(), v8::internal::compiler::HeapConstantNoHole(), v8::internal::index, v8::internal::compiler::StringRef::IsContentAccessible(), v8::internal::compiler::StringRef::IsOneByteRepresentation(), v8::internal::compiler::JSGraphAssembler::jsgraph(), v8::internal::kOld, v8::internal::length, v8::internal::compiler::StringRef::length(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
ReduceStringPrototypeCharCodeAt()
TNode< Number > v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharCodeAt (SpeculationMode speculation_mode)
Definition at line 1224 of file js-call-reducer.cc.
                                      {
  TNode<Object> receiver = ReceiverInput();
  TNode<Object> index = ArgumentOrZero(0);
  TNode<String> receiver_string = CheckString(receiver);
  TNode<Number> length = StringLength(receiver_string);
  if (speculation_mode == SpeculationMode::kDisallowBoundsCheckSpeculation) {
    TNode<Number> index_smi = CheckSmi(index);
    return SelectIf<Number>(NumberLessThan(index_smi, ZeroConstant()))
        .Then(_ { return NaNConstant(); })
        .Else(_ {
          return SelectIf<Number>(NumberLessThan(index_smi, length))
              .Then(_ {
                return TNode<Number>::UncheckedCast(StringCharCodeAt(
                    receiver_string, TypeGuard(Type::Unsigned32(), index_smi)));
              })
              .Else(_ { return NaNConstant(); })
              .ExpectTrue()
              .Value();
        })
        .ExpectFalse()
        .Value();
  }
  DCHECK_EQ(speculation_mode, SpeculationMode::kAllowSpeculation);
  TNode<Number> bounded_index = CheckBounds(index, length);
  return TNode<Number>::UncheckedCast(
      (StringCharCodeAt(receiver_string, bounded_index)));
}
References _, ArgumentOrZero(), CheckBounds(), CheckSmi(), CheckString(), DCHECK_EQ, v8::internal::index, v8::internal::kAllowSpeculation, v8::internal::kDisallowBoundsCheckSpeculation, v8::internal::length, v8::internal::compiler::JSGraphAssembler::NumberLessThan(), ReceiverInput(), v8::internal::compiler::JSGraphAssembler::StringCharCodeAt(), v8::internal::compiler::JSGraphAssembler::StringLength(), v8::internal::compiler::GraphAssembler::TypeGuard(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStringCharCodeAt().
ReduceStringPrototypeEndsWith() [1/2]
TNode< Boolean > v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith ()
Definition at line 1112 of file js-call-reducer.cc.
                                                                     {
  TNode<Object> receiver = ReceiverInput();
  TNode<Object> search_string = ArgumentOrUndefined(0);
  TNode<Object> end_position = ArgumentOrUndefined(1);
  TNode<Number> zero = ZeroConstant();
  TNode<String> receiver_string = CheckString(receiver);
  TNode<Number> length = StringLength(receiver_string);
  TNode<String> search_element_string = CheckString(search_string);
  TNode<Number> search_string_length = StringLength(search_element_string);
  TNode<Number> clamped_end =
      SelectIf<Number>(IsUndefined(end_position))
          .Then(_ { return length; })
          .Else(_ {
            return NumberMin(NumberMax(CheckSmi(end_position), zero), length);
          })
          .ExpectTrue()
          .Value();
  TNode<Number> start = NumberSubtract(clamped_end, search_string_length);
  auto out = MakeLabel(MachineRepresentation::kTagged);
  TNode<Boolean> search_string_too_long = NumberLessThan(start, zero);
  GotoIf(search_string_too_long, &out, BranchHint::kFalse, FalseConstant());
  ForZeroUntil(search_string_length).Do([&](TNode<Number> k) {
    TNode<Number> receiver_string_position = TNode<Number>::UncheckedCast(
        TypeGuard(Type::UnsignedSmall(), NumberAdd(k, start)));
    Node* receiver_string_char =
        StringCharCodeAt(receiver_string, receiver_string_position);
    if (!v8_flags.turbo_loop_variable) {
      // Without loop variable analysis, Turbofan's typer is unable to derive a
      // sufficiently precise type here. This is not a soundness problem, but
      // triggers graph verification errors. So we only insert the TypeGuard if
      // necessary.
      k = TypeGuard(Type::Unsigned32(), k);
    }
    Node* search_string_char = StringCharCodeAt(search_element_string, k);
    auto is_equal = graph()->NewNode(simplified()->NumberEqual(),
                                     receiver_string_char, search_string_char);
    GotoIfNot(is_equal, &out, FalseConstant());
  });
  Goto(&out, TrueConstant());
  Bind(&out);
  return out.PhiAt<Boolean>(0);
}
References _, ArgumentOrUndefined(), v8::internal::compiler::GraphAssembler::Bind(), CheckSmi(), CheckString(), v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::Do(), ForZeroUntil(), v8::internal::compiler::GraphAssembler::Goto(), v8::internal::compiler::GraphAssembler::GotoIf(), v8::internal::compiler::GraphAssembler::GotoIfNot(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::kFalse, v8::internal::kTagged, v8::internal::length, v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::JSGraphAssembler::NumberAdd(), v8::internal::compiler::JSGraphAssembler::NumberEqual(), v8::internal::compiler::JSGraphAssembler::NumberLessThan(), v8::internal::compiler::JSGraphAssembler::NumberMax(), v8::internal::compiler::JSGraphAssembler::NumberMin(), v8::internal::compiler::JSGraphAssembler::NumberSubtract(), ReceiverInput(), v8::internal::compiler::JSGraphAssembler::simplified(), v8::internal::compiler::GraphAssembler::start(), v8::internal::compiler::JSGraphAssembler::StringCharCodeAt(), v8::internal::compiler::JSGraphAssembler::StringLength(), v8::internal::compiler::GraphAssembler::TypeGuard(), v8::internal::TNode< T >::UncheckedCast(), v8::internal::compiler::Type::UnsignedSmall(), v8::internal::v8_flags, and v8::internal::zero.
Referenced by v8::internal::compiler::JSCallReducer::ReduceStringPrototypeEndsWith().
ReduceStringPrototypeEndsWith() [2/2]
TNode< Boolean > v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith (StringRef search_element_string)
Definition at line 1064 of file js-call-reducer.cc.
                                     {
  DCHECK(search_element_string.IsContentAccessible());
  TNode<Object> receiver = ReceiverInput();
  TNode<Object> end_position = ArgumentOrUndefined(1);
  TNode<Number> zero = ZeroConstant();
  TNode<String> receiver_string = CheckString(receiver);
  TNode<Number> length = StringLength(receiver_string);
  int search_string_length = search_element_string.length();
  DCHECK_LE(search_string_length, JSCallReducer::kMaxInlineMatchSequence);
  TNode<Number> clamped_end =
      SelectIf<Number>(IsUndefined(end_position))
          .Then(_ { return length; })
          .Else(_ {
            return NumberMin(NumberMax(CheckSmi(end_position), zero), length);
          })
          .ExpectTrue()
          .Value();
  TNode<Number> start =
      NumberSubtract(clamped_end, NumberConstant(search_string_length));
  auto out = MakeLabel(MachineRepresentation::kTagged);
  TNode<Boolean> search_string_too_long = NumberLessThan(start, zero);
  GotoIf(search_string_too_long, &out, BranchHint::kFalse, FalseConstant());
  for (int i = 0; i < search_string_length; i++) {
    TNode<Number> k = NumberConstant(i);
    TNode<Number> receiver_string_position = TNode<Number>::UncheckedCast(
        TypeGuard(Type::UnsignedSmall(), NumberAdd(k, start)));
    Node* receiver_string_char =
        StringCharCodeAt(receiver_string, receiver_string_position);
    Node* search_string_char = jsgraph()->ConstantNoHole(
        search_element_string.GetChar(broker(), i).value());
    auto is_equal = graph()->NewNode(simplified()->NumberEqual(),
                                     receiver_string_char, search_string_char);
    GotoIfNot(is_equal, &out, FalseConstant());
  }
  Goto(&out, TrueConstant());
  Bind(&out);
  return out.PhiAt<Boolean>(0);
}
References _, ArgumentOrUndefined(), v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::JSGraphAssembler::broker(), CheckSmi(), CheckString(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::compiler::StringRef::GetChar(), v8::internal::compiler::GraphAssembler::Goto(), v8::internal::compiler::GraphAssembler::GotoIf(), v8::internal::compiler::GraphAssembler::GotoIfNot(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::StringRef::IsContentAccessible(), v8::internal::compiler::JSGraphAssembler::jsgraph(), v8::internal::kFalse, v8::internal::compiler::JSCallReducer::kMaxInlineMatchSequence, v8::internal::kTagged, v8::internal::length, v8::internal::compiler::StringRef::length(), v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::JSGraphAssembler::NumberAdd(), v8::internal::compiler::JSGraphAssembler::NumberConstant(), v8::internal::compiler::JSGraphAssembler::NumberEqual(), v8::internal::compiler::JSGraphAssembler::NumberLessThan(), v8::internal::compiler::JSGraphAssembler::NumberMax(), v8::internal::compiler::JSGraphAssembler::NumberMin(), v8::internal::compiler::JSGraphAssembler::NumberSubtract(), ReceiverInput(), v8::internal::compiler::JSGraphAssembler::simplified(), v8::internal::compiler::GraphAssembler::start(), v8::internal::compiler::JSGraphAssembler::StringCharCodeAt(), v8::internal::compiler::JSGraphAssembler::StringLength(), v8::internal::compiler::GraphAssembler::TypeGuard(), v8::internal::TNode< T >::UncheckedCast(), v8::internal::compiler::Type::UnsignedSmall(), v8::internal::value, and v8::internal::zero.
ReduceStringPrototypeSlice()
TNode< String > v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice ()
Definition at line 1256 of file js-call-reducer.cc.
                                                                 {
  TNode<Object> receiver = ReceiverInput();
  TNode<String> receiver_string = CheckString(receiver);
  TNode<Number> length = StringLength(receiver_string);
  TNode<Object> start = Argument(0);
  TNode<Object> end = ArgumentOrUndefined(1);
  // Special case str.slice(-1) to str.charAt(str.length - 1).
  // This will not hit if the start offset is not known to be the -1 constant
  // during this reduction, nor if the end argument is explicitly rather than
  // implicitly undefined; hopefully in common cases the code will explicitly
  // use the -1 literal.
  if (ArgumentCount() == 1) {
    NumberMatcher m(start);
    if (m.Is(-1)) {
      return SelectIf<String>(
                 ReferenceEqual(receiver_string, EmptyStringConstant()))
          .Then(_ { return EmptyStringConstant(); })
          .Else(_ {
            return StringFromSingleCharCode(
                TNode<Number>::UncheckedCast(StringCharCodeAt(
                    receiver_string,
                    TypeGuard(Type::Unsigned32(),
                              NumberAdd(length, TNode<Number>::UncheckedCast(
                                                    m.node()))))));
          })
          .Value();
    }
  }
  TNode<Number> start_smi = CheckSmi(start);
  TNode<Number> end_smi = SelectIf<Number>(IsUndefined(end))
                              .Then(_ { return length; })
                              .Else(_ { return CheckSmi(end); })
                              .ExpectFalse()
                              .Value();
  TNode<Number> zero = ZeroConstant();
  TNode<Number> from_untyped =
      SelectIf<Number>(NumberLessThan(start_smi, zero))
          .Then(_ { return NumberMax(NumberAdd(length, start_smi), zero); })
          .Else(_ { return NumberMin(start_smi, length); })
          .ExpectFalse()
          .Value();
  // {from} is always in non-negative Smi range, but our typer cannot figure
  // that out yet.
  TNode<Smi> from = TypeGuardUnsignedSmall(from_untyped);
  TNode<Number> to_untyped =
      SelectIf<Number>(NumberLessThan(end_smi, zero))
          .Then(_ { return NumberMax(NumberAdd(length, end_smi), zero); })
          .Else(_ { return NumberMin(end_smi, length); })
          .ExpectFalse()
          .Value();
  // {to} is always in non-negative Smi range, but our typer cannot figure that
  // out yet.
  TNode<Smi> to = TypeGuardUnsignedSmall(to_untyped);
  return SelectIf<String>(NumberLessThan(from, to))
      .Then(_ { return StringSubstring(receiver_string, from, to); })
      .Else(_ { return EmptyStringConstant(); })
      .ExpectTrue()
      .Value();
}
References _, Argument(), ArgumentCount(), ArgumentOrUndefined(), CheckSmi(), CheckString(), v8::internal::compiler::end(), v8::internal::compiler::FloatMatcher< T, kOpcode >::Is(), v8::internal::length, v8::internal::compiler::NodeMatcher::node(), v8::internal::compiler::JSGraphAssembler::NumberAdd(), v8::internal::compiler::JSGraphAssembler::NumberLessThan(), v8::internal::compiler::JSGraphAssembler::NumberMax(), v8::internal::compiler::JSGraphAssembler::NumberMin(), ReceiverInput(), v8::internal::compiler::JSGraphAssembler::ReferenceEqual(), v8::internal::compiler::GraphAssembler::start(), v8::internal::compiler::JSGraphAssembler::StringCharCodeAt(), v8::internal::compiler::JSGraphAssembler::StringFromSingleCharCode(), v8::internal::compiler::JSGraphAssembler::StringLength(), v8::internal::compiler::JSGraphAssembler::StringSubstring(), v8::internal::compiler::GraphAssembler::TypeGuard(), TypeGuardUnsignedSmall(), and v8::internal::zero.
Referenced by v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSlice().
ReduceStringPrototypeStartsWith() [1/2]
TNode< Boolean > v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith ()
Definition at line 1016 of file js-call-reducer.cc.
                                                                       {
  TNode<Object> receiver = ReceiverInput();
  TNode<Object> search_element = ArgumentOrUndefined(0);
  TNode<Object> start = ArgumentOrZero(1);
  TNode<String> receiver_string = CheckString(receiver);
  TNode<String> search_string = CheckString(search_element);
  TNode<Smi> start_smi = CheckSmi(start);
  TNode<Number> length = StringLength(receiver_string);
  TNode<Number> zero = ZeroConstant();
  TNode<Number> clamped_start = NumberMin(NumberMax(start_smi, zero), length);
  TNode<Number> search_string_length = StringLength(search_string);
  auto out = MakeLabel(MachineRepresentation::kTagged);
  auto search_string_too_long = NumberLessThan(
      NumberSubtract(length, clamped_start), search_string_length);
  GotoIf(search_string_too_long, &out, BranchHint::kFalse, FalseConstant());
  static_assert(String::kMaxLength <= kSmiMaxValue);
  ForZeroUntil(search_string_length).Do([&](TNode<Number> k) {
    TNode<Number> receiver_string_position = TNode<Number>::UncheckedCast(
        TypeGuard(Type::UnsignedSmall(), NumberAdd(k, clamped_start)));
    Node* receiver_string_char =
        StringCharCodeAt(receiver_string, receiver_string_position);
    if (!v8_flags.turbo_loop_variable) {
      // Without loop variable analysis, Turbofan's typer is unable to derive a
      // sufficiently precise type here. This is not a soundness problem, but
      // triggers graph verification errors. So we only insert the TypeGuard if
      // necessary.
      k = TypeGuard(Type::Unsigned32(), k);
    }
    Node* search_string_char = StringCharCodeAt(search_string, k);
    auto is_equal = graph()->NewNode(simplified()->NumberEqual(),
                                     receiver_string_char, search_string_char);
    GotoIfNot(is_equal, &out, FalseConstant());
  });
  Goto(&out, TrueConstant());
  Bind(&out);
  return out.PhiAt<Boolean>(0);
}
References ArgumentOrUndefined(), ArgumentOrZero(), v8::internal::compiler::GraphAssembler::Bind(), CheckSmi(), CheckString(), v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::Do(), ForZeroUntil(), v8::internal::compiler::GraphAssembler::Goto(), v8::internal::compiler::GraphAssembler::GotoIf(), v8::internal::compiler::GraphAssembler::GotoIfNot(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::kFalse, v8::internal::String::kMaxLength, v8::internal::kSmiMaxValue, v8::internal::kTagged, v8::internal::length, v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::JSGraphAssembler::NumberAdd(), v8::internal::compiler::JSGraphAssembler::NumberEqual(), v8::internal::compiler::JSGraphAssembler::NumberLessThan(), v8::internal::compiler::JSGraphAssembler::NumberMax(), v8::internal::compiler::JSGraphAssembler::NumberMin(), v8::internal::compiler::JSGraphAssembler::NumberSubtract(), ReceiverInput(), v8::internal::compiler::JSGraphAssembler::simplified(), v8::internal::compiler::GraphAssembler::start(), v8::internal::compiler::JSGraphAssembler::StringCharCodeAt(), v8::internal::compiler::JSGraphAssembler::StringLength(), v8::internal::compiler::GraphAssembler::TypeGuard(), v8::internal::TNode< T >::UncheckedCast(), v8::internal::compiler::Type::UnsignedSmall(), v8::internal::v8_flags, and v8::internal::zero.
Referenced by v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStartsWith().
ReduceStringPrototypeStartsWith() [2/2]
TNode< Boolean > v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith (StringRef search_element_string)
Definition at line 971 of file js-call-reducer.cc.
                                     {
  DCHECK(search_element_string.IsContentAccessible());
  TNode<Object> receiver = ReceiverInput();
  TNode<Object> start = ArgumentOrZero(1);
  TNode<String> receiver_string = CheckString(receiver);
  TNode<Smi> start_smi = CheckSmi(start);
  TNode<Number> length = StringLength(receiver_string);
  TNode<Number> zero = ZeroConstant();
  TNode<Number> clamped_start = NumberMin(NumberMax(start_smi, zero), length);
  int search_string_length = search_element_string.length();
  DCHECK(search_string_length <= JSCallReducer::kMaxInlineMatchSequence);
  auto out = MakeLabel(MachineRepresentation::kTagged);
  auto search_string_too_long =
      NumberLessThan(NumberSubtract(length, clamped_start),
                     NumberConstant(search_string_length));
  GotoIf(search_string_too_long, &out, BranchHint::kFalse, FalseConstant());
  static_assert(String::kMaxLength <= kSmiMaxValue);
  for (int i = 0; i < search_string_length; i++) {
    TNode<Number> k = NumberConstant(i);
    TNode<Number> receiver_string_position = TNode<Number>::UncheckedCast(
        TypeGuard(Type::UnsignedSmall(), NumberAdd(k, clamped_start)));
    Node* receiver_string_char =
        StringCharCodeAt(receiver_string, receiver_string_position);
    Node* search_string_char = jsgraph()->ConstantNoHole(
        search_element_string.GetChar(broker(), i).value());
    auto is_equal = graph()->NewNode(simplified()->NumberEqual(),
                                     search_string_char, receiver_string_char);
    GotoIfNot(is_equal, &out, FalseConstant());
  }
  Goto(&out, TrueConstant());
  Bind(&out);
  return out.PhiAt<Boolean>(0);
}
References ArgumentOrZero(), v8::internal::compiler::GraphAssembler::Bind(), v8::internal::compiler::JSGraphAssembler::broker(), CheckSmi(), CheckString(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::DCHECK(), v8::internal::compiler::StringRef::GetChar(), v8::internal::compiler::GraphAssembler::Goto(), v8::internal::compiler::GraphAssembler::GotoIf(), v8::internal::compiler::GraphAssembler::GotoIfNot(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::StringRef::IsContentAccessible(), v8::internal::compiler::JSGraphAssembler::jsgraph(), v8::internal::kFalse, v8::internal::compiler::JSCallReducer::kMaxInlineMatchSequence, v8::internal::String::kMaxLength, v8::internal::kSmiMaxValue, v8::internal::kTagged, v8::internal::length, v8::internal::compiler::StringRef::length(), v8::internal::compiler::GraphAssembler::MakeLabel(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::JSGraphAssembler::NumberAdd(), v8::internal::compiler::JSGraphAssembler::NumberConstant(), v8::internal::compiler::JSGraphAssembler::NumberEqual(), v8::internal::compiler::JSGraphAssembler::NumberLessThan(), v8::internal::compiler::JSGraphAssembler::NumberMax(), v8::internal::compiler::JSGraphAssembler::NumberMin(), v8::internal::compiler::JSGraphAssembler::NumberSubtract(), ReceiverInput(), v8::internal::compiler::JSGraphAssembler::simplified(), v8::internal::compiler::GraphAssembler::start(), v8::internal::compiler::JSGraphAssembler::StringCharCodeAt(), v8::internal::compiler::JSGraphAssembler::StringLength(), v8::internal::compiler::GraphAssembler::TypeGuard(), v8::internal::TNode< T >::UncheckedCast(), v8::internal::compiler::Type::UnsignedSmall(), v8::internal::value, and v8::internal::zero.
ReduceStringPrototypeSubstring()
TNode< String > v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSubstring ()
Definition at line 946 of file js-call-reducer.cc.
                                                                     {
  TNode<Object> receiver = ReceiverInput();
  TNode<Object> start = Argument(0);
  TNode<Object> end = ArgumentOrUndefined(1);
  TNode<String> receiver_string = CheckString(receiver);
  TNode<Number> start_smi = CheckSmi(start);
  TNode<Number> length = StringLength(receiver_string);
  TNode<Number> end_smi = SelectIf<Number>(IsUndefined(end))
                              .Then(_ { return length; })
                              .Else(_ { return CheckSmi(end); })
                              .ExpectFalse()
                              .Value();
  TNode<Number> zero = TNode<Number>::UncheckedCast(ZeroConstant());
  TNode<Number> finalStart = NumberMin(NumberMax(start_smi, zero), length);
  TNode<Number> finalEnd = NumberMin(NumberMax(end_smi, zero), length);
  TNode<Number> from = NumberMin(finalStart, finalEnd);
  TNode<Number> to = NumberMax(finalStart, finalEnd);
  return StringSubstring(receiver_string, from, to);
}
References _, Argument(), ArgumentOrUndefined(), CheckSmi(), CheckString(), v8::internal::compiler::end(), v8::internal::length, v8::internal::compiler::JSGraphAssembler::NumberMax(), v8::internal::compiler::JSGraphAssembler::NumberMin(), ReceiverInput(), v8::internal::compiler::GraphAssembler::start(), v8::internal::compiler::JSGraphAssembler::StringLength(), v8::internal::compiler::JSGraphAssembler::StringSubstring(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::zero.
Referenced by v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstring().
SpeculativeToNumber()
TNode< Number > v8::internal::compiler::JSCallReducerAssembler::SpeculativeToNumber (TNode< Object > value, NumberOperationHint hint = NumberOperationHint::kNumberOrOddball)
Definition at line 790 of file js-call-reducer.cc.
                                                   {
  return AddNode<Number>(
      graph()->NewNode(simplified()->SpeculativeToNumber(hint, feedback()),
                       value, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), feedback(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::compiler::JSGraphAssembler::simplified(), and v8::internal::value.
Referenced by ReduceMathBinary(), and ReduceMathUnary().
TargetInput()
TNode<Object> v8::internal::compiler::JSCallReducerAssembler::TargetInput () const [inline]
Definition at line 96 of file js-call-reducer.cc.
{ return JSCallNode{node_ptr()}.target(); }
References node_ptr().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
ThrowIfNotCallable()
void v8::internal::compiler::JSCallReducerAssembler::ThrowIfNotCallable (TNode< Object > maybe_callable, FrameState frame_state) [inline]
Definition at line 376 of file js-call-reducer.cc.
                                                  {
    IfNot(ObjectIsCallable(maybe_callable))
        .Then(_ {
          JSCallRuntime1(Runtime::kThrowCalledNonCallable, maybe_callable,
                         ContextInput(), frame_state);
          Unreachable(); // The runtime call throws unconditionally.
        })
        .ExpectTrue();
  }
References _, ContextInput(), v8::internal::compiler::JSGraphAssembler::IfNot(), v8::internal::compiler::JSGraphAssembler::JSCallRuntime1(), v8::internal::compiler::JSGraphAssembler::ObjectIsCallable(), and v8::internal::compiler::GraphAssembler::Unreachable().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
Try()
TryCatchBuilder0 v8::internal::compiler::JSCallReducerAssembler::Try (const VoidGenerator0 & try_body) [inline]
Definition at line 229 of file js-call-reducer.cc.
                                                       {
    return {this, try_body};
  }
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor().
TypeGuardFixedArrayLength()
TNode< Number > v8::internal::compiler::JSCallReducerAssembler::TypeGuardFixedArrayLength (TNode< Object > value)
Definition at line 829 of file js-call-reducer.cc.
                         {
  DCHECK(TypeCache::Get()->kFixedDoubleArrayLengthType.Is(
      TypeCache::Get()->kFixedArrayLengthType));
  return TNode<Number>::UncheckedCast(
      TypeGuard(TypeCache::Get()->kFixedArrayLengthType, value));
}
References v8::internal::DCHECK(), v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kFixedArrayLengthType, v8::internal::compiler::GraphAssembler::TypeGuard(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter().
TypeGuardNonInternal()
TNode< Object > v8::internal::compiler::JSCallReducerAssembler::TypeGuardNonInternal (TNode< Object > value)
Definition at line 824 of file js-call-reducer.cc.
                         {
  return TNode<Object>::UncheckedCast(TypeGuard(Type::NonInternal(), value));
}
References v8::internal::compiler::GraphAssembler::TypeGuard(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::MaybeSkipHole(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
TypeGuardUnsignedSmall()
TNode< Smi > v8::internal::compiler::JSCallReducerAssembler::TypeGuardUnsignedSmall (TNode< Object > value)
Definition at line 820 of file js-call-reducer.cc.
                                                                             {
  return TNode<Smi>::UncheckedCast(TypeGuard(Type::UnsignedSmall(), value));
}
References v8::internal::compiler::GraphAssembler::TypeGuard(), v8::internal::TNode< T >::UncheckedCast(), v8::internal::compiler::Type::UnsignedSmall(), and v8::internal::value.
Referenced by ReduceStringPrototypeSlice().
Member Data Documentation
dependencies_
CompilationDependencies* const v8::internal::compiler::JSCallReducerAssembler::dependencies_ [private]
Definition at line 430 of file js-call-reducer.cc.
Referenced by dependencies().
kMarkLoopExits
constexpr bool v8::internal::compiler::JSCallReducerAssembler::kMarkLoopExits = true [static], [constexpr], [private]
Definition at line 57 of file js-call-reducer.cc.
node_
Node* const v8::internal::compiler::JSCallReducerAssembler::node_ [private]
Definition at line 431 of file js-call-reducer.cc.
Referenced by ContextInput(), FrameStateInput(), and node_ptr().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-call-reducer.cc