v8::internal::EmbeddedData Class Reference
#include <embedded-data.h>
Classes
struct BuiltinLookupEntry
struct LayoutDescription
Public Member Functions
const uint8_t * code () const
uint32_t code_size () const
const uint8_t * data () const
uint32_t data_size () const
bool IsInCodeRange (Address pc) const
void Dispose ()
Address InstructionStartOf (Builtin builtin) const
Address InstructionEndOf (Builtin builtin) const
uint32_t InstructionSizeOf (Builtin builtin) const
Address InstructionStartOfBytecodeHandlers () const
Address InstructionEndOfBytecodeHandlers () const
Address MetadataStartOf (Builtin builtin) const
uint32_t AddressForHashing (Address addr)
uint32_t PaddedInstructionSizeOf (Builtin builtin) const
size_t CreateEmbeddedBlobDataHash () const
size_t CreateEmbeddedBlobCodeHash () const
size_t EmbeddedBlobDataHash () const
size_t EmbeddedBlobCodeHash () const
size_t IsolateHash () const
Builtin TryLookupCode (Address address) const
Builtin GetBuiltinId (ReorderedBuiltinIndex embedded_index) const
Static Public Member Functions
static EmbeddedData NewFromIsolate (Isolate *isolate)
static EmbeddedData FromBlob ()
static EmbeddedData FromBlob (Isolate *isolate)
static EmbeddedData FromBlob (CodeRange *code_range)
static EmbeddedData FromBlobForPc (Isolate *isolate, Address maybe_builtin_pc)
static constexpr uint32_t EmbeddedBlobDataHashOffset ()
static constexpr uint32_t EmbeddedBlobDataHashSize ()
static constexpr uint32_t EmbeddedBlobCodeHashOffset ()
static constexpr uint32_t EmbeddedBlobCodeHashSize ()
static constexpr uint32_t IsolateHashOffset ()
static constexpr uint32_t IsolateHashSize ()
static constexpr uint32_t LayoutDescriptionTableOffset ()
static constexpr uint32_t LayoutDescriptionTableSize ()
static constexpr uint32_t BuiltinLookupEntryTableOffset ()
static constexpr uint32_t BuiltinLookupEntryTableSize ()
static constexpr uint32_t FixedDataSize ()
static constexpr uint32_t RawMetadataOffset ()
static constexpr uint32_t RawCodeOffset ()
Static Public Attributes
static constexpr uint32_t kTableSize = Builtins::kBuiltinCount
Private Member Functions
EmbeddedData (const uint8_t *code, uint32_t code_size, const uint8_t *data, uint32_t data_size)
const uint8_t * RawCode () const
const LayoutDescription & LayoutDescription (Builtin builtin) const
const BuiltinLookupEntry * BuiltinLookupEntry (ReorderedBuiltinIndex index) const
const uint8_t * RawMetadata () const
void PrintStatistics () const
Static Private Member Functions
static constexpr int PadAndAlignCode (int size)
static constexpr int PadAndAlignData (int size)
Private Attributes
const uint8_t * code_
uint32_t code_size_
const uint8_t * data_
uint32_t data_size_
Detailed Description
Definition at line 55 of file embedded-data.h.
Constructor & Destructor Documentation
EmbeddedData()
v8::internal::EmbeddedData::EmbeddedData (const uint8_t * code, uint32_t code_size, const uint8_t * data, uint32_t data_size) [inline], [private]
Definition at line 262 of file embedded-data.h.
      : code_(code), code_size_(code_size), data_(data), data_size_(data_size) {
    DCHECK_NOT_NULL(code);
    DCHECK_LT(0, code_size);
    DCHECK_NOT_NULL(data);
    DCHECK_LT(0, data_size);
  }
References code(), code_size(), data(), data_size(), DCHECK_LT, and DCHECK_NOT_NULL.
Referenced by FromBlob().
Member Function Documentation
AddressForHashing()
uint32_t v8::internal::EmbeddedData::AddressForHashing (Address addr) [inline]
Definition at line 147 of file embedded-data.h.
                                           {
    DCHECK(IsInCodeRange(addr));
    Address start = reinterpret_cast<Address>(code_);
    return static_cast<uint32_t>(addr - start);
  }
References code_, v8::internal::DCHECK(), and IsInCodeRange().
Referenced by v8::internal::OffHeapInstructionStream::TryGetAddressForHashing().
BuiltinLookupEntry()
const BuiltinLookupEntry* v8::internal::EmbeddedData::BuiltinLookupEntry (ReorderedBuiltinIndex index) const [inline], [private]
Definition at line 280 of file embedded-data.h.
                                         {
    const struct BuiltinLookupEntry* entries =
        reinterpret_cast<const struct BuiltinLookupEntry*>(
            data_ + BuiltinLookupEntryTableOffset());
    return entries + index;
  }
References BuiltinLookupEntryTableOffset(), data_, and v8::internal::index.
Referenced by GetBuiltinId(), and TryLookupCode().
BuiltinLookupEntryTableOffset()
static constexpr uint32_t v8::internal::EmbeddedData::BuiltinLookupEntryTableOffset () [inline], [static], [constexpr]
Definition at line 246 of file embedded-data.h.
                                                            {
    return LayoutDescriptionTableOffset() + LayoutDescriptionTableSize();
  }
References LayoutDescriptionTableOffset(), and LayoutDescriptionTableSize().
Referenced by BuiltinLookupEntry(), FixedDataSize(), and NewFromIsolate().
BuiltinLookupEntryTableSize()
static constexpr uint32_t v8::internal::EmbeddedData::BuiltinLookupEntryTableSize () [inline], [static], [constexpr]
Definition at line 249 of file embedded-data.h.
                                                          {
    return sizeof(struct BuiltinLookupEntry) * kTableSize;
  }
References kTableSize.
Referenced by FixedDataSize(), and NewFromIsolate().
code()
const uint8_t* v8::internal::EmbeddedData::code () const [inline]
Definition at line 123 of file embedded-data.h.
{ return code_; }
References code_.
Referenced by v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream(), EmbeddedData(), v8::Isolate::GetEmbeddedCodeRange(), and NewFromIsolate().
code_size()
uint32_t v8::internal::EmbeddedData::code_size () const [inline]
Definition at line 124 of file embedded-data.h.
{ return code_size_; }
References code_size_.
Referenced by v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream(), EmbeddedData(), v8::Isolate::GetEmbeddedCodeRange(), PrintStatistics(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::EmbeddedFileWriter::WriteFileEpilogue().
CreateEmbeddedBlobCodeHash()
size_t v8::internal::EmbeddedData::CreateEmbeddedBlobCodeHash () const
Definition at line 438 of file embedded-data.cc.
                                                      {
  CHECK(v8_flags.text_is_readable);
  base::Vector<const uint8_t> payload(code_, code_size_);
  return Checksum(payload);
}
References CHECK, v8::internal::Checksum(), code_, code_size_, and v8::internal::v8_flags.
Referenced by NewFromIsolate(), and v8::internal::Isolate::SetEmbeddedBlob().
CreateEmbeddedBlobDataHash()
size_t v8::internal::EmbeddedData::CreateEmbeddedBlobDataHash () const
Definition at line 425 of file embedded-data.cc.
                                                      {
  static_assert(EmbeddedBlobDataHashOffset() == 0);
  static_assert(EmbeddedBlobCodeHashOffset() == EmbeddedBlobDataHashSize());
  static_assert(IsolateHashOffset() ==
                EmbeddedBlobCodeHashOffset() + EmbeddedBlobCodeHashSize());
  static constexpr uint32_t kFirstHashedDataOffset = IsolateHashOffset();
  // Hash the entire data section except the embedded blob hash fields
  // themselves.
  base::Vector<const uint8_t> payload(data_ + kFirstHashedDataOffset,
                                      data_size_ - kFirstHashedDataOffset);
  return Checksum(payload);
}
References v8::internal::Checksum(), data_, data_size_, EmbeddedBlobCodeHashOffset(), EmbeddedBlobCodeHashSize(), EmbeddedBlobDataHashOffset(), EmbeddedBlobDataHashSize(), and IsolateHashOffset().
Referenced by NewFromIsolate(), and v8::internal::Isolate::SetEmbeddedBlob().
data()
const uint8_t* v8::internal::EmbeddedData::data () const [inline]
Definition at line 125 of file embedded-data.h.
{ return data_; }
References data_.
Referenced by v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream(), EmbeddedData(), and v8::internal::EmbeddedFileWriter::WriteDataSection().
data_size()
uint32_t v8::internal::EmbeddedData::data_size () const [inline]
Definition at line 126 of file embedded-data.h.
{ return data_size_; }
References data_size_.
Referenced by v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream(), EmbeddedData(), PrintStatistics(), v8::internal::RUNTIME_FUNCTION(), v8::internal::EmbeddedFileWriter::WriteDataSection(), and v8::internal::EmbeddedFileWriter::WriteFileEpilogue().
Dispose()
void v8::internal::EmbeddedData::Dispose () [inline]
Definition at line 133 of file embedded-data.h.
                 {
    delete[] code_;
    code_ = nullptr;
    delete[] data_;
    data_ = nullptr;
  }
References code_, and data_.
Referenced by v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream().
EmbeddedBlobCodeHash()
size_t v8::internal::EmbeddedData::EmbeddedBlobCodeHash () const [inline]
Definition at line 162 of file embedded-data.h.
                                      {
    return *reinterpret_cast<const size_t*>(data_ +
                                            EmbeddedBlobCodeHashOffset());
  }
References data_, and EmbeddedBlobCodeHashOffset().
Referenced by NewFromIsolate(), and v8::internal::Isolate::SetEmbeddedBlob().
EmbeddedBlobCodeHashOffset()
static constexpr uint32_t v8::internal::EmbeddedData::EmbeddedBlobCodeHashOffset () [inline], [static], [constexpr]
Definition at line 232 of file embedded-data.h.
                                                         {
    return EmbeddedBlobDataHashOffset() + EmbeddedBlobDataHashSize();
  }
References EmbeddedBlobDataHashOffset(), and EmbeddedBlobDataHashSize().
Referenced by CreateEmbeddedBlobDataHash(), EmbeddedBlobCodeHash(), IsolateHashOffset(), and NewFromIsolate().
EmbeddedBlobCodeHashSize()
static constexpr uint32_t v8::internal::EmbeddedData::EmbeddedBlobCodeHashSize () [inline], [static], [constexpr]
Definition at line 235 of file embedded-data.h.
{ return kSizetSize; }
References v8::internal::kSizetSize.
Referenced by CreateEmbeddedBlobDataHash(), IsolateHashOffset(), and NewFromIsolate().
EmbeddedBlobDataHash()
size_t v8::internal::EmbeddedData::EmbeddedBlobDataHash () const [inline]
Definition at line 158 of file embedded-data.h.
                                      {
    return *reinterpret_cast<const size_t*>(data_ +
                                            EmbeddedBlobDataHashOffset());
  }
References data_, and EmbeddedBlobDataHashOffset().
Referenced by NewFromIsolate(), and v8::internal::Isolate::SetEmbeddedBlob().
EmbeddedBlobDataHashOffset()
static constexpr uint32_t v8::internal::EmbeddedData::EmbeddedBlobDataHashOffset () [inline], [static], [constexpr]
Definition at line 230 of file embedded-data.h.
{ return 0; }
Referenced by CreateEmbeddedBlobDataHash(), EmbeddedBlobCodeHashOffset(), EmbeddedBlobDataHash(), and NewFromIsolate().
EmbeddedBlobDataHashSize()
static constexpr uint32_t v8::internal::EmbeddedData::EmbeddedBlobDataHashSize () [inline], [static], [constexpr]
Definition at line 231 of file embedded-data.h.
{ return kSizetSize; }
References v8::internal::kSizetSize.
Referenced by CreateEmbeddedBlobDataHash(), EmbeddedBlobCodeHashOffset(), and NewFromIsolate().
FixedDataSize()
static constexpr uint32_t v8::internal::EmbeddedData::FixedDataSize () [inline], [static], [constexpr]
Definition at line 252 of file embedded-data.h.
                                            {
    return BuiltinLookupEntryTableOffset() + BuiltinLookupEntryTableSize();
  }
References BuiltinLookupEntryTableOffset(), and BuiltinLookupEntryTableSize().
Referenced by NewFromIsolate(), and RawMetadataOffset().
FromBlob() [1/3]
static EmbeddedData v8::internal::EmbeddedData::FromBlob () [inline], [static]
Definition at line 62 of file embedded-data.h.
                                 {
    return EmbeddedData(Isolate::CurrentEmbeddedBlobCode(),
                        Isolate::CurrentEmbeddedBlobCodeSize(),
                        Isolate::CurrentEmbeddedBlobData(),
                        Isolate::CurrentEmbeddedBlobDataSize());
  }
References v8::internal::Isolate::CurrentEmbeddedBlobCode(), v8::internal::Isolate::CurrentEmbeddedBlobCodeSize(), v8::internal::Isolate::CurrentEmbeddedBlobData(), v8::internal::Isolate::CurrentEmbeddedBlobDataSize(), and EmbeddedData().
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), v8::internal::RegExpMacroAssemblerRISCV::CallCheckStackGuardState(), v8::internal::Builtins::EmbeddedEntryOf(), v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects(), FromBlobForPc(), v8::Isolate::GetEmbeddedCodeRange(), v8::internal::JSFunction::GetRequestedOptimizationIfAny(), v8::internal::init_memcopy_functions(), v8::internal::Builtins::InitializeIsolateDataTables(), v8::internal::wasm::InitTrapHandlersOnce(), v8::internal::JSFunction::IsMaglevRequested(), v8::internal::StackFrameIteratorForProfiler::IsNoFrameBytecodeHandlerPc(), v8::internal::JSFunction::IsTurbofanRequested(), v8::internal::ProfilerCodeObserver::LogBuiltins(), v8::internal::MacroAssembler::MacroAssemblerBase(), v8::internal::Code::metadata_start(), v8::internal::OffHeapInstructionStream::PcIsOffHeap(), v8::internal::ObjectPostProcessor::PostProcessCode(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Isolate::SetEmbeddedBlob(), v8::internal::OffHeapInstructionStream::TryGetAddressForHashing(), v8::internal::OffHeapInstructionStream::TryLookupCode(), and anonymous_namespace{mksnapshot.cc}::WriteEmbeddedFile().
FromBlob() [2/3]
static EmbeddedData v8::internal::EmbeddedData::FromBlob (CodeRange * code_range) [inline], [static]
Definition at line 79 of file embedded-data.h.
                                                      {
    return EmbeddedData(code_range->embedded_blob_code_copy(),
                        Isolate::CurrentEmbeddedBlobCodeSize(),
                        Isolate::CurrentEmbeddedBlobData(),
                        Isolate::CurrentEmbeddedBlobDataSize());
  }
References v8::internal::Isolate::CurrentEmbeddedBlobCodeSize(), v8::internal::Isolate::CurrentEmbeddedBlobData(), v8::internal::Isolate::CurrentEmbeddedBlobDataSize(), v8::internal::CodeRange::embedded_blob_code_copy(), and EmbeddedData().
FromBlob() [3/3]
static EmbeddedData v8::internal::EmbeddedData::FromBlob (Isolate * isolate) [inline], [static]
Definition at line 71 of file embedded-data.h.
                                                 {
    return EmbeddedData(
        isolate->embedded_blob_code(), isolate->embedded_blob_code_size(),
        isolate->embedded_blob_data(), isolate->embedded_blob_data_size());
  }
References v8::internal::Isolate::embedded_blob_code(), v8::internal::Isolate::embedded_blob_code_size(), v8::internal::Isolate::embedded_blob_data(), v8::internal::Isolate::embedded_blob_data_size(), and EmbeddedData().
FromBlobForPc()
static EmbeddedData v8::internal::EmbeddedData::FromBlobForPc (Isolate * isolate, Address maybe_builtin_pc) [inline], [static]
Definition at line 94 of file embedded-data.h.
                                                              {
    EmbeddedData d = EmbeddedData::FromBlob(isolate);
    if (d.IsInCodeRange(maybe_builtin_pc)) return d;
    if (isolate->is_short_builtin_calls_enabled()) {
      EmbeddedData global_d = EmbeddedData::FromBlob();
      // If the pc does not belong to the embedded code blob we should be using
      // the un-embedded one.
      if (global_d.IsInCodeRange(maybe_builtin_pc)) return global_d;
    }
#if defined(V8_COMPRESS_POINTERS_IN_SHARED_CAGE) && \
    defined(V8_SHORT_BUILTIN_CALLS)
    // When shared pointer compression cage is enabled and it has the embedded
    // code blob copy then it could have been used regardless of whether the
    // isolate uses it or knows about it or not (see
    // InstructionStream::OffHeapInstructionStart()).
    // So, this blob has to be checked too.
    CodeRange* code_range = IsolateGroup::current()->GetCodeRange();
    if (code_range && code_range->embedded_blob_code_copy() != nullptr) {
      EmbeddedData remapped_d = EmbeddedData::FromBlob(code_range);
      // If the pc does not belong to the embedded code blob we should be
      // using the un-embedded one.
      if (remapped_d.IsInCodeRange(maybe_builtin_pc)) return remapped_d;
    }
#endif // defined(V8_COMPRESS_POINTERS_IN_SHARED_CAGE) &&
        // defined(V8_SHORT_BUILTIN_CALLS)
    return d;
  }
References v8::internal::IsolateGroup::current(), v8::internal::CodeRange::embedded_blob_code_copy(), FromBlob(), v8::internal::IsolateGroup::GetCodeRange(), v8::internal::Isolate::is_short_builtin_calls_enabled(), and IsInCodeRange().
Referenced by v8::internal::Code::InstructionStart().
GetBuiltinId()
Builtin v8::internal::EmbeddedData::GetBuiltinId (ReorderedBuiltinIndex embedded_index) const
Definition at line 444 of file embedded-data.cc.
                                                                             {
  Builtin builtin =
      Builtins::FromInt(BuiltinLookupEntry(embedded_index)->builtin_id);
  return builtin;
}
References BuiltinLookupEntry(), and v8::internal::Builtins::FromInt().
Referenced by v8::internal::EmbeddedFileWriter::WriteCodeSection().
InstructionEndOf()
Address v8::internal::EmbeddedData::InstructionEndOf (Builtin builtin) const [inline]
Definition at line 22 of file embedded-data-inl.h.
                                                            {
  DCHECK(Builtins::IsBuiltinId(builtin));
  const struct LayoutDescription& desc = LayoutDescription(builtin);
  const uint8_t* result =
      RawCode() + desc.instruction_offset + desc.instruction_length;
  DCHECK_LT(result, code_ + code_size_);
  return reinterpret_cast<Address>(result);
}
References code_, code_size_, v8::internal::DCHECK(), DCHECK_LT, v8::internal::EmbeddedData::LayoutDescription::instruction_length, v8::internal::EmbeddedData::LayoutDescription::instruction_offset, v8::internal::Builtins::IsBuiltinId(), LayoutDescription(), RawCode(), and v8::base::internal::result.
InstructionEndOfBytecodeHandlers()
Address v8::internal::EmbeddedData::InstructionEndOfBytecodeHandlers () const [inline]
Definition at line 49 of file embedded-data-inl.h.
                                                             {
  static_assert(Builtins::kBytecodeHandlersAreSortedLast);
  // Note this also includes trailing padding, but that's fine for our purposes.
  return reinterpret_cast<Address>(code_ + code_size_);
}
References code_, code_size_, and v8::internal::Builtins::kBytecodeHandlersAreSortedLast.
Referenced by v8::internal::StackFrameIteratorForProfiler::IsNoFrameBytecodeHandlerPc().
InstructionSizeOf()
uint32_t v8::internal::EmbeddedData::InstructionSizeOf (Builtin builtin) const [inline]
Definition at line 31 of file embedded-data-inl.h.
                                                              {
  DCHECK(Builtins::IsBuiltinId(builtin));
  const struct LayoutDescription& desc = LayoutDescription(builtin);
  return desc.instruction_length;
}
References v8::internal::DCHECK(), v8::internal::EmbeddedData::LayoutDescription::instruction_length, v8::internal::Builtins::IsBuiltinId(), and LayoutDescription().
Referenced by v8::internal::ProfilerCodeObserver::LogBuiltins(), NewFromIsolate(), PaddedInstructionSizeOf(), PrintStatistics(), and v8::internal::EmbeddedFileWriter::WriteBuiltin().
InstructionStartOf()
Address v8::internal::EmbeddedData::InstructionStartOf (Builtin builtin) const [inline]
Definition at line 14 of file embedded-data-inl.h.
                                                              {
  DCHECK(Builtins::IsBuiltinId(builtin));
  const struct LayoutDescription& desc = LayoutDescription(builtin);
  const uint8_t* result = RawCode() + desc.instruction_offset;
  DCHECK_LT(result, code_ + code_size_);
  return reinterpret_cast<Address>(result);
}
References code_, code_size_, v8::internal::DCHECK(), DCHECK_LT, v8::internal::EmbeddedData::LayoutDescription::instruction_offset, v8::internal::Builtins::IsBuiltinId(), LayoutDescription(), RawCode(), and v8::base::internal::result.
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), v8::internal::RegExpMacroAssemblerRISCV::CallCheckStackGuardState(), v8::internal::Builtins::EmbeddedEntryOf(), v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects(), v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::init_memcopy_functions(), v8::internal::Builtins::InitializeIsolateDataTables(), v8::internal::Code::InstructionStart(), InstructionStartOfBytecodeHandlers(), TryLookupCode(), and v8::internal::EmbeddedFileWriter::WriteBuiltin().
InstructionStartOfBytecodeHandlers()
Address v8::internal::EmbeddedData::InstructionStartOfBytecodeHandlers () const [inline]
Definition at line 45 of file embedded-data-inl.h.
                                                               {
  return InstructionStartOf(Builtin::kFirstBytecodeHandler);
}
References InstructionStartOf().
Referenced by v8::internal::StackFrameIteratorForProfiler::IsNoFrameBytecodeHandlerPc().
IsInCodeRange()
bool v8::internal::EmbeddedData::IsInCodeRange (Address pc) const [inline]
Definition at line 128 of file embedded-data.h.
                                       {
    Address start = reinterpret_cast<Address>(code_);
    return (start <= pc) && (pc < start + code_size_);
  }
References code_, and code_size_.
Referenced by AddressForHashing(), FromBlobForPc(), v8::internal::OffHeapInstructionStream::PcIsOffHeap(), v8::internal::OffHeapInstructionStream::TryGetAddressForHashing(), and TryLookupCode().
IsolateHash()
size_t v8::internal::EmbeddedData::IsolateHash () const [inline]
Definition at line 167 of file embedded-data.h.
                             {
    return *reinterpret_cast<const size_t*>(data_ + IsolateHashOffset());
  }
References data_, and IsolateHashOffset().
IsolateHashOffset()
static constexpr uint32_t v8::internal::EmbeddedData::IsolateHashOffset () [inline], [static], [constexpr]
Definition at line 236 of file embedded-data.h.
                                                {
    return EmbeddedBlobCodeHashOffset() + EmbeddedBlobCodeHashSize();
  }
References EmbeddedBlobCodeHashOffset(), and EmbeddedBlobCodeHashSize().
Referenced by CreateEmbeddedBlobDataHash(), IsolateHash(), LayoutDescriptionTableOffset(), and NewFromIsolate().
IsolateHashSize()
static constexpr uint32_t v8::internal::EmbeddedData::IsolateHashSize () [inline], [static], [constexpr]
Definition at line 239 of file embedded-data.h.
{ return kSizetSize; }
References v8::internal::kSizetSize.
Referenced by LayoutDescriptionTableOffset(), and NewFromIsolate().
LayoutDescription()
const LayoutDescription& v8::internal::EmbeddedData::LayoutDescription (Builtin builtin) const [inline], [private]
Definition at line 273 of file embedded-data.h.
                                                                    {
    const struct LayoutDescription* descs =
        reinterpret_cast<const struct LayoutDescription*>(
            data_ + LayoutDescriptionTableOffset());
    return descs[static_cast<int>(builtin)];
  }
References data_, and LayoutDescriptionTableOffset().
Referenced by InstructionEndOf(), InstructionSizeOf(), InstructionStartOf(), and MetadataStartOf().
LayoutDescriptionTableOffset()
static constexpr uint32_t v8::internal::EmbeddedData::LayoutDescriptionTableOffset () [inline], [static], [constexpr]
Definition at line 240 of file embedded-data.h.
                                                           {
    return IsolateHashOffset() + IsolateHashSize();
  }
References IsolateHashOffset(), and IsolateHashSize().
Referenced by BuiltinLookupEntryTableOffset(), LayoutDescription(), and NewFromIsolate().
LayoutDescriptionTableSize()
static constexpr uint32_t v8::internal::EmbeddedData::LayoutDescriptionTableSize () [inline], [static], [constexpr]
Definition at line 243 of file embedded-data.h.
                                                         {
    return sizeof(struct LayoutDescription) * kTableSize;
  }
References kTableSize.
Referenced by BuiltinLookupEntryTableOffset(), and NewFromIsolate().
MetadataStartOf()
Address v8::internal::EmbeddedData::MetadataStartOf (Builtin builtin) const [inline]
Definition at line 37 of file embedded-data-inl.h.
                                                           {
  DCHECK(Builtins::IsBuiltinId(builtin));
  const struct LayoutDescription& desc = LayoutDescription(builtin);
  const uint8_t* result = RawMetadata() + desc.metadata_offset;
  DCHECK_LE(desc.metadata_offset, data_size_);
  return reinterpret_cast<Address>(result);
}
References data_size_, v8::internal::DCHECK(), DCHECK_LE, v8::internal::Builtins::IsBuiltinId(), LayoutDescription(), v8::internal::EmbeddedData::LayoutDescription::metadata_offset, RawMetadata(), and v8::base::internal::result.
Referenced by v8::internal::Code::metadata_start().
NewFromIsolate()
EmbeddedData v8::internal::EmbeddedData::NewFromIsolate (Isolate * isolate) [static]
Definition at line 240 of file embedded-data.cc.
                                                          {
  Builtins* builtins = isolate->builtins();
  // Store instruction stream lengths and offsets.
  std::vector<struct LayoutDescription> layout_descriptions(kTableSize);
  std::vector<struct BuiltinLookupEntry> offset_descriptions(kTableSize);
  bool saw_unsafe_builtin = false;
  uint32_t raw_code_size = 0;
  uint32_t raw_data_size = 0;
  static_assert(Builtins::kAllBuiltinsAreIsolateIndependent);
  std::vector<Builtin> reordered_builtins;
  if (v8_flags.reorder_builtins &&
      BuiltinsCallGraph::Get()->all_hash_matched()) {
    DCHECK(v8_flags.turbo_profiling_input.value());
    // TODO(ishell, v8:13938): avoid the binary size overhead for non-mksnapshot
    // binaries.
    BuiltinsSorter sorter;
    std::vector<uint32_t> builtin_sizes;
    for (Builtin i = Builtins::kFirst; i <= Builtins::kLast; ++i) {
      Tagged<Code> code = builtins->code(i);
      uint32_t instruction_size =
          static_cast<uint32_t>(code->instruction_size());
      uint32_t padding_size = PadAndAlignCode(instruction_size);
      builtin_sizes.push_back(padding_size);
    }
    reordered_builtins = sorter.SortBuiltins(
        v8_flags.turbo_profiling_input.value(), builtin_sizes);
    CHECK_EQ(reordered_builtins.size(), Builtins::kBuiltinCount);
  }
  for (ReorderedBuiltinIndex embedded_index = 0;
       embedded_index < Builtins::kBuiltinCount; embedded_index++) {
    Builtin builtin;
    if (reordered_builtins.empty()) {
      builtin = static_cast<Builtin>(embedded_index);
    } else {
      builtin = reordered_builtins[embedded_index];
    }
    Tagged<Code> code = builtins->code(builtin);
    // Sanity-check that the given builtin is isolate-independent.
    if (!code->IsIsolateIndependent(isolate)) {
      saw_unsafe_builtin = true;
      fprintf(stderr, "%s is not isolate-independent.\n",
              Builtins::name(builtin));
    }
    uint32_t instruction_size = static_cast<uint32_t>(code->instruction_size());
    DCHECK_EQ(0, raw_code_size % kCodeAlignment);
    {
      // We use builtin id as index in layout_descriptions.
      const int builtin_id = static_cast<int>(builtin);
      struct LayoutDescription& layout_desc = layout_descriptions[builtin_id];
      layout_desc.instruction_offset = raw_code_size;
      layout_desc.instruction_length = instruction_size;
      layout_desc.metadata_offset = raw_data_size;
    }
    // Align the start of each section.
    raw_code_size += PadAndAlignCode(instruction_size);
    raw_data_size += PadAndAlignData(code->metadata_size());
    {
      // We use embedded index as index in offset_descriptions.
      struct BuiltinLookupEntry& offset_desc =
          offset_descriptions[embedded_index];
      offset_desc.end_offset = raw_code_size;
      offset_desc.builtin_id = static_cast<uint32_t>(builtin);
    }
  }
  CHECK_WITH_MSG(
      !saw_unsafe_builtin,
      "One or more builtins marked as isolate-independent either contains "
      "isolate-dependent code or aliases the off-heap trampoline register. "
      "If in doubt, ask jgruber@");
  // Allocate space for the code section, value-initialized to 0.
  static_assert(RawCodeOffset() == 0);
  const uint32_t blob_code_size = RawCodeOffset() + raw_code_size;
  uint8_t* const blob_code = new uint8_t[blob_code_size]();
  // Allocate space for the data section, value-initialized to 0.
  static_assert(
      IsAligned(FixedDataSize(), InstructionStream::kMetadataAlignment));
  const uint32_t blob_data_size = FixedDataSize() + raw_data_size;
  uint8_t* const blob_data = new uint8_t[blob_data_size]();
  // Initially zap the entire blob, effectively padding the alignment area
  // between two builtins with int3's (on x64/ia32).
  ZapCode(reinterpret_cast<Address>(blob_code), blob_code_size);
  // Hash relevant parts of the Isolate's heap and store the result.
  {
    static_assert(IsolateHashSize() == kSizetSize);
    const size_t hash = isolate->HashIsolateForEmbeddedBlob();
    std::memcpy(blob_data + IsolateHashOffset(), &hash, IsolateHashSize());
  }
  // Write the layout_descriptions tables.
  DCHECK_EQ(LayoutDescriptionTableSize(),
            sizeof(layout_descriptions[0]) * layout_descriptions.size());
  std::memcpy(blob_data + LayoutDescriptionTableOffset(),
              layout_descriptions.data(), LayoutDescriptionTableSize());
  // Write the builtin_offset_descriptions tables.
  DCHECK_EQ(BuiltinLookupEntryTableSize(),
            sizeof(offset_descriptions[0]) * offset_descriptions.size());
  std::memcpy(blob_data + BuiltinLookupEntryTableOffset(),
              offset_descriptions.data(), BuiltinLookupEntryTableSize());
  // .. and the variable-size data section.
  uint8_t* const raw_metadata_start = blob_data + RawMetadataOffset();
  static_assert(Builtins::kAllBuiltinsAreIsolateIndependent);
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
       ++builtin) {
    Tagged<Code> code = builtins->code(builtin);
    uint32_t offset =
        layout_descriptions[static_cast<int>(builtin)].metadata_offset;
    uint8_t* dst = raw_metadata_start + offset;
    DCHECK_LE(RawMetadataOffset() + offset + code->metadata_size(),
              blob_data_size);
    std::memcpy(dst, reinterpret_cast<uint8_t*>(code->metadata_start()),
                code->metadata_size());
  }
  CHECK_IMPLIES(
      kMaxPCRelativeCodeRangeInMB,
      static_cast<size_t>(raw_code_size) <= kMaxPCRelativeCodeRangeInMB * MB);
  // .. and the variable-size code section.
  uint8_t* const raw_code_start = blob_code + RawCodeOffset();
  static_assert(Builtins::kAllBuiltinsAreIsolateIndependent);
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
       ++builtin) {
    Tagged<Code> code = builtins->code(builtin);
    uint32_t offset =
        layout_descriptions[static_cast<int>(builtin)].instruction_offset;
    uint8_t* dst = raw_code_start + offset;
    DCHECK_LE(RawCodeOffset() + offset + code->instruction_size(),
              blob_code_size);
    std::memcpy(dst, reinterpret_cast<uint8_t*>(code->instruction_start()),
                code->instruction_size());
  }
  EmbeddedData d(blob_code, blob_code_size, blob_data, blob_data_size);
  // Fix up call targets that point to other embedded builtins.
  FinalizeEmbeddedCodeTargets(isolate, &d);
  // Hash the blob and store the result.
  {
    static_assert(EmbeddedBlobDataHashSize() == kSizetSize);
    const size_t data_hash = d.CreateEmbeddedBlobDataHash();
    std::memcpy(blob_data + EmbeddedBlobDataHashOffset(), &data_hash,
                EmbeddedBlobDataHashSize());
    static_assert(EmbeddedBlobCodeHashSize() == kSizetSize);
    const size_t code_hash = d.CreateEmbeddedBlobCodeHash();
    std::memcpy(blob_data + EmbeddedBlobCodeHashOffset(), &code_hash,
                EmbeddedBlobCodeHashSize());
    DCHECK_EQ(data_hash, d.CreateEmbeddedBlobDataHash());
    DCHECK_EQ(data_hash, d.EmbeddedBlobDataHash());
    DCHECK_EQ(code_hash, d.CreateEmbeddedBlobCodeHash());
    DCHECK_EQ(code_hash, d.EmbeddedBlobCodeHash());
  }
  if (DEBUG_BOOL) {
    for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
         ++builtin) {
      Tagged<Code> code = builtins->code(builtin);
      CHECK_EQ(d.InstructionSizeOf(builtin), code->instruction_size());
    }
  }
  // Ensure that InterpreterEntryTrampolineForProfiling is relocatable.
  // See v8_flags.interpreted_frames_native_stack for details.
  EnsureRelocatable(
      builtins->code(Builtin::kInterpreterEntryTrampolineForProfiling));
  if (v8_flags.serialization_statistics) d.PrintStatistics();
  return d;
}
References v8::internal::BuiltinsCallGraph::all_hash_matched(), BuiltinLookupEntryTableOffset(), BuiltinLookupEntryTableSize(), v8::internal::Isolate::builtins(), CHECK_EQ, CHECK_IMPLIES, CHECK_WITH_MSG, code(), v8::internal::Builtins::code(), CreateEmbeddedBlobCodeHash(), CreateEmbeddedBlobDataHash(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DEBUG_BOOL, EmbeddedBlobCodeHash(), EmbeddedBlobCodeHashOffset(), EmbeddedBlobCodeHashSize(), EmbeddedBlobDataHash(), EmbeddedBlobDataHashOffset(), EmbeddedBlobDataHashSize(), v8::internal::anonymous_namespace{embedded-data.cc}::EnsureRelocatable(), v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), FixedDataSize(), v8::internal::BuiltinsCallGraph::Get(), v8::internal::Isolate::HashIsolateForEmbeddedBlob(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::EmbeddedData::LayoutDescription::instruction_length, v8::internal::EmbeddedData::LayoutDescription::instruction_offset, InstructionSizeOf(), IsAligned(), IsolateHashOffset(), IsolateHashSize(), v8::internal::Builtins::kAllBuiltinsAreIsolateIndependent, v8::internal::Builtins::kBuiltinCount, v8::internal::kCodeAlignment, v8::internal::Builtins::kFirst, v8::internal::Builtins::kLast, v8::internal::kMaxPCRelativeCodeRangeInMB, v8::internal::InstructionStream::kMetadataAlignment, v8::internal::kSizetSize, kTableSize, LayoutDescriptionTableOffset(), LayoutDescriptionTableSize(), v8::internal::MB, v8::internal::EmbeddedData::LayoutDescription::metadata_offset, v8::internal::Builtins::name(), PadAndAlignCode(), PadAndAlignData(), PrintStatistics(), RawCodeOffset(), RawMetadataOffset(), v8::internal::BuiltinsSorter::SortBuiltins(), v8::internal::v8_flags, and v8::internal::ZapCode().
Referenced by v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream().
PadAndAlignCode()
static constexpr int v8::internal::EmbeddedData::PadAndAlignCode (int size) [inline], [static], [constexpr], [private]
Definition at line 290 of file embedded-data.h.
                                                 {
    // Ensure we have at least one byte trailing the actual builtin
    // instructions which we can later fill with int3.
    return RoundUp<kCodeAlignment>(size + 1);
  }
References size().
Referenced by NewFromIsolate(), and PaddedInstructionSizeOf().
PadAndAlignData()
static constexpr int v8::internal::EmbeddedData::PadAndAlignData (int size) [inline], [static], [constexpr], [private]
Definition at line 295 of file embedded-data.h.
                                                 {
    // Ensure we have at least one byte trailing the actual builtin
    // instructions which we can later fill with int3.
    return RoundUp<InstructionStream::kMetadataAlignment>(size);
  }
References size().
Referenced by NewFromIsolate().
PaddedInstructionSizeOf()
uint32_t v8::internal::EmbeddedData::PaddedInstructionSizeOf (Builtin builtin) const [inline]
Definition at line 55 of file embedded-data-inl.h.
                                                                    {
  uint32_t size = InstructionSizeOf(builtin);
  CHECK_NE(size, 0);
  return PadAndAlignCode(size);
}
References CHECK_NE, InstructionSizeOf(), PadAndAlignCode(), and size().
Referenced by TryLookupCode(), and v8::internal::EmbeddedFileWriter::WriteBuiltin().
PrintStatistics()
void v8::internal::EmbeddedData::PrintStatistics () const [private]
Definition at line 450 of file embedded-data.cc.
                                         {
  DCHECK(v8_flags.serialization_statistics);
  constexpr int kCount = Builtins::kBuiltinCount;
  int sizes[kCount];
  static_assert(Builtins::kAllBuiltinsAreIsolateIndependent);
  for (int i = 0; i < kCount; i++) {
    sizes[i] = InstructionSizeOf(Builtins::FromInt(i));
  }
  // Sort for percentiles.
  std::sort(&sizes[0], &sizes[kCount]);
  const int k50th = kCount * 0.5;
  const int k75th = kCount * 0.75;
  const int k90th = kCount * 0.90;
  const int k99th = kCount * 0.99;
  PrintF("EmbeddedData:\n");
  PrintF(" Total size: %d\n",
         static_cast<int>(code_size() + data_size()));
  PrintF(" Data size: %d\n", static_cast<int>(data_size()));
  PrintF(" Code size: %d\n", static_cast<int>(code_size()));
  PrintF(" Instruction size (50th percentile): %d\n", sizes[k50th]);
  PrintF(" Instruction size (75th percentile): %d\n", sizes[k75th]);
  PrintF(" Instruction size (90th percentile): %d\n", sizes[k90th]);
  PrintF(" Instruction size (99th percentile): %d\n", sizes[k99th]);
  PrintF("\n");
}
References code_size(), data_size(), v8::internal::DCHECK(), v8::internal::Builtins::FromInt(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, InstructionSizeOf(), v8::internal::Builtins::kAllBuiltinsAreIsolateIndependent, v8::internal::Builtins::kBuiltinCount, v8::internal::PrintF(), v8::base::sort(), and v8::internal::v8_flags.
Referenced by NewFromIsolate().
RawCode()
const uint8_t* v8::internal::EmbeddedData::RawCode () const [inline], [private]
Definition at line 271 of file embedded-data.h.
{ return code_ + RawCodeOffset(); }
References code_, and RawCodeOffset().
Referenced by InstructionEndOf(), InstructionStartOf(), and TryLookupCode().
RawCodeOffset()
static constexpr uint32_t v8::internal::EmbeddedData::RawCodeOffset () [inline], [static], [constexpr]
Definition at line 259 of file embedded-data.h.
{ return 0; }
Referenced by NewFromIsolate(), and RawCode().
RawMetadata()
const uint8_t* v8::internal::EmbeddedData::RawMetadata () const [inline], [private]
Definition at line 288 of file embedded-data.h.
{ return data_ + RawMetadataOffset(); }
References data_, and RawMetadataOffset().
Referenced by MetadataStartOf().
RawMetadataOffset()
static constexpr uint32_t v8::internal::EmbeddedData::RawMetadataOffset () [inline], [static], [constexpr]
Definition at line 256 of file embedded-data.h.
{ return FixedDataSize(); }
References FixedDataSize().
Referenced by NewFromIsolate(), and RawMetadata().
TryLookupCode()
Builtin v8::internal::EmbeddedData::TryLookupCode (Address address) const
Definition at line 16 of file embedded-data.cc.
                                                         {
  if (!IsInCodeRange(address)) return Builtin::kNoBuiltinId;
  // Note: Addresses within the padding section between builtins (i.e. within
  // start + size <= address < start + padded_size) are interpreted as belonging
  // to the preceding builtin.
  uint32_t offset =
      static_cast<uint32_t>(address - reinterpret_cast<Address>(RawCode()));
  const struct BuiltinLookupEntry* start =
      BuiltinLookupEntry(static_cast<ReorderedBuiltinIndex>(0));
  const struct BuiltinLookupEntry* end = start + kTableSize;
  const struct BuiltinLookupEntry* desc =
      std::upper_bound(start, end, offset,
                       [](uint32_t o, const struct BuiltinLookupEntry& desc) {
                         return o < desc.end_offset;
                       });
  Builtin builtin = static_cast<Builtin>(desc->builtin_id);
  DCHECK_LT(address,
            InstructionStartOf(builtin) + PaddedInstructionSizeOf(builtin));
  DCHECK_GE(address, InstructionStartOf(builtin));
  return builtin;
}
References v8::internal::EmbeddedData::BuiltinLookupEntry::builtin_id, BuiltinLookupEntry(), DCHECK_GE, DCHECK_LT, v8::internal::compiler::end(), v8::internal::EmbeddedData::BuiltinLookupEntry::end_offset, InstructionStartOf(), IsInCodeRange(), v8::internal::kNoBuiltinId, kTableSize, PaddedInstructionSizeOf(), and RawCode().
Referenced by v8::internal::OffHeapInstructionStream::TryLookupCode().
Member Data Documentation
code_
const uint8_t* v8::internal::EmbeddedData::code_ [private]
Definition at line 305 of file embedded-data.h.
Referenced by AddressForHashing(), code(), CreateEmbeddedBlobCodeHash(), Dispose(), InstructionEndOf(), InstructionEndOfBytecodeHandlers(), InstructionStartOf(), IsInCodeRange(), and RawCode().
code_size_
uint32_t v8::internal::EmbeddedData::code_size_ [private]
Definition at line 306 of file embedded-data.h.
Referenced by code_size(), CreateEmbeddedBlobCodeHash(), InstructionEndOf(), InstructionEndOfBytecodeHandlers(), InstructionStartOf(), and IsInCodeRange().
data_
const uint8_t* v8::internal::EmbeddedData::data_ [private]
Definition at line 312 of file embedded-data.h.
Referenced by BuiltinLookupEntry(), CreateEmbeddedBlobDataHash(), data(), Dispose(), EmbeddedBlobCodeHash(), EmbeddedBlobDataHash(), IsolateHash(), LayoutDescription(), and RawMetadata().
data_size_
uint32_t v8::internal::EmbeddedData::data_size_ [private]
Definition at line 313 of file embedded-data.h.
Referenced by CreateEmbeddedBlobDataHash(), data_size(), and MetadataStartOf().
kTableSize
constexpr uint32_t v8::internal::EmbeddedData::kTableSize = Builtins::kBuiltinCount [static], [constexpr]
Definition at line 229 of file embedded-data.h.
Referenced by BuiltinLookupEntryTableSize(), LayoutDescriptionTableSize(), NewFromIsolate(), and TryLookupCode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/embedded/embedded-data.h
/mnt/V8SourceCode/src/snapshot/embedded/embedded-data-inl.h
/mnt/V8SourceCode/src/snapshot/embedded/embedded-data.cc