v8::internal::anonymous_namespace{mark-compact.cc}::SharedStructTypeRegistryCleaner Class Reference
Public Member Functions
SharedStructTypeRegistryCleaner (Heap *heap)
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) override
void VisitRootPointers (Root root, const char *description, OffHeapObjectSlot start, OffHeapObjectSlot end) override
int ElementsRemoved () const
Private Attributes
Heap * heap_
int elements_removed_ = 0
Additional Inherited Members
Detailed Description
Definition at line 2791 of file mark-compact.cc.
Constructor & Destructor Documentation
SharedStructTypeRegistryCleaner()
v8::internal::anonymous_namespace{mark-compact.cc}::SharedStructTypeRegistryCleaner::SharedStructTypeRegistryCleaner (Heap * heap) [inline], [explicit]
Definition at line 2793 of file mark-compact.cc.
: heap_(heap) {}
Member Function Documentation
ElementsRemoved()
int v8::internal::anonymous_namespace{mark-compact.cc}::SharedStructTypeRegistryCleaner::ElementsRemoved () const [inline]
Definition at line 2823 of file mark-compact.cc.
{ return elements_removed_; }
Referenced by v8::internal::anonymous_namespace{mark-compact.cc}::ClearSharedStructTypeRegistryJobItem::Run().
VisitRootPointers() [1/2]
void v8::internal::anonymous_namespace{mark-compact.cc}::SharedStructTypeRegistryCleaner::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 2795 of file mark-compact.cc.
                                                                            {
    UNREACHABLE();
  }
References UNREACHABLE.
VisitRootPointers() [2/2]
void v8::internal::anonymous_namespace{mark-compact.cc}::SharedStructTypeRegistryCleaner::VisitRootPointers (Root root, const char * description, OffHeapObjectSlot start, OffHeapObjectSlot end) [inline], [override], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 2800 of file mark-compact.cc.
                                                         {
    DCHECK_EQ(root, Root::kSharedStructTypeRegistry);
    // The SharedStructTypeRegistry holds the canonical SharedStructType
    // instance maps weakly. Visit all Map pointers in [start, end), deleting
    // it if unmarked.
    auto* marking_state = heap_->marking_state();
    Isolate* const isolate = heap_->isolate();
    for (OffHeapObjectSlot p = start; p < end; p++) {
      Tagged<Object> o = p.load(isolate);
      DCHECK(!IsString(o));
      if (IsMap(o)) {
        Tagged<HeapObject> map = Cast<Map>(o);
        DCHECK(HeapLayout::InAnySharedSpace(map));
        if (MarkingHelper::IsMarkedOrAlwaysLive(heap_, marking_state, map))
          continue;
        elements_removed_++;
        p.store(SharedStructTypeRegistry::deleted_element());
      }
    }
  }
References DCHECK, DCHECK_EQ, v8::internal::compiler::end(), and v8::internal::Factory::isolate().
Member Data Documentation
elements_removed_
int v8::internal::anonymous_namespace{mark-compact.cc}::SharedStructTypeRegistryCleaner::elements_removed_ = 0 [private]
Definition at line 2827 of file mark-compact.cc.
heap_
Heap* v8::internal::anonymous_namespace{mark-compact.cc}::SharedStructTypeRegistryCleaner::heap_ [private]
Definition at line 2826 of file mark-compact.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc