cppgc::internal::HeapVisitor< Derived > Class Template Reference
#include <heap-visitor.h>
Public Member Functions
void Traverse (RawHeap &heap)
void Traverse (BaseSpace &space)
void Traverse (BasePage &page)
Protected Member Functions
bool VisitHeap (RawHeap &)
bool VisitNormalPageSpace (NormalPageSpace &)
bool VisitLargePageSpace (LargePageSpace &)
bool VisitNormalPage (NormalPage &)
bool VisitLargePage (LargePage &)
bool VisitHeapObjectHeader (HeapObjectHeader &)
Private Member Functions
Derived & ToDerived ()
bool VisitHeapImpl (RawHeap &heap)
bool VisitNormalPageSpaceImpl (NormalPageSpace &space)
bool VisitLargePageSpaceImpl (LargePageSpace &space)
bool VisitNormalPageImpl (NormalPage &page)
bool VisitLargePageImpl (LargePage &page)
bool VisitHeapObjectHeaderImpl (HeapObjectHeader &header)
Detailed Description
template<typename Derived>
class cppgc::internal::HeapVisitor< Derived >
Definition at line 20 of file heap-visitor.h.
Member Function Documentation
ToDerived()
template<typename Derived >
Derived& cppgc::internal::HeapVisitor< Derived >::ToDerived () [inline], [private]
Definition at line 65 of file heap-visitor.h.
{ return static_cast<Derived&>(*this); }
Referenced by cppgc::internal::HeapVisitor< Derived >::VisitHeapImpl(), cppgc::internal::HeapVisitor< Derived >::VisitHeapObjectHeaderImpl(), cppgc::internal::HeapVisitor< Derived >::VisitLargePageImpl(), cppgc::internal::HeapVisitor< Derived >::VisitLargePageSpaceImpl(), cppgc::internal::HeapVisitor< Derived >::VisitNormalPageImpl(), and cppgc::internal::HeapVisitor< Derived >::VisitNormalPageSpaceImpl().
Traverse() [1/3]
template<typename Derived >
void cppgc::internal::HeapVisitor< Derived >::Traverse (BasePage & page) [inline]
Definition at line 40 of file heap-visitor.h.
                                {
    if (page.is_large()) {
      auto* large_page = LargePage::From(&page);
      if (VisitLargePageImpl(*large_page)) return;
      VisitHeapObjectHeaderImpl(*large_page->ObjectHeader());
    } else {
      auto* normal_page = NormalPage::From(&page);
      if (VisitNormalPageImpl(*normal_page)) return;
      for (auto& header : *normal_page) {
        VisitHeapObjectHeaderImpl(header);
      }
    }
  }
References cppgc::internal::NormalPage::From(), cppgc::internal::LargePage::From(), cppgc::internal::BasePage::is_large(), cppgc::internal::HeapVisitor< Derived >::VisitHeapObjectHeaderImpl(), cppgc::internal::HeapVisitor< Derived >::VisitLargePageImpl(), and cppgc::internal::HeapVisitor< Derived >::VisitNormalPageImpl().
Traverse() [2/3]
template<typename Derived >
void cppgc::internal::HeapVisitor< Derived >::Traverse (BaseSpace & space) [inline]
Definition at line 29 of file heap-visitor.h.
                                  {
    const bool is_stopped =
        space.is_large()
            ? VisitLargePageSpaceImpl(LargePageSpace::From(space))
            : VisitNormalPageSpaceImpl(NormalPageSpace::From(space));
    if (is_stopped) return;
    for (auto* page : space) {
      Traverse(*page);
    }
  }
References cppgc::internal::NormalPageSpace::From(), cppgc::internal::LargePageSpace::From(), space, cppgc::internal::HeapVisitor< Derived >::Traverse(), cppgc::internal::HeapVisitor< Derived >::VisitLargePageSpaceImpl(), and cppgc::internal::HeapVisitor< Derived >::VisitNormalPageSpaceImpl().
Traverse() [3/3]
template<typename Derived >
void cppgc::internal::HeapVisitor< Derived >::Traverse (RawHeap & heap) [inline]
Definition at line 22 of file heap-visitor.h.
                               {
    if (VisitHeapImpl(heap)) return;
    for (auto& space : heap) {
      Traverse(*space.get());
    }
  }
References space, and cppgc::internal::HeapVisitor< Derived >::VisitHeapImpl().
Referenced by v8::internal::CppGraphBuilderImpl::Run(), and cppgc::internal::HeapVisitor< Derived >::Traverse().
VisitHeap()
template<typename Derived >
bool cppgc::internal::HeapVisitor< Derived >::VisitHeap (RawHeap &) [inline], [protected]
Definition at line 57 of file heap-visitor.h.
{ return false; }
VisitHeapImpl()
template<typename Derived >
bool cppgc::internal::HeapVisitor< Derived >::VisitHeapImpl (RawHeap & heap) [inline], [private]
Definition at line 67 of file heap-visitor.h.
{ return ToDerived().VisitHeap(heap); }
References cppgc::internal::HeapVisitor< Derived >::ToDerived().
Referenced by cppgc::internal::HeapVisitor< Derived >::Traverse().
VisitHeapObjectHeader()
template<typename Derived >
bool cppgc::internal::HeapVisitor< Derived >::VisitHeapObjectHeader (HeapObjectHeader &) [inline], [protected]
Definition at line 62 of file heap-visitor.h.
{ return false; }
VisitHeapObjectHeaderImpl()
template<typename Derived >
bool cppgc::internal::HeapVisitor< Derived >::VisitHeapObjectHeaderImpl (HeapObjectHeader & header) [inline], [private]
Definition at line 80 of file heap-visitor.h.
                                                           {
    return ToDerived().VisitHeapObjectHeader(header);
  }
References cppgc::internal::HeapVisitor< Derived >::ToDerived().
Referenced by cppgc::internal::HeapVisitor< Derived >::Traverse().
VisitLargePage()
template<typename Derived >
bool cppgc::internal::HeapVisitor< Derived >::VisitLargePage (LargePage &) [inline], [protected]
Definition at line 61 of file heap-visitor.h.
{ return false; }
VisitLargePageImpl()
template<typename Derived >
bool cppgc::internal::HeapVisitor< Derived >::VisitLargePageImpl (LargePage & page) [inline], [private]
Definition at line 77 of file heap-visitor.h.
                                           {
    return ToDerived().VisitLargePage(page);
  }
References cppgc::internal::HeapVisitor< Derived >::ToDerived().
Referenced by cppgc::internal::HeapVisitor< Derived >::Traverse().
VisitLargePageSpace()
template<typename Derived >
bool cppgc::internal::HeapVisitor< Derived >::VisitLargePageSpace (LargePageSpace &) [inline], [protected]
Definition at line 59 of file heap-visitor.h.
{ return false; }
VisitLargePageSpaceImpl()
template<typename Derived >
bool cppgc::internal::HeapVisitor< Derived >::VisitLargePageSpaceImpl (LargePageSpace & space) [inline], [private]
Definition at line 71 of file heap-visitor.h.
                                                      {
    return ToDerived().VisitLargePageSpace(space);
  }
References space, and cppgc::internal::HeapVisitor< Derived >::ToDerived().
Referenced by cppgc::internal::HeapVisitor< Derived >::Traverse().
VisitNormalPage()
template<typename Derived >
bool cppgc::internal::HeapVisitor< Derived >::VisitNormalPage (NormalPage &) [inline], [protected]
Definition at line 60 of file heap-visitor.h.
{ return false; }
VisitNormalPageImpl()
template<typename Derived >
bool cppgc::internal::HeapVisitor< Derived >::VisitNormalPageImpl (NormalPage & page) [inline], [private]
Definition at line 74 of file heap-visitor.h.
                                             {
    return ToDerived().VisitNormalPage(page);
  }
References cppgc::internal::HeapVisitor< Derived >::ToDerived().
Referenced by cppgc::internal::HeapVisitor< Derived >::Traverse().
VisitNormalPageSpace()
template<typename Derived >
bool cppgc::internal::HeapVisitor< Derived >::VisitNormalPageSpace (NormalPageSpace &) [inline], [protected]
Definition at line 58 of file heap-visitor.h.
{ return false; }
VisitNormalPageSpaceImpl()
template<typename Derived >
bool cppgc::internal::HeapVisitor< Derived >::VisitNormalPageSpaceImpl (NormalPageSpace & space) [inline], [private]
Definition at line 68 of file heap-visitor.h.
                                                        {
    return ToDerived().VisitNormalPageSpace(space);
  }
References space, and cppgc::internal::HeapVisitor< Derived >::ToDerived().
Referenced by cppgc::internal::HeapVisitor< Derived >::Traverse().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/heap-visitor.h