v8::internal::WriteBarrier Class Reference
#include <heap-write-barrier.h>
Static Public Member Functions
static void EphemeronKeyWriteBarrierFromCode (Address raw_object, Address key_slot_address, Isolate *isolate)
static int MarkingFromCode (Address raw_host, Address raw_slot)
static int IndirectPointerMarkingFromCode (Address raw_host, Address raw_slot, Address raw_tag)
static int SharedMarkingFromCode (Address raw_host, Address raw_slot)
static int SharedFromCode (Address raw_host, Address raw_slot)
static WriteBarrierMode GetWriteBarrierModeForObject (Tagged< HeapObject > object, const DisallowGarbageCollection &promise)
template<typename T >
static void ForValue (Tagged< HeapObject > host, MaybeObjectSlot slot, Tagged< T > value, WriteBarrierMode mode)
template<typename T >
static void ForValue (HeapObjectLayout *host, TaggedMemberBase *slot, Tagged< T > value, WriteBarrierMode mode)
static void ForEphemeronHashTable (Tagged< EphemeronHashTable > host, ObjectSlot slot, Tagged< Object > value, WriteBarrierMode mode)
static void ForRelocInfo (Tagged< InstructionStream > host, RelocInfo *rinfo, Tagged< HeapObject > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
static void ForDescriptorArray (Tagged< DescriptorArray >, int number_of_own_descriptors)
static void ForArrayBufferExtension (Tagged< JSArrayBuffer > host, ArrayBufferExtension *extension)
static void ForExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
static void ForIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, Tagged< HeapObject > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
static void ForProtectedPointer (Tagged< TrustedObject > host, ProtectedPointerSlot slot, Tagged< TrustedObject > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
static void ForCppHeapPointer (Tagged< CppHeapPointerWrapperObjectT > host, CppHeapPointerSlot slot, void *value)
static void ForJSDispatchHandle (Tagged< HeapObject > host, JSDispatchHandle handle, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
template<typename TSlot >
static void ForRange (Heap *heap, Tagged< HeapObject > object, TSlot start, TSlot end)
static MarkingBarrier * SetForThread (MarkingBarrier *marking_barrier)
static MarkingBarrier * CurrentMarkingBarrier (Tagged< HeapObject > verification_candidate)
static void MarkingFromTracedHandle (Tagged< Object > value)
static void GenerationalForRelocInfo (Tagged< InstructionStream > host, RelocInfo *rinfo, Tagged< HeapObject > object)
static void SharedForRelocInfo (Tagged< InstructionStream > host, RelocInfo *, Tagged< HeapObject > value)
static void MarkingForTesting (Tagged< HeapObject > host, ObjectSlot, Tagged< Object > value)
Static Public Attributes
static constexpr bool kUninterestingPagesCanBeSkipped = true
Static Private Member Functions
static bool PageFlagsAreConsistent (Tagged< HeapObject > object)
static bool IsImmortalImmovableHeapObject (Tagged< HeapObject > object)
static bool IsMarking (Tagged< HeapObject > object)
static void Marking (Tagged< HeapObject > host, HeapObjectSlot, Tagged< HeapObject > value)
static void Marking (Tagged< HeapObject > host, MaybeObjectSlot, Tagged< MaybeObject > value)
static void MarkingForRelocInfo (Tagged< InstructionStream > host, RelocInfo *, Tagged< HeapObject > value)
static void Marking (Tagged< HeapObject > host, ExternalPointerSlot slot)
static void Marking (Tagged< HeapObject > host, IndirectPointerSlot slot)
static void Marking (Tagged< TrustedObject > host, ProtectedPointerSlot slot, Tagged< TrustedObject > value)
static void Marking (Tagged< HeapObject > host, JSDispatchHandle handle)
static void MarkingSlow (Tagged< HeapObject > host, HeapObjectSlot, Tagged< HeapObject > value)
static void MarkingSlow (Tagged< InstructionStream > host, RelocInfo *, Tagged< HeapObject > value)
static void MarkingSlow (Tagged< JSArrayBuffer > host, ArrayBufferExtension *)
static void MarkingSlow (Tagged< DescriptorArray >, int number_of_own_descriptors)
static void MarkingSlow (Tagged< HeapObject > host, ExternalPointerSlot slot)
static void MarkingSlow (Tagged< HeapObject > host, IndirectPointerSlot slot)
static void MarkingSlow (Tagged< TrustedObject > host, ProtectedPointerSlot slot, Tagged< TrustedObject > value)
static void MarkingSlow (Tagged< HeapObject > host, JSDispatchHandle handle)
static void MarkingSlowFromTracedHandle (Tagged< HeapObject > value)
static void MarkingSlowFromCppHeapWrappable (Heap *heap, Tagged< CppHeapPointerWrapperObjectT > host, CppHeapPointerSlot slot, void *object)
static void GenerationalBarrierSlow (Tagged< HeapObject > object, Address slot, Tagged< HeapObject > value)
static void GenerationalBarrierForCppHeapPointer (Tagged< CppHeapPointerWrapperObjectT > host, void *value)
static void SharedSlow (Tagged< TrustedObject > host, ProtectedPointerSlot slot, Tagged< TrustedObject > value)
static void SharedSlow (Tagged< InstructionStream > host, RelocInfo *, Tagged< HeapObject > value)
static void SharedHeapBarrierSlow (Tagged< HeapObject > object, Address slot)
static void CombinedWriteBarrierInternal (Tagged< HeapObject > host, HeapObjectSlot slot, Tagged< HeapObject > value, WriteBarrierMode mode)
static void CombinedGenerationalAndSharedBarrierSlow (Tagged< HeapObject > object, Address slot, Tagged< HeapObject > value)
static void CombinedGenerationalAndSharedEphemeronBarrierSlow (Tagged< EphemeronHashTable > table, Address slot, Tagged< HeapObject > value)
static void GenerationalBarrierForCodeSlow (Tagged< InstructionStream > host, RelocInfo *rinfo, Tagged< HeapObject > value)
Detailed Description
Definition at line 36 of file heap-write-barrier.h.
Member Function Documentation
CombinedGenerationalAndSharedBarrierSlow()
void v8::internal::WriteBarrier::CombinedGenerationalAndSharedBarrierSlow (Tagged< HeapObject > object, Address slot, Tagged< HeapObject > value) [static], [private]
Definition at line 358 of file heap-write-barrier.cc.
                                                                       {
  if (HeapLayout::InYoungGeneration(value)) {
    GenerationalBarrierSlow(object, slot, value);
  } else {
    DCHECK(MemoryChunk::FromHeapObject(value)->InWritableSharedSpace());
    DCHECK(!HeapLayout::InWritableSharedSpace(object));
    SharedHeapBarrierSlow(object, slot);
  }
}
References v8::internal::DCHECK(), v8::internal::MemoryChunk::FromHeapObject(), GenerationalBarrierSlow(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::HeapLayout::InYoungGeneration(), SharedHeapBarrierSlow(), and v8::internal::value.
Referenced by CombinedWriteBarrierInternal().
CombinedGenerationalAndSharedEphemeronBarrierSlow()
void v8::internal::WriteBarrier::CombinedGenerationalAndSharedEphemeronBarrierSlow (Tagged< EphemeronHashTable > table, Address slot, Tagged< HeapObject > value) [static], [private]
Definition at line 340 of file heap-write-barrier.cc.
                                                                              {
  SLOW_DCHECK_IMPLIES(kUninterestingPagesCanBeSkipped,
                      MemoryChunk::FromHeapObject(table)->GetFlags() &
                          MemoryChunk::kPointersFromHereAreInterestingMask);
  if (HeapLayout::InYoungGeneration(value)) {
    MutablePageMetadata* table_chunk =
        MutablePageMetadata::FromHeapObject(table);
    table_chunk->heap()->ephemeron_remembered_set()->RecordEphemeronKeyWrite(
        table, slot);
  } else {
    DCHECK(MemoryChunk::FromHeapObject(value)->InWritableSharedSpace());
    DCHECK(!HeapLayout::InWritableSharedSpace(table));
    SharedHeapBarrierSlow(table, slot);
  }
}
References v8::internal::DCHECK(), v8::internal::Heap::ephemeron_remembered_set(), v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunkMetadata::heap(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::MemoryChunk::kPointersFromHereAreInterestingMask, kUninterestingPagesCanBeSkipped, v8::internal::EphemeronRememberedSet::RecordEphemeronKeyWrite(), SharedHeapBarrierSlow(), SLOW_DCHECK_IMPLIES, and v8::internal::value.
Referenced by ForEphemeronHashTable().
CombinedWriteBarrierInternal()
void v8::internal::WriteBarrier::CombinedWriteBarrierInternal (Tagged< HeapObject > host, HeapObjectSlot slot, Tagged< HeapObject > value, WriteBarrierMode mode) [inline], [static], [private]
Definition at line 25 of file heap-write-barrier-inl.h.
                                                                       {
  DCHECK_EQ(mode, UPDATE_WRITE_BARRIER);
  MemoryChunk* host_chunk = MemoryChunk::FromHeapObject(host);
  MemoryChunk* value_chunk = MemoryChunk::FromHeapObject(value);
  const bool is_marking = host_chunk->IsMarking();
  if (v8_flags.sticky_mark_bits) {
    // TODO(333906585): Support shared barrier.
    if (!HeapLayout::InYoungGeneration(host_chunk, host) &&
        HeapLayout::InYoungGeneration(value_chunk, value)) {
      // Generational or shared heap write barrier (old-to-new or
      // old-to-shared).
      CombinedGenerationalAndSharedBarrierSlow(host, slot.address(), value);
    }
  } else {
    const bool pointers_from_here_are_interesting =
        !host_chunk->IsYoungOrSharedChunk();
    if (pointers_from_here_are_interesting &&
        value_chunk->IsYoungOrSharedChunk()) {
      // Generational or shared heap write barrier (old-to-new or
      // old-to-shared).
      CombinedGenerationalAndSharedBarrierSlow(host, slot.address(), value);
    }
  }
  // Marking barrier: mark value & record slots when marking is on.
  if (V8_UNLIKELY(is_marking)) {
    MarkingSlow(host, HeapObjectSlot(slot), value);
  }
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), CombinedGenerationalAndSharedBarrierSlow(), DCHECK_EQ, v8::internal::MemoryChunk::FromHeapObject(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::MemoryChunk::IsMarking(), v8::internal::MemoryChunk::IsYoungOrSharedChunk(), MarkingSlow(), mode(), v8::internal::UPDATE_WRITE_BARRIER, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::value.
Referenced by ForValue().
CurrentMarkingBarrier()
MarkingBarrier * v8::internal::WriteBarrier::CurrentMarkingBarrier (Tagged< HeapObject > verification_candidate) [static]
Definition at line 26 of file heap-write-barrier.cc.
                                               {
  MarkingBarrier* marking_barrier = current_marking_barrier;
  DCHECK_NOT_NULL(marking_barrier);
#if DEBUG
  if (!verification_candidate.is_null() &&
      !HeapLayout::InAnySharedSpace(verification_candidate)) {
    Heap* host_heap =
        MutablePageMetadata::FromHeapObject(verification_candidate)->heap();
    LocalHeap* local_heap = LocalHeap::Current();
    if (!local_heap) local_heap = host_heap->main_thread_local_heap();
    DCHECK_EQ(marking_barrier, local_heap->marking_barrier());
  }
#endif // DEBUG
  return marking_barrier;
}
References v8::internal::anonymous_namespace{heap-write-barrier.cc}::current_marking_barrier, DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::MemoryChunkMetadata::heap(), v8::internal::HeapLayout::InAnySharedSpace(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::Heap::main_thread_local_heap(), and v8::internal::LocalHeap::marking_barrier().
Referenced by ForCppHeapPointer(), v8::internal::anonymous_namespace{heap-write-barrier.cc}::ForRangeImpl(), IndirectPointerMarkingFromCode(), v8::internal::MarkingBarrier::IsCurrentMarkingBarrier(), MarkingFromCode(), MarkingSlow(), MarkingSlowFromCppHeapWrappable(), MarkingSlowFromTracedHandle(), and SharedMarkingFromCode().
EphemeronKeyWriteBarrierFromCode()
void v8::internal::WriteBarrier::EphemeronKeyWriteBarrierFromCode (Address raw_object, Address key_slot_address, Isolate * isolate) [static]
Definition at line 386 of file heap-write-barrier.cc.
                                                                      {
  Tagged<EphemeronHashTable> table =
      Cast<EphemeronHashTable>(Tagged<Object>(raw_object));
  ObjectSlot key_slot(key_slot_address);
  ForEphemeronHashTable(table, key_slot, *key_slot, UPDATE_WRITE_BARRIER);
}
References ForEphemeronHashTable(), and v8::internal::UPDATE_WRITE_BARRIER.
ForArrayBufferExtension()
void v8::internal::WriteBarrier::ForArrayBufferExtension (Tagged< JSArrayBuffer > host, ArrayBufferExtension * extension) [inline], [static]
Definition at line 297 of file heap-write-barrier-inl.h.
                                                                            {
  if (!extension || V8_LIKELY(!IsMarking(host))) {
    return;
  }
  MarkingSlow(host, extension);
}
References IsMarking(), MarkingSlow(), and V8_LIKELY.
ForCppHeapPointer()
void v8::internal::WriteBarrier::ForCppHeapPointer (Tagged< CppHeapPointerWrapperObjectT > host, CppHeapPointerSlot slot, void * value) [inline], [static]
Definition at line 352 of file heap-write-barrier-inl.h.
                                                                           {
  // Note: this is currently a combined barrier for marking both the
  // CppHeapPointerTable entry and the referenced object.
  if (V8_LIKELY(!IsMarking(host))) {
#if defined(CPPGC_YOUNG_GENERATION)
    // There is no young-gen CppHeapPointerTable space so we should not mark
    // the table entry in this case.
    if (value) {
      GenerationalBarrierForCppHeapPointer(host, value);
    }
#endif
    return;
  }
  MarkingBarrier* marking_barrier = CurrentMarkingBarrier(host);
  if (marking_barrier->is_minor()) {
    // TODO(v8:13012): We do not currently mark Oilpan objects while MinorMS is
    // active. Once Oilpan uses a generational GC with incremental marking and
    // unified heap, this barrier will be needed again.
    return;
  }
  MarkingSlowFromCppHeapWrappable(marking_barrier->heap(), host, slot, value);
}
References CurrentMarkingBarrier(), GenerationalBarrierForCppHeapPointer(), v8::internal::MarkingBarrier::heap(), v8::internal::MarkingBarrier::is_minor(), IsMarking(), MarkingSlowFromCppHeapWrappable(), V8_LIKELY, and v8::internal::value.
Referenced by v8::internal::CppHeapObjectWrapper::SetCppHeapWrappable().
ForDescriptorArray()
void v8::internal::WriteBarrier::ForDescriptorArray (Tagged< DescriptorArray > descriptor_array, int number_of_own_descriptors) [inline], [static]
Definition at line 305 of file heap-write-barrier-inl.h.
                                                                     {
  if (V8_LIKELY(!IsMarking(descriptor_array))) {
    return;
  }
  MarkingSlow(descriptor_array, number_of_own_descriptors);
}
References IsMarking(), MarkingSlow(), and V8_LIKELY.
Referenced by v8::internal::Map::AppendDescriptor(), v8::internal::Map::EnsureDescriptorSlack(), v8::internal::Map::ReplaceDescriptors(), and v8::internal::Map::SetInstanceDescriptors().
ForEphemeronHashTable()
void v8::internal::WriteBarrier::ForEphemeronHashTable (Tagged< EphemeronHashTable > host, ObjectSlot slot, Tagged< Object > value, WriteBarrierMode mode) [inline], [static]
Definition at line 138 of file heap-write-barrier-inl.h.
                                                                {
  if (mode == SKIP_WRITE_BARRIER) {
    SLOW_DCHECK(!WriteBarrier::IsRequired(host, value));
    return;
  }
  DCHECK_EQ(mode, UPDATE_WRITE_BARRIER);
  if (!value.IsHeapObject()) return;
  MemoryChunk* host_chunk = MemoryChunk::FromHeapObject(host);
  Tagged<HeapObject> heap_object_value = Cast<HeapObject>(value);
  MemoryChunk* value_chunk = MemoryChunk::FromHeapObject(heap_object_value);
  const bool pointers_from_here_are_interesting =
      !host_chunk->IsYoungOrSharedChunk();
  const bool is_marking = host_chunk->IsMarking();
  if (pointers_from_here_are_interesting &&
      value_chunk->IsYoungOrSharedChunk()) {
    CombinedGenerationalAndSharedEphemeronBarrierSlow(host, slot.address(),
                                                      heap_object_value);
  }
  // Marking barrier: mark value & record slots when marking is on.
  if (is_marking) {
    MarkingSlow(host, HeapObjectSlot(slot), heap_object_value);
  }
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), CombinedGenerationalAndSharedEphemeronBarrierSlow(), DCHECK_EQ, v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::IsMarking(), v8::internal::MemoryChunk::IsYoungOrSharedChunk(), MarkingSlow(), mode(), v8::internal::SKIP_WRITE_BARRIER, SLOW_DCHECK, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
Referenced by EphemeronKeyWriteBarrierFromCode().
ForExternalPointer()
void v8::internal::WriteBarrier::ForExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline], [static]
Definition at line 171 of file heap-write-barrier-inl.h.
                                                             {
  if (mode == SKIP_WRITE_BARRIER) {
    SLOW_DCHECK(HeapLayout::InYoungGeneration(host));
    return;
  }
  Marking(host, slot);
}
References v8::internal::HeapLayout::InYoungGeneration(), Marking(), mode(), v8::internal::SKIP_WRITE_BARRIER, and SLOW_DCHECK.
ForIndirectPointer()
void v8::internal::WriteBarrier::ForIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, Tagged< HeapObject > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline], [static]
Definition at line 182 of file heap-write-barrier-inl.h.
                                                             {
  // Indirect pointers are only used when the sandbox is enabled.
  DCHECK(V8_ENABLE_SANDBOX_BOOL);
  if (mode == SKIP_WRITE_BARRIER) {
    SLOW_DCHECK(!WriteBarrier::IsRequired(host, value));
    return;
  }
  // Objects referenced via indirect pointers are currently never allocated in
  // the young generation.
  if (!v8_flags.sticky_mark_bits) {
    DCHECK(!MemoryChunk::FromHeapObject(value)->InYoungGeneration());
  }
  Marking(host, slot);
}
References v8::internal::DCHECK(), v8::internal::MemoryChunk::FromHeapObject(), Marking(), mode(), v8::internal::SKIP_WRITE_BARRIER, SLOW_DCHECK, V8_ENABLE_SANDBOX_BOOL, v8::internal::v8_flags, and v8::internal::value.
Referenced by v8::internal::SlotAccessorForHeapObject::WriteIndirectPointerTo().
ForJSDispatchHandle()
void v8::internal::WriteBarrier::ForJSDispatchHandle (Tagged< HeapObject > host, JSDispatchHandle handle, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline], [static]
Definition at line 201 of file heap-write-barrier-inl.h.
                                                              {
  DCHECK(V8_ENABLE_LEAPTIERING_BOOL);
  SLOW_DCHECK(
      WriteBarrier::VerifyDispatchHandleMarkingState(host, handle, mode));
  if (mode == SKIP_WRITE_BARRIER) {
    return;
  }
  Marking(host, handle);
}
References v8::internal::DCHECK(), v8::internal::handle(), Marking(), mode(), v8::internal::SKIP_WRITE_BARRIER, SLOW_DCHECK, and V8_ENABLE_LEAPTIERING_BOOL.
Referenced by v8::internal::WritableRelocInfo::set_js_dispatch_handle().
ForProtectedPointer()
void v8::internal::WriteBarrier::ForProtectedPointer (Tagged< TrustedObject > host, ProtectedPointerSlot slot, Tagged< TrustedObject > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline], [static]
Definition at line 214 of file heap-write-barrier-inl.h.
                                                              {
  if (mode == SKIP_WRITE_BARRIER) {
    SLOW_DCHECK(!WriteBarrier::IsRequired(host, value));
    return;
  }
  // Protected pointers are only used within trusted and shared trusted space.
  DCHECK_IMPLIES(!v8_flags.sticky_mark_bits,
                 !MemoryChunk::FromHeapObject(value)->InYoungGeneration());
  if (MemoryChunk::FromHeapObject(value)->InWritableSharedSpace()) {
    SharedSlow(host, slot, value);
  }
  Marking(host, slot, value);
}
References DCHECK_IMPLIES, v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::InYoungGeneration(), Marking(), mode(), SharedSlow(), v8::internal::SKIP_WRITE_BARRIER, SLOW_DCHECK, v8::internal::v8_flags, and v8::internal::value.
ForRange()
template<typename TSlot >
void v8::internal::WriteBarrier::ForRange (Heap * heap, Tagged< HeapObject > object, TSlot start, TSlot end) [static]
Definition at line 489 of file heap-write-barrier.cc.
                                                              {
  if (v8_flags.disable_write_barriers) {
    return;
  }
  MemoryChunk* source_chunk = MemoryChunk::FromHeapObject(object);
  base::Flags<RangeWriteBarrierMode> mode;
  if (!HeapLayout::InYoungGeneration(object) &&
      !source_chunk->InWritableSharedSpace()) {
    mode |= kDoGenerationalOrShared;
  }
  if (heap->incremental_marking()->IsMarking()) {
    mode |= kDoMarking;
    if (!source_chunk->ShouldSkipEvacuationSlotRecording()) {
      mode |= kDoEvacuationSlotRecording;
    }
  }
  switch (mode) {
    // Nothing to be done.
    case 0:
      return;
    // Generational only.
    case kDoGenerationalOrShared:
      return ForRangeImpl<kDoGenerationalOrShared>(heap, source_chunk, object,
                                                   start_slot, end_slot);
    // Marking, no evacuation slot recording.
    case kDoMarking:
      return ForRangeImpl<kDoMarking>(heap, source_chunk, object, start_slot,
                                      end_slot);
    // Marking with evacuation slot recording.
    case kDoMarking | kDoEvacuationSlotRecording:
      return ForRangeImpl<kDoMarking | kDoEvacuationSlotRecording>(
          heap, source_chunk, object, start_slot, end_slot);
    // Generational and marking, no evacuation slot recording.
    case kDoGenerationalOrShared | kDoMarking:
      return ForRangeImpl<kDoGenerationalOrShared | kDoMarking>(
          heap, source_chunk, object, start_slot, end_slot);
    // Generational and marking with evacuation slot recording.
    case kDoGenerationalOrShared | kDoMarking | kDoEvacuationSlotRecording:
      return ForRangeImpl<kDoGenerationalOrShared | kDoMarking |
                          kDoEvacuationSlotRecording>(
          heap, source_chunk, object, start_slot, end_slot);
    default:
      UNREACHABLE();
  }
}
References v8::internal::anonymous_namespace{heap-write-barrier.cc}::ForRangeImpl(), v8::internal::MemoryChunk::FromHeapObject(), heap(), v8::internal::MemoryChunk::InWritableSharedSpace(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::anonymous_namespace{heap-write-barrier.cc}::kDoEvacuationSlotRecording, v8::internal::anonymous_namespace{heap-write-barrier.cc}::kDoGenerationalOrShared, v8::internal::anonymous_namespace{heap-write-barrier.cc}::kDoMarking, mode(), v8::internal::MemoryChunk::ShouldSkipEvacuationSlotRecording(), v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::array_fill_wrapper(), v8::internal::Factory::CopyJSObjectWithAllocationSite(), v8::internal::anonymous_namespace{heap.cc}::CopyOrMoveRangeImpl(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::anonymous_namespace{elements.cc}::SortIndices().
ForRelocInfo()
void v8::internal::WriteBarrier::ForRelocInfo (Tagged< InstructionStream > host, RelocInfo * rinfo, Tagged< HeapObject > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline], [static]
Definition at line 85 of file heap-write-barrier-inl.h.
                                                       {
  if (mode == SKIP_WRITE_BARRIER) {
    SLOW_DCHECK(!WriteBarrier::IsRequired(host, value));
    return;
  }
  // Used during InstructionStream initialization where we update the write
  // barriers together separate from the field writes.
  if (mode == UNSAFE_SKIP_WRITE_BARRIER) {
    DCHECK(!DisallowGarbageCollection::IsAllowed());
    return;
  }
  DCHECK_EQ(mode, UPDATE_WRITE_BARRIER);
  GenerationalForRelocInfo(host, rinfo, value);
  SharedForRelocInfo(host, rinfo, value);
  MarkingForRelocInfo(host, rinfo, value);
}
References v8::internal::DCHECK(), DCHECK_EQ, GenerationalForRelocInfo(), MarkingForRelocInfo(), mode(), SharedForRelocInfo(), v8::internal::SKIP_WRITE_BARRIER, SLOW_DCHECK, v8::internal::UNSAFE_SKIP_WRITE_BARRIER, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
Referenced by v8::internal::InstructionStream::RelocateFromDescWriteBarriers(), v8::internal::WritableRelocInfo::set_target_address(), and v8::internal::WritableRelocInfo::set_target_object().
ForValue() [1/2]
template<typename T >
void v8::internal::WriteBarrier::ForValue (HeapObjectLayout * host, TaggedMemberBase * slot, Tagged< T > value, WriteBarrierMode mode) [inline], [static]
Definition at line 123 of file heap-write-barrier-inl.h.
                                                                    {
  if (mode == SKIP_WRITE_BARRIER) {
    SLOW_DCHECK(!WriteBarrier::IsRequired(host, value));
    return;
  }
  Tagged<HeapObject> value_object;
  if (!value.GetHeapObject(&value_object)) {
    return;
  }
  CombinedWriteBarrierInternal(Tagged(host), HeapObjectSlot(ObjectSlot(slot)),
                               value_object, mode);
}
References CombinedWriteBarrierInternal(), mode(), v8::internal::SKIP_WRITE_BARRIER, SLOW_DCHECK, v8::internal::Tagged(), and v8::internal::value.
ForValue() [2/2]
template<typename T >
void v8::internal::WriteBarrier::ForValue (Tagged< HeapObject > host, MaybeObjectSlot slot, Tagged< T > value, WriteBarrierMode mode) [inline], [static]
Definition at line 108 of file heap-write-barrier-inl.h.
                                                                    {
  if (mode == SKIP_WRITE_BARRIER) {
    SLOW_DCHECK(!WriteBarrier::IsRequired(host, value));
    return;
  }
  Tagged<HeapObject> value_object;
  if (!value.GetHeapObject(&value_object)) {
    return;
  }
  CombinedWriteBarrierInternal(host, HeapObjectSlot(slot), value_object, mode);
}
References CombinedWriteBarrierInternal(), mode(), v8::internal::SKIP_WRITE_BARRIER, SLOW_DCHECK, and v8::internal::value.
Referenced by v8::internal::HeapObject::set_map(), v8::internal::HeapObject::set_map_after_allocation(), v8::internal::SlotAccessorForHeapObject::Write(), and v8::internal::TaggedMember< T, CompressionScheme >::WriteBarrier().
GenerationalBarrierForCodeSlow()
void v8::internal::WriteBarrier::GenerationalBarrierForCodeSlow (Tagged< InstructionStream > host, RelocInfo * rinfo, Tagged< HeapObject > value) [static], [private]
Definition at line 327 of file heap-write-barrier.cc.
                              {
  DCHECK(HeapLayout::InYoungGeneration(value));
  const MarkCompactCollector::RecordRelocSlotInfo info =
      MarkCompactCollector::ProcessRelocInfo(host, rinfo, value);
  base::MutexGuard write_scope(info.page_metadata->mutex());
  RememberedSet<OLD_TO_NEW>::InsertTyped(info.page_metadata, info.slot_type,
                                         info.offset);
}
References v8::internal::DCHECK(), v8::internal::RememberedSet< type >::InsertTyped(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::MutablePageMetadata::mutex(), v8::internal::MarkCompactCollector::RecordRelocSlotInfo::offset, v8::internal::MarkCompactCollector::RecordRelocSlotInfo::page_metadata, v8::internal::MarkCompactCollector::ProcessRelocInfo(), v8::internal::MarkCompactCollector::RecordRelocSlotInfo::slot_type, and v8::internal::value.
Referenced by GenerationalForRelocInfo().
GenerationalBarrierForCppHeapPointer()
void v8::internal::WriteBarrier::GenerationalBarrierForCppHeapPointer (Tagged< CppHeapPointerWrapperObjectT > host, void * value) [inline], [static], [private]
Definition at line 379 of file heap-write-barrier-inl.h.
                                                            {
  if (!value) {
    return;
  }
  auto* memory_chunk = MemoryChunk::FromHeapObject(host);
  if (V8_LIKELY(HeapLayout::InYoungGeneration(memory_chunk, host))) {
    return;
  }
  auto* cpp_heap = memory_chunk->GetHeap()->cpp_heap();
  v8::internal::CppHeap::From(cpp_heap)->RememberCrossHeapReferenceIfNeeded(
      host, value);
}
References v8::internal::CppHeap::From(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::CppHeap::RememberCrossHeapReferenceIfNeeded(), V8_LIKELY, and v8::internal::value.
Referenced by ForCppHeapPointer().
GenerationalBarrierSlow()
void v8::internal::WriteBarrier::GenerationalBarrierSlow (Tagged< HeapObject > object, Address slot, Tagged< HeapObject > value) [static], [private]
Definition at line 371 of file heap-write-barrier.cc.
                                                                     {
  MemoryChunk* chunk = MemoryChunk::FromHeapObject(object);
  MutablePageMetadata* metadata = MutablePageMetadata::cast(chunk->Metadata());
  if (LocalHeap::Current() == nullptr) {
    RememberedSet<OLD_TO_NEW>::Insert<AccessMode::NON_ATOMIC>(
        metadata, chunk->Offset(slot));
  } else {
    RememberedSet<OLD_TO_NEW_BACKGROUND>::Insert<AccessMode::ATOMIC>(
        metadata, chunk->Offset(slot));
  }
}
References v8::internal::MutablePageMetadata::cast(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::Metadata(), and v8::internal::MemoryChunk::Offset().
Referenced by CombinedGenerationalAndSharedBarrierSlow().
GenerationalForRelocInfo()
void v8::internal::WriteBarrier::GenerationalForRelocInfo (Tagged< InstructionStream > host, RelocInfo * rinfo, Tagged< HeapObject > object) [inline], [static]
Definition at line 232 of file heap-write-barrier-inl.h.
                                                                       {
  if (!HeapLayout::InYoungGeneration(object)) {
    return;
  }
  GenerationalBarrierForCodeSlow(host, rinfo, object);
}
References GenerationalBarrierForCodeSlow(), and v8::internal::HeapLayout::InYoungGeneration().
Referenced by ForRelocInfo(), and v8::internal::RecordMigratedSlotVisitor::VisitEmbeddedPointer().
GetWriteBarrierModeForObject()
WriteBarrierMode v8::internal::WriteBarrier::GetWriteBarrierModeForObject (Tagged< HeapObject > object, const DisallowGarbageCollection & promise) [inline], [static]
Definition at line 62 of file heap-write-barrier-inl.h.
                                                                         {
  if (v8_flags.disable_write_barriers) {
    return SKIP_WRITE_BARRIER;
  }
  DCHECK(PageFlagsAreConsistent(object));
  MemoryChunk* chunk = MemoryChunk::FromHeapObject(object);
  if (chunk->IsMarking()) {
    return UPDATE_WRITE_BARRIER;
  }
  if (HeapLayout::InYoungGeneration(chunk, object)) {
    return SKIP_WRITE_BARRIER;
  }
  return UPDATE_WRITE_BARRIER;
}
References v8::internal::DCHECK(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::MemoryChunk::IsMarking(), PageFlagsAreConsistent(), v8::internal::SKIP_WRITE_BARRIER, v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::v8_flags.
Referenced by v8::internal::HeapObjectLayout::GetWriteBarrierMode(), and v8::internal::HeapObject::GetWriteBarrierMode().
IndirectPointerMarkingFromCode()
int v8::internal::WriteBarrier::IndirectPointerMarkingFromCode (Address raw_host, Address raw_slot, Address raw_tag) [static]
Definition at line 229 of file heap-write-barrier.cc.
                                                                  {
  Tagged<HeapObject> host = Cast<HeapObject>(Tagged<Object>(raw_host));
  IndirectPointerTag tag = static_cast<IndirectPointerTag>(raw_tag);
  DCHECK(IsValidIndirectPointerTag(tag));
  IndirectPointerSlot slot(raw_slot, tag);
#if DEBUG
  DCHECK(!HeapLayout::InWritableSharedSpace(host));
  MarkingBarrier* barrier = CurrentMarkingBarrier(host);
  DCHECK(barrier->heap()->isolate()->isolate_data()->is_marking());
  DCHECK(IsExposedTrustedObject(slot.load(barrier->heap()->isolate())));
#endif
  Marking(host, slot);
  // Called by WriteBarrierCodeStubAssembler, which doesn't accept void type
  return 0;
}
References CurrentMarkingBarrier(), v8::internal::DCHECK(), v8::internal::MarkingBarrier::heap(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::IsolateData::is_marking(), v8::internal::Heap::isolate(), v8::internal::Isolate::isolate_data(), v8::internal::IsValidIndirectPointerTag(), v8::internal::IndirectPointerSlot::load(), and Marking().
IsImmortalImmovableHeapObject()
bool v8::internal::WriteBarrier::IsImmortalImmovableHeapObject (Tagged< HeapObject > object) [inline], [static], [private]
Definition at line 79 of file heap-write-barrier-inl.h.
                                                                          {
  // All objects in readonly space are immortal and immovable.
  return HeapLayout::InReadOnlySpace(object);
}
References v8::internal::HeapLayout::InReadOnlySpace().
IsMarking()
bool v8::internal::WriteBarrier::IsMarking (Tagged< HeapObject > object) [inline], [static], [private]
Definition at line 242 of file heap-write-barrier-inl.h.
                                                      {
  return MemoryChunk::FromHeapObject(object)->IsMarking();
}
References v8::internal::MemoryChunk::FromHeapObject(), and v8::internal::MemoryChunk::IsMarking().
Referenced by ForArrayBufferExtension(), ForCppHeapPointer(), ForDescriptorArray(), Marking(), and MarkingForRelocInfo().
Marking() [1/6]
void v8::internal::WriteBarrier::Marking (Tagged< HeapObject > host, ExternalPointerSlot slot) [inline], [static], [private]
Definition at line 313 of file heap-write-barrier-inl.h.
                                                                            {
  if (V8_LIKELY(!IsMarking(host))) {
    return;
  }
  MarkingSlow(host, slot);
}
References IsMarking(), MarkingSlow(), and V8_LIKELY.
Marking() [2/6]
void v8::internal::WriteBarrier::Marking (Tagged< HeapObject > host, HeapObjectSlot slot, Tagged< HeapObject > value) [inline], [static], [private]
Definition at line 270 of file heap-write-barrier-inl.h.
                                                     {
  if (V8_LIKELY(!IsMarking(host))) {
    return;
  }
  MarkingSlow(host, slot, value);
}
References IsMarking(), MarkingSlow(), V8_LIKELY, and v8::internal::value.
Referenced by ForExternalPointer(), ForIndirectPointer(), ForJSDispatchHandle(), ForProtectedPointer(), IndirectPointerMarkingFromCode(), Marking(), MarkingForTesting(), MarkingFromCode(), and SharedMarkingFromCode().
Marking() [3/6]
void v8::internal::WriteBarrier::Marking (Tagged< HeapObject > host, IndirectPointerSlot slot) [inline], [static], [private]
Definition at line 320 of file heap-write-barrier-inl.h.
                                                                            {
  if (V8_LIKELY(!IsMarking(host))) {
    return;
  }
  MarkingSlow(host, slot);
}
References IsMarking(), MarkingSlow(), and V8_LIKELY.
Marking() [4/6]
void v8::internal::WriteBarrier::Marking (Tagged< HeapObject > host, JSDispatchHandle handle) [inline], [static], [private]
Definition at line 336 of file heap-write-barrier-inl.h.
                                                                           {
  if (V8_LIKELY(!IsMarking(host))) {
    return;
  }
  MarkingSlow(host, handle);
}
References v8::internal::handle(), IsMarking(), MarkingSlow(), and V8_LIKELY.
Marking() [5/6]
void v8::internal::WriteBarrier::Marking (Tagged< HeapObject > host, MaybeObjectSlot slot, Tagged< MaybeObject > value) [inline], [static], [private]
Definition at line 256 of file heap-write-barrier-inl.h.
                                                      {
  Tagged<HeapObject> value_heap_object;
  if (!value.GetHeapObject(&value_heap_object)) {
    return;
  }
  // This barrier is called from generated code and from C++ code.
  // There must be no stores of InstructionStream values from generated code and
  // all stores of InstructionStream values in C++ must be handled by
  // CombinedWriteBarrierInternal().
  DCHECK(!HeapLayout::InCodeSpace(value_heap_object));
  Marking(host, HeapObjectSlot(slot), value_heap_object);
}
References v8::internal::DCHECK(), v8::internal::HeapLayout::InCodeSpace(), Marking(), and v8::internal::value.
Marking() [6/6]
void v8::internal::WriteBarrier::Marking (Tagged< TrustedObject > host, ProtectedPointerSlot slot, Tagged< TrustedObject > value) [inline], [static], [private]
Definition at line 327 of file heap-write-barrier-inl.h.
                                                        {
  if (V8_LIKELY(!IsMarking(host))) {
    return;
  }
  MarkingSlow(host, slot, value);
}
References IsMarking(), MarkingSlow(), V8_LIKELY, and v8::internal::value.
MarkingForRelocInfo()
void v8::internal::WriteBarrier::MarkingForRelocInfo (Tagged< InstructionStream > host, RelocInfo * reloc_info, Tagged< HeapObject > value) [inline], [static], [private]
Definition at line 278 of file heap-write-barrier-inl.h.
                                                                 {
  if (V8_LIKELY(!IsMarking(host))) {
    return;
  }
  MarkingSlow(host, reloc_info, value);
}
References IsMarking(), MarkingSlow(), V8_LIKELY, and v8::internal::value.
Referenced by ForRelocInfo().
MarkingForTesting()
void v8::internal::WriteBarrier::MarkingForTesting (Tagged< HeapObject > host, ObjectSlot slot, Tagged< Object > value) [inline], [static]
Definition at line 246 of file heap-write-barrier-inl.h.
                                                           {
  DCHECK(!HasWeakHeapObjectTag(value));
  if (!value.IsHeapObject()) {
    return;
  }
  Tagged<HeapObject> value_heap_object = Cast<HeapObject>(value);
  Marking(host, HeapObjectSlot(slot), value_heap_object);
}
References v8::internal::DCHECK(), v8::internal::HasWeakHeapObjectTag(), Marking(), and v8::internal::value.
MarkingFromCode()
int v8::internal::WriteBarrier::MarkingFromCode (Address raw_host, Address raw_slot) [static]
Definition at line 197 of file heap-write-barrier.cc.
                                                                    {
  Tagged<HeapObject> host = Cast<HeapObject>(Tagged<Object>(raw_host));
  MaybeObjectSlot slot(raw_slot);
  Address value = (*slot).ptr();
#ifdef V8_MAP_PACKING
  if (slot.address() == host.address()) {
    // Clear metadata bits and fix object tag.
    value = (value & ~Internals::kMapWordMetadataMask &
             ~Internals::kMapWordXorMask) |
            (uint64_t)kHeapObjectTag;
  }
#endif
#if DEBUG
  Heap* heap = MutablePageMetadata::FromHeapObject(host)->heap();
  DCHECK(heap->incremental_marking()->IsMarking());
  // We will only reach local objects here while incremental marking in the
  // current isolate is enabled. However, we might still reach objects in the
  // shared space but only from the shared space isolate (= the main isolate).
  MarkingBarrier* barrier = CurrentMarkingBarrier(host);
  DCHECK_IMPLIES(HeapLayout::InWritableSharedSpace(host),
                 barrier->heap()->isolate()->is_shared_space_isolate());
  barrier->AssertMarkingIsActivated();
#endif // DEBUG
  Marking(host, slot, Tagged<MaybeObject>(value));
  // Called by WriteBarrierCodeStubAssembler, which doesn't accept void type
  return 0;
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), v8::internal::Tagged< HeapObject >::address(), CurrentMarkingBarrier(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::MarkingBarrier::heap(), v8::internal::MemoryChunkMetadata::heap(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::Isolate::is_shared_space_isolate(), v8::internal::Heap::isolate(), v8::internal::kHeapObjectTag, Marking(), and v8::internal::value.
MarkingFromTracedHandle()
void v8::internal::WriteBarrier::MarkingFromTracedHandle (Tagged< Object > value) [inline], [static]
Definition at line 344 of file heap-write-barrier-inl.h.
                                                               {
  if (!value.IsHeapObject()) {
    return;
  }
  MarkingSlowFromTracedHandle(Cast<HeapObject>(value));
}
References MarkingSlowFromTracedHandle(), and v8::internal::value.
Referenced by v8::internal::TracedHandles::Create(), and v8::internal::TracedHandles::Move().
MarkingSlow() [1/8]
void v8::internal::WriteBarrier::MarkingSlow (Tagged< DescriptorArray > descriptor_array, int number_of_own_descriptors) [static], [private]
Definition at line 133 of file heap-write-barrier.cc.
                                                              {
  MarkingBarrier* marking_barrier = CurrentMarkingBarrier(descriptor_array);
  marking_barrier->Write(descriptor_array, number_of_own_descriptors);
}
References CurrentMarkingBarrier(), and v8::internal::MarkingBarrier::Write().
MarkingSlow() [2/8]
void v8::internal::WriteBarrier::MarkingSlow (Tagged< HeapObject > host, ExternalPointerSlot slot) [static], [private]
Definition at line 139 of file heap-write-barrier.cc.
                                                         {
#ifdef V8_COMPRESS_POINTERS
  if (!slot.HasExternalPointerHandle()) return;
  MarkingBarrier* marking_barrier = CurrentMarkingBarrier(host);
  IsolateForPointerCompression isolate(marking_barrier->heap()->isolate());
  ExternalPointerTable& table =
      isolate.GetExternalPointerTableFor(slot.tag_range());
  ExternalPointerTable::Space* space =
      isolate.GetExternalPointerTableSpaceFor(slot.tag_range(), host.address());
  ExternalPointerHandle handle = slot.Relaxed_LoadHandle();
  table.Mark(space, handle, slot.address());
#endif // V8_COMPRESS_POINTERS
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), v8::internal::Tagged< HeapObject >::address(), CurrentMarkingBarrier(), v8::internal::handle(), v8::internal::MarkingBarrier::heap(), v8::internal::Heap::isolate(), space, and v8::internal::ExternalPointerSlot::tag_range().
MarkingSlow() [3/8]
void v8::internal::WriteBarrier::MarkingSlow (Tagged< HeapObject > host, HeapObjectSlot slot, Tagged< HeapObject > value) [static], [private]
Definition at line 49 of file heap-write-barrier.cc.
                                                         {
  SLOW_DCHECK_IMPLIES(kUninterestingPagesCanBeSkipped,
                      MemoryChunk::FromHeapObject(host)->GetFlags() &
                          MemoryChunk::kPointersFromHereAreInterestingMask);
  MarkingBarrier* marking_barrier = CurrentMarkingBarrier(host);
  marking_barrier->Write(host, slot, value);
}
References CurrentMarkingBarrier(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::kPointersFromHereAreInterestingMask, kUninterestingPagesCanBeSkipped, SLOW_DCHECK_IMPLIES, v8::internal::value, and v8::internal::MarkingBarrier::Write().
Referenced by CombinedWriteBarrierInternal(), ForArrayBufferExtension(), ForDescriptorArray(), ForEphemeronHashTable(), Marking(), and MarkingForRelocInfo().
MarkingSlow() [4/8]
void v8::internal::WriteBarrier::MarkingSlow (Tagged< HeapObject > host, IndirectPointerSlot slot) [static], [private]
Definition at line 157 of file heap-write-barrier.cc.
                                                         {
  MarkingBarrier* marking_barrier = CurrentMarkingBarrier(host);
  marking_barrier->Write(host, slot);
}
References CurrentMarkingBarrier(), and v8::internal::MarkingBarrier::Write().
MarkingSlow() [5/8]
void v8::internal::WriteBarrier::MarkingSlow (Tagged< HeapObject > host, JSDispatchHandle handle) [static], [private]
Definition at line 170 of file heap-write-barrier.cc.
                                                        {
#ifdef V8_ENABLE_LEAPTIERING
  MarkingBarrier* marking_barrier = CurrentMarkingBarrier(host);
  // The JSDispatchTable is only marked during major GC so we can skip the
  // barrier if we're only doing a minor GC.
  // This is mostly an optimization, but it does help avoid scenarios where a
  // minor GC marking barrier marks a table entry as alive but not the Code
  // object contained in it (because it's not a young-gen object).
  if (marking_barrier->is_minor()) return;
  // Mark both the table entry and its content.
  JSDispatchTable* jdt = IsolateGroup::current()->js_dispatch_table();
  static_assert(JSDispatchTable::kWriteBarrierSetsEntryMarkBit);
  jdt->Mark(handle);
  marking_barrier->MarkValue(host, jdt->GetCode(handle));
  // We don't need to record a slot here because the entries in the
  // JSDispatchTable are not compacted and because the pointers stored in the
  // table entries are updated after compacting GC.
  static_assert(!JSDispatchTable::kSupportsCompaction);
#else
  UNREACHABLE();
#endif
}
References v8::internal::IsolateGroup::current(), CurrentMarkingBarrier(), v8::internal::handle(), v8::internal::MarkingBarrier::is_minor(), v8::internal::MarkingBarrier::MarkValue(), and v8::internal::UNREACHABLE().
MarkingSlow() [6/8]
void v8::internal::WriteBarrier::MarkingSlow (Tagged< InstructionStream > host, RelocInfo * reloc_info, Tagged< HeapObject > value) [static], [private]
Definition at line 87 of file heap-write-barrier.cc.
                                                         {
  MarkingBarrier* marking_barrier = CurrentMarkingBarrier(host);
  marking_barrier->Write(host, reloc_info, value);
}
References CurrentMarkingBarrier(), v8::internal::value, and v8::internal::MarkingBarrier::Write().
MarkingSlow() [7/8]
void v8::internal::WriteBarrier::MarkingSlow (Tagged< JSArrayBuffer > host, ArrayBufferExtension * extension) [static], [private]
Definition at line 127 of file heap-write-barrier.cc.
                                                                {
  MarkingBarrier* marking_barrier = CurrentMarkingBarrier(host);
  marking_barrier->Write(host, extension);
}
References CurrentMarkingBarrier(), and v8::internal::MarkingBarrier::Write().
MarkingSlow() [8/8]
void v8::internal::WriteBarrier::MarkingSlow (Tagged< TrustedObject > host, ProtectedPointerSlot slot, Tagged< TrustedObject > value) [static], [private]
Definition at line 163 of file heap-write-barrier.cc.
                                                            {
  MarkingBarrier* marking_barrier = CurrentMarkingBarrier(host);
  marking_barrier->Write(host, slot, value);
}
References CurrentMarkingBarrier(), v8::internal::value, and v8::internal::MarkingBarrier::Write().
MarkingSlowFromCppHeapWrappable()
void v8::internal::WriteBarrier::MarkingSlowFromCppHeapWrappable (Heap * heap, Tagged< CppHeapPointerWrapperObjectT > host, CppHeapPointerSlot slot, void * object) [static], [private]
Definition at line 65 of file heap-write-barrier.cc.
                                           {
  // Note: this is currently a combined barrier for marking both the
  // CppHeapPointerTable entry and the referenced object (if any).
#ifdef V8_COMPRESS_POINTERS
  MarkingBarrier* marking_barrier = CurrentMarkingBarrier(host);
  IsolateForPointerCompression isolate(marking_barrier->heap()->isolate());
  CppHeapPointerTable& table = isolate.GetCppHeapPointerTable();
  CppHeapPointerTable::Space* space = isolate.GetCppHeapPointerTableSpace();
  ExternalPointerHandle handle = slot.Relaxed_LoadHandle();
  table.Mark(space, handle, slot.address());
#endif // V8_COMPRESS_POINTERS
  if (heap->cpp_heap() && object) {
    CppHeap::From(heap->cpp_heap())->WriteBarrier(object);
  }
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), CurrentMarkingBarrier(), v8::internal::CppHeap::From(), v8::internal::handle(), v8::internal::MarkingBarrier::heap(), v8::internal::Heap::isolate(), space, and v8::internal::CppHeap::WriteBarrier().
Referenced by ForCppHeapPointer().
MarkingSlowFromTracedHandle()
void v8::internal::WriteBarrier::MarkingSlowFromTracedHandle (Tagged< HeapObject > value) [static], [private]
Definition at line 59 of file heap-write-barrier.cc.
                                                                       {
  MarkingBarrier* marking_barrier = CurrentMarkingBarrier(value);
  marking_barrier->WriteWithoutHost(value);
}
References CurrentMarkingBarrier(), v8::internal::value, and v8::internal::MarkingBarrier::WriteWithoutHost().
Referenced by MarkingFromTracedHandle().
PageFlagsAreConsistent()
bool v8::internal::WriteBarrier::PageFlagsAreConsistent (Tagged< HeapObject > object) [static], [private]
Definition at line 289 of file heap-write-barrier.cc.
                                                                   {
  MemoryChunkMetadata* metadata = MemoryChunkMetadata::FromHeapObject(object);
  MemoryChunk* chunk = MemoryChunk::FromHeapObject(object);
  // Slim chunk flags consistency.
  CHECK_EQ(chunk->IsFlagSet(MemoryChunk::INCREMENTAL_MARKING),
           chunk->IsMarking());
  if (!v8_flags.sticky_mark_bits) {
    AllocationSpace identity = metadata->owner()->identity();
    // Generation consistency.
    CHECK_EQ(identity == NEW_SPACE || identity == NEW_LO_SPACE,
             chunk->InYoungGeneration());
  }
  // Marking consistency.
  if (metadata->IsWritable()) {
    // RO_SPACE can be shared between heaps, so we can't use RO_SPACE objects to
    // find a heap. The exception is when the ReadOnlySpace is writeable, during
    // bootstrapping, so explicitly allow this case.
    Heap* heap = Heap::FromWritableHeapObject(object);
    if (chunk->InWritableSharedSpace()) {
      // The marking bit is not set for chunks in shared spaces during MinorMS
      // concurrent marking.
      CHECK_EQ(chunk->IsMarking(),
               heap->incremental_marking()->IsMajorMarking());
    } else {
      CHECK_EQ(chunk->IsMarking(), heap->incremental_marking()->IsMarking());
    }
  } else {
    // Non-writable RO_SPACE must never have marking flag set.
    CHECK(!chunk->IsMarking());
  }
  return true;
}
References CHECK, CHECK_EQ, v8::internal::MemoryChunkMetadata::FromHeapObject(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::Heap::FromWritableHeapObject(), v8::internal::BaseSpace::identity(), v8::internal::MemoryChunk::INCREMENTAL_MARKING, v8::internal::MemoryChunk::InWritableSharedSpace(), v8::internal::MemoryChunk::InYoungGeneration(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::IsMarking(), v8::internal::MemoryChunkMetadata::IsWritable(), v8::internal::NEW_LO_SPACE, v8::internal::NEW_SPACE, v8::internal::MemoryChunkMetadata::owner(), and v8::internal::v8_flags.
Referenced by GetWriteBarrierModeForObject().
SetForThread()
MarkingBarrier * v8::internal::WriteBarrier::SetForThread (MarkingBarrier * marking_barrier) [static]
Definition at line 43 of file heap-write-barrier.cc.
                                                                          {
  MarkingBarrier* existing = current_marking_barrier;
  current_marking_barrier = marking_barrier;
  return existing;
}
References v8::internal::anonymous_namespace{heap-write-barrier.cc}::current_marking_barrier.
Referenced by v8::internal::LocalHeap::LocalHeap(), v8::internal::Isolate::SetIsolateThreadLocals(), and v8::internal::LocalHeap::~LocalHeap().
SharedForRelocInfo()
void v8::internal::WriteBarrier::SharedForRelocInfo (Tagged< InstructionStream > host, RelocInfo * reloc_info, Tagged< HeapObject > value) [inline], [static]
Definition at line 287 of file heap-write-barrier-inl.h.
                                                                {
  MemoryChunk* value_chunk = MemoryChunk::FromHeapObject(value);
  if (!value_chunk->InWritableSharedSpace()) {
    return;
  }
  SharedSlow(host, reloc_info, value);
}
References v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::InWritableSharedSpace(), SharedSlow(), and v8::internal::value.
Referenced by ForRelocInfo(), and v8::internal::RecordMigratedSlotVisitor::VisitEmbeddedPointer().
SharedFromCode()
int v8::internal::WriteBarrier::SharedFromCode (Address raw_host, Address raw_slot) [static]
Definition at line 277 of file heap-write-barrier.cc.
                                                                   {
  Tagged<HeapObject> host = Cast<HeapObject>(Tagged<Object>(raw_host));
  if (!HeapLayout::InWritableSharedSpace(host)) {
    SharedHeapBarrierSlow(host, raw_slot);
  }
  // Called by WriteBarrierCodeStubAssembler, which doesn't accept void type
  return 0;
}
References v8::internal::HeapLayout::InWritableSharedSpace(), and SharedHeapBarrierSlow().
SharedHeapBarrierSlow()
void v8::internal::WriteBarrier::SharedHeapBarrierSlow (Tagged< HeapObject > object, Address slot) [static], [private]
Definition at line 106 of file heap-write-barrier.cc.
                                                       {
  MemoryChunk* chunk = MemoryChunk::FromHeapObject(object);
  DCHECK(!chunk->InWritableSharedSpace());
  RememberedSet<OLD_TO_SHARED>::Insert<AccessMode::ATOMIC>(
      MutablePageMetadata::cast(chunk->Metadata()), chunk->Offset(slot));
}
References v8::internal::MutablePageMetadata::cast(), v8::internal::DCHECK(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::InWritableSharedSpace(), v8::internal::MemoryChunk::Metadata(), and v8::internal::MemoryChunk::Offset().
Referenced by CombinedGenerationalAndSharedBarrierSlow(), CombinedGenerationalAndSharedEphemeronBarrierSlow(), and SharedFromCode().
SharedMarkingFromCode()
int v8::internal::WriteBarrier::SharedMarkingFromCode (Address raw_host, Address raw_slot) [static]
Definition at line 250 of file heap-write-barrier.cc.
                                                                          {
  Tagged<HeapObject> host = Cast<HeapObject>(Tagged<Object>(raw_host));
  MaybeObjectSlot slot(raw_slot);
  Address raw_value = (*slot).ptr();
  Tagged<MaybeObject> value(raw_value);
  DCHECK(HeapLayout::InWritableSharedSpace(host));
#if DEBUG
  Heap* heap = MutablePageMetadata::FromHeapObject(host)->heap();
  DCHECK(heap->incremental_marking()->IsMajorMarking());
  Isolate* isolate = heap->isolate();
  DCHECK(isolate->is_shared_space_isolate());
  // The shared marking barrier will only be reached from client isolates (=
  // worker isolates).
  MarkingBarrier* barrier = CurrentMarkingBarrier(host);
  DCHECK(!barrier->heap()->isolate()->is_shared_space_isolate());
  barrier->AssertSharedMarkingIsActivated();
#endif // DEBUG
  Marking(host, slot, Tagged<MaybeObject>(value));
  // Called by WriteBarrierCodeStubAssembler, which doesn't accept void type
  return 0;
}
References CurrentMarkingBarrier(), v8::internal::DCHECK(), v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::MarkingBarrier::heap(), v8::internal::MemoryChunkMetadata::heap(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::Isolate::is_shared_space_isolate(), v8::internal::Heap::isolate(), Marking(), and v8::internal::value.
SharedSlow() [1/2]
void v8::internal::WriteBarrier::SharedSlow (Tagged< InstructionStream > host, RelocInfo * reloc_info, Tagged< HeapObject > value) [static], [private]
Definition at line 95 of file heap-write-barrier.cc.
                                                                               {
  MarkCompactCollector::RecordRelocSlotInfo info =
      MarkCompactCollector::ProcessRelocInfo(host, reloc_info, value);
  base::MutexGuard write_scope(info.page_metadata->mutex());
  RememberedSet<OLD_TO_SHARED>::InsertTyped(info.page_metadata, info.slot_type,
                                            info.offset);
}
References v8::internal::RememberedSet< type >::InsertTyped(), v8::internal::MutablePageMetadata::mutex(), v8::internal::MarkCompactCollector::RecordRelocSlotInfo::offset, v8::internal::MarkCompactCollector::RecordRelocSlotInfo::page_metadata, v8::internal::MarkCompactCollector::ProcessRelocInfo(), v8::internal::MarkCompactCollector::RecordRelocSlotInfo::slot_type, and v8::internal::value.
SharedSlow() [2/2]
void v8::internal::WriteBarrier::SharedSlow (Tagged< TrustedObject > host, ProtectedPointerSlot slot, Tagged< TrustedObject > value) [static], [private]
Definition at line 115 of file heap-write-barrier.cc.
                                                           {
  DCHECK(MemoryChunk::FromHeapObject(value)->InWritableSharedSpace());
  if (!MemoryChunk::FromHeapObject(host)->InWritableSharedSpace()) {
    MutablePageMetadata* host_chunk_metadata =
        MutablePageMetadata::FromHeapObject(host);
    RememberedSet<TRUSTED_TO_SHARED_TRUSTED>::Insert<AccessMode::NON_ATOMIC>(
        host_chunk_metadata, host_chunk_metadata->Offset(slot.address()));
  }
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), v8::internal::DCHECK(), v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunkMetadata::Offset(), and v8::internal::value.
Referenced by ForProtectedPointer(), and SharedForRelocInfo().
Member Data Documentation
kUninterestingPagesCanBeSkipped
constexpr bool v8::internal::WriteBarrier::kUninterestingPagesCanBeSkipped = true [static], [constexpr]
Definition at line 122 of file heap-write-barrier.h.
Referenced by v8::internal::maglev::MaglevAssembler::CheckAndEmitDeferredWriteBarrier(), CombinedGenerationalAndSharedEphemeronBarrierSlow(), MarkingSlow(), and v8::internal::CodeStubAssembler::TrySkipWriteBarrier().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap-write-barrier.h
/mnt/V8SourceCode/src/heap/heap-write-barrier-inl.h
/mnt/V8SourceCode/src/heap/heap-write-barrier.cc