v8::internal::StackFrameIteratorBase Class Reference
#include <frames.h>
Public Member Functions
StackFrameIteratorBase (const StackFrameIteratorBase &)=delete
StackFrameIteratorBase & operator= (const StackFrameIteratorBase &)=delete
Isolate * isolate () const
bool done () const
virtual StackFrame::Type ComputeStackFrameType (StackFrame::State *state) const =0
Protected Member Functions
StackFrameIteratorBase (Isolate *isolate)
StackHandler * handler () const
void SetNewFrame (StackFrame::Type type, StackFrame::State *state)
void SetNewFrame (StackFrame::Type type)
Protected Attributes
Isolate *const isolate_
xx xx xx xx xx xx xx xx xx
union {
 char uninitialized_
};
StackFrame * frame_
StackHandler * handler_
Friends
class StackFrame
Detailed Description
Definition at line 1632 of file frames.h.
Constructor & Destructor Documentation
StackFrameIteratorBase() [1/2]
v8::internal::StackFrameIteratorBase::StackFrameIteratorBase (const StackFrameIteratorBase &) [delete]
StackFrameIteratorBase() [2/2]
v8::internal::StackFrameIteratorBase::StackFrameIteratorBase (Isolate * isolate) [explicit], [protected]
Definition at line 149 of file frames.cc.
    : isolate_(isolate), frame_(nullptr), handler_(nullptr) {}
Member Function Documentation
ComputeStackFrameType()
virtual StackFrame::Type v8::internal::StackFrameIteratorBase::ComputeStackFrameType (StackFrame::State * state) const [pure virtual]
Implemented in v8::internal::StackFrameIteratorForProfiler, and v8::internal::StackFrameIterator.
Referenced by v8::internal::StackFrame::GetCallerState().
done()
bool v8::internal::StackFrameIteratorBase::done () const [inline]
Definition at line 1642 of file frames.h.
{ return frame_ == nullptr; }
References frame_.
Referenced by _v8_internal_Expand_StackTrace(), v8::internal::ProfilerEventsProcessor::AddCurrentStack(), v8::internal::StackFrameIterator::Advance(), v8::internal::JavaScriptStackFrameIterator::Advance(), v8::internal::StackFrameIteratorForProfiler::Advance(), v8::internal::StackFrameIteratorForProfiler::AdvanceOneFrame(), v8::internal::Debug::AllFramesOnStackAreBlackboxed(), v8::internal::anonymous_namespace{runtime-object.cc}::CheckExcludedPropertiesAreOnCallerStack(), v8::internal::Deoptimizer::DeoptimizeMarkedCode(), v8::internal::JavaScriptStackFrameIterator::done(), v8::internal::StackFrameIterator::frame(), v8::internal::StackFrameIteratorForProfiler::frame(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetCallStack(), v8::internal::GetShouldThrow(), v8::internal::TickSample::GetStackSample(), handler(), v8::internal::wasm::StackMemory::Iterate(), v8::internal::Isolate::NotifyExceptionPropagationCallback(), v8::internal::Debug::OnException(), v8::internal::PrintFrames(), v8::internal::MarkCompactCollector::ProcessTopOptimizedFrame(), v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC(), v8::internal::RUNTIME_FUNCTION(), v8::internal::FinalizationRegistryCleanupTask::SlowAssertNoActiveJavaScript(), v8::internal::StackFrameIteratorForProfiler::StackFrameIteratorForProfiler(), v8::internal::StackTraceFailureMessage::StackTraceFailureMessage(), v8::internal::Isolate::UnwindAndFindHandler(), v8::internal::anonymous_namespace{isolate.cc}::VisitStack(), and v8::internal::anonymous_namespace{deoptimizer.cc}::ActivationsFinder::VisitThread().
handler()
StackHandler* v8::internal::StackFrameIteratorBase::handler () const [inline], [protected]
Definition at line 1673 of file frames.h.
                                {
    DCHECK(!done());
    return handler_;
  }
References v8::internal::DCHECK(), done(), and handler_.
Referenced by v8::internal::StackFrameIteratorForProfiler::IsValidTop(), and v8::internal::StackFrame::top_handler().
isolate()
Isolate* v8::internal::StackFrameIteratorBase::isolate () const [inline]
Definition at line 1637 of file frames.h.
{ return isolate_; }
References isolate_.
Referenced by v8::internal::StackFrameIterator::ComputeStackFrameType(), v8::internal::StackFrameIteratorForProfiler::ComputeStackFrameType(), v8::internal::StackFrameIteratorForProfiler::IsNoFrameBytecodeHandlerPc(), and v8::internal::StackFrameIteratorForProfiler::StackFrameIteratorForProfiler().
operator=()
StackFrameIteratorBase& v8::internal::StackFrameIteratorBase::operator= (const StackFrameIteratorBase &) [delete]
SetNewFrame() [1/2]
void v8::internal::StackFrameIteratorBase::SetNewFrame (StackFrame::Type type) [protected]
Definition at line 312 of file frames.cc.
                                                            {
  switch (type) {
#define FRAME_TYPE_CASE(type, class) \
  case StackFrame::type: \
    frame_ = new (&class##_) class(this); \
    return;
    STACK_FRAME_TYPE_LIST(FRAME_TYPE_CASE)
#undef FRAME_TYPE_CASE
    case StackFrame::NO_FRAME_TYPE:
    // We don't expect to see NUMBER_OF_TYPES or MANUAL, but stay robust against
    // them rather than being UNREACHABLE in case stack frame iteration gets
    // wonky.
    case StackFrame::NUMBER_OF_TYPES:
    case StackFrame::MANUAL:
      break;
  }
  frame_ = nullptr;
}
References frame_, FRAME_TYPE_CASE, v8::internal::StackFrame::MANUAL, v8::internal::StackFrame::NO_FRAME_TYPE, STACK_FRAME_TYPE_LIST, and v8::internal::tracing::type.
SetNewFrame() [2/2]
void v8::internal::StackFrameIteratorBase::SetNewFrame (StackFrame::Type type, StackFrame::State * state) [protected]
Definition at line 305 of file frames.cc.
                                                                 {
  SetNewFrame(type);
  DCHECK_EQ(!frame_, type == StackFrame::NO_FRAME_TYPE);
  if (frame_) frame_->state_ = *state;
}
References DCHECK_EQ, frame_, v8::internal::StackFrame::NO_FRAME_TYPE, v8::internal::StackFrame::state_, and v8::internal::tracing::type.
Referenced by v8::internal::StackFrameIterator::Advance(), v8::internal::StackFrameIteratorForProfiler::AdvanceOneFrame(), v8::internal::StackFrameIterator::Reframe(), v8::internal::StackFrameIterator::Reset(), and v8::internal::StackFrameIteratorForProfiler::StackFrameIteratorForProfiler().
Friends And Related Function Documentation
StackFrame
friend class StackFrame [friend]
Definition at line 1684 of file frames.h.
Member Data Documentation
union { ... } [protected]
frame_
StackFrame* v8::internal::StackFrameIteratorBase::frame_ [protected]
Definition at line 1664 of file frames.h.
Referenced by v8::internal::StackFrameIterator::Advance(), v8::internal::StackFrameIteratorForProfiler::Advance(), v8::internal::StackFrameIteratorForProfiler::AdvanceOneFrame(), done(), v8::internal::StackFrameIterator::frame(), v8::internal::StackFrameIteratorForProfiler::frame(), v8::internal::StackFrameIterator::Reframe(), and SetNewFrame().
handler_
StackHandler* v8::internal::StackFrameIteratorBase::handler_ [protected]
Definition at line 1665 of file frames.h.
Referenced by v8::internal::StackFrameIterator::Advance(), handler(), and v8::internal::StackFrameIterator::Reset().
isolate_
Isolate* const v8::internal::StackFrameIteratorBase::isolate_ [protected]
Definition at line 1657 of file frames.h.
Referenced by v8::internal::StackFrameIterator::ComputeStackFrameType(), v8::internal::StackFrameIteratorForProfiler::ComputeStackFrameType(), isolate(), and v8::internal::StackFrameIterator::Reset().
uninitialized_
char v8::internal::StackFrameIteratorBase::uninitialized_
Definition at line 1659 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames.cc