cppgc::internal::anonymous_namespace{sweeper.cc}::DiscardingFreeHandler Class Reference
Public Member Functions
DiscardingFreeHandler (PageAllocator &page_allocator, FreeList &free_list, BasePage &page)
void Free (FreeList::Block block)
void FreeFreeList (std::vector< FreeList::Block > &unfinalized_free_list) final
Private Attributes
PageAllocator & page_allocator_
FreeList & free_list_
BasePage & page_
Detailed Description
Definition at line 120 of file sweeper.cc.
Constructor & Destructor Documentation
DiscardingFreeHandler()
cppgc::internal::anonymous_namespace{sweeper.cc}::DiscardingFreeHandler::DiscardingFreeHandler (PageAllocator & page_allocator, FreeList & free_list, BasePage & page) [inline]
Definition at line 122 of file sweeper.cc.
      : page_allocator_(page_allocator), free_list_(free_list), page_(page) {}
Member Function Documentation
Free()
void cppgc::internal::anonymous_namespace{sweeper.cc}::DiscardingFreeHandler::Free (FreeList::Block block) [inline]
Definition at line 126 of file sweeper.cc.
                                 {
    const auto unused_range = free_list_.AddReturningUnusedBounds(block);
    const uintptr_t aligned_begin_unused =
        RoundUp(reinterpret_cast<uintptr_t>(unused_range.first),
                page_allocator_.CommitPageSize());
    const uintptr_t aligned_end_unused =
        RoundDown(reinterpret_cast<uintptr_t>(unused_range.second),
                  page_allocator_.CommitPageSize());
    if (aligned_begin_unused < aligned_end_unused) {
      const size_t discarded_size = aligned_end_unused - aligned_begin_unused;
      page_allocator_.DiscardSystemPages(
          reinterpret_cast<void*>(aligned_begin_unused),
          aligned_end_unused - aligned_begin_unused);
      page_.IncrementDiscardedMemory(discarded_size);
      page_.space()
          .raw_heap()
          ->heap()
          ->stats_collector()
          ->IncrementDiscardedMemory(discarded_size);
    }
  }
References RoundDown(), and RoundUp().
FreeFreeList()
void cppgc::internal::anonymous_namespace{sweeper.cc}::DiscardingFreeHandler::FreeFreeList (std::vector< FreeList::Block > & unfinalized_free_list) [inline], [final], [virtual]
Implements cppgc::internal::anonymous_namespace{sweeper.cc}::FreeHandlerBase.
Definition at line 148 of file sweeper.cc.
                                                                           {
    for (auto entry : unfinalized_free_list) {
      Free(std::move(entry));
    }
  }
References v8::base::Free().
Member Data Documentation
free_list_
FreeList& cppgc::internal::anonymous_namespace{sweeper.cc}::DiscardingFreeHandler::free_list_ [private]
Definition at line 156 of file sweeper.cc.
page_
BasePage& cppgc::internal::anonymous_namespace{sweeper.cc}::DiscardingFreeHandler::page_ [private]
Definition at line 157 of file sweeper.cc.
page_allocator_
PageAllocator& cppgc::internal::anonymous_namespace{sweeper.cc}::DiscardingFreeHandler::page_allocator_ [private]
Definition at line 155 of file sweeper.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/sweeper.cc