v8::internal::compiler::ParallelMove Class Reference
#include <instruction.h>
Public Member Functions
ParallelMove (Zone *zone)
ParallelMove (const ParallelMove &)=delete
ParallelMove & operator= (const ParallelMove &)=delete
MoveOperands * AddMove (const InstructionOperand &from, const InstructionOperand &to)
MoveOperands * AddMove (const InstructionOperand &from, const InstructionOperand &to, Zone *operand_allocation_zone)
bool IsRedundant () const
void PrepareInsertAfter (MoveOperands *move, ZoneVector< MoveOperands * > *to_eliminate) const
bool Equals (const ParallelMove &that) const
void Eliminate ()
Detailed Description
Definition at line 847 of file instruction.h.
Constructor & Destructor Documentation
ParallelMove() [1/2]
v8::internal::compiler::ParallelMove::ParallelMove (Zone * zone) [inline], [explicit]
Definition at line 851 of file instruction.h.
: ZoneVector<MoveOperands*>(zone) {}
ParallelMove() [2/2]
v8::internal::compiler::ParallelMove::ParallelMove (const ParallelMove &) [delete]
Member Function Documentation
AddMove() [1/2]
MoveOperands* v8::internal::compiler::ParallelMove::AddMove (const InstructionOperand & from, const InstructionOperand & to) [inline]
Definition at line 855 of file instruction.h.
                                                      {
    return AddMove(from, to, zone());
  }
Referenced by v8::internal::compiler::RegisterAllocationData::AddGapMove(), v8::internal::compiler::TopLevelLiveRange::CommitSpillMoves(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::MoveOptimizer::FinalizeMoves(), v8::internal::compiler::MoveOptimizer::MigrateMoves(), and v8::internal::compiler::MoveOptimizer::OptimizeMerge().
AddMove() [2/2]
MoveOperands* v8::internal::compiler::ParallelMove::AddMove (const InstructionOperand & from, const InstructionOperand & to, Zone * operand_allocation_zone) [inline]
Definition at line 860 of file instruction.h.
                                                       {
    if (from.EqualsCanonicalized(to)) return nullptr;
    MoveOperands* move = operand_allocation_zone->New<MoveOperands>(from, to);
    if (empty()) reserve(4);
    push_back(move);
    return move;
  }
References v8::internal::compiler::InstructionOperand::EqualsCanonicalized(), and v8::internal::Zone::New().
Eliminate()
void v8::internal::compiler::ParallelMove::Eliminate ()
Definition at line 368 of file instruction.cc.
                             {
  for (MoveOperands* move : *this) {
    move->Eliminate();
  }
}
References v8::internal::compiler::MoveOperands::Eliminate().
Referenced by v8::internal::compiler::JumpThreading::ApplyForwarding(), and v8::internal::compiler::TopLevelLiveRange::FilterSpillMoves().
Equals()
bool v8::internal::compiler::ParallelMove::Equals (const ParallelMove & that) const
Definition at line 360 of file instruction.cc.
                                                        {
  if (this->size() != that.size()) return false;
  for (size_t i = 0; i < this->size(); ++i) {
    if (!(*this)[i]->Equals(*that[i])) return false;
  }
  return true;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and size().
Referenced by v8::internal::compiler::anonymous_namespace{jump-threading.cc}::GapJumpRecord::CanForwardGapJump().
IsRedundant()
bool v8::internal::compiler::ParallelMove::IsRedundant () const
Definition at line 328 of file instruction.cc.
                                     {
  for (MoveOperands* move : *this) {
    if (!move->IsRedundant()) return false;
  }
  return true;
}
References v8::internal::compiler::MoveOperands::IsRedundant().
operator=()
ParallelMove& v8::internal::compiler::ParallelMove::operator= (const ParallelMove &) [delete]
PrepareInsertAfter()
void v8::internal::compiler::ParallelMove::PrepareInsertAfter (MoveOperands * move, ZoneVector< MoveOperands * > * to_eliminate) const
Definition at line 335 of file instruction.cc.
                                                                       {
  bool no_aliasing = kFPAliasing != AliasingKind::kCombine ||
                     !move->destination().IsFPLocationOperand();
  MoveOperands* replacement = nullptr;
  MoveOperands* eliminated = nullptr;
  for (MoveOperands* curr : *this) {
    if (curr->IsEliminated()) continue;
    if (curr->destination().EqualsCanonicalized(move->source())) {
      // We must replace move's source with curr's destination in order to
      // insert it into this ParallelMove.
      DCHECK(!replacement);
      replacement = curr;
      if (no_aliasing && eliminated != nullptr) break;
    } else if (curr->destination().InterferesWith(move->destination())) {
      // We can eliminate curr, since move overwrites at least a part of its
      // destination, implying its value is no longer live.
      eliminated = curr;
      to_eliminate->push_back(curr);
      if (no_aliasing && replacement != nullptr) break;
    }
  }
  if (replacement != nullptr) move->set_source(replacement->source());
}
References v8::internal::DCHECK(), v8::internal::compiler::MoveOperands::destination(), v8::internal::compiler::InstructionOperand::EqualsCanonicalized(), v8::internal::compiler::InstructionOperand::InterferesWith(), v8::internal::compiler::MoveOperands::IsEliminated(), v8::internal::compiler::InstructionOperand::IsFPLocationOperand(), v8::internal::kCombine, v8::internal::kFPAliasing, v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::MoveOperands::set_source(), and v8::internal::compiler::MoveOperands::source().
Referenced by v8::internal::compiler::MoveOptimizer::CompressMoves(), and v8::internal::compiler::LiveRangeConnector::ConnectRanges().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction.h
/mnt/V8SourceCode/src/compiler/backend/instruction.cc