v8::internal::maglev::MaglevConcurrentDispatcher::JobTask Class Reference
Public Member Functions
JobTask (MaglevConcurrentDispatcher *dispatcher)
void Run (JobDelegate *delegate) override
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Private Member Functions
Isolate * isolate () const
QueueT * incoming_queue () const
QueueT * outgoing_queue () const
QueueT * destruction_queue () const
Private Attributes
MaglevConcurrentDispatcher *const dispatcher_
Detailed Description
Definition at line 260 of file maglev-concurrent-dispatcher.cc.
Constructor & Destructor Documentation
JobTask()
v8::internal::maglev::MaglevConcurrentDispatcher::JobTask::JobTask (MaglevConcurrentDispatcher * dispatcher) [inline], [explicit]
Definition at line 262 of file maglev-concurrent-dispatcher.cc.
      : dispatcher_(dispatcher) {}
Member Function Documentation
destruction_queue()
QueueT* v8::internal::maglev::MaglevConcurrentDispatcher::JobTask::destruction_queue () const [inline], [private]
Definition at line 321 of file maglev-concurrent-dispatcher.cc.
{ return &dispatcher_->destruction_queue_; }
References dispatcher_.
Referenced by GetMaxConcurrency(), and Run().
GetMaxConcurrency()
size_t v8::internal::maglev::MaglevConcurrentDispatcher::JobTask::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 307 of file maglev-concurrent-dispatcher.cc.
                                                               {
    size_t num_tasks =
        incoming_queue()->size() + destruction_queue()->size() + worker_count;
    size_t max_threads = v8_flags.concurrent_maglev_max_threads;
    if (max_threads > 0) {
      return std::min(max_threads, num_tasks);
    }
    return num_tasks;
  }
References destruction_queue(), incoming_queue(), and v8::internal::v8_flags.
incoming_queue()
QueueT* v8::internal::maglev::MaglevConcurrentDispatcher::JobTask::incoming_queue () const [inline], [private]
Definition at line 319 of file maglev-concurrent-dispatcher.cc.
{ return &dispatcher_->incoming_queue_; }
References dispatcher_.
Referenced by GetMaxConcurrency(), and Run().
isolate()
Isolate* v8::internal::maglev::MaglevConcurrentDispatcher::JobTask::isolate () const [inline], [private]
Definition at line 318 of file maglev-concurrent-dispatcher.cc.
{ return dispatcher_->isolate_; }
References dispatcher_.
Referenced by Run().
outgoing_queue()
QueueT* v8::internal::maglev::MaglevConcurrentDispatcher::JobTask::outgoing_queue () const [inline], [private]
Definition at line 320 of file maglev-concurrent-dispatcher.cc.
{ return &dispatcher_->outgoing_queue_; }
References dispatcher_.
Referenced by Run().
Run()
void v8::internal::maglev::MaglevConcurrentDispatcher::JobTask::Run (JobDelegate * delegate) [inline], [override], [virtual]
Implements v8::JobTask.
Definition at line 265 of file maglev-concurrent-dispatcher.cc.
                                           {
    if (incoming_queue()->IsEmpty() && destruction_queue()->IsEmpty()) {
      return;
    }
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.compile"), "V8.MaglevTask");
    base::FlushDenormalsScope flush_denormals_scope(
        isolate()->flush_denormals());
    LocalIsolate local_isolate(isolate(), ThreadKind::kBackground);
    DCHECK(local_isolate.heap()->IsParked());
    std::unique_ptr<MaglevCompilationJob> job_to_destruct;
    while (!delegate->ShouldYield()) {
      std::unique_ptr<MaglevCompilationJob> job;
      if (incoming_queue()->Dequeue(&job)) {
        DCHECK_NOT_NULL(job);
        TRACE_EVENT_WITH_FLOW0(
            TRACE_DISABLED_BY_DEFAULT("v8.compile"), "V8.MaglevBackground",
            job->trace_id(),
            TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
        RCS_SCOPE(&local_isolate,
                  RuntimeCallCounterId::kOptimizeBackgroundMaglev);
        CompilationJob::Status status =
            job->ExecuteJob(local_isolate.runtime_call_stats(), &local_isolate);
        if (status == CompilationJob::SUCCEEDED) {
          outgoing_queue()->Enqueue(std::move(job));
          isolate()->stack_guard()->RequestInstallMaglevCode();
        }
      } else if (destruction_queue()->Dequeue(&job)) {
        // Maglev jobs aren't cheap to destruct, so destroy them here in the
        // background thread rather than on the main thread.
        DCHECK_NOT_NULL(job);
        TRACE_EVENT_WITH_FLOW0(TRACE_DISABLED_BY_DEFAULT("v8.compile"),
                               "V8.MaglevDestructBackground", job->trace_id(),
                               TRACE_EVENT_FLAG_FLOW_IN);
        UnparkedScope unparked_scope(&local_isolate);
        job.reset();
      } else {
        break;
      }
    }
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, destruction_queue(), v8::internal::LocalIsolate::heap(), incoming_queue(), isolate(), v8::internal::LocalHeap::IsParked(), v8::internal::kBackground, outgoing_queue(), RCS_SCOPE, v8::internal::LocalIsolate::runtime_call_stats(), v8::JobDelegate::ShouldYield(), v8::internal::Isolate::stack_guard(), v8::internal::status, v8::internal::CompilationJob::SUCCEEDED, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, and TRACE_EVENT_WITH_FLOW0.
Member Data Documentation
dispatcher_
MaglevConcurrentDispatcher* const v8::internal::maglev::MaglevConcurrentDispatcher::JobTask::dispatcher_ [private]
Definition at line 323 of file maglev-concurrent-dispatcher.cc.
Referenced by destruction_queue(), incoming_queue(), isolate(), and outgoing_queue().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-concurrent-dispatcher.cc