v8::internal::compiler::JSContextSpecialization Class Reference
#include <js-context-specialization.h>
Public Member Functions
JSContextSpecialization (Editor *editor, JSGraph *jsgraph, JSHeapBroker *broker, Maybe< OuterContext > outer, MaybeHandle< JSFunction > closure)
JSContextSpecialization (const JSContextSpecialization &)=delete
JSContextSpecialization & operator= (const JSContextSpecialization &)=delete
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
Reduction ReduceParameter (Node *node)
Reduction ReduceJSLoadContextNoCell (Node *node)
Reduction ReduceJSLoadContext (Node *node)
Reduction ReduceJSStoreContextNoCell (Node *node)
Reduction ReduceJSStoreContext (Node *node)
Reduction ReduceJSGetImportMeta (Node *node)
Reduction SimplifyJSLoadContextNoCell (Node *node, Node *new_context, size_t new_depth)
Reduction SimplifyJSLoadContext (Node *node, Node *new_context, size_t new_depth)
Reduction SimplifyJSStoreContextNoCell (Node *node, Node *new_context, size_t new_depth)
Reduction SimplifyJSStoreContext (Node *node, Node *new_context, size_t new_depth)
Isolate * isolate () const
JSGraph * jsgraph () const
Maybe< OuterContext > outer () const
MaybeHandle< JSFunction > closure () const
JSHeapBroker * broker () const
Private Attributes
JSGraph *const jsgraph_
Maybe< OuterContext > outer_
MaybeHandle< JSFunction > closure_
JSHeapBroker *const broker_
Additional Inherited Members
Detailed Description
Definition at line 37 of file js-context-specialization.h.
Constructor & Destructor Documentation
JSContextSpecialization() [1/2]
v8::internal::compiler::JSContextSpecialization::JSContextSpecialization (Editor * editor, JSGraph * jsgraph, JSHeapBroker * broker, Maybe< OuterContext > outer, MaybeHandle< JSFunction > closure) [inline]
Definition at line 39 of file js-context-specialization.h.
      : AdvancedReducer(editor),
        jsgraph_(jsgraph),
        outer_(outer),
        closure_(closure),
        broker_(broker) {}
JSContextSpecialization() [2/2]
v8::internal::compiler::JSContextSpecialization::JSContextSpecialization (const JSContextSpecialization &) [delete]
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::JSContextSpecialization::broker () const [inline], [private]
Definition at line 77 of file js-context-specialization.h.
{ return broker_; }
Referenced by ReduceJSGetImportMeta(), ReduceJSLoadContext(), ReduceJSLoadContextNoCell(), ReduceJSStoreContext(), ReduceJSStoreContextNoCell(), and ReduceParameter().
closure()
MaybeHandle<JSFunction> v8::internal::compiler::JSContextSpecialization::closure () const [inline], [private]
Definition at line 76 of file js-context-specialization.h.
{ return closure_; }
Referenced by ReduceParameter().
isolate()
Isolate * v8::internal::compiler::JSContextSpecialization::isolate () const [private]
Definition at line 559 of file js-context-specialization.cc.
                                                {
  return jsgraph()->isolate();
}
References v8::internal::compiler::JSGraph::isolate(), and jsgraph().
jsgraph()
JSGraph* v8::internal::compiler::JSContextSpecialization::jsgraph () const [inline], [private]
Definition at line 74 of file js-context-specialization.h.
{ return jsgraph_; }
Referenced by isolate(), ReduceJSGetImportMeta(), ReduceJSLoadContext(), ReduceJSLoadContextNoCell(), ReduceJSStoreContext(), ReduceJSStoreContextNoCell(), and ReduceParameter().
operator=()
JSContextSpecialization& v8::internal::compiler::JSContextSpecialization::operator= (const JSContextSpecialization &) [delete]
outer()
Maybe<OuterContext> v8::internal::compiler::JSContextSpecialization::outer () const [inline], [private]
Definition at line 75 of file js-context-specialization.h.
{ return outer_; }
Referenced by ReduceJSGetImportMeta(), ReduceJSLoadContext(), ReduceJSLoadContextNoCell(), ReduceJSStoreContext(), and ReduceJSStoreContextNoCell().
Reduce()
Reduction v8::internal::compiler::JSContextSpecialization::Reduce (Node * node) [final], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 28 of file js-context-specialization.cc.
                                                    {
  switch (node->opcode()) {
    case IrOpcode::kParameter:
      return ReduceParameter(node);
    case IrOpcode::kJSLoadContextNoCell:
      return ReduceJSLoadContextNoCell(node);
    case IrOpcode::kJSLoadContext:
      return ReduceJSLoadContext(node);
    case IrOpcode::kJSStoreContextNoCell:
      return ReduceJSStoreContextNoCell(node);
    case IrOpcode::kJSStoreContext:
      return ReduceJSStoreContext(node);
    case IrOpcode::kJSGetImportMeta:
      return ReduceJSGetImportMeta(node);
    default:
      break;
  }
  return NoChange();
}
References v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::opcode(), ReduceJSGetImportMeta(), ReduceJSLoadContext(), ReduceJSLoadContextNoCell(), ReduceJSStoreContext(), ReduceJSStoreContextNoCell(), and ReduceParameter().
ReduceJSGetImportMeta()
Reduction v8::internal::compiler::JSContextSpecialization::ReduceJSGetImportMeta (Node * node) [private]
Definition at line 537 of file js-context-specialization.cc.
                                                                   {
  OptionalContextRef maybe_context = GetModuleContext(broker(), node, outer());
  if (!maybe_context.has_value()) return NoChange();
  ContextRef context = maybe_context.value();
  OptionalObjectRef module = context.get(broker(), Context::EXTENSION_INDEX);
  if (!module.has_value()) return NoChange();
  OptionalObjectRef import_meta =
      module->AsSourceTextModule().import_meta(broker());
  if (!import_meta.has_value()) return NoChange();
  if (!import_meta->IsJSObject()) {
    DCHECK(import_meta->IsTheHole());
    // The import.meta object has not yet been created. Let JSGenericLowering
    // replace the operator with a runtime call.
    return NoChange();
  }
  Node* import_meta_const = jsgraph()->ConstantNoHole(*import_meta, broker());
  ReplaceWithValue(node, import_meta_const);
  return Changed(import_meta_const);
}
References broker(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::DCHECK(), v8::internal::Context::EXTENSION_INDEX, v8::internal::compiler::ContextRef::get(), v8::internal::compiler::GetModuleContext(), jsgraph(), v8::internal::compiler::Reducer::NoChange(), outer(), and v8::internal::compiler::AdvancedReducer::ReplaceWithValue().
Referenced by Reduce().
ReduceJSLoadContext()
Reduction v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext (Node * node) [private]
Definition at line 248 of file js-context-specialization.cc.
                                                                 {
  DCHECK_EQ(IrOpcode::kJSLoadContext, node->opcode());
  const ContextAccess& access = ContextAccessOf(node->op());
  DCHECK(!access.immutable());
  size_t depth = access.depth();
  // First walk up the context chain in the graph as far as possible.
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* context = NodeProperties::GetOuterContext(node, &depth);
  OptionalContextRef maybe_concrete =
      GetSpecializationContext(broker(), context, &depth, outer());
  if (!maybe_concrete.has_value()) {
    // We do not have a concrete context object, so we can only partially reduce
    // the load by folding-in the outer context node.
    return SimplifyJSLoadContext(node, context, depth);
  }
  // Now walk up the concrete context chain for the remaining depth.
  ContextRef concrete = maybe_concrete.value();
  concrete = concrete.previous(broker(), &depth);
  if (depth > 0) {
    TRACE_BROKER_MISSING(broker(), "previous value for context " << concrete);
    return SimplifyJSLoadContext(
        node, jsgraph()->ConstantNoHole(concrete, broker()), depth);
  }
  auto maybe_value = concrete.get(broker(), static_cast<int>(access.index()));
  if (!maybe_value || maybe_value->IsTheHole() ||
      maybe_value->IsUndefinedContextCell()) {
    return SimplifyJSLoadContext(
        node, jsgraph()->ConstantNoHole(concrete, broker()), depth);
  }
  if (!maybe_value->IsContextCell()) {
    // Do a normal context load.
    Node* load = effect = jsgraph_->graph()->NewNode(
        jsgraph_->simplified()->LoadField(
            AccessBuilder::ForContextSlot(access.index())),
        jsgraph_->ConstantNoHole(concrete, broker()), effect, control);
    ReplaceWithValue(node, load, effect, control);
    return Changed(node);
  }
  DCHECK(concrete.object()->HasContextCells());
  compiler::ContextCellRef slot_ref = maybe_value->AsContextCell();
  // TODO(victorgomes): Make DependOnContextCell return the state instead.
  ContextCell::State state = slot_ref.state();
  switch (state) {
    case ContextCell::kConst: {
      auto constant = slot_ref.tagged_value(broker());
      if (!constant.has_value()) {
        return SimplifyJSLoadContext(
            node, jsgraph()->ConstantNoHole(concrete, broker()), depth);
      }
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      ReplaceWithValue(node, jsgraph_->ConstantNoHole(*constant, broker()),
                       effect, control);
      return Changed(node);
    }
    case ContextCell::kSmi: {
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      Node* load = effect = jsgraph_->graph()->NewNode(
          jsgraph_->simplified()->LoadField(
              AccessBuilder::ForContextCellTaggedValue()),
          jsgraph_->ConstantNoHole(slot_ref, broker()), effect, control);
      ReplaceWithValue(node, load, effect, control);
      return Changed(node);
    }
    case ContextCell::kInt32: {
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      Node* int32_load = effect = jsgraph_->graph()->NewNode(
          jsgraph_->simplified()->LoadField(
              AccessBuilder::ForContextCellInt32Value()),
          jsgraph_->ConstantNoHole(slot_ref, broker()), effect, control);
      ReplaceWithValue(node, int32_load, effect, control);
      return Changed(node);
    }
    case ContextCell::kFloat64: {
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      Node* double_load = effect = jsgraph_->graph()->NewNode(
          jsgraph_->simplified()->LoadField(
              AccessBuilder::ForContextCellFloat64Value()),
          jsgraph_->ConstantNoHole(slot_ref, broker()), effect, control);
      ReplaceWithValue(node, double_load, effect, control);
      return Changed(node);
    }
    case ContextCell::kDetached: {
      Node* load = effect = jsgraph_->graph()->NewNode(
          jsgraph_->simplified()->LoadField(
              AccessBuilder::ForContextSlot(access.index())),
          jsgraph_->ConstantNoHole(concrete, broker()), effect, control);
      ReplaceWithValue(node, load, effect, control);
      return Changed(node);
    }
  }
  UNREACHABLE();
}
References broker(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::ContextAccessOf(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnContextCell(), v8::internal::compiler::ContextAccess::depth(), v8::internal::compiler::AccessBuilder::ForContextCellFloat64Value(), v8::internal::compiler::AccessBuilder::ForContextCellInt32Value(), v8::internal::compiler::AccessBuilder::ForContextCellTaggedValue(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::ContextRef::get(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetOuterContext(), v8::internal::compiler::anonymous_namespace{js-context-specialization.cc}::GetSpecializationContext(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::ContextAccess::immutable(), v8::internal::compiler::ContextAccess::index(), jsgraph(), jsgraph_, v8::internal::ContextCell::kConst, v8::internal::ContextCell::kDetached, v8::internal::ContextCell::kFloat64, v8::internal::ContextCell::kInt32, v8::internal::ContextCell::kSmi, v8::internal::compiler::SimplifiedOperatorBuilder::LoadField(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::ContextRef::object(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), outer(), v8::internal::compiler::ContextRef::previous(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), v8::internal::compiler::JSGraph::simplified(), SimplifyJSLoadContext(), v8::internal::compiler::ContextCellRef::state(), v8::internal::compiler::ContextCellRef::tagged_value(), TRACE_BROKER_MISSING, and v8::internal::UNREACHABLE().
Referenced by Reduce().
ReduceJSLoadContextNoCell()
Reduction v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContextNoCell (Node * node) [private]
Definition at line 185 of file js-context-specialization.cc.
                                                                       {
  DCHECK_EQ(IrOpcode::kJSLoadContextNoCell, node->opcode());
  const ContextAccess& access = ContextAccessOf(node->op());
  size_t depth = access.depth();
  // First walk up the context chain in the graph as far as possible.
  Node* context = NodeProperties::GetOuterContext(node, &depth);
  OptionalContextRef maybe_concrete =
      GetSpecializationContext(broker(), context, &depth, outer());
  if (!maybe_concrete.has_value()) {
    // We do not have a concrete context object, so we can only partially reduce
    // the load by folding-in the outer context node.
    return SimplifyJSLoadContextNoCell(node, context, depth);
  }
  // Now walk up the concrete context chain for the remaining depth.
  ContextRef concrete = maybe_concrete.value();
  concrete = concrete.previous(broker(), &depth);
  if (depth > 0) {
    TRACE_BROKER_MISSING(broker(), "previous value for context " << concrete);
    return SimplifyJSLoadContextNoCell(
        node, jsgraph()->ConstantNoHole(concrete, broker()), depth);
  }
  if (!access.immutable() &&
      !broker()->dependencies()->DependOnContextCell(
          concrete, access.index(), ContextCell::kConst, broker())) {
    // We found the requested context object but since the context slot is
    // mutable we can only partially reduce the load.
    return SimplifyJSLoadContextNoCell(
        node, jsgraph()->ConstantNoHole(concrete, broker()), depth);
  }
  // This will hold the final value, if we can figure it out.
  OptionalObjectRef maybe_value;
  maybe_value = concrete.get(broker(), static_cast<int>(access.index()));
  if (!maybe_value.has_value()) {
    TRACE_BROKER_MISSING(broker(), "slot value " << access.index()
                                                 << " for context "
                                                 << concrete);
    return SimplifyJSLoadContextNoCell(
        node, jsgraph()->ConstantNoHole(concrete, broker()), depth);
  }
  // Even though the context slot is immutable, the context might have escaped
  // before the function to which it belongs has initialized the slot.
  // We must be conservative and check if the value in the slot is currently
  // the hole or undefined. Only if it is neither of these, can we be sure
  // that it won't change anymore.
  if (maybe_value->IsUndefined() || maybe_value->IsTheHole()) {
    return SimplifyJSLoadContextNoCell(
        node, jsgraph()->ConstantNoHole(concrete, broker()), depth);
  }
  // Success. The context load can be replaced with the constant.
  Node* constant = jsgraph_->ConstantNoHole(*maybe_value, broker());
  ReplaceWithValue(node, constant);
  return Replace(constant);
}
References broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::ContextAccessOf(), DCHECK_EQ, v8::internal::compiler::ContextAccess::depth(), v8::internal::compiler::ContextRef::get(), v8::internal::compiler::NodeProperties::GetOuterContext(), v8::internal::compiler::anonymous_namespace{js-context-specialization.cc}::GetSpecializationContext(), v8::internal::compiler::ContextAccess::immutable(), v8::internal::compiler::ContextAccess::index(), jsgraph(), jsgraph_, v8::internal::ContextCell::kConst, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), outer(), v8::internal::compiler::ContextRef::previous(), v8::internal::compiler::AdvancedReducer::Replace(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), SimplifyJSLoadContextNoCell(), and TRACE_BROKER_MISSING.
Referenced by Reduce().
ReduceJSStoreContext()
Reduction v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext (Node * node) [private]
Definition at line 379 of file js-context-specialization.cc.
                                                                  {
  DCHECK(v8_flags.script_context_cells || v8_flags.function_context_cells);
  DCHECK_EQ(IrOpcode::kJSStoreContext, node->opcode());
  const ContextAccess& access = ContextAccessOf(node->op());
  size_t depth = access.depth();
  // First walk up the context chain in the graph until we reduce the depth to 0
  // or hit a node that does not have a CreateXYZContext operator.
  Node* context = NodeProperties::GetOuterContext(node, &depth);
  Node* value = NodeProperties::GetValueInput(node, 0);
  Effect effect{NodeProperties::GetEffectInput(node)};
  Control control{NodeProperties::GetControlInput(node)};
  OptionalContextRef maybe_concrete =
      GetSpecializationContext(broker(), context, &depth, outer());
  if (!maybe_concrete.has_value()) {
    // We do not have a concrete context object, so we can only partially reduce
    // the load by folding-in the outer context node.
    return SimplifyJSStoreContext(node, context, depth);
  }
  // Now walk up the concrete context chain for the remaining depth.
  ContextRef concrete = maybe_concrete.value();
  concrete = concrete.previous(broker(), &depth);
  if (depth > 0) {
    TRACE_BROKER_MISSING(broker(), "previous value for context " << concrete);
    return SimplifyJSStoreContext(
        node, jsgraph()->ConstantNoHole(concrete, broker()), depth);
  }
  auto maybe_value = concrete.get(broker(), static_cast<int>(access.index()));
  if (!maybe_value || maybe_value->IsTheHole() ||
      maybe_value->IsUndefinedContextCell()) {
    return SimplifyJSStoreContext(
        node, jsgraph()->ConstantNoHole(concrete, broker()), depth);
  }
  if (!maybe_value->IsContextCell()) {
    // Do a normal context store.
    Node* store = jsgraph()->graph()->NewNode(
        jsgraph()->simplified()->StoreField(
            AccessBuilder::ForContextSlot(access.index())),
        jsgraph()->ConstantNoHole(concrete, broker()), value, effect, control);
    ReplaceWithValue(node, store, store, control);
    return Changed(node);
  }
  DCHECK(concrete.object()->HasContextCells());
  compiler::ContextCellRef slot_ref = maybe_value->AsContextCell();
  PropertyAccessBuilder access_builder(jsgraph(), broker());
  ContextCell::State state = slot_ref.state();
  switch (state) {
    case ContextCell::kConst: {
      auto constant = slot_ref.tagged_value(broker());
      if (!constant.has_value() ||
          (constant->IsString() && !constant->IsInternalizedString())) {
        return SimplifyJSStoreContext(
            node, jsgraph()->ConstantNoHole(concrete, broker()), depth);
      }
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      access_builder.BuildCheckValue(value, &effect, control, *constant);
      ReplaceWithValue(node, effect, effect, control);
      return Changed(node);
    }
    case ContextCell::kSmi: {
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      Node* smi_value = access_builder.BuildCheckSmi(value, &effect, control);
      Node* smi_store = jsgraph()->graph()->NewNode(
          jsgraph()->simplified()->StoreField(
              AccessBuilder::ForContextCellTaggedValue()),
          jsgraph()->ConstantNoHole(slot_ref, broker()), smi_value, effect,
          control);
      ReplaceWithValue(node, smi_store, smi_store, control);
      return Changed(node);
    }
    case ContextCell::kInt32: {
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      Node* input_number =
          access_builder.BuildCheckNumberFitsInt32(value, &effect, control);
      Node* double_store = jsgraph()->graph()->NewNode(
          jsgraph()->simplified()->StoreField(
              AccessBuilder::ForContextCellInt32Value()),
          jsgraph_->ConstantNoHole(slot_ref, broker()), input_number, effect,
          control);
      ReplaceWithValue(node, double_store, double_store, control);
      return Changed(node);
    }
    case ContextCell::kFloat64: {
      broker()->dependencies()->DependOnContextCell(slot_ref, state);
      Node* input_number =
          access_builder.BuildCheckNumber(value, &effect, control);
      Node* double_store = jsgraph()->graph()->NewNode(
          jsgraph()->simplified()->StoreField(
              AccessBuilder::ForContextCellFloat64Value()),
          jsgraph_->ConstantNoHole(slot_ref, broker()), input_number, effect,
          control);
      ReplaceWithValue(node, double_store, double_store, control);
      return Changed(node);
    }
    case ContextCell::kDetached: {
      Node* store = jsgraph()->graph()->NewNode(
          jsgraph()->simplified()->StoreField(
              AccessBuilder::ForContextSlot(access.index())),
          jsgraph()->ConstantNoHole(concrete, broker()), value, effect,
          control);
      ReplaceWithValue(node, store, store, control);
      return Changed(node);
    }
  }
  UNREACHABLE();
}
References broker(), v8::internal::compiler::PropertyAccessBuilder::BuildCheckNumber(), v8::internal::compiler::PropertyAccessBuilder::BuildCheckNumberFitsInt32(), v8::internal::compiler::PropertyAccessBuilder::BuildCheckSmi(), v8::internal::compiler::PropertyAccessBuilder::BuildCheckValue(), v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::ContextAccessOf(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::JSHeapBroker::dependencies(), v8::internal::compiler::CompilationDependencies::DependOnContextCell(), v8::internal::compiler::ContextAccess::depth(), v8::internal::compiler::AccessBuilder::ForContextCellFloat64Value(), v8::internal::compiler::AccessBuilder::ForContextCellInt32Value(), v8::internal::compiler::AccessBuilder::ForContextCellTaggedValue(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::ContextRef::get(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetOuterContext(), v8::internal::compiler::anonymous_namespace{js-context-specialization.cc}::GetSpecializationContext(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::ContextAccess::index(), jsgraph(), jsgraph_, v8::internal::ContextCell::kConst, v8::internal::ContextCell::kDetached, v8::internal::ContextCell::kFloat64, v8::internal::ContextCell::kInt32, v8::internal::ContextCell::kSmi, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::ContextRef::object(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), outer(), v8::internal::compiler::ContextRef::previous(), v8::internal::compiler::AdvancedReducer::ReplaceWithValue(), SimplifyJSStoreContext(), v8::internal::compiler::ContextCellRef::state(), store(), v8::internal::compiler::ContextCellRef::tagged_value(), TRACE_BROKER_MISSING, v8::internal::UNREACHABLE(), v8::internal::v8_flags, and v8::internal::value.
Referenced by Reduce().
ReduceJSStoreContextNoCell()
Reduction v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContextNoCell (Node * node) [private]
Definition at line 348 of file js-context-specialization.cc.
                                                                        {
  DCHECK_EQ(IrOpcode::kJSStoreContextNoCell, node->opcode());
  const ContextAccess& access = ContextAccessOf(node->op());
  size_t depth = access.depth();
  // First walk up the context chain in the graph until we reduce the depth to 0
  // or hit a node that does not have a CreateXYZContext operator.
  Node* context = NodeProperties::GetOuterContext(node, &depth);
  OptionalContextRef maybe_concrete =
      GetSpecializationContext(broker(), context, &depth, outer());
  if (!maybe_concrete.has_value()) {
    // We do not have a concrete context object, so we can only partially reduce
    // the load by folding-in the outer context node.
    return SimplifyJSStoreContextNoCell(node, context, depth);
  }
  // Now walk up the concrete context chain for the remaining depth.
  ContextRef concrete = maybe_concrete.value();
  concrete = concrete.previous(broker(), &depth);
  if (depth > 0) {
    TRACE_BROKER_MISSING(broker(), "previous value for context " << concrete);
    return SimplifyJSStoreContextNoCell(
        node, jsgraph()->ConstantNoHole(concrete, broker()), depth);
  }
  return SimplifyJSStoreContextNoCell(
      node, jsgraph()->ConstantNoHole(concrete, broker()), depth);
}
References broker(), v8::internal::compiler::ContextAccessOf(), DCHECK_EQ, v8::internal::compiler::ContextAccess::depth(), v8::internal::compiler::NodeProperties::GetOuterContext(), v8::internal::compiler::anonymous_namespace{js-context-specialization.cc}::GetSpecializationContext(), jsgraph(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), outer(), v8::internal::compiler::ContextRef::previous(), SimplifyJSStoreContextNoCell(), and TRACE_BROKER_MISSING.
Referenced by Reduce().
ReduceParameter()
Reduction v8::internal::compiler::JSContextSpecialization::ReduceParameter (Node * node) [private]
Definition at line 48 of file js-context-specialization.cc.
                                                             {
  DCHECK_EQ(IrOpcode::kParameter, node->opcode());
  int const index = ParameterIndexOf(node->op());
  if (index == Linkage::kJSCallClosureParamIndex) {
    // Constant-fold the function parameter {node}.
    Handle<JSFunction> function;
    if (closure().ToHandle(&function)) {
      Node* value =
          jsgraph()->ConstantNoHole(MakeRef(broker_, function), broker());
      return Replace(value);
    }
  }
  return NoChange();
}
References broker(), broker_, closure(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_EQ, v8::internal::index, jsgraph(), v8::internal::compiler::Linkage::kJSCallClosureParamIndex, v8::internal::compiler::MakeRef(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::ParameterIndexOf(), v8::internal::compiler::AdvancedReducer::Replace(), v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::value.
Referenced by Reduce().
reducer_name()
const char* v8::internal::compiler::JSContextSpecialization::reducer_name () const [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 50 of file js-context-specialization.h.
                                            {
    return "JSContextSpecialization";
  }
SimplifyJSLoadContext()
Reduction v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContext (Node * node, Node * new_context, size_t new_depth) [private]
Definition at line 81 of file js-context-specialization.cc.
                                                                           {
  DCHECK_EQ(IrOpcode::kJSLoadContext, node->opcode());
  const ContextAccess& access = ContextAccessOf(node->op());
  DCHECK_LE(new_depth, access.depth());
  if (new_depth == access.depth() &&
      new_context == NodeProperties::GetContextInput(node)) {
    return NoChange();
  }
  const Operator* op =
      jsgraph_->javascript()->LoadContext(new_depth, access.index());
  NodeProperties::ReplaceContextInput(node, new_context);
  NodeProperties::ChangeOp(node, op);
  return Changed(node);
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::ContextAccessOf(), DCHECK_EQ, DCHECK_LE, v8::internal::compiler::ContextAccess::depth(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::ContextAccess::index(), v8::internal::compiler::JSGraph::javascript(), jsgraph_, v8::internal::compiler::JSOperatorBuilder::LoadContext(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::NodeProperties::ReplaceContextInput().
Referenced by ReduceJSLoadContext().
SimplifyJSLoadContextNoCell()
Reduction v8::internal::compiler::JSContextSpecialization::SimplifyJSLoadContextNoCell (Node * node, Node * new_context, size_t new_depth) [private]
Definition at line 63 of file js-context-specialization.cc.
                                                     {
  DCHECK_EQ(IrOpcode::kJSLoadContextNoCell, node->opcode());
  const ContextAccess& access = ContextAccessOf(node->op());
  DCHECK_LE(new_depth, access.depth());
  if (new_depth == access.depth() &&
      new_context == NodeProperties::GetContextInput(node)) {
    return NoChange();
  }
  const Operator* op = jsgraph_->javascript()->LoadContextNoCell(
      new_depth, access.index(), access.immutable());
  NodeProperties::ReplaceContextInput(node, new_context);
  NodeProperties::ChangeOp(node, op);
  return Changed(node);
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::ContextAccessOf(), DCHECK_EQ, DCHECK_LE, v8::internal::compiler::ContextAccess::depth(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::ContextAccess::immutable(), v8::internal::compiler::ContextAccess::index(), v8::internal::compiler::JSGraph::javascript(), jsgraph_, v8::internal::compiler::JSOperatorBuilder::LoadContextNoCell(), v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::NodeProperties::ReplaceContextInput().
Referenced by ReduceJSLoadContextNoCell().
SimplifyJSStoreContext()
Reduction v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContext (Node * node, Node * new_context, size_t new_depth) [private]
Definition at line 118 of file js-context-specialization.cc.
                                                                            {
  DCHECK_EQ(IrOpcode::kJSStoreContext, node->opcode());
  const ContextAccess& access = ContextAccessOf(node->op());
  DCHECK_LE(new_depth, access.depth());
  if (new_depth == access.depth() &&
      new_context == NodeProperties::GetContextInput(node)) {
    return NoChange();
  }
  const Operator* op =
      jsgraph_->javascript()->StoreContext(new_depth, access.index());
  NodeProperties::ReplaceContextInput(node, new_context);
  NodeProperties::ChangeOp(node, op);
  return Changed(node);
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::ContextAccessOf(), DCHECK_EQ, DCHECK_LE, v8::internal::compiler::ContextAccess::depth(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::ContextAccess::index(), v8::internal::compiler::JSGraph::javascript(), jsgraph_, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::NodeProperties::ReplaceContextInput(), and v8::internal::compiler::JSOperatorBuilder::StoreContext().
Referenced by ReduceJSStoreContext().
SimplifyJSStoreContextNoCell()
Reduction v8::internal::compiler::JSContextSpecialization::SimplifyJSStoreContextNoCell (Node * node, Node * new_context, size_t new_depth) [private]
Definition at line 100 of file js-context-specialization.cc.
                                                     {
  DCHECK_EQ(IrOpcode::kJSStoreContextNoCell, node->opcode());
  const ContextAccess& access = ContextAccessOf(node->op());
  DCHECK_LE(new_depth, access.depth());
  if (new_depth == access.depth() &&
      new_context == NodeProperties::GetContextInput(node)) {
    return NoChange();
  }
  const Operator* op =
      jsgraph_->javascript()->StoreContextNoCell(new_depth, access.index());
  NodeProperties::ReplaceContextInput(node, new_context);
  NodeProperties::ChangeOp(node, op);
  return Changed(node);
}
References v8::internal::compiler::Reducer::Changed(), v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::ContextAccessOf(), DCHECK_EQ, DCHECK_LE, v8::internal::compiler::ContextAccess::depth(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::ContextAccess::index(), v8::internal::compiler::JSGraph::javascript(), jsgraph_, v8::internal::compiler::Reducer::NoChange(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::NodeProperties::ReplaceContextInput(), and v8::internal::compiler::JSOperatorBuilder::StoreContextNoCell().
Referenced by ReduceJSStoreContextNoCell().
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::JSContextSpecialization::broker_ [private]
Definition at line 82 of file js-context-specialization.h.
Referenced by ReduceParameter().
closure_
MaybeHandle<JSFunction> v8::internal::compiler::JSContextSpecialization::closure_ [private]
Definition at line 81 of file js-context-specialization.h.
jsgraph_
JSGraph* const v8::internal::compiler::JSContextSpecialization::jsgraph_ [private]
Definition at line 79 of file js-context-specialization.h.
Referenced by ReduceJSLoadContext(), ReduceJSLoadContextNoCell(), ReduceJSStoreContext(), SimplifyJSLoadContext(), SimplifyJSLoadContextNoCell(), SimplifyJSStoreContext(), and SimplifyJSStoreContextNoCell().
outer_
Maybe<OuterContext> v8::internal::compiler::JSContextSpecialization::outer_ [private]
Definition at line 80 of file js-context-specialization.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-context-specialization.h
/mnt/V8SourceCode/src/compiler/js-context-specialization.cc