v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived > Class Template Reference
#include <maglev-assembler.h>
Classes
struct SavedData
Public Member Functions
TemporaryRegisterScopeBase (MaglevAssembler *masm)
TemporaryRegisterScopeBase (MaglevAssembler *masm, const SavedData &saved_data)
~TemporaryRegisterScopeBase ()
void ResetToDefault ()
Register Acquire ()
void Include (const RegList list)
DoubleRegister AcquireDouble ()
void IncludeDouble (const DoubleRegList list)
RegList Available ()
void SetAvailable (RegList list)
DoubleRegList AvailableDouble ()
void SetAvailableDouble (DoubleRegList list)
Protected Member Functions
SavedData CopyForDeferBase ()
Protected Attributes
MaglevAssembler * masm_
Derived * prev_scope_
RegList available_
DoubleRegList available_double_
Detailed Description
template<typename Derived>
class v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >
Definition at line 871 of file maglev-assembler.h.
Constructor & Destructor Documentation
TemporaryRegisterScopeBase() [1/2]
template<typename Derived >
v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::TemporaryRegisterScopeBase (MaglevAssembler * masm) [inline], [explicit]
Definition at line 878 of file maglev-assembler.h.
      : masm_(masm),
        prev_scope_(masm->scratch_register_scope_),
        available_(masm->scratch_register_scope_
                       ? static_cast<TemporaryRegisterScopeBase*>(prev_scope_)
                             ->available_
                       : RegList()),
        available_double_(
            masm->scratch_register_scope_
                ? static_cast<TemporaryRegisterScopeBase*>(prev_scope_)
                      ->available_double_
                : DoubleRegList()) {
    masm_->scratch_register_scope_ = static_cast<Derived*>(this);
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::masm_, and v8::internal::maglev::MaglevAssembler::scratch_register_scope_.
TemporaryRegisterScopeBase() [2/2]
template<typename Derived >
v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::TemporaryRegisterScopeBase (MaglevAssembler * masm, const SavedData & saved_data) [inline], [explicit]
Definition at line 892 of file maglev-assembler.h.
      : masm_(masm),
        prev_scope_(masm->scratch_register_scope_),
        available_(saved_data.available_),
        available_double_(saved_data.available_double_) {
    masm_->scratch_register_scope_ = static_cast<Derived*>(this);
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::masm_, and v8::internal::maglev::MaglevAssembler::scratch_register_scope_.
 TemporaryRegisterScopeBase()
template<typename Derived >
v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::~TemporaryRegisterScopeBase () [inline]
Definition at line 900 of file maglev-assembler.h.
                                {
    masm_->scratch_register_scope_ = prev_scope_;
    // TODO(leszeks): Clear used registers.
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::masm_, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::prev_scope_, and v8::internal::maglev::MaglevAssembler::scratch_register_scope_.
Member Function Documentation
Acquire()
template<typename Derived >
Register v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Acquire () [inline]
Definition at line 911 of file maglev-assembler.h.
                     {
    CHECK(!available_.is_empty());
    return available_.PopFirst();
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_, CHECK, v8::internal::RegListBase< RegisterT >::is_empty(), and v8::internal::RegListBase< RegisterT >::PopFirst().
Referenced by v8::internal::maglev::BuiltinStringFromCharCode::GenerateCode(), v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::GenerateReduceInterruptBudget(), v8::internal::maglev::anonymous_namespace{maglev-ir-riscv.cc}::GenerateReduceInterruptBudget(), and v8::internal::maglev::MapCompare::MapCompare().
AcquireDouble()
template<typename Derived >
DoubleRegister v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::AcquireDouble () [inline]
Definition at line 920 of file maglev-assembler.h.
                                 {
    CHECK(!available_double_.is_empty());
    return available_double_.PopFirst();
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_double_, CHECK, v8::internal::RegListBase< RegisterT >::is_empty(), and v8::internal::RegListBase< RegisterT >::PopFirst().
Available()
template<typename Derived >
RegList v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Available () [inline]
Definition at line 929 of file maglev-assembler.h.
{ return available_; }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_.
Referenced by v8::internal::maglev::MaglevAssembler::CallBuiltin(), v8::internal::maglev::MaglevAssembler::Prologue(), and v8::internal::maglev::MaglevAssembler::TestTypeOf().
AvailableDouble()
template<typename Derived >
DoubleRegList v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::AvailableDouble () [inline]
Definition at line 932 of file maglev-assembler.h.
{ return available_double_; }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_double_.
CopyForDeferBase()
template<typename Derived >
SavedData v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::CopyForDeferBase () [inline], [protected]
Definition at line 936 of file maglev-assembler.h.
                               {
    return SavedData{available_, available_double_};
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_, and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_double_.
Include()
template<typename Derived >
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Include (const RegList list) [inline]
Definition at line 915 of file maglev-assembler.h.
                                   {
    DCHECK((list - kAllocatableGeneralRegisters).is_empty());
    available_ = available_ | list;
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::is_empty(), and v8::internal::kAllocatableGeneralRegisters.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), and v8::internal::maglev::MaglevAssembler::Prologue().
IncludeDouble()
template<typename Derived >
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::IncludeDouble (const DoubleRegList list) [inline]
Definition at line 924 of file maglev-assembler.h.
                                               {
    DCHECK((list - kAllocatableDoubleRegisters).is_empty());
    available_double_ = available_double_ | list;
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_double_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::is_empty(), and v8::internal::kAllocatableDoubleRegisters.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process().
ResetToDefault()
template<typename Derived >
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::ResetToDefault () [inline]
Definition at line 905 of file maglev-assembler.h.
                        {
    available_ = {};
    available_double_ = {};
    static_cast<Derived*>(this)->ResetToDefaultImpl();
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_, and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_double_.
Referenced by v8::internal::maglev::MaglevAssembler::CallBuiltin(), and v8::internal::maglev::MaglevAssembler::CallRuntime().
SetAvailable()
template<typename Derived >
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::SetAvailable (RegList list) [inline]
Definition at line 930 of file maglev-assembler.h.
{ available_ = list; }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_.
SetAvailableDouble()
template<typename Derived >
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::SetAvailableDouble (DoubleRegList list) [inline]
Definition at line 933 of file maglev-assembler.h.
{ available_double_ = list; }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_double_.
Member Data Documentation
available_
template<typename Derived >
RegList v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_ [protected]
Definition at line 942 of file maglev-assembler.h.
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Acquire(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Available(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::CopyForDeferBase(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::Include(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::ResetToDefault(), and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::SetAvailable().
available_double_
template<typename Derived >
DoubleRegList v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::available_double_ [protected]
Definition at line 943 of file maglev-assembler.h.
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::AcquireDouble(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::AvailableDouble(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::CopyForDeferBase(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::IncludeDouble(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::ResetToDefault(), and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::SetAvailableDouble().
masm_
template<typename Derived >
MaglevAssembler* v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::masm_ [protected]
Definition at line 940 of file maglev-assembler.h.
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::TemporaryRegisterScopeBase(), and v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::~TemporaryRegisterScopeBase().
prev_scope_
template<typename Derived >
Derived* v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::prev_scope_ [protected]
Definition at line 941 of file maglev-assembler.h.
Referenced by v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< Derived >::~TemporaryRegisterScopeBase().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-assembler.h