v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter Class Reference
#include <graph-visualizer.h>
Public Member Functions
JSONTurboshaftGraphWriter (std::ostream &os, const Graph &turboshaft_graph, NodeOriginTable *origins, Zone *zone)
JSONTurboshaftGraphWriter (const JSONTurboshaftGraphWriter &)=delete
JSONTurboshaftGraphWriter & operator= (const JSONTurboshaftGraphWriter &)=delete
void Print ()
Protected Member Functions
void PrintNodes ()
void PrintEdges ()
void PrintBlocks ()
Protected Attributes
std::ostream & os_
Zone * zone_
const Graph & turboshaft_graph_
NodeOriginTable * origins_
Detailed Description
Definition at line 29 of file graph-visualizer.h.
Constructor & Destructor Documentation
JSONTurboshaftGraphWriter() [1/2]
v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::JSONTurboshaftGraphWriter (std::ostream & os, const Graph & turboshaft_graph, NodeOriginTable * origins, Zone * zone)
Definition at line 13 of file graph-visualizer.cc.
    : os_(os),
      zone_(zone),
      turboshaft_graph_(turboshaft_graph),
      origins_(origins) {}
JSONTurboshaftGraphWriter() [2/2]
v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::JSONTurboshaftGraphWriter (const JSONTurboshaftGraphWriter &) [delete]
Member Function Documentation
operator=()
JSONTurboshaftGraphWriter& v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::operator= (const JSONTurboshaftGraphWriter &) [delete]
Print()
void v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::Print ()
Definition at line 21 of file graph-visualizer.cc.
                                      {
  os_ << "{\n\"nodes\":[";
  PrintNodes();
  os_ << "\n],\n\"edges\":[";
  PrintEdges();
  os_ << "\n],\n\"blocks\":[";
  PrintBlocks();
  os_ << "\n]}";
}
References os_, PrintBlocks(), PrintEdges(), and PrintNodes().
Referenced by v8::internal::compiler::turboshaft::operator<<().
PrintBlocks()
void v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintBlocks () [protected]
Definition at line 82 of file graph-visualizer.cc.
                                            {
  bool first_block = true;
  for (const Block& block : turboshaft_graph_.blocks()) {
    if (!first_block) os_ << ",\n";
    first_block = false;
    os_ << "{\"id\":" << block.index().id() << ",";
    os_ << "\"type\":\"" << block.kind() << "\",";
    os_ << "\"predecessors\":[";
    bool first_predecessor = true;
    for (const Block* pred : block.Predecessors()) {
      if (!first_predecessor) os_ << ", ";
      first_predecessor = false;
      os_ << pred->index().id();
    }
    os_ << "]}";
  }
}
References v8::internal::compiler::turboshaft::Graph::blocks(), os_, v8::internal::compiler::turboshaft::Block::Predecessors(), and turboshaft_graph_.
Referenced by Print().
PrintEdges()
void v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintEdges () [protected]
Definition at line 57 of file graph-visualizer.cc.
                                           {
  bool first = true;
  for (const Block& block : turboshaft_graph_.blocks()) {
    for (const Operation& op : turboshaft_graph_.operations(block)) {
      int target_id = turboshaft_graph_.Index(op).id();
      base::SmallVector<OpIndex, 32> inputs{op.inputs()};
      // Reorder the inputs to correspond to the order used in constructor and
      // assembler functions.
      if (auto* store = op.TryCast<StoreOp>()) {
        if (store->index().valid()) {
          DCHECK_EQ(store->input_count, 3);
          inputs = {store->base(), store->index().value_or_invalid(),
                    store->value()};
        }
      }
      for (OpIndex input : inputs) {
        if (!first) os_ << ",\n";
        first = false;
        os_ << "{\"source\":" << input.id() << ",";
        os_ << "\"target\":" << target_id << "}";
      }
    }
  }
}
References v8::internal::compiler::turboshaft::Graph::blocks(), DCHECK_EQ, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::Graph::Index(), v8::internal::compiler::turboshaft::Graph::operations(), os_, store(), and turboshaft_graph_.
Referenced by Print().
PrintNodes()
void v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintNodes () [protected]
Definition at line 31 of file graph-visualizer.cc.
                                           {
  bool first = true;
  for (const Block& block : turboshaft_graph_.blocks()) {
    for (const Operation& op : turboshaft_graph_.operations(block)) {
      OpIndex index = turboshaft_graph_.Index(op);
      if (!first) os_ << ",\n";
      first = false;
      os_ << "{\"id\":" << index.id() << ",";
      os_ << "\"title\":\"" << OpcodeName(op.opcode) << "\",";
      os_ << "\"block_id\":" << block.index().id() << ",";
      os_ << "\"op_effects\":\"" << op.Effects() << "\"";
      if (origins_) {
        NodeOrigin origin = origins_->GetNodeOrigin(index.id());
        if (origin.IsKnown()) {
          os_ << ", \"origin\":" << AsJSON(origin);
        }
      }
      SourcePosition position = turboshaft_graph_.source_positions()[index];
      if (position.IsKnown()) {
        os_ << ", \"sourcePosition\":" << compiler::AsJSON(position);
      }
      os_ << "}";
    }
  }
}
References v8::internal::compiler::turboshaft::AsJSON(), v8::internal::compiler::AsJSON(), v8::internal::compiler::turboshaft::Graph::blocks(), v8::internal::compiler::NodeOriginTable::GetNodeOrigin(), v8::internal::compiler::turboshaft::Graph::Index(), v8::internal::index, v8::internal::compiler::NodeOrigin::IsKnown(), v8::internal::SourcePosition::IsKnown(), v8::internal::compiler::turboshaft::OpcodeName(), v8::internal::compiler::turboshaft::Graph::operations(), origins_, os_, v8::internal::compiler::turboshaft::Graph::source_positions(), and turboshaft_graph_.
Referenced by Print().
Member Data Documentation
origins_
NodeOriginTable* v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::origins_ [protected]
Definition at line 49 of file graph-visualizer.h.
Referenced by PrintNodes().
os_
std::ostream& v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::os_ [protected]
Definition at line 46 of file graph-visualizer.h.
Referenced by Print(), PrintBlocks(), PrintEdges(), and PrintNodes().
turboshaft_graph_
const Graph& v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::turboshaft_graph_ [protected]
Definition at line 48 of file graph-visualizer.h.
Referenced by PrintBlocks(), PrintEdges(), and PrintNodes().
zone_
Zone* v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::zone_ [protected]
Definition at line 47 of file graph-visualizer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/graph-visualizer.h
/mnt/V8SourceCode/src/compiler/turboshaft/graph-visualizer.cc