v8::internal::compiler::turboshaft::Tracing Class Reference
#include <tracing.h>
Public Types
using OperationDataPrinter = std::function< bool(std::ostream &, const Graph &, OpIndex)>
using BlockDataPrinter = std::function< bool(std::ostream &, const Graph &, BlockIndex)>
Public Member Functions
Tracing (OptimizedCompilationInfo *info)
bool is_enabled () const
void PrintPerOperationData (const char *data_name, const Graph &graph, OperationDataPrinter printer)
void PrintPerBlockData (const char *data_name, const Graph &graph, BlockDataPrinter printer)
Private Attributes
OptimizedCompilationInfo * info_
Additional Inherited Members
Detailed Description
Definition at line 16 of file tracing.h.
Member Typedef Documentation
BlockDataPrinter
using v8::internal::compiler::turboshaft::Tracing::BlockDataPrinter = std::function<bool(std::ostream&, const Graph&, BlockIndex)>
Definition at line 24 of file tracing.h.
OperationDataPrinter
using v8::internal::compiler::turboshaft::Tracing::OperationDataPrinter = std::function<bool(std::ostream&, const Graph&, OpIndex)>
Definition at line 22 of file tracing.h.
Constructor & Destructor Documentation
Tracing()
v8::internal::compiler::turboshaft::Tracing::Tracing (OptimizedCompilationInfo * info) [inline], [explicit]
Definition at line 18 of file tracing.h.
                                                   : info_(info) {
    DCHECK_NOT_NULL(info_);
  }
References DCHECK_NOT_NULL, and info_.
Member Function Documentation
is_enabled()
bool v8::internal::compiler::turboshaft::Tracing::is_enabled () const [inline]
Definition at line 27 of file tracing.h.
{ return info_->trace_turbo_json(); }
References info_.
Referenced by PrintPerBlockData(), and PrintPerOperationData().
PrintPerBlockData()
void v8::internal::compiler::turboshaft::Tracing::PrintPerBlockData (const char * data_name, const Graph & graph, BlockDataPrinter printer) [inline]
Definition at line 36 of file tracing.h.
                                                   {
    DCHECK(printer);
    if (!is_enabled()) return;
    TurboJsonFile json_of(info_, std::ios_base::app);
    PrintTurboshaftCustomDataPerBlock(json_of, data_name, graph, printer);
  }
References v8::internal::DCHECK(), graph(), info_, is_enabled(), and v8::internal::compiler::turboshaft::PrintTurboshaftCustomDataPerBlock().
PrintPerOperationData()
void v8::internal::compiler::turboshaft::Tracing::PrintPerOperationData (const char * data_name, const Graph & graph, OperationDataPrinter printer) [inline]
Definition at line 29 of file tracing.h.
                                                           {
    DCHECK(printer);
    if (!is_enabled()) return;
    TurboJsonFile json_of(info_, std::ios_base::app);
    PrintTurboshaftCustomDataPerOperation(json_of, data_name, graph, printer);
  }
References v8::internal::DCHECK(), graph(), info_, is_enabled(), and v8::internal::compiler::turboshaft::PrintTurboshaftCustomDataPerOperation().
Member Data Documentation
info_
OptimizedCompilationInfo* v8::internal::compiler::turboshaft::Tracing::info_ [private]
Definition at line 45 of file tracing.h.
Referenced by is_enabled(), PrintPerBlockData(), PrintPerOperationData(), and Tracing().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/tracing.h