cppgc::internal::MarkerBase Class Reference
#include <marker.h>
Classes
class IncrementalMarkingAllocationObserver
class IncrementalMarkingTask
class PauseConcurrentMarkingScope
Public Types
enum class WriteBarrierType { kDijkstra
, kSteele
 }
Public Member Functions
virtual ~MarkerBase ()
MarkerBase (const MarkerBase &)=delete
MarkerBase & operator= (const MarkerBase &)=delete
template<typename Class >
Class & To ()
void EnterAtomicPause (StackState)
void EnterProcessGlobalAtomicPause ()
void ReEnableConcurrentMarking ()
bool AdvanceMarkingWithLimits (v8::base::TimeDelta=kMaximumIncrementalStepDuration, size_t marked_bytes_limit=0)
size_t last_bytes_marked () const
void LeaveAtomicPause ()
void StartMarking ()
void FinishMarking (StackState)
void ProcessCrossThreadWeaknessIfNeeded ()
void ProcessWeakness ()
bool JoinConcurrentMarkingIfNeeded ()
void NotifyConcurrentMarkingOfWorkIfNeeded (cppgc::TaskPriority)
template<WriteBarrierType type>
void WriteBarrierForObject (HeapObjectHeader &)
HeapBase & heap ()
cppgc::Visitor & Visitor ()
bool IsMarking () const
void SetMainThreadMarkingDisabledForTesting (bool)
void WaitForConcurrentMarkingForTesting ()
void ClearAllWorklistsForTesting ()
bool IncrementalMarkingStepForTesting (StackState)
MarkingWorklists & MarkingWorklistsForTesting ()
MutatorMarkingState & MutatorMarkingStateForTesting ()
Protected Types
using IncrementalMarkingTaskHandle = SingleThreadedHandle
Protected Member Functions
MarkerBase (HeapBase &, cppgc::Platform *, MarkingConfig)
virtual cppgc::Visitor & visitor ()=0
virtual ConservativeTracingVisitor & conservative_visitor ()=0
virtual heap::base::StackVisitor & stack_visitor ()=0
virtual ConcurrentMarkerBase & concurrent_marker ()=0
virtual heap::base::IncrementalMarkingSchedule & schedule ()=0
bool ProcessWorklistsWithDeadline (size_t marked_bytes_deadline, v8::base::TimeTicks time_deadline)
void AdvanceMarkingWithLimitsEpilogue ()
void VisitLocalRoots (StackState)
void VisitCrossThreadRoots ()
void MarkNotFullyConstructedObjects ()
virtual void ScheduleIncrementalMarkingTask ()
bool IncrementalMarkingStep (StackState)
void AdvanceMarkingOnAllocation ()
virtual void AdvanceMarkingOnAllocationImpl ()
void HandleNotFullyConstructedObjects ()
void MarkStrongCrossThreadRoots ()
Protected Attributes
HeapBase & heap_
MarkingConfig config_ = MarkingConfig::Default()
cppgc::Platform * platform_
std::shared_ptr< cppgc::TaskRunner > foreground_task_runner_
IncrementalMarkingTaskHandle incremental_marking_handle_
IncrementalMarkingAllocationObserver incremental_marking_allocation_observer_
MarkingWorklists marking_worklists_
MutatorMarkingState mutator_marking_state_
size_t last_bytes_marked_ = 0
bool is_marking_ {false}
bool main_marking_disabled_for_testing_ {false}
bool visited_cross_thread_persistents_in_atomic_pause_ {false}
bool processed_cross_thread_weakness_ {false}
Static Protected Attributes
static constexpr v8::base::TimeDelta kMaximumIncrementalStepDuration
Detailed Description
Definition at line 45 of file marker.h.
Member Typedef Documentation
IncrementalMarkingTaskHandle
using cppgc::internal::MarkerBase::IncrementalMarkingTaskHandle = SingleThreadedHandle [protected]
Definition at line 161 of file marker.h.
Member Enumeration Documentation
WriteBarrierType
enum cppgc::internal::MarkerBase::WriteBarrierType [strong]
Enumerator
kDijkstra
kSteele
Definition at line 49 of file marker.h.
                              {
    kDijkstra,
    kSteele,
  };
Constructor & Destructor Documentation
 MarkerBase()
cppgc::internal::MarkerBase::~MarkerBase () [virtual]
Definition at line 166 of file marker.cc.
                        {
  // The fixed point iteration may have found not-fully-constructed objects.
  // Such objects should have already been found through the stack scan though
  // and should thus already be marked.
  if (!marking_worklists_.not_fully_constructed_worklist()->IsEmpty()) {
#if DEBUG
    DCHECK_NE(StackState::kNoHeapPointers, config_.stack_state);
    std::unordered_set<HeapObjectHeader*> objects =
        mutator_marking_state_.not_fully_constructed_worklist().Extract();
    for (HeapObjectHeader* object : objects) DCHECK(object->IsMarked());
#else
    marking_worklists_.not_fully_constructed_worklist()->Clear();
#endif
  }
  // |discovered_ephemeron_pairs_worklist_| may still hold ephemeron pairs with
  // dead keys.
  if (!marking_worklists_.discovered_ephemeron_pairs_worklist()->IsEmpty()) {
#if DEBUG
    MarkingWorklists::EphemeronPairItem item;
    while (mutator_marking_state_.discovered_ephemeron_pairs_worklist().Pop(
        &item)) {
      DCHECK(!HeapObjectHeader::FromObject(item.key).IsMarked());
    }
#else
    marking_worklists_.discovered_ephemeron_pairs_worklist()->Clear();
#endif
  }
  marking_worklists_.weak_containers_worklist()->Clear();
}
References heap::base::Worklist< EntryType, MinSegmentSize >::Clear(), cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Clear(), config_, DCHECK, DCHECK_NE, cppgc::internal::BasicMarkingState::discovered_ephemeron_pairs_worklist(), cppgc::internal::MarkingWorklists::discovered_ephemeron_pairs_worklist(), cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Extract(), cppgc::internal::HeapObjectHeader::FromObject(), cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::IsEmpty(), heap::base::Worklist< EntryType, MinSegmentSize >::IsEmpty(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::MarkingWorklists::EphemeronPairItem::key, marking_worklists_, mutator_marking_state_, cppgc::internal::MarkingStateBase::not_fully_constructed_worklist(), cppgc::internal::MarkingWorklists::not_fully_constructed_worklist(), cppgc::internal::MarkingConfig::stack_state, and cppgc::internal::MarkingWorklists::weak_containers_worklist().
MarkerBase() [1/2]
cppgc::internal::MarkerBase::MarkerBase (const MarkerBase &) [delete]
MarkerBase() [2/2]
cppgc::internal::MarkerBase::MarkerBase (HeapBase & heap, cppgc::Platform * platform, MarkingConfig config) [protected]
Definition at line 153 of file marker.cc.
    : heap_(heap),
      config_(config),
      platform_(platform),
      foreground_task_runner_(platform_->GetForegroundTaskRunner()),
      incremental_marking_allocation_observer_(*this),
      mutator_marking_state_(heap, marking_worklists_,
                             heap.compactor().compaction_worklists()) {
  DCHECK_IMPLIES(config_.collection_type == CollectionType::kMinor,
                 heap_.generational_gc_supported());
}
References cppgc::internal::MarkingConfig::collection_type, config_, DCHECK_IMPLIES, cppgc::internal::HeapBase::generational_gc_supported(), heap_, and cppgc::internal::kMinor.
Member Function Documentation
AdvanceMarkingOnAllocation()
void cppgc::internal::MarkerBase::AdvanceMarkingOnAllocation () [protected]
Definition at line 565 of file marker.cc.
                                            {
  StatsCollector::EnabledScope stats_scope(heap().stats_collector(),
                                           StatsCollector::kIncrementalMark);
  StatsCollector::EnabledScope nested_scope(heap().stats_collector(),
                                            StatsCollector::kMarkOnAllocation);
  AdvanceMarkingOnAllocationImpl();
}
References AdvanceMarkingOnAllocationImpl(), and heap().
AdvanceMarkingOnAllocationImpl()
void cppgc::internal::MarkerBase::AdvanceMarkingOnAllocationImpl () [protected], [virtual]
Reimplemented in v8::internal::UnifiedHeapMarker.
Definition at line 573 of file marker.cc.
                                                {
  if (AdvanceMarkingWithLimits()) {
    // Schedule another incremental task for finalizing without a stack.
    ScheduleIncrementalMarkingTask();
  }
}
References AdvanceMarkingWithLimits(), and ScheduleIncrementalMarkingTask().
Referenced by AdvanceMarkingOnAllocation().
AdvanceMarkingWithLimits()
bool cppgc::internal::MarkerBase::AdvanceMarkingWithLimits (v8::base::TimeDelta max_duration = kMaximumIncrementalStepDuration, size_t marked_bytes_limit = 0)
Definition at line 610 of file marker.cc.
                                                                     {
  if (V8_UNLIKELY(main_marking_disabled_for_testing_)) {
    AdvanceMarkingWithLimitsEpilogue();
    return false;
  }
  StatsCollector::EnabledScope deadline_scope(
      heap().stats_collector(),
      StatsCollector::kMarkTransitiveClosureWithDeadline, "max_duration_ms",
      max_duration.InMillisecondsF(), "max_bytes", marked_bytes_limit);
  last_bytes_marked_ = 0;
  const auto deadline = v8::base::TimeTicks::Now() + max_duration;
  if (marked_bytes_limit == 0) {
    marked_bytes_limit = GetNextIncrementalStepDuration(schedule(), heap_);
  }
  // `ProcessWorklistsWithDeadline()` below checks against `marked_bytes()`
  // which are never reset.
  size_t marked_bytes_deadline =
      marked_bytes_limit + mutator_marking_state_.marked_bytes();
  if (marked_bytes_deadline < marked_bytes_limit) {
    marked_bytes_deadline = SIZE_MAX;
  }
  const bool is_done =
      ProcessWorklistsWithDeadline(marked_bytes_deadline, deadline);
  last_bytes_marked_ = mutator_marking_state_.RecentlyMarkedBytes();
  schedule().AddMutatorThreadMarkedBytes(last_bytes_marked_);
  mutator_marking_state_.Publish();
  if (!is_done) {
    AdvanceMarkingWithLimitsEpilogue();
  }
  return is_done;
}
References heap::base::IncrementalMarkingSchedule::AddMutatorThreadMarkedBytes(), AdvanceMarkingWithLimitsEpilogue(), cppgc::internal::anonymous_namespace{marker.cc}::GetNextIncrementalStepDuration(), heap(), heap_, v8::base::TimeDelta::InMillisecondsF(), last_bytes_marked_, main_marking_disabled_for_testing_, cppgc::internal::BasicMarkingState::marked_bytes(), mutator_marking_state_, v8::base::TimeTicks::Now(), ProcessWorklistsWithDeadline(), cppgc::internal::MutatorMarkingState::Publish(), cppgc::internal::BasicMarkingState::RecentlyMarkedBytes(), schedule(), and V8_UNLIKELY.
Referenced by AdvanceMarkingOnAllocationImpl(), FinishMarking(), and IncrementalMarkingStep().
AdvanceMarkingWithLimitsEpilogue()
void cppgc::internal::MarkerBase::AdvanceMarkingWithLimitsEpilogue () [protected]
Definition at line 600 of file marker.cc.
                                                  {
  // Epilogue is only needed when marking is not finished.
  DCHECK_NE(MarkingConfig::MarkingType::kAtomic, config_.marking_type);
  ScheduleIncrementalMarkingTask();
  if (config_.marking_type ==
      MarkingConfig::MarkingType::kIncrementalAndConcurrent) {
    concurrent_marker().NotifyIncrementalMutatorStepCompleted();
  }
}
References concurrent_marker(), config_, DCHECK_NE, cppgc::Heap::kAtomic, cppgc::Heap::kIncrementalAndConcurrent, cppgc::internal::MarkingConfig::marking_type, cppgc::internal::ConcurrentMarkerBase::NotifyIncrementalMutatorStepCompleted(), and ScheduleIncrementalMarkingTask().
Referenced by AdvanceMarkingWithLimits().
ClearAllWorklistsForTesting()
void cppgc::internal::MarkerBase::ClearAllWorklistsForTesting ()
Definition at line 767 of file marker.cc.
                                             {
  marking_worklists_.ClearForTesting();
  auto* compaction_worklists = heap_.compactor().compaction_worklists();
  if (compaction_worklists) compaction_worklists->ClearForTesting();
}
References cppgc::internal::CompactionWorklists::ClearForTesting(), cppgc::internal::MarkingWorklists::ClearForTesting(), cppgc::internal::Compactor::compaction_worklists(), cppgc::internal::HeapBase::compactor(), heap_, and marking_worklists_.
concurrent_marker()
virtual ConcurrentMarkerBase& cppgc::internal::MarkerBase::concurrent_marker () [protected], [pure virtual]
Implemented in cppgc::internal::Marker, and v8::internal::UnifiedHeapMarker.
Referenced by AdvanceMarkingWithLimitsEpilogue(), EnterAtomicPause(), JoinConcurrentMarkingIfNeeded(), LeaveAtomicPause(), NotifyConcurrentMarkingOfWorkIfNeeded(), ReEnableConcurrentMarking(), StartMarking(), and WaitForConcurrentMarkingForTesting().
conservative_visitor()
virtual ConservativeTracingVisitor& cppgc::internal::MarkerBase::conservative_visitor () [protected], [pure virtual]
Implemented in cppgc::internal::Marker, and v8::internal::UnifiedHeapMarker.
Referenced by v8::internal::CppHeap::EnterFinalPause(), MarkNotFullyConstructedObjects(), and VisitLocalRoots().
EnterAtomicPause()
void cppgc::internal::MarkerBase::EnterAtomicPause (StackState stack_state)
Definition at line 251 of file marker.cc.
                                                        {
  StatsCollector::EnabledScope top_stats_scope(heap().stats_collector(),
                                               StatsCollector::kAtomicMark);
  StatsCollector::EnabledScope stats_scope(heap().stats_collector(),
                                           StatsCollector::kMarkAtomicPrologue);
  const MarkingConfig::MarkingType old_marking_type = config_.marking_type;
  if (ExitIncrementalMarkingIfNeeded(config_, heap())) {
    // Cancel remaining incremental tasks. Concurrent marking jobs are left to
    // run in parallel with the atomic pause until the mutator thread runs out
    // of work.
    incremental_marking_handle_.CancelIfNonEmpty();
    heap().stats_collector()->UnregisterObserver(
        &incremental_marking_allocation_observer_);
  }
  config_.stack_state = stack_state;
  config_.marking_type = MarkingConfig::MarkingType::kAtomic;
  mutator_marking_state_.set_in_atomic_pause();
  {
    // VisitLocalRoots() also resets the LABs.
    VisitLocalRoots(config_.stack_state);
    // Early marking of strong cross-thread roots before parallel marking. Helps
    // avoiding long single-threaded marking phases.
    MarkStrongCrossThreadRoots();
    HandleNotFullyConstructedObjects();
  }
  if (old_marking_type ==
      MarkingConfig::MarkingType::kIncrementalAndConcurrent) {
    // Start parallel marking.
    mutator_marking_state_.Publish();
    ConcurrentMarkerBase& marker = concurrent_marker();
    if (marker.IsActive()) {
      marker.NotifyIncrementalMutatorStepCompleted();
    } else {
      marker.Start();
    }
  }
}
References cppgc::internal::SingleThreadedHandle::CancelIfNonEmpty(), concurrent_marker(), config_, cppgc::internal::anonymous_namespace{marker.cc}::ExitIncrementalMarkingIfNeeded(), HandleNotFullyConstructedObjects(), heap(), incremental_marking_allocation_observer_, incremental_marking_handle_, cppgc::internal::ConcurrentMarkerBase::IsActive(), cppgc::Heap::kAtomic, cppgc::Heap::kIncrementalAndConcurrent, cppgc::internal::MarkingConfig::marking_type, MarkStrongCrossThreadRoots(), mutator_marking_state_, cppgc::internal::ConcurrentMarkerBase::NotifyIncrementalMutatorStepCompleted(), cppgc::internal::MutatorMarkingState::Publish(), cppgc::internal::BasicMarkingState::set_in_atomic_pause(), cppgc::internal::MarkingConfig::stack_state, cppgc::internal::ConcurrentMarkerBase::Start(), cppgc::internal::HeapBase::stats_collector(), cppgc::internal::StatsCollector::UnregisterObserver(), and VisitLocalRoots().
Referenced by v8::internal::CppHeap::EnterFinalPause(), and FinishMarking().
EnterProcessGlobalAtomicPause()
void cppgc::internal::MarkerBase::EnterProcessGlobalAtomicPause ()
Definition at line 325 of file marker.cc.
{ VisitCrossThreadRoots(); }
References VisitCrossThreadRoots().
Referenced by FinishMarking().
FinishMarking()
void cppgc::internal::MarkerBase::FinishMarking (StackState stack_state)
Definition at line 327 of file marker.cc.
                                                     {
  DCHECK(is_marking_);
  EnterAtomicPause(stack_state);
  EnterProcessGlobalAtomicPause();
  {
    StatsCollector::EnabledScope stats_scope(heap().stats_collector(),
                                             StatsCollector::kAtomicMark);
    CHECK(AdvanceMarkingWithLimits(v8::base::TimeDelta::Max(), SIZE_MAX));
    if (JoinConcurrentMarkingIfNeeded()) {
      CHECK(AdvanceMarkingWithLimits(v8::base::TimeDelta::Max(), SIZE_MAX));
    }
    mutator_marking_state_.Publish();
  }
  LeaveAtomicPause();
}
References AdvanceMarkingWithLimits(), CHECK, DCHECK, EnterAtomicPause(), EnterProcessGlobalAtomicPause(), heap(), is_marking_, JoinConcurrentMarkingIfNeeded(), LeaveAtomicPause(), v8::base::TimeDelta::Max(), mutator_marking_state_, and cppgc::internal::MutatorMarkingState::Publish().
HandleNotFullyConstructedObjects()
void cppgc::internal::MarkerBase::HandleNotFullyConstructedObjects () [protected]
Definition at line 243 of file marker.cc.
                                                  {
  if (config_.stack_state == StackState::kNoHeapPointers) {
    mutator_marking_state_.FlushNotFullyConstructedObjects();
  } else {
    MarkNotFullyConstructedObjects();
  }
}
References config_, cppgc::internal::MutatorMarkingState::FlushNotFullyConstructedObjects(), MarkNotFullyConstructedObjects(), mutator_marking_state_, and cppgc::internal::MarkingConfig::stack_state.
Referenced by EnterAtomicPause(), and JoinConcurrentMarkingIfNeeded().
heap()
HeapBase& cppgc::internal::MarkerBase::heap () [inline]
Definition at line 130 of file marker.h.
{ return heap_; }
Referenced by AdvanceMarkingOnAllocation(), AdvanceMarkingWithLimits(), EnterAtomicPause(), FinishMarking(), LeaveAtomicPause(), MarkNotFullyConstructedObjects(), MarkStrongCrossThreadRoots(), cppgc::internal::MarkerBase::IncrementalMarkingTask::Post(), ProcessCrossThreadWeaknessIfNeeded(), ProcessWeakness(), ProcessWorklistsWithDeadline(), cppgc::internal::MarkerBase::IncrementalMarkingTask::Run(), StartMarking(), VisitCrossThreadRoots(), and VisitLocalRoots().
IncrementalMarkingStep()
bool cppgc::internal::MarkerBase::IncrementalMarkingStep (StackState stack_state) [protected]
Definition at line 556 of file marker.cc.
                                                              {
  if (stack_state == StackState::kNoHeapPointers) {
    mutator_marking_state_.FlushNotFullyConstructedObjects();
  }
  config_.stack_state = stack_state;
  return AdvanceMarkingWithLimits();
}
References AdvanceMarkingWithLimits(), config_, cppgc::internal::MutatorMarkingState::FlushNotFullyConstructedObjects(), mutator_marking_state_, and cppgc::internal::MarkingConfig::stack_state.
Referenced by IncrementalMarkingStepForTesting(), and cppgc::internal::MarkerBase::IncrementalMarkingTask::Run().
IncrementalMarkingStepForTesting()
bool cppgc::internal::MarkerBase::IncrementalMarkingStepForTesting (StackState stack_state)
Definition at line 552 of file marker.cc.
                                                                        {
  return IncrementalMarkingStep(stack_state);
}
References IncrementalMarkingStep().
Referenced by cppgc::testing::StandaloneTestingHeap::PerformMarkingStep().
IsMarking()
bool cppgc::internal::MarkerBase::IsMarking () const [inline]
Definition at line 134 of file marker.h.
{ return is_marking_; }
Referenced by cppgc::subtle::HeapState::IsMarking().
JoinConcurrentMarkingIfNeeded()
bool cppgc::internal::MarkerBase::JoinConcurrentMarkingIfNeeded ()
Definition at line 580 of file marker.cc.
                                               {
  if (config_.marking_type != MarkingConfig::MarkingType::kAtomic ||
      !concurrent_marker().Join())
    return false;
  // Concurrent markers may have pushed some "leftover" in-construction objects
  // after flushing in EnterAtomicPause.
  HandleNotFullyConstructedObjects();
  DCHECK(marking_worklists_.not_fully_constructed_worklist()->IsEmpty());
  return true;
}
References concurrent_marker(), config_, DCHECK, HandleNotFullyConstructedObjects(), cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::IsEmpty(), cppgc::Heap::kAtomic, cppgc::internal::MarkingConfig::marking_type, marking_worklists_, and cppgc::internal::MarkingWorklists::not_fully_constructed_worklist().
Referenced by FinishMarking().
last_bytes_marked()
size_t cppgc::internal::MarkerBase::last_bytes_marked () const [inline]
Definition at line 103 of file marker.h.
{ return last_bytes_marked_; }
LeaveAtomicPause()
void cppgc::internal::MarkerBase::LeaveAtomicPause ()
Definition at line 308 of file marker.cc.
                                  {
  {
    StatsCollector::EnabledScope top_stats_scope(heap().stats_collector(),
                                                 StatsCollector::kAtomicMark);
    StatsCollector::EnabledScope stats_scope(
        heap().stats_collector(), StatsCollector::kMarkAtomicEpilogue);
    DCHECK(!incremental_marking_handle_);
    const size_t overall_marked_bytes =
        mutator_marking_state_.marked_bytes() +
        concurrent_marker().concurrently_marked_bytes();
    heap().stats_collector()->NotifyMarkingCompleted(overall_marked_bytes);
    is_marking_ = false;
  }
  ProcessWeakness();
  heap().SetStackStateOfPrevGC(config_.stack_state);
}
References concurrent_marker(), cppgc::internal::ConcurrentMarkerBase::concurrently_marked_bytes(), config_, DCHECK, heap(), incremental_marking_handle_, is_marking_, cppgc::internal::BasicMarkingState::marked_bytes(), mutator_marking_state_, cppgc::internal::StatsCollector::NotifyMarkingCompleted(), ProcessWeakness(), cppgc::internal::HeapBase::SetStackStateOfPrevGC(), cppgc::internal::MarkingConfig::stack_state, and cppgc::internal::HeapBase::stats_collector().
Referenced by FinishMarking().
MarkingWorklistsForTesting()
MarkingWorklists& cppgc::internal::MarkerBase::MarkingWorklistsForTesting () [inline]
Definition at line 141 of file marker.h.
{ return marking_worklists_; }
MarkNotFullyConstructedObjects()
void cppgc::internal::MarkerBase::MarkNotFullyConstructedObjects () [protected]
Definition at line 746 of file marker.cc.
                                                {
  // Parallel marking may still be running which is why atomic extraction is
  // required.
  std::unordered_set<HeapObjectHeader*> objects =
      mutator_marking_state_.not_fully_constructed_worklist()
          .Extract<AccessMode::kAtomic>();
  if (objects.empty()) {
    return;
  }
  StatsCollector::DisabledScope stats_scope(
      heap().stats_collector(),
      StatsCollector::kMarkVisitNotFullyConstructedObjects);
  for (HeapObjectHeader* object : objects) {
    DCHECK(object);
    // TraceConservativelyIfNeeded delegates to either in-construction or
    // fully constructed handling. Both handlers have their own marked bytes
    // accounting and markbit handling (bailout).
    conservative_visitor().TraceConservativelyIfNeeded(*object);
  }
}
References conservative_visitor(), DCHECK, cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Extract(), heap(), cppgc::internal::kAtomic, mutator_marking_state_, cppgc::internal::MarkingStateBase::not_fully_constructed_worklist(), and cppgc::internal::ConservativeTracingVisitor::TraceConservativelyIfNeeded().
Referenced by HandleNotFullyConstructedObjects().
MarkStrongCrossThreadRoots()
void cppgc::internal::MarkerBase::MarkStrongCrossThreadRoots () [protected]
Definition at line 538 of file marker.cc.
                                            {
  ProcessGlobalLock::Lock<ProcessGlobalLock::Reason::kForGC>();
  RootMarkingVisitor root_marking_visitor(mutator_marking_state_);
  heap().GetStrongCrossThreadPersistentRegion().Iterate(root_marking_visitor);
  ProcessGlobalLock::Unlock<ProcessGlobalLock::Reason::kForGC>();
}
References cppgc::internal::HeapBase::GetStrongCrossThreadPersistentRegion(), heap(), cppgc::internal::CrossThreadPersistentRegion::Iterate(), and mutator_marking_state_.
Referenced by EnterAtomicPause(), and StartMarking().
MutatorMarkingStateForTesting()
MutatorMarkingState& cppgc::internal::MarkerBase::MutatorMarkingStateForTesting () [inline]
Definition at line 142 of file marker.h.
                                                       {
    return mutator_marking_state_;
  }
NotifyConcurrentMarkingOfWorkIfNeeded()
void cppgc::internal::MarkerBase::NotifyConcurrentMarkingOfWorkIfNeeded (cppgc::TaskPriority priority)
Definition at line 592 of file marker.cc.
                                {
  ConcurrentMarkerBase& marker = concurrent_marker();
  if (marker.IsActive()) {
    marker.NotifyOfWorkIfNeeded(priority);
  }
}
References concurrent_marker(), cppgc::internal::ConcurrentMarkerBase::IsActive(), and cppgc::internal::ConcurrentMarkerBase::NotifyOfWorkIfNeeded().
operator=()
MarkerBase& cppgc::internal::MarkerBase::operator= (const MarkerBase &) [delete]
ProcessCrossThreadWeaknessIfNeeded()
void cppgc::internal::MarkerBase::ProcessCrossThreadWeaknessIfNeeded ()
Definition at line 374 of file marker.cc.
                                                    {
  DCHECK_EQ(MarkingConfig::MarkingType::kAtomic, config_.marking_type);
  if (processed_cross_thread_weakness_) {
    return;
  }
  StatsCollector::EnabledScope stats_scope(heap().stats_collector(),
                                           StatsCollector::kAtomicWeak);
  // Weakness callbacks are forbidden from allocating objects.
  cppgc::subtle::DisallowGarbageCollectionScope disallow_gc_scope(heap_);
  RootMarkingVisitor root_marking_visitor(mutator_marking_state_);
  // Processing cross-thread roots requires taking the global process lock.
  // Process these weak roots first to minimize the time the lock is held.
  ProcessGlobalLock::AssertHeld();
  CHECK(visited_cross_thread_persistents_in_atomic_pause_);
  heap().GetWeakCrossThreadPersistentRegion().Iterate(root_marking_visitor);
  ProcessGlobalLock::Unlock<ProcessGlobalLock::Reason::kForGC>();
  processed_cross_thread_weakness_ = true;
}
References cppgc::internal::ProcessGlobalLock::AssertHeld(), CHECK, config_, DCHECK_EQ, cppgc::internal::HeapBase::GetWeakCrossThreadPersistentRegion(), heap(), heap_, cppgc::internal::CrossThreadPersistentRegion::Iterate(), cppgc::Heap::kAtomic, cppgc::internal::MarkingConfig::marking_type, mutator_marking_state_, processed_cross_thread_weakness_, and visited_cross_thread_persistents_in_atomic_pause_.
Referenced by ProcessWeakness().
ProcessWeakness()
void cppgc::internal::MarkerBase::ProcessWeakness ()
Definition at line 397 of file marker.cc.
                                 {
  DCHECK_EQ(MarkingConfig::MarkingType::kAtomic, config_.marking_type);
  ProcessCrossThreadWeaknessIfNeeded();
  // Weakness callbacks are forbidden from allocating objects.
  cppgc::subtle::DisallowGarbageCollectionScope disallow_gc_scope(heap_);
  StatsCollector::EnabledScope stats_scope(heap().stats_collector(),
                                           StatsCollector::kAtomicWeak);
  RootMarkingVisitor root_marking_visitor(mutator_marking_state_);
  // Launch the parallel job before anything else to provide the maximum time
  // slice for processing.
  LivenessBroker broker = LivenessBrokerFactory::Create();
  std::unique_ptr<cppgc::JobHandle> job_handle{nullptr};
  if (heap().marking_support() ==
      cppgc::Heap::MarkingType::kIncrementalAndConcurrent) {
    job_handle = platform_->PostJob(
        cppgc::TaskPriority::kUserBlocking,
        std::make_unique<WeakCallbackJobTask>(
            this, marking_worklists_.parallel_weak_callback_worklist(),
            broker));
  }
  // Process same-thread roots.
  heap().GetWeakPersistentRegion().Iterate(root_marking_visitor);
  // Call weak callbacks on objects that may now be pointing to dead objects.
#if defined(CPPGC_YOUNG_GENERATION)
  if (heap().generational_gc_supported()) {
    auto& remembered_set = heap().remembered_set();
    if (config_.collection_type == CollectionType::kMinor) {
      // Custom callbacks assume that untraced pointers point to not yet freed
      // objects. They must make sure that upon callback completion no
      // UntracedMember points to a freed object. This may not hold true if a
      // custom callback for an old object operates with a reference to a young
      // object that was freed on a minor collection cycle. To maintain the
      // invariant that UntracedMembers always point to valid objects, execute
      // custom callbacks for old objects on each minor collection cycle.
      remembered_set.ExecuteCustomCallbacks(broker);
    } else {
      // For major GCs, just release all the remembered weak callbacks.
      remembered_set.ReleaseCustomCallbacks();
    }
  }
#endif // defined(CPPGC_YOUNG_GENERATION)
  {
    // First, process weak container callbacks.
    StatsCollector::EnabledScope inner_stats_scope(
        heap().stats_collector(),
        StatsCollector::kWeakContainerCallbacksProcessing);
    MarkingWorklists::WeakCallbackItem item;
    MarkingWorklists::WeakCallbackWorklist::Local& collections_local =
        mutator_marking_state_.weak_container_callback_worklist();
    while (collections_local.Pop(&item)) {
      item.callback(broker, item.parameter);
    }
  }
  {
    // Then, process custom weak callbacks.
    StatsCollector::EnabledScope inner_stats_scope(
        heap().stats_collector(), StatsCollector::kCustomCallbacksProcessing);
    MarkingWorklists::WeakCallbackItem item;
    MarkingWorklists::WeakCustomCallbackWorklist::Local& custom_callbacks =
        mutator_marking_state_.weak_custom_callback_worklist();
    while (custom_callbacks.Pop(&item)) {
      item.callback(broker, item.parameter);
#if defined(CPPGC_YOUNG_GENERATION)
      if (heap().generational_gc_supported())
        heap().remembered_set().AddWeakCallback(item);
#endif // defined(CPPGC_YOUNG_GENERATION)
    }
  }
  if (job_handle) {
    job_handle->Join();
  } else {
    MarkingWorklists::WeakCallbackItem item;
    MarkingWorklists::WeakCallbackWorklist::Local& local =
        mutator_marking_state_.parallel_weak_callback_worklist();
    while (local.Pop(&item)) {
      item.callback(broker, item.parameter);
    }
  }
  // Weak callbacks should not add any new objects for marking.
  DCHECK(marking_worklists_.marking_worklist()->IsEmpty());
}
References broker(), cppgc::internal::MarkingWorklists::WeakCallbackItem::callback, cppgc::internal::MarkingConfig::collection_type, config_, cppgc::internal::LivenessBrokerFactory::Create(), DCHECK, DCHECK_EQ, cppgc::internal::HeapBase::GetWeakPersistentRegion(), heap(), heap_, heap::base::Worklist< EntryType, MinSegmentSize >::IsEmpty(), cppgc::internal::PersistentRegionBase::Iterate(), cppgc::Heap::kAtomic, cppgc::Heap::kIncrementalAndConcurrent, cppgc::internal::kMinor, v8::kUserBlocking, cppgc::internal::MarkingConfig::marking_type, cppgc::internal::MarkingWorklists::marking_worklist(), marking_worklists_, mutator_marking_state_, cppgc::internal::BasicMarkingState::parallel_weak_callback_worklist(), cppgc::internal::MarkingWorklists::parallel_weak_callback_worklist(), cppgc::internal::MarkingWorklists::WeakCallbackItem::parameter, platform_, cppgc::Platform::PostJob(), ProcessCrossThreadWeaknessIfNeeded(), cppgc::internal::BasicMarkingState::weak_container_callback_worklist(), and cppgc::internal::BasicMarkingState::weak_custom_callback_worklist().
Referenced by LeaveAtomicPause().
ProcessWorklistsWithDeadline()
bool cppgc::internal::MarkerBase::ProcessWorklistsWithDeadline (size_t marked_bytes_deadline, v8::base::TimeTicks time_deadline) [protected]
Definition at line 644 of file marker.cc.
                                                                 {
  StatsCollector* stats_collector = heap().stats_collector();
  StatsCollector::EnabledScope stats_scope(
      stats_collector, StatsCollector::kMarkTransitiveClosure);
  bool saved_did_discover_new_ephemeron_pairs;
  do {
    mutator_marking_state_.ResetDidDiscoverNewEphemeronPairs();
    if ((config_.marking_type == MarkingConfig::MarkingType::kAtomic) ||
        schedule().ShouldFlushEphemeronPairs()) {
      mutator_marking_state_.FlushDiscoveredEphemeronPairs();
    }
    // Bailout objects may be complicated to trace and thus might take longer
    // than other objects. Therefore we reduce the interval between deadline
    // checks to guarantee the deadline is not exceeded.
    if (!DrainWorklistWithBytesAndTimeDeadline<
            StatsCollector::kMarkProcessBailOutObjects,
            kDefaultDeadlineCheckInterval / 5>(
            stats_collector, mutator_marking_state_, SIZE_MAX, time_deadline,
            mutator_marking_state_.concurrent_marking_bailout_worklist(),
            [this](const MarkingWorklists::ConcurrentMarkingBailoutItem& item) {
              mutator_marking_state_.AccountMarkedBytes(
                  BasePage::FromPayload(const_cast<void*>(item.parameter)),
                  item.bailedout_size);
              item.callback(&visitor(), item.parameter);
            })) {
      return false;
    }
    if (!DrainWorklistWithBytesAndTimeDeadline<
            StatsCollector::kMarkProcessNotFullyconstructedWorklist>(
            stats_collector, mutator_marking_state_, marked_bytes_deadline,
            time_deadline,
            mutator_marking_state_.previously_not_fully_constructed_worklist(),
            [this](HeapObjectHeader* header) {
              mutator_marking_state_.AccountMarkedBytes(*header);
              DynamicallyTraceMarkedObject<AccessMode::kNonAtomic>(visitor(),
                                                                   *header);
            })) {
      return false;
    }
    if (!DrainWorklistWithBytesAndTimeDeadline<
            StatsCollector::kMarkProcessMarkingWorklist>(
            stats_collector, mutator_marking_state_, marked_bytes_deadline,
            time_deadline, mutator_marking_state_.marking_worklist(),
            [this](const MarkingWorklists::MarkingItem& item) {
              const HeapObjectHeader& header =
                  HeapObjectHeader::FromObject(item.base_object_payload);
              DCHECK(!header.IsInConstruction<AccessMode::kNonAtomic>());
              DCHECK(header.IsMarked<AccessMode::kAtomic>());
              mutator_marking_state_.AccountMarkedBytes(header);
              item.callback(&visitor(), item.base_object_payload);
            })) {
      return false;
    }
    if (!DrainWorklistWithBytesAndTimeDeadline<
            StatsCollector::kMarkProcessWriteBarrierWorklist>(
            stats_collector, mutator_marking_state_, marked_bytes_deadline,
            time_deadline, mutator_marking_state_.write_barrier_worklist(),
            [this](HeapObjectHeader* header) {
              mutator_marking_state_.AccountMarkedBytes(*header);
              DynamicallyTraceMarkedObject<AccessMode::kNonAtomic>(visitor(),
                                                                   *header);
            })) {
      return false;
    }
    if (!DrainWorklistWithBytesAndTimeDeadline<
            StatsCollector::kMarkProcessRetraceWorklist>(
            stats_collector, mutator_marking_state_, marked_bytes_deadline,
            time_deadline,
            mutator_marking_state_.retrace_marked_objects_worklist(),
            [this](HeapObjectHeader* header) {
              // Retracing does not increment marked bytes as the object has
              // already been processed before.
              DynamicallyTraceMarkedObject<AccessMode::kNonAtomic>(visitor(),
                                                                   *header);
            })) {
      return false;
    }
    saved_did_discover_new_ephemeron_pairs =
        mutator_marking_state_.DidDiscoverNewEphemeronPairs();
    if (!DrainWorklistWithBytesAndTimeDeadline<
            StatsCollector::kMarkProcessEphemerons>(
            stats_collector, mutator_marking_state_, marked_bytes_deadline,
            time_deadline,
            mutator_marking_state_.ephemeron_pairs_for_processing_worklist(),
            [this](const MarkingWorklists::EphemeronPairItem& item) {
              mutator_marking_state_.ProcessEphemeron(
                  item.key, item.value, item.value_desc, visitor());
            })) {
      return false;
    }
  } while (!mutator_marking_state_.marking_worklist().IsLocalAndGlobalEmpty() ||
           saved_did_discover_new_ephemeron_pairs);
  return true;
}
References cppgc::internal::BasicMarkingState::concurrent_marking_bailout_worklist(), config_, cppgc::internal::BasicMarkingState::DidDiscoverNewEphemeronPairs(), cppgc::internal::anonymous_namespace{marker.cc}::DrainWorklistWithBytesAndTimeDeadline(), cppgc::internal::BasicMarkingState::ephemeron_pairs_for_processing_worklist(), cppgc::internal::MutatorMarkingState::FlushDiscoveredEphemeronPairs(), heap(), cppgc::Heap::kAtomic, cppgc::internal::anonymous_namespace{marker.cc}::kDefaultDeadlineCheckInterval, cppgc::internal::MarkingConfig::marking_type, cppgc::internal::MarkingStateBase::marking_worklist(), mutator_marking_state_, cppgc::internal::BasicMarkingState::previously_not_fully_constructed_worklist(), cppgc::internal::BasicMarkingState::ResetDidDiscoverNewEphemeronPairs(), cppgc::internal::MutatorMarkingState::retrace_marked_objects_worklist(), schedule(), cppgc::internal::HeapBase::stats_collector(), and cppgc::internal::BasicMarkingState::write_barrier_worklist().
Referenced by AdvanceMarkingWithLimits().
ReEnableConcurrentMarking()
void cppgc::internal::MarkerBase::ReEnableConcurrentMarking ()
Definition at line 292 of file marker.cc.
                                           {
  CHECK(is_marking_);
  if (config_.marking_type == MarkingConfig::MarkingType::kAtomic) {
    return;
  }
  CHECK_EQ(config_.marking_type, MarkingConfig::MarkingType::kIncremental);
  config_.marking_type = MarkingConfig::MarkingType::kIncrementalAndConcurrent;
  mutator_marking_state_.Publish();
  ConcurrentMarkerBase& marker = concurrent_marker();
  CHECK(!marker.IsActive());
  marker.Start();
  CHECK(marker.IsActive());
}
References CHECK, CHECK_EQ, concurrent_marker(), config_, is_marking_, cppgc::internal::ConcurrentMarkerBase::IsActive(), cppgc::Heap::kAtomic, cppgc::Heap::kIncremental, cppgc::Heap::kIncrementalAndConcurrent, cppgc::internal::MarkingConfig::marking_type, mutator_marking_state_, cppgc::internal::MutatorMarkingState::Publish(), and cppgc::internal::ConcurrentMarkerBase::Start().
schedule()
virtual heap::base::IncrementalMarkingSchedule& cppgc::internal::MarkerBase::schedule () [protected], [pure virtual]
Implemented in cppgc::internal::Marker, and v8::internal::UnifiedHeapMarker.
Referenced by AdvanceMarkingWithLimits(), ProcessWorklistsWithDeadline(), and StartMarking().
ScheduleIncrementalMarkingTask()
void cppgc::internal::MarkerBase::ScheduleIncrementalMarkingTask () [protected], [virtual]
Reimplemented in v8::internal::UnifiedHeapMarker.
Definition at line 545 of file marker.cc.
                                                {
  DCHECK(platform_);
  if (!foreground_task_runner_ || incremental_marking_handle_) return;
  incremental_marking_handle_ =
      IncrementalMarkingTask::Post(foreground_task_runner_.get(), this);
}
References DCHECK, foreground_task_runner_, incremental_marking_handle_, platform_, and cppgc::internal::MarkerBase::IncrementalMarkingTask::Post().
Referenced by AdvanceMarkingOnAllocationImpl(), AdvanceMarkingWithLimitsEpilogue(), and StartMarking().
SetMainThreadMarkingDisabledForTesting()
void cppgc::internal::MarkerBase::SetMainThreadMarkingDisabledForTesting (bool value)
Definition at line 773 of file marker.cc.
                                                                  {
  main_marking_disabled_for_testing_ = value;
}
References main_marking_disabled_for_testing_, and v8::internal::value.
Referenced by cppgc::testing::StandaloneTestingHeap::ToggleMainThreadMarking().
stack_visitor()
virtual heap::base::StackVisitor& cppgc::internal::MarkerBase::stack_visitor () [protected], [pure virtual]
Implemented in cppgc::internal::Marker, and v8::internal::UnifiedHeapMarker.
Referenced by VisitLocalRoots().
StartMarking()
void cppgc::internal::MarkerBase::StartMarking ()
Definition at line 211 of file marker.cc.
                              {
  DCHECK(!is_marking_);
  StatsCollector::EnabledScope stats_scope(
      heap().stats_collector(),
      config_.marking_type == MarkingConfig::MarkingType::kAtomic
          ? StatsCollector::kAtomicMark
          : StatsCollector::kIncrementalMark);
  heap().stats_collector()->NotifyMarkingStarted(
      config_.collection_type, config_.marking_type, config_.is_forced_gc);
  is_marking_ = true;
  if (EnterIncrementalMarkingIfNeeded(config_, heap())) {
    StatsCollector::EnabledScope inner_stats_scope(
        heap().stats_collector(), StatsCollector::kMarkIncrementalStart);
    // Performing incremental or concurrent marking.
    schedule().NotifyIncrementalMarkingStart();
    // Scanning the stack is expensive so we only do it at the atomic pause.
    VisitLocalRoots(StackState::kNoHeapPointers);
    ScheduleIncrementalMarkingTask();
    if (config_.marking_type ==
        MarkingConfig::MarkingType::kIncrementalAndConcurrent) {
      mutator_marking_state_.Publish();
      concurrent_marker().Start();
    }
    MarkStrongCrossThreadRoots();
    heap().stats_collector()->RegisterObserver(
        &incremental_marking_allocation_observer_);
  }
}
References cppgc::internal::MarkingConfig::collection_type, concurrent_marker(), config_, DCHECK, cppgc::internal::anonymous_namespace{marker.cc}::EnterIncrementalMarkingIfNeeded(), heap(), incremental_marking_allocation_observer_, cppgc::internal::MarkingConfig::is_forced_gc, is_marking_, cppgc::Heap::kAtomic, cppgc::Heap::kIncrementalAndConcurrent, cppgc::internal::MarkingConfig::marking_type, MarkStrongCrossThreadRoots(), mutator_marking_state_, heap::base::IncrementalMarkingSchedule::NotifyIncrementalMarkingStart(), cppgc::internal::StatsCollector::NotifyMarkingStarted(), cppgc::internal::MutatorMarkingState::Publish(), cppgc::internal::StatsCollector::RegisterObserver(), schedule(), ScheduleIncrementalMarkingTask(), cppgc::internal::ConcurrentMarkerBase::Start(), cppgc::internal::HeapBase::stats_collector(), and VisitLocalRoots().
To()
template<typename Class >
Class& cppgc::internal::MarkerBase::To () [inline]
Definition at line 71 of file marker.h.
              {
    return *static_cast<Class*>(this);
  }
VisitCrossThreadRoots()
void cppgc::internal::MarkerBase::VisitCrossThreadRoots () [protected]
Definition at line 522 of file marker.cc.
                                       {
  StatsCollector::DisabledScope inner_stats_scope(
      heap().stats_collector(),
      StatsCollector::kMarkVisitCrossThreadPersistents);
  CHECK_EQ(config_.marking_type, MarkingConfig::MarkingType::kAtomic);
  CHECK(!visited_cross_thread_persistents_in_atomic_pause_);
  // Lock guards against changes to {Weak}CrossThreadPersistent handles, that
  // may conflict with marking. E.g., a WeakCrossThreadPersistent may be
  // converted into a CrossThreadPersistent which requires that the handle
  // is either cleared or the object is retained.
  ProcessGlobalLock::Lock<ProcessGlobalLock::Reason::kForGC>();
  RootMarkingVisitor root_marking_visitor(mutator_marking_state_);
  heap().GetStrongCrossThreadPersistentRegion().Iterate(root_marking_visitor);
  visited_cross_thread_persistents_in_atomic_pause_ = true;
}
References CHECK, CHECK_EQ, config_, cppgc::internal::HeapBase::GetStrongCrossThreadPersistentRegion(), heap(), cppgc::internal::CrossThreadPersistentRegion::Iterate(), cppgc::Heap::kAtomic, cppgc::internal::MarkingConfig::marking_type, mutator_marking_state_, and visited_cross_thread_persistents_in_atomic_pause_.
Referenced by EnterProcessGlobalAtomicPause().
VisitLocalRoots()
void cppgc::internal::MarkerBase::VisitLocalRoots (StackState stack_state) [protected]
Definition at line 489 of file marker.cc.
                                                       {
  StatsCollector::EnabledScope stats_scope(heap().stats_collector(),
                                           StatsCollector::kMarkVisitRoots);
  // Reset LABs before scanning roots. LABs are cleared to allow
  // ObjectStartBitmap handling without considering LABs.
  heap().object_allocator().ResetLinearAllocationBuffers();
  {
    StatsCollector::DisabledScope inner_stats_scope(
        heap().stats_collector(), StatsCollector::kMarkVisitPersistents);
    RootMarkingVisitor root_marking_visitor(mutator_marking_state_);
    heap().GetStrongPersistentRegion().Iterate(root_marking_visitor);
  }
  if (stack_state != StackState::kNoHeapPointers) {
    StatsCollector::DisabledScope stack_stats_scope(
        heap().stats_collector(), StatsCollector::kMarkVisitStack);
    heap().stack()->SetMarkerIfNeededAndCallback([this]() {
      heap().stack()->IteratePointersUntilMarker(&stack_visitor());
    });
  }
#if defined(CPPGC_YOUNG_GENERATION)
  if (config_.collection_type == CollectionType::kMinor) {
    StatsCollector::EnabledScope inner_stats_scope(
        heap().stats_collector(), StatsCollector::kMarkVisitRememberedSets);
    heap().remembered_set().Visit(visitor(), conservative_visitor(),
                                  mutator_marking_state_);
  }
#endif // defined(CPPGC_YOUNG_GENERATION)
}
References cppgc::internal::MarkingConfig::collection_type, config_, conservative_visitor(), cppgc::internal::HeapBase::GetStrongPersistentRegion(), heap(), cppgc::internal::PersistentRegionBase::Iterate(), heap::base::Stack::IteratePointersUntilMarker(), cppgc::internal::kMinor, mutator_marking_state_, cppgc::internal::HeapBase::object_allocator(), cppgc::internal::ObjectAllocator::ResetLinearAllocationBuffers(), heap::base::Stack::SetMarkerIfNeededAndCallback(), cppgc::internal::HeapBase::stack(), stack_visitor(), and visitor().
Referenced by EnterAtomicPause(), and StartMarking().
Visitor()
cppgc::Visitor& cppgc::internal::MarkerBase::Visitor () [inline]
Definition at line 132 of file marker.h.
{ return visitor(); }
visitor()
virtual cppgc::Visitor& cppgc::internal::MarkerBase::visitor () [protected], [pure virtual]
Implemented in cppgc::internal::Marker, and v8::internal::UnifiedHeapMarker.
Referenced by VisitLocalRoots().
WaitForConcurrentMarkingForTesting()
void cppgc::internal::MarkerBase::WaitForConcurrentMarkingForTesting ()
Definition at line 777 of file marker.cc.
                                                    {
  concurrent_marker().Join();
}
References concurrent_marker(), and cppgc::internal::ConcurrentMarkerBase::Join().
WriteBarrierForObject()
template<MarkerBase::WriteBarrierType type>
void cppgc::internal::MarkerBase::WriteBarrierForObject (HeapObjectHeader & header) [inline]
Definition at line 242 of file marker.h.
                                                               {
  // The barrier optimizes for the bailout cases:
  // - kDijkstra: Marked objects.
  // - kSteele: Unmarked objects.
  switch (type) {
    case MarkerBase::WriteBarrierType::kDijkstra:
      if (!header.TryMarkAtomic()) {
        return;
      }
      break;
    case MarkerBase::WriteBarrierType::kSteele:
      if (!header.IsMarked<AccessMode::kAtomic>()) {
        return;
      }
      break;
  }
  // The barrier fired. Filter out in-construction objects here. This possibly
  // requires unmarking the object again.
  if (V8_UNLIKELY(header.IsInConstruction<AccessMode::kNonAtomic>())) {
    // In construction objects are traced only if they are unmarked. If marking
    // reaches this object again when it is fully constructed, it will re-mark
    // it and tracing it as a previously not fully constructed object would know
    // to bail out.
    header.Unmark<AccessMode::kAtomic>();
    mutator_marking_state_.not_fully_constructed_worklist()
        .Push<AccessMode::kAtomic>(&header);
    return;
  }
  switch (type) {
    case MarkerBase::WriteBarrierType::kDijkstra:
      mutator_marking_state_.write_barrier_worklist().Push(&header);
      break;
    case MarkerBase::WriteBarrierType::kSteele:
      mutator_marking_state_.retrace_marked_objects_worklist().Push(&header);
      break;
  }
}
References cppgc::internal::HeapObjectHeader::IsInConstruction(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kAtomic, kDijkstra, cppgc::internal::kNonAtomic, kSteele, mutator_marking_state_, cppgc::internal::MarkingStateBase::not_fully_constructed_worklist(), cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Push(), cppgc::internal::MutatorMarkingState::retrace_marked_objects_worklist(), cppgc::internal::HeapObjectHeader::TryMarkAtomic(), v8::internal::tracing::type, cppgc::internal::HeapObjectHeader::Unmark(), V8_UNLIKELY, and cppgc::internal::BasicMarkingState::write_barrier_worklist().
Member Data Documentation
config_
MarkingConfig cppgc::internal::MarkerBase::config_ = MarkingConfig::Default() [protected]
Definition at line 199 of file marker.h.
Referenced by AdvanceMarkingWithLimitsEpilogue(), EnterAtomicPause(), HandleNotFullyConstructedObjects(), IncrementalMarkingStep(), JoinConcurrentMarkingIfNeeded(), LeaveAtomicPause(), MarkerBase(), ProcessCrossThreadWeaknessIfNeeded(), ProcessWeakness(), ProcessWorklistsWithDeadline(), ReEnableConcurrentMarking(), StartMarking(), VisitCrossThreadRoots(), VisitLocalRoots(), and ~MarkerBase().
foreground_task_runner_
std::shared_ptr<cppgc::TaskRunner> cppgc::internal::MarkerBase::foreground_task_runner_ [protected]
Definition at line 201 of file marker.h.
Referenced by ScheduleIncrementalMarkingTask().
heap_
HeapBase& cppgc::internal::MarkerBase::heap_ [protected]
Definition at line 198 of file marker.h.
Referenced by AdvanceMarkingWithLimits(), ClearAllWorklistsForTesting(), MarkerBase(), ProcessCrossThreadWeaknessIfNeeded(), and ProcessWeakness().
incremental_marking_allocation_observer_
IncrementalMarkingAllocationObserver cppgc::internal::MarkerBase::incremental_marking_allocation_observer_ [protected]
Definition at line 203 of file marker.h.
Referenced by EnterAtomicPause(), and StartMarking().
incremental_marking_handle_
IncrementalMarkingTaskHandle cppgc::internal::MarkerBase::incremental_marking_handle_ [protected]
Definition at line 202 of file marker.h.
Referenced by EnterAtomicPause(), LeaveAtomicPause(), and ScheduleIncrementalMarkingTask().
is_marking_
bool cppgc::internal::MarkerBase::is_marking_ {false} [protected]
Definition at line 207 of file marker.h.
Referenced by FinishMarking(), LeaveAtomicPause(), ReEnableConcurrentMarking(), and StartMarking().
kMaximumIncrementalStepDuration
constexpr v8::base::TimeDelta cppgc::internal::MarkerBase::kMaximumIncrementalStepDuration [static], [constexpr], [protected]
Initial value:
=
      v8::base::TimeDelta::FromMilliseconds(2)
Definition at line 163 of file marker.h.
last_bytes_marked_
size_t cppgc::internal::MarkerBase::last_bytes_marked_ = 0 [protected]
Definition at line 206 of file marker.h.
Referenced by AdvanceMarkingWithLimits().
main_marking_disabled_for_testing_
bool cppgc::internal::MarkerBase::main_marking_disabled_for_testing_ {false} [protected]
Definition at line 208 of file marker.h.
Referenced by AdvanceMarkingWithLimits(), and SetMainThreadMarkingDisabledForTesting().
marking_worklists_
MarkingWorklists cppgc::internal::MarkerBase::marking_worklists_ [protected]
Definition at line 204 of file marker.h.
Referenced by ClearAllWorklistsForTesting(), v8::internal::UnifiedHeapMarker::GetMarkingWorklists(), JoinConcurrentMarkingIfNeeded(), ProcessWeakness(), and ~MarkerBase().
mutator_marking_state_
MutatorMarkingState cppgc::internal::MarkerBase::mutator_marking_state_ [protected]
Definition at line 205 of file marker.h.
Referenced by AdvanceMarkingWithLimits(), EnterAtomicPause(), FinishMarking(), HandleNotFullyConstructedObjects(), IncrementalMarkingStep(), LeaveAtomicPause(), MarkNotFullyConstructedObjects(), MarkStrongCrossThreadRoots(), ProcessCrossThreadWeaknessIfNeeded(), ProcessWeakness(), ProcessWorklistsWithDeadline(), ReEnableConcurrentMarking(), StartMarking(), VisitCrossThreadRoots(), VisitLocalRoots(), WriteBarrierForObject(), and ~MarkerBase().
platform_
cppgc::Platform* cppgc::internal::MarkerBase::platform_ [protected]
Definition at line 200 of file marker.h.
Referenced by ProcessWeakness(), and ScheduleIncrementalMarkingTask().
processed_cross_thread_weakness_
bool cppgc::internal::MarkerBase::processed_cross_thread_weakness_ {false} [protected]
Definition at line 210 of file marker.h.
Referenced by ProcessCrossThreadWeaknessIfNeeded().
visited_cross_thread_persistents_in_atomic_pause_
bool cppgc::internal::MarkerBase::visited_cross_thread_persistents_in_atomic_pause_ {false} [protected]
Definition at line 209 of file marker.h.
Referenced by ProcessCrossThreadWeaknessIfNeeded(), and VisitCrossThreadRoots().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/marker.h
/mnt/V8SourceCode/src/heap/cppgc/marker.cc