v8::internal::StoreDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_PARAMETER_TYPES (MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::TaggedSigned()) static const expr inline Register ReceiverRegister()
Static Public Member Functions
static constexpr Register NameRegister ()
static constexpr Register ValueRegister ()
static constexpr Register SlotRegister ()
static constexpr auto registers ()
Additional Inherited Members
Detailed Description
Definition at line 1164 of file interface-descriptors.h.
Member Function Documentation
DEFINE_PARAMETER_TYPES()
v8::internal::StoreDescriptor::DEFINE_PARAMETER_TYPES (MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::TaggedSigned()) const
NameRegister()
constexpr Register v8::internal::StoreDescriptor::NameRegister () [inline], [static], [constexpr]
Definition at line 125 of file interface-descriptors-riscv-inl.h.
{ return a2; }
Referenced by registers(), v8::internal::StoreTransitionDescriptor::registers(), v8::internal::StoreWithVectorDescriptor::registers(), and v8::internal::DefineKeyedOwnDescriptor::registers().
registers()
constexpr auto v8::internal::StoreDescriptor::registers () [static], [constexpr]
Definition at line 415 of file interface-descriptors-inl.h.
                                          {
  return RegisterArray(ReceiverRegister(), NameRegister(), ValueRegister(),
                       SlotRegister());
}
References NameRegister(), v8::internal::RegisterArray(), SlotRegister(), and ValueRegister().
SlotRegister()
constexpr Register v8::internal::StoreDescriptor::SlotRegister () [inline], [static], [constexpr]
Definition at line 129 of file interface-descriptors-riscv-inl.h.
{ return a4; }
Referenced by registers(), v8::internal::StoreTransitionDescriptor::registers(), v8::internal::StoreWithVectorDescriptor::registers(), and v8::internal::DefineKeyedOwnDescriptor::registers().
ValueRegister()
constexpr Register v8::internal::StoreDescriptor::ValueRegister () [inline], [static], [constexpr]
Definition at line 127 of file interface-descriptors-riscv-inl.h.
{ return a0; }
Referenced by registers(), v8::internal::StoreTransitionDescriptor::registers(), v8::internal::StoreWithVectorDescriptor::registers(), and v8::internal::DefineKeyedOwnDescriptor::registers().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h
/mnt/V8SourceCode/src/codegen/riscv/interface-descriptors-riscv-inl.h