v8::internal::compiler::CheckParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
CheckParameters (const FeedbackSource &feedback)
FeedbackSource const & feedback () const
Private Attributes
FeedbackSource feedback_
Detailed Description
Definition at line 268 of file simplified-operator.h.
Constructor & Destructor Documentation
CheckParameters()
v8::internal::compiler::CheckParameters::CheckParameters (const FeedbackSource & feedback) [inline], [explicit]
Definition at line 270 of file simplified-operator.h.
      : feedback_(feedback) {}
Member Function Documentation
feedback()
FeedbackSource const& v8::internal::compiler::CheckParameters::feedback () const [inline]
Definition at line 273 of file simplified-operator.h.
{ return feedback_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), v8::internal::compiler::TypedOptimization::ReduceCheckBounds(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), and v8::internal::compiler::RepresentationSelector::VisitNode().
Member Data Documentation
feedback_
FeedbackSource v8::internal::compiler::CheckParameters::feedback_ [private]
Definition at line 276 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h