v8::CompiledWasmModule Class Reference
#include <v8-wasm.h>
Public Member Functions
OwnedBuffer Serialize ()
Serialize the compiled module.
MemorySpan< const uint8_t > GetWireBytesRef ()
Get the (wasm-encoded) wire bytes that were used to compile this module.
const std::string & source_url () const
Private Member Functions
CompiledWasmModule (std::shared_ptr< internal::wasm::NativeModule >, const char *source_url, size_t url_length)
Private Attributes
const std::shared_ptr< internal::wasm::NativeModule > native_module_
const std::string source_url_
Friends
class WasmModuleObject
class WasmStreaming
Detailed Description
Definition at line 43 of file v8-wasm.h.
Constructor & Destructor Documentation
CompiledWasmModule()
v8::CompiledWasmModule::CompiledWasmModule (std::shared_ptr< internal::wasm::NativeModule > native_module, const char * source_url, size_t url_length) [explicit], [private]
Definition at line 8774 of file api.cc.
    : native_module_(std::move(native_module)),
      source_url_(source_url, url_length) {
  CHECK_NOT_NULL(native_module_);
}
References CHECK_NOT_NULL, and native_module_.
Member Function Documentation
GetWireBytesRef()
MemorySpan< const uint8_t > v8::CompiledWasmModule::GetWireBytesRef ()
Get the (wasm-encoded) wire bytes that were used to compile this module.
Definition at line 8797 of file api.cc.
                                                              {
#if V8_ENABLE_WEBASSEMBLY
  base::Vector<const uint8_t> bytes_vec = native_module_->wire_bytes();
  return {bytes_vec.begin(), bytes_vec.size()};
#else
  UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::base::Vector< T >::begin(), native_module_, v8::base::Vector< T >::size(), and UNREACHABLE.
Serialize()
OwnedBuffer v8::CompiledWasmModule::Serialize ()
Serialize the compiled module.
The serialized data does not include the wire bytes.
Definition at line 8782 of file api.cc.
                                          {
#if V8_ENABLE_WEBASSEMBLY
  TRACE_EVENT0("v8.wasm", "wasm.SerializeModule");
  i::wasm::WasmSerializer wasm_serializer(native_module_.get());
  size_t buffer_size = wasm_serializer.GetSerializedNativeModuleSize();
  std::unique_ptr<uint8_t[]> buffer(new uint8_t[buffer_size]);
  if (!wasm_serializer.SerializeNativeModule({buffer.get(), buffer_size})) {
    return {};
  }
  return {std::move(buffer), buffer_size};
#else
  UNREACHABLE();
#endif // V8_ENABLE_WEBASSEMBLY
}
References native_module_, TRACE_EVENT0, and UNREACHABLE.
source_url()
const std::string& v8::CompiledWasmModule::source_url () const [inline]
Definition at line 56 of file v8-wasm.h.
{ return source_url_; }
Referenced by v8::WasmModuleObject::FromCompiledModule().
Friends And Related Function Documentation
WasmModuleObject
friend class WasmModuleObject [friend]
Definition at line 59 of file v8-wasm.h.
WasmStreaming
friend class WasmStreaming [friend]
Definition at line 60 of file v8-wasm.h.
Member Data Documentation
native_module_
const std::shared_ptr<internal::wasm::NativeModule> v8::CompiledWasmModule::native_module_ [private]
Definition at line 65 of file v8-wasm.h.
Referenced by CompiledWasmModule(), v8::WasmModuleObject::FromCompiledModule(), GetWireBytesRef(), and Serialize().
source_url_
const std::string v8::CompiledWasmModule::source_url_ [private]
Definition at line 66 of file v8-wasm.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-wasm.h
/mnt/V8SourceCode/src/api/api.cc