v8::internal::CharacterRange Class Reference
#include <regexp-ast.h>
Public Member Functions
CharacterRange ()=default
CharacterRange (void *null)
bool Contains (base::uc32 i) const
base::uc32 from () const
base::uc32 to () const
bool IsEverything (base::uc32 max) const
bool IsSingleton () const
Static Public Member Functions
static CharacterRange Singleton (base::uc32 value)
static CharacterRange Range (base::uc32 from, base::uc32 to)
static CharacterRange Everything ()
static ZoneList< CharacterRange > * List (Zone *zone, CharacterRange range)
static V8_EXPORT_PRIVATE void AddClassEscape (StandardCharacterSet standard_character_set, ZoneList< CharacterRange > *ranges, bool add_unicode_case_equivalents, Zone *zone)
static V8_EXPORT_PRIVATE void AddCaseEquivalents (Isolate *isolate, Zone *zone, ZoneList< CharacterRange > *ranges, bool is_one_byte)
static void AddUnicodeCaseEquivalents (ZoneList< CharacterRange > *ranges, Zone *zone)
static V8_EXPORT_PRIVATE bool IsCanonical (const ZoneList< CharacterRange > *ranges)
static void Canonicalize (ZoneList< CharacterRange > *ranges)
static void Negate (const ZoneList< CharacterRange > *src, ZoneList< CharacterRange > *dst, Zone *zone)
static void Intersect (const ZoneList< CharacterRange > *lhs, const ZoneList< CharacterRange > *rhs, ZoneList< CharacterRange > *dst, Zone *zone)
static void Subtract (const ZoneList< CharacterRange > *src, const ZoneList< CharacterRange > *to_remove, ZoneList< CharacterRange > *dst, Zone *zone)
static void ClampToOneByte (ZoneList< CharacterRange > *ranges)
static bool Equals (const ZoneList< CharacterRange > *lhs, const ZoneList< CharacterRange > *rhs)
Private Member Functions
CharacterRange (base::uc32 from, base::uc32 to)
Private Attributes
base::uc32 from_ = 0
base::uc32 to_ = 0
Static Private Attributes
static constexpr int kMaxCodePoint = 0x10ffff
Detailed Description
Definition at line 96 of file regexp-ast.h.
Constructor & Destructor Documentation
CharacterRange() [1/3]
v8::internal::CharacterRange::CharacterRange () [default]
Referenced by Everything(), Range(), and Singleton().
CharacterRange() [2/3]
v8::internal::CharacterRange::CharacterRange (void * null) [inline]
Definition at line 100 of file regexp-ast.h.
{ DCHECK_NULL(null); } // NOLINT
References DCHECK_NULL.
CharacterRange() [3/3]
v8::internal::CharacterRange::CharacterRange (base::uc32 from, base::uc32 to) [inline], [private]
Definition at line 172 of file regexp-ast.h.
: from_(from), to_(to) {}
Member Function Documentation
AddCaseEquivalents()
void v8::internal::CharacterRange::AddCaseEquivalents (Isolate * isolate, Zone * zone, ZoneList< CharacterRange > * ranges, bool is_one_byte) [static]
Definition at line 1493 of file regexp-compiler-tonode.cc.
                                                          {
  CharacterRange::Canonicalize(ranges);
  int range_count = ranges->length();
#ifdef V8_INTL_SUPPORT
  icu::UnicodeSet others;
  for (int i = 0; i < range_count; i++) {
    CharacterRange range = ranges->at(i);
    base::uc32 from = range.from();
    if (from > kMaxUtf16CodeUnit) continue;
    base::uc32 to = std::min({range.to(), kMaxUtf16CodeUnitU});
    // Nothing to be done for surrogates.
    if (from >= kLeadSurrogateStart && to <= kTrailSurrogateEnd) continue;
    if (is_one_byte && !RangeContainsLatin1Equivalents(range)) {
      if (from > String::kMaxOneByteCharCode) continue;
      if (to > String::kMaxOneByteCharCode) to = String::kMaxOneByteCharCode;
    }
    others.add(from, to);
  }
  // Compute the set of additional characters that should be added,
  // using UnicodeSet::closeOver. ECMA 262 defines slightly different
  // case-folding rules than Unicode, so some characters that are
  // added by closeOver do not match anything other than themselves in
  // JS. For example, 'ſ' (U+017F LATIN SMALL LETTER LONG S) is the
  // same case-insensitive character as 's' or 'S' according to
  // Unicode, but does not match any other character in JS. To handle
  // this case, we add such characters to the IgnoreSet and filter
  // them out. We filter twice: once before calling closeOver (to
  // prevent 'ſ' from adding 's'), and once after calling closeOver
  // (to prevent 's' from adding 'ſ'). See regexp/special-case.h for
  // more information.
  icu::UnicodeSet already_added(others);
  others.removeAll(RegExpCaseFolding::IgnoreSet());
  others.closeOver(USET_CASE_INSENSITIVE);
  others.removeAll(RegExpCaseFolding::IgnoreSet());
  others.removeAll(already_added);
  // Add others to the ranges
  for (int32_t i = 0; i < others.getRangeCount(); i++) {
    UChar32 from = others.getRangeStart(i);
    UChar32 to = others.getRangeEnd(i);
    if (from == to) {
      ranges->Add(CharacterRange::Singleton(from), zone);
    } else {
      ranges->Add(CharacterRange::Range(from, to), zone);
    }
  }
#else
  for (int i = 0; i < range_count; i++) {
    CharacterRange range = ranges->at(i);
    base::uc32 bottom = range.from();
    if (bottom > kMaxUtf16CodeUnit) continue;
    base::uc32 top = std::min({range.to(), kMaxUtf16CodeUnitU});
    // Nothing to be done for surrogates.
    if (bottom >= kLeadSurrogateStart && top <= kTrailSurrogateEnd) continue;
    if (is_one_byte && !RangeContainsLatin1Equivalents(range)) {
      if (bottom > String::kMaxOneByteCharCode) continue;
      if (top > String::kMaxOneByteCharCode) top = String::kMaxOneByteCharCode;
    }
    unibrow::uchar chars[unibrow::Ecma262UnCanonicalize::kMaxWidth];
    if (top == bottom) {
      // If this is a singleton we just expand the one character.
      int length = isolate->jsregexp_uncanonicalize()->get(bottom, '\0', chars);
      for (int j = 0; j < length; j++) {
        base::uc32 chr = chars[j];
        if (chr != bottom) {
          ranges->Add(CharacterRange::Singleton(chars[j]), zone);
        }
      }
    } else {
      // If this is a range we expand the characters block by block, expanding
      // contiguous subranges (blocks) one at a time. The approach is as
      // follows. For a given start character we look up the remainder of the
      // block that contains it (represented by the end point), for instance we
      // find 'z' if the character is 'c'. A block is characterized by the
      // property that all characters uncanonicalize in the same way, except
      // that each entry in the result is incremented by the distance from the
      // first element. So a-z is a block because 'a' uncanonicalizes to ['a',
      // 'A'] and the k'th letter uncanonicalizes to ['a' + k, 'A' + k]. Once
      // we've found the end point we look up its uncanonicalization and
      // produce a range for each element. For instance for [c-f] we look up
      // ['z', 'Z'] and produce [c-f] and [C-F]. We then only add a range if
      // it is not already contained in the input, so [c-f] will be skipped but
      // [C-F] will be added. If this range is not completely contained in a
      // block we do this for all the blocks covered by the range (handling
      // characters that is not in a block as a "singleton block").
      unibrow::uchar equivalents[unibrow::Ecma262UnCanonicalize::kMaxWidth];
      base::uc32 pos = bottom;
      while (pos <= top) {
        int length =
            isolate->jsregexp_canonrange()->get(pos, '\0', equivalents);
        base::uc32 block_end;
        if (length == 0) {
          block_end = pos;
        } else {
          DCHECK_EQ(1, length);
          block_end = equivalents[0];
        }
        int end = (block_end > top) ? top : block_end;
        length = isolate->jsregexp_uncanonicalize()->get(block_end, '\0',
                                                         equivalents);
        for (int j = 0; j < length; j++) {
          base::uc32 c = equivalents[j];
          base::uc32 range_from = c - (block_end - pos);
          base::uc32 range_to = c - (block_end - end);
          if (!(bottom <= range_from && range_to <= top)) {
            ranges->Add(CharacterRange::Range(range_from, range_to), zone);
          }
        }
        pos = end + 1;
      }
    }
  }
#endif // V8_INTL_SUPPORT
}
References v8::internal::ZoneList< T >::Add(), v8::internal::ZoneList< T >::at(), Canonicalize(), DCHECK_EQ, v8::internal::compiler::end(), from(), unibrow::Mapping< T, size >::get(), v8::internal::Isolate::jsregexp_canonrange(), v8::internal::Isolate::jsregexp_uncanonicalize(), v8::internal::kLeadSurrogateStart, v8::internal::String::kMaxOneByteCharCode, v8::internal::kMaxUtf16CodeUnit, v8::internal::kMaxUtf16CodeUnitU, unibrow::Ecma262UnCanonicalize::kMaxWidth, v8::internal::kTrailSurrogateEnd, v8::internal::length, v8::internal::ZoneList< T >::length(), Range(), v8::internal::RangeContainsLatin1Equivalents(), Singleton(), and to().
Referenced by v8::internal::TextNode::MakeCaseIndependent().
AddClassEscape()
void v8::internal::CharacterRange::AddClassEscape (StandardCharacterSet standard_character_set, ZoneList< CharacterRange > * ranges, bool add_unicode_case_equivalents, Zone * zone) [static]
Definition at line 1430 of file regexp-compiler-tonode.cc.
                                                {
  if (add_unicode_case_equivalents &&
      (standard_character_set == StandardCharacterSet::kWord ||
       standard_character_set == StandardCharacterSet::kNotWord)) {
    // See #sec-runtime-semantics-wordcharacters-abstract-operation
    // In case of unicode and ignore_case, we need to create the closure over
    // case equivalent characters before negating.
    ZoneList<CharacterRange>* new_ranges =
        zone->New<ZoneList<CharacterRange>>(2, zone);
    AddClass(kWordRanges, kWordRangeCount, new_ranges, zone);
    AddUnicodeCaseEquivalents(new_ranges, zone);
    if (standard_character_set == StandardCharacterSet::kNotWord) {
      ZoneList<CharacterRange>* negated =
          zone->New<ZoneList<CharacterRange>>(2, zone);
      CharacterRange::Negate(new_ranges, negated, zone);
      new_ranges = negated;
    }
    ranges->AddAll(*new_ranges, zone);
    return;
  }
  switch (standard_character_set) {
    case StandardCharacterSet::kWhitespace:
      AddClass(kSpaceRanges, kSpaceRangeCount, ranges, zone);
      break;
    case StandardCharacterSet::kNotWhitespace:
      AddClassNegated(kSpaceRanges, kSpaceRangeCount, ranges, zone);
      break;
    case StandardCharacterSet::kWord:
      AddClass(kWordRanges, kWordRangeCount, ranges, zone);
      break;
    case StandardCharacterSet::kNotWord:
      AddClassNegated(kWordRanges, kWordRangeCount, ranges, zone);
      break;
    case StandardCharacterSet::kDigit:
      AddClass(kDigitRanges, kDigitRangeCount, ranges, zone);
      break;
    case StandardCharacterSet::kNotDigit:
      AddClassNegated(kDigitRanges, kDigitRangeCount, ranges, zone);
      break;
    // This is the set of characters matched by the $ and ^ symbols
    // in multiline mode.
    case StandardCharacterSet::kLineTerminator:
      AddClass(kLineTerminatorRanges, kLineTerminatorRangeCount, ranges, zone);
      break;
    case StandardCharacterSet::kNotLineTerminator:
      AddClassNegated(kLineTerminatorRanges, kLineTerminatorRangeCount, ranges,
                      zone);
      break;
    // This is not a character range as defined by the spec but a
    // convenient shorthand for a character class that matches any
    // character.
    case StandardCharacterSet::kEverything:
      ranges->Add(CharacterRange::Everything(), zone);
      break;
  }
}
References v8::internal::ZoneList< T >::Add(), v8::internal::ZoneList< T >::AddAll(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddClass(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddClassNegated(), Everything(), v8::internal::kDigit, v8::internal::regexp_compiler_constants::kDigitRangeCount, v8::internal::regexp_compiler_constants::kDigitRanges, v8::internal::kEverything, v8::internal::kLineTerminator, v8::internal::regexp_compiler_constants::kLineTerminatorRangeCount, v8::internal::regexp_compiler_constants::kLineTerminatorRanges, v8::internal::kNotDigit, v8::internal::kNotLineTerminator, v8::internal::kNotWhitespace, v8::internal::kNotWord, v8::internal::regexp_compiler_constants::kSpaceRangeCount, v8::internal::regexp_compiler_constants::kSpaceRanges, v8::internal::kWhitespace, v8::internal::kWord, v8::internal::regexp_compiler_constants::kWordRangeCount, v8::internal::regexp_compiler_constants::kWordRanges, Negate(), and v8::internal::Zone::New().
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::BoundaryAssertionAsLookaround(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseDisjunction(), v8::internal::CharacterSet::ranges(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::TryParseCharacterClassEscape().
AddUnicodeCaseEquivalents()
void v8::internal::CharacterRange::AddUnicodeCaseEquivalents (ZoneList< CharacterRange > * ranges, Zone * zone) [static]
Definition at line 427 of file regexp-compiler-tonode.cc.
                                                           {
#ifdef V8_INTL_SUPPORT
  DCHECK(IsCanonical(ranges));
  // Micro-optimization to avoid passing large ranges to UnicodeSet::closeOver.
  // See also https://crbug.com/v8/6727.
  // TODO(jgruber): This only covers the special case of the {0,0x10FFFF} range,
  // which we use frequently internally. But large ranges can also easily be
  // created by the user. We might want to have a more general caching mechanism
  // for such ranges.
  if (ranges->length() == 1 && ranges->at(0).IsEverything(kNonBmpEnd)) return;
  // Use ICU to compute the case fold closure over the ranges.
  icu::UnicodeSet set;
  for (int i = 0; i < ranges->length(); i++) {
    set.add(ranges->at(i).from(), ranges->at(i).to());
  }
  // Clear the ranges list without freeing the backing store.
  ranges->Rewind(0);
  set.closeOver(USET_SIMPLE_CASE_INSENSITIVE);
  for (int i = 0; i < set.getRangeCount(); i++) {
    ranges->Add(Range(set.getRangeStart(i), set.getRangeEnd(i)), zone);
  }
  // No errors and everything we collected have been ranges.
  Canonicalize(ranges);
#endif // V8_INTL_SUPPORT
}
References v8::internal::ZoneList< T >::Add(), v8::internal::ZoneList< T >::at(), v8::internal::DCHECK(), v8::internal::kNonBmpEnd, v8::internal::ZoneList< T >::length(), v8::internal::compiler::turboshaft::Range(), and v8::internal::ZoneList< T >::Rewind().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::AddMaybeSimpleCaseFoldedRange().
Canonicalize()
void v8::internal::CharacterRange::Canonicalize (ZoneList< CharacterRange > * ranges) [static]
Definition at line 1716 of file regexp-compiler-tonode.cc.
                                                                            {
  if (character_ranges->length() <= 1) return;
  // Check whether ranges are already canonical (increasing, non-overlapping,
  // non-adjacent).
  int n = character_ranges->length();
  base::uc32 max = character_ranges->at(0).to();
  int i = 1;
  while (i < n) {
    CharacterRange current = character_ranges->at(i);
    if (current.from() <= max + 1) {
      break;
    }
    max = current.to();
    i++;
  }
  // Canonical until the i'th range. If that's all of them, we are done.
  if (i == n) return;
  // The ranges at index i and forward are not canonicalized. Make them so by
  // doing the equivalent of insertion sort (inserting each into the previous
  // list, in order).
  // Notice that inserting a range can reduce the number of ranges in the
  // result due to combining of adjacent and overlapping ranges.
  int read = i; // Range to insert.
  int num_canonical = i; // Length of canonicalized part of list.
  do {
    num_canonical = InsertRangeInCanonicalList(character_ranges, num_canonical,
                                               character_ranges->at(read));
    read++;
  } while (read < n);
  character_ranges->Rewind(num_canonical);
  DCHECK(CharacterRange::IsCanonical(character_ranges));
}
References v8::internal::ZoneList< T >::at(), v8::internal::DCHECK(), from(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::InsertRangeInCanonicalList(), IsCanonical(), v8::internal::ZoneList< T >::length(), v8::internal::ZoneList< T >::Rewind(), and to().
Referenced by AddCaseEquivalents(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::AddMaybeSimpleCaseFoldedRange(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs(), v8::internal::CharacterSet::Canonicalize(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileCharacterRanges(), v8::internal::RegExpClassSetExpression::ComputeExpression(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::TextNode::FilterOneByte(), v8::internal::TextNode::GetSuccessorOfOmnivorousTextNode(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::NeedsDesugaringForUnicode(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassStringDisjunction(), and v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::ToCanonicalZoneList().
ClampToOneByte()
void v8::internal::CharacterRange::ClampToOneByte (ZoneList< CharacterRange > * ranges) [static]
Definition at line 1901 of file regexp-compiler-tonode.cc.
                                                                    {
  DCHECK(IsCanonical(ranges));
  // Drop all ranges that don't contain one-byte code units, and clamp the last
  // range s.t. it likewise only contains one-byte code units. Note this relies
  // on `ranges` being canonicalized, i.e. sorted and non-overlapping.
  static constexpr base::uc32 max_char = String::kMaxOneByteCharCodeU;
  int n = ranges->length();
  for (; n > 0; n--) {
    CharacterRange& r = ranges->at(n - 1);
    if (r.from() <= max_char) {
      r.to_ = std::min(r.to_, max_char);
      break;
    }
  }
  ranges->Rewind(n);
}
References v8::internal::ZoneList< T >::at(), v8::internal::DCHECK(), from(), v8::internal::String::kMaxOneByteCharCodeU, v8::internal::ZoneList< T >::length(), v8::internal::ZoneList< T >::Rewind(), and to_.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges().
Contains()
bool v8::internal::CharacterRange::Contains (base::uc32 i) const [inline]
Definition at line 139 of file regexp-ast.h.
{ return from_ <= i && i <= to_; }
References from_, and to_.
Referenced by v8::internal::RangeContainsLatin1Equivalents().
Equals()
bool v8::internal::CharacterRange::Equals (const ZoneList< CharacterRange > * lhs, const ZoneList< CharacterRange > * rhs) [static]
Definition at line 1922 of file regexp-compiler-tonode.cc.
                                                                 {
  DCHECK(IsCanonical(lhs));
  DCHECK(IsCanonical(rhs));
  if (lhs->length() != rhs->length()) return false;
  for (int i = 0; i < lhs->length(); i++) {
    if (lhs->at(i) != rhs->at(i)) return false;
  }
  return true;
}
References v8::internal::ZoneList< T >::at(), v8::internal::DCHECK(), and v8::internal::ZoneList< T >::length().
Everything()
static CharacterRange v8::internal::CharacterRange::Everything () [inline], [static]
Definition at line 110 of file regexp-ast.h.
                                            {
    return CharacterRange(0, kMaxCodePoint);
  }
References CharacterRange(), and kMaxCodePoint.
Referenced by AddClassEscape(), and v8::internal::RegExpClassRanges::RegExpClassRanges().
from()
base::uc32 v8::internal::CharacterRange::from () const [inline]
Definition at line 140 of file regexp-ast.h.
{ return from_; }
References from_.
Referenced by AddCaseEquivalents(), v8::internal::UnicodeRangeSplitter::AddRange(), Canonicalize(), ClampToOneByte(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareInverseRanges(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareRanges(), v8::internal::TextNode::CreateForSurrogatePair(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::Equals(), v8::internal::TextNode::FillInBMInfo(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::Hash(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::InsertRangeInCanonicalList(), IsCanonical(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::MakeRangeArray(), Negate(), v8::internal::operator==(), Range(), Subtract(), and v8::internal::anonymous_namespace{regexp-ast.cc}::RegExpUnparser::VisitCharacterRange().
Intersect()
void v8::internal::CharacterRange::Intersect (const ZoneList< CharacterRange > * lhs, const ZoneList< CharacterRange > * rhs, ZoneList< CharacterRange > * dst, Zone * zone) [static]
Definition at line 1776 of file regexp-compiler-tonode.cc.
                                           {
  DCHECK(CharacterRange::IsCanonical(lhs));
  DCHECK(CharacterRange::IsCanonical(rhs));
  DCHECK_EQ(0, intersection->length());
  int lhs_index = 0;
  int rhs_index = 0;
  while (lhs_index < lhs->length() && rhs_index < rhs->length()) {
    // Skip non-overlapping ranges.
    if (lhs->at(lhs_index).to() < rhs->at(rhs_index).from()) {
      lhs_index++;
      continue;
    }
    if (rhs->at(rhs_index).to() < lhs->at(lhs_index).from()) {
      rhs_index++;
      continue;
    }
    base::uc32 from =
        std::max(lhs->at(lhs_index).from(), rhs->at(rhs_index).from());
    base::uc32 to = std::min(lhs->at(lhs_index).to(), rhs->at(rhs_index).to());
    intersection->Add(CharacterRange::Range(from, to), zone);
    if (to == lhs->at(lhs_index).to()) {
      lhs_index++;
    } else {
      rhs_index++;
    }
  }
  DCHECK(IsCanonical(intersection));
}
References v8::internal::ZoneList< T >::Add(), v8::internal::ZoneList< T >::at(), v8::internal::DCHECK(), DCHECK_EQ, IsCanonical(), v8::internal::length, v8::internal::ZoneList< T >::length(), and Range().
Referenced by v8::internal::RegExpClassSetOperand::Intersect().
IsCanonical()
bool v8::internal::CharacterRange::IsCanonical (const ZoneList< CharacterRange > * ranges) [static]
Definition at line 1611 of file regexp-compiler-tonode.cc.
                                                                       {
  DCHECK_NOT_NULL(ranges);
  int n = ranges->length();
  if (n <= 1) return true;
  base::uc32 max = ranges->at(0).to();
  for (int i = 1; i < n; i++) {
    CharacterRange next_range = ranges->at(i);
    if (next_range.from() <= max + 1) return false;
    max = next_range.to();
  }
  return true;
}
References v8::internal::ZoneList< T >::at(), DCHECK_NOT_NULL, from(), v8::internal::ZoneList< T >::length(), and to().
Referenced by Canonicalize(), Intersect(), Negate(), and Subtract().
IsEverything()
bool v8::internal::CharacterRange::IsEverything (base::uc32 max) const [inline]
Definition at line 142 of file regexp-ast.h.
{ return from_ == 0 && to_ >= max; }
References from_, and to_.
IsSingleton()
bool v8::internal::CharacterRange::IsSingleton () const [inline]
Definition at line 143 of file regexp-ast.h.
{ return from_ == to_; }
References from_, and to_.
Referenced by v8::internal::anonymous_namespace{regexp-ast.cc}::RegExpUnparser::VisitCharacterRange().
List()
static ZoneList<CharacterRange>* v8::internal::CharacterRange::List (Zone * zone, CharacterRange range) [inline], [static]
Definition at line 114 of file regexp-ast.h.
                                                                     {
    ZoneList<CharacterRange>* list =
        zone->New<ZoneList<CharacterRange>>(1, zone);
    list->Add(range, zone);
    return list;
  }
References v8::internal::ZoneList< T >::Add(), and v8::internal::Zone::New().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddClassRangesForDesugaring(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddLoneLeadSurrogates(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddLoneTrailSurrogates(), v8::internal::TextNode::CreateForSurrogatePair(), v8::internal::RegExpCompiler::OptionallyStepBackToLeadSurrogate(), and v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::UnanchoredAdvance().
Negate()
void v8::internal::CharacterRange::Negate (const ZoneList< CharacterRange > * src, ZoneList< CharacterRange > * dst, Zone * zone) [static]
Definition at line 1752 of file regexp-compiler-tonode.cc.
                                        {
  DCHECK(CharacterRange::IsCanonical(ranges));
  DCHECK_EQ(0, negated_ranges->length());
  int range_count = ranges->length();
  base::uc32 from = 0;
  int i = 0;
  if (range_count > 0 && ranges->at(0).from() == 0) {
    from = ranges->at(0).to() + 1;
    i = 1;
  }
  while (i < range_count) {
    CharacterRange range = ranges->at(i);
    negated_ranges->Add(CharacterRange::Range(from, range.from() - 1), zone);
    from = range.to() + 1;
    i++;
  }
  if (from < kMaxCodePoint) {
    negated_ranges->Add(CharacterRange::Range(from, kMaxCodePoint), zone);
  }
}
References v8::internal::ZoneList< T >::Add(), v8::internal::ZoneList< T >::at(), v8::internal::DCHECK(), DCHECK_EQ, from(), IsCanonical(), v8::internal::kMaxCodePoint, v8::internal::ZoneList< T >::length(), Range(), and to().
Referenced by AddClassEscape(), v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileCharacterRanges(), v8::internal::RegExpClassSetExpression::ComputeExpression(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::NeedsDesugaringForUnicode().
Range()
static CharacterRange v8::internal::CharacterRange::Range (base::uc32 from, base::uc32 to) [inline], [static]
Definition at line 105 of file regexp-ast.h.
                                                                 {
    DCHECK(0 <= from && to <= kMaxCodePoint);
    DCHECK(static_cast<uint32_t>(from) <= static_cast<uint32_t>(to));
    return CharacterRange(from, to);
  }
References CharacterRange(), v8::internal::DCHECK(), from(), kMaxCodePoint, and to().
Referenced by AddCaseEquivalents(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddClass(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddClassNegated(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddLoneLeadSurrogates(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddLoneTrailSurrogates(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs(), v8::internal::UnicodeRangeSplitter::AddRange(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::InsertRangeInCanonicalList(), Intersect(), Negate(), v8::internal::RegExpCompiler::OptionallyStepBackToLeadSurrogate(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassRanges(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassUnion(), Subtract(), and v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::UnanchoredAdvance().
Singleton()
static CharacterRange v8::internal::CharacterRange::Singleton (base::uc32 value) [inline], [static]
Definition at line 102 of file regexp-ast.h.
                                                         {
    return CharacterRange(value, value);
  }
References CharacterRange(), and v8::internal::value.
Referenced by AddCaseEquivalents(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddClassRangesForDesugaring(), v8::internal::anonymous_namespace{regexp-parser.cc}::anonymous_namespace{regexp-parser.cc}::AddClassString(), v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseCharacterClass(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassRanges(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassSetOperand(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassUnion().
Subtract()
void v8::internal::CharacterRange::Subtract (const ZoneList< CharacterRange > * src, const ZoneList< CharacterRange > * to_remove, ZoneList< CharacterRange > * dst, Zone * zone) [static]
Definition at line 1829 of file regexp-compiler-tonode.cc.
                                                                            {
  DCHECK(CharacterRange::IsCanonical(src));
  DCHECK(CharacterRange::IsCanonical(to_remove));
  DCHECK_EQ(0, result->length());
  if (src->is_empty()) return;
  int src_index = 0;
  int to_remove_index = 0;
  base::uc32 from = src->at(src_index).from();
  base::uc32 to = src->at(src_index).to();
  while (src_index < src->length() && to_remove_index < to_remove->length()) {
    CharacterRange remove_range = to_remove->at(to_remove_index);
    if (remove_range.to() < from) {
      // (a) Non-overlapping case, ignore current to_remove range.
      // |-------|
      // |-------|
      to_remove_index++;
    } else if (to < remove_range.from()) {
      // (b) Non-overlapping case, add full current range to result.
      // |-------|
      // |-------|
      result->Add(CharacterRange::Range(from, to), zone);
      SafeAdvanceRange(src, &src_index, &from, &to);
    } else if (from >= remove_range.from() && to <= remove_range.to()) {
      // (c) Current to_remove range fully covers current range.
      // |---|
      // |-------|
      SafeAdvanceRange(src, &src_index, &from, &to);
    } else if (from < remove_range.from() && to > remove_range.to()) {
      // (d) Split current range.
      // |-------|
      // |---|
      result->Add(CharacterRange::Range(from, remove_range.from() - 1), zone);
      from = remove_range.to() + 1;
      to_remove_index++;
    } else if (from < remove_range.from()) {
      // (e) End current range.
      // |-------|
      // |-------|
      to = remove_range.from() - 1;
      result->Add(CharacterRange::Range(from, to), zone);
      SafeAdvanceRange(src, &src_index, &from, &to);
    } else if (to > remove_range.to()) {
      // (f) Modify start of current range.
      // |-------|
      // |-------|
      from = remove_range.to() + 1;
      to_remove_index++;
    } else {
      UNREACHABLE();
    }
  }
  // The last range needs special treatment after |to_remove| is exhausted, as
  // |from| might have been modified by the last |to_remove| range and |to| was
  // not yet known (i.e. cases d and f).
  if (from <= to) {
    result->Add(CharacterRange::Range(from, to), zone);
  }
  src_index++;
  // Add remaining ranges after |to_remove| is exhausted.
  for (; src_index < src->length(); src_index++) {
    result->Add(src->at(src_index), zone);
  }
  DCHECK(IsCanonical(result));
}
References v8::internal::ZoneList< T >::at(), v8::internal::DCHECK(), DCHECK_EQ, from(), v8::internal::ZoneList< T >::is_empty(), IsCanonical(), v8::internal::length, v8::internal::ZoneList< T >::length(), Range(), v8::base::internal::result, v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::SafeAdvanceRange(), to(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::RegExpClassSetOperand::Subtract().
to()
base::uc32 v8::internal::CharacterRange::to () const [inline]
Definition at line 141 of file regexp-ast.h.
{ return to_; }
References to_.
Referenced by AddCaseEquivalents(), v8::internal::UnicodeRangeSplitter::AddRange(), Canonicalize(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareInverseRanges(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::CompareRanges(), v8::internal::TextNode::CreateForSurrogatePair(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::Equals(), v8::internal::TextNode::FillInBMInfo(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::Hash(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::InsertRangeInCanonicalList(), IsCanonical(), v8::internal::anonymous_namespace{regexp-macro-assembler.cc}::MakeRangeArray(), Negate(), v8::internal::operator==(), Range(), Subtract(), and v8::internal::anonymous_namespace{regexp-ast.cc}::RegExpUnparser::VisitCharacterRange().
Member Data Documentation
from_
base::uc32 v8::internal::CharacterRange::from_ = 0 [private]
Definition at line 176 of file regexp-ast.h.
Referenced by Contains(), from(), IsEverything(), and IsSingleton().
kMaxCodePoint
constexpr int v8::internal::CharacterRange::kMaxCodePoint = 0x10ffff [static], [constexpr], [private]
Definition at line 174 of file regexp-ast.h.
Referenced by Everything(), and Range().
to_
base::uc32 v8::internal::CharacterRange::to_ = 0 [private]
Definition at line 177 of file regexp-ast.h.
Referenced by ClampToOneByte(), Contains(), IsEverything(), IsSingleton(), and to().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-compiler-tonode.cc