v8::platform::tracing::TraceObject Class Reference
#include <v8-tracing.h>
Classes
union ArgValue
Public Member Functions
TraceObject ()=default
~TraceObject ()
void Initialize (char phase, const uint8_t *category_enabled_flag, const char *name, const char *scope, uint64_t id, uint64_t bind_id, int num_args, const char **arg_names, const uint8_t *arg_types, const uint64_t *arg_values, std::unique_ptr< v8::ConvertableToTraceFormat > *arg_convertables, unsigned int flags, int64_t timestamp, int64_t cpu_timestamp)
void UpdateDuration (int64_t timestamp, int64_t cpu_timestamp)
void InitializeForTesting (char phase, const uint8_t *category_enabled_flag, const char *name, const char *scope, uint64_t id, uint64_t bind_id, int num_args, const char **arg_names, const uint8_t *arg_types, const uint64_t *arg_values, std::unique_ptr< v8::ConvertableToTraceFormat > *arg_convertables, unsigned int flags, int pid, int tid, int64_t ts, int64_t tts, uint64_t duration, uint64_t cpu_duration)
int pid () const
int tid () const
char phase () const
const uint8_t * category_enabled_flag () const
const char * name () const
const char * scope () const
uint64_t id () const
uint64_t bind_id () const
int num_args () const
const char ** arg_names ()
uint8_t * arg_types ()
ArgValue * arg_values ()
std::unique_ptr< v8::ConvertableToTraceFormat > * arg_convertables ()
unsigned int flags () const
int64_t ts ()
int64_t tts ()
uint64_t duration ()
uint64_t cpu_duration ()
Private Member Functions
TraceObject (const TraceObject &)=delete
void operator= (const TraceObject &)=delete
Private Attributes
int pid_
int tid_
char phase_
const char * name_
const char * scope_
const uint8_t * category_enabled_flag_
uint64_t id_
uint64_t bind_id_
int num_args_ = 0
const char * arg_names_ [kTraceMaxNumArgs]
uint8_t arg_types_ [kTraceMaxNumArgs]
ArgValue arg_values_ [kTraceMaxNumArgs]
std::unique_ptr< v8::ConvertableToTraceFormat > arg_convertables_ [kTraceMaxNumArgs]
char * parameter_copy_storage_ = nullptr
unsigned int flags_
int64_t ts_
int64_t tts_
uint64_t duration_
uint64_t cpu_duration_
Detailed Description
Definition at line 36 of file v8-tracing.h.
Constructor & Destructor Documentation
TraceObject() [1/2]
v8::platform::tracing::TraceObject::TraceObject () [default]
 TraceObject()
v8::platform::tracing::TraceObject::~TraceObject ()
Definition at line 102 of file trace-object.cc.
{ delete[] parameter_copy_storage_; }
References parameter_copy_storage_.
TraceObject() [2/2]
v8::platform::tracing::TraceObject::TraceObject (const TraceObject &) [private], [delete]
Member Function Documentation
arg_convertables()
std::unique_ptr<v8::ConvertableToTraceFormat>* v8::platform::tracing::TraceObject::arg_convertables () [inline]
Definition at line 79 of file v8-tracing.h.
                                                                {
    return arg_convertables_;
  }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), and Initialize().
arg_names()
const char** v8::platform::tracing::TraceObject::arg_names () [inline]
Definition at line 76 of file v8-tracing.h.
{ return arg_names_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), and Initialize().
arg_types()
uint8_t* v8::platform::tracing::TraceObject::arg_types () [inline]
Definition at line 77 of file v8-tracing.h.
{ return arg_types_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), and Initialize().
arg_values()
ArgValue* v8::platform::tracing::TraceObject::arg_values () [inline]
Definition at line 78 of file v8-tracing.h.
{ return arg_values_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), and Initialize().
bind_id()
uint64_t v8::platform::tracing::TraceObject::bind_id () const [inline]
Definition at line 74 of file v8-tracing.h.
{ return bind_id_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), Initialize(), and InitializeForTesting().
category_enabled_flag()
const uint8_t* v8::platform::tracing::TraceObject::category_enabled_flag () const [inline]
Definition at line 68 of file v8-tracing.h.
                                               {
    return category_enabled_flag_;
  }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), Initialize(), and InitializeForTesting().
cpu_duration()
uint64_t v8::platform::tracing::TraceObject::cpu_duration () [inline]
Definition at line 86 of file v8-tracing.h.
{ return cpu_duration_; }
Referenced by v8::platform::tracing::Recorder::AddEvent(), v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), and InitializeForTesting().
duration()
uint64_t v8::platform::tracing::TraceObject::duration () [inline]
Definition at line 85 of file v8-tracing.h.
{ return duration_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), and InitializeForTesting().
flags()
unsigned int v8::platform::tracing::TraceObject::flags () const [inline]
Definition at line 82 of file v8-tracing.h.
{ return flags_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), Initialize(), and InitializeForTesting().
id()
uint64_t v8::platform::tracing::TraceObject::id () const [inline]
Definition at line 73 of file v8-tracing.h.
{ return id_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), Initialize(), and InitializeForTesting().
Initialize()
void v8::platform::tracing::TraceObject::Initialize (char phase, const uint8_t * category_enabled_flag, const char * name, const char * scope, uint64_t id, uint64_t bind_id, int num_args, const char ** arg_names, const uint8_t * arg_types, const uint64_t * arg_values, std::unique_ptr< v8::ConvertableToTraceFormat > * arg_convertables, unsigned int flags, int64_t timestamp, int64_t cpu_timestamp)
Definition at line 32 of file trace-object.cc.
                                                                  {
  pid_ = base::OS::GetCurrentProcessId();
  tid_ = base::OS::GetCurrentThreadId();
  phase_ = phase;
  category_enabled_flag_ = category_enabled_flag;
  name_ = name;
  scope_ = scope;
  id_ = id;
  bind_id_ = bind_id;
  flags_ = flags;
  ts_ = timestamp;
  tts_ = cpu_timestamp;
  duration_ = 0;
  cpu_duration_ = 0;
  // Clamp num_args since it may have been set by a third-party library.
  num_args_ = (num_args > kTraceMaxNumArgs) ? kTraceMaxNumArgs : num_args;
  for (int i = 0; i < num_args_; ++i) {
    arg_names_[i] = arg_names[i];
    arg_values_[i].as_uint = arg_values[i];
    arg_types_[i] = arg_types[i];
    if (arg_types[i] == TRACE_VALUE_TYPE_CONVERTABLE)
      arg_convertables_[i] = std::move(arg_convertables[i]);
  }
  bool copy = !!(flags & TRACE_EVENT_FLAG_COPY);
  // Allocate a long string to fit all string copies.
  size_t alloc_size = 0;
  if (copy) {
    alloc_size += GetAllocLength(name) + GetAllocLength(scope);
    for (int i = 0; i < num_args_; ++i) {
      alloc_size += GetAllocLength(arg_names_[i]);
      if (arg_types_[i] == TRACE_VALUE_TYPE_STRING)
        arg_types_[i] = TRACE_VALUE_TYPE_COPY_STRING;
    }
  }
  bool arg_is_copy[kTraceMaxNumArgs];
  for (int i = 0; i < num_args_; ++i) {
    // We only take a copy of arg_vals if they are of type COPY_STRING.
    arg_is_copy[i] = (arg_types_[i] == TRACE_VALUE_TYPE_COPY_STRING);
    if (arg_is_copy[i]) alloc_size += GetAllocLength(arg_values_[i].as_string);
  }
  if (alloc_size) {
    // Since TraceObject can be initialized multiple times, we might need
    // to free old memory.
    delete[] parameter_copy_storage_;
    char* ptr = parameter_copy_storage_ = new char[alloc_size];
    if (copy) {
      CopyTraceObjectParameter(&ptr, &name_);
      CopyTraceObjectParameter(&ptr, &scope_);
      for (int i = 0; i < num_args_; ++i) {
        CopyTraceObjectParameter(&ptr, &arg_names_[i]);
      }
    }
    for (int i = 0; i < num_args_; ++i) {
      if (arg_is_copy[i]) {
        CopyTraceObjectParameter(&ptr, &arg_values_[i].as_string);
      }
    }
  }
}
References arg_convertables(), arg_convertables_, arg_names(), arg_names_, arg_types(), arg_types_, arg_values(), arg_values_, v8::platform::tracing::TraceObject::ArgValue::as_uint, bind_id(), bind_id_, category_enabled_flag(), category_enabled_flag_, v8::platform::tracing::CopyTraceObjectParameter(), cpu_duration_, duration_, flags(), flags_, v8::platform::tracing::GetAllocLength(), v8::base::OS::GetCurrentProcessId(), v8::base::OS::GetCurrentThreadId(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, id(), id_, v8::platform::tracing::kTraceMaxNumArgs, name(), name_, num_args(), num_args_, parameter_copy_storage_, phase(), phase_, pid_, scope(), scope_, tid_, TRACE_EVENT_FLAG_COPY, TRACE_VALUE_TYPE_CONVERTABLE, TRACE_VALUE_TYPE_COPY_STRING, TRACE_VALUE_TYPE_STRING, ts_, and tts_.
InitializeForTesting()
void v8::platform::tracing::TraceObject::InitializeForTesting (char phase, const uint8_t * category_enabled_flag, const char * name, const char * scope, uint64_t id, uint64_t bind_id, int num_args, const char ** arg_names, const uint8_t * arg_types, const uint64_t * arg_values, std::unique_ptr< v8::ConvertableToTraceFormat > * arg_convertables, unsigned int flags, int pid, int tid, int64_t ts, int64_t tts, uint64_t duration, uint64_t cpu_duration)
Definition at line 109 of file trace-object.cc.
                                              {
  pid_ = pid;
  tid_ = tid;
  phase_ = phase;
  category_enabled_flag_ = category_enabled_flag;
  name_ = name;
  scope_ = scope;
  id_ = id;
  bind_id_ = bind_id;
  num_args_ = num_args;
  flags_ = flags;
  ts_ = ts;
  tts_ = tts;
  duration_ = duration;
  cpu_duration_ = cpu_duration;
}
References bind_id(), bind_id_, category_enabled_flag(), category_enabled_flag_, cpu_duration(), cpu_duration_, duration(), duration_, flags(), flags_, id(), id_, name(), name_, num_args(), num_args_, phase(), phase_, pid(), pid_, scope(), scope_, tid(), tid_, ts(), ts_, tts(), and tts_.
name()
const char* v8::platform::tracing::TraceObject::name () const [inline]
Definition at line 71 of file v8-tracing.h.
{ return name_; }
Referenced by v8::platform::tracing::Recorder::AddEvent(), v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), Initialize(), and InitializeForTesting().
num_args()
int v8::platform::tracing::TraceObject::num_args () const [inline]
Definition at line 75 of file v8-tracing.h.
{ return num_args_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), Initialize(), and InitializeForTesting().
operator=()
void v8::platform::tracing::TraceObject::operator= (const TraceObject &) [private], [delete]
phase()
char v8::platform::tracing::TraceObject::phase () const [inline]
Definition at line 67 of file v8-tracing.h.
{ return phase_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), Initialize(), and InitializeForTesting().
pid()
int v8::platform::tracing::TraceObject::pid () const [inline]
Definition at line 65 of file v8-tracing.h.
{ return pid_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), and InitializeForTesting().
scope()
const char* v8::platform::tracing::TraceObject::scope () const [inline]
Definition at line 72 of file v8-tracing.h.
{ return scope_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), Initialize(), and InitializeForTesting().
tid()
int v8::platform::tracing::TraceObject::tid () const [inline]
Definition at line 66 of file v8-tracing.h.
{ return tid_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), and InitializeForTesting().
ts()
int64_t v8::platform::tracing::TraceObject::ts () [inline]
Definition at line 83 of file v8-tracing.h.
{ return ts_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), and InitializeForTesting().
tts()
int64_t v8::platform::tracing::TraceObject::tts () [inline]
Definition at line 84 of file v8-tracing.h.
{ return tts_; }
Referenced by v8::platform::tracing::JSONTraceWriter::AppendTraceEvent(), and InitializeForTesting().
UpdateDuration()
void v8::platform::tracing::TraceObject::UpdateDuration (int64_t timestamp, int64_t cpu_timestamp)
Definition at line 104 of file trace-object.cc.
                                                                         {
  duration_ = timestamp - ts_;
  cpu_duration_ = cpu_timestamp - tts_;
}
References cpu_duration_, duration_, ts_, and tts_.
Referenced by v8::platform::tracing::TracingController::UpdateTraceEventDuration().
Member Data Documentation
arg_convertables_
std::unique_ptr<v8::ConvertableToTraceFormat> v8::platform::tracing::TraceObject::arg_convertables_[kTraceMaxNumArgs] [private]
Definition at line 102 of file v8-tracing.h.
Referenced by Initialize().
arg_names_
const char* v8::platform::tracing::TraceObject::arg_names_[kTraceMaxNumArgs] [private]
Definition at line 98 of file v8-tracing.h.
Referenced by Initialize().
arg_types_
uint8_t v8::platform::tracing::TraceObject::arg_types_[kTraceMaxNumArgs] [private]
Definition at line 99 of file v8-tracing.h.
Referenced by Initialize().
arg_values_
ArgValue v8::platform::tracing::TraceObject::arg_values_[kTraceMaxNumArgs] [private]
Definition at line 100 of file v8-tracing.h.
Referenced by Initialize().
bind_id_
uint64_t v8::platform::tracing::TraceObject::bind_id_ [private]
Definition at line 96 of file v8-tracing.h.
Referenced by Initialize(), and InitializeForTesting().
category_enabled_flag_
const uint8_t* v8::platform::tracing::TraceObject::category_enabled_flag_ [private]
Definition at line 94 of file v8-tracing.h.
Referenced by Initialize(), and InitializeForTesting().
cpu_duration_
uint64_t v8::platform::tracing::TraceObject::cpu_duration_ [private]
Definition at line 108 of file v8-tracing.h.
Referenced by Initialize(), InitializeForTesting(), and UpdateDuration().
duration_
uint64_t v8::platform::tracing::TraceObject::duration_ [private]
Definition at line 107 of file v8-tracing.h.
Referenced by Initialize(), InitializeForTesting(), and UpdateDuration().
flags_
unsigned int v8::platform::tracing::TraceObject::flags_ [private]
Definition at line 104 of file v8-tracing.h.
Referenced by Initialize(), and InitializeForTesting().
id_
uint64_t v8::platform::tracing::TraceObject::id_ [private]
Definition at line 95 of file v8-tracing.h.
Referenced by Initialize(), and InitializeForTesting().
name_
const char* v8::platform::tracing::TraceObject::name_ [private]
Definition at line 92 of file v8-tracing.h.
Referenced by Initialize(), and InitializeForTesting().
num_args_
int v8::platform::tracing::TraceObject::num_args_ = 0 [private]
Definition at line 97 of file v8-tracing.h.
Referenced by Initialize(), and InitializeForTesting().
parameter_copy_storage_
char* v8::platform::tracing::TraceObject::parameter_copy_storage_ = nullptr [private]
Definition at line 103 of file v8-tracing.h.
Referenced by Initialize(), and ~TraceObject().
phase_
char v8::platform::tracing::TraceObject::phase_ [private]
Definition at line 91 of file v8-tracing.h.
Referenced by Initialize(), and InitializeForTesting().
pid_
int v8::platform::tracing::TraceObject::pid_ [private]
Definition at line 89 of file v8-tracing.h.
Referenced by Initialize(), and InitializeForTesting().
scope_
const char* v8::platform::tracing::TraceObject::scope_ [private]
Definition at line 93 of file v8-tracing.h.
Referenced by Initialize(), and InitializeForTesting().
tid_
int v8::platform::tracing::TraceObject::tid_ [private]
Definition at line 90 of file v8-tracing.h.
Referenced by Initialize(), and InitializeForTesting().
ts_
int64_t v8::platform::tracing::TraceObject::ts_ [private]
Definition at line 105 of file v8-tracing.h.
Referenced by Initialize(), InitializeForTesting(), and UpdateDuration().
tts_
int64_t v8::platform::tracing::TraceObject::tts_ [private]
Definition at line 106 of file v8-tracing.h.
Referenced by Initialize(), InitializeForTesting(), and UpdateDuration().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/libplatform/v8-tracing.h
/mnt/V8SourceCode/src/libplatform/tracing/trace-object.cc