v8::internal::AllocateDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_RESULT_AND_PARAMETER_TYPES (MachineType::TaggedPointer(), MachineType::IntPtr()) static const expr auto registers()
Additional Inherited Members
Detailed Description
Definition at line 883 of file interface-descriptors.h.
Member Function Documentation
DEFINE_RESULT_AND_PARAMETER_TYPES()
v8::internal::AllocateDescriptor::DEFINE_RESULT_AND_PARAMETER_TYPES (MachineType::TaggedPointer() , MachineType::IntPtr()) const
References DECLARE_DESCRIPTOR, DEFINE_PARAMETERS_NO_CONTEXT, v8::internal::WasmHandleStackOverflowDescriptor::DEFINE_RESULT_AND_PARAMETER_TYPES(), INTERNAL_DESCRIPTOR, v8::internal::MachineType::IntPtr(), v8::internal::kSandboxed, SANDBOXING_MODE, v8::internal::MachineType::TaggedPointer(), and v8::internal::MachineType::TaggedSigned().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h