v8::internal::FutexEmulation Class Reference
#include <futex-emulation.h>
Public Types
enum WaitMode { kSync = 0
, kAsync
 }
enum class CallType { kIsNotWasm = 0
, kIsWasm
 }
Static Public Member Functions
static Tagged< Object > WaitJs32 (Isolate *isolate, WaitMode mode, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, int32_t value, double rel_timeout_ms)
static Tagged< Object > WaitJs64 (Isolate *isolate, WaitMode mode, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, int64_t value, double rel_timeout_ms)
static V8_EXPORT_PRIVATE Tagged< Object > WaitWasm32 (Isolate *isolate, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, int32_t value, int64_t rel_timeout_ns)
static V8_EXPORT_PRIVATE Tagged< Object > WaitWasm64 (Isolate *isolate, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, int64_t value, int64_t rel_timeout_ns)
static V8_EXPORT_PRIVATE int Wake (Tagged< JSArrayBuffer > array_buffer, size_t addr, uint32_t num_waiters_to_wake)
static int Wake (void *addr, uint32_t num_waiters_to_wake)
static void IsolateDeinit (Isolate *isolate)
static int NumWaitersForTesting (Tagged< JSArrayBuffer > array_buffer, size_t addr)
static int NumUnresolvedAsyncPromisesForTesting (Tagged< JSArrayBuffer > array_buffer, size_t addr)
Static Public Attributes
static const uint32_t kWakeAll = UINT32_MAX
Static Private Member Functions
template<typename T >
static Tagged< Object > Wait (Isolate *isolate, WaitMode mode, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, T value, double rel_timeout_ms)
template<typename T >
static Tagged< Object > Wait (Isolate *isolate, WaitMode mode, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, T value, bool use_timeout, int64_t rel_timeout_ns, CallType call_type=CallType::kIsNotWasm)
template<typename T >
static Tagged< Object > WaitSync (Isolate *isolate, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, T value, bool use_timeout, int64_t rel_timeout_ns, CallType call_type)
template<typename T >
static Tagged< Object > WaitAsync (Isolate *isolate, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, T value, bool use_timeout, int64_t rel_timeout_ns, CallType call_type)
static void ResolveAsyncWaiterPromises (Isolate *isolate)
static void ResolveAsyncWaiterPromise (FutexWaitListNode *node)
static void HandleAsyncWaiterTimeout (FutexWaitListNode *node)
static void NotifyAsyncWaiter (FutexWaitListNode *node)
static void CleanupAsyncWaiterPromise (FutexWaitListNode *node)
Friends
class FutexWaitListNode
class ResolveAsyncWaiterPromisesTask
class AsyncWaiterTimeoutTask
Detailed Description
Definition at line 138 of file futex-emulation.h.
Member Enumeration Documentation
CallType
enum v8::internal::FutexEmulation::CallType [strong]
Enumerator
kIsNotWasm
kIsWasm
Definition at line 141 of file futex-emulation.h.
{ kIsNotWasm = 0, kIsWasm };
WaitMode
enum v8::internal::FutexEmulation::WaitMode
Enumerator
kSync
kAsync
Definition at line 140 of file futex-emulation.h.
{ kSync = 0, kAsync };
Member Function Documentation
CleanupAsyncWaiterPromise()
void v8::internal::FutexEmulation::CleanupAsyncWaiterPromise (FutexWaitListNode * node) [static], [private]
Definition at line 727 of file futex-emulation.cc.
                                                                      {
  DCHECK(node->IsAsync());
  // This function must run in the main thread of node's Isolate. This function
  // may allocate memory. To avoid deadlocks, we shouldn't be holding the
  // FutexEmulationGlobalState::mutex.
  Isolate* isolate = node->async_state_->isolate_for_async_waiters;
  auto v8_isolate = reinterpret_cast<v8::Isolate*>(isolate);
  if (!node->async_state_->promise.IsEmpty()) {
    auto promise = Cast<JSPromise>(
        Utils::OpenDirectHandle(*node->async_state_->promise.Get(v8_isolate)));
    // Promise keeps the NativeContext alive.
    DCHECK(!node->async_state_->native_context.IsEmpty());
    auto native_context = Cast<NativeContext>(Utils::OpenDirectHandle(
        *node->async_state_->native_context.Get(v8_isolate)));
    // Remove the Promise from the NativeContext's set.
    DirectHandle<OrderedHashSet> promises(
        native_context->atomics_waitasync_promises(), isolate);
    bool was_deleted = OrderedHashSet::Delete(isolate, *promises, *promise);
    DCHECK(was_deleted);
    USE(was_deleted);
    promises = OrderedHashSet::Shrink(isolate, promises);
    native_context->set_atomics_waitasync_promises(*promises);
  } else {
    // NativeContext keeps the Promise alive; if the Promise is dead then
    // surely NativeContext is too.
    DCHECK(node->async_state_->native_context.IsEmpty());
  }
}
References v8::internal::FutexWaitListNode::async_state_, v8::internal::DCHECK(), v8::internal::OrderedHashTable< OrderedHashSet, 1 >::Delete(), v8::internal::FutexWaitListNode::IsAsync(), v8::internal::native_context, v8::Utils::OpenDirectHandle(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink(), and USE.
Referenced by HandleAsyncWaiterTimeout(), and ResolveAsyncWaiterPromises().
HandleAsyncWaiterTimeout()
void v8::internal::FutexEmulation::HandleAsyncWaiterTimeout (FutexWaitListNode * node) [static], [private]
Definition at line 837 of file futex-emulation.cc.
                                                                     {
  // This function must run in the main thread of node's Isolate.
  DCHECK(node->IsAsync());
  FutexWaitList* wait_list = GetWaitList();
  {
    NoGarbageCollectionMutexGuard lock_guard(wait_list->mutex());
    node->async_state_->timeout_task_id = CancelableTaskManager::kInvalidTaskId;
    if (!node->waiting_) {
      // If the Node is not waiting, it's already scheduled to have its Promise
      // resolved. Ignore the timeout.
      return;
    }
    wait_list->RemoveNode(node);
  }
  // "node" has been taken out of the lists, so it's ok to access it without
  // holding the mutex. We also need to not hold the mutex while calling
  // CleanupAsyncWaiterPromise, since it may allocate memory.
  HandleScope handle_scope(node->async_state_->isolate_for_async_waiters);
  ResolveAsyncWaiterPromise(node);
  CleanupAsyncWaiterPromise(node);
  delete node;
}
References v8::internal::FutexWaitListNode::async_state_, CleanupAsyncWaiterPromise(), v8::internal::DCHECK(), v8::internal::FutexWaitListNode::IsAsync(), v8::internal::CancelableTaskManager::kInvalidTaskId, v8::internal::FutexWaitList::mutex(), v8::internal::FutexWaitList::RemoveNode(), ResolveAsyncWaiterPromise(), and v8::internal::FutexWaitListNode::waiting_.
Referenced by v8::internal::AsyncWaiterTimeoutTask::RunInternal().
IsolateDeinit()
void v8::internal::FutexEmulation::IsolateDeinit (Isolate * isolate) [static]
Definition at line 864 of file futex-emulation.cc.
                                                   {
  FutexWaitList* wait_list = GetWaitList();
  NoGarbageCollectionMutexGuard lock_guard(wait_list->mutex());
  // Iterate all locations to find nodes belonging to "isolate" and delete them.
  // The Isolate is going away; don't bother cleaning up the Promises in the
  // NativeContext. Also we don't need to cancel the timeout tasks, since they
  // will be cancelled by Isolate::Deinit.
  {
    auto& location_lists = wait_list->location_lists_;
    auto it = location_lists.begin();
    while (it != location_lists.end()) {
      FutexWaitListNode*& head = it->second.head;
      FutexWaitListNode*& tail = it->second.tail;
      FutexWaitList::DeleteNodesForIsolate(isolate, &head, &tail);
      // head and tail are either both nullptr or both non-nullptr.
      DCHECK_EQ(head == nullptr, tail == nullptr);
      if (head == nullptr) {
        it = location_lists.erase(it);
      } else {
        ++it;
      }
    }
  }
  {
    auto& isolate_map = wait_list->isolate_promises_to_resolve_;
    auto it = isolate_map.find(isolate);
    if (it != isolate_map.end()) {
      for (FutexWaitListNode* node = it->second.head; node;) {
        DCHECK(node->IsAsync());
        DCHECK_EQ(isolate, node->async_state_->isolate_for_async_waiters);
        node->async_state_->timeout_task_id =
            CancelableTaskManager::kInvalidTaskId;
        node = FutexWaitList::DeleteAsyncWaiterNode(node);
      }
      isolate_map.erase(it);
    }
  }
  wait_list->Verify();
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::FutexWaitList::DeleteAsyncWaiterNode(), v8::internal::FutexWaitList::DeleteNodesForIsolate(), v8::internal::ETWJITInterface::isolate_map, v8::internal::FutexWaitList::isolate_promises_to_resolve_, v8::internal::CancelableTaskManager::kInvalidTaskId, v8::internal::FutexWaitList::location_lists_, v8::internal::FutexWaitList::mutex(), and v8::internal::FutexWaitList::Verify().
Referenced by v8::internal::Isolate::Deinit().
NotifyAsyncWaiter()
void v8::internal::FutexEmulation::NotifyAsyncWaiter (FutexWaitListNode * node) [static], [private]
Definition at line 179 of file futex-emulation.cc.
                                                              {
  DCHECK(node->IsAsync());
  // This function can run in any thread.
  FutexWaitList* wait_list = GetWaitList();
  wait_list->mutex()->AssertHeld();
  // Nullify the timeout time; this distinguishes timed out waiters from
  // woken up ones.
  node->async_state_->timeout_time = base::TimeTicks();
  wait_list->RemoveNode(node);
  // Schedule a task for resolving the Promise. It's still possible that the
  // timeout task runs before the promise resolving task. In that case, the
  // timeout task will just ignore the node.
  auto& isolate_map = wait_list->isolate_promises_to_resolve_;
  auto it = isolate_map.find(node->async_state_->isolate_for_async_waiters);
  if (it == isolate_map.end()) {
    // This Isolate doesn't have other Promises to resolve at the moment.
    isolate_map.insert(
        std::make_pair(node->async_state_->isolate_for_async_waiters,
                       FutexWaitList::HeadAndTail{node, node}));
    auto task = std::make_unique<ResolveAsyncWaiterPromisesTask>(
        node->async_state_->isolate_for_async_waiters);
    node->async_state_->task_runner->PostNonNestableTask(std::move(task));
  } else {
    // Add this Node into the existing list.
    node->prev_ = it->second.tail;
    it->second.tail->next_ = node;
    it->second.tail = node;
  }
}
References v8::base::Mutex::AssertHeld(), v8::internal::FutexWaitListNode::async_state_, v8::internal::DCHECK(), v8::internal::FutexWaitListNode::IsAsync(), v8::internal::ETWJITInterface::isolate_map, v8::internal::FutexWaitList::isolate_promises_to_resolve_, v8::internal::FutexWaitList::mutex(), v8::internal::FutexWaitListNode::next_, v8::internal::FutexWaitListNode::prev_, and v8::internal::FutexWaitList::RemoveNode().
Referenced by Wake().
NumUnresolvedAsyncPromisesForTesting()
int v8::internal::FutexEmulation::NumUnresolvedAsyncPromisesForTesting (Tagged< JSArrayBuffer > array_buffer, size_t addr) [static]
Definition at line 931 of file futex-emulation.cc.
                                                     {
  void* wait_location = FutexWaitList::ToWaitLocation(array_buffer, addr);
  FutexWaitList* wait_list = GetWaitList();
  NoGarbageCollectionMutexGuard lock_guard(wait_list->mutex());
  int num_waiters = 0;
  auto& isolate_map = wait_list->isolate_promises_to_resolve_;
  for (const auto& it : isolate_map) {
    for (FutexWaitListNode* node = it.second.head; node; node = node->next_) {
      DCHECK(node->IsAsync());
      if (node->waiting_) continue;
      if (wait_location != node->wait_location_) continue;
      if (node->async_state_->backing_store.expired()) continue;
      DCHECK_EQ(array_buffer->GetBackingStore(),
                node->async_state_->backing_store.lock());
      num_waiters++;
    }
  }
  return num_waiters;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ETWJITInterface::isolate_map, v8::internal::FutexWaitList::isolate_promises_to_resolve_, v8::internal::FutexWaitList::mutex(), v8::internal::FutexWaitListNode::next_, and v8::internal::FutexWaitList::ToWaitLocation().
Referenced by v8::internal::RUNTIME_FUNCTION().
NumWaitersForTesting()
int v8::internal::FutexEmulation::NumWaitersForTesting (Tagged< JSArrayBuffer > array_buffer, size_t addr) [static]
Definition at line 907 of file futex-emulation.cc.
                                                      {
  void* wait_location = FutexWaitList::ToWaitLocation(*array_buffer, addr);
  FutexWaitList* wait_list = GetWaitList();
  NoGarbageCollectionMutexGuard lock_guard(wait_list->mutex());
  int num_waiters = 0;
  auto& location_lists = wait_list->location_lists_;
  auto it = location_lists.find(wait_location);
  if (it == location_lists.end()) return num_waiters;
  for (FutexWaitListNode* node = it->second.head; node; node = node->next_) {
    if (!node->waiting_) continue;
    if (node->IsAsync()) {
      if (node->async_state_->backing_store.expired()) continue;
      DCHECK_EQ(array_buffer->GetBackingStore(),
                node->async_state_->backing_store.lock());
    }
    num_waiters++;
  }
  return num_waiters;
}
References DCHECK_EQ, v8::internal::FutexWaitList::location_lists_, v8::internal::FutexWaitList::mutex(), v8::internal::FutexWaitListNode::next_, and v8::internal::FutexWaitList::ToWaitLocation().
Referenced by v8::internal::RUNTIME_FUNCTION().
ResolveAsyncWaiterPromise()
void v8::internal::FutexEmulation::ResolveAsyncWaiterPromise (FutexWaitListNode * node) [static], [private]
Definition at line 759 of file futex-emulation.cc.
                                                                      {
  DCHECK(node->IsAsync());
  // This function must run in the main thread of node's Isolate.
  Isolate* isolate = node->async_state_->isolate_for_async_waiters;
  v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate);
  // Try to cancel the timeout task (if one exists). If the timeout task exists,
  // cancelling it will always succeed. It's not possible for the timeout task
  // to be running, since it's scheduled to run in the same thread as this task.
  // Using the CancelableTaskManager here is OK since the Isolate is guaranteed
  // to be alive - FutexEmulation::IsolateDeinit removes all FutexWaitListNodes
  // owned by an Isolate which is going to die.
  bool success = node->CancelTimeoutTask();
  DCHECK(success);
  USE(success);
  if (!node->async_state_->promise.IsEmpty()) {
    DCHECK(!node->async_state_->native_context.IsEmpty());
    Local<v8::Context> native_context =
        node->async_state_->native_context.Get(v8_isolate);
    v8::Context::Scope contextScope(native_context);
    DirectHandle<JSPromise> promise = Cast<JSPromise>(
        Utils::OpenHandle(*node->async_state_->promise.Get(v8_isolate)));
    DirectHandle<String> result_string;
    // When waiters are notified, their timeout_time is reset. Having a
    // non-zero timeout_time here means the waiter timed out.
    if (node->async_state_->timeout_time != base::TimeTicks()) {
      DCHECK(node->waiting_);
      result_string = isolate->factory()->timed_out_string();
    } else {
      DCHECK(!node->waiting_);
      result_string = isolate->factory()->ok_string();
    }
    MaybeDirectHandle<Object> resolve_result =
        JSPromise::Resolve(promise, result_string);
    DCHECK(!resolve_result.is_null());
    USE(resolve_result);
  }
}
References v8::internal::FutexWaitListNode::async_state_, v8::internal::FutexWaitListNode::CancelTimeoutTask(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::FutexWaitListNode::IsAsync(), v8::internal::native_context, v8::Utils::OpenHandle(), v8::internal::JSPromise::Resolve(), USE, and v8::internal::FutexWaitListNode::waiting_.
Referenced by HandleAsyncWaiterTimeout(), and ResolveAsyncWaiterPromises().
ResolveAsyncWaiterPromises()
void v8::internal::FutexEmulation::ResolveAsyncWaiterPromises (Isolate * isolate) [static], [private]
Definition at line 801 of file futex-emulation.cc.
                                                                {
  // This function must run in the main thread of isolate.
  FutexWaitList* wait_list = GetWaitList();
  FutexWaitListNode* node;
  {
    NoGarbageCollectionMutexGuard lock_guard(wait_list->mutex());
    auto& isolate_map = wait_list->isolate_promises_to_resolve_;
    auto it = isolate_map.find(isolate);
    DCHECK_NE(isolate_map.end(), it);
    node = it->second.head;
    isolate_map.erase(it);
  }
  // The list of nodes starting from "node" are no longer on any list, so it's
  // ok to iterate them without holding the mutex. We also need to not hold the
  // mutex while calling CleanupAsyncWaiterPromise, since it may allocate
  // memory.
  HandleScope handle_scope(isolate);
  while (node) {
    DCHECK(node->IsAsync());
    DCHECK_EQ(isolate, node->async_state_->isolate_for_async_waiters);
    DCHECK(!node->waiting_);
    ResolveAsyncWaiterPromise(node);
    CleanupAsyncWaiterPromise(node);
    // We've already tried to cancel the timeout task for the node; since we're
    // now in the same thread the timeout task is supposed to run, we know the
    // timeout task will never happen, and it's safe to delete the node here.
    DCHECK_EQ(CancelableTaskManager::kInvalidTaskId,
              node->async_state_->timeout_task_id);
    node = FutexWaitList::DeleteAsyncWaiterNode(node);
  }
}
References v8::internal::FutexWaitListNode::async_state_, CleanupAsyncWaiterPromise(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::FutexWaitList::DeleteAsyncWaiterNode(), v8::internal::FutexWaitListNode::IsAsync(), v8::internal::ETWJITInterface::isolate_map, v8::internal::FutexWaitList::isolate_promises_to_resolve_, v8::internal::CancelableTaskManager::kInvalidTaskId, v8::internal::FutexWaitList::mutex(), ResolveAsyncWaiterPromise(), and v8::internal::FutexWaitListNode::waiting_.
Referenced by v8::internal::ResolveAsyncWaiterPromisesTask::RunInternal().
Wait() [1/2]
template<typename T >
Tagged< Object > v8::internal::FutexEmulation::Wait (Isolate * isolate, WaitMode mode, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, T value, bool use_timeout, int64_t rel_timeout_ns, CallType call_type = CallType::kIsNotWasm) [static], [private]
Definition at line 345 of file futex-emulation.cc.
                                                        {
  if (mode == WaitMode::kSync) {
    return WaitSync(isolate, array_buffer, addr, value, use_timeout,
                    rel_timeout_ns, call_type);
  }
  DCHECK_EQ(mode, WaitMode::kAsync);
  return WaitAsync(isolate, array_buffer, addr, value, use_timeout,
                   rel_timeout_ns, call_type);
}
References DCHECK_EQ, mode(), v8::internal::value, WaitAsync(), and WaitSync().
Wait() [2/2]
template<typename T >
Tagged< Object > v8::internal::FutexEmulation::Wait (Isolate * isolate, WaitMode mode, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, T value, double rel_timeout_ms) [static], [private]
Definition at line 318 of file futex-emulation.cc.
                                                           {
  DCHECK_LT(addr, array_buffer->GetByteLength());
  bool use_timeout = rel_timeout_ms != V8_INFINITY;
  int64_t rel_timeout_ns = -1;
  if (use_timeout) {
    // Convert to nanoseconds.
    double timeout_ns = rel_timeout_ms *
                        base::Time::kNanosecondsPerMicrosecond *
                        base::Time::kMicrosecondsPerMillisecond;
    if (timeout_ns > static_cast<double>(std::numeric_limits<int64_t>::max())) {
      // 2**63 nanoseconds is 292 years. Let's just treat anything greater as
      // infinite.
      use_timeout = false;
    } else {
      rel_timeout_ns = static_cast<int64_t>(timeout_ns);
    }
  }
  return Wait(isolate, mode, array_buffer, addr, value, use_timeout,
              rel_timeout_ns);
}
References DCHECK_LT, v8::base::TimeConstants::kMicrosecondsPerMillisecond, v8::base::TimeConstants::kNanosecondsPerMicrosecond, mode(), V8_INFINITY, and v8::internal::value.
WaitAsync()
template<typename T >
Tagged< Object > v8::internal::FutexEmulation::WaitAsync (Isolate * isolate, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, T value, bool use_timeout, int64_t rel_timeout_ns, CallType call_type) [static], [private]
Definition at line 503 of file futex-emulation.cc.
                                                                           {
  base::TimeDelta rel_timeout =
      base::TimeDelta::FromNanoseconds(rel_timeout_ns);
  Factory* factory = isolate->factory();
  DirectHandle<JSObject> result =
      factory->NewJSObject(isolate->object_function());
  DirectHandle<JSObject> promise_capability = factory->NewJSPromise();
  enum class ResultKind { kNotEqual, kTimedOut, kAsync };
  ResultKind result_kind;
  void* wait_location = FutexWaitList::ToWaitLocation(*array_buffer, addr);
  // Get a weak pointer to the backing store, to be stored in the async state of
  // the node.
  std::weak_ptr<BackingStore> backing_store{array_buffer->GetBackingStore()};
  FutexWaitList* wait_list = GetWaitList();
  {
    // 16. Perform EnterCriticalSection(WL).
    NoGarbageCollectionMutexGuard lock_guard(wait_list->mutex());
    // 17. Let w be ! AtomicLoad(typedArray, i).
    std::atomic<T>* p = static_cast<std::atomic<T>*>(wait_location);
    T loaded_value = p->load();
#if defined(V8_TARGET_BIG_ENDIAN)
    // If loading a Wasm value, it needs to be reversed on Big Endian platforms.
    if (call_type == CallType::kIsWasm) {
      DCHECK(sizeof(T) == kInt32Size || sizeof(T) == kInt64Size);
      loaded_value = ByteReverse(loaded_value);
    }
#endif
    if (loaded_value != value) {
      result_kind = ResultKind::kNotEqual;
    } else if (use_timeout && rel_timeout_ns == 0) {
      result_kind = ResultKind::kTimedOut;
    } else {
      result_kind = ResultKind::kAsync;
      FutexWaitListNode* node = new FutexWaitListNode(
          std::move(backing_store), wait_location, promise_capability, isolate);
      if (use_timeout) {
        node->async_state_->timeout_time = base::TimeTicks::Now() + rel_timeout;
        auto task = std::make_unique<AsyncWaiterTimeoutTask>(
            node->async_state_->isolate_for_async_waiters
                ->cancelable_task_manager(),
            node);
        node->async_state_->timeout_task_id = task->id();
        node->async_state_->task_runner->PostNonNestableDelayedTask(
            std::move(task), rel_timeout.InSecondsF());
      }
      wait_list->AddNode(node);
    }
    // Leaving the block collapses the following steps:
    // 18.a. Perform LeaveCriticalSection(WL).
    // 19.b. Perform LeaveCriticalSection(WL).
    // 24. Perform LeaveCriticalSection(WL).
  }
  switch (result_kind) {
    case ResultKind::kNotEqual:
      // 18. If v is not equal to w, then
      // ...
      // c. Perform ! CreateDataPropertyOrThrow(resultObject, "async", false).
      // d. Perform ! CreateDataPropertyOrThrow(resultObject, "value",
      // "not-equal").
      // e. Return resultObject.
      CHECK(JSReceiver::CreateDataProperty(
                isolate, result, factory->async_string(),
                factory->false_value(), Just(kDontThrow))
                .FromJust());
      CHECK(JSReceiver::CreateDataProperty(
                isolate, result, factory->value_string(),
                factory->not_equal_string(), Just(kDontThrow))
                .FromJust());
      break;
    case ResultKind::kTimedOut:
      // 19. If t is 0 and mode is async, then
      // ...
      // c. Perform ! CreateDataPropertyOrThrow(resultObject, "async", false).
      // d. Perform ! CreateDataPropertyOrThrow(resultObject, "value",
      // "timed-out").
      // e. Return resultObject.
      CHECK(JSReceiver::CreateDataProperty(
                isolate, result, factory->async_string(),
                factory->false_value(), Just(kDontThrow))
                .FromJust());
      CHECK(JSReceiver::CreateDataProperty(
                isolate, result, factory->value_string(),
                factory->timed_out_string(), Just(kDontThrow))
                .FromJust());
      break;
    case ResultKind::kAsync:
      // Add the Promise into the NativeContext's atomics_waitasync_promises
      // set, so that the list keeps it alive.
      DirectHandle<NativeContext> native_context(isolate->native_context());
      DirectHandle<OrderedHashSet> promises(
          native_context->atomics_waitasync_promises(), isolate);
      promises = OrderedHashSet::Add(isolate, promises, promise_capability)
                     .ToHandleChecked();
      native_context->set_atomics_waitasync_promises(*promises);
      // 26. Perform ! CreateDataPropertyOrThrow(resultObject, "async", true).
      // 27. Perform ! CreateDataPropertyOrThrow(resultObject, "value",
      // promiseCapability.[[Promise]]).
      // 28. Return resultObject.
      CHECK(JSReceiver::CreateDataProperty(
                isolate, result, factory->async_string(), factory->true_value(),
                Just(kDontThrow))
                .FromJust());
      CHECK(JSReceiver::CreateDataProperty(isolate, result,
                                           factory->value_string(),
                                           promise_capability, Just(kDontThrow))
                .FromJust());
      break;
  }
  return *result;
}
References v8::bigint::Add(), v8::internal::FutexWaitList::AddNode(), v8::internal::FutexWaitListNode::async_state_, v8::internal::ByteReverse(), CHECK, v8::internal::JSReceiver::CreateDataProperty(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::base::TimeDelta::FromNanoseconds(), FutexWaitListNode, v8::base::TimeDelta::InSecondsF(), v8::Just(), kAsync, v8::internal::kDontThrow, v8::internal::kInt32Size, v8::internal::kInt64Size, kIsWasm, v8::internal::kNotEqual, v8::internal::kTimedOut, v8::internal::FutexWaitList::mutex(), v8::internal::Isolate::native_context(), v8::internal::native_context, v8::internal::Factory::NewJSObject(), v8::internal::Factory::NewJSPromise(), v8::base::TimeTicks::Now(), v8::base::internal::result, v8::internal::FutexWaitList::ToWaitLocation(), and v8::internal::value.
Referenced by Wait().
WaitJs32()
Tagged< Object > v8::internal::FutexEmulation::WaitJs32 (Isolate * isolate, WaitMode mode, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, int32_t value, double rel_timeout_ms) [static]
Definition at line 287 of file futex-emulation.cc.
                                                       {
  Tagged<Object> res =
      Wait<int32_t>(isolate, mode, array_buffer, addr, value, rel_timeout_ms);
  return WaitJsTranslateReturn(isolate, res);
}
References mode(), v8::internal::value, and v8::internal::anonymous_namespace{futex-emulation.cc}::WaitJsTranslateReturn().
Referenced by v8::internal::DoWait().
WaitJs64()
Tagged< Object > v8::internal::FutexEmulation::WaitJs64 (Isolate * isolate, WaitMode mode, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, int64_t value, double rel_timeout_ms) [static]
Definition at line 295 of file futex-emulation.cc.
                                                       {
  Tagged<Object> res =
      Wait<int64_t>(isolate, mode, array_buffer, addr, value, rel_timeout_ms);
  return WaitJsTranslateReturn(isolate, res);
}
References mode(), v8::internal::value, and v8::internal::anonymous_namespace{futex-emulation.cc}::WaitJsTranslateReturn().
Referenced by v8::internal::DoWait().
WaitSync()
template<typename T >
Tagged< Object > v8::internal::FutexEmulation::WaitSync (Isolate * isolate, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, T value, bool use_timeout, int64_t rel_timeout_ns, CallType call_type) [static], [private]
Definition at line 360 of file futex-emulation.cc.
                                                                           {
  VMState<ATOMICS_WAIT> state(isolate);
  base::TimeDelta rel_timeout =
      base::TimeDelta::FromNanoseconds(rel_timeout_ns);
  DirectHandle<Object> result;
  FutexWaitList* wait_list = GetWaitList();
  FutexWaitListNode* node = isolate->futex_wait_list_node();
  void* wait_location = FutexWaitList::ToWaitLocation(*array_buffer, addr);
  base::TimeTicks timeout_time;
  if (use_timeout) {
    base::TimeTicks current_time = base::TimeTicks::Now();
    timeout_time = current_time + rel_timeout;
  }
  // The following is not really a loop; the do-while construct makes it easier
  // to break out early.
  // Keep the code in the loop as minimal as possible, because this is all in
  // the critical section.
  do {
    NoGarbageCollectionMutexGuard lock_guard(wait_list->mutex());
    std::atomic<T>* p = reinterpret_cast<std::atomic<T>*>(wait_location);
    T loaded_value = p->load();
#if defined(V8_TARGET_BIG_ENDIAN)
    // If loading a Wasm value, it needs to be reversed on Big Endian platforms.
    if (call_type == CallType::kIsWasm) {
      DCHECK(sizeof(T) == kInt32Size || sizeof(T) == kInt64Size);
      loaded_value = ByteReverse(loaded_value);
    }
#endif
    if (loaded_value != value) {
      result =
          direct_handle(Smi::FromInt(WaitReturnValue::kNotEqualValue), isolate);
      break;
    }
    node->wait_location_ = wait_location;
    node->waiting_ = true;
    wait_list->AddNode(node);
    while (true) {
      if (V8_UNLIKELY(node->interrupted_)) {
        // Reset the interrupted flag while still holding the mutex.
        node->interrupted_ = false;
        // Unlock the mutex here to prevent deadlock from lock ordering between
        // mutex and mutexes locked by HandleInterrupts.
        lock_guard.Unlock();
        // Because the mutex is unlocked, we have to be careful about not
        // dropping an interrupt. The notification can happen in three different
        // places:
        // 1) Before Wait is called: the notification will be dropped, but
        // interrupted_ will be set to 1. This will be checked below.
        // 2) After interrupted has been checked here, but before mutex is
        // acquired: interrupted is checked in a loop, with mutex locked.
        // Because the wakeup signal also acquires mutex, we know it will not
        // be able to notify until mutex is released below, when waiting on
        // the condition variable.
        // 3) After the mutex is released in the call to WaitFor(): this
        // notification will wake up the condition variable. node->waiting()
        // will be false, so we'll loop and then check interrupts.
        Tagged<Object> interrupt_object =
            isolate->stack_guard()->HandleInterrupts();
        lock_guard.Lock();
        if (IsException(interrupt_object, isolate)) {
          result = direct_handle(interrupt_object, isolate);
          break;
        }
      }
      if (V8_UNLIKELY(node->interrupted_)) {
        // An interrupt occurred while the mutex was unlocked. Don't wait yet.
        continue;
      }
      if (!node->waiting_) {
        // We were woken via Wake.
        result = direct_handle(Smi::FromInt(WaitReturnValue::kOk), isolate);
        break;
      }
      // No interrupts, now wait.
      if (use_timeout) {
        base::TimeTicks current_time = base::TimeTicks::Now();
        if (current_time >= timeout_time) {
          result =
              direct_handle(Smi::FromInt(WaitReturnValue::kTimedOut), isolate);
          break;
        }
        base::TimeDelta time_until_timeout = timeout_time - current_time;
        DCHECK_GE(time_until_timeout.InMicroseconds(), 0);
        bool wait_for_result =
            node->cond_.WaitFor(wait_list->mutex(), time_until_timeout);
        USE(wait_for_result);
      } else {
        node->cond_.Wait(wait_list->mutex());
      }
      // Spurious wakeup, interrupt or timeout.
    }
    node->waiting_ = false;
    wait_list->RemoveNode(node);
  } while (false);
  DCHECK(!node->waiting_);
  return *result;
}
References v8::internal::FutexWaitList::AddNode(), v8::internal::ByteReverse(), v8::internal::FutexWaitListNode::cond_, v8::internal::DCHECK(), DCHECK_GE, v8::internal::direct_handle(), v8::internal::Smi::FromInt(), v8::base::TimeDelta::FromNanoseconds(), v8::internal::Isolate::futex_wait_list_node(), v8::internal::StackGuard::HandleInterrupts(), v8::base::TimeDelta::InMicroseconds(), v8::internal::FutexWaitListNode::interrupted_, v8::internal::kInt32Size, v8::internal::kInt64Size, kIsWasm, v8::internal::kNotEqualValue, v8::internal::kOk, v8::internal::kTimedOut, v8::internal::NoGarbageCollectionMutexGuard::Lock(), v8::internal::FutexWaitList::mutex(), v8::base::TimeTicks::Now(), v8::internal::FutexWaitList::RemoveNode(), v8::base::internal::result, v8::internal::Isolate::stack_guard(), v8::internal::FutexWaitList::ToWaitLocation(), v8::internal::NoGarbageCollectionMutexGuard::Unlock(), USE, V8_UNLIKELY, v8::internal::value, v8::base::ConditionVariable::Wait(), v8::internal::FutexWaitListNode::wait_location_, v8::base::ConditionVariable::WaitFor(), and v8::internal::FutexWaitListNode::waiting_.
Referenced by Wait().
WaitWasm32()
Tagged< Object > v8::internal::FutexEmulation::WaitWasm32 (Isolate * isolate, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, int32_t value, int64_t rel_timeout_ns) [static]
Definition at line 303 of file futex-emulation.cc.
                                           {
  return Wait<int32_t>(isolate, WaitMode::kSync, array_buffer, addr, value,
                       rel_timeout_ns >= 0, rel_timeout_ns, CallType::kIsWasm);
}
References kIsWasm, and v8::internal::value.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::I32AtomicWait(), and v8::internal::RUNTIME_FUNCTION().
WaitWasm64()
Tagged< Object > v8::internal::FutexEmulation::WaitWasm64 (Isolate * isolate, DirectHandle< JSArrayBuffer > array_buffer, size_t addr, int64_t value, int64_t rel_timeout_ns) [static]
Definition at line 310 of file futex-emulation.cc.
                                           {
  return Wait<int64_t>(isolate, WaitMode::kSync, array_buffer, addr, value,
                       rel_timeout_ns >= 0, rel_timeout_ns, CallType::kIsWasm);
}
References kIsWasm, and v8::internal::value.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::I64AtomicWait(), and v8::internal::RUNTIME_FUNCTION().
Wake() [1/2]
int v8::internal::FutexEmulation::Wake (Tagged< JSArrayBuffer > array_buffer, size_t addr, uint32_t num_waiters_to_wake) [static]
Definition at line 628 of file futex-emulation.cc.
                                                       {
  void* wait_location = FutexWaitList::ToWaitLocation(array_buffer, addr);
  return Wake(wait_location, num_waiters_to_wake);
}
References v8::internal::FutexWaitList::ToWaitLocation().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::AtomicNotify(), and v8::internal::BUILTIN().
Wake() [2/2]
int v8::internal::FutexEmulation::Wake (void * addr, uint32_t num_waiters_to_wake) [static]
Definition at line 634 of file futex-emulation.cc.
                                                                          {
  int num_waiters_woken = 0;
  FutexWaitList* wait_list = GetWaitList();
  NoGarbageCollectionMutexGuard lock_guard(wait_list->mutex());
  auto& location_lists = wait_list->location_lists_;
  auto it = location_lists.find(wait_location);
  if (it == location_lists.end()) return num_waiters_woken;
  FutexWaitListNode* node = it->second.head;
  while (node && num_waiters_to_wake > 0) {
    if (!node->waiting_) {
      node = node->next_;
      continue;
    }
    // Relying on wait_location_ here is not enough, since we need to guard
    // against the case where the BackingStore of the node has been deleted
    // during an async wait and a new BackingStore recreated in the same memory
    // area. Note that sync wait always keeps the backing store alive.
    // It is sufficient to check whether the node's backing store is expired
    // (and consider this a non-match). If it is not expired, it must be
    // identical to the backing store from which wait_location was computed by
    // the caller. In that case, the current context holds the arraybuffer and
    // backing store alive during this call, so it can not expire while we
    // execute this code.
    bool matching_backing_store =
        !node->IsAsync() || !node->async_state_->backing_store.expired();
    if (V8_LIKELY(matching_backing_store)) {
      node->waiting_ = false;
      // Retrieve the next node to iterate before calling NotifyAsyncWaiter,
      // since NotifyAsyncWaiter will take the node out of the linked list.
      FutexWaitListNode* next_node = node->next_;
      if (node->IsAsync()) {
        NotifyAsyncWaiter(node);
      } else {
        // WaitSync will remove the node from the list.
        node->cond_.NotifyOne();
      }
      node = next_node;
      if (num_waiters_to_wake != kWakeAll) {
        --num_waiters_to_wake;
      }
      num_waiters_woken++;
      continue;
    }
    // ---
    // Code below handles the unlikely case that this node's backing store was
    // deleted during an async wait and a new one was allocated in its place.
    // We delete the node if possible (no timeout, or context is gone).
    // ---
    bool delete_this_node = false;
    DCHECK(node->IsAsync());
    if (node->async_state_->timeout_time.IsNull()) {
      // Backing store has been deleted and the node is still waiting, and
      // there's no timeout. It's never going to be woken up, so we can clean it
      // up now. We don't need to cancel the timeout task, because there is
      // none.
      // This cleanup code is not very efficient, since it only kicks in when
      // a new BackingStore has been created in the same memory area where the
      // deleted BackingStore was.
      DCHECK(node->IsAsync());
      DCHECK_EQ(CancelableTaskManager::kInvalidTaskId,
                node->async_state_->timeout_task_id);
      delete_this_node = true;
    }
    if (node->async_state_->native_context.IsEmpty()) {
      // The NativeContext related to the async waiter has been deleted.
      // Ditto, clean up now.
      // Using the CancelableTaskManager here is OK since the Isolate is
      // guaranteed to be alive - FutexEmulation::IsolateDeinit removes all
      // FutexWaitListNodes owned by an Isolate which is going to die.
      if (node->CancelTimeoutTask()) {
        delete_this_node = true;
      }
      // If cancelling the timeout task failed, the timeout task is already
      // running and will clean up the node.
    }
    FutexWaitListNode* next_node = node->next_;
    if (delete_this_node) {
      wait_list->RemoveNode(node);
      delete node;
    }
    node = next_node;
  }
  return num_waiters_woken;
}
References v8::internal::FutexWaitListNode::async_state_, v8::internal::FutexWaitListNode::CancelTimeoutTask(), v8::internal::FutexWaitListNode::cond_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::FutexWaitListNode::IsAsync(), v8::internal::CancelableTaskManager::kInvalidTaskId, kWakeAll, v8::internal::FutexWaitList::location_lists_, v8::internal::FutexWaitList::mutex(), v8::internal::FutexWaitListNode::next_, NotifyAsyncWaiter(), v8::base::ConditionVariable::NotifyOne(), v8::internal::FutexWaitList::RemoveNode(), V8_LIKELY, and v8::internal::FutexWaitListNode::waiting_.
Friends And Related Function Documentation
AsyncWaiterTimeoutTask
friend class AsyncWaiterTimeoutTask [friend]
Definition at line 202 of file futex-emulation.h.
FutexWaitListNode
friend class FutexWaitListNode [friend]
Definition at line 200 of file futex-emulation.h.
Referenced by WaitAsync().
ResolveAsyncWaiterPromisesTask
friend class ResolveAsyncWaiterPromisesTask [friend]
Definition at line 201 of file futex-emulation.h.
Member Data Documentation
kWakeAll
const uint32_t v8::internal::FutexEmulation::kWakeAll = UINT32_MAX [static]
Definition at line 144 of file futex-emulation.h.
Referenced by Wake().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/futex-emulation.h
/mnt/V8SourceCode/src/execution/futex-emulation.cc