v8::internal::FullStringForwardingTableCleaner Class Reference
Public Member Functions
FullStringForwardingTableCleaner (Heap *heap)
void TransitionStrings ()
void ProcessFullWithStack ()
Private Member Functions
void MarkForwardObject (StringForwardingTable::Record *record)
void TransitionStrings (StringForwardingTable::Record *record)
void TryExternalize (Tagged< String > original_string, StringForwardingTable::Record *record)
void TryInternalize (Tagged< String > original_string, StringForwardingTable::Record *record)
Private Attributes
Heap *const heap_
Additional Inherited Members
Detailed Description
Definition at line 2654 of file mark-compact.cc.
Constructor & Destructor Documentation
FullStringForwardingTableCleaner()
v8::internal::FullStringForwardingTableCleaner::FullStringForwardingTableCleaner (Heap * heap) [inline], [explicit]
Definition at line 2657 of file mark-compact.cc.
      : StringForwardingTableCleanerBase(heap), heap_(heap) {
    USE(heap_);
  }
References USE.
Member Function Documentation
MarkForwardObject()
void v8::internal::FullStringForwardingTableCleaner::MarkForwardObject (StringForwardingTable::Record * record) [inline], [private]
Definition at line 2695 of file mark-compact.cc.
                                                              {
    Tagged<Object> original = record->OriginalStringObject(isolate_);
    if (!IsHeapObject(original)) {
      DCHECK_EQ(original, StringForwardingTable::deleted_element());
      return;
    }
    Tagged<String> original_string = Cast<String>(original);
    if (MarkingHelper::IsMarkedOrAlwaysLive(heap_, marking_state_,
                                            original_string)) {
      Tagged<Object> forward = record->ForwardStringObjectOrHash(isolate_);
      if (!IsHeapObject(forward) ||
          (MarkingHelper::GetLivenessMode(heap_, Cast<HeapObject>(forward)) ==
           MarkingHelper::LivenessMode::kAlwaysLive)) {
        return;
      }
      marking_state_->TryMarkAndAccountLiveBytes(Cast<HeapObject>(forward));
    } else {
      DisposeExternalResource(record);
      record->set_original_string(StringForwardingTable::deleted_element());
    }
  }
References DCHECK_EQ, v8::internal::StringForwardingTable::Record::ForwardStringObjectOrHash(), v8::internal::InstanceTypeChecker::IsHeapObject(), v8::internal::StringForwardingTable::Record::OriginalStringObject(), and v8::internal::StringForwardingTable::Record::set_original_string().
ProcessFullWithStack()
void v8::internal::FullStringForwardingTableCleaner::ProcessFullWithStack () [inline]
Definition at line 2683 of file mark-compact.cc.
                              {
    DCHECK(heap_->IsGCWithStack() &&
           !v8_flags.transition_strings_during_gc_with_stack);
    StringForwardingTable* forwarding_table =
        isolate_->string_forwarding_table();
    forwarding_table->IterateElements(
        [&](StringForwardingTable::Record* record) {
          MarkForwardObject(record);
        });
  }
References DCHECK, v8::internal::StringForwardingTable::IterateElements(), and v8::internal::v8_flags.
Referenced by v8::internal::MarkCompactCollector::ClearNonLiveReferences().
TransitionStrings() [1/2]
void v8::internal::FullStringForwardingTableCleaner::TransitionStrings () [inline]
Definition at line 2664 of file mark-compact.cc.
                           {
    DCHECK(!heap_->IsGCWithStack() ||
           v8_flags.transition_strings_during_gc_with_stack);
    StringForwardingTable* forwarding_table =
        isolate_->string_forwarding_table();
    forwarding_table->IterateElements(
        [&](StringForwardingTable::Record* record) {
          TransitionStrings(record);
        });
    forwarding_table->Reset();
  }
References DCHECK, v8::internal::StringForwardingTable::IterateElements(), v8::internal::StringForwardingTable::Reset(), and v8::internal::v8_flags.
Referenced by v8::internal::MarkCompactCollector::ClearNonLiveReferences().
TransitionStrings() [2/2]
void v8::internal::FullStringForwardingTableCleaner::TransitionStrings (StringForwardingTable::Record * record) [inline], [private]
Definition at line 2717 of file mark-compact.cc.
                                                              {
    Tagged<Object> original = record->OriginalStringObject(isolate_);
    if (!IsHeapObject(original)) {
      DCHECK_EQ(original, StringForwardingTable::deleted_element());
      return;
    }
    if (MarkingHelper::IsMarkedOrAlwaysLive(heap_, marking_state_,
                                            Cast<HeapObject>(original))) {
      Tagged<String> original_string = Cast<String>(original);
      if (IsThinString(original_string)) {
        original_string = Cast<ThinString>(original_string)->actual();
      }
      TryExternalize(original_string, record);
      TryInternalize(original_string, record);
      original_string->set_raw_hash_field(record->raw_hash(isolate_));
    } else {
      DisposeExternalResource(record);
    }
  }
References DCHECK_EQ, v8::internal::InstanceTypeChecker::IsHeapObject(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::StringForwardingTable::Record::OriginalStringObject(), and v8::internal::StringForwardingTable::Record::raw_hash().
TryExternalize()
void v8::internal::FullStringForwardingTableCleaner::TryExternalize (Tagged< String > original_string, StringForwardingTable::Record * record) [inline], [private]
Definition at line 2737 of file mark-compact.cc.
                                                           {
    // If the string is already external, dispose the resource.
    if (IsExternalString(original_string)) {
      record->DisposeUnusedExternalResource(isolate_, original_string);
      return;
    }
    bool is_one_byte;
    v8::String::ExternalStringResourceBase* external_resource =
        record->external_resource(&is_one_byte);
    if (external_resource == nullptr) return;
    if (is_one_byte) {
      original_string->MakeExternalDuringGC(
          isolate_,
          reinterpret_cast<v8::String::ExternalOneByteStringResource*>(
              external_resource));
    } else {
      original_string->MakeExternalDuringGC(
          isolate_, reinterpret_cast<v8::String::ExternalStringResource*>(
                        external_resource));
    }
  }
References v8::internal::StringForwardingTable::Record::DisposeUnusedExternalResource(), v8::internal::StringForwardingTable::Record::external_resource(), and v8::internal::InstanceTypeChecker::IsExternalString().
TryInternalize()
void v8::internal::FullStringForwardingTableCleaner::TryInternalize (Tagged< String > original_string, StringForwardingTable::Record * record) [inline], [private]
Definition at line 2762 of file mark-compact.cc.
                                                           {
    if (IsInternalizedString(original_string)) return;
    Tagged<Object> forward = record->ForwardStringObjectOrHash(isolate_);
    if (!IsHeapObject(forward)) {
      return;
    }
    Tagged<String> forward_string = Cast<String>(forward);
    // Mark the forwarded string to keep it alive.
    if (MarkingHelper::GetLivenessMode(heap_, forward_string) !=
        MarkingHelper::LivenessMode::kAlwaysLive) {
      marking_state_->TryMarkAndAccountLiveBytes(forward_string);
    }
    // Transition the original string to a ThinString and override the
    // forwarding index with the correct hash.
    original_string->MakeThin(isolate_, forward_string);
    // Record the slot in the old-to-old remembered set. This is
    // required as the internalized string could be relocated during
    // compaction.
    ObjectSlot slot(&Cast<ThinString>(original_string)->actual_);
    MarkCompactCollector::RecordSlot(original_string, slot, forward_string);
  }
References v8::internal::StringForwardingTable::Record::ForwardStringObjectOrHash(), v8::internal::InstanceTypeChecker::IsHeapObject(), and v8::internal::InstanceTypeChecker::IsInternalizedString().
Member Data Documentation
heap_
Heap* const v8::internal::FullStringForwardingTableCleaner::heap_ [private]
Definition at line 2786 of file mark-compact.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc