v8::internal::IdentityMapBase Class Reference
#include <identity-map.h>
Public Member Functions
IdentityMapBase (const IdentityMapBase &)=delete
IdentityMapBase & operator= (const IdentityMapBase &)=delete
bool empty () const
int size () const
int capacity () const
bool is_iterable () const
Protected Types
using RawEntry = uintptr_t *
Protected Member Functions
IdentityMapBase (Heap *heap)
virtual ~IdentityMapBase ()
IdentityMapFindResult< uintptr_t > FindOrInsertEntry (Address key)
RawEntry FindEntry (Address key) const
RawEntry InsertEntry (Address key)
bool DeleteEntry (Address key, uintptr_t *deleted_value)
void Clear ()
Address KeyAtIndex (int index) const
RawEntry EntryAtIndex (int index) const
int NextIndex (int index) const
void EnableIteration ()
void DisableIteration ()
virtual uintptr_t * NewPointerArray (size_t length, uintptr_t value)=0
virtual void DeletePointerArray (uintptr_t *array, size_t length)=0
Private Member Functions
std::pair< int, bool > ScanKeysFor (Address address, uint32_t hash) const
std::pair< int, bool > InsertKey (Address address, uint32_t hash)
int Lookup (Address key) const
std::pair< int, bool > LookupOrInsert (Address key)
bool DeleteIndex (int index, uintptr_t *deleted_value)
void Rehash ()
void Resize (int new_capacity)
uint32_t Hash (Address address) const
bool ShouldGrow () const
Private Attributes
base::hash< uintptr_t > hasher_
Heap * heap_
int gc_counter_
int size_
int capacity_
int mask_
Address * keys_
StrongRootsEntry * strong_roots_entry_
uintptr_t * values_
bool is_iterable_
Friends
class IdentityMapTester
Detailed Description
Definition at line 29 of file identity-map.h.
Member Typedef Documentation
RawEntry
using v8::internal::IdentityMapBase::RawEntry = uintptr_t* [protected]
Definition at line 43 of file identity-map.h.
Constructor & Destructor Documentation
IdentityMapBase() [1/2]
v8::internal::IdentityMapBase::IdentityMapBase (const IdentityMapBase &) [delete]
IdentityMapBase() [2/2]
v8::internal::IdentityMapBase::IdentityMapBase (Heap * heap) [inline], [explicit], [protected]
Definition at line 45 of file identity-map.h.
      : heap_(heap),
        gc_counter_(-1),
        size_(0),
        capacity_(0),
        mask_(0),
        keys_(nullptr),
        strong_roots_entry_(nullptr),
        values_(nullptr),
        is_iterable_(false) {}
 IdentityMapBase()
v8::internal::IdentityMapBase::~IdentityMapBase () [protected], [virtual]
Definition at line 18 of file identity-map.cc.
                                  {
  // Clear must be called by the subclass to avoid calling the virtual
  // DeleteArray function from the destructor.
  DCHECK_NULL(keys_);
}
References DCHECK_NULL, and keys_.
Member Function Documentation
capacity()
int v8::internal::IdentityMapBase::capacity () const [inline]
Definition at line 35 of file identity-map.h.
{ return capacity_; }
Clear()
void v8::internal::IdentityMapBase::Clear () [protected]
Definition at line 24 of file identity-map.cc.
                            {
  if (keys_) {
    DCHECK(!is_iterable());
    DCHECK_NOT_NULL(strong_roots_entry_);
    heap_->UnregisterStrongRoots(strong_roots_entry_);
    DeletePointerArray(reinterpret_cast<uintptr_t*>(keys_), capacity_);
    DeletePointerArray(values_, capacity_);
    keys_ = nullptr;
    strong_roots_entry_ = nullptr;
    values_ = nullptr;
    size_ = 0;
    capacity_ = 0;
    mask_ = 0;
  }
}
References capacity_, v8::internal::DCHECK(), DCHECK_NOT_NULL, DeletePointerArray(), heap_, is_iterable(), keys_, mask_, size_, strong_roots_entry_, v8::internal::Heap::UnregisterStrongRoots(), and values_.
Referenced by v8::internal::IdentityMap< V, AllocationPolicy >::Clear().
DeleteEntry()
bool v8::internal::IdentityMapBase::DeleteEntry (Address key, uintptr_t * deleted_value) [protected]
Definition at line 251 of file identity-map.cc.
                                                                       {
  CHECK(!is_iterable()); // Don't allow deletion by key while iterable.
  if (size_ == 0) return false;
  int index = Lookup(key);
  if (index < 0) return false; // No entry found.
  return DeleteIndex(index, deleted_value);
}
References CHECK, DeleteIndex(), v8::internal::index, is_iterable(), v8::internal::key, Lookup(), and size_.
Referenced by v8::internal::IdentityMap< V, AllocationPolicy >::Delete().
DeleteIndex()
bool v8::internal::IdentityMapBase::DeleteIndex (int index, uintptr_t * deleted_value) [private]
Definition at line 99 of file identity-map.cc.
                                                                     {
  DCHECK_NE(heap_->gc_state(), Heap::MARK_COMPACT);
  if (deleted_value != nullptr) *deleted_value = values_[index];
  Address not_mapped = ReadOnlyRoots(heap_).not_mapped_symbol().ptr();
  DCHECK_NE(keys_[index], not_mapped);
  keys_[index] = not_mapped;
  values_[index] = 0;
  size_--;
  DCHECK_GE(size_, 0);
  if (capacity_ > kInitialIdentityMapSize &&
      size_ * kResizeFactor < capacity_ / kResizeFactor) {
    Resize(capacity_ / kResizeFactor);
    return true; // No need to fix collisions as resize reinserts keys.
  }
  // Move any collisions to their new correct location.
  int next_index = index;
  for (;;) {
    next_index = (next_index + 1) & mask_;
    Address key = keys_[next_index];
    if (key == not_mapped) break;
    int expected_index = Hash(key) & mask_;
    if (index < next_index) {
      if (index < expected_index && expected_index <= next_index) continue;
    } else {
      DCHECK_GT(index, next_index);
      if (index < expected_index || expected_index <= next_index) continue;
    }
    DCHECK_EQ(not_mapped, keys_[index]);
    DCHECK_EQ(values_[index], 0);
    std::swap(keys_[index], keys_[next_index]);
    std::swap(values_[index], values_[next_index]);
    index = next_index;
  }
  return true;
}
References capacity_, DCHECK_EQ, DCHECK_GE, DCHECK_GT, DCHECK_NE, v8::internal::Heap::gc_state(), Hash(), heap_, v8::internal::index, v8::internal::key, keys_, v8::internal::kInitialIdentityMapSize, v8::internal::kResizeFactor, v8::internal::Heap::MARK_COMPACT, mask_, Resize(), size_, and values_.
Referenced by DeleteEntry().
DeletePointerArray()
virtual void v8::internal::IdentityMapBase::DeletePointerArray (uintptr_t * array, size_t length) [protected], [pure virtual]
Implemented in v8::internal::IdentityMap< V, AllocationPolicy >, v8::internal::IdentityMap< int, v8::base::DefaultAllocationPolicy >, v8::internal::IdentityMap< v8::internal::SerializerReference, v8::base::DefaultAllocationPolicy >, v8::internal::IdentityMap< uint32_t, v8::internal::ZoneAllocationPolicy >, v8::internal::IdentityMap< uint32_t, FreeStoreAllocationPolicy >, and v8::internal::IdentityMap< PendingObjectReferences, v8::base::DefaultAllocationPolicy >.
Referenced by Clear(), and Resize().
DisableIteration()
void v8::internal::IdentityMapBase::DisableIteration () [protected]
Definition at line 45 of file identity-map.cc.
                                       {
  CHECK(is_iterable());
  is_iterable_ = false;
}
References CHECK, is_iterable(), and is_iterable_.
empty()
bool v8::internal::IdentityMapBase::empty () const [inline]
Definition at line 33 of file identity-map.h.
{ return size_ == 0; }
Referenced by v8::internal::BuiltinsConstantsTableBuilder::Finalize().
EnableIteration()
void v8::internal::IdentityMapBase::EnableIteration () [protected]
Definition at line 40 of file identity-map.cc.
                                      {
  CHECK(!is_iterable());
  is_iterable_ = true;
}
References CHECK, is_iterable(), and is_iterable_.
EntryAtIndex()
IdentityMapBase::RawEntry v8::internal::IdentityMapBase::EntryAtIndex (int index) const [protected]
Definition at line 267 of file identity-map.cc.
                                                                     {
  DCHECK_LE(0, index);
  DCHECK_LT(index, capacity_);
  DCHECK_NE(keys_[index], ReadOnlyRoots(heap_).not_mapped_symbol().ptr());
  CHECK(is_iterable()); // Must be iterable to access by index;
  return &values_[index];
}
References capacity_, CHECK, DCHECK_LE, DCHECK_LT, DCHECK_NE, heap_, v8::internal::index, is_iterable(), keys_, and values_.
Referenced by v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::entry().
FindEntry()
IdentityMapBase::RawEntry v8::internal::IdentityMapBase::FindEntry (Address key) const [protected]
Definition at line 207 of file identity-map.cc.
                                                                    {
  DCHECK_NE(heap_->gc_state(), Heap::MARK_COMPACT);
  // Don't allow find by key while iterable (might rehash).
  CHECK(!is_iterable());
  if (size_ == 0) return nullptr;
  int index = Lookup(key);
  return index >= 0 ? &values_[index] : nullptr;
}
References CHECK, DCHECK_NE, v8::internal::Heap::gc_state(), heap_, v8::internal::index, is_iterable(), v8::internal::key, Lookup(), v8::internal::Heap::MARK_COMPACT, size_, and values_.
Referenced by v8::internal::IdentityMap< V, AllocationPolicy >::Find().
FindOrInsertEntry()
IdentityMapFindResult< uintptr_t > v8::internal::IdentityMapBase::FindOrInsertEntry (Address key) [protected]
Definition at line 192 of file identity-map.cc.
                 {
  DCHECK_NE(heap_->gc_state(), Heap::MARK_COMPACT);
  CHECK(!is_iterable()); // Don't allow insertion while iterable.
  if (capacity_ == 0) {
    return {InsertEntry(key), false};
  }
  auto lookup_result = LookupOrInsert(key);
  return {&values_[lookup_result.first], lookup_result.second};
}
References capacity_, CHECK, DCHECK_NE, v8::internal::Heap::gc_state(), heap_, InsertEntry(), is_iterable(), v8::internal::key, LookupOrInsert(), v8::internal::Heap::MARK_COMPACT, and values_.
Referenced by v8::internal::IdentityMap< V, AllocationPolicy >::FindOrInsert().
Hash()
uint32_t v8::internal::IdentityMapBase::Hash (Address address) const [private]
Definition at line 183 of file identity-map.cc.
                                                    {
  CHECK_NE(address, ReadOnlyRoots(heap_).not_mapped_symbol().ptr());
  return static_cast<uint32_t>(hasher_(address));
}
References CHECK_NE, hasher_, and heap_.
Referenced by DeleteIndex(), InsertEntry(), Lookup(), LookupOrInsert(), Rehash(), and Resize().
InsertEntry()
IdentityMapBase::RawEntry v8::internal::IdentityMapBase::InsertEntry (Address key) [protected]
Definition at line 218 of file identity-map.cc.
                                                                {
  DCHECK_NE(heap_->gc_state(), Heap::MARK_COMPACT);
  // Don't allow find by key while iterable (might rehash).
  CHECK(!is_iterable());
  if (capacity_ == 0) {
    // Allocate the initial storage for keys and values.
    capacity_ = kInitialIdentityMapSize;
    mask_ = kInitialIdentityMapSize - 1;
    gc_counter_ = heap_->gc_count();
    uintptr_t not_mapped = ReadOnlyRoots(heap_).not_mapped_symbol().ptr();
    keys_ = reinterpret_cast<Address*>(NewPointerArray(capacity_, not_mapped));
    for (int i = 0; i < capacity_; i++) keys_[i] = not_mapped;
    values_ = NewPointerArray(capacity_, 0);
    strong_roots_entry_ =
        heap_->RegisterStrongRoots("IdentityMapBase", FullObjectSlot(keys_),
                                   FullObjectSlot(keys_ + capacity_));
  } else {
    // Rehash if there was a GC, then insert.
    if (gc_counter_ != heap_->gc_count()) Rehash();
  }
  int index;
  bool already_exists;
  std::tie(index, already_exists) = InsertKey(key, Hash(key));
  DCHECK(!already_exists);
  return &values_[index];
}
References capacity_, CHECK, v8::internal::DCHECK(), DCHECK_NE, v8::internal::Heap::gc_count(), gc_counter_, v8::internal::Heap::gc_state(), Hash(), heap_, v8::internal::index, InsertKey(), is_iterable(), v8::internal::key, keys_, v8::internal::kInitialIdentityMapSize, v8::internal::Heap::MARK_COMPACT, mask_, NewPointerArray(), v8::internal::Heap::RegisterStrongRoots(), Rehash(), strong_roots_entry_, and values_.
Referenced by FindOrInsertEntry(), and v8::internal::IdentityMap< V, AllocationPolicy >::Insert().
InsertKey()
std::pair< int, bool > v8::internal::IdentityMapBase::InsertKey (Address address, uint32_t hash) [private]
Definition at line 70 of file identity-map.cc.
                                                               {
  DCHECK_NE(heap_->gc_state(), Heap::MARK_COMPACT);
  DCHECK_EQ(gc_counter_, heap_->gc_count());
  if (ShouldGrow()) {
    Resize(capacity_ * kResizeFactor);
  }
  Address not_mapped = ReadOnlyRoots(heap_).not_mapped_symbol().ptr();
  int start = hash & mask_;
  // Guaranteed to terminate since size_ < capacity_, there must be at least
  // one empty slot.
  int index = start;
  while (true) {
    if (keys_[index] == address) return {index, true}; // Found.
    if (keys_[index] == not_mapped) { // Free entry.
      size_++;
      DCHECK_LE(size_, capacity_);
      keys_[index] = address;
      return {index, false};
    }
    index = (index + 1) & mask_;
    // We should never loop back to the start.
    DCHECK_NE(index, start);
  }
}
References capacity_, DCHECK_EQ, DCHECK_LE, DCHECK_NE, v8::internal::Heap::gc_count(), gc_counter_, v8::internal::Heap::gc_state(), heap_, v8::internal::index, keys_, v8::internal::kResizeFactor, v8::internal::Heap::MARK_COMPACT, mask_, Resize(), ShouldGrow(), and size_.
Referenced by InsertEntry(), LookupOrInsert(), Rehash(), and Resize().
is_iterable()
bool v8::internal::IdentityMapBase::is_iterable () const [inline]
Definition at line 36 of file identity-map.h.
{ return is_iterable_; }
Referenced by Clear(), DeleteEntry(), DisableIteration(), EnableIteration(), EntryAtIndex(), FindEntry(), FindOrInsertEntry(), InsertEntry(), KeyAtIndex(), NextIndex(), Rehash(), and Resize().
KeyAtIndex()
Address v8::internal::IdentityMapBase::KeyAtIndex (int index) const [protected]
Definition at line 259 of file identity-map.cc.
                                                   {
  DCHECK_LE(0, index);
  DCHECK_LT(index, capacity_);
  DCHECK_NE(keys_[index], ReadOnlyRoots(heap_).not_mapped_symbol().ptr());
  CHECK(is_iterable()); // Must be iterable to access by index;
  return keys_[index];
}
References capacity_, CHECK, DCHECK_LE, DCHECK_LT, DCHECK_NE, heap_, v8::internal::index, is_iterable(), and keys_.
Referenced by v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::key().
Lookup()
int v8::internal::IdentityMapBase::Lookup (Address key) const [private]
Definition at line 140 of file identity-map.cc.
                                             {
  DCHECK_NE(heap_->gc_state(), Heap::MARK_COMPACT);
  uint32_t hash = Hash(key);
  int index;
  bool found;
  std::tie(index, found) = ScanKeysFor(key, hash);
  if (!found && gc_counter_ != heap_->gc_count()) {
    // Miss; rehash if there was a GC, then lookup again.
    const_cast<IdentityMapBase*>(this)->Rehash();
    std::tie(index, found) = ScanKeysFor(key, hash);
  }
  return found ? index : -1;
}
References DCHECK_NE, v8::internal::Heap::gc_count(), gc_counter_, v8::internal::Heap::gc_state(), Hash(), heap_, v8::internal::index, v8::internal::key, v8::internal::Heap::MARK_COMPACT, Rehash(), and ScanKeysFor().
Referenced by DeleteEntry(), and FindEntry().
LookupOrInsert()
std::pair< int, bool > v8::internal::IdentityMapBase::LookupOrInsert (Address key) [private]
Definition at line 154 of file identity-map.cc.
                                                              {
  DCHECK_NE(heap_->gc_state(), Heap::MARK_COMPACT);
  uint32_t hash = Hash(key);
  // Perform an optimistic lookup.
  int index;
  bool already_exists;
  std::tie(index, already_exists) = ScanKeysFor(key, hash);
  if (!already_exists) {
    // Miss; rehash if there was a GC, then insert.
    if (gc_counter_ != heap_->gc_count()) {
      Rehash();
      index = -1;
    }
    if (index < 0 || ShouldGrow()) {
      std::tie(index, already_exists) = InsertKey(key, hash);
    } else {
      // If rehashing is not necessary, and the table is already big enough,
      // then avoid calling InsertKey because it would search the table again
      // and we already found an adequate location to insert the new key.
      size_++;
      DCHECK_LE(size_, capacity_);
      DCHECK_EQ(keys_[index], ReadOnlyRoots(heap_).not_mapped_symbol().ptr());
      keys_[index] = key;
    }
  }
  DCHECK_GE(index, 0);
  return {index, already_exists};
}
References capacity_, DCHECK_EQ, DCHECK_GE, DCHECK_LE, DCHECK_NE, v8::internal::Heap::gc_count(), gc_counter_, v8::internal::Heap::gc_state(), Hash(), heap_, v8::internal::index, InsertKey(), v8::internal::key, keys_, v8::internal::Heap::MARK_COMPACT, Rehash(), ScanKeysFor(), ShouldGrow(), and size_.
Referenced by FindOrInsertEntry().
NewPointerArray()
virtual uintptr_t* v8::internal::IdentityMapBase::NewPointerArray (size_t length, uintptr_t value) [protected], [pure virtual]
Implemented in v8::internal::IdentityMap< V, AllocationPolicy >, v8::internal::IdentityMap< int, v8::base::DefaultAllocationPolicy >, v8::internal::IdentityMap< v8::internal::SerializerReference, v8::base::DefaultAllocationPolicy >, v8::internal::IdentityMap< uint32_t, v8::internal::ZoneAllocationPolicy >, v8::internal::IdentityMap< uint32_t, FreeStoreAllocationPolicy >, and v8::internal::IdentityMap< PendingObjectReferences, v8::base::DefaultAllocationPolicy >.
Referenced by InsertEntry(), and Resize().
NextIndex()
int v8::internal::IdentityMapBase::NextIndex (int index) const [protected]
Definition at line 275 of file identity-map.cc.
                                              {
  DCHECK_LE(-1, index);
  DCHECK_LE(index, capacity_);
  CHECK(is_iterable()); // Must be iterable to access by index;
  Address not_mapped = ReadOnlyRoots(heap_).not_mapped_symbol().ptr();
  for (++index; index < capacity_; ++index) {
    if (keys_[index] != not_mapped) {
      return index;
    }
  }
  return capacity_;
}
References capacity_, CHECK, DCHECK_LE, heap_, v8::internal::index, is_iterable(), and keys_.
Referenced by v8::internal::IdentityMap< V, AllocationPolicy >::Iterator::operator++().
operator=()
IdentityMapBase& v8::internal::IdentityMapBase::operator= (const IdentityMapBase &) [delete]
Rehash()
void v8::internal::IdentityMapBase::Rehash () [private]
Definition at line 288 of file identity-map.cc.
                             {
  DCHECK_NE(heap_->gc_state(), Heap::MARK_COMPACT);
  CHECK(!is_iterable()); // Can't rehash while iterating.
  // Record the current GC counter.
  gc_counter_ = heap_->gc_count();
  // Assume that most objects won't be moved.
  std::vector<std::pair<Address, uintptr_t>> reinsert;
  // Search the table looking for keys that wouldn't be found with their
  // current hashcode and evacuate them.
  int last_empty = -1;
  Address not_mapped = ReadOnlyRoots(heap_).not_mapped_symbol().ptr();
  for (int i = 0; i < capacity_; i++) {
    if (keys_[i] == not_mapped) {
      last_empty = i;
    } else {
      int pos = Hash(keys_[i]) & mask_;
      if (pos <= last_empty || pos > i) {
        // Evacuate an entry that is in the wrong place.
        reinsert.push_back(std::pair<Address, uintptr_t>(keys_[i], values_[i]));
        keys_[i] = not_mapped;
        values_[i] = 0;
        last_empty = i;
        size_--;
      }
    }
  }
  // Reinsert all the key/value pairs that were in the wrong place.
  for (auto pair : reinsert) {
    int index = InsertKey(pair.first, Hash(pair.first)).first;
    DCHECK_GE(index, 0);
    values_[index] = pair.second;
  }
}
References capacity_, CHECK, DCHECK_GE, DCHECK_NE, v8::internal::Heap::gc_count(), gc_counter_, v8::internal::Heap::gc_state(), Hash(), heap_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, InsertKey(), is_iterable(), keys_, v8::internal::Heap::MARK_COMPACT, mask_, size_, and values_.
Referenced by InsertEntry(), Lookup(), and LookupOrInsert().
Resize()
void v8::internal::IdentityMapBase::Resize (int new_capacity) [private]
Definition at line 322 of file identity-map.cc.
                                             {
  DCHECK_NE(heap_->gc_state(), Heap::MARK_COMPACT);
  CHECK(!is_iterable()); // Can't resize while iterating.
  // Resize the internal storage and reinsert all the key/value pairs.
  DCHECK_GT(new_capacity, size_);
  int old_capacity = capacity_;
  Address* old_keys = keys_;
  uintptr_t* old_values = values_;
  capacity_ = new_capacity;
  mask_ = capacity_ - 1;
  gc_counter_ = heap_->gc_count();
  size_ = 0;
  Address not_mapped = ReadOnlyRoots(heap_).not_mapped_symbol().ptr();
  keys_ = reinterpret_cast<Address*>(NewPointerArray(capacity_, not_mapped));
  values_ = NewPointerArray(capacity_, 0);
  for (int i = 0; i < old_capacity; i++) {
    if (old_keys[i] == not_mapped) continue;
    int index = InsertKey(old_keys[i], Hash(old_keys[i])).first;
    DCHECK_GE(index, 0);
    values_[index] = old_values[i];
  }
  // Unregister old keys and register new keys.
  DCHECK_NOT_NULL(strong_roots_entry_);
  heap_->UpdateStrongRoots(strong_roots_entry_, FullObjectSlot(keys_),
                           FullObjectSlot(keys_ + capacity_));
  // Delete old storage;
  DeletePointerArray(reinterpret_cast<uintptr_t*>(old_keys), old_capacity);
  DeletePointerArray(old_values, old_capacity);
}
References capacity_, CHECK, DCHECK_GE, DCHECK_GT, DCHECK_NE, DCHECK_NOT_NULL, DeletePointerArray(), v8::internal::Heap::gc_count(), gc_counter_, v8::internal::Heap::gc_state(), Hash(), heap_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, InsertKey(), is_iterable(), keys_, v8::internal::Heap::MARK_COMPACT, mask_, NewPointerArray(), size_, strong_roots_entry_, v8::internal::Heap::UpdateStrongRoots(), and values_.
Referenced by DeleteIndex(), and InsertKey().
ScanKeysFor()
std::pair< int, bool > v8::internal::IdentityMapBase::ScanKeysFor (Address address, uint32_t hash) const [private]
Definition at line 50 of file identity-map.cc.
                                                                       {
  int start = hash & mask_;
  Address not_mapped = ReadOnlyRoots(heap_).not_mapped_symbol().ptr();
  for (int index = start; index < capacity_; index++) {
    if (keys_[index] == address) return {index, true}; // Found.
    if (keys_[index] == not_mapped) return {index, false}; // Not found.
  }
  for (int index = 0; index < start; index++) {
    if (keys_[index] == address) return {index, true}; // Found.
    if (keys_[index] == not_mapped) return {index, false}; // Not found.
  }
  return {-1, false};
}
References capacity_, heap_, v8::internal::index, keys_, and mask_.
Referenced by Lookup(), and LookupOrInsert().
ShouldGrow()
bool v8::internal::IdentityMapBase::ShouldGrow () const [private]
Definition at line 65 of file identity-map.cc.
                                       {
  // Grow the map if we reached >= 80% occupancy.
  return size_ + size_ / 4 >= capacity_;
}
References capacity_, and size_.
Referenced by InsertKey(), and LookupOrInsert().
size()
int v8::internal::IdentityMapBase::size () const [inline]
Definition at line 34 of file identity-map.h.
{ return size_; }
Referenced by v8::internal::BuiltinsConstantsTableBuilder::AddObject(), and v8::internal::BuiltinsConstantsTableBuilder::Finalize().
Friends And Related Function Documentation
IdentityMapTester
friend class IdentityMapTester [friend]
Definition at line 41 of file identity-map.h.
Member Data Documentation
capacity_
int v8::internal::IdentityMapBase::capacity_ [private]
Definition at line 94 of file identity-map.h.
Referenced by Clear(), DeleteIndex(), EntryAtIndex(), FindOrInsertEntry(), InsertEntry(), InsertKey(), KeyAtIndex(), LookupOrInsert(), NextIndex(), Rehash(), Resize(), ScanKeysFor(), and ShouldGrow().
gc_counter_
int v8::internal::IdentityMapBase::gc_counter_ [private]
Definition at line 92 of file identity-map.h.
Referenced by InsertEntry(), InsertKey(), Lookup(), LookupOrInsert(), Rehash(), and Resize().
hasher_
base::hash<uintptr_t> v8::internal::IdentityMapBase::hasher_ [private]
Definition at line 90 of file identity-map.h.
Referenced by Hash().
heap_
Heap* v8::internal::IdentityMapBase::heap_ [private]
Definition at line 91 of file identity-map.h.
Referenced by Clear(), DeleteIndex(), EntryAtIndex(), FindEntry(), FindOrInsertEntry(), Hash(), InsertEntry(), InsertKey(), KeyAtIndex(), Lookup(), LookupOrInsert(), NextIndex(), Rehash(), Resize(), and ScanKeysFor().
is_iterable_
bool v8::internal::IdentityMapBase::is_iterable_ [private]
Definition at line 99 of file identity-map.h.
Referenced by DisableIteration(), and EnableIteration().
keys_
Address* v8::internal::IdentityMapBase::keys_ [private]
Definition at line 96 of file identity-map.h.
Referenced by Clear(), DeleteIndex(), EntryAtIndex(), InsertEntry(), InsertKey(), KeyAtIndex(), LookupOrInsert(), NextIndex(), Rehash(), Resize(), ScanKeysFor(), and ~IdentityMapBase().
mask_
int v8::internal::IdentityMapBase::mask_ [private]
Definition at line 95 of file identity-map.h.
Referenced by Clear(), DeleteIndex(), InsertEntry(), InsertKey(), Rehash(), Resize(), and ScanKeysFor().
size_
int v8::internal::IdentityMapBase::size_ [private]
Definition at line 93 of file identity-map.h.
Referenced by Clear(), DeleteEntry(), DeleteIndex(), FindEntry(), InsertKey(), LookupOrInsert(), Rehash(), Resize(), and ShouldGrow().
strong_roots_entry_
StrongRootsEntry* v8::internal::IdentityMapBase::strong_roots_entry_ [private]
Definition at line 97 of file identity-map.h.
Referenced by Clear(), InsertEntry(), and Resize().
values_
uintptr_t* v8::internal::IdentityMapBase::values_ [private]
Definition at line 98 of file identity-map.h.
Referenced by Clear(), DeleteIndex(), EntryAtIndex(), FindEntry(), FindOrInsertEntry(), InsertEntry(), Rehash(), and Resize().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/utils/identity-map.h
/mnt/V8SourceCode/src/utils/identity-map.cc