v8::internal::IteratorBuiltinsAssembler Class Reference
#include <builtins-iterator-gen.h>
Public Types
using IteratorRecord = TorqueStructIteratorRecord
Public Member Functions
IteratorBuiltinsAssembler (compiler::CodeAssemblerState *state)
TNode< JSAny > GetIteratorMethod (TNode< Context > context, TNode< JSAny >)
IteratorRecord GetIterator (TNode< Context > context, TNode< JSAny > object)
IteratorRecord GetIterator (TNode< Context > context, TNode< JSAny > object, TNode< Object > method)
TNode< JSReceiver > IteratorStep (TNode< Context > context, const IteratorRecord &iterator, Label *if_done, std::optional< TNode< Map >> fast_iterator_result_map=std::nullopt)
TNode< JSReceiver > IteratorStep (TNode< Context > context, const IteratorRecord &iterator, std::optional< TNode< Map >> fast_iterator_result_map, Label *if_done)
void IteratorComplete (TNode< Context > context, const TNode< JSAnyNotSmi > iterator, Label *if_done, std::optional< TNode< Map >> fast_iterator_result_map=std::nullopt)
void IteratorComplete (TNode< Context > context, const TNode< JSAnyNotSmi > iterator, std::optional< TNode< Map >> fast_iterator_result_map, Label *if_done)
TNode< JSAny > IteratorValue (TNode< Context > context, TNode< JSReceiver > result, std::optional< TNode< Map >> fast_iterator_result_map=std::nullopt)
void Iterate (TNode< Context > context, TNode< JSAny > iterable, std::function< void(TNode< Object >)> func, std::initializer_list< compiler::CodeAssemblerVariable * > merged_variables={})
void Iterate (TNode< Context > context, TNode< JSAny > iterable, TNode< Object > iterable_fn, std::function< void(TNode< Object >)> func, std::initializer_list< compiler::CodeAssemblerVariable * > merged_variables={})
TNode< JSArray > IterableToList (TNode< Context > context, TNode< JSAny > iterable, TNode< Object > iterator_fn)
TNode< FixedArray > IterableToFixedArray (TNode< Context > context, TNode< JSAny > iterable, TNode< Object > iterator_fn)
void FillFixedArrayFromIterable (TNode< Context > context, TNode< JSAny > iterable, TNode< Object > iterator_fn, GrowableFixedArray *values)
TNode< FixedArray > StringListFromIterable (TNode< Context > context, TNode< JSAny > iterable)
void FastIterableToList (TNode< Context > context, TNode< JSAny > iterable, TVariable< JSArray > *var_result, Label *slow)
TNode< JSArray > FastIterableToList (TNode< Context > context, TNode< JSAny > iterable, Label *slow)
Additional Inherited Members
Detailed Description
Definition at line 16 of file builtins-iterator-gen.h.
Member Typedef Documentation
IteratorRecord
using v8::internal::IteratorBuiltinsAssembler::IteratorRecord = TorqueStructIteratorRecord
Definition at line 21 of file builtins-iterator-gen.h.
Constructor & Destructor Documentation
IteratorBuiltinsAssembler()
v8::internal::IteratorBuiltinsAssembler::IteratorBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 18 of file builtins-iterator-gen.h.
      : CodeStubAssembler(state) {}
Member Function Documentation
FastIterableToList() [1/2]
TNode< JSArray > v8::internal::IteratorBuiltinsAssembler::FastIterableToList (TNode< Context > context, TNode< JSAny > iterable, Label * slow)
Definition at line 458 of file builtins-iterator-gen.cc.
                                                                {
  TVARIABLE(JSArray, var_fast_result);
  FastIterableToList(context, iterable, &var_fast_result, slow);
  return var_fast_result.value();
}
References FastIterableToList().
FastIterableToList() [2/2]
void v8::internal::IteratorBuiltinsAssembler::FastIterableToList (TNode< Context > context, TNode< JSAny > iterable, TVariable< JSArray > * var_result, Label * slow)
Definition at line 395 of file builtins-iterator-gen.cc.
                                                 {
  Label done(this), check_string(this), check_map(this), check_set(this);
  // Always call the `next()` builtins when the debugger is
  // active, to ensure we capture side-effects correctly.
  GotoIf(IsDebugActive(), slow);
  GotoIfNot(
      Word32Or(IsFastJSArrayWithNoCustomIteration(context, iterable),
               IsFastJSArrayForReadWithNoCustomIteration(context, iterable)),
      &check_string);
  // Fast path for fast JSArray.
  *var_result = CAST(
      CallBuiltin(Builtin::kCloneFastJSArrayFillingHoles, context, iterable));
  Goto(&done);
  BIND(&check_string);
  {
    Label string_maybe_fast_call(this);
    StringBuiltinsAssembler string_assembler(state());
    string_assembler.BranchIfStringPrimitiveWithNoCustomIteration(
        iterable, context, &string_maybe_fast_call, &check_map);
    BIND(&string_maybe_fast_call);
    const TNode<Uint32T> length = LoadStringLengthAsWord32(CAST(iterable));
    // Use string length as conservative approximation of number of codepoints.
    GotoIf(
        Uint32GreaterThan(length, Uint32Constant(JSArray::kMaxFastArrayLength)),
        slow);
    *var_result = CAST(CallBuiltin(Builtin::kStringToList, context, iterable));
    Goto(&done);
  }
  BIND(&check_map);
  {
    Label map_fast_call(this);
    BranchIfIterableWithOriginalKeyOrValueMapIterator(
        state(), iterable, context, &map_fast_call, &check_set);
    BIND(&map_fast_call);
    *var_result =
        CAST(CallBuiltin(Builtin::kMapIteratorToList, context, iterable));
    Goto(&done);
  }
  BIND(&check_set);
  {
    Label set_fast_call(this);
    BranchIfIterableWithOriginalValueSetIterator(state(), iterable, context,
                                                 &set_fast_call, slow);
    BIND(&set_fast_call);
    *var_result =
        CAST(CallBuiltin(Builtin::kSetOrSetIteratorToList, context, iterable));
    Goto(&done);
  }
  BIND(&done);
}
References v8::internal::BranchIfIterableWithOriginalKeyOrValueMapIterator(), v8::internal::BranchIfIterableWithOriginalValueSetIterator(), v8::internal::StringBuiltinsAssembler::BranchIfStringPrimitiveWithNoCustomIteration(), v8::internal::compiler::CodeAssembler::CallBuiltin(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::IsDebugActive(), v8::internal::JSArray::kMaxFastArrayLength, v8::internal::length, v8::internal::CodeStubAssembler::LoadStringLengthAsWord32(), v8::internal::compiler::CodeAssembler::state(), v8::internal::compiler::CodeAssembler::Uint32Constant(), and v8::internal::compiler::CodeAssembler::Word32Or().
Referenced by FastIterableToList().
FillFixedArrayFromIterable()
void v8::internal::IteratorBuiltinsAssembler::FillFixedArrayFromIterable (TNode< Context > context, TNode< JSAny > iterable, TNode< Object > iterator_fn, GrowableFixedArray * values)
Definition at line 217 of file builtins-iterator-gen.cc.
                                {
  // 1. Let iteratorRecord be ? GetIterator(items, method) (handled by Iterate).
  // 2. Let values be a new empty List.
  // The GrowableFixedArray has already been created. It's ok if we do this step
  // out of order, since creating an empty List is not observable.
  // 3. Let next be true. (handled by Iterate)
  // 4. Repeat, while next is not false (handled by Iterate)
  Iterate(context, iterable, iterator_fn,
          [&values](TNode<Object> value) {
            // Handled by Iterate:
            // a. Set next to ? IteratorStep(iteratorRecord).
            // b. If next is not false, then
            // i. Let nextValue be ? IteratorValue(next).
            // ii. Append nextValue to the end of the List values.
            values->Push(value);
          },
          {values->var_array(), values->var_capacity(), values->var_length()});
}
References Iterate(), v8::internal::GrowableFixedArray::Push(), v8::internal::value, v8::internal::GrowableFixedArray::var_array(), v8::internal::GrowableFixedArray::var_capacity(), and v8::internal::GrowableFixedArray::var_length().
Referenced by IterableToFixedArray(), and IterableToList().
GetIterator() [1/2]
IteratorRecord v8::internal::IteratorBuiltinsAssembler::GetIterator (TNode< Context > context, TNode< JSAny > object)
Definition at line 30 of file builtins-iterator-gen.cc.
                                                                           {
  TNode<Object> method = GetIteratorMethod(context, object);
  return GetIterator(context, object, method);
}
References GetIteratorMethod().
Referenced by v8::internal::BaseCollectionsAssembler::AddConstructorEntriesFromIterable(), and Iterate().
GetIterator() [2/2]
IteratorRecord v8::internal::IteratorBuiltinsAssembler::GetIterator (TNode< Context > context, TNode< JSAny > object, TNode< Object > method)
Definition at line 36 of file builtins-iterator-gen.cc.
                                                                            {
  Label if_not_callable(this, Label::kDeferred), if_callable(this);
  GotoIf(TaggedIsSmi(method), &if_not_callable);
  Branch(IsCallable(CAST(method)), &if_callable, &if_not_callable);
  BIND(&if_not_callable);
  CallRuntime(Runtime::kThrowIteratorError, context, object);
  Unreachable();
  BIND(&if_callable);
  {
    TNode<JSAny> iterator = Call(context, method, object);
    Label get_next(this), if_notobject(this, Label::kDeferred);
    GotoIf(TaggedIsSmi(iterator), &if_notobject);
    Branch(JSAnyIsNotPrimitive(CAST(iterator)), &get_next, &if_notobject);
    BIND(&if_notobject);
    CallRuntime(Runtime::kThrowSymbolIteratorInvalid, context);
    Unreachable();
    BIND(&get_next);
    TNode<JSAny> next =
        GetProperty(context, iterator, factory()->next_string());
    return IteratorRecord{TNode<JSReceiver>::UncheckedCast(iterator), next};
  }
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::CodeStubAssembler::Call(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::compiler::CodeAssembler::factory(), v8::internal::CodeStubAssembler::GetProperty(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::IsCallable(), v8::internal::CodeStubAssembler::JSAnyIsNotPrimitive(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::compiler::CodeAssembler::Unreachable().
GetIteratorMethod()
TNode< JSAny > v8::internal::IteratorBuiltinsAssembler::GetIteratorMethod (TNode< Context > context, TNode< JSAny > object)
Definition at line 25 of file builtins-iterator-gen.cc.
                                                 {
  return GetProperty(context, object, factory()->iterator_symbol());
}
References v8::internal::compiler::CodeAssembler::factory(), and v8::internal::CodeStubAssembler::GetProperty().
Referenced by GetIterator(), and Iterate().
IterableToFixedArray()
TNode< FixedArray > v8::internal::IteratorBuiltinsAssembler::IterableToFixedArray (TNode< Context > context, TNode< JSAny > iterable, TNode< Object > iterator_fn)
Definition at line 209 of file builtins-iterator-gen.cc.
                                                                              {
  GrowableFixedArray values(state());
  FillFixedArrayFromIterable(context, iterable, iterator_fn, &values);
  TNode<FixedArray> new_array = values.ToFixedArray();
  return new_array;
}
References FillFixedArrayFromIterable(), v8::internal::compiler::CodeAssembler::state(), and v8::internal::GrowableFixedArray::ToFixedArray().
IterableToList()
TNode< JSArray > v8::internal::IteratorBuiltinsAssembler::IterableToList (TNode< Context > context, TNode< JSAny > iterable, TNode< Object > iterator_fn)
Definition at line 202 of file builtins-iterator-gen.cc.
                                                                              {
  GrowableFixedArray values(state());
  FillFixedArrayFromIterable(context, iterable, iterator_fn, &values);
  return values.ToJSArray(context);
}
References FillFixedArrayFromIterable(), v8::internal::compiler::CodeAssembler::state(), and v8::internal::GrowableFixedArray::ToJSArray().
Iterate() [1/2]
void v8::internal::IteratorBuiltinsAssembler::Iterate (TNode< Context > context, TNode< JSAny > iterable, std::function< void(TNode< Object >)> func, std::initializer_list< compiler::CodeAssemblerVariable * > merged_variables = {})
Definition at line 153 of file builtins-iterator-gen.cc.
                                                                          {
  Iterate(context, iterable, GetIteratorMethod(context, iterable), func,
          merged_variables);
}
References GetIteratorMethod().
Referenced by FillFixedArrayFromIterable(), and StringListFromIterable().
Iterate() [2/2]
void v8::internal::IteratorBuiltinsAssembler::Iterate (TNode< Context > context, TNode< JSAny > iterable, TNode< Object > iterable_fn, std::function< void(TNode< Object >)> func, std::initializer_list< compiler::CodeAssemblerVariable * > merged_variables = {})
Definition at line 161 of file builtins-iterator-gen.cc.
                                                                          {
  Label done(this);
  IteratorRecord iterator_record = GetIterator(context, iterable, iterable_fn);
  Label if_exception(this, Label::kDeferred);
  TVARIABLE(Object, var_exception);
  Label loop_start(this, merged_variables);
  Goto(&loop_start);
  BIND(&loop_start);
  {
    TNode<JSReceiver> next = IteratorStep(context, iterator_record, &done);
    TNode<Object> next_value = IteratorValue(context, next);
    {
      compiler::ScopedExceptionHandler handler(this, &if_exception,
                                               &var_exception);
      func(next_value);
    }
    Goto(&loop_start);
  }
  BIND(&if_exception);
  {
    TNode<HeapObject> message = GetPendingMessage();
    SetPendingMessage(TheHoleConstant());
    IteratorCloseOnException(context, iterator_record.object);
    CallRuntime(Runtime::kReThrowWithMessage, context, var_exception.value(),
                message);
    Unreachable();
  }
  BIND(&done);
}
References v8::internal::compiler::CodeAssembler::CallRuntime(), GetIterator(), v8::internal::CodeStubAssembler::GetPendingMessage(), v8::internal::compiler::CodeAssembler::Goto(), IteratorStep(), IteratorValue(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::SetPendingMessage(), and v8::internal::compiler::CodeAssembler::Unreachable().
IteratorComplete() [1/2]
void v8::internal::IteratorBuiltinsAssembler::IteratorComplete (TNode< Context > context, const TNode< JSAnyNotSmi > iterator, Label * if_done, std::optional< TNode< Map >> fast_iterator_result_map = std::nullopt)
Definition at line 94 of file builtins-iterator-gen.cc.
                                                      {
  DCHECK_NOT_NULL(if_done);
  Label return_result(this);
  TNode<Map> result_map = LoadMap(iterator);
  if (fast_iterator_result_map) {
    // Fast iterator result case:
    Label if_generic(this);
    // 4. Return result.
    GotoIfNot(TaggedEqual(result_map, *fast_iterator_result_map), &if_generic);
    // 2. Return ToBoolean(? Get(iterResult, "done")).
    TNode<Object> done =
        LoadObjectField(iterator, JSIteratorResult::kDoneOffset);
    BranchIfToBooleanIsTrue(done, if_done, &return_result);
    BIND(&if_generic);
  }
  // Generic iterator result case:
  {
    // 2. Return ToBoolean(? Get(iterResult, "done")).
    TNode<JSAny> done =
        GetProperty(context, iterator, factory()->done_string());
    BranchIfToBooleanIsTrue(done, if_done, &return_result);
  }
  BIND(&return_result);
}
References v8::internal::CodeStubAssembler::BranchIfToBooleanIsTrue(), DCHECK_NOT_NULL, v8::internal::compiler::CodeAssembler::factory(), v8::internal::CodeStubAssembler::GetProperty(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadObjectField(), and v8::internal::CodeStubAssembler::TaggedEqual().
Referenced by IteratorComplete(), and IteratorStep().
IteratorComplete() [2/2]
void v8::internal::IteratorBuiltinsAssembler::IteratorComplete (TNode< Context > context, const TNode< JSAnyNotSmi > iterator, std::optional< TNode< Map >> fast_iterator_result_map, Label * if_done) [inline]
Definition at line 50 of file builtins-iterator-gen.h.
                                        {
    return IteratorComplete(context, iterator, if_done,
                            fast_iterator_result_map);
  }
References IteratorComplete().
IteratorStep() [1/2]
TNode< JSReceiver > v8::internal::IteratorBuiltinsAssembler::IteratorStep (TNode< Context > context, const IteratorRecord & iterator, Label * if_done, std::optional< TNode< Map >> fast_iterator_result_map = std::nullopt)
Definition at line 66 of file builtins-iterator-gen.cc.
                                                      {
  DCHECK_NOT_NULL(if_done);
  // 1. a. Let result be ? Invoke(iterator, "next",).
  TNode<JSAny> result = Call(context, iterator.next, iterator.object);
  // 3. If Type(result) is not Object, throw a TypeError exception.
  Label if_notobject(this, Label::kDeferred), return_result(this);
  GotoIf(TaggedIsSmi(result), &if_notobject);
  TNode<JSAnyNotSmi> heap_object_result = CAST(result);
  TNode<Map> result_map = LoadMap(heap_object_result);
  GotoIfNot(JSAnyIsNotPrimitiveMap(result_map), &if_notobject);
  // IteratorComplete
  // 2. Return ToBoolean(? Get(iterResult, "done")).
  IteratorComplete(context, heap_object_result, if_done,
                   fast_iterator_result_map);
  Goto(&return_result);
  BIND(&if_notobject);
  CallRuntime(Runtime::kThrowIteratorResultNotAnObject, context, result);
  Unreachable();
  BIND(&return_result);
  return CAST(heap_object_result);
}
References v8::internal::CodeStubAssembler::Call(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, DCHECK_NOT_NULL, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), IteratorComplete(), v8::internal::CodeStubAssembler::JSAnyIsNotPrimitiveMap(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadMap(), v8::base::internal::result, v8::internal::CodeStubAssembler::TaggedIsSmi(), and v8::internal::compiler::CodeAssembler::Unreachable().
Referenced by v8::internal::BaseCollectionsAssembler::AddConstructorEntriesFromIterable(), Iterate(), and IteratorStep().
IteratorStep() [2/2]
TNode<JSReceiver> v8::internal::IteratorBuiltinsAssembler::IteratorStep (TNode< Context > context, const IteratorRecord & iterator, std::optional< TNode< Map >> fast_iterator_result_map, Label * if_done) [inline]
Definition at line 40 of file builtins-iterator-gen.h.
                                                                        {
    return IteratorStep(context, iterator, if_done, fast_iterator_result_map);
  }
References IteratorStep().
IteratorValue()
TNode< JSAny > v8::internal::IteratorBuiltinsAssembler::IteratorValue (TNode< Context > context, TNode< JSReceiver > result, std::optional< TNode< Map >> fast_iterator_result_map = std::nullopt)
Definition at line 129 of file builtins-iterator-gen.cc.
                                                      {
  Label exit(this);
  TVARIABLE(JSAny, var_value);
  if (fast_iterator_result_map) {
    // Fast iterator result case:
    Label if_generic(this);
    TNode<Map> map = LoadMap(result);
    GotoIfNot(TaggedEqual(map, *fast_iterator_result_map), &if_generic);
    var_value = CAST(LoadObjectField(result, JSIteratorResult::kValueOffset));
    Goto(&exit);
    BIND(&if_generic);
  }
  // Generic iterator result case:
  var_value = GetProperty(context, result, factory()->value_string());
  Goto(&exit);
  BIND(&exit);
  return var_value.value();
}
References CAST, v8::internal::compiler::CodeAssembler::factory(), v8::internal::CodeStubAssembler::GetProperty(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::base::internal::result, and v8::internal::CodeStubAssembler::TaggedEqual().
Referenced by v8::internal::BaseCollectionsAssembler::AddConstructorEntriesFromIterable(), and Iterate().
StringListFromIterable()
TNode< FixedArray > v8::internal::IteratorBuiltinsAssembler::StringListFromIterable (TNode< Context > context, TNode< JSAny > iterable)
Definition at line 283 of file builtins-iterator-gen.cc.
                                                   {
  Label done(this);
  GrowableFixedArray list(state());
  // 1. If iterable is undefined, then
  // a. Return a new empty List.
  GotoIf(IsUndefined(iterable), &done);
  // 2. Let iteratorRecord be ? GetIterator(items) (handled by Iterate).
  // 3. Let list be a new empty List.
  // 4. Let next be true (handled by Iterate).
  // 5. Repeat, while next is not false (handled by Iterate).
  Iterate(
      context, iterable,
      [&](TNode<Object> next_value) {
        // Handled by Iterate:
        // a. Set next to ? IteratorStep(iteratorRecord).
        // b. If next is not false, then
        // i. Let nextValue be ? IteratorValue(next).
        // ii. If Type(nextValue) is not String, then
        Label if_isnotstringtype(this, Label::kDeferred), loop_body_end(this);
        GotoIf(TaggedIsSmi(next_value), &if_isnotstringtype);
        TNode<Uint16T> next_value_type = LoadInstanceType(CAST(next_value));
        GotoIfNot(IsStringInstanceType(next_value_type), &if_isnotstringtype);
        // iii. Append nextValue to the end of the List list.
        list.Push(next_value);
        Goto(&loop_body_end);
        // 5.b.ii
        BIND(&if_isnotstringtype);
        {
          // 1. Let error be ThrowCompletion(a newly created TypeError object).
          CallRuntime(Runtime::kThrowTypeError, context,
                      SmiConstant(MessageTemplate::kIterableYieldedNonString),
                      next_value);
          // 2. Return ? IteratorClose(iteratorRecord, error). (handled by
          // Iterate).
          Unreachable();
        }
        BIND(&loop_body_end);
      },
      {list.var_array(), list.var_length(), list.var_capacity()});
  Goto(&done);
  BIND(&done);
  // 6. Return list.
  return list.ToFixedArray();
}
References v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::IsStringInstanceType(), Iterate(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadInstanceType(), v8::internal::GrowableFixedArray::Push(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::compiler::CodeAssembler::state(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::GrowableFixedArray::ToFixedArray(), v8::internal::compiler::CodeAssembler::Unreachable(), v8::internal::GrowableFixedArray::var_array(), v8::internal::GrowableFixedArray::var_capacity(), and v8::internal::GrowableFixedArray::var_length().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-iterator-gen.h
/mnt/V8SourceCode/src/builtins/builtins-iterator-gen.cc