v8::internal::wasm::ValidateFunctionsStreamingJob Class Reference
Public Member Functions
ValidateFunctionsStreamingJob (const WasmModule *module, WasmEnabledFeatures enabled_features, ValidateFunctionsStreamingJobData *data)
void Run (JobDelegate *delegate) override
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Private Attributes
const WasmModule *const module_
const WasmEnabledFeatures enabled_features_
ValidateFunctionsStreamingJobData * data_
Detailed Description
Definition at line 2579 of file module-compiler.cc.
Constructor & Destructor Documentation
ValidateFunctionsStreamingJob()
v8::internal::wasm::ValidateFunctionsStreamingJob::ValidateFunctionsStreamingJob (const WasmModule * module, WasmEnabledFeatures enabled_features, ValidateFunctionsStreamingJobData * data) [inline]
Definition at line 2581 of file module-compiler.cc.
      : module_(module), enabled_features_(enabled_features), data_(data) {}
Member Function Documentation
GetMaxConcurrency()
size_t v8::internal::wasm::ValidateFunctionsStreamingJob::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 2608 of file module-compiler.cc.
                                                               {
    return worker_count + data_->NumOutstandingUnits();
  }
References data_, and v8::internal::wasm::ValidateFunctionsStreamingJobData::NumOutstandingUnits().
Run()
void v8::internal::wasm::ValidateFunctionsStreamingJob::Run (JobDelegate * delegate) [inline], [override], [virtual]
Implements v8::JobTask.
Definition at line 2586 of file module-compiler.cc.
                                           {
    TRACE_EVENT0("v8.wasm", "wasm.ValidateFunctionsStreaming");
    using Unit = ValidateFunctionsStreamingJobData::Unit;
    Zone validation_zone{GetWasmEngine()->allocator(), ZONE_NAME};
    WasmDetectedFeatures detected_features;
    while (Unit unit = data_->GetUnit()) {
      validation_zone.Reset();
      DecodeResult result = ValidateSingleFunction(
          &validation_zone, module_, unit.func_index, unit.code,
          enabled_features_, &detected_features);
      if (result.failed()) {
        data_->found_error.store(true, std::memory_order_relaxed);
        break;
      }
      // After validating one function, check if we should yield.
      if (delegate->ShouldYield()) break;
    }
    data_->UpdateDetectedFeatures(detected_features);
  }
References v8::internal::wasm::WasmEngine::allocator(), v8::internal::wasm::WasmModule::code, data_, enabled_features_, v8::internal::wasm::ValidateFunctionsStreamingJobData::found_error, v8::internal::wasm::ValidateFunctionsStreamingJobData::GetUnit(), v8::internal::wasm::GetWasmEngine(), module_, v8::base::internal::result, v8::JobDelegate::ShouldYield(), TRACE_EVENT0, v8::internal::wasm::ValidateFunctionsStreamingJobData::UpdateDetectedFeatures(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::ValidateSingleFunction(), and ZONE_NAME.
Member Data Documentation
data_
ValidateFunctionsStreamingJobData* v8::internal::wasm::ValidateFunctionsStreamingJob::data_ [private]
Definition at line 2615 of file module-compiler.cc.
Referenced by GetMaxConcurrency(), and Run().
enabled_features_
const WasmEnabledFeatures v8::internal::wasm::ValidateFunctionsStreamingJob::enabled_features_ [private]
Definition at line 2614 of file module-compiler.cc.
Referenced by Run().
module_
const WasmModule* const v8::internal::wasm::ValidateFunctionsStreamingJob::module_ [private]
Definition at line 2613 of file module-compiler.cc.
Referenced by Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc