v8::internal::maglev::BranchIfFloat64Compare Class Reference
#include <maglev-ir.h>
Public Member Functions
Input & left_input ()
Input & right_input ()
BranchIfFloat64Compare (uint64_t bitfield, Operation operation, BasicBlockRef *if_true_refs, BasicBlockRef *if_false_refs)
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Operation operation () const
Static Public Attributes
static constexpr int kLeftIndex = 0
static constexpr int kRightIndex = 1
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = BranchControlNodeT< 2, BranchIfFloat64Compare >
Private Attributes
Operation operation_
Additional Inherited Members
Detailed Description
Definition at line 11770 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::BranchIfFloat64Compare::Base = BranchControlNodeT<2, BranchIfFloat64Compare> [private]
Definition at line 11772 of file maglev-ir.h.
Constructor & Destructor Documentation
BranchIfFloat64Compare()
v8::internal::maglev::BranchIfFloat64Compare::BranchIfFloat64Compare (uint64_t bitfield, Operation operation, BasicBlockRef * if_true_refs, BasicBlockRef * if_false_refs) [inline], [explicit]
Definition at line 11780 of file maglev-ir.h.
      : Base(bitfield, if_true_refs, if_false_refs), operation_(operation) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::BranchIfFloat64Compare::GenerateCode (MaglevAssembler * , const ProcessingState &)
left_input()
Input& v8::internal::maglev::BranchIfFloat64Compare::left_input () [inline]
Definition at line 11777 of file maglev-ir.h.
{ return NodeBase::input(kLeftIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
operation()
Operation v8::internal::maglev::BranchIfFloat64Compare::operation () const [inline]
Definition at line 11792 of file maglev-ir.h.
{ return operation_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::BranchIfFloat64Compare::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8453 of file maglev-ir.cc.
                                                               {
  os << "(" << operation_ << ")";
}
References operation_.
right_input()
Input& v8::internal::maglev::BranchIfFloat64Compare::right_input () [inline]
Definition at line 11778 of file maglev-ir.h.
{ return NodeBase::input(kRightIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::BranchIfFloat64Compare::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::BranchIfFloat64Compare::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kFloat64, ValueRepresentation::kFloat64}
Definition at line 11785 of file maglev-ir.h.
kLeftIndex
constexpr int v8::internal::maglev::BranchIfFloat64Compare::kLeftIndex = 0 [static], [constexpr]
Definition at line 11775 of file maglev-ir.h.
kRightIndex
constexpr int v8::internal::maglev::BranchIfFloat64Compare::kRightIndex = 1 [static], [constexpr]
Definition at line 11776 of file maglev-ir.h.
operation_
Operation v8::internal::maglev::BranchIfFloat64Compare::operation_ [private]
Definition at line 11795 of file maglev-ir.h.
Referenced by PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc