v8::internal::InnerPointerToCodeCache Class Reference
#include <frames-inl.h>
Classes
struct InnerPointerToCodeCacheEntry
Public Member Functions
InnerPointerToCodeCache (Isolate *isolate)
InnerPointerToCodeCache (const InnerPointerToCodeCache &)=delete
InnerPointerToCodeCache & operator= (const InnerPointerToCodeCache &)=delete
void Flush ()
InnerPointerToCodeCacheEntry * GetCacheEntry (Address inner_pointer)
Private Member Functions
InnerPointerToCodeCacheEntry * cache (int index)
Private Attributes
Isolate *const isolate_
InnerPointerToCodeCacheEntry cache_ [kInnerPointerToCodeCacheSize]
Static Private Attributes
static const int kInnerPointerToCodeCacheSize = 1024
Detailed Description
Definition at line 22 of file frames-inl.h.
Constructor & Destructor Documentation
InnerPointerToCodeCache() [1/2]
v8::internal::InnerPointerToCodeCache::InnerPointerToCodeCache (Isolate * isolate) [inline], [explicit]
Definition at line 34 of file frames-inl.h.
                                                     : isolate_(isolate) {
    Flush();
  }
References Flush().
InnerPointerToCodeCache() [2/2]
v8::internal::InnerPointerToCodeCache::InnerPointerToCodeCache (const InnerPointerToCodeCache &) [delete]
Member Function Documentation
cache()
InnerPointerToCodeCacheEntry* v8::internal::InnerPointerToCodeCache::cache (int index) [inline], [private]
Definition at line 46 of file frames-inl.h.
{ return &cache_[index]; }
References cache_, and v8::internal::index.
Flush()
void v8::internal::InnerPointerToCodeCache::Flush () [inline]
Definition at line 41 of file frames-inl.h.
{ memset(static_cast<void*>(&cache_[0]), 0, sizeof(cache_)); }
References cache_.
Referenced by InnerPointerToCodeCache().
GetCacheEntry()
InnerPointerToCodeCache::InnerPointerToCodeCacheEntry * v8::internal::InnerPointerToCodeCache::GetCacheEntry (Address inner_pointer)
Definition at line 4137 of file frames.cc.
                                                            {
  DCHECK(base::bits::IsPowerOfTwo(kInnerPointerToCodeCacheSize));
  uint32_t hash =
      ComputeUnseededHash(PcAddressForHashing(isolate_, inner_pointer));
  uint32_t index = hash & (kInnerPointerToCodeCacheSize - 1);
  InnerPointerToCodeCacheEntry* entry = cache(index);
  if (entry->inner_pointer == inner_pointer) {
    // Why this DCHECK holds is nontrivial:
    //
    // - the cache is filled lazily on calls to this function.
    // - this function may be called while GC, and in particular
    // MarkCompactCollector::UpdatePointersAfterEvacuation, is in progress.
    // - the cache is cleared at the end of UpdatePointersAfterEvacuation.
    // - now, why does pointer equality hold even during moving GC?
    // - .. because GcSafeFindCodeForInnerPointer does not follow forwarding
    // pointers and always returns the old object (which is still valid,
    // *except* for the map_word).
    DCHECK_EQ(entry->code,
              isolate_->heap()->GcSafeFindCodeForInnerPointer(inner_pointer));
  } else {
    // Because this code may be interrupted by a profiling signal that
    // also queries the cache, we cannot update inner_pointer before the code
    // has been set. Otherwise, we risk trying to use a cache entry before
    // the code has been computed.
    entry->code =
        isolate_->heap()->GcSafeFindCodeForInnerPointer(inner_pointer);
    if (entry->code.value()->is_maglevved()) {
      entry->maglev_safepoint_entry.Reset();
    } else {
      entry->safepoint_entry.Reset();
    }
    entry->inner_pointer = inner_pointer;
  }
  return entry;
}
References v8::internal::ComputeUnseededHash(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::index, v8::base::bits::IsPowerOfTwo(), and v8::internal::anonymous_namespace{frames.cc}::PcAddressForHashing().
Referenced by v8::internal::anonymous_namespace{frames.cc}::GetContainingCode(), v8::internal::TypedFrame::Iterate(), v8::internal::MaglevFrame::Iterate(), v8::internal::CommonFrame::IterateTurbofanJSOptimizedFrame(), and v8::internal::Isolate::UnwindAndFindHandler().
operator=()
InnerPointerToCodeCache& v8::internal::InnerPointerToCodeCache::operator= (const InnerPointerToCodeCache &) [delete]
Member Data Documentation
cache_
InnerPointerToCodeCacheEntry v8::internal::InnerPointerToCodeCache::cache_[kInnerPointerToCodeCacheSize] [private]
Definition at line 51 of file frames-inl.h.
Referenced by cache(), and Flush().
isolate_
Isolate* const v8::internal::InnerPointerToCodeCache::isolate_ [private]
Definition at line 48 of file frames-inl.h.
kInnerPointerToCodeCacheSize
const int v8::internal::InnerPointerToCodeCache::kInnerPointerToCodeCacheSize = 1024 [static], [private]
Definition at line 50 of file frames-inl.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc