v8::internal::BuiltinsCallGraph Class Reference
#include <basic-block-profiler.h>
Public Member Functions
BuiltinsCallGraph ()
~BuiltinsCallGraph ()=default
BuiltinsCallGraph (const BuiltinsCallGraph &)=delete
BuiltinsCallGraph & operator= (const BuiltinsCallGraph &)=delete
void AddBuiltinCall (Builtin caller, Builtin callee, int32_t block_id)
const BuiltinCallees * GetBuiltinCallees (Builtin builtin)
bool all_hash_matched () const
void set_all_hash_matched (bool all_hash_matched)
Static Public Member Functions
static BuiltinsCallGraph * Get ()
Private Attributes
BuiltinCallMap builtin_call_map_
bool all_hash_matched_
Detailed Description
Definition at line 113 of file basic-block-profiler.h.
Constructor & Destructor Documentation
BuiltinsCallGraph() [1/2]
v8::internal::BuiltinsCallGraph::BuiltinsCallGraph ()
Definition at line 281 of file basic-block-profiler.cc.
: all_hash_matched_(true) {}
 BuiltinsCallGraph()
v8::internal::BuiltinsCallGraph::~BuiltinsCallGraph () [default]
BuiltinsCallGraph() [2/2]
v8::internal::BuiltinsCallGraph::BuiltinsCallGraph (const BuiltinsCallGraph &) [delete]
Member Function Documentation
AddBuiltinCall()
void v8::internal::BuiltinsCallGraph::AddBuiltinCall (Builtin caller, Builtin callee, int32_t block_id)
Definition at line 283 of file basic-block-profiler.cc.
                                                         {
  if (builtin_call_map_.count(caller) == 0) {
    builtin_call_map_.emplace(caller, BuiltinCallees());
  }
  BuiltinCallees& callees = builtin_call_map_.at(caller);
  if (callees.count(block_id) == 0) {
    callees.emplace(block_id, BlockCallees());
  }
  BlockCallees& block_callees = callees.at(block_id);
  if (block_callees.count(callee) == 0) {
    block_callees.emplace(callee);
  }
}
References builtin_call_map_.
Referenced by v8::internal::compiler::anonymous_namespace{basic-block-instrumentor.cc}::StoreBuiltinCallForNode(), and v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph().
all_hash_matched()
bool v8::internal::BuiltinsCallGraph::all_hash_matched () const [inline]
Definition at line 123 of file basic-block-profiler.h.
{ return all_hash_matched_; }
References all_hash_matched_.
Referenced by v8::internal::EmbeddedData::NewFromIsolate(), and set_all_hash_matched().
Get()
static BuiltinsCallGraph* v8::internal::BuiltinsCallGraph::Get () [static]
Referenced by v8::internal::EmbeddedData::NewFromIsolate(), v8::internal::BuiltinsSorter::ProcessBlockCountLineInfo(), v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph(), and v8::internal::compiler::anonymous_namespace{pipeline.cc}::ValidateProfileData().
GetBuiltinCallees()
const BuiltinCallees * v8::internal::BuiltinsCallGraph::GetBuiltinCallees (Builtin builtin)
Definition at line 298 of file basic-block-profiler.cc.
                                                                          {
  if (builtin_call_map_.count(builtin) == 0) return nullptr;
  return &builtin_call_map_.at(builtin);
}
References builtin_call_map_.
Referenced by v8::internal::BuiltinsSorter::ProcessBlockCountLineInfo().
operator=()
BuiltinsCallGraph& v8::internal::BuiltinsCallGraph::operator= (const BuiltinsCallGraph &) [delete]
set_all_hash_matched()
void v8::internal::BuiltinsCallGraph::set_all_hash_matched (bool all_hash_matched) [inline]
Definition at line 124 of file basic-block-profiler.h.
                                                             {
    all_hash_matched_ = all_hash_matched;
  }
References all_hash_matched(), and all_hash_matched_.
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::ValidateProfileData().
Member Data Documentation
all_hash_matched_
bool v8::internal::BuiltinsCallGraph::all_hash_matched_ [private]
Definition at line 130 of file basic-block-profiler.h.
Referenced by all_hash_matched(), and set_all_hash_matched().
builtin_call_map_
BuiltinCallMap v8::internal::BuiltinsCallGraph::builtin_call_map_ [private]
Definition at line 129 of file basic-block-profiler.h.
Referenced by AddBuiltinCall(), and GetBuiltinCallees().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/diagnostics/basic-block-profiler.h
/mnt/V8SourceCode/src/diagnostics/basic-block-profiler.cc