v8::internal::compiler::ObservableNodeState Class Reference
#include <node-observer.h>
Public Member Functions
ObservableNodeState (const Node *node, Zone *zone)
uint32_t id () const
const Operator * op () const
int16_t opcode () const
Type type () const
Private Attributes
uint32_t id_
const Operator * op_
Type type_
Detailed Description
Definition at line 31 of file node-observer.h.
Constructor & Destructor Documentation
ObservableNodeState()
v8::internal::compiler::ObservableNodeState::ObservableNodeState (const Node * node, Zone * zone)
Definition at line 13 of file node-observer.cc.
    : id_(node->id()),
      op_(node->op()),
      type_(NodeProperties::GetTypeOrAny(node)) {}
Member Function Documentation
id()
uint32_t v8::internal::compiler::ObservableNodeState::id () const [inline]
Definition at line 35 of file node-observer.h.
{ return id_; }
References id_.
Referenced by v8::internal::compiler::operator==().
op()
const Operator* v8::internal::compiler::ObservableNodeState::op () const [inline]
Definition at line 36 of file node-observer.h.
{ return op_; }
References op_.
Referenced by v8::internal::compiler::operator==().
opcode()
int16_t v8::internal::compiler::ObservableNodeState::opcode () const [inline]
Definition at line 37 of file node-observer.h.
{ return op_->opcode(); }
References op_, and v8::internal::compiler::Operator::opcode().
type()
Type v8::internal::compiler::ObservableNodeState::type () const [inline]
Definition at line 38 of file node-observer.h.
{ return type_; }
References type_.
Referenced by v8::internal::compiler::operator==().
Member Data Documentation
id_
uint32_t v8::internal::compiler::ObservableNodeState::id_ [private]
Definition at line 41 of file node-observer.h.
Referenced by id().
op_
const Operator* v8::internal::compiler::ObservableNodeState::op_ [private]
Definition at line 42 of file node-observer.h.
Referenced by op(), and opcode().
type_
Type v8::internal::compiler::ObservableNodeState::type_ [private]
Definition at line 43 of file node-observer.h.
Referenced by type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/node-observer.h
/mnt/V8SourceCode/src/compiler/node-observer.cc