cppgc::internal::BasePageHandle Class Reference
#include <base-page-handle.h>
Public Member Functions
HeapHandle & heap_handle ()
const HeapHandle & heap_handle () const
Static Public Member Functions
static BasePageHandle * FromPayload (void *payload)
static const BasePageHandle * FromPayload (const void *payload)
Protected Member Functions
BasePageHandle (HeapHandle &heap_handle)
Protected Attributes
HeapHandle & heap_handle_
Detailed Description
Definition at line 18 of file base-page-handle.h.
Constructor & Destructor Documentation
BasePageHandle()
cppgc::internal::BasePageHandle::BasePageHandle (HeapHandle & heap_handle) [inline], [explicit], [protected]
Definition at line 32 of file base-page-handle.h.
                                                   : heap_handle_(heap_handle) {
    CPPGC_DCHECK(reinterpret_cast<uintptr_t>(this) % api_constants::kPageSize ==
                 0);
  }
References CPPGC_DCHECK, and cppgc::internal::api_constants::kPageSize.
Member Function Documentation
FromPayload() [1/2]
static const BasePageHandle* cppgc::internal::BasePageHandle::FromPayload (const void * payload) [inline], [static]
Definition at line 24 of file base-page-handle.h.
                                                                          {
    return FromPayload(const_cast<void*>(payload));
  }
References FromPayload().
FromPayload() [2/2]
static BasePageHandle* cppgc::internal::BasePageHandle::FromPayload (void * payload) [inline], [static]
Definition at line 20 of file base-page-handle.h.
                                                              {
    return reinterpret_cast<BasePageHandle*>(
        reinterpret_cast<uintptr_t>(payload) & ~(api_constants::kPageSize - 1));
  }
References cppgc::internal::api_constants::kPageSize.
Referenced by FromPayload(), cppgc::internal::BasePage::FromPayload(), and cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::ValueModeDispatch< WriteBarrier::ValueMode::kValuePresent >::Get().
heap_handle() [1/2]
HeapHandle& cppgc::internal::BasePageHandle::heap_handle () [inline]
Definition at line 28 of file base-page-handle.h.
{ return heap_handle_; }
References heap_handle_.
Referenced by cppgc::internal::WriteBarrierTypeForNonCagedHeapPolicy::ValueModeDispatch< WriteBarrier::ValueMode::kValuePresent >::Get().
heap_handle() [2/2]
const HeapHandle& cppgc::internal::BasePageHandle::heap_handle () const [inline]
Definition at line 29 of file base-page-handle.h.
{ return heap_handle_; }
References heap_handle_.
Member Data Documentation
heap_handle_
HeapHandle& cppgc::internal::BasePageHandle::heap_handle_ [protected]
Definition at line 37 of file base-page-handle.h.
Referenced by cppgc::internal::BasePage::heap(), and heap_handle().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/cppgc/internal/base-page-handle.h