v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror Class Reference
Public Member Functions
PrimitiveValueMirror (v8::Isolate *isolate, v8::Local< v8::Primitive > value, const String16 &type)
Response buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions &wrapOptions, std::unique_ptr< RemoteObject > *result) const override
void buildEntryPreview (v8::Local< v8::Context > context, int *nameLimit, int *indexLimit, std::unique_ptr< ObjectPreview > *preview) const override
void buildPropertyPreview (v8::Local< v8::Context > context, const String16 &name, std::unique_ptr< PropertyPreview > *preview) const override
Response buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, std::unique_ptr< protocol::DictionaryValue > *result) const override
Private Attributes
String16 m_type
String16 m_subtype
Additional Inherited Members
Detailed Description
Definition at line 503 of file value-mirror.cc.
Constructor & Destructor Documentation
PrimitiveValueMirror()
v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::PrimitiveValueMirror (v8::Isolate * isolate, v8::Local< v8::Primitive > value, const String16 & type) [inline]
Definition at line 505 of file value-mirror.cc.
      : ValueMirrorBase(isolate, value), m_type(type) {}
Member Function Documentation
buildDeepSerializedValue()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, std::unique_ptr< protocol::DictionaryValue > * result) const [inline], [override], [virtual]
Implements v8_inspector::ValueMirror.
Definition at line 552 of file value-mirror.cc.
                                                                     {
    v8::Local<v8::Value> value = v8Value(v8::Isolate::GetCurrent());
    if (value->IsUndefined()) {
      *result = protocol::DictionaryValue::create();
      (*result)->setString(
          "type", protocol::Runtime::DeepSerializedValue::TypeEnum::Undefined);
      return Response::Success();
    }
    if (value->IsNull()) {
      *result = protocol::DictionaryValue::create();
      (*result)->setString(
          "type", protocol::Runtime::DeepSerializedValue::TypeEnum::Null);
      return Response::Success();
    }
    if (value->IsString()) {
      *result = protocol::DictionaryValue::create();
      (*result)->setString(
          "type", protocol::Runtime::DeepSerializedValue::TypeEnum::String);
      (*result)->setString("value", toProtocolString(v8::Isolate::GetCurrent(),
                                                     value.As<v8::String>()));
      return Response::Success();
    }
    if (value->IsBoolean()) {
      *result = protocol::DictionaryValue::create();
      (*result)->setString(
          "type", protocol::Runtime::DeepSerializedValue::TypeEnum::Boolean);
      (*result)->setBoolean("value", value.As<v8::Boolean>()->Value());
      return Response::Success();
    }
    // Fallback in case of unexpected type.
    bool isKnown;
    *result = duplicateTracker.LinkExistingOrCreate(value, &isKnown);
    if (isKnown) {
      return Response::Success();
    }
    (*result)->setString(
        "type", protocol::Runtime::DeepSerializedValue::TypeEnum::Object);
    return Response::Success();
  }
References v8::Isolate::GetCurrent(), v8_inspector::V8SerializationDuplicateTracker::LinkExistingOrCreate(), v8::internal::compiler::Null, v8::internal::compiler::Object, v8::base::internal::result, v8_inspector::toProtocolString(), v8::internal::compiler::Undefined, v8::Boolean::Value(), and v8::internal::value.
buildEntryPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildEntryPreview (v8::Local< v8::Context > context, int * nameLimit, int * indexLimit, std::unique_ptr< ObjectPreview > * preview) const [inline], [override]
Definition at line 523 of file value-mirror.cc.
                                                            {
    v8::Local<v8::Value> value = v8Value(v8::Isolate::GetCurrent());
    *preview =
        ObjectPreview::create()
            .setType(m_type)
            .setDescription(descriptionForPrimitiveType(context, value))
            .setOverflow(false)
            .setProperties(std::make_unique<protocol::Array<PropertyPreview>>())
            .build();
    if (value->IsNull())
      (*preview)->setSubtype(RemoteObject::SubtypeEnum::Null);
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrimitiveType(), v8::Isolate::GetCurrent(), v8::internal::compiler::Null, and v8::internal::value.
buildPropertyPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildPropertyPreview (v8::Local< v8::Context > context, const String16 & name, std::unique_ptr< PropertyPreview > * preview) const [inline], [override]
Definition at line 538 of file value-mirror.cc.
                                                              {
    v8::Local<v8::Value> value = v8Value(v8::Isolate::GetCurrent());
    *preview = PropertyPreview::create()
                   .setName(name)
                   .setValue(abbreviateString(
                       descriptionForPrimitiveType(context, value), kMiddle))
                   .setType(m_type)
                   .build();
    if (value->IsNull())
      (*preview)->setSubtype(RemoteObject::SubtypeEnum::Null);
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::abbreviateString(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForPrimitiveType(), v8::Isolate::GetCurrent(), v8_inspector::anonymous_namespace{value-mirror.cc}::kMiddle, name, v8::internal::compiler::Null, and v8::internal::value.
buildRemoteObject()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions & wrapOptions, std::unique_ptr< RemoteObject > * result) const [inline], [override]
Definition at line 509 of file value-mirror.cc.
                                                          {
    std::unique_ptr<protocol::Value> protocolValue;
    v8::Local<v8::Value> value = v8Value(v8::Isolate::GetCurrent());
    toProtocolValue(context, value, &protocolValue);
    *result = RemoteObject::create()
                  .setType(m_type)
                  .setValue(std::move(protocolValue))
                  .build();
    if (value->IsNull()) (*result)->setSubtype(RemoteObject::SubtypeEnum::Null);
    return Response::Success();
  }
References v8::Isolate::GetCurrent(), v8::internal::compiler::Null, v8::base::internal::result, v8_inspector::toProtocolValue(), and v8::internal::value.
Member Data Documentation
m_subtype
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::m_subtype [private]
Definition at line 600 of file value-mirror.cc.
m_type
String16 v8_inspector::anonymous_namespace{value-mirror.cc}::PrimitiveValueMirror::m_type [private]
Definition at line 599 of file value-mirror.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/value-mirror.cc