cppgc::internal::GCInfoTable Class Reference
#include <gc-info-table.h>
Public Member Functions
GCInfoTable (PageAllocator &page_allocator, FatalOutOfMemoryHandler &oom_handler)
~GCInfoTable ()
GCInfoTable (const GCInfoTable &)=delete
GCInfoTable & operator= (const GCInfoTable &)=delete
GCInfoIndex RegisterNewGCInfo (std::atomic< uint16_t > &, const GCInfo &info)
const GCInfo & GCInfoFromIndex (GCInfoIndex index) const
GCInfoIndex NumberOfGCInfos () const
GCInfoIndex LimitForTesting () const
GCInfo & TableSlotForTesting (GCInfoIndex index)
PageAllocator & allocator () const
Static Public Attributes
static constexpr GCInfoIndex kMaxIndex = 1 << 14
static constexpr GCInfoIndex kMinIndex = 1
static constexpr GCInfoIndex kInitialWantedLimit = 512
Private Member Functions
void Resize ()
GCInfoIndex InitialTableLimit () const
size_t MaxTableSize () const
void CheckMemoryIsZeroed (uintptr_t *base, size_t len)
Private Attributes
PageAllocator & page_allocator_
FatalOutOfMemoryHandler & oom_handler_
GCInfo * table_
uint8_t * read_only_table_end_
GCInfoIndex current_index_ = kMinIndex
GCInfoIndex limit_ = 0
v8::base::Mutex table_mutex_
Detailed Description
Definition at line 35 of file gc-info-table.h.
Constructor & Destructor Documentation
GCInfoTable() [1/2]
cppgc::internal::GCInfoTable::GCInfoTable (PageAllocator & page_allocator, FatalOutOfMemoryHandler & oom_handler)
Definition at line 52 of file gc-info-table.cc.
    : page_allocator_(page_allocator),
      oom_handler_(oom_handler),
      table_(static_cast<decltype(table_)>(page_allocator_.AllocatePages(
          nullptr, MaxTableSize(), page_allocator_.AllocatePageSize(),
          PageAllocator::kNoAccess))),
      read_only_table_end_(reinterpret_cast<uint8_t*>(table_)) {
  if (!table_) {
    oom_handler_("Oilpan: GCInfoTable initial reservation.");
  }
  Resize();
}
References oom_handler_, Resize(), and table_.
 GCInfoTable()
cppgc::internal::GCInfoTable::~GCInfoTable ()
Definition at line 66 of file gc-info-table.cc.
                          {
  page_allocator_.ReleasePages(const_cast<GCInfo*>(table_), MaxTableSize(), 0);
}
References MaxTableSize(), page_allocator_, v8::PageAllocator::ReleasePages(), and table_.
GCInfoTable() [2/2]
cppgc::internal::GCInfoTable::GCInfoTable (const GCInfoTable &) [delete]
Member Function Documentation
allocator()
PageAllocator& cppgc::internal::GCInfoTable::allocator () const [inline]
Definition at line 77 of file gc-info-table.h.
{ return page_allocator_; }
Referenced by cppgc::internal::GlobalGCInfoTable::Initialize().
CheckMemoryIsZeroed()
void cppgc::internal::GCInfoTable::CheckMemoryIsZeroed (uintptr_t * base, size_t len) [private]
Definition at line 119 of file gc-info-table.cc.
                                                                 {
#if DEBUG
  for (size_t i = 0; i < len; ++i) {
    DCHECK(!base[i]);
  }
#endif // DEBUG
}
References DCHECK, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by Resize().
GCInfoFromIndex()
const GCInfo& cppgc::internal::GCInfoTable::GCInfoFromIndex (GCInfoIndex index) const [inline]
Definition at line 65 of file gc-info-table.h.
                                                         {
    DCHECK_GE(index, kMinIndex);
    DCHECK_LT(index, kMaxIndex);
    DCHECK(table_);
    return table_[index];
  }
References DCHECK, DCHECK_GE, DCHECK_LT, and v8::internal::index.
InitialTableLimit()
GCInfoIndex cppgc::internal::GCInfoTable::InitialTableLimit () const [private]
Definition at line 75 of file gc-info-table.cc.
                                                 {
  // Different OSes have different page sizes, so we have to choose the minimum
  // of memory wanted and OS page size.
  constexpr size_t memory_wanted = kInitialWantedLimit * kEntrySize;
  const size_t initial_limit =
      RoundUp(memory_wanted, page_allocator_.AllocatePageSize()) / kEntrySize;
  CHECK_GT(std::numeric_limits<GCInfoIndex>::max(), initial_limit);
  return static_cast<GCInfoIndex>(
      std::min(static_cast<size_t>(kMaxIndex), initial_limit));
}
References v8::PageAllocator::AllocatePageSize(), CHECK_GT, cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, kInitialWantedLimit, kMaxIndex, page_allocator_, and RoundUp().
Referenced by Resize().
LimitForTesting()
GCInfoIndex cppgc::internal::GCInfoTable::LimitForTesting () const [inline]
Definition at line 74 of file gc-info-table.h.
{ return limit_; }
MaxTableSize()
size_t cppgc::internal::GCInfoTable::MaxTableSize () const [private]
Definition at line 70 of file gc-info-table.cc.
                                       {
  return RoundUp(GCInfoTable::kMaxIndex * kEntrySize,
                 page_allocator_.AllocatePageSize());
}
References v8::PageAllocator::AllocatePageSize(), cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, kMaxIndex, page_allocator_, and RoundUp().
Referenced by Resize(), and ~GCInfoTable().
NumberOfGCInfos()
GCInfoIndex cppgc::internal::GCInfoTable::NumberOfGCInfos () const [inline]
Definition at line 72 of file gc-info-table.h.
{ return current_index_; }
operator=()
GCInfoTable& cppgc::internal::GCInfoTable::operator= (const GCInfoTable &) [delete]
RegisterNewGCInfo()
GCInfoIndex cppgc::internal::GCInfoTable::RegisterNewGCInfo (std::atomic< uint16_t > & registered_index, const GCInfo & info)
Definition at line 127 of file gc-info-table.cc.
                                                                  {
  // Ensuring a new index involves current index adjustment as well as
  // potentially resizing the table. For simplicity we use a lock.
  v8::base::MutexGuard guard(&table_mutex_);
  // Check the registered index again after taking the lock as some other
  // thread may have registered the info at the same time.
  const GCInfoIndex index = registered_index.load(std::memory_order_relaxed);
  if (index) {
    return index;
  }
  if (current_index_ == limit_) {
    Resize();
  }
  const GCInfoIndex new_index = current_index_++;
  CHECK_LT(new_index, GCInfoTable::kMaxIndex);
  table_[new_index] = info;
  registered_index.store(new_index, std::memory_order_release);
  return new_index;
}
References CHECK_LT, current_index_, v8::internal::index, kMaxIndex, limit_, Resize(), table_, and table_mutex_.
Referenced by cppgc::internal::EnsureGCInfoIndexTrait::EnsureGCInfoIndex().
Resize()
void cppgc::internal::GCInfoTable::Resize () [private]
Definition at line 86 of file gc-info-table.cc.
                         {
  const GCInfoIndex new_limit = (limit_) ? 2 * limit_ : InitialTableLimit();
  CHECK_GT(new_limit, limit_);
  const size_t old_committed_size = limit_ * kEntrySize;
  const size_t new_committed_size = new_limit * kEntrySize;
  CHECK(table_);
  CHECK_EQ(0u, new_committed_size % page_allocator_.AllocatePageSize());
  CHECK_GE(MaxTableSize(), new_committed_size);
  // Recommit new area as read/write.
  uint8_t* current_table_end =
      reinterpret_cast<uint8_t*>(table_) + old_committed_size;
  const size_t table_size_delta = new_committed_size - old_committed_size;
  if (!page_allocator_.SetPermissions(current_table_end, table_size_delta,
                                      PageAllocator::kReadWrite)) {
    oom_handler_("Oilpan: GCInfoTable resize.");
  }
  // Recommit old area as read-only.
  if (read_only_table_end_ != current_table_end) {
    DCHECK_GT(current_table_end, read_only_table_end_);
    const size_t read_only_delta = current_table_end - read_only_table_end_;
    CHECK(page_allocator_.SetPermissions(read_only_table_end_, read_only_delta,
                                         PageAllocator::kRead));
    read_only_table_end_ += read_only_delta;
  }
  // Check that newly-committed memory is zero-initialized.
  CheckMemoryIsZeroed(reinterpret_cast<uintptr_t*>(current_table_end),
                      table_size_delta / sizeof(uintptr_t));
  limit_ = new_limit;
}
References v8::PageAllocator::AllocatePageSize(), CHECK, CHECK_EQ, CHECK_GE, CHECK_GT, CheckMemoryIsZeroed(), DCHECK_GT, InitialTableLimit(), cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, v8::PageAllocator::kRead, v8::PageAllocator::kReadWrite, limit_, MaxTableSize(), oom_handler_, page_allocator_, read_only_table_end_, v8::PageAllocator::SetPermissions(), and table_.
Referenced by GCInfoTable(), and RegisterNewGCInfo().
TableSlotForTesting()
GCInfo& cppgc::internal::GCInfoTable::TableSlotForTesting (GCInfoIndex index) [inline]
Definition at line 75 of file gc-info-table.h.
{ return table_[index]; }
References v8::internal::index.
Member Data Documentation
current_index_
GCInfoIndex cppgc::internal::GCInfoTable::current_index_ = kMinIndex [private]
Definition at line 94 of file gc-info-table.h.
Referenced by RegisterNewGCInfo().
kInitialWantedLimit
constexpr GCInfoIndex cppgc::internal::GCInfoTable::kInitialWantedLimit = 512 [static], [constexpr]
Definition at line 53 of file gc-info-table.h.
Referenced by InitialTableLimit().
kMaxIndex
constexpr GCInfoIndex cppgc::internal::GCInfoTable::kMaxIndex = 1 << 14 [static], [constexpr]
Definition at line 45 of file gc-info-table.h.
Referenced by cppgc::internal::HeapObjectHeader::HeapObjectHeader(), InitialTableLimit(), MaxTableSize(), and RegisterNewGCInfo().
kMinIndex
constexpr GCInfoIndex cppgc::internal::GCInfoTable::kMinIndex = 1 [static], [constexpr]
Definition at line 49 of file gc-info-table.h.
limit_
GCInfoIndex cppgc::internal::GCInfoTable::limit_ = 0 [private]
Definition at line 96 of file gc-info-table.h.
Referenced by RegisterNewGCInfo(), and Resize().
oom_handler_
FatalOutOfMemoryHandler& cppgc::internal::GCInfoTable::oom_handler_ [private]
Definition at line 88 of file gc-info-table.h.
Referenced by GCInfoTable(), and Resize().
page_allocator_
PageAllocator& cppgc::internal::GCInfoTable::page_allocator_ [private]
Definition at line 87 of file gc-info-table.h.
Referenced by InitialTableLimit(), MaxTableSize(), Resize(), and ~GCInfoTable().
read_only_table_end_
uint8_t* cppgc::internal::GCInfoTable::read_only_table_end_ [private]
Definition at line 92 of file gc-info-table.h.
Referenced by Resize().
table_
GCInfo* cppgc::internal::GCInfoTable::table_ [private]
Definition at line 91 of file gc-info-table.h.
Referenced by GCInfoTable(), RegisterNewGCInfo(), Resize(), and ~GCInfoTable().
table_mutex_
v8::base::Mutex cppgc::internal::GCInfoTable::table_mutex_ [private]
Definition at line 98 of file gc-info-table.h.
Referenced by RegisterNewGCInfo().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/gc-info-table.h
/mnt/V8SourceCode/src/heap/cppgc/gc-info-table.cc