v8::internal::CountersVisitor Class Reference
#include <counters.h>
Public Member Functions
CountersVisitor (Counters *counters)
void Start ()
Counters * counters ()
Protected Member Functions
virtual void VisitHistograms ()
virtual void VisitStatsCounters ()
virtual void VisitHistogram (Histogram *histogram, const char *caption)
virtual void VisitStatsCounter (StatsCounter *counter, const char *caption)
virtual void Visit (Histogram *histogram, const char *caption, int min, int max, int num_buckets)
virtual void Visit (TimedHistogram *histogram, const char *caption, int max, TimedHistogramResolution res)
virtual void Visit (NestedTimedHistogram *histogram, const char *caption, int max, TimedHistogramResolution res)
virtual void Visit (AggregatableHistogramTimer *histogram, const char *caption)
virtual void Visit (PercentageHistogram *histogram, const char *caption)
virtual void Visit (LegacyMemoryHistogram *histogram, const char *caption)
virtual void Visit (StatsCounter *counter, const char *caption)
Private Attributes
Counters * counters_
Detailed Description
Definition at line 706 of file counters.h.
Constructor & Destructor Documentation
CountersVisitor()
v8::internal::CountersVisitor::CountersVisitor (Counters * counters) [inline], [explicit]
Definition at line 708 of file counters.h.
: counters_(counters) {}
Member Function Documentation
counters()
Counters* v8::internal::CountersVisitor::counters () [inline]
Definition at line 711 of file counters.h.
{ return counters_; }
References counters_.
Referenced by v8::internal::CountersInitializer::Visit().
Start()
void v8::internal::CountersVisitor::Start ()
Definition at line 191 of file counters.cc.
                            {
  VisitStatsCounters();
  VisitHistograms();
}
References VisitHistograms(), and VisitStatsCounters().
Referenced by v8::internal::Counters::Counters(), v8::internal::Counters::ResetCounterFunction(), and v8::internal::Counters::ResetCreateHistogramFunction().
Visit() [1/7]
void v8::internal::CountersVisitor::Visit (AggregatableHistogramTimer * histogram, const char * caption) [protected], [virtual]
Reimplemented in v8::internal::CountersInitializer.
Definition at line 258 of file counters.cc.
                                                 {
  VisitHistogram(histogram, caption);
}
References VisitHistogram().
Visit() [2/7]
void v8::internal::CountersVisitor::Visit (Histogram * histogram, const char * caption, int min, int max, int num_buckets) [protected], [virtual]
Reimplemented in v8::internal::CountersInitializer.
Definition at line 244 of file counters.cc.
                                                      {
  VisitHistogram(histogram, caption);
}
References VisitHistogram().
Visit() [3/7]
void v8::internal::CountersVisitor::Visit (LegacyMemoryHistogram * histogram, const char * caption) [protected], [virtual]
Reimplemented in v8::internal::CountersInitializer.
Definition at line 268 of file counters.cc.
                                                 {
  VisitHistogram(histogram, caption);
}
References VisitHistogram().
Visit() [4/7]
void v8::internal::CountersVisitor::Visit (NestedTimedHistogram * histogram, const char * caption, int max, TimedHistogramResolution res) [protected], [virtual]
Reimplemented in v8::internal::CountersInitializer.
Definition at line 252 of file counters.cc.
                                                          {
  VisitHistogram(histogram, caption);
}
References VisitHistogram().
Visit() [5/7]
void v8::internal::CountersVisitor::Visit (PercentageHistogram * histogram, const char * caption) [protected], [virtual]
Reimplemented in v8::internal::CountersInitializer.
Definition at line 263 of file counters.cc.
                                                 {
  VisitHistogram(histogram, caption);
}
References VisitHistogram().
Visit() [6/7]
void v8::internal::CountersVisitor::Visit (StatsCounter * counter, const char * caption) [protected], [virtual]
Reimplemented in v8::internal::CountersInitializer.
Definition at line 273 of file counters.cc.
                                                                      {
  VisitStatsCounter(counter, caption);
}
References VisitStatsCounter().
Visit() [7/7]
void v8::internal::CountersVisitor::Visit (TimedHistogram * histogram, const char * caption, int max, TimedHistogramResolution res) [protected], [virtual]
Reimplemented in v8::internal::CountersInitializer.
Definition at line 248 of file counters.cc.
                                                                   {
  VisitHistogram(histogram, caption);
}
References VisitHistogram().
VisitHistogram()
virtual void v8::internal::CountersVisitor::VisitHistogram (Histogram * histogram, const char * caption) [inline], [protected], [virtual]
Reimplemented in v8::internal::HistogramResetter.
Definition at line 717 of file counters.h.
{}
Referenced by Visit().
VisitHistograms()
void v8::internal::CountersVisitor::VisitHistograms () [protected], [virtual]
Reimplemented in v8::internal::StatsCounterResetter.
Definition at line 196 of file counters.cc.
                                      {
#define HR(name, caption, min, max, num_buckets) \
  Visit(&counters()->name##_, #caption, min, max, num_buckets);
  HISTOGRAM_RANGE_LIST(HR)
#undef HR
#if V8_ENABLE_DRUMBRAKE
#define HR(name, caption, min, max, num_buckets) \
  Visit(&counters()->name##_, #caption, min, max, num_buckets);
  HISTOGRAM_RANGE_LIST_SLOW(HR)
#undef HR
#endif // V8_ENABLE_DRUMBRAKE
#define HR(name, caption) Visit(&counters()->name##_, #caption);
  HISTOGRAM_PERCENTAGE_LIST(HR)
#undef HR
#define HR(name, caption) Visit(&counters()->name##_, #caption);
  HISTOGRAM_LEGACY_MEMORY_LIST(HR)
#undef HR
#define HT(name, caption, max, res) \
  Visit(&counters()->name##_, #caption, max, TimedHistogramResolution::res);
  NESTED_TIMED_HISTOGRAM_LIST(HT)
#undef HT
#define HT(name, caption, max, res) \
  Visit(&counters()->name##_, #caption, max, TimedHistogramResolution::res);
  NESTED_TIMED_HISTOGRAM_LIST_SLOW(HT)
#undef HT
#define HT(name, caption, max, res) \
  Visit(&counters()->name##_, #caption, max, TimedHistogramResolution::res);
  TIMED_HISTOGRAM_LIST(HT)
#undef HT
#define AHT(name, caption) Visit(&counters()->name##_, #caption);
  AGGREGATABLE_HISTOGRAM_TIMER_LIST(AHT)
#undef AHT
}
References AGGREGATABLE_HISTOGRAM_TIMER_LIST, AHT, HISTOGRAM_LEGACY_MEMORY_LIST, HISTOGRAM_PERCENTAGE_LIST, HISTOGRAM_RANGE_LIST, HR, HT, NESTED_TIMED_HISTOGRAM_LIST, NESTED_TIMED_HISTOGRAM_LIST_SLOW, and TIMED_HISTOGRAM_LIST.
Referenced by Start().
VisitStatsCounter()
virtual void v8::internal::CountersVisitor::VisitStatsCounter (StatsCounter * counter, const char * caption) [inline], [protected], [virtual]
Reimplemented in v8::internal::StatsCounterResetter.
Definition at line 718 of file counters.h.
{}
Referenced by Visit().
VisitStatsCounters()
void v8::internal::CountersVisitor::VisitStatsCounters () [protected], [virtual]
Reimplemented in v8::internal::HistogramResetter.
Definition at line 237 of file counters.cc.
                                         {
#define SC(name, caption) Visit(&counters()->name##_, "c:" #caption);
  STATS_COUNTER_LIST(SC)
  STATS_COUNTER_NATIVE_CODE_LIST(SC)
#undef SC
}
References v8::internal::SC, STATS_COUNTER_LIST, and STATS_COUNTER_NATIVE_CODE_LIST.
Referenced by Start().
Member Data Documentation
counters_
Counters* v8::internal::CountersVisitor::counters_ [private]
Definition at line 733 of file counters.h.
Referenced by counters().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/counters.h
/mnt/V8SourceCode/src/logging/counters.cc