v8::internal::OrderedHashSetHandler Class Reference
#include <ordered-hash-table.h>
Static Public Member Functions
static MaybeHandle< HeapObject > Add (Isolate *isolate, Handle< HeapObject > table, DirectHandle< Object > key)
static MaybeHandle< OrderedHashSet > AdjustRepresentation (Isolate *isolate, DirectHandle< SmallOrderedHashSet > table)
Detailed Description
Definition at line 768 of file ordered-hash-table.h.
Member Function Documentation
Add()
MaybeHandle< HeapObject > v8::internal::OrderedHashSetHandler::Add (Isolate * isolate, Handle< HeapObject > table, DirectHandle< Object > key) [static]
Definition at line 1267 of file ordered-hash-table.cc.
                                                                             {
  if (IsSmallOrderedHashSet(*table)) {
    Handle<SmallOrderedHashSet> small_set = Cast<SmallOrderedHashSet>(table);
    MaybeHandle<SmallOrderedHashSet> new_set =
        SmallOrderedHashSet::Add(isolate, small_set, key);
    if (!new_set.is_null()) return new_set.ToHandleChecked();
    // We couldn't add to the small table, let's migrate to the
    // big table.
    MaybeHandle<OrderedHashSet> table_candidate =
        OrderedHashSetHandler::AdjustRepresentation(isolate, small_set);
    if (!table_candidate.ToHandle(&table)) {
      return table_candidate;
    }
  }
  DCHECK(IsOrderedHashSet(*table));
  return OrderedHashSet::Add(isolate, Cast<OrderedHashSet>(table), key);
}
References v8::bigint::Add(), DCHECK, v8::internal::MaybeHandle< T >::is_null(), v8::internal::key, v8::internal::MaybeHandle< T >::ToHandle(), and v8::internal::MaybeHandle< T >::ToHandleChecked().
AdjustRepresentation()
MaybeHandle< OrderedHashSet > v8::internal::OrderedHashSetHandler::AdjustRepresentation (Isolate * isolate, DirectHandle< SmallOrderedHashSet > table) [static]
Definition at line 1192 of file ordered-hash-table.cc.
                                                               {
  MaybeHandle<OrderedHashSet> new_table_candidate =
      OrderedHashSet::Allocate(isolate, OrderedHashTableMinSize);
  Handle<OrderedHashSet> new_table;
  if (!new_table_candidate.ToHandle(&new_table)) {
    return new_table_candidate;
  }
  // TODO(gsathya): Optimize the lookup to not re calc offsets. Also,
  // unhandlify this code as we preallocate the new backing store with
  // the proper capacity.
  for (InternalIndex entry : table->IterateEntries()) {
    DirectHandle<Object> key(table->KeyAt(entry), isolate);
    if (IsTheHole(*key, isolate)) continue;
    new_table_candidate = OrderedHashSet::Add(isolate, new_table, key);
    if (!new_table_candidate.ToHandle(&new_table)) {
      return new_table_candidate;
    }
  }
  return new_table_candidate;
}
References v8::bigint::Add(), v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::internal::key, and v8::internal::MaybeHandle< T >::ToHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/ordered-hash-table.h
/mnt/V8SourceCode/src/objects/ordered-hash-table.cc