v8::internal::ScopedList< T, TBacking > Class Template Reference
#include <scoped-list.h>
Public Types
using iterator = T *
using const_iterator = const T *
Public Member Functions
ScopedList (std::vector< TBacking > *buffer)
~ScopedList ()
void Rewind ()
void MergeInto (ScopedList *parent)
int length () const
const T & at (int i) const
T & at (int i)
base::Vector< const T > ToConstVector () const
void Add (const T &value)
void AddAll (base::Vector< const T > list)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Private Attributes
std::vector< TBacking > & buffer_
size_t start_
size_t end_
Detailed Description
template<typename T, typename TBacking = T>
class v8::internal::ScopedList< T, TBacking >
Definition at line 30 of file scoped-list.h.
Member Typedef Documentation
const_iterator
template<typename T , typename TBacking = T>
using v8::internal::ScopedList< T, TBacking >::const_iterator = const T*
Definition at line 93 of file scoped-list.h.
iterator
template<typename T , typename TBacking = T>
using v8::internal::ScopedList< T, TBacking >::iterator = T*
Definition at line 92 of file scoped-list.h.
Constructor & Destructor Documentation
ScopedList()
template<typename T , typename TBacking = T>
v8::internal::ScopedList< T, TBacking >::ScopedList (std::vector< TBacking > * buffer) [inline], [explicit]
Definition at line 38 of file scoped-list.h.
      : buffer_(*buffer), start_(buffer->size()), end_(buffer->size()) {}
 ScopedList()
template<typename T , typename TBacking = T>
v8::internal::ScopedList< T, TBacking >::~ScopedList () [inline]
Definition at line 41 of file scoped-list.h.
{ Rewind(); }
Member Function Documentation
Add()
template<typename T , typename TBacking = T>
void v8::internal::ScopedList< T, TBacking >::Add (const T & value) [inline]
Definition at line 77 of file scoped-list.h.
                           {
    DCHECK_EQ(buffer_.size(), end_);
    buffer_.push_back(value);
    ++end_;
  }
References DCHECK_EQ, and v8::internal::value.
Referenced by v8::internal::Parser::CloseTemplateLiteral(), v8::internal::Parser::CreateInitializerFunction(), v8::internal::Parser::DefaultConstructor(), v8::internal::Parser::DesugarLexicalBindingsInForStatement(), v8::internal::Parser::DoParseProgram(), v8::internal::Parser::InitializeVariables(), v8::internal::Parser::MakeAutoAccessorGetter(), v8::internal::Parser::MakeAutoAccessorSetter(), v8::internal::Parser::NewV8RuntimeFunctionForFuzzing(), v8::internal::Parser::ParseAsyncGeneratorFunctionBody(), v8::internal::Parser::ParseGeneratorFunctionBody(), v8::internal::Parser::ParseModuleItemList(), v8::internal::Parser::ParseREPLProgram(), v8::internal::Parser::ParseWrapped(), and v8::internal::Parser::WrapREPLResult().
AddAll()
template<typename T , typename TBacking = T>
void v8::internal::ScopedList< T, TBacking >::AddAll (base::Vector< const T > list) [inline]
Definition at line 83 of file scoped-list.h.
                                        {
    DCHECK_EQ(buffer_.size(), end_);
    buffer_.reserve(buffer_.size() + list.length());
    for (int i = 0; i < list.length(); i++) {
      buffer_.push_back(list.at(i));
    }
    end_ += list.length();
  }
References v8::base::Vector< T >::at(), DCHECK_EQ, and v8::base::Vector< T >::length().
Referenced by v8::internal::Parser::CloseTemplateLiteral().
at() [1/2]
template<typename T , typename TBacking = T>
T& v8::internal::ScopedList< T, TBacking >::at (int i) [inline]
Definition at line 65 of file scoped-list.h.
               {
    size_t index = start_ + i;
    DCHECK_LE(start_, index);
    DCHECK_LT(index, buffer_.size());
    return *reinterpret_cast<T*>(&buffer_[index]);
  }
References DCHECK_LE, DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::index.
at() [2/2]
template<typename T , typename TBacking = T>
const T& v8::internal::ScopedList< T, TBacking >::at (int i) const [inline]
Definition at line 58 of file scoped-list.h.
                           {
    size_t index = start_ + i;
    DCHECK_LE(start_, index);
    DCHECK_LT(index, buffer_.size());
    return *reinterpret_cast<T*>(&buffer_[index]);
  }
References DCHECK_LE, DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::index.
Referenced by v8::internal::Parser::DesugarLexicalBindingsInForStatement(), and v8::internal::Parser::DoParseProgram().
begin() [1/2]
template<typename T , typename TBacking = T>
iterator v8::internal::ScopedList< T, TBacking >::begin () [inline]
Definition at line 95 of file scoped-list.h.
                          {
    return reinterpret_cast<T*>(buffer_.data() + start_);
  }
begin() [2/2]
template<typename T , typename TBacking = T>
const_iterator v8::internal::ScopedList< T, TBacking >::begin () const [inline]
Definition at line 98 of file scoped-list.h.
                                      {
    return reinterpret_cast<T*>(buffer_.data() + start_);
  }
end() [1/2]
template<typename T , typename TBacking = T>
iterator v8::internal::ScopedList< T, TBacking >::end () [inline]
Definition at line 102 of file scoped-list.h.
{ return reinterpret_cast<T*>(buffer_.data() + end_); }
end() [2/2]
template<typename T , typename TBacking = T>
const_iterator v8::internal::ScopedList< T, TBacking >::end () const [inline]
Definition at line 103 of file scoped-list.h.
                                    {
    return reinterpret_cast<T*>(buffer_.data() + end_);
  }
length()
template<typename T , typename TBacking = T>
int v8::internal::ScopedList< T, TBacking >::length () const [inline]
Definition at line 56 of file scoped-list.h.
{ return static_cast<int>(end_ - start_); }
Referenced by v8::internal::Parser::DoParseProgram().
MergeInto()
template<typename T , typename TBacking = T>
void v8::internal::ScopedList< T, TBacking >::MergeInto (ScopedList< T, TBacking > * parent) [inline]
Definition at line 49 of file scoped-list.h.
                                     {
    DCHECK_EQ(parent->end_, start_);
    parent->end_ = end_;
    start_ = end_;
    DCHECK_EQ(0, length());
  }
References DCHECK_EQ, v8::internal::ScopedList< T, TBacking >::end_, and v8::internal::length.
Rewind()
template<typename T , typename TBacking = T>
void v8::internal::ScopedList< T, TBacking >::Rewind () [inline]
Definition at line 43 of file scoped-list.h.
                {
    DCHECK_EQ(buffer_.size(), end_);
    buffer_.resize(start_);
    end_ = start_;
  }
References DCHECK_EQ.
ToConstVector()
template<typename T , typename TBacking = T>
base::Vector<const T> v8::internal::ScopedList< T, TBacking >::ToConstVector () const [inline]
Definition at line 72 of file scoped-list.h.
                                            {
    T* data = reinterpret_cast<T*>(buffer_.data() + start_);
    return base::Vector<const T>(data, length());
  }
References v8::internal::length.
Member Data Documentation
buffer_
template<typename T , typename TBacking = T>
std::vector<TBacking>& v8::internal::ScopedList< T, TBacking >::buffer_ [private]
Definition at line 108 of file scoped-list.h.
end_
template<typename T , typename TBacking = T>
size_t v8::internal::ScopedList< T, TBacking >::end_ [private]
Definition at line 110 of file scoped-list.h.
Referenced by v8::internal::ScopedList< T, TBacking >::MergeInto().
start_
template<typename T , typename TBacking = T>
size_t v8::internal::ScopedList< T, TBacking >::start_ [private]
Definition at line 109 of file scoped-list.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/scoped-list.h