v8::internal::LinearAllocationArea Class Reference
#include <linear-allocation-area.h>
Public Member Functions
LinearAllocationArea ()=default
LinearAllocationArea (Address top, Address limit)
void Reset (Address top, Address limit)
void ResetStart ()
bool CanIncrementTop (size_t bytes) const
Address IncrementTop (size_t bytes)
bool DecrementTopIfAdjacent (Address new_top, size_t bytes)
void SetLimit (Address limit)
Address start () const
Address top () const
Address limit () const
const Address * top_address () const
Address * top_address ()
const Address * limit_address () const
Address * limit_address ()
void Verify () const
Static Public Attributes
static constexpr int kSize = 3 * kSystemPointerSize
Private Attributes
Address start_ = kNullAddress
Address top_ = kNullAddress
Address limit_ = kNullAddress
Detailed Description
Definition at line 20 of file linear-allocation-area.h.
Constructor & Destructor Documentation
LinearAllocationArea() [1/2]
v8::internal::LinearAllocationArea::LinearAllocationArea () [default]
LinearAllocationArea() [2/2]
v8::internal::LinearAllocationArea::LinearAllocationArea (Address top, Address limit) [inline]
Definition at line 23 of file linear-allocation-area.h.
      : start_(top), top_(top), limit_(limit) {
    Verify();
  }
References Verify().
Member Function Documentation
CanIncrementTop()
bool v8::internal::LinearAllocationArea::CanIncrementTop (size_t bytes) const [inline]
Definition at line 37 of file linear-allocation-area.h.
                                                     {
    Verify();
    return (top_ + bytes) <= limit_;
  }
References limit_, top_, and Verify().
DecrementTopIfAdjacent()
bool v8::internal::LinearAllocationArea::DecrementTopIfAdjacent (Address new_top, size_t bytes) [inline]
Definition at line 49 of file linear-allocation-area.h.
                                                                       {
    Verify();
    if ((new_top + bytes) == top_) {
      top_ = new_top;
      if (start_ > top_) {
        ResetStart();
      }
      Verify();
      return true;
    }
    return false;
  }
References ResetStart(), start_, top_, and Verify().
Referenced by v8::internal::MainAllocator::TryFreeLast().
IncrementTop()
Address v8::internal::LinearAllocationArea::IncrementTop (size_t bytes) [inline]
Definition at line 42 of file linear-allocation-area.h.
                                               {
    Address old_top = top_;
    top_ += bytes;
    Verify();
    return old_top;
  }
References top_, and Verify().
Referenced by v8::internal::MainAllocator::AlignTopForTesting().
limit()
Address v8::internal::LinearAllocationArea::limit () const [inline]
Definition at line 75 of file linear-allocation-area.h.
                                  {
    Verify();
    return limit_;
  }
References limit_, and Verify().
Referenced by v8::internal::PagedSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::MainAllocator::InvokeAllocationObservers(), Reset(), and SetLimit().
limit_address() [1/2]
Address* v8::internal::LinearAllocationArea::limit_address () [inline]
Definition at line 82 of file linear-allocation-area.h.
{ return &limit_; }
References limit_.
limit_address() [2/2]
const Address* v8::internal::LinearAllocationArea::limit_address () const [inline]
Definition at line 81 of file linear-allocation-area.h.
{ return &limit_; }
References limit_.
Referenced by v8::internal::Heap::NewSpaceAllocationLimitAddress().
Reset()
void v8::internal::LinearAllocationArea::Reset (Address top, Address limit) [inline]
Definition at line 28 of file linear-allocation-area.h.
                                         {
    start_ = top;
    top_ = top;
    limit_ = limit;
    Verify();
  }
References limit(), limit_, start_, top(), top_, and Verify().
Referenced by v8::internal::MainAllocator::ResetLab().
ResetStart()
void v8::internal::LinearAllocationArea::ResetStart () [inline]
Definition at line 35 of file linear-allocation-area.h.
{ start_ = top_; }
References start_, and top_.
Referenced by DecrementTopIfAdjacent(), and v8::internal::MainAllocator::MarkLabStartInitialized().
SetLimit()
void v8::internal::LinearAllocationArea::SetLimit (Address limit) [inline]
Definition at line 62 of file linear-allocation-area.h.
                                         {
    limit_ = limit;
    Verify();
  }
References limit(), limit_, and Verify().
Referenced by v8::internal::MainAllocator::ExtendLAB().
start()
Address v8::internal::LinearAllocationArea::start () const [inline]
Definition at line 67 of file linear-allocation-area.h.
                                  {
    Verify();
    return start_;
  }
References start_, and Verify().
Referenced by v8::internal::MainAllocator::InvokeAllocationObservers(), and v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList().
top()
Address v8::internal::LinearAllocationArea::top () const [inline]
Definition at line 71 of file linear-allocation-area.h.
                                {
    Verify();
    return top_;
  }
References top_, and Verify().
Referenced by v8::internal::MainAllocator::AllocateFastAligned(), v8::internal::PagedSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::MainAllocator::InvokeAllocationObservers(), Reset(), and v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList().
top_address() [1/2]
Address* v8::internal::LinearAllocationArea::top_address () [inline]
Definition at line 80 of file linear-allocation-area.h.
{ return &top_; }
References top_.
top_address() [2/2]
const Address* v8::internal::LinearAllocationArea::top_address () const [inline]
Definition at line 79 of file linear-allocation-area.h.
{ return &top_; }
References top_.
Referenced by v8::internal::Heap::NewSpaceAllocationTopAddress().
Verify()
void v8::internal::LinearAllocationArea::Verify () const [inline]
Definition at line 84 of file linear-allocation-area.h.
                      {
#ifdef DEBUG
    SLOW_DCHECK(start_ <= top_);
    SLOW_DCHECK(top_ <= limit_);
    if (V8_COMPRESS_POINTERS_8GB_BOOL) {
      SLOW_DCHECK(IsAligned(top_, kObjectAlignment8GbHeap));
    } else {
      SLOW_DCHECK(IsAligned(top_, kObjectAlignment));
    }
#endif // DEBUG
  }
References IsAligned(), v8::internal::kObjectAlignment, v8::internal::kObjectAlignment8GbHeap, limit_, SLOW_DCHECK, start_, top_, and V8_COMPRESS_POINTERS_8GB_BOOL.
Referenced by CanIncrementTop(), DecrementTopIfAdjacent(), IncrementTop(), limit(), LinearAllocationArea(), Reset(), SetLimit(), start(), and top().
Member Data Documentation
kSize
constexpr int v8::internal::LinearAllocationArea::kSize = 3 * kSystemPointerSize [static], [constexpr]
Definition at line 96 of file linear-allocation-area.h.
limit_
Address v8::internal::LinearAllocationArea::limit_ = kNullAddress [private]
Definition at line 106 of file linear-allocation-area.h.
Referenced by CanIncrementTop(), limit(), limit_address(), Reset(), SetLimit(), and Verify().
start_
Address v8::internal::LinearAllocationArea::start_ = kNullAddress [private]
Definition at line 102 of file linear-allocation-area.h.
Referenced by DecrementTopIfAdjacent(), Reset(), ResetStart(), start(), and Verify().
top_
Address v8::internal::LinearAllocationArea::top_ = kNullAddress [private]
Definition at line 104 of file linear-allocation-area.h.
Referenced by CanIncrementTop(), DecrementTopIfAdjacent(), IncrementTop(), Reset(), ResetStart(), top(), top_address(), and Verify().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/linear-allocation-area.h