v8::internal::SharedHeapSerializer Class Reference
#include <shared-heap-serializer.h>
Public Member Functions
SharedHeapSerializer (Isolate *isolate, Snapshot::SerializerFlags flags)
~SharedHeapSerializer () override
SharedHeapSerializer (const SharedHeapSerializer &)=delete
SharedHeapSerializer & operator= (const SharedHeapSerializer &)=delete
void FinalizeSerialization ()
bool SerializeUsingSharedHeapObjectCache (SnapshotByteSink *sink, Handle< HeapObject > obj)
Static Public Member Functions
static bool CanBeInSharedOldSpace (Tagged< HeapObject > obj)
static bool ShouldBeInSharedHeapObjectCache (Tagged< HeapObject > obj)
Private Member Functions
bool ShouldReconstructSharedHeapObjectCacheForTesting () const
void ReconstructSharedHeapObjectCacheForTesting ()
void SerializeStringTable (StringTable *string_table)
void SerializeObjectImpl (Handle< HeapObject > obj, SlotType slot_type) override
Additional Inherited Members
Detailed Description
Definition at line 19 of file shared-heap-serializer.h.
Constructor & Destructor Documentation
SharedHeapSerializer() [1/2]
v8::internal::SharedHeapSerializer::SharedHeapSerializer (Isolate * isolate, Snapshot::SerializerFlags flags)
Definition at line 37 of file shared-heap-serializer.cc.
    : RootsSerializer(isolate, flags, RootIndex::kFirstStrongRoot)
#ifdef DEBUG
      ,
      serialized_objects_(isolate->heap())
#endif
{
  if (ShouldReconstructSharedHeapObjectCacheForTesting()) {
    ReconstructSharedHeapObjectCacheForTesting();
  }
}
References v8::internal::kFirstStrongRoot, ReconstructSharedHeapObjectCacheForTesting(), and ShouldReconstructSharedHeapObjectCacheForTesting().
 SharedHeapSerializer()
v8::internal::SharedHeapSerializer::~SharedHeapSerializer () [override]
Definition at line 50 of file shared-heap-serializer.cc.
                                            {
  OutputStatistics("SharedHeapSerializer");
}
References v8::internal::Serializer::OutputStatistics().
SharedHeapSerializer() [2/2]
v8::internal::SharedHeapSerializer::SharedHeapSerializer (const SharedHeapSerializer &) [delete]
Member Function Documentation
CanBeInSharedOldSpace()
bool v8::internal::SharedHeapSerializer::CanBeInSharedOldSpace (Tagged< HeapObject > obj) [static]
Definition at line 15 of file shared-heap-serializer.cc.
                                                                       {
  if (ReadOnlyHeap::Contains(obj)) return false;
  if (IsString(obj)) {
    return IsInternalizedString(obj) ||
           String::IsInPlaceInternalizable(Cast<String>(obj));
  }
  return false;
}
References v8::internal::ReadOnlyHeap::Contains(), v8::internal::String::IsInPlaceInternalizable(), and v8::internal::InstanceTypeChecker::IsInternalizedString().
Referenced by FinalizeSerialization(), SerializeObjectImpl(), and ShouldBeInSharedHeapObjectCache().
FinalizeSerialization()
void v8::internal::SharedHeapSerializer::FinalizeSerialization ()
Definition at line 54 of file shared-heap-serializer.cc.
                                                 {
  // This is called after serialization of the startup and context snapshots
  // which entries are added to the shared heap object cache. Terminate the
  // cache with an undefined.
  Tagged<Object> undefined = ReadOnlyRoots(isolate()).undefined_value();
  VisitRootPointer(Root::kSharedHeapObjectCache, nullptr,
                   FullObjectSlot(&undefined));
  // When v8_flags.shared_string_table is true, all internalized and
  // internalizable-in-place strings are in the shared heap.
  SerializeStringTable(isolate()->string_table());
  SerializeDeferredObjects();
  Pad();
#ifdef DEBUG
  // Check that all serialized object are in shared heap and not RO. RO objects
  // should be in the RO snapshot.
  IdentityMap<int, base::DefaultAllocationPolicy>::IteratableScope it_scope(
      &serialized_objects_);
  for (auto it = it_scope.begin(); it != it_scope.end(); ++it) {
    Tagged<HeapObject> obj = Cast<HeapObject>(it.key());
    CHECK(CanBeInSharedOldSpace(obj));
    CHECK(!ReadOnlyHeap::Contains(obj));
  }
#endif
}
References v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope::begin(), CanBeInSharedOldSpace(), CHECK, v8::internal::ReadOnlyHeap::Contains(), v8::internal::IdentityMap< V, AllocationPolicy >::IteratableScope::end(), v8::internal::Serializer::isolate(), v8::internal::Serializer::Pad(), v8::internal::Serializer::SerializeDeferredObjects(), SerializeStringTable(), v8::internal::undefined, and v8::internal::RootVisitor::VisitRootPointer().
Referenced by v8::internal::Snapshot::Create().
operator=()
SharedHeapSerializer& v8::internal::SharedHeapSerializer::operator= (const SharedHeapSerializer &) [delete]
ReconstructSharedHeapObjectCacheForTesting()
void v8::internal::SharedHeapSerializer::ReconstructSharedHeapObjectCacheForTesting () [private]
Definition at line 203 of file shared-heap-serializer.cc.
                                                                      {
  std::vector<Tagged<Object>>* cache =
      isolate()->shared_space_isolate()->shared_heap_object_cache();
  // Don't reconstruct the final element, which is always undefined and marks
  // the end of the cache, since serializing the live Isolate may extend the
  // shared object cache.
  for (size_t i = 0, size = cache->size(); i < size - 1; i++) {
    Handle<HeapObject> obj(Cast<HeapObject>(cache->at(i)), isolate());
    DCHECK(ShouldBeInSharedHeapObjectCache(*obj));
    int cache_index = SerializeInObjectCache(obj);
    USE(cache_index);
    DCHECK_EQ(cache_index, i);
  }
  DCHECK(IsUndefined(cache->back(), isolate()));
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Serializer::isolate(), v8::internal::RootsSerializer::SerializeInObjectCache(), v8::internal::Isolate::shared_heap_object_cache(), v8::internal::Isolate::shared_space_isolate(), ShouldBeInSharedHeapObjectCache(), size(), and USE.
Referenced by SharedHeapSerializer().
SerializeObjectImpl()
void v8::internal::SharedHeapSerializer::SerializeObjectImpl (Handle< HeapObject > obj, SlotType slot_type) [override], [private], [virtual]
Implements v8::internal::Serializer.
Definition at line 162 of file shared-heap-serializer.cc.
                                                                   {
  // Objects in the shared heap cannot depend on per-Isolate roots but can
  // depend on RO roots since sharing objects requires sharing the RO space.
  DCHECK(CanBeInSharedOldSpace(*obj) || ReadOnlyHeap::Contains(*obj));
  {
    DisallowGarbageCollection no_gc;
    Tagged<HeapObject> raw = *obj;
    if (SerializeHotObject(raw)) return;
    if (IsRootAndHasBeenSerialized(raw) && SerializeRoot(raw)) return;
  }
  if (SerializeReadOnlyObjectReference(*obj, &sink_)) return;
  {
    DisallowGarbageCollection no_gc;
    Tagged<HeapObject> raw = *obj;
    if (SerializeBackReference(raw)) return;
    CheckRehashability(raw);
    DCHECK(!ReadOnlyHeap::Contains(raw));
  }
  ObjectSerializer object_serializer(this, obj, &sink_);
  object_serializer.Serialize(slot_type);
#ifdef DEBUG
  CHECK_NULL(serialized_objects_.Find(obj));
  // There's no "IdentitySet", so use an IdentityMap with a value that is
  // later ignored.
  serialized_objects_.Insert(obj, 0);
#endif
}
References CanBeInSharedOldSpace(), CHECK_NULL, v8::internal::RootsSerializer::CheckRehashability(), v8::internal::ReadOnlyHeap::Contains(), v8::internal::DCHECK(), v8::internal::RootsSerializer::IsRootAndHasBeenSerialized(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Serializer::ObjectSerializer::Serialize(), v8::internal::Serializer::SerializeBackReference(), v8::internal::Serializer::SerializeHotObject(), v8::internal::Serializer::SerializeReadOnlyObjectReference(), v8::internal::Serializer::SerializeRoot(), and v8::internal::Serializer::sink_.
SerializeStringTable()
void v8::internal::SharedHeapSerializer::SerializeStringTable (StringTable * string_table) [private]
Definition at line 110 of file shared-heap-serializer.cc.
                                                                         {
  // A StringTable is serialized as:
  //
  // N : int
  // string 1
  // string 2
  // ...
  // string N
  //
  // Notably, the hashmap structure, including empty and deleted elements, is
  // not serialized.
  sink_.PutUint30(string_table->NumberOfElements(),
                  "String table number of elements");
  // Custom RootVisitor which walks the string table, but only serializes the
  // string entries. This is an inline class to be able to access the non-public
  // SerializeObject method.
  class SharedHeapSerializerStringTableVisitor : public RootVisitor {
   public:
    explicit SharedHeapSerializerStringTableVisitor(
        SharedHeapSerializer* serializer)
        : serializer_(serializer) {}
    void VisitRootPointers(Root root, const char* description,
                           FullObjectSlot start, FullObjectSlot end) override {
      UNREACHABLE();
    }
    void VisitRootPointers(Root root, const char* description,
                           OffHeapObjectSlot start,
                           OffHeapObjectSlot end) override {
      DCHECK_EQ(root, Root::kStringTable);
      Isolate* isolate = serializer_->isolate();
      for (OffHeapObjectSlot current = start; current < end; ++current) {
        Tagged<Object> obj = current.load(isolate);
        if (IsHeapObject(obj)) {
          DCHECK(IsInternalizedString(obj));
          serializer_->SerializeObject(handle(Cast<HeapObject>(obj), isolate),
                                       SlotType::kAnySlot);
        }
      }
    }
   private:
    SharedHeapSerializer* serializer_;
  };
  SharedHeapSerializerStringTableVisitor string_table_visitor(this);
  isolate()->string_table()->IterateElements(&string_table_visitor);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::end(), v8::internal::handle(), v8::internal::IsHeapObject(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::Factory::isolate(), v8::internal::Serializer::isolate(), v8::internal::StringTable::IterateElements(), v8::internal::SerializerDeserializer::kAnySlot, v8::internal::StringTable::NumberOfElements(), v8::internal::SnapshotByteSink::PutUint30(), v8::internal::Serializer::sink_, v8::internal::Isolate::string_table(), v8::internal::UNREACHABLE(), and v8::internal::RootsSerializer::VisitRootPointers().
Referenced by FinalizeSerialization().
SerializeUsingSharedHeapObjectCache()
bool v8::internal::SharedHeapSerializer::SerializeUsingSharedHeapObjectCache (SnapshotByteSink * sink, Handle< HeapObject > obj)
Definition at line 81 of file shared-heap-serializer.cc.
                                                    {
  if (!ShouldBeInSharedHeapObjectCache(*obj)) return false;
  int cache_index = SerializeInObjectCache(obj);
  // When testing deserialization of a snapshot from a live Isolate where there
  // is also a shared Isolate, the shared object cache needs to be extended
  // because the live isolate may have had new internalized strings that were
  // not present in the startup snapshot to be serialized.
  if (ShouldReconstructSharedHeapObjectCacheForTesting()) {
    std::vector<Tagged<Object>>* existing_cache =
        isolate()->shared_space_isolate()->shared_heap_object_cache();
    const size_t existing_cache_size = existing_cache->size();
    // This is strictly < because the existing cache contains the terminating
    // undefined value, which the reconstructed cache does not.
    DCHECK_LT(base::checked_cast<size_t>(cache_index), existing_cache_size);
    if (base::checked_cast<size_t>(cache_index) == existing_cache_size - 1) {
      ReadOnlyRoots roots(isolate());
      DCHECK(IsUndefined(existing_cache->back(), roots));
      existing_cache->back() = *obj;
      existing_cache->push_back(roots.undefined_value());
    }
  }
  sink->Put(kSharedHeapObjectCache, "SharedHeapObjectCache");
  sink->PutUint30(cache_index, "shared_heap_object_cache_index");
  return true;
}
References v8::internal::DCHECK(), DCHECK_LT, v8::internal::Serializer::isolate(), v8::internal::SerializerDeserializer::kSharedHeapObjectCache, v8::internal::SnapshotByteSink::Put(), v8::internal::SnapshotByteSink::PutUint30(), v8::internal::RootsSerializer::SerializeInObjectCache(), v8::internal::Isolate::shared_heap_object_cache(), v8::internal::Isolate::shared_space_isolate(), ShouldBeInSharedHeapObjectCache(), and ShouldReconstructSharedHeapObjectCacheForTesting().
Referenced by v8::internal::StartupSerializer::SerializeUsingSharedHeapObjectCache().
ShouldBeInSharedHeapObjectCache()
bool v8::internal::SharedHeapSerializer::ShouldBeInSharedHeapObjectCache (Tagged< HeapObject > obj) [static]
Definition at line 25 of file shared-heap-serializer.cc.
                            {
  // To keep the shared heap object cache lean, only include objects that should
  // not be duplicated. Currently, that is only internalized strings. In-place
  // internalizable strings will still be allocated in the shared heap by the
  // deserializer, but do not need to be kept alive forever in the cache.
  if (CanBeInSharedOldSpace(obj)) {
    if (IsInternalizedString(obj)) return true;
  }
  return false;
}
References CanBeInSharedOldSpace(), and v8::internal::InstanceTypeChecker::IsInternalizedString().
Referenced by ReconstructSharedHeapObjectCacheForTesting(), and SerializeUsingSharedHeapObjectCache().
ShouldReconstructSharedHeapObjectCacheForTesting()
bool v8::internal::SharedHeapSerializer::ShouldReconstructSharedHeapObjectCacheForTesting () const [private]
Definition at line 194 of file shared-heap-serializer.cc.
          {
  // When the live Isolate being serialized is not a client Isolate, there's no
  // need to reconstruct the shared heap object cache because it is not actually
  // shared.
  return reconstruct_read_only_and_shared_object_caches_for_testing() &&
         isolate()->has_shared_space();
}
References v8::internal::Isolate::has_shared_space(), v8::internal::Serializer::isolate(), and v8::internal::Serializer::reconstruct_read_only_and_shared_object_caches_for_testing().
Referenced by SerializeUsingSharedHeapObjectCache(), and SharedHeapSerializer().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/shared-heap-serializer.h
/mnt/V8SourceCode/src/snapshot/shared-heap-serializer.cc