v8::internal::JSReceiver Class Reference
#include <js-objects.h>
Public Types
using IntegrityLevel = PropertyAttributes
Public Member Functions
void SetProperties (Tagged< HeapObject > properties)
void initialize_properties (Isolate *isolate)
V8_EXPORT_PRIVATE Tagged< String > class_name ()
V8_EXPORT_PRIVATE std::optional< Tagged< NativeContext > > GetCreationContext ()
V8_EXPORT_PRIVATE MaybeDirectHandle< NativeContext > GetCreationContext (Isolate *isolate)
V8_EXPORT_PRIVATE Tagged< Object > GetIdentityHash ()
V8_EXPORT_PRIVATE Tagged< Smi > GetOrCreateIdentityHash (Isolate *isolate)
V8_EXPORT_PRIVATE void SetIdentityHash (int masked_hash)
bool HasProxyInPrototype (Isolate *isolate)
bool IsCodeLike (Isolate *isolate) const
Static Public Member Functions
static void DeleteNormalizedProperty (DirectHandle< JSReceiver > object, InternalIndex entry)
static V8_EXPORT_PRIVATE MaybeHandle< NativeContext > GetContextForMicrotask (DirectHandle< JSReceiver > receiver)
static MaybeDirectHandle< JSPrototype > GetPrototype (Isolate *isolate, DirectHandle< JSReceiver > receiver)
static V8_WARN_UNUSED_RESULT Maybe< bool > HasInPrototypeChain (Isolate *isolate, DirectHandle< JSReceiver > object, DirectHandle< Object > proto)
static V8_WARN_UNUSED_RESULT Maybe< bool > SetOrCopyDataProperties (Isolate *isolate, DirectHandle< JSReceiver > target, DirectHandle< Object > source, PropertiesEnumerationMode mode, base::Vector< DirectHandle< Object >> excluded_properties={}, bool use_set=true)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Maybe< bool > HasProperty (LookupIterator *it)
static V8_WARN_UNUSED_RESULT Maybe< bool > HasProperty (Isolate *isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name)
static V8_WARN_UNUSED_RESULT Maybe< bool > HasElement (Isolate *isolate, DirectHandle< JSReceiver > object, uint32_t index)
static V8_WARN_UNUSED_RESULT Maybe< bool > HasPropertyOrElement (Isolate *isolate, DirectHandle< JSReceiver > object, PropertyKey key)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Maybe< bool > HasOwnProperty (Isolate *isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name)
static V8_WARN_UNUSED_RESULT Maybe< bool > HasOwnProperty (Isolate *isolate, DirectHandle< JSReceiver > object, uint32_t index)
static V8_WARN_UNUSED_RESULT MaybeHandle< Object > GetProperty (Isolate *isolate, DirectHandle< JSReceiver > receiver, const char *key)
static V8_WARN_UNUSED_RESULT MaybeHandle< Object > GetProperty (Isolate *isolate, DirectHandle< JSReceiver > receiver, DirectHandle< Name > name)
static V8_WARN_UNUSED_RESULT MaybeHandle< Object > GetElement (Isolate *isolate, DirectHandle< JSReceiver > receiver, uint32_t index)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Maybe< bool > DeletePropertyOrElement (Isolate *isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name, LanguageMode language_mode=LanguageMode::kSloppy)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Maybe< bool > DeletePropertyOrElement (Isolate *isolate, DirectHandle< JSReceiver > object, PropertyKey key, LanguageMode language_mode=LanguageMode::kSloppy)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Maybe< bool > DeleteProperty (Isolate *isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name, LanguageMode language_mode=LanguageMode::kSloppy)
static V8_WARN_UNUSED_RESULT Maybe< bool > DeleteProperty (LookupIterator *it, LanguageMode language_mode)
static V8_WARN_UNUSED_RESULT Maybe< bool > DeleteElement (Isolate *isolate, DirectHandle< JSReceiver > object, uint32_t index, LanguageMode language_mode=LanguageMode::kSloppy)
static V8_WARN_UNUSED_RESULT Tagged< Object > DefineProperty (Isolate *isolate, DirectHandle< Object > object, DirectHandle< Object > name, Handle< Object > attributes)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > DefineProperties (Isolate *isolate, DirectHandle< Object > object, DirectHandle< Object > properties)
static V8_WARN_UNUSED_RESULT Maybe< bool > DefineOwnProperty (Isolate *isolate, DirectHandle< JSReceiver > object, DirectHandle< Object > key, PropertyDescriptor *desc, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > CheckPrivateNameStore (LookupIterator *it, bool is_define)
static V8_WARN_UNUSED_RESULT Maybe< bool > CreateDataProperty (Isolate *isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > key, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > CreateDataProperty (Isolate *isolate, DirectHandle< JSAny > object, PropertyKey key, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > CreateDataProperty (Isolate *isolate, DirectHandle< JSReceiver > object, PropertyKey key, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > AddPrivateField (LookupIterator *it, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > OrdinaryDefineOwnProperty (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Object > key, PropertyDescriptor *desc, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > OrdinaryDefineOwnProperty (Isolate *isolate, DirectHandle< JSObject > object, const PropertyKey &key, PropertyDescriptor *desc, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > OrdinaryDefineOwnProperty (LookupIterator *it, PropertyDescriptor *desc, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > IsCompatiblePropertyDescriptor (Isolate *isolate, bool extensible, PropertyDescriptor *desc, PropertyDescriptor *current, DirectHandle< Name > property_name, Maybe< ShouldThrow > should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > ValidateAndApplyPropertyDescriptor (Isolate *isolate, LookupIterator *it, bool extensible, PropertyDescriptor *desc, PropertyDescriptor *current, Maybe< ShouldThrow > should_throw, DirectHandle< Name > property_name)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Maybe< bool > GetOwnPropertyDescriptor (Isolate *isolate, DirectHandle< JSReceiver > object, DirectHandle< Object > key, PropertyDescriptor *desc)
static V8_WARN_UNUSED_RESULT Maybe< bool > GetOwnPropertyDescriptor (LookupIterator *it, PropertyDescriptor *desc)
static V8_WARN_UNUSED_RESULT Maybe< bool > SetIntegrityLevel (Isolate *isolate, DirectHandle< JSReceiver > object, IntegrityLevel lvl, ShouldThrow should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > TestIntegrityLevel (Isolate *isolate, DirectHandle< JSReceiver > object, IntegrityLevel lvl)
static V8_WARN_UNUSED_RESULT Maybe< bool > PreventExtensions (Isolate *isolate, DirectHandle< JSReceiver > object, ShouldThrow should_throw)
static V8_WARN_UNUSED_RESULT Maybe< bool > IsExtensible (Isolate *isolate, DirectHandle< JSReceiver > object)
static MaybeDirectHandle< JSFunction > GetConstructor (Isolate *isolate, DirectHandle< JSReceiver > receiver)
static DirectHandle< String > GetConstructorName (Isolate *isolate, DirectHandle< JSReceiver > receiver)
static V8_WARN_UNUSED_RESULT Maybe< PropertyAttributes > GetPropertyAttributes (Isolate *isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name)
static V8_WARN_UNUSED_RESULT Maybe< PropertyAttributes > GetOwnPropertyAttributes (Isolate *isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name)
static V8_WARN_UNUSED_RESULT Maybe< PropertyAttributes > GetOwnPropertyAttributes (Isolate *isolate, DirectHandle< JSReceiver > object, uint32_t index)
static V8_WARN_UNUSED_RESULT Maybe< PropertyAttributes > GetElementAttributes (Isolate *isolate, DirectHandle< JSReceiver > object, uint32_t index)
static V8_WARN_UNUSED_RESULT Maybe< PropertyAttributes > GetOwnElementAttributes (Isolate *isolate, DirectHandle< JSReceiver > object, uint32_t index)
static V8_WARN_UNUSED_RESULT Maybe< PropertyAttributes > GetPropertyAttributes (LookupIterator *it)
V8_EXPORT_PRIVATE static V8_WARN_UNUSED_RESULT Maybe< bool > SetPrototype (Isolate *isolate, DirectHandle< JSReceiver > object, DirectHandle< Object > value, bool from_javascript, ShouldThrow should_throw)
static Handle< Object > GetDataProperty (Isolate *isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name)
static V8_EXPORT_PRIVATE Handle< Object > GetDataProperty (LookupIterator *it, AllocationPolicy allocation_policy=AllocationPolicy::kAllocationAllowed)
static Tagged< Smi > CreateIdentityHash (Isolate *isolate, Tagged< JSReceiver > key)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< FixedArray > OwnPropertyKeys (Isolate *isolate, DirectHandle< JSReceiver > object)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< FixedArray > GetOwnValues (Isolate *isolate, DirectHandle< JSReceiver > object, PropertyFilter filter, bool try_fast_path=true)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< FixedArray > GetOwnEntries (Isolate *isolate, DirectHandle< JSReceiver > object, PropertyFilter filter, bool try_fast_path=true)
Static Public Attributes
static const int kHashMask = PropertyArray::HashField::kMask
Detailed Description
Definition at line 46 of file js-objects.h.
Member Typedef Documentation
IntegrityLevel
using v8::internal::JSReceiver::IntegrityLevel = PropertyAttributes
Definition at line 252 of file js-objects.h.
Member Function Documentation
AddPrivateField()
Maybe< bool > v8::internal::JSReceiver::AddPrivateField (LookupIterator * it, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw) [static]
Definition at line 1783 of file js-objects.cc.
                                                                         {
  DirectHandle<JSReceiver> receiver = Cast<JSReceiver>(it->GetReceiver());
  DCHECK(!IsAlwaysSharedSpaceJSObject(*receiver));
  Isolate* isolate = it->isolate();
  DCHECK(it->GetName()->IsPrivateName());
  DirectHandle<Symbol> symbol = Cast<Symbol>(it->GetName());
  switch (it->state()) {
    case LookupIterator::JSPROXY: {
      PropertyDescriptor new_desc;
      new_desc.set_value(Cast<JSAny>(value));
      new_desc.set_writable(true);
      new_desc.set_enumerable(true);
      new_desc.set_configurable(true);
      return JSProxy::SetPrivateSymbol(isolate, Cast<JSProxy>(receiver), symbol,
                                       &new_desc, should_throw);
    }
    case LookupIterator::WASM_OBJECT:
      RETURN_FAILURE(isolate, kThrowOnError,
                     NewTypeError(MessageTemplate::kWasmObjectsAreOpaque));
    case LookupIterator::DATA:
    case LookupIterator::INTERCEPTOR:
    case LookupIterator::ACCESSOR:
    case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
    case LookupIterator::STRING_LOOKUP_START_OBJECT:
      UNREACHABLE();
    case LookupIterator::ACCESS_CHECK: {
      if (!it->HasAccess()) {
        RETURN_ON_EXCEPTION_VALUE(
            isolate,
            it->isolate()->ReportFailedAccessCheck(it->GetHolder<JSObject>()),
            Nothing<bool>());
        UNREACHABLE();
      }
      break;
    }
    case LookupIterator::TRANSITION:
    case LookupIterator::NOT_FOUND:
      break;
  }
  return Object::TransitionAndWriteDataProperty(it, value, NONE, should_throw,
                                                StoreOrigin::kMaybeKeyed);
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::LookupIterator::isolate(), v8::internal::LookupIterator::JSPROXY, v8::internal::kMaybeKeyed, v8::internal::kThrowOnError, v8::internal::NONE, v8::internal::LookupIterator::NOT_FOUND, v8::internal::Isolate::ReportFailedAccessCheck(), RETURN_FAILURE, RETURN_ON_EXCEPTION_VALUE, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), v8::internal::JSProxy::SetPrivateSymbol(), v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::internal::LookupIterator::TRANSITION, v8::internal::Object::TransitionAndWriteDataProperty(), v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), v8::internal::value, and v8::internal::LookupIterator::WASM_OBJECT.
Referenced by v8::internal::Runtime::DefineObjectOwnProperty(), and v8::internal::StoreIC::Store().
CheckPrivateNameStore()
Maybe< bool > v8::internal::JSReceiver::CheckPrivateNameStore (LookupIterator * it, bool is_define) [static]
Definition at line 208 of file js-objects.cc.
                                                              {
  DCHECK(it->GetName()->IsPrivateName());
  Isolate* isolate = it->isolate();
  DirectHandle<String> name_string(
      Cast<String>(Cast<Symbol>(it->GetName())->description()), isolate);
  for (;; it->Next()) {
    switch (it->state()) {
      case LookupIterator::TRANSITION:
      case LookupIterator::INTERCEPTOR:
      case LookupIterator::JSPROXY:
      case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
      case LookupIterator::ACCESSOR:
      case LookupIterator::STRING_LOOKUP_START_OBJECT:
        UNREACHABLE();
      case LookupIterator::ACCESS_CHECK:
        if (!it->HasAccess()) {
          RETURN_ON_EXCEPTION_VALUE(isolate,
                                    isolate->ReportFailedAccessCheck(
                                        Cast<JSObject>(it->GetReceiver())),
                                    Nothing<bool>());
          UNREACHABLE();
        }
        continue;
      case LookupIterator::DATA:
        if (is_define) {
          MessageTemplate message =
              it->GetName()->IsPrivateBrand()
                  ? MessageTemplate::kInvalidPrivateBrandReinitialization
                  : MessageTemplate::kInvalidPrivateFieldReinitialization;
          RETURN_FAILURE(isolate,
                         GetShouldThrow(isolate, Nothing<ShouldThrow>()),
                         NewTypeError(message, name_string, it->GetReceiver()));
        }
        return Just(true);
      case LookupIterator::WASM_OBJECT:
        RETURN_FAILURE(isolate, kThrowOnError,
                       NewTypeError(MessageTemplate::kWasmObjectsAreOpaque));
      case LookupIterator::NOT_FOUND:
        if (!is_define) {
          RETURN_FAILURE(
              isolate, GetShouldThrow(isolate, Nothing<ShouldThrow>()),
              NewTypeError(MessageTemplate::kInvalidPrivateMemberWrite,
                           name_string, it->GetReceiver()));
        } else if (it->ExtendingNonExtensible(
                       it->GetStoreTarget<JSReceiver>())) {
          RETURN_FAILURE(
              isolate, kThrowOnError,
              NewTypeError(MessageTemplate::kDefineDisallowed, name_string));
        }
        return Just(true);
    }
    UNREACHABLE();
  }
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), v8::internal::LookupIterator::ExtendingNonExtensible(), v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::GetReceiver(), v8::internal::GetShouldThrow(), v8::internal::LookupIterator::GetStoreTarget(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::LookupIterator::isolate(), v8::internal::LookupIterator::JSPROXY, v8::Just(), v8::internal::kThrowOnError, v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::NOT_FOUND, v8::internal::Isolate::ReportFailedAccessCheck(), RETURN_FAILURE, RETURN_ON_EXCEPTION_VALUE, v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), and v8::internal::LookupIterator::WASM_OBJECT.
Referenced by v8::internal::Runtime::DefineObjectOwnProperty(), v8::internal::Runtime::SetObjectProperty(), and v8::internal::StoreIC::Store().
class_name()
Tagged< String > v8::internal::JSReceiver::class_name ()
Definition at line 501 of file js-objects.cc.
                                      {
  ReadOnlyRoots roots = GetReadOnlyRoots();
  if (IsJSFunctionOrBoundFunctionOrWrappedFunction(*this)) {
    return roots.Function_string();
  }
  if (IsJSArgumentsObject(*this)) return roots.Arguments_string();
  if (IsJSArray(*this)) return roots.Array_string();
  if (IsJSArrayBuffer(*this)) {
    if (Cast<JSArrayBuffer>(*this)->is_shared()) {
      return roots.SharedArrayBuffer_string();
    }
    return roots.ArrayBuffer_string();
  }
  if (IsJSArrayIterator(*this)) return roots.ArrayIterator_string();
  if (IsJSDate(*this)) return roots.Date_string();
  if (IsJSError(*this)) return roots.Error_string();
  if (IsJSGeneratorObject(*this)) return roots.Generator_string();
  if (IsJSMap(*this)) return roots.Map_string();
  if (IsJSMapIterator(*this)) return roots.MapIterator_string();
  if (IsJSProxy(*this)) {
    return map()->is_callable() ? roots.Function_string()
                                : roots.Object_string();
  }
  if (IsJSRegExp(*this)) return roots.RegExp_string();
  if (IsJSSet(*this)) return roots.Set_string();
  if (IsJSSetIterator(*this)) return roots.SetIterator_string();
  if (IsJSTypedArray(*this)) {
#define SWITCH_KIND(Type, type, TYPE, ctype) \
  if (map()->elements_kind() == TYPE##_ELEMENTS) { \
    return roots.Type##Array_string(); \
  }
    TYPED_ARRAYS(SWITCH_KIND)
#undef SWITCH_KIND
  }
  if (IsJSPrimitiveWrapper(*this)) {
    Tagged<Object> value = Cast<JSPrimitiveWrapper>(*this)->value();
    if (IsBoolean(value)) return roots.Boolean_string();
    if (IsString(value)) return roots.String_string();
    if (IsNumber(value)) return roots.Number_string();
    if (IsBigInt(value)) return roots.BigInt_string();
    if (IsSymbol(value)) return roots.Symbol_string();
    if (IsScript(value)) return roots.Script_string();
    UNREACHABLE();
  }
  if (IsJSWeakMap(*this)) return roots.WeakMap_string();
  if (IsJSWeakSet(*this)) return roots.WeakSet_string();
  if (IsJSGlobalProxy(*this)) return roots.global_string();
  if (IsShared(*this)) {
    if (IsJSSharedStruct(*this)) return roots.SharedStruct_string();
    if (IsJSSharedArray(*this)) return roots.SharedArray_string();
    if (IsJSAtomicsMutex(*this)) return roots.AtomicsMutex_string();
    if (IsJSAtomicsCondition(*this)) return roots.AtomicsCondition_string();
    // Other shared values are primitives.
    UNREACHABLE();
  }
  return roots.Object_string();
}
References v8::internal::GetReadOnlyRoots(), v8::internal::IsNumber(), v8::internal::IsShared(), SWITCH_KIND, TYPED_ARRAYS, v8::internal::UNREACHABLE(), and v8::internal::value.
CreateDataProperty() [1/3]
Maybe< bool > v8::internal::JSReceiver::CreateDataProperty (Isolate * isolate, DirectHandle< JSAny > object, PropertyKey key, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw) [static]
Definition at line 1748 of file js-objects.cc.
                                                                            {
  if (!IsJSReceiver(*object)) {
    return Object::CannotCreateProperty(isolate, object, key.GetName(isolate),
                                        value, Nothing<ShouldThrow>());
  }
  return CreateDataProperty(isolate, Cast<JSReceiver>(object), key, value,
                            should_throw);
}
References v8::internal::Object::CannotCreateProperty(), CreateDataProperty(), v8::internal::key, and v8::internal::value.
CreateDataProperty() [2/3]
Maybe< bool > v8::internal::JSReceiver::CreateDataProperty (Isolate * isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > key, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw) [static]
Definition at line 1738 of file js-objects.cc.
                                                                            {
  return CreateDataProperty(isolate, object, PropertyKey(isolate, key), value,
                            should_throw);
}
References v8::internal::key, and v8::internal::value.
Referenced by v8::internal::BUILTIN(), CreateDataProperty(), v8::Object::CreateDataProperty(), v8::internal::anonymous_namespace{js-plural-rules.cc}::CreateDataPropertyForOptions(), v8::internal::anonymous_namespace{js-collator.cc}::CreateDataPropertyForOptions(), v8::internal::Runtime::DefineObjectOwnProperty(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::internal::JSLocale::GetTextInfo(), v8::internal::JSLocale::GetWeekInfo(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::JSCollator::ResolvedOptions(), v8::internal::JSDateTimeFormat::ResolvedOptions(), v8::internal::JSDisplayNames::ResolvedOptions(), v8::internal::JSNumberFormat::ResolvedOptions(), v8::internal::JSTemporalInstant::Round(), v8::internal::RUNTIME_FUNCTION(), SetOrCopyDataProperties(), v8::internal::Object::SetSuperProperty(), v8::internal::StoreIC::Store(), v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::visit(), and v8::internal::FutexEmulation::WaitAsync().
CreateDataProperty() [3/3]
Maybe< bool > v8::internal::JSReceiver::CreateDataProperty (Isolate * isolate, DirectHandle< JSReceiver > object, PropertyKey key, DirectHandle< Object > value, Maybe< ShouldThrow > should_throw) [static]
Definition at line 1762 of file js-objects.cc.
                                                                            {
  if (IsJSObject(*object)) {
    return JSObject::CreateDataProperty(isolate, Cast<JSObject>(object), key,
                                        value, should_throw); // Shortcut.
  }
  PropertyDescriptor new_desc;
  new_desc.set_value(Cast<JSAny>(value));
  new_desc.set_writable(true);
  new_desc.set_enumerable(true);
  new_desc.set_configurable(true);
  return JSReceiver::DefineOwnProperty(isolate, object, key.GetName(isolate),
                                       &new_desc, should_throw);
}
References v8::internal::JSObject::CreateDataProperty(), DefineOwnProperty(), v8::internal::key, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), and v8::internal::value.
CreateIdentityHash()
Tagged< Smi > v8::internal::JSReceiver::CreateIdentityHash (Isolate * isolate, Tagged< JSReceiver > key) [static]
Definition at line 853 of file js-objects.cc.
                                                                   {
  DisallowGarbageCollection no_gc;
  int hash = isolate->GenerateIdentityHash(PropertyArray::HashField::kMax);
  DCHECK_NE(PropertyArray::kNoHashSentinel, hash);
  key->SetIdentityHash(hash);
  return Smi::FromInt(hash);
}
References DCHECK_NE, v8::internal::Smi::FromInt(), v8::internal::Isolate::GenerateIdentityHash(), v8::internal::key, v8::base::BitField< T, shift, size, U >::kMax, v8::internal::PropertyArray::kNoHashSentinel, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by GetOrCreateIdentityHash(), and v8::internal::JSReceiverCreateIdentityHash().
DefineOwnProperty()
Maybe< bool > v8::internal::JSReceiver::DefineOwnProperty (Isolate * isolate, DirectHandle< JSReceiver > object, DirectHandle< Object > key, PropertyDescriptor * desc, Maybe< ShouldThrow > should_throw) [static]
Definition at line 1143 of file js-objects.cc.
                                                                           {
  if (IsJSArray(*object)) {
    return JSArray::DefineOwnProperty(isolate, Cast<JSArray>(object), key, desc,
                                      should_throw);
  }
  if (IsJSProxy(*object)) {
    return JSProxy::DefineOwnProperty(isolate, Cast<JSProxy>(object), key, desc,
                                      should_throw);
  }
  if (IsJSTypedArray(*object)) {
    return JSTypedArray::DefineOwnProperty(isolate, Cast<JSTypedArray>(object),
                                           key, desc, should_throw);
  }
  if (IsJSModuleNamespace(*object)) {
    return JSModuleNamespace::DefineOwnProperty(
        isolate, Cast<JSModuleNamespace>(object), key, desc, should_throw);
  }
  if (IsWasmObject(*object)) {
    RETURN_FAILURE(isolate, kThrowOnError,
                   NewTypeError(MessageTemplate::kWasmObjectsAreOpaque));
  }
  if (IsAlwaysSharedSpaceJSObject(*object)) {
    return AlwaysSharedSpaceJSObject::DefineOwnProperty(
        isolate, Cast<AlwaysSharedSpaceJSObject>(object), key, desc,
        should_throw);
  }
  // OrdinaryDefineOwnProperty, by virtue of calling
  // DefineOwnPropertyIgnoreAttributes, can handle arguments
  // (ES#sec-arguments-exotic-objects-defineownproperty-p-desc).
  return OrdinaryDefineOwnProperty(isolate, Cast<JSObject>(object), key, desc,
                                   should_throw);
}
References v8::internal::AlwaysSharedSpaceJSObject::DefineOwnProperty(), v8::internal::JSArray::DefineOwnProperty(), v8::internal::JSModuleNamespace::DefineOwnProperty(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::internal::IsWasmObject(), v8::internal::key, v8::internal::kThrowOnError, OrdinaryDefineOwnProperty(), and RETURN_FAILURE.
Referenced by v8::internal::BUILTIN(), v8::internal::ErrorUtils::CaptureStackTrace(), CreateDataProperty(), v8::internal::JSProxy::DefineOwnProperty(), v8::Object::DefineOwnProperty(), DefineProperties(), DefineProperty(), v8::Object::DefineProperty(), v8::internal::wasm::JSPrototypesSetup::InstallMethodImpl(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectDefineAccessor(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::JsonParseInternalizer::RecurseAndApply(), v8::Object::SetAccessorProperty(), SetIntegrityLevel(), and v8::internal::Object::SetSuperProperty().
DefineProperties()
MaybeDirectHandle< Object > v8::internal::JSReceiver::DefineProperties (Isolate * isolate, DirectHandle< Object > object, DirectHandle< Object > properties) [static]
Definition at line 1070 of file js-objects.cc.
                                     {
  // 1. If Type(O) is not Object, throw a TypeError exception.
  if (!IsJSReceiver(*object)) {
    DirectHandle<String> fun_name =
        isolate->factory()->InternalizeUtf8String("Object.defineProperties");
    THROW_NEW_ERROR(
        isolate, NewTypeError(MessageTemplate::kCalledOnNonObject, fun_name));
  }
  // 2. Let props be ToObject(Properties).
  // 3. ReturnIfAbrupt(props).
  DirectHandle<JSReceiver> props;
  ASSIGN_RETURN_ON_EXCEPTION(isolate, props,
                             Object::ToObject(isolate, properties));
  // 4. Let keys be props.[[OwnPropertyKeys]]().
  // 5. ReturnIfAbrupt(keys).
  DirectHandle<FixedArray> keys;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, keys,
      KeyAccumulator::GetKeys(isolate, props, KeyCollectionMode::kOwnOnly,
                              ALL_PROPERTIES));
  // 6. Let descriptors be an empty List.s
  int capacity = keys->length();
  std::vector<PropertyDescriptor> descriptors(capacity);
  size_t descriptors_index = 0;
  // 7. Repeat for each element nextKey of keys in List order,
  for (int i = 0; i < keys->length(); ++i) {
    DirectHandle<JSAny> next_key(Cast<JSAny>(keys->get(i)), isolate);
    // 7a. Let propDesc be props.[[GetOwnProperty]](nextKey).
    // 7b. ReturnIfAbrupt(propDesc).
    PropertyKey key(isolate, next_key);
    LookupIterator it(isolate, props, key, LookupIterator::OWN);
    Maybe<PropertyAttributes> maybe = JSReceiver::GetPropertyAttributes(&it);
    if (maybe.IsNothing()) return MaybeDirectHandle<Object>();
    PropertyAttributes attrs = maybe.FromJust();
    // 7c. If propDesc is not undefined and propDesc.[[Enumerable]] is true:
    if (attrs == ABSENT) continue;
    if (attrs & DONT_ENUM) continue;
    // 7c i. Let descObj be Get(props, nextKey).
    // 7c ii. ReturnIfAbrupt(descObj).
    Handle<JSAny> desc_obj;
    ASSIGN_RETURN_ON_EXCEPTION(isolate, desc_obj,
                               Cast<JSAny>(Object::GetProperty(&it)));
    // 7c iii. Let desc be ToPropertyDescriptor(descObj).
    bool success = PropertyDescriptor::ToPropertyDescriptor(
        isolate, desc_obj, &descriptors[descriptors_index]);
    // 7c iv. ReturnIfAbrupt(desc).
    if (!success) return MaybeDirectHandle<Object>();
    // 7c v. Append the pair (a two element List) consisting of nextKey and
    // desc to the end of descriptors.
    descriptors[descriptors_index].set_name(next_key);
    descriptors_index++;
  }
  // 8. For each pair from descriptors in list order,
  for (size_t i = 0; i < descriptors_index; ++i) {
    PropertyDescriptor* desc = &descriptors[i];
    // 8a. Let P be the first element of pair.
    // 8b. Let desc be the second element of pair.
    // 8c. Let status be DefinePropertyOrThrow(O, P, desc).
    Maybe<bool> status =
        DefineOwnProperty(isolate, Cast<JSReceiver>(object), desc->name(), desc,
                          Just(kThrowOnError));
    // 8d. ReturnIfAbrupt(status).
    if (status.IsNothing()) return MaybeDirectHandle<Object>();
    CHECK(status.FromJust());
  }
  // 9. Return o.
  return object;
}
References v8::internal::ABSENT, v8::internal::ALL_PROPERTIES, ASSIGN_RETURN_ON_EXCEPTION, CHECK, DefineOwnProperty(), v8::internal::DONT_ENUM, v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::Object::GetProperty(), GetPropertyAttributes(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Factory::InternalizeUtf8String(), v8::Maybe< T >::IsNothing(), v8::Just(), v8::internal::key, v8::internal::kOwnOnly, v8::internal::kThrowOnError, v8::internal::PropertyDescriptor::name(), v8::internal::LookupIterator::OWN, v8::internal::status, THROW_NEW_ERROR, v8::Value::ToObject(), and v8::internal::PropertyDescriptor::ToPropertyDescriptor().
Referenced by v8::internal::BUILTIN(), and v8::internal::RUNTIME_FUNCTION().
DefineProperty()
Tagged< Object > v8::internal::JSReceiver::DefineProperty (Isolate * isolate, DirectHandle< Object > object, DirectHandle< Object > name, Handle< Object > attributes) [static]
Definition at line 1036 of file js-objects.cc.
                                                                     {
  // 1. If Type(O) is not Object, throw a TypeError exception.
  if (!IsJSReceiver(*object)) {
    DirectHandle<String> fun_name =
        isolate->factory()->InternalizeUtf8String("Object.defineProperty");
    THROW_NEW_ERROR_RETURN_FAILURE(
        isolate, NewTypeError(MessageTemplate::kCalledOnNonObject, fun_name));
  }
  // 2. Let key be ToPropertyKey(P).
  // 3. ReturnIfAbrupt(key).
  ASSIGN_RETURN_FAILURE_ON_EXCEPTION(isolate, key,
                                     Object::ToPropertyKey(isolate, key));
  // 4. Let desc be ToPropertyDescriptor(Attributes).
  // 5. ReturnIfAbrupt(desc).
  PropertyDescriptor desc;
  if (!PropertyDescriptor::ToPropertyDescriptor(
          isolate, Cast<JSAny>(attributes), &desc)) {
    return ReadOnlyRoots(isolate).exception();
  }
  // 6. Let success be DefinePropertyOrThrow(O,key, desc).
  Maybe<bool> success = DefineOwnProperty(isolate, Cast<JSReceiver>(object),
                                          key, &desc, Just(kThrowOnError));
  // 7. ReturnIfAbrupt(success).
  MAYBE_RETURN(success, ReadOnlyRoots(isolate).exception());
  CHECK(success.FromJust());
  // 8. Return O.
  return *object;
}
References ASSIGN_RETURN_FAILURE_ON_EXCEPTION, CHECK, DefineOwnProperty(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::Factory::InternalizeUtf8String(), v8::Just(), v8::internal::key, v8::internal::kThrowOnError, MAYBE_RETURN, THROW_NEW_ERROR_RETURN_FAILURE, and v8::internal::PropertyDescriptor::ToPropertyDescriptor().
Referenced by v8::internal::BUILTIN().
DeleteElement()
Maybe< bool > v8::internal::JSReceiver::DeleteElement (Isolate * isolate, DirectHandle< JSReceiver > object, uint32_t index, LanguageMode language_mode = LanguageMode::kSloppy) [static]
Definition at line 1002 of file js-objects.cc.
                                                                  {
  LookupIterator it(isolate, object, index, object, LookupIterator::OWN);
  return DeleteProperty(&it, language_mode);
}
References DeleteProperty(), v8::internal::index, and v8::internal::LookupIterator::OWN.
Referenced by v8::Object::Delete().
DeleteNormalizedProperty()
void v8::internal::JSReceiver::DeleteNormalizedProperty (DirectHandle< JSReceiver > object, InternalIndex entry) [static]
Definition at line 874 of file js-objects.cc.
                                                               {
  DCHECK(!object->HasFastProperties());
  Isolate* isolate = Isolate::Current();
  DCHECK(entry.is_found());
  if (IsJSGlobalObject(*object)) {
    // If we have a global object, invalidate the cell and remove it from the
    // global object's dictionary.
    DirectHandle<GlobalDictionary> dictionary(
        Cast<JSGlobalObject>(*object)->global_dictionary(kAcquireLoad),
        isolate);
    DirectHandle<PropertyCell> cell(dictionary->CellAt(entry), isolate);
    DirectHandle<GlobalDictionary> new_dictionary =
        GlobalDictionary::DeleteEntry(isolate, dictionary, entry);
    Cast<JSGlobalObject>(*object)->set_global_dictionary(*new_dictionary,
                                                         kReleaseStore);
    cell->ClearAndInvalidate(isolate);
  } else {
    if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      DirectHandle<SwissNameDictionary> dictionary(
          object->property_dictionary_swiss(), isolate);
      dictionary = SwissNameDictionary::DeleteEntry(isolate, dictionary, entry);
      object->SetProperties(*dictionary);
    } else {
      DirectHandle<NameDictionary> dictionary(object->property_dictionary(),
                                              isolate);
      dictionary = NameDictionary::DeleteEntry(isolate, dictionary, entry);
      object->SetProperties(*dictionary);
    }
  }
  if (object->map()->is_prototype_map()) {
    // Invalidate prototype validity cell as this may invalidate transitioning
    // store IC handlers.
    JSObject::InvalidatePrototypeChains(object->map());
  }
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::JSObject::InvalidatePrototypeChains(), v8::internal::InternalIndex::is_found(), v8::kAcquireLoad, v8::kReleaseStore, and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by v8::internal::LookupIterator::Delete().
DeleteProperty() [1/2]
Maybe< bool > v8::internal::JSReceiver::DeleteProperty (Isolate * isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name, LanguageMode language_mode = LanguageMode::kSloppy) [static]
Definition at line 1010 of file js-objects.cc.
                                                                   {
  LookupIterator it(isolate, object, name, object, LookupIterator::OWN);
  return DeleteProperty(&it, language_mode);
}
References v8::internal::name, and v8::internal::LookupIterator::OWN.
Referenced by DeleteElement(), v8::internal::Runtime::DeleteObjectProperty(), DeletePropertyOrElement(), and v8::internal::RUNTIME_FUNCTION().
DeleteProperty() [2/2]
Maybe< bool > v8::internal::JSReceiver::DeleteProperty (LookupIterator * it, LanguageMode language_mode) [static]
Definition at line 917 of file js-objects.cc.
                                                                   {
  it->UpdateProtector();
  Isolate* isolate = it->isolate();
  if (it->state() == LookupIterator::JSPROXY) {
    return JSProxy::DeletePropertyOrElement(it->GetHolder<JSProxy>(),
                                            it->GetName(), language_mode);
  }
  if (IsJSProxy(*it->GetReceiver())) {
    if (it->state() != LookupIterator::NOT_FOUND) {
      DCHECK_EQ(LookupIterator::DATA, it->state());
      DCHECK(it->name()->IsPrivate());
      it->Delete();
    }
    return Just(true);
  }
  for (;; it->Next()) {
    switch (it->state()) {
      case LookupIterator::JSPROXY:
      case LookupIterator::TRANSITION:
      case LookupIterator::STRING_LOOKUP_START_OBJECT:
        UNREACHABLE();
      case LookupIterator::WASM_OBJECT:
        RETURN_FAILURE(isolate, kThrowOnError,
                       NewTypeError(MessageTemplate::kWasmObjectsAreOpaque));
      case LookupIterator::ACCESS_CHECK:
        if (it->HasAccess()) continue;
        RETURN_ON_EXCEPTION_VALUE(
            isolate,
            isolate->ReportFailedAccessCheck(it->GetHolder<JSObject>()),
            Nothing<bool>());
        UNREACHABLE();
      case LookupIterator::INTERCEPTOR: {
        ShouldThrow should_throw =
            is_sloppy(language_mode) ? kDontThrow : kThrowOnError;
        InterceptorResult result;
        if (!JSObject::DeletePropertyWithInterceptor(it, should_throw)
                 .To(&result)) {
          // An exception was thrown in the interceptor. Propagate.
          return Nothing<bool>();
        }
        switch (result) {
          case InterceptorResult::kFalse:
            return Just(false);
          case InterceptorResult::kTrue:
            return Just(true);
          case InterceptorResult::kNotIntercepted:
            // Proceed lookup.
            continue;
        }
        UNREACHABLE();
      }
      case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
        return Just(true);
      case LookupIterator::DATA:
      case LookupIterator::ACCESSOR: {
        DirectHandle<JSObject> holder = it->GetHolder<JSObject>();
        if (!it->IsConfigurable() ||
            (IsJSTypedArray(*holder) && it->IsElement(*holder))) {
          // Fail if the property is not configurable if the property is a
          // TypedArray element.
          if (is_strict(language_mode)) {
            isolate->Throw(*isolate->factory()->NewTypeError(
                MessageTemplate::kStrictDeleteProperty, it->GetName(),
                it->GetReceiver()));
            return Nothing<bool>();
          }
          return Just(false);
        }
        it->Delete();
        return Just(true);
      }
      case LookupIterator::NOT_FOUND:
        return Just(true);
    }
    UNREACHABLE();
  }
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, v8::internal::LookupIterator::DATA, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::LookupIterator::Delete(), v8::internal::JSProxy::DeletePropertyOrElement(), v8::internal::JSObject::DeletePropertyWithInterceptor(), v8::internal::Isolate::factory(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), v8::internal::LookupIterator::GetReceiver(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::is_sloppy(), v8::internal::is_strict(), v8::internal::LookupIterator::IsConfigurable(), v8::internal::LookupIterator::IsElement(), v8::internal::LookupIterator::isolate(), v8::internal::LookupIterator::JSPROXY, v8::Just(), v8::internal::kDontThrow, v8::internal::kFalse, v8::internal::kNotIntercepted, v8::internal::kThrowOnError, v8::internal::kTrue, v8::internal::LookupIterator::name(), v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::NOT_FOUND, v8::internal::Isolate::ReportFailedAccessCheck(), v8::base::internal::result, RETURN_FAILURE, RETURN_ON_EXCEPTION_VALUE, v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::internal::Isolate::Throw(), v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), v8::internal::LookupIterator::UpdateProtector(), and v8::internal::LookupIterator::WASM_OBJECT.
DeletePropertyOrElement() [1/2]
Maybe< bool > v8::internal::JSReceiver::DeletePropertyOrElement (Isolate * isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name, LanguageMode language_mode = LanguageMode::kSloppy) [static]
Definition at line 1018 of file js-objects.cc.
                                                                            {
  return DeletePropertyOrElement(isolate, object, PropertyKey(isolate, name),
                                 language_mode);
}
References v8::internal::name.
Referenced by v8::internal::JSProxy::DeletePropertyOrElement(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPop(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayShift(), and v8::internal::JsonParseInternalizer::RecurseAndApply().
DeletePropertyOrElement() [2/2]
Maybe< bool > v8::internal::JSReceiver::DeletePropertyOrElement (Isolate * isolate, DirectHandle< JSReceiver > object, PropertyKey key, LanguageMode language_mode = LanguageMode::kSloppy) [static]
Definition at line 1026 of file js-objects.cc.
                                                                            {
  LookupIterator it(isolate, object, key, object, LookupIterator::OWN);
  return DeleteProperty(&it, language_mode);
}
References DeleteProperty(), v8::internal::key, and v8::internal::LookupIterator::OWN.
GetConstructor()
MaybeDirectHandle< JSFunction > v8::internal::JSReceiver::GetConstructor (Isolate * isolate, DirectHandle< JSReceiver > receiver) [static]
Definition at line 640 of file js-objects.cc.
                                                         {
  return GetConstructorHelper(isolate, receiver).first;
}
References v8::internal::anonymous_namespace{js-objects.cc}::GetConstructorHelper().
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompilationExceptionIsRangeError(), and v8::internal::V8HeapExplorer::GetConstructor().
GetConstructorName()
DirectHandle< String > v8::internal::JSReceiver::GetConstructorName (Isolate * isolate, DirectHandle< JSReceiver > receiver) [static]
Definition at line 646 of file js-objects.cc.
                                                         {
  return GetConstructorHelper(isolate, receiver).second;
}
References v8::internal::anonymous_namespace{js-objects.cc}::GetConstructorHelper().
Referenced by v8::internal::CircularStructureMessageBuilder::AppendConstructorName(), v8::Object::GetConstructorName(), v8::internal::V8HeapExplorer::GetConstructorName(), v8::internal::CallSiteInfo::GetTypeName(), and v8::internal::Isolate::ReportExceptionPropertyCallback().
GetContextForMicrotask()
MaybeHandle< NativeContext > v8::internal::JSReceiver::GetContextForMicrotask (DirectHandle< JSReceiver > receiver) [static]
Definition at line 693 of file js-objects.cc.
                                       {
  Isolate* isolate = Isolate::Current();
  while (IsJSBoundFunction(*receiver) || IsJSProxy(*receiver)) {
    if (IsJSBoundFunction(*receiver)) {
      receiver = direct_handle(
          Cast<JSBoundFunction>(receiver)->bound_target_function(), isolate);
    } else {
      DCHECK(IsJSProxy(*receiver));
      DirectHandle<Object> target(Cast<JSProxy>(receiver)->target(), isolate);
      if (!IsJSReceiver(*target)) return MaybeHandle<NativeContext>();
      receiver = Cast<JSReceiver>(target);
    }
  }
  if (!IsJSFunction(*receiver)) return MaybeHandle<NativeContext>();
  return handle(Cast<JSFunction>(receiver)->native_context(), isolate);
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::handle(), and v8::internal::native_context.
Referenced by v8::Isolate::EnqueueMicrotask(), v8::internal::JSPromise::Resolve(), and v8::internal::JSPromise::TriggerPromiseReactions().
GetCreationContext() [1/2]
std::optional< Tagged< NativeContext > > v8::internal::JSReceiver::GetCreationContext () [inline]
Definition at line 923 of file js-objects-inl.h.
                                                                  {
  DisallowGarbageCollection no_gc;
  Tagged<Map> meta_map = map()->map();
  DCHECK(IsMapMap(meta_map));
  Tagged<Object> maybe_native_context = meta_map->native_context_or_null();
  if (V8_UNLIKELY(IsNull(maybe_native_context))) return {};
  DCHECK(IsNativeContext(maybe_native_context));
  return Cast<NativeContext>(maybe_native_context);
}
References DCHECK, v8::internal::IsNull(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and V8_UNLIKELY.
Referenced by GetOwnPropertyDescriptor(), and v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor().
GetCreationContext() [2/2]
MaybeDirectHandle< NativeContext > v8::internal::JSReceiver::GetCreationContext (Isolate * isolate) [inline]
Definition at line 933 of file js-objects-inl.h.
                      {
  DisallowGarbageCollection no_gc;
  std::optional<Tagged<NativeContext>> maybe_context = GetCreationContext();
  if (!maybe_context.has_value()) return {};
  return direct_handle(maybe_context.value(), isolate);
}
References v8::internal::direct_handle(), v8::debug::GetCreationContext(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetDataProperty() [1/2]
Handle< Object > v8::internal::JSReceiver::GetDataProperty (Isolate * isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name) [inline], [static]
Definition at line 101 of file js-objects-inl.h.
                                                                    {
  LookupIterator it(isolate, object, name, object,
                    LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR);
  if (!it.IsFound()) return it.factory()->undefined_value();
  return GetDataProperty(&it);
}
References v8::internal::LookupIterator::factory(), v8::internal::LookupIterator::IsFound(), and name.
Referenced by v8::internal::anonymous_namespace{asm-js.cc}::AreStdlibMembersValid(), v8::internal::BUILTIN(), v8::internal::anonymous_namespace{template-objects.cc}::CachedTemplateMatches(), v8::internal::Isolate::ComputeLocationFromException(), v8::internal::anonymous_namespace{js-objects.cc}::GetConstructorHelper(), v8::internal::JSFunction::GetDerivedMap(), v8::internal::ErrorUtils::GetErrorStackProperty(), v8::debug::GetMessageFromPromise(), v8::internal::Isolate::GetStackTraceLimit(), v8::internal::anonymous_namespace{objects.cc}::NoSideEffectsErrorToString(), v8::internal::Object::NoSideEffectsToMaybeString(), v8::internal::Object::NoSideEffectsToString(), v8::internal::Debug::PrepareStep(), v8::internal::anonymous_namespace{isolate.cc}::ReceiverIsForwardingHandler(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{asm-js.cc}::StdlibMathMember(), v8::internal::JSFunction::ToString(), v8::internal::ErrorUtils::ToString(), v8::internal::DebugEvaluate::ContextBuilder::UpdateValues(), and v8::internal::ScopeIterator::VisitLocalScope().
GetDataProperty() [2/2]
Handle< Object > v8::internal::JSReceiver::GetDataProperty (LookupIterator * it, AllocationPolicy allocation_policy = AllocationPolicy::kAllocationAllowed) [static]
Definition at line 159 of file js-objects.cc.
                                                                               {
  for (;; it->Next()) {
    switch (it->state()) {
      case LookupIterator::INTERCEPTOR:
      case LookupIterator::TRANSITION:
      case LookupIterator::STRING_LOOKUP_START_OBJECT:
        UNREACHABLE();
      case LookupIterator::ACCESS_CHECK:
        // Support calling this method without an active context, but refuse
        // access to access-checked objects in that case.
        if (!it->isolate()->context().is_null() && it->HasAccess()) continue;
        [[fallthrough]];
      case LookupIterator::JSPROXY:
        it->NotFound();
        return it->isolate()->factory()->undefined_value();
      case LookupIterator::WASM_OBJECT:
        continue; // Continue to the prototype, if present.
      case LookupIterator::ACCESSOR:
        // TODO(verwaest): For now this doesn't call into AccessorInfo, since
        // clients don't need it. Update once relevant.
        it->NotFound();
        return it->isolate()->factory()->undefined_value();
      case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
        return it->isolate()->factory()->undefined_value();
      case LookupIterator::DATA:
        return it->GetDataValue(allocation_policy);
      case LookupIterator::NOT_FOUND:
        return it->isolate()->factory()->undefined_value();
    }
    UNREACHABLE();
  }
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, v8::internal::Isolate::context(), v8::internal::LookupIterator::DATA, v8::internal::Isolate::factory(), v8::internal::LookupIterator::GetDataValue(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::LookupIterator::isolate(), v8::internal::LookupIterator::JSPROXY, v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::NOT_FOUND, v8::internal::LookupIterator::NotFound(), v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), and v8::internal::LookupIterator::WASM_OBJECT.
GetElement()
MaybeHandle< Object > v8::internal::JSReceiver::GetElement (Isolate * isolate, DirectHandle< JSReceiver > receiver, uint32_t index) [inline], [static]
Definition at line 93 of file js-objects-inl.h.
                                                           {
  LookupIterator it(isolate, receiver, index, receiver);
  if (!it.IsFound()) return it.factory()->undefined_value();
  return Object::GetProperty(&it);
}
References v8::internal::LookupIterator::factory(), v8::internal::index, and v8::internal::LookupIterator::IsFound().
Referenced by v8::internal::BUILTIN(), v8::internal::anonymous_namespace{builtins-struct.cc}::CollectFieldsAndElements(), v8::internal::Object::CreateListFromArrayLike(), v8::Object::Get(), v8::Array::Iterate(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElementsSlow(), and v8::internal::JsonStringifier::SerializeArrayLikeSlow().
GetElementAttributes()
Maybe< PropertyAttributes > v8::internal::JSReceiver::GetElementAttributes (Isolate * isolate, DirectHandle< JSReceiver > object, uint32_t index) [inline], [static]
Definition at line 997 of file js-objects-inl.h.
                                                                       {
  LookupIterator it(isolate, object, index, object);
  return GetPropertyAttributes(&it);
}
References v8::internal::index.
GetIdentityHash()
Tagged< Object > v8::internal::JSReceiver::GetIdentityHash ()
Definition at line 841 of file js-objects.cc.
                                           {
  DisallowGarbageCollection no_gc;
  int hash = GetIdentityHashHelper(*this);
  if (hash == PropertyArray::kNoHashSentinel) {
    return GetReadOnlyRoots().undefined_value();
  }
  return Smi::FromInt(hash);
}
References v8::internal::Smi::FromInt(), v8::internal::anonymous_namespace{js-objects.cc}::GetIdentityHashHelper(), v8::internal::GetReadOnlyRoots(), v8::internal::PropertyArray::kNoHashSentinel, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetOrCreateIdentityHash()
Tagged< Smi > v8::internal::JSReceiver::GetOrCreateIdentityHash (Isolate * isolate)
Definition at line 863 of file js-objects.cc.
                                                                {
  DisallowGarbageCollection no_gc;
  int hash = GetIdentityHashHelper(*this);
  if (hash != PropertyArray::kNoHashSentinel) {
    return Smi::FromInt(hash);
  }
  return JSReceiver::CreateIdentityHash(isolate, *this);
}
References CreateIdentityHash(), v8::internal::Smi::FromInt(), v8::internal::anonymous_namespace{js-objects.cc}::GetIdentityHashHelper(), v8::internal::PropertyArray::kNoHashSentinel, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetOwnElementAttributes()
Maybe< PropertyAttributes > v8::internal::JSReceiver::GetOwnElementAttributes (Isolate * isolate, DirectHandle< JSReceiver > object, uint32_t index) [inline], [static]
Definition at line 1003 of file js-objects-inl.h.
                                                                       {
  LookupIterator it(isolate, object, index, object, LookupIterator::OWN);
  return GetPropertyAttributes(&it);
}
References v8::internal::index.
GetOwnEntries()
MaybeDirectHandle< FixedArray > v8::internal::JSReceiver::GetOwnEntries (Isolate * isolate, DirectHandle< JSReceiver > object, PropertyFilter filter, bool try_fast_path = true) [static]
Definition at line 2343 of file js-objects.cc.
                        {
  return GetOwnValuesOrEntries(isolate, object, filter, try_fast_path, true);
}
References v8::internal::GetOwnValuesOrEntries().
Referenced by v8::internal::RUNTIME_FUNCTION().
GetOwnPropertyAttributes() [1/2]
Maybe< PropertyAttributes > v8::internal::JSReceiver::GetOwnPropertyAttributes (Isolate * isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name) [inline], [static]
Definition at line 983 of file js-objects-inl.h.
                             {
  PropertyKey key(isolate, name);
  LookupIterator it(isolate, object, key, object, LookupIterator::OWN);
  return GetPropertyAttributes(&it);
}
References v8::internal::key, and name.
Referenced by v8::internal::BUILTIN(), HasOwnProperty(), and v8::internal::Context::Lookup().
GetOwnPropertyAttributes() [2/2]
Maybe< PropertyAttributes > v8::internal::JSReceiver::GetOwnPropertyAttributes (Isolate * isolate, DirectHandle< JSReceiver > object, uint32_t index) [inline], [static]
Definition at line 991 of file js-objects-inl.h.
                                                                       {
  LookupIterator it(isolate, object, index, object, LookupIterator::OWN);
  return GetPropertyAttributes(&it);
}
References v8::internal::index.
GetOwnPropertyDescriptor() [1/2]
Maybe< bool > v8::internal::JSReceiver::GetOwnPropertyDescriptor (Isolate * isolate, DirectHandle< JSReceiver > object, DirectHandle< Object > key, PropertyDescriptor * desc) [static]
Definition at line 1833 of file js-objects.cc.
                              {
  DCHECK(IsName(*key) || IsNumber(*key)); // |key| is a PropertyKey.
  PropertyKey lookup_key(isolate, key);
  LookupIterator it(isolate, object, lookup_key, LookupIterator::OWN);
  return GetOwnPropertyDescriptor(&it, desc);
}
References v8::internal::DCHECK(), v8::internal::IsNumber(), v8::internal::key, and v8::internal::LookupIterator::OWN.
Referenced by v8::internal::BUILTIN(), v8::internal::JSProxy::CheckDeleteTrap(), v8::internal::JSProxy::CheckGetSetTrapResult(), v8::internal::JSProxy::CheckHasTrap(), v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::DebugPropertyIterator::descriptor(), v8::internal::anonymous_namespace{js-objects.cc}::GenericTestIntegrityLevel(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::Object::GetOwnPropertyDescriptor(), v8::internal::GetOwnValuesOrEntries(), HasOwnProperty(), OrdinaryDefineOwnProperty(), v8::internal::RUNTIME_FUNCTION(), SetIntegrityLevel(), SetOrCopyDataProperties(), v8::internal::Object::SetSuperProperty(), and v8::internal::ValueSerializer::WriteJSError().
GetOwnPropertyDescriptor() [2/2]
Maybe< bool > v8::internal::JSReceiver::GetOwnPropertyDescriptor (LookupIterator * it, PropertyDescriptor * desc) [static]
Definition at line 1909 of file js-objects.cc.
                                                                           {
  Isolate* isolate = it->isolate();
  // "Virtual" dispatch.
  if (it->IsFound() && IsJSProxy(*it->GetHolder<JSReceiver>())) {
    return JSProxy::GetOwnPropertyDescriptor(isolate, it->GetHolder<JSProxy>(),
                                             it->GetName(), desc);
  }
  Maybe<bool> intercepted = GetPropertyDescriptorWithInterceptor(it, desc);
  MAYBE_RETURN(intercepted, Nothing<bool>());
  if (intercepted.FromJust()) {
    return Just(true);
  }
  // Request was not intercepted, continue as normal.
  // 1. (Assert)
  // 2. If O does not have an own property with key P, return undefined.
  Maybe<PropertyAttributes> maybe = JSObject::GetPropertyAttributes(it);
  MAYBE_RETURN(maybe, Nothing<bool>());
  PropertyAttributes attrs = maybe.FromJust();
  if (attrs == ABSENT) return Just(false);
  DCHECK(!isolate->has_exception());
  // 3. Let D be a newly created Property Descriptor with no fields.
  DCHECK(desc->is_empty());
  // 4. Let X be O's own property whose key is P.
  // 5. If X is a data property, then
  bool is_accessor_pair = it->state() == LookupIterator::ACCESSOR &&
                          IsAccessorPair(*it->GetAccessors());
  if (!is_accessor_pair) {
    // 5a. Set D.[[Value]] to the value of X's [[Value]] attribute.
    DirectHandle<JSAny> value;
    if (!Cast<JSAny>(Object::GetProperty(it)).ToHandle(&value)) {
      DCHECK(isolate->has_exception());
      return Nothing<bool>();
    }
    desc->set_value(value);
    // 5b. Set D.[[Writable]] to the value of X's [[Writable]] attribute
    desc->set_writable((attrs & READ_ONLY) == 0);
  } else {
    // 6. Else X is an accessor property, so
    auto accessors = Cast<AccessorPair>(it->GetAccessors());
    DirectHandle<NativeContext> holder_realm(
        it->GetHolder<JSReceiver>()->GetCreationContext().value(), isolate);
    // 6a. Set D.[[Get]] to the value of X's [[Get]] attribute.
    desc->set_get(AccessorPair::GetComponent(isolate, holder_realm, accessors,
                                             ACCESSOR_GETTER));
    // 6b. Set D.[[Set]] to the value of X's [[Set]] attribute.
    desc->set_set(AccessorPair::GetComponent(isolate, holder_realm, accessors,
                                             ACCESSOR_SETTER));
  }
  // 7. Set D.[[Enumerable]] to the value of X's [[Enumerable]] attribute.
  desc->set_enumerable((attrs & DONT_ENUM) == 0);
  // 8. Set D.[[Configurable]] to the value of X's [[Configurable]] attribute.
  desc->set_configurable((attrs & DONT_DELETE) == 0);
  // 9. Return D.
  DCHECK(PropertyDescriptor::IsAccessorDescriptor(desc) !=
         PropertyDescriptor::IsDataDescriptor(desc));
  return Just(true);
}
References v8::internal::ABSENT, v8::internal::LookupIterator::ACCESSOR, v8::internal::ACCESSOR_GETTER, v8::internal::ACCESSOR_SETTER, v8::internal::DCHECK(), v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, v8::Maybe< T >::FromJust(), v8::internal::LookupIterator::GetAccessors(), v8::internal::AccessorPair::GetComponent(), GetCreationContext(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::internal::Object::GetProperty(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::internal::Isolate::has_exception(), v8::internal::PropertyDescriptor::is_empty(), v8::internal::PropertyDescriptor::IsAccessorDescriptor(), v8::internal::PropertyDescriptor::IsDataDescriptor(), v8::internal::LookupIterator::IsFound(), v8::internal::LookupIterator::isolate(), v8::Just(), MAYBE_RETURN, v8::internal::READ_ONLY, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_get(), v8::internal::PropertyDescriptor::set_set(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), v8::internal::LookupIterator::state(), v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::value.
GetOwnValues()
MaybeDirectHandle< FixedArray > v8::internal::JSReceiver::GetOwnValues (Isolate * isolate, DirectHandle< JSReceiver > object, PropertyFilter filter, bool try_fast_path = true) [static]
Definition at line 2337 of file js-objects.cc.
                        {
  return GetOwnValuesOrEntries(isolate, object, filter, try_fast_path, false);
}
References v8::internal::GetOwnValuesOrEntries().
Referenced by v8::internal::RUNTIME_FUNCTION().
GetProperty() [1/2]
MaybeHandle< Object > v8::internal::JSReceiver::GetProperty (Isolate * isolate, DirectHandle< JSReceiver > receiver, const char * key) [inline], [static]
Definition at line 123 of file js-objects-inl.h.
                                                              {
  DirectHandle<String> str = isolate->factory()->InternalizeUtf8String(name);
  return GetProperty(isolate, receiver, str);
}
References v8::internal::Isolate::factory(), v8::internal::Factory::InternalizeUtf8String(), and name.
Referenced by v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::internal::Object::ArraySpeciesConstructor(), v8::internal::BUILTIN(), v8::internal::JSFunction::GetDerivedMap(), v8::internal::WasmExceptionPackage::GetExceptionTag(), v8::internal::WasmExceptionPackage::GetExceptionValues(), v8::internal::Isolate::GetImportAttributesFromArgument(), v8::internal::Object::GetLengthFromArrayLike(), v8::internal::Object::GetMethod(), v8::internal::GetNumberOption(), v8::internal::GetNumberOptionAsDouble(), v8::internal::temporal::GetRoundingIncrementOption(), v8::internal::temporal::GetSingleDurationField(), v8::internal::temporal::GetSingleTimeRecordField(), v8::internal::temporal::GetTemporalFractionalSecondDigitsOption(), v8::internal::Intl::LegacyUnwrapReceiver(), v8::internal::JSPromise::Resolve(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Intl::SetNumberFormatDigitOptions(), v8::TryCatch::StackTrace(), v8::internal::temporal::ToPartialDuration(), v8::internal::JSTemporalInstant::ToString(), v8::internal::UnscopableLookup(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyDescriptorOptionsImpl().
GetProperty() [2/2]
MaybeHandle< Object > v8::internal::JSReceiver::GetProperty (Isolate * isolate, DirectHandle< JSReceiver > receiver, DirectHandle< Name > name) [inline], [static]
Definition at line 85 of file js-objects-inl.h.
                                                                     {
  LookupIterator it(isolate, receiver, name, receiver);
  if (!it.IsFound()) return it.factory()->undefined_value();
  return Object::GetProperty(&it);
}
References v8::internal::LookupIterator::factory(), v8::internal::LookupIterator::IsFound(), and name.
GetPropertyAttributes() [1/2]
Maybe< PropertyAttributes > v8::internal::JSReceiver::GetPropertyAttributes (Isolate * isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name) [inline], [static]
Definition at line 975 of file js-objects-inl.h.
                             {
  PropertyKey key(isolate, name);
  LookupIterator it(isolate, object, key, object);
  return GetPropertyAttributes(&it);
}
References v8::internal::key, and name.
Referenced by v8::internal::DebugPropertyIterator::attributes(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::anonymous_namespace{runtime-scopes.cc}::DeclareGlobal(), v8::internal::anonymous_namespace{api-natives.cc}::DefineDataProperty(), DefineProperties(), v8::Object::GetPropertyAttributes(), v8::Object::GetRealNamedPropertyAttributes(), v8::Object::GetRealNamedPropertyAttributesInPrototypeChain(), v8::internal::anonymous_namespace{execution.cc}::NewScriptContext(), and v8::internal::RUNTIME_FUNCTION().
GetPropertyAttributes() [2/2]
Maybe< PropertyAttributes > v8::internal::JSReceiver::GetPropertyAttributes (LookupIterator * it) [static]
Definition at line 712 of file js-objects.cc.
                        {
  for (;; it->Next()) {
    switch (it->state()) {
      case LookupIterator::TRANSITION:
      case LookupIterator::STRING_LOOKUP_START_OBJECT:
        UNREACHABLE();
      case LookupIterator::JSPROXY:
        return JSProxy::GetPropertyAttributes(it);
      case LookupIterator::WASM_OBJECT:
        return Just(ABSENT);
      case LookupIterator::INTERCEPTOR: {
        Maybe<PropertyAttributes> result =
            JSObject::GetPropertyAttributesWithInterceptor(it);
        if (result.IsNothing()) return result;
        if (result.FromJust() != ABSENT) return result;
        continue;
      }
      case LookupIterator::ACCESS_CHECK:
        if (it->HasAccess()) continue;
        return JSObject::GetPropertyAttributesWithFailedAccessCheck(it);
      case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
        return Just(ABSENT);
      case LookupIterator::ACCESSOR:
        if (IsJSModuleNamespace(*it->GetHolder<Object>())) {
          return JSModuleNamespace::GetPropertyAttributes(it);
        } else {
          return Just(it->property_attributes());
        }
      case LookupIterator::DATA:
        return Just(it->property_attributes());
      case LookupIterator::NOT_FOUND:
        return Just(ABSENT);
    }
    UNREACHABLE();
  }
}
References v8::internal::ABSENT, v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, v8::internal::LookupIterator::DATA, v8::internal::LookupIterator::GetHolder(), v8::internal::JSProxy::GetPropertyAttributes(), v8::internal::JSModuleNamespace::GetPropertyAttributes(), v8::internal::JSObject::GetPropertyAttributesWithFailedAccessCheck(), v8::internal::JSObject::GetPropertyAttributesWithInterceptor(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::LookupIterator::JSPROXY, v8::Just(), v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::NOT_FOUND, v8::internal::LookupIterator::property_attributes(), v8::base::internal::result, v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), and v8::internal::LookupIterator::WASM_OBJECT.
GetPrototype()
MaybeDirectHandle< JSPrototype > v8::internal::JSReceiver::GetPrototype (Isolate * isolate, DirectHandle< JSReceiver > receiver) [inline], [static]
Definition at line 110 of file js-objects-inl.h.
                                                         {
  // We don't expect access checks to be needed on JSProxy objects.
  DCHECK(!IsAccessCheckNeeded(*receiver) || IsJSObject(*receiver));
  PrototypeIterator iter(isolate, receiver, kStartAtReceiver,
                         PrototypeIterator::END_AT_NON_HIDDEN);
  do {
    if (!iter.AdvanceFollowingProxies()) return {};
  } while (!iter.IsAtEnd());
  return PrototypeIterator::GetCurrent(iter);
}
References v8::internal::PrototypeIterator::AdvanceFollowingProxies(), DCHECK, v8::internal::PrototypeIterator::IsAtEnd(), and v8::internal::kStartAtReceiver.
Referenced by v8::internal::BUILTIN(), v8::internal::anonymous_namespace{builtins-function.cc}::DoFunctionBind(), v8::internal::JSProxy::GetPrototype(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::JSProxy::SetPrototype().
HasElement()
Maybe< bool > v8::internal::JSReceiver::HasElement (Isolate * isolate, DirectHandle< JSReceiver > object, uint32_t index) [inline], [static]
Definition at line 947 of file js-objects-inl.h.
                                                   {
  LookupIterator it(isolate, object, index, object);
  return HasProperty(&it);
}
References v8::internal::index.
Referenced by v8::Object::Has(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements(), and v8::internal::anonymous_namespace{builtins-array.cc}::IterateElementsSlow().
HasInPrototypeChain()
Maybe< bool > v8::internal::JSReceiver::HasInPrototypeChain (Isolate * isolate, DirectHandle< JSReceiver > object, DirectHandle< Object > proto) [static]
Definition at line 194 of file js-objects.cc.
                                                                        {
  PrototypeIterator iter(isolate, object, kStartAtReceiver);
  while (true) {
    if (!iter.AdvanceFollowingProxies()) return Nothing<bool>();
    if (iter.IsAtEnd()) return Just(false);
    if (PrototypeIterator::GetCurrent(iter).is_identical_to(proto)) {
      return Just(true);
    }
  }
}
References v8::internal::PrototypeIterator::AdvanceFollowingProxies(), v8::internal::PrototypeIterator::GetCurrent(), v8::internal::PrototypeIterator::IsAtEnd(), v8::Just(), and v8::internal::kStartAtReceiver.
Referenced by v8::internal::Object::OrdinaryHasInstance(), and v8::internal::RUNTIME_FUNCTION().
HasOwnProperty() [1/2]
Maybe< bool > v8::internal::JSReceiver::HasOwnProperty (Isolate * isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name) [static]
Definition at line 139 of file js-objects.cc.
                                                                {
  if (IsJSModuleNamespace(*object)) {
    PropertyDescriptor desc;
    return JSReceiver::GetOwnPropertyDescriptor(isolate, object, name, &desc);
  }
  if (IsJSObject(*object)) { // Shortcut.
    PropertyKey key(isolate, name);
    LookupIterator it(isolate, object, key, LookupIterator::OWN);
    return HasProperty(&it);
  }
  Maybe<PropertyAttributes> attributes =
      JSReceiver::GetOwnPropertyAttributes(isolate, object, name);
  MAYBE_RETURN(attributes, Nothing<bool>());
  return Just(attributes.FromJust() != ABSENT);
}
References v8::internal::ABSENT, v8::Maybe< T >::FromJust(), GetOwnPropertyAttributes(), GetOwnPropertyDescriptor(), HasProperty(), v8::Just(), v8::internal::key, MAYBE_RETURN, v8::internal::name, and v8::internal::LookupIterator::OWN.
Referenced by v8::internal::ErrorUtils::HasErrorStackSymbolOwnProperty(), v8::Object::HasOwnProperty(), and v8::internal::ScopeIterator::ScopeObject().
HasOwnProperty() [2/2]
Maybe< bool > v8::internal::JSReceiver::HasOwnProperty (Isolate * isolate, DirectHandle< JSReceiver > object, uint32_t index) [inline], [static]
Definition at line 961 of file js-objects-inl.h.
                                                       {
  if (IsJSObject(*object)) { // Shortcut.
    LookupIterator it(isolate, object, index, object, LookupIterator::OWN);
    return HasProperty(&it);
  }
  Maybe<PropertyAttributes> attributes =
      JSReceiver::GetOwnPropertyAttributes(isolate, object, index);
  MAYBE_RETURN(attributes, Nothing<bool>());
  return Just(attributes.FromJust() != ABSENT);
}
References v8::internal::ABSENT, v8::Maybe< T >::FromJust(), v8::internal::index, v8::Just(), and MAYBE_RETURN.
HasProperty() [1/2]
Maybe< bool > v8::internal::JSReceiver::HasProperty (Isolate * isolate, DirectHandle< JSReceiver > object, DirectHandle< Name > name) [inline], [static]
Definition at line 941 of file js-objects-inl.h.
                                                             {
  return HasPropertyOrElement(isolate, object, PropertyKey(isolate, name));
}
References name.
HasProperty() [2/2]
Maybe< bool > v8::internal::JSReceiver::HasProperty (LookupIterator * it) [static]
Definition at line 100 of file js-objects.cc.
                                                      {
  for (;; it->Next()) {
    switch (it->state()) {
      case LookupIterator::TRANSITION:
      case LookupIterator::STRING_LOOKUP_START_OBJECT:
        UNREACHABLE();
      case LookupIterator::JSPROXY:
        return JSProxy::HasProperty(it->isolate(), it->GetHolder<JSProxy>(),
                                    it->GetName());
      case LookupIterator::WASM_OBJECT:
        continue; // Continue to the prototype, if present.
      case LookupIterator::INTERCEPTOR: {
        Maybe<PropertyAttributes> result =
            JSObject::GetPropertyAttributesWithInterceptor(it);
        if (result.IsNothing()) return Nothing<bool>();
        if (result.FromJust() != ABSENT) return Just(true);
        continue;
      }
      case LookupIterator::ACCESS_CHECK: {
        if (it->HasAccess()) continue;
        Maybe<PropertyAttributes> result =
            JSObject::GetPropertyAttributesWithFailedAccessCheck(it);
        if (result.IsNothing()) return Nothing<bool>();
        return Just(result.FromJust() != ABSENT);
      }
      case LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND:
        // TypedArray out-of-bounds access.
        return Just(false);
      case LookupIterator::ACCESSOR:
      case LookupIterator::DATA:
        return Just(true);
      case LookupIterator::NOT_FOUND:
        return Just(false);
    }
    UNREACHABLE();
  }
}
References v8::internal::ABSENT, v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::LookupIterator::ACCESSOR, v8::internal::LookupIterator::DATA, v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetName(), v8::internal::JSObject::GetPropertyAttributesWithFailedAccessCheck(), v8::internal::JSObject::GetPropertyAttributesWithInterceptor(), v8::internal::LookupIterator::HasAccess(), v8::internal::JSProxy::HasProperty(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::LookupIterator::isolate(), v8::internal::LookupIterator::JSPROXY, v8::Just(), v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::NOT_FOUND, v8::base::internal::result, v8::internal::LookupIterator::state(), v8::internal::LookupIterator::STRING_LOOKUP_START_OBJECT, v8::internal::LookupIterator::TRANSITION, v8::internal::LookupIterator::TYPED_ARRAY_INDEX_NOT_FOUND, v8::internal::UNREACHABLE(), and v8::internal::LookupIterator::WASM_OBJECT.
Referenced by v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::internal::Intl::CanonicalizeLocaleList(), v8::internal::anonymous_namespace{property-descriptor.cc}::GetPropertyIfPresent(), v8::Object::Has(), HasOwnProperty(), v8::internal::JSProxy::HasProperty(), v8::internal::Runtime::HasProperty(), v8::internal::LoadIC::Load(), v8::internal::Context::Lookup(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ScopeIterator::SetContextExtensionValue(), v8::TryCatch::StackTrace(), and v8::internal::UnscopableLookup().
HasPropertyOrElement()
Maybe< bool > v8::internal::JSReceiver::HasPropertyOrElement (Isolate * isolate, DirectHandle< JSReceiver > object, PropertyKey key) [inline], [static]
Definition at line 954 of file js-objects-inl.h.
                                                              {
  LookupIterator it(isolate, object, key, object);
  return HasProperty(&it);
}
References v8::internal::key.
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayShift().
HasProxyInPrototype()
bool v8::internal::JSReceiver::HasProxyInPrototype (Isolate * isolate)
Definition at line 2367 of file js-objects.cc.
                                                     {
  for (PrototypeIterator iter(isolate, *this, kStartAtReceiver,
                              PrototypeIterator::END_AT_NULL);
       !iter.IsAtEnd(); iter.AdvanceIgnoringProxies()) {
    if (IsJSProxy(iter.GetCurrent())) return true;
  }
  return false;
}
References v8::internal::PrototypeIterator::END_AT_NULL, v8::internal::PrototypeIterator::IsAtEnd(), and v8::internal::kStartAtReceiver.
initialize_properties()
void v8::internal::JSReceiver::initialize_properties (Isolate * isolate) [inline]
Definition at line 846 of file js-objects-inl.h.
                                                       {
  ReadOnlyRoots roots(isolate);
  DCHECK(!HeapLayout::InYoungGeneration(roots.empty_fixed_array()));
  DCHECK(!HeapLayout::InYoungGeneration(roots.empty_property_dictionary()));
  DCHECK(!HeapLayout::InYoungGeneration(
      roots.empty_ordered_property_dictionary()));
  if (map(isolate)->is_dictionary_map()) {
    if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      WRITE_FIELD(*this, kPropertiesOrHashOffset,
                  roots.empty_swiss_property_dictionary());
    } else {
      WRITE_FIELD(*this, kPropertiesOrHashOffset,
                  roots.empty_property_dictionary());
    }
  } else {
    WRITE_FIELD(*this, kPropertiesOrHashOffset, roots.empty_fixed_array());
  }
}
References DCHECK, V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, and WRITE_FIELD.
IsCodeLike()
bool v8::internal::JSReceiver::IsCodeLike (Isolate * isolate) const
Definition at line 2376 of file js-objects.cc.
                                                  {
  DisallowGarbageCollection no_gc;
  Tagged<Object> maybe_constructor = map()->GetConstructor();
  if (!IsJSFunction(maybe_constructor)) return false;
  if (!Cast<JSFunction>(maybe_constructor)->shared()->IsApiFunction()) {
    return false;
  }
  Tagged<Object> instance_template = Cast<JSFunction>(maybe_constructor)
                                         ->shared()
                                         ->api_func_data()
                                         ->GetInstanceTemplate();
  if (IsUndefined(instance_template, isolate)) return false;
  return Cast<ObjectTemplateInfo>(instance_template)->code_like();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
IsCompatiblePropertyDescriptor()
Maybe< bool > v8::internal::JSReceiver::IsCompatiblePropertyDescriptor (Isolate * isolate, bool extensible, PropertyDescriptor * desc, PropertyDescriptor * current, DirectHandle< Name > property_name, Maybe< ShouldThrow > should_throw) [static]
Definition at line 1465 of file js-objects.cc.
                                     {
  // 1. Return ValidateAndApplyPropertyDescriptor(undefined, undefined,
  // Extensible, Desc, Current).
  return ValidateAndApplyPropertyDescriptor(
      isolate, nullptr, extensible, desc, current, should_throw, property_name);
}
References ValidateAndApplyPropertyDescriptor().
IsExtensible()
Maybe< bool > v8::internal::JSReceiver::IsExtensible (Isolate * isolate, DirectHandle< JSReceiver > object) [static]
Definition at line 2102 of file js-objects.cc.
                                                                      {
  if (IsJSProxy(*object)) {
    return JSProxy::IsExtensible(Cast<JSProxy>(object));
  }
  if (IsWasmObject(*object)) {
    return Just(false);
  }
  return Just(JSObject::IsExtensible(isolate, Cast<JSObject>(object)));
}
References v8::internal::JSProxy::IsExtensible(), v8::internal::JSObject::IsExtensible(), v8::internal::IsWasmObject(), and v8::Just().
Referenced by v8::internal::JSProxy::CheckDeleteTrap(), v8::internal::JSProxy::CheckHasTrap(), v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::anonymous_namespace{js-objects.cc}::GenericTestIntegrityLevel(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::internal::JSProxy::GetPrototype(), v8::internal::JSProxy::IsExtensible(), v8::internal::JSProxy::PreventExtensions(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::JSProxy::SetPrototype().
OrdinaryDefineOwnProperty() [1/3]
Maybe< bool > v8::internal::JSReceiver::OrdinaryDefineOwnProperty (Isolate * isolate, DirectHandle< JSObject > object, const PropertyKey & key, PropertyDescriptor * desc, Maybe< ShouldThrow > should_throw) [static]
Definition at line 1396 of file js-objects.cc.
                                                               {
  LookupIterator it(isolate, object, key, LookupIterator::OWN);
  // Deal with access checks first.
  while (it.state() == LookupIterator::ACCESS_CHECK) {
    if (!it.HasAccess()) {
      RETURN_ON_EXCEPTION_VALUE(
          isolate, isolate->ReportFailedAccessCheck(it.GetHolder<JSObject>()),
          Nothing<bool>());
      UNREACHABLE();
    }
    it.Next();
  }
  // 1. Let current be O.[[GetOwnProperty]](P).
  // 2. ReturnIfAbrupt(current).
  PropertyDescriptor current;
  MAYBE_RETURN(GetOwnPropertyDescriptor(&it, &current), Nothing<bool>());
  // TODO(jkummerow/verwaest): It would be nice if we didn't have to reset
  // the iterator every time. Currently, the reasons why we need it are because
  // GetOwnPropertyDescriptor can have side effects, namely:
  // - Interceptors
  // - Accessors (which might change the holder's map)
  it.Restart();
  // Skip over the access check after restarting -- we've already checked it.
  while (it.state() == LookupIterator::ACCESS_CHECK) {
    DCHECK(it.HasAccess());
    it.Next();
  }
  // Handle interceptor.
  if (it.state() == LookupIterator::INTERCEPTOR) {
    if (it.HolderIsReceiverOrHiddenPrototype()) {
      InterceptorResult result;
      if (!DefinePropertyWithInterceptorInternal(&it, it.GetInterceptor(),
                                                 should_throw, desc)
               .To(&result)) {
        // An exception was thrown in the interceptor. Propagate.
        return Nothing<bool>();
      }
      switch (result) {
        case InterceptorResult::kFalse:
          return Just(false);
        case InterceptorResult::kTrue:
          return Just(true);
        case InterceptorResult::kNotIntercepted:
          // Proceed lookup.
          break;
      }
      // We need to restart the lookup in case the interceptor ran with side
      // effects.
      it.Restart();
    }
  }
  // 3. Let extensible be the value of the [[Extensible]] internal slot of O.
  bool extensible = JSObject::IsExtensible(isolate, object);
  return ValidateAndApplyPropertyDescriptor(isolate, &it, extensible, desc,
                                            &current, should_throw, {});
}
References v8::internal::LookupIterator::ACCESS_CHECK, v8::internal::DCHECK(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::LookupIterator::GetHolder(), v8::internal::LookupIterator::GetInterceptor(), GetOwnPropertyDescriptor(), v8::internal::LookupIterator::HasAccess(), v8::internal::LookupIterator::HolderIsReceiverOrHiddenPrototype(), v8::internal::LookupIterator::INTERCEPTOR, v8::internal::JSObject::IsExtensible(), v8::Just(), v8::internal::key, v8::internal::kFalse, v8::internal::kNotIntercepted, v8::internal::kTrue, MAYBE_RETURN, v8::internal::LookupIterator::Next(), v8::internal::LookupIterator::OWN, v8::internal::Isolate::ReportFailedAccessCheck(), v8::internal::LookupIterator::Restart(), v8::base::internal::result, RETURN_ON_EXCEPTION_VALUE, v8::internal::LookupIterator::state(), v8::internal::UNREACHABLE(), and ValidateAndApplyPropertyDescriptor().
OrdinaryDefineOwnProperty() [2/3]
Maybe< bool > v8::internal::JSReceiver::OrdinaryDefineOwnProperty (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Object > key, PropertyDescriptor * desc, Maybe< ShouldThrow > should_throw) [static]
Definition at line 1182 of file js-objects.cc.
                                                               {
  DCHECK(IsName(*key) || IsNumber(*key)); // |key| is a PropertyKey.
  PropertyKey lookup_key(isolate, key);
  return OrdinaryDefineOwnProperty(isolate, object, lookup_key, desc,
                                   should_throw);
}
References v8::internal::DCHECK(), v8::internal::IsNumber(), and v8::internal::key.
Referenced by DefineOwnProperty().
OrdinaryDefineOwnProperty() [3/3]
static V8_WARN_UNUSED_RESULT Maybe<bool> v8::internal::JSReceiver::OrdinaryDefineOwnProperty (LookupIterator * it, PropertyDescriptor * desc, Maybe< ShouldThrow > should_throw) [static]
OwnPropertyKeys()
V8_WARN_UNUSED_RESULT MaybeDirectHandle< FixedArray > v8::internal::JSReceiver::OwnPropertyKeys (Isolate * isolate, DirectHandle< JSReceiver > object) [inline], [static]
Definition at line 131 of file js-objects-inl.h.
                                                       {
  return KeyAccumulator::GetKeys(isolate, object, KeyCollectionMode::kOwnOnly,
                                 ALL_PROPERTIES,
                                 GetKeysConversion::kConvertToString);
}
References v8::internal::ALL_PROPERTIES.
Referenced by v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::anonymous_namespace{js-objects.cc}::GenericTestIntegrityLevel(), and SetIntegrityLevel().
PreventExtensions()
Maybe< bool > v8::internal::JSReceiver::PreventExtensions (Isolate * isolate, DirectHandle< JSReceiver > object, ShouldThrow should_throw) [static]
Definition at line 2087 of file js-objects.cc.
                                                                    {
  if (IsJSProxy(*object)) {
    return JSProxy::PreventExtensions(Cast<JSProxy>(object), should_throw);
  }
  if (IsWasmObject(*object)) {
    RETURN_FAILURE(isolate, kThrowOnError,
                   NewTypeError(MessageTemplate::kWasmObjectsAreOpaque));
  }
  DCHECK(IsJSObject(*object));
  return JSObject::PreventExtensions(isolate, Cast<JSObject>(object),
                                     should_throw);
}
References v8::internal::DCHECK(), v8::internal::IsWasmObject(), v8::internal::kThrowOnError, v8::internal::JSProxy::PreventExtensions(), v8::internal::JSObject::PreventExtensions(), and RETURN_FAILURE.
Referenced by v8::internal::JSProxy::PreventExtensions(), v8::internal::RUNTIME_FUNCTION(), and SetIntegrityLevel().
SetIdentityHash()
void v8::internal::JSReceiver::SetIdentityHash (int masked_hash)
Definition at line 812 of file js-objects.cc.
                                         {
  DisallowGarbageCollection no_gc;
  DCHECK_NE(PropertyArray::kNoHashSentinel, hash);
  DCHECK(PropertyArray::HashField::is_valid(hash));
  Tagged<HeapObject> existing_properties =
      Cast<HeapObject>(raw_properties_or_hash());
  Tagged<Object> new_properties =
      SetHashAndUpdateProperties(existing_properties, hash);
  set_raw_properties_or_hash(new_properties, kRelaxedStore);
}
References v8::internal::DCHECK(), DCHECK_NE, v8::base::BitField< T, shift, size, U >::is_valid(), v8::internal::PropertyArray::kNoHashSentinel, v8::kRelaxedStore, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::raw_properties_or_hash, and v8::internal::anonymous_namespace{js-objects.cc}::SetHashAndUpdateProperties().
SetIntegrityLevel()
Maybe< bool > v8::internal::JSReceiver::SetIntegrityLevel (Isolate * isolate, DirectHandle< JSReceiver > object, IntegrityLevel lvl, ShouldThrow should_throw) [static]
Definition at line 1972 of file js-objects.cc.
                                                                    {
  DCHECK(level == SEALED || level == FROZEN);
  if (IsJSObject(*receiver)) {
    DirectHandle<JSObject> object = Cast<JSObject>(receiver);
    if (!object->HasSloppyArgumentsElements() &&
        !IsJSModuleNamespace(*object)) { // Fast path.
      // Prevent memory leaks by not adding unnecessary transitions.
      Maybe<bool> test = JSObject::TestIntegrityLevel(isolate, object, level);
      MAYBE_RETURN(test, Nothing<bool>());
      if (test.FromJust()) return test;
      if (level == SEALED) {
        return JSObject::PreventExtensionsWithTransition<SEALED>(
            isolate, object, should_throw);
      } else {
        return JSObject::PreventExtensionsWithTransition<FROZEN>(
            isolate, object, should_throw);
      }
    }
  }
  MAYBE_RETURN(JSReceiver::PreventExtensions(isolate, receiver, should_throw),
               Nothing<bool>());
  DirectHandle<FixedArray> keys;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, keys, JSReceiver::OwnPropertyKeys(isolate, receiver),
      Nothing<bool>());
  PropertyDescriptor no_conf;
  no_conf.set_configurable(false);
  PropertyDescriptor no_conf_no_write;
  no_conf_no_write.set_configurable(false);
  no_conf_no_write.set_writable(false);
  if (level == SEALED) {
    for (int i = 0; i < keys->length(); ++i) {
      DirectHandle<Object> key(keys->get(i), isolate);
      MAYBE_RETURN(DefineOwnProperty(isolate, receiver, key, &no_conf,
                                     Just(kThrowOnError)),
                   Nothing<bool>());
    }
    return Just(true);
  }
  for (int i = 0; i < keys->length(); ++i) {
    DirectHandle<Object> key(keys->get(i), isolate);
    PropertyDescriptor current_desc;
    Maybe<bool> owned = JSReceiver::GetOwnPropertyDescriptor(
        isolate, receiver, key, &current_desc);
    MAYBE_RETURN(owned, Nothing<bool>());
    if (owned.FromJust()) {
      PropertyDescriptor desc =
          PropertyDescriptor::IsAccessorDescriptor(&current_desc)
              ? no_conf
              : no_conf_no_write;
      MAYBE_RETURN(
          DefineOwnProperty(isolate, receiver, key, &desc, Just(kThrowOnError)),
          Nothing<bool>());
    }
  }
  return Just(true);
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::DCHECK(), DefineOwnProperty(), v8::Maybe< T >::FromJust(), v8::internal::FROZEN, GetOwnPropertyDescriptor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::PropertyDescriptor::IsAccessorDescriptor(), v8::Just(), v8::internal::key, v8::internal::kThrowOnError, MAYBE_RETURN, OwnPropertyKeys(), PreventExtensions(), v8::internal::SEALED, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_writable(), and v8::internal::JSObject::TestIntegrityLevel().
Referenced by v8::internal::BUILTIN(), v8::internal::CreateDummyWasmLookAlikeForFuzzing(), v8::anonymous_namespace{api.cc}::ObjectVisitorDeepFreezer::DeepFreeze(), v8::internal::wasm::InstanceBuilder::FinalizeExportsObject(), and v8::Object::SetIntegrityLevel().
SetOrCopyDataProperties()
Maybe< bool > v8::internal::JSReceiver::SetOrCopyDataProperties (Isolate * isolate, DirectHandle< JSReceiver > target, DirectHandle< Object > source, PropertiesEnumerationMode mode, base::Vector< DirectHandle< Object >> excluded_properties = {}, bool use_set = true) [static]
Definition at line 415 of file js-objects.cc.
                                                                        {
  Maybe<bool> fast_assign =
      FastAssign(isolate, target, source, mode, excluded_properties, use_set);
  if (fast_assign.IsNothing()) return Nothing<bool>();
  if (fast_assign.FromJust()) return Just(true);
  DirectHandle<JSReceiver> from =
      Object::ToObject(isolate, source).ToHandleChecked();
  // 3b. Let keys be ? from.[[OwnPropertyKeys]]().
  DirectHandle<FixedArray> keys;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, keys,
      KeyAccumulator::GetKeys(isolate, from, KeyCollectionMode::kOwnOnly,
                              ALL_PROPERTIES, GetKeysConversion::kKeepNumbers),
      Nothing<bool>());
  if (!from->HasFastProperties() && target->HasFastProperties() &&
      IsJSObject(*target) && !IsJSGlobalProxy(*target)) {
    // Convert to slow properties if we're guaranteed to overflow the number of
    // descriptors.
    int source_length;
    if (IsJSGlobalObject(*from)) {
      source_length = Cast<JSGlobalObject>(*from)
                          ->global_dictionary(kAcquireLoad)
                          ->NumberOfEnumerableProperties();
    } else if constexpr (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      source_length =
          from->property_dictionary_swiss()->NumberOfEnumerableProperties();
    } else {
      source_length =
          from->property_dictionary()->NumberOfEnumerableProperties();
    }
    if (source_length > kMaxNumberOfDescriptors) {
      JSObject::NormalizeProperties(isolate, Cast<JSObject>(target),
                                    CLEAR_INOBJECT_PROPERTIES, source_length,
                                    "Copying data properties");
    }
  }
  // 4. Repeat for each element nextKey of keys in List order,
  for (int i = 0; i < keys->length(); ++i) {
    DirectHandle<Object> next_key(keys->get(i), isolate);
    if (!excluded_properties.empty() &&
        HasExcludedProperty(excluded_properties, next_key)) {
      continue;
    }
    // 4a i. Let desc be ? from.[[GetOwnProperty]](nextKey).
    PropertyDescriptor desc;
    Maybe<bool> found =
        JSReceiver::GetOwnPropertyDescriptor(isolate, from, next_key, &desc);
    if (found.IsNothing()) return Nothing<bool>();
    // 4a ii. If desc is not undefined and desc.[[Enumerable]] is true, then
    if (found.FromJust() && desc.enumerable()) {
      // 4a ii 1. Let propValue be ? Get(from, nextKey).
      DirectHandle<Object> prop_value;
      ASSIGN_RETURN_ON_EXCEPTION_VALUE(
          isolate, prop_value,
          Runtime::GetObjectProperty(isolate, from, next_key), Nothing<bool>());
      if (use_set) {
        // 4c ii 2. Let status be ? Set(to, nextKey, propValue, true).
        DirectHandle<Object> status;
        ASSIGN_RETURN_ON_EXCEPTION_VALUE(
            isolate, status,
            Runtime::SetObjectProperty(isolate, target, next_key, prop_value,
                                       StoreOrigin::kMaybeKeyed,
                                       Just(ShouldThrow::kThrowOnError)),
            Nothing<bool>());
      } else {
        // 4a ii 2. Perform ! CreateDataProperty(target, nextKey, propValue).
        PropertyKey key(isolate, next_key);
        CHECK(JSReceiver::CreateDataProperty(isolate, target, key, prop_value,
                                             Just(kThrowOnError))
                  .FromJust());
      }
    }
  }
  return Just(true);
}
References v8::internal::ALL_PROPERTIES, ASSIGN_RETURN_ON_EXCEPTION_VALUE, CHECK, v8::internal::CLEAR_INOBJECT_PROPERTIES, CreateDataProperty(), v8::internal::PropertyDescriptor::enumerable(), v8::internal::anonymous_namespace{js-objects.cc}::FastAssign(), v8::Maybe< T >::FromJust(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::Runtime::GetObjectProperty(), GetOwnPropertyDescriptor(), v8::internal::anonymous_namespace{js-objects.cc}::HasExcludedProperty(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::Maybe< T >::IsNothing(), v8::Just(), v8::kAcquireLoad, v8::internal::key, v8::internal::kKeepNumbers, v8::internal::kMaxNumberOfDescriptors, v8::internal::kMaybeKeyed, v8::internal::kOwnOnly, v8::internal::kThrowOnError, mode(), v8::internal::JSObject::NormalizeProperties(), v8::internal::Runtime::SetObjectProperty(), v8::internal::status, v8::Value::ToObject(), and V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL.
Referenced by v8::internal::CloneObjectSlowPath(), and v8::internal::RUNTIME_FUNCTION().
SetProperties()
void v8::internal::JSReceiver::SetProperties (Tagged< HeapObject > properties)
Definition at line 824 of file js-objects.cc.
                                                            {
  DCHECK_IMPLIES(IsPropertyArray(properties) &&
                     Cast<PropertyArray>(properties)->length() == 0,
                 properties == GetReadOnlyRoots().empty_property_array());
  DisallowGarbageCollection no_gc;
  int hash = GetIdentityHashHelper(*this);
  Tagged<Object> new_properties = properties;
  // TODO(cbruni): Make GetIdentityHashHelper return a bool so that we
  // don't have to manually compare against kNoHashSentinel.
  if (hash != PropertyArray::kNoHashSentinel) {
    new_properties = SetHashAndUpdateProperties(properties, hash);
  }
  set_raw_properties_or_hash(new_properties, kRelaxedStore);
}
References DCHECK_IMPLIES, v8::internal::anonymous_namespace{js-objects.cc}::GetIdentityHashHelper(), v8::internal::GetReadOnlyRoots(), v8::internal::PropertyArray::kNoHashSentinel, v8::kRelaxedStore, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::anonymous_namespace{js-objects.cc}::SetHashAndUpdateProperties().
SetPrototype()
Maybe< bool > v8::internal::JSReceiver::SetPrototype (Isolate * isolate, DirectHandle< JSReceiver > object, DirectHandle< Object > value, bool from_javascript, ShouldThrow should_throw) [static]
Definition at line 2349 of file js-objects.cc.
                                                               {
  if (IsWasmObject(*object)) {
    RETURN_FAILURE(isolate, should_throw,
                   NewTypeError(MessageTemplate::kWasmObjectsAreOpaque));
  }
  if (IsJSProxy(*object)) {
    return JSProxy::SetPrototype(isolate, Cast<JSProxy>(object), value,
                                 from_javascript, should_throw);
  }
  return JSObject::SetPrototype(isolate, Cast<JSObject>(object), value,
                                from_javascript, should_throw);
}
References v8::internal::IsWasmObject(), RETURN_FAILURE, v8::internal::JSObject::SetPrototype(), v8::internal::JSProxy::SetPrototype(), and v8::internal::value.
Referenced by v8::internal::BUILTIN(), v8::internal::InstallError(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::JSProxy::SetPrototype().
TestIntegrityLevel()
Maybe< bool > v8::internal::JSReceiver::TestIntegrityLevel (Isolate * isolate, DirectHandle< JSReceiver > object, IntegrityLevel lvl) [static]
Definition at line 2077 of file js-objects.cc.
                                                                 {
  if (!IsCustomElementsReceiverMap(receiver->map())) {
    return JSObject::TestIntegrityLevel(isolate, Cast<JSObject>(receiver),
                                        level);
  }
  return GenericTestIntegrityLevel(isolate, receiver, level);
}
References v8::internal::anonymous_namespace{js-objects.cc}::GenericTestIntegrityLevel(), v8::internal::IsCustomElementsReceiverMap(), and v8::internal::JSObject::TestIntegrityLevel().
Referenced by v8::internal::BUILTIN().
ValidateAndApplyPropertyDescriptor()
Maybe< bool > v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor (Isolate * isolate, LookupIterator * it, bool extensible, PropertyDescriptor * desc, PropertyDescriptor * current, Maybe< ShouldThrow > should_throw, DirectHandle< Name > property_name) [static]
Definition at line 1477 of file js-objects.cc.
                                                                       {
  // We either need a LookupIterator, or a property name.
  DCHECK((it == nullptr) != property_name.is_null());
  bool desc_is_data_descriptor = PropertyDescriptor::IsDataDescriptor(desc);
  bool desc_is_accessor_descriptor =
      PropertyDescriptor::IsAccessorDescriptor(desc);
  bool desc_is_generic_descriptor =
      PropertyDescriptor::IsGenericDescriptor(desc);
  // 1. (Assert)
  // 2. If current is undefined, then
  if (current->is_empty()) {
    // 2a. If extensible is false, return false.
    if (!extensible) {
      RETURN_FAILURE(
          isolate, GetShouldThrow(isolate, should_throw),
          NewTypeError(MessageTemplate::kDefineDisallowed,
                       it != nullptr ? it->GetName() : property_name));
    }
    // 2c. If IsGenericDescriptor(Desc) or IsDataDescriptor(Desc) is true, then:
    // (This is equivalent to !IsAccessorDescriptor(desc).)
    DCHECK_EQ(desc_is_generic_descriptor || desc_is_data_descriptor,
              !desc_is_accessor_descriptor);
    if (!desc_is_accessor_descriptor) {
      // 2c i. If O is not undefined, create an own data property named P of
      // object O whose [[Value]], [[Writable]], [[Enumerable]] and
      // [[Configurable]] attribute values are described by Desc. If the value
      // of an attribute field of Desc is absent, the attribute of the newly
      // created property is set to its default value.
      if (it != nullptr) {
        if (!desc->has_writable()) desc->set_writable(false);
        if (!desc->has_enumerable()) desc->set_enumerable(false);
        if (!desc->has_configurable()) desc->set_configurable(false);
        DirectHandle<Object> value(
            desc->has_value()
                ? desc->value()
                : Cast<Object>(isolate->factory()->undefined_value()));
        MaybeDirectHandle<Object> result =
            JSObject::DefineOwnPropertyIgnoreAttributes(it, value,
                                                        desc->ToAttributes());
        if (result.is_null()) return Nothing<bool>();
      }
    } else {
      // 2d. Else Desc must be an accessor Property Descriptor,
      DCHECK(desc_is_accessor_descriptor);
      // 2d i. If O is not undefined, create an own accessor property named P
      // of object O whose [[Get]], [[Set]], [[Enumerable]] and
      // [[Configurable]] attribute values are described by Desc. If the value
      // of an attribute field of Desc is absent, the attribute of the newly
      // created property is set to its default value.
      if (it != nullptr) {
        if (!desc->has_enumerable()) desc->set_enumerable(false);
        if (!desc->has_configurable()) desc->set_configurable(false);
        DirectHandle<Object> getter(
            desc->has_get() ? desc->get()
                            : Cast<Object>(isolate->factory()->null_value()));
        DirectHandle<Object> setter(
            desc->has_set() ? desc->set()
                            : Cast<Object>(isolate->factory()->null_value()));
        MaybeDirectHandle<Object> result =
            JSObject::DefineOwnAccessorIgnoreAttributes(it, getter, setter,
                                                        desc->ToAttributes());
        if (result.is_null()) return Nothing<bool>();
      }
    }
    // 2e. Return true.
    return Just(true);
  }
  // 3. If every field in Desc is absent, return true. (This also has a shortcut
  // not in the spec: if every field value matches the current value, return.)
  if ((!desc->has_enumerable() ||
       desc->enumerable() == current->enumerable()) &&
      (!desc->has_configurable() ||
       desc->configurable() == current->configurable()) &&
      !desc->has_value() &&
      (!desc->has_writable() ||
       (current->has_writable() && current->writable() == desc->writable())) &&
      (!desc->has_get() ||
       (current->has_get() &&
        Object::SameValue(*current->get(), *desc->get()))) &&
      (!desc->has_set() ||
       (current->has_set() &&
        Object::SameValue(*current->set(), *desc->set())))) {
    return Just(true);
  }
  // 4. If current.[[Configurable]] is false, then
  if (!current->configurable()) {
    // 4a. If Desc.[[Configurable]] is present and its value is true, return
    // false.
    if (desc->has_configurable() && desc->configurable()) {
      RETURN_FAILURE(
          isolate, GetShouldThrow(isolate, should_throw),
          NewTypeError(MessageTemplate::kRedefineDisallowed,
                       it != nullptr ? it->GetName() : property_name));
    }
    // 4b. If Desc.[[Enumerable]] is present and
    // ! SameValue(Desc.[[Enumerable]], current.[[Enumerable]]) is false, return
    // false.
    if (desc->has_enumerable() && desc->enumerable() != current->enumerable()) {
      RETURN_FAILURE(
          isolate, GetShouldThrow(isolate, should_throw),
          NewTypeError(MessageTemplate::kRedefineDisallowed,
                       it != nullptr ? it->GetName() : property_name));
    }
  }
  bool current_is_data_descriptor =
      PropertyDescriptor::IsDataDescriptor(current);
  // 5. If ! IsGenericDescriptor(Desc) is true, no further validation is
  // required.
  if (desc_is_generic_descriptor) {
    // Nothing to see here.
    // 6. Else if ! SameValue(!IsDataDescriptor(current),
    // !IsDataDescriptor(Desc)) is false, the
  } else if (current_is_data_descriptor != desc_is_data_descriptor) {
    // 6a. If current.[[Configurable]] is false, return false.
    if (!current->configurable()) {
      RETURN_FAILURE(
          isolate, GetShouldThrow(isolate, should_throw),
          NewTypeError(MessageTemplate::kRedefineDisallowed,
                       it != nullptr ? it->GetName() : property_name));
    }
    // 6b. If IsDataDescriptor(current) is true, then:
    if (current_is_data_descriptor) {
      // 6b i. If O is not undefined, convert the property named P of object O
      // from a data property to an accessor property. Preserve the existing
      // values of the converted property's [[Configurable]] and [[Enumerable]]
      // attributes and set the rest of the property's attributes to their
      // default values.
      // --> Folded into step 9
    } else {
      // 6c i. If O is not undefined, convert the property named P of object O
      // from an accessor property to a data property. Preserve the existing
      // values of the converted propertys [[Configurable]] and [[Enumerable]]
      // attributes and set the rest of the propertys attributes to their
      // default values.
      // --> Folded into step 9
    }
    // 7. Else if IsDataDescriptor(current) and IsDataDescriptor(Desc) are both
    // true, then:
  } else if (current_is_data_descriptor && desc_is_data_descriptor) {
    // 7a. If current.[[Configurable]] is false and current.[[Writable]] is
    // false, then
    if (!current->configurable() && !current->writable()) {
      // 7a i. If Desc.[[Writable]] is present and Desc.[[Writable]] is true,
      // return false.
      if (desc->has_writable() && desc->writable()) {
        RETURN_FAILURE(
            isolate, GetShouldThrow(isolate, should_throw),
            NewTypeError(MessageTemplate::kRedefineDisallowed,
                         it != nullptr ? it->GetName() : property_name));
      }
      // 7a ii. If Desc.[[Value]] is present and SameValue(Desc.[[Value]],
      // current.[[Value]]) is false, return false.
      if (desc->has_value()) {
        // We'll succeed applying the property, but the value is already the
        // same and the property is read-only, so skip actually writing the
        // property. Otherwise we may try to e.g., write to frozen elements.
        if (Object::SameValue(*desc->value(), *current->value()))
          return Just(true);
        RETURN_FAILURE(
            isolate, GetShouldThrow(isolate, should_throw),
            NewTypeError(MessageTemplate::kRedefineDisallowed,
                         it != nullptr ? it->GetName() : property_name));
      }
    }
  } else {
    // 8. Else,
    // 8a. Assert: ! IsAccessorDescriptor(current) and
    // ! IsAccessorDescriptor(Desc) are both true.
    DCHECK(PropertyDescriptor::IsAccessorDescriptor(current) &&
           desc_is_accessor_descriptor);
    // 8b. If current.[[Configurable]] is false, then:
    if (!current->configurable()) {
      // 8a i. If Desc.[[Set]] is present and SameValue(Desc.[[Set]],
      // current.[[Set]]) is false, return false.
      if (desc->has_set() &&
          !Object::SameValue(*desc->set(), *current->set())) {
        RETURN_FAILURE(
            isolate, GetShouldThrow(isolate, should_throw),
            NewTypeError(MessageTemplate::kRedefineDisallowed,
                         it != nullptr ? it->GetName() : property_name));
      }
      // 8a ii. If Desc.[[Get]] is present and SameValue(Desc.[[Get]],
      // current.[[Get]]) is false, return false.
      if (desc->has_get() &&
          !Object::SameValue(*desc->get(), *current->get())) {
        RETURN_FAILURE(
            isolate, GetShouldThrow(isolate, should_throw),
            NewTypeError(MessageTemplate::kRedefineDisallowed,
                         it != nullptr ? it->GetName() : property_name));
      }
    }
  }
  // 9. If O is not undefined, then:
  if (it != nullptr) {
    // 9a. For each field of Desc that is present, set the corresponding
    // attribute of the property named P of object O to the value of the field.
    PropertyAttributes attrs = NONE;
    if (desc->has_enumerable()) {
      attrs = static_cast<PropertyAttributes>(
          attrs | (desc->enumerable() ? NONE : DONT_ENUM));
    } else {
      attrs = static_cast<PropertyAttributes>(
          attrs | (current->enumerable() ? NONE : DONT_ENUM));
    }
    if (desc->has_configurable()) {
      attrs = static_cast<PropertyAttributes>(
          attrs | (desc->configurable() ? NONE : DONT_DELETE));
    } else {
      attrs = static_cast<PropertyAttributes>(
          attrs | (current->configurable() ? NONE : DONT_DELETE));
    }
    if (desc_is_data_descriptor ||
        (desc_is_generic_descriptor && current_is_data_descriptor)) {
      if (desc->has_writable()) {
        attrs = static_cast<PropertyAttributes>(
            attrs | (desc->writable() ? NONE : READ_ONLY));
      } else {
        attrs = static_cast<PropertyAttributes>(
            attrs | (current->writable() ? NONE : READ_ONLY));
      }
      DirectHandle<Object> value(
          desc->has_value() ? desc->value()
          : current->has_value()
              ? current->value()
              : Cast<Object>(isolate->factory()->undefined_value()));
      return JSObject::DefineOwnPropertyIgnoreAttributes(it, value, attrs,
                                                         should_throw);
    } else {
      DCHECK(desc_is_accessor_descriptor ||
             (desc_is_generic_descriptor &&
              PropertyDescriptor::IsAccessorDescriptor(current)));
      DirectHandle<Object> getter(
          desc->has_get() ? desc->get()
          : current->has_get()
              ? current->get()
              : Cast<Object>(isolate->factory()->null_value()));
      DirectHandle<Object> setter(
          desc->has_set() ? desc->set()
          : current->has_set()
              ? current->set()
              : Cast<Object>(isolate->factory()->null_value()));
      MaybeDirectHandle<Object> result =
          JSObject::DefineOwnAccessorIgnoreAttributes(it, getter, setter,
                                                      attrs);
      if (result.is_null()) return Nothing<bool>();
    }
  }
  // 10. Return true.
  return Just(true);
}
References v8::internal::PropertyDescriptor::configurable(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::JSObject::DefineOwnAccessorIgnoreAttributes(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, v8::internal::PropertyDescriptor::enumerable(), v8::internal::Isolate::factory(), v8::internal::PropertyDescriptor::get(), v8::internal::LookupIterator::GetName(), v8::internal::GetShouldThrow(), v8::internal::PropertyDescriptor::has_configurable(), v8::internal::PropertyDescriptor::has_enumerable(), v8::internal::PropertyDescriptor::has_get(), v8::internal::PropertyDescriptor::has_set(), v8::internal::PropertyDescriptor::has_value(), v8::internal::PropertyDescriptor::has_writable(), v8::internal::PropertyDescriptor::is_empty(), v8::internal::DirectHandle< T >::is_null(), v8::internal::PropertyDescriptor::IsAccessorDescriptor(), v8::internal::PropertyDescriptor::IsDataDescriptor(), v8::internal::PropertyDescriptor::IsGenericDescriptor(), v8::Just(), v8::internal::NONE, v8::internal::READ_ONLY, v8::base::internal::result, RETURN_FAILURE, v8::internal::Object::SameValue(), v8::internal::PropertyDescriptor::set(), v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_writable(), v8::internal::setter, v8::internal::PropertyDescriptor::ToAttributes(), v8::internal::value, v8::internal::PropertyDescriptor::value(), and v8::internal::PropertyDescriptor::writable().
Referenced by IsCompatiblePropertyDescriptor(), and OrdinaryDefineOwnProperty().
Member Data Documentation
kHashMask
const int v8::internal::JSReceiver::kHashMask = PropertyArray::HashField::kMask [static]
Definition at line 352 of file js-objects.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-objects.h
/mnt/V8SourceCode/src/objects/js-objects-inl.h
/mnt/V8SourceCode/src/objects/js-objects.cc