v8::internal::SwissNameDictionary Class Reference
#include <objects-body-descriptors-inl.h>
Classes
class IndexIterable
class IndexIterator
Public Types
using Group = swiss_table::Group
using Offset = int
Public Member Functions
template<typename IsolateT , template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< SwissNameDictionary >, DirectHandle< SwissNameDictionary >>) inline static HandleType< SwissNameDictionary > Add(IsolateT *isolate
template<template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< SwissNameDictionary >, DirectHandle< SwissNameDictionary >>) static HandleType< SwissNameDictionary > Shrink(Isolate *isolate
template<template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< SwissNameDictionary >, DirectHandle< SwissNameDictionary >>) static HandleType< SwissNameDictionary > DeleteEntry(Isolate *isolate
template<typename IsolateT >
InternalIndex FindEntry (IsolateT *isolate, Tagged< Object > key)
template<typename IsolateT >
InternalIndex FindEntry (IsolateT *isolate, DirectHandle< Object > key)
bool ToKey (ReadOnlyRoots roots, InternalIndex entry, Tagged< Object > *out_key)
Tagged< Object > KeyAt (InternalIndex entry)
Tagged< Name > NameAt (InternalIndex entry)
Tagged< Object > ValueAt (InternalIndex entry)
std::optional< Tagged< Object > > TryValueAt (InternalIndex entry)
PropertyDetails DetailsAt (InternalIndex entry)
void ValueAtPut (InternalIndex entry, Tagged< Object > value)
void DetailsAtPut (InternalIndex entry, PropertyDetails value)
int NumberOfElements ()
int NumberOfDeletedElements ()
int Capacity ()
int UsedCapacity ()
int NumberOfEnumerableProperties ()
bool may_have_interesting_properties ()
void set_may_have_interesting_properties (bool value)
bool EqualsForTesting (Tagged< SwissNameDictionary > other)
template<typename IsolateT >
void Initialize (IsolateT *isolate, Tagged< ByteArray > meta_table, int capacity)
template<typename IsolateT , template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< SwissNameDictionary >, DirectHandle< SwissNameDictionary >>) static HandleType< SwissNameDictionary > Rehash(IsolateT *isolate
template<typename IsolateT >
void Rehash (IsolateT *isolate)
void SetHash (int hash)
int Hash ()
Tagged< Object > SlowReverseLookup (Isolate *isolate, Tagged< Object > value)
IndexIterable IterateEntriesOrdered ()
IndexIterable IterateEntries ()
int EntryForEnumerationIndex (int enumeration_index)
OBJECT_CONSTRUCTORS (SwissNameDictionary, HeapObject)
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
static int SizeOf (Tagged< Map > map, Tagged< HeapObject > obj)
static bool IsKey (ReadOnlyRoots roots, Tagged< Object > key_candidate)
static DirectHandle< SwissNameDictionary > ShallowCopy (Isolate *isolate, DirectHandle< SwissNameDictionary > table)
static constexpr bool IsValidCapacity (int capacity)
static int CapacityFor (int at_least_space_for)
static constexpr int MaxUsableCapacity (int capacity)
static constexpr int MaxCapacity ()
static constexpr int SizeFor (int capacity)
static constexpr int MetaTableSizePerEntryFor (int capacity)
static constexpr int MetaTableSizeFor (int capacity)
static constexpr int DataTableSize (int capacity)
static constexpr int CtrlTableSize (int capacity)
static constexpr Offset PrefixOffset ()
static constexpr Offset CapacityOffset ()
static constexpr Offset MetaTablePointerOffset ()
static constexpr Offset DataTableStartOffset ()
static constexpr Offset DataTableEndOffset (int capacity)
static constexpr Offset CtrlTableStartOffset (int capacity)
static constexpr Offset PropertyDetailsTableStartOffset (int capacity)
Public Attributes
HandleType< SwissNameDictionary > table
HandleType< SwissNameDictionary > DirectHandle< Name > key
HandleType< SwissNameDictionary > DirectHandle< Name > DirectHandle< Object > value
HandleType< SwissNameDictionary > DirectHandle< Name > DirectHandle< Object > PropertyDetails details
HandleType< SwissNameDictionary > DirectHandle< Name > DirectHandle< Object > PropertyDetails InternalIndex * entry_out = nullptr)
HandleType< SwissNameDictionary > InternalIndex entry
HandleType< SwissNameDictionary > int new_capacity
Static Public Attributes
static constexpr bool kIsOrderedDictionaryType = true
static constexpr int kNotFoundSentinel = -1
static const int kGroupWidth = Group::kWidth
static const bool kUseSIMD = kGroupWidth == 16
static constexpr int kInitialCapacity = kSwissNameDictionaryInitialCapacity
static constexpr int kDataTableEntryCount = 2
static constexpr int kDataTableKeyEntryIndex = 0
static constexpr int kDataTableValueEntryIndex = kDataTableKeyEntryIndex + 1
static constexpr int kMetaTableElementCountFieldIndex = 0
static constexpr int kMetaTableDeletedElementCountFieldIndex = 1
static constexpr int kMetaTableEnumerationDataStartIndex = 2
static constexpr int kMax1ByteMetaTableCapacity = (1 << 8)
static constexpr int kMax2ByteMetaTableCapacity = (1 << 16)
Private Types
using ctrl_t = swiss_table::ctrl_t
using Ctrl = swiss_table::Ctrl
Private Member Functions
template<typename IsolateT , template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< SwissNameDictionary >, DirectHandle< SwissNameDictionary >>) inline static HandleType< SwissNameDictionary > EnsureGrowable(IsolateT *isolate
uint8_t * PropertyDetailsTable ()
void ClearDataTableEntry (Isolate *isolate, int entry)
void SetKey (int entry, Tagged< Object > key)
void DetailsAtPut (int entry, PropertyDetails value)
void ValueAtPut (int entry, Tagged< Object > value)
PropertyDetails DetailsAt (int entry)
Tagged< Object > ValueAtRaw (int entry)
Tagged< Object > KeyAt (int entry)
bool ToKey (ReadOnlyRoots roots, int entry, Tagged< Object > *out_key)
int FindFirstEmpty (uint32_t hash)
int AddInternal (Tagged< Name > key, Tagged< Object > value, PropertyDetails details)
ctrl_t * CtrlTable ()
void SetCtrl (int entry, ctrl_t h)
ctrl_t GetCtrl (int entry)
Tagged< Object > LoadFromDataTable (int entry, int data_offset)
Tagged< Object > LoadFromDataTable (PtrComprCageBase cage_base, int entry, int data_offset)
void StoreToDataTable (int entry, int data_offset, Tagged< Object > data)
void StoreToDataTableNoBarrier (int entry, int data_offset, Tagged< Object > data)
void SetCapacity (int capacity)
void SetNumberOfElements (int elements)
void SetNumberOfDeletedElements (int deleted_elements)
void SetEntryForEnumerationIndex (int enumeration_index, int entry)
void SetMetaTableField (int field_index, int value)
int GetMetaTableField (int field_index)
Static Private Member Functions
static bool IsEmpty (ctrl_t c)
static bool IsFull (ctrl_t c)
static bool IsDeleted (ctrl_t c)
static bool IsEmptyOrDeleted (ctrl_t c)
static swiss_table::ProbeSequence< Group::kWidth > probe (uint32_t hash, int capacity)
template<typename T >
static void SetMetaTableField (Tagged< ByteArray > meta_table, int field_index, int value)
template<typename T >
static int GetMetaTableField (Tagged< ByteArray > meta_table, int field_index)
Additional Inherited Members
Detailed Description
Definition at line 739 of file objects-body-descriptors-inl.h.
Member Typedef Documentation
Ctrl
using v8::internal::SwissNameDictionary::Ctrl = swiss_table::Ctrl [private]
Definition at line 282 of file swiss-name-dictionary.h.
ctrl_t
using v8::internal::SwissNameDictionary::ctrl_t = swiss_table::ctrl_t [private]
Definition at line 281 of file swiss-name-dictionary.h.
Group
using v8::internal::SwissNameDictionary::Group = swiss_table::Group
Definition at line 73 of file swiss-name-dictionary.h.
Offset
using v8::internal::SwissNameDictionary::Offset = int
Definition at line 264 of file swiss-name-dictionary.h.
Member Function Documentation
AddInternal()
int v8::internal::SwissNameDictionary::AddInternal (Tagged< Name > key, Tagged< Object > value, PropertyDetails details) [inline], [private]
Definition at line 541 of file swiss-name-dictionary-inl.h.
                                                              {
  DisallowHeapAllocation no_gc;
  DCHECK(IsUniqueName(key));
  DCHECK_LE(UsedCapacity(), MaxUsableCapacity(Capacity()));
  uint32_t hash = key->hash();
  // For now we don't reuse deleted buckets (due to enumeration table
  // complications), which is why we only look for empty buckets here, not
  // deleted ones.
  int target = FindFirstEmpty(hash);
  SetCtrl(target, swiss_table::H2(hash));
  SetKey(target, key);
  ValueAtPut(target, value);
  DetailsAtPut(target, details);
  // Note that we do not update the number of elements or the enumeration table
  // in this function.
  return target;
}
References Capacity(), v8::internal::DCHECK(), DCHECK_LE, details, DetailsAtPut(), FindFirstEmpty(), v8::internal::swiss_table::H2(), v8::internal::IsUniqueName(), key, MaxUsableCapacity(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, SetCtrl(), SetKey(), UsedCapacity(), value, and ValueAtPut().
Referenced by Rehash().
Capacity()
int v8::internal::SwissNameDictionary::Capacity () [inline]
Definition at line 44 of file swiss-name-dictionary-inl.h.
                                  {
  return ReadField<int32_t>(CapacityOffset());
}
References CapacityOffset().
Referenced by AddInternal(), DetailsAtPut(), EqualsForTesting(), FindEntry(), FindFirstEmpty(), GetCtrl(), GetMetaTableField(), IterateEntriesOrdered(), LoadFromDataTable(), PropertyDetailsTable(), Rehash(), v8::internal::requires(), SetCtrl(), SetEntryForEnumerationIndex(), SetMetaTableField(), StoreToDataTable(), StoreToDataTableNoBarrier(), and TryValueAt().
CapacityFor()
int v8::internal::SwissNameDictionary::CapacityFor (int at_least_space_for) [inline], [static]
Definition at line 117 of file swiss-name-dictionary-inl.h.
                                                           {
  if (at_least_space_for <= 4) {
    if (at_least_space_for == 0) {
      return 0;
    } else if (at_least_space_for < 4) {
      return 4;
    } else if (kGroupWidth == 16) {
      DCHECK_EQ(4, at_least_space_for);
      return 4;
    } else if (kGroupWidth == 8) {
      DCHECK_EQ(4, at_least_space_for);
      return 8;
    }
  }
  int non_normalized = at_least_space_for + at_least_space_for / 7;
  return base::bits::RoundUpToPowerOfTwo32(non_normalized);
}
References DCHECK_EQ, and kGroupWidth.
Referenced by v8::internal::FactoryBase< Impl >::NewSwissNameDictionary().
CapacityOffset()
constexpr int v8::internal::SwissNameDictionary::CapacityOffset () [inline], [static], [constexpr]
Definition at line 680 of file swiss-name-dictionary-inl.h.
                                                  {
  return PrefixOffset() + sizeof(uint32_t);
}
References PrefixOffset().
Referenced by Capacity(), MetaTablePointerOffset(), SetCapacity(), and v8::internal::CodeStubAssembler::StoreSwissNameDictionaryCapacity().
ClearDataTableEntry()
void v8::internal::SwissNameDictionary::ClearDataTableEntry (Isolate * isolate, int entry) [inline], [private]
Definition at line 258 of file swiss-name-dictionary-inl.h.
                                                                         {
  ReadOnlyRoots roots(isolate);
  StoreToDataTable(entry, kDataTableKeyEntryIndex, roots.the_hole_value());
  StoreToDataTable(entry, kDataTableValueEntryIndex, roots.the_hole_value());
}
References entry, kDataTableKeyEntryIndex, kDataTableValueEntryIndex, and StoreToDataTable().
CtrlTable()
swiss_table::ctrl_t * v8::internal::SwissNameDictionary::CtrlTable () [inline], [private]
Definition at line 34 of file swiss-name-dictionary-inl.h.
                                                  {
  return reinterpret_cast<ctrl_t*>(
      field_address(CtrlTableStartOffset(Capacity())));
}
Referenced by EqualsForTesting(), FindEntry(), FindFirstEmpty(), GetCtrl(), Initialize(), and SetCtrl().
CtrlTableSize()
constexpr int v8::internal::SwissNameDictionary::CtrlTableSize (int capacity) [inline], [static], [constexpr]
Definition at line 87 of file swiss-name-dictionary-inl.h.
                                                             {
  // Doing + |kGroupWidth| due to the copy of first group at the end of control
  // table.
  return (capacity + kGroupWidth) * kOneByteSize;
}
References kGroupWidth, and v8::internal::kOneByteSize.
Referenced by Initialize(), PropertyDetailsTableStartOffset(), and ShallowCopy().
CtrlTableStartOffset()
constexpr int v8::internal::SwissNameDictionary::CtrlTableStartOffset (int capacity) [inline], [static], [constexpr]
Definition at line 700 of file swiss-name-dictionary-inl.h.
                                                                    {
  return DataTableStartOffset() + DataTableSize(capacity);
}
References DataTableSize(), and DataTableStartOffset().
Referenced by DataTableEndOffset(), PropertyDetailsTableStartOffset(), and ShallowCopy().
DataTableEndOffset()
constexpr int v8::internal::SwissNameDictionary::DataTableEndOffset (int capacity) [inline], [static], [constexpr]
Definition at line 695 of file swiss-name-dictionary-inl.h.
                                                                  {
  return CtrlTableStartOffset(capacity);
}
References CtrlTableStartOffset().
Referenced by ShallowCopy().
DataTableSize()
constexpr int v8::internal::SwissNameDictionary::DataTableSize (int capacity) [inline], [static], [constexpr]
Definition at line 82 of file swiss-name-dictionary-inl.h.
                                                             {
  return capacity * kTaggedSize * kDataTableEntryCount;
}
References kDataTableEntryCount, and v8::internal::kTaggedSize.
Referenced by CtrlTableStartOffset(), and ShallowCopy().
DataTableStartOffset()
constexpr int v8::internal::SwissNameDictionary::DataTableStartOffset () [inline], [static], [constexpr]
Definition at line 690 of file swiss-name-dictionary-inl.h.
                                                        {
  return MetaTablePointerOffset() + kTaggedSize;
}
References v8::internal::kTaggedSize, and MetaTablePointerOffset().
Referenced by v8::internal::CodeStubAssembler::CopySwissNameDictionary(), CtrlTableStartOffset(), Initialize(), LoadFromDataTable(), MaxCapacity(), ShallowCopy(), StoreToDataTable(), and StoreToDataTableNoBarrier().
DetailsAt() [1/2]
PropertyDetails v8::internal::SwissNameDictionary::DetailsAt (int entry) [inline], [private]
Definition at line 330 of file swiss-name-dictionary-inl.h.
                                                        {
  // GetCtrl(entry) does a bounds check for |entry| value.
  DCHECK(IsFull(GetCtrl(entry)));
  uint8_t encoded_details = PropertyDetailsTable()[entry];
  return PropertyDetails::FromByte(encoded_details);
}
References v8::internal::DCHECK(), entry, v8::internal::PropertyDetails::FromByte(), GetCtrl(), IsFull(), and PropertyDetailsTable().
DetailsAt() [2/2]
PropertyDetails v8::internal::SwissNameDictionary::DetailsAt (InternalIndex entry) [inline]
Definition at line 338 of file swiss-name-dictionary-inl.h.
                                                                  {
  return DetailsAt(entry.as_int());
}
References v8::internal::InternalIndex::as_int(), and entry.
Referenced by EqualsForTesting(), NumberOfEnumerableProperties(), and Rehash().
DetailsAtPut() [1/2]
void v8::internal::SwissNameDictionary::DetailsAtPut (int entry, PropertyDetails value) [inline], [private]
Definition at line 280 of file swiss-name-dictionary-inl.h.
                                                                         {
  DCHECK_LT(static_cast<unsigned>(entry), static_cast<unsigned>(Capacity()));
  uint8_t encoded_details = details.ToByte();
  PropertyDetailsTable()[entry] = encoded_details;
}
References Capacity(), DCHECK_LT, details, entry, PropertyDetailsTable(), and v8::internal::PropertyDetails::ToByte().
DetailsAtPut() [2/2]
void v8::internal::SwissNameDictionary::DetailsAtPut (InternalIndex entry, PropertyDetails value) [inline]
Definition at line 286 of file swiss-name-dictionary-inl.h.
                                                                {
  DetailsAtPut(entry.as_int(), details);
}
References v8::internal::InternalIndex::as_int(), details, and entry.
Referenced by AddInternal().
EntryForEnumerationIndex()
int v8::internal::SwissNameDictionary::EntryForEnumerationIndex (int enumeration_index) [inline]
Definition at line 136 of file swiss-name-dictionary-inl.h.
                                                                       {
  DCHECK_LT(enumeration_index, UsedCapacity());
  return GetMetaTableField(kMetaTableEnumerationDataStartIndex +
                           enumeration_index);
}
References DCHECK_LT, GetMetaTableField(), kMetaTableEnumerationDataStartIndex, and UsedCapacity().
Referenced by EqualsForTesting(), and Rehash().
EqualsForTesting()
bool v8::internal::SwissNameDictionary::EqualsForTesting (Tagged< SwissNameDictionary > other)
Definition at line 88 of file swiss-name-dictionary.cc.
                                                                            {
  if (Capacity() != other->Capacity() ||
      NumberOfElements() != other->NumberOfElements() ||
      NumberOfDeletedElements() != other->NumberOfDeletedElements() ||
      Hash() != other->Hash()) {
    return false;
  }
  for (int i = 0; i < Capacity() + kGroupWidth; i++) {
    if (CtrlTable()[i] != other->CtrlTable()[i]) {
      return false;
    }
  }
  for (int i = 0; i < Capacity(); i++) {
    if (KeyAt(i) != other->KeyAt(i) || ValueAtRaw(i) != other->ValueAtRaw(i)) {
      return false;
    }
    if (IsFull(GetCtrl(i))) {
      if (DetailsAt(i) != other->DetailsAt(i)) return false;
    }
  }
  for (int i = 0; i < UsedCapacity(); i++) {
    if (EntryForEnumerationIndex(i) != other->EntryForEnumerationIndex(i)) {
      return false;
    }
  }
  return true;
}
References Capacity(), CtrlTable(), DetailsAt(), EntryForEnumerationIndex(), GetCtrl(), Hash(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, IsFull(), KeyAt(), kGroupWidth, NumberOfDeletedElements(), NumberOfElements(), UsedCapacity(), and ValueAtRaw().
FindEntry() [1/2]
template<typename IsolateT >
InternalIndex v8::internal::SwissNameDictionary::FindEntry (IsolateT * isolate, DirectHandle< Object > key) [inline]
Definition at line 219 of file swiss-name-dictionary-inl.h.
                                                                       {
  return FindEntry(isolate, *key);
}
References FindEntry(), and key.
FindEntry() [2/2]
template<typename IsolateT >
InternalIndex v8::internal::SwissNameDictionary::FindEntry (IsolateT * isolate, Tagged< Object > key) [inline]
Definition at line 153 of file swiss-name-dictionary-inl.h.
                                                                 {
  Tagged<Name> name = Cast<Name>(key);
  DCHECK(IsUniqueName(name));
  uint32_t hash = name->hash();
  // We probe the hash table in groups of |kGroupWidth| buckets. One bucket
  // corresponds to a 1-byte entry in the control table.
  // Each group can be uniquely identified by the index of its first bucket,
  // which must be a value between 0 (inclusive) and Capacity() (exclusive).
  // Note that logically, groups wrap around after index Capacity() - 1. This
  // means that probing the group starting at, for example, index Capacity() - 1
  // means probing CtrlTable()[Capacity() - 1] followed by CtrlTable()[0] to
  // CtrlTable()[6], assuming a group width of 8. However, in memory, this is
  // achieved by maintaining an additional |kGroupWidth| bytes after the first
  // Capacity() entries of the control table. These contain a copy of the first
  // max(Capacity(), kGroupWidth) entries of the control table. If Capacity() <
  // |kGroupWidth|, then the remaining |kGroupWidth| - Capacity() control bytes
  // are left as |kEmpty|.
  // This means that actually, probing the group starting
  // at index Capacity() - 1 is achieved by probing CtrlTable()[Capacity() - 1],
  // followed by CtrlTable()[Capacity()] to CtrlTable()[Capacity() + 7].
  ctrl_t* ctrl = CtrlTable();
  auto seq = probe(hash, Capacity());
  // At this point, seq.offset() denotes the index of the first bucket in the
  // first group to probe. Note that this doesn't have to be divisible by
  // |kGroupWidth|, but can have any value between 0 (inclusive) and Capacity()
  // (exclusive).
  while (true) {
    Group g{ctrl + seq.offset()};
    for (int i : g.Match(swiss_table::H2(hash))) {
      int candidate_entry = seq.offset(i);
      Tagged<Object> candidate_key = KeyAt(candidate_entry);
      // This key matching is SwissNameDictionary specific!
      if (candidate_key == key) return InternalIndex(candidate_entry);
    }
    if (g.MatchEmpty()) return InternalIndex::NotFound();
    // The following selects the next group to probe. Note that seq.offset()
    // always advances by a multiple of |kGroupWidth|, modulo Capacity(). This
    // is done in a way such that we visit Capacity() / |kGroupWidth|
    // non-overlapping (!) groups before we would visit the same group (or
    // bucket) again.
    seq.next();
    // If the following DCHECK weren't true, we would have probed all Capacity()
    // different buckets without finding one containing |kEmpty| (which would
    // haved triggered the g.MatchEmpty() check above). This must not be the
    // case because the maximum load factor of 7/8 guarantees that there must
    // always remain empty buckets.
    //
    // The only exception from this rule are small tables, where 2 * Capacity()
    // < |kGroupWidth|, in which case all Capacity() entries can be filled
    // without leaving empty buckets. The layout of the control
    // table guarantees that after the first Capacity() entries of the control
    // table, the control table contains a copy of those first Capacity()
    // entries, followed by kGroupWidth - 2 * Capacity() entries containing
    // |kEmpty|. This guarantees that the g.MatchEmpty() check above will
    // always trigger if the element wasn't found, correctly preventing us from
    // probing more than one group in this special case.
    DCHECK_LT(seq.index(), Capacity());
  }
}
References Capacity(), CtrlTable(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::swiss_table::H2(), v8::internal::IsUniqueName(), key, KeyAt(), v8::internal::name, v8::internal::InternalIndex::NotFound(), and probe().
Referenced by FindEntry().
FindFirstEmpty()
int v8::internal::SwissNameDictionary::FindFirstEmpty (uint32_t hash) [inline], [private]
Definition at line 395 of file swiss-name-dictionary-inl.h.
                                                            {
  // See SwissNameDictionary::FindEntry for description of probing algorithm.
  auto seq = probe(hash, Capacity());
  while (true) {
    Group g{CtrlTable() + seq.offset()};
    auto mask = g.MatchEmpty();
    if (mask) {
      // Note that picking the lowest bit set here means using the leftmost
      // empty bucket in the group. Here, "left" means smaller entry/bucket
      // index.
      return seq.offset(mask.LowestBitSet());
    }
    seq.next();
    DCHECK_LT(seq.index(), Capacity());
  }
}
References Capacity(), CtrlTable(), DCHECK_LT, and probe().
Referenced by AddInternal().
GetCtrl()
swiss_table::ctrl_t v8::internal::SwissNameDictionary::GetCtrl (int entry) [inline], [private]
Definition at line 359 of file swiss-name-dictionary-inl.h.
                                                        {
  DCHECK_LT(static_cast<unsigned>(entry), static_cast<unsigned>(Capacity()));
  return CtrlTable()[entry];
}
References Capacity(), CtrlTable(), DCHECK_LT, and entry.
Referenced by DetailsAt(), EqualsForTesting(), SetEntryForEnumerationIndex(), and ValueAt().
GetMetaTableField() [1/2]
int v8::internal::SwissNameDictionary::GetMetaTableField (int field_index) [inline], [private]
Definition at line 428 of file swiss-name-dictionary-inl.h.
                                                          {
  // See the STATIC_ASSERTs on |kMax1ByteMetaTableCapacity| and
  // |kMax2ByteMetaTableCapacity| in the .cc file for an explanation of these
  // constants.
  int capacity = Capacity();
  Tagged<ByteArray> meta_table = this->meta_table();
  if (capacity <= kMax1ByteMetaTableCapacity) {
    return GetMetaTableField<uint8_t>(meta_table, field_index);
  } else if (capacity <= kMax2ByteMetaTableCapacity) {
    return GetMetaTableField<uint16_t>(meta_table, field_index);
  } else {
    return GetMetaTableField<uint32_t>(meta_table, field_index);
  }
}
References Capacity(), kMax1ByteMetaTableCapacity, and kMax2ByteMetaTableCapacity.
Referenced by EntryForEnumerationIndex(), NumberOfDeletedElements(), and NumberOfElements().
GetMetaTableField() [2/2]
template<typename T >
int v8::internal::SwissNameDictionary::GetMetaTableField (Tagged< ByteArray > meta_table, int field_index) [inline], [static], [private]
Definition at line 457 of file swiss-name-dictionary-inl.h.
                                                            {
  static_assert((std::is_same_v<T, uint8_t>) || (std::is_same_v<T, uint16_t>) ||
                (std::is_same_v<T, uint32_t>));
  DCHECK_LT(meta_table->begin() + field_index * sizeof(T), meta_table->end());
  T* raw_data = reinterpret_cast<T*>(meta_table->begin());
  return raw_data[field_index];
}
References DCHECK_LT.
Hash()
int v8::internal::SwissNameDictionary::Hash () [inline]
Definition at line 672 of file swiss-name-dictionary-inl.h.
{ return ReadField<int32_t>(PrefixOffset()); }
References PrefixOffset().
Referenced by EqualsForTesting().
Initialize()
template<typename IsolateT >
template V8_EXPORT_PRIVATE void v8::internal::SwissNameDictionary::Initialize (IsolateT * isolate, Tagged< ByteArray > meta_table, int capacity)
Definition at line 567 of file swiss-name-dictionary-inl.h.
                                                   {
  DCHECK(IsValidCapacity(capacity));
  DisallowHeapAllocation no_gc;
  ReadOnlyRoots roots(isolate);
  SetCapacity(capacity);
  SetHash(PropertyArray::kNoHashSentinel);
  memset(CtrlTable(), Ctrl::kEmpty, CtrlTableSize(capacity));
  MemsetTagged(RawField(DataTableStartOffset()), roots.the_hole_value(),
               capacity * kDataTableEntryCount);
  set_meta_table(meta_table);
  SetNumberOfElements(0);
  SetNumberOfDeletedElements(0);
  // We leave the enumeration table PropertyDetails table and uninitialized.
}
References CtrlTable(), CtrlTableSize(), DataTableStartOffset(), v8::internal::DCHECK(), IsValidCapacity(), kDataTableEntryCount, v8::internal::swiss_table::kEmpty, v8::internal::PropertyArray::kNoHashSentinel, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::HeapObject::RawField(), SetCapacity(), SetHash(), SetNumberOfDeletedElements(), and SetNumberOfElements().
Referenced by Rehash().
IsDeleted()
bool v8::internal::SwissNameDictionary::IsDeleted (ctrl_t c) [inline], [static], [private]
Definition at line 745 of file swiss-name-dictionary-inl.h.
{ return c == Ctrl::kDeleted; }
References v8::internal::swiss_table::kDeleted.
IsEmpty()
bool v8::internal::SwissNameDictionary::IsEmpty (ctrl_t c) [inline], [static], [private]
Definition at line 734 of file swiss-name-dictionary-inl.h.
{ return c == Ctrl::kEmpty; }
References v8::internal::swiss_table::kEmpty.
IsEmptyOrDeleted()
bool v8::internal::SwissNameDictionary::IsEmptyOrDeleted (ctrl_t c) [inline], [static], [private]
Definition at line 748 of file swiss-name-dictionary-inl.h.
                                                   {
  static_assert(Ctrl::kDeleted < Ctrl::kSentinel);
  static_assert(Ctrl::kEmpty < Ctrl::kSentinel);
  static_assert(Ctrl::kSentinel < 0);
  return c < Ctrl::kSentinel;
}
References v8::internal::swiss_table::kDeleted, v8::internal::swiss_table::kEmpty, and v8::internal::swiss_table::kSentinel.
IsFull()
bool v8::internal::SwissNameDictionary::IsFull (ctrl_t c) [inline], [static], [private]
Definition at line 737 of file swiss-name-dictionary-inl.h.
                                         {
  static_assert(Ctrl::kEmpty < 0);
  static_assert(Ctrl::kDeleted < 0);
  static_assert(Ctrl::kSentinel < 0);
  return c >= 0;
}
References v8::internal::swiss_table::kDeleted, v8::internal::swiss_table::kEmpty, and v8::internal::swiss_table::kSentinel.
Referenced by DetailsAt(), EqualsForTesting(), SetEntryForEnumerationIndex(), ShallowCopy(), and ValueAt().
IsKey()
bool v8::internal::SwissNameDictionary::IsKey (ReadOnlyRoots roots, Tagged< Object > key_candidate) [inline], [static]
Definition at line 493 of file swiss-name-dictionary-inl.h.
                                                              {
  return key_candidate != roots.the_hole_value();
}
Referenced by v8::internal::JSObject::MigrateSlowToFast(), and ToKey().
IsValidCapacity()
constexpr bool v8::internal::SwissNameDictionary::IsValidCapacity (int capacity) [inline], [static], [constexpr]
Definition at line 75 of file swiss-name-dictionary-inl.h.
                                                                {
  return capacity == 0 || (capacity >= kInitialCapacity &&
                           // Must be power of 2.
                           ((capacity & (capacity - 1)) == 0));
}
References kInitialCapacity.
Referenced by Initialize(), MaxUsableCapacity(), MetaTableSizeFor(), MetaTableSizePerEntryFor(), v8::internal::FactoryBase< Impl >::NewSwissNameDictionaryWithCapacity(), SetCapacity(), and SizeFor().
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::SwissNameDictionary::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 743 of file objects-body-descriptors-inl.h.
                                                                    {
    Tagged<SwissNameDictionary> table = UncheckedCast<SwissNameDictionary>(obj);
    static_assert(MetaTablePointerOffset() + kTaggedSize ==
                  DataTableStartOffset());
    int start_offset = MetaTablePointerOffset();
    int end_offset = table->DataTableEndOffset(table->Capacity());
    IteratePointers(obj, start_offset, end_offset, v);
  }
References v8::internal::kTaggedSize.
IterateEntries()
SwissNameDictionary::IndexIterable v8::internal::SwissNameDictionary::IterateEntries () [inline]
Definition at line 664 of file swiss-name-dictionary-inl.h.
                                                                     {
  return IterateEntriesOrdered();
}
References IterateEntriesOrdered().
Referenced by NumberOfEnumerableProperties(), and SlowReverseLookup().
IterateEntriesOrdered()
SwissNameDictionary::IndexIterable v8::internal::SwissNameDictionary::IterateEntriesOrdered () [inline]
Definition at line 647 of file swiss-name-dictionary-inl.h.
                                           {
  // If we are supposed to iterate the empty dictionary (which is non-writable),
  // we have no simple way to get the isolate, which we would need to create a
  // handle.
  // TODO(emrich): Consider always using roots.empty_swiss_dictionary()
  // in the condition once this function gets Isolate as a parameter in order to
  // avoid empty dict checks.
  if (Capacity() == 0) {
    return IndexIterable(DirectHandle<SwissNameDictionary>::null());
  }
  Isolate* isolate;
  GetIsolateFromHeapObject(*this, &isolate);
  DCHECK_NE(isolate, nullptr);
  return IndexIterable(direct_handle(*this, isolate));
}
References Capacity(), DCHECK_NE, v8::internal::direct_handle(), and v8::internal::GetIsolateFromHeapObject().
Referenced by IterateEntries().
KeyAt() [1/2]
Tagged< Object > v8::internal::SwissNameDictionary::KeyAt (int entry) [inline], [private]
Definition at line 291 of file swiss-name-dictionary-inl.h.
                                                   {
  return LoadFromDataTable(entry, kDataTableKeyEntryIndex);
}
References entry, kDataTableKeyEntryIndex, and LoadFromDataTable().
KeyAt() [2/2]
Tagged< Object > v8::internal::SwissNameDictionary::KeyAt (InternalIndex entry) [inline]
Definition at line 295 of file swiss-name-dictionary-inl.h.
                                                             {
  return KeyAt(entry.as_int());
}
References v8::internal::InternalIndex::as_int(), and entry.
Referenced by EqualsForTesting(), FindEntry(), NameAt(), and ToKey().
LoadFromDataTable() [1/2]
Tagged< Object > v8::internal::SwissNameDictionary::LoadFromDataTable (int entry, int data_offset) [inline], [private]
Definition at line 224 of file swiss-name-dictionary-inl.h.
                                                                       {
  return LoadFromDataTable(GetPtrComprCageBase(*this), entry, data_offset);
}
References entry, and v8::internal::GetPtrComprCageBase().
Referenced by KeyAt(), and ValueAtRaw().
LoadFromDataTable() [2/2]
Tagged< Object > v8::internal::SwissNameDictionary::LoadFromDataTable (PtrComprCageBase cage_base, int entry, int data_offset) [inline], [private]
Definition at line 229 of file swiss-name-dictionary-inl.h.
                                                            {
  DCHECK_LT(static_cast<unsigned>(entry), static_cast<unsigned>(Capacity()));
  int offset = DataTableStartOffset() +
               (entry * kDataTableEntryCount + data_offset) * kTaggedSize;
  return TaggedField<Object>::Relaxed_Load(cage_base, *this, offset);
}
References Capacity(), DataTableStartOffset(), DCHECK_LT, entry, kDataTableEntryCount, v8::internal::kTaggedSize, and v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load().
MaxCapacity()
constexpr int v8::internal::SwissNameDictionary::MaxCapacity () [inline], [static], [constexpr]
Definition at line 711 of file swiss-name-dictionary-inl.h.
                                               {
  constexpr int kConstSize =
      SwissNameDictionary::DataTableStartOffset() + sizeof(ByteArray::Header) +
      // Size for present and deleted element count at max capacity:
      2 * sizeof(uint32_t);
  constexpr int kPerEntrySize =
      // size of data table entries:
      kDataTableEntryCount * kTaggedSize +
      // ctrl table entry size:
      kOneByteSize +
      // PropertyDetails table entry size:
      kOneByteSize +
      // Enumeration table entry size at maximum capacity:
      sizeof(uint32_t);
  constexpr int result =
      (kMaxFixedArrayCapacity * kTaggedSize - kConstSize) / kPerEntrySize;
  static_assert(Smi::kMaxValue >= result);
  return result;
}
References DataTableStartOffset(), kDataTableEntryCount, v8::internal::kMaxFixedArrayCapacity, v8::internal::Smi::kMaxValue, v8::internal::kOneByteSize, v8::internal::kTaggedSize, and v8::base::internal::result.
Referenced by v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), and v8::internal::FactoryBase< Impl >::NewSwissNameDictionaryWithCapacity().
MaxUsableCapacity()
constexpr int v8::internal::SwissNameDictionary::MaxUsableCapacity (int capacity) [inline], [static], [constexpr]
Definition at line 103 of file swiss-name-dictionary-inl.h.
                                                                 {
  DCHECK(IsValidCapacity(capacity));
  if (Group::kWidth == 8 && capacity == 4) {
    // If the group size is 16 we can fully utilize capacity 4: There will be
    // enough kEmpty entries in the ctrl table.
    return 3;
  }
  return capacity - capacity / 8;
}
References v8::internal::DCHECK(), IsValidCapacity(), and v8::internal::swiss_table::GroupPortableImpl::kWidth.
Referenced by AddInternal(), and MetaTableSizeFor().
may_have_interesting_properties()
bool v8::internal::SwissNameDictionary::may_have_interesting_properties () [inline]
Definition at line 130 of file swiss-name-dictionary.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
MetaTablePointerOffset()
constexpr int v8::internal::SwissNameDictionary::MetaTablePointerOffset () [inline], [static], [constexpr]
Definition at line 685 of file swiss-name-dictionary-inl.h.
                                                          {
  return CapacityOffset() + sizeof(int32_t);
}
References CapacityOffset().
Referenced by DataTableStartOffset().
MetaTableSizeFor()
constexpr int v8::internal::SwissNameDictionary::MetaTableSizeFor (int capacity) [inline], [static], [constexpr]
Definition at line 481 of file swiss-name-dictionary-inl.h.
                                                                {
  DCHECK(IsValidCapacity(capacity));
  int per_entry_size = MetaTableSizePerEntryFor(capacity);
  // The enumeration table only needs to have as many slots as there can be
  // present + deleted entries in the hash table (= maximum load factor *
  // capactiy). Two more slots to store the number of present and deleted
  // entries.
  return per_entry_size * (MaxUsableCapacity(capacity) + 2);
}
References v8::internal::DCHECK(), IsValidCapacity(), MaxUsableCapacity(), and MetaTableSizePerEntryFor().
Referenced by v8::internal::FactoryBase< Impl >::NewSwissNameDictionaryWithCapacity().
MetaTableSizePerEntryFor()
constexpr int v8::internal::SwissNameDictionary::MetaTableSizePerEntryFor (int capacity) [inline], [static], [constexpr]
Definition at line 466 of file swiss-name-dictionary-inl.h.
                                                                        {
  DCHECK(IsValidCapacity(capacity));
  // See the STATIC_ASSERTs on |kMax1ByteMetaTableCapacity| and
  // |kMax2ByteMetaTableCapacity| in the .cc file for an explanation of these
  // constants.
  if (capacity <= kMax1ByteMetaTableCapacity) {
    return sizeof(uint8_t);
  } else if (capacity <= kMax2ByteMetaTableCapacity) {
    return sizeof(uint16_t);
  } else {
    return sizeof(uint32_t);
  }
}
References v8::internal::DCHECK(), IsValidCapacity(), kMax1ByteMetaTableCapacity, and kMax2ByteMetaTableCapacity.
Referenced by MetaTableSizeFor(), and ShallowCopy().
NameAt()
Tagged< Name > v8::internal::SwissNameDictionary::NameAt (InternalIndex entry) [inline]
Definition at line 299 of file swiss-name-dictionary-inl.h.
                                                            {
  return Cast<Name>(KeyAt(entry));
}
References entry, and KeyAt().
NumberOfDeletedElements()
int v8::internal::SwissNameDictionary::NumberOfDeletedElements () [inline]
Definition at line 58 of file swiss-name-dictionary-inl.h.
                                                 {
  return GetMetaTableField(kMetaTableDeletedElementCountFieldIndex);
}
References GetMetaTableField(), and kMetaTableDeletedElementCountFieldIndex.
Referenced by EqualsForTesting(), and UsedCapacity().
NumberOfElements()
int v8::internal::SwissNameDictionary::NumberOfElements () [inline]
Definition at line 54 of file swiss-name-dictionary-inl.h.
                                          {
  return GetMetaTableField(kMetaTableElementCountFieldIndex);
}
References GetMetaTableField(), and kMetaTableElementCountFieldIndex.
Referenced by EqualsForTesting(), Rehash(), and UsedCapacity().
NumberOfEnumerableProperties()
int v8::internal::SwissNameDictionary::NumberOfEnumerableProperties ()
Definition at line 266 of file swiss-name-dictionary.cc.
                                                      {
  ReadOnlyRoots roots = GetReadOnlyRoots();
  int result = 0;
  for (InternalIndex i : this->IterateEntries()) {
    Tagged<Object> k;
    if (!this->ToKey(roots, i, &k)) continue;
    if (Object::FilterKey(k, ENUMERABLE_STRINGS)) continue;
    PropertyDetails details = this->DetailsAt(i);
    PropertyAttributes attr = details.attributes();
    if ((int{attr} & ONLY_ENUMERABLE) == 0) result++;
  }
  return result;
}
References v8::internal::PropertyDetails::attributes(), details, DetailsAt(), v8::internal::ENUMERABLE_STRINGS, v8::internal::Object::FilterKey(), v8::internal::GetReadOnlyRoots(), IterateEntries(), v8::internal::ONLY_ENUMERABLE, v8::base::internal::result, and ToKey().
OBJECT_CONSTRUCTORS()
v8::internal::SwissNameDictionary::OBJECT_CONSTRUCTORS (SwissNameDictionary , HeapObject)
PrefixOffset()
constexpr int v8::internal::SwissNameDictionary::PrefixOffset () [inline], [static], [constexpr]
Definition at line 675 of file swiss-name-dictionary-inl.h.
                                                {
  return HeapObject::kHeaderSize;
}
References v8::internal::HeapObject::kHeaderSize.
Referenced by CapacityOffset(), Hash(), and SetHash().
probe()
swiss_table::ProbeSequence< SwissNameDictionary::kGroupWidth > v8::internal::SwissNameDictionary::probe (uint32_t hash, int capacity) [inline], [static], [private]
Definition at line 757 of file swiss-name-dictionary-inl.h.
                                                      {
  // If |capacity| is 0, we must produce 1 here, such that the - 1 below
  // yields 0, which is the correct modulo mask for a table of capacity 0.
  int non_zero_capacity = capacity | (capacity == 0);
  return swiss_table::ProbeSequence<SwissNameDictionary::kGroupWidth>(
      swiss_table::H1(hash), static_cast<uint32_t>(non_zero_capacity - 1));
}
References v8::internal::swiss_table::H1().
Referenced by FindEntry(), and FindFirstEmpty().
PropertyDetailsTable()
uint8_t * v8::internal::SwissNameDictionary::PropertyDetailsTable () [inline], [private]
Definition at line 39 of file swiss-name-dictionary-inl.h.
                                                   {
  return reinterpret_cast<uint8_t*>(
      field_address(PropertyDetailsTableStartOffset(Capacity())));
}
References Capacity(), v8::internal::HeapObject::field_address(), and PropertyDetailsTableStartOffset().
Referenced by DetailsAt(), and DetailsAtPut().
PropertyDetailsTableStartOffset()
constexpr int v8::internal::SwissNameDictionary::PropertyDetailsTableStartOffset (int capacity) [inline], [static], [constexpr]
Definition at line 705 of file swiss-name-dictionary-inl.h.
                  {
  return CtrlTableStartOffset(capacity) + CtrlTableSize(capacity);
}
References CtrlTableSize(), and CtrlTableStartOffset().
Referenced by PropertyDetailsTable(), and SizeFor().
Rehash()
template<typename IsolateT >
template V8_EXPORT_PRIVATE void v8::internal::SwissNameDictionary::Rehash (IsolateT * isolate)
Definition at line 223 of file swiss-name-dictionary.cc.
                                                  {
  DisallowHeapAllocation no_gc;
  struct Entry {
    Tagged<Name> key;
    Tagged<Object> value;
    PropertyDetails details;
  };
  if (Capacity() == 0) return;
  Entry dummy{Tagged<Name>(), Tagged<Object>(), PropertyDetails::Empty()};
  std::vector<Entry> data(NumberOfElements(), dummy);
  ReadOnlyRoots roots(isolate);
  int data_index = 0;
  for (int enum_index = 0; enum_index < UsedCapacity(); ++enum_index) {
    int entry = EntryForEnumerationIndex(enum_index);
    Tagged<Object> key;
    if (!ToKey(roots, entry, &key)) continue;
    data[data_index++] =
        Entry{Cast<Name>(key), ValueAtRaw(entry), DetailsAt(entry)};
  }
  Initialize(isolate, meta_table(), Capacity());
  int new_enum_index = 0;
  SetNumberOfElements(static_cast<int>(data.size()));
  for (Entry& e : data) {
    int new_entry = AddInternal(e.key, e.value, e.details);
    // TODO(v8::11388) Investigate ways of hoisting the branching needed to
    // select the correct meta table entry size (based on the capacity of the
    // table) out of the loop.
    SetEntryForEnumerationIndex(new_enum_index, new_entry);
    ++new_enum_index;
  }
}
References AddInternal(), Capacity(), details, DetailsAt(), v8::internal::PropertyDetails::Empty(), entry, EntryForEnumerationIndex(), Initialize(), key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, NumberOfElements(), SetEntryForEnumerationIndex(), SetNumberOfElements(), v8::internal::Tagged< Object >, ToKey(), UsedCapacity(), value, and ValueAtRaw().
requires() [1/5]
template<typename IsolateT , template< typename > typename HandleType>
v8::internal::SwissNameDictionary::requires (std::is_convertible_v< HandleType< SwissNameDictionary >, DirectHandle< SwissNameDictionary >>)
requires() [2/5]
template<typename IsolateT , template< typename > typename HandleType>
v8::internal::SwissNameDictionary::requires (std::is_convertible_v< HandleType< SwissNameDictionary >, DirectHandle< SwissNameDictionary >>) [private]
requires() [3/5]
template<template< typename > typename HandleType>
v8::internal::SwissNameDictionary::requires (std::is_convertible_v< HandleType< SwissNameDictionary >, DirectHandle< SwissNameDictionary >>)
requires() [4/5]
template<typename IsolateT , template< typename > typename HandleType>
v8::internal::SwissNameDictionary::requires (std::is_convertible_v< HandleType< SwissNameDictionary >, DirectHandle< SwissNameDictionary >>)
requires() [5/5]
template<template< typename > typename HandleType>
v8::internal::SwissNameDictionary::requires (std::is_convertible_v< HandleType< SwissNameDictionary >, DirectHandle< SwissNameDictionary >>)
set_may_have_interesting_properties()
void v8::internal::SwissNameDictionary::set_may_have_interesting_properties (bool value) [inline]
Definition at line 131 of file swiss-name-dictionary.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
SetCapacity()
void v8::internal::SwissNameDictionary::SetCapacity (int capacity) [inline], [private]
Definition at line 48 of file swiss-name-dictionary-inl.h.
                                                  {
  DCHECK(IsValidCapacity(capacity));
  WriteField<int32_t>(CapacityOffset(), capacity);
}
References CapacityOffset(), v8::internal::DCHECK(), and IsValidCapacity().
Referenced by Initialize().
SetCtrl()
void v8::internal::SwissNameDictionary::SetCtrl (int entry, ctrl_t h) [inline], [private]
Definition at line 365 of file swiss-name-dictionary-inl.h.
                                                     {
  int capacity = Capacity();
  DCHECK_LT(static_cast<unsigned>(entry), static_cast<unsigned>(capacity));
  ctrl_t* ctrl = CtrlTable();
  ctrl[entry] = h;
  // The ctrl table contains a copy of the first group (i.e., the group starting
  // at entry 0) after the first |capacity| entries of the ctrl table. This
  // means that the ctrl table always has size |capacity| + |kGroupWidth|.
  // However, note that we may have |capacity| < |kGroupWidth|. For example, if
  // Capacity() == 8 and |kGroupWidth| == 16, then ctrl[0] is copied to ctrl[8],
  // ctrl[1] to ctrl[9], etc. In this case, ctrl[16] to ctrl[23] remain unused,
  // which means that their values are always Ctrl::kEmpty.
  // We achieve the necessary copying without branching here using some bit
  // magic: We set {copy_entry = entry} in those cases where we don't actually
  // have to perform a copy (meaning that we just repeat the {ctrl[entry] = h}
  // from above). If we do need to do some actual copying, we set {copy_entry =
  // Capacity() + entry}.
  int mask = capacity - 1;
  int copy_entry =
      ((entry - Group::kWidth) & mask) + 1 + ((Group::kWidth - 1) & mask);
  DCHECK_IMPLIES(entry < static_cast<int>(Group::kWidth),
                 copy_entry == capacity + entry);
  DCHECK_IMPLIES(entry >= static_cast<int>(Group::kWidth), copy_entry == entry);
  ctrl[copy_entry] = h;
}
References Capacity(), CtrlTable(), DCHECK_IMPLIES, DCHECK_LT, entry, h(), and v8::internal::swiss_table::GroupPortableImpl::kWidth.
Referenced by AddInternal().
SetEntryForEnumerationIndex()
void v8::internal::SwissNameDictionary::SetEntryForEnumerationIndex (int enumeration_index, int entry) [inline], [private]
Definition at line 142 of file swiss-name-dictionary-inl.h.
                                                                 {
  DCHECK_LT(enumeration_index, UsedCapacity());
  DCHECK_LT(static_cast<unsigned>(entry), static_cast<unsigned>(Capacity()));
  DCHECK(IsFull(GetCtrl(entry)));
  SetMetaTableField(kMetaTableEnumerationDataStartIndex + enumeration_index,
                    entry);
}
References Capacity(), v8::internal::DCHECK(), DCHECK_LT, entry, GetCtrl(), IsFull(), kMetaTableEnumerationDataStartIndex, SetMetaTableField(), and UsedCapacity().
Referenced by Rehash().
SetHash()
void v8::internal::SwissNameDictionary::SetHash (int hash) [inline]
Definition at line 668 of file swiss-name-dictionary-inl.h.
                                              {
  WriteField(PrefixOffset(), hash);
}
References PrefixOffset(), and v8::internal::HeapObject::WriteField().
Referenced by Initialize().
SetKey()
void v8::internal::SwissNameDictionary::SetKey (int entry, Tagged< Object > key) [inline], [private]
Definition at line 275 of file swiss-name-dictionary-inl.h.
                                                              {
  DCHECK(!IsTheHole(key));
  StoreToDataTable(entry, kDataTableKeyEntryIndex, key);
}
References v8::internal::DCHECK(), entry, kDataTableKeyEntryIndex, key, and StoreToDataTable().
Referenced by AddInternal().
SetMetaTableField() [1/2]
void v8::internal::SwissNameDictionary::SetMetaTableField (int field_index, int value) [inline], [private]
Definition at line 413 of file swiss-name-dictionary-inl.h.
                                                                      {
  // See the STATIC_ASSERTs on |kMax1ByteMetaTableCapacity| and
  // |kMax2ByteMetaTableCapacity| in the .cc file for an explanation of these
  // constants.
  int capacity = Capacity();
  Tagged<ByteArray> meta_table = this->meta_table();
  if (capacity <= kMax1ByteMetaTableCapacity) {
    SetMetaTableField<uint8_t>(meta_table, field_index, value);
  } else if (capacity <= kMax2ByteMetaTableCapacity) {
    SetMetaTableField<uint16_t>(meta_table, field_index, value);
  } else {
    SetMetaTableField<uint32_t>(meta_table, field_index, value);
  }
}
References Capacity(), kMax1ByteMetaTableCapacity, kMax2ByteMetaTableCapacity, and value.
Referenced by SetEntryForEnumerationIndex(), SetNumberOfDeletedElements(), and SetNumberOfElements().
SetMetaTableField() [2/2]
template<typename T >
void v8::internal::SwissNameDictionary::SetMetaTableField (Tagged< ByteArray > meta_table, int field_index, int value) [inline], [static], [private]
Definition at line 445 of file swiss-name-dictionary-inl.h.
                                                                        {
  static_assert((std::is_same_v<T, uint8_t>) || (std::is_same_v<T, uint16_t>) ||
                (std::is_same_v<T, uint32_t>));
  DCHECK_LE(value, std::numeric_limits<T>::max());
  DCHECK_LT(meta_table->begin() + field_index * sizeof(T), meta_table->end());
  T* raw_data = reinterpret_cast<T*>(meta_table->begin());
  raw_data[field_index] = value;
}
References DCHECK_LE, DCHECK_LT, and value.
SetNumberOfDeletedElements()
void v8::internal::SwissNameDictionary::SetNumberOfDeletedElements (int deleted_elements) [inline], [private]
Definition at line 66 of file swiss-name-dictionary-inl.h.
                                                                         {
  SetMetaTableField(kMetaTableDeletedElementCountFieldIndex, deleted_elements);
}
References kMetaTableDeletedElementCountFieldIndex, and SetMetaTableField().
Referenced by Initialize().
SetNumberOfElements()
void v8::internal::SwissNameDictionary::SetNumberOfElements (int elements) [inline], [private]
Definition at line 62 of file swiss-name-dictionary-inl.h.
                                                          {
  SetMetaTableField(kMetaTableElementCountFieldIndex, elements);
}
References kMetaTableElementCountFieldIndex, and SetMetaTableField().
Referenced by Initialize(), and Rehash().
ShallowCopy()
DirectHandle< SwissNameDictionary > v8::internal::SwissNameDictionary::ShallowCopy (Isolate * isolate, DirectHandle< SwissNameDictionary > table) [static]
Definition at line 118 of file swiss-name-dictionary.cc.
                                                               {
  // TODO(v8:11388) Consider doing some cleanup during copying: For example, we
  // could turn kDeleted into kEmpty in certain situations. But this would
  // require tidying up the enumeration table in a similar fashion as would be
  // required when trying to reuse deleted entries.
  if (table->Capacity() == 0) {
    return table;
  }
  int capacity = table->Capacity();
  int used_capacity = table->UsedCapacity();
  DirectHandle<SwissNameDictionary> new_table =
      isolate->factory()->NewSwissNameDictionaryWithCapacity(
          capacity, HeapLayout::InYoungGeneration(*table)
                        ? AllocationType::kYoung
                        : AllocationType::kOld);
  new_table->SetHash(table->Hash());
  DisallowGarbageCollection no_gc;
  WriteBarrierMode mode = new_table->GetWriteBarrierMode(no_gc);
  if (mode == WriteBarrierMode::SKIP_WRITE_BARRIER) {
    // Copy data table and ctrl table, which are stored next to each other.
    void* original_start =
        reinterpret_cast<void*>(table->field_address(DataTableStartOffset()));
    void* new_table_start = reinterpret_cast<void*>(
        new_table->field_address(DataTableStartOffset()));
    size_t bytes_to_copy = DataTableSize(capacity) + CtrlTableSize(capacity);
    DCHECK(DataTableEndOffset(capacity) == CtrlTableStartOffset(capacity));
    MemCopy(new_table_start, original_start, bytes_to_copy);
  } else {
    DCHECK_EQ(UPDATE_WRITE_BARRIER, mode);
    // We may have to trigger write barriers when copying the data table.
    for (int i = 0; i < capacity; ++i) {
      Tagged<Object> key = table->KeyAt(i);
      Tagged<Object> value = table->ValueAtRaw(i);
      // Cannot use SetKey/ValueAtPut because they don't accept the hole as data
      // to store.
      new_table->StoreToDataTable(i, kDataTableKeyEntryIndex, key);
      new_table->StoreToDataTable(i, kDataTableValueEntryIndex, value);
    }
    void* original_ctrl_table = table->CtrlTable();
    void* new_ctrl_table = new_table->CtrlTable();
    MemCopy(new_ctrl_table, original_ctrl_table, CtrlTableSize(capacity));
  }
  // PropertyDetails table may contain uninitialized data for unused slots.
  for (int i = 0; i < capacity; ++i) {
    if (IsFull(table->GetCtrl(i))) {
      new_table->DetailsAtPut(i, table->DetailsAt(i));
    }
  }
  // Meta table is only initialized for the first 2 + UsedCapacity() entries,
  // where size of each entry depends on table capacity.
  int size_per_meta_table_entry = MetaTableSizePerEntryFor(capacity);
  int meta_table_used_bytes = (2 + used_capacity) * size_per_meta_table_entry;
  MemCopy(new_table->meta_table()->begin(), table->meta_table()->begin(),
          meta_table_used_bytes);
  return new_table;
}
References CtrlTableSize(), CtrlTableStartOffset(), DataTableEndOffset(), DataTableSize(), DataTableStartOffset(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::HeapLayout::InYoungGeneration(), IsFull(), kDataTableKeyEntryIndex, kDataTableValueEntryIndex, key, v8::internal::kOld, v8::internal::kYoung, v8::internal::MemCopy(), MetaTableSizePerEntryFor(), mode(), v8::internal::FactoryBase< Impl >::NewSwissNameDictionaryWithCapacity(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, table, v8::internal::UPDATE_WRITE_BARRIER, and value.
Referenced by v8::internal::Factory::CopyJSObjectWithAllocationSite().
SizeFor()
constexpr int v8::internal::SwissNameDictionary::SizeFor (int capacity) [inline], [static], [constexpr]
Definition at line 94 of file swiss-name-dictionary-inl.h.
                                                       {
  DCHECK(IsValidCapacity(capacity));
  return PropertyDetailsTableStartOffset(capacity) + capacity;
}
References v8::internal::DCHECK(), IsValidCapacity(), and PropertyDetailsTableStartOffset().
Referenced by v8::internal::Factory::CreateCanonicalEmptySwissNameDictionary(), v8::internal::FactoryBase< Impl >::NewSwissNameDictionaryWithCapacity(), v8::internal::HeapObject::SizeFromMap(), and SizeOf().
SizeOf()
static int v8::internal::SwissNameDictionary::SizeOf (Tagged< Map > map, Tagged< HeapObject > obj) [inline], [static]
Definition at line 753 of file objects-body-descriptors-inl.h.
                                                                    {
    Tagged<SwissNameDictionary> table = UncheckedCast<SwissNameDictionary>(obj);
    return SwissNameDictionary::SizeFor(table->Capacity());
  }
References SizeFor().
SlowReverseLookup()
Tagged< Object > v8::internal::SwissNameDictionary::SlowReverseLookup (Isolate * isolate, Tagged< Object > value)
Definition at line 283 of file swiss-name-dictionary.cc.
                                                                            {
  ReadOnlyRoots roots(isolate);
  for (InternalIndex i : IterateEntries()) {
    Tagged<Object> k;
    if (!ToKey(roots, i, &k)) continue;
    Tagged<Object> e = this->ValueAt(i);
    if (e == value) return k;
  }
  return roots.undefined_value();
}
References IterateEntries(), ToKey(), value, and ValueAt().
StoreToDataTable()
void v8::internal::SwissNameDictionary::StoreToDataTable (int entry, int data_offset, Tagged< Object > data) [inline], [private]
Definition at line 237 of file swiss-name-dictionary-inl.h.
                                                                {
  DCHECK_LT(static_cast<unsigned>(entry), static_cast<unsigned>(Capacity()));
  int offset = DataTableStartOffset() +
               (entry * kDataTableEntryCount + data_offset) * kTaggedSize;
  RELAXED_WRITE_FIELD(*this, offset, data);
  WRITE_BARRIER(*this, offset, data);
}
References Capacity(), DataTableStartOffset(), DCHECK_LT, entry, kDataTableEntryCount, v8::internal::kTaggedSize, RELAXED_WRITE_FIELD, and WRITE_BARRIER.
Referenced by ClearDataTableEntry(), SetKey(), and ValueAtPut().
StoreToDataTableNoBarrier()
void v8::internal::SwissNameDictionary::StoreToDataTableNoBarrier (int entry, int data_offset, Tagged< Object > data) [inline], [private]
Definition at line 248 of file swiss-name-dictionary-inl.h.
                                                                         {
  DCHECK_LT(static_cast<unsigned>(entry), static_cast<unsigned>(Capacity()));
  int offset = DataTableStartOffset() +
               (entry * kDataTableEntryCount + data_offset) * kTaggedSize;
  RELAXED_WRITE_FIELD(*this, offset, data);
}
References Capacity(), DataTableStartOffset(), DCHECK_LT, entry, kDataTableEntryCount, v8::internal::kTaggedSize, and RELAXED_WRITE_FIELD.
ToKey() [1/2]
bool v8::internal::SwissNameDictionary::ToKey (ReadOnlyRoots roots, int entry, Tagged< Object > * out_key) [inline], [private]
Definition at line 498 of file swiss-name-dictionary-inl.h.
                                                         {
  Tagged<Object> k = KeyAt(entry);
  if (!IsKey(roots, k)) return false;
  *out_key = k;
  return true;
}
References entry, IsKey(), and KeyAt().
ToKey() [2/2]
bool v8::internal::SwissNameDictionary::ToKey (ReadOnlyRoots roots, InternalIndex entry, Tagged< Object > * out_key) [inline]
Definition at line 506 of file swiss-name-dictionary-inl.h.
                                                         {
  return ToKey(roots, entry.as_int(), out_key);
}
References v8::internal::InternalIndex::as_int(), and entry.
Referenced by NumberOfEnumerableProperties(), Rehash(), and SlowReverseLookup().
TryValueAt()
std::optional< Tagged< Object > > v8::internal::SwissNameDictionary::TryValueAt (InternalIndex entry) [inline]
Definition at line 313 of file swiss-name-dictionary-inl.h.
                         {
#if DEBUG
  Isolate* isolate;
  GetIsolateFromHeapObject(*this, &isolate);
  DCHECK_NE(isolate, nullptr);
  SLOW_DCHECK(!isolate->heap()->IsPendingAllocation(Tagged(*this)));
#endif // DEBUG
  // We can read Capacity() in a non-atomic way since we are reading an
  // initialized object which is not pending allocation.
  if (static_cast<unsigned>(entry.as_int()) >=
      static_cast<unsigned>(Capacity())) {
    return {};
  }
  return ValueAtRaw(entry.as_int());
}
References v8::internal::InternalIndex::as_int(), Capacity(), DCHECK_NE, entry, v8::internal::GetIsolateFromHeapObject(), v8::internal::Isolate::heap(), v8::internal::Heap::IsPendingAllocation(), SLOW_DCHECK, and ValueAtRaw().
UsedCapacity()
int v8::internal::SwissNameDictionary::UsedCapacity () [inline]
Definition at line 70 of file swiss-name-dictionary-inl.h.
                                      {
  return NumberOfElements() + NumberOfDeletedElements();
}
References NumberOfDeletedElements(), and NumberOfElements().
Referenced by AddInternal(), EntryForEnumerationIndex(), EqualsForTesting(), Rehash(), and SetEntryForEnumerationIndex().
ValueAt()
Tagged< Object > v8::internal::SwissNameDictionary::ValueAt (InternalIndex entry) [inline]
Definition at line 308 of file swiss-name-dictionary-inl.h.
                                                               {
  DCHECK(IsFull(GetCtrl(entry.as_int())));
  return ValueAtRaw(entry.as_int());
}
References v8::internal::InternalIndex::as_int(), v8::internal::DCHECK(), entry, GetCtrl(), IsFull(), and ValueAtRaw().
Referenced by SlowReverseLookup().
ValueAtPut() [1/2]
void v8::internal::SwissNameDictionary::ValueAtPut (int entry, Tagged< Object > value) [inline], [private]
Definition at line 265 of file swiss-name-dictionary-inl.h.
                                                                    {
  DCHECK(!IsTheHole(value));
  StoreToDataTable(entry, kDataTableValueEntryIndex, value);
}
References v8::internal::DCHECK(), entry, kDataTableValueEntryIndex, StoreToDataTable(), and value.
ValueAtPut() [2/2]
void v8::internal::SwissNameDictionary::ValueAtPut (InternalIndex entry, Tagged< Object > value) [inline]
Definition at line 270 of file swiss-name-dictionary-inl.h.
                                                           {
  ValueAtPut(entry.as_int(), value);
}
References v8::internal::InternalIndex::as_int(), entry, and value.
Referenced by AddInternal().
ValueAtRaw()
Tagged< Object > v8::internal::SwissNameDictionary::ValueAtRaw (int entry) [inline], [private]
Definition at line 304 of file swiss-name-dictionary-inl.h.
                                                        {
  return LoadFromDataTable(entry, kDataTableValueEntryIndex);
}
References entry, kDataTableValueEntryIndex, and LoadFromDataTable().
Referenced by EqualsForTesting(), Rehash(), TryValueAt(), and ValueAt().
Member Data Documentation
details
HandleType<SwissNameDictionary> DirectHandle<Name> DirectHandle<Object> PropertyDetails v8::internal::SwissNameDictionary::details
Definition at line 81 of file swiss-name-dictionary.h.
Referenced by AddInternal(), DetailsAtPut(), NumberOfEnumerableProperties(), and Rehash().
entry
HandleType<SwissNameDictionary> InternalIndex v8::internal::SwissNameDictionary::entry
Definition at line 94 of file swiss-name-dictionary.h.
Referenced by ClearDataTableEntry(), DetailsAt(), DetailsAtPut(), GetCtrl(), KeyAt(), LoadFromDataTable(), NameAt(), Rehash(), SetCtrl(), SetEntryForEnumerationIndex(), SetKey(), StoreToDataTable(), StoreToDataTableNoBarrier(), ToKey(), TryValueAt(), ValueAt(), ValueAtPut(), and ValueAtRaw().
entry_out
HandleType<SwissNameDictionary> DirectHandle<Name> DirectHandle<Object> PropertyDetails InternalIndex* v8::internal::SwissNameDictionary::entry_out = nullptr)
Definition at line 81 of file swiss-name-dictionary.h.
kDataTableEntryCount
constexpr int v8::internal::SwissNameDictionary::kDataTableEntryCount = 2 [static], [constexpr]
Definition at line 237 of file swiss-name-dictionary.h.
Referenced by v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), DataTableSize(), Initialize(), LoadFromDataTable(), MaxCapacity(), StoreToDataTable(), StoreToDataTableNoBarrier(), v8::internal::CodeStubAssembler::SwissNameDictionaryOffsetIntoDataTableMT(), and v8::internal::CodeStubAssembler::SwissNameDictionaryOffsetIntoPropertyDetailsTableMT().
kDataTableKeyEntryIndex
constexpr int v8::internal::SwissNameDictionary::kDataTableKeyEntryIndex = 0 [static], [constexpr]
Definition at line 238 of file swiss-name-dictionary.h.
Referenced by ClearDataTableEntry(), KeyAt(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryKey(), SetKey(), ShallowCopy(), and v8::internal::CodeStubAssembler::StoreSwissNameDictionaryKeyAndValue().
kDataTableValueEntryIndex
constexpr int v8::internal::SwissNameDictionary::kDataTableValueEntryIndex = kDataTableKeyEntryIndex + 1 [static], [constexpr]
Definition at line 239 of file swiss-name-dictionary.h.
Referenced by ClearDataTableEntry(), v8::internal::CodeStubAssembler::LoadValueByKeyIndex(), ShallowCopy(), v8::internal::CodeStubAssembler::StoreSwissNameDictionaryKeyAndValue(), v8::internal::CodeStubAssembler::StoreValueByKeyIndex(), ValueAtPut(), and ValueAtRaw().
key
HandleType<SwissNameDictionary> DirectHandle<Name> v8::internal::SwissNameDictionary::key
Definition at line 80 of file swiss-name-dictionary.h.
Referenced by AddInternal(), FindEntry(), Rehash(), SetKey(), and ShallowCopy().
kGroupWidth
constexpr int v8::internal::SwissNameDictionary::kGroupWidth = Group::kWidth [static], [constexpr]
Definition at line 226 of file swiss-name-dictionary.h.
Referenced by v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), CapacityFor(), v8::internal::CodeStubAssembler::CopySwissNameDictionary(), CtrlTableSize(), EqualsForTesting(), v8::internal::CodeStubAssembler::SwissNameDictionaryOffsetIntoPropertyDetailsTableMT(), and v8::internal::CodeStubAssembler::SwissNameDictionarySetCtrl().
kInitialCapacity
constexpr int v8::internal::SwissNameDictionary::kInitialCapacity = kSwissNameDictionaryInitialCapacity [static], [constexpr]
Definition at line 233 of file swiss-name-dictionary.h.
Referenced by v8::internal::CodeStubAssembler::AllocateSwissNameDictionary(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), and IsValidCapacity().
kIsOrderedDictionaryType
constexpr bool v8::internal::SwissNameDictionary::kIsOrderedDictionaryType = true [static], [constexpr]
Definition at line 220 of file swiss-name-dictionary.h.
kMax1ByteMetaTableCapacity
constexpr int v8::internal::SwissNameDictionary::kMax1ByteMetaTableCapacity = (1 << 8) [static], [constexpr]
Definition at line 255 of file swiss-name-dictionary.h.
Referenced by v8::internal::anonymous_namespace{code-stub-assembler.cc}::GenerateMetaTableAccess(), GetMetaTableField(), MetaTableSizePerEntryFor(), and SetMetaTableField().
kMax2ByteMetaTableCapacity
constexpr int v8::internal::SwissNameDictionary::kMax2ByteMetaTableCapacity = (1 << 16) [static], [constexpr]
Definition at line 258 of file swiss-name-dictionary.h.
Referenced by v8::internal::anonymous_namespace{code-stub-assembler.cc}::GenerateMetaTableAccess(), GetMetaTableField(), MetaTableSizePerEntryFor(), and SetMetaTableField().
kMetaTableDeletedElementCountFieldIndex
constexpr int v8::internal::SwissNameDictionary::kMetaTableDeletedElementCountFieldIndex = 1 [static], [constexpr]
Definition at line 248 of file swiss-name-dictionary.h.
Referenced by v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryNumberOfDeletedElements(), NumberOfDeletedElements(), SetNumberOfDeletedElements(), v8::internal::CodeStubAssembler::SwissNameDictionaryIncreaseElementCountOrBailout(), and v8::internal::CodeStubAssembler::SwissNameDictionaryUpdateCountsForDeletion().
kMetaTableElementCountFieldIndex
constexpr int v8::internal::SwissNameDictionary::kMetaTableElementCountFieldIndex = 0 [static], [constexpr]
Definition at line 247 of file swiss-name-dictionary.h.
Referenced by v8::internal::CodeStubAssembler::AllocateSwissNameDictionaryWithCapacity(), v8::internal::CodeStubAssembler::LoadSwissNameDictionaryNumberOfElements(), NumberOfElements(), SetNumberOfElements(), v8::internal::CodeStubAssembler::SwissNameDictionaryIncreaseElementCountOrBailout(), and v8::internal::CodeStubAssembler::SwissNameDictionaryUpdateCountsForDeletion().
kMetaTableEnumerationDataStartIndex
constexpr int v8::internal::SwissNameDictionary::kMetaTableEnumerationDataStartIndex = 2 [static], [constexpr]
Definition at line 251 of file swiss-name-dictionary.h.
Referenced by v8::internal::Factory::CreateCanonicalEmptySwissNameDictionary(), EntryForEnumerationIndex(), SetEntryForEnumerationIndex(), and v8::internal::CodeStubAssembler::StoreSwissNameDictionaryEnumToEntryMapping().
kNotFoundSentinel
constexpr int v8::internal::SwissNameDictionary::kNotFoundSentinel = -1 [static], [constexpr]
Definition at line 224 of file swiss-name-dictionary.h.
Referenced by v8::internal::RUNTIME_FUNCTION().
kUseSIMD
const bool v8::internal::SwissNameDictionary::kUseSIMD = kGroupWidth == 16 [static]
Definition at line 227 of file swiss-name-dictionary.h.
Referenced by v8::internal::CodeStubAssembler::SwissNameDictionaryAdd(), and v8::internal::CodeStubAssembler::SwissNameDictionaryFindEntry().
new_capacity
HandleType<SwissNameDictionary> int v8::internal::SwissNameDictionary::new_capacity
Definition at line 151 of file swiss-name-dictionary.h.
table
HandleType< SwissNameDictionary > v8::internal::SwissNameDictionary::table
Definition at line 79 of file swiss-name-dictionary.h.
Referenced by ShallowCopy().
value
HandleType<SwissNameDictionary> DirectHandle<Name> DirectHandle<Object> v8::internal::SwissNameDictionary::value
Definition at line 80 of file swiss-name-dictionary.h.
Referenced by AddInternal(), Rehash(), SetMetaTableField(), ShallowCopy(), SlowReverseLookup(), and ValueAtPut().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h
/mnt/V8SourceCode/src/objects/swiss-name-dictionary.h
/mnt/V8SourceCode/src/objects/swiss-name-dictionary-inl.h
/mnt/V8SourceCode/src/objects/swiss-name-dictionary.cc