v8::internal::compiler::SharedFunctionInfoRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< SharedFunctionInfo > object () const
Builtin builtin_id () const
int context_header_size () const
int context_parameters_start () const
BytecodeArrayRef GetBytecodeArray (JSHeapBroker *broker) const
bool HasBreakInfo (JSHeapBroker *broker) const
SharedFunctionInfo::Inlineability GetInlineability (CodeKind code_kind, JSHeapBroker *broker) const
OptionalFunctionTemplateInfoRef function_template_info (JSHeapBroker *broker) const
ScopeInfoRef scope_info (JSHeapBroker *broker) const
int internal_formal_parameter_count_with_receiver_deprecated () const
int internal_formal_parameter_count_without_receiver_deprecated () const
bool IsInlineable (CodeKind code_kind, JSHeapBroker *broker) const
Detailed Description
Definition at line 1149 of file heap-refs.h.
Member Function Documentation
builtin_id()
Builtin v8::internal::compiler::SharedFunctionInfoRef::builtin_id () const
Referenced by v8::internal::compiler::JSCallReducer::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure(), v8::internal::maglev::MaglevGraphBuilder::TryBuildFastInstanceOf(), v8::internal::maglev::MaglevGraphBuilder::TryReduceBuiltin(), v8::internal::maglev::MaglevGraphBuilder::TryReduceConstructBuiltin(), and v8::internal::compiler::JSCallReducer::TryReduceJSCallMathMinMaxWithArrayLike().
context_header_size()
int v8::internal::compiler::SharedFunctionInfoRef::context_header_size () const
Definition at line 2466 of file heap-refs.cc.
                                                     {
  return object()->scope_info()->ContextHeaderLength();
}
References object().
context_parameters_start()
int v8::internal::compiler::SharedFunctionInfoRef::context_parameters_start () const
Definition at line 2470 of file heap-refs.cc.
                                                          {
  return object()->scope_info()->ParametersStartIndex();
}
References object().
Referenced by v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments().
function_template_info()
OptionalFunctionTemplateInfoRef v8::internal::compiler::SharedFunctionInfoRef::function_template_info (JSHeapBroker * broker) const
Definition at line 2460 of file heap-refs.cc.
                                {
  if (!object()->IsApiFunction()) return {};
  return TryMakeRef(broker, object()->api_func_data());
}
References broker(), and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildCallKnownApiFunction().
GetBytecodeArray()
BytecodeArrayRef v8::internal::compiler::SharedFunctionInfoRef::GetBytecodeArray (JSHeapBroker * broker) const
Definition at line 1752 of file heap-refs.cc.
                                {
  CHECK(HasBytecodeArray());
  Tagged<BytecodeArray> bytecode_array;
  if (!broker->IsMainThread()) {
    bytecode_array = object()->GetBytecodeArray(broker->local_isolate());
  } else {
    bytecode_array = object()->GetBytecodeArray(broker->isolate());
  }
  return MakeRefAssumeMemoryFence(broker, bytecode_array);
}
References broker(), CHECK, and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::maglev::MaglevInliner::BuildInlineFunction(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CanConsiderForInlining(), v8::internal::maglev::MaglevGraphBuilder::CanInlineCall(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::maglev::MaglevGraphBuilder::ShouldEagerInlineCall(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildAndAllocateJSGeneratorObject().
GetInlineability()
SharedFunctionInfo::Inlineability v8::internal::compiler::SharedFunctionInfoRef::GetInlineability (CodeKind code_kind, JSHeapBroker * broker) const
Definition at line 1780 of file heap-refs.cc.
                                                    {
  return broker->IsMainThread()
             ? object()->GetInlineability(code_kind, broker->isolate())
             : object()->GetInlineability(code_kind, broker->local_isolate());
}
References broker(), and object().
Referenced by v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CanConsiderForInlining(), v8::internal::maglev::MaglevGraphBuilder::CanInlineCall(), and v8::internal::compiler::JSInliningHeuristic::Reduce().
HasBreakInfo()
bool v8::internal::compiler::SharedFunctionInfoRef::HasBreakInfo (JSHeapBroker * broker) const
Definition at line 1769 of file heap-refs.cc.
                                                                   {
  if (broker->IsMainThread()) {
    return object()->HasBreakInfo(broker->isolate());
  } else {
    LocalIsolate* local_isolate = broker->local_isolate();
    MutexGuardIfOffThread<LocalIsolate> mutex_guard(
        local_isolate->shared_function_info_access(), local_isolate);
    return object()->HasBreakInfo(local_isolate->GetMainThreadIsolateUnsafe());
  }
}
References broker(), v8::internal::LocalIsolate::GetMainThreadIsolateUnsafe(), object(), and v8::internal::LocalIsolate::shared_function_info_access().
Referenced by v8::internal::compiler::JSCallReducer::ReduceJSCall(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::maglev::MaglevGraphBuilder::TryReduceCallForConstant(), and v8::internal::maglev::MaglevGraphBuilder::TryReduceConstruct().
internal_formal_parameter_count_with_receiver_deprecated()
int v8::internal::compiler::SharedFunctionInfoRef::internal_formal_parameter_count_with_receiver_deprecated () const
Definition at line 2478 of file heap-refs.cc.
                                                                     {
  return object()->internal_formal_parameter_count_with_receiver();
}
References object().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCallSelf(), and v8::internal::maglev::MaglevCompilationUnit::MaglevCompilationUnit().
internal_formal_parameter_count_without_receiver_deprecated()
int v8::internal::compiler::SharedFunctionInfoRef::internal_formal_parameter_count_without_receiver_deprecated () const
Definition at line 2483 of file heap-refs.cc.
                                                                        {
  return object()->internal_formal_parameter_count_without_receiver();
}
References object().
Referenced by v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::PromiseConstructorFrameState(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), and v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments().
IsInlineable()
bool v8::internal::compiler::SharedFunctionInfoRef::IsInlineable (CodeKind code_kind, JSHeapBroker * broker) const [inline]
Definition at line 1177 of file heap-refs.h.
                                                                    {
    return GetInlineability(code_kind, broker) ==
           SharedFunctionInfo::kIsInlineable;
  }
References broker(), and v8::internal::SharedFunctionInfo::kIsInlineable.
Referenced by v8::internal::compiler::JSInliningHeuristic::Reduce().
object()
IndirectHandle<SharedFunctionInfo> v8::internal::compiler::SharedFunctionInfoRef::object () const
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlineFunction(), v8::internal::maglev::MaglevCompiler::Compile(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfo(), context_header_size(), context_parameters_start(), v8::internal::compiler::JSInliner::CreateArtificialFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateConstructInvokeStubFrameState(), v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::maglev::MaglevCompiler::GenerateCode(), v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), GetInlineability(), HasBreakInfo(), internal_formal_parameter_count_with_receiver_deprecated(), internal_formal_parameter_count_without_receiver_deprecated(), v8::internal::maglev::FastCreateClosure::PrintParams(), v8::internal::maglev::CreateClosure::PrintParams(), v8::internal::maglev::CallKnownJSFunction::PrintParams(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), v8::internal::compiler::JSInliningHeuristic::Reduce(), v8::internal::compiler::JSCallReducer::ReduceJSCall(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
scope_info()
ScopeInfoRef v8::internal::compiler::SharedFunctionInfoRef::scope_info (JSHeapBroker * broker) const
Definition at line 2474 of file heap-refs.cc.
                                                                         {
  return MakeRefAssumeMemoryFence(broker, object()->scope_info(kAcquireLoad));
}
References broker(), v8::kAcquireLoad, and v8::internal::compiler::MakeRefAssumeMemoryFence().
Referenced by v8::internal::maglev::MaglevGraphBuilder::Build().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc