v8::internal::compiler::SparseInputMask Class Reference
#include <common-operator.h>
Classes
class InputIterator
Public Types
using BitMaskType = uint32_t
Public Member Functions
SparseInputMask (BitMaskType bit_mask)
BitMaskType mask () const
bool IsDense () const
int CountReal () const
InputIterator IterateOverInputs (Node *node)
Static Public Member Functions
static SparseInputMask Dense ()
Static Public Attributes
static const BitMaskType kDenseBitMask = 0x0
static const BitMaskType kEndMarker = 0x1
static const BitMaskType kEntryMask = 0x1
static const int kMaxSparseInputs = (sizeof(BitMaskType) * kBitsPerByte - 1)
Private Attributes
BitMaskType bit_mask_
Detailed Description
Definition at line 278 of file common-operator.h.
Member Typedef Documentation
BitMaskType
using v8::internal::compiler::SparseInputMask::BitMaskType = uint32_t
Definition at line 280 of file common-operator.h.
Constructor & Destructor Documentation
SparseInputMask()
v8::internal::compiler::SparseInputMask::SparseInputMask (BitMaskType bit_mask) [inline], [explicit]
Definition at line 336 of file common-operator.h.
: bit_mask_(bit_mask) {}
Referenced by Dense().
Member Function Documentation
CountReal()
int v8::internal::compiler::SparseInputMask::CountReal () const
Definition at line 316 of file common-operator.cc.
                                     {
  DCHECK(!IsDense());
  return base::bits::CountPopulation(bit_mask_) -
         base::bits::CountPopulation(kEndMarker);
}
References bit_mask_, v8::base::bits::CountPopulation(), v8::internal::DCHECK(), IsDense(), and kEndMarker.
Referenced by IterateOverInputs(), v8::internal::compiler::CommonOperatorBuilder::StateValues(), and v8::internal::compiler::CommonOperatorBuilder::TypedStateValues().
Dense()
static SparseInputMask v8::internal::compiler::SparseInputMask::Dense () [inline], [static]
Definition at line 339 of file common-operator.h.
{ return SparseInputMask(kDenseBitMask); }
References kDenseBitMask, and SparseInputMask().
Referenced by v8::internal::compiler::JSInliner::CreateArtificialFrameState(), v8::internal::compiler::anonymous_namespace{frame-states.cc}::CreateBuiltinContinuationFrameStateCommon(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateConstructInvokeStubFrameState(), v8::internal::compiler::StateValuesCache::GetEmptyStateValues(), v8::internal::compiler::BytecodeGraphBuilder::Environment::UpdateStateValues(), and v8::internal::compiler::RepresentationSelector::VisitFrameState().
IsDense()
bool v8::internal::compiler::SparseInputMask::IsDense () const [inline]
Definition at line 343 of file common-operator.h.
{ return bit_mask_ == SparseInputMask::kDenseBitMask; }
References bit_mask_, and kDenseBitMask.
Referenced by CountReal(), IterateOverInputs(), v8::internal::compiler::operator<<(), v8::internal::compiler::CommonOperatorBuilder::StateValues(), and v8::internal::compiler::CommonOperatorBuilder::TypedStateValues().
IterateOverInputs()
SparseInputMask::InputIterator v8::internal::compiler::SparseInputMask::IterateOverInputs (Node * node)
Definition at line 322 of file common-operator.cc.
                                                                          {
  DCHECK(IsDense() || CountReal() == node->InputCount());
  return InputIterator(bit_mask_, node);
}
References bit_mask_, CountReal(), v8::internal::DCHECK(), v8::internal::compiler::Node::InputCount(), and IsDense().
Referenced by v8::internal::compiler::StateValuesAccess::iterator::iterator(), v8::internal::compiler::StateValuesAccess::iterator::Push(), and v8::internal::compiler::StateValuesAccess::size().
mask()
BitMaskType v8::internal::compiler::SparseInputMask::mask () const [inline]
Definition at line 341 of file common-operator.h.
{ return bit_mask_; }
References bit_mask_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
Member Data Documentation
bit_mask_
BitMaskType v8::internal::compiler::SparseInputMask::bit_mask_ [private]
Definition at line 368 of file common-operator.h.
Referenced by v8::internal::compiler::SparseInputMask::InputIterator::Advance(), v8::internal::compiler::SparseInputMask::InputIterator::AdvanceToNextRealOrEnd(), CountReal(), IsDense(), v8::internal::compiler::SparseInputMask::InputIterator::IsEnd(), v8::internal::compiler::SparseInputMask::InputIterator::IsReal(), IterateOverInputs(), and mask().
kDenseBitMask
const BitMaskType v8::internal::compiler::SparseInputMask::kDenseBitMask = 0x0 [static]
Definition at line 283 of file common-operator.h.
Referenced by v8::internal::compiler::SparseInputMask::InputIterator::AdvanceToNextRealOrEnd(), v8::internal::compiler::StateValuesCache::BuildTree(), Dense(), v8::internal::compiler::SparseInputMask::InputIterator::InputIterator(), IsDense(), v8::internal::compiler::SparseInputMask::InputIterator::IsEnd(), v8::internal::compiler::SparseInputMask::InputIterator::IsReal(), and v8::internal::compiler::operator<<().
kEndMarker
const BitMaskType v8::internal::compiler::SparseInputMask::kEndMarker = 0x1 [static]
Definition at line 285 of file common-operator.h.
Referenced by CountReal(), v8::internal::compiler::StateValuesCache::FillBufferWithValues(), v8::internal::compiler::SparseInputMask::InputIterator::InputIterator(), v8::internal::compiler::SparseInputMask::InputIterator::IsEnd(), and v8::internal::compiler::operator<<().
kEntryMask
const BitMaskType v8::internal::compiler::SparseInputMask::kEntryMask = 0x1 [static]
Definition at line 287 of file common-operator.h.
Referenced by v8::internal::compiler::SparseInputMask::InputIterator::IsReal(), and v8::internal::compiler::operator<<().
kMaxSparseInputs
const int v8::internal::compiler::SparseInputMask::kMaxSparseInputs = (sizeof(BitMaskType) * kBitsPerByte - 1) [static]
Definition at line 290 of file common-operator.h.
Referenced by v8::internal::compiler::StateValuesCache::FillBufferWithValues().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/common-operator.h
/mnt/V8SourceCode/src/compiler/common-operator.cc