v8::internal::compiler::JSSpeculativeBinopBuilder Class Reference
Public Member Functions
JSSpeculativeBinopBuilder (const JSTypeHintLowering *lowering, const Operator *op, Node *left, Node *right, Node *effect, Node *control, FeedbackSlot slot)
bool GetBinaryNumberOperationHint (NumberOperationHint *hint)
bool GetBinaryBigIntOperationHint (BigIntOperationHint *hint)
bool GetCompareNumberOperationHint (NumberOperationHint *hint)
bool GetCompareBigIntOperationHint (BigIntOperationHint *hint)
const Operator * SpeculativeNumberOp (NumberOperationHint hint)
const Operator * SpeculativeBigIntOp (BigIntOperationHint hint)
const Operator * SpeculativeNumberCompareOp (NumberOperationHint hint)
const Operator * SpeculativeBigIntCompareOp (BigIntOperationHint hint)
Node * BuildSpeculativeOperation (const Operator *op)
Node * TryBuildNumberBinop ()
Node * TryBuildBigIntBinop ()
Node * TryBuildNumberCompare ()
Node * TryBuildBigIntCompare ()
JSGraph * jsgraph () const
Isolate * isolate () const
TFGraph * graph () const
JSOperatorBuilder * javascript ()
SimplifiedOperatorBuilder * simplified ()
CommonOperatorBuilder * common ()
Private Member Functions
BinaryOperationHint GetBinaryOperationHint ()
CompareOperationHint GetCompareOperationHint ()
Private Attributes
JSTypeHintLowering const *const lowering_
Operator const *const op_
Node * left_
Node * right_
Node *const effect_
Node *const control_
FeedbackSlot const slot_
Detailed Description
Definition at line 75 of file js-type-hint-lowering.cc.
Constructor & Destructor Documentation
JSSpeculativeBinopBuilder()
v8::internal::compiler::JSSpeculativeBinopBuilder::JSSpeculativeBinopBuilder (const JSTypeHintLowering * lowering, const Operator * op, Node * left, Node * right, Node * effect, Node * control, FeedbackSlot slot) [inline]
Definition at line 77 of file js-type-hint-lowering.cc.
      : lowering_(lowering),
        op_(op),
        left_(left),
        right_(right),
        effect_(effect),
        control_(control),
        slot_(slot) {}
Member Function Documentation
BuildSpeculativeOperation()
Node* v8::internal::compiler::JSSpeculativeBinopBuilder::BuildSpeculativeOperation (const Operator * op) [inline]
Definition at line 263 of file js-type-hint-lowering.cc.
                                                      {
    DCHECK_EQ(2, op->ValueInputCount());
    DCHECK_EQ(1, op->EffectInputCount());
    DCHECK_EQ(1, op->ControlInputCount());
    DCHECK_EQ(false, OperatorProperties::HasFrameStateInput(op));
    DCHECK_EQ(false, OperatorProperties::HasContextInput(op));
    DCHECK_EQ(1, op->EffectOutputCount());
    DCHECK_EQ(0, op->ControlOutputCount());
    return graph()->NewNode(op, left_, right_, effect_, control_);
  }
References control_, v8::internal::compiler::Operator::ControlInputCount(), v8::internal::compiler::Operator::ControlOutputCount(), DCHECK_EQ, effect_, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::EffectOutputCount(), graph(), v8::internal::compiler::OperatorProperties::HasContextInput(), v8::internal::compiler::OperatorProperties::HasFrameStateInput(), left_, v8::internal::compiler::TFGraph::NewNode(), right_, and v8::internal::compiler::Operator::ValueInputCount().
Referenced by TryBuildBigIntBinop(), TryBuildBigIntCompare(), TryBuildNumberBinop(), and TryBuildNumberCompare().
common()
CommonOperatorBuilder* v8::internal::compiler::JSSpeculativeBinopBuilder::common () [inline]
Definition at line 324 of file js-type-hint-lowering.cc.
{ return jsgraph()->common(); }
References v8::internal::compiler::MachineGraph::common(), and jsgraph().
GetBinaryBigIntOperationHint()
bool v8::internal::compiler::JSSpeculativeBinopBuilder::GetBinaryBigIntOperationHint (BigIntOperationHint * hint) [inline]
Definition at line 93 of file js-type-hint-lowering.cc.
                                                               {
    return BinaryOperationHintToBigIntOperationHint(GetBinaryOperationHint(),
                                                    hint);
  }
References v8::internal::compiler::anonymous_namespace{js-type-hint-lowering.cc}::BinaryOperationHintToBigIntOperationHint(), and GetBinaryOperationHint().
Referenced by TryBuildBigIntBinop().
GetBinaryNumberOperationHint()
bool v8::internal::compiler::JSSpeculativeBinopBuilder::GetBinaryNumberOperationHint (NumberOperationHint * hint) [inline]
Definition at line 88 of file js-type-hint-lowering.cc.
                                                               {
    return BinaryOperationHintToNumberOperationHint(GetBinaryOperationHint(),
                                                    hint);
  }
References v8::internal::compiler::anonymous_namespace{js-type-hint-lowering.cc}::BinaryOperationHintToNumberOperationHint(), and GetBinaryOperationHint().
Referenced by TryBuildNumberBinop().
GetBinaryOperationHint()
BinaryOperationHint v8::internal::compiler::JSSpeculativeBinopBuilder::GetBinaryOperationHint () [inline], [private]
Definition at line 327 of file js-type-hint-lowering.cc.
                                               {
    return lowering_->GetBinaryOperationHint(slot_);
  }
References v8::internal::compiler::JSTypeHintLowering::GetBinaryOperationHint(), lowering_, and slot_.
Referenced by GetBinaryBigIntOperationHint(), and GetBinaryNumberOperationHint().
GetCompareBigIntOperationHint()
bool v8::internal::compiler::JSSpeculativeBinopBuilder::GetCompareBigIntOperationHint (BigIntOperationHint * hint) [inline]
Definition at line 127 of file js-type-hint-lowering.cc.
                                                                {
    switch (GetCompareOperationHint()) {
      case CompareOperationHint::kSignedSmall:
      case CompareOperationHint::kNumber:
      case CompareOperationHint::kNumberOrBoolean:
      case CompareOperationHint::kNumberOrOddball:
      case CompareOperationHint::kAny:
      case CompareOperationHint::kNone:
      case CompareOperationHint::kString:
      case CompareOperationHint::kSymbol:
      case CompareOperationHint::kReceiver:
      case CompareOperationHint::kReceiverOrNullOrUndefined:
      case CompareOperationHint::kStringOrOddball:
      case CompareOperationHint::kInternalizedString:
        return false;
      case CompareOperationHint::kBigInt:
        *hint = BigIntOperationHint::kBigInt;
        return true;
      case CompareOperationHint::kBigInt64:
        *hint = BigIntOperationHint::kBigInt64;
        return true;
    }
  }
References GetCompareOperationHint(), v8::internal::kAny, v8::internal::compiler::kBigInt, v8::internal::kBigInt, v8::internal::compiler::kBigInt64, v8::internal::kBigInt64, v8::internal::kInternalizedString, v8::internal::kNone, v8::internal::kNumber, v8::internal::kNumberOrBoolean, v8::internal::kNumberOrOddball, v8::internal::kReceiver, v8::internal::kReceiverOrNullOrUndefined, v8::internal::kSignedSmall, v8::internal::kString, v8::internal::kStringOrOddball, and v8::internal::kSymbol.
Referenced by TryBuildBigIntCompare().
GetCompareNumberOperationHint()
bool v8::internal::compiler::JSSpeculativeBinopBuilder::GetCompareNumberOperationHint (NumberOperationHint * hint) [inline]
Definition at line 98 of file js-type-hint-lowering.cc.
                                                                {
    switch (GetCompareOperationHint()) {
      case CompareOperationHint::kSignedSmall:
        *hint = NumberOperationHint::kSignedSmall;
        return true;
      case CompareOperationHint::kNumber:
        *hint = NumberOperationHint::kNumber;
        return true;
      case CompareOperationHint::kNumberOrBoolean:
        *hint = NumberOperationHint::kNumberOrBoolean;
        return true;
      case CompareOperationHint::kNumberOrOddball:
        *hint = NumberOperationHint::kNumberOrOddball;
        return true;
      case CompareOperationHint::kAny:
      case CompareOperationHint::kNone:
      case CompareOperationHint::kString:
      case CompareOperationHint::kSymbol:
      case CompareOperationHint::kBigInt:
      case CompareOperationHint::kBigInt64:
      case CompareOperationHint::kReceiver:
      case CompareOperationHint::kReceiverOrNullOrUndefined:
      case CompareOperationHint::kStringOrOddball:
      case CompareOperationHint::kInternalizedString:
        break;
    }
    return false;
  }
References GetCompareOperationHint(), v8::internal::kAny, v8::internal::kBigInt, v8::internal::kBigInt64, v8::internal::kInternalizedString, v8::internal::kNone, v8::internal::compiler::kNumber, v8::internal::kNumber, v8::internal::compiler::kNumberOrBoolean, v8::internal::kNumberOrBoolean, v8::internal::compiler::kNumberOrOddball, v8::internal::kNumberOrOddball, v8::internal::kReceiver, v8::internal::kReceiverOrNullOrUndefined, v8::internal::compiler::kSignedSmall, v8::internal::kSignedSmall, v8::internal::kString, v8::internal::kStringOrOddball, and v8::internal::kSymbol.
Referenced by TryBuildNumberCompare().
GetCompareOperationHint()
CompareOperationHint v8::internal::compiler::JSSpeculativeBinopBuilder::GetCompareOperationHint () [inline], [private]
Definition at line 331 of file js-type-hint-lowering.cc.
                                                 {
    return lowering_->GetCompareOperationHint(slot_);
  }
References v8::internal::compiler::JSTypeHintLowering::GetCompareOperationHint(), lowering_, and slot_.
Referenced by GetCompareBigIntOperationHint(), and GetCompareNumberOperationHint().
graph()
TFGraph* v8::internal::compiler::JSSpeculativeBinopBuilder::graph () const [inline]
Definition at line 321 of file js-type-hint-lowering.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by BuildSpeculativeOperation().
isolate()
Isolate* v8::internal::compiler::JSSpeculativeBinopBuilder::isolate () const [inline]
Definition at line 320 of file js-type-hint-lowering.cc.
{ return jsgraph()->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph().
javascript()
JSOperatorBuilder* v8::internal::compiler::JSSpeculativeBinopBuilder::javascript () [inline]
Definition at line 322 of file js-type-hint-lowering.cc.
{ return jsgraph()->javascript(); }
References v8::internal::compiler::JSGraph::javascript(), and jsgraph().
jsgraph()
JSGraph* v8::internal::compiler::JSSpeculativeBinopBuilder::jsgraph () const [inline]
Definition at line 319 of file js-type-hint-lowering.cc.
{ return lowering_->jsgraph(); }
References v8::internal::compiler::JSTypeHintLowering::jsgraph(), and lowering_.
Referenced by common(), graph(), isolate(), javascript(), and simplified().
simplified()
SimplifiedOperatorBuilder* v8::internal::compiler::JSSpeculativeBinopBuilder::simplified () [inline]
Definition at line 323 of file js-type-hint-lowering.cc.
{ return jsgraph()->simplified(); }
References jsgraph(), and v8::internal::compiler::JSGraph::simplified().
Referenced by SpeculativeBigIntCompareOp(), SpeculativeBigIntOp(), SpeculativeNumberCompareOp(), and SpeculativeNumberOp().
SpeculativeBigIntCompareOp()
const Operator* v8::internal::compiler::JSSpeculativeBinopBuilder::SpeculativeBigIntCompareOp (BigIntOperationHint hint) [inline]
Definition at line 243 of file js-type-hint-lowering.cc.
                                                                       {
    switch (op_->opcode()) {
      case IrOpcode::kJSEqual:
        return simplified()->SpeculativeBigIntEqual(hint);
      case IrOpcode::kJSLessThan:
        return simplified()->SpeculativeBigIntLessThan(hint);
      case IrOpcode::kJSGreaterThan:
        std::swap(left_, right_);
        return simplified()->SpeculativeBigIntLessThan(hint);
      case IrOpcode::kJSLessThanOrEqual:
        return simplified()->SpeculativeBigIntLessThanOrEqual(hint);
      case IrOpcode::kJSGreaterThanOrEqual:
        std::swap(left_, right_);
        return simplified()->SpeculativeBigIntLessThanOrEqual(hint);
      default:
        break;
    }
    UNREACHABLE();
  }
References left_, op_, v8::internal::compiler::Operator::opcode(), right_, simplified(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntEqual(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntLessThan(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntLessThanOrEqual(), and v8::internal::UNREACHABLE().
Referenced by TryBuildBigIntCompare().
SpeculativeBigIntOp()
const Operator* v8::internal::compiler::JSSpeculativeBinopBuilder::SpeculativeBigIntOp (BigIntOperationHint hint) [inline]
Definition at line 195 of file js-type-hint-lowering.cc.
                                                                {
    switch (op_->opcode()) {
      case IrOpcode::kJSAdd:
        return simplified()->SpeculativeBigIntAdd(hint);
      case IrOpcode::kJSSubtract:
        return simplified()->SpeculativeBigIntSubtract(hint);
      case IrOpcode::kJSMultiply:
        return simplified()->SpeculativeBigIntMultiply(hint);
      case IrOpcode::kJSDivide:
        return simplified()->SpeculativeBigIntDivide(hint);
      case IrOpcode::kJSModulus:
        return simplified()->SpeculativeBigIntModulus(hint);
      case IrOpcode::kJSBitwiseAnd:
        return simplified()->SpeculativeBigIntBitwiseAnd(hint);
      case IrOpcode::kJSBitwiseOr:
        return simplified()->SpeculativeBigIntBitwiseOr(hint);
      case IrOpcode::kJSBitwiseXor:
        return simplified()->SpeculativeBigIntBitwiseXor(hint);
      case IrOpcode::kJSShiftLeft:
        return simplified()->SpeculativeBigIntShiftLeft(hint);
      case IrOpcode::kJSShiftRight:
        return simplified()->SpeculativeBigIntShiftRight(hint);
      default:
        break;
    }
    UNREACHABLE();
  }
References op_, v8::internal::compiler::Operator::opcode(), simplified(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntAdd(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntBitwiseAnd(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntBitwiseOr(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntBitwiseXor(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntDivide(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntModulus(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntMultiply(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntShiftLeft(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntShiftRight(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntSubtract(), and v8::internal::UNREACHABLE().
Referenced by TryBuildBigIntBinop().
SpeculativeNumberCompareOp()
const Operator* v8::internal::compiler::JSSpeculativeBinopBuilder::SpeculativeNumberCompareOp (NumberOperationHint hint) [inline]
Definition at line 223 of file js-type-hint-lowering.cc.
                                                                       {
    switch (op_->opcode()) {
      case IrOpcode::kJSEqual:
        return simplified()->SpeculativeNumberEqual(hint);
      case IrOpcode::kJSLessThan:
        return simplified()->SpeculativeNumberLessThan(hint);
      case IrOpcode::kJSGreaterThan:
        std::swap(left_, right_); // a > b => b < a
        return simplified()->SpeculativeNumberLessThan(hint);
      case IrOpcode::kJSLessThanOrEqual:
        return simplified()->SpeculativeNumberLessThanOrEqual(hint);
      case IrOpcode::kJSGreaterThanOrEqual:
        std::swap(left_, right_); // a >= b => b <= a
        return simplified()->SpeculativeNumberLessThanOrEqual(hint);
      default:
        break;
    }
    UNREACHABLE();
  }
References left_, op_, v8::internal::compiler::Operator::opcode(), right_, simplified(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberEqual(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberLessThan(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberLessThanOrEqual(), and v8::internal::UNREACHABLE().
Referenced by TryBuildNumberCompare().
SpeculativeNumberOp()
const Operator* v8::internal::compiler::JSSpeculativeBinopBuilder::SpeculativeNumberOp (NumberOperationHint hint) [inline]
Definition at line 151 of file js-type-hint-lowering.cc.
                                                                {
    switch (op_->opcode()) {
      case IrOpcode::kJSAdd:
        if (hint == NumberOperationHint::kSignedSmall) {
          return simplified()->SpeculativeSmallIntegerAdd(hint);
        } else if (hint == NumberOperationHint::kAdditiveSafeInteger) {
          return simplified()->SpeculativeAdditiveSafeIntegerAdd(hint);
        } else {
          return simplified()->SpeculativeNumberAdd(hint);
        }
      case IrOpcode::kJSSubtract:
        if (hint == NumberOperationHint::kSignedSmall) {
          return simplified()->SpeculativeSmallIntegerSubtract(hint);
        } else if (hint == NumberOperationHint::kAdditiveSafeInteger) {
          return simplified()->SpeculativeAdditiveSafeIntegerSubtract(hint);
        } else {
          return simplified()->SpeculativeNumberSubtract(hint);
        }
      case IrOpcode::kJSMultiply:
        return simplified()->SpeculativeNumberMultiply(hint);
      case IrOpcode::kJSExponentiate:
        return simplified()->SpeculativeNumberPow(hint);
      case IrOpcode::kJSDivide:
        return simplified()->SpeculativeNumberDivide(hint);
      case IrOpcode::kJSModulus:
        return simplified()->SpeculativeNumberModulus(hint);
      case IrOpcode::kJSBitwiseAnd:
        return simplified()->SpeculativeNumberBitwiseAnd(hint);
      case IrOpcode::kJSBitwiseOr:
        return simplified()->SpeculativeNumberBitwiseOr(hint);
      case IrOpcode::kJSBitwiseXor:
        return simplified()->SpeculativeNumberBitwiseXor(hint);
      case IrOpcode::kJSShiftLeft:
        return simplified()->SpeculativeNumberShiftLeft(hint);
      case IrOpcode::kJSShiftRight:
        return simplified()->SpeculativeNumberShiftRight(hint);
      case IrOpcode::kJSShiftRightLogical:
        return simplified()->SpeculativeNumberShiftRightLogical(hint);
      default:
        break;
    }
    UNREACHABLE();
  }
References v8::internal::compiler::kAdditiveSafeInteger, v8::internal::compiler::kSignedSmall, op_, v8::internal::compiler::Operator::opcode(), simplified(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeAdditiveSafeIntegerAdd(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeAdditiveSafeIntegerSubtract(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberAdd(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberBitwiseAnd(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberBitwiseOr(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberBitwiseXor(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberDivide(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberModulus(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberMultiply(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberPow(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberShiftLeft(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberShiftRight(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberShiftRightLogical(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeNumberSubtract(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeSmallIntegerAdd(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeSmallIntegerSubtract(), and v8::internal::UNREACHABLE().
Referenced by TryBuildNumberBinop().
TryBuildBigIntBinop()
Node* v8::internal::compiler::JSSpeculativeBinopBuilder::TryBuildBigIntBinop () [inline]
Definition at line 284 of file js-type-hint-lowering.cc.
                              {
    BigIntOperationHint hint;
    if (GetBinaryBigIntOperationHint(&hint)) {
      const Operator* op = SpeculativeBigIntOp(hint);
      Node* node = BuildSpeculativeOperation(op);
      return node;
    }
    return nullptr;
  }
References BuildSpeculativeOperation(), GetBinaryBigIntOperationHint(), and SpeculativeBigIntOp().
Referenced by v8::internal::compiler::JSTypeHintLowering::ReduceBinaryOperation().
TryBuildBigIntCompare()
Node* v8::internal::compiler::JSSpeculativeBinopBuilder::TryBuildBigIntCompare () [inline]
Definition at line 309 of file js-type-hint-lowering.cc.
                                {
    BigIntOperationHint hint;
    if (GetCompareBigIntOperationHint(&hint)) {
      const Operator* op = SpeculativeBigIntCompareOp(hint);
      Node* node = BuildSpeculativeOperation(op);
      return node;
    }
    return nullptr;
  }
References BuildSpeculativeOperation(), GetCompareBigIntOperationHint(), and SpeculativeBigIntCompareOp().
Referenced by v8::internal::compiler::JSTypeHintLowering::ReduceBinaryOperation().
TryBuildNumberBinop()
Node* v8::internal::compiler::JSSpeculativeBinopBuilder::TryBuildNumberBinop () [inline]
Definition at line 274 of file js-type-hint-lowering.cc.
                              {
    NumberOperationHint hint;
    if (GetBinaryNumberOperationHint(&hint)) {
      const Operator* op = SpeculativeNumberOp(hint);
      Node* node = BuildSpeculativeOperation(op);
      return node;
    }
    return nullptr;
  }
References BuildSpeculativeOperation(), GetBinaryNumberOperationHint(), and SpeculativeNumberOp().
Referenced by v8::internal::compiler::JSTypeHintLowering::ReduceBinaryOperation(), and v8::internal::compiler::JSTypeHintLowering::ReduceUnaryOperation().
TryBuildNumberCompare()
Node* v8::internal::compiler::JSSpeculativeBinopBuilder::TryBuildNumberCompare () [inline]
Definition at line 294 of file js-type-hint-lowering.cc.
                                {
    NumberOperationHint hint;
    if (GetCompareNumberOperationHint(&hint)) {
      // Equality doesn't not perform ToNumber conversions on Oddballs.
      if (hint == NumberOperationHint::kNumberOrOddball &&
          op_->opcode() == IrOpcode::kJSEqual) {
        return nullptr;
      }
      const Operator* op = SpeculativeNumberCompareOp(hint);
      Node* node = BuildSpeculativeOperation(op);
      return node;
    }
    return nullptr;
  }
References BuildSpeculativeOperation(), GetCompareNumberOperationHint(), v8::internal::compiler::kNumberOrOddball, op_, v8::internal::compiler::Operator::opcode(), and SpeculativeNumberCompareOp().
Referenced by v8::internal::compiler::JSTypeHintLowering::ReduceBinaryOperation().
Member Data Documentation
control_
Node* const v8::internal::compiler::JSSpeculativeBinopBuilder::control_ [private]
Definition at line 340 of file js-type-hint-lowering.cc.
Referenced by BuildSpeculativeOperation().
effect_
Node* const v8::internal::compiler::JSSpeculativeBinopBuilder::effect_ [private]
Definition at line 339 of file js-type-hint-lowering.cc.
Referenced by BuildSpeculativeOperation().
left_
Node* v8::internal::compiler::JSSpeculativeBinopBuilder::left_ [private]
Definition at line 337 of file js-type-hint-lowering.cc.
Referenced by BuildSpeculativeOperation(), SpeculativeBigIntCompareOp(), and SpeculativeNumberCompareOp().
lowering_
JSTypeHintLowering const* const v8::internal::compiler::JSSpeculativeBinopBuilder::lowering_ [private]
Definition at line 335 of file js-type-hint-lowering.cc.
Referenced by GetBinaryOperationHint(), GetCompareOperationHint(), and jsgraph().
op_
Operator const* const v8::internal::compiler::JSSpeculativeBinopBuilder::op_ [private]
Definition at line 336 of file js-type-hint-lowering.cc.
Referenced by SpeculativeBigIntCompareOp(), SpeculativeBigIntOp(), SpeculativeNumberCompareOp(), SpeculativeNumberOp(), and TryBuildNumberCompare().
right_
Node* v8::internal::compiler::JSSpeculativeBinopBuilder::right_ [private]
Definition at line 338 of file js-type-hint-lowering.cc.
Referenced by BuildSpeculativeOperation(), SpeculativeBigIntCompareOp(), and SpeculativeNumberCompareOp().
slot_
FeedbackSlot const v8::internal::compiler::JSSpeculativeBinopBuilder::slot_ [private]
Definition at line 341 of file js-type-hint-lowering.cc.
Referenced by GetBinaryOperationHint(), and GetCompareOperationHint().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-type-hint-lowering.cc