v8::internal::SimpleStringBuilder Class Reference
Public Member Functions
SimpleStringBuilder (size_t size)
SimpleStringBuilder (char *buffer, size_t size)
~SimpleStringBuilder ()
size_t position () const
void AddCharacter (char c)
void AddString (const char *s, size_t len)
template<size_t N>
void AddStringLiteral (const char(&s)[N])
void AddSubstring (const char *s, size_t n)
void AddPadding (char c, int count)
void AddExponent (int value)
char * Finalize ()
Private Member Functions
bool is_finalized () const
DISALLOW_IMPLICIT_CONSTRUCTORS (SimpleStringBuilder)
Private Attributes
base::Vector< char > buffer_
char * cursor_
Detailed Description
Definition at line 223 of file conversions.cc.
Constructor & Destructor Documentation
SimpleStringBuilder() [1/2]
v8::internal::SimpleStringBuilder::SimpleStringBuilder (size_t size) [inline], [explicit]
Definition at line 228 of file conversions.cc.
                                            {
    buffer_ = base::Vector<char>::New(size);
    cursor_ = buffer_.begin();
  }
References v8::base::Vector< T >::begin(), buffer_, cursor_, v8::base::Vector< T >::New(), and size().
SimpleStringBuilder() [2/2]
v8::internal::SimpleStringBuilder::SimpleStringBuilder (char * buffer, size_t size) [inline]
Definition at line 233 of file conversions.cc.
      : buffer_(buffer, size), cursor_(buffer) {}
 SimpleStringBuilder()
v8::internal::SimpleStringBuilder::~SimpleStringBuilder () [inline]
Definition at line 236 of file conversions.cc.
                         {
    if (V8_UNLIKELY(!is_finalized())) Finalize();
  }
References Finalize(), is_finalized(), and V8_UNLIKELY.
Member Function Documentation
AddCharacter()
void v8::internal::SimpleStringBuilder::AddCharacter (char c) [inline]
Definition at line 249 of file conversions.cc.
                                      {
    DCHECK_NE(c, '\0');
    DCHECK(!is_finalized());
    DCHECK_LT(position(), buffer_.size());
    *cursor_++ = c;
  }
References buffer_, cursor_, v8::internal::DCHECK(), DCHECK_LT, DCHECK_NE, is_finalized(), position(), and v8::base::Vector< T >::size().
Referenced by AddExponent(), v8::internal::CreateExponentialRepresentation(), v8::internal::DoubleToFixedStringView(), v8::internal::DoubleToPrecisionStringView(), and v8::internal::DoubleToStringView().
AddExponent()
void v8::internal::SimpleStringBuilder::AddExponent (int value) [inline]
Definition at line 288 of file conversions.cc.
                                        {
    DCHECK(!is_finalized());
    DCHECK_GE(value, 0);
    DCHECK_LE(value, 999);
    if (value >= 100) {
      // d1 = value / 10; d2 = value % 10;
      // 6554 = ceil(2^16 / 10)
      uint32_t d1 = (static_cast<uint32_t>(value) * 6554) >> 16;
      uint32_t d2 = static_cast<uint32_t>(value) - 10 * d1;
      DCHECK_LT(position() + 2, buffer_.length());
      Convert2Digits(d1, cursor_);
      cursor_ += 2;
      AddCharacter('0' + d2);
    } else if (value >= 10) {
      DCHECK_LT(position() + 2, buffer_.length());
      Convert2Digits(value, cursor_);
      cursor_ += 2;
    } else {
      DCHECK_LT(value, 10);
      AddCharacter('0' + value);
    }
  }
References AddCharacter(), buffer_, v8::internal::Convert2Digits(), cursor_, v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, DCHECK_LT, is_finalized(), v8::base::Vector< T >::length(), position(), and v8::internal::value.
Referenced by v8::internal::CreateExponentialRepresentation(), and v8::internal::DoubleToStringView().
AddPadding()
void v8::internal::SimpleStringBuilder::AddPadding (char c, int count) [inline]
Definition at line 280 of file conversions.cc.
                                               {
    DCHECK(!is_finalized());
    DCHECK_LE(position() + std::max(0, count), buffer_.size());
    cursor_ = std::fill_n(cursor_, count, c);
  }
References buffer_, cursor_, v8::internal::DCHECK(), DCHECK_LE, is_finalized(), position(), and v8::base::Vector< T >::size().
Referenced by v8::internal::CreateExponentialRepresentation(), v8::internal::DoubleToFixedStringView(), v8::internal::DoubleToPrecisionStringView(), and v8::internal::DoubleToStringView().
AddString()
void v8::internal::SimpleStringBuilder::AddString (const char * s, size_t len) [inline]
Definition at line 257 of file conversions.cc.
                                                      {
    DCHECK_EQ(len, strlen(s));
    AddSubstring(s, len);
  }
References AddSubstring(), and DCHECK_EQ.
Referenced by v8::internal::CreateExponentialRepresentation(), v8::internal::DoubleToFixedStringView(), v8::internal::DoubleToPrecisionStringView(), and v8::internal::DoubleToStringView().
AddStringLiteral()
template<size_t N>
void v8::internal::SimpleStringBuilder::AddStringLiteral (const char(&) s[N]) [inline]
Definition at line 264 of file conversions.cc.
                                                      {
    AddSubstring(s, N - 1);
  }
References AddSubstring(), and v8::internal::N.
Referenced by v8::internal::DoubleToPrecisionStringView(), and v8::internal::DoubleToStringView().
AddSubstring()
void v8::internal::SimpleStringBuilder::AddSubstring (const char * s, size_t n) [inline]
Definition at line 270 of file conversions.cc.
                                                       {
    DCHECK(!is_finalized());
    DCHECK_LE(position() + n, buffer_.size());
    DCHECK_LE(n, strlen(s));
    MemCopy(cursor_, s, n * kCharSize);
    cursor_ += n;
  }
References buffer_, cursor_, v8::internal::DCHECK(), DCHECK_LE, is_finalized(), v8::internal::kCharSize, v8::internal::MemCopy(), position(), and v8::base::Vector< T >::size().
Referenced by AddString(), AddStringLiteral(), v8::internal::DoubleToFixedStringView(), v8::internal::DoubleToPrecisionStringView(), and v8::internal::DoubleToStringView().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::SimpleStringBuilder::DISALLOW_IMPLICIT_CONSTRUCTORS (SimpleStringBuilder) [private]
Finalize()
char* v8::internal::SimpleStringBuilder::Finalize () [inline]
Definition at line 313 of file conversions.cc.
                   {
    DCHECK(!is_finalized());
    DCHECK_LE(position(), buffer_.size());
#ifdef DEBUG
    // Make sure nobody managed to add a 0-character to the
    // buffer while building the string.
    for (const char* buf = buffer_.begin(); buf != cursor_; buf++) {
      DCHECK_NE(*buf, '\0');
    }
#endif
    char* ret = cursor_;
    cursor_ = nullptr;
    DCHECK(is_finalized());
    return ret;
  }
References v8::base::Vector< T >::begin(), buffer_, cursor_, v8::internal::DCHECK(), DCHECK_LE, DCHECK_NE, is_finalized(), position(), and v8::base::Vector< T >::size().
Referenced by v8::internal::CreateExponentialRepresentation(), v8::internal::DoubleToFixedStringView(), v8::internal::DoubleToPrecisionStringView(), v8::internal::DoubleToStringView(), and ~SimpleStringBuilder().
is_finalized()
bool v8::internal::SimpleStringBuilder::is_finalized () const [inline], [private]
Definition at line 333 of file conversions.cc.
{ return cursor_ == nullptr; }
References cursor_.
Referenced by AddCharacter(), AddExponent(), AddPadding(), AddSubstring(), Finalize(), position(), and ~SimpleStringBuilder().
position()
size_t v8::internal::SimpleStringBuilder::position () const [inline]
Definition at line 241 of file conversions.cc.
                          {
    DCHECK(!is_finalized());
    return cursor_ - buffer_.begin();
  }
References v8::base::Vector< T >::begin(), buffer_, cursor_, v8::internal::DCHECK(), and is_finalized().
Referenced by AddCharacter(), AddExponent(), AddPadding(), AddSubstring(), v8::internal::DoubleToPrecisionStringView(), and Finalize().
Member Data Documentation
buffer_
base::Vector<char> v8::internal::SimpleStringBuilder::buffer_ [private]
Definition at line 330 of file conversions.cc.
Referenced by AddCharacter(), AddExponent(), AddPadding(), AddSubstring(), Finalize(), position(), and SimpleStringBuilder().
cursor_
char* v8::internal::SimpleStringBuilder::cursor_ [private]
Definition at line 331 of file conversions.cc.
Referenced by AddCharacter(), AddExponent(), AddPadding(), AddSubstring(), Finalize(), is_finalized(), position(), and SimpleStringBuilder().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/numbers/conversions.cc