v8::internal::compiler::FrameState Class Reference
#include <common-operator.h>
Public Member Functions
constexpr FrameState (Node *node)
const FrameStateInfo & frame_state_info () const
Node * parameters () const
Node * locals () const
Node * stack () const
Node * context () const
Node * function () const
Node * outer_frame_state () const
Static Public Attributes
static constexpr int kFrameStateParametersInput = 0
static constexpr int kFrameStateLocalsInput = 1
static constexpr int kFrameStateStackInput = 2
static constexpr int kFrameStateContextInput = 3
static constexpr int kFrameStateFunctionInput = 4
static constexpr int kFrameStateOuterStateInput = 5
static constexpr int kFrameStateInputCount = 6
Additional Inherited Members
Detailed Description
Definition at line 715 of file common-operator.h.
Constructor & Destructor Documentation
FrameState()
constexpr v8::internal::compiler::FrameState::FrameState (Node * node) [inline], [explicit], [constexpr]
Definition at line 717 of file common-operator.h.
                                            : CommonNodeWrapperBase(node) {
    DCHECK_EQ(node->opcode(), IrOpcode::kFrameState);
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
context()
Node* v8::internal::compiler::FrameState::context () const [inline]
Definition at line 750 of file common-operator.h.
{ return node()->InputAt(kFrameStateContextInput); }
References v8::internal::compiler::Node::InputAt(), kFrameStateContextInput, and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::BuildFrameStateData(), and v8::internal::compiler::CloneFrameState().
frame_state_info()
const FrameStateInfo& v8::internal::compiler::FrameState::frame_state_info () const [inline]
Definition at line 721 of file common-operator.h.
                                                 {
    return FrameStateInfoOf(node()->op());
  }
References v8::internal::compiler::FrameStateInfoOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::CloneFrameState(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSFindNonDefaultConstructorOrConstruct(), v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateArguments(), and v8::internal::compiler::JSCreateLowering::TryAllocateRestArguments().
function()
Node* v8::internal::compiler::FrameState::function () const [inline]
Definition at line 751 of file common-operator.h.
{ return node()->InputAt(kFrameStateFunctionInput); }
References v8::internal::compiler::Node::InputAt(), kFrameStateFunctionInput, and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::BuildFrameStateData(), and v8::internal::compiler::CloneFrameState().
locals()
Node* v8::internal::compiler::FrameState::locals () const [inline]
Definition at line 741 of file common-operator.h.
                       {
    Node* n = node()->InputAt(kFrameStateLocalsInput);
    DCHECK(n->opcode() == IrOpcode::kStateValues ||
           n->opcode() == IrOpcode::kTypedStateValues);
    return n;
  }
References v8::internal::DCHECK(), v8::internal::compiler::Node::InputAt(), kFrameStateLocalsInput, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::BuildFrameStateData(), v8::internal::compiler::CloneFrameState(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CollectFrameStateUniqueUses(), and v8::internal::compiler::JSInliningHeuristic::DuplicateFrameStateAndRename().
outer_frame_state()
Node* v8::internal::compiler::FrameState::outer_frame_state () const [inline]
Definition at line 755 of file common-operator.h.
                                  {
    Node* result = node()->InputAt(kFrameStateOuterStateInput);
    DCHECK(result->opcode() == IrOpcode::kFrameState ||
           result->opcode() == IrOpcode::kStart ||
           result->opcode() == IrOpcode::kDeadValue);
    return result;
  }
References v8::internal::DCHECK(), v8::internal::compiler::Node::InputAt(), kFrameStateOuterStateInput, v8::kStart, v8::internal::compiler::NodeWrapper::node(), and v8::base::internal::result.
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::BuildFrameStateData(), v8::internal::compiler::CloneFrameState(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSInliner::ReduceJSCall(), and v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs().
parameters()
Node* v8::internal::compiler::FrameState::parameters () const [inline]
Definition at line 734 of file common-operator.h.
                           {
    Node* n = node()->InputAt(kFrameStateParametersInput);
    DCHECK(n->opcode() == IrOpcode::kStateValues ||
           n->opcode() == IrOpcode::kTypedStateValues ||
           n->opcode() == IrOpcode::kDeadValue);
    return n;
  }
References v8::internal::DCHECK(), v8::internal::compiler::Node::InputAt(), kFrameStateParametersInput, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::BuildFrameStateData(), v8::internal::compiler::CloneFrameState(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateArguments(), and v8::internal::compiler::JSCreateLowering::TryAllocateRestArguments().
stack()
Node* v8::internal::compiler::FrameState::stack () const [inline]
Definition at line 749 of file common-operator.h.
{ return node()->InputAt(kFrameStateStackInput); }
References v8::internal::compiler::Node::InputAt(), kFrameStateStackInput, and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::BuildFrameStateData(), v8::internal::compiler::CloneFrameState(), v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CollectFrameStateUniqueUses(), v8::internal::compiler::JSInliningHeuristic::DuplicateFrameStateAndRename(), and v8::internal::compiler::RepresentationSelector::VisitFrameState().
Member Data Documentation
kFrameStateContextInput
constexpr int v8::internal::compiler::FrameState::kFrameStateContextInput = 3 [static], [constexpr]
Definition at line 728 of file common-operator.h.
Referenced by context(), v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState(), and v8::internal::compiler::RepresentationSelector::VisitFrameState().
kFrameStateFunctionInput
constexpr int v8::internal::compiler::FrameState::kFrameStateFunctionInput = 4 [static], [constexpr]
Definition at line 729 of file common-operator.h.
Referenced by function(), v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState(), and v8::internal::compiler::RepresentationSelector::VisitFrameState().
kFrameStateInputCount
constexpr int v8::internal::compiler::FrameState::kFrameStateInputCount = 6 [static], [constexpr]
Definition at line 731 of file common-operator.h.
Referenced by v8::internal::compiler::RepresentationSelector::VisitFrameState().
kFrameStateLocalsInput
constexpr int v8::internal::compiler::FrameState::kFrameStateLocalsInput = 1 [static], [constexpr]
Definition at line 726 of file common-operator.h.
Referenced by v8::internal::compiler::JSInliningHeuristic::DuplicateFrameStateAndRename(), locals(), v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState(), and v8::internal::compiler::RepresentationSelector::VisitFrameState().
kFrameStateOuterStateInput
constexpr int v8::internal::compiler::FrameState::kFrameStateOuterStateInput = 5 [static], [constexpr]
Definition at line 730 of file common-operator.h.
Referenced by outer_frame_state(), v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState(), and v8::internal::compiler::RepresentationSelector::VisitFrameState().
kFrameStateParametersInput
constexpr int v8::internal::compiler::FrameState::kFrameStateParametersInput = 0 [static], [constexpr]
Definition at line 725 of file common-operator.h.
Referenced by parameters(), v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState(), and v8::internal::compiler::RepresentationSelector::VisitFrameState().
kFrameStateStackInput
constexpr int v8::internal::compiler::FrameState::kFrameStateStackInput = 2 [static], [constexpr]
Definition at line 727 of file common-operator.h.
Referenced by v8::internal::compiler::anonymous_namespace{js-inlining-heuristic.cc}::CollectFrameStateUniqueUses(), v8::internal::compiler::JSInliningHeuristic::DuplicateFrameStateAndRename(), v8::internal::compiler::EscapeAnalysisReducer::ReduceDeoptState(), stack(), and v8::internal::compiler::RepresentationSelector::VisitFrameState().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/common-operator.h