v8::internal::SourceTextModuleDescriptor::AstModuleRequest Class Reference
#include <modules.h>
Public Member Functions
AstModuleRequest (const AstRawString *specifier, const ModuleImportPhase phase, const ImportAttributes *import_attributes, int position, int index)
template<typename IsolateT >
DirectHandle< v8::internal::ModuleRequest > Serialize (IsolateT *isolate) const
const AstRawString * specifier () const
const ImportAttributes * import_attributes () const
ModuleImportPhase phase () const
int position () const
int index () const
template<typename IsolateT >
DirectHandle< ModuleRequest > Serialize (IsolateT *isolate) const
Private Attributes
const AstRawString * specifier_
const ModuleImportPhase phase_
const ImportAttributes * import_attributes_
int position_
int index_
Detailed Description
Definition at line 124 of file modules.h.
Constructor & Destructor Documentation
AstModuleRequest()
v8::internal::SourceTextModuleDescriptor::AstModuleRequest::AstModuleRequest (const AstRawString * specifier, const ModuleImportPhase phase, const ImportAttributes * import_attributes, int position, int index) [inline]
Definition at line 126 of file modules.h.
        : specifier_(specifier),
          phase_(phase),
          import_attributes_(import_attributes),
          position_(position),
          index_(index) {}
Member Function Documentation
import_attributes()
const ImportAttributes* v8::internal::SourceTextModuleDescriptor::AstModuleRequest::import_attributes () const [inline]
Definition at line 141 of file modules.h.
                                                      {
      return import_attributes_;
    }
References import_attributes_.
Referenced by v8::internal::SourceTextModuleDescriptor::ModuleRequestComparer::operator()().
index()
int v8::internal::SourceTextModuleDescriptor::AstModuleRequest::index () const [inline]
Definition at line 147 of file modules.h.
{ return index_; }
References index_.
phase()
ModuleImportPhase v8::internal::SourceTextModuleDescriptor::AstModuleRequest::phase () const [inline]
Definition at line 144 of file modules.h.
{ return phase_; }
References phase_.
Referenced by v8::internal::SourceTextModuleDescriptor::ModuleRequestComparer::operator()().
position()
int v8::internal::SourceTextModuleDescriptor::AstModuleRequest::position () const [inline]
Definition at line 146 of file modules.h.
{ return position_; }
References position_.
Serialize() [1/2]
template<typename IsolateT >
DirectHandle<ModuleRequest> v8::internal::SourceTextModuleDescriptor::AstModuleRequest::Serialize (IsolateT * isolate) const
Definition at line 137 of file modules.cc.
                             {
  // The import attributes will be stored in this array in the form:
  // [key1, value1, location1, key2, value2, location2, ...]
  DirectHandle<FixedArray> import_attributes_array =
      isolate->factory()->NewFixedArray(
          static_cast<int>(import_attributes()->size() *
                           ModuleRequest::kAttributeEntrySize),
          AllocationType::kOld);
  {
    DisallowGarbageCollection no_gc;
    Tagged<FixedArray> raw_import_attributes = *import_attributes_array;
    int i = 0;
    for (auto iter = import_attributes()->cbegin();
         iter != import_attributes()->cend();
         ++iter, i += ModuleRequest::kAttributeEntrySize) {
      raw_import_attributes->set(i, *iter->first->string());
      raw_import_attributes->set(i + 1, *iter->second.first->string());
      raw_import_attributes->set(i + 2,
                                 Smi::FromInt(iter->second.second.beg_pos));
    }
  }
  return v8::internal::ModuleRequest::New(isolate, specifier()->string(),
                                          phase_, import_attributes_array,
                                          position());
}
References v8::internal::Smi::FromInt(), v8::internal::ModuleRequest::kAttributeEntrySize, v8::internal::kOld, v8::internal::ModuleRequest::New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and size().
Serialize() [2/2]
template<typename IsolateT >
DirectHandle<v8::internal::ModuleRequest> v8::internal::SourceTextModuleDescriptor::AstModuleRequest::Serialize (IsolateT * isolate) const
specifier()
const AstRawString* v8::internal::SourceTextModuleDescriptor::AstModuleRequest::specifier () const [inline]
Definition at line 140 of file modules.h.
{ return specifier_; }
References specifier_.
Referenced by v8::internal::SourceTextModuleDescriptor::ModuleRequestComparer::operator()().
Member Data Documentation
import_attributes_
const ImportAttributes* v8::internal::SourceTextModuleDescriptor::AstModuleRequest::import_attributes_ [private]
Definition at line 152 of file modules.h.
Referenced by import_attributes().
index_
int v8::internal::SourceTextModuleDescriptor::AstModuleRequest::index_ [private]
Definition at line 159 of file modules.h.
Referenced by index().
phase_
const ModuleImportPhase v8::internal::SourceTextModuleDescriptor::AstModuleRequest::phase_ [private]
Definition at line 151 of file modules.h.
Referenced by phase().
position_
int v8::internal::SourceTextModuleDescriptor::AstModuleRequest::position_ [private]
Definition at line 155 of file modules.h.
Referenced by position().
specifier_
const AstRawString* v8::internal::SourceTextModuleDescriptor::AstModuleRequest::specifier_ [private]
Definition at line 150 of file modules.h.
Referenced by specifier().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/modules.h
/mnt/V8SourceCode/src/ast/modules.cc