v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor Class Reference
Static Public Member Functions
static ZoneList< RegExpInstruction > Compile (RegExpTree *tree, RegExpFlags flags, Zone *zone)
Private Member Functions
CompileVisitor (Zone *zone)
void CompileLookaround (RegExpLookaround *lookaround)
template<class F >
void CompileDisjunction (int alt_num, F &&gen_alt)
void * VisitDisjunction (RegExpDisjunction *node, void *) override
void * VisitAlternative (RegExpAlternative *node, void *) override
void * VisitAssertion (RegExpAssertion *node, void *) override
void CompileCharacterRanges (ZoneList< CharacterRange > *ranges, bool negated)
void * VisitClassRanges (RegExpClassRanges *node, void *) override
void * VisitClassSetOperand (RegExpClassSetOperand *node, void *) override
void * VisitClassSetExpression (RegExpClassSetExpression *node, void *) override
void * VisitAtom (RegExpAtom *node, void *) override
void ClearRegisters (Interval indices)
template<class F >
void CompileGreedyStar (F &&emit_body)
template<class F >
void CompileNonGreedyStar (F &&emit_body)
template<class F >
void CompileGreedyRepetition (F &&emit_body, int max_repetition_num)
template<class F >
void CompileNonGreedyRepetition (F &&emit_body, int max_repetition_num)
template<class F >
void CompileNonNullableGreedyPlus (F &&emit_body)
template<class F >
void CompileNonNullableNonGreedyPlus (F &&emit_body)
void * VisitQuantifier (RegExpQuantifier *node, void *) override
void * VisitCapture (RegExpCapture *node, void *) override
void * VisitGroup (RegExpGroup *node, void *) override
void * VisitLookaround (RegExpLookaround *node, void *) override
void * VisitBackReference (RegExpBackReference *node, void *) override
void * VisitEmpty (RegExpEmpty *node, void *) override
void * VisitText (RegExpText *node, void *) override
int RemapQuantifier (int id)
int RemapLookaround (int id)
Private Attributes
Zone * zone_
ZoneLinkedList< RegExpLookaround * > lookarounds_
std::optional< ZoneMap< int, int > > quantifier_id_remapping_
ZoneMap< int, int > lookaround_id_remapping_
BytecodeAssembler assembler_
bool reverse_
bool ignore_captures_
bool ignore_lookarounds_
Detailed Description
Definition at line 553 of file experimental-compiler.cc.
Constructor & Destructor Documentation
CompileVisitor()
v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileVisitor (Zone * zone) [inline], [explicit], [private]
Definition at line 619 of file experimental-compiler.cc.
      : zone_(zone),
        lookarounds_(zone),
        quantifier_id_remapping_({}),
        lookaround_id_remapping_(zone),
        assembler_(zone),
        reverse_(false),
        ignore_captures_(false),
        ignore_lookarounds_(false) {
    if (v8_flags.experimental_regexp_engine_capture_group_opt) {
      quantifier_id_remapping_.emplace(zone_);
    }
  }
Member Function Documentation
ClearRegisters()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::ClearRegisters (Interval indices) [inline], [private]
Definition at line 820 of file experimental-compiler.cc.
                                        {
    if (indices.is_empty()) return;
    DCHECK_EQ(indices.from() % 2, 0);
    DCHECK_EQ(indices.to() % 2, 1);
    for (int i = indices.from(); i <= indices.to(); i += 2) {
      // It suffices to clear the register containing the `begin` of a capture
      // because this indicates that the capture is undefined, regardless of
      // the value in the `end` register.
      assembler_.ClearRegister(i);
    }
  }
References DCHECK_EQ, v8::internal::Interval::from(), v8::internal::Interval::is_empty(), and v8::internal::Interval::to().
Compile()
static ZoneList<RegExpInstruction> v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::Compile (RegExpTree * tree, RegExpFlags flags, Zone * zone) [inline], [static]
Definition at line 555 of file experimental-compiler.cc.
                                                                            {
    CompileVisitor compiler(zone);
    if (!IsSticky(flags) && !tree->IsAnchoredAtStart()) {
      // The match is not anchored, i.e. may start at any input position, so we
      // emit a preamble corresponding to /.*?/. This skips an arbitrary
      // prefix in the input non-greedily.
      compiler.CompileNonGreedyStar(
          [&]() { compiler.assembler_.ConsumeAnyChar(); });
    }
    compiler.assembler_.SetRegisterToCp(0);
    tree->Accept(&compiler, nullptr);
    compiler.assembler_.SetRegisterToCp(1);
    compiler.assembler_.Accept();
    // Each lookaround is compiled as two different bytecode sections: a
    // reverse, captureless automaton and a capturing one. The indexes are
    // remapped to avoid holes in the lookaround table, which would occur when
    // lookarounds are optimized out of the AST. The resulting indexes have the
    // following order: lookarounds can only depend on ones with a higher index.
    //
    // During the compilation of the main expression, lookarounds are not
    // immediately compiled, and are instead pushed at the back of a queue.
    // After compiling the filtering instructions, the queue is emptied and
    // each lookaround body is compiled into two sections:
    //
    // 1. A non-capturing automaton, which is reversed if it is a lookahead.
    // 2. A capturing automaton, reversed if it is a lookbehind. Since it is
    // only used for capturing, it can be empty if the lookaround does
    // not contain any captures.
    //
    // See the comment on `NfaInterpreter` in experimental-interpreter.cc for
    // detailed explanation on the reversal's reasons. The sections are
    // delimited by `START_LOOKAROUND` and `END_LOOKAROUND`, and the separation
    // occurs right after `WRITE_LOOKAROUND_TABLE`.
    //
    // If another lookaround is encountered during this phase, it is added
    // at the back of the queue.
    //
    // This approach prevents the use of the sticky or global flags. In both
    // cases, when resuming the search, it starts at a non null index, while the
    // lookbehinds always need to start at the beginning of the string. A future
    // implementation for the global flag may store the active lookbehind
    // threads in the regexp to resume the execution of the lookbehinds
    // automata.
    while (!compiler.lookarounds_.empty()) {
      auto node = compiler.lookarounds_.front();
      compiler.CompileLookaround(node);
      compiler.lookarounds_.pop_front();
    }
    if (v8_flags.experimental_regexp_engine_capture_group_opt) {
      FilterGroupsCompileVisitor::CompileFilter(
          zone, tree, compiler.assembler_,
          compiler.quantifier_id_remapping_.value(),
          compiler.lookaround_id_remapping_);
    }
    return std::move(compiler.assembler_).IntoCode();
  }
References v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Accept(), v8::internal::RegExpTree::Accept(), assembler_, CompileLookaround(), CompileNonGreedyStar(), v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::ConsumeAnyChar(), v8::internal::flags, v8::internal::RegExpTree::IsAnchoredAtStart(), lookaround_id_remapping_, lookarounds_, quantifier_id_remapping_, v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::SetRegisterToCp(), and v8::internal::v8_flags.
CompileCharacterRanges()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileCharacterRanges (ZoneList< CharacterRange > * ranges, bool negated) [inline], [private]
Definition at line 743 of file experimental-compiler.cc.
                                                                              {
    // A character class is compiled as disjoint character ranges.
    // A single range is represented by a single `CONSUME_RANGE` instruction.
    // Disjoint ranges are represented by a `RANGE_COUNT` instruction followed
    // by `CONSUME_RANGE` instructions.
    CharacterRange::Canonicalize(ranges);
    if (negated) {
      // The complement of a disjoint, non-adjacent (i.e. `Canonicalize`d)
      // union of k intervals is a union of at most k + 1 intervals.
      ZoneList<CharacterRange>* negated_ranges =
          zone_->New<ZoneList<CharacterRange>>(ranges->length() + 1, zone_);
      CharacterRange::Negate(ranges, negated_ranges, zone_);
      DCHECK_LE(negated_ranges->length(), ranges->length() + 1);
      ranges = negated_ranges;
    }
    if (ranges->length() == 0) {
      assembler_.Fail();
      return;
    }
    if (ranges->length() > 1) {
      // In the case of a multiple ranges, we need a RANGE_COUNT instruction.
      assembler_.RangeCount(ranges->length());
    }
    for (int i = 0; i < ranges->length(); ++i) {
      // We don't support utf16 for now, so only ranges that can be specified
      // by (complements of) ranges with base::uc16 bounds.
      static_assert(kMaxSupportedCodepoint <=
                    std::numeric_limits<base::uc16>::max());
      base::uc32 from = (*ranges)[i].from();
      DCHECK_LE(from, kMaxSupportedCodepoint);
      base::uc16 from_uc16 = static_cast<base::uc16>(from);
      base::uc32 to = (*ranges)[i].to();
      DCHECK_IMPLIES(to > kMaxSupportedCodepoint, to == kMaxCodePoint);
      base::uc16 to_uc16 =
          static_cast<base::uc16>(std::min(to, kMaxSupportedCodepoint));
      assembler_.ConsumeRange(from_uc16, to_uc16);
    }
  }
References v8::internal::CharacterRange::Canonicalize(), DCHECK_IMPLIES, DCHECK_LE, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kMaxCodePoint, v8::internal::anonymous_namespace{experimental-compiler.cc}::kMaxSupportedCodepoint, v8::internal::ZoneList< T >::length(), and v8::internal::CharacterRange::Negate().
CompileDisjunction()
template<class F >
void v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileDisjunction (int alt_num, F && gen_alt) [inline], [private]
Definition at line 673 of file experimental-compiler.cc.
                                                    {
    // An alternative a1 | ... | an is compiled into
    //
    // FORK tail1
    // <a1>
    // JMP end
    // tail1:
    // FORK tail2
    // <a2>
    // JMP end
    // tail2:
    // ...
    // ...
    // tail{n -1}:
    // <an>
    // end:
    //
    // By the semantics of the FORK instruction (see above at definition and
    // semantics), a forked thread has lower priority than the thread that
    // spawned it. This means that with the code we're generating here, the
    // thread matching the alternative a1 has indeed highest priority, followed
    // by the thread for a2 and so on.
    if (alt_num == 0) {
      // The empty disjunction. This can never match.
      assembler_.Fail();
      return;
    }
    Label end;
    for (int i = 0; i != alt_num - 1; ++i) {
      Label tail;
      assembler_.Fork(tail);
      gen_alt(i);
      assembler_.Jmp(end);
      assembler_.Bind(tail);
    }
    gen_alt(alt_num - 1);
    assembler_.Bind(end);
  }
References v8::internal::compiler::end(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
CompileGreedyRepetition()
template<class F >
void v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileGreedyRepetition (F && emit_body, int max_repetition_num) [inline], [private]
Definition at line 893 of file experimental-compiler.cc.
                                                                      {
    // This is compiled into
    //
    // FORK end
    // BEGIN_LOOP
    // <body>
    // END_LOOP
    // FORK end
    // BEGIN_LOOP
    // <body>
    // END_LOOP
    // ...
    // ...
    // FORK end
    // <body>
    // end:
    // ...
    //
    // We add `BEGIN_LOOP` and `END_LOOP` instructions because these optional
    // repetitions of the body cannot match the empty string.
    Label end;
    for (int i = 0; i != max_repetition_num; ++i) {
      assembler_.Fork(end);
      assembler_.BeginLoop();
      emit_body();
      assembler_.EndLoop();
    }
    assembler_.Bind(end);
  }
References v8::internal::compiler::end(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
CompileGreedyStar()
template<class F >
void v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileGreedyStar (F && emit_body) [inline], [private]
Definition at line 834 of file experimental-compiler.cc.
                                        {
    // This is compiled into
    //
    // begin:
    // FORK end
    // BEGIN_LOOP
    // <body>
    // END_LOOP
    // JMP begin
    // end:
    // ...
    //
    // This is greedy because a forked thread has lower priority than the
    // thread that spawned it.
    Label begin;
    Label end;
    assembler_.Bind(begin);
    assembler_.Fork(end);
    assembler_.BeginLoop();
    emit_body();
    assembler_.EndLoop();
    assembler_.Jmp(begin);
    assembler_.Bind(end);
  }
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
CompileLookaround()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileLookaround (RegExpLookaround * lookaround) [inline], [private]
Definition at line 634 of file experimental-compiler.cc.
                                                       {
    // Generate the first section, reversed in the case of a lookahead.
    assembler_.StartLookaround(RemapLookaround(lookaround->index()),
                               lookaround->is_positive(), lookaround->type());
    // If the lookaround is not anchored, we add a /.*?/ at its start, such
    // that the resulting automaton will run over the whole input.
    if ((lookaround->type() == RegExpLookaround::LOOKAHEAD &&
         !lookaround->body()->IsAnchoredAtEnd()) ||
        (lookaround->type() == RegExpLookaround::LOOKBEHIND &&
         !lookaround->body()->IsAnchoredAtStart())) {
      CompileNonGreedyStar([&]() { assembler_.ConsumeAnyChar(); });
    }
    reverse_ = lookaround->type() == RegExpLookaround::LOOKAHEAD;
    ignore_captures_ = true;
    lookaround->body()->Accept(this, nullptr);
    ignore_captures_ = false;
    assembler_.WriteLookaroundTable(RemapLookaround(lookaround->index()));
    // Generate the second sections, reversed in the case of a lookbehind.
    if (lookaround->capture_count() > 0 && lookaround->is_positive()) {
      reverse_ = lookaround->type() == RegExpLookaround::LOOKBEHIND;
      ignore_lookarounds_ = true;
      lookaround->body()->Accept(this, nullptr);
      ignore_lookarounds_ = false;
    }
    assembler_.EndLookaround();
  }
References v8::internal::RegExpTree::Accept(), v8::internal::RegExpLookaround::body(), v8::internal::RegExpLookaround::capture_count(), v8::internal::RegExpLookaround::index(), v8::internal::RegExpLookaround::is_positive(), v8::internal::RegExpTree::IsAnchoredAtEnd(), v8::internal::RegExpTree::IsAnchoredAtStart(), v8::internal::RegExpLookaround::LOOKAHEAD, v8::internal::RegExpLookaround::LOOKBEHIND, and v8::internal::RegExpLookaround::type().
Referenced by Compile().
CompileNonGreedyRepetition()
template<class F >
void v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileNonGreedyRepetition (F && emit_body, int max_repetition_num) [inline], [private]
Definition at line 926 of file experimental-compiler.cc.
                                                                         {
    // This is compiled into
    //
    // FORK body0
    // JMP end
    // body0:
    // BEGIN_LOOP
    // <body>
    // END_LOOP
    //
    // FORK body1
    // JMP end
    // body1:
    // BEGIN_LOOP
    // <body>
    // END_LOOP
    // ...
    // ...
    // body{max_repetition_num - 1}:
    // BEGIN_LOOP
    // <body>
    // END_LOOP
    // end:
    // ...
    //
    // We add `BEGIN_LOOP` and `END_LOOP` instructions because these optional
    // repetitions of the body cannot match the empty string.
    Label end;
    for (int i = 0; i != max_repetition_num; ++i) {
      Label body;
      assembler_.Fork(body);
      assembler_.Jmp(end);
      assembler_.Bind(body);
      assembler_.BeginLoop();
      emit_body();
      assembler_.EndLoop();
    }
    assembler_.Bind(end);
  }
References v8::internal::compiler::end(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
CompileNonGreedyStar()
template<class F >
void v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileNonGreedyStar (F && emit_body) [inline], [private]
Definition at line 863 of file experimental-compiler.cc.
                                           {
    // This is compiled into
    //
    // FORK body
    // JMP end
    // body:
    // BEGIN_LOOP
    // <body>
    // END_LOOP
    // FORK body
    // end:
    // ...
    Label body;
    Label end;
    assembler_.Fork(body);
    assembler_.Jmp(end);
    assembler_.Bind(body);
    assembler_.BeginLoop();
    emit_body();
    assembler_.EndLoop();
    assembler_.Fork(body);
    assembler_.Bind(end);
  }
References v8::internal::compiler::end().
Referenced by Compile().
CompileNonNullableGreedyPlus()
template<class F >
void v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileNonNullableGreedyPlus (F && emit_body) [inline], [private]
Definition at line 985 of file experimental-compiler.cc.
                                                   {
    // This is compiled into
    //
    // begin:
    // <body>
    //
    // FORK end
    // JMP begin
    // end:
    // ...
    Label begin, end;
    assembler_.Bind(begin);
    emit_body();
    assembler_.Fork(end);
    assembler_.Jmp(begin);
    assembler_.Bind(end);
  }
References v8::internal::compiler::begin(), and v8::internal::compiler::end().
CompileNonNullableNonGreedyPlus()
template<class F >
void v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::CompileNonNullableNonGreedyPlus (F && emit_body) [inline], [private]
Definition at line 1008 of file experimental-compiler.cc.
                                                      {
    // This is compiled into
    //
    // begin:
    // <body>
    //
    // FORK begin
    // ...
    Label begin;
    assembler_.Bind(begin);
    emit_body();
    assembler_.Fork(begin);
  }
References v8::internal::compiler::begin().
RemapLookaround()
int v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::RemapLookaround (int id) [inline], [private]
Definition at line 1191 of file experimental-compiler.cc.
                              {
    if (!lookaround_id_remapping_.contains(id)) {
      lookaround_id_remapping_[id] =
          static_cast<int>(lookaround_id_remapping_.size());
    }
    return lookaround_id_remapping_[id];
  }
RemapQuantifier()
int v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::RemapQuantifier (int id) [inline], [private]
Definition at line 1179 of file experimental-compiler.cc.
                              {
    DCHECK(v8_flags.experimental_regexp_engine_capture_group_opt);
    DCHECK(quantifier_id_remapping_.has_value());
    auto& map = quantifier_id_remapping_.value();
    if (!map.contains(id)) {
      map[id] = static_cast<int>(map.size());
    }
    return map[id];
  }
References v8::internal::DCHECK(), and v8::internal::v8_flags.
VisitAlternative()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitAlternative (RegExpAlternative * node, void *) [inline], [override], [private]
Definition at line 724 of file experimental-compiler.cc.
                                                                  {
    if (reverse_) {
      ZoneList<RegExpTree*>* children = node->nodes();
      for (int i = children->length() - 1; i >= 0; --i) {
        children->at(i)->Accept(this, nullptr);
      }
    } else {
      for (RegExpTree* child : *node->nodes()) {
        child->Accept(this, nullptr);
      }
    }
    return nullptr;
  }
References v8::internal::ZoneList< T >::at(), v8::internal::ZoneList< T >::length(), and v8::internal::RegExpAlternative::nodes().
VisitAssertion()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitAssertion (RegExpAssertion * node, void *) [inline], [override], [private]
Definition at line 738 of file experimental-compiler.cc.
                                                              {
    assembler_.Assertion(node->assertion_type());
    return nullptr;
  }
References v8::internal::RegExpAssertion::assertion_type().
VisitAtom()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitAtom (RegExpAtom * node, void *) [inline], [override], [private]
Definition at line 806 of file experimental-compiler.cc.
                                                    {
    if (reverse_) {
      base::Vector<const base::uc16> data = node->data();
      for (int i = data.length() - 1; i >= 0; --i) {
        assembler_.ConsumeRange(data.at(i), data.at(i));
      }
    } else {
      for (base::uc16 c : node->data()) {
        assembler_.ConsumeRange(c, c);
      }
    }
    return nullptr;
  }
References v8::base::Vector< T >::at(), v8::internal::RegExpAtom::data(), and v8::base::Vector< T >::length().
VisitBackReference()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitBackReference (RegExpBackReference * node, void *) [inline], [override], [private]
Definition at line 1159 of file experimental-compiler.cc.
                                                                      {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitCapture()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitCapture (RegExpCapture * node, void *) [inline], [override], [private]
Definition at line 1125 of file experimental-compiler.cc.
                                                          {
    if (ignore_captures_) {
      // Skips the `SET_REGISTER_TO_CP` instructions.
      node->body()->Accept(this, nullptr);
    } else {
      int index = node->index();
      int start_register = RegExpCapture::StartRegister(index);
      int end_register = RegExpCapture::EndRegister(index);
      assembler_.SetRegisterToCp(reverse_ ? end_register : start_register);
      node->body()->Accept(this, nullptr);
      assembler_.SetRegisterToCp(reverse_ ? start_register : end_register);
    }
    return nullptr;
  }
References v8::internal::RegExpTree::Accept(), v8::internal::RegExpCapture::body(), v8::internal::RegExpCapture::EndRegister(), v8::internal::index, v8::internal::RegExpCapture::index(), and v8::internal::RegExpCapture::StartRegister().
VisitClassRanges()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitClassRanges (RegExpClassRanges * node, void *) [inline], [override], [private]
Definition at line 788 of file experimental-compiler.cc.
                                                                  {
    CompileCharacterRanges(node->ranges(zone_), node->is_negated());
    return nullptr;
  }
References v8::internal::RegExpClassRanges::is_negated(), and v8::internal::RegExpClassRanges::ranges().
VisitClassSetExpression()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitClassSetExpression (RegExpClassSetExpression * node, void *) [inline], [override], [private]
Definition at line 800 of file experimental-compiler.cc.
                                                {
    // TODO(v8:11935): Add support.
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
VisitClassSetOperand()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitClassSetOperand (RegExpClassSetOperand * node, void *) [inline], [override], [private]
Definition at line 793 of file experimental-compiler.cc.
                                                                          {
    // TODO(v8:11935): Support strings.
    DCHECK(!node->has_strings());
    CompileCharacterRanges(node->ranges(), false);
    return nullptr;
  }
References v8::internal::DCHECK(), v8::internal::RegExpClassSetOperand::has_strings(), and v8::internal::RegExpClassSetOperand::ranges().
VisitDisjunction()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitDisjunction (RegExpDisjunction * node, void *) [inline], [override], [private]
Definition at line 717 of file experimental-compiler.cc.
                                                                  {
    ZoneList<RegExpTree*>& alts = *node->alternatives();
    CompileDisjunction(alts.length(),
                       [&](int i) { alts[i]->Accept(this, nullptr); });
    return nullptr;
  }
References v8::internal::RegExpDisjunction::alternatives(), and v8::internal::ZoneList< T >::length().
VisitEmpty()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitEmpty (RegExpEmpty * node, void *) [inline], [override], [private]
Definition at line 1163 of file experimental-compiler.cc.
{ return nullptr; }
VisitGroup()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitGroup (RegExpGroup * node, void *) [inline], [override], [private]
Definition at line 1142 of file experimental-compiler.cc.
                                                      {
    node->body()->Accept(this, nullptr);
    return nullptr;
  }
References v8::internal::RegExpTree::Accept(), and v8::internal::RegExpGroup::body().
VisitLookaround()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitLookaround (RegExpLookaround * node, void *) [inline], [override], [private]
Definition at line 1147 of file experimental-compiler.cc.
                                                                {
    assembler_.ReadLookaroundTable(RemapLookaround(node->index()),
                                   node->is_positive(), node->type());
    // Add the lookbehind to the queue of lookbehinds to be compiled.
    if (!ignore_lookarounds_) {
      lookarounds_.push_back(node);
    }
    return nullptr;
  }
References v8::internal::RegExpLookaround::index(), v8::internal::RegExpLookaround::is_positive(), and v8::internal::RegExpLookaround::type().
VisitQuantifier()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitQuantifier (RegExpQuantifier * node, void *) [inline], [override], [private]
Definition at line 1024 of file experimental-compiler.cc.
                                                                {
    // If the quantifier must match nothing, we do not produce its body, but
    // still need the `SET_QUANTIFIER_TO_CLOCK` for the Nfa to be able to
    // correctly determine the number of quantifiers.
    if (v8_flags.experimental_regexp_engine_capture_group_opt &&
        node->max() == 0) {
      if (!node->CaptureRegisters().is_empty()) {
        assembler_.SetQuantifierToClock(RemapQuantifier(node->index()));
      }
      return nullptr;
    }
    // Emit the body, but clear registers occurring in body first.
    //
    // TODO(mbid,v8:10765): It's not always necessary to a) capture registers
    // and b) clear them. For example, we don't have to capture anything for
    // the first 4 repetitions if node->min() >= 5, and then we don't have to
    // clear registers in the first node->min() repetitions.
    // Later, and if node->min() == 0, we don't have to clear registers before
    // the first optional repetition.
    Interval body_registers = node->body()->CaptureRegisters();
    auto emit_body = [&]() {
      if (v8_flags.experimental_regexp_engine_capture_group_opt) {
        assembler_.SetQuantifierToClock(RemapQuantifier(node->index()));
      } else {
        ClearRegisters(body_registers);
      }
      node->body()->Accept(this, nullptr);
    };
    bool can_be_reduced_to_non_nullable_plus =
        node->min() > 0 && node->max() == RegExpTree::kInfinity &&
        node->min_match() > 0;
    if (can_be_reduced_to_non_nullable_plus) {
      // Compile <body>+ with an optimization allowing linear sized bytecode in
      // the case of nested pluses. Repetitions with infinite upperbound like
      // <body>{n,}, with n != 0, are compiled into <body>{n-1}<body+>, avoiding
      // one repetition, compared to <body>{n}<body>*.
      // Compile the mandatory repetitions. We repeat `min() - 1` times, such
      // that the last repetition, compiled later, can be reused in a loop.
      for (int i = 0; i < node->min() - 1; ++i) {
        emit_body();
      }
      // Compile the optional repetitions, using an optimized plus when
      // possible.
      switch (node->quantifier_type()) {
        case RegExpQuantifier::POSSESSIVE:
          UNREACHABLE();
        case RegExpQuantifier::GREEDY: {
          // Compile both last mandatory repetition and optional ones.
          CompileNonNullableGreedyPlus(emit_body);
          break;
        }
        case RegExpQuantifier::NON_GREEDY: {
          // Compile both last mandatory repetition and optional ones.
          CompileNonNullableNonGreedyPlus(emit_body);
          break;
        }
      }
    } else {
      // Compile <body>+ into <body><body>*, and <body>{n,}, with n != 0, into
      // <body>{n}<body>*.
      // Compile the first `min()` repetitions.
      for (int i = 0; i < node->min(); ++i) {
        emit_body();
      }
      // Compile the optional repetitions, using stars or repetitions.
      switch (node->quantifier_type()) {
        case RegExpQuantifier::POSSESSIVE:
          UNREACHABLE();
        case RegExpQuantifier::GREEDY: {
          if (node->max() == RegExpTree::kInfinity) {
            CompileGreedyStar(emit_body);
          } else {
            DCHECK_NE(node->max(), RegExpTree::kInfinity);
            CompileGreedyRepetition(emit_body, node->max() - node->min());
          }
          break;
        }
        case RegExpQuantifier::NON_GREEDY: {
          if (node->max() == RegExpTree::kInfinity) {
            CompileNonGreedyStar(emit_body);
          } else {
            DCHECK_NE(node->max(), RegExpTree::kInfinity);
            CompileNonGreedyRepetition(emit_body, node->max() - node->min());
          }
          break;
        }
      }
    }
    return nullptr;
  }
References v8::internal::RegExpTree::Accept(), v8::internal::RegExpQuantifier::body(), v8::internal::RegExpTree::CaptureRegisters(), v8::internal::RegExpQuantifier::CaptureRegisters(), DCHECK_NE, v8::internal::RegExpQuantifier::GREEDY, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::RegExpQuantifier::index(), v8::internal::Interval::is_empty(), v8::internal::RegExpTree::kInfinity, v8::internal::RegExpQuantifier::max(), v8::internal::RegExpQuantifier::min(), v8::internal::RegExpQuantifier::min_match(), v8::internal::RegExpQuantifier::NON_GREEDY, v8::internal::RegExpQuantifier::POSSESSIVE, v8::internal::RegExpQuantifier::quantifier_type(), v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
VisitText()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitText (RegExpText * node, void *) [inline], [override], [private]
Definition at line 1165 of file experimental-compiler.cc.
                                                    {
    if (reverse_) {
      ZoneList<TextElement>* elements = node->elements();
      for (int i = elements->length() - 1; i >= 0; --i) {
        elements->at(i).tree()->Accept(this, nullptr);
      }
    } else {
      for (TextElement& text_el : *node->elements()) {
        text_el.tree()->Accept(this, nullptr);
      }
    }
    return nullptr;
  }
References v8::internal::ZoneList< T >::at(), v8::internal::RegExpText::elements(), and v8::internal::ZoneList< T >::length().
Member Data Documentation
assembler_
BytecodeAssembler v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::assembler_ [private]
Definition at line 1210 of file experimental-compiler.cc.
Referenced by Compile().
ignore_captures_
bool v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::ignore_captures_ [private]
Definition at line 1216 of file experimental-compiler.cc.
ignore_lookarounds_
bool v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::ignore_lookarounds_ [private]
Definition at line 1222 of file experimental-compiler.cc.
lookaround_id_remapping_
ZoneMap<int, int> v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::lookaround_id_remapping_ [private]
Definition at line 1208 of file experimental-compiler.cc.
Referenced by Compile().
lookarounds_
ZoneLinkedList<RegExpLookaround*> v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::lookarounds_ [private]
Definition at line 1205 of file experimental-compiler.cc.
Referenced by Compile().
quantifier_id_remapping_
std::optional<ZoneMap<int, int> > v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::quantifier_id_remapping_ [private]
Definition at line 1207 of file experimental-compiler.cc.
Referenced by Compile().
reverse_
bool v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::reverse_ [private]
Definition at line 1211 of file experimental-compiler.cc.
zone_
Zone* v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::zone_ [private]
Definition at line 1201 of file experimental-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/experimental/experimental-compiler.cc