v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits > Class Template Reference
Static Public Member Functions
static void SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value)
static void SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value)
static void SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, WriteBarrierMode mode)
static Tagged< Object > GetRaw (Tagged< FixedArray > backing_store, InternalIndex entry)
static void CopyElementsImpl (Isolate *isolate, Tagged< FixedArrayBase > from, uint32_t from_start, Tagged< FixedArrayBase > to, ElementsKind from_kind, uint32_t to_start, int packed_size, int copy_size)
static Maybe< bool > CollectValuesOrEntriesImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > values_or_entries, bool get_entries, int *nof_items, PropertyFilter filter)
static Maybe< int64_t > IndexOfValueImpl (Isolate *isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > search_value, size_t start_from, size_t length)
Additional Inherited Members
Detailed Description
template<typename Subclass, typename KindTraits>
class v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >
Definition at line 2705 of file elements.cc.
Member Function Documentation
CollectValuesOrEntriesImpl()
template<typename Subclass , typename KindTraits >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::CollectValuesOrEntriesImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArray > values_or_entries, bool get_entries, int * nof_items, PropertyFilter filter) [inline], [static]
Definition at line 2784 of file elements.cc.
                                             {
    int count = 0;
    if (get_entries) {
      // Collecting entries needs to allocate, so this code must be handlified.
      DirectHandle<FixedArray> elements(Cast<FixedArray>(object->elements()),
                                        isolate);
      uint32_t length = elements->length();
      for (uint32_t index = 0; index < length; ++index) {
        InternalIndex entry(index);
        if (!Subclass::HasEntryImpl(isolate, *elements, entry)) continue;
        DirectHandle<Object> value =
            Subclass::GetImpl(isolate, *elements, entry);
        value = MakeEntryPair(isolate, index, value);
        values_or_entries->set(count++, *value);
      }
    } else {
      // No allocations here, so we can avoid handlification overhead.
      DisallowGarbageCollection no_gc;
      Tagged<FixedArray> elements = Cast<FixedArray>(object->elements());
      uint32_t length = elements->length();
      for (uint32_t index = 0; index < length; ++index) {
        InternalIndex entry(index);
        if (!Subclass::HasEntryImpl(isolate, elements, entry)) continue;
        Tagged<Object> value = GetRaw(elements, entry);
        values_or_entries->set(count++, value);
      }
    }
    *nof_items = count;
    return Just(true);
  }
References v8::internal::index, v8::Just(), v8::internal::length, v8::internal::MakeEntryPair(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
CopyElementsImpl()
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::CopyElementsImpl (Isolate * isolate, Tagged< FixedArrayBase > from, uint32_t from_start, Tagged< FixedArrayBase > to, ElementsKind from_kind, uint32_t to_start, int packed_size, int copy_size) [inline], [static]
Definition at line 2734 of file elements.cc.
                                                               {
    DisallowGarbageCollection no_gc;
    ElementsKind to_kind = KindTraits::Kind;
    switch (from_kind) {
      case PACKED_SMI_ELEMENTS:
      case HOLEY_SMI_ELEMENTS:
      case PACKED_ELEMENTS:
      case PACKED_FROZEN_ELEMENTS:
      case PACKED_SEALED_ELEMENTS:
      case PACKED_NONEXTENSIBLE_ELEMENTS:
      case HOLEY_ELEMENTS:
      case HOLEY_FROZEN_ELEMENTS:
      case HOLEY_SEALED_ELEMENTS:
      case HOLEY_NONEXTENSIBLE_ELEMENTS:
      case SHARED_ARRAY_ELEMENTS:
        CopyObjectToObjectElements(isolate, from, from_kind, from_start, to,
                                   to_kind, to_start, copy_size);
        break;
      case PACKED_DOUBLE_ELEMENTS:
      case HOLEY_DOUBLE_ELEMENTS: {
        AllowGarbageCollection allow_allocation;
        DCHECK(IsObjectElementsKind(to_kind));
        CopyDoubleToObjectElements(isolate, from, from_start, to, to_start,
                                   copy_size);
        break;
      }
      case DICTIONARY_ELEMENTS:
        CopyDictionaryToObjectElements(isolate, from, from_start, to, to_kind,
                                       to_start, copy_size);
        break;
      case FAST_SLOPPY_ARGUMENTS_ELEMENTS:
      case SLOW_SLOPPY_ARGUMENTS_ELEMENTS:
      case FAST_STRING_WRAPPER_ELEMENTS:
      case SLOW_STRING_WRAPPER_ELEMENTS:
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) case TYPE##_ELEMENTS:
        TYPED_ARRAYS(TYPED_ARRAY_CASE)
        RAB_GSAB_TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
      case WASM_ARRAY_ELEMENTS:
        // This function is currently only used for JSArrays with non-zero
        // length.
        UNREACHABLE();
      case NO_ELEMENTS:
        break; // Nothing to do.
    }
  }
References v8::internal::anonymous_namespace{elements.cc}::CopyDictionaryToObjectElements(), v8::internal::anonymous_namespace{elements.cc}::CopyDoubleToObjectElements(), v8::internal::anonymous_namespace{elements.cc}::CopyObjectToObjectElements(), v8::internal::DCHECK(), v8::internal::DICTIONARY_ELEMENTS, v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::FAST_STRING_WRAPPER_ELEMENTS, v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_FROZEN_ELEMENTS, v8::internal::HOLEY_NONEXTENSIBLE_ELEMENTS, v8::internal::HOLEY_SEALED_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::IsObjectElementsKind(), v8::internal::NO_ELEMENTS, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_FROZEN_ELEMENTS, v8::internal::PACKED_NONEXTENSIBLE_ELEMENTS, v8::internal::PACKED_SEALED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, RAB_GSAB_TYPED_ARRAYS, v8::internal::SHARED_ARRAY_ELEMENTS, v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, TYPED_ARRAY_CASE, TYPED_ARRAYS, v8::internal::UNREACHABLE(), and v8::internal::WASM_ARRAY_ELEMENTS.
GetRaw()
template<typename Subclass , typename KindTraits >
static Tagged<Object> v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::GetRaw (Tagged< FixedArray > backing_store, InternalIndex entry) [inline], [static]
Definition at line 2724 of file elements.cc.
                                                    {
    return backing_store->get(entry.as_int());
  }
References v8::internal::InternalIndex::as_int().
IndexOfValueImpl()
template<typename Subclass , typename KindTraits >
static Maybe<int64_t> v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::IndexOfValueImpl (Isolate * isolate, DirectHandle< JSObject > receiver, DirectHandle< Object > search_value, size_t start_from, size_t length) [inline], [static]
Definition at line 2818 of file elements.cc.
                                                                           {
    DCHECK(JSObject::PrototypeHasNoElements(isolate, *receiver));
    DisallowGarbageCollection no_gc;
    Tagged<FixedArrayBase> elements_base = receiver->elements();
    Tagged<Object> value = *search_value;
    if (start_from >= length) return Just<int64_t>(-1);
    length = std::min(static_cast<size_t>(elements_base->length()), length);
    // Only FAST_{,HOLEY_}ELEMENTS can store non-numbers.
    if (!IsNumber(value) && !IsObjectElementsKind(Subclass::kind()) &&
        !IsAnyNonextensibleElementsKind(Subclass::kind())) {
      return Just<int64_t>(-1);
    }
    // NaN can never be found by strict equality.
    if (IsNaN(value)) return Just<int64_t>(-1);
    // k can be greater than receiver->length() below, but it is bounded by
    // elements_base->length() so we never read out of bounds. This means that
    // elements->get(k) can return the hole, for which the StrictEquals will
    // always fail.
    Tagged<FixedArray> elements = Cast<FixedArray>(receiver->elements());
    static_assert(FixedArray::kMaxLength <=
                  std::numeric_limits<uint32_t>::max());
    for (size_t k = start_from; k < length; ++k) {
      if (Object::StrictEquals(value,
                               elements->get(static_cast<uint32_t>(k)))) {
        return Just<int64_t>(k);
      }
    }
    return Just<int64_t>(-1);
  }
References v8::internal::DCHECK(), v8::internal::IsAnyNonextensibleElementsKind(), v8::internal::IsNaN(), v8::internal::IsNumber(), v8::internal::IsObjectElementsKind(), v8::internal::FixedArray::kMaxLength, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::JSObject::PrototypeHasNoElements(), v8::internal::Object::StrictEquals(), and v8::internal::value.
SetImpl() [1/3]
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value) [inline], [static]
Definition at line 2708 of file elements.cc.
                                                   {
    SetImpl(holder->elements(), entry, value);
  }
References v8::internal::value.
SetImpl() [2/3]
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value) [inline], [static]
Definition at line 2713 of file elements.cc.
                                                                        {
    Cast<FixedArray>(backing_store)->set(entry.as_int(), value);
  }
References v8::internal::InternalIndex::as_int(), and v8::internal::value.
SetImpl() [3/3]
template<typename Subclass , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::FastSmiOrObjectElementsAccessor< Subclass, KindTraits >::SetImpl (Tagged< FixedArrayBase > backing_store, InternalIndex entry, Tagged< Object > value, WriteBarrierMode mode) [inline], [static]
Definition at line 2718 of file elements.cc.
                                                    {
    Cast<FixedArray>(backing_store)->set(entry.as_int(), value, mode);
  }
References v8::internal::InternalIndex::as_int(), mode(), and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/elements.cc