v8::internal::DebugEvaluate::ContextBuilder Class Reference
Classes
struct ContextChainElement
Public Member Functions
ContextBuilder (Isolate *isolate, JavaScriptFrame *frame, int inlined_jsframe_index)
void UpdateValues ()
DirectHandle< Context > evaluation_context () const
DirectHandle< SharedFunctionInfo > outer_info () const
Private Attributes
Handle< Context > evaluation_context_
std::vector< ContextChainElement > context_chain_
Isolate * isolate_
FrameInspector frame_inspector_
ScopeIterator scope_iterator_
Detailed Description
Definition at line 77 of file debug-evaluate.h.
Constructor & Destructor Documentation
ContextBuilder()
v8::internal::DebugEvaluate::ContextBuilder::ContextBuilder (Isolate * isolate, JavaScriptFrame * frame, int inlined_jsframe_index)
Definition at line 201 of file debug-evaluate.cc.
    : isolate_(isolate),
      frame_inspector_(frame, inlined_jsframe_index, isolate),
      scope_iterator_(isolate, &frame_inspector_,
                      ScopeIterator::ReparseStrategy::kScriptIfNeeded) {
  Handle<Context> outer_context(frame_inspector_.GetFunction()->context(),
                                isolate);
  evaluation_context_ = outer_context;
  Factory* factory = isolate->factory();
  if (scope_iterator_.Done()) return;
  // To evaluate as if we were running eval at the point of the debug break,
  // we reconstruct the context chain as follows:
  // - To make stack-allocated variables visible, we materialize them and
  // use a debug-evaluate context to wrap both the materialized object and
  // the original context.
  // - Each scope from the break position up to the function scope is wrapped
  // in a debug-evaluate context.
  // - Between the function scope and the native context, we only resolve
  // variable names that are guaranteed to not be shadowed by stack-allocated
  // variables. ScopeInfos between the function scope and the native
  // context have a blocklist attached to implement that.
  // - The various block lists are calculated by the ScopeIterator during
  // iteration.
  // Context::Lookup has special handling for debug-evaluate contexts:
  // - Look up in the materialized stack variables.
  // - Look up in the original context.
  // - Once we have seen a debug-evaluate context we start to take the
  // block lists into account before moving up the context chain.
  for (; scope_iterator_.InInnerScope(); scope_iterator_.Next()) {
    ScopeIterator::ScopeType scope_type = scope_iterator_.Type();
    if (scope_type == ScopeIterator::ScopeTypeScript) break;
    ContextChainElement context_chain_element;
    if (scope_type == ScopeIterator::ScopeTypeLocal ||
        scope_iterator_.DeclaresLocals(ScopeIterator::Mode::STACK)) {
      context_chain_element.materialized_object =
          scope_iterator_.ScopeObject(ScopeIterator::Mode::STACK);
    }
    if (scope_iterator_.HasContext()) {
      context_chain_element.wrapped_context = scope_iterator_.CurrentContext();
    }
    context_chain_.push_back(context_chain_element);
  }
  DirectHandle<ScopeInfo> scope_info =
      IsNativeContext(*evaluation_context_)
          ? DirectHandle<ScopeInfo>::null()
          : direct_handle(evaluation_context_->scope_info(), isolate);
  for (auto rit = context_chain_.rbegin(); rit != context_chain_.rend();
       rit++) {
    ContextChainElement element = *rit;
    scope_info = ScopeInfo::CreateForWithScope(isolate, scope_info);
    scope_info->SetIsDebugEvaluateScope();
    // In the case where the "paused function scope" is the script scope
    // itself, we don't need (and don't have) a blocklist.
    const bool paused_scope_is_script_scope =
        scope_iterator_.Done() || scope_iterator_.InInnerScope();
    if (rit == context_chain_.rbegin() && !paused_scope_is_script_scope) {
      // The DebugEvaluateContext we create for the closure scope is the only
      // DebugEvaluateContext with a block list. This means we'll retrieve
      // the existing block list from the paused function scope
      // and also associate the temporary scope_info we create here with that
      // blocklist.
      DirectHandle<ScopeInfo> function_scope_info(
          frame_inspector_.GetFunction()->shared()->scope_info(), isolate_);
      DirectHandle<Object> block_list(
          isolate_->LocalsBlockListCacheGet(function_scope_info), isolate_);
      CHECK(IsStringSet(*block_list));
      isolate_->LocalsBlockListCacheSet(scope_info, Handle<ScopeInfo>::null(),
                                        Cast<StringSet>(block_list));
    }
    evaluation_context_ = factory->NewDebugEvaluateContext(
        evaluation_context_, scope_info, element.materialized_object,
        element.wrapped_context);
  }
}
References CHECK, context_chain_, v8::internal::ScopeInfo::CreateForWithScope(), v8::internal::ScopeIterator::CurrentContext(), v8::internal::ScopeIterator::DeclaresLocals(), v8::internal::direct_handle(), v8::internal::ScopeIterator::Done(), evaluation_context_, v8::internal::Isolate::factory(), frame_inspector_, v8::internal::FrameInspector::GetFunction(), v8::internal::ScopeIterator::HasContext(), v8::internal::ScopeIterator::InInnerScope(), isolate_, v8::internal::Isolate::LocalsBlockListCacheGet(), v8::internal::Isolate::LocalsBlockListCacheSet(), v8::internal::DebugEvaluate::ContextBuilder::ContextChainElement::materialized_object, v8::internal::Factory::NewDebugEvaluateContext(), v8::internal::ScopeIterator::Next(), v8::internal::DirectHandle< T >::null(), scope_iterator_, v8::internal::ScopeIterator::ScopeObject(), v8::internal::ScopeIterator::ScopeTypeLocal, v8::internal::ScopeIterator::ScopeTypeScript, v8::internal::ScopeIterator::STACK, v8::internal::ScopeIterator::Type(), and v8::internal::DebugEvaluate::ContextBuilder::ContextChainElement::wrapped_context.
Member Function Documentation
evaluation_context()
DirectHandle<Context> v8::internal::DebugEvaluate::ContextBuilder::evaluation_context () const [inline]
Definition at line 84 of file debug-evaluate.h.
                                                     {
      return evaluation_context_;
    }
References evaluation_context_.
Referenced by v8::internal::DebugEvaluate::Local().
outer_info()
DirectHandle< SharedFunctionInfo > v8::internal::DebugEvaluate::ContextBuilder::outer_info () const
Definition at line 196 of file debug-evaluate.cc.
          {
  return direct_handle(frame_inspector_.GetFunction()->shared(), isolate_);
}
References v8::internal::direct_handle(), frame_inspector_, v8::internal::FrameInspector::GetFunction(), and isolate_.
Referenced by v8::internal::DebugEvaluate::Local().
UpdateValues()
void v8::internal::DebugEvaluate::ContextBuilder::UpdateValues ()
Definition at line 283 of file debug-evaluate.cc.
                                               {
  scope_iterator_.Restart();
  for (ContextChainElement& element : context_chain_) {
    if (!element.materialized_object.is_null()) {
      DirectHandle<FixedArray> keys =
          KeyAccumulator::GetKeys(isolate_, element.materialized_object,
                                  KeyCollectionMode::kOwnOnly,
                                  ENUMERABLE_STRINGS)
              .ToHandleChecked();
      for (int i = 0; i < keys->length(); i++) {
        DCHECK(IsString(keys->get(i)));
        Handle<String> key(Cast<String>(keys->get(i)), isolate_);
        DirectHandle<Object> value = JSReceiver::GetDataProperty(
            isolate_, element.materialized_object, key);
        scope_iterator_.SetVariableValue(key, value);
      }
    }
    scope_iterator_.Next();
  }
}
References v8::internal::DCHECK(), v8::internal::ENUMERABLE_STRINGS, v8::internal::JSReceiver::GetDataProperty(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::key, v8::internal::kOwnOnly, and v8::internal::value.
Referenced by v8::internal::DebugEvaluate::Local().
Member Data Documentation
context_chain_
std::vector<ContextChainElement> v8::internal::DebugEvaluate::ContextBuilder::context_chain_ [private]
Definition at line 97 of file debug-evaluate.h.
Referenced by ContextBuilder().
evaluation_context_
Handle<Context> v8::internal::DebugEvaluate::ContextBuilder::evaluation_context_ [private]
Definition at line 96 of file debug-evaluate.h.
Referenced by ContextBuilder(), and evaluation_context().
frame_inspector_
FrameInspector v8::internal::DebugEvaluate::ContextBuilder::frame_inspector_ [private]
Definition at line 99 of file debug-evaluate.h.
Referenced by ContextBuilder(), and outer_info().
isolate_
Isolate* v8::internal::DebugEvaluate::ContextBuilder::isolate_ [private]
Definition at line 98 of file debug-evaluate.h.
Referenced by ContextBuilder(), and outer_info().
scope_iterator_
ScopeIterator v8::internal::DebugEvaluate::ContextBuilder::scope_iterator_ [private]
Definition at line 100 of file debug-evaluate.h.
Referenced by ContextBuilder().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-evaluate.h
/mnt/V8SourceCode/src/debug/debug-evaluate.cc