v8::internal::SerializerDeserializer Class Reference
#include <serializer-deserializer.h>
Classes
struct BytecodeValueEncoder
struct VariableRepeatRootCount
Static Public Member Functions
static void IterateStartupObjectCache (Isolate *isolate, RootVisitor *visitor)
static void IterateSharedHeapObjectCache (Isolate *isolate, RootVisitor *visitor)
Protected Types
enum class SlotType { kAnySlot
, kMapSlot
 }
enum Bytecode : uint8_t {
kNewObject = 0x00
, kBackref = 0x04
, kReadOnlyHeapRef
, kStartupObjectCache
,
kRootArray
, kAttachedReference
, kSharedHeapObjectCache
, kNop
,
kSynchronize
, kVariableRepeatRoot
, kOffHeapBackingStore
, kOffHeapResizableBackingStore
,
kEmbedderFieldsData
, kApiWrapperFieldsData
, kVariableRawData
, kApiReference
,
kExternalReference
, kSandboxedApiReference
, kSandboxedExternalReference
, kSandboxedRawExternalReference
,
kClearedWeakReference
, kWeakPrefix
, kRegisterPendingForwardRef
, kResolvePendingForwardRef
,
kNewContextlessMetaMap
, kNewContextfulMetaMap
, kIndirectPointerPrefix
, kInitializeSelfIndirectPointer
,
kAllocateJSDispatchEntry
, kJSDispatchEntry
, kProtectedPointerPrefix
, kRootArrayConstants = 0x40
,
kFixedRawData = 0x60
, kFixedRepeatRoot = 0x80
, kHotObject = 0x90
 }
template<Bytecode bytecode>
using SpaceEncoder = BytecodeValueEncoder< bytecode, 0, kNumberOfSnapshotSpaces - 1, SnapshotSpace >
using NewObject = SpaceEncoder< kNewObject >
using FixedRawDataWithSize = BytecodeValueEncoder< kFixedRawData, kFirstEncodableFixedRawDataSize, kLastEncodableFixedRawDataSize >
using FixedRepeatRootWithCount = BytecodeValueEncoder< kFixedRepeatRoot, kFirstEncodableRepeatRootCount, kLastEncodableFixedRepeatRootCount >
using RootArrayConstant = BytecodeValueEncoder< kRootArrayConstants, 0, kRootArrayConstantsCount - 1, RootIndex >
using HotObject = BytecodeValueEncoder< kHotObject, 0, kHotObjectCount - 1 >
Protected Member Functions
void RestoreExternalReferenceRedirector (Isolate *isolate, Tagged< AccessorInfo > accessor_info)
void RestoreExternalReferenceRedirector (Isolate *isolate, Tagged< FunctionTemplateInfo > function_template_info)
Static Protected Member Functions
static bool CanBeDeferred (Tagged< HeapObject > o, SlotType slot_type)
Static Protected Attributes
static const int kRootArrayConstantsCount = 0x20
static const int kFixedRawDataCount = 0x20
static const int kFixedRepeatRootCount = 0x10
static const int kHotObjectCount = 8
static const int kDoubleAlignmentSentinel = 0
static const int kFirstEncodableFixedRawDataSize = 1
static const int kLastEncodableFixedRawDataSize
static const int kFirstEncodableRepeatRootCount = 2
static const int kLastEncodableFixedRepeatRootCount
static const int kFirstEncodableVariableRepeatRootCount
static const uint32_t kEmptyBackingStoreRefSentinel = 0
Additional Inherited Members
Detailed Description
Definition at line 19 of file serializer-deserializer.h.
Member Typedef Documentation
FixedRawDataWithSize
using v8::internal::SerializerDeserializer::FixedRawDataWithSize = BytecodeValueEncoder<kFixedRawData, kFirstEncodableFixedRawDataSize, kLastEncodableFixedRawDataSize> [protected]
Definition at line 242 of file serializer-deserializer.h.
FixedRepeatRootWithCount
using v8::internal::SerializerDeserializer::FixedRepeatRootWithCount = BytecodeValueEncoder<kFixedRepeatRoot, kFirstEncodableRepeatRootCount, kLastEncodableFixedRepeatRootCount> [protected]
Definition at line 253 of file serializer-deserializer.h.
HotObject
using v8::internal::SerializerDeserializer::HotObject = BytecodeValueEncoder<kHotObject, 0, kHotObjectCount - 1> [protected]
Definition at line 277 of file serializer-deserializer.h.
NewObject
using v8::internal::SerializerDeserializer::NewObject = SpaceEncoder<kNewObject> [protected]
Definition at line 228 of file serializer-deserializer.h.
RootArrayConstant
using v8::internal::SerializerDeserializer::RootArrayConstant = BytecodeValueEncoder<kRootArrayConstants, 0, kRootArrayConstantsCount - 1, RootIndex> [protected]
Definition at line 274 of file serializer-deserializer.h.
SpaceEncoder
template<Bytecode bytecode>
using v8::internal::SerializerDeserializer::SpaceEncoder = BytecodeValueEncoder<bytecode, 0, kNumberOfSnapshotSpaces - 1, SnapshotSpace> [protected]
Definition at line 224 of file serializer-deserializer.h.
Member Enumeration Documentation
Bytecode
enum v8::internal::SerializerDeserializer::Bytecode : uint8_t [protected]
Enumerator
kNewObject
kBackref
kReadOnlyHeapRef
kStartupObjectCache
kRootArray
kAttachedReference
kSharedHeapObjectCache
kNop
kSynchronize
kVariableRepeatRoot
kOffHeapBackingStore
kOffHeapResizableBackingStore
kEmbedderFieldsData
kApiWrapperFieldsData
kVariableRawData
kApiReference
kExternalReference
kSandboxedApiReference
kSandboxedExternalReference
kSandboxedRawExternalReference
kClearedWeakReference
kWeakPrefix
kRegisterPendingForwardRef
kResolvePendingForwardRef
kNewContextlessMetaMap
kNewContextfulMetaMap
kIndirectPointerPrefix
kInitializeSelfIndirectPointer
kAllocateJSDispatchEntry
kJSDispatchEntry
kProtectedPointerPrefix
kRootArrayConstants
kFixedRawData
kFixedRepeatRoot
kHotObject
Definition at line 84 of file serializer-deserializer.h.
                : uint8_t {
    //
    // ---------- byte code range 0x00..0x1f ----------
    //
    // 0x00..0x03 Allocate new object, in specified space.
    kNewObject = 0x00,
    // Reference to previously allocated object.
    kBackref = 0x04,
    // Reference to an object in the read only heap.
    kReadOnlyHeapRef,
    // Object in the startup object cache.
    kStartupObjectCache,
    // Root array item.
    kRootArray,
    // Object provided in the attached list.
    kAttachedReference,
    // Object in the shared heap object cache.
    kSharedHeapObjectCache,
    // Do nothing, used for padding.
    kNop,
    // A tag emitted at strategic points in the snapshot to delineate sections.
    // If the deserializer does not find these at the expected moments then it
    // is an indication that the snapshot and the VM do not fit together.
    // Examine the build process for architecture, version or configuration
    // mismatches.
    kSynchronize,
    // Repeats of variable length of a root.
    kVariableRepeatRoot,
    // Used for embedder-allocated backing stores for TypedArrays.
    kOffHeapBackingStore,
    kOffHeapResizableBackingStore,
    // Used for embedder-provided serialization data for embedder fields.
    kEmbedderFieldsData,
    // Used for embedder-provided serialziation data for API wrappers.
    kApiWrapperFieldsData,
    // Raw data of variable length.
    kVariableRawData,
    // Used to encode external references provided through the API.
    kApiReference,
    // External reference referenced by id.
    kExternalReference,
    // Same as three bytecodes above but for serializing sandboxed external
    // pointer values.
    // TODO(v8:10391): Remove them once all ExternalPointer usages are
    // sandbox-ready.
    kSandboxedApiReference,
    kSandboxedExternalReference,
    kSandboxedRawExternalReference,
    // In-place weak references.
    kClearedWeakReference,
    kWeakPrefix,
    // Registers the current slot as a "pending" forward reference, to be later
    // filled by a corresponding resolution bytecode.
    kRegisterPendingForwardRef,
    // Resolves an existing "pending" forward reference to point to the current
    // object.
    kResolvePendingForwardRef,
    // Special construction bytecodes for the metamaps. In theory we could
    // reuse forward-references for this, but then the forward reference would
    // be registered during object map deserialization, before the object is
    // allocated, so there wouldn't be a allocated object whose map field we can
    // register as the pending field. We could either hack around this, or
    // simply introduce this new bytecode.
    kNewContextlessMetaMap,
    kNewContextfulMetaMap,
    // When the sandbox is enabled, a prefix indicating that the following
    // object is referenced through an indirect pointer, i.e. through an entry
    // in a pointer table.
    kIndirectPointerPrefix,
    // When the sandbox is enabled, this bytecode instructs the deserializer to
    // initialize the "self" indirect pointer of trusted objects, which
    // references the object's pointer table entry. As the "self" indirect
    // pointer is always the first field after the map word, it is guaranteed
    // that it will be deserialized before any inner objects, which may require
    // the pointer table entry for back reference to the trusted object.
    kInitializeSelfIndirectPointer,
    // This bytecode instructs the deserializer to allocate an entry in the
    // JSDispatchTable for the host object and store the corresponding dispatch
    // handle into the current slot.
    kAllocateJSDispatchEntry,
    // A back-reference to the already allocated n-th dispatch entry.
    kJSDispatchEntry,
    // A prefix indicating that the following object is referenced through a
    // protected pointer, i.e. a pointer from one trusted object to another.
    kProtectedPointerPrefix,
    //
    // ---------- byte code range 0x40..0x7f ----------
    //
    // 0x40..0x5f
    kRootArrayConstants = 0x40,
    // 0x60..0x7f
    kFixedRawData = 0x60,
    //
    // ---------- byte code range 0x80..0x9f ----------
    //
    // 0x80..0x8f
    kFixedRepeatRoot = 0x80,
    // 0x90..0x97
    kHotObject = 0x90,
  };
SlotType
enum v8::internal::SerializerDeserializer::SlotType [strong], [protected]
Enumerator
kAnySlot
kMapSlot
Definition at line 27 of file serializer-deserializer.h.
                      {
    kAnySlot,
    kMapSlot,
  };
Member Function Documentation
CanBeDeferred()
bool v8::internal::SerializerDeserializer::CanBeDeferred (Tagged< HeapObject > o, SlotType slot_type) [static], [protected]
Definition at line 48 of file serializer-deserializer.cc.
                                                               {
  // HeapObjects' map slots cannot be deferred as objects are expected to have a
  // valid map immediately.
  if (slot_type == SlotType::kMapSlot) {
    DCHECK(IsMap(o));
    return false;
  }
  // * Internalized strings cannot be deferred as they might be
  // converted to thin strings during post processing, at which point forward
  // references to the now-thin string will already have been written.
  // * JS objects with embedder fields cannot be deferred because the
  // serialize/deserialize callbacks need the back reference immediately to
  // identify the object.
  // * ByteArray cannot be deferred as JSTypedArray needs the base_pointer
  // ByteArray immediately if it's on heap.
  // * Non-empty EmbdderDataArrays cannot be deferred because the serialize
  // and deserialize callbacks need the back reference immediately to
  // identify the object.
  // TODO(leszeks): Could we defer string serialization if forward references
  // were resolved after object post processing?
  return !IsInternalizedString(o) &&
         !(IsJSObject(o) && Cast<JSObject>(o)->GetEmbedderFieldCount() > 0) &&
         !IsByteArray(o) &&
         !(IsEmbedderDataArray(o) && Cast<EmbedderDataArray>(o)->length() > 0);
}
References v8::internal::DCHECK(), v8::internal::InstanceTypeChecker::IsInternalizedString(), and kMapSlot.
Referenced by v8::internal::Serializer::RegisterObjectIsPending(), and v8::internal::Serializer::ObjectSerializer::Serialize().
IterateSharedHeapObjectCache()
void v8::internal::SerializerDeserializer::IterateSharedHeapObjectCache (Isolate * isolate, RootVisitor * visitor) [static]
Definition at line 42 of file serializer-deserializer.cc.
                                            {
  IterateObjectCache(isolate, isolate->shared_heap_object_cache(),
                     Root::kSharedHeapObjectCache, visitor);
}
References v8::internal::anonymous_namespace{serializer-deserializer.cc}::IterateObjectCache(), and v8::internal::Isolate::shared_heap_object_cache().
Referenced by v8::internal::SharedHeapDeserializer::DeserializeIntoIsolate(), and v8::internal::Heap::IterateRoots().
IterateStartupObjectCache()
void v8::internal::SerializerDeserializer::IterateStartupObjectCache (Isolate * isolate, RootVisitor * visitor) [static]
Definition at line 36 of file serializer-deserializer.cc.
                                                                             {
  IterateObjectCache(isolate, isolate->startup_object_cache(),
                     Root::kStartupObjectCache, visitor);
}
References v8::internal::anonymous_namespace{serializer-deserializer.cc}::IterateObjectCache(), and v8::internal::Isolate::startup_object_cache().
Referenced by v8::internal::StartupDeserializer::DeserializeIntoIsolate(), and v8::internal::Heap::IterateRoots().
RestoreExternalReferenceRedirector() [1/2]
void v8::internal::SerializerDeserializer::RestoreExternalReferenceRedirector (Isolate * isolate, Tagged< AccessorInfo > accessor_info) [protected]
Definition at line 75 of file serializer-deserializer.cc.
                                                          {
  DisallowGarbageCollection no_gc;
  accessor_info->init_getter_redirection(isolate);
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::StartupDeserializer::DeserializeIntoIsolate(), and v8::internal::StartupSerializer::~StartupSerializer().
RestoreExternalReferenceRedirector() [2/2]
void v8::internal::SerializerDeserializer::RestoreExternalReferenceRedirector (Isolate * isolate, Tagged< FunctionTemplateInfo > function_template_info) [protected]
Definition at line 81 of file serializer-deserializer.cc.
                                                                           {
  DisallowGarbageCollection no_gc;
  function_template_info->init_callback_redirection(isolate);
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Member Data Documentation
kDoubleAlignmentSentinel
const int v8::internal::SerializerDeserializer::kDoubleAlignmentSentinel = 0 [static], [protected]
Definition at line 235 of file serializer-deserializer.h.
kEmptyBackingStoreRefSentinel
const uint32_t v8::internal::SerializerDeserializer::kEmptyBackingStoreRefSentinel = 0 [static], [protected]
Definition at line 281 of file serializer-deserializer.h.
Referenced by v8::internal::Deserializer< IsolateT >::Deserializer(), and v8::internal::Serializer::ObjectSerializer::SerializeJSArrayBuffer().
kFirstEncodableFixedRawDataSize
const int v8::internal::SerializerDeserializer::kFirstEncodableFixedRawDataSize = 1 [static], [protected]
Definition at line 238 of file serializer-deserializer.h.
kFirstEncodableRepeatRootCount
const int v8::internal::SerializerDeserializer::kFirstEncodableRepeatRootCount = 2 [static], [protected]
Definition at line 247 of file serializer-deserializer.h.
kFirstEncodableVariableRepeatRootCount
const int v8::internal::SerializerDeserializer::kFirstEncodableVariableRepeatRootCount [static], [protected]
Initial value:
=
      kLastEncodableFixedRepeatRootCount + 1
Definition at line 250 of file serializer-deserializer.h.
Referenced by v8::internal::SerializerDeserializer::VariableRepeatRootCount::Decode(), v8::internal::SerializerDeserializer::VariableRepeatRootCount::Encode(), and v8::internal::SerializerDeserializer::VariableRepeatRootCount::IsEncodable().
kFixedRawDataCount
const int v8::internal::SerializerDeserializer::kFixedRawDataCount = 0x20 [static], [protected]
Definition at line 77 of file serializer-deserializer.h.
Referenced by v8::internal::Serializer::ObjectSerializer::OutputExternalReference(), and v8::internal::Serializer::ObjectSerializer::OutputRawData().
kFixedRepeatRootCount
const int v8::internal::SerializerDeserializer::kFixedRepeatRootCount = 0x10 [static], [protected]
Definition at line 79 of file serializer-deserializer.h.
kHotObjectCount
const int v8::internal::SerializerDeserializer::kHotObjectCount = 8 [static], [protected]
Definition at line 82 of file serializer-deserializer.h.
Referenced by v8::internal::Serializer::SerializeHotObject().
kLastEncodableFixedRawDataSize
const int v8::internal::SerializerDeserializer::kLastEncodableFixedRawDataSize [static], [protected]
Initial value:
=
      kFirstEncodableFixedRawDataSize + kFixedRawDataCount - 1
Definition at line 239 of file serializer-deserializer.h.
kLastEncodableFixedRepeatRootCount
const int v8::internal::SerializerDeserializer::kLastEncodableFixedRepeatRootCount [static], [protected]
Initial value:
=
      kFirstEncodableRepeatRootCount + kFixedRepeatRootCount - 1
Definition at line 248 of file serializer-deserializer.h.
Referenced by v8::internal::Serializer::PutRepeatRoot().
kRootArrayConstantsCount
const int v8::internal::SerializerDeserializer::kRootArrayConstantsCount = 0x20 [static], [protected]
Definition at line 74 of file serializer-deserializer.h.
Referenced by v8::internal::Serializer::PutRoot().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/serializer-deserializer.h
/mnt/V8SourceCode/src/snapshot/serializer-deserializer.cc