v8::internal::RegExpAssertion Class Reference
#include <regexp-ast.h>
Public Types
enum class Type {
START_OF_LINE = 0
, START_OF_INPUT = 1
, END_OF_LINE = 2
, END_OF_INPUT = 3
,
BOUNDARY = 4
, NON_BOUNDARY = 5
, LAST_ASSERTION_TYPE = NON_BOUNDARY
 }
Public Member Functions
RegExpAssertion (Type type)
DECL_BOILERPLATE (Assertion)
bool IsAnchoredAtStart () override
bool IsAnchoredAtEnd () override
int min_match () override
int max_match () override
Type assertion_type () const
Private Attributes
const Type assertion_type_
Additional Inherited Members
Detailed Description
Definition at line 259 of file regexp-ast.h.
Member Enumeration Documentation
Type
enum v8::internal::RegExpAssertion::Type [strong]
Enumerator
START_OF_LINE
START_OF_INPUT
END_OF_LINE
END_OF_INPUT
BOUNDARY
NON_BOUNDARY
LAST_ASSERTION_TYPE
Definition at line 261 of file regexp-ast.h.
                  {
    START_OF_LINE = 0,
    START_OF_INPUT = 1,
    END_OF_LINE = 2,
    END_OF_INPUT = 3,
    BOUNDARY = 4,
    NON_BOUNDARY = 5,
    LAST_ASSERTION_TYPE = NON_BOUNDARY,
  };
Constructor & Destructor Documentation
RegExpAssertion()
v8::internal::RegExpAssertion::RegExpAssertion (Type type) [inline], [explicit]
Definition at line 270 of file regexp-ast.h.
: assertion_type_(type) {}
Member Function Documentation
assertion_type()
Type v8::internal::RegExpAssertion::assertion_type () const [inline]
Definition at line 278 of file regexp-ast.h.
{ return assertion_type_; }
References assertion_type_.
Referenced by IsAnchoredAtEnd(), IsAnchoredAtStart(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AssertionSequenceRewriter::Rewrite(), and v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::VisitAssertion().
DECL_BOILERPLATE()
v8::internal::RegExpAssertion::DECL_BOILERPLATE (Assertion)
IsAnchoredAtEnd()
bool v8::internal::RegExpAssertion::IsAnchoredAtEnd () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 74 of file regexp-ast.cc.
                                      {
  return assertion_type() == RegExpAssertion::Type::END_OF_INPUT;
}
References assertion_type(), and END_OF_INPUT.
IsAnchoredAtStart()
bool v8::internal::RegExpAssertion::IsAnchoredAtStart () [override], [virtual]
Reimplemented from v8::internal::RegExpTree.
Definition at line 69 of file regexp-ast.cc.
                                        {
  return assertion_type() == RegExpAssertion::Type::START_OF_INPUT;
}
References assertion_type(), and START_OF_INPUT.
max_match()
int v8::internal::RegExpAssertion::max_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 277 of file regexp-ast.h.
{ return 0; }
min_match()
int v8::internal::RegExpAssertion::min_match () [inline], [override], [virtual]
Implements v8::internal::RegExpTree.
Definition at line 276 of file regexp-ast.h.
{ return 0; }
Member Data Documentation
assertion_type_
const Type v8::internal::RegExpAssertion::assertion_type_ [private]
Definition at line 281 of file regexp-ast.h.
Referenced by assertion_type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-ast.h
/mnt/V8SourceCode/src/regexp/regexp-ast.cc