v8::internal::ClientRootVisitor< Visitor > Class Template Reference
#include <visitors.h>
Public Member Functions
ClientRootVisitor (Visitor *actual_visitor)
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) final
void VisitRootPointers (Root root, const char *description, OffHeapObjectSlot start, OffHeapObjectSlot end) final
void VisitRunningCode (FullObjectSlot code_slot, FullObjectSlot maybe_istream_slot) final
void Synchronize (VisitorSynchronization::SyncTag tag) final
Static Private Member Functions
static bool IsSharedHeapObject (Tagged< Object > object)
Private Attributes
Visitor *const actual_visitor_
Additional Inherited Members
Detailed Description
template<typename Visitor = RootVisitor>
class v8::internal::ClientRootVisitor< Visitor >
Definition at line 258 of file visitors.h.
Constructor & Destructor Documentation
ClientRootVisitor()
template<typename Visitor = RootVisitor>
v8::internal::ClientRootVisitor< Visitor >::ClientRootVisitor (Visitor * actual_visitor) [inline], [explicit]
Definition at line 260 of file visitors.h.
      : actual_visitor_(actual_visitor) {}
Member Function Documentation
IsSharedHeapObject()
template<typename Visitor >
bool v8::internal::ClientRootVisitor< Visitor >::IsSharedHeapObject (Tagged< Object > object) [inline], [static], [private]
Definition at line 58 of file visitors-inl.h.
                                                                         {
  return IsHeapObject(object) &&
         HeapLayout::InWritableSharedSpace(Cast<HeapObject>(object));
}
References v8::internal::HeapLayout::InWritableSharedSpace(), and v8::internal::IsHeapObject().
Referenced by v8::internal::ClientRootVisitor< Visitor >::VisitRootPointers().
Synchronize()
template<typename Visitor = RootVisitor>
void v8::internal::ClientRootVisitor< Visitor >::Synchronize (VisitorSynchronization::SyncTag tag) [inline], [final], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 283 of file visitors.h.
                                                            {
    actual_visitor_->Synchronize(tag);
  }
References v8::internal::ClientRootVisitor< Visitor >::actual_visitor_.
VisitRootPointers() [1/2]
template<typename Visitor = RootVisitor>
void v8::internal::ClientRootVisitor< Visitor >::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 263 of file visitors.h.
                                                                         {
    for (FullObjectSlot p = start; p < end; ++p) {
      Tagged<Object> object = *p;
#ifdef V8_ENABLE_DIRECT_HANDLE
      if (object.ptr() == ValueHelper::kTaggedNullAddress) continue;
#endif
      if (!IsSharedHeapObject(object)) continue;
      actual_visitor_->VisitRootPointer(root, description, p);
    }
  }
References v8::internal::ClientRootVisitor< Visitor >::actual_visitor_, v8::internal::compiler::end(), v8::internal::ClientRootVisitor< Visitor >::IsSharedHeapObject(), and v8::internal::kTaggedNullAddress.
VisitRootPointers() [2/2]
template<typename Visitor = RootVisitor>
void v8::internal::ClientRootVisitor< Visitor >::VisitRootPointers (Root root, const char * description, OffHeapObjectSlot start, OffHeapObjectSlot end) [inline], [final], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 275 of file visitors.h.
                                                                               {
    actual_visitor_->VisitRootPointers(root, description, start, end);
  }
References v8::internal::ClientRootVisitor< Visitor >::actual_visitor_, and v8::internal::compiler::end().
VisitRunningCode()
template<typename Visitor >
void v8::internal::ClientRootVisitor< Visitor >::VisitRunningCode (FullObjectSlot code_slot, FullObjectSlot maybe_istream_slot) [inline], [final], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 46 of file visitors-inl.h.
                                                                 {
#if DEBUG
  DCHECK(!HeapLayout::InWritableSharedSpace(Cast<HeapObject>(*code_slot)));
  Tagged<Object> maybe_istream = *maybe_istream_slot;
  DCHECK(maybe_istream == Smi::zero() ||
         !HeapLayout::InWritableSharedSpace(Cast<HeapObject>(maybe_istream)));
#endif
}
References v8::internal::DCHECK(), v8::internal::HeapLayout::InWritableSharedSpace(), and v8::internal::Smi::zero().
Member Data Documentation
actual_visitor_
template<typename Visitor = RootVisitor>
Visitor* const v8::internal::ClientRootVisitor< Visitor >::actual_visitor_ [private]
Definition at line 290 of file visitors.h.
Referenced by v8::internal::ClientRootVisitor< Visitor >::Synchronize(), and v8::internal::ClientRootVisitor< Visitor >::VisitRootPointers().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/visitors.h
/mnt/V8SourceCode/src/objects/visitors-inl.h