v8::internal::compiler::turboshaft::OperationMatcher Class Reference
#include <operation-matcher.h>
Public Types
template<typename T >
using VMatch = detail::ValueMatch< T, const_or_v_exists_v< T > >
template<typename T >
using OMatch = detail::OptionMatch< T >
Public Member Functions
OperationMatcher (const Graph &graph)
template<class Op >
bool Is (V< AnyOrNone > op_idx) const
template<class Op >
const underlying_operation_t< Op > * TryCast (V< AnyOrNone > op_idx) const
template<class Op >
const underlying_operation_t< Op > & Cast (V< AnyOrNone > op_idx) const
const Operation & Get (V< AnyOrNone > op_idx) const
V< AnyOrNone > Index (const Operation &op) const
bool MatchZero (V< Any > matched) const
bool MatchIntegralZero (V< Any > matched) const
bool MatchSmiZero (V< Any > matched) const
bool MatchFloat32Constant (V< Any > matched, float *constant) const
bool MatchFloat32Constant (V< Any > matched, i::Float32 *constant) const
bool MatchFloat64Constant (V< Any > matched, double *constant) const
bool MatchFloat64Constant (V< Any > matched, i::Float64 *constant) const
bool MatchFloat (V< Any > matched, double *value) const
bool MatchFloat (V< Any > matched, double value) const
bool MatchNaN (V< Float > matched) const
bool MatchHeapConstant (V< Any > matched, Handle< HeapObject > *tagged=nullptr) const
bool MatchIntegralWordConstant (V< Any > matched, WordRepresentation rep, uint64_t *unsigned_constant, int64_t *signed_constant=nullptr) const
bool MatchIntegralWordConstant (V< Any > matched, WordRepresentation rep, int64_t *signed_constant) const
bool MatchIntegralWord32Constant (V< Any > matched, uint32_t *constant) const
bool MatchIntegralWord64Constant (V< Any > matched, uint64_t *constant) const
bool MatchIntegralWord32Constant (V< Any > matched, uint32_t constant) const
bool MatchIntegralWord64Constant (V< Any > matched, int64_t *constant) const
bool MatchIntegralWord32Constant (V< Any > matched, int32_t *constant) const
template<typename T = intptr_t>
bool MatchIntegralWordPtrConstant (V< Any > matched, T *constant) const
bool MatchSignedIntegralConstant (V< Any > matched, int64_t *constant) const
bool MatchUnsignedIntegralConstant (V< Any > matched, uint64_t *constant) const
bool MatchExternalConstant (V< Any > matched, ExternalReference *reference) const
bool MatchWasmStubCallConstant (V< Any > matched, uint64_t *stub_id) const
template<typename T >
bool MatchChange (V< Any > matched, VMatch< T > input, OMatch< ChangeOp::Kind > kind={}, OMatch< ChangeOp::Assumption > assumption={}, OMatch< RegisterRepresentation > from={}, OMatch< RegisterRepresentation > to={}) const
bool MatchTruncateWord64ToWord32 (V< Any > matched, VMatch< Word64 > input) const
template<typename T >
requires (IsWord< T >()) bool MatchWordBinop(V< Any > matched
Public Attributes
VMatch< T > left
VMatch< T > VMatch< T > right
VMatch< T > VMatch< T > OMatch< WordBinopOp::Kind > kind = {}
VMatch< T > VMatch< T > OMatch< WordBinopOp::Kind > OMatch< WordRepresentation > rep
Detailed Description
Definition at line 85 of file operation-matcher.h.
Member Typedef Documentation
OMatch
template<typename T >
using v8::internal::compiler::turboshaft::OperationMatcher::OMatch = detail::OptionMatch<T>
Definition at line 90 of file operation-matcher.h.
VMatch
template<typename T >
using v8::internal::compiler::turboshaft::OperationMatcher::VMatch = detail::ValueMatch<T, const_or_v_exists_v<T> >
Definition at line 88 of file operation-matcher.h.
Constructor & Destructor Documentation
OperationMatcher()
v8::internal::compiler::turboshaft::OperationMatcher::OperationMatcher (const Graph & graph) [inline], [explicit]
Definition at line 92 of file operation-matcher.h.
: graph_(graph) {}
Member Function Documentation
Cast()
template<class Op >
const underlying_operation_t<Op>& v8::internal::compiler::turboshaft::OperationMatcher::Cast (V< AnyOrNone > op_idx) const [inline]
Definition at line 105 of file operation-matcher.h.
                                                                    {
    return graph_.Get(op_idx).Cast<Op>();
  }
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::EmitInt64MulWithOverflow(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::GetIterCountIfStaticCanonicalForLoop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrowWordAnd(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MatchHeapObjectEqual(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::RemoveUnnecessaryWordAnd(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), v8::internal::compiler::OperandGenerator::ToNegatedConstant(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryVisitWordShift(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoWord32ToWord64Conversion(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicBinop(), v8::internal::compiler::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicBinOp(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::VisitInt32PairBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMulHigh(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::VisitShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift(), v8::internal::compiler::VisitWord32PairShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32Shift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64Shift().
Get()
const Operation& v8::internal::compiler::turboshaft::OperationMatcher::Get (V< AnyOrNone > op_idx) const [inline]
Definition at line 109 of file operation-matcher.h.
{ return graph_.Get(op_idx); }
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::AtomicOpType(), v8::internal::compiler::AtomicOrder(), v8::internal::compiler::CanBeImmediate(), v8::internal::compiler::InstructionSelector::CanCover(), v8::internal::compiler::InstructionSelector::CanDoBranchIfOverflowFusion(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::CanUseOptimizedWord32Compare(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::CombineFlagSettingOps(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::InstructionSelector::EmitIdentity(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), v8::internal::compiler::EmitS128Load(), v8::internal::compiler::EmitSignExtendWord(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::InstructionSelector::FindProjection(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands(), v8::internal::compiler::turboshaft::GetFlagsCondition(), v8::internal::compiler::GetImmediateIntegerValue(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::increment_effect_level_for_node(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::InstructionSelector::IsCommutative(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsIntConstant(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::IsNodeUnsigned(), v8::internal::compiler::InstructionSelector::IsProtectedLoad(), v8::internal::compiler::InstructionSelector::IsReallyUsed(), v8::internal::compiler::InstructionSelector::IsSourcePositionUsed(), v8::internal::compiler::InstructionSelector::IsUsed(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsWordAnd(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::MatchPhiCompareCst(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MatchScaledIndex(), v8::internal::compiler::MatchScaledIndex(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::MaybeReplaceCmpZeroWithFlagSettingBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::MaybeReplaceCmpZeroWithFlagSettingBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceMemoryIndex(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitBitfieldExtract32(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyAdd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyNegate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplySub(), v8::internal::compiler::TryGetRightWordConstant(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchAnyExtend(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchAnyShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacement(), v8::internal::compiler::TryMatchBaseWithScaledIndexAndDisplacement64(), v8::internal::compiler::TryMatchBaseWithScaledIndexAndDisplacement64ForWordBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacementForWordBinop(), v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainBranch(), v8::internal::compiler::turboshaft::TryMatchConditionalCompareChainSet(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchLoadStoreShift(), v8::internal::compiler::TryMatchNegFromSub(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShift(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShiftImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchSignExtendShift(), v8::internal::compiler::TryMatchSignExtInt16OrInt8FromWord32Sar(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAddSub(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitBinOp(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBitMask(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitFloat32Compare(), v8::internal::compiler::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitFloat64Compare(), v8::internal::compiler::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitFullWord32Compare(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::VisitLogical(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMinOrMax(), v8::internal::compiler::InstructionSelector::VisitNode(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitOptimizedWord32Compare(), v8::internal::compiler::VisitPairAtomicBinop(), v8::internal::compiler::InstructionSelector::VisitPhi(), v8::internal::compiler::InstructionSelector::VisitProjection(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTemp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTempSimd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRR(), v8::internal::compiler::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRR(), v8::internal::compiler::VisitRRI(), v8::internal::compiler::VisitRRIR(), v8::internal::compiler::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRROFloat(), v8::internal::compiler::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRR(), v8::internal::compiler::VisitSimdShift(), v8::internal::compiler::InstructionSelector::VisitStaticAssert(), v8::internal::compiler::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTestUnderMask(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitUnaryOp(), v8::internal::compiler::VisitUniqueRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitWord32Compare(), v8::internal::compiler::InstructionSelector::VisitWord64AtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64EqualImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitWordCompare(), v8::internal::compiler::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
Index()
V<AnyOrNone> v8::internal::compiler::turboshaft::OperationMatcher::Index (const Operation & op) const [inline]
Definition at line 111 of file operation-matcher.h.
{ return graph_.Index(op); }
Is()
template<class Op >
bool v8::internal::compiler::turboshaft::OperationMatcher::Is (V< AnyOrNone > op_idx) const [inline]
Definition at line 95 of file operation-matcher.h.
                                     {
    return graph_.Get(op_idx).Is<Op>();
  }
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::CheckPairOrPairOp(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::GetBinopLeftRightCstOnTheRight(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsBit(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Load(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Store(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryMatchHeapObject(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::VisitLoadCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), v8::internal::compiler::VisitStoreCommon(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
MatchChange()
template<typename T >
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchChange (V< Any > matched, VMatch< T > input, OMatch< ChangeOp::Kind > kind = {}, OMatch< ChangeOp::Assumption > assumption = {}, OMatch< RegisterRepresentation > from = {}, OMatch< RegisterRepresentation > to = {}) const [inline]
Definition at line 348 of file operation-matcher.h.
                                               {},
                   OMatch<ChangeOp::Assumption> assumption = {},
                   OMatch<RegisterRepresentation> from = {},
                   OMatch<RegisterRepresentation> to = {}) const {
    const ChangeOp* op = TryCast<ChangeOp>(matched);
    if (!op) return false;
    if (input.matches(op->input(), this) && kind.matches(op->kind) &&
        assumption.matches(op->assumption) && from.matches(op->from) &&
        to.matches(op->to)) {
      input.bind(op->input(), this);
      kind.bind(op->kind);
      assumption.bind(op->assumption);
      from.bind(op->from);
      to.bind(op->to);
      return true;
    }
    return false;
  }
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsFloat32ConvertedToFloat64(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoFloat32ToFloat64Conversion().
MatchExternalConstant()
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchExternalConstant (V< Any > matched, ExternalReference * reference) const [inline]
Definition at line 328 of file operation-matcher.h.
                                                                 {
    const ConstantOp* op = TryCast<ConstantOp>(matched);
    if (!op) return false;
    if (op->kind != ConstantOp::Kind::kExternal) return false;
    *reference = op->storage.external;
    return true;
  }
References v8::internal::compiler::turboshaft::ConstantOp::Storage::external, v8::internal::compiler::turboshaft::ConstantOp::kExternal, v8::internal::compiler::turboshaft::ConstantOp::kind, and v8::internal::compiler::turboshaft::ConstantOp::storage.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon().
MatchFloat() [1/2]
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat (V< Any > matched, double * value) const [inline]
Definition at line 175 of file operation-matcher.h.
                                                       {
    const ConstantOp* op = TryCast<ConstantOp>(matched);
    if (!op) return false;
    if (op->kind == ConstantOp::Kind::kFloat64) {
      *value = op->storage.float64.get_scalar();
      return true;
    } else if (op->kind == ConstantOp::Kind::kFloat32) {
      *value = op->storage.float32.get_scalar();
      return true;
    }
    return false;
  }
References v8::internal::compiler::turboshaft::ConstantOp::Storage::float32, v8::internal::compiler::turboshaft::ConstantOp::Storage::float64, v8::internal::Float32::get_scalar(), v8::internal::Float64::get_scalar(), v8::internal::compiler::turboshaft::ConstantOp::kFloat32, v8::internal::compiler::turboshaft::ConstantOp::kFloat64, v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::ConstantOp::storage, and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), MatchFloat(), and MatchNaN().
MatchFloat() [2/2]
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat (V< Any > matched, double value) const [inline]
Definition at line 188 of file operation-matcher.h.
                                                      {
    double k;
    if (!MatchFloat(matched, &k)) return false;
    return base::bit_cast<uint64_t>(value) == base::bit_cast<uint64_t>(k) ||
           (std::isnan(k) && std::isnan(value));
  }
References MatchFloat(), and v8::internal::value.
MatchFloat32Constant() [1/2]
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat32Constant (V< Any > matched, float * constant) const [inline]
Definition at line 143 of file operation-matcher.h.
                                                                   {
    const ConstantOp* op = TryCast<ConstantOp>(matched);
    if (!op) return false;
    if (op->kind != ConstantOp::Kind::kFloat32) return false;
    *constant = op->storage.float32.get_scalar();
    return true;
  }
References v8::internal::compiler::turboshaft::ConstantOp::Storage::float32, v8::internal::Float32::get_scalar(), v8::internal::compiler::turboshaft::ConstantOp::kFloat32, v8::internal::compiler::turboshaft::ConstantOp::kind, and v8::internal::compiler::turboshaft::ConstantOp::storage.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual().
MatchFloat32Constant() [2/2]
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat32Constant (V< Any > matched, i::Float32 * constant) const [inline]
Definition at line 151 of file operation-matcher.h.
                                                                      {
    const ConstantOp* op = TryCast<ConstantOp>(matched);
    if (!op) return false;
    if (op->kind != ConstantOp::Kind::kFloat32) return false;
    *constant = op->storage.float32;
    return true;
  }
References v8::internal::compiler::turboshaft::ConstantOp::Storage::float32, v8::internal::compiler::turboshaft::ConstantOp::kFloat32, v8::internal::compiler::turboshaft::ConstantOp::kind, and v8::internal::compiler::turboshaft::ConstantOp::storage.
MatchFloat64Constant() [1/2]
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat64Constant (V< Any > matched, double * constant) const [inline]
Definition at line 159 of file operation-matcher.h.
                                                                    {
    const ConstantOp* op = TryCast<ConstantOp>(matched);
    if (!op) return false;
    if (op->kind != ConstantOp::Kind::kFloat64) return false;
    *constant = op->storage.float64.get_scalar();
    return true;
  }
References v8::internal::compiler::turboshaft::ConstantOp::Storage::float64, v8::internal::Float64::get_scalar(), v8::internal::compiler::turboshaft::ConstantOp::kFloat64, v8::internal::compiler::turboshaft::ConstantOp::kind, and v8::internal::compiler::turboshaft::ConstantOp::storage.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatBinop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::FloatUnary(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsFloat32ConvertedToFloat64(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoFloat32ToFloat64Conversion().
MatchFloat64Constant() [2/2]
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchFloat64Constant (V< Any > matched, i::Float64 * constant) const [inline]
Definition at line 167 of file operation-matcher.h.
                                                                      {
    const ConstantOp* op = TryCast<ConstantOp>(matched);
    if (!op) return false;
    if (op->kind != ConstantOp::Kind::kFloat64) return false;
    *constant = op->storage.float64;
    return true;
  }
References v8::internal::compiler::turboshaft::ConstantOp::Storage::float64, v8::internal::compiler::turboshaft::ConstantOp::kFloat64, v8::internal::compiler::turboshaft::ConstantOp::kind, and v8::internal::compiler::turboshaft::ConstantOp::storage.
MatchHeapConstant()
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchHeapConstant (V< Any > matched, Handle< HeapObject > * tagged = nullptr) const [inline]
Definition at line 200 of file operation-matcher.h.
                                                                     {
    const ConstantOp* op = TryCast<ConstantOp>(matched);
    if (!op) return false;
    if (!(op->kind == any_of(ConstantOp::Kind::kHeapObject,
                             ConstantOp::Kind::kCompressedHeapObject))) {
      return false;
    }
    if (tagged) {
      *tagged = op->handle();
    }
    return true;
  }
References v8::internal::compiler::turboshaft::ConstantOp::handle(), v8::internal::compiler::turboshaft::ConstantOp::kCompressedHeapObject, v8::internal::compiler::turboshaft::ConstantOp::kHeapObject, and v8::internal::compiler::turboshaft::ConstantOp::kind.
Referenced by v8::internal::compiler::IsBuiltinCall(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MatchHeapObjectEqual(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryMatchHeapObject(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64EqualImpl().
MatchIntegralWord32Constant() [1/3]
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant (V< Any > matched, int32_t * constant) const [inline]
Definition at line 280 of file operation-matcher.h.
                                                                            {
    if (int64_t value; MatchIntegralWordConstant(
            matched, WordRepresentation::Word32(), &value)) {
      *constant = static_cast<int32_t>(value);
      return true;
    }
    return false;
  }
References MatchIntegralWordConstant(), v8::internal::value, and v8::internal::compiler::turboshaft::WordRepresentation::Word32().
MatchIntegralWord32Constant() [2/3]
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant (V< Any > matched, uint32_t * constant) const [inline]
Definition at line 253 of file operation-matcher.h.
                                                                             {
    if (uint64_t value; MatchIntegralWordConstant(
            matched, WordRepresentation::Word32(), &value)) {
      *constant = static_cast<uint32_t>(value);
      return true;
    }
    return false;
  }
References MatchIntegralWordConstant(), v8::internal::value, and v8::internal::compiler::turboshaft::WordRepresentation::Word32().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::BitcastWord32PairToFloat64(), v8::internal::compiler::turboshaft::detail::BitfieldCheck::Detect(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerRotateRight(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::MatchBoolConstant(), MatchIntegralWordPtrConstant(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MatchScaledIndex(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceBranchCondition(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringNewWtf8ArrayImpl(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Switch(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacementForWordBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchBitwiseAndSmallMask(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchShiftImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchSignExtendShift(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordUnary().
MatchIntegralWord32Constant() [3/3]
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant (V< Any > matched, uint32_t constant) const [inline]
Definition at line 267 of file operation-matcher.h.
                                                                            {
    if (uint64_t value; MatchIntegralWordConstant(
            matched, WordRepresentation::Word32(), &value)) {
      return static_cast<uint32_t>(value) == constant;
    }
    return false;
  }
References MatchIntegralWordConstant(), v8::internal::value, and v8::internal::compiler::turboshaft::WordRepresentation::Word32().
MatchIntegralWord64Constant() [1/2]
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord64Constant (V< Any > matched, int64_t * constant) const [inline]
Definition at line 275 of file operation-matcher.h.
                                                                            {
    return MatchIntegralWordConstant(matched, WordRepresentation::Word64(),
                                     constant);
  }
References MatchIntegralWordConstant(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
MatchIntegralWord64Constant() [2/2]
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord64Constant (V< Any > matched, uint64_t * constant) const [inline]
Definition at line 262 of file operation-matcher.h.
                                                                             {
    return MatchIntegralWordConstant(matched, WordRepresentation::Word64(),
                                     constant);
  }
References MatchIntegralWordConstant(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsWord32ConvertedToWord64(), MatchIntegralWordPtrConstant(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordUnary().
MatchIntegralWordConstant() [1/2]
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant (V< Any > matched, WordRepresentation rep, int64_t * signed_constant) const [inline]
Definition at line 248 of file operation-matcher.h.
                                                                 {
    return MatchIntegralWordConstant(matched, rep, nullptr, signed_constant);
  }
References MatchIntegralWordConstant(), and rep.
MatchIntegralWordConstant() [2/2]
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordConstant (V< Any > matched, WordRepresentation rep, uint64_t * unsigned_constant, int64_t * signed_constant = nullptr) const [inline]
Definition at line 214 of file operation-matcher.h.
                                                                           {
    const ConstantOp* op = TryCast<ConstantOp>(matched);
    if (!op) return false;
    switch (op->kind) {
      case ConstantOp::Kind::kWord32:
      case ConstantOp::Kind::kWord64:
      case ConstantOp::Kind::kRelocatableWasmCall:
      case ConstantOp::Kind::kRelocatableWasmStubCall:
        if (rep.value() == WordRepresentation::Word32()) {
          if (unsigned_constant) {
            *unsigned_constant = static_cast<uint32_t>(op->integral());
          }
          if (signed_constant) {
            *signed_constant = static_cast<int32_t>(op->signed_integral());
          }
          return true;
        } else if (rep.value() == WordRepresentation::Word64()) {
          if (unsigned_constant) {
            *unsigned_constant = op->integral();
          }
          if (signed_constant) {
            *signed_constant = op->signed_integral();
          }
          return true;
        }
        return false;
      default:
        return false;
    }
    UNREACHABLE();
  }
References v8::internal::compiler::turboshaft::ConstantOp::integral(), v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::ConstantOp::kRelocatableWasmCall, v8::internal::compiler::turboshaft::ConstantOp::kRelocatableWasmStubCall, v8::internal::compiler::turboshaft::ConstantOp::kWord32, v8::internal::compiler::turboshaft::ConstantOp::kWord64, rep, v8::internal::compiler::turboshaft::ConstantOp::signed_integral(), v8::internal::UNREACHABLE(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Change(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Comparison(), MatchIntegralWord32Constant(), MatchIntegralWord64Constant(), MatchIntegralWordConstant(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceWithTruncation(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::Shift(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryAdjustElementScale(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryReduceToRor(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
MatchIntegralWordPtrConstant()
template<typename T = intptr_t>
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWordPtrConstant (V< Any > matched, T * constant) const [inline]
Definition at line 290 of file operation-matcher.h.
                                                                       {
    if constexpr (Is64()) {
      static_assert(sizeof(T) == sizeof(int64_t));
      int64_t v;
      if (!MatchIntegralWord64Constant(matched, &v)) return false;
      *constant = static_cast<T>(v);
      return true;
    } else {
      static_assert(sizeof(T) == sizeof(int32_t));
      int32_t v;
      if (!MatchIntegralWord32Constant(matched, &v)) return false;
      *constant = static_cast<T>(v);
      return true;
    }
  }
References v8::internal::Is64(), MatchIntegralWord32Constant(), and MatchIntegralWord64Constant().
Referenced by v8::internal::BuiltinsReducer< Next >::TryToIntPtrConstant().
MatchIntegralZero()
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralZero (V< Any > matched) const [inline]
Definition at line 131 of file operation-matcher.h.
                                               {
    int64_t constant;
    return MatchSignedIntegralConstant(matched, &constant) && constant == 0;
  }
References MatchSignedIntegralConstant().
Referenced by v8::internal::compiler::InstructionSelector::ConsumeEqualZero(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::SimplifyLoadStore(), v8::internal::compiler::TryMatchNegFromSub(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord32Compare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare().
MatchNaN()
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchNaN (V< Float > matched) const [inline]
Definition at line 195 of file operation-matcher.h.
                                        {
    double k;
    return MatchFloat(matched, &k) && std::isnan(k);
  }
References MatchFloat().
MatchSignedIntegralConstant()
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchSignedIntegralConstant (V< Any > matched, int64_t * constant) const [inline]
Definition at line 306 of file operation-matcher.h.
                                                                            {
    if (const ConstantOp* c = TryCast<ConstantOp>(matched)) {
      if (c->kind == ConstantOp::Kind::kWord32 ||
          c->kind == ConstantOp::Kind::kWord64) {
        *constant = c->signed_integral();
        return true;
      }
    }
    return false;
  }
References v8::internal::compiler::turboshaft::ConstantOp::kWord32, and v8::internal::compiler::turboshaft::ConstantOp::kWord64.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrowWordAnd(), MatchIntegralZero(), v8::internal::compiler::MatchScaledIndex(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::RemoveUnnecessaryWordAnd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitBitfieldExtract32(), v8::internal::compiler::TryMatchBaseWithScaledIndexAndDisplacement64ForWordBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::VisitLogical(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWordCompare().
MatchSmiZero()
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchSmiZero (V< Any > matched) const [inline]
Definition at line 136 of file operation-matcher.h.
                                          {
    const ConstantOp* op = TryCast<ConstantOp>(matched);
    if (!op) return false;
    if (op->kind != ConstantOp::Kind::kSmi) return false;
    return op->smi().value() == 0;
  }
References v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::ConstantOp::kSmi, v8::internal::compiler::turboshaft::ConstantOp::smi(), and v8::internal::Tagged< Smi >::value().
Referenced by v8::internal::compiler::InstructionSelector::ConsumeEqualZero().
MatchTruncateWord64ToWord32()
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchTruncateWord64ToWord32 (V< Any > matched, VMatch< Word64 > input) const [inline]
Definition at line 368 of file operation-matcher.h.
                                                                               {
    return MatchChange<Word64>(matched, input, ChangeOp::Kind::kTruncate, {},
                               RegisterRepresentation::Word64(),
                               RegisterRepresentation::Word32());
  }
References v8::internal::compiler::turboshaft::ChangeOp::kTruncate, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32Shift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWordCompare().
MatchUnsignedIntegralConstant()
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchUnsignedIntegralConstant (V< Any > matched, uint64_t * constant) const [inline]
Definition at line 317 of file operation-matcher.h.
                                                                               {
    if (const ConstantOp* c = TryCast<ConstantOp>(matched)) {
      if (c->kind == ConstantOp::Kind::kWord32 ||
          c->kind == ConstantOp::Kind::kWord64) {
        *constant = c->integral();
        return true;
      }
    }
    return false;
  }
References v8::internal::compiler::turboshaft::ConstantOp::kWord32, and v8::internal::compiler::turboshaft::ConstantOp::kWord64.
Referenced by v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::GetIterCountIfStaticCanonicalForLoop(), v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::MatchPhiCompareCst(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::TryGetRightWordConstant(), v8::internal::compiler::TryMatchSignExtInt16OrInt8FromWord32Sar(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWord32Compare().
MatchWasmStubCallConstant()
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchWasmStubCallConstant (V< Any > matched, uint64_t * stub_id) const [inline]
Definition at line 337 of file operation-matcher.h.
                                                                          {
    const ConstantOp* op = TryCast<ConstantOp>(matched);
    if (!op) return false;
    if (op->kind != ConstantOp::Kind::kRelocatableWasmStubCall) {
      return false;
    }
    *stub_id = op->integral();
    return true;
  }
References v8::internal::compiler::turboshaft::ConstantOp::integral(), v8::internal::compiler::turboshaft::ConstantOp::kind, and v8::internal::compiler::turboshaft::ConstantOp::kRelocatableWasmStubCall.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::IsArrayNewSegment().
MatchZero()
bool v8::internal::compiler::turboshaft::OperationMatcher::MatchZero (V< Any > matched) const [inline]
Definition at line 113 of file operation-matcher.h.
                                       {
    const ConstantOp* op = TryCast<ConstantOp>(matched);
    if (!op) return false;
    switch (op->kind) {
      case ConstantOp::Kind::kWord32:
      case ConstantOp::Kind::kWord64:
        return op->integral() == 0;
      case ConstantOp::Kind::kFloat32:
        return op->float32().get_scalar() == 0;
      case ConstantOp::Kind::kFloat64:
        return op->float64().get_scalar() == 0;
      case ConstantOp::Kind::kSmi:
        return op->smi().value() == 0;
      default:
        return false;
    }
  }
References v8::internal::compiler::turboshaft::ConstantOp::float32(), v8::internal::compiler::turboshaft::ConstantOp::float64(), v8::internal::Float32::get_scalar(), v8::internal::Float64::get_scalar(), v8::internal::compiler::turboshaft::ConstantOp::integral(), v8::internal::compiler::turboshaft::ConstantOp::kFloat32, v8::internal::compiler::turboshaft::ConstantOp::kFloat64, v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::ConstantOp::kSmi, v8::internal::compiler::turboshaft::ConstantOp::kWord32, v8::internal::compiler::turboshaft::ConstantOp::kWord64, v8::internal::compiler::turboshaft::ConstantOp::smi(), and v8::internal::Tagged< Smi >::value().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::OverflowCheckedBinop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceBranchCondition(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat32Compare(), v8::internal::compiler::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFloat64Compare(), v8::internal::compiler::VisitFloat64Compare(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::WordBinop().
requires()
template<typename T >
v8::internal::compiler::turboshaft::OperationMatcher::requires (IsWord< T > ())
TryCast()
template<class Op >
const underlying_operation_t<Op>* v8::internal::compiler::turboshaft::OperationMatcher::TryCast (V< AnyOrNone > op_idx) const [inline]
Definition at line 100 of file operation-matcher.h.
                                                                       {
    return graph_.Get(op_idx).TryCast<Op>();
  }
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::CheckPairOrPairOp(), v8::internal::compiler::GetWord32Constant(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsCompressed(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsInt16(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsInt8(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::IsWord32ConvertedToWord64(), v8::internal::compiler::turboshaft::StaticCanonicalForLoopMatcher::MatchCheckedOverflowBinop(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceBranchCondition(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TaggedBitcast(), v8::internal::compiler::OperandGenerator::ToConstant(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchBitwiseAndSmallMask(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryMatchHeapObject(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchSignExtendShift(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryReduceToRor(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryRemoveWord32ToWord64Conversion(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::UndoWord32ToWord64Conversion().
Member Data Documentation
kind
VMatch<T> VMatch<T> OMatch<WordBinopOp::Kind> v8::internal::compiler::turboshaft::OperationMatcher::kind = {}
Definition at line 377 of file operation-matcher.h.
Referenced by v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), and v8::internal::compiler::InstructionSelector::AppendDeoptimizeArguments().
left
VMatch<T> v8::internal::compiler::turboshaft::OperationMatcher::left
Definition at line 376 of file operation-matcher.h.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::TryMatchBaseWithScaledIndexAndDisplacementForWordBinop().
rep
VMatch<T> VMatch<T> OMatch<WordBinopOp::Kind> OMatch<WordRepresentation> v8::internal::compiler::turboshaft::OperationMatcher::rep
Definition at line 378 of file operation-matcher.h.
Referenced by v8::internal::compiler::InstructionSelector::InitializeCallBuffer(), v8::internal::compiler::InstructionSelector::MarkAsRepresentation(), MatchIntegralWordConstant(), and v8::internal::compiler::InstructionSelector::VisitNode().
right
VMatch<T> VMatch<T> v8::internal::compiler::turboshaft::OperationMatcher::right
Definition at line 376 of file operation-matcher.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/operation-matcher.h