v8::internal::compiler::ConstructParameters Class Reference
#include <js-operator.h>
Public Member Functions
ConstructParameters (uint32_t arity, CallFrequency const &frequency, FeedbackSource const &feedback)
uint32_t arity () const
int arity_without_implicit_args () const
CallFrequency const & frequency () const
FeedbackSource const & feedback () const
Static Public Attributes
static constexpr int kExtraConstructInputCount = 3
Private Attributes
uint32_t const arity_
CallFrequency const frequency_
FeedbackSource const feedback_
Detailed Description
Definition at line 152 of file js-operator.h.
Constructor & Destructor Documentation
ConstructParameters()
v8::internal::compiler::ConstructParameters::ConstructParameters (uint32_t arity, CallFrequency const & frequency, FeedbackSource const & feedback) [inline]
Definition at line 158 of file js-operator.h.
      : arity_(arity), frequency_(frequency), feedback_(feedback) {
    DCHECK_GE(arity, kExtraConstructInputCount);
    DCHECK(is_int32(arity));
  }
References arity(), v8::internal::DCHECK(), DCHECK_GE, and kExtraConstructInputCount.
Member Function Documentation
arity()
uint32_t v8::internal::compiler::ConstructParameters::arity () const [inline]
Definition at line 171 of file js-operator.h.
{ return arity_; }
References arity_.
Referenced by v8::internal::compiler::JSOperatorBuilder::Construct(), v8::internal::compiler::JSOperatorBuilder::ConstructForwardAllArgs(), ConstructParameters(), v8::internal::compiler::JSOperatorBuilder::ConstructWithArrayLike(), v8::internal::compiler::JSOperatorBuilder::ConstructWithSpread(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
arity_without_implicit_args()
int v8::internal::compiler::ConstructParameters::arity_without_implicit_args () const [inline]
Definition at line 172 of file js-operator.h.
                                          {
    return static_cast<int>(arity_ - kExtraConstructInputCount);
  }
References arity_, and kExtraConstructInputCount.
Referenced by v8::internal::compiler::JSConstructNodeBase< kOpcode >::ArgumentCount(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), and v8::internal::compiler::JSTypedLowering::ReduceJSConstruct().
feedback()
FeedbackSource const& v8::internal::compiler::ConstructParameters::feedback () const [inline]
Definition at line 177 of file js-operator.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator==(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSCallReducer::ReduceJSConstructWithArrayLike(), and v8::internal::compiler::JSCallReducer::ReduceJSConstructWithSpread().
frequency()
CallFrequency const& v8::internal::compiler::ConstructParameters::frequency () const [inline]
Definition at line 176 of file js-operator.h.
{ return frequency_; }
References frequency_.
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseExecutor(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseReject(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::JSInliningHeuristic::Reduce(), v8::internal::compiler::JSCallReducer::ReduceJSConstruct(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), v8::internal::compiler::JSCallReducer::ReduceJSConstructWithArrayLike(), and v8::internal::compiler::JSCallReducer::ReduceJSConstructWithSpread().
Member Data Documentation
arity_
uint32_t const v8::internal::compiler::ConstructParameters::arity_ [private]
Definition at line 180 of file js-operator.h.
Referenced by arity(), and arity_without_implicit_args().
feedback_
FeedbackSource const v8::internal::compiler::ConstructParameters::feedback_ [private]
Definition at line 182 of file js-operator.h.
Referenced by feedback().
frequency_
CallFrequency const v8::internal::compiler::ConstructParameters::frequency_ [private]
Definition at line 181 of file js-operator.h.
Referenced by frequency().
kExtraConstructInputCount
constexpr int v8::internal::compiler::ConstructParameters::kExtraConstructInputCount = 3 [static], [constexpr]
Definition at line 156 of file js-operator.h.
Referenced by arity_without_implicit_args(), and ConstructParameters().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h