v8::internal::wasm::WasmDeoptView Class Reference
#include <wasm-deopt-data.h>
Public Member Functions
WasmDeoptView (base::Vector< const uint8_t > deopt_data)
bool HasDeoptData () const
const WasmDeoptData & GetDeoptData () const
base::Vector< const uint8_t > GetTranslationsArray () const
WasmDeoptEntry GetDeoptEntry (uint32_t deopt_index) const
std::vector< DeoptimizationLiteral > BuildDeoptimizationLiteralArray ()
Private Attributes
base::Vector< const uint8_t > deopt_data_
WasmDeoptData base_data_
Detailed Description
Definition at line 46 of file wasm-deopt-data.h.
Constructor & Destructor Documentation
WasmDeoptView()
v8::internal::wasm::WasmDeoptView::WasmDeoptView (base::Vector< const uint8_t > deopt_data) [inline], [explicit]
Definition at line 48 of file wasm-deopt-data.h.
      : deopt_data_(deopt_data) {
    if (!deopt_data.empty()) {
      static_assert(std::is_trivially_copy_assignable_v<WasmDeoptData>);
      DCHECK_GE(deopt_data_.size(), sizeof(WasmDeoptData));
      std::memcpy(&base_data_, deopt_data_.begin(), sizeof(base_data_));
    }
  }
References base_data_, v8::base::Vector< T >::begin(), DCHECK_GE, deopt_data_, v8::base::Vector< T >::empty(), and v8::base::Vector< T >::size().
Member Function Documentation
BuildDeoptimizationLiteralArray()
std::vector< DeoptimizationLiteral > v8::internal::wasm::WasmDeoptView::BuildDeoptimizationLiteralArray ()
Definition at line 12 of file wasm-deopt-data.cc.
                                               {
  DCHECK(HasDeoptData());
  static_assert(std::is_trivially_copy_assignable_v<DeoptimizationLiteral>);
  std::vector<DeoptimizationLiteral> deopt_literals(
      base_data_.deopt_literals_size);
  const uint8_t* data = deopt_data_.begin() + sizeof(base_data_) +
                        base_data_.translation_array_size +
                        sizeof(WasmDeoptEntry) * base_data_.entry_count;
  // Copy the data (as the data in the WasmCode object is potentially
  // misaligned).
  std::memcpy(deopt_literals.data(), data,
              base_data_.deopt_literals_size * sizeof(deopt_literals[0]));
  return deopt_literals;
}
References base_data_, v8::base::Vector< T >::begin(), v8::internal::DCHECK(), deopt_data_, v8::internal::wasm::WasmDeoptData::deopt_literals_size, v8::internal::wasm::WasmDeoptData::entry_count, HasDeoptData(), and v8::internal::wasm::WasmDeoptData::translation_array_size.
GetDeoptData()
const WasmDeoptData& v8::internal::wasm::WasmDeoptView::GetDeoptData () const [inline]
Definition at line 59 of file wasm-deopt-data.h.
                                            {
    DCHECK(HasDeoptData());
    return base_data_;
  }
References base_data_, v8::internal::DCHECK(), and HasDeoptData().
Referenced by v8::internal::Deoptimizer::Deoptimizer(), and v8::internal::wasm::WasmCode::Disassemble().
GetDeoptEntry()
WasmDeoptEntry v8::internal::wasm::WasmDeoptView::GetDeoptEntry (uint32_t deopt_index) const [inline]
Definition at line 70 of file wasm-deopt-data.h.
                                                           {
    DCHECK(HasDeoptData());
    DCHECK(deopt_index < base_data_.entry_count);
    const uint8_t* begin = deopt_data_.begin() + sizeof(base_data_) +
                           base_data_.translation_array_size;
    return base::ReadUnalignedValue<WasmDeoptEntry>(reinterpret_cast<Address>(
        begin + sizeof(WasmDeoptEntry) * deopt_index));
  }
References base_data_, v8::base::Vector< T >::begin(), v8::internal::compiler::begin(), v8::internal::DCHECK(), deopt_data_, v8::internal::wasm::WasmDeoptData::entry_count, HasDeoptData(), and v8::internal::wasm::WasmDeoptData::translation_array_size.
Referenced by v8::internal::wasm::WasmCode::Disassemble().
GetTranslationsArray()
base::Vector<const uint8_t> v8::internal::wasm::WasmDeoptView::GetTranslationsArray () const [inline]
Definition at line 64 of file wasm-deopt-data.h.
                                                         {
    DCHECK(HasDeoptData());
    return {deopt_data_.begin() + sizeof(base_data_),
            base_data_.translation_array_size};
  }
References base_data_, v8::base::Vector< T >::begin(), v8::internal::DCHECK(), deopt_data_, HasDeoptData(), and v8::internal::wasm::WasmDeoptData::translation_array_size.
HasDeoptData()
bool v8::internal::wasm::WasmDeoptView::HasDeoptData () const [inline]
Definition at line 57 of file wasm-deopt-data.h.
{ return !deopt_data_.empty(); }
References deopt_data_, and v8::base::Vector< T >::empty().
Referenced by BuildDeoptimizationLiteralArray(), GetDeoptData(), GetDeoptEntry(), and GetTranslationsArray().
Member Data Documentation
base_data_
WasmDeoptData v8::internal::wasm::WasmDeoptView::base_data_ [private]
Definition at line 83 of file wasm-deopt-data.h.
Referenced by BuildDeoptimizationLiteralArray(), GetDeoptData(), GetDeoptEntry(), GetTranslationsArray(), and WasmDeoptView().
deopt_data_
base::Vector<const uint8_t> v8::internal::wasm::WasmDeoptView::deopt_data_ [private]
Definition at line 82 of file wasm-deopt-data.h.
Referenced by BuildDeoptimizationLiteralArray(), GetDeoptEntry(), GetTranslationsArray(), HasDeoptData(), and WasmDeoptView().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-deopt-data.h
/mnt/V8SourceCode/src/wasm/wasm-deopt-data.cc