v8::internal::EvacuateOldSpaceVisitor Class Reference
Public Member Functions
EvacuateOldSpaceVisitor (Heap *heap, EvacuationAllocator *local_allocator, RecordMigratedSlotVisitor *record_visitor)
bool Visit (Tagged< HeapObject > object, int size) override
Additional Inherited Members
Detailed Description
Definition at line 1788 of file mark-compact.cc.
Constructor & Destructor Documentation
EvacuateOldSpaceVisitor()
v8::internal::EvacuateOldSpaceVisitor::EvacuateOldSpaceVisitor (Heap * heap, EvacuationAllocator * local_allocator, RecordMigratedSlotVisitor * record_visitor) [inline]
Definition at line 1790 of file mark-compact.cc.
      : EvacuateVisitorBase(heap, local_allocator, record_visitor) {}
Member Function Documentation
Visit()
bool v8::internal::EvacuateOldSpaceVisitor::Visit (Tagged< HeapObject > object, int size) [inline], [override], [virtual]
Implements v8::internal::HeapObjectVisitor.
Definition at line 1794 of file mark-compact.cc.
                                                                  {
    Tagged<HeapObject> target_object;
    if (TryEvacuateObject(
            PageMetadata::FromHeapObject(object)->owner_identity(), object,
            size, &target_object)) {
      DCHECK(object->map_word(heap_->isolate(), kRelaxedLoad)
                 .IsForwardingAddress());
      return true;
    }
    return false;
  }
References v8::internal::DCHECK(), v8::internal::PageMetadata::FromHeapObject(), v8::internal::EvacuateVisitorBase::heap_, v8::internal::Heap::isolate(), v8::kRelaxedLoad, size(), and v8::internal::EvacuateVisitorBase::TryEvacuateObject().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc