v8::internal::wasm::StructTypeBase Class Reference
#include <struct-types.h>
Classes
class BuilderImpl
Public Member Functions
StructTypeBase (uint32_t field_count, uint32_t *field_offsets, const ValueTypeBase *reps, const bool *mutabilities, bool is_descriptor, bool is_shared)
bool is_descriptor () const
bool is_shared () const
uint32_t field_count () const
ValueTypeBase field (uint32_t index) const
bool mutability (uint32_t index) const
base::iterator_range< const ValueTypeBase * > fields () const
base::iterator_range< const bool * > mutabilities () const
uint32_t field_offset (uint32_t index) const
uint32_t total_fields_size () const
uint32_t Align (uint32_t offset, uint32_t alignment, bool is_shared)
void InitializeOffsets ()
bool first_field_can_be_prototype () const
Static Public Attributes
static const size_t kMaxFieldOffset
Private Attributes
const uint16_t field_count_
const bool is_descriptor_
const bool is_shared_
uint32_t *const field_offsets_
const ValueTypeBase *const reps_
const bool *const mutabilities_
Friends
class StructType
class CanonicalStructType
Detailed Description
Definition at line 20 of file struct-types.h.
Constructor & Destructor Documentation
StructTypeBase()
v8::internal::wasm::StructTypeBase::StructTypeBase (uint32_t field_count, uint32_t * field_offsets, const ValueTypeBase * reps, const bool * mutabilities, bool is_descriptor, bool is_shared) [inline]
Definition at line 22 of file struct-types.h.
      : field_count_(field_count),
        is_descriptor_(is_descriptor),
        is_shared_(is_shared),
        field_offsets_(field_offsets),
        reps_(reps),
        mutabilities_(mutabilities) {
    DCHECK_LE(field_count, kV8MaxWasmStructFields);
  }
References DCHECK_LE, field_count(), and v8::internal::wasm::kV8MaxWasmStructFields.
Member Function Documentation
Align()
uint32_t v8::internal::wasm::StructTypeBase::Align (uint32_t offset, uint32_t alignment, bool is_shared) [inline]
Definition at line 76 of file struct-types.h.
                                                                      {
    return RoundUp(
        offset,
        std::min(alignment,
                 static_cast<uint32_t>(is_shared ? kDoubleSize : kTaggedSize)));
  }
References is_shared(), v8::internal::kDoubleSize, v8::internal::kTaggedSize, and RoundUp().
Referenced by InitializeOffsets().
field()
ValueTypeBase v8::internal::wasm::StructTypeBase::field (uint32_t index) const [inline]
Definition at line 40 of file struct-types.h.
                                            {
    DCHECK_LT(index, field_count_);
    return reps_[index];
  }
References DCHECK_LT, field_count_, v8::internal::index, and reps_.
Referenced by v8::internal::wasm::StructType::field(), v8::internal::wasm::CanonicalStructType::field(), and InitializeOffsets().
field_count()
uint32_t v8::internal::wasm::StructTypeBase::field_count () const [inline]
Definition at line 38 of file struct-types.h.
{ return field_count_; }
References field_count_.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::StructProxy::Count(), v8::internal::CreateWasmObject(), v8::internal::wasm::DecodeCanonicalTypeNames(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), field_offset(), v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomStructs(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateStructNewInitExpr(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetFirstFieldIfPrototype(), InitializeOffsets(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object(), v8::internal::wasm::CanonicalStructType::operator==(), v8::internal::wasm::StructType::operator==(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseStructGet(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseStructSet(), v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNew(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNewDefault(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_set(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructNew(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNew(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNewDefault(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNewImpl(), StructTypeBase(), total_fields_size(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidStructSubtypeDefinition(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
field_offset()
uint32_t v8::internal::wasm::StructTypeBase::field_offset (uint32_t index) const [inline]
Definition at line 61 of file struct-types.h.
                                              {
    DCHECK_LT(index, field_count());
    if (index == 0) {
      return is_descriptor() ? kTaggedSize : 0;
    }
    DCHECK(offsets_initialized_);
    return field_offsets_[index - 1];
  }
References v8::internal::DCHECK(), DCHECK_LT, field_count(), field_offsets_, v8::internal::index, is_descriptor(), and v8::internal::kTaggedSize.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructFieldOffset(), and v8::internal::wasm::StructFieldOffset().
fields()
base::iterator_range<const ValueTypeBase*> v8::internal::wasm::StructTypeBase::fields () const [inline]
Definition at line 51 of file struct-types.h.
                                                          {
    return {reps_, reps_ + field_count_};
  }
References field_count_, and reps_.
first_field_can_be_prototype()
bool v8::internal::wasm::StructTypeBase::first_field_can_be_prototype () const [inline]
Definition at line 138 of file struct-types.h.
                                            {
    return v8_flags.wasm_explicit_prototypes && is_descriptor_ &&
           field_count_ > 0 && !mutabilities_[0] &&
           reps_[0].is_reference_to(GenericKind::kExtern);
  }
References field_count_, is_descriptor_, v8::internal::wasm::ValueTypeBase::is_reference_to(), mutabilities_, reps_, and v8::internal::v8_flags.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetFirstFieldIfPrototype(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNewImpl().
InitializeOffsets()
void v8::internal::wasm::StructTypeBase::InitializeOffsets () [inline]
Definition at line 83 of file struct-types.h.
                           {
    if (field_count() == 0) return;
    DCHECK(!offsets_initialized_);
    if (is_descriptor() && is_shared()) {
      // TODO(42204563, 403372470): Implement shared custom descriptors and
      // update the offset calculation for the first field.
      UNIMPLEMENTED();
    }
    uint32_t offset = is_descriptor() ? kTaggedSize : 0;
    offset += field(0).value_kind_size();
    // Optimization: we track the last gap that was introduced by alignment,
    // and place any sufficiently-small fields in it.
    // It's important that the algorithm that assigns offsets to fields is
    // subtyping-safe, i.e. two lists of fields with a common prefix must
    // always compute the same offsets for the fields in this common prefix.
    uint32_t gap_position = 0;
    uint32_t gap_size = 0;
    for (uint32_t i = 1; i < field_count(); i++) {
      uint32_t field_size = field(i).value_kind_size();
      if (field_size <= gap_size) {
        uint32_t aligned_gap = Align(gap_position, field_size, is_shared());
        uint32_t gap_before = aligned_gap - gap_position;
        uint32_t aligned_gap_size = gap_size - gap_before;
        if (field_size <= aligned_gap_size) {
          field_offsets_[i - 1] = aligned_gap;
          uint32_t gap_after = aligned_gap_size - field_size;
          if (gap_before > gap_after) {
            // Keep old {gap_position}.
            gap_size = gap_before;
          } else {
            gap_position = aligned_gap + field_size;
            gap_size = gap_after;
          }
          continue; // Successfully placed the field in the gap.
        }
      }
      uint32_t old_offset = offset;
      offset = Align(offset, field_size, is_shared());
      uint32_t gap = offset - old_offset;
      if (gap > gap_size) {
        gap_size = gap;
        gap_position = old_offset;
      }
      field_offsets_[i - 1] = offset;
      offset += field_size;
    }
    offset = RoundUp(offset, kTaggedSize);
    field_offsets_[field_count() - 1] = offset;
#if DEBUG
    offsets_initialized_ = true;
#endif
  }
References Align(), v8::internal::DCHECK(), field(), field_count(), field_offsets_, is_descriptor(), is_shared(), v8::internal::kTaggedSize, RoundUp(), v8::internal::UNIMPLEMENTED(), and v8::internal::wasm::ValueTypeBase::value_kind_size().
is_descriptor()
bool v8::internal::wasm::StructTypeBase::is_descriptor () const [inline]
Definition at line 34 of file struct-types.h.
{ return is_descriptor_; }
References is_descriptor_.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), field_offset(), InitializeOffsets(), v8::internal::wasm::CanonicalStructType::operator==(), v8::internal::wasm::StructType::operator==(), and total_fields_size().
is_shared()
bool v8::internal::wasm::StructTypeBase::is_shared () const [inline]
Definition at line 36 of file struct-types.h.
{ return is_shared_; }
References is_shared_.
Referenced by Align(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), and InitializeOffsets().
mutabilities()
base::iterator_range<const bool*> v8::internal::wasm::StructTypeBase::mutabilities () const [inline]
Definition at line 54 of file struct-types.h.
                                                       {
    return {mutabilities_, mutabilities_ + field_count_};
  }
References field_count_, and mutabilities_.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add(), v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualStructType(), v8::internal::wasm::CanonicalStructType::operator==(), and v8::internal::wasm::StructType::operator==().
mutability()
bool v8::internal::wasm::StructTypeBase::mutability (uint32_t index) const [inline]
Definition at line 45 of file struct-types.h.
                                        {
    DCHECK_LT(index, field_count_);
    return mutabilities_[index];
  }
References DCHECK_LT, field_count_, v8::internal::index, and mutabilities_.
Referenced by v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::AddField(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomStructs(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_set(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidStructSubtypeDefinition(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
total_fields_size()
uint32_t v8::internal::wasm::StructTypeBase::total_fields_size () const [inline]
Definition at line 69 of file struct-types.h.
                                     {
    if (field_count() == 0) {
      return is_descriptor() ? kTaggedSize : 0;
    }
    return field_offsets_[field_count() - 1];
  }
References field_count(), field_offsets_, is_descriptor(), and v8::internal::kTaggedSize.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef().
Friends And Related Function Documentation
CanonicalStructType
friend class CanonicalStructType [friend]
Definition at line 227 of file struct-types.h.
StructType
friend class StructType [friend]
Definition at line 226 of file struct-types.h.
Member Data Documentation
field_count_
const uint16_t v8::internal::wasm::StructTypeBase::field_count_ [private]
Definition at line 230 of file struct-types.h.
Referenced by field(), field_count(), fields(), v8::internal::wasm::StructType::fields(), v8::internal::wasm::CanonicalStructType::fields(), first_field_can_be_prototype(), mutabilities(), and mutability().
field_offsets_
uint32_t* const v8::internal::wasm::StructTypeBase::field_offsets_ [private]
Definition at line 236 of file struct-types.h.
Referenced by field_offset(), InitializeOffsets(), and total_fields_size().
is_descriptor_
const bool v8::internal::wasm::StructTypeBase::is_descriptor_ [private]
Definition at line 231 of file struct-types.h.
Referenced by first_field_can_be_prototype(), and is_descriptor().
is_shared_
const bool v8::internal::wasm::StructTypeBase::is_shared_ [private]
Definition at line 232 of file struct-types.h.
Referenced by is_shared().
kMaxFieldOffset
const size_t v8::internal::wasm::StructTypeBase::kMaxFieldOffset [static]
Initial value:
=
      (kV8MaxWasmStructFields - 1) * kMaxValueTypeSize
Definition at line 222 of file struct-types.h.
mutabilities_
const bool* const v8::internal::wasm::StructTypeBase::mutabilities_ [private]
Definition at line 238 of file struct-types.h.
Referenced by first_field_can_be_prototype(), mutabilities(), and mutability().
reps_
const ValueTypeBase* const v8::internal::wasm::StructTypeBase::reps_ [private]
Definition at line 237 of file struct-types.h.
Referenced by field(), fields(), v8::internal::wasm::StructType::fields(), v8::internal::wasm::CanonicalStructType::fields(), and first_field_can_be_prototype().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/struct-types.h