v8::internal::compiler::PipelineCompilationJob Class Reference
Public Member Functions
PipelineCompilationJob (Isolate *isolate, Handle< SharedFunctionInfo > shared_info, Handle< JSFunction > function, BytecodeOffset osr_offset, CodeKind code_kind)
~PipelineCompilationJob () final
PipelineCompilationJob (const PipelineCompilationJob &)=delete
PipelineCompilationJob & operator= (const PipelineCompilationJob &)=delete
Protected Member Functions
Status PrepareJobImpl (Isolate *isolate) final
Status ExecuteJobImpl (RuntimeCallStats *stats, LocalIsolate *local_isolate) final
Status FinalizeJobImpl (Isolate *isolate) final
Private Attributes
Zone zone_
ZoneStats zone_stats_
OptimizedCompilationInfo compilation_info_
std::unique_ptr< TurbofanPipelineStatistics > pipeline_statistics_
TFPipelineData data_
turboshaft::PipelineData turboshaft_data_
PipelineImpl pipeline_
Linkage * linkage_
Additional Inherited Members
Detailed Description
Definition at line 506 of file pipeline.cc.
Constructor & Destructor Documentation
PipelineCompilationJob() [1/2]
v8::internal::compiler::PipelineCompilationJob::PipelineCompilationJob (Isolate * isolate, Handle< SharedFunctionInfo > shared_info, Handle< JSFunction > function, BytecodeOffset osr_offset, CodeKind code_kind)
Definition at line 533 of file pipeline.cc.
    : TurbofanCompilationJob(isolate, &compilation_info_,
                             CompilationJob::State::kReadyToPrepare),
      zone_(isolate->allocator(), kPipelineCompilationJobZoneName),
      zone_stats_(isolate->allocator()),
      compilation_info_(&zone_, isolate, shared_info, function, code_kind,
                        osr_offset),
      pipeline_statistics_(CreatePipelineStatistics(
          direct_handle(Cast<Script>(shared_info->script()), isolate),
          compilation_info(), isolate, &zone_stats_)),
      data_(&zone_stats_, isolate, compilation_info(),
            pipeline_statistics_.get()),
      turboshaft_data_(&zone_stats_, turboshaft::TurboshaftPipelineKind::kJS,
                       isolate, compilation_info(),
                       AssemblerOptions::Default(isolate)),
      pipeline_(&data_),
      linkage_(nullptr) {
  turboshaft_data_.set_pipeline_statistics(pipeline_statistics_.get());
}
References pipeline_statistics_, v8::internal::compiler::turboshaft::PipelineData::set_pipeline_statistics(), and turboshaft_data_.
 PipelineCompilationJob()
v8::internal::compiler::PipelineCompilationJob::~PipelineCompilationJob () [final], [default]
PipelineCompilationJob() [2/2]
v8::internal::compiler::PipelineCompilationJob::PipelineCompilationJob (const PipelineCompilationJob &) [delete]
Member Function Documentation
ExecuteJobImpl()
PipelineCompilationJob::Status v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl (RuntimeCallStats * stats, LocalIsolate * local_isolate) [final], [protected], [virtual]
Implements v8::internal::OptimizedCompilationJob.
Definition at line 764 of file pipeline.cc.
                                                          {
  // Ensure that the RuntimeCallStats table is only available during execution
  // and not during finalization as that might be on a different thread.
  PipelineJobScope scope(&data_, stats);
  LocalIsolateScope local_isolate_scope(data_.broker(), data_.info(),
                                        local_isolate);
  turboshaft_data_.InitializeBrokerAndDependencies(data_.broker_ptr(),
                                                   data_.dependencies());
  turboshaft::Pipeline turboshaft_pipeline(&turboshaft_data_);
  if (compilation_info_.was_cancelled()) {
    return AbortOptimization(BailoutReason::kCancelled);
  }
  if (V8_UNLIKELY(v8_flags.turbolev)) {
    if (!turboshaft_pipeline.CreateGraphWithMaglev(linkage_)) {
      return AbortOptimization(BailoutReason::kTurbofanGraphBuildingFailed);
    }
  } else {
    if (!pipeline_.CreateGraph(linkage_)) {
      return AbortOptimization(BailoutReason::kTurbofanGraphBuildingFailed);
    }
    // We selectively Unpark inside OptimizeTurbofanGraph.
    if (!pipeline_.OptimizeTurbofanGraph(linkage_)) return FAILED;
    // We convert the turbofan graph to turboshaft.
    if (!turboshaft_pipeline.CreateGraphFromTurbofan(&data_, linkage_)) {
      data_.EndPhaseKind();
      return FAILED;
    }
  }
  if (!turboshaft_pipeline.OptimizeTurboshaftGraph(linkage_)) {
    return FAILED;
  }
  const bool success = GenerateCodeFromTurboshaftGraph(
      linkage_, turboshaft_pipeline, &pipeline_, data_.osr_helper_ptr());
  return success ? SUCCEEDED : FAILED;
}
References v8::internal::TurbofanCompilationJob::AbortOptimization(), v8::internal::compiler::TFPipelineData::broker(), v8::internal::compiler::TFPipelineData::broker_ptr(), compilation_info_, v8::internal::compiler::PipelineImpl::CreateGraph(), v8::internal::compiler::turboshaft::Pipeline::CreateGraphFromTurbofan(), v8::internal::compiler::turboshaft::Pipeline::CreateGraphWithMaglev(), data_, v8::internal::compiler::TFPipelineData::dependencies(), v8::internal::compiler::TFPipelineData::EndPhaseKind(), v8::internal::CompilationJob::FAILED, v8::internal::compiler::anonymous_namespace{pipeline.cc}::GenerateCodeFromTurboshaftGraph(), v8::internal::compiler::TFPipelineData::info(), v8::internal::compiler::turboshaft::PipelineData::InitializeBrokerAndDependencies(), linkage_, v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph(), v8::internal::compiler::turboshaft::Pipeline::OptimizeTurboshaftGraph(), v8::internal::compiler::TFPipelineData::osr_helper_ptr(), pipeline_, v8::internal::CompilationJob::SUCCEEDED, turboshaft_data_, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::OptimizedCompilationInfo::was_cancelled().
FinalizeJobImpl()
PipelineCompilationJob::Status v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl (Isolate * isolate) [final], [protected], [virtual]
Implements v8::internal::OptimizedCompilationJob.
Definition at line 807 of file pipeline.cc.
                      {
  // Ensure that the RuntimeCallStats table of main thread is available for
  // phases happening during PrepareJob.
  PipelineJobScope scope(&data_, isolate->counters()->runtime_call_stats());
  RCS_SCOPE(isolate, RuntimeCallCounterId::kOptimizeFinalizePipelineJob);
  Handle<Code> code;
  DirectHandle<NativeContext> context;
  turboshaft::Pipeline turboshaft_pipeline(&turboshaft_data_);
  MaybeHandle<Code> maybe_code = turboshaft_pipeline.FinalizeCode();
  if (!maybe_code.ToHandle(&code)) {
    if (compilation_info()->bailout_reason() == BailoutReason::kNoReason) {
      return AbortOptimization(BailoutReason::kTurbofanCodeGenerationFailed);
    }
    return FAILED;
  }
  context = DirectHandle<NativeContext>(compilation_info()->native_context(),
                                        isolate);
  if (context->IsDetached(isolate)) {
    return AbortOptimization(BailoutReason::kDetachedNativeContext);
  }
  if (!CheckNoDeprecatedMaps(code, isolate)) {
    return RetryOptimization(BailoutReason::kConcurrentMapDeprecation);
  }
  if (!turboshaft_pipeline.CommitDependencies(code)) {
    return RetryOptimization(BailoutReason::kBailedOutDueToDependencyChange);
  }
  compilation_info()->SetCode(code);
  GlobalHandleVector<Map> maps = CollectRetainedMaps(isolate, code);
  RegisterWeakObjectsInOptimizedCode(isolate, context, code, std::move(maps));
  return SUCCEEDED;
}
References v8::internal::TurbofanCompilationJob::AbortOptimization(), v8::internal::compiler::CheckNoDeprecatedMaps(), code, v8::internal::OptimizedCompilationJob::CollectRetainedMaps(), v8::internal::compiler::turboshaft::Pipeline::CommitDependencies(), v8::internal::TurbofanCompilationJob::compilation_info(), v8::internal::Isolate::counters(), data_, v8::internal::CompilationJob::FAILED, v8::internal::compiler::turboshaft::Pipeline::FinalizeCode(), v8::internal::TurbofanCompilationJob::isolate(), v8::internal::native_context, RCS_SCOPE, v8::internal::OptimizedCompilationJob::RegisterWeakObjectsInOptimizedCode(), v8::internal::TurbofanCompilationJob::RetryOptimization(), v8::internal::Counters::runtime_call_stats(), v8::internal::OptimizedCompilationInfo::SetCode(), v8::internal::CompilationJob::SUCCEEDED, v8::internal::MaybeHandle< T >::ToHandle(), and turboshaft_data_.
operator=()
PipelineCompilationJob& v8::internal::compiler::PipelineCompilationJob::operator= (const PipelineCompilationJob &) [delete]
PrepareJobImpl()
PipelineCompilationJob::Status v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl (Isolate * isolate) [final], [protected], [virtual]
Implements v8::internal::OptimizedCompilationJob.
Definition at line 698 of file pipeline.cc.
                      {
  // Ensure that the RuntimeCallStats table of main thread is available for
  // phases happening during PrepareJob.
  PipelineJobScope scope(&data_, isolate->counters()->runtime_call_stats());
  if (compilation_info()->bytecode_array()->length() >
      v8_flags.max_optimized_bytecode_size) {
    return AbortOptimization(BailoutReason::kFunctionTooBig);
  }
  if (!v8_flags.always_turbofan) {
    compilation_info()->set_bailout_on_uninitialized();
  }
  if (v8_flags.turbo_loop_peeling) {
    compilation_info()->set_loop_peeling();
  }
  if (v8_flags.turbo_inlining) {
    compilation_info()->set_inlining();
  }
  if (v8_flags.turbo_allocation_folding) {
    compilation_info()->set_allocation_folding();
  }
  // Determine whether to specialize the code for the function's context.
  // We can't do this in the case of OSR, because we want to cache the
  // generated code on the native context keyed on SharedFunctionInfo.
  // TODO(mythria): Check if it is better to key the OSR cache on JSFunction and
  // allow context specialization for OSR code.
  if (!compilation_info()
           ->shared_info()
           ->function_context_independent_compiled() &&
      compilation_info()->closure()->raw_feedback_cell()->map() ==
          ReadOnlyRoots(isolate).one_closure_cell_map() &&
      !compilation_info()->is_osr()) {
    compilation_info()->set_function_context_specializing();
    data_.ChooseSpecializationContext();
  }
  if (compilation_info()->source_positions()) {
    SharedFunctionInfo::EnsureSourcePositionsAvailable(
        isolate, compilation_info()->shared_info());
  }
  data_.set_start_source_position(
      compilation_info()->shared_info()->StartPosition());
  linkage_ = compilation_info()->zone()->New<Linkage>(
      Linkage::ComputeIncoming(compilation_info()->zone(), compilation_info()));
  if (compilation_info()->is_osr()) data_.InitializeOsrHelper();
  // InitializeHeapBroker() and CreateGraph() may already use
  // IsPendingAllocation.
  isolate->heap()->PublishMainThreadPendingAllocations();
  if (!pipeline_.InitializeHeapBroker()) {
    return FAILED;
  }
  // Serialization may have allocated.
  isolate->heap()->PublishMainThreadPendingAllocations();
  return SUCCEEDED;
}
References v8::internal::TurbofanCompilationJob::AbortOptimization(), v8::internal::compiler::TFPipelineData::ChooseSpecializationContext(), v8::internal::TurbofanCompilationJob::compilation_info(), v8::internal::compiler::Linkage::ComputeIncoming(), v8::internal::Isolate::counters(), data_, v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), v8::internal::CompilationJob::FAILED, v8::internal::Isolate::heap(), v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), v8::internal::compiler::TFPipelineData::InitializeOsrHelper(), v8::internal::OptimizedCompilationInfo::is_osr(), v8::internal::TurbofanCompilationJob::isolate(), v8::internal::length, linkage_, v8::internal::Zone::New(), pipeline_, v8::internal::Heap::PublishMainThreadPendingAllocations(), v8::internal::compiler::raw_feedback_cell, v8::internal::Counters::runtime_call_stats(), v8::internal::compiler::TFPipelineData::set_start_source_position(), v8::internal::anonymous_namespace{debug-coverage.cc}::StartPosition(), v8::internal::CompilationJob::SUCCEEDED, v8::internal::v8_flags, and v8::internal::OptimizedCompilationInfo::zone().
Member Data Documentation
compilation_info_
OptimizedCompilationInfo v8::internal::compiler::PipelineCompilationJob::compilation_info_ [private]
Definition at line 525 of file pipeline.cc.
Referenced by ExecuteJobImpl().
data_
TFPipelineData v8::internal::compiler::PipelineCompilationJob::data_ [private]
Definition at line 527 of file pipeline.cc.
Referenced by v8::internal::compiler::PipelineImpl::CreateGraph(), ExecuteJobImpl(), FinalizeJobImpl(), v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), v8::internal::compiler::PipelineImpl::OptimizeTurbofanGraph(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::PipelineJobScope(), PrepareJobImpl(), v8::internal::compiler::PipelineImpl::Run(), and v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::~PipelineJobScope().
linkage_
Linkage* v8::internal::compiler::PipelineCompilationJob::linkage_ [private]
Definition at line 530 of file pipeline.cc.
Referenced by ExecuteJobImpl(), and PrepareJobImpl().
pipeline_
PipelineImpl v8::internal::compiler::PipelineCompilationJob::pipeline_ [private]
Definition at line 529 of file pipeline.cc.
Referenced by ExecuteJobImpl(), and PrepareJobImpl().
pipeline_statistics_
std::unique_ptr<TurbofanPipelineStatistics> v8::internal::compiler::PipelineCompilationJob::pipeline_statistics_ [private]
Definition at line 526 of file pipeline.cc.
Referenced by PipelineCompilationJob().
turboshaft_data_
turboshaft::PipelineData v8::internal::compiler::PipelineCompilationJob::turboshaft_data_ [private]
Definition at line 528 of file pipeline.cc.
Referenced by ExecuteJobImpl(), FinalizeJobImpl(), PipelineCompilationJob(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::PipelineJobScope(), and v8::internal::compiler::anonymous_namespace{pipeline.cc}::PipelineJobScope::~PipelineJobScope().
zone_
Zone v8::internal::compiler::PipelineCompilationJob::zone_ [private]
Definition at line 523 of file pipeline.cc.
zone_stats_
ZoneStats v8::internal::compiler::PipelineCompilationJob::zone_stats_ [private]
Definition at line 524 of file pipeline.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/pipeline.cc