v8::HeapProfiler Class Reference
Interface for controlling heap profiling.
#include <v8-profiler.h>
Classes
struct HeapSnapshotOptions
class ObjectNameResolver
Callback interface for retrieving user friendly names of global objects.
Public Types
enum SamplingFlags { kSamplingNoFlags = 0
, kSamplingForceGC = 1 << 0
, kSamplingIncludeObjectsCollectedByMajorGC = 1 << 1
, kSamplingIncludeObjectsCollectedByMinorGC = 1 << 2
 }
enum class HeapSnapshotMode { kRegular
, kExposeInternals
 }
enum class NumericsMode { kHideNumericValues
, kExposeNumericValues
 }
typedef void(* BuildEmbedderGraphCallback) (v8::Isolate *isolate, v8::EmbedderGraph *graph, void *data)
Callback function invoked during heap snapshot generation to retrieve the embedder object graph.
using GetDetachednessCallback = EmbedderGraph::Node::Detachedness(*)(v8::Isolate *isolate, const v8::Local< v8::Value > &v8_value, uint16_t class_id, void *data)
Callback function invoked during heap snapshot generation to retrieve the detachedness state of a JS object referenced by a TracedReference.
Public Member Functions
void QueryObjects (v8::Local< v8::Context > context, QueryObjectPredicate *predicate, std::vector< v8::Global< v8::Object >> *objects)
int GetSnapshotCount ()
Returns the number of snapshots taken.
const HeapSnapshot * GetHeapSnapshot (int index)
Returns a snapshot by index.
SnapshotObjectId GetObjectId (Local< Value > value)
Returns SnapshotObjectId for a heap object referenced by |value| if it has been seen by the heap profiler, kUnknownObjectId otherwise.
SnapshotObjectId GetObjectId (NativeObject value)
Returns SnapshotObjectId for a native object referenced by |value| if it has been seen by the heap profiler, kUnknownObjectId otherwise.
Local< Value > FindObjectById (SnapshotObjectId id)
Returns heap object with given SnapshotObjectId if the object is alive, otherwise empty handle is returned.
void ClearObjectIds ()
Clears internal map from SnapshotObjectId to heap object.
const HeapSnapshot * TakeHeapSnapshot (const HeapSnapshotOptions &options=HeapSnapshotOptions())
Takes a heap snapshot.
const HeapSnapshot * TakeHeapSnapshot (ActivityControl *control, ObjectNameResolver *global_object_name_resolver=nullptr, bool hide_internals=true, bool capture_numeric_value=false)
Takes a heap snapshot.
std::vector< v8::Local< v8::Value > > GetDetachedJSWrapperObjects ()
Obtains list of Detached JS Wrapper Objects.
void StartTrackingHeapObjects (bool track_allocations=false)
Starts tracking of heap objects population statistics.
SnapshotObjectId GetHeapStats (OutputStream *stream, int64_t *timestamp_us=nullptr)
Adds a new time interval entry to the aggregated statistics array.
void StopTrackingHeapObjects ()
Stops tracking of heap objects population statistics, cleans up all collected data.
bool StartSamplingHeapProfiler (uint64_t sample_interval=512 *1024, int stack_depth=16, SamplingFlags flags=kSamplingNoFlags)
Starts gathering a sampling heap profile.
void StopSamplingHeapProfiler ()
Stops the sampling heap profile and discards the current profile.
AllocationProfile * GetAllocationProfile ()
Returns the sampled profile of allocations allocated (and still live) since StartSamplingHeapProfiler was called.
void DeleteAllHeapSnapshots ()
Deletes all snapshots taken.
void AddBuildEmbedderGraphCallback (BuildEmbedderGraphCallback callback, void *data)
void RemoveBuildEmbedderGraphCallback (BuildEmbedderGraphCallback callback, void *data)
void SetGetDetachednessCallback (GetDetachednessCallback callback, void *data)
bool IsTakingSnapshot ()
Returns whether the heap profiler is currently taking a snapshot.
const char * CopyNameForHeapSnapshot (const char *name)
Allocates a copy of the provided string within the heap snapshot generator and returns a pointer to the copy.
Static Public Attributes
static const SnapshotObjectId kUnknownObjectId = 0
A constant for invalid SnapshotObjectId.
static const uint16_t kPersistentHandleNoClassId = 0
Default value of persistent handle class ID.
Private Member Functions
HeapProfiler ()
~HeapProfiler ()
HeapProfiler (const HeapProfiler &)
HeapProfiler & operator= (const HeapProfiler &)
Detailed Description
Interface for controlling heap profiling.
Instance of the profiler can be retrieved using v8::Isolate::GetHeapProfiler.
Definition at line 969 of file v8-profiler.h.
Member Typedef Documentation
BuildEmbedderGraphCallback
typedef void(* v8::HeapProfiler::BuildEmbedderGraphCallback) (v8::Isolate *isolate, v8::EmbedderGraph *graph, void *data)
Callback function invoked during heap snapshot generation to retrieve the embedder object graph.
The callback should use graph->AddEdge(..) to add references between the objects. The callback must not trigger garbage collection in V8.
Definition at line 988 of file v8-profiler.h.
GetDetachednessCallback
using v8::HeapProfiler::GetDetachednessCallback = EmbedderGraph::Node::Detachedness (*)(v8::Isolate* isolate, const v8::Local<v8::Value>& v8_value, uint16_t class_id, void* data)
Callback function invoked during heap snapshot generation to retrieve the detachedness state of a JS object referenced by a TracedReference.
The callback takes Local<Value> as parameter to allow the embedder to unpack the TracedReference into a Local and reuse that Local for different purposes.
Definition at line 1000 of file v8-profiler.h.
Member Enumeration Documentation
HeapSnapshotMode
enum v8::HeapProfiler::HeapSnapshotMode [strong]
Enumerator
kRegular Heap snapshot for regular developers.
kExposeInternals Heap snapshot is exposing internals that may be useful for experts.
Definition at line 1057 of file v8-profiler.h.
                              {
    /**
     * Heap snapshot for regular developers.
     */
    kRegular,
    /**
     * Heap snapshot is exposing internals that may be useful for experts.
     */
    kExposeInternals,
  };
NumericsMode
enum v8::HeapProfiler::NumericsMode [strong]
Enumerator
kHideNumericValues Numeric values are hidden as they are values of the corresponding objects.
kExposeNumericValues Numeric values are exposed in artificial fields.
Definition at line 1068 of file v8-profiler.h.
                          {
    /**
     * Numeric values are hidden as they are values of the corresponding
     * objects.
     */
    kHideNumericValues,
    /**
     * Numeric values are exposed in artificial fields.
     */
    kExposeNumericValues
  };
SamplingFlags
enum v8::HeapProfiler::SamplingFlags
Enumerator
kSamplingNoFlags
kSamplingForceGC
kSamplingIncludeObjectsCollectedByMajorGC
kSamplingIncludeObjectsCollectedByMinorGC
Definition at line 975 of file v8-profiler.h.
                     {
    kSamplingNoFlags = 0,
    kSamplingForceGC = 1 << 0,
    kSamplingIncludeObjectsCollectedByMajorGC = 1 << 1,
    kSamplingIncludeObjectsCollectedByMinorGC = 1 << 2,
  };
Constructor & Destructor Documentation
HeapProfiler() [1/2]
v8::HeapProfiler::HeapProfiler () [private]
 HeapProfiler()
v8::HeapProfiler::~HeapProfiler () [private]
HeapProfiler() [2/2]
v8::HeapProfiler::HeapProfiler (const HeapProfiler &) [private]
Member Function Documentation
AddBuildEmbedderGraphCallback()
void v8::HeapProfiler::AddBuildEmbedderGraphCallback (BuildEmbedderGraphCallback callback, void * data)
Definition at line 11825 of file api.cc.
                                                     {
  reinterpret_cast<i::HeapProfiler*>(this)->AddBuildEmbedderGraphCallback(
      callback, data);
}
ClearObjectIds()
void v8::HeapProfiler::ClearObjectIds ()
Clears internal map from SnapshotObjectId to heap object.
The new objects will not be added into it unless a heap snapshot is taken or heap object tracking is kicked off.
Definition at line 11755 of file api.cc.
                                  {
  reinterpret_cast<i::HeapProfiler*>(this)->ClearHeapObjectMap();
}
Referenced by v8_inspector::V8HeapProfilerAgentImpl::disable().
CopyNameForHeapSnapshot()
const char * v8::HeapProfiler::CopyNameForHeapSnapshot (const char * name)
Allocates a copy of the provided string within the heap snapshot generator and returns a pointer to the copy.
May only be called during heap snapshot generation.
Definition at line 11847 of file api.cc.
                                                                  {
  return reinterpret_cast<i::HeapProfiler*>(this)->CopyNameForHeapSnapshot(
      name);
}
References name.
DeleteAllHeapSnapshots()
void v8::HeapProfiler::DeleteAllHeapSnapshots ()
Deletes all snapshots taken.
All previously returned pointers to snapshots and their contents become invalid after this call.
Definition at line 11815 of file api.cc.
                                          {
  reinterpret_cast<i::HeapProfiler*>(this)->DeleteAllSnapshots();
}
FindObjectById()
Local< Value > v8::HeapProfiler::FindObjectById (SnapshotObjectId id)
Returns heap object with given SnapshotObjectId if the object is alive, otherwise empty handle is returned.
Definition at line 11748 of file api.cc.
                                                             {
  i::DirectHandle<i::Object> obj =
      reinterpret_cast<i::HeapProfiler*>(this)->FindHeapObjectById(id);
  if (obj.is_null()) return {};
  return Utils::ToLocal(obj);
}
References v8::internal::DirectHandle< T >::is_null().
Referenced by v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::objectByHeapObjectId().
GetAllocationProfile()
AllocationProfile * v8::HeapProfiler::GetAllocationProfile ()
Returns the sampled profile of allocations allocated (and still live) since StartSamplingHeapProfiler was called.
The ownership of the pointer is transferred to the caller. Returns nullptr if sampling heap profiler is not active.
Definition at line 11811 of file api.cc.
                                                      {
  return reinterpret_cast<i::HeapProfiler*>(this)->GetAllocationProfile();
}
Referenced by v8_inspector::V8HeapProfilerAgentImpl::getSamplingProfile().
GetDetachedJSWrapperObjects()
std::vector< v8::Local< v8::Value > > v8::HeapProfiler::GetDetachedJSWrapperObjects ()
Obtains list of Detached JS Wrapper Objects.
This functon calls garbage collection, then iterates over traced handles in the isolate
Definition at line 11780 of file api.cc.
                                                                      {
  return reinterpret_cast<i::HeapProfiler*>(this)
      ->GetDetachedJSWrapperObjects();
}
GetHeapSnapshot()
const HeapSnapshot * v8::HeapProfiler::GetHeapSnapshot (int index)
Returns a snapshot by index.
Definition at line 11734 of file api.cc.
                                                           {
  return reinterpret_cast<const HeapSnapshot*>(
      reinterpret_cast<i::HeapProfiler*>(this)->GetSnapshot(index));
}
References v8::internal::index.
GetHeapStats()
SnapshotObjectId v8::HeapProfiler::GetHeapStats (OutputStream * stream, int64_t * timestamp_us = nullptr)
Adds a new time interval entry to the aggregated statistics array.
The time interval entry contains information on the current heap objects population size. The method also updates aggregated statistics and reports updates for all previous time intervals via the OutputStream object. Updates on each time interval are provided as a stream of the HeapStatsUpdate structure instances. If |timestamp_us| is supplied, timestamp of the new entry will be written into it. The return value of the function is the last seen heap object Id.
StartTrackingHeapObjects must be called before the first call to this method.
Definition at line 11794 of file api.cc.
                                                                   {
  i::HeapProfiler* heap_profiler = reinterpret_cast<i::HeapProfiler*>(this);
  return heap_profiler->PushHeapObjectsStats(stream, timestamp_us);
}
References v8::internal::HeapProfiler::PushHeapObjectsStats().
Referenced by v8_inspector::V8HeapProfilerAgentImpl::requestHeapStatsUpdate().
GetObjectId() [1/2]
SnapshotObjectId v8::HeapProfiler::GetObjectId (Local< Value > value)
Returns SnapshotObjectId for a heap object referenced by |value| if it has been seen by the heap profiler, kUnknownObjectId otherwise.
Definition at line 11739 of file api.cc.
                                                             {
  auto obj = Utils::OpenDirectHandle(*value);
  return reinterpret_cast<i::HeapProfiler*>(this)->GetSnapshotObjectId(obj);
}
References v8::Utils::OpenDirectHandle(), and v8::internal::value.
Referenced by v8_inspector::V8HeapProfilerAgentImpl::getHeapObjectId().
GetObjectId() [2/2]
SnapshotObjectId v8::HeapProfiler::GetObjectId (NativeObject value)
Returns SnapshotObjectId for a native object referenced by |value| if it has been seen by the heap profiler, kUnknownObjectId otherwise.
Definition at line 11744 of file api.cc.
                                                             {
  return reinterpret_cast<i::HeapProfiler*>(this)->GetSnapshotObjectId(value);
}
References v8::internal::value.
GetSnapshotCount()
int v8::HeapProfiler::GetSnapshotCount ()
Returns the number of snapshots taken.
Definition at line 11719 of file api.cc.
                                   {
  return reinterpret_cast<i::HeapProfiler*>(this)->GetSnapshotsCount();
}
IsTakingSnapshot()
bool v8::HeapProfiler::IsTakingSnapshot ()
Returns whether the heap profiler is currently taking a snapshot.
Definition at line 11843 of file api.cc.
                                    {
  return reinterpret_cast<i::HeapProfiler*>(this)->IsTakingSnapshot();
}
operator=()
HeapProfiler& v8::HeapProfiler::operator= (const HeapProfiler &) [private]
QueryObjects()
void v8::HeapProfiler::QueryObjects (v8::Local< v8::Context > context, QueryObjectPredicate * predicate, std::vector< v8::Global< v8::Object >> * objects)
Definition at line 11723 of file api.cc.
                                                                    {
  i::Isolate* isolate = i::Isolate::Current();
  i::HeapProfiler* profiler = reinterpret_cast<i::HeapProfiler*>(this);
  DCHECK_EQ(isolate, profiler->isolate());
  EnterV8NoScriptNoExceptionScope api_scope(isolate);
  profiler->QueryObjects(Utils::OpenDirectHandle(*v8_context), predicate,
                         objects);
}
References v8::internal::Isolate::Current(), DCHECK_EQ, v8::internal::HeapProfiler::isolate(), v8::Utils::OpenDirectHandle(), and v8::internal::HeapProfiler::QueryObjects().
Referenced by v8_inspector::V8Debugger::queryObjects().
RemoveBuildEmbedderGraphCallback()
void v8::HeapProfiler::RemoveBuildEmbedderGraphCallback (BuildEmbedderGraphCallback callback, void * data)
Definition at line 11831 of file api.cc.
                                                     {
  reinterpret_cast<i::HeapProfiler*>(this)->RemoveBuildEmbedderGraphCallback(
      callback, data);
}
SetGetDetachednessCallback()
void v8::HeapProfiler::SetGetDetachednessCallback (GetDetachednessCallback callback, void * data)
Definition at line 11837 of file api.cc.
                                                          {
  reinterpret_cast<i::HeapProfiler*>(this)->SetGetDetachednessCallback(callback,
                                                                       data);
}
StartSamplingHeapProfiler()
bool v8::HeapProfiler::StartSamplingHeapProfiler (uint64_t sample_interval = 512 * 1024, int stack_depth = 16, SamplingFlags flags = kSamplingNoFlags)
Starts gathering a sampling heap profile.
A sampling heap profile is similar to tcmalloc's heap profiler and Go's mprof. It samples object allocations and builds an online 'sampling' heap profile. At any point in time, this profile is expected to be a representative sample of objects currently live in the system. Each sampled allocation includes the stack trace at the time of allocation, which makes this really useful for memory leak detection.
This mechanism is intended to be cheap enough that it can be used in production with minimal performance overhead.
Allocations are sampled using a randomized Poisson process. On average, one allocation will be sampled every |sample_interval| bytes allocated. The |stack_depth| parameter controls the maximum number of stack frames to be captured on each allocation.
NOTE: Support for native allocations doesn't exist yet, but is anticipated in the future.
Objects allocated before the sampling is started will not be included in the profile.
Returns false if a sampling heap profiler is already running.
Definition at line 11800 of file api.cc.
                                                                  {
  return reinterpret_cast<i::HeapProfiler*>(this)->StartSamplingHeapProfiler(
      sample_interval, stack_depth, flags);
}
References flags().
Referenced by v8_inspector::V8HeapProfilerAgentImpl::startSampling().
StartTrackingHeapObjects()
void v8::HeapProfiler::StartTrackingHeapObjects (bool track_allocations = false)
Starts tracking of heap objects population statistics.
After calling this method, all heap objects relocations done by the garbage collector are being registered.
|track_allocations| parameter controls whether stack trace of each allocation in the heap will be recorded and reported as part of HeapSnapshot.
Definition at line 11785 of file api.cc.
                                                                  {
  reinterpret_cast<i::HeapProfiler*>(this)->StartHeapObjectsTracking(
      track_allocations);
}
Referenced by v8_inspector::V8HeapProfilerAgentImpl::startTrackingHeapObjectsInternal().
StopSamplingHeapProfiler()
void v8::HeapProfiler::StopSamplingHeapProfiler ()
Stops the sampling heap profile and discards the current profile.
Definition at line 11807 of file api.cc.
                                            {
  reinterpret_cast<i::HeapProfiler*>(this)->StopSamplingHeapProfiler();
}
Referenced by v8_inspector::V8HeapProfilerAgentImpl::disable(), and v8_inspector::V8HeapProfilerAgentImpl::stopSampling().
StopTrackingHeapObjects()
void v8::HeapProfiler::StopTrackingHeapObjects ()
Stops tracking of heap objects population statistics, cleans up all collected data.
StartHeapObjectsTracking must be called again prior to calling GetHeapStats next time.
Definition at line 11790 of file api.cc.
                                           {
  reinterpret_cast<i::HeapProfiler*>(this)->StopHeapObjectsTracking();
}
Referenced by v8_inspector::V8HeapProfilerAgentImpl::stopTrackingHeapObjectsInternal().
TakeHeapSnapshot() [1/2]
const HeapSnapshot * v8::HeapProfiler::TakeHeapSnapshot (ActivityControl * control, ObjectNameResolver * global_object_name_resolver = nullptr, bool hide_internals = true, bool capture_numeric_value = false)
Takes a heap snapshot.
See HeapSnapshotOptions for details on the parameters.
Returns
the snapshot.
Definition at line 11765 of file api.cc.
                                                                               {
  HeapSnapshotOptions options;
  options.control = control;
  options.global_object_name_resolver = resolver;
  options.snapshot_mode = hide_internals ? HeapSnapshotMode::kRegular
                                         : HeapSnapshotMode::kExposeInternals;
  options.numerics_mode = capture_numeric_value
                              ? NumericsMode::kExposeNumericValues
                              : NumericsMode::kHideNumericValues;
  return TakeHeapSnapshot(options);
}
References v8::HeapProfiler::HeapSnapshotOptions::control, v8::HeapProfiler::HeapSnapshotOptions::global_object_name_resolver, kExposeInternals, kExposeNumericValues, kHideNumericValues, kRegular, v8::HeapProfiler::HeapSnapshotOptions::numerics_mode, v8::HeapProfiler::HeapSnapshotOptions::snapshot_mode, and TakeHeapSnapshot().
TakeHeapSnapshot() [2/2]
const HeapSnapshot * v8::HeapProfiler::TakeHeapSnapshot (const HeapSnapshotOptions & options = HeapSnapshotOptions())
Takes a heap snapshot.
Returns
the snapshot.
Definition at line 11759 of file api.cc.
                                        {
  return reinterpret_cast<const HeapSnapshot*>(
      reinterpret_cast<i::HeapProfiler*>(this)->TakeSnapshot(options));
}
Referenced by TakeHeapSnapshot(), and v8_inspector::V8HeapProfilerAgentImpl::takeHeapSnapshotNow().
Member Data Documentation
kPersistentHandleNoClassId
const uint16_t v8::HeapProfiler::kPersistentHandleNoClassId = 0 [static]
Default value of persistent handle class ID.
Must not be used to define a class. Can be used to reset a class of a persistent handle.
Definition at line 1240 of file v8-profiler.h.
Referenced by v8::internal::NodeBase< Child >::CheckNodeIsFreeNode(), v8::internal::NodeBase< Child >::ClearFields(), and v8::internal::NodeBase< Child >::has_wrapper_class_id().
kUnknownObjectId
STATIC_CONST_MEMBER_DEFINITION const SnapshotObjectId v8::HeapProfiler::kUnknownObjectId = 0 [static]
A constant for invalid SnapshotObjectId.
GetSnapshotObjectId will return it in case heap profiler cannot find id for the object passed as parameter. HeapSnapshot::GetNodeById will always return NULL for such id.
Definition at line 1040 of file v8-profiler.h.
Referenced by v8::internal::HeapObjectsMap::FindEntry(), v8::internal::HeapObjectsMap::FindMergedNativeEntry(), and v8::internal::HeapProfiler::GetSnapshotObjectId().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-profiler.h
/mnt/V8SourceCode/src/api/api.cc