v8::internal::compiler::JSGraphAssembler Class Reference
#include <graph-assembler.h>
Classes
class CatchScope
class IfBuilder0
class IfBuilder1
Public Types
using NodeGenerator0 = std::function< TNode< Object >()>
using VoidGenerator0 = std::function< void()>
Public Member Functions
JSGraphAssembler (JSHeapBroker *broker, JSGraph *jsgraph, Zone *zone, BranchSemantics branch_semantics, std::optional< NodeChangedCallback > node_changed_callback=std::nullopt, bool mark_loop_exits=false)
TNode< Smi > SmiConstant (int32_t value)
TNode< HeapObject > HeapConstant (Handle< HeapObject > object)
TNode< Object > Constant (ObjectRef ref)
TNode< Number > NumberConstant (double value)
Node * CEntryStubConstant (int result_size)
Node * Allocate (AllocationType allocation, Node *size)
TNode< Map > LoadMap (TNode< HeapObject > object)
Node * LoadField (FieldAccess const &, Node *object)
template<typename T >
TNode< T > LoadField (FieldAccess const &access, TNode< HeapObject > object)
TNode< Uint32T > LoadElementsKind (TNode< Map > map)
Node * LoadElement (ElementAccess const &, Node *object, Node *index)
template<typename T >
TNode< T > LoadElement (ElementAccess const &access, TNode< HeapObject > object, TNode< Number > index)
Node * StoreField (FieldAccess const &, Node *object, Node *value)
Node * StoreElement (ElementAccess const &, Node *object, Node *index, Node *value)
Node * ClearPendingMessage ()
void TransitionAndStoreElement (MapRef double_map, MapRef fast_map, TNode< HeapObject > object, TNode< Number > index, TNode< Object > value)
TNode< Number > StringLength (TNode< String > string)
TNode< Boolean > ReferenceEqual (TNode< Object > lhs, TNode< Object > rhs)
TNode< Number > PlainPrimitiveToNumber (TNode< Object > value)
TNode< Number > NumberMin (TNode< Number > lhs, TNode< Number > rhs)
TNode< Number > NumberMax (TNode< Number > lhs, TNode< Number > rhs)
TNode< Boolean > NumberEqual (TNode< Number > lhs, TNode< Number > rhs)
TNode< Boolean > NumberLessThan (TNode< Number > lhs, TNode< Number > rhs)
TNode< Boolean > NumberLessThanOrEqual (TNode< Number > lhs, TNode< Number > rhs)
TNode< Number > NumberAdd (TNode< Number > lhs, TNode< Number > rhs)
TNode< Number > NumberSubtract (TNode< Number > lhs, TNode< Number > rhs)
TNode< Number > NumberShiftRightLogical (TNode< Number > lhs, TNode< Number > rhs)
TNode< Number > NumberBitwiseAnd (TNode< Number > lhs, TNode< Number > rhs)
TNode< Number > NumberBitwiseOr (TNode< Number > lhs, TNode< Number > rhs)
TNode< Number > NumberDivide (TNode< Number > lhs, TNode< Number > rhs)
TNode< Number > NumberFloor (TNode< Number > value)
TNode< String > StringSubstring (TNode< String > string, TNode< Number > from, TNode< Number > to)
TNode< Boolean > ObjectIsCallable (TNode< Object > value)
TNode< Boolean > ObjectIsSmi (TNode< Object > value)
TNode< Boolean > ObjectIsUndetectable (TNode< Object > value)
Node * BooleanNot (Node *cond)
Node * CheckSmi (Node *value, const FeedbackSource &feedback={})
Node * CheckNumber (Node *value, const FeedbackSource &feedback={})
Node * CheckNumberFitsInt32 (Node *value, const FeedbackSource &feedback={})
Node * CheckIf (Node *cond, DeoptimizeReason reason, const FeedbackSource &feedback={})
Node * Assert (Node *cond, const char *condition_string=``, const char *file=``, int line=-1)
void Assert (TNode< Word32T > cond, const char *condition_string=``, const char *file=``, int line=-1)
void DetachContextCell (TNode< Object > context, TNode< Object > new_value, int index, FrameState frame_state)
TNode< Boolean > NumberIsFloat64Hole (TNode< Number > value)
TNode< Boolean > ToBoolean (TNode< Object > value)
TNode< Object > ConvertTaggedHoleToUndefined (TNode< Object > value)
TNode< FixedArrayBase > MaybeGrowFastElements (ElementsKind kind, const FeedbackSource &feedback, TNode< JSArray > array, TNode< FixedArrayBase > elements, TNode< Number > new_length, TNode< Number > old_length)
Node * StringCharCodeAt (TNode< String > string, TNode< Number > position)
TNode< String > StringFromSingleCharCode (TNode< Number > code)
TNode< Object > DoubleArrayMax (TNode< JSArray > array)
TNode< Object > DoubleArrayMin (TNode< JSArray > array)
TNode< Number > ArrayBufferViewByteLength (TNode< JSArrayBufferView > array_buffer_view, InstanceType instance_type, std::set< ElementsKind > elements_kinds_candidates, TNode< Context > context)
TNode< Word32T > ArrayBufferDetachedBit (TNode< HeapObject > buffer)
TNode< Word32T > ArrayBufferViewDetachedBit (TNode< JSArrayBufferView > array_buffer_view)
TNode< Number > TypedArrayLength (TNode< JSTypedArray > typed_array, std::set< ElementsKind > elements_kinds_candidates, TNode< Context > context)
void CheckIfTypedArrayWasDetachedOrOutOfBounds (TNode< JSTypedArray > typed_array, std::set< ElementsKind > elements_kinds_candidates, const FeedbackSource &feedback)
TNode< Uint32T > LookupByteShiftForElementsKind (TNode< Uint32T > elements_kind)
TNode< Uint32T > LookupByteSizeForElementsKind (TNode< Uint32T > elements_kind)
TNode< Object > JSCallRuntime1 (Runtime::FunctionId function_id, TNode< Object > arg0, TNode< Context > context, std::optional< FrameState > frame_state, Operator::Properties properties=Operator::kNoProperties)
TNode< Object > JSCallRuntime2 (Runtime::FunctionId function_id, TNode< Object > arg0, TNode< Object > arg1, TNode< Context > context, FrameState frame_state)
Node * Chained (const Operator *op, Node *input)
JSHeapBroker * broker () const
JSGraph * jsgraph () const
Isolate * isolate () const
SimplifiedOperatorBuilder * simplified () override
JSOperatorBuilder * javascript () const
template<typename T , typename U >
TNode< T > EnterMachineGraph (TNode< U > input, UseInfo use_info)
template<typename T , typename U >
TNode< T > ExitMachineGraph (TNode< U > input, MachineRepresentation output_representation, Type output_type)
CatchScope * catch_scope () const
Node * outermost_handler () const
TNode< Object > MayThrow (const NodeGenerator0 &body)
IfBuilder0< Boolean > If (TNode< Boolean > cond)
IfBuilder0< Boolean > IfNot (TNode< Boolean > cond)
IfBuilder0< Word32T > MachineIf (TNode< Word32T > cond)
template<typename T >
IfBuilder1< T, Boolean > SelectIf (TNode< Boolean > cond)
template<typename T >
IfBuilder1< T, Boolean > SelectIfNot (TNode< Boolean > cond)
template<typename T >
IfBuilder1< T, Word32T > MachineSelectIf (TNode< Word32T > cond)
template<typename T >
TNode< T > MachineSelect (TNode< Word32T > cond, TNode< T > true_value, TNode< T > false_value, BranchHint hint=BranchHint::kNone)
Protected Member Functions
Operator const * PlainPrimitiveToNumberOperator ()
Protected Attributes
CatchScope outermost_catch_scope_
Node * outermost_handler_
CatchScope * catch_scope_
Private Attributes
JSHeapBroker * broker_
JSGraph * jsgraph_
SetOncePointer< Operator const > to_number_operator_
Friends
class CatchScope
Detailed Description
Definition at line 953 of file graph-assembler.h.
Member Typedef Documentation
NodeGenerator0
using v8::internal::compiler::JSGraphAssembler::NodeGenerator0 = std::function<TNode<Object>()>
Definition at line 1224 of file graph-assembler.h.
VoidGenerator0
using v8::internal::compiler::JSGraphAssembler::VoidGenerator0 = std::function<void()>
Definition at line 1247 of file graph-assembler.h.
Constructor & Destructor Documentation
JSGraphAssembler()
v8::internal::compiler::JSGraphAssembler::JSGraphAssembler (JSHeapBroker * broker, JSGraph * jsgraph, Zone * zone, BranchSemantics branch_semantics, std::optional< NodeChangedCallback > node_changed_callback = std::nullopt, bool mark_loop_exits = false) [inline]
Definition at line 957 of file graph-assembler.h.
      : GraphAssembler(jsgraph, zone, branch_semantics, node_changed_callback,
                       mark_loop_exits),
        broker_(broker),
        jsgraph_(jsgraph),
        outermost_catch_scope_(CatchScope::Outermost(zone)),
        catch_scope_(&outermost_catch_scope_) {
    outermost_catch_scope_.set_gasm(this);
  }
Member Function Documentation
Allocate()
Node * v8::internal::compiler::JSGraphAssembler::Allocate (AllocationType allocation, Node * size)
Definition at line 301 of file graph-assembler.cc.
                                                                      {
  return AddNode(
      graph()->NewNode(simplified()->AllocateRaw(Type::Any(), allocation), size,
                       effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::maglev::anonymous_namespace{maglev-assembler-arm.cc}::AllocateRaw(), v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), simplified(), and size().
ArrayBufferDetachedBit()
TNode< Word32T > v8::internal::compiler::JSGraphAssembler::ArrayBufferDetachedBit (TNode< HeapObject > buffer)
Definition at line 979 of file graph-assembler.cc.
                              {
  TNode<Word32T> bitfield = EnterMachineGraph<Word32T>(
      LoadField<Word32T>(AccessBuilder::ForJSArrayBufferBitField(), buffer),
      UseInfo::TruncatingWord32());
  return Word32And(bitfield,
                   Uint32Constant(JSArrayBuffer::WasDetachedBit::kMask));
}
References v8::internal::compiler::AccessBuilder::ForJSArrayBufferBitField(), v8::internal::compiler::UseInfo::TruncatingWord32(), and v8::internal::compiler::GraphAssembler::Uint32Constant().
Referenced by ArrayBufferViewDetachedBit().
ArrayBufferViewByteLength()
TNode< Number > v8::internal::compiler::JSGraphAssembler::ArrayBufferViewByteLength (TNode< JSArrayBufferView > array_buffer_view, InstanceType instance_type, std::set< ElementsKind > elements_kinds_candidates, TNode< Context > context)
Definition at line 968 of file graph-assembler.cc.
                                                                            {
  ArrayBufferViewAccessBuilder builder(this, instance_type,
                                       std::move(elements_kinds_candidates));
  return ExitMachineGraph<Number>(
      builder.BuildByteLength(array_buffer_view, context),
      MachineType::PointerRepresentation(),
      TypeCache::Get()->kJSArrayBufferByteLengthType);
}
References v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildByteLength(), v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kJSArrayBufferByteLengthType, and v8::internal::MachineType::PointerRepresentation().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewByteLengthAccessor().
ArrayBufferViewDetachedBit()
TNode< Word32T > v8::internal::compiler::JSGraphAssembler::ArrayBufferViewDetachedBit (TNode< JSArrayBufferView > array_buffer_view)
Definition at line 988 of file graph-assembler.cc.
                                                {
  TNode<HeapObject> buffer = LoadField<HeapObject>(
      AccessBuilder::ForJSArrayBufferViewBuffer(), array_buffer_view);
  return ArrayBufferDetachedBit(buffer);
}
References ArrayBufferDetachedBit(), and v8::internal::compiler::AccessBuilder::ForJSArrayBufferViewBuffer().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), and v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength().
Assert() [1/2]
Node * v8::internal::compiler::JSGraphAssembler::Assert (Node * cond, const char * condition_string = ``, const char * file = ``, int line = -1)
Definition at line 504 of file graph-assembler.cc.
                                                           {
  return AddNode(graph()->NewNode(
      common()->Assert(BranchSemantics::kJS, condition_string, file, line),
      cond, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::common(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), file(), v8::internal::compiler::GraphAssembler::graph(), and v8::internal::compiler::kJS.
Referenced by Assert().
Assert() [2/2]
void v8::internal::compiler::JSGraphAssembler::Assert (TNode< Word32T > cond, const char * condition_string = ``, const char * file = ``, int line = -1)
Definition at line 511 of file graph-assembler.cc.
                                                          {
  AddNode(graph()->NewNode(
      common()->Assert(BranchSemantics::kMachine, condition_string, file, line),
      cond, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), Assert(), v8::internal::compiler::GraphAssembler::common(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), file(), v8::internal::compiler::GraphAssembler::graph(), and v8::internal::compiler::kMachine.
BooleanNot()
Node * v8::internal::compiler::JSGraphAssembler::BooleanNot (Node * cond)
Definition at line 477 of file graph-assembler.cc.
                                             {
  return AddNode(graph()->NewNode(simplified()->BooleanNot(), cond));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::graph(), and simplified().
broker()
JSHeapBroker* v8::internal::compiler::JSGraphAssembler::broker () const [inline]
Definition at line 1100 of file graph-assembler.h.
{ return broker_; }
Referenced by v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), Constant(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateFunctionContext(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith().
catch_scope()
CatchScope* v8::internal::compiler::JSGraphAssembler::catch_scope () const [inline]
Definition at line 1221 of file graph-assembler.h.
{ return catch_scope_; }
Referenced by v8::internal::compiler::JSCallReducerAssembler::TryCatchBuilder0::Catch(), v8::internal::compiler::JSCallReducer::ReleaseEffectAndControlFromAssembler(), v8::internal::compiler::JSNativeContextSpecialization::ReleaseEffectAndControlFromAssembler(), and v8::internal::compiler::JSCallReducer::ReplaceWithSubgraph().
CEntryStubConstant()
Node * v8::internal::compiler::JSGraphAssembler::CEntryStubConstant (int result_size)
Definition at line 135 of file graph-assembler.cc.
                                                          {
  return AddClonedNode(jsgraph()->CEntryStubConstant(result_size));
}
References v8::internal::compiler::GraphAssembler::AddClonedNode(), and jsgraph().
Chained()
Node * v8::internal::compiler::JSGraphAssembler::Chained (const Operator * op, Node * input)
Definition at line 1070 of file graph-assembler.cc.
                                                               {
  DCHECK_EQ(op->ValueInputCount(), 1);
  return AddNode(
      graph()->NewNode(common()->Chained(op), input, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::common(), v8::internal::compiler::GraphAssembler::control(), DCHECK_EQ, v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and v8::internal::compiler::Operator::ValueInputCount().
CheckIf()
Node * v8::internal::compiler::JSGraphAssembler::CheckIf (Node * cond, DeoptimizeReason reason, const FeedbackSource & feedback = {})
Definition at line 498 of file graph-assembler.cc.
                                                                {
  return AddNode(graph()->NewNode(simplified()->CheckIf(reason, feedback), cond,
                                  effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by CheckIfTypedArrayWasDetachedOrOutOfBounds(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), and v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty().
CheckIfTypedArrayWasDetachedOrOutOfBounds()
void v8::internal::compiler::JSGraphAssembler::CheckIfTypedArrayWasDetachedOrOutOfBounds (TNode< JSTypedArray > typed_array, std::set< ElementsKind > elements_kinds_candidates, const FeedbackSource & feedback)
Definition at line 1005 of file graph-assembler.cc.
                                    {
  ArrayBufferViewAccessBuilder builder(this, JS_TYPED_ARRAY_TYPE,
                                       std::move(elements_kinds_candidates));
  TNode<Word32T> detached_check =
      builder.BuildDetachedOrOutOfBoundsCheck(typed_array);
  TNode<Boolean> is_not_detached =
      ExitMachineGraph<Boolean>(Word32Equal(detached_check, Uint32Constant(0)),
                                MachineRepresentation::kBit, Type::Boolean());
  CheckIf(is_not_detached, DeoptimizeReason::kArrayBufferWasDetached, feedback);
}
References v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildDetachedOrOutOfBoundsCheck(), CheckIf(), v8::internal::kBit, v8::internal::compiler::GraphAssembler::Uint32Constant(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayIterator().
CheckNumber()
Node * v8::internal::compiler::JSGraphAssembler::CheckNumber (Node * value, const FeedbackSource & feedback = {})
Definition at line 492 of file graph-assembler.cc.
                                                                    {
  return AddNode(graph()->NewNode(simplified()->CheckNumber(feedback), value,
                                  effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), simplified(), and v8::internal::value.
CheckNumberFitsInt32()
Node * v8::internal::compiler::JSGraphAssembler::CheckNumberFitsInt32 (Node * value, const FeedbackSource & feedback = {})
Definition at line 486 of file graph-assembler.cc.
                                                                             {
  return AddNode(graph()->NewNode(simplified()->CheckNumberFitsInt32(feedback),
                                  value, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), simplified(), and v8::internal::value.
CheckSmi()
Node * v8::internal::compiler::JSGraphAssembler::CheckSmi (Node * value, const FeedbackSource & feedback = {})
Definition at line 481 of file graph-assembler.cc.
                                                                            {
  return AddNode(graph()->NewNode(simplified()->CheckSmi(feedback), value,
                                  effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), simplified(), and v8::internal::value.
ClearPendingMessage()
Node * v8::internal::compiler::JSGraphAssembler::ClearPendingMessage ()
Definition at line 339 of file graph-assembler.cc.
                                            {
  ExternalReference const ref =
      ExternalReference::address_of_pending_message(isolate());
  return AddNode(graph()->NewNode(
      simplified()->StoreMessage(), jsgraph()->ExternalConstant(ref),
      jsgraph()->TheHoleConstant(), effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::ExternalReference::address_of_pending_message(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::ExternalConstant(), v8::internal::compiler::GraphAssembler::graph(), isolate(), jsgraph(), and simplified().
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor().
Constant()
TNode< Object > v8::internal::compiler::JSGraphAssembler::Constant (ObjectRef ref)
Definition at line 112 of file graph-assembler.cc.
                                                      {
  return TNode<Object>::UncheckedCast(
      AddClonedNode(jsgraph()->ConstantNoHole(ref, broker())));
}
References v8::internal::compiler::GraphAssembler::AddClonedNode(), broker(), jsgraph(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), and v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall().
ConvertTaggedHoleToUndefined()
TNode< Object > v8::internal::compiler::JSGraphAssembler::ConvertTaggedHoleToUndefined (TNode< Object > value)
Definition at line 536 of file graph-assembler.cc.
                         {
  return AddNode<Object>(
      graph()->NewNode(simplified()->ConvertTaggedHoleToUndefined(), value));
}
References v8::internal::compiler::GraphAssembler::graph(), simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::JSCallReducerAssembler::ConvertHoleToUndefined().
DetachContextCell()
void v8::internal::compiler::JSGraphAssembler::DetachContextCell (TNode< Object > context, TNode< Object > new_value, int index, FrameState frame_state)
Definition at line 518 of file graph-assembler.cc.
                                                                 {
  AddNode<Object>(graph()->NewNode(javascript()->DetachContextCell(index),
                                   context, new_value, NoContextConstant(),
                                   static_cast<Node*>(frame_state), effect(),
                                   control()));
}
References v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::index, and javascript().
DoubleArrayMax()
TNode< Object > v8::internal::compiler::JSGraphAssembler::DoubleArrayMax (TNode< JSArray > array)
Definition at line 554 of file graph-assembler.cc.
                                                                   {
  return AddNode<Object>(graph()->NewNode(simplified()->DoubleArrayMax(), array,
                                          effect(), control()));
}
References v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike().
DoubleArrayMin()
TNode< Object > v8::internal::compiler::JSGraphAssembler::DoubleArrayMin (TNode< JSArray > array)
Definition at line 559 of file graph-assembler.cc.
                                                                   {
  return AddNode<Object>(graph()->NewNode(simplified()->DoubleArrayMin(), array,
                                          effect(), control()));
}
References v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike().
EnterMachineGraph()
template<typename T , typename U >
TNode<T> v8::internal::compiler::JSGraphAssembler::EnterMachineGraph (TNode< U > input, UseInfo use_info) [inline]
Definition at line 1109 of file graph-assembler.h.
                                                               {
    DCHECK_EQ(use_info.type_check(), TypeCheckKind::kNone);
    return AddNode<T>(
        graph()->NewNode(common()->EnterMachineGraph(use_info), input));
  }
References DCHECK_EQ, graph(), v8::internal::compiler::kNone, and v8::internal::compiler::UseInfo::type_check().
Referenced by v8::internal::compiler::ArrayBufferViewAccessBuilder::MachineLoadField(), and v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension().
ExitMachineGraph()
template<typename T , typename U >
TNode<T> v8::internal::compiler::JSGraphAssembler::ExitMachineGraph (TNode< U > input, MachineRepresentation output_representation, Type output_type) [inline]
Definition at line 1116 of file graph-assembler.h.
                                              {
    return AddNode<T>(graph()->NewNode(
        common()->ExitMachineGraph(output_representation, output_type), input));
  }
References graph().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension().
HeapConstant()
TNode< HeapObject > v8::internal::compiler::JSGraphAssembler::HeapConstant (Handle< HeapObject > object)
Definition at line 107 of file graph-assembler.cc.
                                                                          {
  return TNode<HeapObject>::UncheckedCast(
      AddClonedNode(jsgraph()->HeapConstantNoHole(object)));
}
References v8::internal::compiler::GraphAssembler::AddClonedNode(), v8::internal::compiler::HeapConstantNoHole(), jsgraph(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::JSCallReducerAssembler::Call4(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), and v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty().
If()
IfBuilder0<Boolean> v8::internal::compiler::JSGraphAssembler::If (TNode< Boolean > cond) [inline]
Definition at line 1335 of file graph-assembler.h.
{ return {this, cond, false}; }
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext().
IfNot()
IfBuilder0<Boolean> v8::internal::compiler::JSGraphAssembler::IfNot (TNode< Boolean > cond) [inline]
Definition at line 1336 of file graph-assembler.h.
{ return {this, cond, true}; }
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor(), and v8::internal::compiler::JSCallReducerAssembler::ThrowIfNotCallable().
isolate()
Isolate* v8::internal::compiler::JSGraphAssembler::isolate () const [inline]
Definition at line 1102 of file graph-assembler.h.
{ return jsgraph()->isolate(); }
Referenced by ClearPendingMessage(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateClosureFromBuiltinSharedFunctionInfo(), PlainPrimitiveToNumberOperator(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), and v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor().
javascript()
JSOperatorBuilder* v8::internal::compiler::JSGraphAssembler::javascript () const [inline]
Definition at line 1106 of file graph-assembler.h.
{ return jsgraph()->javascript(); }
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseExecutor(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseReject(), v8::internal::compiler::JSCallReducerAssembler::CreateArrayNoThrow(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateFunctionContext(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreatePromise(), DetachContextCell(), v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSCallReducerAssembler::JSCall4(), JSCallRuntime2(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), and v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty().
JSCallRuntime1()
TNode< Object > v8::internal::compiler::JSGraphAssembler::JSCallRuntime1 (Runtime::FunctionId function_id, TNode< Object > arg0, TNode< Context > context, std::optional< FrameState > frame_state, Operator::Properties properties = Operator::kNoProperties)
Definition at line 1042 of file graph-assembler.cc.
                                                                        {
  return MayThrow([&]() {
    if (frame_state.has_value()) {
      return AddNode<Object>(graph()->NewNode(
          javascript()->CallRuntime(function_id, 1, properties), arg0, context,
          static_cast<Node*>(*frame_state), effect(), control()));
    } else {
      return AddNode<Object>(graph()->NewNode(
          javascript()->CallRuntime(function_id, 1, properties), arg0, context,
          effect(), control()));
    }
  });
}
References MayThrow().
Referenced by v8::internal::compiler::JSCallReducerAssembler::ThrowIfNotCallable().
JSCallRuntime2()
TNode< Object > v8::internal::compiler::JSGraphAssembler::JSCallRuntime2 (Runtime::FunctionId function_id, TNode< Object > arg0, TNode< Object > arg1, TNode< Context > context, FrameState frame_state)
Definition at line 1058 of file graph-assembler.cc.
                                                                       {
  return MayThrow([&]() {
    return AddNode<Object>(
        graph()->NewNode(javascript()->CallRuntime(function_id, 2), arg0, arg1,
                         context, frame_state, effect(), control()));
  });
}
References v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), javascript(), and MayThrow().
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor().
jsgraph()
JSGraph* v8::internal::compiler::JSGraphAssembler::jsgraph () const [inline]
Definition at line 1101 of file graph-assembler.h.
{ return jsgraph_; }
Referenced by v8::internal::compiler::JSCallReducerAssembler::AllocateEmptyJSArray(), CEntryStubConstant(), ClearPendingMessage(), Constant(), HeapConstant(), v8::internal::compiler::JSCallReducerAssembler::MaybeInsertMapChecks(), NumberConstant(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), and SmiConstant().
LoadElement() [1/2]
Node * v8::internal::compiler::JSGraphAssembler::LoadElement (ElementAccess const & access, Node * object, Node * index)
Definition at line 326 of file graph-assembler.cc.
                                                 {
  Node* value = AddNode(graph()->NewNode(simplified()->LoadElement(access),
                                         object, index, effect(), control()));
  return value;
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::index, simplified(), and v8::internal::value.
LoadElement() [2/2]
template<typename T >
TNode<T> v8::internal::compiler::JSGraphAssembler::LoadElement (ElementAccess const & access, TNode< HeapObject > object, TNode< Number > index) [inline]
Definition at line 1000 of file graph-assembler.h.
                                            {
    // TODO(jgruber): Investigate issues on ptr compression bots and enable.
    // DCHECK(IsMachineRepresentationOf<T>(
    // access.machine_type.representation()));
    return TNode<T>::UncheckedCast(LoadElement(access, object, index));
  }
References v8::internal::index, and v8::internal::TNode< T >::UncheckedCast().
LoadElementsKind()
TNode< Uint32T > v8::internal::compiler::JSGraphAssembler::LoadElementsKind (TNode< Map > map)
Definition at line 317 of file graph-assembler.cc.
                                                                {
  TNode<Uint8T> bit_field2 = EnterMachineGraph<Uint8T>(
      LoadField<Uint8T>(AccessBuilder::ForMapBitField2(), map),
      UseInfo::TruncatingWord32());
  return TNode<Uint32T>::UncheckedCast(
      Word32Shr(TNode<Word32T>::UncheckedCast(bit_field2),
                Uint32Constant(Map::Bits2::ElementsKindBits::kShift)));
}
References v8::internal::bit_field2, v8::internal::compiler::AccessBuilder::ForMapBitField2(), v8::internal::compiler::UseInfo::TruncatingWord32(), v8::internal::compiler::GraphAssembler::Uint32Constant(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor().
LoadField() [1/2]
Node * v8::internal::compiler::JSGraphAssembler::LoadField (FieldAccess const & access, Node * object)
Definition at line 311 of file graph-assembler.cc.
                                                                         {
  Node* value = AddNode(graph()->NewNode(simplified()->LoadField(access),
                                         object, effect(), control()));
  return value;
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), simplified(), and v8::internal::value.
Referenced by LoadMap(), v8::internal::compiler::ArrayBufferViewAccessBuilder::MachineLoadField(), v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::JSTypedLowering::ReduceJSHasContextExtension(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), and v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext().
LoadField() [2/2]
template<typename T >
TNode<T> v8::internal::compiler::JSGraphAssembler::LoadField (FieldAccess const & access, TNode< HeapObject > object) [inline]
Definition at line 991 of file graph-assembler.h.
                                                                          {
    // TODO(jgruber): Investigate issues on ptr compression bots and enable.
    // DCHECK(IsMachineRepresentationOf<T>(
    // access.machine_type.representation()));
    return TNode<T>::UncheckedCast(LoadField(access, object));
  }
References v8::internal::TNode< T >::UncheckedCast().
LoadMap()
TNode< Map > v8::internal::compiler::JSGraphAssembler::LoadMap (TNode< HeapObject > object)
Definition at line 307 of file graph-assembler.cc.
                                                             {
  return TNode<Map>::UncheckedCast(LoadField(AccessBuilder::ForMap(), object));
}
References v8::internal::compiler::AccessBuilder::ForMap(), LoadField(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), and v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext().
LookupByteShiftForElementsKind()
TNode< Uint32T > v8::internal::compiler::JSGraphAssembler::LookupByteShiftForElementsKind (TNode< Uint32T > elements_kind)
Definition at line 1020 of file graph-assembler.cc.
                                  {
  TNode<UintPtrT> index = ChangeUint32ToUintPtr(Int32Sub(
      elements_kind, Uint32Constant(FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND)));
  TNode<RawPtrT> shift_table = TNode<RawPtrT>::UncheckedCast(ExternalConstant(
      ExternalReference::
          typed_array_and_rab_gsab_typed_array_elements_kind_shifts()));
  return TNode<Uint8T>::UncheckedCast(
      Load(MachineType::Uint8(), shift_table, index));
}
References v8::internal::compiler::GraphAssembler::ChangeUint32ToUintPtr(), v8::internal::compiler::GraphAssembler::ExternalConstant(), v8::internal::FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND, v8::internal::index, v8::internal::compiler::GraphAssembler::Load(), v8::internal::compiler::GraphAssembler::Uint32Constant(), v8::internal::MachineType::Uint8(), and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor().
LookupByteSizeForElementsKind()
TNode< Uint32T > v8::internal::compiler::JSGraphAssembler::LookupByteSizeForElementsKind (TNode< Uint32T > elements_kind)
Definition at line 1031 of file graph-assembler.cc.
                                  {
  TNode<UintPtrT> index = ChangeUint32ToUintPtr(Int32Sub(
      elements_kind, Uint32Constant(FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND)));
  TNode<RawPtrT> size_table = TNode<RawPtrT>::UncheckedCast(ExternalConstant(
      ExternalReference::
          typed_array_and_rab_gsab_typed_array_elements_kind_sizes()));
  return TNode<Uint8T>::UncheckedCast(
      Load(MachineType::Uint8(), size_table, index));
}
References v8::internal::compiler::GraphAssembler::ChangeUint32ToUintPtr(), v8::internal::compiler::GraphAssembler::ExternalConstant(), v8::internal::FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND, v8::internal::index, v8::internal::compiler::GraphAssembler::Load(), v8::internal::compiler::GraphAssembler::Uint32Constant(), v8::internal::MachineType::Uint8(), and v8::internal::TNode< T >::UncheckedCast().
MachineIf()
IfBuilder0<Word32T> v8::internal::compiler::JSGraphAssembler::MachineIf (TNode< Word32T > cond) [inline]
Definition at line 1338 of file graph-assembler.h.
                                                     {
    return {this, cond, false};
  }
MachineSelect()
template<typename T >
TNode<T> v8::internal::compiler::JSGraphAssembler::MachineSelect (TNode< Word32T > cond, TNode< T > true_value, TNode< T > false_value, BranchHint hint = BranchHint::kNone) [inline]
Definition at line 1432 of file graph-assembler.h.
                                                            {
    return TNode<T>::UncheckedCast(AddNode(
        graph()->NewNode(common()->Select(T::kMachineRepresentation, hint,
                                          BranchSemantics::kMachine),
                         cond, true_value, false_value)));
  }
References graph(), v8::internal::compiler::kMachine, and v8::internal::TNode< T >::UncheckedCast().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayBufferViewAccessor().
MachineSelectIf()
template<typename T >
IfBuilder1<T, Word32T> v8::internal::compiler::JSGraphAssembler::MachineSelectIf (TNode< Word32T > cond) [inline]
Definition at line 1428 of file graph-assembler.h.
                                                              {
    return {this, cond, false};
  }
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), and v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength().
MaybeGrowFastElements()
TNode< FixedArrayBase > v8::internal::compiler::JSGraphAssembler::MaybeGrowFastElements (ElementsKind kind, const FeedbackSource & feedback, TNode< JSArray > array, TNode< FixedArrayBase > elements, TNode< Number > new_length, TNode< Number > old_length)
Definition at line 542 of file graph-assembler.cc.
                              {
  GrowFastElementsMode mode = IsDoubleElementsKind(kind)
                                  ? GrowFastElementsMode::kDoubleElements
                                  : GrowFastElementsMode::kSmiOrObjectElements;
  return AddNode<FixedArrayBase>(graph()->NewNode(
      simplified()->MaybeGrowFastElements(mode, feedback), array, elements,
      index_needed, old_length, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::IsDoubleElementsKind(), v8::internal::compiler::kDoubleElements, v8::internal::compiler::kSmiOrObjectElements, mode(), and simplified().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush().
MayThrow()
TNode<Object> v8::internal::compiler::JSGraphAssembler::MayThrow (const NodeGenerator0 & body) [inline]
Definition at line 1229 of file graph-assembler.h.
                                                     {
    TNode<Object> result = body();
    if (catch_scope()->has_handler()) {
      // The IfException node is later merged into the outer graph.
      // Note: AddNode is intentionally not called since effect and control
      // should not be updated.
      Node* if_exception =
          graph()->NewNode(common()->IfException(), effect(), control());
      catch_scope()->RegisterIfExceptionNode(if_exception);
      // Control resumes here.
      AddNode(graph()->NewNode(common()->IfSuccess(), control()));
    }
    return result;
  }
References graph(), and v8::base::internal::result.
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseExecutor(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CallPromiseReject(), v8::internal::compiler::JSCallReducerAssembler::CopyNode(), v8::internal::compiler::JSCallReducerAssembler::JSCall3(), v8::internal::compiler::JSCallReducerAssembler::JSCall4(), JSCallRuntime1(), JSCallRuntime2(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt().
NumberAdd()
TNode< Number > v8::internal::compiler::JSGraphAssembler::NumberAdd (TNode< Number > lhs, TNode< Number > rhs)
Definition at line 415 of file graph-assembler.cc.
                                                             {
  return AddNode<Number>(graph()->NewNode(simplified()->NumberAdd(), lhs, rhs));
}
References v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::JSCallReducerAssembler::For1ZeroUntil(), v8::internal::compiler::JSCallReducerAssembler::ForZeroUntil(), v8::internal::compiler::JSCallReducerAssembler::NumberInc(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeForEach(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith().
NumberBitwiseAnd()
TNode< Number > v8::internal::compiler::JSGraphAssembler::NumberBitwiseAnd (TNode< Number > lhs, TNode< Number > rhs)
Definition at line 444 of file graph-assembler.cc.
                                                                    {
  return AddNode<Number>(
      graph()->NewNode(simplified()->NumberBitwiseAnd(), lhs, rhs));
}
References v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::JSCallReducerAssembler::LoadMapElementsKind().
NumberBitwiseOr()
TNode< Number > v8::internal::compiler::JSGraphAssembler::NumberBitwiseOr (TNode< Number > lhs, TNode< Number > rhs)
Definition at line 450 of file graph-assembler.cc.
                                                                   {
  return AddNode<Number>(
      graph()->NewNode(simplified()->NumberBitwiseOr(), lhs, rhs));
}
References v8::internal::compiler::GraphAssembler::graph(), and simplified().
NumberConstant()
TNode< Number > v8::internal::compiler::JSGraphAssembler::NumberConstant (double value)
Definition at line 117 of file graph-assembler.cc.
                                                           {
  return TNode<Number>::UncheckedCast(
      AddClonedNode(jsgraph()->ConstantNoHole(value)));
}
References v8::internal::compiler::GraphAssembler::AddClonedNode(), jsgraph(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
Referenced by v8::internal::compiler::JSCallReducerAssembler::LoadMapElementsKind(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), and v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength().
NumberDivide()
TNode<Number> v8::internal::compiler::JSGraphAssembler::NumberDivide (TNode< Number > lhs, TNode< Number > rhs)
NumberEqual()
TNode< Boolean > v8::internal::compiler::JSGraphAssembler::NumberEqual (TNode< Number > lhs, TNode< Number > rhs)
Definition at line 399 of file graph-assembler.cc.
                                                                {
  return AddNode<Boolean>(
      graph()->NewNode(simplified()->NumberEqual(), lhs, rhs));
}
References v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith().
NumberFloor()
TNode<Number> v8::internal::compiler::JSGraphAssembler::NumberFloor (TNode< Number > value)
NumberIsFloat64Hole()
TNode< Boolean > v8::internal::compiler::JSGraphAssembler::NumberIsFloat64Hole (TNode< Number > value)
Definition at line 527 of file graph-assembler.cc.
                                                                        {
  return AddNode<Boolean>(
      graph()->NewNode(simplified()->NumberIsFloat64Hole(), value));
}
References v8::internal::compiler::GraphAssembler::graph(), simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::HoleCheck().
NumberLessThan()
TNode< Boolean > v8::internal::compiler::JSGraphAssembler::NumberLessThan (TNode< Number > lhs, TNode< Number > rhs)
Definition at line 426 of file graph-assembler.cc.
                                                                   {
  return AddNode<Boolean>(
      graph()->NewNode(simplified()->NumberLessThan(), lhs, rhs));
}
References v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::JSCallReducerAssembler::For1ZeroUntil(), v8::internal::compiler::JSCallReducerAssembler::ForZeroUntil(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharCodeAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith().
NumberLessThanOrEqual()
TNode< Boolean > v8::internal::compiler::JSGraphAssembler::NumberLessThanOrEqual (TNode< Number > lhs, TNode< Number > rhs)
Definition at line 432 of file graph-assembler.cc.
                                                                          {
  return AddNode<Boolean>(
      graph()->NewNode(simplified()->NumberLessThanOrEqual(), lhs, rhs));
}
References v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce().
NumberMax()
TNode< Number > v8::internal::compiler::JSGraphAssembler::NumberMax (TNode< Number > lhs, TNode< Number > rhs)
Definition at line 410 of file graph-assembler.cc.
                                                             {
  return AddNode<Number>(graph()->NewNode(simplified()->NumberMax(), lhs, rhs));
}
References v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeIndexOfIncludes(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSubstring().
NumberMin()
TNode< Number > v8::internal::compiler::JSGraphAssembler::NumberMin (TNode< Number > lhs, TNode< Number > rhs)
Definition at line 405 of file graph-assembler.cc.
                                                             {
  return AddNode<Number>(graph()->NewNode(simplified()->NumberMin(), lhs, rhs));
}
References v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSubstring().
NumberShiftRightLogical()
TNode< Number > v8::internal::compiler::JSGraphAssembler::NumberShiftRightLogical (TNode< Number > lhs, TNode< Number > rhs)
Definition at line 438 of file graph-assembler.cc.
                                                                           {
  return AddNode<Number>(
      graph()->NewNode(simplified()->NumberShiftRightLogical(), lhs, rhs));
}
References v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::JSCallReducerAssembler::LoadMapElementsKind().
NumberSubtract()
TNode< Number > v8::internal::compiler::JSGraphAssembler::NumberSubtract (TNode< Number > lhs, TNode< Number > rhs)
Definition at line 420 of file graph-assembler.cc.
                                                                  {
  return AddNode<Number>(
      graph()->NewNode(simplified()->NumberSubtract(), lhs, rhs));
}
References v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeReduce(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith().
ObjectIsCallable()
TNode< Boolean > v8::internal::compiler::JSGraphAssembler::ObjectIsCallable (TNode< Object > value)
Definition at line 463 of file graph-assembler.cc.
                                                                     {
  return AddNode<Boolean>(
      graph()->NewNode(simplified()->ObjectIsCallable(), value));
}
References v8::internal::compiler::GraphAssembler::graph(), simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor(), and v8::internal::compiler::JSCallReducerAssembler::ThrowIfNotCallable().
ObjectIsSmi()
TNode< Boolean > v8::internal::compiler::JSGraphAssembler::ObjectIsSmi (TNode< Object > value)
Definition at line 468 of file graph-assembler.cc.
                                                                {
  return AddNode<Boolean>(graph()->NewNode(simplified()->ObjectIsSmi(), value));
}
References v8::internal::compiler::GraphAssembler::graph(), simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallMathMinMaxWithArrayLike(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext(), and v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext().
ObjectIsUndetectable()
TNode< Boolean > v8::internal::compiler::JSGraphAssembler::ObjectIsUndetectable (TNode< Object > value)
Definition at line 472 of file graph-assembler.cc.
                                                                         {
  return AddNode<Boolean>(
      graph()->NewNode(simplified()->ObjectIsUndetectable(), value));
}
References v8::internal::compiler::GraphAssembler::graph(), simplified(), and v8::internal::value.
outermost_handler()
Node* v8::internal::compiler::JSGraphAssembler::outermost_handler () const [inline]
Definition at line 1222 of file graph-assembler.h.
{ return outermost_handler_; }
Referenced by v8::internal::compiler::JSCallReducer::ReleaseEffectAndControlFromAssembler(), v8::internal::compiler::JSNativeContextSpecialization::ReleaseEffectAndControlFromAssembler(), and v8::internal::compiler::JSCallReducer::ReplaceWithSubgraph().
PlainPrimitiveToNumber()
TNode< Number > v8::internal::compiler::JSGraphAssembler::PlainPrimitiveToNumber (TNode< Object > value)
Definition at line 1203 of file graph-assembler.cc.
                                                                          {
  return AddNode<Number>(graph()->NewNode(
      PlainPrimitiveToNumberOperator(), PlainPrimitiveToNumberBuiltinConstant(),
      value, effect()));
}
References v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), PlainPrimitiveToNumberOperator(), and v8::internal::value.
PlainPrimitiveToNumberOperator()
Operator const * v8::internal::compiler::JSGraphAssembler::PlainPrimitiveToNumberOperator () [protected]
Definition at line 1351 of file graph-assembler.cc.
                                                                 {
  if (!to_number_operator_.is_set()) {
    Callable callable =
        Builtins::CallableFor(isolate(), Builtin::kPlainPrimitiveToNumber);
    CallDescriptor::Flags flags = CallDescriptor::kNoFlags;
    auto call_descriptor = Linkage::GetStubCallDescriptor(
        graph()->zone(), callable.descriptor(),
        callable.descriptor().GetStackParameterCount(), flags,
        Operator::kEliminatable);
    to_number_operator_.set(common()->Call(call_descriptor));
  }
  return to_number_operator_.get();
}
References v8::internal::compiler::GraphAssembler::Call(), v8::internal::Builtins::CallableFor(), v8::internal::compiler::GraphAssembler::common(), v8::internal::Callable::descriptor(), v8::internal::flags, v8::internal::CallInterfaceDescriptor::GetStackParameterCount(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::GraphAssembler::graph(), isolate(), v8::internal::compiler::Operator::kEliminatable, v8::internal::compiler::CallDescriptor::kNoFlags, and to_number_operator_.
Referenced by PlainPrimitiveToNumber().
ReferenceEqual()
TNode< Boolean > v8::internal::compiler::JSGraphAssembler::ReferenceEqual (TNode< Object > lhs, TNode< Object > rhs)
Definition at line 393 of file graph-assembler.cc.
                                                                   {
  return AddNode<Boolean>(
      graph()->NewNode(simplified()->ReferenceEqual(), lhs, rhs));
}
References v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeAt(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducerAssembler::ReduceJSCallWithArrayLikeOrSpreadOfEmpty(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice().
SelectIf()
template<typename T >
IfBuilder1<T, Boolean> v8::internal::compiler::JSGraphAssembler::SelectIf (TNode< Boolean > cond) [inline]
Definition at line 1420 of file graph-assembler.h.
                                                       {
    return {this, cond, false};
  }
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSLoadContext().
SelectIfNot()
template<typename T >
IfBuilder1<T, Boolean> v8::internal::compiler::JSGraphAssembler::SelectIfNot (TNode< Boolean > cond) [inline]
Definition at line 1424 of file graph-assembler.h.
                                                          {
    return {this, cond, true};
  }
simplified()
SimplifiedOperatorBuilder* v8::internal::compiler::JSGraphAssembler::simplified () [inline], [override], [virtual]
Reimplemented from v8::internal::compiler::GraphAssembler.
Definition at line 1103 of file graph-assembler.h.
                                                   {
    return jsgraph()->simplified();
  }
Referenced by Allocate(), BooleanNot(), v8::internal::compiler::JSCallReducerAssembler::CheckBounds(), CheckIf(), CheckNumber(), v8::internal::compiler::JSCallReducerAssembler::CheckNumber(), CheckNumberFitsInt32(), CheckSmi(), v8::internal::compiler::JSCallReducerAssembler::CheckSmi(), v8::internal::compiler::JSCallReducerAssembler::CheckString(), ClearPendingMessage(), v8::internal::compiler::JSCallReducerAssembler::ConvertHoleToUndefined(), ConvertTaggedHoleToUndefined(), DoubleArrayMax(), DoubleArrayMin(), v8::internal::compiler::FastApiCallReducerAssembler::FastApiCall(), LoadElement(), LoadField(), MaybeGrowFastElements(), NumberAdd(), NumberBitwiseAnd(), NumberBitwiseOr(), NumberEqual(), NumberIsFloat64Hole(), NumberLessThan(), NumberLessThanOrEqual(), NumberMax(), NumberMin(), NumberShiftRightLogical(), NumberSubtract(), ObjectIsCallable(), ObjectIsSmi(), ObjectIsUndetectable(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypePush(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), ReferenceEqual(), v8::internal::compiler::JSCallReducerAssembler::SpeculativeToNumber(), StoreElement(), StoreField(), StringCharCodeAt(), StringFromSingleCharCode(), StringLength(), StringSubstring(), ToBoolean(), and TransitionAndStoreElement().
SmiConstant()
TNode< Smi > v8::internal::compiler::JSGraphAssembler::SmiConstant (int32_t value)
Definition at line 98 of file graph-assembler.cc.
                                                      {
  return TNode<Smi>::UncheckedCast(
      AddClonedNode(jsgraph()->SmiConstant(value)));
}
References v8::internal::compiler::GraphAssembler::AddClonedNode(), jsgraph(), v8::internal::TNode< T >::UncheckedCast(), and v8::internal::value.
Referenced by v8::internal::compiler::PromiseBuiltinReducerAssembler::ReducePromiseConstructor().
StoreElement()
Node * v8::internal::compiler::JSGraphAssembler::StoreElement (ElementAccess const & access, Node * object, Node * index, Node * value)
Definition at line 372 of file graph-assembler.cc.
                                                               {
  return AddNode(graph()->NewNode(simplified()->StoreElement(access), object,
                                  index, value, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::index, simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::StoreFixedArrayBaseElement().
StoreField()
Node * v8::internal::compiler::JSGraphAssembler::StoreField (FieldAccess const & access, Node * object, Node * value)
Definition at line 333 of file graph-assembler.cc.
                                                {
  return AddNode(graph()->NewNode(simplified()->StoreField(access), object,
                                  value, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSStoreContext(), v8::internal::compiler::PromiseBuiltinReducerAssembler::StoreContextNoCellSlot(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::StoreJSArrayLength().
StringCharCodeAt()
Node * v8::internal::compiler::JSGraphAssembler::StringCharCodeAt (TNode< String > string, TNode< Number > position)
Definition at line 564 of file graph-assembler.cc.
                                                                 {
  return AddNode(graph()->NewNode(simplified()->StringCharCodeAt(), string,
                                  position, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharCodeAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith().
StringFromSingleCharCode()
TNode< String > v8::internal::compiler::JSGraphAssembler::StringFromSingleCharCode (TNode< Number > code)
Definition at line 570 of file graph-assembler.cc.
                                                                           {
  return AddNode<String>(
      graph()->NewNode(simplified()->StringFromSingleCharCode(), code));
}
References code, v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice().
StringLength()
TNode< Number > v8::internal::compiler::JSGraphAssembler::StringLength (TNode< String > string)
Definition at line 388 of file graph-assembler.cc.
                                                                 {
  return AddNode<Number>(
      graph()->NewNode(simplified()->StringLength(), string));
}
References v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharCodeAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSubstring().
StringSubstring()
TNode< String > v8::internal::compiler::JSGraphAssembler::StringSubstring (TNode< String > string, TNode< Number > from, TNode< Number > to)
Definition at line 456 of file graph-assembler.cc.
                                                                  {
  return AddNode<String>(graph()->NewNode(
      simplified()->StringSubstring(), string, from, to, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), and simplified().
Referenced by v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSlice(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeSubstring().
ToBoolean()
TNode< Boolean > v8::internal::compiler::JSGraphAssembler::ToBoolean (TNode< Object > value)
Definition at line 532 of file graph-assembler.cc.
                                                              {
  return AddNode<Boolean>(graph()->NewNode(simplified()->ToBoolean(), value));
}
References v8::internal::compiler::GraphAssembler::graph(), simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeEverySome(), v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFilter(), and v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeFind().
TransitionAndStoreElement()
void v8::internal::compiler::JSGraphAssembler::TransitionAndStoreElement (MapRef double_map, MapRef fast_map, TNode< HeapObject > object, TNode< Number > index, TNode< Object > value)
Definition at line 378 of file graph-assembler.cc.
                                                                      {
  AddNode(graph()->NewNode(
      simplified()->TransitionAndStoreElement(double_map, fast_map), object,
      index, value, effect(), control()));
}
References v8::internal::compiler::GraphAssembler::AddNode(), v8::internal::compiler::GraphAssembler::control(), v8::internal::compiler::GraphAssembler::effect(), v8::internal::compiler::GraphAssembler::graph(), v8::internal::index, simplified(), and v8::internal::value.
Referenced by v8::internal::compiler::IteratingArrayBuiltinReducerAssembler::ReduceArrayPrototypeMap().
TypedArrayLength()
TNode< Number > v8::internal::compiler::JSGraphAssembler::TypedArrayLength (TNode< JSTypedArray > typed_array, std::set< ElementsKind > elements_kinds_candidates, TNode< Context > context)
Definition at line 995 of file graph-assembler.cc.
                                                                            {
  ArrayBufferViewAccessBuilder builder(this, JS_TYPED_ARRAY_TYPE,
                                       std::move(elements_kinds_candidates));
  return ExitMachineGraph<Number>(builder.BuildLength(typed_array, context),
                                  MachineType::PointerRepresentation(),
                                  TypeCache::Get()->kJSTypedArrayLengthType);
}
References v8::internal::compiler::ArrayBufferViewAccessBuilder::BuildLength(), v8::internal::compiler::TypeCache::Get(), v8::internal::compiler::TypeCache::kJSTypedArrayLengthType, and v8::internal::MachineType::PointerRepresentation().
Referenced by v8::internal::compiler::JSCallReducer::ReduceTypedArrayPrototypeLength().
Friends And Related Function Documentation
CatchScope
friend class CatchScope [friend]
Definition at line 1453 of file graph-assembler.h.
Member Data Documentation
broker_
JSHeapBroker* v8::internal::compiler::JSGraphAssembler::broker_ [private]
Definition at line 1445 of file graph-assembler.h.
catch_scope_
CatchScope* v8::internal::compiler::JSGraphAssembler::catch_scope_ [protected]
Definition at line 1452 of file graph-assembler.h.
jsgraph_
JSGraph* v8::internal::compiler::JSGraphAssembler::jsgraph_ [private]
Definition at line 1446 of file graph-assembler.h.
outermost_catch_scope_
CatchScope v8::internal::compiler::JSGraphAssembler::outermost_catch_scope_ [protected]
Definition at line 1450 of file graph-assembler.h.
outermost_handler_
Node* v8::internal::compiler::JSGraphAssembler::outermost_handler_ [protected]
Definition at line 1451 of file graph-assembler.h.
to_number_operator_
SetOncePointer<Operator const> v8::internal::compiler::JSGraphAssembler::to_number_operator_ [private]
Definition at line 1447 of file graph-assembler.h.
Referenced by PlainPrimitiveToNumberOperator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/graph-assembler.h
/mnt/V8SourceCode/src/compiler/graph-assembler.cc