v8::internal::compiler::Type Class Reference
#include <turbofan-types.h>
Public Types
using bitset = BitsetType::bitset
Public Member Functions
Type ()
bool IsNone () const
bool IsInvalid () const
bool Is (Type that) const
bool Maybe (Type that) const
bool Equals (Type that) const
bool IsBitset () const
bool IsRange () const
bool IsHeapConstant () const
bool IsOtherNumberConstant () const
bool IsTuple () const
bool IsSingleton () const
bool CanBeAsserted () const
Handle< TurbofanType > AllocateOnHeap (Factory *factory)
const HeapConstantType * AsHeapConstant () const
const OtherNumberConstantType * AsOtherNumberConstant () const
const RangeType * AsRange () const
const TupleType * AsTuple () const
double Min () const
double Max () const
Type GetRange () const
int NumConstants () const
bool operator== (Type other) const
bool operator!= (Type other) const
void PrintTo (std::ostream &os) const
bool IsUnionForTesting ()
bitset AsBitsetForTesting ()
const UnionType * AsUnionForTesting ()
Type BitsetGlbForTesting ()
Type BitsetLubForTesting ()
Static Public Member Functions
static Type SignedSmall ()
static Type UnsignedSmall ()
static Type Constant (JSHeapBroker *broker, Handle< i::Object > value, Zone *zone)
static Type Constant (JSHeapBroker *broker, ObjectRef value, Zone *zone)
static Type Constant (double value, Zone *zone)
static Type Range (double min, double max, Zone *zone)
static Type Tuple (Type first, Type second, Type third, Zone *zone)
static Type Tuple (Type first, Type second, Zone *zone)
static Type Union (Type type1, Type type2, Zone *zone)
static Type Intersect (Type type1, Type type2, Zone *zone)
static Type For (MapRef type, JSHeapBroker *broker)
static Type Invalid ()
Private Member Functions
Type (bitset bits)
Type (TypeBase *type_base)
bool IsKind (TypeBase::Kind kind) const
const TypeBase * ToTypeBase () const
bool IsAny () const
bool IsUnion () const
bitset AsBitset () const
const UnionType * AsUnion () const
bitset BitsetGlb () const
bitset BitsetLub () const
bool SlowIs (Type that) const
bool SimplyEquals (Type that) const
Static Private Member Functions
static Type FromTypeBase (TypeBase *type)
static Type NewBitset (bitset bits)
static Type Range (RangeType::Limits lims, Zone *zone)
static Type OtherNumberConstant (double value, Zone *zone)
static Type HeapConstant (HeapObjectRef value, JSHeapBroker *broker, Zone *zone)
static bool Overlap (const RangeType *lhs, const RangeType *rhs)
static bool Contains (const RangeType *lhs, const RangeType *rhs)
static int UpdateRange (Type type, UnionType *result, int size, Zone *zone)
static RangeType::Limits IntersectRangeAndBitset (Type range, Type bits, Zone *zone)
static RangeType::Limits ToLimits (bitset bits, Zone *zone)
static int AddToUnion (Type type, UnionType *result, int size, Zone *zone)
static int IntersectAux (Type type, Type other, UnionType *result, int size, RangeType::Limits *limits, Zone *zone)
static Type NormalizeUnion (UnionType *unioned, int size, Zone *zone)
static Type NormalizeRangeAndBitset (Type range, bitset *bits, Zone *zone)
Private Attributes
friend BitsetType
friend UnionType
uint64_t payload_
Friends
template<class >
class Iterator
size_t hash_value (Type type)
Detailed Description
Definition at line 424 of file turbofan-types.h.
Member Typedef Documentation
bitset
using v8::internal::compiler::Type::bitset = BitsetType::bitset
Definition at line 426 of file turbofan-types.h.
Constructor & Destructor Documentation
Type() [1/3]
v8::internal::compiler::Type::Type () [inline]
Definition at line 434 of file turbofan-types.h.
: payload_(uint64_t{0}) {}
Type() [2/3]
v8::internal::compiler::Type::Type (bitset bits) [inline], [explicit], [private]
Definition at line 541 of file turbofan-types.h.
: payload_(bits | uint64_t{1}) {}
Type() [3/3]
v8::internal::compiler::Type::Type (TypeBase * type_base) [inline], [private]
Definition at line 543 of file turbofan-types.h.
      : payload_(reinterpret_cast<uint64_t>(type_base)) {}
Member Function Documentation
AddToUnion()
static int v8::internal::compiler::Type::AddToUnion (Type type, UnionType * result, int size, Zone * zone) [static], [private]
AllocateOnHeap()
Handle<TurbofanType> v8::internal::compiler::Type::AllocateOnHeap (Factory * factory)
AsBitset()
bitset v8::internal::compiler::Type::AsBitset () const [inline], [private]
Definition at line 561 of file turbofan-types.h.
                          {
    DCHECK(IsBitset());
    return static_cast<bitset>(payload_) ^ uint64_t { 1 };
  }
References v8::internal::DCHECK().
AsBitsetForTesting()
bitset v8::internal::compiler::Type::AsBitsetForTesting () [inline]
Definition at line 528 of file turbofan-types.h.
{ return AsBitset(); }
AsHeapConstant()
const HeapConstantType* v8::internal::compiler::Type::AsHeapConstant () const
Referenced by v8::internal::compiler::JSTypedLowering::BuildGetModuleCell(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc}::CheckMapsHelper(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::GetStableMapFromObjectType(), v8::internal::compiler::Typer::Visitor::JSCallTyper(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumberInput(), v8::internal::compiler::TypedOptimization::ReduceJSToNumberInput(), v8::internal::compiler::TypedOptimization::ReduceReferenceEqual(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift(), and v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCode().
AsOtherNumberConstant()
const OtherNumberConstantType* v8::internal::compiler::Type::AsOtherNumberConstant () const
AsRange()
const RangeType* v8::internal::compiler::Type::AsRange () const
Referenced by v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor().
AsTuple()
const TupleType* v8::internal::compiler::Type::AsTuple () const
AsUnion()
const UnionType* v8::internal::compiler::Type::AsUnion () const [private]
AsUnionForTesting()
const UnionType* v8::internal::compiler::Type::AsUnionForTesting () [inline]
Definition at line 529 of file turbofan-types.h.
{ return AsUnion(); }
BitsetGlb()
bitset v8::internal::compiler::Type::BitsetGlb () const [private]
BitsetGlbForTesting()
Type v8::internal::compiler::Type::BitsetGlbForTesting () [inline]
Definition at line 530 of file turbofan-types.h.
{ return NewBitset(BitsetGlb()); }
BitsetLub()
bitset v8::internal::compiler::Type::BitsetLub () const [private]
BitsetLubForTesting()
Type v8::internal::compiler::Type::BitsetLubForTesting () [inline]
Definition at line 531 of file turbofan-types.h.
{ return NewBitset(BitsetLub()); }
CanBeAsserted()
bool v8::internal::compiler::Type::CanBeAsserted () const [inline]
Definition at line 489 of file turbofan-types.h.
{ return Is(Type::NonInternal()); }
References v8::internal::Is().
Referenced by v8::internal::compiler::RepresentationSelector::VisitNode().
Constant() [1/3]
static Type v8::internal::compiler::Type::Constant (double value, Zone * zone) [static]
Constant() [2/3]
static Type v8::internal::compiler::Type::Constant (JSHeapBroker * broker, Handle< i::Object > value, Zone * zone) [static]
Referenced by v8::internal::compiler::EscapeAnalysisReducer::Finalize(), v8::internal::compiler::RepresentationChanger::GetBitRepresentationFor(), v8::internal::compiler::OperationTyper::OperationTyper(), v8::internal::compiler::RepresentationSelector::RepresentationSelector(), v8::internal::compiler::Typer::Visitor::ToLength(), v8::internal::compiler::Typer::Visitor::TypeConstant(), and v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode().
Constant() [3/3]
static Type v8::internal::compiler::Type::Constant (JSHeapBroker * broker, ObjectRef value, Zone * zone) [static]
Contains()
static bool v8::internal::compiler::Type::Contains (const RangeType * lhs, const RangeType * rhs) [static], [private]
Equals()
bool v8::internal::compiler::Type::Equals (Type that) const [inline]
Definition at line 468 of file turbofan-types.h.
{ return this->Is(that) && that.Is(*this); }
References v8::internal::Is(), and Is().
Referenced by v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), and v8::internal::compiler::operator==().
For()
static Type v8::internal::compiler::Type::For (MapRef type, JSHeapBroker * broker) [inline], [static]
Definition at line 455 of file turbofan-types.h.
                                                     {
    return NewBitset(
        BitsetType::ExpandInternals(BitsetType::Lub(type, broker)));
  }
References broker(), v8::internal::compiler::BitsetType::ExpandInternals(), v8::internal::compiler::BitsetType::Lub(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp(), v8::internal::compiler::PropertyAccessBuilder::BuildLoadDataField(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), and v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral().
FromTypeBase()
static Type v8::internal::compiler::Type::FromTypeBase (TypeBase * type) [inline], [static], [private]
Definition at line 556 of file turbofan-types.h.
{ return Type(type); }
References v8::internal::tracing::type.
GetRange()
Type v8::internal::compiler::Type::GetRange () const
Referenced by v8::internal::compiler::Typer::Visitor::Weaken(), and v8::internal::compiler::RepresentationSelector::Weaken().
HeapConstant()
static Type v8::internal::compiler::Type::HeapConstant (HeapObjectRef value, JSHeapBroker * broker, Zone * zone) [static], [private]
Intersect()
static Type v8::internal::compiler::Type::Intersect (Type type1, Type type2, Zone * zone) [static]
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CanOverflowSigned32(), v8::internal::compiler::JSBinopReduction::ChangeToPureOperator(), v8::internal::compiler::JSBinopReduction::ChangeToSpeculativeOperator(), v8::internal::compiler::OperationTyper::CheckBounds(), v8::internal::compiler::OperationTyper::CheckFloat64Hole(), v8::internal::compiler::OperationTyper::CheckNumber(), v8::internal::compiler::OperationTyper::CheckNumberFitsInt32(), v8::internal::compiler::OperationTyper::CheckNumberOrUndefined(), v8::internal::compiler::OperationTyper::ConvertTaggedHoleToUndefined(), v8::internal::compiler::Typer::Decorator::Decorate(), v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint(), v8::internal::compiler::TypeNarrowingReducer::Reduce(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSToBigIntConvertNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumeric(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::TypedOptimization::ReducePhi(), v8::internal::compiler::TypedOptimization::ReduceSelect(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::RepresentationSelector::SetOutput(), v8::internal::compiler::OperationTyper::ToBigIntConvertNumber(), v8::internal::compiler::Typer::Visitor::ToInteger(), v8::internal::compiler::OperationTyper::ToNumber(), v8::internal::compiler::OperationTyper::ToNumberConvertBigInt(), v8::internal::compiler::OperationTyper::ToNumeric(), v8::internal::compiler::OperationTyper::TypeTypeGuard(), v8::internal::compiler::RepresentationSelector::UpdateFeedbackType(), v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::Typer::Visitor::Weaken(), and v8::internal::compiler::RepresentationSelector::Weaken().
IntersectAux()
static int v8::internal::compiler::Type::IntersectAux (Type type, Type other, UnionType * result, int size, RangeType::Limits * limits, Zone * zone) [static], [private]
IntersectRangeAndBitset()
static RangeType::Limits v8::internal::compiler::Type::IntersectRangeAndBitset (Type range, Type bits, Zone * zone) [static], [private]
Invalid()
static Type v8::internal::compiler::Type::Invalid () [inline], [static]
Definition at line 513 of file turbofan-types.h.
{ return Type(); }
Referenced by v8::internal::compiler::NodeProperties::RemoveType().
Is()
bool v8::internal::compiler::Type::Is (Type that) const [inline]
Definition at line 464 of file turbofan-types.h.
                           {
    return payload_ == that.payload_ || this->SlowIs(that);
  }
References payload_.
Referenced by v8::internal::compiler::Typer::Visitor::BinaryNumberOpTyper(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::BothAre(), v8::internal::compiler::RepresentationSelector::BothInputsAre(), v8::internal::compiler::RepresentationSelector::CanSpeculateAdditiveSafeInteger(), v8::internal::compiler::LoopVariableOptimizer::ChangeToPhisAndInsertGuards(), v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::CheckSubsumes(), v8::internal::compiler::JSBinopReduction::ConvertToUI32(), Equals(), v8::internal::compiler::RepresentationChanger::GetBitRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat16RawBitsRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedPointerRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedSignedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint(), v8::internal::compiler::RepresentationSelector::InputIs(), v8::internal::compiler::Typer::Visitor::JSCompareTyper(), v8::internal::compiler::JSBinopReduction::LeftInputIs(), v8::internal::compiler::RepresentationSelector::MaskShiftOperand(), v8::internal::compiler::Typer::Visitor::NumberCompareTyper(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::OffsetOfElementsAccess(), v8::internal::compiler::TypeNarrowingReducer::Reduce(), v8::internal::compiler::TypedOptimization::ReduceCheckEqualsInternalizedString(), v8::internal::compiler::TypedOptimization::ReduceCheckEqualsSymbol(), v8::internal::compiler::TypedOptimization::ReduceCheckNumber(), v8::internal::compiler::TypedOptimization::ReduceCheckNumberFitsInt32(), v8::internal::compiler::TypedOptimization::ReduceCheckString(), v8::internal::compiler::TypedOptimization::ReduceCheckStringOrStringWrapper(), v8::internal::compiler::JSTypedLowering::ReduceJSBitwiseNot(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSCallForwardVarargs(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSTypedLowering::ReduceJSDecrement(), v8::internal::compiler::JSTypedLowering::ReduceJSIncrement(), v8::internal::compiler::JSTypedLowering::ReduceJSLoadNamed(), v8::internal::compiler::JSTypedLowering::ReduceJSNegate(), v8::internal::compiler::JSTypedLowering::ReduceJSParseInt(), v8::internal::compiler::JSTypedLowering::ReduceJSResolvePromise(), v8::internal::compiler::JSTypedLowering::ReduceJSToBigInt(), v8::internal::compiler::JSTypedLowering::ReduceJSToBigIntConvertNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToLength(), v8::internal::compiler::JSTypedLowering::ReduceJSToName(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumber(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumberInput(), v8::internal::compiler::TypedOptimization::ReduceJSToNumberInput(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumeric(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSTypedLowering::ReduceJSToStringInput(), v8::internal::compiler::LoadElimination::ReduceLoadElement(), v8::internal::compiler::MemoryLowering::ReduceLoadField(), v8::internal::compiler::TypedOptimization::ReduceMaybeGrowFastElements(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode(), v8::internal::compiler::TypedOptimization::ReduceNumberFloor(), v8::internal::compiler::TypedOptimization::ReduceNumberRoundop(), v8::internal::compiler::TypedOptimization::ReduceNumberSilenceNaN(), v8::internal::compiler::TypedOptimization::ReduceNumberToUint8Clamped(), v8::internal::compiler::TypedOptimization::ReducePhi(), v8::internal::compiler::TypedOptimization::ReduceReferenceEqual(), v8::internal::compiler::TypedOptimization::ReduceSameValue(), v8::internal::compiler::TypedOptimization::ReduceSelect(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberComparison(), v8::internal::compiler::TypedOptimization::ReduceSpeculativeToNumber(), v8::internal::compiler::MemoryLowering::ReduceStoreField(), v8::internal::compiler::TypedOptimization::ReduceStringComparison(), v8::internal::compiler::TypedOptimization::ReduceToBoolean(), v8::internal::compiler::Typer::Visitor::ReferenceEqualTyper(), v8::internal::compiler::ValueNumberingReducer::ReplaceIfTypesMatch(), v8::internal::compiler::EscapeAnalysisReducer::ReplaceNode(), v8::internal::compiler::JSBinopReduction::RightInputIs(), v8::internal::compiler::OperationTyper::SameValue(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::StoreFieldImpl(), v8::internal::compiler::OperationTyper::StrictEqual(), v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift(), v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCode(), v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::TypeSubsumes(), v8::internal::compiler::RepresentationSelector::UpdateFeedbackType(), v8::internal::compiler::Typer::Visitor::UpdateType(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitObjectIs(), v8::internal::compiler::RepresentationSelector::VisitSelect(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeSmallIntegerAdditiveOp(), and v8::internal::compiler::RepresentationSelector::WriteBarrierKindFor().
IsAny()
bool v8::internal::compiler::Type::IsAny () const [inline], [private]
Definition at line 558 of file turbofan-types.h.
{ return payload_ == Any().payload_; }
IsBitset()
bool v8::internal::compiler::Type::IsBitset () const [inline]
Definition at line 471 of file turbofan-types.h.
{ return payload_ & uint64_t{1}; }
IsHeapConstant()
bool v8::internal::compiler::Type::IsHeapConstant () const [inline]
Definition at line 473 of file turbofan-types.h.
{ return IsKind(TypeBase::kHeapConstant); }
References v8::internal::compiler::TypeBase::kHeapConstant.
Referenced by v8::internal::compiler::JSTypedLowering::BuildGetModuleCell(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::anonymous_namespace{escape-analysis.cc}::CheckMapsHelper(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::GetStableMapFromObjectType(), v8::internal::compiler::Typer::Visitor::JSCallTyper(), v8::internal::compiler::Typer::Visitor::NumberCompareTyper(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSConstructForwardVarargs(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject(), v8::internal::compiler::JSTypedLowering::ReduceJSToNumberInput(), v8::internal::compiler::TypedOptimization::ReduceJSToNumberInput(), v8::internal::compiler::TypedOptimization::ReduceReferenceEqual(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::Typer::Visitor::ReferenceEqualTyper(), v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift(), and v8::internal::compiler::TypedOptimization::TryReduceStringComparisonOfStringFromSingleCharCode().
IsInvalid()
bool v8::internal::compiler::Type::IsInvalid () const [inline]
Definition at line 462 of file turbofan-types.h.
{ return payload_ == uint64_t{0}; }
Referenced by v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::compiler::RepresentationSelector::PrintNodeFeedbackType(), v8::internal::compiler::RepresentationSelector::RunVerifyPhase(), v8::internal::compiler::RepresentationSelector::UpdateFeedbackType(), v8::internal::compiler::Typer::Visitor::Weaken(), and v8::internal::compiler::RepresentationSelector::Weaken().
IsKind()
bool v8::internal::compiler::Type::IsKind (TypeBase::Kind kind) const [inline], [private]
Definition at line 547 of file turbofan-types.h.
                                       {
    if (IsBitset()) return false;
    const TypeBase* base = ToTypeBase();
    return base->kind() == kind;
  }
References v8::internal::compiler::TypeBase::kind().
IsNone()
bool v8::internal::compiler::Type::IsNone () const [inline]
Definition at line 461 of file turbofan-types.h.
{ return payload_ == None().payload_; }
Referenced by v8::internal::compiler::Typer::Visitor::BigIntCompareTyper(), v8::internal::compiler::Typer::Visitor::BinaryNumberOpTyper(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CanOverflowSigned32(), v8::internal::compiler::RepresentationChanger::GetRepresentationFor(), v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint(), v8::internal::compiler::anonymous_namespace{dead-code-elimination.cc}::NoReturn(), v8::internal::compiler::Typer::Visitor::NumberCompareTyper(), v8::internal::compiler::JSTypedLowering::ReduceJSToLength(), v8::internal::compiler::TypedOptimization::ReduceMaybeGrowFastElements(), v8::internal::compiler::TypedOptimization::ReduceNumberFloor(), v8::internal::compiler::OperationTyper::SameValue(), v8::internal::compiler::OperationTyper::StrictEqual(), v8::internal::compiler::Typer::Visitor::TypeBinaryOp(), v8::internal::compiler::Typer::Visitor::TypeUnaryOp(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitNode(), and v8::internal::compiler::RepresentationSelector::Weaken().
IsOtherNumberConstant()
bool v8::internal::compiler::Type::IsOtherNumberConstant () const [inline]
Definition at line 474 of file turbofan-types.h.
                                     {
    return IsKind(TypeBase::kOtherNumberConstant);
  }
References v8::internal::compiler::TypeBase::kOtherNumberConstant.
IsRange()
bool v8::internal::compiler::Type::IsRange () const [inline]
Definition at line 472 of file turbofan-types.h.
{ return IsKind(TypeBase::kRange); }
References v8::internal::compiler::TypeBase::kRange.
Referenced by v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor().
IsSingleton()
bool v8::internal::compiler::Type::IsSingleton () const [inline]
Definition at line 482 of file turbofan-types.h.
                           {
    if (IsNone()) return false;
    return Is(Type::Null()) || Is(Type::Undefined()) || Is(Type::MinusZero()) ||
           Is(Type::NaN()) || IsHeapConstant() ||
           (Is(Type::PlainNumber()) && Min() == Max());
  }
References v8::internal::Is(), v8::internal::IsNone(), v8::internal::compiler::Null, and v8::internal::compiler::Undefined.
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSStrictEqual(), and v8::internal::compiler::OperationTyper::StrictEqual().
IsTuple()
bool v8::internal::compiler::Type::IsTuple () const [inline]
Definition at line 477 of file turbofan-types.h.
{ return IsKind(TypeBase::kTuple); }
References v8::internal::compiler::TypeBase::kTuple.
IsUnion()
bool v8::internal::compiler::Type::IsUnion () const [inline], [private]
Definition at line 559 of file turbofan-types.h.
{ return IsKind(TypeBase::kUnion); }
References v8::internal::compiler::TypeBase::kUnion.
IsUnionForTesting()
bool v8::internal::compiler::Type::IsUnionForTesting () [inline]
Definition at line 527 of file turbofan-types.h.
{ return IsUnion(); }
Max()
double v8::internal::compiler::Type::Max () const
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CanOverflowSigned32(), v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint(), v8::internal::compiler::Typer::Visitor::NumberCompareTyper(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::OffsetOfElementsAccess(), v8::internal::compiler::TypeNarrowingReducer::Reduce(), v8::internal::compiler::JSCallReducer::ReduceArrayIteratorPrototypeNext(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSTypedLowering::ReduceJSToLength(), v8::internal::compiler::TypedOptimization::ReduceMaybeGrowFastElements(), v8::internal::compiler::OperationTyper::SameValue(), v8::internal::compiler::OperationTyper::StrictEqual(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), v8::internal::compiler::Typer::Visitor::Weaken(), and v8::internal::compiler::OperationTyper::WeakenRange().
Maybe()
bool v8::internal::compiler::Type::Maybe (Type that) const
Referenced by v8::internal::compiler::JSBinopReduction::BothInputsMaybe(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CanOverflowSigned32(), v8::internal::compiler::OperationTyper::ConvertTaggedHoleToUndefined(), v8::internal::compiler::RepresentationChanger::GetBitRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetFloat64RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedPointerRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedSignedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::RepresentationSelector::InputCannotBe(), v8::internal::compiler::Typer::Visitor::JSCompareTyper(), v8::internal::compiler::LoadElimination::AbstractElements::Kill(), v8::internal::compiler::anonymous_namespace{typed-optimization.cc}::NeitherCanBe(), v8::internal::compiler::JSBinopReduction::NeitherInputCanBe(), v8::internal::compiler::Typer::Visitor::NumberCompareTyper(), v8::internal::compiler::RepresentationSelector::OneInputCannotBe(), v8::internal::compiler::JSBinopReduction::OneInputCannotBe(), v8::internal::compiler::OperationTyper::OperationTyper(), v8::internal::compiler::TypedOptimization::ReduceCheckBounds(), v8::internal::compiler::TypedOptimization::ReduceCheckHeapObject(), v8::internal::compiler::TypedOptimization::ReduceCheckNotTaggedHole(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSTypedLowering::ReduceJSOrdinaryHasInstance(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::TypedOptimization::ReduceReferenceEqual(), v8::internal::compiler::OperationTyper::SameValue(), v8::internal::compiler::OperationTyper::StrictEqual(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::RepresentationSelector::VisitObjectIs(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus(), v8::internal::compiler::RepresentationSelector::VisitSpeculativeSmallIntegerAdditiveOp(), v8::internal::compiler::Typer::Visitor::Weaken(), and v8::internal::compiler::RepresentationSelector::Weaken().
Min()
double v8::internal::compiler::Type::Min () const
Referenced by v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CanOverflowSigned32(), v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint(), v8::internal::compiler::Typer::Visitor::NumberCompareTyper(), v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::OffsetOfElementsAccess(), v8::internal::compiler::TypeNarrowingReducer::Reduce(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSTypedLowering::ReduceJSToLength(), v8::internal::compiler::TypedOptimization::ReduceMaybeGrowFastElements(), v8::internal::compiler::OperationTyper::SameValue(), v8::internal::compiler::OperationTyper::StrictEqual(), v8::internal::compiler::RepresentationSelector::VisitCheckBounds(), v8::internal::compiler::Typer::Visitor::Weaken(), and v8::internal::compiler::OperationTyper::WeakenRange().
NewBitset()
static Type v8::internal::compiler::Type::NewBitset (bitset bits) [inline], [static], [private]
Definition at line 573 of file turbofan-types.h.
{ return Type(bits); }
NormalizeRangeAndBitset()
static Type v8::internal::compiler::Type::NormalizeRangeAndBitset (Type range, bitset * bits, Zone * zone) [static], [private]
NormalizeUnion()
static Type v8::internal::compiler::Type::NormalizeUnion (UnionType * unioned, int size, Zone * zone) [static], [private]
NumConstants()
int v8::internal::compiler::Type::NumConstants () const
operator!=()
bool v8::internal::compiler::Type::operator!= (Type other) const [inline]
Definition at line 516 of file turbofan-types.h.
{ return payload_ != other.payload_; }
References payload_.
operator==()
bool v8::internal::compiler::Type::operator== (Type other) const [inline]
Definition at line 515 of file turbofan-types.h.
{ return payload_ == other.payload_; }
References payload_.
OtherNumberConstant()
static Type v8::internal::compiler::Type::OtherNumberConstant (double value, Zone * zone) [static], [private]
Overlap()
static bool v8::internal::compiler::Type::Overlap (const RangeType * lhs, const RangeType * rhs) [static], [private]
PrintTo()
void v8::internal::compiler::Type::PrintTo (std::ostream & os) const
Referenced by v8::internal::compiler::SimplifiedLoweringVerifier::CheckType(), and v8::internal::compiler::RepresentationChanger::TypeError().
Range() [1/2]
static Type v8::internal::compiler::Type::Range (double min, double max, Zone * zone) [static]
Referenced by v8::internal::compiler::OperationTyper::AddRanger(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::OperationTyper::CheckBounds(), v8::internal::compiler::TypeCache::CreateRange(), v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint(), v8::internal::compiler::IsNonTruncatingMachineTypeFor(), v8::internal::compiler::Typer::Visitor::JSCallTyper(), v8::internal::compiler::OperationTyper::MultiplyRanger(), v8::internal::compiler::OperationTyper::Rangify(), v8::internal::compiler::OperationTyper::SubtractRanger(), v8::internal::compiler::Typer::Visitor::ToLength(), v8::internal::compiler::Typer::Visitor::Weaken(), and v8::internal::compiler::OperationTyper::WeakenRange().
Range() [2/2]
static Type v8::internal::compiler::Type::Range (RangeType::Limits lims, Zone * zone) [static], [private]
SignedSmall()
static Type v8::internal::compiler::Type::SignedSmall () [inline], [static]
Definition at line 436 of file turbofan-types.h.
{ return NewBitset(BitsetType::SignedSmall()); }
References v8::internal::compiler::BitsetType::SignedSmall().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::BuildExtendPropertiesBackingStore(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::AccessInfoFactory::ComputeDataFieldAccessInfo(), v8::internal::compiler::AccessBuilder::ForContextSlotSmi(), v8::internal::compiler::AccessBuilder::ForDictionaryNextEnumerationIndex(), v8::internal::compiler::AccessBuilder::ForDictionaryObjectHashIndex(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForHashTableBaseCapacity(), v8::internal::compiler::AccessBuilder::ForHashTableBaseNumberOfDeletedElement(), v8::internal::compiler::AccessBuilder::ForHashTableBaseNumberOfElements(), v8::internal::compiler::AccessBuilder::ForJSAsyncGeneratorObjectIsAwaiting(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContinuation(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectResumeMode(), v8::internal::compiler::AccessBuilder::ForNameDictionaryFlagsIndex(), v8::internal::compiler::AccessBuilder::ForPropertyArrayLengthAndHash(), v8::internal::compiler::AccessBuilder::ForSlicedStringOffset(), v8::internal::compiler::RepresentationChanger::GetBitRepresentationFor(), v8::internal::compiler::RepresentationSelector::GetOutputInfoForPhi(), v8::internal::compiler::RepresentationChanger::GetTaggedPointerRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetTaggedSignedRepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord32RepresentationFor(), v8::internal::compiler::RepresentationChanger::GetWord64RepresentationFor(), v8::internal::compiler::AccessInfoFactory::LookupTransition(), v8::internal::compiler::Typer::Visitor::ObjectIsSmi(), v8::internal::compiler::TypedOptimization::ReduceCheckHeapObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceGlobalAccess(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::JSCreateLowering::ReduceNewArray(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::TransitionAndStoreArrayElement(), v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode(), and v8::internal::compiler::RepresentationSelector::VisitNode().
SimplyEquals()
bool v8::internal::compiler::Type::SimplyEquals (Type that) const [private]
SlowIs()
bool v8::internal::compiler::Type::SlowIs (Type that) const [private]
ToLimits()
static RangeType::Limits v8::internal::compiler::Type::ToLimits (bitset bits, Zone * zone) [static], [private]
ToTypeBase()
const TypeBase* v8::internal::compiler::Type::ToTypeBase () const [inline], [private]
Definition at line 553 of file turbofan-types.h.
                                     {
    return reinterpret_cast<TypeBase*>(payload_);
  }
Tuple() [1/2]
static Type v8::internal::compiler::Type::Tuple (Type first, Type second, Type third, Zone * zone) [static]
Tuple() [2/2]
static Type v8::internal::compiler::Type::Tuple (Type first, Type second, Zone * zone) [static]
Union()
static Type v8::internal::compiler::Type::Union (Type type1, Type type2, Zone * zone) [static]
Referenced by v8::internal::compiler::OperationTyper::AddRanger(), v8::internal::compiler::JSNativeContextSpecialization::BuildElementAccess(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CanOverflowSigned32(), v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::OperationTyper::CheckBounds(), v8::internal::compiler::OperationTyper::CheckFloat64Hole(), v8::internal::compiler::OperationTyper::ConvertTaggedHoleToUndefined(), v8::internal::compiler::RepresentationSelector::GetOutputInfoForPhi(), v8::internal::compiler::Typer::Visitor::InductionVariablePhiTypeIsPrefixedPoint(), v8::internal::compiler::Typer::Visitor::JSCallTyper(), v8::internal::compiler::PropertyAccessInfo::Merge(), v8::internal::compiler::OperationTyper::Merge(), v8::internal::compiler::GraphAssembler::MergeState(), v8::internal::compiler::OperationTyper::MultiplyRanger(), v8::internal::compiler::OperationTyper::OperationTyper(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::TypedOptimization::ReducePhi(), v8::internal::compiler::TypedOptimization::ReduceSelect(), v8::internal::compiler::OperationTyper::SubtractRanger(), v8::internal::compiler::OperationTyper::ToBigIntConvertNumber(), v8::internal::compiler::Typer::Visitor::ToInteger(), v8::internal::compiler::OperationTyper::ToNumber(), v8::internal::compiler::OperationTyper::ToNumberConvertBigInt(), v8::internal::compiler::OperationTyper::ToNumeric(), v8::internal::compiler::RepresentationSelector::VisitNode(), v8::internal::compiler::Typer::Visitor::Weaken(), and v8::internal::compiler::RepresentationSelector::Weaken().
UnsignedSmall()
static Type v8::internal::compiler::Type::UnsignedSmall () [inline], [static]
Definition at line 437 of file turbofan-types.h.
{ return NewBitset(BitsetType::UnsignedSmall()); }
References v8::internal::compiler::BitsetType::UnsignedSmall().
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray(), v8::internal::compiler::RedundancyElimination::ReduceSpeculativeNumberComparison(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeSubstr(), and v8::internal::compiler::JSCallReducerAssembler::TypeGuardUnsignedSmall().
UpdateRange()
static int v8::internal::compiler::Type::UpdateRange (Type type, UnionType * result, int size, Zone * zone) [static], [private]
Friends And Related Function Documentation
hash_value
size_t hash_value (Type type) [friend]
Definition at line 602 of file turbofan-types.h.
{ return type.payload_; }
Iterator
template<class >
friend class Iterator [friend]
Definition at line 536 of file turbofan-types.h.
Member Data Documentation
BitsetType
friend v8::internal::compiler::Type::BitsetType [private]
Definition at line 537 of file turbofan-types.h.
payload_
uint64_t v8::internal::compiler::Type::payload_ [private]
Definition at line 599 of file turbofan-types.h.
Referenced by Is(), operator!=(), and operator==().
UnionType
friend v8::internal::compiler::Type::UnionType [private]
Definition at line 538 of file turbofan-types.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turbofan-types.h