v8::internal::compiler::SpillPlacer::Entry Class Reference
Public Member Functions
void SetSpillRequiredSingleValue (int value_index)
void SetDefinitionSingleValue (int value_index)
uint64_t SpillRequired () const
void SetSpillRequired (uint64_t mask)
uint64_t SpillRequiredInNonDeferredSuccessor () const
void SetSpillRequiredInNonDeferredSuccessor (uint64_t mask)
uint64_t SpillRequiredInDeferredSuccessor () const
void SetSpillRequiredInDeferredSuccessor (uint64_t mask)
uint64_t Definition () const
void SetDefinition (uint64_t mask)
Private Types
enum State {
kUnmarked
, kSpillRequired
, kSpillRequiredInNonDeferredSuccessor
, kSpillRequiredInDeferredSuccessor
,
kDefinition
 }
Private Member Functions
template<State state>
uint64_t GetValuesInState () const
template<State state>
void UpdateValuesToState (uint64_t mask)
Static Private Member Functions
template<bool set_ones>
static uint64_t UpdateBitDataWithMask (uint64_t data, uint64_t mask)
Private Attributes
uint64_t first_bit_ = 0
uint64_t second_bit_ = 0
uint64_t third_bit_ = 0
Detailed Description
Definition at line 115 of file spill-placer.cc.
Member Enumeration Documentation
State
enum v8::internal::compiler::SpillPlacer::Entry::State [private]
Enumerator
kUnmarked
kSpillRequired
kSpillRequiredInNonDeferredSuccessor
kSpillRequiredInDeferredSuccessor
kDefinition
Definition at line 153 of file spill-placer.cc.
             {
    // This block is not (yet) known to require the on-stack value.
    kUnmarked,
    // The value must be on the stack in this block.
    kSpillRequired,
    // The value doesn't need to be on-stack in this block, but some
    // non-deferred successor needs it.
    kSpillRequiredInNonDeferredSuccessor,
    // The value doesn't need to be on-stack in this block, but some
    // deferred successor needs it.
    kSpillRequiredInDeferredSuccessor,
    // The value is defined in this block.
    kDefinition,
  };
Member Function Documentation
Definition()
uint64_t v8::internal::compiler::SpillPlacer::Entry::Definition () const [inline]
Definition at line 148 of file spill-placer.cc.
{ return GetValuesInState<kDefinition>(); }
Referenced by v8::internal::compiler::SpillPlacer::FirstBackwardPass(), and v8::internal::compiler::SpillPlacer::SecondBackwardPass().
GetValuesInState()
template<State state>
uint64_t v8::internal::compiler::SpillPlacer::Entry::GetValuesInState () const [inline], [private]
Definition at line 173 of file spill-placer.cc.
                                    {
    static_assert(state < 8);
    return ((state & 1) ? first_bit_ : ~first_bit_) &
           ((state & 2) ? second_bit_ : ~second_bit_) &
           ((state & 4) ? third_bit_ : ~third_bit_);
  }
References first_bit_, second_bit_, and third_bit_.
SetDefinition()
void v8::internal::compiler::SpillPlacer::Entry::SetDefinition (uint64_t mask) [inline]
Definition at line 149 of file spill-placer.cc.
{ UpdateValuesToState<kDefinition>(mask); }
Referenced by SetDefinitionSingleValue().
SetDefinitionSingleValue()
void v8::internal::compiler::SpillPlacer::Entry::SetDefinitionSingleValue (int value_index) [inline]
Definition at line 124 of file spill-placer.cc.
                                                 {
    DCHECK_LT(value_index, kValueIndicesPerEntry);
    uint64_t bit = uint64_t{1} << value_index;
    SetDefinition(bit);
  }
References DCHECK_LT, v8::internal::compiler::SpillPlacer::kValueIndicesPerEntry, and SetDefinition().
Referenced by v8::internal::compiler::SpillPlacer::SetDefinition().
SetSpillRequired()
void v8::internal::compiler::SpillPlacer::Entry::SetSpillRequired (uint64_t mask) [inline]
Definition at line 133 of file spill-placer.cc.
                                       {
    UpdateValuesToState<kSpillRequired>(mask);
  }
Referenced by v8::internal::compiler::SpillPlacer::ForwardPass(), v8::internal::compiler::SpillPlacer::SecondBackwardPass(), and SetSpillRequiredSingleValue().
SetSpillRequiredInDeferredSuccessor()
void v8::internal::compiler::SpillPlacer::Entry::SetSpillRequiredInDeferredSuccessor (uint64_t mask) [inline]
Definition at line 145 of file spill-placer.cc.
                                                          {
    UpdateValuesToState<kSpillRequiredInDeferredSuccessor>(mask);
  }
Referenced by v8::internal::compiler::SpillPlacer::FirstBackwardPass().
SetSpillRequiredInNonDeferredSuccessor()
void v8::internal::compiler::SpillPlacer::Entry::SetSpillRequiredInNonDeferredSuccessor (uint64_t mask) [inline]
Definition at line 139 of file spill-placer.cc.
                                                             {
    UpdateValuesToState<kSpillRequiredInNonDeferredSuccessor>(mask);
  }
Referenced by v8::internal::compiler::SpillPlacer::FirstBackwardPass().
SetSpillRequiredSingleValue()
void v8::internal::compiler::SpillPlacer::Entry::SetSpillRequiredSingleValue (int value_index) [inline]
Definition at line 119 of file spill-placer.cc.
                                                    {
    DCHECK_LT(value_index, kValueIndicesPerEntry);
    uint64_t bit = uint64_t{1} << value_index;
    SetSpillRequired(bit);
  }
References DCHECK_LT, v8::internal::compiler::SpillPlacer::kValueIndicesPerEntry, and SetSpillRequired().
Referenced by v8::internal::compiler::SpillPlacer::SetSpillRequired().
SpillRequired()
uint64_t v8::internal::compiler::SpillPlacer::Entry::SpillRequired () const [inline]
Definition at line 132 of file spill-placer.cc.
{ return GetValuesInState<kSpillRequired>(); }
Referenced by v8::internal::compiler::SpillPlacer::FirstBackwardPass(), v8::internal::compiler::SpillPlacer::ForwardPass(), and v8::internal::compiler::SpillPlacer::SecondBackwardPass().
SpillRequiredInDeferredSuccessor()
uint64_t v8::internal::compiler::SpillPlacer::Entry::SpillRequiredInDeferredSuccessor () const [inline]
Definition at line 142 of file spill-placer.cc.
                                                    {
    return GetValuesInState<kSpillRequiredInDeferredSuccessor>();
  }
Referenced by v8::internal::compiler::SpillPlacer::FirstBackwardPass(), and v8::internal::compiler::SpillPlacer::ForwardPass().
SpillRequiredInNonDeferredSuccessor()
uint64_t v8::internal::compiler::SpillPlacer::Entry::SpillRequiredInNonDeferredSuccessor () const [inline]
Definition at line 136 of file spill-placer.cc.
                                                       {
    return GetValuesInState<kSpillRequiredInNonDeferredSuccessor>();
  }
Referenced by v8::internal::compiler::SpillPlacer::FirstBackwardPass(), and v8::internal::compiler::SpillPlacer::ForwardPass().
UpdateBitDataWithMask()
template<bool set_ones>
static uint64_t v8::internal::compiler::SpillPlacer::Entry::UpdateBitDataWithMask (uint64_t data, uint64_t mask) [inline], [static], [private]
Definition at line 192 of file spill-placer.cc.
                                                                      {
    return set_ones ? data | mask : data & ~mask;
  }
References v8::internal::compiler::SpillPlacer::data().
UpdateValuesToState()
template<State state>
void v8::internal::compiler::SpillPlacer::Entry::UpdateValuesToState (uint64_t mask) [inline], [private]
Definition at line 181 of file spill-placer.cc.
                                          {
    static_assert(state < 8);
    first_bit_ =
        Entry::UpdateBitDataWithMask<(state & 1) != 0>(first_bit_, mask);
    second_bit_ =
        Entry::UpdateBitDataWithMask<(state & 2) != 0>(second_bit_, mask);
    third_bit_ =
        Entry::UpdateBitDataWithMask<(state & 4) != 0>(third_bit_, mask);
  }
References first_bit_, second_bit_, and third_bit_.
Member Data Documentation
first_bit_
uint64_t v8::internal::compiler::SpillPlacer::Entry::first_bit_ = 0 [private]
Definition at line 197 of file spill-placer.cc.
Referenced by GetValuesInState(), and UpdateValuesToState().
second_bit_
uint64_t v8::internal::compiler::SpillPlacer::Entry::second_bit_ = 0 [private]
Definition at line 198 of file spill-placer.cc.
Referenced by GetValuesInState(), and UpdateValuesToState().
third_bit_
uint64_t v8::internal::compiler::SpillPlacer::Entry::third_bit_ = 0 [private]
Definition at line 199 of file spill-placer.cc.
Referenced by GetValuesInState(), and UpdateValuesToState().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/spill-placer.cc