v8::internal::EndNode Class Reference
#include <regexp-nodes.h>
Public Types
enum Action { ACCEPT
, BACKTRACK
, NEGATIVE_SUBMATCH_SUCCESS
 }
Public Member Functions
EndNode (Action action, Zone *zone)
EndNode * AsEndNode () override
void Accept (NodeVisitor *visitor) override
void Emit (RegExpCompiler *compiler, Trace *trace) override
void GetQuickCheckDetails (QuickCheckDetails *details, RegExpCompiler *compiler, int characters_filled_in, bool not_at_start) override
void FillInBMInfo (Isolate *isolate, int offset, int budget, BoyerMooreLookahead *bm, bool not_at_start) override
Private Attributes
Action action_
Additional Inherited Members
Detailed Description
Definition at line 585 of file regexp-nodes.h.
Member Enumeration Documentation
Action
enum v8::internal::EndNode::Action
Enumerator
ACCEPT
BACKTRACK
NEGATIVE_SUBMATCH_SUCCESS
Definition at line 587 of file regexp-nodes.h.
{ ACCEPT, BACKTRACK, NEGATIVE_SUBMATCH_SUCCESS };
Constructor & Destructor Documentation
EndNode()
v8::internal::EndNode::EndNode (Action action, Zone * zone) [inline]
Definition at line 588 of file regexp-nodes.h.
: RegExpNode(zone), action_(action) {}
Member Function Documentation
Accept()
void v8::internal::EndNode::Accept (NodeVisitor * visitor) [override], [virtual]
Implements v8::internal::RegExpNode.
AsEndNode()
EndNode* v8::internal::EndNode::AsEndNode () [inline], [override]
Definition at line 589 of file regexp-nodes.h.
{ return this; }
Emit()
void v8::internal::EndNode::Emit (RegExpCompiler * compiler, Trace * trace) [override], [virtual]
Implements v8::internal::RegExpNode.
Reimplemented in v8::internal::NegativeSubmatchSuccess.
Definition at line 615 of file regexp-compiler.cc.
                                                         {
  if (!trace->is_trivial()) {
    DCHECK(action_ == ACCEPT);
    trace->Flush(compiler, this, Trace::kFlushSuccess);
    return;
  }
  RegExpMacroAssembler* assembler = compiler->macro_assembler();
  if (!label()->is_bound()) {
    assembler->Bind(label());
  }
  switch (action_) {
    case ACCEPT:
      assembler->Succeed();
      return;
    case BACKTRACK:
      assembler->GoTo(trace->backtrack());
      return;
    case NEGATIVE_SUBMATCH_SUCCESS:
      // This case is handled in a different virtual method.
      UNREACHABLE();
  }
  UNIMPLEMENTED();
}
References ACCEPT, action_, v8::internal::Trace::backtrack(), BACKTRACK, v8::internal::RegExpMacroAssembler::Bind(), v8::internal::DCHECK(), v8::internal::Trace::Flush(), v8::internal::RegExpMacroAssembler::GoTo(), v8::internal::Trace::is_trivial(), v8::internal::Trace::kFlushSuccess, v8::internal::RegExpNode::label(), v8::internal::RegExpCompiler::macro_assembler(), NEGATIVE_SUBMATCH_SUCCESS, v8::internal::RegExpMacroAssembler::Succeed(), v8::internal::UNIMPLEMENTED(), and v8::internal::UNREACHABLE().
FillInBMInfo()
void v8::internal::EndNode::FillInBMInfo (Isolate * isolate, int offset, int budget, BoyerMooreLookahead * bm, bool not_at_start) [inline], [override], [virtual]
Reimplemented from v8::internal::RegExpNode.
Definition at line 598 of file regexp-nodes.h.
                                                                         {
    // Returning 0 from EatsAtLeast should ensure we never get here.
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
GetQuickCheckDetails()
void v8::internal::EndNode::GetQuickCheckDetails (QuickCheckDetails * details, RegExpCompiler * compiler, int characters_filled_in, bool not_at_start) [inline], [override], [virtual]
Implements v8::internal::RegExpNode.
Definition at line 592 of file regexp-nodes.h.
                                                        {
    // Returning 0 from EatsAtLeast should ensure we never get here.
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
Member Data Documentation
action_
Action v8::internal::EndNode::action_ [private]
Definition at line 605 of file regexp-nodes.h.
Referenced by Emit().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-nodes.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc