v8::internal::compiler::GraphAssembler::LoopScope< Reps > Class Template Reference
#include <graph-assembler.h>
Classes
class LoopScopeInternal
Public Member Functions
LoopScope (GraphAssembler *gasm)
~LoopScope ()
GraphAssemblerLabel< sizeof...(Reps)> * loop_header_label ()
Private Attributes
const LoopScopeInternal internal_scope_
GraphAssembler *const gasm_
GraphAssemblerLabel< sizeof...(Reps)> loop_header_label_
Detailed Description
template<MachineRepresentation... Reps>
class v8::internal::compiler::GraphAssembler::LoopScope< Reps >
Definition at line 577 of file graph-assembler.h.
Constructor & Destructor Documentation
LoopScope()
template<MachineRepresentation... Reps>
v8::internal::compiler::GraphAssembler::LoopScope< Reps >::LoopScope (GraphAssembler * gasm) [inline], [explicit]
Definition at line 600 of file graph-assembler.h.
        : internal_scope_(gasm),
          gasm_(gasm),
          loop_header_label_(gasm->MakeLoopLabel(Reps...)) {
      // This feature may only be used if it has been enabled.
      DCHECK(gasm_->mark_loop_exits_);
      gasm->loop_headers_.push_back(&loop_header_label_.control_);
      DCHECK_EQ(static_cast<int>(gasm_->loop_headers_.size()),
                gasm_->loop_nesting_level_);
    }
References v8::internal::DCHECK(), DCHECK_EQ, and v8::internal::compiler::GraphAssembler::loop_headers_.
 LoopScope()
template<MachineRepresentation... Reps>
v8::internal::compiler::GraphAssembler::LoopScope< Reps >::~LoopScope () [inline]
Definition at line 611 of file graph-assembler.h.
                 {
      DCHECK_EQ(static_cast<int>(gasm_->loop_headers_.size()),
                gasm_->loop_nesting_level_);
      gasm_->loop_headers_.pop_back();
    }
References DCHECK_EQ.
Member Function Documentation
loop_header_label()
template<MachineRepresentation... Reps>
GraphAssemblerLabel<sizeof...(Reps)>* v8::internal::compiler::GraphAssembler::LoopScope< Reps >::loop_header_label () [inline]
Definition at line 617 of file graph-assembler.h.
                                                              {
      return &loop_header_label_;
    }
Referenced by v8::internal::compiler::JSCallReducerAssembler::ForBuilder0::Do(), and v8::internal::compiler::JSCallReducerAssembler::ForBuilder1::Value().
Member Data Documentation
gasm_
template<MachineRepresentation... Reps>
GraphAssembler* const v8::internal::compiler::GraphAssembler::LoopScope< Reps >::gasm_ [private]
Definition at line 623 of file graph-assembler.h.
internal_scope_
template<MachineRepresentation... Reps>
const LoopScopeInternal v8::internal::compiler::GraphAssembler::LoopScope< Reps >::internal_scope_ [private]
Definition at line 622 of file graph-assembler.h.
loop_header_label_
template<MachineRepresentation... Reps>
GraphAssemblerLabel<sizeof...(Reps)> v8::internal::compiler::GraphAssembler::LoopScope< Reps >::loop_header_label_ [private]
Definition at line 624 of file graph-assembler.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/graph-assembler.h