v8::internal::CompilationCacheScript Class Reference
#include <compilation-cache.h>
Public Types
using LookupResult = CompilationCacheScriptLookupResult
Public Member Functions
CompilationCacheScript (Isolate *isolate)
LookupResult Lookup (Handle< String > source, const ScriptDetails &script_details)
void Put (Handle< String > source, DirectHandle< SharedFunctionInfo > function_info)
void Age ()
Private Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (CompilationCacheScript)
Additional Inherited Members
Detailed Description
Definition at line 49 of file compilation-cache.h.
Member Typedef Documentation
LookupResult
using v8::internal::CompilationCacheScript::LookupResult = CompilationCacheScriptLookupResult
Definition at line 54 of file compilation-cache.h.
Constructor & Destructor Documentation
CompilationCacheScript()
v8::internal::CompilationCacheScript::CompilationCacheScript (Isolate * isolate) [inline], [explicit]
Definition at line 51 of file compilation-cache.h.
      : CompilationCacheEvalOrScript(isolate) {}
Member Function Documentation
Age()
void v8::internal::CompilationCacheScript::Age ()
Definition at line 66 of file compilation-cache.cc.
                                 {
  DisallowGarbageCollection no_gc;
  if (IsUndefined(table_, isolate())) return;
  Tagged<CompilationCacheTable> table = Cast<CompilationCacheTable>(table_);
  for (InternalIndex entry : table->IterateEntries()) {
    Tagged<Object> key;
    if (!table->ToKey(isolate(), entry, &key)) continue;
    DCHECK(IsWeakFixedArray(key));
    Tagged<Object> value = table->PrimaryValueAt(entry);
    if (!IsUndefined(value, isolate())) {
      Tagged<SharedFunctionInfo> info = Cast<SharedFunctionInfo>(value);
      // Clear entries after Bytecode was flushed from SFI.
      if (!info->HasBytecodeArray()) {
        table->SetPrimaryValueAt(entry,
                                 ReadOnlyRoots(isolate()).undefined_value(),
                                 SKIP_WRITE_BARRIER);
      }
    }
  }
}
References v8::internal::DCHECK(), v8::internal::CompilationCacheEvalOrScript::isolate(), v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, v8::internal::CompilationCacheEvalOrScript::table_, and v8::internal::value.
Referenced by v8::internal::CompilationCache::MarkCompactPrologue().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::CompilationCacheScript::DISALLOW_IMPLICIT_CONSTRUCTORS (CompilationCacheScript) [private]
Lookup()
CompilationCacheScript::LookupResult v8::internal::CompilationCacheScript::Lookup (Handle< String > source, const ScriptDetails & script_details)
Definition at line 135 of file compilation-cache.cc.
                                                                {
  DirectHandle<CompilationCacheTable> table = GetTable();
  LookupResult result = CompilationCacheTable::LookupScript(
      table, source, script_details, isolate());
  DirectHandle<Script> script;
  if (result.script().ToHandle(&script)) {
    DirectHandle<SharedFunctionInfo> sfi;
    if (result.toplevel_sfi().ToHandle(&sfi)) {
      isolate()->counters()->compilation_cache_hits()->Increment();
      LOG(isolate(), CompilationCacheEvent("hit", "script", *sfi));
    } else {
      isolate()->counters()->compilation_cache_partial_hits()->Increment();
    }
  } else {
    isolate()->counters()->compilation_cache_misses()->Increment();
  }
  return result;
}
References v8::internal::Isolate::counters(), v8::internal::CompilationCacheEvalOrScript::GetTable(), v8::internal::CompilationCacheEvalOrScript::isolate(), LOG, v8::internal::CompilationCacheTable::LookupScript(), v8::base::internal::result, and v8::internal::script.
Referenced by v8::internal::CompilationCache::LookupScript().
Put()
void v8::internal::CompilationCacheScript::Put (Handle< String > source, DirectHandle< SharedFunctionInfo > function_info)
Definition at line 156 of file compilation-cache.cc.
                                                                           {
  Handle<CompilationCacheTable> table = GetTable();
  table_ = *CompilationCacheTable::PutScript(table, source, kNullMaybeHandle,
                                             function_info, isolate());
}
References v8::internal::CompilationCacheEvalOrScript::GetTable(), v8::internal::CompilationCacheEvalOrScript::isolate(), v8::internal::kNullMaybeHandle, v8::internal::CompilationCacheTable::PutScript(), and v8::internal::CompilationCacheEvalOrScript::table_.
Referenced by v8::internal::CompilationCache::PutScript().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/compilation-cache.h
/mnt/V8SourceCode/src/codegen/compilation-cache.cc