v8::internal::DebugPropertyIterator Class Reference
#include <debug-property-iterator.h>
Public Member Functions
~DebugPropertyIterator () override=default
DebugPropertyIterator (const DebugPropertyIterator &)=delete
DebugPropertyIterator & operator= (const DebugPropertyIterator &)=delete
bool Done () const override
V8_WARN_UNUSED_RESULT Maybe< bool > Advance () override
v8::Local< v8::Name > name () const override
bool is_native_accessor () override
bool has_native_getter () override
bool has_native_setter () override
v8::Maybe< v8::PropertyAttribute > attributes () override
v8::Maybe< v8::debug::PropertyDescriptor > descriptor () override
bool is_own () override
bool is_array_index () override
Static Public Member Functions
static V8_WARN_UNUSED_RESULT std::unique_ptr< DebugPropertyIterator > Create (Isolate *isolate, DirectHandle< JSReceiver > receiver, bool skip_indices)
Private Types
enum { kExoticIndices = 0
, kEnumerableStrings = 1
, kAllProperties = 2
 }
Private Member Functions
DebugPropertyIterator (Isolate *isolate, DirectHandle< JSReceiver > receiver, bool skip_indices)
V8_WARN_UNUSED_RESULT bool FillKeysForCurrentPrototypeAndStage ()
bool should_move_to_next_stage () const
void CalculateNativeAccessorFlags ()
DirectHandle< Name > raw_name () const
void AdvanceToPrototype ()
V8_WARN_UNUSED_RESULT bool AdvanceInternal ()
Private Attributes
Isolate * isolate_
PrototypeIterator prototype_iterator_
enum v8::internal::DebugPropertyIterator:: { ... } stage_ = kExoticIndices
bool skip_indices_
size_t current_key_index_
Handle< FixedArray > current_keys_
size_t current_keys_length_
bool calculated_native_accessor_flags_ = false
int native_accessor_flags_ = 0
bool is_own_ = true
bool is_done_ = false
Detailed Description
Definition at line 24 of file debug-property-iterator.h.
Member Enumeration Documentation
anonymous enum
anonymous enum [private]
Enumerator
kExoticIndices
kEnumerableStrings
kAllProperties
Definition at line 58 of file debug-property-iterator.h.
       {
    kExoticIndices = 0,
    kEnumerableStrings = 1,
    kAllProperties = 2
  } stage_ = kExoticIndices;
Constructor & Destructor Documentation
 DebugPropertyIterator()
v8::internal::DebugPropertyIterator::~DebugPropertyIterator () [override], [default]
DebugPropertyIterator() [1/2]
v8::internal::DebugPropertyIterator::DebugPropertyIterator (const DebugPropertyIterator &) [delete]
Referenced by Create().
DebugPropertyIterator() [2/2]
v8::internal::DebugPropertyIterator::DebugPropertyIterator (Isolate * isolate, DirectHandle< JSReceiver > receiver, bool skip_indices) [private]
Definition at line 35 of file debug-property-iterator.cc.
    : isolate_(isolate),
      prototype_iterator_(isolate, receiver, kStartAtReceiver,
                          PrototypeIterator::END_AT_NULL),
      skip_indices_(skip_indices),
      current_key_index_(0),
      current_keys_(isolate_->factory()->empty_fixed_array()),
      current_keys_length_(0) {}
Member Function Documentation
Advance()
Maybe< bool > v8::internal::DebugPropertyIterator::Advance () [override], [virtual]
Implements v8::debug::PropertyIterator.
Definition at line 1503 of file debug-interface.cc.
                                           {
  if (isolate_->is_execution_terminating()) {
    return {};
  }
  Local<v8::Context> context = Utils::ToLocal(
      direct_handle(isolate_->context()->native_context(), isolate_));
  CallDepthScope<false> call_depth_scope(isolate_, context);
  if (!AdvanceInternal()) {
    DCHECK(isolate_->has_exception());
    return {};
  }
  return Just(true);
}
References DCHECK, v8::internal::direct_handle(), and v8::Just().
AdvanceInternal()
bool v8::internal::DebugPropertyIterator::AdvanceInternal () [private]
Definition at line 56 of file debug-property-iterator.cc.
                                            {
  ++current_key_index_;
  calculated_native_accessor_flags_ = false;
  while (should_move_to_next_stage()) {
    switch (stage_) {
      case kExoticIndices:
        stage_ = kEnumerableStrings;
        break;
      case kEnumerableStrings:
        stage_ = kAllProperties;
        break;
      case kAllProperties:
        AdvanceToPrototype();
        break;
    }
    if (!FillKeysForCurrentPrototypeAndStage()) return false;
  }
  return true;
}
References AdvanceToPrototype(), calculated_native_accessor_flags_, current_key_index_, FillKeysForCurrentPrototypeAndStage(), kAllProperties, kEnumerableStrings, kExoticIndices, should_move_to_next_stage(), and stage_.
AdvanceToPrototype()
void v8::internal::DebugPropertyIterator::AdvanceToPrototype () [private]
Definition at line 48 of file debug-property-iterator.cc.
                                               {
  stage_ = kExoticIndices;
  is_own_ = false;
  if (!prototype_iterator_.HasAccess()) is_done_ = true;
  prototype_iterator_.AdvanceIgnoringProxies();
  if (prototype_iterator_.IsAtEnd()) is_done_ = true;
}
References v8::internal::PrototypeIterator::AdvanceIgnoringProxies(), v8::internal::PrototypeIterator::HasAccess(), is_done_, is_own_, v8::internal::PrototypeIterator::IsAtEnd(), kExoticIndices, prototype_iterator_, and stage_.
Referenced by AdvanceInternal().
attributes()
v8::Maybe< v8::PropertyAttribute > v8::internal::DebugPropertyIterator::attributes () [override], [virtual]
Implements v8::debug::PropertyIterator.
Definition at line 107 of file debug-property-iterator.cc.
                                                               {
  DirectHandle<JSReceiver> receiver =
      PrototypeIterator::GetCurrent<JSReceiver>(prototype_iterator_);
  auto result =
      JSReceiver::GetPropertyAttributes(isolate_, receiver, raw_name());
  if (result.IsNothing()) return Nothing<v8::PropertyAttribute>();
  // This should almost never happen, however we have seen cases where we do
  // trigger this check. In these rare events, it typically is a
  // misconfiguration by an embedder (such as Blink) in how the embedder
  // processes properities.
  //
  // In the case of crbug.com/1262066 we discovered that Blink was returning
  // a list of properties to contain in an object, after which V8 queries each
  // property individually. But, Blink incorrectly claimed that the property
  // in question did *not* exist. As such, V8 is instructed to process a
  // property, requests the embedder for more information and then suddenly the
  // embedder claims it doesn't exist. In these cases, we hit this DCHECK.
  //
  // If you are running into this problem, check your embedder implementation
  // and verify that the data from both sides matches. If there is a mismatch,
  // V8 will crash.
#if DEBUG
  base::ScopedVector<char> property_message(128);
  base::ScopedVector<char> name_buffer(100);
  raw_name()->NameShortPrint(name_buffer);
  v8::base::SNPrintF(property_message, "Invalid result for property \"%s\"\n",
                     name_buffer.begin());
  DCHECK_WITH_MSG(result.FromJust() != ABSENT, property_message.begin());
#endif
  return Just(static_cast<v8::PropertyAttribute>(result.FromJust()));
}
References v8::internal::ABSENT, v8::base::Vector< T >::begin(), DCHECK_WITH_MSG, v8::internal::JSReceiver::GetPropertyAttributes(), isolate_, v8::Just(), prototype_iterator_, raw_name(), v8::base::internal::result, and v8::base::SNPrintF().
CalculateNativeAccessorFlags()
void v8::internal::DebugPropertyIterator::CalculateNativeAccessorFlags () [private]
Definition at line 245 of file debug-property-iterator.cc.
                                                         {
  if (calculated_native_accessor_flags_) return;
  if (stage_ == kExoticIndices) {
    native_accessor_flags_ = 0;
  } else {
    DirectHandle<JSReceiver> receiver =
        PrototypeIterator::GetCurrent<JSReceiver>(prototype_iterator_);
    native_accessor_flags_ =
        GetNativeAccessorDescriptorInternal(receiver, raw_name());
  }
  calculated_native_accessor_flags_ = true;
}
References calculated_native_accessor_flags_, v8::internal::anonymous_namespace{debug-property-iterator.cc}::GetNativeAccessorDescriptorInternal(), kExoticIndices, native_accessor_flags_, prototype_iterator_, raw_name(), and stage_.
Referenced by has_native_getter(), has_native_setter(), and is_native_accessor().
Create()
std::unique_ptr< DebugPropertyIterator > v8::internal::DebugPropertyIterator::Create (Isolate * isolate, DirectHandle< JSReceiver > receiver, bool skip_indices) [static]
Definition at line 17 of file debug-property-iterator.cc.
                                                                            {
  // Can't use std::make_unique as Ctor is private.
  auto iterator = std::unique_ptr<DebugPropertyIterator>(
      new DebugPropertyIterator(isolate, receiver, skip_indices));
  if (IsJSProxy(*receiver)) {
    iterator->AdvanceToPrototype();
  }
  if (!iterator->FillKeysForCurrentPrototypeAndStage()) return nullptr;
  if (iterator->should_move_to_next_stage() && !iterator->AdvanceInternal()) {
    return nullptr;
  }
  return iterator;
}
References DebugPropertyIterator().
Referenced by v8::debug::PropertyIterator::Create().
descriptor()
v8::Maybe< v8::debug::PropertyDescriptor > v8::internal::DebugPropertyIterator::descriptor () [override], [virtual]
Implements v8::debug::PropertyIterator.
Definition at line 140 of file debug-property-iterator.cc.
                                                                     {
  DirectHandle<JSReceiver> receiver =
      PrototypeIterator::GetCurrent<JSReceiver>(prototype_iterator_);
  PropertyDescriptor descriptor;
  Maybe<bool> did_get_descriptor = JSReceiver::GetOwnPropertyDescriptor(
      isolate_, receiver, raw_name(), &descriptor);
  if (did_get_descriptor.IsNothing()) {
    return Nothing<v8::debug::PropertyDescriptor>();
  }
  if (!did_get_descriptor.FromJust()) {
    return Just(v8::debug::PropertyDescriptor{
        false, false, /* enumerable */
        false, false, /* configurable */
        false, false, /* writable */
        v8::Local<v8::Value>(), /* value */
        v8::Local<v8::Value>(), /* get */
        v8::Local<v8::Value>(), /* set */
    });
  }
  DCHECK(did_get_descriptor.FromJust());
  return Just(v8::debug::PropertyDescriptor{
      descriptor.enumerable(), descriptor.has_enumerable(),
      descriptor.configurable(), descriptor.has_configurable(),
      descriptor.writable(), descriptor.has_writable(),
      descriptor.has_value() ? Utils::ToLocal(descriptor.value())
                             : v8::Local<v8::Value>(),
      descriptor.has_get() ? Utils::ToLocal(descriptor.get())
                           : v8::Local<v8::Value>(),
      descriptor.has_set() ? Utils::ToLocal(descriptor.set())
                           : v8::Local<v8::Value>(),
  });
}
References v8::internal::DCHECK(), v8::Maybe< T >::FromJust(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::Maybe< T >::IsNothing(), isolate_, v8::Just(), prototype_iterator_, and raw_name().
Done()
bool v8::internal::DebugPropertyIterator::Done () const [override], [virtual]
Implements v8::debug::PropertyIterator.
Definition at line 46 of file debug-property-iterator.cc.
{ return is_done_; }
References is_done_.
Referenced by raw_name().
FillKeysForCurrentPrototypeAndStage()
bool v8::internal::DebugPropertyIterator::FillKeysForCurrentPrototypeAndStage () [private]
Definition at line 182 of file debug-property-iterator.cc.
                                                                {
  current_key_index_ = 0;
  current_keys_ = isolate_->factory()->empty_fixed_array();
  current_keys_length_ = 0;
  if (is_done_) return true;
  DirectHandle<JSReceiver> receiver =
      PrototypeIterator::GetCurrent<JSReceiver>(prototype_iterator_);
  if (stage_ == kExoticIndices) {
    if (skip_indices_ || !IsJSTypedArray(*receiver)) return true;
    auto typed_array = Cast<JSTypedArray>(receiver);
    current_keys_length_ =
        typed_array->WasDetached() ? 0 : typed_array->GetLength();
    return true;
  }
  PropertyFilter filter =
      stage_ == kEnumerableStrings ? ENUMERABLE_STRINGS : ALL_PROPERTIES;
  if (KeyAccumulator::GetKeys(isolate_, receiver, KeyCollectionMode::kOwnOnly,
                              filter, GetKeysConversion::kConvertToString,
                              false, skip_indices_ || IsJSTypedArray(*receiver))
          .ToHandle(&current_keys_)) {
    current_keys_length_ = current_keys_->length();
    return true;
  }
  return false;
}
References v8::internal::ALL_PROPERTIES, current_key_index_, current_keys_, current_keys_length_, v8::internal::ENUMERABLE_STRINGS, v8::internal::Isolate::factory(), v8::internal::KeyAccumulator::GetKeys(), is_done_, isolate_, v8::internal::kConvertToString, kEnumerableStrings, kExoticIndices, v8::internal::kOwnOnly, prototype_iterator_, skip_indices_, stage_, and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by AdvanceInternal().
has_native_getter()
bool v8::internal::DebugPropertyIterator::has_native_getter () [override], [virtual]
Implements v8::debug::PropertyIterator.
Definition at line 81 of file debug-property-iterator.cc.
                                              {
  CalculateNativeAccessorFlags();
  return native_accessor_flags_ &
         static_cast<int>(debug::NativeAccessorType::HasGetter);
}
References CalculateNativeAccessorFlags(), v8::debug::HasGetter, and native_accessor_flags_.
has_native_setter()
bool v8::internal::DebugPropertyIterator::has_native_setter () [override], [virtual]
Implements v8::debug::PropertyIterator.
Definition at line 87 of file debug-property-iterator.cc.
                                              {
  CalculateNativeAccessorFlags();
  return native_accessor_flags_ &
         static_cast<int>(debug::NativeAccessorType::HasSetter);
}
References CalculateNativeAccessorFlags(), v8::debug::HasSetter, and native_accessor_flags_.
is_array_index()
bool v8::internal::DebugPropertyIterator::is_array_index () [override], [virtual]
Implements v8::debug::PropertyIterator.
Definition at line 176 of file debug-property-iterator.cc.
                                           {
  if (stage_ == kExoticIndices) return true;
  PropertyKey key(isolate_, raw_name());
  return key.is_element();
}
References isolate_, kExoticIndices, v8::internal::key, raw_name(), and stage_.
is_native_accessor()
bool v8::internal::DebugPropertyIterator::is_native_accessor () [override], [virtual]
Implements v8::debug::PropertyIterator.
Definition at line 76 of file debug-property-iterator.cc.
                                               {
  CalculateNativeAccessorFlags();
  return native_accessor_flags_;
}
References CalculateNativeAccessorFlags(), and native_accessor_flags_.
is_own()
bool v8::internal::DebugPropertyIterator::is_own () [override], [virtual]
Implements v8::debug::PropertyIterator.
Definition at line 174 of file debug-property-iterator.cc.
{ return is_own_; }
References is_own_.
name()
v8::Local< v8::Name > v8::internal::DebugPropertyIterator::name () const [override], [virtual]
Implements v8::debug::PropertyIterator.
Definition at line 103 of file debug-property-iterator.cc.
                                                  {
  return Utils::ToLocal(raw_name());
}
References raw_name().
operator=()
DebugPropertyIterator& v8::internal::DebugPropertyIterator::operator= (const DebugPropertyIterator &) [delete]
raw_name()
DirectHandle< Name > v8::internal::DebugPropertyIterator::raw_name () const [private]
Definition at line 93 of file debug-property-iterator.cc.
                                                         {
  DCHECK(!Done());
  if (stage_ == kExoticIndices) {
    return isolate_->factory()->SizeToString(current_key_index_);
  } else {
    return Cast<Name>(direct_handle(
        current_keys_->get(static_cast<int>(current_key_index_)), isolate_));
  }
}
References current_key_index_, current_keys_, v8::internal::DCHECK(), v8::internal::direct_handle(), Done(), v8::internal::Isolate::factory(), isolate_, kExoticIndices, v8::internal::Factory::SizeToString(), and stage_.
Referenced by attributes(), CalculateNativeAccessorFlags(), descriptor(), is_array_index(), and name().
should_move_to_next_stage()
bool v8::internal::DebugPropertyIterator::should_move_to_next_stage () const [private]
Definition at line 208 of file debug-property-iterator.cc.
                                                            {
  return !is_done_ && current_key_index_ >= current_keys_length_;
}
References current_key_index_, current_keys_length_, and is_done_.
Referenced by AdvanceInternal().
Member Data Documentation
calculated_native_accessor_flags_
bool v8::internal::DebugPropertyIterator::calculated_native_accessor_flags_ = false [private]
Definition at line 69 of file debug-property-iterator.h.
Referenced by AdvanceInternal(), and CalculateNativeAccessorFlags().
current_key_index_
size_t v8::internal::DebugPropertyIterator::current_key_index_ [private]
Definition at line 65 of file debug-property-iterator.h.
Referenced by AdvanceInternal(), FillKeysForCurrentPrototypeAndStage(), raw_name(), and should_move_to_next_stage().
current_keys_
Handle<FixedArray> v8::internal::DebugPropertyIterator::current_keys_ [private]
Definition at line 66 of file debug-property-iterator.h.
Referenced by FillKeysForCurrentPrototypeAndStage(), and raw_name().
current_keys_length_
size_t v8::internal::DebugPropertyIterator::current_keys_length_ [private]
Definition at line 67 of file debug-property-iterator.h.
Referenced by FillKeysForCurrentPrototypeAndStage(), and should_move_to_next_stage().
is_done_
bool v8::internal::DebugPropertyIterator::is_done_ = false [private]
Definition at line 72 of file debug-property-iterator.h.
Referenced by AdvanceToPrototype(), Done(), FillKeysForCurrentPrototypeAndStage(), and should_move_to_next_stage().
is_own_
bool v8::internal::DebugPropertyIterator::is_own_ = true [private]
Definition at line 71 of file debug-property-iterator.h.
Referenced by AdvanceToPrototype(), and is_own().
isolate_
Isolate* v8::internal::DebugPropertyIterator::isolate_ [private]
Definition at line 56 of file debug-property-iterator.h.
Referenced by attributes(), descriptor(), FillKeysForCurrentPrototypeAndStage(), is_array_index(), and raw_name().
native_accessor_flags_
int v8::internal::DebugPropertyIterator::native_accessor_flags_ = 0 [private]
Definition at line 70 of file debug-property-iterator.h.
Referenced by CalculateNativeAccessorFlags(), has_native_getter(), has_native_setter(), and is_native_accessor().
prototype_iterator_
PrototypeIterator v8::internal::DebugPropertyIterator::prototype_iterator_ [private]
Definition at line 57 of file debug-property-iterator.h.
Referenced by AdvanceToPrototype(), attributes(), CalculateNativeAccessorFlags(), descriptor(), and FillKeysForCurrentPrototypeAndStage().
skip_indices_
bool v8::internal::DebugPropertyIterator::skip_indices_ [private]
Definition at line 63 of file debug-property-iterator.h.
Referenced by FillKeysForCurrentPrototypeAndStage().
enum { ... } v8::internal::DebugPropertyIterator::stage_ [private]
Referenced by AdvanceInternal(), AdvanceToPrototype(), CalculateNativeAccessorFlags(), FillKeysForCurrentPrototypeAndStage(), is_array_index(), and raw_name().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug-property-iterator.h
/mnt/V8SourceCode/src/debug/debug-interface.cc
/mnt/V8SourceCode/src/debug/debug-property-iterator.cc