v8::internal::InternalizedStringKey Class Reference
Public Member Functions
InternalizedStringKey (DirectHandle< String > string, uint32_t hash)
bool IsMatch (Isolate *isolate, Tagged< String > string)
void PrepareForInsertion (Isolate *isolate)
DirectHandle< String > GetHandleForInsertion (Isolate *isolate)
Private Attributes
DirectHandle< String > string_
MaybeDirectHandle< String > internalized_string_
MaybeDirectHandle< Map > maybe_internalized_map_
Additional Inherited Members
Detailed Description
Definition at line 181 of file string-table.cc.
Constructor & Destructor Documentation
InternalizedStringKey()
v8::internal::InternalizedStringKey::InternalizedStringKey (DirectHandle< String > string, uint32_t hash) [inline], [explicit]
Definition at line 183 of file string-table.cc.
      : StringTableKey(hash, string->length()), string_(string) {
    // When sharing the string table, it's possible that another thread already
    // internalized the key, in which case StringTable::LookupKey will perform a
    // redundant lookup and return the already internalized copy.
    DCHECK_IMPLIES(!v8_flags.shared_string_table,
                   !IsInternalizedString(*string));
    DCHECK(string->IsFlat());
    DCHECK(String::IsHashFieldComputed(hash));
  }
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::StringTableKey::hash(), v8::internal::Name::IsHashFieldComputed(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::string, and v8::internal::v8_flags.
Member Function Documentation
GetHandleForInsertion()
DirectHandle<String> v8::internal::InternalizedStringKey::GetHandleForInsertion (Isolate * isolate) [inline]
Definition at line 256 of file string-table.cc.
                                                               {
    DirectHandle<Map> internalized_map;
    // When preparing the string, the strategy was to in-place migrate it.
    if (maybe_internalized_map_.ToHandle(&internalized_map)) {
      // It is always safe to overwrite the map. The only transition possible
      // is another thread migrated the string to internalized already.
      // Migrations to thin are impossible, as we only call this method on table
      // misses inside the critical section.
      string_->set_map_safe_transition_no_write_barrier(isolate,
                                                        *internalized_map);
      DCHECK(IsInternalizedString(*string_));
      return string_;
    }
    // We prepared an internalized copy for the string or the string was already
    // internalized.
    // In theory we could have created a copy of a SeqString in young generation
    // that has been promoted to old space by now. In that case we could
    // in-place migrate the original string instead of internalizing the copy
    // and migrating the original string to a ThinString. This scenario doesn't
    // seem to be common enough to justify re-computing the strategy here.
    return internalized_string_.ToHandleChecked();
  }
References v8::internal::DCHECK(), internalized_string_, v8::internal::InstanceTypeChecker::IsInternalizedString(), maybe_internalized_map_, and string_.
IsMatch()
bool v8::internal::InternalizedStringKey::IsMatch (Isolate * isolate, Tagged< String > string) [inline]
Definition at line 194 of file string-table.cc.
                                                        {
    DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(string));
    return string_->SlowEquals(string);
  }
References v8::internal::DCHECK(), v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), and string_.
PrepareForInsertion()
void v8::internal::InternalizedStringKey::PrepareForInsertion (Isolate * isolate) [inline]
Definition at line 199 of file string-table.cc.
                                             {
    StringTransitionStrategy strategy =
        isolate->factory()->ComputeInternalizationStrategyForString(
            string_, &maybe_internalized_map_);
    switch (strategy) {
      case StringTransitionStrategy::kCopy:
        break;
      case StringTransitionStrategy::kInPlace:
        // In-place transition will be done in GetHandleForInsertion, when we
        // are sure that we are going to insert the string into the table.
        return;
      case StringTransitionStrategy::kAlreadyTransitioned:
        // We can see already internalized strings here only when sharing the
        // string table and allowing concurrent internalization.
        DCHECK(v8_flags.shared_string_table);
        internalized_string_ = string_;
        return;
    }
    // Copying the string here is always threadsafe, as no instance type
    // requiring a copy can transition any further.
    StringShape shape(*string_);
    // External strings get special treatment, to avoid copying their
    // contents as long as they are not uncached or the string table is shared.
    // If the string table is shared, another thread could lookup a string with
    // the same content before this thread completes MakeThin (which sets the
    // resource), resulting in a string table hit returning the string we just
    // created that is not correctly initialized.
    const bool can_move_resource =
        !v8_flags.shared_string_table && !shape.IsUncachedExternal();
    if (can_move_resource && shape.IsExternalOneByte()) {
      // Shared external strings are always in-place internalizable.
      // If this assumption is invalidated in the future, make sure that we
      // fully initialize (copy contents) for shared external strings, as the
      // original string is not transitioned to a ThinString (setting the
      // resource) immediately.
      DCHECK(!shape.IsShared());
      internalized_string_ =
          isolate->factory()->InternalizeExternalString<ExternalOneByteString>(
              string_);
    } else if (can_move_resource && shape.IsExternalTwoByte()) {
      // Shared external strings are always in-place internalizable.
      // If this assumption is invalidated in the future, make sure that we
      // fully initialize (copy contents) for shared external strings, as the
      // original string is not transitioned to a ThinString (setting the
      // resource) immediately.
      DCHECK(!shape.IsShared());
      internalized_string_ =
          isolate->factory()->InternalizeExternalString<ExternalTwoByteString>(
              string_);
    } else {
      // Otherwise allocate a new internalized string.
      internalized_string_ = isolate->factory()->NewInternalizedStringImpl(
          string_, length(), raw_hash_field());
    }
  }
References v8::internal::Factory::ComputeInternalizationStrategyForString(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), internalized_string_, v8::internal::Factory::InternalizeExternalString(), v8::internal::StringShape::IsExternalOneByte(), v8::internal::StringShape::IsExternalTwoByte(), v8::internal::StringShape::IsShared(), v8::internal::StringShape::IsUncachedExternal(), v8::internal::kAlreadyTransitioned, v8::internal::kCopy, v8::internal::kInPlace, v8::internal::StringTableKey::length(), maybe_internalized_map_, v8::internal::Factory::NewInternalizedStringImpl(), v8::internal::StringTableKey::raw_hash_field(), string_, and v8::internal::v8_flags.
Member Data Documentation
internalized_string_
MaybeDirectHandle<String> v8::internal::InternalizedStringKey::internalized_string_ [private]
Definition at line 286 of file string-table.cc.
Referenced by GetHandleForInsertion(), and PrepareForInsertion().
maybe_internalized_map_
MaybeDirectHandle<Map> v8::internal::InternalizedStringKey::maybe_internalized_map_ [private]
Definition at line 287 of file string-table.cc.
Referenced by GetHandleForInsertion(), and PrepareForInsertion().
string_
DirectHandle<String> v8::internal::InternalizedStringKey::string_ [private]
Definition at line 280 of file string-table.cc.
Referenced by GetHandleForInsertion(), IsMatch(), and PrepareForInsertion().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/string-table.cc