v8::internal::ProfilingScope Class Reference
#include <cpu-profiler.h>
Public Member Functions
ProfilingScope (Isolate *isolate, ProfilerListener *listener)
~ProfilingScope ()
Private Attributes
Isolate *const isolate_
ProfilerListener *const listener_
Detailed Description
Definition at line 155 of file cpu-profiler.h.
Constructor & Destructor Documentation
ProfilingScope()
v8::internal::ProfilingScope::ProfilingScope (Isolate * isolate, ProfilerListener * listener)
Definition at line 75 of file cpu-profiler.cc.
    : isolate_(isolate), listener_(listener) {
  size_t profiler_count = isolate_->num_cpu_profilers();
  profiler_count++;
  isolate_->set_num_cpu_profilers(profiler_count);
  isolate_->SetIsProfiling(true);
#if V8_ENABLE_WEBASSEMBLY
  wasm::GetWasmEngine()->EnableCodeLogging(isolate_);
#endif // V8_ENABLE_WEBASSEMBLY
  CHECK(isolate_->logger()->AddListener(listener_));
  V8FileLogger* file_logger = isolate_->v8_file_logger();
  // Populate the ProfilerCodeObserver with the initial functions and
  // callbacks on the heap.
  DCHECK(isolate_->heap()->HasBeenSetUp());
  if (!v8_flags.prof_browser_mode) {
    file_logger->LogCodeObjects();
  }
  file_logger->LogCompiledFunctions();
  file_logger->LogAccessorCallbacks();
}
References v8::internal::Logger::AddListener(), CHECK, v8::internal::DCHECK(), v8::internal::wasm::WasmEngine::EnableCodeLogging(), v8::internal::wasm::GetWasmEngine(), v8::internal::Heap::HasBeenSetUp(), v8::internal::Isolate::heap(), isolate_, listener_, v8::internal::V8FileLogger::LogAccessorCallbacks(), v8::internal::V8FileLogger::LogCodeObjects(), v8::internal::V8FileLogger::LogCompiledFunctions(), v8::internal::Isolate::logger(), v8::internal::Isolate::SetIsProfiling(), v8::internal::Isolate::v8_file_logger(), and v8::internal::v8_flags.
 ProfilingScope()
v8::internal::ProfilingScope::~ProfilingScope ()
Definition at line 98 of file cpu-profiler.cc.
                                {
  CHECK(isolate_->logger()->RemoveListener(listener_));
  size_t profiler_count = isolate_->num_cpu_profilers();
  DCHECK_GT(profiler_count, 0);
  profiler_count--;
  isolate_->set_num_cpu_profilers(profiler_count);
  if (profiler_count == 0) isolate_->SetIsProfiling(false);
}
References CHECK, DCHECK_GT, isolate_, listener_, v8::internal::Isolate::logger(), v8::internal::Logger::RemoveListener(), and v8::internal::Isolate::SetIsProfiling().
Member Data Documentation
isolate_
Isolate* const v8::internal::ProfilingScope::isolate_ [private]
Definition at line 161 of file cpu-profiler.h.
Referenced by ProfilingScope(), and ~ProfilingScope().
listener_
ProfilerListener* const v8::internal::ProfilingScope::listener_ [private]
Definition at line 162 of file cpu-profiler.h.
Referenced by ProfilingScope(), and ~ProfilingScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/cpu-profiler.h
/mnt/V8SourceCode/src/profiler/cpu-profiler.cc