v8::internal::CompilationCache Class Reference
#include <compilation-cache.h>
Public Member Functions
CompilationCache (const CompilationCache &)=delete
CompilationCache & operator= (const CompilationCache &)=delete
CompilationCacheScript::LookupResult LookupScript (Handle< String > source, const ScriptDetails &script_details, LanguageMode language_mode)
InfoCellPair LookupEval (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< Context > context, LanguageMode language_mode, int position)
void UpdateEval (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< JSFunction > js_function, LanguageMode language_mode, int position)
MaybeDirectHandle< RegExpData > LookupRegExp (DirectHandle< String > source, JSRegExp::Flags flags)
void PutScript (Handle< String > source, LanguageMode language_mode, DirectHandle< SharedFunctionInfo > function_info)
void PutEval (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< JSFunction > js_function, int position)
void PutRegExp (DirectHandle< String > source, JSRegExp::Flags flags, DirectHandle< RegExpData > data)
void Clear ()
void Remove (DirectHandle< SharedFunctionInfo > function_info)
void Iterate (RootVisitor *v)
void MarkCompactPrologue ()
void EnableScriptAndEval ()
void DisableScriptAndEval ()
Private Member Functions
CompilationCache (Isolate *isolate)
~CompilationCache ()=default
base::HashMap * EagerOptimizingSet ()
bool IsEnabledScriptAndEval () const
bool IsEnabledScript (LanguageMode language_mode)
Isolate * isolate () const
Private Attributes
Isolate * isolate_
CompilationCacheScript script_
CompilationCacheEval eval_global_
CompilationCacheEval eval_contextual_
CompilationCacheRegExp reg_exp_
bool enabled_script_and_eval_
Friends
class Isolate
Detailed Description
Definition at line 145 of file compilation-cache.h.
Constructor & Destructor Documentation
CompilationCache() [1/2]
v8::internal::CompilationCache::CompilationCache (const CompilationCache &) [delete]
CompilationCache() [2/2]
v8::internal::CompilationCache::CompilationCache (Isolate * isolate) [explicit], [private]
Definition at line 24 of file compilation-cache.cc.
    : isolate_(isolate),
      script_(isolate),
      eval_global_(isolate),
      eval_contextual_(isolate),
      reg_exp_(isolate),
      enabled_script_and_eval_(true) {}
 CompilationCache()
v8::internal::CompilationCache::~CompilationCache () [private], [default]
Member Function Documentation
Clear()
void v8::internal::CompilationCache::Clear ()
Definition at line 331 of file compilation-cache.cc.
                             {
  script_.Clear();
  eval_global_.Clear();
  eval_contextual_.Clear();
  reg_exp_.Clear();
}
References v8::internal::CompilationCacheEvalOrScript::Clear(), v8::internal::CompilationCacheRegExp::Clear(), eval_contextual_, eval_global_, reg_exp_, and script_.
Referenced by v8::Isolate::ClearCachesForTesting(), v8::internal::Heap::CreateInitialMutableObjects(), DisableScriptAndEval(), and v8::internal::anonymous_namespace{heap.cc}::FreeCachesOnMemoryPressure().
DisableScriptAndEval()
void v8::internal::CompilationCache::DisableScriptAndEval ()
Definition at line 359 of file compilation-cache.cc.
                                            {
  enabled_script_and_eval_ = false;
  Clear();
}
References Clear(), and enabled_script_and_eval_.
Referenced by v8::internal::Debug::UpdateState().
EagerOptimizingSet()
base::HashMap* v8::internal::CompilationCache::EagerOptimizingSet () [private]
EnableScriptAndEval()
void v8::internal::CompilationCache::EnableScriptAndEval ()
Definition at line 355 of file compilation-cache.cc.
                                           {
  enabled_script_and_eval_ = true;
}
References enabled_script_and_eval_.
Referenced by v8::internal::Debug::UpdateState().
IsEnabledScript()
bool v8::internal::CompilationCache::IsEnabledScript (LanguageMode language_mode) [inline], [private]
Definition at line 224 of file compilation-cache.h.
                                                   {
    // Tests can change v8_flags.use_strict at runtime. The compilation cache
    // only contains scripts which were compiled with the default language mode.
    return IsEnabledScriptAndEval() && language_mode == LanguageMode::kSloppy;
  }
References v8::internal::kSloppy.
Referenced by LookupScript(), and PutScript().
IsEnabledScriptAndEval()
bool v8::internal::CompilationCache::IsEnabledScriptAndEval () const [inline], [private]
Definition at line 221 of file compilation-cache.h.
                                      {
    return v8_flags.compilation_cache && enabled_script_and_eval_;
  }
References v8::internal::v8_flags.
Referenced by LookupEval(), PutEval(), and Remove().
isolate()
Isolate* v8::internal::CompilationCache::isolate () const [inline], [private]
Definition at line 230 of file compilation-cache.h.
{ return isolate_; }
Referenced by LookupEval(), PutEval(), and PutScript().
Iterate()
void v8::internal::CompilationCache::Iterate (RootVisitor * v)
Definition at line 338 of file compilation-cache.cc.
                                             {
  script_.Iterate(v);
  eval_global_.Iterate(v);
  eval_contextual_.Iterate(v);
  reg_exp_.Iterate(v);
}
References eval_contextual_, eval_global_, v8::internal::CompilationCacheEvalOrScript::Iterate(), v8::internal::CompilationCacheRegExp::Iterate(), reg_exp_, and script_.
Referenced by v8::internal::Heap::IterateRoots().
LookupEval()
InfoCellPair v8::internal::CompilationCache::LookupEval (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< Context > context, LanguageMode language_mode, int position)
Definition at line 262 of file compilation-cache.cc.
                                                                             {
  InfoCellPair result;
  if (!IsEnabledScriptAndEval()) return result;
  const char* cache_type;
  DirectHandle<NativeContext> maybe_native_context;
  if (TryCast<NativeContext>(context, &maybe_native_context)) {
    result = eval_global_.Lookup(source, outer_info, maybe_native_context,
                                 language_mode, position);
    cache_type = "eval-global";
  } else {
    DCHECK_NE(position, kNoSourcePosition);
    DirectHandle<NativeContext> native_context(context->native_context(),
                                               isolate());
    result = eval_contextual_.Lookup(source, outer_info, native_context,
                                     language_mode, position);
    cache_type = "eval-contextual";
  }
  if (result.has_shared()) {
    LOG(isolate(), CompilationCacheEvent("hit", cache_type, result.shared()));
  }
  return result;
}
References DCHECK_NE, eval_contextual_, eval_global_, IsEnabledScriptAndEval(), isolate(), v8::internal::kNoSourcePosition, LOG, v8::internal::CompilationCacheEval::Lookup(), v8::internal::native_context, and v8::base::internal::result.
Referenced by v8::internal::Compiler::GetFunctionFromEval().
LookupRegExp()
MaybeDirectHandle< RegExpData > v8::internal::CompilationCache::LookupRegExp (DirectHandle< String > source, JSRegExp::Flags flags)
Definition at line 292 of file compilation-cache.cc.
                                                      {
  return reg_exp_.Lookup(source, flags);
}
References v8::internal::flags, v8::internal::CompilationCacheRegExp::Lookup(), and reg_exp_.
Referenced by v8::internal::RegExp::Compile().
LookupScript()
CompilationCacheScript::LookupResult v8::internal::CompilationCache::LookupScript (Handle< String > source, const ScriptDetails & script_details, LanguageMode language_mode)
Definition at line 241 of file compilation-cache.cc.
                                {
  if (!IsEnabledScript(language_mode)) return {};
  return script_.Lookup(source, script_details);
}
References IsEnabledScript(), v8::internal::CompilationCacheScript::Lookup(), and script_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript(), v8::internal::Compiler::GetWrappedFunction(), and v8::internal::BackgroundMergeTask::SetUpOnMainThread().
MarkCompactPrologue()
void v8::internal::CompilationCache::MarkCompactPrologue ()
Definition at line 345 of file compilation-cache.cc.
                                           {
  // Drop SFI entries with flushed bytecode.
  script_.Age();
  eval_global_.Age();
  eval_contextual_.Age();
  // Drop entries in oldest generation.
  reg_exp_.Age();
}
References v8::internal::CompilationCacheScript::Age(), v8::internal::CompilationCacheEval::Age(), v8::internal::CompilationCacheRegExp::Age(), eval_contextual_, eval_global_, reg_exp_, and script_.
Referenced by v8::internal::MarkCompactCollector::StartMarking().
operator=()
CompilationCache& v8::internal::CompilationCache::operator= (const CompilationCache &) [delete]
PutEval()
void v8::internal::CompilationCache::PutEval (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< JSFunction > js_function, int position)
Definition at line 306 of file compilation-cache.cc.
                                             {
  if (!IsEnabledScriptAndEval()) return;
  const char* cache_type;
  if (IsNativeContext(js_function->context())) {
    eval_global_.Put(source, outer_info, js_function, position);
    cache_type = "eval-global";
  } else {
    DCHECK_NE(position, kNoSourcePosition);
    eval_contextual_.Put(source, outer_info, js_function, position);
    cache_type = "eval-contextual";
  }
  LOG(isolate(),
      CompilationCacheEvent("put", cache_type, js_function->shared()));
}
References DCHECK_NE, eval_contextual_, eval_global_, IsEnabledScriptAndEval(), isolate(), v8::internal::kNoSourcePosition, LOG, and v8::internal::CompilationCacheEval::Put().
Referenced by v8::internal::Compiler::GetFunctionFromEval().
PutRegExp()
void v8::internal::CompilationCache::PutRegExp (DirectHandle< String > source, JSRegExp::Flags flags, DirectHandle< RegExpData > data)
Definition at line 325 of file compilation-cache.cc.
                                                                {
  reg_exp_.Put(source, flags, data);
}
References v8::internal::flags, v8::internal::CompilationCacheRegExp::Put(), and reg_exp_.
Referenced by v8::internal::RegExp::Compile().
PutScript()
void v8::internal::CompilationCache::PutScript (Handle< String > source, LanguageMode language_mode, DirectHandle< SharedFunctionInfo > function_info)
Definition at line 297 of file compilation-cache.cc.
                                                    {
  if (!IsEnabledScript(language_mode)) return;
  LOG(isolate(), CompilationCacheEvent("put", "script", *function_info));
  script_.Put(source, function_info);
}
References IsEnabledScript(), isolate(), LOG, v8::internal::CompilationCacheScript::Put(), and script_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), v8::internal::Compiler::GetSharedFunctionInfoForStreamedScript(), and v8::internal::Compiler::GetWrappedFunction().
Remove()
void v8::internal::CompilationCache::Remove (DirectHandle< SharedFunctionInfo > function_info)
Definition at line 233 of file compilation-cache.cc.
                                                                            {
  if (!IsEnabledScriptAndEval()) return;
  eval_global_.Remove(function_info);
  eval_contextual_.Remove(function_info);
  script_.Remove(function_info);
}
References eval_contextual_, eval_global_, IsEnabledScriptAndEval(), v8::internal::CompilationCacheEvalOrScript::Remove(), and script_.
Referenced by v8::internal::LiveEdit::PatchScript().
UpdateEval()
void v8::internal::CompilationCache::UpdateEval (DirectHandle< String > source, DirectHandle< SharedFunctionInfo > outer_info, DirectHandle< JSFunction > js_function, LanguageMode language_mode, int position)
Definition at line 248 of file compilation-cache.cc.
                                                                            {
  if (IsNativeContext(js_function->context())) {
    eval_global_.UpdateEval(source, outer_info, js_function, language_mode,
                            position);
  } else {
    DCHECK_NE(position, kNoSourcePosition);
    eval_contextual_.UpdateEval(source, outer_info, js_function, language_mode,
                                position);
  }
}
References DCHECK_NE, eval_contextual_, eval_global_, v8::internal::kNoSourcePosition, and v8::internal::CompilationCacheEval::UpdateEval().
Referenced by v8::internal::Compiler::GetFunctionFromEval().
Friends And Related Function Documentation
Isolate
friend class Isolate [friend]
Definition at line 242 of file compilation-cache.h.
Member Data Documentation
enabled_script_and_eval_
bool v8::internal::CompilationCache::enabled_script_and_eval_ [private]
Definition at line 240 of file compilation-cache.h.
Referenced by DisableScriptAndEval(), and EnableScriptAndEval().
eval_contextual_
CompilationCacheEval v8::internal::CompilationCache::eval_contextual_ [private]
Definition at line 236 of file compilation-cache.h.
Referenced by Clear(), Iterate(), LookupEval(), MarkCompactPrologue(), PutEval(), Remove(), and UpdateEval().
eval_global_
CompilationCacheEval v8::internal::CompilationCache::eval_global_ [private]
Definition at line 235 of file compilation-cache.h.
Referenced by Clear(), Iterate(), LookupEval(), MarkCompactPrologue(), PutEval(), Remove(), and UpdateEval().
isolate_
Isolate* v8::internal::CompilationCache::isolate_ [private]
Definition at line 232 of file compilation-cache.h.
reg_exp_
CompilationCacheRegExp v8::internal::CompilationCache::reg_exp_ [private]
Definition at line 237 of file compilation-cache.h.
Referenced by Clear(), Iterate(), LookupRegExp(), MarkCompactPrologue(), and PutRegExp().
script_
CompilationCacheScript v8::internal::CompilationCache::script_ [private]
Definition at line 234 of file compilation-cache.h.
Referenced by Clear(), Iterate(), LookupScript(), MarkCompactPrologue(), PutScript(), and Remove().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/compilation-cache.h
/mnt/V8SourceCode/src/codegen/compilation-cache.cc