v8::internal::compiler::JSCallAccessor Class Reference
Public Member Functions
JSCallAccessor (Node *call)
Node * target () const
Node * receiver () const
Node * new_target () const
FrameState frame_state () const
int argument_count () const
CallFrequency const & frequency () const
Private Attributes
Node * call_
Detailed Description
Definition at line 50 of file js-inlining.cc.
Constructor & Destructor Documentation
JSCallAccessor()
v8::internal::compiler::JSCallAccessor::JSCallAccessor (Node * call) [inline], [explicit]
Definition at line 52 of file js-inlining.cc.
                                      : call_(call) {
    DCHECK(call->opcode() == IrOpcode::kJSCall ||
           call->opcode() == IrOpcode::kJSConstruct);
  }
References v8::internal::DCHECK(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
argument_count()
int v8::internal::compiler::JSCallAccessor::argument_count () const [inline]
Definition at line 69 of file js-inlining.cc.
                             {
    return (call_->opcode() == IrOpcode::kJSCall)
               ? JSCallNode{call_}.ArgumentCount()
               : JSConstructNode{call_}.ArgumentCount();
  }
References call_, and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::JSInliner::ReduceJSCall().
frame_state()
FrameState v8::internal::compiler::JSCallAccessor::frame_state () const [inline]
Definition at line 65 of file js-inlining.cc.
                                 {
    return FrameState{NodeProperties::GetFrameStateInput(call_)};
  }
References call_, and v8::internal::compiler::NodeProperties::GetFrameStateInput().
Referenced by v8::internal::compiler::JSInliner::ReduceJSCall().
frequency()
CallFrequency const& v8::internal::compiler::JSCallAccessor::frequency () const [inline]
Definition at line 75 of file js-inlining.cc.
                                         {
    return (call_->opcode() == IrOpcode::kJSCall)
               ? JSCallNode{call_}.Parameters().frequency()
               : JSConstructNode{call_}.Parameters().frequency();
  }
References call_, and v8::internal::compiler::Node::opcode().
Referenced by v8::internal::compiler::JSInliner::ReduceJSCall().
new_target()
Node* v8::internal::compiler::JSCallAccessor::new_target () const [inline]
Definition at line 63 of file js-inlining.cc.
{ return JSConstructNode{call_}.new_target(); }
References call_.
receiver()
Node* v8::internal::compiler::JSCallAccessor::receiver () const [inline]
Definition at line 61 of file js-inlining.cc.
{ return JSCallNode{call_}.receiver(); }
References call_.
Referenced by v8::internal::compiler::JSInliner::ReduceJSCall().
target()
Node* v8::internal::compiler::JSCallAccessor::target () const [inline]
Definition at line 57 of file js-inlining.cc.
                       {
    return call_->InputAt(JSCallOrConstructNode::TargetIndex());
  }
References call_, and v8::internal::compiler::Node::InputAt().
Referenced by v8::internal::compiler::JSInliner::ReduceJSCall().
Member Data Documentation
call_
Node* v8::internal::compiler::JSCallAccessor::call_ [private]
Definition at line 82 of file js-inlining.cc.
Referenced by argument_count(), frame_state(), frequency(), new_target(), receiver(), and target().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-inlining.cc