v8::internal::MarkingStateBase< ConcreteState, access_mode > Class Template Reference
#include <marking-state.h>
Public Member Functions
MarkingStateBase (PtrComprCageBase cage_base)
PtrComprCageBase cage_base () const
bool TryMark (Tagged< HeapObject > obj)
bool TryMarkAndAccountLiveBytes (Tagged< HeapObject > obj)
bool TryMarkAndAccountLiveBytes (Tagged< HeapObject > obj, int object_size)
bool IsMarked (const Tagged< HeapObject > obj) const
bool IsUnmarked (const Tagged< HeapObject > obj) const
Detailed Description
template<typename ConcreteState, AccessMode access_mode>
class v8::internal::MarkingStateBase< ConcreteState, access_mode >
Definition at line 19 of file marking-state.h.
Constructor & Destructor Documentation
MarkingStateBase()
template<typename ConcreteState , AccessMode access_mode>
v8::internal::MarkingStateBase< ConcreteState, access_mode >::MarkingStateBase (PtrComprCageBase cage_base) [inline], [explicit]
Definition at line 21 of file marking-state.h.
      : cage_base_(cage_base)
#endif
  {
  }
Member Function Documentation
cage_base()
template<typename ConcreteState , AccessMode access_mode>
PtrComprCageBase v8::internal::MarkingStateBase< ConcreteState, access_mode >::cage_base () const [inline]
Definition at line 30 of file marking-state.h.
                                               {
#if V8_COMPRESS_POINTERS
    return cage_base_;
#else
    return PtrComprCageBase{};
#endif // V8_COMPRESS_POINTERS
  }
IsMarked()
template<typename ConcreteState , AccessMode access_mode>
bool v8::internal::MarkingStateBase< ConcreteState, access_mode >::IsMarked (const Tagged< HeapObject > obj) const [inline]
Definition at line 18 of file marking-state-inl.h.
                                        {
  return MarkBit::From(obj).template Get<access_mode>();
}
References v8::internal::MarkBit::From().
Referenced by v8::internal::HeapAllocator::AllocateRaw(), v8::internal::Sweeper::RawSweep(), and v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace().
IsUnmarked()
template<typename ConcreteState , AccessMode access_mode>
bool v8::internal::MarkingStateBase< ConcreteState, access_mode >::IsUnmarked (const Tagged< HeapObject > obj) const [inline]
Definition at line 24 of file marking-state-inl.h.
                                        {
  return !IsMarked(obj);
}
Referenced by v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences(), and v8::internal::MinorMarkSweepCollector::DrainMarkingWorklist().
TryMark()
template<typename ConcreteState , AccessMode access_mode>
bool v8::internal::MarkingStateBase< ConcreteState, access_mode >::TryMark (Tagged< HeapObject > obj) [inline]
Definition at line 30 of file marking-state-inl.h.
                            {
  return MarkBit::From(obj).template Set<access_mode>();
}
References v8::internal::MarkBit::From().
Referenced by v8::internal::MarkingBarrier::MarkValueShared(), v8::internal::MarkingHelper::TryMarkAndPush(), and v8::internal::MarkingBarrier::Write().
TryMarkAndAccountLiveBytes() [1/2]
template<typename ConcreteState , AccessMode access_mode>
bool v8::internal::MarkingStateBase< ConcreteState, access_mode >::TryMarkAndAccountLiveBytes (Tagged< HeapObject > obj) [inline]
Definition at line 36 of file marking-state-inl.h.
                            {
  if (TryMark(obj)) {
    MutablePageMetadata::FromHeapObject(obj)->IncrementLiveBytesAtomically(
        ALIGN_TO_ALLOCATION_ALIGNMENT(obj->Size(cage_base())));
    return true;
  }
  return false;
}
Referenced by v8::internal::OldLargeObjectSpace::AllocateRaw(), and v8::internal::MarkCompactWeakObjectRetainer::RetainAs().
TryMarkAndAccountLiveBytes() [2/2]
template<typename ConcreteState , AccessMode access_mode>
bool v8::internal::MarkingStateBase< ConcreteState, access_mode >::TryMarkAndAccountLiveBytes (Tagged< HeapObject > obj, int object_size) [inline]
Definition at line 47 of file marking-state-inl.h.
                                             {
  if (TryMark(obj)) {
    MutablePageMetadata::FromHeapObject(obj)->IncrementLiveBytesAtomically(
        object_size);
    return true;
  }
  return false;
}
References v8::internal::MutablePageMetadata::FromHeapObject(), and v8::internal::MutablePageMetadata::IncrementLiveBytesAtomically().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/marking-state.h
/mnt/V8SourceCode/src/heap/marking-state-inl.h