v8::WasmMemoryMapDescriptor Class Reference
The V8 interface for a WebAssembly memory map descriptor.
#include <v8-wasm.h>
Public Types
using WasmFileDescriptor = int32_t
Public Member Functions
WasmMemoryMapDescriptor ()=delete
Static Public Member Functions
static WasmMemoryMapDescriptor * Cast (Value *value)
static Local< WasmMemoryMapDescriptor > New (Isolate *isolate, WasmFileDescriptor fd)
Static Private Member Functions
static void CheckCast (Value *object)
Additional Inherited Members
Detailed Description
The V8 interface for a WebAssembly memory map descriptor.
This is an experimental feature that may change and be removed without further communication.
Definition at line 207 of file v8-wasm.h.
Member Typedef Documentation
WasmFileDescriptor
using v8::WasmMemoryMapDescriptor::WasmFileDescriptor = int32_t
Definition at line 218 of file v8-wasm.h.
Constructor & Destructor Documentation
WasmMemoryMapDescriptor()
v8::WasmMemoryMapDescriptor::WasmMemoryMapDescriptor () [delete]
Member Function Documentation
Cast()
static WasmMemoryMapDescriptor* v8::WasmMemoryMapDescriptor::Cast (Value * value) [inline], [static]
Definition at line 211 of file v8-wasm.h.
                                                               {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<WasmMemoryMapDescriptor*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::WasmMemoryMapDescriptor::CheckCast (Value * object) [static], [private]
Definition at line 3996 of file api.cc.
                                                     {
  Utils::ApiCheck(that->IsWasmMemoryMapDescriptor(),
                  "v8::WasmMemoryMapDescriptor::Cast",
                  "Value is not a WasmMemoryMapDescriptor");
}
References v8::Utils::ApiCheck(), and v8::Value::IsWasmMemoryMapDescriptor().
New()
Local< WasmMemoryMapDescriptor > v8::WasmMemoryMapDescriptor::New (v8::Isolate * v8_isolate, WasmMemoryMapDescriptor::WasmFileDescriptor fd) [static]
Definition at line 8873 of file api.cc.
                                                                         {
#if V8_ENABLE_WEBASSEMBLY
  CHECK(i::v8_flags.experimental_wasm_memory_control);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::DirectHandle<i::WasmMemoryMapDescriptor> result =
      i::WasmMemoryMapDescriptor::NewFromFileDescriptor(i_isolate, fd);
  return Utils::ToLocal(result);
#else
  Utils::ApiCheck(false, "WasmMemoryMapDescriptor::New",
                  "WebAssembly support is not enabled");
  UNREACHABLE();
#endif
}
References v8::Utils::ApiCheck(), CHECK, v8::internal::WasmMemoryMapDescriptor::NewFromFileDescriptor(), v8::base::internal::result, UNREACHABLE, and v8::internal::v8_flags.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-wasm.h
/mnt/V8SourceCode/src/api/api.cc