v8::internal::compiler::StringBuilderOptimizer Class Reference
#include <string-builder-optimizer.h>
Classes
struct Status
struct StringBuilder
Public Member Functions
StringBuilderOptimizer (JSGraph *jsgraph, Schedule *schedule, Zone *temp_zone, JSHeapBroker *broker)
bool BlockShouldFinalizeStringBuilders (BasicBlock *block)
ZoneVector< Node * > GetStringBuildersToFinalize (BasicBlock *block)
bool IsStringBuilderEnd (Node *node)
bool IsNonLoopPhiStringBuilderEnd (Node *node)
bool IsStringBuilderConcatInput (Node *node)
bool ConcatIsInStringBuilder (Node *node)
bool IsFirstConcatInStringBuilder (Node *node)
OneOrTwoByteAnalysis::State GetOneOrTwoByte (Node *node)
void Run ()
JSGraph * jsgraph () const
TFGraph * graph () const
Schedule * schedule () const
Zone * temp_zone () const
JSHeapBroker * broker () const
Private Types
enum class State : uint8_t {
kUnvisited = 0
, kBeginStringBuilder
, kInStringBuilder
, kPendingPhi
,
kConfirmedInStringBuilder
, kEndStringBuilder
, kEndStringBuilderLoopPhi
, kInvalid
,
kNumberOfState
 }
Private Member Functions
Status GetStatus (Node *node) const
void SetStatus (Node *node, State state, int id=kInvalidId)
void UpdateStatus (Node *node, State state)
bool IsLoopPhi (Node *node) const
bool LoopContains (Node *loop_phi, Node *node)
int GetStringBuilderIdForConcat (Node *node)
void ReplaceConcatInputIfNeeded (Node *node, int input_idx)
bool CheckNodeUses (Node *node, Node *concat_child, Status status)
bool CheckPreviousNodeUses (Node *child, Status status, int input_if_loop_phi=0)
int GetPhiPredecessorsCommonId (Node *node)
void FinalizeStringBuilders ()
void VisitNode (Node *node, BasicBlock *block)
void VisitGraph ()
Private Attributes
const StringBuilder kInvalidStringBuilder
JSGraph * jsgraph_
Schedule * schedule_
Zone * temp_zone_
JSHeapBroker * broker_
unsigned int string_builder_count_ = 0
ZoneVector< std::optional< ZoneVector< Node * > > > blocks_to_trimmings_map_
ZoneVector< Status > status_
ZoneVector< StringBuilder > string_builders_
ZoneVector< BasicBlock * > loop_headers_
Static Private Attributes
static constexpr int kInvalidId = -1
static constexpr bool kAllowAnyStringOnTheRhs = false
Detailed Description
Definition at line 214 of file string-builder-optimizer.h.
Member Enumeration Documentation
State
enum v8::internal::compiler::StringBuilderOptimizer::State : uint8_t [strong], [private]
Enumerator
kUnvisited
kBeginStringBuilder
kInStringBuilder
kPendingPhi
kConfirmedInStringBuilder
kEndStringBuilder
kEndStringBuilderLoopPhi
kInvalid
kNumberOfState
Definition at line 268 of file string-builder-optimizer.h.
                   : uint8_t {
    kUnvisited = 0,
    kBeginStringBuilder, // A (potential) beginning of a StringBuilder
    kInStringBuilder, // A node that could be in a StringBuilder
    kPendingPhi, // A phi that could be in a StringBuilder
    kConfirmedInStringBuilder, // A node that is definitely in a StringBuilder
    kEndStringBuilder, // A node that ends definitely a StringBuilder, and that
                        // can be trimmed right away
    kEndStringBuilderLoopPhi, // A phi that ends a StringBuilder, and whose
                               // trimming need to be done at the beginning of
                               // the following blocks.
    kInvalid, // A node that we visited and that we can't optimize.
    kNumberOfState
  };
Constructor & Destructor Documentation
StringBuilderOptimizer()
v8::internal::compiler::StringBuilderOptimizer::StringBuilderOptimizer (JSGraph * jsgraph, Schedule * schedule, Zone * temp_zone, JSHeapBroker * broker)
Definition at line 1178 of file string-builder-optimizer.cc.
    : jsgraph_(jsgraph),
      schedule_(schedule),
      temp_zone_(temp_zone),
      broker_(broker),
      blocks_to_trimmings_map_(schedule->BasicBlockCount(), temp_zone),
      status_(jsgraph->graph()->NodeCount(),
              Status{kInvalidId, State::kUnvisited}, temp_zone),
      string_builders_(temp_zone),
      loop_headers_(temp_zone) {}
Member Function Documentation
BlockShouldFinalizeStringBuilders()
bool v8::internal::compiler::StringBuilderOptimizer::BlockShouldFinalizeStringBuilders (BasicBlock * block)
Definition at line 317 of file string-builder-optimizer.cc.
                       {
  DCHECK_LT(block->id().ToInt(), blocks_to_trimmings_map_.size());
  return blocks_to_trimmings_map_[block->id().ToInt()].has_value();
}
References blocks_to_trimmings_map_, DCHECK_LT, v8::internal::compiler::BasicBlock::id(), and v8::internal::compiler::BasicBlock::Id::ToInt().
Referenced by GetStringBuildersToFinalize().
broker()
JSHeapBroker* v8::internal::compiler::StringBuilderOptimizer::broker () const [inline]
Definition at line 265 of file string-builder-optimizer.h.
{ return broker_; }
Referenced by FinalizeStringBuilders(), ReplaceConcatInputIfNeeded(), and VisitNode().
CheckNodeUses()
bool v8::internal::compiler::StringBuilderOptimizer::CheckNodeUses (Node * node, Node * concat_child, Status status) [private]
Definition at line 638 of file string-builder-optimizer.cc.
                                                          {
  DCHECK(GetStatus(string_builder_child).state == State::kInStringBuilder ||
         GetStatus(string_builder_child).state == State::kPendingPhi);
  BasicBlock* child_block = schedule()->block(string_builder_child);
  if (node->UseCount() == 1) return true;
  BasicBlock* node_block = schedule()->block(node);
  bool is_loop_phi = IsLoopPhi(node);
  bool child_is_in_loop =
      is_loop_phi && LoopContains(node, string_builder_child);
  base::SmallVector<BasicBlock*, kMaxPredecessors> current_predecessors;
  bool predecessors_computed = false;
  for (Node* other_child : node->uses()) {
    if (other_child == string_builder_child) continue;
    BasicBlock* other_child_block = schedule()->block(other_child);
    if (!OpcodeIsAllowed(other_child->opcode())) {
      // {other_child} could write {node} (the beginning of the string builder)
      // in memory (or keep it alive through other means, such as a Phi). This
      // means that if {string_builder_child} modifies the string builder, then
      // the value stored by {other_child} will become out-dated (since
      // {other_child} will probably just write a pointer to the string in
      // memory, and the string pointed by this pointer will be updated by the
      // string builder).
      if (is_loop_phi && child_is_in_loop &&
          !node_block->LoopContains(other_child_block)) {
        // {other_child} keeps the string alive, but this is only after the
        // loop, when {string_builder_child} isn't alive anymore, so this isn't
        // an issue.
        continue;
      }
      return false;
    }
    if (other_child_block == child_block) {
      // Both {child} and {other_child} are in the same block, we need to make
      // sure that {other_child} comes first.
      Status other_status = GetStatus(other_child);
      if (other_status.id != kInvalidId) {
        DCHECK_EQ(other_status.id, status.id);
        // {node} flows into 2 different nodes of the string builder, both of
        // which are in the same BasicBlock, which is not supported. We need to
        // invalidate {other_child} as well, or the input of {child} could be
        // wrong. In theory, we could keep one of {other_child} and {child} (the
        // one that comes the later in the BasicBlock), but it's simpler to keep
        // neither, and end the string builder on {node}.
        SetStatus(other_child, State::kInvalid);
        return false;
      }
      if (!ComesBeforeInBlock(other_child, string_builder_child, child_block)) {
        return false;
      }
      continue;
    }
    if (is_loop_phi) {
      if ((child_is_in_loop && !node_block->LoopContains(other_child_block)) ||
          (!child_is_in_loop && node_block->LoopContains(other_child_block))) {
        // {child} is in the loop and {other_child} isn't (or the other way
        // around). In that case, we skip {other_child}: it will be tested
        // later when we leave the loop (if {child} is in the loop) or has
        // been tested earlier while we were inside the loop (if {child} isn't
        // in the loop).
        continue;
      }
    } else if (!ValidControlFlowForStringBuilder(child_block, other_child_block,
                                                 node_block, loop_headers_)) {
      return false;
    }
    if (IsPhiContainingGivenInputs(other_child, node, string_builder_child,
                                   schedule())) {
      // {other_child} is a Phi that merges {child} and {node} (and maybe some
      // other nodes that we don't care about for now: if {other_child} merges
      // more than 2 nodes, it won't be added to the string builder anyways).
      continue;
    }
    base::SmallVector<BasicBlock*, kMaxPredecessors> other_predecessors;
    bool all_other_predecessors_computed =
        ComputePredecessors(other_child_block, node_block, &other_predecessors);
    // Making sure that {child_block} isn't in the predecessors of
    // {other_child_block}. Otherwise, the use of {node} in {other_child}
    // would be invalid.
    if (std::find(other_predecessors.begin(), other_predecessors.end(),
                  child_block) != other_predecessors.end()) {
      // {child} is in the predecessor of {other_child}, which is definitely
      // invalid (because it means that {other_child} uses an out-dated version
      // of {node}, since {child} modified it).
      return false;
    } else {
      if (all_other_predecessors_computed) {
        // {child} is definitely not in the predecessors of {other_child}, which
        // means that it's either a successor of {other_child} (which is safe),
        // or it's in another path of the graph alltogether (which is also
        // safe).
        continue;
      } else {
        // We didn't compute all the predecessors of {other_child}, so it's
        // possible that {child_block} is one of the predecessor that we didn't
        // compute.
        //
        // Trying to see if we can find {other_child_block} in the
        // predecessors of {child_block}: that would mean that {other_child}
        // is guaranteed to be scheduled before {child}, making it safe.
        if (!predecessors_computed) {
          ComputePredecessors(child_block, node_block, &current_predecessors);
          predecessors_computed = true;
        }
        if (std::find(current_predecessors.begin(), current_predecessors.end(),
                      other_child_block) == current_predecessors.end()) {
          // We didn't find {other_child} in the predecessors of {child}. It
          // means that either {other_child} comes after in the graph (which
          // is unsafe), or that {other_child} and {child} are on two
          // independent subgraphs (which is safe). We have no efficient way
          // to know which one of the two this is, so, we fall back to a
          // stricter approach: the use of {node} in {other_child} is
          // guaranteed to be safe if {other_child_block} dominates
          // {child_block}.
          if (!IsClosebyDominator(other_child_block, child_block)) {
            return false;
          }
        }
      }
    }
  }
  return true;
}
References v8::base::SmallVector< T, kSize, Allocator >::begin(), v8::internal::compiler::Schedule::block(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ComesBeforeInBlock(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ComputePredecessors(), v8::internal::DCHECK(), DCHECK_EQ, v8::base::SmallVector< T, kSize, Allocator >::end(), GetStatus(), v8::internal::compiler::StringBuilderOptimizer::Status::id, v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsClosebyDominator(), IsLoopPhi(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsPhiContainingGivenInputs(), kInStringBuilder, kInvalid, kInvalidId, kPendingPhi, loop_headers_, v8::internal::compiler::BasicBlock::LoopContains(), LoopContains(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::OpcodeIsAllowed(), schedule(), SetStatus(), v8::internal::status, v8::internal::compiler::Node::UseCount(), v8::internal::compiler::Node::uses(), and v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::ValidControlFlowForStringBuilder().
Referenced by CheckPreviousNodeUses().
CheckPreviousNodeUses()
bool v8::internal::compiler::StringBuilderOptimizer::CheckPreviousNodeUses (Node * child, Status status, int input_if_loop_phi = 0) [private]
Definition at line 775 of file string-builder-optimizer.cc.
                                                                          {
  if (IsConcat(child)) {
    return CheckNodeUses(child->InputAt(1), child, status);
  }
  if (child->opcode() == IrOpcode::kPhi) {
    BasicBlock* child_block = schedule()->block(child);
    if (child_block->IsLoopHeader()) {
      return CheckNodeUses(child->InputAt(input_if_loop_phi), child, status);
    } else {
      DCHECK_EQ(child->InputCount(), 3);
      return CheckNodeUses(child->InputAt(0), child, status) &&
             CheckNodeUses(child->InputAt(1), child, status);
    }
  }
  UNREACHABLE();
}
References v8::internal::compiler::Schedule::block(), CheckNodeUses(), DCHECK_EQ, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsConcat(), v8::internal::compiler::BasicBlock::IsLoopHeader(), v8::internal::compiler::Node::opcode(), schedule(), v8::internal::status, and v8::internal::UNREACHABLE().
Referenced by VisitNode().
ConcatIsInStringBuilder()
bool v8::internal::compiler::StringBuilderOptimizer::ConcatIsInStringBuilder (Node * node)
Definition at line 362 of file string-builder-optimizer.cc.
                                                               {
  DCHECK(IsConcat(node));
  Status status = GetStatus(node);
  DCHECK_IMPLIES(status.state == State::kConfirmedInStringBuilder ||
                     status.state == State::kBeginStringBuilder ||
                     status.state == State::kEndStringBuilder,
                 status.id != kInvalidId &&
                     StringBuilderIsValid(string_builders_[status.id]));
  return status.state == State::kConfirmedInStringBuilder ||
         status.state == State::kBeginStringBuilder ||
         status.state == State::kEndStringBuilder;
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, GetStatus(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsConcat(), kBeginStringBuilder, kConfirmedInStringBuilder, kEndStringBuilder, kInvalidId, v8::internal::status, and string_builders_.
Referenced by GetOneOrTwoByte(), and IsFirstConcatInStringBuilder().
FinalizeStringBuilders()
void v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders () [private]
Definition at line 1016 of file string-builder-optimizer.cc.
                                                    {
  OneOrTwoByteAnalysis one_or_two_byte_analysis(graph(), temp_zone(), broker());
  // We use {to_visit} to iterate through a string builder, and {ends} to
  // collect its ending. To save some memory, these 2 variables are declared a
  // bit early, and we .clear() them at the beginning of each iteration (which
  // shouldn't free their memory), rather than allocating new memory for each
  // string builder.
  ZoneVector<Node*> to_visit(temp_zone());
  ZoneVector<Node*> ends(temp_zone());
  bool one_string_builder_or_more_valid = false;
  for (unsigned int string_builder_id = 0;
       string_builder_id < string_builder_count_; string_builder_id++) {
    StringBuilder* string_builder = &string_builders_[string_builder_id];
    Node* start = string_builder->start;
    Status start_status = GetStatus(start);
    if (start_status.state != State::kBeginStringBuilder ||
        !string_builder->has_loop_phi) {
      // {start} has already been invalidated, or the string builder doesn't
      // contain a loop Phi.
      *string_builder = kInvalidStringBuilder;
      UpdateStatus(start, State::kInvalid);
      continue;
    }
    DCHECK_EQ(start_status.state, State::kBeginStringBuilder);
    DCHECK_EQ(start_status.id, string_builder_id);
    one_string_builder_or_more_valid = true;
    OneOrTwoByteAnalysis::State one_or_two_byte =
        one_or_two_byte_analysis.OneOrTwoByte(start);
    to_visit.clear();
    ends.clear();
    to_visit.push_back(start);
    while (!to_visit.empty()) {
      Node* curr = to_visit.back();
      to_visit.pop_back();
      Status curr_status = GetStatus(curr);
      if (curr_status.state == State::kConfirmedInStringBuilder) continue;
      DCHECK(curr_status.state == State::kInStringBuilder ||
             curr_status.state == State::kBeginStringBuilder);
      DCHECK_IMPLIES(curr_status.state == State::kBeginStringBuilder,
                     curr == start);
      DCHECK_EQ(curr_status.id, start_status.id);
      if (curr_status.state != State::kBeginStringBuilder) {
        UpdateStatus(curr, State::kConfirmedInStringBuilder);
      }
      if (IsConcat(curr)) {
        one_or_two_byte = OneOrTwoByteAnalysis::ConcatResultIsOneOrTwoByte(
            one_or_two_byte, one_or_two_byte_analysis.OneOrTwoByte(curr));
        // Duplicating string inputs if needed, and marking them as
        // InStringBuilder (so that EffectControlLinearizer doesn't lower them).
        ReplaceConcatInputIfNeeded(curr, 1);
        ReplaceConcatInputIfNeeded(curr, 2);
      }
      // Check if {curr} is one of the string builder's ends: if {curr} has no
      // uses that are part of the string builder, then {curr} ends the string
      // builder.
      bool has_use_in_string_builder = false;
      for (Node* next : curr->uses()) {
        Status next_status = GetStatus(next);
        if ((next_status.state == State::kInStringBuilder ||
             next_status.state == State::kConfirmedInStringBuilder) &&
            next_status.id == curr_status.id) {
          if (next_status.state == State::kInStringBuilder) {
            // We only add to {to_visit} when the state is kInStringBuilder to
            // make sure that we don't revisit already-visited nodes.
            to_visit.push_back(next);
          }
          if (!IsLoopPhi(curr) || !LoopContains(curr, next)) {
            // The condition above is true when:
            // - {curr} is not a loop phi: in that case, {next} is (one of) the
            // nodes in the string builder after {curr}.
            // - {curr} is a loop phi, and {next} is not inside the loop: in
            // that case, {node} is (one of) the nodes in the string builder
            // that are after {curr}. Note that we ignore uses of {curr}
            // inside the loop, since if {curr} has no uses **after** the
            // loop, then it's (one of) the end of the string builder.
            has_use_in_string_builder = true;
          }
        }
      }
      if (!has_use_in_string_builder) {
        ends.push_back(curr);
      }
    }
    // Note that there is no need to check that the ends have no conflicting
    // uses, because none of the ends can be alive at the same time, and thus,
    // uses of the different ends can't be alive at the same time either. The
    // reason that ens can't be alive at the same time is that if 2 ends were
    // alive at the same time, then there exist a node n that is a predecessors
    // of both ends, and that has 2 successors in the string builder (and alive
    // at the same time), which is not possible because CheckNodeUses prevents
    // it.
    // Collecting next blocks where trimming is required (blocks following a
    // loop Phi where the Phi is the last in a string builder), and setting
    // kEndStringBuilder state to nodes where trimming should be done right
    // after computing the node (when the last node in a string builder is not a
    // loop phi).
    for (Node* end : ends) {
      if (IsLoopPhi(end)) {
        BasicBlock* phi_block = schedule()->block(end);
        for (BasicBlock* block : phi_block->successors()) {
          if (phi_block->LoopContains(block)) continue;
          if (!blocks_to_trimmings_map_[block->id().ToInt()].has_value()) {
            blocks_to_trimmings_map_[block->id().ToInt()] =
                ZoneVector<Node*>(temp_zone());
          }
          blocks_to_trimmings_map_[block->id().ToInt()]->push_back(end);
        }
        UpdateStatus(end, State::kEndStringBuilderLoopPhi);
      } else {
        UpdateStatus(end, State::kEndStringBuilder);
      }
    }
    string_builder->one_or_two_bytes = one_or_two_byte;
  }
#ifdef DEBUG
  if (one_string_builder_or_more_valid) {
    broker()->isolate()->set_has_turbofan_string_builders();
  }
#else
  USE(one_string_builder_or_more_valid);
#endif
}
References v8::internal::ZoneVector< T >::back(), v8::internal::compiler::Schedule::block(), blocks_to_trimmings_map_, broker(), v8::internal::ZoneVector< T >::clear(), v8::internal::compiler::OneOrTwoByteAnalysis::ConcatResultIsOneOrTwoByte(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::ZoneVector< T >::empty(), v8::internal::compiler::end(), GetStatus(), graph(), v8::internal::compiler::StringBuilderOptimizer::StringBuilder::has_loop_phi, v8::internal::compiler::StringBuilderOptimizer::Status::id, v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsConcat(), IsLoopPhi(), v8::internal::compiler::JSHeapBroker::isolate(), kBeginStringBuilder, kConfirmedInStringBuilder, kEndStringBuilder, kEndStringBuilderLoopPhi, kInStringBuilder, kInvalid, kInvalidStringBuilder, v8::internal::compiler::BasicBlock::LoopContains(), LoopContains(), v8::internal::compiler::StringBuilderOptimizer::StringBuilder::one_or_two_bytes, v8::internal::compiler::OneOrTwoByteAnalysis::OneOrTwoByte(), v8::internal::ZoneVector< T >::pop_back(), v8::internal::ZoneVector< T >::push_back(), ReplaceConcatInputIfNeeded(), schedule(), v8::internal::compiler::StringBuilderOptimizer::StringBuilder::start, v8::internal::compiler::StringBuilderOptimizer::Status::state, string_builder_count_, string_builders_, v8::internal::compiler::BasicBlock::successors(), temp_zone(), UpdateStatus(), USE, and v8::internal::compiler::Node::uses().
Referenced by VisitGraph().
GetOneOrTwoByte()
OneOrTwoByteAnalysis::State v8::internal::compiler::StringBuilderOptimizer::GetOneOrTwoByte (Node * node)
Definition at line 329 of file string-builder-optimizer.cc.
                {
  DCHECK(ConcatIsInStringBuilder(node));
  // TODO(v8:13785,dmercadier): once externalization can no longer convert a
  // 1-byte into a 2-byte string, return the proper OneOrTwoByte status for the
  // node (= remove the next line and uncomment the 2 after).
  return OneOrTwoByteAnalysis::State::kCantKnow;
  // int string_builder_number = GetStringBuilderIdForConcat(node);
  // return string_builders_[string_builder_number].one_or_two_bytes;
}
References ConcatIsInStringBuilder(), v8::internal::DCHECK(), and v8::internal::compiler::OneOrTwoByteAnalysis::kCantKnow.
GetPhiPredecessorsCommonId()
int v8::internal::compiler::StringBuilderOptimizer::GetPhiPredecessorsCommonId (Node * node) [private]
Definition at line 414 of file string-builder-optimizer.cc.
                                                                 {
  DCHECK_EQ(node->opcode(), IrOpcode::kPhi);
  int id = kInvalidId;
  for (int i = 0; i < node->op()->ValueInputCount(); i++) {
    Node* input = NodeProperties::GetValueInput(node, i);
    Status status = GetStatus(input);
    switch (status.state) {
      case State::kBeginStringBuilder:
      case State::kInStringBuilder:
      case State::kPendingPhi:
        if (id == kInvalidId) {
          // Initializind {id}.
          id = status.id;
        } else if (id != status.id) {
          // 2 inputs belong to different StringBuilder chains.
          return kInvalidId;
        }
        break;
      case State::kInvalid:
      case State::kUnvisited:
        return kInvalidId;
      default:
        UNREACHABLE();
    }
  }
  DCHECK_NE(id, kInvalidId);
  return id;
}
References DCHECK_EQ, DCHECK_NE, GetStatus(), v8::internal::compiler::NodeProperties::GetValueInput(), kBeginStringBuilder, kInStringBuilder, kInvalid, kInvalidId, kPendingPhi, kUnvisited, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::status, and v8::internal::UNREACHABLE().
Referenced by VisitNode().
GetStatus()
Status v8::internal::compiler::StringBuilderOptimizer::GetStatus (Node * node) const [inline], [private]
Definition at line 290 of file string-builder-optimizer.h.
                                     {
    if (node->id() > status_.size()) {
      return Status{kInvalidId, State::kInvalid};
    } else {
      return status_[node->id()];
    }
  }
References v8::internal::compiler::Node::id(), and v8::internal::anonymous_namespace{isolate.cc}::kInvalid.
Referenced by CheckNodeUses(), ConcatIsInStringBuilder(), FinalizeStringBuilders(), GetPhiPredecessorsCommonId(), GetStringBuilderIdForConcat(), IsFirstConcatInStringBuilder(), IsStringBuilderConcatInput(), IsStringBuilderEnd(), ReplaceConcatInputIfNeeded(), and VisitNode().
GetStringBuilderIdForConcat()
int v8::internal::compiler::StringBuilderOptimizer::GetStringBuilderIdForConcat (Node * node) [private]
Definition at line 375 of file string-builder-optimizer.cc.
                                                                  {
  DCHECK(IsConcat(node));
  Status status = GetStatus(node);
  DCHECK(status.state == State::kConfirmedInStringBuilder ||
         status.state == State::kBeginStringBuilder ||
         status.state == State::kEndStringBuilder);
  DCHECK_NE(status.id, kInvalidId);
  return status.id;
}
References v8::internal::DCHECK(), DCHECK_NE, GetStatus(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsConcat(), kBeginStringBuilder, kConfirmedInStringBuilder, kEndStringBuilder, kInvalidId, and v8::internal::status.
GetStringBuildersToFinalize()
ZoneVector< Node * > v8::internal::compiler::StringBuilderOptimizer::GetStringBuildersToFinalize (BasicBlock * block)
Definition at line 323 of file string-builder-optimizer.cc.
                       {
  DCHECK(BlockShouldFinalizeStringBuilders(block));
  return blocks_to_trimmings_map_[block->id().ToInt()].value();
}
References blocks_to_trimmings_map_, BlockShouldFinalizeStringBuilders(), v8::internal::DCHECK(), v8::internal::compiler::BasicBlock::id(), and v8::internal::compiler::BasicBlock::Id::ToInt().
graph()
TFGraph* v8::internal::compiler::StringBuilderOptimizer::graph () const [inline]
Definition at line 262 of file string-builder-optimizer.h.
{ return jsgraph_->graph(); }
Referenced by FinalizeStringBuilders(), and ReplaceConcatInputIfNeeded().
IsFirstConcatInStringBuilder()
bool v8::internal::compiler::StringBuilderOptimizer::IsFirstConcatInStringBuilder (Node * node)
Definition at line 385 of file string-builder-optimizer.cc.
                                                                    {
  if (!ConcatIsInStringBuilder(node)) return false;
  Status status = GetStatus(node);
  return status.state == State::kBeginStringBuilder;
}
References ConcatIsInStringBuilder(), GetStatus(), kBeginStringBuilder, and v8::internal::status.
IsLoopPhi()
bool v8::internal::compiler::StringBuilderOptimizer::IsLoopPhi (Node * node) const [inline], [private]
Definition at line 331 of file string-builder-optimizer.h.
                                   {
    return node->opcode() == IrOpcode::kPhi &&
           schedule()->block(node)->IsLoopHeader();
  }
References v8::internal::compiler::Schedule::block(), v8::internal::compiler::BasicBlock::IsLoopHeader(), and v8::internal::compiler::Node::opcode().
Referenced by CheckNodeUses(), FinalizeStringBuilders(), and IsNonLoopPhiStringBuilderEnd().
IsNonLoopPhiStringBuilderEnd()
bool v8::internal::compiler::StringBuilderOptimizer::IsNonLoopPhiStringBuilderEnd (Node * node)
Definition at line 350 of file string-builder-optimizer.cc.
                                                                    {
  return IsStringBuilderEnd(node) && !IsLoopPhi(node);
}
References IsLoopPhi(), and IsStringBuilderEnd().
IsStringBuilderConcatInput()
bool v8::internal::compiler::StringBuilderOptimizer::IsStringBuilderConcatInput (Node * node)
Definition at line 354 of file string-builder-optimizer.cc.
                                                                  {
  Status status = GetStatus(node);
  DCHECK_IMPLIES(status.state == State::kConfirmedInStringBuilder,
                 status.id != kInvalidId &&
                     StringBuilderIsValid(string_builders_[status.id]));
  return status.state == State::kConfirmedInStringBuilder;
}
References DCHECK_IMPLIES, GetStatus(), kConfirmedInStringBuilder, kInvalidId, v8::internal::status, and string_builders_.
IsStringBuilderEnd()
bool v8::internal::compiler::StringBuilderOptimizer::IsStringBuilderEnd (Node * node)
Definition at line 340 of file string-builder-optimizer.cc.
                                                          {
  Status status = GetStatus(node);
  DCHECK_IMPLIES(status.state == State::kEndStringBuilder ||
                     status.state == State::kEndStringBuilderLoopPhi,
                 status.id != kInvalidId &&
                     StringBuilderIsValid(string_builders_[status.id]));
  return status.state == State::kEndStringBuilder ||
         status.state == State::kEndStringBuilderLoopPhi;
}
References DCHECK_IMPLIES, GetStatus(), kEndStringBuilder, kEndStringBuilderLoopPhi, kInvalidId, v8::internal::status, and string_builders_.
Referenced by IsNonLoopPhiStringBuilderEnd().
jsgraph()
JSGraph* v8::internal::compiler::StringBuilderOptimizer::jsgraph () const [inline]
Definition at line 261 of file string-builder-optimizer.h.
{ return jsgraph_; }
LoopContains()
bool v8::internal::compiler::StringBuilderOptimizer::LoopContains (Node * loop_phi, Node * node) [inline], [private]
Definition at line 335 of file string-builder-optimizer.h.
                                                {
    DCHECK(IsLoopPhi(loop_phi));
    return schedule()->block(loop_phi)->LoopContains(schedule()->block(node));
  }
References v8::internal::compiler::Schedule::block(), v8::internal::DCHECK(), and v8::internal::compiler::BasicBlock::LoopContains().
Referenced by CheckNodeUses(), and FinalizeStringBuilders().
ReplaceConcatInputIfNeeded()
void v8::internal::compiler::StringBuilderOptimizer::ReplaceConcatInputIfNeeded (Node * node, int input_idx) [private]
Definition at line 397 of file string-builder-optimizer.cc.
                                                                       {
  if (!IsLiteralString(node->InputAt(input_idx), broker())) return;
  Node* input = node->InputAt(input_idx);
  DCHECK_EQ(input->op()->EffectOutputCount(), 0);
  DCHECK_EQ(input->op()->ControlOutputCount(), 0);
  if (input->UseCount() > 1) {
    input = graph()->CloneNode(input);
    node->ReplaceInput(input_idx, input);
  }
  Status node_status = GetStatus(node);
  DCHECK_NE(node_status.id, kInvalidId);
  SetStatus(input, State::kConfirmedInStringBuilder, node_status.id);
}
References broker(), v8::internal::compiler::TFGraph::CloneNode(), v8::internal::compiler::Operator::ControlOutputCount(), DCHECK_EQ, DCHECK_NE, v8::internal::compiler::Operator::EffectOutputCount(), GetStatus(), graph(), v8::internal::compiler::StringBuilderOptimizer::Status::id, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsLiteralString(), kConfirmedInStringBuilder, kInvalidId, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::ReplaceInput(), SetStatus(), and v8::internal::compiler::Node::UseCount().
Referenced by FinalizeStringBuilders().
Run()
void v8::internal::compiler::StringBuilderOptimizer::Run ()
Definition at line 1176 of file string-builder-optimizer.cc.
{ VisitGraph(); }
References VisitGraph().
schedule()
Schedule* v8::internal::compiler::StringBuilderOptimizer::schedule () const [inline]
Definition at line 263 of file string-builder-optimizer.h.
{ return schedule_; }
Referenced by CheckNodeUses(), CheckPreviousNodeUses(), FinalizeStringBuilders(), VisitGraph(), and VisitNode().
SetStatus()
void v8::internal::compiler::StringBuilderOptimizer::SetStatus (Node * node, State state, int id = kInvalidId) [inline], [private]
Definition at line 297 of file string-builder-optimizer.h.
                                                               {
    DCHECK_NE(state, State::kUnvisited);
    DCHECK_IMPLIES(id != kInvalidId, state != State::kInvalid);
    if (node->id() >= status_.size()) {
      // We should really not allocate too many new nodes: the only new nodes we
      // allocate are constant inputs of nodes in the string builder that have
      // multiple uses. Thus, we use a slow exponential growth for {status_}.
      constexpr double growth_factor = 1.1;
      status_.resize(node->id() * growth_factor,
                     Status{kInvalidId, State::kUnvisited});
    }
    status_[node->id()] = Status{id, state};
  }
References DCHECK_IMPLIES, DCHECK_NE, v8::internal::compiler::Node::id(), v8::internal::anonymous_namespace{isolate.cc}::kInvalid, and v8::internal::compiler::kUnvisited.
Referenced by CheckNodeUses(), ReplaceConcatInputIfNeeded(), and VisitNode().
temp_zone()
Zone* v8::internal::compiler::StringBuilderOptimizer::temp_zone () const [inline]
Definition at line 264 of file string-builder-optimizer.h.
{ return temp_zone_; }
Referenced by FinalizeStringBuilders().
UpdateStatus()
void v8::internal::compiler::StringBuilderOptimizer::UpdateStatus (Node * node, State state) [inline], [private]
Definition at line 310 of file string-builder-optimizer.h.
                                             {
    int id = state == State::kInvalid ? kInvalidId : GetStatus(node).id;
    status_[node->id()] = Status{id, state};
  }
References v8::internal::compiler::Node::id(), and v8::internal::anonymous_namespace{isolate.cc}::kInvalid.
Referenced by FinalizeStringBuilders().
VisitGraph()
void v8::internal::compiler::StringBuilderOptimizer::VisitGraph () [private]
Definition at line 1152 of file string-builder-optimizer.cc.
                                        {
  // Initial discovery of the potential string builders.
  for (BasicBlock* block : *schedule()->rpo_order()) {
    // Removing finished loops.
    while (!loop_headers_.empty() &&
           loop_headers_.back()->loop_end() == block) {
      loop_headers_.pop_back();
    }
    // Adding new loop if necessary.
    if (block->IsLoopHeader()) {
      loop_headers_.push_back(block);
    }
    // Visiting block content.
    for (Node* node : *block->nodes()) {
      VisitNode(node, block);
    }
  }
  // Finalize valid string builders (moving valid nodes to status
  // kConfirmedInStringBuilder or kEndStringBuilder), and collecting the
  // trimming points.
  FinalizeStringBuilders();
}
References v8::internal::ZoneVector< T >::back(), v8::internal::ZoneVector< T >::empty(), FinalizeStringBuilders(), loop_headers_, v8::internal::ZoneVector< T >::pop_back(), v8::internal::ZoneVector< T >::push_back(), schedule(), and VisitNode().
Referenced by Run().
VisitNode()
void v8::internal::compiler::StringBuilderOptimizer::VisitNode (Node * node, BasicBlock * block) [private]
Definition at line 793 of file string-builder-optimizer.cc.
                                                                    {
  if (IsConcat(node)) {
    Node* lhs = node->InputAt(1);
    Node* rhs = node->InputAt(2);
    if (!IsLiteralString(rhs, broker())) {
      SetStatus(node, State::kInvalid);
      return;
    }
    if (IsLiteralString(lhs, broker())) {
      // This node could start a string builder. However, we won't know until
      // we've properly inspected its uses, found a Phi somewhere down its use
      // chain, made sure that the Phi was valid, etc. Pre-emptively, we do a
      // quick check (with HasConcatOrPhiUse) that this node has a
      // StringConcat/NewConsString in its uses, and if so, we set its state as
      // kBeginConcat, and increment the {string_builder_count_}. The goal of
      // the HasConcatOrPhiUse is mainly to avoid incrementing
      // {string_builder_count_} too often for things that are obviously just
      // regular concatenations of 2 constant strings and that can't be
      // beginning of string builders.
      if (HasConcatOrPhiUse(lhs)) {
        SetStatus(node, State::kBeginStringBuilder, string_builder_count_);
        string_builders_.push_back(
            StringBuilder{node, static_cast<int>(string_builder_count_), false,
                          OneOrTwoByteAnalysis::State::kUnknown});
        string_builder_count_++;
      }
      // A concatenation between 2 literal strings has no predecessor in the
      // string builder, and there is thus no more checks/bookkeeping required
      // ==> early return.
      return;
    } else {
      Status lhs_status = GetStatus(lhs);
      switch (lhs_status.state) {
        case State::kBeginStringBuilder:
        case State::kInStringBuilder:
          SetStatus(node, State::kInStringBuilder, lhs_status.id);
          break;
        case State::kPendingPhi: {
          BasicBlock* phi_block = schedule()->block(lhs);
          if (phi_block->LoopContains(block)) {
            // This node uses a PendingPhi and is inside the loop. We
            // speculatively set it to kInStringBuilder.
            SetStatus(node, State::kInStringBuilder, lhs_status.id);
          } else {
            // This node uses a PendingPhi but is not inside the loop, which
            // means that the PendingPhi was never resolved to a kInConcat or a
            // kInvalid, which means that it's actually not valid (because we
            // visit the graph in RPO order, which means that we've already
            // visited the whole loop). Thus, we set the Phi to kInvalid, and
            // thus, we also set the current node to kInvalid.
            SetStatus(lhs, State::kInvalid);
            SetStatus(node, State::kInvalid);
          }
          break;
        }
        case State::kInvalid:
        case State::kUnvisited:
          SetStatus(node, State::kInvalid);
          break;
        default:
          UNREACHABLE();
      }
    }
  } else if (node->opcode() == IrOpcode::kPhi &&
             PhiInputsAreConcatsOrPhi(node)) {
    if (!block->IsLoopHeader()) {
      // This Phi merges nodes after a if/else.
      int id = GetPhiPredecessorsCommonId(node);
      if (id == kInvalidId) {
        SetStatus(node, State::kInvalid);
      } else {
        SetStatus(node, State::kInStringBuilder, id);
      }
    } else {
      // This Phi merges a value from inside the loop with one from before.
      DCHECK_EQ(node->op()->ValueInputCount(), 2);
      Status first_input_status = GetStatus(node->InputAt(0));
      switch (first_input_status.state) {
        case State::kBeginStringBuilder:
        case State::kInStringBuilder:
          SetStatus(node, State::kPendingPhi, first_input_status.id);
          break;
        case State::kPendingPhi:
        case State::kInvalid:
        case State::kUnvisited:
          SetStatus(node, State::kInvalid);
          break;
        default:
          UNREACHABLE();
      }
    }
  } else {
    SetStatus(node, State::kInvalid);
  }
  Status status = GetStatus(node);
  if (status.state == State::kInStringBuilder ||
      status.state == State::kPendingPhi) {
    // We make sure that this node being in the string builder doesn't conflict
    // with other uses of the previous node of the string builder. Note that
    // loop phis can never have the kInStringBuilder state at this point. We
    // thus check their uses when we finish the loop and set the phi's status to
    // InStringBuilder.
    if (!CheckPreviousNodeUses(node, status, 0)) {
      SetStatus(node, State::kInvalid);
      return;
    }
    // Updating following PendingPhi if needed.
    for (Node* use : node->uses()) {
      if (use->opcode() == IrOpcode::kPhi) {
        Status use_status = GetStatus(use);
        if (use_status.state == State::kPendingPhi) {
          // Finished the loop.
          SetStatus(use, State::kInStringBuilder, status.id);
          if (use_status.id == status.id &&
              CheckPreviousNodeUses(use, status, 1)) {
            string_builders_[status.id].has_loop_phi = true;
          } else {
            // One of the uses of {node} is a pending Phi that hasn't the
            // correct id (is that even possible?), or the uses of {node} are
            // invalid. Either way, both {node} and {use} are invalid.
            SetStatus(node, State::kInvalid);
            SetStatus(use, State::kInvalid);
          }
        }
      }
    }
  }
}
References v8::internal::compiler::Schedule::block(), broker(), CheckPreviousNodeUses(), DCHECK_EQ, GetPhiPredecessorsCommonId(), GetStatus(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::HasConcatOrPhiUse(), v8::internal::compiler::StringBuilderOptimizer::Status::id, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsConcat(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsLiteralString(), v8::internal::compiler::BasicBlock::IsLoopHeader(), kBeginStringBuilder, kInStringBuilder, kInvalid, kInvalidId, kPendingPhi, v8::internal::compiler::OneOrTwoByteAnalysis::kUnknown, kUnvisited, v8::internal::compiler::BasicBlock::LoopContains(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::PhiInputsAreConcatsOrPhi(), schedule(), SetStatus(), v8::internal::compiler::StringBuilderOptimizer::Status::state, v8::internal::status, string_builder_count_, string_builders_, v8::internal::UNREACHABLE(), use(), v8::internal::compiler::Node::uses(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by VisitGraph().
Member Data Documentation
blocks_to_trimmings_map_
ZoneVector<std::optional<ZoneVector<Node*> > > v8::internal::compiler::StringBuilderOptimizer::blocks_to_trimmings_map_ [private]
Definition at line 366 of file string-builder-optimizer.h.
Referenced by BlockShouldFinalizeStringBuilders(), FinalizeStringBuilders(), and GetStringBuildersToFinalize().
broker_
JSHeapBroker* v8::internal::compiler::StringBuilderOptimizer::broker_ [private]
Definition at line 356 of file string-builder-optimizer.h.
jsgraph_
JSGraph* v8::internal::compiler::StringBuilderOptimizer::jsgraph_ [private]
Definition at line 353 of file string-builder-optimizer.h.
kAllowAnyStringOnTheRhs
constexpr bool v8::internal::compiler::StringBuilderOptimizer::kAllowAnyStringOnTheRhs = false [static], [constexpr], [private]
Definition at line 351 of file string-builder-optimizer.h.
kInvalidId
constexpr int v8::internal::compiler::StringBuilderOptimizer::kInvalidId = -1 [static], [constexpr], [private]
Definition at line 288 of file string-builder-optimizer.h.
Referenced by CheckNodeUses(), ConcatIsInStringBuilder(), GetPhiPredecessorsCommonId(), GetStringBuilderIdForConcat(), IsStringBuilderConcatInput(), IsStringBuilderEnd(), ReplaceConcatInputIfNeeded(), and VisitNode().
kInvalidStringBuilder
const StringBuilder v8::internal::compiler::StringBuilderOptimizer::kInvalidStringBuilder [private]
Initial value:
= {
      nullptr, kInvalidId, false, OneOrTwoByteAnalysis::State::kUnknown}
Definition at line 321 of file string-builder-optimizer.h.
Referenced by FinalizeStringBuilders().
loop_headers_
ZoneVector<BasicBlock*> v8::internal::compiler::StringBuilderOptimizer::loop_headers_ [private]
Definition at line 371 of file string-builder-optimizer.h.
Referenced by CheckNodeUses(), and VisitGraph().
schedule_
Schedule* v8::internal::compiler::StringBuilderOptimizer::schedule_ [private]
Definition at line 354 of file string-builder-optimizer.h.
status_
ZoneVector<Status> v8::internal::compiler::StringBuilderOptimizer::status_ [private]
Definition at line 367 of file string-builder-optimizer.h.
string_builder_count_
unsigned int v8::internal::compiler::StringBuilderOptimizer::string_builder_count_ = 0 [private]
Definition at line 357 of file string-builder-optimizer.h.
Referenced by FinalizeStringBuilders(), and VisitNode().
string_builders_
ZoneVector<StringBuilder> v8::internal::compiler::StringBuilderOptimizer::string_builders_ [private]
Definition at line 368 of file string-builder-optimizer.h.
Referenced by ConcatIsInStringBuilder(), FinalizeStringBuilders(), IsStringBuilderConcatInput(), IsStringBuilderEnd(), and VisitNode().
temp_zone_
Zone* v8::internal::compiler::StringBuilderOptimizer::temp_zone_ [private]
Definition at line 355 of file string-builder-optimizer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/string-builder-optimizer.h
/mnt/V8SourceCode/src/compiler/string-builder-optimizer.cc