v8::internal::compiler::Control Class Reference
#include <node.h>
Public Member Functions
constexpr Control (Node *node)
Node * operator= (Node *value)
Additional Inherited Members
Detailed Description
Definition at line 355 of file node.h.
Constructor & Destructor Documentation
Control()
constexpr v8::internal::compiler::Control::Control (Node * node) [inline], [explicit], [constexpr]
Definition at line 357 of file node.h.
                                         : NodeWrapper(node) {
    // TODO(jgruber): Remove the End special case.
    SLOW_DCHECK(node == nullptr || node->opcode() == IrOpcode::kEnd ||
                node->op()->ControlOutputCount() > 0);
  }
References v8::internal::compiler::Operator::ControlOutputCount(), v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and SLOW_DCHECK.
Member Function Documentation
operator=()
Node* v8::internal::compiler::Control::operator= (Node * value) [inline]
Definition at line 364 of file node.h.
                               {
    DCHECK_GT(value->op()->ControlOutputCount(), 0);
    set_node(value);
    return value;
  }
References DCHECK_GT, and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/node.h