v8::internal::SourceTextModuleDescriptor Class Reference
#include <modules.h>
Classes
class AstModuleRequest
struct AstRawStringComparer
struct Entry
struct ModuleRequestComparer
Public Types
enum CellIndexKind { kInvalid
, kExport
, kImport
 }
using ModuleRequestMap = ZoneSet< const AstModuleRequest *, ModuleRequestComparer >
using RegularExportMap = ZoneMultimap< const AstRawString *, Entry *, AstRawStringComparer >
using RegularImportMap = ZoneMap< const AstRawString *, Entry *, AstRawStringComparer >
Public Member Functions
SourceTextModuleDescriptor (Zone *zone)
void AddImport (const AstRawString *import_name, const AstRawString *local_name, const AstRawString *specifier, const ModuleImportPhase import_phase, const ImportAttributes *import_attributes, const Scanner::Location loc, const Scanner::Location specifier_loc, Zone *zone)
void AddStarImport (const AstRawString *local_name, const AstRawString *specifier, const ImportAttributes *import_attributes, const Scanner::Location loc, const Scanner::Location specifier_loc, Zone *zone)
void AddEmptyImport (const AstRawString *specifier, const ImportAttributes *import_attributes, const Scanner::Location specifier_loc, Zone *zone)
void AddExport (const AstRawString *local_name, const AstRawString *export_name, const Scanner::Location loc, Zone *zone)
void AddExport (const AstRawString *export_name, const AstRawString *import_name, const AstRawString *specifier, const ImportAttributes *import_attributes, const Scanner::Location loc, const Scanner::Location specifier_loc, Zone *zone)
void AddStarExport (const AstRawString *specifier, const ImportAttributes *import_attributes, const Scanner::Location loc, const Scanner::Location specifier_loc, Zone *zone)
bool Validate (ModuleScope *module_scope, PendingCompilationErrorHandler *error_handler, Zone *zone)
const ModuleRequestMap & module_requests () const
const ZoneVector< const Entry * > & namespace_imports () const
const RegularImportMap & regular_imports () const
const ZoneVector< const Entry * > & special_exports () const
const RegularExportMap & regular_exports () const
void AddRegularExport (Entry *entry)
void AddSpecialExport (const Entry *entry, Zone *zone)
void AddRegularImport (Entry *entry)
void AddNamespaceImport (const Entry *entry, Zone *zone)
template<typename IsolateT >
DirectHandle< FixedArray > SerializeRegularExports (IsolateT *isolate, Zone *zone) const
Static Public Member Functions
static CellIndexKind GetCellIndexKind (int cell_index)
Private Member Functions
const Entry * FindDuplicateExport (Zone *zone) const
void MakeIndirectExportsExplicit (Zone *zone)
void AssignCellIndices ()
int AddModuleRequest (const AstRawString *specifier, const ModuleImportPhase import_phase, const ImportAttributes *import_attributes, Scanner::Location specifier_loc, Zone *zone)
Private Attributes
ModuleRequestMap module_requests_
ZoneVector< const Entry * > special_exports_
ZoneVector< const Entry * > namespace_imports_
RegularExportMap regular_exports_
RegularImportMap regular_imports_
Detailed Description
Definition at line 23 of file modules.h.
Member Typedef Documentation
ModuleRequestMap
using v8::internal::SourceTextModuleDescriptor::ModuleRequestMap = ZoneSet<const AstModuleRequest*, ModuleRequestComparer>
Definition at line 173 of file modules.h.
RegularExportMap
using v8::internal::SourceTextModuleDescriptor::RegularExportMap = ZoneMultimap<const AstRawString*, Entry*, AstRawStringComparer>
Definition at line 175 of file modules.h.
RegularImportMap
using v8::internal::SourceTextModuleDescriptor::RegularImportMap = ZoneMap<const AstRawString*, Entry*, AstRawStringComparer>
Definition at line 177 of file modules.h.
Member Enumeration Documentation
CellIndexKind
enum v8::internal::SourceTextModuleDescriptor::CellIndexKind
Enumerator
kInvalid
kExport
kImport
Definition at line 121 of file modules.h.
{ kInvalid, kExport, kImport };
Constructor & Destructor Documentation
SourceTextModuleDescriptor()
v8::internal::SourceTextModuleDescriptor::SourceTextModuleDescriptor (Zone * zone) [inline], [explicit]
Definition at line 25 of file modules.h.
      : module_requests_(zone),
        special_exports_(zone),
        namespace_imports_(zone),
        regular_exports_(zone),
        regular_imports_(zone) {}
Member Function Documentation
AddEmptyImport()
void v8::internal::SourceTextModuleDescriptor::AddEmptyImport (const AstRawString * specifier, const ImportAttributes * import_attributes, const Scanner::Location specifier_loc, Zone * zone)
Definition at line 83 of file modules.cc.
                                                     {
  AddModuleRequest(specifier, ModuleImportPhase::kEvaluation, import_attributes,
                   specifier_loc, zone);
}
References AddModuleRequest(), and v8::kEvaluation.
AddExport() [1/2]
void v8::internal::SourceTextModuleDescriptor::AddExport (const AstRawString * export_name, const AstRawString * import_name, const AstRawString * specifier, const ImportAttributes * import_attributes, const Scanner::Location loc, const Scanner::Location specifier_loc, Zone * zone)
Definition at line 99 of file modules.cc.
                {
  DCHECK_NOT_NULL(import_name);
  DCHECK_NOT_NULL(export_name);
  Entry* entry = zone->New<Entry>(loc);
  entry->export_name = export_name;
  entry->import_name = import_name;
  entry->module_request =
      AddModuleRequest(specifier, ModuleImportPhase::kEvaluation,
                       import_attributes, specifier_loc, zone);
  AddSpecialExport(entry, zone);
}
References AddModuleRequest(), AddSpecialExport(), DCHECK_NOT_NULL, v8::internal::SourceTextModuleDescriptor::Entry::export_name, v8::internal::SourceTextModuleDescriptor::Entry::import_name, v8::kEvaluation, v8::internal::loc, v8::internal::SourceTextModuleDescriptor::Entry::module_request, and v8::internal::Zone::New().
AddExport() [2/2]
void v8::internal::SourceTextModuleDescriptor::AddExport (const AstRawString * local_name, const AstRawString * export_name, const Scanner::Location loc, Zone * zone)
Definition at line 90 of file modules.cc.
                                                                            {
  Entry* entry = zone->New<Entry>(loc);
  entry->export_name = export_name;
  entry->local_name = local_name;
  AddRegularExport(entry);
}
References AddRegularExport(), v8::internal::SourceTextModuleDescriptor::Entry::export_name, v8::internal::loc, v8::internal::SourceTextModuleDescriptor::Entry::local_name, and v8::internal::Zone::New().
Referenced by v8::internal::Parser::ParseExportDeclaration().
AddImport()
void v8::internal::SourceTextModuleDescriptor::AddImport (const AstRawString * import_name, const AstRawString * local_name, const AstRawString * specifier, const ModuleImportPhase import_phase, const ImportAttributes * import_attributes, const Scanner::Location loc, const Scanner::Location specifier_loc, Zone * zone)
Definition at line 58 of file modules.cc.
                                                     {
  Entry* entry = zone->New<Entry>(loc);
  entry->local_name = local_name;
  entry->import_name = import_name;
  entry->module_request = AddModuleRequest(
      specifier, import_phase, import_attributes, specifier_loc, zone);
  AddRegularImport(entry);
}
References AddModuleRequest(), AddRegularImport(), v8::internal::SourceTextModuleDescriptor::Entry::import_name, v8::internal::loc, v8::internal::SourceTextModuleDescriptor::Entry::local_name, v8::internal::SourceTextModuleDescriptor::Entry::module_request, and v8::internal::Zone::New().
AddModuleRequest()
int v8::internal::SourceTextModuleDescriptor::AddModuleRequest (const AstRawString * specifier, const ModuleImportPhase import_phase, const ImportAttributes * import_attributes, Scanner::Location specifier_loc, Zone * zone) [inline], [private]
Definition at line 270 of file modules.h.
                                                                  {
    DCHECK_NOT_NULL(specifier);
    int module_requests_count = static_cast<int>(module_requests_.size());
    auto it = module_requests_
                  .insert(zone->New<AstModuleRequest>(
                      specifier, import_phase, import_attributes,
                      specifier_loc.beg_pos, module_requests_count))
                  .first;
    return (*it)->index();
  }
References v8::internal::Scanner::Location::beg_pos, DCHECK_NOT_NULL, module_requests_, and v8::internal::Zone::New().
Referenced by AddEmptyImport(), AddExport(), AddImport(), AddStarExport(), and AddStarImport().
AddNamespaceImport()
void v8::internal::SourceTextModuleDescriptor::AddNamespaceImport (const Entry * entry, Zone * zone) [inline]
Definition at line 224 of file modules.h.
                                                          {
    DCHECK_NULL(entry->import_name);
    DCHECK_NULL(entry->export_name);
    DCHECK_NOT_NULL(entry->local_name);
    DCHECK_LE(0, entry->module_request);
    namespace_imports_.push_back(entry);
  }
References DCHECK_LE, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::SourceTextModuleDescriptor::Entry::export_name, v8::internal::SourceTextModuleDescriptor::Entry::import_name, v8::internal::SourceTextModuleDescriptor::Entry::local_name, v8::internal::SourceTextModuleDescriptor::Entry::module_request, and namespace_imports_.
Referenced by AddStarImport().
AddRegularExport()
void v8::internal::SourceTextModuleDescriptor::AddRegularExport (Entry * entry) [inline]
Definition at line 200 of file modules.h.
                                      {
    DCHECK_NOT_NULL(entry->export_name);
    DCHECK_NOT_NULL(entry->local_name);
    DCHECK_NULL(entry->import_name);
    DCHECK_LT(entry->module_request, 0);
    regular_exports_.insert(std::make_pair(entry->local_name, entry));
  }
References DCHECK_LT, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::SourceTextModuleDescriptor::Entry::export_name, v8::internal::SourceTextModuleDescriptor::Entry::import_name, v8::internal::SourceTextModuleDescriptor::Entry::local_name, v8::internal::SourceTextModuleDescriptor::Entry::module_request, and regular_exports_.
Referenced by AddExport().
AddRegularImport()
void v8::internal::SourceTextModuleDescriptor::AddRegularImport (Entry * entry) [inline]
Definition at line 214 of file modules.h.
                                      {
    DCHECK_NOT_NULL(entry->import_name);
    DCHECK_NOT_NULL(entry->local_name);
    DCHECK_NULL(entry->export_name);
    DCHECK_LE(0, entry->module_request);
    regular_imports_.insert(std::make_pair(entry->local_name, entry));
    // We don't care if there's already an entry for this local name, as in that
    // case we will report an error when declaring the variable.
  }
References DCHECK_LE, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::SourceTextModuleDescriptor::Entry::export_name, v8::internal::SourceTextModuleDescriptor::Entry::import_name, v8::internal::SourceTextModuleDescriptor::Entry::local_name, v8::internal::SourceTextModuleDescriptor::Entry::module_request, and regular_imports_.
Referenced by AddImport().
AddSpecialExport()
void v8::internal::SourceTextModuleDescriptor::AddSpecialExport (const Entry * entry, Zone * zone) [inline]
Definition at line 208 of file modules.h.
                                                        {
    DCHECK_NULL(entry->local_name);
    DCHECK_LE(0, entry->module_request);
    special_exports_.push_back(entry);
  }
References DCHECK_LE, DCHECK_NULL, v8::internal::SourceTextModuleDescriptor::Entry::local_name, v8::internal::SourceTextModuleDescriptor::Entry::module_request, and special_exports_.
Referenced by AddExport(), AddStarExport(), and MakeIndirectExportsExplicit().
AddStarExport()
void v8::internal::SourceTextModuleDescriptor::AddStarExport (const AstRawString * specifier, const ImportAttributes * import_attributes, const Scanner::Location loc, const Scanner::Location specifier_loc, Zone * zone)
Definition at line 115 of file modules.cc.
                {
  Entry* entry = zone->New<Entry>(loc);
  entry->module_request =
      AddModuleRequest(specifier, ModuleImportPhase::kEvaluation,
                       import_attributes, specifier_loc, zone);
  AddSpecialExport(entry, zone);
}
References AddModuleRequest(), AddSpecialExport(), v8::kEvaluation, v8::internal::loc, v8::internal::SourceTextModuleDescriptor::Entry::module_request, and v8::internal::Zone::New().
AddStarImport()
void v8::internal::SourceTextModuleDescriptor::AddStarImport (const AstRawString * local_name, const AstRawString * specifier, const ImportAttributes * import_attributes, const Scanner::Location loc, const Scanner::Location specifier_loc, Zone * zone)
Definition at line 71 of file modules.cc.
                                                     {
  Entry* entry = zone->New<Entry>(loc);
  entry->local_name = local_name;
  entry->module_request =
      AddModuleRequest(specifier, ModuleImportPhase::kEvaluation,
                       import_attributes, specifier_loc, zone);
  AddNamespaceImport(entry, zone);
}
References AddModuleRequest(), AddNamespaceImport(), v8::kEvaluation, v8::internal::loc, v8::internal::SourceTextModuleDescriptor::Entry::local_name, v8::internal::SourceTextModuleDescriptor::Entry::module_request, and v8::internal::Zone::New().
AssignCellIndices()
void v8::internal::SourceTextModuleDescriptor::AssignCellIndices () [private]
Definition at line 285 of file modules.cc.
                                                   {
  int export_index = 1;
  for (auto it = regular_exports_.begin(); it != regular_exports_.end();) {
    auto current_key = it->first;
    // This local name may be exported under multiple export names. Assign the
    // same index to each such entry.
    do {
      Entry* entry = it->second;
      DCHECK_NOT_NULL(entry->local_name);
      DCHECK_NULL(entry->import_name);
      DCHECK_LT(entry->module_request, 0);
      DCHECK_EQ(entry->cell_index, 0);
      entry->cell_index = export_index;
      it++;
    } while (it != regular_exports_.end() && it->first == current_key);
    export_index++;
  }
  int import_index = -1;
  for (const auto& elem : regular_imports_) {
    Entry* entry = elem.second;
    DCHECK_NOT_NULL(entry->local_name);
    DCHECK_NOT_NULL(entry->import_name);
    DCHECK_LE(0, entry->module_request);
    DCHECK_EQ(entry->cell_index, 0);
    entry->cell_index = import_index;
    import_index--;
  }
}
References v8::internal::SourceTextModuleDescriptor::Entry::cell_index, DCHECK_EQ, DCHECK_LE, DCHECK_LT, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::SourceTextModuleDescriptor::Entry::import_name, v8::internal::SourceTextModuleDescriptor::Entry::local_name, v8::internal::SourceTextModuleDescriptor::Entry::module_request, regular_exports_, and regular_imports_.
Referenced by Validate().
FindDuplicateExport()
const SourceTextModuleDescriptor::Entry * v8::internal::SourceTextModuleDescriptor::FindDuplicateExport (Zone * zone) const [private]
Definition at line 338 of file modules.cc.
                                                                {
  const SourceTextModuleDescriptor::Entry* duplicate = nullptr;
  ZoneMap<const AstRawString*, const SourceTextModuleDescriptor::Entry*>
      export_names(zone);
  for (const auto& elem : regular_exports_) {
    duplicate = BetterDuplicate(elem.second, export_names, duplicate);
  }
  for (auto entry : special_exports_) {
    if (entry->export_name == nullptr) continue; // Star export.
    duplicate = BetterDuplicate(entry, export_names, duplicate);
  }
  return duplicate;
}
References v8::internal::anonymous_namespace{modules.cc}::BetterDuplicate(), regular_exports_, and special_exports_.
Referenced by Validate().
GetCellIndexKind()
SourceTextModuleDescriptor::CellIndexKind v8::internal::SourceTextModuleDescriptor::GetCellIndexKind (int cell_index) [static]
Definition at line 279 of file modules.cc.
                                                           {
  if (cell_index > 0) return kExport;
  if (cell_index < 0) return kImport;
  return kInvalid;
}
References kExport, kImport, and kInvalid.
Referenced by v8::internal::compiler::JSTypedLowering::BuildGetModuleCell(), v8::internal::SourceTextModule::ExportIndex(), v8::internal::SourceTextModule::GetCell(), v8::internal::SourceTextModule::ImportIndex(), v8::internal::Context::Lookup(), v8::internal::compiler::JSTypedLowering::ReduceJSStoreModule(), v8::internal::ScopeIterator::SetModuleVariableValue(), and v8::internal::SourceTextModule::StoreVariable().
MakeIndirectExportsExplicit()
void v8::internal::SourceTextModuleDescriptor::MakeIndirectExportsExplicit (Zone * zone) [private]
Definition at line 246 of file modules.cc.
                                                                       {
  for (auto it = regular_exports_.begin(); it != regular_exports_.end();) {
    Entry* entry = it->second;
    DCHECK_NOT_NULL(entry->local_name);
    auto import = regular_imports_.find(entry->local_name);
    if (import != regular_imports_.end()) {
      // Found an indirect export. Patch export entry and move it from regular
      // to special.
      DCHECK_NULL(entry->import_name);
      DCHECK_LT(entry->module_request, 0);
      DCHECK_NOT_NULL(import->second->import_name);
      DCHECK_LE(0, import->second->module_request);
      DCHECK_LT(import->second->module_request,
                static_cast<int>(module_requests_.size()));
      entry->import_name = import->second->import_name;
      entry->module_request = import->second->module_request;
      // Hack: When the indirect export cannot be resolved, we want the error
      // message to point at the import statement, not at the export statement.
      // Therefore we overwrite [entry]'s location here. Note that Validate()
      // has already checked for duplicate exports, so it's guaranteed that we
      // won't need to report any error pointing at the (now lost) export
      // location.
      entry->location = import->second->location;
      entry->local_name = nullptr;
      AddSpecialExport(entry, zone);
      it = regular_exports_.erase(it);
    } else {
      it++;
    }
  }
}
References AddSpecialExport(), DCHECK_LE, DCHECK_LT, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::SourceTextModuleDescriptor::Entry::import_name, v8::internal::SourceTextModuleDescriptor::Entry::local_name, v8::internal::SourceTextModuleDescriptor::Entry::location, v8::internal::SourceTextModuleDescriptor::Entry::module_request, module_requests_, regular_exports_, and regular_imports_.
Referenced by Validate().
module_requests()
const ModuleRequestMap& v8::internal::SourceTextModuleDescriptor::module_requests () const [inline]
Definition at line 181 of file modules.h.
{ return module_requests_; }
References module_requests_.
Referenced by v8::internal::SourceTextModuleInfo::New().
namespace_imports()
const ZoneVector<const Entry*>& v8::internal::SourceTextModuleDescriptor::namespace_imports () const [inline]
Definition at line 184 of file modules.h.
                                                            {
    return namespace_imports_;
  }
References namespace_imports_.
Referenced by v8::internal::SourceTextModuleInfo::New(), and v8::internal::interpreter::BytecodeGenerator::VisitModuleNamespaceImports().
regular_exports()
const RegularExportMap& v8::internal::SourceTextModuleDescriptor::regular_exports () const [inline]
Definition at line 198 of file modules.h.
{ return regular_exports_; }
References regular_exports_.
regular_imports()
const RegularImportMap& v8::internal::SourceTextModuleDescriptor::regular_imports () const [inline]
Definition at line 189 of file modules.h.
{ return regular_imports_; }
References regular_imports_.
Referenced by v8::internal::SourceTextModuleInfo::New().
SerializeRegularExports()
template<typename IsolateT >
template DirectHandle< FixedArray > v8::internal::SourceTextModuleDescriptor::SerializeRegularExports (IsolateT * isolate, Zone * zone) const
Definition at line 185 of file modules.cc.
                                         {
  // We serialize regular exports in a way that lets us later iterate over their
  // local names and for each local name immediately access all its export
  // names. (Regular exports have neither import name nor module request.)
  ZoneVector<IndirectHandle<Object>> data(
      SourceTextModuleInfo::kRegularExportLength * regular_exports_.size(),
      zone);
  int index = 0;
  for (auto it = regular_exports_.begin(); it != regular_exports_.end();) {
    // Find out how many export names this local name has.
    auto next = it;
    int count = 0;
    do {
      DCHECK_EQ(it->second->local_name, next->second->local_name);
      DCHECK_EQ(it->second->cell_index, next->second->cell_index);
      ++next;
      ++count;
    } while (next != regular_exports_.end() && next->first == it->first);
    Handle<FixedArray> export_names =
        isolate->factory()->NewFixedArray(count, AllocationType::kOld);
    data[index + SourceTextModuleInfo::kRegularExportLocalNameOffset] =
        it->second->local_name->string();
    data[index + SourceTextModuleInfo::kRegularExportCellIndexOffset] =
        handle(Smi::FromInt(it->second->cell_index), isolate);
    data[index + SourceTextModuleInfo::kRegularExportExportNamesOffset] =
        export_names;
    index += SourceTextModuleInfo::kRegularExportLength;
    // Collect the export names.
    int i = 0;
    for (; it != next; ++it) {
      export_names->set(i++, *it->second->export_name->string());
    }
    DCHECK_EQ(i, count);
    // Continue with the next distinct key.
    DCHECK(it == next);
  }
  DCHECK_LE(index, static_cast<int>(data.size()));
  data.resize(index);
  // We cannot create the FixedArray earlier because we only now know the
  // precise size.
  DirectHandle<FixedArray> result =
      isolate->factory()->NewFixedArray(index, AllocationType::kOld);
  for (int i = 0; i < index; ++i) {
    result->set(i, *data[i]);
  }
  return result;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::Smi::FromInt(), v8::internal::handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::kOld, v8::internal::SourceTextModuleInfo::kRegularExportCellIndexOffset, v8::internal::SourceTextModuleInfo::kRegularExportExportNamesOffset, v8::internal::SourceTextModuleInfo::kRegularExportLength, v8::internal::SourceTextModuleInfo::kRegularExportLocalNameOffset, regular_exports_, v8::internal::ZoneVector< T >::resize(), v8::base::internal::result, and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::SourceTextModuleInfo::New().
special_exports()
const ZoneVector<const Entry*>& v8::internal::SourceTextModuleDescriptor::special_exports () const [inline]
Definition at line 192 of file modules.h.
                                                          {
    return special_exports_;
  }
References special_exports_.
Referenced by v8::internal::SourceTextModuleInfo::New().
Validate()
bool v8::internal::SourceTextModuleDescriptor::Validate (ModuleScope * module_scope, PendingCompilationErrorHandler * error_handler, Zone * zone)
Definition at line 352 of file modules.cc.
                {
  DCHECK_EQ(this, module_scope->module());
  DCHECK_NOT_NULL(error_handler);
  // Report error iff there are duplicate exports.
  {
    const Entry* entry = FindDuplicateExport(zone);
    if (entry != nullptr) {
      error_handler->ReportMessageAt(
          entry->location.beg_pos, entry->location.end_pos,
          MessageTemplate::kDuplicateExport, entry->export_name);
      return false;
    }
  }
  // Report error iff there are exports of non-existent local names.
  for (const auto& elem : regular_exports_) {
    const Entry* entry = elem.second;
    DCHECK_NOT_NULL(entry->local_name);
    if (module_scope->LookupLocal(entry->local_name) == nullptr) {
      error_handler->ReportMessageAt(
          entry->location.beg_pos, entry->location.end_pos,
          MessageTemplate::kModuleExportUndefined, entry->local_name);
      return false;
    }
  }
  MakeIndirectExportsExplicit(zone);
  AssignCellIndices();
  return true;
}
References AssignCellIndices(), v8::internal::Scanner::Location::beg_pos, DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::Scanner::Location::end_pos, v8::internal::SourceTextModuleDescriptor::Entry::export_name, FindDuplicateExport(), v8::internal::SourceTextModuleDescriptor::Entry::local_name, v8::internal::SourceTextModuleDescriptor::Entry::location, v8::internal::Scope::LookupLocal(), MakeIndirectExportsExplicit(), v8::internal::ModuleScope::module(), regular_exports_, and v8::internal::PendingCompilationErrorHandler::ReportMessageAt().
Member Data Documentation
module_requests_
ModuleRequestMap v8::internal::SourceTextModuleDescriptor::module_requests_ [private]
Definition at line 237 of file modules.h.
Referenced by AddModuleRequest(), MakeIndirectExportsExplicit(), and module_requests().
namespace_imports_
ZoneVector<const Entry*> v8::internal::SourceTextModuleDescriptor::namespace_imports_ [private]
Definition at line 239 of file modules.h.
Referenced by AddNamespaceImport(), and namespace_imports().
regular_exports_
RegularExportMap v8::internal::SourceTextModuleDescriptor::regular_exports_ [private]
Definition at line 240 of file modules.h.
Referenced by AddRegularExport(), AssignCellIndices(), FindDuplicateExport(), MakeIndirectExportsExplicit(), regular_exports(), SerializeRegularExports(), and Validate().
regular_imports_
RegularImportMap v8::internal::SourceTextModuleDescriptor::regular_imports_ [private]
Definition at line 241 of file modules.h.
Referenced by AddRegularImport(), AssignCellIndices(), MakeIndirectExportsExplicit(), and regular_imports().
special_exports_
ZoneVector<const Entry*> v8::internal::SourceTextModuleDescriptor::special_exports_ [private]
Definition at line 238 of file modules.h.
Referenced by AddSpecialExport(), FindDuplicateExport(), and special_exports().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/modules.h
/mnt/V8SourceCode/src/ast/modules.cc