cppgc::subtle::NoGarbageCollectionScope Class Reference
Avoids invoking garbage collection finalizations.
#include <heap-consistency.h>
Public Member Functions
NoGarbageCollectionScope (HeapHandle &heap_handle)
Constructs a scoped object that automatically enters and leaves a no garbage collection scope based on its lifetime.
~NoGarbageCollectionScope ()
NoGarbageCollectionScope (const NoGarbageCollectionScope &)=delete
NoGarbageCollectionScope & operator= (const NoGarbageCollectionScope &)=delete
Static Public Member Functions
static void Enter (HeapHandle &heap_handle)
Enters a no garbage collection scope.
static void Leave (HeapHandle &heap_handle)
Leaves a no garbage collection scope.
Private Member Functions
CPPGC_STACK_ALLOCATED ()
Private Attributes
HeapHandle & heap_handle_
Detailed Description
Avoids invoking garbage collection finalizations.
Already running garbage collection phase are unaffected by this scope.
Should only be used temporarily as the scope has an impact on memory usage and follow up garbage collections.
Definition at line 270 of file heap-consistency.h.
Constructor & Destructor Documentation
NoGarbageCollectionScope() [1/2]
cppgc::subtle::NoGarbageCollectionScope::NoGarbageCollectionScope (cppgc::HeapHandle & heap_handle) [explicit]
Constructs a scoped object that automatically enters and leaves a no garbage collection scope based on its lifetime.
Parameters
heap_handle The corresponding heap.
Definition at line 55 of file heap-consistency.cc.
    : heap_handle_(heap_handle) {
  Enter(heap_handle);
}
References Enter().
 NoGarbageCollectionScope()
cppgc::subtle::NoGarbageCollectionScope::~NoGarbageCollectionScope ()
Definition at line 61 of file heap-consistency.cc.
{ Leave(heap_handle_); }
References heap_handle_, and Leave().
NoGarbageCollectionScope() [2/2]
cppgc::subtle::NoGarbageCollectionScope::NoGarbageCollectionScope (const NoGarbageCollectionScope &) [delete]
Member Function Documentation
CPPGC_STACK_ALLOCATED()
cppgc::subtle::NoGarbageCollectionScope::CPPGC_STACK_ALLOCATED () [private]
Enter()
void cppgc::subtle::NoGarbageCollectionScope::Enter (cppgc::HeapHandle & heap_handle) [static]
Enters a no garbage collection scope.
Must be paired with Leave(). Prefer a scope instance of NoGarbageCollectionScope.
Parameters
heap_handle The corresponding heap.
Definition at line 44 of file heap-consistency.cc.
                                                                 {
  auto& heap_base = internal::HeapBase::From(heap_handle);
  heap_base.EnterNoGCScope();
}
References cppgc::internal::HeapBase::From().
Referenced by NoGarbageCollectionScope().
Leave()
void cppgc::subtle::NoGarbageCollectionScope::Leave (cppgc::HeapHandle & heap_handle) [static]
Leaves a no garbage collection scope.
Must be paired with Enter(). Prefer a scope instance of NoGarbageCollectionScope.
Parameters
heap_handle The corresponding heap.
Definition at line 50 of file heap-consistency.cc.
                                                                 {
  auto& heap_base = internal::HeapBase::From(heap_handle);
  heap_base.LeaveNoGCScope();
}
References cppgc::internal::HeapBase::From().
Referenced by ~NoGarbageCollectionScope().
operator=()
NoGarbageCollectionScope& cppgc::subtle::NoGarbageCollectionScope::operator= (const NoGarbageCollectionScope &) [delete]
Member Data Documentation
heap_handle_
HeapHandle& cppgc::subtle::NoGarbageCollectionScope::heap_handle_ [private]
Definition at line 303 of file heap-consistency.h.
Referenced by ~NoGarbageCollectionScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/heap-consistency.h
/mnt/V8SourceCode/src/heap/cppgc/heap-consistency.cc