v8::internal::IntlMathematicalValue Class Reference
#include <js-number-format.h>
Public Member Functions
IntlMathematicalValue ()
V8_EXPORT_PRIVATE bool IsNaN () const
Static Public Member Functions
static V8_EXPORT_PRIVATE Maybe< IntlMathematicalValue > From (Isolate *isolate, Handle< Object > value)
static Maybe< icu::number::FormattedNumber > FormatNumeric (Isolate *isolate, const icu::number::LocalizedNumberFormatter &number_format, const IntlMathematicalValue &x)
static Maybe< icu::number::FormattedNumberRange > FormatRange (Isolate *isolate, const icu::number::LocalizedNumberRangeFormatter &number_range_format, const IntlMathematicalValue &x, const IntlMathematicalValue &y)
Private Member Functions
Maybe< icu::Formattable > ToFormattable (Isolate *isolate) const
MaybeHandle< String > ToString (Isolate *isolate) const
Private Attributes
double approx_
Handle< Object > value_
Detailed Description
Definition at line 128 of file js-number-format.h.
Constructor & Destructor Documentation
IntlMathematicalValue()
v8::internal::IntlMathematicalValue::IntlMathematicalValue () [inline]
Definition at line 130 of file js-number-format.h.
: approx_(0) {}
Member Function Documentation
FormatNumeric()
Maybe< icu::number::FormattedNumber > v8::internal::IntlMathematicalValue::FormatNumeric (Isolate * isolate, const icu::number::LocalizedNumberFormatter & number_format, const IntlMathematicalValue & x) [static]
Definition at line 1596 of file js-number-format.cc.
                                    {
  if (IsString(*x.value_)) {
    Handle<String> string;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, string, x.ToString(isolate),
                                     Nothing<icu::number::FormattedNumber>());
    UErrorCode status = U_ZERO_ERROR;
    icu::number::FormattedNumber result =
        FormatDecimalString(isolate, number_format, string, status);
    if (U_FAILURE(status)) {
      THROW_NEW_ERROR_RETURN_VALUE(isolate,
                                   NewTypeError(MessageTemplate::kIcuError),
                                   Nothing<icu::number::FormattedNumber>());
    }
    return Just(std::move(result));
  }
  CHECK(IsNumber(*x.value_) || IsBigInt(*x.value_));
  return IcuFormatNumber(isolate, number_format, x.value_);
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, CHECK, v8::internal::anonymous_namespace{js-number-format.cc}::FormatDecimalString(), v8::internal::anonymous_namespace{js-number-format.cc}::IcuFormatNumber(), v8::internal::IsNumber(), v8::Just(), v8::base::internal::result, v8::internal::status, v8::internal::string, THROW_NEW_ERROR_RETURN_VALUE, ToString(), and value_.
Referenced by v8::internal::JSNumberFormat::FormatToParts(), and v8::internal::JSNumberFormat::NumberFormatFunction().
FormatRange()
Maybe< icu::number::FormattedNumberRange > v8::internal::IntlMathematicalValue::FormatRange (Isolate * isolate, const icu::number::LocalizedNumberRangeFormatter & number_range_format, const IntlMathematicalValue & x, const IntlMathematicalValue & y) [static]
Definition at line 1618 of file js-number-format.cc.
                                                                    {
  icu::Formattable x_formatable;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, x_formatable, x.ToFormattable(isolate),
      Nothing<icu::number::FormattedNumberRange>());
  icu::Formattable y_formatable;
  MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate, y_formatable, y.ToFormattable(isolate),
      Nothing<icu::number::FormattedNumberRange>());
  UErrorCode status = U_ZERO_ERROR;
  icu::number::FormattedNumberRange result =
      number_range_format.formatFormattableRange(x_formatable, y_formatable,
                                                 status);
  if (U_FAILURE(status)) {
    THROW_NEW_ERROR_RETURN_VALUE(isolate,
                                 NewTypeError(MessageTemplate::kIcuError),
                                 Nothing<icu::number::FormattedNumberRange>());
  }
  return Just(std::move(result));
}
References v8::Just(), MAYBE_ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::base::internal::result, v8::internal::status, THROW_NEW_ERROR_RETURN_VALUE, ToFormattable(), and v8::internal::y.
Referenced by v8::internal::anonymous_namespace{js-number-format.cc}::PartitionNumberRangePattern().
From()
Maybe< IntlMathematicalValue > v8::internal::IntlMathematicalValue::From (Isolate * isolate, Handle< Object > value) [static]
Definition at line 1695 of file js-number-format.cc.
                                                                               {
  Factory* factory = isolate->factory();
  // 1. Let primValue be ? ToPrimitive(value, number).
  Handle<Object> prim_value;
  if (IsJSReceiver(*value)) {
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, prim_value,
        JSReceiver::ToPrimitive(isolate, Cast<JSReceiver>(value),
                                ToPrimitiveHint::kNumber),
        Nothing<IntlMathematicalValue>());
  } else {
    prim_value = value;
  }
  IntlMathematicalValue result;
  // 2. If Type(primValue) is BigInt, return the mathematical value of
  // primValue.
  if (IsBigInt(*prim_value)) {
    result.value_ = prim_value;
    result.approx_ = Cast<BigInt>(prim_value)->AsInt64();
    return Just(result);
  }
  if (IsOddball(*prim_value)) {
    prim_value = Oddball::ToNumber(isolate, Cast<Oddball>(prim_value));
  }
  if (IsNumber(*prim_value)) {
    result.value_ = prim_value;
    result.approx_ = Object::NumberValue(*prim_value);
    return Just(result);
  }
  if (!IsString(*prim_value)) {
    // No need to convert from Number to String, just call ToNumber.
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, result.value_,
                                     Object::ToNumber(isolate, prim_value),
                                     Nothing<IntlMathematicalValue>());
    result.approx_ = Object::NumberValue(*result.value_);
    return Just(result);
  }
  Handle<String> string = Cast<String>(prim_value);
  string = TrimWhiteSpaceOrLineTerminator(isolate, string);
  if (string->length() == 0) {
    result.value_ = handle(Smi::zero(), isolate);
    result.approx_ = 0;
    return Just(result);
  }
  // We may have a NonDecimalIntegerLiteral:
  if (2 < string->length() && string->Get(0) == '0') {
    uint16_t ch = string->Get(1);
    if (ch == 'b' || ch == 'B' || ch == 'o' || ch == 'O' || ch == 'x' ||
        ch == 'X') {
      result.approx_ =
          StringToDouble(isolate, string, ALLOW_NON_DECIMAL_PREFIX, 0);
      // If approx is within the precision, just return as Number.
      if (result.approx_ < kMaxSafeInteger) {
        result.value_ = isolate->factory()->NewNumber(result.approx_);
        return Just(result);
      }
      // Otherwise return the BigInt
      MaybeHandle<BigInt> maybe_bigint = StringToBigInt(isolate, string);
      // If the parsing of BigInt fail, return nan
      if (maybe_bigint.is_null()) {
        isolate->clear_exception();
        result.value_ = factory->nan_value();
        return Just(result);
      }
      result.value_ = maybe_bigint.ToHandleChecked();
      return Just(result);
    }
  }
  // If it does not fit StrDecimalLiteral StrWhiteSpace_opt, StringToDouble will
  // parse it as NaN, in that case, return NaN.
  result.approx_ = StringToDouble(isolate, string, NO_CONVERSION_FLAG, 0);
  if (std::isnan(result.approx_)) {
    result.value_ = factory->nan_value();
    return Just(result);
  }
  // Handle Infinity / +Infinity / -Infinity
  if (!std::isfinite(result.approx_)) {
    if (result.approx_ < 0) {
      result.value_ = factory->minus_infinity_value();
    } else {
      result.value_ = factory->infinity_value();
    }
    return Just(result);
  }
  // At this point, str is for sure fit
  // "StrNumericLiteral StrWhiteSpace_opt" excluding "(+|-)?Infinity"
  result.value_ = string;
  return Just(result);
}
References v8::internal::ALLOW_NON_DECIMAL_PREFIX, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::Isolate::clear_exception(), v8::internal::Isolate::factory(), v8::internal::handle(), v8::internal::MaybeHandle< T >::is_null(), v8::internal::IsNumber(), v8::Just(), v8::internal::kMaxSafeInteger, v8::internal::kNumber, v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::NO_CONVERSION_FLAG, v8::internal::Object::NumberValue(), v8::base::internal::result, v8::internal::string, v8::internal::StringToBigInt(), v8::internal::StringToDouble(), v8::internal::MaybeHandle< T >::ToHandleChecked(), v8::internal::Oddball::ToNumber(), v8::Value::ToNumber(), v8::internal::anonymous_namespace{js-number-format.cc}::TrimWhiteSpaceOrLineTerminator(), v8::internal::value, and v8::internal::Smi::zero().
Referenced by v8::internal::JSNumberFormat::FormatToParts(), v8::internal::JSNumberFormat::NumberFormatFunction(), and v8::internal::anonymous_namespace{js-number-format.cc}::PartitionNumberRangePattern().
IsNaN()
bool v8::internal::IntlMathematicalValue::IsNaN () const
Definition at line 1519 of file js-number-format.cc.
{ return i::IsNaN(*value_); }
References v8::internal::IsNaN(), and value_.
Referenced by v8::internal::JSNumberFormat::NumberFormatFunction(), and v8::internal::anonymous_namespace{js-number-format.cc}::PartitionNumberRangePattern().
ToFormattable()
Maybe< icu::Formattable > v8::internal::IntlMathematicalValue::ToFormattable (Isolate * isolate) const [private]
Definition at line 1788 of file js-number-format.cc.
                            {
  if (IsNumber(*value_)) {
    return Just(icu::Formattable(approx_));
  }
  DirectHandle<String> string;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, string, ToString(isolate),
                                   Nothing<icu::Formattable>());
  UErrorCode status = U_ZERO_ERROR;
  {
    DisallowGarbageCollection no_gc;
    const String::FlatContent& flat = string->GetFlatContent(no_gc);
    int32_t length = SignedStringLength(string);
    if (flat.IsOneByte()) {
      icu::Formattable result(
          {reinterpret_cast<const char*>(flat.ToOneByteVector().begin()),
           length},
          status);
      if (U_SUCCESS(status)) return Just(result);
    } else {
      auto converted = string->ToStdString();
      icu::Formattable result(converted, status);
      if (U_SUCCESS(status)) return Just(result);
    }
  }
  THROW_NEW_ERROR_RETURN_VALUE(isolate,
                               NewTypeError(MessageTemplate::kIcuError),
                               Nothing<icu::Formattable>());
}
References approx_, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::compiler::begin(), v8::internal::IsNumber(), v8::internal::String::FlatContent::IsOneByte(), v8::Just(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::anonymous_namespace{js-number-format.cc}::SignedStringLength(), v8::internal::status, v8::internal::string, THROW_NEW_ERROR_RETURN_VALUE, v8::internal::String::FlatContent::ToOneByteVector(), ToString(), and value_.
Referenced by FormatRange().
ToString()
MaybeHandle< String > v8::internal::IntlMathematicalValue::ToString (Isolate * isolate) const [private]
Definition at line 1521 of file js-number-format.cc.
                                                                          {
  DirectHandle<String> string;
  if (IsNumber(*value_)) {
    return isolate->factory()->NumberToString(value_);
  }
  if (IsBigInt(*value_)) {
    return BigInt::ToString(isolate, Cast<BigInt>(value_));
  }
  DCHECK(IsString(*value_));
  return Cast<String>(value_);
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::IsNumber(), v8::internal::FactoryBase< Impl >::NumberToString(), v8::internal::string, v8::internal::BigInt::ToString(), and value_.
Referenced by FormatNumeric(), and ToFormattable().
Member Data Documentation
approx_
double v8::internal::IntlMathematicalValue::approx_ [private]
Definition at line 147 of file js-number-format.h.
Referenced by ToFormattable().
value_
Handle<Object> v8::internal::IntlMathematicalValue::value_ [private]
Definition at line 148 of file js-number-format.h.
Referenced by FormatNumeric(), IsNaN(), ToFormattable(), and ToString().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-number-format.h
/mnt/V8SourceCode/src/objects/js-number-format.cc