v8::internal::ObjectStatsVisitor Class Reference
Public Member Functions
ObjectStatsVisitor (Heap *heap, ObjectStatsCollectorImpl *live_collector, ObjectStatsCollectorImpl *dead_collector, ObjectStatsCollectorImpl::Phase phase)
void Visit (Tagged< HeapObject > obj)
Private Attributes
ObjectStatsCollectorImpl *const live_collector_
ObjectStatsCollectorImpl *const dead_collector_
Heap *const heap_
NonAtomicMarkingState *const marking_state_
ObjectStatsCollectorImpl::Phase phase_
Detailed Description
Definition at line 1157 of file object-stats.cc.
Constructor & Destructor Documentation
ObjectStatsVisitor()
v8::internal::ObjectStatsVisitor::ObjectStatsVisitor (Heap * heap, ObjectStatsCollectorImpl * live_collector, ObjectStatsCollectorImpl * dead_collector, ObjectStatsCollectorImpl::Phase phase) [inline]
Definition at line 1159 of file object-stats.cc.
      : live_collector_(live_collector),
        dead_collector_(dead_collector),
        heap_(heap),
        marking_state_(heap->non_atomic_marking_state()),
        phase_(phase) {}
Member Function Documentation
Visit()
void v8::internal::ObjectStatsVisitor::Visit (Tagged< HeapObject > obj) [inline]
Definition at line 1168 of file object-stats.cc.
                                     {
    if (MarkingHelper::IsMarkedOrAlwaysLive(heap_, marking_state_, obj)) {
      live_collector_->CollectStatistics(
          obj, phase_, ObjectStatsCollectorImpl::CollectFieldStats::kYes);
    } else {
      dead_collector_->CollectStatistics(
          obj, phase_, ObjectStatsCollectorImpl::CollectFieldStats::kNo);
    }
  }
References v8::internal::ObjectStatsCollectorImpl::CollectStatistics(), dead_collector_, heap_, v8::internal::MarkingHelper::IsMarkedOrAlwaysLive(), v8::internal::ObjectStatsCollectorImpl::kNo, v8::internal::ObjectStatsCollectorImpl::kYes, live_collector_, marking_state_, and phase_.
Referenced by v8::internal::anonymous_namespace{object-stats.cc}::IterateHeap().
Member Data Documentation
dead_collector_
ObjectStatsCollectorImpl* const v8::internal::ObjectStatsVisitor::dead_collector_ [private]
Definition at line 1180 of file object-stats.cc.
Referenced by Visit().
heap_
Heap* const v8::internal::ObjectStatsVisitor::heap_ [private]
Definition at line 1181 of file object-stats.cc.
Referenced by Visit().
live_collector_
ObjectStatsCollectorImpl* const v8::internal::ObjectStatsVisitor::live_collector_ [private]
Definition at line 1179 of file object-stats.cc.
Referenced by Visit().
marking_state_
NonAtomicMarkingState* const v8::internal::ObjectStatsVisitor::marking_state_ [private]
Definition at line 1182 of file object-stats.cc.
Referenced by Visit().
phase_
ObjectStatsCollectorImpl::Phase v8::internal::ObjectStatsVisitor::phase_ [private]
Definition at line 1183 of file object-stats.cc.
Referenced by Visit().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/object-stats.cc