v8::internal::FeedbackVectorSpec Class Reference
#include <feedback-vector.h>
Public Member Functions
FeedbackVectorSpec (Zone *zone)
int slot_count () const
int create_closure_slot_count () const
int AddCreateClosureParameterCount (uint16_t parameter_count)
uint16_t GetCreateClosureParameterCount (int index) const
FeedbackSlotKind GetKind (FeedbackSlot slot) const
FeedbackSlot AddCallICSlot ()
FeedbackSlot AddLoadICSlot ()
FeedbackSlot AddLoadGlobalICSlot (TypeofMode typeof_mode)
FeedbackSlot AddKeyedLoadICSlot ()
FeedbackSlot AddKeyedHasICSlot ()
FeedbackSlotKind GetStoreICSlot (LanguageMode language_mode)
FeedbackSlot AddStoreICSlot (LanguageMode language_mode)
FeedbackSlot AddDefineNamedOwnICSlot ()
FeedbackSlot AddDefineKeyedOwnICSlot ()
FeedbackSlot AddStoreGlobalICSlot (LanguageMode language_mode)
FeedbackSlotKind GetKeyedStoreICSlotKind (LanguageMode language_mode)
FeedbackSlot AddKeyedStoreICSlot (LanguageMode language_mode)
FeedbackSlot AddStoreInArrayLiteralICSlot ()
FeedbackSlot AddBinaryOpICSlot ()
FeedbackSlot AddCompareICSlot ()
FeedbackSlot AddForInSlot ()
FeedbackSlot AddInstanceOfSlot ()
FeedbackSlot AddTypeOfSlot ()
FeedbackSlot AddLiteralSlot ()
FeedbackSlot AddDefineKeyedOwnPropertyInLiteralICSlot ()
FeedbackSlot AddCloneObjectSlot ()
FeedbackSlot AddJumpLoopSlot ()
FeedbackSlot AddStringAddAndInternalizeICSlot ()
Private Member Functions
FeedbackSlot AddSlot (FeedbackSlotKind kind)
void append (FeedbackSlotKind kind)
Private Attributes
ZoneVector< FeedbackSlotKind > slot_kinds_
ZoneVector< uint16_t > create_closure_parameter_counts_
Friends
class SharedFeedbackSlot
Detailed Description
Definition at line 562 of file feedback-vector.h.
Constructor & Destructor Documentation
FeedbackVectorSpec()
v8::internal::FeedbackVectorSpec::FeedbackVectorSpec (Zone * zone) [inline], [explicit]
Definition at line 564 of file feedback-vector.h.
      : slot_kinds_(zone), create_closure_parameter_counts_(zone) {
    slot_kinds_.reserve(16);
  }
Member Function Documentation
AddBinaryOpICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddBinaryOpICSlot () [inline]
Definition at line 648 of file feedback-vector.h.
                                   {
    return AddSlot(FeedbackSlotKind::kBinaryOp);
  }
References v8::internal::kBinaryOp.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::FeedbackVector::NewWithOneBinarySlotForTesting(), and v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression().
AddCallICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddCallICSlot () [inline]
Definition at line 587 of file feedback-vector.h.
{ return AddSlot(FeedbackSlotKind::kCall); }
References v8::internal::kCall.
AddCloneObjectSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddCloneObjectSlot () [inline]
Definition at line 670 of file feedback-vector.h.
                                    {
    return AddSlot(FeedbackSlotKind::kCloneObject);
  }
References v8::internal::kCloneObject.
AddCompareICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddCompareICSlot () [inline]
Definition at line 652 of file feedback-vector.h.
                                  {
    return AddSlot(FeedbackSlotKind::kCompareOp);
  }
References v8::internal::kCompareOp.
Referenced by v8::internal::FeedbackVector::NewWithOneCompareSlotForTesting().
AddCreateClosureParameterCount()
int v8::internal::FeedbackVectorSpec::AddCreateClosureParameterCount (uint16_t parameter_count) [inline]
Definition at line 574 of file feedback-vector.h.
                                                               {
    create_closure_parameter_counts_.push_back(parameter_count);
    return create_closure_slot_count() - 1;
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::GetCachedCreateClosureSlot().
AddDefineKeyedOwnICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddDefineKeyedOwnICSlot () [inline]
Definition at line 623 of file feedback-vector.h.
                                         {
    return AddSlot(FeedbackSlotKind::kDefineKeyedOwn);
  }
References v8::internal::kDefineKeyedOwn.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), and v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization().
AddDefineKeyedOwnPropertyInLiteralICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddDefineKeyedOwnPropertyInLiteralICSlot () [inline]
Definition at line 666 of file feedback-vector.h.
                                                          {
    return AddSlot(FeedbackSlotKind::kDefineKeyedOwnPropertyInLiteral);
  }
References v8::internal::kDefineKeyedOwnPropertyInLiteral.
AddDefineNamedOwnICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddDefineNamedOwnICSlot () [inline]
Definition at line 617 of file feedback-vector.h.
                                         {
    return AddSlot(FeedbackSlotKind::kDefineNamedOwn);
  }
References v8::internal::kDefineNamedOwn.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassProperty().
AddForInSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddForInSlot () [inline]
Definition at line 656 of file feedback-vector.h.
{ return AddSlot(FeedbackSlotKind::kForIn); }
References v8::internal::kForIn.
AddInstanceOfSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddInstanceOfSlot () [inline]
Definition at line 658 of file feedback-vector.h.
                                   {
    return AddSlot(FeedbackSlotKind::kInstanceOf);
  }
References v8::internal::kInstanceOf.
AddJumpLoopSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddJumpLoopSlot () [inline]
Definition at line 674 of file feedback-vector.h.
                                 {
    return AddSlot(FeedbackSlotKind::kJumpLoop);
  }
References v8::internal::kJumpLoop.
Referenced by v8::internal::interpreter::LoopBuilder::JumpToHeader().
AddKeyedHasICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddKeyedHasICSlot () [inline]
Definition at line 603 of file feedback-vector.h.
                                   {
    return AddSlot(FeedbackSlotKind::kHasKeyed);
  }
References v8::internal::kHasKeyed.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildPrivateMethodIn().
AddKeyedLoadICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddKeyedLoadICSlot () [inline]
Definition at line 599 of file feedback-vector.h.
                                    {
    return AddSlot(FeedbackSlotKind::kLoadKeyed);
  }
References v8::internal::kLoadKeyed.
AddKeyedStoreICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddKeyedStoreICSlot (LanguageMode language_mode) [inline]
Definition at line 640 of file feedback-vector.h.
                                                               {
    return AddSlot(GetKeyedStoreICSlotKind(language_mode));
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildAssignment().
AddLiteralSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddLiteralSlot () [inline]
Definition at line 664 of file feedback-vector.h.
{ return AddSlot(FeedbackSlotKind::kLiteral); }
References v8::internal::kLiteral.
AddLoadGlobalICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddLoadGlobalICSlot (TypeofMode typeof_mode) [inline]
Definition at line 593 of file feedback-vector.h.
                                                           {
    return AddSlot(typeof_mode == TypeofMode::kInside
                       ? FeedbackSlotKind::kLoadGlobalInsideTypeof
                       : FeedbackSlotKind::kLoadGlobalNotInsideTypeof);
  }
References v8::internal::kInside, v8::internal::kLoadGlobalInsideTypeof, and v8::internal::kLoadGlobalNotInsideTypeof.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildVariableLoad(), and v8::internal::interpreter::BytecodeGenerator::GetCachedLoadGlobalICSlot().
AddLoadICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddLoadICSlot () [inline]
Definition at line 589 of file feedback-vector.h.
                               {
    return AddSlot(FeedbackSlotKind::kLoadProperty);
  }
References v8::internal::kLoadProperty.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildCallIteratorMethod(), v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment(), v8::internal::interpreter::BytecodeGenerator::BuildInstanceMemberInitialization(), v8::internal::interpreter::BytecodeGenerator::GetCachedLoadICSlot(), and v8::internal::interpreter::BytecodeGenerator::GetCachedLoadSuperICSlot().
AddSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddSlot (FeedbackSlotKind kind) [private]
Definition at line 26 of file feedback-vector.cc.
                                                              {
  int slot = slot_count();
  int entries_per_slot = FeedbackMetadata::GetSlotSize(kind);
  append(kind);
  for (int i = 1; i < entries_per_slot; i++) {
    append(FeedbackSlotKind::kInvalid);
  }
  return FeedbackSlot(slot);
}
References append(), v8::internal::FeedbackMetadata::GetSlotSize(), v8::internal::kInvalid, and slot_count().
Referenced by v8::internal::SharedFeedbackSlot::Get().
AddStoreGlobalICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddStoreGlobalICSlot (LanguageMode language_mode) [inline]
Definition at line 627 of file feedback-vector.h.
                                                                {
    static_assert(LanguageModeSize == 2);
    return AddSlot(is_strict(language_mode)
                       ? FeedbackSlotKind::kStoreGlobalStrict
                       : FeedbackSlotKind::kStoreGlobalSloppy);
  }
References v8::internal::is_strict(), v8::internal::kStoreGlobalSloppy, v8::internal::kStoreGlobalStrict, and v8::internal::LanguageModeSize.
Referenced by v8::internal::interpreter::BytecodeGenerator::GetCachedStoreGlobalICSlot().
AddStoreICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddStoreICSlot (LanguageMode language_mode) [inline]
Definition at line 613 of file feedback-vector.h.
                                                          {
    return AddSlot(GetStoreICSlot(language_mode));
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::interpreter::BytecodeGenerator::GetCachedStoreICSlot().
AddStoreInArrayLiteralICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddStoreInArrayLiteralICSlot () [inline]
Definition at line 644 of file feedback-vector.h.
                                              {
    return AddSlot(FeedbackSlotKind::kStoreInArrayLiteral);
  }
References v8::internal::kStoreInArrayLiteral.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDestructuringArrayAssignment().
AddStringAddAndInternalizeICSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddStringAddAndInternalizeICSlot () [inline]
Definition at line 678 of file feedback-vector.h.
                                                  {
    return AddSlot(FeedbackSlotKind::kStringAddAndInternalize);
  }
References v8::internal::kStringAddAndInternalize.
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitArithmeticExpression().
AddTypeOfSlot()
FeedbackSlot v8::internal::FeedbackVectorSpec::AddTypeOfSlot () [inline]
Definition at line 662 of file feedback-vector.h.
{ return AddSlot(FeedbackSlotKind::kTypeOf); }
References v8::internal::kTypeOf.
append()
void v8::internal::FeedbackVectorSpec::append (FeedbackSlotKind kind) [inline], [private]
Definition at line 692 of file feedback-vector.h.
{ slot_kinds_.push_back(kind); }
Referenced by AddSlot().
create_closure_slot_count()
int v8::internal::FeedbackVectorSpec::create_closure_slot_count () const [inline]
Definition at line 570 of file feedback-vector.h.
                                        {
    return static_cast<int>(create_closure_parameter_counts_.size());
  }
Referenced by v8::internal::FeedbackMetadata::New().
GetCreateClosureParameterCount()
uint16_t v8::internal::FeedbackVectorSpec::GetCreateClosureParameterCount (int index) const [inline]
Definition at line 579 of file feedback-vector.h.
                                                           {
    return create_closure_parameter_counts_.at(index);
  }
References v8::internal::index.
Referenced by v8::internal::FeedbackMetadata::New().
GetKeyedStoreICSlotKind()
FeedbackSlotKind v8::internal::FeedbackVectorSpec::GetKeyedStoreICSlotKind (LanguageMode language_mode) [inline]
Definition at line 634 of file feedback-vector.h.
                                                                       {
    static_assert(LanguageModeSize == 2);
    return is_strict(language_mode) ? FeedbackSlotKind::kSetKeyedStrict
                                    : FeedbackSlotKind::kSetKeyedSloppy;
  }
References v8::internal::is_strict(), v8::internal::kSetKeyedSloppy, v8::internal::kSetKeyedStrict, and v8::internal::LanguageModeSize.
GetKind()
FeedbackSlotKind v8::internal::FeedbackVectorSpec::GetKind (FeedbackSlot slot) const [inline]
Definition at line 583 of file feedback-vector.h.
                                                    {
    return slot_kinds_.at(slot.ToInt());
  }
References v8::internal::FeedbackSlot::ToInt().
Referenced by v8::internal::FeedbackMetadata::New(), and v8::internal::FeedbackMetadata::SpecDiffersFrom().
GetStoreICSlot()
FeedbackSlotKind v8::internal::FeedbackVectorSpec::GetStoreICSlot (LanguageMode language_mode) [inline]
Definition at line 607 of file feedback-vector.h.
                                                              {
    static_assert(LanguageModeSize == 2);
    return is_strict(language_mode) ? FeedbackSlotKind::kSetNamedStrict
                                    : FeedbackSlotKind::kSetNamedSloppy;
  }
References v8::internal::is_strict(), v8::internal::kSetNamedSloppy, v8::internal::kSetNamedStrict, and v8::internal::LanguageModeSize.
slot_count()
int v8::internal::FeedbackVectorSpec::slot_count () const [inline]
Definition at line 569 of file feedback-vector.h.
{ return static_cast<int>(slot_kinds_.size()); }
Referenced by AddSlot(), v8::internal::FeedbackMetadata::New(), and v8::internal::FeedbackMetadata::SpecDiffersFrom().
Friends And Related Function Documentation
SharedFeedbackSlot
friend class SharedFeedbackSlot [friend]
Definition at line 699 of file feedback-vector.h.
Member Data Documentation
create_closure_parameter_counts_
ZoneVector<uint16_t> v8::internal::FeedbackVectorSpec::create_closure_parameter_counts_ [private]
Definition at line 697 of file feedback-vector.h.
slot_kinds_
ZoneVector<FeedbackSlotKind> v8::internal::FeedbackVectorSpec::slot_kinds_ [private]
Definition at line 695 of file feedback-vector.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/feedback-vector.h
/mnt/V8SourceCode/src/objects/feedback-vector.cc