v8::base::TimeDelta Class Reference
#include <time.h>
Public Member Functions
constexpr TimeDelta ()
constexpr bool IsZero () const
constexpr bool IsMax () const
constexpr bool IsMin () const
int InDays () const
int InHours () const
int InMinutes () const
double InSecondsF () const
int64_t InSeconds () const
double InMillisecondsF () const
int64_t InMilliseconds () const
int64_t InMillisecondsRoundedUp () const
int64_t InMicroseconds () const
int64_t InNanoseconds () const
struct mach_timespec ToMachTimespec () const
struct timespec ToTimespec () const
constexpr TimeDelta operator+ (const TimeDelta &other) const
constexpr TimeDelta operator- (const TimeDelta &other) const
constexpr TimeDelta & operator+= (const TimeDelta &other)
constexpr TimeDelta & operator-= (const TimeDelta &other)
constexpr TimeDelta operator- () const
double TimesOf (const TimeDelta &other) const
double PercentOf (const TimeDelta &other) const
TimeDelta operator* (int64_t a) const
TimeDelta operator/ (int64_t a) const
TimeDelta & operator*= (int64_t a)
TimeDelta & operator/= (int64_t a)
int64_t operator/ (const TimeDelta &other) const
constexpr auto operator<=> (const TimeDelta &) const =default
Static Public Member Functions
static constexpr TimeDelta FromDays (int days)
static constexpr TimeDelta FromHours (int hours)
static constexpr TimeDelta FromMinutes (int minutes)
static constexpr TimeDelta FromSeconds (int64_t seconds)
static constexpr TimeDelta FromMilliseconds (int64_t milliseconds)
static constexpr TimeDelta FromMicroseconds (int64_t microseconds)
static constexpr TimeDelta FromNanoseconds (int64_t nanoseconds)
static constexpr TimeDelta FromSecondsD (double seconds)
static constexpr TimeDelta FromMillisecondsD (double milliseconds)
static constexpr TimeDelta Max ()
static constexpr TimeDelta Min ()
static TimeDelta FromMachTimespec (struct mach_timespec ts)
static TimeDelta FromTimespec (struct timespec ts)
Private Member Functions
constexpr TimeDelta (int64_t delta)
Static Private Member Functions
static constexpr TimeDelta FromDouble (double value)
Private Attributes
int64_t delta_
Friends
template<class TimeClass >
class time_internal::TimeBase
void swap (TimeDelta a, TimeDelta b)
Detailed Description
Definition at line 70 of file time.h.
Constructor & Destructor Documentation
TimeDelta() [1/2]
constexpr v8::base::TimeDelta::TimeDelta () [inline], [constexpr]
Definition at line 72 of file time.h.
: delta_(0) {}
Referenced by FromDouble(), Max(), and Min().
TimeDelta() [2/2]
constexpr v8::base::TimeDelta::TimeDelta (int64_t delta) [inline], [explicit], [constexpr], [private]
Definition at line 206 of file time.h.
: delta_(delta) {}
Member Function Documentation
FromDays()
static constexpr TimeDelta v8::base::TimeDelta::FromDays (int days) [inline], [static], [constexpr]
Definition at line 75 of file time.h.
                                                {
    return TimeDelta(days * TimeConstants::kMicrosecondsPerDay);
  }
References v8::base::TimeConstants::kMicrosecondsPerDay.
FromDouble()
constexpr TimeDelta v8::base::TimeDelta::FromDouble (double value) [inline], [static], [constexpr], [private]
Definition at line 213 of file time.h.
                                                      {
  return TimeDelta(saturated_cast<int64_t>(value));
}
References TimeDelta(), and v8::internal::value.
FromHours()
static constexpr TimeDelta v8::base::TimeDelta::FromHours (int hours) [inline], [static], [constexpr]
Definition at line 78 of file time.h.
                                                  {
    return TimeDelta(hours * TimeConstants::kMicrosecondsPerHour);
  }
References v8::base::TimeConstants::kMicrosecondsPerHour.
FromMachTimespec()
static TimeDelta v8::base::TimeDelta::FromMachTimespec (struct mach_timespec ts) [static]
FromMicroseconds()
static constexpr TimeDelta v8::base::TimeDelta::FromMicroseconds (int64_t microseconds) [inline], [static], [constexpr]
Definition at line 90 of file time.h.
                                                                    {
    return TimeDelta(microseconds);
  }
References v8::internal::microseconds.
Referenced by v8::internal::CpuProfile::CheckSubsample(), v8::internal::CpuProfilesCollection::GetCommonSamplingInterval(), cppgc::internal::StatsCollector::marking_time(), v8::base::time_internal::TimeBase< TimeClass >::operator-(), v8::DelayedTasksPlatform::DelayedTask::Run(), v8::internal::SamplingThread::Run(), v8::DelayedTasksPlatform::DelayedIdleTask::Run(), v8::DelayedTasksPlatform::DelayedJob::Run(), v8::CpuProfiler::SetSamplingInterval(), v8::base::time_internal::TimeBase< TimeClass >::since_origin(), v8::internal::TracingCpuProfilerImpl::StartProfiling(), v8::internal::BaseTimedHistogramScope::Stop(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerCachingAfterTimeout(), cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObjectImpl(), v8::platform::DelayedTaskQueue::TryGetNext(), cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBuffer(), and v8::platform::DefaultForegroundTaskRunner::WaitForTaskLocked().
FromMilliseconds()
static constexpr TimeDelta v8::base::TimeDelta::FromMilliseconds (int64_t milliseconds) [inline], [static], [constexpr]
Definition at line 87 of file time.h.
                                                                    {
    return TimeDelta(milliseconds * TimeConstants::kMicrosecondsPerMillisecond);
  }
References v8::base::TimeConstants::kMicrosecondsPerMillisecond.
Referenced by v8::platform::TaskQueue::BlockUntilQueueEmptyForTesting(), v8::internal::anonymous_namespace{builtins-atomics-synchronization.cc}::GetTimeoutDelta(), v8::internal::SamplingEventsProcessor::Run(), v8::internal::OptimizingCompileTaskExecutor::RunCompilationJob(), v8::internal::wasm::gdb_server::Target::Suspend(), cppgc::internal::Sweeper::SweeperImpl::SweepInForegroundTaskImpl(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerCachingAfterTimeout(), v8::internal::IncrementalMarking::TryInitializeTaskTimeout(), v8::internal::wasm::WasmExecutionTimer::WasmExecutionTimer(), and v8::internal::wasm::WasmInterpreterRuntime::WasmStackCheck().
FromMillisecondsD()
static constexpr TimeDelta v8::base::TimeDelta::FromMillisecondsD (double milliseconds) [inline], [static], [constexpr]
Definition at line 100 of file time.h.
                                                                    {
    return FromDouble(milliseconds *
                      TimeConstants::kMicrosecondsPerMillisecond);
  }
References v8::base::TimeConstants::kMicrosecondsPerMillisecond.
Referenced by v8::internal::GCTracer::AddCompactionEvent(), v8::internal::GCTracer::AddIncrementalMarkingStep(), v8::Shell::GetTracingTimestampFromPerformanceTimestamp(), v8::internal::IdleTaskOnContextDispose::RunInternal(), v8::internal::IncrementalMarking::TryInitializeTaskTimeout(), and v8::internal::IdleTaskOnContextDispose::TryRunMinorGC().
FromMinutes()
static constexpr TimeDelta v8::base::TimeDelta::FromMinutes (int minutes) [inline], [static], [constexpr]
Definition at line 81 of file time.h.
                                                      {
    return TimeDelta(minutes * TimeConstants::kMicrosecondsPerMinute);
  }
References v8::base::TimeConstants::kMicrosecondsPerMinute.
FromNanoseconds()
static constexpr TimeDelta v8::base::TimeDelta::FromNanoseconds (int64_t nanoseconds) [inline], [static], [constexpr]
Definition at line 93 of file time.h.
                                                                  {
    return TimeDelta(nanoseconds / TimeConstants::kNanosecondsPerMicrosecond);
  }
References v8::base::TimeConstants::kNanosecondsPerMicrosecond, and v8::internal::nanoseconds.
Referenced by v8::internal::FutexEmulation::WaitAsync(), and v8::internal::FutexEmulation::WaitSync().
FromSeconds()
static constexpr TimeDelta v8::base::TimeDelta::FromSeconds (int64_t seconds) [inline], [static], [constexpr]
Definition at line 84 of file time.h.
                                                          {
    return TimeDelta(seconds * TimeConstants::kMicrosecondsPerSecond);
  }
References v8::base::TimeConstants::kMicrosecondsPerSecond, and v8::internal::seconds.
Referenced by v8::internal::PagePool::AddLarge(), v8::internal::GCTracer::NotifyMarkingStart(), and v8::internal::PagePool::ReleaseOnTearDown().
FromSecondsD()
static constexpr TimeDelta v8::base::TimeDelta::FromSecondsD (double seconds) [inline], [static], [constexpr]
Definition at line 97 of file time.h.
                                                          {
    return FromDouble(seconds * TimeConstants::kMicrosecondsPerSecond);
  }
References v8::base::TimeConstants::kMicrosecondsPerSecond, and v8::internal::seconds.
FromTimespec()
static TimeDelta v8::base::TimeDelta::FromTimespec (struct timespec ts) [static]
InDays()
int v8::base::TimeDelta::InDays () const
Definition at line 186 of file time.cc.
                            {
  if (IsMax()) {
    // Preserve max to prevent overflow.
    return std::numeric_limits<int>::max();
  }
  return static_cast<int>(delta_ / Time::kMicrosecondsPerDay);
}
References delta_, IsMax(), and v8::base::TimeConstants::kMicrosecondsPerDay.
InHours()
int v8::base::TimeDelta::InHours () const
Definition at line 194 of file time.cc.
                             {
  if (IsMax()) {
    // Preserve max to prevent overflow.
    return std::numeric_limits<int>::max();
  }
  return static_cast<int>(delta_ / Time::kMicrosecondsPerHour);
}
References delta_, IsMax(), and v8::base::TimeConstants::kMicrosecondsPerHour.
InMicroseconds()
int64_t v8::base::TimeDelta::InMicroseconds () const
Definition at line 251 of file time.cc.
                                        {
  if (IsMax()) {
    // Preserve max to prevent overflow.
    return std::numeric_limits<int64_t>::max();
  }
  return delta_;
}
References delta_, and IsMax().
Referenced by v8::internal::TimedHistogram::AddTimedSample(), v8::internal::wasm::InstanceBuilder::Build(), v8::internal::CpuProfile::CpuProfile(), v8::internal::wasm::DecodeWasmModule(), v8::base::ElapsedTimer::Elapsed(), v8::internal::CpuProfile::FinishProfile(), v8::internal::CpuProfilesCollection::GetCommonSamplingInterval(), v8::CpuProfile::GetEndTime(), v8::CpuProfile::GetSampleTimestamp(), v8::CpuProfile::GetStartTime(), cppgc::internal::StatsCollector::NotifySweepingCompleted(), v8::internal::TickSample::print(), v8::internal::TimedHistogram::RecordAbandon(), v8::internal::TurbofanCompilationJob::RecordCompilationStats(), v8::internal::NestedTimedHistogramScope::RecordLongTaskTime(), v8::internal::GCTracer::ReportFullCycleToRecorder(), v8::internal::GCTracer::ReportYoungCycleToRecorder(), v8::base::ElapsedTimer::Restart(), v8::internal::CpuProfileJSONSerializer::SerializeImpl(), v8::internal::HeapSnapshotJSONSerializer::SerializeSamples(), v8::internal::CpuProfileJSONSerializer::SerializeTimeDeltas(), v8::base::OS::Sleep(), v8::base::PreciseSleepTimer::Sleep(), v8::internal::AggregatableHistogramTimer::Stop(), v8::internal::V8FileLogger::Time(), v8::internal::FutexEmulation::WaitSync(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompileLazyTimingScope::~CompileLazyTimingScope().
InMilliseconds()
int64_t v8::base::TimeDelta::InMilliseconds () const
Definition at line 234 of file time.cc.
                                        {
  if (IsMax()) {
    // Preserve max to prevent overflow.
    return std::numeric_limits<int64_t>::max();
  }
  return delta_ / Time::kMicrosecondsPerMillisecond;
}
References delta_, IsMax(), and v8::base::TimeConstants::kMicrosecondsPerMillisecond.
Referenced by v8::internal::TimedHistogram::AddTimedSample(), v8::internal::TimedHistogram::RecordAbandon(), v8::internal::MemoryMeasurement::ReportResults(), v8::internal::anonymous_namespace{gc-tracer.cc}::TruncateToMs(), and v8::internal::ETWJITInterface::EtwIsolateCaptureStateMonitor::WaitFor().
InMillisecondsF()
double v8::base::TimeDelta::InMillisecondsF () const
Definition at line 226 of file time.cc.
                                        {
  if (IsMax()) {
    // Preserve max to prevent overflow.
    return std::numeric_limits<double>::infinity();
  }
  return static_cast<double>(delta_) / Time::kMicrosecondsPerMillisecond;
}
References delta_, IsMax(), and v8::base::TimeConstants::kMicrosecondsPerMillisecond.
Referenced by cppgc::internal::MarkerBase::AdvanceMarkingWithLimits(), v8::internal::Compiler::CompileSharedWithBaseline(), v8::internal::SnapshotCompression::Compress(), anonymous_namespace{mksnapshot.cc}::CreateSnapshotDataBlob(), v8::internal::GCTracer::current_scope(), heap::base::SmoothedBytesAndDuration::Decay(), v8::internal::SnapshotCompression::Decompress(), v8::internal::CodeSerializer::Deserialize(), v8::internal::ContextDeserializer::DeserializeContext(), v8::internal::ReadOnlyDeserializer::DeserializeIntoIsolate(), v8::internal::StartupDeserializer::DeserializeIntoIsolate(), v8::internal::Deoptimizer::DoComputeOutputFrames(), v8::internal::OptimizedCompilationJob::execute_in_ms(), v8::internal::OptimizedCompilationJob::finalize_in_ms(), v8::internal::anonymous_namespace{code-serializer.cc}::FinalizeDeserialization(), v8::internal::AsmJsCompilationJob::FinalizeJobImpl(), v8::internal::CodeSerializer::FinishOffThreadDeserialize(), v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), v8::internal::Genesis::Genesis(), heap::base::IncrementalMarkingSchedule::GetNextIncrementalStepDuration(), v8::Shell::GetTimestamp(), cppgc::internal::ConcurrentMarkerBase::IncreaseMarkingPriorityIfNeeded(), v8::internal::GCTracer::IncrementalMarkingSpeedInBytesPerMillisecond(), v8::internal::Isolate::Init(), v8::internal::baseline::BaselineCompilerTask::Install(), v8::internal::AsmJs::InstantiateAsmWasm(), v8::internal::anonymous_namespace{compiler.cc}::LogUnoptimizedCompilation(), v8::internal::ParserBase< Impl >::ParseArrowFunctionLiteral(), v8::internal::Parser::ParseFunction(), v8::internal::Parser::ParseFunctionLiteral(), v8::internal::PreParser::ParseFunctionLiteral(), v8::internal::Parser::ParseProgram(), cppgc::internal::Sweeper::SweeperImpl::PerformSweepOnMutatorThread(), v8::internal::OptimizedCompilationJob::prepare_in_ms(), v8::internal::GCTracer::PrintNVP(), v8::internal::Heap::PrintShortHeapStatistics(), v8::internal::TurbofanCompilationJob::RecordCompilationStats(), v8::internal::TurbofanCompilationJob::RecordFunctionCompilation(), v8::internal::GCTracer::RecordGCSumCounters(), v8::internal::GCTracer::RecordMutatorUtilization(), v8::internal::IdleTaskOnContextDispose::RunInternal(), v8::internal::RUNTIME_FUNCTION(), v8::internal::CodeSerializer::Serialize(), v8::internal::HeapSnapshotJSONSerializer::Serialize(), v8::internal::IncrementalMarking::Step(), v8::internal::CollectionBarrier::StopTimeToCollectionTimer(), v8::D8Console::TimeEnd(), v8::D8Console::TimeLog(), v8::D8Console::TimeStamp(), v8::internal::IdleTaskOnContextDispose::TryRunMinorGC(), heap::base::SmoothedBytesAndDuration::Update(), v8::internal::MemoryBalancer::UpdateAllocationRate(), v8::internal::MemoryBalancer::UpdateGCSpeed(), v8::internal::Snapshot::VerifyChecksum(), anonymous_namespace{mksnapshot.cc}::WarmUpSnapshotDataBlob(), and v8::internal::WriteLine().
InMillisecondsRoundedUp()
int64_t v8::base::TimeDelta::InMillisecondsRoundedUp () const
Definition at line 242 of file time.cc.
                                                 {
  if (IsMax()) {
    // Preserve max to prevent overflow.
    return std::numeric_limits<int64_t>::max();
  }
  return (delta_ + Time::kMicrosecondsPerMillisecond - 1) /
         Time::kMicrosecondsPerMillisecond;
}
References delta_, IsMax(), and v8::base::TimeConstants::kMicrosecondsPerMillisecond.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::TriggerCachingAfterTimeout().
InMinutes()
int v8::base::TimeDelta::InMinutes () const
Definition at line 202 of file time.cc.
                               {
  if (IsMax()) {
    // Preserve max to prevent overflow.
    return std::numeric_limits<int>::max();
  }
  return static_cast<int>(delta_ / Time::kMicrosecondsPerMinute);
}
References delta_, IsMax(), and v8::base::TimeConstants::kMicrosecondsPerMinute.
InNanoseconds()
int64_t v8::base::TimeDelta::InNanoseconds () const
Definition at line 259 of file time.cc.
                                       {
  if (IsMax()) {
    // Preserve max to prevent overflow.
    return std::numeric_limits<int64_t>::max();
  }
  return delta_ * Time::kNanosecondsPerMicrosecond;
}
References delta_, IsMax(), and v8::base::TimeConstants::kNanosecondsPerMicrosecond.
Referenced by v8::base::ConditionVariable::WaitFor().
InSeconds()
int64_t v8::base::TimeDelta::InSeconds () const
Definition at line 218 of file time.cc.
                                   {
  if (IsMax()) {
    // Preserve max to prevent overflow.
    return std::numeric_limits<int64_t>::max();
  }
  return delta_ / Time::kMicrosecondsPerSecond;
}
References delta_, IsMax(), and v8::base::TimeConstants::kMicrosecondsPerSecond.
InSecondsF()
double v8::base::TimeDelta::InSecondsF () const
Definition at line 210 of file time.cc.
                                   {
  if (IsMax()) {
    // Preserve max to prevent overflow.
    return std::numeric_limits<double>::infinity();
  }
  return static_cast<double>(delta_) / Time::kMicrosecondsPerSecond;
}
References delta_, IsMax(), and v8::base::TimeConstants::kMicrosecondsPerSecond.
Referenced by v8::internal::PagePool::AddLarge(), v8_inspector::V8HeapProfilerAgentImpl::onTimerImpl(), v8_inspector::V8ProfilerAgentImpl::startPreciseCoverage(), v8_inspector::V8HeapProfilerAgentImpl::startTrackingHeapObjectsInternal(), v8_inspector::V8ProfilerAgentImpl::takePreciseCoverage(), v8_inspector::V8ProfilerAgentImpl::triggerPreciseCoverageDeltaUpdate(), and v8::internal::FutexEmulation::WaitAsync().
IsMax()
constexpr bool v8::base::TimeDelta::IsMax () const [inline], [constexpr]
Definition at line 119 of file time.h.
                               {
    return delta_ == std::numeric_limits<int64_t>::max();
  }
Referenced by InDays(), InHours(), InMicroseconds(), InMilliseconds(), InMillisecondsF(), InMillisecondsRoundedUp(), InMinutes(), InNanoseconds(), InSeconds(), and InSecondsF().
IsMin()
constexpr bool v8::base::TimeDelta::IsMin () const [inline], [constexpr]
Definition at line 122 of file time.h.
                               {
    return delta_ == std::numeric_limits<int64_t>::min();
  }
IsZero()
constexpr bool v8::base::TimeDelta::IsZero () const [inline], [constexpr]
Definition at line 116 of file time.h.
{ return delta_ == 0; }
Referenced by v8::internal::CpuProfile::CheckSubsample(), v8::internal::GCTracer::IncrementalMarkingSpeedInBytesPerMillisecond(), cppgc::internal::StatsCollector::NotifySweepingCompleted(), v8::internal::GCTracer::RecordGCPhasesHistograms(), v8::internal::GCTracer::RecordMutatorUtilization(), v8::internal::GCTracer::ReportFullCycleToRecorder(), v8::internal::GCTracer::ReportYoungCycleToRecorder(), v8::internal::GCTracer::StopObservablePause(), and heap::base::SmoothedBytesAndDuration::Update().
Max()
constexpr TimeDelta v8::base::TimeDelta::Max () [static], [constexpr]
Definition at line 218 of file time.h.
                                   {
  return TimeDelta(std::numeric_limits<int64_t>::max());
}
References TimeDelta().
Referenced by v8::internal::CppHeap::CollectGarbageForTesting(), cppgc::internal::MarkerBase::FinishMarking(), v8::internal::anonymous_namespace{incremental-marking.cc}::GetMaxDuration(), v8::internal::MarkCompactCollector::MarkTransitiveClosureLinear(), v8::internal::MarkCompactCollector::PerformWrapperTracing(), v8::internal::MinorMarkSweepCollector::PerformWrapperTracing(), v8::internal::MarkCompactCollector::ProcessEphemerons(), v8::internal::TimedHistogram::RecordAbandon(), cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObjectImpl(), and cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBuffer().
Min()
constexpr TimeDelta v8::base::TimeDelta::Min () [static], [constexpr]
Definition at line 223 of file time.h.
                                   {
  return TimeDelta(std::numeric_limits<int64_t>::min());
}
References TimeDelta().
operator*()
TimeDelta v8::base::TimeDelta::operator* (int64_t a) const [inline]
Definition at line 177 of file time.h.
                                       {
    return TimeDelta(delta_ * a);
  }
operator*=()
TimeDelta& v8::base::TimeDelta::operator*= (int64_t a) [inline]
Definition at line 183 of file time.h.
                                   {
    delta_ *= a;
    return *this;
  }
operator+()
constexpr TimeDelta v8::base::TimeDelta::operator+ (const TimeDelta & other) const [inline], [constexpr]
Definition at line 151 of file time.h.
                                                              {
    return TimeDelta(delta_ + other.delta_);
  }
References delta_.
operator+=()
constexpr TimeDelta& v8::base::TimeDelta::operator+= (const TimeDelta & other) [inline], [constexpr]
Definition at line 158 of file time.h.
                                                          {
    delta_ += other.delta_;
    return *this;
  }
References delta_.
operator-() [1/2]
constexpr TimeDelta v8::base::TimeDelta::operator- () const [inline], [constexpr]
Definition at line 166 of file time.h.
{ return TimeDelta(-delta_); }
operator-() [2/2]
constexpr TimeDelta v8::base::TimeDelta::operator- (const TimeDelta & other) const [inline], [constexpr]
Definition at line 154 of file time.h.
                                                              {
    return TimeDelta(delta_ - other.delta_);
  }
References delta_.
operator-=()
constexpr TimeDelta& v8::base::TimeDelta::operator-= (const TimeDelta & other) [inline], [constexpr]
Definition at line 162 of file time.h.
                                                          {
    delta_ -= other.delta_;
    return *this;
  }
References delta_.
operator/() [1/2]
int64_t v8::base::TimeDelta::operator/ (const TimeDelta & other) const [inline]
Definition at line 191 of file time.h.
                                                  {
    return delta_ / other.delta_;
  }
References delta_.
operator/() [2/2]
TimeDelta v8::base::TimeDelta::operator/ (int64_t a) const [inline]
Definition at line 180 of file time.h.
                                       {
    return TimeDelta(delta_ / a);
  }
operator/=()
TimeDelta& v8::base::TimeDelta::operator/= (int64_t a) [inline]
Definition at line 187 of file time.h.
                                   {
    delta_ /= a;
    return *this;
  }
operator<=>()
constexpr auto v8::base::TimeDelta::operator<=> (const TimeDelta &) const [constexpr], [default]
PercentOf()
double v8::base::TimeDelta::PercentOf (const TimeDelta & other) const [inline]
Definition at line 171 of file time.h.
                                                 {
    return TimesOf(other) * 100.0;
  }
Referenced by v8::internal::WriteLine().
TimesOf()
double v8::base::TimeDelta::TimesOf (const TimeDelta & other) const [inline]
Definition at line 168 of file time.h.
                                               {
    return static_cast<double>(delta_) / static_cast<double>(other.delta_);
  }
References delta_.
Referenced by v8::internal::wasm::WasmExecutionTimer::EndInterval().
ToMachTimespec()
struct mach_timespec v8::base::TimeDelta::ToMachTimespec () const
ToTimespec()
struct timespec v8::base::TimeDelta::ToTimespec () const
Friends And Related Function Documentation
swap
void swap (TimeDelta a, TimeDelta b) [friend]
Definition at line 197 of file time.h.
{ std::swap(a.delta_, b.delta_); }
time_internal::TimeBase
template<class TimeClass >
friend class time_internal::TimeBase [friend]
Definition at line 202 of file time.h.
Member Data Documentation
delta_
int64_t v8::base::TimeDelta::delta_ [private]
Definition at line 209 of file time.h.
Referenced by InDays(), InHours(), InMicroseconds(), InMilliseconds(), InMillisecondsF(), InMillisecondsRoundedUp(), InMinutes(), InNanoseconds(), InSeconds(), InSecondsF(), operator+(), v8::base::time_internal::TimeBase< TimeClass >::operator+(), operator+=(), operator-(), v8::base::time_internal::TimeBase< TimeClass >::operator-(), operator-=(), operator/(), and TimesOf().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/time.h
/mnt/V8SourceCode/src/base/platform/time.cc