v8::internal::maglev::StoreSignedIntDataViewElement Class Reference
#include <maglev-ir.h>
Public Member Functions
StoreSignedIntDataViewElement (uint64_t bitfield, ExternalArrayType type)
Input & object_input ()
Input & index_input ()
Input & value_input ()
Input & is_little_endian_input ()
bool is_little_endian_constant ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
ExternalArrayType type () const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::CanWrite()
static constexpr Base::InputTypes kInputTypes
static constexpr int kObjectIndex = 0
static constexpr int kIndexIndex = 1
static constexpr int kValueIndex = 2
static constexpr int kIsLittleEndianIndex = 3
Private Types
using Base = FixedInputNodeT< 4, StoreSignedIntDataViewElement >
Private Attributes
ExternalArrayType type_
Additional Inherited Members
Detailed Description
Definition at line 8849 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::StoreSignedIntDataViewElement::Base = FixedInputNodeT<4, StoreSignedIntDataViewElement> [private]
Definition at line 8851 of file maglev-ir.h.
Constructor & Destructor Documentation
StoreSignedIntDataViewElement()
v8::internal::maglev::StoreSignedIntDataViewElement::StoreSignedIntDataViewElement (uint64_t bitfield, ExternalArrayType type) [inline], [explicit]
Definition at line 8854 of file maglev-ir.h.
      : Base(bitfield), type_(type) {
    DCHECK(type == ExternalArrayType::kExternalInt8Array ||
           type == ExternalArrayType::kExternalInt16Array ||
           type == ExternalArrayType::kExternalInt32Array);
  }
References DCHECK, v8::internal::kExternalInt16Array, v8::internal::kExternalInt32Array, v8::internal::kExternalInt8Array, and v8::internal::tracing::type.
Member Function Documentation
GenerateCode()
void v8::internal::maglev::StoreSignedIntDataViewElement::GenerateCode (MaglevAssembler * , const ProcessingState &)
index_input()
Input& v8::internal::maglev::StoreSignedIntDataViewElement::index_input () [inline]
Definition at line 8872 of file maglev-ir.h.
{ return input(kIndexIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
is_little_endian_constant()
bool v8::internal::maglev::StoreSignedIntDataViewElement::is_little_endian_constant () [inline]
Definition at line 8876 of file maglev-ir.h.
                                   {
    return IsConstantNode(is_little_endian_input().node()->opcode());
  }
References v8::internal::maglev::IsConstantNode().
is_little_endian_input()
Input& v8::internal::maglev::StoreSignedIntDataViewElement::is_little_endian_input () [inline]
Definition at line 8874 of file maglev-ir.h.
{ return input(kIsLittleEndianIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
object_input()
Input& v8::internal::maglev::StoreSignedIntDataViewElement::object_input () [inline]
Definition at line 8871 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::StoreSignedIntDataViewElement::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 8882 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::StoreSignedIntDataViewElement::SetValueLocationConstraints ()
type()
ExternalArrayType v8::internal::maglev::StoreSignedIntDataViewElement::type () const [inline]
Definition at line 8884 of file maglev-ir.h.
{ return type_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
value_input()
Input& v8::internal::maglev::StoreSignedIntDataViewElement::value_input () [inline]
Definition at line 8873 of file maglev-ir.h.
{ return input(kValueIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kIndexIndex
constexpr int v8::internal::maglev::StoreSignedIntDataViewElement::kIndexIndex = 1 [static], [constexpr]
Definition at line 8868 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::StoreSignedIntDataViewElement::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kInt32,
      ValueRepresentation::kInt32, ValueRepresentation::kTagged}
Definition at line 8863 of file maglev-ir.h.
kIsLittleEndianIndex
constexpr int v8::internal::maglev::StoreSignedIntDataViewElement::kIsLittleEndianIndex = 3 [static], [constexpr]
Definition at line 8870 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::StoreSignedIntDataViewElement::kObjectIndex = 0 [static], [constexpr]
Definition at line 8867 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::StoreSignedIntDataViewElement::kProperties = OpProperties::CanWrite() [static], [constexpr]
Definition at line 8862 of file maglev-ir.h.
kValueIndex
constexpr int v8::internal::maglev::StoreSignedIntDataViewElement::kValueIndex = 2 [static], [constexpr]
Definition at line 8869 of file maglev-ir.h.
type_
ExternalArrayType v8::internal::maglev::StoreSignedIntDataViewElement::type_ [private]
Definition at line 8887 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h