v8::internal::HeapLayout Class Reference
#include <heap-layout.h>
Static Public Member Functions
static bool InReadOnlySpace (Tagged< HeapObject > object)
static bool InYoungGeneration (Tagged< Object > object)
static bool InYoungGeneration (Tagged< HeapObject > object)
static bool InYoungGeneration (Tagged< MaybeObject > object)
static bool InYoungGeneration (const HeapObjectLayout *object)
static bool InYoungGeneration (const MemoryChunk *chunk, Tagged< HeapObject > object)
static bool InWritableSharedSpace (Tagged< HeapObject > object)
static bool InAnySharedSpace (Tagged< HeapObject > object)
static bool InCodeSpace (Tagged< HeapObject > object)
static bool InTrustedSpace (Tagged< HeapObject > object)
static bool InBlackAllocatedPage (Tagged< HeapObject > object)
static bool IsOwnedByAnyHeap (Tagged< HeapObject > object)
static bool IsSelfForwarded (Tagged< HeapObject > object)
static bool IsSelfForwarded (Tagged< HeapObject > object, PtrComprCageBase cage_base)
static bool IsSelfForwarded (Tagged< HeapObject > object, MapWord map_word)
Static Private Member Functions
static bool InYoungGenerationForStickyMarkbits (const MemoryChunk *chunk, Tagged< HeapObject > object)
static void CheckYoungGenerationConsistency (const MemoryChunk *chunk)
Detailed Description
Definition at line 22 of file heap-layout.h.
Member Function Documentation
CheckYoungGenerationConsistency()
void v8::internal::HeapLayout::CheckYoungGenerationConsistency (const MemoryChunk * chunk) [static], [private]
Definition at line 25 of file heap-layout.cc.
                                                                         {
  // Young generation objects should only be found in to space when the GC is
  // not currently running.
  // If the object is in the young generation, then it is safe to get to the
  // containing Heap.
#ifdef DEBUG
  const MemoryChunkMetadata* metadata = chunk->Metadata();
  SLOW_DCHECK(metadata->IsWritable());
  Heap* heap = metadata->heap();
  SLOW_DCHECK(heap != nullptr);
  DCHECK_IMPLIES(heap->gc_state() == Heap::NOT_IN_GC,
                 chunk->IsFlagSet(MemoryChunk::TO_PAGE));
#endif // DEBUG
}
References DCHECK_IMPLIES, v8::internal::MemoryChunkMetadata::heap(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunkMetadata::IsWritable(), v8::internal::MemoryChunk::Metadata(), v8::internal::Heap::NOT_IN_GC, SLOW_DCHECK, and v8::internal::MemoryChunk::TO_PAGE.
Referenced by InYoungGeneration().
InAnySharedSpace()
bool v8::internal::HeapLayout::InAnySharedSpace (Tagged< HeapObject > object) [inline], [static]
Definition at line 72 of file heap-layout-inl.h.
                                                           {
  if (HeapLayout::InReadOnlySpace(object)) {
    return true;
  }
  return HeapLayout::InWritableSharedSpace(object);
}
References InReadOnlySpace(), and InWritableSharedSpace().
Referenced by v8::internal::StringForwardingTable::AddExternalResourceAndHash(), v8::internal::StringForwardingTable::AddForwardString(), v8::internal::Heap::AddRetainedMaps(), v8::internal::Object::CanBeHeldWeakly(), v8::internal::Map::CanTransition(), v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::CheckForSharedObject(), v8::internal::Factory::ComputeInternalizationStrategyForString(), v8::internal::Factory::ComputeSharingStrategyForString(), v8::internal::JSSharedStruct::CreateInstanceMap(), v8::internal::WriteBarrier::CurrentMarkingBarrier(), v8::internal::DependentCode::DeoptimizeDependencyGroups(), v8::internal::WasmTrustedInstanceData::GetOrCreateFuncRef(), v8::internal::WasmDispatchTable::Grow(), v8::internal::String::IsShared(), v8::internal::IsShared(), v8::internal::StringTable::LookupKey(), v8::internal::DependentCode::MarkCodeForDeoptimization(), v8::internal::MarkingBarrier::MarkValueShared(), v8::internal::Factory::NewEnumCache(), v8::internal::requires(), v8::internal::SlotAccessorForHeapObject::WriteIndirectPointerTo(), and v8::internal::ValueSerializer::WriteJSReceiver().
InBlackAllocatedPage()
bool v8::internal::HeapLayout::InBlackAllocatedPage (Tagged< HeapObject > object) [inline], [static]
Definition at line 89 of file heap-layout-inl.h.
                                                               {
  DCHECK(v8_flags.black_allocated_pages);
  return MemoryChunk::FromHeapObject(object)->GetFlags() &
         MemoryChunk::BLACK_ALLOCATED;
}
References v8::internal::MemoryChunk::BLACK_ALLOCATED, v8::internal::DCHECK(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::GetFlags(), and v8::internal::v8_flags.
Referenced by v8::internal::MarkingBarrier::MarkValue(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorsForMap(), and v8::internal::MarkingBarrier::Write().
InCodeSpace()
bool v8::internal::HeapLayout::InCodeSpace (Tagged< HeapObject > object) [inline], [static]
Definition at line 80 of file heap-layout-inl.h.
                                                      {
  return MemoryChunk::FromHeapObject(object)->InCodeSpace();
}
References v8::internal::MemoryChunk::FromHeapObject(), and v8::internal::MemoryChunk::InCodeSpace().
Referenced by v8::internal::HeapProfiler::GetDetachedJSWrapperObjects(), v8::internal::V8HeapExplorer::IsEssentialObject(), v8::internal::WriteBarrier::Marking(), v8::internal::SamplingHeapProfiler::SampleObject(), and v8::internal::EvacuateNewToOldSpacePageVisitor::Visit().
InReadOnlySpace()
bool v8::internal::HeapLayout::InReadOnlySpace (Tagged< HeapObject > object) [inline], [static]
Definition at line 20 of file heap-layout-inl.h.
                                                          {
  return MemoryChunk::FromHeapObject(object)->InReadOnlySpace();
}
References v8::internal::MemoryChunk::FromHeapObject(), and v8::internal::MemoryChunk::InReadOnlySpace().
Referenced by v8::internal::BuiltinsConstantsTableBuilder::AddObject(), v8::UnboundScript::BindToCurrentContext(), v8::internal::anonymous_namespace{ic.cc}::CanCacheCloneTargetMapTransition(), v8::internal::Map::CanTransition(), v8::ScriptCompiler::CompileUnboundInternal(), v8::ScriptCompiler::CreateCodeCache(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CreateExternalizableString(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::DeleteDeadObjects(), v8::internal::DependentCode::DeoptimizeDependencyGroups(), v8::internal::compiler::CompilationDependencies::DependOnEmptyContextExtension(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::DeterminePromotees(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency::EmptyContextExtensionDependency(), v8::internal::TemplateInfo::EnsureHasSerialNumber(), v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::EvaluateSubgraph(), v8::UnboundScript::GetColumnNumber(), v8::UnboundScript::GetId(), v8::UnboundScript::GetLineNumber(), v8::UnboundScript::GetScriptName(), v8::UnboundScript::GetSourceMappingURL(), v8::UnboundModuleScript::GetSourceMappingURL(), v8::UnboundScript::GetSourceURL(), v8::UnboundModuleScript::GetSourceURL(), v8::Script::GetUnboundScript(), v8::internal::Code::has_instruction_stream(), InAnySharedSpace(), v8::internal::WriteBarrier::IsImmortalImmovableHeapObject(), v8::internal::IsShared(), v8::internal::String::MakeExternal(), v8::internal::DependentCode::MarkCodeForDeoptimization(), v8::internal::MarkingBarrier::MarkValue(), v8::internal::MarkingBarrier::MarkValueLocal(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::RUNTIME_FUNCTION(), v8::internal::FunctionTemplateInfo::SealAndPrepareForPromotionToReadOnly(), v8::internal::ObjectTemplateInfo::SealAndPrepareForPromotionToReadOnly(), v8::internal::Map::SetInstanceDescriptors(), v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::SizeForSnapshot(), v8::internal::String::SupportsExternalization(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::Verify(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorsForMap(), v8::internal::MarkingBarrier::Write(), and v8::internal::MarkingBarrier::WriteWithoutHost().
InTrustedSpace()
bool v8::internal::HeapLayout::InTrustedSpace (Tagged< HeapObject > object) [inline], [static]
Definition at line 85 of file heap-layout-inl.h.
                                                         {
  return MemoryChunk::FromHeapObject(object)->InTrustedSpace();
}
References v8::internal::MemoryChunk::FromHeapObject(), and v8::internal::MemoryChunk::InTrustedSpace().
Referenced by v8::internal::V8HeapExplorer::IsEssentialObject(), v8::internal::ExistingCodeLogger::LogCompiledFunctions(), v8::internal::InstructionStream::raw_code(), and v8::internal::SamplingHeapProfiler::SampleObject().
InWritableSharedSpace()
bool v8::internal::HeapLayout::InWritableSharedSpace (Tagged< HeapObject > object) [inline], [static]
Definition at line 67 of file heap-layout-inl.h.
                                                                {
  return MemoryChunk::FromHeapObject(object)->InWritableSharedSpace();
}
References v8::internal::MemoryChunk::FromHeapObject(), and v8::internal::MemoryChunk::InWritableSharedSpace().
Referenced by v8::internal::anonymous_namespace{wasm-objects.cc}::CanonicalizeHeapNumber(), v8::internal::wasm::anonymous_namespace{wasm-objects.cc}::CheckExpectedSharedness(), v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::CheckForSharedObject(), v8::internal::HeapObject::CheckRequiredAlignment(), v8::internal::WriteBarrier::CombinedGenerationalAndSharedBarrierSlow(), v8::internal::WriteBarrier::CombinedGenerationalAndSharedEphemeronBarrierSlow(), v8::internal::wasm::anonymous_namespace{wasm-objects.cc}::ConvertToSharedIfExpected(), v8::internal::ExternalString::DisposeResource(), v8::internal::anonymous_namespace{heap-write-barrier.cc}::ForRangeImpl(), v8::Object::GetConstructorName(), v8::internal::IterateAndScavengePromotedObjectsVisitor::HandleSlot(), InAnySharedSpace(), v8::internal::WriteBarrier::IndirectPointerMarkingFromCode(), v8::internal::MarkingBarrier::IsCompacting(), v8::internal::IsJSObjectThatCanBeTrackedAsPrototype(), v8::internal::IsShared(), v8::internal::ClientRootVisitor< Visitor >::IsSharedHeapObject(), v8::internal::ClientObjectVisitor< Visitor >::IsSharedHeapObject(), v8::internal::MarkCompactCollector::IsUnmarkedSharedHeapObject(), v8::internal::String::MakeExternal(), v8::internal::Map::MapPrint(), v8::internal::WriteBarrier::MarkingFromCode(), v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::MarkPointerTableEntry(), v8::internal::MarkingBarrier::MarkValue(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), v8::internal::HeapObject::RequiredAlignment(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Map::SetPrototype(), v8::internal::WriteBarrier::SharedFromCode(), v8::internal::WriteBarrier::SharedMarkingFromCode(), v8::internal::StringForwardingTable::Block::UpdateAfterYoungEvacuation(), v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VerifyHost(), v8::internal::ClientObjectVisitor< Visitor >::VisitCodeTarget(), v8::internal::RecordMigratedSlotVisitor::VisitCodeTarget(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitEphemeronHashTable(), v8::internal::ClientObjectVisitor< Visitor >::VisitInstructionStreamPointer(), v8::internal::ClientRootVisitor< Visitor >::VisitRunningCode(), v8::internal::MarkingBarrier::Write(), and v8::internal::MarkingBarrier::WriteWithoutHost().
InYoungGeneration() [1/5]
bool v8::internal::HeapLayout::InYoungGeneration (const HeapObjectLayout * object) [inline], [static]
Definition at line 62 of file heap-layout-inl.h.
                                                                 {
  return InYoungGeneration(Tagged<HeapObject>(object));
}
References InYoungGeneration().
InYoungGeneration() [2/5]
bool v8::internal::HeapLayout::InYoungGeneration (const MemoryChunk * chunk, Tagged< HeapObject > object) [inline], [static]
Definition at line 25 of file heap-layout-inl.h.
                                                              {
  if constexpr (v8_flags.single_generation.value()) {
    return false;
  }
  if constexpr (v8_flags.sticky_mark_bits.value()) {
    return InYoungGenerationForStickyMarkbits(chunk, object);
  }
  const bool in_young_generation = chunk->InYoungGeneration();
#ifdef DEBUG
  if (in_young_generation) {
    CheckYoungGenerationConsistency(chunk);
  }
#endif // DEBUG
  return in_young_generation;
}
References CheckYoungGenerationConsistency(), v8::internal::MemoryChunk::InYoungGeneration(), InYoungGenerationForStickyMarkbits(), and v8::internal::v8_flags.
InYoungGeneration() [3/5]
bool v8::internal::HeapLayout::InYoungGeneration (Tagged< HeapObject > object) [inline], [static]
Definition at line 57 of file heap-layout-inl.h.
                                                            {
  return InYoungGeneration(MemoryChunk::FromHeapObject(object), object);
}
References v8::internal::MemoryChunk::FromHeapObject(), and InYoungGeneration().
InYoungGeneration() [4/5]
bool v8::internal::HeapLayout::InYoungGeneration (Tagged< MaybeObject > object) [inline], [static]
Definition at line 51 of file heap-layout-inl.h.
                                                             {
  Tagged<HeapObject> heap_object;
  return object.GetHeapObject(&heap_object) && InYoungGeneration(heap_object);
}
References v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), and InYoungGeneration().
InYoungGeneration() [5/5]
bool v8::internal::HeapLayout::InYoungGeneration (Tagged< Object > object) [inline], [static]
Definition at line 43 of file heap-layout-inl.h.
                                                        {
  if (object.IsSmi()) {
    return false;
  }
  return InYoungGeneration(Cast<HeapObject>(object));
}
References v8::internal::IsSmi().
Referenced by v8::internal::Heap::ExternalStringTable::AddString(), v8::internal::Scavenger::CheckAndScavengeObject(), v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::CheckForSharedObject(), v8::internal::Heap::ExternalStringTable::CleanUpAll(), v8::internal::Heap::ExternalStringTable::CleanUpYoung(), v8::internal::OrderedHashTable< Derived, entrysize >::Clear(), v8::internal::anonymous_namespace{global-handles.cc}::ClearListOfYoungNodesImpl(), v8::internal::MinorMarkSweepCollector::ClearNonLiveReferences(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::YoungStringForwardingTableCleaner::ClearNonLiveYoungObjects(), v8::internal::WriteBarrier::CombinedGenerationalAndSharedBarrierSlow(), v8::internal::WriteBarrier::CombinedGenerationalAndSharedEphemeronBarrierSlow(), v8::internal::WriteBarrier::CombinedWriteBarrierInternal(), v8::internal::Factory::ComputeInternalizationStrategyForString(), v8::internal::compiler::JSNativeContextSpecialization::Concatenate(), v8::internal::EternalHandles::Create(), v8::internal::Heap::CreateEarlyReadOnlyMapsAndObjects(), v8::internal::JSArrayBuffer::CreateExtension(), v8::internal::Heap::CreateReadOnlyObjects(), v8::internal::Scavenger::EvacuateShortcutCandidate(), v8::internal::Scavenger::EvacuateThinString(), v8::internal::WriteBarrier::ForExternalPointer(), v8::internal::WriteBarrier::ForRange(), v8::internal::anonymous_namespace{heap-write-barrier.cc}::ForRangeImpl(), v8::internal::WriteBarrier::GenerationalBarrierForCodeSlow(), v8::internal::WriteBarrier::GenerationalBarrierForCppHeapPointer(), v8::internal::WriteBarrier::GenerationalForRelocInfo(), v8::internal::Map::GetInitialElements(), v8::internal::WriteBarrier::GetWriteBarrierModeForObject(), v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::HandleHeapObject(), v8::internal::InstructionStream::Initialize(), v8::internal::Heap::InOldSpace(), InYoungGeneration(), v8::internal::compiler::JSObjectRef::IsElementsTenured(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::IsUnmarkedObjectInYoungGeneration(), v8::internal::TracedHandles::IterateAndMarkYoungRootsWithOldHosts(), v8::internal::anonymous_namespace{traced-handles.cc}::MarkObject(), v8::internal::MarkingBarrier::MarkValueLocal(), v8::internal::anonymous_namespace{heap.cc}::MayContainRecordedSlots(), v8::internal::TracedHandles::Move(), v8::internal::Heap::MustBeInSharedOldSpace(), v8::internal::TracedHandles::NeedsToBeRemembered(), v8::internal::TracedHandles::NeedsTrackingInYoungNodes(), v8::internal::anonymous_namespace{global-handles.cc}::NeedsTrackingInYoungNodes(), v8::internal::Heap::NotifyObjectLayoutChange(), v8::internal::EternalHandles::PostGarbageCollectionProcessing(), v8::internal::Serializer::PutRoot(), v8::internal::InstructionStream::raw_code(), v8::internal::EphemeronRememberedSet::RecordEphemeronKeyWrite(), v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd(), v8::internal::JSFinalizationRegistry::RemoveUnregisterToken(), v8::internal::requires(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Scavenger::ScavengeObject(), v8::internal::SwissNameDictionary::ShallowCopy(), v8::internal::String::SupportsExternalization(), v8::internal::StringForwardingTable::Block::UpdateAfterYoungEvacuation(), v8::internal::PretenuringHandler::UpdateAllocationSite(), v8::internal::JSObject::UpdateAllocationSite(), v8::internal::TracedHandles::UpdateListOfYoungNodes(), v8::internal::anonymous_namespace{global-handles.cc}::UpdateListOfYoungNodesImpl(), v8::internal::anonymous_namespace{scavenger.cc}::GlobalHandlesWeakRootsUpdatingVisitor::UpdatePointer(), v8::internal::Heap::ExternalStringTable::UpdateYoungReferences(), v8::internal::Heap::ExternalStringTable::Verify(), v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VerifyHost(), v8::internal::Heap::ExternalStringTable::VerifyYoung(), v8::internal::RecordMigratedSlotVisitor::VisitCodeTarget(), v8::internal::RecordMigratedSlotVisitor::VisitEphemeron(), v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitEphemeron(), v8::internal::anonymous_namespace{sweeper.cc}::PromotedPageRecordMigratedSlotVisitor::VisitEphemeronHashTable(), v8::internal::ScavengeVisitor::VisitExternalPointer(), v8::internal::ScavengeVisitor::VisitHeapObjectImpl(), v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitObjectViaSlot(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::VisitObjectWithCppHeapPointerField(), v8::internal::Serializer::ObjectSerializer::VisitPointers(), v8::internal::InternalizedStringTableCleaner::VisitRootPointers(), and v8::internal::MarkingBarrier::Write().
InYoungGenerationForStickyMarkbits()
bool v8::internal::HeapLayout::InYoungGenerationForStickyMarkbits (const MemoryChunk * chunk, Tagged< HeapObject > object) [static], [private]
Definition at line 16 of file heap-layout.cc.
                                                                               {
  CHECK(v8_flags.sticky_mark_bits.value());
  return !chunk->IsOnlyOldOrMajorMarkingOn() &&
         !MarkingBitmap::MarkBitFromAddress(object.address())
              .template Get<AccessMode::ATOMIC>();
}
References CHECK, v8::internal::MemoryChunk::IsOnlyOldOrMajorMarkingOn(), v8::internal::MarkingBitmap::MarkBitFromAddress(), and v8::internal::v8_flags.
Referenced by InYoungGeneration().
IsOwnedByAnyHeap()
bool v8::internal::HeapLayout::IsOwnedByAnyHeap (Tagged< HeapObject > object) [inline], [static]
Definition at line 96 of file heap-layout-inl.h.
                                                           {
  return MemoryChunk::FromHeapObject(object)->GetHeap();
}
References v8::internal::MemoryChunk::FromHeapObject(), and v8::internal::MemoryChunk::GetHeap().
Referenced by v8::internal::TaggedMember< T, CompressionScheme >::WriteBarrier().
IsSelfForwarded() [1/3]
bool v8::internal::HeapLayout::IsSelfForwarded (Tagged< HeapObject > object) [static]
Definition at line 42 of file heap-layout.cc.
                                                          {
  return IsSelfForwarded(object, GetPtrComprCageBase(object));
}
References v8::internal::GetPtrComprCageBase().
Referenced by v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::FilterLargeObject(), v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::FilterNormalObject(), v8::internal::anonymous_namespace{scavenger.cc}::ObjectPinningVisitorBase< ConcreteVisitor >::HandleHeapObject(), v8::internal::anonymous_namespace{scavenger.cc}::PreciseObjectPinningVisitor::HandlePointer(), IsSelfForwarded(), v8::internal::PretenuringHandler::MergeAllocationSitePretenuringFeedback(), v8::internal::anonymous_namespace{scavenger.cc}::RestorePinnedObjects(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::Scavenger::ScavengeObject(), v8::internal::IterateAndScavengePromotedObjectsVisitor::VisitEphemeron(), and v8::internal::anonymous_namespace{frames.cc}::VisitSpillSlot().
IsSelfForwarded() [2/3]
bool v8::internal::HeapLayout::IsSelfForwarded (Tagged< HeapObject > object, MapWord map_word) [static]
Definition at line 53 of file heap-layout.cc.
                                                                            {
  return map_word == MapWord::FromForwardingAddress(object, object);
}
References v8::internal::MapWord::FromForwardingAddress().
IsSelfForwarded() [3/3]
bool v8::internal::HeapLayout::IsSelfForwarded (Tagged< HeapObject > object, PtrComprCageBase cage_base) [static]
Definition at line 47 of file heap-layout.cc.
                                                             {
  return IsSelfForwarded(object, object->map_word(cage_base, kRelaxedLoad));
}
References IsSelfForwarded(), and v8::kRelaxedLoad.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap-layout.h
/mnt/V8SourceCode/src/heap/heap-layout-inl.h
/mnt/V8SourceCode/src/heap/heap-layout.cc