v8::internal::AllocationTracker::ScriptData Class Reference
Public Member Functions
ScriptData (Tagged< Script >, Isolate *, AllocationTracker *)
~ScriptData ()
String::LineEndsVector & line_ends ()
Static Private Member Functions
static void HandleWeakScript (const v8::WeakCallbackInfo< ScriptData > &)
Private Attributes
Global< debug::Script > script_
ScriptId script_id_
String::LineEndsVector line_ends_
AllocationTracker * tracker_
Detailed Description
Definition at line 148 of file allocation-tracker.h.
Constructor & Destructor Documentation
ScriptData()
v8::internal::AllocationTracker::ScriptData::ScriptData (Tagged< Script > script, Isolate * isolate, AllocationTracker * tracker)
Definition at line 228 of file allocation-tracker.cc.
    : script_id_(script->id()),
      line_ends_(Script::GetLineEnds(isolate, direct_handle(script, isolate))),
      tracker_(tracker) {
  DirectHandle<Script> script_direct_handle(script, isolate);
  auto local_script = ToApiHandle<debug::Script>(script_direct_handle);
  script_.Reset(reinterpret_cast<v8::Isolate*>(isolate), local_script);
  script_.SetWeak(this, &HandleWeakScript, v8::WeakCallbackType::kParameter);
}
References HandleWeakScript(), v8::kParameter, v8::internal::script, and script_.
 ScriptData()
v8::internal::AllocationTracker::ScriptData::~ScriptData ()
Definition at line 240 of file allocation-tracker.cc.
                                         {
  if (!script_.IsEmpty()) {
    script_.ClearWeak();
  }
}
Member Function Documentation
HandleWeakScript()
void v8::internal::AllocationTracker::ScriptData::HandleWeakScript (const v8::WeakCallbackInfo< ScriptData > & data) [static], [private]
Definition at line 246 of file allocation-tracker.cc.
                                                {
  ScriptData* script_data = reinterpret_cast<ScriptData*>(data.GetParameter());
  script_data->script_.ClearWeak();
  script_data->script_.Reset();
  script_data->tracker_->scripts_data_map_.erase(script_data->script_id_);
}
References v8::WeakCallbackInfo< T >::GetParameter(), script_, script_id_, v8::internal::AllocationTracker::scripts_data_map_, and tracker_.
Referenced by ScriptData().
line_ends()
String::LineEndsVector& v8::internal::AllocationTracker::ScriptData::line_ends () [inline]
Definition at line 152 of file allocation-tracker.h.
{ return line_ends_; }
References line_ends_.
Member Data Documentation
line_ends_
String::LineEndsVector v8::internal::AllocationTracker::ScriptData::line_ends_ [private]
Definition at line 158 of file allocation-tracker.h.
Referenced by line_ends().
script_
Global<debug::Script> v8::internal::AllocationTracker::ScriptData::script_ [private]
Definition at line 156 of file allocation-tracker.h.
Referenced by HandleWeakScript(), and ScriptData().
script_id_
ScriptId v8::internal::AllocationTracker::ScriptData::script_id_ [private]
Definition at line 157 of file allocation-tracker.h.
Referenced by HandleWeakScript().
tracker_
AllocationTracker* v8::internal::AllocationTracker::ScriptData::tracker_ [private]
Definition at line 159 of file allocation-tracker.h.
Referenced by HandleWeakScript().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/allocation-tracker.h
/mnt/V8SourceCode/src/profiler/allocation-tracker.cc