v8::internal::GlobalDictionaryShape Class Reference
#include <dictionary.h>
Static Public Member Functions
static bool IsMatch (DirectHandle< Name > key, Tagged< Object > other)
static uint32_t HashForObject (ReadOnlyRoots roots, Tagged< Object > object)
template<typename Dictionary >
static PropertyDetails DetailsAt (Tagged< Dictionary > dict, InternalIndex entry)
template<typename Dictionary >
static void DetailsAtPut (Tagged< Dictionary > dict, InternalIndex entry, PropertyDetails value)
static Tagged< Object > Unwrap (Tagged< Object > key)
Static Public Attributes
static const bool kMatchNeedsHoleCheck = true
static const int kPrefixSize = 2
static const int kEntrySize = 1
Additional Inherited Members
Detailed Description
Definition at line 315 of file dictionary.h.
Member Function Documentation
DetailsAt()
template<typename Dictionary >
PropertyDetails v8::internal::GlobalDictionaryShape::DetailsAt (Tagged< Dictionary > dict, InternalIndex entry) [inline], [static]
Definition at line 372 of file dictionary-inl.h.
                                                                      {
  DCHECK(entry.is_found());
  return dict->CellAt(entry)->property_details();
}
References v8::internal::DCHECK(), and v8::internal::InternalIndex::is_found().
DetailsAtPut()
template<typename Dictionary >
void v8::internal::GlobalDictionaryShape::DetailsAtPut (Tagged< Dictionary > dict, InternalIndex entry, PropertyDetails value) [inline], [static]
Definition at line 379 of file dictionary-inl.h.
                                                                {
  DCHECK(entry.is_found());
  dict->CellAt(entry)->UpdatePropertyDetailsExceptCellType(value);
}
References v8::internal::DCHECK(), v8::internal::InternalIndex::is_found(), and v8::internal::value.
HashForObject()
uint32_t v8::internal::GlobalDictionaryShape::HashForObject (ReadOnlyRoots roots, Tagged< Object > object) [inline], [static]
Definition at line 352 of file dictionary-inl.h.
                                                                    {
  return Cast<PropertyCell>(other)->name()->hash();
}
IsMatch()
bool v8::internal::GlobalDictionaryShape::IsMatch (DirectHandle< Name > key, Tagged< Object > other) [inline], [static]
Definition at line 345 of file dictionary-inl.h.
                                                          {
  DCHECK(IsUniqueName(*key));
  DCHECK(IsUniqueName(Cast<PropertyCell>(other)->name()));
  return *key == Cast<PropertyCell>(other)->name();
}
References v8::internal::DCHECK(), v8::internal::IsUniqueName(), v8::internal::key, and v8::internal::name.
Unwrap()
Tagged< Object > v8::internal::GlobalDictionaryShape::Unwrap (Tagged< Object > key) [inline], [static]
Definition at line 206 of file dictionary-inl.h.
                                                                  {
  return Cast<PropertyCell>(object)->name();
}
Member Data Documentation
kEntrySize
const int v8::internal::GlobalDictionaryShape::kEntrySize = 1 [static]
Definition at line 323 of file dictionary.h.
kMatchNeedsHoleCheck
const bool v8::internal::GlobalDictionaryShape::kMatchNeedsHoleCheck = true [static]
Definition at line 321 of file dictionary.h.
kPrefixSize
const int v8::internal::GlobalDictionaryShape::kPrefixSize = 2 [static]
Definition at line 322 of file dictionary.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/dictionary.h
/mnt/V8SourceCode/src/objects/dictionary-inl.h