v8::internal::maglev::ForInNext Class Reference
#include <maglev-ir.h>
Public Member Functions
ForInNext (uint64_t bitfield, compiler::FeedbackSource &feedback)
compiler::FeedbackSource feedback () const
Input & context ()
Input & receiver ()
Input & cache_array ()
Input & cache_type ()
Input & cache_index ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::JSCall()
static constexpr Base::InputTypes kInputTypes
Private Types
using Base = FixedInputValueNodeT< 5, ForInNext >
Private Attributes
const compiler::FeedbackSource feedback_
Additional Inherited Members
Detailed Description
Definition at line 5310 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::ForInNext::Base = FixedInputValueNodeT<5, ForInNext> [private]
Definition at line 5311 of file maglev-ir.h.
Constructor & Destructor Documentation
ForInNext()
v8::internal::maglev::ForInNext::ForInNext (uint64_t bitfield, compiler::FeedbackSource & feedback) [inline], [explicit]
Definition at line 5314 of file maglev-ir.h.
      : Base(bitfield), feedback_(feedback) {}
Member Function Documentation
cache_array()
Input& v8::internal::maglev::ForInNext::cache_array () [inline]
Definition at line 5327 of file maglev-ir.h.
{ return Node::input(2); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
cache_index()
Input& v8::internal::maglev::ForInNext::cache_index () [inline]
Definition at line 5329 of file maglev-ir.h.
{ return Node::input(4); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
cache_type()
Input& v8::internal::maglev::ForInNext::cache_type () [inline]
Definition at line 5328 of file maglev-ir.h.
{ return Node::input(3); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context()
Input& v8::internal::maglev::ForInNext::context () [inline]
Definition at line 5325 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
feedback()
compiler::FeedbackSource v8::internal::maglev::ForInNext::feedback () const [inline]
Definition at line 5323 of file maglev-ir.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::ForInNext::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::ForInNext::MaxCallStackArgs () const
PrintParams()
void v8::internal::maglev::ForInNext::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 5334 of file maglev-ir.h.
{}
receiver()
Input& v8::internal::maglev::ForInNext::receiver () [inline]
Definition at line 5326 of file maglev-ir.h.
{ return Node::input(1); }
References v8::internal::maglev::NodeBase::input().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::ForInNext::SetValueLocationConstraints ()
Member Data Documentation
feedback_
const compiler::FeedbackSource v8::internal::maglev::ForInNext::feedback_ [private]
Definition at line 5337 of file maglev-ir.h.
Referenced by feedback().
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::ForInNext::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kTagged,
      ValueRepresentation::kTagged, ValueRepresentation::kTagged,
      ValueRepresentation::kTagged}
Definition at line 5318 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::ForInNext::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 5317 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h