v8::FunctionTemplate Class Reference
A FunctionTemplate is used to create functions at runtime.
#include <v8-template.h>
Public Member Functions
V8_WARN_UNUSED_RESULT MaybeLocal< Function > GetFunction (Local< Context > context)
Returns the unique function instance in the current execution context.
V8_WARN_UNUSED_RESULT MaybeLocal< Object > NewRemoteInstance ()
Similar to Context::NewRemoteContext, this creates an instance that isn't backed by an actual object.
void SetCallHandler (FunctionCallback callback, Local< Value > data=Local< Value >(), SideEffectType side_effect_type=SideEffectType::kHasSideEffect, const MemorySpan< const CFunction > &c_function_overloads={})
Set the call-handler callback for a FunctionTemplate.
void SetLength (int length)
Set the predefined length property for the FunctionTemplate.
Local< ObjectTemplate > InstanceTemplate ()
Get the InstanceTemplate.
void Inherit (Local< FunctionTemplate > parent)
Causes the function template to inherit from a parent function template.
Local< ObjectTemplate > PrototypeTemplate ()
A PrototypeTemplate is the template used to create the prototype object of the function created by this template.
void SetPrototypeProviderTemplate (Local< FunctionTemplate > prototype_provider)
A PrototypeProviderTemplate is another function template whose prototype property is used for this template.
void SetClassName (Local< String > name)
Set the class name of the FunctionTemplate.
void SetInterfaceName (Local< String > name)
Set the interface name of the FunctionTemplate.
void SetExceptionContext (ExceptionContext context)
Provides information on the type of FunctionTemplate for embedder exception handling.
void SetAcceptAnyReceiver (bool value)
When set to true, no access check will be performed on the receiver of a function call.
void ReadOnlyPrototype ()
Sets the ReadOnly flag in the attributes of the 'prototype' property of functions created from this FunctionTemplate to true.
void RemovePrototype ()
Removes the prototype property from functions created from this FunctionTemplate.
bool HasInstance (Local< Value > object)
Returns true if the given object is an instance of this function template.
bool IsLeafTemplateForApiObject (v8::Local< v8::Value > value) const
Returns true if the given value is an API object that was constructed by an instance of this function template (without checking for inheriting function templates).
void SealAndPrepareForPromotionToReadOnly ()
Seal the object and mark it for promotion to read only space during context snapshot creation.
Static Public Member Functions
static Local< FunctionTemplate > New (Isolate *isolate, FunctionCallback callback=nullptr, Local< Value > data=Local< Value >(), Local< Signature > signature=Local< Signature >(), int length=0, ConstructorBehavior behavior=ConstructorBehavior::kAllow, SideEffectType side_effect_type=SideEffectType::kHasSideEffect, const CFunction *c_function=nullptr, uint16_t instance_type=0, uint16_t allowed_receiver_instance_type_range_start=0, uint16_t allowed_receiver_instance_type_range_end=0)
Creates a function template.
static Local< FunctionTemplate > NewWithCFunctionOverloads (Isolate *isolate, FunctionCallback callback=nullptr, Local< Value > data=Local< Value >(), Local< Signature > signature=Local< Signature >(), int length=0, ConstructorBehavior behavior=ConstructorBehavior::kAllow, SideEffectType side_effect_type=SideEffectType::kHasSideEffect, const MemorySpan< const CFunction > &c_function_overloads={})
Creates a function template for multiple overloaded fast API calls.
static Local< FunctionTemplate > NewWithCache (Isolate *isolate, FunctionCallback callback, Local< Private > cache_property, Local< Value > data=Local< Value >(), Local< Signature > signature=Local< Signature >(), int length=0, SideEffectType side_effect_type=SideEffectType::kHasSideEffect)
Creates a function template backed/cached by a private property.
static FunctionTemplate * Cast (Data *data)
Private Member Functions
FunctionTemplate ()
Static Private Member Functions
static void CheckCast (Data *that)
Friends
class Context
class ObjectTemplate
Detailed Description
A FunctionTemplate is used to create functions at runtime.
There can only be one function created from a FunctionTemplate in a context. The lifetime of the created function is equal to the lifetime of the context. So in case the embedder needs to create temporary functions that can be collected using Scripts is preferred.
Any modification of a FunctionTemplate after first instantiation will trigger a crash.
A FunctionTemplate can have properties, these properties are added to the function object when it is created.
A FunctionTemplate has a corresponding instance template which is used to create object instances when the function is used as a constructor. Properties added to the instance template are added to each object instance.
A FunctionTemplate can have a prototype template. The prototype template is used to create the prototype object of the function.
The following example shows how to use a FunctionTemplate:
v8::Local<v8::FunctionTemplate> t = v8::FunctionTemplate::New(isolate);
t->Set(isolate, "func_property", v8::Number::New(isolate, 1));
v8::Local<v8::Template> proto_t = t->PrototypeTemplate();
proto_t->Set(isolate,
             "proto_method",
             v8::FunctionTemplate::New(isolate, InvokeCallback));
proto_t->Set(isolate, "proto_const", v8::Number::New(isolate, 2));
v8::Local<v8::ObjectTemplate> instance_t = t->InstanceTemplate();
instance_t->SetNativeDataProperty(
    String::NewFromUtf8Literal(isolate, "instance_accessor"),
    InstanceAccessorCallback);
instance_t->SetHandler(
    NamedPropertyHandlerConfiguration(PropertyHandlerCallback));
instance_t->Set(String::NewFromUtf8Literal(isolate, "instance_property"),
                Number::New(isolate, 3));
v8::Local<v8::Function> function = t->GetFunction();
v8::Local<v8::Object> instance = function->NewInstance();
Let's use `function` as the JS variable name of the function object and `instance` for the instance object created above. The function and the instance will have the following properties:
func_property in function == true;
function.func_property == 1;
function.prototype.proto_method() invokes 'InvokeCallback'
function.prototype.proto_const == 2;
instance instanceof function == true;
instance.instance_accessor calls 'InstanceAccessorCallback'
instance.instance_property == 3;
A FunctionTemplate can inherit from another one by calling the FunctionTemplate::Inherit method. The following graph illustrates the semantics of inheritance:
FunctionTemplate Parent -> Parent() . prototype -> { }
  ^ ^
  | Inherit(Parent) | .__proto__
  | |
FunctionTemplate Child -> Child() . prototype -> { }
A FunctionTemplate 'Child' inherits from 'Parent', the prototype object of the Child() function has proto pointing to the Parent() function's prototype object. An instance of the Child function has all properties on Parent's instance templates.
Let Parent be the FunctionTemplate initialized in the previous section and create a Child FunctionTemplate by:
Local<FunctionTemplate> parent = t;
Local<FunctionTemplate> child = FunctionTemplate::New();
child->Inherit(parent);
Local<Function> child_function = child->GetFunction();
Local<Object> child_instance = child_function->NewInstance();
The Child function and Child instance will have the following properties:
child_func.prototype.__proto__ == function.prototype;
child_instance.instance_accessor calls 'InstanceAccessorCallback'
child_instance.instance_property == 3;
The additional 'c_function' parameter refers to a fast API call, which must not trigger GC or JavaScript execution, or call into V8 in other ways. For more information how to define them, see include/v8-fast-api-calls.h. Please note that this feature is still experimental.
Definition at line 584 of file v8-template.h.
Constructor & Destructor Documentation
FunctionTemplate()
v8::FunctionTemplate::FunctionTemplate () [private]
Member Function Documentation
Cast()
FunctionTemplate * v8::FunctionTemplate::Cast (Data * data) [inline], [static]
Definition at line 1137 of file v8-template.h.
                                                   {
#ifdef V8_ENABLE_CHECKS
  CheckCast(data);
#endif
  return reinterpret_cast<FunctionTemplate*>(data);
}
References CheckCast().
CheckCast()
void v8::FunctionTemplate::CheckCast (Data * that) [static], [private]
Definition at line 7346 of file api.cc.
                                             {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsFunctionTemplateInfo(*obj), "v8::FunctionTemplate::Cast",
                  "Value is not a FunctionTemplate");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
Referenced by Cast().
GetFunction()
MaybeLocal< v8::Function > v8::FunctionTemplate::GetFunction (Local< Context > context)
Returns the unique function instance in the current execution context.
Definition at line 7358 of file api.cc.
                                                                           {
  PrepareForExecutionScope api_scope{context,
                                     RCCId::kAPI_FunctionTemplate_GetFunction};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto self = Utils::OpenDirectHandle(this);
  return api_scope.EscapeMaybe(i::ApiNatives::InstantiateFunction(
      i_isolate, i_isolate->native_context(), self));
}
References v8::internal::ApiNatives::InstantiateFunction(), v8::internal::Isolate::native_context(), and v8::Utils::OpenDirectHandle().
HasInstance()
bool v8::FunctionTemplate::HasInstance (Local< Value > object)
Returns true if the given object is an instance of this function template.
Definition at line 7394 of file api.cc.
                                                         {
  auto self = Utils::OpenDirectHandle(this);
  auto obj = Utils::OpenDirectHandle(*value);
  if (i::IsJSObject(*obj) && self->IsTemplateFor(i::Cast<i::JSObject>(*obj))) {
    return true;
  }
  if (i::IsJSGlobalProxy(*obj)) {
    // If it's a global proxy, then test with the global object. Note that the
    // inner global object may not necessarily be a JSGlobalObject.
    auto jsobj = i::Cast<i::JSObject>(*obj);
    i::PrototypeIterator iter(i::Isolate::Current(), jsobj->map());
    // The global proxy should always have a prototype, as it is a bug to call
    // this on a detached JSGlobalProxy.
    DCHECK(!iter.IsAtEnd());
    return self->IsTemplateFor(iter.GetCurrent<i::JSObject>());
  }
  return false;
}
References v8::internal::Isolate::Current(), DCHECK, v8::internal::PrototypeIterator::GetCurrent(), v8::internal::PrototypeIterator::IsAtEnd(), v8::Utils::OpenDirectHandle(), and v8::internal::value.
Inherit()
void v8::FunctionTemplate::Inherit (v8::Local< FunctionTemplate > value)
Causes the function template to inherit from a parent function template.
This means the function's prototype.__proto__ is set to the parent function's prototype.
Definition at line 1102 of file api.cc.
                                                              {
  auto info = Utils::OpenDirectHandle(this);
  EnsureNotPublished(info, "v8::FunctionTemplate::Inherit");
  i::Isolate* i_isolate = info->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  Utils::ApiCheck(
      i::IsUndefined(info->GetPrototypeProviderTemplate(), i_isolate),
      "v8::FunctionTemplate::Inherit", "Protoype provider must be empty");
  i::FunctionTemplateInfo::SetParentTemplate(i_isolate, info,
                                             Utils::OpenDirectHandle(*value));
}
References v8::Utils::ApiCheck(), v8::anonymous_namespace{api.cc}::EnsureNotPublished(), v8::Utils::OpenDirectHandle(), and v8::internal::value.
InstanceTemplate()
Local< ObjectTemplate > v8::FunctionTemplate::InstanceTemplate ()
Get the InstanceTemplate.
Definition at line 1313 of file api.cc.
                                                         {
  auto constructor = Utils::OpenDirectHandle(this, true);
  if (!Utils::ApiCheck(!constructor.is_null(),
                       "v8::FunctionTemplate::InstanceTemplate()",
                       "Reading from empty handle")) {
    return {};
  }
  i::Isolate* i_isolate = constructor->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  auto maybe_templ = constructor->GetInstanceTemplate();
  if (!i::IsUndefined(maybe_templ, i_isolate)) {
    return Utils::ToLocal(i::direct_handle(
        i::Cast<i::ObjectTemplateInfo>(maybe_templ), i_isolate));
  }
  constexpr bool do_not_cache = false;
  i::DirectHandle<i::ObjectTemplateInfo> templ =
      i_isolate->factory()->NewObjectTemplateInfo(constructor, do_not_cache);
  i::FunctionTemplateInfo::SetInstanceTemplate(i_isolate, constructor, templ);
  return Utils::ToLocal(templ);
}
References v8::Utils::ApiCheck(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Factory::NewObjectTemplateInfo(), and v8::Utils::OpenDirectHandle().
IsLeafTemplateForApiObject()
bool v8::FunctionTemplate::IsLeafTemplateForApiObject (v8::Local< v8::Value > value) const
Returns true if the given value is an API object that was constructed by an instance of this function template (without checking for inheriting function templates).
This is an experimental feature and may still change significantly.
Definition at line 7413 of file api.cc.
                                  {
  i::DisallowGarbageCollection no_gc;
  auto self = Utils::OpenDirectHandle(this);
  i::Tagged<i::Object> object = *Utils::OpenDirectHandle(*value);
  return self->IsLeafTemplateForApiObject(object);
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::Utils::OpenDirectHandle(), and v8::internal::value.
New()
Local< FunctionTemplate > v8::FunctionTemplate::New (Isolate * isolate, FunctionCallback callback = nullptr, v8::Local< Value > data = Local<Value>(), v8::Local< Signature > signature = Local<Signature>(), int length = 0, ConstructorBehavior behavior = ConstructorBehavior::kAllow, SideEffectType side_effect_type = SideEffectType::kHasSideEffect, const CFunction * c_function = nullptr, uint16_t instance_type = 0, uint16_t allowed_receiver_instance_type_range_start = 0, uint16_t allowed_receiver_instance_type_range_end = 0) [static]
Creates a function template.
Definition at line 1114 of file api.cc.
                                                       {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  // Changes to the environment cannot be captured in the snapshot. Expect no
  // function templates when the isolate is created for serialization.
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_FunctionTemplate_New);
  if (!Utils::ApiCheck(
          !c_function || behavior == ConstructorBehavior::kThrow,
          "FunctionTemplate::New",
          "Fast API calls are not supported for constructor functions")) {
    return {};
  }
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::FunctionTemplateInfo> templ = FunctionTemplateNew(
      i_isolate, callback, data, signature, length, behavior, false,
      Local<Private>(), side_effect_type,
      c_function ? MemorySpan<const CFunction>{c_function, 1}
                 : MemorySpan<const CFunction>{});
  if (instance_type) {
    if (!Utils::ApiCheck(
            base::IsInRange(static_cast<int>(instance_type),
                            i::Internals::kFirstEmbedderJSApiObjectType,
                            i::Internals::kLastEmbedderJSApiObjectType),
            "FunctionTemplate::New",
            "instance_type is outside the range of valid JSApiObject types")) {
      return {};
    }
    templ->SetInstanceType(instance_type);
  }
  if (allowed_receiver_instance_type_range_start ||
      allowed_receiver_instance_type_range_end) {
    if (!Utils::ApiCheck(i::Internals::kFirstEmbedderJSApiObjectType <=
                                 allowed_receiver_instance_type_range_start &&
                             allowed_receiver_instance_type_range_start <=
                                 allowed_receiver_instance_type_range_end &&
                             allowed_receiver_instance_type_range_end <=
                                 i::Internals::kLastEmbedderJSApiObjectType,
                         "FunctionTemplate::New",
                         "allowed receiver instance type range is outside the "
                         "range of valid JSApiObject types")) {
      return {};
    }
    templ->SetAllowedReceiverInstanceTypeRange(
        allowed_receiver_instance_type_range_start,
        allowed_receiver_instance_type_range_end);
  }
  return Utils::ToLocal(templ);
}
References v8::internal::allowed_receiver_instance_type_range_end, v8::Utils::ApiCheck(), v8::anonymous_namespace{api.cc}::FunctionTemplateNew(), v8::internal::Internals::kFirstEmbedderJSApiObjectType, v8::internal::Internals::kLastEmbedderJSApiObjectType, v8::kThrow, and v8::internal::length.
Referenced by v8::Shell::AddOSMethods(), v8::AsyncHooks::AsyncHooks(), v8::internal::ApiNatives::CreateAccessorFunctionTemplateInfo(), v8::Shell::CreateAsyncHookTemplate(), v8::Shell::CreateD8Template(), v8::CreateFastCAPIObject(), v8::Shell::CreateGlobalTemplate(), v8::Shell::CreateLeafInterfaceTypeTemplate(), v8::Shell::CreateNodeTemplates(), v8::Shell::CreatePerformanceTemplate(), v8::Shell::CreateRealmTemplate(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::CreateTemplate(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::CreateTemplate(), v8::Shell::CreateTestFastCApiTemplate(), v8::Shell::CreateWorkerTemplate(), v8::anonymous_namespace{api.cc}::EnsureConstructor(), v8::Worker::ExecuteInThread(), v8::internal::CpuTraceMarkExtension::GetNativeFunctionTemplate(), v8::internal::ExternalizeStringExtension::GetNativeFunctionTemplate(), v8::internal::GCExtension::GetNativeFunctionTemplate(), v8::internal::IgnitionStatisticsExtension::GetNativeFunctionTemplate(), v8::internal::StatisticsExtension::GetNativeFunctionTemplate(), v8::internal::TriggerFailureExtension::GetNativeFunctionTemplate(), v8::internal::VTuneDomainSupportExtension::GetNativeFunctionTemplate(), v8::internal::FuzzilliExtension::GetNativeFunctionTemplate(), v8::InspectorClient::InspectorClient(), v8::NewDOMFunctionTemplate(), v8::NewFunctionTemplate(), v8::internal::RUNTIME_FUNCTION(), and v8_inspector::V8Console::taskTemplate().
NewRemoteInstance()
MaybeLocal< v8::Object > v8::FunctionTemplate::NewRemoteInstance ()
Similar to Context::NewRemoteContext, this creates an instance that isn't backed by an actual object.
The InstanceTemplate of this FunctionTemplate must have access checks with handlers installed.
Definition at line 7367 of file api.cc.
                                                         {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = self->GetIsolateChecked();
  ApiRuntimeCallStatsScope rcs_scope(
      i_isolate, RCCId::kAPI_FunctionTemplate_NewRemoteInstance);
  i::HandleScope scope(i_isolate);
  i::DirectHandle<i::FunctionTemplateInfo> constructor =
      EnsureConstructor(i_isolate, *InstanceTemplate());
  Utils::ApiCheck(constructor->needs_access_check(),
                  "v8::FunctionTemplate::NewRemoteInstance",
                  "InstanceTemplate needs to have access checks enabled");
  i::DirectHandle<i::AccessCheckInfo> access_check_info(
      i::Cast<i::AccessCheckInfo>(constructor->GetAccessCheckInfo()),
      i_isolate);
  Utils::ApiCheck(
      access_check_info->named_interceptor() != i::Tagged<i::Object>(),
      "v8::FunctionTemplate::NewRemoteInstance",
      "InstanceTemplate needs to have access check handlers");
  i::DirectHandle<i::JSObject> object;
  if (!i::ApiNatives::InstantiateRemoteObject(
           Utils::OpenDirectHandle(*InstanceTemplate()))
           .ToHandle(&object)) {
    return {};
  }
  return Utils::ToLocal(scope.CloseAndEscape(object));
}
References v8::Utils::ApiCheck(), v8::anonymous_namespace{api.cc}::EnsureConstructor(), v8::internal::InstanceTemplate, v8::internal::ApiNatives::InstantiateRemoteObject(), v8::Utils::OpenDirectHandle(), and v8::anonymous_namespace{api.cc}::ToHandle().
NewWithCache()
Local< FunctionTemplate > v8::FunctionTemplate::NewWithCache (Isolate * isolate, FunctionCallback callback, Local< Private > cache_property, Local< Value > data = Local<Value>(), Local< Signature > signature = Local<Signature>(), int length = 0, SideEffectType side_effect_type = SideEffectType::kHasSideEffect) [static]
Creates a function template backed/cached by a private property.
Definition at line 1206 of file api.cc.
                                                                             {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_FunctionTemplate_NewWithCache);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::FunctionTemplateInfo> templ = FunctionTemplateNew(
      i_isolate, callback, data, signature, length, ConstructorBehavior::kAllow,
      false, cache_property, side_effect_type);
  return Utils::ToLocal(templ);
}
References v8::anonymous_namespace{api.cc}::FunctionTemplateNew(), v8::kAllow, and v8::internal::length.
NewWithCFunctionOverloads()
Local< FunctionTemplate > v8::FunctionTemplate::NewWithCFunctionOverloads (Isolate * isolate, FunctionCallback callback = nullptr, v8::Local< Value > data = Local<Value>(), v8::Local< Signature > signature = Local<Signature>(), int length = 0, ConstructorBehavior behavior = ConstructorBehavior::kAllow, SideEffectType side_effect_type = SideEffectType::kHasSideEffect, const MemorySpan< const CFunction > & c_function_overloads = {}) [static]
Creates a function template for multiple overloaded fast API calls.
Definition at line 1172 of file api.cc.
                                                             {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_FunctionTemplate_New);
  // Check that all overloads of the fast API callback have different numbers of
  // parameters. Since the number of overloads is supposed to be small, just
  // comparing them with each other should be fine.
  for (size_t i = 0; i < c_function_overloads.size(); ++i) {
    for (size_t j = i + 1; j < c_function_overloads.size(); ++j) {
      CHECK_NE(c_function_overloads.data()[i].ArgumentCount(),
               c_function_overloads.data()[j].ArgumentCount());
    }
  }
  if (!Utils::ApiCheck(
          c_function_overloads.empty() ||
              behavior == ConstructorBehavior::kThrow,
          "FunctionTemplate::NewWithCFunctionOverloads",
          "Fast API calls are not supported for constructor functions")) {
    return {};
  }
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::FunctionTemplateInfo> templ = FunctionTemplateNew(
      i_isolate, callback, data, signature, length, behavior, false,
      Local<Private>(), side_effect_type, c_function_overloads);
  return Utils::ToLocal(templ);
}
References v8::Utils::ApiCheck(), CHECK_NE, v8::MemorySpan< T >::data(), v8::MemorySpan< T >::empty(), v8::anonymous_namespace{api.cc}::FunctionTemplateNew(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::kThrow, v8::internal::length, and v8::MemorySpan< T >::size().
Referenced by v8::Shell::CreateTestFastCApiTemplate().
PrototypeTemplate()
Local< ObjectTemplate > v8::FunctionTemplate::PrototypeTemplate ()
A PrototypeTemplate is the template used to create the prototype object of the function created by this template.
Definition at line 1027 of file api.cc.
                                                          {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = self->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::HeapObject> heap_obj(self->GetPrototypeTemplate(),
                                          i_isolate);
  if (i::IsUndefined(*heap_obj, i_isolate)) {
    // Do not cache prototype objects.
    constexpr bool do_not_cache = true;
    i::DirectHandle<i::ObjectTemplateInfo> proto_template =
        i_isolate->factory()->NewObjectTemplateInfo({}, do_not_cache);
    i::FunctionTemplateInfo::SetPrototypeTemplate(i_isolate, self,
                                                  proto_template);
    return Utils::ToLocal(proto_template);
  }
  return ToApiHandle<ObjectTemplate>(heap_obj);
}
References v8::internal::Isolate::factory(), v8::internal::Factory::NewObjectTemplateInfo(), and v8::Utils::OpenDirectHandle().
ReadOnlyPrototype()
void v8::FunctionTemplate::ReadOnlyPrototype ()
Sets the ReadOnly flag in the attributes of the 'prototype' property of functions created from this FunctionTemplate to true.
Definition at line 1374 of file api.cc.
                                         {
  auto info = Utils::OpenDirectHandle(this);
  EnsureNotPublished(info, "v8::FunctionTemplate::ReadOnlyPrototype");
  i::Isolate* i_isolate = info->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  info->set_read_only_prototype(true);
}
References v8::anonymous_namespace{api.cc}::EnsureNotPublished(), and v8::Utils::OpenDirectHandle().
RemovePrototype()
void v8::FunctionTemplate::RemovePrototype ()
Removes the prototype property from functions created from this FunctionTemplate.
Definition at line 1382 of file api.cc.
                                       {
  auto info = Utils::OpenDirectHandle(this);
  EnsureNotPublished(info, "v8::FunctionTemplate::RemovePrototype");
  i::Isolate* i_isolate = info->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  info->set_remove_prototype(true);
}
References v8::anonymous_namespace{api.cc}::EnsureNotPublished(), and v8::Utils::OpenDirectHandle().
SealAndPrepareForPromotionToReadOnly()
void v8::FunctionTemplate::SealAndPrepareForPromotionToReadOnly ()
Seal the object and mark it for promotion to read only space during context snapshot creation.
This is an experimental feature and may still change significantly.
Definition at line 7427 of file api.cc.
                                                            {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = self->GetIsolateChecked();
  i::FunctionTemplateInfo::SealAndPrepareForPromotionToReadOnly(i_isolate,
                                                                self);
}
References v8::Utils::OpenDirectHandle(), and v8::internal::FunctionTemplateInfo::SealAndPrepareForPromotionToReadOnly().
SetAcceptAnyReceiver()
void v8::FunctionTemplate::SetAcceptAnyReceiver (bool value)
When set to true, no access check will be performed on the receiver of a function call.
Currently defaults to true, but this is subject to change.
Definition at line 1366 of file api.cc.
                                                      {
  auto info = Utils::OpenDirectHandle(this);
  EnsureNotPublished(info, "v8::FunctionTemplate::SetAcceptAnyReceiver");
  i::Isolate* i_isolate = info->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  info->set_accept_any_receiver(value);
}
References v8::anonymous_namespace{api.cc}::EnsureNotPublished(), v8::Utils::OpenDirectHandle(), and v8::internal::value.
SetCallHandler()
void v8::FunctionTemplate::SetCallHandler (FunctionCallback callback, v8::Local< Value > data = Local<Value>(), SideEffectType side_effect_type = SideEffectType::kHasSideEffect, const MemorySpan< const CFunction > & c_function_overloads = {})
Set the call-handler callback for a FunctionTemplate.
This callback is called whenever the function created from this FunctionTemplate is called. The 'c_function' represents a fast API call, see the comment above the class declaration.
Definition at line 1232 of file api.cc.
                                                             {
  auto info = Utils::OpenDirectHandle(this);
  EnsureNotPublished(info, "v8::FunctionTemplate::SetCallHandler");
  i::Isolate* i_isolate = info->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::HandleScope scope(i_isolate);
  info->set_has_side_effects(side_effect_type !=
                             SideEffectType::kHasNoSideEffect);
  info->set_callback(i_isolate, reinterpret_cast<i::Address>(callback));
  if (data.IsEmpty()) {
    data = v8::Undefined(reinterpret_cast<v8::Isolate*>(i_isolate));
  }
  // "Release" callback and callback data fields.
  info->set_callback_data(*Utils::OpenDirectHandle(*data), kReleaseStore);
  if (!c_function_overloads.empty()) {
    // Stores the data for a sequence of CFunction overloads into a single
    // FixedArray, as [address_0, signature_0, ... address_n-1, signature_n-1].
    i::DirectHandle<i::FixedArray> function_overloads =
        i_isolate->factory()->NewFixedArray(static_cast<int>(
            c_function_overloads.size() *
            i::FunctionTemplateInfo::kFunctionOverloadEntrySize));
    int function_count = static_cast<int>(c_function_overloads.size());
    for (int i = 0; i < function_count; i++) {
      const CFunction& c_function = c_function_overloads.data()[i];
      i::DirectHandle<i::Object> address = FromCData<internal::kCFunctionTag>(
          i_isolate, c_function.GetAddress());
      function_overloads->set(
          i::FunctionTemplateInfo::kFunctionOverloadEntrySize * i, *address);
      i::DirectHandle<i::Object> signature =
          FromCData<internal::kCFunctionInfoTag>(i_isolate,
                                                 c_function.GetTypeInfo());
      function_overloads->set(
          i::FunctionTemplateInfo::kFunctionOverloadEntrySize * i + 1,
          *signature);
    }
    i::FunctionTemplateInfo::SetCFunctionOverloads(i_isolate, info,
                                                   function_overloads);
  }
}
References v8::MemorySpan< T >::data(), v8::MemorySpan< T >::empty(), v8::anonymous_namespace{api.cc}::EnsureNotPublished(), v8::internal::Isolate::factory(), v8::CFunction::GetAddress(), v8::CFunction::GetTypeInfo(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::FunctionTemplateInfo::kFunctionOverloadEntrySize, v8::kHasNoSideEffect, v8::kReleaseStore, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::Utils::OpenDirectHandle(), v8::MemorySpan< T >::size(), and v8::Undefined().
SetClassName()
void v8::FunctionTemplate::SetClassName (Local< String > name)
Set the class name of the FunctionTemplate.
This is used for printing objects created with the function created from the FunctionTemplate as its constructor.
Definition at line 1342 of file api.cc.
                                                      {
  auto info = Utils::OpenDirectHandle(this);
  EnsureNotPublished(info, "v8::FunctionTemplate::SetClassName");
  i::Isolate* i_isolate = info->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  info->set_class_name(*Utils::OpenDirectHandle(*name));
}
References v8::anonymous_namespace{api.cc}::EnsureNotPublished(), name, and v8::Utils::OpenDirectHandle().
SetExceptionContext()
void v8::FunctionTemplate::SetExceptionContext (ExceptionContext context)
Provides information on the type of FunctionTemplate for embedder exception handling.
Definition at line 1358 of file api.cc.
                                                                   {
  auto info = Utils::OpenDirectHandle(this);
  EnsureNotPublished(info, "v8::FunctionTemplate::SetExceptionContext");
  i::Isolate* i_isolate = info->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  info->set_exception_context(static_cast<uint32_t>(context));
}
References v8::anonymous_namespace{api.cc}::EnsureNotPublished(), and v8::Utils::OpenDirectHandle().
SetInterfaceName()
void v8::FunctionTemplate::SetInterfaceName (Local< String > name)
Set the interface name of the FunctionTemplate.
This is provided as contextual information in an ExceptionPropagationMessage to the embedder.
Definition at line 1350 of file api.cc.
                                                          {
  auto info = Utils::OpenDirectHandle(this);
  EnsureNotPublished(info, "v8::FunctionTemplate::SetInterfaceName");
  i::Isolate* i_isolate = info->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  info->set_interface_name(*Utils::OpenDirectHandle(*name));
}
References v8::anonymous_namespace{api.cc}::EnsureNotPublished(), name, and v8::Utils::OpenDirectHandle().
SetLength()
void v8::FunctionTemplate::SetLength (int length)
Set the predefined length property for the FunctionTemplate.
Definition at line 1334 of file api.cc.
                                           {
  auto info = Utils::OpenDirectHandle(this);
  EnsureNotPublished(info, "v8::FunctionTemplate::SetLength");
  i::Isolate* i_isolate = info->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  info->set_length(length);
}
References v8::anonymous_namespace{api.cc}::EnsureNotPublished(), v8::internal::length, and v8::Utils::OpenDirectHandle().
SetPrototypeProviderTemplate()
void v8::FunctionTemplate::SetPrototypeProviderTemplate (Local< FunctionTemplate > prototype_provider)
A PrototypeProviderTemplate is another function template whose prototype property is used for this template.
This is mutually exclusive with setting a prototype template indirectly by calling PrototypeTemplate() or using Inherit().
Definition at line 1045 of file api.cc.
                                                {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = self->GetIsolateChecked();
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::DirectHandle<i::FunctionTemplateInfo> result =
      Utils::OpenDirectHandle(*prototype_provider);
  Utils::ApiCheck(i::IsUndefined(self->GetPrototypeTemplate(), i_isolate),
                  "v8::FunctionTemplate::SetPrototypeProviderTemplate",
                  "Protoype must be undefined");
  Utils::ApiCheck(i::IsUndefined(self->GetParentTemplate(), i_isolate),
                  "v8::FunctionTemplate::SetPrototypeProviderTemplate",
                  "Prototype provider must be empty");
  i::FunctionTemplateInfo::SetPrototypeProviderTemplate(i_isolate, self,
                                                        result);
}
References v8::Utils::ApiCheck(), v8::Utils::OpenDirectHandle(), and v8::base::internal::result.
Friends And Related Function Documentation
Context
friend class Context [friend]
Definition at line 732 of file v8-template.h.
ObjectTemplate
friend class ObjectTemplate [friend]
Definition at line 733 of file v8-template.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-template.h
/mnt/V8SourceCode/src/api/api.cc