v8::internal::TranslatedFrame::iterator Class Reference
#include <translated-state.h>
Public Member Functions
iterator & operator++ ()
iterator operator++ (int)
bool operator== (const iterator &other) const
bool operator!= (const iterator &other) const
TranslatedValue & operator* ()
TranslatedValue * operator-> ()
const TranslatedValue & operator* () const
const TranslatedValue * operator-> () const
int input_index () const
Private Member Functions
iterator (std::deque< TranslatedValue >::iterator position, int input_index=0)
Private Attributes
friend TranslatedFrame
std::deque< TranslatedValue >::iterator position_
int input_index_
Detailed Description
Definition at line 261 of file translated-state.h.
Constructor & Destructor Documentation
iterator()
v8::internal::TranslatedFrame::iterator::iterator (std::deque< TranslatedValue >::iterator position, int input_index = 0) [inline], [explicit], [private]
Definition at line 292 of file translated-state.h.
        : position_(position), input_index_(input_index) {}
Member Function Documentation
input_index()
int v8::internal::TranslatedFrame::iterator::input_index () const [inline]
Definition at line 287 of file translated-state.h.
{ return input_index_; }
References input_index_.
Referenced by v8::internal::FrameWriter::PushTranslatedValue().
operator!=()
bool v8::internal::TranslatedFrame::iterator::operator!= (const iterator & other) const [inline]
Definition at line 280 of file translated-state.h.
{ return !(*this == other); }
operator*() [1/2]
TranslatedValue& v8::internal::TranslatedFrame::iterator::operator* () [inline]
Definition at line 282 of file translated-state.h.
{ return (*position_); }
References position_.
operator*() [2/2]
const TranslatedValue& v8::internal::TranslatedFrame::iterator::operator* () const [inline]
Definition at line 284 of file translated-state.h.
{ return (*position_); }
References position_.
operator++() [1/2]
iterator& v8::internal::TranslatedFrame::iterator::operator++ () [inline]
Definition at line 263 of file translated-state.h.
                           {
      ++input_index_;
      AdvanceIterator(&position_);
      return *this;
    }
References v8::internal::TranslatedFrame::AdvanceIterator(), input_index_, and position_.
operator++() [2/2]
iterator v8::internal::TranslatedFrame::iterator::operator++ (int) [inline]
Definition at line 269 of file translated-state.h.
                             {
      iterator original(position_, input_index_);
      ++input_index_;
      AdvanceIterator(&position_);
      return original;
    }
References v8::internal::TranslatedFrame::AdvanceIterator(), input_index_, and position_.
operator->() [1/2]
TranslatedValue* v8::internal::TranslatedFrame::iterator::operator-> () [inline]
Definition at line 283 of file translated-state.h.
{ return &(*position_); }
operator->() [2/2]
const TranslatedValue* v8::internal::TranslatedFrame::iterator::operator-> () const [inline]
Definition at line 285 of file translated-state.h.
{ return &(*position_); }
operator==()
bool v8::internal::TranslatedFrame::iterator::operator== (const iterator & other) const [inline]
Definition at line 276 of file translated-state.h.
                                                 {
      // Ignore {input_index_} for equality.
      return position_ == other.position_;
    }
References position_.
Member Data Documentation
input_index_
int v8::internal::TranslatedFrame::iterator::input_index_ [private]
Definition at line 297 of file translated-state.h.
Referenced by input_index(), and operator++().
position_
std::deque<TranslatedValue>::iterator v8::internal::TranslatedFrame::iterator::position_ [private]
Definition at line 296 of file translated-state.h.
Referenced by operator*(), operator++(), and operator==().
TranslatedFrame
friend v8::internal::TranslatedFrame::iterator::TranslatedFrame [private]
Definition at line 290 of file translated-state.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/deoptimizer/translated-state.h