v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency Class Reference
Public Member Functions
EmptyContextExtensionDependency (ScopeInfoRef scope_info)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const ScopeInfoRef scope_info_
Additional Inherited Members
Detailed Description
Definition at line 943 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
EmptyContextExtensionDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency::EmptyContextExtensionDependency (ScopeInfoRef scope_info) [inline], [explicit]
Definition at line 945 of file compilation-dependencies.cc.
      : CompilationDependency(kEmptyContextExtension), scope_info_(scope_info) {
    DCHECK(v8_flags.empty_context_extension_dep);
    DCHECK(scope_info.SloppyEvalCanExtendVars());
    DCHECK(!HeapLayout::InReadOnlySpace(*scope_info.object()));
  }
References v8::internal::DCHECK(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::compiler::ScopeInfoRef::object(), v8::internal::compiler::ScopeInfoRef::SloppyEvalCanExtendVars(), and v8::internal::v8_flags.
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 968 of file compilation-dependencies.cc.
                                                                {
    const EmptyContextExtensionDependency* const zat =
        that->AsEmptyContextExtension();
    return scope_info_.equals(zat->scope_info_);
  }
References scope_info_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 963 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(scope_info_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 956 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    deps->Register(scope_info_.object(),
                   DependentCode::kEmptyContextExtensionGroup);
  }
References broker(), v8::internal::DependentCode::kEmptyContextExtensionGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 952 of file compilation-dependencies.cc.
                                                    {
    return !scope_info_.SomeContextHasExtension();
  }
Member Data Documentation
scope_info_
const ScopeInfoRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::EmptyContextExtensionDependency::scope_info_ [private]
Definition at line 974 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc