v8::internal::compiler::NodeObserver Class Reference
#include <node-observer.h>
Public Types
enum class Observation { kContinue
, kStop
 }
Public Member Functions
NodeObserver ()=default
virtual ~NodeObserver ()=0
NodeObserver (const NodeObserver &)=delete
NodeObserver & operator= (const NodeObserver &)=delete
virtual Observation OnNodeCreated (const Node *node)
virtual Observation OnNodeChanged (const char *reducer_name, const Node *node, const ObservableNodeState &old_state)
void set_has_observed_changes ()
bool has_observed_changes () const
Private Attributes
std::atomic< bool > has_observed_changes_ {false}
Detailed Description
Definition at line 57 of file node-observer.h.
Member Enumeration Documentation
Observation
enum v8::internal::compiler::NodeObserver::Observation [strong]
Enumerator
kContinue
kStop
Definition at line 59 of file node-observer.h.
                         {
    kContinue,
    kStop,
  };
Constructor & Destructor Documentation
NodeObserver() [1/2]
v8::internal::compiler::NodeObserver::NodeObserver () [default]
 NodeObserver()
v8::internal::compiler::NodeObserver::~NodeObserver () [inline], [pure virtual], [default]
NodeObserver() [2/2]
v8::internal::compiler::NodeObserver::NodeObserver (const NodeObserver &) [delete]
Member Function Documentation
has_observed_changes()
bool v8::internal::compiler::NodeObserver::has_observed_changes () const [inline]
Definition at line 80 of file node-observer.h.
{ return has_observed_changes_; }
References has_observed_changes_.
OnNodeChanged()
virtual Observation v8::internal::compiler::NodeObserver::OnNodeChanged (const char * reducer_name, const Node * node, const ObservableNodeState & old_state) [inline], [virtual]
Definition at line 74 of file node-observer.h.
                                                                          {
    return Observation::kContinue;
  }
References kContinue.
Referenced by v8::internal::compiler::ObserveNodeManager::OnNodeChanged().
OnNodeCreated()
virtual Observation v8::internal::compiler::NodeObserver::OnNodeCreated (const Node * node) [inline], [virtual]
Definition at line 70 of file node-observer.h.
                                                      {
    return Observation::kContinue;
  }
References kContinue.
Referenced by v8::internal::compiler::Revectorizer::ReduceStoreChain(), and v8::internal::compiler::ObserveNodeManager::StartObserving().
operator=()
NodeObserver& v8::internal::compiler::NodeObserver::operator= (const NodeObserver &) [delete]
set_has_observed_changes()
void v8::internal::compiler::NodeObserver::set_has_observed_changes () [inline]
Definition at line 79 of file node-observer.h.
{ has_observed_changes_ = true; }
References has_observed_changes_.
Referenced by v8::internal::compiler::ObserveNodeManager::StartObserving().
Member Data Documentation
has_observed_changes_
std::atomic<bool> v8::internal::compiler::NodeObserver::has_observed_changes_ {false} [private]
Definition at line 83 of file node-observer.h.
Referenced by has_observed_changes(), and set_has_observed_changes().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/node-observer.h