cppgc::internal::Compactor Class Reference
#include <compactor.h>
Public Member Functions
Compactor (RawHeap &)
~Compactor ()
Compactor (const Compactor &)=delete
Compactor & operator= (const Compactor &)=delete
void InitializeIfShouldCompact (GCConfig::MarkingType, StackState)
void CancelIfShouldNotCompact (GCConfig::MarkingType, StackState)
CompactableSpaceHandling CompactSpacesIfEnabled ()
CompactionWorklists * compaction_worklists ()
void EnableForNextGCForTesting ()
bool IsEnabledForTesting () const
Private Types
using CompactableSpaceHandling = SweepingConfig::CompactableSpaceHandling
Private Member Functions
bool ShouldCompact (GCConfig::MarkingType, StackState) const
Private Attributes
RawHeap & heap_
std::vector< NormalPageSpace * > compactable_spaces_
std::unique_ptr< CompactionWorklists > compaction_worklists_
bool is_enabled_ = false
bool is_cancelled_ = false
bool enable_for_next_gc_for_testing_ = false
Detailed Description
Definition at line 17 of file compactor.h.
Member Typedef Documentation
CompactableSpaceHandling
using cppgc::internal::Compactor::CompactableSpaceHandling = SweepingConfig::CompactableSpaceHandling [private]
Definition at line 18 of file compactor.h.
Constructor & Destructor Documentation
Compactor() [1/2]
cppgc::internal::Compactor::Compactor (RawHeap & heap) [explicit]
Definition at line 453 of file compactor.cc.
                                  : heap_(heap) {
  for (auto& space : heap_) {
    if (!space->is_compactable()) continue;
    DCHECK_EQ(&heap, space->raw_heap());
    compactable_spaces_.push_back(static_cast<NormalPageSpace*>(space.get()));
  }
}
References compactable_spaces_, DCHECK_EQ, heap_, and space.
 Compactor()
cppgc::internal::Compactor::~Compactor () [inline]
Definition at line 22 of file compactor.h.
{ DCHECK(!is_enabled_); }
References DCHECK.
Compactor() [2/2]
cppgc::internal::Compactor::Compactor (const Compactor &) [delete]
Member Function Documentation
CancelIfShouldNotCompact()
void cppgc::internal::Compactor::CancelIfShouldNotCompact (GCConfig::MarkingType marking_type, StackState stack_state)
Definition at line 493 of file compactor.cc.
                                                                 {
  if (!is_enabled_ || ShouldCompact(marking_type, stack_state)) return;
  is_cancelled_ = true;
  is_enabled_ = false;
}
References is_cancelled_, is_enabled_, and ShouldCompact().
Referenced by v8::internal::CppHeap::EnterFinalPause().
compaction_worklists()
CompactionWorklists* cppgc::internal::Compactor::compaction_worklists () [inline]
Definition at line 33 of file compactor.h.
                                              {
    return compaction_worklists_.get();
  }
Referenced by cppgc::internal::MarkerBase::ClearAllWorklistsForTesting(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::Run().
CompactSpacesIfEnabled()
Compactor::CompactableSpaceHandling cppgc::internal::Compactor::CompactSpacesIfEnabled ()
Definition at line 501 of file compactor.cc.
                                                                    {
  if (is_cancelled_ && compaction_worklists_) {
    compaction_worklists_->movable_slots_worklist()->Clear();
    compaction_worklists_.reset();
  }
  if (!is_enabled_) return CompactableSpaceHandling::kSweep;
  StatsCollector::EnabledScope stats_scope(heap_.heap()->stats_collector(),
                                           StatsCollector::kAtomicCompact);
  MovableReferences movable_references(*heap_.heap());
  CompactionWorklists::MovableReferencesWorklist::Local local(
      *compaction_worklists_->movable_slots_worklist());
  CompactionWorklists::MovableReference* slot;
  while (local.Pop(&slot)) {
    movable_references.AddOrFilter(slot);
  }
  compaction_worklists_.reset();
  const StickyBits sticky_bits = heap_.heap()->sticky_bits();
  for (NormalPageSpace* space : compactable_spaces_) {
    CompactSpace(space, movable_references, sticky_bits);
  }
  enable_for_next_gc_for_testing_ = false;
  is_enabled_ = false;
  return CompactableSpaceHandling::kIgnore;
}
References compactable_spaces_, compaction_worklists_, cppgc::internal::anonymous_namespace{compactor.cc}::CompactSpace(), enable_for_next_gc_for_testing_, cppgc::internal::RawHeap::heap(), heap_, is_cancelled_, is_enabled_, cppgc::internal::SweepingConfig::kIgnore, cppgc::internal::SweepingConfig::kSweep, space, cppgc::internal::HeapBase::stats_collector(), and cppgc::internal::HeapBase::sticky_bits().
Referenced by v8::internal::CppHeap::CompactAndSweep().
EnableForNextGCForTesting()
void cppgc::internal::Compactor::EnableForNextGCForTesting ()
Definition at line 532 of file compactor.cc.
                                          {
  DCHECK_NULL(heap_.heap()->marker());
  enable_for_next_gc_for_testing_ = true;
}
References DCHECK_NULL, enable_for_next_gc_for_testing_, cppgc::internal::RawHeap::heap(), heap_, and cppgc::internal::HeapBase::marker().
Referenced by cppgc::testing::StandaloneTestingHeap::ForceCompactionForNextGarbageCollection().
InitializeIfShouldCompact()
void cppgc::internal::Compactor::InitializeIfShouldCompact (GCConfig::MarkingType marking_type, StackState stack_state)
Definition at line 481 of file compactor.cc.
                                                                  {
  DCHECK(!is_enabled_);
  if (!ShouldCompact(marking_type, stack_state)) return;
  compaction_worklists_ = std::make_unique<CompactionWorklists>();
  is_enabled_ = true;
  is_cancelled_ = false;
}
References compaction_worklists_, DCHECK, is_cancelled_, is_enabled_, and ShouldCompact().
Referenced by v8::internal::CppHeap::InitializeMarking().
IsEnabledForTesting()
bool cppgc::internal::Compactor::IsEnabledForTesting () const [inline]
Definition at line 38 of file compactor.h.
{ return is_enabled_; }
operator=()
Compactor& cppgc::internal::Compactor::operator= (const Compactor &) [delete]
ShouldCompact()
bool cppgc::internal::Compactor::ShouldCompact (GCConfig::MarkingType marking_type, StackState stack_state) const [private]
Definition at line 461 of file compactor.cc.
                                                            {
  if (compactable_spaces_.empty() ||
      (marking_type == GCConfig::MarkingType::kAtomic &&
       stack_state == StackState::kMayContainHeapPointers)) {
    // The following check ensures that tests that want to test compaction are
    // not interrupted by garbage collections that cannot use compaction.
    DCHECK(!enable_for_next_gc_for_testing_);
    return false;
  }
  if (enable_for_next_gc_for_testing_) {
    return true;
  }
  size_t free_list_size = UpdateHeapResidency(compactable_spaces_);
  return free_list_size > kFreeListSizeThreshold;
}
References compactable_spaces_, DCHECK, enable_for_next_gc_for_testing_, cppgc::Heap::kAtomic, cppgc::internal::anonymous_namespace{compactor.cc}::kFreeListSizeThreshold, and cppgc::internal::anonymous_namespace{compactor.cc}::UpdateHeapResidency().
Referenced by CancelIfShouldNotCompact(), and InitializeIfShouldCompact().
Member Data Documentation
compactable_spaces_
std::vector<NormalPageSpace*> cppgc::internal::Compactor::compactable_spaces_ [private]
Definition at line 45 of file compactor.h.
Referenced by Compactor(), CompactSpacesIfEnabled(), and ShouldCompact().
compaction_worklists_
std::unique_ptr<CompactionWorklists> cppgc::internal::Compactor::compaction_worklists_ [private]
Definition at line 47 of file compactor.h.
Referenced by CompactSpacesIfEnabled(), and InitializeIfShouldCompact().
enable_for_next_gc_for_testing_
bool cppgc::internal::Compactor::enable_for_next_gc_for_testing_ = false [private]
Definition at line 51 of file compactor.h.
Referenced by CompactSpacesIfEnabled(), EnableForNextGCForTesting(), and ShouldCompact().
heap_
RawHeap& cppgc::internal::Compactor::heap_ [private]
Definition at line 43 of file compactor.h.
Referenced by Compactor(), CompactSpacesIfEnabled(), and EnableForNextGCForTesting().
is_cancelled_
bool cppgc::internal::Compactor::is_cancelled_ = false [private]
Definition at line 50 of file compactor.h.
Referenced by CancelIfShouldNotCompact(), CompactSpacesIfEnabled(), and InitializeIfShouldCompact().
is_enabled_
bool cppgc::internal::Compactor::is_enabled_ = false [private]
Definition at line 49 of file compactor.h.
Referenced by CancelIfShouldNotCompact(), CompactSpacesIfEnabled(), and InitializeIfShouldCompact().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/compactor.h
/mnt/V8SourceCode/src/heap/cppgc/compactor.cc