v8::internal::compiler::turboshaft::TupleType Class Reference
#include <types.h>
Public Member Functions
int size () const
const Type & element (int index) const
base::Vector< Type > elements () const
bool Equals (const TupleType &other) const
bool IsSubtypeOf (const TupleType &other) const
void PrintTo (std::ostream &stream) const
Static Public Member Functions
static TupleType Tuple (const Type &element0, const Type &element1, Zone *zone)
static TupleType Tuple (base::Vector< Type > elements, Zone *zone)
static Type LeastUpperBound (const TupleType &lhs, const TupleType &rhs, Zone *zone)
Static Public Attributes
static constexpr int kMaxTupleSize = std::numeric_limits<uint8_t>::max()
Private Types
using Payload = detail::Payload_OutlineSet< Type >
Private Member Functions
TupleType (uint8_t tuple_size, const Payload &payload)
Static Private Attributes
static constexpr Kind KIND = Kind::kTuple
Additional Inherited Members
Detailed Description
Definition at line 808 of file types.h.
Member Typedef Documentation
Payload
using v8::internal::compiler::turboshaft::TupleType::Payload = detail::Payload_OutlineSet<Type> [private]
Definition at line 854 of file types.h.
Constructor & Destructor Documentation
TupleType()
v8::internal::compiler::turboshaft::TupleType::TupleType (uint8_t tuple_size, const Payload & payload) [inline], [private]
Definition at line 856 of file types.h.
      : Type(KIND, 0, tuple_size, 0, 0, payload) {}
Member Function Documentation
element()
const Type& v8::internal::compiler::turboshaft::TupleType::element (int index) const [inline]
Definition at line 836 of file types.h.
                                       {
    DCHECK_LE(0, index);
    DCHECK_LT(index, size());
    return get_payload<Payload>().array[index];
  }
References DCHECK_LE, DCHECK_LT, v8::internal::index, and size().
Referenced by Equals(), IsSubtypeOf(), LeastUpperBound(), PrintTo(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessProjection(), and v8::internal::compiler::turboshaft::Typer::TypeProjection().
elements()
base::Vector<Type> v8::internal::compiler::turboshaft::TupleType::elements () const [inline]
Definition at line 841 of file types.h.
                                    {
    return {get_payload<Payload>().array, static_cast<size_t>(size())};
  }
References size().
Equals()
bool v8::internal::compiler::turboshaft::TupleType::Equals (const TupleType & other) const
Definition at line 674 of file types.cc.
                                                   {
  if (size() != other.size()) return false;
  for (int i = 0; i < size(); ++i) {
    if (!element(i).Equals(other.element(i))) return false;
  }
  return true;
}
References element(), v8::internal::compiler::turboshaft::Type::Equals(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and size().
IsSubtypeOf()
bool v8::internal::compiler::turboshaft::TupleType::IsSubtypeOf (const TupleType & other) const
Definition at line 682 of file types.cc.
                                                        {
  if (size() != other.size()) return false;
  for (int i = 0; i < size(); ++i) {
    if (!element(i).IsSubtypeOf(other.element(i))) return false;
  }
  return true;
}
References element(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::Type::IsSubtypeOf(), and size().
LeastUpperBound()
Type v8::internal::compiler::turboshaft::TupleType::LeastUpperBound (const TupleType & lhs, const TupleType & rhs, Zone * zone) [static]
Definition at line 691 of file types.cc.
                                            {
  if (lhs.size() != rhs.size()) return Type::Any();
  Payload p;
  p.array = zone->AllocateArray<Type>(lhs.size());
  for (int i = 0; i < lhs.size(); ++i) {
    p.array[i] = Type::LeastUpperBound(lhs.element(i), rhs.element(i), zone);
  }
  return TupleType{static_cast<uint8_t>(lhs.size()), p};
}
References v8::internal::Zone::AllocateArray(), v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::turboshaft::detail::Payload_OutlineSet< T >::array, element(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::Type::LeastUpperBound(), and size().
PrintTo()
void v8::internal::compiler::turboshaft::TupleType::PrintTo (std::ostream & stream) const
Definition at line 702 of file types.cc.
                                                {
  stream << "(";
  for (int i = 0; i < size(); ++i) {
    if (i != 0) stream << ", ";
    element(i).PrintTo(stream);
  }
  stream << ")";
}
References element(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::Type::PrintTo(), and size().
size()
int v8::internal::compiler::turboshaft::TupleType::size () const [inline]
Definition at line 835 of file types.h.
{ return static_cast<int>(set_size_); }
Referenced by Equals(), IsSubtypeOf(), LeastUpperBound(), PrintTo(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessProjection(), and v8::internal::compiler::turboshaft::Typer::TypeProjection().
Tuple() [1/2]
static TupleType v8::internal::compiler::turboshaft::TupleType::Tuple (base::Vector< Type > elements, Zone * zone) [inline], [static]
Definition at line 823 of file types.h.
                                                                {
    DCHECK_LE(elements.size(), kMaxTupleSize);
    Payload p;
    p.array = zone->AllocateArray<Type>(elements.size());
    DCHECK_NOT_NULL(p.array);
    for (size_t i = 0; i < elements.size(); ++i) {
      p.array[i] = elements[i];
    }
    return TupleType{static_cast<uint8_t>(elements.size()), p};
  }
References v8::internal::Zone::AllocateArray(), v8::internal::compiler::turboshaft::detail::Payload_OutlineSet< T >::array, DCHECK_LE, DCHECK_NOT_NULL, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::Vector< T >::size().
Tuple() [2/2]
static TupleType v8::internal::compiler::turboshaft::TupleType::Tuple (const Type & element0, const Type & element1, Zone * zone) [inline], [static]
Definition at line 813 of file types.h.
                                     {
    Payload p;
    p.array = zone->AllocateArray<Type>(2);
    DCHECK_NOT_NULL(p.array);
    p.array[0] = element0;
    p.array[1] = element1;
    return TupleType{2, p};
  }
References v8::internal::Zone::AllocateArray(), v8::internal::compiler::turboshaft::detail::Payload_OutlineSet< T >::array, and DCHECK_NOT_NULL.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::GetTupleType(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::compiler::turboshaft::Typer::TypeOverflowCheckedBinop(), and v8::internal::compiler::turboshaft::Typer::TypeWord32OverflowCheckedAdd().
Member Data Documentation
KIND
constexpr Kind v8::internal::compiler::turboshaft::TupleType::KIND = Kind::kTuple [static], [constexpr], [private]
Definition at line 853 of file types.h.
kMaxTupleSize
constexpr int v8::internal::compiler::turboshaft::TupleType::kMaxTupleSize = std::numeric_limits<uint8_t>::max() [static], [constexpr]
Definition at line 810 of file types.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/types.h
/mnt/V8SourceCode/src/compiler/turboshaft/types.cc