v8::internal::JSAtomicsMutex Class Reference
#include <js-atomics-synchronization.h>
Classes
class LockGuard
class LockGuardBase
class TryLockGuard
Public Types
enum { kMutexAsyncContextSlot = Context::MIN_CONTEXT_SLOTS
, kUnlockedPromiseAsyncContextSlot
, kAsyncLockedWaiterAsyncContextSlot
, kAsyncContextLength
 }
using AsyncWaiterNodeType = LockAsyncWaiterQueueNode
Public Member Functions
V8_WARN_UNUSED_RESULT bool TryLock ()
void Unlock (Isolate *requester)
bool IsHeld ()
bool IsCurrentThreadOwner ()
void UnlockAsyncLockedMutex (Isolate *requester, DirectHandle< Foreign > async_locked_waiter_wrapper)
Static Public Member Functions
static DirectHandle< JSObject > CreateResultObject (Isolate *isolate, DirectHandle< Object > value, bool success)
static bool Lock (Isolate *requester, DirectHandle< JSAtomicsMutex > mutex, std::optional< base::TimeDelta > timeout=std::nullopt)
static bool LockAsync (Isolate *requester, DirectHandle< JSAtomicsMutex > mutex, Handle< JSPromise > internal_locked_promise, MaybeHandle< JSPromise > unlocked_promise, AsyncWaiterNodeType **waiter_node, std::optional< base::TimeDelta > timeout=std::nullopt)
static DirectHandle< JSPromise > LockAsyncWrapperForWait (Isolate *requester, DirectHandle< JSAtomicsMutex > mutex)
static MaybeDirectHandle< JSPromise > LockOrEnqueuePromise (Isolate *isolate, DirectHandle< JSAtomicsMutex > mutex, DirectHandle< Object > callback, std::optional< base::TimeDelta > timeout)
static bool LockOrEnqueueAsyncNode (Isolate *isolate, DirectHandle< JSAtomicsMutex > mutex, LockAsyncWaiterQueueNode *node)
static void HandleAsyncNotify (LockAsyncWaiterQueueNode *node)
static void HandleAsyncTimeout (LockAsyncWaiterQueueNode *node)
static void CleanupMatchingAsyncWaiters (Isolate *isolate, WaiterQueueNode *node, DequeueMatcher matcher)
Private Types
using IsLockedField = JSSynchronizationPrimitive::NextBitField< bool, 1 >
Private Member Functions
void SetCurrentThreadAsOwner ()
void ClearOwnerThread ()
std::atomic< int32_t > * AtomicOwnerThreadIdPtr ()
V8_EXPORT_PRIVATE void UnlockSlowPath (Isolate *requester, std::atomic< StateT > *state)
bool LockJSMutexOrDequeueTimedOutWaiter (Isolate *requester, std::atomic< StateT > *state, WaiterQueueNode *timed_out_waiter)
Static Private Member Functions
static V8_EXPORT_PRIVATE bool LockSlowPath (Isolate *requester, DirectHandle< JSAtomicsMutex > mutex, std::atomic< StateT > *state, std::optional< base::TimeDelta > timeout)
static bool LockAsyncSlowPath (Isolate *isolate, DirectHandle< JSAtomicsMutex > mutex, std::atomic< StateT > *state, Handle< JSPromise > internal_locked_promise, MaybeHandle< JSPromise > unlocked_promise, AsyncWaiterNodeType **waiter_node, std::optional< base::TimeDelta > timeout)
static bool TryLockExplicit (std::atomic< StateT > *state, StateT &expected)
static std::optional< WaiterQueueLockGuard > LockWaiterQueueOrJSMutex (std::atomic< StateT > *state, StateT &current_state)
static V8_EXPORT_PRIVATE bool MutexTryLock (Isolate *requester, DirectHandle< JSAtomicsMutex > mutex, std::atomic< StateT > *state)
static bool BackoffTryLock (Isolate *requester, DirectHandle< JSAtomicsMutex > mutex, std::atomic< StateT > *state)
static bool DequeueTimedOutAsyncWaiter (Isolate *requester, DirectHandle< JSAtomicsMutex > mutex, std::atomic< StateT > *state, WaiterQueueNode *timed_out_waiter)
static V8_EXPORT_PRIVATE bool MaybeEnqueueNode (Isolate *requester, DirectHandle< JSAtomicsMutex > mutex, std::atomic< StateT > *state, WaiterQueueNode *this_waiter)
template<typename LockSlowPathWrapper , typename = std::enable_if<std::is_invocable_r_v< bool, LockSlowPathWrapper, std::atomic<StateT>*>>>
static bool LockImpl (Isolate *requester, DirectHandle< JSAtomicsMutex > mutex, std::optional< base::TimeDelta > timeout, LockSlowPathWrapper slow_path_wrapper)
Static Private Attributes
static constexpr StateT kUnlockedUncontended = kEmptyState
static constexpr StateT kLockedUncontended = IsLockedField::encode(true)
Friends
class Factory
Detailed Description
Definition at line 173 of file js-atomics-synchronization.h.
Member Typedef Documentation
AsyncWaiterNodeType
using v8::internal::JSAtomicsMutex::AsyncWaiterNodeType = LockAsyncWaiterQueueNode
Definition at line 177 of file js-atomics-synchronization.h.
IsLockedField
using v8::internal::JSAtomicsMutex::IsLockedField = JSSynchronizationPrimitive::NextBitField<bool, 1> [private]
Definition at line 301 of file js-atomics-synchronization.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
kMutexAsyncContextSlot
kUnlockedPromiseAsyncContextSlot
kAsyncLockedWaiterAsyncContextSlot
kAsyncContextLength
Definition at line 275 of file js-atomics-synchronization.h.
       {
    // The context slot for the js mutex that is locked asynchronously.
    kMutexAsyncContextSlot = Context::MIN_CONTEXT_SLOTS,
    // The context slot for the js exposed promise returned by the call to
    // Atomics.Mutex.lockAsync, it should be resolved or rejected after the
    // mutex is released.
    kUnlockedPromiseAsyncContextSlot,
    // The isolate keeps track of WaiterQueueNodes for each mutex locked
    // asynchronously, this is so that the lock can be released in case worker
    // termination. The kAsyncLockedWaiterAsyncContextSlot slot is used to store
    // a Foreign wrapping around an ExternalPointerHandle (or raw
    // pointer when pointer compression is disabled) pointing to the
    // WaiterQueueNode so that it can be removed from the list when the lock is
    // released through the usual path.
    kAsyncLockedWaiterAsyncContextSlot,
    kAsyncContextLength
  };
Member Function Documentation
AtomicOwnerThreadIdPtr()
std::atomic< int32_t > * v8::internal::JSAtomicsMutex::AtomicOwnerThreadIdPtr () [inline], [private]
Definition at line 244 of file js-atomics-synchronization-inl.h.
                                                           {
  int32_t* owner_thread_id_ptr =
      reinterpret_cast<int32_t*>(field_address(kOwnerThreadIdOffset));
  return base::AsAtomicPtr(owner_thread_id_ptr);
}
References v8::base::AsAtomicPtr().
Referenced by ClearOwnerThread(), IsCurrentThreadOwner(), SetCurrentThreadAsOwner(), and UnlockSlowPath().
BackoffTryLock()
bool v8::internal::JSAtomicsMutex::BackoffTryLock (Isolate * requester, DirectHandle< JSAtomicsMutex > mutex, std::atomic< StateT > * state) [inline], [static], [private]
Definition at line 598 of file js-atomics-synchronization.cc.
                                                              {
  // The backoff algorithm is copied from PartitionAlloc's SpinningMutex.
  constexpr int kSpinCount = 64;
  constexpr int kMaxBackoff = 16;
  int tries = 0;
  int backoff = 1;
  StateT current_state = state->load(std::memory_order_relaxed);
  do {
    if (JSAtomicsMutex::TryLockExplicit(state, current_state)) return true;
    for (int yields = 0; yields < backoff; yields++) {
      YIELD_PROCESSOR;
      tries++;
    }
    backoff = std::min(kMaxBackoff, backoff << 1);
  } while (tries < kSpinCount);
  return false;
}
References TryLockExplicit(), and YIELD_PROCESSOR.
Referenced by LockAsyncSlowPath(), LockOrEnqueueAsyncNode(), and LockSlowPath().
CleanupMatchingAsyncWaiters()
void v8::internal::JSAtomicsMutex::CleanupMatchingAsyncWaiters (Isolate * isolate, WaiterQueueNode * node, DequeueMatcher matcher) [static]
Definition at line 529 of file js-atomics-synchronization.cc.
                                                                         {
  auto* async_node = static_cast<LockAsyncWaiterQueueNode*>(node);
  if (async_node->ready_for_async_cleanup_) {
    // Whenever a node needs to be looked up in the waiter queue we also remove
    // any other matching nodes and mark them as ready for async cleanup. This
    // way we avoid taking the queue lock multiple times, which could slow down
    // other threads.
    return;
  }
  if (async_node->IsEmpty()) {
    // The node's underlying synchronization primitive has been collected, so
    // delete it.
    async_node->SetNotInListForVerification();
    return;
  }
  DirectHandle<JSAtomicsMutex> mutex =
      async_node->GetSynchronizationPrimitive();
  std::atomic<StateT>* state = mutex->AtomicStatePtr();
  StateT current_state = state->load(std::memory_order_relaxed);
  // The details of updating the state in this function are too complicated
  // for the waiter queue lock guard to manage, so handle the state manually.
  while (!TryLockWaiterQueueExplicit(state, current_state)) {
    YIELD_PROCESSOR;
  }
  bool was_locked_by_this_thread = mutex->IsCurrentThreadOwner();
  WaiterQueueNode* waiter_head =
      mutex->DestructivelyGetWaiterQueueHead(isolate);
  if (waiter_head) {
    // Dequeue all the matching waiters.
    WaiterQueueNode::DequeueAllMatchingForAsyncCleanup(&waiter_head, matcher);
    if (!async_node->ready_for_async_cleanup_) {
      // The node was not in the queue, so it has already being notified.
      // Notify the next head unless the lock is already taken by a different
      // thread or the queue may stall.
      if (waiter_head && (!IsLockedField::decode(current_state) ||
                          was_locked_by_this_thread)) {
        // Notify the next head unless the lock is already taken, in which case
        // the lock owner will notify the next waiter.
        WaiterQueueNode* old_head = WaiterQueueNode::Dequeue(&waiter_head);
        old_head->Notify();
      }
    }
  }
  StateT new_state = kUnlockedUncontended;
  new_state = mutex->SetWaiterQueueHead(isolate, waiter_head, new_state);
  new_state = IsWaiterQueueLockedField::update(new_state, false);
  if (was_locked_by_this_thread) {
    mutex->ClearOwnerThread();
    new_state = IsLockedField::update(new_state, false);
    state->store(new_state, std::memory_order_release);
  } else {
    SetWaiterQueueStateOnly(state, new_state);
  }
}
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::detail::WaiterQueueNode::Dequeue(), v8::internal::detail::WaiterQueueNode::DequeueAllMatchingForAsyncCleanup(), kUnlockedUncontended, v8::internal::detail::WaiterQueueNode::Notify(), v8::internal::detail::WaiterQueueNode::SetNotInListForVerification(), v8::base::BitField< T, shift, size, U >::update(), and YIELD_PROCESSOR.
ClearOwnerThread()
void v8::internal::JSAtomicsMutex::ClearOwnerThread () [inline], [private]
Definition at line 239 of file js-atomics-synchronization-inl.h.
                                      {
  AtomicOwnerThreadIdPtr()->store(ThreadId::Invalid().ToInteger(),
                                  std::memory_order_relaxed);
}
References AtomicOwnerThreadIdPtr(), and v8::internal::ThreadId::Invalid().
Referenced by Unlock().
CreateResultObject()
DirectHandle< JSObject > v8::internal::JSAtomicsMutex::CreateResultObject (Isolate * isolate, DirectHandle< Object > value, bool success) [static]
Definition at line 516 of file js-atomics-synchronization.cc.
                                                                {
  DirectHandle<JSObject> result =
      isolate->factory()->NewJSObject(isolate->object_function());
  DirectHandle<Object> success_value = isolate->factory()->ToBoolean(success);
  JSObject::AddProperty(isolate, result, "value", value,
                        PropertyAttributes::NONE);
  JSObject::AddProperty(isolate, result, "success", success_value,
                        PropertyAttributes::NONE);
  return result;
}
References v8::internal::JSObject::AddProperty(), v8::internal::Isolate::factory(), v8::internal::Factory::NewJSObject(), v8::internal::NONE, v8::base::internal::result, v8::internal::FactoryBase< Impl >::ToBoolean(), and v8::internal::value.
Referenced by v8::internal::BUILTIN(), and HandleAsyncTimeout().
DequeueTimedOutAsyncWaiter()
bool v8::internal::JSAtomicsMutex::DequeueTimedOutAsyncWaiter (Isolate * requester, DirectHandle< JSAtomicsMutex > mutex, std::atomic< StateT > * state, WaiterQueueNode * timed_out_waiter) [static], [private]
Definition at line 978 of file js-atomics-synchronization.cc.
                                                                 {
  // First acquire the queue lock, which is itself a spinlock.
  StateT current_state = state->load(std::memory_order_relaxed);
  // There are no waiters, but the js mutex lock may be held by another thread.
  if (!HasWaitersField::decode(current_state)) return false;
  // The details of updating the state in this function are too complicated
  // for the waiter queue lock guard to manage, so handle the state manually.
  while (!TryLockWaiterQueueExplicit(state, current_state)) {
    YIELD_PROCESSOR;
  }
  // Get the waiter queue head.
  WaiterQueueNode* waiter_head =
      mutex->DestructivelyGetWaiterQueueHead(requester);
  if (waiter_head == nullptr) {
    // The queue is empty but the js mutex lock may be held by another thread,
    // release the waiter queue bit without changing the "is locked" bit.
    DCHECK(!HasWaitersField::decode(current_state));
    SetWaiterQueueStateOnly(state, kUnlockedUncontended);
    return false;
  }
  WaiterQueueNode* dequeued_node = WaiterQueueNode::DequeueMatching(
      &waiter_head,
      [&](WaiterQueueNode* node) { return node == timed_out_waiter; });
  // Release the queue lock and install the new waiter queue head.
  DCHECK_EQ(state->load(),
            IsWaiterQueueLockedField::update(current_state, true));
  StateT new_state = kUnlockedUncontended;
  new_state = mutex->SetWaiterQueueHead(requester, waiter_head, new_state);
  SetWaiterQueueStateOnly(state, new_state);
  return dequeued_node != nullptr;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::detail::WaiterQueueNode::DequeueMatching(), kUnlockedUncontended, and YIELD_PROCESSOR.
Referenced by HandleAsyncTimeout().
HandleAsyncNotify()
void v8::internal::JSAtomicsMutex::HandleAsyncNotify (LockAsyncWaiterQueueNode * node) [static]
Definition at line 1057 of file js-atomics-synchronization.cc.
                                                                       {
  Isolate* requester = waiter->requester_;
  HandleScope scope(requester);
  if (V8_UNLIKELY(waiter->native_context_.IsEmpty())) {
    // The native context was destroyed, so the promise was already removed. But
    // it is possible that other threads are holding references to the
    // synchronization primitive. Try to notify the next waiter.
    if (!waiter->synchronization_primitive_.IsEmpty()) {
      DirectHandle<JSAtomicsMutex> js_mutex =
          waiter->GetSynchronizationPrimitive();
      std::atomic<StateT>* state = js_mutex->AtomicStatePtr();
      StateT current_state = state->load(std::memory_order_acquire);
      if (HasWaitersField::decode(current_state)) {
        // Another thread might take the lock while we are notifying the next
        // waiter, so manually release the queue lock without changing the
        // IsLockedField bit.
        while (!TryLockWaiterQueueExplicit(state, current_state)) {
          YIELD_PROCESSOR;
        }
        WaiterQueueNode* waiter_head =
            js_mutex->DestructivelyGetWaiterQueueHead(requester);
        if (waiter_head) {
          WaiterQueueNode* old_head = WaiterQueueNode::Dequeue(&waiter_head);
          old_head->Notify();
        }
        StateT new_state =
            js_mutex->SetWaiterQueueHead(requester, waiter_head, kEmptyState);
        new_state = IsWaiterQueueLockedField::update(new_state, false);
        SetWaiterQueueStateOnly(state, new_state);
      }
    }
    LockAsyncWaiterQueueNode::RemoveFromAsyncWaiterQueueList(waiter);
    return;
  }
  v8::Context::Scope contextScope(waiter->GetNativeContext());
  DirectHandle<JSAtomicsMutex> js_mutex = waiter->GetSynchronizationPrimitive();
  DirectHandle<JSPromise> promise = waiter->GetInternalWaitingPromise();
  bool locked = LockOrEnqueueAsyncNode(requester, js_mutex, waiter);
  if (locked) {
    if (waiter->timeout_task_id_ != CancelableTaskManager::kInvalidTaskId) {
      TryAbortResult abort_result =
          requester->cancelable_task_manager()->TryAbort(
              waiter->timeout_task_id_);
      DCHECK_EQ(abort_result, TryAbortResult::kTaskAborted);
      USE(abort_result);
    }
    if (waiter->unlocked_promise_.IsEmpty()) {
      // This node came from an async wait notify giving control back to an
      // async lock call, so we don't need to put the node in the locked waiter
      // list because the original LockAsycWaiterQueueNode is already in
      // the locked waiter list.
      LockAsyncWaiterQueueNode::RemoveFromAsyncWaiterQueueList(waiter);
    }
    js_mutex->SetCurrentThreadAsOwner();
    auto resolve_result =
        JSPromise::Resolve(promise, requester->factory()->undefined_value());
    USE(resolve_result);
    RemovePromiseFromNativeContext(requester, promise);
  }
}
References v8::internal::Isolate::cancelable_task_manager(), DCHECK_EQ, v8::internal::detail::WaiterQueueNode::Dequeue(), v8::internal::Isolate::factory(), v8::internal::detail::AsyncWaiterQueueNode< T >::GetInternalWaitingPromise(), v8::internal::detail::AsyncWaiterQueueNode< T >::GetNativeContext(), v8::internal::detail::AsyncWaiterQueueNode< T >::GetSynchronizationPrimitive(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::CancelableTaskManager::kInvalidTaskId, v8::internal::kTaskAborted, LockOrEnqueueAsyncNode(), v8::internal::detail::AsyncWaiterQueueNode< T >::native_context_, v8::internal::detail::WaiterQueueNode::Notify(), v8::internal::detail::AsyncWaiterQueueNode< T >::RemoveFromAsyncWaiterQueueList(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::RemovePromiseFromNativeContext(), v8::internal::detail::WaiterQueueNode::requester_, v8::internal::JSPromise::Resolve(), v8::internal::detail::AsyncWaiterQueueNode< T >::synchronization_primitive_, v8::internal::detail::AsyncWaiterQueueNode< T >::timeout_task_id_, v8::internal::CancelableTaskManager::TryAbort(), v8::internal::detail::AsyncWaiterQueueNode< T >::unlocked_promise_, USE, V8_UNLIKELY, and YIELD_PROCESSOR.
HandleAsyncTimeout()
void v8::internal::JSAtomicsMutex::HandleAsyncTimeout (LockAsyncWaiterQueueNode * node) [static]
Definition at line 1019 of file js-atomics-synchronization.cc.
                                                                        {
  Isolate* requester = waiter->requester_;
  HandleScope scope(requester);
  if (V8_UNLIKELY(waiter->native_context_.IsEmpty())) {
    // The native context was destroyed so the lock_promise was already removed
    // from the native context. Remove the node from the async unlocked waiter
    // list.
    LockAsyncWaiterQueueNode::RemoveFromAsyncWaiterQueueList(waiter);
    return;
  }
  v8::Context::Scope contextScope(waiter->GetNativeContext());
  DirectHandle<JSAtomicsMutex> js_mutex = waiter->GetSynchronizationPrimitive();
  bool dequeued = JSAtomicsMutex::DequeueTimedOutAsyncWaiter(
      requester, js_mutex, js_mutex->AtomicStatePtr(), waiter);
  // If the waiter is no longer in the queue, then its corresponding notify
  // task is already in the event loop, this doesn't guarantee that the lock
  // will be taken by the time the notify task runs, so cancel the notify task.
  if (!dequeued) {
    TryAbortResult abort_result =
        requester->cancelable_task_manager()->TryAbort(waiter->notify_task_id_);
    DCHECK_EQ(abort_result, TryAbortResult::kTaskAborted);
    USE(abort_result);
  }
  DirectHandle<JSPromise> lock_promise = waiter->GetInternalWaitingPromise();
  DirectHandle<JSPromise> lock_async_promise = waiter->GetUnlockedPromise();
  DirectHandle<JSObject> result = CreateResultObject(
      requester, requester->factory()->undefined_value(), false);
  auto resolve_result = JSPromise::Resolve(lock_async_promise, result);
  USE(resolve_result);
  LockAsyncWaiterQueueNode::RemoveFromAsyncWaiterQueueList(waiter);
  RemovePromiseFromNativeContext(requester, lock_promise);
}
References v8::internal::Isolate::cancelable_task_manager(), CreateResultObject(), DCHECK_EQ, DequeueTimedOutAsyncWaiter(), v8::internal::Isolate::factory(), v8::internal::detail::AsyncWaiterQueueNode< T >::GetInternalWaitingPromise(), v8::internal::detail::AsyncWaiterQueueNode< T >::GetNativeContext(), v8::internal::detail::AsyncWaiterQueueNode< T >::GetSynchronizationPrimitive(), v8::internal::detail::AsyncWaiterQueueNode< T >::GetUnlockedPromise(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::kTaskAborted, v8::internal::detail::AsyncWaiterQueueNode< T >::native_context_, v8::internal::detail::AsyncWaiterQueueNode< T >::notify_task_id_, v8::internal::detail::AsyncWaiterQueueNode< T >::RemoveFromAsyncWaiterQueueList(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::RemovePromiseFromNativeContext(), v8::internal::detail::WaiterQueueNode::requester_, v8::internal::JSPromise::Resolve(), v8::base::internal::result, v8::internal::CancelableTaskManager::TryAbort(), USE, and V8_UNLIKELY.
IsCurrentThreadOwner()
bool v8::internal::JSAtomicsMutex::IsCurrentThreadOwner () [inline]
Definition at line 227 of file js-atomics-synchronization-inl.h.
                                          {
  bool result = AtomicOwnerThreadIdPtr()->load(std::memory_order_relaxed) ==
                ThreadId::Current().ToInteger();
  DCHECK_IMPLIES(result, IsHeld());
  return result;
}
References AtomicOwnerThreadIdPtr(), v8::internal::ThreadId::Current(), DCHECK_IMPLIES, IsHeld(), v8::base::internal::result, and v8::internal::ThreadId::ToInteger().
Referenced by Unlock(), and UnlockAsyncLockedMutex().
IsHeld()
bool v8::internal::JSAtomicsMutex::IsHeld () [inline]
Definition at line 222 of file js-atomics-synchronization-inl.h.
                            {
  return IsLockedField::decode(
      AtomicStatePtr()->load(std::memory_order_relaxed));
}
References v8::base::BitField< T, shift, size, U >::decode().
Referenced by IsCurrentThreadOwner().
Lock()
bool v8::internal::JSAtomicsMutex::Lock (Isolate * requester, DirectHandle< JSAtomicsMutex > mutex, std::optional< base::TimeDelta > timeout = std::nullopt) [inline], [static]
Definition at line 182 of file js-atomics-synchronization-inl.h.
                                                              {
  return LockImpl(requester, mutex, timeout, [=](std::atomic<StateT>* state) {
    return LockSlowPath(requester, mutex, state, timeout);
  });
}
References LockImpl(), and LockSlowPath().
Referenced by v8::internal::JSAtomicsCondition::WaitFor().
LockAsync()
bool v8::internal::JSAtomicsMutex::LockAsync (Isolate * requester, DirectHandle< JSAtomicsMutex > mutex, Handle< JSPromise > internal_locked_promise, MaybeHandle< JSPromise > unlocked_promise, AsyncWaiterNodeType ** waiter_node, std::optional< base::TimeDelta > timeout = std::nullopt) [static]
Definition at line 862 of file js-atomics-synchronization.cc.
                                                                   {
  bool locked =
      LockImpl(requester, mutex, timeout, [=](std::atomic<StateT>* state) {
        return LockAsyncSlowPath(requester, mutex, state,
                                 internal_locked_promise, unlocked_promise,
                                 waiter_node, timeout);
      });
  if (locked) {
    // Resolve `internal_locked_promise` instead of synchronously running the
    // callback. This guarantees that the callback is run in a microtask
    // regardless of the current state of the mutex.
    MaybeDirectHandle<Object> result = JSPromise::Resolve(
        internal_locked_promise, requester->factory()->undefined_value());
    USE(result);
  } else {
    // If the promise is not resolved, keep it alive in a set in the native
    // context. The promise will be resolved and remove from the set in
    // `JSAtomicsMutex::HandleAsyncNotify` or
    // `JSAtomicsMutex::HandleAsyncTimeout`.
    AddPromiseToNativeContext(requester, internal_locked_promise);
  }
  return locked;
}
References v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::AddPromiseToNativeContext(), v8::internal::Isolate::factory(), LockAsyncSlowPath(), LockImpl(), v8::internal::JSPromise::Resolve(), v8::base::internal::result, and USE.
Referenced by LockAsyncWrapperForWait(), and LockOrEnqueuePromise().
LockAsyncSlowPath()
bool v8::internal::JSAtomicsMutex::LockAsyncSlowPath (Isolate * isolate, DirectHandle< JSAtomicsMutex > mutex, std::atomic< StateT > * state, Handle< JSPromise > internal_locked_promise, MaybeHandle< JSPromise > unlocked_promise, AsyncWaiterNodeType ** waiter_node, std::optional< base::TimeDelta > timeout) [static], [private]
Definition at line 902 of file js-atomics-synchronization.cc.
                                        {
  // Spin for a little bit to try to acquire the lock, so as to be fast under
  // microcontention.
  if (BackoffTryLock(isolate, mutex, state)) {
    return true;
  }
  // At this point the lock is considered contended, create a new async waiter
  // node in the C++ heap. It's lifetime is managed by the requester's
  // `async_waiter_queue_nodes` list.
  LockAsyncWaiterQueueNode* this_waiter =
      LockAsyncWaiterQueueNode::NewAsyncWaiterStoredInIsolate(
          isolate, mutex, internal_locked_promise, unlocked_promise);
  if (!MaybeEnqueueNode(isolate, mutex, state, this_waiter)) {
    return true;
  }
  if (timeout) {
    // Start a timer to run the `AsyncLockTimeoutTask` after the timeout.
    TaskRunner* taks_runner = this_waiter->task_runner();
    auto task = std::make_unique<AsyncLockTimeoutTask>(
        isolate->cancelable_task_manager(), this_waiter);
    this_waiter->timeout_task_id_ = task->id();
    taks_runner->PostNonNestableDelayedTask(std::move(task),
                                            timeout->InSecondsF());
  }
  *waiter_node = this_waiter;
  return false;
}
References BackoffTryLock(), v8::internal::Isolate::cancelable_task_manager(), MaybeEnqueueNode(), v8::internal::detail::AsyncWaiterQueueNode< T >::NewAsyncWaiterStoredInIsolate(), v8::TaskRunner::PostNonNestableDelayedTask(), v8::internal::detail::AsyncWaiterQueueNode< T >::task_runner(), and v8::internal::detail::AsyncWaiterQueueNode< T >::timeout_task_id_.
Referenced by LockAsync().
LockAsyncWrapperForWait()
DirectHandle< JSPromise > v8::internal::JSAtomicsMutex::LockAsyncWrapperForWait (Isolate * requester, DirectHandle< JSAtomicsMutex > mutex) [static]
Definition at line 892 of file js-atomics-synchronization.cc.
                                                            {
  Handle<JSPromise> internal_locked_promise =
      requester->factory()->NewJSPromise();
  AsyncWaiterNodeType* waiter_node = nullptr;
  LockAsync(requester, mutex, internal_locked_promise, {}, &waiter_node);
  return internal_locked_promise;
}
References v8::internal::Isolate::factory(), LockAsync(), and v8::internal::Factory::NewJSPromise().
Referenced by v8::internal::BUILTIN().
LockImpl()
template<typename LockSlowPathWrapper , typename >
bool v8::internal::JSAtomicsMutex::LockImpl (Isolate * requester, DirectHandle< JSAtomicsMutex > mutex, std::optional< base::TimeDelta > timeout, LockSlowPathWrapper slow_path_wrapper) [inline], [static], [private]
Definition at line 154 of file js-atomics-synchronization-inl.h.
                                                                     {
  DisallowGarbageCollection no_gc;
  // First try to lock an uncontended mutex, which should be the common case. If
  // this fails, then go to the slow path to possibly put the current thread to
  // sleep.
  //
  // The fast path is done using a weak CAS which may fail spuriously on
  // architectures with load-link/store-conditional instructions.
  std::atomic<StateT>* state = mutex->AtomicStatePtr();
  StateT expected = kUnlockedUncontended;
  bool locked;
  if (V8_LIKELY(state->compare_exchange_weak(expected, kLockedUncontended,
                                             std::memory_order_acquire,
                                             std::memory_order_relaxed))) {
    locked = true;
  } else {
    locked = slow_path_wrapper(state);
  }
  if (V8_LIKELY(locked)) {
    mutex->SetCurrentThreadAsOwner();
  }
  return locked;
}
References kLockedUncontended, kUnlockedUncontended, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and V8_LIKELY.
Referenced by Lock(), and LockAsync().
LockJSMutexOrDequeueTimedOutWaiter()
bool v8::internal::JSAtomicsMutex::LockJSMutexOrDequeueTimedOutWaiter (Isolate * requester, std::atomic< StateT > * state, WaiterQueueNode * timed_out_waiter) [private]
Definition at line 669 of file js-atomics-synchronization.cc.
                                       {
  // First acquire the queue lock, which is itself a spinlock.
  StateT current_state = state->load(std::memory_order_relaxed);
  // There are no waiters, but the js mutex lock may be held by another thread.
  if (!HasWaitersField::decode(current_state)) return false;
  // The details of updating the state in this function are too complicated
  // for the waiter queue lock guard to manage, so handle the state manually.
  while (!TryLockWaiterQueueExplicit(state, current_state)) {
    YIELD_PROCESSOR;
  }
  WaiterQueueNode* waiter_head = DestructivelyGetWaiterQueueHead(requester);
  if (waiter_head == nullptr) {
    // The queue is empty but the js mutex lock may be held by another thread,
    // release the waiter queue bit without changing the "is locked" bit.
    DCHECK(!HasWaitersField::decode(current_state));
    SetWaiterQueueStateOnly(state, kUnlockedUncontended);
    return false;
  }
  WaiterQueueNode* dequeued_node = WaiterQueueNode::DequeueMatching(
      &waiter_head,
      [&](WaiterQueueNode* node) { return node == timed_out_waiter; });
  // Release the queue lock and install the new waiter queue head.
  DCHECK_EQ(state->load(),
            IsWaiterQueueLockedField::update(current_state, true));
  StateT new_state = kUnlockedUncontended;
  new_state = SetWaiterQueueHead(requester, waiter_head, new_state);
  if (!dequeued_node) {
    // The timed out waiter was not in the queue, so it must have been dequeued
    // and notified between the time this thread woke up and the time it
    // acquired the queue lock, so there is a risk that the next queue head is
    // never notified. Try to take the js mutex lock here, if we succeed, the
    // next node will be notified by this thread, otherwise, it will be notified
    // by the thread holding the lock now.
    // Since we use strong CAS below, we know that the js mutex lock will be
    // held by either this thread or another thread that can't go through the
    // unlock fast path because this thread is holding the waiter queue lock.
    // Hence, it is safe to always set the "is locked" bit in new_state.
    new_state = IsLockedField::update(new_state, true);
    DCHECK(!IsWaiterQueueLockedField::decode(new_state));
    current_state = IsLockedField::update(current_state, false);
    if (state->compare_exchange_strong(current_state, new_state,
                                       std::memory_order_acq_rel,
                                       std::memory_order_relaxed)) {
      // The CAS atomically released the waiter queue lock and acquired the js
      // mutex lock.
      return true;
    }
    DCHECK(IsLockedField::decode(state->load()));
    state->store(new_state, std::memory_order_release);
    return false;
  }
  SetWaiterQueueStateOnly(state, new_state);
  return false;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::detail::WaiterQueueNode::DequeueMatching(), kUnlockedUncontended, v8::base::BitField< T, shift, size, U >::update(), and YIELD_PROCESSOR.
LockOrEnqueueAsyncNode()
bool v8::internal::JSAtomicsMutex::LockOrEnqueueAsyncNode (Isolate * isolate, DirectHandle< JSAtomicsMutex > mutex, LockAsyncWaiterQueueNode * node) [static]
Definition at line 938 of file js-atomics-synchronization.cc.
                                                                              {
  std::atomic<StateT>* state = mutex->AtomicStatePtr();
  // Spin for a little bit to try to acquire the lock, so as to be fast under
  // microcontention.
  if (BackoffTryLock(isolate, mutex, state)) {
    return true;
  }
  return !MaybeEnqueueNode(isolate, mutex, state, waiter);
}
References BackoffTryLock(), and MaybeEnqueueNode().
Referenced by HandleAsyncNotify().
LockOrEnqueuePromise()
MaybeDirectHandle< JSPromise > v8::internal::JSAtomicsMutex::LockOrEnqueuePromise (Isolate * isolate, DirectHandle< JSAtomicsMutex > mutex, DirectHandle< Object > callback, std::optional< base::TimeDelta > timeout) [static]
Definition at line 821 of file js-atomics-synchronization.cc.
                                                                       {
  Handle<JSPromise> internal_locked_promise =
      requester->factory()->NewJSPromise();
  DirectHandle<JSReceiver> waiting_for_callback_promise;
  ASSIGN_RETURN_ON_EXCEPTION(
      requester, waiting_for_callback_promise,
      PerformPromiseThen(requester, internal_locked_promise, callback));
  Handle<JSPromise> unlocked_promise = requester->factory()->NewJSPromise();
  // Set the async unlock handlers here so we can throw without any additional
  // cleanup if the inner `promise_then` call fails. Keep a reference to
  // the handlers' synthetic context so we can store the waiter node in it once
  // the node is created.
  DirectHandle<Context> handlers_context;
  ASSIGN_RETURN_ON_EXCEPTION(
      requester, handlers_context,
      SetAsyncUnlockHandlers(requester, mutex, waiting_for_callback_promise,
                             unlocked_promise));
  LockAsyncWaiterQueueNode* waiter_node = nullptr;
  bool locked = LockAsync(requester, mutex, internal_locked_promise,
                          unlocked_promise, &waiter_node, timeout);
  if (locked) {
    // Create an LockAsyncWaiterQueueNode to be queued in the async locked
    // waiter queue.
    DCHECK(!waiter_node);
    waiter_node = LockAsyncWaiterQueueNode::NewLockedAsyncWaiterStoredInIsolate(
        requester, mutex);
  }
  // Don't use kWaiterQueueNodeTag here as that will cause the pointer to be
  // stored in the shared external pointer table, which is not necessary since
  // this object is only visible in this thread.
  DirectHandle<Foreign> wrapper =
      requester->factory()->NewForeign<kWaiterQueueForeignTag>(
          reinterpret_cast<Address>(waiter_node));
  handlers_context->SetNoCell(
      JSAtomicsMutex::kAsyncLockedWaiterAsyncContextSlot, *wrapper);
  return unlocked_promise;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), v8::internal::Isolate::factory(), kAsyncLockedWaiterAsyncContextSlot, v8::internal::kWaiterQueueForeignTag, LockAsync(), v8::internal::Factory::NewForeign(), v8::internal::Factory::NewJSPromise(), v8::internal::detail::AsyncWaiterQueueNode< T >::NewLockedAsyncWaiterStoredInIsolate(), v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::PerformPromiseThen(), and v8::internal::anonymous_namespace{js-atomics-synchronization.cc}::SetAsyncUnlockHandlers().
Referenced by v8::internal::BUILTIN().
LockSlowPath()
bool v8::internal::JSAtomicsMutex::LockSlowPath (Isolate * requester, DirectHandle< JSAtomicsMutex > mutex, std::atomic< StateT > * state, std::optional< base::TimeDelta > timeout) [static], [private]
Definition at line 736 of file js-atomics-synchronization.cc.
                                                                      {
  for (;;) {
    // Spin for a little bit to try to acquire the lock, so as to be fast under
    // microcontention.
    if (BackoffTryLock(requester, mutex, state)) return true;
    // At this point the lock is considered contended, so try to go to sleep and
    // put the requester thread on the waiter queue.
    // Allocate a waiter queue node on-stack, since this thread is going to
    // sleep and will be blocked anyway.
    SyncWaiterQueueNode this_waiter(requester);
    if (!MaybeEnqueueNode(requester, mutex, state, &this_waiter)) return true;
    bool rv;
    // Wait for another thread to release the lock and wake us up.
    if (timeout) {
      rv = this_waiter.WaitFor(*timeout);
      // Reload the state pointer after wake up in case of shared GC while
      // blocked.
      state = mutex->AtomicStatePtr();
      if (!rv) {
        // If timed out, remove ourself from the waiter list, which is usually
        // done by the thread performing the notifying.
        rv = mutex->LockJSMutexOrDequeueTimedOutWaiter(requester, state,
                                                       &this_waiter);
        return rv;
      }
    } else {
      this_waiter.Wait();
      // Reload the state pointer after wake up in case of shared GC while
      // blocked.
      state = mutex->AtomicStatePtr();
    }
    // After wake up we try to acquire the lock again by spinning, as the
    // contention at the point of going to sleep should not be correlated with
    // contention at the point of waking up.
  }
}
References BackoffTryLock(), MaybeEnqueueNode(), v8::internal::detail::SyncWaiterQueueNode::Wait(), and v8::internal::detail::SyncWaiterQueueNode::WaitFor().
Referenced by Lock().
LockWaiterQueueOrJSMutex()
std::optional< WaiterQueueLockGuard > v8::internal::JSAtomicsMutex::LockWaiterQueueOrJSMutex (std::atomic< StateT > * state, StateT & current_state) [static], [private]
Definition at line 655 of file js-atomics-synchronization.cc.
                                                     {
  for (;;) {
    if (IsLockedField::decode(current_state) &&
        TryLockWaiterQueueExplicit(state, current_state)) {
      return WaiterQueueLockGuard::NewAlreadyLockedWaiterQueueLockGuard(state);
    }
    // Also check for the lock having been released by another thread during
    // attempts to acquire the queue lock.
    if (TryLockExplicit(state, current_state)) return std::nullopt;
    YIELD_PROCESSOR;
  }
}
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::detail::WaiterQueueLockGuard::NewAlreadyLockedWaiterQueueLockGuard(), TryLockExplicit(), and YIELD_PROCESSOR.
Referenced by MaybeEnqueueNode().
MaybeEnqueueNode()
bool v8::internal::JSAtomicsMutex::MaybeEnqueueNode (Isolate * requester, DirectHandle< JSAtomicsMutex > mutex, std::atomic< StateT > * state, WaiterQueueNode * this_waiter) [static], [private]
Definition at line 621 of file js-atomics-synchronization.cc.
                                                                    {
  DCHECK_NOT_NULL(this_waiter);
  // Try to acquire the queue lock, which is itself a spinlock.
  StateT current_state = state->load(std::memory_order_relaxed);
  std::optional<WaiterQueueLockGuard> waiter_queue_lock_guard =
      LockWaiterQueueOrJSMutex(state, current_state);
  if (!waiter_queue_lock_guard.has_value()) {
    // There is no waiter queue lock guard, so the lock was acquired.
    DCHECK(IsLockedField::decode(state->load()));
    return false;
  }
  // With the queue lock held, enqueue the requester onto the waiter queue.
  WaiterQueueNode* waiter_head =
      mutex->DestructivelyGetWaiterQueueHead(requester);
  WaiterQueueNode::Enqueue(&waiter_head, this_waiter);
  // Enqueue a new waiter queue head and release the queue lock.
  DCHECK_EQ(state->load(),
            IsWaiterQueueLockedField::update(current_state, true));
  StateT new_state =
      mutex->SetWaiterQueueHead(requester, waiter_head, current_state);
  // The lock is held, just not by us, so don't set the current thread id as
  // the owner.
  DCHECK(IsLockedField::decode(current_state));
  new_state = IsLockedField::update(new_state, true);
  waiter_queue_lock_guard->set_new_state(new_state);
  return true;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::detail::WaiterQueueNode::Enqueue(), LockWaiterQueueOrJSMutex(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by LockAsyncSlowPath(), LockOrEnqueueAsyncNode(), and LockSlowPath().
MutexTryLock()
static V8_EXPORT_PRIVATE bool v8::internal::JSAtomicsMutex::MutexTryLock (Isolate * requester, DirectHandle< JSAtomicsMutex > mutex, std::atomic< StateT > * state) [static], [private]
SetCurrentThreadAsOwner()
void v8::internal::JSAtomicsMutex::SetCurrentThreadAsOwner () [inline], [private]
Definition at line 234 of file js-atomics-synchronization-inl.h.
                                             {
  AtomicOwnerThreadIdPtr()->store(ThreadId::Current().ToInteger(),
                                  std::memory_order_relaxed);
}
References AtomicOwnerThreadIdPtr(), and v8::internal::ThreadId::Current().
Referenced by TryLock().
TryLock()
bool v8::internal::JSAtomicsMutex::TryLock () [inline]
Definition at line 190 of file js-atomics-synchronization-inl.h.
                             {
  DisallowGarbageCollection no_gc;
  StateT expected = kUnlockedUncontended;
  if (V8_LIKELY(AtomicStatePtr()->compare_exchange_strong(
          expected, kLockedUncontended, std::memory_order_acquire,
          std::memory_order_relaxed))) {
    SetCurrentThreadAsOwner();
    return true;
  }
  return false;
}
References kLockedUncontended, kUnlockedUncontended, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, SetCurrentThreadAsOwner(), and V8_LIKELY.
TryLockExplicit()
bool v8::internal::JSAtomicsMutex::TryLockExplicit (std::atomic< StateT > * state, StateT & expected) [static], [private]
Definition at line 589 of file js-atomics-synchronization.cc.
                                                       {
  // Try to lock a possibly contended mutex.
  expected = IsLockedField::update(expected, false);
  return state->compare_exchange_weak(
      expected, IsLockedField::update(expected, true),
      std::memory_order_acquire, std::memory_order_relaxed);
}
References v8::base::BitField< T, shift, size, U >::update().
Referenced by BackoffTryLock(), and LockWaiterQueueOrJSMutex().
Unlock()
void v8::internal::JSAtomicsMutex::Unlock (Isolate * requester) [inline]
Definition at line 202 of file js-atomics-synchronization-inl.h.
                                              {
  DisallowGarbageCollection no_gc;
  // First try to unlock an uncontended mutex, which should be the common
  // case. If this fails, then go to the slow path to wake a waiting thread.
  //
  // In contrast to Lock, the fast path is done using a strong CAS which does
  // not fail spuriously. This simplifies the slow path by guaranteeing that
  // there is at least one waiter to be notified.
  DCHECK(IsCurrentThreadOwner());
  ClearOwnerThread();
  std::atomic<StateT>* state = AtomicStatePtr();
  StateT expected = kLockedUncontended;
  if (V8_LIKELY(state->compare_exchange_strong(expected, kUnlockedUncontended,
                                               std::memory_order_release,
                                               std::memory_order_relaxed))) {
    return;
  }
  UnlockSlowPath(requester, state);
}
References ClearOwnerThread(), v8::internal::DCHECK(), IsCurrentThreadOwner(), kLockedUncontended, kUnlockedUncontended, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, UnlockSlowPath(), and V8_LIKELY.
Referenced by UnlockAsyncLockedMutex().
UnlockAsyncLockedMutex()
void v8::internal::JSAtomicsMutex::UnlockAsyncLockedMutex (Isolate * requester, DirectHandle< Foreign > async_locked_waiter_wrapper)
Definition at line 951 of file js-atomics-synchronization.cc.
                                                                           {
  LockAsyncWaiterQueueNode* waiter_node =
      reinterpret_cast<LockAsyncWaiterQueueNode*>(
          async_locked_waiter_wrapper->foreign_address<kWaiterQueueForeignTag>(
              IsolateForSandbox(requester)));
  LockAsyncWaiterQueueNode::RemoveFromAsyncWaiterQueueList(waiter_node);
  if (IsCurrentThreadOwner()) {
    Unlock(requester);
    return;
  }
  // If this is reached, the lock was already released by this thread.
  // This can happen if waitAsync is called without awaiting or due to
  // promise prototype tampering. Setting Promise.prototype.then to a
  // non callable will cause the `waiting_for_callback_promise` (defined in
  // LockOrEnqueuePromise) reactions to be called even if the async callback
  // is not resolved; as a consequence, the following code will try to unlock
  // the mutex twice:
  //
  // let mutex = new Atomics.Mutex();
  // let cv = new Atomics.Condition();
  // Promise.prototype.then = undefined;
  // Atomics.Mutex.lockAsync(mutex, async function() {
  // await Atomics.Condition.waitAsync(cv, mutex);
  // }
}
References IsCurrentThreadOwner(), v8::internal::kWaiterQueueForeignTag, v8::internal::detail::AsyncWaiterQueueNode< T >::RemoveFromAsyncWaiterQueueList(), and Unlock().
UnlockSlowPath()
void v8::internal::JSAtomicsMutex::UnlockSlowPath (Isolate * requester, std::atomic< StateT > * state) [private]
Definition at line 780 of file js-atomics-synchronization.cc.
                                                              {
  // The fast path unconditionally cleared the owner thread.
  DCHECK_EQ(ThreadId::Invalid().ToInteger(),
            AtomicOwnerThreadIdPtr()->load(std::memory_order_relaxed));
  // To wake a sleeping thread, first acquire the queue lock, which is itself
  // a spinlock.
  StateT current_state = state->load(std::memory_order_relaxed);
  WaiterQueueLockGuard waiter_queue_lock_guard(state, current_state);
  if (!HasWaitersField::decode(current_state)) {
    // All waiters were removed while waiting for the queue lock, possibly by
    // timing out. Release both the lock and the queue lock.
    StateT new_state = IsLockedField::update(current_state, false);
    waiter_queue_lock_guard.set_new_state(new_state);
    return;
  }
  WaiterQueueNode* waiter_head = DestructivelyGetWaiterQueueHead(requester);
  DCHECK_NOT_NULL(waiter_head);
  WaiterQueueNode* old_head = WaiterQueueNode::Dequeue(&waiter_head);
  // Release both the lock and the queue lock, and install the new waiter queue
  // head.
  StateT new_state = IsLockedField::update(current_state, false);
  new_state = SetWaiterQueueHead(requester, waiter_head, new_state);
  waiter_queue_lock_guard.set_new_state(new_state);
  old_head->Notify();
}
References AtomicOwnerThreadIdPtr(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::detail::WaiterQueueNode::Dequeue(), v8::internal::ThreadId::Invalid(), v8::internal::detail::WaiterQueueNode::Notify(), v8::internal::detail::WaiterQueueLockGuard::set_new_state(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by Unlock().
Friends And Related Function Documentation
Factory
friend class Factory [friend]
Definition at line 296 of file js-atomics-synchronization.h.
Member Data Documentation
kLockedUncontended
constexpr StateT v8::internal::JSAtomicsMutex::kLockedUncontended = IsLockedField::encode(true) [static], [constexpr], [private]
Definition at line 304 of file js-atomics-synchronization.h.
Referenced by LockImpl(), TryLock(), and Unlock().
kUnlockedUncontended
constexpr StateT v8::internal::JSAtomicsMutex::kUnlockedUncontended = kEmptyState [static], [constexpr], [private]
Definition at line 303 of file js-atomics-synchronization.h.
Referenced by CleanupMatchingAsyncWaiters(), DequeueTimedOutAsyncWaiter(), LockImpl(), LockJSMutexOrDequeueTimedOutWaiter(), v8::internal::Factory::NewJSAtomicsMutex(), TryLock(), and Unlock().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-atomics-synchronization.h
/mnt/V8SourceCode/src/objects/js-atomics-synchronization-inl.h
/mnt/V8SourceCode/src/objects/js-atomics-synchronization.cc