v8::internal::WriteBarrierCodeStubAssembler Class Reference
Public Member Functions
WriteBarrierCodeStubAssembler (compiler::CodeAssemblerState *state)
TNode< BoolT > IsMarking ()
TNode< BoolT > IsMinorMarking ()
TNode< BoolT > IsSharedSpaceIsolate ()
TNode< BoolT > UsesSharedHeap ()
TNode< BoolT > IsUnmarked (TNode< IntPtrT > object)
void InsertIntoRememberedSet (TNode< IntPtrT > object, TNode< IntPtrT > slot, SaveFPRegsMode fp_mode)
TNode< IntPtrT > LoadSlotSet (TNode< IntPtrT > page, Label *slow_path)
TNode< IntPtrT > LoadBucket (TNode< IntPtrT > slot_set, TNode< WordT > slot_offset, TNode< IntPtrT > num_buckets, Label *slow_path)
void SetBitInCell (TNode< IntPtrT > bucket, TNode< WordT > slot_offset)
void WriteBarrier (SaveFPRegsMode fp_mode)
void IndirectPointerWriteBarrier (SaveFPRegsMode fp_mode)
void GenerationalOrSharedBarrierSlow (TNode< IntPtrT > slot, Label *next, SaveFPRegsMode fp_mode)
void GenerationalBarrierSlow (TNode< IntPtrT > slot, Label *next, SaveFPRegsMode fp_mode)
void SharedBarrierSlow (TNode< IntPtrT > slot, Label *next, SaveFPRegsMode fp_mode)
void WriteBarrierDuringMarking (TNode< IntPtrT > slot, Label *next, SaveFPRegsMode fp_mode)
void GenerationalOrSharedBarrierDuringMarking (TNode< IntPtrT > slot, Label *next, SaveFPRegsMode fp_mode)
void InYoungGeneration (TNode< IntPtrT > object, Label *true_label, Label *false_label)
void InSharedHeap (TNode< IntPtrT > object, Label *true_label, Label *false_label)
void IncrementalWriteBarrierMinor (TNode< IntPtrT > slot, TNode< IntPtrT > value, SaveFPRegsMode fp_mode, Label *next)
void IncrementalWriteBarrierMajor (TNode< IntPtrT > slot, TNode< IntPtrT > value, SaveFPRegsMode fp_mode, Label *next)
void IsValueUnmarkedOrRecordSlot (TNode< IntPtrT > value, Label *true_label, Label *false_label)
void IncrementalWriteBarrier (TNode< IntPtrT > slot, SaveFPRegsMode fp_mode)
void IncrementalWriteBarrierShared (TNode< IntPtrT > object, TNode< IntPtrT > slot, TNode< IntPtrT > value, SaveFPRegsMode fp_mode, Label *next)
void IncrementalWriteBarrierLocal (TNode< IntPtrT > slot, TNode< IntPtrT > value, SaveFPRegsMode fp_mode, Label *next)
void GenerateRecordWrite (SaveFPRegsMode fp_mode)
void GenerateIndirectPointerBarrier (SaveFPRegsMode fp_mode)
void GenerateEphemeronKeyBarrier (SaveFPRegsMode fp_mode)
Additional Inherited Members
Detailed Description
Definition at line 119 of file builtins-internal-gen.cc.
Constructor & Destructor Documentation
WriteBarrierCodeStubAssembler()
v8::internal::WriteBarrierCodeStubAssembler::WriteBarrierCodeStubAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 121 of file builtins-internal-gen.cc.
      : CodeStubAssembler(state) {}
Member Function Documentation
GenerateEphemeronKeyBarrier()
void v8::internal::WriteBarrierCodeStubAssembler::GenerateEphemeronKeyBarrier (SaveFPRegsMode fp_mode) [inline]
Definition at line 587 of file builtins-internal-gen.cc.
                                                           {
    TNode<ExternalReference> function = ExternalConstant(
        ExternalReference::ephemeron_key_write_barrier_function());
    TNode<ExternalReference> isolate_constant =
        ExternalConstant(ExternalReference::isolate_address());
    // In this method we limit the allocatable registers so we have to use
    // UncheckedParameter. Parameter does not work because the checked cast
    // needs more registers.
    auto address =
        UncheckedParameter<IntPtrT>(WriteBarrierDescriptor::kSlotAddress);
    TNode<IntPtrT> object = BitcastTaggedToWord(
        UncheckedParameter<Object>(WriteBarrierDescriptor::kObject));
    CallCFunctionWithCallerSavedRegisters(
        function, MachineTypeOf<Int32T>::value, fp_mode,
        std::make_pair(MachineTypeOf<IntPtrT>::value, object),
        std::make_pair(MachineTypeOf<IntPtrT>::value, address),
        std::make_pair(MachineTypeOf<ExternalReference>::value,
                       isolate_constant));
    IncrementCounter(isolate()->counters()->write_barriers(), 1);
    Return(TrueConstant());
  }
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::CallCFunctionWithCallerSavedRegisters(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::CodeStubAssembler::IncrementCounter(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::ExternalReference::isolate_address(), and v8::internal::compiler::CodeAssembler::Return().
GenerateIndirectPointerBarrier()
void v8::internal::WriteBarrierCodeStubAssembler::GenerateIndirectPointerBarrier (SaveFPRegsMode fp_mode) [inline]
Definition at line 571 of file builtins-internal-gen.cc.
                                                              {
    if (V8_DISABLE_WRITE_BARRIERS_BOOL) {
      Return(TrueConstant());
      return;
    }
    if (!V8_ENABLE_SANDBOX_BOOL) {
      Unreachable();
      return;
    }
    IndirectPointerWriteBarrier(fp_mode);
    IncrementCounter(isolate()->counters()->write_barriers(), 1);
    Return(TrueConstant());
  }
References v8::internal::CodeStubAssembler::IncrementCounter(), IndirectPointerWriteBarrier(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::compiler::CodeAssembler::Return(), v8::internal::compiler::CodeAssembler::Unreachable(), V8_DISABLE_WRITE_BARRIERS_BOOL, and V8_ENABLE_SANDBOX_BOOL.
GenerateRecordWrite()
void v8::internal::WriteBarrierCodeStubAssembler::GenerateRecordWrite (SaveFPRegsMode fp_mode) [inline]
Definition at line 560 of file builtins-internal-gen.cc.
                                                   {
    if (V8_DISABLE_WRITE_BARRIERS_BOOL) {
      Return(TrueConstant());
      return;
    }
    WriteBarrier(fp_mode);
    IncrementCounter(isolate()->counters()->write_barriers(), 1);
    Return(TrueConstant());
  }
References v8::internal::CodeStubAssembler::IncrementCounter(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::compiler::CodeAssembler::Return(), V8_DISABLE_WRITE_BARRIERS_BOOL, and WriteBarrier().
GenerationalBarrierSlow()
void v8::internal::WriteBarrierCodeStubAssembler::GenerationalBarrierSlow (TNode< IntPtrT > slot, Label * next, SaveFPRegsMode fp_mode) [inline]
Definition at line 306 of file builtins-internal-gen.cc.
                                                       {
    TNode<IntPtrT> object = BitcastTaggedToWord(
        UncheckedParameter<Object>(WriteBarrierDescriptor::kObject));
    InsertIntoRememberedSet(object, slot, fp_mode);
    Goto(next);
  }
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::Goto(), and InsertIntoRememberedSet().
Referenced by GenerationalOrSharedBarrierDuringMarking(), and GenerationalOrSharedBarrierSlow().
GenerationalOrSharedBarrierDuringMarking()
void v8::internal::WriteBarrierCodeStubAssembler::GenerationalOrSharedBarrierDuringMarking (TNode< IntPtrT > slot, Label * next, SaveFPRegsMode fp_mode) [inline]
Definition at line 341 of file builtins-internal-gen.cc.
                                                                        {
    Label generational_barrier_check(this), shared_barrier_check(this),
        shared_barrier_slow(this), generational_barrier_slow(this);
    // During incremental marking we always reach this slow path, so we need to
    // check whether this is an old-to-new or old-to-shared reference.
    TNode<IntPtrT> object = BitcastTaggedToWord(
        UncheckedParameter<Object>(WriteBarrierDescriptor::kObject));
    if (!v8_flags.sticky_mark_bits) {
      // With sticky markbits we know everything will be old after the GC so no
      // need to check the age.
      InYoungGeneration(object, next, &generational_barrier_check);
      BIND(&generational_barrier_check);
    }
    TNode<IntPtrT> value = BitcastTaggedToWord(Load<HeapObject>(slot));
    if (!v8_flags.sticky_mark_bits) {
      // With sticky markbits we know everything will be old after the GC so no
      // need to track old-to-new references.
      InYoungGeneration(value, &generational_barrier_slow,
                        &shared_barrier_check);
      BIND(&generational_barrier_slow);
      GenerationalBarrierSlow(slot, next, fp_mode);
      BIND(&shared_barrier_check);
    }
    InSharedHeap(value, &shared_barrier_slow, next);
    BIND(&shared_barrier_slow);
    SharedBarrierSlow(slot, next, fp_mode);
  }
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), GenerationalBarrierSlow(), InSharedHeap(), InYoungGeneration(), SharedBarrierSlow(), v8::internal::v8_flags, and v8::internal::value.
Referenced by WriteBarrierDuringMarking().
GenerationalOrSharedBarrierSlow()
void v8::internal::WriteBarrierCodeStubAssembler::GenerationalOrSharedBarrierSlow (TNode< IntPtrT > slot, Label * next, SaveFPRegsMode fp_mode) [inline]
Definition at line 280 of file builtins-internal-gen.cc.
                                                               {
    // When incremental marking is not on, the fast and out-of-line fast path of
    // the write barrier already checked whether we need to run the generational
    // or shared barrier slow path.
    Label generational_barrier(this), shared_barrier(this);
    TNode<IntPtrT> value = BitcastTaggedToWord(Load<HeapObject>(slot));
    InYoungGeneration(value, &generational_barrier, &shared_barrier);
    BIND(&generational_barrier);
    if (!v8_flags.sticky_mark_bits) {
      CSA_DCHECK(this,
                 IsPageFlagSet(value, MemoryChunk::kIsInYoungGenerationMask));
    }
    GenerationalBarrierSlow(slot, next, fp_mode);
    // TODO(333906585): With sticky-mark bits and without the shared barrier
    // support, we actually never jump here. Don't put it under the flag though,
    // since the assert below has been useful.
    BIND(&shared_barrier);
    CSA_DCHECK(this, IsPageFlagSet(value, MemoryChunk::kInSharedHeap));
    SharedBarrierSlow(slot, next, fp_mode);
  }
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), GenerationalBarrierSlow(), InYoungGeneration(), v8::internal::CodeStubAssembler::IsPageFlagSet(), v8::internal::MemoryChunk::kInSharedHeap, v8::internal::MemoryChunk::kIsInYoungGenerationMask, SharedBarrierSlow(), v8::internal::v8_flags, and v8::internal::value.
Referenced by WriteBarrier().
IncrementalWriteBarrier()
void v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrier (TNode< IntPtrT > slot, SaveFPRegsMode fp_mode) [inline]
Definition at line 482 of file builtins-internal-gen.cc.
                                                                            {
    Label next(this), write_into_shared_object(this),
        write_into_local_object(this),
        local_object_and_value(this, Label::kDeferred);
    TNode<IntPtrT> object = BitcastTaggedToWord(
        UncheckedParameter<Object>(WriteBarrierDescriptor::kObject));
    TNode<IntPtrT> value = BitcastTaggedToWord(Load<HeapObject>(slot));
    // Without a shared heap, all objects are local. This is the fast path
    // always used when no shared heap exists.
    GotoIfNot(UsesSharedHeap(), &local_object_and_value);
    // From the point-of-view of the shared space isolate (= the main isolate)
    // shared heap objects are just local objects.
    GotoIf(IsSharedSpaceIsolate(), &local_object_and_value);
    // These checks here are now only reached by client isolates (= worker
    // isolates). Now first check whether incremental marking is activated for
    // that particular object's space. Incrementally marking might only be
    // enabled for either local or shared objects on client isolates.
    GotoIfNot(IsPageFlagSet(object, MemoryChunk::kIncrementalMarking), &next);
    // We now know that incremental marking is enabled for the given object.
    // Decide whether to run the shared or local incremental marking barrier.
    InSharedHeap(object, &write_into_shared_object, &write_into_local_object);
    BIND(&write_into_shared_object);
    // Run the shared incremental marking barrier.
    IncrementalWriteBarrierShared(object, slot, value, fp_mode, &next);
    BIND(&write_into_local_object);
    // When writing into a local object we can ignore stores of shared object
    // values since for those no slot recording or marking is required.
    InSharedHeap(value, &next, &local_object_and_value);
    // Both object and value are now guaranteed to be local objects, run the
    // local incremental marking barrier.
    BIND(&local_object_and_value);
    IncrementalWriteBarrierLocal(slot, value, fp_mode, &next);
    BIND(&next);
  }
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), IncrementalWriteBarrierLocal(), IncrementalWriteBarrierShared(), InSharedHeap(), v8::internal::CodeStubAssembler::IsPageFlagSet(), IsSharedSpaceIsolate(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::MemoryChunk::kIncrementalMarking, UsesSharedHeap(), and v8::internal::value.
Referenced by WriteBarrierDuringMarking().
IncrementalWriteBarrierLocal()
void v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierLocal (TNode< IntPtrT > slot, TNode< IntPtrT > value, SaveFPRegsMode fp_mode, Label * next) [inline]
Definition at line 548 of file builtins-internal-gen.cc.
                                                                         {
    Label is_minor(this), is_major(this);
    Branch(IsMinorMarking(), &is_minor, &is_major);
    BIND(&is_minor);
    IncrementalWriteBarrierMinor(slot, value, fp_mode, next);
    BIND(&is_major);
    IncrementalWriteBarrierMajor(slot, value, fp_mode, next);
  }
References v8::internal::compiler::CodeAssembler::Branch(), IncrementalWriteBarrierMajor(), IncrementalWriteBarrierMinor(), IsMinorMarking(), and v8::internal::value.
Referenced by IncrementalWriteBarrier().
IncrementalWriteBarrierMajor()
void v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierMajor (TNode< IntPtrT > slot, TNode< IntPtrT > value, SaveFPRegsMode fp_mode, Label * next) [inline]
Definition at line 438 of file builtins-internal-gen.cc.
                                                                         {
    Label marking_cpp_slow_path(this);
    IsValueUnmarkedOrRecordSlot(value, &marking_cpp_slow_path, next);
    BIND(&marking_cpp_slow_path);
    {
      TNode<ExternalReference> function = ExternalConstant(
          ExternalReference::write_barrier_marking_from_code_function());
      TNode<IntPtrT> object = BitcastTaggedToWord(
          UncheckedParameter<Object>(WriteBarrierDescriptor::kObject));
      CallCFunctionWithCallerSavedRegisters(
          function, MachineTypeOf<Int32T>::value, fp_mode,
          std::make_pair(MachineTypeOf<IntPtrT>::value, object),
          std::make_pair(MachineTypeOf<IntPtrT>::value, slot));
      Goto(next);
    }
  }
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::CallCFunctionWithCallerSavedRegisters(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Goto(), IsValueUnmarkedOrRecordSlot(), and v8::internal::value.
Referenced by IncrementalWriteBarrierLocal().
IncrementalWriteBarrierMinor()
void v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierMinor (TNode< IntPtrT > slot, TNode< IntPtrT > value, SaveFPRegsMode fp_mode, Label * next) [inline]
Definition at line 411 of file builtins-internal-gen.cc.
                                                                         {
    Label check_is_unmarked(this, Label::kDeferred);
    if (!v8_flags.sticky_mark_bits) {
      // With sticky markbits, InYoungGeneration and IsUnmarked below are
      // equivalent.
      InYoungGeneration(value, &check_is_unmarked, next);
      BIND(&check_is_unmarked);
    }
    GotoIfNot(IsUnmarked(value), next);
    {
      TNode<ExternalReference> function = ExternalConstant(
          ExternalReference::write_barrier_marking_from_code_function());
      TNode<IntPtrT> object = BitcastTaggedToWord(
          UncheckedParameter<Object>(WriteBarrierDescriptor::kObject));
      CallCFunctionWithCallerSavedRegisters(
          function, MachineTypeOf<Int32T>::value, fp_mode,
          std::make_pair(MachineTypeOf<IntPtrT>::value, object),
          std::make_pair(MachineTypeOf<IntPtrT>::value, slot));
      Goto(next);
    }
  }
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::CallCFunctionWithCallerSavedRegisters(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIfNot(), InYoungGeneration(), IsUnmarked(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::v8_flags, and v8::internal::value.
Referenced by IncrementalWriteBarrierLocal().
IncrementalWriteBarrierShared()
void v8::internal::WriteBarrierCodeStubAssembler::IncrementalWriteBarrierShared (TNode< IntPtrT > object, TNode< IntPtrT > slot, TNode< IntPtrT > value, SaveFPRegsMode fp_mode, Label * next) [inline]
Definition at line 528 of file builtins-internal-gen.cc.
                                                                          {
    Label shared_marking_cpp_slow_path(this);
    IsValueUnmarkedOrRecordSlot(value, &shared_marking_cpp_slow_path, next);
    BIND(&shared_marking_cpp_slow_path);
    {
      TNode<ExternalReference> function = ExternalConstant(
          ExternalReference::write_barrier_shared_marking_from_code_function());
      CallCFunctionWithCallerSavedRegisters(
          function, MachineTypeOf<Int32T>::value, fp_mode,
          std::make_pair(MachineTypeOf<IntPtrT>::value, object),
          std::make_pair(MachineTypeOf<IntPtrT>::value, slot));
      Goto(next);
    }
  }
References v8::internal::compiler::CodeAssembler::CallCFunctionWithCallerSavedRegisters(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Goto(), IsValueUnmarkedOrRecordSlot(), and v8::internal::value.
Referenced by IncrementalWriteBarrier().
IndirectPointerWriteBarrier()
void v8::internal::WriteBarrierCodeStubAssembler::IndirectPointerWriteBarrier (SaveFPRegsMode fp_mode) [inline]
Definition at line 256 of file builtins-internal-gen.cc.
                                                           {
    CSA_DCHECK(this, IsMarking());
    // For this barrier, the slot contains an index into a pointer table and not
    // directly a pointer to a HeapObject. Further, the slot address is tagged
    // with the indirect pointer tag of the slot, so it cannot directly be
    // dereferenced but needs to be decoded first.
    TNode<IntPtrT> slot = UncheckedParameter<IntPtrT>(
        IndirectPointerWriteBarrierDescriptor::kSlotAddress);
    TNode<IntPtrT> object = BitcastTaggedToWord(UncheckedParameter<Object>(
        IndirectPointerWriteBarrierDescriptor::kObject));
    TNode<IntPtrT> tag = UncheckedParameter<IntPtrT>(
        IndirectPointerWriteBarrierDescriptor::kIndirectPointerTag);
    TNode<ExternalReference> function = ExternalConstant(
        ExternalReference::
            write_barrier_indirect_pointer_marking_from_code_function());
    CallCFunctionWithCallerSavedRegisters(
        function, MachineTypeOf<Int32T>::value, fp_mode,
        std::make_pair(MachineTypeOf<IntPtrT>::value, object),
        std::make_pair(MachineTypeOf<IntPtrT>::value, slot),
        std::make_pair(MachineTypeOf<IntPtrT>::value, tag));
  }
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::CallCFunctionWithCallerSavedRegisters(), v8::internal::compiler::CodeAssembler::ExternalConstant(), and IsMarking().
Referenced by GenerateIndirectPointerBarrier().
InsertIntoRememberedSet()
void v8::internal::WriteBarrierCodeStubAssembler::InsertIntoRememberedSet (TNode< IntPtrT > object, TNode< IntPtrT > slot, SaveFPRegsMode fp_mode) [inline]
Definition at line 160 of file builtins-internal-gen.cc.
                                                       {
    Label slow_path(this), next(this);
    TNode<IntPtrT> chunk = MemoryChunkFromAddress(object);
    TNode<IntPtrT> page = PageMetadataFromMemoryChunk(chunk);
    // Load address of SlotSet
    TNode<IntPtrT> slot_set = LoadSlotSet(page, &slow_path);
    TNode<IntPtrT> slot_offset = IntPtrSub(slot, chunk);
    TNode<IntPtrT> num_buckets_address =
        IntPtrSub(slot_set, IntPtrConstant(SlotSet::kNumBucketsSize));
    TNode<IntPtrT> num_buckets = UncheckedCast<IntPtrT>(
        Load(MachineType::Pointer(), num_buckets_address, IntPtrConstant(0)));
    // Load bucket
    TNode<IntPtrT> bucket =
        LoadBucket(slot_set, slot_offset, num_buckets, &slow_path);
    // Update cell
    SetBitInCell(bucket, slot_offset);
    Goto(&next);
    BIND(&slow_path);
    {
      TNode<ExternalReference> function =
          ExternalConstant(ExternalReference::insert_remembered_set_function());
      CallCFunctionWithCallerSavedRegisters(
          function, MachineTypeOf<Int32T>::value, fp_mode,
          std::make_pair(MachineTypeOf<IntPtrT>::value, page),
          std::make_pair(MachineTypeOf<IntPtrT>::value, slot_offset));
      Goto(&next);
    }
    BIND(&next);
  }
References v8::internal::compiler::CodeAssembler::CallCFunctionWithCallerSavedRegisters(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrSub(), heap::base::BasicSlotSet< kTaggedSize >::kNumBucketsSize, v8::internal::compiler::CodeAssembler::Load(), LoadBucket(), LoadSlotSet(), v8::internal::CodeStubAssembler::MemoryChunkFromAddress(), v8::internal::CodeStubAssembler::PageMetadataFromMemoryChunk(), v8::internal::MachineType::Pointer(), and SetBitInCell().
Referenced by GenerationalBarrierSlow().
InSharedHeap()
void v8::internal::WriteBarrierCodeStubAssembler::InSharedHeap (TNode< IntPtrT > object, Label * true_label, Label * false_label) [inline]
Definition at line 403 of file builtins-internal-gen.cc.
                                        {
    TNode<BoolT> object_is_young =
        IsPageFlagSet(object, MemoryChunk::kInSharedHeap);
    Branch(object_is_young, true_label, false_label);
  }
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::CodeStubAssembler::IsPageFlagSet(), and v8::internal::MemoryChunk::kInSharedHeap.
Referenced by GenerationalOrSharedBarrierDuringMarking(), and IncrementalWriteBarrier().
InYoungGeneration()
void v8::internal::WriteBarrierCodeStubAssembler::InYoungGeneration (TNode< IntPtrT > object, Label * true_label, Label * false_label) [inline]
Definition at line 381 of file builtins-internal-gen.cc.
                                             {
    if (v8_flags.sticky_mark_bits) {
      // This method is currently only used when marking is disabled. Checking
      // markbits while marking is active may result in unexpected results.
      CSA_DCHECK(this, Word32Equal(IsMarking(), BoolConstant(false)));
      Label not_read_only(this);
      TNode<BoolT> is_read_only_page =
          IsPageFlagSet(object, MemoryChunk::kIsOnlyOldOrMajorGCInProgressMask);
      Branch(is_read_only_page, false_label, &not_read_only);
      BIND(&not_read_only);
      Branch(IsUnmarked(object), true_label, false_label);
    } else {
      TNode<BoolT> object_is_young =
          IsPageFlagSet(object, MemoryChunk::kIsInYoungGenerationMask);
      Branch(object_is_young, true_label, false_label);
    }
  }
References v8::internal::compiler::CodeAssembler::BoolConstant(), v8::internal::compiler::CodeAssembler::Branch(), IsMarking(), v8::internal::CodeStubAssembler::IsPageFlagSet(), IsUnmarked(), v8::internal::MemoryChunk::kIsInYoungGenerationMask, v8::internal::MemoryChunk::kIsOnlyOldOrMajorGCInProgressMask, v8::internal::v8_flags, and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by GenerationalOrSharedBarrierDuringMarking(), GenerationalOrSharedBarrierSlow(), and IncrementalWriteBarrierMinor().
IsMarking()
TNode<BoolT> v8::internal::WriteBarrierCodeStubAssembler::IsMarking () [inline]
Definition at line 124 of file builtins-internal-gen.cc.
                           {
    TNode<ExternalReference> is_marking_addr = ExternalConstant(
        ExternalReference::heap_is_marking_flag_address(this->isolate()));
    return Word32NotEqual(Load<Uint8T>(is_marking_addr), Int32Constant(0));
  }
References v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::isolate(), and v8::internal::compiler::CodeAssembler::Word32NotEqual().
Referenced by IndirectPointerWriteBarrier(), InYoungGeneration(), and WriteBarrier().
IsMinorMarking()
TNode<BoolT> v8::internal::WriteBarrierCodeStubAssembler::IsMinorMarking () [inline]
Definition at line 130 of file builtins-internal-gen.cc.
                                {
    TNode<ExternalReference> is_minor_marking_addr = ExternalConstant(
        ExternalReference::heap_is_minor_marking_flag_address(this->isolate()));
    return Word32NotEqual(Load<Uint8T>(is_minor_marking_addr),
                          Int32Constant(0));
  }
References v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::isolate(), and v8::internal::compiler::CodeAssembler::Word32NotEqual().
Referenced by IncrementalWriteBarrierLocal().
IsSharedSpaceIsolate()
TNode<BoolT> v8::internal::WriteBarrierCodeStubAssembler::IsSharedSpaceIsolate () [inline]
Definition at line 137 of file builtins-internal-gen.cc.
                                      {
    TNode<ExternalReference> is_shared_space_isolate_addr = ExternalConstant(
        ExternalReference::is_shared_space_isolate_flag_address(
            this->isolate()));
    return Word32NotEqual(Load<Uint8T>(is_shared_space_isolate_addr),
                          Int32Constant(0));
  }
References v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::isolate(), and v8::internal::compiler::CodeAssembler::Word32NotEqual().
Referenced by IncrementalWriteBarrier().
IsUnmarked()
TNode<BoolT> v8::internal::WriteBarrierCodeStubAssembler::IsUnmarked (TNode< IntPtrT > object) [inline]
Definition at line 152 of file builtins-internal-gen.cc.
                                                 {
    TNode<IntPtrT> cell;
    TNode<IntPtrT> mask;
    GetMarkBit(object, &cell, &mask);
    // Marked only requires checking a single bit here.
    return WordEqual(WordAnd(Load<IntPtrT>(cell), mask), IntPtrConstant(0));
  }
References v8::internal::CodeStubAssembler::GetMarkBit(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::WordAnd(), and v8::internal::compiler::CodeAssembler::WordEqual().
Referenced by IncrementalWriteBarrierMinor(), InYoungGeneration(), and IsValueUnmarkedOrRecordSlot().
IsValueUnmarkedOrRecordSlot()
void v8::internal::WriteBarrierCodeStubAssembler::IsValueUnmarkedOrRecordSlot (TNode< IntPtrT > value, Label * true_label, Label * false_label) [inline]
Definition at line 458 of file builtins-internal-gen.cc.
                                                       {
    // This code implements the following condition:
    // IsUnmarked(value) ||
    // OnEvacuationCandidate(value) &&
    // !SkipEvacuationCandidateRecording(value)
    // 1) IsUnmarked(value) || ....
    GotoIf(IsUnmarked(value), true_label);
    // 2) OnEvacuationCandidate(value) &&
    // !SkipEvacuationCandidateRecording(value)
    GotoIfNot(IsPageFlagSet(value, MemoryChunk::kEvacuationCandidateMask),
              false_label);
    {
      TNode<IntPtrT> object = BitcastTaggedToWord(
          UncheckedParameter<Object>(WriteBarrierDescriptor::kObject));
      Branch(
          IsPageFlagSet(object, MemoryChunk::kSkipEvacuationSlotsRecordingMask),
          false_label, true_label);
    }
  }
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::IsPageFlagSet(), IsUnmarked(), v8::internal::MemoryChunk::kEvacuationCandidateMask, v8::internal::MemoryChunk::kSkipEvacuationSlotsRecordingMask, and v8::internal::value.
Referenced by IncrementalWriteBarrierMajor(), and IncrementalWriteBarrierShared().
LoadBucket()
TNode<IntPtrT> v8::internal::WriteBarrierCodeStubAssembler::LoadBucket (TNode< IntPtrT > slot_set, TNode< WordT > slot_offset, TNode< IntPtrT > num_buckets, Label * slow_path) [inline]
Definition at line 205 of file builtins-internal-gen.cc.
                                                                          {
    TNode<WordT> bucket_index =
        WordShr(slot_offset, SlotSet::kBitsPerBucketLog2 + kTaggedSizeLog2);
    CSA_CHECK(this, IntPtrLessThan(bucket_index, num_buckets));
    TNode<IntPtrT> bucket = UncheckedCast<IntPtrT>(
        Load(MachineType::Pointer(), slot_set,
             WordShl(bucket_index, kSystemPointerSizeLog2)));
    GotoIf(WordEqual(bucket, IntPtrConstant(0)), slow_path);
    return bucket;
  }
References v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThan(), heap::base::BasicSlotSet< kTaggedSize >::kBitsPerBucketLog2, v8::internal::kSystemPointerSizeLog2, v8::internal::kTaggedSizeLog2, v8::internal::compiler::CodeAssembler::Load(), v8::internal::MachineType::Pointer(), v8::internal::compiler::CodeAssembler::WordEqual(), v8::internal::compiler::CodeAssembler::WordShl(), and v8::internal::compiler::CodeAssembler::WordShr().
Referenced by InsertIntoRememberedSet().
LoadSlotSet()
TNode<IntPtrT> v8::internal::WriteBarrierCodeStubAssembler::LoadSlotSet (TNode< IntPtrT > page, Label * slow_path) [inline]
Definition at line 196 of file builtins-internal-gen.cc.
                                                                    {
    TNode<IntPtrT> slot_set = UncheckedCast<IntPtrT>(
        Load(MachineType::Pointer(), page,
             IntPtrConstant(MutablePageMetadata::SlotSetOffset(
                 RememberedSetType::OLD_TO_NEW))));
    GotoIf(WordEqual(slot_set, IntPtrConstant(0)), slow_path);
    return slot_set;
  }
References v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::Load(), v8::internal::OLD_TO_NEW, v8::internal::MachineType::Pointer(), v8::internal::MutablePageMetadata::SlotSetOffset(), and v8::internal::compiler::CodeAssembler::WordEqual().
Referenced by InsertIntoRememberedSet().
SetBitInCell()
void v8::internal::WriteBarrierCodeStubAssembler::SetBitInCell (TNode< IntPtrT > bucket, TNode< WordT > slot_offset) [inline]
Definition at line 217 of file builtins-internal-gen.cc.
                                                                     {
    // Load cell value
    TNode<WordT> cell_offset = WordAnd(
        WordShr(slot_offset, SlotSet::kBitsPerCellLog2 + kTaggedSizeLog2 -
                                 SlotSet::kCellSizeBytesLog2),
        IntPtrConstant((SlotSet::kCellsPerBucket - 1)
                       << SlotSet::kCellSizeBytesLog2));
    TNode<IntPtrT> cell_address =
        UncheckedCast<IntPtrT>(IntPtrAdd(bucket, cell_offset));
    TNode<IntPtrT> old_cell_value =
        ChangeInt32ToIntPtr(Load<Int32T>(cell_address));
    // Calculate new cell value
    TNode<WordT> bit_index = WordAnd(WordShr(slot_offset, kTaggedSizeLog2),
                                     IntPtrConstant(SlotSet::kBitsPerCell - 1));
    TNode<IntPtrT> new_cell_value = UncheckedCast<IntPtrT>(
        WordOr(old_cell_value, WordShl(IntPtrConstant(1), bit_index)));
    // Update cell value
    StoreNoWriteBarrier(MachineRepresentation::kWord32, cell_address,
                        TruncateIntPtrToInt32(new_cell_value));
  }
References v8::internal::compiler::CodeAssembler::ChangeInt32ToIntPtr(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), heap::base::BasicSlotSet< kTaggedSize >::kBitsPerCell, heap::base::BasicSlotSet< kTaggedSize >::kBitsPerCellLog2, heap::base::BasicSlotSet< kTaggedSize >::kCellSizeBytesLog2, heap::base::BasicSlotSet< kTaggedSize >::kCellsPerBucket, v8::internal::kTaggedSizeLog2, v8::internal::kWord32, v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier(), v8::internal::CodeStubAssembler::TruncateIntPtrToInt32(), v8::internal::compiler::CodeAssembler::WordAnd(), v8::internal::compiler::CodeAssembler::WordOr(), v8::internal::compiler::CodeAssembler::WordShl(), and v8::internal::compiler::CodeAssembler::WordShr().
Referenced by InsertIntoRememberedSet().
SharedBarrierSlow()
void v8::internal::WriteBarrierCodeStubAssembler::SharedBarrierSlow (TNode< IntPtrT > slot, Label * next, SaveFPRegsMode fp_mode) [inline]
Definition at line 314 of file builtins-internal-gen.cc.
                                                 {
    TNode<ExternalReference> function = ExternalConstant(
        ExternalReference::shared_barrier_from_code_function());
    TNode<IntPtrT> object = BitcastTaggedToWord(
        UncheckedParameter<Object>(WriteBarrierDescriptor::kObject));
    CallCFunctionWithCallerSavedRegisters(
        function, MachineTypeOf<Int32T>::value, fp_mode,
        std::make_pair(MachineTypeOf<IntPtrT>::value, object),
        std::make_pair(MachineTypeOf<IntPtrT>::value, slot));
    Goto(next);
  }
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::CallCFunctionWithCallerSavedRegisters(), v8::internal::compiler::CodeAssembler::ExternalConstant(), and v8::internal::compiler::CodeAssembler::Goto().
Referenced by GenerationalOrSharedBarrierDuringMarking(), and GenerationalOrSharedBarrierSlow().
UsesSharedHeap()
TNode<BoolT> v8::internal::WriteBarrierCodeStubAssembler::UsesSharedHeap () [inline]
Definition at line 145 of file builtins-internal-gen.cc.
                                {
    TNode<ExternalReference> uses_shared_heap_addr =
        IsolateField(IsolateFieldId::kUsesSharedHeapFlag);
    return Word32NotEqual(Load<Uint8T>(uses_shared_heap_addr),
                          Int32Constant(0));
  }
References v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IsolateField(), and v8::internal::compiler::CodeAssembler::Word32NotEqual().
Referenced by IncrementalWriteBarrier().
WriteBarrier()
void v8::internal::WriteBarrierCodeStubAssembler::WriteBarrier (SaveFPRegsMode fp_mode) [inline]
Definition at line 240 of file builtins-internal-gen.cc.
                                            {
    Label marking_is_on(this), marking_is_off(this), next(this);
    auto slot =
        UncheckedParameter<IntPtrT>(WriteBarrierDescriptor::kSlotAddress);
    Branch(IsMarking(), &marking_is_on, &marking_is_off);
    BIND(&marking_is_off);
    GenerationalOrSharedBarrierSlow(slot, &next, fp_mode);
    BIND(&marking_is_on);
    WriteBarrierDuringMarking(slot, &next, fp_mode);
    BIND(&next);
  }
References v8::internal::compiler::CodeAssembler::Branch(), GenerationalOrSharedBarrierSlow(), IsMarking(), and WriteBarrierDuringMarking().
Referenced by GenerateRecordWrite().
WriteBarrierDuringMarking()
void v8::internal::WriteBarrierCodeStubAssembler::WriteBarrierDuringMarking (TNode< IntPtrT > slot, Label * next, SaveFPRegsMode fp_mode) [inline]
Definition at line 327 of file builtins-internal-gen.cc.
                                                         {
    // When incremental marking is on, we need to perform generational, shared
    // and incremental marking write barrier.
    Label incremental_barrier(this);
    GenerationalOrSharedBarrierDuringMarking(slot, &incremental_barrier,
                                             fp_mode);
    BIND(&incremental_barrier);
    IncrementalWriteBarrier(slot, fp_mode);
    Goto(next);
  }
References GenerationalOrSharedBarrierDuringMarking(), v8::internal::compiler::CodeAssembler::Goto(), and IncrementalWriteBarrier().
Referenced by WriteBarrier().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-internal-gen.cc