v8::internal::ScriptContextTable Class Reference
#include <contexts.h>
Classes
class BodyDescriptor
Public Types
using Shape = ScriptContextTableShape
Public Member Functions
int length (AcquireLoadTag) const
void set_length (int value, ReleaseStoreTag)
Tagged< NameToIndexHashTable > names_to_context_index () const
void set_names_to_context_index (Tagged< NameToIndexHashTable > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< Context > get (int index) const
Tagged< Context > get (int index, AcquireLoadTag) const
V8_WARN_UNUSED_RESULT V8_EXPORT_PRIVATE bool Lookup (DirectHandle< String > name, VariableLookupResult *result)
Static Public Member Functions
static Handle< ScriptContextTable > New (Isolate *isolate, int capacity, AllocationType allocation=AllocationType::kYoung)
V8_WARN_UNUSED_RESULT static V8_EXPORT_PRIVATE Handle< ScriptContextTable > Add (Isolate *isolate, Handle< ScriptContextTable > table, DirectHandle< Context > script_context, bool ignore_duplicates)
Private Types
using Super = TaggedArrayBase< ScriptContextTable, ScriptContextTableShape >
Additional Inherited Members
Detailed Description
Definition at line 841 of file contexts.h.
Member Typedef Documentation
Shape
using v8::internal::ScriptContextTable::Shape = ScriptContextTableShape
Definition at line 846 of file contexts.h.
Super
using v8::internal::ScriptContextTable::Super = TaggedArrayBase<ScriptContextTable, ScriptContextTableShape> [private]
Definition at line 843 of file contexts.h.
Member Function Documentation
Add()
Handle< ScriptContextTable > v8::internal::ScriptContextTable::Add (Isolate * isolate, Handle< ScriptContextTable > table, DirectHandle< Context > script_context, bool ignore_duplicates) [static]
Definition at line 78 of file contexts.cc.
                                                                  {
  DCHECK(script_context->IsScriptContext());
  int old_length = table->length(kAcquireLoad);
  int new_length = old_length + 1;
  DCHECK_LE(0, old_length);
  Handle<ScriptContextTable> result = table;
  int old_capacity = table->capacity();
  DCHECK_LE(old_length, old_capacity);
  if (old_length == old_capacity) {
    int new_capacity = NewCapacityForIndex(old_length, old_capacity);
    auto new_table = New(isolate, new_capacity);
    new_table->set_length(old_length, kReleaseStore);
    new_table->set_names_to_context_index(table->names_to_context_index());
    CopyElements(isolate, *new_table, 0, *table, 0, old_length);
    result = new_table;
  }
  Handle<NameToIndexHashTable> names_table(result->names_to_context_index(),
                                           isolate);
  names_table = AddLocalNamesFromContext(isolate, names_table, script_context,
                                         ignore_duplicates, old_length);
  result->set_names_to_context_index(*names_table);
  result->set(old_length, *script_context, kReleaseStore);
  result->set_length(new_length, kReleaseStore);
  return result;
}
References v8::internal::anonymous_namespace{contexts.cc}::AddLocalNamesFromContext(), v8::internal::TaggedArrayBase< ScriptContextTable, ScriptContextTableShape >::CopyElements(), v8::internal::DCHECK(), DCHECK_LE, v8::kAcquireLoad, v8::kReleaseStore, New(), v8::internal::TaggedArrayBase< ScriptContextTable, ScriptContextTableShape >::NewCapacityForIndex(), and v8::base::internal::result.
Referenced by v8::internal::Genesis::InstallGlobalThisBinding(), and v8::internal::anonymous_namespace{execution.cc}::NewScriptContext().
get() [1/2]
Tagged< Context > v8::internal::ScriptContextTable::get (int index) const [inline]
Definition at line 49 of file contexts-inl.h.
                                                   {
  DCHECK_LT(i, length(kAcquireLoad));
  return Super::get(i);
}
References DCHECK_LT, v8::internal::TaggedArrayBase< ScriptContextTable, ScriptContextTableShape >::get(), v8::kAcquireLoad, and length().
Referenced by Lookup().
get() [2/2]
Tagged< Context > v8::internal::ScriptContextTable::get (int index, AcquireLoadTag tag) const [inline]
Definition at line 54 of file contexts-inl.h.
                                                                       {
  DCHECK_LT(i, length(tag));
  return Super::get(i, tag);
}
References DCHECK_LT, v8::internal::TaggedArrayBase< ScriptContextTable, ScriptContextTableShape >::get(), and length().
length()
int v8::internal::ScriptContextTable::length (AcquireLoadTag) const [inline]
Definition at line 33 of file contexts-inl.h.
                                                   {
  return length_.Acquire_Load().value();
}
Referenced by get(), and Lookup().
Lookup()
bool v8::internal::ScriptContextTable::Lookup (DirectHandle< String > name, VariableLookupResult * result)
Definition at line 120 of file contexts.cc.
                                                              {
  DisallowGarbageCollection no_gc;
  int index = names_to_context_index()->Lookup(*name);
  if (index == -1) return false;
  DCHECK_LE(0, index);
  DCHECK_LT(index, length(kAcquireLoad));
  Tagged<Context> context = get(index);
  DCHECK(context->IsScriptContext());
  int slot_index = context->scope_info()->ContextSlotIndex(*name, result);
  if (slot_index < 0) return false;
  result->context_index = index;
  result->slot_index = slot_index;
  return true;
}
References v8::internal::DCHECK(), DCHECK_LE, DCHECK_LT, get(), v8::internal::index, v8::kAcquireLoad, length(), v8::internal::name, names_to_context_index(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
names_to_context_index()
Tagged< NameToIndexHashTable > v8::internal::ScriptContextTable::names_to_context_index () const [inline]
Definition at line 40 of file contexts-inl.h.
          {
  return names_to_context_index_.load();
}
Referenced by Lookup().
New()
Handle< ScriptContextTable > v8::internal::ScriptContextTable::New (Isolate * isolate, int capacity, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 30 of file contexts.cc.
                                                                              {
  DCHECK_GE(capacity, 0);
  DCHECK_LE(capacity, kMaxCapacity);
  auto names = NameToIndexHashTable::New(isolate, 16);
  std::optional<DisallowGarbageCollection> no_gc;
  Handle<ScriptContextTable> result =
      Allocate(isolate, capacity, &no_gc, allocation);
  result->set_length(0, kReleaseStore);
  result->set_names_to_context_index(*names);
  ReadOnlyRoots roots{isolate};
  MemsetTagged(result->RawFieldOfFirstElement(), roots.undefined_value(),
               capacity);
  return result;
}
References v8::internal::TaggedArrayBase< ScriptContextTable, ScriptContextTableShape >::Allocate(), DCHECK_GE, DCHECK_LE, v8::internal::TaggedArrayBase< ScriptContextTable, ScriptContextTableShape >::kMaxCapacity, v8::kReleaseStore, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
Referenced by Add(), and v8::internal::Factory::NewScriptContextTable().
set_length()
void v8::internal::ScriptContextTable::set_length (int value, ReleaseStoreTag) [inline]
Definition at line 36 of file contexts-inl.h.
                                                              {
  length_.Release_Store(this, Smi::FromInt(value));
}
References v8::internal::Smi::FromInt(), and v8::internal::value.
set_names_to_context_index()
void v8::internal::ScriptContextTable::set_names_to_context_index (Tagged< NameToIndexHashTable > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 44 of file contexts-inl.h.
                                                               {
  names_to_context_index_.store(this, value, mode);
}
References mode(), and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/contexts.h
/mnt/V8SourceCode/src/objects/contexts-inl.h
/mnt/V8SourceCode/src/objects/contexts.cc