v8::internal::torque::Method Class Reference
#include <declarable.h>
Public Member Functions
bool ShouldBeInlined (OutputType output_type) const override
AggregateType * aggregate_type () const
Private Member Functions
Method (AggregateType *aggregate_type, std::string external_name, std::string readable_name, const Signature &signature, Statement *body)
Private Attributes
AggregateType * aggregate_type_
Friends
class Declarations
Additional Inherited Members
Detailed Description
Definition at line 476 of file declarable.h.
Constructor & Destructor Documentation
Method()
v8::internal::torque::Method::Method (AggregateType * aggregate_type, std::string external_name, std::string readable_name, const Signature & signature, Statement * body) [inline], [private]
Definition at line 489 of file declarable.h.
      : TorqueMacro(Declarable::kMethod, std::move(external_name),
                    std::move(readable_name), signature, body, true, false),
        aggregate_type_(aggregate_type) {}
Member Function Documentation
aggregate_type()
AggregateType* v8::internal::torque::Method::aggregate_type () const [inline]
Definition at line 485 of file declarable.h.
{ return aggregate_type_; }
References aggregate_type_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall().
ShouldBeInlined()
bool v8::internal::torque::Method::ShouldBeInlined (OutputType output_type) const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Macro.
Definition at line 479 of file declarable.h.
                                                              {
    return Macro::ShouldBeInlined(output_type) ||
           signature()
               .parameter_types.types[signature().implicit_count]
               ->IsStructType();
  }
References v8::internal::torque::Signature::implicit_count, v8::internal::torque::Signature::parameter_types, v8::internal::torque::Macro::ShouldBeInlined(), v8::internal::torque::Callable::signature(), and v8::internal::torque::ParameterTypes::types.
Friends And Related Function Documentation
Declarations
friend class Declarations [friend]
Definition at line 488 of file declarable.h.
Member Data Documentation
aggregate_type_
AggregateType* v8::internal::torque::Method::aggregate_type_ [private]
Definition at line 494 of file declarable.h.
Referenced by aggregate_type().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/declarable.h