v8::internal::compiler::turboshaft::StringEscapeAnalyzer Class Reference
#include <string-escape-analysis-reducer.h>
Public Member Functions
StringEscapeAnalyzer (const Graph &graph, Zone *phase_zone)
void Run ()
bool IsEscaping (OpIndex idx) const
bool ShouldReconstructFrameState (V< FrameState > idx)
Private Member Functions
void ProcessBlock (const Block &block)
void ProcessFrameState (V< FrameState > index, const FrameStateOp &framestate)
void MarkNextFrameStateInputAsEscaping (FrameStateData::Iterator *it)
void MarkAllInputsAsEscaping (const Operation &op)
void RecursivelyMarkAllStringConcatInputsAsEscaping (const StringConcatOp *concat)
void ReprocessStringConcats ()
void ComputeFrameStatesToReconstruct ()
void MarkAsEscaping (OpIndex index)
void RecursiveMarkAsShouldReconstruct (V< FrameState > idx)
Private Attributes
const Graph & graph_
Zone * zone_
FixedOpIndexSidetable< bool > escaping_operations_and_frame_states_to_reconstruct_
ZoneVector< V< String > > maybe_non_escaping_string_concats_
ZoneVector< V< FrameState > > maybe_to_reconstruct_frame_states_
uint32_t max_frame_state_input_count_ = 0
Detailed Description
Definition at line 31 of file string-escape-analysis-reducer.h.
Constructor & Destructor Documentation
StringEscapeAnalyzer()
v8::internal::compiler::turboshaft::StringEscapeAnalyzer::StringEscapeAnalyzer (const Graph & graph, Zone * phase_zone) [inline]
Definition at line 33 of file string-escape-analysis-reducer.h.
      : graph_(graph),
        zone_(phase_zone),
        escaping_operations_and_frame_states_to_reconstruct_(
            graph.op_id_count(), false, zone_, &graph),
        maybe_non_escaping_string_concats_(phase_zone),
        maybe_to_reconstruct_frame_states_(phase_zone) {}
Member Function Documentation
ComputeFrameStatesToReconstruct()
void v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ComputeFrameStatesToReconstruct () [private]
Definition at line 159 of file string-escape-analysis-reducer.cc.
                                                           {
  for (V<FrameState> frame_state_idx : maybe_to_reconstruct_frame_states_) {
    const FrameStateOp& frame_state =
        graph_.Get(frame_state_idx).Cast<FrameStateOp>();
    for (V<Any> input : frame_state.inputs()) {
      if (graph_.Get(input).Is<StringConcatOp>() && !IsEscaping(input)) {
        RecursiveMarkAsShouldReconstruct(frame_state_idx);
        break;
      }
    }
  }
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::OperationT< Derived >::inputs(), v8::internal::compiler::turboshaft::Operation::Is(), IsEscaping(), maybe_to_reconstruct_frame_states_, and RecursiveMarkAsShouldReconstruct().
Referenced by Run().
IsEscaping()
bool v8::internal::compiler::turboshaft::StringEscapeAnalyzer::IsEscaping (OpIndex idx) const [inline]
Definition at line 42 of file string-escape-analysis-reducer.h.
                                     {
    DCHECK(!graph_.Get(idx).Is<FrameStateOp>());
    return escaping_operations_and_frame_states_to_reconstruct_[idx];
  }
References v8::internal::DCHECK(), escaping_operations_and_frame_states_to_reconstruct_, v8::internal::compiler::turboshaft::Graph::Get(), graph_, and v8::internal::compiler::turboshaft::Operation::Is().
Referenced by ComputeFrameStatesToReconstruct(), ProcessBlock(), RecursivelyMarkAllStringConcatInputsAsEscaping(), ReprocessStringConcats(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::StringConcat(), and v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::StringLength().
MarkAllInputsAsEscaping()
void v8::internal::compiler::turboshaft::StringEscapeAnalyzer::MarkAllInputsAsEscaping (const Operation & op) [private]
Definition at line 107 of file string-escape-analysis-reducer.cc.
                                                                      {
  for (V<Any> input : op.inputs()) {
    if (!graph_.Get(input).Is<FrameStateOp>()) {
      MarkAsEscaping(input);
    }
  }
}
References v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::Operation::inputs(), v8::internal::compiler::turboshaft::Operation::Is(), and MarkAsEscaping().
Referenced by ProcessBlock().
MarkAsEscaping()
void v8::internal::compiler::turboshaft::StringEscapeAnalyzer::MarkAsEscaping (OpIndex index) [inline], [private]
Definition at line 64 of file string-escape-analysis-reducer.h.
                                     {
    DCHECK(!graph_.Get(index).Is<FrameStateOp>());
    escaping_operations_and_frame_states_to_reconstruct_[index] = true;
  }
References v8::internal::DCHECK(), escaping_operations_and_frame_states_to_reconstruct_, v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::index, and v8::internal::compiler::turboshaft::Operation::Is().
Referenced by MarkAllInputsAsEscaping(), MarkNextFrameStateInputAsEscaping(), RecursivelyMarkAllStringConcatInputsAsEscaping(), and ReprocessStringConcats().
MarkNextFrameStateInputAsEscaping()
void v8::internal::compiler::turboshaft::StringEscapeAnalyzer::MarkNextFrameStateInputAsEscaping (FrameStateData::Iterator * it) [private]
Definition at line 32 of file string-escape-analysis-reducer.cc.
                                {
  switch (it->current_instr()) {
    using Instr = FrameStateData::Instr;
    case Instr::kInput: {
      MachineType type;
      OpIndex input;
      it->ConsumeInput(&type, &input);
      MarkAsEscaping(input);
      return;
    }
    case Instr::kArgumentsElements:
    case Instr::kArgumentsLength:
    case Instr::kRestLength:
    case Instr::kDematerializedObjectReference:
    case Instr::kDematerializedObject:
    case Instr::kDematerializedStringConcat:
    case Instr::kDematerializedStringConcatReference:
    case Instr::kUnusedRegister:
      return;
  }
}
References v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeInput(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::current_instr(), MarkAsEscaping(), and v8::internal::tracing::type.
Referenced by ProcessFrameState().
ProcessBlock()
void v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ProcessBlock (const Block & block) [private]
Definition at line 79 of file string-escape-analysis-reducer.cc.
                                                          {
  for (V<Any> index : base::Reversed(graph_.OperationIndices(block))) {
    const Operation& op = graph_.Get(index);
    switch (op.opcode) {
      case Opcode::kFrameState:
        ProcessFrameState(V<FrameState>::Cast(index), op.Cast<FrameStateOp>());
        break;
      case Opcode::kStringConcat:
        // The inputs of a StringConcat are only escaping if the StringConcat
        // itself is already escaping itself.
        if (IsEscaping(index)) {
          MarkAllInputsAsEscaping(op);
        } else {
          maybe_non_escaping_string_concats_.push_back(V<String>::Cast(index));
        }
        break;
      case Opcode::kStringLength:
        // The first input to StringConcat is the length of the result, which
        // means that StringLength won't prevent eliding StringConcat:
        // StringLength(StringConcat(len, left, rigth)) == len
        break;
      default:
        // By default, all uses are considered as escaping their inputs.
        MarkAllInputsAsEscaping(op);
    }
  }
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::index, IsEscaping(), MarkAllInputsAsEscaping(), maybe_non_escaping_string_concats_, v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::Graph::OperationIndices(), ProcessFrameState(), and v8::base::Reversed().
Referenced by Run().
ProcessFrameState()
void v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ProcessFrameState (V< FrameState > index, const FrameStateOp & framestate) [private]
Definition at line 55 of file string-escape-analysis-reducer.cc.
                                                                             {
  max_frame_state_input_count_ =
      std::max<uint32_t>(max_frame_state_input_count_, framestate.input_count);
  for (V<Any> input_idx : framestate.inputs()) {
    if (graph_.Get(input_idx).Is<StringConcatOp>()) {
      // This FrameState has a StringConcat as input, so we might need to
      // recreate it in the reducer.
      maybe_to_reconstruct_frame_states_.push_back(index);
      break;
    }
  }
  // We need to mark the Function and the Receiver as escaping. See
  // https://crbug.com/40059369.
  auto it = framestate.data->iterator(framestate.state_values());
  // Function
  MarkNextFrameStateInputAsEscaping(&it);
  // 1st parameter = receiver
  MarkNextFrameStateInputAsEscaping(&it);
  // Other FrameState uses are not considered as escaping.
}
References v8::internal::compiler::turboshaft::FrameStateOp::data, v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::index, v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::turboshaft::OperationT< Derived >::inputs(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::FrameStateData::iterator(), MarkNextFrameStateInputAsEscaping(), max_frame_state_input_count_, maybe_to_reconstruct_frame_states_, and v8::internal::compiler::turboshaft::FrameStateOp::state_values().
Referenced by ProcessBlock().
RecursivelyMarkAllStringConcatInputsAsEscaping()
void v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursivelyMarkAllStringConcatInputsAsEscaping (const StringConcatOp * concat) [private]
Definition at line 115 of file string-escape-analysis-reducer.cc.
                                  {
  base::SmallVector<const StringConcatOp*, 16> to_mark;
  to_mark.push_back(concat);
  while (!to_mark.empty()) {
    const StringConcatOp* curr = to_mark.back();
    to_mark.pop_back();
    for (V<Any> input_index : curr->inputs()) {
      const Operation& input = graph_.Get(input_index);
      if (input.Is<StringConcatOp>() && !IsEscaping(input_index)) {
        MarkAsEscaping(input_index);
        to_mark.push_back(&input.Cast<StringConcatOp>());
      }
    }
  }
}
References v8::base::SmallVector< T, kSize, Allocator >::back(), v8::internal::compiler::turboshaft::Operation::Cast(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::OperationT< Derived >::inputs(), v8::internal::compiler::turboshaft::Operation::Is(), IsEscaping(), MarkAsEscaping(), v8::base::SmallVector< T, kSize, Allocator >::pop_back(), and v8::base::SmallVector< T, kSize, Allocator >::push_back().
Referenced by ReprocessStringConcats().
RecursiveMarkAsShouldReconstruct()
void v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursiveMarkAsShouldReconstruct (V< FrameState > idx) [inline], [private]
Definition at line 69 of file string-escape-analysis-reducer.h.
                                                           {
    escaping_operations_and_frame_states_to_reconstruct_[idx] = true;
    const FrameStateOp* frame_state = &graph_.Get(idx).Cast<FrameStateOp>();
    while (frame_state->inlined) {
      V<FrameState> parent = frame_state->parent_frame_state();
      escaping_operations_and_frame_states_to_reconstruct_[parent] = true;
      frame_state = &graph_.Get(parent).Cast<FrameStateOp>();
    }
  }
References v8::internal::compiler::turboshaft::Operation::Cast(), escaping_operations_and_frame_states_to_reconstruct_, v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::FrameStateOp::inlined, and v8::internal::compiler::turboshaft::FrameStateOp::parent_frame_state().
Referenced by ComputeFrameStatesToReconstruct().
ReprocessStringConcats()
void v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ReprocessStringConcats () [private]
Definition at line 134 of file string-escape-analysis-reducer.cc.
                                                  {
  constexpr uint32_t kMaxOpInputCount = std::numeric_limits<
      decltype(std::declval<Operation>().input_count)>::max();
  if (maybe_non_escaping_string_concats_.size() + max_frame_state_input_count_ >
      kMaxOpInputCount) {
    // There is a risk that in order to elide some StringConcat, we end up
    // needing more inputs for a FrameState than the maximum number of possible
    // inputs. Note that this is a bit of an overapproximation, but it should
    // still happen very rarely since it would require a huge function with
    // thousand of local variables and/or parameters. When this happens, we mark
    // all operations as "escaping", so that the reducer doesn't try to elide
    // anything.
    for (V<String> index : maybe_non_escaping_string_concats_) {
      MarkAsEscaping(index);
    }
  }
  for (V<String> index : maybe_non_escaping_string_concats_) {
    if (IsEscaping(index)) {
      RecursivelyMarkAllStringConcatInputsAsEscaping(
          &graph_.Get(index).Cast<StringConcatOp>());
    }
  }
}
References v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), IsEscaping(), MarkAsEscaping(), max_frame_state_input_count_, maybe_non_escaping_string_concats_, and RecursivelyMarkAllStringConcatInputsAsEscaping().
Referenced by Run().
Run()
void v8::internal::compiler::turboshaft::StringEscapeAnalyzer::Run ()
Definition at line 15 of file string-escape-analysis-reducer.cc.
                               {
  for (uint32_t processed = graph_.block_count(); processed > 0; --processed) {
    BlockIndex block_index = static_cast<BlockIndex>(processed - 1);
    const Block& block = graph_.Get(block_index);
    ProcessBlock(block);
  }
  // Because of loop phis, some StringConcat could now be escaping even though
  // they weren't escaping on first use.
  ReprocessStringConcats();
  // Now that we know for a fact which StringConcat will be elided, we can
  // compute which FrameStates will need to be reconstructed in the reducer.
  ComputeFrameStatesToReconstruct();
}
References v8::internal::compiler::turboshaft::Graph::block_count(), ComputeFrameStatesToReconstruct(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, ProcessBlock(), and ReprocessStringConcats().
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::Analyze().
ShouldReconstructFrameState()
bool v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ShouldReconstructFrameState (V< FrameState > idx) [inline]
Definition at line 47 of file string-escape-analysis-reducer.h.
                                                      {
    return escaping_operations_and_frame_states_to_reconstruct_[idx];
  }
References escaping_operations_and_frame_states_to_reconstruct_.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), and v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::FrameState().
Member Data Documentation
escaping_operations_and_frame_states_to_reconstruct_
FixedOpIndexSidetable<bool> v8::internal::compiler::turboshaft::StringEscapeAnalyzer::escaping_operations_and_frame_states_to_reconstruct_ [private]
Definition at line 89 of file string-escape-analysis-reducer.h.
Referenced by IsEscaping(), MarkAsEscaping(), RecursiveMarkAsShouldReconstruct(), and ShouldReconstructFrameState().
graph_
const Graph& v8::internal::compiler::turboshaft::StringEscapeAnalyzer::graph_ [private]
Definition at line 52 of file string-escape-analysis-reducer.h.
Referenced by ComputeFrameStatesToReconstruct(), IsEscaping(), MarkAllInputsAsEscaping(), MarkAsEscaping(), ProcessBlock(), ProcessFrameState(), RecursivelyMarkAllStringConcatInputsAsEscaping(), RecursiveMarkAsShouldReconstruct(), ReprocessStringConcats(), and Run().
max_frame_state_input_count_
uint32_t v8::internal::compiler::turboshaft::StringEscapeAnalyzer::max_frame_state_input_count_ = 0 [private]
Definition at line 101 of file string-escape-analysis-reducer.h.
Referenced by ProcessFrameState(), and ReprocessStringConcats().
maybe_non_escaping_string_concats_
ZoneVector<V<String> > v8::internal::compiler::turboshaft::StringEscapeAnalyzer::maybe_non_escaping_string_concats_ [private]
Definition at line 97 of file string-escape-analysis-reducer.h.
Referenced by ProcessBlock(), and ReprocessStringConcats().
maybe_to_reconstruct_frame_states_
ZoneVector<V<FrameState> > v8::internal::compiler::turboshaft::StringEscapeAnalyzer::maybe_to_reconstruct_frame_states_ [private]
Definition at line 99 of file string-escape-analysis-reducer.h.
Referenced by ComputeFrameStatesToReconstruct(), and ProcessFrameState().
zone_
Zone* v8::internal::compiler::turboshaft::StringEscapeAnalyzer::zone_ [private]
Definition at line 53 of file string-escape-analysis-reducer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/string-escape-analysis-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/string-escape-analysis-reducer.cc