v8::internal::wasm::DescriptorsSectionIterator::DeclEntry Class Reference
#include <module-decoder-impl.h>
Public Member Functions
bool has_parent () const
uint32_t Parent (uint32_t current_index)
Private Member Functions
DeclEntry (DescriptorsSectionIterator *decoder)
Friends
class DescriptorsSectionIterator
Additional Inherited Members
Detailed Description
Definition at line 3129 of file module-decoder-impl.h.
Constructor & Destructor Documentation
DeclEntry()
v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::DeclEntry (DescriptorsSectionIterator * decoder) [inline], [explicit], [private]
Definition at line 3149 of file module-decoder-impl.h.
                                                            : Entry(decoder) {
      const uint8_t* pos = decoder->pc();
      uint32_t num_parents = consume_u32v("number of parents");
      if (num_parents > 1) {
        decoder->errorf(pos, "invalid parent count %u", num_parents);
        return;
      }
      if (num_parents == 0) ProceedToExports();
    }
References v8::internal::wasm::DescriptorsSectionIterator::Entry::consume_u32v(), v8::internal::wasm::DescriptorsSectionIterator::Entry::decoder(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::Decoder::pc(), and v8::internal::wasm::DescriptorsSectionIterator::Entry::ProceedToExports().
Member Function Documentation
has_parent()
bool v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::has_parent () const [inline]
Definition at line 3131 of file module-decoder-impl.h.
{ return state() == State::kParentOrImport; }
References v8::internal::wasm::DescriptorsSectionIterator::Entry::kParentOrImport, and v8::internal::wasm::DescriptorsSectionIterator::Entry::state().
Referenced by v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl().
Parent()
uint32_t v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::Parent (uint32_t current_index) [inline]
Definition at line 3133 of file module-decoder-impl.h.
                                            {
      DCHECK_EQ(state(), State::kParentOrImport);
      const uint8_t* pos = decoder()->pc();
      uint32_t result = consume_u32v("parent");
      if (result >= current_index) {
        decoder()->errorf(pos, "parent index %u must be lower than %u", result,
                          current_index);
        return result;
      }
      ProceedToExports();
      return result;
    }
References v8::internal::wasm::DescriptorsSectionIterator::Entry::consume_u32v(), DCHECK_EQ, v8::internal::wasm::DescriptorsSectionIterator::Entry::decoder(), v8::internal::wasm::Decoder::errorf(), v8::internal::wasm::DescriptorsSectionIterator::Entry::kParentOrImport, v8::internal::wasm::Decoder::pc(), v8::internal::wasm::DescriptorsSectionIterator::Entry::ProceedToExports(), v8::base::internal::result, and v8::internal::wasm::DescriptorsSectionIterator::Entry::state().
Referenced by v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl().
Friends And Related Function Documentation
DescriptorsSectionIterator
friend class DescriptorsSectionIterator [friend]
Definition at line 3147 of file module-decoder-impl.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-decoder-impl.h