v8::internal::AssemblerRISCVV Class Reference
#include <extension-riscv-v.h>
Public Member Functions
void vl (VRegister vd, Register rs1, uint8_t lumop, VSew vsew, MaskType mask=NoMask)
void vls (VRegister vd, Register rs1, Register rs2, VSew vsew, MaskType mask=NoMask)
void vlx (VRegister vd, Register rs1, VRegister vs3, VSew vsew, MaskType mask=NoMask)
void vs (VRegister vd, Register rs1, uint8_t sumop, VSew vsew, MaskType mask=NoMask)
void vss (VRegister vd, Register rs1, Register rs2, VSew vsew, MaskType mask=NoMask)
void vsx (VRegister vd, Register rs1, VRegister vs3, VSew vsew, MaskType mask=NoMask)
void vsu (VRegister vd, Register rs1, VRegister vs3, VSew vsew, MaskType mask=NoMask)
SegInstr (vl) SegInstr(vs) SegInstr(vls) SegInstr(vss) SegInstr(vsx) SegInstr(vlx) void vmv_vv(VRegister vd
void vmv_vx (VRegister vd, Register rs1)
void vmv_vi (VRegister vd, uint8_t simm5)
void vmv_xs (Register rd, VRegister vs2)
void vmv_sx (VRegister vd, Register rs1)
void vmerge_vv (VRegister vd, VRegister vs1, VRegister vs2)
void vmerge_vx (VRegister vd, Register rs1, VRegister vs2)
void vmerge_vi (VRegister vd, uint8_t imm5, VRegister vs2)
void vredmaxu_vs (VRegister vd, VRegister vs2, VRegister vs1, MaskType mask=NoMask)
void vredmax_vs (VRegister vd, VRegister vs2, VRegister vs1, MaskType mask=NoMask)
void vredmin_vs (VRegister vd, VRegister vs2, VRegister vs1, MaskType mask=NoMask)
void vredminu_vs (VRegister vd, VRegister vs2, VRegister vs1, MaskType mask=NoMask)
void vadc_vv (VRegister vd, VRegister vs1, VRegister vs2)
void vadc_vx (VRegister vd, Register rs1, VRegister vs2)
void vadc_vi (VRegister vd, uint8_t imm5, VRegister vs2)
void vmadc_vv (VRegister vd, VRegister vs1, VRegister vs2)
void vmadc_vx (VRegister vd, Register rs1, VRegister vs2)
void vmadc_vi (VRegister vd, uint8_t imm5, VRegister vs2)
void vfmv_vf (VRegister vd, FPURegister fs1)
void vfmv_fs (FPURegister fd, VRegister vs2)
void vfmv_sf (VRegister vd, FPURegister fs)
void vfmerge_vf (VRegister vd, FPURegister fs1, VRegister vs2)
void vwaddu_wx (VRegister vd, VRegister vs2, Register rs1, MaskType mask=NoMask)
void vid_v (VRegister vd, MaskType mask=Mask)
void vnot_vv (VRegister dst, VRegister src, MaskType mask=NoMask)
void vneg_vv (VRegister dst, VRegister src, MaskType mask=NoMask)
void vfneg_vv (VRegister dst, VRegister src, MaskType mask=NoMask)
void vfabs_vv (VRegister dst, VRegister src, MaskType mask=NoMask)
void vfirst_m (Register rd, VRegister vs2, MaskType mask=NoMask)
void vcpop_m (Register rd, VRegister vs2, MaskType mask=NoMask)
void vmslt_vi (VRegister vd, VRegister vs1, int8_t imm5, MaskType mask=NoMask)
void vmsltu_vi (VRegister vd, VRegister vs1, int8_t imm5, MaskType mask=NoMask)
Static Public Member Functions
static int32_t GenZimm (VSew vsew, Vlmul vlmul, TailAgnosticType tail=tu, MaskAgnosticType mask=mu)
Public Attributes
VRegister vs1
Protected Member Functions
void vsetvli (Register rd, Register rs1, VSew vsew, Vlmul vlmul, TailAgnosticType tail=tu, MaskAgnosticType mask=mu)
void vsetivli (Register rd, uint8_t uimm, VSew vsew, Vlmul vlmul, TailAgnosticType tail=tu, MaskAgnosticType mask=mu)
void vsetvlmax (Register rd, VSew vsew, Vlmul vlmul, TailAgnosticType tail=tu, MaskAgnosticType mask=mu)
void vsetvl (VSew vsew, Vlmul vlmul, TailAgnosticType tail=tu, MaskAgnosticType mask=mu)
void vsetvl (Register rd, Register rs1, Register rs2)
void GenInstrV (Register rd, Register rs1, Register rs2)
void GenInstrV (Register rd, Register rs1, uint32_t zimm)
void GenInstrV (uint8_t funct6, Opcode opcode, VRegister vd, VRegister vs1, VRegister vs2, MaskType mask=NoMask)
void GenInstrV (uint8_t funct6, Opcode opcode, VRegister vd, int8_t vs1, VRegister vs2, MaskType mask=NoMask)
void GenInstrV (uint8_t funct6, Opcode opcode, VRegister vd, VRegister vs2, MaskType mask=NoMask)
void GenInstrV (uint8_t funct6, Opcode opcode, Register rd, VRegister vs1, VRegister vs2, MaskType mask=NoMask)
void GenInstrV (uint8_t funct6, Opcode opcode, FPURegister fd, VRegister vs1, VRegister vs2, MaskType mask=NoMask)
void GenInstrV (uint8_t funct6, Opcode opcode, VRegister vd, Register rs1, VRegister vs2, MaskType mask=NoMask)
void GenInstrV (uint8_t funct6, Opcode opcode, VRegister vd, FPURegister fs1, VRegister vs2, MaskType mask=NoMask)
void GenInstrV (uint8_t funct6, Register rd, Register rs1, VRegister vs2, MaskType mask=NoMask)
void GenInstrV (uint8_t funct6, VRegister vd, int8_t simm5, VRegister vs2, MaskType mask=NoMask)
void GenInstrV (BaseOpcode opcode, uint8_t width, VRegister vd, Register rs1, uint8_t umop, MaskType mask, uint8_t IsMop, bool IsMew, uint8_t Nf)
void GenInstrV (BaseOpcode opcode, uint8_t width, VRegister vd, Register rs1, Register rs2, MaskType mask, uint8_t IsMop, bool IsMew, uint8_t Nf)
void GenInstrV (BaseOpcode opcode, uint8_t width, VRegister vd, Register rs1, VRegister vs2, MaskType mask, uint8_t IsMop, bool IsMew, uint8_t Nf)
void GenInstrV (uint8_t funct6, Opcode opcode, Register rd, uint8_t vs1, VRegister vs2, MaskType mask)
Additional Inherited Members
Detailed Description
Definition at line 17 of file extension-riscv-v.h.
Member Function Documentation
GenInstrV() [1/15]
void v8::internal::AssemblerRISCVV::GenInstrV (BaseOpcode opcode, uint8_t width, VRegister vd, Register rs1, Register rs2, MaskType mask, uint8_t IsMop, bool IsMew, uint8_t Nf) [protected]
Definition at line 564 of file extension-riscv-v.cc.
                                                                       {
  DCHECK(opcode == LOAD_FP || opcode == STORE_FP);
  Instr instr = opcode | ((vd.code() << kRvvVdShift) & kRvvVdMask) |
                ((width << kRvvWidthShift) & kRvvWidthMask) |
                ((rs1.code() << kRvvRs1Shift) & kRvvRs1Mask) |
                ((rs2.code() << kRvvRs2Shift) & kRvvRs2Mask) |
                ((mask << kRvvVmShift) & kRvvVmMask) |
                ((IsMop << kRvvMopShift) & kRvvMopMask) |
                ((IsMew << kRvvMewShift) & kRvvMewMask) |
                ((Nf << kRvvNfShift) & kRvvNfMask);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::emit(), v8::internal::kRvvMewMask, v8::internal::kRvvMewShift, v8::internal::kRvvMopMask, v8::internal::kRvvMopShift, v8::internal::kRvvNfMask, v8::internal::kRvvNfShift, v8::internal::kRvvRs1Mask, v8::internal::kRvvRs1Shift, v8::internal::kRvvRs2Mask, v8::internal::kRvvRs2Shift, v8::internal::kRvvVdMask, v8::internal::kRvvVdShift, v8::internal::kRvvVmMask, v8::internal::kRvvVmShift, v8::internal::kRvvWidthMask, v8::internal::kRvvWidthShift, v8::internal::LOAD_FP, and v8::internal::STORE_FP.
GenInstrV() [2/15]
void v8::internal::AssemblerRISCVV::GenInstrV (BaseOpcode opcode, uint8_t width, VRegister vd, Register rs1, uint8_t umop, MaskType mask, uint8_t IsMop, bool IsMew, uint8_t Nf) [protected]
Definition at line 550 of file extension-riscv-v.cc.
                                                                       {
  DCHECK(opcode == LOAD_FP || opcode == STORE_FP);
  Instr instr = opcode | ((vd.code() << kRvvVdShift) & kRvvVdMask) |
                ((width << kRvvWidthShift) & kRvvWidthMask) |
                ((rs1.code() << kRvvRs1Shift) & kRvvRs1Mask) |
                ((umop << kRvvRs2Shift) & kRvvRs2Mask) |
                ((mask << kRvvVmShift) & kRvvVmMask) |
                ((IsMop << kRvvMopShift) & kRvvMopMask) |
                ((IsMew << kRvvMewShift) & kRvvMewMask) |
                ((Nf << kRvvNfShift) & kRvvNfMask);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::emit(), v8::internal::kRvvMewMask, v8::internal::kRvvMewShift, v8::internal::kRvvMopMask, v8::internal::kRvvMopShift, v8::internal::kRvvNfMask, v8::internal::kRvvNfShift, v8::internal::kRvvRs1Mask, v8::internal::kRvvRs1Shift, v8::internal::kRvvRs2Mask, v8::internal::kRvvRs2Shift, v8::internal::kRvvVdMask, v8::internal::kRvvVdShift, v8::internal::kRvvVmMask, v8::internal::kRvvVmShift, v8::internal::kRvvWidthMask, v8::internal::kRvvWidthShift, v8::internal::LOAD_FP, and v8::internal::STORE_FP.
GenInstrV() [3/15]
void v8::internal::AssemblerRISCVV::GenInstrV (BaseOpcode opcode, uint8_t width, VRegister vd, Register rs1, VRegister vs2, MaskType mask, uint8_t IsMop, bool IsMew, uint8_t Nf) [protected]
Definition at line 579 of file extension-riscv-v.cc.
                                                                       {
  DCHECK(opcode == LOAD_FP || opcode == STORE_FP || opcode == AMO);
  Instr instr = opcode | ((vd.code() << kRvvVdShift) & kRvvVdMask) |
                ((width << kRvvWidthShift) & kRvvWidthMask) |
                ((rs1.code() << kRvvRs1Shift) & kRvvRs1Mask) |
                ((vs2.code() << kRvvRs2Shift) & kRvvRs2Mask) |
                ((mask << kRvvVmShift) & kRvvVmMask) |
                ((IsMop << kRvvMopShift) & kRvvMopMask) |
                ((IsMew << kRvvMewShift) & kRvvMewMask) |
                ((Nf << kRvvNfShift) & kRvvNfMask);
  emit(instr);
}
References v8::internal::AMO, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::emit(), v8::internal::kRvvMewMask, v8::internal::kRvvMewShift, v8::internal::kRvvMopMask, v8::internal::kRvvMopShift, v8::internal::kRvvNfMask, v8::internal::kRvvNfShift, v8::internal::kRvvRs1Mask, v8::internal::kRvvRs1Shift, v8::internal::kRvvRs2Mask, v8::internal::kRvvRs2Shift, v8::internal::kRvvVdMask, v8::internal::kRvvVdShift, v8::internal::kRvvVmMask, v8::internal::kRvvVmShift, v8::internal::kRvvWidthMask, v8::internal::kRvvWidthShift, v8::internal::LOAD_FP, and v8::internal::STORE_FP.
GenInstrV() [4/15]
void v8::internal::AssemblerRISCVV::GenInstrV (Register rd, Register rs1, Register rs2) [protected]
Referenced by vadc_vi(), vadc_vv(), vadc_vx(), vcpop_m(), vfirst_m(), vfmerge_vf(), vfmv_fs(), vfmv_sf(), vfmv_vf(), vid_v(), vl(), vls(), vlx(), vmadc_vi(), vmadc_vv(), vmadc_vx(), vmerge_vi(), vmerge_vv(), vmerge_vx(), vmv_sx(), vmv_vi(), vmv_vx(), vmv_xs(), vredmax_vs(), vredmaxu_vs(), vredmin_vs(), vredminu_vs(), vs(), vss(), vsu(), vsx(), and vwaddu_wx().
GenInstrV() [5/15]
void v8::internal::AssemblerRISCVV::GenInstrV (Register rd, Register rs1, uint32_t zimm) [protected]
GenInstrV() [6/15]
void v8::internal::AssemblerRISCVV::GenInstrV (uint8_t funct6, Opcode opcode, FPURegister fd, VRegister vs1, VRegister vs2, MaskType mask = NoMask) [protected]
Definition at line 497 of file extension-riscv-v.cc.
                                                                             {
  DCHECK(opcode == OP_FVV);
  Instr instr = (funct6 << kRvvFunct6Shift) | opcode | (mask << kRvvVmShift) |
                ((fd.code() & 0x1F) << kRvvVdShift) |
                ((vs1.code() & 0x1F) << kRvvVs1Shift) |
                ((vs2.code() & 0x1F) << kRvvVs2Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::emit(), v8::internal::kRvvFunct6Shift, v8::internal::kRvvVdShift, v8::internal::kRvvVmShift, v8::internal::kRvvVs1Shift, v8::internal::kRvvVs2Shift, v8::internal::OP_FVV, and vs1.
GenInstrV() [7/15]
void v8::internal::AssemblerRISCVV::GenInstrV (uint8_t funct6, Opcode opcode, Register rd, uint8_t vs1, VRegister vs2, MaskType mask) [protected]
Definition at line 594 of file extension-riscv-v.cc.
                                                                           {
  DCHECK(opcode == OP_MVV);
  Instr instr = (funct6 << kRvvFunct6Shift) | opcode | (mask << kRvvVmShift) |
                ((rd.code() & 0x1F) << kRvvVdShift) |
                ((vs1 & 0x1F) << kRvvVs1Shift) |
                ((vs2.code() & 0x1F) << kRvvVs2Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::emit(), v8::internal::kRvvFunct6Shift, v8::internal::kRvvVdShift, v8::internal::kRvvVmShift, v8::internal::kRvvVs1Shift, v8::internal::kRvvVs2Shift, v8::internal::OP_MVV, and vs1.
GenInstrV() [8/15]
void v8::internal::AssemblerRISCVV::GenInstrV (uint8_t funct6, Opcode opcode, Register rd, VRegister vs1, VRegister vs2, MaskType mask = NoMask) [protected]
Definition at line 486 of file extension-riscv-v.cc.
                                                                             {
  DCHECK(opcode == OP_MVV || opcode == OP_FVV);
  Instr instr = (funct6 << kRvvFunct6Shift) | opcode | (mask << kRvvVmShift) |
                ((rd.code() & 0x1F) << kRvvVdShift) |
                ((vs1.code() & 0x1F) << kRvvVs1Shift) |
                ((vs2.code() & 0x1F) << kRvvVs2Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::emit(), v8::internal::kRvvFunct6Shift, v8::internal::kRvvVdShift, v8::internal::kRvvVmShift, v8::internal::kRvvVs1Shift, v8::internal::kRvvVs2Shift, v8::internal::OP_FVV, v8::internal::OP_MVV, and vs1.
GenInstrV() [9/15]
void v8::internal::AssemblerRISCVV::GenInstrV (uint8_t funct6, Opcode opcode, VRegister vd, FPURegister fs1, VRegister vs2, MaskType mask = NoMask) [protected]
Definition at line 519 of file extension-riscv-v.cc.
                                                                               {
  DCHECK(opcode == OP_FVF);
  Instr instr = (funct6 << kRvvFunct6Shift) | opcode | (mask << kRvvVmShift) |
                ((vd.code() & 0x1F) << kRvvVdShift) |
                ((fs1.code() & 0x1F) << kRvvRs1Shift) |
                ((vs2.code() & 0x1F) << kRvvVs2Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::emit(), v8::internal::kRvvFunct6Shift, v8::internal::kRvvRs1Shift, v8::internal::kRvvVdShift, v8::internal::kRvvVmShift, v8::internal::kRvvVs2Shift, and v8::internal::OP_FVF.
GenInstrV() [10/15]
void v8::internal::AssemblerRISCVV::GenInstrV (uint8_t funct6, Opcode opcode, VRegister vd, int8_t vs1, VRegister vs2, MaskType mask = NoMask) [protected]
Definition at line 476 of file extension-riscv-v.cc.
                                                                          {
  DCHECK(opcode == OP_MVV || opcode == OP_FVV || opcode == OP_IVV);
  Instr instr = (funct6 << kRvvFunct6Shift) | opcode | (mask << kRvvVmShift) |
                ((vd.code() & 0x1F) << kRvvVdShift) |
                ((vs1 & 0x1F) << kRvvVs1Shift) |
                ((vs2.code() & 0x1F) << kRvvVs2Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::emit(), v8::internal::kRvvFunct6Shift, v8::internal::kRvvVdShift, v8::internal::kRvvVmShift, v8::internal::kRvvVs1Shift, v8::internal::kRvvVs2Shift, v8::internal::OP_FVV, v8::internal::OP_IVV, v8::internal::OP_MVV, and vs1.
GenInstrV() [11/15]
void v8::internal::AssemblerRISCVV::GenInstrV (uint8_t funct6, Opcode opcode, VRegister vd, Register rs1, VRegister vs2, MaskType mask = NoMask) [protected]
Definition at line 508 of file extension-riscv-v.cc.
                                                                            {
  DCHECK(opcode == OP_IVX || opcode == OP_MVX);
  Instr instr = (funct6 << kRvvFunct6Shift) | opcode | (mask << kRvvVmShift) |
                ((vd.code() & 0x1F) << kRvvVdShift) |
                ((rs1.code() & 0x1F) << kRvvRs1Shift) |
                ((vs2.code() & 0x1F) << kRvvVs2Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::emit(), v8::internal::kRvvFunct6Shift, v8::internal::kRvvRs1Shift, v8::internal::kRvvVdShift, v8::internal::kRvvVmShift, v8::internal::kRvvVs2Shift, v8::internal::OP_IVX, and v8::internal::OP_MVX.
GenInstrV() [12/15]
void v8::internal::AssemblerRISCVV::GenInstrV (uint8_t funct6, Opcode opcode, VRegister vd, VRegister vs1, VRegister vs2, MaskType mask = NoMask) [protected]
Definition at line 466 of file extension-riscv-v.cc.
                                                                             {
  DCHECK(opcode == OP_MVV || opcode == OP_FVV || opcode == OP_IVV);
  Instr instr = (funct6 << kRvvFunct6Shift) | opcode | (mask << kRvvVmShift) |
                ((vd.code() & 0x1F) << kRvvVdShift) |
                ((vs1.code() & 0x1F) << kRvvVs1Shift) |
                ((vs2.code() & 0x1F) << kRvvVs2Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::emit(), v8::internal::kRvvFunct6Shift, v8::internal::kRvvVdShift, v8::internal::kRvvVmShift, v8::internal::kRvvVs1Shift, v8::internal::kRvvVs2Shift, v8::internal::OP_FVV, v8::internal::OP_IVV, v8::internal::OP_MVV, and vs1.
GenInstrV() [13/15]
void v8::internal::AssemblerRISCVV::GenInstrV (uint8_t funct6, Opcode opcode, VRegister vd, VRegister vs2, MaskType mask = NoMask) [protected]
GenInstrV() [14/15]
void v8::internal::AssemblerRISCVV::GenInstrV (uint8_t funct6, Register rd, Register rs1, VRegister vs2, MaskType mask = NoMask) [protected]
Definition at line 530 of file extension-riscv-v.cc.
                                                              {
  Instr instr = (funct6 << kRvvFunct6Shift) | OP_MVX | (mask << kRvvVmShift) |
                ((rd.code() & 0x1F) << kRvvVdShift) |
                ((rs1.code() & 0x1F) << kRvvRs1Shift) |
                ((vs2.code() & 0x1F) << kRvvVs2Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::AssemblerRiscvBase::emit(), v8::internal::kRvvFunct6Shift, v8::internal::kRvvRs1Shift, v8::internal::kRvvVdShift, v8::internal::kRvvVmShift, v8::internal::kRvvVs2Shift, and v8::internal::OP_MVX.
GenInstrV() [15/15]
void v8::internal::AssemblerRISCVV::GenInstrV (uint8_t funct6, VRegister vd, int8_t simm5, VRegister vs2, MaskType mask = NoMask) [protected]
Definition at line 539 of file extension-riscv-v.cc.
                                                              {
  DCHECK(is_uint5(imm5) || is_int5(imm5));
  Instr instr = (funct6 << kRvvFunct6Shift) | OP_IVI | (mask << kRvvVmShift) |
                ((vd.code() & 0x1F) << kRvvVdShift) |
                (((uint32_t)imm5 << kRvvImm5Shift) & kRvvImm5Mask) |
                ((vs2.code() & 0x1F) << kRvvVs2Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::emit(), v8::internal::kRvvFunct6Shift, v8::internal::kRvvImm5Mask, v8::internal::kRvvImm5Shift, v8::internal::kRvvVdShift, v8::internal::kRvvVmShift, v8::internal::kRvvVs2Shift, and v8::internal::OP_IVI.
GenZimm()
static int32_t v8::internal::AssemblerRISCVV::GenZimm (VSew vsew, Vlmul vlmul, TailAgnosticType tail = tu, MaskAgnosticType mask = mu) [inline], [static]
Definition at line 20 of file extension-riscv-v.h.
                                                     {
    return (mask << 7) | (tail << 6) | ((vsew & 0x7) << 3) | (vlmul & 0x7);
  }
Referenced by vsetivli(), and vsetvli().
SegInstr()
v8::internal::AssemblerRISCVV::SegInstr (vl)
vadc_vi()
void v8::internal::AssemblerRISCVV::vadc_vi (VRegister vd, uint8_t imm5, VRegister vs2)
Definition at line 77 of file extension-riscv-v.cc.
                                                                       {
  GenInstrV(VADC_FUNCT6, vd, imm5, vs2, Mask);
}
References GenInstrV(), v8::internal::Mask, and v8::internal::VADC_FUNCT6.
vadc_vv()
void v8::internal::AssemblerRISCVV::vadc_vv (VRegister vd, VRegister vs1, VRegister vs2)
Definition at line 69 of file extension-riscv-v.cc.
                                                                        {
  GenInstrV(VADC_FUNCT6, OP_IVV, vd, vs1, vs2, Mask);
}
References GenInstrV(), v8::internal::Mask, v8::internal::OP_IVV, v8::internal::VADC_FUNCT6, and vs1.
vadc_vx()
void v8::internal::AssemblerRISCVV::vadc_vx (VRegister vd, Register rs1, VRegister vs2)
Definition at line 73 of file extension-riscv-v.cc.
                                                                       {
  GenInstrV(VADC_FUNCT6, OP_IVX, vd, rs1, vs2, Mask);
}
References GenInstrV(), v8::internal::Mask, v8::internal::OP_IVX, and v8::internal::VADC_FUNCT6.
vcpop_m()
void v8::internal::AssemblerRISCVV::vcpop_m (Register rd, VRegister vs2, MaskType mask = NoMask)
Definition at line 865 of file extension-riscv-v.cc.
                                                                       {
  GenInstrV(VWXUNARY0_FUNCT6, OP_MVV, rd, 0b10000, vs2, mask);
}
References GenInstrV(), v8::internal::OP_MVV, and v8::internal::VWXUNARY0_FUNCT6.
vfabs_vv()
void v8::internal::AssemblerRISCVV::vfabs_vv (VRegister dst, VRegister src, MaskType mask = NoMask) [inline]
Definition at line 400 of file extension-riscv-v.h.
                                                                      {
    vfsngjx_vv(dst, src, src, mask);
  }
vfirst_m()
void v8::internal::AssemblerRISCVV::vfirst_m (Register rd, VRegister vs2, MaskType mask = NoMask)
Definition at line 861 of file extension-riscv-v.cc.
                                                                        {
  GenInstrV(VWXUNARY0_FUNCT6, OP_MVV, rd, 0b10001, vs2, mask);
}
References GenInstrV(), v8::internal::OP_MVV, and v8::internal::VWXUNARY0_FUNCT6.
vfmerge_vf()
void v8::internal::AssemblerRISCVV::vfmerge_vf (VRegister vd, FPURegister fs1, VRegister vs2)
Definition at line 214 of file extension-riscv-v.cc.
                                                                             {
  GenInstrV(VMV_FUNCT6, OP_FVF, vd, fs1, vs2, Mask);
}
References GenInstrV(), v8::internal::Mask, v8::internal::OP_FVF, and v8::internal::VMV_FUNCT6.
Referenced by v8::internal::MacroAssembler::LoadLane().
vfmv_fs()
void v8::internal::AssemblerRISCVV::vfmv_fs (FPURegister fd, VRegister vs2)
Definition at line 206 of file extension-riscv-v.cc.
                                                           {
  GenInstrV(VWFUNARY0_FUNCT6, OP_FVV, fd, v0, vs2, NoMask);
}
References GenInstrV(), v8::internal::NoMask, v8::internal::OP_FVV, and v8::internal::VWFUNARY0_FUNCT6.
Referenced by v8::internal::MacroAssembler::StoreLane().
vfmv_sf()
void v8::internal::AssemblerRISCVV::vfmv_sf (VRegister vd, FPURegister fs)
Definition at line 210 of file extension-riscv-v.cc.
                                                          {
  GenInstrV(VRFUNARY0_FUNCT6, OP_FVF, vd, fs, v0, NoMask);
}
References GenInstrV(), v8::internal::NoMask, v8::internal::OP_FVF, and v8::internal::VRFUNARY0_FUNCT6.
vfmv_vf()
void v8::internal::AssemblerRISCVV::vfmv_vf (VRegister vd, FPURegister fs1)
Definition at line 202 of file extension-riscv-v.cc.
                                                           {
  GenInstrV(VMV_FUNCT6, OP_FVF, vd, fs1, v0, NoMask);
}
References GenInstrV(), v8::internal::NoMask, v8::internal::OP_FVF, and v8::internal::VMV_FUNCT6.
vfneg_vv()
void v8::internal::AssemblerRISCVV::vfneg_vv (VRegister dst, VRegister src, MaskType mask = NoMask) [inline]
Definition at line 397 of file extension-riscv-v.h.
                                                                      {
    vfsngjn_vv(dst, src, src, mask);
  }
vid_v()
void v8::internal::AssemblerRISCVV::vid_v (VRegister vd, MaskType mask = Mask)
Definition at line 117 of file extension-riscv-v.cc.
                                                       {
  GenInstrV(VMUNARY0_FUNCT6, OP_MVV, vd, VID_V, v0, mask);
}
References GenInstrV(), v8::internal::OP_MVV, v8::internal::VID_V, and v8::internal::VMUNARY0_FUNCT6.
vl()
void v8::internal::AssemblerRISCVV::vl (VRegister vd, Register rs1, uint8_t lumop, VSew vsew, MaskType mask = NoMask)
Definition at line 604 of file extension-riscv-v.cc.
                                        {
  uint8_t width = vsew_switch(vsew);
  GenInstrV(LOAD_FP, width, vd, rs1, lumop, mask, 0b00, 0, 0b000);
}
References GenInstrV(), v8::internal::LOAD_FP, and v8::internal::vsew_switch().
vls()
void v8::internal::AssemblerRISCVV::vls (VRegister vd, Register rs1, Register rs2, VSew vsew, MaskType mask = NoMask)
Definition at line 609 of file extension-riscv-v.cc.
                                         {
  uint8_t width = vsew_switch(vsew);
  GenInstrV(LOAD_FP, width, vd, rs1, rs2, mask, 0b10, 0, 0b000);
}
References GenInstrV(), v8::internal::LOAD_FP, and v8::internal::vsew_switch().
vlx()
void v8::internal::AssemblerRISCVV::vlx (VRegister vd, Register rs1, VRegister vs3, VSew vsew, MaskType mask = NoMask)
Definition at line 614 of file extension-riscv-v.cc.
                                         {
  uint8_t width = vsew_switch(vsew);
  GenInstrV(LOAD_FP, width, vd, rs1, vs2, mask, 0b11, 0, 0);
}
References GenInstrV(), v8::internal::LOAD_FP, and v8::internal::vsew_switch().
vmadc_vi()
void v8::internal::AssemblerRISCVV::vmadc_vi (VRegister vd, uint8_t imm5, VRegister vs2)
Definition at line 89 of file extension-riscv-v.cc.
                                                                        {
  GenInstrV(VMADC_FUNCT6, vd, imm5, vs2, Mask);
}
References GenInstrV(), v8::internal::Mask, and v8::internal::VMADC_FUNCT6.
vmadc_vv()
void v8::internal::AssemblerRISCVV::vmadc_vv (VRegister vd, VRegister vs1, VRegister vs2)
Definition at line 81 of file extension-riscv-v.cc.
                                                                         {
  GenInstrV(VMADC_FUNCT6, OP_IVV, vd, vs1, vs2, Mask);
}
References GenInstrV(), v8::internal::Mask, v8::internal::OP_IVV, v8::internal::VMADC_FUNCT6, and vs1.
vmadc_vx()
void v8::internal::AssemblerRISCVV::vmadc_vx (VRegister vd, Register rs1, VRegister vs2)
Definition at line 85 of file extension-riscv-v.cc.
                                                                        {
  GenInstrV(VMADC_FUNCT6, OP_IVX, vd, rs1, vs2, Mask);
}
References GenInstrV(), v8::internal::Mask, v8::internal::OP_IVX, and v8::internal::VMADC_FUNCT6.
vmerge_vi()
void v8::internal::AssemblerRISCVV::vmerge_vi (VRegister vd, uint8_t imm5, VRegister vs2)
Definition at line 65 of file extension-riscv-v.cc.
                                                                         {
  GenInstrV(VMV_FUNCT6, vd, imm5, vs2, Mask);
}
References GenInstrV(), v8::internal::Mask, and v8::internal::VMV_FUNCT6.
vmerge_vv()
void v8::internal::AssemblerRISCVV::vmerge_vv (VRegister vd, VRegister vs1, VRegister vs2)
Definition at line 57 of file extension-riscv-v.cc.
                                                                          {
  GenInstrV(VMV_FUNCT6, OP_IVV, vd, vs1, vs2, Mask);
}
References GenInstrV(), v8::internal::Mask, v8::internal::OP_IVV, v8::internal::VMV_FUNCT6, and vs1.
vmerge_vx()
void v8::internal::AssemblerRISCVV::vmerge_vx (VRegister vd, Register rs1, VRegister vs2)
Definition at line 61 of file extension-riscv-v.cc.
                                                                         {
  GenInstrV(VMV_FUNCT6, OP_IVX, vd, rs1, vs2, Mask);
}
References GenInstrV(), v8::internal::Mask, v8::internal::OP_IVX, and v8::internal::VMV_FUNCT6.
Referenced by v8::internal::MacroAssembler::LoadLane(), v8::internal::MacroAssembler::WasmRvvEq(), v8::internal::MacroAssembler::WasmRvvGeS(), v8::internal::MacroAssembler::WasmRvvGeU(), v8::internal::MacroAssembler::WasmRvvGtS(), v8::internal::MacroAssembler::WasmRvvGtU(), and v8::internal::MacroAssembler::WasmRvvNe().
vmslt_vi()
void v8::internal::AssemblerRISCVV::vmslt_vi (VRegister vd, VRegister vs1, int8_t imm5, MaskType mask = NoMask) [inline]
Definition at line 407 of file extension-riscv-v.h.
                                        {
    DCHECK(imm5 >= -15 && imm5 <= 16);
    vmsle_vi(vd, vs1, imm5 - 1, mask);
  }
References v8::internal::DCHECK(), and vs1.
vmsltu_vi()
void v8::internal::AssemblerRISCVV::vmsltu_vi (VRegister vd, VRegister vs1, int8_t imm5, MaskType mask = NoMask) [inline]
Definition at line 413 of file extension-riscv-v.h.
                                         {
    DCHECK(imm5 >= 1 && imm5 <= 16);
    vmsleu_vi(vd, vs1, imm5 - 1, mask);
  }
References v8::internal::DCHECK(), and vs1.
vmv_sx()
void v8::internal::AssemblerRISCVV::vmv_sx (VRegister vd, Register rs1)
Definition at line 53 of file extension-riscv-v.cc.
                                                       {
  GenInstrV(VRXUNARY0_FUNCT6, OP_MVX, vd, rs1, v0, NoMask);
}
References GenInstrV(), v8::internal::NoMask, v8::internal::OP_MVX, and v8::internal::VRXUNARY0_FUNCT6.
Referenced by v8::internal::MacroAssembler::LoadLane().
vmv_vi()
void v8::internal::AssemblerRISCVV::vmv_vi (VRegister vd, uint8_t simm5)
Definition at line 45 of file extension-riscv-v.cc.
                                                        {
  GenInstrV(VMV_FUNCT6, vd, simm5, v0, NoMask);
}
References GenInstrV(), v8::internal::NoMask, and v8::internal::VMV_FUNCT6.
vmv_vx()
void v8::internal::AssemblerRISCVV::vmv_vx (VRegister vd, Register rs1)
Definition at line 41 of file extension-riscv-v.cc.
                                                       {
  GenInstrV(VMV_FUNCT6, OP_IVX, vd, rs1, v0, NoMask);
}
References GenInstrV(), v8::internal::NoMask, v8::internal::OP_IVX, and v8::internal::VMV_FUNCT6.
Referenced by v8::internal::MacroAssembler::RoundHelper(), v8::internal::MacroAssembler::WasmRvvEq(), v8::internal::MacroAssembler::WasmRvvGeS(), v8::internal::MacroAssembler::WasmRvvGeU(), v8::internal::MacroAssembler::WasmRvvGtS(), v8::internal::MacroAssembler::WasmRvvGtU(), and v8::internal::MacroAssembler::WasmRvvNe().
vmv_xs()
void v8::internal::AssemblerRISCVV::vmv_xs (Register rd, VRegister vs2)
Definition at line 49 of file extension-riscv-v.cc.
                                                       {
  GenInstrV(VWXUNARY0_FUNCT6, OP_MVV, rd, 0b00000, vs2, NoMask);
}
References GenInstrV(), v8::internal::NoMask, v8::internal::OP_MVV, and v8::internal::VWXUNARY0_FUNCT6.
Referenced by v8::internal::MacroAssembler::StoreLane().
vneg_vv()
void v8::internal::AssemblerRISCVV::vneg_vv (VRegister dst, VRegister src, MaskType mask = NoMask) [inline]
Definition at line 393 of file extension-riscv-v.h.
                                                                     {
    vrsub_vx(dst, src, zero_reg, mask);
  }
vnot_vv()
void v8::internal::AssemblerRISCVV::vnot_vv (VRegister dst, VRegister src, MaskType mask = NoMask) [inline]
Definition at line 389 of file extension-riscv-v.h.
                                                                     {
    vxor_vi(dst, src, -1, mask);
  }
Referenced by v8::internal::MacroAssembler::RoundHelper().
vredmax_vs()
void v8::internal::AssemblerRISCVV::vredmax_vs (VRegister vd, VRegister vs2, VRegister vs1, MaskType mask = NoMask)
Definition at line 22 of file extension-riscv-v.cc.
                                                {
  GenInstrV(VREDMAX_FUNCT6, OP_MVV, vd, vs1, vs2, mask);
}
References GenInstrV(), v8::internal::OP_MVV, v8::internal::VREDMAX_FUNCT6, and vs1.
vredmaxu_vs()
void v8::internal::AssemblerRISCVV::vredmaxu_vs (VRegister vd, VRegister vs2, VRegister vs1, MaskType mask = NoMask)
Definition at line 17 of file extension-riscv-v.cc.
                                                 {
  GenInstrV(VREDMAXU_FUNCT6, OP_MVV, vd, vs1, vs2, mask);
}
References GenInstrV(), v8::internal::OP_MVV, v8::internal::VREDMAXU_FUNCT6, and vs1.
vredmin_vs()
void v8::internal::AssemblerRISCVV::vredmin_vs (VRegister vd, VRegister vs2, VRegister vs1, MaskType mask = NoMask)
Definition at line 27 of file extension-riscv-v.cc.
                                                {
  GenInstrV(VREDMIN_FUNCT6, OP_MVV, vd, vs1, vs2, mask);
}
References GenInstrV(), v8::internal::OP_MVV, v8::internal::VREDMIN_FUNCT6, and vs1.
vredminu_vs()
void v8::internal::AssemblerRISCVV::vredminu_vs (VRegister vd, VRegister vs2, VRegister vs1, MaskType mask = NoMask)
Definition at line 32 of file extension-riscv-v.cc.
                                                 {
  GenInstrV(VREDMINU_FUNCT6, OP_MVV, vd, vs1, vs2, mask);
}
References GenInstrV(), v8::internal::OP_MVV, v8::internal::VREDMINU_FUNCT6, and vs1.
vs()
void v8::internal::AssemblerRISCVV::vs (VRegister vd, Register rs1, uint8_t sumop, VSew vsew, MaskType mask = NoMask)
Definition at line 620 of file extension-riscv-v.cc.
                                        {
  uint8_t width = vsew_switch(vsew);
  GenInstrV(STORE_FP, width, vd, rs1, sumop, mask, 0b00, 0, 0b000);
}
References GenInstrV(), v8::internal::STORE_FP, and v8::internal::vsew_switch().
Referenced by v8::internal::maglev::MaglevAssembler::CompareDoubleAndJumpIfZeroOrNaN(), v8::internal::wasm::LiftoffAssembler::emit_f32_set_cond(), v8::internal::wasm::LiftoffAssembler::emit_f64_set_cond(), and v8::internal::wasm::LiftoffAssembler::emit_type_conversion().
vsetivli()
void v8::internal::AssemblerRISCVV::vsetivli (Register rd, uint8_t uimm, VSew vsew, Vlmul vlmul, TailAgnosticType tail = tu, MaskAgnosticType mask = mu) [protected]
Definition at line 428 of file extension-riscv-v.cc.
                                                      {
  DCHECK(is_uint5(uimm));
  int32_t zimm = GenZimm(vsew, vlmul, tail, mask) & 0x3FF;
  Instr instr = OP_V | ((rd.code() & 0x1F) << kRvvRdShift) | (0x7 << 12) |
                ((uimm & 0x1F) << kRvvUimmShift) |
                (((uint32_t)zimm << kRvvZimmShift) & kRvvZimmMask) | 0x3 << 30;
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), v8::internal::AssemblerRiscvBase::emit(), GenZimm(), v8::internal::kRvvRdShift, v8::internal::kRvvUimmShift, v8::internal::kRvvZimmMask, v8::internal::kRvvZimmShift, and v8::internal::OP_V.
vsetvl() [1/2]
void v8::internal::AssemblerRISCVV::vsetvl (Register rd, Register rs1, Register rs2) [protected]
Definition at line 439 of file extension-riscv-v.cc.
                                                                    {
  Instr instr = OP_V | ((rd.code() & 0x1F) << kRvvRdShift) | (0x7 << 12) |
                ((rs1.code() & 0x1F) << kRvvRs1Shift) |
                ((rs2.code() & 0x1F) << kRvvRs2Shift) | 0x40 << 25;
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::AssemblerRiscvBase::emit(), v8::internal::kRvvRdShift, v8::internal::kRvvRs1Shift, v8::internal::kRvvRs2Shift, and v8::internal::OP_V.
vsetvl() [2/2]
void v8::internal::AssemblerRISCVV::vsetvl (VSew vsew, Vlmul vlmul, TailAgnosticType tail = tu, MaskAgnosticType mask = mu) [inline], [protected]
Definition at line 432 of file extension-riscv-v.h.
                                                 {
    vsetvli(zero_reg, zero_reg, vsew, vlmul, tu, mu);
  }
References v8::internal::mu, v8::internal::tu, and vsetvli().
vsetvli()
void v8::internal::AssemblerRISCVV::vsetvli (Register rd, Register rs1, VSew vsew, Vlmul vlmul, TailAgnosticType tail = tu, MaskAgnosticType mask = mu) [protected]
Definition at line 419 of file extension-riscv-v.cc.
                                                                            {
  int32_t zimm = GenZimm(vsew, vlmul, tail, mask);
  Instr instr = OP_V | ((rd.code() & 0x1F) << kRvvRdShift) | (0x7 << 12) |
                ((rs1.code() & 0x1F) << kRvvRs1Shift) |
                (((uint32_t)zimm << kRvvZimmShift) & kRvvZimmMask) | 0x0 << 31;
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::AssemblerRiscvBase::emit(), GenZimm(), v8::internal::kRvvRdShift, v8::internal::kRvvRs1Shift, v8::internal::kRvvZimmMask, v8::internal::kRvvZimmShift, and v8::internal::OP_V.
Referenced by vsetvl(), and vsetvlmax().
vsetvlmax()
void v8::internal::AssemblerRISCVV::vsetvlmax (Register rd, VSew vsew, Vlmul vlmul, TailAgnosticType tail = tu, MaskAgnosticType mask = mu) [inline], [protected]
Definition at line 426 of file extension-riscv-v.h.
                                                    {
    vsetvli(rd, zero_reg, vsew, vlmul, tu, mu);
  }
References v8::internal::mu, v8::internal::tu, and vsetvli().
vss()
void v8::internal::AssemblerRISCVV::vss (VRegister vd, Register rs1, Register rs2, VSew vsew, MaskType mask = NoMask)
Definition at line 625 of file extension-riscv-v.cc.
                                         {
  uint8_t width = vsew_switch(vsew);
  GenInstrV(STORE_FP, width, vs3, rs1, rs2, mask, 0b10, 0, 0b000);
}
References GenInstrV(), v8::internal::STORE_FP, and v8::internal::vsew_switch().
vsu()
void v8::internal::AssemblerRISCVV::vsu (VRegister vd, Register rs1, VRegister vs3, VSew vsew, MaskType mask = NoMask)
Definition at line 636 of file extension-riscv-v.cc.
                                         {
  uint8_t width = vsew_switch(vsew);
  GenInstrV(STORE_FP, width, vd, rs1, vs2, mask, 0b01, 0, 0b000);
}
References GenInstrV(), v8::internal::STORE_FP, and v8::internal::vsew_switch().
vsx()
void v8::internal::AssemblerRISCVV::vsx (VRegister vd, Register rs1, VRegister vs3, VSew vsew, MaskType mask = NoMask)
Definition at line 631 of file extension-riscv-v.cc.
                                         {
  uint8_t width = vsew_switch(vsew);
  GenInstrV(STORE_FP, width, vd, rs1, vs2, mask, 0b11, 0, 0b000);
}
References GenInstrV(), v8::internal::STORE_FP, and v8::internal::vsew_switch().
vwaddu_wx()
void v8::internal::AssemblerRISCVV::vwaddu_wx (VRegister vd, VRegister vs2, Register rs1, MaskType mask = NoMask)
Definition at line 112 of file extension-riscv-v.cc.
                                               {
  GenInstrV(VWADDUW_FUNCT6, OP_MVX, vd, rs1, vs2, mask);
}
References GenInstrV(), v8::internal::OP_MVX, and v8::internal::VWADDUW_FUNCT6.
Member Data Documentation
vs1
VRegister v8::internal::AssemblerRISCVV::vs1
Definition at line 71 of file extension-riscv-v.h.
Referenced by GenInstrV(), vadc_vv(), vmadc_vv(), vmerge_vv(), vmslt_vi(), vmsltu_vi(), vredmax_vs(), vredmaxu_vs(), vredmin_vs(), and vredminu_vs().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-v.h
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-v.cc