v8::internal::CppHeapObjectWrapper Class Reference
#include <cpp-heap-object-wrapper.h>
Public Member Functions
CppHeapObjectWrapper (Tagged< JSObject > object)
CppHeapObjectWrapper (Tagged< CppHeapExternalObject > object)
void InitializeCppHeapWrapper ()
template<CppHeapPointerTag tag>
void SetCppHeapWrappable (IsolateForPointerCompression isolate, void *)
void SetCppHeapWrappable (IsolateForPointerCompression isolate, void *, CppHeapPointerTag tag)
template<CppHeapPointerTag lower_bound, CppHeapPointerTag upper_bound>
void * GetCppHeapWrappable (IsolateForPointerCompression isolate) const
void * GetCppHeapWrappable (IsolateForPointerCompression isolate, CppHeapPointerTagRange tag_range) const
Static Public Member Functions
static CppHeapObjectWrapper From (Tagged< CppHeapPointerWrapperObjectT > object)
Private Attributes
Tagged< CppHeapPointerWrapperObjectT > object_
int offset_
Detailed Description
Definition at line 20 of file cpp-heap-object-wrapper.h.
Constructor & Destructor Documentation
CppHeapObjectWrapper() [1/2]
v8::internal::CppHeapObjectWrapper::CppHeapObjectWrapper (Tagged< JSObject > object) [inline], [explicit]
Definition at line 32 of file cpp-heap-object-wrapper-inl.h.
    : object_(object),
      offset_(JSAPIObjectWithEmbedderSlots::kCppHeapWrappableOffset) {
  DCHECK(IsCppHeapPointerWrapperObject(object));
  DCHECK(IsJSApiWrapperObject(object));
  DCHECK(IsJSAPIObjectWithEmbedderSlots(object_) || IsJSSpecialObject(object_));
}
References v8::internal::DCHECK(), v8::internal::InstanceTypeChecker::IsCppHeapPointerWrapperObject(), v8::internal::InstanceTypeChecker::IsJSApiWrapperObject(), and object_.
Referenced by From().
CppHeapObjectWrapper() [2/2]
v8::internal::CppHeapObjectWrapper::CppHeapObjectWrapper (Tagged< CppHeapExternalObject > object) [inline], [explicit]
Definition at line 27 of file cpp-heap-object-wrapper-inl.h.
    : object_(object), offset_(CppHeapExternalObject::kCppHeapWrappableOffset) {
  DCHECK(IsCppHeapPointerWrapperObject(object));
}
References v8::internal::DCHECK(), and v8::internal::InstanceTypeChecker::IsCppHeapPointerWrapperObject().
Member Function Documentation
From()
CppHeapObjectWrapper v8::internal::CppHeapObjectWrapper::From (Tagged< CppHeapPointerWrapperObjectT > object) [inline], [static]
Definition at line 17 of file cpp-heap-object-wrapper-inl.h.
                                                 {
  DCHECK(IsCppHeapPointerWrapperObject(object));
  if (IsCppHeapExternalObject(object)) {
    return CppHeapObjectWrapper(Cast<CppHeapExternalObject>(object));
  }
  DCHECK(IsJSObject(object));
  return CppHeapObjectWrapper(Cast<JSObject>(object));
}
References CppHeapObjectWrapper(), v8::internal::DCHECK(), and v8::internal::InstanceTypeChecker::IsCppHeapPointerWrapperObject().
Referenced by v8::internal::anonymous_namespace{minor-mark-sweep.cc}::VisitObjectWithCppHeapPointerField().
GetCppHeapWrappable() [1/2]
template<CppHeapPointerTag lower_bound, CppHeapPointerTag upper_bound>
void * v8::internal::CppHeapObjectWrapper::GetCppHeapWrappable (IsolateForPointerCompression isolate) const [inline]
Definition at line 45 of file cpp-heap-object-wrapper-inl.h.
                                                {
  return reinterpret_cast<void*>(
      object_->ReadCppHeapPointerField<lower_bound, upper_bound>(offset_,
                                                                 isolate));
}
References object_, and offset_.
Referenced by v8::internal::CppGraphBuilderImpl::AddEdgeForCppHeapExternalObject(), v8::internal::ExtractEmbedderDataBackref(), v8::internal::HeapProfiler::GetDetachedJSWrapperObjects(), v8::internal::ContextSerializer::SerializeApiWrapperFields(), v8::Object::Unwrap(), v8::CppHeapExternal::ValueImpl(), and v8::internal::anonymous_namespace{minor-mark-sweep.cc}::VisitObjectWithCppHeapPointerField().
GetCppHeapWrappable() [2/2]
void * v8::internal::CppHeapObjectWrapper::GetCppHeapWrappable (IsolateForPointerCompression isolate, CppHeapPointerTagRange tag_range) const [inline]
Definition at line 52 of file cpp-heap-object-wrapper-inl.h.
                                            {
  return reinterpret_cast<void*>(
      object_->ReadCppHeapPointerField(offset_, isolate, tag_range));
}
References object_, and offset_.
InitializeCppHeapWrapper()
void v8::internal::CppHeapObjectWrapper::InitializeCppHeapWrapper () [inline]
Definition at line 40 of file cpp-heap-object-wrapper-inl.h.
                                                    {
  object_->SetupLazilyInitializedCppHeapPointerField(offset_);
}
References object_, and offset_.
Referenced by v8::internal::Factory::InitializeJSObjectFromMap(), and v8::internal::Factory::NewCppHeapExternal().
SetCppHeapWrappable() [1/2]
template<CppHeapPointerTag tag>
void v8::internal::CppHeapObjectWrapper::SetCppHeapWrappable (IsolateForPointerCompression isolate, void * instance) [inline]
Definition at line 60 of file cpp-heap-object-wrapper-inl.h.
                                                          {
  object_->WriteLazilyInitializedCppHeapPointerField<tag>(
      offset_, isolate, reinterpret_cast<Address>(instance));
  WriteBarrier::ForCppHeapPointer(
      object_, object_->RawCppHeapPointerField(offset_), instance);
}
References v8::internal::WriteBarrier::ForCppHeapPointer(), object_, and offset_.
Referenced by v8::CppHeapExternal::NewImpl(), and v8::Object::Wrap().
SetCppHeapWrappable() [2/2]
void v8::internal::CppHeapObjectWrapper::SetCppHeapWrappable (IsolateForPointerCompression isolate, void * instance, CppHeapPointerTag tag) [inline]
Definition at line 68 of file cpp-heap-object-wrapper-inl.h.
                           {
  object_->WriteLazilyInitializedCppHeapPointerField(
      offset_, isolate, reinterpret_cast<Address>(instance), tag);
  WriteBarrier::ForCppHeapPointer(
      object_, object_->RawCppHeapPointerField(offset_), instance);
}
References v8::internal::WriteBarrier::ForCppHeapPointer(), object_, and offset_.
Member Data Documentation
object_
Tagged<CppHeapPointerWrapperObjectT> v8::internal::CppHeapObjectWrapper::object_ [private]
Definition at line 45 of file cpp-heap-object-wrapper.h.
Referenced by CppHeapObjectWrapper(), GetCppHeapWrappable(), InitializeCppHeapWrapper(), and SetCppHeapWrappable().
offset_
int v8::internal::CppHeapObjectWrapper::offset_ [private]
Definition at line 46 of file cpp-heap-object-wrapper.h.
Referenced by GetCppHeapWrappable(), InitializeCppHeapWrapper(), and SetCppHeapWrappable().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/cpp-heap-object-wrapper.h
/mnt/V8SourceCode/src/objects/cpp-heap-object-wrapper-inl.h