v8::internal::compiler::SelectParameters Class Reference
#include <common-operator.h>
Public Member Functions
SelectParameters (MachineRepresentation representation, BranchHint hint=BranchHint::kNone, BranchSemantics semantics=BranchSemantics::kUnspecified)
MachineRepresentation representation () const
BranchHint hint () const
BranchSemantics semantics () const
Private Attributes
const MachineRepresentation representation_
const BranchHint hint_
const BranchSemantics semantics_
Detailed Description
Definition at line 161 of file common-operator.h.
Constructor & Destructor Documentation
SelectParameters()
v8::internal::compiler::SelectParameters::SelectParameters (MachineRepresentation representation, BranchHint hint = BranchHint::kNone, BranchSemantics semantics = BranchSemantics::kUnspecified) [inline], [explicit]
Definition at line 163 of file common-operator.h.
      : representation_(representation), hint_(hint), semantics_(semantics) {}
Member Function Documentation
hint()
BranchHint v8::internal::compiler::SelectParameters::hint () const [inline]
Definition at line 169 of file common-operator.h.
{ return hint_; }
References hint_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::RepresentationSelector::VisitSelect().
representation()
MachineRepresentation v8::internal::compiler::SelectParameters::representation () const [inline]
Definition at line 168 of file common-operator.h.
{ return representation_; }
References representation_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::SelectLowering::LowerSelect(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process(), and v8::internal::compiler::RepresentationSelector::VisitSelect().
semantics()
BranchSemantics v8::internal::compiler::SelectParameters::semantics () const [inline]
Definition at line 170 of file common-operator.h.
{ return semantics_; }
References semantics_.
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
Member Data Documentation
hint_
const BranchHint v8::internal::compiler::SelectParameters::hint_ [private]
Definition at line 174 of file common-operator.h.
Referenced by hint().
representation_
const MachineRepresentation v8::internal::compiler::SelectParameters::representation_ [private]
Definition at line 173 of file common-operator.h.
Referenced by representation().
semantics_
const BranchSemantics v8::internal::compiler::SelectParameters::semantics_ [private]
Definition at line 175 of file common-operator.h.
Referenced by semantics().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/common-operator.h