v8::internal::Float16 Class Reference
#include <float16.h>
Public Member Functions
Float16 ()
void Write (base::Address destination)
float ToFloat32 () const
Static Public Member Functions
static Float16 Read (base::Address source)
static Float16 FromFloat32 (float f32)
Private Member Functions
Float16 (uint16_t raw_bits)
Private Attributes
uint16_t bits_
Detailed Description
Definition at line 14 of file float16.h.
Constructor & Destructor Documentation
Float16() [1/2]
v8::internal::Float16::Float16 () [inline]
Definition at line 16 of file float16.h.
: bits_(0) {}
Referenced by FromFloat32(), and Read().
Float16() [2/2]
v8::internal::Float16::Float16 (uint16_t raw_bits) [inline], [explicit], [private]
Definition at line 33 of file float16.h.
: bits_(raw_bits) {}
Member Function Documentation
FromFloat32()
static Float16 v8::internal::Float16::FromFloat32 (float f32) [inline], [static]
Definition at line 26 of file float16.h.
                                        {
    return Float16(fp16_ieee_from_fp32_value(f32));
  }
References Float16().
Referenced by v8::internal::wasm::ConvertToF16S(), v8::internal::wasm::ConvertToF16U(), v8::internal::wasm::f16_abs(), v8::internal::wasm::f16_add(), v8::internal::wasm::f16_ceil(), v8::internal::wasm::f16_div(), v8::internal::wasm::f16_floor(), v8::internal::wasm::f16_max(), v8::internal::wasm::f16_min(), v8::internal::wasm::f16_mul(), v8::internal::wasm::f16_nearest_int(), v8::internal::wasm::f16_neg(), v8::internal::wasm::f16_pmax(), v8::internal::wasm::f16_pmin(), v8::internal::wasm::f16_sqrt(), v8::internal::wasm::f16_sub(), v8::internal::wasm::f16_trunc(), v8::internal::wasm::f16x8_demote_f32x4_zero_wrapper(), v8::internal::wasm::f16x8_demote_f64x2_zero_wrapper(), v8::internal::wasm::float32_to_float16_wrapper(), and v8::internal::wasm::simd_float16_fma_wrapper().
Read()
static Float16 v8::internal::Float16::Read (base::Address source) [inline], [static]
Definition at line 18 of file float16.h.
                                          {
    return Float16(base::ReadUnalignedValue<uint16_t>(source));
  }
References Float16().
Referenced by v8::internal::wasm::f32x4_promote_low_f16x8_wrapper(), v8::internal::wasm::float16_to_float32_wrapper(), v8::internal::wasm::simd_float16_bin_wrapper(), and v8::internal::wasm::simd_float16_fma_wrapper().
ToFloat32()
float v8::internal::Float16::ToFloat32 () const [inline]
Definition at line 30 of file float16.h.
{ return fp16_ieee_to_fp32_value(bits_); }
References bits_.
Referenced by v8::internal::wasm::ConvertToIntS(), v8::internal::wasm::ConvertToIntU(), v8::internal::wasm::f16_abs(), v8::internal::wasm::f16_add(), v8::internal::wasm::f16_ceil(), v8::internal::wasm::f16_div(), v8::internal::wasm::f16_eq(), v8::internal::wasm::f16_floor(), v8::internal::wasm::f16_le(), v8::internal::wasm::f16_lt(), v8::internal::wasm::f16_max(), v8::internal::wasm::f16_min(), v8::internal::wasm::f16_mul(), v8::internal::wasm::f16_ne(), v8::internal::wasm::f16_nearest_int(), v8::internal::wasm::f16_neg(), v8::internal::wasm::f16_pmax(), v8::internal::wasm::f16_pmin(), v8::internal::wasm::f16_sqrt(), v8::internal::wasm::f16_sub(), v8::internal::wasm::f16_trunc(), v8::internal::wasm::f32x4_promote_low_f16x8_wrapper(), and v8::internal::wasm::simd_float16_fma_wrapper().
Write()
void v8::internal::Float16::Write (base::Address destination) [inline]
Definition at line 22 of file float16.h.
                                      {
    return base::WriteUnalignedValue<uint16_t>(destination, bits_);
  }
References bits_.
Referenced by v8::internal::wasm::f16x8_demote_f32x4_zero_wrapper(), v8::internal::wasm::float32_to_float16_wrapper(), and v8::internal::wasm::simd_float16_fma_wrapper().
Member Data Documentation
bits_
uint16_t v8::internal::Float16::bits_ [private]
Definition at line 35 of file float16.h.
Referenced by ToFloat32(), and Write().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/float16.h