v8::internal::CodeStubArguments Class Reference
#include <code-stub-assembler.h>
Public Types
using ForEachBodyFunction = std::function< void(TNode< JSAny > arg)>
Public Member Functions
CodeStubArguments (CodeStubAssembler *assembler, TNode< IntPtrT > argc)
CodeStubArguments (CodeStubAssembler *assembler, TNode< Int32T > argc)
CodeStubArguments (CodeStubAssembler *assembler, TNode< IntPtrT > argc, TNode< RawPtrT > fp)
CodeStubArguments (CodeStubAssembler *assembler, TorqueStructArguments torque_arguments)
bool MayHavePaddingArguments () const
TNode< JSAny > GetReceiver () const
void SetReceiver (TNode< JSAny > object) const
TNode< RawPtrT > AtIndexPtr (TNode< IntPtrT > index) const
TNode< JSAny > AtIndex (TNode< IntPtrT > index) const
TNode< JSAny > AtIndex (int index) const
TNode< IntPtrT > GetLengthWithoutReceiver () const
TNode< IntPtrT > GetLengthWithReceiver () const
TorqueStructArguments GetTorqueArguments () const
TNode< JSAny > GetOptionalArgumentValue (TNode< IntPtrT > index, TNode< JSAny > default_value)
TNode< JSAny > GetOptionalArgumentValue (TNode< IntPtrT > index)
TNode< JSAny > GetOptionalArgumentValue (int index)
void ForEach (const ForEachBodyFunction &body, TNode< IntPtrT > first={}, TNode< IntPtrT > last={}) const
void ForEach (const CodeStubAssembler::VariableList &vars, const ForEachBodyFunction &body, TNode< IntPtrT > first={}, TNode< IntPtrT > last={}) const
void PopAndReturn (TNode< JSAny > value)
Private Attributes
CodeStubAssembler * assembler_
TNode< IntPtrT > argc_
TNode< RawPtrT > base_
TNode< RawPtrT > fp_
Detailed Description
Definition at line 4857 of file code-stub-assembler.h.
Member Typedef Documentation
ForEachBodyFunction
using v8::internal::CodeStubArguments::ForEachBodyFunction = std::function<void(TNode<JSAny> arg)>
Definition at line 4911 of file code-stub-assembler.h.
Constructor & Destructor Documentation
CodeStubArguments() [1/4]
v8::internal::CodeStubArguments::CodeStubArguments (CodeStubAssembler * assembler, TNode< IntPtrT > argc) [inline]
Definition at line 4860 of file code-stub-assembler.h.
      : CodeStubArguments(assembler, argc, TNode<RawPtrT>()) {}
CodeStubArguments() [2/4]
v8::internal::CodeStubArguments::CodeStubArguments (CodeStubAssembler * assembler, TNode< Int32T > argc) [inline]
Definition at line 4862 of file code-stub-assembler.h.
      : CodeStubArguments(assembler, assembler->ChangeInt32ToIntPtr(argc)) {}
CodeStubArguments() [3/4]
v8::internal::CodeStubArguments::CodeStubArguments (CodeStubAssembler * assembler, TNode< IntPtrT > argc, TNode< RawPtrT > fp)
Definition at line 17568 of file code-stub-assembler.cc.
    : assembler_(assembler),
      argc_(argc),
      base_(),
      fp_(fp != nullptr ? fp : assembler_->LoadFramePointer()) {
  TNode<IntPtrT> offset = assembler_->IntPtrConstant(
      (StandardFrameConstants::kFixedSlotCountAboveFp + 1) *
      kSystemPointerSize);
  DCHECK_NOT_NULL(argc_);
  // base_ points to the first argument, not the receiver
  // whether present or not.
  base_ = assembler_->RawPtrAdd(fp_, offset);
}
References argc_, assembler_, base_, DCHECK_NOT_NULL, fp_, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp, v8::internal::kSystemPointerSize, and v8::internal::compiler::CodeAssembler::RawPtrAdd().
CodeStubArguments() [4/4]
v8::internal::CodeStubArguments::CodeStubArguments (CodeStubAssembler * assembler, TorqueStructArguments torque_arguments) [inline]
Definition at line 4869 of file code-stub-assembler.h.
      : assembler_(assembler),
        argc_(torque_arguments.actual_count),
        base_(torque_arguments.base),
        fp_(torque_arguments.frame) {}
Member Function Documentation
AtIndex() [1/2]
TNode< JSAny > v8::internal::CodeStubArguments::AtIndex (int index) const
Definition at line 17614 of file code-stub-assembler.cc.
                                                       {
  return AtIndex(assembler_->IntPtrConstant(index));
}
References assembler_, AtIndex(), v8::internal::index, and v8::internal::compiler::CodeAssembler::IntPtrConstant().
AtIndex() [2/2]
TNode< JSAny > v8::internal::CodeStubArguments::AtIndex (TNode< IntPtrT > index) const
Definition at line 17607 of file code-stub-assembler.cc.
                                                                  {
  // Defense-in-depth check to prevent out-of-bounds stack access.
  CSA_SBXCHECK(assembler_, assembler_->UintPtrOrSmiLessThan(
                               index, GetLengthWithoutReceiver()));
  return assembler_->CAST(assembler_->LoadFullTagged(AtIndexPtr(index)));
}
References assembler_, AtIndexPtr(), GetLengthWithoutReceiver(), v8::internal::index, and v8::internal::compiler::CodeAssembler::LoadFullTagged().
Referenced by AtIndex(), GetOptionalArgumentValue(), and v8::internal::TF_BUILTIN().
AtIndexPtr()
TNode< RawPtrT > v8::internal::CodeStubArguments::AtIndexPtr (TNode< IntPtrT > index) const
Definition at line 17601 of file code-stub-assembler.cc.
                                                                       {
  TNode<IntPtrT> offset =
      assembler_->ElementOffsetFromIndex(index, SYSTEM_POINTER_ELEMENTS, 0);
  return assembler_->RawPtrAdd(base_, offset);
}
References assembler_, base_, v8::internal::CodeStubAssembler::ElementOffsetFromIndex(), v8::internal::index, v8::internal::compiler::CodeAssembler::RawPtrAdd(), and v8::internal::SYSTEM_POINTER_ELEMENTS.
Referenced by AtIndex(), ForEach(), and v8::internal::TF_BUILTIN().
ForEach() [1/2]
void v8::internal::CodeStubArguments::ForEach (const CodeStubAssembler::VariableList & vars, const ForEachBodyFunction & body, TNode< IntPtrT > first = {}, TNode< IntPtrT > last = {}) const
Definition at line 17647 of file code-stub-assembler.cc.
                               {
  assembler_->Comment("CodeStubArguments::ForEach");
  if (first == nullptr) {
    first = assembler_->IntPtrConstant(0);
  }
  if (last == nullptr) {
    last = GetLengthWithoutReceiver();
  }
  TNode<RawPtrT> start = AtIndexPtr(first);
  TNode<RawPtrT> end = AtIndexPtr(last);
  const int increment = kSystemPointerSize;
  assembler_->BuildFastLoop<RawPtrT>(
      vars, start, end,
      [&](TNode<RawPtrT> current) {
        TNode<JSAny> arg =
            assembler_->CAST(assembler_->LoadFullTagged(current));
        body(arg);
      },
      increment, CodeStubAssembler::LoopUnrollingMode::kNo,
      CodeStubAssembler::IndexAdvanceMode::kPost);
}
References assembler_, AtIndexPtr(), v8::internal::CodeStubAssembler::BuildFastLoop(), v8::internal::compiler::CodeAssembler::Comment(), v8::internal::compiler::end(), GetLengthWithoutReceiver(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::kNo, v8::internal::CodeStubAssembler::kPost, v8::internal::kSystemPointerSize, and v8::internal::compiler::CodeAssembler::LoadFullTagged().
ForEach() [2/2]
void v8::internal::CodeStubArguments::ForEach (const ForEachBodyFunction & body, TNode< IntPtrT > first = {}, TNode< IntPtrT > last = {}) const [inline]
Definition at line 4912 of file code-stub-assembler.h.
                                                                       {},
               TNode<IntPtrT> last = {}) const {
    CodeStubAssembler::VariableList list(0, assembler_->zone());
    ForEach(list, body, first, last);
  }
Referenced by v8::internal::TF_BUILTIN().
GetLengthWithoutReceiver()
TNode< IntPtrT > v8::internal::CodeStubArguments::GetLengthWithoutReceiver () const
Definition at line 17618 of file code-stub-assembler.cc.
                                                                 {
  return assembler_->IntPtrSub(
      argc_, assembler_->IntPtrConstant(kJSArgcReceiverSlots));
}
References argc_, assembler_, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrSub(), and v8::internal::kJSArgcReceiverSlots.
Referenced by AtIndex(), ForEach(), GetOptionalArgumentValue(), and v8::internal::TF_BUILTIN().
GetLengthWithReceiver()
TNode< IntPtrT > v8::internal::CodeStubArguments::GetLengthWithReceiver () const
Definition at line 17623 of file code-stub-assembler.cc.
                                                              {
  return argc_;
}
References argc_.
Referenced by PopAndReturn().
GetOptionalArgumentValue() [1/3]
TNode<JSAny> v8::internal::CodeStubArguments::GetOptionalArgumentValue (int index) [inline]
Definition at line 4906 of file code-stub-assembler.h.
                                                   {
    return GetOptionalArgumentValue(assembler_->IntPtrConstant(index));
  }
References v8::internal::index.
GetOptionalArgumentValue() [2/3]
TNode<JSAny> v8::internal::CodeStubArguments::GetOptionalArgumentValue (TNode< IntPtrT > index) [inline]
Definition at line 4903 of file code-stub-assembler.h.
                                                              {
    return GetOptionalArgumentValue(index, assembler_->UndefinedConstant());
  }
References v8::internal::index.
GetOptionalArgumentValue() [3/3]
TNode< JSAny > v8::internal::CodeStubArguments::GetOptionalArgumentValue (TNode< IntPtrT > index, TNode< JSAny > default_value)
Definition at line 17627 of file code-stub-assembler.cc.
                                                      {
  CodeStubAssembler::TVariable<JSAny> result(assembler_);
  CodeStubAssembler::Label argument_missing(assembler_),
      argument_done(assembler_, &result);
  assembler_->GotoIf(
      assembler_->UintPtrGreaterThanOrEqual(index, GetLengthWithoutReceiver()),
      &argument_missing);
  result = AtIndex(index);
  assembler_->Goto(&argument_done);
  assembler_->BIND(&argument_missing);
  result = default_value;
  assembler_->Goto(&argument_done);
  assembler_->BIND(&argument_done);
  return result.value();
}
References assembler_, AtIndex(), GetLengthWithoutReceiver(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::index, and v8::base::internal::result.
GetReceiver()
TNode< JSAny > v8::internal::CodeStubArguments::GetReceiver () const
Definition at line 17589 of file code-stub-assembler.cc.
                                                  {
  intptr_t offset = -kSystemPointerSize;
  return assembler_->CAST(
      assembler_->LoadFullTagged(base_, assembler_->IntPtrConstant(offset)));
}
References assembler_, base_, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::kSystemPointerSize, and v8::internal::compiler::CodeAssembler::LoadFullTagged().
GetTorqueArguments()
TorqueStructArguments v8::internal::CodeStubArguments::GetTorqueArguments () const [inline]
Definition at line 4897 of file code-stub-assembler.h.
                                                   {
    return TorqueStructArguments{fp_, base_, GetLengthWithoutReceiver(), argc_};
  }
MayHavePaddingArguments()
bool v8::internal::CodeStubArguments::MayHavePaddingArguments () const
Definition at line 17583 of file code-stub-assembler.cc.
                                                      {
  // If we're using a dynamic parameter count, then there may be additional
  // padding arguments on the stack pushed by the caller.
  return assembler_->HasDynamicJSParameterCount();
}
References assembler_, and v8::internal::compiler::CodeAssembler::HasDynamicJSParameterCount().
Referenced by PopAndReturn().
PopAndReturn()
void v8::internal::CodeStubArguments::PopAndReturn (TNode< JSAny > value)
Definition at line 17672 of file code-stub-assembler.cc.
                                                       {
  TNode<IntPtrT> argument_count = GetLengthWithReceiver();
  if (MayHavePaddingArguments()) {
    // If there may be padding arguments, we need to remove the maximum of the
    // parameter count and the actual argument count.
    // TODO(saelo): it would probably be nicer to have this logic in the
    // low-level assembler instead, where we also keep the parameter count
    // value. It's not even clear why we need this PopAndReturn method at all
    // in the higher-level CodeStubAssembler class, as the lower-level
    // assemblers should have all the necessary information.
    TNode<IntPtrT> parameter_count =
        assembler_->ChangeInt32ToIntPtr(assembler_->DynamicJSParameterCount());
    CodeStubAssembler::Label pop_parameter_count(assembler_),
        pop_argument_count(assembler_);
    assembler_->Branch(
        assembler_->IntPtrLessThan(argument_count, parameter_count),
        &pop_parameter_count, &pop_argument_count);
    assembler_->BIND(&pop_parameter_count);
    assembler_->PopAndReturn(parameter_count, value);
    assembler_->BIND(&pop_argument_count);
    assembler_->PopAndReturn(argument_count, value);
  } else {
    assembler_->PopAndReturn(argument_count, value);
  }
}
References assembler_, v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::ChangeInt32ToIntPtr(), v8::internal::compiler::CodeAssembler::DynamicJSParameterCount(), GetLengthWithReceiver(), MayHavePaddingArguments(), v8::internal::compiler::CodeAssembler::PopAndReturn(), and v8::internal::value.
Referenced by v8::internal::TF_BUILTIN().
SetReceiver()
void v8::internal::CodeStubArguments::SetReceiver (TNode< JSAny > object) const
Definition at line 17595 of file code-stub-assembler.cc.
                                                             {
  intptr_t offset = -kSystemPointerSize;
  assembler_->StoreFullTaggedNoWriteBarrier(
      base_, assembler_->IntPtrConstant(offset), object);
}
References assembler_, base_, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::kSystemPointerSize, and v8::internal::compiler::CodeAssembler::StoreFullTaggedNoWriteBarrier().
Member Data Documentation
argc_
TNode<IntPtrT> v8::internal::CodeStubArguments::argc_ [private]
Definition at line 4925 of file code-stub-assembler.h.
Referenced by CodeStubArguments(), GetLengthWithoutReceiver(), and GetLengthWithReceiver().
assembler_
CodeStubAssembler* v8::internal::CodeStubArguments::assembler_ [private]
Definition at line 4924 of file code-stub-assembler.h.
Referenced by AtIndex(), AtIndexPtr(), CodeStubArguments(), ForEach(), GetLengthWithoutReceiver(), GetOptionalArgumentValue(), GetReceiver(), MayHavePaddingArguments(), PopAndReturn(), and SetReceiver().
base_
TNode<RawPtrT> v8::internal::CodeStubArguments::base_ [private]
Definition at line 4926 of file code-stub-assembler.h.
Referenced by AtIndexPtr(), CodeStubArguments(), GetReceiver(), and SetReceiver().
fp_
TNode<RawPtrT> v8::internal::CodeStubArguments::fp_ [private]
Definition at line 4927 of file code-stub-assembler.h.
Referenced by CodeStubArguments().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/code-stub-assembler.h
/mnt/V8SourceCode/src/codegen/code-stub-assembler.cc