v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32 Class Reference
#include <maglev-ir.h>
Public Member Functions
CheckedTruncateNumberOrOddballToInt32 (uint64_t bitfield, TaggedToFloat64ConversionType conversion_type)
Input & input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
TaggedToFloat64ConversionType conversion_type () const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
Private Types
using Base = FixedInputValueNodeT< 1, CheckedTruncateNumberOrOddballToInt32 >
using TaggedToFloat64ConversionTypeOffset = NextBitField< TaggedToFloat64ConversionType, 2 >
Additional Inherited Members
Detailed Description
Definition at line 4849 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32::Base = FixedInputValueNodeT<1, CheckedTruncateNumberOrOddballToInt32> [private]
Definition at line 4851 of file maglev-ir.h.
TaggedToFloat64ConversionTypeOffset
using v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32::TaggedToFloat64ConversionTypeOffset = NextBitField<TaggedToFloat64ConversionType, 2> [private]
Definition at line 4877 of file maglev-ir.h.
Constructor & Destructor Documentation
CheckedTruncateNumberOrOddballToInt32()
v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32::CheckedTruncateNumberOrOddballToInt32 (uint64_t bitfield, TaggedToFloat64ConversionType conversion_type) [inline], [explicit]
Definition at line 4854 of file maglev-ir.h.
      : Base(TaggedToFloat64ConversionTypeOffset::update(bitfield,
                                                         conversion_type)) {}
Member Function Documentation
conversion_type()
TaggedToFloat64ConversionType v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32::conversion_type () const [inline]
Definition at line 4870 of file maglev-ir.h.
                                                        {
    return TaggedToFloat64ConversionTypeOffset::decode(bitfield());
  }
Referenced by options(), and PrintParams().
GenerateCode()
void v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32::GenerateCode (MaglevAssembler * , const ProcessingState &)
input()
Input& v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32::input () [inline]
Definition at line 4864 of file maglev-ir.h.
{ return Node::input(0); }
References v8::internal::maglev::NodeBase::input().
options()
auto v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32::options () const [inline]
Definition at line 4874 of file maglev-ir.h.
{ return std::tuple{conversion_type()}; }
References conversion_type().
PrintParams()
void v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8160 of file maglev-ir.cc.
                                                               {
  os << "(" << conversion_type() << ")";
}
References conversion_type().
SetValueLocationConstraints()
void v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 4862 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CheckedTruncateNumberOrOddballToInt32::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::EagerDeopt() | OpProperties::Int32()
Definition at line 4859 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc