wasm::anonymous_namespace{c-api.cc}::SignatureHelper Class Reference
Static Public Member Functions
static const i::wasm::CanonicalTypeIndex Canonicalize (FuncType *type)
static own< FuncType > FromV8Sig (const i::wasm::CanonicalSig *sig)
static const i::wasm::CanonicalSig * GetSig (i::DirectHandle< i::JSFunction > function)
Detailed Description
Definition at line 1510 of file c-api.cc.
Member Function Documentation
Canonicalize()
static const i::wasm::CanonicalTypeIndex wasm::anonymous_namespace{c-api.cc}::SignatureHelper::Canonicalize (FuncType * type) [inline], [static]
Definition at line 1512 of file c-api.cc.
                                                                    {
    std::vector<i::wasm::ValueType> types;
    types.reserve(type->results().size() + type->params().size());
    // TODO(jkummerow): Consider making vec<> range-based for-iterable.
    for (size_t i = 0; i < type->results().size(); i++) {
      types.push_back(WasmValKindToV8(type->results()[i]->kind()));
    }
    for (size_t i = 0; i < type->params().size(); i++) {
      types.push_back(WasmValKindToV8(type->params()[i]->kind()));
    }
    i::wasm::FunctionSig non_canonical_sig{type->results().size(),
                                           type->params().size(), types.data()};
    return i::wasm::GetTypeCanonicalizer()->AddRecursiveGroup(
        &non_canonical_sig);
  }
References v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), v8::internal::wasm::GetTypeCanonicalizer(), size(), v8::internal::tracing::type, and wasm::anonymous_namespace{c-api.cc}::WasmValKindToV8().
FromV8Sig()
static own<FuncType> wasm::anonymous_namespace{c-api.cc}::SignatureHelper::FromV8Sig (const i::wasm::CanonicalSig * sig) [inline], [static]
Definition at line 1530 of file c-api.cc.
                                                               {
    int result_arity = static_cast<int>(sig->return_count());
    int param_arity = static_cast<int>(sig->parameter_count());
    ownvec<ValType> results = ownvec<ValType>::make_uninitialized(result_arity);
    ownvec<ValType> params = ownvec<ValType>::make_uninitialized(param_arity);
    for (int i = 0; i < result_arity; ++i) {
      results[i] = ValType::make(V8ValueTypeToWasm(sig->GetReturn(i)));
    }
    for (int i = 0; i < param_arity; ++i) {
      params[i] = ValType::make(V8ValueTypeToWasm(sig->GetParam(i)));
    }
    return FuncType::make(std::move(params), std::move(results));
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::sig, and wasm::anonymous_namespace{c-api.cc}::V8ValueTypeToWasm().
GetSig()
static const i::wasm::CanonicalSig* wasm::anonymous_namespace{c-api.cc}::SignatureHelper::GetSig (i::DirectHandle< i::JSFunction > function) [inline], [static]
Definition at line 1545 of file c-api.cc.
                                           {
    return i::Cast<i::WasmCapiFunction>(*function)->sig();
  }
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/c-api.cc