v8::internal::ArrayBufferExtension Class Reference
#include <js-array-buffer.h>
Classes
struct AccountingState
Public Types
enum class Age : uint8_t { kYoung = 0
, kOld = 1
 }
Public Member Functions
ArrayBufferExtension (std::shared_ptr< BackingStore > backing_store, ArrayBufferExtension::Age age)
void Mark ()
void Unmark ()
bool IsMarked () const
void YoungMark ()
void YoungMarkPromoted ()
void YoungUnmark ()
bool IsYoungMarked () const
bool IsYoungPromoted () const
std::shared_ptr< BackingStore > backing_store ()
void set_backing_store (std::shared_ptr< BackingStore > backing_store)
std::shared_ptr< BackingStore > RemoveBackingStore ()
size_t accounting_length () const
AccountingState UpdateAccountingLength (int64_t delta)
AccountingState ClearAccountingLength ()
ArrayBufferExtension * next () const
void set_next (ArrayBufferExtension *extension)
Age age () const
AccountingState SetOld ()
AccountingState SetYoung ()
Private Types
enum class GcState : uint8_t { Dead = 0
, Copied
, Promoted
 }
using AgeField = base::BitField< uint8_t, 0, 1, uint64_t >
using AccountingLengthField = AgeField::Next< size_t, 63 >
Private Member Functions
GcState young_gc_state () const
void set_young_gc_state (GcState value)
Private Attributes
std::shared_ptr< BackingStore > backing_store_
ArrayBufferExtension * next_ = nullptr
std::atomic< uint64_t > accounting_state_
std::atomic< bool > marked_ {false}
std::atomic< GcState > young_gc_state_ {GcState::Dead}
Additional Inherited Members
Detailed Description
Definition at line 193 of file js-array-buffer.h.
Member Typedef Documentation
AccountingLengthField
using v8::internal::ArrayBufferExtension::AccountingLengthField = AgeField::Next<size_t, 63> [private]
Definition at line 282 of file js-array-buffer.h.
AgeField
using v8::internal::ArrayBufferExtension::AgeField = base::BitField<uint8_t, 0, 1, uint64_t> [private]
Definition at line 281 of file js-array-buffer.h.
Member Enumeration Documentation
Age
enum v8::internal::ArrayBufferExtension::Age : uint8_t [strong]
Enumerator
kYoung
kOld
Definition at line 200 of file js-array-buffer.h.
: uint8_t { kYoung = 0, kOld = 1 };
GcState
enum v8::internal::ArrayBufferExtension::GcState : uint8_t [strong], [private]
Enumerator
Dead
Copied
Promoted
Definition at line 279 of file js-array-buffer.h.
: uint8_t { Dead = 0, Copied, Promoted };
Constructor & Destructor Documentation
ArrayBufferExtension()
v8::internal::ArrayBufferExtension::ArrayBufferExtension (std::shared_ptr< BackingStore > backing_store, ArrayBufferExtension::Age age) [inline]
Definition at line 213 of file js-array-buffer.h.
      : backing_store_(std::move(backing_store)),
        accounting_state_(AccountingLengthField::encode(static_cast<size_t>(
                              backing_store_->PerIsolateAccountingLength())) |
                          AgeField::encode(static_cast<uint8_t>(age))) {}
Member Function Documentation
accounting_length()
size_t v8::internal::ArrayBufferExtension::accounting_length () const [inline]
Definition at line 238 of file js-array-buffer.h.
                                   {
    return AccountingState{accounting_state_.load(std::memory_order_relaxed)}
        .accounting_length();
  }
References accounting_state_.
Referenced by v8::internal::ArrayBufferSweeper::Append(), v8::internal::ArrayBufferList::BytesSlow(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepListFull(), and v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung().
age()
Age v8::internal::ArrayBufferExtension::age () const [inline]
Definition at line 264 of file js-array-buffer.h.
                  {
    return AccountingState{accounting_state_.load(std::memory_order_relaxed)}
        .age();
  }
References accounting_state_.
Referenced by v8::internal::ArrayBufferSweeper::Append(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepListFull(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung(), and v8::internal::JSArrayBuffer::YoungMarkExtension().
backing_store()
std::shared_ptr<BackingStore> v8::internal::ArrayBufferExtension::backing_store () [inline]
Definition at line 230 of file js-array-buffer.h.
{ return backing_store_; }
References backing_store_.
Referenced by set_backing_store().
ClearAccountingLength()
AccountingState v8::internal::ArrayBufferExtension::ClearAccountingLength () [inline]
Definition at line 256 of file js-array-buffer.h.
                                          {
    return {accounting_state_.fetch_and(AgeField::kMask,
                                        std::memory_order_relaxed)};
  }
References accounting_state_, and v8::base::BitField< T, shift, size, U >::kMask.
Referenced by v8::internal::ArrayBufferSweeper::Detach(), and v8::internal::ArrayBufferSweeper::ReleaseAll().
IsMarked()
bool v8::internal::ArrayBufferExtension::IsMarked () const [inline]
Definition at line 222 of file js-array-buffer.h.
{ return marked_.load(std::memory_order_relaxed); }
References marked_.
Referenced by v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepListFull().
IsYoungMarked()
bool v8::internal::ArrayBufferExtension::IsYoungMarked () const [inline]
Definition at line 227 of file js-array-buffer.h.
{ return young_gc_state() != GcState::Dead; }
References Dead, and young_gc_state().
Referenced by v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung().
IsYoungPromoted()
bool v8::internal::ArrayBufferExtension::IsYoungPromoted () const [inline]
Definition at line 228 of file js-array-buffer.h.
{ return young_gc_state() == GcState::Promoted; }
References Promoted, and young_gc_state().
Referenced by v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung().
Mark()
void v8::internal::ArrayBufferExtension::Mark () [inline]
Definition at line 220 of file js-array-buffer.h.
{ marked_.store(true, std::memory_order_relaxed); }
References marked_.
Referenced by v8::internal::JSArrayBuffer::MarkExtension(), and v8::internal::MarkingBarrier::Write().
next()
ArrayBufferExtension* v8::internal::ArrayBufferExtension::next () const [inline]
Definition at line 261 of file js-array-buffer.h.
{ return next_; }
References next_.
Referenced by v8::internal::ArrayBufferList::BytesSlow(), v8::internal::ArrayBufferList::ContainsSlow(), v8::internal::ArrayBufferSweeper::ReleaseAll(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepListFull(), and v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung().
RemoveBackingStore()
std::shared_ptr<BackingStore> v8::internal::ArrayBufferExtension::RemoveBackingStore () [inline]
Definition at line 234 of file js-array-buffer.h.
                                                   {
    return std::move(backing_store_);
  }
References backing_store_.
Referenced by v8::internal::JSArrayBuffer::RemoveExtension().
set_backing_store()
void v8::internal::ArrayBufferExtension::set_backing_store (std::shared_ptr< BackingStore > backing_store) [inline]
Definition at line 231 of file js-array-buffer.h.
                                                                    {
    backing_store_ = std::move(backing_store);
  }
References backing_store(), and backing_store_.
set_next()
void v8::internal::ArrayBufferExtension::set_next (ArrayBufferExtension * extension) [inline]
Definition at line 262 of file js-array-buffer.h.
{ next_ = extension; }
References next_.
Referenced by v8::internal::ArrayBufferList::Append().
set_young_gc_state()
void v8::internal::ArrayBufferExtension::set_young_gc_state (GcState value) [inline], [private]
Definition at line 288 of file js-array-buffer.h.
                                         {
    young_gc_state_.store(value, std::memory_order_relaxed);
  }
References v8::internal::value, and young_gc_state_.
Referenced by YoungMark(), YoungMarkPromoted(), and YoungUnmark().
SetOld()
AccountingState v8::internal::ArrayBufferExtension::SetOld () [inline]
Definition at line 269 of file js-array-buffer.h.
                           {
    return {
        accounting_state_.fetch_or(AgeField::kMask, std::memory_order_relaxed)};
  }
References accounting_state_, and v8::base::BitField< T, shift, size, U >::kMask.
Referenced by v8::internal::ArrayBufferList::Append().
SetYoung()
AccountingState v8::internal::ArrayBufferExtension::SetYoung () [inline]
Definition at line 273 of file js-array-buffer.h.
                             {
    return {accounting_state_.fetch_and(~AgeField::kMask,
                                        std::memory_order_relaxed)};
  }
References accounting_state_, and v8::base::BitField< T, shift, size, U >::kMask.
Referenced by v8::internal::ArrayBufferList::Append().
Unmark()
void v8::internal::ArrayBufferExtension::Unmark () [inline]
Definition at line 221 of file js-array-buffer.h.
{ marked_.store(false, std::memory_order_relaxed); }
References marked_.
Referenced by v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepListFull().
UpdateAccountingLength()
AccountingState v8::internal::ArrayBufferExtension::UpdateAccountingLength (int64_t delta) [inline]
Definition at line 244 of file js-array-buffer.h.
                                                        {
    if (delta >= 0) {
      return {accounting_state_.fetch_add(
          AccountingLengthField::encode(static_cast<size_t>(delta)),
          std::memory_order_relaxed)};
    }
    return {accounting_state_.fetch_sub(
        AccountingLengthField::encode(static_cast<size_t>(-delta)),
        std::memory_order_relaxed)};
  }
References accounting_state_, and v8::base::BitField< T, shift, size, U >::encode().
Referenced by v8::internal::ArrayBufferSweeper::Resize().
young_gc_state()
GcState v8::internal::ArrayBufferExtension::young_gc_state () const [inline], [private]
Definition at line 284 of file js-array-buffer.h.
                                 {
    return young_gc_state_.load(std::memory_order_relaxed);
  }
References young_gc_state_.
Referenced by IsYoungMarked(), and IsYoungPromoted().
YoungMark()
void v8::internal::ArrayBufferExtension::YoungMark () [inline]
Definition at line 224 of file js-array-buffer.h.
{ set_young_gc_state(GcState::Copied); }
References Copied, and set_young_gc_state().
Referenced by v8::internal::MarkingBarrier::Write(), and v8::internal::JSArrayBuffer::YoungMarkExtension().
YoungMarkPromoted()
void v8::internal::ArrayBufferExtension::YoungMarkPromoted () [inline]
Definition at line 225 of file js-array-buffer.h.
{ set_young_gc_state(GcState::Promoted); }
References Promoted, and set_young_gc_state().
Referenced by v8::internal::JSArrayBuffer::YoungMarkExtensionPromoted().
YoungUnmark()
void v8::internal::ArrayBufferExtension::YoungUnmark () [inline]
Definition at line 226 of file js-array-buffer.h.
{ set_young_gc_state(GcState::Dead); }
References Dead, and set_young_gc_state().
Referenced by v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::SweepYoung().
Member Data Documentation
accounting_state_
std::atomic<uint64_t> v8::internal::ArrayBufferExtension::accounting_state_ [private]
Definition at line 294 of file js-array-buffer.h.
Referenced by accounting_length(), age(), ClearAccountingLength(), SetOld(), SetYoung(), and UpdateAccountingLength().
backing_store_
std::shared_ptr<BackingStore> v8::internal::ArrayBufferExtension::backing_store_ [private]
Definition at line 292 of file js-array-buffer.h.
Referenced by backing_store(), RemoveBackingStore(), and set_backing_store().
marked_
std::atomic<bool> v8::internal::ArrayBufferExtension::marked_ {false} [private]
Definition at line 295 of file js-array-buffer.h.
Referenced by IsMarked(), Mark(), and Unmark().
next_
ArrayBufferExtension* v8::internal::ArrayBufferExtension::next_ = nullptr [private]
Definition at line 293 of file js-array-buffer.h.
Referenced by next(), and set_next().
young_gc_state_
std::atomic<GcState> v8::internal::ArrayBufferExtension::young_gc_state_ {GcState::Dead} [private]
Definition at line 296 of file js-array-buffer.h.
Referenced by set_young_gc_state(), and young_gc_state().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/js-array-buffer.h