v8::internal::NumberDictionary Class Reference
#include <dictionary.h>
Public Member Functions
template<template< typename > typename HandleType>
requires (std::is_convertible_v< HandleType< NumberDictionary >, DirectHandle< NumberDictionary >>) V8_WARN_UNUSED_RESULT static HandleType< NumberDictionary > Set(Isolate *isolate
void UpdateMaxNumberKey (uint32_t key, DirectHandle< JSObject > dictionary_holder)
void CopyValuesTo (Tagged< FixedArray > elements)
bool requires_slow_elements ()
void set_requires_slow_elements ()
uint32_t max_number_key ()
Static Public Member Functions
static DirectHandle< Map > GetMap (RootsTable &roots)
static void UncheckedSet (Isolate *isolate, DirectHandle< NumberDictionary > dictionary, uint32_t key, DirectHandle< Object > value)
Public Attributes
HandleType< NumberDictionary > dictionary
HandleType< NumberDictionary > uint32_t key
HandleType< NumberDictionary > uint32_t DirectHandle< Object > value
HandleType< NumberDictionary > uint32_t DirectHandle< Object > DirectHandle< JSObject > dictionary_holder = DirectHandle<JSObject>::null()
HandleType< NumberDictionary > uint32_t DirectHandle< Object > DirectHandle< JSObject > PropertyDetails details = PropertyDetails::Empty())
Static Public Attributes
static const int kMaxNumberKeyIndex = kPrefixStartIndex
static const int kEntryValueIndex = 1
static const int kEntryDetailsIndex = 2
static const int kRequiresSlowElementsMask = 1
static const int kRequiresSlowElementsTagSize = 1
static const uint32_t kRequiresSlowElementsLimit = (1 << 29) - 1
static const uint32_t kPreferFastElementsSizeFactor = 3
Detailed Description
Definition at line 425 of file dictionary.h.
Member Function Documentation
CopyValuesTo()
void v8::internal::NumberDictionary::CopyValuesTo (Tagged< FixedArray > elements)
Definition at line 5951 of file objects.cc.
                                                               {
  ReadOnlyRoots roots = GetReadOnlyRoots();
  int pos = 0;
  DisallowGarbageCollection no_gc;
  WriteBarrierMode mode = elements->GetWriteBarrierMode(no_gc);
  for (InternalIndex i : this->IterateEntries()) {
    Tagged<Object> k;
    if (this->ToKey(roots, i, &k)) {
      elements->set(pos++, this->ValueAt(i), mode);
    }
  }
  DCHECK_EQ(pos, elements->length());
}
References DCHECK_EQ, v8::internal::GetReadOnlyRoots(), mode(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
GetMap()
DirectHandle< Map > v8::internal::NumberDictionary::GetMap (RootsTable & roots) [inline], [static]
Definition at line 314 of file dictionary-inl.h.
                                                            {
  return roots.number_dictionary_map();
}
max_number_key()
uint32_t v8::internal::NumberDictionary::max_number_key () [inline]
Definition at line 146 of file dictionary-inl.h.
                                          {
  DCHECK(!requires_slow_elements());
  Tagged<Object> max_index_object = get(kMaxNumberKeyIndex);
  if (!IsSmi(max_index_object)) return 0;
  uint32_t value = static_cast<uint32_t>(Smi::ToInt(max_index_object));
  return value >> kRequiresSlowElementsTagSize;
}
requires()
template<template< typename > typename HandleType>
v8::internal::NumberDictionary::requires (std::is_convertible_v< HandleType< NumberDictionary >, DirectHandle< NumberDictionary >>)
requires_slow_elements()
bool v8::internal::NumberDictionary::requires_slow_elements () [inline]
Definition at line 140 of file dictionary-inl.h.
                                              {
  Tagged<Object> max_index_object = get(kMaxNumberKeyIndex);
  if (!IsSmi(max_index_object)) return false;
  return 0 != (Smi::ToInt(max_index_object) & kRequiresSlowElementsMask);
}
References v8::internal::IsSmi(), kMaxNumberKeyIndex, kRequiresSlowElementsMask, and v8::internal::Smi::ToInt().
set_requires_slow_elements()
void v8::internal::NumberDictionary::set_requires_slow_elements () [inline]
Definition at line 154 of file dictionary-inl.h.
                                                  {
  set(kMaxNumberKeyIndex, Smi::FromInt(kRequiresSlowElementsMask));
}
References v8::internal::Smi::FromInt(), kMaxNumberKeyIndex, and kRequiresSlowElementsMask.
UncheckedSet()
void v8::internal::NumberDictionary::UncheckedSet (Isolate * isolate, DirectHandle< NumberDictionary > dictionary, uint32_t key, DirectHandle< Object > value) [static]
Definition at line 5945 of file objects.cc.
                                                                              {
  UncheckedAtPut(isolate, dictionary, key, value, PropertyDetails::Empty());
}
References v8::internal::PropertyDetails::Empty(), v8::internal::key, and v8::internal::value.
Referenced by v8::internal::JsonParser< Char >::BuildJsonObject().
UpdateMaxNumberKey()
void v8::internal::NumberDictionary::UpdateMaxNumberKey (uint32_t key, DirectHandle< JSObject > dictionary_holder)
Definition at line 5896 of file objects.cc.
                                                            {
  DisallowGarbageCollection no_gc;
  // If the dictionary requires slow elements an element has already
  // been added at a high index.
  if (requires_slow_elements()) return;
  // Check if this index is high enough that we should require slow
  // elements.
  if (key > kRequiresSlowElementsLimit) {
    if (!dictionary_holder.is_null()) {
      dictionary_holder->RequireSlowElements(this);
    }
    set_requires_slow_elements();
    return;
  }
  // Update max key value.
  Tagged<Object> max_index_object = get(kMaxNumberKeyIndex);
  if (!IsSmi(max_index_object) || max_number_key() < key) {
    FixedArray::set(kMaxNumberKeyIndex,
                    Smi::FromInt(key << kRequiresSlowElementsTagSize));
  }
}
References v8::internal::Smi::FromInt(), v8::internal::DirectHandle< T >::is_null(), v8::internal::IsSmi(), v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::set().
Member Data Documentation
details
HandleType<NumberDictionary> uint32_t DirectHandle<Object> DirectHandle<JSObject> PropertyDetails v8::internal::NumberDictionary::details = PropertyDetails::Empty())
Definition at line 440 of file dictionary.h.
dictionary
HandleType<NumberDictionary> v8::internal::NumberDictionary::dictionary
Definition at line 437 of file dictionary.h.
dictionary_holder
HandleType<NumberDictionary> uint32_t DirectHandle<Object> DirectHandle<JSObject> v8::internal::NumberDictionary::dictionary_holder = DirectHandle<JSObject>::null()
Definition at line 439 of file dictionary.h.
kEntryDetailsIndex
const int v8::internal::NumberDictionary::kEntryDetailsIndex = 2 [static]
Definition at line 471 of file dictionary.h.
kEntryValueIndex
const int v8::internal::NumberDictionary::kEntryValueIndex = 1 [static]
Definition at line 470 of file dictionary.h.
key
HandleType<NumberDictionary> uint32_t v8::internal::NumberDictionary::key
Definition at line 437 of file dictionary.h.
kMaxNumberKeyIndex
const int v8::internal::NumberDictionary::kMaxNumberKeyIndex = kPrefixStartIndex [static]
Definition at line 450 of file dictionary.h.
Referenced by requires_slow_elements(), and set_requires_slow_elements().
kPreferFastElementsSizeFactor
const uint32_t v8::internal::NumberDictionary::kPreferFastElementsSizeFactor = 3 [static]
Definition at line 480 of file dictionary.h.
Referenced by v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::DeleteCommon().
kRequiresSlowElementsLimit
const uint32_t v8::internal::NumberDictionary::kRequiresSlowElementsLimit = (1 << 29) - 1 [static]
Definition at line 476 of file dictionary.h.
Referenced by v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::ValidateContents().
kRequiresSlowElementsMask
const int v8::internal::NumberDictionary::kRequiresSlowElementsMask = 1 [static]
Definition at line 474 of file dictionary.h.
Referenced by requires_slow_elements(), and set_requires_slow_elements().
kRequiresSlowElementsTagSize
const int v8::internal::NumberDictionary::kRequiresSlowElementsTagSize = 1 [static]
Definition at line 475 of file dictionary.h.
value
HandleType<NumberDictionary> uint32_t DirectHandle<Object> v8::internal::NumberDictionary::value
Definition at line 438 of file dictionary.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/dictionary.h
/mnt/V8SourceCode/src/objects/dictionary-inl.h
/mnt/V8SourceCode/src/objects/objects.cc