disasm::Disassembler Class Reference
#include <disasm.h>
Public Types
enum UnimplementedOpcodeAction : int8_t { kContinueOnUnimplementedOpcode
, kAbortOnUnimplementedOpcode
 }
Public Member Functions
Disassembler (const NameConverter &converter, UnimplementedOpcodeAction unimplemented_opcode_action=kAbortOnUnimplementedOpcode)
UnimplementedOpcodeAction unimplemented_opcode_action () const
V8_EXPORT_PRIVATE int InstructionDecode (v8::base::Vector< char > buffer, uint8_t *instruction)
int ConstantPoolSizeAt (uint8_t *instruction)
Static Public Member Functions
static V8_EXPORT_PRIVATE void Disassemble (FILE *f, uint8_t *begin, uint8_t *end, UnimplementedOpcodeAction unimplemented_action=kAbortOnUnimplementedOpcode)
Private Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (Disassembler)
Private Attributes
const NameConverter & converter_
const UnimplementedOpcodeAction unimplemented_opcode_action_
Detailed Description
Definition at line 36 of file disasm.h.
Member Enumeration Documentation
UnimplementedOpcodeAction
enum disasm::Disassembler::UnimplementedOpcodeAction : int8_t
Enumerator
kContinueOnUnimplementedOpcode
kAbortOnUnimplementedOpcode
Definition at line 38 of file disasm.h.
                                 : int8_t {
    kContinueOnUnimplementedOpcode,
    kAbortOnUnimplementedOpcode
  };
Constructor & Destructor Documentation
Disassembler()
disasm::Disassembler::Disassembler (const NameConverter & converter, UnimplementedOpcodeAction unimplemented_opcode_action = kAbortOnUnimplementedOpcode) [inline], [explicit]
Definition at line 44 of file disasm.h.
      : converter_(converter),
        unimplemented_opcode_action_(unimplemented_opcode_action) {}
Member Function Documentation
ConstantPoolSizeAt()
int disasm::Disassembler::ConstantPoolSizeAt (uint8_t * instruction)
Definition at line 3352 of file disasm-riscv.cc.
                                                         {
  return v8::internal::Assembler::ConstantPoolSizeAt(
      reinterpret_cast<v8::internal::Instruction*>(instruction));
}
References v8::internal::Assembler::ConstantPoolSizeAt().
DISALLOW_IMPLICIT_CONSTRUCTORS()
disasm::Disassembler::DISALLOW_IMPLICIT_CONSTRUCTORS (Disassembler) [private]
Disassemble()
void disasm::Disassembler::Disassemble (FILE * f, uint8_t * begin, uint8_t * end, UnimplementedOpcodeAction unimplemented_action = kAbortOnUnimplementedOpcode) [static]
Definition at line 3357 of file disasm-riscv.cc.
                                                                               {
  NameConverter converter;
  Disassembler d(converter, unimplemented_action);
  for (uint8_t* pc = begin; pc < end;) {
    v8::base::EmbeddedVector<char, 128> buffer;
    buffer[0] = '\0';
    uint8_t* prev_pc = pc;
    pc += d.InstructionDecode(buffer, pc);
    v8::internal::PrintF(f, "%p %08x %s\n", static_cast<void*>(prev_pc),
                         *reinterpret_cast<uint32_t*>(prev_pc), buffer.begin());
  }
}
References v8::base::Vector< T >::begin(), v8::internal::compiler::begin(), v8::internal::compiler::end(), InstructionDecode(), and v8::internal::PrintF().
InstructionDecode()
int disasm::Disassembler::InstructionDecode (v8::base::Vector< char > buffer, uint8_t * instruction)
Definition at line 3346 of file disasm-riscv.cc.
                                                          {
  v8::internal::Decoder d(converter_, buffer);
  return d.InstructionDecode(instruction);
}
References converter_, and v8::internal::Decoder< V >::InstructionDecode().
Referenced by Disassemble().
unimplemented_opcode_action()
UnimplementedOpcodeAction disasm::Disassembler::unimplemented_opcode_action () const [inline]
Definition at line 50 of file disasm.h.
                                                                {
    return unimplemented_opcode_action_;
  }
References unimplemented_opcode_action_.
Member Data Documentation
converter_
const NameConverter& disasm::Disassembler::converter_ [private]
Definition at line 71 of file disasm.h.
Referenced by InstructionDecode().
unimplemented_opcode_action_
const UnimplementedOpcodeAction disasm::Disassembler::unimplemented_opcode_action_ [private]
Definition at line 72 of file disasm.h.
Referenced by unimplemented_opcode_action().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/diagnostics/disasm.h
/mnt/V8SourceCode/src/diagnostics/riscv/disasm-riscv.cc