v8::internal::Operand Class Reference
#include <assembler-arm.h>
Classes
struct LabelOperand
struct MemoryOperand
union Value
Public Member Functions
Operand (int32_t immediate, RelocInfo::Mode rmode=RelocInfo::NO_INFO)
Operand (const ExternalReference &f)
Operand (Handle< HeapObject > handle)
Operand (Tagged< Smi > value)
Operand (Register rm)
Operand (Register rm, ShiftOp shift_op, int shift_imm)
Operand (Register rm, ShiftOp shift_op, Register rs)
bool IsRegister () const
bool IsImmediateShiftedRegister () const
bool IsRegisterShiftedRegister () const
int InstructionsRequired (const Assembler *assembler, Instr instr=0) const
bool MustOutputRelocInfo (const Assembler *assembler) const
int32_t immediate () const
bool IsImmediate () const
HeapNumberRequest heap_number_request () const
bool IsHeapNumberRequest () const
Register rm () const
Register rs () const
ShiftOp shift_op () const
Operand (Register reg, Shift shift=LSL, unsigned shift_amount=0)
Operand (Register reg, Extend extend, unsigned shift_amount=0)
bool IsHeapNumberRequest () const
HeapNumberRequest heap_number_request () const
Immediate immediate_for_heap_number_request () const
template<typename T >
Operand (T t)
template<typename T >
Operand (T t, RelocInfo::Mode rmode)
bool IsImmediate () const
bool IsShiftedRegister () const
bool IsExtendedRegister () const
bool IsZero () const
Operand ToExtendedRegister () const
Operand ToW () const
Immediate immediate () const
int64_t ImmediateValue () const
RelocInfo::Mode ImmediateRMode () const
Register reg () const
Shift shift () const
Extend extend () const
unsigned shift_amount () const
bool NeedsRelocation (const Assembler *assembler) const
Operand (Register reg)
Operand (XMMRegister xmm_reg)
Operand (int32_t disp, RelocInfo::Mode rmode)
Operand (Immediate imm)
Operand (Register base, int32_t disp, RelocInfo::Mode rmode=RelocInfo::NO_INFO)
Operand (Label *label)
Operand (Register base, Register index, ScaleFactor scale, int32_t disp, RelocInfo::Mode rmode=RelocInfo::NO_INFO)
Operand (Register index, ScaleFactor scale, int32_t disp, RelocInfo::Mode rmode=RelocInfo::NO_INFO)
bool is_reg (Register reg) const
bool is_reg (XMMRegister reg) const
bool is_reg_only () const
Register reg () const
base::Vector< const uint8_t > encoded_bytes () const
RelocInfo::Mode rmode ()
Operand (int64_t immediate, RelocInfo::Mode rmode=RelocInfo::NO_INFO)
Operand (const ExternalReference &f)
Operand (Tagged< Smi > value)
Operand (Handle< HeapObject > handle)
Operand (Register rm)
bool is_reg () const
int64_t immediate () const
bool IsImmediate () const
HeapNumberRequest heap_number_request () const
bool IsHeapNumberRequest () const
Register rm () const
RelocInfo::Mode rmode () const
Operand (int64_t immediate, RelocInfo::Mode rmode=RelocInfo::NO_INFO)
Operand (const ExternalReference &f)
Operand (Tagged< Smi > value)
Operand (Handle< HeapObject > handle)
Operand (Register rm)
bool is_reg () const
int64_t immediate () const
bool IsImmediate () const
HeapNumberRequest heap_number_request () const
bool IsHeapNumberRequest () const
Register rm () const
RelocInfo::Mode rmode () const
Operand (intptr_t immediate, RelocInfo::Mode rmode=RelocInfo::NO_INFO)
Operand (const ExternalReference &f)
Operand (Handle< HeapObject > handle)
Operand (Tagged< Smi > value)
Operand (Register rm)
bool is_reg () const
bool must_output_reloc_info (const Assembler *assembler) const
intptr_t immediate () const
bool IsImmediate () const
HeapNumberRequest heap_number_request () const
Register rm () const
bool IsHeapNumberRequest () const
Operand (intptr_t immediate, RelocInfo::Mode rmode=RelocInfo::NO_INFO)
Operand (Tagged< Smi > value)
Operand (const ExternalReference &f)
Operand (Handle< HeapObject > handle, RelocInfo::Mode rmode=RelocInfo::FULL_EMBEDDED_OBJECT)
Operand (Register rm)
bool is_reg () const
intptr_t immediate_for_heap_number_request () const
intptr_t immediate () const
bool IsImmediate () const
HeapNumberRequest heap_number_request () const
bool IsHeapNumberRequest () const
Register rm () const
RelocInfo::Mode rmode () const
Operand (intptr_t immediate, RelocInfo::Mode rmode=RelocInfo::NO_INFO)
Operand (const ExternalReference &f)
Operand (Handle< HeapObject > handle)
Operand (Tagged< Smi > value)
Operand (Register rm)
bool is_reg () const
bool must_output_reloc_info (const Assembler *assembler) const
intptr_t immediate () const
HeapNumberRequest heap_number_request () const
void setBits (int n)
Register rm () const
bool is_heap_number_request () const
RelocInfo::Mode rmode () const
constexpr Operand (Register base, int32_t disp)
Operand (Register base, Register index, ScaleFactor scale, int32_t disp)
Operand (Register index, ScaleFactor scale, int32_t disp)
Operand (Operand base, int32_t offset)
Operand (Label *label, int addend=0)
Operand (const Operand &) V8_NOEXCEPT=default
Operand & operator= (const Operand &) V8_NOEXCEPT=default
constexpr bool is_label_operand () const
constexpr uint8_t rex () const
const MemoryOperand & memory () const
const LabelOperand & label () const
bool AddressUsesRegister (Register reg) const
Static Public Member Functions
static Operand Zero ()
static Operand SmiUntag (Register rm)
static Operand PointerOffsetFromSmiKey (Register key)
static Operand DoubleOffsetFromSmiKey (Register key)
static Operand EmbeddedNumber (double number)
static Operand EmbeddedNumber (double number)
static Operand EmbeddedHeapNumber (double number)
static Operand JumpTable (Register index, ScaleFactor scale, Label *table)
static Operand ForRegisterPlusImmediate (Register base, Immediate imm)
static Operand EmbeddedNumber (double number)
static Operand EmbeddedNumber (double number)
static Operand Zero ()
static Operand EmbeddedNumber (double number)
static Operand EmbeddedNumber (double number)
static Operand Zero ()
static Operand EmbeddedNumber (double value)
Private Member Functions
void set_modrm (int mod, Register rm)
void set_sib (ScaleFactor scale, Register index, Register base)
void set_disp8 (int8_t disp)
void set_dispr (int32_t disp, RelocInfo::Mode rmode)
bool is_reg (int reg_code) const
constexpr void set_modrm (int mod, Register rm_reg)
constexpr void set_sib (ScaleFactor scale, Register index, Register base)
constexpr void set_disp8 (int disp)
void set_disp32 (int disp)
Private Attributes
Register rm_ = no_reg
Register rs_ = no_reg
ShiftOp shift_op_
int shift_imm_
union v8::internal::Operand::Value value_
bool is_heap_number_request_ = false
RelocInfo::Mode rmode_ = RelocInfo::NO_INFO
std::optional< HeapNumberRequest > heap_number_request_
Immediate immediate_
Register reg_
Shift shift_
Extend extend_
unsigned shift_amount_
uint8_t buf_ [6]
uint8_t len_ = 0
xx xx xx xx xx xx xx xx xx
union {
 LabelOperand label_
 MemoryOperand memory_ = {}
};
Friends
class Assembler
class MacroAssembler
Detailed Description
Definition at line 84 of file assembler-arm.h.
Constructor & Destructor Documentation
Operand() [1/50]
v8::internal::Operand::Operand (int32_t immediate, RelocInfo::Mode rmode = RelocInfo::NO_INFO) [inline], [explicit]
Definition at line 87 of file assembler-arm.h.
      : rmode_(rmode) {
    value_.immediate = immediate;
  }
Referenced by EmbeddedNumber(), ToExtendedRegister(), ToW(), and Zero().
Operand() [2/50]
v8::internal::Operand::Operand (const ExternalReference & f) [inline], [explicit]
Definition at line 173 of file assembler-arm-inl.h.
    : rmode_(RelocInfo::EXTERNAL_REFERENCE) {
  value_.immediate = static_cast<int32_t>(f.address());
}
References v8::internal::ExternalReference::address(), v8::internal::Operand::Value::immediate, and value_.
Operand() [3/50]
v8::internal::Operand::Operand (Handle< HeapObject > handle) [explicit]
Operand() [4/50]
v8::internal::Operand::Operand (Tagged< Smi > value) [inline], [explicit]
Definition at line 178 of file assembler-arm-inl.h.
                                  : rmode_(RelocInfo::NO_INFO) {
  value_.immediate = static_cast<intptr_t>(value.ptr());
}
References v8::internal::Operand::Value::immediate, v8::internal::value, and value_.
Operand() [5/50]
v8::internal::Operand::Operand (Register rm) [inline], [explicit]
Definition at line 182 of file assembler-arm-inl.h.
: rm_(rm), shift_op_(LSL), shift_imm_(0) {}
Operand() [6/50]
v8::internal::Operand::Operand (Register rm, ShiftOp shift_op, int shift_imm) [explicit]
Operand() [7/50]
v8::internal::Operand::Operand (Register rm, ShiftOp shift_op, Register rs) [explicit]
Operand() [8/50]
v8::internal::Operand::Operand (Register reg, Shift shift = LSL, unsigned shift_amount = 0) [inline]
Definition at line 253 of file assembler-arm64-inl.h.
    : immediate_(0),
      reg_(reg),
      shift_(shift),
      extend_(NO_EXTEND),
      shift_amount_(shift_amount) {
  DCHECK(reg.Is64Bits() || (shift_amount < kWRegSizeInBits));
  DCHECK(reg.Is32Bits() || (shift_amount < kXRegSizeInBits));
  DCHECK_IMPLIES(reg.IsSP(), shift_amount == 0);
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::CPURegister::Is32Bits(), v8::internal::CPURegister::Is64Bits(), v8::internal::CPURegister::IsSP(), v8::internal::kWRegSizeInBits, v8::internal::kXRegSizeInBits, reg(), and shift_amount().
Operand() [9/50]
v8::internal::Operand::Operand (Register reg, Extend extend, unsigned shift_amount = 0) [inline]
Definition at line 264 of file assembler-arm64-inl.h.
    : immediate_(0),
      reg_(reg),
      shift_(NO_SHIFT),
      extend_(extend),
      shift_amount_(shift_amount) {
  DCHECK(reg.is_valid());
  DCHECK_LE(shift_amount, 4);
  DCHECK(!reg.IsSP());
  // Extend modes SXTX and UXTX require a 64-bit register.
  DCHECK(reg.Is64Bits() || ((extend != SXTX) && (extend != UXTX)));
}
References v8::internal::DCHECK(), DCHECK_LE, extend(), v8::internal::CPURegister::Is64Bits(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::CPURegister::IsSP(), reg(), shift_amount(), v8::internal::SXTX, and v8::internal::UXTX.
Operand() [10/50]
template<typename T >
v8::internal::Operand::Operand (T t) [inline]
Definition at line 247 of file assembler-arm64-inl.h.
: immediate_(t), reg_(NoReg) {}
Operand() [11/50]
template<typename T >
v8::internal::Operand::Operand (T t, RelocInfo::Mode rmode) [inline]
Definition at line 250 of file assembler-arm64-inl.h.
    : immediate_(t, rmode), reg_(NoReg) {}
Operand() [12/50]
v8::internal::Operand::Operand (Register reg) [inline], [explicit]
Definition at line 226 of file assembler-ia32.h.
{ set_modrm(3, reg); }
Operand() [13/50]
v8::internal::Operand::Operand (XMMRegister xmm_reg) [inline], [explicit]
Definition at line 229 of file assembler-ia32.h.
                                                  {
    Register reg = Register::from_code(xmm_reg.code());
    set_modrm(3, reg);
  }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), and v8::internal::Register::from_code().
Operand() [14/50]
v8::internal::Operand::Operand (int32_t disp, RelocInfo::Mode rmode) [inline], [explicit]
Definition at line 235 of file assembler-ia32.h.
                                                                {
    set_modrm(0, ebp);
    set_dispr(disp, rmode);
  }
Operand() [15/50]
v8::internal::Operand::Operand (Immediate imm) [inline], [explicit]
Definition at line 241 of file assembler-ia32.h.
                                            {
    set_modrm(0, ebp);
    set_dispr(imm.immediate(), imm.rmode_);
  }
Operand() [16/50]
v8::internal::Operand::Operand (Register base, int32_t disp, RelocInfo::Mode rmode = RelocInfo::NO_INFO) [explicit]
Operand() [17/50]
v8::internal::Operand::Operand (Label * label) [inline], [explicit]
Definition at line 251 of file assembler-ia32.h.
                                 {
    set_modrm(0, ebp);
    set_dispr(reinterpret_cast<intptr_t>(label), RelocInfo::INTERNAL_REFERENCE);
  }
References v8::internal::RelocInfo::INTERNAL_REFERENCE.
Operand() [18/50]
v8::internal::Operand::Operand (Register base, Register index, ScaleFactor scale, int32_t disp, RelocInfo::Mode rmode = RelocInfo::NO_INFO) [explicit]
Operand() [19/50]
v8::internal::Operand::Operand (Register index, ScaleFactor scale, int32_t disp, RelocInfo::Mode rmode = RelocInfo::NO_INFO) [explicit]
Operand() [20/50]
v8::internal::Operand::Operand (int64_t immediate, RelocInfo::Mode rmode = RelocInfo::NO_INFO) [inline], [explicit]
Definition at line 35 of file assembler-loong64.h.
      : rm_(no_reg), rmode_(rmode) {
    value_.immediate = immediate;
  }
References immediate(), v8::internal::Operand::Value::immediate, and value_.
Operand() [21/50]
v8::internal::Operand::Operand (const ExternalReference & f) [inline], [explicit]
Definition at line 40 of file assembler-loong64.h.
      : rm_(no_reg), rmode_(RelocInfo::EXTERNAL_REFERENCE) {
    value_.immediate = static_cast<int64_t>(f.address());
  }
References v8::internal::ExternalReference::address(), v8::internal::Operand::Value::immediate, and value_.
Operand() [22/50]
v8::internal::Operand::Operand (Tagged< Smi > value) [inline], [explicit]
Definition at line 44 of file assembler-loong64.h.
      : Operand(static_cast<intptr_t>(value.ptr())) {}
Operand() [23/50]
v8::internal::Operand::Operand (Handle< HeapObject > handle) [explicit]
Operand() [24/50]
v8::internal::Operand::Operand (Register rm) [inline], [explicit]
Definition at line 52 of file assembler-loong64.h.
: rm_(rm) {}
Operand() [25/50]
v8::internal::Operand::Operand (int64_t immediate, RelocInfo::Mode rmode = RelocInfo::NO_INFO) [inline], [explicit]
Definition at line 65 of file assembler-mips64.h.
      : rm_(no_reg), rmode_(rmode) {
    value_.immediate = immediate;
  }
References immediate(), v8::internal::Operand::Value::immediate, and value_.
Operand() [26/50]
v8::internal::Operand::Operand (const ExternalReference & f) [inline], [explicit]
Definition at line 70 of file assembler-mips64.h.
      : rm_(no_reg), rmode_(RelocInfo::EXTERNAL_REFERENCE) {
    value_.immediate = static_cast<int64_t>(f.address());
  }
References v8::internal::ExternalReference::address(), v8::internal::Operand::Value::immediate, and value_.
Operand() [27/50]
v8::internal::Operand::Operand (Tagged< Smi > value) [inline], [explicit]
Definition at line 74 of file assembler-mips64.h.
      : Operand(static_cast<intptr_t>(value.ptr())) {}
Operand() [28/50]
v8::internal::Operand::Operand (Handle< HeapObject > handle) [explicit]
Operand() [29/50]
v8::internal::Operand::Operand (Register rm) [inline], [explicit]
Definition at line 82 of file assembler-mips64.h.
: rm_(rm) {}
Operand() [30/50]
v8::internal::Operand::Operand (intptr_t immediate, RelocInfo::Mode rmode = RelocInfo::NO_INFO) [inline], [explicit]
Definition at line 68 of file assembler-ppc.h.
      : rmode_(rmode) {
    value_.immediate = immediate;
  }
Operand() [31/50]
v8::internal::Operand::Operand (const ExternalReference & f) [inline], [explicit]
Definition at line 74 of file assembler-ppc.h.
      : rmode_(RelocInfo::EXTERNAL_REFERENCE) {
    value_.immediate = static_cast<intptr_t>(f.address());
  }
References v8::internal::ExternalReference::address().
Operand() [32/50]
v8::internal::Operand::Operand (Handle< HeapObject > handle) [explicit]
Operand() [33/50]
v8::internal::Operand::Operand (Tagged< Smi > value) [inline], [explicit]
Definition at line 79 of file assembler-ppc.h.
                                                : rmode_(RelocInfo::NO_INFO) {
    value_.immediate = static_cast<intptr_t>(value.ptr());
  }
References v8::internal::value.
Operand() [34/50]
v8::internal::Operand::Operand (Register rm) [inline], [explicit]
Operand() [35/50]
v8::internal::Operand::Operand (intptr_t immediate, RelocInfo::Mode rmode = RelocInfo::NO_INFO) [inline], [explicit]
Definition at line 85 of file assembler-riscv.h.
      : rm_(no_reg), rmode_(rmode) {
    value_.immediate = immediate;
  }
References immediate(), v8::internal::Operand::Value::immediate, and value_.
Operand() [36/50]
v8::internal::Operand::Operand (Tagged< Smi > value) [inline], [explicit]
Definition at line 91 of file assembler-riscv.h.
      : Operand(static_cast<intptr_t>(value.ptr())) {}
Operand() [37/50]
v8::internal::Operand::Operand (const ExternalReference & f) [inline], [explicit]
Definition at line 94 of file assembler-riscv.h.
      : rm_(no_reg), rmode_(RelocInfo::EXTERNAL_REFERENCE) {
    value_.immediate = static_cast<intptr_t>(f.address());
  }
References v8::internal::ExternalReference::address(), v8::internal::Operand::Value::immediate, and value_.
Operand() [38/50]
v8::internal::Operand::Operand (Handle< HeapObject > handle, RelocInfo::Mode rmode = RelocInfo::FULL_EMBEDDED_OBJECT) [explicit]
Definition at line 220 of file assembler-riscv.cc.
    : rm_(no_reg), rmode_(rmode) {
  DCHECK(RelocInfo::IsEmbeddedObjectMode(rmode) || RelocInfo::IsNoInfo(rmode));
  value_.immediate = static_cast<intptr_t>(handle.address());
}
References v8::internal::DCHECK(), v8::internal::handle(), v8::internal::Operand::Value::immediate, v8::internal::RelocInfo::IsEmbeddedObjectMode(), v8::internal::RelocInfo::IsNoInfo(), rmode(), and value_.
Operand() [39/50]
v8::internal::Operand::Operand (Register rm) [inline], [explicit]
Definition at line 105 of file assembler-riscv.h.
: rm_(rm) {}
Operand() [40/50]
v8::internal::Operand::Operand (intptr_t immediate, RelocInfo::Mode rmode = RelocInfo::NO_INFO) [inline], [explicit]
Definition at line 75 of file assembler-s390.h.
      : rmode_(rmode) {
    value_.immediate = immediate;
  }
Operand() [41/50]
v8::internal::Operand::Operand (const ExternalReference & f) [inline], [explicit]
Definition at line 81 of file assembler-s390.h.
      : rmode_(RelocInfo::EXTERNAL_REFERENCE) {
    value_.immediate = static_cast<intptr_t>(f.address());
  }
References v8::internal::ExternalReference::address().
Operand() [42/50]
v8::internal::Operand::Operand (Handle< HeapObject > handle) [explicit]
Operand() [43/50]
v8::internal::Operand::Operand (Tagged< Smi > value) [inline], [explicit]
Definition at line 86 of file assembler-s390.h.
                                                : rmode_(RelocInfo::NO_INFO) {
    value_.immediate = static_cast<intptr_t>(value.ptr());
  }
References v8::internal::value.
Operand() [44/50]
v8::internal::Operand::Operand (Register rm) [inline], [explicit]
Operand() [45/50]
constexpr v8::internal::Operand::Operand (Register base, int32_t disp) [inline], [constexpr]
Definition at line 223 of file assembler-x64.h.
                                                           {
    if (base == rsp || base == r12) {
      // SIB byte is needed to encode (rsp + offset) or (r12 + offset).
      set_sib(times_1, rsp, base);
    }
    if (disp == 0 && base != rbp && base != r13) {
      set_modrm(0, base);
    } else if (is_int8(disp)) {
      set_modrm(1, base);
      set_disp8(disp);
    } else {
      set_modrm(2, base);
      set_disp32(disp);
    }
  }
References v8::internal::times_1.
Operand() [46/50]
v8::internal::Operand::Operand (Register base, Register index, ScaleFactor scale, int32_t disp) [inline]
Definition at line 241 of file assembler-x64.h.
                                  {
    DCHECK(index != rsp);
    set_sib(scale, index, base);
    if (disp == 0 && base != rbp && base != r13) {
      // This call to set_modrm doesn't overwrite the REX.B (or REX.X) bits
      // possibly set by set_sib.
      set_modrm(0, rsp);
    } else if (is_int8(disp)) {
      set_modrm(1, rsp);
      set_disp8(disp);
    } else {
      set_modrm(2, rsp);
      set_disp32(disp);
    }
  }
References v8::internal::DCHECK(), and v8::internal::index.
Operand() [47/50]
v8::internal::Operand::Operand (Register index, ScaleFactor scale, int32_t disp) [inline]
Definition at line 259 of file assembler-x64.h.
                                                                     {
    // The encoding generated by this constructor is longer than the
    // {register, displacement} constructor above. Hence only use this if the
    // scale factor is >1.
    // We could dynamically check this and do what the other constructor does,
    // but that adds unnecessary checks to a very commonly used constructor in
    // the Assembler, which should be as fast as possible.
    DCHECK_NE(ScaleFactor::times_1, scale);
    DCHECK(index != rsp);
    set_modrm(0, rsp);
    set_sib(scale, index, rbp);
    set_disp32(disp);
  }
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::index, and v8::internal::times_1.
Operand() [48/50]
v8::internal::Operand::Operand (Operand base, int32_t offset)
Operand() [49/50]
v8::internal::Operand::Operand (Label * label, int addend = 0) [inline], [explicit]
Definition at line 280 of file assembler-x64.h.
                                                           {
    DCHECK_NOT_NULL(label);
    DCHECK(addend == 0 || (is_int8(addend) && label->is_bound()));
    label_ = {};
    label_.label = label;
    label_.addend = addend;
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, and v8::internal::Label::is_bound().
Operand() [50/50]
v8::internal::Operand::Operand (const Operand &) [default]
Member Function Documentation
AddressUsesRegister()
bool v8::internal::Operand::AddressUsesRegister (Register reg) const
DoubleOffsetFromSmiKey()
static Operand v8::internal::Operand::DoubleOffsetFromSmiKey (Register key) [inline], [static]
Definition at line 109 of file assembler-arm.h.
                                                                {
    static_assert(kSmiTag == 0 && kSmiTagSize < kDoubleSizeLog2);
    return Operand(key, LSL, kDoubleSizeLog2 - kSmiTagSize);
  }
References v8::internal::kDoubleSizeLog2, v8::internal::key, v8::internal::kSmiTag, v8::internal::kSmiTagSize, and v8::internal::LSL.
EmbeddedHeapNumber()
static Operand v8::internal::Operand::EmbeddedHeapNumber (double number) [static]
EmbeddedNumber() [1/7]
Operand v8::internal::Operand::EmbeddedNumber (double number) [static]
Definition at line 226 of file assembler-riscv.cc.
                                            {
  int32_t smi;
  if (DoubleToSmiInteger(value, &smi)) return Operand(Smi::FromInt(smi));
  Operand result(0, RelocInfo::FULL_EMBEDDED_OBJECT);
  result.is_heap_number_request_ = true;
  result.value_.heap_number_request = HeapNumberRequest(value);
  return result;
}
References v8::internal::DoubleToSmiInteger(), v8::internal::Smi::FromInt(), v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, Operand(), v8::base::internal::result, and v8::internal::value.
Referenced by v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::MipsOperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::compiler::S390OperandConverter::InputImmediate(), v8::internal::maglev::MaglevAssembler::MoveHeapNumber(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), and v8::internal::compiler::ArmOperandConverter::ToImmediate().
EmbeddedNumber() [2/7]
static Operand v8::internal::Operand::EmbeddedNumber (double number) [static]
EmbeddedNumber() [3/7]
static Operand v8::internal::Operand::EmbeddedNumber (double number) [static]
EmbeddedNumber() [4/7]
static Operand v8::internal::Operand::EmbeddedNumber (double number) [static]
EmbeddedNumber() [5/7]
static Operand v8::internal::Operand::EmbeddedNumber (double number) [static]
EmbeddedNumber() [6/7]
static Operand v8::internal::Operand::EmbeddedNumber (double number) [static]
EmbeddedNumber() [7/7]
static Operand v8::internal::Operand::EmbeddedNumber (double value) [static]
encoded_bytes()
base::Vector<const uint8_t> v8::internal::Operand::encoded_bytes () const [inline]
Definition at line 284 of file assembler-ia32.h.
{ return {buf_, len_}; }
extend()
Extend v8::internal::Operand::extend () const [inline]
Definition at line 359 of file assembler-arm64-inl.h.
                             {
  DCHECK(IsExtendedRegister());
  return extend_;
}
References v8::internal::DCHECK(), extend_, and IsExtendedRegister().
Referenced by Operand(), and ToW().
ForRegisterPlusImmediate()
static Operand v8::internal::Operand::ForRegisterPlusImmediate (Register base, Immediate imm) [inline], [static]
Definition at line 269 of file assembler-ia32.h.
                                                                        {
    return Operand(base, imm.value_.immediate, imm.rmode_);
  }
heap_number_request() [1/7]
HeapNumberRequest v8::internal::Operand::heap_number_request () const [inline]
Definition at line 154 of file assembler-arm.h.
                                                {
    DCHECK(IsHeapNumberRequest());
    return value_.heap_number_request;
  }
References v8::internal::DCHECK().
heap_number_request() [2/7]
HeapNumberRequest v8::internal::Operand::heap_number_request () const [inline]
heap_number_request() [3/7]
HeapNumberRequest v8::internal::Operand::heap_number_request () const [inline]
Definition at line 61 of file assembler-loong64.h.
                                                {
    DCHECK(IsHeapNumberRequest());
    return value_.heap_number_request;
  }
References v8::internal::DCHECK(), v8::internal::Operand::Value::heap_number_request, IsHeapNumberRequest(), and value_.
heap_number_request() [4/7]
HeapNumberRequest v8::internal::Operand::heap_number_request () const [inline]
Definition at line 91 of file assembler-mips64.h.
                                                {
    DCHECK(IsHeapNumberRequest());
    return value_.heap_number_request;
  }
References v8::internal::DCHECK(), v8::internal::Operand::Value::heap_number_request, IsHeapNumberRequest(), and value_.
heap_number_request() [5/7]
HeapNumberRequest v8::internal::Operand::heap_number_request () const [inline]
Definition at line 99 of file assembler-ppc.h.
                                                {
    DCHECK(IsHeapNumberRequest());
    return value_.heap_number_request;
  }
References v8::internal::DCHECK().
heap_number_request() [6/7]
HeapNumberRequest v8::internal::Operand::heap_number_request () const [inline]
Definition at line 123 of file assembler-riscv.h.
                                                {
    DCHECK(IsHeapNumberRequest());
    return value_.heap_number_request;
  }
References v8::internal::DCHECK(), v8::internal::Operand::Value::heap_number_request, IsHeapNumberRequest(), and value_.
heap_number_request() [7/7]
HeapNumberRequest v8::internal::Operand::heap_number_request () const [inline]
Definition at line 106 of file assembler-s390.h.
                                                {
    DCHECK(is_heap_number_request());
    return value_.heap_number_request;
  }
References v8::internal::DCHECK().
immediate() [1/7]
int64_t v8::internal::Operand::immediate () const [inline]
Definition at line 147 of file assembler-arm.h.
                                   {
    DCHECK(IsImmediate());
    DCHECK(!IsHeapNumberRequest());
    return value_.immediate;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Assembler::bc(), v8::internal::IsZero(), Operand(), v8::internal::Assembler::pfd(), v8::internal::Assembler::prefix_form(), and v8::internal::Assembler::vx_form().
immediate() [2/7]
Immediate v8::internal::Operand::immediate () const [inline]
immediate() [3/7]
int64_t v8::internal::Operand::immediate () const [inline]
immediate() [4/7]
int64_t v8::internal::Operand::immediate () const [inline]
immediate() [5/7]
intptr_t v8::internal::Operand::immediate () const [inline]
Definition at line 92 of file assembler-ppc.h.
                                    {
    DCHECK(IsImmediate());
    DCHECK(!IsHeapNumberRequest());
    return value_.immediate;
  }
References v8::internal::DCHECK().
immediate() [6/7]
intptr_t v8::internal::Operand::immediate () const [inline]
Definition at line 115 of file assembler-riscv.h.
                                    {
    DCHECK(!is_reg());
    DCHECK(!IsHeapNumberRequest());
    return value_.immediate;
  }
References v8::internal::DCHECK(), v8::internal::Operand::Value::immediate, is_reg(), IsHeapNumberRequest(), and value_.
immediate() [7/7]
intptr_t v8::internal::Operand::immediate () const [inline]
Definition at line 100 of file assembler-s390.h.
                                    {
    DCHECK(!rm_.is_valid());
    DCHECK(!is_heap_number_request());
    return value_.immediate;
  }
References v8::internal::DCHECK().
immediate_for_heap_number_request() [1/2]
Immediate v8::internal::Operand::immediate_for_heap_number_request () const [inline]
Definition at line 329 of file assembler-arm64-inl.h.
                                                           {
  DCHECK(immediate_.rmode() == RelocInfo::FULL_EMBEDDED_OBJECT);
  return immediate_;
}
References v8::internal::DCHECK(), v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, immediate_, and v8::internal::Immediate::rmode().
immediate_for_heap_number_request() [2/2]
intptr_t v8::internal::Operand::immediate_for_heap_number_request () const [inline]
Definition at line 110 of file assembler-riscv.h.
                                                            {
    DCHECK(rmode() == RelocInfo::FULL_EMBEDDED_OBJECT);
    return value_.immediate;
  }
References v8::internal::DCHECK(), v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, v8::internal::Operand::Value::immediate, rmode(), and value_.
ImmediateRMode()
RelocInfo::Mode v8::internal::Operand::ImmediateRMode () const [inline]
Definition at line 344 of file assembler-arm64-inl.h.
                                            {
  DCHECK(IsImmediate() || IsHeapNumberRequest());
  return immediate_.rmode();
}
References v8::internal::DCHECK(), immediate_, IsHeapNumberRequest(), IsImmediate(), and v8::internal::Immediate::rmode().
ImmediateValue()
int64_t v8::internal::Operand::ImmediateValue () const [inline]
Definition at line 339 of file assembler-arm64-inl.h.
                                      {
  DCHECK(IsImmediate());
  return immediate_.value();
}
References v8::internal::DCHECK(), immediate_, IsImmediate(), and v8::internal::Immediate::value().
Referenced by v8::internal::MacroAssembler::Add(), v8::internal::MacroAssembler::Adds(), v8::internal::MacroAssembler::Ccmn(), v8::internal::MacroAssembler::Ccmp(), v8::internal::MacroAssembler::CompareAndBranch(), IsZero(), v8::internal::MacroAssembler::Neg(), v8::internal::MacroAssembler::Peek(), v8::internal::MacroAssembler::Poke(), v8::internal::MacroAssembler::Sub(), and v8::internal::MacroAssembler::Subs().
InstructionsRequired()
int v8::internal::Operand::InstructionsRequired (const Assembler * assembler, Instr instr = 0) const
is_heap_number_request()
bool v8::internal::Operand::is_heap_number_request () const [inline]
Definition at line 118 of file assembler-s390.h.
                                      {
    DCHECK_IMPLIES(is_heap_number_request_, !rm_.is_valid());
    DCHECK_IMPLIES(is_heap_number_request_,
                   rmode_ == RelocInfo::FULL_EMBEDDED_OBJECT ||
                       rmode_ == RelocInfo::CODE_TARGET);
    return is_heap_number_request_;
  }
References v8::internal::RelocInfo::CODE_TARGET, DCHECK_IMPLIES, and v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT.
is_label_operand()
constexpr bool v8::internal::Operand::is_label_operand () const [inline], [constexpr]
Definition at line 291 of file assembler-x64.h.
                                                    {
    // Since this field is in the common initial sequence of {label_} and
    // {memory_}, the access is valid regardless of the active union member.
    return memory_.is_label_operand;
  }
is_reg() [1/8]
bool v8::internal::Operand::is_reg () const [inline]
Definition at line 26 of file assembler-loong64-inl.h.
{ return rm_.is_valid(); }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), and rm_.
Referenced by immediate().
is_reg() [2/8]
bool v8::internal::Operand::is_reg () const [inline]
is_reg() [3/8]
bool v8::internal::Operand::is_reg () const [inline]
Definition at line 88 of file assembler-ppc.h.
{ return rm_.is_valid(); }
is_reg() [4/8]
bool v8::internal::Operand::is_reg () const [inline]
Definition at line 108 of file assembler-riscv.h.
{ return rm_.is_valid(); }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), and rm_.
is_reg() [5/8]
bool v8::internal::Operand::is_reg () const [inline]
Definition at line 96 of file assembler-s390.h.
{ return rm_.is_valid(); }
is_reg() [6/8]
bool v8::internal::Operand::is_reg (int reg_code) const [inline], [private]
Definition at line 306 of file assembler-ia32.h.
                                         {
    return ((buf_[0] & 0xF8) == 0xC0) // addressing mode is register only.
           && ((buf_[0] & 0x07) == reg_code); // register codes match.
  }
is_reg() [7/8]
bool v8::internal::Operand::is_reg (Register reg) const [inline]
Definition at line 274 of file assembler-ia32.h.
{ return is_reg(reg.code()); }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), and is_reg().
Referenced by v8::internal::MacroAssembler::AddOverflowWord(), v8::internal::compiler::AssembleBranchToLabels(), v8::internal::MacroAssembler::CompareTaggedAndBranch(), is_reg(), v8::internal::IsZero(), v8::internal::compiler::SignExtend(), and v8::internal::MacroAssembler::SubOverflowWord().
is_reg() [8/8]
bool v8::internal::Operand::is_reg (XMMRegister reg) const [inline]
Definition at line 275 of file assembler-ia32.h.
{ return is_reg(reg.code()); }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), and is_reg().
Referenced by is_reg().
is_reg_only()
bool v8::internal::Operand::is_reg_only () const
IsExtendedRegister()
bool v8::internal::Operand::IsExtendedRegister () const [inline]
Definition at line 299 of file assembler-arm64-inl.h.
                                       {
  return reg_.is_valid() && (extend_ != NO_EXTEND);
}
References extend_, v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::NO_EXTEND, and reg_.
Referenced by extend(), reg(), shift_amount(), and ToW().
IsHeapNumberRequest() [1/6]
bool v8::internal::Operand::IsHeapNumberRequest () const [inline]
Definition at line 158 of file assembler-arm.h.
                                   {
    DCHECK_IMPLIES(is_heap_number_request_, IsImmediate());
    DCHECK_IMPLIES(is_heap_number_request_,
                   rmode_ == RelocInfo::FULL_EMBEDDED_OBJECT ||
                       rmode_ == RelocInfo::CODE_TARGET);
    return is_heap_number_request_;
  }
References v8::internal::RelocInfo::CODE_TARGET, DCHECK_IMPLIES, and v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT.
Referenced by heap_number_request(), immediate(), and ImmediateRMode().
IsHeapNumberRequest() [2/6]
bool v8::internal::Operand::IsHeapNumberRequest () const [inline]
IsHeapNumberRequest() [3/6]
bool v8::internal::Operand::IsHeapNumberRequest () const [inline]
Definition at line 66 of file assembler-loong64.h.
                                   {
    DCHECK_IMPLIES(is_heap_number_request_, IsImmediate());
    DCHECK_IMPLIES(is_heap_number_request_,
                   rmode_ == RelocInfo::FULL_EMBEDDED_OBJECT ||
                       rmode_ == RelocInfo::CODE_TARGET);
    return is_heap_number_request_;
  }
References v8::internal::RelocInfo::CODE_TARGET, DCHECK_IMPLIES, v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, is_heap_number_request_, IsImmediate(), and rmode_.
IsHeapNumberRequest() [4/6]
bool v8::internal::Operand::IsHeapNumberRequest () const [inline]
Definition at line 96 of file assembler-mips64.h.
                                   {
    DCHECK_IMPLIES(is_heap_number_request_, IsImmediate());
    DCHECK_IMPLIES(is_heap_number_request_,
                   rmode_ == RelocInfo::FULL_EMBEDDED_OBJECT ||
                       rmode_ == RelocInfo::CODE_TARGET);
    return is_heap_number_request_;
  }
References v8::internal::RelocInfo::CODE_TARGET, DCHECK_IMPLIES, v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, is_heap_number_request_, IsImmediate(), and rmode_.
IsHeapNumberRequest() [5/6]
bool v8::internal::Operand::IsHeapNumberRequest () const [inline]
Definition at line 106 of file assembler-ppc.h.
                                   {
    DCHECK_IMPLIES(is_heap_number_request_, IsImmediate());
    DCHECK_IMPLIES(is_heap_number_request_,
                   rmode_ == RelocInfo::FULL_EMBEDDED_OBJECT ||
                       rmode_ == RelocInfo::CODE_TARGET);
    return is_heap_number_request_;
  }
References v8::internal::RelocInfo::CODE_TARGET, DCHECK_IMPLIES, and v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT.
IsHeapNumberRequest() [6/6]
bool v8::internal::Operand::IsHeapNumberRequest () const [inline]
Definition at line 128 of file assembler-riscv.h.
                                   {
    DCHECK_IMPLIES(is_heap_number_request_, IsImmediate());
    DCHECK_IMPLIES(is_heap_number_request_,
                   rmode_ == RelocInfo::FULL_EMBEDDED_OBJECT ||
                       rmode_ == RelocInfo::CODE_TARGET);
    return is_heap_number_request_;
  }
References v8::internal::RelocInfo::CODE_TARGET, DCHECK_IMPLIES, v8::internal::RelocInfo::FULL_EMBEDDED_OBJECT, is_heap_number_request_, IsImmediate(), and rmode_.
IsImmediate() [1/6]
bool v8::internal::Operand::IsImmediate () const [inline]
Definition at line 152 of file assembler-arm.h.
{ return !rm_.is_valid(); }
Referenced by v8::internal::MacroAssembler::Add(), v8::internal::MacroAssembler::Adds(), v8::internal::MacroAssembler::Ccmn(), v8::internal::MacroAssembler::Ccmp(), v8::internal::MacroAssembler::CompareAndBranch(), ImmediateRMode(), ImmediateValue(), IsHeapNumberRequest(), IsZero(), v8::internal::MacroAssembler::MoveObjectAndSlot(), v8::internal::MacroAssembler::Neg(), v8::internal::MacroAssembler::Peek(), v8::internal::MacroAssembler::Poke(), v8::internal::MacroAssembler::RecordWrite(), v8::internal::MacroAssembler::Sub(), v8::internal::MacroAssembler::Subs(), and ToW().
IsImmediate() [2/6]
bool v8::internal::Operand::IsImmediate () const [inline]
IsImmediate() [3/6]
bool v8::internal::Operand::IsImmediate () const [inline]
Definition at line 59 of file assembler-loong64.h.
{ return !rm_.is_valid(); }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), and rm_.
IsImmediate() [4/6]
bool v8::internal::Operand::IsImmediate () const [inline]
Definition at line 89 of file assembler-mips64.h.
{ return !rm_.is_valid(); }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), and rm_.
IsImmediate() [5/6]
bool v8::internal::Operand::IsImmediate () const [inline]
Definition at line 97 of file assembler-ppc.h.
{ return !rm_.is_valid(); }
IsImmediate() [6/6]
bool v8::internal::Operand::IsImmediate () const [inline]
Definition at line 121 of file assembler-riscv.h.
{ return !rm_.is_valid(); }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), and rm_.
IsImmediateShiftedRegister()
bool v8::internal::Operand::IsImmediateShiftedRegister () const [inline]
Definition at line 125 of file assembler-arm.h.
                                          {
    return rm_.is_valid() && !rs_.is_valid();
  }
IsRegister()
bool v8::internal::Operand::IsRegister () const [inline]
Definition at line 120 of file assembler-arm.h.
                          {
    return rm_.is_valid() && rs_ == no_reg && shift_op_ == LSL &&
           shift_imm_ == 0;
  }
References v8::internal::LSL, and v8::internal::no_reg.
Referenced by v8::internal::MacroAssembler::Move().
IsRegisterShiftedRegister()
bool v8::internal::Operand::IsRegisterShiftedRegister () const [inline]
Definition at line 129 of file assembler-arm.h.
                                         {
    return rm_.is_valid() && rs_.is_valid();
  }
IsShiftedRegister()
bool v8::internal::Operand::IsShiftedRegister () const [inline]
Definition at line 295 of file assembler-arm64-inl.h.
                                      {
  return reg_.is_valid() && (shift_ != NO_SHIFT);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::NO_SHIFT, reg_, and shift_.
Referenced by v8::internal::MacroAssembler::Add(), v8::internal::MacroAssembler::Cmp(), reg(), shift(), shift_amount(), v8::internal::MacroAssembler::Sub(), ToExtendedRegister(), and ToW().
IsZero()
bool v8::internal::Operand::IsZero () const [inline]
Definition at line 303 of file assembler-arm64-inl.h.
                           {
  if (IsImmediate()) {
    return ImmediateValue() == 0;
  } else {
    return reg().IsZero();
  }
}
References ImmediateValue(), IsImmediate(), v8::internal::CPURegister::IsZero(), and reg().
JumpTable()
static Operand v8::internal::Operand::JumpTable (Register index, ScaleFactor scale, Label * table) [inline], [static]
Definition at line 264 of file assembler-ia32.h.
                                                                            {
    return Operand(index, scale, reinterpret_cast<int32_t>(table),
                   RelocInfo::INTERNAL_REFERENCE);
  }
References v8::internal::index, and v8::internal::RelocInfo::INTERNAL_REFERENCE.
label()
const LabelOperand& v8::internal::Operand::label () const [inline]
Definition at line 310 of file assembler-x64.h.
                                              {
    DCHECK(is_label_operand());
    return label_;
  }
References v8::internal::DCHECK().
memory()
const MemoryOperand& v8::internal::Operand::memory () const [inline]
Definition at line 305 of file assembler-x64.h.
                                                {
    DCHECK(!is_label_operand());
    return memory_;
  }
References v8::internal::DCHECK().
must_output_reloc_info() [1/2]
bool v8::internal::Operand::must_output_reloc_info (const Assembler * assembler) const
must_output_reloc_info() [2/2]
bool v8::internal::Operand::must_output_reloc_info (const Assembler * assembler) const
MustOutputRelocInfo()
bool v8::internal::Operand::MustOutputRelocInfo (const Assembler * assembler) const
NeedsRelocation()
bool v8::internal::Operand::NeedsRelocation (const Assembler * assembler) const
operator=()
Operand& v8::internal::Operand::operator= (const Operand &) [default]
PointerOffsetFromSmiKey()
static Operand v8::internal::Operand::PointerOffsetFromSmiKey (Register key) [inline], [static]
Definition at line 105 of file assembler-arm.h.
                                                                 {
    static_assert(kSmiTag == 0 && kSmiTagSize < kPointerSizeLog2);
    return Operand(key, LSL, kPointerSizeLog2 - kSmiTagSize);
  }
References v8::internal::key, v8::internal::kPointerSizeLog2, v8::internal::kSmiTag, v8::internal::kSmiTagSize, and v8::internal::LSL.
reg() [1/2]
Register v8::internal::Operand::reg () const [inline]
Definition at line 349 of file assembler-arm64-inl.h.
                            {
  DCHECK(IsShiftedRegister() || IsExtendedRegister());
  return reg_;
}
References v8::internal::DCHECK(), IsExtendedRegister(), IsShiftedRegister(), and reg_.
Referenced by v8::internal::MacroAssembler::Add(), v8::internal::MacroAssembler::Cmp(), IsZero(), Operand(), and v8::internal::MacroAssembler::Sub().
reg() [2/2]
Register v8::internal::Operand::reg () const
rex()
constexpr uint8_t v8::internal::Operand::rex () const [inline], [constexpr]
Definition at line 297 of file assembler-x64.h.
                                          {
    // Since both fields are in the common initial sequence of {label_} and
    // {memory_}, the access is valid regardless of the active union member.
    // Label operands always have a REX prefix of zero.
    V8_ASSUME(!memory_.is_label_operand || memory_.rex == 0);
    return memory_.rex;
  }
References V8_ASSUME.
Referenced by v8::internal::Assembler::emit_optional_rex_32(), v8::internal::Assembler::emit_rex_32(), v8::internal::Assembler::emit_rex_64(), v8::internal::Assembler::emit_vex3_byte1(), and v8::internal::Assembler::emit_vex_prefix().
rm() [1/6]
Register v8::internal::Operand::rm () const [inline]
Definition at line 166 of file assembler-arm.h.
{ return rm_; }
Referenced by v8::internal::MacroAssembler::AddOverflowWord(), v8::internal::MacroAssembler::CompareTaggedAndBranch(), v8::internal::IsZero(), v8::internal::MacroAssembler::Move(), v8::internal::MacroAssembler::MoveObjectAndSlot(), v8::internal::compiler::SignExtend(), and v8::internal::MacroAssembler::SubOverflowWord().
rm() [2/6]
Register v8::internal::Operand::rm () const [inline]
Definition at line 74 of file assembler-loong64.h.
{ return rm_; }
References rm_.
rm() [3/6]
Register v8::internal::Operand::rm () const [inline]
Definition at line 104 of file assembler-mips64.h.
{ return rm_; }
References rm_.
rm() [4/6]
Register v8::internal::Operand::rm () const [inline]
Definition at line 104 of file assembler-ppc.h.
{ return rm_; }
rm() [5/6]
Register v8::internal::Operand::rm () const [inline]
Definition at line 136 of file assembler-riscv.h.
{ return rm_; }
References rm_.
rm() [6/6]
Register v8::internal::Operand::rm () const [inline]
Definition at line 116 of file assembler-s390.h.
{ return rm_; }
rmode() [1/5]
RelocInfo::Mode v8::internal::Operand::rmode () [inline]
Definition at line 285 of file assembler-ia32.h.
{ return rmode_; }
Referenced by immediate_for_heap_number_request(), and Operand().
rmode() [2/5]
RelocInfo::Mode v8::internal::Operand::rmode () const [inline]
Definition at line 76 of file assembler-loong64.h.
{ return rmode_; }
References rmode_.
rmode() [3/5]
RelocInfo::Mode v8::internal::Operand::rmode () const [inline]
Definition at line 106 of file assembler-mips64.h.
{ return rmode_; }
References rmode_.
rmode() [4/5]
RelocInfo::Mode v8::internal::Operand::rmode () const [inline]
Definition at line 138 of file assembler-riscv.h.
{ return rmode_; }
References rmode_.
rmode() [5/5]
RelocInfo::Mode v8::internal::Operand::rmode () const [inline]
Definition at line 126 of file assembler-s390.h.
{ return rmode_; }
rs()
Register v8::internal::Operand::rs () const [inline]
Definition at line 167 of file assembler-arm.h.
{ return rs_; }
set_disp32()
void v8::internal::Operand::set_disp32 (int disp) [inline], [private]
Definition at line 347 of file assembler-x64.h.
                                      {
    V8_ASSUME(memory_.len == 1 || memory_.len == 2);
    Address p = reinterpret_cast<Address>(&memory_.buf[memory_.len]);
    WriteUnalignedValue(p, disp);
    memory_.len += sizeof(int32_t);
  }
References V8_ASSUME, and v8::base::WriteUnalignedValue().
set_disp8() [1/2]
constexpr void v8::internal::Operand::set_disp8 (int disp) [inline], [constexpr], [private]
Definition at line 340 of file assembler-x64.h.
                                               {
    V8_ASSUME(memory_.len == 1 || memory_.len == 2);
    DCHECK(is_int8(disp));
    memory_.buf[memory_.len] = disp;
    memory_.len += sizeof(int8_t);
  }
References v8::internal::DCHECK(), and V8_ASSUME.
set_disp8() [2/2]
void v8::internal::Operand::set_disp8 (int8_t disp) [inline], [private]
Definition at line 298 of file assembler-ia32-inl.h.
                                   {
  DCHECK(len_ == 1 || len_ == 2);
  *reinterpret_cast<int8_t*>(&buf_[len_++]) = disp;
}
References buf_, v8::internal::DCHECK(), and len_.
set_dispr()
void v8::internal::Operand::set_dispr (int32_t disp, RelocInfo::Mode rmode) [inline], [private]
Definition at line 298 of file assembler-ia32.h.
                                                           {
    DCHECK(len_ == 1 || len_ == 2);
    Address p = reinterpret_cast<Address>(&buf_[len_]);
    WriteUnalignedValue(p, disp);
    len_ += sizeof(int32_t);
    rmode_ = rmode;
  }
References v8::internal::DCHECK(), and v8::base::WriteUnalignedValue().
set_modrm() [1/2]
void v8::internal::Operand::set_modrm (int mod, Register rm) [inline], [private]
Definition at line 290 of file assembler-ia32.h.
                                              {
    DCHECK_EQ(mod & -4, 0);
    buf_[0] = mod << 6 | rm.code();
    len_ = 1;
  }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), and DCHECK_EQ.
set_modrm() [2/2]
constexpr void v8::internal::Operand::set_modrm (int mod, Register rm_reg) [inline], [constexpr], [private]
Definition at line 320 of file assembler-x64.h.
                                                               {
    DCHECK(!is_label_operand());
    DCHECK(is_uint2(mod));
    memory_.buf[0] = mod << 6 | rm_reg.low_bits();
    // Set REX.B to the high bit of rm.code().
    memory_.rex |= rm_reg.high_bit();
  }
References v8::internal::DCHECK(), v8::internal::Register::high_bit(), and v8::internal::Register::low_bits().
set_sib() [1/2]
void v8::internal::Operand::set_sib (ScaleFactor scale, Register index, Register base) [inline], [private]
Definition at line 289 of file assembler-ia32-inl.h.
                                                                      {
  DCHECK_EQ(len_, 1);
  DCHECK_EQ(scale & -4, 0);
  // Use SIB with no index register only for base esp.
  DCHECK(index != esp || base == esp);
  buf_[1] = scale << 6 | index.code() << 3 | base.code();
  len_ = 2;
}
References buf_, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::index, and len_.
set_sib() [2/2]
constexpr void v8::internal::Operand::set_sib (ScaleFactor scale, Register index, Register base) [inline], [constexpr], [private]
Definition at line 328 of file assembler-x64.h.
                                                  {
    V8_ASSUME(memory_.len == 1);
    DCHECK(is_uint2(scale));
    // Use SIB with no index register only for base rsp or r12. Otherwise we
    // would skip the SIB byte entirely.
    DCHECK(index != rsp || base == rsp || base == r12);
    memory_.buf[1] = (scale << 6) | (index.low_bits() << 3) | base.low_bits();
    memory_.rex |= index.high_bit() << 1 | base.high_bit();
    memory_.len = 2;
  }
References v8::internal::DCHECK(), v8::internal::Register::high_bit(), v8::internal::index, v8::internal::Register::low_bits(), and V8_ASSUME.
setBits()
void v8::internal::Operand::setBits (int n) [inline]
Definition at line 111 of file assembler-s390.h.
                             {
    value_.immediate =
        (static_cast<uint32_t>(value_.immediate) << (32 - n)) >> (32 - n);
  }
shift()
Shift v8::internal::Operand::shift () const [inline]
Definition at line 354 of file assembler-arm64-inl.h.
                           {
  DCHECK(IsShiftedRegister());
  return shift_;
}
References v8::internal::DCHECK(), IsShiftedRegister(), and shift_.
Referenced by ToW().
shift_amount()
unsigned v8::internal::Operand::shift_amount () const [inline]
Definition at line 364 of file assembler-arm64-inl.h.
                                     {
  DCHECK(IsShiftedRegister() || IsExtendedRegister());
  return shift_amount_;
}
References v8::internal::DCHECK(), IsExtendedRegister(), IsShiftedRegister(), and shift_amount_.
Referenced by v8::internal::MacroAssembler::Add(), v8::internal::MacroAssembler::Cmp(), Operand(), v8::internal::MacroAssembler::Sub(), and ToW().
shift_op()
ShiftOp v8::internal::Operand::shift_op () const [inline]
Definition at line 168 of file assembler-arm.h.
{ return shift_op_; }
SmiUntag()
static Operand v8::internal::Operand::SmiUntag (Register rm) [inline], [static]
Definition at line 102 of file assembler-arm.h.
                                                 {
    return Operand(rm, ASR, kSmiTagSize);
  }
References v8::internal::ASR, and v8::internal::kSmiTagSize.
Referenced by v8::internal::MacroAssembler::SmiUntag().
ToExtendedRegister()
Operand v8::internal::Operand::ToExtendedRegister () const [inline]
Definition at line 311 of file assembler-arm64-inl.h.
                                          {
  DCHECK(IsShiftedRegister());
  DCHECK((shift_ == LSL) && (shift_amount_ <= 4));
  return Operand(reg_, reg_.Is64Bits() ? UXTX : UXTW, shift_amount_);
}
References v8::internal::DCHECK(), v8::internal::CPURegister::Is64Bits(), IsShiftedRegister(), v8::internal::LSL, Operand(), reg_, shift_, shift_amount_, v8::internal::UXTW, and v8::internal::UXTX.
ToW()
Operand v8::internal::Operand::ToW () const [inline]
Definition at line 317 of file assembler-arm64-inl.h.
                           {
  if (IsShiftedRegister()) {
    DCHECK(reg_.Is64Bits());
    return Operand(reg_.W(), shift(), shift_amount());
  } else if (IsExtendedRegister()) {
    DCHECK(reg_.Is64Bits());
    return Operand(reg_.W(), extend(), shift_amount());
  }
  DCHECK(IsImmediate());
  return *this;
}
References v8::internal::DCHECK(), extend(), v8::internal::CPURegister::Is64Bits(), IsExtendedRegister(), IsImmediate(), IsShiftedRegister(), Operand(), reg_, shift(), shift_amount(), and v8::internal::CPURegister::W().
Referenced by v8::internal::MacroAssembler::CcmpTagged(), v8::internal::MacroAssembler::CmpTagged(), and v8::internal::MacroAssembler::CompareTaggedAndBranch().
Zero() [1/3]
Operand v8::internal::Operand::Zero () [inline], [static]
Definition at line 171 of file assembler-arm-inl.h.
{ return Operand(static_cast<int32_t>(0)); }
References Operand().
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction().
Zero() [2/3]
static Operand v8::internal::Operand::Zero () [inline], [static]
Definition at line 73 of file assembler-ppc.h.
{ return Operand(static_cast<intptr_t>(0)); }
Zero() [3/3]
static Operand v8::internal::Operand::Zero () [inline], [static]
Definition at line 80 of file assembler-s390.h.
{ return Operand(static_cast<intptr_t>(0)); }
Friends And Related Function Documentation
Assembler
Assembler [friend]
Definition at line 183 of file assembler-arm.h.
MacroAssembler
MacroAssembler [friend]
Definition at line 89 of file assembler-loong64.h.
Member Data Documentation
union { ... } [private]
buf_
uint8_t v8::internal::Operand::buf_[6] [private]
Definition at line 311 of file assembler-ia32.h.
Referenced by set_disp8(), and set_sib().
extend_
Extend v8::internal::Operand::extend_ [private]
Definition at line 129 of file assembler-arm64.h.
Referenced by extend(), and IsExtendedRegister().
heap_number_request_
std::optional<HeapNumberRequest> v8::internal::Operand::heap_number_request_ [private]
Definition at line 125 of file assembler-arm64.h.
immediate_
Immediate v8::internal::Operand::immediate_ [private]
Definition at line 126 of file assembler-arm64.h.
Referenced by immediate_for_heap_number_request(), ImmediateRMode(), and ImmediateValue().
is_heap_number_request_
bool v8::internal::Operand::is_heap_number_request_ = false [private]
Definition at line 180 of file assembler-arm.h.
Referenced by IsHeapNumberRequest().
label_
LabelOperand v8::internal::Operand::label_
Definition at line 355 of file assembler-x64.h.
len_
uint8_t v8::internal::Operand::len_ = 0 [private]
Definition at line 313 of file assembler-ia32.h.
Referenced by set_disp8(), and set_sib().
memory_
MemoryOperand v8::internal::Operand::memory_ = {}
Definition at line 356 of file assembler-x64.h.
reg_
Register v8::internal::Operand::reg_ [private]
Definition at line 127 of file assembler-arm64.h.
Referenced by IsExtendedRegister(), IsShiftedRegister(), reg(), ToExtendedRegister(), and ToW().
rm_
Register v8::internal::Operand::rm_ = no_reg [private]
Definition at line 171 of file assembler-arm.h.
Referenced by is_reg(), IsImmediate(), and rm().
rmode_
RelocInfo::Mode v8::internal::Operand::rmode_ = RelocInfo::NO_INFO [private]
Definition at line 181 of file assembler-arm.h.
Referenced by IsHeapNumberRequest(), and rmode().
rs_
Register v8::internal::Operand::rs_ = no_reg [private]
Definition at line 172 of file assembler-arm.h.
shift_
Shift v8::internal::Operand::shift_ [private]
Definition at line 128 of file assembler-arm64.h.
Referenced by IsShiftedRegister(), shift(), and ToExtendedRegister().
shift_amount_
unsigned v8::internal::Operand::shift_amount_ [private]
Definition at line 130 of file assembler-arm64.h.
Referenced by shift_amount(), and ToExtendedRegister().
shift_imm_
int v8::internal::Operand::shift_imm_ [private]
Definition at line 174 of file assembler-arm.h.
shift_op_
ShiftOp v8::internal::Operand::shift_op_ [private]
Definition at line 173 of file assembler-arm.h.
value_
union v8::internal::Operand::Value v8::internal::Operand::value_ [private]
Referenced by heap_number_request(), immediate(), immediate_for_heap_number_request(), and Operand().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/arm/assembler-arm.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64.h
/mnt/V8SourceCode/src/codegen/ia32/assembler-ia32.h
/mnt/V8SourceCode/src/codegen/loong64/assembler-loong64.h
/mnt/V8SourceCode/src/codegen/mips64/assembler-mips64.h
/mnt/V8SourceCode/src/codegen/ppc/assembler-ppc.h
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv.h
/mnt/V8SourceCode/src/codegen/s390/assembler-s390.h
/mnt/V8SourceCode/src/codegen/x64/assembler-x64.h
/mnt/V8SourceCode/src/codegen/arm/assembler-arm-inl.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64-inl.h
/mnt/V8SourceCode/src/codegen/ia32/assembler-ia32-inl.h
/mnt/V8SourceCode/src/codegen/loong64/assembler-loong64-inl.h
/mnt/V8SourceCode/src/codegen/mips64/assembler-mips64-inl.h
/mnt/V8SourceCode/src/codegen/ppc/assembler-ppc-inl.h
/mnt/V8SourceCode/src/codegen/riscv/assembler-riscv.cc
/mnt/V8SourceCode/src/codegen/s390/assembler-s390-inl.h