v8::internal::MaglevSafepointTable Class Reference
#include <maglev-safepoint-table.h>
Public Member Functions
MaglevSafepointTable (Isolate *isolate, Address pc, Tagged< Code > code)
MaglevSafepointTable (const MaglevSafepointTable &)=delete
MaglevSafepointTable & operator= (const MaglevSafepointTable &)=delete
int length () const
int byte_size () const
int find_return_pc (int pc_offset)
uint32_t stack_slots ()
MaglevSafepointEntry GetEntry (int index) const
MaglevSafepointEntry FindEntry (Address pc) const
void Print (std::ostream &) const
Static Public Member Functions
static MaglevSafepointEntry FindEntry (Isolate *isolate, Tagged< GcSafeCode > code, Address pc)
Private Types
using HasDeoptDataField = base::BitField< bool, 0, 1 >
using RegisterIndexesSizeField = HasDeoptDataField::Next< int, 3 >
using PcSizeField = RegisterIndexesSizeField::Next< int, 3 >
using DeoptIndexSizeField = PcSizeField::Next< int, 3 >
Private Member Functions
MaglevSafepointTable (Isolate *isolate, Address pc, Tagged< GcSafeCode > code)
MaglevSafepointTable (Address instruction_start, Address safepoint_table_address)
int entry_size () const
bool has_deopt_data () const
int pc_size () const
int deopt_index_size () const
int register_indexes_size () const
Static Private Member Functions
static int read_bytes (Address *ptr, int bytes)
static uint8_t read_byte (Address *ptr)
Private Attributes
const Address instruction_start_
const Address safepoint_table_address_
const SafepointTableStackSlotsField_t stack_slots_
const int length_
const uint32_t entry_configuration_
const uint32_t num_tagged_slots_
Friends
class MaglevSafepointTableBuilder
class MaglevSafepointEntry
Detailed Description
Definition at line 60 of file maglev-safepoint-table.h.
Member Typedef Documentation
DeoptIndexSizeField
using v8::internal::MaglevSafepointTable::DeoptIndexSizeField = PcSizeField::Next<int, 3> [private]
Definition at line 133 of file maglev-safepoint-table.h.
HasDeoptDataField
using v8::internal::MaglevSafepointTable::HasDeoptDataField = base::BitField<bool, 0, 1> [private]
Definition at line 130 of file maglev-safepoint-table.h.
PcSizeField
using v8::internal::MaglevSafepointTable::PcSizeField = RegisterIndexesSizeField::Next<int, 3> [private]
Definition at line 132 of file maglev-safepoint-table.h.
RegisterIndexesSizeField
using v8::internal::MaglevSafepointTable::RegisterIndexesSizeField = HasDeoptDataField::Next<int, 3> [private]
Definition at line 131 of file maglev-safepoint-table.h.
Constructor & Destructor Documentation
MaglevSafepointTable() [1/4]
v8::internal::MaglevSafepointTable::MaglevSafepointTable (Isolate * isolate, Address pc, Tagged< Code > code) [explicit]
Definition at line 15 of file maglev-safepoint-table.cc.
    : MaglevSafepointTable(code->InstructionStart(isolate, pc),
                           code->safepoint_table_address()) {
  DCHECK(code->is_maglevved());
}
References code, and v8::internal::DCHECK().
MaglevSafepointTable() [2/4]
v8::internal::MaglevSafepointTable::MaglevSafepointTable (const MaglevSafepointTable &) [delete]
MaglevSafepointTable() [3/4]
v8::internal::MaglevSafepointTable::MaglevSafepointTable (Isolate * isolate, Address pc, Tagged< GcSafeCode > code) [private]
Definition at line 22 of file maglev-safepoint-table.cc.
    : MaglevSafepointTable(code->InstructionStart(isolate, pc),
                           code->safepoint_table_address()) {
  DCHECK(code->is_maglevved());
}
References code, and v8::internal::DCHECK().
MaglevSafepointTable() [4/4]
v8::internal::MaglevSafepointTable::MaglevSafepointTable (Address instruction_start, Address safepoint_table_address) [private]
Definition at line 29 of file maglev-safepoint-table.cc.
    : instruction_start_(instruction_start),
      safepoint_table_address_(safepoint_table_address),
      stack_slots_(base::Memory<SafepointTableStackSlotsField_t>(
          safepoint_table_address + kStackSlotsOffset)),
      length_(base::Memory<int>(safepoint_table_address + kLengthOffset)),
      entry_configuration_(base::Memory<uint32_t>(safepoint_table_address +
                                                  kEntryConfigurationOffset)),
      num_tagged_slots_(base::Memory<uint32_t>(safepoint_table_address +
                                               kNumTaggedSlotsOffset)) {}
Member Function Documentation
byte_size()
int v8::internal::MaglevSafepointTable::byte_size () const [inline]
Definition at line 71 of file maglev-safepoint-table.h.
{ return kHeaderSize + length_ * entry_size(); }
References entry_size(), and length_.
Referenced by Print().
deopt_index_size()
int v8::internal::MaglevSafepointTable::deopt_index_size () const [inline], [private]
Definition at line 149 of file maglev-safepoint-table.h.
                      { return PcSizeField::decode(entry_configuration_); }
  int deopt_index_size() const {
    return DeoptIndexSizeField::decode(entry_configuration_);
References v8::base::BitField< T, shift, size, U >::decode(), and entry_configuration_.
Referenced by entry_size(), and GetEntry().
entry_size()
int v8::internal::MaglevSafepointTable::entry_size () const [inline], [private]
Definition at line 138 of file maglev-safepoint-table.h.
                         {
    int deopt_data_size = has_deopt_data() ? pc_size() + deopt_index_size() : 0;
    const int num_pushed_registers_size = 1;
    return pc_size() + deopt_data_size + num_pushed_registers_size +
           register_indexes_size();
References deopt_index_size(), has_deopt_data(), pc_size(), and register_indexes_size().
Referenced by byte_size(), and GetEntry().
find_return_pc()
int v8::internal::MaglevSafepointTable::find_return_pc (int pc_offset)
Definition at line 41 of file maglev-safepoint-table.cc.
                                                      {
  for (int i = 0; i < length(); i++) {
    MaglevSafepointEntry entry = GetEntry(i);
    if (entry.trampoline_pc() == pc_offset || entry.pc() == pc_offset) {
      return entry.pc();
    }
  }
  UNREACHABLE();
}
References GetEntry(), length(), v8::internal::SafepointEntryBase::pc(), v8::internal::SafepointEntryBase::trampoline_pc(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::MaglevFrame::FindReturnPCForTrampoline().
FindEntry() [1/2]
MaglevSafepointEntry v8::internal::MaglevSafepointTable::FindEntry (Address pc) const
Definition at line 51 of file maglev-safepoint-table.cc.
                                                                     {
  int pc_offset = static_cast<int>(pc - instruction_start_);
  // Check if the PC is pointing at a trampoline.
  if (has_deopt_data()) {
    for (int i = 0; i < length_; ++i) {
      MaglevSafepointEntry entry = GetEntry(i);
      int trampoline_pc = GetEntry(i).trampoline_pc();
      if (trampoline_pc != -1 && trampoline_pc == pc_offset) return entry;
      if (trampoline_pc > pc_offset) break;
    }
  }
  // Try to find an exact pc match.
  for (int i = 0; i < length_; ++i) {
    MaglevSafepointEntry entry = GetEntry(i);
    if (entry.pc() == pc_offset) {
      return entry;
    }
  }
  // Return a default entry which has no deopt data and no pushed registers.
  // This allows us to elide emitting entries for trivial calls.
  int deopt_index = MaglevSafepointEntry::kNoDeoptIndex;
  int trampoline_pc = MaglevSafepointEntry::kNoTrampolinePC;
  uint8_t num_extra_spill_slots = 0;
  int tagged_register_indexes = 0;
  return MaglevSafepointEntry(pc_offset, deopt_index, num_tagged_slots_,
                              num_extra_spill_slots, tagged_register_indexes,
                              trampoline_pc);
}
References GetEntry(), has_deopt_data(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, instruction_start_, v8::internal::MaglevSafepointEntry::kNoDeoptIndex, v8::internal::MaglevSafepointEntry::kNoTrampolinePC, length_, MaglevSafepointEntry, num_tagged_slots_, v8::internal::SafepointEntryBase::pc(), and v8::internal::SafepointEntryBase::trampoline_pc().
Referenced by v8::internal::Deoptimizer::ComputeInputFrameSize(), v8::internal::Deoptimizer::DeoptimizeMarkedCode(), FindEntry(), v8::internal::Code::GetMaglevSafepointEntry(), v8::internal::anonymous_namespace{frames.cc}::GetMaglevSafepointEntryFromCodeCache(), and v8::internal::anonymous_namespace{deoptimizer.cc}::ActivationsFinder::VisitThread().
FindEntry() [2/2]
MaglevSafepointEntry v8::internal::MaglevSafepointTable::FindEntry (Isolate * isolate, Tagged< GcSafeCode > code, Address pc) [static]
Definition at line 85 of file maglev-safepoint-table.cc.
                                                                 {
  MaglevSafepointTable table(isolate, pc, code);
  return table.FindEntry(pc);
}
References code, and FindEntry().
GetEntry()
MaglevSafepointEntry v8::internal::MaglevSafepointTable::GetEntry (int index) const [inline]
Definition at line 77 of file maglev-safepoint-table.h.
                                                 {
    DCHECK_GT(length_, index);
    Address entry_ptr =
        safepoint_table_address_ + kHeaderSize + index * entry_size();
    int pc = read_bytes(&entry_ptr, pc_size());
    int deopt_index = MaglevSafepointEntry::kNoDeoptIndex;
    int trampoline_pc = MaglevSafepointEntry::kNoTrampolinePC;
    if (has_deopt_data()) {
      static_assert(MaglevSafepointEntry::kNoDeoptIndex == -1);
      static_assert(MaglevSafepointEntry::kNoTrampolinePC == -1);
      // `-1` to restore the original value, see also
      // MaglevSafepointTableBuilder::Emit.
      deopt_index = read_bytes(&entry_ptr, deopt_index_size()) - 1;
      trampoline_pc = read_bytes(&entry_ptr, pc_size()) - 1;
      DCHECK(deopt_index >= 0 ||
             deopt_index == MaglevSafepointEntry::kNoDeoptIndex);
      DCHECK(trampoline_pc >= 0 ||
             trampoline_pc == MaglevSafepointEntry::kNoTrampolinePC);
    }
    uint8_t num_extra_spill_slots = read_byte(&entry_ptr);
    int tagged_register_indexes =
        read_bytes(&entry_ptr, register_indexes_size());
    return MaglevSafepointEntry(pc, deopt_index, num_tagged_slots_,
                                num_extra_spill_slots, tagged_register_indexes,
                                trampoline_pc);
  }
References v8::internal::DCHECK(), DCHECK_GT, deopt_index_size(), entry_size(), has_deopt_data(), v8::internal::index, v8::internal::MaglevSafepointEntry::kNoDeoptIndex, v8::internal::MaglevSafepointEntry::kNoTrampolinePC, length_, MaglevSafepointEntry, num_tagged_slots_, pc_size(), read_byte(), read_bytes(), register_indexes_size(), and safepoint_table_address_.
Referenced by find_return_pc(), FindEntry(), and Print().
has_deopt_data()
bool v8::internal::MaglevSafepointTable::has_deopt_data () const [inline], [private]
Definition at line 145 of file maglev-safepoint-table.h.
                              {
    return HasDeoptDataField::decode(entry_configuration_);
References v8::base::BitField< T, shift, size, U >::decode(), and entry_configuration_.
Referenced by entry_size(), FindEntry(), and GetEntry().
length()
int v8::internal::MaglevSafepointTable::length () const [inline]
Definition at line 69 of file maglev-safepoint-table.h.
{ return length_; }
References length_.
Referenced by find_return_pc().
operator=()
MaglevSafepointTable& v8::internal::MaglevSafepointTable::operator= (const MaglevSafepointTable &) [delete]
pc_size()
int v8::internal::MaglevSafepointTable::pc_size () const [inline], [private]
Definition at line 148 of file maglev-safepoint-table.h.
{ return PcSizeField::decode(entry_configuration_); }
Referenced by entry_size(), and GetEntry().
Print()
void v8::internal::MaglevSafepointTable::Print (std::ostream & os) const
Definition at line 92 of file maglev-safepoint-table.cc.
                                                     {
  os << "Safepoints (stack slots = " << stack_slots_
     << ", entries = " << length_ << ", byte size = " << byte_size()
     << ", tagged slots = " << num_tagged_slots_ << ")\n";
  for (int index = 0; index < length_; index++) {
    MaglevSafepointEntry entry = GetEntry(index);
    os << reinterpret_cast<const void*>(instruction_start_ + entry.pc()) << " "
       << std::setw(6) << std::hex << entry.pc() << std::dec;
    os << " num extra spill slots: "
       << static_cast<int>(entry.num_extra_spill_slots());
    if (entry.tagged_register_indexes() != 0) {
      os << " registers: ";
      uint32_t register_bits = entry.tagged_register_indexes();
      int bits = 32 - base::bits::CountLeadingZeros32(register_bits);
      for (int j = bits - 1; j >= 0; --j) {
        os << ((register_bits >> j) & 1);
      }
    }
    if (entry.has_deoptimization_index()) {
      os << " deopt " << std::setw(6) << entry.deoptimization_index()
         << " trampoline: " << std::setw(6) << std::hex
         << entry.trampoline_pc();
    }
    os << "\n";
  }
}
References byte_size(), v8::base::bits::CountLeadingZeros32(), v8::internal::SafepointEntryBase::deoptimization_index(), GetEntry(), v8::internal::SafepointEntryBase::has_deoptimization_index(), v8::internal::index, instruction_start_, length_, v8::internal::MaglevSafepointEntry::num_extra_spill_slots(), num_tagged_slots_, v8::internal::SafepointEntryBase::pc(), stack_slots_, v8::internal::MaglevSafepointEntry::tagged_register_indexes(), and v8::internal::SafepointEntryBase::trampoline_pc().
read_byte()
static uint8_t v8::internal::MaglevSafepointTable::read_byte (Address * ptr) [inline], [static], [private]
Definition at line 164 of file maglev-safepoint-table.h.
                                         {
    uint8_t result = *reinterpret_cast<uint8_t*>(*ptr);
    ++*ptr;
    return result;
References v8::base::internal::result.
Referenced by GetEntry(), and read_bytes().
read_bytes()
static int v8::internal::MaglevSafepointTable::read_bytes (Address * ptr, int bytes) [inline], [static], [private]
Definition at line 156 of file maglev-safepoint-table.h.
                                                 {
    uint32_t result = 0;
    for (int b = 0; b < bytes; ++b) {
      result |= uint32_t{read_byte(ptr)} << (8 * b);
    }
    return static_cast<int>(result);
References read_byte(), and v8::base::internal::result.
Referenced by GetEntry().
register_indexes_size()
int v8::internal::MaglevSafepointTable::register_indexes_size () const [inline], [private]
Definition at line 152 of file maglev-safepoint-table.h.
                                    {
    return RegisterIndexesSizeField::decode(entry_configuration_);
Referenced by entry_size(), and GetEntry().
stack_slots()
uint32_t v8::internal::MaglevSafepointTable::stack_slots () [inline]
Definition at line 75 of file maglev-safepoint-table.h.
{ return stack_slots_; }
References stack_slots_.
Friends And Related Function Documentation
MaglevSafepointEntry
friend class MaglevSafepointEntry [friend]
Definition at line 182 of file maglev-safepoint-table.h.
Referenced by FindEntry(), and GetEntry().
MaglevSafepointTableBuilder
friend class MaglevSafepointTableBuilder [friend]
Definition at line 181 of file maglev-safepoint-table.h.
Member Data Documentation
entry_configuration_
const uint32_t v8::internal::MaglevSafepointTable::entry_configuration_ [private]
Definition at line 178 of file maglev-safepoint-table.h.
Referenced by deopt_index_size(), and has_deopt_data().
instruction_start_
const Address v8::internal::MaglevSafepointTable::instruction_start_ [private]
Definition at line 172 of file maglev-safepoint-table.h.
Referenced by FindEntry(), and Print().
length_
const int v8::internal::MaglevSafepointTable::length_ [private]
Definition at line 177 of file maglev-safepoint-table.h.
Referenced by byte_size(), FindEntry(), GetEntry(), length(), and Print().
num_tagged_slots_
const uint32_t v8::internal::MaglevSafepointTable::num_tagged_slots_ [private]
Definition at line 179 of file maglev-safepoint-table.h.
Referenced by FindEntry(), GetEntry(), and Print().
safepoint_table_address_
const Address v8::internal::MaglevSafepointTable::safepoint_table_address_ [private]
Definition at line 175 of file maglev-safepoint-table.h.
Referenced by GetEntry().
stack_slots_
const SafepointTableStackSlotsField_t v8::internal::MaglevSafepointTable::stack_slots_ [private]
Definition at line 176 of file maglev-safepoint-table.h.
Referenced by Print(), and stack_slots().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/maglev-safepoint-table.h
/mnt/V8SourceCode/src/codegen/maglev-safepoint-table.cc