v8::internal::ApiAccessorExitFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
Tagged< Name > property_name () const
Tagged< Object > receiver () const
Tagged< Object > holder () const
void Print (StringStream *accumulator, PrintMode mode, int index) const override
FrameSummaries Summarize () const override
Static Public Member Functions
static ApiAccessorExitFrame * cast (StackFrame *frame)
Protected Member Functions
ApiAccessorExitFrame (StackFrameIteratorBase *iterator)
Private Member Functions
FullObjectSlot property_name_slot () const
FullObjectSlot receiver_slot () const
FullObjectSlot holder_slot () const
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 1017 of file frames.h.
Constructor & Destructor Documentation
ApiAccessorExitFrame()
v8::internal::ApiAccessorExitFrame::ApiAccessorExitFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 212 of file frames-inl.h.
    : ExitFrame(iterator) {}
Member Function Documentation
cast()
static ApiAccessorExitFrame* v8::internal::ApiAccessorExitFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 1032 of file frames.h.
                                                       {
    DCHECK(frame->is_api_accessor_exit());
    return static_cast<ApiAccessorExitFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_api_accessor_exit().
Referenced by v8::internal::Isolate::NotifyExceptionPropagationCallback().
holder()
Tagged< Object > v8::internal::ApiAccessorExitFrame::holder () const [inline]
Definition at line 237 of file frames-inl.h.
{ return *holder_slot(); }
References holder_slot().
Referenced by v8::internal::Isolate::NotifyExceptionPropagationCallback(), Print(), and Summarize().
holder_slot()
FullObjectSlot v8::internal::ApiAccessorExitFrame::holder_slot () const [inline], [private]
Definition at line 225 of file frames-inl.h.
                                                              {
  return FullObjectSlot(fp() + ApiAccessorExitFrameConstants::kHolderOffset);
}
References v8::internal::StackFrame::fp(), and v8::internal::ApiAccessorExitFrameConstants::kHolderOffset.
Referenced by holder().
Print()
void v8::internal::ApiAccessorExitFrame::Print (StringStream * accumulator, PrintMode mode, int index) const [override], [virtual]
Reimplemented from v8::internal::StackFrame.
Definition at line 1458 of file frames.cc.
                                                  {
  DisallowGarbageCollection no_gc;
  PrintIndex(accumulator, mode, index);
  accumulator->Add("api accessor exit frame: ");
  Tagged<Name> name = property_name();
  Tagged<Object> receiver = this->receiver();
  Tagged<Object> holder = this->holder();
  accumulator->Add("(this=%o, holder=%o, name=%o)\n", receiver, holder, name);
}
References v8::internal::StringStream::Add(), holder(), v8::internal::index, mode(), v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::anonymous_namespace{frames.cc}::PrintIndex(), property_name(), and receiver().
property_name()
Tagged< Name > v8::internal::ApiAccessorExitFrame::property_name () const [inline]
Definition at line 229 of file frames-inl.h.
                                                       {
  return Cast<Name>(*property_name_slot());
}
References property_name_slot().
Referenced by v8::internal::Isolate::NotifyExceptionPropagationCallback(), Print(), and Summarize().
property_name_slot()
FullObjectSlot v8::internal::ApiAccessorExitFrame::property_name_slot () const [inline], [private]
Definition at line 216 of file frames-inl.h.
                                                                     {
  return FullObjectSlot(fp() +
                        ApiAccessorExitFrameConstants::kPropertyNameOffset);
}
References v8::internal::StackFrame::fp(), and v8::internal::ApiAccessorExitFrameConstants::kPropertyNameOffset.
Referenced by property_name().
receiver()
Tagged< Object > v8::internal::ApiAccessorExitFrame::receiver () const [inline]
Definition at line 233 of file frames-inl.h.
                                                    {
  return *receiver_slot();
}
References receiver_slot().
Referenced by Print(), and Summarize().
receiver_slot()
FullObjectSlot v8::internal::ApiAccessorExitFrame::receiver_slot () const [inline], [private]
Definition at line 221 of file frames-inl.h.
                                                                {
  return FullObjectSlot(fp() + ApiAccessorExitFrameConstants::kReceiverOffset);
}
References v8::internal::StackFrame::fp(), and v8::internal::ApiAccessorExitFrameConstants::kReceiverOffset.
Referenced by receiver().
Summarize()
FrameSummaries v8::internal::ApiAccessorExitFrame::Summarize () const [override], [virtual]
Reimplemented from v8::internal::CommonFrame.
Definition at line 1368 of file frames.cc.
                                                     {
  // This frame is not supposed to appear in exception stack traces.
  DCHECK(IsName(property_name()));
  DCHECK(IsJSReceiver(receiver()));
  DCHECK(IsJSReceiver(holder()));
  return FrameSummaries();
}
References v8::internal::DCHECK(), holder(), property_name(), and receiver().
type()
Type v8::internal::ApiAccessorExitFrame::type () const [inline], [override], [virtual]
Reimplemented from v8::internal::ExitFrame.
Definition at line 1019 of file frames.h.
{ return API_ACCESSOR_EXIT; }
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 1045 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc