v8::internal::torque::Lexer Class Reference
#include <earley-parser.h>
Public Types
using PatternFunction = bool(*)(InputPosition *pos)
Public Member Functions
void SetWhitespace (PatternFunction whitespace)
Symbol * Pattern (PatternFunction pattern)
Symbol * Token (const std::string &keyword)
V8_EXPORT_PRIVATE LexerResult RunLexer (const std::string &input)
Private Member Functions
Symbol * MatchToken (InputPosition *pos, InputPosition end)
Private Attributes
PatternFunction match_whitespace_ = [](InputPosition*) { return false; }
std::map< PatternFunction, Symbol > patterns_
std::map< std::string, Symbol > keywords_
Detailed Description
Definition at line 391 of file earley-parser.h.
Member Typedef Documentation
PatternFunction
using v8::internal::torque::Lexer::PatternFunction = bool (*)(InputPosition* pos)
Definition at line 396 of file earley-parser.h.
Member Function Documentation
MatchToken()
Symbol * v8::internal::torque::Lexer::MatchToken (InputPosition * pos, InputPosition end) [private]
Definition at line 155 of file earley-parser.cc.
                                                               {
  InputPosition token_start = *pos;
  Symbol* symbol = nullptr;
  // Find longest matching pattern.
  for (std::pair<const PatternFunction, Symbol>& pair : patterns_) {
    InputPosition token_end = token_start;
    PatternFunction matchPattern = pair.first;
    if (matchPattern(&token_end) && token_end > *pos) {
      *pos = token_end;
      symbol = &pair.second;
    }
  }
  size_t pattern_size = *pos - token_start;
  // Now check for keywords. Prefer keywords over patterns unless the pattern is
  // longer. Iterate from the end to ensure that if one keyword is a prefix of
  // another, we first try to match the longer one.
  for (auto it = keywords_.rbegin(); it != keywords_.rend(); ++it) {
    const std::string& keyword = it->first;
    if (static_cast<size_t>(end - token_start) < keyword.size()) continue;
    if (keyword.size() >= pattern_size &&
        keyword == std::string(token_start, token_start + keyword.size())) {
      *pos = token_start + keyword.size();
      return &it->second;
    }
  }
  if (pattern_size > 0) return symbol;
  return nullptr;
}
References v8::internal::compiler::end(), keywords_, patterns_, and v8::internal::string.
Referenced by RunLexer().
Pattern()
Symbol* v8::internal::torque::Lexer::Pattern (PatternFunction pattern) [inline]
Definition at line 402 of file earley-parser.h.
{ return &patterns_[pattern]; }
References patterns_.
Referenced by v8::internal::torque::Grammar::Pattern().
RunLexer()
LexerResult v8::internal::torque::Lexer::RunLexer (const std::string & input)
Definition at line 117 of file earley-parser.cc.
                                                  {
  LexerResult result;
  InputPosition const begin = input.c_str();
  InputPosition const end = begin + input.size();
  InputPosition pos = begin;
  InputPosition token_start = pos;
  LineAndColumnTracker line_column_tracker;
  match_whitespace_(&pos);
  line_column_tracker.Advance(token_start, pos);
  while (pos != end) {
    token_start = pos;
    Symbol* symbol = MatchToken(&pos, end);
    DCHECK_IMPLIES(symbol != nullptr, pos != token_start);
    InputPosition token_end = pos;
    line_column_tracker.Advance(token_start, token_end);
    if (!symbol) {
      CurrentSourcePosition::Scope pos_scope(
          line_column_tracker.ToSourcePosition());
      ReportError("Lexer Error: unknown token " +
                  StringLiteralQuote(std::string(
                      token_start, token_start + std::min<ptrdiff_t>(
                                                     end - token_start, 10))));
    }
    result.token_symbols.push_back(symbol);
    result.token_contents.push_back(
        {token_start, pos, line_column_tracker.ToSourcePosition()});
    match_whitespace_(&pos);
    line_column_tracker.Advance(token_end, pos);
  }
  // Add an additional token position to simplify corner cases.
  line_column_tracker.Advance(token_start, pos);
  result.token_contents.push_back(
      {pos, pos, line_column_tracker.ToSourcePosition()});
  return result;
}
References v8::internal::compiler::begin(), DCHECK_IMPLIES, v8::internal::compiler::end(), match_whitespace_, MatchToken(), v8::internal::torque::ReportError(), v8::base::internal::result, v8::internal::string, and v8::internal::torque::StringLiteralQuote().
Referenced by v8::internal::torque::Grammar::Parse().
SetWhitespace()
void v8::internal::torque::Lexer::SetWhitespace (PatternFunction whitespace) [inline]
Definition at line 398 of file earley-parser.h.
                                                 {
    match_whitespace_ = whitespace;
  }
References match_whitespace_.
Referenced by v8::internal::torque::Grammar::SetWhitespace().
Token()
Symbol* v8::internal::torque::Lexer::Token (const std::string & keyword) [inline]
Definition at line 403 of file earley-parser.h.
{ return &keywords_[keyword]; }
References keywords_.
Referenced by v8::internal::torque::Grammar::Token().
Member Data Documentation
keywords_
std::map<std::string, Symbol> v8::internal::torque::Lexer::keywords_ [private]
Definition at line 409 of file earley-parser.h.
Referenced by MatchToken(), and Token().
match_whitespace_
PatternFunction v8::internal::torque::Lexer::match_whitespace_ = [](InputPosition*) { return false; } [private]
Definition at line 407 of file earley-parser.h.
Referenced by RunLexer(), and SetWhitespace().
patterns_
std::map<PatternFunction, Symbol> v8::internal::torque::Lexer::patterns_ [private]
Definition at line 408 of file earley-parser.h.
Referenced by MatchToken(), and Pattern().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/earley-parser.h
/mnt/V8SourceCode/src/torque/earley-parser.cc