v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator Class Reference
#include <scope-info-inl.h>
Public Member Functions
Iterator (const LocalNamesRange *range, InternalIndex index)
Iterator & operator++ ()
Tagged< String > name (PtrComprCageBase cage_base) const
Tagged< String > name () const
const Iterator * operator* () const
int index () const
Private Member Functions
ScopeInfoPtr scope_info () const
Tagged< NameToIndexHashTable > table () const
void advance_hashtable_index ()
Private Attributes
const LocalNamesRange * range_
InternalIndex index_
Friends
class LocalNamesRange
bool operator== (const Iterator &a, const Iterator &b)
bool operator!= (const Iterator &a, const Iterator &b)
Detailed Description
template<typename ScopeInfoPtr>
class v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator
Definition at line 55 of file scope-info-inl.h.
Constructor & Destructor Documentation
Iterator()
template<typename ScopeInfoPtr >
v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::Iterator (const LocalNamesRange * range, InternalIndex index) [inline]
Definition at line 57 of file scope-info-inl.h.
        : range_(range), index_(index) {
      DCHECK_NOT_NULL(range);
      if (!range_->inlined()) advance_hashtable_index();
    }
References v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::advance_hashtable_index(), DCHECK_NOT_NULL, v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::inlined(), and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::range_.
Member Function Documentation
advance_hashtable_index()
template<typename ScopeInfoPtr >
void v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::advance_hashtable_index () [inline], [private]
Definition at line 110 of file scope-info-inl.h.
                                   {
      DisallowGarbageCollection no_gc;
      ReadOnlyRoots roots = GetReadOnlyRoots();
      InternalIndex max = range_->max_index();
      // Increment until iterator points to a valid key or max.
      while (index_ < max) {
        Tagged<Object> key = table()->KeyAt(index_);
        if (table()->IsKey(roots, key)) break;
        ++index_;
      }
    }
References v8::internal::GetReadOnlyRoots(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::index_, v8::internal::key, v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::max_index(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::range_, and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::table().
Referenced by v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::Iterator(), and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::operator++().
index()
template<typename ScopeInfoPtr >
int v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::index () const [inline]
Definition at line 95 of file scope-info-inl.h.
                      {
      if (range_->inlined()) return index_.as_int();
      return table()->IndexAt(index_);
    }
References v8::internal::InternalIndex::as_int(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::index_, v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::inlined(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::range_, and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::table().
name() [1/2]
template<typename ScopeInfoPtr >
Tagged<String> v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::name () const [inline]
Definition at line 88 of file scope-info-inl.h.
                                {
      PtrComprCageBase cage_base = GetPtrComprCageBase(*scope_info());
      return name(cage_base);
    }
References v8::internal::GetPtrComprCageBase(), and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::scope_info().
name() [2/2]
template<typename ScopeInfoPtr >
Tagged<String> v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::name (PtrComprCageBase cage_base) const [inline]
Definition at line 79 of file scope-info-inl.h.
                                                          {
      DCHECK_LT(index_, range_->max_index());
      if (range_->inlined()) {
        return scope_info()->ContextInlinedLocalName(cage_base,
                                                     index_.as_int());
      }
      return Cast<String>(table()->KeyAt(cage_base, index_));
    }
References v8::internal::InternalIndex::as_int(), DCHECK_LT, v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::index_, v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::inlined(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::max_index(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::range_, v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::scope_info(), and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::table().
operator*()
template<typename ScopeInfoPtr >
const Iterator* v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::operator* () const [inline]
Definition at line 93 of file scope-info-inl.h.
{ return this; }
operator++()
template<typename ScopeInfoPtr >
Iterator& v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::operator++ () [inline]
Definition at line 63 of file scope-info-inl.h.
                           {
      DCHECK_LT(index_, range_->max_index());
      ++index_;
      if (range_->inlined()) return *this;
      advance_hashtable_index();
      return *this;
    }
References v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::advance_hashtable_index(), DCHECK_LT, v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::index_, v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::inlined(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::max_index(), and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::range_.
scope_info()
template<typename ScopeInfoPtr >
ScopeInfoPtr v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::scope_info () const [inline], [private]
Definition at line 104 of file scope-info-inl.h.
{ return range_->scope_info_; }
References v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::range_, and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::scope_info_.
Referenced by v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::name(), and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::table().
table()
template<typename ScopeInfoPtr >
Tagged<NameToIndexHashTable> v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::table () const [inline], [private]
Definition at line 106 of file scope-info-inl.h.
                                               {
      return scope_info()->context_local_names_hashtable();
    }
References v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::scope_info().
Referenced by v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::advance_hashtable_index(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::index(), and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::name().
Friends And Related Function Documentation
LocalNamesRange
template<typename ScopeInfoPtr >
friend class LocalNamesRange [friend]
Definition at line 122 of file scope-info-inl.h.
operator!=
template<typename ScopeInfoPtr >
bool operator!= (const Iterator & a, const Iterator & b) [friend]
Definition at line 75 of file scope-info-inl.h.
                                                                 {
      return !(a == b);
    }
operator==
template<typename ScopeInfoPtr >
bool operator== (const Iterator & a, const Iterator & b) [friend]
Definition at line 71 of file scope-info-inl.h.
                                                                 {
      return a.range_ == b.range_ && a.index_ == b.index_;
    }
Member Data Documentation
index_
template<typename ScopeInfoPtr >
InternalIndex v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::index_ [private]
Definition at line 102 of file scope-info-inl.h.
Referenced by v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::advance_hashtable_index(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::index(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::name(), and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::operator++().
range_
template<typename ScopeInfoPtr >
const LocalNamesRange* v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::range_ [private]
Definition at line 101 of file scope-info-inl.h.
Referenced by v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::advance_hashtable_index(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::index(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::Iterator(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::name(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::operator++(), and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::scope_info().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/scope-info-inl.h