v8::internal::compiler::LoadElimination::AbstractState Class Reference
Public Member Functions
bool Equals (AbstractState const *that) const
void Merge (AbstractState const *that, Zone *zone)
AbstractState const * SetMaps (Node *object, ZoneRefSet< Map > maps, Zone *zone) const
AbstractState const * KillMaps (Node *object, Zone *zone) const
AbstractState const * KillMaps (const AliasStateInfo &alias_info, Zone *zone) const
bool LookupMaps (Node *object, ZoneRefSet< Map > *object_maps) const
AbstractState const * AddField (Node *object, IndexRange index, FieldInfo info, Zone *zone) const
AbstractState const * KillConstField (Node *object, IndexRange index_range, Zone *zone) const
AbstractState const * KillField (const AliasStateInfo &alias_info, IndexRange index, MaybeHandle< Name > name, Zone *zone) const
AbstractState const * KillField (Node *object, IndexRange index, MaybeHandle< Name > name, Zone *zone) const
AbstractState const * KillFields (Node *object, MaybeHandle< Name > name, Zone *zone) const
AbstractState const * KillAll (Zone *zone) const
FieldInfo const * LookupField (Node *object, IndexRange index, ConstFieldInfo const_field_info) const
AbstractState const * AddElement (Node *object, Node *index, Node *value, MachineRepresentation representation, Zone *zone) const
AbstractState const * KillElement (Node *object, Node *index, Zone *zone) const
Node * LookupElement (Node *object, Node *index, MachineRepresentation representation) const
void Print () const
Static Public Member Functions
static AbstractState const * empty_state ()
Private Types
using AbstractFields = std::array< AbstractField const *, kMaxTrackedFieldsPerObject >
Private Member Functions
bool FieldsEquals (AbstractFields const &this_fields, AbstractFields const &that_fields) const
void FieldsMerge (AbstractFields *this_fields, AbstractFields const &that_fields, Zone *zone)
Private Attributes
AbstractElements const * elements_ = nullptr
AbstractFields fields_ {}
AbstractFields const_fields_ {}
AbstractMaps const * maps_ = nullptr
int const_fields_count_ = 0
int fields_count_ = 0
Static Private Attributes
static AbstractState const empty_state_
Detailed Description
Definition at line 254 of file load-elimination.h.
Member Typedef Documentation
AbstractFields
using v8::internal::compiler::LoadElimination::AbstractState::AbstractFields = std::array<AbstractField const*, kMaxTrackedFieldsPerObject> [private]
Definition at line 296 of file load-elimination.h.
Member Function Documentation
AddElement()
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::AbstractState::AddElement (Node * object, Node * index, Node * value, MachineRepresentation representation, Zone * zone) const
Definition at line 536 of file load-elimination.cc.
                                                             {
  AbstractState* that = zone->New<AbstractState>(*this);
  if (that->elements_) {
    that->elements_ =
        that->elements_->Extend(object, index, value, representation, zone);
  } else {
    that->elements_ =
        zone->New<AbstractElements>(object, index, value, representation, zone);
  }
  return that;
}
References elements_, v8::internal::compiler::LoadElimination::AbstractElements::Extend(), v8::internal::index, v8::internal::Zone::New(), v8::internal::value, and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::ReduceLoadElement(), and v8::internal::compiler::LoadElimination::ReduceStoreElement().
AddField()
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::AbstractState::AddField (Node * object, IndexRange index, LoadElimination::FieldInfo info, Zone * zone) const
Definition at line 566 of file load-elimination.cc.
                      {
  AbstractState* that = zone->New<AbstractState>(*this);
  bool is_const = info.const_field_info.IsConst();
  AbstractFields& fields = is_const ? that->const_fields_ : that->fields_;
  for (int index : index_range) {
    int count_before = fields[index] ? fields[index]->count() : 0;
    if (fields[index]) {
      fields[index] =
          fields[index]->Extend(object, info, zone, that->fields_count_);
    } else {
      fields[index] = zone->New<AbstractField>(object, info, zone);
    }
    int added = fields[index]->count() - count_before;
    if (is_const) that->const_fields_count_ += added;
    that->fields_count_ += added;
  }
  return that;
}
References v8::internal::compiler::LoadElimination::FieldInfo::const_field_info, const_fields_, const_fields_count_, v8::internal::compiler::LoadElimination::AbstractField::count(), fields_, fields_count_, v8::internal::index, v8::internal::compiler::ConstFieldInfo::IsConst(), v8::internal::Zone::New(), and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::ReduceEnsureWritableFastElements(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::LoadElimination::ReduceMaybeGrowFastElements(), and v8::internal::compiler::LoadElimination::ReduceStoreField().
empty_state()
static AbstractState const* v8::internal::compiler::LoadElimination::AbstractState::empty_state () [inline], [static]
Definition at line 291 of file load-elimination.h.
{ return &empty_state_; }
Equals()
bool v8::internal::compiler::LoadElimination::AbstractState::Equals (AbstractState const * that) const
Definition at line 434 of file load-elimination.cc.
                                                                         {
  if (this->elements_) {
    if (!that->elements_ || !that->elements_->Equals(this->elements_)) {
      return false;
    }
  } else if (that->elements_) {
    return false;
  }
  if (!FieldsEquals(this->fields_, that->fields_) ||
      !FieldsEquals(this->const_fields_, that->const_fields_)) {
    return false;
  }
  if (this->maps_) {
    if (!that->maps_ || !that->maps_->Equals(this->maps_)) {
      return false;
    }
  } else if (that->maps_) {
    return false;
  }
  return true;
}
References const_fields_, elements_, v8::internal::compiler::LoadElimination::AbstractElements::Equals(), v8::internal::compiler::LoadElimination::AbstractMaps::Equals(), fields_, maps_, and v8::internal::this.
Referenced by v8::internal::compiler::LoadElimination::UpdateState().
FieldsEquals()
bool v8::internal::compiler::LoadElimination::AbstractState::FieldsEquals (AbstractFields const & this_fields, AbstractFields const & that_fields) const [private]
Definition at line 419 of file load-elimination.cc.
                                             {
  for (size_t i = 0u; i < this_fields.size(); ++i) {
    AbstractField const* this_field = this_fields[i];
    AbstractField const* that_field = that_fields[i];
    if (this_field) {
      if (!that_field || !that_field->Equals(this_field)) return false;
    } else if (that_field) {
      return false;
    }
  }
  return true;
}
References v8::internal::compiler::LoadElimination::AbstractField::Equals(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
FieldsMerge()
void v8::internal::compiler::LoadElimination::AbstractState::FieldsMerge (AbstractFields * this_fields, AbstractFields const & that_fields, Zone * zone) [private]
Definition at line 456 of file load-elimination.cc.
                {
  for (size_t i = 0; i < this_fields->size(); ++i) {
    AbstractField const*& this_field = (*this_fields)[i];
    if (this_field) {
      if (that_fields[i]) {
        this_field = this_field->Merge(that_fields[i], zone, &fields_count_);
      } else {
        this_field = nullptr;
      }
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::LoadElimination::AbstractField::Merge(), and v8::internal::compiler::LoadElimination::zone().
KillAll()
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::AbstractState::KillAll (Zone * zone) const
Definition at line 662 of file load-elimination.cc.
                      {
  // Kill everything except for const fields
  for (size_t i = 0; i < const_fields_.size(); ++i) {
    if (const_fields_[i]) {
      AbstractState* that = zone->New<AbstractState>();
      that->const_fields_ = const_fields_;
      that->const_fields_count_ = const_fields_count_;
      that->fields_count_ = const_fields_count_;
      return that;
    }
  }
  return LoadElimination::empty_state();
}
References const_fields_, const_fields_count_, v8::internal::compiler::LoadElimination::empty_state(), fields_count_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Zone::New(), and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::ComputeLoopState(), and v8::internal::compiler::LoadElimination::ReduceOtherNode().
KillConstField()
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::AbstractState::KillConstField (Node * object, IndexRange index_range, Zone * zone) const
Definition at line 588 of file load-elimination.cc.
                                                                 {
  AliasStateInfo alias_info(this, object);
  AbstractState* that = nullptr;
  for (int index : index_range) {
    if (AbstractField const* this_field = this->const_fields_[index]) {
      this_field = this_field->KillConst(object, zone);
      if (this->const_fields_[index] != this_field) {
        if (!that) that = zone->New<AbstractState>(*this);
        that->const_fields_[index] = this_field;
        int removed = this->const_fields_[index]->count() -
                      that->const_fields_[index]->count();
        that->const_fields_count_ -= removed;
        that->fields_count_ -= removed;
      }
    }
  }
  return that ? that : this;
}
References const_fields_, const_fields_count_, fields_count_, v8::internal::index, v8::internal::Zone::New(), and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::ReduceStoreField().
KillElement()
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::AbstractState::KillElement (Node * object, Node * index, Zone * zone) const
Definition at line 552 of file load-elimination.cc.
                                                              {
  if (this->elements_) {
    AbstractElements const* that_elements =
        this->elements_->Kill(object, index, zone);
    if (this->elements_ != that_elements) {
      AbstractState* that = zone->New<AbstractState>(*this);
      that->elements_ = that_elements;
      return that;
    }
  }
  return this;
}
References elements_, v8::internal::index, v8::internal::compiler::LoadElimination::AbstractElements::Kill(), v8::internal::Zone::New(), and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::ComputeLoopState(), and v8::internal::compiler::LoadElimination::ReduceStoreElement().
KillField() [1/2]
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::AbstractState::KillField (const AliasStateInfo & alias_info, IndexRange index, MaybeHandle< Name > name, Zone * zone) const
Definition at line 616 of file load-elimination.cc.
                                              {
  AbstractState* that = nullptr;
  for (int index : index_range) {
    if (AbstractField const* this_field = this->fields_[index]) {
      this_field = this_field->Kill(alias_info, name, zone);
      if (this->fields_[index] != this_field) {
        if (!that) that = zone->New<AbstractState>(*this);
        that->fields_[index] = this_field;
        int removed =
            this->fields_[index]->count() - that->fields_[index]->count();
        that->fields_count_ -= removed;
      }
    }
  }
  return that ? that : this;
}
References fields_, fields_count_, v8::internal::index, v8::internal::name, v8::internal::Zone::New(), and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::LoadElimination::ComputeLoopStateForStoreField(), v8::internal::compiler::LoadElimination::ReduceEnsureWritableFastElements(), v8::internal::compiler::LoadElimination::ReduceMaybeGrowFastElements(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::LoadElimination::ReduceTransitionAndStoreElement(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind(), and v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap().
KillField() [2/2]
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::AbstractState::KillField (Node * object, IndexRange index, MaybeHandle< Name > name, Zone * zone) const
Definition at line 609 of file load-elimination.cc.
                      {
  AliasStateInfo alias_info(this, object);
  return KillField(alias_info, index_range, name, zone);
}
References v8::internal::name, and v8::internal::compiler::LoadElimination::zone().
KillFields()
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::AbstractState::KillFields (Node * object, MaybeHandle< Name > name, Zone * zone) const
Definition at line 636 of file load-elimination.cc.
                                                             {
  AliasStateInfo alias_info(this, object);
  for (size_t i = 0;; ++i) {
    if (i == fields_.size()) {
      return this;
    }
    if (AbstractField const* this_field = this->fields_[i]) {
      AbstractField const* that_field =
          this_field->Kill(alias_info, name, zone);
      if (that_field != this_field) {
        AbstractState* that = zone->New<AbstractState>(*this);
        that->fields_[i] = that_field;
        while (++i < fields_.size()) {
          if (this->fields_[i] != nullptr) {
            that->fields_[i] = this->fields_[i]->Kill(alias_info, name, zone);
            int removed = this->fields_[i]->count() - that->fields_[i]->count();
            that->fields_count_ -= removed;
          }
        }
        return that;
      }
    }
  }
}
References fields_, fields_count_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::LoadElimination::AbstractField::Kill(), v8::internal::name, v8::internal::Zone::New(), and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::ComputeLoopStateForStoreField(), and v8::internal::compiler::LoadElimination::ReduceStoreField().
KillMaps() [1/2]
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::AbstractState::KillMaps (const AliasStateInfo & alias_info, Zone * zone) const
Definition at line 508 of file load-elimination.cc.
                                                        {
  if (this->maps_) {
    AbstractMaps const* that_maps = this->maps_->Kill(alias_info, zone);
    if (this->maps_ != that_maps) {
      AbstractState* that = zone->New<AbstractState>(*this);
      that->maps_ = that_maps;
      return that;
    }
  }
  return this;
}
References v8::internal::compiler::LoadElimination::AbstractMaps::Kill(), maps_, v8::internal::Zone::New(), and v8::internal::compiler::LoadElimination::zone().
KillMaps() [2/2]
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::AbstractState::KillMaps (Node * object, Zone * zone) const
Definition at line 521 of file load-elimination.cc.
                                    {
  AliasStateInfo alias_info(this, object);
  return KillMaps(alias_info, zone);
}
References v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::LoadElimination::ComputeLoopStateForStoreField(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::LoadElimination::ReduceTransitionAndStoreElement(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind(), and v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap().
LookupElement()
Node * v8::internal::compiler::LoadElimination::AbstractState::LookupElement (Node * object, Node * index, MachineRepresentation representation) const
Definition at line 527 of file load-elimination.cc.
                                                                           {
  if (this->elements_) {
    return this->elements_->Lookup(object, index, representation);
  }
  return nullptr;
}
References v8::internal::index.
Referenced by v8::internal::compiler::LoadElimination::ReduceLoadElement(), and v8::internal::compiler::LoadElimination::ReduceStoreElement().
LookupField()
LoadElimination::FieldInfo const * v8::internal::compiler::LoadElimination::AbstractState::LookupField (Node * object, IndexRange index, ConstFieldInfo const_field_info) const
Definition at line 677 of file load-elimination.cc.
                                           {
  // Check if all the indices in {index_range} contain identical information.
  // If not, a partially overlapping access has invalidated part of the value.
  std::optional<LoadElimination::FieldInfo const*> result;
  for (int index : index_range) {
    LoadElimination::FieldInfo const* info = nullptr;
    if (const_field_info.IsConst()) {
      if (AbstractField const* this_field = const_fields_[index]) {
        info = this_field->Lookup(object);
      }
      if (!(info && info->const_field_info == const_field_info)) return nullptr;
    } else {
      if (AbstractField const* this_field = fields_[index]) {
        info = this_field->Lookup(object);
      }
      if (!info) return nullptr;
    }
    if (!result.has_value()) {
      result = info;
    } else if (**result != *info) {
      // We detected inconsistent information for a field here.
      // This can happen when incomplete alias information makes an unrelated
      // write invalidate part of a field and then we re-combine this partial
      // information.
      // This is probably OK, but since it's rare, we better bail out here.
      return nullptr;
    }
  }
  return *result;
}
References v8::internal::compiler::LoadElimination::FieldInfo::const_field_info, v8::internal::index, v8::internal::compiler::ConstFieldInfo::IsConst(), and v8::base::internal::result.
Referenced by v8::internal::compiler::LoadElimination::ReduceLoadField(), and v8::internal::compiler::LoadElimination::ReduceStoreField().
LookupMaps()
bool v8::internal::compiler::LoadElimination::AbstractState::LookupMaps (Node * object, ZoneRefSet< Map > * object_maps) const
Definition at line 492 of file load-elimination.cc.
                                                     {
  return this->maps_ && this->maps_->Lookup(object, object_map);
}
Referenced by v8::internal::compiler::LoadElimination::ComputeLoopState(), v8::internal::compiler::LoadElimination::ReduceCheckMaps(), v8::internal::compiler::LoadElimination::ReduceCompareMaps(), v8::internal::compiler::LoadElimination::ReduceEnsureWritableFastElements(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::LoadElimination::ReduceMapGuard(), v8::internal::compiler::LoadElimination::ReduceTransitionAndStoreElement(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap(), and v8::internal::compiler::LoadElimination::UpdateStateForPhi().
Merge()
void v8::internal::compiler::LoadElimination::AbstractState::Merge (AbstractState const * that, Zone * zone)
Definition at line 471 of file load-elimination.cc.
                                                       {
  // Merge the information we have about the elements.
  if (this->elements_) {
    this->elements_ = that->elements_
                          ? that->elements_->Merge(this->elements_, zone)
                          : nullptr;
  }
  // Merge the information we have about the fields.
  fields_count_ = 0;
  FieldsMerge(&this->const_fields_, that->const_fields_, zone);
  const_fields_count_ = fields_count_;
  FieldsMerge(&this->fields_, that->fields_, zone);
  // Merge the information we have about the maps.
  if (this->maps_) {
    this->maps_ = that->maps_ ? that->maps_->Merge(this->maps_, zone) : nullptr;
  }
}
References const_fields_, elements_, fields_, maps_, v8::internal::compiler::LoadElimination::AbstractElements::Merge(), v8::internal::compiler::LoadElimination::AbstractMaps::Merge(), and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::ReduceEffectPhi().
Print()
void v8::internal::compiler::LoadElimination::AbstractState::Print () const
Definition at line 734 of file load-elimination.cc.
                                               {
  if (maps_) {
    PrintF(" maps:\n");
    maps_->Print();
  }
  if (elements_) {
    PrintF(" elements:\n");
    elements_->Print();
  }
  for (size_t i = 0; i < fields_.size(); ++i) {
    if (AbstractField const* const field = fields_[i]) {
      PrintF(" field %zu:\n", i);
      field->Print();
    }
  }
  for (size_t i = 0; i < const_fields_.size(); ++i) {
    if (AbstractField const* const const_field = const_fields_[i]) {
      PrintF(" const field %zu:\n", i);
      const_field->Print();
    }
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::PrintF().
SetMaps()
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::AbstractState::SetMaps (Node * object, ZoneRefSet< Map > maps, Zone * zone) const
Definition at line 497 of file load-elimination.cc.
                                                          {
  AbstractState* that = zone->New<AbstractState>(*this);
  if (that->maps_) {
    that->maps_ = that->maps_->Extend(object, maps, zone);
  } else {
    that->maps_ = zone->New<AbstractMaps>(object, maps, zone);
  }
  return that;
}
References v8::internal::compiler::LoadElimination::AbstractMaps::Extend(), maps_, v8::internal::Zone::New(), and v8::internal::compiler::LoadElimination::zone().
Referenced by v8::internal::compiler::LoadElimination::ReduceCheckMaps(), v8::internal::compiler::LoadElimination::ReduceEnsureWritableFastElements(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::LoadElimination::ReduceMapGuard(), v8::internal::compiler::LoadElimination::ReduceMaybeGrowFastElements(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::LoadElimination::ReduceTransitionAndStoreElement(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap(), and v8::internal::compiler::LoadElimination::UpdateStateForPhi().
Member Data Documentation
const_fields_
AbstractFields v8::internal::compiler::LoadElimination::AbstractState::const_fields_ {} [private]
Definition at line 306 of file load-elimination.h.
Referenced by AddField(), Equals(), KillAll(), KillConstField(), and Merge().
const_fields_count_
int v8::internal::compiler::LoadElimination::AbstractState::const_fields_count_ = 0 [private]
Definition at line 308 of file load-elimination.h.
Referenced by AddField(), KillAll(), and KillConstField().
elements_
AbstractElements const* v8::internal::compiler::LoadElimination::AbstractState::elements_ = nullptr [private]
Definition at line 304 of file load-elimination.h.
Referenced by AddElement(), Equals(), KillElement(), and Merge().
empty_state_
LoadElimination::AbstractState const v8::internal::compiler::LoadElimination::AbstractState::empty_state_ [static], [private]
Definition at line 294 of file load-elimination.h.
fields_
AbstractFields v8::internal::compiler::LoadElimination::AbstractState::fields_ {} [private]
Definition at line 305 of file load-elimination.h.
Referenced by AddField(), Equals(), KillField(), KillFields(), and Merge().
fields_count_
int v8::internal::compiler::LoadElimination::AbstractState::fields_count_ = 0 [private]
Definition at line 312 of file load-elimination.h.
Referenced by AddField(), KillAll(), KillConstField(), KillField(), and KillFields().
maps_
AbstractMaps const* v8::internal::compiler::LoadElimination::AbstractState::maps_ = nullptr [private]
Definition at line 307 of file load-elimination.h.
Referenced by Equals(), KillMaps(), Merge(), and SetMaps().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/load-elimination.h
/mnt/V8SourceCode/src/compiler/load-elimination.cc