v8::internal::IntlBuiltinsAssembler Class Reference
Public Types
enum class ToLowerCaseKind { kToLowerCase
, kToLocaleLowerCase
 }
Public Member Functions
IntlBuiltinsAssembler (compiler::CodeAssemblerState *state)
void ListFormatCommon (TNode< Context > context, TNode< Int32T > argc, Runtime::FunctionId format_func_id, const char *method_name)
TNode< JSArray > AllocateEmptyJSArray (TNode< Context > context)
TNode< IntPtrT > PointerToSeqStringData (TNode< String > seq_string)
TNode< Uint8T > GetChar (TNode< SeqOneByteString > seq_string, int index)
void JumpIfStartsWithIgnoreCase (TNode< SeqOneByteString > seq_string, const char *pattern, Label *target)
TNode< BoolT > IsNonAlpha (TNode< Uint8T > character)
void ToLowerCaseImpl (TNode< String > string, TNode< Object > maybe_locales, TNode< Context > context, ToLowerCaseKind kind, std::function< void(TNode< JSAny >)> ReturnFct)
Additional Inherited Members
Detailed Description
Definition at line 22 of file builtins-intl-gen.cc.
Member Enumeration Documentation
ToLowerCaseKind
enum v8::internal::IntlBuiltinsAssembler::ToLowerCaseKind [strong]
Enumerator
kToLowerCase
kToLocaleLowerCase
Definition at line 75 of file builtins-intl-gen.cc.
                             {
    kToLowerCase,
    kToLocaleLowerCase,
  };
Constructor & Destructor Documentation
IntlBuiltinsAssembler()
v8::internal::IntlBuiltinsAssembler::IntlBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 24 of file builtins-intl-gen.cc.
      : CodeStubAssembler(state) {}
Member Function Documentation
AllocateEmptyJSArray()
TNode< JSArray > v8::internal::IntlBuiltinsAssembler::AllocateEmptyJSArray (TNode< Context > context)
Definition at line 281 of file builtins-intl-gen.cc.
                            {
  return CodeStubAssembler::AllocateJSArray(
      PACKED_ELEMENTS,
      LoadJSArrayElementsMap(PACKED_ELEMENTS, LoadNativeContext(context)),
      IntPtrConstant(0), SmiConstant(0));
}
References v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::PACKED_ELEMENTS, and v8::internal::compiler::CodeAssembler::SmiConstant().
GetChar()
TNode<Uint8T> v8::internal::IntlBuiltinsAssembler::GetChar (TNode< SeqOneByteString > seq_string, int index) [inline]
Definition at line 43 of file builtins-intl-gen.cc.
                                                                       {
    size_t effective_offset = OFFSET_OF_DATA_START(SeqOneByteString) +
                              sizeof(SeqOneByteString::Char) * index -
                              kHeapObjectTag;
    return Load<Uint8T>(seq_string, IntPtrConstant(effective_offset));
  }
References v8::internal::index, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::kHeapObjectTag, and OFFSET_OF_DATA_START.
Referenced by ToLowerCaseImpl().
IsNonAlpha()
TNode<BoolT> v8::internal::IntlBuiltinsAssembler::IsNonAlpha (TNode< Uint8T > character) [inline]
Definition at line 69 of file builtins-intl-gen.cc.
                                                   {
    return Uint32GreaterThan(
        Int32Sub(Word32Or(character, Int32Constant(0x20)), Int32Constant('a')),
        Int32Constant('z' - 'a'));
  }
References v8::internal::character, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::Int32Sub(), and v8::internal::compiler::CodeAssembler::Word32Or().
Referenced by ToLowerCaseImpl().
JumpIfStartsWithIgnoreCase()
void v8::internal::IntlBuiltinsAssembler::JumpIfStartsWithIgnoreCase (TNode< SeqOneByteString > seq_string, const char * pattern, Label * target) [inline]
Definition at line 52 of file builtins-intl-gen.cc.
                                                                      {
    size_t effective_offset =
        OFFSET_OF_DATA_START(SeqOneByteString) - kHeapObjectTag;
    TNode<Uint16T> raw =
        Load<Uint16T>(seq_string, IntPtrConstant(effective_offset));
    DCHECK_EQ(strlen(pattern), 2);
#if V8_TARGET_BIG_ENDIAN
    int raw_pattern = (pattern[0] << 8) + pattern[1];
#else
    int raw_pattern = pattern[0] + (pattern[1] << 8);
#endif
    GotoIf(Word32Equal(Word32Or(raw, Int32Constant(0x2020)),
                       Int32Constant(raw_pattern)),
           target);
  }
References DCHECK_EQ, v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::kHeapObjectTag, OFFSET_OF_DATA_START, v8::internal::compiler::CodeAssembler::Word32Equal(), and v8::internal::compiler::CodeAssembler::Word32Or().
Referenced by ToLowerCaseImpl().
ListFormatCommon()
void v8::internal::IntlBuiltinsAssembler::ListFormatCommon (TNode< Context > context, TNode< Int32T > argc, Runtime::FunctionId format_func_id, const char * method_name)
Definition at line 253 of file builtins-intl-gen.cc.
                                                                      {
  CodeStubArguments args(this, argc);
  // Label has_list(this);
  // 1. Let lf be this value.
  // 2. If Type(lf) is not Object, throw a TypeError exception.
  TNode<Object> receiver = args.GetReceiver();
  // 3. If lf does not have an [[InitializedListFormat]] internal slot, throw a
  // TypeError exception.
  ThrowIfNotInstanceType(context, receiver, JS_LIST_FORMAT_TYPE, method_name);
  TNode<JSListFormat> list_format = CAST(receiver);
  TNode<Object> list = args.GetOptionalArgumentValue(0);
  {
    // 4. Let stringList be ? StringListFromIterable(list).
    TNode<Object> string_list =
        CallBuiltin(Builtin::kStringListFromIterable, context, list);
    // 6. Return ? FormatList(lf, stringList).
    args.PopAndReturn(
        CallRuntime<JSAny>(format_func_id, context, list_format, string_list));
  }
}
References v8::base::args, v8::internal::compiler::CodeAssembler::CallBuiltin(), CAST, and v8::internal::CodeStubAssembler::ThrowIfNotInstanceType().
PointerToSeqStringData()
TNode<IntPtrT> v8::internal::IntlBuiltinsAssembler::PointerToSeqStringData (TNode< String > seq_string) [inline]
Definition at line 33 of file builtins-intl-gen.cc.
                                                                  {
    CSA_DCHECK(this,
               IsSequentialStringInstanceType(LoadInstanceType(seq_string)));
    static_assert(OFFSET_OF_DATA_START(SeqOneByteString) ==
                  OFFSET_OF_DATA_START(SeqTwoByteString));
    return IntPtrAdd(BitcastTaggedToWord(seq_string),
                     IntPtrConstant(OFFSET_OF_DATA_START(SeqOneByteString) -
                                    kHeapObjectTag));
  }
References v8::internal::compiler::CodeAssembler::BitcastTaggedToWord(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::IsSequentialStringInstanceType(), v8::internal::kHeapObjectTag, v8::internal::CodeStubAssembler::LoadInstanceType(), and OFFSET_OF_DATA_START.
Referenced by ToLowerCaseImpl().
ToLowerCaseImpl()
void v8::internal::IntlBuiltinsAssembler::ToLowerCaseImpl (TNode< String > string, TNode< Object > maybe_locales, TNode< Context > context, ToLowerCaseKind kind, std::function< void(TNode< JSAny >)> ReturnFct)
Definition at line 124 of file builtins-intl-gen.cc.
                                                                     {
  Label call_c(this), return_string(this), runtime(this, Label::kDeferred);
  // Unpack strings if possible, and bail to runtime unless we get a one-byte
  // flat string.
  ToDirectStringAssembler to_direct(
      state(), string, ToDirectStringAssembler::kDontUnpackSlicedStrings);
  to_direct.TryToDirect(&runtime);
  if (kind == ToLowerCaseKind::kToLocaleLowerCase) {
    Label fast(this), check_locale(this);
    // Check for fast locales.
    GotoIf(IsUndefined(maybe_locales), &fast);
    // Passing a Smi as locales requires performing a ToObject conversion
    // followed by reading the length property and the "indexed" properties of
    // it until a valid locale is found.
    GotoIf(TaggedIsSmi(maybe_locales), &runtime);
    GotoIfNot(IsString(CAST(maybe_locales)), &runtime);
    GotoIfNot(IsSeqOneByteString(CAST(maybe_locales)), &runtime);
    TNode<SeqOneByteString> locale = CAST(maybe_locales);
    TNode<Uint32T> locale_length = LoadStringLengthAsWord32(locale);
    GotoIf(Int32LessThan(locale_length, Int32Constant(2)), &runtime);
    GotoIf(IsNonAlpha(GetChar(locale, 0)), &runtime);
    GotoIf(IsNonAlpha(GetChar(locale, 1)), &runtime);
    GotoIf(Word32Equal(locale_length, Int32Constant(2)), &check_locale);
    GotoIf(Word32NotEqual(locale_length, Int32Constant(5)), &runtime);
    GotoIf(Word32NotEqual(GetChar(locale, 2), Int32Constant('-')), &runtime);
    GotoIf(IsNonAlpha(GetChar(locale, 3)), &runtime);
    GotoIf(IsNonAlpha(GetChar(locale, 4)), &runtime);
    Goto(&check_locale);
    Bind(&check_locale);
    JumpIfStartsWithIgnoreCase(locale, "az", &runtime);
    JumpIfStartsWithIgnoreCase(locale, "el", &runtime);
    JumpIfStartsWithIgnoreCase(locale, "lt", &runtime);
    JumpIfStartsWithIgnoreCase(locale, "tr", &runtime);
    Goto(&fast);
    Bind(&fast);
  }
  // Early exit on empty string.
  const TNode<Uint32T> length = LoadStringLengthAsWord32(string);
  GotoIf(Word32Equal(length, Uint32Constant(0)), &return_string);
  const TNode<BoolT> is_one_byte = to_direct.IsOneByte();
  GotoIfNot(is_one_byte, &runtime);
  // For short strings, do the conversion in CSA through the lookup table.
  const TNode<String> dst = AllocateSeqOneByteString(length);
  const int kMaxShortStringLength = 24; // Determined empirically.
  GotoIf(Uint32GreaterThan(length, Uint32Constant(kMaxShortStringLength)),
         &call_c);
  {
    const TNode<IntPtrT> dst_ptr = PointerToSeqStringData(dst);
    TVARIABLE(IntPtrT, var_cursor, IntPtrConstant(0));
    const TNode<IntPtrT> start_address =
        ReinterpretCast<IntPtrT>(to_direct.PointerToData(&call_c));
    const TNode<IntPtrT> end_address =
        Signed(IntPtrAdd(start_address, ChangeUint32ToWord(length)));
    const TNode<ExternalReference> to_lower_table_addr =
        ExternalConstant(ExternalReference::intl_to_latin1_lower_table());
    TVARIABLE(Word32T, var_did_change, Int32Constant(0));
    VariableList push_vars({&var_cursor, &var_did_change}, zone());
    BuildFastLoop<IntPtrT>(
        push_vars, start_address, end_address,
        [&](TNode<IntPtrT> current) {
          TNode<Uint8T> c = Load<Uint8T>(current);
          TNode<Uint8T> lower =
              Load<Uint8T>(to_lower_table_addr, ChangeInt32ToIntPtr(c));
          StoreNoWriteBarrier(MachineRepresentation::kWord8, dst_ptr,
                              var_cursor.value(), lower);
          var_did_change =
              Word32Or(Word32NotEqual(c, lower), var_did_change.value());
          Increment(&var_cursor);
        },
        kCharSize, LoopUnrollingMode::kNo, IndexAdvanceMode::kPost);
    // Return the original string if it remained unchanged in order to preserve
    // e.g. internalization and private symbols (such as the preserved object
    // hash) on the source string.
    GotoIfNot(var_did_change.value(), &return_string);
    ReturnFct(dst);
  }
  // Call into C for case conversion. The signature is:
  // String ConvertOneByteToLower(String src, String dst);
  BIND(&call_c);
  {
    const TNode<String> src = to_direct.string();
    const TNode<ExternalReference> function_addr =
        ExternalConstant(ExternalReference::intl_convert_one_byte_to_lower());
    MachineType type_tagged = MachineType::AnyTagged();
    const TNode<String> result = CAST(CallCFunction(
        function_addr, type_tagged, std::make_pair(type_tagged, src),
        std::make_pair(type_tagged, dst)));
    ReturnFct(result);
  }
  BIND(&return_string);
  ReturnFct(string);
  BIND(&runtime);
  if (kind == ToLowerCaseKind::kToLocaleLowerCase) {
    ReturnFct(CallRuntime<JSAny>(Runtime::kStringToLocaleLowerCase, context,
                                 string, maybe_locales));
  } else {
    DCHECK_EQ(kind, ToLowerCaseKind::kToLowerCase);
    ReturnFct(CallRuntime<JSAny>(Runtime::kStringToLowerCaseIntl,
                                 NoContextConstant(), string));
  }
}
References v8::internal::CodeStubAssembler::AllocateSeqOneByteString(), v8::internal::MachineType::AnyTagged(), v8::internal::CodeStubAssembler::Bind(), v8::internal::compiler::CodeAssembler::CallCFunction(), CAST, v8::internal::compiler::CodeAssembler::ChangeInt32ToIntPtr(), v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), DCHECK_EQ, v8::internal::compiler::CodeAssembler::ExternalConstant(), GetChar(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::Increment(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), IsNonAlpha(), v8::internal::ToDirectStringAssembler::IsOneByte(), v8::internal::CodeStubAssembler::IsSeqOneByteString(), v8::internal::CodeStubAssembler::IsString(), JumpIfStartsWithIgnoreCase(), v8::internal::kCharSize, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::ToDirectStringAssembler::kDontUnpackSlicedStrings, v8::internal::CodeStubAssembler::kNo, v8::internal::CodeStubAssembler::kPost, kToLocaleLowerCase, kToLowerCase, v8::internal::kWord8, v8::internal::length, v8::internal::CodeStubAssembler::LoadStringLengthAsWord32(), v8::internal::CodeStubAssembler::NoContextConstant(), v8::internal::ToDirectStringAssembler::PointerToData(), PointerToSeqStringData(), v8::base::internal::result, v8::internal::compiler::CodeAssembler::Signed(), v8::internal::compiler::CodeAssembler::state(), v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier(), v8::internal::ToDirectStringAssembler::string(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::ToDirectStringAssembler::TryToDirect(), v8::internal::compiler::CodeAssembler::Uint32Constant(), v8::internal::compiler::CodeAssembler::Word32Equal(), v8::internal::compiler::CodeAssembler::Word32NotEqual(), v8::internal::compiler::CodeAssembler::Word32Or(), and v8::internal::compiler::CodeAssembler::zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-intl-gen.cc