v8::internal::OffHeapInstructionStream Class Reference
#include <embedded-data.h>
Static Public Member Functions
static bool PcIsOffHeap (Isolate *isolate, Address pc)
static bool TryGetAddressForHashing (Isolate *isolate, Address address, uint32_t *hashable_address)
static Builtin TryLookupCode (Isolate *isolate, Address address)
static void CreateOffHeapOffHeapInstructionStream (Isolate *isolate, uint8_t **code, uint32_t *code_size, uint8_t **data, uint32_t *data_size)
static void FreeOffHeapOffHeapInstructionStream (uint8_t *code, uint32_t code_size, uint8_t *data, uint32_t data_size)
Detailed Description
Definition at line 25 of file embedded-data.h.
Member Function Documentation
CreateOffHeapOffHeapInstructionStream()
void v8::internal::OffHeapInstructionStream::CreateOffHeapOffHeapInstructionStream (Isolate * isolate, uint8_t ** code, uint32_t * code_size, uint8_t ** data, uint32_t * data_size) [static]
Definition at line 105 of file embedded-data.cc.
                         {
  // Create the embedded blob from scratch using the current Isolate's heap.
  EmbeddedData d = EmbeddedData::NewFromIsolate(isolate);
  // Allocate the backing store that will contain the embedded blob in this
  // Isolate. The backing store is on the native heap, *not* on V8's garbage-
  // collected heap.
  v8::PageAllocator* page_allocator = v8::internal::GetPlatformPageAllocator();
  const uint32_t alignment =
      static_cast<uint32_t>(page_allocator->AllocatePageSize());
  void* const requested_allocation_code_address =
      AlignedAddress(isolate->heap()->GetRandomMmapAddr(), alignment);
  const uint32_t allocation_code_size = RoundUp(d.code_size(), alignment);
  uint8_t* allocated_code_bytes = static_cast<uint8_t*>(
      AllocatePages(page_allocator, allocation_code_size, alignment,
                    PageAllocator::kReadWrite,
                    v8::PageAllocator::AllocationHint().WithAddress(
                        requested_allocation_code_address)));
  CHECK_NOT_NULL(allocated_code_bytes);
  void* const requested_allocation_data_address =
      AlignedAddress(isolate->heap()->GetRandomMmapAddr(), alignment);
  const uint32_t allocation_data_size = RoundUp(d.data_size(), alignment);
  uint8_t* allocated_data_bytes = static_cast<uint8_t*>(
      AllocatePages(page_allocator, allocation_data_size, alignment,
                    PageAllocator::kReadWrite,
                    v8::PageAllocator::AllocationHint().WithAddress(
                        requested_allocation_data_address)));
  CHECK_NOT_NULL(allocated_data_bytes);
  // Copy the embedded blob into the newly allocated backing store. Switch
  // permissions to read-execute since builtin code is immutable from now on
  // and must be executable in case any JS execution is triggered.
  //
  // Once this backing store is set as the current_embedded_blob, V8 cannot tell
  // the difference between a 'real' embedded build (where the blob is embedded
  // in the binary) and what we are currently setting up here (where the blob is
  // on the native heap).
  std::memcpy(allocated_code_bytes, d.code(), d.code_size());
  if (v8_flags.experimental_flush_embedded_blob_icache) {
    FlushInstructionCache(allocated_code_bytes, d.code_size());
  }
  CHECK(SetPermissions(page_allocator, allocated_code_bytes,
                       allocation_code_size, PageAllocator::kReadExecute));
  std::memcpy(allocated_data_bytes, d.data(), d.data_size());
  CHECK(SetPermissions(page_allocator, allocated_data_bytes,
                       allocation_data_size, PageAllocator::kRead));
  *code = allocated_code_bytes;
  *code_size = d.code_size();
  *data = allocated_data_bytes;
  *data_size = d.data_size();
  d.Dispose();
}
References AlignedAddress(), v8::internal::AllocatePages(), v8::PageAllocator::AllocatePageSize(), CHECK, CHECK_NOT_NULL, code, v8::internal::EmbeddedData::code(), v8::internal::EmbeddedData::code_size(), v8::internal::EmbeddedData::data(), v8::internal::EmbeddedData::data_size(), v8::internal::EmbeddedData::Dispose(), v8::internal::FlushInstructionCache(), v8::internal::GetPlatformPageAllocator(), v8::internal::Heap::GetRandomMmapAddr(), v8::internal::Isolate::heap(), v8::PageAllocator::kRead, v8::PageAllocator::kReadExecute, v8::PageAllocator::kReadWrite, v8::internal::EmbeddedData::NewFromIsolate(), RoundUp(), v8::internal::SetPermissions(), and v8::internal::v8_flags.
Referenced by v8::internal::Isolate::CreateAndSetEmbeddedBlob().
FreeOffHeapOffHeapInstructionStream()
void v8::internal::OffHeapInstructionStream::FreeOffHeapOffHeapInstructionStream (uint8_t * code, uint32_t code_size, uint8_t * data, uint32_t data_size) [static]
Definition at line 166 of file embedded-data.cc.
                                                                          {
  v8::PageAllocator* page_allocator = v8::internal::GetPlatformPageAllocator();
  const uint32_t page_size =
      static_cast<uint32_t>(page_allocator->AllocatePageSize());
  FreePages(page_allocator, code, RoundUp(code_size, page_size));
  FreePages(page_allocator, data, RoundUp(data_size, page_size));
}
References v8::PageAllocator::AllocatePageSize(), code, v8::internal::FreePages(), v8::internal::GetPlatformPageAllocator(), and RoundUp().
Referenced by v8::internal::FreeCurrentEmbeddedBlob(), and v8::internal::Isolate::TearDownEmbeddedBlob().
PcIsOffHeap()
bool v8::internal::OffHeapInstructionStream::PcIsOffHeap (Isolate * isolate, Address pc) [static]
Definition at line 41 of file embedded-data.cc.
                                                                       {
  // Mksnapshot calls this while the embedded blob is not available yet.
  if (isolate->embedded_blob_code() == nullptr) return false;
  DCHECK_NOT_NULL(Isolate::CurrentEmbeddedBlobCode());
  if (EmbeddedData::FromBlob(isolate).IsInCodeRange(pc)) return true;
  return isolate->is_short_builtin_calls_enabled() &&
         EmbeddedData::FromBlob().IsInCodeRange(pc);
}
References v8::internal::Isolate::CurrentEmbeddedBlobCode(), DCHECK_NOT_NULL, v8::internal::Isolate::embedded_blob_code(), v8::internal::EmbeddedData::FromBlob(), v8::internal::Isolate::is_short_builtin_calls_enabled(), and v8::internal::EmbeddedData::IsInCodeRange().
Referenced by v8::internal::Code::IsIsolateIndependent(), and v8::internal::Heap::TryFindCodeForInnerPointerForPrinting().
TryGetAddressForHashing()
bool v8::internal::OffHeapInstructionStream::TryGetAddressForHashing (Isolate * isolate, Address address, uint32_t * hashable_address) [static]
Definition at line 52 of file embedded-data.cc.
                                                                   {
  // Mksnapshot calls this while the embedded blob is not available yet.
  if (isolate->embedded_blob_code() == nullptr) return false;
  DCHECK_NOT_NULL(Isolate::CurrentEmbeddedBlobCode());
  EmbeddedData d = EmbeddedData::FromBlob(isolate);
  if (d.IsInCodeRange(address)) {
    *hashable_address = d.AddressForHashing(address);
    return true;
  }
  if (isolate->is_short_builtin_calls_enabled()) {
    d = EmbeddedData::FromBlob();
    if (d.IsInCodeRange(address)) {
      *hashable_address = d.AddressForHashing(address);
      return true;
    }
  }
  return false;
}
References v8::internal::EmbeddedData::AddressForHashing(), v8::internal::Isolate::CurrentEmbeddedBlobCode(), DCHECK_NOT_NULL, v8::internal::Isolate::embedded_blob_code(), v8::internal::EmbeddedData::FromBlob(), v8::internal::Isolate::is_short_builtin_calls_enabled(), and v8::internal::EmbeddedData::IsInCodeRange().
Referenced by v8::internal::anonymous_namespace{frames.cc}::PcAddressForHashing().
TryLookupCode()
Builtin v8::internal::OffHeapInstructionStream::TryLookupCode (Isolate * isolate, Address address) [static]
Definition at line 75 of file embedded-data.cc.
                                                                 {
  // Mksnapshot calls this while the embedded blob is not available yet.
  if (isolate->embedded_blob_code() == nullptr) return Builtin::kNoBuiltinId;
  DCHECK_NOT_NULL(Isolate::CurrentEmbeddedBlobCode());
  Builtin builtin = EmbeddedData::FromBlob(isolate).TryLookupCode(address);
  if (isolate->is_short_builtin_calls_enabled() &&
      !Builtins::IsBuiltinId(builtin)) {
    builtin = EmbeddedData::FromBlob().TryLookupCode(address);
  }
#ifdef V8_COMPRESS_POINTERS_IN_SHARED_CAGE
  if (V8_SHORT_BUILTIN_CALLS_BOOL && !Builtins::IsBuiltinId(builtin)) {
    // When shared pointer compression cage is enabled and it has the embedded
    // code blob copy then it could have been used regardless of whether the
    // isolate uses it or knows about it or not (see
    // InstructionStream::OffHeapInstructionStart()).
    // So, this blob has to be checked too.
    CodeRange* code_range = IsolateGroup::current()->GetCodeRange();
    if (code_range && code_range->embedded_blob_code_copy() != nullptr) {
      builtin = EmbeddedData::FromBlob(code_range).TryLookupCode(address);
    }
  }
#endif
  return builtin;
}
References v8::internal::IsolateGroup::current(), v8::internal::Isolate::CurrentEmbeddedBlobCode(), DCHECK_NOT_NULL, v8::internal::Isolate::embedded_blob_code(), v8::internal::CodeRange::embedded_blob_code_copy(), v8::internal::EmbeddedData::FromBlob(), v8::internal::IsolateGroup::GetCodeRange(), v8::internal::Isolate::is_short_builtin_calls_enabled(), v8::internal::Builtins::IsBuiltinId(), v8::internal::kNoBuiltinId, v8::internal::EmbeddedData::TryLookupCode(), and V8_SHORT_BUILTIN_CALLS_BOOL.
Referenced by v8::internal::Heap::GcSafeInstructionStreamContains(), v8::internal::Heap::GcSafeTryFindCodeForInnerPointer(), v8::internal::anonymous_namespace{frames.cc}::IsInterpreterFramePc(), and v8::internal::Builtins::Lookup().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/embedded/embedded-data.h
/mnt/V8SourceCode/src/snapshot/embedded/embedded-data.cc