v8::internal::compiler::turboshaft::ShufflePackNode Class Reference
#include <wasm-revec-reducer.h>
Classes
class SpecificInfo
Public Member Functions
ShufflePackNode (Zone *zone, const NodeGroup &node_group, SpecificInfo::Kind kind)
SpecificInfo & info ()
Private Attributes
SpecificInfo info_
Additional Inherited Members
Detailed Description
Definition at line 344 of file wasm-revec-reducer.h.
Constructor & Destructor Documentation
ShufflePackNode()
v8::internal::compiler::turboshaft::ShufflePackNode::ShufflePackNode (Zone * zone, const NodeGroup & node_group, SpecificInfo::Kind kind) [inline]
Definition at line 406 of file wasm-revec-reducer.h.
      : PackNode(zone, node_group, kShufflePackNode) {
    info_.set_kind(kind);
  }
References info_, and v8::internal::compiler::turboshaft::ShufflePackNode::SpecificInfo::set_kind().
Member Function Documentation
info()
SpecificInfo& v8::internal::compiler::turboshaft::ShufflePackNode::info () [inline]
Definition at line 412 of file wasm-revec-reducer.h.
{ return info_; }
References info_.
Referenced by v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), and v8::internal::compiler::turboshaft::WasmRevecReducer< Next >::Simd128Shuffle().
Member Data Documentation
info_
SpecificInfo v8::internal::compiler::turboshaft::ShufflePackNode::info_ [private]
Definition at line 415 of file wasm-revec-reducer.h.
Referenced by info(), and ShufflePackNode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-revec-reducer.h