v8::internal::RememberedSet< type > Class Template Reference
#include <remembered-set.h>
Static Public Member Functions
template<AccessMode access_mode>
static void Insert (MutablePageMetadata *page, size_t slot_offset)
static void MergeAndDelete (MutablePageMetadata *chunk, SlotSet &&other_slot_set)
static void MergeAndDeleteTyped (MutablePageMetadata *chunk, TypedSlotSet &&other_typed_slot_set)
static void DeleteTyped (TypedSlotSet &&other_typed_slot_set)
static bool Contains (MutablePageMetadata *chunk, Address slot_addr)
static void CheckNoneInRange (MutablePageMetadata *page, Address start, Address end)
static void Remove (MutablePageMetadata *chunk, Address slot_addr)
static void RemoveRange (MutablePageMetadata *chunk, Address start, Address end, SlotSet::EmptyBucketMode mode)
template<typename Callback >
static void IterateMemoryChunks (Heap *heap, Callback callback)
template<AccessMode access_mode = AccessMode::ATOMIC, typename Callback >
static int Iterate (MutablePageMetadata *chunk, Callback callback, SlotSet::EmptyBucketMode mode)
template<AccessMode access_mode = AccessMode::ATOMIC, typename Callback >
static int Iterate (SlotSet *slot_set, const MutablePageMetadata *chunk, Callback callback, SlotSet::EmptyBucketMode mode)
template<typename Callback >
static int IterateAndTrackEmptyBuckets (MutablePageMetadata *chunk, Callback callback, ::heap::base::Worklist< MutablePageMetadata *, 64 >::Local *empty_chunks)
static bool CheckPossiblyEmptyBuckets (MutablePageMetadata *chunk)
static void InsertTyped (MutablePageMetadata *memory_chunk, SlotType slot_type, uint32_t offset)
static void MergeTyped (MutablePageMetadata *page, std::unique_ptr< TypedSlots > other)
static void RemoveRangeTyped (MutablePageMetadata *page, Address start, Address end)
template<typename Callback >
static int IterateTyped (MutablePageMetadata *chunk, Callback callback)
template<typename Callback >
static int IterateTyped (TypedSlotSet *slot_set, Callback callback)
static void ClearAll (Heap *heap)
Detailed Description
template<RememberedSetType type>
class v8::internal::RememberedSet< type >
Definition at line 92 of file remembered-set.h.
Member Function Documentation
CheckNoneInRange()
template<RememberedSetType type>
static void v8::internal::RememberedSet< type >::CheckNoneInRange (MutablePageMetadata * page, Address start, Address end) [inline], [static]
Definition at line 152 of file remembered-set.h.
                                            {
    SlotSet* slot_set = page->slot_set<type>();
    RememberedSetOperations::CheckNoneInRange(slot_set, page->Chunk(), start,
                                              end);
  }
References v8::internal::RememberedSetOperations::CheckNoneInRange(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::compiler::end(), v8::internal::MutablePageMetadata::slot_set(), and v8::internal::tracing::type.
CheckPossiblyEmptyBuckets()
template<RememberedSetType type>
static bool v8::internal::RememberedSet< type >::CheckPossiblyEmptyBuckets (MutablePageMetadata * chunk) [inline], [static]
Definition at line 228 of file remembered-set.h.
                                                                    {
    DCHECK(type == OLD_TO_NEW || type == OLD_TO_NEW_BACKGROUND);
    SlotSet* slot_set = chunk->slot_set<type, AccessMode::NON_ATOMIC>();
    if (slot_set != nullptr &&
        slot_set->CheckPossiblyEmptyBuckets(chunk->BucketsInSlotSet(),
                                            chunk->possibly_empty_buckets())) {
      chunk->ReleaseSlotSet(type);
      return true;
    }
    return false;
  }
References v8::internal::MutablePageMetadata::BucketsInSlotSet(), v8::internal::SlotSet::CheckPossiblyEmptyBuckets(), v8::internal::DCHECK(), v8::internal::NON_ATOMIC, v8::internal::OLD_TO_NEW, v8::internal::OLD_TO_NEW_BACKGROUND, v8::internal::MutablePageMetadata::possibly_empty_buckets(), v8::internal::MutablePageMetadata::ReleaseSlotSet(), v8::internal::MutablePageMetadata::slot_set(), and v8::internal::tracing::type.
ClearAll()
template<RememberedSetType type>
static void v8::internal::RememberedSet< type >::ClearAll (Heap * heap) [inline], [static]
Definition at line 293 of file remembered-set.h.
                                   {
    static_assert(type == OLD_TO_OLD || type == TRUSTED_TO_CODE);
    OldGenerationMemoryChunkIterator it(heap);
    MutablePageMetadata* chunk;
    while ((chunk = it.next()) != nullptr) {
      chunk->ReleaseSlotSet(OLD_TO_OLD);
      chunk->ReleaseSlotSet(TRUSTED_TO_CODE);
      chunk->ReleaseTypedSlotSet(OLD_TO_OLD);
    }
  }
References v8::internal::OldGenerationMemoryChunkIterator::next(), v8::internal::OLD_TO_OLD, v8::internal::MutablePageMetadata::ReleaseSlotSet(), v8::internal::MutablePageMetadata::ReleaseTypedSlotSet(), v8::internal::TRUSTED_TO_CODE, and v8::internal::tracing::type.
Contains()
template<RememberedSetType type>
static bool v8::internal::RememberedSet< type >::Contains (MutablePageMetadata * chunk, Address slot_addr) [inline], [static]
Definition at line 142 of file remembered-set.h.
                                                                      {
    DCHECK(chunk->Contains(slot_addr));
    SlotSet* slot_set = chunk->slot_set<type>();
    if (slot_set == nullptr) {
      return false;
    }
    uintptr_t offset = chunk->Offset(slot_addr);
    return slot_set->Contains(offset);
  }
References v8::internal::MemoryChunkMetadata::Contains(), heap::base::BasicSlotSet< SlotGranularity >::Contains(), v8::internal::DCHECK(), v8::internal::MemoryChunkMetadata::Offset(), v8::internal::MutablePageMetadata::slot_set(), and v8::internal::tracing::type.
DeleteTyped()
template<RememberedSetType type>
static void v8::internal::RememberedSet< type >::DeleteTyped (TypedSlotSet && other_typed_slot_set) [inline], [static]
Definition at line 136 of file remembered-set.h.
                                                               {
    delete &other_typed_slot_set;
  }
Referenced by v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::DeleteRememberedSets().
Insert()
template<RememberedSetType type>
template<AccessMode access_mode>
static void v8::internal::RememberedSet< type >::Insert (MutablePageMetadata * page, size_t slot_offset) [inline], [static]
Definition at line 97 of file remembered-set.h.
                                                                    {
    SlotSet* slot_set = page->slot_set<type, access_mode>();
    if (slot_set == nullptr) {
      slot_set = page->AllocateSlotSet(type);
    }
    RememberedSetOperations::Insert<access_mode>(slot_set, slot_offset);
  }
References v8::internal::MutablePageMetadata::AllocateSlotSet(), v8::internal::MutablePageMetadata::slot_set(), and v8::internal::tracing::type.
InsertTyped()
template<RememberedSetType type>
static void v8::internal::RememberedSet< type >::InsertTyped (MutablePageMetadata * memory_chunk, SlotType slot_type, uint32_t offset) [inline], [static]
Definition at line 243 of file remembered-set.h.
                                           {
    TypedSlotSet* slot_set = memory_chunk->typed_slot_set<type>();
    if (slot_set == nullptr) {
      slot_set = memory_chunk->AllocateTypedSlotSet(type);
    }
    slot_set->Insert(slot_type, offset);
  }
References v8::internal::MutablePageMetadata::AllocateTypedSlotSet(), v8::internal::TypedSlots::Insert(), v8::internal::tracing::type, and v8::internal::MutablePageMetadata::typed_slot_set().
Referenced by v8::internal::WriteBarrier::GenerationalBarrierForCodeSlow(), and v8::internal::WriteBarrier::SharedSlow().
Iterate() [1/2]
template<RememberedSetType type>
template<AccessMode access_mode = AccessMode::ATOMIC, typename Callback >
static int v8::internal::RememberedSet< type >::Iterate (MutablePageMetadata * chunk, Callback callback, SlotSet::EmptyBucketMode mode) [inline], [static]
Definition at line 198 of file remembered-set.h.
                                                  {
    SlotSet* slot_set = chunk->slot_set<type>();
    return Iterate<access_mode>(slot_set, chunk, callback, mode);
  }
References mode(), v8::internal::MutablePageMetadata::slot_set(), and v8::internal::tracing::type.
Referenced by v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap().
Iterate() [2/2]
template<RememberedSetType type>
template<AccessMode access_mode = AccessMode::ATOMIC, typename Callback >
static int v8::internal::RememberedSet< type >::Iterate (SlotSet * slot_set, const MutablePageMetadata * chunk, Callback callback, SlotSet::EmptyBucketMode mode) [inline], [static]
Definition at line 205 of file remembered-set.h.
                                                                     {
    return RememberedSetOperations::Iterate<access_mode>(slot_set, chunk,
                                                         callback, mode);
  }
References mode().
IterateAndTrackEmptyBuckets()
template<RememberedSetType type>
template<typename Callback >
static int v8::internal::RememberedSet< type >::IterateAndTrackEmptyBuckets (MutablePageMetadata * chunk, Callback callback, ::heap::base::Worklist< MutablePageMetadata *, 64 >::Local * empty_chunks) [inline], [static]
Definition at line 212 of file remembered-set.h.
                                                                     {
    SlotSet* slot_set = chunk->slot_set<type>();
    int slots = 0;
    if (slot_set != nullptr) {
      PossiblyEmptyBuckets* possibly_empty_buckets =
          chunk->possibly_empty_buckets();
      slots += slot_set->IterateAndTrackEmptyBuckets(
          chunk->ChunkAddress(), 0, chunk->BucketsInSlotSet(), callback,
          possibly_empty_buckets);
      if (!possibly_empty_buckets->IsEmpty()) empty_chunks->Push(chunk);
    }
    return slots;
  }
References v8::internal::MutablePageMetadata::BucketsInSlotSet(), v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::PossiblyEmptyBuckets::IsEmpty(), v8::internal::SlotSet::IterateAndTrackEmptyBuckets(), v8::internal::MutablePageMetadata::possibly_empty_buckets(), heap::base::Worklist< EntryType, MinSegmentSize >::Local::Push(), v8::internal::MutablePageMetadata::slot_set(), and v8::internal::tracing::type.
Referenced by v8::internal::Scavenger::ScavengePage().
IterateMemoryChunks()
template<RememberedSetType type>
template<typename Callback >
static void v8::internal::RememberedSet< type >::IterateMemoryChunks (Heap * heap, Callback callback) [inline], [static]
Definition at line 179 of file remembered-set.h.
                                                                 {
    OldGenerationMemoryChunkIterator it(heap);
    MutablePageMetadata* chunk;
    while ((chunk = it.next()) != nullptr) {
      SlotSet* slot_set = chunk->slot_set<type>();
      TypedSlotSet* typed_slot_set = chunk->typed_slot_set<type>();
      if (slot_set != nullptr || typed_slot_set != nullptr) {
        callback(chunk);
      }
    }
  }
References v8::internal::OldGenerationMemoryChunkIterator::next(), v8::internal::MutablePageMetadata::slot_set(), v8::internal::tracing::type, and v8::internal::MutablePageMetadata::typed_slot_set().
IterateTyped() [1/2]
template<RememberedSetType type>
template<typename Callback >
static int v8::internal::RememberedSet< type >::IterateTyped (MutablePageMetadata * chunk, Callback callback) [inline], [static]
Definition at line 280 of file remembered-set.h.
                                                                         {
    TypedSlotSet* slot_set = chunk->typed_slot_set<type>();
    if (!slot_set) return 0;
    return IterateTyped(slot_set, callback);
  }
References v8::internal::tracing::type, and v8::internal::MutablePageMetadata::typed_slot_set().
Referenced by v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::MarkTypedPointers(), and v8::internal::Scavenger::ScavengePage().
IterateTyped() [2/2]
template<RememberedSetType type>
template<typename Callback >
static int v8::internal::RememberedSet< type >::IterateTyped (TypedSlotSet * slot_set, Callback callback) [inline], [static]
Definition at line 287 of file remembered-set.h.
                                                                     {
    DCHECK_NOT_NULL(slot_set);
    return slot_set->Iterate(callback, TypedSlotSet::KEEP_EMPTY_CHUNKS);
  }
References DCHECK_NOT_NULL, v8::internal::TypedSlotSet::Iterate(), and v8::internal::TypedSlotSet::KEEP_EMPTY_CHUNKS.
MergeAndDelete()
template<RememberedSetType type>
static void v8::internal::RememberedSet< type >::MergeAndDelete (MutablePageMetadata * chunk, SlotSet && other_slot_set) [inline], [static]
Definition at line 107 of file remembered-set.h.
                                                       {
    static_assert(type == RememberedSetType::OLD_TO_NEW ||
                  type == RememberedSetType::OLD_TO_NEW_BACKGROUND);
    SlotSet* slot_set = chunk->slot_set<type, AccessMode::NON_ATOMIC>();
    if (slot_set == nullptr) {
      chunk->set_slot_set<type, AccessMode::NON_ATOMIC>(&other_slot_set);
      return;
    }
    slot_set->Merge(&other_slot_set, chunk->BucketsInSlotSet());
    SlotSet::Delete(&other_slot_set);
  }
References v8::internal::MutablePageMetadata::BucketsInSlotSet(), heap::base::BasicSlotSet< kTaggedSize >::Delete(), v8::internal::SlotSet::Merge(), v8::internal::NON_ATOMIC, v8::internal::OLD_TO_NEW, v8::internal::OLD_TO_NEW_BACKGROUND, v8::internal::MutablePageMetadata::set_slot_set(), v8::internal::MutablePageMetadata::slot_set(), and v8::internal::tracing::type.
Referenced by v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::MergeAndDeleteRememberedSets().
MergeAndDeleteTyped()
template<RememberedSetType type>
static void v8::internal::RememberedSet< type >::MergeAndDeleteTyped (MutablePageMetadata * chunk, TypedSlotSet && other_typed_slot_set) [inline], [static]
Definition at line 122 of file remembered-set.h.
                                                                       {
    static_assert(type == RememberedSetType::OLD_TO_NEW);
    TypedSlotSet* typed_slot_set =
        chunk->typed_slot_set<type, AccessMode::NON_ATOMIC>();
    if (typed_slot_set == nullptr) {
      chunk->set_typed_slot_set<RememberedSetType::OLD_TO_NEW,
                                AccessMode::NON_ATOMIC>(&other_typed_slot_set);
      return;
    }
    typed_slot_set->Merge(&other_typed_slot_set);
    delete &other_typed_slot_set;
  }
References v8::internal::TypedSlots::Merge(), v8::internal::NON_ATOMIC, v8::internal::OLD_TO_NEW, v8::internal::MutablePageMetadata::set_typed_slot_set(), v8::internal::tracing::type, and v8::internal::MutablePageMetadata::typed_slot_set().
Referenced by v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::MergeAndDeleteRememberedSets().
MergeTyped()
template<RememberedSetType type>
static void v8::internal::RememberedSet< type >::MergeTyped (MutablePageMetadata * page, std::unique_ptr< TypedSlots > other) [inline], [static]
Definition at line 252 of file remembered-set.h.
                                                          {
    TypedSlotSet* slot_set = page->typed_slot_set<type>();
    if (slot_set == nullptr) {
      slot_set = page->AllocateTypedSlotSet(type);
    }
    slot_set->Merge(other.get());
  }
References v8::internal::MutablePageMetadata::AllocateTypedSlotSet(), v8::internal::TypedSlots::Merge(), v8::internal::tracing::type, and v8::internal::MutablePageMetadata::typed_slot_set().
Referenced by v8::internal::ConcurrentMarking::FlushMemoryChunkData(), and v8::internal::MarkingBarrier::PublishIfNeeded().
Remove()
template<RememberedSetType type>
static void v8::internal::RememberedSet< type >::Remove (MutablePageMetadata * chunk, Address slot_addr) [inline], [static]
Definition at line 162 of file remembered-set.h.
                                                                    {
    DCHECK(chunk->Contains(slot_addr));
    SlotSet* slot_set = chunk->slot_set<type>();
    RememberedSetOperations::Remove(slot_set, chunk, slot_addr);
  }
References v8::internal::MemoryChunkMetadata::Contains(), v8::internal::DCHECK(), v8::internal::RememberedSetOperations::Remove(), v8::internal::MutablePageMetadata::slot_set(), and v8::internal::tracing::type.
RemoveRange()
template<RememberedSetType type>
static void v8::internal::RememberedSet< type >::RemoveRange (MutablePageMetadata * chunk, Address start, Address end, SlotSet::EmptyBucketMode mode) [inline], [static]
Definition at line 170 of file remembered-set.h.
                                                                    {
    SlotSet* slot_set = chunk->slot_set<type>();
    RememberedSetOperations::RemoveRange(slot_set, chunk, start, end, mode);
  }
References v8::internal::compiler::end(), mode(), v8::internal::RememberedSetOperations::RemoveRange(), v8::internal::MutablePageMetadata::slot_set(), and v8::internal::tracing::type.
Referenced by v8::internal::Sweeper::CleanupRememberedSetEntriesForFreedMemory(), v8::internal::LargePageMetadata::ClearOutOfLiveRangeSlots(), v8::internal::Heap::ClearRecordedSlotRange(), and v8::internal::Heap::NotifyObjectLayoutChange().
RemoveRangeTyped()
template<RememberedSetType type>
static void v8::internal::RememberedSet< type >::RemoveRangeTyped (MutablePageMetadata * page, Address start, Address end) [inline], [static]
Definition at line 263 of file remembered-set.h.
                                            {
    TypedSlotSet* slot_set = page->typed_slot_set<type>();
    if (slot_set != nullptr) {
      slot_set->Iterate(
          [=](SlotType slot_type, Address slot_addr) {
            return start <= slot_addr && slot_addr < end ? REMOVE_SLOT
                                                         : KEEP_SLOT;
          },
          TypedSlotSet::FREE_EMPTY_CHUNKS);
    }
  }
References v8::internal::compiler::end(), v8::internal::TypedSlotSet::FREE_EMPTY_CHUNKS, v8::internal::TypedSlotSet::Iterate(), heap::base::KEEP_SLOT, heap::base::REMOVE_SLOT, v8::internal::tracing::type, and v8::internal::MutablePageMetadata::typed_slot_set().
Referenced by v8::internal::LargePageMetadata::ClearOutOfLiveRangeSlots().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/remembered-set.h