v8::internal::ICStats Class Reference
#include <ic-stats.h>
Public Member Functions
ICStats ()
void Dump ()
void Begin ()
void End ()
void Reset ()
ICInfo & Current ()
const char * GetOrCacheScriptName (Tagged< Script > script)
const char * GetOrCacheFunctionName (IsolateForSandbox isolate, Tagged< JSFunction > function)
Static Public Member Functions
static ICStats * instance ()
Public Attributes
const int MAX_IC_INFO = 4096
Private Attributes
base::Atomic32 enabled_
std::vector< ICInfo > ic_infos_
std::unordered_map< Address, std::unique_ptr< char[]> > script_name_map_
std::unordered_map< Address, std::unique_ptr< char[]> > function_name_map_
int pos_
Static Private Attributes
static base::LazyInstance< ICStats >::type instance_
Detailed Description
Definition at line 53 of file ic-stats.h.
Constructor & Destructor Documentation
ICStats()
v8::internal::ICStats::ICStats ()
Definition at line 19 of file ic-stats.cc.
                 : ic_infos_(MAX_IC_INFO), pos_(0) {
  base::Relaxed_Store(&enabled_, 0);
}
References enabled_, and v8::base::Relaxed_Store().
Member Function Documentation
Begin()
void v8::internal::ICStats::Begin ()
Definition at line 23 of file ic-stats.cc.
                    {
  if (V8_LIKELY(!TracingFlags::is_ic_stats_enabled())) return;
  base::Relaxed_Store(&enabled_, 1);
}
References enabled_, v8::internal::TracingFlags::is_ic_stats_enabled(), v8::base::Relaxed_Store(), and V8_LIKELY.
Referenced by v8::internal::IC::TraceIC().
Current()
ICInfo& v8::internal::ICStats::Current () [inline]
Definition at line 62 of file ic-stats.h.
                              {
    DCHECK(pos_ >= 0 && pos_ < MAX_IC_INFO);
    return ic_infos_[pos_];
  }
References v8::internal::DCHECK(), ic_infos_, MAX_IC_INFO, and pos_.
Referenced by v8::internal::IC::TraceIC().
Dump()
void v8::internal::ICStats::Dump ()
Definition at line 44 of file ic-stats.cc.
                   {
  auto value = v8::tracing::TracedValue::Create();
  value->BeginArray("data");
  for (int i = 0; i < pos_; ++i) {
    ic_infos_[i].AppendToTracedValue(value.get());
  }
  value->EndArray();
  TRACE_EVENT_INSTANT1(TRACE_DISABLED_BY_DEFAULT("v8.ic_stats"), "V8.ICStats",
                       TRACE_EVENT_SCOPE_THREAD, "ic-stats", std::move(value));
  Reset();
}
References v8::tracing::TracedValue::Create(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, ic_infos_, pos_, Reset(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_INSTANT1, TRACE_EVENT_SCOPE_THREAD, and v8::internal::value.
Referenced by End().
End()
void v8::internal::ICStats::End ()
Definition at line 28 of file ic-stats.cc.
                  {
  if (base::Relaxed_Load(&enabled_) != 1) return;
  ++pos_;
  if (pos_ == MAX_IC_INFO) {
    Dump();
  }
  base::Relaxed_Store(&enabled_, 0);
}
References Dump(), enabled_, MAX_IC_INFO, pos_, v8::base::Relaxed_Load(), and v8::base::Relaxed_Store().
Referenced by v8::internal::IC::TraceIC().
GetOrCacheFunctionName()
const char * v8::internal::ICStats::GetOrCacheFunctionName (IsolateForSandbox isolate, Tagged< JSFunction > function)
Definition at line 75 of file ic-stats.cc.
                                                                         {
  Address function_ptr = function.ptr();
  // Lookup the function name or add a null unique_ptr if no entry exists.
  std::unique_ptr<char[]>& function_name = function_name_map_[function_ptr];
  if (!function_name) {
    ic_infos_[pos_].is_optimized = function->HasAttachedOptimizedCode(isolate);
    // Update the map entry with the actual debug name.
    function_name = function->shared()->DebugNameCStr();
  }
  return function_name.get();
}
References function_name_map_, ic_infos_, and pos_.
GetOrCacheScriptName()
const char * v8::internal::ICStats::GetOrCacheScriptName (Tagged< Script > script)
Definition at line 57 of file ic-stats.cc.
                                                               {
  Address script_ptr = script.ptr();
  if (script_name_map_.find(script_ptr) != script_name_map_.end()) {
    return script_name_map_[script_ptr].get();
  }
  Tagged<Object> script_name_raw = script->name();
  if (IsString(script_name_raw)) {
    Tagged<String> script_name = Cast<String>(script_name_raw);
    char* c_script_name = script_name->ToCString().release();
    script_name_map_.insert(
        std::make_pair(script_ptr, std::unique_ptr<char[]>(c_script_name)));
    return c_script_name;
  }
  script_name_map_.insert(
      std::make_pair(script_ptr, std::unique_ptr<char[]>(nullptr)));
  return nullptr;
}
References v8::internal::script, and script_name_map_.
instance()
static ICStats* v8::internal::ICStats::instance () [inline], [static]
Definition at line 69 of file ic-stats.h.
{ return instance_.Pointer(); }
References instance_.
Referenced by v8::internal::JavaScriptFrame::CollectFunctionAndOffsetForICStats(), and v8::internal::IC::TraceIC().
Reset()
void v8::internal::ICStats::Reset ()
Definition at line 37 of file ic-stats.cc.
                    {
  for (auto& ic_info : ic_infos_) {
    ic_info.Reset();
  }
  pos_ = 0;
}
References ic_infos_, and pos_.
Referenced by Dump().
Member Data Documentation
enabled_
base::Atomic32 v8::internal::ICStats::enabled_ [private]
Definition at line 73 of file ic-stats.h.
Referenced by Begin(), End(), and ICStats().
function_name_map_
std::unordered_map<Address, std::unique_ptr<char[]> > v8::internal::ICStats::function_name_map_ [private]
Definition at line 78 of file ic-stats.h.
Referenced by GetOrCacheFunctionName().
ic_infos_
std::vector<ICInfo> v8::internal::ICStats::ic_infos_ [private]
Definition at line 74 of file ic-stats.h.
Referenced by Current(), Dump(), GetOrCacheFunctionName(), and Reset().
instance_
base::LazyInstance< ICStats >::type v8::internal::ICStats::instance_ [static], [private]
Initial value:
=
    LAZY_INSTANCE_INITIALIZER
Definition at line 72 of file ic-stats.h.
Referenced by instance().
MAX_IC_INFO
const int v8::internal::ICStats::MAX_IC_INFO = 4096
Definition at line 55 of file ic-stats.h.
Referenced by Current(), and End().
pos_
int v8::internal::ICStats::pos_ [private]
Definition at line 79 of file ic-stats.h.
Referenced by Current(), Dump(), End(), GetOrCacheFunctionName(), and Reset().
script_name_map_
std::unordered_map<Address, std::unique_ptr<char[]> > v8::internal::ICStats::script_name_map_ [private]
Definition at line 76 of file ic-stats.h.
Referenced by GetOrCacheScriptName().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/ic-stats.h
/mnt/V8SourceCode/src/ic/ic-stats.cc