v8::internal::torque::SourceFileMap Class Reference
#include <source-positions.h>
Public Member Functions
SourceFileMap (std::string v8_root)
Static Public Member Functions
static const std::string & PathFromV8Root (SourceId file)
static std::string PathFromV8RootWithoutExtension (SourceId file)
static std::string AbsolutePath (SourceId file)
static SourceId AddSource (std::string path)
static SourceId GetSourceId (const std::string &path)
static std::vector< SourceId > AllSources ()
static bool FileRelativeToV8RootExists (const std::string &path)
Private Attributes
std::vector< std::string > sources_
std::string v8_root_
Additional Inherited Members
Detailed Description
Definition at line 89 of file source-positions.h.
Constructor & Destructor Documentation
SourceFileMap()
v8::internal::torque::SourceFileMap::SourceFileMap (std::string v8_root) [inline], [explicit]
Definition at line 92 of file source-positions.h.
: v8_root_(std::move(v8_root)) {}
Member Function Documentation
AbsolutePath()
std::string v8::internal::torque::SourceFileMap::AbsolutePath (SourceId file) [static]
Definition at line 24 of file source-positions.cc.
                                                   {
  const std::string& root_path = PathFromV8Root(file);
  if (StringStartsWith(root_path, "file://")) return root_path;
  return Get().v8_root_ + "/" + PathFromV8Root(file);
}
References file(), v8::base::ContextualVariable< Derived, VarType >::Get(), PathFromV8Root(), v8::internal::string, and v8::internal::torque::StringStartsWith().
Referenced by v8::internal::torque::CCGenerator::EmitSourcePosition(), v8::internal::torque::CSAGenerator::EmitSourcePosition(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::DiagnosticCollector::GetOrCreateNotificationForSource(), v8::internal::torque::anonymous_namespace{torque-compiler.cc}::ReadAndParseTorqueFile(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::ResetCompilationErrorDiagnostics(), and v8::internal::torque::ls::Location::SetTo().
AddSource()
SourceId v8::internal::torque::SourceFileMap::AddSource (std::string path) [static]
Definition at line 41 of file source-positions.cc.
                                                {
  Get().sources_.push_back(std::move(path));
  return SourceId(static_cast<int>(Get().sources_.size()) - 1);
}
References v8::base::ContextualVariable< Derived, VarType >::Get(), and sources_.
Referenced by v8::internal::torque::CompileTorque(), v8::internal::torque::CompileTorqueForKythe(), v8::internal::torque::ls::ParseJson(), and v8::internal::torque::anonymous_namespace{torque-compiler.cc}::ReadAndParseTorqueFile().
AllSources()
std::vector< SourceId > v8::internal::torque::SourceFileMap::AllSources () [static]
Definition at line 57 of file source-positions.cc.
                                              {
  SourceFileMap& self = Get();
  std::vector<SourceId> result;
  result.reserve(static_cast<int>(self.sources_.size()));
  for (int i = 0; i < static_cast<int>(self.sources_.size()); ++i) {
    result.push_back(SourceId(i));
  }
  return result;
}
References v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::base::internal::result, and sources_.
Referenced by v8::internal::torque::ImplementationVisitor::BeginGeneratedFiles(), v8::internal::torque::ImplementationVisitor::EndGeneratedFiles(), and v8::internal::torque::ImplementationVisitor::GenerateImplementation().
FileRelativeToV8RootExists()
bool v8::internal::torque::SourceFileMap::FileRelativeToV8RootExists (const std::string & path) [static]
Definition at line 68 of file source-positions.cc.
                                                                    {
  const std::string file = Get().v8_root_ + "/" + path;
  std::ifstream stream(file);
  return stream.good();
}
References file(), v8::base::ContextualVariable< Derived, VarType >::Get(), and v8::internal::string.
GetSourceId()
SourceId v8::internal::torque::SourceFileMap::GetSourceId (const std::string & path) [static]
Definition at line 47 of file source-positions.cc.
                                                         {
  for (size_t i = 0; i < Get().sources_.size(); ++i) {
    if (Get().sources_[i] == path) {
      return SourceId(static_cast<int>(i));
    }
  }
  return SourceId::Invalid();
}
References v8::base::ContextualVariable< Derived, VarType >::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::torque::SourceId::Invalid().
Referenced by v8::internal::torque::ClassType::AttributedToFile(), v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleDocumentSymbolRequest(), and v8::internal::torque::ls::anonymous_namespace{message-handler.cc}::HandleGotoDefinitionRequest().
PathFromV8Root()
const std::string & v8::internal::torque::SourceFileMap::PathFromV8Root (SourceId file) [static]
Definition at line 18 of file source-positions.cc.
                                                            {
  CHECK(file.IsValid());
  return Get().sources_[file.id_];
}
References CHECK, file(), and v8::base::ContextualVariable< Derived, VarType >::Get().
Referenced by AbsolutePath(), v8::internal::torque::ClassType::AttributedToFile(), v8::internal::torque::ImplementationVisitor::BeginGeneratedFiles(), v8::internal::torque::ImplementationVisitor::EndGeneratedFiles(), v8::internal::torque::anonymous_namespace{kythe-data.cc}::MakeKythePosition(), v8::internal::torque::operator<<(), PathFromV8RootWithoutExtension(), and v8::internal::torque::PositionAsString().
PathFromV8RootWithoutExtension()
std::string v8::internal::torque::SourceFileMap::PathFromV8RootWithoutExtension (SourceId file) [static]
Definition at line 31 of file source-positions.cc.
                                                                     {
  std::string path_from_root = PathFromV8Root(file);
  if (!StringEndsWith(path_from_root, ".tq")) {
    Error("Not a .tq file: ", path_from_root).Throw();
  }
  path_from_root.resize(path_from_root.size() - strlen(".tq"));
  return path_from_root;
}
References v8::internal::torque::Error(), file(), PathFromV8Root(), v8::internal::string, v8::internal::torque::StringEndsWith(), and v8::internal::torque::MessageBuilder::Throw().
Referenced by v8::internal::torque::ImplementationVisitor::BeginGeneratedFiles(), and v8::internal::torque::ImplementationVisitor::GenerateImplementation().
Member Data Documentation
sources_
std::vector<std::string> v8::internal::torque::SourceFileMap::sources_ [private]
Definition at line 102 of file source-positions.h.
Referenced by AddSource(), and AllSources().
v8_root_
std::string v8::internal::torque::SourceFileMap::v8_root_ [private]
Definition at line 103 of file source-positions.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/source-positions.h
/mnt/V8SourceCode/src/torque/source-positions.cc