v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror Class Reference
Public Member Functions
BigIntMirror (v8::Isolate *isolate, v8::Local< v8::BigInt > value)
Response buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions &wrapOptions, std::unique_ptr< RemoteObject > *result) const override
void buildPropertyPreview (v8::Local< v8::Context > context, const String16 &name, std::unique_ptr< protocol::Runtime::PropertyPreview > *preview) const override
void buildEntryPreview (v8::Local< v8::Context > context, int *nameLimit, int *indexLimit, std::unique_ptr< protocol::Runtime::ObjectPreview > *preview) const override
Response buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker &duplicateTracker, std::unique_ptr< protocol::DictionaryValue > *result) const override
Additional Inherited Members
Detailed Description
Definition at line 676 of file value-mirror.cc.
Constructor & Destructor Documentation
BigIntMirror()
v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::BigIntMirror (v8::Isolate * isolate, v8::Local< v8::BigInt > value) [inline]
Definition at line 678 of file value-mirror.cc.
      : ValueMirrorBase(isolate, value) {}
Member Function Documentation
buildDeepSerializedValue()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildDeepSerializedValue (v8::Local< v8::Context > context, int maxDepth, v8::Local< v8::Object > additionalParameters, V8SerializationDuplicateTracker & duplicateTracker, std::unique_ptr< protocol::DictionaryValue > * result) const [inline], [override], [virtual]
Implements v8_inspector::ValueMirror.
Definition at line 725 of file value-mirror.cc.
                                                                     {
    v8::Local<v8::BigInt> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::BigInt>();
    v8::Local<v8::String> stringValue =
        v8::debug::GetBigIntStringValue(v8::Isolate::GetCurrent(), value);
    *result = protocol::DictionaryValue::create();
    (*result)->setString(
        "type", protocol::Runtime::DeepSerializedValue::TypeEnum::Bigint);
    (*result)->setValue("value", protocol::StringValue::create(toProtocolString(
                                     v8::Isolate::GetCurrent(), stringValue)));
    return Response::Success();
  }
References v8::debug::GetBigIntStringValue(), v8::Isolate::GetCurrent(), v8::base::internal::result, v8_inspector::toProtocolString(), and v8::internal::value.
buildEntryPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildEntryPreview (v8::Local< v8::Context > context, int * nameLimit, int * indexLimit, std::unique_ptr< protocol::Runtime::ObjectPreview > * preview) const [inline], [override], [virtual]
Reimplemented from v8_inspector::ValueMirror.
Definition at line 709 of file value-mirror.cc.
                                                     {
    v8::Local<v8::BigInt> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::BigInt>();
    *preview =
        ObjectPreview::create()
            .setType(RemoteObject::TypeEnum::Bigint)
            .setDescription(
                abbreviateString(descriptionForBigInt(context, value), kMiddle))
            .setOverflow(false)
            .setProperties(std::make_unique<protocol::Array<PropertyPreview>>())
            .build();
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::abbreviateString(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForBigInt(), v8::Isolate::GetCurrent(), v8_inspector::anonymous_namespace{value-mirror.cc}::kMiddle, and v8::internal::value.
buildPropertyPreview()
void v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildPropertyPreview (v8::Local< v8::Context > context, const String16 & name, std::unique_ptr< protocol::Runtime::PropertyPreview > * preview) const [inline], [override], [virtual]
Reimplemented from v8_inspector::ValueMirror.
Definition at line 695 of file value-mirror.cc.
                                                        {
    v8::Local<v8::BigInt> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::BigInt>();
    *preview = PropertyPreview::create()
                   .setName(name)
                   .setType(RemoteObject::TypeEnum::Bigint)
                   .setValue(abbreviateString(
                       descriptionForBigInt(context, value), kMiddle))
                   .build();
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::abbreviateString(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForBigInt(), v8::Isolate::GetCurrent(), v8_inspector::anonymous_namespace{value-mirror.cc}::kMiddle, name, and v8::internal::value.
buildRemoteObject()
Response v8_inspector::anonymous_namespace{value-mirror.cc}::BigIntMirror::buildRemoteObject (v8::Local< v8::Context > context, const WrapOptions & wrapOptions, std::unique_ptr< RemoteObject > * result) const [inline], [override]
Definition at line 681 of file value-mirror.cc.
                                                          {
    v8::Local<v8::BigInt> value =
        v8Value(v8::Isolate::GetCurrent()).As<v8::BigInt>();
    String16 description = descriptionForBigInt(context, value);
    *result = RemoteObject::create()
                  .setType(RemoteObject::TypeEnum::Bigint)
                  .setUnserializableValue(description)
                  .setDescription(abbreviateString(description, kMiddle))
                  .build();
    return Response::Success();
  }
References v8_inspector::anonymous_namespace{value-mirror.cc}::abbreviateString(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForBigInt(), v8::Isolate::GetCurrent(), v8_inspector::anonymous_namespace{value-mirror.cc}::kMiddle, v8::base::internal::result, and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/inspector/value-mirror.cc