v8::internal::IsolateSafepoint Class Reference
#include <safepoint.h>
Classes
class Barrier
struct RunningLocalHeap
Public Member Functions
IsolateSafepoint (Heap *heap)
void Iterate (RootVisitor *visitor)
template<typename Callback >
void IterateLocalHeaps (Callback callback)
void AssertActive ()
V8_EXPORT_PRIVATE void AssertMainThreadIsOnlyThread ()
Private Types
enum class IncludeMainThread { kYes
, kNo
 }
using RunningLocalHeaps = base::SmallVector< RunningLocalHeap, 4 >
Private Member Functions
void WaitInUnpark ()
void WaitInSafepoint ()
void NotifyPark ()
void EnterLocalSafepointScope ()
void LeaveLocalSafepointScope ()
void TryInitiateGlobalSafepointScope (Isolate *initiator, PerClientSafepointData *client_data)
void InitiateGlobalSafepointScope (Isolate *initiator, PerClientSafepointData *client_data)
void InitiateGlobalSafepointScopeRaw (Isolate *initiator, PerClientSafepointData *client_data)
void LeaveGlobalSafepointScope (Isolate *initiator)
void WaitUntilRunningThreadsInSafepoint (const PerClientSafepointData *client_data)
IncludeMainThread ShouldIncludeMainThread (Isolate *initiator)
void LockMutex (LocalHeap *local_heap)
void SetSafepointRequestedFlags (IncludeMainThread include_main_thread, IsolateSafepoint::RunningLocalHeaps &running_local_heaps)
void ClearSafepointRequestedFlags (IncludeMainThread include_main_thread)
template<typename Callback >
void AddLocalHeap (LocalHeap *local_heap, Callback callback)
template<typename Callback >
void RemoveLocalHeap (LocalHeap *local_heap, Callback callback)
Isolate * isolate () const
Isolate * shared_space_isolate () const
Private Attributes
Barrier barrier_
Heap * heap_
base::RecursiveMutex local_heaps_mutex_
LocalHeap * local_heaps_head_ = nullptr
int active_safepoint_scopes_ = 0
Friends
class GlobalSafepoint
class GlobalSafepointScope
class Isolate
class IsolateSafepointScope
class LocalHeap
class PerClientSafepointData
Detailed Description
Definition at line 28 of file safepoint.h.
Member Typedef Documentation
RunningLocalHeaps
using v8::internal::IsolateSafepoint::RunningLocalHeaps = base::SmallVector<RunningLocalHeap, 4> [private]
Definition at line 57 of file safepoint.h.
Member Enumeration Documentation
IncludeMainThread
enum v8::internal::IsolateSafepoint::IncludeMainThread [strong], [private]
Enumerator
kYes
kNo
Definition at line 82 of file safepoint.h.
{ kYes, kNo };
Constructor & Destructor Documentation
IsolateSafepoint()
v8::internal::IsolateSafepoint::IsolateSafepoint (Heap * heap) [explicit]
Definition at line 29 of file safepoint.cc.
: heap_(heap) {}
Member Function Documentation
AddLocalHeap()
template<typename Callback >
void v8::internal::IsolateSafepoint::AddLocalHeap (LocalHeap * local_heap, Callback callback) [inline], [private]
Definition at line 120 of file safepoint.h.
                                                              {
    // Safepoint holds this lock in order to stop threads from starting or
    // stopping.
    base::RecursiveMutexGuard guard(&local_heaps_mutex_);
    // Additional code protected from safepoint
    callback();
    // Add list to doubly-linked list
    if (local_heaps_head_) local_heaps_head_->prev_ = local_heap;
    local_heap->prev_ = nullptr;
    local_heap->next_ = local_heaps_head_;
    local_heaps_head_ = local_heap;
  }
References local_heaps_head_, local_heaps_mutex_, v8::internal::LocalHeap::next_, and v8::internal::LocalHeap::prev_.
Referenced by v8::internal::LocalHeap::LocalHeap().
AssertActive()
void v8::internal::IsolateSafepoint::AssertActive () [inline]
Definition at line 45 of file safepoint.h.
{ local_heaps_mutex_.AssertHeld(); }
References v8::base::RecursiveMutex::AssertHeld(), and local_heaps_mutex_.
Referenced by v8::internal::StringTable::DropOldData(), v8::internal::Heap::GarbageCollectionEpilogueInSafepoint(), Iterate(), v8::internal::PersistentHandlesList::Iterate(), v8::internal::StringTable::IterateElements(), IterateLocalHeaps(), v8::internal::String::MakeExternalDuringGC(), v8::internal::StringTable::NotifyElementsRemoved(), v8::internal::StringForwardingTable::Reset(), and v8::internal::LocalHeap::SetUpSharedMarking().
AssertMainThreadIsOnlyThread()
void v8::internal::IsolateSafepoint::AssertMainThreadIsOnlyThread ()
Definition at line 304 of file safepoint.cc.
                                                    {
  DCHECK_EQ(local_heaps_head_, heap_->main_thread_local_heap());
  DCHECK_NULL(heap_->main_thread_local_heap()->next_);
}
References DCHECK_EQ, DCHECK_NULL, heap_, local_heaps_head_, v8::internal::Heap::main_thread_local_heap(), and v8::internal::LocalHeap::next_.
Referenced by v8::internal::Isolate::Deinit(), v8::internal::Heap::NotifyDeserializationComplete(), v8::internal::Heap::TearDown(), and v8::internal::Heap::TearDownWithSharedHeap().
ClearSafepointRequestedFlags()
void v8::internal::IsolateSafepoint::ClearSafepointRequestedFlags (IncludeMainThread include_main_thread) [private]
Definition at line 201 of file safepoint.cc.
                                           {
  for (LocalHeap* local_heap = local_heaps_head_; local_heap;
       local_heap = local_heap->next_) {
    if (local_heap->is_main_thread() &&
        include_main_thread == IncludeMainThread::kNo) {
      continue;
    }
    const LocalHeap::ThreadState old_state =
        local_heap->state_.ClearSafepointRequested();
    CHECK(old_state.IsParked());
    CHECK(old_state.IsSafepointRequested());
    CHECK_IMPLIES(old_state.IsCollectionRequested(),
                  local_heap->is_main_thread());
  }
}
References CHECK, CHECK_IMPLIES, v8::internal::LocalHeap::ThreadState::IsCollectionRequested(), v8::internal::LocalHeap::ThreadState::IsParked(), v8::internal::LocalHeap::ThreadState::IsSafepointRequested(), kNo, local_heaps_head_, and v8::internal::LocalHeap::next_.
Referenced by LeaveGlobalSafepointScope(), and LeaveLocalSafepointScope().
EnterLocalSafepointScope()
void v8::internal::IsolateSafepoint::EnterLocalSafepointScope () [private]
Definition at line 31 of file safepoint.cc.
                                                {
  // Safepoints need to be initiated on some main thread.
  DCHECK_NULL(LocalHeap::Current());
  DCHECK(AllowGarbageCollection::IsAllowed());
  LockMutex(isolate()->main_thread_local_heap());
  if (++active_safepoint_scopes_ > 1) return;
  // Local safepoint can only be initiated on the isolate's main thread.
  DCHECK_EQ(ThreadId::Current(), isolate()->thread_id());
  TimedHistogramScope timer(isolate()->counters()->gc_time_to_safepoint());
  TRACE_GC(heap_->tracer(), GCTracer::Scope::TIME_TO_SAFEPOINT);
  barrier_.Arm();
  RunningLocalHeaps running_local_heaps;
  SetSafepointRequestedFlags(IncludeMainThread::kNo, running_local_heaps);
  barrier_.WaitUntilRunningThreadsInSafepoint(running_local_heaps);
}
References active_safepoint_scopes_, v8::internal::IsolateSafepoint::Barrier::Arm(), barrier_, v8::internal::ThreadId::Current(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, heap_, isolate(), kNo, LockMutex(), SetSafepointRequestedFlags(), v8::internal::anonymous_namespace{thread-id.cc}::thread_id, TRACE_GC, v8::internal::Heap::tracer(), and v8::internal::IsolateSafepoint::Barrier::WaitUntilRunningThreadsInSafepoint().
Referenced by v8::internal::IsolateSafepointScope::IsolateSafepointScope().
InitiateGlobalSafepointScope()
void v8::internal::IsolateSafepoint::InitiateGlobalSafepointScope (Isolate * initiator, PerClientSafepointData * client_data) [private]
Definition at line 74 of file safepoint.cc.
                                                             {
  shared_space_isolate()->global_safepoint()->AssertActive();
  LockMutex(initiator->main_thread_local_heap());
  InitiateGlobalSafepointScopeRaw(initiator, client_data);
}
References v8::internal::GlobalSafepoint::AssertActive(), v8::internal::Isolate::global_safepoint(), InitiateGlobalSafepointScopeRaw(), LockMutex(), v8::internal::Isolate::main_thread_local_heap(), and shared_space_isolate().
InitiateGlobalSafepointScopeRaw()
void v8::internal::IsolateSafepoint::InitiateGlobalSafepointScopeRaw (Isolate * initiator, PerClientSafepointData * client_data) [private]
Definition at line 105 of file safepoint.cc.
                                                             {
  CHECK_EQ(++active_safepoint_scopes_, 1);
  barrier_.Arm();
  SetSafepointRequestedFlags(ShouldIncludeMainThread(initiator),
                             client_data->running());
  client_data->set_locked();
  if (isolate() != initiator) {
    // An isolate might be waiting in the event loop. Post a task in order to
    // wake it up.
    isolate()->heap()->GetForegroundTaskRunner()->PostTask(
        std::make_unique<GlobalSafepointInterruptTask>(heap_));
    // Request an interrupt in case of long-running code.
    isolate()->stack_guard()->RequestGlobalSafepoint();
  }
}
References active_safepoint_scopes_, v8::internal::IsolateSafepoint::Barrier::Arm(), barrier_, CHECK_EQ, v8::internal::Heap::GetForegroundTaskRunner(), v8::internal::Isolate::heap(), heap_, isolate(), v8::internal::PerClientSafepointData::running(), v8::internal::PerClientSafepointData::set_locked(), SetSafepointRequestedFlags(), ShouldIncludeMainThread(), and v8::internal::Isolate::stack_guard().
Referenced by InitiateGlobalSafepointScope(), and TryInitiateGlobalSafepointScope().
isolate()
Isolate * v8::internal::IsolateSafepoint::isolate () const [private]
Definition at line 309 of file safepoint.cc.
{ return heap_->isolate(); }
References heap_, and v8::internal::Heap::isolate().
Referenced by EnterLocalSafepointScope(), InitiateGlobalSafepointScopeRaw(), shared_space_isolate(), and ShouldIncludeMainThread().
Iterate()
void v8::internal::IsolateSafepoint::Iterate (RootVisitor * visitor)
Definition at line 296 of file safepoint.cc.
                                                   {
  AssertActive();
  for (LocalHeap* current = local_heaps_head_; current;
       current = current->next_) {
    current->Iterate(visitor);
  }
}
References AssertActive(), local_heaps_head_, and v8::internal::LocalHeap::next_.
IterateLocalHeaps()
template<typename Callback >
void v8::internal::IsolateSafepoint::IterateLocalHeaps (Callback callback) [inline]
Definition at line 37 of file safepoint.h.
                                            {
    AssertActive();
    for (LocalHeap* current = local_heaps_head_; current;
         current = current->next_) {
      callback(current);
    }
  }
References AssertActive(), local_heaps_head_, and v8::internal::LocalHeap::next_.
Referenced by v8::internal::Heap::FreeLinearAllocationAreas(), v8::internal::Heap::FreeSharedLinearAllocationAreasAndResetFreeLists(), v8::internal::Heap::GarbageCollectionEpilogueInSafepoint(), v8::internal::Heap::MakeLinearAllocationAreasIterable(), v8::internal::Heap::MarkSharedLinearAllocationAreasBlack(), v8::internal::IncrementalMarking::PauseBlackAllocation(), v8::internal::IncrementalMarking::StartBlackAllocation(), and v8::internal::Heap::UnmarkSharedLinearAllocationAreas().
LeaveGlobalSafepointScope()
void v8::internal::IsolateSafepoint::LeaveGlobalSafepointScope (Isolate * initiator) [private]
Definition at line 181 of file safepoint.cc.
                                                                   {
  local_heaps_mutex_.AssertHeld();
  CHECK_EQ(--active_safepoint_scopes_, 0);
  ClearSafepointRequestedFlags(ShouldIncludeMainThread(initiator));
  barrier_.Disarm();
  local_heaps_mutex_.Unlock();
}
References active_safepoint_scopes_, v8::base::RecursiveMutex::AssertHeld(), barrier_, CHECK_EQ, ClearSafepointRequestedFlags(), v8::internal::IsolateSafepoint::Barrier::Disarm(), local_heaps_mutex_, ShouldIncludeMainThread(), and v8::base::RecursiveMutex::Unlock().
LeaveLocalSafepointScope()
void v8::internal::IsolateSafepoint::LeaveLocalSafepointScope () [private]
Definition at line 189 of file safepoint.cc.
                                                {
  local_heaps_mutex_.AssertHeld();
  DCHECK_GT(active_safepoint_scopes_, 0);
  if (--active_safepoint_scopes_ == 0) {
    ClearSafepointRequestedFlags(IncludeMainThread::kNo);
    barrier_.Disarm();
  }
  local_heaps_mutex_.Unlock();
}
References active_safepoint_scopes_, v8::base::RecursiveMutex::AssertHeld(), barrier_, ClearSafepointRequestedFlags(), DCHECK_GT, v8::internal::IsolateSafepoint::Barrier::Disarm(), kNo, local_heaps_mutex_, and v8::base::RecursiveMutex::Unlock().
Referenced by v8::internal::IsolateSafepointScope::~IsolateSafepointScope().
LockMutex()
void v8::internal::IsolateSafepoint::LockMutex (LocalHeap * local_heap) [private]
Definition at line 172 of file safepoint.cc.
                                                      {
  if (!local_heaps_mutex_.TryLock()) {
    // Safepoints are only used for GCs, so GC requests should be ignored by
    // default when parking for a safepoint.
    IgnoreLocalGCRequests ignore_gc_requests(local_heap->heap());
    local_heap->ExecuteWhileParked([this]() { local_heaps_mutex_.Lock(); });
  }
}
References v8::internal::LocalHeap::ExecuteWhileParked(), v8::internal::LocalHeap::heap(), local_heaps_mutex_, v8::base::RecursiveMutex::Lock(), and v8::base::RecursiveMutex::TryLock().
Referenced by EnterLocalSafepointScope(), and InitiateGlobalSafepointScope().
NotifyPark()
void v8::internal::IsolateSafepoint::NotifyPark () [private]
Definition at line 224 of file safepoint.cc.
{ barrier_.NotifyPark(); }
References barrier_, and v8::internal::IsolateSafepoint::Barrier::NotifyPark().
Referenced by v8::internal::LocalHeap::ParkSlowPath().
RemoveLocalHeap()
template<typename Callback >
void v8::internal::IsolateSafepoint::RemoveLocalHeap (LocalHeap * local_heap, Callback callback) [inline], [private]
Definition at line 136 of file safepoint.h.
                                                                 {
    base::RecursiveMutexGuard guard(&local_heaps_mutex_);
    // Additional code protected from safepoint
    callback();
    // Remove list from doubly-linked list
    if (local_heap->next_) local_heap->next_->prev_ = local_heap->prev_;
    if (local_heap->prev_)
      local_heap->prev_->next_ = local_heap->next_;
    else
      local_heaps_head_ = local_heap->next_;
  }
References local_heaps_head_, local_heaps_mutex_, v8::internal::LocalHeap::next_, and v8::internal::LocalHeap::prev_.
Referenced by v8::internal::LocalHeap::~LocalHeap().
SetSafepointRequestedFlags()
void v8::internal::IsolateSafepoint::SetSafepointRequestedFlags (IncludeMainThread include_main_thread, IsolateSafepoint::RunningLocalHeaps & running_local_heaps) [private]
Definition at line 131 of file safepoint.cc.
                                                            {
  // There needs to be at least one LocalHeap for the main thread.
  DCHECK_NOT_NULL(local_heaps_head_);
  DCHECK(running_local_heaps.empty());
  for (LocalHeap* local_heap = local_heaps_head_; local_heap;
       local_heap = local_heap->next_) {
    if (local_heap->is_main_thread() &&
        include_main_thread == IncludeMainThread::kNo) {
      continue;
    }
    const LocalHeap::ThreadState old_state =
        local_heap->state_.SetSafepointRequested();
    if (old_state.IsRunning()) {
#if V8_OS_DARWIN
      pthread_override_t qos_override = nullptr;
      if (v8_flags.safepoint_bump_qos_class) {
        // Bump the quality-of-service class to prevent priority inversion (high
        // priority main thread blocking on lower priority background threads).
        qos_override = pthread_override_qos_class_start_np(
            local_heap->thread_handle(), QOS_CLASS_USER_INTERACTIVE, 0);
        CHECK_NOT_NULL(qos_override);
      }
      running_local_heaps.emplace_back(local_heap, qos_override);
#else
      running_local_heaps.emplace_back(local_heap);
#endif
    }
    CHECK_IMPLIES(old_state.IsCollectionRequested(),
                  local_heap->is_main_thread());
    CHECK(!old_state.IsSafepointRequested());
  }
}
References CHECK, CHECK_IMPLIES, CHECK_NOT_NULL, v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::base::SmallVector< T, kSize, Allocator >::emplace_back(), v8::base::SmallVector< T, kSize, Allocator >::empty(), v8::internal::LocalHeap::ThreadState::IsCollectionRequested(), v8::internal::LocalHeap::ThreadState::IsRunning(), v8::internal::LocalHeap::ThreadState::IsSafepointRequested(), kNo, local_heaps_head_, v8::internal::LocalHeap::next_, and v8::internal::v8_flags.
Referenced by EnterLocalSafepointScope(), and InitiateGlobalSafepointScopeRaw().
shared_space_isolate()
Isolate * v8::internal::IsolateSafepoint::shared_space_isolate () const [private]
Definition at line 311 of file safepoint.cc.
                                                      {
  return isolate()->shared_space_isolate();
}
References isolate(), and v8::internal::Isolate::shared_space_isolate().
Referenced by InitiateGlobalSafepointScope(), and TryInitiateGlobalSafepointScope().
ShouldIncludeMainThread()
IsolateSafepoint::IncludeMainThread v8::internal::IsolateSafepoint::ShouldIncludeMainThread (Isolate * initiator) [private]
Definition at line 125 of file safepoint.cc.
                        {
  const bool is_initiator = isolate() == initiator;
  return is_initiator ? IncludeMainThread::kNo : IncludeMainThread::kYes;
}
References isolate(), kNo, and kYes.
Referenced by InitiateGlobalSafepointScopeRaw(), and LeaveGlobalSafepointScope().
TryInitiateGlobalSafepointScope()
void v8::internal::IsolateSafepoint::TryInitiateGlobalSafepointScope (Isolate * initiator, PerClientSafepointData * client_data) [private]
Definition at line 81 of file safepoint.cc.
                                                             {
  shared_space_isolate()->global_safepoint()->AssertActive();
  if (!local_heaps_mutex_.TryLock()) return;
  InitiateGlobalSafepointScopeRaw(initiator, client_data);
}
References v8::internal::GlobalSafepoint::AssertActive(), v8::internal::Isolate::global_safepoint(), InitiateGlobalSafepointScopeRaw(), local_heaps_mutex_, shared_space_isolate(), and v8::base::RecursiveMutex::TryLock().
WaitInSafepoint()
void v8::internal::IsolateSafepoint::WaitInSafepoint () [private]
Definition at line 220 of file safepoint.cc.
{ barrier_.WaitInSafepoint(); }
References barrier_, and v8::internal::IsolateSafepoint::Barrier::WaitInSafepoint().
Referenced by v8::internal::LocalHeap::SleepInSafepoint().
WaitInUnpark()
void v8::internal::IsolateSafepoint::WaitInUnpark () [private]
Definition at line 222 of file safepoint.cc.
{ barrier_.WaitInUnpark(); }
References barrier_, and v8::internal::IsolateSafepoint::Barrier::WaitInUnpark().
Referenced by v8::internal::LocalHeap::SleepInUnpark().
WaitUntilRunningThreadsInSafepoint()
void v8::internal::IsolateSafepoint::WaitUntilRunningThreadsInSafepoint (const PerClientSafepointData * client_data) [private]
Definition at line 226 of file safepoint.cc.
                                               {
  barrier_.WaitUntilRunningThreadsInSafepoint(client_data->running());
}
References barrier_, v8::internal::PerClientSafepointData::running(), and v8::internal::IsolateSafepoint::Barrier::WaitUntilRunningThreadsInSafepoint().
Friends And Related Function Documentation
GlobalSafepoint
friend class GlobalSafepoint [friend]
Definition at line 163 of file safepoint.h.
GlobalSafepointScope
friend class GlobalSafepointScope [friend]
Definition at line 164 of file safepoint.h.
Isolate
friend class Isolate [friend]
Definition at line 165 of file safepoint.h.
IsolateSafepointScope
friend class IsolateSafepointScope [friend]
Definition at line 166 of file safepoint.h.
LocalHeap
friend class LocalHeap [friend]
Definition at line 167 of file safepoint.h.
PerClientSafepointData
friend class PerClientSafepointData [friend]
Definition at line 168 of file safepoint.h.
Member Data Documentation
active_safepoint_scopes_
int v8::internal::IsolateSafepoint::active_safepoint_scopes_ = 0 [private]
Definition at line 161 of file safepoint.h.
Referenced by EnterLocalSafepointScope(), InitiateGlobalSafepointScopeRaw(), LeaveGlobalSafepointScope(), and LeaveLocalSafepointScope().
barrier_
Barrier v8::internal::IsolateSafepoint::barrier_ [private]
Definition at line 153 of file safepoint.h.
Referenced by EnterLocalSafepointScope(), InitiateGlobalSafepointScopeRaw(), LeaveGlobalSafepointScope(), LeaveLocalSafepointScope(), NotifyPark(), WaitInSafepoint(), WaitInUnpark(), and WaitUntilRunningThreadsInSafepoint().
heap_
Heap* v8::internal::IsolateSafepoint::heap_ [private]
Definition at line 154 of file safepoint.h.
Referenced by AssertMainThreadIsOnlyThread(), EnterLocalSafepointScope(), InitiateGlobalSafepointScopeRaw(), and isolate().
local_heaps_head_
LocalHeap* v8::internal::IsolateSafepoint::local_heaps_head_ = nullptr [private]
Definition at line 159 of file safepoint.h.
Referenced by AddLocalHeap(), AssertMainThreadIsOnlyThread(), ClearSafepointRequestedFlags(), Iterate(), IterateLocalHeaps(), RemoveLocalHeap(), and SetSafepointRequestedFlags().
local_heaps_mutex_
base::RecursiveMutex v8::internal::IsolateSafepoint::local_heaps_mutex_ [private]
Definition at line 158 of file safepoint.h.
Referenced by AddLocalHeap(), AssertActive(), v8::internal::Isolate::Deinit(), LeaveGlobalSafepointScope(), LeaveLocalSafepointScope(), LockMutex(), RemoveLocalHeap(), and TryInitiateGlobalSafepointScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/safepoint.h
/mnt/V8SourceCode/src/heap/safepoint.cc