cppgc::internal::VirtualMemory Class Reference
#include <virtual-memory.h>
Public Member Functions
VirtualMemory ()=default
VirtualMemory (PageAllocator *, size_t size, size_t alignment, void *hint=nullptr)
~VirtualMemory () V8_NOEXCEPT
VirtualMemory (VirtualMemory &&) V8_NOEXCEPT
VirtualMemory & operator= (VirtualMemory &&) V8_NOEXCEPT
bool IsReserved () const
void * address () const
size_t size () const
Private Member Functions
void Reset ()
Private Attributes
PageAllocator * page_allocator_ = nullptr
void * start_ = nullptr
size_t size_ = 0
Detailed Description
Definition at line 17 of file virtual-memory.h.
Constructor & Destructor Documentation
VirtualMemory() [1/3]
cppgc::internal::VirtualMemory::VirtualMemory () [default]
VirtualMemory() [2/3]
cppgc::internal::VirtualMemory::VirtualMemory (PageAllocator * page_allocator, size_t size, size_t alignment, void * hint = nullptr)
Definition at line 13 of file virtual-memory.cc.
    : page_allocator_(page_allocator) {
  DCHECK_NOT_NULL(page_allocator);
  DCHECK(IsAligned(size, page_allocator->CommitPageSize()));
  const size_t page_size = page_allocator_->AllocatePageSize();
  start_ = page_allocator->AllocatePages(hint, RoundUp(size, page_size),
                                         RoundUp(alignment, page_size),
                                         PageAllocator::kNoAccess);
  if (start_) {
    size_ = RoundUp(size, page_size);
  }
}
References v8::PageAllocator::AllocatePages(), v8::PageAllocator::AllocatePageSize(), v8::PageAllocator::CommitPageSize(), DCHECK, DCHECK_NOT_NULL, IsAligned(), v8::PageAllocator::kNoAccess, page_allocator_, RoundUp(), size(), size_, and start_.
 VirtualMemory()
cppgc::internal::VirtualMemory::~VirtualMemory ()
Definition at line 28 of file virtual-memory.cc.
                                          {
  if (IsReserved()) {
    page_allocator_->FreePages(start_, size_);
  }
}
References v8::PageAllocator::FreePages(), IsReserved(), page_allocator_, size_, and start_.
VirtualMemory() [3/3]
cppgc::internal::VirtualMemory::VirtualMemory (VirtualMemory && other)
Definition at line 34 of file virtual-memory.cc.
    : page_allocator_(std::move(other.page_allocator_)),
      start_(std::move(other.start_)),
      size_(std::move(other.size_)) {
  other.Reset();
}
Member Function Documentation
address()
void* cppgc::internal::VirtualMemory::address () const [inline]
Definition at line 38 of file virtual-memory.h.
                        {
    DCHECK(IsReserved());
    return start_;
  }
References DCHECK.
Referenced by cppgc::internal::CagedHeap::CagedHeap().
IsReserved()
bool cppgc::internal::VirtualMemory::IsReserved () const [inline]
Definition at line 36 of file virtual-memory.h.
{ return start_ != nullptr; }
Referenced by cppgc::internal::anonymous_namespace{caged-heap.cc}::ReserveCagedHeap(), and ~VirtualMemory().
operator=()
VirtualMemory & cppgc::internal::VirtualMemory::operator= (VirtualMemory && other)
Definition at line 41 of file virtual-memory.cc.
                                                                         {
  DCHECK(!IsReserved());
  page_allocator_ = std::move(other.page_allocator_);
  start_ = std::move(other.start_);
  size_ = std::move(other.size_);
  other.Reset();
  return *this;
}
References DCHECK.
Reset()
void cppgc::internal::VirtualMemory::Reset () [private]
Definition at line 50 of file virtual-memory.cc.
                          {
  start_ = nullptr;
  size_ = 0;
}
References size_, and start_.
size()
size_t cppgc::internal::VirtualMemory::size () const [inline]
Definition at line 43 of file virtual-memory.h.
                      {
    DCHECK(IsReserved());
    return size_;
  }
References DCHECK.
Referenced by VirtualMemory().
Member Data Documentation
page_allocator_
PageAllocator* cppgc::internal::VirtualMemory::page_allocator_ = nullptr [private]
Definition at line 52 of file virtual-memory.h.
Referenced by VirtualMemory(), and ~VirtualMemory().
size_
size_t cppgc::internal::VirtualMemory::size_ = 0 [private]
Definition at line 54 of file virtual-memory.h.
Referenced by Reset(), VirtualMemory(), and ~VirtualMemory().
start_
void* cppgc::internal::VirtualMemory::start_ = nullptr [private]
Definition at line 53 of file virtual-memory.h.
Referenced by Reset(), VirtualMemory(), and ~VirtualMemory().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/virtual-memory.h
/mnt/V8SourceCode/src/heap/cppgc/virtual-memory.cc