v8::internal::compiler::JSUnaryOpNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSUnaryOpNode (Node *node)
Additional Inherited Members
Detailed Description
Definition at line 1164 of file js-operator.h.
Constructor & Destructor Documentation
JSUnaryOpNode()
constexpr v8::internal::compiler::JSUnaryOpNode::JSUnaryOpNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1166 of file js-operator.h.
                                               : JSNodeWrapperBase(node) {
    DCHECK(JSOperator::IsUnaryWithFeedback(node->opcode()));
  }
References v8::internal::DCHECK(), v8::internal::compiler::JSOperator::IsUnaryWithFeedback(), v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h