v8::internal::QwNeonRegister Class Reference
#include <register-arm.h>
Public Member Functions
void split_code (int *vm, int *m) const
DwVfpRegister low () const
DwVfpRegister high () const
VfpRegList ToVfpRegList () const
Static Public Member Functions
static void split_code (int reg_code, int *vm, int *m)
Private Member Functions
constexpr QwNeonRegister (int code)
Friends
class RegisterBase
Additional Inherited Members
Detailed Description
Definition at line 222 of file register-arm.h.
Constructor & Destructor Documentation
QwNeonRegister()
constexpr v8::internal::QwNeonRegister::QwNeonRegister (int code) [inline], [explicit], [constexpr], [private]
Definition at line 242 of file register-arm.h.
: RegisterBase(code) {}
Member Function Documentation
high()
DwVfpRegister v8::internal::QwNeonRegister::high () const [inline]
Definition at line 232 of file register-arm.h.
                             {
    return DwVfpRegister::from_code(code() * 2 + 1);
  }
References v8::internal::RegisterBase< QwNeonRegister, kSimd128AfterLast >::code(), and v8::internal::RegisterBase< DwVfpRegister, kDoubleAfterLast >::from_code().
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_pmax(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_pmin(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_dot_i8x16_i7x16_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_dot_i16x8_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_dot_i8x16_i7x16_add_s(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_mul(), v8::internal::wasm::LiftoffAssembler::emit_s128_store_nonzero_if_nan(), v8::internal::wasm::liftoff::F64x2Compare(), and v8::internal::Assembler::vpush().
low()
DwVfpRegister v8::internal::QwNeonRegister::low () const [inline]
Definition at line 231 of file register-arm.h.
{ return DwVfpRegister::from_code(code() * 2); }
References v8::internal::RegisterBase< QwNeonRegister, kSimd128AfterLast >::code(), and v8::internal::RegisterBase< DwVfpRegister, kDoubleAfterLast >::from_code().
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleMove(), v8::internal::compiler::CodeGenerator::AssembleSwap(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_pmax(), v8::internal::wasm::LiftoffAssembler::emit_f64x2_pmin(), v8::internal::wasm::LiftoffAssembler::emit_i16x8_dot_i8x16_i7x16_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_dot_i16x8_s(), v8::internal::wasm::LiftoffAssembler::emit_i32x4_dot_i8x16_i7x16_add_s(), v8::internal::wasm::LiftoffAssembler::emit_i64x2_mul(), v8::internal::wasm::LiftoffAssembler::emit_s128_store_nonzero_if_nan(), v8::internal::wasm::liftoff::F64x2Compare(), and v8::internal::Assembler::vpush().
split_code() [1/2]
void v8::internal::QwNeonRegister::split_code (int * vm, int * m) const [inline]
Definition at line 230 of file register-arm.h.
{ split_code(code(), vm, m); }
References v8::internal::RegisterBase< QwNeonRegister, kSimd128AfterLast >::code(), and split_code().
Referenced by split_code().
split_code() [2/2]
static void v8::internal::QwNeonRegister::split_code (int reg_code, int * vm, int * m) [inline], [static]
Definition at line 224 of file register-arm.h.
                                                        {
    V8_ASSUME(reg_code >= 0 && reg_code < kNumRegisters);
    int encoded_code = reg_code << 1;
    *m = (encoded_code & 0x10) >> 4;
    *vm = encoded_code & 0x0F;
  }
References v8::internal::RegisterBase< QwNeonRegister, kSimd128AfterLast >::kNumRegisters, and V8_ASSUME.
ToVfpRegList()
VfpRegList v8::internal::QwNeonRegister::ToVfpRegList () const [inline]
Definition at line 235 of file register-arm.h.
                                  {
    // A Q register overlaps four S registers.
    return uint64_t{0xf} << (code() * 4);
  }
References v8::internal::RegisterBase< QwNeonRegister, kSimd128AfterLast >::code().
Referenced by v8::internal::compiler::CodeGenerator::SetPendingMove().
Friends And Related Function Documentation
RegisterBase
friend class RegisterBase [friend]
Definition at line 241 of file register-arm.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/codegen/arm/register-arm.h