v8::internal::compiler::turboshaft::Var< T, Assembler > Class Template Reference
#include <assembler.h>
Public Member Functions
template<typename Reducer >
Var (Reducer *reducer)
template<typename Reducer >
Var (Reducer *reducer, value_type initial_value)
Var (Assembler &assembler)
Var (const Var &)=delete
Var (Var &&)=delete
Var & operator= (const Var)=delete
Var & operator= (Var &&)=delete
~Var ()=default
void Set (value_type new_value)
V< T > Get () const
void operator= (value_type new_value)
template<typename U >
operator V<U > () const requires v_traits< U >
operator OpIndex () const
operator OptionalOpIndex () const
Protected Attributes
Assembler & assembler_
Private Types
using value_type = maybe_const_or_v_t< T >
Additional Inherited Members
Detailed Description
template<class T, class Assembler>
class v8::internal::compiler::turboshaft::Var< T, Assembler >
Definition at line 829 of file assembler.h.
Member Typedef Documentation
value_type
template<class T , class Assembler >
using v8::internal::compiler::turboshaft::Var< T, Assembler >::value_type = maybe_const_or_v_t<T> [private]
Definition at line 830 of file assembler.h.
Constructor & Destructor Documentation
Var() [1/5]
template<class T , class Assembler >
template<typename Reducer >
v8::internal::compiler::turboshaft::Var< T, Assembler >::Var (Reducer * reducer) [inline], [explicit]
Definition at line 834 of file assembler.h.
: Var(reducer->Asm()) {}
Var() [2/5]
template<class T , class Assembler >
template<typename Reducer >
v8::internal::compiler::turboshaft::Var< T, Assembler >::Var (Reducer * reducer, value_type initial_value) [inline]
Definition at line 837 of file assembler.h.
                                                  : Var(reducer) {
    assembler_.SetVariable(*this, assembler_.resolve(initial_value));
  }
Var() [3/5]
template<class T , class Assembler >
v8::internal::compiler::turboshaft::Var< T, Assembler >::Var (Assembler & assembler) [inline], [explicit]
Definition at line 841 of file assembler.h.
      : Variable(assembler.NewVariable(
            static_cast<const RegisterRepresentation&>(V<T>::rep))),
        assembler_(assembler) {}
Var() [4/5]
template<class T , class Assembler >
v8::internal::compiler::turboshaft::Var< T, Assembler >::Var (const Var< T, Assembler > &) [delete]
Var() [5/5]
template<class T , class Assembler >
v8::internal::compiler::turboshaft::Var< T, Assembler >::Var (Var< T, Assembler > &&) [delete]
 Var()
template<class T , class Assembler >
v8::internal::compiler::turboshaft::Var< T, Assembler >::~Var () [default]
Member Function Documentation
Get()
template<class T , class Assembler >
V<T> v8::internal::compiler::turboshaft::Var< T, Assembler >::Get () const [inline]
Definition at line 855 of file assembler.h.
{ return assembler_.GetVariable(*this); }
operator OpIndex()
template<class T , class Assembler >
v8::internal::compiler::turboshaft::Var< T, Assembler >::operator OpIndex () const [inline]
Definition at line 877 of file assembler.h.
{ return Get(); }
References v8::internal::compiler::turboshaft::Get().
operator OptionalOpIndex()
template<class T , class Assembler >
v8::internal::compiler::turboshaft::Var< T, Assembler >::operator OptionalOpIndex () const [inline]
Definition at line 878 of file assembler.h.
{ return Get(); }
References v8::internal::compiler::turboshaft::Get().
operator V<U >()
template<class T , class Assembler >
template<typename U >
v8::internal::compiler::turboshaft::Var< T, Assembler >::operator V<U > () const [inline]
Definition at line 859 of file assembler.h.
                                        {
    return Get();
  }
  template <typename U>
  operator OptionalV<U>() const
    requires v_traits<U>::template
  implicitly_constructible_from<T>::value {
    return Get();
  }
  template <typename U>
  operator ConstOrV<U>() const
    requires(const_or_v_exists_v<U> &&
             v_traits<U>::template implicitly_constructible_from<T>::value)
  {
    return Get();
  }
References v8::internal::compiler::turboshaft::Get().
operator=() [1/3]
template<class T , class Assembler >
Var& v8::internal::compiler::turboshaft::Var< T, Assembler >::operator= (const Var) [delete]
operator=() [2/3]
template<class T , class Assembler >
void v8::internal::compiler::turboshaft::Var< T, Assembler >::operator= (value_type new_value) [inline]
Definition at line 857 of file assembler.h.
{ Set(new_value); }
operator=() [3/3]
template<class T , class Assembler >
Var& v8::internal::compiler::turboshaft::Var< T, Assembler >::operator= (Var< T, Assembler > &&) [delete]
Set()
template<class T , class Assembler >
void v8::internal::compiler::turboshaft::Var< T, Assembler >::Set (value_type new_value) [inline]
Definition at line 852 of file assembler.h.
                                 {
    assembler_.SetVariable(*this, assembler_.resolve(new_value));
  }
Member Data Documentation
assembler_
template<class T , class Assembler >
Assembler& v8::internal::compiler::turboshaft::Var< T, Assembler >::assembler_ [protected]
Definition at line 881 of file assembler.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/assembler.h