cppgc::internal::NormalPageSpace Class Reference
#include <heap-space.h>
Classes
class LinearAllocationBuffer
Public Member Functions
NormalPageSpace (RawHeap *heap, size_t index, bool is_compactable)
LinearAllocationBuffer & linear_allocation_buffer ()
const LinearAllocationBuffer & linear_allocation_buffer () const
FreeList & free_list ()
const FreeList & free_list () const
Static Public Member Functions
static NormalPageSpace & From (BaseSpace &space)
static const NormalPageSpace & From (const BaseSpace &space)
Private Attributes
LinearAllocationBuffer current_lab_
FreeList free_list_
Additional Inherited Members
Detailed Description
Definition at line 68 of file heap-space.h.
Constructor & Destructor Documentation
NormalPageSpace()
cppgc::internal::NormalPageSpace::NormalPageSpace (RawHeap * heap, size_t index, bool is_compactable)
Definition at line 44 of file heap-space.cc.
    : BaseSpace(heap, index, PageType::kNormal, is_compactable) {}
Member Function Documentation
free_list() [1/2]
FreeList& cppgc::internal::NormalPageSpace::free_list () [inline]
Definition at line 108 of file heap-space.h.
{ return free_list_; }
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage().
free_list() [2/2]
const FreeList& cppgc::internal::NormalPageSpace::free_list () const [inline]
Definition at line 109 of file heap-space.h.
{ return free_list_; }
From() [1/2]
static NormalPageSpace& cppgc::internal::NormalPageSpace::From (BaseSpace & space) [inline], [static]
Definition at line 93 of file heap-space.h.
                                                 {
    DCHECK(!space.is_large());
    return static_cast<NormalPageSpace&>(space);
  }
References DCHECK, and space.
Referenced by cppgc::internal::ObjectAllocator::AllocateObject(), cppgc::internal::NormalPage::begin(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage(), cppgc::internal::HeapVisitor< Derived >::Traverse(), cppgc::internal::BasePage::TryObjectHeaderFromInnerAddress(), and cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitNormalPage().
From() [2/2]
static const NormalPageSpace& cppgc::internal::NormalPageSpace::From (const BaseSpace & space) [inline], [static]
Definition at line 97 of file heap-space.h.
                                                             {
    return From(const_cast<BaseSpace&>(space));
  }
References space.
linear_allocation_buffer() [1/2]
LinearAllocationBuffer& cppgc::internal::NormalPageSpace::linear_allocation_buffer () [inline]
Definition at line 103 of file heap-space.h.
{ return current_lab_; }
Referenced by cppgc::internal::NormalPage::begin(), cppgc::internal::ExplicitManagementImpl::FreeUnreferencedObject(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Grow(), cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink(), and cppgc::internal::BasePage::TryObjectHeaderFromInnerAddress().
linear_allocation_buffer() [2/2]
const LinearAllocationBuffer& cppgc::internal::NormalPageSpace::linear_allocation_buffer () const [inline]
Definition at line 104 of file heap-space.h.
                                                                 {
    return current_lab_;
  }
Member Data Documentation
current_lab_
LinearAllocationBuffer cppgc::internal::NormalPageSpace::current_lab_ [private]
Definition at line 112 of file heap-space.h.
free_list_
FreeList cppgc::internal::NormalPageSpace::free_list_ [private]
Definition at line 113 of file heap-space.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/heap-space.h
/mnt/V8SourceCode/src/heap/cppgc/heap-space.cc