v8::internal::UnalignedValueMember< T > Class Template Reference
#include <tagged-field.h>
Public Member Functions
UnalignedValueMember ()=default
T value () const
void set_value (T value)
Protected Attributes
char storage_ [sizeof(T)]
Detailed Description
template<typename T>
class v8::internal::UnalignedValueMember< T >
Definition at line 71 of file tagged-field.h.
Constructor & Destructor Documentation
UnalignedValueMember()
template<typename T >
v8::internal::UnalignedValueMember< T >::UnalignedValueMember () [default]
Member Function Documentation
set_value()
template<typename T >
void v8::internal::UnalignedValueMember< T >::set_value (T value) [inline]
Definition at line 76 of file tagged-field.h.
{ base::WriteUnalignedValue(storage_, value); }
References v8::internal::UnalignedValueMember< T >::storage_, v8::internal::UnalignedValueMember< T >::value(), and v8::base::WriteUnalignedValue().
Referenced by v8::internal::ContextCell::set_float64_value(), and v8::internal::HeapNumber::set_value().
value()
template<typename T >
T v8::internal::UnalignedValueMember< T >::value () const [inline]
Definition at line 75 of file tagged-field.h.
{ return base::ReadUnalignedValue<T>(storage_); }
References v8::internal::UnalignedValueMember< T >::storage_.
Referenced by v8::internal::ContextCell::float64_value(), v8::internal::UnalignedValueMember< T >::set_value(), and v8::internal::HeapNumber::value().
Member Data Documentation
storage_
template<typename T >
char v8::internal::UnalignedValueMember< T >::storage_[sizeof(T)] [protected]
Definition at line 79 of file tagged-field.h.
Referenced by v8::internal::UnalignedValueMember< T >::set_value(), and v8::internal::UnalignedValueMember< T >::value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/tagged-field.h