v8::internal::DbgStreamBuf Class Reference
#include <ostreams.h>
Public Member Functions
DbgStreamBuf ()
~DbgStreamBuf () override
Private Member Functions
int sync () override
int overflow (int c) override
Private Attributes
char data_ [256]
Detailed Description
Definition at line 35 of file ostreams.h.
Constructor & Destructor Documentation
DbgStreamBuf()
v8::internal::DbgStreamBuf::DbgStreamBuf ()
Definition at line 27 of file ostreams.cc.
{ setp(data_, data_ + sizeof(data_)); }
References data_.
 DbgStreamBuf()
v8::internal::DbgStreamBuf::~DbgStreamBuf () [override]
Definition at line 29 of file ostreams.cc.
{ sync(); }
References sync().
Member Function Documentation
overflow()
int v8::internal::DbgStreamBuf::overflow (int c) [override], [private]
Definition at line 31 of file ostreams.cc.
                                {
#if V8_OS_WIN
  if (!IsDebuggerPresent()) {
    return 0;
  }
  sync();
  if (c != EOF) {
    if (pbase() == epptr()) {
      auto as_char = static_cast<char>(c);
      OutputDebugStringA(&as_char);
    } else {
      sputc(static_cast<char>(c));
    }
  }
#endif
  return 0;
}
References sync().
sync()
int v8::internal::DbgStreamBuf::sync () [override], [private]
Definition at line 51 of file ostreams.cc.
                       {
#if V8_OS_WIN
  if (!IsDebuggerPresent()) {
    return 0;
  }
  if (pbase() != pptr()) {
    OutputDebugStringA(std::string(pbase(), static_cast<std::string::size_type>(
                                                pptr() - pbase()))
                           .c_str());
    setp(pbase(), epptr());
  }
#endif
  return 0;
}
References v8::internal::string.
Referenced by overflow(), and ~DbgStreamBuf().
Member Data Documentation
data_
char v8::internal::DbgStreamBuf::data_[256] [private]
Definition at line 44 of file ostreams.h.
Referenced by DbgStreamBuf().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/utils/ostreams.h
/mnt/V8SourceCode/src/utils/ostreams.cc