v8::internal::compiler::NodeMarkerBase Class Reference
#include <node-marker.h>
Public Member Functions
NodeMarkerBase (TFGraph *graph, uint32_t num_states)
NodeMarkerBase (const NodeMarkerBase &)=delete
NodeMarkerBase & operator= (const NodeMarkerBase &)=delete
Mark Get (const Node *node)
void Set (Node *node, Mark mark)
Private Attributes
Mark const mark_min_
Mark const mark_max_
Detailed Description
Definition at line 18 of file node-marker.h.
Constructor & Destructor Documentation
NodeMarkerBase() [1/2]
v8::internal::compiler::NodeMarkerBase::NodeMarkerBase (TFGraph * graph, uint32_t num_states)
Definition at line 13 of file node-marker.cc.
    : mark_min_(graph->mark_max_), mark_max_(graph->mark_max_ += num_states) {
  DCHECK_NE(0u, num_states); // user error!
  DCHECK_LT(mark_min_, mark_max_); // check for wraparound.
}
References DCHECK_LT, DCHECK_NE, mark_max_, and mark_min_.
NodeMarkerBase() [2/2]
v8::internal::compiler::NodeMarkerBase::NodeMarkerBase (const NodeMarkerBase &) [delete]
Member Function Documentation
Get()
Mark v8::internal::compiler::NodeMarkerBase::Get (const Node * node) [inline]
Definition at line 24 of file node-marker.h.
                                       {
    Mark mark = node->mark();
    if (mark < mark_min_) {
      return 0;
    }
    DCHECK_LT(mark, mark_max_);
    return mark - mark_min_;
  }
References DCHECK_LT, v8::internal::compiler::Node::mark(), mark_max_, and mark_min_.
Referenced by v8::internal::compiler::NodeMarker< State >::Get().
operator=()
NodeMarkerBase& v8::internal::compiler::NodeMarkerBase::operator= (const NodeMarkerBase &) [delete]
Set()
void v8::internal::compiler::NodeMarkerBase::Set (Node * node, Mark mark) [inline]
Definition at line 32 of file node-marker.h.
                                            {
    DCHECK_LT(mark, mark_max_ - mark_min_);
    DCHECK_LT(node->mark(), mark_max_);
    node->set_mark(mark + mark_min_);
  }
References DCHECK_LT, v8::internal::compiler::Node::mark(), mark_max_, mark_min_, and v8::internal::compiler::Node::set_mark().
Referenced by v8::internal::compiler::NodeMarker< State >::Set().
Member Data Documentation
mark_max_
Mark const v8::internal::compiler::NodeMarkerBase::mark_max_ [private]
Definition at line 40 of file node-marker.h.
Referenced by Get(), NodeMarkerBase(), and Set().
mark_min_
Mark const v8::internal::compiler::NodeMarkerBase::mark_min_ [private]
Definition at line 39 of file node-marker.h.
Referenced by Get(), NodeMarkerBase(), and Set().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/node-marker.h
/mnt/V8SourceCode/src/compiler/node-marker.cc