v8::internal::wasm::WasmCodePointerTable Class Reference
#include <wasm-code-pointer-table.h>
Public Types
using Handle = uint32_t
using WriteScope = CFIMetadataWriteScope
Public Member Functions
WasmCodePointerTable ()=default
WasmCodePointerTable (const WasmCodePointerTable &)=delete
WasmCodePointerTable & operator= (const WasmCodePointerTable &)=delete
void Initialize ()
void TearDown ()
Address GetEntrypoint (WasmCodePointer index, uint64_t signature_hash) const
Address GetEntrypointWithoutSignatureCheck (WasmCodePointer index) const
void UpdateEntrypoint (WasmCodePointer index, Address value, uint64_t signature_hash)
void UpdateEntrypointUnlocked (WasmCodePointer index, Address value, uint64_t signature_hash)
void SetEntrypointAndSignature (WasmCodePointer index, Address value, uint64_t signature_hash)
void SetEntrypointWithWriteScope (WasmCodePointer index, Address value, uint64_t signature_hash, WriteScope &write_scope)
WasmCodePointer AllocateAndInitializeEntry (Address entrypoint, uint64_t signature_hash)
WasmCodePointer AllocateUninitializedEntry ()
void FreeEntry (WasmCodePointer index)
void SweepSegments (size_t threshold=2 *kEntriesPerSegment)
WasmCodePointer GetOrCreateHandleForNativeFunction (Address addr)
bool EntrypointEqualTo (WasmCodePointer index, Address address)
Static Public Attributes
static constexpr Handle kInvalidHandle = -1
Private Types
using Base = SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >
Private Member Functions
FreelistHead ReadFreelistHead ()
uint32_t AllocateEntryImpl ()
FreelistHead LinkFreelist (FreelistHead new_freelist, uint32_t last_element)
std::vector< uint32_t > FreelistToVector (FreelistHead freelist)
FreelistHead VectorToFreelist (std::vector< uint32_t > entries)
bool TryAllocateFromFreelist (uint32_t *index)
uint32_t AllocateEntryFromFreelistNonAtomic (FreelistHead *freelist_head)
void FreeNativeFunctionHandles ()
Static Private Member Functions
static bool IsRetryMarker (FreelistHead freelist)
Private Attributes
std::atomic< FreelistHead > freelist_head_ = FreelistHead()
base::Mutex segment_allocation_mutex_
base::Mutex native_function_map_mutex_
std::map< Address, WasmCodePointer > native_function_map_
Static Private Attributes
static constexpr FreelistHead kRetryMarker = FreelistHead(0xffffffff, 0)
Friends
class ::v8::internal::ExternalReference
class WasmCodePointerTableTest
Additional Inherited Members
Detailed Description
Definition at line 65 of file wasm-code-pointer-table.h.
Member Typedef Documentation
Base
using v8::internal::wasm::WasmCodePointerTable::Base = SegmentedTable<WasmCodePointerTableEntry, kCodePointerTableReservationSize> [private]
Definition at line 68 of file wasm-code-pointer-table.h.
Handle
using v8::internal::wasm::WasmCodePointerTable::Handle = uint32_t
Definition at line 76 of file wasm-code-pointer-table.h.
WriteScope
using v8::internal::wasm::WasmCodePointerTable::WriteScope = CFIMetadataWriteScope
Definition at line 89 of file wasm-code-pointer-table.h.
Constructor & Destructor Documentation
WasmCodePointerTable() [1/2]
v8::internal::wasm::WasmCodePointerTable::WasmCodePointerTable () [default]
WasmCodePointerTable() [2/2]
v8::internal::wasm::WasmCodePointerTable::WasmCodePointerTable (const WasmCodePointerTable &) [delete]
Member Function Documentation
AllocateAndInitializeEntry()
WasmCodePointer v8::internal::wasm::WasmCodePointerTable::AllocateAndInitializeEntry (Address entrypoint, uint64_t signature_hash) [inline]
Definition at line 95 of file wasm-code-pointer-table-inl.h.
                                                 {
  WasmCodePointer index = AllocateUninitializedEntry();
  WriteScope write_scope("WasmCodePointerTable write");
  at(index.value()).MakeCodePointerEntry(entrypoint, signature_hash);
  return index;
}
References AllocateUninitializedEntry(), v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::at(), and v8::internal::index.
Referenced by GetOrCreateHandleForNativeFunction().
AllocateEntryFromFreelistNonAtomic()
uint32_t v8::internal::wasm::WasmCodePointerTable::AllocateEntryFromFreelistNonAtomic (FreelistHead * freelist_head) [inline], [private]
Definition at line 187 of file wasm-code-pointer-table-inl.h.
                                 {
  DCHECK(!freelist_head->is_empty());
  uint32_t index = freelist_head->next();
  uint32_t next_next = at(freelist_head->next()).GetNextFreelistEntryIndex();
  *freelist_head = FreelistHead(next_next, freelist_head->length() - 1);
  return index;
}
References v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::at(), v8::internal::DCHECK(), and v8::internal::index.
Referenced by AllocateUninitializedEntry().
AllocateEntryImpl()
uint32_t v8::internal::wasm::WasmCodePointerTable::AllocateEntryImpl () [private]
AllocateUninitializedEntry()
WasmCodePointer v8::internal::wasm::WasmCodePointerTable::AllocateUninitializedEntry () [inline]
Definition at line 115 of file wasm-code-pointer-table-inl.h.
                                                                 {
  DCHECK(is_initialized());
  while (true) {
    // Fast path, try to take an entry from the freelist.
    uint32_t allocated_entry;
    if (TryAllocateFromFreelist(&allocated_entry)) {
      return WasmCodePointer{allocated_entry};
    }
    // This is essentially DCLP (see
    // https://preshing.com/20130930/double-checked-locking-is-fixed-in-cpp11/)
    // and so requires an acquire load as well as a release store in
    // AllocateTableSegment() to prevent reordering of memory accesses, which
    // could for example cause one thread to read a freelist entry before it
    // has been properly initialized.
    // The freelist is empty. We take a lock to avoid another thread from
    // allocating a new segment in the meantime. However, the freelist can
    // still grow if another thread frees an entry, so we'll merge the
    // freelists atomically in the end.
    base::MutexGuard guard(&segment_allocation_mutex_);
    // Reload freelist head in case another thread already grew the table.
    if (!freelist_head_.load(std::memory_order_relaxed).is_empty()) {
      // Something changed, retry.
      continue;
    }
    // Freelist is (still) empty so extend this space by another segment.
    auto [segment, freelist] = AllocateAndInitializeSegment();
    // Take out the first entry before we link it to the freelist_head.
    allocated_entry = AllocateEntryFromFreelistNonAtomic(&freelist);
    // Merge the new freelist entries into our freelist.
    LinkFreelist(freelist, segment.last_entry());
    return WasmCodePointer{allocated_entry};
  }
}
References v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::AllocateAndInitializeSegment(), AllocateEntryFromFreelistNonAtomic(), v8::internal::DCHECK(), freelist_head_, v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::is_initialized(), LinkFreelist(), segment_allocation_mutex_, and TryAllocateFromFreelist().
Referenced by AllocateAndInitializeEntry(), and v8::internal::wasm::NativeModule::InitializeCodePointerTableHandles().
EntrypointEqualTo()
bool v8::internal::wasm::WasmCodePointerTable::EntrypointEqualTo (WasmCodePointer index, Address address)
Definition at line 138 of file wasm-code-pointer-table.cc.
                                                              {
  return at(index.value()).GetEntrypointWithoutSignatureCheck() == address;
}
References v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::at(), and v8::internal::index.
Referenced by v8::internal::RUNTIME_FUNCTION().
FreeEntry()
void v8::internal::wasm::WasmCodePointerTable::FreeEntry (WasmCodePointer index) [inline]
Definition at line 196 of file wasm-code-pointer-table-inl.h.
                                                          {
  // TODO(sroettger): adding to the inline freelist requires a WriteScope. We
  // could keep a second fixed size out-of-line freelist to avoid frequent
  // permission changes here.
  LinkFreelist(FreelistHead(entry.value(), 1), entry.value());
}
References LinkFreelist(), and v8::internal::WasmCodePointer::value().
Referenced by v8::internal::wasm::NativeModule::FreeCodePointerTableHandles(), FreeNativeFunctionHandles(), and v8::internal::wasm::WasmImportWrapperHandle::~WasmImportWrapperHandle().
FreelistToVector()
std::vector<uint32_t> v8::internal::wasm::WasmCodePointerTable::FreelistToVector (FreelistHead freelist) [private]
Referenced by SweepSegments().
FreeNativeFunctionHandles()
void v8::internal::wasm::WasmCodePointerTable::FreeNativeFunctionHandles () [private]
Definition at line 143 of file wasm-code-pointer-table.cc.
                                                     {
  base::MutexGuard guard(&native_function_map_mutex_);
  for (auto const& [address, handle] : native_function_map_) {
    FreeEntry(handle);
  }
  native_function_map_.clear();
}
References FreeEntry(), v8::internal::handle(), native_function_map_, and native_function_map_mutex_.
Referenced by TearDown().
GetEntrypoint()
Address v8::internal::wasm::WasmCodePointerTable::GetEntrypoint (WasmCodePointer index, uint64_t signature_hash) const [inline]
Definition at line 59 of file wasm-code-pointer-table-inl.h.
                                                                           {
  return at(index.value()).GetEntrypoint(signature_hash);
}
References v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::at(), and v8::internal::index.
GetEntrypointWithoutSignatureCheck()
Address v8::internal::wasm::WasmCodePointerTable::GetEntrypointWithoutSignatureCheck (WasmCodePointer index) const [inline]
Definition at line 64 of file wasm-code-pointer-table-inl.h.
                                 {
  return at(index.value()).GetEntrypointWithoutSignatureCheck();
}
References v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::at(), and v8::internal::index.
Referenced by v8::internal::wasm::FeedbackMaker::AddCallIndirectCandidate(), v8::internal::ImportedFunctionEntry::SetWasmToWasm(), and v8::internal::WasmTableObject::UpdateDispatchTable().
GetOrCreateHandleForNativeFunction()
WasmCodePointer v8::internal::wasm::WasmCodePointerTable::GetOrCreateHandleForNativeFunction (Address addr)
Definition at line 124 of file wasm-code-pointer-table.cc.
                  {
  base::MutexGuard guard(&native_function_map_mutex_);
  auto it = native_function_map_.find(addr);
  if (it != native_function_map_.end()) {
    return it->second;
  }
  WasmCodePointer handle = AllocateAndInitializeEntry(addr, -1);
  native_function_map_.insert({addr, handle});
  return handle;
}
References AllocateAndInitializeEntry(), v8::internal::handle(), native_function_map_, and native_function_map_mutex_.
Initialize()
void v8::internal::wasm::WasmCodePointerTable::Initialize ()
Definition at line 12 of file wasm-code-pointer-table.cc.
{ Base::Initialize(); }
References v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::Initialize().
Referenced by v8::internal::wasm::WasmEngine::InitializeOncePerProcess().
IsRetryMarker()
static bool v8::internal::wasm::WasmCodePointerTable::IsRetryMarker (FreelistHead freelist) [inline], [static], [private]
Definition at line 142 of file wasm-code-pointer-table.h.
                                                   {
    return freelist.length() == kRetryMarker.length() &&
           freelist.next() == kRetryMarker.next();
  }
Referenced by ReadFreelistHead().
LinkFreelist()
WasmCodePointerTable::FreelistHead v8::internal::wasm::WasmCodePointerTable::LinkFreelist (FreelistHead new_freelist, uint32_t last_element) [inline], [private]
Definition at line 203 of file wasm-code-pointer-table-inl.h.
                                                          {
  DCHECK(!freelist_to_link.is_empty());
  FreelistHead current_head, new_head;
  do {
    current_head = ReadFreelistHead();
    new_head = FreelistHead(freelist_to_link.next(),
                            freelist_to_link.length() + current_head.length());
    WriteScope write_scope("write free list entry");
    at(last_element).MakeFreelistEntry(current_head.next());
    // This must be a release store since we previously wrote the freelist
    // entries in AllocateTableSegment() and we need to prevent the writes from
    // being reordered past this store. See AllocateEntry() for more details.
  } while (!freelist_head_.compare_exchange_strong(current_head, new_head,
                                                   std::memory_order_release));
  return new_head;
}
References v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::at(), v8::internal::DCHECK(), freelist_head_, and ReadFreelistHead().
Referenced by AllocateUninitializedEntry(), FreeEntry(), and SweepSegments().
operator=()
WasmCodePointerTable& v8::internal::wasm::WasmCodePointerTable::operator= (const WasmCodePointerTable &) [delete]
ReadFreelistHead()
WasmCodePointerTable::FreelistHead v8::internal::wasm::WasmCodePointerTable::ReadFreelistHead () [inline], [private]
Definition at line 103 of file wasm-code-pointer-table-inl.h.
                                                                        {
  while (true) {
    FreelistHead freelist = freelist_head_.load(std::memory_order_acquire);
    if (IsRetryMarker(freelist)) {
      // The retry marker will only be stored for a short amount of time. We can
      // check for it in a busy loop.
      continue;
    }
    return freelist;
  }
}
References freelist_head_, and IsRetryMarker().
Referenced by LinkFreelist(), SweepSegments(), and TryAllocateFromFreelist().
SetEntrypointAndSignature()
void v8::internal::wasm::WasmCodePointerTable::SetEntrypointAndSignature (WasmCodePointer index, Address value, uint64_t signature_hash) [inline]
Definition at line 82 of file wasm-code-pointer-table-inl.h.
                                                                              {
  WriteScope write_scope("WasmCodePointerTable write");
  at(index.value()).MakeCodePointerEntry(value, signature_hash);
}
References v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::at(), v8::internal::index, and v8::internal::value.
Referenced by v8::internal::wasm::NativeModule::PatchJumpTablesLocked().
SetEntrypointWithWriteScope()
void v8::internal::wasm::WasmCodePointerTable::SetEntrypointWithWriteScope (WasmCodePointer index, Address value, uint64_t signature_hash, WriteScope & write_scope) [inline]
Definition at line 89 of file wasm-code-pointer-table-inl.h.
                             {
  at(index.value()).MakeCodePointerEntry(value, signature_hash);
}
References v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::at(), v8::internal::index, and v8::internal::value.
Referenced by v8::internal::wasm::NativeModule::InitializeJumpTableForLazyCompilation().
SweepSegments()
void v8::internal::wasm::WasmCodePointerTable::SweepSegments (size_t threshold = 2 * kEntriesPerSegment)
Definition at line 57 of file wasm-code-pointer-table.cc.
                                                         {
  if (threshold < kEntriesPerSegment) {
    // We need at least a whole empty segment if we want to sweep anything.
    threshold = kEntriesPerSegment;
  }
  FreelistHead initial_head, empty_freelist;
  do {
    initial_head = ReadFreelistHead();
    if (initial_head.length() < threshold) {
      return;
    }
    // Try to unlink the freelist. If it fails, try again.
  } while (
      !freelist_head_.compare_exchange_strong(initial_head, empty_freelist));
  // We unlinked the whole free list, so we have exclusive access to it at
  // this point.
  // Now search for empty segments (== all entries are freelist entries) and
  // unlink them.
  std::vector<uint32_t> freelist_entries = FreelistToVector(initial_head);
  std::sort(freelist_entries.begin(), freelist_entries.end());
  // The minimum threshold is kEntriesPerSegment.
  DCHECK_GE(freelist_entries.size(), kEntriesPerSegment);
  // We iterate over all freelist entries and copy them over to a new vector,
  // while skipping and unmapping empty segments.
  std::vector<uint32_t> new_freelist_entries;
  for (size_t i = 0; i < freelist_entries.size(); i++) {
    uint32_t entry = freelist_entries[i];
    Segment segment = Segment::Containing(entry);
    if (segment.first_entry() == entry &&
        i + kEntriesPerSegment - 1 < freelist_entries.size()) {
      uint32_t last_entry = freelist_entries[i + kEntriesPerSegment - 1];
      if (segment.last_entry() == last_entry) {
        // The whole segment is empty. Delete the segment and skip all
        // entries;
        FreeTableSegment(segment);
        i += kEntriesPerSegment - 1;
        continue;
      }
    }
    new_freelist_entries.push_back(entry);
  }
  DCHECK_LE(new_freelist_entries.size(), freelist_entries.size());
  DCHECK(IsAligned(freelist_entries.size() - new_freelist_entries.size(),
                   kEntriesPerSegment));
  if (new_freelist_entries.empty()) {
    return;
  }
  // Finally, add the new freelist back.
  uint32_t last_element = new_freelist_entries.back();
  FreelistHead new_freelist = VectorToFreelist(new_freelist_entries);
  LinkFreelist(new_freelist, last_element);
}
References v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, freelist_head_, FreelistToVector(), v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::FreeTableSegment(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, IsAligned(), v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::kEntriesPerSegment, LinkFreelist(), ReadFreelistHead(), v8::base::sort(), and VectorToFreelist().
Referenced by TearDown().
TearDown()
void v8::internal::wasm::WasmCodePointerTable::TearDown ()
Definition at line 14 of file wasm-code-pointer-table.cc.
                                    {
  FreeNativeFunctionHandles();
  SweepSegments(0);
  DCHECK(freelist_head_.load().is_empty());
  Base::TearDown();
}
References v8::internal::DCHECK(), freelist_head_, FreeNativeFunctionHandles(), SweepSegments(), and v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::TearDown().
Referenced by v8::internal::wasm::WasmEngine::GlobalTearDown().
TryAllocateFromFreelist()
bool v8::internal::wasm::WasmCodePointerTable::TryAllocateFromFreelist (uint32_t * index) [inline], [private]
Definition at line 157 of file wasm-code-pointer-table-inl.h.
                                                                  {
  while (true) {
    FreelistHead current_freelist_head = ReadFreelistHead();
    if (current_freelist_head.is_empty()) {
      return false;
    }
    // Temporarily replace the freelist head with a marker to gain exclusive
    // access to it. This avoids a race condition where another thread could
    // unmap the memory while we're trying to read from it.
    if (!freelist_head_.compare_exchange_strong(current_freelist_head,
                                                kRetryMarker)) {
      continue;
    }
    uint32_t next_freelist_entry =
        at(current_freelist_head.next()).GetNextFreelistEntryIndex();
    FreelistHead new_freelist_head(next_freelist_entry,
                                   current_freelist_head.length() - 1);
    // We are allowed to overwrite the freelist_head_ since we stored the
    // kRetryMarker in there.
    freelist_head_.store(new_freelist_head, std::memory_order_relaxed);
    *index = current_freelist_head.next();
    return true;
  }
}
References v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::at(), freelist_head_, v8::internal::index, kRetryMarker, and ReadFreelistHead().
Referenced by AllocateUninitializedEntry().
UpdateEntrypoint()
void v8::internal::wasm::WasmCodePointerTable::UpdateEntrypoint (WasmCodePointer index, Address value, uint64_t signature_hash) [inline]
Definition at line 69 of file wasm-code-pointer-table-inl.h.
                                                                     {
  WriteScope write_scope("WasmCodePointerTable write");
  return UpdateEntrypointUnlocked(index, value, signature_hash);
}
References v8::internal::index, UpdateEntrypointUnlocked(), and v8::internal::value.
UpdateEntrypointUnlocked()
void v8::internal::wasm::WasmCodePointerTable::UpdateEntrypointUnlocked (WasmCodePointer index, Address value, uint64_t signature_hash) [inline]
Definition at line 76 of file wasm-code-pointer-table-inl.h.
                                                                             {
  at(index.value()).UpdateCodePointerEntry(value, signature_hash);
}
References v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::at(), v8::internal::index, and v8::internal::value.
Referenced by UpdateEntrypoint().
VectorToFreelist()
WasmCodePointerTable::FreelistHead v8::internal::wasm::WasmCodePointerTable::VectorToFreelist (std::vector< uint32_t > entries) [private]
Definition at line 38 of file wasm-code-pointer-table.cc.
                                 {
  if (entries.empty()) {
    return FreelistHead();
  }
  FreelistHead new_freelist =
      FreelistHead(entries[0], static_cast<uint32_t>(entries.size()));
  WriteScope write_scope("Freelist write");
  for (size_t i = 0; i < entries.size() - 1; i++) {
    uint32_t entry = entries[i];
    uint32_t next_entry = entries[i + 1];
    at(entry).MakeFreelistEntry(next_entry);
  }
  return new_freelist;
}
References v8::internal::SegmentedTable< WasmCodePointerTableEntry, kCodePointerTableReservationSize >::at(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by SweepSegments().
Friends And Related Function Documentation
::v8::internal::ExternalReference
friend class ::v8::internal::ExternalReference [friend]
Definition at line 137 of file wasm-code-pointer-table.h.
WasmCodePointerTableTest
friend class WasmCodePointerTableTest [friend]
Definition at line 185 of file wasm-code-pointer-table.h.
Member Data Documentation
freelist_head_
std::atomic<FreelistHead> v8::internal::wasm::WasmCodePointerTable::freelist_head_ = FreelistHead() [private]
Definition at line 177 of file wasm-code-pointer-table.h.
Referenced by AllocateUninitializedEntry(), LinkFreelist(), ReadFreelistHead(), SweepSegments(), TearDown(), and TryAllocateFromFreelist().
kInvalidHandle
constexpr Handle v8::internal::wasm::WasmCodePointerTable::kInvalidHandle = -1 [static], [constexpr]
Definition at line 77 of file wasm-code-pointer-table.h.
kRetryMarker
constexpr FreelistHead v8::internal::wasm::WasmCodePointerTable::kRetryMarker = FreelistHead(0xffffffff, 0) [static], [constexpr], [private]
Definition at line 141 of file wasm-code-pointer-table.h.
Referenced by TryAllocateFromFreelist().
native_function_map_
std::map<Address, WasmCodePointer> v8::internal::wasm::WasmCodePointerTable::native_function_map_ [private]
Definition at line 183 of file wasm-code-pointer-table.h.
Referenced by FreeNativeFunctionHandles(), and GetOrCreateHandleForNativeFunction().
native_function_map_mutex_
base::Mutex v8::internal::wasm::WasmCodePointerTable::native_function_map_mutex_ [private]
Definition at line 182 of file wasm-code-pointer-table.h.
Referenced by FreeNativeFunctionHandles(), and GetOrCreateHandleForNativeFunction().
segment_allocation_mutex_
base::Mutex v8::internal::wasm::WasmCodePointerTable::segment_allocation_mutex_ [private]
Definition at line 180 of file wasm-code-pointer-table.h.
Referenced by AllocateUninitializedEntry().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-code-pointer-table.h
/mnt/V8SourceCode/src/wasm/wasm-code-pointer-table-inl.h
/mnt/V8SourceCode/src/wasm/wasm-code-pointer-table.cc