v8::internal::maglev::NodeInfo::AlternativeNodes Class Reference
#include <maglev-interpreter-frame-state.h>
Public Types
enum Kind { kNumberOfAlternatives
 }
Public Member Functions
AlternativeNodes ()
bool has_none () const
void MergeWith (const AlternativeNodes &other)
Private Member Functions
AlternativeNodes (const AlternativeNodes &) V8_NOEXCEPT=default
AlternativeNodes & operator= (const AlternativeNodes &) V8_NOEXCEPT=default
Private Attributes
std::array< ValueNode *, Kind::kNumberOfAlternatives > store_
Friends
class NodeInfo
Detailed Description
Definition at line 99 of file maglev-interpreter-frame-state.h.
Member Enumeration Documentation
Kind
enum v8::internal::maglev::NodeInfo::AlternativeNodes::Kind
Enumerator
kNumberOfAlternatives
Definition at line 110 of file maglev-interpreter-frame-state.h.
              {
#define KIND(name, Name) k##Name,
      ALTERNATIVES(KIND)
#undef KIND
          kNumberOfAlternatives
    };
Constructor & Destructor Documentation
AlternativeNodes() [1/2]
v8::internal::maglev::NodeInfo::AlternativeNodes::AlternativeNodes () [inline]
Definition at line 101 of file maglev-interpreter-frame-state.h.
{ store_.fill(nullptr); }
References store_.
Referenced by has_none().
AlternativeNodes() [2/2]
v8::internal::maglev::NodeInfo::AlternativeNodes::AlternativeNodes (const AlternativeNodes &) [private], [default]
Member Function Documentation
has_none()
bool v8::internal::maglev::NodeInfo::AlternativeNodes::has_none () const [inline]
Definition at line 131 of file maglev-interpreter-frame-state.h.
{ return store_ == AlternativeNodes().store_; }
References AlternativeNodes(), and store_.
Referenced by v8::internal::maglev::NodeInfo::no_info_available().
MergeWith()
void v8::internal::maglev::NodeInfo::AlternativeNodes::MergeWith (const AlternativeNodes & other) [inline]
Definition at line 133 of file maglev-interpreter-frame-state.h.
                                                  {
      for (size_t i = 0; i < Kind::kNumberOfAlternatives; ++i) {
        if (store_[i] && store_[i] != other.store_[i]) {
          store_[i] = nullptr;
        }
      }
    }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, and store_.
Referenced by v8::internal::maglev::NodeInfo::MergeWith().
operator=()
AlternativeNodes& v8::internal::maglev::NodeInfo::AlternativeNodes::operator= (const AlternativeNodes &) [private], [default]
Friends And Related Function Documentation
NodeInfo
friend class NodeInfo [friend]
Definition at line 150 of file maglev-interpreter-frame-state.h.
Member Data Documentation
store_
std::array<ValueNode*, Kind::kNumberOfAlternatives> v8::internal::maglev::NodeInfo::AlternativeNodes::store_ [private]
Definition at line 144 of file maglev-interpreter-frame-state.h.
Referenced by AlternativeNodes(), has_none(), and MergeWith().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-interpreter-frame-state.h