v8::internal::LoadHandler Class Reference
#include <handler-configuration.h>
Public Types
enum class Kind {
kElement
, kElementWithTransition
, kIndexedString
, kNormal
,
kGlobal
, kField
, kConstantFromPrototype
, kAccessorFromPrototype
,
kNativeDataProperty
, kApiGetter
, kInterceptor
, kSlow
,
kProxy
, kNonExistent
, kModuleExport
, kGeneric
 }
using KindBits = base::BitField< Kind, 0, 4 >
using DoAccessCheckOnLookupStartObjectBits = KindBits::Next< bool, 1 >
using LookupOnLookupStartObjectBits = DoAccessCheckOnLookupStartObjectBits::Next< bool, 1 >
using DescriptorBits = LookupOnLookupStartObjectBits::Next< unsigned, kDescriptorIndexBitCount >
using IsWasmStructBits = LookupOnLookupStartObjectBits::Next< bool, 1 >
using IsInobjectBits = IsWasmStructBits::Next< bool, 1 >
using IsDoubleBits = IsInobjectBits::Next< bool, 1 >
using FieldIndexBits = IsDoubleBits::Next< unsigned, kDescriptorIndexBitCount+1 >
using WasmFieldTypeBits = IsWasmStructBits::Next< WasmValueType, 4 >
using WasmFieldOffsetBits = WasmFieldTypeBits::Next< unsigned, 20 >
using AllowOutOfBoundsBits = LookupOnLookupStartObjectBits::Next< bool, 1 >
using IsWasmArrayBits = AllowOutOfBoundsBits::Next< bool, 1 >
using IsJsArrayBits = IsWasmArrayBits::Next< bool, 1 >
using AllowHandlingHole = IsJsArrayBits::Next< bool, 1 >
using ElementsKindBits = AllowHandlingHole::Next< ElementsKind, 8 >
using WasmArrayTypeBits = IsWasmArrayBits::Next< WasmValueType, 4 >
using ExportsIndexBits = LookupOnLookupStartObjectBits::Next< unsigned, kSmiValueSize - LookupOnLookupStartObjectBits::kLastUsedBit - 1 >
Static Public Member Functions
static Kind GetHandlerKind (Tagged< Smi > smi_handler)
static Handle< Smi > LoadNormal (Isolate *isolate)
static Handle< Smi > LoadGlobal (Isolate *isolate)
static Handle< Smi > LoadInterceptor (Isolate *isolate)
static Handle< Smi > LoadSlow (Isolate *isolate)
static Handle< Smi > LoadGeneric (Isolate *isolate)
static Tagged< Smi > LoadGeneric ()
static Handle< Smi > LoadField (Isolate *isolate, FieldIndex field_index)
static Handle< Smi > LoadConstantFromPrototype (Isolate *isolate)
static DirectHandle< Smi > LoadAccessorFromPrototype (Isolate *isolate)
static Handle< Smi > LoadProxy (Isolate *isolate)
static Handle< Smi > LoadNativeDataProperty (Isolate *isolate, int descriptor)
static Handle< Smi > LoadApiGetter (Isolate *isolate)
static Handle< Smi > LoadModuleExport (Isolate *isolate, int index)
static DirectHandle< Smi > LoadWasmStructField (Isolate *isolate, WasmValueType type, int offset)
static DirectHandle< Smi > LoadWasmArrayElement (Isolate *isolate, WasmValueType type)
static Handle< Object > LoadFullChain (Isolate *isolate, DirectHandle< Map > receiver_map, const MaybeObjectDirectHandle &holder, Handle< Smi > smi_handler)
static Handle< Object > LoadFromPrototype (Isolate *isolate, DirectHandle< Map > receiver_map, DirectHandle< JSReceiver > holder, Tagged< Smi > smi_handler, MaybeObjectDirectHandle maybe_data1=MaybeObjectDirectHandle(), MaybeObjectDirectHandle maybe_data2=MaybeObjectDirectHandle())
static Handle< Smi > LoadNonExistent (Isolate *isolate)
static Handle< Object > LoadNonExistent (Isolate *isolate, DirectHandle< Map > lookup_start_object_map)
static Handle< Smi > LoadElement (Isolate *isolate, ElementsKind elements_kind, bool is_js_array, KeyedAccessLoadMode load_mode)
static Handle< Smi > TransitionAndLoadElement (Isolate *isolate, ElementsKind kind_after_transition, KeyedAccessLoadMode load_mode)
static Handle< Smi > LoadIndexedString (Isolate *isolate, KeyedAccessLoadMode load_mode)
static KeyedAccessLoadMode GetKeyedAccessLoadMode (Tagged< MaybeObject > handler)
static bool CanHandleHolderNotLookupStart (Tagged< Object > handler)
Additional Inherited Members
Detailed Description
Definition at line 44 of file handler-configuration.h.
Member Typedef Documentation
AllowHandlingHole
using v8::internal::LoadHandler::AllowHandlingHole = IsJsArrayBits::Next<bool, 1>
Definition at line 129 of file handler-configuration.h.
AllowOutOfBoundsBits
using v8::internal::LoadHandler::AllowOutOfBoundsBits = LookupOnLookupStartObjectBits::Next<bool, 1>
Definition at line 118 of file handler-configuration.h.
DescriptorBits
using v8::internal::LoadHandler::DescriptorBits = LookupOnLookupStartObjectBits::Next<unsigned, kDescriptorIndexBitCount>
Definition at line 86 of file handler-configuration.h.
DoAccessCheckOnLookupStartObjectBits
using v8::internal::LoadHandler::DoAccessCheckOnLookupStartObjectBits = KindBits::Next<bool, 1>
Definition at line 72 of file handler-configuration.h.
ElementsKindBits
using v8::internal::LoadHandler::ElementsKindBits = AllowHandlingHole::Next<ElementsKind, 8>
Definition at line 130 of file handler-configuration.h.
ExportsIndexBits
using v8::internal::LoadHandler::ExportsIndexBits = LookupOnLookupStartObjectBits::Next< unsigned, kSmiValueSize - LookupOnLookupStartObjectBits::kLastUsedBit - 1>
Definition at line 144 of file handler-configuration.h.
FieldIndexBits
using v8::internal::LoadHandler::FieldIndexBits = IsDoubleBits::Next<unsigned, kDescriptorIndexBitCount + 1>
Definition at line 102 of file handler-configuration.h.
IsDoubleBits
using v8::internal::LoadHandler::IsDoubleBits = IsInobjectBits::Next<bool, 1>
Definition at line 100 of file handler-configuration.h.
IsInobjectBits
using v8::internal::LoadHandler::IsInobjectBits = IsWasmStructBits::Next<bool, 1>
Definition at line 99 of file handler-configuration.h.
IsJsArrayBits
using v8::internal::LoadHandler::IsJsArrayBits = IsWasmArrayBits::Next<bool, 1>
Definition at line 128 of file handler-configuration.h.
IsWasmArrayBits
using v8::internal::LoadHandler::IsWasmArrayBits = AllowOutOfBoundsBits::Next<bool, 1>
Definition at line 123 of file handler-configuration.h.
IsWasmStructBits
using v8::internal::LoadHandler::IsWasmStructBits = LookupOnLookupStartObjectBits::Next<bool, 1>
Definition at line 94 of file handler-configuration.h.
KindBits
using v8::internal::LoadHandler::KindBits = base::BitField<Kind, 0, 4>
Definition at line 67 of file handler-configuration.h.
LookupOnLookupStartObjectBits
using v8::internal::LoadHandler::LookupOnLookupStartObjectBits = DoAccessCheckOnLookupStartObjectBits::Next<bool, 1>
Definition at line 78 of file handler-configuration.h.
WasmArrayTypeBits
using v8::internal::LoadHandler::WasmArrayTypeBits = IsWasmArrayBits::Next<WasmValueType, 4>
Definition at line 137 of file handler-configuration.h.
WasmFieldOffsetBits
using v8::internal::LoadHandler::WasmFieldOffsetBits = WasmFieldTypeBits::Next<unsigned, 20>
Definition at line 111 of file handler-configuration.h.
WasmFieldTypeBits
using v8::internal::LoadHandler::WasmFieldTypeBits = IsWasmStructBits::Next<WasmValueType, 4>
Definition at line 110 of file handler-configuration.h.
Member Enumeration Documentation
Kind
enum v8::internal::LoadHandler::Kind [strong]
Enumerator
kElement
kElementWithTransition
kIndexedString
kNormal
kGlobal
kField
kConstantFromPrototype
kAccessorFromPrototype
kNativeDataProperty
kApiGetter
kInterceptor
kSlow
kProxy
kNonExistent
kModuleExport
kGeneric
Definition at line 49 of file handler-configuration.h.
                  {
    kElement,
    kElementWithTransition,
    kIndexedString,
    kNormal,
    kGlobal,
    kField,
    kConstantFromPrototype,
    kAccessorFromPrototype,
    kNativeDataProperty,
    kApiGetter,
    kInterceptor,
    kSlow,
    kProxy,
    kNonExistent,
    kModuleExport,
    kGeneric, // Used for keyed loads with "1 map, many property names".
  };
Member Function Documentation
CanHandleHolderNotLookupStart()
bool v8::internal::LoadHandler::CanHandleHolderNotLookupStart (Tagged< Object > handler) [static]
Definition at line 430 of file handler-configuration.cc.
                                                                      {
  if (IsSmi(handler)) {
    auto kind = LoadHandler::KindBits::decode(handler.ToSmi().value());
    return kind == LoadHandler::Kind::kSlow ||
           kind == LoadHandler::Kind::kNonExistent;
  }
  return IsLoadHandler(handler);
}
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::IsSmi(), kNonExistent, kSlow, and v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi().
Referenced by v8::internal::LoadIC::UpdateCaches().
GetHandlerKind()
LoadHandler::Kind v8::internal::LoadHandler::GetHandlerKind (Tagged< Smi > smi_handler) [inline], [static]
Definition at line 26 of file handler-configuration-inl.h.
                                                                   {
  return KindBits::decode(smi_handler.value());
}
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::DataHandler::smi_handler().
GetKeyedAccessLoadMode()
KeyedAccessLoadMode v8::internal::LoadHandler::GetKeyedAccessLoadMode (Tagged< MaybeObject > handler) [static]
Definition at line 245 of file handler-configuration.cc.
                                 {
  DisallowGarbageCollection no_gc;
  if (IsSmi(handler)) {
    int const raw_handler = handler.ToSmi().value();
    Kind const kind = KindBits::decode(raw_handler);
    if (kind == Kind::kElement || kind == Kind::kIndexedString) {
      bool handle_oob = AllowOutOfBoundsBits::decode(raw_handler);
      bool handle_holes = AllowHandlingHole::decode(raw_handler);
      return CreateKeyedAccessLoadMode(handle_oob, handle_holes);
    }
  }
  return KeyedAccessLoadMode::kInBounds;
}
References v8::internal::CreateKeyedAccessLoadMode(), v8::base::BitField< T, shift, size, U >::decode(), v8::internal::IsSmi(), kElement, v8::internal::kInBounds, kIndexedString, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi().
Referenced by v8::internal::FeedbackNexus::GetKeyedAccessLoadMode(), and v8::internal::KeyedLoadIC::GetKeyedAccessLoadModeFor().
LoadAccessorFromPrototype()
DirectHandle< Smi > v8::internal::LoadHandler::LoadAccessorFromPrototype (Isolate * isolate) [inline], [static]
Definition at line 80 of file handler-configuration-inl.h.
                                                                         {
  int config = KindBits::encode(Kind::kAccessorFromPrototype);
  return direct_handle(Smi::FromInt(config), isolate);
}
References v8::internal::direct_handle(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), and kAccessorFromPrototype.
Referenced by v8::internal::LoadIC::ComputeHandler().
LoadApiGetter()
Handle< Smi > v8::internal::LoadHandler::LoadApiGetter (Isolate * isolate) [inline], [static]
Definition at line 97 of file handler-configuration-inl.h.
                                                       {
  int config = KindBits::encode(Kind::kApiGetter);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), and kApiGetter.
Referenced by v8::internal::LoadIC::ComputeHandler().
LoadConstantFromPrototype()
Handle< Smi > v8::internal::LoadHandler::LoadConstantFromPrototype (Isolate * isolate) [inline], [static]
Definition at line 75 of file handler-configuration-inl.h.
                                                                   {
  int config = KindBits::encode(Kind::kConstantFromPrototype);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), and kConstantFromPrototype.
Referenced by v8::internal::LoadIC::ComputeHandler().
LoadElement()
Handle< Smi > v8::internal::LoadHandler::LoadElement (Isolate * isolate, ElementsKind elements_kind, bool is_js_array, KeyedAccessLoadMode load_mode) [inline], [static]
Definition at line 113 of file handler-configuration-inl.h.
                                                                    {
  DCHECK_IMPLIES(LoadModeHandlesHoles(load_mode),
                 IsHoleyElementsKind(elements_kind));
  int config = KindBits::encode(Kind::kElement) |
               AllowOutOfBoundsBits::encode(LoadModeHandlesOOB(load_mode)) |
               ElementsKindBits::encode(elements_kind) |
               AllowHandlingHole::encode(LoadModeHandlesHoles(load_mode)) |
               IsJsArrayBits::encode(is_js_array);
  return handle(Smi::FromInt(config), isolate);
}
References DCHECK_IMPLIES, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), v8::internal::IsHoleyElementsKind(), kElement, v8::internal::LoadModeHandlesHoles(), and v8::internal::LoadModeHandlesOOB().
Referenced by v8::internal::KeyedLoadIC::LoadElementHandler().
LoadField()
Handle< Smi > v8::internal::LoadHandler::LoadField (Isolate * isolate, FieldIndex field_index) [inline], [static]
Definition at line 58 of file handler-configuration-inl.h.
                                                                           {
  int config = KindBits::encode(Kind::kField) |
               IsInobjectBits::encode(field_index.is_inobject()) |
               IsDoubleBits::encode(field_index.is_double()) |
               FieldIndexBits::encode(field_index.index());
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), v8::internal::FieldIndex::index(), v8::internal::FieldIndex::is_double(), v8::internal::FieldIndex::is_inobject(), and kField.
Referenced by v8::internal::LoadIC::ComputeHandler().
LoadFromPrototype()
Handle< Object > v8::internal::LoadHandler::LoadFromPrototype (Isolate * isolate, DirectHandle< Map > receiver_map, DirectHandle< JSReceiver > holder, Tagged< Smi > smi_handler, MaybeObjectDirectHandle maybe_data1 = MaybeObjectDirectHandle(), MaybeObjectDirectHandle maybe_data2 = MaybeObjectDirectHandle()) [static]
Definition at line 115 of file handler-configuration.cc.
                                                                              {
  MaybeObjectDirectHandle data1;
  if (maybe_data1.is_null()) {
    data1 = MaybeObjectDirectHandle::Weak(holder);
  } else {
    data1 = maybe_data1;
  }
  int data_size = GetHandlerDataSize<LoadHandler>(
      isolate, &smi_handler, lookup_start_object_map, data1, maybe_data2);
  DirectHandle<UnionOf<Smi, Cell>> validity_cell =
      Map::GetOrCreatePrototypeChainValidityCell(lookup_start_object_map,
                                                 isolate);
  Handle<LoadHandler> handler = isolate->factory()->NewLoadHandler(data_size);
  handler->set_smi_handler(smi_handler);
  handler->set_validity_cell(*validity_cell);
  InitPrototypeChecks(isolate, direct_handle(handler), lookup_start_object_map,
                      data1, maybe_data2);
  return handler;
}
References v8::internal::DataHandler::data1(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), v8::internal::anonymous_namespace{handler-configuration.cc}::InitPrototypeChecks(), v8::internal::MaybeObjectDirectHandle::is_null(), v8::internal::Factory::NewLoadHandler(), v8::internal::DataHandler::smi_handler(), v8::internal::DataHandler::validity_cell(), and v8::internal::MaybeObjectDirectHandle::Weak().
Referenced by v8::internal::LoadIC::ComputeHandler().
LoadFullChain()
Handle< Object > v8::internal::LoadHandler::LoadFullChain (Isolate * isolate, DirectHandle< Map > receiver_map, const MaybeObjectDirectHandle & holder, Handle< Smi > smi_handler) [static]
Definition at line 143 of file handler-configuration.cc.
                                                                           {
  Tagged<Smi> smi_handler = *smi_handler_handle;
  MaybeObjectDirectHandle data1 = holder;
  int data_size = GetHandlerDataSize<LoadHandler>(
      isolate, &smi_handler, lookup_start_object_map, data1);
  DirectHandle<UnionOf<Smi, Cell>> validity_cell =
      Map::GetOrCreatePrototypeChainValidityCell(lookup_start_object_map,
                                                 isolate);
  if (IsSmi(*validity_cell)) {
    DCHECK_EQ(1, data_size);
    // Lookup on lookup start object isn't supported in case of a simple smi
    // handler.
    if (!LookupOnLookupStartObjectBits::decode(smi_handler.value())) {
      return smi_handler_handle;
    }
  }
  Handle<LoadHandler> handler = isolate->factory()->NewLoadHandler(data_size);
  handler->set_smi_handler(smi_handler);
  handler->set_validity_cell(*validity_cell);
  InitPrototypeChecks(isolate, direct_handle(handler), lookup_start_object_map,
                      data1);
  return handler;
}
References v8::internal::DataHandler::data1(), DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), v8::internal::anonymous_namespace{handler-configuration.cc}::InitPrototypeChecks(), v8::internal::IsSmi(), v8::internal::Factory::NewLoadHandler(), v8::internal::DataHandler::smi_handler(), and v8::internal::DataHandler::validity_cell().
Referenced by v8::internal::LoadIC::ComputeHandler().
LoadGeneric() [1/2]
Tagged< Smi > v8::internal::LoadHandler::LoadGeneric () [inline], [static]
Definition at line 54 of file handler-configuration-inl.h.
                                     {
  return Smi::FromInt(KindBits::encode(Kind::kGeneric));
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), and kGeneric.
Referenced by v8::internal::AccessorAssembler::GenerateLoadIC_Megamorphic(), v8::internal::FeedbackNexus::IsOneMapManyNames(), LoadGeneric(), and v8::internal::IC::UpdateOneMapManyNamesIC().
LoadGeneric() [2/2]
Handle< Smi > v8::internal::LoadHandler::LoadGeneric (Isolate * isolate) [inline], [static]
Definition at line 50 of file handler-configuration-inl.h.
                                                     {
  return handle(LoadGeneric(), isolate);
}
References v8::internal::handle(), and LoadGeneric().
LoadGlobal()
Handle< Smi > v8::internal::LoadHandler::LoadGlobal (Isolate * isolate) [inline], [static]
Definition at line 35 of file handler-configuration-inl.h.
                                                    {
  int config = KindBits::encode(Kind::kGlobal);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), and kGlobal.
Referenced by v8::internal::LoadIC::ComputeHandler().
LoadIndexedString()
Handle< Smi > v8::internal::LoadHandler::LoadIndexedString (Isolate * isolate, KeyedAccessLoadMode load_mode) [inline], [static]
Definition at line 138 of file handler-configuration-inl.h.
                                                                          {
  int config = KindBits::encode(Kind::kIndexedString) |
               AllowOutOfBoundsBits::encode(LoadModeHandlesOOB(load_mode));
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), kIndexedString, and v8::internal::LoadModeHandlesOOB().
Referenced by v8::internal::KeyedLoadIC::LoadElementHandler().
LoadInterceptor()
Handle< Smi > v8::internal::LoadHandler::LoadInterceptor (Isolate * isolate) [inline], [static]
Definition at line 40 of file handler-configuration-inl.h.
                                                         {
  int config = KindBits::encode(Kind::kInterceptor);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), and kInterceptor.
Referenced by v8::internal::LoadIC::ComputeHandler().
LoadModuleExport()
Handle< Smi > v8::internal::LoadHandler::LoadModuleExport (Isolate * isolate, int index) [inline], [static]
Definition at line 102 of file handler-configuration-inl.h.
                                                                     {
  int config =
      KindBits::encode(Kind::kModuleExport) | ExportsIndexBits::encode(index);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), v8::internal::index, and kModuleExport.
Referenced by v8::internal::LoadIC::ComputeHandler().
LoadNativeDataProperty()
Handle< Smi > v8::internal::LoadHandler::LoadNativeDataProperty (Isolate * isolate, int descriptor) [inline], [static]
Definition at line 90 of file handler-configuration-inl.h.
                                                                {
  int config = KindBits::encode(Kind::kNativeDataProperty) |
               DescriptorBits::encode(descriptor);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), and kNativeDataProperty.
Referenced by v8::internal::LoadIC::ComputeHandler().
LoadNonExistent() [1/2]
Handle< Smi > v8::internal::LoadHandler::LoadNonExistent (Isolate * isolate) [inline], [static]
Definition at line 108 of file handler-configuration-inl.h.
                                                         {
  int config = KindBits::encode(Kind::kNonExistent);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), and kNonExistent.
Referenced by v8::internal::LoadIC::ComputeHandler(), and v8::internal::LoadIC::UpdateCaches().
LoadNonExistent() [2/2]
Handle< Object > v8::internal::LoadHandler::LoadNonExistent (Isolate * isolate, DirectHandle< Map > lookup_start_object_map) [static]
Definition at line 172 of file handler-configuration.cc.
                                                                 {
  Tagged<Smi> smi_handler = Smi::FromInt(KindBits::encode(Kind::kNonExistent));
  MaybeObjectDirectHandle data1 =
      MaybeObjectDirectHandle(isolate->factory()->null_value());
  int data_size = GetHandlerDataSize<LoadHandler>(
      isolate, &smi_handler, lookup_start_object_map, data1);
  DirectHandle<PrototypeInfo> prototype_info;
  DirectHandle<UnionOf<Smi, Cell>> validity_cell =
      Map::GetOrCreatePrototypeChainValidityCell(lookup_start_object_map,
                                                 isolate, &prototype_info);
  // Try to fetch cached handler if it was already created.
  int handler_index;
  if (IsSmi(*validity_cell)) {
    DCHECK_EQ(1, data_size);
    // Lookup on lookup start object isn't supported in case of a simple smi
    // handler.
    if (!LookupOnLookupStartObjectBits::decode(smi_handler.value())) {
      return handle(smi_handler, isolate);
    }
    // Handlers with Smi validity cells are not cacheable.
    handler_index = -1;
  } else {
    // |smi_handler| already has do-access-check-on-lookup or lookup-on-receiver
    // bits set if necessary, so just use them in order to figure out the index
    // of the cached non-existent handler.
    int config = smi_handler.value();
    const uint32_t non_default_mask =
        DoAccessCheckOnLookupStartObjectBits::kMask |
        LookupOnLookupStartObjectBits::kMask;
    if (config & non_default_mask) {
      if (config & LookupOnLookupStartObjectBits::kMask) {
        handler_index =
            PrototypeInfo::kLoadNonExistentHandlerWithLookupOnReceiver;
      } else {
        DCHECK(config & DoAccessCheckOnLookupStartObjectBits::kMask);
        // This is a less often used version, we don't cache it.
        handler_index = -1;
      }
    } else {
      handler_index = PrototypeInfo::kLoadNonExistentHandlerDefault;
    }
    if (handler_index >= 0) {
      auto maybe_handler = prototype_info->cached_handler(handler_index);
      if (!IsSmi(maybe_handler)) {
        Tagged<LoadHandler> handler = Cast<LoadHandler>(maybe_handler);
        // Handler's validity cell must be the up-to-date one.
        DCHECK_EQ(handler->validity_cell(), *validity_cell);
        return handle(handler, isolate);
      }
      // Proceed with allocating a handler and caching it in prototype info.
    }
  }
  Handle<LoadHandler> handler = isolate->factory()->NewLoadHandler(data_size);
  handler->set_smi_handler(smi_handler);
  handler->set_validity_cell(*validity_cell);
  InitPrototypeChecks(isolate, direct_handle(handler), lookup_start_object_map,
                      data1);
  if (handler_index >= 0) {
    prototype_info->set_cached_handler(handler_index, *handler);
  }
  return handler;
}
References v8::internal::DataHandler::data1(), v8::internal::DCHECK(), DCHECK_EQ, v8::base::BitField< T, shift, size, U >::decode(), v8::internal::direct_handle(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::Map::GetOrCreatePrototypeChainValidityCell(), v8::internal::handle(), v8::internal::anonymous_namespace{handler-configuration.cc}::InitPrototypeChecks(), v8::internal::IsSmi(), v8::internal::PrototypeInfo::kLoadNonExistentHandlerDefault, v8::internal::PrototypeInfo::kLoadNonExistentHandlerWithLookupOnReceiver, v8::base::BitField< T, shift, size, U >::kMask, kNonExistent, v8::internal::Factory::NewLoadHandler(), v8::internal::DataHandler::smi_handler(), and v8::internal::DataHandler::validity_cell().
LoadNormal()
Handle< Smi > v8::internal::LoadHandler::LoadNormal (Isolate * isolate) [inline], [static]
Definition at line 30 of file handler-configuration-inl.h.
                                                    {
  int config = KindBits::encode(Kind::kNormal);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), and kNormal.
Referenced by v8::internal::LoadIC::ComputeHandler().
LoadProxy()
Handle< Smi > v8::internal::LoadHandler::LoadProxy (Isolate * isolate) [inline], [static]
Definition at line 85 of file handler-configuration-inl.h.
                                                   {
  int config = KindBits::encode(Kind::kProxy);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), and kProxy.
Referenced by v8::internal::LoadIC::ComputeHandler(), and v8::internal::KeyedLoadIC::LoadElementHandler().
LoadSlow()
Handle< Smi > v8::internal::LoadHandler::LoadSlow (Isolate * isolate) [inline], [static]
Definition at line 45 of file handler-configuration-inl.h.
                                                  {
  int config = KindBits::encode(Kind::kSlow);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), and kSlow.
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::AccessorAssembler::GenerateLoadIC_Megamorphic(), v8::internal::LoadIC::Load(), v8::internal::LoadGlobalIC::Load(), v8::internal::KeyedLoadIC::LoadElementHandler(), and v8::internal::LoadIC::UpdateCaches().
LoadWasmArrayElement()
DirectHandle< Smi > v8::internal::LoadHandler::LoadWasmArrayElement (Isolate * isolate, WasmValueType type) [inline], [static]
Definition at line 145 of file handler-configuration-inl.h.
                                                                        {
  int config = KindBits::encode(Kind::kElement) |
               IsWasmArrayBits::encode(true) | WasmArrayTypeBits::encode(type);
  return direct_handle(Smi::FromInt(config), isolate);
}
References v8::internal::direct_handle(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), kElement, and v8::internal::tracing::type.
LoadWasmStructField()
DirectHandle< Smi > v8::internal::LoadHandler::LoadWasmStructField (Isolate * isolate, WasmValueType type, int offset) [inline], [static]
Definition at line 66 of file handler-configuration-inl.h.
                                                               {
  int config = KindBits::encode(Kind::kField) | IsWasmStructBits::encode(true) |
               WasmFieldTypeBits::encode(type) |
               WasmFieldOffsetBits::encode(offset);
  return direct_handle(Smi::FromInt(config), isolate);
}
References v8::internal::direct_handle(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), kField, and v8::internal::tracing::type.
TransitionAndLoadElement()
Handle< Smi > v8::internal::LoadHandler::TransitionAndLoadElement (Isolate * isolate, ElementsKind kind_after_transition, KeyedAccessLoadMode load_mode) [inline], [static]
Definition at line 127 of file handler-configuration-inl.h.
                                   {
  int config = KindBits::encode(Kind::kElementWithTransition) |
               AllowOutOfBoundsBits::encode(LoadModeHandlesOOB(load_mode)) |
               ElementsKindBits::encode(kind_after_transition) |
               AllowHandlingHole::encode(LoadModeHandlesHoles(load_mode)) |
               IsJsArrayBits::encode(true);
  return handle(Smi::FromInt(config), isolate);
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::internal::handle(), kElementWithTransition, v8::internal::LoadModeHandlesHoles(), and v8::internal::LoadModeHandlesOOB().
Referenced by v8::internal::KeyedLoadIC::LoadElementHandler().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/handler-configuration.h
/mnt/V8SourceCode/src/ic/handler-configuration-inl.h
/mnt/V8SourceCode/src/ic/handler-configuration.cc