v8::base::VirtualAddressSpace Class Reference
#include <virtual-address-space.h>
Public Member Functions
VirtualAddressSpace ()
~VirtualAddressSpace () override=default
void SetRandomSeed (int64_t seed) override
Address RandomPageAddress () override
Address AllocatePages (Address hint, size_t size, size_t alignment, PagePermissions access) override
void FreePages (Address address, size_t size) override
bool SetPagePermissions (Address address, size_t size, PagePermissions access) override
bool AllocateGuardRegion (Address address, size_t size) override
void FreeGuardRegion (Address address, size_t size) override
Address AllocateSharedPages (Address hint, size_t size, PagePermissions permissions, PlatformSharedMemoryHandle handle, uint64_t offset) override
void FreeSharedPages (Address address, size_t size) override
bool CanAllocateSubspaces () override
std::unique_ptr< v8::VirtualAddressSpace > AllocateSubspace (Address hint, size_t size, size_t alignment, PagePermissions max_page_permissions) override
bool RecommitPages (Address address, size_t size, PagePermissions access) override
bool DiscardSystemPages (Address address, size_t size) override
bool DecommitPages (Address address, size_t size) override
Private Member Functions
void FreeSubspace (VirtualAddressSubspace *subspace) override
Detailed Description
Definition at line 51 of file virtual-address-space.h.
Constructor & Destructor Documentation
VirtualAddressSpace()
v8::base::VirtualAddressSpace::VirtualAddressSpace ()
Definition at line 53 of file virtual-address-space.cc.
    : VirtualAddressSpaceBase(OS::CommitPageSize(), OS::AllocatePageSize(),
                              kNullAddress,
                              std::numeric_limits<uintptr_t>::max(),
                              PagePermissions::kReadWriteExecute) {
#if V8_OS_WIN
  // On Windows, this additional step is required to lookup the VirtualAlloc2
  // and friends functions.
  OS::EnsureWin32MemoryAPILoaded();
#endif // V8_OS_WIN
  DCHECK(bits::IsPowerOfTwo(page_size()));
  DCHECK(bits::IsPowerOfTwo(allocation_granularity()));
  DCHECK_GE(allocation_granularity(), page_size());
  DCHECK(IsAligned(allocation_granularity(), page_size()));
}
References DCHECK, DCHECK_GE, IsAligned(), v8::base::bits::IsPowerOfTwo(), and v8::kReadWriteExecute.
 VirtualAddressSpace()
v8::base::VirtualAddressSpace::~VirtualAddressSpace () [override], [default]
Member Function Documentation
AllocateGuardRegion()
bool v8::base::VirtualAddressSpace::AllocateGuardRegion (Address address, size_t size) [override]
Definition at line 105 of file virtual-address-space.cc.
                                                                          {
  DCHECK(IsAligned(address, allocation_granularity()));
  DCHECK(IsAligned(size, allocation_granularity()));
  void* hint = reinterpret_cast<void*>(address);
  void* result = OS::Allocate(hint, size, allocation_granularity(),
                              OS::MemoryPermission::kNoAccess);
  if (result && result != hint) {
    OS::Free(result, size);
  }
  return result == hint;
}
References v8::base::OS::Allocate(), DCHECK, v8::base::OS::Free(), IsAligned(), v8::base::OS::kNoAccess, v8::base::internal::result, and size().
AllocatePages()
Address v8::base::VirtualAddressSpace::AllocatePages (Address hint, size_t size, size_t alignment, PagePermissions access) [override]
Definition at line 77 of file virtual-address-space.cc.
                                                                        {
  DCHECK(IsAligned(alignment, allocation_granularity()));
  DCHECK(IsAligned(hint, alignment));
  DCHECK(IsAligned(size, allocation_granularity()));
  return reinterpret_cast<Address>(
      OS::Allocate(reinterpret_cast<void*>(hint), size, alignment,
                   static_cast<OS::MemoryPermission>(permissions)));
}
References v8::base::OS::Allocate(), DCHECK, IsAligned(), and size().
AllocateSharedPages()
Address v8::base::VirtualAddressSpace::AllocateSharedPages (Address hint, size_t size, PagePermissions permissions, PlatformSharedMemoryHandle handle, uint64_t offset) [override]
Definition at line 129 of file virtual-address-space.cc.
                                                        {
  DCHECK(IsAligned(hint, allocation_granularity()));
  DCHECK(IsAligned(size, allocation_granularity()));
  DCHECK(IsAligned(offset, allocation_granularity()));
  return reinterpret_cast<Address>(OS::AllocateShared(
      reinterpret_cast<void*>(hint), size,
      static_cast<OS::MemoryPermission>(permissions), handle, offset));
}
References v8::base::OS::AllocateShared(), DCHECK, v8::internal::handle(), IsAligned(), and size().
AllocateSubspace()
std::unique_ptr< v8::VirtualAddressSpace > v8::base::VirtualAddressSpace::AllocateSubspace (Address hint, size_t size, size_t alignment, PagePermissions max_page_permissions) [override]
Definition at line 148 of file virtual-address-space.cc.
                                          {
  DCHECK(IsAligned(alignment, allocation_granularity()));
  DCHECK(IsAligned(hint, alignment));
  DCHECK(IsAligned(size, allocation_granularity()));
  std::optional<AddressSpaceReservation> reservation =
      OS::CreateAddressSpaceReservation(
          reinterpret_cast<void*>(hint), size, alignment,
          static_cast<OS::MemoryPermission>(max_page_permissions));
  if (!reservation.has_value())
    return std::unique_ptr<v8::VirtualAddressSpace>();
  return std::unique_ptr<v8::VirtualAddressSpace>(
      new VirtualAddressSubspace(*reservation, this, max_page_permissions));
}
References v8::base::OS::CreateAddressSpaceReservation(), DCHECK, IsAligned(), size(), and v8::base::VirtualAddressSpaceBase::VirtualAddressSubspace.
CanAllocateSubspaces()
bool v8::base::VirtualAddressSpace::CanAllocateSubspaces () [override]
Definition at line 125 of file virtual-address-space.cc.
                                               {
  return OS::CanReserveAddressSpace();
}
References v8::base::OS::CanReserveAddressSpace().
DecommitPages()
bool v8::base::VirtualAddressSpace::DecommitPages (Address address, size_t size) [override]
Definition at line 181 of file virtual-address-space.cc.
                                                                    {
  DCHECK(IsAligned(address, page_size()));
  DCHECK(IsAligned(size, page_size()));
  return OS::DecommitPages(reinterpret_cast<void*>(address), size);
}
References DCHECK, v8::base::OS::DecommitPages(), IsAligned(), and size().
DiscardSystemPages()
bool v8::base::VirtualAddressSpace::DiscardSystemPages (Address address, size_t size) [override]
Definition at line 174 of file virtual-address-space.cc.
                                                                         {
  DCHECK(IsAligned(address, page_size()));
  DCHECK(IsAligned(size, page_size()));
  return OS::DiscardSystemPages(reinterpret_cast<void*>(address), size);
}
References DCHECK, v8::base::OS::DiscardSystemPages(), IsAligned(), and size().
FreeGuardRegion()
void v8::base::VirtualAddressSpace::FreeGuardRegion (Address address, size_t size) [override]
Definition at line 118 of file virtual-address-space.cc.
                                                                      {
  DCHECK(IsAligned(address, allocation_granularity()));
  DCHECK(IsAligned(size, allocation_granularity()));
  OS::Free(reinterpret_cast<void*>(address), size);
}
References DCHECK, v8::base::OS::Free(), IsAligned(), and size().
FreePages()
void v8::base::VirtualAddressSpace::FreePages (Address address, size_t size) [override]
Definition at line 89 of file virtual-address-space.cc.
                                                                {
  DCHECK(IsAligned(address, allocation_granularity()));
  DCHECK(IsAligned(size, allocation_granularity()));
  OS::Free(reinterpret_cast<void*>(address), size);
}
References DCHECK, v8::base::OS::Free(), IsAligned(), and size().
FreeSharedPages()
void v8::base::VirtualAddressSpace::FreeSharedPages (Address address, size_t size) [override]
Definition at line 141 of file virtual-address-space.cc.
                                                                      {
  DCHECK(IsAligned(address, allocation_granularity()));
  DCHECK(IsAligned(size, allocation_granularity()));
  OS::FreeShared(reinterpret_cast<void*>(address), size);
}
References DCHECK, v8::base::OS::FreeShared(), IsAligned(), and size().
FreeSubspace()
void v8::base::VirtualAddressSpace::FreeSubspace (VirtualAddressSubspace * subspace) [override], [private], [virtual]
Implements v8::base::VirtualAddressSpaceBase.
Definition at line 188 of file virtual-address-space.cc.
                                                                       {
  OS::FreeAddressSpaceReservation(subspace->reservation_);
}
References v8::base::OS::FreeAddressSpaceReservation(), and v8::base::VirtualAddressSubspace::reservation_.
RandomPageAddress()
Address v8::base::VirtualAddressSpace::RandomPageAddress () [override]
Definition at line 73 of file virtual-address-space.cc.
                                               {
  return reinterpret_cast<Address>(OS::GetRandomMmapAddr());
}
References v8::base::OS::GetRandomMmapAddr().
RecommitPages()
bool v8::base::VirtualAddressSpace::RecommitPages (Address address, size_t size, PagePermissions access) [override]
Definition at line 165 of file virtual-address-space.cc.
                                                                     {
  DCHECK(IsAligned(address, page_size()));
  DCHECK(IsAligned(size, page_size()));
  return OS::RecommitPages(reinterpret_cast<void*>(address), size,
                           static_cast<OS::MemoryPermission>(permissions));
}
References DCHECK, IsAligned(), v8::base::OS::RecommitPages(), and size().
SetPagePermissions()
bool v8::base::VirtualAddressSpace::SetPagePermissions (Address address, size_t size, PagePermissions access) [override]
Definition at line 96 of file virtual-address-space.cc.
                                                                          {
  DCHECK(IsAligned(address, page_size()));
  DCHECK(IsAligned(size, page_size()));
  return OS::SetPermissions(reinterpret_cast<void*>(address), size,
                            static_cast<OS::MemoryPermission>(permissions));
}
References DCHECK, IsAligned(), v8::base::OS::SetPermissions(), and size().
SetRandomSeed()
void v8::base::VirtualAddressSpace::SetRandomSeed (int64_t seed) [override]
Definition at line 69 of file virtual-address-space.cc.
                                                    {
  OS::SetRandomMmapSeed(seed);
}
References v8::base::OS::SetRandomMmapSeed().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/virtual-address-space.h
/mnt/V8SourceCode/src/base/virtual-address-space.cc