v8::internal::CallOptimization Class Reference
#include <call-optimization.h>
Public Types
enum HolderLookup { kHolderNotFound
, kHolderIsReceiver
, kHolderFound
 }
Public Member Functions
template<class IsolateT >
CallOptimization (IsolateT *isolate, Handle< Object > function)
std::optional< Tagged< NativeContext > > GetAccessorContext (Tagged< Map > holder_map) const
bool IsCrossContextLazyAccessorPair (Tagged< NativeContext > native_context, Tagged< Map > holder_map) const
bool is_constant_call () const
bool accept_any_receiver () const
bool requires_signature_check () const
DirectHandle< JSFunction > constant_function () const
bool is_simple_api_call () const
DirectHandle< FunctionTemplateInfo > expected_receiver_type () const
DirectHandle< FunctionTemplateInfo > api_call_info () const
template<class IsolateT >
Handle< JSObject > LookupHolderOfExpectedType (IsolateT *isolate, DirectHandle< Map > receiver_map, HolderLookup *holder_lookup) const
bool IsCompatibleReceiverMap (DirectHandle< JSObject > api_holder, Handle< JSObject > holder, HolderLookup) const
Private Member Functions
template<class IsolateT >
void Initialize (IsolateT *isolate, Handle< JSFunction > function)
template<class IsolateT >
void Initialize (IsolateT *isolate, Handle< FunctionTemplateInfo > function_template_info)
template<class IsolateT >
void AnalyzePossibleApiFunction (IsolateT *isolate, DirectHandle< JSFunction > function)
Private Attributes
Handle< JSFunction > constant_function_
Handle< FunctionTemplateInfo > expected_receiver_type_
Handle< FunctionTemplateInfo > api_call_info_
bool is_simple_api_call_ = false
bool accept_any_receiver_ = false
Detailed Description
Definition at line 17 of file call-optimization.h.
Member Enumeration Documentation
HolderLookup
enum v8::internal::CallOptimization::HolderLookup
Enumerator
kHolderNotFound
kHolderIsReceiver
kHolderFound
Definition at line 57 of file call-optimization.h.
{ kHolderNotFound, kHolderIsReceiver, kHolderFound };
Constructor & Destructor Documentation
CallOptimization()
template<class IsolateT >
template v8::internal::CallOptimization::CallOptimization (IsolateT * isolate, Handle< Object > function)
Definition at line 15 of file call-optimization.cc.
                                                                             {
  if (IsJSFunction(*function)) {
    Initialize(isolate, Cast<JSFunction>(function));
  } else if (IsFunctionTemplateInfo(*function)) {
    Initialize(isolate, Cast<FunctionTemplateInfo>(function));
  }
}
References Initialize().
Member Function Documentation
accept_any_receiver()
bool v8::internal::CallOptimization::accept_any_receiver () const [inline]
Definition at line 35 of file call-optimization.h.
{ return accept_any_receiver_; }
References accept_any_receiver_.
Referenced by v8::internal::IC::UpdateMegaDOMIC().
AnalyzePossibleApiFunction()
template<class IsolateT >
void v8::internal::CallOptimization::AnalyzePossibleApiFunction (IsolateT * isolate, DirectHandle< JSFunction > function) [private]
Definition at line 142 of file call-optimization.cc.
                                                          {
  if (!function->shared()->IsApiFunction()) return;
  Handle<FunctionTemplateInfo> function_template_info(
      function->shared()->api_func_data(), isolate);
  Initialize(isolate, function_template_info);
}
References Initialize().
Referenced by Initialize().
api_call_info()
DirectHandle<FunctionTemplateInfo> v8::internal::CallOptimization::api_call_info () const [inline]
Definition at line 52 of file call-optimization.h.
                                                           {
    DCHECK(is_simple_api_call());
    return api_call_info_;
  }
References api_call_info_, v8::internal::DCHECK(), and is_simple_api_call().
Referenced by v8::internal::LoadIC::ComputeHandler(), and v8::internal::StoreIC::ComputeHandler().
constant_function()
DirectHandle<JSFunction> v8::internal::CallOptimization::constant_function () const [inline]
Definition at line 40 of file call-optimization.h.
                                                     {
    DCHECK(is_constant_call());
    return constant_function_;
  }
References constant_function_, v8::internal::DCHECK(), and is_constant_call().
expected_receiver_type()
DirectHandle<FunctionTemplateInfo> v8::internal::CallOptimization::expected_receiver_type () const [inline]
Definition at line 47 of file call-optimization.h.
                                                                    {
    DCHECK(is_simple_api_call());
    return expected_receiver_type_;
  }
References v8::internal::DCHECK(), expected_receiver_type_, and is_simple_api_call().
GetAccessorContext()
std::optional< Tagged< NativeContext > > v8::internal::CallOptimization::GetAccessorContext (Tagged< Map > holder_map) const
Definition at line 29 of file call-optimization.cc.
                                  {
  if (is_constant_call()) {
    return constant_function_->native_context();
  }
  Tagged<Object> maybe_native_context =
      holder_map->map()->native_context_or_null();
  if (IsNull(maybe_native_context)) {
    // The holder is a remote object which doesn't have a creation context.
    return {};
  }
  DCHECK(IsNativeContext(maybe_native_context));
  return Cast<NativeContext>(maybe_native_context);
}
References constant_function_, v8::internal::DCHECK(), is_constant_call(), and v8::internal::IsNull().
Referenced by v8::internal::anonymous_namespace{ic.cc}::GetAccessorContext(), and IsCrossContextLazyAccessorPair().
Initialize() [1/2]
template<class IsolateT >
void v8::internal::CallOptimization::Initialize (IsolateT * isolate, Handle< FunctionTemplateInfo > function_template_info) [private]
Definition at line 118 of file call-optimization.cc.
                                                                            {
  if (!function_template_info->has_callback(isolate)) return;
  api_call_info_ = function_template_info;
  Tagged<HeapObject> signature = function_template_info->signature();
  if (!IsUndefined(signature, isolate)) {
    expected_receiver_type_ =
        handle(Cast<FunctionTemplateInfo>(signature), isolate);
  }
  is_simple_api_call_ = true;
  accept_any_receiver_ = function_template_info->accept_any_receiver();
}
References accept_any_receiver_, api_call_info_, expected_receiver_type_, v8::internal::handle(), and is_simple_api_call_.
Initialize() [2/2]
template<class IsolateT >
void v8::internal::CallOptimization::Initialize (IsolateT * isolate, Handle< JSFunction > function) [private]
Definition at line 133 of file call-optimization.cc.
                                                               {
  if (function.is_null() || !function->is_compiled(isolate)) return;
  constant_function_ = function;
  AnalyzePossibleApiFunction(isolate, function);
}
References AnalyzePossibleApiFunction(), and constant_function_.
Referenced by AnalyzePossibleApiFunction(), and CallOptimization().
is_constant_call()
bool v8::internal::CallOptimization::is_constant_call () const [inline]
Definition at line 34 of file call-optimization.h.
{ return !constant_function_.is_null(); }
References constant_function_.
Referenced by constant_function(), GetAccessorContext(), and IsCrossContextLazyAccessorPair().
is_simple_api_call()
bool v8::internal::CallOptimization::is_simple_api_call () const [inline]
Definition at line 45 of file call-optimization.h.
{ return is_simple_api_call_; }
References is_simple_api_call_.
Referenced by api_call_info(), v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), expected_receiver_type(), IsCompatibleReceiverMap(), LookupHolderOfExpectedType(), and v8::internal::IC::UpdateMegaDOMIC().
IsCompatibleReceiverMap()
bool v8::internal::CallOptimization::IsCompatibleReceiverMap (DirectHandle< JSObject > api_holder, Handle< JSObject > holder, HolderLookup holder_lookup) const
Definition at line 92 of file call-optimization.cc.
                                      {
  DCHECK(is_simple_api_call());
  switch (holder_lookup) {
    case kHolderNotFound:
      return false;
    case kHolderIsReceiver:
      return true;
    case kHolderFound:
      if (api_holder.is_identical_to(holder)) return true;
      // Check if holder is in prototype chain of api_holder.
      {
        Tagged<JSObject> object = *api_holder;
        while (true) {
          Tagged<Object> prototype = object->map()->prototype();
          if (!IsJSObject(prototype)) return false;
          if (prototype == *holder) return true;
          object = Cast<JSObject>(prototype);
        }
      }
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), v8::internal::DirectHandle< T >::is_identical_to(), is_simple_api_call(), kHolderFound, kHolderIsReceiver, kHolderNotFound, v8::internal::prototype, and v8::internal::UNREACHABLE().
Referenced by v8::internal::LoadIC::ComputeHandler(), and v8::internal::StoreIC::ComputeHandler().
IsCrossContextLazyAccessorPair()
bool v8::internal::CallOptimization::IsCrossContextLazyAccessorPair (Tagged< NativeContext > native_context, Tagged< Map > holder_map) const
Definition at line 44 of file call-optimization.cc.
                                                                        {
  DCHECK(IsNativeContext(native_context));
  if (is_constant_call()) return false;
  std::optional<Tagged<NativeContext>> maybe_context =
      GetAccessorContext(holder_map);
  if (!maybe_context.has_value()) {
    // The holder is a remote object which doesn't have a creation context.
    return true;
  }
  return native_context != maybe_context.value();
}
References v8::internal::DCHECK(), GetAccessorContext(), is_constant_call(), and v8::internal::native_context.
LookupHolderOfExpectedType()
template<class IsolateT >
template Handle< JSObject > v8::internal::CallOptimization::LookupHolderOfExpectedType (IsolateT * isolate, DirectHandle< Map > receiver_map, HolderLookup * holder_lookup) const
Definition at line 58 of file call-optimization.cc.
                                       {
  DCHECK(is_simple_api_call());
  if (!IsJSObjectMap(*object_map)) {
    *holder_lookup = kHolderNotFound;
    return Handle<JSObject>::null();
  }
  if (expected_receiver_type_.is_null() ||
      expected_receiver_type_->IsTemplateFor(*object_map)) {
    *holder_lookup = kHolderIsReceiver;
    return Handle<JSObject>::null();
  }
  if (IsJSGlobalProxyMap(*object_map) && !IsNull(object_map->prototype())) {
    Tagged<JSObject> raw_prototype = Cast<JSObject>(object_map->prototype());
    Handle<JSObject> prototype(raw_prototype, isolate);
    object_map = direct_handle(prototype->map(), isolate);
    if (expected_receiver_type_->IsTemplateFor(*object_map)) {
      *holder_lookup = kHolderFound;
      return prototype;
    }
  }
  *holder_lookup = kHolderNotFound;
  return Handle<JSObject>::null();
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), expected_receiver_type_, is_simple_api_call(), v8::internal::IsNull(), kHolderFound, kHolderIsReceiver, kHolderNotFound, v8::internal::Handle< T >::null(), and v8::internal::prototype.
Referenced by v8::internal::LoadIC::ComputeHandler(), v8::internal::StoreIC::ComputeHandler(), and v8::internal::IC::UpdateMegaDOMIC().
requires_signature_check()
bool v8::internal::CallOptimization::requires_signature_check () const [inline]
Definition at line 36 of file call-optimization.h.
                                        {
    return !expected_receiver_type_.is_null();
  }
References expected_receiver_type_.
Referenced by v8::internal::IC::UpdateMegaDOMIC().
Member Data Documentation
accept_any_receiver_
bool v8::internal::CallOptimization::accept_any_receiver_ = false [private]
Definition at line 87 of file call-optimization.h.
Referenced by accept_any_receiver(), and Initialize().
api_call_info_
Handle<FunctionTemplateInfo> v8::internal::CallOptimization::api_call_info_ [private]
Definition at line 82 of file call-optimization.h.
Referenced by api_call_info(), and Initialize().
constant_function_
Handle<JSFunction> v8::internal::CallOptimization::constant_function_ [private]
Definition at line 80 of file call-optimization.h.
Referenced by constant_function(), GetAccessorContext(), Initialize(), and is_constant_call().
expected_receiver_type_
Handle<FunctionTemplateInfo> v8::internal::CallOptimization::expected_receiver_type_ [private]
Definition at line 81 of file call-optimization.h.
Referenced by expected_receiver_type(), Initialize(), LookupHolderOfExpectedType(), and requires_signature_check().
is_simple_api_call_
bool v8::internal::CallOptimization::is_simple_api_call_ = false [private]
Definition at line 86 of file call-optimization.h.
Referenced by Initialize(), and is_simple_api_call().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/call-optimization.h
/mnt/V8SourceCode/src/ic/call-optimization.cc