v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency Class Reference
Public Member Functions
OwnConstantDataPropertyDependency (JSHeapBroker *broker, JSObjectRef holder, MapRef map, FieldIndex index, ObjectRef value)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
JSHeapBroker *const broker_
JSObjectRef const holder_
MapRef const map_
FieldIndex const index_
ObjectRef const value_
Additional Inherited Members
Detailed Description
Definition at line 453 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
OwnConstantDataPropertyDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency::OwnConstantDataPropertyDependency (JSHeapBroker * broker, JSObjectRef holder, MapRef map, FieldIndex index, ObjectRef value) [inline]
Definition at line 455 of file compilation-dependencies.cc.
      : CompilationDependency(kOwnConstantDataProperty),
        broker_(broker),
        holder_(holder),
        map_(map),
        index_(index),
        value_(value) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 493 of file compilation-dependencies.cc.
                                                                {
    const OwnConstantDataPropertyDependency* const zat =
        that->AsOwnConstantDataProperty();
    return holder_.equals(zat->holder_) && map_.equals(zat->map_) &&
           index_ == zat->index_ && value_.equals(zat->value_);
  }
References holder_, index_, map_, and value_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 487 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(holder_), h(map_), index_.bit_field(),
                              h(value_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 483 of file compilation-dependencies.cc.
                                                                               {
  }
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 465 of file compilation-dependencies.cc.
                                                    {
    if (holder_.object()->map() != *map_.object()) {
      TRACE_BROKER_MISSING(broker_,
                           "Map change detected in " << holder_.object());
      return false;
    }
    DisallowGarbageCollection no_heap_allocation;
    Tagged<Object> current_value = holder_.object()->RawFastPropertyAt(index_);
    Tagged<Object> used_value = *value_.object();
    if (current_value != used_value) {
      TRACE_BROKER_MISSING(broker_, "Constant property value changed in "
                                        << holder_.object() << " at FieldIndex "
                                        << index_.property_index());
      return false;
    }
    return true;
  }
References v8::internal::compiler::CompilationDependencies::broker_, and TRACE_BROKER_MISSING.
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency::broker_ [private]
Definition at line 500 of file compilation-dependencies.cc.
holder_
JSObjectRef const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency::holder_ [private]
Definition at line 501 of file compilation-dependencies.cc.
Referenced by Equals().
index_
FieldIndex const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency::index_ [private]
Definition at line 503 of file compilation-dependencies.cc.
Referenced by Equals().
map_
MapRef const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency::map_ [private]
Definition at line 502 of file compilation-dependencies.cc.
Referenced by Equals().
value_
ObjectRef const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDataPropertyDependency::value_ [private]
Definition at line 504 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc