v8::internal::compiler::CallFrequency Class Reference
#include <js-operator.h>
Public Member Functions
CallFrequency ()
CallFrequency (float value)
bool IsKnown () const
bool IsUnknown () const
float value () const
bool operator== (CallFrequency const &that) const
bool operator!= (CallFrequency const &that) const
Static Public Attributes
static constexpr float kNoFeedbackCallFrequency = -1
Private Attributes
float value_
Friends
size_t hash_value (CallFrequency const &f)
Detailed Description
Definition at line 82 of file js-operator.h.
Constructor & Destructor Documentation
CallFrequency() [1/2]
v8::internal::compiler::CallFrequency::CallFrequency () [inline]
Definition at line 84 of file js-operator.h.
: value_(std::numeric_limits<float>::quiet_NaN()) {}
CallFrequency() [2/2]
v8::internal::compiler::CallFrequency::CallFrequency (float value) [inline], [explicit]
Definition at line 85 of file js-operator.h.
                                      : value_(value) {
    DCHECK(!std::isnan(value));
  }
References v8::internal::DCHECK(), and value().
Member Function Documentation
IsKnown()
bool v8::internal::compiler::CallFrequency::IsKnown () const [inline]
Definition at line 89 of file js-operator.h.
{ return !IsUnknown(); }
References IsUnknown().
Referenced by v8::internal::compiler::JSInliningHeuristic::Reduce(), and value().
IsUnknown()
bool v8::internal::compiler::CallFrequency::IsUnknown () const [inline]
Definition at line 90 of file js-operator.h.
{ return std::isnan(value_); }
References value_.
Referenced by IsKnown(), v8::internal::compiler::JSInliningHeuristic::CandidateCompare::operator()(), and v8::internal::compiler::operator<<().
operator!=()
bool v8::internal::compiler::CallFrequency::operator!= (CallFrequency const & that) const [inline]
Definition at line 100 of file js-operator.h.
{ return !(*this == that); }
operator==()
bool v8::internal::compiler::CallFrequency::operator== (CallFrequency const & that) const [inline]
Definition at line 96 of file js-operator.h.
                                                   {
    return base::bit_cast<uint32_t>(this->value_) ==
           base::bit_cast<uint32_t>(that.value_);
  }
References value_.
value()
float v8::internal::compiler::CallFrequency::value () const [inline]
Definition at line 91 of file js-operator.h.
                      {
    DCHECK(IsKnown());
    return value_;
  }
References v8::internal::DCHECK(), IsKnown(), and value_.
Referenced by CallFrequency(), v8::internal::compiler::JSInliningHeuristic::CandidateCompare::operator()(), v8::internal::compiler::operator<<(), and v8::internal::compiler::JSInliningHeuristic::Reduce().
Friends And Related Function Documentation
hash_value
size_t hash_value (CallFrequency const & f) [friend]
Definition at line 102 of file js-operator.h.
                                                   {
    return base::bit_cast<uint32_t>(f.value_);
  }
Member Data Documentation
kNoFeedbackCallFrequency
constexpr float v8::internal::compiler::CallFrequency::kNoFeedbackCallFrequency = -1 [static], [constexpr]
Definition at line 106 of file js-operator.h.
value_
float v8::internal::compiler::CallFrequency::value_ [private]
Definition at line 109 of file js-operator.h.
Referenced by IsUnknown(), operator==(), and value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h