v8::internal::Sweeper Class Reference
#include <sweeper.h>
Classes
class ConcurrentMajorSweeper
class ConcurrentMinorSweeper
class LocalSweeper
class MajorSweeperJob
class MinorSweeperJob
class PauseMajorSweepingScope
class SweepingState
Public Types
enum class SweepingMode { kEagerDuringGC
, kLazyOrConcurrent
 }
using SweepingList = std::vector< PageMetadata * >
using SweptList = std::vector< PageMetadata * >
Public Member Functions
Sweeper (Heap *heap)
~Sweeper ()
bool major_sweeping_in_progress () const
bool minor_sweeping_in_progress () const
bool sweeping_in_progress () const
bool sweeping_in_progress_for_space (AllocationSpace space) const
void TearDown ()
void AddPage (AllocationSpace space, PageMetadata *page)
void AddNewSpacePage (PageMetadata *page)
void AddPromotedPage (MutablePageMetadata *chunk)
bool ParallelSweepSpace (AllocationSpace identity, SweepingMode sweeping_mode, uint32_t max_pages=std::numeric_limits< uint32_t >::max())
void EnsurePageIsSwept (PageMetadata *page)
void WaitForPageToBeSwept (PageMetadata *page)
void StartMajorSweeping ()
void StartMinorSweeping ()
void InitializeMajorSweeping ()
void InitializeMinorSweeping ()
V8_EXPORT_PRIVATE void StartMajorSweeperTasks ()
V8_EXPORT_PRIVATE void StartMinorSweeperTasks ()
void FinishMajorJobs ()
void EnsureMajorCompleted ()
void FinishMinorJobs ()
void EnsureMinorCompleted ()
bool AreMinorSweeperTasksRunning () const
bool AreMajorSweeperTasksRunning () const
bool UsingMajorSweeperTasks () const
PageMetadata * GetSweptPageSafe (PagedSpaceBase *space)
SweptList GetAllSweptPagesSafe (PagedSpaceBase *space)
bool IsSweepingDoneForSpace (AllocationSpace space) const
GCTracer::Scope::ScopeId GetTracingScope (AllocationSpace space, bool is_joining_thread)
bool IsIteratingPromotedPages () const
void ContributeAndWaitForPromotedPagesIteration ()
bool ShouldRefillFreelistForSpace (AllocationSpace space) const
void SweepEmptyNewSpacePage (PageMetadata *page)
uint64_t GetTraceIdForFlowEvent (GCTracer::Scope::ScopeId scope_id) const
Static Public Member Functions
static V8_EXPORT_PRIVATE std::optional< base::AddressRegion > ComputeDiscardMemoryArea (Address start, Address end)
Private Types
enum class SweepingScope { kMinor
, kMajor
 }
Private Member Functions
NonAtomicMarkingState * marking_state () const
void RawSweep (PageMetadata *p, FreeSpaceTreatmentMode free_space_treatment_mode, SweepingMode sweeping_mode, bool should_reduce_memory)
void ZeroOrDiscardUnusedMemory (PageMetadata *page, Address addr, size_t size)
void AddPageImpl (AllocationSpace space, PageMetadata *page)
template<typename Callback >
void ForAllSweepingSpaces (Callback callback) const
size_t FreeAndProcessFreedMemory (Address free_start, Address free_end, PageMetadata *page, Space *space, FreeSpaceTreatmentMode free_space_treatment_mode, bool should_reduce_memory)
void CleanupRememberedSetEntriesForFreedMemory (Address free_start, Address free_end, PageMetadata *page, bool record_free_ranges, TypedSlotSet::FreeRangesMap *free_ranges_map, SweepingMode sweeping_mode)
void CleanupTypedSlotsInFreeMemory (PageMetadata *page, const TypedSlotSet::FreeRangesMap &free_ranges_map, SweepingMode sweeping_mode)
void ClearMarkBitsAndHandleLivenessStatistics (PageMetadata *page, size_t live_bytes)
size_t ConcurrentMinorSweepingPageCount ()
size_t ConcurrentMajorSweepingPageCount ()
PageMetadata * GetSweepingPageSafe (AllocationSpace space)
MutablePageMetadata * GetPromotedPageSafe ()
bool TryRemoveSweepingPageSafe (AllocationSpace space, PageMetadata *page)
bool TryRemovePromotedPageSafe (MutablePageMetadata *chunk)
void PrepareToBeSweptPage (AllocationSpace space, PageMetadata *page)
void PrepareToBeIteratedPromotedPage (PageMetadata *page)
void NotifyPromotedPageIterationFinished (MutablePageMetadata *chunk)
void NotifyPromotedPagesIterationFinished ()
void AddSweptPage (PageMetadata *page, AllocationSpace identity)
Static Private Member Functions
static bool IsValidSweepingSpace (AllocationSpace space)
static int GetSweepSpaceIndex (AllocationSpace space)
Private Attributes
Heap *const heap_
NonAtomicMarkingState *const marking_state_
base::Mutex mutex_
base::ConditionVariable cv_page_swept_
SweptList swept_list_ [kNumberOfSweepingSpaces]
SweepingList sweeping_list_ [kNumberOfSweepingSpaces]
std::atomic< bool > has_sweeping_work_ [kNumberOfSweepingSpaces] {false}
std::atomic< bool > has_swept_pages_ [kNumberOfSweepingSpaces] {false}
std::vector< MutablePageMetadata * > sweeping_list_for_promoted_page_iteration_
LocalSweeper main_thread_local_sweeper_
SweepingState< SweepingScope::kMajor > major_sweeping_state_ {this}
SweepingState< SweepingScope::kMinor > minor_sweeping_state_ {this}
size_t promoted_pages_for_iteration_count_ = 0
std::atomic< size_t > iterated_promoted_pages_count_ {0}
base::Mutex promoted_pages_iteration_notification_mutex_
base::ConditionVariable promoted_pages_iteration_notification_variable_
std::atomic< bool > promoted_page_iteration_in_progress_ {false}
Static Private Attributes
static constexpr int kNumberOfSweepingSpaces
Detailed Description
Definition at line 37 of file sweeper.h.
Member Typedef Documentation
SweepingList
using v8::internal::Sweeper::SweepingList = std::vector<PageMetadata*>
Definition at line 52 of file sweeper.h.
SweptList
using v8::internal::Sweeper::SweptList = std::vector<PageMetadata*>
Definition at line 53 of file sweeper.h.
Member Enumeration Documentation
SweepingMode
enum v8::internal::Sweeper::SweepingMode [strong]
Enumerator
kEagerDuringGC
kLazyOrConcurrent
Definition at line 55 of file sweeper.h.
{ kEagerDuringGC, kLazyOrConcurrent };
SweepingScope
enum v8::internal::Sweeper::SweepingScope [strong], [private]
Enumerator
kMinor
kMajor
Definition at line 273 of file sweeper.h.
{ kMinor, kMajor };
Constructor & Destructor Documentation
Sweeper()
v8::internal::Sweeper::Sweeper (Heap * heap) [explicit]
Definition at line 684 of file sweeper.cc.
    : heap_(heap),
      marking_state_(heap_->non_atomic_marking_state()),
      main_thread_local_sweeper_(this) {}
 Sweeper()
v8::internal::Sweeper::~Sweeper () [default]
Member Function Documentation
AddNewSpacePage()
void v8::internal::Sweeper::AddNewSpacePage (PageMetadata * page)
Definition at line 1390 of file sweeper.cc.
                                                {
  DCHECK_EQ(NEW_SPACE, page->owner_identity());
  DCHECK_LE(page->AgeInNewSpace(), v8_flags.minor_ms_max_page_age);
  size_t live_bytes = page->live_bytes();
  heap_->IncrementNewSpaceSurvivingObjectSize(live_bytes);
  heap_->IncrementYoungSurvivorsCounter(live_bytes);
  AddPageImpl(NEW_SPACE, page);
  page->IncrementAgeInNewSpace();
}
References AddPageImpl(), v8::internal::MutablePageMetadata::AgeInNewSpace(), DCHECK_EQ, DCHECK_LE, heap_, v8::internal::MutablePageMetadata::IncrementAgeInNewSpace(), v8::internal::Heap::IncrementNewSpaceSurvivingObjectSize(), v8::internal::Heap::IncrementYoungSurvivorsCounter(), v8::internal::MutablePageMetadata::live_bytes(), v8::internal::NEW_SPACE, v8::internal::MutablePageMetadata::owner_identity(), and v8::internal::v8_flags.
Referenced by v8::internal::MinorMarkSweepCollector::StartSweepNewSpace().
AddPage()
void v8::internal::Sweeper::AddPage (AllocationSpace space, PageMetadata * page)
Definition at line 1385 of file sweeper.cc.
                                                               {
  DCHECK_NE(NEW_SPACE, space);
  AddPageImpl(space, page);
}
References AddPageImpl(), DCHECK_NE, v8::internal::NEW_SPACE, and space.
Referenced by v8::internal::MinorMarkSweepCollector::StartSweepNewSpaceWithStickyBits(), and v8::internal::MarkCompactCollector::StartSweepSpace().
AddPageImpl()
void v8::internal::Sweeper::AddPageImpl (AllocationSpace space, PageMetadata * page) [private]
Definition at line 1400 of file sweeper.cc.
                                                                   {
  DCHECK(heap_->IsMainThread());
  DCHECK(page->SweepingDone());
  DCHECK(!page->Chunk()->IsFlagSet(MemoryChunk::BLACK_ALLOCATED));
  DCHECK(IsValidSweepingSpace(space));
  DCHECK_IMPLIES(v8_flags.concurrent_sweeping && (space != NEW_SPACE),
                 !major_sweeping_state_.HasValidJob());
  DCHECK_IMPLIES(v8_flags.concurrent_sweeping,
                 !minor_sweeping_state_.HasValidJob());
  PrepareToBeSweptPage(space, page);
  DCHECK_EQ(PageMetadata::ConcurrentSweepingState::kPendingSweeping,
            page->concurrent_sweeping_state());
  sweeping_list_[GetSweepSpaceIndex(space)].push_back(page);
  has_sweeping_work_[GetSweepSpaceIndex(space)].store(
      true, std::memory_order_release);
}
References v8::internal::MemoryChunk::BLACK_ALLOCATED, v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MutablePageMetadata::concurrent_sweeping_state(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, GetSweepSpaceIndex(), has_sweeping_work_, v8::internal::Sweeper::SweepingState< scope >::HasValidJob(), heap_, v8::internal::MemoryChunk::IsFlagSet(), v8::internal::Heap::IsMainThread(), IsValidSweepingSpace(), v8::internal::MutablePageMetadata::kPendingSweeping, major_sweeping_state_, minor_sweeping_state_, v8::internal::NEW_SPACE, PrepareToBeSweptPage(), space, sweeping_list_, v8::internal::MutablePageMetadata::SweepingDone(), and v8::internal::v8_flags.
Referenced by AddNewSpacePage(), and AddPage().
AddPromotedPage()
void v8::internal::Sweeper::AddPromotedPage (MutablePageMetadata * chunk)
Definition at line 1417 of file sweeper.cc.
                                                        {
  DCHECK(heap_->IsMainThread());
  DCHECK(chunk->owner_identity() == OLD_SPACE ||
         chunk->owner_identity() == LO_SPACE);
  DCHECK_IMPLIES(v8_flags.concurrent_sweeping,
                 !minor_sweeping_state_.HasValidJob());
  size_t live_bytes = chunk->live_bytes();
  DCHECK_GE(chunk->area_size(), live_bytes);
  heap_->IncrementPromotedObjectsSize(live_bytes);
  heap_->IncrementYoungSurvivorsCounter(live_bytes);
  DCHECK_EQ(PageMetadata::ConcurrentSweepingState::kDone,
            chunk->concurrent_sweeping_state());
  if (!chunk->Chunk()->IsLargePage()) {
    PrepareToBeIteratedPromotedPage(static_cast<PageMetadata*>(chunk));
  } else {
    chunk->set_concurrent_sweeping_state(
        PageMetadata::ConcurrentSweepingState::kPendingIteration);
  }
  DCHECK_EQ(PageMetadata::ConcurrentSweepingState::kPendingIteration,
            chunk->concurrent_sweeping_state());
  // This method is called only from the main thread while sweeping tasks have
  // not yet started, thus a mutex is not needed.
  sweeping_list_for_promoted_page_iteration_.push_back(chunk);
  promoted_pages_for_iteration_count_++;
}
References v8::internal::MemoryChunkMetadata::area_size(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MutablePageMetadata::concurrent_sweeping_state(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_IMPLIES, v8::internal::Sweeper::SweepingState< scope >::HasValidJob(), heap_, v8::internal::Heap::IncrementPromotedObjectsSize(), v8::internal::Heap::IncrementYoungSurvivorsCounter(), v8::internal::MemoryChunk::IsLargePage(), v8::internal::Heap::IsMainThread(), v8::internal::MutablePageMetadata::kDone, v8::internal::MutablePageMetadata::kPendingIteration, v8::internal::MutablePageMetadata::live_bytes(), v8::internal::LO_SPACE, minor_sweeping_state_, v8::internal::OLD_SPACE, v8::internal::MutablePageMetadata::owner_identity(), PrepareToBeIteratedPromotedPage(), promoted_pages_for_iteration_count_, v8::internal::MutablePageMetadata::set_concurrent_sweeping_state(), sweeping_list_for_promoted_page_iteration_, and v8::internal::v8_flags.
Referenced by v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), and v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace().
AddSweptPage()
void v8::internal::Sweeper::AddSweptPage (PageMetadata * page, AllocationSpace identity) [private]
Definition at line 1534 of file sweeper.cc.
                                                                       {
  base::MutexGuard guard(&mutex_);
  page->set_concurrent_sweeping_state(
      PageMetadata::ConcurrentSweepingState::kDone);
  swept_list_[GetSweepSpaceIndex(identity)].push_back(page);
  has_swept_pages_[GetSweepSpaceIndex(identity)].store(
      true, std::memory_order_release);
  cv_page_swept_.NotifyAll();
}
References cv_page_swept_, GetSweepSpaceIndex(), has_swept_pages_, v8::internal::MutablePageMetadata::kDone, mutex_, v8::base::ConditionVariable::NotifyAll(), v8::internal::MutablePageMetadata::set_concurrent_sweeping_state(), and swept_list_.
AreMajorSweeperTasksRunning()
bool v8::internal::Sweeper::AreMajorSweeperTasksRunning () const
Definition at line 977 of file sweeper.cc.
                                                {
  return major_sweeping_state_.HasActiveJob();
}
References v8::internal::Sweeper::SweepingState< scope >::HasActiveJob(), and major_sweeping_state_.
AreMinorSweeperTasksRunning()
bool v8::internal::Sweeper::AreMinorSweeperTasksRunning () const
Definition at line 973 of file sweeper.cc.
                                                {
  return minor_sweeping_state_.HasActiveJob();
}
References v8::internal::Sweeper::SweepingState< scope >::HasActiveJob(), and minor_sweeping_state_.
Referenced by v8::internal::PagedNewSpaceAllocatorPolicy::WaitForSweepingForAllocation().
CleanupRememberedSetEntriesForFreedMemory()
void v8::internal::Sweeper::CleanupRememberedSetEntriesForFreedMemory (Address free_start, Address free_end, PageMetadata * page, bool record_free_ranges, TypedSlotSet::FreeRangesMap * free_ranges_map, SweepingMode sweeping_mode) [inline], [private]
Definition at line 1080 of file sweeper.cc.
                                {
  DCHECK_LE(free_start, free_end);
  if (sweeping_mode == SweepingMode::kEagerDuringGC) {
    // New space and in consequence the old-to-new remembered set is always
    // empty after a full GC, so we do not need to remove from it after the full
    // GC. However, we wouldn't even be allowed to do that, since the main
    // thread then owns the old-to-new remembered set. Removing from it from a
    // sweeper thread would race with the main thread.
    RememberedSet<OLD_TO_NEW>::RemoveRange(page, free_start, free_end,
                                           SlotSet::KEEP_EMPTY_BUCKETS);
    RememberedSet<OLD_TO_NEW_BACKGROUND>::RemoveRange(
        page, free_start, free_end, SlotSet::KEEP_EMPTY_BUCKETS);
    // While we only add old-to-old slots on live objects, we can still end up
    // with old-to-old slots in free memory with e.g. right-trimming of objects.
    RememberedSet<OLD_TO_OLD>::RemoveRange(page, free_start, free_end,
                                           SlotSet::KEEP_EMPTY_BUCKETS);
    RememberedSet<TRUSTED_TO_TRUSTED>::RemoveRange(page, free_start, free_end,
                                                   SlotSet::KEEP_EMPTY_BUCKETS);
  } else {
    DCHECK_NULL(page->slot_set<OLD_TO_OLD>());
    DCHECK_NULL(page->slot_set<TRUSTED_TO_TRUSTED>());
  }
  // Old-to-shared isn't reset after a full GC, so needs to be cleaned both
  // during and after a full GC.
  RememberedSet<OLD_TO_SHARED>::RemoveRange(page, free_start, free_end,
                                            SlotSet::KEEP_EMPTY_BUCKETS);
  RememberedSet<TRUSTED_TO_SHARED_TRUSTED>::RemoveRange(
      page, free_start, free_end, SlotSet::KEEP_EMPTY_BUCKETS);
  if (record_free_ranges) {
    MemoryChunk* chunk = page->Chunk();
    free_ranges_map->insert(std::pair<uint32_t, uint32_t>(
        static_cast<uint32_t>(chunk->Offset(free_start)),
        static_cast<uint32_t>(chunk->Offset(free_end))));
  }
}
References v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_LE, DCHECK_NULL, kEagerDuringGC, heap::base::BasicSlotSet< kTaggedSize >::KEEP_EMPTY_BUCKETS, v8::internal::MemoryChunk::Offset(), v8::internal::OLD_TO_OLD, v8::internal::RememberedSet< type >::RemoveRange(), v8::internal::MutablePageMetadata::slot_set(), and v8::internal::TRUSTED_TO_TRUSTED.
Referenced by RawSweep().
CleanupTypedSlotsInFreeMemory()
void v8::internal::Sweeper::CleanupTypedSlotsInFreeMemory (PageMetadata * page, const TypedSlotSet::FreeRangesMap & free_ranges_map, SweepingMode sweeping_mode) [private]
Definition at line 1122 of file sweeper.cc.
                                {
  // No support for typed trusted-to-shared-trusted pointers.
  DCHECK_NULL(page->typed_slot_set<TRUSTED_TO_SHARED_TRUSTED>());
  if (sweeping_mode == SweepingMode::kEagerDuringGC) {
    page->ClearTypedSlotsInFreeMemory<OLD_TO_NEW>(free_ranges_map);
    // Typed old-to-old slot sets are only ever recorded in live code objects.
    // Also code objects are never right-trimmed, so there cannot be any slots
    // in a free range.
    page->AssertNoTypedSlotsInFreeMemory<OLD_TO_OLD>(free_ranges_map);
    page->ClearTypedSlotsInFreeMemory<OLD_TO_SHARED>(free_ranges_map);
    return;
  }
  DCHECK_EQ(sweeping_mode, SweepingMode::kLazyOrConcurrent);
  // After a full GC there are no old-to-new typed slots. The main thread
  // could create new slots but not in a free range.
  page->AssertNoTypedSlotsInFreeMemory<OLD_TO_NEW>(free_ranges_map);
  DCHECK_NULL(page->typed_slot_set<OLD_TO_OLD>());
  page->ClearTypedSlotsInFreeMemory<OLD_TO_SHARED>(free_ranges_map);
}
References v8::internal::PageMetadata::AssertNoTypedSlotsInFreeMemory(), v8::internal::PageMetadata::ClearTypedSlotsInFreeMemory(), DCHECK_EQ, DCHECK_NULL, kEagerDuringGC, kLazyOrConcurrent, v8::internal::OLD_TO_NEW, v8::internal::OLD_TO_OLD, v8::internal::OLD_TO_SHARED, v8::internal::TRUSTED_TO_SHARED_TRUSTED, and v8::internal::MutablePageMetadata::typed_slot_set().
Referenced by RawSweep().
ClearMarkBitsAndHandleLivenessStatistics()
void v8::internal::Sweeper::ClearMarkBitsAndHandleLivenessStatistics (PageMetadata * page, size_t live_bytes) [private]
Definition at line 1148 of file sweeper.cc.
                                                                          {
  if (!v8_flags.sticky_mark_bits) {
    page->marking_bitmap()->Clear<AccessMode::NON_ATOMIC>();
  }
  // Keep the old live bytes counter of the page until RefillFreeList, where
  // the space size is refined.
  // The allocated_bytes() counter is precisely the total size of objects.
  DCHECK_EQ(live_bytes, page->allocated_bytes());
}
References v8::internal::MemoryChunkMetadata::allocated_bytes(), v8::internal::MarkingBitmap::Clear(), DCHECK_EQ, v8::internal::MutablePageMetadata::marking_bitmap(), v8::internal::NON_ATOMIC, and v8::internal::v8_flags.
Referenced by RawSweep().
ComputeDiscardMemoryArea()
std::optional< base::AddressRegion > v8::internal::Sweeper::ComputeDiscardMemoryArea (Address start, Address end) [static]
Definition at line 1014 of file sweeper.cc.
                                {
  const size_t page_size = MemoryAllocator::GetCommitPageSize();
  const Address discard_start = RoundUp(start, page_size);
  const Address discard_end = RoundDown(end, page_size);
  if (discard_start < discard_end) {
    return base::AddressRegion(discard_start, discard_end - discard_start);
  } else {
    return {};
  }
}
References v8::internal::compiler::end(), v8::internal::MemoryAllocator::GetCommitPageSize(), RoundDown(), and RoundUp().
Referenced by ZeroOrDiscardUnusedMemory().
ConcurrentMajorSweepingPageCount()
size_t v8::internal::Sweeper::ConcurrentMajorSweepingPageCount () [private]
Definition at line 1286 of file sweeper.cc.
                                                 {
  DCHECK(major_sweeping_in_progress());
  base::MutexGuard guard(&mutex_);
  size_t count = 0;
  for (int i = 0; i < kNumberOfSweepingSpaces; i++) {
    if (i == GetSweepSpaceIndex(NEW_SPACE)) continue;
    count += sweeping_list_[i].size();
  }
  return count;
}
References v8::internal::DCHECK(), GetSweepSpaceIndex(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kNumberOfSweepingSpaces, major_sweeping_in_progress(), mutex_, v8::internal::NEW_SPACE, and sweeping_list_.
Referenced by v8::internal::Sweeper::MajorSweeperJob::GetMaxConcurrency().
ConcurrentMinorSweepingPageCount()
size_t v8::internal::Sweeper::ConcurrentMinorSweepingPageCount () [private]
Definition at line 1279 of file sweeper.cc.
                                                 {
  DCHECK(minor_sweeping_in_progress());
  base::MutexGuard guard(&mutex_);
  return sweeping_list_for_promoted_page_iteration_.size() +
         sweeping_list_[GetSweepSpaceIndex(NEW_SPACE)].size();
}
References v8::internal::DCHECK(), GetSweepSpaceIndex(), minor_sweeping_in_progress(), mutex_, v8::internal::NEW_SPACE, sweeping_list_, and sweeping_list_for_promoted_page_iteration_.
Referenced by v8::internal::Sweeper::MinorSweeperJob::GetMaxConcurrency().
ContributeAndWaitForPromotedPagesIteration()
void v8::internal::Sweeper::ContributeAndWaitForPromotedPagesIteration ()
Definition at line 1257 of file sweeper.cc.
                                                         {
  main_thread_local_sweeper_.ContributeAndWaitForPromotedPagesIteration();
}
References v8::internal::Sweeper::LocalSweeper::ContributeAndWaitForPromotedPagesIteration(), and main_thread_local_sweeper_.
Referenced by v8::internal::Heap::PauseConcurrentThreadsInClients().
EnsureMajorCompleted()
void v8::internal::Sweeper::EnsureMajorCompleted ()
Definition at line 891 of file sweeper.cc.
                                   {
  DCHECK(heap_->IsMainThread());
  // If sweeping is not completed or not running at all, we try to complete it
  // here.
  if (minor_sweeping_in_progress()) {
    TRACE_GC_EPOCH_WITH_FLOW(
        heap_->tracer(), GCTracer::Scope::MINOR_MS_COMPLETE_SWEEPING,
        ThreadKind::kMain,
        GetTraceIdForFlowEvent(GCTracer::Scope::MINOR_MS_COMPLETE_SWEEPING),
        TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
    // TODO(40096225): When finalizing sweeping for a starting a new major GC,
    // OLD_TO_NEW is no longer needed. If this is the main isolate, we could
    // cancel promoted page iteration instead of finishing it.
    EnsureMinorCompleted();
  }
  if (major_sweeping_in_progress()) {
    TRACE_GC_EPOCH_WITH_FLOW(
        heap_->tracer(), GCTracer::Scope::MC_COMPLETE_SWEEPING,
        ThreadKind::kMain,
        GetTraceIdForFlowEvent(GCTracer::Scope::MC_COMPLETE_SWEEPING),
        TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
    // Discard all pooled pages on memory-reducing GCs.
    if (major_sweeping_state_.should_reduce_memory()) {
      heap_->memory_allocator()->ReleasePooledChunksImmediately();
    }
    FinishMajorJobs();
    major_sweeping_state_.FinishSweeping();
    // Sweeping should not add pages to the pool.
    DCHECK_IMPLIES(major_sweeping_state_.should_reduce_memory(),
                   heap_->memory_allocator()->GetPooledChunksCount() == 0);
  }
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, EnsureMinorCompleted(), FinishMajorJobs(), v8::internal::Sweeper::SweepingState< scope >::FinishSweeping(), v8::internal::MemoryAllocator::GetPooledChunksCount(), GetTraceIdForFlowEvent(), heap_, v8::internal::Heap::IsMainThread(), v8::internal::kMain, major_sweeping_in_progress(), major_sweeping_state_, v8::internal::Heap::memory_allocator(), minor_sweeping_in_progress(), v8::internal::MemoryAllocator::ReleasePooledChunksImmediately(), v8::internal::Sweeper::SweepingState< scope >::should_reduce_memory(), TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_EPOCH_WITH_FLOW, and v8::internal::Heap::tracer().
Referenced by v8::internal::Heap::EnsureSweepingCompleted().
EnsureMinorCompleted()
void v8::internal::Sweeper::EnsureMinorCompleted ()
Definition at line 962 of file sweeper.cc.
                                   {
  if (!minor_sweeping_in_progress()) return;
  DCHECK(!minor_sweeping_state_.should_reduce_memory());
  FinishMinorJobs();
  minor_sweeping_state_.FinishSweeping();
  promoted_pages_for_iteration_count_ = 0;
  iterated_promoted_pages_count_ = 0;
}
References v8::internal::DCHECK(), FinishMinorJobs(), v8::internal::Sweeper::SweepingState< scope >::FinishSweeping(), iterated_promoted_pages_count_, minor_sweeping_in_progress(), minor_sweeping_state_, promoted_pages_for_iteration_count_, and v8::internal::Sweeper::SweepingState< scope >::should_reduce_memory().
Referenced by EnsureMajorCompleted(), and v8::internal::Heap::EnsureYoungSweepingCompleted().
EnsurePageIsSwept()
void v8::internal::Sweeper::EnsurePageIsSwept (PageMetadata * page)
Definition at line 1305 of file sweeper.cc.
                                                  {
  DCHECK(heap_->IsMainThread());
  auto concurrent_sweeping_state = page->concurrent_sweeping_state();
  DCHECK_IMPLIES(!sweeping_in_progress(),
                 concurrent_sweeping_state ==
                     PageMetadata::ConcurrentSweepingState::kDone);
  if (concurrent_sweeping_state ==
      PageMetadata::ConcurrentSweepingState::kDone) {
    DCHECK(page->SweepingDone());
    return;
  }
  AllocationSpace space = page->owner_identity();
  DCHECK(IsValidSweepingSpace(space));
  auto scope_id = GetTracingScope(space, true);
  TRACE_GC_EPOCH_WITH_FLOW(
      heap_->tracer(), scope_id, ThreadKind::kMain,
      GetTraceIdForFlowEvent(scope_id),
      TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
  if ((concurrent_sweeping_state ==
       PageMetadata::ConcurrentSweepingState::kPendingSweeping) &&
      TryRemoveSweepingPageSafe(space, page)) {
    // Page was successfully removed and can now be swept.
    main_thread_local_sweeper_.ParallelSweepPage(
        page, space, SweepingMode::kLazyOrConcurrent);
  } else if ((concurrent_sweeping_state ==
              PageMetadata::ConcurrentSweepingState::kPendingIteration) &&
             TryRemovePromotedPageSafe(page)) {
    // Page was successfully removed and can now be iterated.
    main_thread_local_sweeper_.ParallelIteratePromotedPage(page);
  } else {
    // Some sweeper task already took ownership of that page, wait until
    // sweeping is finished.
    WaitForPageToBeSwept(page);
  }
  CHECK(page->SweepingDone());
}
References CHECK, v8::internal::MutablePageMetadata::concurrent_sweeping_state(), v8::internal::DCHECK(), DCHECK_IMPLIES, GetTraceIdForFlowEvent(), GetTracingScope(), heap_, v8::internal::Heap::IsMainThread(), IsValidSweepingSpace(), v8::internal::MutablePageMetadata::kDone, kLazyOrConcurrent, v8::internal::kMain, v8::internal::MutablePageMetadata::kPendingIteration, v8::internal::MutablePageMetadata::kPendingSweeping, main_thread_local_sweeper_, v8::internal::MutablePageMetadata::owner_identity(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::Sweeper::LocalSweeper::ParallelSweepPage(), space, sweeping_in_progress(), v8::internal::MutablePageMetadata::SweepingDone(), TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_EPOCH_WITH_FLOW, v8::internal::Heap::tracer(), TryRemovePromotedPageSafe(), TryRemoveSweepingPageSafe(), and WaitForPageToBeSwept().
Referenced by v8::internal::Heap::EnsureSweepingCompletedForObject().
FinishMajorJobs()
void v8::internal::Sweeper::FinishMajorJobs ()
Definition at line 857 of file sweeper.cc.
                              {
  if (!major_sweeping_in_progress()) return;
  {
    const bool is_main_thread = heap_->IsMainThread();
    DCHECK_IMPLIES(
        !is_main_thread,
        heap_->isolate()->shared_space_isolate()->heap()->IsMainThread());
    TRACE_GC_EPOCH_WITH_FLOW(
        heap_->tracer(),
        is_main_thread ? GCTracer::Scope::MC_SWEEP
                       : GCTracer::Scope::MC_BACKGROUND_SWEEPING,
        is_main_thread ? ThreadKind::kMain : ThreadKind::kBackground,
        major_sweeping_state_.trace_id(),
        TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
    ForAllSweepingSpaces([this](AllocationSpace space) {
      if (space == NEW_SPACE) return;
      main_thread_local_sweeper_.ParallelSweepSpace(
          space, SweepingMode::kLazyOrConcurrent);
    });
  }
  // Join all concurrent tasks.
  major_sweeping_state_.JoinSweeping();
  // All jobs are done but we still remain in sweeping state here.
  DCHECK(major_sweeping_in_progress());
  ForAllSweepingSpaces([this](AllocationSpace space) {
    if (space == NEW_SPACE) return;
    CHECK(sweeping_list_[GetSweepSpaceIndex(space)].empty());
    DCHECK(IsSweepingDoneForSpace(space));
  });
}
References CHECK, v8::internal::DCHECK(), DCHECK_IMPLIES, ForAllSweepingSpaces(), GetSweepSpaceIndex(), v8::internal::Isolate::heap(), heap_, v8::internal::Heap::IsMainThread(), v8::internal::Heap::isolate(), IsSweepingDoneForSpace(), v8::internal::Sweeper::SweepingState< scope >::JoinSweeping(), v8::internal::kBackground, kLazyOrConcurrent, v8::internal::kMain, main_thread_local_sweeper_, major_sweeping_in_progress(), major_sweeping_state_, v8::internal::NEW_SPACE, v8::internal::Sweeper::LocalSweeper::ParallelSweepSpace(), v8::internal::Isolate::shared_space_isolate(), space, sweeping_list_, TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_EPOCH_WITH_FLOW, v8::internal::Sweeper::SweepingState< scope >::trace_id(), and v8::internal::Heap::tracer().
Referenced by EnsureMajorCompleted(), and v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap().
FinishMinorJobs()
void v8::internal::Sweeper::FinishMinorJobs ()
Definition at line 927 of file sweeper.cc.
                              {
  if (!minor_sweeping_in_progress()) return;
  {
    const bool is_main_thread = heap_->IsMainThread();
    DCHECK_IMPLIES(
        !is_main_thread,
        heap_->isolate()->shared_space_isolate()->heap()->IsMainThread());
    TRACE_GC_EPOCH_WITH_FLOW(
        heap_->tracer(),
        is_main_thread ? GCTracer::Scope::MINOR_MS_SWEEP
                       : GCTracer::Scope::MINOR_MS_BACKGROUND_SWEEPING,
        is_main_thread ? ThreadKind::kMain : ThreadKind::kBackground,
        minor_sweeping_state_.trace_id(),
        TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
    main_thread_local_sweeper_.ParallelSweepSpace(
        kNewSpace, SweepingMode::kLazyOrConcurrent);
    // Array buffer sweeper may have grabbed a page for iteration to contribute.
    // Wait until it has finished iterating.
    main_thread_local_sweeper_.ContributeAndWaitForPromotedPagesIteration();
  }
  // Join all concurrent tasks.
  minor_sweeping_state_.JoinSweeping();
  // All jobs are done but we still remain in sweeping state here.
  DCHECK(minor_sweeping_in_progress());
  CHECK(sweeping_list_[GetSweepSpaceIndex(kNewSpace)].empty());
  DCHECK(IsSweepingDoneForSpace(kNewSpace));
  DCHECK_EQ(promoted_pages_for_iteration_count_,
            iterated_promoted_pages_count_);
  CHECK(sweeping_list_for_promoted_page_iteration_.empty());
}
References CHECK, v8::internal::Sweeper::LocalSweeper::ContributeAndWaitForPromotedPagesIteration(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, GetSweepSpaceIndex(), v8::internal::Isolate::heap(), heap_, v8::internal::Heap::IsMainThread(), v8::internal::Heap::isolate(), IsSweepingDoneForSpace(), iterated_promoted_pages_count_, v8::internal::Sweeper::SweepingState< scope >::JoinSweeping(), v8::internal::kBackground, kLazyOrConcurrent, v8::internal::kMain, v8::internal::kNewSpace, main_thread_local_sweeper_, minor_sweeping_in_progress(), minor_sweeping_state_, v8::internal::Sweeper::LocalSweeper::ParallelSweepSpace(), promoted_pages_for_iteration_count_, v8::internal::Isolate::shared_space_isolate(), sweeping_list_, sweeping_list_for_promoted_page_iteration_, TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_EPOCH_WITH_FLOW, v8::internal::Sweeper::SweepingState< scope >::trace_id(), and v8::internal::Heap::tracer().
Referenced by EnsureMinorCompleted(), and v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap().
ForAllSweepingSpaces()
template<typename Callback >
void v8::internal::Sweeper::ForAllSweepingSpaces (Callback callback) const [inline], [private]
Definition at line 210 of file sweeper.h.
                                                     {
    if (v8_flags.minor_ms) {
      callback(NEW_SPACE);
    }
    callback(OLD_SPACE);
    callback(CODE_SPACE);
    callback(SHARED_SPACE);
    callback(TRUSTED_SPACE);
    callback(SHARED_TRUSTED_SPACE);
  }
References v8::internal::CODE_SPACE, v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, v8::internal::SHARED_SPACE, v8::internal::SHARED_TRUSTED_SPACE, v8::internal::TRUSTED_SPACE, and v8::internal::v8_flags.
Referenced by FinishMajorJobs(), and StartMajorSweeping().
FreeAndProcessFreedMemory()
size_t v8::internal::Sweeper::FreeAndProcessFreedMemory (Address free_start, Address free_end, PageMetadata * page, Space * space, FreeSpaceTreatmentMode free_space_treatment_mode, bool should_reduce_memory) [inline], [private]
Definition at line 985 of file sweeper.cc.
                               {
  CHECK_GT(free_end, free_start);
  size_t freed_bytes = 0;
  size_t size = static_cast<size_t>(free_end - free_start);
  if (free_space_treatment_mode == FreeSpaceTreatmentMode::kZapFreeSpace) {
    CodePageMemoryModificationScopeForDebugging memory_modification_scope(page);
    AtomicZapBlock(free_start, size);
  }
  freed_bytes = reinterpret_cast<PagedSpaceBase*>(space)->FreeDuringSweep(
      free_start, size);
  if (should_reduce_memory) {
    ZeroOrDiscardUnusedMemory(page, free_start, size);
  }
  if (v8_flags.sticky_mark_bits) {
    // Clear the bitmap, since fillers or slack may still be marked from black
    // allocation.
    page->marking_bitmap()->ClearRange<AccessMode::NON_ATOMIC>(
        MarkingBitmap::AddressToIndex(free_start),
        MarkingBitmap::AddressToIndex(free_end));
  }
  return freed_bytes;
}
References v8::internal::MarkingBitmap::AddressToIndex(), v8::internal::anonymous_namespace{sweeper.cc}::AtomicZapBlock(), CHECK_GT, v8::internal::MarkingBitmap::ClearRange(), v8::internal::kZapFreeSpace, v8::internal::MutablePageMetadata::marking_bitmap(), v8::internal::NON_ATOMIC, size(), space, v8::internal::v8_flags, and ZeroOrDiscardUnusedMemory().
Referenced by RawSweep().
GetAllSweptPagesSafe()
Sweeper::SweptList v8::internal::Sweeper::GetAllSweptPagesSafe (PagedSpaceBase * space)
Definition at line 848 of file sweeper.cc.
                                                                    {
  base::MutexGuard guard(&mutex_);
  SweptList list;
  list.swap(swept_list_[GetSweepSpaceIndex(space->identity())]);
  has_swept_pages_[GetSweepSpaceIndex(space->identity())].store(
      false, std::memory_order_release);
  return list;
}
References GetSweepSpaceIndex(), has_swept_pages_, mutex_, space, and swept_list_.
GetPromotedPageSafe()
MutablePageMetadata * v8::internal::Sweeper::GetPromotedPageSafe () [private]
Definition at line 1509 of file sweeper.cc.
                                                  {
  base::MutexGuard guard(&mutex_);
  MutablePageMetadata* chunk = nullptr;
  if (!sweeping_list_for_promoted_page_iteration_.empty()) {
    chunk = sweeping_list_for_promoted_page_iteration_.back();
    sweeping_list_for_promoted_page_iteration_.pop_back();
  }
  return chunk;
}
References mutex_, and sweeping_list_for_promoted_page_iteration_.
GetSweepingPageSafe()
PageMetadata * v8::internal::Sweeper::GetSweepingPageSafe (AllocationSpace space) [private]
Definition at line 1492 of file sweeper.cc.
                                                                {
  base::MutexGuard guard(&mutex_);
  DCHECK(IsValidSweepingSpace(space));
  int space_index = GetSweepSpaceIndex(space);
  PageMetadata* page = nullptr;
  SweepingList& sweeping_list = sweeping_list_[space_index];
  if (!sweeping_list.empty()) {
    page = sweeping_list.back();
    sweeping_list.pop_back();
  }
  if (sweeping_list.empty()) {
    has_sweeping_work_[GetSweepSpaceIndex(space)].store(
        false, std::memory_order_release);
  }
  return page;
}
References v8::internal::DCHECK(), GetSweepSpaceIndex(), has_sweeping_work_, IsValidSweepingSpace(), mutex_, space, and sweeping_list_.
Referenced by v8::internal::Sweeper::ConcurrentMajorSweeper::ConcurrentSweepSpace(), and v8::internal::Sweeper::ConcurrentMinorSweeper::ConcurrentSweepSpace().
GetSweepSpaceIndex()
static int v8::internal::Sweeper::GetSweepSpaceIndex (AllocationSpace space) [inline], [static], [private]
Definition at line 263 of file sweeper.h.
                                                       {
    DCHECK(IsValidSweepingSpace(space));
    return space - FIRST_SWEEPABLE_SPACE;
  }
References v8::internal::DCHECK(), v8::internal::FIRST_SWEEPABLE_SPACE, IsValidSweepingSpace(), and space.
Referenced by AddPageImpl(), AddSweptPage(), ConcurrentMajorSweepingPageCount(), ConcurrentMinorSweepingPageCount(), FinishMajorJobs(), FinishMinorJobs(), GetAllSweptPagesSafe(), GetSweepingPageSafe(), GetSweptPageSafe(), IsSweepingDoneForSpace(), v8::internal::Sweeper::LocalSweeper::ParallelSweepSpace(), ShouldRefillFreelistForSpace(), StartMajorSweeping(), StartMinorSweeping(), and TryRemoveSweepingPageSafe().
GetSweptPageSafe()
PageMetadata * v8::internal::Sweeper::GetSweptPageSafe (PagedSpaceBase * space)
Definition at line 833 of file sweeper.cc.
                                                             {
  base::MutexGuard guard(&mutex_);
  SweptList& list = swept_list_[GetSweepSpaceIndex(space->identity())];
  PageMetadata* page = nullptr;
  if (!list.empty()) {
    page = list.back();
    list.pop_back();
  }
  if (list.empty()) {
    has_swept_pages_[GetSweepSpaceIndex(space->identity())].store(
        false, std::memory_order_release);
  }
  return page;
}
References GetSweepSpaceIndex(), has_swept_pages_, mutex_, space, and swept_list_.
Referenced by v8::internal::CompactionSpace::RefillFreeList().
GetTraceIdForFlowEvent()
uint64_t v8::internal::Sweeper::GetTraceIdForFlowEvent (GCTracer::Scope::ScopeId scope_id) const
Definition at line 1615 of file sweeper.cc.
                                         {
  return GCTracer::Scope::NeedsYoungEpoch(scope_id)
             ? minor_sweeping_state_.trace_id()
             : major_sweeping_state_.trace_id();
}
References major_sweeping_state_, minor_sweeping_state_, v8::internal::GCTracer::Scope::NeedsYoungEpoch(), and v8::internal::Sweeper::SweepingState< scope >::trace_id().
Referenced by EnsureMajorCompleted(), EnsurePageIsSwept(), v8::internal::MarkCompactCollector::Finish(), v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::Run(), and v8::internal::MinorMarkSweepCollector::Sweep().
GetTracingScope()
GCTracer::Scope::ScopeId v8::internal::Sweeper::GetTracingScope (AllocationSpace space, bool is_joining_thread)
Definition at line 1519 of file sweeper.cc.
                                                                          {
  if (space == NEW_SPACE) {
    return is_joining_thread ? GCTracer::Scope::MINOR_MS_SWEEP
                             : GCTracer::Scope::MINOR_MS_BACKGROUND_SWEEPING;
  }
  return is_joining_thread ? GCTracer::Scope::MC_SWEEP
                           : GCTracer::Scope::MC_BACKGROUND_SWEEPING;
}
References v8::internal::NEW_SPACE, and space.
Referenced by v8::internal::PagedSpaceAllocatorPolicy::ContributeToSweeping(), EnsurePageIsSwept(), v8::internal::Sweeper::MajorSweeperJob::RunImpl(), and v8::internal::Sweeper::MinorSweeperJob::RunImpl().
InitializeMajorSweeping()
void v8::internal::Sweeper::InitializeMajorSweeping ()
Definition at line 696 of file sweeper.cc.
                                      {
  major_sweeping_state_.InitializeSweeping();
}
References v8::internal::Sweeper::SweepingState< scope >::InitializeSweeping(), and major_sweeping_state_.
InitializeMinorSweeping()
void v8::internal::Sweeper::InitializeMinorSweeping ()
Definition at line 700 of file sweeper.cc.
                                      {
  minor_sweeping_state_.InitializeSweeping();
}
References v8::internal::Sweeper::SweepingState< scope >::InitializeSweeping(), and minor_sweeping_state_.
Referenced by v8::internal::MinorMarkSweepCollector::Sweep().
IsIteratingPromotedPages()
bool v8::internal::Sweeper::IsIteratingPromotedPages () const
Definition at line 1253 of file sweeper.cc.
                                             {
  return promoted_page_iteration_in_progress_.load(std::memory_order_acquire);
}
References promoted_page_iteration_in_progress_.
Referenced by v8::internal::Sweeper::LocalSweeper::ContributeAndWaitForPromotedPagesIterationImpl(), and v8::internal::ArrayBufferSweeper::SweepingState::SweepingJob::Run().
IsSweepingDoneForSpace()
bool v8::internal::Sweeper::IsSweepingDoneForSpace (AllocationSpace space) const
Definition at line 1529 of file sweeper.cc.
                                                                {
  return !has_sweeping_work_[GetSweepSpaceIndex(space)].load(
      std::memory_order_acquire);
}
References GetSweepSpaceIndex(), has_sweeping_work_, and space.
Referenced by FinishMajorJobs(), and FinishMinorJobs().
IsValidSweepingSpace()
static bool v8::internal::Sweeper::IsValidSweepingSpace (AllocationSpace space) [inline], [static], [private]
Definition at line 259 of file sweeper.h.
                                                          {
    return space >= FIRST_SWEEPABLE_SPACE && space <= LAST_SWEEPABLE_SPACE;
  }
References v8::internal::FIRST_SWEEPABLE_SPACE, v8::internal::LAST_SWEEPABLE_SPACE, and space.
Referenced by AddPageImpl(), v8::internal::Sweeper::ConcurrentMajorSweeper::ConcurrentSweepSpace(), v8::internal::Sweeper::ConcurrentMinorSweeper::ConcurrentSweepSpace(), EnsurePageIsSwept(), GetSweepingPageSafe(), GetSweepSpaceIndex(), v8::internal::Sweeper::LocalSweeper::ParallelSweepPage(), and TryRemoveSweepingPageSafe().
major_sweeping_in_progress()
bool v8::internal::Sweeper::major_sweeping_in_progress () const [inline]
Definition at line 108 of file sweeper.h.
                                          {
    return major_sweeping_state_.in_progress();
  }
References v8::internal::Sweeper::SweepingState< scope >::in_progress(), and major_sweeping_state_.
Referenced by ConcurrentMajorSweepingPageCount(), EnsureMajorCompleted(), FinishMajorJobs(), v8::internal::Sweeper::MajorSweeperJob::RunImpl(), sweeping_in_progress(), and sweeping_in_progress_for_space().
marking_state()
NonAtomicMarkingState* v8::internal::Sweeper::marking_state () const [inline], [private]
Definition at line 190 of file sweeper.h.
{ return marking_state_; }
References marking_state_.
minor_sweeping_in_progress()
bool v8::internal::Sweeper::minor_sweeping_in_progress () const [inline]
Definition at line 111 of file sweeper.h.
                                          {
    return minor_sweeping_state_.in_progress();
  }
References v8::internal::Sweeper::SweepingState< scope >::in_progress(), and minor_sweeping_state_.
Referenced by ConcurrentMinorSweepingPageCount(), EnsureMajorCompleted(), EnsureMinorCompleted(), FinishMinorJobs(), v8::internal::Sweeper::MinorSweeperJob::RunImpl(), StartMajorSweeperTasks(), StartMajorSweeping(), sweeping_in_progress(), and sweeping_in_progress_for_space().
NotifyPromotedPageIterationFinished()
void v8::internal::Sweeper::NotifyPromotedPageIterationFinished (MutablePageMetadata * chunk) [private]
Definition at line 1261 of file sweeper.cc.
                                                                            {
  if (++iterated_promoted_pages_count_ == promoted_pages_for_iteration_count_) {
    NotifyPromotedPagesIterationFinished();
  }
  chunk->set_concurrent_sweeping_state(
      PageMetadata::ConcurrentSweepingState::kDone);
  base::MutexGuard guard(&mutex_);
  cv_page_swept_.NotifyAll();
}
References cv_page_swept_, iterated_promoted_pages_count_, v8::internal::MutablePageMetadata::kDone, mutex_, v8::base::ConditionVariable::NotifyAll(), NotifyPromotedPagesIterationFinished(), promoted_pages_for_iteration_count_, and v8::internal::MutablePageMetadata::set_concurrent_sweeping_state().
NotifyPromotedPagesIterationFinished()
void v8::internal::Sweeper::NotifyPromotedPagesIterationFinished () [private]
Definition at line 1271 of file sweeper.cc.
                                                   {
  DCHECK_EQ(iterated_promoted_pages_count_,
            promoted_pages_for_iteration_count_);
  base::MutexGuard guard(&promoted_pages_iteration_notification_mutex_);
  promoted_page_iteration_in_progress_.store(false, std::memory_order_release);
  promoted_pages_iteration_notification_variable_.NotifyAll();
}
References DCHECK_EQ, iterated_promoted_pages_count_, v8::base::ConditionVariable::NotifyAll(), promoted_page_iteration_in_progress_, promoted_pages_for_iteration_count_, promoted_pages_iteration_notification_mutex_, and promoted_pages_iteration_notification_variable_.
Referenced by NotifyPromotedPageIterationFinished().
ParallelSweepSpace()
bool v8::internal::Sweeper::ParallelSweepSpace (AllocationSpace identity, SweepingMode sweeping_mode, uint32_t max_pages = std::numeric_limits<uint32_t>::max())
Definition at line 1297 of file sweeper.cc.
                                                     {
  DCHECK_IMPLIES(identity == NEW_SPACE, heap_->IsMainThread());
  return main_thread_local_sweeper_.ParallelSweepSpace(identity, sweeping_mode,
                                                       max_pages);
}
References DCHECK_IMPLIES, heap_, v8::internal::Heap::IsMainThread(), main_thread_local_sweeper_, v8::internal::NEW_SPACE, and v8::internal::Sweeper::LocalSweeper::ParallelSweepSpace().
PrepareToBeIteratedPromotedPage()
void v8::internal::Sweeper::PrepareToBeIteratedPromotedPage (PageMetadata * page) [private]
Definition at line 1476 of file sweeper.cc.
                                                                {
  DCHECK(!page->Chunk()->IsFlagSet(MemoryChunk::BLACK_ALLOCATED));
  DCHECK_EQ(OLD_SPACE, page->owner_identity());
  VerifyPreparedPage(page);
  page->set_concurrent_sweeping_state(
      PageMetadata::ConcurrentSweepingState::kPendingIteration);
  // Account the whole page as allocated since it won't be in the free list.
  // TODO(v8:12612): Consider accounting for wasted bytes when checking old gen
  // size against old gen allocation limit, and treat previously unallocated
  // memory as wasted rather than allocated.
  page->ResetAllocationStatisticsForPromotedPage();
  PagedSpace* space = static_cast<PagedSpace*>(page->owner());
  space->IncreaseAllocatedBytes(page->allocated_bytes(), page);
  space->free_list()->increase_wasted_bytes(page->wasted_memory());
}
References v8::internal::MemoryChunkMetadata::allocated_bytes(), v8::internal::MemoryChunk::BLACK_ALLOCATED, v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MutablePageMetadata::kPendingIteration, v8::internal::OLD_SPACE, v8::internal::MutablePageMetadata::owner(), v8::internal::MutablePageMetadata::owner_identity(), v8::internal::MutablePageMetadata::ResetAllocationStatisticsForPromotedPage(), v8::internal::MutablePageMetadata::set_concurrent_sweeping_state(), space, v8::internal::anonymous_namespace{sweeper.cc}::VerifyPreparedPage(), and v8::internal::MemoryChunkMetadata::wasted_memory().
Referenced by AddPromotedPage().
PrepareToBeSweptPage()
void v8::internal::Sweeper::PrepareToBeSweptPage (AllocationSpace space, PageMetadata * page) [private]
Definition at line 1456 of file sweeper.cc.
                                                                            {
  VerifyPreparedPage(page);
  page->set_concurrent_sweeping_state(
      PageMetadata::ConcurrentSweepingState::kPendingSweeping);
  PagedSpaceBase* paged_space;
  if (space == NEW_SPACE) {
    DCHECK(v8_flags.minor_ms);
    paged_space = heap_->paged_new_space()->paged_space();
  } else {
    paged_space = heap_->paged_space(space);
  }
  paged_space->IncreaseAllocatedBytes(page->live_bytes(), page);
  // Set the allocated_bytes_ counter to area_size and clear the wasted_memory_
  // counter. The free operations during sweeping will decrease allocated_bytes_
  // to actual live bytes and keep track of wasted_memory_.
  page->ResetAllocationStatistics();
}
References v8::internal::DCHECK(), heap_, v8::internal::PagedSpaceBase::IncreaseAllocatedBytes(), v8::internal::MutablePageMetadata::kPendingSweeping, v8::internal::MutablePageMetadata::live_bytes(), v8::internal::NEW_SPACE, v8::internal::Heap::paged_new_space(), v8::internal::PagedNewSpace::paged_space(), v8::internal::Heap::paged_space(), v8::internal::MutablePageMetadata::ResetAllocationStatistics(), v8::internal::MutablePageMetadata::set_concurrent_sweeping_state(), space, v8::internal::v8_flags, and v8::internal::anonymous_namespace{sweeper.cc}::VerifyPreparedPage().
Referenced by AddPageImpl().
RawSweep()
void v8::internal::Sweeper::RawSweep (PageMetadata * p, FreeSpaceTreatmentMode free_space_treatment_mode, SweepingMode sweeping_mode, bool should_reduce_memory) [private]
Definition at line 1159 of file sweeper.cc.
                                                                              {
  DCHECK_NOT_NULL(p);
  Space* space = p->owner();
  DCHECK_NOT_NULL(space);
  DCHECK(space->identity() == OLD_SPACE || space->identity() == CODE_SPACE ||
         space->identity() == SHARED_SPACE ||
         space->identity() == TRUSTED_SPACE ||
         space->identity() == SHARED_TRUSTED_SPACE ||
         (space->identity() == NEW_SPACE && v8_flags.minor_ms));
  DCHECK(!p->Chunk()->IsEvacuationCandidate());
  DCHECK(!p->SweepingDone());
  DCHECK(!p->Chunk()->IsFlagSet(MemoryChunk::BLACK_ALLOCATED));
  DCHECK_IMPLIES(space->identity() == NEW_SPACE,
                 !heap_->incremental_marking()->IsMinorMarking());
  DCHECK_IMPLIES(space->identity() != NEW_SPACE,
                 !heap_->incremental_marking()->IsMajorMarking());
  // Phase 1: Prepare the page for sweeping.
  std::optional<ActiveSystemPages> active_system_pages_after_sweeping;
  if (should_reduce_memory) {
    // Only decrement counter when we discard unused system pages.
    active_system_pages_after_sweeping = ActiveSystemPages();
    active_system_pages_after_sweeping->Init(
        sizeof(MemoryChunk), MemoryAllocator::GetCommitPageSizeBits(),
        PageMetadata::kPageSize);
  }
  // Phase 2: Free the non-live memory and clean-up the regular remembered set
  // entires.
  // Liveness and freeing statistics.
  size_t live_bytes = 0;
  // Promoted pages have no interesting remebered sets yet.
  bool record_free_ranges = (p->typed_slot_set<OLD_TO_NEW>() != nullptr ||
                             p->typed_slot_set<OLD_TO_OLD>() != nullptr ||
                             p->typed_slot_set<OLD_TO_SHARED>() != nullptr) ||
                            DEBUG_BOOL;
  // The free ranges map is used for filtering typed slots.
  TypedSlotSet::FreeRangesMap free_ranges_map;
  // Iterate over the page using the live objects and free the memory before
  // the given live object.
  Address free_start = p->area_start();
  for (auto [object, size] : LiveObjectRange(p)) {
    DCHECK(marking_state_->IsMarked(object));
    Address free_end = object.address();
    if (free_end != free_start) {
      FreeAndProcessFreedMemory(free_start, free_end, p, space,
                                free_space_treatment_mode,
                                should_reduce_memory);
      CleanupRememberedSetEntriesForFreedMemory(
          free_start, free_end, p, record_free_ranges, &free_ranges_map,
          sweeping_mode);
    }
    live_bytes += size;
    free_start = free_end + size;
    if (active_system_pages_after_sweeping) {
      MemoryChunk* chunk = p->Chunk();
      active_system_pages_after_sweeping->Add(
          chunk->Offset(free_end), chunk->Offset(free_start),
          MemoryAllocator::GetCommitPageSizeBits());
    }
  }
  // If there is free memory after the last live object also free that.
  Address free_end = p->area_end();
  if (free_end != free_start) {
    FreeAndProcessFreedMemory(free_start, free_end, p, space,
                              free_space_treatment_mode, should_reduce_memory);
    CleanupRememberedSetEntriesForFreedMemory(free_start, free_end, p,
                                              record_free_ranges,
                                              &free_ranges_map, sweeping_mode);
  }
  // Phase 3: Post process the page.
  p->ReleaseSlotSet(SURVIVOR_TO_EXTERNAL_POINTER);
  CleanupTypedSlotsInFreeMemory(p, free_ranges_map, sweeping_mode);
  ClearMarkBitsAndHandleLivenessStatistics(p, live_bytes);
  if (active_system_pages_after_sweeping) {
    // Decrement accounted memory for discarded memory.
    PagedSpaceBase* paged_space = static_cast<PagedSpaceBase*>(p->owner());
    paged_space->ReduceActiveSystemPages(p,
                                         *active_system_pages_after_sweeping);
  }
}
References v8::internal::MemoryChunkMetadata::area_end(), v8::internal::MemoryChunkMetadata::area_start(), v8::internal::MemoryChunk::BLACK_ALLOCATED, v8::internal::MemoryChunkMetadata::Chunk(), CleanupRememberedSetEntriesForFreedMemory(), CleanupTypedSlotsInFreeMemory(), ClearMarkBitsAndHandleLivenessStatistics(), v8::internal::CODE_SPACE, v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NOT_NULL, DEBUG_BOOL, FreeAndProcessFreedMemory(), v8::internal::MemoryAllocator::GetCommitPageSizeBits(), heap_, v8::internal::Heap::incremental_marking(), v8::internal::MemoryChunk::IsEvacuationCandidate(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::IncrementalMarking::IsMajorMarking(), v8::internal::MarkingStateBase< ConcreteState, access_mode >::IsMarked(), v8::internal::IncrementalMarking::IsMinorMarking(), v8::internal::MutablePageMetadata::kPageSize, marking_state_, v8::internal::NEW_SPACE, v8::internal::MemoryChunk::Offset(), v8::internal::OLD_SPACE, v8::internal::OLD_TO_NEW, v8::internal::OLD_TO_OLD, v8::internal::OLD_TO_SHARED, v8::internal::MutablePageMetadata::owner(), v8::internal::PagedSpaceBase::ReduceActiveSystemPages(), v8::internal::MutablePageMetadata::ReleaseSlotSet(), v8::internal::SHARED_SPACE, v8::internal::SHARED_TRUSTED_SPACE, size(), space, v8::internal::SURVIVOR_TO_EXTERNAL_POINTER, v8::internal::MutablePageMetadata::SweepingDone(), v8::internal::TRUSTED_SPACE, v8::internal::MutablePageMetadata::typed_slot_set(), and v8::internal::v8_flags.
ShouldRefillFreelistForSpace()
bool v8::internal::Sweeper::ShouldRefillFreelistForSpace (AllocationSpace space) const
Definition at line 1544 of file sweeper.cc.
                                                                      {
  DCHECK_IMPLIES(space == NEW_SPACE, v8_flags.minor_ms);
  return has_swept_pages_[GetSweepSpaceIndex(space)].load(
      std::memory_order_acquire);
}
References DCHECK_IMPLIES, GetSweepSpaceIndex(), has_swept_pages_, v8::internal::NEW_SPACE, space, and v8::internal::v8_flags.
Referenced by v8::internal::PagedSpaceAllocatorPolicy::RefillLab(), and v8::internal::PagedNewSpaceAllocatorPolicy::WaitForSweepingForAllocation().
StartMajorSweeperTasks()
void v8::internal::Sweeper::StartMajorSweeperTasks ()
Definition at line 769 of file sweeper.cc.
                                     {
  DCHECK_IMPLIES(v8_flags.minor_ms, GarbageCollector::MARK_COMPACTOR ==
                                        heap_->tracer()->GetCurrentCollector());
  DCHECK(!minor_sweeping_in_progress());
  DCHECK(!promoted_page_iteration_in_progress_);
  DCHECK_EQ(0, promoted_pages_for_iteration_count_);
  major_sweeping_state_.StartConcurrentSweeping();
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::GCTracer::GetCurrentCollector(), heap_, major_sweeping_state_, v8::internal::MARK_COMPACTOR, minor_sweeping_in_progress(), promoted_page_iteration_in_progress_, promoted_pages_for_iteration_count_, v8::internal::Sweeper::SweepingState< scope >::StartConcurrentSweeping(), v8::internal::Heap::tracer(), and v8::internal::v8_flags.
Referenced by v8::internal::MarkCompactCollector::Finish().
StartMajorSweeping()
void v8::internal::Sweeper::StartMajorSweeping ()
Definition at line 719 of file sweeper.cc.
                                 {
  DCHECK_EQ(GarbageCollector::MARK_COMPACTOR,
            heap_->tracer()->GetCurrentCollector());
  DCHECK(!minor_sweeping_in_progress());
  major_sweeping_state_.StartSweeping();
  ForAllSweepingSpaces([this](AllocationSpace space) {
    // Sorting is done in order to make compaction more efficient: by sweeping
    // pages with the most free bytes first, we make it more likely that when
    // evacuating a page, already swept pages will have enough free bytes to
    // hold the objects to move (and therefore, we won't need to wait for more
    // pages to be swept in order to move those objects).
    int space_index = GetSweepSpaceIndex(space);
    DCHECK_IMPLIES(space == NEW_SPACE, sweeping_list_[space_index].empty());
    std::sort(sweeping_list_[space_index].begin(),
              sweeping_list_[space_index].end(), ComparePagesForSweepingOrder);
  });
}
References v8::internal::compiler::begin(), v8::internal::anonymous_namespace{sweeper.cc}::ComparePagesForSweepingOrder(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::compiler::end(), ForAllSweepingSpaces(), v8::internal::GCTracer::GetCurrentCollector(), GetSweepSpaceIndex(), heap_, major_sweeping_state_, v8::internal::MARK_COMPACTOR, minor_sweeping_in_progress(), v8::internal::NEW_SPACE, v8::base::sort(), space, v8::internal::Sweeper::SweepingState< scope >::StartSweeping(), sweeping_list_, and v8::internal::Heap::tracer().
StartMinorSweeperTasks()
void v8::internal::Sweeper::StartMinorSweeperTasks ()
Definition at line 812 of file sweeper.cc.
                                     {
  DCHECK(v8_flags.minor_ms);
  DCHECK_EQ(GarbageCollector::MINOR_MARK_SWEEPER,
            heap_->tracer()->GetCurrentCollector());
  DCHECK(!promoted_page_iteration_in_progress_);
  std::vector<MutablePageMetadata*> promoted_pages_for_clearing;
  if (promoted_pages_for_iteration_count_ > 0) {
    if (ShouldUpdateRememberedSets(heap_)) {
      promoted_page_iteration_in_progress_.store(true,
                                                 std::memory_order_release);
    } else {
      promoted_pages_for_clearing.swap(
          sweeping_list_for_promoted_page_iteration_);
      DCHECK(sweeping_list_for_promoted_page_iteration_.empty());
      promoted_pages_for_iteration_count_ = 0;
    }
  }
  minor_sweeping_state_.StartConcurrentSweeping();
  ClearPromotedPages(heap_, promoted_pages_for_clearing);
}
References v8::internal::anonymous_namespace{sweeper.cc}::ClearPromotedPages(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::GCTracer::GetCurrentCollector(), heap_, v8::internal::MINOR_MARK_SWEEPER, minor_sweeping_state_, promoted_page_iteration_in_progress_, promoted_pages_for_iteration_count_, v8::internal::anonymous_namespace{sweeper.cc}::ShouldUpdateRememberedSets(), v8::internal::Sweeper::SweepingState< scope >::StartConcurrentSweeping(), sweeping_list_for_promoted_page_iteration_, v8::internal::Heap::tracer(), and v8::internal::v8_flags.
Referenced by v8::internal::MinorMarkSweepCollector::Sweep().
StartMinorSweeping()
void v8::internal::Sweeper::StartMinorSweeping ()
Definition at line 737 of file sweeper.cc.
                                 {
  DCHECK_EQ(GarbageCollector::MINOR_MARK_SWEEPER,
            heap_->tracer()->GetCurrentCollector());
  minor_sweeping_state_.StartSweeping();
  int new_space_index = GetSweepSpaceIndex(kNewSpace);
  std::sort(sweeping_list_[new_space_index].begin(),
            sweeping_list_[new_space_index].end(),
            ComparePagesForSweepingOrder);
}
References v8::internal::compiler::begin(), v8::internal::anonymous_namespace{sweeper.cc}::ComparePagesForSweepingOrder(), DCHECK_EQ, v8::internal::compiler::end(), v8::internal::GCTracer::GetCurrentCollector(), GetSweepSpaceIndex(), heap_, v8::internal::kNewSpace, v8::internal::MINOR_MARK_SWEEPER, minor_sweeping_state_, v8::base::sort(), v8::internal::Sweeper::SweepingState< scope >::StartSweeping(), sweeping_list_, and v8::internal::Heap::tracer().
Referenced by v8::internal::MinorMarkSweepCollector::Sweep().
SweepEmptyNewSpacePage()
void v8::internal::Sweeper::SweepEmptyNewSpacePage (PageMetadata * page)
Definition at line 1550 of file sweeper.cc.
                                                       {
  DCHECK(v8_flags.minor_ms);
  DCHECK_EQ(kNewSpace, page->owner_identity());
  DCHECK_EQ(0, page->live_bytes());
  DCHECK(page->marking_bitmap()->IsClean());
  DCHECK(heap_->IsMainThread());
  DCHECK(heap_->tracer()->IsInAtomicPause());
  DCHECK_EQ(PageMetadata::ConcurrentSweepingState::kDone,
            page->concurrent_sweeping_state());
  PagedSpaceBase* paged_space = nullptr;
  if (v8_flags.sticky_mark_bits) {
    paged_space = heap_->sticky_space();
  } else {
    paged_space = PagedNewSpace::From(heap_->new_space())->paged_space();
  }
  Address start = page->area_start();
  size_t size = page->area_size();
  if (heap::ShouldZapGarbage()) {
    static constexpr Tagged_t kZapTagged = static_cast<Tagged_t>(kZapValue);
    const size_t size_in_tagged = size / kTaggedSize;
    Tagged_t* current_addr = reinterpret_cast<Tagged_t*>(start);
    for (size_t i = 0; i < size_in_tagged; ++i) {
      base::AsAtomicPtr(current_addr++)
          ->store(kZapTagged, std::memory_order_relaxed);
    }
  }
  page->ResetAllocationStatistics();
  page->ResetAgeInNewSpace();
  page->ReleaseSlotSet(SURVIVOR_TO_EXTERNAL_POINTER);
  page->Chunk()->ClearFlagNonExecutable(MemoryChunk::NEVER_ALLOCATE_ON_PAGE);
  paged_space->FreeDuringSweep(start, size);
  paged_space->IncreaseAllocatedBytes(0, page);
  paged_space->RelinkFreeListCategories(page);
  if (heap_->ShouldReduceMemory()) {
    ZeroOrDiscardUnusedMemory(page, start, size);
    // Only decrement counter when we discard unused system pages.
    ActiveSystemPages active_system_pages_after_sweeping;
    active_system_pages_after_sweeping.Init(
        sizeof(MemoryChunk), MemoryAllocator::GetCommitPageSizeBits(),
        PageMetadata::kPageSize);
    // Decrement accounted memory for discarded memory.
    paged_space->ReduceActiveSystemPages(page,
                                         active_system_pages_after_sweeping);
  }
}
References v8::internal::MemoryChunkMetadata::area_size(), v8::internal::MemoryChunkMetadata::area_start(), v8::base::AsAtomicPtr(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunk::ClearFlagNonExecutable(), v8::internal::MutablePageMetadata::concurrent_sweeping_state(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::PagedSpaceBase::FreeDuringSweep(), v8::internal::PagedNewSpace::From(), v8::internal::MemoryAllocator::GetCommitPageSizeBits(), heap_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::PagedSpaceBase::IncreaseAllocatedBytes(), heap::base::ActiveSystemPages::Init(), v8::internal::MarkingBitmap::IsClean(), v8::internal::Heap::IsMainThread(), v8::internal::MutablePageMetadata::kDone, v8::internal::kNewSpace, v8::internal::MutablePageMetadata::kPageSize, v8::internal::kTaggedSize, v8::internal::kZapValue, v8::internal::MutablePageMetadata::live_bytes(), v8::internal::MutablePageMetadata::marking_bitmap(), v8::internal::MemoryChunk::NEVER_ALLOCATE_ON_PAGE, v8::internal::Heap::new_space(), v8::internal::MutablePageMetadata::owner_identity(), v8::internal::PagedNewSpace::paged_space(), v8::internal::PagedSpaceBase::ReduceActiveSystemPages(), v8::internal::MutablePageMetadata::ReleaseSlotSet(), v8::internal::PagedSpaceBase::RelinkFreeListCategories(), v8::internal::MutablePageMetadata::ResetAgeInNewSpace(), v8::internal::MutablePageMetadata::ResetAllocationStatistics(), v8::internal::Heap::ShouldReduceMemory(), v8::internal::heap::ShouldZapGarbage(), size(), v8::internal::Heap::sticky_space(), v8::internal::SURVIVOR_TO_EXTERNAL_POINTER, v8::internal::Heap::tracer(), v8::internal::v8_flags, and ZeroOrDiscardUnusedMemory().
Referenced by v8::internal::MarkCompactCollector::Finish(), v8::internal::MinorMarkSweepCollector::StartSweepNewSpace(), and v8::internal::MinorMarkSweepCollector::StartSweepNewSpaceWithStickyBits().
sweeping_in_progress()
bool v8::internal::Sweeper::sweeping_in_progress () const [inline]
Definition at line 114 of file sweeper.h.
                                    {
    return minor_sweeping_in_progress() || major_sweeping_in_progress();
  }
References major_sweeping_in_progress(), and minor_sweeping_in_progress().
Referenced by v8::internal::MarkCompactCollector::CollectEvacuationCandidates(), v8::internal::Sweeper::LocalSweeper::ContributeAndWaitForPromotedPagesIterationImpl(), EnsurePageIsSwept(), v8::internal::MarkCompactCollector::Prepare(), and WaitForPageToBeSwept().
sweeping_in_progress_for_space()
bool v8::internal::Sweeper::sweeping_in_progress_for_space (AllocationSpace space) const [inline]
Definition at line 117 of file sweeper.h.
                                                                   {
    if (space == NEW_SPACE) return minor_sweeping_in_progress();
    return major_sweeping_in_progress();
  }
References major_sweeping_in_progress(), minor_sweeping_in_progress(), v8::internal::NEW_SPACE, and space.
TearDown()
void v8::internal::Sweeper::TearDown ()
Definition at line 691 of file sweeper.cc.
                       {
  minor_sweeping_state_.StopConcurrentSweeping();
  major_sweeping_state_.StopConcurrentSweeping();
}
References major_sweeping_state_, minor_sweeping_state_, and v8::internal::Sweeper::SweepingState< scope >::StopConcurrentSweeping().
TryRemovePromotedPageSafe()
bool v8::internal::Sweeper::TryRemovePromotedPageSafe (MutablePageMetadata * chunk) [private]
Definition at line 1374 of file sweeper.cc.
                                                                  {
  base::MutexGuard guard(&mutex_);
  auto position =
      std::find(sweeping_list_for_promoted_page_iteration_.begin(),
                sweeping_list_for_promoted_page_iteration_.end(), chunk);
  if (position == sweeping_list_for_promoted_page_iteration_.end())
    return false;
  sweeping_list_for_promoted_page_iteration_.erase(position);
  return true;
}
References mutex_, and sweeping_list_for_promoted_page_iteration_.
Referenced by EnsurePageIsSwept().
TryRemoveSweepingPageSafe()
bool v8::internal::Sweeper::TryRemoveSweepingPageSafe (AllocationSpace space, PageMetadata * page) [private]
Definition at line 1357 of file sweeper.cc.
                                                            {
  base::MutexGuard guard(&mutex_);
  DCHECK(IsValidSweepingSpace(space));
  int space_index = GetSweepSpaceIndex(space);
  SweepingList& sweeping_list = sweeping_list_[space_index];
  SweepingList::iterator position =
      std::find(sweeping_list.begin(), sweeping_list.end(), page);
  if (position == sweeping_list.end()) return false;
  sweeping_list.erase(position);
  if (sweeping_list.empty()) {
    has_sweeping_work_[GetSweepSpaceIndex(space)].store(
        false, std::memory_order_release);
  }
  return true;
}
References v8::internal::DCHECK(), GetSweepSpaceIndex(), has_sweeping_work_, IsValidSweepingSpace(), mutex_, space, and sweeping_list_.
Referenced by EnsurePageIsSwept().
UsingMajorSweeperTasks()
bool v8::internal::Sweeper::UsingMajorSweeperTasks () const
Definition at line 981 of file sweeper.cc.
                                           {
  return major_sweeping_state_.HasValidJob();
}
References v8::internal::Sweeper::SweepingState< scope >::HasValidJob(), and major_sweeping_state_.
WaitForPageToBeSwept()
void v8::internal::Sweeper::WaitForPageToBeSwept (PageMetadata * page)
Definition at line 1347 of file sweeper.cc.
                                                     {
  DCHECK(heap_->IsMainThread());
  DCHECK(sweeping_in_progress());
  base::MutexGuard guard(&mutex_);
  while (!page->SweepingDone()) {
    cv_page_swept_.Wait(&mutex_);
  }
}
References cv_page_swept_, v8::internal::DCHECK(), heap_, v8::internal::Heap::IsMainThread(), mutex_, sweeping_in_progress(), v8::internal::MutablePageMetadata::SweepingDone(), and v8::base::ConditionVariable::Wait().
Referenced by EnsurePageIsSwept(), and v8::internal::PagedNewSpaceAllocatorPolicy::WaitForSweepingForAllocation().
ZeroOrDiscardUnusedMemory()
void v8::internal::Sweeper::ZeroOrDiscardUnusedMemory (PageMetadata * page, Address addr, size_t size) [private]
Definition at line 1027 of file sweeper.cc.
                                                     {
  if (size < sizeof(FreeSpace)) {
    return;
  }
  const Address unused_start = addr + sizeof(FreeSpace);
  DCHECK(page->ContainsLimit(unused_start));
  const Address unused_end = addr + size;
  DCHECK(page->ContainsLimit(unused_end));
  std::optional<RwxMemoryWriteScope> scope;
  if (page->Chunk()->executable()) {
    scope.emplace("For zeroing unused memory.");
  }
  const std::optional<base::AddressRegion> discard_area =
      ComputeDiscardMemoryArea(unused_start, unused_end);
#if !defined(V8_OS_WIN)
  constexpr bool kDiscardEmptyPages = true;
#else
  // Discarding memory on Windows does not decommit the memory and does not
  // contribute to reduce the memory footprint. On the other hand, these
  // calls become expensive the more memory is allocated in the system and
  // can result in hangs. Thus, it is better to not discard on Windows.
  constexpr bool kDiscardEmptyPages = false;
#endif // !defined(V8_OS_WIN)
  if (kDiscardEmptyPages && discard_area) {
    {
      v8::PageAllocator* page_allocator =
          heap_->memory_allocator()->page_allocator(page->owner_identity());
      DiscardSealedMemoryScope discard_scope("Discard unused memory");
      CHECK(page_allocator->DiscardSystemPages(
          reinterpret_cast<void*>(discard_area->begin()),
          discard_area->size()));
    }
    if (v8_flags.zero_unused_memory) {
      // Now zero unused memory right before and after the discarded OS pages to
      // help with OS page compression.
      memset(reinterpret_cast<void*>(unused_start), 0,
             discard_area->begin() - unused_start);
      memset(reinterpret_cast<void*>(discard_area->end()), 0,
             unused_end - discard_area->end());
    }
  } else if (v8_flags.zero_unused_memory) {
    // Unused memory does not span a full OS page. Simply clear all of the
    // unused memory. This helps with OS page compression.
    memset(reinterpret_cast<void*>(unused_start), 0, unused_end - unused_start);
  }
}
References CHECK, v8::internal::MemoryChunkMetadata::Chunk(), ComputeDiscardMemoryArea(), v8::internal::MemoryChunkMetadata::ContainsLimit(), v8::internal::DCHECK(), v8::PageAllocator::DiscardSystemPages(), v8::internal::MemoryChunk::executable(), heap_, v8::internal::Heap::memory_allocator(), v8::internal::MutablePageMetadata::owner_identity(), v8::internal::MemoryAllocator::page_allocator(), size(), and v8::internal::v8_flags.
Referenced by FreeAndProcessFreedMemory(), and SweepEmptyNewSpacePage().
Member Data Documentation
cv_page_swept_
base::ConditionVariable v8::internal::Sweeper::cv_page_swept_ [private]
Definition at line 324 of file sweeper.h.
Referenced by AddSweptPage(), NotifyPromotedPageIterationFinished(), and WaitForPageToBeSwept().
has_sweeping_work_
std::atomic<bool> v8::internal::Sweeper::has_sweeping_work_[kNumberOfSweepingSpaces] {false} [private]
Definition at line 327 of file sweeper.h.
Referenced by AddPageImpl(), GetSweepingPageSafe(), IsSweepingDoneForSpace(), and TryRemoveSweepingPageSafe().
has_swept_pages_
std::atomic<bool> v8::internal::Sweeper::has_swept_pages_[kNumberOfSweepingSpaces] {false} [private]
Definition at line 328 of file sweeper.h.
Referenced by AddSweptPage(), GetAllSweptPagesSafe(), GetSweptPageSafe(), and ShouldRefillFreelistForSpace().
heap_
Heap* const v8::internal::Sweeper::heap_ [private]
Definition at line 321 of file sweeper.h.
Referenced by AddNewSpacePage(), AddPageImpl(), AddPromotedPage(), EnsureMajorCompleted(), EnsurePageIsSwept(), FinishMajorJobs(), FinishMinorJobs(), ParallelSweepSpace(), PrepareToBeSweptPage(), RawSweep(), v8::internal::Sweeper::MajorSweeperJob::Run(), v8::internal::Sweeper::MinorSweeperJob::Run(), v8::internal::Sweeper::MajorSweeperJob::RunImpl(), v8::internal::Sweeper::MinorSweeperJob::RunImpl(), StartMajorSweeperTasks(), StartMajorSweeping(), StartMinorSweeperTasks(), StartMinorSweeping(), SweepEmptyNewSpacePage(), WaitForPageToBeSwept(), and ZeroOrDiscardUnusedMemory().
iterated_promoted_pages_count_
std::atomic<size_t> v8::internal::Sweeper::iterated_promoted_pages_count_ {0} [private]
Definition at line 337 of file sweeper.h.
Referenced by EnsureMinorCompleted(), FinishMinorJobs(), NotifyPromotedPageIterationFinished(), and NotifyPromotedPagesIterationFinished().
kNumberOfSweepingSpaces
constexpr int v8::internal::Sweeper::kNumberOfSweepingSpaces [static], [constexpr], [private]
Initial value:
=
      LAST_SWEEPABLE_SPACE - FIRST_SWEEPABLE_SPACE + 1
Definition at line 206 of file sweeper.h.
Referenced by ConcurrentMajorSweepingPageCount().
main_thread_local_sweeper_
LocalSweeper v8::internal::Sweeper::main_thread_local_sweeper_ [private]
Definition at line 330 of file sweeper.h.
Referenced by ContributeAndWaitForPromotedPagesIteration(), EnsurePageIsSwept(), FinishMajorJobs(), FinishMinorJobs(), and ParallelSweepSpace().
major_sweeping_state_
SweepingState<SweepingScope::kMajor> v8::internal::Sweeper::major_sweeping_state_ {this} [private]
Definition at line 331 of file sweeper.h.
Referenced by AddPageImpl(), AreMajorSweeperTasksRunning(), EnsureMajorCompleted(), FinishMajorJobs(), GetTraceIdForFlowEvent(), InitializeMajorSweeping(), major_sweeping_in_progress(), v8::internal::Sweeper::PauseMajorSweepingScope::PauseMajorSweepingScope(), StartMajorSweeperTasks(), StartMajorSweeping(), TearDown(), and UsingMajorSweeperTasks().
marking_state_
NonAtomicMarkingState* const v8::internal::Sweeper::marking_state_ [private]
Definition at line 322 of file sweeper.h.
Referenced by marking_state(), and RawSweep().
minor_sweeping_state_
SweepingState<SweepingScope::kMinor> v8::internal::Sweeper::minor_sweeping_state_ {this} [private]
Definition at line 332 of file sweeper.h.
Referenced by AddPageImpl(), AddPromotedPage(), AreMinorSweeperTasksRunning(), EnsureMinorCompleted(), FinishMinorJobs(), GetTraceIdForFlowEvent(), InitializeMinorSweeping(), minor_sweeping_in_progress(), StartMinorSweeperTasks(), StartMinorSweeping(), and TearDown().
mutex_
base::Mutex v8::internal::Sweeper::mutex_ [private]
Definition at line 323 of file sweeper.h.
Referenced by AddSweptPage(), ConcurrentMajorSweepingPageCount(), ConcurrentMinorSweepingPageCount(), GetAllSweptPagesSafe(), GetPromotedPageSafe(), GetSweepingPageSafe(), GetSweptPageSafe(), NotifyPromotedPageIterationFinished(), TryRemovePromotedPageSafe(), TryRemoveSweepingPageSafe(), and WaitForPageToBeSwept().
promoted_page_iteration_in_progress_
std::atomic<bool> v8::internal::Sweeper::promoted_page_iteration_in_progress_ {false} [private]
Definition at line 340 of file sweeper.h.
Referenced by IsIteratingPromotedPages(), NotifyPromotedPagesIterationFinished(), StartMajorSweeperTasks(), and StartMinorSweeperTasks().
promoted_pages_for_iteration_count_
size_t v8::internal::Sweeper::promoted_pages_for_iteration_count_ = 0 [private]
Definition at line 336 of file sweeper.h.
Referenced by AddPromotedPage(), EnsureMinorCompleted(), FinishMinorJobs(), NotifyPromotedPageIterationFinished(), NotifyPromotedPagesIterationFinished(), StartMajorSweeperTasks(), and StartMinorSweeperTasks().
promoted_pages_iteration_notification_mutex_
base::Mutex v8::internal::Sweeper::promoted_pages_iteration_notification_mutex_ [private]
Definition at line 338 of file sweeper.h.
Referenced by v8::internal::Sweeper::LocalSweeper::ContributeAndWaitForPromotedPagesIterationImpl(), and NotifyPromotedPagesIterationFinished().
promoted_pages_iteration_notification_variable_
base::ConditionVariable v8::internal::Sweeper::promoted_pages_iteration_notification_variable_ [private]
Definition at line 339 of file sweeper.h.
Referenced by v8::internal::Sweeper::LocalSweeper::ContributeAndWaitForPromotedPagesIterationImpl(), and NotifyPromotedPagesIterationFinished().
sweeping_list_
SweepingList v8::internal::Sweeper::sweeping_list_[kNumberOfSweepingSpaces] [private]
Definition at line 326 of file sweeper.h.
Referenced by AddPageImpl(), ConcurrentMajorSweepingPageCount(), ConcurrentMinorSweepingPageCount(), FinishMajorJobs(), FinishMinorJobs(), GetSweepingPageSafe(), StartMajorSweeping(), StartMinorSweeping(), and TryRemoveSweepingPageSafe().
sweeping_list_for_promoted_page_iteration_
std::vector<MutablePageMetadata*> v8::internal::Sweeper::sweeping_list_for_promoted_page_iteration_ [private]
Definition at line 329 of file sweeper.h.
Referenced by AddPromotedPage(), ConcurrentMinorSweepingPageCount(), FinishMinorJobs(), GetPromotedPageSafe(), StartMinorSweeperTasks(), and TryRemovePromotedPageSafe().
swept_list_
SweptList v8::internal::Sweeper::swept_list_[kNumberOfSweepingSpaces] [private]
Definition at line 325 of file sweeper.h.
Referenced by AddSweptPage(), GetAllSweptPagesSafe(), and GetSweptPageSafe().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/sweeper.h
/mnt/V8SourceCode/src/heap/sweeper.cc