v8::internal::wasm::WasmModuleBuilder Class Reference
#include <wasm-module-builder.h>
Classes
struct RecGroup
struct WasmDataSegment
class WasmElemSegment
struct WasmExport
struct WasmFunctionImport
struct WasmGlobal
struct WasmGlobalImport
struct WasmMemory
struct WasmTable
Public Member Functions
WasmModuleBuilder (Zone *zone)
WasmModuleBuilder (const WasmModuleBuilder &)=delete
WasmModuleBuilder & operator= (const WasmModuleBuilder &)=delete
uint32_t AddImport (base::Vector< const char > name, const FunctionSig *sig, base::Vector< const char > module={})
WasmFunctionBuilder * AddFunction (const FunctionSig *sig=nullptr)
WasmFunctionBuilder * AddFunction (ModuleTypeIndex sig_index)
uint32_t AddGlobal (ValueType type, bool mutability, WasmInitExpr init)
uint32_t AddGlobalImport (base::Vector< const char > name, ValueType type, bool mutability, base::Vector< const char > module={})
void AddDataSegment (const uint8_t *data, uint32_t size, uint32_t dest)
void AddPassiveDataSegment (const uint8_t *data, uint32_t size)
uint32_t AddElementSegment (WasmElemSegment segment)
void SetIndirectFunction (uint32_t table_index, uint32_t index_in_table, uint32_t direct_function_index, WasmElemSegment::FunctionIndexingMode indexing_mode)
uint32_t IncreaseTableMinSize (uint32_t table_index, uint32_t count)
ModuleTypeIndex AddSignature (const FunctionSig *sig, bool is_final, ModuleTypeIndex supertype=kNoSuperType)
ModuleTypeIndex ForceAddSignature (const FunctionSig *sig, bool is_final, ModuleTypeIndex supertype=kNoSuperType)
uint32_t AddTag (const FunctionSig *type)
ModuleTypeIndex AddStructType (StructType *type, bool is_final, ModuleTypeIndex supertype=kNoSuperType)
ModuleTypeIndex AddArrayType (ArrayType *type, bool is_final, ModuleTypeIndex supertype=kNoSuperType)
uint32_t AddTable (ValueType type, uint32_t min_size)
uint32_t AddTable (ValueType type, uint32_t min_size, uint32_t max_size, AddressType address_type=AddressType::kI32)
uint32_t AddTable (ValueType type, uint32_t min_size, uint32_t max_size, WasmInitExpr init, AddressType address_type=AddressType::kI32)
uint32_t AddMemory (uint32_t min_pages)
uint32_t AddMemory (uint32_t min_pages, uint32_t max_pages)
uint32_t AddMemory64 (uint32_t min_pages)
uint32_t AddMemory64 (uint32_t min_pages, uint32_t max_pages)
void MarkStartFunction (WasmFunctionBuilder *builder)
void AddExport (base::Vector< const char > name, ImportExportKindCode kind, uint32_t index)
void AddExport (base::Vector< const char > name, WasmFunctionBuilder *builder)
uint32_t AddExportedGlobal (ValueType type, bool mutability, WasmInitExpr init, base::Vector< const char > name)
void ExportImportedFunction (base::Vector< const char > name, int import_index)
void StartRecursiveTypeGroup ()
void EndRecursiveTypeGroup ()
void AddRecursiveTypeGroup (uint32_t start, uint32_t size)
void WriteTo (ZoneBuffer *buffer) const
void WriteAsmJsOffsetTable (ZoneBuffer *buffer) const
Zone * zone ()
ValueType GetTableType (uint32_t index)
bool IsSignature (uint32_t index)
bool IsSignature (ModuleTypeIndex index)
const FunctionSig * GetSignature (uint32_t index)
const FunctionSig * GetSignature (ModuleTypeIndex index)
bool IsStructType (uint32_t index)
bool IsStructType (ModuleTypeIndex index)
const StructType * GetStructType (uint32_t index)
const StructType * GetStructType (ModuleTypeIndex index)
bool IsArrayType (uint32_t index)
bool IsArrayType (ModuleTypeIndex index)
const ArrayType * GetArrayType (uint32_t index)
const ArrayType * GetArrayType (ModuleTypeIndex index)
ModuleTypeIndex GetSuperType (uint32_t index)
WasmFunctionBuilder * GetFunction (uint32_t index)
int NumTags ()
int NumTypes ()
int NumTables ()
int NumMemories ()
int NumGlobals ()
int NumImportedFunctions ()
int NumDeclaredFunctions ()
int NumDataSegments ()
bool IsMemory64 (uint32_t index)
bool IsTable64 (uint32_t index)
const FunctionSig * GetTagType (int index)
ValueType GetGlobalType (uint32_t index) const
bool IsMutableGlobal (uint32_t index) const
Private Attributes
Zone * zone_
ZoneVector< TypeDefinition > types_
ZoneVector< WasmFunctionImport > function_imports_
ZoneVector< WasmGlobalImport > global_imports_
ZoneVector< WasmExport > exports_
ZoneVector< WasmFunctionBuilder * > functions_
ZoneVector< WasmTable > tables_
ZoneVector< WasmMemory > memories_
ZoneVector< WasmDataSegment > data_segments_
ZoneVector< WasmElemSegment > element_segments_
ZoneVector< WasmGlobal > globals_
ZoneVector< ModuleTypeIndex > tags_
ZoneUnorderedMap< FunctionSig, ModuleTypeIndex > signature_map_
int current_recursive_group_start_
ZoneVector< RecGroup > recursive_groups_
int start_function_index_
Friends
class WasmFunctionBuilder
Detailed Description
Definition at line 257 of file wasm-module-builder.h.
Constructor & Destructor Documentation
WasmModuleBuilder() [1/2]
v8::internal::wasm::WasmModuleBuilder::WasmModuleBuilder (Zone * zone) [explicit]
Definition at line 435 of file wasm-module-builder.cc.
    : zone_(zone),
      types_(zone),
      function_imports_(zone),
      global_imports_(zone),
      exports_(zone),
      functions_(zone),
      tables_(zone),
      memories_(zone),
      data_segments_(zone),
      element_segments_(zone),
      globals_(zone),
      tags_(zone),
      signature_map_(zone),
      current_recursive_group_start_(-1),
      recursive_groups_(zone),
      start_function_index_(-1) {}
WasmModuleBuilder() [2/2]
v8::internal::wasm::WasmModuleBuilder::WasmModuleBuilder (const WasmModuleBuilder &) [delete]
Member Function Documentation
AddArrayType()
ModuleTypeIndex v8::internal::wasm::WasmModuleBuilder::AddArrayType (ArrayType * type, bool is_final, ModuleTypeIndex supertype = kNoSuperType)
Definition at line 517 of file wasm-module-builder.cc.
                                                                           {
  uint32_t index = static_cast<uint32_t>(types_.size());
  types_.emplace_back(type, supertype, is_final, false);
  return ModuleTypeIndex{index};
}
References v8::internal::index, v8::internal::tracing::type, and types_.
Referenced by v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForDeopt(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions().
AddDataSegment()
void v8::internal::wasm::WasmModuleBuilder::AddDataSegment (const uint8_t * data, uint32_t size, uint32_t dest)
Definition at line 466 of file wasm-module-builder.cc.
                                                      {
  data_segments_.push_back({.data = ZoneVector<uint8_t>(zone()), .dest = dest});
  ZoneVector<uint8_t>& vec = data_segments_.back().data;
  for (uint32_t i = 0; i < size; i++) {
    vec.push_back(data[i]);
  }
}
References data_segments_, v8::internal::ZoneVector< T >::push_back(), size(), and zone().
AddElementSegment()
uint32_t v8::internal::wasm::WasmModuleBuilder::AddElementSegment (WasmElemSegment segment)
Definition at line 591 of file wasm-module-builder.cc.
                                                                     {
  element_segments_.push_back(std::move(segment));
  return static_cast<uint32_t>(element_segments_.size() - 1);
}
References element_segments_.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateRefTypeElementSegment(), and SetIndirectFunction().
AddExport() [1/2]
void v8::internal::wasm::WasmModuleBuilder::AddExport (base::Vector< const char > name, ImportExportKindCode kind, uint32_t index)
Definition at line 631 of file wasm-module-builder.cc.
                                                                             {
  DCHECK_LE(index, std::numeric_limits<int>::max());
  exports_.push_back(
      {.name = name, .kind = kind, .index = static_cast<int>(index)});
}
References DCHECK_LE, exports_, v8::internal::index, and v8::internal::wasm::name().
Referenced by AddExportedGlobal(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), and v8::internal::wasm::AsmJsParser::ValidateExport().
AddExport() [2/2]
void v8::internal::wasm::WasmModuleBuilder::AddExport (base::Vector< const char > name, WasmFunctionBuilder * builder) [inline]
Definition at line 377 of file wasm-module-builder.h.
                                                                            {
    AddExport(name, kExternalFunction, builder->func_index());
  }
References v8::internal::wasm::WasmFunctionBuilder::func_index(), v8::internal::wasm::kExternalFunction, and v8::internal::wasm::name().
AddExportedGlobal()
uint32_t v8::internal::wasm::WasmModuleBuilder::AddExportedGlobal (ValueType type, bool mutability, WasmInitExpr init, base::Vector< const char > name)
Definition at line 638 of file wasm-module-builder.cc.
                                                                           {
  uint32_t index = AddGlobal(type, mutability, init);
  AddExport(name, kExternalGlobal, index);
  return index;
}
References AddExport(), AddGlobal(), v8::internal::index, v8::internal::wasm::kExternalGlobal, v8::internal::wasm::name(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions().
AddFunction() [1/2]
WasmFunctionBuilder * v8::internal::wasm::WasmModuleBuilder::AddFunction (const FunctionSig * sig = nullptr)
Definition at line 453 of file wasm-module-builder.cc.
                                                                          {
  functions_.push_back(zone_->New<WasmFunctionBuilder>(this));
  // Add the signature if one was provided here.
  if (sig) functions_.back()->SetSignature(sig);
  return functions_.back();
}
References functions_, v8::internal::Zone::New(), v8::internal::sig, and zone_.
Referenced by v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), v8::internal::wasm::AsmJsParser::ValidateCall(), v8::internal::wasm::AsmJsParser::ValidateFunction(), and v8::internal::wasm::AsmJsParser::ValidateModule().
AddFunction() [2/2]
WasmFunctionBuilder * v8::internal::wasm::WasmModuleBuilder::AddFunction (ModuleTypeIndex sig_index)
Definition at line 460 of file wasm-module-builder.cc.
                                                                             {
  functions_.push_back(zone_->New<WasmFunctionBuilder>(this));
  functions_.back()->SetSignature(sig_index);
  return functions_.back();
}
References functions_, v8::internal::Zone::New(), and zone_.
AddGlobal()
uint32_t v8::internal::wasm::WasmModuleBuilder::AddGlobal (ValueType type, bool mutability, WasmInitExpr init)
Definition at line 658 of file wasm-module-builder.cc.
                                                         {
  globals_.push_back({.type = type, .mutability = mutability, .init = init});
  return static_cast<uint32_t>(globals_.size() - 1);
}
References globals_, and v8::internal::tracing::type.
Referenced by AddExportedGlobal(), and v8::internal::wasm::AsmJsParser::DeclareGlobal().
AddGlobalImport()
uint32_t v8::internal::wasm::WasmModuleBuilder::AddGlobalImport (base::Vector< const char > name, ValueType type, bool mutability, base::Vector< const char > module = {})
Definition at line 617 of file wasm-module-builder.cc.
                                                                           {
  global_imports_.push_back({.module = module,
                             .name = name,
                             .type_code = type.value_type_code(),
                             .mutability = mutability});
  return static_cast<uint32_t>(global_imports_.size() - 1);
}
References global_imports_, v8::internal::wasm::name(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::AsmJsParser::ValidateModule().
AddImport()
uint32_t v8::internal::wasm::WasmModuleBuilder::AddImport (base::Vector< const char > name, const FunctionSig * sig, base::Vector< const char > module = {})
Definition at line 608 of file wasm-module-builder.cc.
                                                                     {
  DCHECK(adding_imports_allowed_);
  function_imports_.push_back(
      {.module = module, .name = name, .sig_index = AddSignature(sig, true)});
  return static_cast<uint32_t>(function_imports_.size() - 1);
}
References AddSignature(), v8::internal::DCHECK(), function_imports_, v8::internal::wasm::name(), and v8::internal::sig.
Referenced by v8::internal::wasm::AsmJsParser::ValidateCall(), and v8::internal::wasm::AsmJsParser::ValidateModule().
AddMemory() [1/2]
uint32_t v8::internal::wasm::WasmModuleBuilder::AddMemory (uint32_t min_pages)
Definition at line 565 of file wasm-module-builder.cc.
                                                        {
  memories_.push_back({.min_pages = min_pages});
  return static_cast<uint32_t>(memories_.size() - 1);
}
References memories_.
Referenced by v8::internal::wasm::AsmJsParser::AsmJsParser().
AddMemory() [2/2]
uint32_t v8::internal::wasm::WasmModuleBuilder::AddMemory (uint32_t min_pages, uint32_t max_pages)
Definition at line 570 of file wasm-module-builder.cc.
                                                                            {
  memories_.push_back(
      {.min_pages = min_pages, .max_pages = max_pages, .has_max_pages = true});
  return static_cast<uint32_t>(memories_.size() - 1);
}
References memories_.
AddMemory64() [1/2]
uint32_t v8::internal::wasm::WasmModuleBuilder::AddMemory64 (uint32_t min_pages)
Definition at line 576 of file wasm-module-builder.cc.
                                                          {
  memories_.push_back(
      {.min_pages = min_pages, .address_type = AddressType::kI64});
  return static_cast<uint32_t>(memories_.size() - 1);
}
References v8::internal::wasm::kI64, and memories_.
AddMemory64() [2/2]
uint32_t v8::internal::wasm::WasmModuleBuilder::AddMemory64 (uint32_t min_pages, uint32_t max_pages)
Definition at line 582 of file wasm-module-builder.cc.
                                                            {
  memories_.push_back({.min_pages = min_pages,
                       .max_pages = max_pages,
                       .has_max_pages = true,
                       .address_type = AddressType::kI64});
  return static_cast<uint32_t>(memories_.size() - 1);
}
References v8::internal::wasm::kI64, and memories_.
AddPassiveDataSegment()
void v8::internal::wasm::WasmModuleBuilder::AddPassiveDataSegment (const uint8_t * data, uint32_t size)
Definition at line 475 of file wasm-module-builder.cc.
                                                             {
  data_segments_.push_back(
      {.data = ZoneVector<uint8_t>(zone()), .dest = 0, .is_active = false});
  ZoneVector<uint8_t>& vec = data_segments_.back().data;
  for (uint32_t i = 0; i < size; i++) {
    vec.push_back(data[i]);
  }
}
References data_segments_, v8::internal::ZoneVector< T >::push_back(), size(), and zone().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GeneratePassiveDataSegment().
AddRecursiveTypeGroup()
void v8::internal::wasm::WasmModuleBuilder::AddRecursiveTypeGroup (uint32_t start, uint32_t size) [inline]
Definition at line 398 of file wasm-module-builder.h.
                                                            {
    recursive_groups_.emplace_back(start, size);
  }
References size().
AddSignature()
ModuleTypeIndex v8::internal::wasm::WasmModuleBuilder::AddSignature (const FunctionSig * sig, bool is_final, ModuleTypeIndex supertype = kNoSuperType)
Definition at line 493 of file wasm-module-builder.cc.
                                                                           {
  auto sig_entry = signature_map_.find(*sig);
  if (sig_entry != signature_map_.end()) return sig_entry->second;
  return ForceAddSignature(sig, is_final, supertype);
}
References ForceAddSignature(), v8::internal::sig, and signature_map_.
Referenced by AddImport(), AddTag(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope(), v8::internal::wasm::WasmFunctionBuilder::SetSignature(), and v8::internal::wasm::AsmJsParser::ValidateCall().
AddStructType()
ModuleTypeIndex v8::internal::wasm::WasmModuleBuilder::AddStructType (StructType * type, bool is_final, ModuleTypeIndex supertype = kNoSuperType)
Definition at line 509 of file wasm-module-builder.cc.
                                                                            {
  uint32_t index = static_cast<uint32_t>(types_.size());
  types_.emplace_back(type, supertype, is_final, false);
  return ModuleTypeIndex{index};
}
References v8::internal::index, v8::internal::tracing::type, and types_.
Referenced by v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions().
AddTable() [1/3]
uint32_t v8::internal::wasm::WasmModuleBuilder::AddTable (ValueType type, uint32_t min_size)
Definition at line 537 of file wasm-module-builder.cc.
                                                                      {
  tables_.push_back({.type = type, .min_size = min_size});
  return static_cast<uint32_t>(tables_.size() - 1);
}
References tables_, and v8::internal::tracing::type.
Referenced by v8::internal::wasm::AsmJsParser::ValidateCall().
AddTable() [2/3]
uint32_t v8::internal::wasm::WasmModuleBuilder::AddTable (ValueType type, uint32_t min_size, uint32_t max_size, AddressType address_type = AddressType::kI32)
Definition at line 542 of file wasm-module-builder.cc.
                                                               {
  tables_.push_back({.type = type,
                     .min_size = min_size,
                     .max_size = max_size,
                     .has_maximum = true,
                     .address_type = address_type});
  return static_cast<uint32_t>(tables_.size() - 1);
}
References tables_, and v8::internal::tracing::type.
AddTable() [3/3]
uint32_t v8::internal::wasm::WasmModuleBuilder::AddTable (ValueType type, uint32_t min_size, uint32_t max_size, WasmInitExpr init, AddressType address_type = AddressType::kI32)
Definition at line 553 of file wasm-module-builder.cc.
                                                               {
  tables_.push_back({.type = type,
                     .min_size = min_size,
                     .max_size = max_size,
                     .has_maximum = true,
                     .address_type = address_type,
                     .init = {init}});
  return static_cast<uint32_t>(tables_.size() - 1);
}
References tables_, and v8::internal::tracing::type.
AddTag()
uint32_t v8::internal::wasm::WasmModuleBuilder::AddTag (const FunctionSig * type)
Definition at line 501 of file wasm-module-builder.cc.
                                                          {
  DCHECK_EQ(0, type->return_count());
  ModuleTypeIndex type_index = AddSignature(type, true);
  uint32_t except_index = static_cast<uint32_t>(tags_.size());
  tags_.push_back(type_index);
  return except_index;
}
References AddSignature(), DCHECK_EQ, tags_, and v8::internal::tracing::type.
EndRecursiveTypeGroup()
void v8::internal::wasm::WasmModuleBuilder::EndRecursiveTypeGroup () [inline]
Definition at line 389 of file wasm-module-builder.h.
                               {
    // Make sure we are in a recursive group.
    DCHECK_NE(current_recursive_group_start_, -1);
    recursive_groups_.emplace_back(
        current_recursive_group_start_,
        static_cast<uint32_t>(types_.size()) - current_recursive_group_start_);
    current_recursive_group_start_ = -1;
  }
References DCHECK_NE.
ExportImportedFunction()
void v8::internal::wasm::WasmModuleBuilder::ExportImportedFunction (base::Vector< const char > name, int import_index)
Definition at line 646 of file wasm-module-builder.cc.
                                                                 {
#if DEBUG
  // The size of function_imports_ must not change any more.
  adding_imports_allowed_ = false;
#endif
  exports_.push_back(
      {.name = name,
       .kind = kExternalFunction,
       .index = import_index - static_cast<int>(function_imports_.size())});
}
References exports_, function_imports_, v8::internal::wasm::kExternalFunction, and v8::internal::wasm::name().
ForceAddSignature()
ModuleTypeIndex v8::internal::wasm::WasmModuleBuilder::ForceAddSignature (const FunctionSig * sig, bool is_final, ModuleTypeIndex supertype = kNoSuperType)
Definition at line 485 of file wasm-module-builder.cc.
                                                                      {
  ModuleTypeIndex index{static_cast<uint32_t>(types_.size())};
  signature_map_.emplace(*sig, index);
  types_.emplace_back(sig, supertype, is_final, false);
  return index;
}
References v8::internal::index, v8::internal::sig, signature_map_, and types_.
Referenced by AddSignature(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForDeopt(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec().
GetArrayType() [1/2]
const ArrayType* v8::internal::wasm::WasmModuleBuilder::GetArrayType (ModuleTypeIndex index) [inline]
Definition at line 441 of file wasm-module-builder.h.
                                                       {
    return GetArrayType(index.index);
  }
References v8::internal::index.
GetArrayType() [2/2]
const ArrayType* v8::internal::wasm::WasmModuleBuilder::GetArrayType (uint32_t index) [inline]
Definition at line 438 of file wasm-module-builder.h.
                                                {
    return types_[index].array_type;
  }
References v8::internal::index.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_set(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateArrayInitExpr(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions().
GetFunction()
WasmFunctionBuilder* v8::internal::wasm::WasmModuleBuilder::GetFunction (uint32_t index) [inline]
Definition at line 449 of file wasm-module-builder.h.
{ return functions_[index]; }
References v8::internal::index.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
GetGlobalType()
ValueType v8::internal::wasm::WasmModuleBuilder::GetGlobalType (uint32_t index) const [inline]
Definition at line 475 of file wasm-module-builder.h.
{ return globals_[index].type; }
References v8::internal::index.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
GetSignature() [1/2]
const FunctionSig* v8::internal::wasm::WasmModuleBuilder::GetSignature (ModuleTypeIndex index) [inline]
Definition at line 419 of file wasm-module-builder.h.
                                                         {
    return GetSignature(index.index);
  }
References v8::internal::index.
GetSignature() [2/2]
const FunctionSig* v8::internal::wasm::WasmModuleBuilder::GetSignature (uint32_t index) [inline]
Definition at line 415 of file wasm-module-builder.h.
                                                  {
    DCHECK(types_[index].kind == TypeDefinition::kFunction);
    return types_[index].function_sig;
  }
References v8::internal::DCHECK(), v8::internal::index, and v8::internal::wasm::TypeDefinition::kFunction.
GetStructType() [1/2]
const StructType* v8::internal::wasm::WasmModuleBuilder::GetStructType (ModuleTypeIndex index) [inline]
Definition at line 430 of file wasm-module-builder.h.
                                                         {
    return GetStructType(index.index);
  }
References v8::internal::index.
GetStructType() [2/2]
const StructType* v8::internal::wasm::WasmModuleBuilder::GetStructType (uint32_t index) [inline]
Definition at line 427 of file wasm-module-builder.h.
                                                  {
    return types_[index].struct_type;
  }
References v8::internal::index.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateStructNewInitExpr(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_helper(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_set().
GetSuperType()
ModuleTypeIndex v8::internal::wasm::WasmModuleBuilder::GetSuperType (uint32_t index) [inline]
Definition at line 445 of file wasm-module-builder.h.
                                               {
    return types_[index].supertype;
  }
References v8::internal::index.
GetTableType()
ValueType v8::internal::wasm::WasmModuleBuilder::GetTableType (uint32_t index) [inline]
Definition at line 408 of file wasm-module-builder.h.
{ return tables_[index].type; }
References v8::internal::index.
GetTagType()
const FunctionSig* v8::internal::wasm::WasmModuleBuilder::GetTagType (int index) [inline]
Definition at line 471 of file wasm-module-builder.h.
                                           {
    return types_[tags_[index].index].function_sig;
  }
References v8::internal::index.
IncreaseTableMinSize()
uint32_t v8::internal::wasm::WasmModuleBuilder::IncreaseTableMinSize (uint32_t table_index, uint32_t count)
Definition at line 524 of file wasm-module-builder.cc.
                                                                 {
  DCHECK_LT(table_index, tables_.size());
  uint32_t old_min_size = tables_[table_index].min_size;
  if (count > wasm::max_table_size() - old_min_size) {
    return std::numeric_limits<uint32_t>::max();
  }
  tables_[table_index].min_size = old_min_size + count;
  tables_[table_index].max_size =
      std::max(old_min_size + count, tables_[table_index].max_size);
  return old_min_size;
}
References DCHECK_LT, v8::internal::wasm::max_table_size(), and tables_.
Referenced by v8::internal::wasm::AsmJsParser::ValidateCall().
IsArrayType() [1/2]
bool v8::internal::wasm::WasmModuleBuilder::IsArrayType (ModuleTypeIndex index) [inline]
Definition at line 437 of file wasm-module-builder.h.
{ return IsArrayType(index.index); }
References v8::internal::index, and IsArrayType().
Referenced by IsArrayType().
IsArrayType() [2/2]
bool v8::internal::wasm::WasmModuleBuilder::IsArrayType (uint32_t index) [inline]
Definition at line 434 of file wasm-module-builder.h.
                                   {
    return types_[index].kind == TypeDefinition::kArray;
  }
References v8::internal::index, and v8::internal::wasm::TypeDefinition::kArray.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_set(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
IsMemory64()
bool v8::internal::wasm::WasmModuleBuilder::IsMemory64 (uint32_t index) [inline]
Definition at line 467 of file wasm-module-builder.h.
{ return memories_[index].is_memory64(); }
References v8::internal::index.
Referenced by v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec().
IsMutableGlobal()
bool v8::internal::wasm::WasmModuleBuilder::IsMutableGlobal (uint32_t index) const [inline]
Definition at line 477 of file wasm-module-builder.h.
                                             {
    return globals_[index].mutability;
  }
References v8::internal::index.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
IsSignature() [1/2]
bool v8::internal::wasm::WasmModuleBuilder::IsSignature (ModuleTypeIndex index) [inline]
Definition at line 413 of file wasm-module-builder.h.
{ return IsSignature(index.index); }
References v8::internal::index, and IsSignature().
Referenced by IsSignature().
IsSignature() [2/2]
bool v8::internal::wasm::WasmModuleBuilder::IsSignature (uint32_t index) [inline]
Definition at line 410 of file wasm-module-builder.h.
                                   {
    return types_[index].kind == TypeDefinition::kFunction;
  }
References v8::internal::index, and v8::internal::wasm::TypeDefinition::kFunction.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
IsStructType() [1/2]
bool v8::internal::wasm::WasmModuleBuilder::IsStructType (ModuleTypeIndex index) [inline]
Definition at line 426 of file wasm-module-builder.h.
{ return IsStructType(index.index); }
References v8::internal::index, and IsStructType().
Referenced by IsStructType().
IsStructType() [2/2]
bool v8::internal::wasm::WasmModuleBuilder::IsStructType (uint32_t index) [inline]
Definition at line 423 of file wasm-module-builder.h.
                                    {
    return types_[index].kind == TypeDefinition::kStruct;
  }
References v8::internal::index, and v8::internal::wasm::TypeDefinition::kStruct.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_helper(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_set().
IsTable64()
bool v8::internal::wasm::WasmModuleBuilder::IsTable64 (uint32_t index) [inline]
Definition at line 469 of file wasm-module-builder.h.
{ return tables_[index].is_table64(); }
References v8::internal::index.
MarkStartFunction()
void v8::internal::wasm::WasmModuleBuilder::MarkStartFunction (WasmFunctionBuilder * builder)
Definition at line 627 of file wasm-module-builder.cc.
                                                                       {
  start_function_index_ = function->func_index();
}
References start_function_index_.
Referenced by v8::internal::wasm::AsmJsParser::ValidateModule().
NumDataSegments()
int v8::internal::wasm::WasmModuleBuilder::NumDataSegments () [inline]
Definition at line 465 of file wasm-module-builder.h.
{ return static_cast<int>(data_segments_.size()); }
NumDeclaredFunctions()
int v8::internal::wasm::WasmModuleBuilder::NumDeclaredFunctions () [inline]
Definition at line 463 of file wasm-module-builder.h.
{ return static_cast<int>(functions_.size()); }
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
NumGlobals()
int v8::internal::wasm::WasmModuleBuilder::NumGlobals () [inline]
Definition at line 458 of file wasm-module-builder.h.
{ return static_cast<int>(globals_.size()); }
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
NumImportedFunctions()
int v8::internal::wasm::WasmModuleBuilder::NumImportedFunctions () [inline]
Definition at line 460 of file wasm-module-builder.h.
                             {
    return static_cast<int>(function_imports_.size());
  }
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr().
NumMemories()
int v8::internal::wasm::WasmModuleBuilder::NumMemories () [inline]
Definition at line 456 of file wasm-module-builder.h.
{ return static_cast<int>(memories_.size()); }
NumTables()
int v8::internal::wasm::WasmModuleBuilder::NumTables () [inline]
Definition at line 454 of file wasm-module-builder.h.
{ return static_cast<int>(tables_.size()); }
Referenced by v8::internal::wasm::AsmJsParser::ValidateCall().
NumTags()
int v8::internal::wasm::WasmModuleBuilder::NumTags () [inline]
Definition at line 450 of file wasm-module-builder.h.
{ return static_cast<int>(tags_.size()); }
NumTypes()
int v8::internal::wasm::WasmModuleBuilder::NumTypes () [inline]
Definition at line 452 of file wasm-module-builder.h.
{ return static_cast<int>(types_.size()); }
operator=()
WasmModuleBuilder& v8::internal::wasm::WasmModuleBuilder::operator= (const WasmModuleBuilder &) [delete]
SetIndirectFunction()
void v8::internal::wasm::WasmModuleBuilder::SetIndirectFunction (uint32_t table_index, uint32_t index_in_table, uint32_t direct_function_index, WasmElemSegment::FunctionIndexingMode indexing_mode)
Definition at line 596 of file wasm-module-builder.cc.
                                                       {
  WasmElemSegment segment(zone_, kWasmFuncRef, table_index,
                          WasmInitExpr(static_cast<int>(index_in_table)));
  segment.indexing_mode = indexing_mode;
  segment.entries.emplace_back(WasmElemSegment::Entry::kRefFuncEntry,
                               direct_function_index);
  AddElementSegment(std::move(segment));
}
References AddElementSegment(), v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::entries, v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::indexing_mode, v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::Entry::kRefFuncEntry, v8::internal::wasm::kWasmFuncRef, and zone_.
Referenced by v8::internal::wasm::AsmJsParser::ValidateFunctionTable().
StartRecursiveTypeGroup()
void v8::internal::wasm::WasmModuleBuilder::StartRecursiveTypeGroup () [inline]
Definition at line 384 of file wasm-module-builder.h.
                                 {
    DCHECK_EQ(current_recursive_group_start_, -1);
    current_recursive_group_start_ = static_cast<int>(types_.size());
  }
References DCHECK_EQ.
WriteAsmJsOffsetTable()
void v8::internal::wasm::WasmModuleBuilder::WriteAsmJsOffsetTable (ZoneBuffer * buffer) const
Definition at line 1046 of file wasm-module-builder.cc.
                                                                      {
  // == Emit asm.js offset table ===============================================
  buffer->write_size(functions_.size());
  // Emit the offset table per function.
  for (auto* function : functions_) {
    function->WriteAsmWasmOffsetTable(buffer);
  }
}
References functions_, and v8::internal::wasm::ZoneBuffer::write_size().
Referenced by v8::internal::AsmJsCompilationJob::ExecuteJobImpl().
WriteTo()
void v8::internal::wasm::WasmModuleBuilder::WriteTo (ZoneBuffer * buffer) const
Definition at line 664 of file wasm-module-builder.cc.
                                                        {
  // == Emit magic =============================================================
  buffer->write_u32(kWasmMagic);
  buffer->write_u32(kWasmVersion);
  // == Emit types =============================================================
  if (!types_.empty()) {
    size_t start = EmitSection(kTypeSectionCode, buffer);
    // Every recursion group occupies one type entry.
    size_t type_count = types_.size() + recursive_groups_.size();
    // Types inside recursion groups occupy no additional type entry.
    for (auto [first_index, size] : recursive_groups_) {
      type_count -= size;
    }
    buffer->write_size(type_count);
    const RecGroup* next_rec_group =
        recursive_groups_.empty() ? nullptr : recursive_groups_.data();
    for (uint32_t i = 0; i < types_.size(); i++) {
      // Note: while loop, because recgroups can be empty.
      while (next_rec_group && i == next_rec_group->start_index) {
        buffer->write_u8(kWasmRecursiveTypeGroupCode);
        buffer->write_u32v(next_rec_group->size);
        next_rec_group = next_rec_group == &recursive_groups_.back()
                             ? nullptr
                             : next_rec_group + 1;
      }
      const TypeDefinition& type = types_[i];
      if (type.supertype.valid()) {
        buffer->write_u8(type.is_final ? kWasmSubtypeFinalCode
                                       : kWasmSubtypeCode);
        buffer->write_u8(1);
        buffer->write_u32v(type.supertype);
      } else if (!type.is_final) {
        buffer->write_u8(kWasmSubtypeCode);
        buffer->write_u8(0);
      }
      switch (type.kind) {
        case TypeDefinition::kFunction: {
          const FunctionSig* sig = type.function_sig;
          buffer->write_u8(kWasmFunctionTypeCode);
          buffer->write_size(sig->parameter_count());
          for (auto param : sig->parameters()) {
            WriteValueType(buffer, param);
          }
          buffer->write_size(sig->return_count());
          for (auto ret : sig->returns()) {
            WriteValueType(buffer, ret);
          }
          break;
        }
        case TypeDefinition::kStruct: {
          const StructType* struct_type = type.struct_type;
          buffer->write_u8(kWasmStructTypeCode);
          buffer->write_size(struct_type->field_count());
          for (uint32_t j = 0; j < struct_type->field_count(); j++) {
            WriteValueType(buffer, struct_type->field(j));
            buffer->write_u8(struct_type->mutability(j) ? 1 : 0);
          }
          break;
        }
        case TypeDefinition::kArray: {
          const ArrayType* array_type = type.array_type;
          buffer->write_u8(kWasmArrayTypeCode);
          WriteValueType(buffer, array_type->element_type());
          buffer->write_u8(array_type->mutability() ? 1 : 0);
          break;
        }
        case TypeDefinition::kCont: {
          const ContType* cont_type = type.cont_type;
          buffer->write_u8(kWasmContTypeCode);
          buffer->write_u32v(cont_type->contfun_typeindex());
          break;
        }
      }
    }
    // Handle empty recursion groups defined after all types.
    while (next_rec_group) {
      DCHECK_EQ(types_.size(), next_rec_group->start_index);
      DCHECK_EQ(0, next_rec_group->size);
      buffer->write_u8(kWasmRecursiveTypeGroupCode);
      buffer->write_u32v(0);
      if (next_rec_group == &recursive_groups_.back()) break;
      ++next_rec_group;
    }
    FixupSection(buffer, start);
  }
  // == Emit imports ===========================================================
  if (global_imports_.size() + function_imports_.size() > 0) {
    size_t start = EmitSection(kImportSectionCode, buffer);
    buffer->write_size(global_imports_.size() + function_imports_.size());
    for (auto import : global_imports_) {
      buffer->write_string(import.module); // module name
      buffer->write_string(import.name); // field name
      buffer->write_u8(kExternalGlobal);
      buffer->write_u8(import.type_code);
      buffer->write_u8(import.mutability ? 1 : 0);
    }
    for (auto import : function_imports_) {
      buffer->write_string(import.module); // module name
      buffer->write_string(import.name); // field name
      buffer->write_u8(kExternalFunction);
      buffer->write_u32v(import.sig_index);
    }
    FixupSection(buffer, start);
  }
  // == Emit function signatures ===============================================
  uint32_t num_function_names = 0;
  if (!functions_.empty()) {
    size_t start = EmitSection(kFunctionSectionCode, buffer);
    buffer->write_size(functions_.size());
    for (auto* function : functions_) {
      function->WriteSignature(buffer);
      if (!function->name_.empty()) ++num_function_names;
    }
    FixupSection(buffer, start);
  }
  // == Emit tables ============================================================
  if (!tables_.empty()) {
    size_t start = EmitSection(kTableSectionCode, buffer);
    buffer->write_size(tables_.size());
    for (const WasmTable& table : tables_) {
      if (table.init) {
        buffer->write_u8(0x40); // table-with-initializer
        buffer->write_u8(0x00); // reserved byte
      }
      WriteValueType(buffer, table.type);
      uint8_t limits_byte = (table.is_table64() ? 4 : 0) |
                            (table.is_shared ? 2 : 0) |
                            (table.has_maximum ? 1 : 0);
      buffer->write_u8(limits_byte);
      auto WriteValToBuffer = [&](uint32_t val) {
        table.is_table64() ? buffer->write_u64v(val) : buffer->write_u32v(val);
      };
      WriteValToBuffer(table.min_size);
      if (table.has_maximum) {
        WriteValToBuffer(table.max_size);
      }
      if (table.init) {
        WriteInitializerExpression(buffer, *table.init);
      }
    }
    FixupSection(buffer, start);
  }
  // == Emit memory declaration ================================================
  if (!memories_.empty()) {
    size_t start = EmitSection(kMemorySectionCode, buffer);
    buffer->write_size(memories_.size());
    for (const WasmMemory& memory : memories_) {
      uint8_t limits_byte = (memory.is_memory64() ? 4 : 0) |
                            (memory.is_shared ? 2 : 0) |
                            (memory.has_max_pages ? 1 : 0);
      buffer->write_u8(limits_byte);
      auto WriteValToBuffer = [&](uint32_t val) {
        memory.is_memory64() ? buffer->write_u64v(val)
                             : buffer->write_u32v(val);
      };
      WriteValToBuffer(memory.min_pages);
      if (memory.has_max_pages) {
        WriteValToBuffer(memory.max_pages);
      }
    }
    FixupSection(buffer, start);
  }
  // == Emit event section =====================================================
  if (!tags_.empty()) {
    size_t start = EmitSection(kTagSectionCode, buffer);
    buffer->write_size(tags_.size());
    for (ModuleTypeIndex type : tags_) {
      buffer->write_u32v(kExceptionAttribute);
      buffer->write_u32v(type);
    }
    FixupSection(buffer, start);
  }
  // == Emit globals ===========================================================
  if (!globals_.empty()) {
    size_t start = EmitSection(kGlobalSectionCode, buffer);
    buffer->write_size(globals_.size());
    for (const WasmGlobal& global : globals_) {
      WriteValueType(buffer, global.type);
      buffer->write_u8(global.mutability ? 1 : 0);
      WriteInitializerExpression(buffer, global.init);
    }
    FixupSection(buffer, start);
  }
  // == Emit exports ===========================================================
  if (!exports_.empty()) {
    size_t start = EmitSection(kExportSectionCode, buffer);
    buffer->write_size(exports_.size());
    for (auto ex : exports_) {
      buffer->write_string(ex.name);
      buffer->write_u8(ex.kind);
      switch (ex.kind) {
        case kExternalFunction:
          buffer->write_size(ex.index + function_imports_.size());
          break;
        case kExternalGlobal:
          buffer->write_size(ex.index + global_imports_.size());
          break;
        case kExternalMemory:
        case kExternalTable:
          // The WasmModuleBuilder doesn't support importing tables or memories
          // yet, so there is no index offset to add.
          buffer->write_size(ex.index);
          break;
        case kExternalTag:
          UNREACHABLE();
      }
    }
    FixupSection(buffer, start);
  }
  // == Emit start function index ==============================================
  if (start_function_index_ >= 0) {
    size_t start = EmitSection(kStartSectionCode, buffer);
    buffer->write_size(start_function_index_ + function_imports_.size());
    FixupSection(buffer, start);
  }
  // == Emit element segments ==================================================
  if (!element_segments_.empty()) {
    size_t start = EmitSection(kElementSectionCode, buffer);
    buffer->write_size(element_segments_.size());
    for (const WasmElemSegment& segment : element_segments_) {
      bool is_active = segment.status == WasmElemSegment::kStatusActive;
      // We pick the most general syntax, i.e., we always explicitly emit the
      // table index and the type, and use the expressions-as-elements syntax.
      // The initial byte is one of 0x05, 0x06, and 0x07.
      uint8_t kind_mask =
          segment.status == WasmElemSegment::kStatusActive
              ? 0b10
              : segment.status == WasmElemSegment::kStatusDeclarative ? 0b11
                                                                      : 0b01;
      uint8_t expressions_as_elements_mask = 0b100;
      buffer->write_u8(kind_mask | expressions_as_elements_mask);
      if (is_active) {
        buffer->write_u32v(segment.table_index);
        WriteInitializerExpression(buffer, segment.offset);
      }
      WriteValueType(buffer, segment.type);
      buffer->write_size(segment.entries.size());
      for (const WasmElemSegment::Entry entry : segment.entries) {
        uint8_t opcode =
            entry.kind == WasmElemSegment::Entry::kGlobalGetEntry
                ? kExprGlobalGet
                : entry.kind == WasmElemSegment::Entry::kRefFuncEntry
                      ? kExprRefFunc
                      : kExprRefNull;
        bool needs_function_offset =
            segment.indexing_mode ==
                WasmElemSegment::kRelativeToDeclaredFunctions &&
            entry.kind == WasmElemSegment::Entry::kRefFuncEntry;
        uint32_t index =
            entry.index + (needs_function_offset
                               ? static_cast<uint32_t>(function_imports_.size())
                               : 0);
        buffer->write_u8(opcode);
        buffer->write_u32v(index);
        buffer->write_u8(kExprEnd);
      }
    }
    FixupSection(buffer, start);
  }
  // == Emit data segment count section ========================================
  if (std::any_of(
          data_segments_.begin(), data_segments_.end(),
          [](const WasmDataSegment& segment) { return !segment.is_active; })) {
    buffer->write_u8(kDataCountSectionCode);
    buffer->write_u32v(1); // section length
    buffer->write_u32v(static_cast<uint32_t>(data_segments_.size()));
  }
  // == Emit compilation hints section =========================================
  bool emit_compilation_hints = false;
  for (auto* fn : functions_) {
    if (fn->hint_ != kNoCompilationHint) {
      emit_compilation_hints = true;
      break;
    }
  }
  if (emit_compilation_hints) {
    // Emit the section code.
    buffer->write_u8(kUnknownSectionCode);
    // Emit a placeholder for section length.
    size_t start = buffer->reserve_u32v();
    // Emit custom section name.
    buffer->write_string(base::CStrVector("compilationHints"));
    // Emit hint count.
    buffer->write_size(functions_.size());
    // Emit hint bytes.
    for (auto* fn : functions_) {
      uint8_t hint_byte =
          fn->hint_ != kNoCompilationHint ? fn->hint_ : kDefaultCompilationHint;
      buffer->write_u8(hint_byte);
    }
    FixupSection(buffer, start);
  }
  // == Emit code ==============================================================
  if (!functions_.empty()) {
    size_t start = EmitSection(kCodeSectionCode, buffer);
    buffer->write_size(functions_.size());
    for (auto* function : functions_) {
      function->WriteBody(buffer);
    }
    FixupSection(buffer, start);
  }
  // == Emit data segments =====================================================
  if (!data_segments_.empty()) {
    size_t start = EmitSection(kDataSectionCode, buffer);
    buffer->write_size(data_segments_.size());
    for (auto segment : data_segments_) {
      if (segment.is_active) {
        buffer->write_u8(0); // linear memory segment
        buffer->write_u8(kExprI32Const); // constant expression for dest
        buffer->write_u32v(segment.dest);
        buffer->write_u8(kExprEnd);
      } else {
        buffer->write_u8(kPassive);
      }
      buffer->write_u32v(static_cast<uint32_t>(segment.data.size()));
      buffer->write(segment.data.data(), segment.data.size());
    }
    FixupSection(buffer, start);
  }
  // == Emit names =============================================================
  if (num_function_names > 0 || !function_imports_.empty()) {
    // Emit the section code.
    buffer->write_u8(kUnknownSectionCode);
    // Emit a placeholder for the length.
    size_t start = buffer->reserve_u32v();
    // Emit the section string.
    buffer->write_string(base::CStrVector("name"));
    // Emit a subsection for the function names.
    buffer->write_u8(NameSectionKindCode::kFunctionCode);
    // Emit a placeholder for the subsection length.
    size_t functions_start = buffer->reserve_u32v();
    // Emit the function names.
    // Imports are always named.
    uint32_t num_imports = static_cast<uint32_t>(function_imports_.size());
    buffer->write_size(num_imports + num_function_names);
    uint32_t function_index = 0;
    for (; function_index < num_imports; ++function_index) {
      const WasmFunctionImport* import = &function_imports_[function_index];
      DCHECK(!import->name.empty());
      buffer->write_u32v(function_index);
      buffer->write_string(import->name);
    }
    if (num_function_names > 0) {
      for (auto* function : functions_) {
        DCHECK_EQ(function_index,
                  function->func_index() + function_imports_.size());
        if (!function->name_.empty()) {
          buffer->write_u32v(function_index);
          buffer->write_string(function->name_);
        }
        ++function_index;
      }
    }
    FixupSection(buffer, functions_start);
    FixupSection(buffer, start);
  }
}
References v8::base::any_of(), v8::internal::wasm::ContType::contfun_typeindex(), v8::base::CStrVector(), v8::internal::wasm::WasmModuleBuilder::WasmDataSegment::data, v8::internal::ZoneVector< T >::data(), data_segments_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::WasmModuleBuilder::WasmDataSegment::dest, element_segments_, v8::internal::wasm::ArrayType::element_type(), v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::EmitSection(), exports_, v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::FixupSection(), function_imports_, functions_, global_imports_, globals_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::Entry::index, v8::internal::wasm::WasmModuleBuilder::WasmDataSegment::is_active, v8::internal::wasm::TypeDefinition::kArray, v8::internal::wasm::kCodeSectionCode, v8::internal::wasm::TypeDefinition::kCont, v8::internal::wasm::kDataCountSectionCode, v8::internal::wasm::kDataSectionCode, v8::internal::wasm::kDefaultCompilationHint, v8::internal::wasm::kElementSectionCode, v8::internal::wasm::kExceptionAttribute, v8::internal::wasm::kExportSectionCode, v8::internal::wasm::kExternalFunction, v8::internal::wasm::kExternalGlobal, v8::internal::wasm::kExternalMemory, v8::internal::wasm::kExternalTable, v8::internal::wasm::kExternalTag, v8::internal::wasm::TypeDefinition::kFunction, v8::internal::wasm::kFunctionCode, v8::internal::wasm::kFunctionSectionCode, v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::Entry::kGlobalGetEntry, v8::internal::wasm::kGlobalSectionCode, v8::internal::wasm::kImportSectionCode, v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::Entry::kind, v8::internal::wasm::kMemorySectionCode, v8::internal::wasm::kNoCompilationHint, v8::internal::wasm::kPassive, v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::Entry::kRefFuncEntry, v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::kRelativeToDeclaredFunctions, v8::internal::wasm::kStartSectionCode, v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::kStatusActive, v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::kStatusDeclarative, v8::internal::wasm::TypeDefinition::kStruct, v8::internal::wasm::kTableSectionCode, v8::internal::wasm::kTagSectionCode, v8::internal::wasm::kTypeSectionCode, v8::internal::wasm::kUnknownSectionCode, v8::internal::wasm::kWasmArrayTypeCode, v8::internal::wasm::kWasmContTypeCode, v8::internal::wasm::kWasmFunctionTypeCode, v8::internal::wasm::kWasmMagic, v8::internal::wasm::kWasmRecursiveTypeGroupCode, v8::internal::wasm::kWasmStructTypeCode, v8::internal::wasm::kWasmSubtypeCode, v8::internal::wasm::kWasmSubtypeFinalCode, v8::internal::wasm::kWasmVersion, memories_, v8::internal::wasm::ArrayTypeBase::mutability(), v8::internal::wasm::StructTypeBase::mutability(), v8::internal::wasm::name(), nullptr, v8::internal::wasm::ZoneBuffer::offset(), recursive_groups_, v8::internal::wasm::ZoneBuffer::reserve_u32v(), v8::internal::sig, v8::internal::ZoneVector< T >::size(), size(), v8::internal::wasm::WasmModuleBuilder::RecGroup::size, start_function_index_, v8::internal::wasm::WasmModuleBuilder::RecGroup::start_index, tables_, tags_, v8::internal::tracing::type, types_, v8::internal::UNREACHABLE(), v8::internal::wasm::ZoneBuffer::write(), v8::internal::wasm::ZoneBuffer::write_size(), v8::internal::wasm::ZoneBuffer::write_string(), v8::internal::wasm::ZoneBuffer::write_u32(), v8::internal::wasm::ZoneBuffer::write_u32v(), v8::internal::wasm::ZoneBuffer::write_u64v(), v8::internal::wasm::ZoneBuffer::write_u8(), v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpression(), and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteValueType().
Referenced by v8::internal::AsmJsCompilationJob::ExecuteJobImpl(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec().
zone()
Zone* v8::internal::wasm::WasmModuleBuilder::zone () [inline]
Definition at line 406 of file wasm-module-builder.h.
{ return zone_; }
Referenced by AddDataSegment(), AddPassiveDataSegment(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_set(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GeneratePassiveDataSegment(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateRefTypeElementSegment(), v8::internal::wasm::fuzzing::GenerateWasmModuleForDeopt(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_helper(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_set().
Friends And Related Function Documentation
WasmFunctionBuilder
friend class WasmFunctionBuilder [friend]
Definition at line 536 of file wasm-module-builder.h.
Member Data Documentation
current_recursive_group_start_
int v8::internal::wasm::WasmModuleBuilder::current_recursive_group_start_ [private]
Definition at line 550 of file wasm-module-builder.h.
data_segments_
ZoneVector<WasmDataSegment> v8::internal::wasm::WasmModuleBuilder::data_segments_ [private]
Definition at line 545 of file wasm-module-builder.h.
Referenced by AddDataSegment(), AddPassiveDataSegment(), and WriteTo().
element_segments_
ZoneVector<WasmElemSegment> v8::internal::wasm::WasmModuleBuilder::element_segments_ [private]
Definition at line 546 of file wasm-module-builder.h.
Referenced by AddElementSegment(), and WriteTo().
exports_
ZoneVector<WasmExport> v8::internal::wasm::WasmModuleBuilder::exports_ [private]
Definition at line 541 of file wasm-module-builder.h.
Referenced by AddExport(), ExportImportedFunction(), and WriteTo().
function_imports_
ZoneVector<WasmFunctionImport> v8::internal::wasm::WasmModuleBuilder::function_imports_ [private]
Definition at line 539 of file wasm-module-builder.h.
Referenced by AddImport(), ExportImportedFunction(), v8::internal::wasm::WasmFunctionBuilder::WriteBody(), and WriteTo().
functions_
ZoneVector<WasmFunctionBuilder*> v8::internal::wasm::WasmModuleBuilder::functions_ [private]
Definition at line 542 of file wasm-module-builder.h.
Referenced by AddFunction(), WriteAsmJsOffsetTable(), and WriteTo().
global_imports_
ZoneVector<WasmGlobalImport> v8::internal::wasm::WasmModuleBuilder::global_imports_ [private]
Definition at line 540 of file wasm-module-builder.h.
Referenced by AddGlobalImport(), and WriteTo().
globals_
ZoneVector<WasmGlobal> v8::internal::wasm::WasmModuleBuilder::globals_ [private]
Definition at line 547 of file wasm-module-builder.h.
Referenced by AddGlobal(), and WriteTo().
memories_
ZoneVector<WasmMemory> v8::internal::wasm::WasmModuleBuilder::memories_ [private]
Definition at line 544 of file wasm-module-builder.h.
Referenced by AddMemory(), AddMemory64(), and WriteTo().
recursive_groups_
ZoneVector<RecGroup> v8::internal::wasm::WasmModuleBuilder::recursive_groups_ [private]
Definition at line 555 of file wasm-module-builder.h.
Referenced by WriteTo().
signature_map_
ZoneUnorderedMap<FunctionSig, ModuleTypeIndex> v8::internal::wasm::WasmModuleBuilder::signature_map_ [private]
Definition at line 549 of file wasm-module-builder.h.
Referenced by AddSignature(), and ForceAddSignature().
start_function_index_
int v8::internal::wasm::WasmModuleBuilder::start_function_index_ [private]
Definition at line 556 of file wasm-module-builder.h.
Referenced by MarkStartFunction(), and WriteTo().
tables_
ZoneVector<WasmTable> v8::internal::wasm::WasmModuleBuilder::tables_ [private]
Definition at line 543 of file wasm-module-builder.h.
Referenced by AddTable(), IncreaseTableMinSize(), and WriteTo().
tags_
ZoneVector<ModuleTypeIndex> v8::internal::wasm::WasmModuleBuilder::tags_ [private]
Definition at line 548 of file wasm-module-builder.h.
Referenced by AddTag(), and WriteTo().
types_
ZoneVector<TypeDefinition> v8::internal::wasm::WasmModuleBuilder::types_ [private]
Definition at line 538 of file wasm-module-builder.h.
Referenced by AddArrayType(), AddStructType(), ForceAddSignature(), v8::internal::wasm::WasmFunctionBuilder::SetSignature(), v8::internal::wasm::WasmFunctionBuilder::signature(), and WriteTo().
zone_
Zone* v8::internal::wasm::WasmModuleBuilder::zone_ [private]
Definition at line 537 of file wasm-module-builder.h.
Referenced by AddFunction(), and SetIndirectFunction().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-module-builder.h
/mnt/V8SourceCode/src/wasm/wasm-module-builder.cc