v8::internal::interpreter::LoopBuilder Class Reference
#include <control-flow-builders.h>
Public Member Functions
LoopBuilder (BytecodeArrayBuilder *builder, BlockCoverageBuilder *block_coverage_builder, AstNode *node, FeedbackVectorSpec *feedback_vector_spec)
~LoopBuilder () override
void LoopHeader ()
void LoopBody ()
void JumpToHeader (int loop_depth, LoopBuilder *const parent_loop)
void BindContinueTarget ()
void Continue ()
void ContinueIfUndefined ()
Private Member Functions
void JumpToLoopEnd ()
void BindLoopEnd ()
Private Attributes
BytecodeLoopHeader loop_header_
BytecodeLabels continue_labels_
BytecodeLabels end_labels_
int block_coverage_body_slot_
int source_position_
FeedbackVectorSpec *const feedback_vector_spec_
Additional Inherited Members
Detailed Description
Definition at line 97 of file control-flow-builders.h.
Constructor & Destructor Documentation
LoopBuilder()
v8::internal::interpreter::LoopBuilder::LoopBuilder (BytecodeArrayBuilder * builder, BlockCoverageBuilder * block_coverage_builder, AstNode * node, FeedbackVectorSpec * feedback_vector_spec) [inline]
Definition at line 99 of file control-flow-builders.h.
      : BreakableControlFlowBuilder(builder, block_coverage_builder, node),
        continue_labels_(builder->zone()),
        end_labels_(builder->zone()),
        feedback_vector_spec_(feedback_vector_spec) {
    if (block_coverage_builder_ != nullptr) {
      block_coverage_body_slot_ =
          block_coverage_builder_->AllocateBlockCoverageSlot(
              node, SourceRangeKind::kBody);
    }
    source_position_ = node ? node->position() : kNoSourcePosition;
  }
References v8::internal::kBody, v8::internal::kNoSourcePosition, and v8::internal::AstNode::position().
 LoopBuilder()
v8::internal::interpreter::LoopBuilder::~LoopBuilder () [override]
Definition at line 50 of file control-flow-builders.cc.
                          {
  DCHECK(continue_labels_.empty() || continue_labels_.is_bound());
  DCHECK(end_labels_.empty() || end_labels_.is_bound());
}
References continue_labels_, v8::internal::DCHECK(), v8::internal::interpreter::BytecodeLabels::empty(), end_labels_, and v8::internal::interpreter::BytecodeLabels::is_bound().
Member Function Documentation
BindContinueTarget()
void v8::internal::interpreter::LoopBuilder::BindContinueTarget ()
Definition at line 95 of file control-flow-builders.cc.
{ continue_labels_.Bind(builder()); }
References v8::internal::interpreter::BytecodeLabels::Bind(), v8::internal::interpreter::ControlFlowBuilder::builder(), and continue_labels_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDisposeScope(), v8::internal::interpreter::BytecodeGenerator::BuildFillArrayWithIterator(), and v8::internal::interpreter::BytecodeGenerator::VisitIterationBody().
BindLoopEnd()
void v8::internal::interpreter::LoopBuilder::BindLoopEnd () [private]
Definition at line 97 of file control-flow-builders.cc.
{ end_labels_.Bind(builder()); }
References v8::internal::interpreter::BytecodeLabels::Bind(), v8::internal::interpreter::ControlFlowBuilder::builder(), and end_labels_.
Referenced by JumpToHeader().
Continue()
void v8::internal::interpreter::LoopBuilder::Continue () [inline]
Definition at line 123 of file control-flow-builders.h.
{ EmitJump(&continue_labels_); }
Referenced by v8::internal::interpreter::BytecodeGenerator::ControlScopeForIteration::Execute().
ContinueIfUndefined()
void v8::internal::interpreter::LoopBuilder::ContinueIfUndefined () [inline]
Definition at line 124 of file control-flow-builders.h.
{ EmitJumpIfUndefined(&continue_labels_); }
JumpToHeader()
void v8::internal::interpreter::LoopBuilder::JumpToHeader (int loop_depth, LoopBuilder *const parent_loop)
Definition at line 71 of file control-flow-builders.cc.
                                                                             {
  BindLoopEnd();
  if (parent_loop &&
      loop_header_.offset() == parent_loop->loop_header_.offset()) {
    // TurboFan can't cope with multiple loops that have the same loop header
    // bytecode offset. If we have an inner loop with the same header offset
    // than its parent loop, we do not create a JumpLoop bytecode. Instead, we
    // Jump to our parent's JumpToHeader which in turn can be a JumpLoop or, iff
    // they are a nested inner loop too, a Jump to its parent's JumpToHeader.
    parent_loop->JumpToLoopEnd();
  } else {
    // Pass the proper loop depth to the backwards branch for triggering OSR.
    // For purposes of OSR, the loop depth is capped at `kMaxOsrUrgency - 1`.
    // Once that urgency is reached, all loops become OSR candidates.
    //
    // The loop must have closed form, i.e. all loop elements are within the
    // loop, the loop header precedes the body and next elements in the loop.
    int slot_index = feedback_vector_spec_->AddJumpLoopSlot().ToInt();
    builder()->JumpLoop(
        &loop_header_, std::min(loop_depth, FeedbackVector::kMaxOsrUrgency - 1),
        source_position_, slot_index);
  }
}
References v8::internal::FeedbackVectorSpec::AddJumpLoopSlot(), BindLoopEnd(), v8::internal::interpreter::ControlFlowBuilder::builder(), feedback_vector_spec_, v8::internal::interpreter::BytecodeArrayBuilder::JumpLoop(), JumpToLoopEnd(), v8::internal::FeedbackVector::kMaxOsrUrgency, loop_header_, v8::internal::interpreter::BytecodeLoopHeader::offset(), source_position_, and v8::internal::FeedbackSlot::ToInt().
JumpToLoopEnd()
void v8::internal::interpreter::LoopBuilder::JumpToLoopEnd () [inline], [private]
Definition at line 130 of file control-flow-builders.h.
{ EmitJump(&end_labels_); }
Referenced by JumpToHeader().
LoopBody()
void v8::internal::interpreter::LoopBuilder::LoopBody ()
Definition at line 65 of file control-flow-builders.cc.
                           {
  if (block_coverage_builder_ != nullptr) {
    block_coverage_builder_->IncrementBlockCounter(block_coverage_body_slot_);
  }
}
References block_coverage_body_slot_, v8::internal::interpreter::BreakableControlFlowBuilder::block_coverage_builder_, and v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildFillArrayWithIterator(), and v8::internal::interpreter::BytecodeGenerator::VisitIterationBody().
LoopHeader()
void v8::internal::interpreter::LoopBuilder::LoopHeader ()
Definition at line 55 of file control-flow-builders.cc.
                             {
  // Jumps from before the loop header into the loop violate ordering
  // requirements of bytecode basic blocks. The only entry into a loop
  // must be the loop header. Surely breaks is okay? Not if nested
  // and misplaced between the headers.
  DCHECK(break_labels_.empty() && continue_labels_.empty() &&
         end_labels_.empty());
  builder()->Bind(&loop_header_);
}
References v8::internal::interpreter::BytecodeArrayBuilder::Bind(), v8::internal::interpreter::BreakableControlFlowBuilder::break_labels_, v8::internal::interpreter::ControlFlowBuilder::builder(), continue_labels_, v8::internal::DCHECK(), v8::internal::interpreter::BytecodeLabels::empty(), end_labels_, and loop_header_.
Member Data Documentation
block_coverage_body_slot_
int v8::internal::interpreter::LoopBuilder::block_coverage_body_slot_ [private]
Definition at line 145 of file control-flow-builders.h.
Referenced by LoopBody().
continue_labels_
BytecodeLabels v8::internal::interpreter::LoopBuilder::continue_labels_ [private]
Definition at line 137 of file control-flow-builders.h.
Referenced by BindContinueTarget(), LoopHeader(), and ~LoopBuilder().
end_labels_
BytecodeLabels v8::internal::interpreter::LoopBuilder::end_labels_ [private]
Definition at line 143 of file control-flow-builders.h.
Referenced by BindLoopEnd(), LoopHeader(), and ~LoopBuilder().
feedback_vector_spec_
FeedbackVectorSpec* const v8::internal::interpreter::LoopBuilder::feedback_vector_spec_ [private]
Definition at line 147 of file control-flow-builders.h.
Referenced by JumpToHeader().
loop_header_
BytecodeLoopHeader v8::internal::interpreter::LoopBuilder::loop_header_ [private]
Definition at line 133 of file control-flow-builders.h.
Referenced by JumpToHeader(), and LoopHeader().
source_position_
int v8::internal::interpreter::LoopBuilder::source_position_ [private]
Definition at line 146 of file control-flow-builders.h.
Referenced by JumpToHeader().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/control-flow-builders.h
/mnt/V8SourceCode/src/interpreter/control-flow-builders.cc