v8::base::AddressSpaceReservation Class Reference
#include <platform.h>
Public Types
using Address = uintptr_t
Public Member Functions
void * base () const
size_t size () const
bool Contains (void *region_addr, size_t region_size) const
V8_WARN_UNUSED_RESULT bool Allocate (void *address, size_t size, OS::MemoryPermission access)
V8_WARN_UNUSED_RESULT bool Free (void *address, size_t size)
V8_WARN_UNUSED_RESULT bool AllocateShared (void *address, size_t size, OS::MemoryPermission access, PlatformSharedMemoryHandle handle, uint64_t offset)
V8_WARN_UNUSED_RESULT bool FreeShared (void *address, size_t size)
V8_WARN_UNUSED_RESULT bool SetPermissions (void *address, size_t size, OS::MemoryPermission access)
V8_WARN_UNUSED_RESULT bool RecommitPages (void *address, size_t size, OS::MemoryPermission access)
V8_WARN_UNUSED_RESULT bool DiscardSystemPages (void *address, size_t size)
V8_WARN_UNUSED_RESULT bool DecommitPages (void *address, size_t size)
V8_WARN_UNUSED_RESULT std::optional< AddressSpaceReservation > CreateSubReservation (void *address, size_t size, OS::MemoryPermission max_permission)
Static Public Member Functions
static V8_WARN_UNUSED_RESULT bool FreeSubReservation (AddressSpaceReservation reservation)
Private Member Functions
AddressSpaceReservation (void *base, size_t size)
Private Attributes
void * base_ = nullptr
size_t size_ = 0
Friends
class OS
Detailed Description
Definition at line 457 of file platform.h.
Member Typedef Documentation
Address
using v8::base::AddressSpaceReservation::Address = uintptr_t
Definition at line 459 of file platform.h.
Constructor & Destructor Documentation
AddressSpaceReservation()
v8::base::AddressSpaceReservation::AddressSpaceReservation (void * base, size_t size) [inline], [private]
Definition at line 518 of file platform.h.
: base_(base), size_(size) {}
Referenced by CreateSubReservation().
Member Function Documentation
Allocate()
bool v8::base::AddressSpaceReservation::Allocate (void * address, size_t size, OS::MemoryPermission access)
Definition at line 440 of file platform-fuchsia.cc.
                                                                  {
  DCHECK(Contains(address, size));
  void* allocation = CreateAndMapVmo(
      *zx::unowned_vmar(vmar_), base(), OS::AllocatePageSize(), address,
      PlacementMode::kFixed, size, OS::AllocatePageSize(), access);
  DCHECK(!allocation || allocation == address);
  return allocation != nullptr;
}
References v8::base::OS::AllocatePageSize(), base(), Contains(), v8::base::anonymous_namespace{platform-fuchsia.cc}::CreateAndMapVmo(), DCHECK, and size().
Referenced by v8::base::VirtualAddressSubspace::AllocatePages().
AllocateShared()
bool v8::base::AddressSpaceReservation::AllocateShared (void * address, size_t size, OS::MemoryPermission access, PlatformSharedMemoryHandle handle, uint64_t offset)
Definition at line 210 of file platform-darwin.cc.
                                                              {
  DCHECK(Contains(address, size));
  vm_prot_t prot = GetVMProtFromMemoryPermission(access);
  mach_vm_address_t addr = reinterpret_cast<mach_vm_address_t>(address);
  mach_port_t shared_mem_port = MachMemoryEntryFromSharedMemoryHandle(handle);
  kern_return_t kr =
      mach_vm_map_wrapper(&addr, size, VM_FLAGS_FIXED | VM_FLAGS_OVERWRITE,
                          shared_mem_port, offset, prot);
  return kr == KERN_SUCCESS;
}
References Contains(), DCHECK, v8::base::anonymous_namespace{platform-darwin.cc}::GetVMProtFromMemoryPermission(), v8::internal::handle(), v8::base::anonymous_namespace{platform-darwin.cc}::mach_vm_map_wrapper(), and size().
Referenced by v8::base::VirtualAddressSubspace::AllocateSharedPages().
base()
void* v8::base::AddressSpaceReservation::base () const [inline]
Definition at line 461 of file platform.h.
{ return base_; }
Referenced by Allocate(), CreateSubReservation(), and v8::base::VirtualAddressSubspace::FreeSubspace().
Contains()
bool v8::base::AddressSpaceReservation::Contains (void * region_addr, size_t region_size) const [inline]
Definition at line 464 of file platform.h.
                                                             {
    Address base = reinterpret_cast<Address>(base_);
    Address region_base = reinterpret_cast<Address>(region_addr);
    return (region_base >= base) &&
           ((region_base + region_size) <= (base + size_));
  }
Referenced by Allocate(), AllocateShared(), CreateSubReservation(), DecommitPages(), DiscardSystemPages(), Free(), FreeShared(), and SetPermissions().
CreateSubReservation()
std::optional< AddressSpaceReservation > v8::base::AddressSpaceReservation::CreateSubReservation (void * address, size_t size, OS::MemoryPermission max_permission)
Definition at line 418 of file platform-fuchsia.cc.
                                                                   {
  DCHECK(Contains(address, size));
  zx::vmar child;
  zx_vaddr_t child_addr;
  zx_status_t status = CreateAddressSpaceReservationInternal(
      *zx::unowned_vmar(vmar_), base(), OS::AllocatePageSize(), address,
      PlacementMode::kFixed, size, OS::AllocatePageSize(), max_permission,
      &child, &child_addr);
  if (status != ZX_OK) return {};
  DCHECK_EQ(reinterpret_cast<void*>(child_addr), address);
  return AddressSpaceReservation(reinterpret_cast<void*>(child_addr), size,
                                 child.release());
}
References AddressSpaceReservation(), v8::base::OS::AllocatePageSize(), base(), Contains(), v8::base::anonymous_namespace{platform-fuchsia.cc}::CreateAddressSpaceReservationInternal(), DCHECK, DCHECK_EQ, size(), and v8::internal::status.
Referenced by v8::base::VirtualAddressSubspace::AllocateSubspace().
DecommitPages()
bool v8::base::AddressSpaceReservation::DecommitPages (void * address, size_t size)
Definition at line 491 of file platform-fuchsia.cc.
                                                                      {
  DCHECK(Contains(address, size));
  // See comment in OS::DecommitPages.
  return SetPermissions(address, size, OS::MemoryPermission::kNoAccess) &&
         DiscardSystemPages(address, size);
}
References Contains(), DCHECK, DiscardSystemPages(), v8::base::OS::kNoAccess, SetPermissions(), and size().
Referenced by v8::base::VirtualAddressSubspace::DecommitPages().
DiscardSystemPages()
bool v8::base::AddressSpaceReservation::DiscardSystemPages (void * address, size_t size)
Definition at line 485 of file platform-fuchsia.cc.
                                                                           {
  DCHECK(Contains(address, size));
  return DiscardSystemPagesInternal(*zx::unowned_vmar(vmar_),
                                    OS::CommitPageSize(), address, size);
}
References v8::base::OS::CommitPageSize(), Contains(), DCHECK, v8::base::anonymous_namespace{platform-fuchsia.cc}::DiscardSystemPagesInternal(), and size().
Referenced by DecommitPages(), and v8::base::VirtualAddressSubspace::DiscardSystemPages().
Free()
bool v8::base::AddressSpaceReservation::Free (void * address, size_t size)
Definition at line 450 of file platform-fuchsia.cc.
                                                             {
  DCHECK(Contains(address, size));
  return UnmapVmo(*zx::unowned_vmar(vmar_), OS::AllocatePageSize(), address,
                  size);
}
References v8::base::OS::AllocatePageSize(), Contains(), DCHECK, size(), and v8::base::anonymous_namespace{platform-fuchsia.cc}::UnmapVmo().
Referenced by v8::base::VirtualAddressSubspace::FreePages().
FreeShared()
bool v8::base::AddressSpaceReservation::FreeShared (void * address, size_t size)
Definition at line 467 of file platform-fuchsia.cc.
                                                                   {
  DCHECK(Contains(address, size));
  return UnmapVmo(*zx::unowned_vmar(vmar_), OS::AllocatePageSize(), address,
                  size);
}
References v8::base::OS::AllocatePageSize(), Contains(), DCHECK, size(), and v8::base::anonymous_namespace{platform-fuchsia.cc}::UnmapVmo().
Referenced by v8::base::VirtualAddressSubspace::FreeSharedPages().
FreeSubReservation()
bool v8::base::AddressSpaceReservation::FreeSubReservation (AddressSpaceReservation reservation) [static]
Definition at line 434 of file platform-fuchsia.cc.
                                         {
  OS::FreeAddressSpaceReservation(reservation);
  return true;
}
References v8::base::OS::FreeAddressSpaceReservation().
Referenced by v8::base::VirtualAddressSubspace::FreeSubspace().
RecommitPages()
bool v8::base::AddressSpaceReservation::RecommitPages (void * address, size_t size, OS::MemoryPermission access)
Definition at line 480 of file platform-fuchsia.cc.
                                                                       {
  return SetPermissions(address, size, access);
}
References SetPermissions(), and size().
Referenced by v8::base::VirtualAddressSubspace::RecommitPages().
SetPermissions()
bool v8::base::AddressSpaceReservation::SetPermissions (void * address, size_t size, OS::MemoryPermission access)
Definition at line 473 of file platform-fuchsia.cc.
                                                                        {
  DCHECK(Contains(address, size));
  return SetPermissionsInternal(*zx::unowned_vmar(vmar_), OS::CommitPageSize(),
                                address, size, access);
}
References v8::base::OS::CommitPageSize(), Contains(), DCHECK, v8::base::anonymous_namespace{platform-fuchsia.cc}::SetPermissionsInternal(), and size().
Referenced by DecommitPages(), RecommitPages(), and v8::base::VirtualAddressSubspace::SetPagePermissions().
size()
size_t v8::base::AddressSpaceReservation::size () const [inline]
Definition at line 462 of file platform.h.
{ return size_; }
Referenced by Allocate(), AllocateShared(), CreateSubReservation(), DecommitPages(), DiscardSystemPages(), Free(), FreeShared(), v8::base::VirtualAddressSubspace::FreeSubspace(), RecommitPages(), and SetPermissions().
Friends And Related Function Documentation
OS
friend class OS [friend]
Definition at line 512 of file platform.h.
Member Data Documentation
base_
void* v8::base::AddressSpaceReservation::base_ = nullptr [private]
Definition at line 521 of file platform.h.
size_
size_t v8::base::AddressSpaceReservation::size_ = 0 [private]
Definition at line 522 of file platform.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/platform.h
/mnt/V8SourceCode/src/base/platform/platform-darwin.cc
/mnt/V8SourceCode/src/base/platform/platform-fuchsia.cc
/mnt/V8SourceCode/src/base/platform/platform-posix.cc
/mnt/V8SourceCode/src/base/platform/platform-win32.cc
/mnt/V8SourceCode/src/base/platform/platform-zos.cc