v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocator Class Reference
Protected Member Functions
void * Allocate (size_t length) override
Allocate |length| bytes.
void * AllocateUninitialized (size_t length) override
Allocate |length| bytes.
void Free (void *data, size_t length) override
Free the memory block of size |length|, pointed to by |data|.
Private Member Functions
size_t Adjust (size_t length)
Additional Inherited Members
Detailed Description
Definition at line 211 of file d8.cc.
Member Function Documentation
Adjust()
size_t v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocator::Adjust (size_t length) [inline], [private]
Definition at line 226 of file d8.cc.
                               {
    const size_t kAllocationLimit = 10 * i::MB;
    return length > kAllocationLimit ? i::AllocatePageSize() : length;
  }
References v8::internal::AllocatePageSize(), v8::internal::length, and MB.
Allocate()
void* v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocator::Allocate (size_t length) [inline], [override], [protected], [virtual]
Allocate |length| bytes.
Return nullptr if allocation is not successful. Memory should be initialized to zeroes.
Reimplemented from v8::anonymous_namespace{d8.cc}::ArrayBufferAllocatorBase.
Reimplemented in v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocatiorWithLimit.
Definition at line 213 of file d8.cc.
                                         {
    return ArrayBufferAllocatorBase::Allocate(Adjust(length));
  }
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), and v8::internal::length.
AllocateUninitialized()
void* v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocator::AllocateUninitialized (size_t length) [inline], [override], [protected], [virtual]
Allocate |length| bytes.
Return nullptr if allocation is not successful. Memory does not have to be initialized.
Reimplemented from v8::anonymous_namespace{d8.cc}::ArrayBufferAllocatorBase.
Reimplemented in v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocatiorWithLimit.
Definition at line 217 of file d8.cc.
                                                      {
    return ArrayBufferAllocatorBase::AllocateUninitialized(Adjust(length));
  }
References v8::internal::length.
Free()
void v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocator::Free (void * data, size_t length) [inline], [override], [protected], [virtual]
Free the memory block of size |length|, pointed to by |data|.
That memory is guaranteed to be previously allocated by |Allocate|.
Reimplemented from v8::anonymous_namespace{d8.cc}::ArrayBufferAllocatorBase.
Reimplemented in v8::anonymous_namespace{d8.cc}::MockArrayBufferAllocatiorWithLimit.
Definition at line 221 of file d8.cc.
                                                {
    return ArrayBufferAllocatorBase::Free(data, Adjust(length));
  }
References v8::base::Free(), and v8::internal::length.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/d8/d8.cc