v8::internal::BreakIterator Class Reference
#include <debug.h>
Public Member Functions
BreakIterator (Handle< DebugInfo > debug_info)
BreakIterator (const BreakIterator &)=delete
BreakIterator & operator= (const BreakIterator &)=delete
BreakLocation GetBreakLocation ()
bool Done () const
void Next ()
void SkipToPosition (int position)
void SkipTo (int count)
int code_offset ()
int break_index () const
int position () const
int statement_position () const
void ClearDebugBreak ()
void SetDebugBreak ()
DebugBreakType GetDebugBreakType ()
Private Member Functions
int BreakIndexFromPosition (int position)
Private Attributes
Handle< DebugInfo > debug_info_
int break_index_
int position_
int statement_position_
SourcePositionTableIterator source_position_iterator_
Detailed Description
Definition at line 136 of file debug.h.
Constructor & Destructor Documentation
BreakIterator() [1/2]
v8::internal::BreakIterator::BreakIterator (Handle< DebugInfo > debug_info) [explicit]
Definition at line 327 of file debug.cc.
    : debug_info_(debug_info),
      break_index_(-1),
      source_position_iterator_(
          debug_info->DebugBytecodeArray(Isolate::Current())
              ->SourcePositionTable()) {
  position_ = debug_info->shared()->StartPosition();
  statement_position_ = position_;
  // There is at least one break location.
  DCHECK(!Done());
  Next();
}
References v8::internal::DCHECK(), Done(), Next(), position_, and statement_position_.
BreakIterator() [2/2]
v8::internal::BreakIterator::BreakIterator (const BreakIterator &) [delete]
Member Function Documentation
break_index()
int v8::internal::BreakIterator::break_index () const [inline]
Definition at line 152 of file debug.h.
{ return break_index_; }
Referenced by BreakIndexFromPosition().
BreakIndexFromPosition()
int v8::internal::BreakIterator::BreakIndexFromPosition (int position) [private]
Definition at line 340 of file debug.cc.
                                                             {
  for (; !Done(); Next()) {
    if (GetDebugBreakType() == DEBUG_BREAK_SLOT_AT_SUSPEND) continue;
    if (source_position <= position()) {
      int first_break = break_index();
      for (; !Done(); Next()) {
        if (GetDebugBreakType() == DEBUG_BREAK_SLOT_AT_SUSPEND) continue;
        if (source_position == position()) return break_index();
      }
      return first_break;
    }
  }
  return break_index();
}
References break_index(), v8::internal::DEBUG_BREAK_SLOT_AT_SUSPEND, Done(), GetDebugBreakType(), Next(), and position().
Referenced by SkipToPosition().
ClearDebugBreak()
void v8::internal::BreakIterator::ClearDebugBreak ()
Definition at line 423 of file debug.cc.
                                    {
  DCHECK(GetDebugBreakType() >= DEBUGGER_STATEMENT);
  Isolate* isolate = Isolate::Current();
  Tagged<BytecodeArray> bytecode_array =
      debug_info_->DebugBytecodeArray(isolate);
  Tagged<BytecodeArray> original = debug_info_->OriginalBytecodeArray(isolate);
  bytecode_array->set(code_offset(), original->get(code_offset()));
}
References code_offset(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), debug_info_, v8::internal::DEBUGGER_STATEMENT, and GetDebugBreakType().
code_offset()
int v8::internal::BreakIterator::code_offset () [inline]
Definition at line 151 of file debug.h.
{ return source_position_iterator_.code_offset(); }
Referenced by ClearDebugBreak(), GetBreakLocation(), GetDebugBreakType(), v8::internal::BreakLocation::HasBreakPoint(), and SetDebugBreak().
Done()
bool v8::internal::BreakIterator::Done () const [inline]
Definition at line 143 of file debug.h.
{ return source_position_iterator_.done(); }
Referenced by v8::internal::BreakLocation::AllAtCurrentStatement(), v8::internal::BreakLocation::BreakIndexFromCodeOffset(), BreakIndexFromPosition(), BreakIterator(), v8::internal::Debug::ClearBreakPoints(), v8::internal::anonymous_namespace{debug.cc}::FindBreakablePositions(), v8::internal::Debug::FloodWithOneShot(), and Next().
GetBreakLocation()
BreakLocation v8::internal::BreakIterator::GetBreakLocation ()
Definition at line 432 of file debug.cc.
                                              {
  Isolate* isolate = Isolate::Current();
  Handle<AbstractCode> code(
      Cast<AbstractCode>(debug_info_->DebugBytecodeArray(isolate)), isolate);
  DebugBreakType type = GetDebugBreakType();
  int generator_object_reg_index = -1;
  int generator_suspend_id = -1;
  if (type == DEBUG_BREAK_SLOT_AT_SUSPEND) {
    // For suspend break, we'll need the generator object to be able to step
    // over the suspend as if it didn't return. We get the interpreter register
    // index that holds the generator object by reading it directly off the
    // bytecode array, and we'll read the actual generator object off the
    // interpreter stack frame in GetGeneratorObjectForSuspendedFrame.
    Tagged<BytecodeArray> bytecode_array =
        debug_info_->OriginalBytecodeArray(isolate);
    interpreter::BytecodeArrayIterator iterator(handle(bytecode_array, isolate),
                                                code_offset());
    DCHECK_EQ(iterator.current_bytecode(),
              interpreter::Bytecode::kSuspendGenerator);
    interpreter::Register generator_obj_reg = iterator.GetRegisterOperand(0);
    generator_object_reg_index = generator_obj_reg.index();
    // Also memorize the suspend ID, to be able to decide whether
    // we are paused on the implicit initial yield later.
    generator_suspend_id = iterator.GetUnsignedImmediateOperand(3);
  }
  return BreakLocation(code, type, code_offset(), position_,
                       generator_object_reg_index, generator_suspend_id);
}
References code, code_offset(), v8::internal::Isolate::Current(), v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), DCHECK_EQ, v8::internal::DEBUG_BREAK_SLOT_AT_SUSPEND, debug_info_, GetDebugBreakType(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetUnsignedImmediateOperand(), v8::internal::handle(), v8::internal::interpreter::Register::index(), position_, and v8::internal::tracing::type.
Referenced by v8::internal::anonymous_namespace{debug.cc}::FindBreakablePositions(), and v8::internal::BreakLocation::FromFrame().
GetDebugBreakType()
DebugBreakType v8::internal::BreakIterator::GetDebugBreakType ()
Definition at line 377 of file debug.cc.
                                                {
  Tagged<BytecodeArray> bytecode_array =
      debug_info_->OriginalBytecodeArray(Isolate::Current());
  interpreter::Bytecode bytecode =
      interpreter::Bytecodes::FromByte(bytecode_array->get(code_offset()));
  // Make sure we read the actual bytecode, not a prefix scaling bytecode.
  if (interpreter::Bytecodes::IsPrefixScalingBytecode(bytecode)) {
    bytecode = interpreter::Bytecodes::FromByte(
        bytecode_array->get(code_offset() + 1));
  }
  if (bytecode == interpreter::Bytecode::kDebugger) {
    return DEBUGGER_STATEMENT;
  } else if (bytecode == interpreter::Bytecode::kReturn) {
    return DEBUG_BREAK_SLOT_AT_RETURN;
  } else if (bytecode == interpreter::Bytecode::kSuspendGenerator) {
    // SuspendGenerator should always only carry an expression position that
    // is used in stack trace construction, but should never be a breakable
    // position reported to the debugger front-end.
    DCHECK(!source_position_iterator_.is_statement());
    return DEBUG_BREAK_SLOT_AT_SUSPEND;
  } else if (interpreter::Bytecodes::IsCallOrConstruct(bytecode)) {
    return DEBUG_BREAK_SLOT_AT_CALL;
  } else if (source_position_iterator_.is_statement()) {
    return DEBUG_BREAK_SLOT;
  } else {
    return NOT_DEBUG_BREAK;
  }
}
References code_offset(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::DEBUG_BREAK_SLOT, v8::internal::DEBUG_BREAK_SLOT_AT_CALL, v8::internal::DEBUG_BREAK_SLOT_AT_RETURN, v8::internal::DEBUG_BREAK_SLOT_AT_SUSPEND, debug_info_, v8::internal::DEBUGGER_STATEMENT, v8::internal::interpreter::Bytecodes::FromByte(), v8::internal::SourcePositionTableIterator::is_statement(), v8::internal::interpreter::Bytecodes::IsCallOrConstruct(), v8::internal::interpreter::Bytecodes::IsPrefixScalingBytecode(), v8::internal::NOT_DEBUG_BREAK, and source_position_iterator_.
Referenced by BreakIndexFromPosition(), ClearDebugBreak(), v8::internal::anonymous_namespace{debug.cc}::FindBreakablePositions(), GetBreakLocation(), Next(), and SetDebugBreak().
Next()
void v8::internal::BreakIterator::Next ()
Definition at line 355 of file debug.cc.
                         {
  DisallowGarbageCollection no_gc;
  DCHECK(!Done());
  bool first = break_index_ == -1;
  while (!Done()) {
    if (!first) source_position_iterator_.Advance();
    first = false;
    if (Done()) return;
    if (!source_position_iterator_.is_breakable()) continue;
    position_ = source_position_iterator_.source_position().ScriptOffset();
    if (source_position_iterator_.is_statement()) {
      statement_position_ = position_;
    }
    DCHECK_LE(0, position_);
    DCHECK_LE(0, statement_position_);
    DebugBreakType type = GetDebugBreakType();
    if (type != NOT_DEBUG_BREAK) break;
  }
  break_index_++;
}
References v8::internal::SourcePositionTableIterator::Advance(), break_index_, v8::internal::DCHECK(), DCHECK_LE, Done(), GetDebugBreakType(), v8::internal::SourcePositionTableIterator::is_breakable(), v8::internal::SourcePositionTableIterator::is_statement(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NOT_DEBUG_BREAK, position_, v8::internal::SourcePosition::ScriptOffset(), v8::internal::SourcePositionTableIterator::source_position(), source_position_iterator_, statement_position_, and v8::internal::tracing::type.
Referenced by BreakIndexFromPosition(), BreakIterator(), and v8::internal::anonymous_namespace{debug.cc}::FindBreakablePositions().
operator=()
BreakIterator& v8::internal::BreakIterator::operator= (const BreakIterator &) [delete]
position()
int v8::internal::BreakIterator::position () const [inline]
Definition at line 153 of file debug.h.
{ return position_; }
Referenced by BreakIndexFromPosition(), v8::internal::Debug::FindBreakablePosition(), v8::internal::anonymous_namespace{debug.cc}::FindBreakablePositions(), and SkipToPosition().
SetDebugBreak()
void v8::internal::BreakIterator::SetDebugBreak ()
Definition at line 413 of file debug.cc.
                                  {
  DCHECK(GetDebugBreakType() >= DEBUGGER_STATEMENT);
  Isolate* isolate = Isolate::Current();
  HandleScope scope(isolate);
  Handle<BytecodeArray> bytecode_array(debug_info_->DebugBytecodeArray(isolate),
                                       isolate);
  interpreter::BytecodeArrayIterator(bytecode_array, code_offset())
      .ApplyDebugBreak();
}
References v8::internal::interpreter::BytecodeArrayIterator::ApplyDebugBreak(), code_offset(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), debug_info_, v8::internal::DEBUGGER_STATEMENT, and GetDebugBreakType().
Referenced by v8::internal::Debug::ApplyBreakPoints().
SkipTo()
void v8::internal::BreakIterator::SkipTo (int count) [inline]
Definition at line 147 of file debug.h.
                         {
    while (count-- > 0) Next();
  }
References v8::internal::compiler::turboshaft::anonymous_namespace{loop-unrolling-reducer.cc}::Next().
Referenced by v8::internal::BreakLocation::AllAtCurrentStatement(), v8::internal::BreakLocation::FromFrame(), and SkipToPosition().
SkipToPosition()
void v8::internal::BreakIterator::SkipToPosition (int position)
Definition at line 408 of file debug.cc.
                                               {
  BreakIterator it(debug_info_);
  SkipTo(it.BreakIndexFromPosition(position));
}
References BreakIndexFromPosition(), debug_info_, position(), and SkipTo().
Referenced by v8::internal::Debug::ApplyBreakPoints(), v8::internal::Debug::FindBreakablePosition(), and v8::internal::BreakLocation::HasBreakPoint().
statement_position()
int v8::internal::BreakIterator::statement_position () const [inline]
Definition at line 154 of file debug.h.
{ return statement_position_; }
Referenced by v8::internal::BreakLocation::AllAtCurrentStatement().
Member Data Documentation
break_index_
int v8::internal::BreakIterator::break_index_ [private]
Definition at line 165 of file debug.h.
Referenced by Next().
debug_info_
Handle<DebugInfo> v8::internal::BreakIterator::debug_info_ [private]
Definition at line 164 of file debug.h.
Referenced by ClearDebugBreak(), GetBreakLocation(), GetDebugBreakType(), SetDebugBreak(), and SkipToPosition().
position_
int v8::internal::BreakIterator::position_ [private]
Definition at line 166 of file debug.h.
Referenced by BreakIterator(), GetBreakLocation(), and Next().
source_position_iterator_
SourcePositionTableIterator v8::internal::BreakIterator::source_position_iterator_ [private]
Definition at line 168 of file debug.h.
Referenced by GetDebugBreakType(), and Next().
statement_position_
int v8::internal::BreakIterator::statement_position_ [private]
Definition at line 167 of file debug.h.
Referenced by BreakIterator(), and Next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug.h
/mnt/V8SourceCode/src/debug/debug.cc