heap::base::Stack Class Reference
#include <stack.h>
Classes
struct Segment
Public Types
using ThreadId = int
using IterateStackCallback = void(*)(Stack *, void *, const void *)
Public Member Functions
void SetStackStart ()
void IteratePointers (StackVisitor *visitor) const
void IteratePointersUntilMarker (StackVisitor *visitor) const
void IteratePointersFromAddressUntilMarker (StackVisitor *visitor, const void *address) const
void IterateBackgroundStacks (StackVisitor *visitor) const
template<typename Callback >
void SetMarkerAndCallback (Callback callback)
template<typename Callback >
void SetMarkerIfNeededAndCallback (Callback callback)
template<typename Callback >
void SetMarkerForBackgroundThreadAndCallback (ThreadId thread, Callback callback)
void IteratePointersForTesting (StackVisitor *visitor)
bool IsMarkerSet () const
bool IsMarkerSetForBackgroundThread (ThreadId thread) const
bool HasBackgroundStacks () const
void SetScanSimulatorCallback (StackVisitorCallback callback)
Static Public Member Functions
static bool IsOnStack (const void *slot)
Private Member Functions
V8_NOINLINE void TrampolineCallbackHelper (void *argument, IterateStackCallback callback)
void IteratePointersInSegment (StackVisitor *visitor, Segment segment) const
Static Private Member Functions
template<typename Callback >
static void SetMarkerAndCallbackImpl (Stack *stack, void *argument, const void *stack_end)
template<typename Callback >
static void SetMarkerForBackgroundThreadAndCallbackImpl (Stack *stack, void *argument, const void *stack_end)
Private Attributes
Segment current_segment_
v8::base::Mutex lock_
std::map< ThreadId, Segment > background_stacks_
StackVisitorCallback scan_simulator_callback_ = nullptr
Detailed Description
Definition at line 35 of file stack.h.
Member Typedef Documentation
IterateStackCallback
using heap::base::Stack::IterateStackCallback = void (*)(Stack*, void*, const void*)
Definition at line 100 of file stack.h.
ThreadId
using heap::base::Stack::ThreadId = int
Definition at line 89 of file stack.h.
Member Function Documentation
HasBackgroundStacks()
bool heap::base::Stack::HasBackgroundStacks () const [inline]
Definition at line 119 of file stack.h.
{ return !background_stacks_.empty(); }
Referenced by v8::internal::Heap::IsGCWithStack().
IsMarkerSet()
bool heap::base::Stack::IsMarkerSet () const [inline]
Definition at line 108 of file stack.h.
{ return current_segment_.top != nullptr; }
Referenced by v8::internal::LocalHeap::is_in_trampoline().
IsMarkerSetForBackgroundThread()
bool heap::base::Stack::IsMarkerSetForBackgroundThread (ThreadId thread) const [inline]
Definition at line 109 of file stack.h.
                                                             {
    v8::base::MutexGuard guard(&lock_);
    auto it = background_stacks_.find(thread);
    if (it == background_stacks_.end()) return false;
    DCHECK_NOT_NULL(it->second.top);
    return true;
  }
References DCHECK_NOT_NULL.
Referenced by v8::internal::LocalHeap::is_in_trampoline().
IsOnStack()
bool heap::base::Stack::IsOnStack (const void * slot) [static]
Definition at line 24 of file stack.cc.
                                      {
#ifdef V8_USE_ADDRESS_SANITIZER
  // If the slot is part of a fake frame, then it is definitely on the stack.
  if (__asan_addr_is_in_fake_stack(__asan_get_current_fake_stack(),
                                   const_cast<void*>(slot), nullptr, nullptr)) {
    return true;
  }
  // Fall through as there is still a regular stack present even when running
  // with ASAN fake stacks.
#endif // V8_USE_ADDRESS_SANITIZER
#ifdef V8_USE_SAFE_STACK
  if (__builtin___get_unsafe_stack_ptr() <= slot &&
      slot <= __builtin___get_unsafe_stack_top()) {
    return true;
  }
#endif // V8_USE_SAFE_STACK
  return v8::base::Stack::GetCurrentStackPosition() <= slot &&
         slot <= v8::base::Stack::GetStackStartUnchecked();
}
References v8::base::Stack::GetCurrentStackPosition(), and v8::base::Stack::GetStackStartUnchecked().
Referenced by cppgc::internal::BasicMarkingState::RegisterMovableReference().
IterateBackgroundStacks()
void heap::base::Stack::IterateBackgroundStacks (StackVisitor * visitor) const
Definition at line 186 of file stack.cc.
                                                               {
  // Temporarily stop checking MTE tags whilst scanning the stack (whilst V8
  // may not be tagging its portion of the stack, higher frames from the OS or
  // libc could be using stack tagging.)
  SuspendTagCheckingScope s;
  for (const auto& [_, segment] : background_stacks_) {
    // All supported platforms should have their stack aligned to at least
    // sizeof(void*).
    constexpr size_t kMinStackAlignment = sizeof(void*);
    CHECK_EQ(0u, reinterpret_cast<uintptr_t>(segment.top) &
                     (kMinStackAlignment - 1));
    IteratePointersInStack(visitor, segment);
    IteratePointersInUnsafeStackIfNecessary(visitor, segment);
  }
}
References _, background_stacks_, CHECK_EQ, heap::base::anonymous_namespace{stack.cc}::IteratePointersInStack(), and heap::base::anonymous_namespace{stack.cc}::IteratePointersInUnsafeStackIfNecessary().
Referenced by v8::internal::Heap::IterateConservativeStackRoots().
IteratePointers()
void heap::base::Stack::IteratePointers (StackVisitor * visitor) const [inline]
Definition at line 53 of file stack.h.
                                                    {
    IteratePointersUntilMarker(visitor);
    IterateBackgroundStacks(visitor);
  }
Referenced by IteratePointersForTesting().
IteratePointersForTesting()
void heap::base::Stack::IteratePointersForTesting (StackVisitor * visitor)
Definition at line 157 of file stack.cc.
                                                           {
  SetMarkerAndCallback([this, visitor]() { IteratePointers(visitor); });
}
References IteratePointers(), and SetMarkerAndCallback().
IteratePointersFromAddressUntilMarker()
void heap::base::Stack::IteratePointersFromAddressUntilMarker (StackVisitor * visitor, const void * address) const
Definition at line 165 of file stack.cc.
                                                                             {
  DCHECK_NOT_NULL(address);
  DCHECK(current_segment_.Contains(address));
  Segment segment = {address, current_segment_.top};
  IteratePointersInSegment(visitor, segment);
}
References current_segment_, DCHECK, DCHECK_NOT_NULL, IteratePointersInSegment(), and heap::base::Stack::Segment::top.
Referenced by v8::internal::Heap::IterateConservativeStackRoots().
IteratePointersInSegment()
void heap::base::Stack::IteratePointersInSegment (StackVisitor * visitor, Segment segment) const [private]
Definition at line 173 of file stack.cc.
                                                            {
  // Temporarily stop checking MTE tags whilst scanning the stack (whilst V8
  // may not be tagging its portion of the stack, higher frames from the OS or
  // libc could be using stack tagging.)
  SuspendTagCheckingScope s;
  IteratePointersInStack(visitor, segment);
  IteratePointersInUnsafeStackIfNecessary(visitor, segment);
  if (scan_simulator_callback_) {
    scan_simulator_callback_(visitor);
  }
}
References heap::base::anonymous_namespace{stack.cc}::IteratePointersInStack(), heap::base::anonymous_namespace{stack.cc}::IteratePointersInUnsafeStackIfNecessary(), and scan_simulator_callback_.
Referenced by IteratePointersFromAddressUntilMarker(), and IteratePointersUntilMarker().
IteratePointersUntilMarker()
void heap::base::Stack::IteratePointersUntilMarker (StackVisitor * visitor) const
Definition at line 161 of file stack.cc.
                                                                  {
  IteratePointersInSegment(visitor, current_segment_);
}
References current_segment_, and IteratePointersInSegment().
Referenced by v8::internal::Heap::IterateConservativeStackRoots(), cppgc::internal::MarkingVerifierBase::Run(), and cppgc::internal::MarkerBase::VisitLocalRoots().
SetMarkerAndCallback()
template<typename Callback >
void heap::base::Stack::SetMarkerAndCallback (Callback callback) [inline]
Definition at line 73 of file stack.h.
                                                         {
    TrampolineCallbackHelper(static_cast<void*>(&callback),
                             &SetMarkerAndCallbackImpl<Callback>);
  }
Referenced by v8::internal::LocalHeap::ExecuteMainThreadWhileParked(), v8::internal::LocalHeap::ExecuteWithStackMarker(), and IteratePointersForTesting().
SetMarkerAndCallbackImpl()
template<typename Callback >
static void heap::base::Stack::SetMarkerAndCallbackImpl (Stack * stack, void * argument, const void * stack_end) [inline], [static], [private]
Definition at line 176 of file stack.h.
                                                              {
    Segment previous_segment = stack->current_segment_;
    stack->current_segment_.top = stack_end;
#ifdef V8_USE_SAFE_STACK
    stack->current_segment_.unsafe_stack_top =
        __builtin___get_unsafe_stack_ptr();
#endif // V8_USE_SAFE_STACK
    Callback* callback = static_cast<Callback*>(argument);
    (*callback)();
    stack->current_segment_ = previous_segment;
  }
References v8::internal::stack.
SetMarkerForBackgroundThreadAndCallback()
template<typename Callback >
void heap::base::Stack::SetMarkerForBackgroundThreadAndCallback (ThreadId thread, Callback callback) [inline]
Definition at line 92 of file stack.h.
                                                                            {
    std::pair<ThreadId, Callback*> info{thread, &callback};
    TrampolineCallbackHelper(
        static_cast<void*>(&info),
        &SetMarkerForBackgroundThreadAndCallbackImpl<Callback>);
  }
Referenced by v8::internal::LocalHeap::ExecuteBackgroundThreadWhileParked(), and v8::internal::LocalHeap::ExecuteWithStackMarker().
SetMarkerForBackgroundThreadAndCallbackImpl()
template<typename Callback >
static void heap::base::Stack::SetMarkerForBackgroundThreadAndCallbackImpl (Stack * stack, void * argument, const void * stack_end) [inline], [static], [private]
Definition at line 190 of file stack.h.
                                                           {
    DCHECK(IsOnCurrentStack(stack_end));
    auto [thread, callback] =
        *static_cast<std::pair<ThreadId, Callback*>*>(argument);
    auto& background_stacks = stack->background_stacks_;
    Segment previous_segment;
    {
      v8::base::MutexGuard guard(&stack->lock_);
      if (auto it = background_stacks.find(thread);
          it != background_stacks.end()) {
        previous_segment = it->second;
        DCHECK_NOT_NULL(previous_segment.top);
      } else {
        DCHECK_NULL(previous_segment.top);
      }
      // This implicitly uses the current values (if applicable) for:
      // - asan_fake_start
      // - unsafe stack start
      // - unsafe stack top
      background_stacks[thread] =
          Segment(v8::base::Stack::GetStackStart(), stack_end);
    }
    (*callback)();
    {
      v8::base::MutexGuard guard(&stack->lock_);
      if (previous_segment.top)
        background_stacks[thread] = previous_segment;
      else
        background_stacks.erase(thread);
    }
  }
References DCHECK, DCHECK_NOT_NULL, DCHECK_NULL, v8::base::Stack::GetStackStart(), v8::internal::stack, and heap::base::Stack::Segment::top.
SetMarkerIfNeededAndCallback()
template<typename Callback >
void heap::base::Stack::SetMarkerIfNeededAndCallback (Callback callback) [inline]
Definition at line 79 of file stack.h.
                                                                 {
    if (!IsMarkerSet()) {
      TrampolineCallbackHelper(static_cast<void*>(&callback),
                               &SetMarkerAndCallbackImpl<Callback>);
    } else {
      DCHECK(IsOnCurrentStack(current_segment_.top));
      callback();
    }
  }
References DCHECK.
Referenced by v8::internal::Heap::CollectGarbage(), v8::internal::CppHeap::CollectGarbageForTesting(), cppgc::internal::Heap::FinalizeGarbageCollection(), v8::internal::UnreachableObjectsFilter::MarkReachableObjects(), v8::internal::HeapProfiler::QueryObjects(), v8::internal::HeapProfiler::TakeSnapshot(), cppgc::internal::MarkerBase::VisitLocalRoots(), and v8::internal::HeapProfiler::WriteSnapshotToDiskAfterGC().
SetScanSimulatorCallback()
void heap::base::Stack::SetScanSimulatorCallback (StackVisitorCallback callback) [inline]
Definition at line 121 of file stack.h.
                                                               {
    scan_simulator_callback_ = callback;
  }
Referenced by v8::internal::LocalHeap::LocalHeap().
SetStackStart()
void heap::base::Stack::SetStackStart () [inline]
Definition at line 38 of file stack.h.
                       {
    current_segment_.start = v8::base::Stack::GetStackStart();
#ifdef V8_USE_ADDRESS_SANITIZER
    current_segment_.asan_fake_stack = __asan_get_current_fake_stack();
#endif // V8_USE_ADDRESS_SANITIZER
#ifdef V8_USE_SAFE_STACK
    current_segment_.unsafe_stack_start = __builtin___get_unsafe_stack_top();
#endif // V8_USE_SAFE_STACK
  }
References v8::base::Stack::GetStackStart().
Referenced by v8::internal::Heap::SetStackStart().
TrampolineCallbackHelper()
void heap::base::Stack::TrampolineCallbackHelper (void * argument, IterateStackCallback callback) [private]
Definition at line 213 of file stack.cc.
                                                                    {
  PushAllRegistersAndIterateStack(this, argument, callback);
  // TODO(chromium:1056170): Add support for SIMD and/or filtering.
}
References heap::base::PushAllRegistersAndIterateStack().
Member Data Documentation
background_stacks_
std::map<ThreadId, Segment> heap::base::Stack::background_stacks_ [private]
Definition at line 228 of file stack.h.
Referenced by IterateBackgroundStacks().
current_segment_
Segment heap::base::Stack::current_segment_ [private]
Definition at line 225 of file stack.h.
Referenced by IteratePointersFromAddressUntilMarker(), and IteratePointersUntilMarker().
lock_
v8::base::Mutex heap::base::Stack::lock_ [mutable], [private]
Definition at line 227 of file stack.h.
scan_simulator_callback_
StackVisitorCallback heap::base::Stack::scan_simulator_callback_ = nullptr [private]
Definition at line 230 of file stack.h.
Referenced by IteratePointersInSegment().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/base/stack.h
/mnt/V8SourceCode/src/heap/base/stack.cc