v8::internal::baseline::EnsureAccumulatorPreservedScope Class Reference
#include <baseline-assembler.h>
Public Member Functions
EnsureAccumulatorPreservedScope (BaselineAssembler *assembler)
~EnsureAccumulatorPreservedScope ()
Private Member Functions
void AssertEqualToAccumulator (Register reg)
Private Attributes
BaselineAssembler * assembler_
Detailed Description
Definition at line 260 of file baseline-assembler.h.
Constructor & Destructor Documentation
EnsureAccumulatorPreservedScope()
v8::internal::baseline::EnsureAccumulatorPreservedScope::EnsureAccumulatorPreservedScope (BaselineAssembler * assembler) [inline], [explicit]
Definition at line 157 of file baseline-assembler-inl.h.
    : assembler_(assembler)
#ifdef V8_CODE_COMMENTS
      ,
      comment_(assembler->masm(), "EnsureAccumulatorPreservedScope")
#endif
{
  assembler_->Push(kInterpreterAccumulatorRegister);
}
References assembler_, v8::internal::kInterpreterAccumulatorRegister, and v8::internal::baseline::BaselineAssembler::Push().
 EnsureAccumulatorPreservedScope()
v8::internal::baseline::EnsureAccumulatorPreservedScope::~EnsureAccumulatorPreservedScope () [inline]
Definition at line 168 of file baseline-assembler-inl.h.
                                                                  {
  BaselineAssembler::ScratchRegisterScope scratch(assembler_);
  Register reg = scratch.AcquireScratch();
  assembler_->Pop(reg);
  AssertEqualToAccumulator(reg);
}
References v8::internal::baseline::BaselineAssembler::ScratchRegisterScope::AcquireScratch(), assembler_, AssertEqualToAccumulator(), and v8::internal::baseline::BaselineAssembler::Pop().
Member Function Documentation
AssertEqualToAccumulator()
void v8::internal::baseline::EnsureAccumulatorPreservedScope::AssertEqualToAccumulator (Register reg) [inline], [private]
Definition at line 567 of file baseline-assembler-arm-inl.h.
                  {
  assembler_->masm()->cmp(reg, kInterpreterAccumulatorRegister);
  assembler_->masm()->Assert(eq, AbortReason::kAccumulatorClobbered);
}
References assembler_, v8::internal::MacroAssembler::Assert(), v8::internal::Assembler::cmp(), v8::internal::eq, v8::internal::kInterpreterAccumulatorRegister, and v8::internal::baseline::BaselineAssembler::masm().
Referenced by ~EnsureAccumulatorPreservedScope().
Member Data Documentation
assembler_
BaselineAssembler* v8::internal::baseline::EnsureAccumulatorPreservedScope::assembler_ [private]
Definition at line 269 of file baseline-assembler.h.
Referenced by AssertEqualToAccumulator(), EnsureAccumulatorPreservedScope(), and ~EnsureAccumulatorPreservedScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/baseline/baseline-assembler.h
/mnt/V8SourceCode/src/baseline/arm/baseline-assembler-arm-inl.h
/mnt/V8SourceCode/src/baseline/arm64/baseline-assembler-arm64-inl.h
/mnt/V8SourceCode/src/baseline/baseline-assembler-inl.h
/mnt/V8SourceCode/src/baseline/ia32/baseline-assembler-ia32-inl.h
/mnt/V8SourceCode/src/baseline/loong64/baseline-assembler-loong64-inl.h
/mnt/V8SourceCode/src/baseline/mips64/baseline-assembler-mips64-inl.h
/mnt/V8SourceCode/src/baseline/ppc/baseline-assembler-ppc-inl.h
/mnt/V8SourceCode/src/baseline/riscv/baseline-assembler-riscv-inl.h
/mnt/V8SourceCode/src/baseline/s390/baseline-assembler-s390-inl.h
/mnt/V8SourceCode/src/baseline/x64/baseline-assembler-x64-inl.h