v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes Class Reference
Public Member Functions
AbstractStateForEffectNodes (Zone *zone)
AbstractState const * Get (Node *node) const
void Set (Node *node, AbstractState const *state)
Zone * zone () const
Private Attributes
ZoneVector< AbstractState const * > info_for_node_
Detailed Description
Definition at line 315 of file load-elimination.h.
Constructor & Destructor Documentation
AbstractStateForEffectNodes()
v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::AbstractStateForEffectNodes (Zone * zone) [inline], [explicit]
Definition at line 317 of file load-elimination.h.
: info_for_node_(zone) {}
Member Function Documentation
Get()
LoadElimination::AbstractState const * v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Get (Node * node) const
Definition at line 758 of file load-elimination.cc.
                                                                {
  size_t const id = node->id();
  if (id < info_for_node_.size()) return info_for_node_[id];
  return nullptr;
}
References v8::internal::compiler::Node::id().
Referenced by v8::internal::compiler::LoadElimination::Reduce(), v8::internal::compiler::LoadElimination::ReduceCheckMaps(), v8::internal::compiler::LoadElimination::ReduceCompareMaps(), v8::internal::compiler::LoadElimination::ReduceEffectPhi(), v8::internal::compiler::LoadElimination::ReduceEnsureWritableFastElements(), v8::internal::compiler::LoadElimination::ReduceLoadElement(), v8::internal::compiler::LoadElimination::ReduceLoadField(), v8::internal::compiler::LoadElimination::ReduceMapGuard(), v8::internal::compiler::LoadElimination::ReduceMaybeGrowFastElements(), v8::internal::compiler::LoadElimination::ReduceOtherNode(), v8::internal::compiler::LoadElimination::ReduceStoreElement(), v8::internal::compiler::LoadElimination::ReduceStoreField(), v8::internal::compiler::LoadElimination::ReduceStoreTypedElement(), v8::internal::compiler::LoadElimination::ReduceTransitionAndStoreElement(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKind(), v8::internal::compiler::LoadElimination::ReduceTransitionElementsKindOrCheckMap(), v8::internal::compiler::LoadElimination::UpdateState(), and v8::internal::compiler::LoadElimination::UpdateStateForPhi().
Set()
void v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::Set (Node * node, AbstractState const * state)
Definition at line 764 of file load-elimination.cc.
                                            {
  size_t const id = node->id();
  if (id >= info_for_node_.size()) info_for_node_.resize(id + 1, nullptr);
  info_for_node_[id] = state;
}
References v8::internal::compiler::Node::id().
Referenced by v8::internal::compiler::LoadElimination::UpdateState().
zone()
Zone* v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::zone () const [inline]
Definition at line 321 of file load-elimination.h.
{ return info_for_node_.zone(); }
Member Data Documentation
info_for_node_
ZoneVector<AbstractState const*> v8::internal::compiler::LoadElimination::AbstractStateForEffectNodes::info_for_node_ [private]
Definition at line 324 of file load-elimination.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/load-elimination.h
/mnt/V8SourceCode/src/compiler/load-elimination.cc