cppgc::internal::CagedHeap Class Reference
#include <caged-heap.h>
Public Types
using AllocatorType = v8::base::BoundedPageAllocator
Public Member Functions
CagedHeap (const CagedHeap &)=delete
CagedHeap & operator= (const CagedHeap &)=delete
AllocatorType & page_allocator ()
const AllocatorType & page_allocator () const
bool IsOnHeap (const void *address) const
void * base () const
Static Public Member Functions
template<typename RetType = uintptr_t>
static RetType OffsetFromAddress (const void *address)
static uintptr_t BaseFromAddress (const void *address)
static void InitializeIfNeeded (PageAllocator &platform_allocator, size_t desired_heap_size)
static void CommitAgeTable (PageAllocator &platform_allocator)
static CagedHeap & Instance ()
Private Member Functions
CagedHeap (PageAllocator &platform_allocator, size_t desired_heap_size)
Private Attributes
const VirtualMemory reserved_area_
std::unique_ptr< AllocatorType > page_bounded_allocator_
Static Private Attributes
static CagedHeap * instance_ = nullptr
Friends
class v8::base::LeakyObject< CagedHeap >
class testing::TestWithHeap
Detailed Description
Definition at line 25 of file caged-heap.h.
Member Typedef Documentation
AllocatorType
using cppgc::internal::CagedHeap::AllocatorType = v8::base::BoundedPageAllocator
Definition at line 27 of file caged-heap.h.
Constructor & Destructor Documentation
CagedHeap() [1/2]
cppgc::internal::CagedHeap::CagedHeap (const CagedHeap &) [delete]
CagedHeap() [2/2]
cppgc::internal::CagedHeap::CagedHeap (PageAllocator & platform_allocator, size_t desired_heap_size) [explicit], [private]
defined(CPPGC_POINTER_COMPRESSION)
Definition at line 98 of file caged-heap.cc.
    : reserved_area_(ReserveCagedHeap(platform_allocator)) {
  using CagedAddress = CagedHeap::AllocatorType::Address;
#if defined(CPPGC_POINTER_COMPRESSION)
  // Pick a base offset according to pointer compression shift. See comment in
  // ReserveCagedHeap().
  static constexpr size_t kBaseOffset =
      api_constants::kCagedHeapMaxReservationSize;
#else // !defined(CPPGC_POINTER_COMPRESSION)
  static constexpr size_t kBaseOffset = 0;
#endif //! defined(CPPGC_POINTER_COMPRESSION)
  void* const cage_start =
      static_cast<uint8_t*>(reserved_area_.address()) + kBaseOffset;
  CagedHeapBase::g_heap_base_ = reinterpret_cast<uintptr_t>(cage_start);
#if defined(CPPGC_POINTER_COMPRESSION)
  // With pointer compression only single heap per thread is allowed.
  CHECK(!CageBaseGlobal::IsSet());
  CageBaseGlobalUpdater::UpdateCageBase(CagedHeapBase::g_heap_base_);
#endif // defined(CPPGC_POINTER_COMPRESSION)
  const size_t total_heap_size = std::clamp<size_t>(
      v8::base::bits::RoundUpToPowerOfTwo64(desired_heap_size),
      api_constants::kCagedHeapDefaultReservationSize,
      api_constants::kCagedHeapMaxReservationSize);
  const size_t local_data_size =
      CagedHeapLocalData::CalculateLocalDataSizeForHeapSize(total_heap_size);
  const CagedAddress caged_heap_start = RoundUp(
      reinterpret_cast<CagedAddress>(cage_start) + local_data_size, kPageSize);
  const size_t local_data_size_with_padding =
      caged_heap_start - reinterpret_cast<CagedAddress>(cage_start);
  page_bounded_allocator_ = std::make_unique<v8::base::BoundedPageAllocator>(
      &platform_allocator, caged_heap_start,
      total_heap_size - local_data_size_with_padding, kPageSize,
      v8::base::PageInitializationMode::kAllocatedPagesMustBeZeroInitialized,
      v8::base::PageFreeingMode::kMakeInaccessible);
  instance_ = this;
  CagedHeapBase::g_age_table_size_ = AgeTable::CalculateAgeTableSizeForHeapSize(
      api_constants::kCagedHeapDefaultReservationSize);
}
References cppgc::internal::VirtualMemory::address(), CHECK, instance_, v8::base::kAllocatedPagesMustBeZeroInitialized, v8::base::kMakeInaccessible, cppgc::internal::kPageSize, page_bounded_allocator_, reserved_area_, RoundUp(), and v8::base::bits::RoundUpToPowerOfTwo64().
Member Function Documentation
base()
void* cppgc::internal::CagedHeap::base () const [inline]
Definition at line 65 of file caged-heap.h.
{ return reserved_area_.address(); }
BaseFromAddress()
static uintptr_t cppgc::internal::CagedHeap::BaseFromAddress (const void * address) [inline], [static]
Definition at line 38 of file caged-heap.h.
                                                        {
    return reinterpret_cast<uintptr_t>(address) &
           ~(api_constants::kCagedHeapReservationAlignment - 1);
  }
CommitAgeTable()
void cppgc::internal::CagedHeap::CommitAgeTable (PageAllocator & platform_allocator) [static]
Definition at line 146 of file caged-heap.cc.
                                                                {
  if (!platform_allocator.SetPermissions(
          reinterpret_cast<void*>(CagedHeapBase::g_heap_base_),
          RoundUp(CagedHeapBase::g_age_table_size_,
                  platform_allocator.CommitPageSize()),
          PageAllocator::kReadWrite)) {
    GetGlobalOOMHandler()("Oilpan: CagedHeap commit CageHeapLocalData.");
  }
}
References v8::PageAllocator::CommitPageSize(), cppgc::internal::GetGlobalOOMHandler(), v8::PageAllocator::kReadWrite, RoundUp(), and v8::PageAllocator::SetPermissions().
InitializeIfNeeded()
void cppgc::internal::CagedHeap::InitializeIfNeeded (PageAllocator & platform_allocator, size_t desired_heap_size) [static]
Definition at line 86 of file caged-heap.cc.
                                                             {
  static v8::base::LeakyObject<CagedHeap> caged_heap(platform_allocator,
                                                     desired_heap_size);
}
Referenced by cppgc::InitializeProcess().
Instance()
CagedHeap & cppgc::internal::CagedHeap::Instance () [static]
Definition at line 93 of file caged-heap.cc.
                               {
  DCHECK_NOT_NULL(instance_);
  return *instance_;
}
References DCHECK_NOT_NULL, and instance_.
Referenced by cppgc::internal::HeapBase::InitializePageBackend(), cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl(), and cppgc::internal::MarkingVerifierBase::VisitHeapObjectHeader().
IsOnHeap()
bool cppgc::internal::CagedHeap::IsOnHeap (const void * address) const [inline]
Definition at line 58 of file caged-heap.h.
                                           {
    DCHECK_EQ(reserved_area_.address(),
              reinterpret_cast<void*>(CagedHeapBase::GetBase()));
    return reinterpret_cast<void*>(BaseFromAddress(address)) ==
           reserved_area_.address();
  }
References DCHECK_EQ.
OffsetFromAddress()
template<typename RetType = uintptr_t>
static RetType cppgc::internal::CagedHeap::OffsetFromAddress (const void * address) [inline], [static]
Definition at line 30 of file caged-heap.h.
                                                        {
    static_assert(std::numeric_limits<RetType>::max() >=
                      (api_constants::kCagedHeapMaxReservationSize - 1),
                  "The return type should be large enough");
    return reinterpret_cast<uintptr_t>(address) &
           (api_constants::kCagedHeapReservationAlignment - 1);
  }
Referenced by cppgc::internal::anonymous_namespace{object-allocator.cc}::MarkRangeAsYoung().
operator=()
CagedHeap& cppgc::internal::CagedHeap::operator= (const CagedHeap &) [delete]
page_allocator() [1/2]
AllocatorType& cppgc::internal::CagedHeap::page_allocator () [inline]
Definition at line 53 of file caged-heap.h.
{ return *page_bounded_allocator_; }
Referenced by cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl().
page_allocator() [2/2]
const AllocatorType& cppgc::internal::CagedHeap::page_allocator () const [inline]
Definition at line 54 of file caged-heap.h.
                                              {
    return *page_bounded_allocator_;
  }
Friends And Related Function Documentation
testing::TestWithHeap
friend class testing::TestWithHeap [friend]
Definition at line 69 of file caged-heap.h.
v8::base::LeakyObject< CagedHeap >
friend class v8::base::LeakyObject< CagedHeap > [friend]
Definition at line 65 of file caged-heap.h.
Member Data Documentation
instance_
CagedHeap * cppgc::internal::CagedHeap::instance_ = nullptr [static], [private]
Definition at line 74 of file caged-heap.h.
Referenced by CagedHeap(), and Instance().
page_bounded_allocator_
std::unique_ptr<AllocatorType> cppgc::internal::CagedHeap::page_bounded_allocator_ [private]
Definition at line 79 of file caged-heap.h.
Referenced by CagedHeap().
reserved_area_
const VirtualMemory cppgc::internal::CagedHeap::reserved_area_ [private]
Definition at line 76 of file caged-heap.h.
Referenced by CagedHeap().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/caged-heap.h
/mnt/V8SourceCode/src/heap/cppgc/caged-heap.cc