v8::internal::BinaryOperationSourceRanges Class Reference
#include <ast-source-ranges.h>
Public Member Functions
BinaryOperationSourceRanges (const SourceRange &right_range)
SourceRange GetRange (SourceRangeKind kind) override
bool HasRange (SourceRangeKind kind) override
Private Attributes
SourceRange right_range_
Detailed Description
Definition at line 81 of file ast-source-ranges.h.
Constructor & Destructor Documentation
BinaryOperationSourceRanges()
v8::internal::BinaryOperationSourceRanges::BinaryOperationSourceRanges (const SourceRange & right_range) [inline], [explicit]
Definition at line 83 of file ast-source-ranges.h.
      : right_range_(right_range) {}
Member Function Documentation
GetRange()
SourceRange v8::internal::BinaryOperationSourceRanges::GetRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 86 of file ast-source-ranges.h.
                                                      {
    DCHECK(HasRange(kind));
    return right_range_;
  }
References v8::internal::DCHECK(), HasRange(), and right_range_.
Referenced by v8::internal::Parser::ConvertBinaryToNaryOperationSourceRange().
HasRange()
bool v8::internal::BinaryOperationSourceRanges::HasRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 91 of file ast-source-ranges.h.
                                               {
    return kind == SourceRangeKind::kRight;
  }
References v8::internal::kRight.
Referenced by GetRange().
Member Data Documentation
right_range_
SourceRange v8::internal::BinaryOperationSourceRanges::right_range_ [private]
Definition at line 96 of file ast-source-ranges.h.
Referenced by GetRange().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-source-ranges.h