v8::internal::RegExpMacroAssembler Class Reference
#include <regexp-macro-assembler.h>
Public Types
enum StackCheckFlag { kNoStackLimitCheck = false
, kCheckStackLimit = true
 }
enum IrregexpImplementation
enum GlobalMode { NOT_GLOBAL
, GLOBAL_NO_ZERO_LENGTH_CHECK
, GLOBAL
, GLOBAL_UNICODE
 }
Public Member Functions
RegExpMacroAssembler (Isolate *isolate, Zone *zone)
virtual ~RegExpMacroAssembler ()=default
virtual DirectHandle< HeapObject > GetCode (DirectHandle< String > source, RegExpFlags flags)=0
virtual void AbortedCodeGeneration ()
virtual int stack_limit_slack_slot_count ()=0
virtual bool CanReadUnaligned () const =0
virtual void AdvanceCurrentPosition (int by)=0
virtual void AdvanceRegister (int reg, int by)=0
virtual void Backtrack ()=0
virtual void Bind (Label *label)=0
virtual void CheckCharacter (unsigned c, Label *on_equal)=0
virtual void CheckCharacterAfterAnd (unsigned c, unsigned and_with, Label *on_equal)=0
virtual void CheckCharacterGT (base::uc16 limit, Label *on_greater)=0
virtual void CheckCharacterLT (base::uc16 limit, Label *on_less)=0
virtual void CheckFixedLengthLoop (Label *on_tos_equals_current_position)=0
virtual void CheckAtStart (int cp_offset, Label *on_at_start)=0
virtual void CheckNotAtStart (int cp_offset, Label *on_not_at_start)=0
virtual void CheckNotBackReference (int start_reg, bool read_backward, Label *on_no_match)=0
virtual void CheckNotBackReferenceIgnoreCase (int start_reg, bool read_backward, bool unicode, Label *on_no_match)=0
virtual void CheckNotCharacter (unsigned c, Label *on_not_equal)=0
virtual void CheckNotCharacterAfterAnd (unsigned c, unsigned and_with, Label *on_not_equal)=0
virtual void CheckNotCharacterAfterMinusAnd (base::uc16 c, base::uc16 minus, base::uc16 and_with, Label *on_not_equal)=0
virtual void CheckCharacterInRange (base::uc16 from, base::uc16 to, Label *on_in_range)=0
virtual void CheckCharacterNotInRange (base::uc16 from, base::uc16 to, Label *on_not_in_range)=0
virtual bool CheckCharacterInRangeArray (const ZoneList< CharacterRange > *ranges, Label *on_in_range)=0
virtual bool CheckCharacterNotInRangeArray (const ZoneList< CharacterRange > *ranges, Label *on_not_in_range)=0
virtual void CheckBitInTable (Handle< ByteArray > table, Label *on_bit_set)=0
virtual void SkipUntilBitInTable (int cp_offset, Handle< ByteArray > table, Handle< ByteArray > nibble_table, int advance_by)=0
virtual bool SkipUntilBitInTableUseSimd (int advance_by)
virtual void CheckPosition (int cp_offset, Label *on_outside_input)
virtual bool CheckSpecialClassRanges (StandardCharacterSet type, Label *on_no_match)
virtual void BindJumpTarget (Label *label)
virtual void Fail ()=0
virtual void GoTo (Label *label)=0
virtual void IfRegisterGE (int reg, int comparand, Label *if_ge)=0
virtual void IfRegisterLT (int reg, int comparand, Label *if_lt)=0
virtual void IfRegisterEqPos (int reg, Label *if_eq)=0
V8_EXPORT_PRIVATE void LoadCurrentCharacter (int cp_offset, Label *on_end_of_input, bool check_bounds=true, int characters=1, int eats_at_least=kUseCharactersValue)
virtual void LoadCurrentCharacterImpl (int cp_offset, Label *on_end_of_input, bool check_bounds, int characters, int eats_at_least)=0
virtual void PopCurrentPosition ()=0
virtual void PopRegister (int register_index)=0
virtual void PushBacktrack (Label *label)=0
virtual void PushCurrentPosition ()=0
virtual void PushRegister (int register_index, StackCheckFlag check_stack_limit)=0
virtual void ReadCurrentPositionFromRegister (int reg)=0
virtual void ReadStackPointerFromRegister (int reg)=0
virtual void SetCurrentPositionFromEnd (int by)=0
virtual void SetRegister (int register_index, int to)=0
virtual bool Succeed ()=0
virtual void WriteCurrentPositionToRegister (int reg, int cp_offset)=0
virtual void ClearRegisters (int reg_from, int reg_to)=0
virtual void WriteStackPointerToRegister (int reg)=0
void CheckNotInSurrogatePair (int cp_offset, Label *on_failure)
const char * ImplementationToString (IrregexpImplementation impl)
virtual IrregexpImplementation Implementation ()=0
void set_slow_safe (bool ssc)
bool slow_safe () const
void set_backtrack_limit (uint32_t backtrack_limit)
void set_can_fallback (bool val)
void set_global_mode (GlobalMode mode)
bool global () const
bool global_with_zero_length_check () const
bool global_unicode () const
Isolate * isolate () const
Zone * zone () const
Static Public Member Functions
static int CaseInsensitiveCompareNonUnicode (Address byte_offset1, Address byte_offset2, size_t byte_length, Isolate *isolate)
static int CaseInsensitiveCompareUnicode (Address byte_offset1, Address byte_offset2, size_t byte_length, Isolate *isolate)
static uint32_t IsCharacterInRangeArray (uint32_t current_char, Address raw_byte_array)
Static Public Attributes
static constexpr int kMaxRegisterCount = (1 << 16)
static constexpr int kMaxRegister = kMaxRegisterCount - 1
static constexpr int kMaxCaptures = (kMaxRegister - 1) / 2
static constexpr int kMaxCPOffset = (1 << 15) - 1
static constexpr int kMinCPOffset = -(1 << 15)
static constexpr int kTableSizeBits = 7
static constexpr int kTableSize = 1 << kTableSizeBits
static constexpr int kTableMask = kTableSize - 1
static constexpr int kUseCharactersValue = -1
Protected Member Functions
bool has_backtrack_limit () const
uint32_t backtrack_limit () const
bool can_fallback () const
Private Attributes
bool slow_safe_compiler_
uint32_t backtrack_limit_
bool can_fallback_ = false
GlobalMode global_mode_
Isolate *const isolate_
Zone *const zone_
Detailed Description
Definition at line 29 of file regexp-macro-assembler.h.
Member Enumeration Documentation
GlobalMode
enum v8::internal::RegExpMacroAssembler::GlobalMode
Enumerator
NOT_GLOBAL
GLOBAL_NO_ZERO_LENGTH_CHECK
GLOBAL
GLOBAL_UNICODE
Definition at line 244 of file regexp-macro-assembler.h.
                  {
    NOT_GLOBAL,
    GLOBAL_NO_ZERO_LENGTH_CHECK,
    GLOBAL,
    GLOBAL_UNICODE
  };
IrregexpImplementation
enum v8::internal::RegExpMacroAssembler::IrregexpImplementation
Definition at line 185 of file regexp-macro-assembler.h.
                              {
#define V(Name) k##Name##Implementation,
    IMPLEMENTATIONS_LIST(V)
#undef V
  };
StackCheckFlag
enum v8::internal::RegExpMacroAssembler::StackCheckFlag
Enumerator
kNoStackLimitCheck
kCheckStackLimit
Definition at line 156 of file regexp-macro-assembler.h.
{ kNoStackLimitCheck = false, kCheckStackLimit = true };
Constructor & Destructor Documentation
RegExpMacroAssembler()
v8::internal::RegExpMacroAssembler::RegExpMacroAssembler (Isolate * isolate, Zone * zone)
Definition at line 24 of file regexp-macro-assembler.cc.
    : slow_safe_compiler_(false),
      backtrack_limit_(JSRegExp::kNoBacktrackLimit),
      global_mode_(NOT_GLOBAL),
      isolate_(isolate),
      zone_(zone) {}
 RegExpMacroAssembler()
virtual v8::internal::RegExpMacroAssembler::~RegExpMacroAssembler () [virtual], [default]
Member Function Documentation
AbortedCodeGeneration()
virtual void v8::internal::RegExpMacroAssembler::AbortedCodeGeneration () [inline], [virtual]
Reimplemented in v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Definition at line 52 of file regexp-macro-assembler.h.
{}
Referenced by v8::internal::RegExpMacroAssemblerTracer::AbortedCodeGeneration(), and v8::internal::RegExpCompiler::Assemble().
AdvanceCurrentPosition()
virtual void v8::internal::RegExpMacroAssembler::AdvanceCurrentPosition (int by) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::AdvanceCurrentPosition(), v8::internal::LoopChoiceNode::Emit(), v8::internal::ChoiceNode::EmitFixedLengthLoop(), v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), and v8::internal::Trace::Flush().
AdvanceRegister()
virtual void v8::internal::RegExpMacroAssembler::AdvanceRegister (int reg, int by) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::AdvanceRegister(), and v8::internal::Trace::PerformDeferredActions().
Backtrack()
virtual void v8::internal::RegExpMacroAssembler::Backtrack () [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::Backtrack(), v8::internal::ActionNode::Emit(), v8::internal::NegativeSubmatchSuccess::Emit(), and v8::internal::Trace::Flush().
backtrack_limit()
uint32_t v8::internal::RegExpMacroAssembler::backtrack_limit () const [inline], [protected]
Definition at line 264 of file regexp-macro-assembler.h.
{ return backtrack_limit_; }
References backtrack_limit_.
Referenced by v8::internal::RegExpMacroAssemblerRISCV::Backtrack(), and set_backtrack_limit().
Bind()
virtual void v8::internal::RegExpMacroAssembler::Bind (Label * label) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::AssertionNode::BacktrackIfPrevious(), v8::internal::RegExpMacroAssemblerTracer::Bind(), BindJumpTarget(), v8::internal::FixedLengthLoopState::BindLoopTopLabel(), v8::internal::FixedLengthLoopState::BindStepBackwardsLabel(), CheckNotInSurrogatePair(), v8::internal::ActionNode::Emit(), v8::internal::AssertionNode::Emit(), v8::internal::EndNode::Emit(), v8::internal::NegativeSubmatchSuccess::Emit(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomLetter(), v8::internal::AssertionNode::EmitBoundaryCheck(), v8::internal::ChoiceNode::EmitChoices(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::ChoiceNode::EmitFixedLengthLoop(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat(), v8::internal::ChoiceNode::EmitOutOfLineContinuation(), v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), v8::internal::anonymous_namespace{regexp-compiler.cc}::GenerateBranches(), and v8::internal::RegExpNode::LimitVersions().
BindJumpTarget()
virtual void v8::internal::RegExpMacroAssembler::BindJumpTarget (Label * label) [inline], [virtual]
Reimplemented in v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerX64.
Definition at line 131 of file regexp-macro-assembler.h.
{ Bind(label); }
References Bind().
Referenced by v8::internal::RegExpCompiler::Assemble(), and v8::internal::Trace::Flush().
can_fallback()
bool v8::internal::RegExpMacroAssembler::can_fallback () const [inline], [protected]
Definition at line 266 of file regexp-macro-assembler.h.
{ return can_fallback_; }
References can_fallback_.
Referenced by v8::internal::RegExpBytecodeGenerator::Backtrack(), and v8::internal::RegExpMacroAssemblerRISCV::Backtrack().
CanReadUnaligned()
virtual bool v8::internal::RegExpMacroAssembler::CanReadUnaligned () const [pure virtual]
Implemented in v8::internal::NativeRegExpMacroAssembler, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, and v8::internal::RegExpMacroAssemblerMIPS.
Referenced by v8::internal::ChoiceNode::CalculatePreloadCharacters(), v8::internal::RegExpMacroAssemblerTracer::CanReadUnaligned(), and v8::internal::RegExpNode::EmitQuickCheck().
CaseInsensitiveCompareNonUnicode()
int v8::internal::RegExpMacroAssembler::CaseInsensitiveCompareNonUnicode (Address byte_offset1, Address byte_offset2, size_t byte_length, Isolate * isolate) [static]
Definition at line 36 of file regexp-macro-assembler.cc.
                                                                             {
#ifdef V8_INTL_SUPPORT
  // This function is not allowed to cause a garbage collection.
  // A GC might move the calling generated code and invalidate the
  // return address on the stack.
  DisallowGarbageCollection no_gc;
  DCHECK_EQ(0, byte_length % 2);
  size_t length = byte_length / 2;
  base::uc16* substring1 = reinterpret_cast<base::uc16*>(byte_offset1);
  base::uc16* substring2 = reinterpret_cast<base::uc16*>(byte_offset2);
  for (size_t i = 0; i < length; i++) {
    UChar32 c1 = RegExpCaseFolding::Canonicalize(substring1[i]);
    UChar32 c2 = RegExpCaseFolding::Canonicalize(substring2[i]);
    if (c1 != c2) {
      return 0;
    }
  }
  return 1;
#else
  return CaseInsensitiveCompareUnicode(byte_offset1, byte_offset2, byte_length,
                                       isolate);
#endif
}
References CaseInsensitiveCompareUnicode(), DCHECK_EQ, isolate(), v8::internal::length, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::anonymous_namespace{regexp-interpreter.cc}::BackRefMatchesNoCase().
CaseInsensitiveCompareUnicode()
int v8::internal::RegExpMacroAssembler::CaseInsensitiveCompareUnicode (Address byte_offset1, Address byte_offset2, size_t byte_length, Isolate * isolate) [static]
Definition at line 65 of file regexp-macro-assembler.cc.
                                                                          {
  // This function is not allowed to cause a garbage collection.
  // A GC might move the calling generated code and invalidate the
  // return address on the stack.
  DisallowGarbageCollection no_gc;
  DCHECK_EQ(0, byte_length % 2);
#ifdef V8_INTL_SUPPORT
  int32_t length = static_cast<int32_t>(byte_length >> 1);
  icu::UnicodeString uni_str_1(reinterpret_cast<const char16_t*>(byte_offset1),
                               length);
  return uni_str_1.caseCompare(reinterpret_cast<const char16_t*>(byte_offset2),
                               length, U_FOLD_CASE_DEFAULT) == 0;
#else
  base::uc16* substring1 = reinterpret_cast<base::uc16*>(byte_offset1);
  base::uc16* substring2 = reinterpret_cast<base::uc16*>(byte_offset2);
  size_t length = byte_length >> 1;
  DCHECK_NOT_NULL(isolate);
  unibrow::Mapping<unibrow::Ecma262Canonicalize>* canonicalize =
      isolate->regexp_macro_assembler_canonicalize();
  for (size_t i = 0; i < length; i++) {
    unibrow::uchar c1 = substring1[i];
    unibrow::uchar c2 = substring2[i];
    if (c1 != c2) {
      unibrow::uchar s1[1] = {c1};
      canonicalize->get(c1, '\0', s1);
      if (s1[0] != c2) {
        unibrow::uchar s2[1] = {c2};
        canonicalize->get(c2, '\0', s2);
        if (s1[0] != s2[0]) {
          return 0;
        }
      }
    }
  }
  return 1;
#endif // V8_INTL_SUPPORT
}
References DCHECK_EQ, DCHECK_NOT_NULL, unibrow::Mapping< T, size >::get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, isolate(), v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Isolate::regexp_macro_assembler_canonicalize().
Referenced by v8::internal::anonymous_namespace{regexp-interpreter.cc}::BackRefMatchesNoCase(), and CaseInsensitiveCompareNonUnicode().
CheckAtStart()
virtual void v8::internal::RegExpMacroAssembler::CheckAtStart (int cp_offset, Label * on_at_start) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::AssertionNode::BacktrackIfPrevious(), v8::internal::RegExpMacroAssemblerTracer::CheckAtStart(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat().
CheckBitInTable()
virtual void v8::internal::RegExpMacroAssembler::CheckBitInTable (Handle< ByteArray > table, Label * on_bit_set) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckBitInTable(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitUseLookupTable().
CheckCharacter()
virtual void v8::internal::RegExpMacroAssembler::CheckCharacter (unsigned c, Label * on_equal) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckCharacter(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomLetter(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitDoubleBoundaryTest(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat(), v8::internal::RegExpNode::EmitQuickCheck(), v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitWordCheck().
CheckCharacterAfterAnd()
virtual void v8::internal::RegExpMacroAssembler::CheckCharacterAfterAnd (unsigned c, unsigned and_with, Label * on_equal) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerARM64, v8::internal::RegExpMacroAssemblerARM, and v8::internal::RegExpMacroAssemblerTracer.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckCharacterAfterAnd(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat(), v8::internal::RegExpNode::EmitQuickCheck(), and v8::internal::BoyerMooreLookahead::EmitSkipInstructions().
CheckCharacterGT()
virtual void v8::internal::RegExpMacroAssembler::CheckCharacterGT (base::uc16 limit, Label * on_greater) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckCharacterGT(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitBoundaryTest(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitWordCheck(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::GenerateBranches().
CheckCharacterInRange()
virtual void v8::internal::RegExpMacroAssembler::CheckCharacterInRange (base::uc16 from, base::uc16 to, Label * on_in_range) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckCharacterInRange(), CheckNotInSurrogatePair(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitDoubleBoundaryTest().
CheckCharacterInRangeArray()
virtual bool v8::internal::RegExpMacroAssembler::CheckCharacterInRangeArray (const ZoneList< CharacterRange > * ranges, Label * on_in_range) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckCharacterInRangeArray(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges().
CheckCharacterLT()
virtual void v8::internal::RegExpMacroAssembler::CheckCharacterLT (base::uc16 limit, Label * on_less) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckCharacterLT(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitBoundaryTest(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitWordCheck(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::GenerateBranches().
CheckCharacterNotInRange()
virtual void v8::internal::RegExpMacroAssembler::CheckCharacterNotInRange (base::uc16 from, base::uc16 to, Label * on_not_in_range) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckCharacterNotInRange(), CheckNotInSurrogatePair(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitDoubleBoundaryTest().
CheckCharacterNotInRangeArray()
virtual bool v8::internal::RegExpMacroAssembler::CheckCharacterNotInRangeArray (const ZoneList< CharacterRange > * ranges, Label * on_not_in_range) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckCharacterNotInRangeArray(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges().
CheckFixedLengthLoop()
virtual void v8::internal::RegExpMacroAssembler::CheckFixedLengthLoop (Label * on_tos_equals_current_position) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckFixedLengthLoop(), and v8::internal::ChoiceNode::EmitFixedLengthLoop().
CheckNotAtStart()
virtual void v8::internal::RegExpMacroAssembler::CheckNotAtStart (int cp_offset, Label * on_not_at_start) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckNotAtStart(), and v8::internal::AssertionNode::Emit().
CheckNotBackReference()
virtual void v8::internal::RegExpMacroAssembler::CheckNotBackReference (int start_reg, bool read_backward, Label * on_no_match) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckNotBackReference(), and v8::internal::BackReferenceNode::Emit().
CheckNotBackReferenceIgnoreCase()
virtual void v8::internal::RegExpMacroAssembler::CheckNotBackReferenceIgnoreCase (int start_reg, bool read_backward, bool unicode, Label * on_no_match) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckNotBackReferenceIgnoreCase(), and v8::internal::BackReferenceNode::Emit().
CheckNotCharacter()
virtual void v8::internal::RegExpMacroAssembler::CheckNotCharacter (unsigned c, Label * on_not_equal) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckNotCharacter(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomLetter(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomNonLetter(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitDoubleBoundaryTest(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat(), v8::internal::RegExpNode::EmitQuickCheck(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitSimpleCharacter(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitWordCheck().
CheckNotCharacterAfterAnd()
virtual void v8::internal::RegExpMacroAssembler::CheckNotCharacterAfterAnd (unsigned c, unsigned and_with, Label * on_not_equal) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerARM64, v8::internal::RegExpMacroAssemblerARM, and v8::internal::RegExpMacroAssemblerTracer.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckNotCharacterAfterAnd(), v8::internal::RegExpNode::EmitQuickCheck(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::ShortCutEmitCharacterPair().
CheckNotCharacterAfterMinusAnd()
virtual void v8::internal::RegExpMacroAssembler::CheckNotCharacterAfterMinusAnd (base::uc16 c, base::uc16 minus, base::uc16 and_with, Label * on_not_equal) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, v8::internal::RegExpMacroAssemblerARM, and v8::internal::RegExpMacroAssemblerTracer.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckNotCharacterAfterMinusAnd(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::ShortCutEmitCharacterPair().
CheckNotInSurrogatePair()
void v8::internal::RegExpMacroAssembler::CheckNotInSurrogatePair (int cp_offset, Label * on_failure)
Definition at line 227 of file regexp-macro-assembler.cc.
                                                                      {
  Label ok;
  // Check that current character is not a trail surrogate.
  LoadCurrentCharacter(cp_offset, &ok);
  CheckCharacterNotInRange(kTrailSurrogateStart, kTrailSurrogateEnd, &ok);
  // Check that previous character is not a lead surrogate.
  LoadCurrentCharacter(cp_offset - 1, &ok);
  CheckCharacterInRange(kLeadSurrogateStart, kLeadSurrogateEnd, on_failure);
  Bind(&ok);
}
References Bind(), CheckCharacterInRange(), CheckCharacterNotInRange(), v8::internal::kLeadSurrogateEnd, v8::internal::kLeadSurrogateStart, v8::internal::kTrailSurrogateEnd, v8::internal::kTrailSurrogateStart, and LoadCurrentCharacter().
Referenced by v8::internal::BackReferenceNode::Emit(), and v8::internal::RegExpMacroAssemblerRISCV::GetCode().
CheckPosition()
void v8::internal::RegExpMacroAssembler::CheckPosition (int cp_offset, Label * on_outside_input) [virtual]
Reimplemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Definition at line 239 of file regexp-macro-assembler.cc.
                                                                  {
  LoadCurrentCharacter(cp_offset, on_outside_input, true);
}
References LoadCurrentCharacter().
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckPosition(), v8::internal::AssertionNode::Emit(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), and v8::internal::NativeRegExpMacroAssembler::LoadCurrentCharacterImpl().
CheckSpecialClassRanges()
virtual bool v8::internal::RegExpMacroAssembler::CheckSpecialClassRanges (StandardCharacterSet type, Label * on_no_match) [inline], [virtual]
Reimplemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Definition at line 124 of file regexp-macro-assembler.h.
                                                           {
    return false;
  }
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckSpecialClassRanges(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitWordCheck().
ClearRegisters()
virtual void v8::internal::RegExpMacroAssembler::ClearRegisters (int reg_from, int reg_to) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::ClearRegisters(), v8::internal::ActionNode::Emit(), v8::internal::NegativeSubmatchSuccess::Emit(), v8::internal::Trace::PerformDeferredActions(), and v8::internal::Trace::RestoreAffectedRegisters().
Fail()
virtual void v8::internal::RegExpMacroAssembler::Fail () [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpCompiler::Assemble(), and v8::internal::RegExpMacroAssemblerTracer::Fail().
GetCode()
virtual DirectHandle<HeapObject> v8::internal::RegExpMacroAssembler::GetCode (DirectHandle< String > source, RegExpFlags flags) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpCompiler::Assemble(), and v8::internal::RegExpMacroAssemblerTracer::GetCode().
global()
bool v8::internal::RegExpMacroAssembler::global () const [inline]
Definition at line 253 of file regexp-macro-assembler.h.
{ return global_mode_ != NOT_GLOBAL; }
References global_mode_, and NOT_GLOBAL.
Referenced by v8::internal::Trace::Flush(), v8::internal::RegExpMacroAssemblerRISCV::GetCode(), and v8::internal::RegExpMacroAssemblerRISCV::Succeed().
global_unicode()
bool v8::internal::RegExpMacroAssembler::global_unicode () const [inline]
Definition at line 257 of file regexp-macro-assembler.h.
{ return global_mode_ == GLOBAL_UNICODE; }
References global_mode_, and GLOBAL_UNICODE.
Referenced by v8::internal::RegExpMacroAssemblerRISCV::GetCode().
global_with_zero_length_check()
bool v8::internal::RegExpMacroAssembler::global_with_zero_length_check () const [inline]
Definition at line 254 of file regexp-macro-assembler.h.
                                                    {
    return global_mode_ == GLOBAL || global_mode_ == GLOBAL_UNICODE;
  }
References GLOBAL, global_mode_, and GLOBAL_UNICODE.
Referenced by v8::internal::RegExpMacroAssemblerRISCV::GetCode().
GoTo()
virtual void v8::internal::RegExpMacroAssembler::GoTo (Label * label) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::ActionNode::Emit(), v8::internal::AssertionNode::Emit(), v8::internal::EndNode::Emit(), v8::internal::AssertionNode::EmitBoundaryCheck(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitBoundaryTest(), v8::internal::ChoiceNode::EmitChoices(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitDoubleBoundaryTest(), v8::internal::ChoiceNode::EmitFixedLengthLoop(), v8::internal::ChoiceNode::EmitOutOfLineContinuation(), v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitUseLookupTable(), v8::internal::Trace::Flush(), v8::internal::RegExpMacroAssemblerTracer::GoTo(), v8::internal::FixedLengthLoopState::GoToLoopTopLabel(), v8::internal::RegExpNode::LimitVersions(), and v8::internal::TextNode::TextEmitPass().
has_backtrack_limit()
bool v8::internal::RegExpMacroAssembler::has_backtrack_limit () const [protected]
Definition at line 31 of file regexp-macro-assembler.cc.
                                                     {
  return backtrack_limit_ != JSRegExp::kNoBacktrackLimit;
}
References backtrack_limit_, and v8::internal::JSRegExp::kNoBacktrackLimit.
Referenced by v8::internal::RegExpMacroAssemblerRISCV::Backtrack().
IfRegisterEqPos()
virtual void v8::internal::RegExpMacroAssembler::IfRegisterEqPos (int reg, Label * if_eq) [pure virtual]
Implemented in v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::ActionNode::Emit(), and v8::internal::RegExpMacroAssemblerTracer::IfRegisterEqPos().
IfRegisterGE()
virtual void v8::internal::RegExpMacroAssembler::IfRegisterGE (int reg, int comparand, Label * if_ge) [pure virtual]
Implemented in v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::ChoiceNode::GenerateGuard(), and v8::internal::RegExpMacroAssemblerTracer::IfRegisterGE().
IfRegisterLT()
virtual void v8::internal::RegExpMacroAssembler::IfRegisterLT (int reg, int comparand, Label * if_lt) [pure virtual]
Implemented in v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::ActionNode::Emit(), v8::internal::ChoiceNode::GenerateGuard(), and v8::internal::RegExpMacroAssemblerTracer::IfRegisterLT().
Implementation()
virtual IrregexpImplementation v8::internal::RegExpMacroAssembler::Implementation () [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::Implementation(), and v8::internal::RegExpMacroAssemblerTracer::RegExpMacroAssemblerTracer().
ImplementationToString()
const char* v8::internal::RegExpMacroAssembler::ImplementationToString (IrregexpImplementation impl) [inline]
Definition at line 191 of file regexp-macro-assembler.h.
                                                                         {
    static const char* const kNames[] = {
#define V(Name) #Name,
        IMPLEMENTATIONS_LIST(V)
#undef V
    };
    return kNames[impl];
  }
References wasm::impl(), and IMPLEMENTATIONS_LIST.
Referenced by v8::internal::RegExpMacroAssemblerTracer::RegExpMacroAssemblerTracer().
IsCharacterInRangeArray()
uint32_t v8::internal::RegExpMacroAssembler::IsCharacterInRangeArray (uint32_t current_char, Address raw_byte_array) [static]
Definition at line 183 of file regexp-macro-assembler.cc.
                                                                               {
  // Use uint32_t to avoid complexity around bool return types (which may be
  // optimized to use only the least significant byte).
  static constexpr uint32_t kTrue = 1;
  static constexpr uint32_t kFalse = 0;
  Tagged<FixedUInt16Array> ranges =
      Cast<FixedUInt16Array>(Tagged<Object>(raw_byte_array));
  DCHECK_GE(ranges->length(), 1);
  // Shortcut for fully out of range chars.
  if (current_char < ranges->get(0)) return kFalse;
  if (current_char >= ranges->get(ranges->length() - 1)) {
    // The last range may be open-ended.
    return (ranges->length() % 2) == 0 ? kFalse : kTrue;
  }
  // Binary search for the matching range. `ranges` is encoded as
  // [from0, to0, from1, to1, ..., fromN, toN], or
  // [from0, to0, from1, to1, ..., fromN] (open-ended last interval).
  int mid, lower = 0, upper = ranges->length();
  do {
    mid = lower + (upper - lower) / 2;
    const base::uc16 elem = ranges->get(mid);
    if (current_char < elem) {
      upper = mid;
    } else if (current_char > elem) {
      lower = mid + 1;
    } else {
      DCHECK_EQ(current_char, elem);
      break;
    }
  } while (lower < upper);
  const bool current_char_ge_last_elem = current_char >= ranges->get(mid);
  const int current_range_start_index =
      current_char_ge_last_elem ? mid : mid - 1;
  // Ranges start at even indices and end at odd indices.
  return (current_range_start_index % 2) == 0 ? kTrue : kFalse;
}
References DCHECK_EQ, DCHECK_GE, v8::internal::kFalse, and v8::internal::kTrue.
isolate()
Isolate* v8::internal::RegExpMacroAssembler::isolate () const [inline]
Definition at line 259 of file regexp-macro-assembler.h.
{ return isolate_; }
References isolate_.
Referenced by CaseInsensitiveCompareNonUnicode(), CaseInsensitiveCompareUnicode(), v8::internal::NativeRegExpMacroAssembler::CheckStackGuardState(), v8::internal::AssertionNode::EmitBoundaryCheck(), v8::internal::ChoiceNode::EmitOptimizedUnanchoredSearch(), v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitUseLookupTable(), v8::internal::NativeRegExpMacroAssembler::Execute(), v8::internal::NativeRegExpMacroAssembler::ExecuteForTesting(), v8::internal::RegExpMacroAssemblerTracer::GetCode(), v8::internal::NativeRegExpMacroAssembler::GetOrAddRangeArray(), v8::internal::TextNode::GetQuickCheckDetails(), v8::internal::NativeRegExpMacroAssembler::GrowStack(), v8::internal::NativeRegExpMacroAssembler::Match(), and v8::internal::TextNode::TextEmitPass().
LoadCurrentCharacter()
void v8::internal::RegExpMacroAssembler::LoadCurrentCharacter (int cp_offset, Label * on_end_of_input, bool check_bounds = true, int characters = 1, int eats_at_least = kUseCharactersValue)
Definition at line 244 of file regexp-macro-assembler.cc.
                                                                   {
  // By default, eats_at_least = characters.
  if (eats_at_least == kUseCharactersValue) {
    eats_at_least = characters;
  }
  LoadCurrentCharacterImpl(cp_offset, on_end_of_input, check_bounds, characters,
                           eats_at_least);
}
References kUseCharactersValue, and LoadCurrentCharacterImpl().
Referenced by v8::internal::AssertionNode::BacktrackIfPrevious(), CheckNotInSurrogatePair(), CheckPosition(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomLetter(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomNonLetter(), v8::internal::AssertionNode::EmitBoundaryCheck(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat(), v8::internal::ChoiceNode::EmitOutOfLineContinuation(), v8::internal::RegExpNode::EmitQuickCheck(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitSimpleCharacter(), v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), v8::internal::RegExpMacroAssemblerTracer::LoadCurrentCharacterImpl(), and v8::internal::RegExpMacroAssemblerRISCV::SkipUntilBitInTable().
LoadCurrentCharacterImpl()
virtual void v8::internal::RegExpMacroAssembler::LoadCurrentCharacterImpl (int cp_offset, Label * on_end_of_input, bool check_bounds, int characters, int eats_at_least) [pure virtual]
Implemented in v8::internal::NativeRegExpMacroAssembler, v8::internal::RegExpMacroAssemblerTracer, and v8::internal::RegExpBytecodeGenerator.
Referenced by LoadCurrentCharacter().
PopCurrentPosition()
virtual void v8::internal::RegExpMacroAssembler::PopCurrentPosition () [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::Trace::Flush(), and v8::internal::RegExpMacroAssemblerTracer::PopCurrentPosition().
PopRegister()
virtual void v8::internal::RegExpMacroAssembler::PopRegister (int register_index) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::PopRegister(), and v8::internal::Trace::RestoreAffectedRegisters().
PushBacktrack()
virtual void v8::internal::RegExpMacroAssembler::PushBacktrack (Label * label) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpCompiler::Assemble(), v8::internal::Trace::Flush(), and v8::internal::RegExpMacroAssemblerTracer::PushBacktrack().
PushCurrentPosition()
virtual void v8::internal::RegExpMacroAssembler::PushCurrentPosition () [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::ChoiceNode::EmitFixedLengthLoop(), v8::internal::Trace::Flush(), and v8::internal::RegExpMacroAssemblerTracer::PushCurrentPosition().
PushRegister()
virtual void v8::internal::RegExpMacroAssembler::PushRegister (int register_index, StackCheckFlag check_stack_limit) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::Trace::PerformDeferredActions(), and v8::internal::RegExpMacroAssemblerTracer::PushRegister().
ReadCurrentPositionFromRegister()
virtual void v8::internal::RegExpMacroAssembler::ReadCurrentPositionFromRegister (int reg) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::ActionNode::Emit(), v8::internal::NegativeSubmatchSuccess::Emit(), and v8::internal::RegExpMacroAssemblerTracer::ReadCurrentPositionFromRegister().
ReadStackPointerFromRegister()
virtual void v8::internal::RegExpMacroAssembler::ReadStackPointerFromRegister (int reg) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::ActionNode::Emit(), v8::internal::NegativeSubmatchSuccess::Emit(), and v8::internal::RegExpMacroAssemblerTracer::ReadStackPointerFromRegister().
set_backtrack_limit()
void v8::internal::RegExpMacroAssembler::set_backtrack_limit (uint32_t backtrack_limit) [inline]
Definition at line 235 of file regexp-macro-assembler.h.
                                                     {
    backtrack_limit_ = backtrack_limit;
  }
References backtrack_limit(), and backtrack_limit_.
set_can_fallback()
void v8::internal::RegExpMacroAssembler::set_can_fallback (bool val) [inline]
Definition at line 242 of file regexp-macro-assembler.h.
{ can_fallback_ = val; }
References can_fallback_.
set_global_mode()
void v8::internal::RegExpMacroAssembler::set_global_mode (GlobalMode mode) [inline]
Definition at line 252 of file regexp-macro-assembler.h.
{ global_mode_ = mode; }
References global_mode_, and mode().
set_slow_safe()
void v8::internal::RegExpMacroAssembler::set_slow_safe (bool ssc) [inline]
Definition at line 228 of file regexp-macro-assembler.h.
{ slow_safe_compiler_ = ssc; }
References slow_safe_compiler_.
SetCurrentPositionFromEnd()
virtual void v8::internal::RegExpMacroAssembler::SetCurrentPositionFromEnd (int by) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::RegExpMacroAssemblerTracer::SetCurrentPositionFromEnd().
SetRegister()
virtual void v8::internal::RegExpMacroAssembler::SetRegister (int register_index, int to) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::Trace::PerformDeferredActions(), and v8::internal::RegExpMacroAssemblerTracer::SetRegister().
SkipUntilBitInTable()
virtual void v8::internal::RegExpMacroAssembler::SkipUntilBitInTable (int cp_offset, Handle< ByteArray > table, Handle< ByteArray > nibble_table, int advance_by) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), and v8::internal::RegExpMacroAssemblerTracer::SkipUntilBitInTable().
SkipUntilBitInTableUseSimd()
virtual bool v8::internal::RegExpMacroAssembler::SkipUntilBitInTableUseSimd (int advance_by) [inline], [virtual]
Reimplemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerTracer, and v8::internal::RegExpMacroAssemblerARM64.
Definition at line 115 of file regexp-macro-assembler.h.
{ return false; }
Referenced by v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), and v8::internal::RegExpMacroAssemblerTracer::SkipUntilBitInTableUseSimd().
slow_safe()
bool v8::internal::RegExpMacroAssembler::slow_safe () const [inline]
Definition at line 229 of file regexp-macro-assembler.h.
{ return slow_safe_compiler_; }
References slow_safe_compiler_.
Referenced by v8::internal::NativeRegExpMacroAssembler::CanReadUnaligned().
stack_limit_slack_slot_count()
virtual int v8::internal::RegExpMacroAssembler::stack_limit_slack_slot_count () [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::Trace::PerformDeferredActions(), and v8::internal::RegExpMacroAssemblerTracer::stack_limit_slack_slot_count().
Succeed()
virtual bool v8::internal::RegExpMacroAssembler::Succeed () [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::EndNode::Emit(), and v8::internal::RegExpMacroAssemblerTracer::Succeed().
WriteCurrentPositionToRegister()
virtual void v8::internal::RegExpMacroAssembler::WriteCurrentPositionToRegister (int reg, int cp_offset) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::ActionNode::Emit(), v8::internal::Trace::PerformDeferredActions(), and v8::internal::RegExpMacroAssemblerTracer::WriteCurrentPositionToRegister().
WriteStackPointerToRegister()
virtual void v8::internal::RegExpMacroAssembler::WriteStackPointerToRegister (int reg) [pure virtual]
Implemented in v8::internal::RegExpMacroAssemblerX64, v8::internal::RegExpMacroAssemblerS390, v8::internal::RegExpMacroAssemblerRISCV, v8::internal::RegExpMacroAssemblerTracer, v8::internal::RegExpBytecodeGenerator, v8::internal::RegExpMacroAssemblerPPC, v8::internal::RegExpMacroAssemblerMIPS, v8::internal::RegExpMacroAssemblerLOONG64, v8::internal::RegExpMacroAssemblerIA32, v8::internal::RegExpMacroAssemblerARM64, and v8::internal::RegExpMacroAssemblerARM.
Referenced by v8::internal::ActionNode::Emit(), and v8::internal::RegExpMacroAssemblerTracer::WriteStackPointerToRegister().
zone()
Zone* v8::internal::RegExpMacroAssembler::zone () const [inline]
Definition at line 260 of file regexp-macro-assembler.h.
{ return zone_; }
References zone_.
Referenced by v8::internal::RegExpBytecodeGenerator::GetCode().
Member Data Documentation
backtrack_limit_
uint32_t v8::internal::RegExpMacroAssembler::backtrack_limit_ [private]
Definition at line 270 of file regexp-macro-assembler.h.
Referenced by backtrack_limit(), has_backtrack_limit(), and set_backtrack_limit().
can_fallback_
bool v8::internal::RegExpMacroAssembler::can_fallback_ = false [private]
Definition at line 271 of file regexp-macro-assembler.h.
Referenced by can_fallback(), and set_can_fallback().
global_mode_
GlobalMode v8::internal::RegExpMacroAssembler::global_mode_ [private]
Definition at line 272 of file regexp-macro-assembler.h.
Referenced by global(), global_unicode(), global_with_zero_length_check(), and set_global_mode().
isolate_
Isolate* const v8::internal::RegExpMacroAssembler::isolate_ [private]
Definition at line 273 of file regexp-macro-assembler.h.
Referenced by isolate().
kMaxCaptures
constexpr int v8::internal::RegExpMacroAssembler::kMaxCaptures = (kMaxRegister - 1) / 2 [static], [constexpr]
Definition at line 34 of file regexp-macro-assembler.h.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseBackReferenceIndex(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseOpenParenthesis().
kMaxCPOffset
constexpr int v8::internal::RegExpMacroAssembler::kMaxCPOffset = (1 << 15) - 1 [static], [constexpr]
Definition at line 35 of file regexp-macro-assembler.h.
Referenced by v8::internal::RegExpBytecodeGenerator::AdvanceCurrentPosition(), v8::internal::Trace::AdvanceCurrentPositionInTrace(), v8::internal::TextNode::Emit(), v8::internal::ChoiceNode::FixedLengthLoopLengthForAlternative(), v8::internal::RegExpBytecodeGenerator::LoadCurrentCharacterImpl(), and v8::internal::NativeRegExpMacroAssembler::LoadCurrentCharacterImpl().
kMaxRegister
constexpr int v8::internal::RegExpMacroAssembler::kMaxRegister = kMaxRegisterCount - 1 [static], [constexpr]
Definition at line 33 of file regexp-macro-assembler.h.
Referenced by v8::internal::RegExpBytecodeGenerator::AdvanceRegister(), v8::internal::RegExpCompiler::AllocateRegister(), v8::internal::RegExpBytecodeGenerator::CheckNotBackReference(), v8::internal::RegExpBytecodeGenerator::CheckNotBackReferenceIgnoreCase(), v8::internal::RegExpBytecodeGenerator::IfRegisterEqPos(), v8::internal::RegExpBytecodeGenerator::IfRegisterGE(), v8::internal::RegExpBytecodeGenerator::IfRegisterLT(), v8::internal::RegExpBytecodeGenerator::PopRegister(), v8::internal::RegExpBytecodeGenerator::PushRegister(), v8::internal::RegExpBytecodeGenerator::ReadCurrentPositionFromRegister(), v8::internal::RegExpBytecodeGenerator::ReadStackPointerFromRegister(), v8::internal::RegExpCompiler::RegExpCompiler(), v8::internal::RegExpBytecodeGenerator::SetRegister(), v8::internal::RegExpBytecodeGenerator::WriteCurrentPositionToRegister(), and v8::internal::RegExpBytecodeGenerator::WriteStackPointerToRegister().
kMaxRegisterCount
constexpr int v8::internal::RegExpMacroAssembler::kMaxRegisterCount = (1 << 16) [static], [constexpr]
Definition at line 32 of file regexp-macro-assembler.h.
Referenced by v8::internal::RegExpImpl::Compile(), and v8::internal::anonymous_namespace{regexp-interpreter.cc}::InterpreterRegisters::InterpreterRegisters().
kMinCPOffset
constexpr int v8::internal::RegExpMacroAssembler::kMinCPOffset = -(1 << 15) [static], [constexpr]
Definition at line 36 of file regexp-macro-assembler.h.
Referenced by v8::internal::RegExpBytecodeGenerator::AdvanceCurrentPosition(), v8::internal::ChoiceNode::FixedLengthLoopLengthForAlternative(), v8::internal::RegExpBytecodeGenerator::LoadCurrentCharacterImpl(), and v8::internal::NativeRegExpMacroAssembler::LoadCurrentCharacterImpl().
kTableMask
constexpr int v8::internal::RegExpMacroAssembler::kTableMask = kTableSize - 1 [static], [constexpr]
Definition at line 40 of file regexp-macro-assembler.h.
Referenced by v8::internal::anonymous_namespace{regexp-interpreter.cc}::CheckBitInTable(), v8::internal::RegExpMacroAssemblerTracer::CheckBitInTable(), v8::internal::RegExpMacroAssemblerRISCV::CheckBitInTable(), v8::internal::FrequencyCollator::CountCharacter(), v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitUseLookupTable(), v8::internal::FrequencyCollator::Frequency(), v8::internal::RegExpMacroAssemblerTracer::SkipUntilBitInTable(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::SplitSearchSpace().
kTableSize
constexpr int v8::internal::RegExpMacroAssembler::kTableSize = 1 << kTableSizeBits [static], [constexpr]
Definition at line 39 of file regexp-macro-assembler.h.
Referenced by v8::internal::RegExpMacroAssemblerTracer::CheckBitInTable(), v8::internal::RegExpMacroAssemblerRISCV::CheckBitInTable(), v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), v8::internal::RegExpBytecodeGenerator::EmitSkipTable(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitUseLookupTable(), v8::internal::BoyerMooreLookahead::FindBestInterval(), v8::internal::FrequencyCollator::FrequencyCollator(), v8::internal::RegExpMacroAssemblerTracer::SkipUntilBitInTable(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::SplitSearchSpace().
kTableSizeBits
constexpr int v8::internal::RegExpMacroAssembler::kTableSizeBits = 7 [static], [constexpr]
Definition at line 38 of file regexp-macro-assembler.h.
Referenced by v8::internal::anonymous_namespace{regexp-compiler.cc}::GenerateBranches().
kUseCharactersValue
constexpr int v8::internal::RegExpMacroAssembler::kUseCharactersValue = -1 [static], [constexpr]
Definition at line 42 of file regexp-macro-assembler.h.
Referenced by LoadCurrentCharacter().
slow_safe_compiler_
bool v8::internal::RegExpMacroAssembler::slow_safe_compiler_ [private]
Definition at line 269 of file regexp-macro-assembler.h.
Referenced by set_slow_safe(), and slow_safe().
zone_
Zone* const v8::internal::RegExpMacroAssembler::zone_ [private]
Definition at line 274 of file regexp-macro-assembler.h.
Referenced by zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-macro-assembler.h
/mnt/V8SourceCode/src/regexp/regexp-macro-assembler.cc