v8::internal::RegExpBuiltinsAssembler Class Reference
#include <builtins-regexp-gen.h>
Public Types
using OncePerBatchFunction = std::function< void(TNode< IntPtrT >)>
using OncePerMatchFunction = std::function< void(TNode< RawPtrT >, TNode< Int32T >, TNode< Int32T >)>
using DescriptorIndexNameValue = PrototypeCheckAssembler::DescriptorIndexNameValue
Public Member Functions
RegExpBuiltinsAssembler (compiler::CodeAssemblerState *state)
TNode< Smi > SmiZero ()
TNode< IntPtrT > IntPtrZero ()
TNode< JSRegExpResult > AllocateRegExpResult (TNode< Context > context, TNode< Smi > length, TNode< Smi > index, TNode< String > input, TNode< JSRegExp > regexp, TNode< Number > last_index, TNode< BoolT > has_indices, TNode< FixedArray > *elements_out=nullptr)
TNode< Object > FastLoadLastIndexBeforeSmiCheck (TNode< JSRegExp > regexp)
TNode< Smi > FastLoadLastIndex (TNode< JSRegExp > regexp)
TNode< JSAny > SlowLoadLastIndex (TNode< Context > context, TNode< JSAny > regexp)
void FastStoreLastIndex (TNode< JSRegExp > regexp, TNode< Smi > value)
void SlowStoreLastIndex (TNode< Context > context, TNode< JSAny > regexp, TNode< Object > value)
TNode< Smi > LoadCaptureCount (TNode< RegExpData > data)
TNode< Smi > RegistersForCaptureCount (TNode< Smi > capture_count)
void GetStringPointers (TNode< RawPtrT > string_data, TNode< IntPtrT > offset, TNode< IntPtrT > last_index, TNode< IntPtrT > string_length, String::Encoding encoding, TVariable< RawPtrT > *var_string_start, TVariable< RawPtrT > *var_string_end)
std::pair< TNode< RawPtrT >, TNode< BoolT > > LoadOrAllocateRegExpResultVector (TNode< Smi > register_count)
void FreeRegExpResultVector (TNode< RawPtrT > result_vector, TNode< BoolT > is_dynamic)
TNode< RegExpMatchInfo > InitializeMatchInfoFromRegisters (TNode< Context > context, TNode< RegExpMatchInfo > match_info, TNode< Smi > register_count, TNode< String > subject, TNode< RawPtrT > result_offsets_vector)
TNode< RegExpMatchInfo > RegExpExecInternal_Single (TNode< Context > context, TNode< JSRegExp > regexp, TNode< String > string, TNode< Number > last_index, Label *if_not_matched)
TNode< UintPtrT > RegExpExecInternal (TNode< Context > context, TNode< JSRegExp > regexp, TNode< RegExpData > data, TNode< String > string, TNode< Number > last_index, TNode< RawPtrT > result_offsets_vector, TNode< Int32T > result_offsets_vector_length)
TNode< UintPtrT > RegExpExecAtom (TNode< Context > context, TNode< AtomRegExpData > data, TNode< String > string, TNode< Smi > last_index, TNode< RawPtrT > result_offsets_vector, TNode< Int32T > result_offsets_vector_length)
TNode< IntPtrT > RegExpExecInternal_Batched (TNode< Context > context, TNode< JSRegExp > regexp, TNode< String > subject, TNode< RegExpData > data, const VariableList &merge_vars, OncePerBatchFunction once_per_batch, OncePerMatchFunction once_per_match)
TNode< JSRegExpResult > ConstructNewResultFromMatchInfo (TNode< Context > context, TNode< JSRegExp > regexp, TNode< RegExpMatchInfo > match_info, TNode< String > string, TNode< Number > last_index)
void BranchIfFastRegExp (TNode< Context > context, TNode< HeapObject > object, TNode< Map > map, PrototypeCheckAssembler::Flags prototype_check_flags, std::optional< DescriptorIndexNameValue > additional_property_to_check, Label *if_isunmodified, Label *if_ismodified)
void BranchIfFastRegExpForSearch (TNode< Context > context, TNode< HeapObject > object, Label *if_isunmodified, Label *if_ismodified)
void BranchIfFastRegExpForMatch (TNode< Context > context, TNode< HeapObject > object, Label *if_isunmodified, Label *if_ismodified)
void BranchIfFastRegExp_Strict (TNode< Context > context, TNode< HeapObject > object, Label *if_isunmodified, Label *if_ismodified)
void BranchIfFastRegExp_Permissive (TNode< Context > context, TNode< HeapObject > object, Label *if_isunmodified, Label *if_ismodified)
TNode< BoolT > IsFastRegExpNoPrototype (TNode< Context > context, TNode< Object > object)
TNode< BoolT > IsFastRegExpNoPrototype (TNode< Context > context, TNode< Object > object, TNode< Map > map)
void BranchIfRegExpResult (const TNode< Context > context, const TNode< Object > object, Label *if_isunmodified, Label *if_ismodified)
TNode< String > FlagsGetter (TNode< Context > context, TNode< JSAny > regexp, const bool is_fastpath)
TNode< BoolT > FastFlagGetter (TNode< JSRegExp > regexp, JSRegExp::Flag flag)
TNode< BoolT > FastFlagGetterGlobal (TNode< JSRegExp > regexp)
TNode< BoolT > FastFlagGetterUnicode (TNode< JSRegExp > regexp)
TNode< BoolT > FastFlagGetterUnicodeSets (TNode< JSRegExp > regexp)
TNode< BoolT > SlowFlagGetter (TNode< Context > context, TNode< JSAny > regexp, JSRegExp::Flag flag)
TNode< Object > RegExpInitialize (const TNode< Context > context, const TNode< JSRegExp > regexp, const TNode< Object > maybe_pattern, const TNode< Object > maybe_flags)
TNode< Number > AdvanceStringIndex (TNode< String > string, TNode< Number > index, TNode< BoolT > is_unicode, bool is_fastpath)
TNode< Smi > AdvanceStringIndexFast (TNode< String > string, TNode< Smi > index, TNode< BoolT > is_unicode)
TNode< Smi > AdvanceStringIndexSlow (TNode< String > string, TNode< Number > index, TNode< BoolT > is_unicode)
TNode< JSArray > RegExpPrototypeSplitBody (TNode< Context > context, TNode< JSRegExp > regexp, TNode< String > string, TNode< Smi > limit)
TNode< Union< Null, JSArray > > RegExpMatchGlobal (TNode< Context > context, TNode< JSRegExp > regexp, TNode< String > subject, TNode< RegExpData > data)
TNode< String > AppendStringSlice (TNode< Context > context, TNode< String > to_string, TNode< String > from_string, TNode< Smi > slice_start, TNode< Smi > slice_end)
TNode< String > RegExpReplaceGlobalSimpleString (TNode< Context > context, TNode< JSRegExp > regexp, TNode< String > subject, TNode< RegExpData > data, TNode< String > replace_string)
Additional Inherited Members
Detailed Description
Definition at line 18 of file builtins-regexp-gen.h.
Member Typedef Documentation
DescriptorIndexNameValue
using v8::internal::RegExpBuiltinsAssembler::DescriptorIndexNameValue = PrototypeCheckAssembler::DescriptorIndexNameValue
Definition at line 151 of file builtins-regexp-gen.h.
OncePerBatchFunction
using v8::internal::RegExpBuiltinsAssembler::OncePerBatchFunction = std::function<void(TNode<IntPtrT>)>
Definition at line 111 of file builtins-regexp-gen.h.
OncePerMatchFunction
using v8::internal::RegExpBuiltinsAssembler::OncePerMatchFunction = std::function<void(TNode<RawPtrT>, TNode<Int32T>, TNode<Int32T>)>
Definition at line 112 of file builtins-regexp-gen.h.
Constructor & Destructor Documentation
RegExpBuiltinsAssembler()
v8::internal::RegExpBuiltinsAssembler::RegExpBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 20 of file builtins-regexp-gen.h.
      : CodeStubAssembler(state) {}
Member Function Documentation
AdvanceStringIndex()
TNode< Number > v8::internal::RegExpBuiltinsAssembler::AdvanceStringIndex (TNode< String > string, TNode< Number > index, TNode< BoolT > is_unicode, bool is_fastpath)
Definition at line 1497 of file builtins-regexp-gen.cc.
                      {
  CSA_DCHECK(this, IsNumberNormalized(index));
  if (is_fastpath) CSA_DCHECK(this, TaggedIsPositiveSmi(index));
  // Default to last_index + 1.
  // TODO(pwong): Consider using TrySmiAdd for the fast path to reduce generated
  // code.
  TNode<Number> index_plus_one = NumberInc(index);
  TVARIABLE(Number, var_result, index_plus_one);
  // TODO(v8:9880): Given that we have to convert index from Number to UintPtrT
  // anyway, consider using UintPtrT index to simplify the code below.
  // Advancing the index has some subtle issues involving the distinction
  // between Smis and HeapNumbers. There's three cases:
  // * {index} is a Smi, {index_plus_one} is a Smi. The standard case.
  // * {index} is a Smi, {index_plus_one} overflows into a HeapNumber.
  // In this case we can return the result early, because
  // {index_plus_one} > {string}.length.
  // * {index} is a HeapNumber, {index_plus_one} is a HeapNumber. This can only
  // occur when {index} is outside the Smi range since we normalize
  // explicitly. Again we can return early.
  if (is_fastpath) {
    // Must be in Smi range on the fast path. We control the value of {index}
    // on all call-sites and can never exceed the length of the string.
    static_assert(String::kMaxLength + 2 < Smi::kMaxValue);
    CSA_DCHECK(this, TaggedIsPositiveSmi(index_plus_one));
  }
  Label if_isunicode(this), out(this);
  GotoIfNot(is_unicode, &out);
  // Keep this unconditional (even on the fast path) just to be safe.
  Branch(TaggedIsPositiveSmi(index_plus_one), &if_isunicode, &out,
         BranchHint::kTrue);
  BIND(&if_isunicode);
  {
    TNode<UintPtrT> string_length = Unsigned(LoadStringLengthAsWord(string));
    TNode<UintPtrT> untagged_plus_one =
        Unsigned(SmiUntag(CAST(index_plus_one)));
    GotoIfNot(UintPtrLessThan(untagged_plus_one, string_length), &out,
              GotoHint::kFallthrough);
    TNode<Int32T> lead =
        StringCharCodeAt(string, Unsigned(SmiUntag(CAST(index))));
    GotoIfNot(Word32Equal(Word32And(lead, Int32Constant(0xFC00)),
                          Int32Constant(0xD800)),
              &out, GotoHint::kLabel);
    TNode<Int32T> trail = StringCharCodeAt(string, untagged_plus_one);
    GotoIfNot(Word32Equal(Word32And(trail, Int32Constant(0xFC00)),
                          Int32Constant(0xDC00)),
              &out);
    // At a surrogate pair, return index + 2.
    TNode<Number> index_plus_two = NumberInc(index_plus_one);
    var_result = index_plus_two;
    Goto(&out);
  }
  BIND(&out);
  return var_result.value();
}
References v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::index, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::CodeStubAssembler::IsNumberNormalized(), v8::internal::kFallthrough, v8::internal::kLabel, v8::internal::String::kMaxLength, v8::internal::Smi::kMaxValue, v8::internal::kTrue, v8::internal::CodeStubAssembler::LoadStringLengthAsWord(), v8::internal::CodeStubAssembler::SmiUntag(), v8::internal::CodeStubAssembler::StringCharCodeAt(), v8::internal::CodeStubAssembler::TaggedIsPositiveSmi(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan(), v8::internal::compiler::CodeAssembler::Unsigned(), v8::internal::compiler::CodeAssembler::Word32And(), and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by AdvanceStringIndexFast(), AdvanceStringIndexSlow(), RegExpExecInternal_Batched(), and RegExpPrototypeSplitBody().
AdvanceStringIndexFast()
TNode<Smi> v8::internal::RegExpBuiltinsAssembler::AdvanceStringIndexFast (TNode< String > string, TNode< Smi > index, TNode< BoolT > is_unicode) [inline]
Definition at line 214 of file builtins-regexp-gen.h.
                                                             {
    return CAST(AdvanceStringIndex(string, index, is_unicode, true));
  }
References AdvanceStringIndex(), CAST, and v8::internal::index.
AdvanceStringIndexSlow()
TNode<Smi> v8::internal::RegExpBuiltinsAssembler::AdvanceStringIndexSlow (TNode< String > string, TNode< Number > index, TNode< BoolT > is_unicode) [inline]
Definition at line 219 of file builtins-regexp-gen.h.
                                                             {
    return CAST(AdvanceStringIndex(string, index, is_unicode, false));
  }
References AdvanceStringIndex(), CAST, and v8::internal::index.
AllocateRegExpResult()
TNode< JSRegExpResult > v8::internal::RegExpBuiltinsAssembler::AllocateRegExpResult (TNode< Context > context, TNode< Smi > length, TNode< Smi > index, TNode< String > input, TNode< JSRegExp > regexp, TNode< Number > last_index, TNode< BoolT > has_indices, TNode< FixedArray > * elements_out = nullptr)
Definition at line 55 of file builtins-regexp-gen.cc.
                                                               {
  CSA_DCHECK(this, SmiLessThanOrEqual(
                       length, SmiConstant(JSArray::kMaxFastArrayLength)));
  CSA_DCHECK(this, SmiGreaterThan(length, SmiConstant(0)));
  // Allocate.
  Label result_has_indices(this), allocated(this);
  const ElementsKind elements_kind = PACKED_ELEMENTS;
  std::optional<TNode<AllocationSite>> no_gc_site = std::nullopt;
  TNode<IntPtrT> length_intptr = PositiveSmiUntag(length);
  // Note: The returned `var_elements` may be in young large object space, but
  // `var_array` is guaranteed to be in new space so we could skip write
  // barriers below.
  TVARIABLE(JSArray, var_array);
  TVARIABLE(FixedArrayBase, var_elements);
  GotoIf(has_indices, &result_has_indices, GotoHint::kFallthrough);
  {
    TNode<Map> map = CAST(LoadContextElementNoCell(
        LoadNativeContext(context), Context::REGEXP_RESULT_MAP_INDEX));
    std::tie(var_array, var_elements) =
        AllocateUninitializedJSArrayWithElements(
            elements_kind, map, length, no_gc_site, length_intptr,
            AllocationFlag::kNone, JSRegExpResult::kSize);
    Goto(&allocated);
  }
  BIND(&result_has_indices);
  {
    TNode<Map> map = CAST(LoadContextElementNoCell(
        LoadNativeContext(context),
        Context::REGEXP_RESULT_WITH_INDICES_MAP_INDEX));
    std::tie(var_array, var_elements) =
        AllocateUninitializedJSArrayWithElements(
            elements_kind, map, length, no_gc_site, length_intptr,
            AllocationFlag::kNone, JSRegExpResultWithIndices::kSize);
    Goto(&allocated);
  }
  BIND(&allocated);
  // Finish result initialization.
  TNode<JSRegExpResult> result =
      UncheckedCast<JSRegExpResult>(var_array.value());
  // Load undefined value once here to avoid multiple LoadRoots.
  TNode<Oddball> undefined_value = UncheckedCast<Oddball>(
      CodeAssembler::LoadRoot(RootIndex::kUndefinedValue));
  StoreObjectFieldNoWriteBarrier(result, JSRegExpResult::kIndexOffset, index);
  // TODO(jgruber,turbofan): Could skip barrier but the MemoryOptimizer
  // complains.
  StoreObjectField(result, JSRegExpResult::kInputOffset, input);
  StoreObjectFieldNoWriteBarrier(result, JSRegExpResult::kGroupsOffset,
                                 undefined_value);
  StoreObjectFieldNoWriteBarrier(result, JSRegExpResult::kNamesOffset,
                                 undefined_value);
  StoreObjectField(result, JSRegExpResult::kRegexpInputOffset, input);
  // If non-smi last_index then store an SmiZero instead.
  {
    TNode<Smi> last_index_smi = Select<Smi>(
        TaggedIsSmi(last_index), [=, this] { return CAST(last_index); },
        [=, this] { return SmiZero(); });
    StoreObjectField(result, JSRegExpResult::kRegexpLastIndexOffset,
                     last_index_smi);
  }
  Label finish_initialization(this);
  GotoIfNot(has_indices, &finish_initialization, GotoHint::kLabel);
  {
    static_assert(std::is_base_of_v<JSRegExpResult, JSRegExpResultWithIndices>,
                  "JSRegExpResultWithIndices is a subclass of JSRegExpResult");
    StoreObjectFieldNoWriteBarrier(
        result, JSRegExpResultWithIndices::kIndicesOffset, undefined_value);
    Goto(&finish_initialization);
  }
  BIND(&finish_initialization);
  // Finish elements initialization.
  FillFixedArrayWithValue(elements_kind, var_elements.value(), IntPtrZero(),
                          length_intptr, RootIndex::kUndefinedValue);
  if (elements_out) *elements_out = CAST(var_elements.value());
  return result;
}
References v8::internal::CodeStubAssembler::AllocateUninitializedJSArrayWithElements(), CAST, v8::internal::CodeStubAssembler::FillFixedArrayWithValue(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::index, IntPtrZero(), v8::internal::kFallthrough, v8::internal::kLabel, v8::internal::JSArray::kMaxFastArrayLength, v8::internal::CodeStubAssembler::kNone, v8::internal::length, v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::PACKED_ELEMENTS, v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::base::internal::result, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::SmiLessThanOrEqual, SmiZero(), v8::internal::CodeStubAssembler::StoreObjectField(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
Referenced by ConstructNewResultFromMatchInfo().
AppendStringSlice()
TNode< String > v8::internal::RegExpBuiltinsAssembler::AppendStringSlice (TNode< Context > context, TNode< String > to_string, TNode< String > from_string, TNode< Smi > slice_start, TNode< Smi > slice_end)
Definition at line 2094 of file builtins-regexp-gen.cc.
                                                  {
  // TODO(jgruber): Consider inlining this.
  CSA_DCHECK(this, SmiLessThanOrEqual(slice_start, slice_end));
  TNode<String> slice = CAST(CallBuiltin(Builtin::kSubString, context,
                                         from_string, slice_start, slice_end));
  return CAST(
      CallBuiltin(Builtin::kStringAdd_CheckNone, context, to_string, slice));
}
References v8::internal::compiler::CodeAssembler::CallBuiltin(), CAST, and v8::internal::CodeStubAssembler::SmiLessThanOrEqual.
Referenced by RegExpReplaceGlobalSimpleString().
BranchIfFastRegExp()
void v8::internal::RegExpBuiltinsAssembler::BranchIfFastRegExp (TNode< Context > context, TNode< HeapObject > object, TNode< Map > map, PrototypeCheckAssembler::Flags prototype_check_flags, std::optional< DescriptorIndexNameValue > additional_property_to_check, Label * if_isunmodified, Label * if_ismodified)
Definition at line 950 of file builtins-regexp-gen.cc.
                                                  {
  CSA_DCHECK(this, TaggedEqual(LoadMap(object), map));
  GotoIfForceSlowPath(if_ismodified);
  // This should only be needed for String.p.(split||matchAll), but we are
  // conservative here.
  GotoIf(IsRegExpSpeciesProtectorCellInvalid(), if_ismodified,
         GotoHint::kFallthrough);
  TNode<NativeContext> native_context = LoadNativeContext(context);
  TNode<JSFunction> regexp_fun = CAST(
      LoadContextElementNoCell(native_context, Context::REGEXP_FUNCTION_INDEX));
  TNode<Map> initial_map = CAST(
      LoadObjectField(regexp_fun, JSFunction::kPrototypeOrInitialMapOffset));
  TNode<BoolT> has_initialmap = TaggedEqual(map, initial_map);
  GotoIfNot(has_initialmap, if_ismodified, GotoHint::kFallthrough);
  // The smi check is required to omit ToLength(lastIndex) calls with possible
  // user-code execution on the fast path.
  TNode<Object> last_index = FastLoadLastIndexBeforeSmiCheck(CAST(object));
  GotoIfNot(TaggedIsPositiveSmi(last_index), if_ismodified,
            GotoHint::kFallthrough);
  // Verify the prototype.
  TNode<Map> initial_proto_initial_map = CAST(LoadContextElementNoCell(
      native_context, Context::REGEXP_PROTOTYPE_MAP_INDEX));
  DescriptorIndexNameValue properties_to_check[2];
  int property_count = 0;
  properties_to_check[property_count++] = DescriptorIndexNameValue{
      JSRegExp::kExecFunctionDescriptorIndex, RootIndex::kexec_string,
      Context::REGEXP_EXEC_FUNCTION_INDEX};
  if (additional_property_to_check) {
    properties_to_check[property_count++] = *additional_property_to_check;
  }
  PrototypeCheckAssembler prototype_check_assembler(
      state(), prototype_check_flags, native_context, initial_proto_initial_map,
      base::Vector<DescriptorIndexNameValue>(properties_to_check,
                                             property_count));
  TNode<HeapObject> prototype = LoadMapPrototype(map);
  prototype_check_assembler.CheckAndBranch(prototype, if_isunmodified,
                                           if_ismodified);
}
References CAST, v8::internal::PrototypeCheckAssembler::CheckAndBranch(), FastLoadLastIndexBeforeSmiCheck(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::GotoIfForceSlowPath(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::compiler::initial_map, v8::internal::CodeStubAssembler::IsRegExpSpeciesProtectorCellInvalid(), v8::internal::JSRegExp::kExecFunctionDescriptorIndex, v8::internal::kFallthrough, v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapPrototype(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::native_context, v8::internal::prototype, v8::internal::compiler::CodeAssembler::state(), v8::internal::CodeStubAssembler::TaggedEqual(), and v8::internal::CodeStubAssembler::TaggedIsPositiveSmi().
Referenced by BranchIfFastRegExp_Permissive(), BranchIfFastRegExp_Strict(), BranchIfFastRegExpForMatch(), BranchIfFastRegExpForSearch(), and v8::internal::StringBuiltinsAssembler::MaybeCallFunctionAtSymbol().
BranchIfFastRegExp_Permissive()
void v8::internal::RegExpBuiltinsAssembler::BranchIfFastRegExp_Permissive (TNode< Context > context, TNode< HeapObject > object, Label * if_isunmodified, Label * if_ismodified)
Definition at line 1034 of file builtins-regexp-gen.cc.
                          {
  BranchIfFastRegExp(context, object, LoadMap(object),
                     PrototypeCheckAssembler::kCheckFull, std::nullopt,
                     if_isunmodified, if_ismodified);
}
References BranchIfFastRegExp(), v8::internal::PrototypeCheckAssembler::kCheckFull, and v8::internal::CodeStubAssembler::LoadMap().
BranchIfFastRegExp_Strict()
void v8::internal::RegExpBuiltinsAssembler::BranchIfFastRegExp_Strict (TNode< Context > context, TNode< HeapObject > object, Label * if_isunmodified, Label * if_ismodified)
Definition at line 1026 of file builtins-regexp-gen.cc.
                          {
  BranchIfFastRegExp(context, object, LoadMap(object),
                     PrototypeCheckAssembler::kCheckPrototypePropertyConstness,
                     std::nullopt, if_isunmodified, if_ismodified);
}
References BranchIfFastRegExp(), v8::internal::PrototypeCheckAssembler::kCheckPrototypePropertyConstness, and v8::internal::CodeStubAssembler::LoadMap().
BranchIfFastRegExpForMatch()
void v8::internal::RegExpBuiltinsAssembler::BranchIfFastRegExpForMatch (TNode< Context > context, TNode< HeapObject > object, Label * if_isunmodified, Label * if_ismodified)
Definition at line 1014 of file builtins-regexp-gen.cc.
                          {
  BranchIfFastRegExp(
      context, object, LoadMap(object),
      PrototypeCheckAssembler::kCheckPrototypePropertyConstness,
      DescriptorIndexNameValue{JSRegExp::kSymbolMatchFunctionDescriptorIndex,
                               RootIndex::kmatch_symbol,
                               Context::REGEXP_MATCH_FUNCTION_INDEX},
      if_isunmodified, if_ismodified);
}
References BranchIfFastRegExp(), v8::internal::PrototypeCheckAssembler::kCheckPrototypePropertyConstness, v8::internal::JSRegExp::kSymbolMatchFunctionDescriptorIndex, and v8::internal::CodeStubAssembler::LoadMap().
Referenced by v8::internal::TF_BUILTIN().
BranchIfFastRegExpForSearch()
void v8::internal::RegExpBuiltinsAssembler::BranchIfFastRegExpForSearch (TNode< Context > context, TNode< HeapObject > object, Label * if_isunmodified, Label * if_ismodified)
Definition at line 1002 of file builtins-regexp-gen.cc.
                          {
  BranchIfFastRegExp(
      context, object, LoadMap(object),
      PrototypeCheckAssembler::kCheckPrototypePropertyConstness,
      DescriptorIndexNameValue{JSRegExp::kSymbolSearchFunctionDescriptorIndex,
                               RootIndex::ksearch_symbol,
                               Context::REGEXP_SEARCH_FUNCTION_INDEX},
      if_isunmodified, if_ismodified);
}
References BranchIfFastRegExp(), v8::internal::PrototypeCheckAssembler::kCheckPrototypePropertyConstness, v8::internal::JSRegExp::kSymbolSearchFunctionDescriptorIndex, and v8::internal::CodeStubAssembler::LoadMap().
BranchIfRegExpResult()
void v8::internal::RegExpBuiltinsAssembler::BranchIfRegExpResult (const TNode< Context > context, const TNode< Object > object, Label * if_isunmodified, Label * if_ismodified)
Definition at line 1042 of file builtins-regexp-gen.cc.
                                                                         {
  // Could be a Smi.
  const TNode<Map> map = LoadReceiverMap(object);
  const TNode<NativeContext> native_context = LoadNativeContext(context);
  const TNode<Object> initial_regexp_result_map = LoadContextElementNoCell(
      native_context, Context::REGEXP_RESULT_MAP_INDEX);
  Label maybe_result_with_indices(this);
  Branch(TaggedEqual(map, initial_regexp_result_map), if_isunmodified,
         &maybe_result_with_indices, BranchHint::kTrue);
  BIND(&maybe_result_with_indices);
  {
    static_assert(std::is_base_of_v<JSRegExpResult, JSRegExpResultWithIndices>,
                  "JSRegExpResultWithIndices is a subclass of JSRegExpResult");
    const TNode<Object> initial_regexp_result_with_indices_map =
        LoadContextElementNoCell(native_context,
                                 Context::REGEXP_RESULT_WITH_INDICES_MAP_INDEX);
    Branch(TaggedEqual(map, initial_regexp_result_with_indices_map),
           if_isunmodified, if_ismodified);
  }
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::kTrue, v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadReceiverMap(), v8::internal::native_context, and v8::internal::CodeStubAssembler::TaggedEqual().
ConstructNewResultFromMatchInfo()
TNode< JSRegExpResult > v8::internal::RegExpBuiltinsAssembler::ConstructNewResultFromMatchInfo (TNode< Context > context, TNode< JSRegExp > regexp, TNode< RegExpMatchInfo > match_info, TNode< String > string, TNode< Number > last_index)
Definition at line 198 of file builtins-regexp-gen.cc.
                              {
  Label named_captures(this), maybe_build_indices(this), out(this);
  TNode<IntPtrT> num_indices = PositiveSmiUntag(CAST(LoadObjectField(
      match_info, offsetof(RegExpMatchInfo, number_of_capture_registers_))));
  TNode<Smi> num_results = SmiTag(WordShr(num_indices, 1));
  TNode<Smi> start = LoadArrayElement(match_info, IntPtrConstant(0));
  TNode<Smi> end = LoadArrayElement(match_info, IntPtrConstant(1));
  // Calculate the substring of the first match before creating the result array
  // to avoid an unnecessary write barrier storing the first result.
  TNode<String> first =
      CAST(CallBuiltin(Builtin::kSubString, context, string, start, end));
  // Load flags and check if the result object needs to have indices.
  const TNode<Smi> flags =
      CAST(LoadObjectField(regexp, JSRegExp::kFlagsOffset));
  const TNode<BoolT> has_indices = IsSetSmi(flags, JSRegExp::kHasIndices);
  TNode<FixedArray> result_elements;
  TNode<JSRegExpResult> result =
      AllocateRegExpResult(context, num_results, start, string, regexp,
                           last_index, has_indices, &result_elements);
  UnsafeStoreFixedArrayElement(result_elements, 0, first);
  // If no captures exist we can skip named capture handling as well.
  GotoIf(SmiEqual(num_results, SmiConstant(1)), &maybe_build_indices);
  // Store all remaining captures.
  TNode<IntPtrT> limit = num_indices;
  TVARIABLE(IntPtrT, var_from_cursor, IntPtrConstant(2));
  TVARIABLE(IntPtrT, var_to_cursor, IntPtrConstant(1));
  Label loop(this, {&var_from_cursor, &var_to_cursor});
  Goto(&loop);
  BIND(&loop);
  {
    TNode<IntPtrT> from_cursor = var_from_cursor.value();
    TNode<IntPtrT> to_cursor = var_to_cursor.value();
    TNode<Smi> start_cursor = LoadArrayElement(match_info, from_cursor);
    Label next_iter(this);
    GotoIf(SmiEqual(start_cursor, SmiConstant(-1)), &next_iter);
    TNode<IntPtrT> from_cursor_plus1 =
        IntPtrAdd(from_cursor, IntPtrConstant(1));
    TNode<Smi> end_cursor = LoadArrayElement(match_info, from_cursor_plus1);
    TNode<String> capture = CAST(CallBuiltin(Builtin::kSubString, context,
                                             string, start_cursor, end_cursor));
    UnsafeStoreFixedArrayElement(result_elements, to_cursor, capture);
    Goto(&next_iter);
    BIND(&next_iter);
    var_from_cursor = IntPtrAdd(from_cursor, IntPtrConstant(2));
    var_to_cursor = IntPtrAdd(to_cursor, IntPtrConstant(1));
    Branch(UintPtrLessThan(var_from_cursor.value(), limit), &loop,
           &named_captures);
  }
  BIND(&named_captures);
  {
    CSA_DCHECK(this, SmiGreaterThan(num_results, SmiConstant(1)));
    // Preparations for named capture properties. Exit early if the result does
    // not have any named captures to minimize performance impact.
    TNode<RegExpData> data = CAST(LoadTrustedPointerFromObject(
        regexp, JSRegExp::kDataOffset, kRegExpDataIndirectPointerTag));
    // We reach this point only if captures exist, implying that the assigned
    // regexp engine must be able to handle captures.
    CSA_SBXCHECK(this, HasInstanceType(data, IR_REG_EXP_DATA_TYPE));
    // The names fixed array associates names at even indices with a capture
    // index at odd indices.
    TNode<Object> maybe_names =
        LoadObjectField(data, IrRegExpData::kCaptureNameMapOffset);
    GotoIf(TaggedEqual(maybe_names, SmiZero()), &maybe_build_indices,
           GotoHint::kLabel);
    // One or more named captures exist, add a property for each one.
    TNode<FixedArray> names = CAST(maybe_names);
    TNode<IntPtrT> names_length = LoadAndUntagFixedArrayBaseLength(names);
    CSA_DCHECK(this, IntPtrGreaterThan(names_length, IntPtrZero()));
    // Stash names in case we need them to build the indices array later.
    StoreObjectField(result, JSRegExpResult::kNamesOffset, names);
    // Allocate a new object to store the named capture properties.
    // TODO(jgruber): Could be optimized by adding the object map to the heap
    // root list.
    TNode<IntPtrT> num_properties = WordSar(names_length, 1);
    TNode<NativeContext> native_context = LoadNativeContext(context);
    TNode<Map> map = LoadSlowObjectWithNullPrototypeMap(native_context);
    TNode<HeapObject> properties;
    if (V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL) {
      properties = AllocateSwissNameDictionary(num_properties);
    } else {
      properties = AllocateNameDictionary(num_properties);
    }
    TNode<JSObject> group_object = AllocateJSObjectFromMap(map, properties);
    StoreObjectField(result, JSRegExpResult::kGroupsOffset, group_object);
    TVARIABLE(IntPtrT, var_i, IntPtrZero());
    Label inner_loop(this, &var_i);
    Goto(&inner_loop);
    BIND(&inner_loop);
    {
      TNode<IntPtrT> i = var_i.value();
      TNode<IntPtrT> i_plus_1 = IntPtrAdd(i, IntPtrConstant(1));
      TNode<IntPtrT> i_plus_2 = IntPtrAdd(i_plus_1, IntPtrConstant(1));
      TNode<String> name = CAST(LoadFixedArrayElement(names, i));
      TNode<Smi> index = CAST(LoadFixedArrayElement(names, i_plus_1));
      TNode<HeapObject> capture =
          CAST(LoadFixedArrayElement(result_elements, SmiUntag(index)));
      // TODO(v8:8213): For maintainability, we should call a CSA/Torque
      // implementation of CreateDataProperty instead.
      // At this point the spec says to call CreateDataProperty. However, we can
      // skip most of the steps and go straight to adding/updating a dictionary
      // entry because we know a bunch of useful facts:
      // - All keys are non-numeric internalized strings
      // - Receiver has no prototype
      // - Receiver isn't used as a prototype
      // - Receiver isn't any special object like a Promise intrinsic object
      // - Receiver is extensible
      // - Receiver has no interceptors
      Label add_dictionary_property_slow(this, Label::kDeferred);
      TVARIABLE(IntPtrT, var_name_index);
      Label add_name_entry(this, &var_name_index),
          duplicate_name(this, &var_name_index), next(this);
      NameDictionaryLookup<PropertyDictionary>(
          CAST(properties), name, &duplicate_name, &var_name_index,
          &add_name_entry, kFindExistingOrInsertionIndex);
      BIND(&duplicate_name);
      GotoIf(IsUndefined(capture), &next);
      CSA_DCHECK(this,
                 TaggedEqual(LoadValueByKeyIndex<PropertyDictionary>(
                                 CAST(properties), var_name_index.value()),
                             UndefinedConstant()));
      StoreValueByKeyIndex<PropertyDictionary>(CAST(properties),
                                               var_name_index.value(), capture);
      Goto(&next);
      BIND(&add_name_entry);
      AddToDictionary<PropertyDictionary>(CAST(properties), name, capture,
                                          &add_dictionary_property_slow,
                                          var_name_index.value());
      Goto(&next);
      BIND(&next);
      var_i = i_plus_2;
      Branch(IntPtrGreaterThanOrEqual(var_i.value(), names_length),
             &maybe_build_indices, &inner_loop);
      BIND(&add_dictionary_property_slow);
      // If the dictionary needs resizing, the above Add call will jump here
      // before making any changes. This shouldn't happen because we allocated
      // the dictionary with enough space above.
      Unreachable();
    }
  }
  // Build indices if needed (i.e. if the /d flag is present) after named
  // capture groups are processed.
  BIND(&maybe_build_indices);
  GotoIfNot(has_indices, &out, GotoHint::kLabel);
  {
    const TNode<Object> maybe_names =
        LoadObjectField(result, JSRegExpResultWithIndices::kNamesOffset);
    const TNode<JSRegExpResultIndices> indices =
        UncheckedCast<JSRegExpResultIndices>(
            CallRuntime(Runtime::kRegExpBuildIndices, context, regexp,
                        match_info, maybe_names));
    StoreObjectField(result, JSRegExpResultWithIndices::kIndicesOffset,
                     indices);
    Goto(&out);
  }
  BIND(&out);
  return result;
}
References v8::internal::CodeStubAssembler::AllocateJSObjectFromMap(), v8::internal::CodeStubAssembler::AllocateNameDictionary(), AllocateRegExpResult(), v8::internal::CodeStubAssembler::AllocateSwissNameDictionary(), v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::CallBuiltin(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::compiler::end(), v8::internal::flags, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::HasInstanceType(), v8::internal::index, v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::IntPtrGreaterThanOrEqual, IntPtrZero(), v8::internal::CodeStubAssembler::IsSetSmi(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::kFindExistingOrInsertionIndex, v8::internal::kLabel, v8::internal::CodeStubAssembler::LoadAndUntagFixedArrayBaseLength(), v8::internal::CodeStubAssembler::LoadArrayElement(), v8::internal::CodeStubAssembler::LoadFixedArrayElement(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::CodeStubAssembler::LoadSlowObjectWithNullPrototypeMap(), v8::internal::CodeStubAssembler::LoadTrustedPointerFromObject(), v8::internal::name, v8::internal::native_context, v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::base::internal::result, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::SmiUntag(), SmiZero(), v8::internal::CodeStubAssembler::StoreObjectField(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::compiler::CodeAssembler::Unreachable(), v8::internal::CodeStubAssembler::UnsafeStoreFixedArrayElement(), V8_ENABLE_SWISS_NAME_DICTIONARY_BOOL, v8::internal::compiler::CodeAssembler::WordSar(), and v8::internal::compiler::CodeAssembler::WordShr().
FastFlagGetter()
TNode< BoolT > v8::internal::RegExpBuiltinsAssembler::FastFlagGetter (TNode< JSRegExp > regexp, JSRegExp::Flag flag)
Definition at line 1488 of file builtins-regexp-gen.cc.
                                                                        {
  TNode<Smi> flags = CAST(LoadObjectField(regexp, JSRegExp::kFlagsOffset));
  TNode<Smi> mask = SmiConstant(flag);
  return ReinterpretCast<BoolT>(SmiToInt32(
      SmiShr(SmiAnd(flags, mask),
             base::bits::CountTrailingZeros(static_cast<int>(flag)))));
}
References CAST, v8::base::bits::CountTrailingZeros(), v8::internal::flags, v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::SmiShr(), and v8::internal::CodeStubAssembler::SmiToInt32().
Referenced by FastFlagGetterGlobal(), FastFlagGetterUnicode(), FastFlagGetterUnicodeSets(), RegExpExecInternal_Batched(), RegExpMatchGlobal(), RegExpPrototypeSplitBody(), RegExpReplaceGlobalSimpleString(), and v8::internal::TF_BUILTIN().
FastFlagGetterGlobal()
TNode<BoolT> v8::internal::RegExpBuiltinsAssembler::FastFlagGetterGlobal (TNode< JSRegExp > regexp) [inline]
Definition at line 194 of file builtins-regexp-gen.h.
                                                            {
    return FastFlagGetter(regexp, JSRegExp::kGlobal);
  }
References FastFlagGetter().
FastFlagGetterUnicode()
TNode<BoolT> v8::internal::RegExpBuiltinsAssembler::FastFlagGetterUnicode (TNode< JSRegExp > regexp) [inline]
Definition at line 197 of file builtins-regexp-gen.h.
                                                             {
    return FastFlagGetter(regexp, JSRegExp::kUnicode);
  }
References FastFlagGetter().
FastFlagGetterUnicodeSets()
TNode<BoolT> v8::internal::RegExpBuiltinsAssembler::FastFlagGetterUnicodeSets (TNode< JSRegExp > regexp) [inline]
Definition at line 200 of file builtins-regexp-gen.h.
                                                                 {
    return FastFlagGetter(regexp, JSRegExp::kUnicodeSets);
  }
References FastFlagGetter().
FastLoadLastIndex()
TNode<Smi> v8::internal::RegExpBuiltinsAssembler::FastLoadLastIndex (TNode< JSRegExp > regexp) [inline]
Definition at line 36 of file builtins-regexp-gen.h.
                                                       {
    return CAST(FastLoadLastIndexBeforeSmiCheck(regexp));
  }
References CAST, and FastLoadLastIndexBeforeSmiCheck().
FastLoadLastIndexBeforeSmiCheck()
TNode< Object > v8::internal::RegExpBuiltinsAssembler::FastLoadLastIndexBeforeSmiCheck (TNode< JSRegExp > regexp)
Definition at line 150 of file builtins-regexp-gen.cc.
                            {
  // Load the in-object field.
  static const int field_offset =
      JSRegExp::kHeaderSize + JSRegExp::kLastIndexFieldIndex * kTaggedSize;
  return LoadObjectField(regexp, field_offset);
}
References v8::internal::JSRegExp::kLastIndexFieldIndex, v8::internal::kTaggedSize, and v8::internal::CodeStubAssembler::LoadObjectField().
Referenced by BranchIfFastRegExp(), FastLoadLastIndex(), and IsFastRegExpNoPrototype().
FastStoreLastIndex()
void v8::internal::RegExpBuiltinsAssembler::FastStoreLastIndex (TNode< JSRegExp > regexp, TNode< Smi > value)
Definition at line 165 of file builtins-regexp-gen.cc.
                                                                   {
  // Store the in-object field.
  static const int field_offset =
      JSRegExp::kHeaderSize + JSRegExp::kLastIndexFieldIndex * kTaggedSize;
  StoreObjectField(regexp, field_offset, value);
}
References v8::internal::JSRegExp::kLastIndexFieldIndex, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::StoreObjectField(), and v8::internal::value.
Referenced by RegExpExecInternal_Batched().
FlagsGetter()
TNode< String > v8::internal::RegExpBuiltinsAssembler::FlagsGetter (TNode< Context > context, TNode< JSAny > regexp, const bool is_fastpath)
Definition at line 1155 of file builtins-regexp-gen.cc.
                                                                     {
  TVARIABLE(String, result);
  Label runtime(this, Label::kDeferred), done(this, &result);
  if (is_fastpath) {
    GotoIfForceSlowPath(&runtime);
  }
  Isolate* isolate = this->isolate();
  const TNode<IntPtrT> int_one = IntPtrConstant(1);
  TVARIABLE(Uint32T, var_length, Uint32Constant(0));
  TVARIABLE(IntPtrT, var_flags);
  // First, count the number of characters we will need and check which flags
  // are set.
  if (is_fastpath) {
    // Refer to JSRegExp's flag property on the fast-path.
    CSA_DCHECK(this, IsJSRegExp(CAST(regexp)));
    const TNode<Smi> flags_smi =
        CAST(LoadObjectField(CAST(regexp), JSRegExp::kFlagsOffset));
    var_flags = SmiUntag(flags_smi);
#define CASE_FOR_FLAG(Lower, Camel, ...) \
  do { \
    Label next(this); \
    GotoIfNot(IsSetWord(var_flags.value(), JSRegExp::k##Camel), &next); \
    var_length = Uint32Add(var_length.value(), Uint32Constant(1)); \
    Goto(&next); \
    BIND(&next); \
  } while (false);
    REGEXP_FLAG_LIST(CASE_FOR_FLAG)
#undef CASE_FOR_FLAG
  } else {
    DCHECK(!is_fastpath);
    // Fall back to GetProperty stub on the slow-path.
    var_flags = IntPtrZero();
#define CASE_FOR_FLAG(NAME, FLAG) \
  do { \
    Label next(this); \
    const TNode<Object> flag = GetProperty(\
        context, regexp, isolate->factory()->InternalizeUtf8String(NAME)); \
    Label if_isflagset(this); \
    BranchIfToBooleanIsTrue(flag, &if_isflagset, &next); \
    BIND(&if_isflagset); \
    var_length = Uint32Add(var_length.value(), Uint32Constant(1)); \
    var_flags = Signed(WordOr(var_flags.value(), IntPtrConstant(FLAG))); \
    Goto(&next); \
    BIND(&next); \
  } while (false)
    CASE_FOR_FLAG("hasIndices", JSRegExp::kHasIndices);
    CASE_FOR_FLAG("global", JSRegExp::kGlobal);
    CASE_FOR_FLAG("ignoreCase", JSRegExp::kIgnoreCase);
    CASE_FOR_FLAG("multiline", JSRegExp::kMultiline);
    CASE_FOR_FLAG("dotAll", JSRegExp::kDotAll);
    CASE_FOR_FLAG("unicode", JSRegExp::kUnicode);
    CASE_FOR_FLAG("sticky", JSRegExp::kSticky);
    CASE_FOR_FLAG("unicodeSets", JSRegExp::kUnicodeSets);
#undef CASE_FOR_FLAG
#define CASE_FOR_FLAG(NAME, V8_FLAG_EXTERN_REF, FLAG) \
  do { \
    Label next(this); \
    TNode<Word32T> flag_value = UncheckedCast<Word32T>(\
        Load(MachineType::Uint8(), ExternalConstant(V8_FLAG_EXTERN_REF))); \
    GotoIf(Word32Equal(Word32And(flag_value, Int32Constant(0xFF)), \
                       Int32Constant(0)), \
           &next); \
    const TNode<Object> flag = GetProperty(\
        context, regexp, isolate->factory()->InternalizeUtf8String(NAME)); \
    Label if_isflagset(this); \
    BranchIfToBooleanIsTrue(flag, &if_isflagset, &next); \
    BIND(&if_isflagset); \
    var_length = Uint32Add(var_length.value(), Uint32Constant(1)); \
    var_flags = Signed(WordOr(var_flags.value(), IntPtrConstant(FLAG))); \
    Goto(&next); \
    BIND(&next); \
  } while (false)
    CASE_FOR_FLAG(
        "linear",
        ExternalReference::address_of_enable_experimental_regexp_engine(),
        JSRegExp::kLinear);
#undef CASE_FOR_FLAG
  }
  // Allocate a string of the required length and fill it with the
  // corresponding char for each set flag.
  {
    const TNode<SeqOneByteString> string =
        CAST(AllocateSeqOneByteString(var_length.value()));
    TVARIABLE(IntPtrT, var_offset,
              IntPtrSub(FieldSliceSeqOneByteStringChars(string).offset,
                        IntPtrConstant(1)));
#define CASE_FOR_FLAG(Lower, Camel, LowerCamel, Char, ...) \
  do { \
    Label next(this); \
    GotoIfNot(IsSetWord(var_flags.value(), JSRegExp::k##Camel), &next); \
    const TNode<Int32T> value = Int32Constant(Char); \
    StoreNoWriteBarrier(MachineRepresentation::kWord8, string, \
                        var_offset.value(), value); \
    var_offset = IntPtrAdd(var_offset.value(), int_one); \
    Goto(&next); \
    BIND(&next); \
  } while (false);
    REGEXP_FLAG_LIST(CASE_FOR_FLAG)
#undef CASE_FOR_FLAG
    if (is_fastpath) {
      result = string;
      Goto(&done);
      BIND(&runtime);
      {
        result =
            CAST(CallRuntime(Runtime::kRegExpStringFromFlags, context, regexp));
        Goto(&done);
      }
      BIND(&done);
      return result.value();
    } else {
      return string;
    }
  }
}
References v8::internal::CodeStubAssembler::AllocateSeqOneByteString(), v8::internal::compiler::CodeAssembler::CallRuntime(), CASE_FOR_FLAG, CAST, v8::internal::DCHECK(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::CodeStubAssembler::GotoIfForceSlowPath(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrSub(), IntPtrZero(), v8::internal::CodeStubAssembler::IsJSRegExp(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadObjectField(), REGEXP_FLAG_LIST, v8::base::internal::result, v8::internal::CodeStubAssembler::SmiUntag(), v8::internal::string, and v8::internal::compiler::CodeAssembler::Uint32Constant().
FreeRegExpResultVector()
void v8::internal::RegExpBuiltinsAssembler::FreeRegExpResultVector (TNode< RawPtrT > result_vector, TNode< BoolT > is_dynamic)
Definition at line 460 of file builtins-regexp-gen.cc.
                                                           {
  Label if_dynamic(this), out(this);
  GotoIf(is_dynamic, &if_dynamic, GotoHint::kFallthrough);
  // The vector must have been allocated.
  CSA_DCHECK(this, WordNotEqual(result_vector, IntPtrConstant(0)));
  // Return ownership of the static vector.
  auto address_of_regexp_static_result_offsets_vector = ExternalConstant(
      ExternalReference::address_of_regexp_static_result_offsets_vector(
          isolate()));
  CSA_DCHECK(
      this, WordEqual(UncheckedCast<RawPtrT>(
                          Load(MachineType::Pointer(),
                               address_of_regexp_static_result_offsets_vector)),
                      IntPtrConstant(0)));
  StoreNoWriteBarrier(MachineType::PointerRepresentation(),
                      address_of_regexp_static_result_offsets_vector,
                      result_vector);
  Goto(&out);
  BIND(&if_dynamic);
  auto isolate_ptr = ExternalConstant(ExternalReference::isolate_address());
  CallCFunction(
      ExternalConstant(ExternalReference::free_regexp_result_vector()),
      MachineType::Pointer() /* void */,
      std::make_pair(MachineType::Pointer(), isolate_ptr),
      std::make_pair(MachineType::Pointer(), result_vector));
  Goto(&out);
  BIND(&out);
}
References v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::ExternalReference::isolate_address(), v8::internal::kFallthrough, v8::internal::compiler::CodeAssembler::Load(), v8::internal::MachineType::Pointer(), v8::internal::MachineType::PointerRepresentation(), v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier(), v8::internal::compiler::CodeAssembler::WordEqual(), and v8::internal::compiler::CodeAssembler::WordNotEqual().
Referenced by RegExpExecInternal_Batched(), RegExpExecInternal_Single(), and RegExpPrototypeSplitBody().
GetStringPointers()
void v8::internal::RegExpBuiltinsAssembler::GetStringPointers (TNode< RawPtrT > string_data, TNode< IntPtrT > offset, TNode< IntPtrT > last_index, TNode< IntPtrT > string_length, String::Encoding encoding, TVariable< RawPtrT > * var_string_start, TVariable< RawPtrT > * var_string_end)
Definition at line 395 of file builtins-regexp-gen.cc.
                                        {
  DCHECK_EQ(var_string_start->rep(), MachineType::PointerRepresentation());
  DCHECK_EQ(var_string_end->rep(), MachineType::PointerRepresentation());
  const ElementsKind kind = (encoding == String::ONE_BYTE_ENCODING)
                                ? UINT8_ELEMENTS
                                : UINT16_ELEMENTS;
  TNode<IntPtrT> from_offset =
      ElementOffsetFromIndex(IntPtrAdd(offset, last_index), kind);
  *var_string_start =
      ReinterpretCast<RawPtrT>(IntPtrAdd(string_data, from_offset));
  TNode<IntPtrT> to_offset =
      ElementOffsetFromIndex(IntPtrAdd(offset, string_length), kind);
  *var_string_end = ReinterpretCast<RawPtrT>(IntPtrAdd(string_data, to_offset));
}
References DCHECK_EQ, v8::internal::CodeStubAssembler::ElementOffsetFromIndex(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::String::ONE_BYTE_ENCODING, v8::internal::MachineType::PointerRepresentation(), v8::internal::compiler::CodeAssemblerVariable::rep(), v8::internal::maglev::UINT16_ELEMENTS, and v8::internal::maglev::UINT8_ELEMENTS.
Referenced by RegExpExecInternal().
InitializeMatchInfoFromRegisters()
TNode< RegExpMatchInfo > v8::internal::RegExpBuiltinsAssembler::InitializeMatchInfoFromRegisters (TNode< Context > context, TNode< RegExpMatchInfo > match_info, TNode< Smi > register_count, TNode< String > subject, TNode< RawPtrT > result_offsets_vector)
Definition at line 503 of file builtins-regexp-gen.cc.
                                          {
  TVARIABLE(RegExpMatchInfo, var_match_info, match_info);
  // Check that the last match info has space for the capture registers.
  {
    Label next(this);
    TNode<Smi> available_slots = LoadSmiArrayLength(var_match_info.value());
    GotoIf(SmiLessThanOrEqual(register_count, available_slots), &next,
           GotoHint::kLabel);
    // Grow.
    var_match_info =
        CAST(CallRuntime(Runtime::kRegExpGrowRegExpMatchInfo, context,
                         var_match_info.value(), register_count));
    Goto(&next);
    BIND(&next);
  }
  // Fill match_info.
  StoreObjectField(var_match_info.value(),
                   offsetof(RegExpMatchInfo, number_of_capture_registers_),
                   register_count);
  StoreObjectField(var_match_info.value(),
                   offsetof(RegExpMatchInfo, last_subject_), subject);
  StoreObjectField(var_match_info.value(),
                   offsetof(RegExpMatchInfo, last_input_), subject);
  // Fill match and capture offsets in match_info. They are located in the
  // region:
  //
  // result_offsets_vector + 0
  // ...
  // result_offsets_vector + register_count * kInt32Size.
  {
    // The offset within result_offsets_vector.
    TNode<IntPtrT> loop_start = UncheckedCast<IntPtrT>(result_offsets_vector);
    TNode<IntPtrT> loop_end =
        IntPtrAdd(loop_start, SmiUntag(SmiShl(register_count, kInt32SizeLog2)));
    // The offset within RegExpMatchInfo.
    TNode<IntPtrT> to_offset =
        OffsetOfElementAt<RegExpMatchInfo>(SmiConstant(0));
    TVARIABLE(IntPtrT, var_to_offset, to_offset);
    VariableList vars({&var_to_offset}, zone());
    BuildFastLoop<IntPtrT>(
        vars, loop_start, loop_end,
        [&](TNode<IntPtrT> current_register_address) {
          TNode<Int32T> value = UncheckedCast<Int32T>(
              Load(MachineType::Int32(), current_register_address));
          TNode<Smi> smi_value = SmiFromInt32(value);
          StoreNoWriteBarrier(MachineRepresentation::kTagged,
                              var_match_info.value(), var_to_offset.value(),
                              smi_value);
          Increment(&var_to_offset, kTaggedSize);
        },
        kInt32Size, LoopUnrollingMode::kYes, IndexAdvanceMode::kPost);
  }
  return var_match_info.value();
}
References v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::Increment(), v8::internal::MachineType::Int32(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::kInt32Size, v8::internal::anonymous_namespace{builtins-regexp-gen.cc}::kInt32SizeLog2, v8::internal::kLabel, v8::internal::CodeStubAssembler::kPost, v8::internal::kTagged, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::kYes, v8::internal::compiler::CodeAssembler::Load(), v8::internal::CodeStubAssembler::LoadSmiArrayLength(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::CodeStubAssembler::SmiLessThanOrEqual, v8::internal::CodeStubAssembler::SmiShl(), v8::internal::CodeStubAssembler::SmiUntag(), v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectField(), v8::internal::value, and v8::internal::compiler::CodeAssembler::zone().
Referenced by RegExpExecInternal_Batched(), RegExpExecInternal_Single(), and RegExpPrototypeSplitBody().
IntPtrZero()
TNode< IntPtrT > v8::internal::RegExpBuiltinsAssembler::IntPtrZero ()
Definition at line 48 of file builtins-regexp-gen.cc.
                                                   {
  return IntPtrConstant(0);
}
References v8::internal::compiler::CodeAssembler::IntPtrConstant().
Referenced by AllocateRegExpResult(), ConstructNewResultFromMatchInfo(), FlagsGetter(), and RegExpPrototypeSplitBody().
IsFastRegExpNoPrototype() [1/2]
TNode< BoolT > v8::internal::RegExpBuiltinsAssembler::IsFastRegExpNoPrototype (TNode< Context > context, TNode< Object > object)
Definition at line 944 of file builtins-regexp-gen.cc.
                                                  {
  CSA_DCHECK(this, TaggedIsNotSmi(object));
  return IsFastRegExpNoPrototype(context, object, LoadMap(CAST(object)));
}
References CAST, v8::internal::CodeStubAssembler::LoadMap(), and v8::internal::CodeStubAssembler::TaggedIsNotSmi().
IsFastRegExpNoPrototype() [2/2]
TNode< BoolT > v8::internal::RegExpBuiltinsAssembler::IsFastRegExpNoPrototype (TNode< Context > context, TNode< Object > object, TNode< Map > map)
Definition at line 916 of file builtins-regexp-gen.cc.
                                                                  {
  Label out(this);
  TVARIABLE(BoolT, var_result);
  var_result = Int32FalseConstant();
  GotoIfForceSlowPath(&out);
  const TNode<NativeContext> native_context = LoadNativeContext(context);
  const TNode<HeapObject> regexp_fun = CAST(
      LoadContextElementNoCell(native_context, Context::REGEXP_FUNCTION_INDEX));
  const TNode<Object> initial_map =
      LoadObjectField(regexp_fun, JSFunction::kPrototypeOrInitialMapOffset);
  const TNode<BoolT> has_initialmap = TaggedEqual(map, initial_map);
  var_result = has_initialmap;
  GotoIfNot(has_initialmap, &out, GotoHint::kFallthrough);
  // The smi check is required to omit ToLength(lastIndex) calls with possible
  // user-code execution on the fast path.
  TNode<Object> last_index = FastLoadLastIndexBeforeSmiCheck(CAST(object));
  var_result = TaggedIsPositiveSmi(last_index);
  Goto(&out);
  BIND(&out);
  return var_result.value();
}
References CAST, FastLoadLastIndexBeforeSmiCheck(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::CodeStubAssembler::GotoIfForceSlowPath(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::compiler::initial_map, v8::internal::compiler::CodeAssembler::Int32FalseConstant(), v8::internal::kFallthrough, v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::native_context, v8::internal::CodeStubAssembler::TaggedEqual(), and v8::internal::CodeStubAssembler::TaggedIsPositiveSmi().
LoadCaptureCount()
TNode< Smi > v8::internal::RegExpBuiltinsAssembler::LoadCaptureCount (TNode< RegExpData > data)
Definition at line 181 of file builtins-regexp-gen.cc.
                                                                           {
  return Select<Smi>(
      SmiEqual(LoadObjectField<Smi>(data, RegExpData::kTypeTagOffset),
               SmiConstant(RegExpData::Type::ATOM)),
      [=, this] { return SmiConstant(JSRegExp::kAtomCaptureCount); },
      [=, this] {
        return LoadObjectField<Smi>(data, IrRegExpData::kCaptureCountOffset);
      });
}
References v8::internal::RegExpData::ATOM, v8::internal::JSRegExp::kAtomCaptureCount, and v8::internal::compiler::CodeAssembler::SmiConstant().
Referenced by RegExpExecInternal(), RegExpExecInternal_Batched(), RegExpExecInternal_Single(), and RegExpPrototypeSplitBody().
LoadOrAllocateRegExpResultVector()
std::pair< TNode< RawPtrT >, TNode< BoolT > > v8::internal::RegExpBuiltinsAssembler::LoadOrAllocateRegExpResultVector (TNode< Smi > register_count)
Definition at line 418 of file builtins-regexp-gen.cc.
                               {
  Label if_dynamic(this), out(this);
  TVARIABLE(BoolT, var_is_dynamic, Int32FalseConstant());
  TVARIABLE(RawPtrT, var_vector, UncheckedCast<RawPtrT>(IntPtrConstant(0)));
  // Too large?
  GotoIf(SmiAbove(register_count,
                  SmiConstant(Isolate::kJSRegexpStaticOffsetsVectorSize)),
         &if_dynamic, GotoHint::kFallthrough);
  auto address_of_regexp_static_result_offsets_vector = ExternalConstant(
      ExternalReference::address_of_regexp_static_result_offsets_vector(
          isolate()));
  var_vector = UncheckedCast<RawPtrT>(Load(
      MachineType::Pointer(), address_of_regexp_static_result_offsets_vector));
  // Owned by someone else?
  GotoIf(WordEqual(var_vector.value(), IntPtrConstant(0)), &if_dynamic,
         GotoHint::kFallthrough);
  // Take ownership of the static vector. See also:
  // RegExpResultVectorScope::Initialize.
  StoreNoWriteBarrier(MachineType::PointerRepresentation(),
                      address_of_regexp_static_result_offsets_vector,
                      IntPtrConstant(0));
  Goto(&out);
  BIND(&if_dynamic);
  var_is_dynamic = Int32TrueConstant();
  auto isolate_ptr = ExternalConstant(ExternalReference::isolate_address());
  var_vector = UncheckedCast<RawPtrT>(CallCFunction(
      ExternalConstant(ExternalReference::allocate_regexp_result_vector()),
      MachineType::Pointer(),
      std::make_pair(MachineType::Pointer(), isolate_ptr),
      std::make_pair(MachineType::Uint32(), SmiToInt32(register_count))));
  Goto(&out);
  BIND(&out);
  return {var_vector.value(), var_is_dynamic.value()};
}
References v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::Int32FalseConstant(), v8::internal::compiler::CodeAssembler::Int32TrueConstant(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::ExternalReference::isolate_address(), v8::internal::kFallthrough, v8::internal::Isolate::kJSRegexpStaticOffsetsVectorSize, v8::internal::compiler::CodeAssembler::Load(), v8::internal::MachineType::Pointer(), v8::internal::MachineType::PointerRepresentation(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::SmiToInt32(), v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier(), v8::internal::MachineType::Uint32(), and v8::internal::compiler::CodeAssembler::WordEqual().
Referenced by RegExpExecInternal_Batched(), RegExpExecInternal_Single(), and RegExpPrototypeSplitBody().
RegExpExecAtom()
TNode< UintPtrT > v8::internal::RegExpBuiltinsAssembler::RegExpExecAtom (TNode< Context > context, TNode< AtomRegExpData > data, TNode< String > string, TNode< Smi > last_index, TNode< RawPtrT > result_offsets_vector, TNode< Int32T > result_offsets_vector_length)
Definition at line 1068 of file builtins-regexp-gen.cc.
                                                {
  auto f = ExternalConstant(ExternalReference::re_atom_exec_raw());
  auto isolate_ptr = ExternalConstant(ExternalReference::isolate_address());
  auto result = UncheckedCast<IntPtrT>(CallCFunction(
      f, MachineType::IntPtr(),
      std::make_pair(MachineType::Pointer(), isolate_ptr),
      std::make_pair(MachineType::TaggedPointer(), data),
      std::make_pair(MachineType::TaggedPointer(), subject_string),
      std::make_pair(MachineType::Int32(), SmiToInt32(last_index)),
      std::make_pair(MachineType::Pointer(), result_offsets_vector),
      std::make_pair(MachineType::Int32(), result_offsets_vector_length)));
  return Unsigned(result);
}
References v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::MachineType::Int32(), v8::internal::MachineType::IntPtr(), v8::internal::ExternalReference::isolate_address(), v8::internal::MachineType::Pointer(), v8::base::internal::result, v8::internal::CodeStubAssembler::SmiToInt32(), v8::internal::MachineType::TaggedPointer(), and v8::internal::compiler::CodeAssembler::Unsigned().
Referenced by RegExpExecInternal().
RegExpExecInternal()
TNode< UintPtrT > v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal (TNode< Context > context, TNode< JSRegExp > regexp, TNode< RegExpData > data, TNode< String > string, TNode< Number > last_index, TNode< RawPtrT > result_offsets_vector, TNode< Int32T > result_offsets_vector_length)
Definition at line 625 of file builtins-regexp-gen.cc.
                                                {
  CSA_DCHECK(this, TaggedEqual(data, LoadTrustedPointerFromObject(
                                         regexp, JSRegExp::kDataOffset,
                                         kRegExpDataIndirectPointerTag)));
  ToDirectStringAssembler to_direct(state(), string);
  TVARIABLE(UintPtrT, var_result, UintPtrConstant(0));
  Label out(this), atom(this), runtime(this, Label::kDeferred),
      retry_experimental(this, Label::kDeferred);
  // At this point, last_index is definitely a canonicalized non-negative
  // number, which implies that any non-Smi last_index is greater than
  // the maximal string length. If lastIndex > string.length then the matcher
  // must fail.
  CSA_DCHECK(this, IsNumberNormalized(last_index));
  CSA_DCHECK(this, IsNumberPositive(last_index));
  GotoIf(TaggedIsNotSmi(last_index), &out, GotoHint::kFallthrough);
  TNode<IntPtrT> int_string_length = LoadStringLengthAsWord(string);
  TNode<IntPtrT> int_last_index = PositiveSmiUntag(CAST(last_index));
  GotoIf(UintPtrGreaterThan(int_last_index, int_string_length), &out,
         GotoHint::kFallthrough);
  // Unpack the string. Note that due to SlicedString unpacking (which extracts
  // the parent string and offset), it's not valid to replace `string` with the
  // result of ToDirect here. Instead, we rely on in-place flattening done by
  // String::Flatten.
  // TODO(jgruber): Consider changing ToDirectStringAssembler behavior here
  // since this aspect is surprising. The result of `ToDirect` could always
  // equal the input in length and contents. SlicedString unpacking could
  // happen in `TryToSequential`.
  to_direct.ToDirect();
  // Dispatch on the type of the RegExp.
  // Since the type tag is in trusted space, it is safe to interpret
  // RegExpData as IrRegExpData/AtomRegExpData in the respective branches
  // without checks.
  {
    Label next(this), unreachable(this, Label::kDeferred);
    TNode<Int32T> tag =
        SmiToInt32(LoadObjectField<Smi>(data, RegExpData::kTypeTagOffset));
    int32_t values[] = {
        static_cast<uint8_t>(RegExpData::Type::IRREGEXP),
        static_cast<uint8_t>(RegExpData::Type::ATOM),
        static_cast<uint8_t>(RegExpData::Type::EXPERIMENTAL),
    };
    Label* labels[] = {&next, &atom, &next};
    static_assert(arraysize(values) == arraysize(labels));
    Switch(tag, &unreachable, values, labels, arraysize(values));
    BIND(&unreachable);
    Unreachable();
    BIND(&next);
  }
  // Check (number_of_captures + 1) * 2 <= offsets vector size.
  CSA_DCHECK(
      this, SmiLessThanOrEqual(RegistersForCaptureCount(LoadCaptureCount(data)),
                               SmiFromInt32(result_offsets_vector_length)));
  // Load the irregexp code or bytecode object and offsets into the subject
  // string. Both depend on whether the string is one- or two-byte.
  TVARIABLE(RawPtrT, var_string_start);
  TVARIABLE(RawPtrT, var_string_end);
#ifdef V8_ENABLE_SANDBOX
  using kVarCodeT = IndirectPointerHandleT;
#else
  using kVarCodeT = Object;
#endif
  TVARIABLE(kVarCodeT, var_code);
  TVARIABLE(Object, var_bytecode);
  {
    TNode<RawPtrT> direct_string_data = to_direct.PointerToData(&runtime);
    Label next(this), if_isonebyte(this), if_istwobyte(this, Label::kDeferred);
    Branch(to_direct.IsOneByte(), &if_isonebyte, &if_istwobyte);
    BIND(&if_isonebyte);
    {
      GetStringPointers(direct_string_data, to_direct.offset(), int_last_index,
                        int_string_length, String::ONE_BYTE_ENCODING,
                        &var_string_start, &var_string_end);
      var_code =
          LoadObjectField<kVarCodeT>(data, IrRegExpData::kLatin1CodeOffset);
      var_bytecode = LoadObjectField(data, IrRegExpData::kLatin1BytecodeOffset);
      Goto(&next);
    }
    BIND(&if_istwobyte);
    {
      GetStringPointers(direct_string_data, to_direct.offset(), int_last_index,
                        int_string_length, String::TWO_BYTE_ENCODING,
                        &var_string_start, &var_string_end);
      var_code =
          LoadObjectField<kVarCodeT>(data, IrRegExpData::kUc16CodeOffset);
      var_bytecode = LoadObjectField(data, IrRegExpData::kUc16BytecodeOffset);
      Goto(&next);
    }
    BIND(&next);
  }
  // Check that the irregexp code has been generated for the actual string
  // encoding.
#ifdef V8_ENABLE_SANDBOX
  GotoIf(
      Word32Equal(var_code.value(), Int32Constant(kNullIndirectPointerHandle)),
      &runtime);
#else
  GotoIf(TaggedIsSmi(var_code.value()), &runtime);
#endif
  Label if_exception(this, Label::kDeferred);
  {
    IncrementCounter(isolate()->counters()->regexp_entry_native(), 1);
    // Set up args for the final call into generated Irregexp code.
    MachineType type_int32 = MachineType::Int32();
    MachineType type_tagged = MachineType::AnyTagged();
    MachineType type_ptr = MachineType::Pointer();
    // Result: A NativeRegExpMacroAssembler::Result return code.
    MachineType retval_type = type_int32;
    // Argument 0: Original subject string.
    MachineType arg0_type = type_tagged;
    TNode<String> arg0 = string;
    // Argument 1: Previous index.
    MachineType arg1_type = type_int32;
    TNode<Int32T> arg1 = TruncateIntPtrToInt32(int_last_index);
    // Argument 2: Start of string data. This argument is ignored in the
    // interpreter.
    MachineType arg2_type = type_ptr;
    TNode<RawPtrT> arg2 = var_string_start.value();
    // Argument 3: End of string data. This argument is ignored in the
    // interpreter.
    MachineType arg3_type = type_ptr;
    TNode<RawPtrT> arg3 = var_string_end.value();
    // Argument 4: result offsets vector.
    MachineType arg4_type = type_ptr;
    TNode<RawPtrT> arg4 = result_offsets_vector;
    // Argument 5: Number of capture registers.
    MachineType arg5_type = type_int32;
    TNode<Int32T> arg5 = result_offsets_vector_length;
    // Argument 6: Indicate that this is a direct call from JavaScript.
    MachineType arg6_type = type_int32;
    TNode<Int32T> arg6 = Int32Constant(RegExp::CallOrigin::kFromJs);
    // Argument 7: Pass current isolate address.
    TNode<ExternalReference> isolate_address =
        ExternalConstant(ExternalReference::isolate_address());
    MachineType arg7_type = type_ptr;
    TNode<ExternalReference> arg7 = isolate_address;
    // Argument 8: Regular expression data object. This argument is ignored in
    // native irregexp code.
    MachineType arg8_type = type_tagged;
    TNode<IrRegExpData> arg8 = CAST(data);
#ifdef V8_ENABLE_SANDBOX
    TNode<RawPtrT> code_entry = LoadCodeEntryFromIndirectPointerHandle(
        var_code.value(), kRegExpEntrypointTag);
#else
    TNode<Code> code = CAST(var_code.value());
    TNode<RawPtrT> code_entry =
        LoadCodeInstructionStart(code, kRegExpEntrypointTag);
#endif
    // AIX uses function descriptors on CFunction calls. code_entry in this case
    // may also point to a Regex interpreter entry trampoline which does not
    // have a function descriptor. This method is ineffective on other platforms
    // and is equivalent to CallCFunction.
    TNode<Int32T> result =
        UncheckedCast<Int32T>(CallCFunctionWithoutFunctionDescriptor(
            code_entry, retval_type, std::make_pair(arg0_type, arg0),
            std::make_pair(arg1_type, arg1), std::make_pair(arg2_type, arg2),
            std::make_pair(arg3_type, arg3), std::make_pair(arg4_type, arg4),
            std::make_pair(arg5_type, arg5), std::make_pair(arg6_type, arg6),
            std::make_pair(arg7_type, arg7), std::make_pair(arg8_type, arg8)));
    // Check the result.
    TNode<IntPtrT> int_result = ChangeInt32ToIntPtr(result);
    var_result = UncheckedCast<UintPtrT>(int_result);
    static_assert(RegExp::kInternalRegExpSuccess == 1);
    static_assert(RegExp::kInternalRegExpFailure == 0);
    GotoIf(IntPtrGreaterThanOrEqual(
               int_result, IntPtrConstant(RegExp::kInternalRegExpFailure)),
           &out);
    // GotoHint::kLabel since the other two states are 1. unlikely and 2. it's
    // okay to be a bit slower there.
    GotoIf(
        IntPtrEqual(int_result, IntPtrConstant(RegExp::kInternalRegExpRetry)),
        &runtime, GotoHint::kLabel);
    GotoIf(IntPtrEqual(int_result,
                       IntPtrConstant(RegExp::kInternalRegExpException)),
           &if_exception);
    CSA_CHECK(this,
              IntPtrEqual(int_result,
                          IntPtrConstant(
                              RegExp::kInternalRegExpFallbackToExperimental)));
    Goto(&retry_experimental);
  }
  BIND(&if_exception);
  {
// A stack overflow was detected in RegExp code.
#ifdef DEBUG
    TNode<ExternalReference> exception_address =
        ExternalConstant(ExternalReference::Create(
            IsolateAddressId::kExceptionAddress, isolate()));
    TNode<Object> exception = LoadFullTagged(exception_address);
    CSA_DCHECK(this, IsTheHole(exception));
#endif // DEBUG
    CallRuntime(Runtime::kThrowStackOverflow, context);
    Unreachable();
  }
  BIND(&retry_experimental);
  {
    // Set the implicit (untagged) arg.
    auto vector_arg = ExternalConstant(
        ExternalReference::Create(IsolateFieldId::kRegexpExecVectorArgument));
    StoreNoWriteBarrier(MachineType::PointerRepresentation(), vector_arg,
                        result_offsets_vector);
    static_assert(
        Internals::IsValidSmi(Isolate::kJSRegexpStaticOffsetsVectorSize));
    TNode<Smi> result_as_smi = CAST(CallRuntime(
        Runtime::kRegExpExperimentalOneshotExec, context, regexp, string,
        last_index, SmiFromInt32(result_offsets_vector_length)));
    var_result = UncheckedCast<UintPtrT>(SmiUntag(result_as_smi));
#ifdef DEBUG
    StoreNoWriteBarrier(MachineType::PointerRepresentation(), vector_arg,
                        IntPtrConstant(0));
#endif // DEBUG
    Goto(&out);
  }
  BIND(&runtime);
  {
    // Set the implicit (untagged) arg.
    auto vector_arg = ExternalConstant(
        ExternalReference::Create(IsolateFieldId::kRegexpExecVectorArgument));
    StoreNoWriteBarrier(MachineType::PointerRepresentation(), vector_arg,
                        result_offsets_vector);
    static_assert(
        Internals::IsValidSmi(Isolate::kJSRegexpStaticOffsetsVectorSize));
    TNode<Smi> result_as_smi = CAST(
        CallRuntime(Runtime::kRegExpExec, context, regexp, string, last_index,
                    SmiFromInt32(result_offsets_vector_length)));
    var_result = UncheckedCast<UintPtrT>(SmiUntag(result_as_smi));
#ifdef DEBUG
    StoreNoWriteBarrier(MachineType::PointerRepresentation(), vector_arg,
                        IntPtrConstant(0));
#endif // DEBUG
    Goto(&out);
  }
  BIND(&atom);
  {
    var_result =
        RegExpExecAtom(context, CAST(data), string, CAST(last_index),
                       result_offsets_vector, result_offsets_vector_length);
    Goto(&out);
  }
  BIND(&out);
  return var_result.value();
}
References v8::internal::MachineType::AnyTagged(), arraysize, v8::internal::RegExpData::ATOM, v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::CallCFunctionWithoutFunctionDescriptor(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::compiler::CodeAssembler::ChangeInt32ToIntPtr(), code, v8::internal::ExternalReference::Create(), v8::internal::RegExpData::EXPERIMENTAL, v8::internal::compiler::CodeAssembler::ExternalConstant(), GetStringPointers(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::IncrementCounter(), v8::internal::MachineType::Int32(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::CodeStubAssembler::IntPtrGreaterThanOrEqual, v8::internal::RegExpData::IRREGEXP, v8::internal::CodeStubAssembler::IsNumberNormalized(), v8::internal::CodeStubAssembler::IsNumberPositive(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::ExternalReference::isolate_address(), v8::internal::ToDirectStringAssembler::IsOneByte(), v8::internal::Internals::IsValidSmi(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::kFallthrough, v8::internal::RegExp::kInternalRegExpException, v8::internal::RegExp::kInternalRegExpFailure, v8::internal::RegExp::kInternalRegExpFallbackToExperimental, v8::internal::RegExp::kInternalRegExpRetry, v8::internal::RegExp::kInternalRegExpSuccess, v8::internal::Isolate::kJSRegexpStaticOffsetsVectorSize, v8::internal::kLabel, v8::internal::kNullIndirectPointerHandle, v8::internal::kRegExpEntrypointTag, LoadCaptureCount(), v8::internal::CodeStubAssembler::LoadCodeInstructionStart(), v8::internal::compiler::CodeAssembler::LoadFullTagged(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::CodeStubAssembler::LoadStringLengthAsWord(), v8::internal::CodeStubAssembler::LoadTrustedPointerFromObject(), v8::internal::compiler::Object, v8::internal::ToDirectStringAssembler::offset(), v8::internal::String::ONE_BYTE_ENCODING, v8::internal::MachineType::Pointer(), v8::internal::MachineType::PointerRepresentation(), v8::internal::ToDirectStringAssembler::PointerToData(), v8::internal::CodeStubAssembler::PositiveSmiUntag(), RegExpExecAtom(), RegistersForCaptureCount(), v8::base::internal::result, v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::CodeStubAssembler::SmiLessThanOrEqual, v8::internal::CodeStubAssembler::SmiToInt32(), v8::internal::CodeStubAssembler::SmiUntag(), v8::internal::compiler::CodeAssembler::state(), v8::internal::compiler::CodeAssembler::StoreNoWriteBarrier(), v8::internal::string, v8::internal::compiler::CodeAssembler::Switch(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::CodeStubAssembler::TaggedIsNotSmi(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::ToDirectStringAssembler::ToDirect(), v8::internal::CodeStubAssembler::TruncateIntPtrToInt32(), v8::internal::String::TWO_BYTE_ENCODING, v8::internal::compiler::CodeAssembler::UintPtrConstant(), v8::internal::compiler::CodeAssembler::Unreachable(), and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by RegExpExecInternal_Batched(), RegExpExecInternal_Single(), and RegExpPrototypeSplitBody().
RegExpExecInternal_Batched()
TNode< IntPtrT > v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Batched (TNode< Context > context, TNode< JSRegExp > regexp, TNode< String > subject, TNode< RegExpData > data, const VariableList & merge_vars, OncePerBatchFunction once_per_batch, OncePerMatchFunction once_per_match)
Definition at line 1880 of file builtins-regexp-gen.cc.
                                                                              {
  CSA_DCHECK(this, IsFastRegExpPermissive(context, regexp));
  CSA_DCHECK(this, FastFlagGetter(regexp, JSRegExp::kGlobal));
  // This calls into irregexp and loops over the returned result. Roughly:
  //
  // max_matches = .. that fit into the given offsets array;
  // num_matches_in_batch = max_matches;
  // index = 0;
  // while (num_matches_in_batch == max_matches) {
  // num_matches_in_batch = ExecInternal(..., index);
  // for (i = 0; i < num_matches_in_batch; i++) {
  // .. handle match i
  // }
  // index = MaybeAdvanceZeroLength(last_end_index)
  // }
  Label out(this);
  // Exception handling is necessary to free any allocated memory.
  TVARIABLE(Object, var_exception);
  Label if_exception(this, Label::kDeferred);
  // Determine the number of result slots we want and allocate them.
  TNode<Smi> register_count_per_match =
      RegistersForCaptureCount(LoadCaptureCount(data));
  // TODO(jgruber): Consider a different length selection that considers the
  // register count per match and can go higher than the current static offsets
  // size. Could be helpful for patterns that 1. have many captures and 2.
  // match many times in the given string.
  TNode<Smi> result_offsets_vector_length =
      SmiMax(register_count_per_match,
             SmiConstant(Isolate::kJSRegexpStaticOffsetsVectorSize));
  TNode<RawPtrT> result_offsets_vector;
  TNode<BoolT> result_offsets_vector_is_dynamic;
  std::tie(result_offsets_vector, result_offsets_vector_is_dynamic) =
      LoadOrAllocateRegExpResultVector(result_offsets_vector_length);
  TNode<BoolT> is_unicode =
      Word32Or(FastFlagGetter(regexp, JSRegExp::kUnicode),
               FastFlagGetter(regexp, JSRegExp::kUnicodeSets));
  TVARIABLE(IntPtrT, var_last_match_offsets_vector, IntPtrConstant(0));
  TVARIABLE(Int32T, var_start_of_last_match, Int32Constant(0));
  TVARIABLE(Int32T, var_last_index, Int32Constant(0));
  FastStoreLastIndex(regexp, SmiConstant(0));
  TNode<IntPtrT> max_matches_in_batch =
      IntPtrDiv(SmiUntag(result_offsets_vector_length),
                SmiUntag(register_count_per_match));
  // Initialize such that we always enter the loop initially:
  TVARIABLE(IntPtrT, var_num_matches_in_batch, max_matches_in_batch);
  TVARIABLE(IntPtrT, var_num_matches, IntPtrConstant(0));
  // Loop over multiple batch executions:
  VariableList outer_loop_merge_vars(
      {&var_num_matches_in_batch, &var_num_matches, &var_last_index,
       &var_start_of_last_match, &var_last_match_offsets_vector},
      zone());
  outer_loop_merge_vars.insert(outer_loop_merge_vars.end(), merge_vars.begin(),
                               merge_vars.end());
  Label outer_loop(this, outer_loop_merge_vars);
  Label outer_loop_exit(this);
  Goto(&outer_loop);
  BIND(&outer_loop);
  {
    // Loop condition:
    GotoIf(
        IntPtrLessThan(var_num_matches_in_batch.value(), max_matches_in_batch),
        &outer_loop_exit);
    compiler::ScopedExceptionHandler handler(this, &if_exception,
                                             &var_exception);
    var_num_matches_in_batch = UncheckedCast<IntPtrT>(RegExpExecInternal(
        context, regexp, data, subject, SmiFromInt32(var_last_index.value()),
        result_offsets_vector, SmiToInt32(result_offsets_vector_length)));
    GotoIf(IntPtrEqual(var_num_matches_in_batch.value(), IntPtrConstant(0)),
           &outer_loop_exit);
    var_num_matches =
        IntPtrAdd(var_num_matches.value(), var_num_matches_in_batch.value());
    // At least one match was found. Construct the result array.
    //
    // Loop over the current batch of results:
    {
      once_per_batch(var_num_matches_in_batch.value());
      TNode<IntPtrT> register_count_per_match_intptr =
          SmiUntag(register_count_per_match);
      VariableList inner_loop_merge_vars(
          {&var_last_index, &var_start_of_last_match,
           &var_last_match_offsets_vector},
          zone());
      inner_loop_merge_vars.insert(inner_loop_merge_vars.end(),
                                   merge_vars.begin(), merge_vars.end());
      // Has to be IntPtrT for BuildFastLoop.
      TNode<IntPtrT> inner_loop_start =
          UncheckedCast<IntPtrT>(result_offsets_vector);
      TNode<IntPtrT> inner_loop_increment = WordShl(
          register_count_per_match_intptr, IntPtrConstant(kInt32SizeLog2));
      TNode<IntPtrT> inner_loop_end = IntPtrAdd(
          inner_loop_start,
          IntPtrMul(inner_loop_increment, var_num_matches_in_batch.value()));
      TVARIABLE(IntPtrT, var_inner_loop_index);
      BuildFastLoop<IntPtrT>(
          inner_loop_merge_vars, var_inner_loop_index, inner_loop_start,
          inner_loop_end,
          [&](TNode<IntPtrT> current_match_offsets_vector) {
            TNode<Int32T> start = UncheckedCast<Int32T>(
                Load(MachineType::Int32(), current_match_offsets_vector,
                     IntPtrConstant(0)));
            TNode<Int32T> end = UncheckedCast<Int32T>(
                Load(MachineType::Int32(), current_match_offsets_vector,
                     IntPtrConstant(kInt32Size)));
            once_per_match(UncheckedCast<RawPtrT>(current_match_offsets_vector),
                           start, end);
            var_last_match_offsets_vector = current_match_offsets_vector;
            var_start_of_last_match = start;
            var_last_index = end;
          },
          inner_loop_increment, LoopUnrollingMode::kYes,
          IndexAdvanceMode::kPost, IndexAdvanceDirection::kUp);
    }
    GotoIf(
        Word32NotEqual(var_start_of_last_match.value(), var_last_index.value()),
        &outer_loop, GotoHint::kLabel);
    // For zero-length matches we need to run AdvanceStringIndex.
    var_last_index = SmiToInt32(CAST(AdvanceStringIndex(
        subject, SmiFromInt32(var_last_index.value()), is_unicode, true)));
    Goto(&outer_loop);
  }
  BIND(&outer_loop_exit);
  // If there were no matches, just return.
  GotoIf(IntPtrEqual(var_num_matches.value(), IntPtrConstant(0)), &out);
  // Otherwise initialize the last match info and the result JSArray.
  CSA_DCHECK(this, TaggedEqual(context, LoadNativeContext(context)));
  TNode<RegExpMatchInfo> last_match_info = CAST(
      LoadContextElementNoCell(context, Context::REGEXP_LAST_MATCH_INFO_INDEX));
  InitializeMatchInfoFromRegisters(context, last_match_info,
                                   register_count_per_match, subject,
                                   var_last_match_offsets_vector.value());
  Goto(&out);
  BIND(&if_exception);
  FreeRegExpResultVector(result_offsets_vector,
                         result_offsets_vector_is_dynamic);
  CallRuntime(Runtime::kReThrow, context, var_exception.value());
  Unreachable();
  BIND(&out);
  FreeRegExpResultVector(result_offsets_vector,
                         result_offsets_vector_is_dynamic);
  return var_num_matches.value();
}
References AdvanceStringIndex(), v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::ZoneVector< T >::end(), v8::internal::compiler::end(), FastFlagGetter(), FastStoreLastIndex(), FreeRegExpResultVector(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), InitializeMatchInfoFromRegisters(), v8::internal::ZoneVector< T >::insert(), v8::internal::MachineType::Int32(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThan(), v8::internal::compiler::CodeAssembler::IntPtrMul(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::kInt32Size, v8::internal::anonymous_namespace{builtins-regexp-gen.cc}::kInt32SizeLog2, v8::internal::Isolate::kJSRegexpStaticOffsetsVectorSize, v8::internal::kLabel, v8::internal::CodeStubAssembler::kPost, v8::internal::CodeStubAssembler::kUp, v8::internal::CodeStubAssembler::kYes, v8::internal::compiler::CodeAssembler::Load(), LoadCaptureCount(), v8::internal::CodeStubAssembler::LoadNativeContext(), LoadOrAllocateRegExpResultVector(), RegExpExecInternal(), RegistersForCaptureCount(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::CodeStubAssembler::SmiMax(), v8::internal::CodeStubAssembler::SmiToInt32(), v8::internal::CodeStubAssembler::SmiUntag(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::compiler::CodeAssembler::Unreachable(), v8::internal::compiler::CodeAssembler::Word32NotEqual(), v8::internal::compiler::CodeAssembler::Word32Or(), v8::internal::compiler::CodeAssembler::WordShl(), and v8::internal::compiler::CodeAssembler::zone().
Referenced by RegExpMatchGlobal(), and RegExpReplaceGlobalSimpleString().
RegExpExecInternal_Single()
TNode< RegExpMatchInfo > v8::internal::RegExpBuiltinsAssembler::RegExpExecInternal_Single (TNode< Context > context, TNode< JSRegExp > regexp, TNode< String > string, TNode< Number > last_index, Label * if_not_matched)
Definition at line 568 of file builtins-regexp-gen.cc.
                                                     {
  Label out(this), not_matched(this);
  TVARIABLE(RegExpMatchInfo, var_result);
  TNode<RegExpData> data = CAST(LoadTrustedPointerFromObject(
      regexp, JSRegExp::kDataOffset, kRegExpDataIndirectPointerTag));
  TNode<Smi> register_count_per_match =
      RegistersForCaptureCount(LoadCaptureCount(data));
  // Allocate space for one match.
  TNode<Smi> result_offsets_vector_length = register_count_per_match;
  TNode<RawPtrT> result_offsets_vector;
  TNode<BoolT> result_offsets_vector_is_dynamic;
  std::tie(result_offsets_vector, result_offsets_vector_is_dynamic) =
      LoadOrAllocateRegExpResultVector(result_offsets_vector_length);
  // Exception handling is necessary to free any allocated memory.
  TVARIABLE(Object, var_exception);
  Label if_exception(this, Label::kDeferred);
  {
    compiler::ScopedExceptionHandler handler(this, &if_exception,
                                             &var_exception);
    TNode<UintPtrT> num_matches = RegExpExecInternal(
        context, regexp, data, string, last_index, result_offsets_vector,
        SmiToInt32(result_offsets_vector_length));
    GotoIf(IntPtrEqual(num_matches, IntPtrConstant(0)), &not_matched);
    CSA_DCHECK(this, IntPtrEqual(num_matches, IntPtrConstant(1)));
    CSA_DCHECK(this, TaggedEqual(context, LoadNativeContext(context)));
    TNode<RegExpMatchInfo> last_match_info = CAST(LoadContextElementNoCell(
        context, Context::REGEXP_LAST_MATCH_INFO_INDEX));
    var_result = InitializeMatchInfoFromRegisters(
        context, last_match_info, register_count_per_match, string,
        result_offsets_vector);
    Goto(&out);
  }
  BIND(&if_exception);
  FreeRegExpResultVector(result_offsets_vector,
                         result_offsets_vector_is_dynamic);
  CallRuntime(Runtime::kReThrow, context, var_exception.value());
  Unreachable();
  BIND(&not_matched);
  FreeRegExpResultVector(result_offsets_vector,
                         result_offsets_vector_is_dynamic);
  Goto(if_not_matched);
  BIND(&out);
  FreeRegExpResultVector(result_offsets_vector,
                         result_offsets_vector_is_dynamic);
  return var_result.value();
}
References v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, FreeRegExpResultVector(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), InitializeMatchInfoFromRegisters(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, LoadCaptureCount(), v8::internal::CodeStubAssembler::LoadNativeContext(), LoadOrAllocateRegExpResultVector(), v8::internal::CodeStubAssembler::LoadTrustedPointerFromObject(), RegExpExecInternal(), RegistersForCaptureCount(), v8::internal::CodeStubAssembler::SmiToInt32(), v8::internal::CodeStubAssembler::TaggedEqual(), and v8::internal::compiler::CodeAssembler::Unreachable().
RegExpInitialize()
TNode< Object > v8::internal::RegExpBuiltinsAssembler::RegExpInitialize (const TNode< Context > context, const TNode< JSRegExp > regexp, const TNode< Object > maybe_pattern, const TNode< Object > maybe_flags)
Definition at line 1294 of file builtins-regexp-gen.cc.
                                                                        {
  // Normalize pattern.
  const TNode<Object> pattern = Select<Object>(
      IsUndefined(maybe_pattern), [=, this] { return EmptyStringConstant(); },
      [=, this] { return ToString_Inline(context, maybe_pattern); });
  // Normalize flags.
  const TNode<Object> flags = Select<Object>(
      IsUndefined(maybe_flags), [=, this] { return EmptyStringConstant(); },
      [=, this] { return ToString_Inline(context, maybe_flags); });
  // Initialize.
  return CallRuntime(Runtime::kRegExpInitializeAndCompile, context, regexp,
                     pattern, flags);
}
References v8::internal::compiler::CodeAssembler::CallRuntime(), v8::internal::flags, and v8::internal::CodeStubAssembler::ToString_Inline().
RegExpMatchGlobal()
TNode< Union< Null, JSArray > > v8::internal::RegExpBuiltinsAssembler::RegExpMatchGlobal (TNode< Context > context, TNode< JSRegExp > regexp, TNode< String > subject, TNode< RegExpData > data)
Definition at line 2051 of file builtins-regexp-gen.cc.
                            {
  CSA_DCHECK(this, IsFastRegExpPermissive(context, regexp));
  CSA_DCHECK(this, FastFlagGetter(regexp, JSRegExp::kGlobal));
  TVARIABLE((Union<Null, JSArray>), var_result, NullConstant());
  Label out(this);
  GrowableFixedArray array(state());
  VariableList merge_vars(
      {array.var_array(), array.var_length(), array.var_capacity()}, zone());
  TNode<IntPtrT> num_matches = RegExpExecInternal_Batched(
      context, regexp, subject, data, merge_vars,
      [&](TNode<IntPtrT> num_matches_in_batch) {
        array.Reserve(UncheckedCast<IntPtrT>(
            IntPtrAdd(array.length(), num_matches_in_batch)));
      },
      [&](TNode<RawPtrT> match_offsets, TNode<Int32T> match_start,
          TNode<Int32T> match_end) {
        TNode<Smi> start = SmiFromInt32(match_start);
        TNode<Smi> end = SmiFromInt32(match_end);
        // TODO(jgruber): Consider inlining this or at least reducing the number
        // of redundant checks.
        TNode<String> matched_string = CAST(
            CallBuiltin(Builtin::kSubString, context, subject, start, end));
        array.Push(matched_string);
      });
  CSA_DCHECK(this, IntPtrEqual(num_matches, array.length()));
  // No matches, return null.
  GotoIf(IntPtrEqual(num_matches, IntPtrConstant(0)), &out);
  // Otherwise create the JSArray.
  var_result = array.ToJSArray(context);
  Goto(&out);
  BIND(&out);
  return var_result.value();
}
References v8::internal::compiler::CodeAssembler::CallBuiltin(), CAST, v8::internal::compiler::end(), FastFlagGetter(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::GrowableFixedArray::length(), v8::internal::GrowableFixedArray::Push(), RegExpExecInternal_Batched(), v8::internal::GrowableFixedArray::Reserve(), v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::compiler::CodeAssembler::state(), v8::internal::GrowableFixedArray::ToJSArray(), v8::internal::GrowableFixedArray::var_array(), v8::internal::GrowableFixedArray::var_capacity(), v8::internal::GrowableFixedArray::var_length(), and v8::internal::compiler::CodeAssembler::zone().
RegExpPrototypeSplitBody()
TNode< JSArray > v8::internal::RegExpBuiltinsAssembler::RegExpPrototypeSplitBody (TNode< Context > context, TNode< JSRegExp > regexp, TNode< String > string, TNode< Smi > limit)
Definition at line 1611 of file builtins-regexp-gen.cc.
                      {
  CSA_DCHECK(this, IsFastRegExpPermissive(context, regexp));
  CSA_DCHECK(this, Word32BinaryNot(FastFlagGetter(regexp, JSRegExp::kSticky)));
  TNode<IntPtrT> int_limit = SmiUntag(limit);
  const ElementsKind elements_kind = PACKED_ELEMENTS;
  Label done(this);
  Label return_empty_array(this, Label::kDeferred);
  TVARIABLE(JSArray, var_result);
  // Exception handling is necessary to free any allocated memory.
  TVARIABLE(Object, var_exception);
  Label if_exception(this, Label::kDeferred);
  // Allocate the results vector. Allocate space for exactly one result,
  // forcing the engine to return after each match. This is necessary due to
  // the specialized AdvanceStringIndex logic below.
  TNode<RegExpData> data = CAST(LoadTrustedPointerFromObject(
      regexp, JSRegExp::kDataOffset, kRegExpDataIndirectPointerTag));
  TNode<Smi> capture_count = LoadCaptureCount(data);
  TNode<Smi> register_count_per_match = RegistersForCaptureCount(capture_count);
  TNode<RawPtrT> result_offsets_vector;
  TNode<BoolT> result_offsets_vector_is_dynamic;
  std::tie(result_offsets_vector, result_offsets_vector_is_dynamic) =
      LoadOrAllocateRegExpResultVector(register_count_per_match);
  TNode<Int32T> result_offsets_vector_length =
      SmiToInt32(register_count_per_match);
  {
    compiler::ScopedExceptionHandler handler(this, &if_exception,
                                             &var_exception);
    // If the limit is zero, return an empty array.
    GotoIf(SmiEqual(limit, SmiZero()), &return_empty_array);
    TNode<Smi> string_length = LoadStringLengthAsSmi(string);
    // If passed the empty {string}, return either an empty array or a singleton
    // array depending on whether the {regexp} matches.
    {
      Label next(this), if_stringisempty(this, Label::kDeferred);
      Branch(SmiEqual(string_length, SmiZero()), &if_stringisempty, &next,
             BranchHint::kFalse);
      BIND(&if_stringisempty);
      {
        TNode<IntPtrT> num_matches = UncheckedCast<IntPtrT>(RegExpExecInternal(
            context, regexp, data, string, SmiZero(), result_offsets_vector,
            result_offsets_vector_length));
        Label if_matched(this), if_not_matched(this);
        Branch(IntPtrEqual(num_matches, IntPtrConstant(0)), &if_not_matched,
               &if_matched);
        BIND(&if_matched);
        {
          CSA_DCHECK(this, IntPtrEqual(num_matches, IntPtrConstant(1)));
          CSA_DCHECK(this, TaggedEqual(context, LoadNativeContext(context)));
          TNode<RegExpMatchInfo> last_match_info =
              CAST(LoadContextElementNoCell(
                  context, Context::REGEXP_LAST_MATCH_INFO_INDEX));
          InitializeMatchInfoFromRegisters(context, last_match_info,
                                           register_count_per_match, string,
                                           result_offsets_vector);
          Goto(&return_empty_array);
        }
        BIND(&if_not_matched);
        {
          TNode<Smi> length = SmiConstant(1);
          TNode<IntPtrT> capacity = IntPtrConstant(1);
          std::optional<TNode<AllocationSite>> allocation_site = std::nullopt;
          CSA_DCHECK(this, TaggedEqual(context, LoadNativeContext(context)));
          TNode<Map> array_map =
              LoadJSArrayElementsMap(elements_kind, CAST(context));
          var_result = AllocateJSArray(elements_kind, array_map, capacity,
                                       length, allocation_site);
          TNode<FixedArray> fixed_array =
              CAST(LoadElements(var_result.value()));
          UnsafeStoreFixedArrayElement(fixed_array, 0, string);
          Goto(&done);
        }
      }
      BIND(&next);
    }
    // Loop preparations.
    GrowableFixedArray array(state());
    TVARIABLE(Smi, var_last_matched_until, SmiZero());
    TVARIABLE(Smi, var_next_search_from, SmiZero());
    Label loop(this,
               {array.var_array(), array.var_length(), array.var_capacity(),
                &var_last_matched_until, &var_next_search_from}),
        push_suffix_and_out(this), out(this);
    Goto(&loop);
    BIND(&loop);
    {
      TNode<Smi> next_search_from = var_next_search_from.value();
      TNode<Smi> last_matched_until = var_last_matched_until.value();
      // We're done if we've reached the end of the string.
      GotoIf(SmiEqual(next_search_from, string_length), &push_suffix_and_out);
      // Search for the given {regexp}.
      TNode<IntPtrT> num_matches = UncheckedCast<IntPtrT>(RegExpExecInternal(
          context, regexp, data, string, next_search_from,
          result_offsets_vector, result_offsets_vector_length));
      // We're done if no match was found.
      GotoIf(IntPtrEqual(num_matches, IntPtrConstant(0)), &push_suffix_and_out);
      TNode<Int32T> match_from_int32 = UncheckedCast<Int32T>(
          Load(MachineType::Int32(), result_offsets_vector, IntPtrConstant(0)));
      TNode<Smi> match_from = SmiFromInt32(match_from_int32);
      // We're also done if the match is at the end of the string.
      GotoIf(SmiEqual(match_from, string_length), &push_suffix_and_out);
      // Set the LastMatchInfo.
      // TODO(jgruber): We could elide all but the last of these. BUT this is
      // tricky due to how we omit any match at the end of the string, which
      // makes it hard to tell if we're at the 'last match except for
      // empty-match-at-end-of-string'.
      CSA_DCHECK(this, TaggedEqual(context, LoadNativeContext(context)));
      TNode<RegExpMatchInfo> match_info = CAST(LoadContextElementNoCell(
          context, Context::REGEXP_LAST_MATCH_INFO_INDEX));
      match_info = InitializeMatchInfoFromRegisters(
          context, match_info, register_count_per_match, string,
          result_offsets_vector);
      TNode<Smi> match_to = LoadArrayElement(match_info, IntPtrConstant(1));
      // Advance index and continue if the match is empty.
      {
        Label next(this);
        GotoIfNot(SmiEqual(match_to, next_search_from), &next);
        GotoIfNot(SmiEqual(match_to, last_matched_until), &next);
        TNode<BoolT> is_unicode =
            Word32Or(FastFlagGetter(regexp, JSRegExp::kUnicode),
                     FastFlagGetter(regexp, JSRegExp::kUnicodeSets));
        TNode<Number> new_next_search_from =
            AdvanceStringIndex(string, next_search_from, is_unicode, true);
        var_next_search_from = CAST(new_next_search_from);
        Goto(&loop);
        BIND(&next);
      }
      // A valid match was found, add the new substring to the array.
      {
        TNode<Smi> from = last_matched_until;
        TNode<Smi> to = match_from;
        array.Push(CallBuiltin(Builtin::kSubString, context, string, from, to));
        GotoIf(WordEqual(array.length(), int_limit), &out);
      }
      // Add all captures to the array.
      {
        TNode<IntPtrT> int_num_registers =
            PositiveSmiUntag(register_count_per_match);
        TVARIABLE(IntPtrT, var_reg, IntPtrConstant(2));
        Label nested_loop(this, {array.var_array(), array.var_length(),
                                 array.var_capacity(), &var_reg}),
            nested_loop_out(this);
        Branch(IntPtrLessThan(var_reg.value(), int_num_registers), &nested_loop,
               &nested_loop_out);
        BIND(&nested_loop);
        {
          TNode<IntPtrT> reg = var_reg.value();
          TNode<Smi> from = LoadArrayElement(match_info, reg);
          TNode<Smi> to = LoadArrayElement(match_info, reg, 1 * kTaggedSize);
          Label select_capture(this), select_undefined(this), store_value(this);
          TVARIABLE(Object, var_value);
          Branch(SmiEqual(to, SmiConstant(-1)), &select_undefined,
                 &select_capture);
          BIND(&select_capture);
          {
            var_value =
                CallBuiltin(Builtin::kSubString, context, string, from, to);
            Goto(&store_value);
          }
          BIND(&select_undefined);
          {
            var_value = UndefinedConstant();
            Goto(&store_value);
          }
          BIND(&store_value);
          {
            array.Push(var_value.value());
            GotoIf(WordEqual(array.length(), int_limit), &out);
            TNode<IntPtrT> new_reg = IntPtrAdd(reg, IntPtrConstant(2));
            var_reg = new_reg;
            Branch(IntPtrLessThan(new_reg, int_num_registers), &nested_loop,
                   &nested_loop_out);
          }
        }
        BIND(&nested_loop_out);
      }
      var_last_matched_until = match_to;
      var_next_search_from = match_to;
      Goto(&loop);
    }
    BIND(&push_suffix_and_out);
    {
      TNode<Smi> from = var_last_matched_until.value();
      TNode<Smi> to = string_length;
      array.Push(CallBuiltin(Builtin::kSubString, context, string, from, to));
      Goto(&out);
    }
    BIND(&out);
    {
      var_result = array.ToJSArray(context);
      Goto(&done);
    }
    BIND(&return_empty_array);
    {
      TNode<Smi> length = SmiZero();
      TNode<IntPtrT> capacity = IntPtrZero();
      std::optional<TNode<AllocationSite>> allocation_site = std::nullopt;
      CSA_DCHECK(this, TaggedEqual(context, LoadNativeContext(context)));
      TNode<Map> array_map =
          LoadJSArrayElementsMap(elements_kind, CAST(context));
      var_result = AllocateJSArray(elements_kind, array_map, capacity, length,
                                   allocation_site);
      Goto(&done);
    }
  }
  BIND(&if_exception);
  FreeRegExpResultVector(result_offsets_vector,
                         result_offsets_vector_is_dynamic);
  CallRuntime(Runtime::kReThrow, context, var_exception.value());
  Unreachable();
  BIND(&done);
  FreeRegExpResultVector(result_offsets_vector,
                         result_offsets_vector_is_dynamic);
  return var_result.value();
}
References AdvanceStringIndex(), v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::CallBuiltin(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, FastFlagGetter(), FreeRegExpResultVector(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), InitializeMatchInfoFromRegisters(), v8::internal::MachineType::Int32(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThan(), IntPtrZero(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::kFalse, v8::internal::kTaggedSize, v8::internal::GrowableFixedArray::length(), v8::internal::length, v8::internal::compiler::CodeAssembler::Load(), v8::internal::CodeStubAssembler::LoadArrayElement(), LoadCaptureCount(), v8::internal::CodeStubAssembler::LoadElements(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::CodeStubAssembler::LoadNativeContext(), LoadOrAllocateRegExpResultVector(), v8::internal::CodeStubAssembler::LoadStringLengthAsSmi(), v8::internal::CodeStubAssembler::LoadTrustedPointerFromObject(), v8::internal::PACKED_ELEMENTS, v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::internal::GrowableFixedArray::Push(), RegExpExecInternal(), RegistersForCaptureCount(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::CodeStubAssembler::SmiToInt32(), v8::internal::CodeStubAssembler::SmiUntag(), SmiZero(), v8::internal::compiler::CodeAssembler::state(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::GrowableFixedArray::ToJSArray(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::compiler::CodeAssembler::Unreachable(), v8::internal::CodeStubAssembler::UnsafeStoreFixedArrayElement(), v8::internal::GrowableFixedArray::var_array(), v8::internal::GrowableFixedArray::var_capacity(), v8::internal::GrowableFixedArray::var_length(), v8::internal::compiler::CodeAssembler::Word32Or(), and v8::internal::compiler::CodeAssembler::WordEqual().
RegExpReplaceGlobalSimpleString()
TNode< String > v8::internal::RegExpBuiltinsAssembler::RegExpReplaceGlobalSimpleString (TNode< Context > context, TNode< JSRegExp > regexp, TNode< String > subject, TNode< RegExpData > data, TNode< String > replace_string)
Definition at line 2105 of file builtins-regexp-gen.cc.
                                                          {
  CSA_DCHECK(this, IsFastRegExpPermissive(context, regexp));
  CSA_DCHECK(this, FastFlagGetter(regexp, JSRegExp::kGlobal));
  // The replace_string is 'simple' if it doesn't contain a '$' character.
  CSA_SLOW_DCHECK(this,
                  SmiEqual(StringBuiltinsAssembler{state()}.IndexOfDollarChar(
                               context, replace_string),
                           SmiConstant(-1)));
  TNode<Smi> replace_string_length = LoadStringLengthAsSmi(replace_string);
  TVARIABLE(String, var_result, EmptyStringConstant());
  TVARIABLE(Smi, var_last_match_end, SmiConstant(0));
  VariableList merge_vars({&var_result, &var_last_match_end}, zone());
  RegExpExecInternal_Batched(
      context, regexp, subject, data, merge_vars,
      [&](TNode<IntPtrT> num_matches_in_batch) {},
      [&](TNode<RawPtrT> match_offsets, TNode<Int32T> match_start,
          TNode<Int32T> match_end) {
        TNode<Smi> start = SmiFromInt32(match_start);
        TNode<Smi> end = SmiFromInt32(match_end);
        // Append the slice between this and the previous match.
        var_result = AppendStringSlice(context, var_result.value(), subject,
                                       var_last_match_end.value(), start);
        // Append the replace_string.
        {
          Label next(this);
          GotoIf(SmiEqual(replace_string_length, SmiConstant(0)), &next);
          var_result = CAST(CallBuiltin(Builtin::kStringAdd_CheckNone, context,
                                        var_result.value(), replace_string));
          Goto(&next);
          BIND(&next);
        }
        var_last_match_end = end;
      });
  var_result = AppendStringSlice(context, var_result.value(), subject,
                                 var_last_match_end.value(),
                                 LoadStringLengthAsSmi(subject));
  return var_result.value();
}
References AppendStringSlice(), v8::internal::compiler::CodeAssembler::CallBuiltin(), CAST, v8::internal::compiler::end(), FastFlagGetter(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::LoadStringLengthAsSmi(), RegExpExecInternal_Batched(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::SmiFromInt32(), v8::internal::compiler::CodeAssembler::state(), and v8::internal::compiler::CodeAssembler::zone().
RegistersForCaptureCount()
TNode< Smi > v8::internal::RegExpBuiltinsAssembler::RegistersForCaptureCount (TNode< Smi > capture_count)
Definition at line 191 of file builtins-regexp-gen.cc.
                              {
  // See also: JSRegExp::RegistersForCaptureCount.
  static_assert(Internals::IsValidSmi((JSRegExp::kMaxCaptures + 1) * 2));
  return SmiShl(SmiAdd(capture_count, SmiConstant(1)), 1);
}
References v8::internal::Internals::IsValidSmi(), v8::internal::JSRegExp::kMaxCaptures, v8::internal::compiler::CodeAssembler::SmiConstant(), and v8::internal::CodeStubAssembler::SmiShl().
Referenced by RegExpExecInternal(), RegExpExecInternal_Batched(), RegExpExecInternal_Single(), and RegExpPrototypeSplitBody().
SlowFlagGetter()
TNode<BoolT> v8::internal::RegExpBuiltinsAssembler::SlowFlagGetter (TNode< Context > context, TNode< JSAny > regexp, JSRegExp::Flag flag)
SlowLoadLastIndex()
TNode< JSAny > v8::internal::RegExpBuiltinsAssembler::SlowLoadLastIndex (TNode< Context > context, TNode< JSAny > regexp)
Definition at line 158 of file builtins-regexp-gen.cc.
                                                                             {
  return GetProperty(context, regexp, isolate()->factory()->lastIndex_string());
}
References v8::internal::compiler::CodeAssembler::factory(), v8::internal::CodeStubAssembler::GetProperty(), and v8::internal::compiler::CodeAssembler::isolate().
SlowStoreLastIndex()
void v8::internal::RegExpBuiltinsAssembler::SlowStoreLastIndex (TNode< Context > context, TNode< JSAny > regexp, TNode< Object > value)
Definition at line 173 of file builtins-regexp-gen.cc.
                                                                      {
  TNode<String> name =
      HeapConstantNoHole(isolate()->factory()->lastIndex_string());
  SetPropertyStrict(context, regexp, name, value);
}
References v8::internal::compiler::CodeAssembler::factory(), v8::internal::compiler::CodeAssembler::HeapConstantNoHole(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::name, v8::internal::CodeStubAssembler::SetPropertyStrict(), and v8::internal::value.
SmiZero()
TNode< Smi > v8::internal::RegExpBuiltinsAssembler::SmiZero ()
Definition at line 46 of file builtins-regexp-gen.cc.
{ return SmiConstant(0); }
References v8::internal::compiler::CodeAssembler::SmiConstant().
Referenced by AllocateRegExpResult(), ConstructNewResultFromMatchInfo(), and RegExpPrototypeSplitBody().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-regexp-gen.h
/mnt/V8SourceCode/src/builtins/builtins-regexp-gen.cc