v8::UnboundModuleScript Class Reference
A compiled JavaScript module, not yet tied to a Context.
#include <v8-script.h>
Public Member Functions
Local< Value > GetSourceURL ()
Data read from magic sourceURL comments.
Local< Value > GetSourceMappingURL ()
Data read from magic sourceMappingURL comments.
Detailed Description
A compiled JavaScript module, not yet tied to a Context.
Definition at line 97 of file v8-script.h.
Member Function Documentation
GetSourceMappingURL()
Local< Value > v8::UnboundModuleScript::GetSourceMappingURL ()
Data read from magic sourceMappingURL comments.
Definition at line 1910 of file api.cc.
                                                      {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsScript(obj->script())) {
    // TODO(jgruber): Remove this DCHECK once Function::GetUnboundScript is
    // gone.
    DCHECK(!i::HeapLayout::InReadOnlySpace(*obj));
    i::Isolate* i_isolate = i::GetIsolateFromWritableObject(*obj);
    ApiRuntimeCallStatsScope rcs_scope(
        i_isolate, RCCId::kAPI_UnboundModuleScript_GetSourceMappingURL);
    EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
    i::Tagged<i::Object> url =
        i::Cast<i::Script>(obj->script())->source_mapping_url();
    return Utils::ToLocal(i::direct_handle(url, i_isolate));
  } else {
    return {};
  }
}
References DCHECK, v8::internal::direct_handle(), v8::internal::GetIsolateFromWritableObject(), v8::internal::HeapLayout::InReadOnlySpace(), and v8::Utils::OpenDirectHandle().
GetSourceURL()
Local< Value > v8::UnboundModuleScript::GetSourceURL ()
Data read from magic sourceURL comments.
Definition at line 1893 of file api.cc.
                                               {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsScript(obj->script())) {
    // TODO(jgruber): Remove this DCHECK once Function::GetUnboundScript is
    // gone.
    DCHECK(!i::HeapLayout::InReadOnlySpace(*obj));
    i::Isolate* i_isolate = i::GetIsolateFromWritableObject(*obj);
    ApiRuntimeCallStatsScope rcs_scope(
        i_isolate, RCCId::kAPI_UnboundModuleScript_GetSourceURL);
    EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
    i::Tagged<i::Object> url = i::Cast<i::Script>(obj->script())->source_url();
    return Utils::ToLocal(i::direct_handle(url, i_isolate));
  } else {
    return {};
  }
}
References DCHECK, v8::internal::direct_handle(), v8::internal::GetIsolateFromWritableObject(), v8::internal::HeapLayout::InReadOnlySpace(), and v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-script.h
/mnt/V8SourceCode/src/api/api.cc