v8::internal::compiler::InstructionScheduler Class Reference
#include <instruction-scheduler.h>
Classes
class CriticalPathFirstQueue
class ScheduleGraphNode
class SchedulingQueueBase
class StressSchedulerQueue
Public Member Functions
V8_EXPORT_PRIVATE InstructionScheduler (Zone *zone, InstructionSequence *sequence)
V8_EXPORT_PRIVATE void StartBlock (RpoNumber rpo)
V8_EXPORT_PRIVATE void EndBlock (RpoNumber rpo)
V8_EXPORT_PRIVATE void AddInstruction (Instruction *instr)
V8_EXPORT_PRIVATE void AddTerminator (Instruction *instr)
Static Public Member Functions
static bool SchedulerSupported ()
Private Member Functions
template<typename QueueType >
void Schedule ()
V8_EXPORT_PRIVATE int GetInstructionFlags (const Instruction *instr) const
int GetTargetInstructionFlags (const Instruction *instr) const
bool IsBarrier (const Instruction *instr) const
bool HasSideEffect (const Instruction *instr) const
bool IsLoadOperation (const Instruction *instr) const
bool CanTrap (const Instruction *instr) const
bool MayNeedDeoptOrTrapCheck (const Instruction *instr) const
bool DependsOnDeoptOrTrap (const Instruction *instr) const
bool IsFixedRegisterParameter (const Instruction *instr) const
void ComputeTotalLatencies ()
Zone * zone ()
InstructionSequence * sequence ()
base::RandomNumberGenerator * random_number_generator ()
Static Private Member Functions
static int GetInstructionLatency (const Instruction *instr)
Private Attributes
Zone * zone_
InstructionSequence * sequence_
ZoneVector< ScheduleGraphNode * > graph_
ScheduleGraphNode * last_side_effect_instr_
ZoneVector< ScheduleGraphNode * > pending_loads_
ScheduleGraphNode * last_live_in_reg_marker_
ScheduleGraphNode * last_deopt_or_trap_
ZoneMap< int32_t, ScheduleGraphNode * > operands_map_
std::optional< base::RandomNumberGenerator > random_number_generator_
Friends
class InstructionSchedulerTester
Detailed Description
Definition at line 35 of file instruction-scheduler.h.
Constructor & Destructor Documentation
InstructionScheduler()
v8::internal::compiler::InstructionScheduler::InstructionScheduler (Zone * zone, InstructionSequence * sequence)
Definition at line 77 of file instruction-scheduler.cc.
    : zone_(zone),
      sequence_(sequence),
      graph_(zone),
      last_side_effect_instr_(nullptr),
      pending_loads_(zone),
      last_live_in_reg_marker_(nullptr),
      last_deopt_or_trap_(nullptr),
      operands_map_(zone) {
  if (v8_flags.turbo_stress_instruction_scheduling) {
    random_number_generator_ =
        std::optional<base::RandomNumberGenerator>(v8_flags.random_seed);
  }
}
References random_number_generator_, and v8::internal::v8_flags.
Member Function Documentation
AddInstruction()
void v8::internal::compiler::InstructionScheduler::AddInstruction (Instruction * instr)
Definition at line 122 of file instruction-scheduler.cc.
                                                            {
  if (IsBarrier(instr)) {
    if (v8_flags.turbo_stress_instruction_scheduling) {
      Schedule<StressSchedulerQueue>();
    } else {
      Schedule<CriticalPathFirstQueue>();
    }
    sequence()->AddInstruction(instr);
    return;
  }
  ScheduleGraphNode* new_node = zone()->New<ScheduleGraphNode>(zone(), instr);
  // We should not have branches in the middle of a block.
  DCHECK_NE(instr->flags_mode(), kFlags_branch);
  if (IsFixedRegisterParameter(instr)) {
    if (last_live_in_reg_marker_ != nullptr) {
      last_live_in_reg_marker_->AddSuccessor(new_node);
    }
    last_live_in_reg_marker_ = new_node;
  } else {
    if (last_live_in_reg_marker_ != nullptr) {
      last_live_in_reg_marker_->AddSuccessor(new_node);
    }
    // Make sure that instructions are not scheduled before the last
    // deoptimization or trap point when they depend on it.
    if ((last_deopt_or_trap_ != nullptr) && DependsOnDeoptOrTrap(instr)) {
      last_deopt_or_trap_->AddSuccessor(new_node);
    }
    // Instructions with side effects and memory operations can't be
    // reordered with respect to each other.
    if (HasSideEffect(instr)) {
      if (last_side_effect_instr_ != nullptr) {
        last_side_effect_instr_->AddSuccessor(new_node);
      }
      for (ScheduleGraphNode* load : pending_loads_) {
        load->AddSuccessor(new_node);
      }
      pending_loads_.clear();
      last_side_effect_instr_ = new_node;
    } else if (IsLoadOperation(instr)) {
      // Load operations can't be reordered with side effects instructions but
      // independent loads can be reordered with respect to each other.
      if (last_side_effect_instr_ != nullptr) {
        last_side_effect_instr_->AddSuccessor(new_node);
      }
      pending_loads_.push_back(new_node);
    } else if (instr->IsDeoptimizeCall() || CanTrap(instr)) {
      // Ensure that deopts or traps are not reordered with respect to
      // side-effect instructions.
      if (last_side_effect_instr_ != nullptr) {
        last_side_effect_instr_->AddSuccessor(new_node);
      }
    }
    // Update last deoptimization or trap point.
    if (instr->IsDeoptimizeCall() || CanTrap(instr)) {
      last_deopt_or_trap_ = new_node;
    }
    // Look for operand dependencies.
    for (size_t i = 0; i < instr->InputCount(); ++i) {
      const InstructionOperand* input = instr->InputAt(i);
      if (input->IsUnallocated()) {
        int32_t vreg = UnallocatedOperand::cast(input)->virtual_register();
        auto it = operands_map_.find(vreg);
        if (it != operands_map_.end()) {
          it->second->AddSuccessor(new_node);
        }
      }
    }
    // Record the virtual registers defined by this instruction.
    for (size_t i = 0; i < instr->OutputCount(); ++i) {
      const InstructionOperand* output = instr->OutputAt(i);
      if (output->IsUnallocated()) {
        operands_map_[UnallocatedOperand::cast(output)->virtual_register()] =
            new_node;
      } else if (output->IsConstant()) {
        operands_map_[ConstantOperand::cast(output)->virtual_register()] =
            new_node;
      }
    }
  }
  graph_.push_back(new_node);
}
References v8::internal::compiler::InstructionSequence::AddInstruction(), v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::AddSuccessor(), CanTrap(), DCHECK_NE, DependsOnDeoptOrTrap(), v8::internal::compiler::Instruction::flags_mode(), graph_, HasSideEffect(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::Instruction::InputCount(), IsBarrier(), v8::internal::compiler::Instruction::IsDeoptimizeCall(), IsFixedRegisterParameter(), IsLoadOperation(), v8::internal::compiler::kFlags_branch, last_deopt_or_trap_, last_live_in_reg_marker_, last_side_effect_instr_, v8::internal::Zone::New(), operands_map_, v8::internal::compiler::Instruction::OutputAt(), v8::internal::compiler::Instruction::OutputCount(), pending_loads_, sequence(), v8::internal::v8_flags, and zone().
Referenced by v8::internal::compiler::InstructionSelector::AddInstruction().
AddTerminator()
void v8::internal::compiler::InstructionScheduler::AddTerminator (Instruction * instr)
Definition at line 112 of file instruction-scheduler.cc.
                                                           {
  ScheduleGraphNode* new_node = zone()->New<ScheduleGraphNode>(zone(), instr);
  // Make sure that basic block terminators are not moved by adding them
  // as successor of every instruction.
  for (ScheduleGraphNode* node : graph_) {
    node->AddSuccessor(new_node);
  }
  graph_.push_back(new_node);
}
References v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::AddSuccessor(), graph_, v8::internal::Zone::New(), and zone().
Referenced by v8::internal::compiler::InstructionSelector::AddTerminator().
CanTrap()
bool v8::internal::compiler::InstructionScheduler::CanTrap (const Instruction * instr) const [inline], [private]
Definition at line 173 of file instruction-scheduler.h.
                                               {
    return instr->IsTrap() ||
           (instr->HasMemoryAccessMode() &&
            instr->memory_access_mode() != kMemoryAccessDirect);
  }
References v8::internal::compiler::Instruction::HasMemoryAccessMode(), v8::internal::compiler::Instruction::IsTrap(), v8::internal::compiler::kMemoryAccessDirect, and v8::internal::compiler::Instruction::memory_access_mode().
Referenced by AddInstruction(), and DependsOnDeoptOrTrap().
ComputeTotalLatencies()
void v8::internal::compiler::InstructionScheduler::ComputeTotalLatencies () [private]
Definition at line 410 of file instruction-scheduler.cc.
                                                 {
  for (ScheduleGraphNode* node : base::Reversed(graph_)) {
    int max_latency = 0;
    for (ScheduleGraphNode* successor : node->successors()) {
      DCHECK_NE(-1, successor->total_latency());
      if (successor->total_latency() > max_latency) {
        max_latency = successor->total_latency();
      }
    }
    node->set_total_latency(max_latency + node->latency());
  }
}
References DCHECK_NE, graph_, v8::base::Reversed(), and v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::successors().
Referenced by Schedule().
DependsOnDeoptOrTrap()
bool v8::internal::compiler::InstructionScheduler::DependsOnDeoptOrTrap (const Instruction * instr) const [inline], [private]
Definition at line 192 of file instruction-scheduler.h.
                                                            {
    return MayNeedDeoptOrTrapCheck(instr) || instr->IsDeoptimizeCall() ||
           CanTrap(instr) || HasSideEffect(instr) || IsLoadOperation(instr);
  }
References CanTrap(), HasSideEffect(), v8::internal::compiler::Instruction::IsDeoptimizeCall(), IsLoadOperation(), and MayNeedDeoptOrTrapCheck().
Referenced by AddInstruction().
EndBlock()
void v8::internal::compiler::InstructionScheduler::EndBlock (RpoNumber rpo)
Definition at line 103 of file instruction-scheduler.cc.
                                                 {
  if (v8_flags.turbo_stress_instruction_scheduling) {
    Schedule<StressSchedulerQueue>();
  } else {
    Schedule<CriticalPathFirstQueue>();
  }
  sequence()->EndBlock(rpo);
}
References v8::internal::compiler::InstructionSequence::EndBlock(), sequence(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::InstructionSelector::EndBlock().
GetInstructionFlags()
int v8::internal::compiler::InstructionScheduler::GetInstructionFlags (const Instruction * instr) const [private]
Definition at line 258 of file instruction-scheduler.cc.
                                                                            {
  switch (instr->arch_opcode()) {
    case kArchNop:
    case kArchStackCheckOffset:
    case kArchFramePointer:
    case kArchParentFramePointer:
    case kArchRootPointer:
    case kArchStackSlot: // Despite its name this opcode will produce a
                          // reference to a frame slot, so it is not affected
                          // by the arm64 dual stack issues mentioned below.
    case kArchComment:
    case kArchDeoptimize:
    case kArchJmp:
    case kArchBinarySearchSwitch:
    case kArchRet:
    case kArchTableSwitch:
      return kNoOpcodeFlags;
    case kArchTruncateDoubleToI:
    case kIeee754Float64Acos:
    case kIeee754Float64Acosh:
    case kIeee754Float64Asin:
    case kIeee754Float64Asinh:
    case kIeee754Float64Atan:
    case kIeee754Float64Atanh:
    case kIeee754Float64Atan2:
    case kIeee754Float64Cbrt:
    case kIeee754Float64Cos:
    case kIeee754Float64Cosh:
    case kIeee754Float64Exp:
    case kIeee754Float64Expm1:
    case kIeee754Float64Log:
    case kIeee754Float64Log1p:
    case kIeee754Float64Log10:
    case kIeee754Float64Log2:
    case kIeee754Float64Pow:
    case kIeee754Float64Sin:
    case kIeee754Float64Sinh:
    case kIeee754Float64Tan:
    case kIeee754Float64Tanh:
      return kNoOpcodeFlags;
    case kArchStackPointerGreaterThan:
      // The ArchStackPointerGreaterThan instruction loads the current stack
      // pointer value and must not be reordered with instructions with side
      // effects.
      return kIsLoadOperation;
#if V8_ENABLE_WEBASSEMBLY
    case kArchStackPointer:
    case kArchSetStackPointer:
      // Instructions that load or set the stack pointer must not be reordered
      // with instructions with side effects or with each other.
      return kHasSideEffect;
#endif // V8_ENABLE_WEBASSEMBLY
    case kArchPrepareCallCFunction:
    case kArchPrepareTailCall:
    case kArchTailCallCodeObject:
    case kArchTailCallAddress:
#if V8_ENABLE_WEBASSEMBLY
    case kArchTailCallWasm:
    case kArchTailCallWasmIndirect:
#endif // V8_ENABLE_WEBASSEMBLY
    case kArchAbortCSADcheck:
      return kHasSideEffect;
    case kArchDebugBreak:
      return kIsBarrier;
    case kArchSaveCallerRegisters:
    case kArchRestoreCallerRegisters:
      return kIsBarrier;
    case kArchCallCFunction:
    case kArchCallCodeObject:
    case kArchCallJSFunction:
#if V8_ENABLE_WEBASSEMBLY
    case kArchCallWasmFunction:
    case kArchCallWasmFunctionIndirect:
#endif // V8_ENABLE_WEBASSEMBLY
    case kArchCallBuiltinPointer:
      // Calls can cause GC and GC may relocate objects. If a pure instruction
      // operates on a tagged pointer that was cast to a word then it may be
      // incorrect to move the instruction across the call. Hence we mark all
      // (non-tail-)calls as barriers.
      return kIsBarrier;
    case kArchStoreWithWriteBarrier:
    case kArchAtomicStoreWithWriteBarrier:
    case kArchStoreIndirectWithWriteBarrier:
      return kHasSideEffect;
    case kAtomicLoadInt8:
    case kAtomicLoadUint8:
    case kAtomicLoadInt16:
    case kAtomicLoadUint16:
    case kAtomicLoadWord32:
      return kIsLoadOperation;
    case kAtomicStoreWord8:
    case kAtomicStoreWord16:
    case kAtomicStoreWord32:
      return kHasSideEffect;
    case kAtomicExchangeInt8:
    case kAtomicExchangeUint8:
    case kAtomicExchangeInt16:
    case kAtomicExchangeUint16:
    case kAtomicExchangeWord32:
    case kAtomicExchangeWithWriteBarrier:
    case kAtomicCompareExchangeInt8:
    case kAtomicCompareExchangeUint8:
    case kAtomicCompareExchangeInt16:
    case kAtomicCompareExchangeUint16:
    case kAtomicCompareExchangeWord32:
    case kAtomicAddInt8:
    case kAtomicAddUint8:
    case kAtomicAddInt16:
    case kAtomicAddUint16:
    case kAtomicAddWord32:
    case kAtomicSubInt8:
    case kAtomicSubUint8:
    case kAtomicSubInt16:
    case kAtomicSubUint16:
    case kAtomicSubWord32:
    case kAtomicAndInt8:
    case kAtomicAndUint8:
    case kAtomicAndInt16:
    case kAtomicAndUint16:
    case kAtomicAndWord32:
    case kAtomicOrInt8:
    case kAtomicOrUint8:
    case kAtomicOrInt16:
    case kAtomicOrUint16:
    case kAtomicOrWord32:
    case kAtomicXorInt8:
    case kAtomicXorUint8:
    case kAtomicXorInt16:
    case kAtomicXorUint16:
    case kAtomicXorWord32:
      return kHasSideEffect;
#define CASE(Name) case k##Name:
      TARGET_ARCH_OPCODE_LIST(CASE)
#undef CASE
      return GetTargetInstructionFlags(instr);
  }
  UNREACHABLE();
}
References v8::internal::compiler::Instruction::arch_opcode(), CASE, GetTargetInstructionFlags(), v8::internal::compiler::kHasSideEffect, v8::internal::compiler::kIsBarrier, v8::internal::compiler::kIsLoadOperation, v8::internal::compiler::kNoOpcodeFlags, TARGET_ARCH_OPCODE_LIST, and v8::internal::UNREACHABLE().
Referenced by HasSideEffect(), IsBarrier(), IsLoadOperation(), and MayNeedDeoptOrTrapCheck().
GetInstructionLatency()
int v8::internal::compiler::InstructionScheduler::GetInstructionLatency (const Instruction * instr) [static], [private]
Definition at line 387 of file instruction-scheduler-arm.cc.
                                                                        {
  // TODO(all): Add instruction cost modeling.
  return 1;
}
GetTargetInstructionFlags()
int v8::internal::compiler::InstructionScheduler::GetTargetInstructionFlags (const Instruction * instr) const [private]
Definition at line 13 of file instruction-scheduler-arm.cc.
                                    {
  switch (instr->arch_opcode()) {
    case kArmAdd:
    case kArmAnd:
    case kArmBic:
    case kArmClz:
    case kArmCmp:
    case kArmCmn:
    case kArmTst:
    case kArmTeq:
    case kArmOrr:
    case kArmEor:
    case kArmSub:
    case kArmRsb:
    case kArmMul:
    case kArmMla:
    case kArmMls:
    case kArmSmmul:
    case kArmSmull:
    case kArmSmmla:
    case kArmUmull:
    case kArmSdiv:
    case kArmUdiv:
    case kArmMov:
    case kArmMvn:
    case kArmBfc:
    case kArmUbfx:
    case kArmSbfx:
    case kArmSxtb:
    case kArmSxth:
    case kArmSxtab:
    case kArmSxtah:
    case kArmUxtb:
    case kArmUxth:
    case kArmUxtab:
    case kArmUxtah:
    case kArmRbit:
    case kArmRev:
    case kArmAddPair:
    case kArmSubPair:
    case kArmMulPair:
    case kArmLslPair:
    case kArmLsrPair:
    case kArmAsrPair:
    case kArmVcmpF32:
    case kArmVaddF32:
    case kArmVsubF32:
    case kArmVmulF32:
    case kArmVmlaF32:
    case kArmVmlsF32:
    case kArmVdivF32:
    case kArmVabsF32:
    case kArmVnegF32:
    case kArmVsqrtF32:
    case kArmVcmpF64:
    case kArmVaddF64:
    case kArmVsubF64:
    case kArmVmulF64:
    case kArmVmlaF64:
    case kArmVmlsF64:
    case kArmVdivF64:
    case kArmVmodF64:
    case kArmVabsF64:
    case kArmVnegF64:
    case kArmVsqrtF64:
    case kArmVmullLow:
    case kArmVmullHigh:
    case kArmVrintmF32:
    case kArmVrintmF64:
    case kArmVrintpF32:
    case kArmVrintpF64:
    case kArmVrintzF32:
    case kArmVrintzF64:
    case kArmVrintaF64:
    case kArmVrintnF32:
    case kArmVrintnF64:
    case kArmVcvtF32F64:
    case kArmVcvtF64F32:
    case kArmVcvtF32S32:
    case kArmVcvtF32U32:
    case kArmVcvtF64S32:
    case kArmVcvtF64U32:
    case kArmVcvtS32F32:
    case kArmVcvtU32F32:
    case kArmVcvtS32F64:
    case kArmVcvtU32F64:
    case kArmVmovU32F32:
    case kArmVmovF32U32:
    case kArmVmovLowU32F64:
    case kArmVmovLowF64U32:
    case kArmVmovHighU32F64:
    case kArmVmovHighF64U32:
    case kArmVmovF64U32U32:
    case kArmVmovU32U32F64:
    case kArmVcnt:
    case kArmVpadal:
    case kArmVpaddl:
    case kArmFloat32Max:
    case kArmFloat64Max:
    case kArmFloat32Min:
    case kArmFloat64Min:
    case kArmFloat64SilenceNaN:
    case kArmF64x2Splat:
    case kArmF64x2ExtractLane:
    case kArmF64x2ReplaceLane:
    case kArmF64x2Abs:
    case kArmF64x2Neg:
    case kArmF64x2Sqrt:
    case kArmF64x2Add:
    case kArmF64x2Sub:
    case kArmF64x2Mul:
    case kArmF64x2Div:
    case kArmF64x2Min:
    case kArmF64x2Max:
    case kArmF64x2Eq:
    case kArmF64x2Ne:
    case kArmF64x2Lt:
    case kArmF64x2Le:
    case kArmF64x2Qfma:
    case kArmF64x2Qfms:
    case kArmF64x2Pmin:
    case kArmF64x2Pmax:
    case kArmF64x2Ceil:
    case kArmF64x2Floor:
    case kArmF64x2Trunc:
    case kArmF64x2NearestInt:
    case kArmF64x2ConvertLowI32x4S:
    case kArmF64x2ConvertLowI32x4U:
    case kArmF64x2PromoteLowF32x4:
    case kArmF32x4Splat:
    case kArmF32x4ExtractLane:
    case kArmF32x4ReplaceLane:
    case kArmF32x4SConvertI32x4:
    case kArmF32x4UConvertI32x4:
    case kArmF32x4Abs:
    case kArmF32x4Neg:
    case kArmF32x4Sqrt:
    case kArmF32x4Add:
    case kArmF32x4Sub:
    case kArmF32x4Mul:
    case kArmF32x4Div:
    case kArmF32x4Min:
    case kArmF32x4Max:
    case kArmF32x4Eq:
    case kArmF32x4Ne:
    case kArmF32x4Lt:
    case kArmF32x4Le:
    case kArmF32x4Qfma:
    case kArmF32x4Qfms:
    case kArmF32x4Pmin:
    case kArmF32x4Pmax:
    case kArmF32x4DemoteF64x2Zero:
    case kArmI64x2SplatI32Pair:
    case kArmI64x2ReplaceLaneI32Pair:
    case kArmI64x2Abs:
    case kArmI64x2Neg:
    case kArmI64x2Shl:
    case kArmI64x2ShrS:
    case kArmI64x2Add:
    case kArmI64x2Sub:
    case kArmI64x2Mul:
    case kArmI64x2ShrU:
    case kArmI64x2BitMask:
    case kArmI64x2Eq:
    case kArmI64x2Ne:
    case kArmI64x2GtS:
    case kArmI64x2GeS:
    case kArmI64x2SConvertI32x4Low:
    case kArmI64x2SConvertI32x4High:
    case kArmI64x2UConvertI32x4Low:
    case kArmI64x2UConvertI32x4High:
    case kArmI32x4Splat:
    case kArmI32x4ExtractLane:
    case kArmI32x4ReplaceLane:
    case kArmI32x4SConvertF32x4:
    case kArmI32x4SConvertI16x8Low:
    case kArmI32x4SConvertI16x8High:
    case kArmI32x4Neg:
    case kArmI32x4Shl:
    case kArmI32x4ShrS:
    case kArmI32x4Add:
    case kArmI32x4Sub:
    case kArmI32x4Mul:
    case kArmI32x4MinS:
    case kArmI32x4MaxS:
    case kArmI32x4Eq:
    case kArmI32x4Ne:
    case kArmI32x4GtS:
    case kArmI32x4GeS:
    case kArmI32x4UConvertF32x4:
    case kArmI32x4UConvertI16x8Low:
    case kArmI32x4UConvertI16x8High:
    case kArmI32x4ShrU:
    case kArmI32x4MinU:
    case kArmI32x4MaxU:
    case kArmI32x4GtU:
    case kArmI32x4GeU:
    case kArmI32x4Abs:
    case kArmI32x4BitMask:
    case kArmI32x4DotI16x8S:
    case kArmI16x8DotI8x16S:
    case kArmI32x4DotI8x16AddS:
    case kArmI32x4TruncSatF64x2SZero:
    case kArmI32x4TruncSatF64x2UZero:
    case kArmI16x8Splat:
    case kArmI16x8ExtractLaneS:
    case kArmI16x8ReplaceLane:
    case kArmI16x8SConvertI8x16Low:
    case kArmI16x8SConvertI8x16High:
    case kArmI16x8Neg:
    case kArmI16x8Shl:
    case kArmI16x8ShrS:
    case kArmI16x8SConvertI32x4:
    case kArmI16x8Add:
    case kArmI16x8AddSatS:
    case kArmI16x8Sub:
    case kArmI16x8SubSatS:
    case kArmI16x8Mul:
    case kArmI16x8MinS:
    case kArmI16x8MaxS:
    case kArmI16x8Eq:
    case kArmI16x8Ne:
    case kArmI16x8GtS:
    case kArmI16x8GeS:
    case kArmI16x8ExtractLaneU:
    case kArmI16x8UConvertI8x16Low:
    case kArmI16x8UConvertI8x16High:
    case kArmI16x8ShrU:
    case kArmI16x8UConvertI32x4:
    case kArmI16x8AddSatU:
    case kArmI16x8SubSatU:
    case kArmI16x8MinU:
    case kArmI16x8MaxU:
    case kArmI16x8GtU:
    case kArmI16x8GeU:
    case kArmI16x8RoundingAverageU:
    case kArmI16x8Abs:
    case kArmI16x8BitMask:
    case kArmI16x8Q15MulRSatS:
    case kArmI8x16Splat:
    case kArmI8x16ExtractLaneS:
    case kArmI8x16ReplaceLane:
    case kArmI8x16Neg:
    case kArmI8x16Shl:
    case kArmI8x16ShrS:
    case kArmI8x16SConvertI16x8:
    case kArmI8x16Add:
    case kArmI8x16AddSatS:
    case kArmI8x16Sub:
    case kArmI8x16SubSatS:
    case kArmI8x16MinS:
    case kArmI8x16MaxS:
    case kArmI8x16Eq:
    case kArmI8x16Ne:
    case kArmI8x16GtS:
    case kArmI8x16GeS:
    case kArmI8x16ExtractLaneU:
    case kArmI8x16UConvertI16x8:
    case kArmI8x16AddSatU:
    case kArmI8x16SubSatU:
    case kArmI8x16ShrU:
    case kArmI8x16MinU:
    case kArmI8x16MaxU:
    case kArmI8x16GtU:
    case kArmI8x16GeU:
    case kArmI8x16RoundingAverageU:
    case kArmI8x16Abs:
    case kArmI8x16BitMask:
    case kArmS128Const:
    case kArmS128Zero:
    case kArmS128AllOnes:
    case kArmS128Dup:
    case kArmS128And:
    case kArmS128Or:
    case kArmS128Xor:
    case kArmS128Not:
    case kArmS128Select:
    case kArmS128AndNot:
    case kArmS32x4ZipLeft:
    case kArmS32x4ZipRight:
    case kArmS32x4UnzipLeft:
    case kArmS32x4UnzipRight:
    case kArmS32x4TransposeLeft:
    case kArmS32x4TransposeRight:
    case kArmS32x4Shuffle:
    case kArmS16x8ZipLeft:
    case kArmS16x8ZipRight:
    case kArmS16x8UnzipLeft:
    case kArmS16x8UnzipRight:
    case kArmS16x8TransposeLeft:
    case kArmS16x8TransposeRight:
    case kArmS8x16ZipLeft:
    case kArmS8x16ZipRight:
    case kArmS8x16UnzipLeft:
    case kArmS8x16UnzipRight:
    case kArmS8x16TransposeLeft:
    case kArmS8x16TransposeRight:
    case kArmS8x16Concat:
    case kArmI8x16Swizzle:
    case kArmI8x16Shuffle:
    case kArmS32x2Reverse:
    case kArmS16x4Reverse:
    case kArmS16x2Reverse:
    case kArmS8x8Reverse:
    case kArmS8x4Reverse:
    case kArmS8x2Reverse:
    case kArmI64x2AllTrue:
    case kArmI32x4AllTrue:
    case kArmI16x8AllTrue:
    case kArmV128AnyTrue:
    case kArmI8x16AllTrue:
      return kNoOpcodeFlags;
    case kArmVldrF32:
    case kArmVldrF64:
    case kArmVld1F64:
    case kArmVld1S128:
    case kArmLdrb:
    case kArmLdrsb:
    case kArmLdrh:
    case kArmLdrsh:
    case kArmLdr:
    case kArmPeek:
    case kArmWord32AtomicPairLoad:
    case kArmS128Load8Splat:
    case kArmS128Load16Splat:
    case kArmS128Load32Splat:
    case kArmS128Load64Splat:
    case kArmS128Load8x8S:
    case kArmS128Load8x8U:
    case kArmS128Load16x4S:
    case kArmS128Load16x4U:
    case kArmS128Load32x2S:
    case kArmS128Load32x2U:
    case kArmS128Load32Zero:
    case kArmS128Load64Zero:
    case kArmS128LoadLaneLow:
    case kArmS128LoadLaneHigh:
      return kIsLoadOperation;
    case kArmVstrF32:
    case kArmVstrF64:
    case kArmVst1F64:
    case kArmVst1S128:
    case kArmStrb:
    case kArmStrh:
    case kArmStr:
    case kArmPush:
    case kArmPoke:
    case kArmDmbIsh:
    case kArmDsbIsb:
    case kArmWord32AtomicPairStore:
    case kArmWord32AtomicPairAdd:
    case kArmWord32AtomicPairSub:
    case kArmWord32AtomicPairAnd:
    case kArmWord32AtomicPairOr:
    case kArmWord32AtomicPairXor:
    case kArmWord32AtomicPairExchange:
    case kArmWord32AtomicPairCompareExchange:
    case kArmS128StoreLaneLow:
    case kArmS128StoreLaneHigh:
      return kHasSideEffect;
#define CASE(Name) case k##Name:
      COMMON_ARCH_OPCODE_LIST(CASE)
#undef CASE
      // Already covered in architecture independent code.
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::compiler::Instruction::arch_opcode(), CASE, COMMON_ARCH_OPCODE_LIST, v8::internal::compiler::kHasSideEffect, v8::internal::compiler::kIsLoadOperation, v8::internal::compiler::kNoOpcodeFlags, and v8::internal::UNREACHABLE().
Referenced by GetInstructionFlags().
HasSideEffect()
bool v8::internal::compiler::InstructionScheduler::HasSideEffect (const Instruction * instr) const [inline], [private]
Definition at line 164 of file instruction-scheduler.h.
                                                     {
    return (GetInstructionFlags(instr) & kHasSideEffect) != 0;
  }
References GetInstructionFlags(), and v8::internal::compiler::kHasSideEffect.
Referenced by AddInstruction(), and DependsOnDeoptOrTrap().
IsBarrier()
bool v8::internal::compiler::InstructionScheduler::IsBarrier (const Instruction * instr) const [inline], [private]
Definition at line 158 of file instruction-scheduler.h.
                                                 {
    return (GetInstructionFlags(instr) & kIsBarrier) != 0;
  }
References GetInstructionFlags(), and v8::internal::compiler::kIsBarrier.
Referenced by AddInstruction().
IsFixedRegisterParameter()
bool v8::internal::compiler::InstructionScheduler::IsFixedRegisterParameter (const Instruction * instr) const [inline], [private]
Definition at line 199 of file instruction-scheduler.h.
                                                                {
    return (instr->arch_opcode() == kArchNop) && (instr->OutputCount() == 1) &&
           (instr->OutputAt(0)->IsUnallocated()) &&
           (UnallocatedOperand::cast(instr->OutputAt(0))
                ->HasFixedRegisterPolicy() ||
            UnallocatedOperand::cast(instr->OutputAt(0))
                ->HasFixedFPRegisterPolicy());
  }
References v8::internal::compiler::Instruction::arch_opcode(), v8::internal::compiler::Instruction::OutputAt(), and v8::internal::compiler::Instruction::OutputCount().
Referenced by AddInstruction().
IsLoadOperation()
bool v8::internal::compiler::InstructionScheduler::IsLoadOperation (const Instruction * instr) const [inline], [private]
Definition at line 169 of file instruction-scheduler.h.
                                                       {
    return (GetInstructionFlags(instr) & kIsLoadOperation) != 0;
  }
References GetInstructionFlags(), and v8::internal::compiler::kIsLoadOperation.
Referenced by AddInstruction(), and DependsOnDeoptOrTrap().
MayNeedDeoptOrTrapCheck()
bool v8::internal::compiler::InstructionScheduler::MayNeedDeoptOrTrapCheck (const Instruction * instr) const [inline], [private]
Definition at line 186 of file instruction-scheduler.h.
                                                               {
    return (GetInstructionFlags(instr) & kMayNeedDeoptOrTrapCheck) != 0;
  }
References GetInstructionFlags(), and v8::internal::compiler::kMayNeedDeoptOrTrapCheck.
Referenced by DependsOnDeoptOrTrap().
random_number_generator()
base::RandomNumberGenerator* v8::internal::compiler::InstructionScheduler::random_number_generator () [inline], [private]
Definition at line 214 of file instruction-scheduler.h.
                                                       {
    return &random_number_generator_.value();
  }
References random_number_generator_.
Referenced by v8::internal::compiler::InstructionScheduler::StressSchedulerQueue::PopBestCandidate(), and v8::internal::compiler::InstructionScheduler::StressSchedulerQueue::random_number_generator().
Schedule()
template<typename QueueType >
void v8::internal::compiler::InstructionScheduler::Schedule [private]
Definition at line 214 of file instruction-scheduler.cc.
                                    {
  QueueType ready_list(this);
  // Compute total latencies so that we can schedule the critical path first.
  ComputeTotalLatencies();
  // Add nodes which don't have dependencies to the ready list.
  for (ScheduleGraphNode* node : graph_) {
    if (!node->HasUnscheduledPredecessor()) {
      ready_list.AddNode(node);
    }
  }
  // Go through the ready list and schedule the instructions.
  int cycle = 0;
  while (!ready_list.IsEmpty()) {
    ScheduleGraphNode* candidate = ready_list.PopBestCandidate(cycle);
    if (candidate != nullptr) {
      sequence()->AddInstruction(candidate->instruction());
      for (ScheduleGraphNode* successor : candidate->successors()) {
        successor->DropUnscheduledPredecessor();
        successor->set_start_cycle(
            std::max(successor->start_cycle(), cycle + candidate->latency()));
        if (!successor->HasUnscheduledPredecessor()) {
          ready_list.AddNode(successor);
        }
      }
    }
    cycle++;
  }
  // Reset own state.
  graph_.clear();
  operands_map_.clear();
  pending_loads_.clear();
  last_deopt_or_trap_ = nullptr;
  last_live_in_reg_marker_ = nullptr;
  last_side_effect_instr_ = nullptr;
}
References v8::internal::compiler::InstructionSequence::AddInstruction(), ComputeTotalLatencies(), graph_, v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::instruction(), last_deopt_or_trap_, last_live_in_reg_marker_, last_side_effect_instr_, v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::latency(), operands_map_, pending_loads_, sequence(), and v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::successors().
SchedulerSupported()
bool v8::internal::compiler::InstructionScheduler::SchedulerSupported () [static]
Definition at line 11 of file instruction-scheduler-arm.cc.
{ return true; }
Referenced by v8::internal::compiler::InstructionSelector::UseInstructionScheduling().
sequence()
InstructionSequence* v8::internal::compiler::InstructionScheduler::sequence () [inline], [private]
Definition at line 213 of file instruction-scheduler.h.
{ return sequence_; }
References sequence_.
Referenced by AddInstruction(), EndBlock(), Schedule(), and StartBlock().
StartBlock()
void v8::internal::compiler::InstructionScheduler::StartBlock (RpoNumber rpo)
Definition at line 93 of file instruction-scheduler.cc.
                                                   {
  DCHECK(graph_.empty());
  DCHECK_NULL(last_side_effect_instr_);
  DCHECK(pending_loads_.empty());
  DCHECK_NULL(last_live_in_reg_marker_);
  DCHECK_NULL(last_deopt_or_trap_);
  DCHECK(operands_map_.empty());
  sequence()->StartBlock(rpo);
}
References v8::internal::DCHECK(), DCHECK_NULL, graph_, last_deopt_or_trap_, last_live_in_reg_marker_, last_side_effect_instr_, operands_map_, pending_loads_, sequence(), and v8::internal::compiler::InstructionSequence::StartBlock().
Referenced by v8::internal::compiler::InstructionSelector::StartBlock().
zone()
Zone* v8::internal::compiler::InstructionScheduler::zone () [inline], [private]
Definition at line 212 of file instruction-scheduler.h.
{ return zone_; }
References zone_.
Referenced by AddInstruction(), and AddTerminator().
Friends And Related Function Documentation
InstructionSchedulerTester
friend class InstructionSchedulerTester [friend]
Definition at line 222 of file instruction-scheduler.h.
Member Data Documentation
graph_
ZoneVector<ScheduleGraphNode*> v8::internal::compiler::InstructionScheduler::graph_ [private]
Definition at line 220 of file instruction-scheduler.h.
Referenced by AddInstruction(), AddTerminator(), ComputeTotalLatencies(), Schedule(), and StartBlock().
last_deopt_or_trap_
ScheduleGraphNode* v8::internal::compiler::InstructionScheduler::last_deopt_or_trap_ [private]
Definition at line 241 of file instruction-scheduler.h.
Referenced by AddInstruction(), Schedule(), and StartBlock().
last_live_in_reg_marker_
ScheduleGraphNode* v8::internal::compiler::InstructionScheduler::last_live_in_reg_marker_ [private]
Definition at line 237 of file instruction-scheduler.h.
Referenced by AddInstruction(), Schedule(), and StartBlock().
last_side_effect_instr_
ScheduleGraphNode* v8::internal::compiler::InstructionScheduler::last_side_effect_instr_ [private]
Definition at line 225 of file instruction-scheduler.h.
Referenced by AddInstruction(), Schedule(), and StartBlock().
operands_map_
ZoneMap<int32_t, ScheduleGraphNode*> v8::internal::compiler::InstructionScheduler::operands_map_ [private]
Definition at line 245 of file instruction-scheduler.h.
Referenced by AddInstruction(), Schedule(), and StartBlock().
pending_loads_
ZoneVector<ScheduleGraphNode*> v8::internal::compiler::InstructionScheduler::pending_loads_ [private]
Definition at line 230 of file instruction-scheduler.h.
Referenced by AddInstruction(), Schedule(), and StartBlock().
random_number_generator_
std::optional<base::RandomNumberGenerator> v8::internal::compiler::InstructionScheduler::random_number_generator_ [private]
Definition at line 247 of file instruction-scheduler.h.
Referenced by InstructionScheduler(), and random_number_generator().
sequence_
InstructionSequence* v8::internal::compiler::InstructionScheduler::sequence_ [private]
Definition at line 219 of file instruction-scheduler.h.
Referenced by sequence().
zone_
Zone* v8::internal::compiler::InstructionScheduler::zone_ [private]
Definition at line 218 of file instruction-scheduler.h.
Referenced by zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction-scheduler.h
/mnt/V8SourceCode/src/compiler/backend/arm/instruction-scheduler-arm.cc
/mnt/V8SourceCode/src/compiler/backend/arm64/instruction-scheduler-arm64.cc
/mnt/V8SourceCode/src/compiler/backend/ia32/instruction-scheduler-ia32.cc
/mnt/V8SourceCode/src/compiler/backend/instruction-scheduler.cc
/mnt/V8SourceCode/src/compiler/backend/loong64/instruction-scheduler-loong64.cc
/mnt/V8SourceCode/src/compiler/backend/mips64/instruction-scheduler-mips64.cc
/mnt/V8SourceCode/src/compiler/backend/ppc/instruction-scheduler-ppc.cc
/mnt/V8SourceCode/src/compiler/backend/riscv/instruction-scheduler-riscv.cc
/mnt/V8SourceCode/src/compiler/backend/s390/instruction-scheduler-s390.cc
/mnt/V8SourceCode/src/compiler/backend/x64/instruction-scheduler-x64.cc