v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next > Class Template Reference
#include <dataview-lowering-reducer.h>
Public Member Functions
OpIndex BuildReverseBytes (ExternalArrayType type, OpIndex value)
OpIndex REDUCE() LoadDataViewElement (V< Object > object, V< WordPtr > storage, V< WordPtr > index, V< Word32 > is_little_endian, ExternalArrayType element_type)
OpIndex REDUCE() StoreDataViewElement (V< Object > object, V< WordPtr > storage, V< WordPtr > index, OpIndex value, V< Word32 > is_little_endian, ExternalArrayType element_type)
Detailed Description
template<typename Next>
class v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >
Definition at line 15 of file dataview-lowering-reducer.h.
Member Function Documentation
BuildReverseBytes()
template<typename Next >
OpIndex v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::BuildReverseBytes (ExternalArrayType type, OpIndex value) [inline]
Definition at line 19 of file dataview-lowering-reducer.h.
                                                                   {
    switch (type) {
      case kExternalInt8Array:
      case kExternalUint8Array:
      case kExternalUint8ClampedArray:
        return value;
      case kExternalInt16Array:
        return __ Word32ShiftRightArithmetic(__ Word32ReverseBytes(value), 16);
      case kExternalFloat16Array:
      case kExternalUint16Array:
        return __ Word32ShiftRightLogical(__ Word32ReverseBytes(value), 16);
      case kExternalInt32Array:
      case kExternalUint32Array:
        return __ Word32ReverseBytes(value);
      case kExternalFloat32Array: {
        V<Word32> bytes = __ BitcastFloat32ToWord32(value);
        V<Word32> reversed = __ Word32ReverseBytes(bytes);
        return __ BitcastWord32ToFloat32(reversed);
      }
      case kExternalFloat64Array: {
        if constexpr (Is64()) {
          V<Word64> bytes = __ BitcastFloat64ToWord64(value);
          V<Word64> reversed = __ Word64ReverseBytes(bytes);
          return __ BitcastWord64ToFloat64(reversed);
        } else {
          V<Word32> reversed_lo =
              __ Word32ReverseBytes(__ Float64ExtractLowWord32(value));
          V<Word32> reversed_hi =
              __ Word32ReverseBytes(__ Float64ExtractHighWord32(value));
          return __ BitcastWord32PairToFloat64(reversed_lo, reversed_hi);
        }
      }
      case kExternalBigInt64Array:
      case kExternalBigUint64Array:
        return __ Word64ReverseBytes(value);
    }
  }
References __, v8::internal::Is64(), v8::internal::kExternalBigInt64Array, v8::internal::kExternalBigUint64Array, v8::internal::kExternalFloat16Array, v8::internal::kExternalFloat32Array, v8::internal::kExternalFloat64Array, v8::internal::kExternalInt16Array, v8::internal::kExternalInt32Array, v8::internal::kExternalInt8Array, v8::internal::kExternalUint16Array, v8::internal::kExternalUint32Array, v8::internal::kExternalUint8Array, v8::internal::kExternalUint8ClampedArray, v8::internal::tracing::type, and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::LoadDataViewElement(), and v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::StoreDataViewElement().
LoadDataViewElement()
template<typename Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::LoadDataViewElement (V< Object > object, V< WordPtr > storage, V< WordPtr > index, V< Word32 > is_little_endian, ExternalArrayType element_type) [inline]
Definition at line 57 of file dataview-lowering-reducer.h.
                                                                      {
    const MachineType machine_type =
        AccessBuilder::ForTypedArrayElement(element_type, true).machine_type;
    const MemoryRepresentation memory_rep =
        MemoryRepresentation::FromMachineType(machine_type);
    OpIndex value =
        __ Load(storage, index,
                LoadOp::Kind::MaybeUnaligned(memory_rep).NotLoadEliminable(),
                memory_rep);
    Variable result = Asm().NewLoopInvariantVariable(
        RegisterRepresentationForArrayType(element_type));
    IF (is_little_endian) {
#if V8_TARGET_LITTLE_ENDIAN
      Asm().SetVariable(result, value);
#else
      Asm().SetVariable(result, BuildReverseBytes(element_type, value));
#endif // V8_TARGET_LITTLE_ENDIAN
    } ELSE {
#if V8_TARGET_LITTLE_ENDIAN
      Asm().SetVariable(result, BuildReverseBytes(element_type, value));
#else
      Asm().SetVariable(result, value);
#endif // V8_TARGET_LITTLE_ENDIAN
    }
    // We need to keep the {object} (either the JSArrayBuffer or the JSDataView)
    // alive so that the GC will not release the JSArrayBuffer (if there's any)
    // as long as we are still operating on it.
    __ Retain(object);
    return Asm().GetVariable(result);
  }
References __, v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::BuildReverseBytes(), v8::internal::compiler::AccessBuilder::ForTypedArrayElement(), v8::internal::compiler::turboshaft::MemoryRepresentation::FromMachineType(), v8::internal::index, v8::Load(), v8::internal::compiler::ElementAccess::machine_type, v8::internal::wasm::machine_type(), v8::internal::compiler::turboshaft::LoadOp::Kind::MaybeUnaligned(), v8::internal::compiler::turboshaft::RegisterRepresentationForArrayType(), v8::base::internal::result, and v8::internal::value.
StoreDataViewElement()
template<typename Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::StoreDataViewElement (V< Object > object, V< WordPtr > storage, V< WordPtr > index, OpIndex value, V< Word32 > is_little_endian, ExternalArrayType element_type) [inline]
Definition at line 94 of file dataview-lowering-reducer.h.
                                                                       {
    const MachineType machine_type =
        AccessBuilder::ForTypedArrayElement(element_type, true).machine_type;
    Variable value_to_store = Asm().NewLoopInvariantVariable(
        RegisterRepresentationForArrayType(element_type));
    IF (is_little_endian) {
#if V8_TARGET_LITTLE_ENDIAN
      Asm().SetVariable(value_to_store, value);
#else
      Asm().SetVariable(value_to_store, BuildReverseBytes(element_type, value));
#endif // V8_TARGET_LITTLE_ENDIAN
    } ELSE {
#if V8_TARGET_LITTLE_ENDIAN
      Asm().SetVariable(value_to_store, BuildReverseBytes(element_type, value));
#else
      Asm().SetVariable(value_to_store, value);
#endif // V8_TARGET_LITTLE_ENDIAN
    }
    const MemoryRepresentation memory_rep =
        MemoryRepresentation::FromMachineType(machine_type);
    __ Store(storage, index, Asm().GetVariable(value_to_store),
             StoreOp::Kind::MaybeUnaligned(memory_rep).NotLoadEliminable(),
             memory_rep, WriteBarrierKind::kNoWriteBarrier);
    // We need to keep the {object} (either the JSArrayBuffer or the JSDataView)
    // alive so that the GC will not release the JSArrayBuffer (if there's any)
    // as long as we are still operating on it.
    __ Retain(object);
    return {};
  }
References __, v8::internal::compiler::turboshaft::DataViewLoweringReducer< Next >::BuildReverseBytes(), v8::internal::compiler::AccessBuilder::ForTypedArrayElement(), v8::internal::compiler::turboshaft::MemoryRepresentation::FromMachineType(), v8::internal::index, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::ElementAccess::machine_type, v8::internal::wasm::machine_type(), v8::internal::compiler::turboshaft::LoadOp::Kind::MaybeUnaligned(), v8::internal::compiler::turboshaft::RegisterRepresentationForArrayType(), v8::internal::wasm::liftoff::Store(), and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/dataview-lowering-reducer.h