v8::FunctionCallbackInfo< T > Class Template Reference
The argument information given to function call callbacks.
#include <v8-function-callback.h>
Public Member Functions
int Length () const
The number of available arguments.
Local< Value > operator[] (int i) const
Accessor for the available arguments.
Local< Object > This () const
Returns the receiver.
Local< Value > NewTarget () const
For construct calls, this returns the `new.target` value.
bool IsConstructCall () const
Indicates whether this is a regular call or a construct call.
Local< Value > Data () const
The data argument specified when creating the callback.
Isolate * GetIsolate () const
The current Isolate.
ReturnValue< T > GetReturnValue () const
The ReturnValue for the call.
Private Member Functions
FunctionCallbackInfo (internal::Address *implicit_args, internal::Address *values, int length)
Private Attributes
internal::Address * implicit_args_
internal::Address * values_
internal::Address length_
Static Private Attributes
static constexpr int kUnusedIndex = 0
static constexpr int kIsolateIndex = 1
static constexpr int kContextIndex = 2
static constexpr int kReturnValueIndex = 3
static constexpr int kTargetIndex = 4
static constexpr int kNewTargetIndex = 5
static constexpr int kArgsLength = 6
static constexpr int kArgsLengthWithReceiver = kArgsLength + 1
static constexpr int kSize = 3 * internal::kApiSystemPointerSize
static constexpr int kImplicitArgsOffset = 0
static constexpr int kValuesOffset
static constexpr int kLengthOffset
static constexpr int kThisValuesIndex = -1
Friends
class internal::FunctionCallbackArguments
class internal::CustomArguments< FunctionCallbackInfo >
class debug::ConsoleCallArguments
void internal::PrintFunctionCallbackInfo (void *)
Detailed Description
template<typename T>
class v8::FunctionCallbackInfo< T >
The argument information given to function call callbacks.
This class provides access to information about the context of the call, including the receiver, the number and values of arguments, and the holder of the function.
Definition at line 118 of file v8-function-callback.h.
Constructor & Destructor Documentation
FunctionCallbackInfo()
template<typename T >
v8::FunctionCallbackInfo< T >::FunctionCallbackInfo (internal::Address * implicit_args, internal::Address * values, int length) [inline], [private]
Definition at line 615 of file v8-function-callback.h.
    : implicit_args_(implicit_args), values_(values), length_(length) {}
Member Function Documentation
Data()
template<typename T >
Local< Value > v8::FunctionCallbackInfo< T >::Data [inline]
The data argument specified when creating the callback.
Definition at line 639 of file v8-function-callback.h.
                                                 {
  auto target = Local<v8::Data>::FromSlot(&implicit_args_[kTargetIndex]);
  return api_internal::GetFunctionTemplateData(GetIsolate(), target);
}
References v8::Local< T >::FromSlot(), and v8::api_internal::GetFunctionTemplateData().
Referenced by v8_inspector::V8RuntimeAgentImpl::bindingCallback(), v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8_inspector::V8Console::call(), v8::internal::anonymous_namespace{runtime-test.cc}::call_as_function(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8::Worker::Close(), v8::Shell::ModuleResolutionFailureCallback(), v8::Shell::ModuleResolutionSuccessCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::nativeGetterCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::nativeSetterCallback(), v8::Worker::PostMessageOut(), v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback(), v8::internal::ValidateFunctionCallbackInfo(), v8::anonymous_namespace{wasm-js.cc}::WasmStreamingCallbackForTesting(), and v8::anonymous_namespace{wasm-js.cc}::WasmStreamingPromiseFailedCallback().
GetIsolate()
template<typename T >
Isolate * v8::FunctionCallbackInfo< T >::GetIsolate [inline]
The current Isolate.
Definition at line 645 of file v8-function-callback.h.
                                                   {
  return *reinterpret_cast<Isolate**>(&implicit_args_[kIsolateIndex]);
}
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::Add32BitIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAll32BitIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllAnnotateSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllTypedArraySlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AssertIsExternal(), v8::Shell::AsyncHooksCreateHook(), v8::Shell::AsyncHooksExecutionAsyncId(), v8::Shell::AsyncHooksTriggerAsyncId(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AttributeSetterSlowCallback(), v8_inspector::V8RuntimeAgentImpl::bindingCallback(), v8::internal::anonymous_namespace{runtime-test.cc}::call_as_function(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CallToNumberSlowCallback(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8::Shell::ChangeDirectory(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ClampCompareSlowCallback(), v8::Worker::Close(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ComparePointersSlowCallback(), v8::internal::ExternalizeStringExtension::CreateExternalizableString(), v8::internal::ExternalizeStringExtension::CreateExternalizableTwoByteString(), v8::CreateFastCAPIObject(), v8::AsyncHooks::CreateHook(), v8::CreateLeafInterfaceObject(), v8::Shell::CreateRealm(), v8_inspector::V8Console::createTask(), v8::Shell::DisableDebugger(), v8::Shell::DisposeRealm(), v8::Shell::EnableDebugger(), v8::Shell::EnableJSPI(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::EnforceRangeCompareSlowCallback(), v8::Shell::ExecuteFile(), v8::internal::ExternalizeStringExtension::Externalize(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::FastCallCount(), v8::internal::FuzzilliExtension::Fuzzilli(), v8::internal::GCExtension::GC(), v8::internal::StatisticsExtension::GetCounters(), v8::Shell::GetExtrasBindingObject(), v8::internal::IgnitionStatisticsExtension::GetIgnitionDispatchCounters(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::GetNullPointerSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::GetPointerSlowCallback(), v8::GetTimeouts(), v8_inspector::V8Console::inspectedObject(), v8::Shell::InstallConditionalFeatures(), v8::internal::anonymous_namespace{api.cc}::InvokeFunctionCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsFastCApiObjectSlowCallback(), v8::internal::ExternalizeStringExtension::IsOneByte(), v8_inspector::V8Console::keysCallback(), v8::Shell::LogGetAndStop(), v8::Shell::MakeDirectory(), v8::internal::CpuTraceMarkExtension::Mark(), v8::internal::VTuneDomainSupportExtension::Mark(), v8_inspector::V8Console::memoryGetterCallback(), v8::Shell::ModuleResolutionFailureCallback(), v8::Shell::ModuleResolutionSuccessCallback(), v8_inspector::V8Console::monitorFunctionCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::nativeGetterCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::nativeSetterCallback(), v8::Shell::NodeTypeCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::PassPointerSlowCallback(), v8::Shell::PerformanceMark(), v8::Shell::PerformanceMeasure(), v8::Shell::PerformanceMeasureMemory(), v8::Worker::PostMessageOut(), v8::Shell::ProfilerSetOnProfileEndListener(), v8::Shell::ProfilerTriggerSample(), v8_inspector::V8Console::queryObjectsCallback(), v8::Shell::QuitOnce(), v8::Shell::ReadBuffer(), v8::Shell::ReadCodeTypeAndArguments(), v8::Shell::ReadFile(), v8::Shell::ReadLine(), v8::Shell::ReadSource(), v8::Shell::RealmCreateAllowCrossRealmAccess(), v8::Shell::RealmCurrent(), v8::Shell::RealmDetachGlobal(), v8::Shell::RealmDispose(), v8::Shell::RealmEval(), v8::Shell::RealmGlobal(), v8::PerIsolateData::RealmIndexOrThrow(), v8::Shell::RealmNavigate(), v8::Shell::RealmOwner(), v8::Shell::RealmSwitch(), v8::Shell::RemoveDirectory(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ResetCounts(), v8_inspector::V8Console::runTask(), v8::Shell::ScheduleTermination(), v8::InspectorClient::SendInspectorMessage(), v8::Shell::SerializerDeserialize(), v8::Shell::SerializerSerialize(), v8::Shell::SetEnvironment(), v8::Shell::SetFlushDenormals(), v8::Shell::SetPromiseHooks(), v8::Shell::SetTimeout(), v8::Shell::SetUMask(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::SlowCallCount(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsBigIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsNumberSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsBigIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsNumberSlowCallback(), v8::Shell::System(), v8::Shell::TerminateNow(), v8::Shell::TestVerifySourcePositions(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::TestWasmMemorySlowCallback(), v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ThrowFallbackSlowCallback(), v8::Shell::UnsetEnvironment(), v8::anonymous_namespace{async-hooks-wrapper.cc}::UnwrapHook(), v8::internal::ValidateFunctionCallbackInfo(), v8_inspector::V8Console::valuesCallback(), v8::Shell::Version(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::WasmInstanceOverride(), v8::internal::anonymous_namespace{runtime-test-wasm.cc}::WasmModuleOverride(), v8::anonymous_namespace{wasm-js.cc}::WasmStreamingCallbackForTesting(), v8::anonymous_namespace{wasm-js.cc}::WasmStreamingPromiseFailedCallback(), v8::Shell::WorkerGetMessage(), v8::Shell::WorkerNew(), v8::Shell::WorkerOnMessageGetter(), v8::Shell::WorkerOnMessageSetter(), v8::Shell::WorkerPostMessage(), v8::Shell::WorkerTerminate(), v8::Shell::WorkerTerminateAndWait(), v8::Shell::WriteFile(), and v8::WriteToFile().
GetReturnValue()
template<typename T >
ReturnValue< T > v8::FunctionCallbackInfo< T >::GetReturnValue [inline]
The ReturnValue for the call.
Definition at line 650 of file v8-function-callback.h.
                                                             {
  return ReturnValue<T>(&implicit_args_[kReturnValueIndex]);
}
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::Add32BitIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAll32BitIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllAnnotateSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllTypedArraySlowCallback(), v8::Shell::AsyncHooksCreateHook(), v8::Shell::AsyncHooksExecutionAsyncId(), v8::Shell::AsyncHooksTriggerAsyncId(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AttributeGetterSlowCallback(), v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8::internal::anonymous_namespace{runtime-test.cc}::call_as_function(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ClampCompareSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ComparePointersSlowCallback(), v8::internal::ExternalizeStringExtension::CreateExternalizableString(), v8::internal::ExternalizeStringExtension::CreateExternalizableTwoByteString(), v8::Shell::CreateRealm(), v8_inspector::V8Console::createTask(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::EnforceRangeCompareSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::FastCallCount(), v8::internal::GCExtension::GC(), v8::internal::StatisticsExtension::GetCounters(), v8::Shell::GetExtrasBindingObject(), v8::internal::IgnitionStatisticsExtension::GetIgnitionDispatchCounters(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::GetNullPointerSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::GetPointerSlowCallback(), v8_inspector::V8Console::inspectedObject(), v8_inspector::inspectImpl(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsFastCApiObjectSlowCallback(), v8::internal::ExternalizeStringExtension::IsOneByte(), v8_inspector::V8Console::keysCallback(), v8_inspector::V8Console::lastEvaluationResultCallback(), v8::Shell::LogGetAndStop(), v8_inspector::V8Console::memoryGetterCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::nativeGetterCallback(), v8::Shell::NodeTypeCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::PassPointerSlowCallback(), v8::Shell::PerformanceMark(), v8::Shell::PerformanceMeasure(), v8::Shell::PerformanceMeasureMemory(), v8::Shell::PerformanceNow(), v8::Shell::ReadBuffer(), v8::Shell::ReadFile(), v8::Shell::ReadLine(), v8::Shell::RealmCurrent(), v8::Shell::RealmEval(), v8::Shell::RealmGlobal(), v8::Shell::RealmOwner(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ResetCounts(), v8::internal::ReturnNull(), v8_inspector::V8Console::runTask(), v8::InspectorClient::SendInspectorMessage(), v8::Shell::SerializerDeserialize(), v8::Shell::SerializerSerialize(), v8::Shell::SetPromiseHooks(), v8::Shell::SetTimeout(), v8::Shell::SetUMask(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::SlowCallCount(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsBigIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsNumberSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsBigIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsNumberSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::SupportsFPParams(), v8::Shell::System(), v8::internal::ValidateFunctionCallbackInfo(), v8_inspector::V8Console::valuesCallback(), v8::Shell::Version(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileStreaming(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyDescriptorOptionsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionGetArgImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionIsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunctionType(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalType(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstanceGetExportsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstanceImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateStreaming(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryGetBufferImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryGrowImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorMapImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryToFixedLengthBufferImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryToResizableBufferImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryType(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleCustomSectionsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleExportsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImportsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyPromising(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblySuspendingImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGetImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGetLengthImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGrowImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableType(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagType(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyValidateImpl(), v8::Shell::WorkerGetMessage(), and v8::Shell::WorkerOnMessageGetter().
IsConstructCall()
template<typename T >
bool v8::FunctionCallbackInfo< T >::IsConstructCall [inline]
Indicates whether this is a regular call or a construct call.
Definition at line 655 of file v8-function-callback.h.
                                                    {
  return !NewTarget()->IsUndefined();
}
Referenced by v8::CreateFastCAPIObject(), v8::CreateLeafInterfaceObject(), v8::internal::anonymous_namespace{api.cc}::InvokeFunctionCallback(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyDescriptorOptionsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstanceImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblySuspendingImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl(), and v8::Shell::WorkerNew().
Length()
template<typename T >
int v8::FunctionCallbackInfo< T >::Length [inline]
The number of available arguments.
Definition at line 660 of file v8-function-callback.h.
                                          {
  return static_cast<int>(length_);
}
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::Add32BitIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAll32BitIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllAnnotateSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllTypedArraySlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AttributeSetterSlowCallback(), v8_inspector::V8RuntimeAgentImpl::bindingCallback(), v8::internal::anonymous_namespace{runtime-test.cc}::call_as_function(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CallToNumberSlowCallback(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8::Shell::ChangeDirectory(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ClampCompareSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ComparePointersSlowCallback(), v8_inspector::V8Console::copyCallback(), v8::internal::ExternalizeStringExtension::CreateExternalizableString(), v8::internal::ExternalizeStringExtension::CreateExternalizableTwoByteString(), v8::AsyncHooks::CreateHook(), v8_inspector::V8Console::createTask(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::EnforceRangeCompareSlowCallback(), v8::Shell::ExecuteFile(), v8::internal::ExternalizeStringExtension::Externalize(), v8::internal::GCExtension::GC(), v8::internal::StatisticsExtension::GetCounters(), v8::GetTimeouts(), v8_inspector::V8Console::inspectCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsFastCApiObjectSlowCallback(), v8::internal::ExternalizeStringExtension::IsOneByte(), v8::Shell::MakeDirectory(), v8::internal::CpuTraceMarkExtension::Mark(), v8::internal::VTuneDomainSupportExtension::Mark(), v8::Shell::ModuleResolutionFailureCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::nativeSetterCallback(), v8::internal::anonymous_namespace{gc-extension.cc}::Parse(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::PassPointerSlowCallback(), v8::Shell::PerformanceMark(), v8::Shell::PerformanceMeasure(), v8::Shell::PerformanceMeasureMemory(), v8::Worker::PostMessageOut(), v8_inspector::V8Console::queryObjectsCallback(), v8::Shell::ReadCodeTypeAndArguments(), v8::Shell::ReadFile(), v8::Shell::RealmEval(), v8::PerIsolateData::RealmIndexOrThrow(), v8::Shell::RealmOwner(), v8::Shell::RemoveDirectory(), v8_inspector::V8Console::runTask(), v8::Shell::SerializerSerialize(), v8::Shell::SetEnvironment(), v8::Shell::SetFlushDenormals(), v8::Shell::SetTimeout(), v8::Shell::SetUMask(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsBigIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsNumberSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsBigIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsNumberSlowCallback(), v8::Shell::System(), v8::Shell::TestVerifySourcePositions(), v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback(), v8::Shell::UnsetEnvironment(), v8::internal::ValidateFunctionCallbackInfo(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalSetValueImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGrowImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableSetImpl(), v8::Shell::WorkerNew(), v8::Shell::WorkerOnMessageSetter(), v8::Shell::WorkerPostMessage(), v8::Shell::WriteFile(), and v8::WriteToFile().
NewTarget()
template<typename T >
Local< Value > v8::FunctionCallbackInfo< T >::NewTarget [inline]
For construct calls, this returns the `new.target` value.
Definition at line 634 of file v8-function-callback.h.
                                                      {
  return Local<Value>::FromSlot(&implicit_args_[kNewTargetIndex]);
}
References v8::Local< T >::FromSlot().
Referenced by v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl().
operator[]()
template<typename T >
Local< Value > v8::FunctionCallbackInfo< T >::operator[] (int i) const [inline]
Accessor for the available arguments.
Returns undefined if the index is out of bounds.
Definition at line 621 of file v8-function-callback.h.
                                                            {
  // values_ points to the first argument (not the receiver).
  if (i < 0 || Length() <= i) return Undefined(GetIsolate());
  return Local<Value>::FromSlot(values_ + i);
}
References v8::Local< T >::FromSlot(), and v8::Undefined().
This()
template<typename T >
Local< Object > v8::FunctionCallbackInfo< T >::This [inline]
Returns the receiver.
This corresponds to the `this` value.
Definition at line 628 of file v8-function-callback.h.
                                                  {
  // values_ points to the first argument (not the receiver).
  return Local<Object>::FromSlot(values_ + kThisValuesIndex);
}
References v8::Local< T >::FromSlot().
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::Add32BitIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAll32BitIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllAnnotateSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllTypedArraySlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AssertIsExternal(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AttributeGetterSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AttributeSetterSlowCallback(), v8::internal::anonymous_namespace{runtime-test.cc}::call_as_function(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CallToNumberSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ClampCompareSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ComparePointersSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CopyStringSlowCallback(), v8::CreateFastCAPIObject(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::EnforceRangeCompareSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::FastCallCount(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::GetNullPointerSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::GetPointerSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsFastCApiObjectSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::PassPointerSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ResetCounts(), v8_inspector::V8Console::runTask(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::SlowCallCount(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsBigIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsNumberSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsBigIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsNumberSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::SupportsFPParams(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::TestWasmMemorySlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ThrowFallbackSlowCallback(), v8::anonymous_namespace{async-hooks-wrapper.cc}::UnwrapHook(), v8::internal::ValidateFunctionCallbackInfo(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunctionType(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstanceImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl(), v8::Shell::WorkerGetMessage(), v8::Shell::WorkerNew(), v8::Shell::WorkerOnMessageGetter(), v8::Shell::WorkerOnMessageSetter(), v8::Shell::WorkerPostMessage(), v8::Shell::WorkerTerminate(), and v8::Shell::WorkerTerminateAndWait().
Friends And Related Function Documentation
debug::ConsoleCallArguments
template<typename T >
friend class debug::ConsoleCallArguments [friend]
Definition at line 143 of file v8-function-callback.h.
internal::CustomArguments< FunctionCallbackInfo >
template<typename T >
friend class internal::CustomArguments< FunctionCallbackInfo > [friend]
Definition at line 141 of file v8-function-callback.h.
internal::FunctionCallbackArguments
template<typename T >
friend class internal::FunctionCallbackArguments [friend]
Definition at line 141 of file v8-function-callback.h.
internal::PrintFunctionCallbackInfo
template<typename T >
void internal::PrintFunctionCallbackInfo (void *) [friend]
Member Data Documentation
implicit_args_
template<typename T >
internal::Address* v8::FunctionCallbackInfo< T >::implicit_args_ [private]
Definition at line 177 of file v8-function-callback.h.
Referenced by v8::internal::FunctionCallbackArguments::GetTarget().
kArgsLength
template<typename T >
constexpr int v8::FunctionCallbackInfo< T >::kArgsLength = 6 [static], [constexpr], [private]
Definition at line 155 of file v8-function-callback.h.
kArgsLengthWithReceiver
template<typename T >
constexpr int v8::FunctionCallbackInfo< T >::kArgsLengthWithReceiver = kArgsLength + 1 [static], [constexpr], [private]
Definition at line 157 of file v8-function-callback.h.
kContextIndex
template<typename T >
constexpr int v8::FunctionCallbackInfo< T >::kContextIndex = 2 [static], [constexpr], [private]
Definition at line 151 of file v8-function-callback.h.
Referenced by v8::internal::FunctionCallbackArguments::FunctionCallbackArguments().
kImplicitArgsOffset
template<typename T >
constexpr int v8::FunctionCallbackInfo< T >::kImplicitArgsOffset = 0 [static], [constexpr], [private]
Definition at line 161 of file v8-function-callback.h.
kIsolateIndex
template<typename T >
constexpr int v8::FunctionCallbackInfo< T >::kIsolateIndex = 1 [static], [constexpr], [private]
Definition at line 150 of file v8-function-callback.h.
Referenced by v8::internal::FunctionCallbackArguments::FunctionCallbackArguments().
kLengthOffset
template<typename T >
constexpr int v8::FunctionCallbackInfo< T >::kLengthOffset [static], [constexpr], [private]
Initial value:
=
      kValuesOffset + internal::kApiSystemPointerSize
Definition at line 164 of file v8-function-callback.h.
kNewTargetIndex
template<typename T >
constexpr int v8::FunctionCallbackInfo< T >::kNewTargetIndex = 5 [static], [constexpr], [private]
Definition at line 154 of file v8-function-callback.h.
Referenced by v8::internal::FunctionCallbackArguments::FunctionCallbackArguments().
kReturnValueIndex
template<typename T >
constexpr int v8::FunctionCallbackInfo< T >::kReturnValueIndex = 3 [static], [constexpr], [private]
Definition at line 152 of file v8-function-callback.h.
Referenced by v8::internal::FunctionCallbackArguments::FunctionCallbackArguments().
kSize
template<typename T >
constexpr int v8::FunctionCallbackInfo< T >::kSize = 3 * internal::kApiSystemPointerSize [static], [constexpr], [private]
Definition at line 160 of file v8-function-callback.h.
kTargetIndex
template<typename T >
constexpr int v8::FunctionCallbackInfo< T >::kTargetIndex = 4 [static], [constexpr], [private]
Definition at line 153 of file v8-function-callback.h.
Referenced by v8::internal::FunctionCallbackArguments::FunctionCallbackArguments().
kThisValuesIndex
template<typename T >
constexpr int v8::FunctionCallbackInfo< T >::kThisValuesIndex = -1 [static], [constexpr], [private]
Definition at line 167 of file v8-function-callback.h.
kUnusedIndex
template<typename T >
constexpr int v8::FunctionCallbackInfo< T >::kUnusedIndex = 0 [static], [constexpr], [private]
Definition at line 149 of file v8-function-callback.h.
Referenced by v8::internal::FunctionCallbackArguments::FunctionCallbackArguments().
kValuesOffset
template<typename T >
constexpr int v8::FunctionCallbackInfo< T >::kValuesOffset [static], [constexpr], [private]
Initial value:
=
      kImplicitArgsOffset + internal::kApiSystemPointerSize
Definition at line 162 of file v8-function-callback.h.
length_
template<typename T >
internal::Address v8::FunctionCallbackInfo< T >::length_ [private]
Definition at line 179 of file v8-function-callback.h.
values_
template<typename T >
internal::Address* v8::FunctionCallbackInfo< T >::values_ [private]
Definition at line 178 of file v8-function-callback.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/extensions/cputracemark-extension.h
/mnt/V8SourceCode/include/v8-function-callback.h