v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder Class Reference
Public Types
using SmallRegExpTreeVector = SmallZoneVector< RegExpTree *, 8 >
Public Member Functions
RegExpTextBuilder (Zone *zone, SmallRegExpTreeVector *terms_storage, RegExpFlags flags)
void AddCharacter (base::uc16 character)
void AddUnicodeCharacter (base::uc32 character)
void AddEscapedUnicodeCharacter (base::uc32 character)
void AddAtom (RegExpTree *atom)
void AddTerm (RegExpTree *term)
void AddClassRanges (RegExpClassRanges *cc)
void FlushPendingSurrogate ()
void FlushText ()
RegExpTree * PopLastAtom ()
RegExpTree * ToRegExp ()
Private Member Functions
void AddLeadSurrogate (base::uc16 lead_surrogate)
void AddTrailSurrogate (base::uc16 trail_surrogate)
void FlushCharacters ()
bool NeedsDesugaringForUnicode (RegExpClassRanges *cc)
bool NeedsDesugaringForIgnoreCase (base::uc32 c)
void AddClassRangesForDesugaring (base::uc32 c)
bool ignore_case () const
bool IsUnicodeMode () const
Zone * zone () const
Private Attributes
Zone *const zone_
const RegExpFlags flags_
ZoneList< base::uc16 > * characters_ = nullptr
base::uc16 pending_surrogate_ = kNoPendingSurrogate
SmallRegExpTreeVector * terms_
SmallRegExpTreeVector text_
Static Private Attributes
static const base::uc16 kNoPendingSurrogate = 0
Detailed Description
Definition at line 47 of file regexp-parser.cc.
Member Typedef Documentation
SmallRegExpTreeVector
using v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::SmallRegExpTreeVector = SmallZoneVector<RegExpTree*, 8>
Definition at line 49 of file regexp-parser.cc.
Constructor & Destructor Documentation
RegExpTextBuilder()
v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::RegExpTextBuilder (Zone * zone, SmallRegExpTreeVector * terms_storage, RegExpFlags flags) [inline]
Definition at line 51 of file regexp-parser.cc.
      : zone_(zone), flags_(flags), terms_(terms_storage), text_(zone) {}
Member Function Documentation
AddAtom()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddAtom (RegExpTree * atom)
Definition at line 201 of file regexp-parser.cc.
                                                {
  DCHECK(atom->IsTextElement());
  FlushCharacters();
  text_.emplace_back(atom);
}
References v8::internal::DCHECK(), and v8::internal::RegExpTree::IsTextElement().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddAtom().
AddCharacter()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddCharacter (base::uc16 character)
Definition at line 156 of file regexp-parser.cc.
                                               {
  FlushPendingSurrogate();
  if (characters_ == nullptr) {
    characters_ = zone()->New<ZoneList<base::uc16>>(4, zone());
  }
  characters_->Add(c, zone());
}
References v8::internal::ZoneList< T >::Add().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddCharacter().
AddClassRanges()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddClassRanges (RegExpClassRanges * cc)
Definition at line 186 of file regexp-parser.cc.
                                                            {
  if (NeedsDesugaringForUnicode(cr)) {
    // With /u or /v, character class needs to be desugared, so it
    // must be a standalone term instead of being part of a RegExpText.
    AddTerm(cr);
  } else {
    AddAtom(cr);
  }
}
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddClassRanges().
AddClassRangesForDesugaring()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddClassRangesForDesugaring (base::uc32 c) [private]
Definition at line 196 of file regexp-parser.cc.
                                                              {
  AddTerm(zone()->New<RegExpClassRanges>(
      zone(), CharacterRange::List(zone(), CharacterRange::Singleton(c))));
}
References v8::internal::CharacterRange::List(), and v8::internal::CharacterRange::Singleton().
AddEscapedUnicodeCharacter()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddEscapedUnicodeCharacter (base::uc32 character)
Definition at line 178 of file regexp-parser.cc.
                                                                     {
  // A lead or trail surrogate parsed via escape sequence will not
  // pair up with any preceding lead or following trail surrogate.
  FlushPendingSurrogate();
  AddUnicodeCharacter(character);
  FlushPendingSurrogate();
}
References v8::internal::character.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddEscapedUnicodeCharacter().
AddLeadSurrogate()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddLeadSurrogate (base::uc16 lead_surrogate) [private]
Definition at line 90 of file regexp-parser.cc.
                                                                {
  DCHECK(unibrow::Utf16::IsLeadSurrogate(lead_surrogate));
  FlushPendingSurrogate();
  // Hold onto the lead surrogate, waiting for a trail surrogate to follow.
  pending_surrogate_ = lead_surrogate;
}
References v8::internal::DCHECK(), and unibrow::Utf16::IsLeadSurrogate().
AddTerm()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddTerm (RegExpTree * term)
Definition at line 207 of file regexp-parser.cc.
                                                {
  DCHECK(term->IsTextElement());
  FlushText();
  terms_->emplace_back(term);
}
References v8::internal::DCHECK(), and v8::internal::RegExpTree::IsTextElement().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddTerm().
AddTrailSurrogate()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddTrailSurrogate (base::uc16 trail_surrogate) [private]
Definition at line 97 of file regexp-parser.cc.
                                                                  {
  DCHECK(unibrow::Utf16::IsTrailSurrogate(trail_surrogate));
  if (pending_surrogate_ != kNoPendingSurrogate) {
    base::uc16 lead_surrogate = pending_surrogate_;
    pending_surrogate_ = kNoPendingSurrogate;
    DCHECK(unibrow::Utf16::IsLeadSurrogate(lead_surrogate));
    base::uc32 combined =
        unibrow::Utf16::CombineSurrogatePair(lead_surrogate, trail_surrogate);
    if (NeedsDesugaringForIgnoreCase(combined)) {
      AddClassRangesForDesugaring(combined);
    } else {
      ZoneList<base::uc16> surrogate_pair(2, zone());
      surrogate_pair.Add(lead_surrogate, zone());
      surrogate_pair.Add(trail_surrogate, zone());
      RegExpAtom* atom =
          zone()->New<RegExpAtom>(surrogate_pair.ToConstVector());
      AddAtom(atom);
    }
  } else {
    pending_surrogate_ = trail_surrogate;
    FlushPendingSurrogate();
  }
}
References v8::internal::ZoneList< T >::Add(), unibrow::Utf16::CombineSurrogatePair(), v8::internal::DCHECK(), unibrow::Utf16::IsLeadSurrogate(), unibrow::Utf16::IsTrailSurrogate(), and v8::internal::ZoneList< T >::ToConstVector().
AddUnicodeCharacter()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::AddUnicodeCharacter (base::uc32 character)
Definition at line 164 of file regexp-parser.cc.
                                                      {
  if (c > static_cast<base::uc32>(unibrow::Utf16::kMaxNonSurrogateCharCode)) {
    DCHECK(IsUnicodeMode());
    AddLeadSurrogate(unibrow::Utf16::LeadSurrogate(c));
    AddTrailSurrogate(unibrow::Utf16::TrailSurrogate(c));
  } else if (IsUnicodeMode() && unibrow::Utf16::IsLeadSurrogate(c)) {
    AddLeadSurrogate(c);
  } else if (IsUnicodeMode() && unibrow::Utf16::IsTrailSurrogate(c)) {
    AddTrailSurrogate(c);
  } else {
    AddCharacter(static_cast<base::uc16>(c));
  }
}
References v8::internal::DCHECK(), unibrow::Utf16::IsLeadSurrogate(), unibrow::Utf16::IsTrailSurrogate(), unibrow::Utf16::kMaxNonSurrogateCharCode, unibrow::Utf16::LeadSurrogate(), and unibrow::Utf16::TrailSurrogate().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddUnicodeCharacter(), and v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassStringDisjunction().
FlushCharacters()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::FlushCharacters () [private]
Definition at line 130 of file regexp-parser.cc.
                                        {
  FlushPendingSurrogate();
  if (characters_ != nullptr) {
    RegExpTree* atom = zone()->New<RegExpAtom>(characters_->ToConstVector());
    characters_ = nullptr;
    text_.emplace_back(atom);
  }
}
FlushPendingSurrogate()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::FlushPendingSurrogate ()
Definition at line 121 of file regexp-parser.cc.
                                              {
  if (pending_surrogate_ != kNoPendingSurrogate) {
    DCHECK(IsUnicodeMode());
    base::uc32 c = pending_surrogate_;
    pending_surrogate_ = kNoPendingSurrogate;
    AddClassRangesForDesugaring(c);
  }
}
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddEmpty().
FlushText()
void v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::FlushText ()
Definition at line 139 of file regexp-parser.cc.
                                  {
  FlushCharacters();
  size_t num_text = text_.size();
  if (num_text == 0) {
    return;
  } else if (num_text == 1) {
    terms_->emplace_back(text_.back());
  } else {
    RegExpText* text = zone()->New<RegExpText>(zone());
    for (size_t i = 0; i < num_text; i++) {
      text_[i]->AppendToText(text, zone());
    }
    terms_->emplace_back(text);
  }
  text_.clear();
}
References v8::internal::RegExpText::AppendToText(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::FlushText().
ignore_case()
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::ignore_case () const [inline], [private]
Definition at line 74 of file regexp-parser.cc.
{ return IsIgnoreCase(flags_); }
IsUnicodeMode()
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::IsUnicodeMode () const [inline], [private]
Definition at line 75 of file regexp-parser.cc.
                             {
    // Either /v or /u enable UnicodeMode
    // https://tc39.es/ecma262/#sec-parsepattern
    return IsUnicode(flags_) || IsUnicodeSets(flags_);
  }
NeedsDesugaringForIgnoreCase()
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::NeedsDesugaringForIgnoreCase (base::uc32 c) [private]
Definition at line 243 of file regexp-parser.cc.
                                                               {
#ifdef V8_INTL_SUPPORT
  if (IsUnicodeMode() && ignore_case()) {
    icu::UnicodeSet set(c, c);
    set.closeOver(USET_CASE_INSENSITIVE);
    set.removeAllStrings();
    return set.size() > 1;
  }
  // In the case where ICU is not included, we act as if the unicode flag is
  // not set, and do not desugar.
#endif // V8_INTL_SUPPORT
  return false;
}
NeedsDesugaringForUnicode()
bool v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::NeedsDesugaringForUnicode (RegExpClassRanges * cc) [private]
Definition at line 213 of file regexp-parser.cc.
                                                                       {
  if (!IsUnicodeMode()) return false;
  // TODO(yangguo): we could be smarter than this. Case-insensitivity does not
  // necessarily mean that we need to desugar. It's probably nicer to have a
  // separate pass to figure out unicode desugarings.
  if (ignore_case()) return true;
  ZoneList<CharacterRange>* ranges = cc->ranges(zone());
  CharacterRange::Canonicalize(ranges);
  if (cc->is_negated()) {
    ZoneList<CharacterRange>* negated_ranges =
        zone()->New<ZoneList<CharacterRange>>(ranges->length(), zone());
    CharacterRange::Negate(ranges, negated_ranges, zone());
    ranges = negated_ranges;
  }
  for (int i = ranges->length() - 1; i >= 0; i--) {
    base::uc32 from = ranges->at(i).from();
    base::uc32 to = ranges->at(i).to();
    // Check for non-BMP characters.
    if (to >= kNonBmpStart) return true;
    // Check for lone surrogates.
    if (from <= kTrailSurrogateEnd && to >= kLeadSurrogateStart) return true;
  }
  return false;
}
References v8::internal::ZoneList< T >::at(), v8::internal::CharacterRange::Canonicalize(), v8::internal::cc, v8::internal::kLeadSurrogateStart, v8::internal::kNonBmpStart, v8::internal::ZoneList< T >::length(), and v8::internal::CharacterRange::Negate().
PopLastAtom()
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::PopLastAtom ()
Definition at line 257 of file regexp-parser.cc.
                                           {
  FlushPendingSurrogate();
  RegExpTree* atom;
  if (characters_ != nullptr) {
    base::Vector<const base::uc16> char_vector = characters_->ToConstVector();
    int num_chars = char_vector.length();
    if (num_chars > 1) {
      base::Vector<const base::uc16> prefix =
          char_vector.SubVector(0, num_chars - 1);
      text_.emplace_back(zone()->New<RegExpAtom>(prefix));
      char_vector = char_vector.SubVector(num_chars - 1, num_chars);
    }
    characters_ = nullptr;
    atom = zone()->New<RegExpAtom>(char_vector);
    return atom;
  } else if (!text_.empty()) {
    atom = text_.back();
    text_.pop_back();
    return atom;
  }
  return nullptr;
}
References v8::base::Vector< T >::length(), and v8::base::Vector< T >::SubVector().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::AddQuantifierToAtom().
ToRegExp()
RegExpTree * v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::ToRegExp ()
Definition at line 280 of file regexp-parser.cc.
                                        {
  FlushText();
  size_t number_of_terms = terms_->size();
  if (number_of_terms == 0) return zone()->New<RegExpEmpty>();
  if (number_of_terms == 1) return terms_->back();
  return zone()->New<RegExpAlternative>(zone()->New<ZoneList<RegExpTree*>>(
      base::VectorOf(terms_->begin(), terms_->size()), zone()));
}
References v8::base::VectorOf().
Referenced by v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpParserImpl< CharT >::ParseClassStringDisjunction().
zone()
Zone* v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::zone () const [inline], [private]
Definition at line 80 of file regexp-parser.cc.
{ return zone_; }
Member Data Documentation
characters_
ZoneList<base::uc16>* v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::characters_ = nullptr [private]
Definition at line 84 of file regexp-parser.cc.
flags_
const RegExpFlags v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::flags_ [private]
Definition at line 83 of file regexp-parser.cc.
kNoPendingSurrogate
const base::uc16 v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::kNoPendingSurrogate = 0 [static], [private]
Definition at line 66 of file regexp-parser.cc.
pending_surrogate_
base::uc16 v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::pending_surrogate_ = kNoPendingSurrogate [private]
Definition at line 85 of file regexp-parser.cc.
terms_
SmallRegExpTreeVector* v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::terms_ [private]
Definition at line 86 of file regexp-parser.cc.
text_
SmallRegExpTreeVector v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::text_ [private]
Definition at line 87 of file regexp-parser.cc.
zone_
Zone* const v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpTextBuilder::zone_ [private]
Definition at line 82 of file regexp-parser.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-parser.cc