v8::internal::Managed< CppType > Class Template Reference
#include <managed.h>
Public Member Functions
Managed ()
Managed (Address ptr)
constexpr Managed (Address ptr, SkipTypeCheckTag)
Managed * operator-> ()
const Managed * operator-> () const
CppType * raw ()
const std::shared_ptr< CppType > & get ()
size_t estimated_size () const
Static Public Member Functions
static DirectHandle< Managed< CppType > > From (Isolate *isolate, size_t estimated_size, std::shared_ptr< CppType > shared_ptr, AllocationType allocation_type=AllocationType::kYoung)
Private Member Functions
ManagedPtrDestructor * GetDestructor () const
std::shared_ptr< CppType > * GetSharedPtrPtr ()
Friends
class Tagged< Managed >
Additional Inherited Members
Detailed Description
template<class CppType>
class v8::internal::Managed< CppType >
Definition at line 94 of file managed.h.
Constructor & Destructor Documentation
Managed() [1/3]
template<class CppType >
v8::internal::Managed< CppType >::Managed () [inline]
Definition at line 96 of file managed.h.
: Foreign() {}
Managed() [2/3]
template<class CppType >
v8::internal::Managed< CppType >::Managed (Address ptr) [inline], [explicit]
Definition at line 97 of file managed.h.
: Foreign(ptr) {}
Managed() [3/3]
template<class CppType >
constexpr v8::internal::Managed< CppType >::Managed (Address ptr, SkipTypeCheckTag) [inline], [constexpr]
Definition at line 98 of file managed.h.
      : Foreign(ptr, SkipTypeCheckTag{}) {}
Member Function Documentation
estimated_size()
template<class CppType >
size_t v8::internal::Managed< CppType >::estimated_size () const [inline]
Definition at line 113 of file managed.h.
{ return GetDestructor()->estimated_size_; }
From()
template<class CppType >
DirectHandle< Managed< CppType > > v8::internal::Managed< CppType >::From (Isolate * isolate, size_t estimated_size, std::shared_ptr< CppType > shared_ptr, AllocationType allocation_type = AllocationType::kYoung) [static]
Definition at line 27 of file managed-inl.h.
                                                                       {
  static constexpr ExternalPointerTag kTag = TagForManaged<CppType>::value;
  static_assert(IsManagedExternalPointerType(kTag));
  auto destructor = new ManagedPtrDestructor(
      estimated_size, new std::shared_ptr<CppType>{std::move(shared_ptr)},
      detail::Destructor<CppType>);
  destructor->external_memory_accounter_.Increase(
      reinterpret_cast<v8::Isolate*>(isolate), estimated_size);
  DirectHandle<Managed<CppType>> handle =
      Cast<Managed<CppType>>(isolate->factory()->NewForeign<kTag>(
          reinterpret_cast<Address>(destructor), allocation_type));
  IndirectHandle<Object> global_handle =
      isolate->global_handles()->Create(*handle);
  destructor->global_handle_location_ = global_handle.location();
  GlobalHandles::MakeWeak(destructor->global_handle_location_, destructor,
                          &ManagedObjectFinalizer,
                          v8::WeakCallbackType::kParameter);
  isolate->RegisterManagedPtrDestructor(destructor);
  return handle;
}
References v8::internal::GlobalHandles::Create(), v8::internal::ManagedPtrDestructor::external_memory_accounter_, v8::internal::Isolate::factory(), v8::internal::Isolate::global_handles(), v8::internal::handle(), v8::ExternalMemoryAccounter::Increase(), v8::internal::IsManagedExternalPointerType(), v8::kParameter, v8::internal::GlobalHandles::MakeWeak(), v8::internal::ManagedObjectFinalizer(), v8::internal::Factory::NewForeign(), and v8::internal::Isolate::RegisterManagedPtrDestructor().
Referenced by v8::internal::anonymous_namespace{js-locale.cc}::Construct(), v8::internal::anonymous_namespace{js-temporal-objects.cc}::ConstructRustWrappingType(), v8::internal::JSSegments::Create(), v8::internal::JSSegmentIterator::Create(), v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::AsyncHooks::CreateHook(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::wasm::GetOrCreateInterpreterHandle(), v8::anonymous_namespace{d8.cc}::InitializeModuleEmbedderData(), v8::internal::anonymous_namespace{js-date-time-format.cc}::LazyCreateDateIntervalFormat(), wasm::anonymous_namespace{c-api.cc}::make_func(), v8::internal::JSV8BreakIterator::New(), v8::internal::JSDisplayNames::New(), v8::internal::JSDurationFormat::New(), v8::internal::JSListFormat::New(), v8::internal::JSPluralRules::New(), v8::internal::JSRelativeTimeFormat::New(), v8::internal::JSSegmenter::New(), v8::internal::JSCollator::New(), v8::internal::JSNumberFormat::New(), v8::internal::JSLocale::New(), v8::internal::AsmWasmData::New(), v8::internal::WasmModuleObject::New(), wasm::StoreImpl::SetHostInfo(), v8::internal::Intl::SetTextToBreakIterator(), v8::anonymous_namespace{wasm-js.cc}::StartAsyncCompilationWithResolver(), and v8::Shell::WorkerNew().
get()
template<class CppType >
const std::shared_ptr<CppType>& v8::internal::Managed< CppType >::get () [inline]
Definition at line 110 of file managed.h.
{ return *GetSharedPtrPtr(); }
GetDestructor()
template<class CppType >
ManagedPtrDestructor* v8::internal::Managed< CppType >::GetDestructor () const [inline], [private]
Definition at line 127 of file managed.h.
                                              {
    static constexpr ExternalPointerTag kTag = TagForManaged<CppType>::value;
    return reinterpret_cast<ManagedPtrDestructor*>(foreign_address<kTag>());
  }
GetSharedPtrPtr()
template<class CppType >
std::shared_ptr<CppType>* v8::internal::Managed< CppType >::GetSharedPtrPtr () [inline], [private]
Definition at line 132 of file managed.h.
                                            {
    return reinterpret_cast<std::shared_ptr<CppType>*>(
        GetDestructor()->shared_ptr_ptr_);
  }
operator->() [1/2]
template<class CppType >
Managed* v8::internal::Managed< CppType >::operator-> () [inline]
Definition at line 103 of file managed.h.
{ return this; }
operator->() [2/2]
template<class CppType >
const Managed* v8::internal::Managed< CppType >::operator-> () const [inline]
Definition at line 104 of file managed.h.
{ return this; }
raw()
template<class CppType >
CppType* v8::internal::Managed< CppType >::raw () [inline]
Definition at line 107 of file managed.h.
{ return GetSharedPtrPtr()->get(); }
Referenced by v8::internal::wasm::InterpreterHandle::GetInstanceObject().
Friends And Related Function Documentation
Tagged< Managed >
template<class CppType >
friend class Tagged< Managed > [friend]
Definition at line 117 of file managed.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/managed.h
/mnt/V8SourceCode/src/objects/managed-inl.h