v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator Class Reference
#include <persistent-map.h>
Public Member Functions
std::tuple< Key, Value, Value > operator* ()
double_iterator & operator++ ()
double_iterator (iterator first, iterator second)
bool operator!= (const double_iterator &other)
bool is_end () const
Private Attributes
iterator first_
iterator second_
bool first_current_
bool second_current_
Detailed Description
template<class Key, class Value, class Hasher = base::hash<Key>>
class v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator
Definition at line 342 of file persistent-map.h.
Constructor & Destructor Documentation
double_iterator()
template<class Key , class Value , class Hasher = base::hash<Key>>
v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator::double_iterator (iterator first, iterator second) [inline]
Definition at line 373 of file persistent-map.h.
      : first_(first), second_(second) {
    if (first_ == second_) {
      first_current_ = second_current_ = true;
    } else if (first_ < second_) {
      first_current_ = true;
      second_current_ = false;
    } else {
      DCHECK(second_ < first_);
      first_current_ = false;
      second_current_ = true;
    }
  }
References v8::internal::DCHECK().
Member Function Documentation
is_end()
template<class Key , class Value , class Hasher = base::hash<Key>>
bool v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator::is_end () const [inline]
Definition at line 391 of file persistent-map.h.
{ return first_.is_end() && second_.is_end(); }
operator!=()
template<class Key , class Value , class Hasher = base::hash<Key>>
bool v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator::operator!= (const double_iterator & other) [inline]
Definition at line 387 of file persistent-map.h.
                                                {
    return first_ != other.first_ || second_ != other.second_;
  }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator::first_, and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator::second_.
operator*()
template<class Key , class Value , class Hasher = base::hash<Key>>
std::tuple<Key, Value, Value> v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator::operator* () [inline]
Definition at line 344 of file persistent-map.h.
                                          {
    if (first_current_) {
      auto pair = *first_;
      return std::make_tuple(
          pair.first, pair.second,
          second_current_ ? (*second_).second : second_.def_value());
    } else {
      DCHECK(second_current_);
      auto pair = *second_;
      return std::make_tuple(pair.first, first_.def_value(), pair.second);
    }
  }
References v8::internal::DCHECK().
operator++()
template<class Key , class Value , class Hasher = base::hash<Key>>
double_iterator& v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator::operator++ () [inline]
Definition at line 357 of file persistent-map.h.
                                {
#ifdef DEBUG
    iterator old_first = first_;
    iterator old_second = second_;
#endif
    if (first_current_) {
      ++first_;
      DCHECK(old_first < first_);
    }
    if (second_current_) {
      ++second_;
      DCHECK(old_second < second_);
    }
    return *this = double_iterator(first_, second_);
  }
References v8::internal::DCHECK().
Member Data Documentation
first_
template<class Key , class Value , class Hasher = base::hash<Key>>
iterator v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator::first_ [private]
Definition at line 394 of file persistent-map.h.
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator::operator!=().
first_current_
template<class Key , class Value , class Hasher = base::hash<Key>>
bool v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator::first_current_ [private]
Definition at line 396 of file persistent-map.h.
second_
template<class Key , class Value , class Hasher = base::hash<Key>>
iterator v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator::second_ [private]
Definition at line 395 of file persistent-map.h.
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator::operator!=().
second_current_
template<class Key , class Value , class Hasher = base::hash<Key>>
bool v8::internal::compiler::PersistentMap< Key, Value, Hasher >::double_iterator::second_current_ [private]
Definition at line 397 of file persistent-map.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/persistent-map.h