v8::internal::IndexGenerator Class Reference
#include <index-generator.h>
Public Member Functions
IndexGenerator (size_t size)
IndexGenerator (const IndexGenerator &)=delete
IndexGenerator & operator= (const IndexGenerator &)=delete
std::optional< size_t > GetNext ()
Private Attributes
base::Mutex lock_
bool first_use_
std::queue< std::pair< size_t, size_t > > ranges_to_split_
Detailed Description
Definition at line 20 of file index-generator.h.
Constructor & Destructor Documentation
IndexGenerator() [1/2]
v8::internal::IndexGenerator::IndexGenerator (size_t size) [explicit]
Definition at line 12 of file index-generator.cc.
                                          : first_use_(size > 0) {
  if (size == 0) return;
  base::MutexGuard guard(&lock_);
  ranges_to_split_.emplace(0, size);
}
References lock_, ranges_to_split_, and size().
IndexGenerator() [2/2]
v8::internal::IndexGenerator::IndexGenerator (const IndexGenerator &) [delete]
Member Function Documentation
GetNext()
std::optional< size_t > v8::internal::IndexGenerator::GetNext ()
Definition at line 18 of file index-generator.cc.
                                            {
  base::MutexGuard guard(&lock_);
  if (first_use_) {
    first_use_ = false;
    return 0;
  }
  if (ranges_to_split_.empty()) return std::nullopt;
  // Split the oldest running range in 2 and return the middle index as
  // starting point.
  auto range = ranges_to_split_.front();
  ranges_to_split_.pop();
  size_t size = range.second - range.first;
  size_t mid = range.first + size / 2;
  // Both sides of the range are added to |ranges_to_split_| so they may be
  // further split if possible.
  if (mid - range.first > 1) ranges_to_split_.emplace(range.first, mid);
  if (range.second - mid > 1) ranges_to_split_.emplace(mid, range.second);
  return mid;
}
References first_use_, lock_, ranges_to_split_, and size().
Referenced by v8::internal::YoungGenerationRememberedSetsMarkingWorklist::ProcessNextItem().
operator=()
IndexGenerator& v8::internal::IndexGenerator::operator= (const IndexGenerator &) [delete]
Member Data Documentation
first_use_
bool v8::internal::IndexGenerator::first_use_ [private]
Definition at line 30 of file index-generator.h.
Referenced by GetNext().
lock_
base::Mutex v8::internal::IndexGenerator::lock_ [private]
Definition at line 29 of file index-generator.h.
Referenced by GetNext(), and IndexGenerator().
ranges_to_split_
std::queue<std::pair<size_t, size_t> > v8::internal::IndexGenerator::ranges_to_split_ [private]
Definition at line 32 of file index-generator.h.
Referenced by GetNext(), and IndexGenerator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/index-generator.h
/mnt/V8SourceCode/src/heap/index-generator.cc