v8::base::OwnedVector< T > Class Template Reference
#include <vector.h>
Public Member Functions
OwnedVector ()=default
OwnedVector (std::unique_ptr< T[]> data, size_t length)
OwnedVector (const OwnedVector &)=delete
OwnedVector & operator= (const OwnedVector &)=delete
template<typename U >
requires std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T > > OwnedVector (OwnedVector< U > &&other) V8_NOEXCEPT
template<typename U >
requires std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T > > OwnedVector & operator= (OwnedVector< U > &&other) V8_NOEXCEPT
constexpr size_t size () const
constexpr bool empty () const
constexpr T * begin () const
constexpr T * end () const
constexpr T * data () const
constexpr std::reverse_iterator< T * > rbegin () const
constexpr std::reverse_iterator< T * > rend () const
T & operator[] (size_t index) const
Vector< T > as_vector () const
std::unique_ptr< T[]> ReleaseData ()
bool operator== (std::nullptr_t) const
Static Public Member Functions
static OwnedVector< T > New (size_t size)
template<typename U >
static OwnedVector< T > New (size_t size, U init)
static OwnedVector< T > NewForOverwrite (size_t size)
template<typename U >
static OwnedVector< U > NewByCopying (const U *data, size_t size)
Private Attributes
std::unique_ptr< T[]> data_
size_t length_ = 0
Friends
template<typename U >
class OwnedVector
Detailed Description
template<typename T>
class v8::base::OwnedVector< T >
Definition at line 199 of file vector.h.
Constructor & Destructor Documentation
OwnedVector() [1/4]
template<typename T >
v8::base::OwnedVector< T >::OwnedVector () [default]
OwnedVector() [2/4]
template<typename T >
v8::base::OwnedVector< T >::OwnedVector (std::unique_ptr< T[]> data, size_t length) [inline]
Definition at line 203 of file vector.h.
      : data_(std::move(data)), length_(length) {
    DCHECK_IMPLIES(length_ > 0, data_ != nullptr);
  }
References v8::base::OwnedVector< T >::data_, DCHECK_IMPLIES, and v8::base::OwnedVector< T >::length_.
OwnedVector() [3/4]
template<typename T >
v8::base::OwnedVector< T >::OwnedVector (const OwnedVector< T > &) [delete]
OwnedVector() [4/4]
template<typename T >
template<typename U >
requires std::is_convertible_v<std::unique_ptr<U>, std::unique_ptr<T> > v8::base::OwnedVector< T >::OwnedVector (OwnedVector< U > && other) [inline]
Definition at line 220 of file vector.h.
                                                  {
    *this = std::move(other);
  }
Member Function Documentation
as_vector()
template<typename T >
Vector<T> v8::base::OwnedVector< T >::as_vector () const [inline]
Definition at line 266 of file vector.h.
{ return {begin(), size()}; }
References v8::base::OwnedVector< T >::begin(), and v8::base::OwnedVector< T >::size().
Referenced by v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::WasmEngine::AsyncCompile(), v8::internal::wasm::DeserializeNativeModule(), v8::internal::wasm::DeserializeTypeFeedback(), v8::internal::wasm::AsmJsOffsetInformation::EnsureDecodedOffsets(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishFunction(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetOrCompileNewNativeModule(), v8::internal::wasm::LoadProfileFromFile(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::WasmEngine::SyncCompile(), and v8::internal::wasm::WasmEngine::SyncCompileTranslatedAsmJs().
begin()
template<typename T >
constexpr T* v8::base::OwnedVector< T >::begin () const [inline], [constexpr]
Definition at line 241 of file vector.h.
                             {
    DCHECK_IMPLIES(length_ > 0, data_ != nullptr);
    return data_.get();
  }
References v8::base::OwnedVector< T >::data_, DCHECK_IMPLIES, and v8::base::OwnedVector< T >::length_.
Referenced by v8::base::OwnedVector< T >::as_vector(), v8::base::OwnedVector< T >::data(), v8::internal::wasm::DumpProfileToFile(), v8::base::OwnedVector< T >::end(), v8::internal::ProfilerListener::GetName(), v8::internal::wasm::LoadProfileFromFile(), v8::base::OwnedVector< T >::New(), v8::base::OwnedVector< T >::rend(), and v8::anonymous_namespace{wasm-js.cc}::WasmStreamingCallbackForTesting().
data()
template<typename T >
constexpr T* v8::base::OwnedVector< T >::data () const [inline], [constexpr]
Definition at line 250 of file vector.h.
{ return begin(); }
References v8::base::OwnedVector< T >::begin().
Referenced by v8::base::OwnedVector< T >::NewByCopying().
empty()
template<typename T >
constexpr bool v8::base::OwnedVector< T >::empty () const [inline], [constexpr]
Definition at line 239 of file vector.h.
{ return length_ == 0; }
References v8::base::OwnedVector< T >::length_.
Referenced by v8::internal::wasm::WasmEngine::AsyncCompile(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishFunction(), v8::anonymous_namespace{wasm-js.cc}::WasmStreamingCallbackForTesting(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyCompileImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl().
end()
template<typename T >
constexpr T* v8::base::OwnedVector< T >::end () const [inline], [constexpr]
Definition at line 246 of file vector.h.
{ return begin() + length_; }
References v8::base::OwnedVector< T >::begin(), and v8::base::OwnedVector< T >::length_.
Referenced by v8::base::OwnedVector< T >::rbegin().
New() [1/2]
template<typename T >
static OwnedVector<T> v8::base::OwnedVector< T >::New (size_t size) [inline], [static]
Definition at line 277 of file vector.h.
                                         {
    if (size == 0) return {};
    return OwnedVector<T>(std::make_unique<T[]>(size), size);
  }
References v8::base::OwnedVector< T >::size().
Referenced by v8::internal::OptimizingCompileTaskExecutor::EnsureStarted(), v8::internal::WasmExportedFunction::GetDebugName(), v8::internal::ProfilerListener::GetName(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgress(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationProgressAfterDeserialization(), v8::internal::wasm::WasmDeoptDataProcessor::Serialize(), and v8::internal::wasm::WasmFunctionCoverageData::WasmFunctionCoverageData().
New() [2/2]
template<typename T >
template<typename U >
static OwnedVector<T> v8::base::OwnedVector< T >::New (size_t size, U init) [inline], [static]
Definition at line 285 of file vector.h.
                                                 {
    if (size == 0) return {};
    OwnedVector<T> vec = NewForOverwrite(size);
    std::fill_n(vec.begin(), size, init);
    return vec;
  }
References v8::base::OwnedVector< T >::begin(), v8::base::OwnedVector< T >::NewForOverwrite(), and v8::base::OwnedVector< T >::size().
NewByCopying()
template<typename T >
template<typename U >
static OwnedVector<U> v8::base::OwnedVector< T >::NewByCopying (const U * data, size_t size) [inline], [static]
Definition at line 303 of file vector.h.
                                                                 {
    auto result = OwnedVector<U>::NewForOverwrite(size);
    std::copy(data, data + size, result.begin());
    return result;
  }
References v8::base::OwnedVector< T >::data(), v8::base::OwnedVector< T >::NewForOverwrite(), v8::base::internal::result, and v8::base::OwnedVector< T >::size().
Referenced by v8::internal::wasm::DecodeCanonicalTypeNames(), and v8::base::OwnedCopyOf().
NewForOverwrite()
template<typename T >
static OwnedVector<T> v8::base::OwnedVector< T >::NewForOverwrite (size_t size) [inline], [static]
Definition at line 294 of file vector.h.
                                                     {
    if (size == 0) return {};
    return OwnedVector<T>(std::make_unique_for_overwrite<T[]>(size), size);
  }
References v8::base::OwnedVector< T >::size().
Referenced by v8::internal::wasm::DeserializeTypeFeedback(), v8::internal::wasm::AsyncStreamingDecoder::Finish(), v8::internal::wasm::SyncStreamingDecoder::Finish(), v8::anonymous_namespace{wasm-js.cc}::GetAndCopyFirstArgumentAsBytes(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetCurrentDebugSideTableEntries(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GetStackValueTypesForDebugging(), v8::internal::wasm::ValidateFunctionsStreamingJobData::Initialize(), v8::internal::wasm::LoadProfileFromFile(), v8::base::OwnedVector< T >::New(), v8::base::OwnedVector< T >::NewByCopying(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyValidateImpl().
operator=() [1/2]
template<typename T >
OwnedVector& v8::base::OwnedVector< T >::operator= (const OwnedVector< T > &) [delete]
operator=() [2/2]
template<typename T >
template<typename U >
requires std::is_convertible_v<std::unique_ptr<U>, std::unique_ptr<T> > OwnedVector& v8::base::OwnedVector< T >::operator= (OwnedVector< U > && other) [inline]
Definition at line 226 of file vector.h.
                                                             {
    static_assert(sizeof(U) == sizeof(T));
    data_ = std::move(other.data_);
    length_ = other.length_;
    DCHECK_NULL(other.data_);
    other.length_ = 0;
    return *this;
  }
References v8::base::OwnedVector< T >::data_, DCHECK_NULL, v8::base::OwnedVector< T >::length_, and v8::base::internal::U.
operator==()
template<typename T >
bool v8::base::OwnedVector< T >::operator== (std::nullptr_t) const [inline]
Definition at line 309 of file vector.h.
{ return data_ == nullptr; }
References v8::base::OwnedVector< T >::data_.
operator[]()
template<typename T >
T& v8::base::OwnedVector< T >::operator[] (size_t index) const [inline]
Definition at line 260 of file vector.h.
                                    {
    DCHECK_LT(index, length_);
    return data_[index];
  }
References v8::base::OwnedVector< T >::data_, DCHECK_LT, v8::internal::index, and v8::base::OwnedVector< T >::length_.
rbegin()
template<typename T >
constexpr std::reverse_iterator<T*> v8::base::OwnedVector< T >::rbegin () const [inline], [constexpr]
Definition at line 252 of file vector.h.
                                                   {
    return std::make_reverse_iterator(end());
  }
References v8::base::OwnedVector< T >::end().
ReleaseData()
template<typename T >
std::unique_ptr<T[]> v8::base::OwnedVector< T >::ReleaseData () [inline]
Definition at line 270 of file vector.h.
                                   {
    length_ = 0;
    return std::move(data_);
  }
References v8::base::OwnedVector< T >::data_, and v8::base::OwnedVector< T >::length_.
Referenced by v8::internal::wasm::AsmJsOffsetInformation::EnsureDecodedOffsets().
rend()
template<typename T >
constexpr std::reverse_iterator<T*> v8::base::OwnedVector< T >::rend () const [inline], [constexpr]
Definition at line 255 of file vector.h.
                                                 {
    return std::make_reverse_iterator(begin());
  }
References v8::base::OwnedVector< T >::begin().
size()
template<typename T >
constexpr size_t v8::base::OwnedVector< T >::size () const [inline], [constexpr]
Definition at line 236 of file vector.h.
{ return length_; }
References v8::base::OwnedVector< T >::length_.
Referenced by v8::base::OwnedVector< T >::as_vector(), v8::internal::wasm::ContentSize(), v8::internal::wasm::DumpProfileToFile(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::InitializeCompilationUnits(), v8::internal::wasm::InliningTree::Inline(), v8::base::OwnedVector< T >::New(), v8::base::OwnedVector< T >::NewByCopying(), v8::base::OwnedVector< T >::NewForOverwrite(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits(), v8::internal::wasm::TransitiveTypeFeedbackProcessor::ProcessFunction(), v8::internal::anonymous_namespace{builtins-regexp.cc}::RegExpEscapeImpl(), v8::internal::wasm::ProfileGenerator::SerializeTypeFeedback(), and v8::anonymous_namespace{wasm-js.cc}::WasmStreamingCallbackForTesting().
Friends And Related Function Documentation
OwnedVector
template<typename T >
template<typename U >
friend class OwnedVector [friend]
Definition at line 313 of file vector.h.
Member Data Documentation
data_
template<typename T >
std::unique_ptr<T[]> v8::base::OwnedVector< T >::data_ [private]
Definition at line 315 of file vector.h.
Referenced by v8::base::OwnedVector< T >::begin(), v8::base::OwnedVector< T >::operator=(), v8::base::OwnedVector< T >::operator==(), v8::base::OwnedVector< T >::operator[](), v8::base::OwnedVector< T >::OwnedVector(), and v8::base::OwnedVector< T >::ReleaseData().
length_
template<typename T >
size_t v8::base::OwnedVector< T >::length_ = 0 [private]
Definition at line 316 of file vector.h.
Referenced by v8::base::OwnedVector< T >::begin(), v8::base::OwnedVector< T >::empty(), v8::base::OwnedVector< T >::end(), v8::base::OwnedVector< T >::operator=(), v8::base::OwnedVector< T >::operator[](), v8::base::OwnedVector< T >::OwnedVector(), v8::base::OwnedVector< T >::ReleaseData(), and v8::base::OwnedVector< T >::size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/vector.h