v8::internal::compiler::PersistentMap< Key, Value, Hasher > Class Template Reference
#include <persistent-map.h>
Classes
class double_iterator
struct FocusedTree
class HashValue
class iterator
struct KeyValue
struct ZipIterable
Public Types
using key_type = Key
using mapped_type = Value
using value_type = std::pair< Key, Value >
Public Member Functions
size_t last_depth () const
const Value & Get (const Key &key) const
void Set (Key key, Value value)
template<class F >
void Modify (Key key, F f)
bool operator== (const PersistentMap &other) const
bool operator!= (const PersistentMap &other) const
iterator begin () const
iterator end () const
ZipIterable Zip (const PersistentMap &other) const
PersistentMap (Zone *zone, Value def_value=Value())
Private Types
enum Bit : int { kLeft = 0
, kRight = 1
 }
Private Member Functions
const FocusedTree * FindHash (HashValue hash) const
const FocusedTree * FindHash (HashValue hash, std::array< const FocusedTree *, kHashBits > *path, int *length) const
const Value & GetFocusedValue (const FocusedTree *tree, const Key &key) const
PersistentMap (const FocusedTree *tree, Zone *zone, Value def_value)
Static Private Member Functions
static const FocusedTree * GetChild (const FocusedTree *tree, int level, Bit bit)
static const FocusedTree * FindLeftmost (const FocusedTree *start, int *level, std::array< const FocusedTree *, kHashBits > *path)
Private Attributes
const FocusedTree * tree_
Value def_value_
Zone * zone_
Static Private Attributes
static constexpr size_t kHashBits = 32
Friends
struct may_be_unequal< PersistentMap< Key, Value, Hasher > >
Detailed Description
template<class Key, class Value, class Hasher = base::hash<Key>>
class v8::internal::compiler::PersistentMap< Key, Value, Hasher >
Definition at line 43 of file persistent-map.h.
Member Typedef Documentation
key_type
template<class Key , class Value , class Hasher = base::hash<Key>>
using v8::internal::compiler::PersistentMap< Key, Value, Hasher >::key_type = Key
Definition at line 45 of file persistent-map.h.
mapped_type
template<class Key , class Value , class Hasher = base::hash<Key>>
using v8::internal::compiler::PersistentMap< Key, Value, Hasher >::mapped_type = Value
Definition at line 46 of file persistent-map.h.
value_type
template<class Key , class Value , class Hasher = base::hash<Key>>
using v8::internal::compiler::PersistentMap< Key, Value, Hasher >::value_type = std::pair<Key, Value>
Definition at line 47 of file persistent-map.h.
Member Enumeration Documentation
Bit
template<class Key , class Value , class Hasher = base::hash<Key>>
enum v8::internal::compiler::PersistentMap::Bit : int [private]
Enumerator
kLeft
kRight
Definition at line 51 of file persistent-map.h.
: int { kLeft = 0, kRight = 1 };
Constructor & Destructor Documentation
PersistentMap() [1/2]
template<class Key , class Value , class Hasher = base::hash<Key>>
v8::internal::compiler::PersistentMap< Key, Value, Hasher >::PersistentMap (Zone * zone, Value def_value = Value()) [inline], [explicit]
Definition at line 131 of file persistent-map.h.
      : PersistentMap(nullptr, zone, def_value) {}
PersistentMap() [2/2]
template<class Key , class Value , class Hasher = base::hash<Key>>
v8::internal::compiler::PersistentMap< Key, Value, Hasher >::PersistentMap (const FocusedTree * tree, Zone * zone, Value def_value) [inline], [private]
Definition at line 163 of file persistent-map.h.
      : tree_(tree), def_value_(def_value), zone_(zone) {}
Member Function Documentation
begin()
template<class Key , class Value , class Hasher = base::hash<Key>>
iterator v8::internal::compiler::PersistentMap< Key, Value, Hasher >::begin () const [inline]
Definition at line 110 of file persistent-map.h.
                         {
    if (!tree_) return end();
    return iterator::begin(tree_, def_value_);
  }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::begin(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::def_value_, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::end(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::tree_.
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::ZipIterable::begin(), and v8::internal::compiler::VariableTracker::State::begin().
end()
template<class Key , class Value , class Hasher = base::hash<Key>>
iterator v8::internal::compiler::PersistentMap< Key, Value, Hasher >::end () const [inline]
Definition at line 114 of file persistent-map.h.
{ return iterator::end(def_value_); }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::def_value_, and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::end().
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::begin(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::ZipIterable::end(), v8::internal::compiler::VariableTracker::State::end(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator++().
FindHash() [1/2]
template<class Key , class Value , class Hasher >
const PersistentMap< Key, Value, Hasher >::FocusedTree * v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FindHash (HashValue hash) const [private]
Definition at line 445 of file persistent-map.h.
                                                                {
  const FocusedTree* tree = tree_;
  int level = 0;
  while (tree && hash != tree->key_hash) {
    while ((hash ^ tree->key_hash)[level] == 0) {
      ++level;
    }
    tree = level < tree->length ? tree->path(level) : nullptr;
    ++level;
  }
  return tree;
}
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::key_hash, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::length, and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::path().
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Get().
FindHash() [2/2]
template<class Key , class Value , class Hasher >
const PersistentMap< Key, Value, Hasher >::FocusedTree * v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FindHash (HashValue hash, std::array< const FocusedTree *, kHashBits > * path, int * length) const [private]
Definition at line 460 of file persistent-map.h.
                       {
  const FocusedTree* tree = tree_;
  int level = 0;
  while (tree && hash != tree->key_hash) {
    int map_length = tree->length;
    while ((hash ^ tree->key_hash)[level] == 0) {
      (*path)[level] = level < map_length ? tree->path(level) : nullptr;
      ++level;
    }
    (*path)[level] = tree;
    tree = level < tree->length ? tree->path(level) : nullptr;
    ++level;
  }
  if (tree) {
    while (level < tree->length) {
      (*path)[level] = tree->path(level);
      ++level;
    }
  }
  *length = level;
  return tree;
}
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::key_hash, v8::internal::length, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::length, and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::path().
FindLeftmost()
template<class Key , class Value , class Hasher >
const PersistentMap< Key, Value, Hasher >::FocusedTree * v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FindLeftmost (const FocusedTree * start, int * level, std::array< const FocusedTree *, kHashBits > * path) [static], [private]
Definition at line 521 of file persistent-map.h.
                                                   {
  const FocusedTree* current = start;
  while (*level < current->length) {
    if (const FocusedTree* left_child = GetChild(current, *level, kLeft)) {
      (*path)[*level] = GetChild(current, *level, kRight);
      current = left_child;
      ++*level;
    } else if (const FocusedTree* right_child =
                   GetChild(current, *level, kRight)) {
      (*path)[*level] = GetChild(current, *level, kLeft);
      current = right_child;
      ++*level;
    } else {
      UNREACHABLE();
    }
  }
  return current;
}
References v8::internal::length, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::begin(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator++().
Get()
template<class Key , class Value , class Hasher = base::hash<Key>>
const Value& v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Get (const Key & key) const [inline]
Definition at line 79 of file persistent-map.h.
                                         {
    HashValue key_hash = HashValue(Hasher()(key));
    const FocusedTree* tree = FindHash(key_hash);
    return GetFocusedValue(tree, key);
  }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FindHash(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::GetFocusedValue(), and v8::internal::key.
Referenced by v8::internal::compiler::VariableTracker::State::Get(), v8::internal::compiler::WasmLoadElimination::HalfState::IntersectWith(), v8::internal::compiler::CsaLoadElimination::HalfState::IntersectWith(), v8::internal::compiler::WasmLoadElimination::HalfState::KillField(), v8::internal::compiler::CsaLoadElimination::HalfState::KillOffset(), v8::internal::compiler::CsaLoadElimination::HalfState::Lookup(), v8::internal::compiler::WasmLoadElimination::HalfState::LookupField(), v8::internal::compiler::CsaLoadElimination::HalfState::Update(), and v8::internal::compiler::WasmLoadElimination::HalfState::Update().
GetChild()
template<class Key , class Value , class Hasher >
const PersistentMap< Key, Value, Hasher >::FocusedTree * v8::internal::compiler::PersistentMap< Key, Value, Hasher >::GetChild (const FocusedTree * tree, int level, Bit bit) [static], [private]
Definition at line 508 of file persistent-map.h.
                                                     {
  if (tree->key_hash[level] == bit) {
    return tree;
  } else if (level < tree->length) {
    return tree->path(level);
  } else {
    return nullptr;
  }
}
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::key_hash, v8::internal::length, and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::path().
GetFocusedValue()
template<class Key , class Value , class Hasher >
const Value & v8::internal::compiler::PersistentMap< Key, Value, Hasher >::GetFocusedValue (const FocusedTree * tree, const Key & key) const [private]
Definition at line 486 of file persistent-map.h.
                                                   {
  if (!tree) {
    return def_value_;
  }
  if (tree->more) {
    auto it = tree->more->find(key);
    if (it == tree->more->end())
      return def_value_;
    else
      return it->second;
  } else {
    if (key == tree->key_value.key()) {
      return tree->key_value.value();
    } else {
      return def_value_;
    }
  }
}
References v8::internal::key, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::KeyValue::key(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::key_value, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::more, and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::KeyValue::value().
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Get().
last_depth()
template<class Key , class Value , class Hasher = base::hash<Key>>
size_t v8::internal::compiler::PersistentMap< Key, Value, Hasher >::last_depth () const [inline]
Definition at line 71 of file persistent-map.h.
                            {
    if (tree_) {
      return tree_->length;
    } else {
      return 0;
    }
  }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::length, and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::tree_.
Modify()
template<class Key , class Value , class Hasher >
template<class F >
void v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Modify (Key key, F f)
Definition at line 407 of file persistent-map.h.
                                                           {
  static_assert(std::is_void_v<decltype(f(std::declval<Value*>()))>);
  HashValue key_hash = HashValue(Hasher()(key));
  std::array<const FocusedTree*, kHashBits> path;
  int length = 0;
  const FocusedTree* old = FindHash(key_hash, &path, &length);
  ZoneMap<Key, Value>* more = nullptr;
  const Value& old_value = GetFocusedValue(old, key);
  Value new_value = old_value;
  f(&new_value);
  if (!may_be_unequal<Value>()(old_value, new_value)) return;
  if (old && !(old->more == nullptr && old->key_value.key() == key)) {
    more = zone_->New<ZoneMap<Key, Value>>(zone_);
    if (old->more) {
      *more = *old->more;
    } else {
      more->erase(old->key_value.key());
      more->emplace(old->key_value.key(), old->key_value.value());
    }
    more->erase(key);
    more->emplace(key, new_value);
  }
  size_t size = sizeof(FocusedTree) +
                std::max(0, length - 1) * sizeof(const FocusedTree*);
  FocusedTree* tree = new (zone_->Allocate<FocusedTree>(size))
      FocusedTree{KeyValue(std::move(key), std::move(new_value)),
                  static_cast<int8_t>(length),
                  key_hash,
                  more,
                  {}};
  for (int i = 0; i < length; ++i) {
    tree->path(i) = path[i];
  }
  *this = PersistentMap(tree, zone_, def_value_);
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::key, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::KeyValue::key(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::key_value, v8::internal::length, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::more, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::FocusedTree::path(), size(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::KeyValue::value().
operator!=()
template<class Key , class Value , class Hasher = base::hash<Key>>
bool v8::internal::compiler::PersistentMap< Key, Value, Hasher >::operator!= (const PersistentMap< Key, Value, Hasher > & other) const [inline]
Definition at line 101 of file persistent-map.h.
                                                    {
    return !(*this == other);
  }
operator==()
template<class Key , class Value , class Hasher = base::hash<Key>>
bool v8::internal::compiler::PersistentMap< Key, Value, Hasher >::operator== (const PersistentMap< Key, Value, Hasher > & other) const [inline]
Definition at line 92 of file persistent-map.h.
                                                    {
    if (tree_ == other.tree_) return true;
    if (def_value_ != other.def_value_) return false;
    for (std::tuple<Key, Value, Value> triple : Zip(other)) {
      if (std::get<1>(triple) != std::get<2>(triple)) return false;
    }
    return true;
  }
References v8::internal::compiler::PersistentMap< Key, Value, Hasher >::def_value_, v8::internal::compiler::PersistentMap< Key, Value, Hasher >::tree_, and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Zip().
Set()
template<class Key , class Value , class Hasher >
void v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Set (Key key, Value value)
Definition at line 401 of file persistent-map.h.
                                                                    {
  Modify(key, [&](Value* value) { *value = std::move(new_value); });
}
References v8::internal::key, and v8::internal::value.
Referenced by v8::internal::compiler::WasmLoadElimination::HalfState::IntersectWith(), v8::internal::compiler::CsaLoadElimination::HalfState::IntersectWith(), v8::internal::compiler::WasmLoadElimination::HalfState::KillField(), v8::internal::compiler::CsaLoadElimination::HalfState::KillField(), v8::internal::compiler::CsaLoadElimination::HalfState::KillOffset(), v8::internal::compiler::VariableTracker::State::Set(), v8::internal::compiler::CsaLoadElimination::HalfState::Update(), and v8::internal::compiler::WasmLoadElimination::HalfState::Update().
Zip()
template<class Key , class Value , class Hasher = base::hash<Key>>
ZipIterable v8::internal::compiler::PersistentMap< Key, Value, Hasher >::Zip (const PersistentMap< Key, Value, Hasher > & other) const [inline]
Definition at line 129 of file persistent-map.h.
{ return {*this, other}; }
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::operator==().
Friends And Related Function Documentation
may_be_unequal< PersistentMap< Key, Value, Hasher > >
template<class Key , class Value , class Hasher = base::hash<Key>>
friend struct may_be_unequal< PersistentMap< Key, Value, Hasher > > [friend]
Definition at line 50 of file persistent-map.h.
Member Data Documentation
def_value_
template<class Key , class Value , class Hasher = base::hash<Key>>
Value v8::internal::compiler::PersistentMap< Key, Value, Hasher >::def_value_ [private]
Definition at line 167 of file persistent-map.h.
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::begin(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::def_value(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::end(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::iterator::operator++(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::operator==().
kHashBits
template<class Key , class Value , class Hasher = base::hash<Key>>
constexpr size_t v8::internal::compiler::PersistentMap< Key, Value, Hasher >::kHashBits = 32 [static], [constexpr], [private]
Definition at line 50 of file persistent-map.h.
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::HashValue::operator[]().
tree_
template<class Key , class Value , class Hasher = base::hash<Key>>
const FocusedTree* v8::internal::compiler::PersistentMap< Key, Value, Hasher >::tree_ [private]
Definition at line 166 of file persistent-map.h.
Referenced by v8::internal::compiler::PersistentMap< Key, Value, Hasher >::begin(), v8::internal::compiler::PersistentMap< Key, Value, Hasher >::last_depth(), v8::internal::compiler::may_be_unequal< PersistentMap< Key, Value, Hasher > >::operator()(), and v8::internal::compiler::PersistentMap< Key, Value, Hasher >::operator==().
zone_
template<class Key , class Value , class Hasher = base::hash<Key>>
Zone* v8::internal::compiler::PersistentMap< Key, Value, Hasher >::zone_ [private]
Definition at line 168 of file persistent-map.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/persistent-map.h