v8::internal::compiler::FrameAccessState Class Reference
#include <frame.h>
Public Member Functions
FrameAccessState (const Frame *const frame)
const Frame * frame () const
V8_EXPORT_PRIVATE void MarkHasFrame (bool state)
int sp_delta () const
void ClearSPDelta ()
void IncreaseSPDelta (int amount)
bool access_frame_with_fp () const
bool has_frame () const
void SetFrameAccessToDefault ()
void SetFrameAccessToFP ()
void SetFrameAccessToSP ()
int GetSPToFPSlotCount () const
int GetSPToFPOffset () const
FrameOffset GetFrameOffset (int spill_slot) const
Private Attributes
const Frame *const frame_
bool access_frame_with_fp_
int sp_delta_
bool has_frame_
Detailed Description
Definition at line 239 of file frame.h.
Constructor & Destructor Documentation
FrameAccessState()
v8::internal::compiler::FrameAccessState::FrameAccessState (const Frame *const frame) [inline], [explicit]
Definition at line 241 of file frame.h.
      : frame_(frame),
        access_frame_with_fp_(false),
        sp_delta_(0),
        has_frame_(false) {}
Member Function Documentation
access_frame_with_fp()
bool v8::internal::compiler::FrameAccessState::access_frame_with_fp () const [inline]
Definition at line 254 of file frame.h.
{ return access_frame_with_fp_; }
References access_frame_with_fp_.
Referenced by GetFrameOffset().
ClearSPDelta()
void v8::internal::compiler::FrameAccessState::ClearSPDelta () [inline]
Definition at line 251 of file frame.h.
{ sp_delta_ = 0; }
References sp_delta_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction().
frame()
const Frame* v8::internal::compiler::FrameAccessState::frame () const [inline]
Definition at line 247 of file frame.h.
{ return frame_; }
References frame_.
Referenced by v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::AdjustStackPointerForTailCall(), GetSPToFPSlotCount(), v8::internal::compiler::CodeGenerator::Pop(), and v8::internal::compiler::CodeGenerator::Push().
GetFrameOffset()
FrameOffset v8::internal::compiler::FrameAccessState::GetFrameOffset (int spill_slot) const
Definition at line 57 of file frame.cc.
                                                                 {
  const int frame_offset = FrameSlotToFPOffset(spill_slot);
  if (access_frame_with_fp()) {
    return FrameOffset::FromFramePointer(frame_offset);
  } else {
    // No frame. Retrieve all parameters relative to stack pointer.
    int sp_offset = frame_offset + GetSPToFPOffset();
    DCHECK_GE(sp_offset, 0);
    return FrameOffset::FromStackPointer(sp_offset);
  }
}
References access_frame_with_fp(), DCHECK_GE, v8::internal::FrameSlotToFPOffset(), v8::internal::compiler::FrameOffset::FromFramePointer(), v8::internal::compiler::FrameOffset::FromStackPointer(), and GetSPToFPOffset().
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), v8::internal::compiler::ArmOperandConverter::SlotToMemOperand(), v8::internal::compiler::Loong64OperandConverter::SlotToMemOperand(), v8::internal::compiler::MipsOperandConverter::SlotToMemOperand(), v8::internal::compiler::PPCOperandConverter::SlotToMemOperand(), v8::internal::compiler::RiscvOperandConverter::SlotToMemOperand(), v8::internal::compiler::S390OperandConverter::SlotToMemOperand(), v8::internal::compiler::Arm64OperandConverter::SlotToMemOperand(), v8::internal::compiler::IA32OperandConverter::SlotToOperand(), and v8::internal::compiler::X64OperandConverter::SlotToOperand().
GetSPToFPOffset()
int v8::internal::compiler::FrameAccessState::GetSPToFPOffset () const [inline]
Definition at line 270 of file frame.h.
                              {
    return GetSPToFPSlotCount() * kSystemPointerSize;
  }
References GetSPToFPSlotCount(), and v8::internal::kSystemPointerSize.
Referenced by GetFrameOffset(), and v8::internal::compiler::Arm64OperandConverter::SlotToMemOperand().
GetSPToFPSlotCount()
int v8::internal::compiler::FrameAccessState::GetSPToFPSlotCount () const [inline]
Definition at line 264 of file frame.h.
                                 {
    int frame_slot_count =
        (has_frame() ? frame()->GetTotalFrameSlotCount() : kElidedFrameSlots) -
        StandardFrameConstants::kFixedSlotCountAboveFp;
    return frame_slot_count + sp_delta();
  }
References frame(), v8::internal::compiler::Frame::GetTotalFrameSlotCount(), has_frame(), v8::internal::kElidedFrameSlots, v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp, and sp_delta().
Referenced by v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-arm64.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-ia32.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-riscv.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::AdjustStackPointerForTailCall(), and GetSPToFPOffset().
has_frame()
bool v8::internal::compiler::FrameAccessState::has_frame () const [inline]
Definition at line 258 of file frame.h.
{ return has_frame_; }
References has_frame_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleReturn(), GetSPToFPSlotCount(), and SetFrameAccessToDefault().
IncreaseSPDelta()
void v8::internal::compiler::FrameAccessState::IncreaseSPDelta (int amount) [inline]
Definition at line 252 of file frame.h.
{ sp_delta_ += amount; }
References sp_delta_.
Referenced by v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-arm64.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-ia32.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-loong64.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-mips64.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-riscv.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::AdjustStackPointerForTailCall(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::anonymous_namespace{code-generator-arm.cc}::FlushPendingPushRegisters(), v8::internal::compiler::anonymous_namespace{code-generator-ppc.cc}::FlushPendingPushRegisters(), v8::internal::compiler::anonymous_namespace{code-generator-s390.cc}::FlushPendingPushRegisters(), v8::internal::compiler::CodeGenerator::Pop(), v8::internal::compiler::CodeGenerator::PopTempStackSlots(), and v8::internal::compiler::CodeGenerator::Push().
MarkHasFrame()
void v8::internal::compiler::FrameAccessState::MarkHasFrame (bool state)
Definition at line 44 of file frame.cc.
                                              {
  has_frame_ = state;
  SetFrameAccessToDefault();
}
References has_frame_, and SetFrameAccessToDefault().
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode().
SetFrameAccessToDefault()
void v8::internal::compiler::FrameAccessState::SetFrameAccessToDefault ()
Definition at line 49 of file frame.cc.
                                               {
  if (has_frame()) {
    SetFrameAccessToFP();
  } else {
    SetFrameAccessToSP();
  }
}
References has_frame(), SetFrameAccessToFP(), and SetFrameAccessToSP().
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), and MarkHasFrame().
SetFrameAccessToFP()
void v8::internal::compiler::FrameAccessState::SetFrameAccessToFP () [inline]
Definition at line 261 of file frame.h.
{ access_frame_with_fp_ = true; }
References access_frame_with_fp_.
Referenced by v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), and SetFrameAccessToDefault().
SetFrameAccessToSP()
void v8::internal::compiler::FrameAccessState::SetFrameAccessToSP () [inline]
Definition at line 262 of file frame.h.
{ access_frame_with_fp_ = false; }
References access_frame_with_fp_.
Referenced by v8::internal::compiler::CodeGenerator::AssemblePrepareTailCall(), and SetFrameAccessToDefault().
sp_delta()
int v8::internal::compiler::FrameAccessState::sp_delta () const [inline]
Definition at line 250 of file frame.h.
{ return sp_delta_; }
References sp_delta_.
Referenced by GetSPToFPSlotCount(), v8::internal::compiler::CodeGenerator::Pop(), and v8::internal::compiler::CodeGenerator::Push().
Member Data Documentation
access_frame_with_fp_
bool v8::internal::compiler::FrameAccessState::access_frame_with_fp_ [private]
Definition at line 282 of file frame.h.
Referenced by access_frame_with_fp(), SetFrameAccessToFP(), and SetFrameAccessToSP().
frame_
const Frame* const v8::internal::compiler::FrameAccessState::frame_ [private]
Definition at line 281 of file frame.h.
Referenced by frame().
has_frame_
bool v8::internal::compiler::FrameAccessState::has_frame_ [private]
Definition at line 284 of file frame.h.
Referenced by has_frame(), and MarkHasFrame().
sp_delta_
int v8::internal::compiler::FrameAccessState::sp_delta_ [private]
Definition at line 283 of file frame.h.
Referenced by ClearSPDelta(), IncreaseSPDelta(), and sp_delta().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/frame.h
/mnt/V8SourceCode/src/compiler/frame.cc