cppgc::internal::GCInvoker::GCInvokerImpl::GCTask Class Reference
Public Types
using Handle = SingleThreadedHandle
Public Member Functions
GCTask (GarbageCollector *collector, GCConfig config)
Static Public Member Functions
static Handle Post (GarbageCollector *collector, cppgc::TaskRunner *runner, GCConfig config)
Private Member Functions
void Run () final
Handle GetHandle ()
Private Attributes
GarbageCollector * collector_
GCConfig config_
Handle handle_
size_t saved_epoch_
Detailed Description
Definition at line 42 of file gc-invoker.cc.
Member Typedef Documentation
Handle
using cppgc::internal::GCInvoker::GCInvokerImpl::GCTask::Handle = SingleThreadedHandle
Definition at line 44 of file gc-invoker.cc.
Constructor & Destructor Documentation
GCTask()
cppgc::internal::GCInvoker::GCInvokerImpl::GCTask::GCTask (GarbageCollector * collector, GCConfig config) [inline], [explicit]
Definition at line 55 of file gc-invoker.cc.
        : collector_(collector),
          config_(config),
          handle_(Handle::NonEmptyTag{}),
          saved_epoch_(collector->epoch()) {}
Member Function Documentation
GetHandle()
Handle cppgc::internal::GCInvoker::GCInvokerImpl::GCTask::GetHandle () [inline], [private]
Definition at line 71 of file gc-invoker.cc.
{ return handle_; }
References handle_.
Post()
static Handle cppgc::internal::GCInvoker::GCInvokerImpl::GCTask::Post (GarbageCollector * collector, cppgc::TaskRunner * runner, GCConfig config) [inline], [static]
Definition at line 46 of file gc-invoker.cc.
                                        {
      auto task =
          std::make_unique<GCInvoker::GCInvokerImpl::GCTask>(collector, config);
      auto handle = task->GetHandle();
      runner->PostNonNestableTask(std::move(task));
      return handle;
    }
References v8::internal::handle(), and v8::TaskRunner::PostNonNestableTask().
Run()
void cppgc::internal::GCInvoker::GCInvokerImpl::GCTask::Run () [inline], [final], [private], [virtual]
Implements v8::Task.
Definition at line 62 of file gc-invoker.cc.
                     {
      if (handle_.IsCanceled() || (collector_->epoch() != saved_epoch_)) return;
      collector_->set_override_stack_state(EmbedderStackState::kNoHeapPointers);
      collector_->CollectGarbage(config_);
      collector_->clear_overridden_stack_state();
      handle_.Cancel();
    }
References cppgc::internal::SingleThreadedHandle::Cancel(), cppgc::internal::GarbageCollector::clear_overridden_stack_state(), cppgc::internal::GarbageCollector::CollectGarbage(), collector_, config_, cppgc::internal::GarbageCollector::epoch(), handle_, cppgc::internal::SingleThreadedHandle::IsCanceled(), cppgc::kNoHeapPointers, saved_epoch_, and cppgc::internal::GarbageCollector::set_override_stack_state().
Member Data Documentation
collector_
GarbageCollector* cppgc::internal::GCInvoker::GCInvokerImpl::GCTask::collector_ [private]
Definition at line 73 of file gc-invoker.cc.
Referenced by Run().
config_
GCConfig cppgc::internal::GCInvoker::GCInvokerImpl::GCTask::config_ [private]
Definition at line 74 of file gc-invoker.cc.
Referenced by Run().
handle_
Handle cppgc::internal::GCInvoker::GCInvokerImpl::GCTask::handle_ [private]
Definition at line 75 of file gc-invoker.cc.
Referenced by GetHandle(), and Run().
saved_epoch_
size_t cppgc::internal::GCInvoker::GCInvokerImpl::GCTask::saved_epoch_ [private]
Definition at line 76 of file gc-invoker.cc.
Referenced by Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/gc-invoker.cc