v8::internal::CollectionsBuiltinsAssembler Class Reference
#include <builtins-collections-gen.h>
Public Member Functions
CollectionsBuiltinsAssembler (compiler::CodeAssemblerState *state)
void BranchIfIterableWithOriginalKeyOrValueMapIterator (TNode< Object > iterable, TNode< Context > context, Label *if_true, Label *if_false)
void BranchIfIterableWithOriginalValueSetIterator (TNode< Object > iterable, TNode< Context > context, Label *if_true, Label *if_false)
TNode< OrderedHashSet > AddToSetTable (TNode< Object > context, TNode< OrderedHashSet > table, TNode< JSAny > key, TNode< String > method_name)
template<typename CollectionType >
TorqueStructKeyIndexPair NextKeyIndexPairUnmodifiedTable (const TNode< CollectionType > table, const TNode< Int32T > number_of_buckets, const TNode< Int32T > used_capacity, const TNode< IntPtrT > index, Label *if_end)
template<typename CollectionType >
TorqueStructKeyIndexPair NextKeyIndexPair (const TNode< CollectionType > table, const TNode< IntPtrT > index, Label *if_end)
TorqueStructKeyValueIndexTuple NextKeyValueIndexTupleUnmodifiedTable (const TNode< OrderedHashMap > table, const TNode< Int32T > number_of_buckets, const TNode< Int32T > used_capacity, const TNode< IntPtrT > index, Label *if_end)
TorqueStructKeyValueIndexTuple NextKeyValueIndexTuple (const TNode< OrderedHashMap > table, const TNode< IntPtrT > index, Label *if_end)
TNode< BoolT > TableHasKey (const TNode< Object > context, TNode< OrderedHashSet > table, TNode< Object > key)
TNode< BoolT > TableHasKey (const TNode< Object > context, TNode< OrderedHashMap > table, TNode< Object > key)
const TNode< OrderedHashMap > AddValueToKeyedGroup (const TNode< OrderedHashMap > groups, const TNode< Object > key, const TNode< Object > value, const TNode< String > methodName)
const TNode< JSAny > NormalizeNumberKey (const TNode< JSAny > key)
void UnsafeStoreValueInOrderedHashMapEntry (const TNode< OrderedHashMap > table, const TNode< Object > value, const TNode< IntPtrT > entry)
TNode< Smi > DeleteFromSetTable (const TNode< Object > context, TNode< OrderedHashSet > table, TNode< Object > key, Label *not_found)
TorqueStructOrderedHashSetIndexPair TransitionOrderedHashSetNoUpdate (const TNode< OrderedHashSet > table, const TNode< IntPtrT > index)
Protected Types
template<typename TableType >
using UpdateInTransition = std::function< void(const TNode< TableType > table, const TNode< IntPtrT > index)>
template<typename CollectionType >
using GrowCollection = std::function< const TNode< CollectionType >()>
template<typename CollectionType >
using StoreAtEntry = std::function< void(const TNode< CollectionType > table, const TNode< IntPtrT > entry_start)>
Protected Member Functions
template<typename IteratorType >
TNode< HeapObject > AllocateJSCollectionIterator (const TNode< Context > context, int map_index, const TNode< HeapObject > collection)
TNode< HeapObject > AllocateTable (Variant variant, TNode< IntPtrT > at_least_space_for) override
TNode< Uint32T > GetHash (const TNode< HeapObject > key)
TNode< Uint32T > CallGetHashRaw (const TNode< HeapObject > key)
TNode< Smi > CallGetOrCreateHashRaw (const TNode< HeapObject > key)
template<typename TableType >
std::pair< TNode< TableType >, TNode< IntPtrT > > Transition (const TNode< TableType > table, const TNode< IntPtrT > index, UpdateInTransition< TableType > const &update_in_transition)
template<typename IteratorType , typename TableType >
std::pair< TNode< TableType >, TNode< IntPtrT > > TransitionAndUpdate (const TNode< IteratorType > iterator)
template<typename TableType >
std::tuple< TNode< JSAny >, TNode< IntPtrT >, TNode< IntPtrT > > NextSkipHashTableHoles (TNode< TableType > table, TNode< IntPtrT > index, Label *if_end)
template<typename TableType >
std::tuple< TNode< JSAny >, TNode< IntPtrT >, TNode< IntPtrT > > NextSkipHashTableHoles (TNode< TableType > table, TNode< Int32T > number_of_buckets, TNode< Int32T > used_capacity, TNode< IntPtrT > index, Label *if_end)
TNode< OrderedHashSet > SetOrSetIteratorToSet (TNode< Object > iterator)
void AddConstructorEntriesFromSet (TNode< JSSet > collection, TNode< OrderedHashSet > table)
void GetEntriesIfFastCollectionOrIterable (Variant variant, TNode< Object > initial_entries, TNode< Context > context, TVariable< HeapObject > *var_entries_table, TVariable< IntPtrT > *var_number_of_elements, Label *if_not_fast_collection) override
void AddConstructorEntriesFromFastCollection (Variant variant, TNode< HeapObject > collection, TNode< HeapObject > source_table) override
template<typename CollectionType >
void FindOrderedHashTableEntryForSmiKey (TNode< CollectionType > table, TNode< Smi > key_tagged, TVariable< IntPtrT > *result, Label *entry_found, Label *not_found)
void SameValueZeroSmi (TNode< Smi > key_smi, TNode< Object > candidate_key, Label *if_same, Label *if_not_same)
void SameValueZeroHeapNumber (TNode< Float64T > key_float, TNode< Object > candidate_key, Label *if_same, Label *if_not_same)
template<typename CollectionType >
void FindOrderedHashTableEntryForHeapNumberKey (TNode< CollectionType > table, TNode< HeapNumber > key_heap_number, TVariable< IntPtrT > *result, Label *entry_found, Label *not_found)
void SameValueZeroBigInt (TNode< BigInt > key, TNode< Object > candidate_key, Label *if_same, Label *if_not_same)
template<typename CollectionType >
void FindOrderedHashTableEntryForBigIntKey (TNode< CollectionType > table, TNode< BigInt > key_big_int, TVariable< IntPtrT > *result, Label *entry_found, Label *not_found)
template<typename CollectionType >
void FindOrderedHashTableEntryForStringKey (TNode< CollectionType > table, TNode< String > key_tagged, TVariable< IntPtrT > *result, Label *entry_found, Label *not_found)
TNode< Uint32T > ComputeStringHash (TNode< String > string_key)
void SameValueZeroString (TNode< String > key_string, TNode< Object > candidate_key, Label *if_same, Label *if_not_same)
template<typename CollectionType >
void FindOrderedHashTableEntryForOtherKey (TNode< CollectionType > table, TNode< HeapObject > key_heap_object, TVariable< IntPtrT > *result, Label *entry_found, Label *not_found)
template<typename CollectionType >
TNode< CollectionType > AddToOrderedHashTable (const TNode< CollectionType > table, const TNode< Object > key, const GrowCollection< CollectionType > &grow, const StoreAtEntry< CollectionType > &store_at_new_entry, const StoreAtEntry< CollectionType > &store_at_existing_entry)
template<typename CollectionType >
void TryLookupOrderedHashTableIndex (const TNode< CollectionType > table, const TNode< Object > key, TVariable< IntPtrT > *result, Label *if_entry_found, Label *if_not_found)
template<typename CollectionType >
void AddNewToOrderedHashTable (const TNode< CollectionType > table, const TNode< Object > normalised_key, const TNode< IntPtrT > number_of_buckets, const TNode< IntPtrT > occupancy, const StoreAtEntry< CollectionType > &store_at_new_entry)
void AddNewToOrderedHashSet (const TNode< OrderedHashSet > table, const TNode< JSAny > key, const TNode< IntPtrT > number_of_buckets, const TNode< IntPtrT > occupancy)
template<typename CollectionType >
void StoreOrderedHashTableNewEntry (const TNode< CollectionType > table, const TNode< IntPtrT > hash, const TNode< IntPtrT > number_of_buckets, const TNode< IntPtrT > occupancy, const StoreAtEntry< CollectionType > &store_at_new_entry)
void StoreValueInOrderedHashMapEntry (const TNode< OrderedHashMap > table, const TNode< Object > value, const TNode< IntPtrT > entry, CheckBounds check_bounds=CheckBounds::kAlways)
void StoreKeyValueInOrderedHashMapEntry (const TNode< OrderedHashMap > table, const TNode< Object > key, const TNode< Object > value, const TNode< IntPtrT > entry, CheckBounds check_bounds=CheckBounds::kAlways)
void StoreKeyInOrderedHashSetEntry (const TNode< OrderedHashSet > table, const TNode< Object > key, const TNode< IntPtrT > entry, CheckBounds check_bounds=CheckBounds::kAlways)
void UnsafeStoreKeyValueInOrderedHashMapEntry (const TNode< OrderedHashMap > table, const TNode< Object > key, const TNode< Object > value, const TNode< IntPtrT > entry)
void UnsafeStoreKeyInOrderedHashSetEntry (const TNode< OrderedHashSet > table, const TNode< Object > key, const TNode< IntPtrT > entry)
TNode< UnionOf< JSAny, ArrayList > > LoadValueFromOrderedHashMapEntry (const TNode< OrderedHashMap > table, const TNode< IntPtrT > entry, CheckBounds check_bounds=CheckBounds::kAlways)
TNode< UnionOf< JSAny, ArrayList > > UnsafeLoadValueFromOrderedHashMapEntry (const TNode< OrderedHashMap > table, const TNode< IntPtrT > entry)
template<typename CollectionType >
TNode< JSAny > LoadKeyFromOrderedHashTableEntry (const TNode< CollectionType > table, const TNode< IntPtrT > entry, CheckBounds check_bounds=CheckBounds::kAlways)
template<typename CollectionType >
TNode< JSAny > UnsafeLoadKeyFromOrderedHashTableEntry (const TNode< CollectionType > table, const TNode< IntPtrT > entry)
TNode< JSArray > MapIteratorToList (TNode< Context > context, TNode< JSMapIterator > iterator)
TNode< JSArray > SetOrSetIteratorToList (TNode< Context > context, TNode< HeapObject > iterable)
void BranchIfMapIteratorProtectorValid (Label *if_true, Label *if_false)
void BranchIfSetIteratorProtectorValid (Label *if_true, Label *if_false)
template<typename CollectionType >
void FindOrderedHashTableEntry (const TNode< CollectionType > table, const TNode< Uint32T > hash, const std::function< void(TNode< Object >, Label *, Label *)> &key_compare, TVariable< IntPtrT > *entry_start_position, Label *entry_found, Label *not_found)
TNode< Word32T > ComputeUnseededHash (TNode< IntPtrT > key)
Additional Inherited Members
Detailed Description
Definition at line 148 of file builtins-collections-gen.h.
Member Typedef Documentation
GrowCollection
template<typename CollectionType >
using v8::internal::CollectionsBuiltinsAssembler::GrowCollection = std::function<const TNode<CollectionType>()> [protected]
Definition at line 361 of file builtins-collections-gen.h.
StoreAtEntry
template<typename CollectionType >
using v8::internal::CollectionsBuiltinsAssembler::StoreAtEntry = std::function<void(const TNode<CollectionType> table, const TNode<IntPtrT> entry_start)> [protected]
Definition at line 363 of file builtins-collections-gen.h.
UpdateInTransition
template<typename TableType >
using v8::internal::CollectionsBuiltinsAssembler::UpdateInTransition = std::function<void(const TNode<TableType> table, const TNode<IntPtrT> index)> [protected]
Definition at line 241 of file builtins-collections-gen.h.
Constructor & Destructor Documentation
CollectionsBuiltinsAssembler()
v8::internal::CollectionsBuiltinsAssembler::CollectionsBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 150 of file builtins-collections-gen.h.
      : BaseCollectionsAssembler(state) {}
Member Function Documentation
AddConstructorEntriesFromFastCollection()
void v8::internal::CollectionsBuiltinsAssembler::AddConstructorEntriesFromFastCollection (Variant variant, TNode< HeapObject > collection, TNode< HeapObject > source_table) [override], [protected], [virtual]
Implements v8::internal::BaseCollectionsAssembler.
Definition at line 714 of file builtins-collections-gen.cc.
                                    {
  if (variant == kSet) {
    AddConstructorEntriesFromSet(CAST(collection), CAST(source_table));
    return;
  }
}
References AddConstructorEntriesFromSet(), CAST, and v8::internal::BaseCollectionsAssembler::kSet.
AddConstructorEntriesFromSet()
void v8::internal::CollectionsBuiltinsAssembler::AddConstructorEntriesFromSet (TNode< JSSet > collection, TNode< OrderedHashSet > table) [protected]
Definition at line 658 of file builtins-collections-gen.cc.
                                                          {
  TNode<OrderedHashSet> entry_table = LoadObjectField<OrderedHashSet>(
      collection, GetTableOffset(Variant::kSet));
  TNode<IntPtrT> number_of_buckets =
      PositiveSmiUntag(CAST(UnsafeLoadFixedArrayElement(
          table, OrderedHashSet::NumberOfBucketsIndex())));
  TNode<IntPtrT> number_of_elements = LoadAndUntagPositiveSmiObjectField(
      table, OrderedHashSet::NumberOfElementsOffset());
  TNode<IntPtrT> number_of_deleted_elements = PositiveSmiUntag(CAST(
      LoadObjectField(table, OrderedHashSet::NumberOfDeletedElementsOffset())));
  TNode<IntPtrT> used_capacity =
      IntPtrAdd(number_of_elements, number_of_deleted_elements);
  TNode<IntPtrT> loop_bound = IntPtrAdd(
      IntPtrMul(used_capacity, IntPtrConstant(OrderedHashSet::kEntrySize)),
      number_of_buckets);
  TNode<IntPtrT> number_of_buckets_entry_table =
      PositiveSmiUntag(CAST(UnsafeLoadFixedArrayElement(
          entry_table, OrderedHashSet::NumberOfBucketsIndex())));
  TVARIABLE(JSAny, entry_key);
  TVARIABLE(IntPtrT, var_entry_table_occupancy, IntPtrConstant(0));
  VariableList loop_vars({&var_entry_table_occupancy}, zone());
  Label exit(this);
  auto set_entry = [&](TNode<IntPtrT> index) {
    entry_key = UnsafeLoadKeyFromOrderedHashTableEntry(table, index);
    Label if_key_is_not_hole(this), continue_loop(this);
    Branch(IsHashTableHole(entry_key.value()), &continue_loop,
           &if_key_is_not_hole);
    BIND(&if_key_is_not_hole);
    {
      AddNewToOrderedHashSet(entry_table, entry_key.value(),
                             number_of_buckets_entry_table,
                             var_entry_table_occupancy.value());
      Increment(&var_entry_table_occupancy, 1);
      Goto(&continue_loop);
    }
    BIND(&continue_loop);
    return;
  };
  // Instead of using the slower iteration protocol to iterate over the
  // elements, a fast loop is used. This assumes that adding an element
  // to the collection does not call user code that could mutate the elements
  // or collection. The iteration is based on the layout of the ordered hash
  // table.
  BuildFastLoop<IntPtrT>(loop_vars, number_of_buckets, loop_bound, set_entry,
                         OrderedHashSet::kEntrySize, LoopUnrollingMode::kNo,
                         IndexAdvanceMode::kPost);
  Goto(&exit);
  BIND(&exit);
}
References AddNewToOrderedHashSet(), v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::BaseCollectionsAssembler::GetTableOffset(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::CodeStubAssembler::Increment(), v8::internal::index, v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrMul(), v8::internal::OrderedHashTable< OrderedHashSet, 1 >::kEntrySize, v8::internal::CodeStubAssembler::kNo, v8::internal::CodeStubAssembler::kPost, v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::OrderedHashTable< OrderedHashSet, 1 >::NumberOfBucketsIndex(), v8::internal::OrderedHashTable< OrderedHashSet, 1 >::NumberOfDeletedElementsOffset(), v8::internal::OrderedHashTable< OrderedHashSet, 1 >::NumberOfElementsOffset(), v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::internal::CodeStubAssembler::UnsafeLoadFixedArrayElement(), UnsafeLoadKeyFromOrderedHashTableEntry(), and v8::internal::compiler::CodeAssembler::zone().
Referenced by AddConstructorEntriesFromFastCollection().
AddNewToOrderedHashSet()
void v8::internal::CollectionsBuiltinsAssembler::AddNewToOrderedHashSet (const TNode< OrderedHashSet > table, const TNode< JSAny > key, const TNode< IntPtrT > number_of_buckets, const TNode< IntPtrT > occupancy) [inline], [protected]
Definition at line 386 of file builtins-collections-gen.h.
                                                              {
    TNode<JSAny> normalised_key = NormalizeNumberKey(key);
    StoreAtEntry<OrderedHashSet> store_at_new_entry =
        [this, normalised_key](const TNode<OrderedHashSet> table,
                               const TNode<IntPtrT> entry_start) {
          UnsafeStoreKeyInOrderedHashSetEntry(table, normalised_key,
                                              entry_start);
        };
    AddNewToOrderedHashTable<OrderedHashSet>(table, normalised_key,
                                             number_of_buckets, occupancy,
                                             store_at_new_entry);
  }
References v8::internal::key, NormalizeNumberKey(), and UnsafeStoreKeyInOrderedHashSetEntry().
Referenced by AddConstructorEntriesFromSet().
AddNewToOrderedHashTable()
template<typename CollectionType >
void v8::internal::CollectionsBuiltinsAssembler::AddNewToOrderedHashTable (const TNode< CollectionType > table, const TNode< Object > normalised_key, const TNode< IntPtrT > number_of_buckets, const TNode< IntPtrT > occupancy, const StoreAtEntry< CollectionType > & store_at_new_entry) [protected]
Definition at line 1806 of file builtins-collections-gen.cc.
                                                            {
  Label if_key_smi(this), if_key_string(this), if_key_heap_number(this),
      if_key_bigint(this), if_key_other(this), call_store(this);
  TVARIABLE(IntPtrT, hash, IntPtrConstant(0));
  GotoIf(TaggedIsSmi(normalised_key), &if_key_smi);
  TNode<Map> key_map = LoadMap(CAST(normalised_key));
  TNode<Uint16T> key_instance_type = LoadMapInstanceType(key_map);
  GotoIf(IsStringInstanceType(key_instance_type), &if_key_string);
  GotoIf(IsHeapNumberMap(key_map), &if_key_heap_number);
  GotoIf(IsBigIntInstanceType(key_instance_type), &if_key_bigint);
  Goto(&if_key_other);
  BIND(&if_key_other);
  {
    hash = Signed(ChangeUint32ToWord(GetHash(CAST(normalised_key))));
    Goto(&call_store);
  }
  BIND(&if_key_smi);
  {
    hash = ChangeInt32ToIntPtr(
        ComputeUnseededHash(SmiUntag(CAST(normalised_key))));
    Goto(&call_store);
  }
  BIND(&if_key_string);
  {
    hash = Signed(ChangeUint32ToWord(ComputeStringHash(CAST(normalised_key))));
    Goto(&call_store);
  }
  BIND(&if_key_heap_number);
  {
    hash = Signed(ChangeUint32ToWord(GetHash(CAST(normalised_key))));
    Goto(&call_store);
  }
  BIND(&if_key_bigint);
  {
    hash = Signed(ChangeUint32ToWord(GetHash(CAST(normalised_key))));
    Goto(&call_store);
  }
  BIND(&call_store);
  StoreOrderedHashTableNewEntry(table, hash.value(), number_of_buckets,
                                occupancy, store_at_new_entry);
}
References CAST, v8::internal::compiler::CodeAssembler::ChangeInt32ToIntPtr(), v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), ComputeStringHash(), ComputeUnseededHash(), GetHash(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::IsBigIntInstanceType(), v8::internal::CodeStubAssembler::IsStringInstanceType(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapInstanceType(), v8::internal::compiler::CodeAssembler::Signed(), v8::internal::CodeStubAssembler::SmiUntag(), StoreOrderedHashTableNewEntry(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
AddToOrderedHashTable()
template<typename CollectionType >
TNode< CollectionType > v8::internal::CollectionsBuiltinsAssembler::AddToOrderedHashTable (const TNode< CollectionType > table, const TNode< Object > key, const GrowCollection< CollectionType > & grow, const StoreAtEntry< CollectionType > & store_at_new_entry, const StoreAtEntry< CollectionType > & store_at_existing_entry) [protected]
Definition at line 1655 of file builtins-collections-gen.cc.
                                                                 {
  TVARIABLE(CollectionType, table_var, table);
  TVARIABLE(IntPtrT, entry_start_position_or_hash, IntPtrConstant(0));
  Label entry_found(this), not_found(this), done(this);
  TryLookupOrderedHashTableIndex<CollectionType>(
      table, key, &entry_start_position_or_hash, &entry_found, &not_found);
  BIND(&entry_found);
  {
    // If we found the entry, we just store the value there.
    store_at_existing_entry(table, entry_start_position_or_hash.value());
    Goto(&done);
  }
  Label no_hash(this), add_entry(this), store_new_entry(this);
  BIND(&not_found);
  {
    // If we have a hash code, we can start adding the new entry.
    GotoIf(IntPtrGreaterThan(entry_start_position_or_hash.value(),
                             IntPtrConstant(0)),
           &add_entry);
    // Otherwise, go to runtime to compute the hash code.
    entry_start_position_or_hash = SmiUntag(CallGetOrCreateHashRaw(CAST(key)));
    Goto(&add_entry);
  }
  BIND(&add_entry);
  TVARIABLE(IntPtrT, number_of_buckets);
  TVARIABLE(IntPtrT, occupancy);
  {
    // Check we have enough space for the entry.
    number_of_buckets = PositiveSmiUntag(CAST(UnsafeLoadFixedArrayElement(
        table, CollectionType::NumberOfBucketsIndex())));
    static_assert(CollectionType::kLoadFactor == 2);
    const TNode<WordT> capacity = WordShl(number_of_buckets.value(), 1);
    const TNode<IntPtrT> number_of_elements =
        LoadAndUntagPositiveSmiObjectField(
            table, CollectionType::NumberOfElementsOffset());
    const TNode<IntPtrT> number_of_deleted =
        PositiveSmiUntag(CAST(LoadObjectField(
            table, CollectionType::NumberOfDeletedElementsOffset())));
    occupancy = IntPtrAdd(number_of_elements, number_of_deleted);
    GotoIf(IntPtrLessThan(occupancy.value(), capacity), &store_new_entry);
    // We do not have enough space, grow the table and reload the relevant
    // fields.
    table_var = grow();
    number_of_buckets = PositiveSmiUntag(CAST(UnsafeLoadFixedArrayElement(
        table_var.value(), CollectionType::NumberOfBucketsIndex())));
    const TNode<IntPtrT> new_number_of_elements =
        LoadAndUntagPositiveSmiObjectField(
            table_var.value(), CollectionType::NumberOfElementsOffset());
    const TNode<IntPtrT> new_number_of_deleted = PositiveSmiUntag(
        CAST(LoadObjectField(table_var.value(),
                             CollectionType::NumberOfDeletedElementsOffset())));
    occupancy = IntPtrAdd(new_number_of_elements, new_number_of_deleted);
    Goto(&store_new_entry);
  }
  BIND(&store_new_entry);
  {
    StoreOrderedHashTableNewEntry(
        table_var.value(), entry_start_position_or_hash.value(),
        number_of_buckets.value(), occupancy.value(), store_at_new_entry);
    Goto(&done);
  }
  BIND(&done);
  return table_var.value();
}
References CallGetOrCreateHashRaw(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThan(), v8::internal::key, v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::internal::CodeStubAssembler::SmiUntag(), StoreOrderedHashTableNewEntry(), v8::internal::CodeStubAssembler::UnsafeLoadFixedArrayElement(), and v8::internal::compiler::CodeAssembler::WordShl().
Referenced by AddToSetTable(), and AddValueToKeyedGroup().
AddToSetTable()
TNode< OrderedHashSet > v8::internal::CollectionsBuiltinsAssembler::AddToSetTable (TNode< Object > context, TNode< OrderedHashSet > table, TNode< JSAny > key, TNode< String > method_name)
Definition at line 1965 of file builtins-collections-gen.cc.
                               {
  key = NormalizeNumberKey(key);
  GrowCollection<OrderedHashSet> grow = [this, context, table, method_name]() {
    TNode<OrderedHashSet> new_table = Cast(
        CallRuntime(Runtime::kOrderedHashSetGrow, context, table, method_name));
    // TODO(v8:13556): check if the table is updated and remove pointer to the
    // new table.
    return new_table;
  };
  StoreAtEntry<OrderedHashSet> store_at_new_entry =
      [this, key](const TNode<OrderedHashSet> table,
                  const TNode<IntPtrT> entry_start) {
        UnsafeStoreKeyInOrderedHashSetEntry(table, key, entry_start);
      };
  StoreAtEntry<OrderedHashSet> store_at_existing_entry =
      [](const TNode<OrderedHashSet>, const TNode<IntPtrT>) {
        // If the entry was found, there is nothing to do.
      };
  return AddToOrderedHashTable(table, key, grow, store_at_new_entry,
                               store_at_existing_entry);
}
References AddToOrderedHashTable(), v8::internal::compiler::CodeAssembler::CallRuntime(), v8::internal::compiler::CodeAssembler::Cast(), v8::internal::key, NormalizeNumberKey(), and UnsafeStoreKeyInOrderedHashSetEntry().
AddValueToKeyedGroup()
const TNode< OrderedHashMap > v8::internal::CollectionsBuiltinsAssembler::AddValueToKeyedGroup (const TNode< OrderedHashMap > groups, const TNode< Object > key, const TNode< Object > value, const TNode< String > methodName)
Definition at line 2518 of file builtins-collections-gen.cc.
                                                               {
  GrowCollection<OrderedHashMap> grow = [this, groups, methodName]() {
    TNode<OrderedHashMap> new_groups = CAST(CallRuntime(
        Runtime::kOrderedHashMapGrow, NoContextConstant(), groups, methodName));
    // The groups OrderedHashMap is not escaped to user script while grouping
    // items, so there can't be live iterators. So we don't need to keep the
    // pointer from the old table to the new one.
    Label did_grow(this), done(this);
    Branch(TaggedEqual(groups, new_groups), &done, &did_grow);
    BIND(&did_grow);
    {
      StoreObjectFieldNoWriteBarrier(groups, OrderedHashMap::NextTableOffset(),
                                     SmiConstant(0));
      Goto(&done);
    }
    BIND(&done);
    return new_groups;
  };
  StoreAtEntry<OrderedHashMap> store_at_new_entry =
      [this, key, value](const TNode<OrderedHashMap> table,
                         const TNode<IntPtrT> entry_start) {
        TNode<ArrayList> array = AllocateArrayList(SmiConstant(1));
        ArrayListSet(array, SmiConstant(0), value);
        ArrayListSetLength(array, SmiConstant(1));
        StoreKeyValueInOrderedHashMapEntry(table, key, array, entry_start);
      };
  StoreAtEntry<OrderedHashMap> store_at_existing_entry =
      [this, key, value](const TNode<OrderedHashMap> table,
                         const TNode<IntPtrT> entry_start) {
        TNode<ArrayList> array =
            CAST(LoadValueFromOrderedHashMapEntry(table, entry_start));
        TNode<ArrayList> new_array = ArrayListAdd(array, value);
        StoreKeyValueInOrderedHashMapEntry(table, key, new_array, entry_start);
      };
  return AddToOrderedHashTable(groups, key, grow, store_at_new_entry,
                               store_at_existing_entry);
}
References AddToOrderedHashTable(), v8::internal::CodeStubAssembler::AllocateArrayList(), v8::internal::CodeStubAssembler::ArrayListAdd(), v8::internal::CodeStubAssembler::ArrayListSet(), v8::internal::CodeStubAssembler::ArrayListSetLength(), v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::key, LoadValueFromOrderedHashMapEntry(), v8::internal::OrderedHashTable< OrderedHashMap, 2 >::NextTableOffset(), v8::internal::CodeStubAssembler::NoContextConstant(), v8::internal::compiler::CodeAssembler::SmiConstant(), StoreKeyValueInOrderedHashMapEntry(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), v8::internal::CodeStubAssembler::TaggedEqual(), and v8::internal::value.
AllocateJSCollectionIterator()
template<typename IteratorType >
TNode< HeapObject > v8::internal::CollectionsBuiltinsAssembler::AllocateJSCollectionIterator (const TNode< Context > context, int map_index, const TNode< HeapObject > collection) [protected]
Definition at line 724 of file builtins-collections-gen.cc.
                                        {
  const TNode<Object> table =
      LoadObjectField(collection, JSCollection::kTableOffset);
  const TNode<NativeContext> native_context = LoadNativeContext(context);
  const TNode<Map> iterator_map =
      CAST(LoadContextElementNoCell(native_context, map_index));
  const TNode<HeapObject> iterator =
      AllocateInNewSpace(IteratorType::kHeaderSize);
  StoreMapNoWriteBarrier(iterator, iterator_map);
  StoreObjectFieldRoot(iterator, IteratorType::kPropertiesOrHashOffset,
                       RootIndex::kEmptyFixedArray);
  StoreObjectFieldRoot(iterator, IteratorType::kElementsOffset,
                       RootIndex::kEmptyFixedArray);
  StoreObjectFieldNoWriteBarrier(iterator, IteratorType::kTableOffset, table);
  StoreObjectFieldNoWriteBarrier(iterator, IteratorType::kIndexOffset,
                                 SmiConstant(0));
  return iterator;
}
References v8::internal::CodeStubAssembler::AllocateInNewSpace(), CAST, v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::native_context, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::StoreMapNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), and v8::internal::CodeStubAssembler::StoreObjectFieldRoot().
AllocateTable()
TNode< HeapObject > v8::internal::CollectionsBuiltinsAssembler::AllocateTable (Variant variant, TNode< IntPtrT > at_least_space_for) [override], [protected], [virtual]
Implements v8::internal::BaseCollectionsAssembler.
Definition at line 745 of file builtins-collections-gen.cc.
                                                        {
  if (variant == kMap) {
    return AllocateOrderedHashMap();
  } else {
    DCHECK_EQ(variant, kSet);
    TNode<IntPtrT> capacity = HashTableComputeCapacity(at_least_space_for);
    return AllocateOrderedHashSet(capacity);
  }
}
References v8::internal::CodeStubAssembler::AllocateOrderedHashMap(), v8::internal::CodeStubAssembler::AllocateOrderedHashSet(), DCHECK_EQ, v8::internal::CodeStubAssembler::HashTableComputeCapacity(), v8::internal::BaseCollectionsAssembler::kMap, and v8::internal::BaseCollectionsAssembler::kSet.
BranchIfIterableWithOriginalKeyOrValueMapIterator()
void v8::internal::CollectionsBuiltinsAssembler::BranchIfIterableWithOriginalKeyOrValueMapIterator (TNode< Object > iterable, TNode< Context > context, Label * if_true, Label * if_false)
Definition at line 865 of file builtins-collections-gen.cc.
                                                                       {
  Label if_key_or_value_iterator(this), extra_checks(this);
  // Check if iterator is a keys or values JSMapIterator.
  GotoIf(TaggedIsSmi(iterator), if_false);
  TNode<Map> iter_map = LoadMap(CAST(iterator));
  const TNode<Uint16T> instance_type = LoadMapInstanceType(iter_map);
  GotoIf(InstanceTypeEqual(instance_type, JS_MAP_KEY_ITERATOR_TYPE),
         &if_key_or_value_iterator);
  Branch(InstanceTypeEqual(instance_type, JS_MAP_VALUE_ITERATOR_TYPE),
         &if_key_or_value_iterator, if_false);
  BIND(&if_key_or_value_iterator);
  // Check that the iterator is not partially consumed.
  const TNode<Object> index =
      LoadObjectField(CAST(iterator), JSMapIterator::kIndexOffset);
  GotoIfNot(TaggedEqual(index, SmiConstant(0)), if_false);
  BranchIfMapIteratorProtectorValid(&extra_checks, if_false);
  BIND(&extra_checks);
  // Check if the iterator object has the original %MapIteratorPrototype%.
  const TNode<NativeContext> native_context = LoadNativeContext(context);
  const TNode<Object> initial_map_iter_proto = LoadContextElementNoCell(
      native_context, Context::INITIAL_MAP_ITERATOR_PROTOTYPE_INDEX);
  const TNode<HeapObject> map_iter_proto = LoadMapPrototype(iter_map);
  GotoIfNot(TaggedEqual(map_iter_proto, initial_map_iter_proto), if_false);
  // Check if the original MapIterator prototype has the original
  // %IteratorPrototype%.
  const TNode<Object> initial_iter_proto = LoadContextElementNoCell(
      native_context, Context::INITIAL_ITERATOR_PROTOTYPE_INDEX);
  const TNode<HeapObject> iter_proto =
      LoadMapPrototype(LoadMap(map_iter_proto));
  Branch(TaggedEqual(iter_proto, initial_iter_proto), if_true, if_false);
}
References v8::internal::compiler::CodeAssembler::Branch(), BranchIfMapIteratorProtectorValid(), CAST, v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::index, v8::internal::CodeStubAssembler::InstanceTypeEqual(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapInstanceType(), v8::internal::CodeStubAssembler::LoadMapPrototype(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::native_context, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::TaggedEqual(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
Referenced by v8::internal::BranchIfIterableWithOriginalKeyOrValueMapIterator().
BranchIfIterableWithOriginalValueSetIterator()
void v8::internal::CollectionsBuiltinsAssembler::BranchIfIterableWithOriginalValueSetIterator (TNode< Object > iterable, TNode< Context > context, Label * if_true, Label * if_false)
Definition at line 924 of file builtins-collections-gen.cc.
                     {
  Label if_set(this), if_value_iterator(this), check_protector(this);
  TVARIABLE(BoolT, var_result);
  GotoIf(TaggedIsSmi(iterable), if_false);
  TNode<Map> iterable_map = LoadMap(CAST(iterable));
  const TNode<Uint16T> instance_type = LoadMapInstanceType(iterable_map);
  GotoIf(InstanceTypeEqual(instance_type, JS_SET_TYPE), &if_set);
  Branch(InstanceTypeEqual(instance_type, JS_SET_VALUE_ITERATOR_TYPE),
         &if_value_iterator, if_false);
  BIND(&if_set);
  // Check if the set object has the original Set prototype.
  const TNode<Object> initial_set_proto = LoadContextElementNoCell(
      LoadNativeContext(context), Context::INITIAL_SET_PROTOTYPE_INDEX);
  const TNode<HeapObject> set_proto = LoadMapPrototype(iterable_map);
  GotoIfNot(TaggedEqual(set_proto, initial_set_proto), if_false);
  Goto(&check_protector);
  BIND(&if_value_iterator);
  // Check that the iterator is not partially consumed.
  const TNode<Object> index =
      LoadObjectField(CAST(iterable), JSSetIterator::kIndexOffset);
  GotoIfNot(TaggedEqual(index, SmiConstant(0)), if_false);
  // Check if the iterator object has the original SetIterator prototype.
  const TNode<NativeContext> native_context = LoadNativeContext(context);
  const TNode<Object> initial_set_iter_proto = LoadContextElementNoCell(
      native_context, Context::INITIAL_SET_ITERATOR_PROTOTYPE_INDEX);
  const TNode<HeapObject> set_iter_proto = LoadMapPrototype(iterable_map);
  GotoIfNot(TaggedEqual(set_iter_proto, initial_set_iter_proto), if_false);
  // Check if the original SetIterator prototype has the original
  // %IteratorPrototype%.
  const TNode<Object> initial_iter_proto = LoadContextElementNoCell(
      native_context, Context::INITIAL_ITERATOR_PROTOTYPE_INDEX);
  const TNode<HeapObject> iter_proto =
      LoadMapPrototype(LoadMap(set_iter_proto));
  GotoIfNot(TaggedEqual(iter_proto, initial_iter_proto), if_false);
  Goto(&check_protector);
  BIND(&check_protector);
  BranchIfSetIteratorProtectorValid(if_true, if_false);
}
References v8::internal::compiler::CodeAssembler::Branch(), BranchIfSetIteratorProtectorValid(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::index, v8::internal::CodeStubAssembler::InstanceTypeEqual(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapInstanceType(), v8::internal::CodeStubAssembler::LoadMapPrototype(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::native_context, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::TaggedEqual(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
Referenced by v8::internal::BranchIfIterableWithOriginalValueSetIterator(), and GetEntriesIfFastCollectionOrIterable().
BranchIfMapIteratorProtectorValid()
void v8::internal::CollectionsBuiltinsAssembler::BranchIfMapIteratorProtectorValid (Label * if_true, Label * if_false) [protected]
Definition at line 855 of file builtins-collections-gen.cc.
                                     {
  TNode<PropertyCell> protector_cell = MapIteratorProtectorConstant();
  DCHECK(i::IsPropertyCell(isolate()->heap()->map_iterator_protector()));
  Branch(
      TaggedEqual(LoadObjectField(protector_cell, PropertyCell::kValueOffset),
                  SmiConstant(Protectors::kProtectorValid)),
      if_true, if_false);
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::DCHECK(), heap(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::Protectors::kProtectorValid, v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::compiler::CodeAssembler::SmiConstant(), and v8::internal::CodeStubAssembler::TaggedEqual().
Referenced by BranchIfIterableWithOriginalKeyOrValueMapIterator().
BranchIfSetIteratorProtectorValid()
void v8::internal::CollectionsBuiltinsAssembler::BranchIfSetIteratorProtectorValid (Label * if_true, Label * if_false) [protected]
Definition at line 914 of file builtins-collections-gen.cc.
                                     {
  const TNode<PropertyCell> protector_cell = SetIteratorProtectorConstant();
  DCHECK(i::IsPropertyCell(isolate()->heap()->set_iterator_protector()));
  Branch(
      TaggedEqual(LoadObjectField(protector_cell, PropertyCell::kValueOffset),
                  SmiConstant(Protectors::kProtectorValid)),
      if_true, if_false);
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::DCHECK(), heap(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::Protectors::kProtectorValid, v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::compiler::CodeAssembler::SmiConstant(), and v8::internal::CodeStubAssembler::TaggedEqual().
Referenced by BranchIfIterableWithOriginalValueSetIterator().
CallGetHashRaw()
TNode< Uint32T > v8::internal::CollectionsBuiltinsAssembler::CallGetHashRaw (const TNode< HeapObject > key) [protected]
Definition at line 793 of file builtins-collections-gen.cc.
                                 {
  const TNode<ExternalReference> function_addr =
      ExternalConstant(ExternalReference::orderedhashmap_gethash_raw());
  const TNode<ExternalReference> isolate_ptr =
      ExternalConstant(ExternalReference::isolate_address());
  MachineType type_ptr = MachineType::Pointer();
  MachineType type_tagged = MachineType::AnyTagged();
  TNode<Smi> result = CAST(CallCFunction(function_addr, type_tagged,
                                         std::make_pair(type_ptr, isolate_ptr),
                                         std::make_pair(type_tagged, key)));
  return PositiveSmiToUint32(result);
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), CAST, v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::ExternalReference::isolate_address(), v8::internal::key, v8::internal::MachineType::Pointer(), v8::internal::CodeStubAssembler::PositiveSmiToUint32(), and v8::base::internal::result.
Referenced by ComputeStringHash(), FindOrderedHashTableEntryForBigIntKey(), FindOrderedHashTableEntryForHeapNumberKey(), and GetHash().
CallGetOrCreateHashRaw()
TNode< Smi > v8::internal::CollectionsBuiltinsAssembler::CallGetOrCreateHashRaw (const TNode< HeapObject > key) [protected]
Definition at line 776 of file builtins-collections-gen.cc.
                                 {
  const TNode<ExternalReference> function_addr =
      ExternalConstant(ExternalReference::get_or_create_hash_raw());
  const TNode<ExternalReference> isolate_ptr =
      ExternalConstant(ExternalReference::isolate_address());
  MachineType type_ptr = MachineType::Pointer();
  MachineType type_tagged = MachineType::AnyTagged();
  TNode<Smi> result = CAST(CallCFunction(function_addr, type_tagged,
                                         std::make_pair(type_ptr, isolate_ptr),
                                         std::make_pair(type_tagged, key)));
  return result;
}
References v8::internal::MachineType::AnyTagged(), v8::internal::compiler::CodeAssembler::CallCFunction(), CAST, v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::ExternalReference::isolate_address(), v8::internal::key, v8::internal::MachineType::Pointer(), and v8::base::internal::result.
Referenced by AddToOrderedHashTable().
ComputeStringHash()
TNode< Uint32T > v8::internal::CollectionsBuiltinsAssembler::ComputeStringHash (TNode< String > string_key) [protected]
Definition at line 1250 of file builtins-collections-gen.cc.
                              {
  TVARIABLE(Uint32T, var_result);
  Label hash_not_computed(this), done(this, &var_result);
  const TNode<Uint32T> hash = LoadNameHash(string_key, &hash_not_computed);
  var_result = hash;
  Goto(&done);
  BIND(&hash_not_computed);
  var_result = CallGetHashRaw(string_key);
  Goto(&done);
  BIND(&done);
  return var_result.value();
}
References CallGetHashRaw(), v8::internal::compiler::CodeAssembler::Goto(), and v8::internal::CodeStubAssembler::LoadNameHash().
Referenced by AddNewToOrderedHashTable(), and FindOrderedHashTableEntryForStringKey().
ComputeUnseededHash()
TNode< Word32T > v8::internal::CollectionsBuiltinsAssembler::ComputeUnseededHash (TNode< IntPtrT > key) [protected]
Definition at line 1164 of file builtins-collections-gen.cc.
                        {
  // See v8::internal::ComputeUnseededHash()
  TNode<Word32T> hash = TruncateIntPtrToInt32(key);
  hash = Int32Add(Word32Xor(hash, Int32Constant(0xFFFFFFFF)),
                  Word32Shl(hash, Int32Constant(15)));
  hash = Word32Xor(hash, Word32Shr(hash, Int32Constant(12)));
  hash = Int32Add(hash, Word32Shl(hash, Int32Constant(2)));
  hash = Word32Xor(hash, Word32Shr(hash, Int32Constant(4)));
  hash = Int32Mul(hash, Int32Constant(2057));
  hash = Word32Xor(hash, Word32Shr(hash, Int32Constant(16)));
  return Word32And(hash, Int32Constant(0x3FFFFFFF));
}
References v8::internal::compiler::CodeAssembler::Int32Add(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::Int32Mul(), v8::internal::key, v8::internal::CodeStubAssembler::TruncateIntPtrToInt32(), v8::internal::compiler::CodeAssembler::Word32And(), v8::internal::compiler::CodeAssembler::Word32Shl(), and v8::internal::compiler::CodeAssembler::Word32Shr().
Referenced by AddNewToOrderedHashTable(), and FindOrderedHashTableEntryForSmiKey().
DeleteFromSetTable()
TNode< Smi > v8::internal::CollectionsBuiltinsAssembler::DeleteFromSetTable (const TNode< Object > context, TNode< OrderedHashSet > table, TNode< Object > key, Label * not_found)
Definition at line 2057 of file builtins-collections-gen.cc.
                      {
  TVARIABLE(IntPtrT, entry_start_position_or_hash, IntPtrConstant(0));
  Label entry_found(this);
  TryLookupOrderedHashTableIndex<OrderedHashSet>(
      table, key, &entry_start_position_or_hash, &entry_found, not_found);
  BIND(&entry_found);
  // If we found the entry, mark the entry as deleted.
  StoreKeyInOrderedHashSetEntry(table, HashTableHoleConstant(),
                                entry_start_position_or_hash.value());
  // Decrement the number of elements, increment the number of deleted elements.
  const TNode<Smi> number_of_elements = SmiSub(
      CAST(LoadObjectField(table, OrderedHashSet::NumberOfElementsOffset())),
      SmiConstant(1));
  StoreObjectFieldNoWriteBarrier(
      table, OrderedHashSet::NumberOfElementsOffset(), number_of_elements);
  const TNode<Smi> number_of_deleted =
      SmiAdd(CAST(LoadObjectField(
                 table, OrderedHashSet::NumberOfDeletedElementsOffset())),
             SmiConstant(1));
  StoreObjectFieldNoWriteBarrier(
      table, OrderedHashSet::NumberOfDeletedElementsOffset(),
      number_of_deleted);
  return number_of_elements;
}
References CAST, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::key, v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::OrderedHashTable< OrderedHashSet, 1 >::NumberOfDeletedElementsOffset(), v8::internal::OrderedHashTable< OrderedHashSet, 1 >::NumberOfElementsOffset(), v8::internal::compiler::CodeAssembler::SmiConstant(), StoreKeyInOrderedHashSetEntry(), and v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier().
FindOrderedHashTableEntry()
template<typename CollectionType >
void v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntry (const TNode< CollectionType > table, const TNode< Uint32T > hash, const std::function< void(TNode< Object >, Label *, Label *)> & key_compare, TVariable< IntPtrT > * entry_start_position, Label * entry_found, Label * not_found) [protected]
Definition at line 564 of file builtins-collections-gen.cc.
                      {
  // Get the index of the bucket.
  const TNode<Uint32T> number_of_buckets =
      PositiveSmiToUint32(CAST(UnsafeLoadFixedArrayElement(
          table, CollectionType::NumberOfBucketsIndex())));
  const TNode<Uint32T> bucket =
      Word32And(hash, Uint32Sub(number_of_buckets, Uint32Constant(1)));
  const TNode<IntPtrT> first_entry = SmiUntag(CAST(UnsafeLoadFixedArrayElement(
      table, Signed(ChangeUint32ToWord(bucket)),
      CollectionType::HashTableStartIndex() * kTaggedSize)));
  const TNode<IntPtrT> number_of_buckets_intptr =
      Signed(ChangeUint32ToWord(number_of_buckets));
  // Walk the bucket chain.
  TNode<IntPtrT> entry_start;
  Label if_key_found(this);
  {
    TVARIABLE(IntPtrT, var_entry, first_entry);
    Label loop(this, {&var_entry, entry_start_position}),
        continue_next_entry(this);
    Goto(&loop);
    BIND(&loop);
    // If the entry index is the not-found sentinel, we are done.
    GotoIf(IntPtrEqual(var_entry.value(),
                       IntPtrConstant(CollectionType::kNotFound)),
           not_found);
    // Make sure the entry index is within range.
    CSA_DCHECK(
        this,
        UintPtrLessThan(
            var_entry.value(),
            PositiveSmiUntag(SmiAdd(
                CAST(UnsafeLoadFixedArrayElement(
                    table, CollectionType::NumberOfElementsIndex())),
                CAST(UnsafeLoadFixedArrayElement(
                    table, CollectionType::NumberOfDeletedElementsIndex()))))));
    // Compute the index of the entry relative to kHashTableStartIndex.
    entry_start =
        IntPtrAdd(IntPtrMul(var_entry.value(),
                            IntPtrConstant(CollectionType::kEntrySize)),
                  number_of_buckets_intptr);
    // Load the key from the entry.
    const TNode<Object> candidate_key =
        UnsafeLoadKeyFromOrderedHashTableEntry(table, entry_start);
    key_compare(candidate_key, &if_key_found, &continue_next_entry);
    BIND(&continue_next_entry);
    // Load the index of the next entry in the bucket chain.
    var_entry = SmiUntag(CAST(UnsafeLoadFixedArrayElement(
        table, entry_start,
        (CollectionType::HashTableStartIndex() + CollectionType::kChainOffset) *
            kTaggedSize)));
    Goto(&loop);
  }
  BIND(&if_key_found);
  *entry_start_position = entry_start;
  Goto(entry_found);
}
References CAST, v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::compiler::CodeAssembler::IntPtrMul(), cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, v8::internal::kNotFound, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::PositiveSmiToUint32(), v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::internal::compiler::CodeAssembler::Signed(), v8::internal::CodeStubAssembler::SmiUntag(), v8::internal::compiler::CodeAssembler::Uint32Constant(), v8::internal::compiler::CodeAssembler::Uint32Sub(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan(), v8::internal::CodeStubAssembler::UnsafeLoadFixedArrayElement(), UnsafeLoadKeyFromOrderedHashTableEntry(), and v8::internal::compiler::CodeAssembler::Word32And().
FindOrderedHashTableEntryForBigIntKey()
template<typename CollectionType >
void v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForBigIntKey (TNode< CollectionType > table, TNode< BigInt > key_big_int, TVariable< IntPtrT > * result, Label * entry_found, Label * not_found) [protected]
Definition at line 1223 of file builtins-collections-gen.cc.
                                                                      {
  const TNode<Uint32T> hash = CallGetHashRaw(key_big_int);
  *result = Signed(ChangeUint32ToWord(hash));
  FindOrderedHashTableEntry<CollectionType>(
      table, hash,
      [&](TNode<Object> other_key, Label* if_same, Label* if_not_same) {
        SameValueZeroBigInt(key_big_int, other_key, if_same, if_not_same);
      },
      result, entry_found, not_found);
}
References CallGetHashRaw(), v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), v8::base::internal::result, SameValueZeroBigInt(), and v8::internal::compiler::CodeAssembler::Signed().
FindOrderedHashTableEntryForHeapNumberKey()
template<typename CollectionType >
void v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForHeapNumberKey (TNode< CollectionType > table, TNode< HeapNumber > key_heap_number, TVariable< IntPtrT > * result, Label * entry_found, Label * not_found) [protected]
Definition at line 1208 of file builtins-collections-gen.cc.
                                                                      {
  const TNode<Uint32T> hash = CallGetHashRaw(key_heap_number);
  *result = Signed(ChangeUint32ToWord(hash));
  const TNode<Float64T> key_float = LoadHeapNumberValue(key_heap_number);
  FindOrderedHashTableEntry<CollectionType>(
      table, hash,
      [&](TNode<Object> other_key, Label* if_same, Label* if_not_same) {
        SameValueZeroHeapNumber(key_float, other_key, if_same, if_not_same);
      },
      result, entry_found, not_found);
}
References CallGetHashRaw(), v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), v8::internal::CodeStubAssembler::LoadHeapNumberValue(), v8::base::internal::result, SameValueZeroHeapNumber(), and v8::internal::compiler::CodeAssembler::Signed().
FindOrderedHashTableEntryForOtherKey()
template<typename CollectionType >
void v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForOtherKey (TNode< CollectionType > table, TNode< HeapObject > key_heap_object, TVariable< IntPtrT > * result, Label * entry_found, Label * not_found) [protected]
Definition at line 1237 of file builtins-collections-gen.cc.
                                                                      {
  const TNode<Uint32T> hash = GetHash(key_heap_object);
  *result = Signed(ChangeUint32ToWord(hash));
  FindOrderedHashTableEntry<CollectionType>(
      table, hash,
      [&](TNode<Object> other_key, Label* if_same, Label* if_not_same) {
        Branch(TaggedEqual(key_heap_object, other_key), if_same, if_not_same);
      },
      result, entry_found, not_found);
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), GetHash(), v8::base::internal::result, v8::internal::compiler::CodeAssembler::Signed(), and v8::internal::CodeStubAssembler::TaggedEqual().
FindOrderedHashTableEntryForSmiKey()
template<typename CollectionType >
void v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForSmiKey (TNode< CollectionType > table, TNode< Smi > key_tagged, TVariable< IntPtrT > * result, Label * entry_found, Label * not_found) [protected]
Definition at line 1179 of file builtins-collections-gen.cc.
                                          {
  const TNode<IntPtrT> key_untagged = SmiUntag(smi_key);
  const TNode<Uint32T> hash = Unsigned(ComputeUnseededHash(key_untagged));
  *result = Signed(ChangeUint32ToWord(hash));
  FindOrderedHashTableEntry<CollectionType>(
      table, hash,
      [&](TNode<Object> other_key, Label* if_same, Label* if_not_same) {
        SameValueZeroSmi(smi_key, other_key, if_same, if_not_same);
      },
      result, entry_found, not_found);
}
References v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), ComputeUnseededHash(), v8::base::internal::result, SameValueZeroSmi(), v8::internal::compiler::CodeAssembler::Signed(), v8::internal::CodeStubAssembler::SmiUntag(), and v8::internal::compiler::CodeAssembler::Unsigned().
FindOrderedHashTableEntryForStringKey()
template<typename CollectionType >
void v8::internal::CollectionsBuiltinsAssembler::FindOrderedHashTableEntryForStringKey (TNode< CollectionType > table, TNode< String > key_tagged, TVariable< IntPtrT > * result, Label * entry_found, Label * not_found) [protected]
Definition at line 1194 of file builtins-collections-gen.cc.
                                                                      {
  const TNode<Uint32T> hash = ComputeStringHash(key_tagged);
  *result = Signed(ChangeUint32ToWord(hash));
  FindOrderedHashTableEntry<CollectionType>(
      table, hash,
      [&](TNode<Object> other_key, Label* if_same, Label* if_not_same) {
        SameValueZeroString(key_tagged, other_key, if_same, if_not_same);
      },
      result, entry_found, not_found);
}
References v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), ComputeStringHash(), v8::base::internal::result, SameValueZeroString(), and v8::internal::compiler::CodeAssembler::Signed().
GetEntriesIfFastCollectionOrIterable()
void v8::internal::CollectionsBuiltinsAssembler::GetEntriesIfFastCollectionOrIterable (Variant variant, TNode< Object > initial_entries, TNode< Context > context, TVariable< HeapObject > * var_entries_table, TVariable< IntPtrT > * var_number_of_elements, Label * if_not_fast_collection) [override], [protected], [virtual]
Implements v8::internal::BaseCollectionsAssembler.
Definition at line 639 of file builtins-collections-gen.cc.
                                                                               {
  Label if_fast_js_set(this), exit(this);
  DCHECK_EQ(variant, kSet);
  BranchIfIterableWithOriginalValueSetIterator(
      initial_entries, context, &if_fast_js_set, if_not_fast_collection);
  BIND(&if_fast_js_set);
  {
    *var_entries_table = SetOrSetIteratorToSet(initial_entries);
    TNode<Smi> size_smi = LoadObjectField<Smi>(
        var_entries_table->value(), OrderedHashMap::NumberOfElementsOffset());
    *var_number_of_elements = PositiveSmiUntag(size_smi);
    Goto(&exit);
  }
  BIND(&exit);
}
References BranchIfIterableWithOriginalValueSetIterator(), DCHECK_EQ, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::BaseCollectionsAssembler::kSet, v8::internal::OrderedHashTable< OrderedHashMap, 2 >::NumberOfElementsOffset(), v8::internal::CodeStubAssembler::PositiveSmiUntag(), SetOrSetIteratorToSet(), and v8::internal::compiler::TypedCodeAssemblerVariable< T >::value().
GetHash()
TNode< Uint32T > v8::internal::CollectionsBuiltinsAssembler::GetHash (const TNode< HeapObject > key) [protected]
Definition at line 809 of file builtins-collections-gen.cc.
                                 {
  TVARIABLE(Uint32T, var_hash);
  Label if_receiver(this), if_other(this), done(this);
  Branch(IsJSReceiver(key), &if_receiver, &if_other);
  BIND(&if_receiver);
  {
    var_hash = LoadJSReceiverIdentityHash(CAST(key));
    Goto(&done);
  }
  BIND(&if_other);
  {
    var_hash = CallGetHashRaw(key);
    Goto(&done);
  }
  BIND(&done);
  return var_hash.value();
}
References v8::internal::compiler::CodeAssembler::Branch(), CallGetHashRaw(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::CodeStubAssembler::IsJSReceiver(), v8::internal::key, and v8::internal::CodeStubAssembler::LoadJSReceiverIdentityHash().
Referenced by AddNewToOrderedHashTable(), and FindOrderedHashTableEntryForOtherKey().
LoadKeyFromOrderedHashTableEntry()
template<typename CollectionType >
TNode< JSAny > v8::internal::CollectionsBuiltinsAssembler::LoadKeyFromOrderedHashTableEntry (const TNode< CollectionType > table, const TNode< IntPtrT > entry, CheckBounds check_bounds = CheckBounds::kAlways) [protected]
Definition at line 2002 of file builtins-collections-gen.cc.
                              {
  return CAST(LoadFixedArrayElement(
      table, entry, kTaggedSize * CollectionType::HashTableStartIndex(),
      check_bounds));
}
References CAST, v8::internal::kTaggedSize, and v8::internal::CodeStubAssembler::LoadFixedArrayElement().
Referenced by UnsafeLoadKeyFromOrderedHashTableEntry().
LoadValueFromOrderedHashMapEntry()
TNode< UnionOf< JSAny, ArrayList > > v8::internal::CollectionsBuiltinsAssembler::LoadValueFromOrderedHashMapEntry (const TNode< OrderedHashMap > table, const TNode< IntPtrT > entry, CheckBounds check_bounds = CheckBounds::kAlways) [protected]
Definition at line 2011 of file builtins-collections-gen.cc.
                              {
  return CAST(LoadFixedArrayElement(
      table, entry,
      kTaggedSize * (OrderedHashMap::HashTableStartIndex() +
                     OrderedHashMap::kValueOffset),
      check_bounds));
}
References CAST, v8::internal::OrderedHashTable< OrderedHashMap, 2 >::HashTableStartIndex(), v8::internal::kTaggedSize, v8::internal::OrderedHashMap::kValueOffset, and v8::internal::CodeStubAssembler::LoadFixedArrayElement().
Referenced by AddValueToKeyedGroup(), and UnsafeLoadValueFromOrderedHashMapEntry().
MapIteratorToList()
TNode< JSArray > v8::internal::CollectionsBuiltinsAssembler::MapIteratorToList (TNode< Context > context, TNode< JSMapIterator > iterator) [protected]
Definition at line 1025 of file builtins-collections-gen.cc.
                                                           {
  // Transition the {iterator} table if necessary.
  TNode<OrderedHashMap> table;
  TNode<IntPtrT> index;
  std::tie(table, index) =
      TransitionAndUpdate<JSMapIterator, OrderedHashMap>(iterator);
  CSA_DCHECK(this, IntPtrEqual(index, IntPtrConstant(0)));
  TNode<Smi> size_smi =
      LoadObjectField<Smi>(table, OrderedHashMap::NumberOfElementsOffset());
  TNode<IntPtrT> size = PositiveSmiUntag(size_smi);
  const ElementsKind kind = PACKED_ELEMENTS;
  TNode<Map> array_map =
      LoadJSArrayElementsMap(kind, LoadNativeContext(context));
  TNode<JSArray> array = AllocateJSArray(kind, array_map, size, size_smi);
  TNode<FixedArray> elements = CAST(LoadElements(array));
  const int first_element_offset =
      OFFSET_OF_DATA_START(FixedArray) - kHeapObjectTag;
  TNode<IntPtrT> first_to_element_offset =
      ElementOffsetFromIndex(IntPtrConstant(0), kind, 0);
  TVARIABLE(
      IntPtrT, var_offset,
      IntPtrAdd(first_to_element_offset, IntPtrConstant(first_element_offset)));
  TVARIABLE(IntPtrT, var_index, index);
  VariableList vars({&var_index, &var_offset}, zone());
  Label done(this, {&var_index}), loop(this, vars), continue_loop(this, vars),
      write_key(this, vars), write_value(this, vars);
  Goto(&loop);
  BIND(&loop);
  {
    // Read the next entry from the {table}, skipping holes.
    TNode<Object> entry_key;
    TNode<IntPtrT> entry_start_position;
    TNode<IntPtrT> cur_index;
    std::tie(entry_key, entry_start_position, cur_index) =
        NextSkipHashTableHoles<OrderedHashMap>(table, var_index.value(), &done);
    // Decide to write key or value.
    Branch(
        InstanceTypeEqual(LoadInstanceType(iterator), JS_MAP_KEY_ITERATOR_TYPE),
        &write_key, &write_value);
    BIND(&write_key);
    {
      Store(elements, var_offset.value(), entry_key);
      Goto(&continue_loop);
    }
    BIND(&write_value);
    {
      CSA_DCHECK(this, InstanceTypeEqual(LoadInstanceType(iterator),
                                         JS_MAP_VALUE_ITERATOR_TYPE));
      TNode<Object> entry_value =
          UnsafeLoadValueFromOrderedHashMapEntry(table, entry_start_position);
      Store(elements, var_offset.value(), entry_value);
      Goto(&continue_loop);
    }
    BIND(&continue_loop);
    {
      // Increment the array offset and continue the loop to the next entry.
      var_index = cur_index;
      var_offset = IntPtrAdd(var_offset.value(), IntPtrConstant(kTaggedSize));
      Goto(&loop);
    }
  }
  BIND(&done);
  // Set the {iterator} to exhausted.
  StoreObjectFieldRoot(iterator, JSMapIterator::kTableOffset,
                       RootIndex::kEmptyOrderedHashMap);
  StoreObjectFieldNoWriteBarrier(iterator, JSMapIterator::kIndexOffset,
                                 SmiTag(var_index.value()));
  return UncheckedCast<JSArray>(array);
}
References v8::internal::CodeStubAssembler::AllocateJSArray(), v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::CodeStubAssembler::ElementOffsetFromIndex(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::index, v8::internal::CodeStubAssembler::InstanceTypeEqual(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::kHeapObjectTag, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::LoadElements(), v8::internal::CodeStubAssembler::LoadInstanceType(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::OrderedHashTable< OrderedHashMap, 2 >::NumberOfElementsOffset(), OFFSET_OF_DATA_START, v8::internal::PACKED_ELEMENTS, v8::internal::CodeStubAssembler::PositiveSmiUntag(), size(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::compiler::CodeAssembler::Store(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), v8::internal::CodeStubAssembler::StoreObjectFieldRoot(), UnsafeLoadValueFromOrderedHashMapEntry(), and v8::internal::compiler::CodeAssembler::zone().
NextKeyIndexPair()
template<typename CollectionType >
template TorqueStructKeyIndexPair v8::internal::CollectionsBuiltinsAssembler::NextKeyIndexPair (const TNode< CollectionType > table, const TNode< IntPtrT > index, Label * if_end)
Definition at line 1527 of file builtins-collections-gen.cc.
                   {
  TNode<JSAny> key;
  TNode<IntPtrT> entry_start_position;
  TNode<IntPtrT> next_index;
  std::tie(key, entry_start_position, next_index) =
      NextSkipHashTableHoles<CollectionType>(table, index, if_end);
  return TorqueStructKeyIndexPair{key, next_index};
}
References v8::internal::index, and v8::internal::key.
NextKeyIndexPairUnmodifiedTable()
template<typename CollectionType >
template TorqueStructKeyIndexPair v8::internal::CollectionsBuiltinsAssembler::NextKeyIndexPairUnmodifiedTable (const TNode< CollectionType > table, const TNode< Int32T > number_of_buckets, const TNode< Int32T > used_capacity, const TNode< IntPtrT > index, Label * if_end)
Definition at line 1497 of file builtins-collections-gen.cc.
                   {
  // Unmodified tables do not have transitions.
  CSA_DCHECK(this, TaggedIsSmi(LoadObjectField(
                       table, CollectionType::NextTableOffset())));
  TNode<JSAny> key;
  TNode<IntPtrT> entry_start_position;
  TNode<IntPtrT> next_index;
  std::tie(key, entry_start_position, next_index) = NextSkipHashTableHoles(
      table, number_of_buckets, used_capacity, index, if_end);
  return TorqueStructKeyIndexPair{key, next_index};
}
References v8::internal::index, v8::internal::key, v8::internal::CodeStubAssembler::LoadObjectField(), NextSkipHashTableHoles(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
NextKeyValueIndexTuple()
TorqueStructKeyValueIndexTuple v8::internal::CollectionsBuiltinsAssembler::NextKeyValueIndexTuple (const TNode< OrderedHashMap > table, const TNode< IntPtrT > index, Label * if_end)
Definition at line 1568 of file builtins-collections-gen.cc.
                   {
  TNode<JSAny> key;
  TNode<IntPtrT> entry_start_position;
  TNode<IntPtrT> next_index;
  std::tie(key, entry_start_position, next_index) =
      NextSkipHashTableHoles(table, index, if_end);
  TNode<JSAny> value =
      CAST(UnsafeLoadValueFromOrderedHashMapEntry(table, entry_start_position));
  return TorqueStructKeyValueIndexTuple{key, value, next_index};
}
References CAST, v8::internal::index, v8::internal::key, NextSkipHashTableHoles(), UnsafeLoadValueFromOrderedHashMapEntry(), and v8::internal::value.
NextKeyValueIndexTupleUnmodifiedTable()
TorqueStructKeyValueIndexTuple v8::internal::CollectionsBuiltinsAssembler::NextKeyValueIndexTupleUnmodifiedTable (const TNode< OrderedHashMap > table, const TNode< Int32T > number_of_buckets, const TNode< Int32T > used_capacity, const TNode< IntPtrT > index, Label * if_end)
Definition at line 1550 of file builtins-collections-gen.cc.
                   {
  TNode<JSAny> key;
  TNode<IntPtrT> entry_start_position;
  TNode<IntPtrT> next_index;
  std::tie(key, entry_start_position, next_index) = NextSkipHashTableHoles(
      table, number_of_buckets, used_capacity, index, if_end);
  TNode<JSAny> value =
      CAST(UnsafeLoadValueFromOrderedHashMapEntry(table, entry_start_position));
  return TorqueStructKeyValueIndexTuple{key, value, next_index};
}
References CAST, v8::internal::index, v8::internal::key, NextSkipHashTableHoles(), UnsafeLoadValueFromOrderedHashMapEntry(), and v8::internal::value.
NextSkipHashTableHoles() [1/2]
template<typename TableType >
std::tuple< TNode< JSAny >, TNode< IntPtrT >, TNode< IntPtrT > > v8::internal::CollectionsBuiltinsAssembler::NextSkipHashTableHoles (TNode< TableType > table, TNode< Int32T > number_of_buckets, TNode< Int32T > used_capacity, TNode< IntPtrT > index, Label * if_end) [protected]
Definition at line 1458 of file builtins-collections-gen.cc.
                                                                      {
  CSA_DCHECK(this, Word32Equal(number_of_buckets,
                               LoadAndUntagToWord32ObjectField(
                                   table, TableType::NumberOfBucketsOffset())));
  CSA_DCHECK(
      this,
      Word32Equal(
          used_capacity,
          Int32Add(LoadAndUntagToWord32ObjectField(
                       table, TableType::NumberOfElementsOffset()),
                   LoadAndUntagToWord32ObjectField(
                       table, TableType::NumberOfDeletedElementsOffset()))));
  TNode<JSAny> entry_key;
  TNode<Int32T> entry_start_position;
  TVARIABLE(Int32T, var_index, TruncateIntPtrToInt32(index));
  Label loop(this, &var_index), done_loop(this);
  Goto(&loop);
  BIND(&loop);
  {
    GotoIfNot(Int32LessThan(var_index.value(), used_capacity), if_end);
    entry_start_position = Int32Add(
        Int32Mul(var_index.value(), Int32Constant(TableType::kEntrySize)),
        number_of_buckets);
    entry_key = UnsafeLoadKeyFromOrderedHashTableEntry(
        table, ChangePositiveInt32ToIntPtr(entry_start_position));
    var_index = Int32Add(var_index.value(), Int32Constant(1));
    Branch(IsHashTableHole(entry_key), &loop, &done_loop);
  }
  BIND(&done_loop);
  return {entry_key, ChangePositiveInt32ToIntPtr(entry_start_position),
          ChangePositiveInt32ToIntPtr(var_index.value())};
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::CodeStubAssembler::ChangePositiveInt32ToIntPtr(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::index, v8::internal::compiler::CodeAssembler::Int32Add(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::Int32Mul(), cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, v8::internal::CodeStubAssembler::LoadAndUntagToWord32ObjectField(), v8::internal::CodeStubAssembler::TruncateIntPtrToInt32(), UnsafeLoadKeyFromOrderedHashTableEntry(), and v8::internal::compiler::CodeAssembler::Word32Equal().
NextSkipHashTableHoles() [2/2]
template<typename TableType >
std::tuple< TNode< JSAny >, TNode< IntPtrT >, TNode< IntPtrT > > v8::internal::CollectionsBuiltinsAssembler::NextSkipHashTableHoles (TNode< TableType > table, TNode< IntPtrT > index, Label * if_end) [protected]
Definition at line 1439 of file builtins-collections-gen.cc.
                                                                    {
  // Compute the used capacity for the {table}.
  TNode<Int32T> number_of_buckets = LoadAndUntagToWord32ObjectField(
      table, TableType::NumberOfBucketsOffset());
  TNode<Int32T> number_of_elements = LoadAndUntagToWord32ObjectField(
      table, TableType::NumberOfElementsOffset());
  TNode<Int32T> number_of_deleted_elements = LoadAndUntagToWord32ObjectField(
      table, TableType::NumberOfDeletedElementsOffset());
  TNode<Int32T> used_capacity =
      Int32Add(number_of_elements, number_of_deleted_elements);
  return NextSkipHashTableHoles(table, number_of_buckets, used_capacity, index,
                                if_end);
}
References v8::internal::index, v8::internal::compiler::CodeAssembler::Int32Add(), and v8::internal::CodeStubAssembler::LoadAndUntagToWord32ObjectField().
Referenced by NextKeyIndexPairUnmodifiedTable(), NextKeyValueIndexTuple(), and NextKeyValueIndexTupleUnmodifiedTable().
NormalizeNumberKey()
const TNode< JSAny > v8::internal::CollectionsBuiltinsAssembler::NormalizeNumberKey (const TNode< JSAny > key)
Definition at line 1636 of file builtins-collections-gen.cc.
                            {
  TVARIABLE(JSAny, result, key);
  Label done(this);
  GotoIf(TaggedIsSmi(key), &done);
  GotoIfNot(IsHeapNumber(CAST(key)), &done);
  const TNode<Float64T> number = LoadHeapNumberValue(CAST(key));
  GotoIfNot(Float64Equal(number, Float64Constant(0.0)), &done);
  // We know the value is zero, so we take the key to be Smi 0.
  // Another option would be to normalize to Smi here.
  result = SmiConstant(0);
  Goto(&done);
  BIND(&done);
  return result.value();
}
References CAST, v8::internal::compiler::CodeAssembler::Float64Constant(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::key, v8::internal::CodeStubAssembler::LoadHeapNumberValue(), v8::base::internal::result, v8::internal::compiler::CodeAssembler::SmiConstant(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
Referenced by AddNewToOrderedHashSet(), and AddToSetTable().
SameValueZeroBigInt()
void v8::internal::CollectionsBuiltinsAssembler::SameValueZeroBigInt (TNode< BigInt > key, TNode< Object > candidate_key, Label * if_same, Label * if_not_same) [protected]
Definition at line 1278 of file builtins-collections-gen.cc.
                        {
  GotoIf(TaggedIsSmi(candidate_key), if_not_same);
  GotoIfNot(IsBigInt(CAST(candidate_key)), if_not_same);
  Branch(TaggedEqual(CallRuntime(Runtime::kBigIntEqualToBigInt,
                                 NoContextConstant(), key, candidate_key),
                     TrueConstant()),
         if_same, if_not_same);
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::IsBigInt(), v8::internal::key, v8::internal::CodeStubAssembler::NoContextConstant(), v8::internal::CodeStubAssembler::TaggedEqual(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
Referenced by FindOrderedHashTableEntryForBigIntKey().
SameValueZeroHeapNumber()
void v8::internal::CollectionsBuiltinsAssembler::SameValueZeroHeapNumber (TNode< Float64T > key_float, TNode< Object > candidate_key, Label * if_same, Label * if_not_same) [protected]
Definition at line 1290 of file builtins-collections-gen.cc.
                        {
  Label if_smi(this), if_keyisnan(this);
  GotoIf(TaggedIsSmi(candidate_key), &if_smi);
  GotoIfNot(IsHeapNumber(CAST(candidate_key)), if_not_same);
  {
    // {candidate_key} is a heap number.
    const TNode<Float64T> candidate_float =
        LoadHeapNumberValue(CAST(candidate_key));
    GotoIf(Float64Equal(key_float, candidate_float), if_same);
    // SameValueZero needs to treat NaNs as equal. First check if {key_float}
    // is NaN.
    BranchIfFloat64IsNaN(key_float, &if_keyisnan, if_not_same);
    BIND(&if_keyisnan);
    {
      // Return true iff {candidate_key} is NaN.
      Branch(Float64Equal(candidate_float, candidate_float), if_not_same,
             if_same);
    }
  }
  BIND(&if_smi);
  {
    const TNode<Float64T> candidate_float = SmiToFloat64(CAST(candidate_key));
    Branch(Float64Equal(key_float, candidate_float), if_same, if_not_same);
  }
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::CodeStubAssembler::BranchIfFloat64IsNaN(), CAST, v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::LoadHeapNumberValue(), v8::internal::CodeStubAssembler::SmiToFloat64(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
Referenced by FindOrderedHashTableEntryForHeapNumberKey().
SameValueZeroSmi()
void v8::internal::CollectionsBuiltinsAssembler::SameValueZeroSmi (TNode< Smi > key_smi, TNode< Object > candidate_key, Label * if_same, Label * if_not_same) [protected]
Definition at line 831 of file builtins-collections-gen.cc.
                                                                        {
  // If the key is the same, we are done.
  GotoIf(TaggedEqual(candidate_key, key_smi), if_same);
  // If the candidate key is smi, then it must be different (because
  // we already checked for equality above).
  GotoIf(TaggedIsSmi(candidate_key), if_not_same);
  // If the candidate key is not smi, we still have to check if it is a
  // heap number with the same value.
  GotoIfNot(IsHeapNumber(CAST(candidate_key)), if_not_same);
  const TNode<Float64T> candidate_key_number =
      LoadHeapNumberValue(CAST(candidate_key));
  const TNode<Float64T> key_number = SmiToFloat64(key_smi);
  GotoIf(Float64Equal(candidate_key_number, key_number), if_same);
  Goto(if_not_same);
}
References CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::LoadHeapNumberValue(), v8::internal::CodeStubAssembler::SmiToFloat64(), v8::internal::CodeStubAssembler::TaggedEqual(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
Referenced by FindOrderedHashTableEntryForSmiKey().
SameValueZeroString()
void v8::internal::CollectionsBuiltinsAssembler::SameValueZeroString (TNode< String > key_string, TNode< Object > candidate_key, Label * if_same, Label * if_not_same) [protected]
Definition at line 1267 of file builtins-collections-gen.cc.
                        {
  // If the candidate is not a string, the keys are not equal.
  GotoIf(TaggedIsSmi(candidate_key), if_not_same);
  GotoIfNot(IsString(CAST(candidate_key)), if_not_same);
  GotoIf(TaggedEqual(key_string, candidate_key), if_same);
  BranchIfStringEqual(key_string, CAST(candidate_key), if_same, if_not_same);
}
References v8::internal::CodeStubAssembler::BranchIfStringEqual(), CAST, v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::IsString(), v8::internal::CodeStubAssembler::TaggedEqual(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
Referenced by FindOrderedHashTableEntryForStringKey().
SetOrSetIteratorToList()
TNode< JSArray > v8::internal::CollectionsBuiltinsAssembler::SetOrSetIteratorToList (TNode< Context > context, TNode< HeapObject > iterable) [protected]
Definition at line 1113 of file builtins-collections-gen.cc.
                                                        {
  TNode<OrderedHashSet> table = SetOrSetIteratorToSet(iterable);
  TNode<Smi> size_smi =
      LoadObjectField<Smi>(table, OrderedHashMap::NumberOfElementsOffset());
  TNode<IntPtrT> size = PositiveSmiUntag(size_smi);
  const ElementsKind kind = PACKED_ELEMENTS;
  TNode<Map> array_map =
      LoadJSArrayElementsMap(kind, LoadNativeContext(context));
  TNode<JSArray> array = AllocateJSArray(kind, array_map, size, size_smi);
  TNode<FixedArray> elements = CAST(LoadElements(array));
  const int first_element_offset =
      OFFSET_OF_DATA_START(FixedArray) - kHeapObjectTag;
  TNode<IntPtrT> first_to_element_offset =
      ElementOffsetFromIndex(IntPtrConstant(0), kind, 0);
  TVARIABLE(
      IntPtrT, var_offset,
      IntPtrAdd(first_to_element_offset, IntPtrConstant(first_element_offset)));
  TVARIABLE(IntPtrT, var_index, IntPtrConstant(0));
  Label done(this), loop(this, {&var_index, &var_offset});
  Goto(&loop);
  BIND(&loop);
  {
    // Read the next entry from the {table}, skipping holes.
    TNode<Object> entry_key;
    TNode<IntPtrT> entry_start_position;
    TNode<IntPtrT> cur_index;
    std::tie(entry_key, entry_start_position, cur_index) =
        NextSkipHashTableHoles<OrderedHashSet>(table, var_index.value(), &done);
    Store(elements, var_offset.value(), entry_key);
    var_index = cur_index;
    var_offset = IntPtrAdd(var_offset.value(), IntPtrConstant(kTaggedSize));
    Goto(&loop);
  }
  BIND(&done);
  return UncheckedCast<JSArray>(array);
}
References v8::internal::CodeStubAssembler::AllocateJSArray(), CAST, v8::internal::CodeStubAssembler::ElementOffsetFromIndex(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::kHeapObjectTag, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::LoadElements(), v8::internal::CodeStubAssembler::LoadJSArrayElementsMap(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::OrderedHashTable< OrderedHashMap, 2 >::NumberOfElementsOffset(), OFFSET_OF_DATA_START, v8::internal::PACKED_ELEMENTS, v8::internal::CodeStubAssembler::PositiveSmiUntag(), SetOrSetIteratorToSet(), size(), and v8::internal::compiler::CodeAssembler::Store().
SetOrSetIteratorToSet()
TNode< OrderedHashSet > v8::internal::CollectionsBuiltinsAssembler::SetOrSetIteratorToSet (TNode< Object > iterator) [protected]
Definition at line 984 of file builtins-collections-gen.cc.
                            {
  TVARIABLE(OrderedHashSet, var_table);
  Label if_set(this), if_iterator(this), done(this);
  const TNode<Uint16T> instance_type = LoadInstanceType(CAST(iterable));
  Branch(InstanceTypeEqual(instance_type, JS_SET_TYPE), &if_set, &if_iterator);
  BIND(&if_set);
  {
    // {iterable} is a JSSet.
    var_table = LoadObjectField<OrderedHashSet>(CAST(iterable),
                                                GetTableOffset(Variant::kSet));
    Goto(&done);
  }
  BIND(&if_iterator);
  {
    // {iterable} is a JSSetIterator.
    // Transition the {iterable} table if necessary.
    TNode<JSSetIterator> iterator = CAST(iterable);
    TNode<OrderedHashSet> table;
    TNode<IntPtrT> index;
    std::tie(table, index) =
        TransitionAndUpdate<JSSetIterator, OrderedHashSet>(iterator);
    CSA_DCHECK(this, IntPtrEqual(index, IntPtrConstant(0)));
    var_table = table;
    // Set the {iterable} to exhausted if it's an iterator.
    StoreObjectFieldRoot(iterator, JSSetIterator::kTableOffset,
                         RootIndex::kEmptyOrderedHashSet);
    TNode<IntPtrT> number_of_elements = LoadAndUntagPositiveSmiObjectField(
        table, OrderedHashSet::NumberOfElementsOffset());
    StoreObjectFieldNoWriteBarrier(iterator, JSSetIterator::kIndexOffset,
                                   SmiTag(number_of_elements));
    Goto(&done);
  }
  BIND(&done);
  return var_table.value();
}
References v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::BaseCollectionsAssembler::GetTableOffset(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::index, v8::internal::CodeStubAssembler::InstanceTypeEqual(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::CodeStubAssembler::LoadInstanceType(), v8::internal::OrderedHashTable< OrderedHashSet, 1 >::NumberOfElementsOffset(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), and v8::internal::CodeStubAssembler::StoreObjectFieldRoot().
Referenced by GetEntriesIfFastCollectionOrIterable(), and SetOrSetIteratorToList().
StoreKeyInOrderedHashSetEntry()
void v8::internal::CollectionsBuiltinsAssembler::StoreKeyInOrderedHashSetEntry (const TNode< OrderedHashSet > table, const TNode< Object > key, const TNode< IntPtrT > entry, CheckBounds check_bounds = CheckBounds::kAlways) [protected]
Definition at line 1993 of file builtins-collections-gen.cc.
                                                                {
  StoreFixedArrayElement(table, entry_start, key, UPDATE_WRITE_BARRIER,
                         kTaggedSize * OrderedHashSet::HashTableStartIndex(),
                         check_bounds);
}
References v8::internal::OrderedHashTable< OrderedHashSet, 1 >::HashTableStartIndex(), v8::internal::key, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::StoreFixedArrayElement(), and v8::internal::UPDATE_WRITE_BARRIER.
Referenced by DeleteFromSetTable(), and UnsafeStoreKeyInOrderedHashSetEntry().
StoreKeyValueInOrderedHashMapEntry()
void v8::internal::CollectionsBuiltinsAssembler::StoreKeyValueInOrderedHashMapEntry (const TNode< OrderedHashMap > table, const TNode< Object > key, const TNode< Object > value, const TNode< IntPtrT > entry, CheckBounds check_bounds = CheckBounds::kAlways) [protected]
Definition at line 1868 of file builtins-collections-gen.cc.
                              {
  StoreFixedArrayElement(table, entry_start, key, UPDATE_WRITE_BARRIER,
                         kTaggedSize * OrderedHashMap::HashTableStartIndex(),
                         check_bounds);
  StoreValueInOrderedHashMapEntry(table, value, entry_start, check_bounds);
}
References v8::internal::OrderedHashTable< OrderedHashMap, 2 >::HashTableStartIndex(), v8::internal::key, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::StoreFixedArrayElement(), StoreValueInOrderedHashMapEntry(), v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
Referenced by AddValueToKeyedGroup(), and UnsafeStoreKeyValueInOrderedHashMapEntry().
StoreOrderedHashTableNewEntry()
template<typename CollectionType >
void v8::internal::CollectionsBuiltinsAssembler::StoreOrderedHashTableNewEntry (const TNode< CollectionType > table, const TNode< IntPtrT > hash, const TNode< IntPtrT > number_of_buckets, const TNode< IntPtrT > occupancy, const StoreAtEntry< CollectionType > & store_at_new_entry) [protected]
Definition at line 1769 of file builtins-collections-gen.cc.
                                                            {
  const TNode<IntPtrT> bucket =
      WordAnd(hash, IntPtrSub(number_of_buckets, IntPtrConstant(1)));
  TNode<Smi> bucket_entry = CAST(UnsafeLoadFixedArrayElement(
      table, bucket, CollectionType::HashTableStartIndex() * kTaggedSize));
  // Store the entry elements.
  const TNode<IntPtrT> entry_start = IntPtrAdd(
      IntPtrMul(occupancy, IntPtrConstant(CollectionType::kEntrySize)),
      number_of_buckets);
  store_at_new_entry(table, entry_start);
  // Connect the element to the bucket chain.
  UnsafeStoreFixedArrayElement(
      table, entry_start, bucket_entry,
      kTaggedSize * (CollectionType::HashTableStartIndex() +
                     CollectionType::kChainOffset));
  // Update the bucket head.
  UnsafeStoreFixedArrayElement(
      table, bucket, SmiTag(occupancy),
      CollectionType::HashTableStartIndex() * kTaggedSize);
  // Bump the elements count.
  const TNode<Smi> number_of_elements =
      CAST(LoadObjectField(table, CollectionType::NumberOfElementsOffset()));
  StoreObjectFieldNoWriteBarrier(table,
                                 CollectionType::NumberOfElementsOffset(),
                                 SmiAdd(number_of_elements, SmiConstant(1)));
}
References CAST, v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrMul(), v8::internal::compiler::CodeAssembler::IntPtrSub(), cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, v8::internal::kTaggedSize, v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), v8::internal::CodeStubAssembler::UnsafeLoadFixedArrayElement(), v8::internal::CodeStubAssembler::UnsafeStoreFixedArrayElement(), and v8::internal::compiler::CodeAssembler::WordAnd().
Referenced by AddNewToOrderedHashTable(), and AddToOrderedHashTable().
StoreValueInOrderedHashMapEntry()
void v8::internal::CollectionsBuiltinsAssembler::StoreValueInOrderedHashMapEntry (const TNode< OrderedHashMap > table, const TNode< Object > value, const TNode< IntPtrT > entry, CheckBounds check_bounds = CheckBounds::kAlways) [protected]
Definition at line 1859 of file builtins-collections-gen.cc.
                                                                {
  StoreFixedArrayElement(table, entry_start, value, UPDATE_WRITE_BARRIER,
                         kTaggedSize * (OrderedHashMap::HashTableStartIndex() +
                                        OrderedHashMap::kValueOffset),
                         check_bounds);
}
References v8::internal::OrderedHashTable< OrderedHashMap, 2 >::HashTableStartIndex(), v8::internal::kTaggedSize, v8::internal::OrderedHashMap::kValueOffset, v8::internal::CodeStubAssembler::StoreFixedArrayElement(), v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
Referenced by StoreKeyValueInOrderedHashMapEntry(), and UnsafeStoreValueInOrderedHashMapEntry().
TableHasKey() [1/2]
TNode< BoolT > v8::internal::CollectionsBuiltinsAssembler::TableHasKey (const TNode< Object > context, TNode< OrderedHashMap > table, TNode< Object > key)
Definition at line 1627 of file builtins-collections-gen.cc.
                       {
  TNode<Smi> index =
      CAST(CallBuiltin(Builtin::kFindOrderedHashMapEntry, context, table, key));
  return SmiGreaterThanOrEqual(index, SmiConstant(0));
}
References v8::internal::compiler::CodeAssembler::CallBuiltin(), CAST, v8::internal::index, v8::internal::key, and v8::internal::compiler::CodeAssembler::SmiConstant().
TableHasKey() [2/2]
TNode< BoolT > v8::internal::CollectionsBuiltinsAssembler::TableHasKey (const TNode< Object > context, TNode< OrderedHashSet > table, TNode< Object > key)
Definition at line 2278 of file builtins-collections-gen.cc.
                       {
  TNode<Smi> index =
      CAST(CallBuiltin(Builtin::kFindOrderedHashSetEntry, context, table, key));
  return SmiGreaterThanOrEqual(index, SmiConstant(0));
}
References v8::internal::compiler::CodeAssembler::CallBuiltin(), CAST, v8::internal::index, v8::internal::key, and v8::internal::compiler::CodeAssembler::SmiConstant().
Transition()
template<typename TableType >
std::pair< TNode< TableType >, TNode< IntPtrT > > v8::internal::CollectionsBuiltinsAssembler::Transition (const TNode< TableType > table, const TNode< IntPtrT > index, UpdateInTransition< TableType > const & update_in_transition) [protected]
Definition at line 1370 of file builtins-collections-gen.cc.
                                                               {
  TVARIABLE(IntPtrT, var_index, index);
  TVARIABLE(TableType, var_table, table);
  Label if_done(this), if_transition(this, Label::kDeferred);
  Branch(TaggedIsSmi(
             LoadObjectField(var_table.value(), TableType::NextTableOffset())),
         &if_done, &if_transition);
  BIND(&if_transition);
  {
    Label loop(this, {&var_table, &var_index}), done_loop(this);
    Goto(&loop);
    BIND(&loop);
    {
      TNode<TableType> current_table = var_table.value();
      TNode<IntPtrT> current_index = var_index.value();
      TNode<Object> next_table =
          LoadObjectField(current_table, TableType::NextTableOffset());
      GotoIf(TaggedIsSmi(next_table), &done_loop);
      var_table = CAST(next_table);
      var_index = SmiUntag(CAST(CallBuiltin(Builtin::kOrderedHashTableHealIndex,
                                            NoContextConstant(), current_table,
                                            SmiTag(current_index))));
      Goto(&loop);
    }
    BIND(&done_loop);
    // Update with the new {table} and {index}.
    update_in_transition(var_table.value(), var_index.value());
    Goto(&if_done);
  }
  BIND(&if_done);
  return {var_table.value(), var_index.value()};
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::CallBuiltin(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::index, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::CodeStubAssembler::NoContextConstant(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::SmiUntag(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
TransitionAndUpdate()
template<typename IteratorType , typename TableType >
std::pair< TNode< TableType >, TNode< IntPtrT > > v8::internal::CollectionsBuiltinsAssembler::TransitionAndUpdate (const TNode< IteratorType > iterator) [protected]
Definition at line 1412 of file builtins-collections-gen.cc.
                                        {
  return Transition<TableType>(
      CAST(LoadObjectField(iterator, IteratorType::kTableOffset)),
      LoadAndUntagPositiveSmiObjectField(iterator, IteratorType::kIndexOffset),
      [this, iterator](const TNode<TableType> table,
                       const TNode<IntPtrT> index) {
        // Update the {iterator} with the new state.
        StoreObjectField(iterator, IteratorType::kTableOffset, table);
        StoreObjectFieldNoWriteBarrier(iterator, IteratorType::kIndexOffset,
                                       SmiTag(index));
      });
}
References CAST, v8::internal::index, v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::StoreObjectField(), and v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier().
TransitionOrderedHashSetNoUpdate()
TorqueStructOrderedHashSetIndexPair v8::internal::CollectionsBuiltinsAssembler::TransitionOrderedHashSetNoUpdate (const TNode< OrderedHashSet > table, const TNode< IntPtrT > index)
Definition at line 1427 of file builtins-collections-gen.cc.
                                                                           {
  TNode<OrderedHashSet> table;
  TNode<IntPtrT> index;
  std::tie(table, index) = Transition<OrderedHashSet>(
      table_arg, index_arg,
      [](const TNode<OrderedHashSet>, const TNode<IntPtrT>) {});
  return TorqueStructOrderedHashSetIndexPair{table, index};
}
References v8::internal::index.
TryLookupOrderedHashTableIndex()
template<typename CollectionType >
void v8::internal::CollectionsBuiltinsAssembler::TryLookupOrderedHashTableIndex (const TNode< CollectionType > table, const TNode< Object > key, TVariable< IntPtrT > * result, Label * if_entry_found, Label * if_not_found) [protected]
Definition at line 2441 of file builtins-collections-gen.cc.
                                                                            {
  Label if_key_smi(this), if_key_string(this), if_key_heap_number(this),
      if_key_bigint(this);
  GotoIf(TaggedIsSmi(key), &if_key_smi);
  TNode<Map> key_map = LoadMap(CAST(key));
  TNode<Uint16T> key_instance_type = LoadMapInstanceType(key_map);
  GotoIf(IsStringInstanceType(key_instance_type), &if_key_string);
  GotoIf(IsHeapNumberMap(key_map), &if_key_heap_number);
  GotoIf(IsBigIntInstanceType(key_instance_type), &if_key_bigint);
  FindOrderedHashTableEntryForOtherKey<CollectionType>(
      table, CAST(key), result, if_entry_found, if_not_found);
  BIND(&if_key_smi);
  {
    FindOrderedHashTableEntryForSmiKey<CollectionType>(
        table, CAST(key), result, if_entry_found, if_not_found);
  }
  BIND(&if_key_string);
  {
    FindOrderedHashTableEntryForStringKey<CollectionType>(
        table, CAST(key), result, if_entry_found, if_not_found);
  }
  BIND(&if_key_heap_number);
  {
    FindOrderedHashTableEntryForHeapNumberKey<CollectionType>(
        table, CAST(key), result, if_entry_found, if_not_found);
  }
  BIND(&if_key_bigint);
  {
    FindOrderedHashTableEntryForBigIntKey<CollectionType>(
        table, CAST(key), result, if_entry_found, if_not_found);
  }
}
References CAST, v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::IsBigIntInstanceType(), v8::internal::CodeStubAssembler::IsStringInstanceType(), v8::internal::key, v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapInstanceType(), v8::base::internal::result, and v8::internal::CodeStubAssembler::TaggedIsSmi().
UnsafeLoadKeyFromOrderedHashTableEntry()
template<typename CollectionType >
TNode<JSAny> v8::internal::CollectionsBuiltinsAssembler::UnsafeLoadKeyFromOrderedHashTableEntry (const TNode< CollectionType > table, const TNode< IntPtrT > entry) [inline], [protected]
Definition at line 457 of file builtins-collections-gen.h.
                                                                     {
    return LoadKeyFromOrderedHashTableEntry(table, entry,
                                            CheckBounds::kDebugOnly);
  }
References v8::internal::kDebugOnly, and LoadKeyFromOrderedHashTableEntry().
Referenced by AddConstructorEntriesFromSet(), FindOrderedHashTableEntry(), and NextSkipHashTableHoles().
UnsafeLoadValueFromOrderedHashMapEntry()
TNode<UnionOf<JSAny, ArrayList> > v8::internal::CollectionsBuiltinsAssembler::UnsafeLoadValueFromOrderedHashMapEntry (const TNode< OrderedHashMap > table, const TNode< IntPtrT > entry) [inline], [protected]
Definition at line 444 of file builtins-collections-gen.h.
                                                                     {
    return LoadValueFromOrderedHashMapEntry(table, entry,
                                            CheckBounds::kDebugOnly);
  }
References v8::internal::kDebugOnly, and LoadValueFromOrderedHashMapEntry().
Referenced by MapIteratorToList(), NextKeyValueIndexTuple(), and NextKeyValueIndexTupleUnmodifiedTable().
UnsafeStoreKeyInOrderedHashSetEntry()
void v8::internal::CollectionsBuiltinsAssembler::UnsafeStoreKeyInOrderedHashSetEntry (const TNode< OrderedHashSet > table, const TNode< Object > key, const TNode< IntPtrT > entry) [inline], [protected]
Definition at line 433 of file builtins-collections-gen.h.
                                                                       {
    return StoreKeyInOrderedHashSetEntry(table, key, entry,
                                         CheckBounds::kDebugOnly);
  }
References v8::internal::kDebugOnly, v8::internal::key, and StoreKeyInOrderedHashSetEntry().
Referenced by AddNewToOrderedHashSet(), and AddToSetTable().
UnsafeStoreKeyValueInOrderedHashMapEntry()
void v8::internal::CollectionsBuiltinsAssembler::UnsafeStoreKeyValueInOrderedHashMapEntry (const TNode< OrderedHashMap > table, const TNode< Object > key, const TNode< Object > value, const TNode< IntPtrT > entry) [inline], [protected]
Definition at line 427 of file builtins-collections-gen.h.
                                                             {
    return StoreKeyValueInOrderedHashMapEntry(table, key, value, entry,
                                              CheckBounds::kDebugOnly);
  }
References v8::internal::kDebugOnly, v8::internal::key, StoreKeyValueInOrderedHashMapEntry(), and v8::internal::value.
UnsafeStoreValueInOrderedHashMapEntry()
void v8::internal::CollectionsBuiltinsAssembler::UnsafeStoreValueInOrderedHashMapEntry (const TNode< OrderedHashMap > table, const TNode< Object > value, const TNode< IntPtrT > entry) [inline]
Definition at line 213 of file builtins-collections-gen.h.
                                                                         {
    return StoreValueInOrderedHashMapEntry(table, value, entry,
                                           CheckBounds::kDebugOnly);
  }
References v8::internal::kDebugOnly, StoreValueInOrderedHashMapEntry(), and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-collections-gen.h
/mnt/V8SourceCode/src/builtins/builtins-collections-gen.cc