v8::internal::NativeFunctionLiteral Class Reference
#include <ast.h>
Public Member Functions
DirectHandle< String > name () const
const AstRawString * raw_name () const
v8::Extension * extension () const
Private Member Functions
NativeFunctionLiteral (const AstRawString *name, v8::Extension *extension, int pos)
Private Attributes
friend Zone
const AstRawString * name_
v8::Extension * extension_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 2776 of file ast.h.
Constructor & Destructor Documentation
NativeFunctionLiteral()
v8::internal::NativeFunctionLiteral::NativeFunctionLiteral (const AstRawString * name, v8::Extension * extension, int pos) [inline], [private]
Definition at line 2786 of file ast.h.
      : Expression(pos, kNativeFunctionLiteral),
        name_(name),
        extension_(extension) {}
Member Function Documentation
extension()
v8::Extension* v8::internal::NativeFunctionLiteral::extension () const [inline]
Definition at line 2780 of file ast.h.
{ return extension_; }
References extension_.
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants().
name()
DirectHandle<String> v8::internal::NativeFunctionLiteral::name () const [inline]
Definition at line 2778 of file ast.h.
{ return name_->string(); }
References name_, and v8::internal::AstRawString::string().
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants().
raw_name()
const AstRawString* v8::internal::NativeFunctionLiteral::raw_name () const [inline]
Definition at line 2779 of file ast.h.
{ return name_; }
References name_.
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 2783 of file ast.h.
Member Data Documentation
extension_
v8::Extension* v8::internal::NativeFunctionLiteral::extension_ [private]
Definition at line 2793 of file ast.h.
Referenced by extension().
name_
const AstRawString* v8::internal::NativeFunctionLiteral::name_ [private]
Definition at line 2792 of file ast.h.
Referenced by name(), and raw_name().
Zone
friend v8::internal::NativeFunctionLiteral::Zone [private]
Definition at line 2784 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h