v8::internal::compiler::StringRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< String > object () const
OptionalObjectRef GetCharAsStringOrUndefined (JSHeapBroker *broker, uint32_t index) const
std::optional< Handle< String > > ObjectIfContentAccessible (JSHeapBroker *broker)
uint32_t length () const
std::optional< uint16_t > GetFirstChar (JSHeapBroker *broker) const
std::optional< uint16_t > GetChar (JSHeapBroker *broker, uint32_t index) const
std::optional< double > ToNumber (JSHeapBroker *broker)
std::optional< double > ToInt (JSHeapBroker *broker, int radix)
V8_EXPORT_PRIVATE bool IsSeqString () const
bool IsExternalString () const
bool IsContentAccessible () const
V8_EXPORT_PRIVATE bool IsOneByteRepresentation () const
Private Member Functions
bool SupportedStringKind () const
Detailed Description
Definition at line 1183 of file heap-refs.h.
Member Function Documentation
GetChar()
std::optional< uint16_t > v8::internal::compiler::StringRef::GetChar (JSHeapBroker * broker, uint32_t index) const
Definition at line 1446 of file heap-refs.cc.
                                                                 {
  if (!IsContentAccessible()) {
    TRACE_BROKER_MISSING(
        broker,
        "get char for kNeverSerialized unsupported string kind " << *this);
    return std::nullopt;
  }
  if (!broker->IsMainThread()) {
    return object()->Get(index, broker->local_isolate());
  } else {
    // TODO(solanes, v8:7790): Remove this case once the inlining phase is
    // done concurrently all the time.
    return object()->Get(index);
  }
}
References broker(), v8::internal::index, IsContentAccessible(), object(), and TRACE_BROKER_MISSING.
Referenced by GetFirstChar(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), and v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith().
GetCharAsStringOrUndefined()
OptionalObjectRef v8::internal::compiler::StringRef::GetCharAsStringOrUndefined (JSHeapBroker * broker, uint32_t index) const
Definition at line 1397 of file heap-refs.cc.
                                                                              {
  Tagged<String> maybe_char;
  auto result = ConcurrentLookupIterator::TryGetOwnChar(
      &maybe_char, broker->isolate(), broker->local_isolate(), *object(),
      index);
  if (result == ConcurrentLookupIterator::kGaveUp) {
    TRACE_BROKER_MISSING(broker, "StringRef::GetCharAsStringOrUndefined on "
                                     << *this << " at index " << index);
    return {};
  }
  DCHECK_EQ(result, ConcurrentLookupIterator::kPresent);
  return TryMakeRef(broker, maybe_char);
}
References broker(), DCHECK_EQ, v8::internal::index, v8::internal::ConcurrentLookupIterator::kGaveUp, v8::internal::ConcurrentLookupIterator::kPresent, v8::base::internal::result, TRACE_BROKER_MISSING, v8::internal::ConcurrentLookupIterator::TryGetOwnChar(), and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt().
GetFirstChar()
std::optional< uint16_t > v8::internal::compiler::StringRef::GetFirstChar (JSHeapBroker * broker) const
Definition at line 1442 of file heap-refs.cc.
                                                                        {
  return GetChar(broker, 0);
}
References broker(), and GetChar().
IsContentAccessible()
bool v8::internal::compiler::StringRef::IsContentAccessible () const
Definition at line 1418 of file heap-refs.cc.
                                          {
  return data_->kind() != kNeverSerializedHeapObject || SupportedStringKind();
}
References v8::internal::compiler::kNeverSerializedHeapObject, and SupportedStringKind().
Referenced by GetChar(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::IsStringWithNonAccessibleContent(), ObjectIfContentAccessible(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStartsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), ToInt(), and ToNumber().
IsExternalString()
bool v8::internal::compiler::StringRef::IsExternalString () const
Definition at line 1898 of file heap-refs.cc.
                                       {
  return i::IsExternalString(*object());
}
References v8::internal::InstanceTypeChecker::IsExternalString().
Referenced by v8::internal::compiler::JSBinopReduction::ShouldCreateConsString().
IsOneByteRepresentation()
bool v8::internal::compiler::StringRef::IsOneByteRepresentation () const
Definition at line 1422 of file heap-refs.cc.
                                              {
  return object()->IsOneByteRepresentation();
}
References object().
Referenced by v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt().
IsSeqString()
bool v8::internal::compiler::StringRef::IsSeqString () const
Definition at line 1914 of file heap-refs.cc.
{ return i::IsSeqString(*object()); }
References v8::internal::InstanceTypeChecker::IsSeqString().
Referenced by v8::internal::compiler::JSBinopReduction::ShouldCreateConsString(), and v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::StringAt().
length()
uint32_t v8::internal::compiler::StringRef::length () const
Definition at line 1440 of file heap-refs.cc.
{ return object()->length(kAcquireLoad); }
References v8::kAcquireLoad, and object().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::GetMaxStringLength(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeCharAt(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeEndsWith(), v8::internal::compiler::JSCallReducer::ReduceStringPrototypeStartsWith(), v8::internal::compiler::JSCallReducerAssembler::ReduceStringPrototypeStartsWith(), and v8::internal::compiler::JSBinopReduction::ShouldCreateConsString().
object()
IndirectHandle<String> v8::internal::compiler::StringRef::object () const
Referenced by v8::internal::compiler::AccessInfoFactory::ComputePropertyAccessInfo(), GetChar(), IsOneByteRepresentation(), length(), ObjectIfContentAccessible(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
ObjectIfContentAccessible()
std::optional< Handle< String > > v8::internal::compiler::StringRef::ObjectIfContentAccessible (JSHeapBroker * broker)
Definition at line 1428 of file heap-refs.cc.
                          {
  if (!IsContentAccessible()) {
    TRACE_BROKER_MISSING(
        broker,
        "content for kNeverSerialized unsupported string kind " << *this);
    return std::nullopt;
  } else {
    return object();
  }
}
References broker(), IsContentAccessible(), object(), and TRACE_BROKER_MISSING.
Referenced by v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
SupportedStringKind()
bool v8::internal::compiler::StringRef::SupportedStringKind () const [private]
Definition at line 1414 of file heap-refs.cc.
                                          {
  return IsInternalizedString() || IsThinString(*object());
}
References v8::internal::InstanceTypeChecker::IsInternalizedString(), and v8::internal::InstanceTypeChecker::IsThinString().
Referenced by IsContentAccessible().
ToInt()
std::optional< double > v8::internal::compiler::StringRef::ToInt (JSHeapBroker * broker, int radix)
Definition at line 1475 of file heap-refs.cc.
                                                                    {
  if (!IsContentAccessible()) {
    TRACE_BROKER_MISSING(
        broker, "toInt for kNeverSerialized unsupported string kind " << *this);
    return std::nullopt;
  }
  return TryStringToInt(broker->local_isolate(), object(), radix);
}
References broker(), IsContentAccessible(), TRACE_BROKER_MISSING, and v8::internal::TryStringToInt().
Referenced by v8::internal::compiler::JSCallReducer::ReduceNumberParseInt().
ToNumber()
std::optional< double > v8::internal::compiler::StringRef::ToNumber (JSHeapBroker * broker)
Definition at line 1464 of file heap-refs.cc.
                                                            {
  if (!IsContentAccessible()) {
    TRACE_BROKER_MISSING(
        broker,
        "number for kNeverSerialized unsupported string kind " << *this);
    return std::nullopt;
  }
  return TryStringToDouble(broker->local_isolate(), object());
}
References broker(), IsContentAccessible(), TRACE_BROKER_MISSING, and v8::internal::TryStringToDouble().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSToNumberInput(), and v8::internal::compiler::TypedOptimization::ReduceJSToNumberInput().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc