v8::internal::compiler::CodeAssemblerParameterizedLabelBase Class Reference
#include <code-assembler.h>
Public Member Functions
bool is_used () const
CodeAssemblerParameterizedLabelBase (CodeAssembler *assembler, size_t arity, CodeAssemblerLabel::Type type)
Protected Member Functions
CodeAssemblerLabel * plain_label ()
void AddInputs (std::vector< Node * > inputs)
Node * CreatePhi (MachineRepresentation rep, const std::vector< Node * > &inputs)
const std::vector< Node * > & CreatePhis (std::vector< MachineRepresentation > representations)
Private Attributes
CodeAssemblerState * state_
std::vector< std::vector< Node * > > phi_inputs_
std::vector< Node * > phi_nodes_
CodeAssemblerLabel plain_label_
Detailed Description
Definition at line 1817 of file code-assembler.h.
Constructor & Destructor Documentation
CodeAssemblerParameterizedLabelBase()
v8::internal::compiler::CodeAssemblerParameterizedLabelBase::CodeAssemblerParameterizedLabelBase (CodeAssembler * assembler, size_t arity, CodeAssemblerLabel::Type type) [inline], [explicit]
Definition at line 1820 of file code-assembler.h.
      : state_(assembler->state()),
        phi_inputs_(arity),
        plain_label_(assembler, type) {}
Member Function Documentation
AddInputs()
void v8::internal::compiler::CodeAssemblerParameterizedLabelBase::AddInputs (std::vector< Node * > inputs) [protected]
Definition at line 1970 of file code-assembler.cc.
                                                                           {
  if (!phi_nodes_.empty()) {
    DCHECK_EQ(inputs.size(), phi_nodes_.size());
    for (size_t i = 0; i < inputs.size(); ++i) {
      // We use {nullptr} as a sentinel for an uninitialized value.
      if (phi_nodes_[i] == nullptr) continue;
      state_->raw_assembler_->AppendPhiInput(phi_nodes_[i], inputs[i]);
    }
  } else {
    DCHECK_EQ(inputs.size(), phi_inputs_.size());
    for (size_t i = 0; i < inputs.size(); ++i) {
      phi_inputs_[i].push_back(inputs[i]);
    }
  }
}
References DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, phi_inputs_, phi_nodes_, v8::internal::compiler::CodeAssemblerState::raw_assembler_, and state_.
Referenced by v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::AddInputs(), and v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::AddInputsVector().
CreatePhi()
Node * v8::internal::compiler::CodeAssemblerParameterizedLabelBase::CreatePhi (MachineRepresentation rep, const std::vector< Node * > & inputs) [protected]
Definition at line 1986 of file code-assembler.cc.
                                                               {
  for (Node* input : inputs) {
    // We use {nullptr} as a sentinel for an uninitialized value. We must not
    // create phi nodes for these.
    if (input == nullptr) return nullptr;
  }
  return state_->raw_assembler_->Phi(rep, static_cast<int>(inputs.size()),
                                     &inputs.front());
}
References v8::internal::compiler::CodeAssemblerState::raw_assembler_, and state_.
Referenced by CreatePhis().
CreatePhis()
const std::vector< Node * > & v8::internal::compiler::CodeAssemblerParameterizedLabelBase::CreatePhis (std::vector< MachineRepresentation > representations) [protected]
Definition at line 1997 of file code-assembler.cc.
                                                      {
  DCHECK(is_used());
  DCHECK(phi_nodes_.empty());
  phi_nodes_.reserve(phi_inputs_.size());
  DCHECK_EQ(representations.size(), phi_inputs_.size());
  for (size_t i = 0; i < phi_inputs_.size(); ++i) {
    phi_nodes_.push_back(CreatePhi(representations[i], phi_inputs_[i]));
  }
  return phi_nodes_;
}
References CreatePhi(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, is_used(), phi_inputs_, and phi_nodes_.
Referenced by v8::internal::compiler::CodeAssemblerParameterizedLabel< Types >::CreatePhis().
is_used()
bool v8::internal::compiler::CodeAssemblerParameterizedLabelBase::is_used () const [inline]
Definition at line 1819 of file code-assembler.h.
{ return plain_label_.is_used(); }
References v8::internal::compiler::CodeAssemblerLabel::is_used(), and plain_label_.
Referenced by CreatePhis().
plain_label()
CodeAssemblerLabel* v8::internal::compiler::CodeAssemblerParameterizedLabelBase::plain_label () [inline], [protected]
Definition at line 1828 of file code-assembler.h.
{ return &plain_label_; }
References plain_label_.
Referenced by v8::internal::compiler::CodeAssembler::Bind(), v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::Goto(), and v8::internal::compiler::CodeAssembler::HandleException().
Member Data Documentation
phi_inputs_
std::vector<std::vector<Node*> > v8::internal::compiler::CodeAssemblerParameterizedLabelBase::phi_inputs_ [private]
Definition at line 1836 of file code-assembler.h.
Referenced by AddInputs(), and CreatePhis().
phi_nodes_
std::vector<Node*> v8::internal::compiler::CodeAssemblerParameterizedLabelBase::phi_nodes_ [private]
Definition at line 1837 of file code-assembler.h.
Referenced by AddInputs(), and CreatePhis().
plain_label_
CodeAssemblerLabel v8::internal::compiler::CodeAssemblerParameterizedLabelBase::plain_label_ [private]
Definition at line 1838 of file code-assembler.h.
Referenced by is_used(), and plain_label().
state_
CodeAssemblerState* v8::internal::compiler::CodeAssemblerParameterizedLabelBase::state_ [private]
Definition at line 1835 of file code-assembler.h.
Referenced by AddInputs(), and CreatePhi().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/code-assembler.h
/mnt/V8SourceCode/src/compiler/code-assembler.cc