v8::internal::ConcurrentMarking Class Reference
#include <concurrent-marking.h>
Classes
class JobTaskMajor
class JobTaskMinor
class MinorMarkingState
struct TaskState
Public Member Functions
ConcurrentMarking (Heap *heap, WeakObjects *weak_objects)
~ConcurrentMarking ()
void TryScheduleJob (GarbageCollector garbage_collector, TaskPriority priority=TaskPriority::kUserVisible)
void Join ()
void JoinJobForTesting ()
bool Pause ()
void RescheduleJobIfNeeded (GarbageCollector garbage_collector, TaskPriority priority=TaskPriority::kUserVisible)
void FlushNativeContexts (NativeContextStats *main_stats)
void FlushMemoryChunkData ()
void FlushPretenuringFeedback ()
bool IsStopped ()
size_t TotalMarkedBytes ()
void set_another_ephemeron_iteration (bool another_ephemeron_iteration)
bool another_ephemeron_iteration ()
GarbageCollector garbage_collector () const
bool IsWorkLeft () const
size_t FetchAndResetConcurrencyEstimate ()
Private Member Functions
void RunMinor (JobDelegate *delegate)
template<YoungGenerationMarkingVisitationMode marking_mode>
size_t RunMinorImpl (JobDelegate *delegate, TaskState *task_state)
void RunMajor (JobDelegate *delegate, base::EnumSet< CodeFlushMode > code_flush_mode, unsigned mark_compact_epoch, bool should_keep_ages_unchanged)
size_t GetMajorMaxConcurrency (size_t worker_count)
size_t GetMinorMaxConcurrency (size_t worker_count)
void Resume ()
Private Attributes
std::unique_ptr< JobHandle > job_handle_
Heap *const heap_
std::optional< GarbageCollector > garbage_collector_
MarkingWorklists * marking_worklists_
WeakObjects *const weak_objects_
std::vector< std::unique_ptr< TaskState > > task_state_
std::atomic< size_t > total_marked_bytes_ {0}
std::atomic< bool > another_ephemeron_iteration_ {false}
std::optional< uint64_t > current_job_trace_id_
std::unique_ptr< MinorMarkingState > minor_marking_state_
std::atomic< size_t > estimate_concurrency_ {0}
Friends
class Heap
Detailed Description
Definition at line 35 of file concurrent-marking.h.
Constructor & Destructor Documentation
ConcurrentMarking()
v8::internal::ConcurrentMarking::ConcurrentMarking (Heap * heap, WeakObjects * weak_objects)
Definition at line 327 of file concurrent-marking.cc.
    : heap_(heap), weak_objects_(weak_objects) {
#ifndef V8_ATOMIC_OBJECT_FIELD_WRITES
  // Concurrent marking requires atomic object field writes.
  CHECK(!v8_flags.concurrent_marking);
#endif
  int max_tasks;
  if (v8_flags.concurrent_marking_max_worker_num == 0) {
    max_tasks = V8::GetCurrentPlatform()->NumberOfWorkerThreads();
  } else {
    max_tasks = v8_flags.concurrent_marking_max_worker_num;
  }
  task_state_.reserve(max_tasks + 1);
  for (int i = 0; i <= max_tasks; ++i) {
    task_state_.emplace_back(std::make_unique<TaskState>());
  }
}
References CHECK, v8::internal::V8::GetCurrentPlatform(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::Platform::NumberOfWorkerThreads(), task_state_, and v8::internal::v8_flags.
 ConcurrentMarking()
v8::internal::ConcurrentMarking::~ConcurrentMarking () [default]
Member Function Documentation
another_ephemeron_iteration()
bool v8::internal::ConcurrentMarking::another_ephemeron_iteration () [inline]
Definition at line 77 of file concurrent-marking.h.
                                     {
    return another_ephemeron_iteration_.load();
  }
Referenced by RunMajor().
FetchAndResetConcurrencyEstimate()
size_t v8::internal::ConcurrentMarking::FetchAndResetConcurrencyEstimate () [inline]
Definition at line 88 of file concurrent-marking.h.
                                            {
    const size_t estimate =
        estimate_concurrency_.exchange(0, std::memory_order_relaxed);
    return estimate ? estimate : 1;
  }
Referenced by v8::internal::MinorMarkSweepCollector::FinishConcurrentMarking().
FlushMemoryChunkData()
void v8::internal::ConcurrentMarking::FlushMemoryChunkData ()
Definition at line 853 of file concurrent-marking.cc.
                                             {
  DCHECK(!job_handle_ || !job_handle_->IsValid());
  for (auto& task_state : task_state_) {
    task_state->memory_chunk_live_bytes_map.FlushAndClear();
    for (auto&& [page, typed_slots] :
         task_state->memory_chunk_typed_slots_map) {
      RememberedSet<OLD_TO_OLD>::MergeTyped(page, std::move(typed_slots));
    }
    task_state->memory_chunk_typed_slots_map.clear();
    task_state->marked_bytes = 0;
  }
  total_marked_bytes_ = 0;
}
References v8::internal::DCHECK(), job_handle_, v8::internal::RememberedSet< type >::MergeTyped(), task_state_, and total_marked_bytes_.
Referenced by v8::internal::MarkCompactCollector::FinishConcurrentMarking().
FlushNativeContexts()
void v8::internal::ConcurrentMarking::FlushNativeContexts (NativeContextStats * main_stats)
Definition at line 845 of file concurrent-marking.cc.
                                                                          {
  DCHECK(!job_handle_ || !job_handle_->IsValid());
  for (size_t i = 1; i < task_state_.size(); i++) {
    main_stats->Merge(task_state_[i]->native_context_stats);
    task_state_[i]->native_context_stats.Clear();
  }
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, job_handle_, v8::internal::NativeContextStats::Merge(), and task_state_.
Referenced by v8::internal::MarkCompactCollector::FinishConcurrentMarking().
FlushPretenuringFeedback()
void v8::internal::ConcurrentMarking::FlushPretenuringFeedback ()
Definition at line 787 of file concurrent-marking.cc.
                                                 {
  PretenuringHandler* pretenuring_handler = heap_->pretenuring_handler();
  for (auto& task_state : task_state_) {
    pretenuring_handler->MergeAllocationSitePretenuringFeedback(
        task_state->local_pretenuring_feedback);
    task_state->local_pretenuring_feedback.clear();
  }
}
References heap_, v8::internal::PretenuringHandler::MergeAllocationSitePretenuringFeedback(), v8::internal::Heap::pretenuring_handler(), and task_state_.
Referenced by v8::internal::MinorMarkSweepCollector::FinishConcurrentMarking().
garbage_collector()
GarbageCollector v8::internal::ConcurrentMarking::garbage_collector () const [inline]
Definition at line 81 of file concurrent-marking.h.
                                             {
    DCHECK(garbage_collector_.has_value());
    return garbage_collector_.value();
  }
References v8::internal::DCHECK().
Referenced by v8::internal::MarkCompactCollector::FinishConcurrentMarking(), v8::internal::MinorMarkSweepCollector::FinishConcurrentMarking(), RescheduleJobIfNeeded(), and TryScheduleJob().
GetMajorMaxConcurrency()
size_t v8::internal::ConcurrentMarking::GetMajorMaxConcurrency (size_t worker_count) [private]
Definition at line 616 of file concurrent-marking.cc.
                                                                    {
  size_t marking_items = marking_worklists_->shared()->Size();
  marking_items += marking_worklists_->other()->Size();
  for (auto& worklist : marking_worklists_->context_worklists()) {
    marking_items += worklist.worklist->Size();
  }
  const size_t work = std::max<size_t>(
      {marking_items, weak_objects_->current_ephemerons.Size()});
  size_t jobs = worker_count + work;
  jobs = std::min<size_t>(task_state_.size() - 1, jobs);
  if (heap_->ShouldOptimizeForBattery()) {
    return std::min<size_t>(jobs, 1);
  }
  return jobs;
}
References v8::internal::MarkingWorklists::context_worklists(), heap_, marking_worklists_, v8::internal::MarkingWorklists::other(), v8::internal::MarkingWorklists::shared(), v8::internal::Heap::ShouldOptimizeForBattery(), heap::base::Worklist< EntryType, MinSegmentSize >::Size(), task_state_, and weak_objects_.
Referenced by v8::internal::ConcurrentMarking::JobTaskMajor::GetMaxConcurrency().
GetMinorMaxConcurrency()
size_t v8::internal::ConcurrentMarking::GetMinorMaxConcurrency (size_t worker_count) [private]
Definition at line 632 of file concurrent-marking.cc.
                                                                    {
  const size_t marking_items = marking_worklists_->shared()->Size() +
                               heap_->minor_mark_sweep_collector()
                                   ->remembered_sets_marking_handler()
                                   ->RemainingRememberedSetsMarkingIteams();
  DCHECK(marking_worklists_->other()->IsEmpty());
  DCHECK(!marking_worklists_->IsUsingContextWorklists());
  size_t jobs = worker_count + marking_items;
  jobs = std::min<size_t>(task_state_.size() - 1, jobs);
  if (heap_->ShouldOptimizeForBattery()) {
    return std::min<size_t>(jobs, 1);
  }
  return jobs;
}
References v8::internal::DCHECK(), heap_, heap::base::Worklist< EntryType, MinSegmentSize >::IsEmpty(), v8::internal::MarkingWorklists::IsUsingContextWorklists(), marking_worklists_, v8::internal::Heap::minor_mark_sweep_collector(), v8::internal::MarkingWorklists::other(), v8::internal::YoungGenerationRememberedSetsMarkingWorklist::RemainingRememberedSetsMarkingIteams(), v8::internal::MinorMarkSweepCollector::remembered_sets_marking_handler(), v8::internal::MarkingWorklists::shared(), v8::internal::Heap::ShouldOptimizeForBattery(), heap::base::Worklist< EntryType, MinSegmentSize >::Size(), and task_state_.
Referenced by v8::internal::ConcurrentMarking::JobTaskMinor::GetMaxConcurrency().
IsStopped()
bool v8::internal::ConcurrentMarking::IsStopped ()
Definition at line 828 of file concurrent-marking.cc.
                                  {
  if (!v8_flags.concurrent_marking && !v8_flags.parallel_marking) return true;
  return !job_handle_ || !job_handle_->IsValid();
}
References job_handle_, and v8::internal::v8_flags.
Referenced by v8::internal::MinorMarkSweepCollector::FinishConcurrentMarking(), RescheduleJobIfNeeded(), v8::internal::MinorMarkSweepCollector::TearDown(), and TryScheduleJob().
IsWorkLeft()
bool v8::internal::ConcurrentMarking::IsWorkLeft () const
Definition at line 730 of file concurrent-marking.cc.
                                         {
  DCHECK(garbage_collector_.has_value());
  if (garbage_collector_ == GarbageCollector::MARK_COMPACTOR) {
    return !marking_worklists_->shared()->IsEmpty() ||
           !weak_objects_->current_ephemerons.IsEmpty();
  }
  DCHECK_EQ(GarbageCollector::MINOR_MARK_SWEEPER, garbage_collector_);
  return !marking_worklists_->shared()->IsEmpty() ||
         (heap_->minor_mark_sweep_collector()
              ->remembered_sets_marking_handler()
              ->RemainingRememberedSetsMarkingIteams() > 0);
}
References v8::internal::DCHECK(), DCHECK_EQ, garbage_collector_, heap_, heap::base::Worklist< EntryType, MinSegmentSize >::IsEmpty(), v8::internal::MARK_COMPACTOR, marking_worklists_, v8::internal::Heap::minor_mark_sweep_collector(), v8::internal::MINOR_MARK_SWEEPER, v8::internal::YoungGenerationRememberedSetsMarkingWorklist::RemainingRememberedSetsMarkingIteams(), v8::internal::MinorMarkSweepCollector::remembered_sets_marking_handler(), v8::internal::MarkingWorklists::shared(), and weak_objects_.
Referenced by RescheduleJobIfNeeded().
Join()
void v8::internal::ConcurrentMarking::Join ()
Definition at line 796 of file concurrent-marking.cc.
                             {
  DCHECK(v8_flags.parallel_marking || v8_flags.concurrent_marking ||
         v8_flags.concurrent_minor_ms_marking);
  DCHECK_IMPLIES(
      garbage_collector_ == GarbageCollector::MARK_COMPACTOR,
      heap_->mark_compact_collector()->UseBackgroundThreadsInCycle());
  if (!job_handle_ || !job_handle_->IsValid()) return;
  job_handle_->Join();
  current_job_trace_id_.reset();
  garbage_collector_.reset();
  minor_marking_state_.reset();
}
References current_job_trace_id_, v8::internal::DCHECK(), DCHECK_IMPLIES, garbage_collector_, heap_, job_handle_, v8::internal::Heap::mark_compact_collector(), v8::internal::MARK_COMPACTOR, minor_marking_state_, v8::internal::MarkCompactCollector::UseBackgroundThreadsInCycle(), and v8::internal::v8_flags.
Referenced by v8::internal::MarkCompactCollector::FinishConcurrentMarking(), and v8::internal::MinorMarkSweepCollector::FinishConcurrentMarking().
JoinJobForTesting()
void v8::internal::ConcurrentMarking::JoinJobForTesting ()
Definition at line 809 of file concurrent-marking.cc.
                                          {
  if (!job_handle_ || !job_handle_->IsValid()) return;
  job_handle_->Join();
}
References job_handle_.
Pause()
bool v8::internal::ConcurrentMarking::Pause ()
Definition at line 814 of file concurrent-marking.cc.
                              {
  DCHECK(v8_flags.parallel_marking || v8_flags.concurrent_marking);
  if (!job_handle_ || !job_handle_->IsValid()) return false;
  job_handle_->Cancel();
  DCHECK(current_job_trace_id_.has_value());
  TRACE_GC_NOTE_WITH_FLOW(garbage_collector_ == GarbageCollector::MARK_COMPACTOR
                              ? "Major concurrent marking paused"
                              : "Minor concurrent marking paused",
                          current_job_trace_id_.value(),
                          TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
  return true;
}
References current_job_trace_id_, v8::internal::DCHECK(), garbage_collector_, job_handle_, v8::internal::MARK_COMPACTOR, TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_NOTE_WITH_FLOW, and v8::internal::v8_flags.
Referenced by v8::internal::Heap::PauseConcurrentThreadsInClients(), and v8::internal::Heap::StartTearDown().
RescheduleJobIfNeeded()
void v8::internal::ConcurrentMarking::RescheduleJobIfNeeded (GarbageCollector garbage_collector, TaskPriority priority = TaskPriority::kUserVisible)
Definition at line 743 of file concurrent-marking.cc.
                                                               {
  DCHECK(v8_flags.parallel_marking || v8_flags.concurrent_marking ||
         v8_flags.concurrent_minor_ms_marking);
  if (garbage_collector == GarbageCollector::MARK_COMPACTOR &&
      !heap_->mark_compact_collector()->UseBackgroundThreadsInCycle()) {
    return;
  }
  if (garbage_collector == GarbageCollector::MINOR_MARK_SWEEPER &&
      !heap_->minor_mark_sweep_collector()->UseBackgroundThreadsInCycle()) {
    return;
  }
  if (heap_->IsTearingDown()) return;
  if (IsStopped()) {
    // This DCHECK is for the case that concurrent marking was paused.
    DCHECK_IMPLIES(garbage_collector_.has_value(),
                   garbage_collector == garbage_collector_);
    TryScheduleJob(garbage_collector, priority);
  } else {
    DCHECK(garbage_collector_.has_value());
    DCHECK_EQ(garbage_collector, garbage_collector_.value());
    if (garbage_collector == GarbageCollector::MARK_COMPACTOR) {
      heap_->mark_compact_collector()->local_marking_worklists()->Publish();
    } else {
      heap_->minor_mark_sweep_collector()->local_marking_worklists()->Publish();
    }
    if (!IsWorkLeft()) return;
    if (priority != TaskPriority::kUserVisible)
      job_handle_->UpdatePriority(priority);
    DCHECK(current_job_trace_id_.has_value());
    TRACE_GC_NOTE_WITH_FLOW(
        garbage_collector_ == GarbageCollector::MARK_COMPACTOR
            ? "Major concurrent marking rescheduled"
            : "Minor concurrent marking rescheduled",
        current_job_trace_id_.value(),
        TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
    job_handle_->NotifyConcurrencyIncrease();
  }
}
References current_job_trace_id_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, garbage_collector(), garbage_collector_, heap_, IsStopped(), v8::internal::Heap::IsTearingDown(), IsWorkLeft(), job_handle_, v8::kUserVisible, v8::internal::MinorMarkSweepCollector::local_marking_worklists(), v8::internal::MarkCompactCollector::local_marking_worklists(), v8::internal::Heap::mark_compact_collector(), v8::internal::MARK_COMPACTOR, v8::internal::Heap::minor_mark_sweep_collector(), v8::internal::MINOR_MARK_SWEEPER, TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_NOTE_WITH_FLOW, TryScheduleJob(), v8::internal::MarkCompactCollector::UseBackgroundThreadsInCycle(), v8::internal::MinorMarkSweepCollector::UseBackgroundThreadsInCycle(), and v8::internal::v8_flags.
Referenced by v8::internal::PagedNewSpaceAllocatorPolicy::EnsureAllocation(), v8::internal::MinorMarkSweepCollector::MarkLiveObjects(), v8::internal::MarkCompactCollector::MaybeEnableBackgroundThreadsInCycle(), Resume(), and v8::internal::IncrementalMarking::Step().
Resume()
void v8::internal::ConcurrentMarking::Resume () [private]
Definition at line 834 of file concurrent-marking.cc.
                               {
  DCHECK(garbage_collector_.has_value());
  DCHECK(current_job_trace_id_.has_value());
  TRACE_GC_NOTE_WITH_FLOW(garbage_collector_ == GarbageCollector::MARK_COMPACTOR
                              ? "Major concurrent marking resumed"
                              : "Minor concurrent marking resumed",
                          current_job_trace_id_.value(),
                          TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
  RescheduleJobIfNeeded(garbage_collector_.value());
}
References current_job_trace_id_, v8::internal::DCHECK(), garbage_collector_, v8::internal::MARK_COMPACTOR, RescheduleJobIfNeeded(), TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, and TRACE_GC_NOTE_WITH_FLOW.
RunMajor()
void v8::internal::ConcurrentMarking::RunMajor (JobDelegate * delegate, base::EnumSet< CodeFlushMode > code_flush_mode, unsigned mark_compact_epoch, bool should_keep_ages_unchanged) [private]
Definition at line 348 of file concurrent-marking.cc.
                                                                  {
  size_t kBytesUntilInterruptCheck = 64 * KB;
  int kObjectsUntilInterruptCheck = 1000;
  uint8_t task_id = delegate->GetTaskId() + 1;
  TaskState* task_state = task_state_[task_id].get();
  auto* cpp_heap = CppHeap::From(heap_->cpp_heap());
  MarkingWorklists::Local local_marking_worklists(
      marking_worklists_, cpp_heap
                              ? cpp_heap->CreateCppMarkingState()
                              : MarkingWorklists::Local::kNoCppMarkingState);
  WeakObjects::Local local_weak_objects(weak_objects_);
  ConcurrentMarkingVisitor visitor(
      &local_marking_worklists, &local_weak_objects, heap_, mark_compact_epoch,
      code_flush_mode, should_keep_ages_unchanged,
      heap_->tracer()->CodeFlushingIncrease(),
      &task_state->memory_chunk_live_bytes_map,
      &task_state->memory_chunk_typed_slots_map);
  NativeContextInferrer native_context_inferrer;
  NativeContextStats& native_context_stats = task_state->native_context_stats;
  double time_ms;
  size_t marked_bytes = 0;
  Isolate* isolate = heap_->isolate();
  if (v8_flags.trace_concurrent_marking) {
    isolate->PrintWithTimestamp("Starting major concurrent marking task %d\n",
                                task_id);
  }
  bool another_ephemeron_iteration = false;
  MainAllocator* const new_space_allocator =
      heap_->use_new_space() ? heap_->allocator()->new_space_allocator()
                             : nullptr;
  {
    TimedScope scope(&time_ms);
    {
      Ephemeron ephemeron;
      while (local_weak_objects.current_ephemerons_local.Pop(&ephemeron)) {
        if (visitor.ProcessEphemeron(ephemeron.key, ephemeron.value)) {
          another_ephemeron_iteration = true;
        }
      }
    }
    PtrComprCageBase cage_base(isolate);
    bool is_per_context_mode = local_marking_worklists.IsPerContextMode();
    bool done = false;
    while (!done) {
      size_t current_marked_bytes = 0;
      int objects_processed = 0;
      while (current_marked_bytes < kBytesUntilInterruptCheck &&
             objects_processed < kObjectsUntilInterruptCheck) {
        Tagged<HeapObject> object;
        if (!local_marking_worklists.Pop(&object)) {
          done = true;
          break;
        }
        DCHECK(!HeapLayout::InReadOnlySpace(object));
        DCHECK_EQ(HeapUtils::GetOwnerHeap(object), heap_);
        objects_processed++;
        Address new_space_top = kNullAddress;
        Address new_space_limit = kNullAddress;
        Address new_large_object = kNullAddress;
        if (new_space_allocator) {
          std::tie(new_space_top, new_space_limit) =
              new_space_allocator->GetOriginalTopAndLimit();
        }
        if (heap_->new_lo_space()) {
          new_large_object = heap_->new_lo_space()->pending_object();
        }
        Address addr = object.address();
        if ((new_space_top <= addr && addr < new_space_limit) ||
            addr == new_large_object) {
          local_marking_worklists.PushOnHold(object);
        } else {
          Tagged<Map> map = object->map(cage_base, kAcquireLoad);
          // The marking worklist should never contain filler objects.
          CHECK(!IsFreeSpaceOrFillerMap(map));
          if (is_per_context_mode) {
            Address context;
            if (native_context_inferrer.Infer(cage_base, map, object,
                                              &context)) {
              local_marking_worklists.SwitchToContext(context);
            }
          }
          const auto visited_size = visitor.Visit(map, object);
          visitor.IncrementLiveBytesCached(
              MutablePageMetadata::cast(
                  MemoryChunkMetadata::FromHeapObject(object)),
              ALIGN_TO_ALLOCATION_ALIGNMENT(visited_size));
          if (is_per_context_mode) {
            native_context_stats.IncrementSize(
                local_marking_worklists.Context(), map, object, visited_size);
          }
          current_marked_bytes += visited_size;
        }
      }
      if (objects_processed > 0) another_ephemeron_iteration = true;
      marked_bytes += current_marked_bytes;
      base::AsAtomicWord::Relaxed_Store<size_t>(&task_state->marked_bytes,
                                                marked_bytes);
      if (delegate->ShouldYield()) {
        TRACE_GC_NOTE("ConcurrentMarking::RunMajor Preempted");
        break;
      }
    }
    CHECK(local_weak_objects.current_ephemerons_local.IsLocalEmpty());
    local_marking_worklists.Publish();
    local_weak_objects.Publish();
    base::AsAtomicWord::Relaxed_Store<size_t>(&task_state->marked_bytes, 0);
    total_marked_bytes_ += marked_bytes;
    if (another_ephemeron_iteration) {
      set_another_ephemeron_iteration(true);
    }
  }
  if (v8_flags.trace_concurrent_marking) {
    heap_->isolate()->PrintWithTimestamp(
        "Major task %d concurrently marked %dKB in %.2fms\n", task_id,
        static_cast<int>(marked_bytes / KB), time_ms);
  }
  DCHECK(task_state->local_pretenuring_feedback.empty());
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::Heap::allocator(), another_ephemeron_iteration(), v8::internal::MutablePageMetadata::cast(), CHECK, v8::internal::GCTracer::CodeFlushingIncrease(), v8::internal::Heap::cpp_heap(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::CppHeap::From(), v8::internal::MemoryChunkMetadata::FromHeapObject(), v8::internal::MainAllocator::GetOriginalTopAndLimit(), v8::internal::HeapUtils::GetOwnerHeap(), v8::JobDelegate::GetTaskId(), heap_, v8::internal::ConcurrentMarkingVisitor::IncrementLiveBytesCached(), v8::internal::NativeContextStats::IncrementSize(), v8::internal::NativeContextInferrer::Infer(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::Heap::isolate(), v8::kAcquireLoad, v8::internal::KB, v8::internal::Ephemeron::key, v8::internal::kNullAddress, v8::internal::MarkingWorklists::Local(), v8::internal::ConcurrentMarking::TaskState::local_pretenuring_feedback, v8::internal::ConcurrentMarking::TaskState::marked_bytes, marking_worklists_, v8::internal::ConcurrentMarking::TaskState::memory_chunk_live_bytes_map, v8::internal::ConcurrentMarking::TaskState::memory_chunk_typed_slots_map, v8::internal::ConcurrentMarking::TaskState::native_context_stats, v8::internal::Heap::new_lo_space(), v8::internal::HeapAllocator::new_space_allocator(), v8::internal::LargeObjectSpace::pending_object(), v8::internal::ConcurrentMarkingVisitor::ProcessEphemeron(), v8::internal::WeakObjects::Local::Publish(), set_another_ephemeron_iteration(), v8::JobDelegate::ShouldYield(), task_state_, total_marked_bytes_, TRACE_GC_NOTE, v8::internal::Heap::tracer(), v8::internal::Heap::use_new_space(), v8::internal::v8_flags, v8::internal::Ephemeron::value, v8::internal::HeapVisitor< ConcreteVisitor >::Visit(), and weak_objects_.
Referenced by v8::internal::ConcurrentMarking::JobTaskMajor::Run().
RunMinor()
void v8::internal::ConcurrentMarking::RunMinor (JobDelegate * delegate) [private]
Definition at line 578 of file concurrent-marking.cc.
                                                      {
  DCHECK(heap_->use_new_space());
  DCHECK_NOT_NULL(heap_->new_lo_space());
  uint8_t task_id = delegate->GetTaskId() + 1;
  DCHECK_LT(task_id, task_state_.size());
  TaskState* task_state = task_state_[task_id].get();
  double time_ms;
  size_t marked_bytes = 0;
  Isolate* isolate = heap_->isolate();
  if (v8_flags.trace_concurrent_marking) {
    isolate->PrintWithTimestamp("Starting minor concurrent marking task %d\n",
                                task_id);
  }
  {
    TimedScope scope(&time_ms);
    if (heap_->minor_mark_sweep_collector()->is_in_atomic_pause()) {
      // This gets a lower bound for estimated concurrency as we may have marked
      // most of the graph concurrently already and may not be using parallism
      // as much.
      estimate_concurrency_.fetch_add(1, std::memory_order_relaxed);
      marked_bytes =
          RunMinorImpl<YoungGenerationMarkingVisitationMode::kParallel>(
              delegate, task_state);
    } else {
      marked_bytes =
          RunMinorImpl<YoungGenerationMarkingVisitationMode::kConcurrent>(
              delegate, task_state);
    }
  }
  if (v8_flags.trace_concurrent_marking) {
    heap_->isolate()->PrintWithTimestamp(
        "Minor task %d concurrently marked %dKB in %.2fms\n", task_id,
        static_cast<int>(marked_bytes / KB), time_ms);
  }
}
References v8::internal::DCHECK(), DCHECK_LT, DCHECK_NOT_NULL, estimate_concurrency_, v8::JobDelegate::GetTaskId(), heap_, v8::internal::MinorMarkSweepCollector::is_in_atomic_pause(), v8::internal::Heap::isolate(), v8::internal::KB, v8::internal::Heap::minor_mark_sweep_collector(), v8::internal::Heap::new_lo_space(), task_state_, v8::internal::Heap::use_new_space(), and v8::internal::v8_flags.
Referenced by v8::internal::ConcurrentMarking::JobTaskMinor::Run().
RunMinorImpl()
template<YoungGenerationMarkingVisitationMode marking_mode>
size_t v8::internal::ConcurrentMarking::RunMinorImpl (JobDelegate * delegate, TaskState * task_state) [inline], [private]
Definition at line 517 of file concurrent-marking.cc.
                                                                        {
  static constexpr size_t kBytesUntilInterruptCheck = 64 * KB;
  static constexpr int kObjectsUntilInterruptCheck = 1000;
  size_t marked_bytes = 0;
  size_t current_marked_bytes = 0;
  int objects_processed = 0;
  YoungGenerationMarkingVisitor<marking_mode> visitor(
      heap_, &task_state->local_pretenuring_feedback);
  YoungGenerationRememberedSetsMarkingWorklist::Local remembered_sets(
      heap_->minor_mark_sweep_collector()->remembered_sets_marking_handler());
  auto& marking_worklists_local = visitor.marking_worklists_local();
  Isolate* isolate = heap_->isolate();
  minor_marking_state_->MarkerStarted();
  MainAllocator* const new_space_allocator =
      heap_->allocator()->new_space_allocator();
  NewLargeObjectSpace* const new_lo_space = heap_->new_lo_space();
  do {
    if (delegate->IsJoiningThread()) {
      marking_worklists_local.MergeOnHold();
    }
    Tagged<HeapObject> heap_object;
    TRACE_GC_EPOCH(heap_->tracer(),
                   GCTracer::Scope::MINOR_MS_BACKGROUND_MARKING_CLOSURE,
                   ThreadKind::kBackground);
    while (marking_worklists_local.Pop(&heap_object)) {
      if (IsYoungObjectInLab(new_space_allocator, new_lo_space, heap_object)) {
        visitor.marking_worklists_local().PushOnHold(heap_object);
      } else {
        Tagged<Map> map = heap_object->map(isolate);
        const auto visited_size = visitor.Visit(map, heap_object);
        if (visited_size) {
          current_marked_bytes += visited_size;
          visitor.IncrementLiveBytesCached(
              MutablePageMetadata::FromHeapObject(heap_object),
              ALIGN_TO_ALLOCATION_ALIGNMENT(visited_size));
        }
      }
      if (current_marked_bytes >= kBytesUntilInterruptCheck ||
          ++objects_processed >= kObjectsUntilInterruptCheck) {
        marked_bytes += current_marked_bytes;
        if (delegate->ShouldYield()) {
          TRACE_GC_NOTE("ConcurrentMarking::RunMinor Preempted");
          minor_marking_state_->MarkerDone();
          return marked_bytes;
        }
        objects_processed = 0;
        current_marked_bytes = 0;
      }
    }
  } while (remembered_sets.ProcessNextItem(&visitor));
  if (minor_marking_state_->MarkerDone()) {
    // This is the last active marker and it ran out of work. Request GC
    // finalization.
    heap_->minor_mark_sweep_collector()->RequestGC();
  }
  return marked_bytes + current_marked_bytes;
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::Heap::allocator(), v8::internal::MutablePageMetadata::FromHeapObject(), heap_, v8::internal::YoungGenerationMarkingVisitor< marking_mode >::IncrementLiveBytesCached(), v8::JobDelegate::IsJoiningThread(), v8::internal::Heap::isolate(), v8::internal::anonymous_namespace{concurrent-marking.cc}::IsYoungObjectInLab(), v8::internal::KB, v8::internal::kBackground, v8::internal::ConcurrentMarking::TaskState::local_pretenuring_feedback, v8::internal::YoungGenerationMarkingVisitor< marking_mode >::marking_worklists_local(), v8::internal::Heap::minor_mark_sweep_collector(), minor_marking_state_, v8::internal::Heap::new_lo_space(), v8::internal::HeapAllocator::new_space_allocator(), v8::internal::YoungGenerationRememberedSetsMarkingWorklist::Local::ProcessNextItem(), v8::internal::MinorMarkSweepCollector::remembered_sets_marking_handler(), v8::internal::MinorMarkSweepCollector::RequestGC(), v8::JobDelegate::ShouldYield(), TRACE_GC_EPOCH, TRACE_GC_NOTE, v8::internal::Heap::tracer(), and v8::internal::HeapVisitor< ConcreteVisitor >::Visit().
set_another_ephemeron_iteration()
void v8::internal::ConcurrentMarking::set_another_ephemeron_iteration (bool another_ephemeron_iteration) [inline]
Definition at line 74 of file concurrent-marking.h.
                                                                         {
    another_ephemeron_iteration_.store(another_ephemeron_iteration);
  }
Referenced by RunMajor().
TotalMarkedBytes()
size_t v8::internal::ConcurrentMarking::TotalMarkedBytes ()
Definition at line 867 of file concurrent-marking.cc.
                                           {
  size_t result = 0;
  for (size_t i = 1; i < task_state_.size(); i++) {
    result +=
        base::AsAtomicWord::Relaxed_Load<size_t>(&task_state_[i]->marked_bytes);
  }
  result += total_marked_bytes_;
  return result;
}
References v8::base::internal::result, task_state_, and total_marked_bytes_.
Referenced by v8::internal::IncrementalMarking::FetchBytesMarkedConcurrently().
TryScheduleJob()
void v8::internal::ConcurrentMarking::TryScheduleJob (GarbageCollector garbage_collector, TaskPriority priority = TaskPriority::kUserVisible)
Definition at line 647 of file concurrent-marking.cc.
                                                              {
  DCHECK(v8_flags.parallel_marking || v8_flags.concurrent_marking ||
         v8_flags.concurrent_minor_ms_marking);
  DCHECK(!heap_->IsTearingDown());
  DCHECK(IsStopped());
  DCHECK_NE(garbage_collector, GarbageCollector::SCAVENGER);
  if (garbage_collector == GarbageCollector::MARK_COMPACTOR &&
      !heap_->mark_compact_collector()->UseBackgroundThreadsInCycle()) {
    return;
  }
  if (garbage_collector == GarbageCollector::MINOR_MARK_SWEEPER &&
      !heap_->minor_mark_sweep_collector()->UseBackgroundThreadsInCycle()) {
    return;
  }
  if (v8_flags.concurrent_marking_high_priority_threads) {
    priority = TaskPriority::kUserBlocking;
  }
#if DEBUG
  if (garbage_collector_.has_value()) {
    // Concurrent marking resumes. In this case the used collectors need to
    // match.
    DCHECK_EQ(*garbage_collector_, garbage_collector);
  } else {
    // If a new concurrent marking cycle starts, TaskState should not contain
    // any data.
    for (auto& task_state : task_state_) {
      task_state->memory_chunk_live_bytes_map.AssertEmpty();
      DCHECK(task_state->memory_chunk_typed_slots_map.empty());
      DCHECK(task_state->native_context_stats.Empty());
      DCHECK(task_state->local_pretenuring_feedback.empty());
      DCHECK_EQ(0, task_state->marked_bytes);
    }
    DCHECK_EQ(0, total_marked_bytes_.load());
  }
  if (garbage_collector == GarbageCollector::MARK_COMPACTOR) {
    // The full GC never makes use of local_pretenuring_feedback. It needs to be
    // empty even if resuming concurrent marking.
    for (auto& task_state : task_state_) {
      DCHECK(task_state->local_pretenuring_feedback.empty());
    }
  }
  if (minor_marking_state_) {
    // Minor marking state can only be alive if the concurrent marker was
    // previously paused.
    DCHECK(garbage_collector_.has_value());
    DCHECK_EQ(*garbage_collector_, GarbageCollector::MINOR_MARK_SWEEPER);
    DCHECK_EQ(garbage_collector, GarbageCollector::MINOR_MARK_SWEEPER);
  }
#endif // DEBUG
  garbage_collector_ = garbage_collector;
  if (garbage_collector == GarbageCollector::MARK_COMPACTOR) {
    heap_->mark_compact_collector()->local_marking_worklists()->Publish();
    marking_worklists_ = heap_->mark_compact_collector()->marking_worklists();
    auto job = std::make_unique<JobTaskMajor>(
        this, heap_->mark_compact_collector()->epoch(),
        heap_->mark_compact_collector()->code_flush_mode(),
        heap_->ShouldCurrentGCKeepAgesUnchanged());
    current_job_trace_id_.emplace(job->trace_id());
    TRACE_GC_NOTE_WITH_FLOW("Major concurrent marking started", job->trace_id(),
                            TRACE_EVENT_FLAG_FLOW_OUT);
    job_handle_ = V8::GetCurrentPlatform()->PostJob(priority, std::move(job));
  } else {
    DCHECK(garbage_collector == GarbageCollector::MINOR_MARK_SWEEPER);
    minor_marking_state_ = std::make_unique<MinorMarkingState>();
    heap_->minor_mark_sweep_collector()->local_marking_worklists()->Publish();
    marking_worklists_ =
        heap_->minor_mark_sweep_collector()->marking_worklists();
    auto job = std::make_unique<JobTaskMinor>(this);
    current_job_trace_id_.emplace(job->trace_id());
    TRACE_GC_NOTE_WITH_FLOW("Minor concurrent marking started", job->trace_id(),
                            TRACE_EVENT_FLAG_FLOW_OUT);
    job_handle_ = V8::GetCurrentPlatform()->PostJob(priority, std::move(job));
  }
  DCHECK(job_handle_->IsValid());
}
References v8::internal::MarkCompactCollector::code_flush_mode(), current_job_trace_id_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::MarkCompactCollector::epoch(), garbage_collector(), garbage_collector_, v8::internal::V8::GetCurrentPlatform(), heap_, IsStopped(), v8::internal::Heap::IsTearingDown(), job_handle_, v8::kUserBlocking, v8::internal::MinorMarkSweepCollector::local_marking_worklists(), v8::internal::MarkCompactCollector::local_marking_worklists(), v8::internal::Heap::mark_compact_collector(), v8::internal::MARK_COMPACTOR, v8::internal::MarkCompactCollector::marking_worklists(), v8::internal::MinorMarkSweepCollector::marking_worklists(), marking_worklists_, v8::internal::Heap::minor_mark_sweep_collector(), v8::internal::MINOR_MARK_SWEEPER, minor_marking_state_, v8::Platform::PostJob(), v8::internal::SCAVENGER, v8::internal::Heap::ShouldCurrentGCKeepAgesUnchanged(), task_state_, total_marked_bytes_, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_NOTE_WITH_FLOW, v8::internal::MarkCompactCollector::UseBackgroundThreadsInCycle(), v8::internal::MinorMarkSweepCollector::UseBackgroundThreadsInCycle(), and v8::internal::v8_flags.
Referenced by RescheduleJobIfNeeded(), v8::internal::IncrementalMarking::StartMarkingMajor(), and v8::internal::IncrementalMarking::StartMarkingMinor().
Friends And Related Function Documentation
Heap
friend class Heap [friend]
Definition at line 122 of file concurrent-marking.h.
Member Data Documentation
another_ephemeron_iteration_
std::atomic<bool> v8::internal::ConcurrentMarking::another_ephemeron_iteration_ {false} [private]
Definition at line 117 of file concurrent-marking.h.
current_job_trace_id_
std::optional<uint64_t> v8::internal::ConcurrentMarking::current_job_trace_id_ [private]
Definition at line 118 of file concurrent-marking.h.
Referenced by Join(), Pause(), RescheduleJobIfNeeded(), Resume(), and TryScheduleJob().
estimate_concurrency_
std::atomic<size_t> v8::internal::ConcurrentMarking::estimate_concurrency_ {0} [private]
Definition at line 120 of file concurrent-marking.h.
Referenced by RunMinor().
garbage_collector_
std::optional<GarbageCollector> v8::internal::ConcurrentMarking::garbage_collector_ [private]
Definition at line 112 of file concurrent-marking.h.
Referenced by IsWorkLeft(), Join(), Pause(), RescheduleJobIfNeeded(), Resume(), and TryScheduleJob().
heap_
Heap* const v8::internal::ConcurrentMarking::heap_ [private]
Definition at line 111 of file concurrent-marking.h.
Referenced by FlushPretenuringFeedback(), GetMajorMaxConcurrency(), GetMinorMaxConcurrency(), IsWorkLeft(), Join(), RescheduleJobIfNeeded(), v8::internal::ConcurrentMarking::JobTaskMajor::Run(), v8::internal::ConcurrentMarking::JobTaskMinor::Run(), RunMajor(), RunMinor(), RunMinorImpl(), and TryScheduleJob().
job_handle_
std::unique_ptr<JobHandle> v8::internal::ConcurrentMarking::job_handle_ [private]
Definition at line 110 of file concurrent-marking.h.
Referenced by FlushMemoryChunkData(), FlushNativeContexts(), IsStopped(), Join(), JoinJobForTesting(), Pause(), RescheduleJobIfNeeded(), and TryScheduleJob().
marking_worklists_
MarkingWorklists* v8::internal::ConcurrentMarking::marking_worklists_ [private]
Definition at line 113 of file concurrent-marking.h.
Referenced by GetMajorMaxConcurrency(), GetMinorMaxConcurrency(), IsWorkLeft(), RunMajor(), and TryScheduleJob().
minor_marking_state_
std::unique_ptr<MinorMarkingState> v8::internal::ConcurrentMarking::minor_marking_state_ [private]
Definition at line 119 of file concurrent-marking.h.
Referenced by Join(), RunMinorImpl(), and TryScheduleJob().
task_state_
std::vector<std::unique_ptr<TaskState> > v8::internal::ConcurrentMarking::task_state_ [private]
Definition at line 115 of file concurrent-marking.h.
Referenced by ConcurrentMarking(), FlushMemoryChunkData(), FlushNativeContexts(), FlushPretenuringFeedback(), GetMajorMaxConcurrency(), GetMinorMaxConcurrency(), RunMajor(), RunMinor(), TotalMarkedBytes(), and TryScheduleJob().
total_marked_bytes_
std::atomic<size_t> v8::internal::ConcurrentMarking::total_marked_bytes_ {0} [private]
Definition at line 116 of file concurrent-marking.h.
Referenced by FlushMemoryChunkData(), RunMajor(), TotalMarkedBytes(), and TryScheduleJob().
weak_objects_
WeakObjects* const v8::internal::ConcurrentMarking::weak_objects_ [private]
Definition at line 114 of file concurrent-marking.h.
Referenced by GetMajorMaxConcurrency(), IsWorkLeft(), and RunMajor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/concurrent-marking.h
/mnt/V8SourceCode/src/heap/concurrent-marking.cc