v8::internal::FunctionCallbackArguments Class Reference
#include <api-arguments.h>
Public Types
using T = FunctionCallbackInfo< Value >
using Super = CustomArguments< T >
Public Member Functions
FunctionCallbackArguments (Isolate *isolate, Tagged< FunctionTemplateInfo > target, Tagged< HeapObject > new_target, Address *argv, int argc)
DirectHandle< Object > CallOrConstruct (Tagged< FunctionTemplateInfo > function, bool is_construct)
Static Public Member Functions
template<typename T >
static Tagged< Object > GetTarget (const FunctionCallbackInfo< T > &info)
Static Public Attributes
static constexpr int kArgsLength = T::kArgsLength
static constexpr int kArgsLengthWithReceiver = T::kArgsLengthWithReceiver
static constexpr int kUnusedIndex = T::kUnusedIndex
static constexpr int kIsolateIndex = T::kIsolateIndex
static constexpr int kContextIndex = T::kContextIndex
static constexpr int kTargetIndex = T::kTargetIndex
static constexpr int kNewTargetIndex = T::kNewTargetIndex
static constexpr int kSize = T::kSize
static constexpr int kImplicitArgsOffset = T::kImplicitArgsOffset
static constexpr int kValuesOffset = T::kValuesOffset
static constexpr int kLengthOffset = T::kLengthOffset
Private Attributes
Address * argv_
int const argc_
Additional Inherited Members
Detailed Description
Definition at line 254 of file api-arguments.h.
Member Typedef Documentation
Super
using v8::internal::FunctionCallbackArguments::Super = CustomArguments<T>
Definition at line 258 of file api-arguments.h.
T
using v8::internal::FunctionCallbackArguments::T = FunctionCallbackInfo<Value>
Definition at line 257 of file api-arguments.h.
Constructor & Destructor Documentation
FunctionCallbackArguments()
v8::internal::FunctionCallbackArguments::FunctionCallbackArguments (Isolate * isolate, Tagged< FunctionTemplateInfo > target, Tagged< HeapObject > new_target, Address * argv, int argc)
Definition at line 43 of file api-arguments.cc.
    : Super(isolate), argv_(argv), argc_(argc) {
  slot_at(T::kTargetIndex).store(target);
  slot_at(T::kUnusedIndex).store(ReadOnlyRoots(isolate).undefined_value());
  slot_at(T::kNewTargetIndex).store(new_target);
  slot_at(T::kIsolateIndex)
      .store(Tagged<Object>(reinterpret_cast<Address>(isolate)));
  slot_at(T::kReturnValueIndex).store(ReadOnlyRoots(isolate).undefined_value());
  slot_at(T::kContextIndex).store(isolate->context());
  DCHECK(IsSmi(*slot_at(T::kIsolateIndex)));
}
References v8::internal::Isolate::context(), v8::internal::DCHECK(), v8::internal::CustomArguments< FunctionCallbackInfo< Value > >::isolate(), v8::internal::IsSmi(), v8::FunctionCallbackInfo< T >::kContextIndex, v8::FunctionCallbackInfo< T >::kIsolateIndex, v8::FunctionCallbackInfo< T >::kNewTargetIndex, v8::FunctionCallbackInfo< T >::kReturnValueIndex, v8::FunctionCallbackInfo< T >::kTargetIndex, v8::FunctionCallbackInfo< T >::kUnusedIndex, v8::internal::CustomArguments< FunctionCallbackInfo< Value > >::slot_at(), and v8::internal::FullObjectSlot::store().
Member Function Documentation
CallOrConstruct()
DirectHandle< Object > v8::internal::FunctionCallbackArguments::CallOrConstruct (Tagged< FunctionTemplateInfo > function, bool is_construct) [inline]
Definition at line 77 of file api-arguments-inl.h.
                                                              {
  Isolate* isolate = this->isolate();
  RCS_SCOPE(isolate, RuntimeCallCounterId::kFunctionCallback);
  v8::FunctionCallback f =
      reinterpret_cast<v8::FunctionCallback>(function->callback(isolate));
  if (isolate->should_check_side_effects() &&
      !isolate->debug()->PerformSideEffectCheckForCallback(
          handle(function, isolate))) {
    return {};
  }
  FunctionCallbackInfo<v8::Value> info(values_, argv_, argc_);
  ExternalCallbackScope call_scope(isolate, FUNCTION_ADDR(f),
                                   is_construct ? ExceptionContext::kConstructor
                                                : ExceptionContext::kOperation,
                                   &info);
  f(info);
  return GetReturnValue<Object>(isolate);
}
References argc_, argv_, v8::internal::Isolate::debug(), FUNCTION_ADDR, v8::internal::handle(), v8::internal::CustomArguments< FunctionCallbackInfo< Value > >::isolate(), v8::kConstructor, v8::kOperation, v8::internal::Debug::PerformSideEffectCheckForCallback(), RCS_SCOPE, v8::internal::Isolate::should_check_side_effects(), and v8::internal::CustomArguments< FunctionCallbackInfo< Value > >::values_.
Referenced by v8::internal::HandleApiCallAsFunctionOrConstructorDelegate(), and v8::internal::anonymous_namespace{builtins-api.cc}::HandleApiCallHelper().
GetTarget()
template<typename T >
static Tagged<Object> v8::internal::FunctionCallbackArguments::GetTarget (const FunctionCallbackInfo< T > & info) [inline], [static]
Definition at line 300 of file api-arguments.h.
                                                                       {
    return Tagged<Object>(info.implicit_args_[kTargetIndex]);
  }
References v8::FunctionCallbackInfo< T >::implicit_args_, kTargetIndex, and v8::internal::Tagged< Object >.
Referenced by v8::internal::anonymous_namespace{api.cc}::GetTargetFunctionTemplateInfo(), and v8::internal::anonymous_namespace{isolate.cc}::GetTargetFunctionTemplateInfo().
Member Data Documentation
argc_
int const v8::internal::FunctionCallbackArguments::argc_ [private]
Definition at line 306 of file api-arguments.h.
Referenced by CallOrConstruct().
argv_
Address* v8::internal::FunctionCallbackArguments::argv_ [private]
Definition at line 305 of file api-arguments.h.
Referenced by CallOrConstruct().
kArgsLength
constexpr int v8::internal::FunctionCallbackArguments::kArgsLength = T::kArgsLength [static], [constexpr]
Definition at line 259 of file api-arguments.h.
kArgsLengthWithReceiver
constexpr int v8::internal::FunctionCallbackArguments::kArgsLengthWithReceiver = T::kArgsLengthWithReceiver [static], [constexpr]
Definition at line 260 of file api-arguments.h.
kContextIndex
constexpr int v8::internal::FunctionCallbackArguments::kContextIndex = T::kContextIndex [static], [constexpr]
Definition at line 264 of file api-arguments.h.
kImplicitArgsOffset
constexpr int v8::internal::FunctionCallbackArguments::kImplicitArgsOffset = T::kImplicitArgsOffset [static], [constexpr]
Definition at line 271 of file api-arguments.h.
kIsolateIndex
constexpr int v8::internal::FunctionCallbackArguments::kIsolateIndex = T::kIsolateIndex [static], [constexpr]
Definition at line 263 of file api-arguments.h.
kLengthOffset
constexpr int v8::internal::FunctionCallbackArguments::kLengthOffset = T::kLengthOffset [static], [constexpr]
Definition at line 273 of file api-arguments.h.
kNewTargetIndex
constexpr int v8::internal::FunctionCallbackArguments::kNewTargetIndex = T::kNewTargetIndex [static], [constexpr]
Definition at line 266 of file api-arguments.h.
kSize
constexpr int v8::internal::FunctionCallbackArguments::kSize = T::kSize [static], [constexpr]
Definition at line 270 of file api-arguments.h.
kTargetIndex
constexpr int v8::internal::FunctionCallbackArguments::kTargetIndex = T::kTargetIndex [static], [constexpr]
Definition at line 265 of file api-arguments.h.
Referenced by GetTarget().
kUnusedIndex
constexpr int v8::internal::FunctionCallbackArguments::kUnusedIndex = T::kUnusedIndex [static], [constexpr]
Definition at line 262 of file api-arguments.h.
kValuesOffset
constexpr int v8::internal::FunctionCallbackArguments::kValuesOffset = T::kValuesOffset [static], [constexpr]
Definition at line 272 of file api-arguments.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/api/api-arguments.h
/mnt/V8SourceCode/src/api/api-arguments-inl.h
/mnt/V8SourceCode/src/api/api-arguments.cc