v8::internal::tracing::TraceEventHelper Class Reference
#include <trace-event.h>
Static Public Member Functions
static V8_EXPORT_PRIVATE v8::TracingController * GetTracingController ()
Detailed Description
Definition at line 312 of file trace-event.h.
Member Function Documentation
GetTracingController()
v8::TracingController * v8::internal::tracing::TraceEventHelper::GetTracingController () [static]
Definition at line 19 of file trace-event.cc.
                                                            {
  return v8::internal::V8::GetCurrentPlatform()->GetTracingController();
}
References v8::internal::V8::GetCurrentPlatform(), and v8::Platform::GetTracingController().
Referenced by v8::internal::tracing::AddTraceEventImpl(), and v8::internal::tracing::AddTraceEventWithTimestampImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/tracing/trace-event.h
/mnt/V8SourceCode/src/tracing/trace-event.cc