v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor Class Reference
Public Member Functions
DiscardBaselineCodeVisitor (Tagged< SharedFunctionInfo > shared)
DiscardBaselineCodeVisitor ()
void VisitThread (Isolate *isolate, ThreadLocalTop *top) override
Private Attributes
Tagged< SharedFunctionInfo > shared_
Additional Inherited Members
Detailed Description
Definition at line 1693 of file debug.cc.
Constructor & Destructor Documentation
DiscardBaselineCodeVisitor() [1/2]
v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::DiscardBaselineCodeVisitor (Tagged< SharedFunctionInfo > shared) [inline], [explicit]
Definition at line 1695 of file debug.cc.
      : shared_(shared) {}
DiscardBaselineCodeVisitor() [2/2]
v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::DiscardBaselineCodeVisitor () [inline]
Definition at line 1697 of file debug.cc.
: shared_(SharedFunctionInfo()) {}
Member Function Documentation
VisitThread()
void v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::VisitThread (Isolate * isolate, ThreadLocalTop * top) [inline], [override], [virtual]
Implements v8::internal::ThreadVisitor.
Definition at line 1699 of file debug.cc.
                                                                   {
    DisallowGarbageCollection diallow_gc;
    bool deopt_all = shared_ == SharedFunctionInfo();
    for (JavaScriptStackFrameIterator it(isolate, top); !it.done();
         it.Advance()) {
      if (!deopt_all && it.frame()->function()->shared() != shared_) continue;
      if (it.frame()->type() != StackFrame::BASELINE &&
          it.frame()->type() != StackFrame::INTERPRETED) {
        continue;
      }
      Tagged<Code> code = it.frame()->LookupCode();
      // We need to check CodeKind rather than StackFrame type here since
      // previous iterations might already patched this baseline code,
      // but we need to update remaining baseline stack frames as well.
      if (code->kind() == CodeKind::BASELINE) {
        UnoptimizedJSFrame* frame = UnoptimizedJSFrame::cast(it.frame());
        int bytecode_offset = code->GetBytecodeOffsetForBaselinePC(
            frame->pc(), frame->GetBytecodeArray());
        Address* pc_addr = frame->pc_address();
        Address advance;
        if (bytecode_offset == kFunctionEntryBytecodeOffset) {
          advance = BUILTIN_CODE(isolate, BaselineOutOfLinePrologueDeopt)
                        ->instruction_start();
        } else {
          advance = BUILTIN_CODE(isolate, InterpreterEnterAtNextBytecode)
                        ->instruction_start();
        }
        if (v8_flags.cet_compatible) {
          Deoptimizer::PatchToJump(*pc_addr, advance);
          frame->LookupCode()->SetMarkedForDeoptimization(
              isolate, LazyDeoptimizeReason::kDebugger);
        } else {
          PointerAuthentication::ReplacePC(pc_addr, advance,
                                           kSystemPointerSize);
        }
        InterpretedFrame::cast(it.Reframe())
            ->PatchBytecodeOffset(bytecode_offset);
      }
    }
  }
References BUILTIN_CODE, v8::internal::UnoptimizedJSFrame::cast(), v8::internal::InterpretedFrame::cast(), code, v8::internal::JavaScriptStackFrameIterator::done(), v8::internal::UnoptimizedJSFrame::GetBytecodeArray(), v8::internal::kFunctionEntryBytecodeOffset, v8::internal::kSystemPointerSize, v8::internal::StackFrame::LookupCode(), v8::internal::InterpretedFrame::PatchBytecodeOffset(), v8::internal::Deoptimizer::PatchToJump(), v8::internal::StackFrame::pc(), v8::internal::StackFrame::pc_address(), v8::internal::PointerAuthentication::ReplacePC(), and v8::internal::v8_flags.
Member Data Documentation
shared_
Tagged<SharedFunctionInfo> v8::internal::anonymous_namespace{debug.cc}::DiscardBaselineCodeVisitor::shared_ [private]
Definition at line 1742 of file debug.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/debug.cc