v8::internal::ExternalCallbackScope Class Reference
#include <vm-state.h>
Public Member Functions
ExternalCallbackScope (Isolate *isolate, Address callback, v8::ExceptionContext exception_context=v8::ExceptionContext::kUnknown, const void *callback_info=nullptr)
~ExternalCallbackScope ()
Address callback ()
Address * callback_entrypoint_address ()
ExternalCallbackScope * previous ()
Address JSStackComparableAddress ()
v8::ExceptionContext exception_context () const
const void * callback_info ()
Private Attributes
Address const callback_
const void *const callback_info_
ExternalCallbackScope *const previous_scope_
VMState< EXTERNAL > const vm_state_
v8::ExceptionContext exception_context_
PauseNestedTimedHistogramScope const pause_timed_histogram_scope_
Detailed Description
Definition at line 35 of file vm-state.h.
Constructor & Destructor Documentation
ExternalCallbackScope()
v8::internal::ExternalCallbackScope::ExternalCallbackScope (Isolate * isolate, Address callback, v8::ExceptionContext exception_context = v8::ExceptionContext::kUnknown, const void * callback_info = nullptr) [inline]
Definition at line 58 of file vm-state-inl.h.
    : callback_(callback),
      callback_info_(callback_info),
      previous_scope_(isolate->external_callback_scope()),
      vm_state_(isolate),
      exception_context_(exception_context),
      pause_timed_histogram_scope_(isolate->counters()->execute()) {
#if USE_SIMULATOR || V8_USE_ADDRESS_SANITIZER || V8_USE_SAFE_STACK
  js_stack_comparable_address_ =
      i::SimulatorStack::RegisterJSStackComparableAddress(isolate);
#endif
  vm_state_.isolate_->set_external_callback_scope(this);
#ifdef V8_RUNTIME_CALL_STATS
  TRACE_EVENT_BEGIN0(TRACE_DISABLED_BY_DEFAULT("v8.runtime"),
                     "V8.ExternalCallback");
#endif
  // The external callback might be called via different code paths and on some
  // of them it's not guaranteed that the topmost_script_having_context value
  // is still valid (in particular, when the callback call is initiated by
  // embedder via V8 Api). So, clear it to ensure correctness of
  // Isolate::GetIncumbentContext().
  vm_state_.isolate_->clear_topmost_script_having_context();
}
References v8::internal::Isolate::clear_topmost_script_having_context(), v8::internal::VMState< Tag >::isolate_, v8::internal::SimulatorStack::RegisterJSStackComparableAddress(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_BEGIN0, and vm_state_.
 ExternalCallbackScope()
v8::internal::ExternalCallbackScope::~ExternalCallbackScope () [inline]
Definition at line 84 of file vm-state-inl.h.
                                              {
  vm_state_.isolate_->set_external_callback_scope(previous_scope_);
  // JS code might have been executed by the callback and it could have changed
  // {topmost_script_having_context}, clear it to ensure correctness of
  // Isolate::GetIncumbentContext() in case it'll be called after returning
  // from the callback.
  vm_state_.isolate_->clear_topmost_script_having_context();
#ifdef V8_RUNTIME_CALL_STATS
  TRACE_EVENT_END0(TRACE_DISABLED_BY_DEFAULT("v8.runtime"),
                   "V8.ExternalCallback");
#endif
#if USE_SIMULATOR || V8_USE_ADDRESS_SANITIZER || V8_USE_SAFE_STACK
  i::SimulatorStack::UnregisterJSStackComparableAddress(vm_state_.isolate_);
#endif
}
References v8::internal::Isolate::clear_topmost_script_having_context(), v8::internal::VMState< Tag >::isolate_, previous_scope_, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT_END0, v8::internal::SimulatorStack::UnregisterJSStackComparableAddress(), and vm_state_.
Member Function Documentation
callback()
Address v8::internal::ExternalCallbackScope::callback () [inline]
Definition at line 42 of file vm-state.h.
{ return callback_; }
callback_entrypoint_address()
Address* v8::internal::ExternalCallbackScope::callback_entrypoint_address () [inline]
Definition at line 43 of file vm-state.h.
                                         {
    if (callback_ == kNullAddress) return nullptr;
#if USES_FUNCTION_DESCRIPTORS
    return FUNCTION_ENTRYPOINT_ADDRESS(callback_);
#else
    return const_cast<Address*>(&callback_);
#endif
  }
References v8::internal::kNullAddress.
Referenced by v8::internal::StackFrameIteratorForProfiler::Advance(), and v8::internal::TickSample::GetStackSample().
callback_info()
const void* v8::internal::ExternalCallbackScope::callback_info () [inline]
Definition at line 55 of file vm-state.h.
{ return callback_info_; }
Referenced by v8::internal::Isolate::NotifyExceptionPropagationCallback().
exception_context()
v8::ExceptionContext v8::internal::ExternalCallbackScope::exception_context () const [inline]
Definition at line 54 of file vm-state.h.
{ return exception_context_; }
Referenced by v8::internal::Isolate::NotifyExceptionPropagationCallback().
JSStackComparableAddress()
Address v8::internal::ExternalCallbackScope::JSStackComparableAddress () [inline]
Definition at line 100 of file vm-state-inl.h.
                                                        {
#if USE_SIMULATOR || V8_USE_ADDRESS_SANITIZER || V8_USE_SAFE_STACK
  return js_stack_comparable_address_;
#else
  return reinterpret_cast<Address>(this);
#endif
}
Referenced by v8::internal::StackFrameIteratorForProfiler::Advance(), v8::internal::TickSample::GetStackSample(), and v8::internal::Isolate::NotifyExceptionPropagationCallback().
previous()
ExternalCallbackScope* v8::internal::ExternalCallbackScope::previous () [inline]
Definition at line 51 of file vm-state.h.
{ return previous_scope_; }
Referenced by v8::internal::StackFrameIteratorForProfiler::Advance().
Member Data Documentation
callback_
Address const v8::internal::ExternalCallbackScope::callback_ [private]
Definition at line 58 of file vm-state.h.
callback_info_
const void* const v8::internal::ExternalCallbackScope::callback_info_ [private]
Definition at line 60 of file vm-state.h.
exception_context_
v8::ExceptionContext v8::internal::ExternalCallbackScope::exception_context_ [private]
Definition at line 63 of file vm-state.h.
pause_timed_histogram_scope_
PauseNestedTimedHistogramScope const v8::internal::ExternalCallbackScope::pause_timed_histogram_scope_ [private]
Definition at line 64 of file vm-state.h.
previous_scope_
ExternalCallbackScope* const v8::internal::ExternalCallbackScope::previous_scope_ [private]
Definition at line 61 of file vm-state.h.
Referenced by ~ExternalCallbackScope().
vm_state_
VMState<EXTERNAL> const v8::internal::ExternalCallbackScope::vm_state_ [private]
Definition at line 62 of file vm-state.h.
Referenced by ExternalCallbackScope(), and ~ExternalCallbackScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/vm-state.h
/mnt/V8SourceCode/src/execution/vm-state-inl.h