v8::internal::BasicTracedReferenceExtractor Class Reference
#include <unified-heap-marking-state-inl.h>
Static Public Member Functions
static Address * GetObjectSlotForMarking (const TracedReferenceBase &ref)
Detailed Description
Definition at line 26 of file unified-heap-marking-state-inl.h.
Member Function Documentation
GetObjectSlotForMarking()
static Address* v8::internal::BasicTracedReferenceExtractor::GetObjectSlotForMarking (const TracedReferenceBase & ref) [inline], [static]
Definition at line 28 of file unified-heap-marking-state-inl.h.
                                                                          {
    return const_cast<Address*>(ref.GetSlotThreadSafe());
  }
References v8::TracedReferenceBase::GetSlotThreadSafe().
Referenced by v8::internal::UnifiedHeapMarkingState::MarkAndPush(), and v8::internal::UnifiedHeapVerificationState::VerifyMarkedTracedReference().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc-js/unified-heap-marking-state-inl.h