cppgc::internal::anonymous_namespace{sweeper.cc}::ObjectStartBitmapVerifier Class Reference
Public Member Functions
void Verify (RawHeap &heap)
void Verify (NormalPage &page)
Private Member Functions
bool VisitNormalPage (NormalPage &page)
bool VisitHeapObjectHeader (HeapObjectHeader &header)
Private Attributes
PlatformAwareObjectStartBitmap * bitmap_ = nullptr
HeapObjectHeader * prev_ = nullptr
Friends
class HeapVisitor< ObjectStartBitmapVerifier >
Detailed Description
Definition at line 72 of file sweeper.cc.
Member Function Documentation
Verify() [1/2]
void cppgc::internal::anonymous_namespace{sweeper.cc}::ObjectStartBitmapVerifier::Verify (NormalPage & page) [inline]
Definition at line 82 of file sweeper.cc.
                                {
#if DEBUG
    Traverse(page);
#endif // DEBUG
  }
Verify() [2/2]
void cppgc::internal::anonymous_namespace{sweeper.cc}::ObjectStartBitmapVerifier::Verify (RawHeap & heap) [inline]
Definition at line 77 of file sweeper.cc.
                             {
#if DEBUG
    Traverse(heap);
#endif // DEBUG
  }
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage(), and cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::VisitNormalPage().
VisitHeapObjectHeader()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::ObjectStartBitmapVerifier::VisitHeapObjectHeader (HeapObjectHeader & header) [inline], [private]
Definition at line 96 of file sweeper.cc.
                                                       {
    if (header.IsLargeObject()) return true;
    auto* raw_header = reinterpret_cast<ConstAddress>(&header);
    CHECK(bitmap_->CheckBit<AccessMode::kAtomic>(raw_header));
    if (prev_) {
      // No other bits in the range [prev_, raw_header) should be set.
      CHECK_EQ(prev_, bitmap_->FindHeader<AccessMode::kAtomic>(raw_header - 1));
    }
    prev_ = &header;
    return true;
  }
References CHECK, CHECK_EQ, cppgc::internal::HeapObjectHeader::IsLargeObject(), and cppgc::internal::kAtomic.
VisitNormalPage()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::ObjectStartBitmapVerifier::VisitNormalPage (NormalPage & page) [inline], [private]
Definition at line 89 of file sweeper.cc.
                                         {
    // Remember bitmap and reset previous pointer.
    bitmap_ = &page.object_start_bitmap();
    prev_ = nullptr;
    return false;
  }
References cppgc::internal::NormalPage::object_start_bitmap().
Friends And Related Function Documentation
HeapVisitor< ObjectStartBitmapVerifier >
friend class HeapVisitor< ObjectStartBitmapVerifier > [friend]
Definition at line 55 of file sweeper.cc.
Member Data Documentation
bitmap_
PlatformAwareObjectStartBitmap* cppgc::internal::anonymous_namespace{sweeper.cc}::ObjectStartBitmapVerifier::bitmap_ = nullptr [private]
Definition at line 109 of file sweeper.cc.
prev_
HeapObjectHeader* cppgc::internal::anonymous_namespace{sweeper.cc}::ObjectStartBitmapVerifier::prev_ = nullptr [private]
Definition at line 110 of file sweeper.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/sweeper.cc