v8::internal::ClassBoilerplate Class Reference
#include <literal-objects.h>
Classes
struct ComputedEntryFlags
Public Types
enum ValueKind { kData
, kGetter
, kSetter
, kAutoAccessor
 }
enum DefineClassArgumentsIndices { kConstructorArgumentIndex = 1
, kPrototypeArgumentIndex = 2
, kFirstDynamicArgumentIndex = 3
 }
using BodyDescriptor = StructBodyDescriptor
Public Member Functions
template<typename IsolateT , typename PropertyDict >
void AddToPropertiesTemplate (IsolateT *isolate, Handle< PropertyDict > dictionary, Handle< Name > name, int key_index, ClassBoilerplate::ValueKind value_kind, Tagged< Smi > value)
Static Public Member Functions
template<typename IsolateT >
static Handle< ClassBoilerplate > New (IsolateT *isolate, ClassLiteral *expr, AllocationType allocation=AllocationType::kYoung)
template<typename IsolateT , typename Dictionary >
static void AddToPropertiesTemplate (IsolateT *isolate, Handle< Dictionary > dictionary, Handle< Name > name, int key_index, ValueKind value_kind, Tagged< Smi > value)
template<typename IsolateT >
static void AddToElementsTemplate (IsolateT *isolate, Handle< NumberDictionary > dictionary, uint32_t key, int key_index, ValueKind value_kind, Tagged< Smi > value)
Static Public Attributes
static const int kMinimumClassPropertiesCount = 6
static const int kMinimumPrototypePropertiesCount = 1
Private Member Functions
OBJECT_CONSTRUCTORS (ClassBoilerplate, Struct)
Detailed Description
Definition at line 130 of file literal-objects.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::ClassBoilerplate::BodyDescriptor = StructBodyDescriptor
Definition at line 198 of file literal-objects.h.
Member Enumeration Documentation
DefineClassArgumentsIndices
enum v8::internal::ClassBoilerplate::DefineClassArgumentsIndices
Enumerator
kConstructorArgumentIndex
kPrototypeArgumentIndex
kFirstDynamicArgumentIndex
Definition at line 144 of file literal-objects.h.
                                   {
    kConstructorArgumentIndex = 1,
    kPrototypeArgumentIndex = 2,
    // The index of a first dynamic argument passed to Runtime::kDefineClass
    // function. The dynamic arguments are consist of method closures and
    // computed property names.
    kFirstDynamicArgumentIndex = 3,
  };
ValueKind
enum v8::internal::ClassBoilerplate::ValueKind
Enumerator
kData
kGetter
kSetter
kAutoAccessor
Definition at line 134 of file literal-objects.h.
{ kData, kGetter, kSetter, kAutoAccessor };
Member Function Documentation
AddToElementsTemplate()
template<typename IsolateT >
template void v8::internal::ClassBoilerplate::AddToElementsTemplate (IsolateT * isolate, Handle< NumberDictionary > dictionary, uint32_t key, int key_index, ValueKind value_kind, Tagged< Smi > value) [static]
Definition at line 665 of file literal-objects.cc.
                                                                            {
  AddToDictionaryTemplate(isolate, dictionary, key, key_index, value_kind,
                          value);
}
References v8::internal::anonymous_namespace{literal-objects.cc}::AddToDictionaryTemplate(), v8::internal::key, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate().
AddToPropertiesTemplate() [1/2]
template<typename IsolateT , typename Dictionary >
static void v8::internal::ClassBoilerplate::AddToPropertiesTemplate (IsolateT * isolate, Handle< Dictionary > dictionary, Handle< Name > name, int key_index, ValueKind value_kind, Tagged< Smi > value) [static]
Referenced by v8::internal::anonymous_namespace{runtime-classes.cc}::AddDescriptorsByTemplate().
AddToPropertiesTemplate() [2/2]
template<typename IsolateT , typename PropertyDict >
void v8::internal::ClassBoilerplate::AddToPropertiesTemplate (IsolateT * isolate, Handle< PropertyDict > dictionary, Handle< Name > name, int key_index, ClassBoilerplate::ValueKind value_kind, Tagged< Smi > value)
Definition at line 648 of file literal-objects.cc.
                                                                            {
  AddToDictionaryTemplate(isolate, dictionary, name, key_index, value_kind,
                          value);
}
References v8::internal::anonymous_namespace{literal-objects.cc}::AddToDictionaryTemplate(), v8::internal::name, and v8::internal::value.
New()
template<typename IsolateT >
template Handle< ClassBoilerplate > v8::internal::ClassBoilerplate::New (IsolateT * isolate, ClassLiteral * expr, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 680 of file literal-objects.cc.
                                                                          {
  // Create a non-caching handle scope to ensure that the temporary handle used
  // by ObjectDescriptor for passing Smis around does not corrupt handle cache
  // in CanonicalHandleScope.
  typename IsolateT::HandleScopeType scope(isolate);
  auto* factory = isolate->factory();
  ObjectDescriptor<IsolateT> static_desc(kMinimumClassPropertiesCount);
  ObjectDescriptor<IsolateT> instance_desc(kMinimumPrototypePropertiesCount);
  for (int i = 0; i < expr->public_members()->length(); i++) {
    ClassLiteral::Property* property = expr->public_members()->at(i);
    ObjectDescriptor<IsolateT>& desc =
        property->is_static() ? static_desc : instance_desc;
    if (property->is_computed_name()) {
      if (property->kind() != ClassLiteral::Property::FIELD) {
        desc.IncComputedCount();
      }
    } else {
      if (property->key()->AsLiteral()->IsPropertyName()) {
        desc.IncPropertiesCount();
      } else {
        desc.IncElementsCount();
      }
    }
  }
  //
  // Initialize class object template.
  //
  static_desc.CreateTemplates(isolate);
  static_assert(JSFunction::kLengthDescriptorIndex == 0);
  {
    // Add length_accessor.
    PropertyAttributes attribs =
        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY);
    static_desc.AddConstant(isolate, factory->length_string(),
                            factory->function_length_accessor(), attribs);
  }
  {
    // Add name_accessor.
    // All classes, even anonymous ones, have a name accessor.
    PropertyAttributes attribs =
        static_cast<PropertyAttributes>(DONT_ENUM | READ_ONLY);
    static_desc.AddConstant(isolate, factory->name_string(),
                            factory->function_name_accessor(), attribs);
  }
  {
    // Add prototype_accessor.
    PropertyAttributes attribs =
        static_cast<PropertyAttributes>(DONT_ENUM | DONT_DELETE | READ_ONLY);
    static_desc.AddConstant(isolate, factory->prototype_string(),
                            factory->function_prototype_accessor(), attribs);
  }
  {
    DirectHandle<ClassPositions> class_positions = factory->NewClassPositions(
        expr->start_position(), expr->end_position());
    static_desc.AddConstant(isolate, factory->class_positions_symbol(),
                            class_positions, DONT_ENUM);
  }
  //
  // Initialize prototype object template.
  //
  instance_desc.CreateTemplates(isolate);
  {
    DirectHandle<Object> value(
        Smi::FromInt(ClassBoilerplate::kConstructorArgumentIndex), isolate);
    instance_desc.AddConstant(isolate, factory->constructor_string(), value,
                              DONT_ENUM);
  }
  //
  // Fill in class boilerplate.
  //
  int dynamic_argument_index = ClassBoilerplate::kFirstDynamicArgumentIndex;
  for (int i = 0; i < expr->public_members()->length(); i++) {
    ClassLiteral::Property* property = expr->public_members()->at(i);
    ClassBoilerplate::ValueKind value_kind;
    int value_index = dynamic_argument_index;
    switch (property->kind()) {
      case ClassLiteral::Property::METHOD:
        value_kind = ClassBoilerplate::kData;
        break;
      case ClassLiteral::Property::GETTER:
        value_kind = ClassBoilerplate::kGetter;
        break;
      case ClassLiteral::Property::SETTER:
        value_kind = ClassBoilerplate::kSetter;
        break;
      case ClassLiteral::Property::FIELD:
        DCHECK_IMPLIES(property->is_computed_name(), !property->is_private());
        if (property->is_computed_name()) {
          ++dynamic_argument_index;
        }
        continue;
      case ClassLiteral::Property::AUTO_ACCESSOR:
        value_kind = ClassBoilerplate::kAutoAccessor;
        // Auto-accessors have two arguments (getter and setter).
        ++dynamic_argument_index;
    }
    ObjectDescriptor<IsolateT>& desc =
        property->is_static() ? static_desc : instance_desc;
    if (property->is_computed_name()) {
      int computed_name_index = value_index;
      dynamic_argument_index += 2; // Computed name and value indices.
      desc.AddComputed(value_kind, computed_name_index);
      continue;
    }
    dynamic_argument_index++;
    Literal* key_literal = property->key()->AsLiteral();
    uint32_t index;
    if (key_literal->AsArrayIndex(&index)) {
      desc.AddIndexedProperty(isolate, index, value_kind, value_index);
    } else {
      Handle<String> name = key_literal->AsRawPropertyName()->string();
      DCHECK(IsInternalizedString(*name));
      desc.AddNamedProperty(isolate, name, value_kind, value_index);
    }
  }
  static_desc.Finalize(isolate);
  instance_desc.Finalize(isolate);
  auto result = Cast<ClassBoilerplate>(
      factory->NewStruct(CLASS_BOILERPLATE_TYPE, allocation));
  result->set_arguments_count(dynamic_argument_index);
  result->set_static_properties_template(*static_desc.properties_template());
  result->set_static_elements_template(*static_desc.elements_template());
  result->set_static_computed_properties(*static_desc.computed_properties());
  result->set_instance_properties_template(
      *instance_desc.properties_template());
  result->set_instance_elements_template(*instance_desc.elements_template());
  result->set_instance_computed_properties(
      *instance_desc.computed_properties());
  return scope.CloseAndEscape(result);
}
References v8::internal::ObjectDescriptor< IsolateT >::AddComputed(), v8::internal::ObjectDescriptor< IsolateT >::AddConstant(), v8::internal::ObjectDescriptor< IsolateT >::AddIndexedProperty(), v8::internal::ObjectDescriptor< IsolateT >::AddNamedProperty(), v8::internal::Literal::AsArrayIndex(), v8::internal::Literal::AsRawPropertyName(), v8::internal::ClassLiteralProperty::AUTO_ACCESSOR, v8::internal::ObjectDescriptor< IsolateT >::computed_properties(), v8::internal::ObjectDescriptor< IsolateT >::CreateTemplates(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, v8::internal::ObjectDescriptor< IsolateT >::elements_template(), v8::internal::ClassLiteral::end_position(), v8::internal::ClassLiteralProperty::FIELD, v8::internal::ObjectDescriptor< IsolateT >::Finalize(), v8::internal::Smi::FromInt(), v8::internal::ClassLiteralProperty::GETTER, v8::internal::ObjectDescriptor< IsolateT >::IncComputedCount(), v8::internal::ObjectDescriptor< IsolateT >::IncElementsCount(), v8::internal::ObjectDescriptor< IsolateT >::IncPropertiesCount(), v8::internal::index, v8::internal::LiteralProperty::is_computed_name(), v8::internal::ClassLiteralProperty::is_private(), v8::internal::ClassLiteralProperty::is_static(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::Expression::IsPropertyName(), kAutoAccessor, kConstructorArgumentIndex, kData, v8::internal::LiteralProperty::key(), kFirstDynamicArgumentIndex, kGetter, v8::internal::ClassLiteralProperty::kind(), kMinimumClassPropertiesCount, kMinimumPrototypePropertiesCount, kSetter, v8::internal::length, v8::internal::ClassLiteralProperty::METHOD, v8::internal::name, v8::internal::ObjectDescriptor< IsolateT >::properties_template(), v8::internal::ClassLiteral::public_members(), v8::internal::READ_ONLY, v8::base::internal::result, v8::internal::ClassLiteralProperty::SETTER, v8::internal::ClassLiteral::start_position(), v8::internal::AstRawString::string(), and v8::internal::value.
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants().
OBJECT_CONSTRUCTORS()
v8::internal::ClassBoilerplate::OBJECT_CONSTRUCTORS (ClassBoilerplate , Struct) [private]
Member Data Documentation
kMinimumClassPropertiesCount
const int v8::internal::ClassBoilerplate::kMinimumClassPropertiesCount = 6 [static]
Definition at line 153 of file literal-objects.h.
Referenced by v8::internal::anonymous_namespace{literal-objects.cc}::ComputeEnumerationIndex(), and New().
kMinimumPrototypePropertiesCount
const int v8::internal::ClassBoilerplate::kMinimumPrototypePropertiesCount = 1 [static]
Definition at line 154 of file literal-objects.h.
Referenced by v8::internal::anonymous_namespace{literal-objects.cc}::ComputeEnumerationIndex(), and New().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/literal-objects.h
/mnt/V8SourceCode/src/objects/literal-objects.cc