v8::internal::ETWJITInterface::IsolateLoadScriptData Class Reference
#include <etw-isolate-load-script-data-win.h>
Classes
struct EnableInterruptData
struct EnableWithFilterDataInterruptData
Public Member Functions
IsolateLoadScriptData (Isolate *isolate)
IsolateLoadScriptData (IsolateLoadScriptData &&rhs) V8_NOEXCEPT
Static Public Member Functions
static void AddIsolate (Isolate *isolate)
static void RemoveIsolate (Isolate *isolate)
static void UpdateAllIsolates (bool etw_enabled, uint32_t options)
static bool MaybeAddLoadedScript (Isolate *isolate, int script_id)
static void EnableLog (Isolate *isolate, size_t event_id, std::weak_ptr< EtwIsolateCaptureStateMonitor > weak_monitor, uint32_t options)
static void DisableLog (Isolate *isolate, size_t event_id)
static void EnableLogWithFilterDataOnAllIsolates (const uint8_t *data, size_t size, uint32_t options)
static void EnableLogWithFilterData (Isolate *isolate, size_t event_id, const std::string &EnableLogWithFilterData, std::weak_ptr< EtwIsolateCaptureStateMonitor > weak_monitor, uint32_t options)
Private Member Functions
void EnqueueEnableLog (std::weak_ptr< EtwIsolateCaptureStateMonitor > weak_monitor, uint32_t options)
void EnqueueEnableLogWithFilterData (const std::string &etw_filter_payload, std::weak_ptr< EtwIsolateCaptureStateMonitor > weak_monitor, uint32_t options)
void EnqueueDisableLog ()
bool IsScriptLoaded (int script_id) const
void AddLoadedScript (int script_id)
void RemoveAllLoadedScripts ()
size_t CurrentEventId () const
Static Private Member Functions
static IsolateLoadScriptData & GetData (Isolate *isolate)
Private Attributes
Isolate * isolate_ = nullptr
std::unordered_set< int > loaded_scripts_ids_
std::atomic< size_t > event_id_ = 0
Detailed Description
Definition at line 23 of file etw-isolate-load-script-data-win.h.
Constructor & Destructor Documentation
IsolateLoadScriptData() [1/2]
v8::internal::ETWJITInterface::IsolateLoadScriptData::IsolateLoadScriptData (Isolate * isolate) [explicit]
Definition at line 41 of file etw-isolate-load-script-data-win.cc.
    : isolate_(isolate) {}
Referenced by AddIsolate().
IsolateLoadScriptData() [2/2]
v8::internal::ETWJITInterface::IsolateLoadScriptData::IsolateLoadScriptData (IsolateLoadScriptData && rhs) [explicit]
Definition at line 43 of file etw-isolate-load-script-data-win.cc.
                {
  isolate_ = rhs.isolate_;
  loaded_scripts_ids_ = std::move(rhs.loaded_scripts_ids_);
  event_id_ = rhs.event_id_.load();
}
Member Function Documentation
AddIsolate()
void v8::internal::ETWJITInterface::IsolateLoadScriptData::AddIsolate (Isolate * isolate) [static]
Definition at line 51 of file etw-isolate-load-script-data-win.cc.
                                                       {
  base::MutexGuard guard(isolates_mutex.Pointer());
  isolate_map.Pointer()->emplace(isolate, IsolateLoadScriptData(isolate));
}
References v8::internal::ETWJITInterface::isolate_map, IsolateLoadScriptData(), v8::internal::ETWJITInterface::isolates_mutex, and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
Referenced by v8::internal::ETWJITInterface::AddIsolate().
AddLoadedScript()
void v8::internal::ETWJITInterface::IsolateLoadScriptData::AddLoadedScript (int script_id) [private]
Definition at line 299 of file etw-isolate-load-script-data-win.cc.
                                                         {
  loaded_scripts_ids_.insert(script_id);
}
CurrentEventId()
size_t v8::internal::ETWJITInterface::IsolateLoadScriptData::CurrentEventId () const [private]
Definition at line 306 of file etw-isolate-load-script-data-win.cc.
                                                   {
  return event_id_.load();
}
DisableLog()
void v8::internal::ETWJITInterface::IsolateLoadScriptData::DisableLog (Isolate * isolate, size_t event_id) [static]
Definition at line 174 of file etw-isolate-load-script-data-win.cc.
                                                                        {
  {
    base::MutexGuard guard(isolates_mutex.Pointer());
    auto& data = GetData(isolate);
    if (event_id > 0 && data.CurrentEventId() != event_id) {
      // This interrupt was canceled by a newer interrupt.
      return;
    }
    data.RemoveAllLoadedScripts();
  }
  EtwIsolateOperations::Instance()->ResetEtwCodeEventHandler(isolate);
  isolate->SetETWTracingEnabled(false);
}
References v8::internal::ETWJITInterface::isolates_mutex, and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
EnableLog()
void v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLog (Isolate * isolate, size_t event_id, std::weak_ptr< EtwIsolateCaptureStateMonitor > weak_monitor, uint32_t options) [static]
Definition at line 111 of file etw-isolate-load-script-data-win.cc.
                      {
  {
    ETWTRACEDBG << "EnableLog called with event_id==" << event_id
                << " and options==" << options << " taking mutex" << std::endl;
    base::MutexGuard guard(isolates_mutex.Pointer());
    auto& data = GetData(isolate);
    if (event_id > 0 && data.CurrentEventId() != event_id) {
      // This interrupt was canceled by a newer interrupt.
      return;
    }
    // Cause all SourceLoad events to be re-emitted.
    if (options & kJitCodeEventEnumExisting) {
      data.RemoveAllLoadedScripts();
    }
  }
  ETWTRACEDBG << "Mutex released with event_id==" << event_id << std::endl;
  // This cannot be done while isolate_mutex is locked, as it can call
  // EventHandler while in the call for all the existing code.
  EtwIsolateOperations::Instance()->SetEtwCodeEventHandler(isolate, options);
  isolate->SetETWTracingEnabled(true);
  // Notify waiting thread if a monitor was provided.
  if (auto monitor = weak_monitor.lock()) {
    ETWTRACEDBG << "monitor->Notify with event_id==" << event_id << std::endl;
    monitor->Notify();
  }
}
References ETWTRACEDBG, v8::internal::ETWJITInterface::isolates_mutex, v8::kJitCodeEventEnumExisting, and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
Referenced by v8::internal::ETWJITInterface::MaybeSetHandlerNow().
EnableLogWithFilterData()
void v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLogWithFilterData (Isolate * isolate, size_t event_id, const std::string & EnableLogWithFilterData, std::weak_ptr< EtwIsolateCaptureStateMonitor > weak_monitor, uint32_t options) [static]
Definition at line 189 of file etw-isolate-load-script-data-win.cc.
                      {
  bool filter_did_match = false;
  DCHECK(!etw_filter_payload.empty());
  {
    ETWTRACEDBG << "EnableLogWithFilterData called with event_id==" << event_id
                << " and options==" << options << " taking mutex" << std::endl;
    base::MutexGuard guard(isolates_mutex.Pointer());
    auto& data = GetData(isolate);
    if (event_id > 0 && data.CurrentEventId() != event_id) {
      // This interrupt was canceled by a newer interrupt.
      return;
    }
    FilterETWSessionByURLResult filter_etw_session_by_url_result =
        EtwIsolateOperations::Instance()->RunFilterETWSessionByURLCallback(
            isolate, etw_filter_payload);
    filter_did_match = filter_etw_session_by_url_result.enable_etw_tracing;
    if (filter_did_match) {
      if (filter_etw_session_by_url_result.trace_interpreter_frames) {
        isolate->set_etw_trace_interpreted_frames();
      }
      // Cause all SourceLoad events to be re-emitted.
      if (options & kJitCodeEventEnumExisting) {
        data.RemoveAllLoadedScripts();
      }
    }
  }
  if (filter_did_match) {
    ETWTRACEDBG << "Filter was matched with event_id==" << event_id
                << std::endl;
    EtwIsolateOperations::Instance()->SetEtwCodeEventHandler(isolate, options);
    isolate->SetETWTracingEnabled(true);
  }
  // Notify waiting thread if a monitor was provided.
  if (auto monitor = weak_monitor.lock()) {
    ETWTRACEDBG << "monitor->Notify with event_id==" << event_id << std::endl;
    monitor->Notify();
  }
}
References v8::internal::DCHECK(), ETWTRACEDBG, v8::internal::ETWJITInterface::isolates_mutex, v8::kJitCodeEventEnumExisting, and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
Referenced by v8::internal::ETWJITInterface::MaybeSetHandlerNow().
EnableLogWithFilterDataOnAllIsolates()
void v8::internal::ETWJITInterface::IsolateLoadScriptData::EnableLogWithFilterDataOnAllIsolates (const uint8_t * data, size_t size, uint32_t options) [static]
Definition at line 146 of file etw-isolate-load-script-data-win.cc.
                                                        {
  base::MutexGuard guard(isolates_mutex.Pointer());
  std::string etw_filter_payload;
  etw_filter_payload.assign(data, data + size);
  auto monitor = std::make_shared<EtwIsolateCaptureStateMonitor>(
      isolates_mutex.Pointer(), isolate_map.Pointer()->size());
  bool capture_state =
      (options & kJitCodeEventEnumExisting) == kJitCodeEventEnumExisting;
  std::weak_ptr<EtwIsolateCaptureStateMonitor> weak_monitor = monitor;
  std::for_each(isolate_map.Pointer()->begin(), isolate_map.Pointer()->end(),
                [&etw_filter_payload, weak_monitor, options](auto& pair) {
                  auto& isolate_data = pair.second;
                  isolate_data.EnqueueEnableLogWithFilterData(
                      etw_filter_payload, weak_monitor, options);
                });
  if (!capture_state) {
    return;
  }
  bool timeout = !monitor->WaitFor(kCaptureStateTimeout);
  ETWTRACEDBG << "EnableLogWithFilterDataOnAllIsolates WaitFor "
              << (timeout ? "timeout" : "completed") << std::endl;
}
References ETWTRACEDBG, v8::internal::ETWJITInterface::isolate_map, v8::internal::ETWJITInterface::isolates_mutex, v8::internal::ETWJITInterface::kCaptureStateTimeout, v8::kJitCodeEventEnumExisting, v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer(), size(), and v8::internal::string.
Referenced by v8::internal::ETWJITInterface::ETWEnableCallback().
EnqueueDisableLog()
void v8::internal::ETWJITInterface::IsolateLoadScriptData::EnqueueDisableLog () [private]
Definition at line 261 of file etw-isolate-load-script-data-win.cc.
                                              {
  size_t event_id = event_id_.fetch_add(1);
  EtwIsolateOperations::Instance()->RequestInterrupt(
      isolate_,
      // Executed in the isolate thread.
      [](v8::Isolate* v8_isolate, void* data) {
        DisableLog(reinterpret_cast<Isolate*>(v8_isolate),
                   reinterpret_cast<size_t>(data));
      },
      reinterpret_cast<void*>(event_id + 1));
}
EnqueueEnableLog()
void v8::internal::ETWJITInterface::IsolateLoadScriptData::EnqueueEnableLog (std::weak_ptr< EtwIsolateCaptureStateMonitor > weak_monitor, uint32_t options) [private]
Definition at line 242 of file etw-isolate-load-script-data-win.cc.
                      {
  size_t event_id = event_id_.fetch_add(1);
  EtwIsolateOperations::Instance()->RequestInterrupt(
      isolate_,
      // Executed in the isolate thread.
      [](v8::Isolate* v8_isolate, void* data) {
        std::unique_ptr<EnableInterruptData> interrupt_data(
            reinterpret_cast<EnableInterruptData*>(data));
        size_t event_id = interrupt_data->event_id;
        auto weak_monitor = interrupt_data->weak_monitor;
        uint32_t options = interrupt_data->options;
        EnableLog(reinterpret_cast<Isolate*>(v8_isolate), event_id,
                  weak_monitor, options);
      },
      new EnableInterruptData{event_id + 1, weak_monitor, options});
}
EnqueueEnableLogWithFilterData()
void v8::internal::ETWJITInterface::IsolateLoadScriptData::EnqueueEnableLogWithFilterData (const std::string & etw_filter_payload, std::weak_ptr< EtwIsolateCaptureStateMonitor > weak_monitor, uint32_t options) [private]
Definition at line 273 of file etw-isolate-load-script-data-win.cc.
                      {
  size_t event_id = event_id_.fetch_add(1);
  EtwIsolateOperations::Instance()->RequestInterrupt(
      isolate_,
      // Executed in the isolate thread.
      [](v8::Isolate* v8_isolate, void* data) {
        std::unique_ptr<EnableWithFilterDataInterruptData> interrupt_data(
            reinterpret_cast<EnableWithFilterDataInterruptData*>(data));
        size_t event_id = interrupt_data->event_id;
        std::string etw_filter_payload = interrupt_data->payload;
        auto weak_monitor = interrupt_data->weak_monitor;
        uint32_t options = interrupt_data->options;
        EnableLogWithFilterData(reinterpret_cast<Isolate*>(v8_isolate),
                                event_id, etw_filter_payload, weak_monitor,
                                options);
      },
      new EnableWithFilterDataInterruptData{event_id + 1, etw_filter_payload,
                                            weak_monitor, options});
}
References v8::internal::string.
GetData()
IsolateLoadScriptData & v8::internal::ETWJITInterface::IsolateLoadScriptData::GetData (Isolate * isolate) [static], [private]
Definition at line 238 of file etw-isolate-load-script-data-win.cc.
                                                                      {
  return isolate_map.Pointer()->at(isolate);
}
References v8::internal::ETWJITInterface::isolate_map.
IsScriptLoaded()
bool v8::internal::ETWJITInterface::IsolateLoadScriptData::IsScriptLoaded (int script_id) const [private]
Definition at line 296 of file etw-isolate-load-script-data-win.cc.
                                                              {
  return loaded_scripts_ids_.find(script_id) != loaded_scripts_ids_.end();
}
MaybeAddLoadedScript()
bool v8::internal::ETWJITInterface::IsolateLoadScriptData::MaybeAddLoadedScript (Isolate * isolate, int script_id) [static]
Definition at line 99 of file etw-isolate-load-script-data-win.cc.
                                                                {
  base::MutexGuard guard(isolates_mutex.Pointer());
  auto& data = GetData(isolate);
  if (data.IsScriptLoaded(script_id)) {
    return false;
  }
  data.AddLoadedScript(script_id);
  return true;
}
References v8::internal::ETWJITInterface::isolates_mutex, and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
Referenced by v8::internal::ETWJITInterface::EventHandler().
RemoveAllLoadedScripts()
void v8::internal::ETWJITInterface::IsolateLoadScriptData::RemoveAllLoadedScripts () [private]
Definition at line 302 of file etw-isolate-load-script-data-win.cc.
                                                   {
  loaded_scripts_ids_.clear();
}
RemoveIsolate()
void v8::internal::ETWJITInterface::IsolateLoadScriptData::RemoveIsolate (Isolate * isolate) [static]
Definition at line 57 of file etw-isolate-load-script-data-win.cc.
                                                          {
  base::MutexGuard guard(isolates_mutex.Pointer());
  isolate_map.Pointer()->erase(isolate);
}
References v8::internal::ETWJITInterface::isolate_map, v8::internal::ETWJITInterface::isolates_mutex, and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
Referenced by v8::internal::ETWJITInterface::RemoveIsolate().
UpdateAllIsolates()
void v8::internal::ETWJITInterface::IsolateLoadScriptData::UpdateAllIsolates (bool etw_enabled, uint32_t options) [static]
Definition at line 63 of file etw-isolate-load-script-data-win.cc.
                                                                {
  ETWTRACEDBG << "UpdateAllIsolates with etw_enabled==" << etw_enabled
              << " and options==" << options << " acquiring mutex" << std::endl;
  base::MutexGuard guard(isolates_mutex.Pointer());
  ETWTRACEDBG << "UpdateAllIsolates Isolate count=="
              << isolate_map.Pointer()->size() << std::endl;
  auto monitor = std::make_shared<EtwIsolateCaptureStateMonitor>(
      isolates_mutex.Pointer(), isolate_map.Pointer()->size());
  bool capture_state =
      (options & kJitCodeEventEnumExisting) == kJitCodeEventEnumExisting;
  std::weak_ptr<EtwIsolateCaptureStateMonitor> weak_monitor = monitor;
  std::for_each(
      isolate_map.Pointer()->begin(), isolate_map.Pointer()->end(),
      [etw_enabled, weak_monitor, options](auto& pair) {
        auto& isolate_data = pair.second;
        if (etw_enabled) {
          ETWTRACEDBG << "UpdateAllIsolates enqueing enablelog" << std::endl;
          isolate_data.EnqueueEnableLog(weak_monitor, options);
        } else {
          ETWTRACEDBG << "UpdateAllIsolates enqueing disablelog" << std::endl;
          isolate_data.EnqueueDisableLog();
        }
      });
  if (!capture_state) {
    return;
  }
  ETWTRACEDBG << "UpdateAllIsolates starting WaitFor" << std::endl;
  bool timeout = !monitor->WaitFor(kCaptureStateTimeout);
  ETWTRACEDBG << "UpdateAllIsolates WaitFor "
              << (timeout ? "timeout" : "completed") << std::endl;
}
References ETWTRACEDBG, v8::internal::ETWJITInterface::isolate_map, v8::internal::ETWJITInterface::isolates_mutex, v8::kJitCodeEventEnumExisting, and v8::base::LazyInstanceImpl< T, AllocationTrait, CreateTrait, InitOnceTrait, DestroyTrait >::Pointer().
Referenced by v8::internal::ETWJITInterface::UpdateETWEnabled().
Member Data Documentation
event_id_
std::atomic<size_t> v8::internal::ETWJITInterface::IsolateLoadScriptData::event_id_ = 0 [private]
Definition at line 82 of file etw-isolate-load-script-data-win.h.
isolate_
Isolate* v8::internal::ETWJITInterface::IsolateLoadScriptData::isolate_ = nullptr [private]
Definition at line 80 of file etw-isolate-load-script-data-win.h.
loaded_scripts_ids_
std::unordered_set<int> v8::internal::ETWJITInterface::IsolateLoadScriptData::loaded_scripts_ids_ [private]
Definition at line 81 of file etw-isolate-load-script-data-win.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/diagnostics/etw-isolate-load-script-data-win.h
/mnt/V8SourceCode/src/diagnostics/etw-isolate-load-script-data-win.cc