v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next > Class Template Reference
#include <wasm-gc-typed-optimization-reducer.h>
Public Member Functions
void Analyze ()
V< Object > REDUCE_INPUT_GRAPH() WasmTypeCast (V< Object > op_idx, const WasmTypeCastOp &cast_op)
V< Word32 > REDUCE_INPUT_GRAPH() WasmTypeCheck (V< Word32 > op_idx, const WasmTypeCheckOp &type_check)
V< Object > REDUCE_INPUT_GRAPH() AssertNotNull (V< Object > op_idx, const AssertNotNullOp &assert_not_null)
V< Word32 > REDUCE_INPUT_GRAPH() IsNull (V< Word32 > op_idx, const IsNullOp &is_null)
V< Object > REDUCE_INPUT_GRAPH() WasmTypeAnnotation (V< Object > op_idx, const WasmTypeAnnotationOp &type_annotation)
V< Any > REDUCE_INPUT_GRAPH() StructGet (V< Any > op_idx, const StructGetOp &struct_get)
V< None > REDUCE_INPUT_GRAPH() StructSet (V< None > op_idx, const StructSetOp &struct_set)
V< Word32 > REDUCE_INPUT_GRAPH() ArrayLength (V< Word32 > op_idx, const ArrayLengthOp &array_length)
V< Object > REDUCE() AnyConvertExtern (V< Object > object, bool is_shared)
Private Attributes
Graph & graph_ = __ modifiable_input_graph()
const wasm::WasmModule * module_ = __ data() -> wasm_module()
WasmGCTypeAnalyzer analyzer_ {__ data(), graph_, __ phase_zone()}
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >
Definition at line 148 of file wasm-gc-typed-optimization-reducer.h.
Member Function Documentation
Analyze()
template<class Next >
void v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::Analyze () [inline]
Definition at line 152 of file wasm-gc-typed-optimization-reducer.h.
                 {
    analyzer_.Run();
    Next::Analyze();
  }
References v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::analyzer_, and v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::Run().
AnyConvertExtern()
template<class Next >
V<Object> REDUCE() v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::AnyConvertExtern (V< Object > object, bool is_shared) [inline]
Definition at line 415 of file wasm-gc-typed-optimization-reducer.h.
                                                                       {
    LABEL_BLOCK(no_change) {
      return Next::ReduceAnyConvertExtern(object, is_shared);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    if (object.valid()) {
      const ExternConvertAnyOp* externalize =
          __ output_graph().Get(object).template TryCast<ExternConvertAnyOp>();
      if (externalize != nullptr) {
        // Directly return the object as
        // any.convert_extern(extern.convert_any(x)) == x.
        return externalize->object();
      }
    }
    goto no_change;
  }
References __, v8::internal::is_shared, LABEL_BLOCK, and v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep().
ArrayLength()
template<class Next >
V<Word32> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::ArrayLength (V< Word32 > op_idx, const ArrayLengthOp & array_length) [inline]
Definition at line 397 of file wasm-gc-typed-optimization-reducer.h.
                                                                               {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphArrayLength(op_idx, array_length);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    const wasm::ValueType type = analyzer_.GetInputTypeOrSentinelType(op_idx);
    // Remove the null check if it is known to be not null.
    if (array_length.null_check == kWithNullCheck && type.is_non_nullable()) {
      return __ ArrayLength(__ MapToNewGraph(array_length.array()),
                            kWithoutNullCheck);
    }
    goto no_change;
  }
References __, v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetInputTypeOrSentinelType(), v8::internal::compiler::kWithNullCheck, v8::internal::compiler::kWithoutNullCheck, LABEL_BLOCK, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), and v8::internal::tracing::type.
AssertNotNull()
template<class Next >
V<Object> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::AssertNotNull (V< Object > op_idx, const AssertNotNullOp & assert_not_null) [inline]
Definition at line 288 of file wasm-gc-typed-optimization-reducer.h.
                                                                {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphAssertNotNull(op_idx, assert_not_null);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    wasm::ValueType type = analyzer_.GetInputTypeOrSentinelType(op_idx);
    if (type.is_uninhabited()) {
      // We are either already in unreachable code (then this instruction isn't
      // even emitted) or the type analyzer inferred that this instruction will
      // always trap. In either case emitting an unconditional trap to increase
      // the chances of logic errors just leading to wrong behaviors but not
      // resulting in security issues.
      __ TrapIf(1, assert_not_null.trap_id);
      __ Unreachable();
      return OpIndex::Invalid();
    }
    if (type.is_non_nullable()) {
      return __ MapToNewGraph(assert_not_null.object());
    }
    goto no_change;
  }
References __, v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetInputTypeOrSentinelType(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), LABEL_BLOCK, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast().
IsNull()
template<class Next >
V<Word32> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::IsNull (V< Word32 > op_idx, const IsNullOp & is_null) [inline]
Definition at line 312 of file wasm-gc-typed-optimization-reducer.h.
                                                                {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphIsNull(op_idx, is_null);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    const wasm::ValueType type = analyzer_.GetInputTypeOrSentinelType(op_idx);
    if (type.is_uninhabited()) {
      __ Unreachable();
      return OpIndex::Invalid();
    }
    if (type.is_non_nullable()) {
      return __ Word32Constant(0);
    }
    if (type != wasm::ValueType() &&
        wasm::ToNullSentinel({type, module_}) == type) {
      return __ Word32Constant(1);
    }
    goto no_change;
  }
References __, v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetInputTypeOrSentinelType(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), LABEL_BLOCK, v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::module_, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::wasm::ToNullSentinel(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast(), and v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck().
StructGet()
template<class Next >
V<Any> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::StructGet (V< Any > op_idx, const StructGetOp & struct_get) [inline]
Definition at line 340 of file wasm-gc-typed-optimization-reducer.h.
                                                                      {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphStructGet(op_idx, struct_get);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    const wasm::ValueType type = analyzer_.GetInputTypeOrSentinelType(op_idx);
    if (type.is_uninhabited()) {
      // We are either already in unreachable code (then this instruction isn't
      // even emitted) or the type analyzer inferred that this instruction will
      // always trap. In either case emitting an unconditional trap to increase
      // the chances of logic errors just leading to wrong behaviors but not
      // resulting in security issues.
      __ TrapIf(1, TrapId::kTrapNullDereference);
      __ Unreachable();
      return OpIndex::Invalid();
    }
    // Remove the null check if it is known to be not null.
    if (struct_get.null_check == kWithNullCheck && type.is_non_nullable()) {
      return __ StructGet(__ MapToNewGraph(struct_get.object()),
                          struct_get.type, struct_get.type_index,
                          struct_get.field_index, struct_get.is_signed,
                          kWithoutNullCheck, struct_get.memory_order);
    }
    goto no_change;
  }
References __, v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetInputTypeOrSentinelType(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::kWithNullCheck, v8::internal::compiler::kWithoutNullCheck, LABEL_BLOCK, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), and v8::internal::tracing::type.
StructSet()
template<class Next >
V<None> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::StructSet (V< None > op_idx, const StructSetOp & struct_set) [inline]
Definition at line 368 of file wasm-gc-typed-optimization-reducer.h.
                                                                       {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphStructSet(op_idx, struct_set);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    const wasm::ValueType type = analyzer_.GetInputTypeOrSentinelType(op_idx);
    if (type.is_uninhabited()) {
      // We are either already in unreachable code (then this instruction isn't
      // even emitted) or the type analyzer inferred that this instruction will
      // always trap. In either case emitting an unconditional trap to increase
      // the chances of logic errors just leading to wrong behaviors but not
      // resulting in security issues.
      __ TrapIf(1, TrapId::kTrapNullDereference);
      __ Unreachable();
      return OpIndex::Invalid();
    }
    // Remove the null check if it is known to be not null.
    if (struct_set.null_check == kWithNullCheck && type.is_non_nullable()) {
      __ StructSet(__ MapToNewGraph(struct_set.object()),
                   __ MapToNewGraph(struct_set.value()), struct_set.type,
                   struct_set.type_index, struct_set.field_index,
                   kWithoutNullCheck, struct_set.memory_order);
      return OpIndex::Invalid();
    }
    goto no_change;
  }
References __, v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetInputTypeOrSentinelType(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::kWithNullCheck, v8::internal::compiler::kWithoutNullCheck, LABEL_BLOCK, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), and v8::internal::tracing::type.
WasmTypeAnnotation()
template<class Next >
V<Object> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeAnnotation (V< Object > op_idx, const WasmTypeAnnotationOp & type_annotation) [inline]
Definition at line 334 of file wasm-gc-typed-optimization-reducer.h.
                                                                     {
    // Remove type annotation operations as they are not needed any more.
    return __ MapToNewGraph(type_annotation.value());
  }
References __.
WasmTypeCast()
template<class Next >
V<Object> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast (V< Object > op_idx, const WasmTypeCastOp & cast_op) [inline]
Definition at line 157 of file wasm-gc-typed-optimization-reducer.h.
                                                                            {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphWasmTypeCast(op_idx, cast_op);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    wasm::ValueType type = analyzer_.GetInputTypeOrSentinelType(op_idx);
    if (type.is_uninhabited()) {
      // We are either already in unreachable code (then this instruction isn't
      // even emitted) or the type analyzer inferred that this instruction will
      // always trap. In either case emitting an unconditional trap to increase
      // the chances of logic errors just leading to wrong behaviors but not
      // resulting in security issues.
      __ TrapIf(1, TrapId::kTrapIllegalCast);
      __ Unreachable();
      return OpIndex::Invalid();
    }
    if (type != wasm::ValueType()) {
      CHECK(!type.is_uninhabited());
      CHECK(wasm::IsSameTypeHierarchy(type.heap_type(),
                                      cast_op.config.to.heap_type(), module_));
      bool to_nullable = cast_op.config.to.is_nullable();
      if (wasm::IsHeapSubtypeOf(type.heap_type(), cast_op.config.to.heap_type(),
                                module_)) {
        if (to_nullable || type.is_non_nullable()) {
          // The inferred type is already as specific as the cast target, the
          // cast is guaranteed to always succeed and can therefore be removed.
          return __ MapToNewGraph(cast_op.object());
        } else {
          // The inferred heap type is already as specific as the cast target,
          // but the source can be nullable and the target cannot be, so a null
          // check is still required.
          return __ AssertNotNull(__ MapToNewGraph(cast_op.object()), type,
                                  TrapId::kTrapIllegalCast);
        }
      }
      if (wasm::HeapTypesUnrelated(type.heap_type(),
                                   cast_op.config.to.heap_type(), module_)) {
        // A cast between unrelated types can only succeed if the argument is
        // null. Otherwise, it always fails.
        V<Word32> non_trapping_condition =
            type.is_nullable() && to_nullable ? __ IsNull(__ MapToNewGraph(
                                                              cast_op.object()),
                                                          type)
                                              : __ Word32Constant(0);
        __ TrapIfNot(non_trapping_condition, TrapId::kTrapIllegalCast);
        if (!to_nullable) {
          __ Unreachable();
        }
        return __ MapToNewGraph(cast_op.object());
      }
      // If the cast resulted in an uninhabitable type, the analyzer should have
      // returned a sentinel (bottom) type as {type}.
      CHECK(!wasm::Intersection(type, cast_op.config.to, module_)
                 .type.is_uninhabited());
      // The cast cannot be replaced. Still, we can refine the source type, so
      // that the lowering could potentially skip null or smi checks.
      wasm::ValueType from_type =
          wasm::Intersection(type, cast_op.config.from, module_).type;
      DCHECK(!from_type.is_uninhabited());
      WasmTypeCheckConfig config{from_type, cast_op.config.to,
                                 cast_op.config.exactness};
      return __ WasmTypeCast(__ MapToNewGraph(cast_op.object()),
                             __ MapToNewGraph(cast_op.rtt()), config);
    }
    goto no_change;
  }
References __, v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::analyzer_, v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::AssertNotNull(), CHECK, v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::exactness(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetInputTypeOrSentinelType(), v8::internal::wasm::HeapTypesUnrelated(), v8::internal::wasm::Intersection(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::wasm::IsHeapSubtypeOf(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::IsNull(), v8::internal::wasm::IsSameTypeHierarchy(), LABEL_BLOCK, v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::module_, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::tracing::type, and v8::internal::wasm::TypeInModule::type.
WasmTypeCheck()
template<class Next >
V<Word32> REDUCE_INPUT_GRAPH() v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck (V< Word32 > op_idx, const WasmTypeCheckOp & type_check) [inline]
Definition at line 228 of file wasm-gc-typed-optimization-reducer.h.
                                                           {
    LABEL_BLOCK(no_change) {
      return Next::ReduceInputGraphWasmTypeCheck(op_idx, type_check);
    }
    if (ShouldSkipOptimizationStep()) goto no_change;
    wasm::ValueType type = analyzer_.GetInputTypeOrSentinelType(op_idx);
    if (type.is_uninhabited()) {
      __ Unreachable();
      return OpIndex::Invalid();
    }
    if (type != wasm::ValueType()) {
      CHECK(!type.is_uninhabited());
      CHECK(wasm::IsSameTypeHierarchy(
          type.heap_type(), type_check.config.to.heap_type(), module_));
      bool to_nullable = type_check.config.to.is_nullable();
      if (wasm::IsHeapSubtypeOf(type.heap_type(),
                                type_check.config.to.heap_type(), module_)) {
        if (to_nullable || type.is_non_nullable()) {
          // The inferred type is guaranteed to be a subtype of the checked
          // type.
          return __ Word32Constant(1);
        } else {
          // The inferred type is guaranteed to be a subtype of the checked
          // type if it is not null.
          return __ Word32Equal(
              __ IsNull(__ MapToNewGraph(type_check.object()), type), 0);
        }
      }
      if (wasm::HeapTypesUnrelated(type.heap_type(),
                                   type_check.config.to.heap_type(), module_)) {
        if (to_nullable && type.is_nullable()) {
          return __ IsNull(__ MapToNewGraph(type_check.object()), type);
        } else {
          return __ Word32Constant(0);
        }
      }
      // If there isn't a type that matches our known input type and the
      // type_check.config.to type, the type check always fails.
      wasm::ValueType true_type =
          wasm::Intersection(type, type_check.config.to, module_).type;
      if (true_type.is_uninhabited()) {
        return __ Word32Constant(0);
      }
      // The check cannot be replaced. Still, we can refine the source type, so
      // that the lowering could potentially skip null or smi checks.
      wasm::ValueType from_type =
          wasm::Intersection(type, type_check.config.from, module_).type;
      DCHECK(!from_type.is_uninhabited());
      WasmTypeCheckConfig config{from_type, type_check.config.to,
                                 type_check.config.exactness};
      return __ WasmTypeCheck(__ MapToNewGraph(type_check.object()),
                              __ MapToNewGraph(type_check.rtt()), config);
    }
    goto no_change;
  }
References __, v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::analyzer_, CHECK, v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::exactness(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetInputTypeOrSentinelType(), v8::internal::wasm::HeapTypesUnrelated(), v8::internal::wasm::Intersection(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::wasm::IsHeapSubtypeOf(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::IsNull(), v8::internal::wasm::IsSameTypeHierarchy(), LABEL_BLOCK, v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::module_, v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::tracing::type, v8::internal::wasm::TypeInModule::type, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Member Data Documentation
analyzer_
template<class Next >
WasmGCTypeAnalyzer v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::analyzer_ {__ data(), graph_, __ phase_zone()} [private]
Definition at line 436 of file wasm-gc-typed-optimization-reducer.h.
Referenced by v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::Analyze(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::ArrayLength(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::AssertNotNull(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::IsNull(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::StructGet(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::StructSet(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast(), and v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck().
graph_
template<class Next >
Graph& v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::graph_ = __ modifiable_input_graph() [private]
Definition at line 434 of file wasm-gc-typed-optimization-reducer.h.
module_
template<class Next >
const wasm::WasmModule* v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::module_ = __ data() -> wasm_module() [private]
Definition at line 435 of file wasm-gc-typed-optimization-reducer.h.
Referenced by v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::IsNull(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast(), and v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/wasm-gc-typed-optimization-reducer.h