v8::internal::ExperimentalRegExp Class Reference
#include <experimental.h>
Static Public Member Functions
static bool CanBeHandled (RegExpTree *tree, DirectHandle< String > pattern, RegExpFlags flags, int capture_count)
static void Initialize (Isolate *isolate, DirectHandle< JSRegExp > re, DirectHandle< String > pattern, RegExpFlags flags, int capture_count)
static bool IsCompiled (DirectHandle< IrRegExpData > re_data, Isolate *isolate)
static V8_WARN_UNUSED_RESULT bool Compile (Isolate *isolate, DirectHandle< IrRegExpData > re_data)
static int32_t MatchForCallFromJs (Address subject, int32_t start_position, Address input_start, Address input_end, int *output_registers, int32_t output_register_count, RegExp::CallOrigin call_origin, Isolate *isolate, Address regexp_data)
static std::optional< int > Exec (Isolate *isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject, int index, int32_t *result_offsets_vector, uint32_t result_offsets_vector_length)
static int32_t ExecRaw (Isolate *isolate, RegExp::CallOrigin call_origin, Tagged< IrRegExpData > regexp_data, Tagged< String > subject, int32_t *output_registers, int32_t output_register_count, int32_t subject_index)
static std::optional< int > OneshotExec (Isolate *isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject, int index, int32_t *result_offsets_vector, uint32_t result_offsets_vector_length)
static int32_t OneshotExecRaw (Isolate *isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject, int32_t *output_registers, int32_t output_register_count, int32_t subject_index)
Static Public Attributes
static constexpr bool kSupportsUnicode = false
Detailed Description
Definition at line 14 of file experimental.h.
Member Function Documentation
CanBeHandled()
bool v8::internal::ExperimentalRegExp::CanBeHandled (RegExpTree * tree, DirectHandle< String > pattern, RegExpFlags flags, int capture_count) [static]
Definition at line 19 of file experimental.cc.
                                                                            {
  DCHECK(v8_flags.enable_experimental_regexp_engine ||
         v8_flags.enable_experimental_regexp_engine_on_excessive_backtracks);
  bool can_be_handled =
      ExperimentalRegExpCompiler::CanBeHandled(tree, flags, capture_count);
  if (!can_be_handled && v8_flags.trace_experimental_regexp_engine) {
    StdoutStream{} << "Pattern not supported by experimental engine: "
                   << pattern << std::endl;
  }
  return can_be_handled;
}
References v8::internal::ExperimentalRegExpCompiler::CanBeHandled(), v8::internal::DCHECK(), v8::internal::flags, and v8::internal::v8_flags.
Referenced by v8::internal::RegExp::Compile(), and v8::internal::RegExpImpl::Compile().
Compile()
bool v8::internal::ExperimentalRegExp::Compile (Isolate * isolate, DirectHandle< IrRegExpData > re_data) [static]
Definition at line 113 of file experimental.cc.
                                                                     {
  DCHECK(v8_flags.enable_experimental_regexp_engine);
  DCHECK_EQ(re_data->type_tag(), RegExpData::Type::EXPERIMENTAL);
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) re_data->IrRegExpDataVerify(isolate);
#endif
  DirectHandle<String> source(re_data->source(), isolate);
  if (v8_flags.trace_experimental_regexp_engine) {
    StdoutStream{} << "Compiling experimental regexp " << *source << std::endl;
  }
  std::optional<CompilationResult> compilation_result =
      CompileImpl(isolate, re_data);
  if (!compilation_result.has_value()) {
    DCHECK(isolate->has_exception());
    return false;
  }
  re_data->SetBytecodeForExperimental(isolate, *compilation_result->bytecode);
  re_data->set_capture_name_map(compilation_result->capture_name_map);
  return true;
}
References v8::internal::anonymous_namespace{experimental.cc}::CompileImpl(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::RegExpData::EXPERIMENTAL, v8::internal::Isolate::has_exception(), and v8::internal::v8_flags.
Referenced by v8::internal::RegExp::EnsureFullyCompiled(), Exec(), and v8::internal::RegExpGlobalExecRunner::RegExpGlobalExecRunner().
Exec()
std::optional< int > v8::internal::ExperimentalRegExp::Exec (Isolate * isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject, int index, int32_t * result_offsets_vector, uint32_t result_offsets_vector_length) [static]
Definition at line 220 of file experimental.cc.
                                           {
  DCHECK(v8_flags.enable_experimental_regexp_engine);
  DCHECK_EQ(regexp_data->type_tag(), RegExpData::Type::EXPERIMENTAL);
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) regexp_data->IrRegExpDataVerify(isolate);
#endif
  if (!IsCompiled(regexp_data, isolate) && !Compile(isolate, regexp_data)) {
    DCHECK(isolate->has_exception());
    return {};
  }
  DCHECK(IsCompiled(regexp_data, isolate));
  subject = String::Flatten(isolate, subject);
  DCHECK_GE(result_offsets_vector_length,
            JSRegExp::RegistersForCaptureCount(regexp_data->capture_count()));
  do {
    int num_matches =
        ExecRaw(isolate, RegExp::kFromRuntime, *regexp_data, *subject,
                result_offsets_vector, result_offsets_vector_length, index);
    if (num_matches > 0) {
      DCHECK_LE(num_matches * JSRegExp::RegistersForCaptureCount(
                                  regexp_data->capture_count()),
                result_offsets_vector_length);
      return num_matches;
    } else if (num_matches == 0) {
      return num_matches;
    } else {
      DCHECK_LT(num_matches, 0);
      if (num_matches == RegExp::kInternalRegExpRetry) {
        // Re-run execution.
        continue;
      }
      DCHECK(isolate->has_exception());
      return {};
    }
  } while (true);
  UNREACHABLE();
}
References Compile(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_LE, DCHECK_LT, ExecRaw(), v8::internal::RegExpData::EXPERIMENTAL, v8::internal::Isolate::has_exception(), v8::internal::index, IsCompiled(), v8::internal::RegExp::kFromRuntime, v8::internal::RegExp::kInternalRegExpRetry, v8::internal::JSRegExp::RegistersForCaptureCount(), v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by v8::internal::RegExp::Exec().
ExecRaw()
int32_t v8::internal::ExperimentalRegExp::ExecRaw (Isolate * isolate, RegExp::CallOrigin call_origin, Tagged< IrRegExpData > regexp_data, Tagged< String > subject, int32_t * output_registers, int32_t output_register_count, int32_t subject_index) [static]
Definition at line 173 of file experimental.cc.
                                                           {
  CHECK(v8_flags.enable_experimental_regexp_engine);
  DisallowGarbageCollection no_gc;
  if (v8_flags.trace_experimental_regexp_engine) {
    StdoutStream{} << "Executing experimental regexp " << regexp_data->source()
                   << std::endl;
  }
  static constexpr bool kIsLatin1 = true;
  Tagged<TrustedByteArray> bytecode = regexp_data->bytecode(kIsLatin1);
  return ExecRawImpl(isolate, call_origin, bytecode, subject,
                     regexp_data->capture_count(), output_registers,
                     output_register_count, subject_index);
}
References v8::internal::call_origin, CHECK, v8::internal::anonymous_namespace{experimental.cc}::ExecRawImpl(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::v8_flags.
Referenced by Exec(), v8::internal::RegExpGlobalExecRunner::FetchNext(), and MatchForCallFromJs().
Initialize()
void v8::internal::ExperimentalRegExp::Initialize (Isolate * isolate, DirectHandle< JSRegExp > re, DirectHandle< String > pattern, RegExpFlags flags, int capture_count) [static]
Definition at line 33 of file experimental.cc.
                                                                          {
  DCHECK(v8_flags.enable_experimental_regexp_engine);
  if (v8_flags.trace_experimental_regexp_engine) {
    StdoutStream{} << "Initializing experimental regexp " << *source
                   << std::endl;
  }
  isolate->factory()->SetRegExpExperimentalData(
      re, source, JSRegExp::AsJSRegExpFlags(flags), capture_count);
}
References v8::internal::JSRegExp::AsJSRegExpFlags(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::flags, v8::internal::Factory::SetRegExpExperimentalData(), and v8::internal::v8_flags.
Referenced by v8::internal::RegExp::Compile().
IsCompiled()
bool v8::internal::ExperimentalRegExp::IsCompiled (DirectHandle< IrRegExpData > re_data, Isolate * isolate) [static]
Definition at line 46 of file experimental.cc.
                                                      {
  DCHECK(v8_flags.enable_experimental_regexp_engine);
  DCHECK_EQ(re_data->type_tag(), RegExpData::Type::EXPERIMENTAL);
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) re_data->IrRegExpDataVerify(isolate);
#endif
  static constexpr bool kIsLatin1 = true;
  return re_data->has_bytecode(kIsLatin1);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::RegExpData::EXPERIMENTAL, and v8::internal::v8_flags.
Referenced by v8::internal::RegExp::EnsureFullyCompiled(), Exec(), v8::internal::RegExpGlobalExecRunner::FetchNext(), and v8::internal::RegExpGlobalExecRunner::RegExpGlobalExecRunner().
MatchForCallFromJs()
int32_t v8::internal::ExperimentalRegExp::MatchForCallFromJs (Address subject, int32_t start_position, Address input_start, Address input_end, int * output_registers, int32_t output_register_count, RegExp::CallOrigin call_origin, Isolate * isolate, Address regexp_data) [static]
Definition at line 196 of file experimental.cc.
                                                                         {
  DCHECK(v8_flags.enable_experimental_regexp_engine);
  DCHECK_NOT_NULL(isolate);
  DCHECK_NOT_NULL(output_registers);
  DCHECK(call_origin == RegExp::CallOrigin::kFromJs);
  DisallowGarbageCollection no_gc;
  DisallowJavascriptExecution no_js(isolate);
  DisallowHandleAllocation no_handles;
  DisallowHandleDereference no_deref;
  Tagged<String> subject_string = Cast<String>(Tagged<Object>(subject));
  Tagged<IrRegExpData> regexp_data_obj =
      Cast<IrRegExpData>(Tagged<Object>(regexp_data));
  return ExecRaw(isolate, RegExp::kFromJs, regexp_data_obj, subject_string,
                 output_registers, output_register_count, start_position);
}
References v8::internal::call_origin, v8::internal::DCHECK(), DCHECK_NOT_NULL, ExecRaw(), v8::internal::RegExp::kFromJs, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::v8_flags.
OneshotExec()
std::optional< int > v8::internal::ExperimentalRegExp::OneshotExec (Isolate * isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject, int index, int32_t * result_offsets_vector, uint32_t result_offsets_vector_length) [static]
Definition at line 289 of file experimental.cc.
                                                                           {
  DCHECK(v8_flags.enable_experimental_regexp_engine_on_excessive_backtracks);
  do {
    int num_matches =
        OneshotExecRaw(isolate, regexp_data, subject, result_offsets_vector,
                       result_offsets_vector_length, subject_index);
    if (num_matches > 0) {
      DCHECK_LE(num_matches * JSRegExp::RegistersForCaptureCount(
                                  regexp_data->capture_count()),
                result_offsets_vector_length);
      return num_matches;
    } else if (num_matches == 0) {
      return num_matches;
    } else {
      DCHECK_LT(num_matches, 0);
      if (num_matches == RegExp::kInternalRegExpRetry) {
        // Re-run execution.
        continue;
      }
      DCHECK(isolate->has_exception());
      return {};
    }
  } while (true);
  UNREACHABLE();
}
References v8::internal::DCHECK(), DCHECK_LE, DCHECK_LT, v8::internal::Isolate::has_exception(), v8::internal::RegExp::kInternalRegExpRetry, OneshotExecRaw(), v8::internal::JSRegExp::RegistersForCaptureCount(), v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by v8::internal::RegExp::ExperimentalOneshotExec(), and v8::internal::RegExpImpl::IrregexpExec().
OneshotExecRaw()
int32_t v8::internal::ExperimentalRegExp::OneshotExecRaw (Isolate * isolate, DirectHandle< IrRegExpData > regexp_data, DirectHandle< String > subject, int32_t * output_registers, int32_t output_register_count, int32_t subject_index) [static]
Definition at line 267 of file experimental.cc.
                                                          {
  CHECK(v8_flags.enable_experimental_regexp_engine_on_excessive_backtracks);
  if (v8_flags.trace_experimental_regexp_engine) {
    StdoutStream{} << "Experimental execution (oneshot) of regexp "
                   << regexp_data->source() << std::endl;
  }
  std::optional<CompilationResult> compilation_result =
      CompileImpl(isolate, regexp_data);
  if (!compilation_result.has_value()) return RegExp::kInternalRegExpException;
  DisallowGarbageCollection no_gc;
  return ExecRawImpl(isolate, RegExp::kFromRuntime,
                     *compilation_result->bytecode, *subject,
                     regexp_data->capture_count(), output_registers,
                     output_register_count, subject_index);
}
References CHECK, v8::internal::anonymous_namespace{experimental.cc}::CompileImpl(), v8::internal::anonymous_namespace{experimental.cc}::ExecRawImpl(), v8::internal::RegExp::kFromRuntime, v8::internal::RegExp::kInternalRegExpException, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::v8_flags.
Referenced by v8::internal::RegExpGlobalExecRunner::FetchNext(), and OneshotExec().
Member Data Documentation
kSupportsUnicode
constexpr bool v8::internal::ExperimentalRegExp::kSupportsUnicode = false [static], [constexpr]
Definition at line 63 of file experimental.h.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::AreSuitableFlags(), and v8::internal::anonymous_namespace{experimental-interpreter.cc}::NfaInterpreter< Character >::FindMatches().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/experimental/experimental.h
/mnt/V8SourceCode/src/regexp/experimental/experimental.cc