v8::internal::WasmCapiFunction Class Reference
#include <wasm-objects.h>
Public Member Functions
const wasm::CanonicalSig * sig () const
bool MatchesSignature (wasm::CanonicalTypeIndex other_canonical_sig_index) const
OBJECT_CONSTRUCTORS (WasmCapiFunction, JSFunction)
Static Public Member Functions
static bool IsWasmCapiFunction (Tagged< Object > object)
static DirectHandle< WasmCapiFunction > New (Isolate *isolate, Address call_target, DirectHandle< Foreign > embedder_data, wasm::CanonicalTypeIndex sig_index, const wasm::CanonicalSig *sig)
Additional Inherited Members
Detailed Description
Definition at line 1042 of file wasm-objects.h.
Member Function Documentation
IsWasmCapiFunction()
bool v8::internal::WasmCapiFunction::IsWasmCapiFunction (Tagged< Object > object) [static]
Definition at line 2917 of file wasm-objects.cc.
                                                               {
  if (!IsJSFunction(object)) return false;
  Tagged<JSFunction> js_function = Cast<JSFunction>(object);
  // TODO(jkummerow): Enable this when there is a JavaScript wrapper
  // able to call this function.
  // if (js_function->code()->kind() != CodeKind::WASM_TO_CAPI_FUNCTION) {
  // return false;
  // }
  // DCHECK(js_function->shared()->HasWasmCapiFunctionData(
  // GetCurrentIsolateForSandbox()));
  // return true;
  return js_function->shared()->HasWasmCapiFunctionData(
      GetCurrentIsolateForSandbox());
}
References v8::internal::GetCurrentIsolateForSandbox().
Referenced by v8::internal::CastTraits< WasmCapiFunction >::AllowFrom(), v8::internal::wasm::ResolvedWasmImport::ComputeKind(), v8::internal::WasmExternalFunction::IsWasmExternalFunction(), v8::internal::wasm::JSToWasmObject(), and v8::internal::WasmTableObject::SetFunctionTableEntry().
MatchesSignature()
bool v8::internal::WasmCapiFunction::MatchesSignature (wasm::CanonicalTypeIndex other_canonical_sig_index) const
Definition at line 2735 of file wasm-objects.cc.
                                                            {
#if DEBUG
  // TODO(14034): Change this if indexed types are allowed.
  for (wasm::CanonicalValueType type : this->sig()->all()) {
    CHECK(!type.has_index());
  }
#endif
  // TODO(14034): Check for subtyping instead if C API functions can define
  // signature supertype.
  return shared()->wasm_capi_function_data()->sig_index() ==
         other_canonical_sig_index;
}
References all, CHECK, sig(), and v8::internal::tracing::type.
New()
DirectHandle< WasmCapiFunction > v8::internal::WasmCapiFunction::New (Isolate * isolate, Address call_target, DirectHandle< Foreign > embedder_data, wasm::CanonicalTypeIndex sig_index, const wasm::CanonicalSig * sig) [static]
Definition at line 2932 of file wasm-objects.cc.
                                                                   {
  // TODO(jkummerow): Install a JavaScript wrapper. For now, calling
  // these functions directly is unsupported; they can only be called
  // from Wasm code.
  // To support simulator builds, we potentially have to redirect the
  // call target (which is an address pointing into the C++ binary).
  call_target = ExternalReference::Create(call_target).address();
  DirectHandle<Map> rtt = isolate->factory()->wasm_func_ref_map();
  DirectHandle<WasmCapiFunctionData> fun_data =
      isolate->factory()->NewWasmCapiFunctionData(
          call_target, embedder_data, BUILTIN_CODE(isolate, Illegal), rtt,
          sig_index, sig);
  DirectHandle<SharedFunctionInfo> shared =
      isolate->factory()->NewSharedFunctionInfoForWasmCapiFunction(fun_data);
  DirectHandle<JSFunction> result =
      Factory::JSFunctionBuilder{isolate, shared, isolate->native_context()}
          .Build();
  fun_data->internal()->set_external(*result);
  return Cast<WasmCapiFunction>(result);
}
References v8::internal::ExternalReference::address(), BUILTIN_CODE, v8::internal::ExternalReference::Create(), v8::internal::Isolate::factory(), v8::internal::Isolate::native_context(), v8::base::internal::result, and sig().
Referenced by wasm::anonymous_namespace{c-api.cc}::make_func().
OBJECT_CONSTRUCTORS()
v8::internal::WasmCapiFunction::OBJECT_CONSTRUCTORS (WasmCapiFunction , JSFunction)
sig()
const wasm::CanonicalSig * v8::internal::WasmCapiFunction::sig () const
Definition at line 2416 of file wasm-objects.cc.
                                                    {
  return shared()->wasm_capi_function_data()->sig();
}
Referenced by MatchesSignature(), and New().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc