v8::internal::wasm::AdaptiveMap< Value > Class Template Reference
#include <wasm-module.h>
Public Member Functions
AdaptiveMap ()
AdaptiveMap (const AdaptiveMap &)=delete
AdaptiveMap & operator= (const AdaptiveMap &)=delete
AdaptiveMap (AdaptiveMap &&other) V8_NOEXCEPT
AdaptiveMap & operator= (AdaptiveMap &&other) V8_NOEXCEPT
void FinishInitialization ()
bool is_set () const
void Put (uint32_t key, const Value &value)
void Put (uint32_t key, Value &&value)
const Value * Get (uint32_t key) const
bool Has (uint32_t key) const
size_t EstimateCurrentMemoryConsumption () const
Static Public Attributes
static constexpr uint32_t kMaxKey = 10'000'000
Private Types
enum Mode { kDense
, kSparse
, kInitializing
 }
using MapType = std::map< uint32_t, Value >
Private Attributes
Mode mode_ {kInitializing}
std::vector< Value > vector_
std::unique_ptr< MapType > map_
Static Private Attributes
static constexpr uint32_t kLoadFactor = 4
Detailed Description
template<class Value>
class v8::internal::wasm::AdaptiveMap< Value >
Definition at line 303 of file wasm-module.h.
Member Typedef Documentation
MapType
template<class Value >
using v8::internal::wasm::AdaptiveMap< Value >::MapType = std::map<uint32_t, Value> [private]
Definition at line 367 of file wasm-module.h.
Member Enumeration Documentation
Mode
template<class Value >
enum v8::internal::wasm::AdaptiveMap::Mode [private]
Enumerator
kDense
kSparse
kInitializing
Definition at line 368 of file wasm-module.h.
{ kDense, kSparse, kInitializing };
Constructor & Destructor Documentation
AdaptiveMap() [1/3]
template<class Value >
v8::internal::wasm::AdaptiveMap< Value >::AdaptiveMap () [inline]
Definition at line 311 of file wasm-module.h.
: map_(new MapType()) {}
AdaptiveMap() [2/3]
template<class Value >
v8::internal::wasm::AdaptiveMap< Value >::AdaptiveMap (const AdaptiveMap< Value > &) [explicit], [delete]
AdaptiveMap() [3/3]
template<class Value >
v8::internal::wasm::AdaptiveMap< Value >::AdaptiveMap (AdaptiveMap< Value > && other) [inline]
Definition at line 316 of file wasm-module.h.
{ *this = std::move(other); }
Member Function Documentation
EstimateCurrentMemoryConsumption()
template<class Value >
size_t v8::internal::wasm::AdaptiveMap< Value >::EstimateCurrentMemoryConsumption
Definition at line 751 of file wasm-module.cc.
                                                                  {
  UNREACHABLE(); // Explicit implementations below.
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::NamesProvider::EstimateCurrentMemoryConsumption().
FinishInitialization()
template<class Value >
void v8::internal::wasm::AdaptiveMap< Value >::FinishInitialization
Definition at line 63 of file wasm-module.cc.
                                              {
  uint32_t count = 0;
  uint32_t max = 0;
  DCHECK_EQ(mode_, kInitializing);
  for (const auto& entry : *map_) {
    count++;
    max = std::max(max, entry.first);
  }
  if (count >= (max + 1) / kLoadFactor) {
    mode_ = kDense;
    vector_.resize(max + 1);
    for (auto& entry : *map_) {
      vector_[entry.first] = std::move(entry.second);
    }
    map_.reset();
  } else {
    mode_ = kSparse;
  }
}
References DCHECK_EQ.
Referenced by v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeIndirectNameMap(), and v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeNameMapInternal().
Get()
template<class Value >
const Value* v8::internal::wasm::AdaptiveMap< Value >::Get (uint32_t key) const [inline]
Definition at line 341 of file wasm-module.h.
                                       {
    if (mode_ == kDense) {
      if (key >= vector_.size()) return nullptr;
      if (!vector_[key].is_set()) return nullptr;
      return &vector_[key];
    } else {
      DCHECK(mode_ == kSparse || mode_ == kInitializing);
      auto it = map_->find(key);
      if (it == map_->end()) return nullptr;
      return &it->second;
    }
  }
References v8::internal::DCHECK(), and v8::internal::key.
Referenced by v8::internal::wasm::Get(), v8::internal::wasm::LazilyGeneratedNames::Has(), and v8::internal::wasm::LazilyGeneratedNames::LookupFunctionName().
Has()
template<class Value >
bool v8::internal::wasm::AdaptiveMap< Value >::Has (uint32_t key) const [inline]
Definition at line 354 of file wasm-module.h.
                               {
    if (mode_ == kDense) {
      return key < vector_.size() && vector_[key].is_set();
    } else {
      DCHECK(mode_ == kSparse || mode_ == kInitializing);
      return map_->find(key) != map_->end();
    }
  }
References v8::internal::DCHECK(), and v8::internal::key.
is_set()
template<class Value >
bool v8::internal::wasm::AdaptiveMap< Value >::is_set () const [inline]
Definition at line 327 of file wasm-module.h.
{ return mode_ != kInitializing; }
Referenced by v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeIndirectNameMap(), and v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeNameMap().
operator=() [1/2]
template<class Value >
AdaptiveMap& v8::internal::wasm::AdaptiveMap< Value >::operator= (AdaptiveMap< Value > && other) [inline]
Definition at line 318 of file wasm-module.h.
                                                          {
    mode_ = other.mode_;
    vector_.swap(other.vector_);
    map_.swap(other.map_);
    return *this;
  }
operator=() [2/2]
template<class Value >
AdaptiveMap& v8::internal::wasm::AdaptiveMap< Value >::operator= (const AdaptiveMap< Value > &) [delete]
Put() [1/2]
template<class Value >
void v8::internal::wasm::AdaptiveMap< Value >::Put (uint32_t key, const Value & value) [inline]
Definition at line 329 of file wasm-module.h.
                                             {
    DCHECK(mode_ == kInitializing);
    DCHECK_LE(key, kMaxKey);
    map_->insert(std::make_pair(key, value));
  }
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::key, and v8::internal::value.
Referenced by v8::internal::wasm::LazilyGeneratedNames::AddForTesting(), v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeIndirectNameMap(), and v8::internal::wasm::anonymous_namespace{module-decoder.cc}::DecodeNameMapInternal().
Put() [2/2]
template<class Value >
void v8::internal::wasm::AdaptiveMap< Value >::Put (uint32_t key, Value && value) [inline]
Definition at line 335 of file wasm-module.h.
                                        {
    DCHECK(mode_ == kInitializing);
    DCHECK_LE(key, kMaxKey);
    map_->insert(std::make_pair(key, std::move(value)));
  }
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::key, and v8::internal::value.
Member Data Documentation
kLoadFactor
template<class Value >
constexpr uint32_t v8::internal::wasm::AdaptiveMap< Value >::kLoadFactor = 4 [static], [constexpr], [private]
Definition at line 366 of file wasm-module.h.
kMaxKey
template<class Value >
constexpr uint32_t v8::internal::wasm::AdaptiveMap< Value >::kMaxKey = 10'000'000 [static], [constexpr]
Definition at line 308 of file wasm-module.h.
map_
template<class Value >
std::unique_ptr<MapType> v8::internal::wasm::AdaptiveMap< Value >::map_ [private]
Definition at line 372 of file wasm-module.h.
mode_
template<class Value >
Mode v8::internal::wasm::AdaptiveMap< Value >::mode_ {kInitializing} [private]
Definition at line 370 of file wasm-module.h.
vector_
template<class Value >
std::vector<Value> v8::internal::wasm::AdaptiveMap< Value >::vector_ [private]
Definition at line 371 of file wasm-module.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-module.h
/mnt/V8SourceCode/src/wasm/wasm-module.cc