v8::base::OS::MemoryMappedFile Class Reference
#include <platform.h>
Public Types
enum class FileMode { kReadOnly
, kReadWrite
 }
Public Member Functions
virtual ~MemoryMappedFile ()=default
virtual void * memory () const =0
virtual size_t size () const =0
Static Public Member Functions
static MemoryMappedFile * open (const char *name, FileMode mode=FileMode::kReadWrite)
static MemoryMappedFile * create (const char *name, size_t size, void *initial)
Detailed Description
Definition at line 256 of file platform.h.
Member Enumeration Documentation
FileMode
enum v8::base::OS::MemoryMappedFile::FileMode [strong]
Enumerator
kReadOnly
kReadWrite
Definition at line 258 of file platform.h.
{ kReadOnly, kReadWrite };
Constructor & Destructor Documentation
 MemoryMappedFile()
virtual v8::base::OS::MemoryMappedFile::~MemoryMappedFile () [virtual], [default]
Member Function Documentation
create()
OS::MemoryMappedFile * v8::base::OS::MemoryMappedFile::create (const char * name, size_t size, void * initial) [static]
Definition at line 854 of file platform-posix.cc.
                                                                               {
  if (FILE* file = fopen(name, "w+")) {
    if (size == 0) return new PosixMemoryMappedFile(file, nullptr, 0);
    size_t result = fwrite(initial, 1, size, file);
    if (result == size && !ferror(file)) {
      void* memory = mmap(OS::GetRandomMmapAddr(), result,
                          PROT_READ | PROT_WRITE, MAP_SHARED, fileno(file), 0);
      if (memory != MAP_FAILED) {
        return new PosixMemoryMappedFile(file, memory, result);
      }
    }
    fclose(file);
  }
  return nullptr;
}
References file(), v8::base::OS::GetRandomMmapAddr(), name, v8::base::OS::PosixMemoryMappedFile, v8::base::internal::result, and size().
Referenced by v8::Shell::MapCounters().
memory()
virtual void* v8::base::OS::MemoryMappedFile::memory () const [pure virtual]
Implemented in v8::base::PosixMemoryMappedFile, v8::base::Win32MemoryMappedFile, v8::base::StarboardMemoryMappedFile, and v8::base::PosixMemoryMappedFile.
Referenced by open().
open()
OS::MemoryMappedFile * v8::base::OS::MemoryMappedFile::open (const char * name, FileMode mode = FileMode::kReadWrite) [static]
Definition at line 823 of file platform-posix.cc.
                                                                {
  const char* fopen_mode = (mode == FileMode::kReadOnly) ? "r" : "r+";
  struct stat statbuf;
  // Make sure path exists and is not a directory.
  if (stat(name, &statbuf) == 0 && !S_ISDIR(statbuf.st_mode)) {
    if (FILE* file = fopen(name, fopen_mode)) {
      if (fseek(file, 0, SEEK_END) == 0) {
        long size = ftell(file); // NOLINT(runtime/int)
        if (size == 0) return new PosixMemoryMappedFile(file, nullptr, 0);
        if (size > 0) {
          int prot = PROT_READ;
          int flags = MAP_PRIVATE;
          if (mode == FileMode::kReadWrite) {
            prot |= PROT_WRITE;
            flags = MAP_SHARED;
          }
          void* const memory =
              mmap(OS::GetRandomMmapAddr(), size, prot, flags, fileno(file), 0);
          if (memory != MAP_FAILED) {
            return new PosixMemoryMappedFile(file, memory, size);
          }
        }
      }
      fclose(file);
    }
  }
  return nullptr;
}
References file(), flags(), v8::base::OS::GetRandomMmapAddr(), kReadOnly, kReadWrite, memory(), mode(), name, v8::base::OS::PosixMemoryMappedFile, and size().
Referenced by v8::Shell::ReadFileData().
size()
virtual size_t v8::base::OS::MemoryMappedFile::size () const [pure virtual]
Implemented in v8::base::PosixMemoryMappedFile, v8::base::Win32MemoryMappedFile, v8::base::StarboardMemoryMappedFile, and v8::base::PosixMemoryMappedFile.
Referenced by open().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/platform.h
/mnt/V8SourceCode/src/base/platform/platform-posix.cc
/mnt/V8SourceCode/src/base/platform/platform-starboard.cc
/mnt/V8SourceCode/src/base/platform/platform-win32.cc
/mnt/V8SourceCode/src/base/platform/platform-zos.cc