v8::internal::compiler::TupleType Class Reference
#include <turbofan-types.h>
Public Member Functions
int Arity () const
Type Element (int i) const
void InitElement (int i, Type type)
Private Member Functions
TupleType (int length, Zone *zone)
Static Private Member Functions
static TupleType * New (int length, Zone *zone)
Private Attributes
friend Type
friend Zone
Additional Inherited Members
Detailed Description
Definition at line 695 of file turbofan-types.h.
Constructor & Destructor Documentation
TupleType()
v8::internal::compiler::TupleType::TupleType (int length, Zone * zone) [inline], [private]
Definition at line 706 of file turbofan-types.h.
: StructuralType(kTuple, length, zone) {}
Member Function Documentation
Arity()
int v8::internal::compiler::TupleType::Arity () const [inline]
Definition at line 697 of file turbofan-types.h.
{ return this->Length(); }
References v8::internal::compiler::StructuralType::Length().
Element()
Type v8::internal::compiler::TupleType::Element (int i) const [inline]
Definition at line 698 of file turbofan-types.h.
{ return this->Get(i); }
References v8::internal::compiler::StructuralType::Get().
InitElement()
void v8::internal::compiler::TupleType::InitElement (int i, Type type) [inline]
Definition at line 700 of file turbofan-types.h.
{ this->Set(i, type); }
References v8::internal::compiler::StructuralType::Set(), and v8::internal::tracing::type.
New()
static TupleType* v8::internal::compiler::TupleType::New (int length, Zone * zone) [inline], [static], [private]
Definition at line 708 of file turbofan-types.h.
                                                {
    return zone->New<TupleType>(length, zone);
  }
References v8::internal::length, and v8::internal::Zone::New().
Member Data Documentation
Type
friend v8::internal::compiler::TupleType::Type [private]
Definition at line 703 of file turbofan-types.h.
Zone
friend v8::internal::compiler::TupleType::Zone [private]
Definition at line 704 of file turbofan-types.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turbofan-types.h