v8::HeapSnapshot Class Reference
HeapSnapshots record the state of the JS heap at some moment.
#include <v8-profiler.h>
Public Types
enum SerializationFormat { kJSON = 0
 }
Public Member Functions
const HeapGraphNode * GetRoot () const
Returns the root node of the heap graph.
const HeapGraphNode * GetNodeById (SnapshotObjectId id) const
Returns a node by its id.
int GetNodesCount () const
Returns total nodes count in the snapshot.
const HeapGraphNode * GetNode (int index) const
Returns a node by index.
SnapshotObjectId GetMaxSnapshotJSObjectId () const
Returns a max seen JS object Id.
void Delete ()
Deletes the snapshot and removes it from HeapProfiler's list.
void Serialize (OutputStream *stream, SerializationFormat format=kJSON) const
Prepare a serialized representation of the snapshot.
Detailed Description
HeapSnapshots record the state of the JS heap at some moment.
Definition at line 638 of file v8-profiler.h.
Member Enumeration Documentation
SerializationFormat
enum v8::HeapSnapshot::SerializationFormat
Enumerator
kJSON
Definition at line 640 of file v8-profiler.h.
                           {
    kJSON = 0 // See format description near 'Serialize' method.
  };
Member Function Documentation
Delete()
void v8::HeapSnapshot::Delete ()
Deletes the snapshot and removes it from HeapProfiler's list.
All pointers to nodes, edges and paths previously returned become invalid.
Definition at line 11672 of file api.cc.
                          {
  i::Isolate* i_isolate = ToInternal(this)->profiler()->isolate();
  if (i_isolate->heap()->heap_profiler()->GetSnapshotsCount() > 1 ||
      i_isolate->heap()->heap_profiler()->IsTakingSnapshot()) {
    ToInternal(this)->Delete();
  } else {
    // If this is the last snapshot, clean up all accessory data as well.
    i_isolate->heap()->heap_profiler()->DeleteAllSnapshots();
  }
}
References v8::internal::HeapProfiler::DeleteAllSnapshots(), v8::internal::HeapProfiler::GetSnapshotsCount(), v8::internal::Isolate::heap(), v8::internal::Heap::heap_profiler(), v8::internal::HeapProfiler::IsTakingSnapshot(), and v8::ToInternal().
GetMaxSnapshotJSObjectId()
SnapshotObjectId v8::HeapSnapshot::GetMaxSnapshotJSObjectId () const
Returns a max seen JS object Id.
Definition at line 11701 of file api.cc.
                                                              {
  return ToInternal(this)->max_snapshot_js_object_id();
}
References v8::ToInternal().
GetNode()
const HeapGraphNode * v8::HeapSnapshot::GetNode (int index) const
Returns a node by index.
Definition at line 11696 of file api.cc.
                                                          {
  return reinterpret_cast<const HeapGraphNode*>(
      &ToInternal(this)->entries().at(index));
}
References v8::internal::index, and v8::ToInternal().
GetNodeById()
const HeapGraphNode * v8::HeapSnapshot::GetNodeById (SnapshotObjectId id) const
Returns a node by its id.
Definition at line 11687 of file api.cc.
                                                                        {
  return reinterpret_cast<const HeapGraphNode*>(
      ToInternal(this)->GetEntryById(id));
}
References v8::ToInternal().
GetNodesCount()
int v8::HeapSnapshot::GetNodesCount () const
Returns total nodes count in the snapshot.
Definition at line 11692 of file api.cc.
                                      {
  return static_cast<int>(ToInternal(this)->entries().size());
}
References v8::ToInternal().
GetRoot()
const HeapGraphNode * v8::HeapSnapshot::GetRoot () const
Returns the root node of the heap graph.
Definition at line 11683 of file api.cc.
                                                 {
  return reinterpret_cast<const HeapGraphNode*>(ToInternal(this)->root());
}
References v8::ToInternal().
Serialize()
void v8::HeapSnapshot::Serialize (OutputStream * stream, HeapSnapshot::SerializationFormat format = kJSON) const
Prepare a serialized representation of the snapshot.
The result is written into the stream provided in chunks of specified size. The total length of the serialized snapshot is unknown in advance, it can be roughly equal to JS heap size (that means, it can be really big - tens of megabytes).
For the JSON format, heap contents are represented as an object with the following structure:
{ snapshot: { title: `...`, uid: nnn, meta: { meta-info }, node_count: nnn, edge_count: nnn }, nodes: [nodes array], edges: [edges array], strings: [strings array] }
Nodes reference strings, other nodes, and edges by their indexes in corresponding arrays.
Definition at line 11705 of file api.cc.
                                                                           {
  Utils::ApiCheck(format == kJSON, "v8::HeapSnapshot::Serialize",
                  "Unknown serialization format");
  Utils::ApiCheck(stream->GetChunkSize() > 0, "v8::HeapSnapshot::Serialize",
                  "Invalid stream chunk size");
  i::HeapSnapshotJSONSerializer serializer(ToInternal(this));
  serializer.Serialize(stream);
}
References v8::Utils::ApiCheck(), v8::base::format, v8::OutputStream::GetChunkSize(), kJSON, v8::internal::HeapSnapshotJSONSerializer::Serialize(), and v8::ToInternal().
Referenced by v8_inspector::V8HeapProfilerAgentImpl::takeHeapSnapshotNow().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-profiler.h
/mnt/V8SourceCode/src/api/api.cc