v8::internal::CodeRangeAddressHint Class Reference
#include <code-range.h>
Public Member Functions
V8_EXPORT_PRIVATE Address GetAddressHint (size_t code_range_size, size_t alignment)
V8_EXPORT_PRIVATE void NotifyFreedCodeRange (Address code_range_start, size_t code_range_size)
Private Attributes
base::Mutex mutex_
std::unordered_map< size_t, std::vector< Address > > recently_freed_
Detailed Description
Definition at line 22 of file code-range.h.
Member Function Documentation
GetAddressHint()
Address v8::internal::CodeRangeAddressHint::GetAddressHint (size_t code_range_size, size_t alignment)
Definition at line 35 of file code-range.cc.
                                                                        {
  base::MutexGuard guard(&mutex_);
  Address result = 0;
  auto it = recently_freed_.find(code_range_size);
  // No recently freed region has been found, try to provide a hint for placing
  // a code region.
  if (it == recently_freed_.end() || it->second.empty()) {
    return RoundUp(FUNCTION_ADDR(&FunctionInStaticBinaryForAddressHint),
                   allocate_page_size);
  }
  result = it->second.back();
  CHECK(IsAligned(result, allocate_page_size));
  it->second.pop_back();
  return result;
}
References CHECK, FUNCTION_ADDR, v8::internal::anonymous_namespace{code-range.cc}::FunctionInStaticBinaryForAddressHint(), IsAligned(), mutex_, recently_freed_, v8::base::internal::result, and RoundUp().
NotifyFreedCodeRange()
void v8::internal::CodeRangeAddressHint::NotifyFreedCodeRange (Address code_range_start, size_t code_range_size)
Definition at line 54 of file code-range.cc.
                                                                        {
  base::MutexGuard guard(&mutex_);
  recently_freed_[code_range_size].push_back(code_range_start);
}
References mutex_, and recently_freed_.
Member Data Documentation
mutex_
base::Mutex v8::internal::CodeRangeAddressHint::mutex_ [private]
Definition at line 37 of file code-range.h.
Referenced by GetAddressHint(), and NotifyFreedCodeRange().
recently_freed_
std::unordered_map<size_t, std::vector<Address> > v8::internal::CodeRangeAddressHint::recently_freed_ [private]
Definition at line 42 of file code-range.h.
Referenced by GetAddressHint(), and NotifyFreedCodeRange().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/code-range.h
/mnt/V8SourceCode/src/heap/code-range.cc