wasm::StoreImpl Class Reference
#include <c-api.h>
Public Member Functions
~StoreImpl ()
void destroy ()
v8::Isolate * isolate () const
i::Isolate * i_isolate () const
v8::Local< v8::Context > context () const
void SetHostInfo (i::DirectHandle< i::Object > object, void *info, void(*finalizer)(void *))
void * GetHostInfo (i::DirectHandle< i::Object > key)
Static Public Member Functions
static StoreImpl * get (i::Isolate *isolate)
Private Member Functions
StoreImpl ()=default
Private Attributes
v8::Isolate::CreateParams create_params_
v8::Isolate * isolate_ = nullptr
v8::Eternal< v8::Context > context_
i::IndirectHandle< i::JSWeakMap > host_info_map_
Friends
own< Store > Store::make (Engine *)
Detailed Description
Definition at line 32 of file c-api.h.
Constructor & Destructor Documentation
 StoreImpl()
wasm::StoreImpl::~StoreImpl ()
Definition at line 471 of file c-api.cc.
                      {
  {
    v8::Isolate::Scope isolate_scope(isolate_);
#ifdef DEBUG
    i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate_);
    i_isolate->heap()->PreciseCollectAllGarbage(
        i::GCFlag::kForced, i::GarbageCollectionReason::kTesting,
        v8::kNoGCCallbackFlags);
#endif
    context()->Exit();
  }
  isolate_->Dispose();
  delete create_params_.array_buffer_allocator;
}
References v8::Isolate::CreateParams::array_buffer_allocator, context(), create_params_, v8::Isolate::Dispose(), v8::Context::Exit(), v8::internal::Isolate::heap(), i_isolate(), isolate_, v8::internal::kForced, v8::kNoGCCallbackFlags, and v8::internal::Heap::PreciseCollectAllGarbage().
StoreImpl()
wasm::StoreImpl::StoreImpl () [private], [default]
Member Function Documentation
context()
v8::Local<v8::Context> wasm::StoreImpl::context () const [inline]
Definition at line 43 of file c-api.h.
{ return context_.Get(isolate_); }
References context_, v8::Eternal< T >::Get(), and isolate_.
Referenced by ~StoreImpl().
destroy()
void wasm::StoreImpl::destroy ()
Definition at line 469 of file c-api.cc.
{ delete this; }
get()
static StoreImpl* wasm::StoreImpl::get (i::Isolate * isolate) [inline], [static]
Definition at line 45 of file c-api.h.
                                           {
    return static_cast<StoreImpl*>(
        reinterpret_cast<v8::Isolate*>(isolate)->GetData(0));
  }
References isolate().
GetHostInfo()
void * wasm::StoreImpl::GetHostInfo (i::DirectHandle< i::Object > key)
Definition at line 515 of file c-api.cc.
                                                       {
  PtrComprCageAccessScope ptr_compr_cage_access_scope(i_isolate());
  i::Tagged<i::Object> raw =
      i::Cast<i::EphemeronHashTable>(host_info_map_->table())->Lookup(key);
  if (IsTheHole(raw, i_isolate())) return nullptr;
  return i::Cast<i::Managed<ManagedData>>(raw)->raw()->info;
}
References host_info_map_, i_isolate(), and v8::internal::key.
Referenced by wasm::RefImpl< Ref, JSType >::get_host_info().
i_isolate()
i::Isolate* wasm::StoreImpl::i_isolate () const [inline]
Definition at line 39 of file c-api.h.
                              {
    return reinterpret_cast<i::Isolate*>(isolate_);
  }
References isolate_.
Referenced by GetHostInfo(), wasm::RefImpl< Ref, JSType >::isolate(), wasm::RefImpl< Ref, JSType >::make(), SetHostInfo(), and ~StoreImpl().
isolate()
v8::Isolate* wasm::StoreImpl::isolate () const [inline]
Definition at line 38 of file c-api.h.
{ return isolate_; }
References isolate_.
Referenced by get(), wasm::RefImpl< Ref, JSType >::make(), and SetHostInfo().
SetHostInfo()
void wasm::StoreImpl::SetHostInfo (i::DirectHandle< i::Object > object, void * info, void(*)(void *) finalizer)
Definition at line 500 of file c-api.cc.
                                                      {
  v8::Isolate::Scope isolate_scope(isolate());
  i::HandleScope scope(i_isolate());
  // Ideally we would specify the total size kept alive by {info} here,
  // but all we get from the embedder is a {void*}, so our best estimate
  // is the size of the metadata.
  size_t estimated_size = sizeof(ManagedData);
  i::DirectHandle<i::Object> wrapper = i::Managed<ManagedData>::From(
      i_isolate(), estimated_size,
      std::make_shared<ManagedData>(info, finalizer));
  int32_t hash = i::Object::GetOrCreateHash(*object, i_isolate()).value();
  i::JSWeakCollection::Set(host_info_map_, object, wrapper, hash);
}
References v8::internal::Managed< CppType >::From(), v8::internal::Object::GetOrCreateHash(), host_info_map_, i_isolate(), isolate(), v8::internal::JSWeakCollection::Set(), and v8::internal::Tagged< Smi >::value().
Referenced by wasm::RefImpl< Ref, JSType >::set_host_info().
Friends And Related Function Documentation
Store::make
own<Store> Store::make (Engine *) [friend]
Member Data Documentation
context_
v8::Eternal<v8::Context> wasm::StoreImpl::context_ [private]
Definition at line 61 of file c-api.h.
Referenced by context().
create_params_
v8::Isolate::CreateParams wasm::StoreImpl::create_params_ [private]
Definition at line 59 of file c-api.h.
Referenced by ~StoreImpl().
host_info_map_
i::IndirectHandle<i::JSWeakMap> wasm::StoreImpl::host_info_map_ [private]
Definition at line 62 of file c-api.h.
Referenced by GetHostInfo(), and SetHostInfo().
isolate_
v8::Isolate* wasm::StoreImpl::isolate_ = nullptr [private]
Definition at line 60 of file c-api.h.
Referenced by context(), i_isolate(), isolate(), and ~StoreImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/c-api.h
/mnt/V8SourceCode/src/wasm/c-api.cc