v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next > Class Template Reference
#include <load-store-simplification-reducer.h>
Public Member Functions
OpIndex REDUCE() Load (OpIndex base, OptionalOpIndex index, LoadOp::Kind kind, MemoryRepresentation loaded_rep, RegisterRepresentation result_rep, int32_t offset, uint8_t element_size_log2)
OpIndex REDUCE() Store (OpIndex base, OptionalOpIndex index, OpIndex value, StoreOp::Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset, uint8_t element_size_log2, bool maybe_initializing_or_transitioning, IndirectPointerTag maybe_indirect_pointer_tag)
OpIndex REDUCE() AtomicWord32Pair (V< WordPtr > base, OptionalV< WordPtr > index, OptionalV< Word32 > value_low, OptionalV< Word32 > value_high, OptionalV< Word32 > expected_low, OptionalV< Word32 > expected_high, AtomicWord32PairOp::Kind kind, int32_t offset)
Private Member Functions
bool CanEncodeOffset (int32_t offset, bool tagged_base) const
bool CanEncodeAtomic (OptionalOpIndex index, uint8_t element_size_log2, int32_t offset) const
void SimplifyLoadStore (OpIndex &base, OptionalOpIndex &index, LoadOp::Kind &kind, int32_t &offset, uint8_t &element_size_log2)
Private Attributes
OperationMatcher matcher_ {__ output_graph()}
Additional Inherited Members
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >
Definition at line 60 of file load-store-simplification-reducer.h.
Member Function Documentation
AtomicWord32Pair()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::AtomicWord32Pair (V< WordPtr > base, OptionalV< WordPtr > index, OptionalV< Word32 > value_low, OptionalV< Word32 > value_high, OptionalV< Word32 > expected_low, OptionalV< Word32 > expected_high, AtomicWord32PairOp::Kind kind, int32_t offset) [inline]
Definition at line 101 of file load-store-simplification-reducer.h.
                                                   {
    if (kind == AtomicWord32PairOp::Kind::kStore ||
        kind == AtomicWord32PairOp::Kind::kLoad) {
      if (!index.valid()) {
        index = __ IntPtrConstant(offset);
        offset = 0;
      } else if (offset != 0) {
        index = __ WordPtrAdd(index.value(), offset);
        offset = 0;
      }
    }
    return Next::ReduceAtomicWord32Pair(base, index, value_low, value_high,
                                        expected_low, expected_high, kind,
                                        offset);
  }
References __, v8::internal::index, v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::turboshaft::AtomicWord32PairOp::kLoad, and v8::internal::compiler::turboshaft::AtomicWord32PairOp::kStore.
CanEncodeAtomic()
template<class Next >
bool v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::CanEncodeAtomic (OptionalOpIndex index, uint8_t element_size_log2, int32_t offset) const [inline], [private]
Definition at line 135 of file load-store-simplification-reducer.h.
                                             {
    if (element_size_log2 != 0) return false;
    return !(index.has_value() && offset != 0);
  }
References v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::SimplifyLoadStore().
CanEncodeOffset()
template<class Next >
bool v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::CanEncodeOffset (int32_t offset, bool tagged_base) const [inline], [private]
Definition at line 124 of file load-store-simplification-reducer.h.
                                                               {
    // If the base is tagged we also need to subtract the kHeapObjectTag
    // eventually.
    const int32_t min = kMinOffset + (tagged_base ? kHeapObjectTag : 0);
    if (min <= offset && offset <= kMaxOffset) {
      DCHECK(LoadOp::OffsetIsValid(offset, tagged_base));
      return true;
    }
    return false;
  }
References v8::internal::DCHECK(), v8::internal::kHeapObjectTag, v8::internal::compiler::turboshaft::LoadStoreSimplificationConfiguration::kMaxOffset, v8::internal::compiler::turboshaft::LoadStoreSimplificationConfiguration::kMinOffset, and v8::internal::compiler::turboshaft::LoadOp::OffsetIsValid().
Referenced by v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::SimplifyLoadStore().
Load()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::Load (OpIndex base, OptionalOpIndex index, LoadOp::Kind kind, MemoryRepresentation loaded_rep, RegisterRepresentation result_rep, int32_t offset, uint8_t element_size_log2) [inline]
Definition at line 65 of file load-store-simplification-reducer.h.
                                                  {
    SimplifyLoadStore(base, index, kind, offset, element_size_log2);
    return Next::ReduceLoad(base, index, kind, loaded_rep, result_rep, offset,
                            element_size_log2);
  }
References v8::internal::index, and v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::SimplifyLoadStore().
SimplifyLoadStore()
template<class Next >
void v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::SimplifyLoadStore (OpIndex & base, OptionalOpIndex & index, LoadOp::Kind & kind, int32_t & offset, uint8_t & element_size_log2) [inline], [private]
Definition at line 141 of file load-store-simplification-reducer.h.
                                                     {
    if (element_size_log2 > kMaxElementSizeLog2) {
      DCHECK(index.valid());
      index = __ WordPtrShiftLeft(index.value(), element_size_log2);
      element_size_log2 = 0;
    }
    if (kNeedsUntaggedBase) {
      if (kind.tagged_base) {
        kind.tagged_base = false;
        DCHECK_LE(std::numeric_limits<int32_t>::min() + kHeapObjectTag, offset);
        offset -= kHeapObjectTag;
        base = __ BitcastHeapObjectToWordPtr(base);
      }
    }
    // TODO(nicohartmann@): Remove the case for atomics once crrev.com/c/5237267
    // is ported to x64.
    if (!CanEncodeOffset(offset, kind.tagged_base) ||
        (kind.is_atomic &&
         !CanEncodeAtomic(index, element_size_log2, offset))) {
      if (kind.tagged_base) {
        kind.tagged_base = false;
        DCHECK_LE(std::numeric_limits<int32_t>::min() + kHeapObjectTag, offset);
        offset -= kHeapObjectTag;
        base = __ BitcastHeapObjectToWordPtr(base);
      }
      // If an index is present, the element_size_log2 is changed to zero.
      // So any load follows the form *(base + offset). To simplify
      // instruction selection, both static and dynamic offsets are stored in
      // the index input.
      // As tagged loads result in modifying the offset by -1, those loads are
      // converted into raw loads (above).
      if (!index.has_value() || matcher_.MatchIntegralZero(index.value())) {
        index = __ IntPtrConstant(offset);
        element_size_log2 = 0;
        offset = 0;
      } else if (element_size_log2 != 0) {
        index = __ WordPtrShiftLeft(index.value(), element_size_log2);
        element_size_log2 = 0;
      }
      if (offset != 0) {
        index = __ WordPtrAdd(index.value(), offset);
        offset = 0;
      }
      DCHECK_EQ(offset, 0);
      DCHECK_EQ(element_size_log2, 0);
    }
  }
References __, v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::CanEncodeAtomic(), v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::CanEncodeOffset(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::index, v8::internal::compiler::IntPtrConstant(), v8::internal::compiler::turboshaft::LoadOp::Kind::is_atomic, v8::internal::kHeapObjectTag, v8::internal::compiler::turboshaft::LoadStoreSimplificationConfiguration::kMaxElementSizeLog2, v8::internal::compiler::turboshaft::LoadStoreSimplificationConfiguration::kNeedsUntaggedBase, v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralZero(), and v8::internal::compiler::turboshaft::LoadOp::Kind::tagged_base.
Referenced by v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::Load(), and v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::Store().
Store()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::Store (OpIndex base, OptionalOpIndex index, OpIndex value, StoreOp::Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset, uint8_t element_size_log2, bool maybe_initializing_or_transitioning, IndirectPointerTag maybe_indirect_pointer_tag) [inline]
Definition at line 74 of file load-store-simplification-reducer.h.
                                                                       {
    SimplifyLoadStore(base, index, kind, offset, element_size_log2);
    if (write_barrier != WriteBarrierKind::kNoWriteBarrier &&
        !index.has_value() && __ Get(base).template Is<ConstantOp>()) {
      const ConstantOp& const_base = __ Get(base).template Cast<ConstantOp>();
      if (const_base.IsIntegral() ||
          const_base.kind == ConstantOp::Kind::kSmi) {
        // It never makes sense to have a WriteBarrier for a store to a raw
        // address. We should thus be in unreachable code.
        // The instruction selector / register allocator don't handle this very
        // well, so it's easier to emit an Unreachable rather than emitting a
        // weird store that will never be executed.
        __ Unreachable();
        return OpIndex::Invalid();
      }
    }
    return Next::ReduceStore(base, index, value, kind, stored_rep,
                             write_barrier, offset, element_size_log2,
                             maybe_initializing_or_transitioning,
                             maybe_indirect_pointer_tag);
  }
References __, v8::internal::compiler::turboshaft::Get(), v8::internal::index, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::ConstantOp::IsIntegral(), v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::turboshaft::ConstantOp::kSmi, v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::SimplifyLoadStore(), and v8::internal::value.
Member Data Documentation
matcher_
template<class Next >
OperationMatcher v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::matcher_ {__ output_graph()} [private]
Definition at line 193 of file load-store-simplification-reducer.h.
Referenced by v8::internal::compiler::turboshaft::LoadStoreSimplificationReducer< Next >::SimplifyLoadStore().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/load-store-simplification-reducer.h