v8::internal::compiler::ElementAccessFeedback Class Reference
#include <processed-feedback.h>
Public Types
using TransitionGroup = ZoneVector< MapRef >
Public Member Functions
ElementAccessFeedback (Zone *zone, KeyedAccessMode const &keyed_mode, FeedbackSlotKind slot_kind)
KeyedAccessMode keyed_mode () const
ZoneVector< TransitionGroup > const & transition_groups () const
bool HasOnlyStringMaps (JSHeapBroker *broker) const
void AddGroup (TransitionGroup &&group)
ElementAccessFeedback const & Refine (JSHeapBroker *broker, ZoneVector< MapRef > const &inferred_maps) const
ElementAccessFeedback const & Refine (JSHeapBroker *broker, ZoneRefSet< Map > const &inferred_maps, bool always_keep_group_target=true) const
NamedAccessFeedback const & Refine (JSHeapBroker *broker, NameRef name) const
Private Attributes
KeyedAccessMode const keyed_mode_
ZoneVector< TransitionGroup > transition_groups_
Additional Inherited Members
Detailed Description
Definition at line 130 of file processed-feedback.h.
Member Typedef Documentation
TransitionGroup
using v8::internal::compiler::ElementAccessFeedback::TransitionGroup = ZoneVector<MapRef>
Definition at line 140 of file processed-feedback.h.
Constructor & Destructor Documentation
ElementAccessFeedback()
v8::internal::compiler::ElementAccessFeedback::ElementAccessFeedback (Zone * zone, KeyedAccessMode const & keyed_mode, FeedbackSlotKind slot_kind)
Definition at line 387 of file js-heap-broker.cc.
    : ProcessedFeedback(kElementAccess, slot_kind),
      keyed_mode_(keyed_mode),
      transition_groups_(zone) {
  DCHECK(IsKeyedLoadICKind(slot_kind) || IsKeyedHasICKind(slot_kind) ||
         IsDefineKeyedOwnPropertyInLiteralKind(slot_kind) ||
         IsKeyedStoreICKind(slot_kind) ||
         IsStoreInArrayLiteralICKind(slot_kind) ||
         IsDefineKeyedOwnICKind(slot_kind));
}
References v8::internal::DCHECK(), v8::internal::IsDefineKeyedOwnICKind(), v8::internal::IsDefineKeyedOwnPropertyInLiteralKind(), v8::internal::IsKeyedHasICKind(), v8::internal::IsKeyedLoadICKind(), v8::internal::IsKeyedStoreICKind(), v8::internal::IsStoreInArrayLiteralICKind(), and v8::internal::compiler::ProcessedFeedback::slot_kind().
Member Function Documentation
AddGroup()
void v8::internal::compiler::ElementAccessFeedback::AddGroup (TransitionGroup && group)
Definition at line 909 of file js-heap-broker.cc.
                                                            {
  CHECK(!group.empty());
  transition_groups_.push_back(std::move(group));
#ifdef ENABLE_SLOW_DCHECKS
  // Check that each of the group's maps occurs exactly once in the whole
  // feedback. This implies that "a source is not a target".
  for (MapRef map : group) {
    int count = 0;
    for (TransitionGroup const& some_group : transition_groups()) {
      count +=
          std::count_if(some_group.begin(), some_group.end(),
                        [&](MapRef some_map) { return some_map.equals(map); });
    }
    CHECK_EQ(count, 1);
  }
#endif
}
References CHECK, CHECK_EQ, v8::base::count_if(), transition_groups(), and transition_groups_.
HasOnlyStringMaps()
bool v8::internal::compiler::ElementAccessFeedback::HasOnlyStringMaps (JSHeapBroker * broker) const
Definition at line 400 of file js-heap-broker.cc.
                                                                        {
  for (auto const& group : transition_groups()) {
    for (MapRef map : group) {
      if (!map.IsStringMap()) return false;
    }
  }
  return true;
}
References transition_groups().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess().
keyed_mode()
KeyedAccessMode v8::internal::compiler::ElementAccessFeedback::keyed_mode () const
Definition at line 183 of file js-heap-broker.cc.
                                                        {
  return keyed_mode_;
}
References keyed_mode_.
Referenced by v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfos(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess(), Refine(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), and v8::internal::compiler::JSNativeContextSpecialization::TryRefineElementAccessFeedback().
Refine() [1/3]
NamedAccessFeedback const & v8::internal::compiler::ElementAccessFeedback::Refine (JSHeapBroker * broker, NameRef name) const
Definition at line 204 of file js-heap-broker.cc.
                                                                             {
  // Allow swapping megamorphic elements accesses for named accesses when the
  // key is know to be a known name.
  CHECK(transition_groups_.empty());
  ZoneVector<MapRef> maps(broker->zone());
  return *broker->zone()->New<NamedAccessFeedback>(name, maps, slot_kind());
}
References broker(), CHECK, v8::internal::name, v8::internal::compiler::ProcessedFeedback::slot_kind(), and transition_groups_.
Refine() [2/3]
ElementAccessFeedback const & v8::internal::compiler::ElementAccessFeedback::Refine (JSHeapBroker * broker, ZoneRefSet< Map > const & inferred_maps, bool always_keep_group_target = true) const
Definition at line 213 of file js-heap-broker.cc.
                                         {
  ElementAccessFeedback& refined_feedback =
      *broker->zone()->New<ElementAccessFeedback>(broker->zone(), keyed_mode(),
                                                  slot_kind());
  if (inferred_maps.size() == 0) return refined_feedback;
  for (auto const& group : transition_groups()) {
    DCHECK(!group.empty());
    TransitionGroup new_group(broker->zone());
    for (size_t i = 1; i < group.size(); ++i) {
      MapRef source = group[i];
      if (inferred_maps.contains(source)) {
        new_group.push_back(source);
      }
    }
    MapRef target = group.front();
    bool const keep_target = always_keep_group_target ||
                             inferred_maps.contains(target) ||
                             new_group.size() > 1;
    if (keep_target) {
      new_group.push_back(target);
      // The target must be at the front, the order of sources doesn't matter.
      std::swap(new_group[0], new_group[new_group.size() - 1]);
    }
    if (!new_group.empty()) {
      DCHECK(new_group.size() == 1 || new_group.front().equals(target));
      refined_feedback.transition_groups_.push_back(std::move(new_group));
    }
  }
  return refined_feedback;
}
References broker(), v8::internal::ZoneCompactSet< T >::contains(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::empty(), v8::internal::ZoneVector< T >::front(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, keyed_mode(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneCompactSet< T >::size(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::ProcessedFeedback::slot_kind(), transition_groups(), and transition_groups_.
Refine() [3/3]
ElementAccessFeedback const & v8::internal::compiler::ElementAccessFeedback::Refine (JSHeapBroker * broker, ZoneVector< MapRef > const & inferred_maps) const
Definition at line 192 of file js-heap-broker.cc.
                                                                         {
  if (inferred_maps.empty()) {
    return *broker->zone()->New<ElementAccessFeedback>(
        broker->zone(), keyed_mode(), slot_kind());
  }
  ZoneRefSet<Map> inferred(inferred_maps.begin(), inferred_maps.end(),
                           broker->zone());
  return Refine(broker, inferred, false);
}
References v8::internal::ZoneVector< T >::begin(), broker(), v8::internal::ZoneVector< T >::empty(), v8::internal::ZoneVector< T >::end(), keyed_mode(), and v8::internal::compiler::ProcessedFeedback::slot_kind().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), and v8::internal::compiler::JSNativeContextSpecialization::TryRefineElementAccessFeedback().
transition_groups()
ZoneVector< ElementAccessFeedback::TransitionGroup > const & v8::internal::compiler::ElementAccessFeedback::transition_groups () const
Definition at line 188 of file js-heap-broker.cc.
                                               {
  return transition_groups_;
}
References transition_groups_.
Referenced by AddGroup(), v8::internal::compiler::AccessInfoFactory::ComputeElementAccessInfos(), v8::internal::compiler::AccessInfoFactory::ConsolidateElementLoad(), HasOnlyStringMaps(), v8::internal::compiler::JSNativeContextSpecialization::ReduceElementAccess(), v8::internal::compiler::JSNativeContextSpecialization::ReducePropertyAccess(), Refine(), v8::internal::compiler::anonymous_namespace{js-generic-lowering.cc}::ShouldUseMegamorphicAccessBuiltin(), v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccess(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildElementAccessOnString().
Member Data Documentation
keyed_mode_
KeyedAccessMode const v8::internal::compiler::ElementAccessFeedback::keyed_mode_ [private]
Definition at line 169 of file processed-feedback.h.
Referenced by keyed_mode().
transition_groups_
ZoneVector<TransitionGroup> v8::internal::compiler::ElementAccessFeedback::transition_groups_ [private]
Definition at line 170 of file processed-feedback.h.
Referenced by AddGroup(), Refine(), and transition_groups().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/processed-feedback.h
/mnt/V8SourceCode/src/compiler/js-heap-broker.cc