v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor Class Reference
Static Public Member Functions
static bool Check (RegExpTree *tree, RegExpFlags flags, int capture_count)
Private Member Functions
CanBeHandledVisitor (RegExpFlags flags)
void * VisitDisjunction (RegExpDisjunction *node, void *) override
void * VisitAlternative (RegExpAlternative *node, void *) override
void * VisitClassRanges (RegExpClassRanges *node, void *) override
void * VisitClassSetOperand (RegExpClassSetOperand *node, void *) override
void * VisitClassSetExpression (RegExpClassSetExpression *node, void *) override
void * VisitAssertion (RegExpAssertion *node, void *) override
void * VisitAtom (RegExpAtom *node, void *) override
void * VisitText (RegExpText *node, void *) override
void * VisitQuantifier (RegExpQuantifier *node, void *) override
void * VisitCapture (RegExpCapture *node, void *) override
void * VisitGroup (RegExpGroup *node, void *) override
void * VisitLookaround (RegExpLookaround *node, void *) override
void * VisitBackReference (RegExpBackReference *node, void *) override
void * VisitEmpty (RegExpEmpty *node, void *) override
RegExpFlags flags () const
Static Private Member Functions
static bool AreSuitableFlags (RegExpFlags flags)
Private Attributes
int replication_factor_ = 1
bool result_ = true
RegExpFlags flags_
Detailed Description
Definition at line 25 of file experimental-compiler.cc.
Constructor & Destructor Documentation
CanBeHandledVisitor()
v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::CanBeHandledVisitor (RegExpFlags flags) [inline], [explicit], [private]
Definition at line 36 of file experimental-compiler.cc.
: flags_(flags) {}
Member Function Documentation
AreSuitableFlags()
static bool v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::AreSuitableFlags (RegExpFlags flags) [inline], [static], [private]
Definition at line 38 of file experimental-compiler.cc.
                                                  {
    // TODO(mbid, v8:10765): We should be able to support all flags in the
    // future.
    static constexpr RegExpFlags kAllowedFlags =
        RegExpFlag::kGlobal | RegExpFlag::kSticky | RegExpFlag::kMultiline |
        RegExpFlag::kDotAll | RegExpFlag::kLinear;
    // We support Unicode iff kUnicode is among the supported flags.
    static_assert(ExperimentalRegExp::kSupportsUnicode ==
                  IsUnicode(kAllowedFlags));
    return (flags & ~kAllowedFlags) == 0;
  }
References v8::internal::flags, and v8::internal::ExperimentalRegExp::kSupportsUnicode.
Check()
static bool v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::Check (RegExpTree * tree, RegExpFlags flags, int capture_count) [inline], [static]
Definition at line 28 of file experimental-compiler.cc.
                                                                            {
    if (!AreSuitableFlags(flags)) return false;
    CanBeHandledVisitor visitor{flags};
    tree->Accept(&visitor, nullptr);
    return visitor.result_;
  }
References v8::internal::RegExpTree::Accept(), and v8::internal::flags.
flags()
RegExpFlags v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::flags () const [inline], [private]
Definition at line 210 of file experimental-compiler.cc.
{ return flags_; }
VisitAlternative()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitAlternative (RegExpAlternative * node, void *) [inline], [override], [private]
Definition at line 60 of file experimental-compiler.cc.
                                                                  {
    for (RegExpTree* child : *node->nodes()) {
      child->Accept(this, nullptr);
      if (!result_) {
        return nullptr;
      }
    }
    return nullptr;
  }
References v8::internal::RegExpAlternative::nodes().
VisitAssertion()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitAssertion (RegExpAssertion * node, void *) [inline], [override], [private]
Definition at line 85 of file experimental-compiler.cc.
                                                              {
    return nullptr;
  }
VisitAtom()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitAtom (RegExpAtom * node, void *) [inline], [override], [private]
Definition at line 89 of file experimental-compiler.cc.
{ return nullptr; }
VisitBackReference()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitBackReference (RegExpBackReference * node, void *) [inline], [override], [private]
Definition at line 201 of file experimental-compiler.cc.
                                                                      {
    // This can't be implemented without backtracking.
    result_ = false;
    return nullptr;
  }
VisitCapture()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitCapture (RegExpCapture * node, void *) [inline], [override], [private]
Definition at line 159 of file experimental-compiler.cc.
                                                          {
    node->body()->Accept(this, nullptr);
    return nullptr;
  }
References v8::internal::RegExpTree::Accept(), and v8::internal::RegExpCapture::body().
VisitClassRanges()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitClassRanges (RegExpClassRanges * node, void *) [inline], [override], [private]
Definition at line 70 of file experimental-compiler.cc.
                                                                  {
    return nullptr;
  }
VisitClassSetExpression()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitClassSetExpression (RegExpClassSetExpression * node, void *) [inline], [override], [private]
Definition at line 79 of file experimental-compiler.cc.
                                                {
    result_ = false;
    return nullptr;
  }
VisitClassSetOperand()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitClassSetOperand (RegExpClassSetOperand * node, void *) [inline], [override], [private]
Definition at line 74 of file experimental-compiler.cc.
                                                                          {
    result_ = !node->has_strings();
    return nullptr;
  }
References v8::internal::RegExpClassSetOperand::has_strings().
VisitDisjunction()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitDisjunction (RegExpDisjunction * node, void *) [inline], [override], [private]
Definition at line 50 of file experimental-compiler.cc.
                                                                  {
    for (RegExpTree* alt : *node->alternatives()) {
      alt->Accept(this, nullptr);
      if (!result_) {
        return nullptr;
      }
    }
    return nullptr;
  }
References v8::internal::RegExpDisjunction::alternatives().
VisitEmpty()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitEmpty (RegExpEmpty * node, void *) [inline], [override], [private]
Definition at line 207 of file experimental-compiler.cc.
{ return nullptr; }
VisitGroup()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitGroup (RegExpGroup * node, void *) [inline], [override], [private]
Definition at line 164 of file experimental-compiler.cc.
                                                      {
    if (flags() != node->flags()) {
      // Flags that aren't supported by the experimental engine at all, are not
      // supported via modifiers either.
      // TODO(pthier): Currently the only flag supported in modifiers and in
      // the experimental engine is multi-line, which is already handled in the
      // parser. If more flags are supported either by the experimental engine
      // or in modifiers we need to add general support for modifiers to the
      // experimental engine.
      if (!AreSuitableFlags(node->flags())) {
        result_ = false;
        return nullptr;
      }
    }
    node->body()->Accept(this, nullptr);
    return nullptr;
  }
References v8::internal::RegExpTree::Accept(), v8::internal::RegExpGroup::body(), v8::internal::RegExpGroup::flags(), and v8::internal::flags.
VisitLookaround()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitLookaround (RegExpLookaround * node, void *) [inline], [override], [private]
Definition at line 182 of file experimental-compiler.cc.
                                                                {
    if (IsGlobal(flags()) || IsSticky(flags())) {
      result_ = false;
      return nullptr;
    }
    // If `experimental_regexp_engine_capture_group_opt` is false, reject all
    // lookaheads or capturing lookbehinds.
    if (!v8_flags.experimental_regexp_engine_capture_group_opt &&
        (node->type() == RegExpLookaround::LOOKAHEAD ||
         node->capture_count() > 0)) {
      result_ = false;
      return nullptr;
    }
    node->body()->Accept(this, nullptr);
    return nullptr;
  }
References v8::internal::RegExpTree::Accept(), v8::internal::RegExpLookaround::body(), v8::internal::RegExpLookaround::capture_count(), v8::internal::flags, v8::internal::RegExpLookaround::LOOKAHEAD, v8::internal::RegExpLookaround::type(), and v8::internal::v8_flags.
VisitQuantifier()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitQuantifier (RegExpQuantifier * node, void *) [inline], [override], [private]
Definition at line 101 of file experimental-compiler.cc.
                                                                {
    // Finite but large values of `min()` and `max()` are bad for the
    // breadth-first engine because finite (optional) repetition is dealt with
    // by replicating the bytecode of the body of the quantifier. The number
    // of replications grows exponentially in how deeply quantifiers are nested.
    // `replication_factor_` keeps track of how often the current node will
    // have to be replicated in the generated bytecode, and we don't allow this
    // to exceed some small value.
    static constexpr int kMaxReplicationFactor = 16;
    // First we rule out values for min and max that are too big even before
    // taking into account the ambient replication_factor_. This also guards
    // against overflows in `local_replication` or `replication_factor_`.
    if (node->min() > kMaxReplicationFactor ||
        (node->max() != RegExpTree::kInfinity &&
         node->max() > kMaxReplicationFactor)) {
      result_ = false;
      return nullptr;
    }
    // Save the current replication factor so that it can be restored if we
    // return with `result_ == true`.
    int before_replication_factor = replication_factor_;
    int local_replication;
    if (node->max() == RegExpTree::kInfinity) {
      if (node->min() > 0 && node->min_match() > 0) {
        // Quantifier can be reduced to a non nullable plus.
        local_replication = std::max(node->min(), 1);
      } else {
        local_replication = node->min() + 1;
      }
    } else {
      local_replication = node->max();
    }
    replication_factor_ *= local_replication;
    if (replication_factor_ > kMaxReplicationFactor) {
      result_ = false;
      return nullptr;
    }
    switch (node->quantifier_type()) {
      case RegExpQuantifier::GREEDY:
      case RegExpQuantifier::NON_GREEDY:
        break;
      case RegExpQuantifier::POSSESSIVE:
        // TODO(mbid, v8:10765): It's not clear to me whether this can be
        // supported in breadth-first mode. Re2 doesn't support it.
        result_ = false;
        return nullptr;
    }
    node->body()->Accept(this, nullptr);
    replication_factor_ = before_replication_factor;
    return nullptr;
  }
References v8::internal::RegExpTree::Accept(), v8::internal::RegExpQuantifier::body(), v8::internal::RegExpQuantifier::GREEDY, v8::internal::RegExpTree::kInfinity, v8::internal::RegExpQuantifier::max(), v8::internal::RegExpQuantifier::min(), v8::internal::RegExpQuantifier::min_match(), v8::internal::RegExpQuantifier::NON_GREEDY, v8::internal::RegExpQuantifier::POSSESSIVE, and v8::internal::RegExpQuantifier::quantifier_type().
VisitText()
void* v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::VisitText (RegExpText * node, void *) [inline], [override], [private]
Definition at line 91 of file experimental-compiler.cc.
                                                    {
    for (TextElement& el : *node->elements()) {
      el.tree()->Accept(this, nullptr);
      if (!result_) {
        return nullptr;
      }
    }
    return nullptr;
  }
References v8::internal::RegExpText::elements().
Member Data Documentation
flags_
RegExpFlags v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::flags_ [private]
Definition at line 216 of file experimental-compiler.cc.
replication_factor_
int v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::replication_factor_ = 1 [private]
Definition at line 213 of file experimental-compiler.cc.
result_
bool v8::internal::anonymous_namespace{experimental-compiler.cc}::CanBeHandledVisitor::result_ = true [private]
Definition at line 215 of file experimental-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/experimental/experimental-compiler.cc