cppgc::internal::ConservativeMarkingVisitor Class Reference
#include <marking-visitor.h>
Public Member Functions
ConservativeMarkingVisitor (HeapBase &, MutatorMarkingState &, cppgc::Visitor &)
~ConservativeMarkingVisitor () override=default
Private Member Functions
void VisitFullyConstructedConservatively (HeapObjectHeader &) final
void VisitInConstructionConservatively (HeapObjectHeader &, TraceConservativelyCallback) final
void VisitPointer (const void *) final
Private Attributes
MutatorMarkingState & marking_state_
Additional Inherited Members
Detailed Description
Definition at line 78 of file marking-visitor.h.
Constructor & Destructor Documentation
ConservativeMarkingVisitor()
cppgc::internal::ConservativeMarkingVisitor::ConservativeMarkingVisitor (HeapBase & heap, MutatorMarkingState & marking_state, cppgc::Visitor & visitor)
Definition at line 87 of file marking-visitor.cc.
    : ConservativeTracingVisitor(heap, *heap.page_backend(), visitor),
      marking_state_(marking_state) {}
 ConservativeMarkingVisitor()
cppgc::internal::ConservativeMarkingVisitor::~ConservativeMarkingVisitor () [override], [default]
Member Function Documentation
VisitFullyConstructedConservatively()
void cppgc::internal::ConservativeMarkingVisitor::VisitFullyConstructedConservatively (HeapObjectHeader & header) [final], [private], [virtual]
Reimplemented from cppgc::internal::ConservativeTracingVisitor.
Definition at line 92 of file marking-visitor.cc.
                              {
  if (header.IsMarked<AccessMode::kAtomic>()) {
    if (marking_state_.IsMarkedWeakContainer(header))
      marking_state_.ReTraceMarkedWeakContainer(visitor_, header);
    return;
  }
  ConservativeTracingVisitor::VisitFullyConstructedConservatively(header);
}
References cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::MutatorMarkingState::IsMarkedWeakContainer(), cppgc::internal::kAtomic, marking_state_, cppgc::internal::MutatorMarkingState::ReTraceMarkedWeakContainer(), cppgc::internal::ConservativeTracingVisitor::VisitFullyConstructedConservatively(), and cppgc::internal::ConservativeTracingVisitor::visitor_.
VisitInConstructionConservatively()
void cppgc::internal::ConservativeMarkingVisitor::VisitInConstructionConservatively (HeapObjectHeader & header, TraceConservativelyCallback callback) [final], [private], [virtual]
Reimplemented from cppgc::internal::ConservativeTracingVisitor.
Definition at line 102 of file marking-visitor.cc.
                                                                    {
  DCHECK(!marking_state_.IsMarkedWeakContainer(header));
  // In construction objects found through conservative can be marked if they
  // hold a reference to themselves.
  if (!marking_state_.MarkNoPush(header)) return;
  marking_state_.AccountMarkedBytes(header);
#if defined(CPPGC_YOUNG_GENERATION)
  // An in-construction object can add a reference to a young object that may
  // miss the write-barrier on an initializing store. Remember object in the
  // root-set to be retraced on the next GC.
  if (heap_.generational_gc_supported()) {
    heap_.remembered_set().AddInConstructionObjectToBeRetraced(header);
  }
#endif // defined(CPPGC_YOUNG_GENERATION)
  callback(this, header);
}
References cppgc::internal::BasicMarkingState::AccountMarkedBytes(), DCHECK, cppgc::internal::HeapBase::generational_gc_supported(), cppgc::internal::ConservativeTracingVisitor::heap_, cppgc::internal::MutatorMarkingState::IsMarkedWeakContainer(), marking_state_, and cppgc::internal::MutatorMarkingState::MarkNoPush().
VisitPointer()
void cppgc::internal::ConservativeMarkingVisitor::VisitPointer (const void * address) [final], [private], [virtual]
Implements heap::base::StackVisitor.
Definition at line 144 of file marking-visitor.cc.
                                                                 {
  TraceConservativelyIfNeeded(address);
}
References cppgc::internal::ConservativeTracingVisitor::TraceConservativelyIfNeeded().
Member Data Documentation
marking_state_
MutatorMarkingState& cppgc::internal::ConservativeMarkingVisitor::marking_state_ [private]
Definition at line 90 of file marking-visitor.h.
Referenced by VisitFullyConstructedConservatively(), and VisitInConstructionConservatively().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/marking-visitor.h
/mnt/V8SourceCode/src/heap/cppgc/marking-visitor.cc