v8::internal::compiler::turboshaft::Assembler< Reducers > Class Template Reference
#include <assembler.h>
Public Member Functions
Assembler (PipelineData *data, Graph &input_graph, Graph &output_graph, Zone *phase_zone)
PipelineData * data () const
Zone * phase_zone ()
const Graph & input_graph () const
Graph & output_graph () const
Zone * graph_zone () const
Graph & modifiable_input_graph () const
Block * NewLoopHeader ()
Block * NewBlock ()
bool Bind (Block *block)
void BindReachable (Block *block)
void FinalizeLoop (Block *loop_header)
void SetCurrentOrigin (OpIndex operation_origin)
Block * current_block () const
bool generating_unreachable_operations () const
V< AnyOrNone > current_operation_origin () const
const Operation & Get (OpIndex op_idx) const
Block * current_catch_block () const
void set_current_catch_block (Block *block)
V< Any > ReduceProjection (V< Any > tuple, uint16_t index, RegisterRepresentation rep)
void AddPredecessor (Block *source, Block *destination, bool branch)
Private Types
using Stack = typename ReducerStack< Reducers >::type
using node_t = typename Stack::node_t
Private Member Functions
void FinalizeBlock ()
Block * CreateSinglePredecessorForLoop (Block *loop_header)
void AddLoopPredecessor (Block *single_predecessor, Block *new_predecessor)
void SplitEdge (Block *source, Block *destination)
Private Attributes
Block * current_block_ = nullptr
Block * current_catch_block_ = nullptr
bool conceptually_in_a_block_ = false
V< AnyOrNone > current_operation_origin_ = V<AnyOrNone>::Invalid()
Friends
template<class Next >
class TSReducerBase
template<class AssemblerT >
class CatchScopeImpl
Additional Inherited Members
Detailed Description
template<class Reducers>
class v8::internal::compiler::turboshaft::Assembler< Reducers >
Definition at line 5350 of file assembler.h.
Member Typedef Documentation
node_t
template<class Reducers >
using v8::internal::compiler::turboshaft::Assembler< Reducers >::node_t = typename Stack::node_t [private]
Definition at line 5354 of file assembler.h.
Stack
template<class Reducers >
using v8::internal::compiler::turboshaft::Assembler< Reducers >::Stack = typename ReducerStack<Reducers>::type [private]
Definition at line 5353 of file assembler.h.
Constructor & Destructor Documentation
Assembler()
template<class Reducers >
v8::internal::compiler::turboshaft::Assembler< Reducers >::Assembler (PipelineData * data, Graph & input_graph, Graph & output_graph, Zone * phase_zone) [inline], [explicit]
Definition at line 5357 of file assembler.h.
      : AssemblerData(data, input_graph, output_graph, phase_zone), Stack() {
    SupportedOperations::Initialize();
  }
References v8::internal::compiler::turboshaft::SupportedOperations::Initialize().
Member Function Documentation
AddLoopPredecessor()
template<class Reducers >
void v8::internal::compiler::turboshaft::Assembler< Reducers >::AddLoopPredecessor (Block * single_predecessor, Block * new_predecessor) [inline], [private]
Definition at line 5578 of file assembler.h.
                                                                             {
    GotoOp& new_predecessor_goto =
        new_predecessor->LastOperation(this->output_graph())
            .template Cast<GotoOp>();
    new_predecessor_goto.destination = single_predecessor;
    single_predecessor->AddPredecessor(new_predecessor);
  }
References v8::internal::compiler::turboshaft::Block::AddPredecessor(), v8::internal::compiler::turboshaft::GotoOp::destination, and v8::internal::compiler::turboshaft::Block::LastOperation().
AddPredecessor()
template<class Reducers >
void v8::internal::compiler::turboshaft::Assembler< Reducers >::AddPredecessor (Block * source, Block * destination, bool branch) [inline]
Definition at line 5470 of file assembler.h.
                                                                      {
    DCHECK_IMPLIES(branch, source->EndsWithBranchingOp(this->output_graph()));
    if (destination->LastPredecessor() == nullptr) {
      // {destination} has currently no predecessors.
      DCHECK(destination->IsLoopOrMerge());
      if (branch && destination->IsLoop()) {
        // We always split Branch edges that go to loop headers.
        SplitEdge(source, destination);
      } else {
        destination->AddPredecessor(source);
        if (branch) {
          DCHECK(!destination->IsLoop());
          destination->SetKind(Block::Kind::kBranchTarget);
        }
      }
      return;
    } else if (destination->IsBranchTarget()) {
      // {destination} used to be a BranchTarget, but branch targets can only
      // have one predecessor. We'll thus split its (single) incoming edge, and
      // change its type to kMerge.
      DCHECK_EQ(destination->PredecessorCount(), 1);
      Block* pred = destination->LastPredecessor();
      destination->ResetLastPredecessor();
      destination->SetKind(Block::Kind::kMerge);
      // We have to split `pred` first to preserve order of predecessors.
      SplitEdge(pred, destination);
      if (branch) {
        // A branch always goes to a BranchTarget. We thus split the edge: we'll
        // insert a new Block, to which {source} will branch, and which will
        // "Goto" to {destination}.
        SplitEdge(source, destination);
      } else {
        // {destination} is a Merge, and {source} just does a Goto; nothing
        // special to do.
        destination->AddPredecessor(source);
      }
      return;
    }
    DCHECK(destination->IsLoopOrMerge());
    if (destination->IsLoop() && !destination->IsBound()) {
      DCHECK(!branch);
      DCHECK_EQ(destination->PredecessorCount(), 1);
      // We are trying to add an additional forward edge to this loop, which is
      // not allowed (all loops in Turboshaft should have exactly one incoming
      // forward edge). Instead, we'll create a new predecessor for the loop,
      // where all previous and future forward predecessors will be routed to.
      Block* single_predecessor =
          destination->single_loop_predecessor()
              ? destination->single_loop_predecessor()
              : CreateSinglePredecessorForLoop(destination);
      AddLoopPredecessor(single_predecessor, source);
      return;
    }
    if (branch) {
      // A branch always goes to a BranchTarget. We thus split the edge: we'll
      // insert a new Block, to which {source} will branch, and which will
      // "Goto" to {destination}.
      SplitEdge(source, destination);
    } else {
      // {destination} is a Merge, and {source} just does a Goto; nothing
      // special to do.
      destination->AddPredecessor(source);
    }
  }
References v8::internal::compiler::turboshaft::Block::AddPredecessor(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::compiler::turboshaft::Block::EndsWithBranchingOp(), v8::internal::compiler::turboshaft::Block::IsBound(), v8::internal::compiler::turboshaft::Block::IsBranchTarget(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::Block::IsLoopOrMerge(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), v8::internal::compiler::turboshaft::Block::PredecessorCount(), v8::internal::compiler::turboshaft::Block::ResetLastPredecessor(), v8::internal::compiler::turboshaft::Block::SetKind(), v8::internal::compiler::turboshaft::Block::single_loop_predecessor(), and v8::internal::this.
Bind()
template<class Reducers >
bool v8::internal::compiler::turboshaft::Assembler< Reducers >::Bind (Block * block) [inline]
Definition at line 5382 of file assembler.h.
                          {
#ifdef DEBUG
    set_conceptually_in_a_block(true);
#endif
    if (block->IsLoop() && block->single_loop_predecessor()) {
      // {block} is a loop header that had multiple incoming forward edges, and
      // for which we've created a "single_predecessor" block. We bind it now,
      // and insert a single Goto to the original loop header.
      BindReachable(block->single_loop_predecessor());
      // We need to go through a raw Emit because calling this->Goto would go
      // through AddPredecessor and SplitEdge, which would wrongly try to
      // prevent adding more predecessors to the loop header.
      this->template Emit<GotoOp>(block, /*is_backedge*/ false);
    }
    if (!this->output_graph().Add(block)) {
      return false;
    }
    DCHECK_NULL(current_block_);
    current_block_ = block;
    Stack::Bind(block);
    return true;
  }
References v8::bigint::Add(), DCHECK_NULL, v8::internal::compiler::turboshaft::Block::IsLoop(), and v8::internal::compiler::turboshaft::Block::single_loop_predecessor().
BindReachable()
template<class Reducers >
void v8::internal::compiler::turboshaft::Assembler< Reducers >::BindReachable (Block * block) [inline]
Definition at line 5408 of file assembler.h.
                                             {
    bool bound = Bind(block);
    DCHECK(bound);
    USE(bound);
  }
References v8::internal::DCHECK(), and USE.
CreateSinglePredecessorForLoop()
template<class Reducers >
Block* v8::internal::compiler::turboshaft::Assembler< Reducers >::CreateSinglePredecessorForLoop (Block * loop_header) [inline], [private]
Definition at line 5547 of file assembler.h.
                                                            {
    DCHECK(loop_header->IsLoop());
    DCHECK(!loop_header->IsBound());
    DCHECK_EQ(loop_header->PredecessorCount(), 1);
    Block* old_predecessor = loop_header->LastPredecessor();
    // Because we always split edges going to loop headers, we know that
    // {predecessor} ends with a Goto.
    GotoOp& old_predecessor_goto =
        old_predecessor->LastOperation(this->output_graph())
            .template Cast<GotoOp>();
    Block* single_loop_predecessor = NewBlock();
    single_loop_predecessor->SetKind(Block::Kind::kMerge);
    single_loop_predecessor->SetOrigin(loop_header->OriginForLoopHeader());
    // Re-routing the final Goto of {old_predecessor} to go to
    // {single_predecessor} instead of {loop_header}.
    single_loop_predecessor->AddPredecessor(old_predecessor);
    old_predecessor_goto.destination = single_loop_predecessor;
    // Resetting the predecessors of {loop_header}: it will now have a single
    // predecessor, {old_predecessor}, which isn't bound yet. (and which will be
    // bound automatically in Bind)
    loop_header->ResetAllPredecessors();
    loop_header->AddPredecessor(single_loop_predecessor);
    loop_header->SetSingleLoopPredecessor(single_loop_predecessor);
    return single_loop_predecessor;
  }
References v8::internal::compiler::turboshaft::Block::AddPredecessor(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::GotoOp::destination, v8::internal::compiler::turboshaft::Block::IsBound(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), v8::internal::compiler::turboshaft::Block::OriginForLoopHeader(), v8::internal::compiler::turboshaft::Block::PredecessorCount(), v8::internal::compiler::turboshaft::Block::ResetAllPredecessors(), v8::internal::compiler::turboshaft::Block::SetKind(), v8::internal::compiler::turboshaft::Block::SetOrigin(), and v8::internal::compiler::turboshaft::Block::SetSingleLoopPredecessor().
current_block()
template<class Reducers >
Block* v8::internal::compiler::turboshaft::Assembler< Reducers >::current_block () const [inline]
Definition at line 5433 of file assembler.h.
{ return current_block_; }
current_catch_block()
template<class Reducers >
Block* v8::internal::compiler::turboshaft::Assembler< Reducers >::current_catch_block () const [inline]
Definition at line 5445 of file assembler.h.
{ return current_catch_block_; }
current_operation_origin()
template<class Reducers >
V<AnyOrNone> v8::internal::compiler::turboshaft::Assembler< Reducers >::current_operation_origin () const [inline]
Definition at line 5437 of file assembler.h.
                                                {
    return current_operation_origin_;
  }
data()
template<class Reducers >
PipelineData* v8::internal::compiler::turboshaft::Assembler< Reducers >::data () const [inline]
Definition at line 5365 of file assembler.h.
{ return AssemblerData::data; }
References v8::internal::compiler::turboshaft::AssemblerData::data.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState().
FinalizeBlock()
template<class Reducers >
void v8::internal::compiler::turboshaft::Assembler< Reducers >::FinalizeBlock () [inline], [private]
Definition at line 5539 of file assembler.h.
                       {
    this->output_graph().Finalize(current_block_);
    current_block_ = nullptr;
#ifdef DEBUG
    set_conceptually_in_a_block(false);
#endif
  }
FinalizeLoop()
template<class Reducers >
void v8::internal::compiler::turboshaft::Assembler< Reducers >::FinalizeLoop (Block * loop_header) [inline]
Definition at line 5416 of file assembler.h.
                                        {
    if (loop_header->IsLoop() && loop_header->PredecessorCount() == 1) {
      this->output_graph().TurnLoopIntoMerge(loop_header);
    }
  }
References v8::internal::compiler::turboshaft::Block::IsLoop(), and v8::internal::compiler::turboshaft::Block::PredecessorCount().
generating_unreachable_operations()
template<class Reducers >
bool v8::internal::compiler::turboshaft::Assembler< Reducers >::generating_unreachable_operations () const [inline]
Definition at line 5434 of file assembler.h.
                                                 {
    return current_block() == nullptr;
  }
Get()
template<class Reducers >
const Operation& v8::internal::compiler::turboshaft::Assembler< Reducers >::Get (OpIndex op_idx) const [inline]
Definition at line 5441 of file assembler.h.
                                             {
    return this->output_graph().Get(op_idx);
  }
graph_zone()
template<class Reducers >
Zone* v8::internal::compiler::turboshaft::Assembler< Reducers >::graph_zone () const [inline]
Definition at line 5369 of file assembler.h.
{ return output_graph().graph_zone(); }
input_graph()
template<class Reducers >
const Graph& v8::internal::compiler::turboshaft::Assembler< Reducers >::input_graph () const [inline]
Definition at line 5367 of file assembler.h.
{ return AssemblerData::input_graph; }
References v8::internal::compiler::turboshaft::AssemblerData::input_graph.
modifiable_input_graph()
template<class Reducers >
Graph& v8::internal::compiler::turboshaft::Assembler< Reducers >::modifiable_input_graph () const [inline]
Definition at line 5373 of file assembler.h.
{ return AssemblerData::input_graph; }
References v8::internal::compiler::turboshaft::AssemblerData::input_graph.
NewBlock()
template<class Reducers >
Block* v8::internal::compiler::turboshaft::Assembler< Reducers >::NewBlock () [inline]
Definition at line 5376 of file assembler.h.
{ return this->output_graph().NewBlock(); }
NewLoopHeader()
template<class Reducers >
Block* v8::internal::compiler::turboshaft::Assembler< Reducers >::NewLoopHeader () [inline]
Definition at line 5375 of file assembler.h.
{ return this->output_graph().NewLoopHeader(); }
output_graph()
template<class Reducers >
Graph& v8::internal::compiler::turboshaft::Assembler< Reducers >::output_graph () const [inline]
Definition at line 5368 of file assembler.h.
{ return AssemblerData::output_graph; }
References v8::internal::compiler::turboshaft::AssemblerData::output_graph.
phase_zone()
template<class Reducers >
Zone* v8::internal::compiler::turboshaft::Assembler< Reducers >::phase_zone () [inline]
Definition at line 5366 of file assembler.h.
{ return AssemblerData::phase_zone; }
References v8::internal::compiler::turboshaft::AssemblerData::phase_zone.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope(), and v8::internal::wasm::WasmWrapperTSGraphBuilder::ModifyThreadInWasmFlagScope::~ModifyThreadInWasmFlagScope().
ReduceProjection()
template<class Reducers >
V<Any> v8::internal::compiler::turboshaft::Assembler< Reducers >::ReduceProjection (V< Any > tuple, uint16_t index, RegisterRepresentation rep) [inline]
Definition at line 5461 of file assembler.h.
                                                      {
    if (auto* tuple_op = Asm().matcher().template TryCast<TupleOp>(tuple)) {
      return tuple_op->input(index);
    }
    return Stack::ReduceProjection(tuple, index, rep);
  }
References v8::internal::index.
set_current_catch_block()
template<class Reducers >
void v8::internal::compiler::turboshaft::Assembler< Reducers >::set_current_catch_block (Block * block) [inline]
Definition at line 5448 of file assembler.h.
{ current_catch_block_ = block; }
SetCurrentOrigin()
template<class Reducers >
void v8::internal::compiler::turboshaft::Assembler< Reducers >::SetCurrentOrigin (OpIndex operation_origin) [inline]
Definition at line 5422 of file assembler.h.
                                                  {
    current_operation_origin_ = operation_origin;
  }
SplitEdge()
template<class Reducers >
void v8::internal::compiler::turboshaft::Assembler< Reducers >::SplitEdge (Block * source, Block * destination) [inline], [private]
Definition at line 5588 of file assembler.h.
                                                    {
    DCHECK(source->EndsWithBranchingOp(this->output_graph()));
    // Creating the new intermediate block
    Block* intermediate_block = NewBlock();
    intermediate_block->SetKind(Block::Kind::kBranchTarget);
    // Updating "predecessor" edge of {intermediate_block}. This needs to be
    // done before calling Bind, because otherwise Bind will think that this
    // block is not reachable.
    intermediate_block->AddPredecessor(source);
    // Updating {source}'s last Branch/Switch/CheckException. Note that
    // this must be done before Binding {intermediate_block}, otherwise,
    // Reducer::Bind methods will see an invalid block being bound (because its
    // predecessor would be a branch, but none of its targets would be the block
    // being bound).
    Operation& op = this->output_graph().Get(
        this->output_graph().PreviousIndex(source->end()));
    switch (op.opcode) {
      case Opcode::kBranch: {
        BranchOp& branch = op.Cast<BranchOp>();
        if (branch.if_true == destination) {
          branch.if_true = intermediate_block;
          // We enforce that Branches if_false and if_true can never be the same
          // (there is a DCHECK in Assembler::Branch enforcing that).
          DCHECK_NE(branch.if_false, destination);
        } else {
          DCHECK_EQ(branch.if_false, destination);
          branch.if_false = intermediate_block;
        }
        break;
      }
      case Opcode::kCheckException: {
        CheckExceptionOp& catch_exception_op = op.Cast<CheckExceptionOp>();
        if (catch_exception_op.didnt_throw_block == destination) {
          catch_exception_op.didnt_throw_block = intermediate_block;
          // We assume that CheckException's successor and catch_block
          // can never be the same (there is a DCHECK in
          // CheckExceptionOp::Validate enforcing that).
          DCHECK_NE(catch_exception_op.catch_block, destination);
        } else {
          DCHECK_EQ(catch_exception_op.catch_block, destination);
          catch_exception_op.catch_block = intermediate_block;
          // A catch block always has to start with a `CatchBlockBeginOp`.
          BindReachable(intermediate_block);
          intermediate_block->SetOrigin(source->OriginForBlockEnd());
          this->CatchBlockBegin();
          this->Goto(destination);
          return;
        }
        break;
      }
      case Opcode::kSwitch: {
        SwitchOp& switch_op = op.Cast<SwitchOp>();
        bool found = false;
        for (auto& case_block : switch_op.cases) {
          if (case_block.destination == destination) {
            case_block.destination = intermediate_block;
            DCHECK(!found);
            found = true;
#ifndef DEBUG
            break;
#endif
          }
        }
        DCHECK_IMPLIES(found, switch_op.default_case != destination);
        if (!found) {
          DCHECK_EQ(switch_op.default_case, destination);
          switch_op.default_case = intermediate_block;
        }
        break;
      }
      default:
        UNREACHABLE();
    }
    BindReachable(intermediate_block);
    intermediate_block->SetOrigin(source->OriginForBlockEnd());
    // Inserting a Goto in {intermediate_block} to {destination}. This will
    // create the edge from {intermediate_block} to {destination}. Note that
    // this will call AddPredecessor, but we've already removed the possible
    // edge of {destination} that need splitting, so no risks of infinite
    // recursion here.
    this->Goto(destination);
  }
References v8::internal::compiler::turboshaft::Block::AddPredecessor(), v8::internal::compiler::turboshaft::SwitchOp::cases, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::CheckExceptionOp::catch_block, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NE, v8::internal::compiler::turboshaft::SwitchOp::default_case, v8::internal::compiler::turboshaft::CheckExceptionOp::didnt_throw_block, v8::internal::compiler::turboshaft::Block::end(), v8::internal::compiler::turboshaft::Block::EndsWithBranchingOp(), v8::internal::compiler::turboshaft::BranchOp::if_false, v8::internal::compiler::turboshaft::BranchOp::if_true, v8::internal::compiler::turboshaft::kBranch, v8::internal::wasm::kSwitch, v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::Block::OriginForBlockEnd(), v8::internal::compiler::turboshaft::Block::SetKind(), v8::internal::compiler::turboshaft::Block::SetOrigin(), v8::internal::this, and v8::internal::UNREACHABLE().
Friends And Related Function Documentation
CatchScopeImpl
template<class Reducers >
template<class AssemblerT >
friend class CatchScopeImpl [friend]
Definition at line 5741 of file assembler.h.
TSReducerBase
template<class Reducers >
template<class Next >
friend class TSReducerBase [friend]
Definition at line 5739 of file assembler.h.
Member Data Documentation
conceptually_in_a_block_
template<class Reducers >
bool v8::internal::compiler::turboshaft::Assembler< Reducers >::conceptually_in_a_block_ = false [private]
Definition at line 5728 of file assembler.h.
current_block_
template<class Reducers >
Block* v8::internal::compiler::turboshaft::Assembler< Reducers >::current_block_ = nullptr [private]
Definition at line 5674 of file assembler.h.
current_catch_block_
template<class Reducers >
Block* v8::internal::compiler::turboshaft::Assembler< Reducers >::current_catch_block_ = nullptr [private]
Definition at line 5675 of file assembler.h.
current_operation_origin_
template<class Reducers >
V<AnyOrNone> v8::internal::compiler::turboshaft::Assembler< Reducers >::current_operation_origin_ = V<AnyOrNone>::Invalid() [private]
Definition at line 5732 of file assembler.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/assembler.h