v8::internal::compiler::JSGenericLowering Class Reference
#include <js-generic-lowering.h>
Public Member Functions
JSGenericLowering (JSGraph *jsgraph, Editor *editor, JSHeapBroker *broker)
~JSGenericLowering () final
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Protected Member Functions
void ReplaceWithBuiltinCall (Node *node, Builtin builtin)
void ReplaceWithBuiltinCall (Node *node, Callable c, CallDescriptor::Flags flags)
void ReplaceWithBuiltinCall (Node *node, Callable c, CallDescriptor::Flags flags, Operator::Properties properties)
void ReplaceWithRuntimeCall (Node *node, Runtime::FunctionId f, int args=-1)
void ReplaceUnaryOpWithBuiltinCall (Node *node, Builtin builtin_without_feedback, Builtin builtin_with_feedback)
void ReplaceBinaryOpWithBuiltinCall (Node *node, Builtin builtin_without_feedback, Builtin builtin_with_feedback)
Zone * zone () const
Isolate * isolate () const
JSGraph * jsgraph () const
TFGraph * graph () const
CommonOperatorBuilder * common () const
MachineOperatorBuilder * machine () const
JSHeapBroker * broker () const
Private Attributes
JSGraph *const jsgraph_
JSHeapBroker *const broker_
Additional Inherited Members
Detailed Description
Definition at line 24 of file js-generic-lowering.h.
Constructor & Destructor Documentation
JSGenericLowering()
v8::internal::compiler::JSGenericLowering::JSGenericLowering (JSGraph * jsgraph, Editor * editor, JSHeapBroker * broker)
Definition at line 37 of file js-generic-lowering.cc.
    : AdvancedReducer(editor), jsgraph_(jsgraph), broker_(broker) {}
 JSGenericLowering()
v8::internal::compiler::JSGenericLowering::~JSGenericLowering () [final], [default]
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::JSGenericLowering::broker () const [inline], [protected]
Definition at line 61 of file js-generic-lowering.h.
{ return broker_; }
References broker_.
common()
CommonOperatorBuilder * v8::internal::compiler::JSGenericLowering::common () const [protected]
Definition at line 1163 of file js-generic-lowering.cc.
                                        { return jsgraph()->graph(); }
CommonOperatorBuilder* JSGenericLowering::common() const {
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
graph()
TFGraph * v8::internal::compiler::JSGenericLowering::graph () const [protected]
Definition at line 1161 of file js-generic-lowering.cc.
{ return jsgraph()->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph().
isolate()
Isolate * v8::internal::compiler::JSGenericLowering::isolate () const [protected]
Definition at line 1159 of file js-generic-lowering.cc.
Referenced by ReplaceWithBuiltinCall().
jsgraph()
JSGraph* v8::internal::compiler::JSGenericLowering::jsgraph () const [inline], [protected]
Definition at line 57 of file js-generic-lowering.h.
{ return jsgraph_; }
References jsgraph_.
Referenced by common(), graph(), and machine().
machine()
MachineOperatorBuilder * v8::internal::compiler::JSGenericLowering::machine () const [protected]
Definition at line 1168 of file js-generic-lowering.cc.
                                                         {
References jsgraph(), and v8::internal::compiler::MachineGraph::machine().
Reduce()
Reduction v8::internal::compiler::JSGenericLowering::Reduce (Node * node) [final], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 44 of file js-generic-lowering.cc.
                                              {
  switch (node->opcode()) {
#define DECLARE_CASE(x, ...) \
  case IrOpcode::k##x: \
    if constexpr (IrOpcode::k##x == IrOpcode::kJSStackCheck) { \
      /* We don't want to lower stack checks so early, and we don't want to \
       * return `Changed` for them, otherwise we'll loop infinitely trying to \
       * lower them. */ \
      return NoChange(); \
    } \
    Lower##x(node); \
    break;
    JS_OP_LIST(DECLARE_CASE)
#undef DECLARE_CASE
    default:
      // Nothing to see.
      return NoChange();
  }
References v8::internal::compiler::Reducer::Changed(), DECLARE_CASE, JS_OP_LIST, v8::internal::compiler::Reducer::NoChange(), and v8::internal::compiler::Node::opcode().
reducer_name()
const char* v8::internal::compiler::JSGenericLowering::reducer_name () const [inline], [override], [virtual]
Implements v8::internal::compiler::Reducer.
Definition at line 29 of file js-generic-lowering.h.
{ return "JSGenericLowering"; }
ReplaceBinaryOpWithBuiltinCall()
void v8::internal::compiler::JSGenericLowering::ReplaceBinaryOpWithBuiltinCall (Node * node, Builtin builtin_without_feedback, Builtin builtin_with_feedback) [protected]
Definition at line 146 of file js-generic-lowering.cc.
                                   {
  DCHECK(JSOperator::IsBinaryWithFeedback(node->opcode()));
  node->RemoveInput(JSBinaryOpNode::FeedbackVectorIndex());
References v8::internal::DCHECK(), v8::internal::compiler::JSOperator::IsBinaryWithFeedback(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::RemoveInput(), and ReplaceWithBuiltinCall().
ReplaceUnaryOpWithBuiltinCall()
void v8::internal::compiler::JSGenericLowering::ReplaceUnaryOpWithBuiltinCall (Node * node, Builtin builtin_without_feedback, Builtin builtin_with_feedback) [protected]
Definition at line 127 of file js-generic-lowering.cc.
                                   {
  DCHECK(JSOperator::IsUnaryWithFeedback(node->opcode()));
  node->RemoveInput(JSUnaryOpNode::FeedbackVectorIndex());
ReplaceWithBuiltinCall() [1/3]
void v8::internal::compiler::JSGenericLowering::ReplaceWithBuiltinCall (Node * node, Builtin builtin) [protected]
Definition at line 87 of file js-generic-lowering.cc.
                                                                          {
  CallDescriptor::Flags flags = FrameStateFlagForCall(node);
  Callable callable = Builtins::CallableFor(isolate(), builtin);
References v8::internal::Builtins::CallableFor(), v8::internal::flags, v8::internal::compiler::anonymous_namespace{js-generic-lowering.cc}::FrameStateFlagForCall(), and isolate().
Referenced by ReplaceBinaryOpWithBuiltinCall().
ReplaceWithBuiltinCall() [2/3]
void v8::internal::compiler::JSGenericLowering::ReplaceWithBuiltinCall (Node * node, Callable c, CallDescriptor::Flags flags) [protected]
Definition at line 93 of file js-generic-lowering.cc.
                                                                          {
ReplaceWithBuiltinCall() [3/3]
void v8::internal::compiler::JSGenericLowering::ReplaceWithBuiltinCall (Node * node, Callable c, CallDescriptor::Flags flags, Operator::Properties properties) [protected]
Definition at line 98 of file js-generic-lowering.cc.
                                   {
  const CallInterfaceDescriptor& descriptor = callable.descriptor();
  auto call_descriptor = Linkage::GetStubCallDescriptor(
      zone(), descriptor, descriptor.GetStackParameterCount(), flags,
      properties);
  Node* stub_code = jsgraph()->HeapConstantNoHole(callable.code());
  node->InsertInput(zone(), 0, stub_code);
ReplaceWithRuntimeCall()
void v8::internal::compiler::JSGenericLowering::ReplaceWithRuntimeCall (Node * node, Runtime::FunctionId f, int args = -1) [protected]
Definition at line 110 of file js-generic-lowering.cc.
                                                                   {
  CallDescriptor::Flags flags = FrameStateFlagForCall(node);
  Operator::Properties properties = node->op()->properties();
  const Runtime::Function* fun = Runtime::FunctionForId(f);
  int nargs = (nargs_override < 0) ? fun->nargs : nargs_override;
  auto call_descriptor =
      Linkage::GetRuntimeCallDescriptor(zone(), f, nargs, properties, flags);
  Node* ref = jsgraph()->ExternalConstant(ExternalReference::Create(f));
  Node* arity = jsgraph()->Int32Constant(nargs);
  node->InsertInput(zone(), 0, jsgraph()->CEntryStubConstant(fun->result_size));
  node->InsertInput(zone(), nargs + 1, ref);
  node->InsertInput(zone(), nargs + 2, arity);
zone()
Zone * v8::internal::compiler::JSGenericLowering::zone () const [protected]
Definition at line 1156 of file js-generic-lowering.cc.
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::JSGenericLowering::broker_ [private]
Definition at line 65 of file js-generic-lowering.h.
Referenced by broker().
jsgraph_
JSGraph* const v8::internal::compiler::JSGenericLowering::jsgraph_ [private]
Definition at line 64 of file js-generic-lowering.h.
Referenced by jsgraph().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-generic-lowering.h
/mnt/V8SourceCode/src/compiler/js-generic-lowering.cc