v8::internal::wasm::AsmJsParser Class Reference
#include <asm-parser.h>
Classes
struct BlockInfo
class CachedVector
class CachedVectors
struct FunctionImportInfo
struct GlobalImport
class TemporaryVariableScope
struct VarInfo
Public Types
enum StandardMember { kInfinity
, kNaN
 }
using StdlibSet = base::EnumSet< StandardMember, uint64_t >
Public Member Functions
AsmJsParser (Zone *zone, uintptr_t stack_limit, Utf16CharacterStream *stream)
bool Run ()
const char * failure_message () const
int failure_location () const
WasmModuleBuilder * module_builder ()
const StdlibSet * stdlib_uses () const
Private Types
enum class VarKind {
kUnused
, kLocal
, kGlobal
, kSpecial
,
kFunction
, kTable
, kImportedFunction
, V
,
V
 }
enum class BlockKind { kRegular
, kLoop
, kNamed
, kOther
 }
Private Member Functions
Zone * zone ()
bool Peek (AsmJsScanner::token_t token)
bool PeekForZero ()
bool Check (AsmJsScanner::token_t token)
bool CheckForZero ()
bool CheckForDouble (double *value)
bool CheckForUnsigned (uint32_t *value)
bool CheckForUnsignedBelow (uint32_t limit, uint32_t *value)
AsmJsScanner::token_t Consume ()
void SkipSemicolon ()
VarInfo * GetVarInfo (AsmJsScanner::token_t token)
uint32_t VarIndex (VarInfo *info)
void DeclareGlobal (VarInfo *info, bool mutable_variable, AsmType *type, ValueType vtype, WasmInitExpr init)
void DeclareStdlibFunc (VarInfo *info, VarKind kind, AsmType *type)
void AddGlobalImport (base::Vector< const char > name, AsmType *type, ValueType vtype, bool mutable_variable, VarInfo *info)
uint32_t TempVariable (int index)
base::Vector< const char > CopyCurrentIdentifierString ()
void BareBegin (BlockKind kind, AsmJsScanner::token_t label=0)
void BareEnd ()
int FindContinueLabelDepth (AsmJsScanner::token_t label)
int FindBreakLabelDepth (AsmJsScanner::token_t label)
void Begin (AsmJsScanner::token_t label=0)
void Loop (AsmJsScanner::token_t label=0)
void End ()
void InitializeStdlibTypes ()
FunctionSig * ConvertSignature (AsmType *return_type, const ZoneVector< AsmType * > &params)
void ValidateModule ()
void ValidateModuleParameters ()
void ValidateModuleVars ()
void ValidateModuleVar (bool mutable_variable)
void ValidateModuleVarImport (VarInfo *info, bool mutable_variable)
void ValidateModuleVarStdlib (VarInfo *info)
void ValidateModuleVarNewStdlib (VarInfo *info)
void ValidateModuleVarFromGlobal (VarInfo *info, bool mutable_variable)
void ValidateExport ()
void ValidateFunctionTable ()
void ValidateFunction ()
void ValidateFunctionParams (ZoneVector< AsmType * > *params)
void ValidateFunctionLocals (size_t param_count, ZoneVector< ValueType > *locals)
void ValidateStatement ()
void Block ()
void ExpressionStatement ()
void EmptyStatement ()
void IfStatement ()
void ReturnStatement ()
bool IterationStatement ()
void WhileStatement ()
void DoStatement ()
void ForStatement ()
void BreakStatement ()
void ContinueStatement ()
void LabelledStatement ()
void SwitchStatement ()
void ValidateCase ()
void ValidateDefault ()
AsmType * ValidateExpression ()
AsmType * Expression (AsmType *expect)
AsmType * NumericLiteral ()
AsmType * Identifier ()
AsmType * CallExpression ()
AsmType * MemberExpression ()
AsmType * AssignmentExpression ()
AsmType * UnaryExpression ()
AsmType * MultiplicativeExpression ()
AsmType * AdditiveExpression ()
AsmType * ShiftExpression ()
AsmType * RelationalExpression ()
AsmType * EqualityExpression ()
AsmType * BitwiseANDExpression ()
AsmType * BitwiseXORExpression ()
AsmType * BitwiseORExpression ()
AsmType * ConditionalExpression ()
AsmType * ParenthesizedExpression ()
AsmType * ValidateCall ()
bool PeekCall ()
void ValidateHeapAccess ()
void ValidateFloatCoercion ()
void ScanToClosingParenthesis ()
void GatherCases (ZoneVector< int32_t > *cases)
Private Attributes
Zone * zone_
AsmJsScanner scanner_
WasmModuleBuilder * module_builder_
WasmFunctionBuilder * current_function_builder_
AsmType * return_type_ = nullptr
uintptr_t stack_limit_
StdlibSet stdlib_uses_
base::Vector< VarInfo > global_var_info_
base::Vector< VarInfo > local_var_info_
size_t num_globals_ = 0
CachedVectors< ValueType > cached_valuetype_vectors_ {zone_}
CachedVectors< AsmType * > cached_asm_type_p_vectors_ {zone_}
CachedVectors< AsmJsScanner::token_t > cached_token_t_vectors_ {zone_}
CachedVectors< int32_t > cached_int_vectors_ {zone_}
int function_temp_locals_offset_
int function_temp_locals_used_
int function_temp_locals_depth_
bool failed_ = false
const char * failure_message_
int failure_location_ = kNoSourcePosition
AsmJsScanner::token_t stdlib_name_ = kTokenNone
AsmJsScanner::token_t foreign_name_ = kTokenNone
AsmJsScanner::token_t heap_name_ = kTokenNone
bool inside_heap_assignment_ = false
AsmType * heap_access_type_ = nullptr
ZoneVector< BlockInfo > block_stack_
AsmType * stdlib_dq2d_
AsmType * stdlib_dqdq2d_
AsmType * stdlib_i2s_
AsmType * stdlib_ii2s_
AsmType * stdlib_minmax_
AsmType * stdlib_abs_
AsmType * stdlib_ceil_like_
AsmType * stdlib_fround_
AsmType * call_coercion_ = nullptr
size_t call_coercion_position_
AsmType * call_coercion_deferred_ = nullptr
size_t call_coercion_deferred_position_
size_t heap_access_shift_position_
uint32_t heap_access_shift_value_
AsmJsScanner::token_t pending_label_ = kTokenNone
ZoneLinkedList< GlobalImport > global_imports_
Static Private Attributes
static const AsmJsScanner::token_t kTokenNone = 0
static const size_t kNoHeapAccessShift = -1
Detailed Description
Definition at line 33 of file asm-parser.h.
Member Typedef Documentation
StdlibSet
using v8::internal::wasm::AsmJsParser::StdlibSet = base::EnumSet<StandardMember, uint64_t>
Definition at line 51 of file asm-parser.h.
Member Enumeration Documentation
BlockKind
enum v8::internal::wasm::AsmJsParser::BlockKind [strong], [private]
Enumerator
kRegular
kLoop
kNamed
kOther
Definition at line 119 of file asm-parser.h.
{ kRegular, kLoop, kNamed, kOther };
StandardMember
enum v8::internal::wasm::AsmJsParser::StandardMember
Enumerator
kInfinity
kNaN
Definition at line 36 of file asm-parser.h.
                      {
    kInfinity,
    kNaN,
#define V(_unused1, name, _unused2, _unused3) kMath##name,
    STDLIB_MATH_FUNCTION_LIST(V)
#undef V
#define V(name, _unused1) kMath##name,
    STDLIB_MATH_VALUE_LIST(V)
#undef V
#define V(name, _unused1, _unused2, _unused3) k##name,
    STDLIB_ARRAY_TYPE_LIST(V)
#undef V
  };
VarKind
enum v8::internal::wasm::AsmJsParser::VarKind [strong], [private]
Enumerator
kUnused
kLocal
kGlobal
kSpecial
kFunction
kTable
kImportedFunction
V
V
Definition at line 63 of file asm-parser.h.
                     {
    kUnused,
    kLocal,
    kGlobal,
    kSpecial,
    kFunction,
    kTable,
    kImportedFunction,
#define V(_unused0, Name, _unused1, _unused2) kMath##Name,
    STDLIB_MATH_FUNCTION_LIST(V)
#undef V
#define V(Name, _unused1) kMath##Name,
    STDLIB_MATH_VALUE_LIST(V)
#undef V
  };
Constructor & Destructor Documentation
AsmJsParser()
v8::internal::wasm::AsmJsParser::AsmJsParser (Zone * zone, uintptr_t stack_limit, Utf16CharacterStream * stream) [explicit]
Definition at line 73 of file asm-parser.cc.
    : zone_(zone),
      scanner_(stream),
      module_builder_(zone->New<WasmModuleBuilder>(zone)),
      stack_limit_(stack_limit),
      block_stack_(zone),
      global_imports_(zone) {
  module_builder_->AddMemory(0);
  InitializeStdlibTypes();
}
References v8::internal::wasm::WasmModuleBuilder::AddMemory(), InitializeStdlibTypes(), and module_builder_.
Member Function Documentation
AddGlobalImport()
void v8::internal::wasm::AsmJsParser::AddGlobalImport (base::Vector< const char > name, AsmType * type, ValueType vtype, bool mutable_variable, VarInfo * info) [private]
Definition at line 223 of file asm-parser.cc.
                                                 {
  // Allocate a separate variable for the import.
  // TODO(asmjs): Consider using the imported global directly instead of
  // allocating a separate global variable for immutable (i.e. const) imports.
  DeclareGlobal(info, mutable_variable, type, vtype,
                WasmInitExpr::DefaultValue(vtype));
  // Record the need to initialize the global from the import.
  global_imports_.push_back({name, vtype, info});
}
References DeclareGlobal(), v8::internal::wasm::WasmInitExpr::DefaultValue(), global_imports_, v8::internal::wasm::name(), and v8::internal::tracing::type.
Referenced by ValidateModuleVarImport().
AdditiveExpression()
AsmType * v8::internal::wasm::AsmJsParser::AdditiveExpression () [private]
Definition at line 1795 of file asm-parser.cc.
                                         {
  AsmType* a;
  RECURSEn(a = MultiplicativeExpression());
  int n = 0;
  for (;;) {
    if (Check('+')) {
      AsmType* b;
      RECURSEn(b = MultiplicativeExpression());
      if (a->IsA(AsmType::Double()) && b->IsA(AsmType::Double())) {
        current_function_builder_->Emit(kExprF64Add);
        a = AsmType::Double();
      } else if (a->IsA(AsmType::FloatQ()) && b->IsA(AsmType::FloatQ())) {
        current_function_builder_->Emit(kExprF32Add);
        a = AsmType::Floatish();
      } else if (a->IsA(AsmType::Int()) && b->IsA(AsmType::Int())) {
        current_function_builder_->Emit(kExprI32Add);
        a = AsmType::Intish();
        n = 2;
      } else if (a->IsA(AsmType::Intish()) && b->IsA(AsmType::Intish())) {
        // TODO(bradnelson): b should really only be Int.
        // specialize intish to capture count.
        ++n;
        if (n > (1 << 20)) {
          FAILn("more than 2^20 additive values");
        }
        current_function_builder_->Emit(kExprI32Add);
      } else {
        FAILn("illegal types for +");
      }
    } else if (Check('-')) {
      AsmType* b;
      RECURSEn(b = MultiplicativeExpression());
      if (a->IsA(AsmType::Double()) && b->IsA(AsmType::Double())) {
        current_function_builder_->Emit(kExprF64Sub);
        a = AsmType::Double();
      } else if (a->IsA(AsmType::FloatQ()) && b->IsA(AsmType::FloatQ())) {
        current_function_builder_->Emit(kExprF32Sub);
        a = AsmType::Floatish();
      } else if (a->IsA(AsmType::Int()) && b->IsA(AsmType::Int())) {
        current_function_builder_->Emit(kExprI32Sub);
        a = AsmType::Intish();
        n = 2;
      } else if (a->IsA(AsmType::Intish()) && b->IsA(AsmType::Intish())) {
        // TODO(bradnelson): b should really only be Int.
        // specialize intish to capture count.
        ++n;
        if (n > (1 << 20)) {
          FAILn("more than 2^20 additive values");
        }
        current_function_builder_->Emit(kExprI32Sub);
      } else {
        FAILn("illegal types for +");
      }
    } else {
      break;
    }
  }
  return a;
}
References Check(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), FAILn, v8::internal::wasm::AsmType::IsA(), MultiplicativeExpression(), and RECURSEn.
Referenced by ShiftExpression().
AssignmentExpression()
AsmType * v8::internal::wasm::AsmJsParser::AssignmentExpression () [private]
Definition at line 1507 of file asm-parser.cc.
                                           {
  AsmType* ret;
  if (scanner_.IsGlobal() &&
      GetVarInfo(scanner_.Token())->type->IsA(AsmType::Heap())) {
    RECURSEn(ret = ConditionalExpression());
    if (Peek('=')) {
      if (!inside_heap_assignment_) {
        FAILn("Invalid assignment target");
      }
      inside_heap_assignment_ = false;
      DCHECK_NOT_NULL(heap_access_type_);
      AsmType* heap_type = heap_access_type_;
      EXPECT_TOKENn('=');
      AsmType* value;
      RECURSEn(value = AssignmentExpression());
      if (!value->IsA(ret)) {
        FAILn("Illegal type stored to heap view");
      }
      ret = value;
      if (heap_type->IsA(AsmType::Float32Array()) &&
          value->IsA(AsmType::DoubleQ())) {
        // Assignment to a float32 heap can be used to convert doubles.
        current_function_builder_->Emit(kExprF32ConvertF64);
        ret = AsmType::FloatQ();
      }
      if (heap_type->IsA(AsmType::Float64Array()) &&
          value->IsA(AsmType::FloatQ())) {
        // Assignment to a float64 heap can be used to convert floats.
        current_function_builder_->Emit(kExprF64ConvertF32);
        ret = AsmType::DoubleQ();
      }
#define V(array_type, wasmload, wasmstore, type) \
  if (heap_type->IsA(AsmType::array_type())) { \
    current_function_builder_->EmitWithPrefix(\
        kExpr##type##AsmjsStore##wasmstore); \
    return ret; \
  }
      STDLIB_ARRAY_TYPE_LIST(V)
#undef V
    }
  } else if (scanner_.IsLocal() || scanner_.IsGlobal()) {
    bool is_local = scanner_.IsLocal();
    VarInfo* info = GetVarInfo(scanner_.Token());
    USE(is_local);
    ret = info->type;
    scanner_.Next();
    if (Check('=')) {
      // NOTE: Before this point, this might have been VarKind::kUnused even in
      // valid code, as it might be a label.
      if (info->kind == VarKind::kUnused) {
        FAILn("Undeclared assignment target");
      }
      if (!info->mutable_variable) {
        FAILn("Expected mutable variable in assignment");
      }
      DCHECK(is_local ? info->kind == VarKind::kLocal
                      : info->kind == VarKind::kGlobal);
      AsmType* value;
      RECURSEn(value = AssignmentExpression());
      if (!value->IsA(ret)) {
        FAILn("Type mismatch in assignment");
      }
      if (info->kind == VarKind::kLocal) {
        current_function_builder_->EmitTeeLocal(info->index);
      } else if (info->kind == VarKind::kGlobal) {
        current_function_builder_->EmitWithU32V(kExprGlobalSet, VarIndex(info));
        current_function_builder_->EmitWithU32V(kExprGlobalGet, VarIndex(info));
      } else {
        UNREACHABLE();
      }
      return ret;
    }
    scanner_.Rewind();
    RECURSEn(ret = ConditionalExpression());
  } else {
    RECURSEn(ret = ConditionalExpression());
  }
  return ret;
}
References Check(), ConditionalExpression(), current_function_builder_, v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitTeeLocal(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V(), EXPECT_TOKENn, FAILn, GetVarInfo(), heap_access_type_, v8::internal::wasm::AsmJsParser::VarInfo::index, inside_heap_assignment_, v8::internal::wasm::AsmType::IsA(), v8::internal::AsmJsScanner::IsGlobal(), v8::internal::AsmJsScanner::IsLocal(), kGlobal, v8::internal::wasm::AsmJsParser::VarInfo::kind, kLocal, kUnused, v8::internal::wasm::AsmJsParser::VarInfo::mutable_variable, v8::internal::AsmJsScanner::Next(), Peek(), RECURSEn, v8::internal::AsmJsScanner::Rewind(), scanner_, STDLIB_ARRAY_TYPE_LIST, v8::internal::AsmJsScanner::Token(), v8::internal::wasm::AsmJsParser::VarInfo::type, v8::internal::UNREACHABLE(), USE, v8::internal::value, and VarIndex().
Referenced by ConditionalExpression(), Expression(), ValidateCall(), and ValidateFloatCoercion().
BareBegin()
void v8::internal::wasm::AsmJsParser::BareBegin (BlockKind kind, AsmJsScanner::token_t label = 0) [private]
Definition at line 289 of file asm-parser.cc.
                                                                     {
  BlockInfo info;
  info.kind = kind;
  info.label = label;
  block_stack_.push_back(info);
}
References block_stack_, v8::internal::wasm::AsmJsParser::BlockInfo::kind, and v8::internal::wasm::AsmJsParser::BlockInfo::label.
Referenced by Begin(), Block(), DoStatement(), ForStatement(), IfStatement(), Loop(), and SwitchStatement().
BareEnd()
void v8::internal::wasm::AsmJsParser::BareEnd () [private]
Definition at line 296 of file asm-parser.cc.
                          {
  DCHECK_GT(block_stack_.size(), 0);
  block_stack_.pop_back();
}
References block_stack_, and DCHECK_GT.
Referenced by End(), IfStatement(), and SwitchStatement().
Begin()
void v8::internal::wasm::AsmJsParser::Begin (AsmJsScanner::token_t label = 0) [private]
Definition at line 272 of file asm-parser.cc.
                                                 {
  BareBegin(BlockKind::kRegular, label);
  current_function_builder_->EmitWithU8(kExprBlock, kVoidCode);
}
References BareBegin(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::EmitWithU8(), kRegular, and v8::internal::wasm::kVoidCode.
Referenced by DoStatement(), ForStatement(), SwitchStatement(), and WhileStatement().
BitwiseANDExpression()
AsmType * v8::internal::wasm::AsmJsParser::BitwiseANDExpression () [private]
Definition at line 1988 of file asm-parser.cc.
                                           {
  AsmType* a = nullptr;
  RECURSEn(a = EqualityExpression());
  while (Check('&')) {
    AsmType* b = nullptr;
    RECURSEn(b = EqualityExpression());
    if (a->IsA(AsmType::Intish()) && b->IsA(AsmType::Intish())) {
      current_function_builder_->Emit(kExprI32And);
      a = AsmType::Signed();
    } else {
      FAILn("Expected intish for operator &.");
    }
  }
  return a;
}
References Check(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), EqualityExpression(), FAILn, v8::internal::wasm::AsmType::IsA(), RECURSEn, and v8::base::bits::Signed().
Referenced by BitwiseXORExpression().
BitwiseORExpression()
AsmType * v8::internal::wasm::AsmJsParser::BitwiseORExpression () [private]
Definition at line 2022 of file asm-parser.cc.
                                          {
  AsmType* a = nullptr;
  call_coercion_deferred_position_ = scanner_.Position();
  RECURSEn(a = BitwiseXORExpression());
  while (Check('|')) {
    AsmType* b = nullptr;
    // Remember whether the first operand to this OR-expression has requested
    // deferred validation of the |0 annotation.
    // NOTE: This has to happen here to work recursively.
    bool requires_zero =
        AsmType::IsExactly(call_coercion_deferred_, AsmType::Signed());
    call_coercion_deferred_ = nullptr;
    // TODO(bradnelson): Make it prettier.
    bool zero = false;
    size_t old_pos;
    size_t old_code;
    if (a->IsA(AsmType::Intish()) && CheckForZero()) {
      old_pos = scanner_.Position();
      old_code = current_function_builder_->GetPosition();
      scanner_.Rewind();
      zero = true;
    }
    RECURSEn(b = BitwiseXORExpression());
    // Handle |0 specially.
    if (zero && old_pos == scanner_.Position()) {
      current_function_builder_->DeleteCodeAfter(old_code);
      a = AsmType::Signed();
      continue;
    }
    // Anything not matching |0 breaks the lookahead in {ValidateCall}.
    if (requires_zero) {
      FAILn("Expected |0 type annotation for call");
    }
    if (a->IsA(AsmType::Intish()) && b->IsA(AsmType::Intish())) {
      current_function_builder_->Emit(kExprI32Ior);
      a = AsmType::Signed();
    } else {
      FAILn("Expected intish for operator |.");
    }
  }
  DCHECK_NULL(call_coercion_deferred_);
  return a;
}
References BitwiseXORExpression(), call_coercion_deferred_, call_coercion_deferred_position_, Check(), CheckForZero(), current_function_builder_, DCHECK_NULL, v8::internal::wasm::WasmFunctionBuilder::DeleteCodeAfter(), v8::internal::wasm::WasmFunctionBuilder::Emit(), FAILn, v8::internal::wasm::WasmFunctionBuilder::GetPosition(), v8::internal::wasm::AsmType::IsA(), v8::internal::wasm::AsmType::IsExactly(), v8::internal::AsmJsScanner::Position(), RECURSEn, v8::internal::AsmJsScanner::Rewind(), scanner_, v8::base::bits::Signed(), and v8::internal::zero.
Referenced by ConditionalExpression().
BitwiseXORExpression()
AsmType * v8::internal::wasm::AsmJsParser::BitwiseXORExpression () [private]
Definition at line 2005 of file asm-parser.cc.
                                           {
  AsmType* a = nullptr;
  RECURSEn(a = BitwiseANDExpression());
  while (Check('^')) {
    AsmType* b = nullptr;
    RECURSEn(b = BitwiseANDExpression());
    if (a->IsA(AsmType::Intish()) && b->IsA(AsmType::Intish())) {
      current_function_builder_->Emit(kExprI32Xor);
      a = AsmType::Signed();
    } else {
      FAILn("Expected intish for operator &.");
    }
  }
  return a;
}
References BitwiseANDExpression(), Check(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), FAILn, v8::internal::wasm::AsmType::IsA(), RECURSEn, and v8::base::bits::Signed().
Referenced by BitwiseORExpression().
Block()
void v8::internal::wasm::AsmJsParser::Block () [private]
Definition at line 1062 of file asm-parser.cc.
                        {
  bool can_break_to_block = pending_label_ != 0;
  if (can_break_to_block) {
    BareBegin(BlockKind::kNamed, pending_label_);
    current_function_builder_->EmitWithU8(kExprBlock, kVoidCode);
  }
  pending_label_ = 0;
  EXPECT_TOKEN('{');
  while (!failed_ && !Peek('}')) {
    RECURSE(ValidateStatement());
  }
  EXPECT_TOKEN('}');
  if (can_break_to_block) {
    End();
  }
}
References BareBegin(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::EmitWithU8(), End(), EXPECT_TOKEN, failed_, kNamed, v8::internal::wasm::kVoidCode, Peek(), pending_label_, RECURSE, and ValidateStatement().
Referenced by ValidateStatement().
BreakStatement()
void v8::internal::wasm::AsmJsParser::BreakStatement () [private]
Definition at line 1267 of file asm-parser.cc.
                                 {
  EXPECT_TOKEN(TOK(break));
  AsmJsScanner::token_t label_name = kTokenNone;
  if (scanner_.IsGlobal() || scanner_.IsLocal()) {
    // NOTE: Currently using globals/locals for labels too.
    label_name = Consume();
  }
  int depth = FindBreakLabelDepth(label_name);
  if (depth < 0) {
    FAIL("Illegal break");
  }
  current_function_builder_->EmitWithU32V(kExprBr, depth);
  SkipSemicolon();
}
References Consume(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V(), EXPECT_TOKEN, FAIL, FindBreakLabelDepth(), v8::internal::AsmJsScanner::IsGlobal(), v8::internal::AsmJsScanner::IsLocal(), kTokenNone, scanner_, SkipSemicolon(), and TOK.
Referenced by ValidateStatement().
CallExpression()
AsmType * v8::internal::wasm::AsmJsParser::CallExpression () [private]
Definition at line 1464 of file asm-parser.cc.
                                     {
  AsmType* ret;
  if (scanner_.IsGlobal() &&
      GetVarInfo(scanner_.Token())->type->IsA(stdlib_fround_)) {
    ValidateFloatCoercion();
    return AsmType::Float();
  } else if (scanner_.IsGlobal() &&
             GetVarInfo(scanner_.Token())->type->IsA(AsmType::Heap())) {
    RECURSEn(ret = MemberExpression());
  } else if (Peek('(')) {
    RECURSEn(ret = ParenthesizedExpression());
  } else if (PeekCall()) {
    RECURSEn(ret = ValidateCall());
  } else if (scanner_.IsLocal() || scanner_.IsGlobal()) {
    RECURSEn(ret = Identifier());
  } else {
    RECURSEn(ret = NumericLiteral());
  }
  return ret;
}
References GetVarInfo(), Identifier(), v8::internal::wasm::AsmType::IsA(), v8::internal::AsmJsScanner::IsGlobal(), v8::internal::AsmJsScanner::IsLocal(), MemberExpression(), NumericLiteral(), ParenthesizedExpression(), Peek(), PeekCall(), RECURSEn, scanner_, stdlib_fround_, v8::internal::AsmJsScanner::Token(), v8::internal::wasm::AsmJsParser::VarInfo::type, ValidateCall(), and ValidateFloatCoercion().
Referenced by UnaryExpression().
Check()
bool v8::internal::wasm::AsmJsParser::Check (AsmJsScanner::token_t token) [inline], [private]
Definition at line 257 of file asm-parser.h.
                                               {
    if (scanner_.Token() == token) {
      scanner_.Next();
      return true;
    } else {
      return false;
    }
  }
References v8::internal::AsmJsScanner::Next(), scanner_, and v8::internal::AsmJsScanner::Token().
Referenced by AdditiveExpression(), AssignmentExpression(), BitwiseANDExpression(), BitwiseORExpression(), BitwiseXORExpression(), ConditionalExpression(), GatherCases(), IfStatement(), MultiplicativeExpression(), SkipSemicolon(), UnaryExpression(), ValidateCall(), ValidateCase(), ValidateExport(), ValidateFunctionLocals(), ValidateFunctionParams(), ValidateFunctionTable(), ValidateHeapAccess(), ValidateModuleVar(), ValidateModuleVarFromGlobal(), ValidateModuleVarImport(), ValidateModuleVars(), and ValidateModuleVarStdlib().
CheckForDouble()
bool v8::internal::wasm::AsmJsParser::CheckForDouble (double * value) [inline], [private]
Definition at line 275 of file asm-parser.h.
                                            {
    if (scanner_.IsDouble()) {
      *value = scanner_.AsDouble();
      scanner_.Next();
      return true;
    } else {
      return false;
    }
  }
References v8::internal::AsmJsScanner::AsDouble(), v8::internal::AsmJsScanner::IsDouble(), v8::internal::AsmJsScanner::Next(), scanner_, and v8::internal::value.
Referenced by NumericLiteral(), ValidateFunctionLocals(), ValidateModuleVar(), and ValidateModuleVarFromGlobal().
CheckForUnsigned()
bool v8::internal::wasm::AsmJsParser::CheckForUnsigned (uint32_t * value) [inline], [private]
Definition at line 285 of file asm-parser.h.
                                                {
    if (scanner_.IsUnsigned()) {
      *value = scanner_.AsUnsigned();
      scanner_.Next();
      return true;
    } else {
      return false;
    }
  }
References v8::internal::AsmJsScanner::AsUnsigned(), v8::internal::AsmJsScanner::IsUnsigned(), v8::internal::AsmJsScanner::Next(), scanner_, and v8::internal::value.
Referenced by GatherCases(), MultiplicativeExpression(), NumericLiteral(), ShiftExpression(), UnaryExpression(), ValidateCall(), ValidateCase(), ValidateFunctionLocals(), ValidateHeapAccess(), ValidateModuleVar(), and ValidateModuleVarFromGlobal().
CheckForUnsignedBelow()
bool v8::internal::wasm::AsmJsParser::CheckForUnsignedBelow (uint32_t limit, uint32_t * value) [inline], [private]
Definition at line 295 of file asm-parser.h.
                                                                     {
    if (scanner_.IsUnsigned() && scanner_.AsUnsigned() < limit) {
      *value = scanner_.AsUnsigned();
      scanner_.Next();
      return true;
    } else {
      return false;
    }
  }
References v8::internal::AsmJsScanner::AsUnsigned(), v8::internal::AsmJsScanner::IsUnsigned(), v8::internal::AsmJsScanner::Next(), scanner_, and v8::internal::value.
Referenced by MultiplicativeExpression().
CheckForZero()
bool v8::internal::wasm::AsmJsParser::CheckForZero () [inline], [private]
Definition at line 266 of file asm-parser.h.
                             {
    if (scanner_.IsUnsigned() && scanner_.AsUnsigned() == 0) {
      scanner_.Next();
      return true;
    } else {
      return false;
    }
  }
References v8::internal::AsmJsScanner::AsUnsigned(), v8::internal::AsmJsScanner::IsUnsigned(), v8::internal::AsmJsScanner::Next(), and scanner_.
Referenced by BitwiseORExpression(), ValidateFunctionParams(), and ValidateModuleVarImport().
ConditionalExpression()
AsmType * v8::internal::wasm::AsmJsParser::ConditionalExpression () [private]
Definition at line 2067 of file asm-parser.cc.
                                            {
  AsmType* test = nullptr;
  RECURSEn(test = BitwiseORExpression());
  if (Check('?')) {
    if (!test->IsA(AsmType::Int())) {
      FAILn("Expected int in condition of ternary operator.");
    }
    current_function_builder_->EmitWithU8(kExprIf, kI32Code);
    size_t fixup = current_function_builder_->GetPosition() -
                   1; // Assumes encoding knowledge.
    AsmType* cons = nullptr;
    RECURSEn(cons = AssignmentExpression());
    current_function_builder_->Emit(kExprElse);
    EXPECT_TOKENn(':');
    AsmType* alt = nullptr;
    RECURSEn(alt = AssignmentExpression());
    current_function_builder_->Emit(kExprEnd);
    if (cons->IsA(AsmType::Int()) && alt->IsA(AsmType::Int())) {
      current_function_builder_->FixupByte(fixup, kI32Code);
      return AsmType::Int();
    } else if (cons->IsA(AsmType::Double()) && alt->IsA(AsmType::Double())) {
      current_function_builder_->FixupByte(fixup, kF64Code);
      return AsmType::Double();
    } else if (cons->IsA(AsmType::Float()) && alt->IsA(AsmType::Float())) {
      current_function_builder_->FixupByte(fixup, kF32Code);
      return AsmType::Float();
    } else {
      FAILn("Type mismatch in ternary operator.");
    }
  } else {
    return test;
  }
}
References AssignmentExpression(), BitwiseORExpression(), Check(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU8(), EXPECT_TOKENn, FAILn, v8::internal::wasm::WasmFunctionBuilder::FixupByte(), v8::internal::wasm::WasmFunctionBuilder::GetPosition(), v8::internal::wasm::AsmType::IsA(), v8::internal::wasm::kF32Code, v8::internal::wasm::kF64Code, v8::internal::wasm::kI32Code, and RECURSEn.
Referenced by AssignmentExpression().
Consume()
AsmJsScanner::token_t v8::internal::wasm::AsmJsParser::Consume () [inline], [private]
Definition at line 305 of file asm-parser.h.
                                       {
    AsmJsScanner::token_t ret = scanner_.Token();
    scanner_.Next();
    return ret;
  }
References v8::internal::AsmJsScanner::Next(), scanner_, and v8::internal::AsmJsScanner::Token().
Referenced by BreakStatement(), ContinueStatement(), Identifier(), ValidateCall(), ValidateExport(), ValidateFunction(), ValidateFunctionLocals(), ValidateFunctionParams(), ValidateFunctionTable(), ValidateHeapAccess(), ValidateModuleParameters(), ValidateModuleVar(), ValidateModuleVarFromGlobal(), ValidateModuleVarNewStdlib(), and ValidateModuleVarStdlib().
ContinueStatement()
void v8::internal::wasm::AsmJsParser::ContinueStatement () [private]
Definition at line 1283 of file asm-parser.cc.
                                    {
  EXPECT_TOKEN(TOK(continue));
  AsmJsScanner::token_t label_name = kTokenNone;
  if (scanner_.IsGlobal() || scanner_.IsLocal()) {
    // NOTE: Currently using globals/locals for labels too.
    label_name = Consume();
  }
  int depth = FindContinueLabelDepth(label_name);
  if (depth < 0) {
    FAIL("Illegal continue");
  }
  current_function_builder_->EmitWithU32V(kExprBr, depth);
  SkipSemicolon();
}
References Consume(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V(), EXPECT_TOKEN, FAIL, FindContinueLabelDepth(), v8::internal::AsmJsScanner::IsGlobal(), v8::internal::AsmJsScanner::IsLocal(), kTokenNone, scanner_, SkipSemicolon(), and TOK.
Referenced by ValidateStatement().
ConvertSignature()
FunctionSig * v8::internal::wasm::AsmJsParser::ConvertSignature (AsmType * return_type, const ZoneVector< AsmType * > & params) [private]
Definition at line 148 of file asm-parser.cc.
                                                                               {
  FunctionSig::Builder sig_builder(
      zone(), !return_type->IsA(AsmType::Void()) ? 1 : 0, params.size());
  for (auto param : params) {
    if (param->IsA(AsmType::Double())) {
      sig_builder.AddParam(kWasmF64);
    } else if (param->IsA(AsmType::Float())) {
      sig_builder.AddParam(kWasmF32);
    } else if (param->IsA(AsmType::Int())) {
      sig_builder.AddParam(kWasmI32);
    } else {
      UNREACHABLE();
    }
  }
  if (!return_type->IsA(AsmType::Void())) {
    if (return_type->IsA(AsmType::Double())) {
      sig_builder.AddReturn(kWasmF64);
    } else if (return_type->IsA(AsmType::Float())) {
      sig_builder.AddReturn(kWasmF32);
    } else if (return_type->IsA(AsmType::Signed())) {
      sig_builder.AddReturn(kWasmI32);
    } else {
      UNREACHABLE();
    }
  }
  return sig_builder.Get();
}
References v8::internal::SignatureBuilder< SigT, T >::AddParam(), v8::internal::SignatureBuilder< SigT, T >::AddReturn(), v8::internal::SignatureBuilder< SigT, T >::Get(), v8::internal::wasm::AsmType::IsA(), v8::internal::wasm::kWasmF32, v8::internal::wasm::kWasmF64, v8::internal::wasm::kWasmI32, v8::base::bits::Signed(), v8::internal::ZoneVector< T >::size(), v8::internal::UNREACHABLE(), and zone().
Referenced by ValidateCall(), and ValidateFunction().
CopyCurrentIdentifierString()
base::Vector< const char > v8::internal::wasm::AsmJsParser::CopyCurrentIdentifierString () [private]
Definition at line 260 of file asm-parser.cc.
                                                                {
  return zone()->CloneVector(base::VectorOf(scanner_.GetIdentifierString()));
}
References v8::internal::Zone::CloneVector(), v8::internal::AsmJsScanner::GetIdentifierString(), scanner_, v8::base::VectorOf(), and zone().
Referenced by ValidateExport(), ValidateFunction(), and ValidateModuleVarImport().
DeclareGlobal()
void v8::internal::wasm::AsmJsParser::DeclareGlobal (VarInfo * info, bool mutable_variable, AsmType * type, ValueType vtype, WasmInitExpr init) [private]
Definition at line 236 of file asm-parser.cc.
                                                   {
  info->kind = VarKind::kGlobal;
  info->type = type;
  info->index = module_builder_->AddGlobal(vtype, true, init);
  info->mutable_variable = mutable_variable;
}
References v8::internal::wasm::WasmModuleBuilder::AddGlobal(), v8::internal::wasm::AsmJsParser::VarInfo::index, kGlobal, v8::internal::wasm::AsmJsParser::VarInfo::kind, module_builder_, v8::internal::wasm::AsmJsParser::VarInfo::mutable_variable, v8::internal::wasm::AsmJsParser::VarInfo::type, and v8::internal::tracing::type.
Referenced by AddGlobalImport(), ValidateModuleVar(), ValidateModuleVarFromGlobal(), and ValidateModuleVarStdlib().
DeclareStdlibFunc()
void v8::internal::wasm::AsmJsParser::DeclareStdlibFunc (VarInfo * info, VarKind kind, AsmType * type) [private]
Definition at line 245 of file asm-parser.cc.
                                                   {
  info->kind = kind;
  info->type = type;
  info->index = 0; // unused
  info->mutable_variable = false;
}
References v8::internal::wasm::AsmJsParser::VarInfo::index, v8::internal::wasm::AsmJsParser::VarInfo::kind, v8::internal::wasm::AsmJsParser::VarInfo::mutable_variable, v8::internal::wasm::AsmJsParser::VarInfo::type, and v8::internal::tracing::type.
DoStatement()
void v8::internal::wasm::AsmJsParser::DoStatement () [private]
Definition at line 1185 of file asm-parser.cc.
                              {
  // a: block {
  Begin(pending_label_);
  // b: loop {
  Loop();
  // c: block { // but treated like loop so continue works
  BareBegin(BlockKind::kLoop, pending_label_);
  current_function_builder_->EmitWithU8(kExprBlock, kVoidCode);
  pending_label_ = 0;
  EXPECT_TOKEN(TOK(do));
  // BODY
  RECURSE(ValidateStatement());
  EXPECT_TOKEN(TOK(while));
  End();
  // } // end c
  EXPECT_TOKEN('(');
  RECURSE(Expression(AsmType::Int()));
  // if (!CONDITION) break a;
  current_function_builder_->Emit(kExprI32Eqz);
  current_function_builder_->EmitWithU8(kExprBrIf, 1);
  // continue b;
  current_function_builder_->EmitWithU8(kExprBr, 0);
  EXPECT_TOKEN(')');
  // } // end b
  End();
  // } // end a
  End();
  SkipSemicolon();
}
References BareBegin(), Begin(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU8(), End(), EXPECT_TOKEN, Expression(), kLoop, v8::internal::wasm::kVoidCode, Loop(), pending_label_, RECURSE, SkipSemicolon(), TOK, and ValidateStatement().
Referenced by IterationStatement().
EmptyStatement()
void v8::internal::wasm::AsmJsParser::EmptyStatement () [private]
Definition at line 1100 of file asm-parser.cc.
{ EXPECT_TOKEN(';'); }
References EXPECT_TOKEN.
Referenced by ValidateStatement().
End()
void v8::internal::wasm::AsmJsParser::End () [private]
Definition at line 284 of file asm-parser.cc.
                      {
  BareEnd();
  current_function_builder_->Emit(kExprEnd);
}
References BareEnd(), current_function_builder_, and v8::internal::wasm::WasmFunctionBuilder::Emit().
Referenced by Block(), DoStatement(), ForStatement(), SwitchStatement(), and WhileStatement().
EqualityExpression()
AsmType * v8::internal::wasm::AsmJsParser::EqualityExpression () [private]
Definition at line 1953 of file asm-parser.cc.
                                         {
  AsmType* a = nullptr;
  RECURSEn(a = RelationalExpression());
  for (;;) {
    switch (scanner_.Token()) {
#define HANDLE_CASE(op, sop, uop, dop, fop, name) \
  case op: { \
    EXPECT_TOKENn(op); \
    AsmType* b = nullptr; \
    RECURSEn(b = RelationalExpression()); \
    if (a->IsA(AsmType::Signed()) && b->IsA(AsmType::Signed())) { \
      current_function_builder_->Emit(kExpr##sop); \
    } else if (a->IsA(AsmType::Unsigned()) && b->IsA(AsmType::Unsigned())) { \
      current_function_builder_->Emit(kExpr##uop); \
    } else if (a->IsA(AsmType::Double()) && b->IsA(AsmType::Double())) { \
      current_function_builder_->Emit(kExpr##dop); \
    } else if (a->IsA(AsmType::Float()) && b->IsA(AsmType::Float())) { \
      current_function_builder_->Emit(kExpr##fop); \
    } else { \
      FAILn("Expected signed, unsigned, double, or float for operator " #name \
            "."); \
    } \
    a = AsmType::Int(); \
    continue; \
  }
      HANDLE_CASE(TOK(EQ), I32Eq, I32Eq, F64Eq, F32Eq, "==");
      HANDLE_CASE(TOK(NE), I32Ne, I32Ne, F64Ne, F32Ne, "!=");
#undef HANDLE_CASE
      default:
        return a;
    }
  }
}
References v8::internal::EQ, HANDLE_CASE, v8::internal::NE, RECURSEn, RelationalExpression(), scanner_, TOK, and v8::internal::AsmJsScanner::Token().
Referenced by BitwiseANDExpression(), and ValidateCall().
Expression()
AsmType * v8::internal::wasm::AsmJsParser::Expression (AsmType * expect) [private]
Definition at line 1399 of file asm-parser.cc.
                                                  {
  AsmType* a;
  for (;;) {
    RECURSEn(a = AssignmentExpression());
    if (Peek(',')) {
      if (a->IsA(AsmType::None())) {
        FAILn("Expected actual type");
      }
      if (!a->IsA(AsmType::Void())) {
        current_function_builder_->Emit(kExprDrop);
      }
      EXPECT_TOKENn(',');
      continue;
    }
    break;
  }
  if (expected != nullptr && !a->IsA(expected)) {
    FAILn("Unexpected type");
  }
  return a;
}
References AssignmentExpression(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), EXPECT_TOKENn, FAILn, v8::internal::wasm::AsmType::IsA(), v8::None, Peek(), and RECURSEn.
Referenced by DoStatement(), ForStatement(), IfStatement(), ParenthesizedExpression(), ReturnStatement(), SwitchStatement(), ValidateExpression(), ValidateHeapAccess(), and WhileStatement().
ExpressionStatement()
void v8::internal::wasm::AsmJsParser::ExpressionStatement () [private]
Definition at line 1080 of file asm-parser.cc.
                                      {
  if (scanner_.IsGlobal() || scanner_.IsLocal()) {
    // NOTE: Both global or local identifiers can also be used as labels.
    scanner_.Next();
    if (Peek(':')) {
      scanner_.Rewind();
      RECURSE(LabelledStatement());
      return;
    }
    scanner_.Rewind();
  }
  AsmType* ret;
  RECURSE(ret = ValidateExpression());
  if (!ret->IsA(AsmType::Void())) {
    current_function_builder_->Emit(kExprDrop);
  }
  SkipSemicolon();
}
References current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::AsmType::IsA(), v8::internal::AsmJsScanner::IsGlobal(), v8::internal::AsmJsScanner::IsLocal(), LabelledStatement(), v8::internal::AsmJsScanner::Next(), Peek(), RECURSE, v8::internal::AsmJsScanner::Rewind(), scanner_, SkipSemicolon(), and ValidateExpression().
Referenced by ValidateStatement().
failure_location()
int v8::internal::wasm::AsmJsParser::failure_location () const [inline]
Definition at line 57 of file asm-parser.h.
{ return failure_location_; }
References failure_location_.
Referenced by v8::internal::AsmJsCompilationJob::ExecuteJobImpl().
failure_message()
const char* v8::internal::wasm::AsmJsParser::failure_message () const [inline]
Definition at line 56 of file asm-parser.h.
{ return failure_message_; }
References failure_message_.
Referenced by v8::internal::AsmJsCompilationJob::ExecuteJobImpl().
FindBreakLabelDepth()
int v8::internal::wasm::AsmJsParser::FindBreakLabelDepth (AsmJsScanner::token_t label) [private]
Definition at line 316 of file asm-parser.cc.
                                                              {
  int count = 0;
  for (auto it = block_stack_.rbegin(); it != block_stack_.rend();
       ++it, ++count) {
    // A 'break' statement targets ...
    // - The innermost {kRegular} block if no label is given.
    // - The matching {kRegular} or {kNamed} block (when a label is provided).
    if ((it->kind == BlockKind::kRegular &&
         (label == kTokenNone || it->label == label)) ||
        (it->kind == BlockKind::kNamed && it->label == label)) {
      return count;
    }
  }
  return -1;
}
References block_stack_, kNamed, kRegular, and kTokenNone.
Referenced by BreakStatement().
FindContinueLabelDepth()
int v8::internal::wasm::AsmJsParser::FindContinueLabelDepth (AsmJsScanner::token_t label) [private]
Definition at line 301 of file asm-parser.cc.
                                                                 {
  int count = 0;
  for (auto it = block_stack_.rbegin(); it != block_stack_.rend();
       ++it, ++count) {
    // A 'continue' statement targets ...
    // - The innermost {kLoop} block if no label is given.
    // - The matching {kLoop} block (when a label is provided).
    if (it->kind == BlockKind::kLoop &&
        (label == kTokenNone || it->label == label)) {
      return count;
    }
  }
  return -1;
}
References block_stack_, kLoop, and kTokenNone.
Referenced by ContinueStatement().
ForStatement()
void v8::internal::wasm::AsmJsParser::ForStatement () [private]
Definition at line 1216 of file asm-parser.cc.
                               {
  EXPECT_TOKEN(TOK(for));
  EXPECT_TOKEN('(');
  if (!Peek(';')) {
    AsmType* ret;
    RECURSE(ret = Expression(nullptr));
    if (!ret->IsA(AsmType::Void())) {
      current_function_builder_->Emit(kExprDrop);
    }
  }
  EXPECT_TOKEN(';');
  // a: block {
  Begin(pending_label_);
  // b: loop {
  Loop();
  // c: block { // but treated like loop so continue works
  BareBegin(BlockKind::kLoop, pending_label_);
  current_function_builder_->EmitWithU8(kExprBlock, kVoidCode);
  pending_label_ = 0;
  if (!Peek(';')) {
    // if (!CONDITION) break a;
    RECURSE(Expression(AsmType::Int()));
    current_function_builder_->Emit(kExprI32Eqz);
    current_function_builder_->EmitWithU8(kExprBrIf, 2);
  }
  EXPECT_TOKEN(';');
  // Race past INCREMENT
  size_t increment_position = scanner_.Position();
  ScanToClosingParenthesis();
  EXPECT_TOKEN(')');
  // BODY
  RECURSE(ValidateStatement());
  // } // end c
  End();
  // INCREMENT
  size_t end_position = scanner_.Position();
  scanner_.Seek(increment_position);
  if (!Peek(')')) {
    RECURSE(Expression(nullptr));
    // NOTE: No explicit drop because below break is an implicit drop.
  }
  // continue b;
  current_function_builder_->EmitWithU8(kExprBr, 0);
  scanner_.Seek(end_position);
  // } // end b
  End();
  // } // end a
  End();
}
References BareBegin(), Begin(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU8(), End(), EXPECT_TOKEN, Expression(), v8::internal::wasm::AsmType::IsA(), kLoop, v8::internal::wasm::kVoidCode, Loop(), Peek(), pending_label_, v8::internal::AsmJsScanner::Position(), RECURSE, scanner_, ScanToClosingParenthesis(), v8::internal::AsmJsScanner::Seek(), TOK, and ValidateStatement().
Referenced by IterationStatement().
GatherCases()
void v8::internal::wasm::AsmJsParser::GatherCases (ZoneVector< int32_t > * cases) [private]
Definition at line 2547 of file asm-parser.cc.
                                                        {
  size_t start = scanner_.Position();
  int depth = 0;
  for (;;) {
    if (Peek('{')) {
      ++depth;
    } else if (Peek('}')) {
      --depth;
      if (depth <= 0) {
        break;
      }
    } else if (depth == 1 && Peek(TOK(case))) {
      scanner_.Next();
      uint32_t uvalue;
      bool negate = false;
      if (Check('-')) negate = true;
      if (!CheckForUnsigned(&uvalue)) {
        break;
      }
      int32_t value = static_cast<int32_t>(uvalue);
      DCHECK_IMPLIES(negate && uvalue == 0x80000000, value == kMinInt);
      if (negate && value != kMinInt) {
        value = -value;
      }
      cases->push_back(value);
    } else if (Peek(AsmJsScanner::kEndOfInput) ||
               Peek(AsmJsScanner::kParseError)) {
      break;
    }
    scanner_.Next();
  }
  scanner_.Seek(start);
}
References Check(), CheckForUnsigned(), DCHECK_IMPLIES, v8::internal::kMinInt, v8::internal::AsmJsScanner::Next(), Peek(), v8::internal::AsmJsScanner::Position(), v8::internal::ZoneVector< T >::push_back(), scanner_, v8::internal::AsmJsScanner::Seek(), TOK, and v8::internal::value.
Referenced by SwitchStatement().
GetVarInfo()
wasm::AsmJsParser::VarInfo * v8::internal::wasm::AsmJsParser::GetVarInfo (AsmJsScanner::token_t token) [private]
Definition at line 199 of file asm-parser.cc.
                               {
  const bool is_global = AsmJsScanner::IsGlobal(token);
  DCHECK(is_global || AsmJsScanner::IsLocal(token));
  base::Vector<VarInfo>& var_info =
      is_global ? global_var_info_ : local_var_info_;
  size_t old_capacity = var_info.size();
  size_t index = is_global ? AsmJsScanner::GlobalIndex(token)
                           : AsmJsScanner::LocalIndex(token);
  if (is_global && index + 1 > num_globals_) num_globals_ = index + 1;
  if (index + 1 > old_capacity) {
    size_t new_size = std::max(2 * old_capacity, index + 1);
    base::Vector<VarInfo> new_info = zone_->NewVector<VarInfo>(new_size);
    std::copy(var_info.begin(), var_info.end(), new_info.begin());
    var_info = new_info;
  }
  return &var_info[index];
}
References v8::base::Vector< T >::begin(), v8::internal::DCHECK(), v8::base::Vector< T >::end(), global_var_info_, v8::internal::AsmJsScanner::GlobalIndex(), v8::internal::index, v8::internal::AsmJsScanner::IsGlobal(), v8::internal::AsmJsScanner::IsLocal(), local_var_info_, v8::internal::AsmJsScanner::LocalIndex(), v8::internal::Zone::NewVector(), num_globals_, v8::base::Vector< T >::size(), and zone_.
Referenced by AssignmentExpression(), CallExpression(), Identifier(), PeekCall(), ValidateCall(), ValidateExport(), ValidateFloatCoercion(), ValidateFunction(), ValidateFunctionLocals(), ValidateFunctionParams(), ValidateFunctionTable(), ValidateHeapAccess(), ValidateModuleVar(), and ValidateModuleVarFromGlobal().
Identifier()
AsmType * v8::internal::wasm::AsmJsParser::Identifier () [private]
Definition at line 1443 of file asm-parser.cc.
                                 {
  call_coercion_ = nullptr;
  if (scanner_.IsLocal()) {
    VarInfo* info = GetVarInfo(Consume());
    if (info->kind != VarKind::kLocal) {
      FAILn("Undefined local variable");
    }
    current_function_builder_->EmitGetLocal(info->index);
    return info->type;
  } else if (scanner_.IsGlobal()) {
    VarInfo* info = GetVarInfo(Consume());
    if (info->kind != VarKind::kGlobal) {
      FAILn("Undefined global variable");
    }
    current_function_builder_->EmitWithU32V(kExprGlobalGet, VarIndex(info));
    return info->type;
  }
  UNREACHABLE();
}
References call_coercion_, Consume(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::EmitGetLocal(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V(), FAILn, GetVarInfo(), v8::internal::wasm::AsmJsParser::VarInfo::index, v8::internal::AsmJsScanner::IsGlobal(), v8::internal::AsmJsScanner::IsLocal(), kGlobal, v8::internal::wasm::AsmJsParser::VarInfo::kind, kLocal, scanner_, v8::internal::wasm::AsmJsParser::VarInfo::type, v8::internal::UNREACHABLE(), and VarIndex().
Referenced by CallExpression().
IfStatement()
void v8::internal::wasm::AsmJsParser::IfStatement () [private]
Definition at line 1103 of file asm-parser.cc.
                              {
  EXPECT_TOKEN(TOK(if));
  EXPECT_TOKEN('(');
  RECURSE(Expression(AsmType::Int()));
  EXPECT_TOKEN(')');
  BareBegin(BlockKind::kOther);
  current_function_builder_->EmitWithU8(kExprIf, kVoidCode);
  RECURSE(ValidateStatement());
  if (Check(TOK(else))) {
    current_function_builder_->Emit(kExprElse);
    RECURSE(ValidateStatement());
  }
  current_function_builder_->Emit(kExprEnd);
  BareEnd();
}
References BareBegin(), BareEnd(), Check(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU8(), EXPECT_TOKEN, Expression(), kOther, v8::internal::wasm::kVoidCode, RECURSE, TOK, and ValidateStatement().
Referenced by ValidateStatement().
InitializeStdlibTypes()
void v8::internal::wasm::AsmJsParser::InitializeStdlibTypes () [private]
Definition at line 85 of file asm-parser.cc.
                                        {
  auto* d = AsmType::Double();
  auto* dq = AsmType::DoubleQ();
  stdlib_dq2d_ = AsmType::Function(zone(), d);
  stdlib_dq2d_->AsFunctionType()->AddArgument(dq);
  stdlib_dqdq2d_ = AsmType::Function(zone(), d);
  stdlib_dqdq2d_->AsFunctionType()->AddArgument(dq);
  stdlib_dqdq2d_->AsFunctionType()->AddArgument(dq);
  auto* f = AsmType::Float();
  auto* fh = AsmType::Floatish();
  auto* fq = AsmType::FloatQ();
  auto* fq2fh = AsmType::Function(zone(), fh);
  fq2fh->AsFunctionType()->AddArgument(fq);
  auto* s = AsmType::Signed();
  auto* u = AsmType::Unsigned();
  auto* s2u = AsmType::Function(zone(), u);
  s2u->AsFunctionType()->AddArgument(s);
  auto* i = AsmType::Int();
  stdlib_i2s_ = AsmType::Function(zone_, s);
  stdlib_i2s_->AsFunctionType()->AddArgument(i);
  stdlib_ii2s_ = AsmType::Function(zone(), s);
  stdlib_ii2s_->AsFunctionType()->AddArgument(i);
  stdlib_ii2s_->AsFunctionType()->AddArgument(i);
  // The signatures in "9 Standard Library" of the spec draft are outdated and
  // have been superseded with the following by an errata:
  // - Math.min/max : (signed, signed...) -> signed
  // (double, double...) -> double
  // (float, float...) -> float
  auto* minmax_d = AsmType::MinMaxType(zone(), d, d);
  auto* minmax_f = AsmType::MinMaxType(zone(), f, f);
  auto* minmax_s = AsmType::MinMaxType(zone(), s, s);
  stdlib_minmax_ = AsmType::OverloadedFunction(zone());
  stdlib_minmax_->AsOverloadedFunctionType()->AddOverload(minmax_s);
  stdlib_minmax_->AsOverloadedFunctionType()->AddOverload(minmax_f);
  stdlib_minmax_->AsOverloadedFunctionType()->AddOverload(minmax_d);
  // The signatures in "9 Standard Library" of the spec draft are outdated and
  // have been superseded with the following by an errata:
  // - Math.abs : (signed) -> unsigned
  // (double?) -> double
  // (float?) -> floatish
  stdlib_abs_ = AsmType::OverloadedFunction(zone());
  stdlib_abs_->AsOverloadedFunctionType()->AddOverload(s2u);
  stdlib_abs_->AsOverloadedFunctionType()->AddOverload(stdlib_dq2d_);
  stdlib_abs_->AsOverloadedFunctionType()->AddOverload(fq2fh);
  // The signatures in "9 Standard Library" of the spec draft are outdated and
  // have been superseded with the following by an errata:
  // - Math.ceil/floor/sqrt : (double?) -> double
  // (float?) -> floatish
  stdlib_ceil_like_ = AsmType::OverloadedFunction(zone());
  stdlib_ceil_like_->AsOverloadedFunctionType()->AddOverload(stdlib_dq2d_);
  stdlib_ceil_like_->AsOverloadedFunctionType()->AddOverload(fq2fh);
  stdlib_fround_ = AsmType::FroundType(zone());
}
References v8::internal::wasm::AsmType::FroundType(), v8::internal::wasm::AsmType::Function(), v8::internal::wasm::AsmType::MinMaxType(), v8::internal::wasm::AsmType::OverloadedFunction(), v8::base::bits::Signed(), stdlib_abs_, stdlib_ceil_like_, stdlib_dq2d_, stdlib_dqdq2d_, stdlib_fround_, stdlib_i2s_, stdlib_ii2s_, stdlib_minmax_, v8::base::bits::Unsigned(), zone(), and zone_.
Referenced by AsmJsParser().
IterationStatement()
bool v8::internal::wasm::AsmJsParser::IterationStatement () [private]
Definition at line 1147 of file asm-parser.cc.
                                     {
  if (Peek(TOK(while))) {
    WhileStatement();
  } else if (Peek(TOK(do))) {
    DoStatement();
  } else if (Peek(TOK(for))) {
    ForStatement();
  } else {
    return false;
  }
  return true;
}
References DoStatement(), ForStatement(), Peek(), TOK, and WhileStatement().
Referenced by ValidateStatement().
LabelledStatement()
void v8::internal::wasm::AsmJsParser::LabelledStatement () [private]
Definition at line 1299 of file asm-parser.cc.
                                    {
  DCHECK(scanner_.IsGlobal() || scanner_.IsLocal());
  // NOTE: Currently using globals/locals for labels too.
  if (pending_label_ != 0) {
    FAIL("Double label unsupported");
  }
  pending_label_ = scanner_.Token();
  scanner_.Next();
  EXPECT_TOKEN(':');
  RECURSE(ValidateStatement());
}
References v8::internal::DCHECK(), EXPECT_TOKEN, FAIL, v8::internal::AsmJsScanner::IsGlobal(), v8::internal::AsmJsScanner::IsLocal(), v8::internal::AsmJsScanner::Next(), pending_label_, RECURSE, scanner_, v8::internal::AsmJsScanner::Token(), and ValidateStatement().
Referenced by ExpressionStatement().
Loop()
void v8::internal::wasm::AsmJsParser::Loop (AsmJsScanner::token_t label = 0) [private]
Definition at line 277 of file asm-parser.cc.
                                                {
  BareBegin(BlockKind::kLoop, label);
  size_t position = scanner_.Position();
  current_function_builder_->AddAsmWasmOffset(position, position);
  current_function_builder_->EmitWithU8(kExprLoop, kVoidCode);
}
References v8::internal::wasm::WasmFunctionBuilder::AddAsmWasmOffset(), BareBegin(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::EmitWithU8(), kLoop, v8::internal::wasm::kVoidCode, v8::internal::AsmJsScanner::Position(), and scanner_.
Referenced by DoStatement(), ForStatement(), and WhileStatement().
MemberExpression()
AsmType * v8::internal::wasm::AsmJsParser::MemberExpression () [private]
Definition at line 1486 of file asm-parser.cc.
                                       {
  call_coercion_ = nullptr;
  RECURSEn(ValidateHeapAccess());
  DCHECK_NOT_NULL(heap_access_type_);
  if (Peek('=')) {
    inside_heap_assignment_ = true;
    return heap_access_type_->StoreType();
  } else {
#define V(array_type, wasmload, wasmstore, type) \
  if (heap_access_type_->IsA(AsmType::array_type())) { \
    current_function_builder_->EmitWithPrefix(\
        kExpr##type##AsmjsLoad##wasmload); \
    return heap_access_type_->LoadType(); \
  }
    STDLIB_ARRAY_TYPE_LIST(V)
#undef V
    FAILn("Expected valid heap load");
  }
}
References call_coercion_, DCHECK_NOT_NULL, FAILn, heap_access_type_, inside_heap_assignment_, Peek(), RECURSEn, STDLIB_ARRAY_TYPE_LIST, v8::internal::wasm::AsmType::StoreType(), and ValidateHeapAccess().
Referenced by CallExpression().
module_builder()
WasmModuleBuilder* v8::internal::wasm::AsmJsParser::module_builder () [inline]
Definition at line 58 of file asm-parser.h.
{ return module_builder_; }
References module_builder_.
Referenced by v8::internal::AsmJsCompilationJob::ExecuteJobImpl().
MultiplicativeExpression()
AsmType * v8::internal::wasm::AsmJsParser::MultiplicativeExpression () [private]
Definition at line 1676 of file asm-parser.cc.
                                               {
  AsmType* a;
  uint32_t uvalue;
  if (CheckForUnsignedBelow(0x100000, &uvalue)) {
    if (Check('*')) {
      AsmType* type;
      RECURSEn(type = UnaryExpression());
      if (!type->IsA(AsmType::Int())) {
        FAILn("Expected int");
      }
      int32_t value = static_cast<int32_t>(uvalue);
      current_function_builder_->EmitI32Const(value);
      current_function_builder_->Emit(kExprI32Mul);
      return AsmType::Intish();
    } else {
      scanner_.Rewind();
      RECURSEn(a = UnaryExpression());
    }
  } else if (Check('-')) {
    if (!PeekForZero() && CheckForUnsignedBelow(0x100000, &uvalue)) {
      int32_t value = -static_cast<int32_t>(uvalue);
      current_function_builder_->EmitI32Const(value);
      if (Check('*')) {
        AsmType* type;
        RECURSEn(type = UnaryExpression());
        if (!type->IsA(AsmType::Int())) {
          FAILn("Expected int");
        }
        current_function_builder_->Emit(kExprI32Mul);
        return AsmType::Intish();
      }
      a = AsmType::Signed();
    } else {
      scanner_.Rewind();
      RECURSEn(a = UnaryExpression());
    }
  } else {
    RECURSEn(a = UnaryExpression());
  }
  for (;;) {
    if (Check('*')) {
      if (Check('-')) {
        if (!PeekForZero() && CheckForUnsigned(&uvalue)) {
          if (uvalue >= 0x100000) {
            FAILn("Constant multiple out of range");
          }
          if (!a->IsA(AsmType::Int())) {
            FAILn("Integer multiply of expects int");
          }
          int32_t value = -static_cast<int32_t>(uvalue);
          current_function_builder_->EmitI32Const(value);
          current_function_builder_->Emit(kExprI32Mul);
          return AsmType::Intish();
        }
        scanner_.Rewind();
      } else if (CheckForUnsigned(&uvalue)) {
        if (uvalue >= 0x100000) {
          FAILn("Constant multiple out of range");
        }
        if (!a->IsA(AsmType::Int())) {
          FAILn("Integer multiply of expects int");
        }
        int32_t value = static_cast<int32_t>(uvalue);
        current_function_builder_->EmitI32Const(value);
        current_function_builder_->Emit(kExprI32Mul);
        return AsmType::Intish();
      }
      AsmType* b;
      RECURSEn(b = UnaryExpression());
      if (a->IsA(AsmType::DoubleQ()) && b->IsA(AsmType::DoubleQ())) {
        current_function_builder_->Emit(kExprF64Mul);
        a = AsmType::Double();
      } else if (a->IsA(AsmType::FloatQ()) && b->IsA(AsmType::FloatQ())) {
        current_function_builder_->Emit(kExprF32Mul);
        a = AsmType::Floatish();
      } else {
        FAILn("expected doubles or floats");
      }
    } else if (Check('/')) {
      AsmType* b;
      RECURSEn(b = UnaryExpression());
      if (a->IsA(AsmType::DoubleQ()) && b->IsA(AsmType::DoubleQ())) {
        current_function_builder_->Emit(kExprF64Div);
        a = AsmType::Double();
      } else if (a->IsA(AsmType::FloatQ()) && b->IsA(AsmType::FloatQ())) {
        current_function_builder_->Emit(kExprF32Div);
        a = AsmType::Floatish();
      } else if (a->IsA(AsmType::Signed()) && b->IsA(AsmType::Signed())) {
        current_function_builder_->EmitWithPrefix(kExprI32AsmjsDivS);
        a = AsmType::Intish();
      } else if (a->IsA(AsmType::Unsigned()) && b->IsA(AsmType::Unsigned())) {
        current_function_builder_->EmitWithPrefix(kExprI32AsmjsDivU);
        a = AsmType::Intish();
      } else {
        FAILn("expected doubles or floats");
      }
    } else if (Check('%')) {
      AsmType* b;
      RECURSEn(b = UnaryExpression());
      if (a->IsA(AsmType::DoubleQ()) && b->IsA(AsmType::DoubleQ())) {
        current_function_builder_->EmitWithPrefix(kExprF64Mod);
        a = AsmType::Double();
      } else if (a->IsA(AsmType::Signed()) && b->IsA(AsmType::Signed())) {
        current_function_builder_->EmitWithPrefix(kExprI32AsmjsRemS);
        a = AsmType::Intish();
      } else if (a->IsA(AsmType::Unsigned()) && b->IsA(AsmType::Unsigned())) {
        current_function_builder_->EmitWithPrefix(kExprI32AsmjsRemU);
        a = AsmType::Intish();
      } else {
        FAILn("expected doubles or floats");
      }
    } else {
      break;
    }
  }
  return a;
}
References Check(), CheckForUnsigned(), CheckForUnsignedBelow(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitI32Const(), v8::internal::wasm::WasmFunctionBuilder::EmitWithPrefix(), FAILn, v8::internal::wasm::AsmType::IsA(), PeekForZero(), RECURSEn, v8::internal::AsmJsScanner::Rewind(), scanner_, v8::base::bits::Signed(), v8::internal::tracing::type, UnaryExpression(), v8::base::bits::Unsigned(), and v8::internal::value.
Referenced by AdditiveExpression().
NumericLiteral()
AsmType * v8::internal::wasm::AsmJsParser::NumericLiteral () [private]
Definition at line 1422 of file asm-parser.cc.
                                     {
  call_coercion_ = nullptr;
  double dvalue = 0.0;
  uint32_t uvalue = 0;
  if (CheckForDouble(&dvalue)) {
    current_function_builder_->EmitF64Const(dvalue);
    return AsmType::Double();
  } else if (CheckForUnsigned(&uvalue)) {
    if (uvalue <= 0x7FFFFFFF) {
      current_function_builder_->EmitI32Const(static_cast<int32_t>(uvalue));
      return AsmType::FixNum();
    } else {
      current_function_builder_->EmitI32Const(static_cast<int32_t>(uvalue));
      return AsmType::Unsigned();
    }
  } else {
    FAILn("Expected numeric literal.");
  }
}
References call_coercion_, CheckForDouble(), CheckForUnsigned(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::EmitF64Const(), v8::internal::wasm::WasmFunctionBuilder::EmitI32Const(), FAILn, and v8::base::bits::Unsigned().
Referenced by CallExpression().
ParenthesizedExpression()
AsmType * v8::internal::wasm::AsmJsParser::ParenthesizedExpression () [private]
Definition at line 2102 of file asm-parser.cc.
                                              {
  call_coercion_ = nullptr;
  AsmType* ret;
  EXPECT_TOKENn('(');
  RECURSEn(ret = Expression(nullptr));
  EXPECT_TOKENn(')');
  return ret;
}
References call_coercion_, EXPECT_TOKENn, Expression(), and RECURSEn.
Referenced by CallExpression().
Peek()
bool v8::internal::wasm::AsmJsParser::Peek (AsmJsScanner::token_t token) [inline], [private]
Definition at line 249 of file asm-parser.h.
                                              {
    return scanner_.Token() == token;
  }
References scanner_, and v8::internal::AsmJsScanner::Token().
Referenced by AssignmentExpression(), Block(), CallExpression(), Expression(), ExpressionStatement(), ForStatement(), GatherCases(), IterationStatement(), MemberExpression(), PeekCall(), ReturnStatement(), ScanToClosingParenthesis(), SkipSemicolon(), SwitchStatement(), UnaryExpression(), ValidateCall(), ValidateCase(), ValidateDefault(), ValidateExport(), ValidateFunction(), ValidateFunctionLocals(), ValidateFunctionParams(), ValidateFunctionTable(), ValidateModule(), ValidateModuleParameters(), ValidateModuleVar(), ValidateModuleVars(), and ValidateStatement().
PeekCall()
bool v8::internal::wasm::AsmJsParser::PeekCall () [private]
Definition at line 2426 of file asm-parser.cc.
                           {
  if (!scanner_.IsGlobal()) {
    return false;
  }
  if (GetVarInfo(scanner_.Token())->kind == VarKind::kFunction) {
    return true;
  }
  if (GetVarInfo(scanner_.Token())->kind >= VarKind::kImportedFunction) {
    return true;
  }
  if (GetVarInfo(scanner_.Token())->kind == VarKind::kUnused ||
      GetVarInfo(scanner_.Token())->kind == VarKind::kTable) {
    scanner_.Next();
    if (Peek('(') || Peek('[')) {
      scanner_.Rewind();
      return true;
    }
    scanner_.Rewind();
  }
  return false;
}
References GetVarInfo(), v8::internal::AsmJsScanner::IsGlobal(), kFunction, kImportedFunction, v8::internal::wasm::AsmJsParser::VarInfo::kind, kTable, kUnused, v8::internal::AsmJsScanner::Next(), Peek(), v8::internal::AsmJsScanner::Rewind(), scanner_, and v8::internal::AsmJsScanner::Token().
Referenced by CallExpression().
PeekForZero()
bool v8::internal::wasm::AsmJsParser::PeekForZero () [inline], [private]
Definition at line 253 of file asm-parser.h.
                            {
    return (scanner_.IsUnsigned() && scanner_.AsUnsigned() == 0);
  }
References v8::internal::AsmJsScanner::AsUnsigned(), v8::internal::AsmJsScanner::IsUnsigned(), and scanner_.
Referenced by MultiplicativeExpression().
RelationalExpression()
AsmType * v8::internal::wasm::AsmJsParser::RelationalExpression () [private]
Definition at line 1916 of file asm-parser.cc.
                                           {
  AsmType* a = nullptr;
  RECURSEn(a = ShiftExpression());
  for (;;) {
    switch (scanner_.Token()) {
#define HANDLE_CASE(op, sop, uop, dop, fop, name) \
  case op: { \
    EXPECT_TOKENn(op); \
    AsmType* b = nullptr; \
    RECURSEn(b = ShiftExpression()); \
    if (a->IsA(AsmType::Signed()) && b->IsA(AsmType::Signed())) { \
      current_function_builder_->Emit(kExpr##sop); \
    } else if (a->IsA(AsmType::Unsigned()) && b->IsA(AsmType::Unsigned())) { \
      current_function_builder_->Emit(kExpr##uop); \
    } else if (a->IsA(AsmType::Double()) && b->IsA(AsmType::Double())) { \
      current_function_builder_->Emit(kExpr##dop); \
    } else if (a->IsA(AsmType::Float()) && b->IsA(AsmType::Float())) { \
      current_function_builder_->Emit(kExpr##fop); \
    } else { \
      FAILn("Expected signed, unsigned, double, or float for operator " #name \
            "."); \
    } \
    a = AsmType::Int(); \
    continue; \
  }
      HANDLE_CASE('<', I32LtS, I32LtU, F64Lt, F32Lt, "<");
      HANDLE_CASE(TOK(LE), I32LeS, I32LeU, F64Le, F32Le, "<=");
      HANDLE_CASE('>', I32GtS, I32GtU, F64Gt, F32Gt, ">");
      HANDLE_CASE(TOK(GE), I32GeS, I32GeU, F64Ge, F32Ge, ">=");
#undef HANDLE_CASE
      default:
        return a;
    }
  }
}
References v8::internal::GE, HANDLE_CASE, v8::internal::LE, RECURSEn, scanner_, ShiftExpression(), TOK, and v8::internal::AsmJsScanner::Token().
Referenced by EqualityExpression().
ReturnStatement()
void v8::internal::wasm::AsmJsParser::ReturnStatement () [private]
Definition at line 1120 of file asm-parser.cc.
                                  {
  // clang-format off
  EXPECT_TOKEN(TOK(return));
  // clang-format on
  if (!Peek(';') && !Peek('}')) {
    // TODO(bradnelson): See if this can be factored out.
    AsmType* ret;
    RECURSE(ret = Expression(return_type_));
    if (ret->IsA(AsmType::Double())) {
      return_type_ = AsmType::Double();
    } else if (ret->IsA(AsmType::Float())) {
      return_type_ = AsmType::Float();
    } else if (ret->IsA(AsmType::Signed())) {
      return_type_ = AsmType::Signed();
    } else {
      FAIL("Invalid return type");
    }
  } else if (return_type_ == nullptr) {
    return_type_ = AsmType::Void();
  } else if (!return_type_->IsA(AsmType::Void())) {
    FAIL("Invalid void return type");
  }
  current_function_builder_->Emit(kExprReturn);
  SkipSemicolon();
}
References current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), EXPECT_TOKEN, Expression(), FAIL, v8::internal::wasm::AsmType::IsA(), Peek(), RECURSE, return_type_, v8::base::bits::Signed(), SkipSemicolon(), and TOK.
Referenced by ValidateStatement().
Run()
bool v8::internal::wasm::AsmJsParser::Run ()
Definition at line 177 of file asm-parser.cc.
                      {
  ValidateModule();
  return !failed_;
}
References failed_, and ValidateModule().
Referenced by v8::internal::AsmJsCompilationJob::ExecuteJobImpl().
ScanToClosingParenthesis()
void v8::internal::wasm::AsmJsParser::ScanToClosingParenthesis () [private]
Definition at line 2530 of file asm-parser.cc.
                                           {
  int depth = 0;
  for (;;) {
    if (Peek('(')) {
      ++depth;
    } else if (Peek(')')) {
      --depth;
      if (depth < 0) {
        break;
      }
    } else if (Peek(AsmJsScanner::kEndOfInput)) {
      break;
    }
    scanner_.Next();
  }
}
References v8::internal::AsmJsScanner::Next(), Peek(), and scanner_.
Referenced by ForStatement().
ShiftExpression()
AsmType * v8::internal::wasm::AsmJsParser::ShiftExpression () [private]
Definition at line 1856 of file asm-parser.cc.
                                      {
  AsmType* a = nullptr;
  RECURSEn(a = AdditiveExpression());
  heap_access_shift_position_ = kNoHeapAccessShift;
  // TODO(bradnelson): Implement backtracking to avoid emitting code
  // for the x >>> 0 case (similar to what's there for |0).
  for (;;) {
    switch (scanner_.Token()) {
      case TOK(SAR): {
        EXPECT_TOKENn(TOK(SAR));
        heap_access_shift_position_ = kNoHeapAccessShift;
        // Remember position allowing this shift-expression to be used as part
        // of a heap access operation expecting `a >> n:NumericLiteral`.
        bool imm = false;
        size_t old_pos;
        size_t old_code;
        uint32_t shift_imm;
        if (a->IsA(AsmType::Intish()) && CheckForUnsigned(&shift_imm)) {
          old_pos = scanner_.Position();
          old_code = current_function_builder_->GetPosition();
          scanner_.Rewind();
          imm = true;
        }
        AsmType* b = nullptr;
        RECURSEn(b = AdditiveExpression());
        // Check for `a >> n:NumericLiteral` pattern.
        if (imm && old_pos == scanner_.Position()) {
          heap_access_shift_position_ = old_code;
          heap_access_shift_value_ = shift_imm;
        }
        if (!(a->IsA(AsmType::Intish()) && b->IsA(AsmType::Intish()))) {
          FAILn("Expected intish for operator >>.");
        }
        current_function_builder_->Emit(kExprI32ShrS);
        a = AsmType::Signed();
        continue;
      }
#define HANDLE_CASE(op, opcode, name, result) \
  case TOK(op): { \
    EXPECT_TOKENn(TOK(op)); \
    heap_access_shift_position_ = kNoHeapAccessShift; \
    AsmType* b = nullptr; \
    RECURSEn(b = AdditiveExpression()); \
    if (!(a->IsA(AsmType::Intish()) && b->IsA(AsmType::Intish()))) { \
      FAILn("Expected intish for operator " #name "."); \
    } \
    current_function_builder_->Emit(kExpr##opcode); \
    a = AsmType::result(); \
    continue; \
  }
        HANDLE_CASE(SHL, I32Shl, "<<", Signed);
        HANDLE_CASE(SHR, I32ShrU, ">>>", Unsigned);
#undef HANDLE_CASE
      default:
        return a;
    }
  }
}
References AdditiveExpression(), CheckForUnsigned(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), EXPECT_TOKENn, FAILn, v8::internal::wasm::WasmFunctionBuilder::GetPosition(), HANDLE_CASE, heap_access_shift_position_, heap_access_shift_value_, v8::internal::wasm::AsmType::IsA(), kNoHeapAccessShift, v8::internal::AsmJsScanner::Position(), RECURSEn, v8::internal::AsmJsScanner::Rewind(), scanner_, v8::base::bits::Signed(), TOK, v8::internal::AsmJsScanner::Token(), and v8::base::bits::Unsigned().
Referenced by RelationalExpression(), and ValidateHeapAccess().
SkipSemicolon()
void v8::internal::wasm::AsmJsParser::SkipSemicolon () [private]
Definition at line 264 of file asm-parser.cc.
                                {
  if (Check(';')) {
    // Had a semicolon.
  } else if (!Peek('}') && !scanner_.IsPrecededByNewline()) {
    FAIL("Expected ;");
  }
}
References Check(), FAIL, v8::internal::AsmJsScanner::IsPrecededByNewline(), Peek(), and scanner_.
Referenced by BreakStatement(), ContinueStatement(), DoStatement(), ExpressionStatement(), ReturnStatement(), ValidateFunctionLocals(), ValidateFunctionParams(), ValidateFunctionTable(), ValidateModule(), and ValidateModuleVars().
stdlib_uses()
const StdlibSet* v8::internal::wasm::AsmJsParser::stdlib_uses () const [inline]
Definition at line 59 of file asm-parser.h.
{ return &stdlib_uses_; }
References stdlib_uses_.
Referenced by v8::internal::AsmJsCompilationJob::ExecuteJobImpl().
SwitchStatement()
void v8::internal::wasm::AsmJsParser::SwitchStatement () [private]
Definition at line 1312 of file asm-parser.cc.
                                  {
  EXPECT_TOKEN(TOK(switch));
  EXPECT_TOKEN('(');
  AsmType* test;
  RECURSE(test = Expression(nullptr));
  if (!test->IsA(AsmType::Signed())) {
    FAIL("Expected signed for switch value");
  }
  EXPECT_TOKEN(')');
  uint32_t tmp = TempVariable(0);
  current_function_builder_->EmitSetLocal(tmp);
  Begin(pending_label_);
  pending_label_ = 0;
  // TODO(bradnelson): Make less weird.
  CachedVector<int32_t> cases(&cached_int_vectors_);
  GatherCases(&cases);
  EXPECT_TOKEN('{');
  size_t count = cases.size() + 1;
  for (size_t i = 0; i < count; ++i) {
    BareBegin(BlockKind::kOther);
    current_function_builder_->EmitWithU8(kExprBlock, kVoidCode);
  }
  int table_pos = 0;
  for (auto c : cases) {
    current_function_builder_->EmitGetLocal(tmp);
    current_function_builder_->EmitI32Const(c);
    current_function_builder_->Emit(kExprI32Eq);
    current_function_builder_->EmitWithU32V(kExprBrIf, table_pos++);
  }
  current_function_builder_->EmitWithU32V(kExprBr, table_pos++);
  while (!failed_ && Peek(TOK(case))) {
    current_function_builder_->Emit(kExprEnd);
    BareEnd();
    RECURSE(ValidateCase());
  }
  current_function_builder_->Emit(kExprEnd);
  BareEnd();
  if (Peek(TOK(default))) {
    RECURSE(ValidateDefault());
  }
  EXPECT_TOKEN('}');
  End();
}
References BareBegin(), BareEnd(), Begin(), cached_int_vectors_, current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitGetLocal(), v8::internal::wasm::WasmFunctionBuilder::EmitI32Const(), v8::internal::wasm::WasmFunctionBuilder::EmitSetLocal(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU8(), End(), EXPECT_TOKEN, Expression(), FAIL, failed_, GatherCases(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::AsmType::IsA(), kOther, v8::internal::wasm::kVoidCode, Peek(), pending_label_, RECURSE, v8::base::bits::Signed(), v8::internal::ZoneVector< T >::size(), TempVariable(), TOK, ValidateCase(), and ValidateDefault().
Referenced by ValidateStatement().
TempVariable()
uint32_t v8::internal::wasm::AsmJsParser::TempVariable (int index) [private]
Definition at line 253 of file asm-parser.cc.
                                            {
  if (index + 1 > function_temp_locals_used_) {
    function_temp_locals_used_ = index + 1;
  }
  return function_temp_locals_offset_ + index;
}
References function_temp_locals_offset_, function_temp_locals_used_, and v8::internal::index.
Referenced by SwitchStatement().
UnaryExpression()
AsmType * v8::internal::wasm::AsmJsParser::UnaryExpression () [private]
Definition at line 1588 of file asm-parser.cc.
                                      {
  AsmType* ret;
  if (Check('-')) {
    uint32_t uvalue;
    if (CheckForUnsigned(&uvalue)) {
      if (uvalue == 0) {
        current_function_builder_->EmitF64Const(-0.0);
        ret = AsmType::Double();
      } else if (uvalue <= 0x80000000) {
        // TODO(bradnelson): was supposed to be 0x7FFFFFFF, check errata.
        current_function_builder_->EmitI32Const(
            base::NegateWithWraparound(static_cast<int32_t>(uvalue)));
        ret = AsmType::Signed();
      } else {
        FAILn("Integer numeric literal out of range.");
      }
    } else {
      RECURSEn(ret = UnaryExpression());
      if (ret->IsA(AsmType::Int())) {
        TemporaryVariableScope tmp(this);
        current_function_builder_->EmitSetLocal(tmp.get());
        current_function_builder_->EmitI32Const(0);
        current_function_builder_->EmitGetLocal(tmp.get());
        current_function_builder_->Emit(kExprI32Sub);
        ret = AsmType::Intish();
      } else if (ret->IsA(AsmType::DoubleQ())) {
        current_function_builder_->Emit(kExprF64Neg);
        ret = AsmType::Double();
      } else if (ret->IsA(AsmType::FloatQ())) {
        current_function_builder_->Emit(kExprF32Neg);
        ret = AsmType::Floatish();
      } else {
        FAILn("expected int/double?/float?");
      }
    }
  } else if (Peek('+')) {
    call_coercion_ = AsmType::Double();
    call_coercion_position_ = scanner_.Position();
    scanner_.Next(); // Done late for correct position.
    RECURSEn(ret = UnaryExpression());
    // TODO(bradnelson): Generalize.
    if (ret->IsA(AsmType::Signed())) {
      current_function_builder_->Emit(kExprF64SConvertI32);
      ret = AsmType::Double();
    } else if (ret->IsA(AsmType::Unsigned())) {
      current_function_builder_->Emit(kExprF64UConvertI32);
      ret = AsmType::Double();
    } else if (ret->IsA(AsmType::DoubleQ())) {
      ret = AsmType::Double();
    } else if (ret->IsA(AsmType::FloatQ())) {
      current_function_builder_->Emit(kExprF64ConvertF32);
      ret = AsmType::Double();
    } else {
      FAILn("expected signed/unsigned/double?/float?");
    }
  } else if (Check('!')) {
    RECURSEn(ret = UnaryExpression());
    if (!ret->IsA(AsmType::Int())) {
      FAILn("expected int");
    }
    current_function_builder_->Emit(kExprI32Eqz);
  } else if (Check('~')) {
    if (Check('~')) {
      RECURSEn(ret = UnaryExpression());
      if (ret->IsA(AsmType::Double())) {
        current_function_builder_->EmitWithPrefix(kExprI32AsmjsSConvertF64);
      } else if (ret->IsA(AsmType::FloatQ())) {
        current_function_builder_->EmitWithPrefix(kExprI32AsmjsSConvertF32);
      } else {
        FAILn("expected double or float?");
      }
      ret = AsmType::Signed();
    } else {
      RECURSEn(ret = UnaryExpression());
      if (!ret->IsA(AsmType::Intish())) {
        FAILn("operator ~ expects intish");
      }
      current_function_builder_->EmitI32Const(0xFFFFFFFF);
      current_function_builder_->Emit(kExprI32Xor);
      ret = AsmType::Signed();
    }
  } else {
    RECURSEn(ret = CallExpression());
  }
  return ret;
}
References call_coercion_, call_coercion_position_, CallExpression(), Check(), CheckForUnsigned(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitF64Const(), v8::internal::wasm::WasmFunctionBuilder::EmitGetLocal(), v8::internal::wasm::WasmFunctionBuilder::EmitI32Const(), v8::internal::wasm::WasmFunctionBuilder::EmitSetLocal(), v8::internal::wasm::WasmFunctionBuilder::EmitWithPrefix(), FAILn, v8::internal::wasm::AsmJsParser::TemporaryVariableScope::get(), v8::internal::wasm::AsmType::IsA(), v8::base::NegateWithWraparound(), v8::internal::AsmJsScanner::Next(), Peek(), v8::internal::AsmJsScanner::Position(), RECURSEn, scanner_, v8::base::bits::Signed(), and v8::base::bits::Unsigned().
Referenced by MultiplicativeExpression().
ValidateCall()
AsmType * v8::internal::wasm::AsmJsParser::ValidateCall () [private]
Definition at line 2112 of file asm-parser.cc.
                                   {
  AsmType* return_type = call_coercion_;
  call_coercion_ = nullptr;
  size_t call_pos = scanner_.Position();
  size_t to_number_pos = call_coercion_position_;
  bool allow_peek = (call_coercion_deferred_position_ == scanner_.Position());
  AsmJsScanner::token_t function_name = Consume();
  // Distinguish between ordinary function calls and function table calls. In
  // both cases we might be seeing the {function_name} for the first time and
  // hence allocate a {VarInfo} here, all subsequent uses of the same name then
  // need to match the information stored at this point.
  std::optional<TemporaryVariableScope> tmp_scope;
  if (Check('[')) {
    AsmType* index = nullptr;
    RECURSEn(index = EqualityExpression());
    if (!index->IsA(AsmType::Intish())) {
      FAILn("Expected intish index");
    }
    EXPECT_TOKENn('&');
    uint32_t mask = 0;
    if (!CheckForUnsigned(&mask)) {
      FAILn("Expected mask literal");
    }
    if (!base::bits::IsPowerOfTwo(mask + 1)) {
      FAILn("Expected power of 2 mask");
    }
    current_function_builder_->EmitI32Const(mask);
    current_function_builder_->Emit(kExprI32And);
    EXPECT_TOKENn(']');
    VarInfo* function_info = GetVarInfo(function_name);
    if (function_info->kind == VarKind::kUnused) {
      if (module_builder_->NumTables() == 0) {
        module_builder_->AddTable(kWasmFuncRef, 0);
      }
      uint32_t func_index = module_builder_->IncreaseTableMinSize(0, mask + 1);
      if (func_index == std::numeric_limits<uint32_t>::max()) {
        FAILn("Exceeded maximum function table size");
      }
      function_info->kind = VarKind::kTable;
      function_info->mask = mask;
      function_info->index = func_index;
      function_info->mutable_variable = false;
    } else {
      if (function_info->kind != VarKind::kTable) {
        FAILn("Expected call table");
      }
      if (function_info->mask != mask) {
        FAILn("Mask size mismatch");
      }
    }
    current_function_builder_->EmitI32Const(function_info->index);
    current_function_builder_->Emit(kExprI32Add);
    // We have to use a temporary for the correct order of evaluation.
    tmp_scope.emplace(this);
    current_function_builder_->EmitSetLocal(tmp_scope->get());
    // The position of function table calls is after the table lookup.
    call_pos = scanner_.Position();
  } else {
    VarInfo* function_info = GetVarInfo(function_name);
    if (function_info->kind == VarKind::kUnused) {
      function_info->kind = VarKind::kFunction;
      function_info->function_builder = module_builder_->AddFunction();
      function_info->index = function_info->function_builder->func_index();
      function_info->mutable_variable = false;
    } else {
      if (function_info->kind != VarKind::kFunction &&
          function_info->kind < VarKind::kImportedFunction) {
        FAILn("Expected function as call target");
      }
    }
  }
  // Parse argument list and gather types.
  CachedVector<AsmType*> param_types(&cached_asm_type_p_vectors_);
  CachedVector<AsmType*> param_specific_types(&cached_asm_type_p_vectors_);
  EXPECT_TOKENn('(');
  while (!failed_ && !Peek(')')) {
    AsmType* t;
    RECURSEn(t = AssignmentExpression());
    param_specific_types.push_back(t);
    if (t->IsA(AsmType::Int())) {
      param_types.push_back(AsmType::Int());
    } else if (t->IsA(AsmType::Float())) {
      param_types.push_back(AsmType::Float());
    } else if (t->IsA(AsmType::Double())) {
      param_types.push_back(AsmType::Double());
    } else {
      FAILn("Bad function argument type");
    }
    if (!Peek(')')) {
      EXPECT_TOKENn(',');
    }
  }
  EXPECT_TOKENn(')');
  // Reload {VarInfo} after parsing arguments as table might have grown.
  VarInfo* function_info = GetVarInfo(function_name);
  // We potentially use lookahead in order to determine the return type in case
  // it is not yet clear from the call context. Special care has to be taken to
  // ensure the non-contextual lookahead is valid. The following restrictions
  // substantiate the validity of the lookahead implemented below:
  // - All calls (except stdlib calls) require some sort of type annotation.
  // - The coercion to "signed" is part of the {BitwiseORExpression}, any
  // intermittent expressions like parenthesis in `(callsite(..))|0` are
  // syntactically not considered coercions.
  // - The coercion to "double" as part of the {UnaryExpression} has higher
  // precedence and wins in `+callsite(..)|0` cases. Only "float" return
  // types are overridden in `fround(callsite(..)|0)` expressions.
  // - Expected coercions to "signed" are flagged via {call_coercion_deferred}
  // and later on validated as part of {BitwiseORExpression} to ensure they
  // indeed apply to the current call expression.
  // - The deferred validation is only allowed if {BitwiseORExpression} did
  // promise to fulfill the request via {call_coercion_deferred_position}.
  if (allow_peek && Peek('|') &&
      function_info->kind <= VarKind::kImportedFunction &&
      (return_type == nullptr || return_type->IsA(AsmType::Float()))) {
    DCHECK_NULL(call_coercion_deferred_);
    call_coercion_deferred_ = AsmType::Signed();
    to_number_pos = scanner_.Position();
    return_type = AsmType::Signed();
  } else if (return_type == nullptr) {
    to_number_pos = call_pos; // No conversion.
    return_type = AsmType::Void();
  }
  // Compute function type and signature based on gathered types.
  AsmType* function_type = AsmType::Function(zone(), return_type);
  for (auto t : param_types) {
    function_type->AsFunctionType()->AddArgument(t);
  }
  FunctionSig* sig = ConvertSignature(return_type, param_types);
  ModuleTypeIndex signature_index = module_builder_->AddSignature(sig, true);
  // Emit actual function invocation depending on the kind. At this point we
  // also determined the complete function type and can perform checking against
  // the expected type or update the expected type in case of first occurrence.
  if (function_info->kind == VarKind::kImportedFunction) {
    if (param_types.size() > kV8MaxWasmFunctionParams) {
      FAILn("Number of parameters exceeds internal limit");
    }
    for (auto t : param_specific_types) {
      if (!t->IsA(AsmType::Extern())) {
        FAILn("Imported function args must be type extern");
      }
    }
    if (return_type->IsA(AsmType::Float())) {
      FAILn("Imported function can't be called as float");
    }
    DCHECK_NOT_NULL(function_info->import);
    // TODO(bradnelson): Factor out.
    uint32_t index;
    auto it = function_info->import->cache.find(*sig);
    if (it != function_info->import->cache.end()) {
      index = it->second;
      DCHECK(function_info->function_defined);
    } else {
      index =
          module_builder_->AddImport(function_info->import->function_name, sig);
      function_info->import->cache[*sig] = index;
      function_info->function_defined = true;
    }
    current_function_builder_->AddAsmWasmOffset(call_pos, to_number_pos);
    current_function_builder_->EmitWithU32V(kExprCallFunction, index);
  } else if (function_info->kind > VarKind::kImportedFunction) {
    AsmCallableType* callable = function_info->type->AsCallableType();
    if (!callable) {
      FAILn("Expected callable function");
    }
    // TODO(bradnelson): Refactor AsmType to not need this.
    if (callable->CanBeInvokedWith(return_type, param_specific_types)) {
      // Return type ok.
    } else if (callable->CanBeInvokedWith(AsmType::Float(),
                                          param_specific_types)) {
      return_type = AsmType::Float();
    } else if (callable->CanBeInvokedWith(AsmType::Floatish(),
                                          param_specific_types)) {
      return_type = AsmType::Floatish();
    } else if (callable->CanBeInvokedWith(AsmType::Double(),
                                          param_specific_types)) {
      return_type = AsmType::Double();
    } else if (callable->CanBeInvokedWith(AsmType::Signed(),
                                          param_specific_types)) {
      return_type = AsmType::Signed();
    } else if (callable->CanBeInvokedWith(AsmType::Unsigned(),
                                          param_specific_types)) {
      return_type = AsmType::Unsigned();
    } else {
      FAILn("Function use doesn't match definition");
    }
    switch (function_info->kind) {
#define V(name, Name, op, sig) \
  case VarKind::kMath##Name: \
    if ((op) <= 0xff) { \
      current_function_builder_->Emit(op); \
    } else { \
      current_function_builder_->EmitWithPrefix(op); \
    } \
    break;
      STDLIB_MATH_FUNCTION_MONOMORPHIC_LIST(V)
#undef V
#define V(name, Name, op, sig) \
  case VarKind::kMath##Name: \
    if (param_specific_types[0]->IsA(AsmType::DoubleQ())) { \
      current_function_builder_->Emit(kExprF64##Name); \
    } else if (param_specific_types[0]->IsA(AsmType::FloatQ())) { \
      current_function_builder_->Emit(kExprF32##Name); \
    } else { \
      UNREACHABLE(); \
    } \
    break;
      STDLIB_MATH_FUNCTION_CEIL_LIKE_LIST(V)
#undef V
      case VarKind::kMathMin:
      case VarKind::kMathMax:
        if (param_specific_types[0]->IsA(AsmType::Double())) {
          for (size_t i = 1; i < param_specific_types.size(); ++i) {
            if (function_info->kind == VarKind::kMathMin) {
              current_function_builder_->Emit(kExprF64Min);
            } else {
              current_function_builder_->Emit(kExprF64Max);
            }
          }
        } else if (param_specific_types[0]->IsA(AsmType::Float())) {
          // NOTE: Not technically part of the asm.js spec, but Firefox
          // accepts it.
          for (size_t i = 1; i < param_specific_types.size(); ++i) {
            if (function_info->kind == VarKind::kMathMin) {
              current_function_builder_->Emit(kExprF32Min);
            } else {
              current_function_builder_->Emit(kExprF32Max);
            }
          }
        } else if (param_specific_types[0]->IsA(AsmType::Signed())) {
          TemporaryVariableScope tmp_x(this);
          TemporaryVariableScope tmp_y(this);
          for (size_t i = 1; i < param_specific_types.size(); ++i) {
            current_function_builder_->EmitSetLocal(tmp_x.get());
            current_function_builder_->EmitTeeLocal(tmp_y.get());
            current_function_builder_->EmitGetLocal(tmp_x.get());
            if (function_info->kind == VarKind::kMathMin) {
              current_function_builder_->Emit(kExprI32GeS);
            } else {
              current_function_builder_->Emit(kExprI32LeS);
            }
            current_function_builder_->EmitWithU8(kExprIf, kI32Code);
            current_function_builder_->EmitGetLocal(tmp_x.get());
            current_function_builder_->Emit(kExprElse);
            current_function_builder_->EmitGetLocal(tmp_y.get());
            current_function_builder_->Emit(kExprEnd);
          }
        } else {
          UNREACHABLE();
        }
        break;
      case VarKind::kMathAbs:
        if (param_specific_types[0]->IsA(AsmType::Signed())) {
          TemporaryVariableScope tmp(this);
          current_function_builder_->EmitTeeLocal(tmp.get());
          current_function_builder_->EmitGetLocal(tmp.get());
          current_function_builder_->EmitI32Const(31);
          current_function_builder_->Emit(kExprI32ShrS);
          current_function_builder_->EmitTeeLocal(tmp.get());
          current_function_builder_->Emit(kExprI32Xor);
          current_function_builder_->EmitGetLocal(tmp.get());
          current_function_builder_->Emit(kExprI32Sub);
        } else if (param_specific_types[0]->IsA(AsmType::DoubleQ())) {
          current_function_builder_->Emit(kExprF64Abs);
        } else if (param_specific_types[0]->IsA(AsmType::FloatQ())) {
          current_function_builder_->Emit(kExprF32Abs);
        } else {
          UNREACHABLE();
        }
        break;
      case VarKind::kMathFround:
        // NOTE: Handled in {AsmJsParser::CallExpression} specially and treated
        // as a coercion to "float" type. Cannot be reached as a call here.
        UNREACHABLE();
      default:
        UNREACHABLE();
    }
  } else {
    DCHECK(function_info->kind == VarKind::kFunction ||
           function_info->kind == VarKind::kTable);
    if (function_info->type->IsA(AsmType::None())) {
      function_info->type = function_type;
    } else {
      AsmCallableType* callable = function_info->type->AsCallableType();
      if (!callable ||
          !callable->CanBeInvokedWith(return_type, param_specific_types)) {
        FAILn("Function use doesn't match definition");
      }
    }
    if (function_info->kind == VarKind::kTable) {
      current_function_builder_->EmitGetLocal(tmp_scope->get());
      current_function_builder_->AddAsmWasmOffset(call_pos, to_number_pos);
      current_function_builder_->Emit(kExprCallIndirect);
      current_function_builder_->EmitU32V(signature_index);
      current_function_builder_->EmitU32V(0); // table index
    } else {
      current_function_builder_->AddAsmWasmOffset(call_pos, to_number_pos);
      current_function_builder_->Emit(kExprCallFunction);
      current_function_builder_->EmitDirectCallIndex(function_info->index);
    }
  }
  return return_type;
}
References v8::internal::wasm::WasmFunctionBuilder::AddAsmWasmOffset(), v8::internal::wasm::WasmModuleBuilder::AddFunction(), v8::internal::wasm::WasmModuleBuilder::AddImport(), v8::internal::wasm::WasmModuleBuilder::AddSignature(), v8::internal::wasm::WasmModuleBuilder::AddTable(), v8::internal::wasm::AsmType::AsCallableType(), AssignmentExpression(), v8::internal::wasm::AsmJsParser::FunctionImportInfo::cache, cached_asm_type_p_vectors_, call_coercion_, call_coercion_deferred_, call_coercion_deferred_position_, call_coercion_position_, v8::internal::wasm::AsmCallableType::CanBeInvokedWith(), Check(), CheckForUnsigned(), Consume(), ConvertSignature(), current_function_builder_, v8::internal::DCHECK(), DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitDirectCallIndex(), v8::internal::wasm::WasmFunctionBuilder::EmitGetLocal(), v8::internal::wasm::WasmFunctionBuilder::EmitI32Const(), v8::internal::wasm::WasmFunctionBuilder::EmitSetLocal(), v8::internal::wasm::WasmFunctionBuilder::EmitTeeLocal(), v8::internal::wasm::WasmFunctionBuilder::EmitU32V(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU8(), EqualityExpression(), EXPECT_TOKENn, failed_, FAILn, v8::internal::wasm::WasmFunctionBuilder::func_index(), v8::internal::wasm::AsmType::Function(), v8::internal::wasm::AsmJsParser::VarInfo::function_builder, v8::internal::wasm::AsmJsParser::VarInfo::function_defined, v8::internal::wasm::AsmJsParser::FunctionImportInfo::function_name, v8::internal::wasm::AsmJsParser::TemporaryVariableScope::get(), GetVarInfo(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::AsmJsParser::VarInfo::import, v8::internal::wasm::WasmModuleBuilder::IncreaseTableMinSize(), v8::internal::wasm::AsmJsParser::VarInfo::index, v8::internal::index, v8::internal::wasm::AsmType::IsA(), v8::base::bits::IsPowerOfTwo(), kFunction, v8::internal::wasm::kI32Code, kImportedFunction, v8::internal::wasm::AsmJsParser::VarInfo::kind, kTable, kUnused, v8::internal::wasm::kV8MaxWasmFunctionParams, v8::internal::wasm::kWasmFuncRef, v8::internal::wasm::AsmJsParser::VarInfo::mask, module_builder_, v8::internal::wasm::AsmJsParser::VarInfo::mutable_variable, v8::None, v8::internal::wasm::WasmModuleBuilder::NumTables(), Peek(), v8::internal::AsmJsScanner::Position(), v8::internal::ZoneVector< T >::push_back(), RECURSEn, scanner_, v8::internal::sig, v8::base::bits::Signed(), v8::internal::ZoneVector< T >::size(), STDLIB_MATH_FUNCTION_CEIL_LIKE_LIST, STDLIB_MATH_FUNCTION_MONOMORPHIC_LIST, v8::internal::wasm::AsmJsParser::VarInfo::type, v8::internal::UNREACHABLE(), v8::base::bits::Unsigned(), and zone().
Referenced by CallExpression().
ValidateCase()
void v8::internal::wasm::AsmJsParser::ValidateCase () [private]
Definition at line 1357 of file asm-parser.cc.
                               {
  EXPECT_TOKEN(TOK(case));
  bool negate = false;
  if (Check('-')) {
    negate = true;
  }
  uint32_t uvalue;
  if (!CheckForUnsigned(&uvalue)) {
    FAIL("Expected numeric literal");
  }
  // TODO(bradnelson): Share negation plumbing.
  if ((negate && uvalue > 0x80000000) || (!negate && uvalue > 0x7FFFFFFF)) {
    FAIL("Numeric literal out of range");
  }
  int32_t value = static_cast<int32_t>(uvalue);
  DCHECK_IMPLIES(negate && uvalue == 0x80000000, value == kMinInt);
  if (negate && value != kMinInt) {
    value = -value;
  }
  EXPECT_TOKEN(':');
  while (!failed_ && !Peek('}') && !Peek(TOK(case)) && !Peek(TOK(default))) {
    RECURSE(ValidateStatement());
  }
}
References Check(), CheckForUnsigned(), DCHECK_IMPLIES, EXPECT_TOKEN, FAIL, failed_, v8::internal::kMinInt, Peek(), RECURSE, TOK, ValidateStatement(), and v8::internal::value.
Referenced by SwitchStatement().
ValidateDefault()
void v8::internal::wasm::AsmJsParser::ValidateDefault () [private]
Definition at line 1383 of file asm-parser.cc.
                                  {
  EXPECT_TOKEN(TOK(default));
  EXPECT_TOKEN(':');
  while (!failed_ && !Peek('}')) {
    RECURSE(ValidateStatement());
  }
}
References EXPECT_TOKEN, failed_, Peek(), RECURSE, TOK, and ValidateStatement().
Referenced by SwitchStatement().
ValidateExport()
void v8::internal::wasm::AsmJsParser::ValidateExport () [private]
Definition at line 631 of file asm-parser.cc.
                                 {
  // clang-format off
  EXPECT_TOKEN(TOK(return));
  // clang-format on
  if (Check('{')) {
    for (;;) {
      base::Vector<const char> name = CopyCurrentIdentifierString();
      if (!scanner_.IsGlobal() && !scanner_.IsLocal()) {
        FAIL("Illegal export name");
      }
      Consume();
      EXPECT_TOKEN(':');
      if (!scanner_.IsGlobal()) {
        FAIL("Expected function name");
      }
      VarInfo* info = GetVarInfo(Consume());
      if (info->kind != VarKind::kFunction) {
        FAIL("Expected function");
      }
      module_builder_->AddExport(name, info->function_builder);
      if (Check(',')) {
        if (!Peek('}')) {
          continue;
        }
      }
      break;
    }
    EXPECT_TOKEN('}');
  } else {
    if (!scanner_.IsGlobal()) {
      FAIL("Single function export must be a function name");
    }
    VarInfo* info = GetVarInfo(Consume());
    if (info->kind != VarKind::kFunction) {
      FAIL("Single function export must be a function");
    }
    module_builder_->AddExport(base::CStrVector(AsmJs::kSingleFunctionName),
                               info->function_builder);
  }
}
References v8::internal::wasm::WasmModuleBuilder::AddExport(), Check(), Consume(), CopyCurrentIdentifierString(), v8::base::CStrVector(), EXPECT_TOKEN, FAIL, v8::internal::wasm::AsmJsParser::VarInfo::function_builder, GetVarInfo(), v8::internal::AsmJsScanner::IsGlobal(), v8::internal::AsmJsScanner::IsLocal(), kFunction, v8::internal::wasm::AsmJsParser::VarInfo::kind, v8::internal::AsmJs::kSingleFunctionName, module_builder_, v8::internal::wasm::name(), Peek(), scanner_, and TOK.
Referenced by ValidateModule().
ValidateExpression()
AsmType * v8::internal::wasm::AsmJsParser::ValidateExpression () [private]
Definition at line 1392 of file asm-parser.cc.
                                         {
  AsmType* ret;
  RECURSEn(ret = Expression(nullptr));
  return ret;
}
References Expression(), and RECURSEn.
Referenced by ExpressionStatement().
ValidateFloatCoercion()
void v8::internal::wasm::AsmJsParser::ValidateFloatCoercion () [private]
Definition at line 2503 of file asm-parser.cc.
                                        {
  if (!scanner_.IsGlobal() ||
      !GetVarInfo(scanner_.Token())->type->IsA(stdlib_fround_)) {
    FAIL("Expected fround");
  }
  scanner_.Next();
  EXPECT_TOKEN('(');
  call_coercion_ = AsmType::Float();
  // NOTE: The coercion position to float is not observable from JavaScript,
  // because imported functions are not allowed to have float return type.
  call_coercion_position_ = scanner_.Position();
  AsmType* ret;
  RECURSE(ret = AssignmentExpression());
  if (ret->IsA(AsmType::Floatish())) {
    // Do nothing, as already a float.
  } else if (ret->IsA(AsmType::DoubleQ())) {
    current_function_builder_->Emit(kExprF32ConvertF64);
  } else if (ret->IsA(AsmType::Signed())) {
    current_function_builder_->Emit(kExprF32SConvertI32);
  } else if (ret->IsA(AsmType::Unsigned())) {
    current_function_builder_->Emit(kExprF32UConvertI32);
  } else {
    FAIL("Illegal conversion to float");
  }
  EXPECT_TOKEN(')');
}
References AssignmentExpression(), call_coercion_, call_coercion_position_, current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), EXPECT_TOKEN, FAIL, GetVarInfo(), v8::internal::wasm::AsmType::IsA(), v8::internal::AsmJsScanner::IsGlobal(), v8::internal::AsmJsScanner::Next(), v8::internal::AsmJsScanner::Position(), RECURSE, scanner_, v8::base::bits::Signed(), stdlib_fround_, v8::internal::AsmJsScanner::Token(), v8::internal::wasm::AsmJsParser::VarInfo::type, and v8::base::bits::Unsigned().
Referenced by CallExpression().
ValidateFunction()
void v8::internal::wasm::AsmJsParser::ValidateFunction () [private]
Definition at line 728 of file asm-parser.cc.
                                   {
  // Remember position of the 'function' token as start position.
  size_t function_start_position = scanner_.Position();
  EXPECT_TOKEN(TOK(function));
  if (!scanner_.IsGlobal()) {
    FAIL("Expected function name");
  }
  base::Vector<const char> function_name_str = CopyCurrentIdentifierString();
  AsmJsScanner::token_t function_name = Consume();
  VarInfo* function_info = GetVarInfo(function_name);
  if (function_info->kind == VarKind::kUnused) {
    function_info->kind = VarKind::kFunction;
    function_info->function_builder = module_builder_->AddFunction();
    function_info->index = function_info->function_builder->func_index();
    function_info->mutable_variable = false;
  } else if (function_info->kind != VarKind::kFunction) {
    FAIL("Function name collides with variable");
  } else if (function_info->function_defined) {
    FAIL("Function redefined");
  }
  function_info->function_defined = true;
  function_info->function_builder->SetName(function_name_str);
  current_function_builder_ = function_info->function_builder;
  return_type_ = nullptr;
  // Record start of the function, used as position for the stack check.
  current_function_builder_->SetAsmFunctionStartPosition(
      function_start_position);
  CachedVector<AsmType*> params(&cached_asm_type_p_vectors_);
  ValidateFunctionParams(&params);
  // Check against limit on number of parameters.
  if (params.size() > kV8MaxWasmFunctionParams) {
    FAIL("Number of parameters exceeds internal limit");
  }
  CachedVector<ValueType> locals(&cached_valuetype_vectors_);
  ValidateFunctionLocals(params.size(), &locals);
  function_temp_locals_offset_ = static_cast<uint32_t>(
      params.size() + locals.size());
  function_temp_locals_used_ = 0;
  function_temp_locals_depth_ = 0;
  bool last_statement_is_return = false;
  while (!failed_ && !Peek('}')) {
    // clang-format off
    last_statement_is_return = Peek(TOK(return));
    // clang-format on
    RECURSE(ValidateStatement());
  }
  size_t function_end_position = scanner_.Position() + 1;
  EXPECT_TOKEN('}');
  if (!last_statement_is_return) {
    if (return_type_ == nullptr) {
      return_type_ = AsmType::Void();
    } else if (!return_type_->IsA(AsmType::Void())) {
      FAIL("Expected return at end of non-void function");
    }
  }
  DCHECK_NOT_NULL(return_type_);
  // TODO(bradnelson): WasmModuleBuilder can't take this in the right order.
  // We should fix that so we can use it instead.
  FunctionSig* sig = ConvertSignature(return_type_, params);
  current_function_builder_->SetSignature(sig);
  for (auto local : locals) {
    current_function_builder_->AddLocal(local);
  }
  // Add bonus temps.
  for (int i = 0; i < function_temp_locals_used_; ++i) {
    current_function_builder_->AddLocal(kWasmI32);
  }
  // Check against limit on number of local variables.
  if (locals.size() + function_temp_locals_used_ > kV8MaxWasmFunctionLocals) {
    FAIL("Number of local variables exceeds internal limit");
  }
  // End function
  current_function_builder_->Emit(kExprEnd);
  // Emit function end position as the last position for this function.
  current_function_builder_->AddAsmWasmOffset(function_end_position,
                                              function_end_position);
  if (current_function_builder_->GetPosition() > kV8MaxWasmFunctionSize) {
    FAIL("Size of function body exceeds internal limit");
  }
  // Record (or validate) function type.
  AsmType* function_type = AsmType::Function(zone(), return_type_);
  for (auto t : params) {
    function_type->AsFunctionType()->AddArgument(t);
  }
  function_info = GetVarInfo(function_name);
  if (function_info->type->IsA(AsmType::None())) {
    DCHECK_EQ(function_info->kind, VarKind::kFunction);
    function_info->type = function_type;
  } else if (!function_type->IsA(function_info->type)) {
    // TODO(bradnelson): Should IsExactly be used here?
    FAIL("Function definition doesn't match use");
  }
  scanner_.ResetLocals();
  std::fill(local_var_info_.begin(), local_var_info_.end(), VarInfo{});
}
References v8::internal::wasm::WasmFunctionBuilder::AddAsmWasmOffset(), v8::internal::wasm::WasmModuleBuilder::AddFunction(), v8::internal::wasm::WasmFunctionBuilder::AddLocal(), cached_asm_type_p_vectors_, cached_valuetype_vectors_, Consume(), ConvertSignature(), CopyCurrentIdentifierString(), current_function_builder_, DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::wasm::WasmFunctionBuilder::Emit(), EXPECT_TOKEN, FAIL, failed_, v8::internal::wasm::WasmFunctionBuilder::func_index(), v8::internal::wasm::AsmType::Function(), v8::internal::wasm::AsmJsParser::VarInfo::function_builder, v8::internal::wasm::AsmJsParser::VarInfo::function_defined, function_temp_locals_depth_, function_temp_locals_offset_, function_temp_locals_used_, v8::internal::wasm::WasmFunctionBuilder::GetPosition(), GetVarInfo(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::AsmJsParser::VarInfo::index, v8::internal::wasm::AsmType::IsA(), v8::internal::AsmJsScanner::IsGlobal(), kFunction, v8::internal::wasm::AsmJsParser::VarInfo::kind, kUnused, v8::internal::wasm::kV8MaxWasmFunctionLocals, v8::internal::wasm::kV8MaxWasmFunctionParams, v8::internal::wasm::kV8MaxWasmFunctionSize, v8::internal::wasm::kWasmI32, local_var_info_, module_builder_, v8::internal::wasm::AsmJsParser::VarInfo::mutable_variable, v8::None, Peek(), v8::internal::AsmJsScanner::Position(), RECURSE, v8::internal::AsmJsScanner::ResetLocals(), return_type_, scanner_, v8::internal::wasm::WasmFunctionBuilder::SetAsmFunctionStartPosition(), v8::internal::wasm::WasmFunctionBuilder::SetName(), v8::internal::wasm::WasmFunctionBuilder::SetSignature(), v8::internal::sig, v8::internal::ZoneVector< T >::size(), TOK, v8::internal::wasm::AsmJsParser::VarInfo::type, ValidateFunctionLocals(), ValidateFunctionParams(), ValidateStatement(), and zone().
Referenced by ValidateModule().
ValidateFunctionLocals()
void v8::internal::wasm::AsmJsParser::ValidateFunctionLocals (size_t param_count, ZoneVector< ValueType > * locals) [private]
Definition at line 904 of file asm-parser.cc.
                                                                        {
  DCHECK(locals->empty());
  // Local Variables.
  while (Peek(TOK(var))) {
    scanner_.EnterLocalScope();
    EXPECT_TOKEN(TOK(var));
    scanner_.EnterGlobalScope();
    for (;;) {
      if (!scanner_.IsLocal()) {
        FAIL("Expected local variable identifier");
      }
      VarInfo* info = GetVarInfo(Consume());
      if (info->kind != VarKind::kUnused) {
        FAIL("Duplicate local variable name");
      }
      // Store types.
      EXPECT_TOKEN('=');
      double dvalue = 0.0;
      uint32_t uvalue = 0;
      if (Check('-')) {
        if (CheckForDouble(&dvalue)) {
          info->kind = VarKind::kLocal;
          info->type = AsmType::Double();
          info->index = static_cast<uint32_t>(param_count + locals->size());
          locals->push_back(kWasmF64);
          current_function_builder_->EmitF64Const(-dvalue);
          current_function_builder_->EmitSetLocal(info->index);
        } else if (CheckForUnsigned(&uvalue)) {
          if (uvalue > 0x7FFFFFFF) {
            FAIL("Numeric literal out of range");
          }
          info->kind = VarKind::kLocal;
          info->type = AsmType::Int();
          info->index = static_cast<uint32_t>(param_count + locals->size());
          locals->push_back(kWasmI32);
          int32_t value = -static_cast<int32_t>(uvalue);
          current_function_builder_->EmitI32Const(value);
          current_function_builder_->EmitSetLocal(info->index);
        } else {
          FAIL("Expected variable initial value");
        }
      } else if (scanner_.IsGlobal()) {
        VarInfo* sinfo = GetVarInfo(Consume());
        if (sinfo->kind == VarKind::kGlobal) {
          if (sinfo->mutable_variable) {
            FAIL("Initializing from global requires const variable");
          }
          info->kind = VarKind::kLocal;
          info->type = sinfo->type;
          info->index = static_cast<uint32_t>(param_count + locals->size());
          if (sinfo->type->IsA(AsmType::Int())) {
            locals->push_back(kWasmI32);
          } else if (sinfo->type->IsA(AsmType::Float())) {
            locals->push_back(kWasmF32);
          } else if (sinfo->type->IsA(AsmType::Double())) {
            locals->push_back(kWasmF64);
          } else {
            FAIL("Bad local variable definition");
          }
          current_function_builder_->EmitWithU32V(kExprGlobalGet,
                                                  VarIndex(sinfo));
          current_function_builder_->EmitSetLocal(info->index);
        } else if (sinfo->type->IsA(stdlib_fround_)) {
          EXPECT_TOKEN('(');
          bool negate = false;
          if (Check('-')) {
            negate = true;
          }
          if (CheckForDouble(&dvalue)) {
            info->kind = VarKind::kLocal;
            info->type = AsmType::Float();
            info->index = static_cast<uint32_t>(param_count + locals->size());
            locals->push_back(kWasmF32);
            if (negate) {
              dvalue = -dvalue;
            }
            float fvalue = DoubleToFloat32(dvalue);
            current_function_builder_->EmitF32Const(fvalue);
            current_function_builder_->EmitSetLocal(info->index);
          } else if (CheckForUnsigned(&uvalue)) {
            if (uvalue > 0x7FFFFFFF) {
              FAIL("Numeric literal out of range");
            }
            info->kind = VarKind::kLocal;
            info->type = AsmType::Float();
            info->index = static_cast<uint32_t>(param_count + locals->size());
            locals->push_back(kWasmF32);
            int32_t value = static_cast<int32_t>(uvalue);
            if (negate) {
              value = -value;
            }
            float fvalue = static_cast<float>(value);
            current_function_builder_->EmitF32Const(fvalue);
            current_function_builder_->EmitSetLocal(info->index);
          } else {
            FAIL("Expected variable initial value");
          }
          EXPECT_TOKEN(')');
        } else {
          FAIL("expected fround or const global");
        }
      } else if (CheckForDouble(&dvalue)) {
        info->kind = VarKind::kLocal;
        info->type = AsmType::Double();
        info->index = static_cast<uint32_t>(param_count + locals->size());
        locals->push_back(kWasmF64);
        current_function_builder_->EmitF64Const(dvalue);
        current_function_builder_->EmitSetLocal(info->index);
      } else if (CheckForUnsigned(&uvalue)) {
        info->kind = VarKind::kLocal;
        info->type = AsmType::Int();
        info->index = static_cast<uint32_t>(param_count + locals->size());
        locals->push_back(kWasmI32);
        int32_t value = static_cast<int32_t>(uvalue);
        current_function_builder_->EmitI32Const(value);
        current_function_builder_->EmitSetLocal(info->index);
      } else {
        FAIL("Expected variable initial value");
      }
      if (!Peek(',')) {
        break;
      }
      scanner_.EnterLocalScope();
      EXPECT_TOKEN(',');
      scanner_.EnterGlobalScope();
    }
    SkipSemicolon();
  }
}
References Check(), CheckForDouble(), CheckForUnsigned(), Consume(), current_function_builder_, v8::internal::DCHECK(), v8::internal::DoubleToFloat32(), v8::internal::wasm::WasmFunctionBuilder::EmitF32Const(), v8::internal::wasm::WasmFunctionBuilder::EmitF64Const(), v8::internal::wasm::WasmFunctionBuilder::EmitI32Const(), v8::internal::wasm::WasmFunctionBuilder::EmitSetLocal(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V(), v8::internal::ZoneVector< T >::empty(), v8::internal::AsmJsScanner::EnterGlobalScope(), v8::internal::AsmJsScanner::EnterLocalScope(), EXPECT_TOKEN, FAIL, GetVarInfo(), v8::internal::wasm::AsmJsParser::VarInfo::index, v8::internal::wasm::AsmType::IsA(), v8::internal::AsmJsScanner::IsGlobal(), v8::internal::AsmJsScanner::IsLocal(), kGlobal, v8::internal::wasm::AsmJsParser::VarInfo::kind, kLocal, kUnused, v8::internal::wasm::kWasmF32, v8::internal::wasm::kWasmF64, v8::internal::wasm::kWasmI32, v8::internal::wasm::AsmJsParser::VarInfo::mutable_variable, Peek(), v8::internal::ZoneVector< T >::push_back(), scanner_, v8::internal::ZoneVector< T >::size(), SkipSemicolon(), stdlib_fround_, TOK, v8::internal::wasm::AsmJsParser::VarInfo::type, v8::internal::value, and VarIndex().
Referenced by ValidateFunction().
ValidateFunctionParams()
void v8::internal::wasm::AsmJsParser::ValidateFunctionParams (ZoneVector< AsmType * > * params) [private]
Definition at line 843 of file asm-parser.cc.
                                                                     {
  // TODO(bradnelson): Do this differently so that the scanner doesn't need to
  // have a state transition that needs knowledge of how the scanner works
  // inside.
  scanner_.EnterLocalScope();
  EXPECT_TOKEN('(');
  CachedVector<AsmJsScanner::token_t> function_parameters(
      &cached_token_t_vectors_);
  while (!failed_ && !Peek(')')) {
    if (!scanner_.IsLocal()) {
      FAIL("Expected parameter name");
    }
    function_parameters.push_back(Consume());
    if (!Peek(')')) {
      EXPECT_TOKEN(',');
    }
  }
  EXPECT_TOKEN(')');
  scanner_.EnterGlobalScope();
  EXPECT_TOKEN('{');
  // 5.1 Parameter Type Annotations
  for (auto p : function_parameters) {
    EXPECT_TOKEN(p);
    EXPECT_TOKEN('=');
    VarInfo* info = GetVarInfo(p);
    if (info->kind != VarKind::kUnused) {
      FAIL("Duplicate parameter name");
    }
    if (Check(p)) {
      EXPECT_TOKEN('|');
      if (!CheckForZero()) {
        FAIL("Bad integer parameter annotation.");
      }
      info->kind = VarKind::kLocal;
      info->type = AsmType::Int();
      info->index = static_cast<uint32_t>(params->size());
      params->push_back(AsmType::Int());
    } else if (Check('+')) {
      EXPECT_TOKEN(p);
      info->kind = VarKind::kLocal;
      info->type = AsmType::Double();
      info->index = static_cast<uint32_t>(params->size());
      params->push_back(AsmType::Double());
    } else {
      if (!scanner_.IsGlobal() ||
          !GetVarInfo(Consume())->type->IsA(stdlib_fround_)) {
        FAIL("Expected fround");
      }
      EXPECT_TOKEN('(');
      EXPECT_TOKEN(p);
      EXPECT_TOKEN(')');
      info->kind = VarKind::kLocal;
      info->type = AsmType::Float();
      info->index = static_cast<uint32_t>(params->size());
      params->push_back(AsmType::Float());
    }
    SkipSemicolon();
  }
}
References cached_token_t_vectors_, Check(), CheckForZero(), Consume(), v8::internal::AsmJsScanner::EnterGlobalScope(), v8::internal::AsmJsScanner::EnterLocalScope(), EXPECT_TOKEN, FAIL, failed_, GetVarInfo(), v8::internal::wasm::AsmJsParser::VarInfo::index, v8::internal::wasm::AsmType::IsA(), v8::internal::AsmJsScanner::IsGlobal(), v8::internal::AsmJsScanner::IsLocal(), v8::internal::wasm::AsmJsParser::VarInfo::kind, kLocal, kUnused, Peek(), v8::internal::ZoneVector< T >::push_back(), scanner_, v8::internal::ZoneVector< T >::size(), SkipSemicolon(), stdlib_fround_, and v8::internal::wasm::AsmJsParser::VarInfo::type.
Referenced by ValidateFunction().
ValidateFunctionTable()
void v8::internal::wasm::AsmJsParser::ValidateFunctionTable () [private]
Definition at line 673 of file asm-parser.cc.
                                        {
  EXPECT_TOKEN(TOK(var));
  if (!scanner_.IsGlobal()) {
    FAIL("Expected table name");
  }
  VarInfo* table_info = GetVarInfo(Consume());
  if (table_info->kind == VarKind::kTable) {
    if (table_info->function_defined) {
      FAIL("Function table redefined");
    }
    table_info->function_defined = true;
  } else if (table_info->kind != VarKind::kUnused) {
    FAIL("Function table name collides");
  }
  EXPECT_TOKEN('=');
  EXPECT_TOKEN('[');
  uint64_t count = 0;
  for (;;) {
    if (!scanner_.IsGlobal()) {
      FAIL("Expected function name");
    }
    VarInfo* info = GetVarInfo(Consume());
    if (info->kind != VarKind::kFunction) {
      FAIL("Expected function");
    }
    // Only store the function into a table if we used the table somewhere
    // (i.e. tables are first seen at their use sites and allocated there).
    if (table_info->kind == VarKind::kTable) {
      if (count >= static_cast<uint64_t>(table_info->mask) + 1) {
        FAIL("Exceeded function table size");
      }
      if (!info->type->IsA(table_info->type)) {
        FAIL("Function table definition doesn't match use");
      }
      module_builder_->SetIndirectFunction(
          0, static_cast<uint32_t>(table_info->index + count), info->index,
          WasmModuleBuilder::WasmElemSegment::kRelativeToDeclaredFunctions);
    }
    ++count;
    if (Check(',')) {
      if (!Peek(']')) {
        continue;
      }
    }
    break;
  }
  EXPECT_TOKEN(']');
  if (table_info->kind == VarKind::kTable &&
      count != static_cast<uint64_t>(table_info->mask) + 1) {
    FAIL("Function table size does not match uses");
  }
  SkipSemicolon();
}
References Check(), Consume(), EXPECT_TOKEN, FAIL, v8::internal::wasm::AsmJsParser::VarInfo::function_defined, GetVarInfo(), v8::internal::wasm::AsmJsParser::VarInfo::index, v8::internal::wasm::AsmType::IsA(), v8::internal::AsmJsScanner::IsGlobal(), kFunction, v8::internal::wasm::AsmJsParser::VarInfo::kind, v8::internal::wasm::WasmModuleBuilder::WasmElemSegment::kRelativeToDeclaredFunctions, kTable, kUnused, v8::internal::wasm::AsmJsParser::VarInfo::mask, module_builder_, Peek(), scanner_, v8::internal::wasm::WasmModuleBuilder::SetIndirectFunction(), SkipSemicolon(), TOK, and v8::internal::wasm::AsmJsParser::VarInfo::type.
Referenced by ValidateModule().
ValidateHeapAccess()
void v8::internal::wasm::AsmJsParser::ValidateHeapAccess () [private]
Definition at line 2449 of file asm-parser.cc.
                                     {
  VarInfo* info = GetVarInfo(Consume());
  int32_t size = info->type->ElementSizeInBytes();
  EXPECT_TOKEN('[');
  uint32_t offset;
  if (CheckForUnsigned(&offset)) {
    // TODO(bradnelson): Check more things.
    // TODO(asmjs): Clarify and explain where this limit is coming from,
    // as it is not mandated by the spec directly.
    if (offset > 0x7FFFFFFF ||
        static_cast<uint64_t>(offset) * static_cast<uint64_t>(size) >
            0x7FFFFFFF) {
      FAIL("Heap access out of range");
    }
    if (Check(']')) {
      current_function_builder_->EmitI32Const(
          static_cast<uint32_t>(offset * size));
      // NOTE: This has to happen here to work recursively.
      heap_access_type_ = info->type;
      return;
    } else {
      scanner_.Rewind();
    }
  }
  AsmType* index_type;
  if (info->type->IsA(AsmType::Int8Array()) ||
      info->type->IsA(AsmType::Uint8Array())) {
    RECURSE(index_type = Expression(nullptr));
  } else {
    RECURSE(index_type = ShiftExpression());
    if (heap_access_shift_position_ == kNoHeapAccessShift) {
      FAIL("Expected shift of word size");
    }
    if (heap_access_shift_value_ > 3) {
      FAIL("Expected valid heap access shift");
    }
    if ((1 << heap_access_shift_value_) != size) {
      FAIL("Expected heap access shift to match heap view");
    }
    // Delete the code of the actual shift operation.
    current_function_builder_->DeleteCodeAfter(heap_access_shift_position_);
    // Mask bottom bits to match asm.js behavior.
    current_function_builder_->EmitI32Const(~(size - 1));
    current_function_builder_->Emit(kExprI32And);
  }
  if (!index_type->IsA(AsmType::Intish())) {
    FAIL("Expected intish index");
  }
  EXPECT_TOKEN(']');
  // NOTE: This has to happen here to work recursively.
  heap_access_type_ = info->type;
}
References Check(), CheckForUnsigned(), Consume(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::DeleteCodeAfter(), v8::internal::wasm::AsmType::ElementSizeInBytes(), v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitI32Const(), EXPECT_TOKEN, Expression(), FAIL, GetVarInfo(), heap_access_shift_position_, heap_access_shift_value_, heap_access_type_, v8::internal::wasm::AsmType::IsA(), kNoHeapAccessShift, RECURSE, v8::internal::AsmJsScanner::Rewind(), scanner_, ShiftExpression(), size(), and v8::internal::wasm::AsmJsParser::VarInfo::type.
Referenced by MemberExpression().
ValidateModule()
void v8::internal::wasm::AsmJsParser::ValidateModule () [private]
Definition at line 333 of file asm-parser.cc.
                                 {
  RECURSE(ValidateModuleParameters());
  EXPECT_TOKEN('{');
  EXPECT_TOKEN(TOK(UseAsm));
  RECURSE(SkipSemicolon());
  RECURSE(ValidateModuleVars());
  while (Peek(TOK(function))) {
    RECURSE(ValidateFunction());
  }
  while (Peek(TOK(var))) {
    RECURSE(ValidateFunctionTable());
  }
  RECURSE(ValidateExport());
  RECURSE(SkipSemicolon());
  EXPECT_TOKEN('}');
  // Check that all functions were eventually defined.
  for (auto& info : global_var_info_.SubVector(0, num_globals_)) {
    if (info.kind == VarKind::kFunction && !info.function_defined) {
      FAIL("Undefined function");
    }
    if (info.kind == VarKind::kTable && !info.function_defined) {
      FAIL("Undefined function table");
    }
    if (info.kind == VarKind::kImportedFunction && !info.function_defined) {
      // For imported functions without a single call site, we insert a dummy
      // import here to preserve the fact that there actually was an import.
      FunctionSig* void_void_sig = FunctionSig::Builder(zone(), 0, 0).Get();
      module_builder_->AddImport(info.import->function_name, void_void_sig);
    }
  }
  // Add start function to initialize things.
  WasmFunctionBuilder* start = module_builder_->AddFunction();
  module_builder_->MarkStartFunction(start);
  for (auto& global_import : global_imports_) {
    uint32_t import_index = module_builder_->AddGlobalImport(
        global_import.import_name, global_import.value_type,
        false /* mutability */);
    start->EmitWithU32V(kExprGlobalGet, import_index);
    start->EmitWithU32V(kExprGlobalSet, VarIndex(global_import.var_info));
  }
  start->Emit(kExprEnd);
  FunctionSig::Builder b(zone(), 0, 0);
  start->SetSignature(b.Get());
}
References v8::internal::wasm::WasmModuleBuilder::AddFunction(), v8::internal::wasm::WasmModuleBuilder::AddGlobalImport(), v8::internal::wasm::WasmModuleBuilder::AddImport(), v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V(), EXPECT_TOKEN, FAIL, v8::internal::SignatureBuilder< SigT, T >::Get(), global_imports_, global_var_info_, kFunction, kImportedFunction, kTable, v8::internal::wasm::WasmModuleBuilder::MarkStartFunction(), module_builder_, num_globals_, Peek(), RECURSE, v8::internal::wasm::WasmFunctionBuilder::SetSignature(), SkipSemicolon(), TOK, ValidateExport(), ValidateFunction(), ValidateFunctionTable(), ValidateModuleParameters(), ValidateModuleVars(), VarIndex(), and zone().
Referenced by Run().
ValidateModuleParameters()
void v8::internal::wasm::AsmJsParser::ValidateModuleParameters () [private]
Definition at line 381 of file asm-parser.cc.
                                           {
  EXPECT_TOKEN('(');
  stdlib_name_ = 0;
  foreign_name_ = 0;
  heap_name_ = 0;
  if (!Peek(')')) {
    if (!scanner_.IsGlobal()) {
      FAIL("Expected stdlib parameter");
    }
    stdlib_name_ = Consume();
    if (!Peek(')')) {
      EXPECT_TOKEN(',');
      if (!scanner_.IsGlobal()) {
        FAIL("Expected foreign parameter");
      }
      foreign_name_ = Consume();
      if (stdlib_name_ == foreign_name_) {
        FAIL("Duplicate parameter name");
      }
      if (!Peek(')')) {
        EXPECT_TOKEN(',');
        if (!scanner_.IsGlobal()) {
          FAIL("Expected heap parameter");
        }
        heap_name_ = Consume();
        if (heap_name_ == stdlib_name_ || heap_name_ == foreign_name_) {
          FAIL("Duplicate parameter name");
        }
      }
    }
  }
  EXPECT_TOKEN(')');
}
References Consume(), EXPECT_TOKEN, FAIL, foreign_name_, heap_name_, v8::internal::AsmJsScanner::IsGlobal(), Peek(), scanner_, and stdlib_name_.
Referenced by ValidateModule().
ValidateModuleVar()
void v8::internal::wasm::AsmJsParser::ValidateModuleVar (bool mutable_variable) [private]
Definition at line 437 of file asm-parser.cc.
                                                         {
  if (!scanner_.IsGlobal()) {
    FAIL("Expected identifier");
  }
  AsmJsScanner::token_t identifier = Consume();
  if (identifier == stdlib_name_ || identifier == foreign_name_ ||
      identifier == heap_name_) {
    FAIL("Cannot shadow parameters");
  }
  VarInfo* info = GetVarInfo(identifier);
  if (info->kind != VarKind::kUnused) {
    FAIL("Redefinition of variable");
  }
  EXPECT_TOKEN('=');
  double dvalue = 0.0;
  uint32_t uvalue = 0;
  if (CheckForDouble(&dvalue)) {
    DeclareGlobal(info, mutable_variable, AsmType::Double(), kWasmF64,
                  WasmInitExpr(dvalue));
  } else if (CheckForUnsigned(&uvalue)) {
    if (uvalue > 0x7FFFFFFF) {
      FAIL("Numeric literal out of range");
    }
    DeclareGlobal(info, mutable_variable,
                  mutable_variable ? AsmType::Int() : AsmType::Signed(),
                  kWasmI32, WasmInitExpr(static_cast<int32_t>(uvalue)));
  } else if (Check('-')) {
    if (CheckForDouble(&dvalue)) {
      DeclareGlobal(info, mutable_variable, AsmType::Double(), kWasmF64,
                    WasmInitExpr(-dvalue));
    } else if (CheckForUnsigned(&uvalue)) {
      if (uvalue > 0x7FFFFFFF) {
        FAIL("Numeric literal out of range");
      }
      if (uvalue == 0) {
        // '-0' is treated as float.
        DeclareGlobal(info, mutable_variable, AsmType::Float(), kWasmF32,
                      WasmInitExpr(-0.f));
      } else {
        DeclareGlobal(info, mutable_variable,
                      mutable_variable ? AsmType::Int() : AsmType::Signed(),
                      kWasmI32, WasmInitExpr(-static_cast<int32_t>(uvalue)));
      }
    } else {
      FAIL("Expected numeric literal");
    }
  } else if (Check(TOK(new))) {
    RECURSE(ValidateModuleVarNewStdlib(info));
  } else if (Check(stdlib_name_)) {
    EXPECT_TOKEN('.');
    RECURSE(ValidateModuleVarStdlib(info));
  } else if (Peek(foreign_name_) || Peek('+')) {
    RECURSE(ValidateModuleVarImport(info, mutable_variable));
  } else if (scanner_.IsGlobal()) {
    RECURSE(ValidateModuleVarFromGlobal(info, mutable_variable));
  } else {
    FAIL("Bad variable declaration");
  }
}
References Check(), CheckForDouble(), CheckForUnsigned(), Consume(), DeclareGlobal(), EXPECT_TOKEN, FAIL, foreign_name_, GetVarInfo(), heap_name_, v8::internal::AsmJsScanner::IsGlobal(), v8::internal::wasm::AsmJsParser::VarInfo::kind, kUnused, v8::internal::wasm::kWasmF32, v8::internal::wasm::kWasmF64, v8::internal::wasm::kWasmI32, Peek(), RECURSE, scanner_, v8::base::bits::Signed(), stdlib_name_, TOK, ValidateModuleVarFromGlobal(), ValidateModuleVarImport(), ValidateModuleVarNewStdlib(), and ValidateModuleVarStdlib().
Referenced by ValidateModuleVars().
ValidateModuleVarFromGlobal()
void v8::internal::wasm::AsmJsParser::ValidateModuleVarFromGlobal (VarInfo * info, bool mutable_variable) [private]
Definition at line 498 of file asm-parser.cc.
                                                                     {
  VarInfo* src_info = GetVarInfo(Consume());
  if (!src_info->type->IsA(stdlib_fround_)) {
    if (src_info->mutable_variable) {
      FAIL("Can only use immutable variables in global definition");
    }
    if (mutable_variable) {
      FAIL("Can only define immutable variables with other immutables");
    }
    if (!src_info->type->IsA(AsmType::Int()) &&
        !src_info->type->IsA(AsmType::Float()) &&
        !src_info->type->IsA(AsmType::Double())) {
      FAIL("Expected int, float, double, or fround for global definition");
    }
    info->kind = VarKind::kGlobal;
    info->type = src_info->type;
    info->index = src_info->index;
    info->mutable_variable = false;
    return;
  }
  EXPECT_TOKEN('(');
  bool negate = false;
  if (Check('-')) {
    negate = true;
  }
  double dvalue = 0.0;
  uint32_t uvalue = 0;
  if (CheckForDouble(&dvalue)) {
    if (negate) {
      dvalue = -dvalue;
    }
    DeclareGlobal(info, mutable_variable, AsmType::Float(), kWasmF32,
                  WasmInitExpr(DoubleToFloat32(dvalue)));
  } else if (CheckForUnsigned(&uvalue)) {
    dvalue = uvalue;
    if (negate) {
      dvalue = -dvalue;
    }
    DeclareGlobal(info, mutable_variable, AsmType::Float(), kWasmF32,
                  WasmInitExpr(static_cast<float>(dvalue)));
  } else {
    FAIL("Expected numeric literal");
  }
  EXPECT_TOKEN(')');
}
References Check(), CheckForDouble(), CheckForUnsigned(), Consume(), DeclareGlobal(), v8::internal::DoubleToFloat32(), EXPECT_TOKEN, FAIL, GetVarInfo(), v8::internal::wasm::AsmJsParser::VarInfo::index, v8::internal::wasm::AsmType::IsA(), kGlobal, v8::internal::wasm::AsmJsParser::VarInfo::kind, v8::internal::wasm::kWasmF32, v8::internal::wasm::AsmJsParser::VarInfo::mutable_variable, stdlib_fround_, and v8::internal::wasm::AsmJsParser::VarInfo::type.
Referenced by ValidateModuleVar().
ValidateModuleVarImport()
void v8::internal::wasm::AsmJsParser::ValidateModuleVarImport (VarInfo * info, bool mutable_variable) [private]
Definition at line 546 of file asm-parser.cc.
                                                                 {
  if (Check('+')) {
    EXPECT_TOKEN(foreign_name_);
    EXPECT_TOKEN('.');
    base::Vector<const char> name = CopyCurrentIdentifierString();
    AddGlobalImport(name, AsmType::Double(), kWasmF64, mutable_variable, info);
    scanner_.Next();
  } else {
    EXPECT_TOKEN(foreign_name_);
    EXPECT_TOKEN('.');
    base::Vector<const char> name = CopyCurrentIdentifierString();
    scanner_.Next();
    if (Check('|')) {
      if (!CheckForZero()) {
        FAIL("Expected |0 type annotation for foreign integer import");
      }
      AddGlobalImport(name, AsmType::Int(), kWasmI32, mutable_variable, info);
    } else {
      info->kind = VarKind::kImportedFunction;
      info->import = zone()->New<FunctionImportInfo>(name, zone());
      info->mutable_variable = false;
    }
  }
}
References AddGlobalImport(), Check(), CheckForZero(), CopyCurrentIdentifierString(), EXPECT_TOKEN, FAIL, foreign_name_, v8::internal::wasm::AsmJsParser::VarInfo::import, kImportedFunction, v8::internal::wasm::AsmJsParser::VarInfo::kind, v8::internal::wasm::kWasmF64, v8::internal::wasm::kWasmI32, v8::internal::wasm::AsmJsParser::VarInfo::mutable_variable, v8::internal::wasm::name(), v8::internal::Zone::New(), v8::internal::AsmJsScanner::Next(), scanner_, and zone().
Referenced by ValidateModuleVar().
ValidateModuleVarNewStdlib()
void v8::internal::wasm::AsmJsParser::ValidateModuleVarNewStdlib (VarInfo * info) [private]
Definition at line 574 of file asm-parser.cc.
                                                          {
  EXPECT_TOKEN(stdlib_name_);
  EXPECT_TOKEN('.');
  switch (Consume()) {
#define V(name, _junk1, _junk2, _junk3) \
  case TOK(name): \
    DeclareStdlibFunc(info, VarKind::kSpecial, AsmType::name()); \
    stdlib_uses_.Add(StandardMember::k##name); \
    break;
    STDLIB_ARRAY_TYPE_LIST(V)
#undef V
    default:
      FAIL("Expected ArrayBuffer view");
  }
  EXPECT_TOKEN('(');
  EXPECT_TOKEN(heap_name_);
  EXPECT_TOKEN(')');
}
References Consume(), EXPECT_TOKEN, FAIL, heap_name_, STDLIB_ARRAY_TYPE_LIST, and stdlib_name_.
Referenced by ValidateModuleVar().
ValidateModuleVars()
void v8::internal::wasm::AsmJsParser::ValidateModuleVars () [private]
Definition at line 416 of file asm-parser.cc.
                                     {
  while (Peek(TOK(var)) || Peek(TOK(const))) {
    bool mutable_variable = true;
    if (Check(TOK(var))) {
      // Had a var.
    } else {
      EXPECT_TOKEN(TOK(const));
      mutable_variable = false;
    }
    for (;;) {
      RECURSE(ValidateModuleVar(mutable_variable));
      if (Check(',')) {
        continue;
      }
      break;
    }
    SkipSemicolon();
  }
}
References Check(), EXPECT_TOKEN, Peek(), RECURSE, SkipSemicolon(), TOK, and ValidateModuleVar().
Referenced by ValidateModule().
ValidateModuleVarStdlib()
void v8::internal::wasm::AsmJsParser::ValidateModuleVarStdlib (VarInfo * info) [private]
Definition at line 595 of file asm-parser.cc.
                                                       {
  if (Check(TOK(Math))) {
    EXPECT_TOKEN('.');
    switch (Consume()) {
#define V(name, const_value) \
  case TOK(name): \
    DeclareGlobal(info, false, AsmType::Double(), kWasmF64, \
                  WasmInitExpr(const_value)); \
    stdlib_uses_.Add(StandardMember::kMath##name); \
    break;
      STDLIB_MATH_VALUE_LIST(V)
#undef V
#define V(name, Name, op, sig) \
  case TOK(name): \
    DeclareStdlibFunc(info, VarKind::kMath##Name, stdlib_##sig##_); \
    stdlib_uses_.Add(StandardMember::kMath##Name); \
    break;
      STDLIB_MATH_FUNCTION_LIST(V)
#undef V
      default:
        FAIL("Invalid member of stdlib.Math");
    }
  } else if (Check(TOK(Infinity))) {
    DeclareGlobal(info, false, AsmType::Double(), kWasmF64,
                  WasmInitExpr(std::numeric_limits<double>::infinity()));
    stdlib_uses_.Add(StandardMember::kInfinity);
  } else if (Check(TOK(NaN))) {
    DeclareGlobal(info, false, AsmType::Double(), kWasmF64,
                  WasmInitExpr(std::numeric_limits<double>::quiet_NaN()));
    stdlib_uses_.Add(StandardMember::kNaN);
  } else {
    FAIL("Invalid member of stdlib");
  }
}
References v8::base::EnumSet< E, T >::Add(), Check(), Consume(), DeclareGlobal(), EXPECT_TOKEN, FAIL, v8::internal::wasm::kWasmF64, STDLIB_MATH_FUNCTION_LIST, STDLIB_MATH_VALUE_LIST, stdlib_uses_, and TOK.
Referenced by ValidateModuleVar().
ValidateStatement()
void v8::internal::wasm::AsmJsParser::ValidateStatement () [private]
Definition at line 1036 of file asm-parser.cc.
                                    {
  call_coercion_ = nullptr;
  if (Peek('{')) {
    RECURSE(Block());
  } else if (Peek(';')) {
    RECURSE(EmptyStatement());
  } else if (Peek(TOK(if))) {
    RECURSE(IfStatement());
    // clang-format off
  } else if (Peek(TOK(return))) {
    // clang-format on
    RECURSE(ReturnStatement());
  } else if (IterationStatement()) {
    // Handled in IterationStatement.
  } else if (Peek(TOK(break))) {
    RECURSE(BreakStatement());
  } else if (Peek(TOK(continue))) {
    RECURSE(ContinueStatement());
  } else if (Peek(TOK(switch))) {
    RECURSE(SwitchStatement());
  } else {
    RECURSE(ExpressionStatement());
  }
}
References Block(), BreakStatement(), call_coercion_, ContinueStatement(), EmptyStatement(), ExpressionStatement(), IfStatement(), IterationStatement(), Peek(), RECURSE, ReturnStatement(), SwitchStatement(), and TOK.
Referenced by Block(), DoStatement(), ForStatement(), IfStatement(), LabelledStatement(), ValidateCase(), ValidateDefault(), ValidateFunction(), and WhileStatement().
VarIndex()
uint32_t v8::internal::wasm::AsmJsParser::VarIndex (VarInfo * info) [private]
Definition at line 218 of file asm-parser.cc.
                                            {
  DCHECK_EQ(info->kind, VarKind::kGlobal);
  return info->index + static_cast<uint32_t>(global_imports_.size());
}
References DCHECK_EQ, global_imports_, v8::internal::wasm::AsmJsParser::VarInfo::index, kGlobal, and v8::internal::wasm::AsmJsParser::VarInfo::kind.
Referenced by AssignmentExpression(), Identifier(), ValidateFunctionLocals(), and ValidateModule().
WhileStatement()
void v8::internal::wasm::AsmJsParser::WhileStatement () [private]
Definition at line 1161 of file asm-parser.cc.
                                 {
  // a: block {
  Begin(pending_label_);
  // b: loop {
  Loop(pending_label_);
  pending_label_ = 0;
  EXPECT_TOKEN(TOK(while));
  EXPECT_TOKEN('(');
  RECURSE(Expression(AsmType::Int()));
  EXPECT_TOKEN(')');
  // if (!CONDITION) break a;
  current_function_builder_->Emit(kExprI32Eqz);
  current_function_builder_->EmitWithU8(kExprBrIf, 1);
  // BODY
  RECURSE(ValidateStatement());
  // continue b;
  current_function_builder_->EmitWithU8(kExprBr, 0);
  End();
  // }
  // }
  End();
}
References Begin(), current_function_builder_, v8::internal::wasm::WasmFunctionBuilder::Emit(), v8::internal::wasm::WasmFunctionBuilder::EmitWithU8(), End(), EXPECT_TOKEN, Expression(), Loop(), pending_label_, RECURSE, TOK, and ValidateStatement().
Referenced by IterationStatement().
zone()
Zone* v8::internal::wasm::AsmJsParser::zone () [inline], [private]
Definition at line 247 of file asm-parser.h.
{ return zone_; }
References zone_.
Referenced by ConvertSignature(), CopyCurrentIdentifierString(), InitializeStdlibTypes(), ValidateCall(), ValidateFunction(), ValidateModule(), and ValidateModuleVarImport().
Member Data Documentation
block_stack_
ZoneVector<BlockInfo> v8::internal::wasm::AsmJsParser::block_stack_ [private]
Definition at line 202 of file asm-parser.h.
Referenced by BareBegin(), BareEnd(), FindBreakLabelDepth(), and FindContinueLabelDepth().
cached_asm_type_p_vectors_
CachedVectors<AsmType*> v8::internal::wasm::AsmJsParser::cached_asm_type_p_vectors_ {zone_} [private]
Definition at line 178 of file asm-parser.h.
Referenced by ValidateCall(), and ValidateFunction().
cached_int_vectors_
CachedVectors<int32_t> v8::internal::wasm::AsmJsParser::cached_int_vectors_ {zone_} [private]
Definition at line 180 of file asm-parser.h.
Referenced by SwitchStatement().
cached_token_t_vectors_
CachedVectors<AsmJsScanner::token_t> v8::internal::wasm::AsmJsParser::cached_token_t_vectors_ {zone_} [private]
Definition at line 179 of file asm-parser.h.
Referenced by ValidateFunctionParams().
cached_valuetype_vectors_
CachedVectors<ValueType> v8::internal::wasm::AsmJsParser::cached_valuetype_vectors_ {zone_} [private]
Definition at line 177 of file asm-parser.h.
Referenced by ValidateFunction().
call_coercion_
AsmType* v8::internal::wasm::AsmJsParser::call_coercion_ = nullptr [private]
Definition at line 217 of file asm-parser.h.
Referenced by Identifier(), MemberExpression(), NumericLiteral(), ParenthesizedExpression(), UnaryExpression(), ValidateCall(), ValidateFloatCoercion(), and ValidateStatement().
call_coercion_deferred_
AsmType* v8::internal::wasm::AsmJsParser::call_coercion_deferred_ = nullptr [private]
Definition at line 225 of file asm-parser.h.
Referenced by BitwiseORExpression(), and ValidateCall().
call_coercion_deferred_position_
size_t v8::internal::wasm::AsmJsParser::call_coercion_deferred_position_ [private]
Definition at line 229 of file asm-parser.h.
Referenced by BitwiseORExpression(), and ValidateCall().
call_coercion_position_
size_t v8::internal::wasm::AsmJsParser::call_coercion_position_ [private]
Definition at line 220 of file asm-parser.h.
Referenced by UnaryExpression(), ValidateCall(), and ValidateFloatCoercion().
current_function_builder_
WasmFunctionBuilder* v8::internal::wasm::AsmJsParser::current_function_builder_ [private]
Definition at line 169 of file asm-parser.h.
Referenced by AdditiveExpression(), AssignmentExpression(), Begin(), BitwiseANDExpression(), BitwiseORExpression(), BitwiseXORExpression(), Block(), BreakStatement(), ConditionalExpression(), ContinueStatement(), DoStatement(), End(), Expression(), ExpressionStatement(), ForStatement(), Identifier(), IfStatement(), Loop(), MultiplicativeExpression(), NumericLiteral(), ReturnStatement(), ShiftExpression(), SwitchStatement(), UnaryExpression(), ValidateCall(), ValidateFloatCoercion(), ValidateFunction(), ValidateFunctionLocals(), ValidateHeapAccess(), and WhileStatement().
failed_
bool v8::internal::wasm::AsmJsParser::failed_ = false [private]
Definition at line 187 of file asm-parser.h.
Referenced by Block(), Run(), SwitchStatement(), ValidateCall(), ValidateCase(), ValidateDefault(), ValidateFunction(), and ValidateFunctionParams().
failure_location_
int v8::internal::wasm::AsmJsParser::failure_location_ = kNoSourcePosition [private]
Definition at line 189 of file asm-parser.h.
Referenced by failure_location().
failure_message_
const char* v8::internal::wasm::AsmJsParser::failure_message_ [private]
Definition at line 188 of file asm-parser.h.
Referenced by failure_message().
foreign_name_
AsmJsScanner::token_t v8::internal::wasm::AsmJsParser::foreign_name_ = kTokenNone [private]
Definition at line 193 of file asm-parser.h.
Referenced by ValidateModuleParameters(), ValidateModuleVar(), and ValidateModuleVarImport().
function_temp_locals_depth_
int v8::internal::wasm::AsmJsParser::function_temp_locals_depth_ [private]
Definition at line 184 of file asm-parser.h.
Referenced by ValidateFunction().
function_temp_locals_offset_
int v8::internal::wasm::AsmJsParser::function_temp_locals_offset_ [private]
Definition at line 182 of file asm-parser.h.
Referenced by TempVariable(), and ValidateFunction().
function_temp_locals_used_
int v8::internal::wasm::AsmJsParser::function_temp_locals_used_ [private]
Definition at line 183 of file asm-parser.h.
Referenced by TempVariable(), and ValidateFunction().
global_imports_
ZoneLinkedList<GlobalImport> v8::internal::wasm::AsmJsParser::global_imports_ [private]
Definition at line 245 of file asm-parser.h.
Referenced by AddGlobalImport(), ValidateModule(), and VarIndex().
global_var_info_
base::Vector<VarInfo> v8::internal::wasm::AsmJsParser::global_var_info_ [private]
Definition at line 173 of file asm-parser.h.
Referenced by GetVarInfo(), and ValidateModule().
heap_access_shift_position_
size_t v8::internal::wasm::AsmJsParser::heap_access_shift_position_ [private]
Definition at line 235 of file asm-parser.h.
Referenced by ShiftExpression(), and ValidateHeapAccess().
heap_access_shift_value_
uint32_t v8::internal::wasm::AsmJsParser::heap_access_shift_value_ [private]
Definition at line 236 of file asm-parser.h.
Referenced by ShiftExpression(), and ValidateHeapAccess().
heap_access_type_
AsmType* v8::internal::wasm::AsmJsParser::heap_access_type_ = nullptr [private]
Definition at line 200 of file asm-parser.h.
Referenced by AssignmentExpression(), MemberExpression(), and ValidateHeapAccess().
heap_name_
AsmJsScanner::token_t v8::internal::wasm::AsmJsParser::heap_name_ = kTokenNone [private]
Definition at line 194 of file asm-parser.h.
Referenced by ValidateModuleParameters(), ValidateModuleVar(), and ValidateModuleVarNewStdlib().
inside_heap_assignment_
bool v8::internal::wasm::AsmJsParser::inside_heap_assignment_ = false [private]
Definition at line 199 of file asm-parser.h.
Referenced by AssignmentExpression(), and MemberExpression().
kNoHeapAccessShift
const size_t v8::internal::wasm::AsmJsParser::kNoHeapAccessShift = -1 [static], [private]
Definition at line 237 of file asm-parser.h.
Referenced by ShiftExpression(), and ValidateHeapAccess().
kTokenNone
const AsmJsScanner::token_t v8::internal::wasm::AsmJsParser::kTokenNone = 0 [static], [private]
Definition at line 196 of file asm-parser.h.
Referenced by BreakStatement(), ContinueStatement(), FindBreakLabelDepth(), and FindContinueLabelDepth().
local_var_info_
base::Vector<VarInfo> v8::internal::wasm::AsmJsParser::local_var_info_ [private]
Definition at line 174 of file asm-parser.h.
Referenced by GetVarInfo(), and ValidateFunction().
module_builder_
WasmModuleBuilder* v8::internal::wasm::AsmJsParser::module_builder_ [private]
Definition at line 168 of file asm-parser.h.
Referenced by AsmJsParser(), DeclareGlobal(), module_builder(), ValidateCall(), ValidateExport(), ValidateFunction(), ValidateFunctionTable(), and ValidateModule().
num_globals_
size_t v8::internal::wasm::AsmJsParser::num_globals_ = 0 [private]
Definition at line 175 of file asm-parser.h.
Referenced by GetVarInfo(), and ValidateModule().
pending_label_
AsmJsScanner::token_t v8::internal::wasm::AsmJsParser::pending_label_ = kTokenNone [private]
Definition at line 241 of file asm-parser.h.
Referenced by Block(), DoStatement(), ForStatement(), LabelledStatement(), SwitchStatement(), and WhileStatement().
return_type_
AsmType* v8::internal::wasm::AsmJsParser::return_type_ = nullptr [private]
Definition at line 170 of file asm-parser.h.
Referenced by ReturnStatement(), and ValidateFunction().
scanner_
AsmJsScanner v8::internal::wasm::AsmJsParser::scanner_ [private]
Definition at line 167 of file asm-parser.h.
Referenced by AssignmentExpression(), BitwiseORExpression(), BreakStatement(), CallExpression(), Check(), CheckForDouble(), CheckForUnsigned(), CheckForUnsignedBelow(), CheckForZero(), Consume(), ContinueStatement(), CopyCurrentIdentifierString(), EqualityExpression(), ExpressionStatement(), ForStatement(), GatherCases(), Identifier(), LabelledStatement(), Loop(), MultiplicativeExpression(), Peek(), PeekCall(), PeekForZero(), RelationalExpression(), ScanToClosingParenthesis(), ShiftExpression(), SkipSemicolon(), UnaryExpression(), ValidateCall(), ValidateExport(), ValidateFloatCoercion(), ValidateFunction(), ValidateFunctionLocals(), ValidateFunctionParams(), ValidateFunctionTable(), ValidateHeapAccess(), ValidateModuleParameters(), ValidateModuleVar(), and ValidateModuleVarImport().
stack_limit_
uintptr_t v8::internal::wasm::AsmJsParser::stack_limit_ [private]
Definition at line 171 of file asm-parser.h.
stdlib_abs_
AsmType* v8::internal::wasm::AsmJsParser::stdlib_abs_ [private]
Definition at line 210 of file asm-parser.h.
Referenced by InitializeStdlibTypes().
stdlib_ceil_like_
AsmType* v8::internal::wasm::AsmJsParser::stdlib_ceil_like_ [private]
Definition at line 211 of file asm-parser.h.
Referenced by InitializeStdlibTypes().
stdlib_dq2d_
AsmType* v8::internal::wasm::AsmJsParser::stdlib_dq2d_ [private]
Definition at line 205 of file asm-parser.h.
Referenced by InitializeStdlibTypes().
stdlib_dqdq2d_
AsmType* v8::internal::wasm::AsmJsParser::stdlib_dqdq2d_ [private]
Definition at line 206 of file asm-parser.h.
Referenced by InitializeStdlibTypes().
stdlib_fround_
AsmType* v8::internal::wasm::AsmJsParser::stdlib_fround_ [private]
Definition at line 212 of file asm-parser.h.
Referenced by CallExpression(), InitializeStdlibTypes(), ValidateFloatCoercion(), ValidateFunctionLocals(), ValidateFunctionParams(), and ValidateModuleVarFromGlobal().
stdlib_i2s_
AsmType* v8::internal::wasm::AsmJsParser::stdlib_i2s_ [private]
Definition at line 207 of file asm-parser.h.
Referenced by InitializeStdlibTypes().
stdlib_ii2s_
AsmType* v8::internal::wasm::AsmJsParser::stdlib_ii2s_ [private]
Definition at line 208 of file asm-parser.h.
Referenced by InitializeStdlibTypes().
stdlib_minmax_
AsmType* v8::internal::wasm::AsmJsParser::stdlib_minmax_ [private]
Definition at line 209 of file asm-parser.h.
Referenced by InitializeStdlibTypes().
stdlib_name_
AsmJsScanner::token_t v8::internal::wasm::AsmJsParser::stdlib_name_ = kTokenNone [private]
Definition at line 192 of file asm-parser.h.
Referenced by ValidateModuleParameters(), ValidateModuleVar(), and ValidateModuleVarNewStdlib().
stdlib_uses_
StdlibSet v8::internal::wasm::AsmJsParser::stdlib_uses_ [private]
Definition at line 172 of file asm-parser.h.
Referenced by stdlib_uses(), and ValidateModuleVarStdlib().
zone_
Zone* v8::internal::wasm::AsmJsParser::zone_ [private]
Definition at line 166 of file asm-parser.h.
Referenced by GetVarInfo(), InitializeStdlibTypes(), and zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/asmjs/asm-parser.h
/mnt/V8SourceCode/src/asmjs/asm-parser.cc