v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag > Class Template Reference
Public Types
using CaseVector = base::SmallVector< uint8_t, 8 >
using TargetMap = absl::btree_map< uint32_t, CaseVector >
Public Member Functions
bool LowerToBranches (Decoder *decoder, const BranchTableImmediate &imm)
uint32_t primary_target () const
uint32_t default_target () const
const TargetMap & other_targets () const
const CaseVector & primary_indices () const
Static Public Attributes
static constexpr int32_t kMaxComparesPerTarget = 2
static constexpr uint32_t kMaxTargets = 3
static constexpr int32_t kMaxTableCount = 20
Private Member Functions
bool TryAddTarget (uint32_t target, uint32_t index)
void AddDefault (uint32_t target)
Private Attributes
std::optional< uint32_t > default_target_
std::optional< uint32_t > primary_target_
CaseVector primary_indices_
TargetMap other_targets_
Detailed Description
template<typename ValidationTag>
class v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >
Definition at line 792 of file turboshaft-graph-interface.cc.
Member Typedef Documentation
CaseVector
template<typename ValidationTag >
using v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::CaseVector = base::SmallVector<uint8_t, 8>
Definition at line 797 of file turboshaft-graph-interface.cc.
TargetMap
template<typename ValidationTag >
using v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::TargetMap = absl::btree_map<uint32_t, CaseVector>
Definition at line 798 of file turboshaft-graph-interface.cc.
Member Function Documentation
AddDefault()
template<typename ValidationTag >
void v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::AddDefault (uint32_t target) [inline], [private]
Definition at line 848 of file turboshaft-graph-interface.cc.
                                     {
      default_target_ = target;
      if (!primary_target_.has_value()) {
        primary_target_ = default_target();
      }
    }
References v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::default_target(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::default_target_, and v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::primary_target_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::LowerToBranches().
default_target()
template<typename ValidationTag >
uint32_t v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::default_target () const [inline]
Definition at line 825 of file turboshaft-graph-interface.cc.
{ return default_target_.value(); }
References v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::default_target_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::AddDefault(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTable(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::LowerToBranches().
LowerToBranches()
template<typename ValidationTag >
bool v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::LowerToBranches (Decoder * decoder, const BranchTableImmediate & imm) [inline]
Definition at line 800 of file turboshaft-graph-interface.cc.
                                                                            {
      BranchTableIterator<ValidationTag> iterator(decoder, imm);
      while (iterator.has_next()) {
        uint32_t i = iterator.cur_index();
        uint32_t target = iterator.next();
        if (i == imm.table_count) {
          AddDefault(target);
        } else if (!TryAddTarget(target, i)) {
          return false;
        }
      }
      primary_indices_ = other_targets_[primary_target()];
      other_targets_.erase(primary_target());
      size_t total_targets = other_targets_.size() + 1;
      if (default_target() != primary_target() &&
          !other_targets_.count(default_target())) {
        total_targets++;
      }
      return total_targets <= kMaxTargets;
    }
References v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::AddDefault(), v8::internal::wasm::BranchTableIterator< ValidationTag >::cur_index(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::default_target(), v8::internal::wasm::BranchTableIterator< ValidationTag >::has_next(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::kMaxTargets, v8::internal::wasm::BranchTableIterator< ValidationTag >::next(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::other_targets_, v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::primary_indices_, v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::primary_target(), v8::internal::wasm::BranchTableImmediate::table_count, and v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::TryAddTarget().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTable().
other_targets()
template<typename ValidationTag >
const TargetMap& v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::other_targets () const [inline]
Definition at line 828 of file turboshaft-graph-interface.cc.
{ return other_targets_; }
References v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::other_targets_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTable().
primary_indices()
template<typename ValidationTag >
const CaseVector& v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::primary_indices () const [inline]
Definition at line 830 of file turboshaft-graph-interface.cc.
{ return primary_indices_; }
References v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::primary_indices_.
primary_target()
template<typename ValidationTag >
uint32_t v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::primary_target () const [inline]
Definition at line 823 of file turboshaft-graph-interface.cc.
{ return primary_target_.value(); }
References v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::primary_target_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTable(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::LowerToBranches(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::TryAddTarget().
TryAddTarget()
template<typename ValidationTag >
bool v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::TryAddTarget (uint32_t target, uint32_t index) [inline], [private]
Definition at line 833 of file turboshaft-graph-interface.cc.
                                                       {
      DCHECK_LT(index, kMaxTableCount);
      CaseVector& cases = other_targets_[target];
      if (other_targets_.size() > kMaxTargets) {
        return false;
      }
      if (cases.size() == kMaxComparesPerTarget) {
        if (primary_target_.has_value() && target != primary_target()) {
          return false;
        }
        primary_target_ = target;
      }
      cases.push_back(index);
      return true;
    }
References DCHECK_LT, v8::internal::index, v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::kMaxComparesPerTarget, v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::kMaxTableCount, v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::kMaxTargets, v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::other_targets_, v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::primary_target(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::primary_target_, v8::base::SmallVector< T, kSize, Allocator >::push_back(), and v8::base::SmallVector< T, kSize, Allocator >::size().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::LowerToBranches().
Member Data Documentation
default_target_
template<typename ValidationTag >
std::optional<uint32_t> v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::default_target_ [private]
Definition at line 855 of file turboshaft-graph-interface.cc.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::AddDefault(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::default_target().
kMaxComparesPerTarget
template<typename ValidationTag >
constexpr int32_t v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::kMaxComparesPerTarget = 2 [static], [constexpr]
Definition at line 794 of file turboshaft-graph-interface.cc.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::TryAddTarget().
kMaxTableCount
template<typename ValidationTag >
constexpr int32_t v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::kMaxTableCount = 20 [static], [constexpr]
Definition at line 796 of file turboshaft-graph-interface.cc.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::TryAddTarget().
kMaxTargets
template<typename ValidationTag >
constexpr uint32_t v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::kMaxTargets = 3 [static], [constexpr]
Definition at line 795 of file turboshaft-graph-interface.cc.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::LowerToBranches(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::TryAddTarget().
other_targets_
template<typename ValidationTag >
TargetMap v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::other_targets_ [private]
Definition at line 858 of file turboshaft-graph-interface.cc.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::LowerToBranches(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::other_targets(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::TryAddTarget().
primary_indices_
template<typename ValidationTag >
CaseVector v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::primary_indices_ [private]
Definition at line 857 of file turboshaft-graph-interface.cc.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::LowerToBranches(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::primary_indices().
primary_target_
template<typename ValidationTag >
std::optional<uint32_t> v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::primary_target_ [private]
Definition at line 856 of file turboshaft-graph-interface.cc.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::AddDefault(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::primary_target(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::BrTableAnalysis< ValidationTag >::TryAddTarget().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/turboshaft-graph-interface.cc