heap::base::BasicSlotSet< SlotGranularity > Class Template Reference
#include <basic-slot-set.h>
Classes
class Bucket
Public Types
enum AccessMode : uint8_t { ATOMIC
, NON_ATOMIC
 }
enum EmptyBucketMode { FREE_EMPTY_BUCKETS
, KEEP_EMPTY_BUCKETS
 }
using Address = uintptr_t
Public Member Functions
BasicSlotSet ()=delete
template<AccessMode access_mode>
void Insert (size_t slot_offset)
bool Contains (size_t slot_offset)
void Remove (size_t slot_offset)
void RemoveRange (size_t start_offset, size_t end_offset, size_t buckets, EmptyBucketMode mode)
bool Lookup (size_t slot_offset)
template<AccessMode access_mode = AccessMode::ATOMIC, typename Callback >
size_t Iterate (Address chunk_start, size_t start_bucket, size_t end_bucket, Callback callback, EmptyBucketMode mode)
size_t num_buckets () const
Static Public Member Functions
static BasicSlotSet * Allocate (size_t buckets)
static void Delete (BasicSlotSet *slot_set)
constexpr static size_t BucketsForSize (size_t size)
constexpr static size_t BucketForSlot (size_t slot_offset)
constexpr static size_t OffsetForBucket (size_t bucket_index)
Static Public Attributes
static constexpr int kCellsPerBucket = 32
static constexpr int kCellsPerBucketLog2 = 5
static constexpr int kCellSizeBytesLog2 = 2
static constexpr int kCellSizeBytes = 1 << kCellSizeBytesLog2
static constexpr int kBitsPerCell = 32
static constexpr int kBitsPerCellLog2 = 5
static constexpr int kBitsPerBucket = kCellsPerBucket * kBitsPerCell
static constexpr int kBitsPerBucketLog2
Protected Member Functions
template<AccessMode access_mode = AccessMode::ATOMIC, typename Callback , typename EmptyBucketCallback >
size_t Iterate (Address chunk_start, size_t start_bucket, size_t end_bucket, Callback callback, EmptyBucketCallback empty_bucket_callback)
bool FreeBucketIfEmpty (size_t bucket_index)
void ClearBucket (Bucket *bucket, int start_cell, int end_cell)
template<AccessMode access_mode = AccessMode::ATOMIC>
void ReleaseBucket (size_t bucket_index)
template<AccessMode access_mode = AccessMode::ATOMIC>
Bucket * LoadBucket (Bucket **bucket)
template<AccessMode access_mode = AccessMode::ATOMIC>
Bucket * LoadBucket (size_t bucket_index)
template<AccessMode access_mode = AccessMode::ATOMIC>
void StoreBucket (Bucket **bucket, Bucket *value)
template<AccessMode access_mode = AccessMode::ATOMIC>
void StoreBucket (size_t bucket_index, Bucket *value)
template<AccessMode access_mode = AccessMode::ATOMIC>
bool SwapInNewBucket (size_t bucket_index, Bucket *value)
void SlotToIndices (size_t slot_offset, size_t *bucket_index, int *cell_index, int *bit_index)
Bucket ** buckets ()
Bucket ** bucket (size_t bucket_index)
void set_num_buckets (size_t num_buckets)
Static Protected Attributes
static constexpr int kNumBucketsSize = sizeof(size_t)
Static Private Attributes
static constexpr auto kSystemPointerSize = sizeof(void*)
Friends
class v8::internal::WriteBarrierCodeStubAssembler
Detailed Description
template<size_t SlotGranularity>
class heap::base::BasicSlotSet< SlotGranularity >
Definition at line 31 of file basic-slot-set.h.
Member Typedef Documentation
Address
template<size_t SlotGranularity>
using heap::base::BasicSlotSet< SlotGranularity >::Address = uintptr_t
Definition at line 35 of file basic-slot-set.h.
Member Enumeration Documentation
AccessMode
template<size_t SlotGranularity>
enum heap::base::BasicSlotSet::AccessMode : uint8_t
Enumerator
ATOMIC
NON_ATOMIC
Definition at line 37 of file basic-slot-set.h.
                  : uint8_t {
    ATOMIC,
    NON_ATOMIC,
  };
EmptyBucketMode
template<size_t SlotGranularity>
enum heap::base::BasicSlotSet::EmptyBucketMode
Enumerator
FREE_EMPTY_BUCKETS
KEEP_EMPTY_BUCKETS
Definition at line 42 of file basic-slot-set.h.
                       {
    FREE_EMPTY_BUCKETS, // An empty bucket will be deallocated immediately.
    KEEP_EMPTY_BUCKETS // An empty bucket will be kept.
  };
Constructor & Destructor Documentation
BasicSlotSet()
template<size_t SlotGranularity>
heap::base::BasicSlotSet< SlotGranularity >::BasicSlotSet () [delete]
Member Function Documentation
Allocate()
template<size_t SlotGranularity>
static BasicSlotSet* heap::base::BasicSlotSet< SlotGranularity >::Allocate (size_t buckets) [inline], [static]
Definition at line 49 of file basic-slot-set.h.
                                                {
    // BasicSlotSet* slot_set --+
    // |
    // v
    // +-----------------+-------------------------+
    // | num buckets | buckets array |
    // +-----------------+-------------------------+
    // size_t Bucket* buckets
    //
    //
    // The BasicSlotSet pointer points to the beginning of the buckets array for
    // faster access in the write barrier. The number of buckets is maintained
    // for checking bounds for the heap sandbox.
    const size_t buckets_size = buckets * sizeof(Bucket*);
    const size_t size = kNumBucketsSize + buckets_size;
    void* allocation = v8::base::AlignedAlloc(size, kSystemPointerSize);
    CHECK(allocation);
    BasicSlotSet* slot_set = reinterpret_cast<BasicSlotSet*>(
        reinterpret_cast<uint8_t*>(allocation) + kNumBucketsSize);
    DCHECK(
        IsAligned(reinterpret_cast<uintptr_t>(slot_set), kSystemPointerSize));
    slot_set->set_num_buckets(buckets);
    for (size_t i = 0; i < buckets; i++) {
      *slot_set->bucket(i) = nullptr;
    }
    return slot_set;
  }
References v8::base::AlignedAlloc(), heap::base::BasicSlotSet< SlotGranularity >::bucket(), heap::base::BasicSlotSet< SlotGranularity >::buckets(), CHECK, DCHECK, IsAligned(), heap::base::BasicSlotSet< SlotGranularity >::kNumBucketsSize, heap::base::BasicSlotSet< SlotGranularity >::kSystemPointerSize, heap::base::BasicSlotSet< SlotGranularity >::set_num_buckets(), and size().
bucket()
template<size_t SlotGranularity>
Bucket** heap::base::BasicSlotSet< SlotGranularity >::bucket (size_t bucket_index) [inline], [protected]
Definition at line 465 of file basic-slot-set.h.
{ return buckets() + bucket_index; }
References heap::base::BasicSlotSet< SlotGranularity >::buckets().
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Allocate(), heap::base::BasicSlotSet< SlotGranularity >::ClearBucket(), heap::base::BasicSlotSet< SlotGranularity >::Contains(), heap::base::BasicSlotSet< SlotGranularity >::FreeBucketIfEmpty(), heap::base::BasicSlotSet< SlotGranularity >::Insert(), heap::base::BasicSlotSet< SlotGranularity >::Iterate(), heap::base::BasicSlotSet< SlotGranularity >::LoadBucket(), heap::base::BasicSlotSet< SlotGranularity >::Lookup(), heap::base::BasicSlotSet< SlotGranularity >::ReleaseBucket(), heap::base::BasicSlotSet< SlotGranularity >::Remove(), heap::base::BasicSlotSet< SlotGranularity >::RemoveRange(), heap::base::BasicSlotSet< SlotGranularity >::StoreBucket(), and heap::base::BasicSlotSet< SlotGranularity >::SwapInNewBucket().
BucketForSlot()
template<size_t SlotGranularity>
constexpr static size_t heap::base::BasicSlotSet< SlotGranularity >::BucketForSlot (size_t slot_offset) [inline], [static], [constexpr]
Definition at line 95 of file basic-slot-set.h.
                                                            {
    DCHECK(IsAligned(slot_offset, SlotGranularity));
    return slot_offset / (SlotGranularity * kBitsPerBucket);
  }
References DCHECK, IsAligned(), and heap::base::BasicSlotSet< SlotGranularity >::kBitsPerBucket.
buckets()
template<size_t SlotGranularity>
Bucket** heap::base::BasicSlotSet< SlotGranularity >::buckets () [inline], [protected]
Definition at line 464 of file basic-slot-set.h.
{ return reinterpret_cast<Bucket**>(this); }
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Allocate(), heap::base::BasicSlotSet< SlotGranularity >::bucket(), and heap::base::BasicSlotSet< SlotGranularity >::RemoveRange().
BucketsForSize()
template<size_t SlotGranularity>
constexpr static size_t heap::base::BasicSlotSet< SlotGranularity >::BucketsForSize (size_t size) [inline], [static], [constexpr]
Definition at line 89 of file basic-slot-set.h.
                                                      {
    return (size + (SlotGranularity * kBitsPerBucket) - 1) /
           (SlotGranularity * kBitsPerBucket);
  }
References heap::base::BasicSlotSet< SlotGranularity >::kBitsPerBucket, and size().
ClearBucket()
template<size_t SlotGranularity>
void heap::base::BasicSlotSet< SlotGranularity >::ClearBucket (Bucket * bucket, int start_cell, int end_cell) [inline], [protected]
Definition at line 395 of file basic-slot-set.h.
                                                                 {
    DCHECK_GE(start_cell, 0);
    DCHECK_LE(end_cell, kCellsPerBucket);
    int current_cell = start_cell;
    while (current_cell < kCellsPerBucket) {
      bucket->StoreCell(current_cell, 0);
      current_cell++;
    }
  }
References heap::base::BasicSlotSet< SlotGranularity >::bucket(), DCHECK_GE, DCHECK_LE, heap::base::BasicSlotSet< SlotGranularity >::kCellsPerBucket, and heap::base::BasicSlotSet< SlotGranularity >::Bucket::StoreCell().
Referenced by heap::base::BasicSlotSet< SlotGranularity >::RemoveRange().
Contains()
template<size_t SlotGranularity>
bool heap::base::BasicSlotSet< SlotGranularity >::Contains (size_t slot_offset) [inline]
Definition at line 133 of file basic-slot-set.h.
                                    {
    size_t bucket_index;
    int cell_index, bit_index;
    SlotToIndices(slot_offset, &bucket_index, &cell_index, &bit_index);
    Bucket* bucket = LoadBucket(bucket_index);
    if (bucket == nullptr) return false;
    return (bucket->LoadCell(cell_index) & (1u << bit_index)) != 0;
  }
References heap::base::BasicSlotSet< SlotGranularity >::bucket(), heap::base::BasicSlotSet< SlotGranularity >::LoadBucket(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::LoadCell(), and heap::base::BasicSlotSet< SlotGranularity >::SlotToIndices().
Referenced by v8::internal::RememberedSet< type >::Contains().
Delete()
template<size_t SlotGranularity>
static void heap::base::BasicSlotSet< SlotGranularity >::Delete (BasicSlotSet< SlotGranularity > * slot_set) [inline], [static]
Definition at line 77 of file basic-slot-set.h.
                                             {
    if (slot_set == nullptr) {
      return;
    }
    for (size_t i = 0; i < slot_set->num_buckets(); i++) {
      slot_set->ReleaseBucket(i);
    }
    v8::base::AlignedFree(reinterpret_cast<uint8_t*>(slot_set) -
                          kNumBucketsSize);
  }
References v8::base::AlignedFree(), heap::base::BasicSlotSet< SlotGranularity >::kNumBucketsSize, heap::base::BasicSlotSet< SlotGranularity >::num_buckets(), and heap::base::BasicSlotSet< SlotGranularity >::ReleaseBucket().
FreeBucketIfEmpty()
template<size_t SlotGranularity>
bool heap::base::BasicSlotSet< SlotGranularity >::FreeBucketIfEmpty (size_t bucket_index) [inline], [protected]
Definition at line 382 of file basic-slot-set.h.
                                              {
    Bucket* bucket = LoadBucket<AccessMode::NON_ATOMIC>(bucket_index);
    if (bucket != nullptr) {
      if (bucket->IsEmpty()) {
        ReleaseBucket<AccessMode::NON_ATOMIC>(bucket_index);
      } else {
        return false;
      }
    }
    return true;
  }
References heap::base::BasicSlotSet< SlotGranularity >::bucket(), and heap::base::BasicSlotSet< SlotGranularity >::Bucket::IsEmpty().
Insert()
template<size_t SlotGranularity>
template<AccessMode access_mode>
void heap::base::BasicSlotSet< SlotGranularity >::Insert (size_t slot_offset) [inline]
Definition at line 109 of file basic-slot-set.h.
                                  {
    size_t bucket_index;
    int cell_index, bit_index;
    SlotToIndices(slot_offset, &bucket_index, &cell_index, &bit_index);
    Bucket* bucket = LoadBucket<access_mode>(bucket_index);
    if (bucket == nullptr) {
      bucket = new Bucket;
      if (!SwapInNewBucket<access_mode>(bucket_index, bucket)) {
        delete bucket;
        bucket = LoadBucket<access_mode>(bucket_index);
      }
    }
    // Check that monotonicity is preserved, i.e., once a bucket is set we do
    // not free it concurrently.
    DCHECK(bucket != nullptr);
    DCHECK_EQ(bucket->cells(), LoadBucket<access_mode>(bucket_index)->cells());
    uint32_t mask = 1u << bit_index;
    if ((bucket->template LoadCell<access_mode>(cell_index) & mask) == 0) {
      bucket->template SetCellBits<access_mode>(cell_index, mask);
    }
  }
References heap::base::BasicSlotSet< SlotGranularity >::bucket(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::cells(), DCHECK, DCHECK_EQ, and heap::base::BasicSlotSet< SlotGranularity >::SlotToIndices().
Referenced by v8::internal::RememberedSetOperations::Insert().
Iterate() [1/2]
template<size_t SlotGranularity>
template<AccessMode access_mode = AccessMode::ATOMIC, typename Callback , typename EmptyBucketCallback >
size_t heap::base::BasicSlotSet< SlotGranularity >::Iterate (Address chunk_start, size_t start_bucket, size_t end_bucket, Callback callback, EmptyBucketCallback empty_bucket_callback) [inline], [protected]
Definition at line 342 of file basic-slot-set.h.
                                                                               {
    size_t new_count = 0;
    for (size_t bucket_index = start_bucket; bucket_index < end_bucket;
         bucket_index++) {
      Bucket* bucket = LoadBucket<access_mode>(bucket_index);
      if (bucket != nullptr) {
        size_t in_bucket_count = 0;
        size_t cell_offset = bucket_index << kBitsPerBucketLog2;
        for (int i = 0; i < kCellsPerBucket; i++, cell_offset += kBitsPerCell) {
          uint32_t cell = bucket->template LoadCell<access_mode>(i);
          if (cell) {
            uint32_t old_cell = cell;
            uint32_t mask = 0;
            while (cell) {
              int bit_offset = v8::base::bits::CountTrailingZeros(cell);
              uint32_t bit_mask = 1u << bit_offset;
              Address slot = (cell_offset + bit_offset) * SlotGranularity;
              if (callback(chunk_start + slot) == KEEP_SLOT) {
                ++in_bucket_count;
              } else {
                mask |= bit_mask;
              }
              cell ^= bit_mask;
            }
            uint32_t new_cell = old_cell & ~mask;
            if (old_cell != new_cell) {
              bucket->template ClearCellBits<access_mode>(i, mask);
            }
          }
        }
        if (in_bucket_count == 0) {
          empty_bucket_callback(bucket_index);
        }
        new_count += in_bucket_count;
      }
    }
    return new_count;
  }
References heap::base::BasicSlotSet< SlotGranularity >::bucket(), v8::base::bits::CountTrailingZeros(), heap::base::BasicSlotSet< SlotGranularity >::kBitsPerBucketLog2, heap::base::BasicSlotSet< SlotGranularity >::kBitsPerCell, heap::base::BasicSlotSet< SlotGranularity >::kCellsPerBucket, and heap::base::KEEP_SLOT.
Iterate() [2/2]
template<size_t SlotGranularity>
template<AccessMode access_mode = AccessMode::ATOMIC, typename Callback >
size_t heap::base::BasicSlotSet< SlotGranularity >::Iterate (Address chunk_start, size_t start_bucket, size_t end_bucket, Callback callback, EmptyBucketMode mode) [inline]
Definition at line 261 of file basic-slot-set.h.
                                                          {
    return Iterate<access_mode>(
        chunk_start, start_bucket, end_bucket, callback,
        [this, mode](size_t bucket_index) {
          if (mode == EmptyBucketMode::FREE_EMPTY_BUCKETS) {
            ReleaseBucket(bucket_index);
          }
        });
  }
References mode(), and heap::base::BasicSlotSet< SlotGranularity >::ReleaseBucket().
LoadBucket() [1/2]
template<size_t SlotGranularity>
template<AccessMode access_mode = AccessMode::ATOMIC>
Bucket* heap::base::BasicSlotSet< SlotGranularity >::LoadBucket (Bucket ** bucket) [inline], [protected]
Definition at line 413 of file basic-slot-set.h.
                                      {
    if (access_mode == AccessMode::ATOMIC)
      return v8::base::AsAtomicPointer::Acquire_Load(bucket);
    return *bucket;
  }
References v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load(), and heap::base::BasicSlotSet< SlotGranularity >::bucket().
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Contains(), heap::base::BasicSlotSet< SlotGranularity >::LoadBucket(), heap::base::BasicSlotSet< SlotGranularity >::Lookup(), v8::internal::SlotSet::Merge(), heap::base::BasicSlotSet< SlotGranularity >::Remove(), and heap::base::BasicSlotSet< SlotGranularity >::RemoveRange().
LoadBucket() [2/2]
template<size_t SlotGranularity>
template<AccessMode access_mode = AccessMode::ATOMIC>
Bucket* heap::base::BasicSlotSet< SlotGranularity >::LoadBucket (size_t bucket_index) [inline], [protected]
Definition at line 420 of file basic-slot-set.h.
                                          {
    return LoadBucket(bucket(bucket_index));
  }
References heap::base::BasicSlotSet< SlotGranularity >::bucket(), and heap::base::BasicSlotSet< SlotGranularity >::LoadBucket().
Lookup()
template<size_t SlotGranularity>
bool heap::base::BasicSlotSet< SlotGranularity >::Lookup (size_t slot_offset) [inline]
Definition at line 236 of file basic-slot-set.h.
                                  {
    size_t bucket_index;
    int cell_index, bit_index;
    SlotToIndices(slot_offset, &bucket_index, &cell_index, &bit_index);
    Bucket* bucket = LoadBucket(bucket_index);
    if (bucket == nullptr) return false;
    return (bucket->LoadCell(cell_index) & (1u << bit_index)) != 0;
  }
References heap::base::BasicSlotSet< SlotGranularity >::bucket(), heap::base::BasicSlotSet< SlotGranularity >::LoadBucket(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::LoadCell(), and heap::base::BasicSlotSet< SlotGranularity >::SlotToIndices().
num_buckets()
template<size_t SlotGranularity>
size_t heap::base::BasicSlotSet< SlotGranularity >::num_buckets () const [inline]
Definition at line 335 of file basic-slot-set.h.
                             {
    return *(reinterpret_cast<const size_t*>(this) - 1);
  }
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Delete(), heap::base::BasicSlotSet< SlotGranularity >::set_num_buckets(), and heap::base::BasicSlotSet< SlotGranularity >::SlotToIndices().
OffsetForBucket()
template<size_t SlotGranularity>
constexpr static size_t heap::base::BasicSlotSet< SlotGranularity >::OffsetForBucket (size_t bucket_index) [inline], [static], [constexpr]
Definition at line 101 of file basic-slot-set.h.
                                                               {
    return bucket_index * SlotGranularity * kBitsPerBucket;
  }
References heap::base::BasicSlotSet< SlotGranularity >::kBitsPerBucket.
ReleaseBucket()
template<size_t SlotGranularity>
template<AccessMode access_mode = AccessMode::ATOMIC>
void heap::base::BasicSlotSet< SlotGranularity >::ReleaseBucket (size_t bucket_index) [inline], [protected]
Definition at line 406 of file basic-slot-set.h.
                                          {
    Bucket* bucket = LoadBucket<access_mode>(bucket_index);
    StoreBucket<access_mode>(bucket_index, nullptr);
    delete bucket;
  }
References heap::base::BasicSlotSet< SlotGranularity >::bucket().
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Delete(), heap::base::BasicSlotSet< SlotGranularity >::Iterate(), and heap::base::BasicSlotSet< SlotGranularity >::RemoveRange().
Remove()
template<size_t SlotGranularity>
void heap::base::BasicSlotSet< SlotGranularity >::Remove (size_t slot_offset) [inline]
Definition at line 143 of file basic-slot-set.h.
                                  {
    size_t bucket_index;
    int cell_index, bit_index;
    SlotToIndices(slot_offset, &bucket_index, &cell_index, &bit_index);
    Bucket* bucket = LoadBucket(bucket_index);
    if (bucket != nullptr) {
      uint32_t cell = bucket->LoadCell(cell_index);
      uint32_t bit_mask = 1u << bit_index;
      if (cell & bit_mask) {
        bucket->ClearCellBits(cell_index, bit_mask);
      }
    }
  }
References heap::base::BasicSlotSet< SlotGranularity >::bucket(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::ClearCellBits(), heap::base::BasicSlotSet< SlotGranularity >::LoadBucket(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::LoadCell(), and heap::base::BasicSlotSet< SlotGranularity >::SlotToIndices().
Referenced by v8::internal::RememberedSetOperations::Remove().
RemoveRange()
template<size_t SlotGranularity>
void heap::base::BasicSlotSet< SlotGranularity >::RemoveRange (size_t start_offset, size_t end_offset, size_t buckets, EmptyBucketMode mode) [inline]
Definition at line 159 of file basic-slot-set.h.
                                         {
    CHECK_LE(end_offset, buckets * kBitsPerBucket * SlotGranularity);
    DCHECK_LE(start_offset, end_offset);
    size_t start_bucket;
    int start_cell, start_bit;
    SlotToIndices(start_offset, &start_bucket, &start_cell, &start_bit);
    size_t end_bucket;
    int end_cell, end_bit;
    // SlotToIndices() checks that bucket index is within `size`. Since the API
    // allow for an exclusive end interval, we compute the inclusive index and
    // then increment the bit again (with overflows).
    SlotToIndices(end_offset - SlotGranularity, &end_bucket, &end_cell,
                  &end_bit);
    if (++end_bit >= kBitsPerCell) {
      end_bit = 0;
      if (++end_cell >= kCellsPerBucket) {
        end_cell = 0;
        end_bucket++;
      }
    }
    uint32_t start_mask = (1u << start_bit) - 1;
    uint32_t end_mask = ~((1u << end_bit) - 1);
    Bucket* bucket;
    if (start_bucket == end_bucket && start_cell == end_cell) {
      bucket = LoadBucket(start_bucket);
      if (bucket != nullptr) {
        bucket->ClearCellBits(start_cell, ~(start_mask | end_mask));
      }
      return;
    }
    size_t current_bucket = start_bucket;
    int current_cell = start_cell;
    bucket = LoadBucket(current_bucket);
    if (bucket != nullptr) {
      bucket->ClearCellBits(current_cell, ~start_mask);
    }
    current_cell++;
    if (current_bucket < end_bucket) {
      if (bucket != nullptr) {
        ClearBucket(bucket, current_cell, kCellsPerBucket);
      }
      // The rest of the current bucket is cleared.
      // Move on to the next bucket.
      current_bucket++;
      current_cell = 0;
    }
    DCHECK(current_bucket == end_bucket ||
           (current_bucket < end_bucket && current_cell == 0));
    while (current_bucket < end_bucket) {
      if (mode == FREE_EMPTY_BUCKETS) {
        ReleaseBucket(current_bucket);
      } else {
        DCHECK(mode == KEEP_EMPTY_BUCKETS);
        bucket = LoadBucket(current_bucket);
        if (bucket != nullptr) {
          ClearBucket(bucket, 0, kCellsPerBucket);
        }
      }
      current_bucket++;
    }
    // All buckets between start_bucket and end_bucket are cleared.
    DCHECK(current_bucket == end_bucket);
    if (current_bucket == buckets) return;
    bucket = LoadBucket(current_bucket);
    DCHECK(current_cell <= end_cell);
    if (bucket == nullptr) return;
    while (current_cell < end_cell) {
      bucket->StoreCell(current_cell, 0);
      current_cell++;
    }
    // All cells between start_cell and end_cell are cleared.
    DCHECK(current_bucket == end_bucket && current_cell == end_cell);
    bucket->ClearCellBits(end_cell, ~end_mask);
  }
References heap::base::BasicSlotSet< SlotGranularity >::bucket(), heap::base::BasicSlotSet< SlotGranularity >::buckets(), CHECK_LE, heap::base::BasicSlotSet< SlotGranularity >::ClearBucket(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::ClearCellBits(), DCHECK, DCHECK_LE, heap::base::BasicSlotSet< SlotGranularity >::FREE_EMPTY_BUCKETS, heap::base::BasicSlotSet< SlotGranularity >::kBitsPerBucket, heap::base::BasicSlotSet< SlotGranularity >::kBitsPerCell, heap::base::BasicSlotSet< SlotGranularity >::kCellsPerBucket, heap::base::BasicSlotSet< SlotGranularity >::KEEP_EMPTY_BUCKETS, heap::base::BasicSlotSet< SlotGranularity >::LoadBucket(), mode(), heap::base::BasicSlotSet< SlotGranularity >::ReleaseBucket(), heap::base::BasicSlotSet< SlotGranularity >::SlotToIndices(), and heap::base::BasicSlotSet< SlotGranularity >::Bucket::StoreCell().
Referenced by v8::internal::RememberedSetOperations::RemoveRange().
set_num_buckets()
template<size_t SlotGranularity>
void heap::base::BasicSlotSet< SlotGranularity >::set_num_buckets (size_t num_buckets) [inline], [protected]
Definition at line 467 of file basic-slot-set.h.
                                           {
    *(reinterpret_cast<size_t*>(this) - 1) = num_buckets;
  }
References heap::base::BasicSlotSet< SlotGranularity >::num_buckets().
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Allocate().
SlotToIndices()
template<size_t SlotGranularity>
void heap::base::BasicSlotSet< SlotGranularity >::SlotToIndices (size_t slot_offset, size_t * bucket_index, int * cell_index, int * bit_index) [inline], [protected]
Definition at line 452 of file basic-slot-set.h.
                                     {
    DCHECK(IsAligned(slot_offset, SlotGranularity));
    size_t slot = slot_offset / SlotGranularity;
    *bucket_index = slot >> kBitsPerBucketLog2;
    // No SBXCHECK() in base.
    CHECK(*bucket_index < (num_buckets()));
    *cell_index =
        static_cast<int>((slot >> kBitsPerCellLog2) & (kCellsPerBucket - 1));
    *bit_index = static_cast<int>(slot & (kBitsPerCell - 1));
  }
References CHECK, DCHECK, IsAligned(), heap::base::BasicSlotSet< SlotGranularity >::kBitsPerBucketLog2, heap::base::BasicSlotSet< SlotGranularity >::kBitsPerCell, heap::base::BasicSlotSet< SlotGranularity >::kBitsPerCellLog2, heap::base::BasicSlotSet< SlotGranularity >::kCellsPerBucket, and heap::base::BasicSlotSet< SlotGranularity >::num_buckets().
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Contains(), heap::base::BasicSlotSet< SlotGranularity >::Insert(), heap::base::BasicSlotSet< SlotGranularity >::Lookup(), heap::base::BasicSlotSet< SlotGranularity >::Remove(), and heap::base::BasicSlotSet< SlotGranularity >::RemoveRange().
StoreBucket() [1/2]
template<size_t SlotGranularity>
template<AccessMode access_mode = AccessMode::ATOMIC>
void heap::base::BasicSlotSet< SlotGranularity >::StoreBucket (Bucket ** bucket, Bucket * value) [inline], [protected]
Definition at line 425 of file basic-slot-set.h.
                                                   {
    if (access_mode == AccessMode::ATOMIC) {
      v8::base::AsAtomicPointer::Release_Store(bucket, value);
    } else {
      *bucket = value;
    }
  }
References heap::base::BasicSlotSet< SlotGranularity >::bucket(), v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store(), and v8::internal::value.
Referenced by v8::internal::SlotSet::Merge(), and heap::base::BasicSlotSet< SlotGranularity >::StoreBucket().
StoreBucket() [2/2]
template<size_t SlotGranularity>
template<AccessMode access_mode = AccessMode::ATOMIC>
void heap::base::BasicSlotSet< SlotGranularity >::StoreBucket (size_t bucket_index, Bucket * value) [inline], [protected]
Definition at line 434 of file basic-slot-set.h.
                                                       {
    StoreBucket(bucket(bucket_index), value);
  }
References heap::base::BasicSlotSet< SlotGranularity >::bucket(), heap::base::BasicSlotSet< SlotGranularity >::StoreBucket(), and v8::internal::value.
SwapInNewBucket()
template<size_t SlotGranularity>
template<AccessMode access_mode = AccessMode::ATOMIC>
bool heap::base::BasicSlotSet< SlotGranularity >::SwapInNewBucket (size_t bucket_index, Bucket * value) [inline], [protected]
Definition at line 439 of file basic-slot-set.h.
                                                           {
    Bucket** b = bucket(bucket_index);
    if (access_mode == AccessMode::ATOMIC) {
      return v8::base::AsAtomicPointer::Release_CompareAndSwap(
                 b, nullptr, value) == nullptr;
    } else {
      DCHECK_NULL(*b);
      *b = value;
      return true;
    }
  }
References heap::base::BasicSlotSet< SlotGranularity >::bucket(), DCHECK_NULL, v8::base::AsAtomicImpl< TAtomicStorageType >::Release_CompareAndSwap(), and v8::internal::value.
Friends And Related Function Documentation
v8::internal::WriteBarrierCodeStubAssembler
template<size_t SlotGranularity>
friend class v8::internal::WriteBarrierCodeStubAssembler [friend]
Definition at line 474 of file basic-slot-set.h.
Member Data Documentation
kBitsPerBucket
template<size_t SlotGranularity>
constexpr int heap::base::BasicSlotSet< SlotGranularity >::kBitsPerBucket = kCellsPerBucket * kBitsPerCell [static], [constexpr]
Definition at line 278 of file basic-slot-set.h.
Referenced by heap::base::BasicSlotSet< SlotGranularity >::BucketForSlot(), heap::base::BasicSlotSet< SlotGranularity >::BucketsForSize(), heap::base::BasicSlotSet< SlotGranularity >::OffsetForBucket(), and heap::base::BasicSlotSet< SlotGranularity >::RemoveRange().
kBitsPerBucketLog2
template<size_t SlotGranularity>
constexpr int heap::base::BasicSlotSet< SlotGranularity >::kBitsPerBucketLog2 [static], [constexpr]
Initial value:
=
      kCellsPerBucketLog2 + kBitsPerCellLog2
Definition at line 279 of file basic-slot-set.h.
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Iterate(), and heap::base::BasicSlotSet< SlotGranularity >::SlotToIndices().
kBitsPerCell
template<size_t SlotGranularity>
constexpr int heap::base::BasicSlotSet< SlotGranularity >::kBitsPerCell = 32 [static], [constexpr]
Definition at line 276 of file basic-slot-set.h.
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Iterate(), heap::base::BasicSlotSet< SlotGranularity >::RemoveRange(), and heap::base::BasicSlotSet< SlotGranularity >::SlotToIndices().
kBitsPerCellLog2
template<size_t SlotGranularity>
constexpr int heap::base::BasicSlotSet< SlotGranularity >::kBitsPerCellLog2 = 5 [static], [constexpr]
Definition at line 277 of file basic-slot-set.h.
Referenced by heap::base::BasicSlotSet< SlotGranularity >::SlotToIndices().
kCellSizeBytes
template<size_t SlotGranularity>
constexpr int heap::base::BasicSlotSet< SlotGranularity >::kCellSizeBytes = 1 << kCellSizeBytesLog2 [static], [constexpr]
Definition at line 275 of file basic-slot-set.h.
kCellSizeBytesLog2
template<size_t SlotGranularity>
constexpr int heap::base::BasicSlotSet< SlotGranularity >::kCellSizeBytesLog2 = 2 [static], [constexpr]
Definition at line 274 of file basic-slot-set.h.
kCellsPerBucket
template<size_t SlotGranularity>
constexpr int heap::base::BasicSlotSet< SlotGranularity >::kCellsPerBucket = 32 [static], [constexpr]
Definition at line 272 of file basic-slot-set.h.
Referenced by heap::base::BasicSlotSet< SlotGranularity >::ClearBucket(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::IsEmpty(), heap::base::BasicSlotSet< SlotGranularity >::Iterate(), heap::base::BasicSlotSet< SlotGranularity >::Bucket::LoadCell(), heap::base::BasicSlotSet< SlotGranularity >::RemoveRange(), and heap::base::BasicSlotSet< SlotGranularity >::SlotToIndices().
kCellsPerBucketLog2
template<size_t SlotGranularity>
constexpr int heap::base::BasicSlotSet< SlotGranularity >::kCellsPerBucketLog2 = 5 [static], [constexpr]
Definition at line 273 of file basic-slot-set.h.
kNumBucketsSize
template<size_t SlotGranularity>
constexpr int heap::base::BasicSlotSet< SlotGranularity >::kNumBucketsSize = sizeof(size_t) [static], [constexpr], [protected]
Definition at line 471 of file basic-slot-set.h.
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Allocate(), and heap::base::BasicSlotSet< SlotGranularity >::Delete().
kSystemPointerSize
template<size_t SlotGranularity>
constexpr auto heap::base::BasicSlotSet< SlotGranularity >::kSystemPointerSize = sizeof(void*) [static], [constexpr], [private]
Definition at line 32 of file basic-slot-set.h.
Referenced by heap::base::BasicSlotSet< SlotGranularity >::Allocate().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/base/basic-slot-set.h