v8::internal::CodeStatistics Class Reference
#include <code-stats.h>
Static Public Member Functions
static void CollectCodeStatistics (PagedSpace *space, Isolate *isolate)
static void CollectCodeStatistics (OldLargeObjectSpace *space, Isolate *isolate)
static void ResetCodeAndMetadataStatistics (Isolate *isolate)
Static Private Member Functions
static void RecordCodeAndMetadataStatistics (Tagged< HeapObject > object, Isolate *isolate)
Detailed Description
Definition at line 20 of file code-stats.h.
Member Function Documentation
CollectCodeStatistics() [1/2]
void v8::internal::CodeStatistics::CollectCodeStatistics (OldLargeObjectSpace * space, Isolate * isolate) [static]
Definition at line 75 of file code-stats.cc.
                                                             {
  LargeObjectSpaceObjectIterator obj_it(space);
  for (Tagged<HeapObject> obj = obj_it.Next(); !obj.is_null();
       obj = obj_it.Next()) {
    RecordCodeAndMetadataStatistics(obj, isolate);
  }
}
References v8::internal::Tagged< HeapObject >::is_null(), v8::internal::LargeObjectSpaceObjectIterator::Next(), RecordCodeAndMetadataStatistics(), and space.
CollectCodeStatistics() [2/2]
void v8::internal::CodeStatistics::CollectCodeStatistics (PagedSpace * space, Isolate * isolate) [static]
Definition at line 63 of file code-stats.cc.
                                                             {
  PagedSpaceObjectIterator obj_it(isolate->heap(), space);
  for (Tagged<HeapObject> obj = obj_it.Next(); !obj.is_null();
       obj = obj_it.Next()) {
    RecordCodeAndMetadataStatistics(obj, isolate);
  }
}
References v8::internal::Isolate::heap(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::PagedSpaceObjectIterator::Next(), RecordCodeAndMetadataStatistics(), and space.
Referenced by v8::internal::Heap::CollectCodeStatistics().
RecordCodeAndMetadataStatistics()
void v8::internal::CodeStatistics::RecordCodeAndMetadataStatistics (Tagged< HeapObject > object, Isolate * isolate) [static], [private]
Definition at line 17 of file code-stats.cc.
                                                                       {
  PtrComprCageBase cage_base(isolate);
  if (IsScript(object, cage_base)) {
    Tagged<Script> script = Cast<Script>(object);
    // Log the size of external source code.
    Tagged<Object> source = script->source(cage_base);
    if (IsExternalString(source, cage_base)) {
      Tagged<ExternalString> external_source_string =
          Cast<ExternalString>(source);
      int size = isolate->external_script_source_size();
      size += external_source_string->ExternalPayloadSize();
      isolate->set_external_script_source_size(size);
    }
  } else if (IsAbstractCode(object, cage_base)) {
    // Record code+metadata statistics.
    Tagged<AbstractCode> abstract_code = Cast<AbstractCode>(object);
    int size = abstract_code->SizeIncludingMetadata(cage_base);
    if (IsCode(abstract_code, cage_base)) {
      size += isolate->code_and_metadata_size();
      isolate->set_code_and_metadata_size(size);
    } else {
      size += isolate->bytecode_and_metadata_size();
      isolate->set_bytecode_and_metadata_size(size);
    }
#ifdef DEBUG
    CodeKind code_kind = abstract_code->kind(cage_base);
    isolate->code_kind_statistics()[static_cast<int>(code_kind)] +=
        abstract_code->Size(cage_base);
#endif
  }
}
References v8::internal::InstanceTypeChecker::IsAbstractCode(), v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::script, and size().
Referenced by CollectCodeStatistics().
ResetCodeAndMetadataStatistics()
void v8::internal::CodeStatistics::ResetCodeAndMetadataStatistics (Isolate * isolate) [static]
Definition at line 51 of file code-stats.cc.
                                                                    {
  isolate->set_code_and_metadata_size(0);
  isolate->set_bytecode_and_metadata_size(0);
  isolate->set_external_script_source_size(0);
#ifdef DEBUG
  ResetCodeStatistics(isolate);
#endif
}
Referenced by v8::internal::Heap::CollectCodeStatistics().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/code-stats.h
/mnt/V8SourceCode/src/heap/code-stats.cc