v8::internal::compiler::turboshaft::GrowingOpIndexSidetable< T > Class Template Reference
#include <sidetable.h>
Public Member Functions
GrowingOpIndexSidetable (Zone *zone, const Graph *graph)
GrowingOpIndexSidetable (size_t size, const T &initial_value, Zone *zone, const Graph *graph)
T & operator[] (OpIndex index)
const T & operator[] (OpIndex index) const
void SwapData (GrowingOpIndexSidetable< T > &other)
Private Types
using Base = detail::GrowingSidetable< T, OpIndex >
Additional Inherited Members
Detailed Description
template<class T>
class v8::internal::compiler::turboshaft::GrowingOpIndexSidetable< T >
Definition at line 132 of file sidetable.h.
Member Typedef Documentation
Base
template<class T >
using v8::internal::compiler::turboshaft::GrowingOpIndexSidetable< T >::Base = detail::GrowingSidetable<T, OpIndex> [private]
Definition at line 133 of file sidetable.h.
Constructor & Destructor Documentation
GrowingOpIndexSidetable() [1/2]
template<class T >
v8::internal::compiler::turboshaft::GrowingOpIndexSidetable< T >::GrowingOpIndexSidetable (Zone * zone, const Graph * graph) [inline], [explicit]
Definition at line 136 of file sidetable.h.
      : Base(zone)
#ifdef DEBUG
        ,
        graph_(graph)
#endif
  {
    USE(graph);
  }
References graph(), and USE.
GrowingOpIndexSidetable() [2/2]
template<class T >
v8::internal::compiler::turboshaft::GrowingOpIndexSidetable< T >::GrowingOpIndexSidetable (size_t size, const T & initial_value, Zone * zone, const Graph * graph) [inline]
Definition at line 146 of file sidetable.h.
      : Base(size, initial_value, zone)
#ifdef DEBUG
        ,
        graph_(graph)
#endif
  {
    USE(graph);
  }
References graph(), and USE.
Member Function Documentation
operator[]() [1/2]
template<class T >
T& v8::internal::compiler::turboshaft::GrowingOpIndexSidetable< T >::operator[] (OpIndex index) [inline]
Definition at line 157 of file sidetable.h.
                               {
    DCHECK(OpIndexBelongsToTableGraph(graph_, index));
    return Base::operator[](index);
  }
References v8::internal::DCHECK(), v8::internal::index, and v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, OpIndex >::operator[]().
operator[]() [2/2]
template<class T >
const T& v8::internal::compiler::turboshaft::GrowingOpIndexSidetable< T >::operator[] (OpIndex index) const [inline]
Definition at line 162 of file sidetable.h.
                                           {
    DCHECK(OpIndexBelongsToTableGraph(graph_, index));
    return Base::operator[](index);
  }
References v8::internal::DCHECK(), v8::internal::index, and v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, OpIndex >::operator[]().
SwapData()
template<class T >
void v8::internal::compiler::turboshaft::GrowingOpIndexSidetable< T >::SwapData (GrowingOpIndexSidetable< T > & other) [inline]
Definition at line 167 of file sidetable.h.
                                                   {
    std::swap(Base::table_, other.table_);
  }
References v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, Key >::table_, and v8::internal::compiler::turboshaft::detail::GrowingSidetable< T, OpIndex >::table_.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/sidetable.h