v8::internal::compiler::UnparkedScopeIfNeeded Class Reference
#include <js-heap-broker.h>
Public Member Functions
UnparkedScopeIfNeeded (JSHeapBroker *broker, bool extra_condition=true)
Private Attributes
std::optional< UnparkedScope > unparked_scope
Detailed Description
Definition at line 552 of file js-heap-broker.h.
Constructor & Destructor Documentation
UnparkedScopeIfNeeded()
v8::internal::compiler::UnparkedScopeIfNeeded::UnparkedScopeIfNeeded (JSHeapBroker * broker, bool extra_condition = true) [inline], [explicit]
Definition at line 554 of file js-heap-broker.h.
                                                              {
    if (broker != nullptr && extra_condition) {
      LocalIsolate* local_isolate = broker->local_isolate();
      if (local_isolate != nullptr && local_isolate->heap()->IsParked()) {
        unparked_scope.emplace(local_isolate->heap());
      }
    }
  }
References broker(), v8::internal::LocalIsolate::heap(), and v8::internal::LocalHeap::IsParked().
Member Data Documentation
unparked_scope
std::optional<UnparkedScope> v8::internal::compiler::UnparkedScopeIfNeeded::unparked_scope [private]
Definition at line 565 of file js-heap-broker.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-heap-broker.h