v8::internal::DynamicBitSet Class Reference
Public Member Functions
V8_EXPORT_PRIVATE bool Get (unsigned value) const
void Set (unsigned value, Zone *zone)
Private Attributes
uint32_t first_ = 0
ZoneList< unsigned > * remaining_ = nullptr
Static Private Attributes
static constexpr unsigned kFirstLimit = 32
Detailed Description
Definition at line 322 of file regexp-compiler.cc.
Member Function Documentation
Get()
V8_EXPORT_PRIVATE bool v8::internal::DynamicBitSet::Get (unsigned value) const [inline]
Definition at line 324 of file regexp-compiler.cc.
                                                   {
    if (value < kFirstLimit) {
      return (first_ & (1 << value)) != 0;
    } else if (remaining_ == nullptr) {
      return false;
    } else {
      return remaining_->Contains(value);
    }
  }
References v8::internal::ZoneList< T >::Contains(), first_, kFirstLimit, remaining_, and v8::internal::value.
Referenced by v8::internal::Trace::PerformDeferredActions(), and v8::internal::Trace::RestoreAffectedRegisters().
Set()
void v8::internal::DynamicBitSet::Set (unsigned value, Zone * zone) [inline]
Definition at line 335 of file regexp-compiler.cc.
                                       {
    if (value < kFirstLimit) {
      first_ |= (1 << value);
    } else {
      if (remaining_ == nullptr)
        remaining_ = zone->New<ZoneList<unsigned>>(1, zone);
      if (remaining_->is_empty() || !remaining_->Contains(value))
        remaining_->Add(value, zone);
    }
  }
References v8::internal::ZoneList< T >::Add(), v8::internal::ZoneList< T >::Contains(), first_, v8::internal::ZoneList< T >::is_empty(), kFirstLimit, v8::internal::Zone::New(), remaining_, and v8::internal::value.
Referenced by v8::internal::Trace::FindAffectedRegisters(), and v8::internal::Trace::PerformDeferredActions().
Member Data Documentation
first_
uint32_t v8::internal::DynamicBitSet::first_ = 0 [private]
Definition at line 349 of file regexp-compiler.cc.
Referenced by Get(), and Set().
kFirstLimit
constexpr unsigned v8::internal::DynamicBitSet::kFirstLimit = 32 [static], [constexpr], [private]
Definition at line 347 of file regexp-compiler.cc.
Referenced by Get(), and Set().
remaining_
ZoneList<unsigned>* v8::internal::DynamicBitSet::remaining_ = nullptr [private]
Definition at line 350 of file regexp-compiler.cc.
Referenced by Get(), and Set().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc