v8::internal::OrderedNameDictionaryHandler Class Reference
#include <ordered-hash-table.h>
Static Public Member Functions
static MaybeHandle< HeapObject > Add (Isolate *isolate, Handle< HeapObject > table, DirectHandle< Name > key, DirectHandle< Object > value, PropertyDetails details)
static DirectHandle< HeapObject > Shrink (Isolate *isolate, Handle< HeapObject > table)
static DirectHandle< HeapObject > DeleteEntry (Isolate *isolate, Handle< HeapObject > table, InternalIndex entry)
static InternalIndex FindEntry (Isolate *isolate, Tagged< HeapObject > table, Tagged< Name > key)
static void SetEntry (Tagged< HeapObject > table, InternalIndex entry, Tagged< Object > key, Tagged< Object > value, PropertyDetails details)
static Tagged< Object > ValueAt (Tagged< HeapObject > table, InternalIndex entry)
static void ValueAtPut (Tagged< HeapObject > table, InternalIndex entry, Tagged< Object > value)
static PropertyDetails DetailsAt (Tagged< HeapObject > table, InternalIndex entry)
static void DetailsAtPut (Tagged< HeapObject > table, InternalIndex entry, PropertyDetails value)
static Tagged< Name > KeyAt (Tagged< HeapObject > table, InternalIndex entry)
static void SetHash (Tagged< HeapObject > table, int hash)
static int Hash (Tagged< HeapObject > table)
static int NumberOfElements (Tagged< HeapObject > table)
static int Capacity (Tagged< HeapObject > table)
Static Protected Member Functions
static MaybeHandle< OrderedNameDictionary > AdjustRepresentation (Isolate *isolate, DirectHandle< SmallOrderedNameDictionary > table)
Detailed Description
Definition at line 857 of file ordered-hash-table.h.
Member Function Documentation
Add()
MaybeHandle< HeapObject > v8::internal::OrderedNameDictionaryHandler::Add (Isolate * isolate, Handle< HeapObject > table, DirectHandle< Name > key, DirectHandle< Object > value, PropertyDetails details) [static]
Definition at line 1289 of file ordered-hash-table.cc.
                                                         {
  if (IsSmallOrderedNameDictionary(*table)) {
    Handle<SmallOrderedNameDictionary> small_dict =
        Cast<SmallOrderedNameDictionary>(table);
    MaybeHandle<SmallOrderedNameDictionary> new_dict =
        SmallOrderedNameDictionary::Add(isolate, small_dict, key, value,
                                        details);
    if (!new_dict.is_null()) return new_dict.ToHandleChecked();
    // We couldn't add to the small table, let's migrate to the
    // big table.
    MaybeHandle<OrderedNameDictionary> table_candidate =
        OrderedNameDictionaryHandler::AdjustRepresentation(isolate, small_dict);
    if (!table_candidate.ToHandle(&table)) {
      return table_candidate;
    }
  }
  DCHECK(IsOrderedNameDictionary(*table));
  return OrderedNameDictionary::Add(isolate, Cast<OrderedNameDictionary>(table),
                                    key, value, details);
}
References v8::bigint::Add(), DCHECK, v8::internal::MaybeHandle< T >::is_null(), v8::internal::key, v8::internal::MaybeHandle< T >::ToHandle(), v8::internal::MaybeHandle< T >::ToHandleChecked(), and v8::internal::value.
AdjustRepresentation()
MaybeHandle< OrderedNameDictionary > v8::internal::OrderedNameDictionaryHandler::AdjustRepresentation (Isolate * isolate, DirectHandle< SmallOrderedNameDictionary > table) [static], [protected]
Definition at line 1217 of file ordered-hash-table.cc.
                                                                      {
  MaybeHandle<OrderedNameDictionary> new_table_candidate =
      OrderedNameDictionary::Allocate(isolate, OrderedHashTableMinSize);
  Handle<OrderedNameDictionary> new_table;
  if (!new_table_candidate.ToHandle(&new_table)) {
    return new_table_candidate;
  }
  // TODO(gsathya): Optimize the lookup to not re calc offsets. Also,
  // unhandlify this code as we preallocate the new backing store with
  // the proper capacity.
  for (InternalIndex entry : table->IterateEntries()) {
    DirectHandle<Name> key(Cast<Name>(table->KeyAt(entry)), isolate);
    if (IsTheHole(*key, isolate)) continue;
    DirectHandle<Object> value(table->ValueAt(entry), isolate);
    PropertyDetails details = table->DetailsAt(entry);
    new_table_candidate =
        OrderedNameDictionary::Add(isolate, new_table, key, value, details);
    if (!new_table_candidate.ToHandle(&new_table)) {
      return new_table_candidate;
    }
  }
  return new_table_candidate;
}
References v8::bigint::Add(), v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::internal::key, v8::internal::MaybeHandle< T >::ToHandle(), and v8::internal::value.
Capacity()
int v8::internal::OrderedNameDictionaryHandler::Capacity (Tagged< HeapObject > table) [static]
Definition at line 1421 of file ordered-hash-table.cc.
                                                                   {
  if (IsSmallOrderedNameDictionary(table)) {
    return Cast<SmallOrderedNameDictionary>(table)->Capacity();
  }
  return Cast<OrderedNameDictionary>(table)->Capacity();
}
DeleteEntry()
DirectHandle< HeapObject > v8::internal::OrderedNameDictionaryHandler::DeleteEntry (Isolate * isolate, Handle< HeapObject > table, InternalIndex entry) [static]
Definition at line 1441 of file ordered-hash-table.cc.
                                                                     {
  DisallowGarbageCollection no_gc;
  if (IsSmallOrderedNameDictionary(*table)) {
    Handle<SmallOrderedNameDictionary> small_dict =
        Cast<SmallOrderedNameDictionary>(table);
    return SmallOrderedNameDictionary::DeleteEntry(isolate, small_dict, entry);
  }
  Handle<OrderedNameDictionary> large_dict = Cast<OrderedNameDictionary>(table);
  return OrderedNameDictionary::DeleteEntry(isolate, large_dict,
                                            InternalIndex(entry));
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
DetailsAt()
PropertyDetails v8::internal::OrderedNameDictionaryHandler::DetailsAt (Tagged< HeapObject > table, InternalIndex entry) [static]
Definition at line 1363 of file ordered-hash-table.cc.
                                                   {
  if (IsSmallOrderedNameDictionary(table)) {
    return Cast<SmallOrderedNameDictionary>(table)->DetailsAt(entry);
  }
  DCHECK(IsOrderedNameDictionary(table));
  return Cast<OrderedNameDictionary>(table)->DetailsAt(entry);
}
References DCHECK.
DetailsAtPut()
void v8::internal::OrderedNameDictionaryHandler::DetailsAtPut (Tagged< HeapObject > table, InternalIndex entry, PropertyDetails value) [static]
Definition at line 1373 of file ordered-hash-table.cc.
                                                                         {
  if (IsSmallOrderedNameDictionary(table)) {
    return Cast<SmallOrderedNameDictionary>(table)->DetailsAtPut(entry,
                                                                 details);
  }
  DCHECK(IsOrderedNameDictionary(table));
  Cast<OrderedNameDictionary>(table)->DetailsAtPut(entry, details);
}
References DCHECK.
FindEntry()
InternalIndex v8::internal::OrderedNameDictionaryHandler::FindEntry (Isolate * isolate, Tagged< HeapObject > table, Tagged< Name > key) [static]
Definition at line 1330 of file ordered-hash-table.cc.
                                                                        {
  DisallowGarbageCollection no_gc;
  if (IsSmallOrderedNameDictionary(table)) {
    return Cast<SmallOrderedNameDictionary>(table)->FindEntry(isolate, key);
  }
  DCHECK(IsOrderedNameDictionary(table));
  return Cast<OrderedNameDictionary>(table)->FindEntry(isolate, key);
}
References DCHECK, v8::internal::key, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Hash()
int v8::internal::OrderedNameDictionaryHandler::Hash (Tagged< HeapObject > table) [static]
Definition at line 1385 of file ordered-hash-table.cc.
                                                               {
  if (IsSmallOrderedNameDictionary(table)) {
    return Cast<SmallOrderedNameDictionary>(table)->Hash();
  }
  DCHECK(IsOrderedNameDictionary(table));
  return Cast<OrderedNameDictionary>(table)->Hash();
}
References DCHECK.
KeyAt()
Tagged< Name > v8::internal::OrderedNameDictionaryHandler::KeyAt (Tagged< HeapObject > table, InternalIndex entry) [static]
Definition at line 1403 of file ordered-hash-table.cc.
                                                                      {
  if (IsSmallOrderedNameDictionary(table)) {
    return Cast<Name>(Cast<SmallOrderedNameDictionary>(table)->KeyAt(entry));
  }
  return Cast<Name>(
      Cast<OrderedNameDictionary>(table)->KeyAt(InternalIndex(entry)));
}
NumberOfElements()
int v8::internal::OrderedNameDictionaryHandler::NumberOfElements (Tagged< HeapObject > table) [static]
Definition at line 1413 of file ordered-hash-table.cc.
                                                                           {
  if (IsSmallOrderedNameDictionary(table)) {
    return Cast<SmallOrderedNameDictionary>(table)->NumberOfElements();
  }
  return Cast<OrderedNameDictionary>(table)->NumberOfElements();
}
SetEntry()
void v8::internal::OrderedNameDictionaryHandler::SetEntry (Tagged< HeapObject > table, InternalIndex entry, Tagged< Object > key, Tagged< Object > value, PropertyDetails details) [static]
Definition at line 1314 of file ordered-hash-table.cc.
                                                                     {
  DisallowGarbageCollection no_gc;
  if (IsSmallOrderedNameDictionary(table)) {
    return Cast<SmallOrderedNameDictionary>(table)->SetEntry(entry, key, value,
                                                             details);
  }
  DCHECK(IsOrderedNameDictionary(table));
  return Cast<OrderedNameDictionary>(table)->SetEntry(InternalIndex(entry), key,
                                                      value, details);
}
References DCHECK, v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
SetHash()
void v8::internal::OrderedNameDictionaryHandler::SetHash (Tagged< HeapObject > table, int hash) [static]
Definition at line 1394 of file ordered-hash-table.cc.
                                                                             {
  if (IsSmallOrderedNameDictionary(table)) {
    return Cast<SmallOrderedNameDictionary>(table)->SetHash(hash);
  }
  DCHECK(IsOrderedNameDictionary(table));
  Cast<OrderedNameDictionary>(table)->SetHash(hash);
}
References DCHECK.
Shrink()
DirectHandle< HeapObject > v8::internal::OrderedNameDictionaryHandler::Shrink (Isolate * isolate, Handle< HeapObject > table) [static]
Definition at line 1429 of file ordered-hash-table.cc.
                                                {
  if (IsSmallOrderedNameDictionary(*table)) {
    Handle<SmallOrderedNameDictionary> small_dict =
        Cast<SmallOrderedNameDictionary>(table);
    return SmallOrderedNameDictionary::Shrink(isolate, small_dict);
  }
  Handle<OrderedNameDictionary> large_dict = Cast<OrderedNameDictionary>(table);
  return OrderedNameDictionary::Shrink(isolate, large_dict);
}
References cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink().
ValueAt()
Tagged< Object > v8::internal::OrderedNameDictionaryHandler::ValueAt (Tagged< HeapObject > table, InternalIndex entry) [static]
Definition at line 1342 of file ordered-hash-table.cc.
                                                                          {
  if (IsSmallOrderedNameDictionary(table)) {
    return Cast<SmallOrderedNameDictionary>(table)->ValueAt(entry);
  }
  DCHECK(IsOrderedNameDictionary(table));
  return Cast<OrderedNameDictionary>(table)->ValueAt(entry);
}
References DCHECK.
ValueAtPut()
void v8::internal::OrderedNameDictionaryHandler::ValueAtPut (Tagged< HeapObject > table, InternalIndex entry, Tagged< Object > value) [static]
Definition at line 1352 of file ordered-hash-table.cc.
                                                                    {
  if (IsSmallOrderedNameDictionary(table)) {
    return Cast<SmallOrderedNameDictionary>(table)->ValueAtPut(entry, value);
  }
  DCHECK(IsOrderedNameDictionary(table));
  Cast<OrderedNameDictionary>(table)->ValueAtPut(entry, value);
}
References DCHECK, and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/ordered-hash-table.h
/mnt/V8SourceCode/src/objects/ordered-hash-table.cc