v8::ArrayBuffer Class Reference
An instance of the built-in ArrayBuffer constructor (ES6 draft 15.13.5).
#include <v8-array-buffer.h>
Classes
class Allocator
A thread-safe allocator that V8 uses to allocate |ArrayBuffer|'s memory.
Public Member Functions
size_t ByteLength () const
Data length in bytes.
size_t MaxByteLength () const
Maximum length in bytes.
bool IsDetachable () const
Returns true if this ArrayBuffer may be detached.
bool WasDetached () const
Returns true if this ArrayBuffer has been detached.
V8_DEPRECATED (`Use the version which takes a key parameter (passing a null handle is ` `ok).`) void Detach()
Detaches this ArrayBuffer and all its views (typed arrays).
V8_WARN_UNUSED_RESULT Maybe< bool > Detach (v8::Local< v8::Value > key)
Detaches this ArrayBuffer and all its views (typed arrays).
void SetDetachKey (v8::Local< v8::Value > key)
Sets the ArrayBufferDetachKey.
std::shared_ptr< BackingStore > GetBackingStore ()
Get a shared pointer to the backing store of this array buffer.
bool IsResizableByUserJavaScript () const
More efficient shortcut for GetBackingStore()->IsResizableByUserJavaScript().
void * Data () const
More efficient shortcut for GetBackingStore()->Data().
Static Public Member Functions
static MaybeLocal< ArrayBuffer > MaybeNew (Isolate *isolate, size_t byte_length, BackingStoreInitializationMode initialization_mode=BackingStoreInitializationMode::kZeroInitialized)
Attempt to create a new ArrayBuffer.
static Local< ArrayBuffer > New (Isolate *isolate, size_t byte_length, BackingStoreInitializationMode initialization_mode=BackingStoreInitializationMode::kZeroInitialized)
Create a new ArrayBuffer.
static Local< ArrayBuffer > New (Isolate *isolate, std::shared_ptr< BackingStore > backing_store)
Create a new ArrayBuffer with an existing backing store.
static std::unique_ptr< BackingStore > NewBackingStore (Isolate *isolate, size_t byte_length, BackingStoreInitializationMode initialization_mode=BackingStoreInitializationMode::kZeroInitialized, BackingStoreOnFailureMode on_failure=BackingStoreOnFailureMode::kOutOfMemory)
Returns a new standalone BackingStore that is allocated using the array buffer allocator of the isolate.
static std::unique_ptr< BackingStore > NewBackingStore (void *data, size_t byte_length, v8::BackingStore::DeleterCallback deleter, void *deleter_data)
Returns a new standalone BackingStore that takes over the ownership of the given buffer.
static std::unique_ptr< BackingStore > NewResizableBackingStore (size_t byte_length, size_t max_byte_length)
Returns a new resizable standalone BackingStore that is allocated using the array buffer allocator of the isolate.
static ArrayBuffer * Cast (Value *value)
Static Public Attributes
static constexpr int kInternalFieldCount
static constexpr int kEmbedderFieldCount = kInternalFieldCount
static constexpr size_t kMaxByteLength
Private Member Functions
ArrayBuffer ()
Static Private Member Functions
static void CheckCast (Value *obj)
Friends
class TypedArray
Additional Inherited Members
Detailed Description
An instance of the built-in ArrayBuffer constructor (ES6 draft 15.13.5).
Definition at line 131 of file v8-array-buffer.h.
Constructor & Destructor Documentation
ArrayBuffer()
v8::ArrayBuffer::ArrayBuffer () [private]
Member Function Documentation
ByteLength()
size_t v8::ArrayBuffer::ByteLength () const
Data length in bytes.
Definition at line 8961 of file api.cc.
                                       {
  return Utils::OpenDirectHandle(this)->GetByteLength();
}
References v8::Utils::OpenDirectHandle().
Cast()
static ArrayBuffer* v8::ArrayBuffer::Cast (Value * value) [inline], [static]
Definition at line 380 of file v8-array-buffer.h.
                                                   {
#ifdef V8_ENABLE_CHECKS
    CheckCast(value);
#endif
    return static_cast<ArrayBuffer*>(value);
  }
References v8::internal::value.
CheckCast()
void v8::ArrayBuffer::CheckCast (Value * obj) [static], [private]
Definition at line 4076 of file api.cc.
                                         {
  auto obj = *Utils::OpenDirectHandle(that);
  Utils::ApiCheck(
      IsJSArrayBuffer(obj) && !i::Cast<i::JSArrayBuffer>(obj)->is_shared(),
      "v8::ArrayBuffer::Cast()", "Value is not an ArrayBuffer");
}
References v8::Utils::ApiCheck(), v8::internal::is_shared, and v8::Utils::OpenDirectHandle().
Data()
void * v8::ArrayBuffer::Data () const
More efficient shortcut for GetBackingStore()->Data().
The returned pointer is valid as long as the ArrayBuffer is alive.
Definition at line 4054 of file api.cc.
                                {
  return Utils::OpenDirectHandle(this)->backing_store();
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorGetterCallback(), v8_inspector::V8Console::CommandLineAPIScope::accessorSetterCallback(), and v8_inspector::V8Console::call().
Detach()
void v8::ArrayBuffer::Detach (v8::Local< v8::Value > key)
Detaches this ArrayBuffer and all its views (typed arrays).
Detaching sets the byte length of the buffer and all typed arrays to zero, preventing JavaScript from ever accessing underlying backing store. ArrayBuffer should have been externalized and must be detachable. Returns Nothing if the key didn't pass the [[ArrayBufferDetachKey]] check, Just(true) otherwise.
Definition at line 8925 of file api.cc.
                                                      {
  auto obj = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  Utils::ApiCheck(obj->is_detachable(), "v8::ArrayBuffer::Detach",
                  "Only detachable ArrayBuffers can be detached");
  Local<Context> context =
      reinterpret_cast<v8::Isolate*>(i_isolate)->GetCurrentContext();
  // TODO(verwaest): Remove this case after forcing the embedder to enter the
  // context.
  if (context.IsEmpty()) {
    EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
    if (key.IsEmpty()) {
      i::JSArrayBuffer::Detach(obj).Check();
    } else {
      auto i_key = Utils::OpenDirectHandle(*key);
      constexpr bool kForceForWasmMemory = false;
      i::JSArrayBuffer::Detach(obj, kForceForWasmMemory, i_key).Check();
    }
    return Just(true);
  }
  EnterV8NoScriptScope<> api_scope{i_isolate, context,
                                   RCCId::kAPI_ArrayBuffer_Detach};
  if (key.IsEmpty()) return i::JSArrayBuffer::Detach(obj);
  auto i_key = Utils::OpenDirectHandle(*key);
  constexpr bool kForceForWasmMemory = false;
  return i::JSArrayBuffer::Detach(obj, kForceForWasmMemory, i_key);
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::JSArrayBuffer::Detach(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::Just(), v8::internal::key, and v8::Utils::OpenDirectHandle().
GetBackingStore()
std::shared_ptr< v8::BackingStore > v8::ArrayBuffer::GetBackingStore ()
Get a shared pointer to the backing store of this array buffer.
This pointer coordinates the lifetime management of the internal storage with any live ArrayBuffers on the heap, even across isolates. The embedder should not attempt to manage lifetime of the storage through other means.
The returned shared pointer will not be empty, even if the ArrayBuffer has been detached. Use |WasDetached| to tell if it has been detached instead.
Definition at line 4043 of file api.cc.
                                                             {
  auto self = Utils::OpenDirectHandle(this);
  std::shared_ptr<i::BackingStore> backing_store = self->GetBackingStore();
  if (!backing_store) {
    backing_store =
        i::BackingStore::EmptyBackingStore(i::SharedFlag::kNotShared);
  }
  std::shared_ptr<i::BackingStoreBase> bs_base = backing_store;
  return std::static_pointer_cast<v8::BackingStore>(bs_base);
}
References v8::internal::BackingStore::EmptyBackingStore(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::kNotShared, and v8::Utils::OpenDirectHandle().
IsDetachable()
bool v8::ArrayBuffer::IsDetachable () const
Returns true if this ArrayBuffer may be detached.
Definition at line 8910 of file api.cc.
                                       {
  return Utils::OpenDirectHandle(this)->is_detachable();
}
References v8::Utils::OpenDirectHandle().
IsResizableByUserJavaScript()
bool v8::ArrayBuffer::IsResizableByUserJavaScript () const
More efficient shortcut for GetBackingStore()->IsResizableByUserJavaScript().
Definition at line 4058 of file api.cc.
                                                      {
  return Utils::OpenDirectHandle(this)->is_resizable_by_js();
}
References v8::Utils::OpenDirectHandle().
MaxByteLength()
size_t v8::ArrayBuffer::MaxByteLength () const
Maximum length in bytes.
Definition at line 8965 of file api.cc.
                                          {
  return Utils::OpenDirectHandle(this)->max_byte_length();
}
References v8::Utils::OpenDirectHandle().
MaybeNew()
MaybeLocal< ArrayBuffer > v8::ArrayBuffer::MaybeNew (Isolate * isolate, size_t byte_length, BackingStoreInitializationMode initialization_mode = BackingStoreInitializationMode::kZeroInitialized) [static]
Attempt to create a new ArrayBuffer.
Allocate |byte_length| bytes. Allocated memory will be owned by a created ArrayBuffer and will be deallocated when it is garbage-collected, unless the object is externalized. If allocation fails, the Maybe returned will be empty.
Definition at line 8982 of file api.cc.
                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_ArrayBuffer_MaybeNew);
  size_t max = i_isolate->array_buffer_allocator()->MaxAllocationSize();
  DCHECK(max <= ArrayBuffer::kMaxByteLength);
  if (byte_length > max) return {};
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::MaybeDirectHandle<i::JSArrayBuffer> result =
      i_isolate->factory()->NewJSArrayBufferAndBackingStore(
          byte_length, GetInitializedFlag(initialization_mode));
  i::DirectHandle<i::JSArrayBuffer> array_buffer;
  if (!result.ToHandle(&array_buffer)) return {};
  return Utils::ToLocal(array_buffer);
}
References v8::internal::Isolate::array_buffer_allocator(), DCHECK, v8::internal::Isolate::factory(), v8::anonymous_namespace{api.cc}::GetInitializedFlag(), kMaxByteLength, v8::ArrayBuffer::Allocator::MaxAllocationSize(), v8::internal::Factory::NewJSArrayBufferAndBackingStore(), and v8::base::internal::result.
New() [1/2]
Local< ArrayBuffer > v8::ArrayBuffer::New (Isolate * isolate, size_t byte_length, BackingStoreInitializationMode initialization_mode = BackingStoreInitializationMode::kZeroInitialized) [static]
Create a new ArrayBuffer.
Allocate |byte_length| bytes, which are either zero-initialized or uninitialized. Allocated memory will be owned by a created ArrayBuffer and will be deallocated when it is garbage-collected, unless the object is externalized.
Definition at line 9002 of file api.cc.
                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_ArrayBuffer_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  i::MaybeDirectHandle<i::JSArrayBuffer> result =
      i_isolate->factory()->NewJSArrayBufferAndBackingStore(
          byte_length, GetInitializedFlag(initialization_mode));
  i::DirectHandle<i::JSArrayBuffer> array_buffer;
  if (!result.ToHandle(&array_buffer)) {
    i::V8::FatalProcessOutOfMemory(i_isolate, "v8::ArrayBuffer::New");
  }
  return Utils::ToLocal(array_buffer);
}
References v8::internal::Isolate::factory(), v8::internal::V8::FatalProcessOutOfMemory(), v8::anonymous_namespace{api.cc}::GetInitializedFlag(), v8::internal::Factory::NewJSArrayBufferAndBackingStore(), and v8::base::internal::result.
Referenced by v8_inspector::V8Console::CommandLineAPIScope::CommandLineAPIScope(), v8_inspector::V8Console::createCommandLineAPI(), v8::Shell::ReadBuffer(), v8::Deserializer::ReadValue(), and v8::Shell::SerializerSerialize().
New() [2/2]
Local< ArrayBuffer > v8::ArrayBuffer::New (Isolate * isolate, std::shared_ptr< BackingStore > backing_store) [static]
Create a new ArrayBuffer with an existing backing store.
The created array keeps a reference to the backing store until the array is garbage collected. Note that the IsExternal bit does not affect this reference from the array to the backing store.
In future IsExternal bit will be removed. Until then the bit is set as follows. If the backing store does not own the underlying buffer, then the array is created in externalized state. Otherwise, the array is created in internalized state. In the latter case the array can be transitioned to the externalized state using Externalize(backing_store).
Definition at line 9020 of file api.cc.
                                                                    {
  CHECK_IMPLIES(backing_store->ByteLength() != 0,
                backing_store->Data() != nullptr);
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_ArrayBuffer_New);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  std::shared_ptr<i::BackingStore> i_backing_store(
      ToInternal(std::move(backing_store)));
  Utils::ApiCheck(
      !i_backing_store->is_shared(), "v8_ArrayBuffer_New",
      "Cannot construct ArrayBuffer with a BackingStore of SharedArrayBuffer");
  i::DirectHandle<i::JSArrayBuffer> obj =
      i_isolate->factory()->NewJSArrayBuffer(std::move(i_backing_store));
  return Utils::ToLocal(obj);
}
References v8::Utils::ApiCheck(), CHECK_IMPLIES, v8::internal::Isolate::factory(), v8::internal::Factory::NewJSArrayBuffer(), and v8::ToInternal().
NewBackingStore() [1/2]
std::unique_ptr< v8::BackingStore > v8::ArrayBuffer::NewBackingStore (Isolate * isolate, size_t byte_length, BackingStoreInitializationMode initialization_mode = BackingStoreInitializationMode::kZeroInitialized, BackingStoreOnFailureMode on_failure = BackingStoreOnFailureMode::kOutOfMemory) [static]
Returns a new standalone BackingStore that is allocated using the array buffer allocator of the isolate.
The allocation can either be zero initialized, or uninitialized. The result can be later passed to ArrayBuffer::New.
If the allocator returns nullptr, then the function may cause GCs in the given isolate and re-try the allocation.
If GCs do not help and on_failure is kOutOfMemory, then the function will crash with an out-of-memory error.
Otherwise if GCs do not help (or the allocation is too large for GCs to help) and on_failure is kReturnNull, then a null result is returned.
Definition at line 9037 of file api.cc.
                                          {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate,
                                     RCCId::kAPI_ArrayBuffer_NewBackingStore);
  if (on_failure == BackingStoreOnFailureMode::kOutOfMemory) {
    CHECK_LE(byte_length, i::JSArrayBuffer::kMaxByteLength);
  } else if (byte_length > i::JSArrayBuffer::kMaxByteLength) {
    DCHECK(on_failure == BackingStoreOnFailureMode::kReturnNull);
    return {};
  }
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  std::unique_ptr<i::BackingStoreBase> backing_store =
      i::BackingStore::Allocate(i_isolate, byte_length,
                                i::SharedFlag::kNotShared,
                                GetInitializedFlag(initialization_mode));
  if (!backing_store) {
    if (on_failure == BackingStoreOnFailureMode::kOutOfMemory) {
      i::V8::FatalProcessOutOfMemory(i_isolate,
                                     "v8::ArrayBuffer::NewBackingStore");
    } else {
      DCHECK(on_failure == BackingStoreOnFailureMode::kReturnNull);
      return {};
    }
  }
  return std::unique_ptr<v8::BackingStore>(
      static_cast<v8::BackingStore*>(backing_store.release()));
}
References v8::internal::BackingStore::Allocate(), CHECK_LE, DCHECK, v8::internal::V8::FatalProcessOutOfMemory(), v8::anonymous_namespace{api.cc}::GetInitializedFlag(), v8::internal::JSArrayBuffer::kMaxByteLength, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::kNotShared, v8::kOutOfMemory, and v8::kReturnNull.
NewBackingStore() [2/2]
std::unique_ptr< v8::BackingStore > v8::ArrayBuffer::NewBackingStore (void * data, size_t byte_length, v8::BackingStore::DeleterCallback deleter, void * deleter_data) [static]
Returns a new standalone BackingStore that takes over the ownership of the given buffer.
The destructor of the BackingStore invokes the given deleter callback.
The result can be later passed to ArrayBuffer::New. The raw pointer to the buffer must not be passed again to any V8 API function.
Definition at line 9081 of file api.cc.
                        {
  CHECK_LE(byte_length, i::JSArrayBuffer::kMaxByteLength);
#ifdef V8_ENABLE_SANDBOX
  Utils::ApiCheck(!data || i::Sandbox::current()->Contains(data),
                  "v8_ArrayBuffer_NewBackingStore",
                  "When the V8 Sandbox is enabled, ArrayBuffer backing stores "
                  "must be allocated inside the sandbox address space. Please "
                  "use an appropriate ArrayBuffer::Allocator to allocate these "
                  "buffers, or disable the sandbox.");
#endif // V8_ENABLE_SANDBOX
  std::unique_ptr<i::BackingStoreBase> backing_store =
      i::BackingStore::WrapAllocation(data, byte_length, deleter, deleter_data,
                                      i::SharedFlag::kNotShared);
  return std::unique_ptr<v8::BackingStore>(
      static_cast<v8::BackingStore*>(backing_store.release()));
}
References v8::Utils::ApiCheck(), CHECK_LE, v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains(), v8::internal::JSArrayBuffer::kMaxByteLength, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::kNotShared, and v8::internal::BackingStore::WrapAllocation().
NewResizableBackingStore()
std::unique_ptr< BackingStore > v8::ArrayBuffer::NewResizableBackingStore (size_t byte_length, size_t max_byte_length) [static]
Returns a new resizable standalone BackingStore that is allocated using the array buffer allocator of the isolate.
The result can be later passed to ArrayBuffer::New.
|byte_length| must be <= |max_byte_length|.
This function is usable without an isolate. Unlike |NewBackingStore| calls with an isolate, GCs cannot be triggered, and there are no retries. Allocation failure will cause the function to crash with an out-of-memory error.
Definition at line 9102 of file api.cc.
                                                {
  Utils::ApiCheck(byte_length <= max_byte_length,
                  "v8::ArrayBuffer::NewResizableBackingStore",
                  "Cannot construct resizable ArrayBuffer, byte_length must be "
                  "<= max_byte_length");
  Utils::ApiCheck(
      byte_length <= i::JSArrayBuffer::kMaxByteLength,
      "v8::ArrayBuffer::NewResizableBackingStore",
      "Cannot construct resizable ArrayBuffer, requested length is too big");
  size_t page_size, initial_pages, max_pages;
  if (i::JSArrayBuffer::GetResizableBackingStorePageConfiguration(
          nullptr, byte_length, max_byte_length, i::kDontThrow, &page_size,
          &initial_pages, &max_pages)
          .IsNothing()) {
    i::V8::FatalProcessOutOfMemory(nullptr,
                                   "v8::ArrayBuffer::NewResizableBackingStore");
  }
  std::unique_ptr<i::BackingStoreBase> backing_store =
      i::BackingStore::TryAllocateAndPartiallyCommitMemory(
          nullptr, byte_length, max_byte_length, page_size, initial_pages,
          max_pages, i::WasmMemoryFlag::kNotWasm, i::SharedFlag::kNotShared);
  if (!backing_store) {
    i::V8::FatalProcessOutOfMemory(nullptr,
                                   "v8::ArrayBuffer::NewResizableBackingStore");
  }
  return std::unique_ptr<v8::BackingStore>(
      static_cast<v8::BackingStore*>(backing_store.release()));
}
References v8::Utils::ApiCheck(), v8::internal::V8::FatalProcessOutOfMemory(), v8::internal::JSArrayBuffer::GetResizableBackingStorePageConfiguration(), v8::internal::kDontThrow, v8::internal::JSArrayBuffer::kMaxByteLength, v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::kNotShared, and v8::internal::BackingStore::TryAllocateAndPartiallyCommitMemory().
SetDetachKey()
void v8::ArrayBuffer::SetDetachKey (v8::Local< v8::Value > key)
Sets the ArrayBufferDetachKey.
Definition at line 8955 of file api.cc.
                                                     {
  auto obj = Utils::OpenDirectHandle(this);
  auto i_key = Utils::OpenDirectHandle(*key);
  obj->set_detach_key(*i_key);
}
References v8::internal::key, and v8::Utils::OpenDirectHandle().
V8_DEPRECATED()
v8::ArrayBuffer::V8_DEPRECATED (`Use the version which takes a key parameter (passing a null handle is ` `ok).`)
Detaches this ArrayBuffer and all its views (typed arrays).
Detaching sets the byte length of the buffer and all typed arrays to zero, preventing JavaScript from ever accessing underlying backing store. ArrayBuffer should have been externalized and must be detachable.
WasDetached()
bool v8::ArrayBuffer::WasDetached () const
Returns true if this ArrayBuffer has been detached.
Definition at line 8914 of file api.cc.
                                      {
  return Utils::OpenDirectHandle(this)->was_detached();
}
References v8::Utils::OpenDirectHandle().
Friends And Related Function Documentation
TypedArray
friend class TypedArray [friend]
Definition at line 405 of file v8-array-buffer.h.
Member Data Documentation
kEmbedderFieldCount
constexpr int v8::ArrayBuffer::kEmbedderFieldCount = kInternalFieldCount [static], [constexpr]
Definition at line 389 of file v8-array-buffer.h.
Referenced by v8::internal::JSArrayBuffer::Setup().
kInternalFieldCount
constexpr int v8::ArrayBuffer::kInternalFieldCount [static], [constexpr]
Initial value:
=
      V8_ARRAY_BUFFER_INTERNAL_FIELD_COUNT
Definition at line 387 of file v8-array-buffer.h.
kMaxByteLength
constexpr size_t v8::ArrayBuffer::kMaxByteLength [static], [constexpr]
Initial value:
=
      static_cast<size_t>((uint64_t{1} << 53) - 1)
Definition at line 398 of file v8-array-buffer.h.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadTypedArrayLength(), and MaybeNew().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-array-buffer.h
/mnt/V8SourceCode/src/api/api.cc