v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency Class Reference
Public Member Functions
FieldRepresentationDependency (MapRef map, MapRef owner, InternalIndex descriptor, Representation representation)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
bool DependsOn (const Handle< Map > &receiver_map) const
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const MapRef map_
const MapRef owner_
const InternalIndex descriptor_
const Representation representation_
Additional Inherited Members
Detailed Description
Definition at line 721 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
FieldRepresentationDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::FieldRepresentationDependency (MapRef map, MapRef owner, InternalIndex descriptor, Representation representation) [inline]
Definition at line 723 of file compilation-dependencies.cc.
      : CompilationDependency(kFieldRepresentation),
        map_(map),
        owner_(owner),
        descriptor_(descriptor),
        representation_(representation) {}
Member Function Documentation
DependsOn()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::DependsOn (const Handle< Map > & receiver_map) const [inline]
Definition at line 752 of file compilation-dependencies.cc.
                                                        {
    return map_.object().equals(receiver_map);
  }
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 763 of file compilation-dependencies.cc.
                                                                {
    const FieldRepresentationDependency* const zat =
        that->AsFieldRepresentation();
    return map_.equals(zat->map_) && descriptor_ == zat->descriptor_ &&
           representation_.Equals(zat->representation_);
  }
References descriptor_, map_, and representation_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 757 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(map_), descriptor_.as_int(),
                              representation_.kind());
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 741 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    Isolate* isolate = broker->isolate();
    Handle<Map> owner = owner_.object();
    CHECK(!owner->is_deprecated());
    CHECK(representation_.Equals(owner->instance_descriptors(isolate)
                                     ->GetDetails(descriptor_)
                                     .representation()));
    deps->Register(owner, DependentCode::kFieldRepresentationGroup);
  }
References broker(), CHECK, v8::internal::DependentCode::kFieldRepresentationGroup, v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::PendingDependencies::Register(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 732 of file compilation-dependencies.cc.
                                                    {
    DisallowGarbageCollection no_heap_allocation;
    if (map_.object()->is_deprecated()) return false;
    return representation_.Equals(map_.object()
                                      ->instance_descriptors(broker->isolate())
                                      ->GetDetails(descriptor_)
                                      .representation());
  }
References broker().
Member Data Documentation
descriptor_
const InternalIndex v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::descriptor_ [private]
Definition at line 772 of file compilation-dependencies.cc.
Referenced by Equals().
map_
const MapRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::map_ [private]
Definition at line 770 of file compilation-dependencies.cc.
Referenced by Equals().
owner_
const MapRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::owner_ [private]
Definition at line 771 of file compilation-dependencies.cc.
representation_
const Representation v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::FieldRepresentationDependency::representation_ [private]
Definition at line 773 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc