v8::internal::ProtectedFixedArray Class Reference
#include <fixed-array.h>
Classes
class BodyDescriptor
Static Public Member Functions
template<class IsolateT >
static Handle< ProtectedFixedArray > New (IsolateT *isolate, int capacity, bool shared=false)
Static Public Attributes
static constexpr int kMaxLength = Super::kMaxCapacity
static constexpr int kMaxRegularLength
Private Types
using Super = TaggedArrayBase< ProtectedFixedArray, ProtectedArrayShape, TrustedObjectLayout >
Additional Inherited Members
Detailed Description
Definition at line 332 of file fixed-array.h.
Member Typedef Documentation
Super
using v8::internal::ProtectedFixedArray::Super = TaggedArrayBase<ProtectedFixedArray, ProtectedArrayShape, TrustedObjectLayout> [private]
Definition at line 335 of file fixed-array.h.
Member Function Documentation
New()
template<class IsolateT >
Handle< ProtectedFixedArray > v8::internal::ProtectedFixedArray::New (IsolateT * isolate, int capacity, bool shared = false) [inline], [static]
Definition at line 337 of file fixed-array-inl.h.
                                                                  {
  if (V8_UNLIKELY(static_cast<unsigned>(capacity) >
                  ProtectedFixedArray::kMaxLength)) {
    FATAL("Fatal JavaScript invalid size error %d (see crbug.com/1201626)",
          capacity);
  }
  std::optional<DisallowGarbageCollection> no_gc;
  Handle<ProtectedFixedArray> result = Cast<ProtectedFixedArray>(Allocate(
      isolate, capacity, &no_gc,
      shared ? AllocationType::kSharedTrusted : AllocationType::kTrusted));
  MemsetTagged((*result)->RawFieldOfFirstElement(), Smi::zero(), capacity);
  return result;
}
References v8::internal::TaggedArrayBase< ProtectedFixedArray, ProtectedArrayShape, TrustedObjectLayout >::Allocate(), FATAL, kMaxLength, v8::internal::kSharedTrusted, v8::internal::kTrusted, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, V8_UNLIKELY, and v8::internal::Smi::zero().
Referenced by v8::internal::Heap::CreateInitialMutableObjects().
Member Data Documentation
kMaxLength
constexpr int v8::internal::ProtectedFixedArray::kMaxLength = Super::kMaxCapacity [static], [constexpr]
Definition at line 350 of file fixed-array.h.
Referenced by New().
kMaxRegularLength
constexpr int v8::internal::ProtectedFixedArray::kMaxRegularLength [static], [constexpr]
Initial value:
=
      ProtectedFixedArray::kMaxRegularCapacity
Definition at line 351 of file fixed-array.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h