v8::internal::ScavengerCollector Class Reference
#include <scavenger.h>
Classes
class JobTask
struct PinnedObjectEntry
class QuarantinedPageSweeper
Public Types
using PinnedObjects = std::vector< PinnedObjectEntry >
Public Member Functions
ScavengerCollector (Heap *heap)
void CollectGarbage ()
void CompleteSweepingQuarantinedPagesIfNeeded ()
Static Public Attributes
static const int kMaxScavengerTasks = 8
static const int kMainThreadId = 0
Private Member Functions
void MergeSurvivingNewLargeObjects (const SurvivingNewLargeObjectsMap &objects)
int NumberOfScavengeTasks ()
void ProcessWeakReferences (EphemeronRememberedSet::TableList *ephemeron_table_list)
void ClearYoungEphemerons (EphemeronRememberedSet::TableList *ephemeron_table_list)
void ClearOldEphemerons ()
void HandleSurvivingNewLargeObjects ()
void SweepArrayBufferExtensions ()
size_t FetchAndResetConcurrencyEstimate ()
Private Attributes
Isolate *const isolate_
Heap *const heap_
SurvivingNewLargeObjectsMap surviving_new_large_objects_
std::atomic< size_t > estimate_concurrency_ {0}
QuarantinedPageSweeper quarantined_page_sweeper_
Friends
class Scavenger
Detailed Description
Definition at line 234 of file scavenger.h.
Member Typedef Documentation
PinnedObjects
using v8::internal::ScavengerCollector::PinnedObjects = std::vector<PinnedObjectEntry>
Definition at line 241 of file scavenger.h.
Constructor & Destructor Documentation
ScavengerCollector()
v8::internal::ScavengerCollector::ScavengerCollector (Heap * heap) [explicit]
Definition at line 305 of file scavenger.cc.
    : isolate_(heap->isolate()), heap_(heap), quarantined_page_sweeper_(heap) {}
Member Function Documentation
ClearOldEphemerons()
void v8::internal::ScavengerCollector::ClearOldEphemerons () [private]
Definition at line 1323 of file scavenger.cc.
                                            {
  auto* table_map = heap_->ephemeron_remembered_set_->tables();
  for (auto it = table_map->begin(); it != table_map->end();) {
    Tagged<EphemeronHashTable> table = it->first;
    auto& indices = it->second;
    for (auto iti = indices.begin(); iti != indices.end();) {
      // Keys in EphemeronHashTables must be heap objects.
      HeapObjectSlot key_slot(table->RawFieldOfElementAt(
          EphemeronHashTable::EntryToIndex(InternalIndex(*iti))));
      Tagged<HeapObject> key = key_slot.ToHeapObject();
      if (IsUnscavengedHeapObject(heap_, key)) {
        table->RemoveEntry(InternalIndex(*iti));
        iti = indices.erase(iti);
      } else {
        Tagged<HeapObject> forwarded = ForwardingAddress(key);
        key_slot.StoreHeapObject(forwarded);
        if (!HeapLayout::InYoungGeneration(forwarded)) {
          iti = indices.erase(iti);
        } else {
          ++iti;
        }
      }
    }
    if (indices.empty()) {
      it = table_map->erase(it);
    } else {
      ++it;
    }
  }
}
References v8::internal::ForwardingAddress(), v8::internal::anonymous_namespace{scavenger.cc}::IsUnscavengedHeapObject(), v8::internal::key, v8::internal::FullHeapObjectSlot::StoreHeapObject(), and v8::internal::FullHeapObjectSlot::ToHeapObject().
Referenced by ProcessWeakReferences().
ClearYoungEphemerons()
void v8::internal::ScavengerCollector::ClearYoungEphemerons (EphemeronRememberedSet::TableList * ephemeron_table_list) [private]
Definition at line 1302 of file scavenger.cc.
                                                           {
  ephemeron_table_list->Iterate([this](Tagged<EphemeronHashTable> table) {
    for (InternalIndex i : table->IterateEntries()) {
      // Keys in EphemeronHashTables must be heap objects.
      HeapObjectSlot key_slot(
          table->RawFieldOfElementAt(EphemeronHashTable::EntryToIndex(i)));
      Tagged<HeapObject> key = key_slot.ToHeapObject();
      if (IsUnscavengedHeapObject(heap_, key)) {
        table->RemoveEntry(i);
      } else {
        Tagged<HeapObject> forwarded = ForwardingAddress(key);
        key_slot.StoreHeapObject(forwarded);
      }
    }
  });
  ephemeron_table_list->Clear();
}
References heap::base::Worklist< EntryType, MinSegmentSize >::Iterate().
Referenced by ProcessWeakReferences().
CollectGarbage()
void v8::internal::ScavengerCollector::CollectGarbage ()
Definition at line 812 of file scavenger.cc.
                                        {
  ScopedFullHeapCrashKey collect_full_heap_dump_if_crash(isolate_);
  DCHECK(surviving_new_large_objects_.empty());
  DCHECK(!quarantined_page_sweeper_.IsSweeping());
  SemiSpaceNewSpace* new_space = SemiSpaceNewSpace::From(heap_->new_space());
  new_space->GarbageCollectionPrologue();
  new_space->SwapSemiSpaces();
  // We also flip the young generation large object space. All large objects
  // will be in the from space.
  heap_->new_lo_space()->Flip();
  heap_->new_lo_space()->ResetPendingObject();
  DCHECK(!heap_->allocator()->new_space_allocator()->IsLabValid());
  Scavenger::EmptyChunksList empty_chunks;
  Scavenger::CopiedList copied_list;
  Scavenger::PinnedList pinned_list;
  Scavenger::PromotedList promoted_list;
  EphemeronRememberedSet::TableList ephemeron_table_list;
  PinnedObjects pinned_objects;
  const int num_scavenge_tasks = NumberOfScavengeTasks();
  std::vector<std::unique_ptr<Scavenger>> scavengers;
  const bool is_logging = isolate_->log_object_relocation();
  for (int i = 0; i < num_scavenge_tasks; ++i) {
    scavengers.emplace_back(
        new Scavenger(this, heap_, is_logging, &empty_chunks, &copied_list,
                      &pinned_list, &promoted_list, &ephemeron_table_list));
  }
  Scavenger& main_thread_scavenger = *scavengers[kMainThreadId].get();
  {
    // Identify weak unmodified handles. Requires an unmodified graph.
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::SCAVENGER_SCAVENGE_WEAK_GLOBAL_HANDLES_IDENTIFY);
    isolate_->traced_handles()->ComputeWeaknessForYoungObjects();
  }
  std::vector<std::pair<ParallelWorkItem, MutablePageMetadata*>>
      old_to_new_chunks;
  {
    // Copy roots.
    TRACE_GC(heap_->tracer(), GCTracer::Scope::SCAVENGER_SCAVENGE_ROOTS);
    // We must collect old-to-new pages before starting Scavenge because
    // pages could be removed from the old generation for allocation which
    // hides them from the iteration.
    OldGenerationMemoryChunkIterator::ForAll(
        heap_, [&old_to_new_chunks](MutablePageMetadata* chunk) {
          if (chunk->slot_set<OLD_TO_NEW>() ||
              chunk->typed_slot_set<OLD_TO_NEW>() ||
              chunk->slot_set<OLD_TO_NEW_BACKGROUND>()) {
            old_to_new_chunks.emplace_back(ParallelWorkItem{}, chunk);
          }
        });
    const Heap::StackScanMode stack_scan_mode =
        heap_->ConservativeStackScanningModeForMinorGC();
    DCHECK_IMPLIES(stack_scan_mode == Heap::StackScanMode::kSelective,
                   heap_->IsGCWithStack());
    if ((stack_scan_mode != Heap::StackScanMode::kNone) &&
        heap_->IsGCWithStack()) {
      // Pinning objects must be the first step and must happen before
      // scavenging any objects. Specifically we must all pin all objects
      // before visiting other pinned objects. If we scavenge some object X
      // and move it before all stack-reachable objects are pinned, and we
      // later find that we need to pin X, it will be too late to undo the
      // moving.
      TRACE_GC(heap_->tracer(),
               GCTracer::Scope::SCAVENGER_SCAVENGE_PIN_OBJECTS);
      ConservativeObjectPinningVisitor conservative_pinning_visitor(
          heap_, main_thread_scavenger, pinned_objects);
      // Scavenger reuses the page's marking bitmap as a temporary object
      // start bitmap. Stack scanning will incrementally build the map as it
      // searches through pages.
      YoungGenerationConservativeStackVisitor stack_visitor(
          isolate_, &conservative_pinning_visitor);
      // Marker was already set by Heap::CollectGarbage.
      heap_->IterateConservativeStackRoots(&stack_visitor, stack_scan_mode);
      if (V8_UNLIKELY(v8_flags.stress_scavenger_conservative_object_pinning)) {
        TreatConservativelyVisitor handles_visitor(&stack_visitor, heap_);
        heap_->IterateRootsForPrecisePinning(&handles_visitor);
      }
    }
    const bool is_using_precise_pinning =
        heap_->ShouldUsePrecisePinningForMinorGC();
    if (is_using_precise_pinning) {
      PreciseObjectPinningVisitor precise_pinning_visitor(
          heap_, main_thread_scavenger, pinned_objects);
      ClearStaleLeftTrimmedPointerVisitor left_trim_visitor(
          heap_, &precise_pinning_visitor);
      heap_->IterateRootsForPrecisePinning(&left_trim_visitor);
    }
    // Scavenger treats all weak roots except for global handles as strong.
    // That is why we don't set skip_weak = true here and instead visit
    // global handles separately.
    base::EnumSet<SkipRoot> options(
        {SkipRoot::kExternalStringTable, SkipRoot::kGlobalHandles,
         SkipRoot::kTracedHandles, SkipRoot::kOldGeneration,
         SkipRoot::kConservativeStack, SkipRoot::kReadOnlyBuiltins});
    if (is_using_precise_pinning) {
      options.Add({SkipRoot::kMainThreadHandles, SkipRoot::kStack});
    }
    RootScavengeVisitor root_scavenge_visitor(main_thread_scavenger);
    heap_->IterateRoots(&root_scavenge_visitor, options);
    isolate_->global_handles()->IterateYoungStrongAndDependentRoots(
        &root_scavenge_visitor);
    isolate_->traced_handles()->IterateYoungRoots(&root_scavenge_visitor);
  }
  {
    // Parallel phase scavenging all copied and promoted objects.
    TRACE_GC_ARG1(heap_->tracer(),
                  GCTracer::Scope::SCAVENGER_SCAVENGE_PARALLEL_PHASE,
                  "UseBackgroundThreads", heap_->ShouldUseBackgroundThreads());
    auto job = std::make_unique<JobTask>(
        this, &scavengers, std::move(old_to_new_chunks), copied_list,
        pinned_list, promoted_list);
    TRACE_GC_NOTE_WITH_FLOW("Parallel scavenge started", job->trace_id(),
                            TRACE_EVENT_FLAG_FLOW_OUT);
    V8::GetCurrentPlatform()
        ->CreateJob(v8::TaskPriority::kUserBlocking, std::move(job))
        ->Join();
    DCHECK(copied_list.IsEmpty());
    DCHECK(pinned_list.IsEmpty());
    DCHECK(promoted_list.IsEmpty());
  }
  {
    // Scavenge weak global handles.
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::SCAVENGER_SCAVENGE_WEAK_GLOBAL_HANDLES_PROCESS);
    GlobalHandlesWeakRootsUpdatingVisitor visitor;
    isolate_->global_handles()->ProcessWeakYoungObjects(
        &visitor, &IsUnscavengedHeapObjectSlot);
    isolate_->traced_handles()->ProcessWeakYoungObjects(
        &visitor, &IsUnscavengedHeapObjectSlot);
  }
  {
    // Finalize parallel scavenging.
    TRACE_GC(heap_->tracer(), GCTracer::Scope::SCAVENGER_SCAVENGE_FINALIZE);
    DCHECK(surviving_new_large_objects_.empty());
    for (auto& scavenger : scavengers) {
      scavenger->Finalize();
    }
    scavengers.clear();
#ifdef V8_COMPRESS_POINTERS
    // Sweep the external pointer table.
    DCHECK(heap_->concurrent_marking()->IsStopped());
    DCHECK(!heap_->incremental_marking()->IsMajorMarking());
    heap_->isolate()->external_pointer_table().Sweep(
        heap_->young_external_pointer_space(), heap_->isolate()->counters());
#endif // V8_COMPRESS_POINTERS
    HandleSurvivingNewLargeObjects();
    heap_->tracer()->SampleConcurrencyEsimate(
        FetchAndResetConcurrencyEstimate());
  }
  {
    // Update references into new space
    TRACE_GC(heap_->tracer(), GCTracer::Scope::SCAVENGER_SCAVENGE_UPDATE_REFS);
    heap_->UpdateYoungReferencesInExternalStringTable(
        &Heap::UpdateYoungReferenceInExternalStringTableEntry);
    if (V8_UNLIKELY(v8_flags.always_use_string_forwarding_table)) {
      isolate_->string_forwarding_table()->UpdateAfterYoungEvacuation();
    }
  }
  ProcessWeakReferences(&ephemeron_table_list);
  {
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::SCAVENGER_SCAVENGE_RESTORE_AND_QUARANTINE_PINNED);
    RestorePinnedObjects(*new_space, pinned_objects);
    QuarantinePinnedPages(*new_space);
  }
  // Need to free new space LAB that was allocated during scavenge.
  heap_->allocator()->new_space_allocator()->FreeLinearAllocationArea();
  // Since we promote all surviving large objects immediately, all remaining
  // large objects must be dead.
  // TODO(hpayer): Don't free all as soon as we have an intermediate generation.
  heap_->new_lo_space()->FreeDeadObjects(
      [](Tagged<HeapObject>) { return true; });
  new_space->GarbageCollectionEpilogue();
  // Start sweeping quarantined pages.
  if (!pinned_objects.empty()) {
    quarantined_page_sweeper_.StartSweeping(std::move(pinned_objects));
  } else {
    // Sweeping is not started since there are no pages to sweep. Mark sweeping
    // as completed so that the current GC cycle can be stopped since there is
    // no sweeper to mark it has completed later.
    heap_->tracer()->NotifyYoungSweepingCompleted();
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::SCAVENGER_FREE_REMEMBERED_SET);
    Scavenger::EmptyChunksList::Local empty_chunks_local(empty_chunks);
    MutablePageMetadata* chunk;
    while (empty_chunks_local.Pop(&chunk)) {
      RememberedSet<OLD_TO_NEW>::CheckPossiblyEmptyBuckets(chunk);
      RememberedSet<OLD_TO_NEW_BACKGROUND>::CheckPossiblyEmptyBuckets(chunk);
    }
#ifdef DEBUG
    OldGenerationMemoryChunkIterator::ForAll(
        heap_, [](MutablePageMetadata* chunk) {
          if (chunk->slot_set<OLD_TO_NEW>() ||
              chunk->typed_slot_set<OLD_TO_NEW>() ||
              chunk->slot_set<OLD_TO_NEW_BACKGROUND>()) {
            DCHECK(chunk->possibly_empty_buckets()->IsEmpty());
          }
        });
#endif
  }
  SweepArrayBufferExtensions();
  isolate_->global_handles()->UpdateListOfYoungNodes();
  isolate_->traced_handles()->UpdateListOfYoungNodes();
  // Update how much has survived scavenge.
  heap_->IncrementYoungSurvivorsCounter(heap_->SurvivedYoungObjectSize());
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::SCAVENGER_RESIZE_NEW_SPACE);
    heap_->ResizeNewSpace();
  }
}
References v8::base::EnumSet< E, T >::Add(), v8::internal::Heap::allocator(), v8::internal::TracedHandles::ComputeWeaknessForYoungObjects(), v8::internal::Heap::ConservativeStackScanningModeForMinorGC(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::NewLargeObjectSpace::Flip(), v8::internal::OldGenerationMemoryChunkIterator::ForAll(), v8::internal::SemiSpaceNewSpace::From(), v8::internal::SemiSpaceNewSpace::GarbageCollectionPrologue(), v8::internal::Isolate::global_handles(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::heap_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Heap::IsGCWithStack(), v8::internal::MainAllocator::IsLabValid(), isolate_, v8::internal::ScavengerCollector::QuarantinedPageSweeper::IsSweeping(), v8::internal::Heap::IterateConservativeStackRoots(), v8::internal::Heap::IterateRoots(), v8::internal::Heap::IterateRootsForPrecisePinning(), v8::internal::TracedHandles::IterateYoungRoots(), v8::internal::GlobalHandles::IterateYoungStrongAndDependentRoots(), v8::internal::kConservativeStack, v8::internal::kExternalStringTable, v8::internal::kGlobalHandles, v8::internal::kMainThreadHandles, kMainThreadId, v8::internal::Heap::kNone, v8::internal::kOldGeneration, v8::internal::kReadOnlyBuiltins, v8::internal::Heap::kSelective, v8::internal::kStack, v8::internal::kTracedHandles, v8::internal::Isolate::log_object_relocation(), v8::internal::Heap::new_lo_space(), v8::internal::Heap::new_space(), v8::internal::HeapAllocator::new_space_allocator(), NumberOfScavengeTasks(), v8::internal::OLD_TO_NEW, v8::internal::OLD_TO_NEW_BACKGROUND, quarantined_page_sweeper_, v8::internal::LargeObjectSpace::ResetPendingObject(), Scavenger, v8::internal::Heap::ShouldUsePrecisePinningForMinorGC(), v8::internal::MutablePageMetadata::slot_set(), surviving_new_large_objects_, v8::internal::SemiSpaceNewSpace::SwapSemiSpaces(), TRACE_GC, v8::internal::Isolate::traced_handles(), v8::internal::Heap::tracer(), v8::internal::MutablePageMetadata::typed_slot_set(), v8::internal::v8_flags, and V8_UNLIKELY.
CompleteSweepingQuarantinedPagesIfNeeded()
void v8::internal::ScavengerCollector::CompleteSweepingQuarantinedPagesIfNeeded ()
Definition at line 1097 of file scavenger.cc.
                                                                  {
  if (!quarantined_page_sweeper_.IsSweeping()) {
    return;
  }
  quarantined_page_sweeper_.FinishSweeping();
  heap_->tracer()->NotifyYoungSweepingCompletedAndStopCycleIfFinished();
}
References v8::internal::ScavengerCollector::QuarantinedPageSweeper::FinishSweeping(), heap_, v8::internal::ScavengerCollector::QuarantinedPageSweeper::IsSweeping(), v8::internal::GCTracer::NotifyYoungSweepingCompletedAndStopCycleIfFinished(), quarantined_page_sweeper_, and v8::internal::Heap::tracer().
FetchAndResetConcurrencyEstimate()
size_t v8::internal::ScavengerCollector::FetchAndResetConcurrencyEstimate () [inline], [private]
Definition at line 370 of file scavenger.h.
                                            {
    const size_t estimate =
        estimate_concurrency_.exchange(0, std::memory_order_relaxed);
    return estimate == 0 ? 1 : estimate;
  }
References estimate_concurrency_.
HandleSurvivingNewLargeObjects()
void v8::internal::ScavengerCollector::HandleSurvivingNewLargeObjects () [private]
Definition at line 1068 of file scavenger.cc.
                                                        {
  DCHECK(!heap_->incremental_marking()->IsMarking());
  for (SurvivingNewLargeObjectMapEntry update_info :
       surviving_new_large_objects_) {
    Tagged<HeapObject> object = update_info.first;
    Tagged<Map> map = update_info.second;
    // Order is important here. We have to re-install the map to have access
    // to meta-data like size during page promotion.
    object->set_map_word(map, kRelaxedStore);
    LargePageMetadata* page = LargePageMetadata::FromHeapObject(object);
    SBXCHECK(page->IsLargePage());
    SBXCHECK_EQ(page->owner_identity(), NEW_LO_SPACE);
    heap_->lo_space()->PromoteNewLargeObject(page);
  }
  surviving_new_large_objects_.clear();
  heap_->new_lo_space()->set_objects_size(0);
}
References v8::internal::DCHECK(), v8::internal::LargePageMetadata::FromHeapObject(), heap_, v8::internal::Heap::incremental_marking(), v8::internal::MutablePageMetadata::IsLargePage(), v8::internal::IncrementalMarking::IsMarking(), v8::kRelaxedStore, v8::internal::Heap::lo_space(), v8::internal::NEW_LO_SPACE, v8::internal::Heap::new_lo_space(), v8::internal::MutablePageMetadata::owner_identity(), v8::internal::OldLargeObjectSpace::PromoteNewLargeObject(), SBXCHECK, SBXCHECK_EQ, v8::internal::LargeObjectSpace::set_objects_size(), and surviving_new_large_objects_.
MergeSurvivingNewLargeObjects()
void v8::internal::ScavengerCollector::MergeSurvivingNewLargeObjects (const SurvivingNewLargeObjectsMap & objects) [private]
Definition at line 1088 of file scavenger.cc.
                                                {
  for (SurvivingNewLargeObjectMapEntry object : objects) {
    bool success = surviving_new_large_objects_.insert(object).second;
    USE(success);
    DCHECK(success);
  }
}
References v8::internal::DCHECK(), surviving_new_large_objects_, and USE.
NumberOfScavengeTasks()
int v8::internal::ScavengerCollector::NumberOfScavengeTasks () [private]
Definition at line 1105 of file scavenger.cc.
                                              {
  if (!v8_flags.parallel_scavenge) {
    return 1;
  }
  const int num_scavenge_tasks =
      static_cast<int>(
          SemiSpaceNewSpace::From(heap_->new_space())->TotalCapacity()) /
          MB +
      1;
  static int num_cores = V8::GetCurrentPlatform()->NumberOfWorkerThreads() + 1;
  int tasks = std::max(
      1, std::min({num_scavenge_tasks, kMaxScavengerTasks, num_cores}));
  if (!heap_->CanPromoteYoungAndExpandOldGeneration(
          static_cast<size_t>(tasks * PageMetadata::kPageSize))) {
    // Optimize for memory usage near the heap limit.
    tasks = 1;
  }
  return tasks;
}
References v8::internal::Heap::CanPromoteYoungAndExpandOldGeneration(), v8::internal::SemiSpaceNewSpace::From(), v8::internal::V8::GetCurrentPlatform(), heap_, kMaxScavengerTasks, v8::internal::MutablePageMetadata::kPageSize, v8::internal::MB, v8::internal::Heap::new_space(), v8::Platform::NumberOfWorkerThreads(), v8::internal::SemiSpaceNewSpace::TotalCapacity(), and v8::internal::v8_flags.
Referenced by CollectGarbage().
ProcessWeakReferences()
void v8::internal::ScavengerCollector::ProcessWeakReferences (EphemeronRememberedSet::TableList * ephemeron_table_list) [private]
Definition at line 1294 of file scavenger.cc.
                                                           {
  ClearYoungEphemerons(ephemeron_table_list);
  ClearOldEphemerons();
}
References ClearOldEphemerons(), and ClearYoungEphemerons().
SweepArrayBufferExtensions()
void v8::internal::ScavengerCollector::SweepArrayBufferExtensions () [private]
Definition at line 1059 of file scavenger.cc.
                                                    {
  DCHECK_EQ(0, heap_->new_lo_space()->Size());
  heap_->array_buffer_sweeper()->RequestSweep(
      ArrayBufferSweeper::SweepingType::kYoung,
      (heap_->new_space()->SizeOfObjects() == 0)
          ? ArrayBufferSweeper::TreatAllYoungAsPromoted::kYes
          : ArrayBufferSweeper::TreatAllYoungAsPromoted::kNo);
}
References v8::internal::Heap::array_buffer_sweeper(), DCHECK_EQ, heap_, v8::internal::ArrayBufferSweeper::kNo, v8::internal::ArrayBufferSweeper::kYes, v8::internal::ArrayBufferSweeper::kYoung, v8::internal::Heap::new_lo_space(), v8::internal::Heap::new_space(), v8::internal::ArrayBufferSweeper::RequestSweep(), and v8::internal::LargeObjectSpace::Size().
Friends And Related Function Documentation
Scavenger
friend class Scavenger [friend]
Definition at line 382 of file scavenger.h.
Referenced by CollectGarbage().
Member Data Documentation
estimate_concurrency_
std::atomic<size_t> v8::internal::ScavengerCollector::estimate_concurrency_ {0} [private]
Definition at line 379 of file scavenger.h.
Referenced by FetchAndResetConcurrencyEstimate().
heap_
Heap* const v8::internal::ScavengerCollector::heap_ [private]
Definition at line 377 of file scavenger.h.
Referenced by CompleteSweepingQuarantinedPagesIfNeeded(), HandleSurvivingNewLargeObjects(), NumberOfScavengeTasks(), and SweepArrayBufferExtensions().
isolate_
Isolate* const v8::internal::ScavengerCollector::isolate_ [private]
Definition at line 376 of file scavenger.h.
Referenced by CollectGarbage().
kMainThreadId
const int v8::internal::ScavengerCollector::kMainThreadId = 0 [static]
Definition at line 244 of file scavenger.h.
Referenced by CollectGarbage().
kMaxScavengerTasks
const int v8::internal::ScavengerCollector::kMaxScavengerTasks = 8 [static]
Definition at line 243 of file scavenger.h.
Referenced by NumberOfScavengeTasks().
quarantined_page_sweeper_
QuarantinedPageSweeper v8::internal::ScavengerCollector::quarantined_page_sweeper_ [private]
Definition at line 380 of file scavenger.h.
Referenced by CollectGarbage(), and CompleteSweepingQuarantinedPagesIfNeeded().
surviving_new_large_objects_
SurvivingNewLargeObjectsMap v8::internal::ScavengerCollector::surviving_new_large_objects_ [private]
Definition at line 378 of file scavenger.h.
Referenced by CollectGarbage(), HandleSurvivingNewLargeObjects(), and MergeSurvivingNewLargeObjects().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/scavenger.h
/mnt/V8SourceCode/src/heap/scavenger.cc