v8::internal::LocalHeap::AtomicThreadState Class Reference
Public Member Functions
constexpr AtomicThreadState (ThreadState state)
bool CompareExchangeStrong (ThreadState &expected, ThreadState updated)
bool CompareExchangeWeak (ThreadState &expected, ThreadState updated)
ThreadState SetParked ()
ThreadState SetSafepointRequested ()
ThreadState ClearSafepointRequested ()
ThreadState SetCollectionRequested ()
ThreadState ClearCollectionRequested ()
ThreadState load_relaxed () const
Private Attributes
std::atomic< uint8_t > raw_state_
Detailed Description
Definition at line 292 of file local-heap.h.
Constructor & Destructor Documentation
AtomicThreadState()
constexpr v8::internal::LocalHeap::AtomicThreadState::AtomicThreadState (ThreadState state) [inline], [explicit], [constexpr]
Definition at line 294 of file local-heap.h.
        : raw_state_(state.raw()) {}
Member Function Documentation
ClearCollectionRequested()
ThreadState v8::internal::LocalHeap::AtomicThreadState::ClearCollectionRequested () [inline]
Definition at line 323 of file local-heap.h.
                                           {
      return ThreadState(raw_state_.fetch_and(~CollectionRequestedBit::kMask));
    }
Referenced by v8::internal::Heap::GarbageCollectionEpilogueInSafepoint().
ClearSafepointRequested()
ThreadState v8::internal::LocalHeap::AtomicThreadState::ClearSafepointRequested () [inline]
Definition at line 315 of file local-heap.h.
                                          {
      return ThreadState(raw_state_.fetch_and(~SafepointRequestedBit::kMask));
    }
CompareExchangeStrong()
bool v8::internal::LocalHeap::AtomicThreadState::CompareExchangeStrong (ThreadState & expected, ThreadState updated) [inline]
Definition at line 297 of file local-heap.h.
                                                                           {
      return raw_state_.compare_exchange_strong(expected.raw_state_,
                                                updated.raw());
    }
References v8::internal::LocalHeap::ThreadState::raw(), and v8::internal::LocalHeap::ThreadState::raw_state_.
Referenced by v8::internal::LocalHeap::ParkSlowPath(), and v8::internal::LocalHeap::UnparkSlowPath().
CompareExchangeWeak()
bool v8::internal::LocalHeap::AtomicThreadState::CompareExchangeWeak (ThreadState & expected, ThreadState updated) [inline]
Definition at line 302 of file local-heap.h.
                                                                         {
      return raw_state_.compare_exchange_weak(expected.raw_state_,
                                              updated.raw());
    }
References v8::internal::LocalHeap::ThreadState::raw(), and v8::internal::LocalHeap::ThreadState::raw_state_.
load_relaxed()
ThreadState v8::internal::LocalHeap::AtomicThreadState::load_relaxed () const [inline]
Definition at line 327 of file local-heap.h.
                                     {
      return ThreadState(raw_state_.load(std::memory_order_relaxed));
    }
Referenced by v8::internal::LocalHeap::IsParked(), v8::internal::LocalHeap::IsRunning(), and v8::internal::LocalHeap::SafepointSlowPath().
SetCollectionRequested()
ThreadState v8::internal::LocalHeap::AtomicThreadState::SetCollectionRequested () [inline]
Definition at line 319 of file local-heap.h.
                                         {
      return ThreadState(raw_state_.fetch_or(CollectionRequestedBit::kMask));
    }
Referenced by v8::internal::Heap::CollectGarbageFromAnyThread().
SetParked()
ThreadState v8::internal::LocalHeap::AtomicThreadState::SetParked () [inline]
Definition at line 307 of file local-heap.h.
                            {
      return ThreadState(raw_state_.fetch_or(ParkedBit::kMask));
    }
Referenced by v8::internal::LocalHeap::ParkSlowPath(), and v8::internal::LocalHeap::SleepInSafepoint().
SetSafepointRequested()
ThreadState v8::internal::LocalHeap::AtomicThreadState::SetSafepointRequested () [inline]
Definition at line 311 of file local-heap.h.
                                        {
      return ThreadState(raw_state_.fetch_or(SafepointRequestedBit::kMask));
    }
Member Data Documentation
raw_state_
std::atomic<uint8_t> v8::internal::LocalHeap::AtomicThreadState::raw_state_ [private]
Definition at line 332 of file local-heap.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/local-heap.h