v8::internal::BaseTimedHistogramScope Class Reference
#include <counters-scopes.h>
Protected Member Functions
BaseTimedHistogramScope (TimedHistogram *histogram)
void StartInternal ()
base::TimeDelta StopInternal ()
void Start ()
base::TimeDelta Stop ()
void LogStart (Isolate *isolate)
void LogEnd (Isolate *isolate)
Protected Attributes
base::ElapsedTimer timer_
TimedHistogram * histogram_
Detailed Description
Definition at line 15 of file counters-scopes.h.
Constructor & Destructor Documentation
BaseTimedHistogramScope()
v8::internal::BaseTimedHistogramScope::BaseTimedHistogramScope (TimedHistogram * histogram) [inline], [explicit], [protected]
Definition at line 17 of file counters-scopes.h.
      : histogram_(histogram) {}
Member Function Documentation
LogEnd()
void v8::internal::BaseTimedHistogramScope::LogEnd (Isolate * isolate) [inline], [protected]
Definition at line 51 of file counters-scopes.h.
                                          {
    V8FileLogger::CallEventLogger(isolate, histogram_->name(),
                                  v8::LogEventStatus::kEnd, true);
  }
References v8::internal::V8FileLogger::CallEventLogger(), histogram_, v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, and v8::internal::Histogram::name().
LogStart()
void v8::internal::BaseTimedHistogramScope::LogStart (Isolate * isolate) [inline], [protected]
Definition at line 46 of file counters-scopes.h.
                                            {
    V8FileLogger::CallEventLogger(isolate, histogram_->name(),
                                  v8::LogEventStatus::kStart, true);
  }
References v8::internal::V8FileLogger::CallEventLogger(), histogram_, v8::kStart, and v8::internal::Histogram::name().
Start()
void v8::internal::BaseTimedHistogramScope::Start () [inline], [protected]
Definition at line 33 of file counters-scopes.h.
                         {
    if (histogram_->Enabled()) StartInternal();
  }
References v8::internal::Histogram::Enabled(), histogram_, and StartInternal().
Referenced by v8::internal::LazyTimedHistogramScope::LazyTimedHistogramScope().
StartInternal()
void v8::internal::BaseTimedHistogramScope::StartInternal () [inline], [protected]
Definition at line 20 of file counters-scopes.h.
                       {
    DCHECK(histogram_->ToggleRunningState(true));
    timer_.Start();
  }
References v8::internal::DCHECK(), histogram_, v8::base::ElapsedTimer::Start(), and timer_.
Referenced by Start().
Stop()
base::TimeDelta v8::internal::BaseTimedHistogramScope::Stop () [inline], [protected]
Definition at line 41 of file counters-scopes.h.
                                 {
    if (histogram_->Enabled()) return StopInternal();
    return base::TimeDelta::FromMicroseconds(-1);
  }
References v8::internal::Histogram::Enabled(), v8::base::TimeDelta::FromMicroseconds(), histogram_, and StopInternal().
StopInternal()
base::TimeDelta v8::internal::BaseTimedHistogramScope::StopInternal () [inline], [protected]
Definition at line 25 of file counters-scopes.h.
                               {
    DCHECK(histogram_->ToggleRunningState(false));
    base::TimeDelta elapsed = timer_.Elapsed();
    histogram_->AddTimedSample(elapsed);
    timer_.Stop();
    return elapsed;
  }
References v8::internal::TimedHistogram::AddTimedSample(), v8::internal::DCHECK(), v8::base::ElapsedTimer::Elapsed(), histogram_, v8::base::ElapsedTimer::Stop(), and timer_.
Referenced by Stop().
Member Data Documentation
histogram_
TimedHistogram* v8::internal::BaseTimedHistogramScope::histogram_ [protected]
Definition at line 57 of file counters-scopes.h.
Referenced by LogEnd(), LogStart(), Start(), StartInternal(), Stop(), and StopInternal().
timer_
base::ElapsedTimer v8::internal::BaseTimedHistogramScope::timer_ [protected]
Definition at line 56 of file counters-scopes.h.
Referenced by StartInternal(), and StopInternal().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/logging/counters-scopes.h