v8::debug::AsyncEventDelegate Class Reference
#include <debug-interface.h>
Public Member Functions
virtual ~AsyncEventDelegate ()=default
virtual void AsyncEventOccurred (debug::DebugAsyncActionType type, int id, bool is_blackboxed)=0
Detailed Description
Definition at line 352 of file debug-interface.h.
Constructor & Destructor Documentation
 AsyncEventDelegate()
virtual v8::debug::AsyncEventDelegate::~AsyncEventDelegate () [virtual], [default]
Member Function Documentation
AsyncEventOccurred()
virtual void v8::debug::AsyncEventDelegate::AsyncEventOccurred (debug::DebugAsyncActionType type, int id, bool is_blackboxed) [pure virtual]
Implemented in v8_inspector::V8Debugger.
Referenced by v8::internal::Isolate::OnAsyncFunctionSuspended(), v8::internal::Isolate::OnPromiseAfter(), v8::internal::Isolate::OnPromiseBefore(), v8::internal::Isolate::OnPromiseThen(), and v8::internal::Isolate::OnStackTraceCaptured().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/debug-interface.h