v8::internal::ClearStaleLeftTrimmedPointerVisitor Class Reference
#include <heap.h>
Public Member Functions
ClearStaleLeftTrimmedPointerVisitor (Heap *heap, RootVisitor *visitor)
void VisitRootPointer (Root root, const char *description, FullObjectSlot p) override
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) override
void VisitRunningCode (FullObjectSlot code_slot, FullObjectSlot istream_or_smi_zero_slot) override
void Synchronize (VisitorSynchronization::SyncTag tag) override
PtrComprCageBase cage_base () const
Private Member Functions
void ClearLeftTrimmedOrForward (Root root, const char *description, FullObjectSlot p)
bool IsLeftTrimmed (FullObjectSlot p)
Private Attributes
Heap * heap_
RootVisitor * visitor_
Additional Inherited Members
Detailed Description
Definition at line 2799 of file heap.h.
Constructor & Destructor Documentation
ClearStaleLeftTrimmedPointerVisitor()
v8::internal::ClearStaleLeftTrimmedPointerVisitor::ClearStaleLeftTrimmedPointerVisitor (Heap * heap, RootVisitor * visitor)
Definition at line 4774 of file heap.cc.
    : heap_(heap),
      visitor_(visitor)
#if V8_COMPRESS_POINTERS
      ,
      cage_base_(heap->isolate())
#endif // V8_COMPRESS_POINTERS
{
  USE(heap_);
}
References heap_, and USE.
Member Function Documentation
cage_base()
PtrComprCageBase v8::internal::ClearStaleLeftTrimmedPointerVisitor::cage_base () const [inline]
Definition at line 2818 of file heap.h.
                                     {
#if V8_COMPRESS_POINTERS
    return cage_base_;
#else
    return PtrComprCageBase{};
#endif // V8_COMPRESS_POINTERS
  }
ClearLeftTrimmedOrForward()
void v8::internal::ClearStaleLeftTrimmedPointerVisitor::ClearLeftTrimmedOrForward (Root root, const char * description, FullObjectSlot p) [inline], [private]
Definition at line 4731 of file heap.cc.
                                                          {
  if (!IsHeapObject(*p)) return;
  if (IsLeftTrimmed(p)) {
    p.store(Smi::zero());
  } else {
    visitor_->VisitRootPointer(root, description, p);
  }
}
References v8::internal::IsHeapObject(), v8::internal::FullObjectSlot::store(), and v8::internal::Smi::zero().
Referenced by VisitRootPointer(), and VisitRootPointers().
IsLeftTrimmed()
bool v8::internal::ClearStaleLeftTrimmedPointerVisitor::IsLeftTrimmed (FullObjectSlot p) [inline], [private]
Definition at line 4742 of file heap.cc.
                                                                        {
  if (!IsHeapObject(*p)) return false;
  Tagged<HeapObject> current = Cast<HeapObject>(*p);
  if (!current->map_word(cage_base(), kRelaxedLoad).IsForwardingAddress() &&
      IsFreeSpaceOrFiller(current, cage_base())) {
#ifdef DEBUG
      // We need to find a FixedArrayBase map after walking the fillers.
      while (
          !current->map_word(cage_base(), kRelaxedLoad).IsForwardingAddress() &&
          IsFreeSpaceOrFiller(current, cage_base())) {
        Address next = current.ptr();
        if (current->map(cage_base()) ==
            ReadOnlyRoots(heap_).one_pointer_filler_map()) {
          next += kTaggedSize;
        } else if (current->map(cage_base()) ==
                   ReadOnlyRoots(heap_).two_pointer_filler_map()) {
          next += 2 * kTaggedSize;
        } else {
          next += current->Size();
        }
        current = Cast<HeapObject>(Tagged<Object>(next));
      }
      DCHECK(
          current->map_word(cage_base(), kRelaxedLoad).IsForwardingAddress() ||
          IsFixedArrayBase(current, cage_base()));
#endif // DEBUG
      return true;
  } else {
    return false;
  }
}
References v8::internal::DCHECK(), v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller(), v8::internal::IsHeapObject(), v8::kRelaxedLoad, v8::internal::kTaggedSize, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::Heap::ReadOnlyRoots.
Referenced by VisitRunningCode().
Synchronize()
void v8::internal::ClearStaleLeftTrimmedPointerVisitor::Synchronize (VisitorSynchronization::SyncTag tag) [inline], [override], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 2812 of file heap.h.
                                                               {
    visitor_->Synchronize(tag);
  }
VisitRootPointer()
void v8::internal::ClearStaleLeftTrimmedPointerVisitor::VisitRootPointer (Root root, const char * description, FullObjectSlot p) [override], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 4786 of file heap.cc.
                                                          {
  ClearLeftTrimmedOrForward(root, description, p);
}
References ClearLeftTrimmedOrForward().
VisitRootPointers()
void v8::internal::ClearStaleLeftTrimmedPointerVisitor::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [override], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 4791 of file heap.cc.
                        {
  for (FullObjectSlot p = start; p < end; ++p) {
    ClearLeftTrimmedOrForward(root, description, p);
  }
}
References ClearLeftTrimmedOrForward(), and v8::internal::compiler::end().
VisitRunningCode()
void v8::internal::ClearStaleLeftTrimmedPointerVisitor::VisitRunningCode (FullObjectSlot code_slot, FullObjectSlot istream_or_smi_zero_slot) [override], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 4799 of file heap.cc.
                                                                       {
  // Directly forward to actual visitor here. Code objects and instruction
  // stream will not be left-trimmed.
  DCHECK(!IsLeftTrimmed(code_slot));
  DCHECK(!IsLeftTrimmed(istream_or_smi_zero_slot));
  visitor_->VisitRunningCode(code_slot, istream_or_smi_zero_slot);
}
References v8::internal::DCHECK(), IsLeftTrimmed(), visitor_, and v8::internal::RootVisitor::VisitRunningCode().
Member Data Documentation
heap_
Heap* v8::internal::ClearStaleLeftTrimmedPointerVisitor::heap_ [private]
Definition at line 2831 of file heap.h.
Referenced by ClearStaleLeftTrimmedPointerVisitor().
visitor_
RootVisitor* v8::internal::ClearStaleLeftTrimmedPointerVisitor::visitor_ [private]
Definition at line 2832 of file heap.h.
Referenced by VisitRunningCode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap.h
/mnt/V8SourceCode/src/heap/heap.cc