v8::internal::compiler::ContextCellRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< ContextCell > object () const
ContextCell::State state () const
OptionalObjectRef tagged_value (JSHeapBroker *broker) const
Detailed Description
Definition at line 723 of file heap-refs.h.
Member Function Documentation
object()
IndirectHandle<ContextCell> v8::internal::compiler::ContextCellRef::object () const
state()
ContextCell::State v8::internal::compiler::ContextCellRef::state () const
Referenced by v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeLoadContextSlot(), and v8::internal::maglev::MaglevGraphBuilder::TrySpecializeStoreContextSlot().
tagged_value()
OptionalObjectRef v8::internal::compiler::ContextCellRef::tagged_value (JSHeapBroker * broker) const
Definition at line 1609 of file heap-refs.cc.
                                                                         {
  return TryMakeRef(broker, object()->tagged_value());
}
References broker(), and v8::internal::compiler::TryMakeRef().
Referenced by v8::internal::compiler::JSContextSpecialization::ReduceJSLoadContext(), v8::internal::compiler::JSContextSpecialization::ReduceJSStoreContext(), v8::internal::maglev::MaglevGraphBuilder::TrySpecializeLoadContextSlot(), and v8::internal::maglev::MaglevGraphBuilder::TrySpecializeStoreContextSlot().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc