v8::internal::anonymous_namespace{liveedit.cc}::CollectFunctionLiterals Class Reference
Public Member Functions
CollectFunctionLiterals (Isolate *isolate, AstNode *root)
void VisitFunctionLiteral (FunctionLiteral *lit)
void VisitCall (Call *call)
void Run (std::vector< FunctionLiteral * > *literals, std::map< uint32_t, std::vector< uint32_t >> *eval_calls)
Private Attributes
uint32_t function_literal_id_ = 0
std::vector< FunctionLiteral * > * literals_
std::map< uint32_t, std::vector< uint32_t > > * eval_calls_
Additional Inherited Members
Detailed Description
Definition at line 497 of file liveedit.cc.
Constructor & Destructor Documentation
CollectFunctionLiterals()
v8::internal::anonymous_namespace{liveedit.cc}::CollectFunctionLiterals::CollectFunctionLiterals (Isolate * isolate, AstNode * root) [inline]
Definition at line 500 of file liveedit.cc.
      : AstTraversalVisitor<CollectFunctionLiterals>(isolate, root) {}
Member Function Documentation
Run()
void v8::internal::anonymous_namespace{liveedit.cc}::CollectFunctionLiterals::Run (std::vector< FunctionLiteral * > * literals, std::map< uint32_t, std::vector< uint32_t >> * eval_calls) [inline]
Definition at line 516 of file liveedit.cc.
                                                              {
    literals_ = literals;
    eval_calls_ = eval_calls;
    AstTraversalVisitor::Run();
    literals_ = nullptr;
    eval_calls_ = nullptr;
  }
References v8::internal::AstTraversalVisitor< Subclass >::Run().
Referenced by v8::internal::anonymous_namespace{liveedit.cc}::ParseScript().
VisitCall()
void v8::internal::anonymous_namespace{liveedit.cc}::CollectFunctionLiterals::VisitCall (Call * call) [inline]
Definition at line 509 of file liveedit.cc.
                             {
    AstTraversalVisitor::VisitCall(call);
    if (call->is_possibly_eval()) {
      (*eval_calls_)[function_literal_id_].push_back(
          call->eval_scope_info_index());
    }
  }
References v8::internal::Call::eval_scope_info_index(), and v8::internal::Call::is_possibly_eval().
VisitFunctionLiteral()
void v8::internal::anonymous_namespace{liveedit.cc}::CollectFunctionLiterals::VisitFunctionLiteral (FunctionLiteral * lit) [inline]
Definition at line 502 of file liveedit.cc.
                                                  {
    uint32_t parent_id = function_literal_id_;
    function_literal_id_ = lit->function_literal_id();
    AstTraversalVisitor::VisitFunctionLiteral(lit);
    literals_->push_back(lit);
    function_literal_id_ = parent_id;
  }
References v8::internal::FunctionLiteral::function_literal_id().
Member Data Documentation
eval_calls_
std::map<uint32_t, std::vector<uint32_t> >* v8::internal::anonymous_namespace{liveedit.cc}::CollectFunctionLiterals::eval_calls_ [private]
Definition at line 528 of file liveedit.cc.
function_literal_id_
uint32_t v8::internal::anonymous_namespace{liveedit.cc}::CollectFunctionLiterals::function_literal_id_ = 0 [private]
Definition at line 526 of file liveedit.cc.
literals_
std::vector<FunctionLiteral*>* v8::internal::anonymous_namespace{liveedit.cc}::CollectFunctionLiterals::literals_ [private]
Definition at line 527 of file liveedit.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/liveedit.cc