v8::Persistent< T, M > Class Template Reference
A PersistentBase which allows copy and assignment.
#include <v8-persistent-handle.h>
Public Member Functions
Persistent ()=default
A Persistent with no storage cell.
template<class S >
requires (std::is_base_of_v< T, S >) inline Persistent(Isolate *isolate
Construct a Persistent from a Local with automatic up casting.
Local< S > that template value ()))
template<class S , class M2 >
requires (std::is_base_of_v< T, S >) inline Persistent(Isolate *isolate
Construct a Persistent from a Persistent with automatic up casting.
const Persistent< S, M2 > that template value ()))
Persistent (const Persistent &that)
The copy constructors and assignment operator create a Persistent exactly as the Persistent constructor, but the Copy function from the traits class is called, allowing the setting of flags based on the copied Persistent.
template<class S , class M2 >
Persistent (const Persistent< S, M2 > &that)
Persistent & operator= (const Persistent &that)
template<class S , class M2 >
Persistent & operator= (const Persistent< S, M2 > &that)
~Persistent ()
The destructor will dispose the Persistent based on the kResetInDestructor flags in the traits class.
template<class S , class M2 >
Persistent< S, M2 > & As () const
Static Public Member Functions
template<class S , class M2 >
static Persistent< T, M > & Cast (const Persistent< S, M2 > &that)
Public Attributes
Local< S > that: PersistentBase<T>(PersistentBase<T>::New(isolate
const Persistent< S, M2 > & that: PersistentBase<T>(PersistentBase<T>::New(isolate
Private Member Functions
template<class S , class M2 >
void Copy (const Persistent< S, M2 > &that)
Friends
class Isolate
class Utils
template<class F >
class Local
template<class F1 , class F2 >
class Persistent
Persistent is a way to create a strong pointer from an off-heap object to another on-heap object.
template<class F >
class ReturnValue
Additional Inherited Members
Detailed Description
template<class T, class M>
class v8::Persistent< T, M >
A PersistentBase which allows copy and assignment.
Copy, assignment and destructor behavior is controlled by the traits class M.
CAVEAT: Persistent objects do not have proper destruction behavior by default and as such will leak the object without explicit clear. Consider using v8::Global instead which has proper destruction and move semantics.
Definition at line 250 of file v8-persistent-handle.h.
Constructor & Destructor Documentation
Persistent() [1/3]
template<class T , class M >
v8::Persistent< T, M >::Persistent () [inline], [default]
A Persistent with no storage cell.
Persistent() [2/3]
template<class T , class M >
v8::Persistent< T, M >::Persistent (const Persistent< T, M > & that) [inline]
The copy constructors and assignment operator create a Persistent exactly as the Persistent constructor, but the Copy function from the traits class is called, allowing the setting of flags based on the copied Persistent.
Definition at line 285 of file v8-persistent-handle.h.
                                               : PersistentBase<T>() {
    Copy(that);
  }
References v8::Persistent< T, M >::Copy(), and v8::Persistent< T, M >::that.
Persistent() [3/3]
template<class T , class M >
template<class S , class M2 >
v8::Persistent< T, M >::Persistent (const Persistent< S, M2 > & that) [inline]
Definition at line 289 of file v8-persistent-handle.h.
                                                      : PersistentBase<T>() {
    Copy(that);
  }
References v8::Persistent< T, M >::Copy(), and v8::Persistent< T, M >::that.
 Persistent()
template<class T , class M >
v8::Persistent< T, M >::~Persistent () [inline]
The destructor will dispose the Persistent based on the kResetInDestructor flags in the traits class.
Since not calling dispose can result in a memory leak, it is recommended to always set this flag.
Definition at line 307 of file v8-persistent-handle.h.
                          {
    if (M::kResetInDestructor) this->Reset();
  }
References v8::PersistentBase< T >::Reset().
Member Function Documentation
As()
template<class T , class M >
template<class S , class M2 >
Persistent<S, M2>& v8::Persistent< T, M >::As () const [inline]
Definition at line 325 of file v8-persistent-handle.h.
                                          {
    return Persistent<S, M2>::Cast(*this);
  }
References v8::Persistent< T, M >::Cast().
Cast()
template<class T , class M >
template<class S , class M2 >
static Persistent<T, M>& v8::Persistent< T, M >::Cast (const Persistent< S, M2 > & that) [inline], [static]
Definition at line 313 of file v8-persistent-handle.h.
                                                                         {
#ifdef V8_ENABLE_CHECKS
    // If we're going to perform the type check then we have to check
    // that the handle isn't empty before doing the checked cast.
    if (!that.IsEmpty()) T::Cast(that.template value<S>());
#endif
    return reinterpret_cast<Persistent<T, M>&>(
        const_cast<Persistent<S, M2>&>(that));
  }
References v8::internal::Cast(), v8::api_internal::IndirectHandleBase::IsEmpty(), and v8::Persistent< T, M >::that.
Referenced by v8::Persistent< T, M >::As().
Copy()
template<class T , class M >
template<class S , class M2 >
void v8::Persistent< T, M >::Copy (const Persistent< S, M2 > & that) [inline], [private]
Definition at line 433 of file v8-persistent-handle.h.
                                                         {
  static_assert(std::is_base_of_v<T, S>, "type check");
  this->Reset();
  if (that.IsEmpty()) return;
  this->slot() = api_internal::CopyGlobalReference(that.slot());
  M::Copy(that, this);
}
References v8::bigint::anonymous_namespace{div-helpers.cc}::Copy(), v8::api_internal::CopyGlobalReference(), v8::api_internal::IndirectHandleBase::IsEmpty(), and v8::api_internal::IndirectHandleBase::slot().
Referenced by v8::Persistent< T, M >::operator=(), and v8::Persistent< T, M >::Persistent().
operator=() [1/2]
template<class T , class M >
Persistent& v8::Persistent< T, M >::operator= (const Persistent< T, M > & that) [inline]
Definition at line 292 of file v8-persistent-handle.h.
                                                          {
    Copy(that);
    return *this;
  }
References v8::Persistent< T, M >::Copy(), and v8::Persistent< T, M >::that.
operator=() [2/2]
template<class T , class M >
template<class S , class M2 >
Persistent& v8::Persistent< T, M >::operator= (const Persistent< S, M2 > & that) [inline]
Definition at line 297 of file v8-persistent-handle.h.
                                                                 {
    Copy(that);
    return *this;
  }
References v8::Persistent< T, M >::Copy(), and v8::Persistent< T, M >::that.
requires() [1/2]
template<class T , class M >
template<class S >
v8::Persistent< T, M >::requires (std::is_base_of_v< T, S >)
Construct a Persistent from a Local with automatic up casting.
When the Local is non-empty, a new storage cell is created pointing to the same object, and no flags are set.
requires() [2/2]
template<class T , class M >
template<class S , class M2 >
v8::Persistent< T, M >::requires (std::is_base_of_v< T, S >)
Construct a Persistent from a Persistent with automatic up casting.
When the Persistent is non-empty, a new storage cell is created pointing to the same object, and no flags are set.
value() [1/2]
template<class T , class M >
Local<S> that template v8::Persistent< T, M >::value () [inline]
Definition at line 266 of file v8-persistent-handle.h.
{}
value() [2/2]
template<class T , class M >
const Persistent<S, M2> that template v8::Persistent< T, M >::value () [inline]
Definition at line 277 of file v8-persistent-handle.h.
{}
Friends And Related Function Documentation
Isolate
template<class T , class M >
friend class Isolate [friend]
Definition at line 330 of file v8-persistent-handle.h.
Local
template<class T , class M >
template<class F >
friend class Local [friend]
Definition at line 333 of file v8-persistent-handle.h.
Persistent
template<class T , class M >
template<class F1 , class F2 >
friend class Persistent [friend]
Persistent is a way to create a strong pointer from an off-heap object to another on-heap object.
As long as the Persistent handle is alive the GC will keep the object pointed to alive. The Persistent handle is always a GC root from the point of view of the GC. Persistent must be constructed and destructed in the same thread.
Definition at line 335 of file v8-persistent-handle.h.
ReturnValue
template<class T , class M >
template<class F >
friend class ReturnValue [friend]
Definition at line 337 of file v8-persistent-handle.h.
Utils
template<class T , class M >
friend class Utils [friend]
Definition at line 331 of file v8-persistent-handle.h.
Member Data Documentation
that [1/2]
template<class T , class M >
Local<S> v8::Persistent< T, M >::that
Definition at line 264 of file v8-persistent-handle.h.
Referenced by v8::Persistent< T, M >::Cast(), v8::Persistent< T, M >::operator=(), and v8::Persistent< T, M >::Persistent().
that [2/2]
template<class T , class M >
const Persistent<S, M2>& v8::Persistent< T, M >::that
Definition at line 275 of file v8-persistent-handle.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-local-handle.h
/mnt/V8SourceCode/include/v8-persistent-handle.h