v8::internal::Trace Class Reference
#include <regexp-compiler.h>
Classes
class ConstIterator
Public Types
enum TriBool { UNKNOWN = -1
, FALSE_VALUE = 0
, TRUE_VALUE = 1
 }
enum FlushMode { kFlushFull
, kFlushSuccess
 }
Public Member Functions
Trace ()
Trace (const Trace &other) V8_NOEXCEPT
void Flush (RegExpCompiler *compiler, RegExpNode *successor, FlushMode mode=kFlushFull)
int cp_offset () const
bool has_any_actions () const
bool has_action () const
ActionNode * action () const
bool is_trivial () const
TriBool at_start () const
void set_at_start (TriBool at_start)
Label * backtrack () const
FixedLengthLoopState * fixed_length_loop_state () const
int characters_preloaded () const
int bound_checked_up_to () const
int flush_budget () const
QuickCheckDetails * quick_check_performed ()
bool mentions_reg (int reg) const
bool GetStoredPosition (int reg, int *cp_offset) const
void add_action (ActionNode *new_action)
void set_backtrack (Label *backtrack)
void set_fixed_length_loop_state (FixedLengthLoopState *state)
void set_characters_preloaded (int count)
void set_bound_checked_up_to (int to)
void set_flush_budget (int to)
void set_quick_check_performed (QuickCheckDetails *d)
void InvalidateCurrentCharacter ()
void AdvanceCurrentPositionInTrace (int by, RegExpCompiler *compiler)
const Trace * next () const
ConstIterator begin () const
ConstIterator end () const
Private Member Functions
int FindAffectedRegisters (DynamicBitSet *affected_registers, Zone *zone)
void PerformDeferredActions (RegExpMacroAssembler *macro, int max_register, const DynamicBitSet &affected_registers, DynamicBitSet *registers_to_pop, DynamicBitSet *registers_to_clear, Zone *zone)
void RestoreAffectedRegisters (RegExpMacroAssembler *macro, int max_register, const DynamicBitSet &registers_to_pop, const DynamicBitSet &registers_to_clear)
Private Attributes
int cp_offset_
uint16_t flush_budget_
TriBool at_start_: 8
bool has_any_actions_: 8
ActionNode * action_
Label * backtrack_
FixedLengthLoopState * fixed_length_loop_state_
int characters_preloaded_
int bound_checked_up_to_
QuickCheckDetails quick_check_performed_
const Trace * next_
Detailed Description
Definition at line 237 of file regexp-compiler.h.
Member Enumeration Documentation
FlushMode
enum v8::internal::Trace::FlushMode
Enumerator
kFlushFull
kFlushSuccess
Definition at line 272 of file regexp-compiler.h.
                 {
    // Normal flush of the deferred actions, generates code for backtracking.
    kFlushFull,
    // Matching has succeeded, so current position and backtrack stack will be
    // ignored and need not be written.
    kFlushSuccess
  };
TriBool
enum v8::internal::Trace::TriBool
Enumerator
UNKNOWN
FALSE_VALUE
TRUE_VALUE
Definition at line 241 of file regexp-compiler.h.
{ UNKNOWN = -1, FALSE_VALUE = 0, TRUE_VALUE = 1 };
Constructor & Destructor Documentation
Trace() [1/2]
v8::internal::Trace::Trace () [inline]
Definition at line 243 of file regexp-compiler.h.
      : cp_offset_(0),
        flush_budget_(100), // Note: this is a 16 bit field.
        at_start_(UNKNOWN),
        has_any_actions_(false),
        action_(nullptr),
        backtrack_(nullptr),
        fixed_length_loop_state_(nullptr),
        characters_preloaded_(0),
        bound_checked_up_to_(0),
        next_(nullptr) {}
Trace() [2/2]
v8::internal::Trace::Trace (const Trace & other) [inline]
Definition at line 255 of file regexp-compiler.h.
      : cp_offset_(other.cp_offset_),
        flush_budget_(other.flush_budget_),
        at_start_(other.at_start_),
        has_any_actions_(other.has_any_actions_),
        action_(nullptr),
        backtrack_(other.backtrack_),
        fixed_length_loop_state_(other.fixed_length_loop_state_),
        characters_preloaded_(other.characters_preloaded_),
        bound_checked_up_to_(other.bound_checked_up_to_),
        quick_check_performed_(other.quick_check_performed_),
        next_(&other) {}
Member Function Documentation
action()
ActionNode* v8::internal::Trace::action () const [inline]
Definition at line 286 of file regexp-compiler.h.
{ return action_; }
References action_.
Referenced by FindAffectedRegisters(), and PerformDeferredActions().
add_action()
void v8::internal::Trace::add_action (ActionNode * new_action) [inline]
Definition at line 319 of file regexp-compiler.h.
                                          {
    DCHECK(action_ == nullptr); // Otherwise we lose an action.
    action_ = new_action;
    has_any_actions_ = true;
  }
References action_, v8::internal::DCHECK(), and has_any_actions_.
Referenced by v8::internal::ActionNode::Emit().
AdvanceCurrentPositionInTrace()
void v8::internal::Trace::AdvanceCurrentPositionInTrace (int by, RegExpCompiler * compiler)
Definition at line 2604 of file regexp-compiler.cc.
                                                                          {
  // We don't have an instruction for shifting the current character register
  // down or for using a shifted value for anything so lets just forget that
  // we preloaded any characters into it.
  characters_preloaded_ = 0;
  // Adjust the offsets of the quick check performed information. This
  // information is used to find out what we already determined about the
  // characters by means of mask and compare.
  quick_check_performed_.Advance(by, compiler->one_byte());
  cp_offset_ += by;
  if (cp_offset_ > RegExpMacroAssembler::kMaxCPOffset) {
    compiler->SetRegExpTooBig();
    cp_offset_ = 0;
  }
  bound_checked_up_to_ = std::max(0, bound_checked_up_to_ - by);
}
References v8::internal::QuickCheckDetails::Advance(), bound_checked_up_to_, characters_preloaded_, cp_offset_, v8::internal::RegExpMacroAssembler::kMaxCPOffset, v8::internal::RegExpCompiler::one_byte(), quick_check_performed_, and v8::internal::RegExpCompiler::SetRegExpTooBig().
Referenced by v8::internal::TextNode::Emit().
at_start()
TriBool v8::internal::Trace::at_start () const [inline]
Definition at line 302 of file regexp-compiler.h.
{ return at_start_; }
References at_start_.
Referenced by v8::internal::AssertionNode::Emit(), v8::internal::AssertionNode::EmitBoundaryCheck(), v8::internal::RegExpNode::EmitQuickCheck(), set_at_start(), and v8::internal::ChoiceNode::SetUpPreLoad().
backtrack()
Label* v8::internal::Trace::backtrack () const [inline]
Definition at line 304 of file regexp-compiler.h.
{ return backtrack_; }
References backtrack_.
Referenced by v8::internal::AssertionNode::BacktrackIfPrevious(), v8::internal::ActionNode::Emit(), v8::internal::AssertionNode::Emit(), v8::internal::BackReferenceNode::Emit(), v8::internal::EndNode::Emit(), v8::internal::ChoiceNode::EmitChoices(), v8::internal::ChoiceNode::EmitFixedLengthLoop(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat(), v8::internal::RegExpNode::EmitQuickCheck(), Flush(), v8::internal::ChoiceNode::GenerateGuard(), set_backtrack(), and v8::internal::TextNode::TextEmitPass().
begin()
ConstIterator v8::internal::Trace::begin () const [inline]
Definition at line 360 of file regexp-compiler.h.
{ return ConstIterator(this); }
bound_checked_up_to()
int v8::internal::Trace::bound_checked_up_to () const [inline]
Definition at line 309 of file regexp-compiler.h.
{ return bound_checked_up_to_; }
References bound_checked_up_to_.
Referenced by v8::internal::TextNode::Emit().
characters_preloaded()
int v8::internal::Trace::characters_preloaded () const [inline]
Definition at line 308 of file regexp-compiler.h.
{ return characters_preloaded_; }
References characters_preloaded_.
Referenced by v8::internal::TextNode::Emit(), v8::internal::AssertionNode::EmitBoundaryCheck(), v8::internal::RegExpNode::EmitQuickCheck(), and v8::internal::ChoiceNode::SetUpPreLoad().
cp_offset()
int v8::internal::Trace::cp_offset () const [inline]
Definition at line 281 of file regexp-compiler.h.
{ return cp_offset_; }
References cp_offset_.
Referenced by v8::internal::AssertionNode::BacktrackIfPrevious(), v8::internal::ActionNode::Emit(), v8::internal::TextNode::Emit(), v8::internal::AssertionNode::Emit(), v8::internal::BackReferenceNode::Emit(), v8::internal::LoopChoiceNode::Emit(), v8::internal::AssertionNode::EmitBoundaryCheck(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat(), v8::internal::ChoiceNode::EmitOutOfLineContinuation(), v8::internal::RegExpNode::EmitQuickCheck(), GetStoredPosition(), and v8::internal::TextNode::TextEmitPass().
end()
ConstIterator v8::internal::Trace::end () const [inline]
Definition at line 361 of file regexp-compiler.h.
{ return ConstIterator(nullptr); }
FindAffectedRegisters()
int v8::internal::Trace::FindAffectedRegisters (DynamicBitSet * affected_registers, Zone * zone) [private]
Definition at line 353 of file regexp-compiler.cc.
                                             {
  int max_register = RegExpCompiler::kNoRegister;
  for (auto trace : *this) {
    if (ActionNode* action = trace->action_) {
      int to = action->register_to();
      for (int i = action->register_from(); i <= to; i++) {
        affected_registers->Set(i, zone);
      }
      if (to > max_register) max_register = to;
    }
  }
  return max_register;
}
References action(), v8::internal::RegExpCompiler::kNoRegister, v8::internal::ActionNode::register_from, v8::internal::ActionNode::register_to, and v8::internal::DynamicBitSet::Set().
Referenced by Flush().
fixed_length_loop_state()
FixedLengthLoopState* v8::internal::Trace::fixed_length_loop_state () const [inline]
Definition at line 305 of file regexp-compiler.h.
                                                        {
    return fixed_length_loop_state_;
  }
References fixed_length_loop_state_.
Referenced by v8::internal::LoopChoiceNode::Emit(), v8::internal::ChoiceNode::EmitFixedLengthLoop(), and v8::internal::RegExpNode::LimitVersions().
Flush()
void v8::internal::Trace::Flush (RegExpCompiler * compiler, RegExpNode * successor, Trace::FlushMode mode = kFlushFull)
Definition at line 516 of file regexp-compiler.cc.
                                       {
  RegExpMacroAssembler* assembler = compiler->macro_assembler();
  DCHECK(!is_trivial());
  // Normally we don't need to update the current position register if we are
  // about to stop because we had a successful match, but the global mode
  // requires the current position register to be updated so it can start the
  // next match. TODO(erikcorry): Perhaps it should use capture register 1
  // instead.
  bool update_current_position =
      cp_offset_ != 0 && (mode != kFlushSuccess || assembler->global());
  if (!has_any_actions() && (backtrack() == nullptr || mode == kFlushSuccess)) {
    // Here we just have some deferred cp advances to fix and we are back to
    // a normal situation. We may also have to forget some information gained
    // through a quick check that was already performed.
    if (update_current_position) assembler->AdvanceCurrentPosition(cp_offset_);
    // Create a new trivial state and generate the node with that.
    Trace new_state;
    successor->Emit(compiler, &new_state);
    return;
  }
  // Generate deferred actions here along with code to undo them again.
  DynamicBitSet affected_registers;
  if (backtrack() != nullptr && mode != kFlushSuccess) {
    // Here we have a concrete backtrack location. These are set up by choice
    // nodes and so they indicate that we have a deferred save of the current
    // position which we may need to emit here.
    assembler->PushCurrentPosition();
  }
  int max_register =
      FindAffectedRegisters(&affected_registers, compiler->zone());
  DynamicBitSet registers_to_pop;
  DynamicBitSet registers_to_clear;
  PerformDeferredActions(assembler, max_register, affected_registers,
                         &registers_to_pop, &registers_to_clear,
                         compiler->zone());
  if (update_current_position) assembler->AdvanceCurrentPosition(cp_offset_);
  if (mode == kFlushSuccess) {
    Trace new_state;
    successor->Emit(compiler, &new_state);
    return;
  }
  // Create a new trivial state and generate the node with that.
  Label undo;
  assembler->PushBacktrack(&undo);
  if (successor->KeepRecursing(compiler)) {
    Trace new_state;
    successor->Emit(compiler, &new_state);
  } else {
    compiler->AddWork(successor);
    assembler->GoTo(successor->label());
  }
  // On backtrack we need to restore state.
  assembler->BindJumpTarget(&undo);
  RestoreAffectedRegisters(assembler, max_register, registers_to_pop,
                           registers_to_clear);
  if (backtrack() == nullptr) {
    assembler->Backtrack();
  } else {
    assembler->PopCurrentPosition();
    assembler->GoTo(backtrack());
  }
}
References v8::internal::RegExpCompiler::AddWork(), v8::internal::RegExpMacroAssembler::AdvanceCurrentPosition(), backtrack(), v8::internal::RegExpMacroAssembler::Backtrack(), v8::internal::RegExpMacroAssembler::BindJumpTarget(), cp_offset_, v8::internal::DCHECK(), v8::internal::RegExpNode::Emit(), FindAffectedRegisters(), v8::internal::RegExpMacroAssembler::global(), v8::internal::RegExpMacroAssembler::GoTo(), has_any_actions(), is_trivial(), v8::internal::RegExpNode::KeepRecursing(), kFlushSuccess, v8::internal::RegExpNode::label(), v8::internal::RegExpCompiler::macro_assembler(), mode(), PerformDeferredActions(), v8::internal::RegExpMacroAssembler::PopCurrentPosition(), v8::internal::RegExpMacroAssembler::PushBacktrack(), v8::internal::RegExpMacroAssembler::PushCurrentPosition(), RestoreAffectedRegisters(), and v8::internal::RegExpCompiler::zone().
Referenced by v8::internal::ActionNode::Emit(), v8::internal::BackReferenceNode::Emit(), v8::internal::EndNode::Emit(), v8::internal::ChoiceNode::Emit(), v8::internal::LoopChoiceNode::Emit(), and v8::internal::RegExpNode::LimitVersions().
flush_budget()
int v8::internal::Trace::flush_budget () const [inline]
Definition at line 310 of file regexp-compiler.h.
{ return flush_budget_; }
References flush_budget_.
Referenced by v8::internal::ChoiceNode::Emit(), and v8::internal::ChoiceNode::EmitChoices().
GetStoredPosition()
bool v8::internal::Trace::GetStoredPosition (int reg, int * cp_offset) const
Definition at line 304 of file regexp-compiler.cc.
                                                           {
  DCHECK_EQ(0, *cp_offset);
  for (auto trace : *this) {
    if (trace->has_action() && trace->action()->Mentions(reg)) {
      if (trace->action_->action_type() == ActionNode::CLEAR_POSITION ||
          trace->action_->action_type() == ActionNode::RESTORE_POSITION) {
        *cp_offset = trace->next_->cp_offset();
        return true;
      } else {
        return false;
      }
    }
  }
  return false;
}
References v8::internal::ActionNode::CLEAR_POSITION, cp_offset(), DCHECK_EQ, and v8::internal::ActionNode::RESTORE_POSITION.
Referenced by v8::internal::ActionNode::Emit().
has_action()
bool v8::internal::Trace::has_action () const [inline]
Definition at line 285 of file regexp-compiler.h.
{ return action_ != nullptr; }
References action_.
has_any_actions()
bool v8::internal::Trace::has_any_actions () const [inline]
Definition at line 283 of file regexp-compiler.h.
{ return has_any_actions_; }
References has_any_actions_.
Referenced by v8::internal::ChoiceNode::Emit(), v8::internal::ChoiceNode::EmitChoices(), and Flush().
InvalidateCurrentCharacter()
void v8::internal::Trace::InvalidateCurrentCharacter ()
Definition at line 2602 of file regexp-compiler.cc.
{ characters_preloaded_ = 0; }
References characters_preloaded_.
Referenced by v8::internal::AssertionNode::BacktrackIfPrevious(), v8::internal::ChoiceNode::EmitChoices(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat().
is_trivial()
bool v8::internal::Trace::is_trivial () const [inline]
Definition at line 297 of file regexp-compiler.h.
                          {
    return backtrack_ == nullptr && !has_any_actions_ && cp_offset_ == 0 &&
           characters_preloaded_ == 0 && bound_checked_up_to_ == 0 &&
           quick_check_performed_.characters() == 0 && at_start_ == UNKNOWN;
  }
References at_start_, backtrack_, bound_checked_up_to_, v8::internal::QuickCheckDetails::characters(), characters_preloaded_, cp_offset_, has_any_actions_, quick_check_performed_, and UNKNOWN.
Referenced by v8::internal::ActionNode::Emit(), v8::internal::BackReferenceNode::Emit(), v8::internal::EndNode::Emit(), v8::internal::LoopChoiceNode::Emit(), v8::internal::ChoiceNode::EmitOptimizedUnanchoredSearch(), Flush(), and v8::internal::RegExpNode::LimitVersions().
mentions_reg()
bool v8::internal::Trace::mentions_reg (int reg) const
Definition at line 297 of file regexp-compiler.cc.
                                      {
  for (auto trace : *this) {
    if (trace->has_action() && trace->action()->Mentions(reg)) return true;
  }
  return false;
}
Referenced by v8::internal::ChoiceNode::AssertGuardsMentionRegisters(), and v8::internal::ChoiceNode::GenerateGuard().
next()
const Trace* v8::internal::Trace::next () const [inline]
Definition at line 339 of file regexp-compiler.h.
{ return next_; }
References next_.
Referenced by v8::internal::Trace::ConstIterator::operator++().
PerformDeferredActions()
void v8::internal::Trace::PerformDeferredActions (RegExpMacroAssembler * macro, int max_register, const DynamicBitSet & affected_registers, DynamicBitSet * registers_to_pop, DynamicBitSet * registers_to_clear, Zone * zone) [private]
Definition at line 385 of file regexp-compiler.cc.
                                               {
  // Count pushes performed to force a stack limit check occasionally.
  int pushes = 0;
  for (int reg = 0; reg <= max_register; reg++) {
    if (!affected_registers.Get(reg)) continue;
    // The chronologically first deferred action in the trace
    // is used to infer the action needed to restore a register
    // to its previous state (or not, if it's safe to ignore it).
    enum DeferredActionUndoType { IGNORE, RESTORE, CLEAR };
    DeferredActionUndoType undo_action = IGNORE;
    int value = 0;
    bool absolute = false;
    bool clear = false;
    static const int kNoStore = kMinInt;
    int store_position = kNoStore;
    // This is a little tricky because we are scanning the actions in reverse
    // historical order (newest first).
    for (auto trace : *this) {
      ActionNode* action = trace->action_;
      if (!action) continue;
      if (action->Mentions(reg)) {
        switch (action->action_type()) {
          case ActionNode::SET_REGISTER_FOR_LOOP: {
            if (!absolute) {
              value += action->value();
              absolute = true;
            }
            // SET_REGISTER_FOR_LOOP is only used for newly introduced loop
            // counters. They can have a significant previous value if they
            // occur in a loop. TODO(lrn): Propagate this information, so
            // we can set undo_action to IGNORE if we know there is no value to
            // restore.
            undo_action = RESTORE;
            DCHECK_EQ(store_position, kNoStore);
            DCHECK(!clear);
            break;
          }
          case ActionNode::INCREMENT_REGISTER:
            if (!absolute) {
              value++;
            }
            DCHECK_EQ(store_position, kNoStore);
            DCHECK(!clear);
            undo_action = RESTORE;
            break;
          case ActionNode::CLEAR_POSITION:
          case ActionNode::RESTORE_POSITION: {
            if (!clear && store_position == kNoStore) {
              store_position = trace->next()->cp_offset();
            }
            // For captures we know that stores and clears alternate.
            // Other register, are never cleared, and if the occur
            // inside a loop, they might be assigned more than once.
            if (reg <= 1) {
              // Registers zero and one, aka "capture zero", is
              // always set correctly if we succeed. There is no
              // need to undo a setting on backtrack, because we
              // will set it again or fail.
              undo_action = IGNORE;
            } else {
              if (action->action_type() == ActionNode::CLEAR_POSITION) {
                undo_action = CLEAR;
              } else {
                undo_action = RESTORE;
              }
            }
            DCHECK(!absolute);
            DCHECK_EQ(value, 0);
            break;
          }
          case ActionNode::CLEAR_CAPTURES: {
            // Since we're scanning in reverse order, if we've already
            // set the position we have to ignore historically earlier
            // clearing operations.
            if (store_position == kNoStore) {
              clear = true;
            }
            undo_action = RESTORE;
            DCHECK(!absolute);
            DCHECK_EQ(value, 0);
            break;
          }
          default:
            UNREACHABLE();
        }
      }
    }
    // Prepare for the undo-action (e.g., push if it's going to be popped).
    if (undo_action == RESTORE) {
      pushes++;
      RegExpMacroAssembler::StackCheckFlag stack_check =
          RegExpMacroAssembler::kNoStackLimitCheck;
      DCHECK_GT(assembler->stack_limit_slack_slot_count(), 0);
      if (pushes == assembler->stack_limit_slack_slot_count()) {
        stack_check = RegExpMacroAssembler::kCheckStackLimit;
        pushes = 0;
      }
      assembler->PushRegister(reg, stack_check);
      registers_to_pop->Set(reg, zone);
    } else if (undo_action == CLEAR) {
      registers_to_clear->Set(reg, zone);
    }
    // Perform the chronologically last action (or accumulated increment)
    // for the register.
    if (store_position != kNoStore) {
      assembler->WriteCurrentPositionToRegister(reg, store_position);
    } else if (clear) {
      assembler->ClearRegisters(reg, reg);
    } else if (absolute) {
      assembler->SetRegister(reg, value);
    } else if (value != 0) {
      assembler->AdvanceRegister(reg, value);
    }
  }
}
References action(), v8::internal::ActionNode::action_type(), v8::internal::RegExpMacroAssembler::AdvanceRegister(), v8::internal::ActionNode::CLEAR_CAPTURES, v8::internal::ActionNode::CLEAR_POSITION, v8::internal::RegExpMacroAssembler::ClearRegisters(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, v8::internal::DynamicBitSet::Get(), v8::internal::ActionNode::INCREMENT_REGISTER, v8::internal::RegExpMacroAssembler::kCheckStackLimit, v8::internal::kMinInt, v8::internal::RegExpMacroAssembler::kNoStackLimitCheck, v8::internal::ActionNode::Mentions(), v8::internal::RegExpMacroAssembler::PushRegister(), v8::internal::ActionNode::RESTORE_POSITION, v8::internal::DynamicBitSet::Set(), v8::internal::ActionNode::SET_REGISTER_FOR_LOOP, v8::internal::RegExpMacroAssembler::SetRegister(), v8::internal::RegExpMacroAssembler::stack_limit_slack_slot_count(), v8::internal::UNREACHABLE(), v8::internal::value, v8::internal::ActionNode::value, and v8::internal::RegExpMacroAssembler::WriteCurrentPositionToRegister().
Referenced by Flush().
quick_check_performed()
QuickCheckDetails* v8::internal::Trace::quick_check_performed () [inline]
Definition at line 311 of file regexp-compiler.h.
{ return &quick_check_performed_; }
References quick_check_performed_.
Referenced by v8::internal::ChoiceNode::EmitChoices(), and v8::internal::TextNode::TextEmitPass().
RestoreAffectedRegisters()
void v8::internal::Trace::RestoreAffectedRegisters (RegExpMacroAssembler * macro, int max_register, const DynamicBitSet & registers_to_pop, const DynamicBitSet & registers_to_clear) [private]
Definition at line 368 of file regexp-compiler.cc.
                                                                              {
  for (int reg = max_register; reg >= 0; reg--) {
    if (registers_to_pop.Get(reg)) {
      assembler->PopRegister(reg);
    } else if (registers_to_clear.Get(reg)) {
      int clear_to = reg;
      while (reg > 0 && registers_to_clear.Get(reg - 1)) {
        reg--;
      }
      assembler->ClearRegisters(reg, clear_to);
    }
  }
}
References v8::internal::RegExpMacroAssembler::ClearRegisters(), v8::internal::DynamicBitSet::Get(), and v8::internal::RegExpMacroAssembler::PopRegister().
Referenced by Flush().
set_at_start()
void v8::internal::Trace::set_at_start (TriBool at_start) [inline]
Definition at line 303 of file regexp-compiler.h.
{ at_start_ = at_start; }
References at_start(), and at_start_.
Referenced by v8::internal::TextNode::Emit(), v8::internal::AssertionNode::Emit(), v8::internal::BackReferenceNode::Emit(), v8::internal::ChoiceNode::EmitChoices(), v8::internal::ChoiceNode::EmitFixedLengthLoop(), v8::internal::ChoiceNode::EmitOutOfLineContinuation(), and v8::internal::FixedLengthLoopState::FixedLengthLoopState().
set_backtrack()
void v8::internal::Trace::set_backtrack (Label * backtrack) [inline]
Definition at line 324 of file regexp-compiler.h.
{ backtrack_ = backtrack; }
References backtrack(), and backtrack_.
Referenced by v8::internal::ActionNode::Emit(), v8::internal::ChoiceNode::EmitChoices(), v8::internal::ChoiceNode::EmitFixedLengthLoop(), v8::internal::ChoiceNode::EmitOutOfLineContinuation(), and v8::internal::FixedLengthLoopState::FixedLengthLoopState().
set_bound_checked_up_to()
void v8::internal::Trace::set_bound_checked_up_to (int to) [inline]
Definition at line 329 of file regexp-compiler.h.
{ bound_checked_up_to_ = to; }
References bound_checked_up_to_.
Referenced by v8::internal::ChoiceNode::EmitChoices().
set_characters_preloaded()
void v8::internal::Trace::set_characters_preloaded (int count) [inline]
Definition at line 328 of file regexp-compiler.h.
{ characters_preloaded_ = count; }
References characters_preloaded_.
Referenced by v8::internal::ChoiceNode::EmitChoices(), and v8::internal::ChoiceNode::EmitOutOfLineContinuation().
set_fixed_length_loop_state()
void v8::internal::Trace::set_fixed_length_loop_state (FixedLengthLoopState * state) [inline]
Definition at line 325 of file regexp-compiler.h.
                                                                {
    fixed_length_loop_state_ = state;
  }
References fixed_length_loop_state_.
Referenced by v8::internal::ChoiceNode::EmitFixedLengthLoop().
set_flush_budget()
void v8::internal::Trace::set_flush_budget (int to) [inline]
Definition at line 330 of file regexp-compiler.h.
                                {
    DCHECK(to <= UINT16_MAX); // Flush-budget is 16 bit.
    flush_budget_ = to;
  }
References v8::internal::DCHECK(), and flush_budget_.
Referenced by v8::internal::ChoiceNode::Emit(), and v8::internal::ChoiceNode::EmitChoices().
set_quick_check_performed()
void v8::internal::Trace::set_quick_check_performed (QuickCheckDetails * d) [inline]
Definition at line 334 of file regexp-compiler.h.
                                                       {
    quick_check_performed_ = *d;
  }
References quick_check_performed_.
Referenced by v8::internal::ChoiceNode::EmitChoices(), and v8::internal::ChoiceNode::EmitOutOfLineContinuation().
Member Data Documentation
action_
ActionNode* v8::internal::Trace::action_ [private]
Definition at line 376 of file regexp-compiler.h.
Referenced by action(), add_action(), and has_action().
at_start_
TriBool v8::internal::Trace::at_start_ [private]
Definition at line 374 of file regexp-compiler.h.
Referenced by at_start(), is_trivial(), and set_at_start().
backtrack_
Label* v8::internal::Trace::backtrack_ [private]
Definition at line 377 of file regexp-compiler.h.
Referenced by backtrack(), is_trivial(), and set_backtrack().
bound_checked_up_to_
int v8::internal::Trace::bound_checked_up_to_ [private]
Definition at line 380 of file regexp-compiler.h.
Referenced by AdvanceCurrentPositionInTrace(), bound_checked_up_to(), is_trivial(), and set_bound_checked_up_to().
characters_preloaded_
int v8::internal::Trace::characters_preloaded_ [private]
Definition at line 379 of file regexp-compiler.h.
Referenced by AdvanceCurrentPositionInTrace(), characters_preloaded(), InvalidateCurrentCharacter(), is_trivial(), and set_characters_preloaded().
cp_offset_
int v8::internal::Trace::cp_offset_ [private]
Definition at line 372 of file regexp-compiler.h.
Referenced by AdvanceCurrentPositionInTrace(), cp_offset(), Flush(), and is_trivial().
fixed_length_loop_state_
FixedLengthLoopState* v8::internal::Trace::fixed_length_loop_state_ [private]
Definition at line 378 of file regexp-compiler.h.
Referenced by fixed_length_loop_state(), and set_fixed_length_loop_state().
flush_budget_
uint16_t v8::internal::Trace::flush_budget_ [private]
Definition at line 373 of file regexp-compiler.h.
Referenced by flush_budget(), and set_flush_budget().
has_any_actions_
bool v8::internal::Trace::has_any_actions_ [private]
Definition at line 375 of file regexp-compiler.h.
Referenced by add_action(), has_any_actions(), and is_trivial().
next_
const Trace* v8::internal::Trace::next_ [private]
Definition at line 382 of file regexp-compiler.h.
Referenced by next().
quick_check_performed_
QuickCheckDetails v8::internal::Trace::quick_check_performed_ [private]
Definition at line 381 of file regexp-compiler.h.
Referenced by AdvanceCurrentPositionInTrace(), is_trivial(), quick_check_performed(), and set_quick_check_performed().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-compiler.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc