v8::internal::NativeContext Class Reference
#include <contexts.h>
Classes
class BodyDescriptor
Public Member Functions
void set (int index, Tagged< Object > value, WriteBarrierMode mode)=delete
void set (int index, Tagged< Object > value, WriteBarrierMode mode, ReleaseStoreTag)
void synchronized_set_script_context_table (Tagged< ScriptContextTable > script_context_table)
Tagged< ScriptContextTable > synchronized_script_context_table () const
Tagged< JSGlobalObject > global_object ()
Tagged< JSGlobalObject > global_object (AcquireLoadTag)
Tagged< Map > TypedArrayElementsKindToCtorMap (ElementsKind element_kind) const
Tagged< Map > TypedArrayElementsKindToRabGsabCtorMap (ElementsKind element_kind) const
bool HasTemplateLiteralObject (Tagged< JSArray > array)
DEFINE_FIELD_OFFSET_CONSTANTS (Context::kExtendedHeaderSize, NATIVE_CONTEXT_FIELDS_DEF) class BodyDescriptor
void ResetErrorsThrown ()
void IncrementErrorsThrown ()
int GetErrorsThrown ()
Private Member Functions
OBJECT_CONSTRUCTORS (NativeContext, Context)
Additional Inherited Members
Detailed Description
Definition at line 745 of file contexts.h.
Member Function Documentation
DEFINE_FIELD_OFFSET_CONSTANTS()
v8::internal::NativeContext::DEFINE_FIELD_OFFSET_CONSTANTS (Context::kExtendedHeaderSize , NATIVE_CONTEXT_FIELDS_DEF)
GetErrorsThrown()
int v8::internal::NativeContext::GetErrorsThrown ()
Definition at line 755 of file contexts.cc.
{ return errors_thrown().value(); }
global_object() [1/2]
Tagged<JSGlobalObject> v8::internal::NativeContext::global_object () [inline]
Definition at line 771 of file contexts.h.
{ return Context::global_object(); }
References v8::internal::Context::global_object().
global_object() [2/2]
Tagged<JSGlobalObject> v8::internal::NativeContext::global_object (AcquireLoadTag) [inline]
Definition at line 772 of file contexts.h.
                                                       {
    return Context::global_object();
  }
References v8::internal::Context::global_object().
HasTemplateLiteralObject()
bool v8::internal::NativeContext::HasTemplateLiteralObject (Tagged< JSArray > array)
Definition at line 672 of file contexts.cc.
                                                                  {
  return array->map() == js_array_template_literal_object_map();
}
IncrementErrorsThrown()
void v8::internal::NativeContext::IncrementErrorsThrown ()
Definition at line 750 of file contexts.cc.
                                          {
  int previous_value = errors_thrown().value();
  set_errors_thrown(Smi::FromInt(previous_value + 1));
}
References v8::internal::Smi::FromInt().
OBJECT_CONSTRUCTORS()
v8::internal::NativeContext::OBJECT_CONSTRUCTORS (NativeContext , Context) [private]
ResetErrorsThrown()
void v8::internal::NativeContext::ResetErrorsThrown ()
Definition at line 748 of file contexts.cc.
{ set_errors_thrown(Smi::FromInt(0)); }
References v8::internal::Smi::FromInt().
set() [1/2]
void v8::internal::NativeContext::set (int index, Tagged< Object > value, WriteBarrierMode mode) [delete]
Referenced by v8::internal::EXTERNAL_POINTER_ACCESSORS().
set() [2/2]
void v8::internal::NativeContext::set (int index, Tagged< Object > value, WriteBarrierMode mode, ReleaseStoreTag tag) [inline]
Definition at line 133 of file contexts-inl.h.
                                             {
  Context::set(index, value, mode, tag);
}
References v8::internal::index, mode(), v8::internal::Context::set(), and v8::internal::value.
synchronized_script_context_table()
Tagged< ScriptContextTable > v8::internal::NativeContext::synchronized_script_context_table () const [inline]
Definition at line 314 of file contexts-inl.h.
          {
  return Cast<ScriptContextTable>(
      get(SCRIPT_CONTEXT_TABLE_INDEX, kAcquireLoad));
}
References v8::internal::Context::get(), and v8::kAcquireLoad.
synchronized_set_script_context_table()
void v8::internal::NativeContext::synchronized_set_script_context_table (Tagged< ScriptContextTable > script_context_table) [inline]
TypedArrayElementsKindToCtorMap()
Tagged< Map > v8::internal::NativeContext::TypedArrayElementsKindToCtorMap (ElementsKind element_kind) const [inline]
Definition at line 320 of file contexts-inl.h.
                                     {
  int ctor_index = Context::FIRST_FIXED_TYPED_ARRAY_FUN_INDEX + element_kind -
                   ElementsKind::FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND;
  Tagged<Map> map =
      Cast<Map>(Cast<JSFunction>(get(ctor_index, kRelaxedLoad))->initial_map());
  DCHECK_EQ(map->elements_kind(), element_kind);
  DCHECK(InstanceTypeChecker::IsJSTypedArray(map));
  return map;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND, v8::internal::Context::FIRST_FIXED_TYPED_ARRAY_FUN_INDEX, v8::internal::Context::get(), v8::internal::compiler::initial_map, and v8::kRelaxedLoad.
TypedArrayElementsKindToRabGsabCtorMap()
Tagged< Map > v8::internal::NativeContext::TypedArrayElementsKindToRabGsabCtorMap (ElementsKind element_kind) const [inline]
Definition at line 331 of file contexts-inl.h.
                                     {
  int ctor_index = Context::FIRST_RAB_GSAB_TYPED_ARRAY_MAP_INDEX +
                   element_kind -
                   ElementsKind::FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND;
  Tagged<Map> map = Cast<Map>(get(ctor_index, kRelaxedLoad));
  DCHECK_EQ(map->elements_kind(),
            GetCorrespondingRabGsabElementsKind(element_kind));
  DCHECK(InstanceTypeChecker::IsJSTypedArray(map));
  return map;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::FIRST_FIXED_TYPED_ARRAY_ELEMENTS_KIND, v8::internal::Context::FIRST_RAB_GSAB_TYPED_ARRAY_MAP_INDEX, v8::internal::Context::get(), v8::internal::GetCorrespondingRabGsabElementsKind(), and v8::kRelaxedLoad.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/contexts.h
/mnt/V8SourceCode/src/objects/contexts-inl.h
/mnt/V8SourceCode/src/objects/contexts.cc