v8::internal::compiler::turboshaft::MaybeRedundantStoresTable Class Reference
#include <store-store-elimination-reducer-inl.h>
Classes
struct GetActiveKeysIndex
Public Member Functions
MaybeRedundantStoresTable (const Graph &graph, Zone *zone)
void OnNewKey (Key key, StoreObservability value)
void OnValueChange (Key key, StoreObservability old_value, StoreObservability new_value)
void BeginBlock (const Block *block)
StoreObservability GetObservability (OpIndex base, int32_t offset, uint8_t size)
void MarkStoreAsUnobservable (OpIndex base, int32_t offset, uint8_t size)
void MarkPotentiallyAliasingStoresAsObservable (OpIndex base, int32_t offset)
void MarkAllStoresAsObservable ()
void MarkAllStoresAsGCObservable ()
void Seal (bool *snapshot_has_changed=nullptr)
void Print (std::ostream &os, const char *sep=`\n`) const
Private Types
using super = ChangeTrackingSnapshotTable< MaybeRedundantStoresTable, StoreObservability, MaybeRedundantStoresKeyData >
Private Member Functions
Key map_to_key (OpIndex base, int32_t offset, uint8_t size)
Private Attributes
const Graph & graph_
GrowingBlockSidetable< std::optional< Snapshot > > block_to_snapshot_mapping_
ZoneAbslFlatHashMap< std::pair< OpIndex, int32_t >, Key > key_mapping_
ZoneIntrusiveSet< Key, GetActiveKeysIndex > active_keys_
const Block * current_block_ = nullptr
ZoneVector< Snapshot > successor_snapshots_
Additional Inherited Members
Detailed Description
Definition at line 103 of file store-store-elimination-reducer-inl.h.
Member Typedef Documentation
super
using v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::super = ChangeTrackingSnapshotTable<MaybeRedundantStoresTable, StoreObservability, MaybeRedundantStoresKeyData> [private]
Definition at line 107 of file store-store-elimination-reducer-inl.h.
Constructor & Destructor Documentation
MaybeRedundantStoresTable()
v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::MaybeRedundantStoresTable (const Graph & graph, Zone * zone) [inline], [explicit]
Definition at line 112 of file store-store-elimination-reducer-inl.h.
      : ChangeTrackingSnapshotTable(zone),
        graph_(graph),
        block_to_snapshot_mapping_(zone),
        key_mapping_(zone),
        active_keys_(zone),
        successor_snapshots_(zone) {}
Member Function Documentation
BeginBlock()
void v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::BeginBlock (const Block * block) [inline]
Definition at line 135 of file store-store-elimination-reducer-inl.h.
                                      {
    // Seal the current block first.
    if (IsSealed()) {
      DCHECK_NULL(current_block_);
    } else {
      // If we bind a new block while the previous one is still unsealed, we
      // finalize it.
      Seal();
    }
    // Collect the snapshots of all successors.
    {
      auto successors = SuccessorBlocks(block->LastOperation(graph_));
      successor_snapshots_.clear();
      for (const Block* s : successors) {
        std::optional<Snapshot> s_snapshot =
            block_to_snapshot_mapping_[s->index()];
        // When we visit the loop for the first time, the loop header hasn't
        // been visited yet, so we ignore it.
        DCHECK_IMPLIES(!s_snapshot.has_value(), s->IsLoop());
        if (!s_snapshot.has_value()) continue;
        successor_snapshots_.push_back(*s_snapshot);
      }
    }
    // Start a new snapshot for this block by merging information from
    // successors.
    StartNewSnapshot(
        base::VectorOf(successor_snapshots_),
        [](Key, base::Vector<const StoreObservability> successors) {
          return static_cast<StoreObservability>(
              *std::max_element(successors.begin(), successors.end()));
        });
    current_block_ = block;
  }
References v8::base::Vector< T >::begin(), block_to_snapshot_mapping_, v8::internal::ZoneVector< T >::clear(), current_block_, DCHECK_IMPLIES, DCHECK_NULL, v8::base::Vector< T >::end(), graph_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::IsSealed(), v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MaybeRedundantStoresTable, StoreObservability, MaybeRedundantStoresKeyData >::StartNewSnapshot(), successor_snapshots_, v8::internal::compiler::turboshaft::SuccessorBlocks(), and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock().
GetObservability()
StoreObservability v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::GetObservability (OpIndex base, int32_t offset, uint8_t size) [inline]
Definition at line 172 of file store-store-elimination-reducer-inl.h.
                                                    {
    Key key = map_to_key(base, offset, size);
    if (key.data().size < size) return StoreObservability::kObservable;
    return Get(key);
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get(), v8::internal::key, v8::internal::compiler::turboshaft::kObservable, map_to_key(), and size().
Referenced by v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock().
map_to_key()
Key v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::map_to_key (OpIndex base, int32_t offset, uint8_t size) [inline], [private]
Definition at line 252 of file store-store-elimination-reducer-inl.h.
                                                             {
    std::pair p{base, offset};
    auto it = key_mapping_.find(p);
    if (it != key_mapping_.end()) return it->second;
    Key new_key = NewKey(MaybeRedundantStoresKeyData{base, offset, size},
                         StoreObservability::kObservable);
    key_mapping_.emplace(p, new_key);
    return new_key;
  }
References key_mapping_, v8::internal::compiler::turboshaft::kObservable, v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MaybeRedundantStoresTable, StoreObservability, MaybeRedundantStoresKeyData >::NewKey(), and size().
Referenced by GetObservability(), and MarkStoreAsUnobservable().
MarkAllStoresAsGCObservable()
void v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::MarkAllStoresAsGCObservable () [inline]
Definition at line 206 of file store-store-elimination-reducer-inl.h.
                                     {
    for (Key key : active_keys_) {
      auto current = Get(key);
      DCHECK_NE(current, StoreObservability::kObservable);
      if (current == StoreObservability::kUnobservable) {
        Set(key, StoreObservability::kGCObservable);
      }
    }
  }
References active_keys_, DCHECK_NE, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get(), v8::internal::key, v8::internal::compiler::turboshaft::kGCObservable, v8::internal::compiler::turboshaft::kObservable, v8::internal::compiler::turboshaft::kUnobservable, and v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MaybeRedundantStoresTable, StoreObservability, MaybeRedundantStoresKeyData >::Set().
Referenced by v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock().
MarkAllStoresAsObservable()
void v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::MarkAllStoresAsObservable () [inline]
Definition at line 200 of file store-store-elimination-reducer-inl.h.
                                   {
    for (Key key : active_keys_) {
      Set(key, StoreObservability::kObservable);
    }
  }
References active_keys_, v8::internal::key, v8::internal::compiler::turboshaft::kObservable, and v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MaybeRedundantStoresTable, StoreObservability, MaybeRedundantStoresKeyData >::Set().
Referenced by v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock().
MarkPotentiallyAliasingStoresAsObservable()
void v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::MarkPotentiallyAliasingStoresAsObservable (OpIndex base, int32_t offset) [inline]
Definition at line 190 of file store-store-elimination-reducer-inl.h.
                                                                               {
    // For now, we consider all stores to the same offset as potentially
    // aliasing. We might improve this to eliminate more precisely, if we have
    // some sort of aliasing information.
    for (Key key : active_keys_) {
      if (key.data().offset == offset)
        Set(key, StoreObservability::kObservable);
    }
  }
References active_keys_, v8::internal::key, v8::internal::compiler::turboshaft::kObservable, and v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MaybeRedundantStoresTable, StoreObservability, MaybeRedundantStoresKeyData >::Set().
Referenced by v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock().
MarkStoreAsUnobservable()
void v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::MarkStoreAsUnobservable (OpIndex base, int32_t offset, uint8_t size) [inline]
Definition at line 179 of file store-store-elimination-reducer-inl.h.
                                                                           {
    // We can only shadow stores to the exact same `base`+`offset` and keep
    // everything else because they might or might not alias.
    Key key = map_to_key(base, offset, size);
    // If the `size` we want to mark unobservable here is less than the size we
    // have seen for this key before, we do not overwrite the entire field, so
    // preceeding stores are not (fully) unobservable.
    if (size < key.data().size) return;
    Set(key, StoreObservability::kUnobservable);
  }
References v8::internal::key, v8::internal::compiler::turboshaft::kUnobservable, map_to_key(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MaybeRedundantStoresTable, StoreObservability, MaybeRedundantStoresKeyData >::Set(), and size().
Referenced by v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock().
OnNewKey()
void v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::OnNewKey (Key key, StoreObservability value) [inline]
Definition at line 120 of file store-store-elimination-reducer-inl.h.
                                                   {
    DCHECK_EQ(value, StoreObservability::kObservable);
    DCHECK(!active_keys_.Contains(key));
  }
References active_keys_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::key, v8::internal::compiler::turboshaft::kObservable, and v8::internal::value.
OnValueChange()
void v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::OnValueChange (Key key, StoreObservability old_value, StoreObservability new_value) [inline]
Definition at line 125 of file store-store-elimination-reducer-inl.h.
                                                   {
    DCHECK_NE(old_value, new_value);
    if (new_value == StoreObservability::kObservable) {
      active_keys_.Remove(key);
    } else if (old_value == StoreObservability::kObservable) {
      active_keys_.Add(key);
    }
  }
References active_keys_, DCHECK_NE, v8::internal::key, and v8::internal::compiler::turboshaft::kObservable.
Print()
void v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::Print (std::ostream & os, const char * sep = `\n`) const [inline]
Definition at line 242 of file store-store-elimination-reducer-inl.h.
                                                           {
    bool first = true;
    for (Key key : active_keys_) {
      os << (first ? "" : sep) << key.data().base.id() << "@"
         << key.data().offset << ": " << Get(key);
      first = false;
    }
  }
References active_keys_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get(), and v8::internal::key.
Seal()
void v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::Seal (bool * snapshot_has_changed = nullptr) [inline]
Definition at line 216 of file store-store-elimination-reducer-inl.h.
                                                  {
    DCHECK(!IsSealed());
    DCHECK_NOT_NULL(current_block_);
    DCHECK(current_block_->index().valid());
    auto& snapshot = block_to_snapshot_mapping_[current_block_->index()];
    if (!snapshot_has_changed) {
      snapshot = super::Seal();
    } else if (!snapshot.has_value()) {
      *snapshot_has_changed = true;
      snapshot = super::Seal();
    } else {
      auto new_snapshot = super::Seal();
      *snapshot_has_changed = false;
      StartNewSnapshot(
          base::VectorOf({snapshot.value(), new_snapshot}),
          [&](Key key, base::Vector<const StoreObservability> successors) {
            DCHECK_LE(successors[0], successors[1]);
            if (successors[0] != successors[1]) *snapshot_has_changed = true;
            return static_cast<StoreObservability>(
                *std::max_element(successors.begin(), successors.end()));
          });
      snapshot = super::Seal();
    }
    current_block_ = nullptr;
  }
References v8::base::Vector< T >::begin(), block_to_snapshot_mapping_, current_block_, v8::internal::DCHECK(), DCHECK_LE, DCHECK_NOT_NULL, v8::base::Vector< T >::end(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::IsSealed(), v8::internal::key, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< MaybeRedundantStoresTable, StoreObservability, MaybeRedundantStoresKeyData >::StartNewSnapshot(), v8::internal::compiler::turboshaft::BlockIndex::valid(), and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::RedundantStoreAnalysis::Run().
Member Data Documentation
active_keys_
ZoneIntrusiveSet<Key, GetActiveKeysIndex> v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::active_keys_ [private]
Definition at line 273 of file store-store-elimination-reducer-inl.h.
Referenced by MarkAllStoresAsGCObservable(), MarkAllStoresAsObservable(), MarkPotentiallyAliasingStoresAsObservable(), OnNewKey(), OnValueChange(), and Print().
block_to_snapshot_mapping_
GrowingBlockSidetable<std::optional<Snapshot> > v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::block_to_snapshot_mapping_ [private]
Definition at line 268 of file store-store-elimination-reducer-inl.h.
Referenced by BeginBlock(), and Seal().
current_block_
const Block* v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::current_block_ = nullptr [private]
Definition at line 274 of file store-store-elimination-reducer-inl.h.
Referenced by BeginBlock(), and Seal().
graph_
const Graph& v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::graph_ [private]
Definition at line 267 of file store-store-elimination-reducer-inl.h.
Referenced by BeginBlock().
key_mapping_
ZoneAbslFlatHashMap<std::pair<OpIndex, int32_t>, Key> v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::key_mapping_ [private]
Definition at line 269 of file store-store-elimination-reducer-inl.h.
Referenced by map_to_key().
successor_snapshots_
ZoneVector<Snapshot> v8::internal::compiler::turboshaft::MaybeRedundantStoresTable::successor_snapshots_ [private]
Definition at line 277 of file store-store-elimination-reducer-inl.h.
Referenced by BeginBlock().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/store-store-elimination-reducer-inl.h