v8::String::Value Class Reference
Converts an object to a two-byte (UTF-16-encoded) string.
#include <v8-primitive.h>
Public Member Functions
~Value ()
uint16_t * operator* ()
const uint16_t * operator* () const
uint32_t length () const
Value (const Value &)=delete
void operator= (const Value &)=delete
Private Attributes
uint16_t * str_
uint32_t length_
Detailed Description
Converts an object to a two-byte (UTF-16-encoded) string.
If conversion to a string fails (eg. due to an exception in the toString() method of the object) then the length() method returns 0 and the * operator returns NULL.
WARNING: This will unconditionally copy the contents of the JavaScript string, and should be avoided in situations where performance is a concern.
Definition at line 674 of file v8-primitive.h.
Constructor & Destructor Documentation
 Value()
v8::String::Value::~Value ()
Definition at line 11089 of file api.cc.
{ i::DeleteArray(str_); }
Value()
v8::String::Value::Value (const Value &) [delete]
Definition at line 11073 of file api.cc.
    : str_(nullptr), length_(0) {
  if (obj.IsEmpty()) return;
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::HandleScope scope(i_isolate);
  Local<Context> context = v8_isolate->GetCurrentContext();
  EnterV8BasicScope api_scope(i_isolate);
  TryCatch try_catch(v8_isolate);
  Local<String> str;
  if (!obj->ToString(context).ToLocal(&str)) return;
  length_ = str->Length();
  str_ = i::NewArray<uint16_t>(length_ + 1);
  str->WriteV2(v8_isolate, 0, length_, str_,
               String::WriteFlags::kNullTerminate);
}
References v8::Isolate::GetCurrentContext(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::String::WriteFlags::kNullTerminate, length_, str_, and v8::Value::ToString().
Member Function Documentation
length()
uint32_t v8::String::Value::length () const [inline]
Definition at line 683 of file v8-primitive.h.
{ return length_; }
operator*() [1/2]
uint16_t* v8::String::Value::operator* () [inline]
Definition at line 681 of file v8-primitive.h.
{ return str_; }
operator*() [2/2]
const uint16_t* v8::String::Value::operator* () const [inline]
Definition at line 682 of file v8-primitive.h.
{ return str_; }
operator=()
void v8::String::Value::operator= (const Value &) [delete]
Member Data Documentation
length_
uint32_t v8::String::Value::length_ [private]
Definition at line 691 of file v8-primitive.h.
Referenced by Value().
str_
uint16_t* v8::String::Value::str_ [private]
Definition at line 690 of file v8-primitive.h.
Referenced by Value().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc