cppgc::internal::ConcurrentMarkerBase Class Reference
#include <concurrent-marker.h>
Public Member Functions
ConcurrentMarkerBase (HeapBase &, MarkingWorklists &, heap::base::IncrementalMarkingSchedule &, cppgc::Platform *)
virtual ~ConcurrentMarkerBase ()
ConcurrentMarkerBase (const ConcurrentMarkerBase &)=delete
ConcurrentMarkerBase & operator= (const ConcurrentMarkerBase &)=delete
void Start ()
bool Join ()
bool Cancel ()
void NotifyIncrementalMutatorStepCompleted ()
void NotifyOfWorkIfNeeded (cppgc::TaskPriority priority)
bool IsActive () const
HeapBase & heap () const
MarkingWorklists & marking_worklists () const
heap::base::IncrementalMarkingSchedule & incremental_marking_schedule () const
void AddConcurrentlyMarkedBytes (size_t marked_bytes)
size_t concurrently_marked_bytes () const
virtual std::unique_ptr< Visitor > CreateConcurrentMarkingVisitor (ConcurrentMarkingState &) const =0
Protected Member Functions
void IncreaseMarkingPriorityIfNeeded ()
Private Attributes
HeapBase & heap_
MarkingWorklists & marking_worklists_
heap::base::IncrementalMarkingSchedule & incremental_marking_schedule_
cppgc::Platform *const platform_
std::unique_ptr< JobHandle > concurrent_marking_handle_ {nullptr}
std::atomic< size_t > concurrently_marked_bytes_ = 0
bool concurrent_marking_priority_increased_ {false}
Detailed Description
Definition at line 17 of file concurrent-marker.h.
Constructor & Destructor Documentation
ConcurrentMarkerBase() [1/2]
cppgc::internal::ConcurrentMarkerBase::ConcurrentMarkerBase (HeapBase & heap, MarkingWorklists & marking_worklists, heap::base::IncrementalMarkingSchedule & incremental_marking_schedule, cppgc::Platform * platform)
Definition at line 176 of file concurrent-marker.cc.
    : heap_(heap),
      marking_worklists_(marking_worklists),
      incremental_marking_schedule_(incremental_marking_schedule),
      platform_(platform) {}
 ConcurrentMarkerBase()
cppgc::internal::ConcurrentMarkerBase::~ConcurrentMarkerBase () [virtual]
Definition at line 218 of file concurrent-marker.cc.
                                            {
  CHECK_IMPLIES(concurrent_marking_handle_,
                !concurrent_marking_handle_->IsValid());
}
References CHECK_IMPLIES, and concurrent_marking_handle_.
ConcurrentMarkerBase() [2/2]
cppgc::internal::ConcurrentMarkerBase::ConcurrentMarkerBase (const ConcurrentMarkerBase &) [delete]
Member Function Documentation
AddConcurrentlyMarkedBytes()
void cppgc::internal::ConcurrentMarkerBase::AddConcurrentlyMarkedBytes (size_t marked_bytes)
Definition at line 213 of file concurrent-marker.cc.
                                                                         {
  concurrently_marked_bytes_.fetch_add(marked_bytes, std::memory_order_relaxed);
  incremental_marking_schedule().AddConcurrentlyMarkedBytes(marked_bytes);
}
References heap::base::IncrementalMarkingSchedule::AddConcurrentlyMarkedBytes(), concurrently_marked_bytes_, and incremental_marking_schedule().
Referenced by cppgc::internal::anonymous_namespace{concurrent-marker.cc}::DrainWorklistWithYielding(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::Run().
Cancel()
bool cppgc::internal::ConcurrentMarkerBase::Cancel ()
Definition at line 201 of file concurrent-marker.cc.
                                  {
  if (!concurrent_marking_handle_ || !concurrent_marking_handle_->IsValid())
    return false;
  concurrent_marking_handle_->Cancel();
  return true;
}
References concurrent_marking_handle_.
concurrently_marked_bytes()
size_t cppgc::internal::ConcurrentMarkerBase::concurrently_marked_bytes () const [inline]
Definition at line 45 of file concurrent-marker.h.
                                           {
    return concurrently_marked_bytes_.load(std::memory_order_relaxed);
  }
Referenced by cppgc::internal::MarkerBase::LeaveAtomicPause().
CreateConcurrentMarkingVisitor()
virtual std::unique_ptr<Visitor> cppgc::internal::ConcurrentMarkerBase::CreateConcurrentMarkingVisitor (ConcurrentMarkingState &) const [pure virtual]
Implemented in v8::internal::anonymous_namespace{cpp-heap.cc}::UnifiedHeapConcurrentMarker, and cppgc::internal::ConcurrentMarker.
Referenced by cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::Run().
heap()
HeapBase& cppgc::internal::ConcurrentMarkerBase::heap () const [inline]
Definition at line 38 of file concurrent-marker.h.
{ return heap_; }
Referenced by cppgc::internal::ConcurrentMarker::CreateConcurrentMarkingVisitor(), cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::Run().
IncreaseMarkingPriorityIfNeeded()
void cppgc::internal::ConcurrentMarkerBase::IncreaseMarkingPriorityIfNeeded () [protected]
Definition at line 240 of file concurrent-marker.cc.
                                                           {
  if (!concurrent_marking_handle_->UpdatePriorityEnabled() ||
      concurrent_marking_priority_increased_) {
    return;
  }
  // If concurrent tasks aren't executed, it might delay GC finalization. As
  // long as GC is active so is the write barrier, which incurs a performance
  // cost. Marking is estimated to take overall
  // |MarkingSchedulingOracle::kEstimatedMarkingTime|. If concurrent marking
  // tasks have not reported any progress (i.e. the concurrently marked bytes
  // count as not changed) in over
  // |kMarkingScheduleRatioBeforeConcurrentPriorityIncrease| of that expected
  // duration, we increase the concurrent task priority for the duration of the
  // current GC. This is meant to prevent the GC from exceeding it's expected
  // end time.
  const auto time_delta =
      incremental_marking_schedule_.GetTimeSinceLastConcurrentMarkingUpdate();
  if (!time_delta.IsZero() &&
      (time_delta.InMillisecondsF() >
       (heap::base::IncrementalMarkingSchedule::kEstimatedMarkingTime
            .InMillisecondsF() *
        kMarkingScheduleRatioBeforeConcurrentPriorityIncrease))) {
    concurrent_marking_handle_->UpdatePriority(
        cppgc::TaskPriority::kUserBlocking);
    concurrent_marking_priority_increased_ = true;
  }
}
References concurrent_marking_handle_, concurrent_marking_priority_increased_, heap::base::IncrementalMarkingSchedule::GetTimeSinceLastConcurrentMarkingUpdate(), incremental_marking_schedule_, v8::base::TimeDelta::InMillisecondsF(), heap::base::IncrementalMarkingSchedule::kEstimatedMarkingTime, cppgc::internal::anonymous_namespace{concurrent-marker.cc}::kMarkingScheduleRatioBeforeConcurrentPriorityIncrease, and v8::kUserBlocking.
Referenced by NotifyIncrementalMutatorStepCompleted().
incremental_marking_schedule()
heap::base::IncrementalMarkingSchedule& cppgc::internal::ConcurrentMarkerBase::incremental_marking_schedule () const [inline]
Definition at line 40 of file concurrent-marker.h.
                                                                           {
    return incremental_marking_schedule_;
  }
Referenced by AddConcurrentlyMarkedBytes().
IsActive()
bool cppgc::internal::ConcurrentMarkerBase::IsActive () const
Definition at line 209 of file concurrent-marker.cc.
                                          {
  return concurrent_marking_handle_ && concurrent_marking_handle_->IsValid();
}
References concurrent_marking_handle_.
Referenced by cppgc::internal::MarkerBase::EnterAtomicPause(), cppgc::internal::MarkerBase::NotifyConcurrentMarkingOfWorkIfNeeded(), and cppgc::internal::MarkerBase::ReEnableConcurrentMarking().
Join()
bool cppgc::internal::ConcurrentMarkerBase::Join ()
Definition at line 193 of file concurrent-marker.cc.
                                {
  if (!concurrent_marking_handle_ || !concurrent_marking_handle_->IsValid())
    return false;
  concurrent_marking_handle_->Join();
  return true;
}
References concurrent_marking_handle_.
Referenced by cppgc::internal::MarkerBase::WaitForConcurrentMarkingForTesting().
marking_worklists()
MarkingWorklists& cppgc::internal::ConcurrentMarkerBase::marking_worklists () const [inline]
Definition at line 39 of file concurrent-marker.h.
{ return marking_worklists_; }
Referenced by cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::GetMaxConcurrency(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::Run().
NotifyIncrementalMutatorStepCompleted()
void cppgc::internal::ConcurrentMarkerBase::NotifyIncrementalMutatorStepCompleted ()
Definition at line 223 of file concurrent-marker.cc.
                                                                 {
  DCHECK(concurrent_marking_handle_);
  if (HasWorkForConcurrentMarking(marking_worklists_)) {
    // Notifies the scheduler that max concurrency might have increased.
    // This will adjust the number of markers if necessary.
    IncreaseMarkingPriorityIfNeeded();
    concurrent_marking_handle_->NotifyConcurrencyIncrease();
  }
}
References concurrent_marking_handle_, DCHECK, cppgc::internal::anonymous_namespace{concurrent-marker.cc}::HasWorkForConcurrentMarking(), IncreaseMarkingPriorityIfNeeded(), and marking_worklists_.
Referenced by cppgc::internal::MarkerBase::AdvanceMarkingWithLimitsEpilogue(), and cppgc::internal::MarkerBase::EnterAtomicPause().
NotifyOfWorkIfNeeded()
void cppgc::internal::ConcurrentMarkerBase::NotifyOfWorkIfNeeded (cppgc::TaskPriority priority)
Definition at line 233 of file concurrent-marker.cc.
                                                                          {
  if (HasWorkForConcurrentMarking(marking_worklists_)) {
    concurrent_marking_handle_->UpdatePriority(priority);
    concurrent_marking_handle_->NotifyConcurrencyIncrease();
  }
}
References concurrent_marking_handle_, cppgc::internal::anonymous_namespace{concurrent-marker.cc}::HasWorkForConcurrentMarking(), and marking_worklists_.
Referenced by cppgc::internal::MarkerBase::NotifyConcurrentMarkingOfWorkIfNeeded().
operator=()
ConcurrentMarkerBase& cppgc::internal::ConcurrentMarkerBase::operator= (const ConcurrentMarkerBase &) [delete]
Start()
void cppgc::internal::ConcurrentMarkerBase::Start ()
Definition at line 185 of file concurrent-marker.cc.
                                 {
  DCHECK(platform_);
  concurrent_marking_handle_ =
      platform_->PostJob(v8::TaskPriority::kUserVisible,
                         std::make_unique<ConcurrentMarkingTask>(*this));
  incremental_marking_schedule_.NotifyConcurrentMarkingStart();
}
References concurrent_marking_handle_, DCHECK, incremental_marking_schedule_, v8::kUserVisible, heap::base::IncrementalMarkingSchedule::NotifyConcurrentMarkingStart(), platform_, and cppgc::Platform::PostJob().
Referenced by cppgc::internal::MarkerBase::EnterAtomicPause(), cppgc::internal::MarkerBase::ReEnableConcurrentMarking(), and cppgc::internal::MarkerBase::StartMarking().
Member Data Documentation
concurrent_marking_handle_
std::unique_ptr<JobHandle> cppgc::internal::ConcurrentMarkerBase::concurrent_marking_handle_ {nullptr} [private]
Definition at line 62 of file concurrent-marker.h.
Referenced by Cancel(), IncreaseMarkingPriorityIfNeeded(), IsActive(), Join(), NotifyIncrementalMutatorStepCompleted(), NotifyOfWorkIfNeeded(), Start(), and ~ConcurrentMarkerBase().
concurrent_marking_priority_increased_
bool cppgc::internal::ConcurrentMarkerBase::concurrent_marking_priority_increased_ {false} [private]
Definition at line 65 of file concurrent-marker.h.
Referenced by IncreaseMarkingPriorityIfNeeded().
concurrently_marked_bytes_
std::atomic<size_t> cppgc::internal::ConcurrentMarkerBase::concurrently_marked_bytes_ = 0 [private]
Definition at line 64 of file concurrent-marker.h.
Referenced by AddConcurrentlyMarkedBytes().
heap_
HeapBase& cppgc::internal::ConcurrentMarkerBase::heap_ [private]
Definition at line 56 of file concurrent-marker.h.
incremental_marking_schedule_
heap::base::IncrementalMarkingSchedule& cppgc::internal::ConcurrentMarkerBase::incremental_marking_schedule_ [private]
Definition at line 58 of file concurrent-marker.h.
Referenced by IncreaseMarkingPriorityIfNeeded(), and Start().
marking_worklists_
MarkingWorklists& cppgc::internal::ConcurrentMarkerBase::marking_worklists_ [private]
Definition at line 57 of file concurrent-marker.h.
Referenced by NotifyIncrementalMutatorStepCompleted(), and NotifyOfWorkIfNeeded().
platform_
cppgc::Platform* const cppgc::internal::ConcurrentMarkerBase::platform_ [private]
Definition at line 59 of file concurrent-marker.h.
Referenced by Start().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/concurrent-marker.h
/mnt/V8SourceCode/src/heap/cppgc/concurrent-marker.cc