v8::internal::wasm::WasmModuleSourceMap Class Reference
#include <wasm-module-sourcemap.h>
Public Member Functions
WasmModuleSourceMap (v8::Isolate *v8_isolate, v8::Local< v8::String > src_map_str)
bool IsValid () const
bool HasSource (size_t start, size_t end) const
bool HasValidEntry (size_t start, size_t addr) const
size_t GetSourceLine (size_t wasm_offset) const
std::string GetFilename (size_t wasm_offset) const
size_t EstimateCurrentMemoryConsumption () const
Private Member Functions
bool DecodeMapping (const std::string &s)
Private Attributes
std::vector< size_t > offsets
std::vector< std::string > filenames
std::vector< size_t > file_idxs
std::vector< size_t > source_row
bool valid_ = false
Detailed Description
Definition at line 38 of file wasm-module-sourcemap.h.
Constructor & Destructor Documentation
WasmModuleSourceMap()
v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap (v8::Isolate * v8_isolate, v8::Local< v8::String > src_map_str)
Definition at line 24 of file wasm-module-sourcemap.cc.
                                                                        {
  v8::HandleScope scope(v8_isolate);
  v8::Local<v8::Context> context = v8::Context::New(v8_isolate);
  v8::Local<v8::Value> src_map_value;
  if (!v8::JSON::Parse(context, src_map_str).ToLocal(&src_map_value)) return;
  v8::Local<v8::Object> src_map_obj =
      v8::Local<v8::Object>::Cast(src_map_value);
  v8::Local<v8::Value> version_value, sources_value, mappings_value;
  bool has_valid_version =
      src_map_obj
          ->Get(context, v8::String::NewFromUtf8Literal(v8_isolate, "version"))
          .ToLocal(&version_value) &&
      version_value->IsUint32();
  uint32_t version = 0;
  if (!has_valid_version || !version_value->Uint32Value(context).To(&version) ||
      version != 3u)
    return;
  bool has_valid_sources =
      src_map_obj
          ->Get(context, v8::String::NewFromUtf8Literal(v8_isolate, "sources"))
          .ToLocal(&sources_value) &&
      sources_value->IsArray();
  if (!has_valid_sources) return;
  v8::Local<v8::Object> sources_arr =
      v8::Local<v8::Object>::Cast(sources_value);
  v8::Local<v8::Value> sources_len_value;
  if (!sources_arr
           ->Get(context, v8::String::NewFromUtf8Literal(v8_isolate, "length"))
           .ToLocal(&sources_len_value))
    return;
  uint32_t sources_len = 0;
  if (!sources_len_value->Uint32Value(context).To(&sources_len)) return;
  for (uint32_t i = 0; i < sources_len; ++i) {
    v8::Local<v8::Value> file_name_value;
    if (!sources_arr->Get(context, i).ToLocal(&file_name_value) ||
        !file_name_value->IsString())
      return;
    v8::Local<v8::String> file_name =
        v8::Local<v8::String>::Cast(file_name_value);
    size_t file_name_sz = file_name->Utf8LengthV2(v8_isolate) + 1;
    std::unique_ptr<char[]> file_name_buf(new char[file_name_sz]);
    file_name->WriteUtf8V2(v8_isolate, file_name_buf.get(), file_name_sz,
                           v8::String::WriteFlags::kNullTerminate);
    filenames.emplace_back(file_name_buf.get());
  }
  bool has_valid_mappings =
      src_map_obj
          ->Get(context, v8::String::NewFromUtf8Literal(v8_isolate, "mappings"))
          .ToLocal(&mappings_value) &&
      mappings_value->IsString();
  if (!has_valid_mappings) return;
  v8::Local<v8::String> mappings = v8::Local<v8::String>::Cast(mappings_value);
  size_t mappings_sz = mappings->Utf8LengthV2(v8_isolate) + 1;
  std::unique_ptr<char[]> mappings_buf(new char[mappings_sz]);
  mappings->WriteUtf8V2(v8_isolate, mappings_buf.get(), mappings_sz,
                        v8::String::WriteFlags::kNullTerminate);
  valid_ = DecodeMapping(mappings_buf.get());
}
References v8::Local< T >::Cast(), DecodeMapping(), filenames, v8::internal::wasm::Get(), v8::Object::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::Value::IsArray(), v8::Value::IsString(), v8::Value::IsUint32(), v8::String::WriteFlags::kNullTerminate, v8::Context::New(), v8::String::NewFromUtf8Literal(), v8::JSON::Parse(), v8::MaybeLocal< T >::ToLocal(), v8::Value::Uint32Value(), v8::String::Utf8LengthV2(), valid_, and v8::String::WriteUtf8V2().
Referenced by EstimateCurrentMemoryConsumption().
Member Function Documentation
DecodeMapping()
bool v8::internal::wasm::WasmModuleSourceMap::DecodeMapping (const std::string & s) [private]
Definition at line 123 of file wasm-module-sourcemap.cc.
                                                          {
  size_t pos = 0, gen_col = 0, file_idx = 0, ori_line = 0;
  int32_t qnt = 0;
  while (pos < s.size()) {
    // Skip redundant commas.
    if (s[pos] == ',') {
      ++pos;
      continue;
    }
    if ((qnt = base::VLQBase64Decode(s.c_str(), s.size(), &pos)) ==
        std::numeric_limits<int32_t>::min())
      return false;
    gen_col += qnt;
    if ((qnt = base::VLQBase64Decode(s.c_str(), s.size(), &pos)) ==
        std::numeric_limits<int32_t>::min())
      return false;
    file_idx += qnt;
    if ((qnt = base::VLQBase64Decode(s.c_str(), s.size(), &pos)) ==
        std::numeric_limits<int32_t>::min())
      return false;
    ori_line += qnt;
    // Column number in source file is always 0 in source map generated by
    // Emscripten. We just decode this value without further usage of it.
    if ((qnt = base::VLQBase64Decode(s.c_str(), s.size(), &pos)) ==
        std::numeric_limits<int32_t>::min())
      return false;
    if (pos < s.size() && s[pos] != ',') return false;
    pos++;
    file_idxs.push_back(file_idx);
    source_row.push_back(ori_line);
    offsets.push_back(gen_col);
  }
  return true;
}
References file_idxs, offsets, source_row, and v8::base::VLQBase64Decode().
Referenced by WasmModuleSourceMap().
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::WasmModuleSourceMap::EstimateCurrentMemoryConsumption () const
Definition at line 161 of file wasm-module-sourcemap.cc.
                                                                   {
  UPDATE_WHEN_CLASS_CHANGES(WasmModuleSourceMap, 104);
  size_t result = sizeof(WasmModuleSourceMap);
  result += ContentSize(offsets);
  result += ContentSize(filenames);
  for (const std::string& s : filenames) {
    result += s.length();
  }
  result += ContentSize(file_idxs);
  result += ContentSize(source_row);
  return result;
}
References v8::internal::wasm::ContentSize(), file_idxs, filenames, offsets, v8::base::internal::result, source_row, v8::internal::string, UPDATE_WHEN_CLASS_CHANGES, and WasmModuleSourceMap().
GetFilename()
std::string v8::internal::wasm::WasmModuleSourceMap::GetFilename (size_t wasm_offset) const
Definition at line 100 of file wasm-module-sourcemap.cc.
                                                                   {
  std::vector<size_t>::const_iterator up =
      std::upper_bound(offsets.begin(), offsets.end(), wasm_offset);
  CHECK_NE(offsets.begin(), up);
  size_t offset_idx = up - offsets.begin() - 1;
  size_t filename_idx = file_idxs[offset_idx];
  return filenames[filename_idx];
}
References CHECK_NE, file_idxs, filenames, and offsets.
GetSourceLine()
size_t v8::internal::wasm::WasmModuleSourceMap::GetSourceLine (size_t wasm_offset) const
Definition at line 92 of file wasm-module-sourcemap.cc.
                                                                  {
  std::vector<std::size_t>::const_iterator up =
      std::upper_bound(offsets.begin(), offsets.end(), wasm_offset);
  CHECK_NE(offsets.begin(), up);
  size_t source_idx = up - offsets.begin() - 1;
  return source_row[source_idx];
}
References CHECK_NE, offsets, and source_row.
HasSource()
bool v8::internal::wasm::WasmModuleSourceMap::HasSource (size_t start, size_t end) const
Definition at line 109 of file wasm-module-sourcemap.cc.
                                                                  {
  return start <= *(offsets.end() - 1) && end > *offsets.begin();
}
References v8::internal::compiler::end(), and offsets.
HasValidEntry()
bool v8::internal::wasm::WasmModuleSourceMap::HasValidEntry (size_t start, size_t addr) const
Definition at line 113 of file wasm-module-sourcemap.cc.
                                                                       {
  std::vector<size_t>::const_iterator up =
      std::upper_bound(offsets.begin(), offsets.end(), addr);
  if (up == offsets.begin()) return false;
  size_t offset_idx = up - offsets.begin() - 1;
  size_t entry_offset = offsets[offset_idx];
  if (entry_offset < start) return false;
  return true;
}
References offsets.
IsValid()
bool v8::internal::wasm::WasmModuleSourceMap::IsValid () const [inline]
Definition at line 45 of file wasm-module-sourcemap.h.
{ return valid_; }
Member Data Documentation
file_idxs
std::vector<size_t> v8::internal::wasm::WasmModuleSourceMap::file_idxs [private]
Definition at line 80 of file wasm-module-sourcemap.h.
Referenced by DecodeMapping(), EstimateCurrentMemoryConsumption(), and GetFilename().
filenames
std::vector<std::string> v8::internal::wasm::WasmModuleSourceMap::filenames [private]
Definition at line 79 of file wasm-module-sourcemap.h.
Referenced by EstimateCurrentMemoryConsumption(), GetFilename(), and WasmModuleSourceMap().
offsets
std::vector<size_t> v8::internal::wasm::WasmModuleSourceMap::offsets [private]
Definition at line 78 of file wasm-module-sourcemap.h.
Referenced by DecodeMapping(), EstimateCurrentMemoryConsumption(), GetFilename(), GetSourceLine(), HasSource(), and HasValidEntry().
source_row
std::vector<size_t> v8::internal::wasm::WasmModuleSourceMap::source_row [private]
Definition at line 81 of file wasm-module-sourcemap.h.
Referenced by DecodeMapping(), EstimateCurrentMemoryConsumption(), and GetSourceLine().
valid_
bool v8::internal::wasm::WasmModuleSourceMap::valid_ = false [private]
Definition at line 85 of file wasm-module-sourcemap.h.
Referenced by WasmModuleSourceMap().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-module-sourcemap.h
/mnt/V8SourceCode/src/wasm/wasm-module-sourcemap.cc