v8::internal::DebugScope Class Reference
#include <debug.h>
Public Member Functions
DebugScope (Debug *debug)
~DebugScope ()
void set_terminate_on_resume ()
base::TimeDelta ElapsedTimeSinceCreation ()
Private Member Functions
Isolate * isolate ()
Private Attributes
Debug * debug_
DebugScope * prev_
StackFrameId break_frame_id_
PostponeInterruptsScope no_interrupts_
bool terminate_on_resume_ = false
base::ElapsedTimer timer_
Detailed Description
Definition at line 739 of file debug.h.
Constructor & Destructor Documentation
DebugScope()
v8::internal::DebugScope::DebugScope (Debug * debug) [explicit]
Definition at line 2954 of file debug.cc.
    : debug_(debug),
      prev_(reinterpret_cast<DebugScope*>(
          base::Relaxed_Load(&debug->thread_local_.current_debug_scope_))),
      no_interrupts_(debug_->isolate_) {
  timer_.Start();
  // Link recursive debugger entry.
  base::Relaxed_Store(&debug_->thread_local_.current_debug_scope_,
                      reinterpret_cast<base::AtomicWord>(this));
  // Store the previous frame id and return value.
  break_frame_id_ = debug_->break_frame_id();
  // Create the new break info. If there is no proper frames there is no break
  // frame id.
  DebuggableStackFrameIterator it(Isolate::Current());
  bool has_frames = !it.done();
  debug_->thread_local_.break_frame_id_ =
      has_frames ? it.frame()->id() : StackFrameId::NO_ID;
  debug_->UpdateState();
}
References v8::internal::Debug::break_frame_id(), v8::internal::Debug::ThreadLocal::break_frame_id_, break_frame_id_, v8::internal::Isolate::Current(), v8::internal::Debug::ThreadLocal::current_debug_scope_, debug_, v8::internal::DebuggableStackFrameIterator::done(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::StackFrame::id(), v8::internal::NO_ID, v8::base::Relaxed_Store(), v8::base::ElapsedTimer::Start(), v8::internal::Debug::thread_local_, timer_, and v8::internal::Debug::UpdateState().
 DebugScope()
v8::internal::DebugScope::~DebugScope ()
Definition at line 2982 of file debug.cc.
                        {
  // Terminate on resume must have been handled by retrieving it, if this is
  // the outer scope.
  if (terminate_on_resume_) {
    if (!prev_) {
      debug_->isolate_->stack_guard()->RequestTerminateExecution();
    } else {
      prev_->set_terminate_on_resume();
    }
  }
  // Leaving this debugger entry.
  base::Relaxed_Store(&debug_->thread_local_.current_debug_scope_,
                      reinterpret_cast<base::AtomicWord>(prev_));
  // Restore to the previous break state.
  debug_->thread_local_.break_frame_id_ = break_frame_id_;
  debug_->UpdateState();
}
References v8::internal::Debug::ThreadLocal::break_frame_id_, break_frame_id_, v8::internal::Debug::ThreadLocal::current_debug_scope_, debug_, v8::internal::Debug::isolate_, prev_, v8::base::Relaxed_Store(), set_terminate_on_resume(), v8::internal::Isolate::stack_guard(), terminate_on_resume_, v8::internal::Debug::thread_local_, and v8::internal::Debug::UpdateState().
Member Function Documentation
ElapsedTimeSinceCreation()
base::TimeDelta v8::internal::DebugScope::ElapsedTimeSinceCreation ()
Definition at line 2978 of file debug.cc.
                                                   {
  return timer_.Elapsed();
}
References v8::base::ElapsedTimer::Elapsed(), and timer_.
Referenced by v8::internal::Debug::NotifyDebuggerPausedEventSent().
isolate()
Isolate* v8::internal::DebugScope::isolate () [inline], [private]
Definition at line 749 of file debug.h.
{ return debug_->isolate_; }
set_terminate_on_resume()
void v8::internal::DebugScope::set_terminate_on_resume ()
Definition at line 2976 of file debug.cc.
{ terminate_on_resume_ = true; }
References terminate_on_resume_.
Referenced by v8::internal::Debug::SetTerminateOnResume(), and ~DebugScope().
Member Data Documentation
break_frame_id_
StackFrameId v8::internal::DebugScope::break_frame_id_ [private]
Definition at line 753 of file debug.h.
Referenced by DebugScope(), and ~DebugScope().
debug_
Debug* v8::internal::DebugScope::debug_ [private]
Definition at line 751 of file debug.h.
Referenced by DebugScope(), and ~DebugScope().
no_interrupts_
PostponeInterruptsScope v8::internal::DebugScope::no_interrupts_ [private]
Definition at line 754 of file debug.h.
prev_
DebugScope* v8::internal::DebugScope::prev_ [private]
Definition at line 752 of file debug.h.
Referenced by ~DebugScope().
terminate_on_resume_
bool v8::internal::DebugScope::terminate_on_resume_ = false [private]
Definition at line 756 of file debug.h.
Referenced by set_terminate_on_resume(), and ~DebugScope().
timer_
base::ElapsedTimer v8::internal::DebugScope::timer_ [private]
Definition at line 760 of file debug.h.
Referenced by DebugScope(), and ElapsedTimeSinceCreation().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/debug.h
/mnt/V8SourceCode/src/debug/debug.cc