v8::internal::GCTracer::Scope Class Reference
#include <gc-tracer.h>
Public Types
enum ScopeId {
TRACER_SCOPES
, FIRST_INCREMENTAL_SCOPE = MC_INCREMENTAL
, LAST_INCREMENTAL_SCOPE = MC_INCREMENTAL_SWEEPING
, FIRST_SCOPE = MC_INCREMENTAL
,
NUMBER_OF_INCREMENTAL_SCOPES
, FIRST_TOP_MC_SCOPE = MC_CLEAR
, LAST_TOP_MC_SCOPE = MC_SWEEP
, FIRST_BACKGROUND_SCOPE = BACKGROUND_YOUNG_ARRAY_BUFFER_SWEEP
,
LAST_BACKGROUND_SCOPE
 }
Public Member Functions
Scope (GCTracer *tracer, ScopeId scope, ThreadKind thread_kind)
~Scope ()
Scope (const Scope &)=delete
Scope & operator= (const Scope &)=delete
Static Public Member Functions
static constexpr const char * Name (ScopeId id)
static constexpr bool NeedsYoungEpoch (ScopeId id)
static constexpr int IncrementalOffset (ScopeId id)
Private Attributes
GCTracer *const tracer_
const ScopeId scope_
const ThreadKind thread_kind_
const base::TimeTicks start_time_
Detailed Description
Definition at line 119 of file gc-tracer.h.
Member Enumeration Documentation
ScopeId
enum v8::internal::GCTracer::Scope::ScopeId
Enumerator
TRACER_SCOPES
FIRST_INCREMENTAL_SCOPE
LAST_INCREMENTAL_SCOPE
FIRST_SCOPE
NUMBER_OF_INCREMENTAL_SCOPES
FIRST_TOP_MC_SCOPE
LAST_TOP_MC_SCOPE
FIRST_BACKGROUND_SCOPE
LAST_BACKGROUND_SCOPE
Definition at line 121 of file gc-tracer.h.
                 {
#define DEFINE_SCOPE(scope) scope,
      TRACER_SCOPES(DEFINE_SCOPE) TRACER_BACKGROUND_SCOPES(DEFINE_SCOPE)
#undef DEFINE_SCOPE
          NUMBER_OF_SCOPES,
      FIRST_INCREMENTAL_SCOPE = MC_INCREMENTAL,
      LAST_INCREMENTAL_SCOPE = MC_INCREMENTAL_SWEEPING,
      FIRST_SCOPE = MC_INCREMENTAL,
      NUMBER_OF_INCREMENTAL_SCOPES =
          LAST_INCREMENTAL_SCOPE - FIRST_INCREMENTAL_SCOPE + 1,
      FIRST_TOP_MC_SCOPE = MC_CLEAR,
      LAST_TOP_MC_SCOPE = MC_SWEEP,
      FIRST_BACKGROUND_SCOPE = BACKGROUND_YOUNG_ARRAY_BUFFER_SWEEP,
      LAST_BACKGROUND_SCOPE =
          SCAVENGER_BACKGROUND_TRACED_HANDLES_COMPUTE_WEAKNESS_PARALLEL
    };
Constructor & Destructor Documentation
Scope() [1/2]
v8::internal::GCTracer::Scope::Scope (GCTracer * tracer, ScopeId scope, ThreadKind thread_kind) [inline]
Definition at line 29 of file gc-tracer-inl.h.
    : tracer_(tracer),
      scope_(scope),
      thread_kind_(thread_kind),
      start_time_(base::TimeTicks::Now()) {
  DCHECK_IMPLIES(thread_kind_ == ThreadKind::kMain,
                 tracer_->heap_->IsMainThread());
#ifdef V8_RUNTIME_CALL_STATS
  if (V8_LIKELY(!TracingFlags::is_runtime_stats_enabled())) return;
  if (thread_kind_ == ThreadKind::kMain) {
    runtime_stats_ = tracer_->heap_->isolate_->counters()->runtime_call_stats();
    runtime_stats_->Enter(&timer_, GCTracer::RCSCounterFromScope(scope));
  } else {
    runtime_call_stats_scope_.emplace(
        tracer->worker_thread_runtime_call_stats());
    runtime_stats_ = runtime_call_stats_scope_->Get();
    runtime_stats_->Enter(&timer_, GCTracer::RCSCounterFromScope(scope));
  }
#endif // defined(V8_RUNTIME_CALL_STATS)
}
References v8::internal::Isolate::counters(), DCHECK_IMPLIES, v8::internal::GCTracer::heap_, v8::internal::Heap::IsMainThread(), v8::internal::Heap::isolate_, v8::internal::kMain, v8::internal::Counters::runtime_call_stats(), thread_kind_, tracer_, and V8_LIKELY.
 Scope()
v8::internal::GCTracer::Scope::~Scope () [inline]
Definition at line 51 of file gc-tracer-inl.h.
                      {
  const base::TimeDelta duration = base::TimeTicks::Now() - start_time_;
  tracer_->AddScopeSample(scope_, duration);
  if (thread_kind_ == ThreadKind::kMain) {
    if (scope_ == ScopeId::MC_INCREMENTAL ||
        scope_ == ScopeId::MC_INCREMENTAL_START) {
      auto* long_task_stats =
          tracer_->heap_->isolate_->GetCurrentLongTaskStats();
      long_task_stats->gc_full_incremental_wall_clock_duration_us +=
          duration.InMicroseconds();
    }
  }
#ifdef V8_RUNTIME_CALL_STATS
  if (V8_LIKELY(runtime_stats_ == nullptr)) return;
  runtime_stats_->Leave(&timer_);
#endif // defined(V8_RUNTIME_CALL_STATS)
}
References v8::internal::duration, v8::internal::kMain, v8::base::TimeTicks::Now(), and V8_LIKELY.
Scope() [2/2]
v8::internal::GCTracer::Scope::Scope (const Scope &) [delete]
Member Function Documentation
IncrementalOffset()
constexpr int v8::internal::GCTracer::Scope::IncrementalOffset (ScopeId id) [static], [constexpr]
Definition at line 96 of file gc-tracer-inl.h.
                                                         {
  DCHECK_LE(FIRST_INCREMENTAL_SCOPE, id);
  DCHECK_GE(LAST_INCREMENTAL_SCOPE, id);
  return id - FIRST_INCREMENTAL_SCOPE;
}
References DCHECK_GE, and DCHECK_LE.
Referenced by v8::internal::GCTracer::AddScopeSample(), and v8::internal::GCTracer::incremental_scope().
Name()
constexpr const char * v8::internal::GCTracer::Scope::Name (ScopeId id) [static], [constexpr]
Definition at line 71 of file gc-tracer-inl.h.
                                                    {
#define CASE(scope) \
  case Scope::scope: \
    return "V8.GC_" #scope;
  switch (id) {
    TRACER_SCOPES(CASE)
    TRACER_BACKGROUND_SCOPES(CASE)
    default:
      return nullptr;
  }
#undef CASE
}
References CASE, TRACER_BACKGROUND_SCOPES, and TRACER_SCOPES.
NeedsYoungEpoch()
constexpr bool v8::internal::GCTracer::Scope::NeedsYoungEpoch (ScopeId id) [static], [constexpr]
Definition at line 84 of file gc-tracer-inl.h.
                                                        {
#define CASE(scope) \
  case Scope::scope: \
    return true;
  switch (id) {
    TRACER_YOUNG_EPOCH_SCOPES(CASE)
    default:
      return false;
  }
#undef CASE
}
References CASE, and TRACER_YOUNG_EPOCH_SCOPES.
Referenced by v8::internal::GCTracer::CurrentEpoch(), and v8::internal::Sweeper::GetTraceIdForFlowEvent().
operator=()
Scope& v8::internal::GCTracer::Scope::operator= (const Scope &) [delete]
Member Data Documentation
scope_
const ScopeId v8::internal::GCTracer::Scope::scope_ [private]
Definition at line 149 of file gc-tracer.h.
start_time_
const base::TimeTicks v8::internal::GCTracer::Scope::start_time_ [private]
Definition at line 151 of file gc-tracer.h.
thread_kind_
const ThreadKind v8::internal::GCTracer::Scope::thread_kind_ [private]
Definition at line 150 of file gc-tracer.h.
Referenced by Scope().
tracer_
GCTracer* const v8::internal::GCTracer::Scope::tracer_ [private]
Definition at line 148 of file gc-tracer.h.
Referenced by Scope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/gc-tracer.h
/mnt/V8SourceCode/src/heap/gc-tracer-inl.h