cppgc::internal::anonymous_namespace{sweeper.cc}::InlinedFinalizationBuilder< FreeHandler > Class Template Reference
Public Member Functions
InlinedFinalizationBuilder (BasePage &page, PageAllocator &page_allocator)
void AddFinalizer (HeapObjectHeader *header, size_t size)
void AddFreeListEntry (Address start, size_t size)
ResultType && GetResult (bool is_empty)
Additional Inherited Members
Detailed Description
template<typename FreeHandler>
class cppgc::internal::anonymous_namespace{sweeper.cc}::InlinedFinalizationBuilder< FreeHandler >
Definition at line 262 of file sweeper.cc.
Constructor & Destructor Documentation
InlinedFinalizationBuilder()
template<typename FreeHandler >
cppgc::internal::anonymous_namespace{sweeper.cc}::InlinedFinalizationBuilder< FreeHandler >::InlinedFinalizationBuilder (BasePage & page, PageAllocator & page_allocator) [inline]
Definition at line 265 of file sweeper.cc.
      : FreeHandler(page_allocator,
                    NormalPageSpace::From(page.space()).free_list(), page) {}
Member Function Documentation
AddFinalizer()
template<typename FreeHandler >
void cppgc::internal::anonymous_namespace{sweeper.cc}::InlinedFinalizationBuilder< FreeHandler >::AddFinalizer (HeapObjectHeader * header, size_t size) [inline]
Definition at line 269 of file sweeper.cc.
                                                           {
    header->Finalize();
    SetMemoryInaccessible(header, size);
  }
References cppgc::internal::HeapObjectHeader::Finalize(), cppgc::internal::SetMemoryInaccessible(), and size().
AddFreeListEntry()
template<typename FreeHandler >
void cppgc::internal::anonymous_namespace{sweeper.cc}::InlinedFinalizationBuilder< FreeHandler >::AddFreeListEntry (Address start, size_t size) [inline]
Definition at line 274 of file sweeper.cc.
                                                    {
    FreeHandler::Free({start, size});
    result_.largest_new_free_list_entry =
        std::max(result_.largest_new_free_list_entry, size);
  }
References v8::base::Free(), and size().
GetResult()
template<typename FreeHandler >
ResultType&& cppgc::internal::anonymous_namespace{sweeper.cc}::InlinedFinalizationBuilder< FreeHandler >::GetResult (bool is_empty) [inline]
Definition at line 280 of file sweeper.cc.
                                        {
    result_.is_empty = is_empty;
    return std::move(result_);
  }
References v8::internal::compiler::turboshaft::is_empty(), and cppgc::internal::anonymous_namespace{sweeper.cc}::InlinedFinalizationBuilderBase::ResultType::is_empty.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/sweeper.cc