v8::Number Class Reference
A JavaScript number value (ECMA-262, 4.3.20)
#include <v8-primitive.h>
Public Member Functions
double Value () const
Static Public Member Functions
static Local< Number > New (Isolate *isolate, double value)
static Number * Cast (v8::Data *data)
Private Member Functions
Number ()
Static Private Member Functions
static void CheckCast (v8::Data *that)
Detailed Description
A JavaScript number value (ECMA-262, 4.3.20)
Definition at line 848 of file v8-primitive.h.
Constructor & Destructor Documentation
Number()
v8::Number::Number () [private]
Member Function Documentation
Cast()
static Number* v8::Number::Cast (v8::Data * data) [inline], [static]
Definition at line 852 of file v8-primitive.h.
                                              {
#ifdef V8_ENABLE_CHECKS
    CheckCast(data);
#endif
    return static_cast<Number*>(data);
  }
CheckCast()
void v8::Number::CheckCast (v8::Data * that) [static], [private]
Definition at line 3928 of file api.cc.
                                     {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsNumber(*obj), "v8::Number::Cast()",
                  "Value is not a Number");
}
References v8::Utils::ApiCheck(), v8::internal::IsNumber(), and v8::Utils::OpenDirectHandle().
New()
Local< Number > v8::Number::New (Isolate * isolate, double value) [static]
Definition at line 9531 of file api.cc.
                                                             {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  if (std::isnan(value)) {
    // Introduce only canonical NaN value into the VM, to avoid signaling NaNs.
    value = std::numeric_limits<double>::quiet_NaN();
  }
  i::DirectHandle<i::Object> result = i_isolate->factory()->NewNumber(value);
  return Utils::NumberToLocal(result);
}
References v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewNumber(), v8::base::internal::result, and v8::internal::value.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::add(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::Add32BitIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAll32BitIntSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllAnnotateSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllTypedArraySlowCallback(), v8::internal::AddCounter(), v8::internal::AddNumber(), v8::internal::AddNumber64(), v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append(), v8::Shell::AsyncHooksExecutionAsyncId(), v8::Shell::AsyncHooksTriggerAsyncId(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::ClampCompareSlowCallback(), v8::Shell::CreateD8Template(), v8::Shell::CreateEvaluationContext(), v8::internal::ArrayProxy::CreateTemplate(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::FastCallCount(), v8::Shell::NodeTypeCallback(), v8::Shell::PerformanceMark(), v8::Shell::PerformanceMeasure(), v8::ReturnValue< T >::Set(), v8::Shell::SetTimeout(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::SlowCallCount(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsNumberSlowCallback(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsNumberSlowCallback(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionGetArgImpl().
Value()
double v8::Number::Value () const
Definition at line 6184 of file api.cc.
                           {
  return i::Object::NumberValue(*Utils::OpenDirectHandle(this));
}
References v8::internal::Object::NumberValue(), and v8::Utils::OpenDirectHandle().
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumInt64AsNumberSlowCallback(), and v8::anonymous_namespace{d8-test.cc}::FastCApiObject::sumUint64AsNumberSlowCallback().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-primitive.h
/mnt/V8SourceCode/src/api/api.cc