v8::internal::JsonStringifier::SimplePropertyKeyCache Class Reference
Public Member Functions
SimplePropertyKeyCache (Isolate *isolate)
~SimplePropertyKeyCache ()
void TryInsert (Tagged< String > string)
bool Contains (Tagged< String > string)
Private Member Functions
size_t GetIndex (Tagged< String > string)
Tagged_t MaybeCompress (Tagged< String > string)
void Clear ()
Static Private Member Functions
static void UpdatePointersCallback (void *cache)
Private Attributes
Isolate * isolate_
Tagged_t keys_ [kSize]
Static Private Attributes
static constexpr size_t kSizeBits = 6
static constexpr size_t kSize = 1 << kSizeBits
static constexpr size_t kIndexMask = kSize - 1
Detailed Description
Definition at line 339 of file json-stringifier.cc.
Constructor & Destructor Documentation
SimplePropertyKeyCache()
v8::internal::JsonStringifier::SimplePropertyKeyCache::SimplePropertyKeyCache (Isolate * isolate) [inline], [explicit]
Definition at line 341 of file json-stringifier.cc.
                                                      : isolate_(isolate) {
      Clear();
      isolate->main_thread_local_heap()->AddGCEpilogueCallback(
          UpdatePointersCallback, this);
    }
References v8::internal::LocalHeap::AddGCEpilogueCallback(), Clear(), v8::internal::Isolate::main_thread_local_heap(), and UpdatePointersCallback().
 SimplePropertyKeyCache()
v8::internal::JsonStringifier::SimplePropertyKeyCache::~SimplePropertyKeyCache () [inline]
Definition at line 347 of file json-stringifier.cc.
                              {
      isolate_->main_thread_local_heap()->RemoveGCEpilogueCallback(
          UpdatePointersCallback, this);
    }
References isolate_, v8::internal::Isolate::main_thread_local_heap(), v8::internal::LocalHeap::RemoveGCEpilogueCallback(), and UpdatePointersCallback().
Member Function Documentation
Clear()
void v8::internal::JsonStringifier::SimplePropertyKeyCache::Clear () [inline], [private]
Definition at line 376 of file json-stringifier.cc.
{ MemsetTagged(keys_, Smi::zero(), kSize); }
References keys_, kSize, v8::internal::MemsetTagged(), and v8::internal::Smi::zero().
Referenced by SimplePropertyKeyCache(), and UpdatePointersCallback().
Contains()
bool v8::internal::JsonStringifier::SimplePropertyKeyCache::Contains (Tagged< String > string) [inline]
Definition at line 359 of file json-stringifier.cc.
                                         {
      return keys_[GetIndex(string)] == MaybeCompress(string);
    }
References GetIndex(), keys_, and MaybeCompress().
Referenced by v8::internal::JsonStringifier::TrySerializeSimplePropertyKey().
GetIndex()
size_t v8::internal::JsonStringifier::SimplePropertyKeyCache::GetIndex (Tagged< String > string) [inline], [private]
Definition at line 364 of file json-stringifier.cc.
                                           {
      // Short strings are 16 bytes long in pointer-compression builds, so the
      // lower four bits of the pointer may not provide much entropy.
      return (string.ptr() >> 4) & kIndexMask;
    }
References kIndexMask.
Referenced by Contains(), and TryInsert().
MaybeCompress()
Tagged_t v8::internal::JsonStringifier::SimplePropertyKeyCache::MaybeCompress (Tagged< String > string) [inline], [private]
Definition at line 370 of file json-stringifier.cc.
                                                  {
      return COMPRESS_POINTERS_BOOL
                 ? V8HeapCompressionScheme::CompressObject(string.ptr())
                 : static_cast<Tagged_t>(string.ptr());
    }
References COMPRESS_POINTERS_BOOL, and v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressObject().
Referenced by Contains(), and TryInsert().
TryInsert()
void v8::internal::JsonStringifier::SimplePropertyKeyCache::TryInsert (Tagged< String > string) [inline]
Definition at line 352 of file json-stringifier.cc.
                                          {
      ReadOnlyRoots roots(isolate_);
      if (string->map() == roots.internalized_one_byte_string_map()) {
        keys_[GetIndex(string)] = MaybeCompress(string);
      }
    }
References GetIndex(), isolate_, keys_, MaybeCompress(), and v8::internal::string.
Referenced by v8::internal::JsonStringifier::SerializeDeferredKey().
UpdatePointersCallback()
static void v8::internal::JsonStringifier::SimplePropertyKeyCache::UpdatePointersCallback (void * cache) [inline], [static], [private]
Definition at line 378 of file json-stringifier.cc.
                                                    {
      reinterpret_cast<SimplePropertyKeyCache*>(cache)->Clear();
    }
References Clear().
Referenced by SimplePropertyKeyCache(), and ~SimplePropertyKeyCache().
Member Data Documentation
isolate_
Isolate* v8::internal::JsonStringifier::SimplePropertyKeyCache::isolate_ [private]
Definition at line 386 of file json-stringifier.cc.
Referenced by TryInsert(), and ~SimplePropertyKeyCache().
keys_
Tagged_t v8::internal::JsonStringifier::SimplePropertyKeyCache::keys_[kSize] [private]
Definition at line 387 of file json-stringifier.cc.
Referenced by Clear(), Contains(), and TryInsert().
kIndexMask
constexpr size_t v8::internal::JsonStringifier::SimplePropertyKeyCache::kIndexMask = kSize - 1 [static], [constexpr], [private]
Definition at line 384 of file json-stringifier.cc.
Referenced by GetIndex().
kSize
constexpr size_t v8::internal::JsonStringifier::SimplePropertyKeyCache::kSize = 1 << kSizeBits [static], [constexpr], [private]
Definition at line 383 of file json-stringifier.cc.
Referenced by Clear().
kSizeBits
constexpr size_t v8::internal::JsonStringifier::SimplePropertyKeyCache::kSizeBits = 6 [static], [constexpr], [private]
Definition at line 382 of file json-stringifier.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/json/json-stringifier.cc