v8::internal::compiler::InstructionSequence Class Reference
#include <instruction.h>
Public Types
using const_iterator = Instructions::const_iterator
using Immediates = ZoneVector< Constant >
using RpoImmediates = ZoneVector< RpoNumber >
Public Member Functions
InstructionSequence (Isolate *isolate, Zone *zone, InstructionBlocks *instruction_blocks)
InstructionSequence (const InstructionSequence &)=delete
InstructionSequence & operator= (const InstructionSequence &)=delete
int NextVirtualRegister ()
int VirtualRegisterCount () const
const InstructionBlocks & instruction_blocks () const
const InstructionBlocks & ao_blocks () const
int InstructionBlockCount () const
InstructionBlock * InstructionBlockAt (RpoNumber rpo_number)
int LastLoopInstructionIndex (const InstructionBlock *block)
const InstructionBlock * InstructionBlockAt (RpoNumber rpo_number) const
InstructionBlock * GetInstructionBlock (int instruction_index) const
MachineRepresentation GetRepresentation (int virtual_register) const
void MarkAsRepresentation (MachineRepresentation rep, int virtual_register)
bool IsReference (int virtual_register) const
bool IsFP (int virtual_register) const
int representation_mask () const
bool HasFPVirtualRegisters () const
bool HasSimd128VirtualRegisters () const
Instruction * GetBlockStart (RpoNumber rpo) const
const_iterator begin () const
const_iterator end () const
const Instructions & instructions () const
int LastInstructionIndex () const
Instruction * InstructionAt (int index) const
Isolate * isolate () const
const ReferenceMaps * reference_maps () const
Zone * zone () const
int AddInstruction (Instruction *instr)
void StartBlock (RpoNumber rpo)
void EndBlock (RpoNumber rpo)
void AddConstant (int virtual_register, Constant constant)
Constant GetConstant (int virtual_register) const
Immediates & immediates ()
RpoImmediates & rpo_immediates ()
ImmediateOperand AddImmediate (const Constant &constant)
Constant GetImmediate (const ImmediateOperand *op) const
int AddDeoptimizationEntry (FrameStateDescriptor *descriptor, DeoptimizeKind kind, DeoptimizeReason reason, NodeId node_id, FeedbackSource const &feedback)
DeoptimizationEntry const & GetDeoptimizationEntry (int deoptimization_id)
int GetDeoptimizationEntryCount () const
RpoNumber InputRpo (Instruction *instr, size_t index)
bool GetSourcePosition (const Instruction *instr, SourcePosition *result) const
void SetSourcePosition (const Instruction *instr, SourcePosition value)
bool ContainsCall () const
void Print () const
void PrintBlock (int block_id) const
void ValidateEdgeSplitForm () const
void ValidateDeferredBlockExitPaths () const
void ValidateDeferredBlockEntryPaths () const
void ValidateSSA () const
void RecomputeAssemblyOrderForTesting ()
void IncreaseRpoForTesting (size_t rpo_count)
Static Public Member Functions
static InstructionBlocks * InstructionBlocksFor (Zone *zone, const Schedule *schedule)
static InstructionBlocks * InstructionBlocksFor (Zone *zone, const turboshaft::Graph &graph)
static MachineRepresentation DefaultRepresentation ()
static void SetRegisterConfigurationForTesting (const RegisterConfiguration *regConfig)
static void ClearRegisterConfigurationForTesting ()
Private Types
using SourcePositionMap = ZoneAbslFlatHashMap< const Instruction *, SourcePosition >
Private Member Functions
void ComputeAssemblyOrder ()
Static Private Member Functions
static const RegisterConfiguration * RegisterConfigurationForTesting ()
Private Attributes
Isolate * isolate_
Zone *const zone_
InstructionBlocks *const instruction_blocks_
InstructionBlocks * ao_blocks_
SourcePositionMap source_positions_
ConstantMap constants_
Immediates immediates_
RpoImmediates rpo_immediates_
Instructions instructions_
int next_virtual_register_
ReferenceMaps reference_maps_
ZoneVector< MachineRepresentation > representations_
int representation_mask_
DeoptimizationVector deoptimization_entries_
InstructionBlock * current_block_
Static Private Attributes
static const RegisterConfiguration * registerConfigurationForTesting_ = nullptr
Friends
V8_EXPORT_PRIVATE std::ostream & operator<< (std::ostream &, const InstructionSequence &)
Detailed Description
Definition at line 1829 of file instruction.h.
Member Typedef Documentation
const_iterator
using v8::internal::compiler::InstructionSequence::const_iterator = Instructions::const_iterator
Definition at line 1902 of file instruction.h.
Immediates
using v8::internal::compiler::InstructionSequence::Immediates = ZoneVector<Constant>
Definition at line 1939 of file instruction.h.
RpoImmediates
using v8::internal::compiler::InstructionSequence::RpoImmediates = ZoneVector<RpoNumber>
Definition at line 1942 of file instruction.h.
SourcePositionMap
using v8::internal::compiler::InstructionSequence::SourcePositionMap = ZoneAbslFlatHashMap<const Instruction*, SourcePosition> [private]
Definition at line 2041 of file instruction.h.
Constructor & Destructor Documentation
InstructionSequence() [1/2]
v8::internal::compiler::InstructionSequence::InstructionSequence (Isolate * isolate, Zone * zone, InstructionBlocks * instruction_blocks)
Definition at line 964 of file instruction.cc.
    : isolate_(isolate),
      zone_(instruction_zone),
      instruction_blocks_(instruction_blocks),
      ao_blocks_(nullptr),
      // Pre-allocate the hash map of source positions based on the block count.
      // (The actual number of instructions is only known after instruction
      // selection, but should at least correlate with the block count.)
      source_positions_(zone(), instruction_blocks->size() * 2),
      // Avoid collisions for functions with 256 or less constant vregs.
      constants_(zone(), 256),
      immediates_(zone()),
      rpo_immediates_(instruction_blocks->size(), zone()),
      instructions_(zone()),
      next_virtual_register_(0),
      reference_maps_(zone()),
      representations_(zone()),
      representation_mask_(0),
      deoptimization_entries_(zone()),
      current_block_(nullptr) {
  ComputeAssemblyOrder();
}
References ComputeAssemblyOrder().
InstructionSequence() [2/2]
v8::internal::compiler::InstructionSequence::InstructionSequence (const InstructionSequence &) [delete]
Member Function Documentation
AddConstant()
void v8::internal::compiler::InstructionSequence::AddConstant (int virtual_register, Constant constant) [inline]
Definition at line 1925 of file instruction.h.
                                                            {
    // TODO(titzer): allow RPO numbers as constants?
    DCHECK_NE(Constant::kRpoNumber, constant.type());
    DCHECK(virtual_register >= 0 && virtual_register < next_virtual_register_);
    DCHECK(constants_.find(virtual_register) == constants_.end());
    constants_.emplace(virtual_register, constant);
  }
References v8::internal::DCHECK(), DCHECK_NE, v8::internal::compiler::Constant::kRpoNumber, v8::internal::compiler::Constant::type(), and v8::internal::compiler::ConstantOperand::virtual_register().
Referenced by v8::internal::compiler::OperandGenerator::DefineAsConstant().
AddDeoptimizationEntry()
int v8::internal::compiler::InstructionSequence::AddDeoptimizationEntry (FrameStateDescriptor * descriptor, DeoptimizeKind kind, DeoptimizeReason reason, NodeId node_id, FeedbackSource const & feedback)
Definition at line 1085 of file instruction.cc.
                                                                             {
  int deoptimization_id = static_cast<int>(deoptimization_entries_.size());
  deoptimization_entries_.push_back(
      DeoptimizationEntry(descriptor, kind, reason, node_id, feedback));
  return deoptimization_id;
}
References deoptimization_entries_, v8::internal::ZoneVector< T >::push_back(), and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::compiler::InstructionSelector::AppendDeoptimizeArguments(), and v8::internal::compiler::InstructionSelector::InitializeCallBuffer().
AddImmediate()
ImmediateOperand v8::internal::compiler::InstructionSequence::AddImmediate (const Constant & constant) [inline]
Definition at line 1945 of file instruction.h.
                                                          {
    if (RelocInfo::IsNoInfo(constant.rmode())) {
      if (constant.type() == Constant::kRpoNumber) {
        // Ideally we would inline RPO numbers into the operand, however jump-
        // threading modifies RPO values and so we indirect through a vector
        // of rpo_immediates to enable rewriting. We keep this seperate from the
        // immediates vector so that we don't repeatedly push the same rpo
        // number.
        RpoNumber rpo_number = constant.ToRpoNumber();
        DCHECK(!rpo_immediates().at(rpo_number.ToSize()).IsValid() ||
               rpo_immediates().at(rpo_number.ToSize()) == rpo_number);
        rpo_immediates()[rpo_number.ToSize()] = rpo_number;
        return ImmediateOperand(ImmediateOperand::INDEXED_RPO,
                                rpo_number.ToInt());
      } else if (constant.type() == Constant::kInt32) {
        return ImmediateOperand(ImmediateOperand::INLINE_INT32,
                                constant.ToInt32());
      } else if (constant.type() == Constant::kInt64 &&
                 constant.FitsInInt32()) {
        return ImmediateOperand(ImmediateOperand::INLINE_INT64,
                                constant.ToInt32());
      }
    }
    int index = static_cast<int>(immediates_.size());
    immediates_.push_back(constant);
    return ImmediateOperand(ImmediateOperand::INDEXED_IMM, index);
  }
References v8::internal::DCHECK(), v8::internal::compiler::Constant::FitsInInt32(), v8::internal::index, v8::internal::compiler::ImmediateOperand::INDEXED_IMM, v8::internal::compiler::ImmediateOperand::INDEXED_RPO, v8::internal::compiler::ImmediateOperand::INLINE_INT32, v8::internal::compiler::ImmediateOperand::INLINE_INT64, v8::internal::RelocInfo::IsNoInfo(), v8::internal::compiler::Constant::kInt32, v8::internal::compiler::Constant::kInt64, v8::internal::compiler::Constant::kRpoNumber, v8::internal::compiler::Constant::rmode(), v8::internal::compiler::RpoNumber::ToInt(), v8::internal::compiler::Constant::ToInt32(), v8::internal::compiler::Constant::ToRpoNumber(), v8::internal::compiler::RpoNumber::ToSize(), and v8::internal::compiler::Constant::type().
Referenced by v8::internal::compiler::OperandGenerator::Label(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseImmediate64(), and v8::internal::compiler::OperandGenerator::UseNegatedImmediate().
AddInstruction()
int v8::internal::compiler::InstructionSequence::AddInstruction (Instruction * instr)
Definition at line 1016 of file instruction.cc.
                                                          {
  DCHECK_NOT_NULL(current_block_);
  int index = static_cast<int>(instructions_.size());
  instr->set_block(current_block_);
  instructions_.push_back(instr);
  if (instr->NeedsReferenceMap()) {
    DCHECK_NULL(instr->reference_map());
    ReferenceMap* reference_map = zone()->New<ReferenceMap>(zone());
    reference_map->set_instruction_position(index);
    instr->set_reference_map(reference_map);
    reference_maps_.push_back(reference_map);
  }
  return index;
}
References current_block_, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::index, instructions_, v8::internal::compiler::Instruction::NeedsReferenceMap(), v8::internal::Zone::New(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::Instruction::reference_map(), reference_maps_, v8::internal::compiler::Instruction::set_block(), v8::internal::compiler::ReferenceMap::set_instruction_position(), v8::internal::compiler::Instruction::set_reference_map(), v8::internal::ZoneVector< T >::size(), and zone().
Referenced by v8::internal::compiler::InstructionScheduler::AddInstruction(), v8::internal::compiler::InstructionSelector::AddInstruction(), v8::internal::compiler::InstructionSelector::AddTerminator(), and v8::internal::compiler::InstructionScheduler::Schedule().
ao_blocks()
const InstructionBlocks& v8::internal::compiler::InstructionSequence::ao_blocks () const [inline]
Definition at line 1848 of file instruction.h.
{ return *ao_blocks_; }
begin()
const_iterator v8::internal::compiler::InstructionSequence::begin () const [inline]
Definition at line 1903 of file instruction.h.
{ return instructions_.begin(); }
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::VerifyAssignment().
ClearRegisterConfigurationForTesting()
static void v8::internal::compiler::InstructionSequence::ClearRegisterConfigurationForTesting () [static]
ComputeAssemblyOrder()
void v8::internal::compiler::InstructionSequence::ComputeAssemblyOrder () [private]
Definition at line 905 of file instruction.cc.
                                               {
  int ao = 0;
  RpoNumber invalid = RpoNumber::Invalid();
  ao_blocks_ = zone()->AllocateArray<InstructionBlocks>(1);
  new (ao_blocks_) InstructionBlocks(zone());
  ao_blocks_->reserve(instruction_blocks_->size());
  // Place non-deferred blocks.
  for (InstructionBlock* const block : *instruction_blocks_) {
    DCHECK_NOT_NULL(block);
    if (block->IsDeferred()) continue; // skip deferred blocks.
    if (block->ao_number() != invalid) continue; // loop rotated.
    if (block->IsLoopHeader()) {
      bool header_align = true;
      if (v8_flags.turbo_loop_rotation) {
        // Perform loop rotation for non-deferred loops.
        InstructionBlock* loop_end =
            instruction_blocks_->at(block->loop_end().ToSize() - 1);
        if (!loop_end->IsDeferred() && /* Ignore deferred loop ends */
            loop_end->SuccessorCount() == 1 && /* ends with goto */
            loop_end != block /* not a degenerate infinite loop */) {
          // If the last block has an unconditional jump back to the header,
          // then move it to be in front of the header in the assembly order.
          DCHECK_EQ(block->rpo_number(), loop_end->successors()[0]);
          loop_end->set_ao_number(RpoNumber::FromInt(ao++));
          ao_blocks_->push_back(loop_end);
          // This block will be the new machine-level loop header, so align
          // this block instead of the loop header block.
          loop_end->set_loop_header_alignment(true);
          header_align = false;
        }
      }
      block->set_loop_header_alignment(header_align);
    }
    if (block->loop_header().IsValid() && block->IsTableSwitchTarget()) {
      block->set_code_target_alignment(true);
    }
    block->set_ao_number(RpoNumber::FromInt(ao++));
    ao_blocks_->push_back(block);
  }
  // Add all leftover (deferred) blocks.
  for (InstructionBlock* const block : *instruction_blocks_) {
    if (block->ao_number() == invalid) {
      block->set_ao_number(RpoNumber::FromInt(ao++));
      ao_blocks_->push_back(block);
    }
  }
  DCHECK_EQ(instruction_blocks_->size(), ao);
}
References v8::internal::Zone::AllocateArray(), ao_blocks_, v8::internal::ZoneVector< T >::at(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::compiler::RpoNumber::FromInt(), instruction_blocks_, v8::internal::compiler::RpoNumber::Invalid(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::reserve(), v8::internal::compiler::InstructionBlock::set_ao_number(), v8::internal::compiler::InstructionBlock::set_loop_header_alignment(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::InstructionBlock::SuccessorCount(), v8::internal::compiler::InstructionBlock::successors(), v8::internal::v8_flags, and zone().
Referenced by InstructionSequence(), and RecomputeAssemblyOrderForTesting().
ContainsCall()
bool v8::internal::compiler::InstructionSequence::ContainsCall () const [inline]
Definition at line 2009 of file instruction.h.
                            {
    for (Instruction* instr : instructions_) {
      if (instr->IsCall()) return true;
    }
    return false;
  }
DefaultRepresentation()
static MachineRepresentation v8::internal::compiler::InstructionSequence::DefaultRepresentation () [inline], [static]
Definition at line 1871 of file instruction.h.
                                                       {
    return MachineType::PointerRepresentation();
  }
References v8::internal::MachineType::PointerRepresentation().
Referenced by v8::internal::compiler::ConstraintBuilder::AllocateFixed(), v8::internal::compiler::FilterRepresentation(), v8::internal::compiler::LiveRangeBuilder::FixedLiveRangeFor(), GetRepresentation(), and MarkAsRepresentation().
end()
const_iterator v8::internal::compiler::InstructionSequence::end () const [inline]
Definition at line 1904 of file instruction.h.
{ return instructions_.end(); }
Referenced by EndBlock().
EndBlock()
void v8::internal::compiler::InstructionSequence::EndBlock (RpoNumber rpo)
Definition at line 1007 of file instruction.cc.
                                                {
  int end = static_cast<int>(instructions_.size());
  DCHECK_EQ(current_block_->rpo_number(), rpo);
  CHECK(current_block_->code_start() >= 0 &&
        current_block_->code_start() < end);
  current_block_->set_code_end(end);
  current_block_ = nullptr;
}
References CHECK, v8::internal::compiler::InstructionBlock::code_start(), current_block_, DCHECK_EQ, end(), instructions_, v8::internal::compiler::InstructionBlock::rpo_number(), v8::internal::compiler::InstructionBlock::set_code_end(), and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::compiler::InstructionScheduler::EndBlock(), and v8::internal::compiler::InstructionSelector::EndBlock().
GetBlockStart()
Instruction * v8::internal::compiler::InstructionSequence::GetBlockStart (RpoNumber rpo) const
Definition at line 995 of file instruction.cc.
                                                                   {
  const InstructionBlock* block = InstructionBlockAt(rpo);
  return InstructionAt(block->code_start());
}
References v8::internal::compiler::InstructionBlock::code_start(), InstructionAt(), and InstructionBlockAt().
GetConstant()
Constant v8::internal::compiler::InstructionSequence::GetConstant (int virtual_register) const [inline]
Definition at line 1932 of file instruction.h.
                                                   {
    auto it = constants_.find(virtual_register);
    DCHECK(it != constants_.end());
    DCHECK_EQ(virtual_register, it->first);
    return it->second;
  }
References v8::internal::DCHECK(), DCHECK_EQ, and v8::internal::compiler::ConstantOperand::virtual_register().
Referenced by InputRpo(), and v8::internal::compiler::InstructionOperandConverter::ToConstant().
GetDeoptimizationEntry()
DeoptimizationEntry const & v8::internal::compiler::InstructionSequence::GetDeoptimizationEntry (int deoptimization_id)
Definition at line 1094 of file instruction.cc.
                  {
  return deoptimization_entries_[state_id];
}
References deoptimization_entries_.
Referenced by v8::internal::compiler::CodeGenerator::GetDeoptimizationEntry().
GetDeoptimizationEntryCount()
int v8::internal::compiler::InstructionSequence::GetDeoptimizationEntryCount () const [inline]
Definition at line 1999 of file instruction.h.
                                          {
    return static_cast<int>(deoptimization_entries_.size());
  }
GetImmediate()
Constant v8::internal::compiler::InstructionSequence::GetImmediate (const ImmediateOperand * op) const [inline]
Definition at line 1973 of file instruction.h.
                                                          {
    switch (op->type()) {
      case ImmediateOperand::INLINE_INT32:
        return Constant(op->inline_int32_value());
      case ImmediateOperand::INLINE_INT64:
        return Constant(op->inline_int64_value());
      case ImmediateOperand::INDEXED_RPO: {
        int index = op->indexed_value();
        DCHECK_LE(0, index);
        DCHECK_GT(rpo_immediates_.size(), index);
        return Constant(rpo_immediates_[index]);
      }
      case ImmediateOperand::INDEXED_IMM: {
        int index = op->indexed_value();
        DCHECK_LE(0, index);
        DCHECK_GT(immediates_.size(), index);
        return immediates_[index];
      }
    }
    UNREACHABLE();
  }
References DCHECK_GT, DCHECK_LE, v8::internal::index, v8::internal::compiler::ImmediateOperand::INDEXED_IMM, v8::internal::compiler::ImmediateOperand::INDEXED_RPO, v8::internal::compiler::ImmediateOperand::indexed_value(), v8::internal::compiler::ImmediateOperand::INLINE_INT32, v8::internal::compiler::ImmediateOperand::inline_int32_value(), v8::internal::compiler::ImmediateOperand::INLINE_INT64, v8::internal::compiler::ImmediateOperand::inline_int64_value(), v8::internal::compiler::ImmediateOperand::type(), and v8::internal::UNREACHABLE().
Referenced by InputRpo(), v8::internal::compiler::FrameElider::MarkBlocks(), and v8::internal::compiler::InstructionOperandConverter::ToConstant().
GetInstructionBlock()
InstructionBlock* v8::internal::compiler::InstructionSequence::GetInstructionBlock (int instruction_index) const [inline]
Definition at line 1867 of file instruction.h.
                                                                     {
    return instructions()[instruction_index]->block();
  }
Referenced by v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg(), v8::internal::compiler::LinearScanAllocator::AllocateRegisters(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::RegisterAllocationData::IsBlockBoundary(), and v8::internal::compiler::RegisterAllocationData::RangesDefinedInDeferredStayInDeferred().
GetRepresentation()
MachineRepresentation v8::internal::compiler::InstructionSequence::GetRepresentation (int virtual_register) const
Definition at line 1061 of file instruction.cc.
                                {
  DCHECK_LE(0, virtual_register);
  DCHECK_LT(virtual_register, VirtualRegisterCount());
  if (virtual_register >= static_cast<int>(representations_.size())) {
    return DefaultRepresentation();
  }
  return representations_[virtual_register];
}
References DCHECK_LE, DCHECK_LT, DefaultRepresentation(), representations_, v8::internal::ZoneVector< T >::size(), and VirtualRegisterCount().
Referenced by v8::internal::compiler::RegisterAllocationData::RepresentationFor().
GetSourcePosition()
bool v8::internal::compiler::InstructionSequence::GetSourcePosition (const Instruction * instr, SourcePosition * result) const
Definition at line 1108 of file instruction.cc.
                                                                          {
  auto it = source_positions_.find(instr);
  if (it == source_positions_.end()) return false;
  *result = it->second;
  return true;
}
References v8::base::internal::result, and source_positions_.
HasFPVirtualRegisters()
bool v8::internal::compiler::InstructionSequence::HasFPVirtualRegisters () const [inline]
Definition at line 1884 of file instruction.h.
                                     {
    constexpr int kFPRepMask =
        RepresentationBit(MachineRepresentation::kFloat16) |
        RepresentationBit(MachineRepresentation::kFloat32) |
        RepresentationBit(MachineRepresentation::kFloat64) |
        RepresentationBit(MachineRepresentation::kSimd128) |
        RepresentationBit(MachineRepresentation::kSimd256);
    return (representation_mask() & kFPRepMask) != 0;
  }
References v8::internal::kFloat16, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kSimd128, v8::internal::kSimd256, and v8::internal::RepresentationBit().
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
HasSimd128VirtualRegisters()
bool v8::internal::compiler::InstructionSequence::HasSimd128VirtualRegisters () const [inline]
Definition at line 1894 of file instruction.h.
                                          {
    constexpr int kSimd128RepMask =
        RepresentationBit(MachineRepresentation::kSimd128);
    return (representation_mask() & kSimd128RepMask) != 0;
  }
References v8::internal::kSimd128, and v8::internal::RepresentationBit().
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
immediates()
Immediates& v8::internal::compiler::InstructionSequence::immediates () [inline]
Definition at line 1940 of file instruction.h.
{ return immediates_; }
IncreaseRpoForTesting()
void v8::internal::compiler::InstructionSequence::IncreaseRpoForTesting (size_t rpo_count) [inline]
Definition at line 2032 of file instruction.h.
                                               {
    DCHECK_GE(rpo_count, rpo_immediates().size());
    rpo_immediates().resize(rpo_count);
  }
References DCHECK_GE, and size().
InputRpo()
RpoNumber v8::internal::compiler::InstructionSequence::InputRpo (Instruction * instr, size_t index)
Definition at line 1099 of file instruction.cc.
                                                                        {
  InstructionOperand* operand = instr->InputAt(index);
  Constant constant =
      operand->IsImmediate()
          ? GetImmediate(ImmediateOperand::cast(operand))
          : GetConstant(ConstantOperand::cast(operand)->virtual_register());
  return constant.ToRpoNumber();
}
References GetConstant(), GetImmediate(), v8::internal::index, v8::internal::compiler::Instruction::InputAt(), and v8::internal::compiler::Constant::ToRpoNumber().
instruction_blocks()
const InstructionBlocks& v8::internal::compiler::InstructionSequence::instruction_blocks () const [inline]
Definition at line 1844 of file instruction.h.
                                                      {
    return *instruction_blocks_;
  }
Referenced by v8::internal::compiler::SpillPlacer::GetOrCreateIndexForLatestVreg(), v8::internal::compiler::turboshaft::PipelineData::InitializeInstructionComponent(), v8::internal::compiler::TFPipelineData::InitializeInstructionSequence(), v8::internal::compiler::FrameElider::instruction_blocks(), v8::internal::compiler::operator<<(), ValidateDeferredBlockEntryPaths(), ValidateDeferredBlockExitPaths(), ValidateEdgeSplitForm(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
InstructionAt()
Instruction* v8::internal::compiler::InstructionSequence::InstructionAt (int index) const [inline]
Definition at line 1910 of file instruction.h.
                                              {
    DCHECK_LE(0, index);
    DCHECK_GT(instructions_.size(), index);
    return instructions_[index];
  }
References DCHECK_GT, DCHECK_LE, and v8::internal::index.
Referenced by v8::internal::compiler::RegisterAllocationData::AddGapMove(), v8::internal::compiler::ConstraintBuilder::AllocateFixed(), v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::compiler::TopLevelLiveRange::CommitSpillMoves(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::compiler::TopLevelLiveRange::FilterSpillMoves(), GetBlockStart(), v8::internal::compiler::FrameElider::InstructionAt(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), and v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
InstructionBlockAt() [1/2]
InstructionBlock* v8::internal::compiler::InstructionSequence::InstructionBlockAt (RpoNumber rpo_number) [inline]
Definition at line 1854 of file instruction.h.
                                                             {
    return instruction_blocks_->at(rpo_number.ToSize());
  }
References v8::internal::compiler::RpoNumber::ToSize().
Referenced by v8::internal::compiler::LinearScanAllocator::BlockIsDeferredOrImmediatePredecessorIsNotDeferred(), v8::internal::compiler::BundleBuilder::BuildBundles(), v8::internal::compiler::LiveRangeBuilder::BuildLiveRanges(), v8::internal::compiler::LiveRangeConnector::CommitSpillsInDeferredBlocks(), v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut(), v8::internal::compiler::LinearScanAllocator::ConsiderBlockForControlFlow(), GetBlockStart(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetContainingLoop(), v8::internal::compiler::LinearScanAllocator::HasNonDeferredPredecessor(), v8::internal::compiler::FrameElider::InstructionBlockAt(), v8::internal::compiler::CodeGenerator::IsNextInAssemblyOrder(), v8::internal::compiler::LinearScanAllocator::LastDeferredInstructionIndex(), v8::internal::compiler::InstructionSelector::MarkAsTableSwitchTarget(), v8::internal::compiler::ConstraintBuilder::MeetRegisterConstraintsForLastInstructionInBlock(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), PrintBlock(), v8::internal::compiler::GraphC1Visualizer::PrintSchedule(), v8::internal::compiler::LiveRangeBuilder::ProcessPhis(), v8::internal::compiler::LiveRangeConnector::ResolveControlFlow(), v8::internal::compiler::ConstraintBuilder::ResolvePhis(), v8::internal::compiler::InstructionSelector::SelectInstructions(), v8::internal::compiler::SpillPlacer::SetSpillRequired(), StartBlock(), v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi(), ValidateDeferredBlockEntryPaths(), ValidateDeferredBlockExitPaths(), ValidateEdgeSplitForm(), v8::internal::compiler::InstructionSelector::VisitBlock(), and v8::internal::compiler::InstructionSelector::VisitPhi().
InstructionBlockAt() [2/2]
const InstructionBlock* v8::internal::compiler::InstructionSequence::InstructionBlockAt (RpoNumber rpo_number) const [inline]
Definition at line 1863 of file instruction.h.
                                                                         {
    return instruction_blocks_->at(rpo_number.ToSize());
  }
References v8::internal::compiler::RpoNumber::ToSize().
InstructionBlockCount()
int v8::internal::compiler::InstructionSequence::InstructionBlockCount () const [inline]
Definition at line 1850 of file instruction.h.
                                    {
    return static_cast<int>(instruction_blocks_->size());
  }
Referenced by v8::internal::compiler::SpillPlacer::ClearData().
InstructionBlocksFor() [1/2]
InstructionBlocks * v8::internal::compiler::InstructionSequence::InstructionBlocksFor (Zone * zone, const Schedule * schedule) [static]
Definition at line 813 of file instruction.cc.
                                          {
  InstructionBlocks* blocks = zone->AllocateArray<InstructionBlocks>(1);
  new (blocks) InstructionBlocks(
      static_cast<int>(schedule->rpo_order()->size()), nullptr, zone);
  size_t rpo_number = 0;
  for (BasicBlockVector::const_iterator it = schedule->rpo_order()->begin();
       it != schedule->rpo_order()->end(); ++it, ++rpo_number) {
    DCHECK(!(*blocks)[rpo_number]);
    DCHECK_EQ(GetRpo(*it).ToSize(), rpo_number);
    (*blocks)[rpo_number] = InstructionBlockFor(zone, *it);
  }
  return blocks;
}
References v8::internal::Zone::AllocateArray(), v8::internal::ZoneVector< T >::begin(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ZoneVector< T >::end(), v8::internal::compiler::GetRpo(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::Schedule::rpo_order(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::RpoNumber::ToSize(), and zone().
Referenced by v8::internal::compiler::turboshaft::PipelineData::InitializeInstructionComponent(), and v8::internal::compiler::TFPipelineData::InitializeInstructionSequence().
InstructionBlocksFor() [2/2]
InstructionBlocks * v8::internal::compiler::InstructionSequence::InstructionBlocksFor (Zone * zone, const turboshaft::Graph & graph) [static]
Definition at line 828 of file instruction.cc.
                                              {
  InstructionBlocks* blocks = zone->AllocateArray<InstructionBlocks>(1);
  new (blocks)
      InstructionBlocks(static_cast<int>(graph.block_count()), nullptr, zone);
  size_t rpo_number = 0;
  // TODO(dmercadier): currently, the LoopFinder is just used to compute loop
  // headers. Since it's somewhat expensive to compute this, we should also use
  // the LoopFinder to compute the special RPO (we would only need to run the
  // LoopFinder once to compute both the special RPO and the loop headers).
  turboshaft::LoopFinder loop_finder(zone, &graph,
                                     turboshaft::LoopFinder::Config{});
  for (const turboshaft::Block& block : graph.blocks()) {
    DCHECK(!(*blocks)[rpo_number]);
    DCHECK_EQ(RpoNumber::FromInt(block.index().id()).ToSize(), rpo_number);
    (*blocks)[rpo_number] = InstructionBlockFor(
        zone, graph, &block, loop_finder.GetLoopHeader(&block));
    ++rpo_number;
  }
  return blocks;
}
References v8::internal::Zone::AllocateArray(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::RpoNumber::FromInt(), graph(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::RpoNumber::ToSize(), and zone().
instructions()
const Instructions& v8::internal::compiler::InstructionSequence::instructions () const [inline]
Definition at line 1905 of file instruction.h.
{ return instructions_; }
Referenced by v8::internal::compiler::MoveOptimizer::CompressBlock(), v8::internal::compiler::RegisterAllocationData::IsBlockBoundary(), v8::internal::compiler::MoveOptimizer::LastInstruction(), v8::internal::compiler::MoveOptimizer::OptimizeMerge(), and v8::internal::compiler::RegisterAllocatorVerifier::RegisterAllocatorVerifier().
IsFP()
bool v8::internal::compiler::InstructionSequence::IsFP (int virtual_register) const [inline]
Definition at line 1880 of file instruction.h.
                                        {
    return IsFloatingPoint(GetRepresentation(virtual_register));
  }
References v8::internal::IsFloatingPoint(), and v8::internal::compiler::ConstantOperand::virtual_register().
isolate()
Isolate* v8::internal::compiler::InstructionSequence::isolate () const [inline]
Definition at line 1916 of file instruction.h.
{ return isolate_; }
IsReference()
bool v8::internal::compiler::InstructionSequence::IsReference (int virtual_register) const [inline]
Definition at line 1877 of file instruction.h.
                                               {
    return CanBeTaggedOrCompressedPointer(GetRepresentation(virtual_register));
  }
References v8::internal::CanBeTaggedOrCompressedPointer(), and v8::internal::compiler::ConstantOperand::virtual_register().
Referenced by v8::internal::compiler::BlockAssessments::IsStaleReferenceStackSlot(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsAfter(), and v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore().
LastInstructionIndex()
int v8::internal::compiler::InstructionSequence::LastInstructionIndex () const [inline]
Definition at line 1906 of file instruction.h.
                                   {
    return static_cast<int>(instructions().size()) - 1;
  }
Referenced by v8::internal::compiler::operator<<().
LastLoopInstructionIndex()
int v8::internal::compiler::InstructionSequence::LastLoopInstructionIndex (const InstructionBlock * block) [inline]
Definition at line 1858 of file instruction.h.
                                                              {
    return instruction_blocks_->at(block->loop_end().ToSize() - 1)
        ->last_instruction_index();
  }
References v8::internal::compiler::InstructionBlock::loop_end(), and v8::internal::compiler::RpoNumber::ToSize().
MarkAsRepresentation()
void v8::internal::compiler::InstructionSequence::MarkAsRepresentation (MachineRepresentation rep, int virtual_register)
Definition at line 1071 of file instruction.cc.
                                                                     {
  DCHECK_LE(0, virtual_register);
  DCHECK_LT(virtual_register, VirtualRegisterCount());
  if (virtual_register >= static_cast<int>(representations_.size())) {
    representations_.resize(VirtualRegisterCount(), DefaultRepresentation());
  }
  rep = FilterRepresentation(rep);
  DCHECK_IMPLIES(representations_[virtual_register] != rep,
                 representations_[virtual_register] == DefaultRepresentation());
  representations_[virtual_register] = rep;
  representation_mask_ |= RepresentationBit(rep);
}
References DCHECK_IMPLIES, DCHECK_LE, DCHECK_LT, DefaultRepresentation(), v8::internal::compiler::FilterRepresentation(), representation_mask_, v8::internal::RepresentationBit(), representations_, v8::internal::ZoneVector< T >::resize(), v8::internal::ZoneVector< T >::size(), and VirtualRegisterCount().
Referenced by v8::internal::compiler::InstructionSelector::MarkAsRepresentation(), v8::internal::compiler::OperandGenerator::TempDoubleRegister(), v8::internal::compiler::OperandGenerator::TempFpRegister(), v8::internal::compiler::OperandGenerator::TempSimd128Register(), and v8::internal::compiler::OperandGenerator::TempSimd256Register().
NextVirtualRegister()
int v8::internal::compiler::InstructionSequence::NextVirtualRegister ()
Definition at line 989 of file instruction.cc.
                                             {
  int virtual_register = next_virtual_register_++;
  CHECK_NE(virtual_register, InstructionOperand::kInvalidVirtualRegister);
  return virtual_register;
}
References CHECK_NE, v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister, and next_virtual_register_.
Referenced by v8::internal::compiler::OperandGenerator::AllocateVirtualRegister(), and v8::internal::compiler::InstructionSelector::GetVirtualRegister().
operator=()
InstructionSequence& v8::internal::compiler::InstructionSequence::operator= (const InstructionSequence &) [delete]
Print()
void v8::internal::compiler::InstructionSequence::Print () const
Definition at line 1121 of file instruction.cc.
                                      {
  StdoutStream{} << *this << std::endl;
}
PrintBlock()
void v8::internal::compiler::InstructionSequence::PrintBlock (int block_id) const
Definition at line 1125 of file instruction.cc.
                                                       {
  RpoNumber rpo = RpoNumber::FromInt(block_id);
  const InstructionBlock* block = InstructionBlockAt(rpo);
  CHECK(block->rpo_number() == rpo);
  StdoutStream{} << PrintableInstructionBlock{block, this} << std::endl;
}
References CHECK, v8::internal::compiler::RpoNumber::FromInt(), InstructionBlockAt(), and v8::internal::compiler::InstructionBlock::rpo_number().
RecomputeAssemblyOrderForTesting()
void v8::internal::compiler::InstructionSequence::RecomputeAssemblyOrderForTesting ()
Definition at line 956 of file instruction.cc.
                                                           {
  RpoNumber invalid = RpoNumber::Invalid();
  for (InstructionBlock* block : *instruction_blocks_) {
    block->set_ao_number(invalid);
  }
  ComputeAssemblyOrder();
}
References ComputeAssemblyOrder(), instruction_blocks_, and v8::internal::compiler::RpoNumber::Invalid().
reference_maps()
const ReferenceMaps* v8::internal::compiler::InstructionSequence::reference_maps () const [inline]
Definition at line 1917 of file instruction.h.
{ return &reference_maps_; }
Referenced by v8::internal::compiler::ReferenceMapPopulator::PopulateReferenceMaps().
RegisterConfigurationForTesting()
const RegisterConfiguration * v8::internal::compiler::InstructionSequence::RegisterConfigurationForTesting () [static], [private]
Definition at line 1136 of file instruction.cc.
                                                     {
  DCHECK_NOT_NULL(registerConfigurationForTesting_);
  return registerConfigurationForTesting_;
}
References DCHECK_NOT_NULL, and registerConfigurationForTesting_.
Referenced by SetRegisterConfigurationForTesting().
representation_mask()
int v8::internal::compiler::InstructionSequence::representation_mask () const [inline]
Definition at line 1883 of file instruction.h.
{ return representation_mask_; }
Referenced by v8::internal::compiler::LiveRangeBuilder::ProcessInstructions(), and v8::internal::compiler::RegisterAllocator::RegisterAllocator().
rpo_immediates()
RpoImmediates& v8::internal::compiler::InstructionSequence::rpo_immediates () [inline]
Definition at line 1943 of file instruction.h.
{ return rpo_immediates_; }
SetRegisterConfigurationForTesting()
void v8::internal::compiler::InstructionSequence::SetRegisterConfigurationForTesting (const RegisterConfiguration * regConfig) [static]
Definition at line 1141 of file instruction.cc.
                                            {
  registerConfigurationForTesting_ = regConfig;
  GetRegConfig = InstructionSequence::RegisterConfigurationForTesting;
}
References v8::internal::compiler::GetRegConfig, RegisterConfigurationForTesting(), and registerConfigurationForTesting_.
SetSourcePosition()
void v8::internal::compiler::InstructionSequence::SetSourcePosition (const Instruction * instr, SourcePosition value)
Definition at line 1116 of file instruction.cc.
                                                                  {
  source_positions_.insert(std::make_pair(instr, value));
}
References source_positions_, and v8::internal::value.
Referenced by v8::internal::compiler::InstructionSelector::UpdateSourcePosition(), and v8::internal::compiler::InstructionSelector::VisitBlock().
StartBlock()
void v8::internal::compiler::InstructionSequence::StartBlock (RpoNumber rpo)
Definition at line 1000 of file instruction.cc.
                                                  {
  DCHECK_NULL(current_block_);
  current_block_ = InstructionBlockAt(rpo);
  int code_start = static_cast<int>(instructions_.size());
  current_block_->set_code_start(code_start);
}
References current_block_, DCHECK_NULL, InstructionBlockAt(), instructions_, v8::internal::compiler::InstructionBlock::set_code_start(), and v8::internal::ZoneVector< T >::size().
Referenced by v8::internal::compiler::InstructionScheduler::StartBlock(), and v8::internal::compiler::InstructionSelector::StartBlock().
ValidateDeferredBlockEntryPaths()
void v8::internal::compiler::InstructionSequence::ValidateDeferredBlockEntryPaths () const
Definition at line 876 of file instruction.cc.
                                                                {
  // If a deferred block has multiple predecessors, they have to
  // all be deferred. Otherwise, we can run into a situation where a range
  // that spills only in deferred blocks inserts its spill in the block, but
  // other ranges need moves inserted by ResolveControlFlow in the predecessors,
  // which may clobber the register of this range.
  for (const InstructionBlock* block : instruction_blocks()) {
    if (!block->IsDeferred() || block->PredecessorCount() <= 1) continue;
    for (RpoNumber predecessor_id : block->predecessors()) {
      CHECK(InstructionBlockAt(predecessor_id)->IsDeferred());
    }
  }
}
References CHECK, instruction_blocks(), InstructionBlockAt(), and v8::internal::torque::IsDeferred().
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
ValidateDeferredBlockExitPaths()
void v8::internal::compiler::InstructionSequence::ValidateDeferredBlockExitPaths () const
Definition at line 865 of file instruction.cc.
                                                               {
  // A deferred block with more than one successor must have all its successors
  // deferred.
  for (const InstructionBlock* block : instruction_blocks()) {
    if (!block->IsDeferred() || block->SuccessorCount() <= 1) continue;
    for (RpoNumber successor_id : block->successors()) {
      CHECK(InstructionBlockAt(successor_id)->IsDeferred());
    }
  }
}
References CHECK, instruction_blocks(), InstructionBlockAt(), and v8::internal::torque::IsDeferred().
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
ValidateEdgeSplitForm()
void v8::internal::compiler::InstructionSequence::ValidateEdgeSplitForm () const
Definition at line 850 of file instruction.cc.
                                                      {
  // Validate blocks are in edge-split form: no block with multiple successors
  // has an edge to a block (== a successor) with more than one predecessors.
  for (const InstructionBlock* block : instruction_blocks()) {
    if (block->SuccessorCount() > 1) {
      for (const RpoNumber& successor_id : block->successors()) {
        const InstructionBlock* successor = InstructionBlockAt(successor_id);
        // Expect precisely one predecessor: "block".
        CHECK(successor->PredecessorCount() == 1 &&
              successor->predecessors()[0] == block->rpo_number());
      }
    }
  }
}
References CHECK, instruction_blocks(), InstructionBlockAt(), v8::internal::compiler::InstructionBlock::PredecessorCount(), and v8::internal::compiler::InstructionBlock::predecessors().
Referenced by v8::internal::compiler::turboshaft::Pipeline::AllocateRegisters().
ValidateSSA()
void v8::internal::compiler::InstructionSequence::ValidateSSA () const
Definition at line 890 of file instruction.cc.
                                            {
  // TODO(mtrofin): We could use a local zone here instead.
  BitVector definitions(VirtualRegisterCount(), zone());
  for (const Instruction* instruction : *this) {
    for (size_t i = 0; i < instruction->OutputCount(); ++i) {
      const InstructionOperand* output = instruction->OutputAt(i);
      int vreg = (output->IsConstant())
                     ? ConstantOperand::cast(output)->virtual_register()
                     : UnallocatedOperand::cast(output)->virtual_register();
      CHECK(!definitions.Contains(vreg));
      definitions.Add(vreg);
    }
  }
}
References v8::internal::BitVector::Add(), CHECK, v8::internal::BitVector::Contains(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Instruction::OutputAt(), v8::internal::compiler::Instruction::OutputCount(), VirtualRegisterCount(), and zone().
Referenced by v8::internal::compiler::InstructionSelector::SelectInstructions().
VirtualRegisterCount()
int v8::internal::compiler::InstructionSequence::VirtualRegisterCount () const [inline]
Definition at line 1842 of file instruction.h.
{ return next_virtual_register_; }
Referenced by GetRepresentation(), MarkAsRepresentation(), v8::internal::compiler::RegisterAllocationData::RegisterAllocationData(), and ValidateSSA().
zone()
Zone* v8::internal::compiler::InstructionSequence::zone () const [inline]
Definition at line 1918 of file instruction.h.
{ return zone_; }
Referenced by AddInstruction(), v8::internal::compiler::RegisterAllocationData::code_zone(), v8::internal::compiler::LiveRangeBuilder::code_zone(), v8::internal::compiler::LiveRangeConnector::code_zone(), v8::internal::compiler::TopLevelLiveRange::CommitSpillMoves(), ComputeAssemblyOrder(), InstructionBlocksFor(), and ValidateSSA().
Friends And Related Function Documentation
operator<<
V8_EXPORT_PRIVATE std::ostream& operator<< (std::ostream & , const InstructionSequence &) [friend]
Definition at line 1325 of file instruction.cc.
                                                                        {
  for (size_t i = 0; i < code.immediates_.size(); ++i) {
    Constant constant = code.immediates_[i];
    os << "IMM#" << i << ": " << constant << "\n";
  }
  int n = 0;
  for (ConstantMap::const_iterator it = code.constants_.begin();
       it != code.constants_.end(); ++n, ++it) {
    os << "CST#" << n << ": v" << it->first << " = " << it->second << "\n";
  }
  for (int i = 0; i < code.InstructionBlockCount(); i++) {
    auto* block = code.InstructionBlockAt(RpoNumber::FromInt(i));
    os << PrintableInstructionBlock{block, &code};
  }
  return os;
}
Member Data Documentation
ao_blocks_
InstructionBlocks* v8::internal::compiler::InstructionSequence::ao_blocks_ [private]
Definition at line 2053 of file instruction.h.
Referenced by ComputeAssemblyOrder().
constants_
ConstantMap v8::internal::compiler::InstructionSequence::constants_ [private]
Definition at line 2055 of file instruction.h.
current_block_
InstructionBlock* v8::internal::compiler::InstructionSequence::current_block_ [private]
Definition at line 2066 of file instruction.h.
Referenced by AddInstruction(), EndBlock(), and StartBlock().
deoptimization_entries_
DeoptimizationVector v8::internal::compiler::InstructionSequence::deoptimization_entries_ [private]
Definition at line 2063 of file instruction.h.
Referenced by AddDeoptimizationEntry(), and GetDeoptimizationEntry().
immediates_
Immediates v8::internal::compiler::InstructionSequence::immediates_ [private]
Definition at line 2056 of file instruction.h.
instruction_blocks_
InstructionBlocks* const v8::internal::compiler::InstructionSequence::instruction_blocks_ [private]
Definition at line 2052 of file instruction.h.
Referenced by ComputeAssemblyOrder(), and RecomputeAssemblyOrderForTesting().
instructions_
Instructions v8::internal::compiler::InstructionSequence::instructions_ [private]
Definition at line 2058 of file instruction.h.
Referenced by AddInstruction(), EndBlock(), and StartBlock().
isolate_
Isolate* v8::internal::compiler::InstructionSequence::isolate_ [private]
Definition at line 2050 of file instruction.h.
next_virtual_register_
int v8::internal::compiler::InstructionSequence::next_virtual_register_ [private]
Definition at line 2059 of file instruction.h.
Referenced by NextVirtualRegister().
reference_maps_
ReferenceMaps v8::internal::compiler::InstructionSequence::reference_maps_ [private]
Definition at line 2060 of file instruction.h.
Referenced by AddInstruction().
registerConfigurationForTesting_
const RegisterConfiguration * v8::internal::compiler::InstructionSequence::registerConfigurationForTesting_ = nullptr [static], [private]
Definition at line 2045 of file instruction.h.
Referenced by RegisterConfigurationForTesting(), and SetRegisterConfigurationForTesting().
representation_mask_
int v8::internal::compiler::InstructionSequence::representation_mask_ [private]
Definition at line 2062 of file instruction.h.
Referenced by MarkAsRepresentation().
representations_
ZoneVector<MachineRepresentation> v8::internal::compiler::InstructionSequence::representations_ [private]
Definition at line 2061 of file instruction.h.
Referenced by GetRepresentation(), and MarkAsRepresentation().
rpo_immediates_
RpoImmediates v8::internal::compiler::InstructionSequence::rpo_immediates_ [private]
Definition at line 2057 of file instruction.h.
source_positions_
SourcePositionMap v8::internal::compiler::InstructionSequence::source_positions_ [private]
Definition at line 2054 of file instruction.h.
Referenced by GetSourcePosition(), and SetSourcePosition().
zone_
Zone* const v8::internal::compiler::InstructionSequence::zone_ [private]
Definition at line 2051 of file instruction.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction.h
/mnt/V8SourceCode/src/compiler/backend/instruction.cc