v8::internal::LocalHeap Class Reference
#include <local-heap.h>
Classes
class AtomicThreadState
class ThreadState
Public Types
using GCEpilogueCallback = void(void *)
Public Member Functions
LocalHeap (Heap *heap, ThreadKind kind, std::unique_ptr< PersistentHandles > persistent_handles=nullptr)
~LocalHeap ()
void Safepoint ()
LocalHandles * handles ()
template<typename T >
IndirectHandle< T > NewPersistentHandle (Tagged< T > object)
template<typename T , template< typename > typename HandleType>
IndirectHandle< T > NewPersistentHandle (HandleType< T > object) requires(std
template<typename T >
IndirectHandle< T > NewPersistentHandle (T object)
template<typename T , template< typename > typename MaybeHandleType>
MaybeIndirectHandle< T > NewPersistentMaybeHandle (MaybeHandleType< T > maybe_handle) requires(std
void AttachPersistentHandles (std::unique_ptr< PersistentHandles > persistent_handles)
std::unique_ptr< PersistentHandles > DetachPersistentHandles ()
bool IsParked () const
bool IsRunning () const
bool IsRetryOfFailedAllocation () const
void SetRetryOfFailedAllocation (bool value)
Heap * heap () const
Heap * AsHeap () const
MarkingBarrier * marking_barrier ()
void FreeLinearAllocationAreas ()
void MakeLinearAllocationAreasIterable ()
void MarkLinearAllocationAreasBlack ()
void UnmarkLinearAllocationsArea ()
void MarkSharedLinearAllocationAreasBlack ()
void UnmarkSharedLinearAllocationsArea ()
void FreeLinearAllocationAreasAndResetFreeLists ()
void FreeSharedLinearAllocationAreasAndResetFreeLists ()
V8_WARN_UNUSED_RESULT AllocationResult AllocateRaw (int size_in_bytes, AllocationType allocation, AllocationOrigin origin=AllocationOrigin::kRuntime, AllocationAlignment alignment=kTaggedAligned, AllocationHint hint=AllocationHint())
template<HeapAllocator::AllocationRetryMode mode>
Tagged< HeapObject > AllocateRawWith (int size_in_bytes, AllocationType allocation, AllocationOrigin origin=AllocationOrigin::kRuntime, AllocationAlignment alignment=kTaggedAligned, AllocationHint hint=AllocationHint())
V8_WARN_UNUSED_RESULT Address AllocateRawOrFail (int size_in_bytes, AllocationType allocation, AllocationOrigin origin=AllocationOrigin::kRuntime, AllocationAlignment alignment=kTaggedAligned, AllocationHint hint=AllocationHint())
void NotifyObjectSizeChange (Tagged< HeapObject > object, int old_size, int new_size, ClearRecordedSlots clear_recorded_slots)
bool is_main_thread () const
bool is_main_thread_for (Heap *heap) const
bool is_in_trampoline () const
bool deserialization_complete () const
ReadOnlySpace * read_only_space ()
void AddGCEpilogueCallback (GCEpilogueCallback *callback, void *data, GCCallbacksInSafepoint::GCType gc_type=GCCallbacksInSafepoint::GCType::kAll)
void RemoveGCEpilogueCallback (GCEpilogueCallback *callback, void *data)
void WeakenDescriptorArrays (GlobalHandleVector< DescriptorArray > strong_descriptor_arrays)
void SetUpMainThreadForTesting ()
template<typename Callback >
void ExecuteWhileParked (Callback callback)
template<typename Callback >
void ExecuteMainThreadWhileParked (Callback callback)
template<typename Callback >
void ExecuteBackgroundThreadWhileParked (Callback callback)
void Iterate (RootVisitor *visitor)
HeapAllocator * allocator ()
Static Public Member Functions
static void SetCurrent (LocalHeap *local_heap)
Private Types
using ParkedBit = base::BitField8< bool, 0, 1 >
using SafepointRequestedBit = ParkedBit::Next< bool, 1 >
using CollectionRequestedBit = SafepointRequestedBit::Next< bool, 1 >
Private Member Functions
template<typename Callback >
void ExecuteWithStackMarker (Callback callback)
void Park ()
void Unpark ()
void ParkSlowPath ()
void UnparkSlowPath ()
void EnsureParkedBeforeDestruction ()
void SafepointSlowPath ()
void SleepInSafepoint ()
void SleepInUnpark ()
template<typename Callback >
void ParkAndExecuteCallback (Callback callback)
void EnsurePersistentHandles ()
void InvokeGCEpilogueCallbacksInSafepoint (GCCallbacksInSafepoint::GCType gc_type)
void SetUpMainThread (LinearAllocationArea &new_allocation_info, LinearAllocationArea &old_allocation_info)
void SetUpMarkingBarrier ()
void SetUpSharedMarking ()
Private Attributes
Heap * heap_
V8_NO_UNIQUE_ADDRESS PtrComprCageAccessScope ptr_compr_cage_access_scope_
bool is_main_thread_
AtomicThreadState state_
bool allocation_failed_
int nested_parked_scopes_
Isolate * saved_current_isolate_ = nullptr
LocalHeap * prev_
LocalHeap * next_
std::unique_ptr< LocalHandles > handles_
std::unique_ptr< PersistentHandles > persistent_handles_
std::unique_ptr< MarkingBarrier > marking_barrier_
GCCallbacksInSafepoint gc_epilogue_callbacks_
base::SmallVector< GCRootsProvider *, 4 > roots_providers_
HeapAllocator heap_allocator_
MarkingBarrier * saved_marking_barrier_ = nullptr
::heap::base::Stack stack_
Friends
class CollectionBarrier
class GlobalSafepoint
class Heap
class Isolate
class IsolateSafepoint
class IsolateSafepointScope
class ParkedScope
class UnparkedScope
class GCRootsProviderScope
Detailed Description
Definition at line 50 of file local-heap.h.
Member Typedef Documentation
CollectionRequestedBit
using v8::internal::LocalHeap::CollectionRequestedBit = SafepointRequestedBit::Next<bool, 1> [private]
Definition at line 248 of file local-heap.h.
GCEpilogueCallback
using v8::internal::LocalHeap::GCEpilogueCallback = void(void*)
Definition at line 52 of file local-heap.h.
ParkedBit
using v8::internal::LocalHeap::ParkedBit = base::BitField8<bool, 0, 1> [private]
Definition at line 246 of file local-heap.h.
SafepointRequestedBit
using v8::internal::LocalHeap::SafepointRequestedBit = ParkedBit::Next<bool, 1> [private]
Definition at line 247 of file local-heap.h.
Constructor & Destructor Documentation
LocalHeap()
v8::internal::LocalHeap::LocalHeap (Heap * heap, ThreadKind kind, std::unique_ptr< PersistentHandles > persistent_handles = nullptr) [explicit]
Definition at line 51 of file local-heap.cc.
    : heap_(heap),
      ptr_compr_cage_access_scope_(heap->isolate()),
      is_main_thread_(kind == ThreadKind::kMain),
      state_(ThreadState::Parked()),
#if V8_OS_DARWIN
      thread_handle_(pthread_self()),
#endif
      allocation_failed_(false),
      nested_parked_scopes_(0),
      prev_(nullptr),
      next_(nullptr),
      handles_(new LocalHandles),
      persistent_handles_(std::move(persistent_handles)),
      heap_allocator_(this) {
  DCHECK_IMPLIES(!is_main_thread(),
                 (v8_flags.concurrent_builtin_generation &&
                  heap->isolate()->IsGeneratingEmbeddedBuiltins()) ||
                     heap_->deserialization_complete());
  if (!is_main_thread()) {
    heap_allocator_.Setup();
    SetUpMarkingBarrier();
  }
  heap_->safepoint()->AddLocalHeap(this, [this] {
    if (!is_main_thread()) {
      saved_marking_barrier_ =
          WriteBarrier::SetForThread(marking_barrier_.get());
      if (heap_->incremental_marking()->IsMarking()) {
        marking_barrier_->Activate(
            heap_->incremental_marking()->IsCompacting(),
            heap_->incremental_marking()->marking_mode());
      }
      SetUpSharedMarking();
    }
  });
  if (persistent_handles_) {
    persistent_handles_->Attach(this);
  }
  DCHECK_NULL(LocalHeap::Current());
  if (!is_main_thread()) {
    saved_current_isolate_ = Isolate::TryGetCurrent();
    Isolate::SetCurrent(heap_->isolate());
    LocalHeap::SetCurrent(this);
  }
  stack_.SetScanSimulatorCallback(Isolate::IterateRegistersAndStackOfSimulator);
}
References v8::internal::IsolateSafepoint::AddLocalHeap(), DCHECK_IMPLIES, DCHECK_NULL, v8::internal::Heap::deserialization_complete(), heap_, heap_allocator_, v8::internal::Heap::incremental_marking(), is_main_thread(), v8::internal::IncrementalMarking::IsCompacting(), v8::internal::IncrementalMarking::IsMarking(), v8::internal::Heap::isolate(), v8::internal::Isolate::IterateRegistersAndStackOfSimulator(), v8::internal::kMain, marking_barrier_, v8::internal::IncrementalMarking::marking_mode(), persistent_handles_, v8::internal::Heap::safepoint(), saved_current_isolate_, saved_marking_barrier_, v8::internal::Isolate::SetCurrent(), SetCurrent(), v8::internal::WriteBarrier::SetForThread(), heap::base::Stack::SetScanSimulatorCallback(), v8::internal::HeapAllocator::Setup(), SetUpMarkingBarrier(), SetUpSharedMarking(), stack_, v8::Isolate::TryGetCurrent(), and v8::internal::v8_flags.
 LocalHeap()
v8::internal::LocalHeap::~LocalHeap ()
Definition at line 102 of file local-heap.cc.
                      {
  // Park thread since removing the local heap could block.
  EnsureParkedBeforeDestruction();
  heap_->safepoint()->RemoveLocalHeap(this, [this] {
    FreeLinearAllocationAreas();
    if (!is_main_thread()) {
      marking_barrier_->PublishIfNeeded();
      marking_barrier_->PublishSharedIfNeeded();
      MarkingBarrier* overwritten =
          WriteBarrier::SetForThread(saved_marking_barrier_);
      DCHECK_EQ(overwritten, marking_barrier_.get());
      USE(overwritten);
    }
  });
  if (!is_main_thread()) {
    DCHECK_EQ(Isolate::Current(), heap_->isolate());
    Isolate::SetCurrent(saved_current_isolate_);
    DCHECK_EQ(LocalHeap::Current(), this);
    LocalHeap::SetCurrent(nullptr);
  }
  DCHECK(gc_epilogue_callbacks_.IsEmpty());
}
References v8::internal::Isolate::Current(), v8::internal::DCHECK(), DCHECK_EQ, EnsureParkedBeforeDestruction(), FreeLinearAllocationAreas(), gc_epilogue_callbacks_, heap_, is_main_thread(), v8::internal::GCCallbacksInSafepoint::IsEmpty(), v8::internal::Heap::isolate(), marking_barrier_, v8::internal::IsolateSafepoint::RemoveLocalHeap(), v8::internal::Heap::safepoint(), saved_current_isolate_, saved_marking_barrier_, v8::internal::Isolate::SetCurrent(), SetCurrent(), v8::internal::WriteBarrier::SetForThread(), and USE.
Member Function Documentation
AddGCEpilogueCallback()
void v8::internal::LocalHeap::AddGCEpilogueCallback (GCEpilogueCallback * callback, void * data, GCCallbacksInSafepoint::GCType gc_type = GCCallbacksInSafepoint::GCType::kAll)
Definition at line 456 of file local-heap.cc.
                                                                            {
  DCHECK(IsRunning());
  gc_epilogue_callbacks_.Add(callback, data, gc_type);
}
References v8::internal::GCCallbacksInSafepoint::Add(), v8::internal::DCHECK(), gc_epilogue_callbacks_, and IsRunning().
Referenced by v8::internal::interpreter::BytecodeArrayIterator::BytecodeArrayIterator(), v8::internal::baseline::BytecodeOffsetIterator::BytecodeOffsetIterator(), v8::internal::JsonParser< Char >::JsonParser(), v8::internal::RelocatingCharacterStream::RelocatingCharacterStream(), v8::internal::ScheduleMinorGCTaskObserver::ScheduleMinorGCTaskObserver(), and v8::internal::JsonStringifier::SimplePropertyKeyCache::SimplePropertyKeyCache().
AllocateRaw()
AllocationResult v8::internal::LocalHeap::AllocateRaw (int size_in_bytes, AllocationType allocation, AllocationOrigin origin = AllocationOrigin::kRuntime, AllocationAlignment alignment = kTaggedAligned, AllocationHint hint = AllocationHint()) [inline]
Definition at line 29 of file local-heap-inl.h.
                                                             {
  return heap_allocator_.AllocateRaw(size_in_bytes, type, origin, alignment,
                                     hint);
}
References v8::internal::HeapAllocator::AllocateRaw(), heap_allocator_, and v8::internal::tracing::type.
Referenced by v8::internal::StressConcurrentAllocationTask::RunInternal().
AllocateRawOrFail()
Address v8::internal::LocalHeap::AllocateRawOrFail (int size_in_bytes, AllocationType allocation, AllocationOrigin origin = AllocationOrigin::kRuntime, AllocationAlignment alignment = kTaggedAligned, AllocationHint hint = AllocationHint()) [inline]
Definition at line 48 of file local-heap-inl.h.
                                                          {
  return AllocateRawWith<HeapAllocator::kRetryOrFail>(object_size, type, origin,
                                                      alignment, hint)
      .address();
}
References v8::internal::tracing::type.
AllocateRawWith()
template<typename HeapAllocator::AllocationRetryMode mode>
Tagged< HeapObject > v8::internal::LocalHeap::AllocateRawWith (int size_in_bytes, AllocationType allocation, AllocationOrigin origin = AllocationOrigin::kRuntime, AllocationAlignment alignment = kTaggedAligned, AllocationHint hint = AllocationHint())
Definition at line 38 of file local-heap-inl.h.
                                                                   {
  object_size = ALIGN_TO_ALLOCATION_ALIGNMENT(object_size);
  return heap_allocator_.AllocateRawWith<mode>(object_size, type, origin,
                                               alignment, hint);
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::HeapAllocator::AllocateRawWith(), heap_allocator_, mode(), and v8::internal::tracing::type.
allocator()
HeapAllocator* v8::internal::LocalHeap::allocator () [inline]
Definition at line 243 of file local-heap.h.
{ return &heap_allocator_; }
AsHeap()
Heap* v8::internal::LocalHeap::AsHeap () const [inline]
Definition at line 123 of file local-heap.h.
{ return heap(); }
References heap().
Referenced by v8::internal::LocalFactory::AllocationTypeForInPlaceInternalizableString(), v8::internal::BackgroundMergeTask::BeginMergeInBackground(), and WeakenDescriptorArrays().
AttachPersistentHandles()
void v8::internal::LocalHeap::AttachPersistentHandles (std::unique_ptr< PersistentHandles > persistent_handles)
Definition at line 183 of file local-heap.cc.
                                                         {
  DCHECK_NULL(persistent_handles_);
  persistent_handles_ = std::move(persistent_handles);
  persistent_handles_->Attach(this);
}
References DCHECK_NULL, and persistent_handles_.
Referenced by v8::internal::compiler::JSHeapBroker::AttachLocalIsolate(), v8::internal::compiler::JSHeapBroker::AttachLocalIsolateForMaglev(), v8::internal::BackgroundMergeTask::BeginMergeInBackground(), v8::internal::baseline::BaselineBatchCompilerJob::Compile(), and v8::internal::BackgroundCompileTask::Run().
deserialization_complete()
bool v8::internal::LocalHeap::deserialization_complete () const [inline]
Definition at line 203 of file local-heap.h.
                                        {
    return heap_->deserialization_complete();
  }
DetachPersistentHandles()
std::unique_ptr< PersistentHandles > v8::internal::LocalHeap::DetachPersistentHandles ()
Definition at line 190 of file local-heap.cc.
                                                                    {
  if (persistent_handles_) persistent_handles_->Detach();
  return std::move(persistent_handles_);
}
References persistent_handles_.
Referenced by v8::internal::BackgroundMergeTask::BeginMergeInBackground(), v8::internal::baseline::BaselineBatchCompilerJob::Compile(), v8::internal::compiler::JSHeapBroker::DetachLocalIsolate(), v8::internal::compiler::JSHeapBroker::DetachLocalIsolateForMaglev(), v8::internal::BackgroundCompileTask::Run(), and v8::internal::CodeSerializer::StartDeserializeOffThread().
EnsureParkedBeforeDestruction()
void v8::internal::LocalHeap::EnsureParkedBeforeDestruction () [private]
Definition at line 332 of file local-heap.cc.
                                              {
  DCHECK_IMPLIES(!is_main_thread(), IsParked());
}
References DCHECK_IMPLIES, is_main_thread(), and IsParked().
Referenced by ~LocalHeap().
EnsurePersistentHandles()
void v8::internal::LocalHeap::EnsurePersistentHandles () [private]
Definition at line 176 of file local-heap.cc.
                                        {
  if (!persistent_handles_) {
    persistent_handles_ = heap_->isolate()->NewPersistentHandles();
    persistent_handles_->Attach(this);
  }
}
References heap_, v8::internal::Heap::isolate(), v8::internal::Isolate::NewPersistentHandles(), and persistent_handles_.
ExecuteBackgroundThreadWhileParked()
template<typename Callback >
void v8::internal::LocalHeap::ExecuteBackgroundThreadWhileParked (Callback callback) [inline]
Definition at line 99 of file local-heap-inl.h.
                       {
  DCHECK(!is_main_thread());
  heap()->stack().SetMarkerForBackgroundThreadAndCallback(
      ThreadId::Current().ToInteger(),
      [this, callback]() { ParkAndExecuteCallback(callback); });
}
References v8::internal::ThreadId::Current(), v8::internal::DCHECK(), heap(), is_main_thread(), ParkAndExecuteCallback(), heap::base::Stack::SetMarkerForBackgroundThreadAndCallback(), and v8::internal::Heap::stack().
Referenced by v8::internal::LocalIsolate::ParkIfOnBackgroundAndExecute().
ExecuteMainThreadWhileParked()
template<typename Callback >
void v8::internal::LocalHeap::ExecuteMainThreadWhileParked (Callback callback) [inline]
Definition at line 92 of file local-heap-inl.h.
                                                                        {
  DCHECK(is_main_thread());
  heap()->stack().SetMarkerAndCallback(
      [this, callback]() { ParkAndExecuteCallback(callback); });
}
References v8::internal::DCHECK(), heap(), is_main_thread(), ParkAndExecuteCallback(), heap::base::Stack::SetMarkerAndCallback(), and v8::internal::Heap::stack().
Referenced by v8::internal::Isolate::Deinit(), v8::internal::LocalIsolate::ExecuteMainThreadWhileParked(), and v8::Shell::RunMain().
ExecuteWhileParked()
template<typename Callback >
void v8::internal::LocalHeap::ExecuteWhileParked (Callback callback) [inline]
Definition at line 86 of file local-heap-inl.h.
                                                              {
  ExecuteWithStackMarker(
      [this, callback]() { ParkAndExecuteCallback(callback); });
}
References ExecuteWithStackMarker(), and ParkAndExecuteCallback().
Referenced by v8::internal::CollectionBarrier::AwaitCollectionBackground(), v8::internal::GlobalSafepoint::EnterGlobalSafepointScope(), v8::internal::IsolateSafepoint::LockMutex(), v8::internal::ParkingThread::ParkedJoin(), v8::internal::ParkingThread::ParkedJoinAll(), v8::internal::ParkedMutexGuard::ParkedMutexGuard(), v8::internal::ParkedMutexGuardIf::ParkedMutexGuardIf(), v8::internal::ParkedRecursiveMutexGuard::ParkedRecursiveMutexGuard(), v8::internal::ParkingSemaphore::ParkedWait(), v8::internal::ParkingConditionVariable::ParkedWait(), v8::internal::ParkingConditionVariable::ParkedWaitFor(), and v8::internal::ParkingSemaphore::ParkedWaitFor().
ExecuteWithStackMarker()
template<typename Callback >
void v8::internal::LocalHeap::ExecuteWithStackMarker (Callback callback) [inline], [private]
Definition at line 76 of file local-heap-inl.h.
                                                                  {
  if (is_main_thread()) {
    heap()->stack().SetMarkerAndCallback(callback);
  } else {
    heap()->stack().SetMarkerForBackgroundThreadAndCallback(
        ThreadId::Current().ToInteger(), callback);
  }
}
References v8::internal::ThreadId::Current(), heap(), is_main_thread(), heap::base::Stack::SetMarkerAndCallback(), heap::base::Stack::SetMarkerForBackgroundThreadAndCallback(), and v8::internal::Heap::stack().
Referenced by ExecuteWhileParked(), and SleepInSafepoint().
FreeLinearAllocationAreas()
void v8::internal::LocalHeap::FreeLinearAllocationAreas ()
Definition at line 411 of file local-heap.cc.
                                          {
  heap_allocator_.FreeLinearAllocationAreas();
}
References v8::internal::HeapAllocator::FreeLinearAllocationAreas(), and heap_allocator_.
Referenced by v8::internal::Heap::FreeLinearAllocationAreas(), v8::internal::Heap::StartTearDown(), and ~LocalHeap().
FreeLinearAllocationAreasAndResetFreeLists()
void v8::internal::LocalHeap::FreeLinearAllocationAreasAndResetFreeLists ()
Definition at line 445 of file local-heap.cc.
                                                           {
  heap_allocator_.FreeLinearAllocationAreasAndResetFreeLists();
}
References v8::internal::HeapAllocator::FreeLinearAllocationAreasAndResetFreeLists(), and heap_allocator_.
FreeSharedLinearAllocationAreasAndResetFreeLists()
void v8::internal::LocalHeap::FreeSharedLinearAllocationAreasAndResetFreeLists ()
Definition at line 449 of file local-heap.cc.
                                                                 {
  if (heap_allocator_.shared_space_allocator()) {
    heap_allocator_.shared_space_allocator()
        ->FreeLinearAllocationAreaAndResetFreeList();
  }
}
References v8::internal::MainAllocator::FreeLinearAllocationAreaAndResetFreeList(), heap_allocator_, and v8::internal::HeapAllocator::shared_space_allocator().
Referenced by v8::internal::Heap::FreeSharedLinearAllocationAreasAndResetFreeLists().
handles()
LocalHandles* v8::internal::LocalHeap::handles () [inline]
Definition at line 70 of file local-heap.h.
{ return handles_.get(); }
Referenced by v8::internal::LocalHandleScope::CloseScope(), v8::internal::LocalHandleScope::GetHandle(), and v8::internal::LocalHandleScope::LocalHandleScope().
heap()
Heap* v8::internal::LocalHeap::heap () const [inline]
Definition at line 122 of file local-heap.h.
{ return heap_; }
Referenced by v8::internal::LocalHandleScope::CloseMainThreadScope(), v8::internal::Heap::CollectGarbageFromAnyThread(), ExecuteBackgroundThreadWhileParked(), ExecuteMainThreadWhileParked(), ExecuteWithStackMarker(), v8::internal::LocalHandleScope::GetMainThreadHandle(), v8::internal::IsolateSafepoint::LockMutex(), NotifyObjectSizeChange(), v8::internal::LocalHandleScope::OpenMainThreadScope(), ParkSlowPath(), SetUpSharedMarking(), v8::internal::Heap::ShouldExpandOldGenerationOnSlowAllocation(), SleepInSafepoint(), and UnparkSlowPath().
InvokeGCEpilogueCallbacksInSafepoint()
void v8::internal::LocalHeap::InvokeGCEpilogueCallbacksInSafepoint (GCCallbacksInSafepoint::GCType gc_type) [private]
Definition at line 475 of file local-heap.cc.
                                          {
  gc_epilogue_callbacks_.Invoke(gc_type);
}
References gc_epilogue_callbacks_, and v8::internal::GCCallbacksInSafepoint::Invoke().
Referenced by v8::internal::Heap::GarbageCollectionEpilogueInSafepoint().
is_in_trampoline()
bool v8::internal::LocalHeap::is_in_trampoline () const [inline]
Definition at line 107 of file local-heap-inl.h.
                                                 {
  if (is_main_thread()) {
    return heap_->stack().IsMarkerSet();
  } else {
    return heap_->stack().IsMarkerSetForBackgroundThread(
        ThreadId::Current().ToInteger());
  }
}
References v8::internal::ThreadId::Current(), heap_, is_main_thread(), heap::base::Stack::IsMarkerSet(), heap::base::Stack::IsMarkerSetForBackgroundThread(), and v8::internal::Heap::stack().
is_main_thread()
bool v8::internal::LocalHeap::is_main_thread () const [inline]
Definition at line 197 of file local-heap.h.
{ return is_main_thread_; }
Referenced by v8::internal::HeapAllocator::AllocateRaw(), v8::internal::NewLargeObjectSpace::AllocateRaw(), v8::internal::OldLargeObjectSpace::AllocateRaw(), v8::internal::HeapAllocator::CollectAllAvailableGarbage(), v8::internal::HeapAllocator::CollectGarbage(), v8::internal::Heap::CollectGarbageForBackground(), v8::internal::Heap::CollectGarbageFromAnyThread(), EnsureParkedBeforeDestruction(), ExecuteBackgroundThreadWhileParked(), ExecuteMainThreadWhileParked(), ExecuteWithStackMarker(), v8::internal::LocalHandleScope::GetHandle(), is_in_trampoline(), v8::internal::MainAllocator::is_main_thread(), v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), v8::internal::LocalHandleScope::LocalHandleScope(), LocalHeap(), v8::internal::MainAllocator::MainAllocator(), ParkSlowPath(), SafepointSlowPath(), v8::internal::HeapAllocator::Setup(), SetUpMainThread(), SetUpMainThreadForTesting(), SetUpSharedMarking(), SleepInSafepoint(), SleepInUnpark(), v8::internal::UnparkedScopeIfOnBackground::UnparkedScopeIfOnBackground(), UnparkSlowPath(), v8::internal::LocalHandleScope::~LocalHandleScope(), and ~LocalHeap().
is_main_thread_for()
bool v8::internal::LocalHeap::is_main_thread_for (Heap * heap) const [inline]
Definition at line 198 of file local-heap.h.
                                            {
    return is_main_thread() && heap_ == heap;
  }
References heap().
Referenced by v8::internal::Heap::NotifyOldGenerationExpansion(), and v8::internal::Heap::StartIncrementalMarkingIfAllocationLimitIsReached().
IsParked()
bool v8::internal::LocalHeap::IsParked () const
Definition at line 210 of file local-heap.cc.
                               {
#ifdef DEBUG
  VerifyCurrent();
#endif
  return state_.load_relaxed().IsParked();
}
References v8::internal::LocalHeap::ThreadState::IsParked(), v8::internal::LocalHeap::AtomicThreadState::load_relaxed(), and state_.
Referenced by v8::internal::Parser::DoParseProgram(), EnsureParkedBeforeDestruction(), v8::internal::OptimizedCompilationJob::ExecuteJob(), v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::MaybeUnparkForPrint::MaybeUnparkForPrint(), v8::internal::OptimizingCompileTaskExecutor::CompileTask::Run(), v8::internal::maglev::MaglevConcurrentDispatcher::JobTask::Run(), and v8::internal::compiler::UnparkedScopeIfNeeded::UnparkedScopeIfNeeded().
IsRetryOfFailedAllocation()
bool v8::internal::LocalHeap::IsRetryOfFailedAllocation () const [inline]
Definition at line 118 of file local-heap.h.
{ return allocation_failed_; }
Referenced by v8::internal::HeapAllocator::RetryAllocation(), and v8::internal::Heap::ShouldExpandOldGenerationOnSlowAllocation().
IsRunning()
bool v8::internal::LocalHeap::IsRunning () const
Definition at line 217 of file local-heap.cc.
                                {
#ifdef DEBUG
  VerifyCurrent();
#endif
  return state_.load_relaxed().IsRunning();
}
References v8::internal::LocalHeap::ThreadState::IsRunning(), v8::internal::LocalHeap::AtomicThreadState::load_relaxed(), and state_.
Referenced by AddGCEpilogueCallback(), v8::internal::HeapAllocator::AllocateRaw(), v8::internal::Heap::CollectGarbageFromAnyThread(), v8::internal::HandleScope::CreateHandle(), v8::internal::LocalHandleScope::GetHandle(), v8::internal::LocalHandleScope::LocalHandleScope(), RemoveGCEpilogueCallback(), SetUpMainThread(), SetUpMainThreadForTesting(), and SetUpSharedMarking().
Iterate()
void v8::internal::LocalHeap::Iterate (RootVisitor * visitor)
Definition at line 468 of file local-heap.cc.
                                            {
  handles_->Iterate(visitor);
  for (GCRootsProvider* provider : roots_providers_) {
    provider->Iterate(visitor);
  }
}
References handles_, and roots_providers_.
MakeLinearAllocationAreasIterable()
void v8::internal::LocalHeap::MakeLinearAllocationAreasIterable ()
Definition at line 421 of file local-heap.cc.
                                                  {
  heap_allocator_.MakeLinearAllocationAreasIterable();
}
References heap_allocator_, and v8::internal::HeapAllocator::MakeLinearAllocationAreasIterable().
Referenced by v8::internal::Heap::MakeLinearAllocationAreasIterable().
marking_barrier()
MarkingBarrier* v8::internal::LocalHeap::marking_barrier () [inline]
Definition at line 130 of file local-heap.h.
{ return marking_barrier_.get(); }
Referenced by v8::internal::MarkingBarrier::ActivateAll(), v8::internal::MarkingBarrier::ActivateYoung(), v8::internal::WriteBarrier::CurrentMarkingBarrier(), v8::internal::MarkingBarrier::DeactivateAll(), v8::internal::MarkingBarrier::DeactivateYoung(), v8::internal::MarkingBarrier::PublishAll(), v8::internal::MarkingBarrier::PublishYoung(), v8::internal::Isolate::SetIsolateThreadLocals(), v8::internal::MarkCompactCollector::TearDown(), v8::internal::MinorMarkSweepCollector::TearDown(), and v8::internal::Heap::TearDownWithSharedHeap().
MarkLinearAllocationAreasBlack()
void v8::internal::LocalHeap::MarkLinearAllocationAreasBlack ()
Definition at line 425 of file local-heap.cc.
                                               {
  heap_allocator_.MarkLinearAllocationAreasBlack();
}
References heap_allocator_, and v8::internal::HeapAllocator::MarkLinearAllocationAreasBlack().
MarkSharedLinearAllocationAreasBlack()
void v8::internal::LocalHeap::MarkSharedLinearAllocationAreasBlack ()
Definition at line 433 of file local-heap.cc.
                                                     {
  if (heap_allocator_.shared_space_allocator()) {
    heap_allocator_.shared_space_allocator()->MarkLinearAllocationAreaBlack();
  }
}
References heap_allocator_, v8::internal::MainAllocator::MarkLinearAllocationAreaBlack(), and v8::internal::HeapAllocator::shared_space_allocator().
Referenced by v8::internal::Heap::MarkSharedLinearAllocationAreasBlack().
NewPersistentHandle() [1/3]
template<typename T , template< typename > typename HandleType>
IndirectHandle<T> v8::internal::LocalHeap::NewPersistentHandle (HandleType< T > object) [inline]
Definition at line 81 of file local-heap.h.
  {
    return NewPersistentHandle(*object);
  }
NewPersistentHandle() [2/3]
template<typename T >
IndirectHandle<T> v8::internal::LocalHeap::NewPersistentHandle (T object) [inline]
Definition at line 88 of file local-heap.h.
                                                  {
    static_assert(kTaggedCanConvertToRawObjects);
    return NewPersistentHandle(Tagged<T>(object));
  }
References v8::internal::kTaggedCanConvertToRawObjects.
NewPersistentHandle() [3/3]
template<typename T >
IndirectHandle<T> v8::internal::LocalHeap::NewPersistentHandle (Tagged< T > object) [inline]
Definition at line 73 of file local-heap.h.
                                                          {
    if (!persistent_handles_) {
      EnsurePersistentHandles();
    }
    return persistent_handles_->NewHandle(object);
  }
Referenced by v8::internal::maglev::MaglevCodeGenerator::Assemble(), v8::internal::BackgroundMergeTask::BeginMergeInBackground(), v8::internal::IsCompiledScope::IsCompiledScope(), v8::internal::BackgroundCompileTask::Run(), and v8::internal::PendingCompilationErrorHandler::MessageDetails::SetString().
NewPersistentMaybeHandle()
template<typename T , template< typename > typename MaybeHandleType>
MaybeIndirectHandle<T> v8::internal::LocalHeap::NewPersistentMaybeHandle (MaybeHandleType< T > maybe_handle) [inline]
Definition at line 94 of file local-heap.h.
  {
    DirectHandle<T> handle;
    if (maybe_handle.ToHandle(&handle)) {
      return NewPersistentHandle(handle);
    }
    return kNullMaybeHandle;
  }
References v8::internal::handle(), and v8::internal::kNullMaybeHandle.
Referenced by v8::internal::maglev::MaglevCodeGenerator::Assemble(), v8::internal::BackgroundCompileTask::Run(), and v8::internal::CodeSerializer::StartDeserializeOffThread().
NotifyObjectSizeChange()
void v8::internal::LocalHeap::NotifyObjectSizeChange (Tagged< HeapObject > object, int old_size, int new_size, ClearRecordedSlots clear_recorded_slots)
Definition at line 480 of file local-heap.cc.
                                             {
  heap()->NotifyObjectSizeChange(object, old_size, new_size,
                                 clear_recorded_slots);
}
References heap(), and v8::internal::Heap::NotifyObjectSizeChange().
Park()
void v8::internal::LocalHeap::Park () [inline], [private]
Definition at line 342 of file local-heap.h.
              {
    DCHECK(AllowSafepoints::IsAllowed());
    DCHECK(IsSafeForConservativeStackScanning());
    ThreadState expected = ThreadState::Running();
    if (!state_.CompareExchangeWeak(expected, ThreadState::Parked())) {
      ParkSlowPath();
    }
  }
References v8::internal::DCHECK().
ParkAndExecuteCallback()
template<typename Callback >
void v8::internal::LocalHeap::ParkAndExecuteCallback (Callback callback) [inline], [private]
Definition at line 58 of file local-heap-inl.h.
                                                                  {
  // This method is given as a callback to the stack trampoline, when the stack
  // marker has just been set.
#if defined(V8_ENABLE_DIRECT_HANDLE) && defined(ENABLE_SLOW_DCHECKS)
  // Reset the number of direct handles that are below the stack marker.
  // It will be restored before the method returns.
  DirectHandleBase::ResetNumberOfHandlesScope scope;
#endif // V8_ENABLE_DIRECT_HANDLE && ENABLE_SLOW_DCHECKS
  ParkedScope parked(this);
  // Provide the parked scope as a witness, if the callback expects it.
  if constexpr (std::is_invocable_v<Callback, const ParkedScope&>) {
    callback(parked);
  } else {
    callback();
  }
}
Referenced by ExecuteBackgroundThreadWhileParked(), ExecuteMainThreadWhileParked(), and ExecuteWhileParked().
ParkSlowPath()
void v8::internal::LocalHeap::ParkSlowPath () [private]
Definition at line 224 of file local-heap.cc.
                             {
  while (true) {
    ThreadState current_state = ThreadState::Running();
    if (state_.CompareExchangeStrong(current_state, ThreadState::Parked()))
      return;
    // CAS above failed, so state is Running with some additional flag.
    DCHECK(current_state.IsRunning());
    if (is_main_thread()) {
      DCHECK(current_state.IsSafepointRequested() ||
             current_state.IsCollectionRequested());
      if (current_state.IsSafepointRequested()) {
        ThreadState old_state = state_.SetParked();
        heap_->safepoint()->NotifyPark();
        if (old_state.IsCollectionRequested())
          heap_->collection_barrier_->CancelCollectionAndResumeThreads();
        return;
      }
      if (current_state.IsCollectionRequested()) {
        if (!heap()->ignore_local_gc_requests()) {
          heap_->CollectGarbageForBackground(this);
          continue;
        }
        DCHECK(!current_state.IsSafepointRequested());
        if (state_.CompareExchangeStrong(current_state,
                                         current_state.SetParked())) {
          heap_->collection_barrier_->CancelCollectionAndResumeThreads();
          return;
        } else {
          continue;
        }
      }
    } else {
      DCHECK(current_state.IsSafepointRequested());
      DCHECK(!current_state.IsCollectionRequested());
      ThreadState old_state = state_.SetParked();
      CHECK(old_state.IsRunning());
      CHECK(old_state.IsSafepointRequested());
      CHECK(!old_state.IsCollectionRequested());
      heap_->safepoint()->NotifyPark();
      return;
    }
  }
}
References CHECK, v8::internal::Heap::CollectGarbageForBackground(), v8::internal::Heap::collection_barrier_, v8::internal::LocalHeap::AtomicThreadState::CompareExchangeStrong(), v8::internal::DCHECK(), heap(), heap_, is_main_thread(), v8::internal::LocalHeap::ThreadState::IsCollectionRequested(), v8::internal::LocalHeap::ThreadState::IsRunning(), v8::internal::LocalHeap::ThreadState::IsSafepointRequested(), v8::internal::IsolateSafepoint::NotifyPark(), v8::internal::LocalHeap::ThreadState::Parked(), v8::internal::LocalHeap::ThreadState::Running(), v8::internal::Heap::safepoint(), v8::internal::LocalHeap::AtomicThreadState::SetParked(), v8::internal::LocalHeap::ThreadState::SetParked(), and state_.
read_only_space()
ReadOnlySpace* v8::internal::LocalHeap::read_only_space () [inline]
Definition at line 206 of file local-heap.h.
{ return heap_->read_only_space(); }
RemoveGCEpilogueCallback()
void v8::internal::LocalHeap::RemoveGCEpilogueCallback (GCEpilogueCallback * callback, void * data)
Definition at line 462 of file local-heap.cc.
                                                     {
  DCHECK(IsRunning());
  gc_epilogue_callbacks_.Remove(callback, data);
}
References v8::internal::DCHECK(), gc_epilogue_callbacks_, IsRunning(), and v8::internal::GCCallbacksInSafepoint::Remove().
Referenced by v8::internal::interpreter::BytecodeArrayIterator::~BytecodeArrayIterator(), v8::internal::baseline::BytecodeOffsetIterator::~BytecodeOffsetIterator(), v8::internal::RelocatingCharacterStream::~RelocatingCharacterStream(), v8::internal::ScheduleMinorGCTaskObserver::~ScheduleMinorGCTaskObserver(), and v8::internal::JsonStringifier::SimplePropertyKeyCache::~SimplePropertyKeyCache().
Safepoint()
void v8::internal::LocalHeap::Safepoint () [inline]
Definition at line 61 of file local-heap.h.
                   {
    DCHECK(AllowSafepoints::IsAllowed());
    ThreadState current = state_.load_relaxed();
    if (V8_UNLIKELY(current.IsRunningWithSlowPathFlag())) {
      SafepointSlowPath();
    }
  }
References v8::internal::DCHECK(), v8::internal::LocalHeap::ThreadState::IsRunningWithSlowPathFlag(), and V8_UNLIKELY.
Referenced by v8::internal::HeapAllocator::AllocateRaw(), v8::internal::maglev::MaglevGraphBuilder::BuildBody(), v8::internal::maglev::MaglevCodeGenerator::EmitDeopts(), v8::internal::StackGuard::HandleInterrupts(), v8::internal::ConstantPoolPointerForwarder::IterateAndForwardPointers(), v8::internal::StressConcurrentAllocationTask::RunInternal(), v8::internal::GlobalSafepointInterruptTask::RunInternal(), and v8::internal::TickCounter::TickAndMaybeEnterSafepoint().
SafepointSlowPath()
void v8::internal::LocalHeap::SafepointSlowPath () [private]
Definition at line 336 of file local-heap.cc.
                                  {
  ThreadState current_state = state_.load_relaxed();
  DCHECK(current_state.IsRunning());
  if (is_main_thread()) {
    DCHECK(current_state.IsSafepointRequested() ||
           current_state.IsCollectionRequested());
    if (current_state.IsSafepointRequested()) {
      SleepInSafepoint();
    }
    if (current_state.IsCollectionRequested()) {
      heap_->CollectGarbageForBackground(this);
    }
  } else {
    DCHECK(current_state.IsSafepointRequested());
    DCHECK(!current_state.IsCollectionRequested());
    SleepInSafepoint();
  }
}
References v8::internal::Heap::CollectGarbageForBackground(), v8::internal::DCHECK(), heap_, is_main_thread(), v8::internal::LocalHeap::ThreadState::IsCollectionRequested(), v8::internal::LocalHeap::ThreadState::IsRunning(), v8::internal::LocalHeap::ThreadState::IsSafepointRequested(), v8::internal::LocalHeap::AtomicThreadState::load_relaxed(), SleepInSafepoint(), and state_.
SetCurrent()
void v8::internal::LocalHeap::SetCurrent (LocalHeap * local_heap) [static]
Definition at line 36 of file local-heap.cc.
                                                {
  g_current_local_heap_ = local_heap;
}
Referenced by LocalHeap(), and ~LocalHeap().
SetRetryOfFailedAllocation()
void v8::internal::LocalHeap::SetRetryOfFailedAllocation (bool value) [inline]
Definition at line 120 of file local-heap.h.
{ allocation_failed_ = value; }
References v8::internal::value.
Referenced by v8::internal::HeapAllocator::RetryAllocation().
SetUpMainThread()
void v8::internal::LocalHeap::SetUpMainThread (LinearAllocationArea & new_allocation_info, LinearAllocationArea & old_allocation_info) [private]
Definition at line 138 of file local-heap.cc.
                                                                           {
  DCHECK(is_main_thread());
  DCHECK(IsRunning());
  heap_allocator_.Setup(&new_allocation_info, &old_allocation_info);
  SetUpMarkingBarrier();
  SetUpSharedMarking();
}
References v8::internal::DCHECK(), heap_allocator_, is_main_thread(), IsRunning(), v8::internal::HeapAllocator::Setup(), SetUpMarkingBarrier(), and SetUpSharedMarking().
Referenced by v8::internal::Heap::SetUpSpaces().
SetUpMainThreadForTesting()
void v8::internal::LocalHeap::SetUpMainThreadForTesting ()
Definition at line 129 of file local-heap.cc.
                                          {
  Unpark();
  DCHECK(is_main_thread());
  DCHECK(IsRunning());
  heap_allocator_.Setup();
  SetUpMarkingBarrier();
  SetUpSharedMarking();
}
References v8::internal::DCHECK(), heap_allocator_, is_main_thread(), IsRunning(), v8::internal::HeapAllocator::Setup(), SetUpMarkingBarrier(), SetUpSharedMarking(), and Unpark().
SetUpMarkingBarrier()
void v8::internal::LocalHeap::SetUpMarkingBarrier () [private]
Definition at line 147 of file local-heap.cc.
                                    {
  DCHECK_NULL(marking_barrier_);
  marking_barrier_ = std::make_unique<MarkingBarrier>(this);
}
References DCHECK_NULL, and marking_barrier_.
Referenced by LocalHeap(), SetUpMainThread(), and SetUpMainThreadForTesting().
SetUpSharedMarking()
void v8::internal::LocalHeap::SetUpSharedMarking () [private]
Definition at line 152 of file local-heap.cc.
                                   {
#if DEBUG
  // Ensure the thread is either in the running state or holds the safepoint
  // lock. This guarantees that the state of incremental marking can't change
  // concurrently (this requires a safepoint).
  if (is_main_thread()) {
    DCHECK(IsRunning());
  } else {
    heap()->safepoint()->AssertActive();
  }
#endif // DEBUG
  Isolate* isolate = heap_->isolate();
  if (isolate->has_shared_space() && !isolate->is_shared_space_isolate()) {
    if (isolate->shared_space_isolate()
            ->heap()
            ->incremental_marking()
            ->IsMajorMarking()) {
      marking_barrier_->ActivateShared();
    }
  }
}
References v8::internal::IsolateSafepoint::AssertActive(), v8::internal::DCHECK(), v8::internal::Isolate::has_shared_space(), v8::internal::Isolate::heap(), heap(), heap_, v8::internal::Heap::incremental_marking(), is_main_thread(), v8::internal::Isolate::is_shared_space_isolate(), v8::internal::IncrementalMarking::IsMajorMarking(), v8::internal::Heap::isolate(), IsRunning(), marking_barrier_, v8::internal::Heap::safepoint(), and v8::internal::Isolate::shared_space_isolate().
Referenced by LocalHeap(), SetUpMainThread(), and SetUpMainThreadForTesting().
SleepInSafepoint()
void v8::internal::LocalHeap::SleepInSafepoint () [private]
Definition at line 359 of file local-heap.cc.
                                 {
  GCTracer::Scope::ScopeId scope_id;
  ThreadKind thread_kind;
  if (is_main_thread()) {
    scope_id = GCTracer::Scope::SAFEPOINT;
    thread_kind = ThreadKind::kMain;
  } else {
    scope_id = GCTracer::Scope::BACKGROUND_SAFEPOINT;
    thread_kind = ThreadKind::kBackground;
  }
  TRACE_GC1(heap_->tracer(), scope_id, thread_kind);
  ExecuteWithStackMarker([this]() {
    // Parking the running thread here is an optimization. We do not need to
    // wake this thread up to reach the next safepoint.
    ThreadState old_state = state_.SetParked();
    CHECK(old_state.IsRunning());
    CHECK(old_state.IsSafepointRequested());
    CHECK_IMPLIES(old_state.IsCollectionRequested(), is_main_thread());
    heap_->safepoint()->WaitInSafepoint();
    std::optional<IgnoreLocalGCRequests> ignore_gc_requests;
    if (is_main_thread()) ignore_gc_requests.emplace(heap());
    Unpark();
  });
}
References CHECK, CHECK_IMPLIES, ExecuteWithStackMarker(), heap(), heap_, is_main_thread(), v8::internal::LocalHeap::ThreadState::IsCollectionRequested(), v8::internal::LocalHeap::ThreadState::IsRunning(), v8::internal::LocalHeap::ThreadState::IsSafepointRequested(), v8::internal::kBackground, v8::internal::kMain, v8::internal::Heap::safepoint(), v8::internal::LocalHeap::AtomicThreadState::SetParked(), state_, TRACE_GC1, v8::internal::Heap::tracer(), Unpark(), and v8::internal::IsolateSafepoint::WaitInSafepoint().
Referenced by SafepointSlowPath().
SleepInUnpark()
void v8::internal::LocalHeap::SleepInUnpark () [private]
Definition at line 316 of file local-heap.cc.
                              {
  GCTracer::Scope::ScopeId scope_id;
  ThreadKind thread_kind;
  if (is_main_thread()) {
    scope_id = GCTracer::Scope::UNPARK;
    thread_kind = ThreadKind::kMain;
  } else {
    scope_id = GCTracer::Scope::BACKGROUND_UNPARK;
    thread_kind = ThreadKind::kBackground;
  }
  TRACE_GC1(heap_->tracer(), scope_id, thread_kind);
  heap_->safepoint()->WaitInUnpark();
}
References heap_, is_main_thread(), v8::internal::kBackground, v8::internal::kMain, v8::internal::Heap::safepoint(), TRACE_GC1, v8::internal::Heap::tracer(), and v8::internal::IsolateSafepoint::WaitInUnpark().
Referenced by UnparkSlowPath().
UnmarkLinearAllocationsArea()
void v8::internal::LocalHeap::UnmarkLinearAllocationsArea ()
Definition at line 429 of file local-heap.cc.
                                            {
  heap_allocator_.UnmarkLinearAllocationsArea();
}
References heap_allocator_, and v8::internal::HeapAllocator::UnmarkLinearAllocationsArea().
Referenced by v8::internal::IncrementalMarking::PauseBlackAllocation().
UnmarkSharedLinearAllocationsArea()
void v8::internal::LocalHeap::UnmarkSharedLinearAllocationsArea ()
Definition at line 439 of file local-heap.cc.
                                                  {
  if (heap_allocator_.shared_space_allocator()) {
    heap_allocator_.shared_space_allocator()->UnmarkLinearAllocationArea();
  }
}
References heap_allocator_, v8::internal::HeapAllocator::shared_space_allocator(), and v8::internal::MainAllocator::UnmarkLinearAllocationArea().
Referenced by v8::internal::Heap::UnmarkSharedLinearAllocationAreas().
Unpark()
void v8::internal::LocalHeap::Unpark () [inline], [private]
Definition at line 351 of file local-heap.h.
                {
    DCHECK(AllowSafepoints::IsAllowed());
    ThreadState expected = ThreadState::Parked();
    if (!state_.CompareExchangeWeak(expected, ThreadState::Running())) {
      UnparkSlowPath();
    }
  }
References v8::internal::DCHECK().
Referenced by v8::internal::Isolate::Init(), SetUpMainThreadForTesting(), and SleepInSafepoint().
UnparkSlowPath()
void v8::internal::LocalHeap::UnparkSlowPath () [private]
Definition at line 276 of file local-heap.cc.
                               {
  while (true) {
    ThreadState current_state = ThreadState::Parked();
    if (state_.CompareExchangeStrong(current_state, ThreadState::Running()))
      return;
    // CAS above failed, so state is Parked with some additional flag.
    DCHECK(current_state.IsParked());
    if (is_main_thread()) {
      DCHECK(current_state.IsSafepointRequested() ||
             current_state.IsCollectionRequested());
      if (current_state.IsSafepointRequested()) {
        SleepInUnpark();
        continue;
      }
      if (current_state.IsCollectionRequested()) {
        DCHECK(!current_state.IsSafepointRequested());
        if (!state_.CompareExchangeStrong(current_state,
                                          current_state.SetRunning()))
          continue;
        if (!heap()->ignore_local_gc_requests()) {
          heap_->CollectGarbageForBackground(this);
        }
        return;
      }
    } else {
      DCHECK(current_state.IsSafepointRequested());
      DCHECK(!current_state.IsCollectionRequested());
      SleepInUnpark();
    }
  }
}
References v8::internal::Heap::CollectGarbageForBackground(), v8::internal::LocalHeap::AtomicThreadState::CompareExchangeStrong(), v8::internal::DCHECK(), heap(), heap_, is_main_thread(), v8::internal::LocalHeap::ThreadState::IsCollectionRequested(), v8::internal::LocalHeap::ThreadState::IsParked(), v8::internal::LocalHeap::ThreadState::IsSafepointRequested(), v8::internal::LocalHeap::ThreadState::Parked(), v8::internal::LocalHeap::ThreadState::Running(), v8::internal::LocalHeap::ThreadState::SetRunning(), SleepInUnpark(), and state_.
WeakenDescriptorArrays()
void v8::internal::LocalHeap::WeakenDescriptorArrays (GlobalHandleVector< DescriptorArray > strong_descriptor_arrays)
Definition at line 487 of file local-heap.cc.
                                                                  {
  AsHeap()->WeakenDescriptorArrays(std::move(strong_descriptor_arrays));
}
References AsHeap(), and v8::internal::Heap::WeakenDescriptorArrays().
Friends And Related Function Documentation
CollectionBarrier
friend class CollectionBarrier [friend]
Definition at line 413 of file local-heap.h.
GCRootsProviderScope
friend class GCRootsProviderScope [friend]
Definition at line 421 of file local-heap.h.
GlobalSafepoint
friend class GlobalSafepoint [friend]
Definition at line 414 of file local-heap.h.
Heap
friend class Heap [friend]
Definition at line 415 of file local-heap.h.
Isolate
friend class Isolate [friend]
Definition at line 416 of file local-heap.h.
IsolateSafepoint
friend class IsolateSafepoint [friend]
Definition at line 417 of file local-heap.h.
IsolateSafepointScope
friend class IsolateSafepointScope [friend]
Definition at line 418 of file local-heap.h.
ParkedScope
friend class ParkedScope [friend]
Definition at line 419 of file local-heap.h.
UnparkedScope
friend class UnparkedScope [friend]
Definition at line 420 of file local-heap.h.
Member Data Documentation
allocation_failed_
bool v8::internal::LocalHeap::allocation_failed_ [private]
Definition at line 391 of file local-heap.h.
gc_epilogue_callbacks_
GCCallbacksInSafepoint v8::internal::LocalHeap::gc_epilogue_callbacks_ [private]
Definition at line 403 of file local-heap.h.
Referenced by AddGCEpilogueCallback(), InvokeGCEpilogueCallbacksInSafepoint(), RemoveGCEpilogueCallback(), and ~LocalHeap().
handles_
std::unique_ptr<LocalHandles> v8::internal::LocalHeap::handles_ [private]
Definition at line 399 of file local-heap.h.
Referenced by Iterate().
heap_
Heap* v8::internal::LocalHeap::heap_ [private]
Definition at line 381 of file local-heap.h.
Referenced by EnsurePersistentHandles(), is_in_trampoline(), LocalHeap(), ParkSlowPath(), SafepointSlowPath(), SetUpSharedMarking(), SleepInSafepoint(), SleepInUnpark(), UnparkSlowPath(), and ~LocalHeap().
heap_allocator_
HeapAllocator v8::internal::LocalHeap::heap_allocator_ [private]
Definition at line 406 of file local-heap.h.
Referenced by AllocateRaw(), AllocateRawWith(), FreeLinearAllocationAreas(), FreeLinearAllocationAreasAndResetFreeLists(), FreeSharedLinearAllocationAreasAndResetFreeLists(), LocalHeap(), MakeLinearAllocationAreasIterable(), MarkLinearAllocationAreasBlack(), MarkSharedLinearAllocationAreasBlack(), v8::internal::Heap::SetUp(), SetUpMainThread(), SetUpMainThreadForTesting(), UnmarkLinearAllocationsArea(), and UnmarkSharedLinearAllocationsArea().
is_main_thread_
bool v8::internal::LocalHeap::is_main_thread_ [private]
Definition at line 383 of file local-heap.h.
marking_barrier_
std::unique_ptr<MarkingBarrier> v8::internal::LocalHeap::marking_barrier_ [private]
Definition at line 401 of file local-heap.h.
Referenced by LocalHeap(), SetUpMarkingBarrier(), SetUpSharedMarking(), and ~LocalHeap().
nested_parked_scopes_
int v8::internal::LocalHeap::nested_parked_scopes_ [private]
Definition at line 392 of file local-heap.h.
next_
LocalHeap* v8::internal::LocalHeap::next_ [private]
Definition at line 397 of file local-heap.h.
Referenced by v8::internal::IsolateSafepoint::AddLocalHeap(), v8::internal::IsolateSafepoint::AssertMainThreadIsOnlyThread(), v8::internal::IsolateSafepoint::ClearSafepointRequestedFlags(), v8::internal::IsolateSafepoint::Iterate(), v8::internal::IsolateSafepoint::IterateLocalHeaps(), v8::internal::IsolateSafepoint::RemoveLocalHeap(), and v8::internal::IsolateSafepoint::SetSafepointRequestedFlags().
persistent_handles_
std::unique_ptr<PersistentHandles> v8::internal::LocalHeap::persistent_handles_ [private]
Definition at line 400 of file local-heap.h.
Referenced by AttachPersistentHandles(), DetachPersistentHandles(), EnsurePersistentHandles(), and LocalHeap().
prev_
LocalHeap* v8::internal::LocalHeap::prev_ [private]
Definition at line 396 of file local-heap.h.
Referenced by v8::internal::IsolateSafepoint::AddLocalHeap(), and v8::internal::IsolateSafepoint::RemoveLocalHeap().
ptr_compr_cage_access_scope_
V8_NO_UNIQUE_ADDRESS PtrComprCageAccessScope v8::internal::LocalHeap::ptr_compr_cage_access_scope_ [private]
Definition at line 382 of file local-heap.h.
roots_providers_
base::SmallVector<GCRootsProvider*, 4> v8::internal::LocalHeap::roots_providers_ [private]
Definition at line 404 of file local-heap.h.
Referenced by v8::internal::GCRootsProviderScope::GCRootsProviderScope(), Iterate(), and v8::internal::GCRootsProviderScope::~GCRootsProviderScope().
saved_current_isolate_
Isolate* v8::internal::LocalHeap::saved_current_isolate_ = nullptr [private]
Definition at line 394 of file local-heap.h.
Referenced by LocalHeap(), and ~LocalHeap().
saved_marking_barrier_
MarkingBarrier* v8::internal::LocalHeap::saved_marking_barrier_ = nullptr [private]
Definition at line 408 of file local-heap.h.
Referenced by LocalHeap(), and ~LocalHeap().
stack_
::heap::base::Stack v8::internal::LocalHeap::stack_ [private]
Definition at line 411 of file local-heap.h.
Referenced by LocalHeap(), and v8::internal::Heap::stack().
state_
AtomicThreadState v8::internal::LocalHeap::state_ [private]
Definition at line 385 of file local-heap.h.
Referenced by v8::internal::Heap::CollectGarbageFromAnyThread(), v8::internal::Heap::GarbageCollectionEpilogueInSafepoint(), IsParked(), IsRunning(), ParkSlowPath(), SafepointSlowPath(), SleepInSafepoint(), and UnparkSlowPath().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/local-heap.h
/mnt/V8SourceCode/src/heap/local-heap-inl.h
/mnt/V8SourceCode/src/heap/local-heap.cc