v8::internal::compiler::ImmediateOperand Class Reference
#include <instruction.h>
Public Types
enum ImmediateType { INLINE_INT32
, INLINE_INT64
, INDEXED_RPO
, INDEXED_IMM
 }
using TypeField = KindField::Next< ImmediateType, 2 >
using ValueField = base::BitField64< int32_t, 32, 32 >
Public Member Functions
ImmediateOperand (ImmediateType type, int32_t value)
ImmediateType type () const
int32_t inline_int32_value () const
int64_t inline_int64_value () const
int32_t indexed_value () const
Static Public Member Functions
static ImmediateOperand * New (Zone *zone, ImmediateType type, int32_t value)
Additional Inherited Members
Detailed Description
Definition at line 420 of file instruction.h.
Member Typedef Documentation
TypeField
using v8::internal::compiler::ImmediateOperand::TypeField = KindField::Next<ImmediateType, 2>
Definition at line 454 of file instruction.h.
ValueField
using v8::internal::compiler::ImmediateOperand::ValueField = base::BitField64<int32_t, 32, 32>
Definition at line 456 of file instruction.h.
Member Enumeration Documentation
ImmediateType
enum v8::internal::compiler::ImmediateOperand::ImmediateType
Enumerator
INLINE_INT32
INLINE_INT64
INDEXED_RPO
INDEXED_IMM
Definition at line 422 of file instruction.h.
{ INLINE_INT32, INLINE_INT64, INDEXED_RPO, INDEXED_IMM };
Constructor & Destructor Documentation
ImmediateOperand()
v8::internal::compiler::ImmediateOperand::ImmediateOperand (ImmediateType type, int32_t value) [inline], [explicit]
Definition at line 424 of file instruction.h.
      : InstructionOperand(IMMEDIATE) {
    value_ |= TypeField::encode(type);
    value_ |= static_cast<uint64_t>(static_cast<int64_t>(value))
              << ValueField::kShift;
  }
References v8::internal::tracing::type, v8::internal::value, and v8::internal::compiler::InstructionOperand::value_.
Member Function Documentation
indexed_value()
int32_t v8::internal::compiler::ImmediateOperand::indexed_value () const [inline]
Definition at line 443 of file instruction.h.
                                {
    DCHECK(type() == INDEXED_IMM || type() == INDEXED_RPO);
    return static_cast<int64_t>(value_) >> ValueField::kShift;
  }
References v8::internal::DCHECK(), v8::internal::tracing::type, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::InstructionSequence::GetImmediate(), v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::GetValue(), and v8::internal::compiler::operator<<().
inline_int32_value()
int32_t v8::internal::compiler::ImmediateOperand::inline_int32_value () const [inline]
Definition at line 433 of file instruction.h.
                                     {
    DCHECK_EQ(INLINE_INT32, type());
    return static_cast<int64_t>(value_) >> ValueField::kShift;
  }
References DCHECK_EQ, v8::internal::tracing::type, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::InstructionSequence::GetImmediate(), v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::GetValue(), and v8::internal::compiler::operator<<().
inline_int64_value()
int64_t v8::internal::compiler::ImmediateOperand::inline_int64_value () const [inline]
Definition at line 438 of file instruction.h.
                                     {
    DCHECK_EQ(INLINE_INT64, type());
    return static_cast<int64_t>(value_) >> ValueField::kShift;
  }
References DCHECK_EQ, v8::internal::tracing::type, and v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::InstructionSequence::GetImmediate(), v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::GetValue(), and v8::internal::compiler::operator<<().
New()
static ImmediateOperand* v8::internal::compiler::ImmediateOperand::New (Zone * zone, ImmediateType type, int32_t value) [inline], [static]
Definition at line 448 of file instruction.h.
                                                                              {
    return InstructionOperand::New(zone, ImmediateOperand(type, value));
  }
References v8::internal::compiler::InstructionOperand::New(), v8::internal::tracing::type, and v8::internal::value.
type()
ImmediateType v8::internal::compiler::ImmediateOperand::type () const [inline]
Definition at line 431 of file instruction.h.
{ return TypeField::decode(value_); }
References v8::internal::compiler::InstructionOperand::value_.
Referenced by v8::internal::compiler::InstructionSequence::GetImmediate(), v8::internal::compiler::anonymous_namespace{register-allocator-verifier.cc}::GetValue(), and v8::internal::compiler::operator<<().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction.h