v8::internal::TextNode Class Reference
#include <regexp-nodes.h>
Public Member Functions
TextNode (ZoneList< TextElement > *elms, bool read_backward, RegExpNode *on_success)
TextNode (RegExpClassRanges *that, bool read_backward, RegExpNode *on_success)
TextNode * AsTextNode () override
void Accept (NodeVisitor *visitor) override
void Emit (RegExpCompiler *compiler, Trace *trace) override
void GetQuickCheckDetails (QuickCheckDetails *details, RegExpCompiler *compiler, int characters_filled_in, bool not_at_start) override
ZoneList< TextElement > * elements ()
bool read_backward ()
void MakeCaseIndependent (Isolate *isolate, bool is_one_byte, RegExpFlags flags)
int FixedLengthLoopLength () override
RegExpNode * GetSuccessorOfOmnivorousTextNode (RegExpCompiler *compiler) override
void FillInBMInfo (Isolate *isolate, int offset, int budget, BoyerMooreLookahead *bm, bool not_at_start) override
void CalculateOffsets ()
RegExpNode * FilterOneByte (int depth, RegExpCompiler *compiler) override
int Length ()
Static Public Member Functions
static TextNode * CreateForCharacterRanges (Zone *zone, ZoneList< CharacterRange > *ranges, bool read_backward, RegExpNode *on_success)
static TextNode * CreateForSurrogatePair (Zone *zone, CharacterRange lead, ZoneList< CharacterRange > *trail_ranges, bool read_backward, RegExpNode *on_success)
static TextNode * CreateForSurrogatePair (Zone *zone, ZoneList< CharacterRange > *lead_ranges, CharacterRange trail, bool read_backward, RegExpNode *on_success)
Private Types
enum TextEmitPassType {
NON_LATIN1_MATCH
, SIMPLE_CHARACTER_MATCH
, NON_LETTER_CHARACTER_MATCH
, CASE_CHARACTER_MATCH
,
CHARACTER_CLASS_MATCH
 }
Private Member Functions
void TextEmitPass (RegExpCompiler *compiler, TextEmitPassType pass, bool preloaded, Trace *trace, bool first_element_checked, int *checked_up_to)
Private Attributes
ZoneList< TextElement > * elms_
bool read_backward_
Additional Inherited Members
Detailed Description
Definition at line 451 of file regexp-nodes.h.
Member Enumeration Documentation
TextEmitPassType
enum v8::internal::TextNode::TextEmitPassType [private]
Enumerator
NON_LATIN1_MATCH
SIMPLE_CHARACTER_MATCH
NON_LETTER_CHARACTER_MATCH
CASE_CHARACTER_MATCH
CHARACTER_CLASS_MATCH
Definition at line 497 of file regexp-nodes.h.
                        {
    NON_LATIN1_MATCH, // Check for characters that can never match.
    SIMPLE_CHARACTER_MATCH, // Case-dependent single character check.
    NON_LETTER_CHARACTER_MATCH, // Check characters that have no case equivs.
    CASE_CHARACTER_MATCH, // Case-independent single character check.
    CHARACTER_CLASS_MATCH // Character class.
  };
Constructor & Destructor Documentation
TextNode() [1/2]
v8::internal::TextNode::TextNode (ZoneList< TextElement > * elms, bool read_backward, RegExpNode * on_success) [inline]
Definition at line 453 of file regexp-nodes.h.
      : SeqRegExpNode(on_success), elms_(elms), read_backward_(read_backward) {}
TextNode() [2/2]
v8::internal::TextNode::TextNode (RegExpClassRanges * that, bool read_backward, RegExpNode * on_success) [inline]
Definition at line 456 of file regexp-nodes.h.
      : SeqRegExpNode(on_success),
        elms_(zone()->New<ZoneList<TextElement>>(1, zone())),
        read_backward_(read_backward) {
    elms_->Add(TextElement::ClassRanges(that), zone());
  }
References v8::internal::TextElement::ClassRanges(), elms_, and v8::internal::RegExpNode::zone().
Member Function Documentation
Accept()
void v8::internal::TextNode::Accept (NodeVisitor * visitor) [override], [virtual]
Implements v8::internal::RegExpNode.
AsTextNode()
TextNode* v8::internal::TextNode::AsTextNode () [inline], [override]
Definition at line 477 of file regexp-nodes.h.
{ return this; }
CalculateOffsets()
void v8::internal::TextNode::CalculateOffsets ()
Definition at line 3619 of file regexp-compiler.cc.
                                {
  int element_count = elements()->length();
  // Set up the offsets of the elements relative to the start. This is a fixed
  // quantity since a TextNode can only contain fixed-width things.
  int cp_offset = 0;
  for (int i = 0; i < element_count; i++) {
    TextElement& elm = elements()->at(i);
    elm.set_cp_offset(cp_offset);
    cp_offset += elm.length();
  }
}
References elements(), v8::internal::TextElement::length(), and v8::internal::TextElement::set_cp_offset().
Referenced by v8::internal::Analysis< Propagators >::VisitText().
CreateForCharacterRanges()
TextNode * v8::internal::TextNode::CreateForCharacterRanges (Zone * zone, ZoneList< CharacterRange > * ranges, bool read_backward, RegExpNode * on_success) [static]
Definition at line 2502 of file regexp-compiler.cc.
                                                                     {
  DCHECK_NOT_NULL(ranges);
  // TODO(jgruber): There's no fundamental need to create this
  // RegExpClassRanges; we could refactor to avoid the allocation.
  return zone->New<TextNode>(zone->New<RegExpClassRanges>(zone, ranges),
                             read_backward, on_success);
}
References DCHECK_NOT_NULL, v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), read_backward(), and v8::internal::RegExpNode::zone().
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddBmpCharacters(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::BoundaryAssertionAsLookaround(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::MatchAndNegativeLookaroundInReadDirection(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::NegativeLookaroundAgainstReadDirectionAndMatch(), v8::internal::RegExpCompiler::OptionallyStepBackToLeadSurrogate(), and v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::UnanchoredAdvance().
CreateForSurrogatePair() [1/2]
TextNode * v8::internal::TextNode::CreateForSurrogatePair (Zone * zone, CharacterRange lead, ZoneList< CharacterRange > * trail_ranges, bool read_backward, RegExpNode * on_success) [static]
Definition at line 2513 of file regexp-compiler.cc.
                                                {
  ZoneList<TextElement>* elms = zone->New<ZoneList<TextElement>>(2, zone);
  if (lead.from() == lead.to()) {
    ZoneList<base::uc16> lead_surrogate(1, zone);
    lead_surrogate.Add(lead.from(), zone);
    RegExpAtom* atom = zone->New<RegExpAtom>(lead_surrogate.ToConstVector());
    elms->Add(TextElement::Atom(atom), zone);
  } else {
    ZoneList<CharacterRange>* lead_ranges = CharacterRange::List(zone, lead);
    elms->Add(TextElement::ClassRanges(
                  zone->New<RegExpClassRanges>(zone, lead_ranges)),
              zone);
  }
  elms->Add(TextElement::ClassRanges(
                zone->New<RegExpClassRanges>(zone, trail_ranges)),
            zone);
  return zone->New<TextNode>(elms, read_backward, on_success);
}
References v8::internal::ZoneList< T >::Add(), v8::internal::TextElement::Atom(), v8::internal::TextElement::ClassRanges(), v8::internal::CharacterRange::from(), v8::internal::CharacterRange::List(), v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), read_backward(), v8::internal::CharacterRange::to(), v8::internal::ZoneList< T >::ToConstVector(), and v8::internal::RegExpNode::zone().
Referenced by v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs().
CreateForSurrogatePair() [2/2]
TextNode * v8::internal::TextNode::CreateForSurrogatePair (Zone * zone, ZoneList< CharacterRange > * lead_ranges, CharacterRange trail, bool read_backward, RegExpNode * on_success) [static]
Definition at line 2534 of file regexp-compiler.cc.
                                                {
  ZoneList<CharacterRange>* trail_ranges = CharacterRange::List(zone, trail);
  ZoneList<TextElement>* elms = zone->New<ZoneList<TextElement>>(2, zone);
  elms->Add(
      TextElement::ClassRanges(zone->New<RegExpClassRanges>(zone, lead_ranges)),
      zone);
  elms->Add(TextElement::ClassRanges(
                zone->New<RegExpClassRanges>(zone, trail_ranges)),
            zone);
  return zone->New<TextNode>(elms, read_backward, on_success);
}
References v8::internal::ZoneList< T >::Add(), v8::internal::TextElement::ClassRanges(), v8::internal::CharacterRange::List(), v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), read_backward(), and v8::internal::RegExpNode::zone().
elements()
ZoneList<TextElement>* v8::internal::TextNode::elements () [inline]
Definition at line 483 of file regexp-nodes.h.
{ return elms_; }
References elms_.
Referenced by CalculateOffsets(), FillInBMInfo(), FilterOneByte(), GetQuickCheckDetails(), GetSuccessorOfOmnivorousTextNode(), Length(), MakeCaseIndependent(), and TextEmitPass().
Emit()
void v8::internal::TextNode::Emit (RegExpCompiler * compiler, Trace * trace) [override], [virtual]
Implements v8::internal::RegExpNode.
Definition at line 2554 of file regexp-compiler.cc.
                                                          {
  LimitResult limit_result = LimitVersions(compiler, trace);
  if (limit_result == DONE) return;
  DCHECK(limit_result == CONTINUE);
  if (trace->cp_offset() + Length() > RegExpMacroAssembler::kMaxCPOffset) {
    compiler->SetRegExpTooBig();
    return;
  }
  if (compiler->one_byte()) {
    int dummy = 0;
    TextEmitPass(compiler, NON_LATIN1_MATCH, false, trace, false, &dummy);
  }
  bool first_elt_done = false;
  int bound_checked_to = trace->cp_offset() - 1;
  bound_checked_to += trace->bound_checked_up_to();
  // If a character is preloaded into the current character register then
  // check that first to save reloading it.
  for (int twice = 0; twice < 2; twice++) {
    bool is_preloaded_pass = twice == 0;
    if (is_preloaded_pass && trace->characters_preloaded() != 1) continue;
    if (IsIgnoreCase(compiler->flags())) {
      TextEmitPass(compiler, NON_LETTER_CHARACTER_MATCH, is_preloaded_pass,
                   trace, first_elt_done, &bound_checked_to);
      TextEmitPass(compiler, CASE_CHARACTER_MATCH, is_preloaded_pass, trace,
                   first_elt_done, &bound_checked_to);
    } else {
      TextEmitPass(compiler, SIMPLE_CHARACTER_MATCH, is_preloaded_pass, trace,
                   first_elt_done, &bound_checked_to);
    }
    TextEmitPass(compiler, CHARACTER_CLASS_MATCH, is_preloaded_pass, trace,
                 first_elt_done, &bound_checked_to);
    first_elt_done = true;
  }
  Trace successor_trace(*trace);
  // If we advance backward, we may end up at the start.
  successor_trace.AdvanceCurrentPositionInTrace(
      read_backward() ? -Length() : Length(), compiler);
  successor_trace.set_at_start(read_backward() ? Trace::UNKNOWN
                                               : Trace::FALSE_VALUE);
  RecursionCheck rc(compiler);
  on_success()->Emit(compiler, &successor_trace);
}
References v8::internal::Trace::AdvanceCurrentPositionInTrace(), v8::internal::Trace::bound_checked_up_to(), CASE_CHARACTER_MATCH, CHARACTER_CLASS_MATCH, v8::internal::Trace::characters_preloaded(), v8::internal::RegExpNode::CONTINUE, v8::internal::Trace::cp_offset(), v8::internal::DCHECK(), v8::internal::RegExpNode::DONE, v8::internal::RegExpNode::Emit(), v8::internal::Trace::FALSE_VALUE, v8::internal::RegExpCompiler::flags(), v8::internal::RegExpMacroAssembler::kMaxCPOffset, Length(), v8::internal::RegExpNode::LimitVersions(), NON_LATIN1_MATCH, NON_LETTER_CHARACTER_MATCH, v8::internal::SeqRegExpNode::on_success(), v8::internal::RegExpCompiler::one_byte(), read_backward(), v8::internal::Trace::set_at_start(), v8::internal::RegExpCompiler::SetRegExpTooBig(), SIMPLE_CHARACTER_MATCH, TextEmitPass(), and v8::internal::Trace::UNKNOWN.
FillInBMInfo()
void v8::internal::TextNode::FillInBMInfo (Isolate * isolate, int offset, int budget, BoyerMooreLookahead * bm, bool not_at_start) [override], [virtual]
Reimplemented from v8::internal::SeqRegExpNode.
Definition at line 3973 of file regexp-compiler.cc.
                                                                        {
  if (initial_offset >= bm->length()) return;
  if (read_backward()) return;
  int offset = initial_offset;
  int max_char = bm->max_char();
  for (int i = 0; i < elements()->length(); i++) {
    if (offset >= bm->length()) {
      if (initial_offset == 0) set_bm_info(not_at_start, bm);
      return;
    }
    TextElement text = elements()->at(i);
    if (text.text_type() == TextElement::ATOM) {
      RegExpAtom* atom = text.atom();
      for (int j = 0; j < atom->length(); j++, offset++) {
        if (offset >= bm->length()) {
          if (initial_offset == 0) set_bm_info(not_at_start, bm);
          return;
        }
        base::uc16 character = atom->data()[j];
        if (IsIgnoreCase(bm->compiler()->flags())) {
          unibrow::uchar chars[4];
          int length = GetCaseIndependentLetters(isolate, character,
                                                 bm->compiler(), chars, 4);
          for (int k = 0; k < length; k++) {
            bm->Set(offset, chars[k]);
          }
        } else {
          if (character <= max_char) bm->Set(offset, character);
        }
      }
    } else {
      DCHECK_EQ(TextElement::CLASS_RANGES, text.text_type());
      RegExpClassRanges* class_ranges = text.class_ranges();
      ZoneList<CharacterRange>* ranges = class_ranges->ranges(zone());
      if (class_ranges->is_negated()) {
        bm->SetAll(offset);
      } else {
        for (int k = 0; k < ranges->length(); k++) {
          CharacterRange& range = ranges->at(k);
          if (static_cast<int>(range.from()) > max_char) continue;
          int to = std::min(max_char, static_cast<int>(range.to()));
          bm->SetInterval(offset, Interval(range.from(), to));
        }
      }
      offset++;
    }
  }
  if (offset >= bm->length()) {
    if (initial_offset == 0) set_bm_info(not_at_start, bm);
    return;
  }
  on_success()->FillInBMInfo(isolate, offset, budget - 1, bm,
                             true); // Not at start after a text node.
  if (initial_offset == 0) set_bm_info(not_at_start, bm);
}
References v8::internal::ZoneList< T >::at(), v8::internal::TextElement::ATOM, v8::internal::TextElement::atom(), v8::internal::character, v8::internal::TextElement::CLASS_RANGES, v8::internal::TextElement::class_ranges(), v8::internal::BoyerMooreLookahead::compiler(), v8::internal::RegExpAtom::data(), DCHECK_EQ, elements(), v8::internal::RegExpNode::FillInBMInfo(), v8::internal::RegExpCompiler::flags(), v8::internal::CharacterRange::from(), v8::internal::anonymous_namespace{regexp-compiler.cc}::GetCaseIndependentLetters(), v8::internal::RegExpClassRanges::is_negated(), v8::internal::length, v8::internal::BoyerMooreLookahead::length(), v8::internal::RegExpAtom::length(), v8::internal::ZoneList< T >::length(), v8::internal::BoyerMooreLookahead::max_char(), v8::internal::SeqRegExpNode::on_success(), v8::internal::RegExpClassRanges::ranges(), read_backward(), v8::internal::BoyerMooreLookahead::Set(), v8::internal::RegExpNode::set_bm_info(), v8::internal::BoyerMooreLookahead::SetAll(), v8::internal::BoyerMooreLookahead::SetInterval(), v8::internal::TextElement::text_type(), v8::internal::CharacterRange::to(), and v8::internal::RegExpNode::zone().
FilterOneByte()
RegExpNode * v8::internal::TextNode::FilterOneByte (int depth, RegExpCompiler * compiler) [override], [virtual]
Reimplemented from v8::internal::SeqRegExpNode.
Definition at line 1940 of file regexp-compiler.cc.
                                                                       {
  RegExpFlags flags = compiler->flags();
  if (info()->replacement_calculated) return replacement();
  if (depth < 0) return this;
  DCHECK(!info()->visited);
  VisitMarker marker(info());
  int element_count = elements()->length();
  for (int i = 0; i < element_count; i++) {
    TextElement elm = elements()->at(i);
    if (elm.text_type() == TextElement::ATOM) {
      base::Vector<const base::uc16> quarks = elm.atom()->data();
      for (int j = 0; j < quarks.length(); j++) {
        base::uc16 c = quarks[j];
        if (!IsIgnoreCase(flags)) {
          if (c > String::kMaxOneByteCharCode) return set_replacement(nullptr);
        } else {
          unibrow::uchar chars[4];
          int length = GetCaseIndependentLetters(compiler->isolate(), c,
                                                 compiler, chars, 4);
          if (length == 0 || chars[0] > String::kMaxOneByteCharCode) {
            return set_replacement(nullptr);
          }
        }
      }
    } else {
      // A character class can also be impossible to match in one-byte mode.
      DCHECK(elm.text_type() == TextElement::CLASS_RANGES);
      RegExpClassRanges* cr = elm.class_ranges();
      ZoneList<CharacterRange>* ranges = cr->ranges(zone());
      CharacterRange::Canonicalize(ranges);
      // Now they are in order so we only need to look at the first.
      // If we are in non-Unicode case independent mode then we need
      // to be a bit careful here, because the character classes have
      // not been case-desugared yet, but there are characters and ranges
      // that can become Latin-1 when case is considered.
      int range_count = ranges->length();
      if (cr->is_negated()) {
        if (range_count != 0 && ranges->at(0).from() == 0 &&
            ranges->at(0).to() >= String::kMaxOneByteCharCode) {
          bool case_complications = !IsEitherUnicode(flags) &&
                                    IsIgnoreCase(flags) &&
                                    RangesContainLatin1Equivalents(ranges);
          if (!case_complications) {
            return set_replacement(nullptr);
          }
        }
      } else {
        if (range_count == 0 ||
            ranges->at(0).from() > String::kMaxOneByteCharCode) {
          bool case_complications = !IsEitherUnicode(flags) &&
                                    IsIgnoreCase(flags) &&
                                    RangesContainLatin1Equivalents(ranges);
          if (!case_complications) {
            return set_replacement(nullptr);
          }
        }
      }
    }
  }
  return FilterSuccessor(depth - 1, compiler);
}
References v8::internal::ZoneList< T >::at(), v8::internal::TextElement::ATOM, v8::internal::TextElement::atom(), v8::internal::CharacterRange::Canonicalize(), v8::internal::TextElement::CLASS_RANGES, v8::internal::TextElement::class_ranges(), v8::internal::RegExpAtom::data(), v8::internal::DCHECK(), elements(), v8::internal::SeqRegExpNode::FilterSuccessor(), v8::internal::RegExpCompiler::flags(), v8::internal::flags, v8::internal::anonymous_namespace{regexp-compiler.cc}::GetCaseIndependentLetters(), v8::internal::RegExpNode::info(), v8::internal::RegExpClassRanges::is_negated(), v8::internal::IsEitherUnicode(), v8::internal::RegExpCompiler::isolate(), v8::internal::String::kMaxOneByteCharCode, v8::base::Vector< T >::length(), v8::internal::length, v8::internal::ZoneList< T >::length(), v8::internal::RegExpClassRanges::ranges(), v8::internal::anonymous_namespace{regexp-compiler.cc}::RangesContainLatin1Equivalents(), v8::internal::RegExpNode::replacement(), v8::internal::RegExpNode::set_replacement(), v8::internal::TextElement::text_type(), and v8::internal::RegExpNode::zone().
FixedLengthLoopLength()
int v8::internal::TextNode::FixedLengthLoopLength () [override], [virtual]
Reimplemented from v8::internal::RegExpNode.
Definition at line 2644 of file regexp-compiler.cc.
{ return Length(); }
References Length().
GetQuickCheckDetails()
void v8::internal::TextNode::GetQuickCheckDetails (QuickCheckDetails * details, RegExpCompiler * compiler, int characters_filled_in, bool not_at_start) [override], [virtual]
Implements v8::internal::RegExpNode.
Definition at line 1654 of file regexp-compiler.cc.
                                                       {
  // Do not collect any quick check details if the text node reads backward,
  // since it reads in the opposite direction than we use for quick checks.
  if (read_backward()) return;
  Isolate* isolate = compiler->macro_assembler()->isolate();
  DCHECK(characters_filled_in < details->characters());
  int characters = details->characters();
  const uint32_t char_mask = CharMask(compiler->one_byte());
  for (int k = 0; k < elements()->length(); k++) {
    TextElement elm = elements()->at(k);
    if (elm.text_type() == TextElement::ATOM) {
      base::Vector<const base::uc16> quarks = elm.atom()->data();
      for (int i = 0; i < characters && i < quarks.length(); i++) {
        QuickCheckDetails::Position* pos =
            details->positions(characters_filled_in);
        base::uc16 c = quarks[i];
        if (IsIgnoreCase(compiler->flags())) {
          unibrow::uchar chars[4];
          int length =
              GetCaseIndependentLetters(isolate, c, compiler, chars, 4);
          if (length == 0) {
            // This can happen because all case variants are non-Latin1, but we
            // know the input is Latin1.
            details->set_cannot_match();
            pos->determines_perfectly = false;
            return;
          }
          if (length == 1) {
            // This letter has no case equivalents, so it's nice and simple
            // and the mask-compare will determine definitely whether we have
            // a match at this character position.
            pos->mask = char_mask;
            pos->value = chars[0];
            pos->determines_perfectly = true;
          } else {
            uint32_t common_bits = char_mask;
            uint32_t bits = chars[0];
            for (int j = 1; j < length; j++) {
              uint32_t differing_bits = ((chars[j] & common_bits) ^ bits);
              common_bits ^= differing_bits;
              bits &= common_bits;
            }
            // If length is 2 and common bits has only one zero in it then
            // our mask and compare instruction will determine definitely
            // whether we have a match at this character position. Otherwise
            // it can only be an approximate check.
            uint32_t one_zero = (common_bits | ~char_mask);
            if (length == 2 && ((~one_zero) & ((~one_zero) - 1)) == 0) {
              pos->determines_perfectly = true;
            }
            pos->mask = common_bits;
            pos->value = bits;
          }
        } else {
          // Don't ignore case. Nice simple case where the mask-compare will
          // determine definitely whether we have a match at this character
          // position.
          if (c > char_mask) {
            details->set_cannot_match();
            pos->determines_perfectly = false;
            return;
          }
          pos->mask = char_mask;
          pos->value = c;
          pos->determines_perfectly = true;
        }
        characters_filled_in++;
        DCHECK(characters_filled_in <= details->characters());
        if (characters_filled_in == details->characters()) {
          return;
        }
      }
    } else {
      QuickCheckDetails::Position* pos =
          details->positions(characters_filled_in);
      RegExpClassRanges* tree = elm.class_ranges();
      ZoneList<CharacterRange>* ranges = tree->ranges(zone());
      if (tree->is_negated() || ranges->is_empty()) {
        // A quick check uses multi-character mask and compare. There is no
        // useful way to incorporate a negative char class into this scheme
        // so we just conservatively create a mask and value that will always
        // succeed.
        // Likewise for empty ranges (empty ranges can occur e.g. when
        // compiling for one-byte subjects and impossible (non-one-byte) ranges
        // have been removed).
        pos->mask = 0;
        pos->value = 0;
      } else {
        int first_range = 0;
        while (ranges->at(first_range).from() > char_mask) {
          first_range++;
          if (first_range == ranges->length()) {
            details->set_cannot_match();
            pos->determines_perfectly = false;
            return;
          }
        }
        CharacterRange range = ranges->at(first_range);
        const base::uc32 first_from = range.from();
        const base::uc32 first_to =
            (range.to() > char_mask) ? char_mask : range.to();
        const uint32_t differing_bits = (first_from ^ first_to);
        // A mask and compare is only perfect if the differing bits form a
        // number like 00011111 with one single block of trailing 1s.
        if ((differing_bits & (differing_bits + 1)) == 0 &&
            first_from + differing_bits == first_to) {
          pos->determines_perfectly = true;
        }
        uint32_t common_bits = ~SmearBitsRight(differing_bits);
        uint32_t bits = (first_from & common_bits);
        for (int i = first_range + 1; i < ranges->length(); i++) {
          range = ranges->at(i);
          const base::uc32 from = range.from();
          if (from > char_mask) continue;
          const base::uc32 to =
              (range.to() > char_mask) ? char_mask : range.to();
          // Here we are combining more ranges into the mask and compare
          // value. With each new range the mask becomes more sparse and
          // so the chances of a false positive rise. A character class
          // with multiple ranges is assumed never to be equivalent to a
          // mask and compare operation.
          pos->determines_perfectly = false;
          uint32_t new_common_bits = (from ^ to);
          new_common_bits = ~SmearBitsRight(new_common_bits);
          common_bits &= new_common_bits;
          bits &= new_common_bits;
          uint32_t new_differing_bits = (from & common_bits) ^ bits;
          common_bits ^= new_differing_bits;
          bits &= common_bits;
        }
        pos->mask = common_bits;
        pos->value = bits;
      }
      characters_filled_in++;
      DCHECK(characters_filled_in <= details->characters());
      if (characters_filled_in == details->characters()) return;
    }
  }
  DCHECK(characters_filled_in != details->characters());
  if (!details->cannot_match()) {
    on_success()->GetQuickCheckDetails(details, compiler, characters_filled_in,
                                       true);
  }
}
References v8::internal::ZoneList< T >::at(), v8::internal::TextElement::ATOM, v8::internal::TextElement::atom(), v8::internal::QuickCheckDetails::cannot_match(), v8::internal::QuickCheckDetails::characters(), v8::internal::anonymous_namespace{regexp-compiler.cc}::CharMask(), v8::internal::TextElement::class_ranges(), v8::internal::RegExpAtom::data(), v8::internal::DCHECK(), v8::internal::QuickCheckDetails::Position::determines_perfectly, elements(), v8::internal::RegExpCompiler::flags(), v8::internal::CharacterRange::from(), v8::internal::anonymous_namespace{regexp-compiler.cc}::GetCaseIndependentLetters(), v8::internal::RegExpNode::GetQuickCheckDetails(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::ZoneList< T >::is_empty(), v8::internal::RegExpClassRanges::is_negated(), v8::internal::RegExpMacroAssembler::isolate(), v8::base::Vector< T >::length(), v8::internal::length, v8::internal::ZoneList< T >::length(), v8::internal::RegExpCompiler::macro_assembler(), v8::internal::QuickCheckDetails::Position::mask, v8::internal::SeqRegExpNode::on_success(), v8::internal::RegExpCompiler::one_byte(), v8::internal::QuickCheckDetails::positions(), v8::internal::RegExpClassRanges::ranges(), read_backward(), v8::internal::QuickCheckDetails::set_cannot_match(), v8::internal::anonymous_namespace{regexp-compiler.cc}::SmearBitsRight(), v8::internal::TextElement::text_type(), v8::internal::CharacterRange::to(), v8::internal::QuickCheckDetails::Position::value, and v8::internal::RegExpNode::zone().
GetSuccessorOfOmnivorousTextNode()
RegExpNode * v8::internal::TextNode::GetSuccessorOfOmnivorousTextNode (RegExpCompiler * compiler) [override], [virtual]
Reimplemented from v8::internal::RegExpNode.
Definition at line 2646 of file regexp-compiler.cc.
                              {
  if (read_backward()) return nullptr;
  if (elements()->length() != 1) return nullptr;
  TextElement elm = elements()->at(0);
  if (elm.text_type() != TextElement::CLASS_RANGES) return nullptr;
  RegExpClassRanges* node = elm.class_ranges();
  ZoneList<CharacterRange>* ranges = node->ranges(zone());
  CharacterRange::Canonicalize(ranges);
  if (node->is_negated()) {
    return ranges->length() == 0 ? on_success() : nullptr;
  }
  if (ranges->length() != 1) return nullptr;
  const base::uc32 max_char = MaxCodeUnit(compiler->one_byte());
  return ranges->at(0).IsEverything(max_char) ? on_success() : nullptr;
}
References v8::internal::ZoneList< T >::at(), v8::internal::CharacterRange::Canonicalize(), v8::internal::TextElement::CLASS_RANGES, v8::internal::TextElement::class_ranges(), elements(), v8::internal::RegExpClassRanges::is_negated(), v8::internal::length, v8::internal::ZoneList< T >::length(), v8::internal::anonymous_namespace{regexp-compiler.cc}::MaxCodeUnit(), v8::internal::SeqRegExpNode::on_success(), v8::internal::RegExpCompiler::one_byte(), v8::internal::RegExpClassRanges::ranges(), read_backward(), v8::internal::TextElement::text_type(), and v8::internal::RegExpNode::zone().
Length()
int v8::internal::TextNode::Length ()
Definition at line 2496 of file regexp-compiler.cc.
                     {
  TextElement elm = elements()->last();
  DCHECK_LE(0, elm.cp_offset());
  return elm.cp_offset() + elm.length();
}
References v8::internal::TextElement::cp_offset(), DCHECK_LE, elements(), and v8::internal::TextElement::length().
Referenced by Emit(), FixedLengthLoopLength(), TextEmitPass(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitText().
MakeCaseIndependent()
void v8::internal::TextNode::MakeCaseIndependent (Isolate * isolate, bool is_one_byte, RegExpFlags flags)
Definition at line 2621 of file regexp-compiler.cc.
                                                      {
  if (!IsIgnoreCase(flags)) return;
#ifdef V8_INTL_SUPPORT
  // This is done in an earlier step when generating the nodes from the AST
  // because we may have to split up into separate nodes.
  if (NeedsUnicodeCaseEquivalents(flags)) return;
#endif
  int element_count = elements()->length();
  for (int i = 0; i < element_count; i++) {
    TextElement elm = elements()->at(i);
    if (elm.text_type() == TextElement::CLASS_RANGES) {
      RegExpClassRanges* cr = elm.class_ranges();
      // None of the standard character classes is different in the case
      // independent case and it slows us down if we don't know that.
      if (cr->is_standard(zone())) continue;
      ZoneList<CharacterRange>* ranges = cr->ranges(zone());
      CharacterRange::AddCaseEquivalents(isolate, zone(), ranges, is_one_byte);
    }
  }
}
References v8::internal::CharacterRange::AddCaseEquivalents(), v8::internal::TextElement::CLASS_RANGES, v8::internal::TextElement::class_ranges(), elements(), v8::internal::flags, v8::internal::RegExpClassRanges::is_standard(), v8::internal::NeedsUnicodeCaseEquivalents(), v8::internal::RegExpClassRanges::ranges(), v8::internal::TextElement::text_type(), and v8::internal::RegExpNode::zone().
Referenced by v8::internal::Analysis< Propagators >::VisitText().
read_backward()
bool v8::internal::TextNode::read_backward () [inline]
Definition at line 484 of file regexp-nodes.h.
{ return read_backward_; }
References read_backward_.
Referenced by CreateForCharacterRanges(), CreateForSurrogatePair(), Emit(), FillInBMInfo(), GetQuickCheckDetails(), GetSuccessorOfOmnivorousTextNode(), TextEmitPass(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitText().
TextEmitPass()
void v8::internal::TextNode::TextEmitPass (RegExpCompiler * compiler, TextEmitPassType pass, bool preloaded, Trace * trace, bool first_element_checked, int * checked_up_to) [private]
Definition at line 2415 of file regexp-compiler.cc.
                                                                            {
  RegExpMacroAssembler* assembler = compiler->macro_assembler();
  Isolate* isolate = assembler->isolate();
  bool one_byte = compiler->one_byte();
  Label* backtrack = trace->backtrack();
  const QuickCheckDetails* quick_check = trace->quick_check_performed();
  int element_count = elements()->length();
  int backward_offset = read_backward() ? -Length() : 0;
  for (int i = preloaded ? 0 : element_count - 1; i >= 0; i--) {
    TextElement elm = elements()->at(i);
    int cp_offset = trace->cp_offset() + elm.cp_offset() + backward_offset;
    if (elm.text_type() == TextElement::ATOM) {
      base::Vector<const base::uc16> quarks = elm.atom()->data();
      for (int j = preloaded ? 0 : quarks.length() - 1; j >= 0; j--) {
        if (first_element_checked && i == 0 && j == 0) continue;
        if (DeterminedAlready(quick_check, elm.cp_offset() + j)) continue;
        base::uc16 quark = quarks[j];
        bool needs_bounds_check =
            *checked_up_to < cp_offset + j || read_backward();
        bool bounds_checked = false;
        switch (pass) {
          case NON_LATIN1_MATCH: {
            DCHECK(one_byte); // This pass is only done in one-byte mode.
            if (IsIgnoreCase(compiler->flags())) {
              // We are compiling for a one-byte subject, case independent mode.
              // We have to check whether any of the case alternatives are in
              // the one-byte range.
              unibrow::uchar chars[4];
              // Only returns characters that are in the one-byte range.
              int length =
                  GetCaseIndependentLetters(isolate, quark, compiler, chars, 4);
              if (length == 0) {
                assembler->GoTo(backtrack);
                return;
              }
            } else {
              // Case-dependent mode.
              if (quark > String::kMaxOneByteCharCode) {
                assembler->GoTo(backtrack);
                return;
              }
            }
            break;
          }
          case NON_LETTER_CHARACTER_MATCH:
            bounds_checked =
                EmitAtomNonLetter(isolate, compiler, quark, backtrack,
                                  cp_offset + j, needs_bounds_check, preloaded);
            break;
          case SIMPLE_CHARACTER_MATCH:
            bounds_checked = EmitSimpleCharacter(isolate, compiler, quark,
                                                 backtrack, cp_offset + j,
                                                 needs_bounds_check, preloaded);
            break;
          case CASE_CHARACTER_MATCH:
            bounds_checked =
                EmitAtomLetter(isolate, compiler, quark, backtrack,
                               cp_offset + j, needs_bounds_check, preloaded);
            break;
          default:
            break;
        }
        if (bounds_checked) UpdateBoundsCheck(cp_offset + j, checked_up_to);
      }
    } else {
      DCHECK_EQ(TextElement::CLASS_RANGES, elm.text_type());
      if (pass == CHARACTER_CLASS_MATCH) {
        if (first_element_checked && i == 0) continue;
        if (DeterminedAlready(quick_check, elm.cp_offset())) continue;
        RegExpClassRanges* cr = elm.class_ranges();
        bool bounds_check = *checked_up_to < cp_offset || read_backward();
        EmitClassRanges(assembler, cr, one_byte, backtrack, cp_offset,
                        bounds_check, preloaded, zone());
        UpdateBoundsCheck(cp_offset, checked_up_to);
      }
    }
  }
}
References v8::internal::TextElement::ATOM, v8::internal::TextElement::atom(), v8::internal::Trace::backtrack(), CASE_CHARACTER_MATCH, CHARACTER_CLASS_MATCH, v8::internal::TextElement::CLASS_RANGES, v8::internal::TextElement::class_ranges(), v8::internal::TextElement::cp_offset(), v8::internal::Trace::cp_offset(), v8::internal::RegExpAtom::data(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{regexp-compiler.cc}::DeterminedAlready(), elements(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomLetter(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitAtomNonLetter(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitSimpleCharacter(), v8::internal::RegExpCompiler::flags(), v8::internal::anonymous_namespace{regexp-compiler.cc}::GetCaseIndependentLetters(), v8::internal::RegExpMacroAssembler::GoTo(), v8::internal::RegExpMacroAssembler::isolate(), v8::internal::String::kMaxOneByteCharCode, v8::internal::length, Length(), v8::base::Vector< T >::length(), v8::internal::RegExpCompiler::macro_assembler(), NON_LATIN1_MATCH, NON_LETTER_CHARACTER_MATCH, v8::internal::RegExpCompiler::one_byte(), v8::internal::Trace::quick_check_performed(), read_backward(), SIMPLE_CHARACTER_MATCH, v8::internal::TextElement::text_type(), v8::internal::anonymous_namespace{regexp-compiler.cc}::UpdateBoundsCheck(), and v8::internal::RegExpNode::zone().
Referenced by Emit().
Member Data Documentation
elms_
ZoneList<TextElement>* v8::internal::TextNode::elms_ [private]
Definition at line 507 of file regexp-nodes.h.
Referenced by elements(), and TextNode().
read_backward_
bool v8::internal::TextNode::read_backward_ [private]
Definition at line 508 of file regexp-nodes.h.
Referenced by read_backward().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-nodes.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc