v8::internal::CodeEventLogger::NameBuffer Class Reference
Public Member Functions
NameBuffer ()
void Reset ()
void Init (CodeTag tag)
void AppendName (Tagged< Name > name)
void AppendString (Tagged< String > str)
void AppendBytes (const char *bytes, size_t size)
void AppendBytes (const char *bytes)
void AppendByte (char c)
void AppendInt (int n)
void AppendHex (uint32_t n)
const char * get ()
size_t size () const
Private Attributes
size_t utf8_pos_
char utf8_buffer_ [kUtf8BufferSize]
Static Private Attributes
static const size_t kUtf8BufferSize = 4096
static const size_t kUtf16BufferSize = kUtf8BufferSize
Detailed Description
Definition at line 161 of file log.cc.
Constructor & Destructor Documentation
NameBuffer()
v8::internal::CodeEventLogger::NameBuffer::NameBuffer () [inline]
Definition at line 163 of file log.cc.
{ Reset(); }
References Reset().
Member Function Documentation
AppendByte()
void v8::internal::CodeEventLogger::NameBuffer::AppendByte (char c) [inline]
Definition at line 209 of file log.cc.
                          {
    if (utf8_pos_ >= kUtf8BufferSize) return;
    utf8_buffer_[utf8_pos_++] = c;
  }
References kUtf8BufferSize, utf8_buffer_, and utf8_pos_.
Referenced by AppendName(), and Init().
AppendBytes() [1/2]
void v8::internal::CodeEventLogger::NameBuffer::AppendBytes (const char * bytes) [inline]
Definition at line 203 of file log.cc.
                                      {
    size_t len = strlen(bytes);
    DCHECK_GE(kMaxInt, len);
    AppendBytes(bytes, static_cast<int>(len));
  }
References AppendBytes(), DCHECK_GE, and v8::internal::kMaxInt.
AppendBytes() [2/2]
void v8::internal::CodeEventLogger::NameBuffer::AppendBytes (const char * bytes, size_t size) [inline]
Definition at line 197 of file log.cc.
                                                   {
    size = std::min(size, kUtf8BufferSize - utf8_pos_);
    MemCopy(utf8_buffer_ + utf8_pos_, bytes, size);
    utf8_pos_ += size;
  }
References kUtf8BufferSize, v8::internal::MemCopy(), size(), utf8_buffer_, and utf8_pos_.
Referenced by AppendBytes(), AppendName(), AppendString(), and Init().
AppendHex()
void v8::internal::CodeEventLogger::NameBuffer::AppendHex (uint32_t n) [inline]
Definition at line 224 of file log.cc.
                             {
    if (utf8_pos_ >= kUtf8BufferSize) return;
    size_t space = kUtf8BufferSize - utf8_pos_;
    base::Vector<char> buffer(utf8_buffer_ + utf8_pos_, space);
    int size = SNPrintF(buffer, "%x", n);
    if (size > 0 && utf8_pos_ + size <= kUtf8BufferSize) {
      utf8_pos_ += size;
    }
  }
References kUtf8BufferSize, size(), v8::base::SNPrintF(), space, utf8_buffer_, and utf8_pos_.
Referenced by AppendName().
AppendInt()
void v8::internal::CodeEventLogger::NameBuffer::AppendInt (int n) [inline]
Definition at line 214 of file log.cc.
                        {
    if (utf8_pos_ >= kUtf8BufferSize) return;
    size_t space = kUtf8BufferSize - utf8_pos_;
    base::Vector<char> buffer(utf8_buffer_ + utf8_pos_, space);
    int size = SNPrintF(buffer, "%d", n);
    if (size > 0 && utf8_pos_ + size <= kUtf8BufferSize) {
      utf8_pos_ += size;
    }
  }
References kUtf8BufferSize, size(), v8::base::SNPrintF(), space, utf8_buffer_, and utf8_pos_.
AppendName()
void v8::internal::CodeEventLogger::NameBuffer::AppendName (Tagged< Name > name) [inline]
Definition at line 173 of file log.cc.
                                     {
    if (IsString(name)) {
      AppendString(Cast<String>(name));
    } else {
      Tagged<Symbol> symbol = Cast<Symbol>(name);
      AppendBytes("symbol(");
      if (!IsUndefined(symbol->description())) {
        AppendBytes("\"");
        AppendString(Cast<String>(symbol->description()));
        AppendBytes("\" ");
      }
      AppendBytes("hash ");
      AppendHex(symbol->hash());
      AppendByte(')');
    }
  }
References AppendByte(), AppendBytes(), AppendHex(), AppendString(), and v8::internal::name.
AppendString()
void v8::internal::CodeEventLogger::NameBuffer::AppendString (Tagged< String > str) [inline]
Definition at line 190 of file log.cc.
                                        {
    if (str.is_null()) return;
    size_t length = 0;
    std::unique_ptr<char[]> c_str = str->ToCString(&length);
    AppendBytes(c_str.get(), length);
  }
References AppendBytes(), v8::internal::Tagged< HeapObject >::is_null(), and v8::internal::length.
Referenced by AppendName().
get()
const char* v8::internal::CodeEventLogger::NameBuffer::get () [inline]
Definition at line 234 of file log.cc.
{ return utf8_buffer_; }
References utf8_buffer_.
Init()
void v8::internal::CodeEventLogger::NameBuffer::Init (CodeTag tag) [inline]
Definition at line 167 of file log.cc.
                         {
    Reset();
    AppendBytes(kCodeTagNames[static_cast<int>(tag)]);
    AppendByte(':');
  }
References AppendByte(), AppendBytes(), v8::internal::kCodeTagNames, and Reset().
Reset()
void v8::internal::CodeEventLogger::NameBuffer::Reset () [inline]
Definition at line 165 of file log.cc.
{ utf8_pos_ = 0; }
References utf8_pos_.
Referenced by Init(), and NameBuffer().
size()
size_t v8::internal::CodeEventLogger::NameBuffer::size () const [inline]
Definition at line 235 of file log.cc.
{ return utf8_pos_; }
References utf8_pos_.
Referenced by AppendBytes(), AppendHex(), and AppendInt().
Member Data Documentation
kUtf16BufferSize
const size_t v8::internal::CodeEventLogger::NameBuffer::kUtf16BufferSize = kUtf8BufferSize [static], [private]
Definition at line 239 of file log.cc.
kUtf8BufferSize
const size_t v8::internal::CodeEventLogger::NameBuffer::kUtf8BufferSize = 4096 [static], [private]
Definition at line 238 of file log.cc.
Referenced by AppendByte(), AppendBytes(), AppendHex(), and AppendInt().
utf8_buffer_
char v8::internal::CodeEventLogger::NameBuffer::utf8_buffer_[kUtf8BufferSize] [private]
Definition at line 242 of file log.cc.
Referenced by AppendByte(), AppendBytes(), AppendHex(), AppendInt(), and get().
utf8_pos_
size_t v8::internal::CodeEventLogger::NameBuffer::utf8_pos_ [private]
Definition at line 241 of file log.cc.
Referenced by AppendByte(), AppendBytes(), AppendHex(), AppendInt(), Reset(), and size().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/logging/log.cc