v8::internal::IsolateGroup Class Reference
#include <isolate-group.h>
Public Member Functions
IsolateGroup * Acquire ()
void Release ()
v8::PageAllocator * page_allocator () const
CodeRange * EnsureCodeRange (size_t requested_size)
CodeRange * GetCodeRange () const
MemorySpan< Address > external_ref_table ()
bool has_shared_space_isolate () const
Isolate * shared_space_isolate () const
void init_shared_space_isolate (Isolate *isolate)
OptimizingCompileTaskExecutor * optimizing_compile_task_executor ()
ReadOnlyHeap * shared_read_only_heap () const
void set_shared_read_only_heap (ReadOnlyHeap *heap)
base::Mutex * mutex ()
ReadOnlyArtifacts * read_only_artifacts ()
ReadOnlyArtifacts * InitializeReadOnlyArtifacts ()
PageAllocator * GetBackingStorePageAllocator ()
void SetupReadOnlyHeap (Isolate *isolate, SnapshotData *read_only_snapshot_data, bool can_rehash)
void AddIsolate (Isolate *isolate)
void RemoveIsolate (Isolate *isolate)
PagePool * page_pool () const
template<typename Callback >
bool FindAnotherIsolateLocked (Isolate *isolate, Callback callback)
Static Public Member Functions
static IsolateGroup * AcquireDefault ()
static constexpr bool CanCreateNewGroups ()
static IsolateGroup * New ()
static void InitializeOncePerProcess ()
static void TearDownOncePerProcess ()
static IsolateGroup * current ()
static IsolateGroup * GetDefault ()
Private Member Functions
IsolateGroup ()=default
~IsolateGroup ()
IsolateGroup (const IsolateGroup &)=delete
IsolateGroup & operator= (const IsolateGroup &)=delete
void Initialize (bool process_wide)
Static Private Member Functions
static void ReleaseDefault ()
Private Attributes
std::atomic< int > reference_count_ {1}
v8::PageAllocator * page_allocator_ = nullptr
std::unique_ptr< PagePool > page_pool_
base::OnceType init_code_range_ = V8_ONCE_INIT
std::unique_ptr< CodeRange > code_range_
Address external_ref_table_ [ExternalReferenceTable::kSizeIsolateIndependent]
bool process_wide_
base::Mutex mutex_
std::unique_ptr< ReadOnlyArtifacts > read_only_artifacts_
ReadOnlyHeap * shared_read_only_heap_ = nullptr
Isolate * shared_space_isolate_ = nullptr
std::unique_ptr< OptimizingCompileTaskExecutor > optimizing_compile_task_executor_
absl::flat_hash_set< Isolate * > isolates_
Isolate * main_isolate_ = nullptr
Static Private Attributes
static IsolateGroup * default_isolate_group_ = nullptr
Friends
class base::LeakyObject< IsolateGroup >
class PoolTest
class PagePool
Detailed Description
Definition at line 118 of file isolate-group.h.
Constructor & Destructor Documentation
IsolateGroup() [1/2]
v8::internal::IsolateGroup::IsolateGroup () [private], [default]
Referenced by InitializeOncePerProcess(), and New().
 IsolateGroup()
v8::internal::IsolateGroup::~IsolateGroup () [private]
Definition at line 101 of file isolate-group.cc.
                            {
  DCHECK_EQ(reference_count_.load(), 0);
  DCHECK(isolates_.empty());
  DCHECK_NULL(main_isolate_);
  page_pool_->TearDown();
#ifdef V8_ENABLE_LEAPTIERING
  js_dispatch_table_.TearDown();
#endif // V8_ENABLE_LEAPTIERING
#ifdef V8_ENABLE_SANDBOX
  code_pointer_table_.TearDown();
#endif // V8_ENABLE_SANDBOX
  // Reset before `reservation_` for pointer compression but disabled external
  // code space.
  code_range_.reset();
#ifdef V8_COMPRESS_POINTERS
  DCHECK(reservation_.IsReserved());
  reservation_.Free();
#endif // V8_COMPRESS_POINTERS
#ifdef V8_ENABLE_SANDBOX
  sandbox_->TearDown();
#endif // V8_ENABLE_SANDBOX
}
References code_range_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, isolates_, main_isolate_, page_pool_, and reference_count_.
IsolateGroup() [2/2]
v8::internal::IsolateGroup::IsolateGroup (const IsolateGroup &) [private], [delete]
Member Function Documentation
Acquire()
IsolateGroup* v8::internal::IsolateGroup::Acquire () [inline]
Definition at line 142 of file isolate-group.h.
                          {
    DCHECK_LT(0, reference_count_.load());
    reference_count_++;
    return this;
  }
References DCHECK_LT.
Referenced by AcquireDefault(), v8::Isolate::Allocate(), v8::Isolate::GetGroup(), v8::IsolateGroup::IsolateGroup(), and v8::IsolateGroup::operator=().
AcquireDefault()
static IsolateGroup* v8::internal::IsolateGroup::AcquireDefault () [inline], [static]
Definition at line 122 of file isolate-group.h.
{ return GetDefault()->Acquire(); }
References Acquire().
Referenced by v8::IsolateGroup::GetDefault(), and v8::internal::Isolate::New().
AddIsolate()
void v8::internal::IsolateGroup::AddIsolate (Isolate * isolate)
Definition at line 285 of file isolate-group.cc.
                                              {
  DCHECK_EQ(isolate->isolate_group(), this);
  base::MutexGuard guard(&mutex_);
  const bool inserted = isolates_.insert(isolate).second;
  CHECK(inserted);
  if (!main_isolate_) {
    main_isolate_ = isolate;
  }
  optimizing_compile_task_executor_->EnsureStarted();
  if (v8_flags.shared_heap) {
    if (has_shared_space_isolate()) {
      isolate->owns_shareable_data_ = false;
    } else {
      init_shared_space_isolate(isolate);
      isolate->is_shared_space_isolate_ = true;
      DCHECK(isolate->owns_shareable_data_);
    }
  }
}
References CHECK, v8::internal::DCHECK(), DCHECK_EQ, has_shared_space_isolate(), init_shared_space_isolate(), v8::internal::Isolate::is_shared_space_isolate_, v8::internal::Isolate::isolate_group(), isolates_, main_isolate_, mutex_, optimizing_compile_task_executor_, v8::internal::Isolate::owns_shareable_data_, and v8::internal::v8_flags.
Referenced by v8::internal::Isolate::Init().
CanCreateNewGroups()
static constexpr bool v8::internal::IsolateGroup::CanCreateNewGroups () [inline], [static], [constexpr]
Definition at line 126 of file isolate-group.h.
                                             {
    return COMPRESS_POINTERS_IN_MULTIPLE_CAGES_BOOL;
  }
References COMPRESS_POINTERS_IN_MULTIPLE_CAGES_BOOL.
Referenced by v8::IsolateGroup::CanCreateNewGroups(), and New().
current()
static IsolateGroup* v8::internal::IsolateGroup::current () [inline], [static]
Definition at line 181 of file isolate-group.h.
{ return GetDefault(); }
Referenced by v8::internal::Factory::JSFunctionBuilder::BuildRaw(), v8::internal::ConcurrentUnifiedHeapMarkingVisitor::ConcurrentUnifiedHeapMarkingVisitor(), v8::internal::Isolate::Deinit(), v8::internal::ReadOnlyHeap::EarlyGetReadOnlyRoots(), v8::internal::anonymous_namespace{heap.cc}::FreeCachesOnMemoryPressure(), v8::internal::EmbeddedData::FromBlobForPc(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateCCall(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateCCallWithStackBuffer(), v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::GetOrCreateMemoryForSegment(), v8::internal::JSFunction::GetRequestedOptimizationIfAny(), v8::internal::Isolate::Init(), v8::internal::V8::Initialize(), v8::internal::Isolate::InitializeBuiltinJSDispatchTable(), v8::internal::InitSelfIndirectPointerField(), v8::internal::CodeDataSourceIncrementalState::InternIsolate(), v8::internal::JSFunction::IsLoggingRequested(), v8::internal::JSFunction::IsMaglevRequested(), v8::internal::JSFunction::IsTieringRequestedOrInProgress(), v8::internal::JSFunction::IsTurbofanRequested(), v8::internal::anonymous_namespace{runtime-compiler.cc}::LogExecution(), v8::internal::WriteBarrier::MarkingSlow(), v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::MarkPointerTableEntry(), v8::internal::MemoryChunk::Metadata(), v8::internal::ReadOnlyHeap::PopulateReadOnlySpaceStatistics(), v8::internal::JSFunction::raw_code(), v8::internal::ReadCodeEntrypointViaCodePointerField(), v8::internal::ReadOnlyHeap::ReadOnlyHeap(), v8::internal::JSFunction::RequestOptimization(), v8::internal::JSFunction::ResetTieringRequests(), v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::ReturnSegment(), v8::internal::Code::SetMarkedForDeoptimization(), v8::internal::BackingStore::TryAllocateAndPartiallyCommitMemory(), v8::internal::OffHeapInstructionStream::TryLookupCode(), v8::internal::JSFunction::UpdateCodeImpl(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointers(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitJSDispatchTableEntry(), v8::internal::Serializer::ObjectSerializer::VisitJSDispatchTableEntry(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitJSFunction(), v8::internal::WriteCodeEntrypointViaCodePointerField(), and v8::internal::ReadOnlyHeap::~ReadOnlyHeap().
EnsureCodeRange()
CodeRange * v8::internal::IsolateGroup::EnsureCodeRange (size_t requested_size)
Definition at line 256 of file isolate-group.cc.
                                                              {
  base::CallOnce(&init_code_range_, InitCodeRangeOnce, &code_range_,
                 page_allocator_, requested_size, process_wide_);
  return code_range_.get();
}
References v8::base::CallOnce(), code_range_, init_code_range_, v8::internal::anonymous_namespace{isolate-group.cc}::InitCodeRangeOnce(), page_allocator_, and process_wide_.
Referenced by v8::internal::Heap::SetUp().
external_ref_table()
MemorySpan<Address> v8::internal::IsolateGroup::external_ref_table () [inline]
Definition at line 184 of file isolate-group.h.
{ return external_ref_table_; }
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateCCall(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateCCallWithStackBuffer(), and New().
FindAnotherIsolateLocked()
template<typename Callback >
bool v8::internal::IsolateGroup::FindAnotherIsolateLocked (Isolate * isolate, Callback callback) [inline]
Definition at line 248 of file isolate-group.h.
                                                                     {
    // Holding this mutex while invoking the callback avoids the isolate tearing
    // down in the mean time.
    base::MutexGuard group_guard(mutex_);
    Isolate* target_isolate = nullptr;
    DCHECK_NOT_NULL(main_isolate_);
    if (main_isolate_ != isolate) {
      target_isolate = main_isolate_;
    } else {
      for (Isolate* entry : isolates_) {
        if (entry != isolate) {
          target_isolate = entry;
          break;
        }
      }
    }
    if (target_isolate) {
      callback(target_isolate);
      return true;
    }
    return false;
  }
References DCHECK_NOT_NULL.
Referenced by v8::internal::PagePool::ReleaseOnTearDown().
GetBackingStorePageAllocator()
PageAllocator * v8::internal::IsolateGroup::GetBackingStorePageAllocator ()
Definition at line 269 of file isolate-group.cc.
                                                          {
#ifdef V8_ENABLE_SANDBOX
  return sandbox()->page_allocator();
#else
  return GetPlatformPageAllocator();
#endif
}
References v8::internal::GetPlatformPageAllocator().
Referenced by v8::internal::BackingStore::Allocate().
GetCodeRange()
CodeRange* v8::internal::IsolateGroup::GetCodeRange () const [inline]
Definition at line 168 of file isolate-group.h.
{ return code_range_.get(); }
Referenced by v8::internal::ETWJITInterface::EventHandler(), v8::internal::EmbeddedData::FromBlobForPc(), v8::internal::Isolate::InitializeIsShortBuiltinCallsEnabled(), and v8::internal::OffHeapInstructionStream::TryLookupCode().
GetDefault()
static IsolateGroup* v8::internal::IsolateGroup::GetDefault () [inline], [static]
Definition at line 274 of file isolate-group.h.
{ return default_isolate_group_; }
Referenced by InitializeOncePerProcess(), v8::ArrayBuffer::Allocator::NewDefaultAllocator(), and ReleaseDefault().
has_shared_space_isolate()
bool v8::internal::IsolateGroup::has_shared_space_isolate () const [inline]
Definition at line 186 of file isolate-group.h.
                                        {
    return shared_space_isolate_ != nullptr;
  }
Referenced by AddIsolate(), ReleaseDefault(), and RemoveIsolate().
init_shared_space_isolate()
void v8::internal::IsolateGroup::init_shared_space_isolate (Isolate * isolate) [inline]
Definition at line 194 of file isolate-group.h.
                                                   {
    DCHECK(!has_shared_space_isolate());
    shared_space_isolate_ = isolate;
  }
References v8::internal::DCHECK().
Referenced by AddIsolate().
Initialize()
void v8::internal::IsolateGroup::Initialize (bool process_wide) [private]
Definition at line 185 of file isolate-group.cc.
                                               {
  process_wide_ = process_wide;
  page_allocator_ = GetPlatformPageAllocator();
  optimizing_compile_task_executor_ =
      std::make_unique<OptimizingCompileTaskExecutor>();
  page_pool_ = std::make_unique<PagePool>();
#ifdef V8_ENABLE_LEAPTIERING
  js_dispatch_table()->Initialize();
#endif // V8_ENABLE_LEAPTIERING
}
References v8::internal::GetPlatformPageAllocator(), optimizing_compile_task_executor_, page_allocator_, page_pool_, and process_wide_.
Referenced by InitializeOncePerProcess(), and New().
InitializeOncePerProcess()
void v8::internal::IsolateGroup::InitializeOncePerProcess () [static]
Definition at line 198 of file isolate-group.cc.
                                            {
  CHECK_NULL(default_isolate_group_);
  default_isolate_group_ = new IsolateGroup;
  IsolateGroup* group = GetDefault();
  DCHECK_NULL(group->page_allocator_);
#ifdef V8_ENABLE_SANDBOX
  group->Initialize(true, Sandbox::GetDefault());
#else
  group->Initialize(true);
#endif
  CHECK_NOT_NULL(group->page_allocator_);
#ifdef V8_COMPRESS_POINTERS
  V8HeapCompressionScheme::InitBase(group->GetPtrComprCageBase());
#endif // V8_COMPRESS_POINTERS
#ifdef V8_EXTERNAL_CODE_SPACE
  // Speculatively set the code cage base to the same value in case jitless
  // mode will be used. Once the process-wide CodeRange instance is created
  // the code cage base will be set accordingly.
  ExternalCodeCompressionScheme::InitBase(V8HeapCompressionScheme::base());
#endif // V8_EXTERNAL_CODE_SPACE
#ifdef V8_COMPRESS_POINTERS_IN_MULTIPLE_CAGES
  IsolateGroup::set_current(group);
#endif
}
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::base(), CHECK_NOT_NULL, CHECK_NULL, DCHECK_NULL, default_isolate_group_, GetDefault(), v8::internal::V8HeapCompressionSchemeImpl< Cage >::InitBase(), Initialize(), IsolateGroup(), and page_allocator_.
Referenced by v8::internal::V8::Initialize().
InitializeReadOnlyArtifacts()
ReadOnlyArtifacts * v8::internal::IsolateGroup::InitializeReadOnlyArtifacts ()
Definition at line 262 of file isolate-group.cc.
                                                             {
  mutex_.AssertHeld();
  DCHECK(!read_only_artifacts_);
  read_only_artifacts_ = std::make_unique<ReadOnlyArtifacts>();
  return read_only_artifacts_.get();
}
References v8::base::Mutex::AssertHeld(), v8::internal::DCHECK(), mutex_, and read_only_artifacts_.
Referenced by v8::internal::ReadOnlyHeap::SetUp().
mutex()
base::Mutex* v8::internal::IsolateGroup::mutex () [inline]
Definition at line 206 of file isolate-group.h.
{ return &mutex_; }
Referenced by v8::internal::ReadOnlyHeap::SetUp().
New()
IsolateGroup * v8::internal::IsolateGroup::New () [static]
Definition at line 342 of file isolate-group.cc.
                                {
  if (!CanCreateNewGroups()) {
    FATAL(
        "Creation of new isolate groups requires enabling "
        "multiple pointer compression cages at build-time");
  }
  IsolateGroup* group = new IsolateGroup;
#ifdef V8_ENABLE_SANDBOX
  Sandbox* sandbox = Sandbox::New(GetPlatformVirtualAddressSpace());
  group->Initialize(false, sandbox);
#else
  group->Initialize(false);
#endif
  CHECK_NOT_NULL(group->page_allocator_);
  // We need to set this early, because it is needed while initializing the
  // external reference table, eg. in the js_dispatch_table_address and
  // code_pointer_table_address functions. This is also done in
  // IsolateGroup::InitializeOncePerProcess for the single-IsolateGroup
  // configurations.
  IsolateGroupAccessScope group_access_scope(group);
  ExternalReferenceTable::InitializeOncePerIsolateGroup(
      group->external_ref_table());
  return group;
}
References CanCreateNewGroups(), CHECK_NOT_NULL, external_ref_table(), FATAL, v8::internal::GetPlatformVirtualAddressSpace(), Initialize(), v8::internal::ExternalReferenceTable::InitializeOncePerIsolateGroup(), IsolateGroup(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), and page_allocator_.
Referenced by v8::IsolateGroup::Create().
operator=()
IsolateGroup& v8::internal::IsolateGroup::operator= (const IsolateGroup &) [private], [delete]
optimizing_compile_task_executor()
OptimizingCompileTaskExecutor * v8::internal::IsolateGroup::optimizing_compile_task_executor ()
Definition at line 499 of file isolate-group.cc.
                                               {
  return optimizing_compile_task_executor_.get();
}
Referenced by v8::internal::Isolate::Init().
page_allocator()
v8::PageAllocator* v8::internal::IsolateGroup::page_allocator () const [inline]
Definition at line 152 of file isolate-group.h.
{ return page_allocator_; }
Referenced by v8::internal::ReadOnlyArtifacts::Initialize(), and v8::internal::Isolate::page_allocator().
page_pool()
PagePool* v8::internal::IsolateGroup::page_pool () const [inline]
Definition at line 242 of file isolate-group.h.
                              {
    DCHECK(page_pool_);
    return page_pool_.get();
  }
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{heap.cc}::FreeCachesOnMemoryPressure(), v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::GetOrCreateMemoryForSegment(), v8::internal::MemoryAllocator::MemoryAllocator(), and v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::ReturnSegment().
read_only_artifacts()
ReadOnlyArtifacts* v8::internal::IsolateGroup::read_only_artifacts () [inline]
Definition at line 208 of file isolate-group.h.
                                           {
    return read_only_artifacts_.get();
  }
Referenced by v8::internal::ReadOnlyHeap::InitFromIsolate(), v8::internal::ReadOnlyHeap::PopulateReadOnlySpaceStatistics(), and v8::internal::ReadOnlyHeap::SetUp().
Release()
void v8::internal::IsolateGroup::Release ()
Definition at line 228 of file isolate-group.cc.
                           {
  DCHECK_LT(0, reference_count_.load());
  if (--reference_count_ == 0) {
    delete this;
  }
}
References DCHECK_LT, and reference_count_.
Referenced by v8::internal::Isolate::Deinitialize(), v8::IsolateGroup::operator=(), ReleaseDefault(), and v8::IsolateGroup::~IsolateGroup().
ReleaseDefault()
void v8::internal::IsolateGroup::ReleaseDefault () [static], [private]
Definition at line 370 of file isolate-group.cc.
                                  {
  IsolateGroup* group = GetDefault();
  CHECK_EQ(group->reference_count_.load(), 1);
  CHECK(!group->has_shared_space_isolate());
  group->Release();
  default_isolate_group_ = nullptr;
}
References CHECK, CHECK_EQ, default_isolate_group_, GetDefault(), has_shared_space_isolate(), reference_count_, and Release().
Referenced by TearDownOncePerProcess().
RemoveIsolate()
void v8::internal::IsolateGroup::RemoveIsolate (Isolate * isolate)
Definition at line 309 of file isolate-group.cc.
                                                 {
  base::MutexGuard guard(&mutex_);
  if (isolates_.size() == 1) {
    read_only_artifacts_.reset();
    optimizing_compile_task_executor_->Stop();
    // We are removing the last isolate from the group. If this group has a
    // shared heap, the last isolate has to be the shared space isolate.
    DCHECK_EQ(has_shared_space_isolate(), isolate->is_shared_space_isolate());
    if (isolate->is_shared_space_isolate()) {
      CHECK_EQ(isolate, shared_space_isolate_);
      shared_space_isolate_ = nullptr;
    }
  } else {
    // The shared space isolate needs to be removed last.
    DCHECK(!isolate->is_shared_space_isolate());
  }
  CHECK_EQ(isolates_.erase(isolate), 1);
  if (main_isolate_ == isolate) {
    if (isolates_.empty()) {
      main_isolate_ = nullptr;
    } else {
      main_isolate_ = *isolates_.begin();
    }
  }
}
References CHECK_EQ, v8::internal::DCHECK(), DCHECK_EQ, has_shared_space_isolate(), v8::internal::Isolate::is_shared_space_isolate(), isolates_, main_isolate_, mutex_, optimizing_compile_task_executor_, read_only_artifacts_, and shared_space_isolate_.
Referenced by v8::internal::Isolate::Deinit().
set_shared_read_only_heap()
void v8::internal::IsolateGroup::set_shared_read_only_heap (ReadOnlyHeap * heap) [inline]
Definition at line 202 of file isolate-group.h.
                                                     {
    shared_read_only_heap_ = heap;
  }
References heap().
Referenced by v8::internal::ReadOnlyHeap::CreateInitialHeapForBootstrapping().
SetupReadOnlyHeap()
void v8::internal::IsolateGroup::SetupReadOnlyHeap (Isolate * isolate, SnapshotData * read_only_snapshot_data, bool can_rehash)
Definition at line 277 of file isolate-group.cc.
                                                      {
  DCHECK_EQ(isolate->isolate_group(), this);
  base::MutexGuard guard(&mutex_);
  ReadOnlyHeap::SetUp(isolate, read_only_snapshot_data, can_rehash);
}
References DCHECK_EQ, v8::internal::Isolate::isolate_group(), mutex_, and v8::internal::ReadOnlyHeap::SetUp().
Referenced by v8::internal::Isolate::Init().
shared_read_only_heap()
ReadOnlyHeap* v8::internal::IsolateGroup::shared_read_only_heap () const [inline]
Definition at line 201 of file isolate-group.h.
{ return shared_read_only_heap_; }
Referenced by v8::internal::ReadOnlyHeap::EarlyGetReadOnlyRoots().
shared_space_isolate()
Isolate* v8::internal::IsolateGroup::shared_space_isolate () const [inline]
Definition at line 190 of file isolate-group.h.
                                        {
    return shared_space_isolate_;
  }
Referenced by v8::internal::Isolate::Init().
TearDownOncePerProcess()
void v8::internal::IsolateGroup::TearDownOncePerProcess () [static]
Definition at line 226 of file isolate-group.cc.
{ ReleaseDefault(); }
References ReleaseDefault().
Referenced by v8::internal::V8::Dispose().
Friends And Related Function Documentation
base::LeakyObject< IsolateGroup >
friend class base::LeakyObject< IsolateGroup > [friend]
Definition at line 274 of file isolate-group.h.
PagePool
friend class PagePool [friend]
Definition at line 279 of file isolate-group.h.
PoolTest
friend class PoolTest [friend]
Definition at line 278 of file isolate-group.h.
Member Data Documentation
code_range_
std::unique_ptr<CodeRange> v8::internal::IsolateGroup::code_range_ [private]
Definition at line 321 of file isolate-group.h.
Referenced by EnsureCodeRange(), and ~IsolateGroup().
default_isolate_group_
IsolateGroup * v8::internal::IsolateGroup::default_isolate_group_ = nullptr [static], [private]
Definition at line 284 of file isolate-group.h.
Referenced by InitializeOncePerProcess(), and ReleaseDefault().
external_ref_table_
Address v8::internal::IsolateGroup::external_ref_table_[ExternalReferenceTable::kSizeIsolateIndependent] [private]
Initial value:
=
      {0}
Definition at line 322 of file isolate-group.h.
init_code_range_
base::OnceType v8::internal::IsolateGroup::init_code_range_ = V8_ONCE_INIT [private]
Definition at line 320 of file isolate-group.h.
Referenced by EnsureCodeRange().
isolates_
absl::flat_hash_set<Isolate*> v8::internal::IsolateGroup::isolates_ [private]
Definition at line 337 of file isolate-group.h.
Referenced by AddIsolate(), RemoveIsolate(), and ~IsolateGroup().
main_isolate_
Isolate* v8::internal::IsolateGroup::main_isolate_ = nullptr [private]
Definition at line 342 of file isolate-group.h.
Referenced by AddIsolate(), RemoveIsolate(), and ~IsolateGroup().
mutex_
base::Mutex v8::internal::IsolateGroup::mutex_ [private]
Definition at line 329 of file isolate-group.h.
Referenced by AddIsolate(), InitializeReadOnlyArtifacts(), RemoveIsolate(), and SetupReadOnlyHeap().
optimizing_compile_task_executor_
std::unique_ptr<OptimizingCompileTaskExecutor> v8::internal::IsolateGroup::optimizing_compile_task_executor_ [private]
Definition at line 334 of file isolate-group.h.
Referenced by AddIsolate(), Initialize(), and RemoveIsolate().
page_allocator_
v8::PageAllocator* v8::internal::IsolateGroup::page_allocator_ = nullptr [private]
Definition at line 306 of file isolate-group.h.
Referenced by EnsureCodeRange(), Initialize(), InitializeOncePerProcess(), and New().
page_pool_
std::unique_ptr<PagePool> v8::internal::IsolateGroup::page_pool_ [private]
Definition at line 318 of file isolate-group.h.
Referenced by Initialize(), and ~IsolateGroup().
process_wide_
bool v8::internal::IsolateGroup::process_wide_ [private]
Definition at line 325 of file isolate-group.h.
Referenced by EnsureCodeRange(), and Initialize().
read_only_artifacts_
std::unique_ptr<ReadOnlyArtifacts> v8::internal::IsolateGroup::read_only_artifacts_ [private]
Definition at line 330 of file isolate-group.h.
Referenced by InitializeReadOnlyArtifacts(), and RemoveIsolate().
reference_count_
std::atomic<int> v8::internal::IsolateGroup::reference_count_ {1} [private]
Definition at line 305 of file isolate-group.h.
Referenced by Release(), ReleaseDefault(), and ~IsolateGroup().
shared_read_only_heap_
ReadOnlyHeap* v8::internal::IsolateGroup::shared_read_only_heap_ = nullptr [private]
Definition at line 331 of file isolate-group.h.
shared_space_isolate_
Isolate* v8::internal::IsolateGroup::shared_space_isolate_ = nullptr [private]
Definition at line 332 of file isolate-group.h.
Referenced by RemoveIsolate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/init/isolate-group.h
/mnt/V8SourceCode/src/init/isolate-group.cc