v8::internal::PreParserLogger Class Reference
#include <preparser-logger.h>
Public Member Functions
PreParserLogger ()
void LogFunction (int end, int num_parameters, int function_length, int num_inner_infos)
int end () const
int num_parameters () const
int function_length () const
int num_inner_infos () const
Private Attributes
int end_
int num_parameters_
int function_length_
int num_inner_infos_
Detailed Description
Definition at line 11 of file preparser-logger.h.
Constructor & Destructor Documentation
PreParserLogger()
v8::internal::PreParserLogger::PreParserLogger () [inline]
Definition at line 13 of file preparser-logger.h.
      : end_(-1),
        num_parameters_(-1),
        function_length_(-1),
        num_inner_infos_(-1) {}
Member Function Documentation
end()
int v8::internal::PreParserLogger::end () const [inline]
Definition at line 27 of file preparser-logger.h.
{ return end_; }
References end_.
Referenced by LogFunction(), and v8::internal::Parser::SkipFunction().
function_length()
int v8::internal::PreParserLogger::function_length () const [inline]
Definition at line 29 of file preparser-logger.h.
{ return function_length_; }
References function_length_.
Referenced by LogFunction(), and v8::internal::Parser::SkipFunction().
LogFunction()
void v8::internal::PreParserLogger::LogFunction (int end, int num_parameters, int function_length, int num_inner_infos) [inline]
Definition at line 19 of file preparser-logger.h.
                                        {
    end_ = end;
    num_parameters_ = num_parameters;
    function_length_ = function_length;
    num_inner_infos_ = num_inner_infos;
  }
References end(), end_, function_length(), function_length_, num_inner_infos(), num_inner_infos_, num_parameters(), and num_parameters_.
Referenced by v8::internal::PreParser::ParseStatementListAndLogFunction().
num_inner_infos()
int v8::internal::PreParserLogger::num_inner_infos () const [inline]
Definition at line 30 of file preparser-logger.h.
{ return num_inner_infos_; }
References num_inner_infos_.
Referenced by LogFunction(), and v8::internal::Parser::SkipFunction().
num_parameters()
int v8::internal::PreParserLogger::num_parameters () const [inline]
Definition at line 28 of file preparser-logger.h.
{ return num_parameters_; }
References num_parameters_.
Referenced by LogFunction(), and v8::internal::Parser::SkipFunction().
Member Data Documentation
end_
int v8::internal::PreParserLogger::end_ [private]
Definition at line 33 of file preparser-logger.h.
Referenced by end(), and LogFunction().
function_length_
int v8::internal::PreParserLogger::function_length_ [private]
Definition at line 36 of file preparser-logger.h.
Referenced by function_length(), and LogFunction().
num_inner_infos_
int v8::internal::PreParserLogger::num_inner_infos_ [private]
Definition at line 37 of file preparser-logger.h.
Referenced by LogFunction(), and num_inner_infos().
num_parameters_
int v8::internal::PreParserLogger::num_parameters_ [private]
Definition at line 35 of file preparser-logger.h.
Referenced by LogFunction(), and num_parameters().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/preparser-logger.h