v8::internal::UnoptimizedCompileState Class Reference
#include <parse-info.h>
Public Member Functions
const PendingCompilationErrorHandler * pending_error_handler () const
PendingCompilationErrorHandler * pending_error_handler ()
Private Attributes
PendingCompilationErrorHandler pending_error_handler_
Detailed Description
Definition at line 163 of file parse-info.h.
Member Function Documentation
pending_error_handler() [1/2]
PendingCompilationErrorHandler* v8::internal::UnoptimizedCompileState::pending_error_handler () [inline]
Definition at line 168 of file parse-info.h.
                                                          {
    return &pending_error_handler_;
  }
pending_error_handler() [2/2]
const PendingCompilationErrorHandler* v8::internal::UnoptimizedCompileState::pending_error_handler () const [inline]
Definition at line 165 of file parse-info.h.
                                                                      {
    return &pending_error_handler_;
  }
Referenced by v8::internal::BackgroundCompileTask::FinalizeFunction(), v8::internal::BackgroundCompileTask::FinalizeScript(), and v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation().
Member Data Documentation
pending_error_handler_
PendingCompilationErrorHandler v8::internal::UnoptimizedCompileState::pending_error_handler_ [private]
Definition at line 173 of file parse-info.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/parse-info.h