v8::internal::StickySpace Class Reference
#include <paged-spaces.h>
Public Member Functions
size_t young_objects_size () const
size_t old_objects_size () const
void set_old_objects_size (size_t allocated_old_size)
void NotifyBlackAreaCreated (size_t size) override
void NotifyBlackAreaDestroyed (size_t size) override
OldSpace (Heap *heap)
Static Public Member Functions
static StickySpace * From (OldSpace *space)
Private Member Functions
void AdjustDifferenceInAllocatedBytes (size_t) override
Private Attributes
size_t allocated_old_size_ = 0
Additional Inherited Members
Detailed Description
Definition at line 468 of file paged-spaces.h.
Member Function Documentation
AdjustDifferenceInAllocatedBytes()
void v8::internal::StickySpace::AdjustDifferenceInAllocatedBytes (size_t diff) [override], [private], [virtual]
Reimplemented from v8::internal::PagedSpaceBase.
Definition at line 662 of file paged-spaces.cc.
                                                              {
  DCHECK_GE(allocated_old_size_, diff);
  allocated_old_size_ -= diff;
}
References allocated_old_size_, and DCHECK_GE.
From()
static StickySpace* v8::internal::StickySpace::From (OldSpace * space) [inline], [static]
Definition at line 472 of file paged-spaces.h.
                                            {
    DCHECK(v8_flags.sticky_mark_bits);
    return static_cast<StickySpace*>(space);
  }
References v8::internal::DCHECK(), space, and v8::internal::v8_flags.
Referenced by v8::internal::Heap::sticky_space().
NotifyBlackAreaCreated()
void v8::internal::StickySpace::NotifyBlackAreaCreated (size_t size) [inline], [override]
Definition at line 491 of file paged-spaces.h.
                                                    {
    DCHECK_LE(size, Capacity());
    allocated_old_size_ += size;
  }
References DCHECK_LE, and size().
NotifyBlackAreaDestroyed()
void v8::internal::StickySpace::NotifyBlackAreaDestroyed (size_t size) [inline], [override]
Definition at line 496 of file paged-spaces.h.
                                                      {
    DCHECK_LE(size, Capacity());
    allocated_old_size_ -= size;
  }
References DCHECK_LE, and size().
old_objects_size()
size_t v8::internal::StickySpace::old_objects_size () const [inline]
Definition at line 482 of file paged-spaces.h.
                                  {
    DCHECK_GE(Size(), allocated_old_size_);
    return allocated_old_size_;
  }
References DCHECK_GE.
Referenced by v8::internal::Heap::OldGenerationSizeOfObjects(), and v8::internal::Heap::StartMinorMSConcurrentMarkingIfNeeded().
OldSpace()
v8::internal::OldSpace::OldSpace [inline], [explicit]
Definition at line 448 of file paged-spaces.h.
      : PagedSpace(heap, OLD_SPACE, NOT_EXECUTABLE, FreeList::CreateFreeList(),
                   CompactionSpaceKind::kNone) {}
set_old_objects_size()
void v8::internal::StickySpace::set_old_objects_size (size_t allocated_old_size) [inline]
Definition at line 487 of file paged-spaces.h.
                                                       {
    allocated_old_size_ = allocated_old_size;
  }
young_objects_size()
size_t v8::internal::StickySpace::young_objects_size () const [inline]
Definition at line 477 of file paged-spaces.h.
                                    {
    DCHECK_GE(Size(), allocated_old_size_);
    return Size() - allocated_old_size_;
  }
References DCHECK_GE.
Referenced by v8::internal::Heap::CanPromoteYoungAndExpandOldGeneration(), v8::internal::Heap::NewSpaceCapacity(), v8::internal::Heap::NewSpaceSize(), v8::internal::Heap::NewSpaceTargetCapacity(), v8::internal::Heap::StartMinorMSConcurrentMarkingIfNeeded(), v8::internal::MinorMarkSweepCollector::Sweep(), and v8::internal::Heap::YoungGenerationSizeOfObjects().
Member Data Documentation
allocated_old_size_
size_t v8::internal::StickySpace::allocated_old_size_ = 0 [private]
Definition at line 505 of file paged-spaces.h.
Referenced by AdjustDifferenceInAllocatedBytes().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/paged-spaces.h
/mnt/V8SourceCode/src/heap/paged-spaces.cc