v8::internal::maglev::VirtualObject Class Reference
#include <maglev-ir.h>
Classes
struct DoubleArray
struct ObjectFields
struct VirtualConsString
Public Types
enum Type : uint8_t {
kDefault
, kHeapNumber
, kFixedDoubleArray
, kConsString
,
kLast = kConsString
 }
Public Member Functions
VirtualObject (uint64_t bitfield, int id, const VirtualConsString &cons_string)
VirtualObject (uint64_t bitfield, compiler::MapRef map, int id, uint32_t slot_count, ValueNode **slots)
VirtualObject (uint64_t bitfield, compiler::MapRef map, int id, Float64 number)
VirtualObject (uint64_t bitfield, compiler::MapRef map, int id, uint32_t length, compiler::FixedDoubleArrayRef elements)
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
constexpr bool has_static_map () const
compiler::MapRef map () const
Type type () const
uint32_t id () const
size_t size () const
Float64 number () const
uint32_t double_elements_length () const
compiler::FixedDoubleArrayRef double_elements () const
ValueNode * get (uint32_t offset) const
void set (uint32_t offset, ValueNode *value)
ValueNode * string_length () const
const VirtualConsString & cons_string () const
void ClearSlots (int last_init_slot, ValueNode *clear_value)
InlinedAllocation * allocation () const
void set_allocation (InlinedAllocation *allocation)
bool compatible_for_merge (const VirtualObject *other) const
bool IsSnapshot () const
void Snapshot ()
template<typename Function >
void ForEachInput (Function &&callback)
template<typename Function >
void ForEachInput (Function &&callback) const
template<typename Function >
void ForEachNestedRuntimeInput (VirtualObjectList virtual_objects, Function &&f)
template<typename Function >
void ForEachNestedRuntimeInput (VirtualObjectList virtual_objects, Function &&f) const
template<typename Function >
std::optional< VirtualObject * > Merge (const VirtualObject *other, uint32_t new_object_id, Zone *zone, Function MergeValue) const
VirtualObject * Clone (uint32_t new_object_id, Zone *zone, bool empty_clone=false) const
uint32_t slot_count () const
Private Types
using Base = FixedInputValueNodeT< 0, VirtualObject >
Private Member Functions
ValueNode * get_by_index (uint32_t i) const
void set_by_index (uint32_t i, ValueNode *value)
Private Attributes
compiler::OptionalMapRef map_
const int id_
Type type_
bool snapshotted_ = false
xx xx xx xx xx xx xx xx xx
union {
 Float64 number_
 DoubleArray double_array_
 ObjectFields slots_
 VirtualConsString cons_string_
};
InlinedAllocation * allocation_ = nullptr
VirtualObject * next_ = nullptr
friend VirtualObjectList
Friends
std::ostream & operator<< (std::ostream &out, Type type)
Additional Inherited Members
Detailed Description
Definition at line 5808 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::VirtualObject::Base = FixedInputValueNodeT<0, VirtualObject> [private]
Definition at line 5809 of file maglev-ir.h.
Member Enumeration Documentation
Type
enum v8::internal::maglev::VirtualObject::Type : uint8_t
Enumerator
kDefault
kHeapNumber
kFixedDoubleArray
kConsString
kLast
Definition at line 5812 of file maglev-ir.h.
            : uint8_t {
    kDefault,
    kHeapNumber,
    kFixedDoubleArray,
    kConsString,
    kLast = kConsString
  };
Constructor & Destructor Documentation
VirtualObject() [1/4]
v8::internal::maglev::VirtualObject::VirtualObject (uint64_t bitfield, int id, const VirtualConsString & cons_string) [inline], [explicit]
Definition at line 5849 of file maglev-ir.h.
      : Base(bitfield), id_(id), type_(kConsString), cons_string_(cons_string) {
    DCHECK(!has_static_map());
  }
References v8::internal::DCHECK(), and has_static_map().
VirtualObject() [2/4]
v8::internal::maglev::VirtualObject::VirtualObject (uint64_t bitfield, compiler::MapRef map, int id, uint32_t slot_count, ValueNode ** slots) [inline], [explicit]
Definition at line 5855 of file maglev-ir.h.
      : Base(bitfield),
        map_(map),
        id_(id),
        type_(kDefault),
        slots_({slot_count, slots}) {
    DCHECK(has_static_map());
  }
References slot_count().
VirtualObject() [3/4]
v8::internal::maglev::VirtualObject::VirtualObject (uint64_t bitfield, compiler::MapRef map, int id, Float64 number) [inline], [explicit]
Definition at line 5865 of file maglev-ir.h.
      : Base(bitfield),
        map_(map),
        id_(id),
        type_(kHeapNumber),
        number_(number) {
    DCHECK(has_static_map());
  }
References v8::internal::DCHECK(), and has_static_map().
VirtualObject() [4/4]
v8::internal::maglev::VirtualObject::VirtualObject (uint64_t bitfield, compiler::MapRef map, int id, uint32_t length, compiler::FixedDoubleArrayRef elements) [inline], [explicit]
Definition at line 5875 of file maglev-ir.h.
      : Base(bitfield),
        map_(map),
        id_(id),
        type_(kFixedDoubleArray),
        double_array_({length, elements}) {
    DCHECK(has_static_map());
  }
References v8::internal::length.
Member Function Documentation
allocation()
InlinedAllocation* v8::internal::maglev::VirtualObject::allocation () const [inline]
Definition at line 5974 of file maglev-ir.h.
{ return allocation_; }
References allocation_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildVirtualObject(), Clone(), v8::internal::maglev::MaglevGraphBuilder::DeepCopyVirtualObject(), v8::internal::maglev::VirtualObjectList::FindAllocatedWith(), v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObject(), v8::internal::maglev::MaglevGraphLabeller::PrintNodeLabel(), set_allocation(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope(), and v8::internal::maglev::InlinedAllocation::UpdateObject().
ClearSlots()
void v8::internal::maglev::VirtualObject::ClearSlots (int last_init_slot, ValueNode * clear_value) [inline]
Definition at line 5966 of file maglev-ir.h.
                                                              {
    DCHECK_EQ(type_, kDefault);
    int last_init_index = last_init_slot / kTaggedSize;
    for (uint32_t i = last_init_index; i < slot_count(); i++) {
      slots_.data[i] = clear_value;
    }
  }
References v8::internal::maglev::VirtualObject::ObjectFields::data, DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kDefault, v8::internal::kTaggedSize, slot_count(), slots_, and type_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildAndAllocateJSArray(), v8::internal::maglev::MaglevGraphBuilder::CreateFixedArray(), and v8::internal::maglev::MaglevGraphBuilder::TryBuildAndAllocateJSGeneratorObject().
Clone()
VirtualObject* v8::internal::maglev::VirtualObject::Clone (uint32_t new_object_id, Zone * zone, bool empty_clone = false) const [inline]
Definition at line 6079 of file maglev-ir.h.
                                                       {
    VirtualObject* result;
    switch (type_) {
      case kHeapNumber:
      case kFixedDoubleArray:
      case kConsString:
        UNREACHABLE();
      case kDefault: {
        ValueNode** slots = zone->AllocateArray<ValueNode*>(slot_count());
        result = NodeBase::New<VirtualObject>(zone, 0, map(), new_object_id,
                                              slot_count(), slots);
        break;
      }
    }
    if (empty_clone) return result;
    // Copy content
    switch (type_) {
      case kHeapNumber:
      case kFixedDoubleArray:
      case kConsString:
        UNREACHABLE();
      case kDefault: {
        for (uint32_t i = 0; i < slot_count(); i++) {
          result->set_by_index(i, get_by_index(i));
        }
        break;
      }
    }
    result->set_allocation(allocation());
    return result;
  }
References v8::internal::Zone::AllocateArray(), allocation(), get_by_index(), kConsString, kDefault, kFixedDoubleArray, kHeapNumber, map(), v8::base::internal::result, slot_count(), type_, and v8::internal::UNREACHABLE().
Referenced by v8::internal::maglev::MaglevGraphBuilder::DeepCopyVirtualObject(), and Merge().
compatible_for_merge()
bool v8::internal::maglev::VirtualObject::compatible_for_merge (const VirtualObject * other) const [inline]
Definition at line 5979 of file maglev-ir.h.
                                                              {
    if (type_ != other->type_) return false;
    if (allocation_ != other->allocation_) return false;
    // Currently, the graph builder will never change the VO map.
    if (has_static_map()) {
      if (map() != other->map()) return false;
    }
    switch (other->type_) {
      case kHeapNumber:
      case kFixedDoubleArray:
      case kConsString:
        return true;
      case kDefault:
        return slot_count() == other->slot_count();
    }
  }
References allocation_, has_static_map(), kConsString, kDefault, kFixedDoubleArray, kHeapNumber, map(), slot_count(), and type_.
Referenced by Merge(), and v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObject().
cons_string()
const VirtualConsString& v8::internal::maglev::VirtualObject::cons_string () const [inline]
Definition at line 5961 of file maglev-ir.h.
                                               {
    DCHECK_EQ(type_, kConsString);
    return cons_string_;
  }
References cons_string_, DCHECK_EQ, kConsString, and type_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForConsString(), and v8::internal::maglev::MaglevGraphBuilder::BuildNewConsStringMap().
double_elements()
compiler::FixedDoubleArrayRef v8::internal::maglev::VirtualObject::double_elements () const [inline]
Definition at line 5931 of file maglev-ir.h.
                                                      {
    DCHECK_EQ(type_, kFixedDoubleArray);
    return double_array_.values;
  }
References DCHECK_EQ, double_array_, kFixedDoubleArray, type_, and v8::internal::maglev::VirtualObject::DoubleArray::values.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForDoubleFixedArray(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedDoubleArrayElement(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildVirtualObject().
double_elements_length()
uint32_t v8::internal::maglev::VirtualObject::double_elements_length () const [inline]
Definition at line 5926 of file maglev-ir.h.
                                          {
    DCHECK_EQ(type_, kFixedDoubleArray);
    return double_array_.length;
  }
References DCHECK_EQ, double_array_, kFixedDoubleArray, v8::internal::maglev::VirtualObject::DoubleArray::length, and type_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForDoubleFixedArray(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTaggedField(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildVirtualObject(), and size().
ForEachInput() [1/2]
template<typename Function >
void v8::internal::maglev::VirtualObject::ForEachInput (Function && callback) [inline]
Definition at line 6004 of file maglev-ir.h.
                                                {
    switch (type_) {
      case kDefault:
        for (uint32_t i = 0; i < slot_count(); i++) {
          callback(slots_.data[i]);
        }
        break;
      case kConsString:
        for (ValueNode*& val : cons_string_.data) {
          callback(val);
        }
        break;
      case kHeapNumber:
        break;
      case kFixedDoubleArray:
        break;
    }
  }
References cons_string_, v8::internal::maglev::VirtualObject::VirtualConsString::data, v8::internal::maglev::VirtualObject::ObjectFields::data, kConsString, kDefault, kFixedDoubleArray, kHeapNumber, slot_count(), slots_, and type_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddDeoptUse(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocation(), and ForEachNestedRuntimeInput().
ForEachInput() [2/2]
template<typename Function >
void v8::internal::maglev::VirtualObject::ForEachInput (Function && callback) const [inline]
Definition at line 6024 of file maglev-ir.h.
                                                      {
    switch (type_) {
      case kDefault:
        for (uint32_t i = 0; i < slot_count(); i++) {
          callback(get_by_index(i));
        }
        break;
      case kConsString:
        for (ValueNode* val : cons_string_.data) {
          callback(val);
        }
        break;
      case kHeapNumber:
        break;
      case kFixedDoubleArray:
        break;
    }
  }
References cons_string_, v8::internal::maglev::VirtualObject::VirtualConsString::data, get_by_index(), kConsString, kDefault, kFixedDoubleArray, kHeapNumber, slot_count(), and type_.
ForEachNestedRuntimeInput() [1/2]
template<typename Function >
void v8::internal::maglev::VirtualObject::ForEachNestedRuntimeInput (VirtualObjectList virtual_objects, Function && f) [inline]
Definition at line 6371 of file maglev-ir.h.
                                                     {
  ForEachInput([&](ValueNode*& value) {
    if (value->Is<Identity>()) {
      value = value->input(0).node();
    }
    if (IsConstantNode(value->opcode())) {
      // No location assigned to constants.
      return;
    }
    // Special nodes.
    switch (value->opcode()) {
      case Opcode::kArgumentsElements:
      case Opcode::kArgumentsLength:
      case Opcode::kRestLength:
        // No location assigned to these opcodes.
        break;
      case Opcode::kVirtualObject:
        UNREACHABLE();
      case Opcode::kInlinedAllocation: {
        InlinedAllocation* alloc = value->Cast<InlinedAllocation>();
        VirtualObject* inner_vobject = virtual_objects.FindAllocatedWith(alloc);
        // Check if it has escaped.
        if (inner_vobject &&
            (!alloc->HasBeenAnalysed() || alloc->HasBeenElided())) {
          inner_vobject->ForEachNestedRuntimeInput(virtual_objects, f);
        } else {
          f(value);
        }
        break;
      }
      default:
        f(value);
        break;
    }
  });
}
References ForEachInput(), v8::internal::if(), v8::internal::maglev::IsConstantNode(), and v8::internal::value.
Referenced by v8::internal::maglev::DeoptInfoVisitor< DeoptInfoT >::VisitSingleFrame().
ForEachNestedRuntimeInput() [2/2]
template<typename Function >
void v8::internal::maglev::VirtualObject::ForEachNestedRuntimeInput (VirtualObjectList virtual_objects, Function && f) const [inline]
Definition at line 6410 of file maglev-ir.h.
                                                           {
  ForEachInput([&](ValueNode* value) {
    if (value->Is<Identity>()) {
      value = value->input(0).node();
    }
    if (IsConstantNode(value->opcode())) {
      // No location assigned to constants.
      return;
    }
    // Special nodes.
    switch (value->opcode()) {
      case Opcode::kArgumentsElements:
      case Opcode::kArgumentsLength:
      case Opcode::kRestLength:
        // No location assigned to these opcodes.
        break;
      case Opcode::kVirtualObject:
        UNREACHABLE();
      case Opcode::kInlinedAllocation: {
        InlinedAllocation* alloc = value->Cast<InlinedAllocation>();
        VirtualObject* inner_vobject = virtual_objects.FindAllocatedWith(alloc);
        // Check if it has escaped.
        if (inner_vobject &&
            (!alloc->HasBeenAnalysed() || alloc->HasBeenElided())) {
          inner_vobject->ForEachNestedRuntimeInput(virtual_objects, f);
        } else {
          f(value);
        }
        break;
      }
      default:
        f(value);
        break;
    }
  });
}
References v8::internal::if(), v8::internal::maglev::IsConstantNode(), and v8::internal::value.
GenerateCode()
void v8::internal::maglev::VirtualObject::GenerateCode (MaglevAssembler * , const ProcessingState &) [inline]
Definition at line 5887 of file maglev-ir.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
get()
ValueNode* v8::internal::maglev::VirtualObject::get (uint32_t offset) const [inline]
Definition at line 5936 of file maglev-ir.h.
                                        {
    DCHECK_NE(offset, 0); // Don't try to get the map through this getter.
    DCHECK_EQ(type_, kDefault);
    offset -= kTaggedSize;
    SBXCHECK_LT(offset / kTaggedSize, slot_count());
    return slots_.data[offset / kTaggedSize];
  }
References v8::internal::maglev::VirtualObject::ObjectFields::data, DCHECK_EQ, DCHECK_NE, kDefault, v8::internal::kTaggedSize, SBXCHECK_LT, slot_count(), slots_, and type_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTaggedField(), and v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject().
get_by_index()
ValueNode* v8::internal::maglev::VirtualObject::get_by_index (uint32_t i) const [inline], [private]
Definition at line 6119 of file maglev-ir.h.
                                            {
    DCHECK_EQ(type_, kDefault);
    return slots_.data[i];
  }
References v8::internal::maglev::VirtualObject::ObjectFields::data, DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kDefault, slots_, and type_.
Referenced by Clone(), ForEachInput(), and Merge().
has_static_map()
constexpr bool v8::internal::maglev::VirtualObject::has_static_map () const [inline], [constexpr]
Definition at line 5890 of file maglev-ir.h.
                                        {
    switch (type_) {
      case kDefault:
      case kHeapNumber:
      case kFixedDoubleArray:
        return true;
      case kConsString:
        return false;
    }
  }
References kConsString, kDefault, kFixedDoubleArray, kHeapNumber, and type_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocation(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildVirtualObject(), compatible_for_merge(), map(), v8::internal::maglev::MaglevGraphBuilder::TryGetNonEscapingArgumentsObject(), and VirtualObject().
id()
uint32_t v8::internal::maglev::VirtualObject::id () const [inline]
Definition at line 5906 of file maglev-ir.h.
{ return id_; }
References id_.
Referenced by v8::internal::maglev::MaglevGraphLabeller::PrintNodeLabel(), and v8::internal::maglev::VirtualObjectList::WalkUntilCommon().
IsSnapshot()
bool v8::internal::maglev::VirtualObject::IsSnapshot () const [inline]
Definition at line 6000 of file maglev-ir.h.
{ return snapshotted_; }
References snapshotted_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetModifiableObjectFromAllocation(), v8::internal::maglev::MaglevGraphBuilder::GetObjectFromAllocation(), v8::internal::maglev::VirtualObjectList::IsSnapshot(), set(), and v8::internal::maglev::VirtualObjectList::Snapshot().
map()
compiler::MapRef v8::internal::maglev::VirtualObject::map () const [inline]
Definition at line 5901 of file maglev-ir.h.
                             {
    DCHECK(has_static_map());
    return *map_;
  }
References v8::internal::DCHECK(), has_static_map(), and map_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocation(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForDoubleFixedArray(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForHeapNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedArrayElement(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildVirtualObject(), Clone(), compatible_for_merge(), v8::internal::maglev::MaglevGraphBuilder::CreateArgumentsObject(), PrintParams(), v8::internal::maglev::InlinedAllocation::PrintParams(), and v8::internal::maglev::MaglevGraphBuilder::ReduceCallWithArrayLikeForArgumentsObject().
Merge()
template<typename Function >
std::optional<VirtualObject*> v8::internal::maglev::VirtualObject::Merge (const VirtualObject * other, uint32_t new_object_id, Zone * zone, Function MergeValue) const [inline]
Definition at line 6053 of file maglev-ir.h.
                                                                        {
    VirtualObject* result = Clone(new_object_id, zone, /* empty_clone */ true);
    DCHECK(compatible_for_merge(other));
    switch (type_) {
      // These objects are immutable and thus should never need merging.
      case kHeapNumber:
      case kFixedDoubleArray:
      case kConsString:
        UNREACHABLE();
      case kDefault: {
        for (uint32_t i = 0; i < slot_count(); i++) {
          if (auto success =
                  MergeValue(get_by_index(i), other->get_by_index(i))) {
            result->set_by_index(i, *success);
          } else {
            return {};
          }
        }
        break;
      }
    }
    return result;
  }
References Clone(), compatible_for_merge(), v8::internal::DCHECK(), get_by_index(), kConsString, kDefault, kFixedDoubleArray, kHeapNumber, v8::base::internal::result, slot_count(), type_, and v8::internal::UNREACHABLE().
Referenced by v8::internal::maglev::MergePointInterpreterFrameState::MergeVirtualObject().
number()
Float64 v8::internal::maglev::VirtualObject::number () const [inline]
Definition at line 5921 of file maglev-ir.h.
                         {
    DCHECK_EQ(type_, kHeapNumber);
    return number_;
  }
References DCHECK_EQ, kHeapNumber, number_, and type_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForHeapNumber(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildVirtualObject().
PrintParams()
void v8::internal::maglev::VirtualObject::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8002 of file maglev-ir.cc.
                                                                           {
  os << "(" << *map().object() << ")";
}
References map(), and v8::internal::compiler::MapRef::object().
set()
void v8::internal::maglev::VirtualObject::set (uint32_t offset, ValueNode * value) [inline]
Definition at line 5944 of file maglev-ir.h.
                                              {
    DCHECK_NE(offset, 0); // Don't try to set the map through this setter.
    DCHECK_EQ(type_, kDefault);
    DCHECK(!IsSnapshot());
    // Values set here can leak to the interpreter frame state. Conversions
    // should be stored in known_node_aspects/NodeInfo.
    DCHECK(!value->properties().is_conversion());
    offset -= kTaggedSize;
    SBXCHECK_LT(offset / kTaggedSize, slot_count());
    slots_.data[offset / kTaggedSize] = value;
  }
References v8::internal::maglev::VirtualObject::ObjectFields::data, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, IsSnapshot(), kDefault, v8::internal::kTaggedSize, SBXCHECK_LT, slot_count(), slots_, type_, and v8::internal::value.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildAndAllocateJSArray(), v8::internal::maglev::MaglevGraphBuilder::BuildAndAllocateKeyValueArray(), v8::internal::maglev::MaglevGraphBuilder::BuildElementsArray(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedArgumentsElements(), v8::internal::maglev::MaglevGraphBuilder::BuildInlinedUnmappedArgumentsElements(), v8::internal::maglev::MaglevGraphBuilder::BuildVirtualArgumentsObject(), v8::internal::maglev::MaglevGraphBuilder::CreateArgumentsObject(), v8::internal::maglev::MaglevGraphBuilder::CreateContext(), v8::internal::maglev::MaglevGraphBuilder::CreateFixedArray(), v8::internal::maglev::MaglevGraphBuilder::CreateJSIteratorResult(), v8::internal::maglev::MaglevGraphBuilder::CreateJSStringIterator(), v8::internal::maglev::MaglevGraphBuilder::CreateMappedArgumentsElements(), v8::internal::maglev::MaglevGraphBuilder::CreateRegExpLiteralObject(), v8::internal::maglev::MaglevGraphBuilder::TryBuildAndAllocateJSGeneratorObject(), and v8::internal::maglev::MaglevGraphBuilder::TryReadBoilerplateForFastLiteral().
set_allocation()
void v8::internal::maglev::VirtualObject::set_allocation (InlinedAllocation * allocation) [inline]
Definition at line 5975 of file maglev-ir.h.
                                                     {
    allocation_ = allocation;
  }
References allocation(), and allocation_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::ExtendOrReallocateCurrentAllocationBlock().
set_by_index()
void v8::internal::maglev::VirtualObject::set_by_index (uint32_t i, ValueNode * value) [inline], [private]
Definition at line 6124 of file maglev-ir.h.
                                                  {
    DCHECK_EQ(type_, kDefault);
    // Values set here can leak to the interpreter. Conversions should be stored
    // in known_node_aspects/NodeInfo.
    DCHECK(!value->properties().is_conversion());
    slots_.data[i] = value;
  }
References v8::internal::maglev::VirtualObject::ObjectFields::data, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, kDefault, slots_, type_, and v8::internal::value.
SetValueLocationConstraints()
void v8::internal::maglev::VirtualObject::SetValueLocationConstraints () [inline]
Definition at line 5886 of file maglev-ir.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
size()
size_t v8::internal::maglev::VirtualObject::size () const [inline]
Definition at line 5908 of file maglev-ir.h.
                      {
    switch (type_) {
      case kDefault:
        return (slot_count() + 1) * kTaggedSize;
      case kConsString:
        return sizeof(ConsString);
      case kHeapNumber:
        return sizeof(HeapNumber);
      case kFixedDoubleArray:
        return FixedDoubleArray::SizeFor(double_elements_length());
    }
  }
References double_elements_length(), kConsString, kDefault, kFixedDoubleArray, kHeapNumber, v8::internal::kTaggedSize, v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::SizeFor(), slot_count(), and type_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocationForConsString(), v8::internal::maglev::MaglevGraphBuilder::ExtendOrReallocateCurrentAllocationBlock(), and v8::internal::maglev::InlinedAllocation::size().
slot_count()
uint32_t v8::internal::maglev::VirtualObject::slot_count () const [inline]
Definition at line 6113 of file maglev-ir.h.
                              {
    DCHECK_EQ(type_, kDefault);
    return slots_.count;
  }
References v8::internal::maglev::VirtualObject::ObjectFields::count, DCHECK_EQ, kDefault, slots_, and type_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildVirtualObject(), ClearSlots(), Clone(), compatible_for_merge(), ForEachInput(), get(), Merge(), set(), size(), and VirtualObject().
Snapshot()
void v8::internal::maglev::VirtualObject::Snapshot () [inline]
Definition at line 6001 of file maglev-ir.h.
{ snapshotted_ = true; }
References snapshotted_.
Referenced by v8::internal::maglev::VirtualObjectList::Snapshot().
string_length()
ValueNode* v8::internal::maglev::VirtualObject::string_length () const [inline]
Definition at line 5956 of file maglev-ir.h.
                                   {
    DCHECK_EQ(type_, kConsString);
    return cons_string_.length;
  }
References cons_string_, DCHECK_EQ, kConsString, v8::internal::maglev::VirtualObject::VirtualConsString::length, and type_.
type()
Type v8::internal::maglev::VirtualObject::type () const [inline]
Definition at line 5905 of file maglev-ir.h.
{ return type_; }
References type_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildInlinedAllocation(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadFixedArrayElement(), v8::internal::maglev::MaglevGraphBuilder::BuildLoadTaggedField(), v8::internal::maglev::MaglevGraphBuilder::BuildNewConsStringMap(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildVirtualObject(), v8::internal::maglev::MaglevGraphBuilder::DeepCopyVirtualObject(), v8::internal::maglev::InlinedAllocation::PrintParams(), and v8::internal::maglev::MaglevGraphBuilder::StringLengthStaticLowerBound().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, Type type) [friend]
Definition at line 5821 of file maglev-ir.h.
                                                            {
    switch (type) {
      case kDefault:
        out << "object";
        break;
      case kHeapNumber:
        out << "number";
        break;
      case kFixedDoubleArray:
        out << "double[]";
        break;
      case kConsString:
        out << "ConsString";
        break;
    }
    return out;
  }
Member Data Documentation
union { ... } [private]
allocation_
InlinedAllocation* v8::internal::maglev::VirtualObject::allocation_ = nullptr [mutable], [private]
Definition at line 6153 of file maglev-ir.h.
Referenced by allocation(), compatible_for_merge(), and set_allocation().
cons_string_
VirtualConsString v8::internal::maglev::VirtualObject::cons_string_
Definition at line 6151 of file maglev-ir.h.
Referenced by cons_string(), ForEachInput(), and string_length().
double_array_
DoubleArray v8::internal::maglev::VirtualObject::double_array_
Definition at line 6149 of file maglev-ir.h.
Referenced by double_elements(), and double_elements_length().
id_
const int v8::internal::maglev::VirtualObject::id_ [private]
Definition at line 6142 of file maglev-ir.h.
Referenced by id().
map_
compiler::OptionalMapRef v8::internal::maglev::VirtualObject::map_ [private]
Definition at line 6141 of file maglev-ir.h.
Referenced by map().
next_
VirtualObject* v8::internal::maglev::VirtualObject::next_ = nullptr [private]
Definition at line 6155 of file maglev-ir.h.
Referenced by v8::internal::maglev::VirtualObjectList::Add(), v8::internal::maglev::VirtualObjectList::Iterator::operator++(), and v8::internal::maglev::VirtualObjectList::WalkUntilCommon().
number_
Float64 v8::internal::maglev::VirtualObject::number_
Definition at line 6148 of file maglev-ir.h.
Referenced by number().
slots_
ObjectFields v8::internal::maglev::VirtualObject::slots_
Definition at line 6150 of file maglev-ir.h.
Referenced by ClearSlots(), ForEachInput(), get(), get_by_index(), set(), set_by_index(), and slot_count().
snapshotted_
bool v8::internal::maglev::VirtualObject::snapshotted_ = false [private]
Definition at line 6146 of file maglev-ir.h.
Referenced by IsSnapshot(), and Snapshot().
type_
Type v8::internal::maglev::VirtualObject::type_ [private]
Definition at line 6143 of file maglev-ir.h.
Referenced by ClearSlots(), Clone(), compatible_for_merge(), cons_string(), double_elements(), double_elements_length(), ForEachInput(), get(), get_by_index(), has_static_map(), Merge(), number(), set(), set_by_index(), size(), slot_count(), string_length(), and type().
VirtualObjectList
friend v8::internal::maglev::VirtualObject::VirtualObjectList [private]
Definition at line 6156 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc