v8::internal::compiler::BlockAssessments Class Reference
#include <register-allocator-verifier.h>
Public Types
using OperandMap = ZoneMap< InstructionOperand, Assessment *, OperandAsKeyLess >
using OperandSet = ZoneSet< InstructionOperand, OperandAsKeyLess >
Public Member Functions
BlockAssessments (Zone *zone, int spill_slot_delta, const InstructionSequence *sequence)
BlockAssessments (const BlockAssessments &)=delete
BlockAssessments & operator= (const BlockAssessments &)=delete
void Drop (InstructionOperand operand)
void DropRegisters ()
void AddDefinition (InstructionOperand operand, int virtual_register)
void PerformMoves (const Instruction *instruction)
void PerformParallelMoves (const ParallelMove *moves)
void CopyFrom (const BlockAssessments *other)
void CheckReferenceMap (const ReferenceMap *reference_map)
bool IsStaleReferenceStackSlot (InstructionOperand op, std::optional< int > vreg=std::nullopt)
OperandMap & map ()
const OperandMap & map () const
OperandSet & stale_ref_stack_slots ()
const OperandSet & stale_ref_stack_slots () const
int spill_slot_delta () const
void Print () const
Private Attributes
OperandMap map_
OperandMap map_for_moves_
OperandSet stale_ref_stack_slots_
int spill_slot_delta_
Zone * zone_
const InstructionSequence * sequence_
Detailed Description
Definition at line 136 of file register-allocator-verifier.h.
Member Typedef Documentation
OperandMap
using v8::internal::compiler::BlockAssessments::OperandMap = ZoneMap<InstructionOperand, Assessment*, OperandAsKeyLess>
Definition at line 138 of file register-allocator-verifier.h.
OperandSet
using v8::internal::compiler::BlockAssessments::OperandSet = ZoneSet<InstructionOperand, OperandAsKeyLess>
Definition at line 139 of file register-allocator-verifier.h.
Constructor & Destructor Documentation
BlockAssessments() [1/2]
v8::internal::compiler::BlockAssessments::BlockAssessments (Zone * zone, int spill_slot_delta, const InstructionSequence * sequence) [inline], [explicit]
Definition at line 140 of file register-allocator-verifier.h.
      : map_(zone),
        map_for_moves_(zone),
        stale_ref_stack_slots_(zone),
        spill_slot_delta_(spill_slot_delta),
        zone_(zone),
        sequence_(sequence) {}
BlockAssessments() [2/2]
v8::internal::compiler::BlockAssessments::BlockAssessments (const BlockAssessments &) [delete]
Member Function Documentation
AddDefinition()
void v8::internal::compiler::BlockAssessments::AddDefinition (InstructionOperand operand, int virtual_register) [inline]
Definition at line 156 of file register-allocator-verifier.h.
                                                                       {
    auto existent = map_.find(operand);
    if (existent != map_.end()) {
      // Drop the assignment
      map_.erase(existent);
      // Destination operand is no longer a stale reference.
      stale_ref_stack_slots_.erase(operand);
    }
    map_.insert(
        std::make_pair(operand, zone_->New<FinalAssessment>(virtual_register)));
  }
References map_, v8::internal::Zone::New(), stale_ref_stack_slots_, and zone_.
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
CheckReferenceMap()
void v8::internal::compiler::BlockAssessments::CheckReferenceMap (const ReferenceMap * reference_map)
Definition at line 330 of file register-allocator-verifier.cc.
                                                                          {
  // First mark all existing reference stack spill slots as stale.
  for (auto pair : map()) {
    InstructionOperand op = pair.first;
    if (op.IsStackSlot()) {
      const LocationOperand* loc_op = LocationOperand::cast(&op);
      // Only mark arguments that are spill slots as stale, the reference map
      // doesn't track arguments or fixed stack slots, which are implicitly
      // tracked by the GC.
      if (CanBeTaggedOrCompressedPointer(loc_op->representation()) &&
          loc_op->index() >= spill_slot_delta()) {
        stale_ref_stack_slots().insert(op);
      }
    }
  }
  // Now remove any stack spill slots in the reference map from the list of
  // stale slots.
  for (auto ref_map_operand : reference_map->reference_operands()) {
    if (ref_map_operand.IsStackSlot()) {
      auto pair = map().find(ref_map_operand);
      CHECK(pair != map().end());
      stale_ref_stack_slots().erase(pair->first);
    }
  }
}
References v8::internal::CanBeTaggedOrCompressedPointer(), v8::internal::compiler::LocationOperand::cast(), CHECK, v8::internal::compiler::end(), v8::internal::compiler::LocationOperand::index(), v8::internal::compiler::InstructionOperand::IsStackSlot(), map(), v8::internal::compiler::ReferenceMap::reference_operands(), v8::internal::compiler::LocationOperand::representation(), spill_slot_delta(), and stale_ref_stack_slots().
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
CopyFrom()
void v8::internal::compiler::BlockAssessments::CopyFrom (const BlockAssessments * other) [inline]
Definition at line 170 of file register-allocator-verifier.h.
                                               {
    CHECK(map_.empty());
    CHECK(stale_ref_stack_slots_.empty());
    CHECK_NOT_NULL(other);
    map_.insert(other->map_.begin(), other->map_.end());
    stale_ref_stack_slots_.insert(other->stale_ref_stack_slots_.begin(),
                                  other->stale_ref_stack_slots_.end());
  }
References CHECK, CHECK_NOT_NULL, map_, and stale_ref_stack_slots_.
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::CreateForBlock().
Drop()
void v8::internal::compiler::BlockAssessments::Drop (InstructionOperand operand) [inline]
Definition at line 151 of file register-allocator-verifier.h.
                                        {
    map_.erase(operand);
    stale_ref_stack_slots_.erase(operand);
  }
References map_, and stale_ref_stack_slots_.
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
DropRegisters()
void v8::internal::compiler::BlockAssessments::DropRegisters ()
Definition at line 321 of file register-allocator-verifier.cc.
                                     {
  for (auto iterator = map().begin(), end = map().end(); iterator != end;) {
    auto current = iterator;
    ++iterator;
    InstructionOperand op = current->first;
    if (op.IsAnyRegister()) map().erase(current);
  }
}
References v8::internal::compiler::begin(), v8::internal::compiler::end(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), and map().
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
IsStaleReferenceStackSlot()
bool v8::internal::compiler::BlockAssessments::IsStaleReferenceStackSlot (InstructionOperand op, std::optional< int > vreg = std::nullopt)
Definition at line 357 of file register-allocator-verifier.cc.
                                                                        {
  if (!op.IsStackSlot()) return false;
  if (vreg.has_value() && !sequence_->IsReference(*vreg)) return false;
  const LocationOperand* loc_op = LocationOperand::cast(&op);
  return CanBeTaggedOrCompressedPointer(loc_op->representation()) &&
         stale_ref_stack_slots().find(op) != stale_ref_stack_slots().end();
}
References v8::internal::CanBeTaggedOrCompressedPointer(), v8::internal::compiler::LocationOperand::cast(), v8::internal::compiler::InstructionSequence::IsReference(), v8::internal::compiler::InstructionOperand::IsStackSlot(), v8::internal::compiler::LocationOperand::representation(), sequence_, and stale_ref_stack_slots().
Referenced by PerformParallelMoves(), v8::internal::compiler::RegisterAllocatorVerifier::ValidateUse(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
map() [1/2]
OperandMap& v8::internal::compiler::BlockAssessments::map () [inline]
Definition at line 182 of file register-allocator-verifier.h.
{ return map_; }
References map_.
Referenced by CheckReferenceMap(), v8::internal::compiler::RegisterAllocatorVerifier::CreateForBlock(), DropRegisters(), Print(), v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment(), v8::internal::compiler::RegisterAllocatorVerifier::ValidateUse(), and v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
map() [2/2]
const OperandMap& v8::internal::compiler::BlockAssessments::map () const [inline]
Definition at line 183 of file register-allocator-verifier.h.
{ return map_; }
References map_.
operator=()
BlockAssessments& v8::internal::compiler::BlockAssessments::operator= (const BlockAssessments &) [delete]
PerformMoves()
void v8::internal::compiler::BlockAssessments::PerformMoves (const Instruction * instruction)
Definition at line 282 of file register-allocator-verifier.cc.
                                                                  {
  const ParallelMove* first =
      instruction->GetParallelMove(Instruction::GapPosition::START);
  PerformParallelMoves(first);
  const ParallelMove* last =
      instruction->GetParallelMove(Instruction::GapPosition::END);
  PerformParallelMoves(last);
}
References v8::internal::compiler::Instruction::GetParallelMove(), and PerformParallelMoves().
Referenced by v8::internal::compiler::RegisterAllocatorVerifier::VerifyGapMoves().
PerformParallelMoves()
void v8::internal::compiler::BlockAssessments::PerformParallelMoves (const ParallelMove * moves)
Definition at line 291 of file register-allocator-verifier.cc.
                                                                     {
  if (moves == nullptr) return;
  CHECK(map_for_moves_.empty());
  for (MoveOperands* move : *moves) {
    if (move->IsEliminated() || move->IsRedundant()) continue;
    auto it = map_.find(move->source());
    // The RHS of a parallel move should have been already assessed.
    CHECK(it != map_.end());
    // The LHS of a parallel move should not have been assigned in this
    // parallel move.
    CHECK(map_for_moves_.find(move->destination()) == map_for_moves_.end());
    // The RHS of a parallel move should not be a stale reference.
    CHECK(!IsStaleReferenceStackSlot(move->source()));
    // Copy the assessment to the destination.
    map_for_moves_[move->destination()] = it->second;
  }
  for (auto pair : map_for_moves_) {
    // Re-insert the existing key for the new assignment so that it has the
    // correct representation (which is ignored by the canonicalizing map
    // comparator).
    InstructionOperand op = pair.first;
    map_.erase(op);
    map_.insert(pair);
    // Destination is no longer a stale reference.
    stale_ref_stack_slots().erase(op);
  }
  map_for_moves_.clear();
}
References CHECK, IsStaleReferenceStackSlot(), map_, map_for_moves_, and stale_ref_stack_slots().
Referenced by PerformMoves().
Print()
void v8::internal::compiler::BlockAssessments::Print () const
Definition at line 367 of file register-allocator-verifier.cc.
                                   {
  StdoutStream os;
  for (const auto& pair : map()) {
    const InstructionOperand op = pair.first;
    const Assessment* assessment = pair.second;
    // Use operator<< so we can write the assessment on the same
    // line.
    os << op << " : ";
    if (assessment->kind() == AssessmentKind::Final) {
      os << "v" << FinalAssessment::cast(assessment)->virtual_register();
    } else {
      os << "P";
    }
    if (stale_ref_stack_slots().find(op) != stale_ref_stack_slots().end()) {
      os << " (stale reference)";
    }
    os << std::endl;
  }
  os << std::endl;
}
References v8::internal::compiler::FinalAssessment::cast(), v8::internal::compiler::end(), v8::internal::compiler::Final, v8::internal::compiler::Assessment::kind(), map(), stale_ref_stack_slots(), and v8::internal::compiler::FinalAssessment::virtual_register().
spill_slot_delta()
int v8::internal::compiler::BlockAssessments::spill_slot_delta () const [inline]
Definition at line 190 of file register-allocator-verifier.h.
{ return spill_slot_delta_; }
References spill_slot_delta_.
Referenced by CheckReferenceMap().
stale_ref_stack_slots() [1/2]
OperandSet& v8::internal::compiler::BlockAssessments::stale_ref_stack_slots () [inline]
Definition at line 185 of file register-allocator-verifier.h.
{ return stale_ref_stack_slots_; }
References stale_ref_stack_slots_.
Referenced by CheckReferenceMap(), v8::internal::compiler::RegisterAllocatorVerifier::CreateForBlock(), IsStaleReferenceStackSlot(), PerformParallelMoves(), and Print().
stale_ref_stack_slots() [2/2]
const OperandSet& v8::internal::compiler::BlockAssessments::stale_ref_stack_slots () const [inline]
Definition at line 186 of file register-allocator-verifier.h.
                                                  {
    return stale_ref_stack_slots_;
  }
References stale_ref_stack_slots_.
Member Data Documentation
map_
OperandMap v8::internal::compiler::BlockAssessments::map_ [private]
Definition at line 195 of file register-allocator-verifier.h.
Referenced by AddDefinition(), CopyFrom(), Drop(), map(), and PerformParallelMoves().
map_for_moves_
OperandMap v8::internal::compiler::BlockAssessments::map_for_moves_ [private]
Definition at line 196 of file register-allocator-verifier.h.
Referenced by PerformParallelMoves().
sequence_
const InstructionSequence* v8::internal::compiler::BlockAssessments::sequence_ [private]
Definition at line 202 of file register-allocator-verifier.h.
Referenced by IsStaleReferenceStackSlot().
spill_slot_delta_
int v8::internal::compiler::BlockAssessments::spill_slot_delta_ [private]
Definition at line 200 of file register-allocator-verifier.h.
Referenced by spill_slot_delta().
stale_ref_stack_slots_
OperandSet v8::internal::compiler::BlockAssessments::stale_ref_stack_slots_ [private]
Definition at line 199 of file register-allocator-verifier.h.
Referenced by AddDefinition(), CopyFrom(), Drop(), and stale_ref_stack_slots().
zone_
Zone* v8::internal::compiler::BlockAssessments::zone_ [private]
Definition at line 201 of file register-allocator-verifier.h.
Referenced by AddDefinition().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator-verifier.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator-verifier.cc