v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler Class Reference
#include <code-assembler.h>
Public Member Functions
~BuiltinCompilationScheduler ()
int builtins_installed_count () const
void CompileCode (Isolate *isolate, std::unique_ptr< TurbofanCompilationJob > job)
void AwaitAndFinalizeCurrentBatch (Isolate *isolate)
Private Member Functions
void QueueJob (Isolate *isolate, std::unique_ptr< TurbofanCompilationJob > job)
void FinalizeJobOnMainThread (Isolate *isolate, TurbofanCompilationJob *job)
Private Attributes
int builtins_installed_count_ = 0
size_t current_batch_zone_size_ = 0
std::deque< std::unique_ptr< TurbofanCompilationJob > > main_thread_output_queue_
Detailed Description
Definition at line 441 of file code-assembler.h.
Constructor & Destructor Documentation
 BuiltinCompilationScheduler()
v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::~BuiltinCompilationScheduler ()
Definition at line 161 of file code-assembler.cc.
                                                                       {
  // Did you forget to call AwaitAndFinalizeCurrentBatch()?
  CHECK_EQ(0, current_batch_zone_size_);
  CHECK(main_thread_output_queue_.empty());
}
References CHECK, CHECK_EQ, current_batch_zone_size_, and main_thread_output_queue_.
Member Function Documentation
AwaitAndFinalizeCurrentBatch()
void v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::AwaitAndFinalizeCurrentBatch (Isolate * isolate)
Definition at line 221 of file code-assembler.cc.
                      {
  if (v8_flags.concurrent_builtin_generation) {
    auto* dispatcher = isolate->optimizing_compile_dispatcher();
    dispatcher->WaitUntilCompilationJobsDone();
    builtins_installed_count_ =
        dispatcher->InstallGeneratedBuiltins(builtins_installed_count_);
  } else {
    DCHECK_IMPLIES(v8_flags.turbo_profiling, main_thread_output_queue_.empty());
    while (!main_thread_output_queue_.empty()) {
      FinalizeJobOnMainThread(isolate, main_thread_output_queue_.front().get());
      main_thread_output_queue_.pop_front();
    }
  }
  current_batch_zone_size_ = 0;
}
References DCHECK_IMPLIES, v8::internal::compiler::CodeAssembler::isolate(), v8::internal::Isolate::optimizing_compile_dispatcher(), v8::internal::v8_flags, and v8::internal::OptimizingCompileDispatcher::WaitUntilCompilationJobsDone().
builtins_installed_count()
int v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::builtins_installed_count () const [inline]
Definition at line 445 of file code-assembler.h.
{ return builtins_installed_count_; }
CompileCode()
void v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::CompileCode (Isolate * isolate, std::unique_ptr< TurbofanCompilationJob > job)
Definition at line 167 of file code-assembler.cc.
                                                                 {
#ifdef V8_USE_ADDRESS_SANITIZER
  constexpr size_t kInputZoneBatchSize = 128UL * MB;
#else // !V8_USE_ADDRESS_SANITIZER
  constexpr size_t kInputZoneBatchSize = 1536UL * MB;
#endif // V8_USE_ADDRESS_SANITIZER
  // This must be called from the main thread.
  DCHECK_EQ(ThreadId::Current(), isolate->thread_id());
  DCHECK(job->compilation_info()->code_kind() == CodeKind::BUILTIN ||
         job->compilation_info()->code_kind() == CodeKind::BYTECODE_HANDLER);
  CHECK_EQ(CompilationJob::SUCCEEDED, job->PrepareJob(isolate));
  if (current_batch_zone_size_ >= kInputZoneBatchSize) {
    AwaitAndFinalizeCurrentBatch(isolate);
  }
  QueueJob(isolate, std::move(job));
}
References BUILTIN, CHECK_EQ, v8::internal::ThreadId::Current(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::CodeAssembler::isolate(), v8::internal::MB, v8::internal::CompilationJob::SUCCEEDED, and v8::internal::Isolate::thread_id().
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileBytecodeHandler(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileCSLinkageCodeStubBuiltin(), and v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileJSLinkageCodeStubBuiltin().
FinalizeJobOnMainThread()
void v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::FinalizeJobOnMainThread (Isolate * isolate, TurbofanCompilationJob * job) [private]
Definition at line 215 of file code-assembler.cc.
                                                   {
  CHECK_EQ(CompilationJob::SUCCEEDED, job->FinalizeJob(isolate));
  builtins_installed_count_++;
}
References CHECK_EQ, v8::internal::OptimizedCompilationJob::FinalizeJob(), v8::internal::compiler::CodeAssembler::isolate(), and v8::internal::CompilationJob::SUCCEEDED.
QueueJob()
void v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::QueueJob (Isolate * isolate, std::unique_ptr< TurbofanCompilationJob > job) [private]
Definition at line 190 of file code-assembler.cc.
                                                                 {
  current_batch_zone_size_ +=
      job->compilation_info()->zone()->allocation_size();
  if (v8_flags.concurrent_builtin_generation) {
    auto* dispatcher = isolate->optimizing_compile_dispatcher();
    // Spin until we can queue the job.
    while (!dispatcher->TryQueueForOptimization(job)) {
      std::this_thread::yield();
    }
  } else {
    CHECK_EQ(CompilationJob::SUCCEEDED,
             job->ExecuteJob(isolate->counters()->runtime_call_stats(),
                             isolate->main_thread_local_isolate()));
    if (!v8_flags.turbo_profiling) {
      main_thread_output_queue_.push_back(std::move(job));
    } else {
      // When profiling builtins for PGO, each builtin must be completely
      // generated one at a time (i.e. PrepareJob, ExecuteJob, and FinalizeJob)
      // instead of batched.
      FinalizeJobOnMainThread(isolate, job.get());
    }
  }
}
References CHECK_EQ, v8::internal::Isolate::counters(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::Isolate::main_thread_local_isolate(), v8::internal::Isolate::optimizing_compile_dispatcher(), v8::internal::Counters::runtime_call_stats(), v8::internal::CompilationJob::SUCCEEDED, and v8::internal::v8_flags.
Member Data Documentation
builtins_installed_count_
int v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::builtins_installed_count_ = 0 [private]
Definition at line 458 of file code-assembler.h.
current_batch_zone_size_
size_t v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::current_batch_zone_size_ = 0 [private]
Definition at line 461 of file code-assembler.h.
Referenced by ~BuiltinCompilationScheduler().
main_thread_output_queue_
std::deque<std::unique_ptr<TurbofanCompilationJob> > v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::main_thread_output_queue_ [private]
Definition at line 467 of file code-assembler.h.
Referenced by ~BuiltinCompilationScheduler().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/code-assembler.h
/mnt/V8SourceCode/src/compiler/code-assembler.cc