v8::internal::ConstructFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
void Iterate (RootVisitor *v) const override
Static Public Member Functions
static ConstructFrame * cast (StackFrame *frame)
Protected Member Functions
ConstructFrame (StackFrameIteratorBase *iterator)
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 1510 of file frames.h.
Constructor & Destructor Documentation
ConstructFrame()
v8::internal::ConstructFrame::ConstructFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 365 of file frames-inl.h.
    : InternalFrame(iterator) {}
Member Function Documentation
cast()
static ConstructFrame* v8::internal::ConstructFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 1514 of file frames.h.
                                                 {
    DCHECK(frame->is_construct());
    return static_cast<ConstructFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_construct().
Iterate()
void v8::internal::ConstructFrame::Iterate (RootVisitor * v) const [override], [virtual]
Reimplemented from v8::internal::InternalFrame.
Definition at line 341 of file frames.cc.
                                                 {
  // The frame contains the actual argument count (intptr) that should not
  // be visited.
  FullObjectSlot argc(
      &Memory<Address>(fp() + ConstructFrameConstants::kLengthOffset));
  const int last_object_offset = ConstructFrameConstants::kLastObjectOffset;
  FullObjectSlot base(&Memory<Address>(sp()));
  FullObjectSlot limit(&Memory<Address>(fp() + last_object_offset) + 1);
  v->VisitRootPointers(Root::kStackRoots, nullptr, base, argc);
  v->VisitRootPointers(Root::kStackRoots, nullptr, argc + 1, limit);
  IteratePc(v, constant_pool_address(), GcSafeLookupCode());
}
References v8::internal::StackFrame::constant_pool_address(), v8::internal::StackFrame::fp(), v8::internal::StackFrame::GcSafeLookupCode(), v8::internal::StackFrame::IteratePc(), v8::internal::ConstructFrameConstants::kLastObjectOffset, v8::internal::ConstructFrameConstants::kLengthOffset, v8::internal::StackFrame::sp(), and v8::internal::RootVisitor::VisitRootPointers().
type()
Type v8::internal::ConstructFrame::type () const [inline], [override], [virtual]
Reimplemented from v8::internal::InternalFrame.
Definition at line 1512 of file frames.h.
{ return CONSTRUCT; }
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 1525 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc