v8::internal::compiler::NodeAuxData< T, def > Class Template Reference
#include <node-aux-data.h>
Classes
class const_iterator
Public Member Functions
NodeAuxData (Zone *zone)
NodeAuxData (size_t initial_size, Zone *zone)
bool Set (Node *node, T const &data)
bool Set (NodeId id, T const &data)
T Get (Node *node) const
T Get (NodeId id) const
const_iterator begin () const
const_iterator end () const
Private Attributes
Zone * zone_
ZoneVector< T > aux_data_
Friends
class const_iterator
Detailed Description
template<class T, T def = DefaultConstruct<T>>
class v8::internal::compiler::NodeAuxData< T, def >
Definition at line 29 of file node-aux-data.h.
Constructor & Destructor Documentation
NodeAuxData() [1/2]
template<class T , T def = DefaultConstruct<T>>
v8::internal::compiler::NodeAuxData< T, def >::NodeAuxData (Zone * zone) [inline], [explicit]
Definition at line 31 of file node-aux-data.h.
: zone_(zone), aux_data_(zone) {}
NodeAuxData() [2/2]
template<class T , T def = DefaultConstruct<T>>
v8::internal::compiler::NodeAuxData< T, def >::NodeAuxData (size_t initial_size, Zone * zone) [inline], [explicit]
Definition at line 32 of file node-aux-data.h.
      : zone_(zone), aux_data_(initial_size, def(zone), zone) {}
Member Function Documentation
begin()
template<class T , T def>
NodeAuxData< T, def >::const_iterator v8::internal::compiler::NodeAuxData< T, def >::begin
Definition at line 102 of file node-aux-data.h.
          {
  return typename NodeAuxData<T, def>::const_iterator(&aux_data_, 0);
}
References v8::internal::compiler::NodeAuxData< T, def >::const_iterator.
end()
template<class T , T def>
NodeAuxData< T, def >::const_iterator v8::internal::compiler::NodeAuxData< T, def >::end
Definition at line 108 of file node-aux-data.h.
                                                                          {
  return typename NodeAuxData<T, def>::const_iterator(&aux_data_,
                                                      aux_data_.size());
}
References v8::internal::compiler::NodeAuxData< T, def >::const_iterator.
Get() [1/2]
template<class T , T def = DefaultConstruct<T>>
T v8::internal::compiler::NodeAuxData< T, def >::Get (Node * node) const [inline]
Definition at line 50 of file node-aux-data.h.
{ return Get(node->id()); }
References v8::internal::compiler::NodeAuxData< T, def >::Get(), and v8::internal::compiler::Node::id().
Referenced by v8::internal::compiler::NodeAuxData< T, def >::Get(), v8::internal::compiler::AdvancedReducerWithControlPathState< NodeState, node_uniqueness >::IsReduced(), and v8::internal::compiler::LoopVariableOptimizer::Run().
Get() [2/2]
template<class T , T def = DefaultConstruct<T>>
T v8::internal::compiler::NodeAuxData< T, def >::Get (NodeId id) const [inline]
Definition at line 52 of file node-aux-data.h.
                         {
    return (id < aux_data_.size()) ? aux_data_[id] : def(zone_);
  }
References v8::internal::compiler::NodeAuxData< T, def >::aux_data_, and v8::internal::compiler::NodeAuxData< T, def >::zone_.
Set() [1/2]
template<class T , T def = DefaultConstruct<T>>
bool v8::internal::compiler::NodeAuxData< T, def >::Set (Node * node, T const & data) [inline]
Definition at line 36 of file node-aux-data.h.
                                      {
    NodeId const id = node->id();
    return Set(id, data);
  }
References v8::internal::compiler::Node::id().
Referenced by v8::internal::compiler::LoopVariableOptimizer::Run().
Set() [2/2]
template<class T , T def = DefaultConstruct<T>>
bool v8::internal::compiler::NodeAuxData< T, def >::Set (NodeId id, T const & data) [inline]
Definition at line 41 of file node-aux-data.h.
                                     {
    if (id >= aux_data_.size()) aux_data_.resize(id + 1, def(zone_));
    if (aux_data_[id] != data) {
      aux_data_[id] = data;
      return true;
    }
    return false;
  }
References v8::internal::compiler::NodeAuxData< T, def >::aux_data_, and v8::internal::compiler::NodeAuxData< T, def >::zone_.
Friends And Related Function Documentation
const_iterator
template<class T , T def = DefaultConstruct<T>>
friend class const_iterator [friend]
Definition at line 57 of file node-aux-data.h.
Referenced by v8::internal::compiler::NodeAuxData< T, def >::begin(), and v8::internal::compiler::NodeAuxData< T, def >::end().
Member Data Documentation
aux_data_
template<class T , T def = DefaultConstruct<T>>
ZoneVector<T> v8::internal::compiler::NodeAuxData< T, def >::aux_data_ [private]
Definition at line 64 of file node-aux-data.h.
Referenced by v8::internal::compiler::NodeAuxData< T, def >::Get(), and v8::internal::compiler::NodeAuxData< T, def >::Set().
zone_
template<class T , T def = DefaultConstruct<T>>
Zone* v8::internal::compiler::NodeAuxData< T, def >::zone_ [private]
Definition at line 63 of file node-aux-data.h.
Referenced by v8::internal::compiler::NodeAuxData< T, def >::Get(), and v8::internal::compiler::NodeAuxData< T, def >::Set().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/node-aux-data.h