v8::internal::maglev::LoadTypedArrayLength Class Reference
#include <maglev-ir.h>
Public Member Functions
LoadTypedArrayLength (uint64_t bitfield, ElementsKind elements_kind)
Input & receiver_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
ElementsKind elements_kind () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
static constexpr int kReceiverIndex = 0
Private Types
using Base = FixedInputValueNodeT< 1, LoadTypedArrayLength >
Private Attributes
ElementsKind elements_kind_
Additional Inherited Members
Detailed Description
Definition at line 7437 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::LoadTypedArrayLength::Base = FixedInputValueNodeT<1, LoadTypedArrayLength> [private]
Definition at line 7439 of file maglev-ir.h.
Constructor & Destructor Documentation
LoadTypedArrayLength()
v8::internal::maglev::LoadTypedArrayLength::LoadTypedArrayLength (uint64_t bitfield, ElementsKind elements_kind) [inline], [explicit]
Definition at line 7442 of file maglev-ir.h.
      : Base(bitfield), elements_kind_(elements_kind) {}
Member Function Documentation
elements_kind()
ElementsKind v8::internal::maglev::LoadTypedArrayLength::elements_kind () const [inline]
Definition at line 7458 of file maglev-ir.h.
{ return elements_kind_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::LoadTypedArrayLength::GenerateCode (MaglevAssembler * masm, const ProcessingState & state)
Definition at line 717 of file maglev-ir-arm.cc.
                                                                      {
  Register object = ToRegister(receiver_input());
  Register result_register = ToRegister(result());
  if (v8_flags.debug_code) {
    __ AssertObjectType(object, JS_TYPED_ARRAY_TYPE,
                        AbortReason::kUnexpectedValue);
  }
  __ LoadBoundedSizeFromObject(result_register, object,
                               JSTypedArray::kRawByteLengthOffset);
  int shift_size = ElementsKindToShiftSize(elements_kind_);
  if (shift_size > 0) {
    // TODO(leszeks): Merge this shift with the one in LoadBoundedSize.
    DCHECK(shift_size == 1 || shift_size == 2 || shift_size == 3);
    __ lsr(result_register, result_register, Operand(shift_size));
options()
auto v8::internal::maglev::LoadTypedArrayLength::options () const [inline]
Definition at line 7456 of file maglev-ir.h.
{ return std::tuple{elements_kind_}; }
PrintParams()
void v8::internal::maglev::LoadTypedArrayLength::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 7454 of file maglev-ir.h.
{}
receiver_input()
Input& v8::internal::maglev::LoadTypedArrayLength::receiver_input () [inline]
Definition at line 7450 of file maglev-ir.h.
{ return input(kReceiverIndex); }
Referenced by v8::internal::maglev::LoopOptimizationProcessor::Process(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::LoadTypedArrayLength::SetValueLocationConstraints ()
Definition at line 713 of file maglev-ir-arm.cc.
                                                       {
  UseRegister(receiver_input());
Member Data Documentation
elements_kind_
ElementsKind v8::internal::maglev::LoadTypedArrayLength::elements_kind_ [private]
Definition at line 7461 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::LoadTypedArrayLength::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 7447 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::LoadTypedArrayLength::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::IntPtr() | OpProperties::CanRead()
Definition at line 7444 of file maglev-ir.h.
kReceiverIndex
constexpr int v8::internal::maglev::LoadTypedArrayLength::kReceiverIndex = 0 [static], [constexpr]
Definition at line 7449 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/arm/maglev-ir-arm.cc
/mnt/V8SourceCode/src/maglev/arm64/maglev-ir-arm64.cc
/mnt/V8SourceCode/src/maglev/riscv/maglev-ir-riscv.cc
/mnt/V8SourceCode/src/maglev/s390/maglev-ir-s390.cc
/mnt/V8SourceCode/src/maglev/x64/maglev-ir-x64.cc