v8::internal::Suspend Class Reference
#include <ast.h>
Public Types
enum OnAbruptResume { kOnExceptionThrow
, kNoControl
 }
Public Member Functions
Expression * expression () const
OnAbruptResume on_abrupt_resume () const
Private Types
using OnAbruptResumeField = Expression::NextBitField< OnAbruptResume, 1 >
Private Member Functions
Suspend (NodeType node_type, Expression *expression, int pos, OnAbruptResume on_abrupt_resume)
Private Attributes
friend Zone
Expression * expression_
Friends
class AstNodeFactory
class Yield
class YieldStar
class Await
Additional Inherited Members
Detailed Description
Definition at line 2224 of file ast.h.
Member Typedef Documentation
OnAbruptResumeField
using v8::internal::Suspend::OnAbruptResumeField = Expression::NextBitField<OnAbruptResume, 1> [private]
Definition at line 2253 of file ast.h.
Member Enumeration Documentation
OnAbruptResume
enum v8::internal::Suspend::OnAbruptResume
Enumerator
kOnExceptionThrow
kNoControl
Definition at line 2231 of file ast.h.
{ kOnExceptionThrow, kNoControl };
Constructor & Destructor Documentation
Suspend()
v8::internal::Suspend::Suspend (NodeType node_type, Expression * expression, int pos, OnAbruptResume on_abrupt_resume) [inline], [private]
Definition at line 2245 of file ast.h.
      : Expression(pos, node_type), expression_(expression) {
    bit_field_ |= OnAbruptResumeField::encode(on_abrupt_resume);
  }
References v8::internal::AstNode::bit_field_, v8::base::BitField< T, shift, size, U >::encode(), and on_abrupt_resume().
Member Function Documentation
expression()
Expression* v8::internal::Suspend::expression () const [inline]
Definition at line 2233 of file ast.h.
{ return expression_; }
References expression_.
on_abrupt_resume()
OnAbruptResume v8::internal::Suspend::on_abrupt_resume () const [inline]
Definition at line 2234 of file ast.h.
                                          {
    return OnAbruptResumeField::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by Suspend().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 2239 of file ast.h.
Await
friend class Await [friend]
Definition at line 2243 of file ast.h.
Yield
friend class Yield [friend]
Definition at line 2241 of file ast.h.
YieldStar
friend class YieldStar [friend]
Definition at line 2242 of file ast.h.
Member Data Documentation
expression_
Expression* v8::internal::Suspend::expression_ [private]
Definition at line 2251 of file ast.h.
Referenced by expression().
Zone
friend v8::internal::Suspend::Zone [private]
Definition at line 2240 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h