v8::internal::HeapSnapshot Class Reference
#include <heap-snapshot-generator.h>
Public Member Functions
HeapSnapshot (HeapProfiler *profiler, v8::HeapProfiler::HeapSnapshotMode snapshot_mode, v8::HeapProfiler::NumericsMode numerics_mode)
HeapSnapshot (const HeapSnapshot &)=delete
HeapSnapshot & operator= (const HeapSnapshot &)=delete
void Delete ()
HeapProfiler * profiler () const
HeapEntry * root () const
HeapEntry * gc_roots () const
HeapEntry * gc_subroot (Root root) const
std::deque< HeapEntry > & entries ()
const std::deque< HeapEntry > & entries () const
std::deque< HeapGraphEdge > & edges ()
const std::deque< HeapGraphEdge > & edges () const
std::vector< HeapGraphEdge * > & children ()
const std::vector< EntrySourceLocation > & locations () const
void RememberLastJSObjectId ()
SnapshotObjectId max_snapshot_js_object_id () const
bool is_complete () const
bool capture_numeric_value () const
bool expose_internals () const
size_t extra_native_bytes () const
void set_extra_native_bytes (size_t bytes)
void AddLocation (HeapEntry *entry, int scriptId, int line, int col)
HeapEntry * AddEntry (HeapEntry::Type type, const char *name, SnapshotObjectId id, size_t size, unsigned trace_node_id)
void AddSyntheticRootEntries ()
HeapEntry * GetEntryById (SnapshotObjectId id)
void FillChildren ()
void AddScriptLineEnds (int script_id, String::LineEndsVector &&line_ends)
String::LineEndsVector & GetScriptLineEnds (int script_id)
void Print (int max_depth)
Private Types
using ScriptId = int
using ScriptsLineEndsMap = std::unordered_map< ScriptId, String::LineEndsVector >
Private Member Functions
void AddRootEntry ()
void AddGcRootsEntry ()
void AddGcSubrootEntry (Root root, SnapshotObjectId id)
Private Attributes
HeapProfiler * profiler_
HeapEntry * root_entry_ = nullptr
HeapEntry * gc_roots_entry_ = nullptr
HeapEntry * gc_subroot_entries_ [static_cast< int >(Root::kNumberOfRoots)]
std::deque< HeapEntry > entries_
std::deque< HeapGraphEdge > edges_
std::vector< HeapGraphEdge * > children_
std::unordered_map< SnapshotObjectId, HeapEntry * > entries_by_id_cache_
std::vector< EntrySourceLocation > locations_
SnapshotObjectId max_snapshot_js_object_id_ = -1
v8::HeapProfiler::HeapSnapshotMode snapshot_mode_
v8::HeapProfiler::NumericsMode numerics_mode_
size_t extra_native_bytes_ = 0
ScriptsLineEndsMap scripts_line_ends_map_
Detailed Description
Definition at line 223 of file heap-snapshot-generator.h.
Member Typedef Documentation
ScriptId
using v8::internal::HeapSnapshot::ScriptId = int [private]
Definition at line 301 of file heap-snapshot-generator.h.
ScriptsLineEndsMap
using v8::internal::HeapSnapshot::ScriptsLineEndsMap = std::unordered_map<ScriptId, String::LineEndsVector> [private]
Definition at line 302 of file heap-snapshot-generator.h.
Constructor & Destructor Documentation
HeapSnapshot() [1/2]
v8::internal::HeapSnapshot::HeapSnapshot (HeapProfiler * profiler, v8::HeapProfiler::HeapSnapshotMode snapshot_mode, v8::HeapProfiler::NumericsMode numerics_mode)
Definition at line 419 of file heap-snapshot-generator.cc.
    : profiler_(profiler),
      snapshot_mode_(snapshot_mode),
      numerics_mode_(numerics_mode) {
  // It is very important to keep objects that form a heap snapshot
  // as small as possible. Check assumptions about data structure sizes.
  static_assert(kSystemPointerSize != 4 || sizeof(HeapGraphEdge) == 12);
  static_assert(kSystemPointerSize != 8 || sizeof(HeapGraphEdge) == 24);
  static_assert(kSystemPointerSize != 4 || sizeof(HeapEntry) == 32);
#if V8_CC_MSVC
  static_assert(kSystemPointerSize != 8 || sizeof(HeapEntry) == 48);
#else // !V8_CC_MSVC
  static_assert(kSystemPointerSize != 8 || sizeof(HeapEntry) == 40);
#endif // !V8_CC_MSVC
  memset(&gc_subroot_entries_, 0, sizeof(gc_subroot_entries_));
}
References gc_subroot_entries_, and v8::internal::kSystemPointerSize.
HeapSnapshot() [2/2]
v8::internal::HeapSnapshot::HeapSnapshot (const HeapSnapshot &) [delete]
Member Function Documentation
AddEntry()
HeapEntry * v8::internal::HeapSnapshot::AddEntry (HeapEntry::Type type, const char * name, SnapshotObjectId id, size_t size, unsigned trace_node_id)
Definition at line 481 of file heap-snapshot-generator.cc.
                                                          {
  DCHECK(!is_complete());
  entries_.emplace_back(this, static_cast<int>(entries_.size()), type, name, id,
                        size, trace_node_id);
  return &entries_.back();
}
References v8::internal::DCHECK(), entries_, is_complete(), v8::internal::name, size(), and v8::internal::tracing::type.
Referenced by v8::internal::V8HeapExplorer::AddEntry(), AddGcRootsEntry(), AddGcSubrootEntry(), AddRootEntry(), v8::internal::EmbedderGraphEntriesAllocator::AllocateEntry(), v8::internal::V8HeapExplorer::AllocateEntry(), and v8::internal::V8HeapExplorer::ExtractNumberReference().
AddGcRootsEntry()
void v8::internal::HeapSnapshot::AddGcRootsEntry () [private]
Definition at line 464 of file heap-snapshot-generator.cc.
                                   {
  DCHECK_NULL(gc_roots_entry_);
  gc_roots_entry_ = AddEntry(HeapEntry::kSynthetic, "(GC roots)",
                             HeapObjectsMap::kGcRootsObjectId, 0, 0);
}
References AddEntry(), DCHECK_NULL, gc_roots_entry_, v8::internal::HeapObjectsMap::kGcRootsObjectId, and v8::internal::HeapEntry::kSynthetic.
Referenced by AddSyntheticRootEntries().
AddGcSubrootEntry()
void v8::internal::HeapSnapshot::AddGcSubrootEntry (Root root, SnapshotObjectId id) [private]
Definition at line 470 of file heap-snapshot-generator.cc.
                                                                   {
  DCHECK_NULL(gc_subroot_entries_[static_cast<int>(root)]);
  gc_subroot_entries_[static_cast<int>(root)] =
      AddEntry(HeapEntry::kSynthetic, RootVisitor::RootName(root), id, 0, 0);
}
References AddEntry(), DCHECK_NULL, gc_subroot_entries_, v8::internal::HeapEntry::kSynthetic, root(), and v8::internal::RootVisitor::RootName().
Referenced by AddSyntheticRootEntries().
AddLocation()
void v8::internal::HeapSnapshot::AddLocation (HeapEntry * entry, int scriptId, int line, int col)
Definition at line 476 of file heap-snapshot-generator.cc.
                                        {
  locations_.emplace_back(entry->index(), scriptId, line, col);
}
References v8::internal::HeapEntry::index(), and locations_.
Referenced by v8::internal::V8HeapExplorer::ExtractLocationForJSFunction().
AddRootEntry()
void v8::internal::HeapSnapshot::AddRootEntry () [private]
Definition at line 455 of file heap-snapshot-generator.cc.
                                {
  DCHECK_NULL(root_entry_);
  DCHECK(entries_.empty()); // Root entry must be the first one.
  root_entry_ = AddEntry(HeapEntry::kSynthetic, "",
                         HeapObjectsMap::kInternalRootObjectId, 0, 0);
  DCHECK_EQ(1u, entries_.size());
  DCHECK_EQ(root_entry_, &entries_.front());
}
References AddEntry(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NULL, entries_, v8::internal::HeapObjectsMap::kInternalRootObjectId, v8::internal::HeapEntry::kSynthetic, and root_entry_.
Referenced by AddSyntheticRootEntries().
AddScriptLineEnds()
void v8::internal::HeapSnapshot::AddScriptLineEnds (int script_id, String::LineEndsVector && line_ends)
Definition at line 490 of file heap-snapshot-generator.cc.
                                                                       {
  scripts_line_ends_map_.emplace(script_id, std::move(line_ends));
}
References scripts_line_ends_map_.
Referenced by v8::internal::V8HeapExplorer::PopulateLineEnds().
AddSyntheticRootEntries()
void v8::internal::HeapSnapshot::AddSyntheticRootEntries ()
Definition at line 444 of file heap-snapshot-generator.cc.
                                           {
  AddRootEntry();
  AddGcRootsEntry();
  SnapshotObjectId id = HeapObjectsMap::kGcRootsFirstSubrootId;
  for (int root = 0; root < static_cast<int>(Root::kNumberOfRoots); root++) {
    AddGcSubrootEntry(static_cast<Root>(root), id);
    id += HeapObjectsMap::kObjectIdStep;
  }
  DCHECK_EQ(HeapObjectsMap::kFirstAvailableObjectId, id);
}
References AddGcRootsEntry(), AddGcSubrootEntry(), AddRootEntry(), DCHECK_EQ, v8::internal::HeapObjectsMap::kFirstAvailableObjectId, v8::internal::HeapObjectsMap::kGcRootsFirstSubrootId, v8::internal::kNumberOfRoots, v8::internal::HeapObjectsMap::kObjectIdStep, and root().
Referenced by v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), and v8::internal::HeapSnapshotGenerator::GenerateSnapshotAfterGC().
capture_numeric_value()
bool v8::internal::HeapSnapshot::capture_numeric_value () const [inline]
Definition at line 251 of file heap-snapshot-generator.h.
                                     {
    return numerics_mode_ ==
           v8::HeapProfiler::NumericsMode::kExposeNumericValues;
  }
References v8::HeapProfiler::kExposeNumericValues, and numerics_mode_.
Referenced by v8::internal::V8HeapExplorer::ExtractPropertyReferences(), v8::internal::V8HeapExplorer::ExtractReferences(), and v8::internal::V8HeapExplorer::GetEntry().
children()
std::vector<HeapGraphEdge*>& v8::internal::HeapSnapshot::children () [inline]
Definition at line 242 of file heap-snapshot-generator.h.
{ return children_; }
References children_.
Referenced by v8::internal::HeapEntry::add_child(), v8::internal::HeapEntry::children_begin(), v8::internal::HeapEntry::children_end(), FillChildren(), and v8::internal::HeapSnapshotJSONSerializer::SerializeEdges().
Delete()
void v8::internal::HeapSnapshot::Delete ()
Definition at line 438 of file heap-snapshot-generator.cc.
{ profiler_->RemoveSnapshot(this); }
References profiler_, and v8::internal::HeapProfiler::RemoveSnapshot().
edges() [1/2]
std::deque<HeapGraphEdge>& v8::internal::HeapSnapshot::edges () [inline]
Definition at line 240 of file heap-snapshot-generator.h.
{ return edges_; }
References edges_.
Referenced by FillChildren(), v8::internal::HeapSnapshotJSONSerializer::SerializeSnapshot(), v8::internal::HeapEntry::SetIndexedReference(), and v8::internal::HeapEntry::SetNamedReference().
edges() [2/2]
const std::deque<HeapGraphEdge>& v8::internal::HeapSnapshot::edges () const [inline]
Definition at line 241 of file heap-snapshot-generator.h.
{ return edges_; }
References edges_.
entries() [1/2]
std::deque<HeapEntry>& v8::internal::HeapSnapshot::entries () [inline]
Definition at line 238 of file heap-snapshot-generator.h.
{ return entries_; }
References entries_.
Referenced by v8::internal::HeapEntry::children_begin(), FillChildren(), v8::internal::HeapGraphEdge::from(), v8::internal::HeapSnapshotJSONSerializer::SerializeNodes(), and v8::internal::HeapSnapshotJSONSerializer::SerializeSnapshot().
entries() [2/2]
const std::deque<HeapEntry>& v8::internal::HeapSnapshot::entries () const [inline]
Definition at line 239 of file heap-snapshot-generator.h.
{ return entries_; }
References entries_.
expose_internals()
bool v8::internal::HeapSnapshot::expose_internals () const [inline]
Definition at line 255 of file heap-snapshot-generator.h.
                                {
    return snapshot_mode_ ==
           v8::HeapProfiler::HeapSnapshotMode::kExposeInternals;
  }
References v8::HeapProfiler::kExposeInternals, and snapshot_mode_.
Referenced by v8::internal::V8HeapExplorer::SetGcSubrootReference().
extra_native_bytes()
size_t v8::internal::HeapSnapshot::extra_native_bytes () const [inline]
Definition at line 259 of file heap-snapshot-generator.h.
{ return extra_native_bytes_; }
References extra_native_bytes_.
Referenced by v8::internal::HeapSnapshotJSONSerializer::SerializeSnapshot().
FillChildren()
void v8::internal::HeapSnapshot::FillChildren ()
Definition at line 501 of file heap-snapshot-generator.cc.
                                {
  DCHECK(children().empty());
  int children_index = 0;
  for (HeapEntry& entry : entries()) {
    children_index = entry.set_children_index(children_index);
  }
  DCHECK_EQ(edges().size(), static_cast<size_t>(children_index));
  children().resize(edges().size());
  for (HeapGraphEdge& edge : edges()) {
    edge.from()->add_child(&edge);
  }
}
References children(), v8::internal::DCHECK(), DCHECK_EQ, edges(), entries(), and size().
Referenced by v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), and v8::internal::HeapSnapshotGenerator::GenerateSnapshotAfterGC().
gc_roots()
HeapEntry* v8::internal::HeapSnapshot::gc_roots () const [inline]
Definition at line 234 of file heap-snapshot-generator.h.
{ return gc_roots_entry_; }
References gc_roots_entry_.
Referenced by v8::internal::V8HeapExplorer::SetGcRootsReference(), and v8::internal::V8HeapExplorer::SetRootGcRootsReference().
gc_subroot()
HeapEntry* v8::internal::HeapSnapshot::gc_subroot (Root root) const [inline]
Definition at line 235 of file heap-snapshot-generator.h.
                                         {
    return gc_subroot_entries_[static_cast<int>(root)];
  }
References gc_subroot_entries_, and root().
Referenced by v8::internal::V8HeapExplorer::SetGcRootsReference(), and v8::internal::V8HeapExplorer::SetGcSubrootReference().
GetEntryById()
HeapEntry * v8::internal::HeapSnapshot::GetEntryById (SnapshotObjectId id)
Definition at line 514 of file heap-snapshot-generator.cc.
                                                         {
  if (entries_by_id_cache_.empty()) {
    CHECK(is_complete());
    entries_by_id_cache_.reserve(entries_.size());
    for (HeapEntry& entry : entries_) {
      entries_by_id_cache_.emplace(entry.id(), &entry);
    }
  }
  auto it = entries_by_id_cache_.find(id);
  return it != entries_by_id_cache_.end() ? it->second : nullptr;
}
References CHECK, entries_, entries_by_id_cache_, and is_complete().
GetScriptLineEnds()
String::LineEndsVector & v8::internal::HeapSnapshot::GetScriptLineEnds (int script_id)
Definition at line 495 of file heap-snapshot-generator.cc.
                                                                   {
  DCHECK(scripts_line_ends_map_.find(script_id) !=
         scripts_line_ends_map_.end());
  return scripts_line_ends_map_[script_id];
}
References v8::internal::DCHECK(), and scripts_line_ends_map_.
Referenced by v8::internal::V8HeapExplorer::ExtractLocationForJSFunction().
is_complete()
bool v8::internal::HeapSnapshot::is_complete () const [inline]
Definition at line 250 of file heap-snapshot-generator.h.
{ return !children_.empty(); }
References children_.
Referenced by AddEntry(), and GetEntryById().
locations()
const std::vector<EntrySourceLocation>& v8::internal::HeapSnapshot::locations () const [inline]
Definition at line 243 of file heap-snapshot-generator.h.
                                                          {
    return locations_;
  }
References locations_.
Referenced by v8::internal::HeapSnapshotJSONSerializer::SerializeLocations().
max_snapshot_js_object_id()
SnapshotObjectId v8::internal::HeapSnapshot::max_snapshot_js_object_id () const [inline]
Definition at line 247 of file heap-snapshot-generator.h.
                                                     {
    return max_snapshot_js_object_id_;
  }
References max_snapshot_js_object_id_.
operator=()
HeapSnapshot& v8::internal::HeapSnapshot::operator= (const HeapSnapshot &) [delete]
Print()
void v8::internal::HeapSnapshot::Print (int max_depth)
Definition at line 526 of file heap-snapshot-generator.cc.
{ root()->Print("", "", max_depth, 0); }
References v8::internal::HeapEntry::Print(), and root().
profiler()
HeapProfiler* v8::internal::HeapSnapshot::profiler () const [inline]
Definition at line 232 of file heap-snapshot-generator.h.
{ return profiler_; }
References profiler_.
Referenced by v8::internal::V8HeapExplorer::AddEntry(), v8::internal::HeapEntry::isolate(), v8::internal::NativeObjectsExplorer::IterateAndExtractReferences(), v8::internal::HeapSnapshotJSONSerializer::Serialize(), v8::internal::HeapSnapshotJSONSerializer::SerializeSamples(), v8::internal::HeapSnapshotJSONSerializer::SerializeTraceNodeInfos(), and v8::internal::HeapSnapshotJSONSerializer::SerializeTraceTree().
RememberLastJSObjectId()
void v8::internal::HeapSnapshot::RememberLastJSObjectId ()
Definition at line 440 of file heap-snapshot-generator.cc.
                                          {
  max_snapshot_js_object_id_ = profiler_->heap_object_map()->last_assigned_id();
}
References v8::internal::HeapProfiler::heap_object_map(), v8::internal::HeapObjectsMap::last_assigned_id(), max_snapshot_js_object_id_, and profiler_.
Referenced by v8::internal::HeapSnapshotGenerator::GenerateSnapshot(), and v8::internal::HeapSnapshotGenerator::GenerateSnapshotAfterGC().
root()
HeapEntry* v8::internal::HeapSnapshot::root () const [inline]
Definition at line 233 of file heap-snapshot-generator.h.
{ return root_entry_; }
References root_entry_.
Referenced by AddGcSubrootEntry(), AddSyntheticRootEntries(), gc_subroot(), v8::internal::NativeObjectsExplorer::IterateAndExtractReferences(), Print(), v8::internal::HeapSnapshotJSONSerializer::SerializeImpl(), v8::internal::V8HeapExplorer::SetRootGcRootsReference(), and v8::internal::V8HeapExplorer::SetUserGlobalReference().
set_extra_native_bytes()
void v8::internal::HeapSnapshot::set_extra_native_bytes (size_t bytes) [inline]
Definition at line 260 of file heap-snapshot-generator.h.
{ extra_native_bytes_ = bytes; }
References extra_native_bytes_.
Referenced by v8::internal::NativeObjectsExplorer::IterateAndExtractReferences().
Member Data Documentation
children_
std::vector<HeapGraphEdge*> v8::internal::HeapSnapshot::children_ [private]
Definition at line 291 of file heap-snapshot-generator.h.
Referenced by children(), and is_complete().
edges_
std::deque<HeapGraphEdge> v8::internal::HeapSnapshot::edges_ [private]
Definition at line 290 of file heap-snapshot-generator.h.
Referenced by edges().
entries_
std::deque<HeapEntry> v8::internal::HeapSnapshot::entries_ [private]
Definition at line 289 of file heap-snapshot-generator.h.
Referenced by AddEntry(), AddRootEntry(), entries(), and GetEntryById().
entries_by_id_cache_
std::unordered_map<SnapshotObjectId, HeapEntry*> v8::internal::HeapSnapshot::entries_by_id_cache_ [private]
Definition at line 292 of file heap-snapshot-generator.h.
Referenced by GetEntryById().
extra_native_bytes_
size_t v8::internal::HeapSnapshot::extra_native_bytes_ = 0 [private]
Definition at line 297 of file heap-snapshot-generator.h.
Referenced by extra_native_bytes(), and set_extra_native_bytes().
gc_roots_entry_
HeapEntry* v8::internal::HeapSnapshot::gc_roots_entry_ = nullptr [private]
Definition at line 284 of file heap-snapshot-generator.h.
Referenced by AddGcRootsEntry(), and gc_roots().
gc_subroot_entries_
HeapEntry* v8::internal::HeapSnapshot::gc_subroot_entries_[static_cast< int >(Root::kNumberOfRoots)] [private]
Definition at line 285 of file heap-snapshot-generator.h.
Referenced by AddGcSubrootEntry(), gc_subroot(), and HeapSnapshot().
locations_
std::vector<EntrySourceLocation> v8::internal::HeapSnapshot::locations_ [private]
Definition at line 293 of file heap-snapshot-generator.h.
Referenced by AddLocation(), and locations().
max_snapshot_js_object_id_
SnapshotObjectId v8::internal::HeapSnapshot::max_snapshot_js_object_id_ = -1 [private]
Definition at line 294 of file heap-snapshot-generator.h.
Referenced by max_snapshot_js_object_id(), and RememberLastJSObjectId().
numerics_mode_
v8::HeapProfiler::NumericsMode v8::internal::HeapSnapshot::numerics_mode_ [private]
Definition at line 296 of file heap-snapshot-generator.h.
Referenced by capture_numeric_value().
profiler_
HeapProfiler* v8::internal::HeapSnapshot::profiler_ [private]
Definition at line 282 of file heap-snapshot-generator.h.
Referenced by Delete(), profiler(), and RememberLastJSObjectId().
root_entry_
HeapEntry* v8::internal::HeapSnapshot::root_entry_ = nullptr [private]
Definition at line 283 of file heap-snapshot-generator.h.
Referenced by AddRootEntry(), and root().
scripts_line_ends_map_
ScriptsLineEndsMap v8::internal::HeapSnapshot::scripts_line_ends_map_ [private]
Definition at line 304 of file heap-snapshot-generator.h.
Referenced by AddScriptLineEnds(), and GetScriptLineEnds().
snapshot_mode_
v8::HeapProfiler::HeapSnapshotMode v8::internal::HeapSnapshot::snapshot_mode_ [private]
Definition at line 295 of file heap-snapshot-generator.h.
Referenced by expose_internals().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.h
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc