v8::internal::compiler::JSDefineNamedOwnPropertyNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSDefineNamedOwnPropertyNode (Node *node)
const DefineNamedOwnPropertyParameters & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1612 of file js-operator.h.
Constructor & Destructor Documentation
JSDefineNamedOwnPropertyNode()
constexpr v8::internal::compiler::JSDefineNamedOwnPropertyNode::JSDefineNamedOwnPropertyNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1614 of file js-operator.h.
      : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSDefineNamedOwnProperty, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const DefineNamedOwnPropertyParameters& v8::internal::compiler::JSDefineNamedOwnPropertyNode::Parameters () const [inline]
Definition at line 1619 of file js-operator.h.
                                                             {
    return DefineNamedOwnPropertyParametersOf(node()->op());
  }
References v8::internal::compiler::DefineNamedOwnPropertyParametersOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineNamedOwnProperty().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h