v8_inspector::InjectedScript::Scope Class Reference
#include <injected-script.h>
Public Member Functions
Response initialize ()
void installCommandLineAPI ()
void ignoreExceptionsAndMuteConsole ()
void pretendUserGesture ()
void allowCodeGenerationFromStrings ()
void setTryCatchVerbose ()
v8::Local< v8::Context > context () const
InjectedScript * injectedScript () const
const v8::TryCatch & tryCatch () const
V8InspectorImpl * inspector () const
Protected Member Functions
Scope (V8InspectorSessionImpl *)
virtual ~Scope ()
virtual Response findInjectedScript (V8InspectorSessionImpl *)=0
Protected Attributes
V8InspectorImpl * m_inspector
InjectedScript * m_injectedScript
Private Member Functions
void cleanup ()
v8::debug::ExceptionBreakState setPauseOnExceptionsState (v8::debug::ExceptionBreakState)
Private Attributes
v8::HandleScope m_handleScope
v8::TryCatch m_tryCatch
v8::Local< v8::Context > m_context
std::unique_ptr< V8Console::CommandLineAPIScope > m_commandLineAPIScope
bool m_ignoreExceptionsAndMuteConsole
v8::debug::ExceptionBreakState m_previousPauseOnExceptionsState
bool m_userGesture
bool m_allowEval
int m_contextGroupId
int m_sessionId
Detailed Description
Definition at line 153 of file injected-script.h.
Constructor & Destructor Documentation
Scope()
v8_inspector::InjectedScript::Scope::Scope (V8InspectorSessionImpl * session) [explicit], [protected]
Definition at line 1002 of file injected-script.cc.
    : m_inspector(session->inspector()),
      m_injectedScript(nullptr),
      m_handleScope(m_inspector->isolate()),
      m_tryCatch(m_inspector->isolate()),
      m_ignoreExceptionsAndMuteConsole(false),
      m_previousPauseOnExceptionsState(v8::debug::NoBreakOnException),
      m_userGesture(false),
      m_allowEval(false),
      m_contextGroupId(session->contextGroupId()),
      m_sessionId(session->sessionId()) {}
 Scope()
v8_inspector::InjectedScript::Scope::~Scope () [protected], [virtual]
Definition at line 1084 of file injected-script.cc.
                            {
  if (m_ignoreExceptionsAndMuteConsole) {
    setPauseOnExceptionsState(m_previousPauseOnExceptionsState);
    m_inspector->client()->unmuteMetrics(m_contextGroupId);
    m_inspector->unmuteExceptions(m_contextGroupId);
  }
  if (m_userGesture) m_inspector->client()->endUserGesture();
  cleanup();
}
Member Function Documentation
allowCodeGenerationFromStrings()
void v8_inspector::InjectedScript::Scope::allowCodeGenerationFromStrings ()
Definition at line 1064 of file injected-script.cc.
                                                         {
  DCHECK(!m_allowEval);
  if (m_context->IsCodeGenerationFromStringsAllowed()) return;
  m_allowEval = true;
  m_context->AllowCodeGenerationFromStrings(true);
}
References DCHECK, and v8_inspector::InjectedScript::m_context.
Referenced by v8_inspector::V8RuntimeAgentImpl::evaluate(), v8_inspector::V8InspectorSessionImpl::evaluate(), and v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn().
cleanup()
void v8_inspector::InjectedScript::Scope::cleanup () [private]
Definition at line 1075 of file injected-script.cc.
                                  {
  m_commandLineAPIScope.reset();
  if (!m_context.IsEmpty()) {
    if (m_allowEval) m_context->AllowCodeGenerationFromStrings(false);
    m_context->Exit();
    m_context.Clear();
  }
}
References v8_inspector::InjectedScript::m_context.
context()
v8::Local<v8::Context> v8_inspector::InjectedScript::Scope::context () const [inline]
Definition at line 161 of file injected-script.h.
{ return m_context; }
References m_context.
Referenced by v8_inspector::V8RuntimeAgentImpl::callFunctionOn(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::V8RuntimeAgentImpl::compileScript(), v8_inspector::V8RuntimeAgentImpl::evaluate(), v8_inspector::V8InspectorSessionImpl::evaluate(), v8_inspector::V8RuntimeAgentImpl::getProperties(), v8_inspector::V8RuntimeAgentImpl::globalLexicalScopeNames(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8_inspector::V8RuntimeAgentImpl::queryObjects(), v8_inspector::V8RuntimeAgentImpl::runScript(), and v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback().
findInjectedScript()
virtual Response v8_inspector::InjectedScript::Scope::findInjectedScript (V8InspectorSessionImpl *) [protected], [pure virtual]
Implemented in v8_inspector::InjectedScript::CallFrameScope, v8_inspector::InjectedScript::ObjectScope, and v8_inspector::InjectedScript::ContextScope.
ignoreExceptionsAndMuteConsole()
void v8_inspector::InjectedScript::Scope::ignoreExceptionsAndMuteConsole ()
Definition at line 1039 of file injected-script.cc.
                                                         {
  DCHECK(!m_ignoreExceptionsAndMuteConsole);
  m_ignoreExceptionsAndMuteConsole = true;
  m_inspector->client()->muteMetrics(m_contextGroupId);
  m_inspector->muteExceptions(m_contextGroupId);
  m_previousPauseOnExceptionsState =
      setPauseOnExceptionsState(v8::debug::NoBreakOnException);
}
References DCHECK, and v8::debug::NoBreakOnException.
Referenced by v8_inspector::V8RuntimeAgentImpl::evaluate(), v8_inspector::V8DebuggerAgentImpl::evaluateOnCallFrame(), v8_inspector::V8RuntimeAgentImpl::getProperties(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), and v8_inspector::V8RuntimeAgentImpl::runScript().
initialize()
Response v8_inspector::InjectedScript::Scope::initialize ()
Definition at line 1014 of file injected-script.cc.
                                         {
  cleanup();
  V8InspectorSessionImpl* session =
      m_inspector->sessionById(m_contextGroupId, m_sessionId);
  if (!session) return Response::InternalError();
  Response response = findInjectedScript(session);
  if (!response.IsSuccess()) return response;
  m_context = m_injectedScript->context()->context();
  m_context->Enter();
  if (m_allowEval) m_context->AllowCodeGenerationFromStrings(true);
  return Response::Success();
}
References v8_inspector::InspectedContext::context(), v8_inspector::InjectedScript::m_context, and v8_inspector::InjectedScript::m_sessionId.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::add(), v8_inspector::V8RuntimeAgentImpl::awaitPromise(), v8_inspector::V8RuntimeAgentImpl::callFunctionOn(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::V8RuntimeAgentImpl::compileScript(), v8_inspector::V8RuntimeAgentImpl::evaluate(), v8_inspector::V8InspectorSessionImpl::evaluate(), v8_inspector::V8DebuggerAgentImpl::evaluateOnCallFrame(), v8_inspector::V8RuntimeAgentImpl::getExceptionDetails(), v8_inspector::V8RuntimeAgentImpl::getProperties(), v8_inspector::V8RuntimeAgentImpl::globalLexicalScopeNames(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8_inspector::V8RuntimeAgentImpl::queryObjects(), v8_inspector::V8RuntimeAgentImpl::releaseObject(), v8_inspector::V8DebuggerAgentImpl::restartFrame(), v8_inspector::V8RuntimeAgentImpl::runScript(), v8_inspector::PromiseHandlerTracker::sendFailure(), v8_inspector::V8DebuggerAgentImpl::setBreakpointOnFunctionCall(), v8_inspector::V8DebuggerAgentImpl::setReturnValue(), v8_inspector::V8DebuggerAgentImpl::setVariableValue(), and v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback().
injectedScript()
InjectedScript* v8_inspector::InjectedScript::Scope::injectedScript () const [inline]
Definition at line 162 of file injected-script.h.
{ return m_injectedScript; }
References m_injectedScript.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::add(), v8_inspector::V8RuntimeAgentImpl::awaitPromise(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::V8RuntimeAgentImpl::compileScript(), v8_inspector::V8RuntimeAgentImpl::evaluate(), v8_inspector::V8DebuggerAgentImpl::evaluateOnCallFrame(), v8_inspector::V8RuntimeAgentImpl::getExceptionDetails(), v8_inspector::V8RuntimeAgentImpl::getProperties(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8_inspector::V8RuntimeAgentImpl::queryObjects(), v8_inspector::V8RuntimeAgentImpl::releaseObject(), v8_inspector::V8RuntimeAgentImpl::runScript(), v8_inspector::PromiseHandlerTracker::sendFailure(), v8_inspector::V8DebuggerAgentImpl::setReturnValue(), v8_inspector::V8DebuggerAgentImpl::setVariableValue(), and v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback().
inspector()
V8InspectorImpl* v8_inspector::InjectedScript::Scope::inspector () const [inline]
Definition at line 164 of file injected-script.h.
{ return m_inspector; }
References m_inspector.
installCommandLineAPI()
void v8_inspector::InjectedScript::Scope::installCommandLineAPI ()
Definition at line 1027 of file injected-script.cc.
                                                {
  DCHECK(m_injectedScript && !m_context.IsEmpty() &&
         !m_commandLineAPIScope.get());
  V8InspectorSessionImpl* session =
      m_inspector->sessionById(m_contextGroupId, m_sessionId);
  if (session->clientTrustLevel() != V8Inspector::kFullyTrusted) {
    return;
  }
  m_commandLineAPIScope.reset(new V8Console::CommandLineAPIScope(
      m_context, m_injectedScript->commandLineAPI(), m_context->Global()));
}
References v8_inspector::V8InspectorSessionImpl::clientTrustLevel(), DCHECK, v8_inspector::V8Inspector::kFullyTrusted, v8_inspector::InjectedScript::m_context, v8_inspector::InjectedScript::m_sessionId, and v8_inspector::V8InspectorSessionImpl::reset().
Referenced by v8_inspector::V8RuntimeAgentImpl::evaluate(), v8_inspector::V8InspectorSessionImpl::evaluate(), v8_inspector::V8DebuggerAgentImpl::evaluateOnCallFrame(), and v8_inspector::V8RuntimeAgentImpl::runScript().
pretendUserGesture()
void v8_inspector::InjectedScript::Scope::pretendUserGesture ()
Definition at line 1058 of file injected-script.cc.
                                             {
  DCHECK(!m_userGesture);
  m_userGesture = true;
  m_inspector->client()->beginUserGesture();
}
References DCHECK.
Referenced by v8_inspector::V8RuntimeAgentImpl::evaluate(), and v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn().
setPauseOnExceptionsState()
v8::debug::ExceptionBreakState v8_inspector::InjectedScript::Scope::setPauseOnExceptionsState (v8::debug::ExceptionBreakState newState) [private]
Definition at line 1048 of file injected-script.cc.
                                         {
  if (!m_inspector->debugger()->enabled()) return newState;
  v8::debug::ExceptionBreakState presentState =
      m_inspector->debugger()->getPauseOnExceptionsState();
  if (presentState != newState)
    m_inspector->debugger()->setPauseOnExceptionsState(newState);
  return presentState;
}
setTryCatchVerbose()
void v8_inspector::InjectedScript::Scope::setTryCatchVerbose ()
Definition at line 1071 of file injected-script.cc.
                                             {
  m_tryCatch.SetVerbose(true);
}
Referenced by v8_inspector::V8InspectorSessionImpl::evaluate().
tryCatch()
const v8::TryCatch& v8_inspector::InjectedScript::Scope::tryCatch () const [inline]
Definition at line 163 of file injected-script.h.
{ return m_tryCatch; }
References m_tryCatch.
Referenced by v8_inspector::V8RuntimeAgentImpl::compileScript(), v8_inspector::V8RuntimeAgentImpl::evaluate(), v8_inspector::V8InspectorSessionImpl::evaluate(), v8_inspector::V8DebuggerAgentImpl::evaluateOnCallFrame(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8_inspector::V8RuntimeAgentImpl::runScript(), and v8_inspector::V8DebuggerAgentImpl::setVariableValue().
Member Data Documentation
m_allowEval
bool v8_inspector::InjectedScript::Scope::m_allowEval [private]
Definition at line 186 of file injected-script.h.
m_commandLineAPIScope
std::unique_ptr<V8Console::CommandLineAPIScope> v8_inspector::InjectedScript::Scope::m_commandLineAPIScope [private]
Definition at line 182 of file injected-script.h.
m_context
v8::Local<v8::Context> v8_inspector::InjectedScript::Scope::m_context [private]
Definition at line 181 of file injected-script.h.
Referenced by context().
m_contextGroupId
int v8_inspector::InjectedScript::Scope::m_contextGroupId [private]
Definition at line 187 of file injected-script.h.
m_handleScope
v8::HandleScope v8_inspector::InjectedScript::Scope::m_handleScope [private]
Definition at line 179 of file injected-script.h.
m_ignoreExceptionsAndMuteConsole
bool v8_inspector::InjectedScript::Scope::m_ignoreExceptionsAndMuteConsole [private]
Definition at line 183 of file injected-script.h.
m_injectedScript
InjectedScript* v8_inspector::InjectedScript::Scope::m_injectedScript [protected]
Definition at line 172 of file injected-script.h.
Referenced by injectedScript().
m_inspector
V8InspectorImpl* v8_inspector::InjectedScript::Scope::m_inspector [protected]
Definition at line 171 of file injected-script.h.
Referenced by inspector().
m_previousPauseOnExceptionsState
v8::debug::ExceptionBreakState v8_inspector::InjectedScript::Scope::m_previousPauseOnExceptionsState [private]
Definition at line 184 of file injected-script.h.
m_sessionId
int v8_inspector::InjectedScript::Scope::m_sessionId [private]
Definition at line 188 of file injected-script.h.
m_tryCatch
v8::TryCatch v8_inspector::InjectedScript::Scope::m_tryCatch [private]
Definition at line 180 of file injected-script.h.
Referenced by tryCatch().
m_userGesture
bool v8_inspector::InjectedScript::Scope::m_userGesture [private]
Definition at line 185 of file injected-script.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/injected-script.h
/mnt/V8SourceCode/src/inspector/injected-script.cc