v8::base::FPU Class Reference
#include <fpu.h>
Static Public Member Functions
static V8_BASE_EXPORT bool GetFlushDenormals ()
static V8_BASE_EXPORT void SetFlushDenormals (bool)
Detailed Description
Definition at line 11 of file fpu.h.
Member Function Documentation
GetFlushDenormals()
bool v8::base::FPU::GetFlushDenormals () [static]
Definition at line 96 of file fpu.cc.
{ return false; }
Referenced by v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::internal::DoubleToRadixStringView(), v8::internal::Isolate::Init(), v8::internal::LocalIsolate::LocalIsolate(), and v8::Shell::WorkerNew().
SetFlushDenormals()
void v8::base::FPU::SetFlushDenormals (bool value) [static]
Definition at line 97 of file fpu.cc.
{}
Referenced by v8::base::FlushDenormalsScope::FlushDenormalsScope(), v8::Shell::SetFlushDenormals(), v8::base::ThreadEntry(), and v8::base::FlushDenormalsScope::~FlushDenormalsScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/fpu.h
/mnt/V8SourceCode/src/base/fpu.cc