v8::internal::maglev::AbstractLoadTaggedField< Derived > Class Template Reference
#include <maglev-ir.h>
Public Member Functions
AbstractLoadTaggedField (uint64_t bitfield, const int offset)
int offset () const
Input & object_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::CanRead()
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
static constexpr int kObjectIndex = 0
Private Types
using Base = FixedInputValueNodeT< 1, Derived >
Private Attributes
const int offset_
Additional Inherited Members
Detailed Description
template<typename Derived = LoadTaggedField>
class v8::internal::maglev::AbstractLoadTaggedField< Derived >
Definition at line 8106 of file maglev-ir.h.
Member Typedef Documentation
Base
template<typename Derived = LoadTaggedField>
using v8::internal::maglev::AbstractLoadTaggedField< Derived >::Base = FixedInputValueNodeT<1, Derived> [private]
Definition at line 8107 of file maglev-ir.h.
Constructor & Destructor Documentation
AbstractLoadTaggedField()
template<typename Derived = LoadTaggedField>
v8::internal::maglev::AbstractLoadTaggedField< Derived >::AbstractLoadTaggedField (uint64_t bitfield, const int offset) [inline], [explicit]
Definition at line 8111 of file maglev-ir.h.
      : Base(bitfield), offset_(offset) {}
Member Function Documentation
GenerateCode()
template<typename Derived = LoadTaggedField>
void v8::internal::maglev::AbstractLoadTaggedField< Derived >::GenerateCode (MaglevAssembler * , const ProcessingState &)
object_input()
template<typename Derived = LoadTaggedField>
Input& v8::internal::maglev::AbstractLoadTaggedField< Derived >::object_input () [inline]
Definition at line 8122 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::maglev::LoopOptimizationProcessor::Process(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
offset()
template<typename Derived = LoadTaggedField>
int v8::internal::maglev::AbstractLoadTaggedField< Derived >::offset () const [inline]
Definition at line 8118 of file maglev-ir.h.
{ return offset_; }
Referenced by v8::internal::maglev::LoopOptimizationProcessor::Process(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and v8::internal::maglev::KnownNodeAspects::UpdateMayHaveAliasingContexts().
options()
template<typename Derived = LoadTaggedField>
auto v8::internal::maglev::AbstractLoadTaggedField< Derived >::options () const [inline]
Definition at line 8128 of file maglev-ir.h.
{ return std::tuple{offset()}; }
PrintParams()
template<typename T >
void v8::internal::maglev::AbstractLoadTaggedField< T >::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8171 of file maglev-ir.cc.
                                                               {
  os << "(0x" << std::hex << offset() << std::dec;
  // Print compression status only after the result is allocated, since that's
  // when we do decompression marking.
  if (!result().operand().IsUnallocated()) {
    if (decompresses_tagged_result()) {
      os << ", decompressed";
    } else {
      os << ", compressed";
    }
  }
  os << ")";
}
References v8::base::internal::result.
SetValueLocationConstraints()
template<typename Derived = LoadTaggedField>
void v8::internal::maglev::AbstractLoadTaggedField< Derived >::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
template<typename Derived = LoadTaggedField>
constexpr Base::InputTypes v8::internal::maglev::AbstractLoadTaggedField< Derived >::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 8116 of file maglev-ir.h.
kObjectIndex
template<typename Derived = LoadTaggedField>
constexpr int v8::internal::maglev::AbstractLoadTaggedField< Derived >::kObjectIndex = 0 [static], [constexpr]
Definition at line 8121 of file maglev-ir.h.
kProperties
template<typename Derived = LoadTaggedField>
constexpr OpProperties v8::internal::maglev::AbstractLoadTaggedField< Derived >::kProperties = OpProperties::CanRead() [static], [constexpr]
Definition at line 8114 of file maglev-ir.h.
offset_
template<typename Derived = LoadTaggedField>
const int v8::internal::maglev::AbstractLoadTaggedField< Derived >::offset_ [private]
Definition at line 8133 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc