v8::internal::compiler::LinearScanAllocator Class Reference
#include <register-allocator.h>
Classes
struct InactiveLiveRangeOrdering
struct UnhandledLiveRangeOrdering
Public Member Functions
LinearScanAllocator (RegisterAllocationData *data, RegisterKind kind, Zone *local_zone)
LinearScanAllocator (const LinearScanAllocator &)=delete
LinearScanAllocator & operator= (const LinearScanAllocator &)=delete
void AllocateRegisters ()
Private Types
using UnhandledLiveRangeQueue = ZoneMultiset< LiveRange *, UnhandledLiveRangeOrdering >
using InactiveLiveRangeQueue = ZoneVector< LiveRange * >
Private Member Functions
void MaybeSpillPreviousRanges (LiveRange *begin_range, LifetimePosition begin_pos, LiveRange *end_range)
void MaybeUndoPreviousSplit (LiveRange *range, Zone *zone)
void SpillNotLiveRanges (RangeRegisterSmallMap &to_be_live, LifetimePosition position, SpillMode spill_mode)
LiveRange * AssignRegisterOnReload (LiveRange *range, int reg)
void ReloadLiveRanges (RangeRegisterSmallMap const &to_be_live, LifetimePosition position)
void UpdateDeferredFixedRanges (SpillMode spill_mode, InstructionBlock *block)
bool BlockIsDeferredOrImmediatePredecessorIsNotDeferred (const InstructionBlock *block)
bool HasNonDeferredPredecessor (InstructionBlock *block)
UnhandledLiveRangeQueue & unhandled_live_ranges ()
ZoneVector< LiveRange * > & active_live_ranges ()
InactiveLiveRangeQueue & inactive_live_ranges (int reg)
void SlowDCheckInactiveLiveRangesIsSorted (int reg)
void SetLiveRangeAssignedRegister (LiveRange *range, int reg)
void AddToActive (LiveRange *range)
void AddToInactive (LiveRange *range)
void AddToUnhandled (LiveRange *range)
ZoneVector< LiveRange * >::iterator ActiveToHandled (ZoneVector< LiveRange * >::iterator it)
ZoneVector< LiveRange * >::iterator ActiveToInactive (ZoneVector< LiveRange * >::iterator it, LifetimePosition position)
InactiveLiveRangeQueue::iterator InactiveToHandled (InactiveLiveRangeQueue::iterator it)
InactiveLiveRangeQueue::iterator InactiveToActive (InactiveLiveRangeQueue::iterator it, LifetimePosition position)
void ForwardStateTo (LifetimePosition position)
int LastDeferredInstructionIndex (InstructionBlock *start)
bool ConsiderBlockForControlFlow (InstructionBlock *current_block, RpoNumber predecessor)
RpoNumber ChooseOneOfTwoPredecessorStates (InstructionBlock *current_block, LifetimePosition boundary)
bool CheckConflict (MachineRepresentation rep, int reg, const RangeRegisterSmallMap &to_be_live)
void ComputeStateFromManyPredecessors (InstructionBlock *current_block, RangeRegisterSmallMap &to_be_live)
bool TryReuseSpillForPhi (TopLevelLiveRange *range)
int PickRegisterThatIsAvailableLongest (LiveRange *current, int hint_reg, base::Vector< const LifetimePosition > free_until_pos)
bool TryAllocateFreeReg (LiveRange *range, base::Vector< const LifetimePosition > free_until_pos)
bool TryAllocatePreferredReg (LiveRange *range, base::Vector< const LifetimePosition > free_until_pos)
void GetFPRegisterSet (MachineRepresentation rep, int *num_regs, int *num_codes, const int **codes) const
void GetSIMD128RegisterSet (int *num_regs, int *num_codes, const int **codes) const
void FindFreeRegistersForRange (LiveRange *range, base::Vector< LifetimePosition > free_until_pos)
void ProcessCurrentRange (LiveRange *current, SpillMode spill_mode)
void AllocateBlockedReg (LiveRange *range, SpillMode spill_mode)
void SpillAfter (LiveRange *range, LifetimePosition pos, SpillMode spill_mode)
void SpillBetween (LiveRange *range, LifetimePosition start, LifetimePosition end, SpillMode spill_mode)
void SpillBetweenUntil (LiveRange *range, LifetimePosition start, LifetimePosition until, LifetimePosition end, SpillMode spill_mode)
void SplitAndSpillIntersecting (LiveRange *range, SpillMode spill_mode)
void PrintRangeRow (std::ostream &os, const TopLevelLiveRange *toplevel)
void PrintRangeOverview ()
Private Attributes
UnhandledLiveRangeQueue unhandled_live_ranges_
ZoneVector< LiveRange * > active_live_ranges_
ZoneVector< InactiveLiveRangeQueue > inactive_live_ranges_
LifetimePosition next_active_ranges_change_
LifetimePosition next_inactive_ranges_change_
Additional Inherited Members
Detailed Description
Definition at line 1545 of file register-allocator.h.
Member Typedef Documentation
InactiveLiveRangeQueue
using v8::internal::compiler::LinearScanAllocator::InactiveLiveRangeQueue = ZoneVector<LiveRange*> [private]
Definition at line 1591 of file register-allocator.h.
UnhandledLiveRangeQueue
using v8::internal::compiler::LinearScanAllocator::UnhandledLiveRangeQueue = ZoneMultiset<LiveRange*, UnhandledLiveRangeOrdering> [private]
Definition at line 1587 of file register-allocator.h.
Constructor & Destructor Documentation
LinearScanAllocator() [1/2]
v8::internal::compiler::LinearScanAllocator::LinearScanAllocator (RegisterAllocationData * data, RegisterKind kind, Zone * local_zone)
Definition at line 2945 of file register-allocator.cc.
    : RegisterAllocator(data, kind),
      unhandled_live_ranges_(local_zone),
      active_live_ranges_(local_zone),
      inactive_live_ranges_(num_registers(), InactiveLiveRangeQueue(local_zone),
                            local_zone),
      next_active_ranges_change_(LifetimePosition::Invalid()),
      next_inactive_ranges_change_(LifetimePosition::Invalid()) {
  active_live_ranges().reserve(8);
}
References active_live_ranges().
LinearScanAllocator() [2/2]
v8::internal::compiler::LinearScanAllocator::LinearScanAllocator (const LinearScanAllocator &) [delete]
Member Function Documentation
active_live_ranges()
ZoneVector<LiveRange*>& v8::internal::compiler::LinearScanAllocator::active_live_ranges () [inline], [private]
Definition at line 1595 of file register-allocator.h.
{ return active_live_ranges_; }
References active_live_ranges_.
Referenced by ActiveToHandled(), ActiveToInactive(), AddToActive(), AllocateBlockedReg(), AllocateRegisters(), FindFreeRegistersForRange(), ForwardStateTo(), InactiveToActive(), LinearScanAllocator(), SpillNotLiveRanges(), SplitAndSpillIntersecting(), and UpdateDeferredFixedRanges().
ActiveToHandled()
ZoneVector< LiveRange * >::iterator v8::internal::compiler::LinearScanAllocator::ActiveToHandled (ZoneVector< LiveRange * >::iterator it) [private]
Definition at line 3880 of file register-allocator.cc.
                                             {
  TRACE("Moving live range %d:%d from active to handled\n",
        (*it)->TopLevel()->vreg(), (*it)->relative_id());
  return active_live_ranges().erase(it);
}
References active_live_ranges(), and v8::internal::TRACE().
Referenced by ForwardStateTo(), SpillNotLiveRanges(), and SplitAndSpillIntersecting().
ActiveToInactive()
ZoneVector< LiveRange * >::iterator v8::internal::compiler::LinearScanAllocator::ActiveToInactive (ZoneVector< LiveRange * >::iterator it, LifetimePosition position) [private]
Definition at line 3887 of file register-allocator.cc.
                                                                        {
  LiveRange* range = *it;
  TRACE("Moving live range %d:%d from active to inactive\n",
        (range)->TopLevel()->vreg(), range->relative_id());
  LifetimePosition next_active = range->NextStartAfter(position);
  next_inactive_ranges_change_ =
      std::min(next_inactive_ranges_change_, next_active);
  DCHECK(range->HasRegisterAssigned());
  // Keep `inactive_live_ranges` sorted.
  inactive_live_ranges(range->assigned_register())
      .insert(std::upper_bound(
                  inactive_live_ranges(range->assigned_register()).begin(),
                  inactive_live_ranges(range->assigned_register()).end(), range,
                  InactiveLiveRangeOrdering()),
              1, range);
  return active_live_ranges().erase(it);
}
References active_live_ranges(), v8::internal::compiler::LiveRange::assigned_register(), v8::internal::ZoneVector< T >::begin(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::LiveRange::HasRegisterAssigned(), inactive_live_ranges(), v8::internal::ZoneVector< T >::insert(), next_inactive_ranges_change_, v8::internal::compiler::LiveRange::NextStartAfter(), v8::internal::compiler::LiveRange::relative_id(), and v8::internal::TRACE().
Referenced by ForwardStateTo().
AddToActive()
void v8::internal::compiler::LinearScanAllocator::AddToActive (LiveRange * range) [private]
Definition at line 3847 of file register-allocator.cc.
                                                      {
  TRACE("Add live range %d:%d in %s to active\n", range->TopLevel()->vreg(),
        range->relative_id(), RegisterName(range->assigned_register()));
  active_live_ranges().push_back(range);
  next_active_ranges_change_ =
      std::min(next_active_ranges_change_, range->NextEndAfter(range->Start()));
}
References active_live_ranges(), v8::internal::compiler::LiveRange::assigned_register(), next_active_ranges_change_, v8::internal::compiler::LiveRange::NextEndAfter(), v8::internal::compiler::RegisterAllocator::RegisterName(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::LiveRange::Start(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by ProcessCurrentRange(), and ReloadLiveRanges().
AddToInactive()
void v8::internal::compiler::LinearScanAllocator::AddToInactive (LiveRange * range) [private]
Definition at line 3855 of file register-allocator.cc.
                                                        {
  TRACE("Add live range %d:%d to inactive\n", range->TopLevel()->vreg(),
        range->relative_id());
  next_inactive_ranges_change_ = std::min(
      next_inactive_ranges_change_, range->NextStartAfter(range->Start()));
  DCHECK(range->HasRegisterAssigned());
  // Keep `inactive_live_ranges` sorted.
  inactive_live_ranges(range->assigned_register())
      .insert(std::upper_bound(
                  inactive_live_ranges(range->assigned_register()).begin(),
                  inactive_live_ranges(range->assigned_register()).end(), range,
                  InactiveLiveRangeOrdering()),
              1, range);
}
References v8::internal::compiler::LiveRange::assigned_register(), v8::internal::ZoneVector< T >::begin(), v8::internal::DCHECK(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::LiveRange::HasRegisterAssigned(), inactive_live_ranges(), v8::internal::ZoneVector< T >::insert(), next_inactive_ranges_change_, v8::internal::compiler::LiveRange::NextStartAfter(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::LiveRange::Start(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by AllocateRegisters(), and UpdateDeferredFixedRanges().
AddToUnhandled()
void v8::internal::compiler::LinearScanAllocator::AddToUnhandled (LiveRange * range) [private]
Definition at line 3870 of file register-allocator.cc.
                                                         {
  if (range == nullptr || range->IsEmpty()) return;
  DCHECK(!range->HasRegisterAssigned() && !range->spilled());
  DCHECK(allocation_finger_ <= range->Start());
  TRACE("Add live range %d:%d to unhandled\n", range->TopLevel()->vreg(),
        range->relative_id());
  unhandled_live_ranges().insert(range);
}
References v8::internal::DCHECK(), v8::internal::compiler::LiveRange::HasRegisterAssigned(), v8::internal::compiler::LiveRange::IsEmpty(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::LiveRange::spilled(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), unhandled_live_ranges(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by AllocateBlockedReg(), AllocateRegisters(), AssignRegisterOnReload(), ReloadLiveRanges(), SpillBetweenUntil(), SpillNotLiveRanges(), TryAllocateFreeReg(), and UpdateDeferredFixedRanges().
AllocateBlockedReg()
void v8::internal::compiler::LinearScanAllocator::AllocateBlockedReg (LiveRange * range, SpillMode spill_mode) [private]
Definition at line 4237 of file register-allocator.cc.
                                                                   {
  UsePosition* register_use = current->NextRegisterPosition(current->Start());
  if (register_use == nullptr) {
    // There is no use in the current live range that requires a register.
    // We can just spill it.
    LiveRange* begin_spill = nullptr;
    LifetimePosition spill_pos = FindOptimalSpillingPos(
        current, current->Start(), spill_mode, &begin_spill);
    MaybeSpillPreviousRanges(begin_spill, spill_pos, current);
    Spill(current, spill_mode);
    return;
  }
  MachineRepresentation rep = current->representation();
  // use_pos keeps track of positions a register/alias is used at.
  // block_pos keeps track of positions where a register/alias is blocked
  // from.
  base::EmbeddedVector<LifetimePosition, RegisterConfiguration::kMaxRegisters>
      use_pos(LifetimePosition::MaxPosition());
  base::EmbeddedVector<LifetimePosition, RegisterConfiguration::kMaxRegisters>
      block_pos(LifetimePosition::MaxPosition());
  for (LiveRange* range : active_live_ranges()) {
    int cur_reg = range->assigned_register();
    bool is_fixed_or_cant_spill =
        range->TopLevel()->IsFixed() || !range->CanBeSpilled(current->Start());
    if (kFPAliasing != AliasingKind::kCombine || !check_fp_aliasing()) {
      if (is_fixed_or_cant_spill) {
        block_pos[cur_reg] = use_pos[cur_reg] =
            LifetimePosition::GapFromInstructionIndex(0);
      } else {
        DCHECK_NE(LifetimePosition::GapFromInstructionIndex(0),
                  block_pos[cur_reg]);
        use_pos[cur_reg] =
            range->NextLifetimePositionRegisterIsBeneficial(current->Start());
      }
    } else {
      int alias_base_index = -1;
      int aliases = data()->config()->GetAliases(
          range->representation(), cur_reg, rep, &alias_base_index);
      DCHECK(aliases > 0 || (aliases == 0 && alias_base_index == -1));
      while (aliases--) {
        int aliased_reg = alias_base_index + aliases;
        if (is_fixed_or_cant_spill) {
          block_pos[aliased_reg] = use_pos[aliased_reg] =
              LifetimePosition::GapFromInstructionIndex(0);
        } else {
          use_pos[aliased_reg] =
              std::min(block_pos[aliased_reg],
                       range->NextLifetimePositionRegisterIsBeneficial(
                           current->Start()));
        }
      }
    }
  }
  for (int cur_reg = 0; cur_reg < num_registers(); ++cur_reg) {
    SlowDCheckInactiveLiveRangesIsSorted(cur_reg);
    for (LiveRange* range : inactive_live_ranges(cur_reg)) {
      DCHECK(range->End() > current->Start());
      DCHECK_EQ(range->assigned_register(), cur_reg);
      bool is_fixed = range->TopLevel()->IsFixed();
      // Don't perform costly intersections if they are guaranteed to not update
      // block_pos or use_pos.
      // TODO(mtrofin): extend to aliased ranges, too.
      if ((kFPAliasing != AliasingKind::kCombine || !check_fp_aliasing())) {
        DCHECK_LE(use_pos[cur_reg], block_pos[cur_reg]);
        if (block_pos[cur_reg] <= range->NextStart()) break;
        if (!is_fixed && use_pos[cur_reg] <= range->NextStart()) continue;
      }
      LifetimePosition next_intersection = range->FirstIntersection(current);
      if (!next_intersection.IsValid()) continue;
      if (kFPAliasing != AliasingKind::kCombine || !check_fp_aliasing()) {
        if (is_fixed) {
          block_pos[cur_reg] = std::min(block_pos[cur_reg], next_intersection);
          use_pos[cur_reg] = std::min(block_pos[cur_reg], use_pos[cur_reg]);
        } else {
          use_pos[cur_reg] = std::min(use_pos[cur_reg], next_intersection);
        }
      } else {
        int alias_base_index = -1;
        int aliases = data()->config()->GetAliases(
            range->representation(), cur_reg, rep, &alias_base_index);
        DCHECK(aliases > 0 || (aliases == 0 && alias_base_index == -1));
        while (aliases--) {
          int aliased_reg = alias_base_index + aliases;
          if (is_fixed) {
            block_pos[aliased_reg] =
                std::min(block_pos[aliased_reg], next_intersection);
            use_pos[aliased_reg] =
                std::min(block_pos[aliased_reg], use_pos[aliased_reg]);
          } else {
            use_pos[aliased_reg] =
                std::min(use_pos[aliased_reg], next_intersection);
          }
        }
      }
    }
  }
  // Compute register hint if it exists.
  int hint_reg = kUnassignedRegister;
  current->RegisterFromControlFlow(&hint_reg) ||
      register_use->HintRegister(&hint_reg) ||
      current->RegisterFromBundle(&hint_reg);
  int reg = PickRegisterThatIsAvailableLongest(current, hint_reg, use_pos);
  if (use_pos[reg] < register_use->pos()) {
    // If there is a gap position before the next register use, we can
    // spill until there. The gap position will then fit the fill move.
    if (LifetimePosition::ExistsGapPositionBetween(current->Start(),
                                                   register_use->pos())) {
      SpillBetween(current, current->Start(), register_use->pos(), spill_mode);
      return;
    }
  }
  // When in deferred spilling mode avoid stealing registers beyond the current
  // deferred region. This is required as we otherwise might spill an inactive
  // range with a start outside of deferred code and that would not be reloaded.
  LifetimePosition new_end = current->End();
  if (spill_mode == SpillMode::kSpillDeferred) {
    InstructionBlock* deferred_block =
        code()->GetInstructionBlock(current->Start().ToInstructionIndex());
    new_end =
        std::min(new_end, LifetimePosition::GapFromInstructionIndex(
                              LastDeferredInstructionIndex(deferred_block)));
  }
  // We couldn't spill until the next register use. Split before the register
  // is blocked, if applicable.
  if (block_pos[reg] < new_end) {
    // Register becomes blocked before the current range end. Split before that
    // position.
    new_end = block_pos[reg].Start();
  }
  // If there is no register available at all, we can only spill this range.
  // Happens for instance on entry to deferred code where registers might
  // become blocked yet we aim to reload ranges.
  if (new_end == current->Start()) {
    SpillBetween(current, new_end, register_use->pos(), spill_mode);
    return;
  }
  // Split at the new end if we found one.
  if (new_end != current->End()) {
    LiveRange* tail = SplitBetween(current, current->Start(), new_end);
    AddToUnhandled(tail);
  }
  // Register reg is not blocked for the whole range.
  DCHECK(block_pos[reg] >= current->End());
  TRACE("Assigning blocked reg %s to live range %d:%d\n", RegisterName(reg),
        current->TopLevel()->vreg(), current->relative_id());
  SetLiveRangeAssignedRegister(current, reg);
  // This register was not free. Thus we need to find and spill
  // parts of active and inactive live regions that use the same register
  // at the same lifetime positions as current.
  SplitAndSpillIntersecting(current, spill_mode);
}
References active_live_ranges(), AddToUnhandled(), v8::internal::compiler::RegisterAllocator::check_fp_aliasing(), v8::internal::compiler::RegisterAllocator::code(), v8::internal::compiler::RegisterAllocationData::config(), v8::internal::compiler::RegisterAllocator::data(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_NE, v8::internal::compiler::LiveRange::End(), v8::internal::compiler::LifetimePosition::ExistsGapPositionBetween(), v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos(), v8::internal::compiler::LifetimePosition::GapFromInstructionIndex(), v8::internal::RegisterConfiguration::GetAliases(), v8::internal::compiler::InstructionSequence::GetInstructionBlock(), v8::internal::compiler::UsePosition::HintRegister(), inactive_live_ranges(), v8::internal::compiler::LifetimePosition::IsValid(), v8::internal::kCombine, v8::internal::kFPAliasing, v8::internal::compiler::kUnassignedRegister, LastDeferredInstructionIndex(), v8::internal::compiler::LifetimePosition::MaxPosition(), MaybeSpillPreviousRanges(), v8::internal::compiler::LiveRange::NextRegisterPosition(), v8::internal::compiler::RegisterAllocator::num_registers(), PickRegisterThatIsAvailableLongest(), v8::internal::compiler::UsePosition::pos(), v8::internal::compiler::LiveRange::RegisterFromBundle(), v8::internal::compiler::LiveRange::RegisterFromControlFlow(), v8::internal::compiler::RegisterAllocator::RegisterName(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::LiveRange::representation(), SetLiveRangeAssignedRegister(), SlowDCheckInactiveLiveRangesIsSorted(), v8::internal::compiler::RegisterAllocator::Spill(), SpillBetween(), SplitAndSpillIntersecting(), v8::internal::compiler::RegisterAllocator::SplitBetween(), v8::internal::compiler::LiveRange::Start(), v8::internal::compiler::LifetimePosition::ToInstructionIndex(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by ProcessCurrentRange().
AllocateRegisters()
void v8::internal::compiler::LinearScanAllocator::AllocateRegisters ()
Definition at line 3565 of file register-allocator.cc.
                                            {
  DCHECK(unhandled_live_ranges().empty());
  DCHECK(active_live_ranges().empty());
  for (int reg = 0; reg < num_registers(); ++reg) {
    DCHECK(inactive_live_ranges(reg).empty());
  }
  SplitAndSpillRangesDefinedByMemoryOperand();
  data()->ResetSpillState();
  if (v8_flags.trace_turbo_alloc) {
    PrintRangeOverview();
  }
  const size_t live_ranges_size = data()->live_ranges().size();
  for (TopLevelLiveRange* range : data()->live_ranges()) {
    CHECK_EQ(live_ranges_size,
             data()->live_ranges().size()); // TODO(neis): crbug.com/831822
    if (!CanProcessRange(range)) continue;
    for (LiveRange* to_add = range; to_add != nullptr;
         to_add = to_add->next()) {
      if (!to_add->spilled()) {
        AddToUnhandled(to_add);
      }
    }
  }
  if (mode() == RegisterKind::kGeneral) {
    for (TopLevelLiveRange* current : data()->fixed_live_ranges()) {
      if (current != nullptr) {
        if (current->IsDeferredFixed()) continue;
        AddToInactive(current);
      }
    }
  } else if (mode() == RegisterKind::kDouble) {
    for (TopLevelLiveRange* current : data()->fixed_double_live_ranges()) {
      if (current != nullptr) {
        if (current->IsDeferredFixed()) continue;
        AddToInactive(current);
      }
    }
    if (kFPAliasing == AliasingKind::kCombine && check_fp_aliasing()) {
      for (TopLevelLiveRange* current : data()->fixed_float_live_ranges()) {
        if (current != nullptr) {
          if (current->IsDeferredFixed()) continue;
          AddToInactive(current);
        }
      }
      for (TopLevelLiveRange* current : data()->fixed_simd128_live_ranges()) {
        if (current != nullptr) {
          if (current->IsDeferredFixed()) continue;
          AddToInactive(current);
        }
      }
    }
  } else {
    DCHECK(mode() == RegisterKind::kSimd128);
    for (TopLevelLiveRange* current : data()->fixed_simd128_live_ranges()) {
      if (current != nullptr) {
        if (current->IsDeferredFixed()) continue;
        AddToInactive(current);
      }
    }
  }
  RpoNumber last_block = RpoNumber::FromInt(0);
  RpoNumber max_blocks =
      RpoNumber::FromInt(code()->InstructionBlockCount() - 1);
  LifetimePosition next_block_boundary =
      LifetimePosition::InstructionFromInstructionIndex(
          data()
              ->code()
              ->InstructionBlockAt(last_block)
              ->last_instruction_index())
          .NextFullStart();
  SpillMode spill_mode = SpillMode::kSpillAtDefinition;
  // Process all ranges. We also need to ensure that we have seen all block
  // boundaries. Linear scan might have assigned and spilled ranges before
  // reaching the last block and hence we would ignore control flow effects for
  // those. Not only does this produce a potentially bad assignment, it also
  // breaks with the invariant that we undo spills that happen in deferred code
  // when crossing a deferred/non-deferred boundary.
  while (!unhandled_live_ranges().empty() || last_block < max_blocks) {
    data()->tick_counter()->TickAndMaybeEnterSafepoint();
    LiveRange* current = unhandled_live_ranges().empty()
                             ? nullptr
                             : *unhandled_live_ranges().begin();
    LifetimePosition position =
        current ? current->Start() : next_block_boundary;
#ifdef DEBUG
    allocation_finger_ = position;
#endif
    // Check whether we just moved across a block boundary. This will trigger
    // for the first range that is past the current boundary.
    if (position >= next_block_boundary) {
      TRACE("Processing boundary at %d leaving %d\n",
            next_block_boundary.value(), last_block.ToInt());
      // Forward state to before block boundary
      LifetimePosition end_of_block = next_block_boundary.PrevStart().End();
      ForwardStateTo(end_of_block);
      // Remember this state.
      InstructionBlock* current_block = data()->code()->GetInstructionBlock(
          next_block_boundary.ToInstructionIndex());
      // Store current spill state (as the state at end of block). For
      // simplicity, we store the active ranges, e.g., the live ranges that
      // are not spilled.
      data()->RememberSpillState(last_block, active_live_ranges());
      // Only reset the state if this was not a direct fallthrough. Otherwise
      // control flow resolution will get confused (it does not expect changes
      // across fallthrough edges.).
      bool fallthrough =
          (current_block->PredecessorCount() == 1) &&
          current_block->predecessors()[0].IsNext(current_block->rpo_number());
      // When crossing a deferred/non-deferred boundary, we have to load or
      // remove the deferred fixed ranges from inactive.
      if ((spill_mode == SpillMode::kSpillDeferred) !=
          current_block->IsDeferred()) {
        // Update spill mode.
        spill_mode = current_block->IsDeferred()
                         ? SpillMode::kSpillDeferred
                         : SpillMode::kSpillAtDefinition;
        ForwardStateTo(next_block_boundary);
#ifdef DEBUG
        // Allow allocation at current position.
        allocation_finger_ = next_block_boundary;
#endif
        UpdateDeferredFixedRanges(spill_mode, current_block);
      }
      // Allocation relies on the fact that each non-deferred block has at
      // least one non-deferred predecessor. Check this invariant here.
      DCHECK_IMPLIES(!current_block->IsDeferred(),
                     HasNonDeferredPredecessor(current_block));
      if (!fallthrough) {
#ifdef DEBUG
        // Allow allocation at current position.
        allocation_finger_ = next_block_boundary;
#endif
        // We are currently at next_block_boundary - 1. Move the state to the
        // actual block boundary position. In particular, we have to
        // reactivate inactive ranges so that they get rescheduled for
        // allocation if they were not live at the predecessors.
        ForwardStateTo(next_block_boundary);
        RangeRegisterSmallMap to_be_live(allocation_zone());
        // If we end up deciding to use the state of the immediate
        // predecessor, it is better not to perform a change. It would lead to
        // the same outcome anyway.
        // This may never happen on boundaries between deferred and
        // non-deferred code, as we rely on explicit respill to ensure we
        // spill at definition.
        bool no_change_required = false;
        auto pick_state_from = [this, current_block](
                                   RpoNumber pred,
                                   RangeRegisterSmallMap& to_be_live) -> bool {
          TRACE("Using information from B%d\n", pred.ToInt());
          // If this is a fall-through that is not across a deferred
          // boundary, there is nothing to do.
          bool is_noop = pred.IsNext(current_block->rpo_number());
          if (!is_noop) {
            auto& spill_state = data()->GetSpillState(pred);
            TRACE("Not a fallthrough. Adding %zu elements...\n",
                  spill_state.size());
            LifetimePosition pred_end =
                LifetimePosition::GapFromInstructionIndex(
                    this->code()->InstructionBlockAt(pred)->code_end());
            DCHECK(to_be_live.empty());
            for (const auto range : spill_state) {
              // Filter out ranges that were split or had their register
              // stolen by backwards working spill heuristics. These have
              // been spilled after the fact, so ignore them.
              if (range->End() < pred_end || !range->HasRegisterAssigned())
                continue;
              auto [_, inserted] = to_be_live.emplace(
                  range->TopLevel(), range->assigned_register());
              DCHECK(inserted);
              USE(inserted);
            }
          }
          return is_noop;
        };
        // Multiple cases here:
        // 1) We have a single predecessor => this is a control flow split, so
        // just restore the predecessor state.
        // 2) We have two predecessors => this is a conditional, so break ties
        // based on what to do based on forward uses, trying to benefit
        // the same branch if in doubt (make one path fast).
        // 3) We have many predecessors => this is a switch. Compute union
        // based on majority, break ties by looking forward.
        if (current_block->PredecessorCount() == 1) {
          TRACE("Single predecessor for B%d\n",
                current_block->rpo_number().ToInt());
          no_change_required =
              pick_state_from(current_block->predecessors()[0], to_be_live);
        } else if (current_block->PredecessorCount() == 2) {
          TRACE("Two predecessors for B%d\n",
                current_block->rpo_number().ToInt());
          // If one of the branches does not contribute any information,
          // e.g. because it is deferred or a back edge, we can short cut
          // here right away.
          RpoNumber chosen_predecessor = RpoNumber::Invalid();
          if (!ConsiderBlockForControlFlow(current_block,
                                           current_block->predecessors()[0])) {
            chosen_predecessor = current_block->predecessors()[1];
          } else if (!ConsiderBlockForControlFlow(
                         current_block, current_block->predecessors()[1])) {
            chosen_predecessor = current_block->predecessors()[0];
          } else {
            chosen_predecessor = ChooseOneOfTwoPredecessorStates(
                current_block, next_block_boundary);
          }
          no_change_required = pick_state_from(chosen_predecessor, to_be_live);
        } else {
          // Merge at the end of, e.g., a switch.
          ComputeStateFromManyPredecessors(current_block, to_be_live);
        }
        if (!no_change_required) {
          SpillNotLiveRanges(to_be_live, next_block_boundary, spill_mode);
          ReloadLiveRanges(to_be_live, next_block_boundary);
        }
      }
      // Update block information
      last_block = current_block->rpo_number();
      next_block_boundary = LifetimePosition::InstructionFromInstructionIndex(
                                current_block->last_instruction_index())
                                .NextFullStart();
      // We might have created new unhandled live ranges, so cycle around the
      // loop to make sure we pick the top most range in unhandled for
      // processing.
      continue;
    }
    DCHECK_NOT_NULL(current);
    TRACE("Processing interval %d:%d start=%d\n", current->TopLevel()->vreg(),
          current->relative_id(), position.value());
    // Now we can erase current, as we are sure to process it.
    unhandled_live_ranges().erase(unhandled_live_ranges().begin());
    if (current->IsTopLevel() && TryReuseSpillForPhi(current->TopLevel()))
      continue;
    ForwardStateTo(position);
    DCHECK(!current->HasRegisterAssigned() && !current->spilled());
    ProcessCurrentRange(current, spill_mode);
  }
  if (v8_flags.trace_turbo_alloc) {
    PrintRangeOverview();
  }
}
References _, active_live_ranges(), AddToInactive(), AddToUnhandled(), v8::internal::compiler::RegisterAllocator::allocation_zone(), v8::internal::compiler::begin(), v8::internal::compiler::RegisterAllocator::CanProcessRange(), CHECK_EQ, v8::internal::compiler::RegisterAllocator::check_fp_aliasing(), ChooseOneOfTwoPredecessorStates(), v8::internal::compiler::RegisterAllocationData::code(), v8::internal::compiler::RegisterAllocator::code(), ComputeStateFromManyPredecessors(), ConsiderBlockForControlFlow(), v8::internal::compiler::RegisterAllocator::data(), v8::internal::DCHECK(), DCHECK_IMPLIES, DCHECK_NOT_NULL, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::emplace(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::empty(), v8::internal::compiler::LifetimePosition::End(), ForwardStateTo(), v8::internal::compiler::RpoNumber::FromInt(), v8::internal::compiler::LifetimePosition::GapFromInstructionIndex(), v8::internal::compiler::InstructionSequence::GetInstructionBlock(), v8::internal::compiler::RegisterAllocationData::GetSpillState(), HasNonDeferredPredecessor(), v8::internal::compiler::LiveRange::HasRegisterAssigned(), inactive_live_ranges(), v8::internal::compiler::LifetimePosition::InstructionFromInstructionIndex(), v8::internal::compiler::RpoNumber::Invalid(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::compiler::RpoNumber::IsNext(), v8::internal::compiler::LiveRange::IsTopLevel(), v8::internal::kCombine, v8::internal::compiler::kDouble, v8::internal::kFPAliasing, v8::internal::compiler::kGeneral, v8::internal::compiler::kSimd128, v8::internal::compiler::InstructionBlock::last_instruction_index(), v8::internal::compiler::RegisterAllocationData::live_ranges(), v8::internal::compiler::RegisterAllocator::mode(), v8::internal::compiler::LiveRange::next(), v8::internal::compiler::LifetimePosition::NextFullStart(), nullptr, v8::internal::compiler::RegisterAllocator::num_registers(), v8::internal::compiler::InstructionBlock::PredecessorCount(), v8::internal::compiler::InstructionBlock::predecessors(), v8::internal::compiler::LifetimePosition::PrevStart(), PrintRangeOverview(), ProcessCurrentRange(), v8::internal::compiler::LiveRange::relative_id(), ReloadLiveRanges(), v8::internal::compiler::RegisterAllocationData::RememberSpillState(), v8::internal::compiler::RegisterAllocationData::ResetSpillState(), v8::internal::compiler::InstructionBlock::rpo_number(), size(), v8::internal::compiler::LiveRange::spilled(), SpillNotLiveRanges(), v8::internal::compiler::RegisterAllocator::SplitAndSpillRangesDefinedByMemoryOperand(), v8::internal::compiler::LiveRange::Start(), v8::internal::compiler::RegisterAllocationData::tick_counter(), v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), v8::internal::compiler::LifetimePosition::ToInstructionIndex(), v8::internal::compiler::RpoNumber::ToInt(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), TryReuseSpillForPhi(), unhandled_live_ranges(), UpdateDeferredFixedRanges(), USE, v8::internal::v8_flags, v8::internal::compiler::LifetimePosition::value(), and v8::internal::compiler::TopLevelLiveRange::vreg().
AssignRegisterOnReload()
LiveRange * v8::internal::compiler::LinearScanAllocator::AssignRegisterOnReload (LiveRange * range, int reg) [private]
Definition at line 3083 of file register-allocator.cc.
                                                                {
  // We know the register is currently free but it might be in
  // use by a currently inactive range. So we might not be able
  // to reload for the full distance. In such case, split here.
  // TODO(herhut):
  // It might be better if we could use the normal unhandled queue and
  // give reloading registers pecedence. That way we would compute the
  // intersection for the entire future.
  LifetimePosition new_end = range->End();
  for (int cur_reg = 0; cur_reg < num_registers(); ++cur_reg) {
    if ((kFPAliasing != AliasingKind::kCombine || !check_fp_aliasing()) &&
        cur_reg != reg) {
      continue;
    }
    SlowDCheckInactiveLiveRangesIsSorted(cur_reg);
    for (LiveRange* cur_inactive : inactive_live_ranges(cur_reg)) {
      if (kFPAliasing == AliasingKind::kCombine && check_fp_aliasing() &&
          !data()->config()->AreAliases(cur_inactive->representation(), cur_reg,
                                        range->representation(), reg)) {
        continue;
      }
      if (new_end <= cur_inactive->NextStart()) {
        // Inactive ranges are sorted by their next start, so the remaining
        // ranges cannot contribute to new_end.
        break;
      }
      auto next_intersection = cur_inactive->FirstIntersection(range);
      if (!next_intersection.IsValid()) continue;
      new_end = std::min(new_end, next_intersection);
    }
  }
  if (new_end != range->End()) {
    TRACE("Found new end for %d:%d at %d\n", range->TopLevel()->vreg(),
          range->relative_id(), new_end.value());
    LiveRange* tail = SplitRangeAt(range, new_end);
    AddToUnhandled(tail);
  }
  SetLiveRangeAssignedRegister(range, reg);
  return range;
}
References AddToUnhandled(), v8::internal::compiler::RegisterAllocator::check_fp_aliasing(), v8::internal::compiler::RegisterAllocator::data(), v8::internal::compiler::LiveRange::End(), inactive_live_ranges(), v8::internal::kCombine, v8::internal::kFPAliasing, v8::internal::compiler::RegisterAllocator::num_registers(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::LiveRange::representation(), SetLiveRangeAssignedRegister(), SlowDCheckInactiveLiveRangesIsSorted(), v8::internal::compiler::RegisterAllocator::SplitRangeAt(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), v8::internal::compiler::LifetimePosition::value(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by ReloadLiveRanges().
BlockIsDeferredOrImmediatePredecessorIsNotDeferred()
bool v8::internal::compiler::LinearScanAllocator::BlockIsDeferredOrImmediatePredecessorIsNotDeferred (const InstructionBlock * block) [private]
Definition at line 3543 of file register-allocator.cc.
                                   {
  if (block->IsDeferred()) return true;
  if (block->PredecessorCount() == 0) return true;
  bool pred_is_deferred = false;
  for (auto pred : block->predecessors()) {
    if (pred.IsNext(block->rpo_number())) {
      pred_is_deferred = code()->InstructionBlockAt(pred)->IsDeferred();
      break;
    }
  }
  return !pred_is_deferred;
}
References v8::internal::compiler::RegisterAllocator::code(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::compiler::InstructionBlock::PredecessorCount(), v8::internal::compiler::InstructionBlock::predecessors(), and v8::internal::compiler::InstructionBlock::rpo_number().
CheckConflict()
bool v8::internal::compiler::LinearScanAllocator::CheckConflict (MachineRepresentation rep, int reg, const RangeRegisterSmallMap & to_be_live) [private]
Definition at line 3283 of file register-allocator.cc.
                                             {
  for (auto [range, expected_reg] : to_be_live) {
    if (data()->config()->AreAliases(range->representation(), expected_reg, rep,
                                     reg)) {
      return true;
    }
  }
  return false;
}
References v8::internal::compiler::RegisterAllocator::data().
Referenced by ComputeStateFromManyPredecessors().
ChooseOneOfTwoPredecessorStates()
RpoNumber v8::internal::compiler::LinearScanAllocator::ChooseOneOfTwoPredecessorStates (InstructionBlock * current_block, LifetimePosition boundary) [private]
Definition at line 3194 of file register-allocator.cc.
                                                                {
  // Pick the state that would generate the least spill/reloads.
  // Compute vectors of ranges with use counts for both sides.
  // We count uses only for live ranges that are unique to either the left or
  // the right predecessor since many live ranges are shared between both.
  // Shared ranges don't influence the decision anyway and this is faster.
  auto& left = data()->GetSpillState(current_block->predecessors()[0]);
  auto& right = data()->GetSpillState(current_block->predecessors()[1]);
  // Build a set of the `TopLevelLiveRange`s in the left predecessor.
  // Usually this set is very small, e.g., for JetStream2 at most 3 ranges in
  // ~72% of the cases and at most 8 ranges in ~93% of the cases. In those cases
  // `SmallMap` is backed by inline storage and uses fast linear search.
  // In some pathological cases the set grows large (e.g. the Wasm binary of
  // v8:9529) and then `SmallMap` gives us O(log n) worst case lookup when
  // intersecting with the right predecessor below. The set is encoded as a
  // `SmallMap` to `Dummy` values, since we don't have an equivalent `SmallSet`.
  struct Dummy {};
  SmallZoneMap<TopLevelLiveRange*, Dummy, 16> left_set(allocation_zone());
  for (LiveRange* range : left) {
    TopLevelLiveRange* parent = range->TopLevel();
    auto [_, inserted] = left_set.emplace(parent, Dummy{});
    // The `LiveRange`s in `left` come from the spill state, which is just the
    // list of active `LiveRange`s at the end of the block (see
    // `RememberSpillState`). Since at most one `LiveRange` out of a
    // `TopLevelLiveRange` can be active at the same time, there should never be
    // the same `TopLevelLiveRange` twice in `left_set`, hence this check.
    DCHECK(inserted);
    USE(inserted);
  }
  // Now build a list of ranges unique to either the left or right predecessor.
  struct RangeUseCount {
    // The set above contains `TopLevelLiveRange`s, but ultimately we want to
    // count uses of the child `LiveRange` covering `boundary`.
    // The lookup in `GetChildCovers` is O(log n), so do it only once when
    // inserting into this list.
    LiveRange* range;
    // +1 if used in the left predecessor, -1 if used in the right predecessor.
    int use_count_delta;
  };
  SmallZoneVector<RangeUseCount, 16> unique_range_use_counts(allocation_zone());
  for (LiveRange* range : right) {
    TopLevelLiveRange* parent = range->TopLevel();
    auto left_it = left_set.find(parent);
    bool range_is_shared_left_and_right = left_it != left_set.end();
    if (range_is_shared_left_and_right) {
      left_set.erase(left_it);
    } else {
      // This range is unique to the right predecessor, so insert into the list.
      LiveRange* child = parent->GetChildCovers(boundary);
      if (child != nullptr) {
        unique_range_use_counts.push_back({child, -1});
      }
    }
  }
  // So far `unique_range_use_counts` contains only the ranges unique in the
  // right predecessor. Now also add the ranges from the left predecessor.
  for (auto [parent, _] : left_set) {
    LiveRange* child = parent->GetChildCovers(boundary);
    if (child != nullptr) {
      unique_range_use_counts.push_back({child, +1});
    }
  }
  // Finally, count the uses for each range.
  int use_count_difference = 0;
  for (auto [range, use_count] : unique_range_use_counts) {
    if (range->NextUsePositionRegisterIsBeneficial(boundary) != nullptr) {
      use_count_difference += use_count;
    }
  }
  if (use_count_difference == 0) {
    // There is a tie in beneficial register uses. Now, look at any use at all.
    // We do not account for all uses, like flowing into a phi.
    // So we just look at ranges still being live.
    TRACE("Looking at only uses\n");
    for (auto [range, use_count] : unique_range_use_counts) {
      if (range->NextUsePosition(boundary) != range->positions().end()) {
        use_count_difference += use_count;
      }
    }
  }
  TRACE("Left predecessor has %d more uses than right\n", use_count_difference);
  return use_count_difference > 0 ? current_block->predecessors()[0]
                                  : current_block->predecessors()[1];
}
References _, v8::internal::compiler::RegisterAllocator::allocation_zone(), v8::internal::compiler::RegisterAllocator::data(), v8::internal::DCHECK(), v8::Dummy(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::emplace(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find(), v8::internal::compiler::TopLevelLiveRange::GetChildCovers(), v8::internal::compiler::RegisterAllocationData::GetSpillState(), v8::internal::compiler::InstructionBlock::predecessors(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), and USE.
Referenced by AllocateRegisters().
ComputeStateFromManyPredecessors()
void v8::internal::compiler::LinearScanAllocator::ComputeStateFromManyPredecessors (InstructionBlock * current_block, RangeRegisterSmallMap & to_be_live) [private]
Definition at line 3295 of file register-allocator.cc.
                                                                        {
  struct Vote {
    size_t count;
    int used_registers[RegisterConfiguration::kMaxRegisters];
    explicit Vote(int reg) : count(1), used_registers{0} {
      used_registers[reg] = 1;
    }
  };
  struct TopLevelLiveRangeComparator {
    bool operator()(const TopLevelLiveRange* lhs,
                    const TopLevelLiveRange* rhs) const {
      return lhs->vreg() < rhs->vreg();
    }
  };
  // Typically this map is very small, e.g., on JetStream2 it has at most 3
  // elements ~80% of the time and at most 8 elements ~94% of the time.
  // Thus use a `SmallZoneMap` to avoid allocations and because linear search
  // in an array is faster than map lookup for such small sizes.
  // We don't want too many inline elements though since `Vote` is pretty large.
  using RangeVoteMap =
      SmallZoneMap<TopLevelLiveRange*, Vote, 16, TopLevelLiveRangeComparator>;
  static_assert(sizeof(RangeVoteMap) < 4096, "too large stack allocation");
  RangeVoteMap counts(data()->allocation_zone());
  int deferred_blocks = 0;
  for (RpoNumber pred : current_block->predecessors()) {
    if (!ConsiderBlockForControlFlow(current_block, pred)) {
      // Back edges of a loop count as deferred here too.
      deferred_blocks++;
      continue;
    }
    const auto& pred_state = data()->GetSpillState(pred);
    for (LiveRange* range : pred_state) {
      // We might have spilled the register backwards, so the range we
      // stored might have lost its register. Ignore those.
      if (!range->HasRegisterAssigned()) continue;
      TopLevelLiveRange* toplevel = range->TopLevel();
      auto [it, inserted] =
          counts.try_emplace(toplevel, range->assigned_register());
      if (!inserted) {
        it->second.count++;
        it->second.used_registers[range->assigned_register()]++;
      }
    }
  }
  // Choose the live ranges from the majority.
  const size_t majority =
      (current_block->PredecessorCount() + 2 - deferred_blocks) / 2;
  bool taken_registers[RegisterConfiguration::kMaxRegisters] = {false};
  DCHECK(to_be_live.empty());
  auto assign_to_live = [this, majority, &counts](
                            std::function<bool(TopLevelLiveRange*)> filter,
                            RangeRegisterSmallMap& to_be_live,
                            bool* taken_registers) {
    bool check_aliasing =
        kFPAliasing == AliasingKind::kCombine && check_fp_aliasing();
    for (const auto& val : counts) {
      if (!filter(val.first)) continue;
      if (val.second.count >= majority) {
        int register_max = 0;
        int reg = kUnassignedRegister;
        bool conflict = false;
        int num_regs = num_registers();
        int num_codes = num_allocatable_registers();
        const int* codes = allocatable_register_codes();
        MachineRepresentation rep = val.first->representation();
        if (check_aliasing && (rep == MachineRepresentation::kFloat32 ||
                               rep == MachineRepresentation::kSimd128 ||
                               rep == MachineRepresentation::kSimd256))
          GetFPRegisterSet(rep, &num_regs, &num_codes, &codes);
        for (int idx = 0; idx < num_regs; idx++) {
          int uses = val.second.used_registers[idx];
          if (uses == 0) continue;
          if (uses > register_max || (conflict && uses == register_max)) {
            reg = idx;
            register_max = uses;
            conflict = check_aliasing ? CheckConflict(rep, reg, to_be_live)
                                      : taken_registers[reg];
          }
        }
        if (conflict) {
          reg = kUnassignedRegister;
        } else if (!check_aliasing) {
          taken_registers[reg] = true;
        }
        TRACE("Reset %d as live due vote %zu in %s\n", val.first->vreg(),
              val.second.count, RegisterName(reg));
        auto [_, inserted] = to_be_live.emplace(val.first, reg);
        DCHECK(inserted);
        USE(inserted);
      }
    }
  };
  // First round, process fixed registers, as these have precedence.
  // There is only one fixed range per register, so we cannot have
  // conflicts.
  assign_to_live([](TopLevelLiveRange* r) { return r->IsFixed(); }, to_be_live,
                 taken_registers);
  // Second round, process the rest.
  assign_to_live([](TopLevelLiveRange* r) { return !r->IsFixed(); }, to_be_live,
                 taken_registers);
}
References _, v8::internal::compiler::RegisterAllocator::allocatable_register_codes(), v8::internal::compiler::RegisterAllocator::allocation_zone(), v8::internal::compiler::LiveRange::assigned_register(), v8::internal::compiler::bool, v8::internal::compiler::RegisterAllocator::check_fp_aliasing(), CheckConflict(), ConsiderBlockForControlFlow(), v8::internal::compiler::RegisterAllocator::data(), v8::internal::DCHECK(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::emplace(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::empty(), GetFPRegisterSet(), v8::internal::compiler::RegisterAllocationData::GetSpillState(), v8::internal::compiler::TopLevelLiveRange::IsFixed(), v8::internal::kCombine, v8::internal::kFloat32, v8::internal::kFPAliasing, v8::internal::RegisterConfiguration::kMaxRegisters, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::compiler::kUnassignedRegister, v8::internal::compiler::RegisterAllocator::num_allocatable_registers(), v8::internal::compiler::RegisterAllocator::num_registers(), v8::internal::compiler::InstructionBlock::PredecessorCount(), v8::internal::compiler::InstructionBlock::predecessors(), v8::internal::compiler::RegisterAllocator::RegisterName(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), USE, and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by AllocateRegisters().
ConsiderBlockForControlFlow()
bool v8::internal::compiler::LinearScanAllocator::ConsiderBlockForControlFlow (InstructionBlock * current_block, RpoNumber predecessor) [private]
Definition at line 3400 of file register-allocator.cc.
                                                            {
  // We ignore predecessors on back edges when looking for control flow effects,
  // as those lie in the future of allocation and we have no data yet. Also,
  // deferred bocks are ignored on deferred to non-deferred boundaries, as we do
  // not want them to influence allocation of non deferred code.
  return (predecessor < current_block->rpo_number()) &&
         (current_block->IsDeferred() ||
          !code()->InstructionBlockAt(predecessor)->IsDeferred());
}
References v8::internal::compiler::RegisterAllocator::code(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), and v8::internal::compiler::InstructionBlock::IsDeferred().
Referenced by AllocateRegisters(), and ComputeStateFromManyPredecessors().
FindFreeRegistersForRange()
void v8::internal::compiler::LinearScanAllocator::FindFreeRegistersForRange (LiveRange * range, base::Vector< LifetimePosition > free_until_pos) [private]
Definition at line 4025 of file register-allocator.cc.
                                                              {
  int num_regs = num_registers();
  int num_codes = num_allocatable_registers();
  const int* codes = allocatable_register_codes();
  MachineRepresentation rep = range->representation();
  if (kFPAliasing == AliasingKind::kCombine &&
      (rep == MachineRepresentation::kFloat32 ||
       rep == MachineRepresentation::kSimd128)) {
    GetFPRegisterSet(rep, &num_regs, &num_codes, &codes);
  } else if (kFPAliasing == AliasingKind::kIndependent &&
             (rep == MachineRepresentation::kSimd128)) {
    GetSIMD128RegisterSet(&num_regs, &num_codes, &codes);
  }
  DCHECK_GE(positions.length(), num_regs);
  for (int i = 0; i < num_regs; ++i) {
    positions[i] = LifetimePosition::MaxPosition();
  }
  for (LiveRange* cur_active : active_live_ranges()) {
    int cur_reg = cur_active->assigned_register();
    if (kFPAliasing != AliasingKind::kCombine || !check_fp_aliasing()) {
      positions[cur_reg] = LifetimePosition::GapFromInstructionIndex(0);
      TRACE("Register %s is free until pos %d (1) due to %d\n",
            RegisterName(cur_reg),
            LifetimePosition::GapFromInstructionIndex(0).value(),
            cur_active->TopLevel()->vreg());
    } else {
      int alias_base_index = -1;
      int aliases = data()->config()->GetAliases(
          cur_active->representation(), cur_reg, rep, &alias_base_index);
      DCHECK(aliases > 0 || (aliases == 0 && alias_base_index == -1));
      while (aliases--) {
        int aliased_reg = alias_base_index + aliases;
        positions[aliased_reg] = LifetimePosition::GapFromInstructionIndex(0);
      }
    }
  }
  for (int cur_reg = 0; cur_reg < num_regs; ++cur_reg) {
    SlowDCheckInactiveLiveRangesIsSorted(cur_reg);
    for (LiveRange* cur_inactive : inactive_live_ranges(cur_reg)) {
      DCHECK_GT(cur_inactive->End(), range->Start());
      DCHECK_EQ(cur_inactive->assigned_register(), cur_reg);
      // No need to carry out intersections, when this register won't be
      // interesting to this range anyway.
      // TODO(mtrofin): extend to aliased ranges, too.
      if ((kFPAliasing != AliasingKind::kCombine || !check_fp_aliasing()) &&
          (positions[cur_reg] <= cur_inactive->NextStart() ||
           range->End() <= cur_inactive->NextStart())) {
        break;
      }
      LifetimePosition next_intersection =
          cur_inactive->FirstIntersection(range);
      if (!next_intersection.IsValid()) continue;
      if (kFPAliasing != AliasingKind::kCombine || !check_fp_aliasing()) {
        positions[cur_reg] = std::min(positions[cur_reg], next_intersection);
        TRACE("Register %s is free until pos %d (2)\n", RegisterName(cur_reg),
              positions[cur_reg].value());
      } else {
        int alias_base_index = -1;
        int aliases = data()->config()->GetAliases(
            cur_inactive->representation(), cur_reg, rep, &alias_base_index);
        DCHECK(aliases > 0 || (aliases == 0 && alias_base_index == -1));
        while (aliases--) {
          int aliased_reg = alias_base_index + aliases;
          positions[aliased_reg] =
              std::min(positions[aliased_reg], next_intersection);
        }
      }
    }
  }
}
References active_live_ranges(), v8::internal::compiler::RegisterAllocator::allocatable_register_codes(), v8::internal::compiler::RegisterAllocator::check_fp_aliasing(), v8::internal::compiler::RegisterAllocationData::config(), v8::internal::compiler::RegisterAllocator::data(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_GT, v8::internal::compiler::LiveRange::End(), v8::internal::compiler::LifetimePosition::GapFromInstructionIndex(), v8::internal::RegisterConfiguration::GetAliases(), GetFPRegisterSet(), GetSIMD128RegisterSet(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, inactive_live_ranges(), v8::internal::compiler::LifetimePosition::IsValid(), v8::internal::kCombine, v8::internal::kFloat32, v8::internal::kFPAliasing, v8::internal::kIndependent, v8::internal::kSimd128, v8::base::Vector< T >::length(), v8::internal::compiler::LifetimePosition::MaxPosition(), v8::internal::compiler::LifetimePosition::NextStart(), v8::internal::compiler::RegisterAllocator::num_allocatable_registers(), v8::internal::compiler::RegisterAllocator::num_registers(), v8::internal::compiler::RegisterAllocator::RegisterName(), v8::internal::compiler::LiveRange::representation(), SlowDCheckInactiveLiveRangesIsSorted(), v8::internal::compiler::LiveRange::Start(), v8::internal::TRACE(), and v8::internal::value.
Referenced by ProcessCurrentRange().
ForwardStateTo()
void v8::internal::compiler::LinearScanAllocator::ForwardStateTo (LifetimePosition position) [private]
Definition at line 3935 of file register-allocator.cc.
                                                                  {
  if (position >= next_active_ranges_change_) {
    next_active_ranges_change_ = LifetimePosition::MaxPosition();
    for (auto it = active_live_ranges().begin();
         it != active_live_ranges().end();) {
      LiveRange* cur_active = *it;
      if (cur_active->End() <= position) {
        it = ActiveToHandled(it);
      } else if (!cur_active->Covers(position)) {
        it = ActiveToInactive(it, position);
      } else {
        next_active_ranges_change_ = std::min(
            next_active_ranges_change_, cur_active->NextEndAfter(position));
        ++it;
      }
    }
  }
  if (position >= next_inactive_ranges_change_) {
    next_inactive_ranges_change_ = LifetimePosition::MaxPosition();
    for (int reg = 0; reg < num_registers(); ++reg) {
      for (auto it = inactive_live_ranges(reg).begin();
           it != inactive_live_ranges(reg).end();) {
        LiveRange* cur_inactive = *it;
        if (cur_inactive->End() <= position) {
          it = InactiveToHandled(it);
        } else if (cur_inactive->Covers(position)) {
          it = InactiveToActive(it, position);
        } else {
          next_inactive_ranges_change_ = std::min(
              next_inactive_ranges_change_,
              // This modifies `cur_inactive.next_start_` and thus
              // invalidates the ordering of `inactive_live_ranges(reg)`.
              cur_inactive->NextStartAfter(position));
          ++it;
        }
      }
      std::sort(inactive_live_ranges(reg).begin(),
                inactive_live_ranges(reg).end(), InactiveLiveRangeOrdering());
    }
  }
  for (int reg = 0; reg < num_registers(); ++reg) {
    SlowDCheckInactiveLiveRangesIsSorted(reg);
  }
}
References active_live_ranges(), ActiveToHandled(), ActiveToInactive(), v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::begin(), v8::internal::compiler::LiveRange::Covers(), v8::internal::compiler::LiveRange::End(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::end(), inactive_live_ranges(), InactiveToActive(), InactiveToHandled(), v8::internal::compiler::LifetimePosition::MaxPosition(), next_active_ranges_change_, next_inactive_ranges_change_, v8::internal::compiler::LiveRange::NextEndAfter(), v8::internal::compiler::LiveRange::NextStartAfter(), v8::internal::compiler::RegisterAllocator::num_registers(), SlowDCheckInactiveLiveRangesIsSorted(), and v8::base::sort().
Referenced by AllocateRegisters().
GetFPRegisterSet()
void v8::internal::compiler::LinearScanAllocator::GetFPRegisterSet (MachineRepresentation rep, int * num_regs, int * num_codes, const int ** codes) const [private]
Definition at line 3995 of file register-allocator.cc.
                                                                    {
  DCHECK_EQ(kFPAliasing, AliasingKind::kCombine);
  if (rep == MachineRepresentation::kFloat32) {
    *num_regs = data()->config()->num_float_registers();
    *num_codes = data()->config()->num_allocatable_float_registers();
    *codes = data()->config()->allocatable_float_codes();
  } else if (rep == MachineRepresentation::kSimd128) {
    *num_regs = data()->config()->num_simd128_registers();
    *num_codes = data()->config()->num_allocatable_simd128_registers();
    *codes = data()->config()->allocatable_simd128_codes();
  } else if (rep == MachineRepresentation::kSimd256) {
    *num_regs = data()->config()->num_simd256_registers();
    *num_codes = data()->config()->num_allocatable_simd256_registers();
    *codes = data()->config()->allocatable_simd256_codes();
  } else {
    UNREACHABLE();
  }
}
References v8::internal::RegisterConfiguration::allocatable_float_codes(), v8::internal::RegisterConfiguration::allocatable_simd128_codes(), v8::internal::RegisterConfiguration::allocatable_simd256_codes(), v8::internal::compiler::RegisterAllocationData::config(), v8::internal::compiler::RegisterAllocator::data(), DCHECK_EQ, v8::internal::kCombine, v8::internal::kFloat32, v8::internal::kFPAliasing, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::RegisterConfiguration::num_allocatable_float_registers(), v8::internal::RegisterConfiguration::num_allocatable_simd128_registers(), v8::internal::RegisterConfiguration::num_allocatable_simd256_registers(), v8::internal::RegisterConfiguration::num_float_registers(), v8::internal::RegisterConfiguration::num_simd128_registers(), v8::internal::RegisterConfiguration::num_simd256_registers(), and v8::internal::UNREACHABLE().
Referenced by ComputeStateFromManyPredecessors(), FindFreeRegistersForRange(), and PickRegisterThatIsAvailableLongest().
GetSIMD128RegisterSet()
void v8::internal::compiler::LinearScanAllocator::GetSIMD128RegisterSet (int * num_regs, int * num_codes, const int ** codes) const [private]
Definition at line 4016 of file register-allocator.cc.
                                                                         {
  DCHECK_EQ(kFPAliasing, AliasingKind::kIndependent);
  *num_regs = data()->config()->num_simd128_registers();
  *num_codes = data()->config()->num_allocatable_simd128_registers();
  *codes = data()->config()->allocatable_simd128_codes();
}
References v8::internal::RegisterConfiguration::allocatable_simd128_codes(), v8::internal::compiler::RegisterAllocationData::config(), v8::internal::compiler::RegisterAllocator::data(), DCHECK_EQ, v8::internal::kFPAliasing, v8::internal::kIndependent, v8::internal::RegisterConfiguration::num_allocatable_simd128_registers(), and v8::internal::RegisterConfiguration::num_simd128_registers().
Referenced by FindFreeRegistersForRange(), and PickRegisterThatIsAvailableLongest().
HasNonDeferredPredecessor()
bool v8::internal::compiler::LinearScanAllocator::HasNonDeferredPredecessor (InstructionBlock * block) [private]
Definition at line 3557 of file register-allocator.cc.
                                                                           {
  for (auto pred : block->predecessors()) {
    InstructionBlock* pred_block = code()->InstructionBlockAt(pred);
    if (!pred_block->IsDeferred()) return true;
  }
  return false;
}
References v8::internal::compiler::RegisterAllocator::code(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::InstructionBlock::IsDeferred(), and v8::internal::compiler::InstructionBlock::predecessors().
Referenced by AllocateRegisters().
inactive_live_ranges()
InactiveLiveRangeQueue& v8::internal::compiler::LinearScanAllocator::inactive_live_ranges (int reg) [inline], [private]
Definition at line 1596 of file register-allocator.h.
                                                        {
    return inactive_live_ranges_[reg];
  }
References inactive_live_ranges_.
Referenced by ActiveToInactive(), AddToInactive(), AllocateBlockedReg(), AllocateRegisters(), AssignRegisterOnReload(), FindFreeRegistersForRange(), ForwardStateTo(), InactiveToActive(), InactiveToHandled(), SlowDCheckInactiveLiveRangesIsSorted(), SplitAndSpillIntersecting(), and UpdateDeferredFixedRanges().
InactiveToActive()
LinearScanAllocator::InactiveLiveRangeQueue::iterator v8::internal::compiler::LinearScanAllocator::InactiveToActive (InactiveLiveRangeQueue::iterator it, LifetimePosition position) [private]
Definition at line 3918 of file register-allocator.cc.
                                                                 {
  LiveRange* range = *it;
  active_live_ranges().push_back(range);
  TRACE("Moving live range %d:%d from inactive to active\n",
        range->TopLevel()->vreg(), range->relative_id());
  next_active_ranges_change_ =
      std::min(next_active_ranges_change_, range->NextEndAfter(position));
  int reg = range->assigned_register();
  // Remove the element without copying O(n) subsequent elements.
  // The order of `inactive_live_ranges` is established afterwards by sorting in
  // `ForwardStateTo`, which is the only caller.
  std::swap(*it, inactive_live_ranges(reg).back());
  inactive_live_ranges(reg).pop_back();
  return it;
}
References active_live_ranges(), v8::internal::compiler::LiveRange::assigned_register(), inactive_live_ranges(), next_active_ranges_change_, v8::internal::compiler::LiveRange::NextEndAfter(), v8::internal::ZoneVector< T >::pop_back(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by ForwardStateTo().
InactiveToHandled()
LinearScanAllocator::InactiveLiveRangeQueue::iterator v8::internal::compiler::LinearScanAllocator::InactiveToHandled (InactiveLiveRangeQueue::iterator it) [private]
Definition at line 3907 of file register-allocator.cc.
                                                                        {
  LiveRange* range = *it;
  TRACE("Moving live range %d:%d from inactive to handled\n",
        range->TopLevel()->vreg(), range->relative_id());
  int reg = range->assigned_register();
  // This must keep the order of `inactive_live_ranges` intact since one of its
  // callers `SplitAndSpillIntersecting` relies on it being sorted.
  return inactive_live_ranges(reg).erase(it);
}
References v8::internal::compiler::LiveRange::assigned_register(), v8::internal::ZoneVector< T >::erase(), inactive_live_ranges(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by ForwardStateTo(), and SplitAndSpillIntersecting().
LastDeferredInstructionIndex()
int v8::internal::compiler::LinearScanAllocator::LastDeferredInstructionIndex (InstructionBlock * start) [private]
Definition at line 3982 of file register-allocator.cc.
                                                                             {
  DCHECK(start->IsDeferred());
  RpoNumber last_block =
      RpoNumber::FromInt(code()->InstructionBlockCount() - 1);
  while ((start->rpo_number() < last_block)) {
    InstructionBlock* next =
        code()->InstructionBlockAt(start->rpo_number().Next());
    if (!next->IsDeferred()) break;
    start = next;
  }
  return start->last_instruction_index();
}
References v8::internal::compiler::RegisterAllocator::code(), v8::internal::DCHECK(), v8::internal::compiler::RpoNumber::FromInt(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::compiler::InstructionBlock::last_instruction_index(), v8::internal::compiler::RpoNumber::Next(), and v8::internal::compiler::InstructionBlock::rpo_number().
Referenced by AllocateBlockedReg(), and UpdateDeferredFixedRanges().
MaybeSpillPreviousRanges()
void v8::internal::compiler::LinearScanAllocator::MaybeSpillPreviousRanges (LiveRange * begin_range, LifetimePosition begin_pos, LiveRange * end_range) [private]
Definition at line 2957 of file register-allocator.cc.
                                                                         {
  // Spill begin_range after begin_pos, then spill every live range of this
  // virtual register until but excluding end_range.
  DCHECK(begin_range->Covers(begin_pos));
  DCHECK_EQ(begin_range->TopLevel(), end_range->TopLevel());
  if (begin_range != end_range) {
    DCHECK_LE(begin_range->End(), end_range->Start());
    if (!begin_range->spilled()) {
      SpillAfter(begin_range, begin_pos, SpillMode::kSpillAtDefinition);
    }
    for (LiveRange* range = begin_range->next(); range != end_range;
         range = range->next()) {
      if (!range->spilled()) {
        range->Spill();
      }
    }
  }
}
References v8::internal::compiler::LiveRange::Covers(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::compiler::LiveRange::End(), v8::internal::compiler::LiveRange::next(), SpillAfter(), v8::internal::compiler::LiveRange::spilled(), v8::internal::compiler::LiveRange::Start(), and v8::internal::compiler::LiveRange::TopLevel().
Referenced by AllocateBlockedReg(), and SplitAndSpillIntersecting().
MaybeUndoPreviousSplit()
void v8::internal::compiler::LinearScanAllocator::MaybeUndoPreviousSplit (LiveRange * range, Zone * zone) [private]
Definition at line 2979 of file register-allocator.cc.
                                                                             {
  if (range->next() != nullptr && range->next()->ShouldRecombine()) {
    LiveRange* to_remove = range->next();
    TRACE("Recombining %d:%d with %d\n", range->TopLevel()->vreg(),
          range->relative_id(), to_remove->relative_id());
    // Remove the range from unhandled, as attaching it will change its
    // state and hence ordering in the unhandled set.
    auto removed_cnt = unhandled_live_ranges().erase(to_remove);
    DCHECK_EQ(removed_cnt, 1);
    USE(removed_cnt);
    range->AttachToNext(zone);
  } else if (range->next() != nullptr) {
    TRACE("No recombine for %d:%d to %d\n", range->TopLevel()->vreg(),
          range->relative_id(), range->next()->relative_id());
  }
}
References v8::internal::compiler::LiveRange::AttachToNext(), DCHECK_EQ, v8::internal::compiler::LiveRange::next(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::LiveRange::ShouldRecombine(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), unhandled_live_ranges(), USE, and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by ReloadLiveRanges(), and SpillNotLiveRanges().
operator=()
LinearScanAllocator& v8::internal::compiler::LinearScanAllocator::operator= (const LinearScanAllocator &) [delete]
PickRegisterThatIsAvailableLongest()
int v8::internal::compiler::LinearScanAllocator::PickRegisterThatIsAvailableLongest (LiveRange * current, int hint_reg, base::Vector< const LifetimePosition > free_until_pos) [private]
Definition at line 4146 of file register-allocator.cc.
                                                       {
  int num_regs = 0; // used only for the call to GetFPRegisterSet.
  int num_codes = num_allocatable_registers();
  const int* codes = allocatable_register_codes();
  MachineRepresentation rep = current->representation();
  if (kFPAliasing == AliasingKind::kCombine &&
      (rep == MachineRepresentation::kFloat32 ||
       rep == MachineRepresentation::kSimd128)) {
    GetFPRegisterSet(rep, &num_regs, &num_codes, &codes);
  } else if (kFPAliasing == AliasingKind::kIndependent &&
             (rep == MachineRepresentation::kSimd128)) {
    GetSIMD128RegisterSet(&num_regs, &num_codes, &codes);
  }
  DCHECK_GE(free_until_pos.length(), num_codes);
  // Find the register which stays free for the longest time. Check for
  // the hinted register first, as we might want to use that one. Only
  // count full instructions for free ranges, as an instruction's internal
  // positions do not help but might shadow a hinted register. This is
  // typically the case for function calls, where all registered are
  // cloberred after the call except for the argument registers, which are
  // set before the call. Hence, the argument registers always get ignored,
  // as their available time is shorter.
  int reg = (hint_reg == kUnassignedRegister) ? codes[0] : hint_reg;
  int current_free = free_until_pos[reg].ToInstructionIndex();
  for (int i = 0; i < num_codes; ++i) {
    int code = codes[i];
    // Prefer registers that have no fixed uses to avoid blocking later hints.
    // We use the first register that has no fixed uses to ensure we use
    // byte addressable registers in ia32 first.
    int candidate_free = free_until_pos[code].ToInstructionIndex();
    TRACE("Register %s in free until %d\n", RegisterName(code), candidate_free);
    if ((candidate_free > current_free) ||
        (candidate_free == current_free && reg != hint_reg &&
         (data()->HasFixedUse(current->representation(), reg) &&
          !data()->HasFixedUse(current->representation(), code)))) {
      reg = code;
      current_free = candidate_free;
    }
  }
  return reg;
}
References v8::internal::compiler::RegisterAllocator::allocatable_register_codes(), v8::internal::compiler::RegisterAllocator::code(), v8::internal::compiler::RegisterAllocator::data(), DCHECK_GE, GetFPRegisterSet(), GetSIMD128RegisterSet(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kCombine, v8::internal::kFloat32, v8::internal::kFPAliasing, v8::internal::kIndependent, v8::internal::kSimd128, v8::internal::compiler::kUnassignedRegister, v8::base::Vector< T >::length(), v8::internal::compiler::RegisterAllocator::num_allocatable_registers(), v8::internal::compiler::RegisterAllocator::RegisterName(), v8::internal::compiler::LiveRange::representation(), and v8::internal::TRACE().
Referenced by AllocateBlockedReg(), and TryAllocateFreeReg().
PrintRangeOverview()
void v8::internal::compiler::LinearScanAllocator::PrintRangeOverview () [private]
Definition at line 1015 of file register-allocator.cc.
                                             {
  std::ostringstream os;
  PrintBlockRow(os, code()->instruction_blocks());
  for (auto const toplevel : data()->fixed_live_ranges()) {
    if (toplevel == nullptr) continue;
    PrintRangeRow(os, toplevel);
  }
  int rowcount = 0;
  for (auto toplevel : data()->live_ranges()) {
    if (!CanProcessRange(toplevel)) continue;
    if (rowcount++ % 10 == 0) PrintBlockRow(os, code()->instruction_blocks());
    PrintRangeRow(os, toplevel);
  }
  PrintF("%s\n", os.str().c_str());
}
References v8::internal::compiler::RegisterAllocator::CanProcessRange(), v8::internal::compiler::RegisterAllocator::code(), v8::internal::compiler::RegisterAllocator::data(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::PrintBlockRow(), v8::internal::PrintF(), and PrintRangeRow().
Referenced by AllocateRegisters().
PrintRangeRow()
void v8::internal::compiler::LinearScanAllocator::PrintRangeRow (std::ostream & os, const TopLevelLiveRange * toplevel) [private]
Definition at line 963 of file register-allocator.cc.
                                                                           {
  int position = 0;
  os << std::setw(3) << toplevel->vreg() << ": ";
  const char* kind_string;
  switch (toplevel->spill_type()) {
    case TopLevelLiveRange::SpillType::kSpillRange:
      kind_string = "ss";
      break;
    case TopLevelLiveRange::SpillType::kDeferredSpillRange:
      kind_string = "sd";
      break;
    case TopLevelLiveRange::SpillType::kSpillOperand:
      kind_string = "so";
      break;
    default:
      kind_string = "s?";
  }
  for (const LiveRange* range = toplevel; range != nullptr;
       range = range->next()) {
    for (const UseInterval& interval : range->intervals()) {
      LifetimePosition start = interval.start();
      LifetimePosition end = interval.end();
      CHECK_GE(start.value(), position);
      for (; start.value() > position; position++) {
        os << ' ';
      }
      int length = end.value() - start.value();
      constexpr int kMaxPrefixLength = 32;
      char buffer[kMaxPrefixLength];
      int max_prefix_length = std::min(length + 1, kMaxPrefixLength);
      int prefix;
      if (range->spilled()) {
        prefix = snprintf(buffer, max_prefix_length, "|%s", kind_string);
      } else {
        prefix = snprintf(buffer, max_prefix_length, "|%s",
                          RegisterName(range->assigned_register()));
      }
      os << buffer;
      position += std::min(prefix, max_prefix_length - 1);
      CHECK_GE(end.value(), position);
      const char line_style = range->spilled() ? '-' : '=';
      for (; end.value() > position; position++) {
        os << line_style;
      }
    }
  }
  os << '\n';
}
References CHECK_GE, v8::internal::compiler::UseInterval::end(), v8::internal::compiler::end(), v8::internal::compiler::TopLevelLiveRange::kDeferredSpillRange, v8::internal::compiler::TopLevelLiveRange::kSpillOperand, v8::internal::compiler::TopLevelLiveRange::kSpillRange, v8::internal::length, v8::internal::compiler::LiveRange::next(), v8::internal::compiler::RegisterAllocator::RegisterName(), v8::internal::compiler::TopLevelLiveRange::spill_type(), v8::internal::compiler::UseInterval::start(), v8::internal::compiler::LifetimePosition::value(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by PrintRangeOverview().
ProcessCurrentRange()
void v8::internal::compiler::LinearScanAllocator::ProcessCurrentRange (LiveRange * current, SpillMode spill_mode) [private]
Definition at line 4107 of file register-allocator.cc.
                                                                    {
  base::EmbeddedVector<LifetimePosition, RegisterConfiguration::kMaxRegisters>
      free_until_pos;
  FindFreeRegistersForRange(current, free_until_pos);
  if (!TryAllocatePreferredReg(current, free_until_pos)) {
    if (!TryAllocateFreeReg(current, free_until_pos)) {
      AllocateBlockedReg(current, spill_mode);
    }
  }
  if (current->HasRegisterAssigned()) {
    AddToActive(current);
  }
}
References AddToActive(), AllocateBlockedReg(), FindFreeRegistersForRange(), v8::internal::compiler::LiveRange::HasRegisterAssigned(), TryAllocateFreeReg(), and TryAllocatePreferredReg().
Referenced by AllocateRegisters().
ReloadLiveRanges()
void v8::internal::compiler::LinearScanAllocator::ReloadLiveRanges (RangeRegisterSmallMap const & to_be_live, LifetimePosition position) [private]
Definition at line 3125 of file register-allocator.cc.
                                                                        {
  // Assumption: All ranges in {to_be_live} are currently spilled and there are
  // no conflicting registers in the active ranges.
  // The former is ensured by SpillNotLiveRanges, the latter is by construction
  // of the to_be_live set.
  for (auto [range, reg] : to_be_live) {
    LiveRange* to_resurrect = range->GetChildCovers(position);
    if (to_resurrect == nullptr) {
      // While the range was life until the end of the predecessor block, it is
      // not live in this block. Either there is a lifetime gap or the range
      // died.
      TRACE("No candidate for %d at %d\n", range->vreg(), position.value());
    } else {
      // We might be resurrecting a range that we spilled until its next use
      // before. In such cases, we have to unsplit it before processing as
      // otherwise we might get register changes from one range to the other
      // in the middle of blocks.
      // If there is a gap between this range and the next, we can just keep
      // it as a register change won't hurt.
      MaybeUndoPreviousSplit(to_resurrect, allocation_zone());
      if (to_resurrect->Start() == position) {
        // This range already starts at this block. It might have been spilled,
        // so we have to unspill it. Otherwise, it is already in the unhandled
        // queue waiting for processing.
        DCHECK(!to_resurrect->HasRegisterAssigned());
        TRACE("Reload %d:%d starting at %d itself\n", range->vreg(),
              to_resurrect->relative_id(), position.value());
        if (to_resurrect->spilled()) {
          to_resurrect->Unspill();
          to_resurrect->set_controlflow_hint(reg);
          AddToUnhandled(to_resurrect);
        } else {
          // Assign the preassigned register if we know. Otherwise, nothing to
          // do as already in unhandeled.
          if (reg != kUnassignedRegister) {
            auto erased_cnt = unhandled_live_ranges().erase(to_resurrect);
            DCHECK_EQ(erased_cnt, 1);
            USE(erased_cnt);
            // We know that there is no conflict with active ranges, so just
            // assign the register to the range.
            to_resurrect = AssignRegisterOnReload(to_resurrect, reg);
            AddToActive(to_resurrect);
          }
        }
      } else {
        // This range was spilled before. We have to split it and schedule the
        // second part for allocation (or assign the register if we know).
        DCHECK(to_resurrect->spilled());
        LiveRange* split = SplitRangeAt(to_resurrect, position);
        TRACE("Reload %d:%d starting at %d as %d\n", range->vreg(),
              to_resurrect->relative_id(), split->Start().value(),
              split->relative_id());
        DCHECK_NE(split, to_resurrect);
        if (reg != kUnassignedRegister) {
          // We know that there is no conflict with active ranges, so just
          // assign the register to the range.
          split = AssignRegisterOnReload(split, reg);
          AddToActive(split);
        } else {
          // Let normal register assignment find a suitable register.
          split->set_controlflow_hint(reg);
          AddToUnhandled(split);
        }
      }
    }
  }
}
References AddToActive(), AddToUnhandled(), v8::internal::compiler::RegisterAllocator::allocation_zone(), AssignRegisterOnReload(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, v8::internal::compiler::LiveRange::HasRegisterAssigned(), v8::internal::compiler::kUnassignedRegister, MaybeUndoPreviousSplit(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::LiveRange::set_controlflow_hint(), v8::internal::compiler::LiveRange::spilled(), v8::internal::libvtune::split(), v8::internal::compiler::RegisterAllocator::SplitRangeAt(), v8::internal::compiler::LiveRange::Start(), v8::internal::TRACE(), unhandled_live_ranges(), v8::internal::compiler::LiveRange::Unspill(), USE, and v8::internal::compiler::LifetimePosition::value().
Referenced by AllocateRegisters().
SetLiveRangeAssignedRegister()
void v8::internal::compiler::LinearScanAllocator::SetLiveRangeAssignedRegister (LiveRange * range, int reg) [private]
Definition at line 3836 of file register-allocator.cc.
                                                                {
  data()->MarkAllocated(range->representation(), reg);
  range->set_assigned_register(reg);
  range->SetUseHints(reg);
  range->UpdateBundleRegister(reg);
  if (range->IsTopLevel() && range->TopLevel()->is_phi()) {
    data()->GetPhiMapValueFor(range->TopLevel())->set_assigned_register(reg);
  }
}
References v8::internal::compiler::RegisterAllocator::data(), v8::internal::compiler::RegisterAllocationData::GetPhiMapValueFor(), v8::internal::compiler::TopLevelLiveRange::is_phi(), v8::internal::compiler::LiveRange::IsTopLevel(), v8::internal::compiler::RegisterAllocationData::MarkAllocated(), v8::internal::compiler::LiveRange::representation(), v8::internal::compiler::LiveRange::set_assigned_register(), v8::internal::compiler::RegisterAllocationData::PhiMapValue::set_assigned_register(), v8::internal::compiler::LiveRange::SetUseHints(), v8::internal::compiler::LiveRange::TopLevel(), and v8::internal::compiler::LiveRange::UpdateBundleRegister().
Referenced by AllocateBlockedReg(), AssignRegisterOnReload(), TryAllocateFreeReg(), and TryAllocatePreferredReg().
SlowDCheckInactiveLiveRangesIsSorted()
void v8::internal::compiler::LinearScanAllocator::SlowDCheckInactiveLiveRangesIsSorted (int reg) [inline], [private]
Definition at line 1605 of file register-allocator.h.
                                                     {
    SLOW_DCHECK(std::is_sorted(inactive_live_ranges(reg).begin(),
                               inactive_live_ranges(reg).end(),
                               InactiveLiveRangeOrdering()));
  }
References v8::internal::compiler::begin(), v8::internal::compiler::end(), inactive_live_ranges(), and SLOW_DCHECK.
Referenced by AllocateBlockedReg(), AssignRegisterOnReload(), FindFreeRegistersForRange(), ForwardStateTo(), SplitAndSpillIntersecting(), and UpdateDeferredFixedRanges().
SpillAfter()
void v8::internal::compiler::LinearScanAllocator::SpillAfter (LiveRange * range, LifetimePosition pos, SpillMode spill_mode) [private]
Definition at line 4538 of file register-allocator.cc.
                                                           {
  LiveRange* second_part = SplitRangeAt(range, pos);
  Spill(second_part, spill_mode);
}
References v8::internal::compiler::RegisterAllocator::Spill(), and v8::internal::compiler::RegisterAllocator::SplitRangeAt().
Referenced by MaybeSpillPreviousRanges(), and SplitAndSpillIntersecting().
SpillBetween()
void v8::internal::compiler::LinearScanAllocator::SpillBetween (LiveRange * range, LifetimePosition start, LifetimePosition end, SpillMode spill_mode) [private]
Definition at line 4544 of file register-allocator.cc.
                                                             {
  SpillBetweenUntil(range, start, start, end, spill_mode);
}
References v8::internal::compiler::end(), and SpillBetweenUntil().
Referenced by AllocateBlockedReg(), SplitAndSpillIntersecting(), and TryReuseSpillForPhi().
SpillBetweenUntil()
void v8::internal::compiler::LinearScanAllocator::SpillBetweenUntil (LiveRange * range, LifetimePosition start, LifetimePosition until, LifetimePosition end, SpillMode spill_mode) [private]
Definition at line 4550 of file register-allocator.cc.
                                                                  {
  CHECK(start < end);
  LiveRange* second_part = SplitRangeAt(range, start);
  if (second_part->Start() < end) {
    // The split result intersects with [start, end[.
    // Split it at position between ]start+1, end[, spill the middle part
    // and put the rest to unhandled.
    // Make sure that the third part always starts after the start of the
    // second part, as that likely is the current position of the register
    // allocator and we cannot add ranges to unhandled that start before
    // the current position.
    LifetimePosition split_start = std::max(second_part->Start().End(), until);
    // If end is an actual use (which it typically is) we have to split
    // so that there is a gap before so that we have space for moving the
    // value into its position.
    // However, if we have no choice, split right where asked.
    LifetimePosition third_part_end =
        std::max(split_start, end.PrevStart().End());
    // Instead of spliting right after or even before the block boundary,
    // split on the boumndary to avoid extra moves.
    if (data()->IsBlockBoundary(end.Start())) {
      third_part_end = std::max(split_start, end.Start());
    }
    LiveRange* third_part =
        SplitBetween(second_part, split_start, third_part_end);
    if (GetInstructionBlock(data()->code(), second_part->Start())
            ->IsDeferred()) {
      // Try to use the same register as before.
      TRACE("Setting control flow hint for %d:%d to %s\n",
            third_part->TopLevel()->vreg(), third_part->relative_id(),
            RegisterName(range->controlflow_hint()));
      third_part->set_controlflow_hint(range->controlflow_hint());
    }
    AddToUnhandled(third_part);
    // This can happen, even if we checked for start < end above, as we fiddle
    // with the end location. However, we are guaranteed to be after or at
    // until, so this is fine.
    if (third_part != second_part) {
      Spill(second_part, spill_mode);
    }
  } else {
    // The split result does not intersect with [start, end[.
    // Nothing to spill. Just put it to unhandled as whole.
    AddToUnhandled(second_part);
  }
}
References AddToUnhandled(), CHECK, v8::internal::compiler::RegisterAllocator::code(), v8::internal::compiler::LiveRange::controlflow_hint(), v8::internal::compiler::RegisterAllocator::data(), v8::internal::compiler::LifetimePosition::End(), v8::internal::compiler::end(), v8::internal::compiler::anonymous_namespace{register-allocator.cc}::GetInstructionBlock(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::compiler::RegisterAllocator::RegisterName(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::LiveRange::set_controlflow_hint(), v8::internal::compiler::RegisterAllocator::Spill(), v8::internal::compiler::RegisterAllocator::SplitBetween(), v8::internal::compiler::RegisterAllocator::SplitRangeAt(), v8::internal::compiler::LiveRange::Start(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by SpillBetween(), and SplitAndSpillIntersecting().
SpillNotLiveRanges()
void v8::internal::compiler::LinearScanAllocator::SpillNotLiveRanges (RangeRegisterSmallMap & to_be_live, LifetimePosition position, SpillMode spill_mode) [private]
Definition at line 2998 of file register-allocator.cc.
                                                                   {
  for (auto it = active_live_ranges().begin();
       it != active_live_ranges().end();) {
    LiveRange* active_range = *it;
    TopLevelLiveRange* toplevel = (*it)->TopLevel();
    auto found = to_be_live.find(toplevel);
    if (found == to_be_live.end()) {
      // Is not contained in {to_be_live}, spill it.
      // Fixed registers are exempt from this. They might have been
      // added from inactive at the block boundary but we know that
      // they cannot conflict as they are built before register
      // allocation starts. It would be algorithmically fine to split
      // them and reschedule but the code does not allow to do this.
      if (toplevel->IsFixed()) {
        TRACE("Keeping reactivated fixed range for %s\n",
              RegisterName(toplevel->assigned_register()));
        ++it;
      } else {
        // When spilling a previously spilled/reloaded range, we add back the
        // tail that we might have split off when we reloaded/spilled it
        // previously. Otherwise we might keep generating small split-offs.
        MaybeUndoPreviousSplit(active_range, allocation_zone());
        TRACE("Putting back %d:%d\n", toplevel->vreg(),
              active_range->relative_id());
        LiveRange* split = SplitRangeAt(active_range, position);
        DCHECK_NE(split, active_range);
        // Make sure we revisit this range once it has a use that requires
        // a register.
        UsePosition* next_use = split->NextRegisterPosition(position);
        if (next_use != nullptr) {
          // Move to the start of the gap before use so that we have a space
          // to perform the potential reload. Otherwise, do not spill but add
          // to unhandled for reallocation.
          LifetimePosition revisit_at = next_use->pos().FullStart();
          TRACE("Next use at %d\n", revisit_at.value());
          if (!data()->IsBlockBoundary(revisit_at)) {
            // Leave some space so we have enough gap room.
            revisit_at = revisit_at.PrevStart().FullStart();
          }
          // If this range became life right at the block boundary that we are
          // currently processing, we do not need to split it. Instead move it
          // to unhandled right away.
          if (position < revisit_at) {
            LiveRange* third_part = SplitRangeAt(split, revisit_at);
            DCHECK_NE(split, third_part);
            Spill(split, spill_mode);
            TRACE("Marking %d:%d to recombine\n", toplevel->vreg(),
                  third_part->relative_id());
            third_part->SetRecombine();
            AddToUnhandled(third_part);
          } else {
            AddToUnhandled(split);
          }
        } else {
          Spill(split, spill_mode);
        }
        it = ActiveToHandled(it);
      }
    } else {
      // This range is contained in {to_be_live}, so we can keep it.
      int expected_register = found->second;
      to_be_live.erase(found);
      if (expected_register == active_range->assigned_register()) {
        // Was life and in correct register, simply pass through.
        TRACE("Keeping %d:%d in %s\n", toplevel->vreg(),
              active_range->relative_id(),
              RegisterName(active_range->assigned_register()));
        ++it;
      } else {
        // Was life but wrong register. Split and schedule for
        // allocation.
        TRACE("Scheduling %d:%d\n", toplevel->vreg(),
              active_range->relative_id());
        LiveRange* split = SplitRangeAt(active_range, position);
        split->set_controlflow_hint(expected_register);
        AddToUnhandled(split);
        it = ActiveToHandled(it);
      }
    }
  }
}
References active_live_ranges(), ActiveToHandled(), AddToUnhandled(), v8::internal::compiler::RegisterAllocator::allocation_zone(), v8::internal::compiler::LiveRange::assigned_register(), v8::internal::compiler::begin(), v8::internal::compiler::RegisterAllocator::data(), DCHECK_NE, v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::end(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::erase(), v8::base::SmallMap< NormalMap, kArraySize, EqualKey, MapInit >::find(), v8::internal::compiler::LifetimePosition::FullStart(), v8::internal::compiler::TopLevelLiveRange::IsFixed(), MaybeUndoPreviousSplit(), v8::internal::compiler::UsePosition::pos(), v8::internal::compiler::LifetimePosition::PrevStart(), v8::internal::compiler::RegisterAllocator::RegisterName(), v8::internal::compiler::LiveRange::relative_id(), v8::internal::compiler::LiveRange::SetRecombine(), v8::internal::compiler::RegisterAllocator::Spill(), v8::internal::libvtune::split(), v8::internal::compiler::RegisterAllocator::SplitRangeAt(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), v8::internal::compiler::LifetimePosition::value(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by AllocateRegisters().
SplitAndSpillIntersecting()
void v8::internal::compiler::LinearScanAllocator::SplitAndSpillIntersecting (LiveRange * range, SpillMode spill_mode) [private]
Definition at line 4405 of file register-allocator.cc.
                                                                          {
  DCHECK(current->HasRegisterAssigned());
  int reg = current->assigned_register();
  LifetimePosition split_pos = current->Start();
  for (auto it = active_live_ranges().begin();
       it != active_live_ranges().end();) {
    LiveRange* range = *it;
    if (kFPAliasing != AliasingKind::kCombine || !check_fp_aliasing()) {
      if (range->assigned_register() != reg) {
        ++it;
        continue;
      }
    } else {
      if (!data()->config()->AreAliases(current->representation(), reg,
                                        range->representation(),
                                        range->assigned_register())) {
        ++it;
        continue;
      }
    }
    UsePosition* next_pos = range->NextRegisterPosition(current->Start());
    LiveRange* begin_spill = nullptr;
    LifetimePosition spill_pos =
        FindOptimalSpillingPos(range, split_pos, spill_mode, &begin_spill);
    MaybeSpillPreviousRanges(begin_spill, spill_pos, range);
    if (next_pos == nullptr) {
      SpillAfter(range, spill_pos, spill_mode);
    } else {
      // When spilling between spill_pos and next_pos ensure that the range
      // remains spilled at least until the start of the current live range.
      // This guarantees that we will not introduce new unhandled ranges that
      // start before the current range as this violates allocation invariants
      // and will lead to an inconsistent state of active and inactive
      // live-ranges: ranges are allocated in order of their start positions,
      // ranges are retired from active/inactive when the start of the
      // current live-range is larger than their end.
      DCHECK(LifetimePosition::ExistsGapPositionBetween(current->Start(),
                                                        next_pos->pos()));
      SpillBetweenUntil(range, spill_pos, current->Start(), next_pos->pos(),
                        spill_mode);
    }
    it = ActiveToHandled(it);
  }
  for (int cur_reg = 0; cur_reg < num_registers(); ++cur_reg) {
    if (kFPAliasing != AliasingKind::kCombine || !check_fp_aliasing()) {
      if (cur_reg != reg) continue;
    }
    SlowDCheckInactiveLiveRangesIsSorted(cur_reg);
    for (auto it = inactive_live_ranges(cur_reg).begin();
         it != inactive_live_ranges(cur_reg).end();) {
      LiveRange* range = *it;
      if (kFPAliasing == AliasingKind::kCombine && check_fp_aliasing() &&
          !data()->config()->AreAliases(current->representation(), reg,
                                        range->representation(), cur_reg)) {
        ++it;
        continue;
      }
      DCHECK(range->End() > current->Start());
      if (range->TopLevel()->IsFixed()) {
        ++it;
        continue;
      }
      LifetimePosition next_intersection = range->FirstIntersection(current);
      if (next_intersection.IsValid()) {
        UsePosition* next_pos = range->NextRegisterPosition(current->Start());
        if (next_pos == nullptr) {
          SpillAfter(range, split_pos, spill_mode);
        } else {
          next_intersection = std::min(next_intersection, next_pos->pos());
          SpillBetween(range, split_pos, next_intersection, spill_mode);
        }
        it = InactiveToHandled(it);
      } else {
        ++it;
      }
    }
  }
}
References active_live_ranges(), ActiveToHandled(), v8::internal::RegisterConfiguration::AreAliases(), v8::internal::compiler::LiveRange::assigned_register(), v8::internal::compiler::begin(), v8::internal::compiler::RegisterAllocator::check_fp_aliasing(), v8::internal::compiler::RegisterAllocationData::config(), v8::internal::compiler::RegisterAllocator::data(), v8::internal::DCHECK(), v8::internal::compiler::LiveRange::End(), v8::internal::ZoneVector< T >::end(), v8::internal::compiler::LifetimePosition::ExistsGapPositionBetween(), v8::internal::compiler::RegisterAllocator::FindOptimalSpillingPos(), v8::internal::compiler::LiveRange::FirstIntersection(), v8::internal::compiler::LiveRange::HasRegisterAssigned(), inactive_live_ranges(), InactiveToHandled(), v8::internal::compiler::TopLevelLiveRange::IsFixed(), v8::internal::compiler::LifetimePosition::IsValid(), v8::internal::kCombine, v8::internal::kFPAliasing, MaybeSpillPreviousRanges(), v8::internal::compiler::LiveRange::NextRegisterPosition(), v8::internal::compiler::RegisterAllocator::num_registers(), v8::internal::compiler::UsePosition::pos(), v8::internal::compiler::LiveRange::representation(), SlowDCheckInactiveLiveRangesIsSorted(), SpillAfter(), SpillBetween(), SpillBetweenUntil(), v8::internal::compiler::LiveRange::Start(), and v8::internal::compiler::LiveRange::TopLevel().
Referenced by AllocateBlockedReg().
TryAllocateFreeReg()
bool v8::internal::compiler::LinearScanAllocator::TryAllocateFreeReg (LiveRange * range, base::Vector< const LifetimePosition > free_until_pos) [private]
Definition at line 4193 of file register-allocator.cc.
                                                                           {
  // Compute register hint, if such exists.
  int hint_reg = kUnassignedRegister;
  current->RegisterFromControlFlow(&hint_reg) ||
      current->RegisterFromFirstHint(&hint_reg) ||
      current->RegisterFromBundle(&hint_reg);
  int reg =
      PickRegisterThatIsAvailableLongest(current, hint_reg, free_until_pos);
  LifetimePosition pos = free_until_pos[reg];
  if (pos <= current->Start()) {
    // All registers are blocked.
    return false;
  }
  if (pos < current->End()) {
    // Register reg is available at the range start but becomes blocked before
    // the range end. Split current before the position where it becomes
    // blocked. Shift the split position to the last gap position. This is to
    // ensure that if a connecting move is needed, that move coincides with the
    // start of the range that it defines. See crbug.com/1182985.
    LifetimePosition gap_pos =
        pos.IsGapPosition() ? pos : pos.FullStart().End();
    if (gap_pos <= current->Start()) return false;
    LiveRange* tail = SplitRangeAt(current, gap_pos);
    AddToUnhandled(tail);
    // Try to allocate preferred register once more.
    if (TryAllocatePreferredReg(current, free_until_pos)) return true;
  }
  // Register reg is available at the range start and is free until the range
  // end.
  DCHECK_GE(pos, current->End());
  TRACE("Assigning free reg %s to live range %d:%d\n", RegisterName(reg),
        current->TopLevel()->vreg(), current->relative_id());
  SetLiveRangeAssignedRegister(current, reg);
  return true;
}
References AddToUnhandled(), DCHECK_GE, v8::internal::compiler::LifetimePosition::End(), v8::internal::compiler::LiveRange::End(), v8::internal::compiler::LifetimePosition::FullStart(), v8::internal::compiler::LifetimePosition::IsGapPosition(), v8::internal::compiler::kUnassignedRegister, PickRegisterThatIsAvailableLongest(), v8::internal::compiler::LiveRange::RegisterFromBundle(), v8::internal::compiler::LiveRange::RegisterFromControlFlow(), v8::internal::compiler::LiveRange::RegisterFromFirstHint(), v8::internal::compiler::RegisterAllocator::RegisterName(), v8::internal::compiler::LiveRange::relative_id(), SetLiveRangeAssignedRegister(), v8::internal::compiler::RegisterAllocator::SplitRangeAt(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), TryAllocatePreferredReg(), and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by ProcessCurrentRange().
TryAllocatePreferredReg()
bool v8::internal::compiler::LinearScanAllocator::TryAllocatePreferredReg (LiveRange * range, base::Vector< const LifetimePosition > free_until_pos) [private]
Definition at line 4122 of file register-allocator.cc.
                                                                           {
  int hint_register;
  if (current->RegisterFromControlFlow(&hint_register) ||
      current->RegisterFromFirstHint(&hint_register) ||
      current->RegisterFromBundle(&hint_register)) {
    TRACE(
        "Found reg hint %s (free until [%d) for live range %d:%d (end %d[).\n",
        RegisterName(hint_register), free_until_pos[hint_register].value(),
        current->TopLevel()->vreg(), current->relative_id(),
        current->End().value());
    // The desired register is free until the end of the current live range.
    if (free_until_pos[hint_register] >= current->End()) {
      TRACE("Assigning preferred reg %s to live range %d:%d\n",
            RegisterName(hint_register), current->TopLevel()->vreg(),
            current->relative_id());
      SetLiveRangeAssignedRegister(current, hint_register);
      return true;
    }
  }
  return false;
}
References v8::internal::compiler::LiveRange::End(), v8::internal::compiler::LiveRange::RegisterFromBundle(), v8::internal::compiler::LiveRange::RegisterFromControlFlow(), v8::internal::compiler::LiveRange::RegisterFromFirstHint(), v8::internal::compiler::RegisterAllocator::RegisterName(), v8::internal::compiler::LiveRange::relative_id(), SetLiveRangeAssignedRegister(), v8::internal::compiler::LiveRange::TopLevel(), v8::internal::TRACE(), v8::internal::compiler::LifetimePosition::value(), v8::internal::value, and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by ProcessCurrentRange(), and TryAllocateFreeReg().
TryReuseSpillForPhi()
bool v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi (TopLevelLiveRange * range) [private]
Definition at line 4488 of file register-allocator.cc.
                                                                      {
  if (!range->is_phi()) return false;
  DCHECK(!range->HasSpillOperand());
  // Check how many operands belong to the same bundle as the output.
  LiveRangeBundle* out_bundle = range->get_bundle();
  RegisterAllocationData::PhiMapValue* phi_map_value =
      data()->GetPhiMapValueFor(range);
  const PhiInstruction* phi = phi_map_value->phi();
  const InstructionBlock* block = phi_map_value->block();
  // Count the number of spilled operands.
  size_t spilled_count = 0;
  for (size_t i = 0; i < phi->operands().size(); i++) {
    int op = phi->operands()[i];
    TopLevelLiveRange* op_range = data()->GetLiveRangeFor(op);
    if (!op_range->HasSpillRange() || op_range->get_bundle() != out_bundle)
      continue;
    const InstructionBlock* pred =
        code()->InstructionBlockAt(block->predecessors()[i]);
    LifetimePosition pred_end =
        LifetimePosition::InstructionFromInstructionIndex(
            pred->last_instruction_index());
    LiveRange* op_range_child = op_range->GetChildCovers(pred_end);
    if (op_range_child != nullptr && op_range_child->spilled()) {
      spilled_count++;
    }
  }
  // Only continue if more than half of the operands are spilled to the same
  // slot (because part of same bundle).
  if (spilled_count * 2 <= phi->operands().size()) {
    return false;
  }
  // If the range does not need register soon, spill it to the merged
  // spill range.
  LifetimePosition next_pos = range->Start();
  if (next_pos.IsGapPosition()) next_pos = next_pos.NextStart();
  UsePosition* pos = range->NextUsePositionRegisterIsBeneficial(next_pos);
  if (pos == nullptr) {
    Spill(range, SpillMode::kSpillAtDefinition);
    return true;
  } else if (pos->pos() > range->Start().NextStart()) {
    SpillBetween(range, range->Start(), pos->pos(),
                 SpillMode::kSpillAtDefinition);
    return true;
  }
  return false;
}
References v8::internal::compiler::RegisterAllocationData::PhiMapValue::block(), v8::internal::compiler::RegisterAllocator::code(), v8::internal::compiler::RegisterAllocator::data(), v8::internal::DCHECK(), v8::internal::compiler::TopLevelLiveRange::get_bundle(), v8::internal::compiler::TopLevelLiveRange::GetChildCovers(), v8::internal::compiler::RegisterAllocationData::GetLiveRangeFor(), v8::internal::compiler::RegisterAllocationData::GetPhiMapValueFor(), v8::internal::compiler::TopLevelLiveRange::HasSpillOperand(), v8::internal::compiler::TopLevelLiveRange::HasSpillRange(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::LifetimePosition::InstructionFromInstructionIndex(), v8::internal::compiler::TopLevelLiveRange::is_phi(), v8::internal::compiler::LifetimePosition::IsGapPosition(), v8::internal::compiler::InstructionBlock::last_instruction_index(), v8::internal::compiler::LifetimePosition::NextStart(), v8::internal::compiler::LiveRange::NextUsePositionRegisterIsBeneficial(), v8::internal::compiler::PhiInstruction::operands(), v8::internal::compiler::RegisterAllocationData::PhiMapValue::phi(), v8::internal::compiler::UsePosition::pos(), v8::internal::compiler::InstructionBlock::predecessors(), v8::internal::ZoneVector< T >::size(), size(), v8::internal::compiler::RegisterAllocator::Spill(), SpillBetween(), v8::internal::compiler::LiveRange::spilled(), and v8::internal::compiler::LiveRange::Start().
Referenced by AllocateRegisters().
unhandled_live_ranges()
UnhandledLiveRangeQueue& v8::internal::compiler::LinearScanAllocator::unhandled_live_ranges () [inline], [private]
Definition at line 1592 of file register-allocator.h.
                                                   {
    return unhandled_live_ranges_;
  }
References unhandled_live_ranges_.
Referenced by AddToUnhandled(), AllocateRegisters(), MaybeUndoPreviousSplit(), and ReloadLiveRanges().
UpdateDeferredFixedRanges()
void v8::internal::compiler::LinearScanAllocator::UpdateDeferredFixedRanges (SpillMode spill_mode, InstructionBlock * block) [private]
Definition at line 3411 of file register-allocator.cc.
                                                                             {
  if (spill_mode == SpillMode::kSpillDeferred) {
    LifetimePosition max = LifetimePosition::InstructionFromInstructionIndex(
        LastDeferredInstructionIndex(block));
    // Adds range back to inactive, resolving resulting conflicts.
    auto add_to_inactive = [this, max](LiveRange* range) {
      AddToInactive(range);
      // Splits other if it conflicts with range. Other is placed in unhandled
      // for later reallocation.
      auto split_conflicting = [this, max](LiveRange* range, LiveRange* other,
                                           std::function<void(LiveRange*)>
                                               update_caches) {
        if (other->TopLevel()->IsFixed()) return;
        int reg = range->assigned_register();
        if (kFPAliasing != AliasingKind::kCombine || !check_fp_aliasing()) {
          if (other->assigned_register() != reg) {
            return;
          }
        } else {
          if (!data()->config()->AreAliases(range->representation(), reg,
                                            other->representation(),
                                            other->assigned_register())) {
            return;
          }
        }
        // The inactive range might conflict, so check whether we need to
        // split and spill. We can look for the first intersection, as there
        // cannot be any intersections in the past, as those would have been a
        // conflict then.
        LifetimePosition next_start = range->FirstIntersection(other);
        if (!next_start.IsValid() || (next_start > max)) {
          // There is no conflict or the conflict is outside of the current
          // stretch of deferred code. In either case we can ignore the
          // inactive range.
          return;
        }
        // They overlap. So we need to split active and reschedule it
        // for allocation.
        TRACE("Resolving conflict of %d with deferred fixed for register %s\n",
              other->TopLevel()->vreg(),
              RegisterName(other->assigned_register()));
        LiveRange* split_off =
            other->SplitAt(next_start, data()->allocation_zone());
        // Try to get the same register after the deferred block.
        split_off->set_controlflow_hint(other->assigned_register());
        DCHECK_NE(split_off, other);
        AddToUnhandled(split_off);
        update_caches(other);
      };
      // Now check for conflicts in active and inactive ranges. We might have
      // conflicts in inactive, as we do not do this check on every block
      // boundary but only on deferred/non-deferred changes but inactive
      // live ranges might become live on any block boundary.
      for (auto active : active_live_ranges()) {
        split_conflicting(range, active, [this](LiveRange* updated) {
          next_active_ranges_change_ =
              std::min(updated->End(), next_active_ranges_change_);
        });
      }
      for (int reg = 0; reg < num_registers(); ++reg) {
        if ((kFPAliasing != AliasingKind::kCombine || !check_fp_aliasing()) &&
            reg != range->assigned_register()) {
          continue;
        }
        SlowDCheckInactiveLiveRangesIsSorted(reg);
        for (auto inactive : inactive_live_ranges(reg)) {
          if (inactive->NextStart() > max) break;
          split_conflicting(range, inactive, [this](LiveRange* updated) {
            next_inactive_ranges_change_ =
                std::min(updated->End(), next_inactive_ranges_change_);
          });
        }
      }
    };
    if (mode() == RegisterKind::kGeneral) {
      for (TopLevelLiveRange* current : data()->fixed_live_ranges()) {
        if (current != nullptr) {
          if (current->IsDeferredFixed()) {
            add_to_inactive(current);
          }
        }
      }
    } else if (mode() == RegisterKind::kDouble) {
      for (TopLevelLiveRange* current : data()->fixed_double_live_ranges()) {
        if (current != nullptr) {
          if (current->IsDeferredFixed()) {
            add_to_inactive(current);
          }
        }
      }
      if (kFPAliasing == AliasingKind::kCombine && check_fp_aliasing()) {
        for (TopLevelLiveRange* current : data()->fixed_float_live_ranges()) {
          if (current != nullptr) {
            if (current->IsDeferredFixed()) {
              add_to_inactive(current);
            }
          }
        }
        for (TopLevelLiveRange* current : data()->fixed_simd128_live_ranges()) {
          if (current != nullptr) {
            if (current->IsDeferredFixed()) {
              add_to_inactive(current);
            }
          }
        }
      }
    } else {
      DCHECK_EQ(mode(), RegisterKind::kSimd128);
      for (TopLevelLiveRange* current : data()->fixed_simd128_live_ranges()) {
        if (current != nullptr) {
          if (current->IsDeferredFixed()) {
            add_to_inactive(current);
          }
        }
      }
    }
  } else {
    // Remove all ranges.
    for (int reg = 0; reg < num_registers(); ++reg) {
      for (auto it = inactive_live_ranges(reg).begin();
           it != inactive_live_ranges(reg).end();) {
        if ((*it)->TopLevel()->IsDeferredFixed()) {
          it = inactive_live_ranges(reg).erase(it);
        } else {
          ++it;
        }
      }
    }
  }
}
References active_live_ranges(), AddToInactive(), AddToUnhandled(), v8::internal::compiler::RegisterAllocator::allocation_zone(), v8::internal::RegisterConfiguration::AreAliases(), v8::internal::compiler::LiveRange::assigned_register(), v8::internal::ZoneVector< T >::begin(), v8::internal::compiler::RegisterAllocator::check_fp_aliasing(), v8::internal::compiler::RegisterAllocationData::config(), v8::internal::compiler::RegisterAllocator::data(), DCHECK_EQ, DCHECK_NE, v8::internal::compiler::LiveRange::End(), v8::internal::ZoneVector< T >::end(), v8::internal::ZoneVector< T >::erase(), v8::internal::compiler::LiveRange::FirstIntersection(), v8::internal::compiler::RegisterAllocationData::fixed_live_ranges(), inactive_live_ranges(), v8::internal::compiler::LifetimePosition::InstructionFromInstructionIndex(), v8::internal::compiler::LifetimePosition::IsValid(), v8::internal::kCombine, v8::internal::compiler::kDouble, v8::internal::kFPAliasing, v8::internal::compiler::kGeneral, v8::internal::compiler::kSimd128, LastDeferredInstructionIndex(), v8::internal::compiler::RegisterAllocator::mode(), next_active_ranges_change_, next_inactive_ranges_change_, v8::internal::compiler::RegisterAllocator::num_registers(), v8::internal::compiler::RegisterAllocator::RegisterName(), v8::internal::compiler::LiveRange::representation(), v8::internal::compiler::LiveRange::set_controlflow_hint(), SlowDCheckInactiveLiveRangesIsSorted(), v8::internal::compiler::LiveRange::SplitAt(), v8::internal::TRACE(), and v8::internal::wasm::void().
Referenced by AllocateRegisters().
Member Data Documentation
active_live_ranges_
ZoneVector<LiveRange*> v8::internal::compiler::LinearScanAllocator::active_live_ranges_ [private]
Definition at line 1683 of file register-allocator.h.
Referenced by active_live_ranges().
inactive_live_ranges_
ZoneVector<InactiveLiveRangeQueue> v8::internal::compiler::LinearScanAllocator::inactive_live_ranges_ [private]
Definition at line 1684 of file register-allocator.h.
Referenced by inactive_live_ranges().
next_active_ranges_change_
LifetimePosition v8::internal::compiler::LinearScanAllocator::next_active_ranges_change_ [private]
Definition at line 1688 of file register-allocator.h.
Referenced by AddToActive(), ForwardStateTo(), InactiveToActive(), and UpdateDeferredFixedRanges().
next_inactive_ranges_change_
LifetimePosition v8::internal::compiler::LinearScanAllocator::next_inactive_ranges_change_ [private]
Definition at line 1689 of file register-allocator.h.
Referenced by ActiveToInactive(), AddToInactive(), ForwardStateTo(), and UpdateDeferredFixedRanges().
unhandled_live_ranges_
UnhandledLiveRangeQueue v8::internal::compiler::LinearScanAllocator::unhandled_live_ranges_ [private]
Definition at line 1682 of file register-allocator.h.
Referenced by unhandled_live_ranges().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc