v8::Value Class Reference
The superclass of all JavaScript values and objects.
#include <v8-value.h>
Public Member Functions
bool IsUndefined () const
Returns true if this value is the undefined value.
bool IsNull () const
Returns true if this value is the null value.
bool IsNullOrUndefined () const
Returns true if this value is either the null or the undefined value.
bool IsTrue () const
Returns true if this value is true.
bool IsFalse () const
Returns true if this value is false.
bool IsName () const
Returns true if this value is a symbol or a string.
bool IsString () const
Returns true if this value is an instance of the String type.
bool IsSymbol () const
Returns true if this value is a symbol.
bool IsFunction () const
Returns true if this value is a function.
bool IsArray () const
Returns true if this value is an array.
bool IsObject () const
Returns true if this value is an object.
bool IsBigInt () const
Returns true if this value is a bigint.
bool IsBoolean () const
Returns true if this value is boolean.
bool IsNumber () const
Returns true if this value is a number.
bool IsExternal () const
Returns true if this value is an External object.
bool IsInt32 () const
Returns true if this value is a 32-bit signed integer.
bool IsUint32 () const
Returns true if this value is a 32-bit unsigned integer.
bool IsDate () const
Returns true if this value is a Date.
bool IsArgumentsObject () const
Returns true if this value is an Arguments object.
bool IsBigIntObject () const
Returns true if this value is a BigInt object.
bool IsBooleanObject () const
Returns true if this value is a Boolean object.
bool IsNumberObject () const
Returns true if this value is a Number object.
bool IsStringObject () const
Returns true if this value is a String object.
bool IsSymbolObject () const
Returns true if this value is a Symbol object.
bool IsNativeError () const
Returns true if this value is a NativeError.
bool IsRegExp () const
Returns true if this value is a RegExp.
bool IsAsyncFunction () const
Returns true if this value is an async function.
bool IsGeneratorFunction () const
Returns true if this value is a Generator function.
bool IsGeneratorObject () const
Returns true if this value is a Generator object (iterator).
bool IsPromise () const
Returns true if this value is a Promise.
bool IsMap () const
Returns true if this value is a Map.
bool IsSet () const
Returns true if this value is a Set.
bool IsMapIterator () const
Returns true if this value is a Map Iterator.
bool IsSetIterator () const
Returns true if this value is a Set Iterator.
bool IsWeakMap () const
Returns true if this value is a WeakMap.
bool IsWeakSet () const
Returns true if this value is a WeakSet.
bool IsWeakRef () const
Returns true if this value is a WeakRef.
bool IsArrayBuffer () const
Returns true if this value is an ArrayBuffer.
bool IsArrayBufferView () const
Returns true if this value is an ArrayBufferView.
bool IsTypedArray () const
Returns true if this value is one of TypedArrays.
bool IsUint8Array () const
Returns true if this value is an Uint8Array.
bool IsUint8ClampedArray () const
Returns true if this value is an Uint8ClampedArray.
bool IsInt8Array () const
Returns true if this value is an Int8Array.
bool IsUint16Array () const
Returns true if this value is an Uint16Array.
bool IsInt16Array () const
Returns true if this value is an Int16Array.
bool IsUint32Array () const
Returns true if this value is an Uint32Array.
bool IsInt32Array () const
Returns true if this value is an Int32Array.
bool IsFloat16Array () const
Returns true if this value is a Float16Array.
bool IsFloat32Array () const
Returns true if this value is a Float32Array.
bool IsFloat64Array () const
Returns true if this value is a Float64Array.
bool IsBigInt64Array () const
Returns true if this value is a BigInt64Array.
bool IsBigUint64Array () const
Returns true if this value is a BigUint64Array.
bool IsDataView () const
Returns true if this value is a DataView.
bool IsSharedArrayBuffer () const
Returns true if this value is a SharedArrayBuffer.
bool IsProxy () const
Returns true if this value is a JavaScript Proxy.
bool IsWasmMemoryObject () const
Returns true if this value is a WasmMemoryObject.
bool IsWasmMemoryMapDescriptor () const
Returns true if this value is a WasmMemoryMapDescriptor.
bool IsWasmModuleObject () const
Returns true if this value is a WasmModuleObject.
bool IsWasmNull () const
Returns true if this value is the WasmNull object.
bool IsModuleNamespaceObject () const
Returns true if the value is a Module Namespace Object.
bool IsPrimitive () const
Returns true if the value is a primitive.
V8_WARN_UNUSED_RESULT MaybeLocal< Primitive > ToPrimitive (Local< Context > context) const
Perform ToPrimitive(value) as specified in: https://tc39.es/ecma262/#sec-toprimitive.
V8_WARN_UNUSED_RESULT MaybeLocal< Numeric > ToNumeric (Local< Context > context) const
Perform ToNumeric(value) as specified in: https://tc39.es/ecma262/#sec-tonumeric.
V8_WARN_UNUSED_RESULT MaybeLocal< BigInt > ToBigInt (Local< Context > context) const
Perform the equivalent of BigInt(value) in JS.
V8_WARN_UNUSED_RESULT MaybeLocal< Number > ToNumber (Local< Context > context) const
Perform the equivalent of Number(value) in JS.
V8_WARN_UNUSED_RESULT MaybeLocal< String > ToString (Local< Context > context) const
Perform the equivalent of String(value) in JS.
V8_WARN_UNUSED_RESULT MaybeLocal< String > ToDetailString (Local< Context > context) const
Provide a string representation of this value usable for debugging.
V8_WARN_UNUSED_RESULT MaybeLocal< Object > ToObject (Local< Context > context) const
Perform the equivalent of Tagged<Object>(value) in JS.
V8_WARN_UNUSED_RESULT MaybeLocal< Integer > ToInteger (Local< Context > context) const
Perform the equivalent of Number(value) in JS and convert the result to an integer.
V8_WARN_UNUSED_RESULT MaybeLocal< Uint32 > ToUint32 (Local< Context > context) const
Perform the equivalent of Number(value) in JS and convert the result to an unsigned 32-bit integer by performing the steps in https://tc39.es/ecma262/#sec-touint32.
V8_WARN_UNUSED_RESULT MaybeLocal< Int32 > ToInt32 (Local< Context > context) const
Perform the equivalent of Number(value) in JS and convert the result to a signed 32-bit integer by performing the steps in https://tc39.es/ecma262/#sec-toint32.
Local< Boolean > ToBoolean (Isolate *isolate) const
Perform the equivalent of Boolean(value) in JS.
V8_WARN_UNUSED_RESULT MaybeLocal< Uint32 > ToArrayIndex (Local< Context > context) const
Attempts to convert a string to an array index.
bool BooleanValue (Isolate *isolate) const
Returns the equivalent of ToBoolean()->Value().
V8_WARN_UNUSED_RESULT Maybe< double > NumberValue (Local< Context > context) const
Returns the equivalent of ToNumber()->Value().
V8_WARN_UNUSED_RESULT Maybe< int64_t > IntegerValue (Local< Context > context) const
Returns the equivalent of ToInteger()->Value().
V8_WARN_UNUSED_RESULT Maybe< uint32_t > Uint32Value (Local< Context > context) const
Returns the equivalent of ToUint32()->Value().
V8_WARN_UNUSED_RESULT Maybe< int32_t > Int32Value (Local< Context > context) const
Returns the equivalent of ToInt32()->Value().
V8_WARN_UNUSED_RESULT Maybe< bool > Equals (Local< Context > context, Local< Value > that) const
JS ==.
bool StrictEquals (Local< Value > that) const
bool SameValue (Local< Value > that) const
Local< String > TypeOf (Isolate *)
Maybe< bool > InstanceOf (Local< Context > context, Local< Object > object)
uint32_t GetHash ()
Get the hash of this value.
template<> Value * Cast (Data *value)
Static Public Member Functions
template<class T >
static Value * Cast (T *value)
Private Member Functions
bool QuickIsUndefined () const
bool QuickIsNull () const
bool QuickIsNullOrUndefined () const
bool QuickIsString () const
bool FullIsUndefined () const
bool FullIsNull () const
bool FullIsTrue () const
bool FullIsFalse () const
bool FullIsString () const
Static Private Member Functions
static void CheckCast (Data *that)
Detailed Description
The superclass of all JavaScript values and objects.
Definition at line 32 of file v8-value.h.
Member Function Documentation
BooleanValue()
bool v8::Value::BooleanValue (Isolate * isolate) const
Returns the equivalent of ToBoolean()->Value().
Definition at line 3757 of file api.cc.
                                                  {
  return i::Object::BooleanValue(*Utils::OpenDirectHandle(this),
                                 reinterpret_cast<i::Isolate*>(v8_isolate));
}
References v8::internal::Object::BooleanValue(), and v8::Utils::OpenDirectHandle().
Referenced by v8::Shell::SetFlushDenormals(), and ToBoolean().
Cast() [1/2]
template<>
Value* v8::Value::Cast (Data * value) [inline]
Definition at line 537 of file v8-value.h.
                                        {
#ifdef V8_ENABLE_CHECKS
  CheckCast(value);
#endif
  return static_cast<Value*>(value);
}
References CheckCast(), and v8::internal::value.
Cast() [2/2]
template<class T >
static Value* v8::Value::Cast (T * value) [inline], [static]
Definition at line 467 of file v8-value.h.
                                         {
    return static_cast<Value*>(value);
  }
References v8::internal::value.
Referenced by v8::Int32::CheckCast(), v8::Uint32::CheckCast(), and v8::BigInt::CheckCast().
CheckCast()
void v8::Value::CheckCast (Data * that) [static], [private]
Definition at line 3854 of file api.cc.
                                  {
  Utils::ApiCheck(that->IsValue(), "v8::Value::Cast", "Data is not a Value");
}
References v8::Utils::ApiCheck(), and v8::Data::IsValue().
Referenced by Cast().
Equals()
Maybe< bool > v8::Value::Equals (Local< Context > context, Local< Value > that) const
JS ==.
Definition at line 4239 of file api.cc.
                                                                         {
  i::Isolate* i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Value_Equals};
  auto self = Utils::OpenDirectHandle(this);
  auto other = Utils::OpenDirectHandle(*that);
  return i::Object::Equals(i_isolate, self, other);
}
References v8::internal::Isolate::Current(), v8::internal::Object::Equals(), and v8::Utils::OpenDirectHandle().
FullIsFalse()
bool v8::Value::FullIsFalse () const [private]
Definition at line 3525 of file api.cc.
                              {
  i::Tagged<i::Object> object = *Utils::OpenDirectHandle(this);
  if (i::IsSmi(object)) return false;
  return i::IsFalse(object);
}
References v8::internal::IsSmi(), and v8::Utils::OpenDirectHandle().
Referenced by IsFalse().
FullIsNull()
bool v8::Value::FullIsNull () const [private]
Definition at line 3513 of file api.cc.
                             {
  bool result = i::IsNull(*Utils::OpenDirectHandle(this));
  DCHECK_EQ(result, QuickIsNull());
  return result;
}
References DCHECK_EQ, v8::internal::IsNull(), v8::Utils::OpenDirectHandle(), QuickIsNull(), and v8::base::internal::result.
Referenced by IsNull(), and IsNullOrUndefined().
FullIsString()
bool v8::Value::FullIsString () const [private]
Definition at line 3542 of file api.cc.
                               {
  bool result = i::IsString(*Utils::OpenDirectHandle(this));
  DCHECK_EQ(result, QuickIsString());
  return result;
}
References DCHECK_EQ, v8::Utils::OpenDirectHandle(), QuickIsString(), and v8::base::internal::result.
Referenced by IsString().
FullIsTrue()
bool v8::Value::FullIsTrue () const [private]
Definition at line 3519 of file api.cc.
                             {
  auto object = *Utils::OpenDirectHandle(this);
  if (i::IsSmi(object)) return false;
  return i::IsTrue(object);
}
References v8::internal::IsSmi(), and v8::Utils::OpenDirectHandle().
Referenced by IsTrue().
FullIsUndefined()
bool v8::Value::FullIsUndefined () const [private]
Definition at line 3507 of file api.cc.
                                  {
  bool result = i::IsUndefined(*Utils::OpenDirectHandle(this));
  DCHECK_EQ(result, QuickIsUndefined());
  return result;
}
References DCHECK_EQ, v8::Utils::OpenDirectHandle(), QuickIsUndefined(), and v8::base::internal::result.
Referenced by IsNullOrUndefined(), and IsUndefined().
GetHash()
uint32_t v8::Value::GetHash ()
Get the hash of this value.
The hash is not guaranteed to be unique. For |Object| and |Name| instances the result is equal to |GetIdentityHash|. Hashes are not guaranteed to be stable across different isolates or processes.
Definition at line 4286 of file api.cc.
                        {
  i::DisallowGarbageCollection no_gc;
  auto self = Utils::OpenDirectHandle(this);
  i::Tagged<i::Object> hash = i::Object::GetHash(*self);
  if (IsSmi(hash)) return i::Cast<i::Smi>(hash).value();
  i::DirectHandle<i::JSReceiver> obj = i::Cast<i::JSReceiver>(self);
  auto i_isolate = i::Isolate::Current();
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  return obj->GetOrCreateIdentityHash(i_isolate).value();
}
References v8::internal::Isolate::Current(), v8::internal::Object::GetHash(), v8::internal::IsSmi(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::Utils::OpenDirectHandle().
InstanceOf()
Maybe< bool > v8::Value::InstanceOf (Local< Context > context, Local< Object > object)
Definition at line 4267 of file api.cc.
                                                        {
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Value_InstanceOf};
  i::DirectHandle<i::JSAny> left;
  if (!Utils::ApiCheck(
          i::TryCast<i::JSAny>(Utils::OpenDirectHandle(this), &left),
          "Value::InstanceOf",
          "Invalid type, must be a JS primitive or object.")) {
    return {};
  }
  auto right = Utils::OpenDirectHandle(*object);
  i::DirectHandle<i::Object> result;
  if (!i::Object::InstanceOf(i_isolate, left, right).ToHandle(&result)) {
    return {};
  }
  return Just(i::IsTrue(*result, i_isolate));
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::Current(), v8::internal::Object::InstanceOf(), v8::Just(), v8::Utils::OpenDirectHandle(), v8::base::internal::result, and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::doesAttributeHaveObservableSideEffectOnGet().
Int32Value()
Maybe< int32_t > v8::Value::Int32Value (Local< Context > context) const
Returns the equivalent of ToInt32()->Value().
Definition at line 4195 of file api.cc.
                                                             {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsNumber(*obj)) return Just(NumberToInt32(*obj));
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Value_Int32Value};
  i::DirectHandle<i::Object> num;
  if (!i::Object::ToInt32(i_isolate, obj).ToHandle(&num)) return {};
  return Just(IsSmi(*num) ? i::Smi::ToInt(*num)
                          : static_cast<int32_t>(
                                i::Cast<i::HeapNumber>(*num)->value()));
}
References v8::internal::Isolate::Current(), v8::internal::IsNumber(), v8::internal::IsSmi(), v8::Just(), v8::internal::NumberToInt32(), v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::Smi::ToInt(), and v8::internal::Object::ToInt32().
IntegerValue()
Maybe< int64_t > v8::Value::IntegerValue (Local< Context > context) const
Returns the equivalent of ToInteger()->Value().
Definition at line 4183 of file api.cc.
                                                               {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsNumber(*obj)) {
    return Just(NumberToInt64(*obj));
  }
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Value_IntegerValue};
  i::DirectHandle<i::Object> num;
  if (!i::Object::ToInteger(i_isolate, obj).ToHandle(&num)) return {};
  return Just(NumberToInt64(*num));
}
References v8::internal::Isolate::Current(), v8::internal::IsNumber(), v8::Just(), v8::internal::NumberToInt64(), v8::Utils::OpenDirectHandle(), and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::anonymous_namespace{builtins-bigint.cc}::BigIntToStringImpl(), v8::internal::BUILTIN(), v8::internal::anonymous_namespace{builtins-array.cc}::GetRelativeIndex(), v8::internal::anonymous_namespace{builtins-string.cc}::IsValidCodePoint(), v8::internal::RUNTIME_FUNCTION(), v8::internal::SliceHelper(), and v8::internal::temporal::ToIntegerWithTruncation().
IsArgumentsObject()
bool v8::Value::IsArgumentsObject () const
Returns true if this value is an Arguments object.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::isArrayLike().
IsArray()
bool v8::Value::IsArray () const
Returns true if this value is an array.
Note that it will return false for an Proxy for an array.
Definition at line 3552 of file api.cc.
                          {
  return IsJSArray(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceFastCallback(), v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8_inspector::generateCustomPreview(), v8_inspector::anonymous_namespace{value-mirror.cc}::isArrayLike(), v8_inspector::V8Regex::match(), v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap(), and v8_inspector::V8ConsoleMessage::wrapArguments().
IsArrayBuffer()
bool v8::Value::IsArrayBuffer () const
Returns true if this value is an ArrayBuffer.
Definition at line 3556 of file api.cc.
                                {
  auto obj = *Utils::OpenDirectHandle(this);
  if (!IsJSArrayBuffer(obj)) return false;
  return !i::Cast<i::JSArrayBuffer>(obj)->is_shared();
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::ValueMirror::create(), v8::anonymous_namespace{wasm-js.cc}::GetFirstArgumentAsBytes(), and v8_inspector::anonymous_namespace{value-mirror.cc}::getPropertiesForPreview().
IsArrayBufferView()
bool v8::Value::IsArrayBufferView () const
Returns true if this value is an ArrayBufferView.
Definition at line 3562 of file api.cc.
                                    {
  return IsJSArrayBufferView(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
IsAsyncFunction()
bool v8::Value::IsAsyncFunction () const
Returns true if this value is an async function.
Definition at line 3683 of file api.cc.
                                  {
  auto obj = *Utils::OpenDirectHandle(this);
  if (!IsJSFunction(obj)) return false;
  auto func = i::Cast<i::JSFunction>(obj);
  return i::IsAsyncFunction(func->shared()->kind());
}
References v8::internal::IsAsyncFunction(), and v8::Utils::OpenDirectHandle().
IsBigInt()
bool v8::Value::IsBigInt () const
Returns true if this value is a bigint.
This is equivalent to `typeof value === 'bigint' in JS.
Definition at line 3607 of file api.cc.
                           {
  return i::IsBigInt(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
IsBigInt64Array()
bool v8::Value::IsBigInt64Array () const
Returns true if this value is a BigInt64Array.
IsBigIntObject()
bool v8::Value::IsBigIntObject () const
Returns true if this value is a BigInt object.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::getInternalPropertiesForPreview().
IsBigUint64Array()
bool v8::Value::IsBigUint64Array () const
Returns true if this value is a BigUint64Array.
IsBoolean()
bool v8::Value::IsBoolean () const
Returns true if this value is boolean.
This is equivalent to `typeof value === 'boolean' in JS.
Definition at line 3646 of file api.cc.
                            {
  return i::IsBoolean(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
IsBooleanObject()
bool v8::Value::IsBooleanObject () const
Returns true if this value is a Boolean object.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::getInternalPropertiesForPreview().
IsDataView()
bool v8::Value::IsDataView () const
Returns true if this value is a DataView.
Definition at line 3588 of file api.cc.
                             {
  auto obj = *Utils::OpenDirectHandle(this);
  return IsJSDataView(obj) || IsJSRabGsabDataView(obj);
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::ValueMirror::create().
IsDate()
bool v8::Value::IsDate () const
Returns true if this value is a Date.
Referenced by v8_inspector::ValueMirror::create().
IsExternal()
bool v8::Value::IsExternal () const
Returns true if this value is an External object.
Definition at line 3650 of file api.cc.
                             {
  i::Tagged<i::Object> obj = *Utils::OpenDirectHandle(this);
  return IsJSExternalObject(obj);
}
References v8::Utils::OpenDirectHandle().
Referenced by v8::External::CheckCast(), and v8_inspector::V8Console::runTask().
IsFalse()
bool v8::Value::IsFalse () const [inline]
Returns true if this value is false.
This is not the same as !BooleanValue(). The latter performs a conversion to boolean, i.e. the result of !Boolean(value) in JS, whereas this checks value === false.
Definition at line 625 of file v8-value.h.
                          {
#if V8_STATIC_ROOTS_BOOL && !defined(V8_ENABLE_CHECKS)
  return QuickIsFalse();
#else
  return FullIsFalse();
#endif
}
References FullIsFalse().
IsFloat16Array()
bool v8::Value::IsFloat16Array () const
Returns true if this value is a Float16Array.
Definition at line 3580 of file api.cc.
                                 {
  auto obj = *Utils::OpenDirectHandle(this);
  return i::IsJSTypedArray(obj) &&
         i::Cast<i::JSTypedArray>(obj)->type() == i::kExternalFloat16Array &&
         Utils::ApiCheck(i::v8_flags.js_float16array, "Value::IsFloat16Array",
                         "Float16Array is not supported");
}
References v8::Utils::ApiCheck(), v8::internal::kExternalFloat16Array, v8::Utils::OpenDirectHandle(), and v8::internal::v8_flags.
IsFloat32Array()
bool v8::Value::IsFloat32Array () const
Returns true if this value is a Float32Array.
IsFloat64Array()
bool v8::Value::IsFloat64Array () const
Returns true if this value is a Float64Array.
IsFunction()
bool v8::Value::IsFunction () const
Returns true if this value is a function.
This is equivalent to `typeof value === 'function' in JS.
Definition at line 3536 of file api.cc.
                             {
  return IsCallable(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::ValueMirror::create(), v8_inspector::ValueMirror::getInternalProperties(), v8_inspector::ValueMirror::getProperties(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8_inspector::V8Console::queryObjectsCallback(), and v8_inspector::V8DebuggerAgentImpl::setBreakpointOnFunctionCall().
IsGeneratorFunction()
bool v8::Value::IsGeneratorFunction () const
Returns true if this value is a Generator function.
Definition at line 3690 of file api.cc.
                                      {
  auto obj = *Utils::OpenDirectHandle(this);
  if (!IsJSFunction(obj)) return false;
  auto func = i::Cast<i::JSFunction>(obj);
  i::DisallowJavascriptExecutionDebugOnly no_execution;
  i::DisallowExceptionsDebugOnly no_exceptions;
  return i::IsGeneratorFunction(func->shared()->kind());
}
References v8::internal::IsGeneratorFunction(), and v8::Utils::OpenDirectHandle().
IsGeneratorObject()
bool v8::Value::IsGeneratorObject () const
Returns true if this value is a Generator object (iterator).
Definition at line 3699 of file api.cc.
                                    {
  return IsJSGeneratorObject(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::ValueMirror::create(), v8_inspector::ValueMirror::getInternalProperties(), and v8_inspector::anonymous_namespace{value-mirror.cc}::getInternalPropertiesForPreview().
IsInt16Array()
bool v8::Value::IsInt16Array () const
Returns true if this value is an Int16Array.
IsInt32()
bool v8::Value::IsInt32 () const
Returns true if this value is a 32-bit signed integer.
Definition at line 3655 of file api.cc.
                          {
  i::Tagged<i::Object> obj = *Utils::OpenDirectHandle(this);
  if (i::IsSmi(obj)) return true;
  if (i::IsNumber(obj)) {
    return i::IsInt32Double(i::Object::NumberValue(i::Cast<i::Number>(obj)));
  }
  return false;
}
References v8::internal::IsInt32Double(), v8::internal::IsNumber(), v8::internal::IsSmi(), v8::internal::Object::NumberValue(), and v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8_inspector::clientMirror(), and v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsValidApiObject().
IsInt32Array()
bool v8::Value::IsInt32Array () const
Returns true if this value is an Int32Array.
IsInt8Array()
bool v8::Value::IsInt8Array () const
Returns true if this value is an Int8Array.
IsMap()
bool v8::Value::IsMap () const
Returns true if this value is a Map.
Referenced by v8_inspector::ValueMirror::create(), and v8::Object::PreviewEntries().
IsMapIterator()
bool v8::Value::IsMapIterator () const
Returns true if this value is a Map Iterator.
Definition at line 3703 of file api.cc.
                                {
  return IsJSMapIterator(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::ValueMirror::create().
IsModuleNamespaceObject()
bool v8::Value::IsModuleNamespaceObject () const
Returns true if the value is a Module Namespace Object.
Definition at line 3715 of file api.cc.
                                          {
  return IsJSModuleNamespace(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::anonymous_namespace{v8-debugger.cc}::MatchPrototypePredicate::Filter().
IsName()
bool v8::Value::IsName () const
Returns true if this value is a symbol or a string.
This is equivalent to `typeof value === 'string' || typeof value === 'symbol' in JS.
Definition at line 3540 of file api.cc.
{ return i::IsName(*Utils::OpenDirectHandle(this)); }
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorSetterCallback().
IsNativeError()
bool v8::Value::IsNativeError () const
Returns true if this value is a NativeError.
Definition at line 3675 of file api.cc.
                                {
  return IsJSError(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::InjectedScript::addExceptionToDetails(), v8_inspector::ValueMirror::create(), v8_inspector::V8RuntimeAgentImpl::getExceptionDetails(), and v8_inspector::InjectedScript::wrapEvaluateResult().
IsNull()
bool v8::Value::IsNull () const [inline]
Returns true if this value is the null value.
See ECMA-262 4.3.11.
This is equivalent to value === null in JS.
Definition at line 565 of file v8-value.h.
                         {
#ifdef V8_ENABLE_CHECKS
  return FullIsNull();
#else
  return QuickIsNull();
#endif
}
References FullIsNull(), and QuickIsNull().
Referenced by v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback().
IsNullOrUndefined()
bool v8::Value::IsNullOrUndefined () const [inline]
Returns true if this value is either the null or the undefined value.
See ECMA-262 4.3.11. and 4.3.12
This is equivalent to value == null in JS.
Definition at line 586 of file v8-value.h.
                                    {
#ifdef V8_ENABLE_CHECKS
  return FullIsNull() || FullIsUndefined();
#else
  return QuickIsNullOrUndefined();
#endif
}
References FullIsNull(), FullIsUndefined(), and QuickIsNullOrUndefined().
IsNumber()
bool v8::Value::IsNumber () const
Returns true if this value is a number.
This is equivalent to `typeof value === 'number' in JS.
Definition at line 3603 of file api.cc.
                           {
  return i::IsNumber(*Utils::OpenDirectHandle(this));
}
References v8::internal::IsNumber(), and v8::Utils::OpenDirectHandle().
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceJSArrayHelper().
IsNumberObject()
bool v8::Value::IsNumberObject () const
Returns true if this value is a Number object.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::getInternalPropertiesForPreview().
IsObject()
bool v8::Value::IsObject () const
Returns true if this value is an object.
Definition at line 3599 of file api.cc.
                           {
  return i::IsJSReceiver(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8::internal::CppGraphBuilderImpl::AddEdge(), v8_inspector::V8InspectorImpl::associateExceptionData(), v8_inspector::V8Debugger::collectionsEntries(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForProxy(), v8_inspector::anonymous_namespace{value-mirror.cc}::doesAttributeHaveObservableSideEffectOnGet(), v8::internal::ExtractEmbedderDataBackref(), v8_inspector::generateCustomPreview(), v8_inspector::V8InspectorImpl::getAssociatedExceptionData(), v8_inspector::anonymous_namespace{value-mirror.cc}::getErrorProperty(), v8_inspector::V8RuntimeAgentImpl::getProperties(), v8_inspector::InspectedContext::InspectedContext(), v8_inspector::anonymous_namespace{value-mirror.cc}::isArrayLike(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::IsFastCApiObjectFastCallback(), v8_inspector::V8Debugger::privateMethods(), v8_inspector::V8RuntimeAgentImpl::queryObjects(), v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl().
IsPrimitive()
bool v8::Value::IsPrimitive () const
Returns true if the value is a primitive.
Definition at line 3531 of file api.cc.
                              {
  auto object = Utils::OpenDirectHandle(this);
  return i::IsPrimitive(*object) && !IsPrivateSymbol(*object);
}
References v8::internal::IsPrimitive(), v8::internal::IsPrivateSymbol(), and v8::Utils::OpenDirectHandle().
IsPromise()
bool v8::Value::IsPromise () const
Returns true if this value is a Promise.
Definition at line 3711 of file api.cc.
                            {
  return IsJSPromise(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::V8RuntimeAgentImpl::awaitPromise(), v8::Promise::Resolver::CheckCast(), v8::Promise::CheckCast(), v8_inspector::ValueMirror::create(), and v8_inspector::anonymous_namespace{value-mirror.cc}::getInternalPropertiesForPreview().
IsProxy()
bool v8::Value::IsProxy () const
Returns true if this value is a JavaScript Proxy.
Definition at line 3611 of file api.cc.
                          {
  return i::IsJSProxy(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8::Proxy::CheckCast(), and v8_inspector::ValueMirror::create().
IsRegExp()
bool v8::Value::IsRegExp () const
Returns true if this value is a RegExp.
Definition at line 3679 of file api.cc.
                           {
  return IsJSRegExp(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::ValueMirror::create().
IsSet()
bool v8::Value::IsSet () const
Returns true if this value is a Set.
Referenced by v8_inspector::ValueMirror::create(), and v8::Object::PreviewEntries().
IsSetIterator()
bool v8::Value::IsSetIterator () const
Returns true if this value is a Set Iterator.
Definition at line 3707 of file api.cc.
                                {
  return IsJSSetIterator(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::ValueMirror::create().
IsSharedArrayBuffer()
bool v8::Value::IsSharedArrayBuffer () const
Returns true if this value is a SharedArrayBuffer.
Definition at line 3593 of file api.cc.
                                      {
  auto obj = *Utils::OpenDirectHandle(this);
  if (!IsJSArrayBuffer(obj)) return false;
  return i::Cast<i::JSArrayBuffer>(obj)->is_shared();
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::ValueMirror::create(), and v8_inspector::anonymous_namespace{value-mirror.cc}::getPropertiesForPreview().
IsString()
bool v8::Value::IsString () const [inline]
Returns true if this value is an instance of the String type.
See ECMA-262 8.4.
This is equivalent to `typeof value === 'string' in JS.
Definition at line 642 of file v8-value.h.
                           {
#ifdef V8_ENABLE_CHECKS
  return FullIsString();
#else
  return QuickIsString();
#endif
}
References FullIsString(), and QuickIsString().
Referenced by v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::descriptionForError(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::firstArgToString(), v8::internal::anonymous_namespace{gc-extension.cc}::ReadProperty(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeMap(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObjectValue(), v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags(), v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap(), v8_inspector::V8ConsoleMessage::wrapArguments(), and v8_inspector::InjectedScript::wrapTable().
IsStringObject()
bool v8::Value::IsStringObject () const
Returns true if this value is a String object.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::getInternalPropertiesForPreview(), and v8_inspector::anonymous_namespace{value-mirror.cc}::getPropertiesForPreview().
IsSymbol()
bool v8::Value::IsSymbol () const
Returns true if this value is a symbol.
This is equivalent to `typeof value === 'symbol' in JS.
Definition at line 3548 of file api.cc.
                           {
  return IsPublicSymbol(*Utils::OpenDirectHandle(this));
}
References v8::internal::IsPublicSymbol(), and v8::Utils::OpenDirectHandle().
IsSymbolObject()
bool v8::Value::IsSymbolObject () const
Returns true if this value is a Symbol object.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::getInternalPropertiesForPreview().
IsTrue()
bool v8::Value::IsTrue () const [inline]
Returns true if this value is true.
This is not the same as BooleanValue(). The latter performs a conversion to boolean, i.e. the result of Boolean(value) in JS, whereas this checks value === true.
Definition at line 608 of file v8-value.h.
                         {
#if V8_STATIC_ROOTS_BOOL && !defined(V8_ENABLE_CHECKS)
  return QuickIsTrue();
#else
  return FullIsTrue();
#endif
}
References FullIsTrue().
IsTypedArray()
bool v8::Value::IsTypedArray () const
Returns true if this value is one of TypedArrays.
Definition at line 3566 of file api.cc.
                               {
  return IsJSTypedArray(*Utils::OpenDirectHandle(this));
}
References v8::Utils::OpenDirectHandle().
Referenced by v8_inspector::ValueMirror::create(), and v8::anonymous_namespace{wasm-js.cc}::GetFirstArgumentAsBytes().
IsUint16Array()
bool v8::Value::IsUint16Array () const
Returns true if this value is an Uint16Array.
IsUint32()
bool v8::Value::IsUint32 () const
Returns true if this value is a 32-bit unsigned integer.
Definition at line 3664 of file api.cc.
                           {
  auto obj = *Utils::OpenDirectHandle(this);
  if (i::IsSmi(obj)) return i::Smi::ToInt(obj) >= 0;
  if (i::IsNumber(obj)) {
    double value = i::Object::NumberValue(i::Cast<i::Number>(obj));
    return !i::IsMinusZero(value) && value >= 0 && value <= i::kMaxUInt32 &&
           value == i::FastUI2D(i::FastD2UI(value));
  }
  return false;
}
References v8::internal::FastD2UI(), v8::internal::FastUI2D(), v8::internal::IsMinusZero(), v8::internal::IsNumber(), v8::internal::IsSmi(), v8::internal::kMaxUInt32, v8::internal::Object::NumberValue(), v8::Utils::OpenDirectHandle(), v8::internal::Smi::ToInt(), and v8::internal::value.
Referenced by v8_inspector::InspectedContext::getInternalType(), v8_inspector::anonymous_namespace{value-mirror.cc}::isArrayLike(), and v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap().
IsUint32Array()
bool v8::Value::IsUint32Array () const
Returns true if this value is an Uint32Array.
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceFastCallback().
IsUint8Array()
bool v8::Value::IsUint8Array () const
Returns true if this value is an Uint8Array.
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CopyStringFastCallback().
IsUint8ClampedArray()
bool v8::Value::IsUint8ClampedArray () const
Returns true if this value is an Uint8ClampedArray.
IsUndefined()
bool v8::Value::IsUndefined () const [inline]
Returns true if this value is the undefined value.
See ECMA-262 4.3.10.
This is equivalent to value === undefined in JS.
Definition at line 544 of file v8-value.h.
                              {
#ifdef V8_ENABLE_CHECKS
  return FullIsUndefined();
#else
  return QuickIsUndefined();
#endif
}
References FullIsUndefined(), and QuickIsUndefined().
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceJSArrayHelper(), v8_inspector::V8SerializationDuplicateTracker::FindKnownSerializedValue(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::firstArgToString(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetAddressType(), and v8_inspector::objectToProtocolValue().
IsWasmMemoryMapDescriptor()
bool v8::Value::IsWasmMemoryMapDescriptor () const
Returns true if this value is a WasmMemoryMapDescriptor.
Definition at line 3635 of file api.cc.
{ return false; }
Referenced by v8::WasmMemoryMapDescriptor::CheckCast().
IsWasmMemoryObject()
bool v8::Value::IsWasmMemoryObject () const
Returns true if this value is a WasmMemoryObject.
Definition at line 3636 of file api.cc.
{ return false; }
Referenced by v8::WasmMemoryObject::CheckCast(), and v8_inspector::ValueMirror::create().
IsWasmModuleObject()
bool v8::Value::IsWasmModuleObject () const
Returns true if this value is a WasmModuleObject.
Definition at line 3637 of file api.cc.
{ return false; }
Referenced by v8::WasmModuleObject::CheckCast(), and v8::internal::anonymous_namespace{runtime-test-wasm.cc}::IsWasmInstantiateAllowed().
IsWasmNull()
bool v8::Value::IsWasmNull () const
Returns true if this value is the WasmNull object.
Definition at line 3638 of file api.cc.
{ return false; }
IsWeakMap()
bool v8::Value::IsWeakMap () const
Returns true if this value is a WeakMap.
Referenced by v8_inspector::ValueMirror::create().
IsWeakRef()
bool v8::Value::IsWeakRef () const
Returns true if this value is a WeakRef.
Referenced by v8_inspector::anonymous_namespace{value-mirror.cc}::getInternalPropertiesForPreview().
IsWeakSet()
bool v8::Value::IsWeakSet () const
Returns true if this value is a WeakSet.
Referenced by v8_inspector::ValueMirror::create().
NumberValue()
Maybe< double > v8::Value::NumberValue (Local< Context > context) const
Returns the equivalent of ToNumber()->Value().
Definition at line 4171 of file api.cc.
                                                             {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsNumber(*obj)) {
    return Just(i::Object::NumberValue(i::Cast<i::Number>(*obj)));
  }
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Value_NumberValue};
  i::DirectHandle<i::Number> num;
  if (!i::Object::ToNumber(i_isolate, obj).ToHandle(&num)) return {};
  return Just(i::Object::NumberValue(*num));
}
References v8::internal::Isolate::Current(), v8::internal::IsNumber(), v8::Just(), v8::internal::Object::NumberValue(), v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{api.cc}::ToHandle(), and v8::internal::ToNumber().
Referenced by v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EnforceUint32(), v8::internal::FastIterateArray(), and v8::internal::GetLength().
QuickIsNull()
bool v8::Value::QuickIsNull () const [inline], [private]
Definition at line 573 of file v8-value.h.
                              {
  using A = internal::Address;
  using I = internal::Internals;
  A obj = internal::ValueHelper::ValueAsAddress(this);
#if V8_STATIC_ROOTS_BOOL
  return I::is_identical(obj, I::StaticReadOnlyRoot::kNullValue);
#else
  if (!I::HasHeapObjectTag(obj)) return false;
  if (I::GetInstanceType(obj) != I::kOddballType) return false;
  return (I::GetOddballKind(obj) == I::kNullOddballKind);
#endif // V8_STATIC_ROOTS_BOOL
}
References v8::internal::A, I, and v8::internal::ValueHelper::ValueAsAddress().
Referenced by FullIsNull(), IsNull(), and QuickIsNullOrUndefined().
QuickIsNullOrUndefined()
bool v8::Value::QuickIsNullOrUndefined () const [inline], [private]
Definition at line 594 of file v8-value.h.
                                         {
#if V8_STATIC_ROOTS_BOOL
  return QuickIsNull() || QuickIsUndefined();
#else
  using A = internal::Address;
  using I = internal::Internals;
  A obj = internal::ValueHelper::ValueAsAddress(this);
  if (!I::HasHeapObjectTag(obj)) return false;
  if (I::GetInstanceType(obj) != I::kOddballType) return false;
  int kind = I::GetOddballKind(obj);
  return kind == I::kNullOddballKind || kind == I::kUndefinedOddballKind;
#endif // V8_STATIC_ROOTS_BOOL
}
References v8::internal::A, I, QuickIsNull(), QuickIsUndefined(), and v8::internal::ValueHelper::ValueAsAddress().
Referenced by IsNullOrUndefined().
QuickIsString()
bool v8::Value::QuickIsString () const [inline], [private]
Definition at line 650 of file v8-value.h.
                                {
  using A = internal::Address;
  using I = internal::Internals;
  A obj = internal::ValueHelper::ValueAsAddress(this);
  if (!I::HasHeapObjectTag(obj)) return false;
#if V8_STATIC_ROOTS_BOOL && !V8_MAP_PACKING
  return I::CheckInstanceMapRange(obj,
                                  I::StaticReadOnlyRoot::kStringMapLowerBound,
                                  I::StaticReadOnlyRoot::kStringMapUpperBound);
#else
  return (I::GetInstanceType(obj) < I::kFirstNonstringType);
#endif // V8_STATIC_ROOTS_BOOL
}
References v8::internal::A, I, and v8::internal::ValueHelper::ValueAsAddress().
Referenced by FullIsString(), and IsString().
QuickIsUndefined()
bool v8::Value::QuickIsUndefined () const [inline], [private]
Definition at line 552 of file v8-value.h.
                                   {
  using A = internal::Address;
  using I = internal::Internals;
  A obj = internal::ValueHelper::ValueAsAddress(this);
#if V8_STATIC_ROOTS_BOOL
  return I::is_identical(obj, I::StaticReadOnlyRoot::kUndefinedValue);
#else
  if (!I::HasHeapObjectTag(obj)) return false;
  if (I::GetInstanceType(obj) != I::kOddballType) return false;
  return (I::GetOddballKind(obj) == I::kUndefinedOddballKind);
#endif // V8_STATIC_ROOTS_BOOL
}
References v8::internal::A, I, and v8::internal::ValueHelper::ValueAsAddress().
Referenced by FullIsUndefined(), IsUndefined(), and QuickIsNullOrUndefined().
SameValue()
bool v8::Value::SameValue (Local< Value > that) const
Definition at line 4253 of file api.cc.
                                             {
  auto self = Utils::OpenDirectHandle(this);
  auto other = Utils::OpenDirectHandle(*that);
  return i::Object::SameValue(*self, *other);
}
References v8::Utils::OpenDirectHandle(), and v8::internal::Object::SameValue().
StrictEquals()
bool v8::Value::StrictEquals (Local< Value > that) const
Definition at line 4247 of file api.cc.
                                                {
  auto self = Utils::OpenDirectHandle(this);
  auto other = Utils::OpenDirectHandle(*that);
  return i::Object::StrictEquals(*self, *other);
}
References v8::Utils::OpenDirectHandle(), and v8::internal::Object::StrictEquals().
ToArrayIndex()
MaybeLocal< Uint32 > v8::Value::ToArrayIndex (Local< Context > context) const
Attempts to convert a string to an array index.
Returns an empty handle if the conversion fails.
Definition at line 4219 of file api.cc.
                                                                   {
  auto self = Utils::OpenDirectHandle(this);
  if (i::IsSmi(*self)) {
    if (i::Smi::ToInt(*self) >= 0) return Utils::Uint32ToLocal(self);
    return {};
  }
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Object_ToArrayIndex};
  i::Isolate* i_isolate = api_scope.i_isolate();
  i::DirectHandle<i::Object> string_obj;
  if (!i::Object::ToString(i_isolate, self).ToHandle(&string_obj)) return {};
  auto str = i::Cast<i::String>(string_obj);
  uint32_t index;
  if (!str->AsArrayIndex(&index)) return {};
  i::DirectHandle<i::Number> value =
      index <= static_cast<uint32_t>(i::Smi::kMaxValue)
          ? direct_handle<i::Number>(i::Smi::FromInt(index), i_isolate)
          : i_isolate->factory()->NewNumber(index);
  return api_scope.Escape(Utils::Uint32ToLocal(value));
}
References v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::index, v8::internal::IsSmi(), v8::internal::Smi::kMaxValue, v8::internal::FactoryBase< Impl >::NewNumber(), v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::Smi::ToInt(), ToString(), and v8::internal::value.
ToBigInt()
MaybeLocal< BigInt > v8::Value::ToBigInt (Local< Context > context) const
Perform the equivalent of BigInt(value) in JS.
Definition at line 3749 of file api.cc.
                                                               {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsBigInt(*obj)) return ToApiHandle<BigInt>(obj);
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Object_ToBigInt};
  i::Isolate* i_isolate = api_scope.i_isolate();
  return api_scope.EscapeMaybe(i::BigInt::FromObject(i_isolate, obj));
}
References v8::Utils::OpenDirectHandle().
ToBoolean()
Local< Boolean > v8::Value::ToBoolean (Isolate * isolate) const
Perform the equivalent of Boolean(value) in JS.
This can never fail.
Definition at line 3781 of file api.cc.
                                                         {
  auto i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  i::DisallowJavascriptExecutionDebugOnly no_execution(i_isolate);
  i::DisallowExceptionsDebugOnly no_exceptions(i_isolate);
  return ToApiHandle<Boolean>(
      i_isolate->factory()->ToBoolean(BooleanValue(v8_isolate)));
}
References BooleanValue(), v8::internal::Isolate::factory(), and v8::internal::FactoryBase< Impl >::ToBoolean().
ToDetailString()
MaybeLocal< String > v8::Value::ToDetailString (Local< Context > context) const
Provide a string representation of this value usable for debugging.
This operation has no observable side effects and will succeed unless e.g. execution is being terminated.
Definition at line 3727 of file api.cc.
                                                                     {
  i::DirectHandle<i::Object> obj = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate;
  if (!context.IsEmpty()) {
    i_isolate = i::Isolate::Current();
  } else if (IsSmi(*obj) || !i::GetIsolateFromHeapObject(
                                i::Cast<i::HeapObject>(*obj), &i_isolate)) {
    i_isolate = i::Isolate::Current();
  }
  if (i::IsString(*obj)) return ToApiHandle<String>(obj);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  return Utils::ToLocal(i::Object::NoSideEffectsToString(i_isolate, obj));
}
References v8::internal::Isolate::Current(), v8::internal::GetIsolateFromHeapObject(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::IsSmi(), v8::internal::Object::NoSideEffectsToString(), and v8::Utils::OpenDirectHandle().
ToInt32()
MaybeLocal< Int32 > v8::Value::ToInt32 (Local< Context > context) const
Perform the equivalent of Number(value) in JS and convert the result to a signed 32-bit integer by performing the steps in https://tc39.es/ecma262/#sec-toint32.
Definition at line 3807 of file api.cc.
                                                             {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsSmi(*obj)) return ToApiHandle<Int32>(obj);
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Object_ToInt32};
  i::Isolate* i_isolate = api_scope.i_isolate();
  return api_scope.EscapeMaybe(
      Utils::ToMaybeLocal(i::Object::ToInt32(i_isolate, obj)).As<Int32>());
}
References v8::internal::IsSmi(), v8::Utils::OpenDirectHandle(), v8::internal::Object::ToInt32(), and v8::Utils::ToMaybeLocal().
ToInteger()
MaybeLocal< Integer > v8::Value::ToInteger (Local< Context > context) const
Perform the equivalent of Number(value) in JS and convert the result to an integer.
Negative values are rounded up, positive values are rounded down. NaN is converted to 0. Infinite values yield undefined results.
Definition at line 3798 of file api.cc.
                                                                 {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsSmi(*obj)) return ToApiHandle<Integer>(obj);
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Object_ToInteger};
  i::Isolate* i_isolate = api_scope.i_isolate();
  return api_scope.EscapeMaybe(
      Utils::ToMaybeLocal(i::Object::ToInteger(i_isolate, obj)).As<Integer>());
}
References v8::internal::IsSmi(), v8::Utils::OpenDirectHandle(), and v8::Utils::ToMaybeLocal().
Referenced by v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ArrayBufferTransfer(), v8::internal::BUILTIN(), v8::internal::ResizeHelper(), and v8::internal::RUNTIME_FUNCTION().
ToNumber()
MaybeLocal< Number > v8::Value::ToNumber (Local< Context > context) const
Perform the equivalent of Number(value) in JS.
Definition at line 3789 of file api.cc.
                                                               {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsNumber(*obj)) return ToApiHandle<Number>(obj);
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Object_ToNumber};
  i::Isolate* i_isolate = api_scope.i_isolate();
  return api_scope.EscapeMaybe(
      Utils::ToMaybeLocal(i::Object::ToNumber(i_isolate, obj)).As<Number>());
}
References v8::internal::IsNumber(), v8::Utils::OpenDirectHandle(), v8::Utils::ToMaybeLocal(), and v8::internal::ToNumber().
Referenced by v8::internal::Object::Add(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceJSArrayHelper(), v8::internal::JSArray::AnythingToArrayLength(), v8::internal::BUILTIN(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::CallToNumberFastCallback(), v8::internal::anonymous_namespace{js-array-buffer.cc}::CanonicalNumericIndexString(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CopyElementsHandleSlow(), v8::internal::JSDateTimeFormat::DateTimeFormat(), v8::internal::DefaultNumberOption(), v8::internal::DoWait(), v8::internal::Object::Equals(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatCommon(), v8::internal::anonymous_namespace{js-date-time-format.cc}::FormatRangeCommon(), v8::internal::JSDateTimeFormat::FormatToParts(), v8::internal::IntlMathematicalValue::From(), v8::internal::GetNumberOptionAsDouble(), v8::internal::anonymous_namespace{js-date-time-format.cc}::HandleDateTimeOthers(), v8::internal::JsonStringifier::InitializeGap(), v8::internal::anonymous_namespace{builtins-string.cc}::IsValidCodePoint(), v8::internal::anonymous_namespace{builtins-string.cc}::NextCodePoint(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::SerializeJSPrimitiveWrapper(), v8::internal::Object::SetDataProperty(), v8::internal::Object::SetPropertyInternal(), v8::internal::temporal::ToIntegerIfIntegral(), v8::internal::temporal::anonymous_namespace{js-temporal-helpers.cc}::ToIntegerWithoutRounding(), and v8::internal::anonymous_namespace{runtime-regexp.cc}::ToUint32().
ToNumeric()
MaybeLocal< Numeric > v8::Value::ToNumeric (Local< Context > context) const
Perform ToNumeric(value) as specified in: https://tc39.es/ecma262/#sec-tonumeric.
Definition at line 3772 of file api.cc.
                                                                 {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsNumeric(*obj)) return ToApiHandle<Numeric>(obj);
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Object_ToNumeric};
  i::Isolate* i_isolate = api_scope.i_isolate();
  return api_scope.EscapeMaybe(
      Utils::ToMaybeLocal(i::Object::ToNumeric(i_isolate, obj)).As<Numeric>());
}
References v8::base::internal::IsNumeric, v8::Utils::OpenDirectHandle(), and v8::Utils::ToMaybeLocal().
Referenced by v8::internal::Object::Compare(), v8::internal::Intl::NumberToLocaleString(), and v8::internal::RUNTIME_FUNCTION().
ToObject()
MaybeLocal< Object > v8::Value::ToObject (Local< Context > context) const
Perform the equivalent of Tagged<Object>(value) in JS.
Definition at line 3741 of file api.cc.
                                                               {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsJSReceiver(*obj)) return ToApiHandle<Object>(obj);
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Object_ToObject};
  i::Isolate* i_isolate = api_scope.i_isolate();
  return api_scope.EscapeMaybe(i::Object::ToObject(i_isolate, obj));
}
References v8::Utils::OpenDirectHandle(), and v8::anonymous_namespace{api.cc}::ToObject().
Referenced by v8::internal::BUILTIN(), v8::internal::Intl::CanonicalizeLocaleList(), v8::internal::CoerceOptionsToObject(), v8::internal::Object::ConvertReceiver(), v8::internal::JSReceiver::DefineProperties(), v8::internal::anonymous_namespace{runtime-object.cc}::DeleteProperty(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPop(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPush(), v8::internal::CallSiteInfo::GetMethodName(), v8::internal::anonymous_namespace{builtins-object.cc}::GetOwnPropertyKeys(), v8::internal::CallSiteInfo::GetTypeName(), v8::internal::JSV8BreakIterator::New(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectDefineAccessor(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::JSReceiver::SetOrCopyDataProperties().
ToPrimitive()
MaybeLocal< Primitive > v8::Value::ToPrimitive (Local< Context > context) const
Perform ToPrimitive(value) as specified in: https://tc39.es/ecma262/#sec-toprimitive.
Definition at line 3762 of file api.cc.
                                                                     {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsPrimitive(*obj)) return ToApiHandle<Primitive>(obj);
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Object_ToPrimitive};
  i::Isolate* i_isolate = api_scope.i_isolate();
  return api_scope.EscapeMaybe(
      Utils::ToMaybeLocal(i::Object::ToPrimitive(i_isolate, obj))
          .As<Primitive>());
}
References v8::internal::IsPrimitive(), v8::Utils::OpenDirectHandle(), and v8::Utils::ToMaybeLocal().
Referenced by v8::internal::Object::Add(), v8::internal::BUILTIN(), v8::internal::Object::Compare(), and v8::internal::anonymous_namespace{runtime-strings.cc}::StringAdd_StringConstant_Internalize().
ToString()
MaybeLocal< String > v8::Value::ToString (Local< Context > context) const
Perform the equivalent of String(value) in JS.
Definition at line 3719 of file api.cc.
                                                               {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsString(*obj)) return ToApiHandle<String>(obj);
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Object_ToString};
  i::Isolate* i_isolate = api_scope.i_isolate();
  return api_scope.EscapeMaybe(i::Object::ToString(i_isolate, obj));
}
References v8::Utils::OpenDirectHandle(), and ToString().
Referenced by v8::internal::Object::Add(), v8::internal::BUILTIN(), v8::internal::anonymous_namespace{intl-objects.cc}::CanonicalizeLanguageTag(), v8::internal::anonymous_namespace{js-array-buffer.cc}::CanonicalNumericIndexString(), v8::internal::ErrorUtils::Construct(), v8::internal::JSRawJson::Create(), v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), v8_inspector::anonymous_namespace{v8-console.cc}::ConsoleHelper::firstArgToString(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatCommon(), v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::GetCapture(), v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::GetCapture(), v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::GetNamedCapture(), v8::internal::anonymous_namespace{runtime-regexp.cc}::VectorBackedMatch::GetNamedCapture(), v8::internal::GetStringOption(), v8::internal::GetStringOrBooleanOption(), v8::internal::anonymous_namespace{messages.cc}::GetStringPropertyOrDefault(), v8::internal::temporal::GetTemporalFractionalSecondDigitsOption(), v8::internal::JsonStringifier::InitializeGap(), v8::internal::JsonStringifier::InitializeReplacer(), v8::internal::Intl::Normalize(), v8::internal::Object::NoSideEffectsToMaybeString(), v8::internal::JSDisplayNames::Of(), v8::internal::MessageHandler::ReportMessage(), v8::internal::Isolate::RunHostImportModuleDynamicallyCallback(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JsonStringifier::SerializeJSPrimitiveWrapper(), v8::internal::anonymous_namespace{runtime-strings.cc}::StringAdd_StringConstant_Internalize(), v8::internal::Intl::SupportedValuesOf(), v8::internal::ErrorUtils::ToString(), v8::String::Utf8Value::Utf8Value(), v8::internal::Compiler::ValidateDynamicCompilationSource(), v8::String::Value::Value(), and v8::internal::ValueSerializer::WriteJSError().
ToUint32()
MaybeLocal< Uint32 > v8::Value::ToUint32 (Local< Context > context) const
Perform the equivalent of Number(value) in JS and convert the result to an unsigned 32-bit integer by performing the steps in https://tc39.es/ecma262/#sec-touint32.
Definition at line 3816 of file api.cc.
                                                               {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsSmi(*obj)) return ToApiHandle<Uint32>(obj);
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_Object_ToUint32};
  i::Isolate* i_isolate = api_scope.i_isolate();
  return api_scope.EscapeMaybe(
      Utils::ToMaybeLocal(i::Object::ToUint32(i_isolate, obj)).As<Uint32>());
}
References v8::internal::IsSmi(), v8::Utils::OpenDirectHandle(), v8::Utils::ToMaybeLocal(), and v8::internal::Object::ToUint32().
TypeOf()
Local< String > v8::Value::TypeOf (v8::Isolate * external_isolate)
Definition at line 4259 of file api.cc.
                                                       {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(external_isolate);
  EnterV8NoScriptNoExceptionScope api_scope(i_isolate);
  ApiRuntimeCallStatsScope rcs_scope(i_isolate, RCCId::kAPI_Value_TypeOf);
  return Utils::ToLocal(
      i::Object::TypeOf(i_isolate, Utils::OpenDirectHandle(this)));
}
References v8::Utils::OpenDirectHandle(), and v8::internal::Object::TypeOf().
Uint32Value()
Maybe< uint32_t > v8::Value::Uint32Value (Local< Context > context) const
Returns the equivalent of ToUint32()->Value().
Definition at line 4207 of file api.cc.
                                                               {
  auto obj = Utils::OpenDirectHandle(this);
  if (i::IsNumber(*obj)) return Just(NumberToUint32(*obj));
  auto i_isolate = i::Isolate::Current();
  EnterV8Scope<> api_scope{i_isolate, context, RCCId::kAPI_Value_Uint32Value};
  i::DirectHandle<i::Object> num;
  if (!i::Object::ToUint32(i_isolate, obj).ToHandle(&num)) return {};
  return Just(IsSmi(*num) ? static_cast<uint32_t>(i::Smi::ToInt(*num))
                          : static_cast<uint32_t>(
                                i::Cast<i::HeapNumber>(*num)->value()));
}
References v8::internal::Isolate::Current(), v8::internal::IsNumber(), v8::internal::IsSmi(), v8::Just(), v8::internal::NumberToUint32(), v8::Utils::OpenDirectHandle(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::Smi::ToInt(), and v8::internal::Object::ToUint32().
Referenced by v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-value.h
/mnt/V8SourceCode/src/api/api.cc