cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl Class Reference
#include <process-heap-statistics.h>
Public Member Functions
void AllocatedObjectSizeIncreased (size_t bytes) final
void AllocatedObjectSizeDecreased (size_t bytes) final
void ResetAllocatedObjectSize (size_t bytes) final
void AllocatedSizeIncreased (size_t bytes) final
void AllocatedSizeDecreased (size_t bytes) final
Private Attributes
size_t object_size_changes_since_last_reset_ = 0
Detailed Description
Definition at line 19 of file process-heap-statistics.h.
Member Function Documentation
AllocatedObjectSizeDecreased()
void cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl::AllocatedObjectSizeDecreased (size_t bytes) [inline], [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 27 of file process-heap-statistics.h.
                                                          {
      ProcessHeapStatisticsUpdater::DecreaseTotalAllocatedObjectSize(bytes);
      object_size_changes_since_last_reset_ -= bytes;
    }
References cppgc::internal::ProcessHeapStatisticsUpdater::DecreaseTotalAllocatedObjectSize(), and object_size_changes_since_last_reset_.
AllocatedObjectSizeIncreased()
void cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl::AllocatedObjectSizeIncreased (size_t bytes) [inline], [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 22 of file process-heap-statistics.h.
                                                          {
      ProcessHeapStatisticsUpdater::IncreaseTotalAllocatedObjectSize(bytes);
      object_size_changes_since_last_reset_ += bytes;
    }
References cppgc::internal::ProcessHeapStatisticsUpdater::IncreaseTotalAllocatedObjectSize(), and object_size_changes_since_last_reset_.
AllocatedSizeDecreased()
void cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl::AllocatedSizeDecreased (size_t bytes) [inline], [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 43 of file process-heap-statistics.h.
                                                    {
      ProcessHeapStatisticsUpdater::DecreaseTotalAllocatedSpace(bytes);
    }
References cppgc::internal::ProcessHeapStatisticsUpdater::DecreaseTotalAllocatedSpace().
AllocatedSizeIncreased()
void cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl::AllocatedSizeIncreased (size_t bytes) [inline], [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 39 of file process-heap-statistics.h.
                                                    {
      ProcessHeapStatisticsUpdater::IncreaseTotalAllocatedSpace(bytes);
    }
References cppgc::internal::ProcessHeapStatisticsUpdater::IncreaseTotalAllocatedSpace().
ResetAllocatedObjectSize()
void cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl::ResetAllocatedObjectSize (size_t bytes) [inline], [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 32 of file process-heap-statistics.h.
                                                      {
      ProcessHeapStatisticsUpdater::DecreaseTotalAllocatedObjectSize(
          object_size_changes_since_last_reset_);
      ProcessHeapStatisticsUpdater::IncreaseTotalAllocatedObjectSize(bytes);
      object_size_changes_since_last_reset_ = bytes;
    }
References cppgc::internal::ProcessHeapStatisticsUpdater::DecreaseTotalAllocatedObjectSize(), cppgc::internal::ProcessHeapStatisticsUpdater::IncreaseTotalAllocatedObjectSize(), and object_size_changes_since_last_reset_.
Member Data Documentation
object_size_changes_since_last_reset_
size_t cppgc::internal::ProcessHeapStatisticsUpdater::AllocationObserverImpl::object_size_changes_since_last_reset_ = 0 [private]
Definition at line 48 of file process-heap-statistics.h.
Referenced by AllocatedObjectSizeDecreased(), AllocatedObjectSizeIncreased(), and ResetAllocatedObjectSize().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/process-heap-statistics.h