v8::base::AtomicValue< T > Class Template Reference
#include <atomic-utils.h>
Classes
struct cast_helper
struct cast_helper< S * >
Public Member Functions
AtomicValue ()
AtomicValue (T initial)
T Value () const
void SetValue (T new_value)
Private Attributes
base::AtomicWord value_
Detailed Description
template<typename T>
class v8::base::AtomicValue< T >
Definition at line 23 of file atomic-utils.h.
Constructor & Destructor Documentation
AtomicValue() [1/2]
template<typename T >
v8::base::AtomicValue< T >::AtomicValue () [inline]
Definition at line 25 of file atomic-utils.h.
: value_(0) {}
AtomicValue() [2/2]
template<typename T >
v8::base::AtomicValue< T >::AtomicValue (T initial) [inline], [explicit]
Definition at line 27 of file atomic-utils.h.
      : value_(cast_helper<T>::to_storage_type(initial)) {}
Member Function Documentation
SetValue()
template<typename T >
void v8::base::AtomicValue< T >::SetValue (T new_value) [inline]
Definition at line 34 of file atomic-utils.h.
                                       {
    base::Release_Store(&value_, cast_helper<T>::to_storage_type(new_value));
  }
References v8::base::Release_Store(), and v8::base::AtomicValue< T >::value_.
Referenced by v8::internal::LazyCompileDispatcher::DoBackgroundWork().
Value()
template<typename T >
T v8::base::AtomicValue< T >::Value () const [inline]
Definition at line 30 of file atomic-utils.h.
                            {
    return cast_helper<T>::to_return_type(base::Acquire_Load(&value_));
  }
References v8::base::Acquire_Load(), v8::base::AtomicValue< T >::cast_helper< S >::to_return_type(), and v8::base::AtomicValue< T >::value_.
Referenced by v8::internal::LazyCompileDispatcher::DoBackgroundWork().
Member Data Documentation
value_
template<typename T >
base::AtomicWord v8::base::AtomicValue< T >::value_ [private]
Definition at line 61 of file atomic-utils.h.
Referenced by v8::base::AtomicValue< T >::SetValue(), and v8::base::AtomicValue< T >::Value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/atomic-utils.h