v8::internal::compiler::turboshaft::FrameStateData::Builder Class Reference
#include <deopt-data.h>
Public Member Functions
void AddParentFrameState (V< FrameState > parent)
void AddInput (MachineType type, OpIndex input)
void AddUnusedRegister ()
void AddDematerializedObjectReference (uint32_t id)
void AddDematerializedObject (uint32_t id, uint32_t field_count)
void AddDematerializedStringConcat (uint32_t id)
void AddDematerializedStringConcatReference (uint32_t id)
void AddArgumentsElements (CreateArgumentsType type)
void AddArgumentsLength ()
void AddRestLength ()
const FrameStateData * AllocateFrameStateData (const FrameStateInfo &info, Zone *zone)
base::Vector< const OpIndex > Inputs ()
bool inlined () const
Private Attributes
base::SmallVector< Instr, 32 > instructions_
base::SmallVector< MachineType, 32 > machine_types_
base::SmallVector< uint32_t, 16 > int_operands_
base::SmallVector< OpIndex, 32 > inputs_
bool inlined_ = false
Detailed Description
Definition at line 34 of file deopt-data.h.
Member Function Documentation
AddArgumentsElements()
void v8::internal::compiler::turboshaft::FrameStateData::Builder::AddArgumentsElements (CreateArgumentsType type) [inline]
Definition at line 72 of file deopt-data.h.
                                                        {
      instructions_.push_back(Instr::kArgumentsElements);
      int_operands_.push_back(static_cast<int>(type));
    }
References instructions_, int_operands_, v8::internal::compiler::turboshaft::FrameStateData::kArgumentsElements, v8::base::SmallVector< T, kSize, Allocator >::push_back(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::ProcessDeoptInput().
AddArgumentsLength()
void v8::internal::compiler::turboshaft::FrameStateData::Builder::AddArgumentsLength () [inline]
Definition at line 77 of file deopt-data.h.
                              {
      instructions_.push_back(Instr::kArgumentsLength);
    }
References instructions_, v8::internal::compiler::turboshaft::FrameStateData::kArgumentsLength, and v8::base::SmallVector< T, kSize, Allocator >::push_back().
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::ProcessDeoptInput().
AddDematerializedObject()
void v8::internal::compiler::turboshaft::FrameStateData::Builder::AddDematerializedObject (uint32_t id, uint32_t field_count) [inline]
Definition at line 56 of file deopt-data.h.
                                                                    {
      instructions_.push_back(Instr::kDematerializedObject);
      int_operands_.push_back(id);
      int_operands_.push_back(field_count);
    }
References instructions_, int_operands_, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedObject, and v8::base::SmallVector< T, kSize, Allocator >::push_back().
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::ProcessDeoptInput().
AddDematerializedObjectReference()
void v8::internal::compiler::turboshaft::FrameStateData::Builder::AddDematerializedObjectReference (uint32_t id) [inline]
Definition at line 51 of file deopt-data.h.
                                                       {
      instructions_.push_back(Instr::kDematerializedObjectReference);
      int_operands_.push_back(id);
    }
References instructions_, int_operands_, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedObjectReference, and v8::base::SmallVector< T, kSize, Allocator >::push_back().
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::ProcessDeoptInput().
AddDematerializedStringConcat()
void v8::internal::compiler::turboshaft::FrameStateData::Builder::AddDematerializedStringConcat (uint32_t id) [inline]
Definition at line 62 of file deopt-data.h.
                                                    {
      instructions_.push_back(Instr::kDematerializedStringConcat);
      int_operands_.push_back(id);
    }
References instructions_, int_operands_, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedStringConcat, and v8::base::SmallVector< T, kSize, Allocator >::push_back().
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildMaybeElidedString().
AddDematerializedStringConcatReference()
void v8::internal::compiler::turboshaft::FrameStateData::Builder::AddDematerializedStringConcatReference (uint32_t id) [inline]
Definition at line 67 of file deopt-data.h.
                                                             {
      instructions_.push_back(Instr::kDematerializedStringConcatReference);
      int_operands_.push_back(id);
    }
References instructions_, int_operands_, v8::internal::compiler::turboshaft::FrameStateData::kDematerializedStringConcatReference, and v8::base::SmallVector< T, kSize, Allocator >::push_back().
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildMaybeElidedString().
AddInput()
void v8::internal::compiler::turboshaft::FrameStateData::Builder::AddInput (MachineType type, OpIndex input) [inline]
Definition at line 41 of file deopt-data.h.
                                                   {
      instructions_.push_back(Instr::kInput);
      machine_types_.push_back(type);
      inputs_.push_back(input);
    }
References inputs_, instructions_, v8::internal::compiler::turboshaft::FrameStateData::kInput, machine_types_, v8::base::SmallVector< T, kSize, Allocator >::push_back(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildMaybeElidedString(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::ProcessDeoptInput().
AddParentFrameState()
void v8::internal::compiler::turboshaft::FrameStateData::Builder::AddParentFrameState (V< FrameState > parent) [inline]
Definition at line 36 of file deopt-data.h.
                                                   {
      DCHECK(inputs_.empty());
      inlined_ = true;
      inputs_.push_back(parent);
    }
References v8::internal::DCHECK(), inlined_, and inputs_.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::BuildFrameStateData(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState().
AddRestLength()
void v8::internal::compiler::turboshaft::FrameStateData::Builder::AddRestLength () [inline]
Definition at line 81 of file deopt-data.h.
{ instructions_.push_back(Instr::kRestLength); }
References instructions_, v8::internal::compiler::turboshaft::FrameStateData::kRestLength, and v8::base::SmallVector< T, kSize, Allocator >::push_back().
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput().
AddUnusedRegister()
void v8::internal::compiler::turboshaft::FrameStateData::Builder::AddUnusedRegister () [inline]
Definition at line 47 of file deopt-data.h.
                             {
      instructions_.push_back(Instr::kUnusedRegister);
    }
References instructions_, v8::internal::compiler::turboshaft::FrameStateData::kUnusedRegister, and v8::base::SmallVector< T, kSize, Allocator >::push_back().
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameStateInput(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::ProcessStateValues().
AllocateFrameStateData()
const FrameStateData* v8::internal::compiler::turboshaft::FrameStateData::Builder::AllocateFrameStateData (const FrameStateInfo & info, Zone * zone) [inline]
Definition at line 83 of file deopt-data.h.
                                                             {
      return zone->New<FrameStateData>(
          FrameStateData{info, zone->CloneVector(base::VectorOf(instructions_)),
                         zone->CloneVector(base::VectorOf(machine_types_)),
                         zone->CloneVector(base::VectorOf(int_operands_))});
    }
References v8::internal::Zone::CloneVector(), instructions_, int_operands_, machine_types_, v8::internal::Zone::New(), and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
inlined()
bool v8::internal::compiler::turboshaft::FrameStateData::Builder::inlined () const [inline]
Definition at line 92 of file deopt-data.h.
{ return inlined_; }
References inlined_.
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
Inputs()
base::Vector<const OpIndex> v8::internal::compiler::turboshaft::FrameStateData::Builder::Inputs () [inline]
Definition at line 91 of file deopt-data.h.
{ return base::VectorOf(inputs_); }
References inputs_, and v8::base::VectorOf().
Referenced by v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::BuildFrameState(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
Member Data Documentation
inlined_
bool v8::internal::compiler::turboshaft::FrameStateData::Builder::inlined_ = false [private]
Definition at line 100 of file deopt-data.h.
Referenced by AddParentFrameState(), and inlined().
inputs_
base::SmallVector<OpIndex, 32> v8::internal::compiler::turboshaft::FrameStateData::Builder::inputs_ [private]
Definition at line 98 of file deopt-data.h.
Referenced by AddInput(), AddParentFrameState(), and Inputs().
instructions_
base::SmallVector<Instr, 32> v8::internal::compiler::turboshaft::FrameStateData::Builder::instructions_ [private]
Definition at line 95 of file deopt-data.h.
Referenced by AddArgumentsElements(), AddArgumentsLength(), AddDematerializedObject(), AddDematerializedObjectReference(), AddDematerializedStringConcat(), AddDematerializedStringConcatReference(), AddInput(), AddRestLength(), AddUnusedRegister(), and AllocateFrameStateData().
int_operands_
base::SmallVector<uint32_t, 16> v8::internal::compiler::turboshaft::FrameStateData::Builder::int_operands_ [private]
Definition at line 97 of file deopt-data.h.
Referenced by AddArgumentsElements(), AddDematerializedObject(), AddDematerializedObjectReference(), AddDematerializedStringConcat(), AddDematerializedStringConcatReference(), and AllocateFrameStateData().
machine_types_
base::SmallVector<MachineType, 32> v8::internal::compiler::turboshaft::FrameStateData::Builder::machine_types_ [private]
Definition at line 96 of file deopt-data.h.
Referenced by AddInput(), and AllocateFrameStateData().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/deopt-data.h