v8::internal::WritableFreeSpace Class Reference
#include <code-memory-access.h>
Public Member Functions
WritableFreeSpace (const WritableFreeSpace &)=delete
WritableFreeSpace & operator= (const WritableFreeSpace &)=delete
~WritableFreeSpace ()
template<typename T , size_t offset>
void WriteHeaderSlot (Tagged< T > value, RelaxedStoreTag) const
template<size_t offset>
void ClearTagged (size_t count) const
base::Address Address () const
int Size () const
bool Executable () const
Static Public Member Functions
static WritableFreeSpace ForNonExecutableMemory (base::Address addr, size_t size)
Private Member Functions
WritableFreeSpace (base::Address addr, size_t size, bool executable)
Private Attributes
const base::Address address_
const int size_
const bool executable_
Friends
class WritableJitPage
Detailed Description
Definition at line 491 of file code-memory-access.h.
Constructor & Destructor Documentation
WritableFreeSpace() [1/2]
v8::internal::WritableFreeSpace::WritableFreeSpace (const WritableFreeSpace &) [delete]
Referenced by ForNonExecutableMemory().
 WritableFreeSpace()
v8::internal::WritableFreeSpace::~WritableFreeSpace () [inline], [default]
WritableFreeSpace() [2/2]
v8::internal::WritableFreeSpace::WritableFreeSpace (base::Address addr, size_t size, bool executable) [inline], [private]
Definition at line 292 of file code-memory-access-inl.h.
    : address_(addr), size_(static_cast<int>(size)), executable_(executable) {}
Member Function Documentation
Address()
base::Address v8::internal::WritableFreeSpace::Address () const [inline]
Definition at line 509 of file code-memory-access.h.
{ return address_; }
References address_.
Referenced by v8::internal::anonymous_namespace{heap.cc}::CreateFillerObjectAtImpl(), v8::internal::Heap::CreateFillerObjectAtRaw(), v8::internal::FreeList::Free(), v8::internal::FreeListManyCached::Free(), and v8::internal::FreeListCategory::Free().
ClearTagged()
template<size_t offset>
template void v8::internal::WritableFreeSpace::ClearTagged< 2 *kTaggedSize > (size_t count) const
Definition at line 733 of file code-memory-access.cc.
                                                      {
  base::Address start = address_ + offset;
  // TODO(v8:13355): add validation before the write.
  MemsetTagged(ObjectSlot(start), Tagged<Object>(kClearedFreeMemoryValue),
               count);
}
References address_, v8::internal::kClearedFreeMemoryValue, and v8::internal::MemsetTagged().
Referenced by v8::internal::anonymous_namespace{heap.cc}::CreateFillerObjectAtImpl().
Executable()
bool v8::internal::WritableFreeSpace::Executable () const [inline]
Definition at line 511 of file code-memory-access.h.
{ return executable_; }
References executable_.
ForNonExecutableMemory()
WritableFreeSpace v8::internal::WritableFreeSpace::ForNonExecutableMemory (base::Address addr, size_t size) [inline], [static]
Definition at line 288 of file code-memory-access-inl.h.
                                                                       {
  return WritableFreeSpace(addr, size, false);
}
References size(), and WritableFreeSpace().
Referenced by v8::internal::Heap::AlignWithFillerBackground(), v8::internal::Heap::CreateFillerObjectAt(), v8::internal::PagedSpaceBase::FreeInternal(), v8::internal::Heap::LeftTrimFixedArray(), v8::internal::Heap::NotifyObjectSizeChange(), v8::internal::Heap::PrecedeWithFillerBackground(), v8::internal::StressConcurrentAllocationTask::RunInternal(), v8::internal::FreeListCategory::SearchForNodeInList(), and v8::internal::anonymous_namespace{sweeper.cc}::ZapDeadObjectsInRange().
operator=()
WritableFreeSpace& v8::internal::WritableFreeSpace::operator= (const WritableFreeSpace &) [delete]
Size()
int v8::internal::WritableFreeSpace::Size () const [inline]
Definition at line 510 of file code-memory-access.h.
{ return size_; }
References size_.
Referenced by v8::internal::anonymous_namespace{heap.cc}::CreateFillerObjectAtImpl(), v8::internal::Heap::CreateFillerObjectAtRaw(), v8::internal::FreeList::Free(), v8::internal::FreeListManyCached::Free(), and v8::internal::FreeListCategory::Free().
WriteHeaderSlot()
template<typename T , size_t offset>
void v8::internal::WritableFreeSpace::WriteHeaderSlot (Tagged< T > value, RelaxedStoreTag) const [inline]
Definition at line 297 of file code-memory-access-inl.h.
                                                               {
  Tagged<HeapObject> object = HeapObject::FromAddress(address_);
  // TODO(v8:13355): add validation before the write.
  if constexpr (offset == HeapObject::kMapOffset) {
    TaggedField<T, offset>::Relaxed_Store_Map_Word(object, value);
  } else {
    TaggedField<T, offset>::Relaxed_Store(object, value);
  }
}
References address_, v8::internal::HeapObject::FromAddress(), v8::internal::HeapObject::kMapOffset, v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store_Map_Word(), and v8::internal::value.
Referenced by v8::internal::HeapObject::SetFillerMap(), v8::internal::FreeSpace::SetNext(), and v8::internal::FreeSpace::SetSize().
Friends And Related Function Documentation
WritableJitPage
friend class WritableJitPage [friend]
Definition at line 520 of file code-memory-access.h.
Member Data Documentation
address_
const base::Address v8::internal::WritableFreeSpace::address_ [private]
Definition at line 516 of file code-memory-access.h.
Referenced by Address(), ClearTagged(), and WriteHeaderSlot().
executable_
const bool v8::internal::WritableFreeSpace::executable_ [private]
Definition at line 518 of file code-memory-access.h.
Referenced by Executable().
size_
const int v8::internal::WritableFreeSpace::size_ [private]
Definition at line 517 of file code-memory-access.h.
Referenced by Size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/code-memory-access.h
/mnt/V8SourceCode/src/common/code-memory-access-inl.h
/mnt/V8SourceCode/src/common/code-memory-access.cc