v8::internal::maglev::RegisterFrameArray< T > Class Template Reference
#include <maglev-register-frame-array.h>
Public Member Functions
RegisterFrameArray (const MaglevCompilationUnit &info)
RegisterFrameArray (const RegisterFrameArray &other) V8_NOEXCEPT=delete
RegisterFrameArray & operator= (const RegisterFrameArray &other) V8_NOEXCEPT=delete
RegisterFrameArray (RegisterFrameArray &&other) V8_NOEXCEPT=default
RegisterFrameArray & operator= (RegisterFrameArray &&other) V8_NOEXCEPT=default
void CopyFrom (const MaglevCompilationUnit &info, const RegisterFrameArray &other, const compiler::BytecodeLivenessState *liveness)
T & operator[] (interpreter::Register reg)
const T & operator[] (interpreter::Register reg) const
Private Member Functions
T * data_begin (int parameter_count) const
Static Private Member Functions
static int DataSize (int register_count, int parameter_count)
Private Attributes
T * frame_start_ = nullptr
Detailed Description
template<typename T>
class v8::internal::maglev::RegisterFrameArray< T >
Definition at line 19 of file maglev-register-frame-array.h.
Constructor & Destructor Documentation
RegisterFrameArray() [1/3]
template<typename T >
v8::internal::maglev::RegisterFrameArray< T >::RegisterFrameArray (const MaglevCompilationUnit & info) [inline], [explicit]
Definition at line 21 of file maglev-register-frame-array.h.
                                                                 {
    // The first local is at index zero, parameters are behind it with
    // negative indices, and the unoptimized frame header is between the two,
    // so the entire frame state including parameters is the number of locals
    // and parameters, plus the number of slots between them.
    constexpr interpreter::Register first_param =
        interpreter::Register::FromParameterIndex(0);
    static_assert(first_param.index() < 0);
    static_assert(interpreter::Register(0).index() == 0);
    constexpr int frame_size_between_params_and_locals = -first_param.index();
    T* frame = info.zone()->AllocateArray<T>(
        info.parameter_count() + frame_size_between_params_and_locals +
        info.register_count());
    // Set frame_start_ to a "butterfly" pointer into the middle of the above
    // Zone-allocated array, so that locals start at zero.
    frame_start_ =
        frame + info.parameter_count() + frame_size_between_params_and_locals;
  }
References v8::internal::Zone::AllocateArray(), v8::internal::maglev::RegisterFrameArray< T >::frame_start_, v8::internal::interpreter::Register::FromParameterIndex(), v8::internal::index, v8::internal::maglev::MaglevCompilationUnit::parameter_count(), v8::internal::maglev::MaglevCompilationUnit::register_count(), and v8::internal::maglev::MaglevCompilationUnit::zone().
RegisterFrameArray() [2/3]
template<typename T >
v8::internal::maglev::RegisterFrameArray< T >::RegisterFrameArray (const RegisterFrameArray< T > & other) [delete]
RegisterFrameArray() [3/3]
template<typename T >
v8::internal::maglev::RegisterFrameArray< T >::RegisterFrameArray (RegisterFrameArray< T > && other) [default]
Member Function Documentation
CopyFrom()
template<typename T >
void v8::internal::maglev::RegisterFrameArray< T >::CopyFrom (const MaglevCompilationUnit & info, const RegisterFrameArray< T > & other, const compiler::BytecodeLivenessState * liveness) [inline]
Definition at line 52 of file maglev-register-frame-array.h.
                                                               {
    interpreter::Register last_param =
        interpreter::Register::FromParameterIndex(info.parameter_count() - 1);
    int end = 1;
    if (!liveness) {
      interpreter::Register last_local =
          interpreter::Register(info.register_count() - 1);
      end = last_local.index();
    }
    // All parameters are live.
    for (int index = last_param.index(); index <= end; ++index) {
      interpreter::Register reg(index);
      (*this)[reg] = other[reg];
    }
    if (liveness) {
      for (int index : *liveness) {
        interpreter::Register reg(index);
        (*this)[reg] = other[reg];
      }
    }
  }
References v8::internal::compiler::end(), v8::internal::interpreter::Register::FromParameterIndex(), v8::internal::interpreter::Register::index(), v8::internal::index, v8::internal::maglev::MaglevCompilationUnit::parameter_count(), v8::internal::ETWJITInterface::Register(), and v8::internal::maglev::MaglevCompilationUnit::register_count().
data_begin()
template<typename T >
T* v8::internal::maglev::RegisterFrameArray< T >::data_begin (int parameter_count) const [inline], [private]
Definition at line 96 of file maglev-register-frame-array.h.
                                           {
    return frame_start_ +
           interpreter::Register::FromParameterIndex(parameter_count - 1)
               .index();
  }
References v8::internal::maglev::RegisterFrameArray< T >::frame_start_, v8::internal::interpreter::Register::FromParameterIndex(), and v8::internal::interpreter::Register::index().
DataSize()
template<typename T >
static int v8::internal::maglev::RegisterFrameArray< T >::DataSize (int register_count, int parameter_count) [inline], [static], [private]
Definition at line 83 of file maglev-register-frame-array.h.
                                                               {
    // The first local is at index zero, parameters are behind it with
    // negative indices, and the unoptimized frame header is between the two,
    // so the entire frame state including parameters is the distance from the
    // last parameter to the last local frame register, plus one to include both
    // ends.
    interpreter::Register last_local =
        interpreter::Register(register_count - 1);
    interpreter::Register last_param =
        interpreter::Register::FromParameterIndex(parameter_count - 1);
    return last_local.index() - last_param.index() + 1;
  }
References v8::internal::interpreter::Register::FromParameterIndex(), v8::internal::interpreter::Register::index(), and v8::internal::ETWJITInterface::Register().
operator=() [1/2]
template<typename T >
RegisterFrameArray& v8::internal::maglev::RegisterFrameArray< T >::operator= (const RegisterFrameArray< T > & other) [delete]
operator=() [2/2]
template<typename T >
RegisterFrameArray& v8::internal::maglev::RegisterFrameArray< T >::operator= (RegisterFrameArray< T > && other) [default]
operator[]() [1/2]
template<typename T >
T& v8::internal::maglev::RegisterFrameArray< T >::operator[] (interpreter::Register reg) [inline]
Definition at line 76 of file maglev-register-frame-array.h.
{ return frame_start_[reg.index()]; }
References v8::internal::maglev::RegisterFrameArray< T >::frame_start_, and v8::internal::interpreter::Register::index().
operator[]() [2/2]
template<typename T >
const T& v8::internal::maglev::RegisterFrameArray< T >::operator[] (interpreter::Register reg) const [inline]
Definition at line 78 of file maglev-register-frame-array.h.
                                                     {
    return frame_start_[reg.index()];
  }
References v8::internal::maglev::RegisterFrameArray< T >::frame_start_, and v8::internal::interpreter::Register::index().
Member Data Documentation
frame_start_
template<typename T >
T* v8::internal::maglev::RegisterFrameArray< T >::frame_start_ = nullptr [private]
Definition at line 107 of file maglev-register-frame-array.h.
Referenced by v8::internal::maglev::RegisterFrameArray< T >::data_begin(), v8::internal::maglev::RegisterFrameArray< T >::operator[](), and v8::internal::maglev::RegisterFrameArray< T >::RegisterFrameArray().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-register-frame-array.h