v8::internal::OrderedHashMapHandler Class Reference
#include <ordered-hash-table.h>
Static Public Member Functions
static MaybeHandle< HeapObject > Add (Isolate *isolate, Handle< HeapObject > table, DirectHandle< Object > key, DirectHandle< Object > value)
static MaybeHandle< OrderedHashMap > AdjustRepresentation (Isolate *isolate, DirectHandle< SmallOrderedHashMap > table)
Detailed Description
Definition at line 755 of file ordered-hash-table.h.
Member Function Documentation
Add()
MaybeHandle< HeapObject > v8::internal::OrderedHashMapHandler::Add (Isolate * isolate, Handle< HeapObject > table, DirectHandle< Object > key, DirectHandle< Object > value) [static]
Definition at line 1244 of file ordered-hash-table.cc.
                                                                               {
  if (IsSmallOrderedHashMap(*table)) {
    Handle<SmallOrderedHashMap> small_map = Cast<SmallOrderedHashMap>(table);
    MaybeHandle<SmallOrderedHashMap> new_map =
        SmallOrderedHashMap::Add(isolate, small_map, key, value);
    if (!new_map.is_null()) return new_map.ToHandleChecked();
    // We couldn't add to the small table, let's migrate to the
    // big table.
    MaybeHandle<OrderedHashMap> table_candidate =
        OrderedHashMapHandler::AdjustRepresentation(isolate, small_map);
    if (!table_candidate.ToHandle(&table)) {
      return table_candidate;
    }
  }
  DCHECK(IsOrderedHashMap(*table));
  return OrderedHashMap::Add(isolate, Cast<OrderedHashMap>(table), key, value);
}
References v8::bigint::Add(), DCHECK, v8::internal::MaybeHandle< T >::is_null(), v8::internal::key, v8::internal::MaybeHandle< T >::ToHandle(), v8::internal::MaybeHandle< T >::ToHandleChecked(), and v8::internal::value.
AdjustRepresentation()
MaybeHandle< OrderedHashMap > v8::internal::OrderedHashMapHandler::AdjustRepresentation (Isolate * isolate, DirectHandle< SmallOrderedHashMap > table) [static]
Definition at line 1165 of file ordered-hash-table.cc.
                                                               {
  MaybeHandle<OrderedHashMap> new_table_candidate =
      OrderedHashMap::Allocate(isolate, OrderedHashTableMinSize);
  Handle<OrderedHashMap> new_table;
  if (!new_table_candidate.ToHandle(&new_table)) {
    return new_table_candidate;
  }
  // TODO(gsathya): Optimize the lookup to not re calc offsets. Also,
  // unhandlify this code as we preallocate the new backing store with
  // the proper capacity.
  for (InternalIndex entry : table->IterateEntries()) {
    DirectHandle<Object> key(table->KeyAt(entry), isolate);
    if (IsTheHole(*key, isolate)) continue;
    DirectHandle<Object> value(
        table->GetDataEntry(entry.as_int(), SmallOrderedHashMap::kValueIndex),
        isolate);
    new_table_candidate = OrderedHashMap::Add(isolate, new_table, key, value);
    if (!new_table_candidate.ToHandle(&new_table)) {
      return new_table_candidate;
    }
  }
  return new_table_candidate;
}
References v8::bigint::Add(), v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::internal::key, v8::internal::MaybeHandle< T >::ToHandle(), and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/ordered-hash-table.h
/mnt/V8SourceCode/src/objects/ordered-hash-table.cc