v8_inspector::EvaluateCallback Class Reference
#include <injected-script.h>
Public Member Functions
virtual ~EvaluateCallback ()=default
Static Public Member Functions
static void sendSuccess (std::weak_ptr< EvaluateCallback > callback, InjectedScript *injectedScript, std::unique_ptr< protocol::Runtime::RemoteObject > result, std::unique_ptr< protocol::Runtime::ExceptionDetails > exceptionDetails)
static void sendFailure (std::weak_ptr< EvaluateCallback > callback, InjectedScript *injectedScript, const protocol::DispatchResponse &response)
Private Member Functions
virtual void sendSuccess (std::unique_ptr< protocol::Runtime::RemoteObject > result, std::unique_ptr< protocol::Runtime::ExceptionDetails > exceptionDetails)=0
virtual void sendFailure (const protocol::DispatchResponse &response)=0
Detailed Description
Definition at line 57 of file injected-script.h.
Constructor & Destructor Documentation
 EvaluateCallback()
virtual v8_inspector::EvaluateCallback::~EvaluateCallback () [virtual], [default]
Member Function Documentation
sendFailure() [1/2]
virtual void v8_inspector::EvaluateCallback::sendFailure (const protocol::DispatchResponse & response) [private], [pure virtual]
Implemented in v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::EvaluateCallbackWrapper< ProtocolCallback >.
sendFailure() [2/2]
void v8_inspector::EvaluateCallback::sendFailure (std::weak_ptr< EvaluateCallback > callback, InjectedScript * injectedScript, const protocol::DispatchResponse & response) [static]
Definition at line 86 of file injected-script.cc.
                                                                             {
  std::shared_ptr<EvaluateCallback> cb = callback.lock();
  if (!cb) return;
  injectedScript->deleteEvaluateCallback(cb);
  CHECK_EQ(cb.use_count(), 1);
  cb->sendFailure(response);
}
References CHECK_EQ, and v8_inspector::InjectedScript::deleteEvaluateCallback().
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::add(), v8_inspector::InjectedScript::addPromiseCallback(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::InjectedScript::discardEvaluateCallbacks(), v8_inspector::PromiseHandlerTracker::sendFailure(), and v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback().
sendSuccess() [1/2]
virtual void v8_inspector::EvaluateCallback::sendSuccess (std::unique_ptr< protocol::Runtime::RemoteObject > result, std::unique_ptr< protocol::Runtime::ExceptionDetails > exceptionDetails) [private], [pure virtual]
Implemented in v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::EvaluateCallbackWrapper< ProtocolCallback >.
sendSuccess() [2/2]
void v8_inspector::EvaluateCallback::sendSuccess (std::weak_ptr< EvaluateCallback > callback, InjectedScript * injectedScript, std::unique_ptr< protocol::Runtime::RemoteObject > result, std::unique_ptr< protocol::Runtime::ExceptionDetails > exceptionDetails) [static]
Definition at line 74 of file injected-script.cc.
                                                                     {
  std::shared_ptr<EvaluateCallback> cb = callback.lock();
  if (!cb) return;
  injectedScript->deleteEvaluateCallback(cb);
  CHECK_EQ(cb.use_count(), 1);
  cb->sendSuccess(std::move(result), std::move(exceptionDetails));
}
References CHECK_EQ, v8_inspector::InjectedScript::deleteEvaluateCallback(), and v8::base::internal::result.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), and v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/injected-script.h
/mnt/V8SourceCode/src/inspector/injected-script.cc