v8::ModuleRequest Class Reference
#include <v8-script.h>
Public Member Functions
Local< String > GetSpecifier () const
Returns the module specifier for this ModuleRequest.
ModuleImportPhase GetPhase () const
Returns the module import phase for this ModuleRequest.
int GetSourceOffset () const
Returns the source code offset of this module request.
Local< FixedArray > GetImportAttributes () const
Contains the import attributes for this request in the form: [key1, value1, source_offset1, key2, value2, source_offset2, ...].
Local< FixedArray > GetImportAssertions () const
Static Public Member Functions
static ModuleRequest * Cast (Data *data)
Static Private Member Functions
static void CheckCast (Data *obj)
Detailed Description
Definition at line 125 of file v8-script.h.
Member Function Documentation
Cast()
ModuleRequest * v8::ModuleRequest::Cast (Data * data) [inline], [static]
Definition at line 936 of file v8-script.h.
                                             {
#ifdef V8_ENABLE_CHECKS
  CheckCast(data);
#endif
  return reinterpret_cast<ModuleRequest*>(data);
}
CheckCast()
void v8::ModuleRequest::CheckCast (v8::Data * that) [static], [private]
Definition at line 3910 of file api.cc.
                                            {
  auto obj = Utils::OpenDirectHandle(that);
  Utils::ApiCheck(i::IsModuleRequest(*obj), "v8::ModuleRequest::Cast",
                  "Value is not a ModuleRequest");
}
References v8::Utils::ApiCheck(), and v8::Utils::OpenDirectHandle().
GetImportAssertions()
Local<FixedArray> v8::ModuleRequest::GetImportAssertions () const [inline]
Definition at line 159 of file v8-script.h.
                                                {
    return GetImportAttributes();
  }
GetImportAttributes()
Local< FixedArray > v8::ModuleRequest::GetImportAttributes () const
Contains the import attributes for this request in the form: [key1, value1, source_offset1, key2, value2, source_offset2, ...].
The keys and values are of type v8::String, and the source offsets are of type Int32. Use Module::SourceOffsetToLocation to convert the source offsets to Locations with line/column numbers.
All attributes present in the module request will be supplied in this list, regardless of whether they are supported by the host. Per https://tc39.es/proposal-import-attributes/#sec-hostgetsupportedimportattributes, hosts are expected to throw for attributes that they do not support (as opposed to, for example, ignoring them).
Definition at line 2129 of file api.cc.
                                                           {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  return ToApiHandle<FixedArray>(
      i::direct_handle(self->import_attributes(), i_isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
GetPhase()
ModuleImportPhase v8::ModuleRequest::GetPhase () const
Returns the module import phase for this ModuleRequest.
Definition at line 2120 of file api.cc.
                                                {
  auto self = Utils::OpenDirectHandle(this);
  return self->phase();
}
References v8::Utils::OpenDirectHandle().
GetSourceOffset()
int v8::ModuleRequest::GetSourceOffset () const
Returns the source code offset of this module request.
Use Module::SourceOffsetToLocation to convert this to line/column numbers.
Definition at line 2125 of file api.cc.
                                         {
  return Utils::OpenDirectHandle(this)->position();
}
References v8::Utils::OpenDirectHandle().
GetSpecifier()
Local< String > v8::ModuleRequest::GetSpecifier () const
Returns the module specifier for this ModuleRequest.
Definition at line 2114 of file api.cc.
                                                {
  auto self = Utils::OpenDirectHandle(this);
  i::Isolate* i_isolate = i::Isolate::Current();
  return ToApiHandle<String>(i::direct_handle(self->specifier(), i_isolate));
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), and v8::Utils::OpenDirectHandle().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-script.h
/mnt/V8SourceCode/src/api/api.cc