v8::internal::FreeList::FreeListCategoryIterator Class Reference
#include <free-list.h>
Public Member Functions
FreeListCategoryIterator (FreeList *free_list, FreeListCategoryType type)
bool HasNext () const
FreeListCategory * Next ()
Private Attributes
FreeListCategory * current_
Detailed Description
Definition at line 222 of file free-list.h.
Constructor & Destructor Documentation
FreeListCategoryIterator()
v8::internal::FreeList::FreeListCategoryIterator::FreeListCategoryIterator (FreeList * free_list, FreeListCategoryType type) [inline]
Definition at line 224 of file free-list.h.
        : current_(free_list->categories_[type]) {}
Member Function Documentation
HasNext()
bool v8::internal::FreeList::FreeListCategoryIterator::HasNext () const [inline]
Definition at line 227 of file free-list.h.
{ return current_ != nullptr; }
References current_.
Referenced by Next(), v8::internal::FreeList::PrintCategories(), and v8::internal::FreeList::SearchForNodeInList().
Next()
FreeListCategory* v8::internal::FreeList::FreeListCategoryIterator::Next () [inline]
Definition at line 229 of file free-list.h.
                             {
      DCHECK(HasNext());
      FreeListCategory* tmp = current_;
      current_ = current_->next();
      return tmp;
    }
References current_, v8::internal::DCHECK(), HasNext(), and v8::internal::FreeListCategory::next().
Referenced by v8::internal::FreeList::PrintCategories(), and v8::internal::FreeList::SearchForNodeInList().
Member Data Documentation
current_
FreeListCategory* v8::internal::FreeList::FreeListCategoryIterator::current_ [private]
Definition at line 237 of file free-list.h.
Referenced by HasNext(), and Next().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/free-list.h