v8::internal::torque::Grammar Class Reference
#include <earley-parser.h>
Public Types
using PatternFunction = Lexer::PatternFunction
Public Member Functions
Grammar (Symbol *start)
std::optional< ParseResult > Parse (const std::string &input)
Protected Member Functions
Symbol * Token (const std::string &s)
Symbol * Pattern (PatternFunction pattern)
void SetWhitespace (PatternFunction ws)
Symbol * NewSymbol (std::initializer_list< Rule > rules={})
Symbol * Sequence (std::vector< Symbol * > symbols)
template<class T , class Result = T>
Symbol * TryOrDefault (Symbol *s)
template<class T >
Symbol * NonemptyList (Symbol *element, std::optional< Symbol * > separator={})
template<class T >
Symbol * List (Symbol *element, std::optional< Symbol * > separator={})
template<class T >
Symbol * Optional (Symbol *x)
Symbol * CheckIf (Symbol *x)
Lexer & lexer ()
Static Protected Member Functions
static V8_EXPORT_PRIVATE bool MatchChar (int(*char_class)(int), InputPosition *pos)
static V8_EXPORT_PRIVATE bool MatchChar (bool(*char_class)(char), InputPosition *pos)
static V8_EXPORT_PRIVATE bool MatchAnyChar (InputPosition *pos)
static V8_EXPORT_PRIVATE bool MatchString (const char *s, InputPosition *pos)
static std::optional< ParseResult > YieldMatchedInput (ParseResultIterator *child_results)
template<class T , T value>
static std::optional< ParseResult > YieldIntegralConstant (ParseResultIterator *child_results)
template<class T >
static std::optional< ParseResult > YieldDefaultValue (ParseResultIterator *child_results)
template<class From , class To >
static std::optional< ParseResult > CastParseResult (ParseResultIterator *child_results)
template<class T >
static std::optional< ParseResult > MakeSingletonVector (ParseResultIterator *child_results)
template<class T >
static std::optional< ParseResult > MakeExtendedVector (ParseResultIterator *child_results)
Private Attributes
Lexer lexer_
std::vector< std::unique_ptr< Symbol > > generated_symbols_
Symbol * start_
Detailed Description
Definition at line 416 of file earley-parser.h.
Member Typedef Documentation
PatternFunction
using v8::internal::torque::Grammar::PatternFunction = Lexer::PatternFunction
Definition at line 418 of file earley-parser.h.
Constructor & Destructor Documentation
Grammar()
v8::internal::torque::Grammar::Grammar (Symbol * start) [inline], [explicit]
Definition at line 420 of file earley-parser.h.
: start_(start) {}
Member Function Documentation
CastParseResult()
template<class From , class To >
static std::optional<ParseResult> v8::internal::torque::Grammar::CastParseResult (ParseResultIterator * child_results) [inline], [static], [protected]
Definition at line 476 of file earley-parser.h.
                                          {
    To result = child_results->NextAs<From>();
    return ParseResult{std::move(result)};
  }
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
CheckIf()
Symbol* v8::internal::torque::Grammar::CheckIf (Symbol * x) [inline], [protected]
Definition at line 530 of file earley-parser.h.
                             {
    return NewSymbol({Rule({x}, YieldIntegralConstant<bool, true>),
                      Rule({}, YieldIntegralConstant<bool, false>)});
  }
References NewSymbol().
lexer()
Lexer& v8::internal::torque::Grammar::lexer () [inline], [protected]
Definition at line 535 of file earley-parser.h.
{ return lexer_; }
References lexer_.
Referenced by Parse().
List()
template<class T >
Symbol* v8::internal::torque::Grammar::List (Symbol * element, std::optional< Symbol * > separator = {}) [inline], [protected]
Definition at line 521 of file earley-parser.h.
                                                                 {}) {
    return TryOrDefault<std::vector<T>>(NonemptyList<T>(element, separator));
  }
MakeExtendedVector()
template<class T >
static std::optional<ParseResult> v8::internal::torque::Grammar::MakeExtendedVector (ParseResultIterator * child_results) [inline], [static], [protected]
Definition at line 500 of file earley-parser.h.
                                          {
    std::vector<T> l = child_results->NextAs<std::vector<T>>();
    T x = child_results->NextAs<T>();
    l.push_back(std::move(x));
    return ParseResult{std::move(l)};
  }
References v8::internal::compiler::turboshaft::l, and v8::internal::torque::ParseResultIterator::NextAs().
MakeSingletonVector()
template<class T >
static std::optional<ParseResult> v8::internal::torque::Grammar::MakeSingletonVector (ParseResultIterator * child_results) [inline], [static], [protected]
Definition at line 491 of file earley-parser.h.
                                          {
    T x = child_results->NextAs<T>();
    std::vector<T> result;
    result.push_back(std::move(x));
    return ParseResult{std::move(result)};
  }
References v8::internal::torque::ParseResultIterator::NextAs(), and v8::base::internal::result.
MatchAnyChar()
bool v8::internal::torque::Grammar::MatchAnyChar (InputPosition * pos) [static], [protected]
Definition at line 315 of file earley-parser.cc.
                                             {
  return MatchChar([](char c) { return true; }, pos);
}
References MatchChar().
Referenced by v8::internal::torque::ls::JsonGrammar::MatchStringLiteral().
MatchChar() [1/2]
bool v8::internal::torque::Grammar::MatchChar (bool(*)(char) char_class, InputPosition * pos) [static], [protected]
Definition at line 296 of file earley-parser.cc.
                                                                    {
  if (**pos && char_class(**pos)) {
    ++*pos;
    return true;
  }
  return false;
}
MatchChar() [2/2]
DISABLE_CFI_ICALL bool v8::internal::torque::Grammar::MatchChar (int(*)(int) char_class, InputPosition * pos) [static], [protected]
Definition at line 287 of file earley-parser.cc.
                                                                  {
  if (**pos && char_class(static_cast<unsigned char>(**pos))) {
    ++*pos;
    return true;
  }
  return false;
}
Referenced by MatchAnyChar(), v8::internal::torque::ls::JsonGrammar::MatchDecimalLiteral(), v8::internal::torque::ls::JsonGrammar::MatchHexLiteral(), v8::internal::torque::ls::JsonGrammar::MatchStringLiteral(), and v8::internal::torque::ls::JsonGrammar::MatchWhitespace().
MatchString()
bool v8::internal::torque::Grammar::MatchString (const char * s, InputPosition * pos) [static], [protected]
Definition at line 305 of file earley-parser.cc.
                                                           {
  InputPosition current = *pos;
  for (; *s != 0; ++s, ++current) {
    if (*s != *current) return false;
  }
  *pos = current;
  return true;
}
Referenced by v8::internal::torque::ls::JsonGrammar::MatchDecimalLiteral(), v8::internal::torque::ls::JsonGrammar::MatchHexLiteral(), and v8::internal::torque::ls::JsonGrammar::MatchStringLiteral().
NewSymbol()
Symbol* v8::internal::torque::Grammar::NewSymbol (std::initializer_list< Rule > rules = {}) [inline], [protected]
Definition at line 434 of file earley-parser.h.
                                                      {}) {
    auto symbol = std::make_unique<Symbol>(rules);
    Symbol* result = symbol.get();
    generated_symbols_.push_back(std::move(symbol));
    return result;
  }
Referenced by CheckIf(), Sequence(), and TryOrDefault().
NonemptyList()
template<class T >
Symbol* v8::internal::torque::Grammar::NonemptyList (Symbol * element, std::optional< Symbol * > separator = {}) [inline], [protected]
Definition at line 511 of file earley-parser.h.
                                                                         {}) {
    Symbol* list = NewSymbol();
    *list = {Rule({element}, MakeSingletonVector<T>),
             separator
                 ? Rule({list, *separator, element}, MakeExtendedVector<T>)
                 : Rule({list, element}, MakeExtendedVector<T>)};
    return list;
  }
Optional()
template<class T >
Symbol* v8::internal::torque::Grammar::Optional (Symbol * x) [inline], [protected]
Definition at line 526 of file earley-parser.h.
                              {
    return TryOrDefault<std::optional<T>, T>(x);
  }
Parse()
std::optional<ParseResult> v8::internal::torque::Grammar::Parse (const std::string & input) [inline]
Definition at line 422 of file earley-parser.h.
                                                         {
    LexerResult tokens = lexer().RunLexer(input);
    return ParseTokens(start_, tokens);
  }
References lexer(), v8::internal::torque::ParseTokens(), v8::internal::torque::Lexer::RunLexer(), and start_.
Referenced by v8::internal::torque::ls::ParseJson().
Pattern()
Symbol* v8::internal::torque::Grammar::Pattern (PatternFunction pattern) [inline], [protected]
Definition at line 429 of file earley-parser.h.
{ return lexer_.Pattern(pattern); }
References lexer_, and v8::internal::torque::Lexer::Pattern().
Sequence()
Symbol* v8::internal::torque::Grammar::Sequence (std::vector< Symbol * > symbols) [inline], [protected]
Definition at line 459 of file earley-parser.h.
                                               {
    return NewSymbol({Rule(std::move(symbols))});
  }
References NewSymbol().
SetWhitespace()
void v8::internal::torque::Grammar::SetWhitespace (PatternFunction ws) [inline], [protected]
Definition at line 430 of file earley-parser.h.
{ lexer_.SetWhitespace(ws); }
References lexer_, and v8::internal::torque::Lexer::SetWhitespace().
Referenced by v8::internal::torque::ls::JsonGrammar::JsonGrammar().
Token()
Symbol* v8::internal::torque::Grammar::Token (const std::string & s) [inline], [protected]
Definition at line 428 of file earley-parser.h.
{ return lexer_.Token(s); }
References lexer_, and v8::internal::torque::Lexer::Token().
TryOrDefault()
template<class T , class Result = T>
Symbol* v8::internal::torque::Grammar::TryOrDefault (Symbol * s) [inline], [protected]
Definition at line 485 of file earley-parser.h.
                                  {
    return NewSymbol({Rule({s}, CastParseResult<Result, T>),
                      Rule({}, YieldDefaultValue<T>)});
  }
References NewSymbol().
YieldDefaultValue()
template<class T >
static std::optional<ParseResult> v8::internal::torque::Grammar::YieldDefaultValue (ParseResultIterator * child_results) [inline], [static], [protected]
Definition at line 470 of file earley-parser.h.
                                          {
    return ParseResult{T{}};
  }
YieldIntegralConstant()
template<class T , T value>
static std::optional<ParseResult> v8::internal::torque::Grammar::YieldIntegralConstant (ParseResultIterator * child_results) [inline], [static], [protected]
Definition at line 464 of file earley-parser.h.
                                          {
    return ParseResult{value};
  }
References v8::internal::value.
YieldMatchedInput()
static std::optional<ParseResult> v8::internal::torque::Grammar::YieldMatchedInput (ParseResultIterator * child_results) [inline], [static], [protected]
Definition at line 452 of file earley-parser.h.
                                          {
    return ParseResult{child_results->matched_input().ToString()};
  }
References v8::internal::torque::ParseResultIterator::matched_input(), and v8::internal::torque::MatchedInput::ToString().
Member Data Documentation
generated_symbols_
std::vector<std::unique_ptr<Symbol> > v8::internal::torque::Grammar::generated_symbols_ [private]
Definition at line 539 of file earley-parser.h.
lexer_
Lexer v8::internal::torque::Grammar::lexer_ [private]
Definition at line 538 of file earley-parser.h.
Referenced by lexer(), Pattern(), SetWhitespace(), and Token().
start_
Symbol* v8::internal::torque::Grammar::start_ [private]
Definition at line 540 of file earley-parser.h.
Referenced by Parse().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/earley-parser.h
/mnt/V8SourceCode/src/torque/earley-parser.cc