v8::internal::MemoryChunkMetadata Class Reference
#include <memory-chunk-metadata.h>
Public Member Functions
MemoryChunkMetadata (Heap *heap, BaseSpace *space, size_t chunk_size, Address area_start, Address area_end, VirtualMemory reservation)
~MemoryChunkMetadata ()
Address ChunkAddress () const
Address MetadataAddress () const
size_t Offset (Address a) const
size_t size () const
void set_size (size_t size)
Address area_start () const
Address area_end () const
void set_area_end (Address area_end)
size_t area_size () const
Heap * heap () const
BaseSpace * owner () const
void set_owner (BaseSpace *space)
bool InSharedSpace () const
bool InTrustedSpace () const
bool IsWritable () const
bool IsMutablePageMetadata () const
bool Contains (Address addr) const
bool ContainsLimit (Address addr) const
size_t wasted_memory () const
void add_wasted_memory (size_t waste)
size_t allocated_bytes () const
Address HighWaterMark () const
VirtualMemory * reserved_memory ()
void ResetAllocationStatistics ()
void IncreaseAllocatedBytes (size_t bytes)
void DecreaseAllocatedBytes (size_t bytes)
MemoryChunk * Chunk ()
const MemoryChunk * Chunk () const
Static Public Member Functions
static MemoryChunkMetadata * FromAddress (Address a)
static MemoryChunkMetadata * FromHeapObject (Tagged< HeapObject > o)
static MemoryChunkMetadata * FromHeapObject (const HeapObjectLayout *o)
static void UpdateHighWaterMark (Address mark)
Protected Attributes
VirtualMemory reservation_
size_t allocated_bytes_
size_t wasted_memory_ = 0
std::atomic< intptr_t > high_water_mark_
size_t size_
Address area_end_
Heap * heap_
Address area_start_
std::atomic< BaseSpace * > owner_
Static Private Member Functions
static constexpr intptr_t HeapOffset ()
static constexpr intptr_t AreaStartOffset ()
Friends
class debug_helper_internal::ReadStringVisitor
class CodeStubAssembler
class MacroAssembler
Detailed Description
Definition at line 32 of file memory-chunk-metadata.h.
Constructor & Destructor Documentation
MemoryChunkMetadata()
v8::internal::MemoryChunkMetadata::MemoryChunkMetadata (Heap * heap, BaseSpace * space, size_t chunk_size, Address area_start, Address area_end, VirtualMemory reservation)
Definition at line 16 of file memory-chunk-metadata.cc.
    : reservation_(std::move(reservation)),
      allocated_bytes_(area_end - area_start),
      high_water_mark_(area_start -
                       MemoryChunk::FromAddress(area_start)->address()),
      size_(chunk_size),
      area_end_(area_end),
      heap_(heap),
      area_start_(area_start),
      owner_(space) {}
 MemoryChunkMetadata()
v8::internal::MemoryChunkMetadata::~MemoryChunkMetadata ()
Definition at line 30 of file memory-chunk-metadata.cc.
                                          {
#ifdef V8_ENABLE_SANDBOX
  MemoryChunk::ClearMetadataPointer(this);
#endif
}
Member Function Documentation
add_wasted_memory()
void v8::internal::MemoryChunkMetadata::add_wasted_memory (size_t waste) [inline]
Definition at line 100 of file memory-chunk-metadata.h.
{ wasted_memory_ += waste; }
References wasted_memory_.
Referenced by v8::internal::FreeList::EvictFreeListItems(), v8::internal::FreeList::Free(), and v8::internal::FreeListManyCached::Free().
allocated_bytes()
size_t v8::internal::MemoryChunkMetadata::allocated_bytes () const [inline]
Definition at line 101 of file memory-chunk-metadata.h.
{ return allocated_bytes_; }
References allocated_bytes_.
Referenced by v8::internal::MarkCompactCollector::AddEvacuationCandidate(), v8::internal::PagedSpaceBase::AddPageImpl(), v8::internal::OldSpace::AddPromotedPage(), v8::internal::PageMetadata::AvailableInFreeListFromAllocatedBytes(), v8::internal::Sweeper::ClearMarkBitsAndHandleLivenessStatistics(), DecreaseAllocatedBytes(), v8::internal::Sweeper::PrepareToBeIteratedPromotedPage(), v8::internal::HeapLayoutTracer::PrintMemoryChunk(), v8::internal::PagedSpaceBase::RefineAllocatedBytesAfterSweeping(), v8::internal::PagedSpaceBase::RemovePage(), v8::internal::MarkCompactCollector::ResetAndRelinkBlackAllocatedPage(), and v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run().
area_end()
Address v8::internal::MemoryChunkMetadata::area_end () const [inline]
Definition at line 62 of file memory-chunk-metadata.h.
{ return area_end_; }
References area_end_.
Referenced by v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject(), area_size(), v8::internal::LargePageMetadata::ClearOutOfLiveRangeSlots(), Contains(), ContainsLimit(), v8::internal::ReadOnlyHeapImageDeserializer::DeserializeSegment(), v8::internal::ReadOnlySpace::EnsureSpaceForAllocation(), v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::FindBasePtr(), v8::internal::ReadOnlyPageMetadata::OffsetToAddress(), v8::internal::SemiSpace::page_high(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::MemoryAllocator::PartialFreeMemory(), v8::internal::Sweeper::RawSweep(), set_area_end(), v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::SweepPage(), and v8::internal::anonymous_namespace{sweeper.cc}::ZapDeadObjectsOnPage().
area_size()
size_t v8::internal::MemoryChunkMetadata::area_size () const [inline]
Definition at line 65 of file memory-chunk-metadata.h.
                           {
    return static_cast<size_t>(area_end() - area_start());
  }
References area_end(), and area_start().
Referenced by v8::internal::Isolate::AddCodeMemoryChunk(), v8::internal::MarkCompactCollector::AddEvacuationCandidate(), v8::internal::PagedSpaceBase::AddPageImpl(), v8::internal::Sweeper::AddPromotedPage(), v8::internal::OldSpace::AddPromotedPage(), v8::internal::SemiSpace::AllocateFreshPage(), v8::internal::LargeObjectSpace::AllocateLargePage(), v8::internal::PageMetadata::AvailableInFreeListFromAllocatedBytes(), DecreaseAllocatedBytes(), v8::internal::ReadOnlySpace::EnsureSpaceForAllocation(), IncreaseAllocatedBytes(), v8::internal::PagedSpaceForNewSpace::InitializePage(), v8::internal::PagedSpaceBase::InitializePage(), v8::internal::ReadOnlyPageObjectIterator::Next(), v8::internal::ReadOnlyPageObjectIterator::ReadOnlyPageObjectIterator(), v8::internal::PagedSpaceBase::RemovePage(), v8::internal::PagedSpaceBase::RemovePageFromSpaceImpl(), ResetAllocationStatistics(), v8::internal::MutablePageMetadata::ResetAllocationStatisticsForPromotedPage(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run(), v8::internal::Scavenger::ScavengePage(), v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), v8::internal::PagedSpaceBase::TryExpand(), v8::internal::HeapAllocator::TryResizeLargeObject(), v8::internal::MarkCompactCollector::UpdatePointersInClientHeap(), and v8::internal::anonymous_namespace{sweeper.cc}::VerifyPreparedPage().
area_start()
Address v8::internal::MemoryChunkMetadata::area_start () const [inline]
Definition at line 60 of file memory-chunk-metadata.h.
{ return area_start_; }
References area_start_.
Referenced by v8::internal::Isolate::AddCodeMemoryChunk(), v8::internal::SemiSpace::AllocateFreshPage(), area_size(), Chunk(), Contains(), ContainsLimit(), v8::internal::ReadOnlyHeapImageDeserializer::DeserializeSegment(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitAllocatePage(), v8::internal::ReadOnlySpace::EnsureSpaceForAllocation(), v8::internal::MarkingBitmap::FindPreviousValidObject(), v8::internal::LargePageMetadata::GetObject(), v8::internal::ReadOnlySpace::InitializePageForDeserialization(), v8::internal::SemiSpaceObjectIterator::Next(), v8::internal::ReadOnlyPageMetadata::OffsetToAddress(), v8::internal::SemiSpace::page_low(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::Sweeper::RawSweep(), v8::internal::Isolate::RemoveCodeMemoryChunk(), v8::internal::anonymous_namespace{mark-compact.cc}::ReRecordPage(), v8::internal::MemoryAllocator::ResizeLargePage(), v8::internal::Scavenger::ScavengePage(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::SerializePage(), v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), v8::internal::SemiSpace::space_start(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::SweepPage(), v8::internal::PagedSpaceBase::TryExpand(), v8::internal::MarkCompactCollector::UpdatePointersInClientHeap(), and v8::internal::anonymous_namespace{sweeper.cc}::ZapDeadObjectsOnPage().
AreaStartOffset()
static constexpr intptr_t v8::internal::MemoryChunkMetadata::AreaStartOffset () [inline], [static], [constexpr], [private]
Definition at line 174 of file memory-chunk-metadata.h.
                                              {
    return offsetof(MemoryChunkMetadata, area_start_);
  }
References area_start_.
Chunk() [1/2]
MemoryChunk* v8::internal::MemoryChunkMetadata::Chunk () [inline]
Definition at line 123 of file memory-chunk-metadata.h.
{ return MemoryChunk::FromAddress(area_start()); }
References area_start(), and v8::internal::MemoryChunk::FromAddress().
Referenced by v8::internal::PagePool::Add(), v8::internal::MarkCompactCollector::AddEvacuationCandidate(), v8::internal::Sweeper::AddPageImpl(), v8::internal::PagedSpaceBase::AddPageImpl(), v8::internal::Sweeper::AddPromotedPage(), v8::internal::SemiSpace::AddRangeToActiveSystemPages(), v8::internal::PagedSpaceBase::AddRangeToActiveSystemPages(), v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject(), v8::internal::NewLargeObjectSpace::AllocateRaw(), v8::internal::OldLargeObjectSpace::AllocateRaw(), v8::internal::MemoryAllocator::AllocateUninitializedPageFromPool(), v8::internal::LargePageMetadata::cast(), v8::internal::PageMetadata::cast(), v8::internal::RememberedSet< type >::CheckNoneInRange(), ChunkAddress(), v8::internal::Sweeper::CleanupRememberedSetEntriesForFreedMemory(), v8::internal::PageMetadata::ClearEvacuationCandidate(), v8::internal::LargePageMetadata::ClearOutOfLiveRangeSlots(), v8::internal::MarkCompactCollector::CollectEvacuationCandidates(), v8::internal::MutablePageMetadata::CommittedPhysicalMemory(), v8::internal::anonymous_namespace{sweeper.cc}::ComparePagesForSweepingOrder(), v8::internal::LargeObjectSpace::ContainsSlow(), v8::internal::PagedSpaceBase::ContainsSlow(), v8::internal::PageMetadata::ConvertNewToOld(), v8::internal::MemoryAllocator::DeleteMemoryChunk(), v8::internal::Evacuator::EvacuatePage(), v8::internal::MarkCompactCollector::EvacuatePagesInParallel(), v8::internal::MarkingBitmap::FindPreviousValidObject(), v8::internal::SemiSpace::FixPagesFlags(), v8::internal::MemoryAllocator::Free(), v8::internal::MemoryAllocator::FreeReadOnlyPage(), v8::internal::SemiSpace::InitializePage(), v8::internal::PagedSpaceForNewSpace::InitializePage(), v8::internal::PagedSpaceBase::InitializePage(), IsWritable(), v8::internal::PageMetadata::MarkEvacuationCandidate(), v8::internal::MutablePageMetadata::marking_bitmap(), v8::internal::PageMetadata::MarkNeverAllocateForTesting(), v8::internal::PagedSpaceBase::MergeCompactionSpace(), v8::internal::MemoryChunk::Metadata(), v8::internal::CompactionSpace::NotifyNewPage(), v8::internal::Heap::NotifyOldGenerationExpansion(), Offset(), v8::base::hash< const i::MemoryChunkMetadata * >::operator()(), v8::internal::MutablePageMetadata::owner_identity(), v8::internal::Sweeper::LocalSweeper::ParallelIteratePromotedPage(), v8::internal::Sweeper::LocalSweeper::ParallelSweepSpace(), v8::internal::MemoryAllocator::PartialFreeMemory(), v8::internal::MemoryAllocator::PerformFreeMemory(), v8::internal::MarkCompactCollector::PostProcessAbortedEvacuationCandidates(), v8::internal::MemoryAllocator::PreFreeMemory(), v8::internal::Sweeper::PrepareToBeIteratedPromotedPage(), v8::internal::OldLargeObjectSpace::PromoteNewLargeObject(), v8::internal::NewSpace::PromotePageToOldSpace(), v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages(), v8::internal::Evacuator::RawEvacuatePage(), v8::internal::Sweeper::RawSweep(), v8::internal::CompactionSpace::RefillFreeList(), v8::internal::PagedSpaceAllocatorPolicy::RefillLab(), v8::internal::MutablePageMetadata::ReleaseAllocatedMemoryNeededForWritableChunk(), v8::internal::PagedSpaceBase::RelinkFreeListCategories(), v8::internal::PagedSpaceBase::RemovePage(), v8::internal::SemiSpaceNewSpace::RemovePage(), v8::internal::PagedSpaceBase::RemovePageFromSpaceImpl(), v8::internal::RememberedSetOperations::RemoveRange(), v8::internal::MarkCompactCollector::ReportAbortedEvacuationCandidateDueToFlags(), v8::internal::anonymous_namespace{mark-compact.cc}::ReRecordPage(), v8::internal::MarkCompactCollector::ResetAndRelinkBlackAllocatedPage(), v8::internal::Scavenger::ScavengePage(), v8::internal::SemiSpaceNewSpace::SetAgeMarkAndBelowAgeMarkPageFlags(), v8::internal::MutablePageMetadata::SetOldGenerationPageFlags(), v8::internal::MutablePageMetadata::SetYoungGenerationPageFlags(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::ShouldMovePage(), v8::internal::anonymous_namespace{mark-compact.cc}::ShouldMovePage(), v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), v8::internal::MarkCompactCollector::StartSweepNewSpace(), v8::internal::MarkCompactCollector::StartSweepSpace(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), v8::internal::MarkCompactCollector::SweepLargeSpace(), v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace(), v8::internal::MemoryAllocator::TryAllocateUninitializedLargePageFromPool(), v8::internal::MemoryAllocator::UnregisterMemoryChunk(), v8::internal::MemoryAllocator::UnregisterMutableMemoryChunk(), v8::internal::MemoryAllocator::UnregisterReadOnlyPage(), v8::internal::MarkCompactCollector::UpdatePointersInClientHeap(), v8::internal::Heap::ExternalStringTable::Verify(), v8::internal::Heap::ExternalStringTable::VerifyYoung(), and v8::internal::Sweeper::ZeroOrDiscardUnusedMemory().
Chunk() [2/2]
const MemoryChunk* v8::internal::MemoryChunkMetadata::Chunk () const [inline]
Definition at line 124 of file memory-chunk-metadata.h.
                                   {
    return MemoryChunk::FromAddress(area_start());
  }
References area_start(), and v8::internal::MemoryChunk::FromAddress().
ChunkAddress()
Address v8::internal::MemoryChunkMetadata::ChunkAddress () const [inline]
Definition at line 51 of file memory-chunk-metadata.h.
{ return Chunk()->address(); }
References v8::internal::MemoryChunk::address(), and Chunk().
Referenced by v8::internal::ReadOnlySpace::AllocateNextPageAt(), v8::internal::MemoryAllocator::AllocateReadOnlyPage(), v8::internal::MutablePageMetadata::AllocateTypedSlotSet(), v8::internal::MemoryAllocator::AllocateUninitializedPageFromPool(), v8::internal::LargePageMetadata::ClearOutOfLiveRangeSlots(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitAllocatePage(), v8::internal::MinorMarkSweepCollector::EvacuateExternalPointerReferences(), v8::internal::MemoryAllocator::FreeReadOnlyPage(), v8::internal::ReadOnlyPageMetadata::GetAreaStart(), HighWaterMark(), v8::internal::MutablePageMetadata::InitialFlags(), v8::internal::RememberedSetOperations::Iterate(), v8::internal::RememberedSet< type >::IterateAndTrackEmptyBuckets(), v8::internal::ReadOnlyPageMetadata::OffsetToAddress(), v8::internal::MemoryAllocator::PartialFreeMemory(), v8::internal::MemoryAllocator::ResizeLargePage(), v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark(), v8::internal::LargeObjectSpace::TearDown(), v8::internal::MemoryAllocator::TryAllocateUninitializedLargePageFromPool(), and UpdateHighWaterMark().
Contains()
bool v8::internal::MemoryChunkMetadata::Contains (Address addr) const [inline]
Definition at line 89 of file memory-chunk-metadata.h.
                                    {
    return addr >= area_start() && addr < area_end();
  }
References area_end(), and area_start().
Referenced by v8::internal::RememberedSet< type >::Contains(), v8::internal::ConservativeStackVisitorBase< ConcreteVisitor >::FindBasePtr(), v8::internal::MarkingBitmap::FindPreviousValidObject(), v8::internal::SemiSpaceNewSpace::IsPromotionCandidate(), v8::internal::MemoryAllocator::LookupChunkContainingAddressInSafepoint(), v8::internal::Scavenger::PinAndPushObject(), and v8::internal::RememberedSet< type >::Remove().
ContainsLimit()
bool v8::internal::MemoryChunkMetadata::ContainsLimit (Address addr) const [inline]
Definition at line 95 of file memory-chunk-metadata.h.
                                         {
    return addr >= area_start() && addr <= area_end();
  }
References area_end(), and area_start().
Referenced by v8::internal::LiveObjectRange::iterator::AdvanceToNextMarkedObject(), v8::internal::SemiSpaceNewSpace::IsAddressBelowAgeMark(), v8::internal::SemiSpaceNewSpace::ShouldPageBePromoted(), and v8::internal::Sweeper::ZeroOrDiscardUnusedMemory().
DecreaseAllocatedBytes()
void v8::internal::MemoryChunkMetadata::DecreaseAllocatedBytes (size_t bytes) [inline]
Definition at line 117 of file memory-chunk-metadata.h.
                                            {
    DCHECK_LE(bytes, area_size());
    DCHECK_GE(allocated_bytes(), bytes);
    allocated_bytes_ -= bytes;
  }
References allocated_bytes(), allocated_bytes_, area_size(), DCHECK_GE, and DCHECK_LE.
Referenced by v8::internal::OldSpace::AddPromotedPage(), v8::internal::FreeList::Free(), and v8::internal::FreeListManyCached::Free().
FromAddress()
MemoryChunkMetadata * v8::internal::MemoryChunkMetadata::FromAddress (Address a) [inline], [static]
Definition at line 17 of file memory-chunk-metadata-inl.h.
                                                               {
  return MemoryChunk::FromAddress(a)->Metadata();
}
References v8::internal::MemoryChunk::FromAddress(), and v8::internal::MemoryChunk::Metadata().
Referenced by v8::internal::SemiSpace::ContainsSlow(), v8::internal::anonymous_namespace{read-only-serializer.cc}::Encode(), v8::internal::MutablePageMetadata::FromAddress(), FromHeapObject(), v8::internal::Serializer::SerializeReadOnlyObjectReference(), UpdateHighWaterMark(), and v8::internal::heap::ZapCodeBlock().
FromHeapObject() [1/2]
MemoryChunkMetadata * v8::internal::MemoryChunkMetadata::FromHeapObject (const HeapObjectLayout * o) [inline], [static]
Definition at line 27 of file memory-chunk-metadata-inl.h.
                               {
  return FromAddress(reinterpret_cast<Address>(o));
}
References FromAddress().
FromHeapObject() [2/2]
MemoryChunkMetadata * v8::internal::MemoryChunkMetadata::FromHeapObject (Tagged< HeapObject > o) [inline], [static]
Definition at line 22 of file memory-chunk-metadata-inl.h.
                                                                             {
  return FromAddress(o.ptr());
}
References FromAddress(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::internal::LargeObjectSpace::Contains(), v8::internal::MutablePageMetadata::FromHeapObject(), v8::internal::Heap::FromWritableHeapObject(), v8::internal::UnreachableObjectsFilter::MarkAsReachable(), v8::internal::WriteBarrier::PageFlagsAreConsistent(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::ProcessStrongHeapObject(), v8::internal::ConcurrentMarking::RunMajor(), v8::internal::UnreachableObjectsFilter::SkipObject(), and v8::internal::YoungGenerationMarkingVisitor< marking_mode >::VisitObjectViaSlot().
heap()
Heap* v8::internal::MemoryChunkMetadata::heap () const [inline]
Definition at line 69 of file memory-chunk-metadata.h.
                     {
    DCHECK_NOT_NULL(heap_);
    return heap_;
  }
References DCHECK_NOT_NULL, and heap_.
Referenced by v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::CheckSlotForOldToSharedTyped(), v8::internal::HeapLayout::CheckYoungGenerationConsistency(), v8::internal::WriteBarrier::CombinedGenerationalAndSharedEphemeronBarrierSlow(), v8::internal::PageMetadata::ConvertNewToOld(), v8::internal::WriteBarrier::CurrentMarkingBarrier(), v8::internal::Heap::FromWritableHeapObject(), v8::internal::MemoryChunk::GetHeap(), v8::internal::YoungGenerationRememberedSetsMarkingWorklist::MarkingItem::heap(), v8::internal::MutablePageMetadata::InitialFlags(), v8::internal::WriteBarrier::MarkingFromCode(), v8::internal::EvacuateNewToOldSpacePageVisitor::Move(), v8::internal::MarkCompactCollector::RecordSlot(), v8::internal::WriteBarrier::SharedMarkingFromCode(), v8::internal::anonymous_namespace{minor-mark-sweep.cc}::ShouldMovePage(), v8::internal::anonymous_namespace{mark-compact.cc}::ShouldMovePage(), v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark(), and v8::internal::anonymous_namespace{scavenger.cc}::YoungGenerationConservativeStackVisitor::~YoungGenerationConservativeStackVisitor().
HeapOffset()
static constexpr intptr_t v8::internal::MemoryChunkMetadata::HeapOffset () [inline], [static], [constexpr], [private]
Definition at line 170 of file memory-chunk-metadata.h.
                                         {
    return offsetof(MemoryChunkMetadata, heap_);
  }
References heap_.
HighWaterMark()
Address v8::internal::MemoryChunkMetadata::HighWaterMark () const [inline]
Definition at line 103 of file memory-chunk-metadata.h.
{ return ChunkAddress() + high_water_mark_; }
References ChunkAddress(), and high_water_mark_.
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::EmitAllocatePage(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::SerializePage(), and v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark().
IncreaseAllocatedBytes()
void v8::internal::MemoryChunkMetadata::IncreaseAllocatedBytes (size_t bytes) [inline]
Definition at line 112 of file memory-chunk-metadata.h.
                                            {
    DCHECK_LE(bytes, area_size());
    allocated_bytes_ += bytes;
  }
References allocated_bytes_, area_size(), and DCHECK_LE.
Referenced by v8::internal::FreeListMany::Allocate(), v8::internal::FreeListManyCached::Allocate(), v8::internal::FreeListManyCachedFastPathBase::Allocate(), v8::internal::ReadOnlySpace::AllocateRawUnaligned(), v8::internal::ReadOnlySpace::InitializePageForDeserialization(), and v8::internal::ReadOnlySpace::TryAllocateLinearlyAligned().
InSharedSpace()
bool v8::internal::MemoryChunkMetadata::InSharedSpace () const
Definition at line 36 of file memory-chunk-metadata.cc.
                                              {
  return IsAnySharedSpace(owner()->identity());
}
References v8::internal::IsAnySharedSpace(), and owner().
Referenced by v8::internal::MutablePageMetadata::InitialFlags().
InTrustedSpace()
bool v8::internal::MemoryChunkMetadata::InTrustedSpace () const
Definition at line 40 of file memory-chunk-metadata.cc.
                                               {
  return IsAnyTrustedSpace(owner()->identity());
}
References v8::internal::IsAnyTrustedSpace(), and owner().
Referenced by v8::internal::LargePageMetadata::ClearOutOfLiveRangeSlots(), v8::internal::MutablePageMetadata::InitialFlags(), and v8::internal::Heap::NotifyObjectLayoutChange().
IsMutablePageMetadata()
bool v8::internal::MemoryChunkMetadata::IsMutablePageMetadata () const [inline]
Definition at line 87 of file memory-chunk-metadata.h.
{ return owner() != nullptr; }
References owner().
Referenced by v8::internal::MutablePageMetadata::cast().
IsWritable()
bool v8::internal::MemoryChunkMetadata::IsWritable () const [inline]
Definition at line 81 of file memory-chunk-metadata.h.
                          {
    // If this is a read-only space chunk but heap_ is non-null, it has not yet
    // been sealed and can be written to.
    return !Chunk()->InReadOnlySpace() || heap_ != nullptr;
  }
References Chunk(), heap_, and v8::internal::MemoryChunk::InReadOnlySpace().
Referenced by v8::internal::HeapLayout::CheckYoungGenerationConsistency(), v8::internal::Heap::FromWritableHeapObject(), and v8::internal::WriteBarrier::PageFlagsAreConsistent().
MetadataAddress()
Address v8::internal::MemoryChunkMetadata::MetadataAddress () const [inline]
Definition at line 52 of file memory-chunk-metadata.h.
{ return reinterpret_cast<Address>(this); }
Referenced by v8::internal::MarkingBitmap::FromAddress().
Offset()
size_t v8::internal::MemoryChunkMetadata::Offset (Address a) const [inline]
Definition at line 55 of file memory-chunk-metadata.h.
{ return Chunk()->Offset(a); }
References Chunk(), and v8::internal::MemoryChunk::Offset().
Referenced by v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::CheckSlotForOldToSharedTyped(), v8::internal::anonymous_namespace{mark-compact.cc}::RememberedSetUpdatingItem::CheckSlotForOldToSharedUntyped(), v8::internal::RememberedSet< type >::Contains(), v8::internal::anonymous_namespace{read-only-serializer.cc}::Encode(), v8::internal::ReadOnlySpace::InitializePageForDeserialization(), v8::internal::RememberedSetOperations::Remove(), v8::internal::Serializer::SerializeReadOnlyObjectReference(), and v8::internal::WriteBarrier::SharedSlow().
owner()
BaseSpace* v8::internal::MemoryChunkMetadata::owner () const [inline]
Definition at line 75 of file memory-chunk-metadata.h.
{ return owner_; }
References owner_.
Referenced by v8::internal::LargeObjectSpace::Contains(), InSharedSpace(), InTrustedSpace(), IsMutablePageMetadata(), v8::internal::Heap::IsPendingAllocationInternal(), v8::internal::MutablePageMetadata::owner(), v8::internal::WriteBarrier::PageFlagsAreConsistent(), v8::internal::MarkingVisitorBase< ConcreteVisitor >::ProcessStrongHeapObject(), and v8::internal::ScavengerCollector::QuarantinedPageSweeper::JobTask::Run().
reserved_memory()
VirtualMemory* v8::internal::MemoryChunkMetadata::reserved_memory () [inline]
Definition at line 105 of file memory-chunk-metadata.h.
{ return &reservation_; }
References reservation_.
Referenced by v8::internal::MemoryAllocator::DeleteMemoryChunk(), v8::internal::MemoryAllocator::FreeReadOnlyPage(), v8::internal::MemoryAllocator::PartialFreeMemory(), v8::internal::MemoryAllocator::UnregisterMemoryChunk(), and v8::internal::MemoryAllocator::UnregisterSharedMemoryChunk().
ResetAllocationStatistics()
void v8::internal::MemoryChunkMetadata::ResetAllocationStatistics () [inline]
Definition at line 107 of file memory-chunk-metadata.h.
                                   {
    allocated_bytes_ = area_size();
    wasted_memory_ = 0;
  }
References allocated_bytes_, area_size(), and wasted_memory_.
Referenced by v8::internal::MutablePageMetadata::ResetAllocationStatistics().
set_area_end()
void v8::internal::MemoryChunkMetadata::set_area_end (Address area_end) [inline]
Definition at line 63 of file memory-chunk-metadata.h.
{ area_end_ = area_end; }
References area_end(), and area_end_.
Referenced by v8::internal::MemoryAllocator::PartialFreeMemory(), v8::internal::MemoryAllocator::ResizeLargePage(), and v8::internal::LargeObjectSpace::ShrinkPageToObjectSize().
set_owner()
void v8::internal::MemoryChunkMetadata::set_owner (BaseSpace * space) [inline]
Definition at line 76 of file memory-chunk-metadata.h.
{ owner_ = space; }
References owner_, and space.
Referenced by v8::internal::LargeObjectSpace::AddPage(), v8::internal::PagedSpaceBase::AddPageImpl(), v8::internal::PageMetadata::ConvertNewToOld(), v8::internal::SemiSpace::FixPagesFlags(), v8::internal::SemiSpace::MoveQuarantinedPage(), and v8::internal::LargeObjectSpace::RemovePage().
set_size()
void v8::internal::MemoryChunkMetadata::set_size (size_t size) [inline]
Definition at line 58 of file memory-chunk-metadata.h.
{ size_ = size; }
References size(), and size_.
Referenced by v8::internal::MemoryAllocator::PartialFreeMemory(), and v8::internal::MemoryAllocator::ResizeLargePage().
size()
size_t v8::internal::MemoryChunkMetadata::size () const [inline]
Definition at line 57 of file memory-chunk-metadata.h.
{ return size_; }
References size_.
Referenced by v8::internal::PagePool::Add(), v8::internal::PagePool::LargePagePoolImpl::Add(), v8::internal::LargeObjectSpace::AddPage(), v8::internal::PagedSpaceBase::AddPageImpl(), v8::internal::ReadOnlySpace::AllocateNextPage(), v8::internal::ReadOnlySpace::AllocateNextPageAt(), v8::internal::MemoryAllocator::AllocateReadOnlyPage(), v8::internal::MutablePageMetadata::BucketsInSlotSet(), v8::internal::MutablePageMetadata::CommittedPhysicalMemory(), v8::internal::ReadOnlySpace::EnsureSpaceForAllocation(), v8::internal::MemoryAllocator::Free(), v8::internal::MemoryAllocator::FreeReadOnlyPage(), v8::internal::MutablePageMetadata::MutablePageMetadata(), v8::internal::ReadOnlyPageMetadata::OffsetToAddress(), v8::internal::MemoryAllocator::PartialFreeMemory(), v8::internal::HeapLayoutTracer::PrintMemoryChunk(), v8::internal::LargeObjectSpace::RemovePage(), v8::internal::PagedSpaceBase::RemovePage(), v8::internal::PagedSpaceBase::RemovePageFromSpaceImpl(), set_size(), v8::internal::LargeObjectSpace::ShrinkPageToObjectSize(), v8::internal::ReadOnlyPageMetadata::ShrinkToHighWaterMark(), v8::internal::MemoryAllocator::TryAllocateUninitializedLargePageFromPool(), v8::internal::MemoryAllocator::UnregisterMemoryChunk(), and v8::internal::MemoryAllocator::UnregisterSharedMemoryChunk().
UpdateHighWaterMark()
void v8::internal::MemoryChunkMetadata::UpdateHighWaterMark (Address mark) [inline], [static]
Definition at line 33 of file memory-chunk-metadata-inl.h.
                                                          {
  if (mark == kNullAddress) return;
  // Need to subtract one from the mark because when a chunk is full the
  // top points to the next address after the chunk, which effectively belongs
  // to another chunk. See the comment to
  // PageMetadata::FromAllocationAreaAddress.
  MemoryChunkMetadata* chunk = MemoryChunkMetadata::FromAddress(mark - 1);
  intptr_t new_mark = static_cast<intptr_t>(mark - chunk->ChunkAddress());
  intptr_t old_mark = chunk->high_water_mark_.load(std::memory_order_relaxed);
  while ((new_mark > old_mark) &&
         !chunk->high_water_mark_.compare_exchange_weak(
             old_mark, new_mark, std::memory_order_acq_rel)) {
  }
}
References ChunkAddress(), FromAddress(), high_water_mark_, and v8::internal::kNullAddress.
Referenced by v8::internal::ReadOnlySpace::CommittedPhysicalMemory(), v8::internal::MainAllocator::FreeLinearAllocationArea(), v8::internal::ReadOnlySpace::FreeLinearAllocationArea(), v8::internal::ReadOnlySpace::RepairFreeSpacesAfterDeserialization(), v8::internal::MainAllocator::ResetLab(), and v8::internal::ReadOnlySpace::ShrinkPages().
wasted_memory()
size_t v8::internal::MemoryChunkMetadata::wasted_memory () const [inline]
Definition at line 99 of file memory-chunk-metadata.h.
{ return wasted_memory_; }
References wasted_memory_.
Referenced by v8::internal::PageMetadata::AvailableInFreeListFromAllocatedBytes(), v8::internal::Sweeper::PrepareToBeIteratedPromotedPage(), v8::internal::HeapLayoutTracer::PrintMemoryChunk(), v8::internal::CompactionSpace::RefillFreeList(), v8::internal::PagedSpaceBase::RelinkFreeListCategories(), v8::internal::PagedSpaceBase::RemovePage(), and v8::internal::MinorMarkSweepCollector::StartSweepNewSpace().
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 181 of file memory-chunk-metadata.h.
debug_helper_internal::ReadStringVisitor
friend class debug_helper_internal::ReadStringVisitor [friend]
Definition at line 179 of file memory-chunk-metadata.h.
MacroAssembler
friend class MacroAssembler [friend]
Definition at line 182 of file memory-chunk-metadata.h.
Member Data Documentation
allocated_bytes_
size_t v8::internal::MemoryChunkMetadata::allocated_bytes_ [protected]
Definition at line 143 of file memory-chunk-metadata.h.
Referenced by allocated_bytes(), DecreaseAllocatedBytes(), IncreaseAllocatedBytes(), v8::internal::ReadOnlyPageMetadata::ReadOnlyPageMetadata(), ResetAllocationStatistics(), and v8::internal::MutablePageMetadata::ResetAllocationStatisticsForPromotedPage().
area_end_
Address v8::internal::MemoryChunkMetadata::area_end_ [protected]
Definition at line 154 of file memory-chunk-metadata.h.
Referenced by area_end(), and set_area_end().
area_start_
Address v8::internal::MemoryChunkMetadata::area_start_ [protected]
Definition at line 164 of file memory-chunk-metadata.h.
Referenced by area_start(), and AreaStartOffset().
heap_
Heap* v8::internal::MemoryChunkMetadata::heap_ [protected]
Definition at line 161 of file memory-chunk-metadata.h.
Referenced by heap(), HeapOffset(), IsWritable(), v8::internal::ReadOnlyPageMetadata::MakeHeaderRelocatable(), and v8::internal::MutablePageMetadata::MutablePageMetadata().
high_water_mark_
std::atomic<intptr_t> v8::internal::MemoryChunkMetadata::high_water_mark_ [protected]
Definition at line 149 of file memory-chunk-metadata.h.
Referenced by HighWaterMark(), v8::internal::ReadOnlySpace::InitializePageForDeserialization(), and UpdateHighWaterMark().
owner_
std::atomic<BaseSpace*> v8::internal::MemoryChunkMetadata::owner_ [protected]
Definition at line 167 of file memory-chunk-metadata.h.
Referenced by v8::internal::ReadOnlyPageMetadata::MakeHeaderRelocatable(), owner(), and set_owner().
reservation_
VirtualMemory v8::internal::MemoryChunkMetadata::reservation_ [protected]
Definition at line 139 of file memory-chunk-metadata.h.
Referenced by v8::internal::ReadOnlyPageMetadata::MakeHeaderRelocatable(), reserved_memory(), and v8::internal::MemoryAllocator::ResizeLargePage().
size_
size_t v8::internal::MemoryChunkMetadata::size_ [protected]
Definition at line 152 of file memory-chunk-metadata.h.
Referenced by set_size(), and size().
wasted_memory_
size_t v8::internal::MemoryChunkMetadata::wasted_memory_ = 0 [protected]
Definition at line 145 of file memory-chunk-metadata.h.
Referenced by add_wasted_memory(), ResetAllocationStatistics(), v8::internal::MutablePageMetadata::ResetAllocationStatisticsForPromotedPage(), and wasted_memory().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/memory-chunk-metadata.h
/mnt/V8SourceCode/src/heap/memory-chunk-metadata-inl.h
/mnt/V8SourceCode/src/heap/memory-chunk-metadata.cc