v8::JSON Class Reference
A JSON Parser and Stringifier.
#include <v8-json.h>
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeLocal< Value > Parse (Local< Context > context, Local< String > json_string)
Tries to parse the string |json_string| and returns it as value if successful.
static V8_WARN_UNUSED_RESULT MaybeLocal< String > Stringify (Local< Context > context, Local< Value > json_object, Local< String > gap=Local< String >())
Tries to stringify the JSON-serializable object |json_object| and returns it as string if successful.
Detailed Description
A JSON Parser and Stringifier.
Definition at line 20 of file v8-json.h.
Member Function Documentation
Parse()
MaybeLocal< Value > v8::JSON::Parse (Local< Context > context, Local< String > json_string) [static]
Tries to parse the string |json_string| and returns it as value if successful.
Parameters
the context in which to parse and create the value.
json_string The string to parse.
Returns
The corresponding value if successfully parsed.
Definition at line 3212 of file api.cc.
                                                         {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_JSON_Parse};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto string = Utils::OpenHandle(*json_string);
  i::Handle<i::String> source = i::String::Flatten(i_isolate, string);
  i::Handle<i::Object> undefined = i_isolate->factory()->undefined_value();
  auto maybe_result =
      source->IsOneByteRepresentation()
          ? i::JsonParser<uint8_t>::Parse(i_isolate, source, undefined)
          : i::JsonParser<uint16_t>::Parse(i_isolate, source, undefined);
  return api_scope.EscapeMaybe(maybe_result);
}
References v8::internal::Isolate::factory(), v8::Utils::OpenHandle(), v8::internal::JsonParser< Char >::Parse(), and v8::internal::undefined.
Referenced by v8::Shell::FetchModuleTree(), v8::tracing::anonymous_namespace{d8.cc}::TraceConfigParser::FillTraceConfig(), v8::Shell::LoadJSON(), v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags(), and v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap().
Stringify()
MaybeLocal< String > v8::JSON::Stringify (Local< Context > context, Local< Value > json_object, Local< String > gap = Local<String>()) [static]
Tries to stringify the JSON-serializable object |json_object| and returns it as string if successful.
Parameters
json_object The JSON-serializable object to stringify.
Returns
The corresponding string if successfully stringified.
Definition at line 3226 of file api.cc.
                                                      {
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_JSON_Stringify};
  i::Isolate* i_isolate = api_scope.i_isolate();
  i::Handle<i::JSAny> object;
  if (!Utils::ApiCheck(
          i::TryCast<i::JSAny>(Utils::OpenHandle(*json_object), &object),
          "JSON::Stringify",
          "Invalid object, must be a JSON-serializable object.")) {
    return {};
  }
  i::Handle<i::Undefined> replacer = i_isolate->factory()->undefined_value();
  i::Handle<i::String> gap_string = gap.IsEmpty()
                                        ? i_isolate->factory()->empty_string()
                                        : Utils::OpenHandle(*gap);
  i::DirectHandle<i::Object> maybe;
  if (!i::JsonStringify(i_isolate, object, replacer, gap_string)
           .ToHandle(&maybe)) {
    return {};
  }
  return api_scope.EscapeMaybe(i::Object::ToString(i_isolate, maybe));
}
References v8::Utils::ApiCheck(), v8::internal::Isolate::factory(), v8::api_internal::IndirectHandleBase::IsEmpty(), v8::internal::JsonStringify(), v8::Utils::OpenHandle(), v8::anonymous_namespace{api.cc}::ToHandle(), and ToString().
Referenced by v8::Shell::FunctionAndArgumentsToString(), v8_inspector::generateCustomPreview(), and v8::Shell::WriteIgnitionDispatchCountersFile().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-json.h
/mnt/V8SourceCode/src/api/api.cc