v8::internal::compiler::JSHasPropertyNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSHasPropertyNode (Node *node)
const PropertyAccess & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1275 of file js-operator.h.
Constructor & Destructor Documentation
JSHasPropertyNode()
constexpr v8::internal::compiler::JSHasPropertyNode::JSHasPropertyNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1277 of file js-operator.h.
                                                   : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSHasProperty, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const PropertyAccess& v8::internal::compiler::JSHasPropertyNode::Parameters () const [inline]
Definition at line 1281 of file js-operator.h.
                                           {
    return PropertyAccessOf(node()->op());
  }
References v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::PropertyAccessOf().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSHasProperty().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h