v8::internal::wasm::StructType Class Reference
#include <struct-types.h>
Public Types
using Builder = StructTypeBase::BuilderImpl< StructType, ValueType >
Public Member Functions
StructType (uint32_t field_count, uint32_t *field_offsets, const ValueType *reps, const bool *mutabilities, bool is_descriptor, bool is_shared)
bool operator== (const StructType &other) const
ValueType field (uint32_t index) const
base::iterator_range< const ValueType * > fields () const
Additional Inherited Members
Detailed Description
Definition at line 242 of file struct-types.h.
Member Typedef Documentation
Builder
using v8::internal::wasm::StructType::Builder = StructTypeBase::BuilderImpl<StructType, ValueType>
Definition at line 244 of file struct-types.h.
Constructor & Destructor Documentation
StructType()
v8::internal::wasm::StructType::StructType (uint32_t field_count, uint32_t * field_offsets, const ValueType * reps, const bool * mutabilities, bool is_descriptor, bool is_shared) [inline]
Definition at line 246 of file struct-types.h.
      : StructTypeBase(field_count, field_offsets, reps, mutabilities,
                       is_descriptor, is_shared) {}
Member Function Documentation
field()
ValueType v8::internal::wasm::StructType::field (uint32_t index) const [inline]
Definition at line 262 of file struct-types.h.
                                        {
    return ValueType{StructTypeBase::field(index)};
  }
References v8::internal::wasm::StructTypeBase::field(), and v8::internal::index.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::CreateWasmObject(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::ModuleGen::GenerateRandomStructs(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateStructNewInitExpr(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseStructGet(), v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNew(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNewDefault(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_set(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicCompareExchange(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructNew(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructNewDefault(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructSet(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidStructSubtypeDefinition(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
fields()
base::iterator_range<const ValueType*> v8::internal::wasm::StructType::fields () const [inline]
Definition at line 266 of file struct-types.h.
                                                      {
    const ValueType* cast_reps = static_cast<const ValueType*>(reps_);
    return {cast_reps, cast_reps + field_count_};
  }
References v8::internal::wasm::StructTypeBase::field_count_, and v8::internal::wasm::StructTypeBase::reps_.
Referenced by v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateStructNewInitExpr(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object(), and operator==().
operator==()
bool v8::internal::wasm::StructType::operator== (const StructType & other) const [inline]
Definition at line 252 of file struct-types.h.
                                                 {
    if (this == &other) return true;
    if (field_count() != other.field_count()) return false;
    if (this->is_descriptor() != other.is_descriptor()) return false;
    return std::equal(fields().begin(), fields().end(),
                      other.fields().begin()) &&
           std::equal(mutabilities().begin(), mutabilities().end(),
                      other.mutabilities().begin());
  }
References v8::internal::compiler::begin(), v8::internal::compiler::end(), v8::internal::equal, v8::internal::wasm::StructTypeBase::field_count(), fields(), v8::internal::wasm::StructTypeBase::is_descriptor(), and v8::internal::wasm::StructTypeBase::mutabilities().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/struct-types.h