v8::internal::compiler::turboshaft::EmitProjectionReducer< Next > Class Template Reference
#include <assembler.h>
Public Member Functions
V< Object > ReduceCatchBlockBegin ()
template<Opcode opcode, typename Continuation , typename... Args>
OpIndex ReduceOperation (Args... args)
Private Member Functions
template<class Op >
V< Any > WrapInTupleIfNeeded (const Op &op, V< Any > idx)
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::EmitProjectionReducer< Next >
Definition at line 924 of file assembler.h.
Member Function Documentation
ReduceCatchBlockBegin()
template<class Next >
V<Object> v8::internal::compiler::turboshaft::EmitProjectionReducer< Next >::ReduceCatchBlockBegin () [inline]
Definition at line 929 of file assembler.h.
                                    {
    // CatchBlockBegin have a single output, so they never have projections,
    // but additionally split-edge can transform CatchBlockBeginOp into PhiOp,
    // which means that there is no guarantee here that Next::CatchBlockBegin is
    // indeed a CatchBlockBegin (which means that the .Cast<> of the generic
    // ReduceOperation could fail on CatchBlockBegin).
    return Next::ReduceCatchBlockBegin();
  }
ReduceOperation()
template<class Next >
template<Opcode opcode, typename Continuation , typename... Args>
OpIndex v8::internal::compiler::turboshaft::EmitProjectionReducer< Next >::ReduceOperation (Args... args) [inline]
Definition at line 939 of file assembler.h.
                                        {
    OpIndex new_idx = Continuation{this}.Reduce(args...);
    const Operation& op = Asm().output_graph().Get(new_idx);
    if constexpr (MayThrow(opcode)) {
      // Operations that can throw are lowered to an Op+DidntThrow, and what we
      // get from Next::Reduce is the DidntThrow.
      return WrapInTupleIfNeeded(op.Cast<DidntThrowOp>(), new_idx);
    }
    return WrapInTupleIfNeeded(op.Cast<typename Continuation::Op>(), new_idx);
  }
References v8::base::args, v8::internal::compiler::turboshaft::Operation::Cast(), and v8::internal::compiler::turboshaft::MayThrow().
WrapInTupleIfNeeded()
template<class Next >
template<class Op >
V<Any> v8::internal::compiler::turboshaft::EmitProjectionReducer< Next >::WrapInTupleIfNeeded (const Op & op, V< Any > idx) [inline], [private]
Definition at line 952 of file assembler.h.
                                                       {
    if (op.outputs_rep().size() > 1) {
      base::SmallVector<V<Any>, 8> projections;
      auto reps = op.outputs_rep();
      for (int i = 0; i < static_cast<int>(reps.size()); i++) {
        projections.push_back(Asm().Projection(idx, i, reps[i]));
      }
      return Asm().Tuple(base::VectorOf(projections));
    }
    return idx;
  }
References v8::base::SmallVector< T, kSize, Allocator >::push_back(), and v8::base::VectorOf().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/assembler.h