v8::internal::CppGraphBuilder Class Reference
#include <cpp-snapshot.h>
Public Member Functions
CppGraphBuilder ()=delete
Static Public Member Functions
static void Run (v8::Isolate *isolate, v8::EmbedderGraph *graph, void *data, UnorderedCppHeapExternalObjectSet &&cpp_heap_external_objects)
Detailed Description
Definition at line 18 of file cpp-snapshot.h.
Constructor & Destructor Documentation
CppGraphBuilder()
v8::internal::CppGraphBuilder::CppGraphBuilder () [delete]
Member Function Documentation
Run()
void v8::internal::CppGraphBuilder::Run (v8::Isolate * isolate, v8::EmbedderGraph * graph, void * data, UnorderedCppHeapExternalObjectSet && cpp_heap_external_objects) [static]
Definition at line 1094 of file cpp-snapshot.cc.
                                                                   {
  CppHeap* cpp_heap = static_cast<CppHeap*>(data);
  CHECK_NOT_NULL(cpp_heap);
  CHECK_NOT_NULL(graph);
  CppGraphBuilderImpl graph_builder(*cpp_heap, *graph,
                                    std::move(cpp_heap_external_objects));
  graph_builder.Run();
}
References CHECK_NOT_NULL, graph(), and v8::internal::CppGraphBuilderImpl::Run().
Referenced by v8::internal::CppHeap::AttachIsolate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-snapshot.h
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-snapshot.cc