v8::internal::wasm::ResolvedWasmImport Class Reference
#include <module-instantiate.h>
Public Member Functions
V8_EXPORT_PRIVATE ResolvedWasmImport (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int func_index, DirectHandle< JSReceiver > callable, const wasm::CanonicalSig *sig, CanonicalTypeIndex expected_sig_id, WellKnownImport preknown_import)
ImportCallKind kind () const
WellKnownImport well_known_status () const
Suspend suspend () const
DirectHandle< JSReceiver > callable () const
DirectHandle< WasmFunctionData > trusted_function_data () const
Private Member Functions
void SetCallable (Isolate *isolate, Tagged< JSReceiver > callable)
void SetCallable (Isolate *isolate, DirectHandle< JSReceiver > callable)
ImportCallKind ComputeKind (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int func_index, const wasm::CanonicalSig *expected_sig, CanonicalTypeIndex expected_canonical_type_index, WellKnownImport preknown_import)
Private Attributes
ImportCallKind kind_
WellKnownImport well_known_status_ {WellKnownImport::kGeneric}
Suspend suspend_ {kNoSuspend}
DirectHandle< JSReceiver > callable_
DirectHandle< WasmFunctionData > trusted_function_data_
Detailed Description
Definition at line 61 of file module-instantiate.h.
Constructor & Destructor Documentation
ResolvedWasmImport()
v8::internal::wasm::ResolvedWasmImport::ResolvedWasmImport (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int func_index, DirectHandle< JSReceiver > callable, const wasm::CanonicalSig * sig, CanonicalTypeIndex expected_sig_id, WellKnownImport preknown_import)
Definition at line 667 of file module-instantiate.cc.
                                                                         {
  DCHECK_EQ(expected_sig, wasm::GetTypeCanonicalizer()->LookupFunctionSignature(
                              expected_sig_id));
  SetCallable(Isolate::Current(), callable);
  kind_ = ComputeKind(trusted_instance_data, func_index, expected_sig,
                      expected_sig_id, preknown_import);
}
References callable(), ComputeKind(), v8::internal::Isolate::Current(), DCHECK_EQ, v8::internal::wasm::GetTypeCanonicalizer(), kind_, and SetCallable().
Member Function Documentation
callable()
DirectHandle<JSReceiver> v8::internal::wasm::ResolvedWasmImport::callable () const [inline]
Definition at line 74 of file module-instantiate.h.
{ return callable_; }
References callable_.
Referenced by v8::internal::wasm::InstanceBuilder::ProcessImportedFunction(), ResolvedWasmImport(), and SetCallable().
ComputeKind()
ImportCallKind v8::internal::wasm::ResolvedWasmImport::ComputeKind (DirectHandle< WasmTrustedInstanceData > trusted_instance_data, int func_index, const wasm::CanonicalSig * expected_sig, CanonicalTypeIndex expected_canonical_type_index, WellKnownImport preknown_import) [private]
Definition at line 693 of file module-instantiate.cc.
                                     {
  // If we already have a compile-time import, simply pass that through.
  if (IsCompileTimeImport(preknown_import)) {
    well_known_status_ = preknown_import;
    DCHECK(IsJSFunction(*callable_));
    DCHECK_EQ(Cast<JSFunction>(*callable_)
                  ->shared()
                  ->internal_formal_parameter_count_without_receiver(),
              expected_sig->parameter_count());
    return ImportCallKind::kJSFunction;
  }
  Isolate* isolate = Isolate::Current();
  if (IsWasmSuspendingObject(*callable_)) {
    suspend_ = kSuspend;
    SetCallable(isolate, Cast<WasmSuspendingObject>(*callable_)->callable());
  }
  if (!trusted_function_data_.is_null() &&
      IsWasmExportedFunctionData(*trusted_function_data_)) {
    Tagged<WasmExportedFunctionData> data =
        Cast<WasmExportedFunctionData>(*trusted_function_data_);
    if (!data->MatchesSignature(expected_sig_id)) {
      return ImportCallKind::kLinkError;
    }
    uint32_t function_index = static_cast<uint32_t>(data->function_index());
    if (function_index >=
        data->instance_data()->module()->num_imported_functions) {
      return ImportCallKind::kWasmToWasm;
    }
    // Resolve the shortcut to the underlying callable and continue.
    ImportedFunctionEntry entry(direct_handle(data->instance_data(), isolate),
                                function_index);
    suspend_ = Cast<WasmImportData>(entry.implicit_arg())->suspend();
    SetCallable(isolate, entry.callable());
  }
  if (!trusted_function_data_.is_null() &&
      IsWasmJSFunctionData(*trusted_function_data_)) {
    Tagged<WasmJSFunctionData> js_function_data =
        Cast<WasmJSFunctionData>(*trusted_function_data_);
    suspend_ = js_function_data->GetSuspend();
    if (!js_function_data->MatchesSignature(expected_sig_id)) {
      return ImportCallKind::kLinkError;
    }
    if (IsJSFunction(js_function_data->GetCallable())) {
      Tagged<SharedFunctionInfo> sfi =
          Cast<JSFunction>(js_function_data->GetCallable())->shared();
      if (sfi->HasWasmFunctionData(isolate)) {
        // Special case if the underlying callable is a WasmJSFunction or
        // WasmExportedFunction: link the outer WasmJSFunction itself and not
        // the inner callable. Otherwise when the wrapper tiers up, we will try
        // to link the inner WasmJSFunction/WamsExportedFunction which is
        // incorrect.
        return ImportCallKind::kUseCallBuiltin;
      }
    }
    SetCallable(isolate, js_function_data->GetCallable());
  }
  if (WasmCapiFunction::IsWasmCapiFunction(*callable_)) {
    // TODO(jkummerow): Update this to follow the style of the other kinds of
    // functions.
    auto capi_function = Cast<WasmCapiFunction>(callable_);
    if (!capi_function->MatchesSignature(expected_sig_id)) {
      return ImportCallKind::kLinkError;
    }
    return ImportCallKind::kWasmToCapi;
  }
  // Assuming we are calling to JS, check whether this would be a runtime error.
  if (!wasm::IsJSCompatibleSignature(expected_sig)) {
    return ImportCallKind::kRuntimeTypeError;
  }
  // Check if this can be a JS fast API call.
  if (v8_flags.turbo_fast_api_calls &&
      ResolveBoundJSFastApiFunction(expected_sig, callable_)) {
    return ImportCallKind::kWasmToJSFastApi;
  }
  well_known_status_ = CheckForWellKnownImport(
      trusted_instance_data, func_index, callable_, expected_sig);
  if (well_known_status_ == WellKnownImport::kLinkError) {
    return ImportCallKind::kLinkError;
  }
  // TODO(jkummerow): It would be nice to return {kJSFunction} here
  // whenever {well_known_status_ != kGeneric}, so that the generic wrapper
  // can be used instead of a compiled wrapper; but that requires adding
  // support for calling bound functions to the generic wrapper first.
  // For JavaScript calls, determine whether the target has an arity match.
  if (IsJSFunction(*callable_)) {
    auto function = Cast<JSFunction>(callable_);
    DirectHandle<SharedFunctionInfo> shared(function->shared(), isolate);
    if (IsClassConstructor(shared->kind())) {
      // Class constructor will throw anyway.
      return ImportCallKind::kUseCallBuiltin;
    }
    return ImportCallKind::kJSFunction;
  }
  // Unknown case. Use the call builtin.
  return ImportCallKind::kUseCallBuiltin;
}
References v8::internal::ImportedFunctionEntry::callable(), callable_, v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CheckForWellKnownImport(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::ImportedFunctionEntry::implicit_arg(), v8::internal::IsClassConstructor(), v8::internal::wasm::IsCompileTimeImport(), v8::internal::wasm::IsJSCompatibleSignature(), v8::internal::WasmCapiFunction::IsWasmCapiFunction(), v8::internal::wasm::kJSFunction, v8::internal::wasm::kLinkError, v8::internal::wasm::kRuntimeTypeError, v8::internal::wasm::kSuspend, v8::internal::wasm::kUseCallBuiltin, v8::internal::wasm::kWasmToCapi, v8::internal::wasm::kWasmToJSFastApi, v8::internal::wasm::kWasmToWasm, v8::internal::Signature< T >::parameter_count(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ResolveBoundJSFastApiFunction(), SetCallable(), suspend_, trusted_function_data_, v8::internal::v8_flags, and well_known_status_.
Referenced by ResolvedWasmImport().
kind()
ImportCallKind v8::internal::wasm::ResolvedWasmImport::kind () const [inline]
Definition at line 71 of file module-instantiate.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::wasm::InstanceBuilder::ProcessImportedFunction(), and v8::internal::RUNTIME_FUNCTION().
SetCallable() [1/2]
void v8::internal::wasm::ResolvedWasmImport::SetCallable (Isolate * isolate, DirectHandle< JSReceiver > callable) [private]
Definition at line 682 of file module-instantiate.cc.
                                                                        {
  callable_ = callable;
  trusted_function_data_ = {};
  if (!IsJSFunction(*callable)) return;
  Tagged<SharedFunctionInfo> sfi = Cast<JSFunction>(*callable_)->shared();
  if (sfi->HasWasmFunctionData(isolate)) {
    trusted_function_data_ = direct_handle(sfi->wasm_function_data(), isolate);
  }
}
References callable(), callable_, v8::internal::direct_handle(), and trusted_function_data_.
SetCallable() [2/2]
void v8::internal::wasm::ResolvedWasmImport::SetCallable (Isolate * isolate, Tagged< JSReceiver > callable) [private]
Definition at line 678 of file module-instantiate.cc.
                                                                  {
  SetCallable(isolate, direct_handle(callable, isolate));
}
References callable(), and v8::internal::direct_handle().
Referenced by ComputeKind(), and ResolvedWasmImport().
suspend()
Suspend v8::internal::wasm::ResolvedWasmImport::suspend () const [inline]
Definition at line 73 of file module-instantiate.h.
{ return suspend_; }
References suspend_.
Referenced by v8::internal::wasm::InstanceBuilder::ProcessImportedFunction().
trusted_function_data()
DirectHandle<WasmFunctionData> v8::internal::wasm::ResolvedWasmImport::trusted_function_data () const [inline]
Definition at line 78 of file module-instantiate.h.
                                                               {
    return trusted_function_data_;
  }
References trusted_function_data_.
Referenced by v8::internal::wasm::InstanceBuilder::ProcessImportedFunction().
well_known_status()
WellKnownImport v8::internal::wasm::ResolvedWasmImport::well_known_status () const [inline]
Definition at line 72 of file module-instantiate.h.
{ return well_known_status_; }
References well_known_status_.
Referenced by v8::internal::wasm::InstanceBuilder::ProcessImportedFunction().
Member Data Documentation
callable_
DirectHandle<JSReceiver> v8::internal::wasm::ResolvedWasmImport::callable_ [private]
Definition at line 95 of file module-instantiate.h.
Referenced by callable(), ComputeKind(), and SetCallable().
kind_
ImportCallKind v8::internal::wasm::ResolvedWasmImport::kind_ [private]
Definition at line 92 of file module-instantiate.h.
Referenced by kind(), and ResolvedWasmImport().
suspend_
Suspend v8::internal::wasm::ResolvedWasmImport::suspend_ {kNoSuspend} [private]
Definition at line 94 of file module-instantiate.h.
Referenced by ComputeKind(), and suspend().
trusted_function_data_
DirectHandle<WasmFunctionData> v8::internal::wasm::ResolvedWasmImport::trusted_function_data_ [private]
Definition at line 96 of file module-instantiate.h.
Referenced by ComputeKind(), SetCallable(), and trusted_function_data().
well_known_status_
WellKnownImport v8::internal::wasm::ResolvedWasmImport::well_known_status_ {WellKnownImport::kGeneric} [private]
Definition at line 93 of file module-instantiate.h.
Referenced by ComputeKind(), and well_known_status().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/module-instantiate.h
/mnt/V8SourceCode/src/wasm/module-instantiate.cc