v8::internal::GrowArrayElementsDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_PARAMETER_TYPES (MachineType::AnyTagged(), MachineType::AnyTagged()) static const expr inline Register ObjectRegister()
Static Public Member Functions
static constexpr Register KeyRegister ()
static constexpr auto registers ()
Additional Inherited Members
Detailed Description
Definition at line 2340 of file interface-descriptors.h.
Member Function Documentation
DEFINE_PARAMETER_TYPES()
v8::internal::GrowArrayElementsDescriptor::DEFINE_PARAMETER_TYPES (MachineType::AnyTagged() , MachineType::AnyTagged()) const
KeyRegister()
constexpr Register v8::internal::GrowArrayElementsDescriptor::KeyRegister () [inline], [static], [constexpr]
Definition at line 148 of file interface-descriptors-riscv-inl.h.
{ return a3; }
Referenced by registers().
registers()
constexpr auto v8::internal::GrowArrayElementsDescriptor::registers () [static], [constexpr]
Definition at line 737 of file interface-descriptors-inl.h.
                                                      {
  return RegisterArray(ObjectRegister(), KeyRegister());
}
References KeyRegister(), and v8::internal::RegisterArray().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h
/mnt/V8SourceCode/src/codegen/riscv/interface-descriptors-riscv-inl.h