v8::base::Hasher Class Reference
#include <hashing.h>
Public Member Functions
constexpr Hasher ()=default
constexpr Hasher (size_t seed)
constexpr size_t hash () const
Hasher & AddHash (size_t other_hash)
template<typename T >
Hasher & Add (const T &t)
template<typename Iterator >
Hasher & AddRange (Iterator first, Iterator last)
template<typename C >
auto AddRange (C collection) -> decltype(AddRange(std::begin(collection), std::end(collection)))
Static Public Member Functions
template<typename... T>
constexpr static size_t Combine (const T &... ts)
Private Attributes
size_t hash_ = 0
Detailed Description
Definition at line 105 of file hashing.h.
Constructor & Destructor Documentation
Hasher() [1/2]
constexpr v8::base::Hasher::Hasher () [constexpr], [default]
Hasher() [2/2]
constexpr v8::base::Hasher::Hasher (size_t seed) [inline], [explicit], [constexpr]
Definition at line 108 of file hashing.h.
: hash_(seed) {}
Member Function Documentation
Add()
template<typename T >
Hasher& v8::base::Hasher::Add (const T & t) [inline]
Definition at line 121 of file hashing.h.
                          {
    return AddHash(base::hash<T>{}(t));
  }
References AddHash().
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add(), AddRange(), Combine(), v8::internal::CodeEntry::GetHash(), v8::internal::hash_value(), v8::internal::ProfileNode::Hasher::operator()(), v8::internal::wasm::NativeModuleCache::PrefixHash(), and v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader().
AddHash()
Hasher& v8::base::Hasher::AddHash (size_t other_hash) [inline]
Definition at line 114 of file hashing.h.
                                     {
    hash_ = hash_combine(hash_, other_hash);
    return *this;
  }
References hash_, and v8::base::hash_combine().
Referenced by Add().
AddRange() [1/2]
template<typename C >
auto v8::base::Hasher::AddRange (C collection) -> decltype(AddRange(std::begin(collection), std::end(collection))) [inline]
Definition at line 137 of file hashing.h.
                                                                      {
    return AddRange(std::begin(collection), std::end(collection));
  }
References AddRange(), v8::internal::compiler::begin(), and v8::internal::compiler::end().
AddRange() [2/2]
template<typename Iterator >
Hasher& v8::base::Hasher::AddRange (Iterator first, Iterator last) [inline]
Definition at line 127 of file hashing.h.
                                                  {
    // TODO(clemensb): If the iterator returns an integral or POD value smaller
    // than size_t we can combine multiple elements together to get better
    // hashing performance.
    for (; first != last; ++first) Add(*first);
    return *this;
  }
References Add().
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add(), AddRange(), v8::base::hash_range(), v8::internal::hash_value(), v8::base::hash_value(), v8::internal::PerfettoV8String::Hasher::operator()(), v8::internal::wasm::NativeModuleCache::PrefixHash(), and v8::internal::wasm::AsyncStreamingProcessor::ProcessSection().
Combine()
template<typename... T>
constexpr static size_t v8::base::Hasher::Combine (const T &... ts) [inline], [static], [constexpr]
Definition at line 144 of file hashing.h.
                                                  {
    Hasher hasher;
    (..., hasher.Add(ts));
    return hasher.hash();
  }
References Add(), and hash().
Referenced by v8::base::hash_combine(), v8::base::hash_value(), v8::base::hash_value_impl(), v8::internal::CodeDataSourceIncrementalState::Function::Hash::operator()(), v8::internal::PerfettoV8String::Hasher::operator()(), and v8::internal::CodeDataSourceIncrementalState::ScriptUniqueId::Hash::operator()().
hash()
constexpr size_t v8::base::Hasher::hash () const [inline], [constexpr]
Definition at line 111 of file hashing.h.
{ return hash_; }
References hash_.
Referenced by Combine(), v8::internal::CodeEntry::GetHash(), v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::hash(), v8::base::hash_range(), v8::internal::hash_value(), v8::base::hash_value(), v8::internal::wasm::AsyncStreamingProcessor::OnAbort(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::ProfileNode::Hasher::operator()(), v8::internal::PerfettoV8String::Hasher::operator()(), v8::internal::wasm::NativeModuleCache::PrefixHash(), and v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader().
Member Data Documentation
hash_
size_t v8::base::Hasher::hash_ = 0 [private]
Definition at line 151 of file hashing.h.
Referenced by AddHash(), and hash().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/base/hashing.h