v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver Class Reference
Public Member Functions
InstantiateBytesResultResolver (Isolate *isolate, Local< Context > context, Local< Promise::Resolver > promise_resolver, Local< Value > module)
void OnInstantiationSucceeded (i::DirectHandle< i::WasmInstanceObject > instance) override
void OnInstantiationFailed (i::DirectHandle< i::JSAny > error_reason) override
Private Attributes
Isolate * isolate_
Global< Context > context_
Global< Promise::Resolver > promise_resolver_
Global< Value > module_
Static Private Attributes
static constexpr char kGlobalPromiseHandle []
static constexpr char kGlobalModuleHandle []
Detailed Description
Definition at line 365 of file wasm-js.cc.
Constructor & Destructor Documentation
InstantiateBytesResultResolver()
v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver::InstantiateBytesResultResolver (Isolate * isolate, Local< Context > context, Local< Promise::Resolver > promise_resolver, Local< Value > module) [inline]
Definition at line 368 of file wasm-js.cc.
      : isolate_(isolate),
        context_(isolate, context),
        promise_resolver_(isolate, promise_resolver),
        module_(isolate, module) {
    context_.SetWeak();
    promise_resolver_.AnnotateStrongRetainer(kGlobalPromiseHandle);
    module_.AnnotateStrongRetainer(kGlobalModuleHandle);
  }
Member Function Documentation
OnInstantiationFailed()
void v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver::OnInstantiationFailed (i::DirectHandle< i::JSAny > error_reason) [inline], [override]
Definition at line 422 of file wasm-js.cc.
                                                                          {
    if (context_.IsEmpty()) return;
    auto callback = reinterpret_cast<i::Isolate*>(isolate_)
                        ->wasm_async_resolve_promise_callback();
    CHECK(callback);
    callback(isolate_, context_.Get(isolate_), promise_resolver_.Get(isolate_),
             Utils::ToLocal(error_reason), WasmAsyncSuccess::kFail);
  }
References CHECK, and v8::kFail.
OnInstantiationSucceeded()
void v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver::OnInstantiationSucceeded (i::DirectHandle< i::WasmInstanceObject > instance) [inline], [override]
Definition at line 380 of file wasm-js.cc.
                                                            {
    if (context_.IsEmpty()) return;
    Local<Context> context = context_.Get(isolate_);
    WasmAsyncSuccess success = WasmAsyncSuccess::kSuccess;
    // The result is a JSObject with 2 fields which contain the
    // WasmInstanceObject and the WasmModuleObject.
    Local<Object> result = Object::New(isolate_);
    if (V8_UNLIKELY(result
                        ->CreateDataProperty(context,
                                             v8_str(isolate_, "module"),
                                             module_.Get(isolate_))
                        .IsNothing())) {
      i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate_);
      // We assume that a TerminationException is the only reason why
      // `CreateDataProperty` can fail here. We should revisit
      // https://crbug.com/1515227 again if this CHECK fails.
      CHECK(i::IsTerminationException(i_isolate->exception()));
      result = Utils::ToLocal(direct_handle(
          i::Cast<i::JSObject>(i_isolate->exception()), i_isolate));
      success = WasmAsyncSuccess::kFail;
    }
    if (V8_UNLIKELY(result
                        ->CreateDataProperty(
                            context, v8_str(isolate_, "instance"),
                            Utils::ToLocal(i::Cast<i::Object>(instance)))
                        .IsNothing())) {
      i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(isolate_);
      CHECK(i::IsTerminationException(i_isolate->exception()));
      result = Utils::ToLocal(direct_handle(
          i::Cast<i::JSObject>(i_isolate->exception()), i_isolate));
      success = WasmAsyncSuccess::kFail;
    }
    auto callback = reinterpret_cast<i::Isolate*>(isolate_)
                        ->wasm_async_resolve_promise_callback();
    CHECK(callback);
    callback(isolate_, context, promise_resolver_.Get(isolate_), result,
             success);
  }
References CHECK, v8::internal::anonymous_namespace{property-descriptor.cc}::CreateDataProperty(), v8::internal::direct_handle(), v8::internal::Isolate::exception(), v8::kFail, v8::kSuccess, v8::Object::New(), v8::base::internal::result, v8::anonymous_namespace{wasm-js.cc}::v8_str(), and V8_UNLIKELY.
Member Data Documentation
context_
Global<Context> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver::context_ [private]
Definition at line 437 of file wasm-js.cc.
isolate_
Isolate* v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver::isolate_ [private]
Definition at line 436 of file wasm-js.cc.
kGlobalModuleHandle
constexpr char v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver::kGlobalModuleHandle [static], [constexpr], [private]
Initial value:
=
      "InstantiateBytesResultResolver::module_"
Definition at line 434 of file wasm-js.cc.
kGlobalPromiseHandle
constexpr char v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver::kGlobalPromiseHandle [static], [constexpr], [private]
Initial value:
=
      "InstantiateBytesResultResolver::promise_"
Definition at line 432 of file wasm-js.cc.
module_
Global<Value> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver::module_ [private]
Definition at line 439 of file wasm-js.cc.
promise_resolver_
Global<Promise::Resolver> v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::InstantiateBytesResultResolver::promise_resolver_ [private]
Definition at line 438 of file wasm-js.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-js.cc