v8::internal::torque::ClassType Class Reference
#include <types.h>
Public Member Functions
std::string ToExplicitString () const override
std::string GetGeneratedTypeNameImpl () const override
std::string GetGeneratedTNodeTypeNameImpl () const override
bool IsExtern () const
bool ShouldGeneratePrint () const
bool ShouldGenerateVerify () const
bool ShouldGenerateBodyDescriptor () const
bool DoNotGenerateCast () const
bool IsTransient () const override
bool IsAbstract () const
bool IsLayoutDefinedInCpp () const
bool HasSameInstanceTypeAsParent () const
bool ShouldGenerateCppClassDefinitions () const
bool ShouldGenerateCppObjectDefinitionAsserts () const
bool ShouldGenerateCppObjectLayoutDefinitionAsserts () const
bool ShouldGenerateFullClassDefinition () const
bool ShouldGenerateUniqueMap () const
bool ShouldGenerateFactoryFunction () const
bool ShouldExport () const
bool IsShape () const
bool HasStaticSize () const
size_t header_size () const
ResidueClass size () const
const ClassType * GetSuperClass () const
void GenerateAccessors ()
bool AllowInstantiation () const
const Field & RegisterField (Field field) override
void Finalize () const override
std::vector< Field > ComputeAllFields () const
std::vector< Field > ComputeHeaderFields () const
std::vector< Field > ComputeArrayFields () const
std::vector< ObjectSlotKind > ComputeHeaderSlotKinds () const
std::optional< ObjectSlotKind > ComputeArraySlotKind () const
bool HasNoPointerSlotsExceptMap () const
bool HasIndexedFieldsIncludingInParents () const
const Field * GetFieldPreceding (size_t field_index) const
const ClassType * GetClassDeclaringField (const Field &f) const
std::string GetSliceMacroName (const Field &field) const
const InstanceTypeConstraints & GetInstanceTypeConstraints () const
bool IsHighestInstanceTypeWithinParent () const
bool IsLowestInstanceTypeWithinParent () const
bool HasUndefinedLayout () const
SourcePosition GetPosition () const
SourceId AttributedToFile () const
void InitializeInstanceTypes (std::optional< int > own, std::optional< std::pair< int, int >> range) const
std::optional< int > OwnInstanceType () const
std::optional< std::pair< int, int > > InstanceTypeRange () const
Private Member Functions
ClassType (const Type *parent, Namespace *nspace, const std::string &name, ClassFlags flags, const std::string &generates, const ClassDeclaration *decl, const TypeAlias *alias)
void GenerateSliceAccessor (size_t field_index)
Private Attributes
size_t header_size_
ResidueClass size_
ClassFlags flags_
const std::string generates_
const ClassDeclaration * decl_
const TypeAlias * alias_
std::optional< int > own_instance_type_
std::optional< std::pair< int, int > > instance_type_range_
Friends
class TypeOracle
class TypeVisitor
Additional Inherited Members
Detailed Description
Definition at line 672 of file types.h.
Constructor & Destructor Documentation
ClassType()
v8::internal::torque::ClassType::ClassType (const Type * parent, Namespace * nspace, const std::string & name, ClassFlags flags, const std::string & generates, const ClassDeclaration * decl, const TypeAlias * alias) [private]
Definition at line 612 of file types.cc.
    : AggregateType(Kind::kClassType, parent, nspace, name),
      size_(ResidueClass::Unknown()),
      flags_(flags),
      generates_(generates),
      decl_(decl),
      alias_(alias) {}
Member Function Documentation
AllowInstantiation()
bool v8::internal::torque::ClassType::AllowInstantiation () const
Definition at line 634 of file types.cc.
                                         {
  return (!IsExtern() || nspace()->IsDefaultNamespace()) && !IsAbstract();
}
References IsAbstract(), IsExtern(), and v8::internal::torque::AggregateType::nspace().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
AttributedToFile()
SourceId v8::internal::torque::ClassType::AttributedToFile () const
Definition at line 1052 of file types.cc.
                                           {
  bool in_test_directory = StringStartsWith(
      SourceFileMap::PathFromV8Root(GetPosition().source).substr(), "test/");
  if (!in_test_directory && (IsExtern() || ShouldExport())) {
    return GetPosition().source;
  }
  return SourceFileMap::GetSourceId("src/objects/torque-defined-classes.tq");
}
References GetPosition(), v8::internal::torque::SourceFileMap::GetSourceId(), IsExtern(), v8::internal::torque::SourceFileMap::PathFromV8Root(), ShouldExport(), v8::internal::torque::SourcePosition::source, and v8::internal::torque::StringStartsWith().
ComputeAllFields()
std::vector< Field > v8::internal::torque::ClassType::ComputeAllFields () const
Definition at line 648 of file types.cc.
                                                   {
  std::vector<Field> all_fields;
  const ClassType* super_class = this->GetSuperClass();
  if (super_class) {
    all_fields = super_class->ComputeAllFields();
  }
  const std::vector<Field>& fields = this->fields();
  all_fields.insert(all_fields.end(), fields.begin(), fields.end());
  return all_fields;
}
References ComputeAllFields(), v8::internal::torque::AggregateType::fields(), and GetSuperClass().
Referenced by ComputeAllFields(), ComputeArrayFields(), ComputeHeaderFields(), v8::internal::torque::ImplementationVisitor::GenerateArrayLength(), v8::internal::torque::ImplementationVisitor::GenerateLayoutForInitialization(), and v8::internal::torque::ImplementationVisitor::Visit().
ComputeArrayFields()
std::vector< Field > v8::internal::torque::ClassType::ComputeArrayFields () const
Definition at line 671 of file types.cc.
                                                     {
  std::vector<Field> result;
  for (Field& field : ComputeAllFields()) {
    if (!field.index) {
      // The header is allowed to end with an optional padding field of size 0.
      DCHECK(std::get<0>(field.GetFieldSizeInformation()) == 0 ||
             *field.offset < header_size());
      continue;
    }
    result.push_back(std::move(field));
  }
  return result;
}
References ComputeAllFields(), v8::internal::DCHECK(), header_size(), and v8::base::internal::result.
Referenced by ComputeArraySlotKind().
ComputeArraySlotKind()
std::optional< ObjectSlotKind > v8::internal::torque::ClassType::ComputeArraySlotKind () const
Definition at line 757 of file types.cc.
                                                                  {
  std::vector<ObjectSlotKind> kinds;
  ComputeSlotKindsHelper(&kinds, 0, ComputeArrayFields());
  if (kinds.empty()) return std::nullopt;
  std::sort(kinds.begin(), kinds.end());
  if (kinds.front() == kinds.back()) return {kinds.front()};
  if (kinds.front() == ObjectSlotKind::kStrongPointer &&
      kinds.back() == ObjectSlotKind::kMaybeObjectPointer) {
    return ObjectSlotKind::kMaybeObjectPointer;
  }
  Error("Array fields mix types with different GC visitation requirements.")
      .Throw();
}
References ComputeArrayFields(), v8::internal::torque::anonymous_namespace{types.cc}::ComputeSlotKindsHelper(), v8::internal::torque::Error(), v8::internal::torque::kMaybeObjectPointer, v8::internal::torque::kStrongPointer, v8::base::sort(), and v8::internal::torque::MessageBuilder::Throw().
Referenced by HasNoPointerSlotsExceptMap().
ComputeHeaderFields()
std::vector< Field > v8::internal::torque::ClassType::ComputeHeaderFields () const
Definition at line 659 of file types.cc.
                                                      {
  std::vector<Field> result;
  for (Field& field : ComputeAllFields()) {
    if (field.index) break;
    // The header is allowed to end with an optional padding field of size 0.
    DCHECK(std::get<0>(field.GetFieldSizeInformation()) == 0 ||
           *field.offset < header_size());
    result.push_back(std::move(field));
  }
  return result;
}
References ComputeAllFields(), v8::internal::DCHECK(), header_size(), and v8::base::internal::result.
Referenced by ComputeHeaderSlotKinds(), and HasNoPointerSlotsExceptMap().
ComputeHeaderSlotKinds()
std::vector< ObjectSlotKind > v8::internal::torque::ClassType::ComputeHeaderSlotKinds () const
Definition at line 747 of file types.cc.
                                                                  {
  std::vector<ObjectSlotKind> result;
  std::vector<Field> header_fields = ComputeHeaderFields();
  ComputeSlotKindsHelper(&result, 0, header_fields);
  DCHECK_EQ(std::ceil(static_cast<double>(header_size()) /
                      TargetArchitecture::TaggedSize()),
            result.size());
  return result;
}
References ComputeHeaderFields(), v8::internal::torque::anonymous_namespace{types.cc}::ComputeSlotKindsHelper(), DCHECK_EQ, header_size(), v8::base::internal::result, and v8::internal::torque::TargetArchitecture::TaggedSize().
Referenced by HasNoPointerSlotsExceptMap().
DoNotGenerateCast()
bool v8::internal::torque::ClassType::DoNotGenerateCast () const [inline]
Definition at line 699 of file types.h.
                                 {
    return flags_ & ClassFlag::kDoNotGenerateCast;
  }
References flags_, and v8::internal::torque::kDoNotGenerateCast.
Finalize()
void v8::internal::torque::ClassType::Finalize () const [override], [virtual]
Implements v8::internal::torque::AggregateType.
Definition at line 638 of file types.cc.
                               {
  if (is_finalized_) return;
  CurrentScope::Scope scope_activator(alias_->ParentScope());
  CurrentSourcePosition::Scope position_activator(decl_->pos);
  TypeVisitor::VisitClassFieldsAndMethods(const_cast<ClassType*>(this),
                                          this->decl_);
  is_finalized_ = true;
  CheckForDuplicateFields();
}
References alias_, v8::internal::torque::AggregateType::CheckForDuplicateFields(), decl_, v8::internal::torque::AggregateType::is_finalized_, v8::internal::torque::Declarable::ParentScope(), v8::internal::torque::AstNode::pos, and v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods().
Referenced by header_size(), and size().
GenerateAccessors()
void v8::internal::torque::ClassType::GenerateAccessors ()
Definition at line 818 of file types.cc.
                                  {
  bool at_or_after_indexed_field = false;
  if (const ClassType* parent = GetSuperClass()) {
    at_or_after_indexed_field = parent->HasIndexedFieldsIncludingInParents();
  }
  // For each field, construct AST snippets that implement a CSA accessor
  // function. The implementation iterator will turn the snippets into code.
  for (size_t field_index = 0; field_index < fields_.size(); ++field_index) {
    Field& field = fields_[field_index];
    if (field.name_and_type.type == TypeOracle::GetVoidType()) {
      continue;
    }
    at_or_after_indexed_field =
        at_or_after_indexed_field || field.index.has_value();
    CurrentSourcePosition::Scope position_activator(field.pos);
    IdentifierExpression* parameter = MakeIdentifierExpression("o");
    IdentifierExpression* index = MakeIdentifierExpression("i");
    std::string camel_field_name = CamelifyString(field.name_and_type.name);
    if (at_or_after_indexed_field) {
      if (!field.index.has_value()) {
        // There's no fundamental reason we couldn't generate functions to get
        // references instead of slices, but it's not yet implemented.
        ReportError(
            "Torque doesn't yet support non-indexed fields after indexed "
            "fields");
      }
      GenerateSliceAccessor(field_index);
    }
    // For now, only generate indexed accessors for simple types
    if (field.index.has_value() && field.name_and_type.type->IsStructType()) {
      continue;
    }
    // An explicit index is only used for indexed fields not marked as optional.
    // Optional fields implicitly load or store item zero.
    bool use_index = field.index && !field.index->optional;
    // Load accessor
    std::string load_macro_name = "Load" + this->name() + camel_field_name;
    Signature load_signature;
    load_signature.parameter_names.push_back(MakeNode<Identifier>("o"));
    load_signature.parameter_types.types.push_back(this);
    if (use_index) {
      load_signature.parameter_names.push_back(MakeNode<Identifier>("i"));
      load_signature.parameter_types.types.push_back(
          TypeOracle::GetIntPtrType());
    }
    load_signature.parameter_types.var_args = false;
    load_signature.return_type = field.name_and_type.type;
    Expression* load_expression =
        MakeFieldAccessExpression(parameter, field.name_and_type.name);
    if (use_index) {
      load_expression =
          MakeNode<ElementAccessExpression>(load_expression, index);
    }
    Statement* load_body = MakeNode<ReturnStatement>(load_expression);
    Declarations::DeclareMacro(load_macro_name, true, std::nullopt,
                               load_signature, load_body, std::nullopt);
    // Store accessor
    if (!field.const_qualified) {
      IdentifierExpression* value = MakeIdentifierExpression("v");
      std::string store_macro_name = "Store" + this->name() + camel_field_name;
      Signature store_signature;
      store_signature.parameter_names.push_back(MakeNode<Identifier>("o"));
      store_signature.parameter_types.types.push_back(this);
      if (use_index) {
        store_signature.parameter_names.push_back(MakeNode<Identifier>("i"));
        store_signature.parameter_types.types.push_back(
            TypeOracle::GetIntPtrType());
      }
      store_signature.parameter_names.push_back(MakeNode<Identifier>("v"));
      store_signature.parameter_types.types.push_back(field.name_and_type.type);
      store_signature.parameter_types.var_args = false;
      // TODO(danno): Store macros probably should return their value argument
      store_signature.return_type = TypeOracle::GetVoidType();
      Expression* store_expression =
          MakeFieldAccessExpression(parameter, field.name_and_type.name);
      if (use_index) {
        store_expression =
            MakeNode<ElementAccessExpression>(store_expression, index);
      }
      Statement* store_body = MakeNode<ExpressionStatement>(
          MakeNode<AssignmentExpression>(store_expression, value));
      Declarations::DeclareMacro(store_macro_name, true, std::nullopt,
                                 store_signature, store_body, std::nullopt,
                                 false);
    }
  }
}
References v8::internal::torque::CamelifyString(), v8::internal::torque::Field::const_qualified, v8::internal::torque::Declarations::DeclareMacro(), v8::internal::torque::AggregateType::fields_, GenerateSliceAccessor(), v8::internal::torque::TypeOracle::GetIntPtrType(), GetSuperClass(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::index, v8::internal::torque::Field::index, v8::internal::torque::TypeBase::IsStructType(), v8::internal::torque::MakeFieldAccessExpression(), v8::internal::torque::MakeIdentifierExpression(), v8::internal::torque::NameAndType::name, v8::internal::torque::AggregateType::name(), v8::internal::torque::Field::name_and_type, v8::internal::torque::Signature::parameter_names, v8::internal::torque::Signature::parameter_types, v8::internal::torque::Type::parent(), v8::internal::torque::Field::pos, v8::internal::torque::ReportError(), v8::internal::torque::Signature::return_type, v8::internal::string, v8::internal::torque::NameAndType::type, v8::internal::torque::ParameterTypes::types, v8::internal::value, and v8::internal::torque::ParameterTypes::var_args.
Referenced by v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods().
GenerateSliceAccessor()
void v8::internal::torque::ClassType::GenerateSliceAccessor (size_t field_index) [private]
Definition at line 915 of file types.cc.
                                                        {
  // Generate a Torque macro for getting a Slice to this field. This macro can
  // be called by the dot operator for this field. In Torque, this function for
  // class "ClassName" and field "field_name" and field type "FieldType" would
  // be written as one of the following:
  //
  // If the field has a known offset (in this example, 16):
  // FieldSliceClassNameFieldName(o: ClassName) {
  // return torque_internal::unsafe::New{Const,Mutable}Slice<FieldType>(
  // /*object:*/ o,
  // /*offset:*/ 16,
  // /*length:*/ torque_internal::%IndexedFieldLength<ClassName>(
  // o, "field_name")
  //);
  // }
  //
  // If the field has an unknown offset, and the previous field is named p, is
  // not const, and is of type PType with size 4:
  // FieldSliceClassNameFieldName(o: ClassName) {
  // const previous = %FieldSlice<ClassName, MutableSlice<PType>>(o, "p");
  // return torque_internal::unsafe::New{Const,Mutable}Slice<FieldType>(
  // /*object:*/ o,
  // /*offset:*/ previous.offset + 4 * previous.length,
  // /*length:*/ torque_internal::%IndexedFieldLength<ClassName>(
  // o, "field_name")
  //);
  // }
  const Field& field = fields_[field_index];
  std::string macro_name = GetSliceMacroName(field);
  Signature signature;
  Identifier* parameter_identifier = MakeNode<Identifier>("o");
  signature.parameter_names.push_back(parameter_identifier);
  signature.parameter_types.types.push_back(this);
  signature.parameter_types.var_args = false;
  signature.return_type =
      field.const_qualified
          ? TypeOracle::GetConstSliceType(field.name_and_type.type)
          : TypeOracle::GetMutableSliceType(field.name_and_type.type);
  std::vector<Statement*> statements;
  Expression* offset_expression = nullptr;
  IdentifierExpression* parameter =
      MakeNode<IdentifierExpression>(parameter_identifier);
  if (field.offset.has_value()) {
    offset_expression =
        MakeNode<IntegerLiteralExpression>(IntegerLiteral(*field.offset));
  } else {
    const Field* previous = GetFieldPreceding(field_index);
    DCHECK_NOT_NULL(previous);
    const Type* previous_slice_type =
        previous->const_qualified
            ? TypeOracle::GetConstSliceType(previous->name_and_type.type)
            : TypeOracle::GetMutableSliceType(previous->name_and_type.type);
    // %FieldSlice<ClassName, MutableSlice<PType>>(o, "p")
    Expression* previous_expression = MakeCallExpression(
        MakeIdentifierExpression(
            {"torque_internal"}, "%FieldSlice",
            {MakeNode<PrecomputedTypeExpression>(this),
             MakeNode<PrecomputedTypeExpression>(previous_slice_type)}),
        {parameter, MakeNode<StringLiteralExpression>(
                        StringLiteralQuote(previous->name_and_type.name))});
    // const previous = %FieldSlice<ClassName, MutableSlice<PType>>(o, "p");
    Statement* define_previous =
        MakeConstDeclarationStatement("previous", previous_expression);
    statements.push_back(define_previous);
    // 4
    size_t previous_element_size;
    std::tie(previous_element_size, std::ignore) =
        *SizeOf(previous->name_and_type.type);
    Expression* previous_element_size_expression =
        MakeNode<IntegerLiteralExpression>(
            IntegerLiteral(previous_element_size));
    // previous.length
    Expression* previous_length_expression = MakeFieldAccessExpression(
        MakeIdentifierExpression("previous"), "length");
    // previous.offset
    Expression* previous_offset_expression = MakeFieldAccessExpression(
        MakeIdentifierExpression("previous"), "offset");
    // 4 * previous.length
    // In contrast to the code used for allocation, we don't need overflow
    // checks here because we already know all the offsets fit into memory.
    offset_expression = MakeCallExpression(
        "*", {previous_element_size_expression, previous_length_expression});
    // previous.offset + 4 * previous.length
    offset_expression = MakeCallExpression(
        "+", {previous_offset_expression, offset_expression});
  }
  // torque_internal::%IndexedFieldLength<ClassName>(o, "field_name")
  Expression* length_expression = MakeCallExpression(
      MakeIdentifierExpression({"torque_internal"}, "%IndexedFieldLength",
                               {MakeNode<PrecomputedTypeExpression>(this)}),
      {parameter, MakeNode<StringLiteralExpression>(
                      StringLiteralQuote(field.name_and_type.name))});
  // torque_internal::unsafe::New{Const,Mutable}Slice<FieldType>(
  // /*object:*/ o,
  // /*offset:*/ <<offset_expression>>,
  // /*length:*/ torque_internal::%IndexedFieldLength<ClassName>(
  // o, "field_name")
  //)
  IdentifierExpression* new_struct = MakeIdentifierExpression(
      {"torque_internal", "unsafe"},
      field.const_qualified ? "NewConstSlice" : "NewMutableSlice",
      {MakeNode<PrecomputedTypeExpression>(field.name_and_type.type)});
  Expression* slice_expression = MakeCallExpression(
      new_struct, {parameter, offset_expression, length_expression});
  statements.push_back(MakeNode<ReturnStatement>(slice_expression));
  Statement* block =
      MakeNode<BlockStatement>(/*deferred=*/false, std::move(statements));
  Macro* macro = Declarations::DeclareMacro(macro_name, true, std::nullopt,
                                            signature, block, std::nullopt);
  if (this->ShouldGenerateCppObjectLayoutDefinitionAsserts()) {
    GlobalContext::EnsureInCCDebugOutputList(TorqueMacro::cast(macro),
                                             macro->Position().source);
  } else {
    GlobalContext::EnsureInCCOutputList(TorqueMacro::cast(macro),
                                        macro->Position().source);
  }
}
References v8::internal::torque::Field::const_qualified, DCHECK_NOT_NULL, v8::internal::torque::Declarations::DeclareMacro(), v8::internal::torque::GlobalContext::EnsureInCCDebugOutputList(), v8::internal::torque::GlobalContext::EnsureInCCOutputList(), v8::internal::torque::AggregateType::fields_, v8::internal::torque::TypeOracle::GetConstSliceType(), GetFieldPreceding(), v8::internal::torque::TypeOracle::GetMutableSliceType(), GetSliceMacroName(), wasm::ignore(), v8::internal::torque::MakeCallExpression(), v8::internal::torque::MakeConstDeclarationStatement(), v8::internal::torque::MakeFieldAccessExpression(), v8::internal::torque::MakeIdentifierExpression(), v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::internal::torque::Field::offset, v8::internal::torque::Signature::parameter_names, v8::internal::torque::Signature::parameter_types, v8::internal::torque::Declarable::Position(), v8::internal::torque::Signature::return_type, ShouldGenerateCppObjectLayoutDefinitionAsserts(), v8::internal::torque::SizeOf(), v8::internal::torque::SourcePosition::source, v8::internal::string, v8::internal::torque::StringLiteralQuote(), v8::internal::torque::NameAndType::type, v8::internal::torque::ParameterTypes::types, and v8::internal::torque::ParameterTypes::var_args.
Referenced by GenerateAccessors().
GetClassDeclaringField()
const ClassType * v8::internal::torque::ClassType::GetClassDeclaringField (const Field & f) const
Definition at line 805 of file types.cc.
                                                                       {
  for (const Field& field : fields_) {
    if (f.name_and_type.name == field.name_and_type.name) return this;
  }
  return GetSuperClass()->GetClassDeclaringField(f);
}
References v8::internal::torque::AggregateType::fields_, GetClassDeclaringField(), GetSuperClass(), v8::internal::torque::NameAndType::name, and v8::internal::torque::Field::name_and_type.
Referenced by GetClassDeclaringField(), and GetSliceMacroName().
GetFieldPreceding()
const Field * v8::internal::torque::ClassType::GetFieldPreceding (size_t field_index) const
Definition at line 795 of file types.cc.
                                                                  {
  if (field_index > 0) {
    return &fields_[field_index - 1];
  }
  if (const ClassType* parent = GetSuperClass()) {
    return parent->GetFieldPreceding(parent->fields_.size());
  }
  return nullptr;
}
References v8::internal::torque::AggregateType::fields_, GetSuperClass(), and v8::internal::torque::Type::parent().
Referenced by GenerateSliceAccessor().
GetGeneratedTNodeTypeNameImpl()
std::string v8::internal::torque::ClassType::GetGeneratedTNodeTypeNameImpl () const [override], [virtual]
Reimplemented from v8::internal::torque::AggregateType.
Definition at line 623 of file types.cc.
                                                         {
  return generates_;
}
References generates_.
GetGeneratedTypeNameImpl()
std::string v8::internal::torque::ClassType::GetGeneratedTypeNameImpl () const [override], [virtual]
Reimplemented from v8::internal::torque::AggregateType.
Definition at line 627 of file types.cc.
                                                    {
  return IsConstexpr() ? GetGeneratedTNodeTypeName()
                       : "TNode<" + GetGeneratedTNodeTypeName() + ">";
}
References v8::internal::torque::Type::GetGeneratedTNodeTypeName(), and v8::internal::torque::Type::IsConstexpr().
GetInstanceTypeConstraints()
const InstanceTypeConstraints& v8::internal::torque::ClassType::GetInstanceTypeConstraints () const [inline]
Definition at line 771 of file types.h.
                                                                    {
    return decl_->instance_type_constraints;
  }
References decl_, and v8::internal::torque::ClassDeclaration::instance_type_constraints.
Referenced by v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PropagateInstanceTypeConstraints().
GetPosition()
SourcePosition v8::internal::torque::ClassType::GetPosition () const [inline]
Definition at line 783 of file types.h.
{ return decl_->pos; }
References decl_, and v8::internal::torque::AstNode::pos.
Referenced by AttributedToFile(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PrintInstanceTypes(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PropagateInstanceTypeConstraints(), and v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::SelectOwnValues().
GetSliceMacroName()
std::string v8::internal::torque::ClassType::GetSliceMacroName (const Field & field) const
Definition at line 812 of file types.cc.
                                                               {
  const ClassType* declarer = GetClassDeclaringField(field);
  return "FieldSlice" + declarer->name() +
         CamelifyString(field.name_and_type.name);
}
References v8::internal::torque::CamelifyString(), GetClassDeclaringField(), v8::internal::torque::NameAndType::name, v8::internal::torque::AggregateType::name(), and v8::internal::torque::Field::name_and_type.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GenerateClassFieldVerifier(), v8::internal::torque::ImplementationVisitor::GenerateFieldReference(), and GenerateSliceAccessor().
GetSuperClass()
const ClassType* v8::internal::torque::ClassType::GetSuperClass () const [inline]
Definition at line 742 of file types.h.
                                         {
    if (parent() == nullptr) return nullptr;
    return parent()->IsClassType() ? ClassType::DynamicCast(parent()) : nullptr;
  }
References v8::internal::torque::TypeBase::IsClassType(), and v8::internal::torque::Type::parent().
Referenced by v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::BuildInstanceTypeTree(), ComputeAllFields(), GenerateAccessors(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClassConstructors(), v8::internal::torque::ImplementationVisitor::GenerateClassVerifiers(), GetClassDeclaringField(), GetFieldPreceding(), HasIndexedFieldsIncludingInParents(), v8::internal::torque::ImplementationVisitor::InitializeClass(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PrintInstanceTypes(), and v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods().
HasIndexedFieldsIncludingInParents()
bool v8::internal::torque::ClassType::HasIndexedFieldsIncludingInParents () const
Definition at line 785 of file types.cc.
                                                         {
  for (const auto& field : fields_) {
    if (field.index.has_value()) return true;
  }
  if (const ClassType* parent = GetSuperClass()) {
    return parent->HasIndexedFieldsIncludingInParents();
  }
  return false;
}
References v8::internal::torque::AggregateType::fields_, GetSuperClass(), and v8::internal::torque::Type::parent().
HasNoPointerSlotsExceptMap()
bool v8::internal::torque::ClassType::HasNoPointerSlotsExceptMap () const
Definition at line 771 of file types.cc.
                                                 {
  const auto header_slot_kinds = ComputeHeaderSlotKinds();
  DCHECK_GE(header_slot_kinds.size(), 1);
  DCHECK_EQ(ComputeHeaderFields()[0].name_and_type.type,
            TypeOracle::GetMapType());
  for (size_t i = 1; i < header_slot_kinds.size(); ++i) {
    if (header_slot_kinds[i] != ObjectSlotKind::kNoPointer) return false;
  }
  if (auto slot = ComputeArraySlotKind()) {
    if (*slot != ObjectSlotKind::kNoPointer) return false;
  }
  return true;
}
References ComputeArraySlotKind(), ComputeHeaderFields(), ComputeHeaderSlotKinds(), DCHECK_EQ, DCHECK_GE, v8::internal::torque::TypeOracle::GetMapType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::torque::kNoPointer.
HasSameInstanceTypeAsParent()
bool v8::internal::torque::ClassType::HasSameInstanceTypeAsParent () const [inline]
Definition at line 707 of file types.h.
                                           {
    return flags_ & ClassFlag::kHasSameInstanceTypeAsParent;
  }
References flags_, and v8::internal::torque::kHasSameInstanceTypeAsParent.
Referenced by v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PropagateInstanceTypeConstraints().
HasStaticSize()
bool v8::internal::torque::ClassType::HasStaticSize () const
Definition at line 1047 of file types.cc.
                                    {
  if (IsSubtypeOf(TypeOracle::GetJSObjectType()) && !IsShape()) return false;
  return size().SingleValue().has_value();
}
References v8::internal::torque::TypeOracle::GetJSObjectType(), IsShape(), v8::internal::torque::Type::IsSubtypeOf(), v8::internal::torque::ResidueClass::SingleValue(), and size().
HasUndefinedLayout()
bool v8::internal::torque::ClassType::HasUndefinedLayout () const [inline]
Definition at line 780 of file types.h.
                                  {
    return flags_ & ClassFlag::kUndefinedLayout;
  }
References flags_, and v8::internal::torque::kUndefinedLayout.
Referenced by v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PrintInstanceTypes(), ShouldGeneratePrint(), and ShouldGenerateVerify().
header_size()
size_t v8::internal::torque::ClassType::header_size () const [inline]
Definition at line 734 of file types.h.
                             {
    if (!is_finalized_) Finalize();
    return header_size_;
  }
References Finalize(), header_size_, and v8::internal::torque::AggregateType::is_finalized_.
Referenced by ComputeArrayFields(), ComputeHeaderFields(), ComputeHeaderSlotKinds(), and v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods().
InitializeInstanceTypes()
void v8::internal::torque::ClassType::InitializeInstanceTypes (std::optional< int > own, std::optional< std::pair< int, int >> range) const
Definition at line 685 of file types.cc.
                                                                      {
  DCHECK(!own_instance_type_.has_value());
  DCHECK(!instance_type_range_.has_value());
  own_instance_type_ = own;
  instance_type_range_ = range;
}
References v8::internal::DCHECK(), instance_type_range_, and own_instance_type_.
InstanceTypeRange()
std::optional< std::pair< int, int > > v8::internal::torque::ClassType::InstanceTypeRange () const
Definition at line 698 of file types.cc.
                                                                  {
  DCHECK(GlobalContext::IsInstanceTypesInitialized());
  return instance_type_range_;
}
References v8::internal::DCHECK(), instance_type_range_, and v8::internal::torque::GlobalContext::IsInstanceTypesInitialized().
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GetClassInstanceTypeRange().
IsAbstract()
bool v8::internal::torque::ClassType::IsAbstract () const [inline]
Definition at line 703 of file types.h.
{ return flags_ & ClassFlag::kAbstract; }
References flags_, and v8::internal::torque::kAbstract.
Referenced by AllowInstantiation(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PropagateInstanceTypeConstraints(), ShouldGenerateBodyDescriptor(), ShouldGenerateFactoryFunction(), ShouldGeneratePrint(), and ShouldGenerateUniqueMap().
IsExtern()
bool v8::internal::torque::ClassType::IsExtern () const [inline]
Definition at line 678 of file types.h.
{ return flags_ & ClassFlag::kExtern; }
References flags_, and v8::internal::torque::kExtern.
Referenced by AllowInstantiation(), AttributedToFile(), v8::internal::torque::TypeVisitor::ComputeType(), ShouldGenerateBodyDescriptor(), ShouldGenerateCppClassDefinitions(), ShouldGenerateFullClassDefinition(), ShouldGeneratePrint(), ShouldGenerateUniqueMap(), ShouldGenerateVerify(), and v8::internal::torque::ImplementationVisitor::Visit().
IsHighestInstanceTypeWithinParent()
bool v8::internal::torque::ClassType::IsHighestInstanceTypeWithinParent () const [inline]
Definition at line 774 of file types.h.
                                                 {
    return flags_ & ClassFlag::kHighestInstanceTypeWithinParent;
  }
References flags_, and v8::internal::torque::kHighestInstanceTypeWithinParent.
IsLayoutDefinedInCpp()
bool v8::internal::torque::ClassType::IsLayoutDefinedInCpp () const [inline]
Definition at line 704 of file types.h.
                                    {
    return flags_ & ClassFlag::kCppObjectLayoutDefinition;
  }
References flags_, and v8::internal::torque::kCppObjectLayoutDefinition.
IsLowestInstanceTypeWithinParent()
bool v8::internal::torque::ClassType::IsLowestInstanceTypeWithinParent () const [inline]
Definition at line 777 of file types.h.
                                                {
    return flags_ & ClassFlag::kLowestInstanceTypeWithinParent;
  }
References flags_, and v8::internal::torque::kLowestInstanceTypeWithinParent.
IsShape()
bool v8::internal::torque::ClassType::IsShape () const [inline]
Definition at line 732 of file types.h.
{ return flags_ & ClassFlag::kIsShape; }
References flags_, and v8::internal::torque::kIsShape.
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::ClassFieldOffsetGenerator::FirstFieldStart(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GenerateClassConstructors(), HasStaticSize(), ShouldGenerateVerify(), and v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods().
IsTransient()
bool v8::internal::torque::ClassType::IsTransient () const [inline], [override], [virtual]
Reimplemented from v8::internal::torque::Type.
Definition at line 702 of file types.h.
{ return flags_ & ClassFlag::kTransient; }
References flags_, and v8::internal::torque::kTransient.
OwnInstanceType()
std::optional< int > v8::internal::torque::ClassType::OwnInstanceType () const
Definition at line 693 of file types.cc.
                                                  {
  DCHECK(GlobalContext::IsInstanceTypesInitialized());
  return own_instance_type_;
}
References v8::internal::DCHECK(), v8::internal::torque::GlobalContext::IsInstanceTypesInitialized(), and own_instance_type_.
RegisterField()
const Field& v8::internal::torque::ClassType::RegisterField (Field field) [inline], [override], [virtual]
Reimplemented from v8::internal::torque::AggregateType.
Definition at line 748 of file types.h.
                                                   {
    return AggregateType::RegisterField(field);
  }
References v8::internal::torque::AggregateType::RegisterField().
Referenced by v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods().
ShouldExport()
bool v8::internal::torque::ClassType::ShouldExport () const [inline]
Definition at line 731 of file types.h.
{ return flags_ & ClassFlag::kExport; }
References flags_, and v8::internal::torque::kExport.
Referenced by AttributedToFile(), v8::internal::torque::TypeVisitor::ComputeType(), and ShouldGenerateFactoryFunction().
ShouldGenerateBodyDescriptor()
bool v8::internal::torque::ClassType::ShouldGenerateBodyDescriptor () const [inline]
Definition at line 693 of file types.h.
                                            {
    if (flags_ & ClassFlag::kCppObjectDefinition) return false;
    if (flags_ & ClassFlag::kCppObjectLayoutDefinition) return false;
    if (flags_ & ClassFlag::kGenerateBodyDescriptor) return true;
    return !IsAbstract() && !IsExtern();
  }
References flags_, IsAbstract(), IsExtern(), v8::internal::torque::kCppObjectDefinition, v8::internal::torque::kCppObjectLayoutDefinition, and v8::internal::torque::kGenerateBodyDescriptor.
ShouldGenerateCppClassDefinitions()
bool v8::internal::torque::ClassType::ShouldGenerateCppClassDefinitions () const [inline]
Definition at line 710 of file types.h.
                                                 {
    if (flags_ & ClassFlag::kCppObjectDefinition) return false;
    if (flags_ & ClassFlag::kCppObjectLayoutDefinition) return false;
    return (flags_ & ClassFlag::kGenerateCppClassDefinitions) || !IsExtern();
  }
References flags_, IsExtern(), v8::internal::torque::kCppObjectDefinition, v8::internal::torque::kCppObjectLayoutDefinition, and v8::internal::torque::kGenerateCppClassDefinitions.
Referenced by ShouldGeneratePrint(), and ShouldGenerateVerify().
ShouldGenerateCppObjectDefinitionAsserts()
bool v8::internal::torque::ClassType::ShouldGenerateCppObjectDefinitionAsserts () const [inline]
Definition at line 715 of file types.h.
                                                        {
    return flags_ & ClassFlag::kCppObjectDefinition;
  }
References flags_, and v8::internal::torque::kCppObjectDefinition.
ShouldGenerateCppObjectLayoutDefinitionAsserts()
bool v8::internal::torque::ClassType::ShouldGenerateCppObjectLayoutDefinitionAsserts () const [inline]
Definition at line 718 of file types.h.
                                                              {
    return flags_ & ClassFlag::kCppObjectLayoutDefinition &&
           flags_ & ClassFlag::kGenerateCppClassDefinitions;
  }
References flags_, v8::internal::torque::kCppObjectLayoutDefinition, and v8::internal::torque::kGenerateCppClassDefinitions.
Referenced by GenerateSliceAccessor().
ShouldGenerateFactoryFunction()
bool v8::internal::torque::ClassType::ShouldGenerateFactoryFunction () const [inline]
Definition at line 727 of file types.h.
                                             {
    return (flags_ & ClassFlag::kGenerateFactoryFunction) ||
           (ShouldExport() && !IsAbstract());
  }
References flags_, IsAbstract(), v8::internal::torque::kGenerateFactoryFunction, and ShouldExport().
ShouldGenerateFullClassDefinition()
bool v8::internal::torque::ClassType::ShouldGenerateFullClassDefinition () const [inline]
Definition at line 722 of file types.h.
{ return !IsExtern(); }
References IsExtern().
ShouldGeneratePrint()
bool v8::internal::torque::ClassType::ShouldGeneratePrint () const [inline]
Definition at line 679 of file types.h.
                                   {
    if (flags_ & ClassFlag::kCppObjectDefinition) return false;
    if (flags_ & ClassFlag::kCppObjectLayoutDefinition) return false;
    if (!IsExtern()) return true;
    if (!ShouldGenerateCppClassDefinitions()) return false;
    return !IsAbstract() && !HasUndefinedLayout();
  }
References flags_, HasUndefinedLayout(), IsAbstract(), IsExtern(), v8::internal::torque::kCppObjectDefinition, v8::internal::torque::kCppObjectLayoutDefinition, and ShouldGenerateCppClassDefinitions().
ShouldGenerateUniqueMap()
bool v8::internal::torque::ClassType::ShouldGenerateUniqueMap () const [inline]
Definition at line 723 of file types.h.
                                       {
    return (flags_ & ClassFlag::kGenerateUniqueMap) ||
           (!IsExtern() && !IsAbstract());
  }
References flags_, IsAbstract(), IsExtern(), and v8::internal::torque::kGenerateUniqueMap.
ShouldGenerateVerify()
bool v8::internal::torque::ClassType::ShouldGenerateVerify () const [inline]
Definition at line 686 of file types.h.
                                    {
    if (flags_ & ClassFlag::kCppObjectDefinition) return false;
    if (flags_ & ClassFlag::kCppObjectLayoutDefinition) return false;
    if (!IsExtern()) return true;
    if (!ShouldGenerateCppClassDefinitions()) return false;
    return !HasUndefinedLayout() && !IsShape();
  }
References flags_, HasUndefinedLayout(), IsExtern(), IsShape(), v8::internal::torque::kCppObjectDefinition, v8::internal::torque::kCppObjectLayoutDefinition, and ShouldGenerateCppClassDefinitions().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateClassVerifiers().
size()
ResidueClass v8::internal::torque::ClassType::size () const [inline]
Definition at line 738 of file types.h.
                            {
    if (!is_finalized_) Finalize();
    return size_;
  }
References Finalize(), v8::internal::torque::AggregateType::is_finalized_, and size_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateLayoutForInitialization(), HasStaticSize(), and v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods().
ToExplicitString()
std::string v8::internal::torque::ClassType::ToExplicitString () const [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 632 of file types.cc.
{ return "class " + name(); }
References v8::internal::torque::AggregateType::name().
Friends And Related Function Documentation
TypeOracle
friend class TypeOracle [friend]
Definition at line 795 of file types.h.
TypeVisitor
friend class TypeVisitor [friend]
Definition at line 796 of file types.h.
Member Data Documentation
alias_
const TypeAlias* v8::internal::torque::ClassType::alias_ [private]
Definition at line 808 of file types.h.
Referenced by Finalize().
decl_
const ClassDeclaration* v8::internal::torque::ClassType::decl_ [private]
Definition at line 807 of file types.h.
Referenced by Finalize(), GetInstanceTypeConstraints(), and GetPosition().
flags_
ClassFlags v8::internal::torque::ClassType::flags_ [mutable], [private]
Definition at line 805 of file types.h.
Referenced by DoNotGenerateCast(), HasSameInstanceTypeAsParent(), HasUndefinedLayout(), IsAbstract(), IsExtern(), IsHighestInstanceTypeWithinParent(), IsLayoutDefinedInCpp(), IsLowestInstanceTypeWithinParent(), IsShape(), IsTransient(), ShouldExport(), ShouldGenerateBodyDescriptor(), ShouldGenerateCppClassDefinitions(), ShouldGenerateCppObjectDefinitionAsserts(), ShouldGenerateCppObjectLayoutDefinitionAsserts(), ShouldGenerateFactoryFunction(), ShouldGeneratePrint(), ShouldGenerateUniqueMap(), and ShouldGenerateVerify().
generates_
const std::string v8::internal::torque::ClassType::generates_ [private]
Definition at line 806 of file types.h.
Referenced by GetGeneratedTNodeTypeNameImpl().
header_size_
size_t v8::internal::torque::ClassType::header_size_ [private]
Definition at line 803 of file types.h.
Referenced by header_size(), and v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods().
instance_type_range_
std::optional<std::pair<int, int> > v8::internal::torque::ClassType::instance_type_range_ [mutable], [private]
Definition at line 810 of file types.h.
Referenced by InitializeInstanceTypes(), and InstanceTypeRange().
own_instance_type_
std::optional<int> v8::internal::torque::ClassType::own_instance_type_ [mutable], [private]
Definition at line 809 of file types.h.
Referenced by InitializeInstanceTypes(), and OwnInstanceType().
size_
ResidueClass v8::internal::torque::ClassType::size_ [private]
Definition at line 804 of file types.h.
Referenced by size(), and v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/types.h
/mnt/V8SourceCode/src/torque/types.cc