v8::internal::HeapVerifier Class Reference
#include <heap-verifier.h>
Static Public Member Functions
static void VerifyHeap (Heap *heap)
static void VerifyReadOnlyHeap (Heap *heap)
static void VerifySharedHeap (Heap *heap, Isolate *initiator)
static void VerifyRememberedSetFor (Heap *heap, Tagged< HeapObject > object)
static void VerifySafeMapTransition (Heap *heap, Tagged< HeapObject > object, Tagged< Map > new_map)
static void VerifyObjectLayoutChange (Heap *heap, Tagged< HeapObject > object, Tagged< Map > new_map)
static void VerifyObjectLayoutChangeIsAllowed (Heap *heap, Tagged< HeapObject > object)
static void VerifyHeapIfEnabled (Heap *heap)
Private Member Functions
HeapVerifier ()
Detailed Description
Definition at line 36 of file heap-verifier.h.
Constructor & Destructor Documentation
HeapVerifier()
v8::internal::HeapVerifier::HeapVerifier () [private]
Member Function Documentation
VerifyHeap()
static void v8::internal::HeapVerifier::VerifyHeap (Heap * heap) [inline], [static]
Definition at line 66 of file heap-verifier.h.
{}
Referenced by v8::internal::ReadOnlyHeap::OnCreateHeapObjectsComplete(), v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting(), and VerifyHeapIfEnabled().
VerifyHeapIfEnabled()
static void v8::internal::HeapVerifier::VerifyHeapIfEnabled (Heap * heap) [inline], [static]
Definition at line 78 of file heap-verifier.h.
                                                        {
    if (v8_flags.verify_heap) {
      VerifyHeap(heap);
    }
  }
References v8::internal::v8_flags, and VerifyHeap().
Referenced by v8::internal::Heap::PerformHeapVerification(), and v8::internal::Heap::TearDownWithSharedHeap().
VerifyObjectLayoutChange()
static void v8::internal::HeapVerifier::VerifyObjectLayoutChange (Heap * heap, Tagged< HeapObject > object, Tagged< Map > new_map) [inline], [static]
Definition at line 72 of file heap-verifier.h.
                                                            {}
Referenced by v8::internal::HeapObject::set_map().
VerifyObjectLayoutChangeIsAllowed()
static void v8::internal::HeapVerifier::VerifyObjectLayoutChangeIsAllowed (Heap * heap, Tagged< HeapObject > object) [inline], [static]
Definition at line 74 of file heap-verifier.h.
                                                                           {}
VerifyReadOnlyHeap()
static void v8::internal::HeapVerifier::VerifyReadOnlyHeap (Heap * heap) [inline], [static]
Definition at line 67 of file heap-verifier.h.
{}
Referenced by v8::internal::ReadOnlyHeap::OnCreateHeapObjectsComplete().
VerifyRememberedSetFor()
static void v8::internal::HeapVerifier::VerifyRememberedSetFor (Heap * heap, Tagged< HeapObject > object) [inline], [static]
Definition at line 69 of file heap-verifier.h.
{}
VerifySafeMapTransition()
static void v8::internal::HeapVerifier::VerifySafeMapTransition (Heap * heap, Tagged< HeapObject > object, Tagged< Map > new_map) [inline], [static]
Definition at line 70 of file heap-verifier.h.
                                                           {}
Referenced by v8::internal::HeapObject::set_map().
VerifySharedHeap()
static void v8::internal::HeapVerifier::VerifySharedHeap (Heap * heap, Isolate * initiator) [inline], [static]
Definition at line 68 of file heap-verifier.h.
{}
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/heap-verifier.h