v8::internal::anonymous_namespace{runtime-wasm.cc}::ClearThreadInWasmScope Class Reference
Public Member Functions
ClearThreadInWasmScope (Isolate *isolate)
~ClearThreadInWasmScope ()
Private Attributes
Isolate * isolate_
const bool is_thread_in_wasm_
Detailed Description
Definition at line 108 of file runtime-wasm.cc.
Constructor & Destructor Documentation
ClearThreadInWasmScope()
v8::internal::anonymous_namespace{runtime-wasm.cc}::ClearThreadInWasmScope::ClearThreadInWasmScope (Isolate * isolate) [inline], [explicit]
Definition at line 110 of file runtime-wasm.cc.
      : isolate_(isolate), is_thread_in_wasm_(trap_handler::IsThreadInWasm()) {
    // In some cases we call this from Wasm code inlined into JavaScript
    // so the flag might not be set.
    if (is_thread_in_wasm_) {
      trap_handler::ClearThreadInWasm();
    }
#if V8_ENABLE_DRUMBRAKE
    if (v8_flags.wasm_enable_exec_time_histograms && v8_flags.slow_histograms &&
        !v8_flags.wasm_jitless) {
      isolate->wasm_execution_timer()->Stop();
    }
#endif // V8_ENABLE_DRUMBRAKE
  }
References v8::internal::trap_handler::ClearThreadInWasm(), and v8::internal::v8_flags.
 ClearThreadInWasmScope()
v8::internal::anonymous_namespace{runtime-wasm.cc}::ClearThreadInWasmScope::~ClearThreadInWasmScope () [inline]
Definition at line 125 of file runtime-wasm.cc.
                            {
    trap_handler::AssertThreadNotInWasm();
    if (!isolate_->has_exception() && is_thread_in_wasm_) {
      trap_handler::SetThreadInWasm();
#if V8_ENABLE_DRUMBRAKE
      if (v8_flags.wasm_enable_exec_time_histograms &&
          v8_flags.slow_histograms && !v8_flags.wasm_jitless) {
        isolate_->wasm_execution_timer()->Start();
      }
#endif // V8_ENABLE_DRUMBRAKE
    }
    // Otherwise we only want to set the flag if the exception is caught in
    // wasm. This is handled by the unwinder.
  }
References v8::internal::trap_handler::AssertThreadNotInWasm(), v8::internal::trap_handler::SetThreadInWasm(), and v8::internal::v8_flags.
Member Data Documentation
is_thread_in_wasm_
const bool v8::internal::anonymous_namespace{runtime-wasm.cc}::ClearThreadInWasmScope::is_thread_in_wasm_ [private]
Definition at line 143 of file runtime-wasm.cc.
isolate_
Isolate* v8::internal::anonymous_namespace{runtime-wasm.cc}::ClearThreadInWasmScope::isolate_ [private]
Definition at line 142 of file runtime-wasm.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/runtime/runtime-wasm.cc