v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor Class Reference
Static Public Member Functions
static Handle< Object > ConvertArgumentsStoreResult (Isolate *isolate, DirectHandle< SloppyArgumentsElements > elements, Handle< Object > result)
static void SloppyDeleteImpl (Isolate *isolate, DirectHandle< JSObject > obj, DirectHandle< SloppyArgumentsElements > elements, InternalIndex entry)
static Maybe< bool > AddImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity)
static void ReconfigureImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes)
Additional Inherited Members
Detailed Description
Definition at line 5231 of file elements.cc.
Member Function Documentation
AddImpl()
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::AddImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity) [inline], [static]
Definition at line 5263 of file elements.cc.
                                                    {
    DirectHandle<SloppyArgumentsElements> elements(
        Cast<SloppyArgumentsElements>(object->elements()), isolate);
    DirectHandle<FixedArrayBase> old_arguments(elements->arguments(), isolate);
    DirectHandle<NumberDictionary> dictionary =
        IsNumberDictionary(*old_arguments)
            ? Cast<NumberDictionary>(old_arguments)
            : JSObject::NormalizeElements(isolate, object);
    PropertyDetails details(PropertyKind::kData, attributes,
                            PropertyCellType::kNoCell);
    DirectHandle<NumberDictionary> new_dictionary =
        NumberDictionary::Add(isolate, dictionary, index, value, details);
    if (attributes != NONE) object->RequireSlowElements(*new_dictionary);
    if (*dictionary != *new_dictionary) {
      elements->set_arguments(*new_dictionary);
    }
    return Just(true);
  }
References v8::bigint::Add(), v8::internal::Cast< NumberDictionary >(), v8::internal::index, v8::Just(), v8::internal::kData, v8::internal::kNoCell, v8::internal::NONE, v8::internal::JSObject::NormalizeElements(), and v8::internal::value.
ConvertArgumentsStoreResult()
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::ConvertArgumentsStoreResult (Isolate * isolate, DirectHandle< SloppyArgumentsElements > elements, Handle< Object > result) [inline], [static]
Definition at line 5236 of file elements.cc.
                             {
    // Elements of the arguments object in slow mode might be slow aliases.
    if (IsAliasedArgumentsEntry(*result)) {
      DisallowGarbageCollection no_gc;
      Tagged<AliasedArgumentsEntry> alias =
          Cast<AliasedArgumentsEntry>(*result);
      Tagged<Context> context = elements->context();
      int context_entry = alias->aliased_context_slot();
      DCHECK(!IsTheHole(context->GetNoCell(context_entry), isolate));
      return handle(context->GetNoCell(context_entry), isolate);
    }
    return result;
  }
References v8::internal::DCHECK(), v8::internal::handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
ReconfigureImpl()
static void v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::ReconfigureImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes) [inline], [static]
Definition at line 5285 of file elements.cc.
                                                             {
    auto elements = Cast<SloppyArgumentsElements>(store);
    uint32_t length = elements->length();
    if (entry.as_uint32() < length) {
      Tagged<Object> probe =
          elements->mapped_entries(entry.as_uint32(), kRelaxedLoad);
      DCHECK(!IsTheHole(probe, isolate));
      Tagged<Context> context = elements->context();
      int context_entry = Smi::ToInt(probe);
      DCHECK(!IsTheHole(context->GetNoCell(context_entry), isolate));
      context->SetNoCell(context_entry, *value);
      // Redefining attributes of an aliased element destroys fast aliasing.
      elements->set_mapped_entries(entry.as_uint32(),
                                   ReadOnlyRoots(isolate).the_hole_value());
      // For elements that are still writable we re-establish slow aliasing.
      if ((attributes & READ_ONLY) == 0) {
        value = isolate->factory()->NewAliasedArgumentsEntry(context_entry);
      }
      PropertyDetails details(PropertyKind::kData, attributes,
                              PropertyCellType::kNoCell);
      DirectHandle<NumberDictionary> arguments(
          Cast<NumberDictionary>(elements->arguments()), isolate);
      arguments = NumberDictionary::Add(isolate, arguments, entry.as_uint32(),
                                        value, details);
      // If the attributes were NONE, we would have called set rather than
      // reconfigure.
      DCHECK_NE(NONE, attributes);
      object->RequireSlowElements(*arguments);
      elements->set_arguments(*arguments);
    } else {
      DirectHandle<FixedArrayBase> arguments(elements->arguments(), isolate);
      DictionaryElementsAccessor::ReconfigureImpl(isolate, object, arguments,
                                                  entry.adjust_down(length),
                                                  value, attributes);
    }
  }
References v8::bigint::Add(), v8::internal::InternalIndex::adjust_down(), v8::internal::InternalIndex::as_uint32(), v8::internal::Cast< NumberDictionary >(), v8::internal::DCHECK(), DCHECK_NE, v8::internal::Isolate::factory(), v8::internal::kData, v8::internal::kNoCell, v8::kRelaxedLoad, v8::internal::length, v8::internal::Factory::NewAliasedArgumentsEntry(), v8::internal::NONE, v8::internal::READ_ONLY, store(), v8::internal::Smi::ToInt(), and v8::internal::value.
SloppyDeleteImpl()
static void v8::internal::anonymous_namespace{elements.cc}::SlowSloppyArgumentsElementsAccessor::SloppyDeleteImpl (Isolate * isolate, DirectHandle< JSObject > obj, DirectHandle< SloppyArgumentsElements > elements, InternalIndex entry) [inline], [static]
Definition at line 5251 of file elements.cc.
                                                    {
    // No need to delete a context mapped entry from the arguments elements.
    if (entry.is_not_found()) return;
    DirectHandle<NumberDictionary> dict(
        Cast<NumberDictionary>(elements->arguments()), isolate);
    uint32_t length = elements->length();
    dict =
        NumberDictionary::DeleteEntry(isolate, dict, entry.adjust_down(length));
    elements->set_arguments(*dict);
  }
References v8::internal::InternalIndex::adjust_down(), v8::internal::Cast< NumberDictionary >(), v8::internal::InternalIndex::is_not_found(), and v8::internal::length.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/elements.cc