v8::internal::EternalHandles Class Reference
#include <global-handles.h>
Public Member Functions
EternalHandles ()=default
~EternalHandles ()
EternalHandles (const EternalHandles &)=delete
EternalHandles & operator= (const EternalHandles &)=delete
V8_EXPORT_PRIVATE void Create (Isolate *isolate, Tagged< Object > object, int *index)
IndirectHandle< Object > Get (int index)
void IterateAllRoots (RootVisitor *visitor)
void IterateYoungRoots (RootVisitor *visitor)
void PostGarbageCollectionProcessing ()
size_t handles_count () const
Private Member Functions
Address * GetLocation (int index)
Private Attributes
int size_ = 0
std::vector< Address * > blocks_
std::vector< int > young_node_indices_
Static Private Attributes
static const int kInvalidIndex = -1
static const int kShift = 8
static const int kSize = 1 << kShift
static const int kMask = 0xff
Detailed Description
Definition at line 192 of file global-handles.h.
Constructor & Destructor Documentation
EternalHandles() [1/2]
v8::internal::EternalHandles::EternalHandles () [default]
 EternalHandles()
v8::internal::EternalHandles::~EternalHandles ()
Definition at line 1010 of file global-handles.cc.
                                {
  for (Address* block : blocks_) delete[] block;
}
EternalHandles() [2/2]
v8::internal::EternalHandles::EternalHandles (const EternalHandles &) [delete]
Member Function Documentation
Create()
void v8::internal::EternalHandles::Create (Isolate * isolate, Tagged< Object > object, int * index)
Definition at line 1043 of file global-handles.cc.
                                        {
  DCHECK_EQ(kInvalidIndex, *index);
  if (object == Tagged<Object>()) return;
  Tagged<Object> the_hole = ReadOnlyRoots(isolate).the_hole_value();
  DCHECK_NE(the_hole, object);
  int block = size_ >> kShift;
  int offset = size_ & kMask;
  // Need to resize.
  if (offset == 0) {
    Address* next_block = new Address[kSize];
    MemsetPointer(FullObjectSlot(next_block), the_hole, kSize);
    blocks_.push_back(next_block);
  }
  DCHECK_EQ(the_hole.ptr(), blocks_[block][offset]);
  blocks_[block][offset] = object.ptr();
  if (HeapLayout::InYoungGeneration(object)) {
    young_node_indices_.push_back(size_);
  }
  *index = size_++;
}
References DCHECK_EQ, DCHECK_NE, v8::internal::index, v8::internal::HeapLayout::InYoungGeneration(), v8::internal::GlobalHandles::isolate(), v8::internal::trap_handler::kInvalidIndex, v8::internal::MemsetPointer(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::api_internal::Eternalize().
Get()
IndirectHandle<Object> v8::internal::EternalHandles::Get (int index) [inline]
Definition at line 204 of file global-handles.h.
                                               {
    return IndirectHandle<Object>(GetLocation(index));
  }
References GetLocation(), and v8::internal::index.
Referenced by v8::api_internal::Eternalize().
GetLocation()
Address* v8::internal::EternalHandles::GetLocation (int index) [inline], [private]
Definition at line 225 of file global-handles.h.
                                         {
    DCHECK(index >= 0 && index < size_);
    return &blocks_[index >> kShift][index & kMask];
  }
References blocks_, v8::internal::DCHECK(), v8::internal::index, kMask, kShift, and size_.
Referenced by Get().
handles_count()
size_t v8::internal::EternalHandles::handles_count () const [inline]
Definition at line 215 of file global-handles.h.
{ return size_; }
References size_.
Referenced by v8::internal::Heap::CollectAllAvailableGarbage().
IterateAllRoots()
void v8::internal::EternalHandles::IterateAllRoots (RootVisitor * visitor)
Definition at line 1014 of file global-handles.cc.
                                                         {
  int limit = size_;
  for (Address* block : blocks_) {
    DCHECK_GT(limit, 0);
    visitor->VisitRootPointers(
        Root::kEternalHandles, nullptr, FullObjectSlot(block),
        FullObjectSlot(block + std::min({limit, kSize})));
    limit -= kSize;
  }
}
References DCHECK_GT, and v8::internal::RootVisitor::VisitRootPointers().
Referenced by v8::internal::SerializedHandleChecker::CheckGlobalAndEternalHandles(), and v8::internal::Heap::IterateRoots().
IterateYoungRoots()
void v8::internal::EternalHandles::IterateYoungRoots (RootVisitor * visitor)
Definition at line 1025 of file global-handles.cc.
                                                           {
  for (int index : young_node_indices_) {
    visitor->VisitRootPointer(Root::kEternalHandles, nullptr,
                              FullObjectSlot(GetLocation(index)));
  }
}
References v8::internal::index, and v8::internal::RootVisitor::VisitRootPointer().
Referenced by v8::internal::Heap::IterateRoots().
operator=()
EternalHandles& v8::internal::EternalHandles::operator= (const EternalHandles &) [delete]
PostGarbageCollectionProcessing()
void v8::internal::EternalHandles::PostGarbageCollectionProcessing ()
Definition at line 1032 of file global-handles.cc.
                                                     {
  size_t last = 0;
  for (int index : young_node_indices_) {
    if (HeapLayout::InYoungGeneration(Tagged<Object>(*GetLocation(index)))) {
      young_node_indices_[last++] = index;
    }
  }
  DCHECK_LE(last, young_node_indices_.size());
  young_node_indices_.resize(last);
}
References DCHECK_LE, v8::internal::index, and v8::internal::HeapLayout::InYoungGeneration().
Referenced by v8::internal::Heap::PerformGarbageCollection().
Member Data Documentation
blocks_
std::vector<Address*> v8::internal::EternalHandles::blocks_ [private]
Definition at line 231 of file global-handles.h.
Referenced by GetLocation().
kInvalidIndex
const int v8::internal::EternalHandles::kInvalidIndex = -1 [static], [private]
Definition at line 218 of file global-handles.h.
kMask
const int v8::internal::EternalHandles::kMask = 0xff [static], [private]
Definition at line 221 of file global-handles.h.
Referenced by GetLocation().
kShift
const int v8::internal::EternalHandles::kShift = 8 [static], [private]
Definition at line 219 of file global-handles.h.
Referenced by GetLocation().
kSize
const int v8::internal::EternalHandles::kSize = 1 << kShift [static], [private]
Definition at line 220 of file global-handles.h.
size_
int v8::internal::EternalHandles::size_ = 0 [private]
Definition at line 230 of file global-handles.h.
Referenced by GetLocation(), and handles_count().
young_node_indices_
std::vector<int> v8::internal::EternalHandles::young_node_indices_ [private]
Definition at line 232 of file global-handles.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/handles/global-handles.h
/mnt/V8SourceCode/src/handles/global-handles.cc