v8::SerializationDataQueue Class Reference
#include <d8.h>
Public Member Functions
void Enqueue (std::unique_ptr< SerializationData > data)
bool Dequeue (std::unique_ptr< SerializationData > *data)
bool IsEmpty ()
void Clear ()
Private Attributes
base::Mutex mutex_
std::vector< std::unique_ptr< SerializationData > > data_
Detailed Description
Definition at line 175 of file d8.h.
Member Function Documentation
Clear()
void v8::SerializationDataQueue::Clear ()
Definition at line 5360 of file d8.cc.
                                   {
  base::MutexGuard lock_guard(&mutex_);
  data_.clear();
}
Dequeue()
bool v8::SerializationDataQueue::Dequeue (std::unique_ptr< SerializationData > * data)
Definition at line 5345 of file d8.cc.
                                                {
  out_data->reset();
  base::MutexGuard lock_guard(&mutex_);
  if (data_.empty()) return false;
  *out_data = std::move(data_[0]);
  data_.erase(data_.begin());
  return true;
}
Referenced by v8::Worker::GetMessage(), and v8::Worker::TryGetMessage().
Enqueue()
void v8::SerializationDataQueue::Enqueue (std::unique_ptr< SerializationData > data)
Definition at line 5340 of file d8.cc.
                                                                          {
  base::MutexGuard lock_guard(&mutex_);
  data_.push_back(std::move(data));
}
Referenced by v8::Worker::ExecuteInThread(), and v8::Worker::PostMessageOut().
IsEmpty()
bool v8::SerializationDataQueue::IsEmpty ()
Definition at line 5355 of file d8.cc.
                                     {
  base::MutexGuard lock_guard(&mutex_);
  return data_.empty();
}
Member Data Documentation
data_
std::vector<std::unique_ptr<SerializationData> > v8::SerializationDataQueue::data_ [private]
Definition at line 184 of file d8.h.
mutex_
base::Mutex v8::SerializationDataQueue::mutex_ [private]
Definition at line 183 of file d8.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/d8/d8.h
/mnt/V8SourceCode/src/d8/d8.cc