v8::internal::maglev::ControlNode Class Reference
#include <maglev-ir.h>
Public Member Functions
ControlNode * next_post_dominating_hole () const
void set_next_post_dominating_hole (ControlNode *node)
Protected Member Functions
NodeBase (uint64_t bitfield)
Private Attributes
ControlNode * next_post_dominating_hole_ = nullptr
Additional Inherited Members
Detailed Description
Definition at line 11193 of file maglev-ir.h.
Member Function Documentation
next_post_dominating_hole()
ControlNode* v8::internal::maglev::ControlNode::next_post_dominating_hole () const [inline]
Definition at line 11201 of file maglev-ir.h.
                                                 {
    return next_post_dominating_hole_;
  }
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateRegisters(), v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::HighestPostDominatingHole(), and v8::internal::maglev::anonymous_namespace{maglev-regalloc.cc}::NearestPostDominatingHole().
NodeBase()
v8::internal::maglev::NodeBase::NodeBase [inline], [explicit], [protected]
Definition at line 2334 of file maglev-ir.h.
: bitfield_(bitfield) {}
set_next_post_dominating_hole()
void v8::internal::maglev::ControlNode::set_next_post_dominating_hole (ControlNode * node) [inline]
Definition at line 11204 of file maglev-ir.h.
                                                        {
    DCHECK_IMPLIES(node != nullptr, node->Is<UnconditionalControlNode>() ||
                                        node->Is<TerminalControlNode>() ||
                                        node->Is<Switch>());
    next_post_dominating_hole_ = node;
  }
References DCHECK_IMPLIES, and v8::internal::maglev::NodeBase::Is().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::ComputePostDominatingHoles().
Member Data Documentation
next_post_dominating_hole_
ControlNode* v8::internal::maglev::ControlNode::next_post_dominating_hole_ = nullptr [private]
Definition at line 11215 of file maglev-ir.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h