v8::Serializer Class Reference
Public Member Functions
Serializer (Isolate *isolate)
Serializer (const Serializer &)=delete
Serializer & operator= (const Serializer &)=delete
Maybe< bool > WriteValue (Local< Context > context, Local< Value > value, Local< Value > transfer)
std::unique_ptr< SerializationData > Release ()
void AppendBackingStoresTo (std::vector< std::shared_ptr< BackingStore >> *to)
Protected Member Functions
void ThrowDataCloneError (Local< String > message) override
Handles the case where a DataCloneError would be thrown in the structured clone spec.
Maybe< uint32_t > GetSharedArrayBufferId (Isolate *isolate, Local< SharedArrayBuffer > shared_array_buffer) override
Called when the ValueSerializer is going to serialize a SharedArrayBuffer object.
Maybe< uint32_t > GetWasmModuleTransferId (Isolate *isolate, Local< WasmModuleObject > module) override
void * ReallocateBufferMemory (void *old_buffer, size_t size, size_t *actual_size) override
Allocates memory for the buffer of at least the size provided.
void FreeBufferMemory (void *buffer) override
Frees a buffer allocated with |ReallocateBufferMemory|.
bool AdoptSharedValueConveyor (Isolate *isolate, SharedValueConveyor &&conveyor) override
Called when the first shared value is serialized.
Private Member Functions
Maybe< bool > PrepareTransfer (Local< Context > context, Local< Value > transfer)
Maybe< bool > FinalizeTransfer ()
Private Attributes
Isolate * isolate_
ValueSerializer serializer_
std::unique_ptr< SerializationData > data_
std::vector< Global< ArrayBuffer > > array_buffers_
std::vector< Global< SharedArrayBuffer > > shared_array_buffers_
std::vector< Global< WasmModuleObject > > wasm_modules_
std::vector< std::shared_ptr< v8::BackingStore > > backing_stores_
size_t current_memory_usage_
Detailed Description
Definition at line 6332 of file d8.cc.
Constructor & Destructor Documentation
Serializer() [1/2]
v8::Serializer::Serializer (Isolate * isolate) [inline], [explicit]
Definition at line 6334 of file d8.cc.
      : isolate_(isolate),
        serializer_(isolate, this),
        current_memory_usage_(0) {}
Serializer() [2/2]
v8::Serializer::Serializer (const Serializer &) [delete]
Member Function Documentation
AdoptSharedValueConveyor()
bool v8::Serializer::AdoptSharedValueConveyor (Isolate * isolate, SharedValueConveyor && conveyor) [inline], [override], [protected], [virtual]
Called when the first shared value is serialized.
All subsequent shared values will use the same conveyor.
The embedder must ensure the lifetime of the conveyor matches the lifetime of the serialized data.
If the embedder supports serializing shared values, this method should return true. Otherwise the embedder should throw an exception and return false.
This method is called at most once per serializer.
Reimplemented from v8::ValueSerializer::Delegate.
Definition at line 6428 of file d8.cc.
                                                                         {
    data_->shared_value_conveyor_.emplace(std::move(conveyor));
    return true;
  }
AppendBackingStoresTo()
void v8::Serializer::AppendBackingStoresTo (std::vector< std::shared_ptr< BackingStore >> * to) [inline]
Definition at line 6369 of file d8.cc.
                                                                         {
    to->insert(to->end(), std::make_move_iterator(backing_stores_.begin()),
               std::make_move_iterator(backing_stores_.end()));
    backing_stores_.clear();
  }
FinalizeTransfer()
Maybe<bool> v8::Serializer::FinalizeTransfer () [inline], [private]
Definition at line 6473 of file d8.cc.
                                 {
    for (const auto& global_array_buffer : array_buffers_) {
      Local<ArrayBuffer> array_buffer =
          Local<ArrayBuffer>::New(isolate_, global_array_buffer);
      if (!array_buffer->IsDetachable()) {
        isolate_->ThrowError(
            "ArrayBuffer is not detachable and could not be transferred");
        return Nothing<bool>();
      }
      auto backing_store = array_buffer->GetBackingStore();
      data_->backing_stores_.push_back(std::move(backing_store));
      if (array_buffer->Detach(v8::Local<v8::Value>()).IsNothing()) {
        return Nothing<bool>();
      }
    }
    return Just(true);
  }
References v8::Worker::isolate_, v8::Just(), v8::Local< T >::New(), and v8::Isolate::ThrowError().
FreeBufferMemory()
void v8::Serializer::FreeBufferMemory (void * buffer) [inline], [override], [protected], [virtual]
Frees a buffer allocated with |ReallocateBufferMemory|.
The default implementation uses the stdlib's free() function.
Reimplemented from v8::ValueSerializer::Delegate.
Definition at line 6426 of file d8.cc.
{ base::Free(buffer); }
References v8::base::Free().
GetSharedArrayBufferId()
Maybe<uint32_t> v8::Serializer::GetSharedArrayBufferId (Isolate * isolate, Local< SharedArrayBuffer > shared_array_buffer) [inline], [override], [protected], [virtual]
Called when the ValueSerializer is going to serialize a SharedArrayBuffer object.
The embedder must return an ID for the object, using the same ID if this SharedArrayBuffer has already been serialized in this buffer. When deserializing, this ID will be passed to ValueDeserializer::GetSharedArrayBufferFromId as |clone_id|.
If the object cannot be serialized, an exception should be thrown and Nothing<uint32_t>() returned.
Reimplemented from v8::ValueSerializer::Delegate.
Definition at line 6381 of file d8.cc.
                                                                               {
    DCHECK_NOT_NULL(data_);
    for (size_t index = 0; index < shared_array_buffers_.size(); ++index) {
      if (shared_array_buffers_[index] == shared_array_buffer) {
        return Just<uint32_t>(static_cast<uint32_t>(index));
      }
    }
    size_t index = shared_array_buffers_.size();
    shared_array_buffers_.emplace_back(isolate_, shared_array_buffer);
    data_->sab_backing_stores_.push_back(
        shared_array_buffer->GetBackingStore());
    return Just<uint32_t>(static_cast<uint32_t>(index));
  }
References DCHECK_NOT_NULL, v8::internal::index, and v8::Worker::isolate_.
GetWasmModuleTransferId()
Maybe<uint32_t> v8::Serializer::GetWasmModuleTransferId (Isolate * isolate, Local< WasmModuleObject > module) [inline], [override], [protected], [virtual]
Reimplemented from v8::ValueSerializer::Delegate.
Definition at line 6397 of file d8.cc.
                                                                 {
    DCHECK_NOT_NULL(data_);
    for (size_t index = 0; index < wasm_modules_.size(); ++index) {
      if (wasm_modules_[index] == module) {
        return Just<uint32_t>(static_cast<uint32_t>(index));
      }
    }
    size_t index = wasm_modules_.size();
    wasm_modules_.emplace_back(isolate_, module);
    data_->compiled_wasm_modules_.push_back(module->GetCompiledModule());
    return Just<uint32_t>(static_cast<uint32_t>(index));
  }
References DCHECK_NOT_NULL, v8::internal::index, and v8::Worker::isolate_.
operator=()
Serializer& v8::Serializer::operator= (const Serializer &) [delete]
PrepareTransfer()
Maybe<bool> v8::Serializer::PrepareTransfer (Local< Context > context, Local< Value > transfer) [inline], [private]
Definition at line 6435 of file d8.cc.
                                                                             {
    if (transfer->IsArray()) {
      Local<Array> transfer_array = transfer.As<Array>();
      uint32_t length = transfer_array->Length();
      for (uint32_t i = 0; i < length; ++i) {
        Local<Value> element;
        if (transfer_array->Get(context, i).ToLocal(&element)) {
          if (!element->IsArrayBuffer()) {
            isolate_->ThrowError(
                "Transfer array elements must be an ArrayBuffer");
            return Nothing<bool>();
          }
          Local<ArrayBuffer> array_buffer = element.As<ArrayBuffer>();
          if (std::find(array_buffers_.begin(), array_buffers_.end(),
                        array_buffer) != array_buffers_.end()) {
            isolate_->ThrowError(
                "ArrayBuffer occurs in the transfer array more than once");
            return Nothing<bool>();
          }
          serializer_.TransferArrayBuffer(
              static_cast<uint32_t>(array_buffers_.size()), array_buffer);
          array_buffers_.emplace_back(isolate_, array_buffer);
        } else {
          return Nothing<bool>();
        }
      }
      return Just(true);
    } else if (transfer->IsUndefined()) {
      return Just(true);
    } else {
      isolate_->ThrowError("Transfer list must be an Array or undefined");
      return Nothing<bool>();
    }
  }
References v8::Local< T >::As(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::Worker::isolate_, v8::Just(), v8::internal::length, and v8::Isolate::ThrowError().
ReallocateBufferMemory()
void* v8::Serializer::ReallocateBufferMemory (void * old_buffer, size_t size, size_t * actual_size) [inline], [override], [protected], [virtual]
Allocates memory for the buffer of at least the size provided.
The actual size (which may be greater or equal) is written to |actual_size|. If no buffer has been allocated yet, nullptr will be provided.
If the memory cannot be allocated, nullptr should be returned. |actual_size| will be ignored. It is assumed that |old_buffer| is still valid in this case and has not been modified.
The default implementation uses the stdlib's realloc() function.
Reimplemented from v8::ValueSerializer::Delegate.
Definition at line 6412 of file d8.cc.
                                                             {
    // Not accurate, because we don't take into account reallocated buffers,
    // but this is fine for testing.
    current_memory_usage_ += size;
    if (current_memory_usage_ > Shell::options.max_serializer_memory) {
      return nullptr;
    }
    void* result = base::Realloc(old_buffer, size);
    *actual_size = result ? size : 0;
    return result;
  }
References v8::Shell::options, v8::base::Realloc(), v8::base::internal::result, and size().
Release()
std::unique_ptr<SerializationData> v8::Serializer::Release () [inline]
Definition at line 6367 of file d8.cc.
{ return std::move(data_); }
Referenced by v8::Shell::SerializeValue().
ThrowDataCloneError()
void v8::Serializer::ThrowDataCloneError (Local< String > message) [inline], [override], [protected], [virtual]
Handles the case where a DataCloneError would be thrown in the structured clone spec.
Other V8 embedders may throw some other appropriate exception type.
Implements v8::ValueSerializer::Delegate.
Definition at line 6377 of file d8.cc.
                                                           {
    isolate_->ThrowException(Exception::Error(message));
  }
References v8::Exception::Error(), v8::Worker::isolate_, and v8::Isolate::ThrowException().
WriteValue()
Maybe<bool> v8::Serializer::WriteValue (Local< Context > context, Local< Value > value, Local< Value > transfer) [inline]
Definition at line 6342 of file d8.cc.
                                                {
    bool ok;
    DCHECK(!data_);
    data_.reset(new SerializationData);
    if (!PrepareTransfer(context, transfer).To(&ok)) {
      return Nothing<bool>();
    }
    serializer_.WriteHeader();
    if (!serializer_.WriteValue(context, value).To(&ok)) {
      data_.reset();
      return Nothing<bool>();
    }
    if (!FinalizeTransfer().To(&ok)) {
      return Nothing<bool>();
    }
    std::pair<uint8_t*, size_t> pair = serializer_.Release();
    data_->data_.reset(pair.first);
    data_->size_ = pair.second;
    return Just(true);
  }
References DCHECK, v8::Just(), and v8::internal::value.
Referenced by v8::Shell::SerializeValue().
Member Data Documentation
array_buffers_
std::vector<Global<ArrayBuffer> > v8::Serializer::array_buffers_ [private]
Definition at line 6497 of file d8.cc.
backing_stores_
std::vector<std::shared_ptr<v8::BackingStore> > v8::Serializer::backing_stores_ [private]
Definition at line 6500 of file d8.cc.
current_memory_usage_
size_t v8::Serializer::current_memory_usage_ [private]
Definition at line 6501 of file d8.cc.
data_
std::unique_ptr<SerializationData> v8::Serializer::data_ [private]
Definition at line 6496 of file d8.cc.
isolate_
Isolate* v8::Serializer::isolate_ [private]
Definition at line 6494 of file d8.cc.
serializer_
ValueSerializer v8::Serializer::serializer_ [private]
Definition at line 6495 of file d8.cc.
shared_array_buffers_
std::vector<Global<SharedArrayBuffer> > v8::Serializer::shared_array_buffers_ [private]
Definition at line 6498 of file d8.cc.
wasm_modules_
std::vector<Global<WasmModuleObject> > v8::Serializer::wasm_modules_ [private]
Definition at line 6499 of file d8.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/d8/d8.cc