v8::internal::FunctionLiteral Class Reference
#include <ast.h>
Public Types
enum ParameterFlag : uint8_t { kNoDuplicateParameters
, kHasDuplicateParameters
 }
enum EagerCompileHint : uint8_t { kShouldEagerCompile
, kShouldLazyCompile
 }
Public Member Functions
template<typename IsolateT >
MaybeHandle< String > GetName (IsolateT *isolate) const
bool has_shared_name () const
const AstConsString * raw_name () const
void set_raw_name (const AstConsString *name)
DeclarationScope * scope () const
ZonePtrList< Statement > * body ()
void set_function_token_position (int pos)
int function_token_position () const
int start_position () const
int end_position () const
bool is_anonymous_expression () const
bool is_toplevel () const
V8_EXPORT_PRIVATE LanguageMode language_mode () const
void add_expected_properties (int number_properties)
int expected_property_count ()
int parameter_count ()
int function_length ()
bool AllowsLazyCompilation ()
bool CanSuspend ()
std::unique_ptr< char[]> GetDebugName () const
Handle< String > GetInferredName (Isolate *isolate)
Handle< String > GetInferredName (LocalIsolate *isolate) const
Handle< SharedFunctionInfo > shared_function_info () const
void set_shared_function_info (Handle< SharedFunctionInfo > shared_function_info)
const AstConsString * raw_inferred_name ()
void set_raw_inferred_name (AstConsString *raw_inferred_name)
bool pretenure () const
void set_pretenure ()
bool has_duplicate_parameters () const
bool should_parallel_compile () const
void set_should_parallel_compile ()
V8_EXPORT_PRIVATE bool ShouldEagerCompile () const
V8_EXPORT_PRIVATE void SetShouldEagerCompile ()
FunctionSyntaxKind syntax_kind () const
FunctionKind kind () const
bool IsAnonymousFunctionDefinition () const
int suspend_count ()
void set_suspend_count (int suspend_count)
int return_position ()
int function_literal_id () const
void set_function_literal_id (int function_literal_id)
void set_requires_instance_members_initializer (bool value)
bool requires_instance_members_initializer () const
void set_has_static_private_methods_or_accessors (bool value)
bool has_static_private_methods_or_accessors () const
void set_class_scope_has_private_brand (bool value)
bool class_scope_has_private_brand () const
bool private_name_lookup_skips_outer_class () const
ProducedPreparseData * produced_preparse_data () const
Private Types
using FunctionSyntaxKindBits = Expression::NextBitField< FunctionSyntaxKind, 3 >
using Pretenure = FunctionSyntaxKindBits::Next< bool, 1 >
using HasDuplicateParameters = Pretenure::Next< bool, 1 >
using RequiresInstanceMembersInitializer = HasDuplicateParameters::Next< bool, 1 >
using HasStaticPrivateMethodsOrAccessorsField = RequiresInstanceMembersInitializer::Next< bool, 1 >
using HasBracesField = HasStaticPrivateMethodsOrAccessorsField::Next< bool, 1 >
using ShouldParallelCompileField = HasBracesField::Next< bool, 1 >
Private Member Functions
FunctionLiteral (Zone *zone, const AstConsString *name, AstValueFactory *ast_value_factory, DeclarationScope *scope, const ScopedPtrList< Statement > &body, int expected_property_count, int parameter_count, int function_length, FunctionSyntaxKind function_syntax_kind, ParameterFlag has_duplicate_parameters, EagerCompileHint eager_compile_hint, int position, bool has_braces, int function_literal_id, ProducedPreparseData *produced_preparse_data=nullptr)
Private Attributes
friend Zone
int expected_property_count_
int parameter_count_
int function_length_
int function_token_position_
int suspend_count_
int function_literal_id_
const AstConsString * raw_name_
DeclarationScope * scope_
ZonePtrList< Statement > body_
AstConsString * raw_inferred_name_
IndirectHandle< SharedFunctionInfo > shared_function_info_
ProducedPreparseData * produced_preparse_data_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 2297 of file ast.h.
Member Typedef Documentation
FunctionSyntaxKindBits
using v8::internal::FunctionLiteral::FunctionSyntaxKindBits = Expression::NextBitField<FunctionSyntaxKind, 3> [private]
Definition at line 2471 of file ast.h.
HasBracesField
using v8::internal::FunctionLiteral::HasBracesField = HasStaticPrivateMethodsOrAccessorsField::Next<bool, 1> [private]
Definition at line 2479 of file ast.h.
HasDuplicateParameters
using v8::internal::FunctionLiteral::HasDuplicateParameters = Pretenure::Next<bool, 1> [private]
Definition at line 2474 of file ast.h.
HasStaticPrivateMethodsOrAccessorsField
using v8::internal::FunctionLiteral::HasStaticPrivateMethodsOrAccessorsField = RequiresInstanceMembersInitializer::Next<bool, 1> [private]
Definition at line 2477 of file ast.h.
Pretenure
using v8::internal::FunctionLiteral::Pretenure = FunctionSyntaxKindBits::Next<bool, 1> [private]
Definition at line 2473 of file ast.h.
RequiresInstanceMembersInitializer
using v8::internal::FunctionLiteral::RequiresInstanceMembersInitializer = HasDuplicateParameters::Next<bool, 1> [private]
Definition at line 2475 of file ast.h.
ShouldParallelCompileField
using v8::internal::FunctionLiteral::ShouldParallelCompileField = HasBracesField::Next<bool, 1> [private]
Definition at line 2480 of file ast.h.
Member Enumeration Documentation
EagerCompileHint
enum v8::internal::FunctionLiteral::EagerCompileHint : uint8_t
Enumerator
kShouldEagerCompile
kShouldLazyCompile
Definition at line 2303 of file ast.h.
: uint8_t { kShouldEagerCompile, kShouldLazyCompile };
ParameterFlag
enum v8::internal::FunctionLiteral::ParameterFlag : uint8_t
Enumerator
kNoDuplicateParameters
kHasDuplicateParameters
Definition at line 2299 of file ast.h.
                     : uint8_t {
    kNoDuplicateParameters,
    kHasDuplicateParameters
  };
Constructor & Destructor Documentation
FunctionLiteral()
v8::internal::FunctionLiteral::FunctionLiteral (Zone * zone, const AstConsString * name, AstValueFactory * ast_value_factory, DeclarationScope * scope, const ScopedPtrList< Statement > & body, int expected_property_count, int parameter_count, int function_length, FunctionSyntaxKind function_syntax_kind, ParameterFlag has_duplicate_parameters, EagerCompileHint eager_compile_hint, int position, bool has_braces, int function_literal_id, ProducedPreparseData * produced_preparse_data = nullptr) [inline], [private]
Definition at line 2440 of file ast.h.
      : Expression(position, kFunctionLiteral),
        expected_property_count_(expected_property_count),
        parameter_count_(parameter_count),
        function_length_(function_length),
        function_token_position_(kNoSourcePosition),
        suspend_count_(0),
        function_literal_id_(function_literal_id),
        raw_name_(name),
        scope_(scope),
        body_(body.ToConstVector(), zone),
        raw_inferred_name_(ast_value_factory->empty_cons_string()),
        produced_preparse_data_(produced_preparse_data) {
    bit_field_ |= FunctionSyntaxKindBits::encode(function_syntax_kind) |
                  Pretenure::encode(false) |
                  HasDuplicateParameters::encode(has_duplicate_parameters ==
                                                 kHasDuplicateParameters) |
                  RequiresInstanceMembersInitializer::encode(false) |
                  HasBracesField::encode(has_braces) |
                  ShouldParallelCompileField::encode(false);
    if (eager_compile_hint == kShouldEagerCompile) SetShouldEagerCompile();
  }
References v8::internal::AstNode::bit_field_, v8::base::BitField< T, shift, size, U >::encode(), has_duplicate_parameters(), kHasDuplicateParameters, kShouldEagerCompile, and SetShouldEagerCompile().
Member Function Documentation
add_expected_properties()
void v8::internal::FunctionLiteral::add_expected_properties (int number_properties) [inline]
Definition at line 2329 of file ast.h.
                                                      {
    expected_property_count_ += number_properties;
  }
References expected_property_count_.
AllowsLazyCompilation()
bool v8::internal::FunctionLiteral::AllowsLazyCompilation ()
Definition at line 218 of file ast.cc.
                                            {
  return scope()->AllowsLazyCompilation();
}
References v8::internal::DeclarationScope::AllowsLazyCompilation(), and scope().
Referenced by v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), and v8::internal::UnoptimizedCompilationInfo::SourcePositionRecordingMode().
body()
ZonePtrList<Statement>* v8::internal::FunctionLiteral::body () [inline]
Definition at line 2315 of file ast.h.
{ return &body_; }
References body_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildInitializationBlockForParametersIfExist(), v8::internal::interpreter::BytecodeGenerator::GenerateBodyStatementsWithoutImplicitFinalReturn(), and v8::internal::SourceRangeAstVisitor::VisitFunctionLiteral().
CanSuspend()
bool v8::internal::FunctionLiteral::CanSuspend () [inline]
Definition at line 2338 of file ast.h.
                    {
    if (suspend_count() > 0) {
      DCHECK(IsResumableFunction(kind()));
      return true;
    }
    return false;
  }
References v8::internal::DCHECK(), v8::internal::IsResumableFunction(), kind(), and suspend_count().
class_scope_has_private_brand()
bool v8::internal::FunctionLiteral::class_scope_has_private_brand () const
Definition at line 269 of file ast.cc.
                                                          {
  return scope()->class_scope_has_private_brand();
}
References v8::internal::DeclarationScope::class_scope_has_private_brand(), and scope().
Referenced by v8::internal::interpreter::BytecodeGenerator::GenerateBaseConstructorBody(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), and v8::internal::anonymous_namespace{compiler.cc}::UpdateSharedFunctionFlagsAfterCompilation().
end_position()
int v8::internal::FunctionLiteral::end_position () const
Definition at line 226 of file ast.cc.
{ return scope()->end_position(); }
References v8::internal::Scope::end_position(), and scope().
Referenced by v8::internal::SharedFunctionInfo::CreateAndSetUncompiledData(), v8::internal::AsmJsCompilationJob::ExecuteJobImpl(), v8::internal::Compiler::GetSharedFunctionInfo(), v8::internal::anonymous_namespace{liveedit.cc}::SourcePositionEvent::LessThan(), v8::internal::Parser::ParseClassForMemberInitialization(), return_position(), and v8::internal::SharedFunctionInfo::UpdateFromFunctionLiteralForLiveEdit().
expected_property_count()
int v8::internal::FunctionLiteral::expected_property_count () [inline]
Definition at line 2332 of file ast.h.
{ return expected_property_count_; }
References expected_property_count_.
function_length()
int v8::internal::FunctionLiteral::function_length () [inline]
Definition at line 2334 of file ast.h.
{ return function_length_; }
References function_length_.
Referenced by v8::internal::SharedFunctionInfo::InitFromFunctionLiteral().
function_literal_id()
int v8::internal::FunctionLiteral::function_literal_id () const [inline]
Definition at line 2407 of file ast.h.
{ return function_literal_id_; }
References function_literal_id_.
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::Script::FindSharedFunctionInfo(), v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::GetFuncId(), v8::internal::anonymous_namespace{compiler.cc}::GetOrCreateTopLevelSharedFunctionInfo(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), is_toplevel(), v8::internal::anonymous_namespace{liveedit.cc}::SourcePositionEvent::LessThan(), v8::internal::anonymous_namespace{liveedit.cc}::MapLiterals(), v8::internal::Parser::ParseClassForMemberInitialization(), set_function_literal_id(), v8::internal::AstFunctionLiteralIdReindexer::VisitFunctionLiteral(), and v8::internal::anonymous_namespace{liveedit.cc}::CollectFunctionLiterals::VisitFunctionLiteral().
function_token_position()
int v8::internal::FunctionLiteral::function_token_position () const [inline]
Definition at line 2317 of file ast.h.
{ return function_token_position_; }
References function_token_position_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CreateTopLevelSharedFunctionInfo(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), and v8::internal::SharedFunctionInfo::UpdateFromFunctionLiteralForLiveEdit().
GetDebugName()
std::unique_ptr< char[]> v8::internal::FunctionLiteral::GetDebugName () const
Definition at line 234 of file ast.cc.
                                                          {
  const AstConsString* cons_string;
  if (raw_name_ != nullptr && !raw_name_->IsEmpty()) {
    cons_string = raw_name_;
  } else if (raw_inferred_name_ != nullptr && !raw_inferred_name_->IsEmpty()) {
    cons_string = raw_inferred_name_;
  } else if (!shared_function_info_.is_null()) {
    return shared_function_info_->inferred_name()->ToCString();
  } else {
    char* empty_str = new char[1];
    empty_str[0] = 0;
    return std::unique_ptr<char[]>(empty_str);
  }
  // TODO(rmcilroy): Deal with two-character strings.
  std::vector<char> result_vec;
  std::forward_list<const AstRawString*> strings = cons_string->ToRawStrings();
  for (const AstRawString* string : strings) {
    if (!string->is_one_byte()) break;
    for (int i = 0; i < string->length(); i++) {
      result_vec.push_back(string->raw_data()[i]);
    }
  }
  std::unique_ptr<char[]> result(new char[result_vec.size() + 1]);
  if (result_vec.size()) {
    memcpy(result.get(), result_vec.data(), result_vec.size());
  }
  result[result_vec.size()] = '\0';
  return result;
}
References v8::internal::AstConsString::IsEmpty(), raw_inferred_name_, raw_name_, v8::base::internal::result, shared_function_info_, v8::internal::string, and v8::internal::AstConsString::ToRawStrings().
Referenced by v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl(), and v8::internal::interpreter::anonymous_namespace{interpreter.cc}::MaybePrintAst().
GetInferredName() [1/2]
Handle< String > v8::internal::FunctionLiteral::GetInferredName (Isolate * isolate)
Definition at line 194 of file ast.cc.
                                                                {
  if (raw_inferred_name_ != nullptr) {
    return raw_inferred_name_->GetString(isolate);
  }
  DCHECK(!shared_function_info_.is_null());
  return handle(shared_function_info_->inferred_name(), isolate);
}
References v8::internal::DCHECK(), v8::internal::AstConsString::GetString(), v8::internal::handle(), raw_inferred_name_, and shared_function_info_.
Referenced by v8::internal::SharedFunctionInfo::CreateAndSetUncompiledData().
GetInferredName() [2/2]
Handle<String> v8::internal::FunctionLiteral::GetInferredName (LocalIsolate * isolate) const [inline]
Definition at line 2350 of file ast.h.
                                                              {
    DCHECK_NOT_NULL(raw_inferred_name_);
    return raw_inferred_name_->GetString(isolate);
  }
References DCHECK_NOT_NULL, v8::internal::AstConsString::GetString(), and raw_inferred_name_.
GetName()
template<typename IsolateT >
MaybeHandle<String> v8::internal::FunctionLiteral::GetName (IsolateT * isolate) const [inline]
Definition at line 2308 of file ast.h.
                                                       {
    return raw_name_ ? raw_name_->AllocateFlat(isolate) : MaybeHandle<String>();
  }
References v8::internal::AstConsString::AllocateFlat(), and raw_name_.
has_duplicate_parameters()
bool v8::internal::FunctionLiteral::has_duplicate_parameters () const [inline]
Definition at line 2368 of file ast.h.
                                        {
    // Not valid for lazy functions.
    DCHECK(ShouldEagerCompile());
    return HasDuplicateParameters::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), and ShouldEagerCompile().
Referenced by FunctionLiteral(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), and v8::internal::anonymous_namespace{compiler.cc}::UpdateSharedFunctionFlagsAfterCompilation().
has_shared_name()
bool v8::internal::FunctionLiteral::has_shared_name () const [inline]
Definition at line 2311 of file ast.h.
{ return raw_name_ != nullptr; }
References raw_name_.
has_static_private_methods_or_accessors()
bool v8::internal::FunctionLiteral::has_static_private_methods_or_accessors () const [inline]
Definition at line 2423 of file ast.h.
                                                       {
    return HasStaticPrivateMethodsOrAccessorsField::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), and v8::internal::anonymous_namespace{compiler.cc}::UpdateSharedFunctionFlagsAfterCompilation().
is_anonymous_expression()
bool v8::internal::FunctionLiteral::is_anonymous_expression () const [inline]
Definition at line 2320 of file ast.h.
                                       {
    return syntax_kind() == FunctionSyntaxKind::kAnonymousExpression;
  }
References v8::internal::kAnonymousExpression, and syntax_kind().
Referenced by IsAnonymousFunctionDefinition().
is_toplevel()
bool v8::internal::FunctionLiteral::is_toplevel () const [inline]
Definition at line 2324 of file ast.h.
                           {
    return function_literal_id() == kFunctionLiteralIdTopLevel;
  }
References function_literal_id(), and v8::internal::kFunctionLiteralIdTopLevel.
Referenced by v8::internal::UnoptimizedCompileFlags::ForToplevelFunction().
IsAnonymousFunctionDefinition()
bool v8::internal::FunctionLiteral::IsAnonymousFunctionDefinition () const [inline]
Definition at line 2394 of file ast.h.
                                             {
    return is_anonymous_expression();
  }
References is_anonymous_expression().
kind()
FunctionKind v8::internal::FunctionLiteral::kind () const
Definition at line 232 of file ast.cc.
{ return scope()->function_kind(); }
References v8::internal::DeclarationScope::function_kind(), and scope().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildGeneratorObjectVariableInitialization(), CanSuspend(), v8::internal::interpreter::BytecodeGenerator::function_kind(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), and v8::internal::Parser::ParseClassForMemberInitialization().
language_mode()
LanguageMode v8::internal::FunctionLiteral::language_mode () const
Definition at line 228 of file ast.cc.
                                                  {
  return scope()->language_mode();
}
References v8::internal::Scope::language_mode(), and scope().
Referenced by v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), v8::internal::Parser::PostProcessParseResult(), and v8::internal::anonymous_namespace{compiler.cc}::UpdateSharedFunctionFlagsAfterCompilation().
parameter_count()
int v8::internal::FunctionLiteral::parameter_count () [inline]
Definition at line 2333 of file ast.h.
{ return parameter_count_; }
References parameter_count_.
Referenced by v8::internal::interpreter::BytecodeGenerator::GetCachedCreateClosureSlot(), and v8::internal::SharedFunctionInfo::InitFromFunctionLiteral().
pretenure()
bool v8::internal::FunctionLiteral::pretenure () const [inline]
Definition at line 2365 of file ast.h.
{ return Pretenure::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
private_name_lookup_skips_outer_class()
bool v8::internal::FunctionLiteral::private_name_lookup_skips_outer_class () const
Definition at line 265 of file ast.cc.
                                                                  {
  return scope()->private_name_lookup_skips_outer_class();
}
References v8::internal::Scope::private_name_lookup_skips_outer_class(), and scope().
produced_preparse_data()
ProducedPreparseData* v8::internal::FunctionLiteral::produced_preparse_data () const [inline]
Definition at line 2432 of file ast.h.
                                                       {
    return produced_preparse_data_;
  }
References produced_preparse_data_.
Referenced by v8::internal::SharedFunctionInfo::CreateAndSetUncompiledData(), v8::internal::Compiler::GetSharedFunctionInfo(), and v8::internal::SharedFunctionInfo::InitFromFunctionLiteral().
raw_inferred_name()
const AstConsString* v8::internal::FunctionLiteral::raw_inferred_name () [inline]
Definition at line 2361 of file ast.h.
{ return raw_inferred_name_; }
References raw_inferred_name_.
Referenced by set_raw_inferred_name().
raw_name()
const AstConsString* v8::internal::FunctionLiteral::raw_name () const [inline]
Definition at line 2312 of file ast.h.
{ return raw_name_; }
References raw_name_.
requires_instance_members_initializer()
bool v8::internal::FunctionLiteral::requires_instance_members_initializer () const [inline]
Definition at line 2415 of file ast.h.
                                                     {
    return RequiresInstanceMembersInitializer::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::interpreter::BytecodeGenerator::GenerateBaseConstructorBody(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), and v8::internal::anonymous_namespace{compiler.cc}::UpdateSharedFunctionFlagsAfterCompilation().
return_position()
int v8::internal::FunctionLiteral::return_position () [inline]
Definition at line 2401 of file ast.h.
                        {
    return std::max(
        start_position(),
        end_position() - (HasBracesField::decode(bit_field_) ? 1 : 0));
  }
References v8::internal::AstNode::bit_field_, v8::base::BitField< T, shift, size, U >::decode(), end_position(), and start_position().
Referenced by v8::internal::interpreter::BytecodeGenerator::GenerateBodyStatements(), and v8::internal::interpreter::BytecodeGenerator::GenerateDerivedConstructorBody().
scope()
DeclarationScope* v8::internal::FunctionLiteral::scope () const [inline]
Definition at line 2314 of file ast.h.
{ return scope_; }
References scope_.
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), AllowsLazyCompilation(), v8::internal::DeclarationScope::Analyze(), class_scope_has_private_brand(), end_position(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncFunctionBody(), v8::internal::anonymous_namespace{liveedit.cc}::HasChangedScope(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), v8::internal::anonymous_namespace{compiler.cc}::InstallUnoptimizedCode(), kind(), language_mode(), v8::internal::Parser::ParseClassForMemberInitialization(), private_name_lookup_skips_outer_class(), v8::internal::UnoptimizedCompilationInfo::scope(), v8::internal::ParseInfo::scope(), set_class_scope_has_private_brand(), set_raw_inferred_name(), SetShouldEagerCompile(), ShouldEagerCompile(), start_position(), v8::internal::SharedFunctionInfo::UpdateFromFunctionLiteralForLiveEdit(), and v8::internal::anonymous_namespace{compiler.cc}::UpdateSharedFunctionFlagsAfterCompilation().
set_class_scope_has_private_brand()
void v8::internal::FunctionLiteral::set_class_scope_has_private_brand (bool value)
Definition at line 273 of file ast.cc.
                                                                  {
  return scope()->set_class_scope_has_private_brand(value);
}
References scope(), v8::internal::DeclarationScope::set_class_scope_has_private_brand(), and v8::internal::value.
set_function_literal_id()
void v8::internal::FunctionLiteral::set_function_literal_id (int function_literal_id) [inline]
Definition at line 2408 of file ast.h.
                                                        {
    function_literal_id_ = function_literal_id;
  }
References function_literal_id(), and function_literal_id_.
Referenced by v8::internal::AstFunctionLiteralIdReindexer::VisitFunctionLiteral().
set_function_token_position()
void v8::internal::FunctionLiteral::set_function_token_position (int pos) [inline]
Definition at line 2316 of file ast.h.
{ function_token_position_ = pos; }
References function_token_position_.
Referenced by v8::internal::Parser::ParseFunctionLiteral().
set_has_static_private_methods_or_accessors()
void v8::internal::FunctionLiteral::set_has_static_private_methods_or_accessors (bool value) [inline]
Definition at line 2419 of file ast.h.
                                                               {
    bit_field_ =
        HasStaticPrivateMethodsOrAccessorsField::update(bit_field_, value);
  }
References v8::internal::AstNode::bit_field_, v8::base::BitField< T, shift, size, U >::update(), and v8::internal::value.
set_pretenure()
void v8::internal::FunctionLiteral::set_pretenure () [inline]
Definition at line 2366 of file ast.h.
{ bit_field_ = Pretenure::update(bit_field_, true); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::update().
set_raw_inferred_name()
void v8::internal::FunctionLiteral::set_raw_inferred_name (AstConsString * raw_inferred_name)
Definition at line 187 of file ast.cc.
                                                                            {
  DCHECK_NOT_NULL(raw_inferred_name);
  DCHECK(shared_function_info_.is_null());
  raw_inferred_name_ = raw_inferred_name;
  scope()->set_has_inferred_function_name(true);
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, raw_inferred_name(), raw_inferred_name_, scope(), v8::internal::DeclarationScope::set_has_inferred_function_name(), and shared_function_info_.
set_raw_name()
void v8::internal::FunctionLiteral::set_raw_name (const AstConsString * name) [inline]
Definition at line 2313 of file ast.h.
{ raw_name_ = name; }
References v8::internal::name, and raw_name_.
set_requires_instance_members_initializer()
void v8::internal::FunctionLiteral::set_requires_instance_members_initializer (bool value) [inline]
Definition at line 2412 of file ast.h.
                                                             {
    bit_field_ = RequiresInstanceMembersInitializer::update(bit_field_, value);
  }
References v8::internal::AstNode::bit_field_, v8::base::BitField< T, shift, size, U >::update(), and v8::internal::value.
set_shared_function_info()
void v8::internal::FunctionLiteral::set_shared_function_info (Handle< SharedFunctionInfo > shared_function_info)
Definition at line 202 of file ast.cc.
                                                     {
  DCHECK(shared_function_info_.is_null());
  CHECK_EQ(shared_function_info->function_literal_id(kRelaxedLoad),
           function_literal_id_);
  shared_function_info_ = shared_function_info;
}
References CHECK_EQ, v8::internal::DCHECK(), function_literal_id_, v8::kRelaxedLoad, shared_function_info(), and shared_function_info_.
Referenced by v8::internal::Compiler::Compile(), v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl(), v8::internal::Script::FindSharedFunctionInfo(), and v8::internal::BackgroundCompileTask::Run().
set_should_parallel_compile()
void v8::internal::FunctionLiteral::set_should_parallel_compile () [inline]
Definition at line 2377 of file ast.h.
                                     {
    bit_field_ = ShouldParallelCompileField::update(bit_field_, true);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::Parser::ParseFunctionLiteral().
set_suspend_count()
void v8::internal::FunctionLiteral::set_suspend_count (int suspend_count) [inline]
Definition at line 2399 of file ast.h.
{ suspend_count_ = suspend_count; }
References suspend_count(), and suspend_count_.
Referenced by v8::internal::Parser::ParseFunctionLiteral().
SetShouldEagerCompile()
void v8::internal::FunctionLiteral::SetShouldEagerCompile ()
Definition at line 214 of file ast.cc.
                                            {
  scope()->set_should_eager_compile();
}
References scope(), and v8::internal::DeclarationScope::set_should_eager_compile().
Referenced by FunctionLiteral().
shared_function_info()
Handle<SharedFunctionInfo> v8::internal::FunctionLiteral::shared_function_info () const [inline]
Definition at line 2355 of file ast.h.
                                                          {
    return shared_function_info_;
  }
References shared_function_info_.
Referenced by v8::internal::DeclarationScope::AllocateScopeInfos(), v8::internal::SharedFunctionInfo::CreateAndSetUncompiledData(), v8::internal::Script::FindSharedFunctionInfo(), v8::internal::Compiler::GetSharedFunctionInfo(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), v8::internal::anonymous_namespace{compiler.cc}::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs(), v8::internal::BackgroundCompileTask::Run(), set_shared_function_info(), and v8::internal::anonymous_namespace{compiler.cc}::UpdateSharedFunctionFlagsAfterCompilation().
should_parallel_compile()
bool v8::internal::FunctionLiteral::should_parallel_compile () const [inline]
Definition at line 2374 of file ast.h.
                                       {
    return ShouldParallelCompileField::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::interpreter::BytecodeGenerator::AddToEagerLiteralsIfEager(), and v8::internal::SharedFunctionInfo::CreateAndSetUncompiledData().
ShouldEagerCompile()
bool v8::internal::FunctionLiteral::ShouldEagerCompile () const
Definition at line 210 of file ast.cc.
                                               {
  return scope()->ShouldEagerCompile();
}
References scope(), and v8::internal::DeclarationScope::ShouldEagerCompile().
Referenced by v8::internal::interpreter::BytecodeGenerator::AddToEagerLiteralsIfEager(), has_duplicate_parameters(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), and v8::internal::SharedFunctionInfo::UpdateAndFinalizeExpectedNofPropertiesFromEstimate().
start_position()
int v8::internal::FunctionLiteral::start_position () const
Definition at line 222 of file ast.cc.
                                          {
  return scope()->start_position();
}
References scope(), and v8::internal::Scope::start_position().
Referenced by v8::internal::SharedFunctionInfo::CreateAndSetUncompiledData(), v8::internal::AsmJsCompilationJob::ExecuteJobImpl(), v8::internal::anonymous_namespace{liveedit.cc}::FunctionDataMap::GetFuncId(), v8::internal::Compiler::GetSharedFunctionInfo(), v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), v8::internal::anonymous_namespace{liveedit.cc}::SourcePositionEvent::LessThan(), return_position(), and v8::internal::SharedFunctionInfo::UpdateFromFunctionLiteralForLiveEdit().
suspend_count()
int v8::internal::FunctionLiteral::suspend_count () [inline]
Definition at line 2398 of file ast.h.
{ return suspend_count_; }
References suspend_count_.
Referenced by CanSuspend(), and set_suspend_count().
syntax_kind()
FunctionSyntaxKind v8::internal::FunctionLiteral::syntax_kind () const [inline]
Definition at line 2389 of file ast.h.
                                         {
    return FunctionSyntaxKindBits::decode(bit_field_);
  }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::SharedFunctionInfo::InitFromFunctionLiteral(), and is_anonymous_expression().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 2437 of file ast.h.
Member Data Documentation
body_
ZonePtrList<Statement> v8::internal::FunctionLiteral::body_ [private]
Definition at line 2493 of file ast.h.
Referenced by body().
expected_property_count_
int v8::internal::FunctionLiteral::expected_property_count_ [private]
Definition at line 2484 of file ast.h.
Referenced by add_expected_properties(), and expected_property_count().
function_length_
int v8::internal::FunctionLiteral::function_length_ [private]
Definition at line 2486 of file ast.h.
Referenced by function_length().
function_literal_id_
int v8::internal::FunctionLiteral::function_literal_id_ [private]
Definition at line 2489 of file ast.h.
Referenced by function_literal_id(), set_function_literal_id(), and set_shared_function_info().
function_token_position_
int v8::internal::FunctionLiteral::function_token_position_ [private]
Definition at line 2487 of file ast.h.
Referenced by function_token_position(), and set_function_token_position().
parameter_count_
int v8::internal::FunctionLiteral::parameter_count_ [private]
Definition at line 2485 of file ast.h.
Referenced by parameter_count().
produced_preparse_data_
ProducedPreparseData* v8::internal::FunctionLiteral::produced_preparse_data_ [private]
Definition at line 2496 of file ast.h.
Referenced by produced_preparse_data().
raw_inferred_name_
AstConsString* v8::internal::FunctionLiteral::raw_inferred_name_ [private]
Definition at line 2494 of file ast.h.
Referenced by GetDebugName(), GetInferredName(), raw_inferred_name(), and set_raw_inferred_name().
raw_name_
const AstConsString* v8::internal::FunctionLiteral::raw_name_ [private]
Definition at line 2491 of file ast.h.
Referenced by GetDebugName(), GetName(), has_shared_name(), raw_name(), and set_raw_name().
scope_
DeclarationScope* v8::internal::FunctionLiteral::scope_ [private]
Definition at line 2492 of file ast.h.
Referenced by scope().
shared_function_info_
IndirectHandle<SharedFunctionInfo> v8::internal::FunctionLiteral::shared_function_info_ [private]
Definition at line 2495 of file ast.h.
Referenced by GetDebugName(), GetInferredName(), set_raw_inferred_name(), set_shared_function_info(), and shared_function_info().
suspend_count_
int v8::internal::FunctionLiteral::suspend_count_ [private]
Definition at line 2488 of file ast.h.
Referenced by set_suspend_count(), and suspend_count().
Zone
friend v8::internal::FunctionLiteral::Zone [private]
Definition at line 2438 of file ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc