v8::internal::DirectHandleSmallVector< T, kSize > Class Template Reference
#include <handles.h>
Public Types
using value_type = DirectHandle< T >
using reference = value_type &
using const_reference = const value_type &
using size_type = size_t
using difference_type = ptrdiff_t
using iterator = internal::WrappedIterator< element_type *, value_type >
using const_iterator = internal::WrappedIterator< const element_type *, const value_type >
using reverse_iterator = internal::WrappedIterator< element_type *, value_type >
using const_reverse_iterator = internal::WrappedIterator< const element_type *, const value_type >
Public Member Functions
template<typename IsolateT >
DirectHandleSmallVector (IsolateT *isolate)
template<typename IsolateT >
DirectHandleSmallVector (IsolateT *isolate, size_t n)
template<typename IsolateT >
DirectHandleSmallVector (IsolateT *isolate, std::initializer_list< value_type > init)
template<typename IsolateT >
DirectHandleSmallVector (base::Vector< const value_type > init)
value_type * data () noexcept
const value_type * data () const noexcept
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
iterator rbegin () noexcept
const_iterator rbegin () const noexcept
iterator rand () noexcept
const_iterator rend () const noexcept
size_t size () const noexcept
bool empty () const noexcept
size_t capacity () const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
reference at (size_t n)
const_reference at (size_t n) const
reference & operator[] (size_t n)
const_reference & operator[] (size_t n) const
template<typename... Args>
void emplace_back (Args &&... args)
void push_back (const_reference x)
void pop_back (size_t count=1)
iterator insert (const_iterator pos, const_reference value)
iterator insert (const_iterator pos, size_t count, const_reference value)
template<typename InputIt >
iterator insert (const_iterator pos, InputIt first, InputIt last)
iterator insert (const_iterator pos, std::initializer_list< value_type > init)
void erase (iterator erase_start, iterator erase_end)
void erase (iterator pos)
void resize (size_t new_size)
void resize (size_t new_size, const_reference initial_value)
void reserve (size_t n)
void clear () noexcept
auto get_allocator () const
Static Public Attributes
static constexpr size_t kInlineSize = kSize
Private Types
using element_type = internal::DirectHandleUnchecked< T >
using vector_type = ::v8::base::SmallVector< element_type, kSize >
Private Attributes
vector_type backing_
Detailed Description
template<typename T, size_t kSize>
class v8::internal::DirectHandleSmallVector< T, kSize >
Definition at line 984 of file handles.h.
Member Typedef Documentation
const_iterator
template<typename T , size_t kSize>
using v8::internal::DirectHandleSmallVector< T, kSize >::const_iterator = internal::WrappedIterator<const element_type*, const value_type>
Definition at line 1010 of file handles.h.
const_reference
template<typename T , size_t kSize>
using v8::internal::DirectHandleSmallVector< T, kSize >::const_reference = const value_type&
Definition at line 1006 of file handles.h.
const_reverse_iterator
template<typename T , size_t kSize>
using v8::internal::DirectHandleSmallVector< T, kSize >::const_reverse_iterator = internal::WrappedIterator<const element_type*, const value_type>
Definition at line 1013 of file handles.h.
difference_type
template<typename T , size_t kSize>
using v8::internal::DirectHandleSmallVector< T, kSize >::difference_type = ptrdiff_t
Definition at line 1008 of file handles.h.
element_type
template<typename T , size_t kSize>
using v8::internal::DirectHandleSmallVector< T, kSize >::element_type = internal::DirectHandleUnchecked<T> [private]
Definition at line 986 of file handles.h.
iterator
template<typename T , size_t kSize>
using v8::internal::DirectHandleSmallVector< T, kSize >::iterator = internal::WrappedIterator<element_type*, value_type>
Definition at line 1009 of file handles.h.
reference
template<typename T , size_t kSize>
using v8::internal::DirectHandleSmallVector< T, kSize >::reference = value_type&
Definition at line 1005 of file handles.h.
reverse_iterator
template<typename T , size_t kSize>
using v8::internal::DirectHandleSmallVector< T, kSize >::reverse_iterator = internal::WrappedIterator<element_type*, value_type>
Definition at line 1012 of file handles.h.
size_type
template<typename T , size_t kSize>
using v8::internal::DirectHandleSmallVector< T, kSize >::size_type = size_t
Definition at line 1007 of file handles.h.
value_type
template<typename T , size_t kSize>
using v8::internal::DirectHandleSmallVector< T, kSize >::value_type = DirectHandle<T>
Definition at line 1004 of file handles.h.
vector_type
template<typename T , size_t kSize>
using v8::internal::DirectHandleSmallVector< T, kSize >::vector_type = ::v8::base::SmallVector<element_type, kSize> [private]
Definition at line 999 of file handles.h.
Constructor & Destructor Documentation
DirectHandleSmallVector() [1/4]
template<typename T , size_t kSize>
template<typename IsolateT >
v8::internal::DirectHandleSmallVector< T, kSize >::DirectHandleSmallVector (IsolateT * isolate) [inline], [explicit]
Definition at line 1033 of file handles.h.
: backing_() {}
DirectHandleSmallVector() [2/4]
template<typename T , size_t kSize>
template<typename IsolateT >
v8::internal::DirectHandleSmallVector< T, kSize >::DirectHandleSmallVector (IsolateT * isolate, size_t n) [inline]
Definition at line 1035 of file handles.h.
: backing_(n) {}
DirectHandleSmallVector() [3/4]
template<typename T , size_t kSize>
template<typename IsolateT >
v8::internal::DirectHandleSmallVector< T, kSize >::DirectHandleSmallVector (IsolateT * isolate, std::initializer_list< value_type > init) [inline]
Definition at line 1037 of file handles.h.
      : backing_() {
    if (init.size() == 0) return;
    backing_.reserve(init.size());
    backing_.insert(backing_.end(), init.begin(), init.end());
  }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, v8::base::SmallVector< T, kSize, Allocator >::end(), v8::base::SmallVector< T, kSize, Allocator >::insert(), and v8::base::SmallVector< T, kSize, Allocator >::reserve().
DirectHandleSmallVector() [4/4]
template<typename T , size_t kSize>
template<typename IsolateT >
v8::internal::DirectHandleSmallVector< T, kSize >::DirectHandleSmallVector (base::Vector< const value_type > init) [inline], [explicit]
Definition at line 1045 of file handles.h.
      : backing_() {
    if (init.size() == 0) return;
    backing_.reserve(init.size());
    backing_.insert(backing_.end(), init.begin(), init.end());
  }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, v8::base::Vector< T >::begin(), v8::base::SmallVector< T, kSize, Allocator >::end(), v8::base::Vector< T >::end(), v8::base::SmallVector< T, kSize, Allocator >::insert(), v8::base::SmallVector< T, kSize, Allocator >::reserve(), and v8::base::Vector< T >::size().
Member Function Documentation
at() [1/2]
template<typename T , size_t kSize>
reference v8::internal::DirectHandleSmallVector< T, kSize >::at (size_t n) [inline]
Definition at line 1082 of file handles.h.
{ return backing_.at(n); }
References v8::base::SmallVector< T, kSize, Allocator >::at(), and v8::internal::DirectHandleSmallVector< T, kSize >::backing_.
Referenced by v8::internal::KeyedLoadIC::UpdateLoadElement().
at() [2/2]
template<typename T , size_t kSize>
const_reference v8::internal::DirectHandleSmallVector< T, kSize >::at (size_t n) const [inline]
Definition at line 1083 of file handles.h.
{ return backing_.at(n); }
References v8::base::SmallVector< T, kSize, Allocator >::at(), and v8::internal::DirectHandleSmallVector< T, kSize >::backing_.
back() [1/2]
template<typename T , size_t kSize>
reference v8::internal::DirectHandleSmallVector< T, kSize >::back () [inline]
Definition at line 1079 of file handles.h.
{ return backing_.back(); }
References v8::base::SmallVector< T, kSize, Allocator >::back(), and v8::internal::DirectHandleSmallVector< T, kSize >::backing_.
back() [2/2]
template<typename T , size_t kSize>
const_reference v8::internal::DirectHandleSmallVector< T, kSize >::back () const [inline]
Definition at line 1080 of file handles.h.
{ return backing_.back(); }
References v8::base::SmallVector< T, kSize, Allocator >::back(), and v8::internal::DirectHandleSmallVector< T, kSize >::backing_.
begin() [1/2]
template<typename T , size_t kSize>
const_iterator v8::internal::DirectHandleSmallVector< T, kSize >::begin () const [inline], [noexcept]
Definition at line 1058 of file handles.h.
                                        {
    return const_iterator(backing_.begin());
  }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::begin().
begin() [2/2]
template<typename T , size_t kSize>
iterator v8::internal::DirectHandleSmallVector< T, kSize >::begin () [inline], [noexcept]
Definition at line 1057 of file handles.h.
{ return iterator(backing_.begin()); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::begin().
Referenced by v8::internal::KeyedLoadIC::LoadElementPolymorphicHandlers(), v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForElementAccess(), and v8::internal::KeyedLoadIC::UpdateLoadElement().
capacity()
template<typename T , size_t kSize>
size_t v8::internal::DirectHandleSmallVector< T, kSize >::capacity () const [inline]
Definition at line 1075 of file handles.h.
{ return backing_.capacity(); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::capacity().
clear()
template<typename T , size_t kSize>
void v8::internal::DirectHandleSmallVector< T, kSize >::clear () [inline], [noexcept]
Definition at line 1121 of file handles.h.
{ backing_.clear(); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::clear().
data() [1/2]
template<typename T , size_t kSize>
const value_type* v8::internal::DirectHandleSmallVector< T, kSize >::data () const [inline], [noexcept]
Definition at line 1055 of file handles.h.
{ return backing_.data(); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::data().
data() [2/2]
template<typename T , size_t kSize>
value_type* v8::internal::DirectHandleSmallVector< T, kSize >::data () [inline], [noexcept]
Definition at line 1054 of file handles.h.
{ return backing_.data(); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::data().
emplace_back()
template<typename T , size_t kSize>
template<typename... Args>
void v8::internal::DirectHandleSmallVector< T, kSize >::emplace_back (Args &&... args) [inline]
Definition at line 1089 of file handles.h.
                                    {
    backing_.emplace_back(std::forward<Args>(args)...);
  }
References v8::base::args, v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::emplace_back().
Referenced by v8::internal::RUNTIME_FUNCTION().
empty()
template<typename T , size_t kSize>
bool v8::internal::DirectHandleSmallVector< T, kSize >::empty () const [inline], [noexcept]
Definition at line 1074 of file handles.h.
{ return backing_.empty(); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::empty().
Referenced by v8::internal::MapsAndHandlers::empty(), v8::internal::IC::FirstTargetMap(), and v8::internal::KeyedLoadIC::UpdateLoadElement().
end() [1/2]
template<typename T , size_t kSize>
const_iterator v8::internal::DirectHandleSmallVector< T, kSize >::end () const [inline], [noexcept]
Definition at line 1062 of file handles.h.
{ return const_iterator(backing_.end()); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::end().
end() [2/2]
template<typename T , size_t kSize>
iterator v8::internal::DirectHandleSmallVector< T, kSize >::end () [inline], [noexcept]
Definition at line 1061 of file handles.h.
{ return iterator(backing_.end()); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::end().
Referenced by v8::internal::KeyedLoadIC::LoadElementPolymorphicHandlers(), v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForElementAccess(), and v8::internal::KeyedLoadIC::UpdateLoadElement().
erase() [1/2]
template<typename T , size_t kSize>
void v8::internal::DirectHandleSmallVector< T, kSize >::erase (iterator erase_start, iterator erase_end) [inline]
Definition at line 1110 of file handles.h.
                                                       {
    backing_.erase(erase_start.base(), erase_end.base());
  }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, v8::internal::WrappedIterator< Iterator, ElementType >::base(), and v8::base::SmallVector< T, kSize, Allocator >::erase().
Referenced by v8::internal::KeyedLoadIC::LoadElementPolymorphicHandlers().
erase() [2/2]
template<typename T , size_t kSize>
void v8::internal::DirectHandleSmallVector< T, kSize >::erase (iterator pos) [inline]
Definition at line 1113 of file handles.h.
{ return erase(pos, pos + 1); }
References v8::internal::DirectHandleSmallVector< T, kSize >::erase().
Referenced by v8::internal::DirectHandleSmallVector< T, kSize >::erase().
front() [1/2]
template<typename T , size_t kSize>
reference v8::internal::DirectHandleSmallVector< T, kSize >::front () [inline]
Definition at line 1077 of file handles.h.
{ return backing_.front(); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::front().
front() [2/2]
template<typename T , size_t kSize>
const_reference v8::internal::DirectHandleSmallVector< T, kSize >::front () const [inline]
Definition at line 1078 of file handles.h.
{ return backing_.front(); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::front().
get_allocator()
template<typename T , size_t kSize>
auto v8::internal::DirectHandleSmallVector< T, kSize >::get_allocator () const [inline]
Definition at line 1123 of file handles.h.
{ return backing_.get_allocator(); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::get_allocator().
insert() [1/4]
template<typename T , size_t kSize>
iterator v8::internal::DirectHandleSmallVector< T, kSize >::insert (const_iterator pos, const_reference value) [inline]
Definition at line 1096 of file handles.h.
                                                             {
    return iterator(backing_.insert(pos.base(), value));
  }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, v8::internal::WrappedIterator< Iterator, ElementType >::base(), v8::base::SmallVector< T, kSize, Allocator >::insert(), and v8::internal::value.
insert() [2/4]
template<typename T , size_t kSize>
template<typename InputIt >
iterator v8::internal::DirectHandleSmallVector< T, kSize >::insert (const_iterator pos, InputIt first, InputIt last) [inline]
Definition at line 1103 of file handles.h.
                                                                   {
    return iterator(backing_.insert(pos.base(), first, last));
  }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, v8::internal::WrappedIterator< Iterator, ElementType >::base(), and v8::base::SmallVector< T, kSize, Allocator >::insert().
insert() [3/4]
template<typename T , size_t kSize>
iterator v8::internal::DirectHandleSmallVector< T, kSize >::insert (const_iterator pos, size_t count, const_reference value) [inline]
Definition at line 1099 of file handles.h.
                                                                           {
    return iterator(backing_.insert(pos.base(), count, value));
  }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, v8::internal::WrappedIterator< Iterator, ElementType >::base(), v8::base::SmallVector< T, kSize, Allocator >::insert(), and v8::internal::value.
insert() [4/4]
template<typename T , size_t kSize>
iterator v8::internal::DirectHandleSmallVector< T, kSize >::insert (const_iterator pos, std::initializer_list< value_type > init) [inline]
Definition at line 1106 of file handles.h.
                                                                            {
    return iterator(backing_.insert(pos.base(), init.begin(), init.end()));
  }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, v8::internal::WrappedIterator< Iterator, ElementType >::base(), and v8::base::SmallVector< T, kSize, Allocator >::insert().
operator[]() [1/2]
template<typename T , size_t kSize>
reference& v8::internal::DirectHandleSmallVector< T, kSize >::operator[] (size_t n) [inline]
Definition at line 1085 of file handles.h.
{ return backing_[n]; }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_.
operator[]() [2/2]
template<typename T , size_t kSize>
const_reference& v8::internal::DirectHandleSmallVector< T, kSize >::operator[] (size_t n) const [inline]
Definition at line 1086 of file handles.h.
{ return backing_[n]; }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_.
pop_back()
template<typename T , size_t kSize>
void v8::internal::DirectHandleSmallVector< T, kSize >::pop_back (size_t count = 1) [inline]
Definition at line 1094 of file handles.h.
{ backing_.pop_back(count); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::pop_back().
push_back()
template<typename T , size_t kSize>
void v8::internal::DirectHandleSmallVector< T, kSize >::push_back (const_reference x) [inline]
Definition at line 1093 of file handles.h.
{ backing_.push_back(x); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::push_back().
Referenced by v8::internal::anonymous_namespace{ic.cc}::AddOneReceiverMapIfMissing(), v8::internal::MapsAndHandlers::emplace_back(), v8::internal::FeedbackNexus::ExtractMaps(), v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForElementAccess(), and v8::internal::IC::TargetMaps().
rand()
template<typename T , size_t kSize>
iterator v8::internal::DirectHandleSmallVector< T, kSize >::rand () [inline], [noexcept]
Definition at line 1068 of file handles.h.
{ return iterator(backing_.rend()); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::rend().
rbegin() [1/2]
template<typename T , size_t kSize>
const_iterator v8::internal::DirectHandleSmallVector< T, kSize >::rbegin () const [inline], [noexcept]
Definition at line 1065 of file handles.h.
                                         {
    return const_iterator(backing_.rbegin());
  }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::rbegin().
rbegin() [2/2]
template<typename T , size_t kSize>
iterator v8::internal::DirectHandleSmallVector< T, kSize >::rbegin () [inline], [noexcept]
Definition at line 1064 of file handles.h.
{ return iterator(backing_.rbegin()); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::rbegin().
rend()
template<typename T , size_t kSize>
const_iterator v8::internal::DirectHandleSmallVector< T, kSize >::rend () const [inline], [noexcept]
Definition at line 1069 of file handles.h.
                                       {
    return const_iterator(backing_.rend());
  }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::rend().
reserve()
template<typename T , size_t kSize>
void v8::internal::DirectHandleSmallVector< T, kSize >::reserve (size_t n) [inline]
Definition at line 1120 of file handles.h.
{ backing_.reserve(n); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::reserve().
Referenced by v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForElementAccess(), and v8::internal::MapsAndHandlers::reserve().
resize() [1/2]
template<typename T , size_t kSize>
void v8::internal::DirectHandleSmallVector< T, kSize >::resize (size_t new_size) [inline]
Definition at line 1115 of file handles.h.
{ backing_.resize(new_size); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::resize().
resize() [2/2]
template<typename T , size_t kSize>
void v8::internal::DirectHandleSmallVector< T, kSize >::resize (size_t new_size, const_reference initial_value) [inline]
Definition at line 1116 of file handles.h.
                                                              {
    backing_.resize(new_size, initial_value);
  }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::resize().
size()
template<typename T , size_t kSize>
size_t v8::internal::DirectHandleSmallVector< T, kSize >::size () const [inline], [noexcept]
Definition at line 1073 of file handles.h.
{ return backing_.size(); }
References v8::internal::DirectHandleSmallVector< T, kSize >::backing_, and v8::base::SmallVector< T, kSize, Allocator >::size().
Referenced by v8::internal::RUNTIME_FUNCTION(), v8::internal::MapsAndHandlers::size(), and v8::internal::KeyedLoadIC::UpdateLoadElement().
Member Data Documentation
backing_
template<typename T , size_t kSize>
vector_type v8::internal::DirectHandleSmallVector< T, kSize >::backing_ [private]
Definition at line 1126 of file handles.h.
Referenced by v8::internal::DirectHandleSmallVector< T, kSize >::at(), v8::internal::DirectHandleSmallVector< T, kSize >::back(), v8::internal::DirectHandleSmallVector< T, kSize >::begin(), v8::internal::DirectHandleSmallVector< T, kSize >::capacity(), v8::internal::DirectHandleSmallVector< T, kSize >::clear(), v8::internal::DirectHandleSmallVector< T, kSize >::data(), v8::internal::DirectHandleSmallVector< T, kSize >::DirectHandleSmallVector(), v8::internal::DirectHandleSmallVector< T, kSize >::emplace_back(), v8::internal::DirectHandleSmallVector< T, kSize >::empty(), v8::internal::DirectHandleSmallVector< T, kSize >::end(), v8::internal::DirectHandleSmallVector< T, kSize >::erase(), v8::internal::DirectHandleSmallVector< T, kSize >::front(), v8::internal::DirectHandleSmallVector< T, kSize >::get_allocator(), v8::internal::DirectHandleSmallVector< T, kSize >::insert(), v8::internal::DirectHandleSmallVector< T, kSize >::operator[](), v8::internal::DirectHandleSmallVector< T, kSize >::pop_back(), v8::internal::DirectHandleSmallVector< T, kSize >::push_back(), v8::internal::DirectHandleSmallVector< T, kSize >::rand(), v8::internal::DirectHandleSmallVector< T, kSize >::rbegin(), v8::internal::DirectHandleSmallVector< T, kSize >::rend(), v8::internal::DirectHandleSmallVector< T, kSize >::reserve(), v8::internal::DirectHandleSmallVector< T, kSize >::resize(), and v8::internal::DirectHandleSmallVector< T, kSize >::size().
kInlineSize
template<typename T , size_t kSize>
constexpr size_t v8::internal::DirectHandleSmallVector< T, kSize >::kInlineSize = kSize [static], [constexpr]
Definition at line 1003 of file handles.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/handles/handles.h