v8::internal::AssemblerRiscvBase Class Reference
#include <base-assembler-riscv.h>
Protected Types
enum OffsetSize : int {
kOffset21 = 21
, kOffset12 = 12
, kOffset20 = 20
, kOffset13 = 13
,
kOffset32 = 32
, kOffset11 = 11
, kOffset9 = 9
 }
Protected Member Functions
virtual int32_t branch_offset_helper (Label *L, OffsetSize bits)=0
virtual void emit (Instr x)=0
virtual void emit (ShortInstr x)=0
virtual void emit (uint64_t x)=0
virtual void ClearVectorunit ()=0
void GenInstrR (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, Register rd, Register rs1, Register rs2)
void GenInstrR (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, FPURegister rd, FPURegister rs1, FPURegister rs2)
void GenInstrR (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, Register rd, FPURegister rs1, Register rs2)
void GenInstrR (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, FPURegister rd, Register rs1, Register rs2)
void GenInstrR (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, FPURegister rd, FPURegister rs1, Register rs2)
void GenInstrR (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, Register rd, FPURegister rs1, FPURegister rs2)
void GenInstrR4 (uint8_t funct2, BaseOpcode opcode, Register rd, Register rs1, Register rs2, Register rs3, FPURoundingMode frm)
void GenInstrR4 (uint8_t funct2, BaseOpcode opcode, FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm)
void GenInstrRAtomic (uint8_t funct5, bool aq, bool rl, uint8_t funct3, Register rd, Register rs1, Register rs2)
void GenInstrRFrm (uint8_t funct7, BaseOpcode opcode, Register rd, Register rs1, Register rs2, FPURoundingMode frm)
void GenInstrI (uint8_t funct3, BaseOpcode opcode, Register rd, Register rs1, int16_t imm12)
void GenInstrI (uint8_t funct3, BaseOpcode opcode, FPURegister rd, Register rs1, int16_t imm12)
void GenInstrIShift (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, Register rd, Register rs1, uint8_t shamt)
void GenInstrIShiftW (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, Register rd, Register rs1, uint8_t shamt)
void GenInstrS (uint8_t funct3, BaseOpcode opcode, Register rs1, Register rs2, int16_t imm12)
void GenInstrS (uint8_t funct3, BaseOpcode opcode, Register rs1, FPURegister rs2, int16_t imm12)
void GenInstrB (uint8_t funct3, BaseOpcode opcode, Register rs1, Register rs2, int16_t imm12)
void GenInstrU (BaseOpcode opcode, Register rd, int32_t imm20)
void GenInstrJ (BaseOpcode opcode, Register rd, int32_t imm20)
void GenInstrCR (uint8_t funct4, BaseOpcode opcode, Register rd, Register rs2)
void GenInstrCA (uint8_t funct6, BaseOpcode opcode, Register rd, uint8_t funct, Register rs2)
void GenInstrCI (uint8_t funct3, BaseOpcode opcode, Register rd, int8_t imm6)
void GenInstrCIU (uint8_t funct3, BaseOpcode opcode, Register rd, uint8_t uimm6)
void GenInstrCIU (uint8_t funct3, BaseOpcode opcode, FPURegister rd, uint8_t uimm6)
void GenInstrCIW (uint8_t funct3, BaseOpcode opcode, Register rd, uint8_t uimm8)
void GenInstrCSS (uint8_t funct3, BaseOpcode opcode, FPURegister rs2, uint8_t uimm6)
void GenInstrCSS (uint8_t funct3, BaseOpcode opcode, Register rs2, uint8_t uimm6)
void GenInstrCL (uint8_t funct3, BaseOpcode opcode, Register rd, Register rs1, uint8_t uimm5)
void GenInstrCL (uint8_t funct3, BaseOpcode opcode, FPURegister rd, Register rs1, uint8_t uimm5)
void GenInstrCS (uint8_t funct3, BaseOpcode opcode, Register rs2, Register rs1, uint8_t uimm5)
void GenInstrCS (uint8_t funct3, BaseOpcode opcode, FPURegister rs2, Register rs1, uint8_t uimm5)
void GenInstrCJ (uint8_t funct3, BaseOpcode opcode, uint16_t uint11)
void GenInstrCB (uint8_t funct3, BaseOpcode opcode, Register rs1, uint8_t uimm8)
void GenInstrCBA (uint8_t funct3, uint8_t funct2, BaseOpcode opcode, Register rs1, int8_t imm6)
void GenInstrBranchCC_rri (uint8_t funct3, Register rs1, Register rs2, int16_t imm12)
void GenInstrLoad_ri (uint8_t funct3, Register rd, Register rs1, int16_t imm12)
void GenInstrStore_rri (uint8_t funct3, Register rs1, Register rs2, int16_t imm12)
void GenInstrALU_ri (uint8_t funct3, Register rd, Register rs1, int16_t imm12)
void GenInstrShift_ri (bool arithshift, uint8_t funct3, Register rd, Register rs1, uint8_t shamt)
void GenInstrALU_rr (uint8_t funct7, uint8_t funct3, Register rd, Register rs1, Register rs2)
void GenInstrCSR_ir (uint8_t funct3, Register rd, ControlStatusReg csr, Register rs1)
void GenInstrCSR_ii (uint8_t funct3, Register rd, ControlStatusReg csr, uint8_t rs1)
void GenInstrShiftW_ri (bool arithshift, uint8_t funct3, Register rd, Register rs1, uint8_t shamt)
void GenInstrALUW_rr (uint8_t funct7, uint8_t funct3, Register rd, Register rs1, Register rs2)
void GenInstrPriv (uint8_t funct7, Register rs1, Register rs2)
void GenInstrLoadFP_ri (uint8_t funct3, FPURegister rd, Register rs1, int16_t imm12)
void GenInstrStoreFP_rri (uint8_t funct3, Register rs1, FPURegister rs2, int16_t imm12)
void GenInstrALUFP_rr (uint8_t funct7, uint8_t funct3, FPURegister rd, FPURegister rs1, FPURegister rs2)
void GenInstrALUFP_rr (uint8_t funct7, uint8_t funct3, FPURegister rd, Register rs1, Register rs2)
void GenInstrALUFP_rr (uint8_t funct7, uint8_t funct3, FPURegister rd, FPURegister rs1, Register rs2)
void GenInstrALUFP_rr (uint8_t funct7, uint8_t funct3, Register rd, FPURegister rs1, Register rs2)
void GenInstrALUFP_rr (uint8_t funct7, uint8_t funct3, Register rd, FPURegister rs1, FPURegister rs2)
virtual void BlockTrampolinePoolFor (int instructions)=0
Detailed Description
Definition at line 63 of file base-assembler-riscv.h.
Member Enumeration Documentation
OffsetSize
enum v8::internal::AssemblerRiscvBase::OffsetSize : int [protected]
Enumerator
kOffset21
kOffset12
kOffset20
kOffset13
kOffset32
kOffset11
kOffset9
Definition at line 68 of file base-assembler-riscv.h.
                  : int {
    kOffset21 = 21, // RISCV jal
    kOffset12 = 12, // RISCV imm12
    kOffset20 = 20, // RISCV imm20
    kOffset13 = 13, // RISCV branch
    kOffset32 = 32, // RISCV auipc + instr_I
    kOffset11 = 11, // RISCV C_J
    kOffset9 = 9 // RISCV compressed branch
  };
Member Function Documentation
BlockTrampolinePoolFor()
virtual void v8::internal::AssemblerRiscvBase::BlockTrampolinePoolFor (int instructions) [protected], [pure virtual]
Implemented in v8::internal::Assembler, v8::internal::Assembler, v8::internal::Assembler, and v8::internal::Assembler.
Referenced by v8::internal::AssemblerRISCVC::c_j(), v8::internal::AssemblerRISCVC::c_jalr(), v8::internal::AssemblerRISCVC::c_jr(), v8::internal::AssemblerRISCVI::jal(), and v8::internal::AssemblerRISCVI::jalr().
branch_offset_helper()
virtual int32_t v8::internal::AssemblerRiscvBase::branch_offset_helper (Label * L, OffsetSize bits) [protected], [pure virtual]
Referenced by v8::internal::AssemblerRISCVI::branch_offset(), v8::internal::AssemblerRISCVC::cbranch_offset(), v8::internal::AssemblerRISCVC::cjump_offset(), and v8::internal::AssemblerRISCVI::jump_offset().
ClearVectorunit()
virtual void v8::internal::AssemblerRiscvBase::ClearVectorunit () [protected], [pure virtual]
Implemented in v8::internal::Assembler.
Referenced by v8::internal::AssemblerRISCVI::beq(), v8::internal::AssemblerRISCVI::bge(), v8::internal::AssemblerRISCVI::bgeu(), v8::internal::AssemblerRISCVI::blt(), v8::internal::AssemblerRISCVI::bltu(), v8::internal::AssemblerRISCVI::bne(), v8::internal::AssemblerRISCVI::jal(), and v8::internal::AssemblerRISCVI::jalr().
emit() [1/3]
virtual void v8::internal::AssemblerRiscvBase::emit (Instr x) [protected], [pure virtual]
Implemented in v8::internal::Assembler, v8::internal::Assembler, v8::internal::Assembler, and v8::internal::Assembler.
Referenced by GenInstrB(), GenInstrCA(), GenInstrCB(), GenInstrCBA(), GenInstrCI(), GenInstrCIU(), GenInstrCIW(), GenInstrCJ(), GenInstrCL(), GenInstrCR(), GenInstrCS(), GenInstrCSS(), GenInstrI(), GenInstrIShift(), GenInstrIShiftW(), GenInstrJ(), GenInstrR(), GenInstrR4(), GenInstrRAtomic(), GenInstrRFrm(), GenInstrS(), GenInstrU(), v8::internal::AssemblerRISCVV::GenInstrV(), v8::internal::AssemblerRISCVV::vsetivli(), v8::internal::AssemblerRISCVV::vsetvl(), and v8::internal::AssemblerRISCVV::vsetvli().
emit() [2/3]
virtual void v8::internal::AssemblerRiscvBase::emit (ShortInstr x) [protected], [pure virtual]
Implemented in v8::internal::Assembler.
emit() [3/3]
virtual void v8::internal::AssemblerRiscvBase::emit (uint64_t x) [protected], [pure virtual]
Implemented in v8::internal::Assembler, v8::internal::Assembler, and v8::internal::Assembler.
GenInstrALU_ri()
void v8::internal::AssemblerRiscvBase::GenInstrALU_ri (uint8_t funct3, Register rd, Register rs1, int16_t imm12) [protected]
Definition at line 406 of file base-assembler-riscv.cc.
                                                                     {
  GenInstrI(funct3, OP_IMM, rd, rs1, imm12);
}
References GenInstrI(), and v8::internal::OP_IMM.
Referenced by v8::internal::AssemblerRISCVI::addi(), v8::internal::AssemblerRISCVI::andi(), v8::internal::AssemblerRISCVI::ori(), v8::internal::AssemblerRISCVI::slti(), v8::internal::AssemblerRISCVI::sltiu(), and v8::internal::AssemblerRISCVI::xori().
GenInstrALU_rr()
void v8::internal::AssemblerRiscvBase::GenInstrALU_rr (uint8_t funct7, uint8_t funct3, Register rd, Register rs1, Register rs2) [protected]
Definition at line 419 of file base-assembler-riscv.cc.
                                                      {
  GenInstrR(funct7, funct3, OP, rd, rs1, rs2);
}
References GenInstrR(), and v8::internal::OP.
Referenced by v8::internal::AssemblerRISCVI::add(), v8::internal::AssemblerRISCVI::and_(), v8::internal::AssemblerRISCVB::andn(), v8::internal::AssemblerRISCVB::bclr(), v8::internal::AssemblerRISCVB::bext(), v8::internal::AssemblerRISCVB::binv(), v8::internal::AssemblerRISCVB::bset(), v8::internal::AssemblerRISCVZicond::czero_eqz(), v8::internal::AssemblerRISCVZicond::czero_nez(), v8::internal::AssemblerRISCVM::div(), v8::internal::AssemblerRISCVM::divu(), v8::internal::AssemblerRISCVB::max(), v8::internal::AssemblerRISCVB::maxu(), v8::internal::AssemblerRISCVB::min(), v8::internal::AssemblerRISCVB::minu(), v8::internal::AssemblerRISCVM::mul(), v8::internal::AssemblerRISCVM::mulh(), v8::internal::AssemblerRISCVM::mulhsu(), v8::internal::AssemblerRISCVM::mulhu(), v8::internal::AssemblerRISCVI::or_(), v8::internal::AssemblerRISCVB::orn(), v8::internal::AssemblerRISCVM::rem(), v8::internal::AssemblerRISCVM::remu(), v8::internal::AssemblerRISCVB::sh1add(), v8::internal::AssemblerRISCVB::sh2add(), v8::internal::AssemblerRISCVB::sh3add(), v8::internal::AssemblerRISCVI::sll(), v8::internal::AssemblerRISCVI::slt(), v8::internal::AssemblerRISCVI::sltu(), v8::internal::AssemblerRISCVI::sra(), v8::internal::AssemblerRISCVI::srl(), v8::internal::AssemblerRISCVI::sub(), v8::internal::AssemblerRISCVB::xnor(), v8::internal::AssemblerRISCVI::xor_(), and v8::internal::AssemblerRISCVB::zexth().
GenInstrALUFP_rr() [1/5]
void v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr (uint8_t funct7, uint8_t funct3, FPURegister rd, FPURegister rs1, FPURegister rs2) [protected]
Definition at line 463 of file base-assembler-riscv.cc.
                                                           {
  GenInstrR(funct7, funct3, OP_FP, rd, rs1, rs2);
}
References GenInstrR(), and v8::internal::OP_FP.
Referenced by v8::internal::AssemblerRISCVD::fadd_d(), v8::internal::AssemblerRISCVZfh::fadd_h(), v8::internal::AssemblerRISCVF::fadd_s(), v8::internal::AssemblerRISCVD::fclass_d(), v8::internal::AssemblerRISCVZfh::fclass_h(), v8::internal::AssemblerRISCVF::fclass_s(), v8::internal::AssemblerRISCVZfh::fcvt_d_h(), v8::internal::AssemblerRISCVD::fcvt_d_s(), v8::internal::AssemblerRISCVD::fcvt_d_w(), v8::internal::AssemblerRISCVD::fcvt_d_wu(), v8::internal::AssemblerRISCVZfh::fcvt_h_d(), v8::internal::AssemblerRISCVZfh::fcvt_h_s(), v8::internal::AssemblerRISCVZfh::fcvt_h_w(), v8::internal::AssemblerRISCVZfh::fcvt_h_wu(), v8::internal::AssemblerRISCVD::fcvt_s_d(), v8::internal::AssemblerRISCVZfh::fcvt_s_h(), v8::internal::AssemblerRISCVF::fcvt_s_w(), v8::internal::AssemblerRISCVF::fcvt_s_wu(), v8::internal::AssemblerRISCVD::fcvt_w_d(), v8::internal::AssemblerRISCVZfh::fcvt_w_h(), v8::internal::AssemblerRISCVF::fcvt_w_s(), v8::internal::AssemblerRISCVD::fcvt_wu_d(), v8::internal::AssemblerRISCVZfh::fcvt_wu_h(), v8::internal::AssemblerRISCVF::fcvt_wu_s(), v8::internal::AssemblerRISCVD::fdiv_d(), v8::internal::AssemblerRISCVZfh::fdiv_h(), v8::internal::AssemblerRISCVF::fdiv_s(), v8::internal::AssemblerRISCVD::feq_d(), v8::internal::AssemblerRISCVZfh::feq_h(), v8::internal::AssemblerRISCVF::feq_s(), v8::internal::AssemblerRISCVD::fle_d(), v8::internal::AssemblerRISCVZfh::fle_h(), v8::internal::AssemblerRISCVF::fle_s(), v8::internal::AssemblerRISCVD::flt_d(), v8::internal::AssemblerRISCVZfh::flt_h(), v8::internal::AssemblerRISCVF::flt_s(), v8::internal::AssemblerRISCVD::fmax_d(), v8::internal::AssemblerRISCVZfh::fmax_h(), v8::internal::AssemblerRISCVF::fmax_s(), v8::internal::AssemblerRISCVD::fmin_d(), v8::internal::AssemblerRISCVZfh::fmin_h(), v8::internal::AssemblerRISCVF::fmin_s(), v8::internal::AssemblerRISCVD::fmul_d(), v8::internal::AssemblerRISCVZfh::fmul_h(), v8::internal::AssemblerRISCVF::fmul_s(), v8::internal::AssemblerRISCVZfh::fmv_h_x(), v8::internal::AssemblerRISCVF::fmv_w_x(), v8::internal::AssemblerRISCVZfh::fmv_x_h(), v8::internal::AssemblerRISCVF::fmv_x_w(), v8::internal::AssemblerRISCVD::fsgnj_d(), v8::internal::AssemblerRISCVZfh::fsgnj_h(), v8::internal::AssemblerRISCVF::fsgnj_s(), v8::internal::AssemblerRISCVD::fsgnjn_d(), v8::internal::AssemblerRISCVZfh::fsgnjn_h(), v8::internal::AssemblerRISCVF::fsgnjn_s(), v8::internal::AssemblerRISCVD::fsgnjx_d(), v8::internal::AssemblerRISCVZfh::fsgnjx_h(), v8::internal::AssemblerRISCVF::fsgnjx_s(), v8::internal::AssemblerRISCVD::fsqrt_d(), v8::internal::AssemblerRISCVZfh::fsqrt_h(), v8::internal::AssemblerRISCVF::fsqrt_s(), v8::internal::AssemblerRISCVD::fsub_d(), v8::internal::AssemblerRISCVZfh::fsub_h(), and v8::internal::AssemblerRISCVF::fsub_s().
GenInstrALUFP_rr() [2/5]
void v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr (uint8_t funct7, uint8_t funct3, FPURegister rd, FPURegister rs1, Register rs2) [protected]
Definition at line 475 of file base-assembler-riscv.cc.
                                                        {
  GenInstrR(funct7, funct3, OP_FP, rd, rs1, rs2);
}
References GenInstrR(), and v8::internal::OP_FP.
GenInstrALUFP_rr() [3/5]
void v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr (uint8_t funct7, uint8_t funct3, FPURegister rd, Register rs1, Register rs2) [protected]
Definition at line 469 of file base-assembler-riscv.cc.
                                                        {
  GenInstrR(funct7, funct3, OP_FP, rd, rs1, rs2);
}
References GenInstrR(), and v8::internal::OP_FP.
GenInstrALUFP_rr() [4/5]
void v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr (uint8_t funct7, uint8_t funct3, Register rd, FPURegister rs1, FPURegister rs2) [protected]
Definition at line 487 of file base-assembler-riscv.cc.
                                                           {
  GenInstrR(funct7, funct3, OP_FP, rd, rs1, rs2);
}
References GenInstrR(), and v8::internal::OP_FP.
GenInstrALUFP_rr() [5/5]
void v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr (uint8_t funct7, uint8_t funct3, Register rd, FPURegister rs1, Register rs2) [protected]
Definition at line 481 of file base-assembler-riscv.cc.
                                                        {
  GenInstrR(funct7, funct3, OP_FP, rd, rs1, rs2);
}
References GenInstrR(), and v8::internal::OP_FP.
GenInstrALUW_rr()
void v8::internal::AssemblerRiscvBase::GenInstrALUW_rr (uint8_t funct7, uint8_t funct3, Register rd, Register rs1, Register rs2) [protected]
Definition at line 442 of file base-assembler-riscv.cc.
                                                       {
  GenInstrR(funct7, funct3, OP_32, rd, rs1, rs2);
}
References GenInstrR(), and v8::internal::OP_32.
Referenced by v8::internal::AssemblerRISCVB::zexth().
GenInstrB()
void v8::internal::AssemblerRiscvBase::GenInstrB (uint8_t funct3, BaseOpcode opcode, Register rs1, Register rs2, int16_t imm12) [protected]
Definition at line 218 of file base-assembler-riscv.cc.
                                                                              {
  DCHECK(is_uint3(funct3) && rs1.is_valid() && rs2.is_valid() &&
         is_int13(imm13) && ((imm13 & 1) == 0));
  Instr instr = opcode | ((imm13 & 0x800) >> 4) | // bit 11
                ((imm13 & 0x1e) << 7) | // bits 4-1
                (funct3 << kFunct3Shift) | (rs1.code() << kRs1Shift) |
                (rs2.code() << kRs2Shift) |
                ((imm13 & 0x7e0) << 20) | // bits 10-5
                ((imm13 & 0x1000) << 19); // bit 12
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kRs1Shift, and v8::internal::kRs2Shift.
Referenced by GenInstrBranchCC_rri().
GenInstrBranchCC_rri()
void v8::internal::AssemblerRiscvBase::GenInstrBranchCC_rri (uint8_t funct3, Register rs1, Register rs2, int16_t imm12) [protected]
Definition at line 391 of file base-assembler-riscv.cc.
                                                                           {
  GenInstrB(funct3, BRANCH, rs1, rs2, imm13);
}
References v8::internal::BRANCH, and GenInstrB().
Referenced by v8::internal::AssemblerRISCVI::beq(), v8::internal::AssemblerRISCVI::bge(), v8::internal::AssemblerRISCVI::bgeu(), v8::internal::AssemblerRISCVI::blt(), v8::internal::AssemblerRISCVI::bltu(), and v8::internal::AssemblerRISCVI::bne().
GenInstrCA()
void v8::internal::AssemblerRiscvBase::GenInstrCA (uint8_t funct6, BaseOpcode opcode, Register rd, uint8_t funct, Register rs2) [protected]
Definition at line 257 of file base-assembler-riscv.cc.
                                                                              {
  DCHECK(is_uint6(funct6) && rd.is_valid() && rs2.is_valid() &&
         is_uint2(funct));
  ShortInstr instr = opcode | ((rs2.code() & 0x7) << kRvcRs2sShift) |
                     ((rd.code() & 0x7) << kRvcRs1sShift) |
                     (funct6 << kRvcFunct6Shift) | (funct << kRvcFunct2Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kRvcFunct2Shift, v8::internal::kRvcFunct6Shift, v8::internal::kRvcRs1sShift, and v8::internal::kRvcRs2sShift.
Referenced by v8::internal::AssemblerRISCVC::c_and(), v8::internal::AssemblerRISCVC::c_or(), v8::internal::AssemblerRISCVC::c_sub(), and v8::internal::AssemblerRISCVC::c_xor().
GenInstrCB()
void v8::internal::AssemblerRiscvBase::GenInstrCB (uint8_t funct3, BaseOpcode opcode, Register rs1, uint8_t uimm8) [protected]
Definition at line 371 of file base-assembler-riscv.cc.
                                                                 {
  DCHECK(is_uint3(funct3) && is_uint8(uimm8));
  ShortInstr instr = opcode | ((uimm8 & 0x1f) << 2) | ((uimm8 & 0xe0) << 5) |
                     ((rs1.code() & 0x7) << kRvcRs1sShift) |
                     (funct3 << kRvcFunct3Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::kRvcFunct3Shift, and v8::internal::kRvcRs1sShift.
Referenced by v8::internal::AssemblerRISCVC::c_beqz(), and v8::internal::AssemblerRISCVC::c_bnez().
GenInstrCBA()
void v8::internal::AssemblerRiscvBase::GenInstrCBA (uint8_t funct3, uint8_t funct2, BaseOpcode opcode, Register rs1, int8_t imm6) [protected]
Definition at line 380 of file base-assembler-riscv.cc.
                                                  {
  DCHECK(is_uint3(funct3) && is_uint2(funct2) && is_int6(imm6));
  ShortInstr instr = opcode | ((imm6 & 0x1f) << 2) | ((imm6 & 0x20) << 7) |
                     ((rs1.code() & 0x7) << kRvcRs1sShift) |
                     (funct3 << kRvcFunct3Shift) | (funct2 << 10);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::kRvcFunct3Shift, and v8::internal::kRvcRs1sShift.
Referenced by v8::internal::AssemblerRISCVC::c_andi(), v8::internal::AssemblerRISCVC::c_srai(), and v8::internal::AssemblerRISCVC::c_srli().
GenInstrCI()
void v8::internal::AssemblerRiscvBase::GenInstrCI (uint8_t funct3, BaseOpcode opcode, Register rd, int8_t imm6) [protected]
Definition at line 267 of file base-assembler-riscv.cc.
                                                              {
  DCHECK(is_uint3(funct3) && rd.is_valid() && is_int6(imm6));
  ShortInstr instr = opcode | ((imm6 & 0x1f) << 2) |
                     (rd.code() << kRvcRdShift) | ((imm6 & 0x20) << 7) |
                     (funct3 << kRvcFunct3Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kRvcFunct3Shift, and v8::internal::kRvcRdShift.
Referenced by v8::internal::AssemblerRISCVC::c_addi(), v8::internal::AssemblerRISCVC::c_li(), v8::internal::AssemblerRISCVC::c_lui(), and v8::internal::AssemblerRISCVC::c_nop().
GenInstrCIU() [1/2]
void v8::internal::AssemblerRiscvBase::GenInstrCIU (uint8_t funct3, BaseOpcode opcode, FPURegister rd, uint8_t uimm6) [protected]
Definition at line 285 of file base-assembler-riscv.cc.
                                                                    {
  DCHECK(is_uint3(funct3) && rd.is_valid() && is_uint6(uimm6));
  ShortInstr instr = opcode | ((uimm6 & 0x1f) << 2) |
                     (rd.code() << kRvcRdShift) | ((uimm6 & 0x20) << 7) |
                     (funct3 << kRvcFunct3Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kRvcFunct3Shift, and v8::internal::kRvcRdShift.
GenInstrCIU() [2/2]
void v8::internal::AssemblerRiscvBase::GenInstrCIU (uint8_t funct3, BaseOpcode opcode, Register rd, uint8_t uimm6) [protected]
Definition at line 276 of file base-assembler-riscv.cc.
                                                                 {
  DCHECK(is_uint3(funct3) && rd.is_valid() && is_uint6(uimm6));
  ShortInstr instr = opcode | ((uimm6 & 0x1f) << 2) |
                     (rd.code() << kRvcRdShift) | ((uimm6 & 0x20) << 7) |
                     (funct3 << kRvcFunct3Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kRvcFunct3Shift, and v8::internal::kRvcRdShift.
Referenced by v8::internal::AssemblerRISCVC::c_addi16sp(), v8::internal::AssemblerRISCVC::c_fldsp(), v8::internal::AssemblerRISCVC::c_lwsp(), and v8::internal::AssemblerRISCVC::c_slli().
GenInstrCIW()
void v8::internal::AssemblerRiscvBase::GenInstrCIW (uint8_t funct3, BaseOpcode opcode, Register rd, uint8_t uimm8) [protected]
Definition at line 294 of file base-assembler-riscv.cc.
                                                                 {
  DCHECK(is_uint3(funct3) && rd.is_valid() && is_uint8(uimm8));
  ShortInstr instr = opcode | ((uimm8) << 5) |
                     ((rd.code() & 0x7) << kRvcRs2sShift) |
                     (funct3 << kRvcFunct3Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kRvcFunct3Shift, and v8::internal::kRvcRs2sShift.
Referenced by v8::internal::AssemblerRISCVC::c_addi4spn().
GenInstrCJ()
void v8::internal::AssemblerRiscvBase::GenInstrCJ (uint8_t funct3, BaseOpcode opcode, uint16_t uint11) [protected]
Definition at line 341 of file base-assembler-riscv.cc.
                                                     {
  DCHECK(is_uint11(uint11));
  ShortInstr instr = opcode | (funct3 << kRvcFunct3Shift) | (uint11 << 2);
  emit(instr);
}
References v8::internal::DCHECK(), emit(), and v8::internal::kRvcFunct3Shift.
Referenced by v8::internal::AssemblerRISCVC::c_j().
GenInstrCL() [1/2]
void v8::internal::AssemblerRiscvBase::GenInstrCL (uint8_t funct3, BaseOpcode opcode, FPURegister rd, Register rs1, uint8_t uimm5) [protected]
Definition at line 330 of file base-assembler-riscv.cc.
                                                   {
  DCHECK(is_uint3(funct3) && rd.is_valid() && rs1.is_valid() &&
         is_uint5(uimm5));
  ShortInstr instr = opcode | ((uimm5 & 0x3) << 5) |
                     ((rd.code() & 0x7) << kRvcRs2sShift) |
                     ((uimm5 & 0x1c) << 8) | (funct3 << kRvcFunct3Shift) |
                     ((rs1.code() & 0x7) << kRvcRs1sShift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kRvcFunct3Shift, v8::internal::kRvcRs1sShift, and v8::internal::kRvcRs2sShift.
GenInstrCL() [2/2]
void v8::internal::AssemblerRiscvBase::GenInstrCL (uint8_t funct3, BaseOpcode opcode, Register rd, Register rs1, uint8_t uimm5) [protected]
Definition at line 319 of file base-assembler-riscv.cc.
                                                                              {
  DCHECK(is_uint3(funct3) && rd.is_valid() && rs1.is_valid() &&
         is_uint5(uimm5));
  ShortInstr instr = opcode | ((uimm5 & 0x3) << 5) |
                     ((rd.code() & 0x7) << kRvcRs2sShift) |
                     ((uimm5 & 0x1c) << 8) | (funct3 << kRvcFunct3Shift) |
                     ((rs1.code() & 0x7) << kRvcRs1sShift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kRvcFunct3Shift, v8::internal::kRvcRs1sShift, and v8::internal::kRvcRs2sShift.
Referenced by v8::internal::AssemblerRISCVC::c_fld(), and v8::internal::AssemblerRISCVC::c_lw().
GenInstrCR()
void v8::internal::AssemblerRiscvBase::GenInstrCR (uint8_t funct4, BaseOpcode opcode, Register rd, Register rs2) [protected]
Definition at line 249 of file base-assembler-riscv.cc.
                                                               {
  DCHECK(is_uint4(funct4) && rd.is_valid() && rs2.is_valid());
  ShortInstr instr = opcode | (rs2.code() << kRvcRs2Shift) |
                     (rd.code() << kRvcRdShift) | (funct4 << kRvcFunct4Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kRvcFunct4Shift, v8::internal::kRvcRdShift, and v8::internal::kRvcRs2Shift.
Referenced by v8::internal::AssemblerRISCVC::c_add(), v8::internal::AssemblerRISCVC::c_ebreak(), v8::internal::AssemblerRISCVC::c_jalr(), v8::internal::AssemblerRISCVC::c_jr(), and v8::internal::AssemblerRISCVC::c_mv().
GenInstrCS() [1/2]
void v8::internal::AssemblerRiscvBase::GenInstrCS (uint8_t funct3, BaseOpcode opcode, FPURegister rs2, Register rs1, uint8_t uimm5) [protected]
Definition at line 359 of file base-assembler-riscv.cc.
                                                   {
  DCHECK(is_uint3(funct3) && rs2.is_valid() && rs1.is_valid() &&
         is_uint5(uimm5));
  ShortInstr instr = opcode | ((uimm5 & 0x3) << 5) |
                     ((rs2.code() & 0x7) << kRvcRs2sShift) |
                     ((uimm5 & 0x1c) << 8) | (funct3 << kRvcFunct3Shift) |
                     ((rs1.code() & 0x7) << kRvcRs1sShift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kRvcFunct3Shift, v8::internal::kRvcRs1sShift, and v8::internal::kRvcRs2sShift.
GenInstrCS() [2/2]
void v8::internal::AssemblerRiscvBase::GenInstrCS (uint8_t funct3, BaseOpcode opcode, Register rs2, Register rs1, uint8_t uimm5) [protected]
Definition at line 348 of file base-assembler-riscv.cc.
                                                                               {
  DCHECK(is_uint3(funct3) && rs2.is_valid() && rs1.is_valid() &&
         is_uint5(uimm5));
  ShortInstr instr = opcode | ((uimm5 & 0x3) << 5) |
                     ((rs2.code() & 0x7) << kRvcRs2sShift) |
                     ((uimm5 & 0x1c) << 8) | (funct3 << kRvcFunct3Shift) |
                     ((rs1.code() & 0x7) << kRvcRs1sShift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kRvcFunct3Shift, v8::internal::kRvcRs1sShift, and v8::internal::kRvcRs2sShift.
Referenced by v8::internal::AssemblerRISCVC::c_fsd(), and v8::internal::AssemblerRISCVC::c_sw().
GenInstrCSR_ii()
void v8::internal::AssemblerRiscvBase::GenInstrCSR_ii (uint8_t funct3, Register rd, ControlStatusReg csr, uint8_t rs1) [protected]
Definition at line 430 of file base-assembler-riscv.cc.
                                                                            {
  GenInstrI(funct3, SYSTEM, rd, ToRegister(imm5), csr);
}
References GenInstrI(), v8::internal::SYSTEM, and v8::internal::ToRegister().
Referenced by v8::internal::AssemblerRISCVZicsr::csrrci(), v8::internal::AssemblerRISCVZicsr::csrrsi(), and v8::internal::AssemblerRISCVZicsr::csrrwi().
GenInstrCSR_ir()
void v8::internal::AssemblerRiscvBase::GenInstrCSR_ir (uint8_t funct3, Register rd, ControlStatusReg csr, Register rs1) [protected]
Definition at line 425 of file base-assembler-riscv.cc.
                                                                            {
  GenInstrI(funct3, SYSTEM, rd, rs1, csr);
}
References GenInstrI(), and v8::internal::SYSTEM.
Referenced by v8::internal::AssemblerRISCVZicsr::csrrc(), v8::internal::AssemblerRISCVZicsr::csrrs(), and v8::internal::AssemblerRISCVZicsr::csrrw().
GenInstrCSS() [1/2]
void v8::internal::AssemblerRiscvBase::GenInstrCSS (uint8_t funct3, BaseOpcode opcode, FPURegister rs2, uint8_t uimm6) [protected]
Definition at line 311 of file base-assembler-riscv.cc.
                                                                     {
  DCHECK(is_uint3(funct3) && rs2.is_valid() && is_uint6(uimm6));
  ShortInstr instr = opcode | (uimm6 << 7) | (rs2.code() << kRvcRs2Shift) |
                     (funct3 << kRvcFunct3Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kRvcFunct3Shift, and v8::internal::kRvcRs2Shift.
Referenced by v8::internal::AssemblerRISCVC::c_fsdsp(), and v8::internal::AssemblerRISCVC::c_swsp().
GenInstrCSS() [2/2]
void v8::internal::AssemblerRiscvBase::GenInstrCSS (uint8_t funct3, BaseOpcode opcode, Register rs2, uint8_t uimm6) [protected]
Definition at line 303 of file base-assembler-riscv.cc.
                                                                  {
  DCHECK(is_uint3(funct3) && rs2.is_valid() && is_uint6(uimm6));
  ShortInstr instr = opcode | (uimm6 << 7) | (rs2.code() << kRvcRs2Shift) |
                     (funct3 << kRvcFunct3Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kRvcFunct3Shift, and v8::internal::kRvcRs2Shift.
GenInstrI() [1/2]
void v8::internal::AssemblerRiscvBase::GenInstrI (uint8_t funct3, BaseOpcode opcode, FPURegister rd, Register rs1, int16_t imm12) [protected]
Definition at line 163 of file base-assembler-riscv.cc.
                                                  {
  DCHECK(is_uint3(funct3) && rd.is_valid() && rs1.is_valid() &&
         (is_uint12(imm12) || is_int12(imm12)));
  Instr instr = opcode | (rd.code() << kRdShift) | (funct3 << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (imm12 << kImm12Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kImm12Shift, v8::internal::kRdShift, and v8::internal::kRs1Shift.
GenInstrI() [2/2]
void v8::internal::AssemblerRiscvBase::GenInstrI (uint8_t funct3, BaseOpcode opcode, Register rd, Register rs1, int16_t imm12) [protected]
Definition at line 154 of file base-assembler-riscv.cc.
                                                                             {
  DCHECK(is_uint3(funct3) && rd.is_valid() && rs1.is_valid() &&
         (is_uint12(imm12) || is_int12(imm12)));
  Instr instr = opcode | (rd.code() << kRdShift) | (funct3 << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (imm12 << kImm12Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kImm12Shift, v8::internal::kRdShift, and v8::internal::kRs1Shift.
Referenced by v8::internal::AssemblerRISCVI::ebreak(), v8::internal::AssemblerRISCVI::ecall(), v8::internal::AssemblerRISCVI::fence(), v8::internal::AssemblerRISCVZifencei::fence_i(), v8::internal::AssemblerRISCVI::fence_tso(), GenInstrALU_ri(), GenInstrCSR_ii(), GenInstrCSR_ir(), GenInstrLoad_ri(), GenInstrLoadFP_ri(), v8::internal::AssemblerRISCVI::jalr(), v8::internal::AssemblerRISCVB::orcb(), v8::internal::AssemblerRISCVB::rev8(), v8::internal::AssemblerRISCVB::rori(), and v8::internal::AssemblerRISCVI::unimp().
GenInstrIShift()
void v8::internal::AssemblerRiscvBase::GenInstrIShift (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, Register rd, Register rs1, uint8_t shamt) [protected]
Definition at line 173 of file base-assembler-riscv.cc.
                                                                     {
  DCHECK(is_uint3(funct3) && rd.is_valid() && rs1.is_valid() &&
         is_uint6(shamt));
  Instr instr = opcode | (rd.code() << kRdShift) | (funct3 << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (shamt << kShamtShift) |
                (funct6 << kFunct6Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kFunct6Shift, v8::internal::kRdShift, v8::internal::kRs1Shift, and v8::internal::kShamtShift.
Referenced by v8::internal::AssemblerRISCVB::bclri(), v8::internal::AssemblerRISCVB::bexti(), v8::internal::AssemblerRISCVB::binvi(), v8::internal::AssemblerRISCVB::bseti(), and GenInstrShift_ri().
GenInstrIShiftW()
void v8::internal::AssemblerRiscvBase::GenInstrIShiftW (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, Register rd, Register rs1, uint8_t shamt) [protected]
Definition at line 184 of file base-assembler-riscv.cc.
                                                                      {
  DCHECK(is_uint3(funct3) && rd.is_valid() && rs1.is_valid() &&
         is_uint5(shamt));
  Instr instr = opcode | (rd.code() << kRdShift) | (funct3 << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (shamt << kShamtWShift) |
                (funct7 << kFunct7Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kFunct7Shift, v8::internal::kRdShift, v8::internal::kRs1Shift, and v8::internal::kShamtWShift.
Referenced by v8::internal::AssemblerRISCVB::bclri(), v8::internal::AssemblerRISCVB::bexti(), v8::internal::AssemblerRISCVB::binvi(), v8::internal::AssemblerRISCVB::bseti(), v8::internal::AssemblerRISCVB::clz(), v8::internal::AssemblerRISCVB::cpop(), v8::internal::AssemblerRISCVB::ctz(), GenInstrShiftW_ri(), v8::internal::AssemblerRISCVB::sextb(), and v8::internal::AssemblerRISCVB::sexth().
GenInstrJ()
void v8::internal::AssemblerRiscvBase::GenInstrJ (BaseOpcode opcode, Register rd, int32_t imm20) [protected]
Definition at line 238 of file base-assembler-riscv.cc.
                                                  {
  DCHECK(rd.is_valid() && is_int21(imm21) && ((imm21 & 1) == 0));
  Instr instr = opcode | (rd.code() << kRdShift) |
                (imm21 & 0xff000) | // bits 19-12
                ((imm21 & 0x800) << 9) | // bit 11
                ((imm21 & 0x7fe) << 20) | // bits 10-1
                ((imm21 & 0x100000) << 11); // bit 20
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), and v8::internal::kRdShift.
Referenced by v8::internal::AssemblerRISCVI::jal().
GenInstrLoad_ri()
void v8::internal::AssemblerRiscvBase::GenInstrLoad_ri (uint8_t funct3, Register rd, Register rs1, int16_t imm12) [protected]
Definition at line 396 of file base-assembler-riscv.cc.
                                                                      {
  GenInstrI(funct3, LOAD, rd, rs1, imm12);
}
References GenInstrI(), and v8::internal::LOAD.
Referenced by v8::internal::AssemblerRISCVI::lb(), v8::internal::AssemblerRISCVI::lbu(), v8::internal::AssemblerRISCVI::lh(), v8::internal::AssemblerRISCVI::lhu(), and v8::internal::AssemblerRISCVI::lw().
GenInstrLoadFP_ri()
void v8::internal::AssemblerRiscvBase::GenInstrLoadFP_ri (uint8_t funct3, FPURegister rd, Register rs1, int16_t imm12) [protected]
Definition at line 453 of file base-assembler-riscv.cc.
                                                                        {
  GenInstrI(funct3, LOAD_FP, rd, rs1, imm12);
}
References GenInstrI(), and v8::internal::LOAD_FP.
Referenced by v8::internal::AssemblerRISCVD::fld(), v8::internal::AssemblerRISCVZfh::flh(), and v8::internal::AssemblerRISCVF::flw().
GenInstrPriv()
void v8::internal::AssemblerRiscvBase::GenInstrPriv (uint8_t funct7, Register rs1, Register rs2) [protected]
Definition at line 448 of file base-assembler-riscv.cc.
                                                    {
  GenInstrR(funct7, 0b000, SYSTEM, ToRegister(0), rs1, rs2);
}
References GenInstrR(), v8::internal::SYSTEM, and v8::internal::ToRegister().
GenInstrR() [1/6]
void v8::internal::AssemblerRiscvBase::GenInstrR (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, FPURegister rd, FPURegister rs1, FPURegister rs2) [protected]
Definition at line 55 of file base-assembler-riscv.cc.
                                                                     {
  DCHECK(is_uint7(funct7) && is_uint3(funct3) && rd.is_valid() &&
         rs1.is_valid() && rs2.is_valid());
  Instr instr = opcode | (rd.code() << kRdShift) | (funct3 << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (rs2.code() << kRs2Shift) |
                (funct7 << kFunct7Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kFunct7Shift, v8::internal::kRdShift, v8::internal::kRs1Shift, and v8::internal::kRs2Shift.
GenInstrR() [2/6]
void v8::internal::AssemblerRiscvBase::GenInstrR (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, FPURegister rd, FPURegister rs1, Register rs2) [protected]
Definition at line 88 of file base-assembler-riscv.cc.
                                                                  {
  DCHECK(is_uint7(funct7) && is_uint3(funct3) && rd.is_valid() &&
         rs1.is_valid() && rs2.is_valid());
  Instr instr = opcode | (rd.code() << kRdShift) | (funct3 << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (rs2.code() << kRs2Shift) |
                (funct7 << kFunct7Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kFunct7Shift, v8::internal::kRdShift, v8::internal::kRs1Shift, and v8::internal::kRs2Shift.
GenInstrR() [3/6]
void v8::internal::AssemblerRiscvBase::GenInstrR (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, FPURegister rd, Register rs1, Register rs2) [protected]
Definition at line 77 of file base-assembler-riscv.cc.
                                                               {
  DCHECK(is_uint7(funct7) && is_uint3(funct3) && rd.is_valid() &&
         rs1.is_valid() && rs2.is_valid());
  Instr instr = opcode | (rd.code() << kRdShift) | (funct3 << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (rs2.code() << kRs2Shift) |
                (funct7 << kFunct7Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kFunct7Shift, v8::internal::kRdShift, v8::internal::kRs1Shift, and v8::internal::kRs2Shift.
GenInstrR() [4/6]
void v8::internal::AssemblerRiscvBase::GenInstrR (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, Register rd, FPURegister rs1, FPURegister rs2) [protected]
Definition at line 99 of file base-assembler-riscv.cc.
                                                                     {
  DCHECK(is_uint7(funct7) && is_uint3(funct3) && rd.is_valid() &&
         rs1.is_valid() && rs2.is_valid());
  Instr instr = opcode | (rd.code() << kRdShift) | (funct3 << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (rs2.code() << kRs2Shift) |
                (funct7 << kFunct7Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kFunct7Shift, v8::internal::kRdShift, v8::internal::kRs1Shift, and v8::internal::kRs2Shift.
GenInstrR() [5/6]
void v8::internal::AssemblerRiscvBase::GenInstrR (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, Register rd, FPURegister rs1, Register rs2) [protected]
Definition at line 66 of file base-assembler-riscv.cc.
                                                                  {
  DCHECK(is_uint7(funct7) && is_uint3(funct3) && rd.is_valid() &&
         rs1.is_valid() && rs2.is_valid());
  Instr instr = opcode | (rd.code() << kRdShift) | (funct3 << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (rs2.code() << kRs2Shift) |
                (funct7 << kFunct7Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kFunct7Shift, v8::internal::kRdShift, v8::internal::kRs1Shift, and v8::internal::kRs2Shift.
GenInstrR() [6/6]
void v8::internal::AssemblerRiscvBase::GenInstrR (uint8_t funct7, uint8_t funct3, BaseOpcode opcode, Register rd, Register rs1, Register rs2) [protected]
Definition at line 44 of file base-assembler-riscv.cc.
                                                 {
  DCHECK(is_uint7(funct7) && is_uint3(funct3) && rd.is_valid() &&
         rs1.is_valid() && rs2.is_valid());
  Instr instr = opcode | (rd.code() << kRdShift) | (funct3 << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (rs2.code() << kRs2Shift) |
                (funct7 << kFunct7Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kFunct7Shift, v8::internal::kRdShift, v8::internal::kRs1Shift, and v8::internal::kRs2Shift.
Referenced by GenInstrALU_rr(), GenInstrALUFP_rr(), GenInstrALUW_rr(), GenInstrPriv(), v8::internal::AssemblerRISCVB::rol(), and v8::internal::AssemblerRISCVB::ror().
GenInstrR4() [1/2]
void v8::internal::AssemblerRiscvBase::GenInstrR4 (uint8_t funct2, BaseOpcode opcode, FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm) [protected]
Definition at line 121 of file base-assembler-riscv.cc.
                                                         {
  DCHECK(is_uint2(funct2) && rd.is_valid() && rs1.is_valid() &&
         rs2.is_valid() && rs3.is_valid() && is_uint3(frm));
  Instr instr = opcode | (rd.code() << kRdShift) | (frm << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (rs2.code() << kRs2Shift) |
                (funct2 << kFunct2Shift) | (rs3.code() << kRs3Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct2Shift, v8::internal::kFunct3Shift, v8::internal::kRdShift, v8::internal::kRs1Shift, v8::internal::kRs2Shift, and v8::internal::kRs3Shift.
GenInstrR4() [2/2]
void v8::internal::AssemblerRiscvBase::GenInstrR4 (uint8_t funct2, BaseOpcode opcode, Register rd, Register rs1, Register rs2, Register rs3, FPURoundingMode frm) [protected]
Definition at line 110 of file base-assembler-riscv.cc.
                                                                       {
  DCHECK(is_uint2(funct2) && rd.is_valid() && rs1.is_valid() &&
         rs2.is_valid() && rs3.is_valid() && is_uint3(frm));
  Instr instr = opcode | (rd.code() << kRdShift) | (frm << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (rs2.code() << kRs2Shift) |
                (funct2 << kFunct2Shift) | (rs3.code() << kRs3Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct2Shift, v8::internal::kFunct3Shift, v8::internal::kRdShift, v8::internal::kRs1Shift, v8::internal::kRs2Shift, and v8::internal::kRs3Shift.
Referenced by v8::internal::AssemblerRISCVD::fmadd_d(), v8::internal::AssemblerRISCVZfh::fmadd_h(), v8::internal::AssemblerRISCVF::fmadd_s(), v8::internal::AssemblerRISCVD::fmsub_d(), v8::internal::AssemblerRISCVZfh::fmsub_h(), v8::internal::AssemblerRISCVF::fmsub_s(), v8::internal::AssemblerRISCVD::fnmadd_d(), v8::internal::AssemblerRISCVZfh::fnmadd_h(), v8::internal::AssemblerRISCVF::fnmadd_s(), v8::internal::AssemblerRISCVD::fnmsub_d(), v8::internal::AssemblerRISCVZfh::fnmsub_h(), and v8::internal::AssemblerRISCVF::fnmsub_s().
GenInstrRAtomic()
void v8::internal::AssemblerRiscvBase::GenInstrRAtomic (uint8_t funct5, bool aq, bool rl, uint8_t funct3, Register rd, Register rs1, Register rs2) [protected]
Definition at line 133 of file base-assembler-riscv.cc.
                                                                     {
  DCHECK(is_uint5(funct5) && is_uint3(funct3) && rd.is_valid() &&
         rs1.is_valid() && rs2.is_valid());
  Instr instr = AMO | (rd.code() << kRdShift) | (funct3 << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (rs2.code() << kRs2Shift) |
                (rl << kRlShift) | (aq << kAqShift) | (funct5 << kFunct5Shift);
  emit(instr);
}
References v8::internal::AMO, v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kAqShift, v8::internal::kFunct3Shift, v8::internal::kFunct5Shift, v8::internal::kRdShift, v8::internal::kRlShift, v8::internal::kRs1Shift, and v8::internal::kRs2Shift.
Referenced by v8::internal::AssemblerRISCVA::amoadd_w(), v8::internal::AssemblerRISCVA::amoand_w(), v8::internal::AssemblerRISCVA::amomax_w(), v8::internal::AssemblerRISCVA::amomaxu_w(), v8::internal::AssemblerRISCVA::amomin_w(), v8::internal::AssemblerRISCVA::amominu_w(), v8::internal::AssemblerRISCVA::amoor_w(), v8::internal::AssemblerRISCVA::amoswap_w(), v8::internal::AssemblerRISCVA::amoxor_w(), v8::internal::AssemblerRISCVA::lr_w(), and v8::internal::AssemblerRISCVA::sc_w().
GenInstrRFrm()
void v8::internal::AssemblerRiscvBase::GenInstrRFrm (uint8_t funct7, BaseOpcode opcode, Register rd, Register rs1, Register rs2, FPURoundingMode frm) [protected]
Definition at line 144 of file base-assembler-riscv.cc.
                                                           {
  DCHECK(rd.is_valid() && rs1.is_valid() && rs2.is_valid() && is_uint3(frm));
  Instr instr = opcode | (rd.code() << kRdShift) | (frm << kFunct3Shift) |
                (rs1.code() << kRs1Shift) | (rs2.code() << kRs2Shift) |
                (funct7 << kFunct7Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kFunct7Shift, v8::internal::kRdShift, v8::internal::kRs1Shift, and v8::internal::kRs2Shift.
GenInstrS() [1/2]
void v8::internal::AssemblerRiscvBase::GenInstrS (uint8_t funct3, BaseOpcode opcode, Register rs1, FPURegister rs2, int16_t imm12) [protected]
Definition at line 206 of file base-assembler-riscv.cc.
                                                  {
  DCHECK(is_uint3(funct3) && rs1.is_valid() && rs2.is_valid() &&
         is_int12(imm12));
  Instr instr = opcode | ((imm12 & 0x1f) << 7) | // bits 4-0
                (funct3 << kFunct3Shift) | (rs1.code() << kRs1Shift) |
                (rs2.code() << kRs2Shift) |
                ((imm12 & 0xfe0) << 20); // bits 11-5
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kRs1Shift, and v8::internal::kRs2Shift.
GenInstrS() [2/2]
void v8::internal::AssemblerRiscvBase::GenInstrS (uint8_t funct3, BaseOpcode opcode, Register rs1, Register rs2, int16_t imm12) [protected]
Definition at line 195 of file base-assembler-riscv.cc.
                                                                              {
  DCHECK(is_uint3(funct3) && rs1.is_valid() && rs2.is_valid() &&
         is_int12(imm12));
  Instr instr = opcode | ((imm12 & 0x1f) << 7) | // bits 4-0
                (funct3 << kFunct3Shift) | (rs1.code() << kRs1Shift) |
                (rs2.code() << kRs2Shift) |
                ((imm12 & 0xfe0) << 20); // bits 11-5
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kFunct3Shift, v8::internal::kRs1Shift, and v8::internal::kRs2Shift.
Referenced by GenInstrStore_rri(), and GenInstrStoreFP_rri().
GenInstrShift_ri()
void v8::internal::AssemblerRiscvBase::GenInstrShift_ri (bool arithshift, uint8_t funct3, Register rd, Register rs1, uint8_t shamt) [protected]
Definition at line 411 of file base-assembler-riscv.cc.
                                                         {
  DCHECK(is_uint6(shamt));
  GenInstrIShift(arithshift << (kArithShiftShift - kFunct6Shift), funct3,
                 OP_IMM, rd, rs1, shamt);
}
References v8::internal::DCHECK(), GenInstrIShift(), v8::internal::kArithShiftShift, v8::internal::kFunct6Shift, and v8::internal::OP_IMM.
Referenced by v8::internal::AssemblerRISCVI::slli(), v8::internal::AssemblerRISCVI::srai(), and v8::internal::AssemblerRISCVI::srli().
GenInstrShiftW_ri()
void v8::internal::AssemblerRiscvBase::GenInstrShiftW_ri (bool arithshift, uint8_t funct3, Register rd, Register rs1, uint8_t shamt) [protected]
Definition at line 435 of file base-assembler-riscv.cc.
                                                          {
  GenInstrIShiftW(arithshift << (kArithShiftShift - kFunct7Shift), funct3,
                  OP_IMM_32, rd, rs1, shamt);
}
References GenInstrIShiftW(), v8::internal::kArithShiftShift, v8::internal::kFunct7Shift, and v8::internal::OP_IMM_32.
GenInstrStore_rri()
void v8::internal::AssemblerRiscvBase::GenInstrStore_rri (uint8_t funct3, Register rs1, Register rs2, int16_t imm12) [protected]
Definition at line 401 of file base-assembler-riscv.cc.
                                                                        {
  GenInstrS(funct3, STORE, rs1, rs2, imm12);
}
References GenInstrS(), and v8::internal::STORE.
Referenced by v8::internal::AssemblerRISCVI::sb(), v8::internal::AssemblerRISCVI::sh(), and v8::internal::AssemblerRISCVI::sw().
GenInstrStoreFP_rri()
void v8::internal::AssemblerRiscvBase::GenInstrStoreFP_rri (uint8_t funct3, Register rs1, FPURegister rs2, int16_t imm12) [protected]
Definition at line 458 of file base-assembler-riscv.cc.
                                                                             {
  GenInstrS(funct3, STORE_FP, rs1, rs2, imm12);
}
References GenInstrS(), and v8::internal::STORE_FP.
Referenced by v8::internal::AssemblerRISCVD::fsd(), v8::internal::AssemblerRISCVZfh::fsh(), and v8::internal::AssemblerRISCVF::fsw().
GenInstrU()
void v8::internal::AssemblerRiscvBase::GenInstrU (BaseOpcode opcode, Register rd, int32_t imm20) [protected]
Definition at line 231 of file base-assembler-riscv.cc.
                                                  {
  DCHECK(rd.is_valid() && (is_int20(imm20) || is_uint20(imm20)));
  Instr instr = opcode | (rd.code() << kRdShift) | (imm20 << kImm20Shift);
  emit(instr);
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::internal::DCHECK(), emit(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::is_valid(), v8::internal::kImm20Shift, and v8::internal::kRdShift.
Referenced by v8::internal::AssemblerRISCVI::auipc(), and v8::internal::AssemblerRISCVI::lui().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/riscv/base-assembler-riscv.h
/mnt/V8SourceCode/src/codegen/riscv/base-assembler-riscv.cc