v8::internal::FixedArrayBuilder Class Reference
#include <string-builder.h>
Public Member Functions
FixedArrayBuilder (Isolate *isolate, int initial_capacity)
FixedArrayBuilder (DirectHandle< FixedArray > backing_store)
bool HasCapacity (int elements)
void EnsureCapacity (Isolate *isolate, int elements)
void Add (Tagged< Object > value)
void Add (Tagged< Smi > value)
DirectHandle< FixedArray > array ()
int length ()
int capacity ()
Static Public Member Functions
static FixedArrayBuilder Lazy (Isolate *isolate)
Private Member Functions
FixedArrayBuilder (Isolate *isolate)
Private Attributes
DirectHandle< FixedArray > array_
int length_
bool has_non_smi_elements_
Detailed Description
Definition at line 15 of file string-builder.h.
Constructor & Destructor Documentation
FixedArrayBuilder() [1/3]
v8::internal::FixedArrayBuilder::FixedArrayBuilder (Isolate * isolate, int initial_capacity) [explicit]
Definition at line 108 of file string-builder.cc.
    : array_(isolate->factory()->NewFixedArrayWithHoles(initial_capacity)),
      length_(0),
      has_non_smi_elements_(false) {
  // Require a non-zero initial size. Ensures that doubling the size to
  // extend the array will work.
  DCHECK_GT(initial_capacity, 0);
}
References DCHECK_GT.
Referenced by Lazy().
FixedArrayBuilder() [2/3]
v8::internal::FixedArrayBuilder::FixedArrayBuilder (DirectHandle< FixedArray > backing_store) [explicit]
Definition at line 117 of file string-builder.cc.
    : array_(backing_store), length_(0), has_non_smi_elements_(false) {
  // Require a non-zero initial size. Ensures that doubling the size to
  // extend the array will work.
  DCHECK_GT(backing_store->length(), 0);
}
References DCHECK_GT.
FixedArrayBuilder() [3/3]
v8::internal::FixedArrayBuilder::FixedArrayBuilder (Isolate * isolate) [explicit], [private]
Definition at line 124 of file string-builder.cc.
    : array_(isolate->factory()->empty_fixed_array()),
      length_(0),
      has_non_smi_elements_(false) {}
Member Function Documentation
Add() [1/2]
void v8::internal::FixedArrayBuilder::Add (Tagged< Object > value)
Definition at line 162 of file string-builder.cc.
                                                {
  DCHECK(!IsSmi(value));
  array_->set(length_, value);
  length_++;
  has_non_smi_elements_ = true;
}
References array_, v8::internal::DCHECK(), has_non_smi_elements_, v8::internal::IsSmi(), length_, and v8::internal::value.
Referenced by v8::internal::ReplacementStringBuilder::AddElement(), v8::internal::ReplacementStringBuilder::AddSubjectSlice(), and v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple().
Add() [2/2]
void v8::internal::FixedArrayBuilder::Add (Tagged< Smi > value)
Definition at line 169 of file string-builder.cc.
                                             {
  DCHECK(IsSmi(value));
  array_->set(length_, value);
  length_++;
}
References array_, v8::internal::DCHECK(), v8::internal::IsSmi(), length_, and v8::internal::value.
array()
DirectHandle<FixedArray> v8::internal::FixedArrayBuilder::array () [inline]
Definition at line 30 of file string-builder.h.
{ return array_; }
References array_.
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), and v8::internal::ReplacementStringBuilder::ToString().
capacity()
int v8::internal::FixedArrayBuilder::capacity ()
Definition at line 175 of file string-builder.cc.
{ return array_->length(); }
References array_.
EnsureCapacity()
void v8::internal::FixedArrayBuilder::EnsureCapacity (Isolate * isolate, int elements)
Definition at line 140 of file string-builder.cc.
                                                                     {
  int length = array_->length();
  int required_length = length_ + elements;
  if (length < required_length) {
    if (length == 0) {
      constexpr int kInitialCapacityForLazy = 16;
      array_ = isolate->factory()->NewFixedArrayWithHoles(
          std::max(kInitialCapacityForLazy, elements));
      return;
    }
    int new_length = length;
    do {
      new_length *= 2;
    } while (new_length < required_length);
    DirectHandle<FixedArray> extended_array =
        isolate->factory()->NewFixedArrayWithHoles(new_length);
    FixedArray::CopyElements(isolate, *extended_array, 0, *array_, 0, length_);
    array_ = extended_array;
  }
}
References array_, v8::internal::FixedArray::CopyElements(), v8::internal::Isolate::factory(), length(), length_, and v8::internal::FactoryBase< Impl >::NewFixedArrayWithHoles().
Referenced by v8::internal::ReplacementStringBuilder::EnsureCapacity(), and v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple().
HasCapacity()
bool v8::internal::FixedArrayBuilder::HasCapacity (int elements)
Definition at line 134 of file string-builder.cc.
                                                {
  int length = array_->length();
  int required_length = length_ + elements;
  return (length >= required_length);
}
References array_, length(), and length_.
Lazy()
FixedArrayBuilder v8::internal::FixedArrayBuilder::Lazy (Isolate * isolate) [static]
Definition at line 130 of file string-builder.cc.
                                                          {
  return FixedArrayBuilder(isolate);
}
References FixedArrayBuilder().
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple().
length()
int v8::internal::FixedArrayBuilder::length () [inline]
Definition at line 32 of file string-builder.h.
{ return length_; }
References length_.
Referenced by EnsureCapacity(), HasCapacity(), v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), and v8::internal::ReplacementStringBuilder::ToString().
Member Data Documentation
array_
DirectHandle<FixedArray> v8::internal::FixedArrayBuilder::array_ [private]
Definition at line 39 of file string-builder.h.
Referenced by Add(), array(), capacity(), EnsureCapacity(), and HasCapacity().
has_non_smi_elements_
bool v8::internal::FixedArrayBuilder::has_non_smi_elements_ [private]
Definition at line 41 of file string-builder.h.
Referenced by Add().
length_
int v8::internal::FixedArrayBuilder::length_ [private]
Definition at line 40 of file string-builder.h.
Referenced by Add(), EnsureCapacity(), HasCapacity(), and length().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/strings/string-builder.h
/mnt/V8SourceCode/src/strings/string-builder.cc