v8::internal::Sweeper::SweepingState< scope > Class Template Reference
Public Member Functions
SweepingState (Sweeper *sweeper)
~SweepingState ()
void InitializeSweeping ()
void StartSweeping ()
void StartConcurrentSweeping ()
void StopConcurrentSweeping ()
void FinishSweeping ()
void JoinSweeping ()
bool HasValidJob () const
bool HasActiveJob () const
bool in_progress () const
bool should_reduce_memory () const
std::vector< ConcurrentSweeper > & concurrent_sweepers ()
void Pause ()
void Resume ()
uint64_t trace_id () const
uint64_t background_trace_id () const
Private Types
using ConcurrentSweeper = std::conditional_t< scope==SweepingScope::kMinor, ConcurrentMinorSweeper, ConcurrentMajorSweeper >
using SweeperJob = std::conditional_t< scope==SweepingScope::kMinor, MinorSweeperJob, MajorSweeperJob >
Private Attributes
Sweeper * sweeper_
std::atomic< bool > in_progress_ {false}
std::unique_ptr< JobHandle > job_handle_
std::vector< ConcurrentSweeper > concurrent_sweepers_
uint64_t trace_id_ = 0
uint64_t background_trace_id_ = 0
bool should_reduce_memory_ = false
Detailed Description
template<SweepingScope scope>
class v8::internal::Sweeper::SweepingState< scope >
Definition at line 275 of file sweeper.h.
Member Typedef Documentation
ConcurrentSweeper
template<SweepingScope scope>
using v8::internal::Sweeper::SweepingState< scope >::ConcurrentSweeper = std::conditional_t<scope == SweepingScope::kMinor, ConcurrentMinorSweeper, ConcurrentMajorSweeper> [private]
Definition at line 276 of file sweeper.h.
SweeperJob
template<SweepingScope scope>
using v8::internal::Sweeper::SweepingState< scope >::SweeperJob = std::conditional_t<scope == SweepingScope::kMinor, MinorSweeperJob, MajorSweeperJob> [private]
Definition at line 279 of file sweeper.h.
Constructor & Destructor Documentation
SweepingState()
template<SweepingScope scope>
v8::internal::Sweeper::SweepingState< scope >::SweepingState (Sweeper * sweeper) [explicit]
Definition at line 249 of file sweeper.cc.
    : sweeper_(sweeper) {}
 SweepingState()
template<SweepingScope scope>
v8::internal::Sweeper::SweepingState< scope >::~SweepingState ()
Definition at line 253 of file sweeper.cc.
                                            {
  DCHECK(!in_progress_);
  DCHECK(concurrent_sweepers_.empty());
  DCHECK(!HasValidJob());
}
References v8::internal::DCHECK().
Member Function Documentation
background_trace_id()
template<SweepingScope scope>
uint64_t v8::internal::Sweeper::SweepingState< scope >::background_trace_id () const [inline]
Definition at line 306 of file sweeper.h.
{ return background_trace_id_; }
References v8::internal::Sweeper::SweepingState< scope >::background_trace_id_.
concurrent_sweepers()
template<SweepingScope scope>
std::vector<ConcurrentSweeper>& v8::internal::Sweeper::SweepingState< scope >::concurrent_sweepers () [inline]
Definition at line 298 of file sweeper.h.
                                                        {
      return concurrent_sweepers_;
    }
References v8::internal::Sweeper::SweepingState< scope >::concurrent_sweepers_.
FinishSweeping()
template<SweepingScope scope>
void v8::internal::Sweeper::SweepingState< scope >::FinishSweeping ()
Definition at line 339 of file sweeper.cc.
                                                 {
  DCHECK(in_progress_);
  // Sweeping jobs were already joined.
  DCHECK(!HasValidJob());
  concurrent_sweepers_.clear();
  in_progress_ = false;
}
References v8::internal::DCHECK().
Referenced by v8::internal::Sweeper::EnsureMajorCompleted(), and v8::internal::Sweeper::EnsureMinorCompleted().
HasActiveJob()
template<SweepingScope scope>
bool v8::internal::Sweeper::SweepingState< scope >::HasActiveJob () const
Definition at line 265 of file sweeper.cc.
                                                     {
  return HasValidJob() && job_handle_->IsActive();
}
Referenced by v8::internal::Sweeper::AreMajorSweeperTasksRunning(), and v8::internal::Sweeper::AreMinorSweeperTasksRunning().
HasValidJob()
template<SweepingScope scope>
bool v8::internal::Sweeper::SweepingState< scope >::HasValidJob () const
Definition at line 260 of file sweeper.cc.
                                                    {
  return job_handle_ && job_handle_->IsValid();
}
Referenced by v8::internal::Sweeper::AddPageImpl(), v8::internal::Sweeper::AddPromotedPage(), and v8::internal::Sweeper::UsingMajorSweeperTasks().
in_progress()
template<SweepingScope scope>
bool v8::internal::Sweeper::SweepingState< scope >::in_progress () const [inline]
Definition at line 296 of file sweeper.h.
{ return in_progress_; }
References v8::internal::Sweeper::SweepingState< scope >::in_progress_.
Referenced by v8::internal::Sweeper::major_sweeping_in_progress(), and v8::internal::Sweeper::minor_sweeping_in_progress().
InitializeSweeping()
template<SweepingScope scope>
void v8::internal::Sweeper::SweepingState< scope >::InitializeSweeping ()
Definition at line 275 of file sweeper.cc.
                                                     {
  DCHECK(!HasValidJob());
  DCHECK(!in_progress_);
  DCHECK(concurrent_sweepers_.empty());
  DCHECK_IMPLIES(scope == Sweeper::SweepingScope::kMinor, v8_flags.minor_ms);
  DCHECK_IMPLIES(scope == Sweeper::SweepingScope::kMinor,
                 !sweeper_->heap_->ShouldReduceMemory());
  should_reduce_memory_ = (scope != Sweeper::SweepingScope::kMinor) &&
                          sweeper_->heap_->ShouldReduceMemory();
  trace_id_ =
      (reinterpret_cast<uint64_t>(sweeper_) ^
       sweeper_->heap_->tracer()->CurrentEpoch(
           scope == SweepingScope::kMajor ? GCTracer::Scope::MC_SWEEP
                                          : GCTracer::Scope::MINOR_MS_SWEEP))
      << 1;
  background_trace_id_ = trace_id_ + 1;
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::Sweeper::kMinor, and v8::internal::v8_flags.
Referenced by v8::internal::Sweeper::InitializeMajorSweeping(), and v8::internal::Sweeper::InitializeMinorSweeping().
JoinSweeping()
template<SweepingScope scope>
void v8::internal::Sweeper::SweepingState< scope >::JoinSweeping ()
Definition at line 333 of file sweeper.cc.
                                               {
  DCHECK(in_progress_);
  if (HasValidJob()) job_handle_->Join();
}
References v8::internal::DCHECK().
Referenced by v8::internal::Sweeper::FinishMajorJobs(), and v8::internal::Sweeper::FinishMinorJobs().
Pause()
template<SweepingScope scope>
void v8::internal::Sweeper::SweepingState< scope >::Pause ()
Definition at line 349 of file sweeper.cc.
                                        {
  if (!job_handle_ || !job_handle_->IsValid()) return;
  DCHECK(v8_flags.concurrent_sweeping);
  job_handle_->Cancel();
  job_handle_.reset();
}
References v8::internal::DCHECK(), and v8::internal::v8_flags.
Referenced by v8::internal::Sweeper::PauseMajorSweepingScope::PauseMajorSweepingScope().
Resume()
template<SweepingScope scope>
void v8::internal::Sweeper::SweepingState< scope >::Resume ()
Definition at line 358 of file sweeper.cc.
                                         {
  DCHECK(in_progress_);
  job_handle_ = V8::GetCurrentPlatform()->PostJob(
      TaskPriority::kUserVisible,
      std::make_unique<SweeperJob>(sweeper_->heap_->isolate(), sweeper_));
}
References v8::internal::DCHECK(), v8::internal::V8::GetCurrentPlatform(), v8::kUserVisible, and v8::Platform::PostJob().
should_reduce_memory()
template<SweepingScope scope>
bool v8::internal::Sweeper::SweepingState< scope >::should_reduce_memory () const [inline]
Definition at line 297 of file sweeper.h.
{ return should_reduce_memory_; }
References v8::internal::Sweeper::SweepingState< scope >::should_reduce_memory_.
Referenced by v8::internal::Sweeper::EnsureMajorCompleted(), and v8::internal::Sweeper::EnsureMinorCompleted().
StartConcurrentSweeping()
template<SweepingScope scope>
void v8::internal::Sweeper::SweepingState< scope >::StartConcurrentSweeping ()
Definition at line 304 of file sweeper.cc.
                                                          {
  DCHECK(!HasValidJob());
  DCHECK(in_progress_);
  if (v8_flags.concurrent_sweeping &&
      !sweeper_->heap_->delay_sweeper_tasks_for_testing_) {
    auto job =
        std::make_unique<SweeperJob>(sweeper_->heap_->isolate(), sweeper_);
    GCTracer::Scope::ScopeId scope_id =
        scope == SweepingScope::kMinor
            ? GCTracer::Scope::MINOR_MS_SWEEP_START_JOBS
            : GCTracer::Scope::MC_SWEEP_START_JOBS;
    TRACE_GC_WITH_FLOW(sweeper_->heap_->tracer(), scope_id,
                       background_trace_id(), TRACE_EVENT_FLAG_FLOW_OUT);
    DCHECK_IMPLIES(v8_flags.minor_ms, concurrent_sweepers_.empty());
    int max_concurrent_sweeper_count =
        std::min(SweeperJob::kMaxTasks,
                 V8::GetCurrentPlatform()->NumberOfWorkerThreads() + 1);
    if (concurrent_sweepers_.empty()) {
      for (int i = 0; i < max_concurrent_sweeper_count; ++i) {
        concurrent_sweepers_.emplace_back(sweeper_);
      }
    }
    DCHECK_EQ(max_concurrent_sweeper_count, concurrent_sweepers_.size());
    job_handle_ = V8::GetCurrentPlatform()->PostJob(TaskPriority::kUserVisible,
                                                    std::move(job));
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::V8::GetCurrentPlatform(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Sweeper::kMinor, v8::kUserVisible, v8::Platform::PostJob(), TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_WITH_FLOW, and v8::internal::v8_flags.
Referenced by v8::internal::Sweeper::StartMajorSweeperTasks(), and v8::internal::Sweeper::StartMinorSweeperTasks().
StartSweeping()
template<SweepingScope scope>
void v8::internal::Sweeper::SweepingState< scope >::StartSweeping ()
Definition at line 294 of file sweeper.cc.
                                                {
  DCHECK(!HasValidJob());
  DCHECK(!in_progress_);
  DCHECK(concurrent_sweepers_.empty());
  DCHECK_NE(0, trace_id_);
  DCHECK_NE(0, background_trace_id_);
  in_progress_ = true;
}
Referenced by v8::internal::Sweeper::StartMajorSweeping(), and v8::internal::Sweeper::StartMinorSweeping().
StopConcurrentSweeping()
template<SweepingScope scope>
void v8::internal::Sweeper::SweepingState< scope >::StopConcurrentSweeping ()
Definition at line 270 of file sweeper.cc.
                                                         {
  if (HasValidJob()) job_handle_->Cancel();
}
Referenced by v8::internal::Sweeper::TearDown().
trace_id()
template<SweepingScope scope>
uint64_t v8::internal::Sweeper::SweepingState< scope >::trace_id () const [inline]
Definition at line 305 of file sweeper.h.
{ return trace_id_; }
References v8::internal::Sweeper::SweepingState< scope >::trace_id_.
Referenced by v8::internal::Sweeper::FinishMajorJobs(), v8::internal::Sweeper::FinishMinorJobs(), and v8::internal::Sweeper::GetTraceIdForFlowEvent().
Member Data Documentation
background_trace_id_
template<SweepingScope scope>
uint64_t v8::internal::Sweeper::SweepingState< scope >::background_trace_id_ = 0 [private]
Definition at line 317 of file sweeper.h.
Referenced by v8::internal::Sweeper::SweepingState< scope >::background_trace_id().
concurrent_sweepers_
template<SweepingScope scope>
std::vector<ConcurrentSweeper> v8::internal::Sweeper::SweepingState< scope >::concurrent_sweepers_ [private]
Definition at line 315 of file sweeper.h.
Referenced by v8::internal::Sweeper::SweepingState< scope >::concurrent_sweepers().
in_progress_
template<SweepingScope scope>
std::atomic<bool> v8::internal::Sweeper::SweepingState< scope >::in_progress_ {false} [private]
Definition at line 313 of file sweeper.h.
Referenced by v8::internal::Sweeper::SweepingState< scope >::in_progress().
job_handle_
template<SweepingScope scope>
std::unique_ptr<JobHandle> v8::internal::Sweeper::SweepingState< scope >::job_handle_ [private]
Definition at line 314 of file sweeper.h.
should_reduce_memory_
template<SweepingScope scope>
bool v8::internal::Sweeper::SweepingState< scope >::should_reduce_memory_ = false [private]
Definition at line 318 of file sweeper.h.
Referenced by v8::internal::Sweeper::SweepingState< scope >::should_reduce_memory().
sweeper_
template<SweepingScope scope>
Sweeper* v8::internal::Sweeper::SweepingState< scope >::sweeper_ [private]
Definition at line 309 of file sweeper.h.
trace_id_
template<SweepingScope scope>
uint64_t v8::internal::Sweeper::SweepingState< scope >::trace_id_ = 0 [private]
Definition at line 316 of file sweeper.h.
Referenced by v8::internal::Sweeper::SweepingState< scope >::trace_id().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/sweeper.h
/mnt/V8SourceCode/src/heap/sweeper.cc