v8::internal::EphemeronTableUpdatingItem Class Reference
Public Types
enum EvacuationState { kRegular
, kAborted
 }
Public Member Functions
EphemeronTableUpdatingItem (Heap *heap)
~EphemeronTableUpdatingItem () override=default
void Process () override
Private Attributes
Heap *const heap_
Detailed Description
Definition at line 5568 of file mark-compact.cc.
Member Enumeration Documentation
EvacuationState
enum v8::internal::EphemeronTableUpdatingItem::EvacuationState
Enumerator
kRegular
kAborted
Definition at line 5570 of file mark-compact.cc.
{ kRegular, kAborted };
Constructor & Destructor Documentation
EphemeronTableUpdatingItem()
v8::internal::EphemeronTableUpdatingItem::EphemeronTableUpdatingItem (Heap * heap) [inline], [explicit]
Definition at line 5572 of file mark-compact.cc.
: heap_(heap) {}
 EphemeronTableUpdatingItem()
v8::internal::EphemeronTableUpdatingItem::~EphemeronTableUpdatingItem () [override], [default]
Member Function Documentation
Process()
void v8::internal::EphemeronTableUpdatingItem::Process () [inline], [override], [virtual]
Implements v8::internal::UpdatingItem.
Definition at line 5575 of file mark-compact.cc.
                          {
    TRACE_EVENT0(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
                 "EphemeronTableUpdatingItem::Process");
    PtrComprCageBase cage_base(heap_->isolate());
    auto* table_map = heap_->ephemeron_remembered_set()->tables();
    for (auto it = table_map->begin(); it != table_map->end(); it++) {
      Tagged<EphemeronHashTable> table = it->first;
      auto& indices = it->second;
      if (Cast<HeapObject>(table)
              ->map_word(kRelaxedLoad)
              .IsForwardingAddress()) {
        // The object has moved, so ignore slots in dead memory here.
        continue;
      }
      DCHECK(IsMap(table->map(), cage_base));
      DCHECK(IsEphemeronHashTable(table, cage_base));
      for (auto iti = indices.begin(); iti != indices.end(); ++iti) {
        // EphemeronHashTable keys must be heap objects.
        ObjectSlot key_slot(table->RawFieldOfElementAt(
            EphemeronHashTable::EntryToIndex(InternalIndex(*iti))));
        Tagged<Object> key_object = key_slot.Relaxed_Load();
        Tagged<HeapObject> key;
        CHECK(key_object.GetHeapObject(&key));
        MapWord map_word = key->map_word(cage_base, kRelaxedLoad);
        if (map_word.IsForwardingAddress()) {
          key = map_word.ToForwardingAddress(key);
          key_slot.Relaxed_Store(key);
        }
      }
    }
    table_map->clear();
  }
References CHECK, DCHECK, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::MapWord::IsForwardingAddress(), v8::internal::key, v8::kRelaxedLoad, v8::internal::FullObjectSlot::Relaxed_Load(), v8::internal::FullObjectSlot::Relaxed_Store(), v8::internal::MapWord::ToForwardingAddress(), TRACE_DISABLED_BY_DEFAULT, and TRACE_EVENT0.
Member Data Documentation
heap_
Heap* const v8::internal::EphemeronTableUpdatingItem::heap_ [private]
Definition at line 5610 of file mark-compact.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc