v8::internal::OptimizingCompileOutputQueue Class Reference
#include <optimizing-compile-dispatcher.h>
Public Member Functions
void Enqueue (TurbofanCompilationJob *job)
std::unique_ptr< TurbofanCompilationJob > Dequeue ()
int InstallGeneratedBuiltins (Isolate *isolate, int installed_count)
size_t size () const
bool empty () const
Private Attributes
std::deque< TurbofanCompilationJob * > queue_
base::Mutex mutex_
Detailed Description
Definition at line 155 of file optimizing-compile-dispatcher.h.
Member Function Documentation
Dequeue()
std::unique_ptr< TurbofanCompilationJob > v8::internal::OptimizingCompileOutputQueue::Dequeue ()
Definition at line 464 of file optimizing-compile-dispatcher.cc.
                                      {
  base::MutexGuard guard(&mutex_);
  if (queue_.empty()) return {};
  std::unique_ptr<TurbofanCompilationJob> job(queue_.front());
  queue_.pop_front();
  return job;
}
References mutex_, and queue_.
Referenced by v8::internal::OptimizingCompileDispatcher::FlushOutputQueue(), and v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions().
empty()
bool v8::internal::OptimizingCompileOutputQueue::empty () const
Definition at line 474 of file optimizing-compile-dispatcher.cc.
{ return queue_.empty(); }
References queue_.
Referenced by v8::internal::OptimizingCompileDispatcher::HasJobs().
Enqueue()
void v8::internal::OptimizingCompileOutputQueue::Enqueue (TurbofanCompilationJob * job)
Definition at line 458 of file optimizing-compile-dispatcher.cc.
                                                                      {
  base::MutexGuard guard(&mutex_);
  queue_.push_back(job);
}
References mutex_, and queue_.
Referenced by v8::internal::OptimizingCompileDispatcher::QueueFinishedJob().
InstallGeneratedBuiltins()
int v8::internal::OptimizingCompileOutputQueue::InstallGeneratedBuiltins (Isolate * isolate, int installed_count)
Definition at line 476 of file optimizing-compile-dispatcher.cc.
                                           {
  // Builtin generation needs to be deterministic, meaning heap allocations must
  // happen in a deterministic order. To ensure determinism with concurrent
  // compilation, only finalize contiguous builtins in ascending order of their
  // finalization order, which is set at job creation time.
  CHECK(isolate->IsGeneratingEmbeddedBuiltins());
  base::MutexGuard guard(&mutex_);
  std::sort(queue_.begin(), queue_.end(),
            [](const TurbofanCompilationJob* job1,
               const TurbofanCompilationJob* job2) {
              return job1->FinalizeOrder() < job2->FinalizeOrder();
            });
  while (!queue_.empty()) {
    int current = queue_.front()->FinalizeOrder();
    CHECK_EQ(installed_count, current);
    std::unique_ptr<TurbofanCompilationJob> job(queue_.front());
    queue_.pop_front();
    CHECK_EQ(CompilationJob::SUCCEEDED, job->FinalizeJob(isolate));
    installed_count = current + 1;
  }
  return installed_count;
}
References CHECK, CHECK_EQ, v8::internal::Isolate::IsGeneratingEmbeddedBuiltins(), mutex_, queue_, v8::base::sort(), and v8::internal::CompilationJob::SUCCEEDED.
Referenced by v8::internal::OptimizingCompileDispatcher::InstallGeneratedBuiltins().
size()
size_t v8::internal::OptimizingCompileOutputQueue::size () const
Definition at line 472 of file optimizing-compile-dispatcher.cc.
{ return queue_.size(); }
References queue_.
Referenced by v8::internal::OptimizingCompileDispatcher::~OptimizingCompileDispatcher().
Member Data Documentation
mutex_
base::Mutex v8::internal::OptimizingCompileOutputQueue::mutex_ [private]
Definition at line 171 of file optimizing-compile-dispatcher.h.
Referenced by Dequeue(), Enqueue(), and InstallGeneratedBuiltins().
queue_
std::deque<TurbofanCompilationJob*> v8::internal::OptimizingCompileOutputQueue::queue_ [private]
Definition at line 167 of file optimizing-compile-dispatcher.h.
Referenced by Dequeue(), empty(), Enqueue(), InstallGeneratedBuiltins(), and size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler-dispatcher/optimizing-compile-dispatcher.h
/mnt/V8SourceCode/src/compiler-dispatcher/optimizing-compile-dispatcher.cc