v8::internal::Counters Class Reference
#include <counters.h>
Public Types
enum Id { stats_counter_count
 }
Public Member Functions
Counters (Isolate *isolate)
void ResetCounterFunction (CounterLookupCallback f)
void ResetCreateHistogramFunction (CreateHistogramCallback f)
void SetAddHistogramSampleFunction (AddHistogramSampleCallback f)
RuntimeCallStats * runtime_call_stats ()
WorkerThreadRuntimeCallStats * worker_thread_runtime_call_stats ()
Private Member Functions
int * FindLocation (const char *name)
void * CreateHistogram (const char *name, int min, int max, size_t buckets)
void AddHistogramSample (void *histogram, int sample)
Isolate * isolate ()
DISALLOW_IMPLICIT_CONSTRUCTORS (Counters)
Private Attributes
Isolate * isolate_
StatsTable stats_table_
Friends
class CountersVisitor
class Histogram
class NestedTimedHistogramScope
class StatsCounter
class StatsTable
Detailed Description
Definition at line 504 of file counters.h.
Member Enumeration Documentation
Id
enum v8::internal::Counters::Id
Enumerator
stats_counter_count
Definition at line 598 of file counters.h.
          {
#define RATE_ID(name, caption, max, res) k_##name,
    NESTED_TIMED_HISTOGRAM_LIST(RATE_ID)
    NESTED_TIMED_HISTOGRAM_LIST_SLOW(RATE_ID)
    TIMED_HISTOGRAM_LIST(RATE_ID)
#undef RATE_ID
#define AGGREGATABLE_ID(name, caption) k_##name,
    AGGREGATABLE_HISTOGRAM_TIMER_LIST(AGGREGATABLE_ID)
#undef AGGREGATABLE_ID
#define PERCENTAGE_ID(name, caption) k_##name,
    HISTOGRAM_PERCENTAGE_LIST(PERCENTAGE_ID)
#undef PERCENTAGE_ID
#define MEMORY_ID(name, caption) k_##name,
    HISTOGRAM_LEGACY_MEMORY_LIST(MEMORY_ID)
#undef MEMORY_ID
#define COUNTER_ID(name, caption) k_##name,
    STATS_COUNTER_LIST(COUNTER_ID)
    STATS_COUNTER_NATIVE_CODE_LIST(COUNTER_ID)
#undef COUNTER_ID
#define COUNTER_ID(name) kCountOf##name, kSizeOf##name,
    INSTANCE_TYPE_LIST(COUNTER_ID)
#undef COUNTER_ID
#define COUNTER_ID(name) kCountOfCODE_TYPE_##name, \
    kSizeOfCODE_TYPE_##name,
    CODE_KIND_LIST(COUNTER_ID)
#undef COUNTER_ID
    stats_counter_count
  };
Constructor & Destructor Documentation
Counters()
v8::internal::Counters::Counters (Isolate * isolate) [explicit]
Definition at line 157 of file counters.cc.
    :
#ifdef V8_RUNTIME_CALL_STATS
      runtime_call_stats_(RuntimeCallStats::kMainIsolateThread),
      worker_thread_runtime_call_stats_(),
#endif
      isolate_(isolate),
      stats_table_(this) {
  CountersInitializer init(this);
  init.Start();
}
References v8::internal::CountersVisitor::Start().
Member Function Documentation
AddHistogramSample()
void v8::internal::Counters::AddHistogramSample (void * histogram, int sample) [inline], [private]
Definition at line 657 of file counters.h.
                                                       {
    stats_table_.AddHistogramSample(histogram, sample);
  }
References v8::internal::StatsTable::AddHistogramSample(), and stats_table_.
Referenced by v8::internal::Histogram::AddSample().
CreateHistogram()
void* v8::internal::Counters::CreateHistogram (const char * name, int min, int max, size_t buckets) [inline], [private]
Definition at line 653 of file counters.h.
                                                                            {
    return stats_table_.CreateHistogram(name, min, max, buckets);
  }
References v8::internal::StatsTable::CreateHistogram(), v8::internal::name, and stats_table_.
Referenced by v8::internal::Histogram::CreateHistogram().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::Counters::DISALLOW_IMPLICIT_CONSTRUCTORS (Counters) [private]
FindLocation()
int* v8::internal::Counters::FindLocation (const char * name) [inline], [private]
Definition at line 649 of file counters.h.
                                      {
    return stats_table_.FindLocation(name);
  }
References v8::internal::StatsTable::FindLocation(), v8::internal::name, and stats_table_.
Referenced by v8::internal::StatsCounter::SetupPtrFromStatsTable().
isolate()
Isolate* v8::internal::Counters::isolate () [inline], [private]
Definition at line 661 of file counters.h.
{ return isolate_; }
References isolate_.
ResetCounterFunction()
void v8::internal::Counters::ResetCounterFunction (CounterLookupCallback f)
Definition at line 174 of file counters.cc.
                                                           {
  stats_table_.SetCounterFunction(f);
  StatsCounterResetter resetter(this);
  resetter.Start();
}
References v8::internal::StatsTable::SetCounterFunction(), v8::internal::CountersVisitor::Start(), and stats_table_.
Referenced by v8::Isolate::SetCounterFunction().
ResetCreateHistogramFunction()
void v8::internal::Counters::ResetCreateHistogramFunction (CreateHistogramCallback f)
Definition at line 185 of file counters.cc.
                                                                     {
  stats_table_.SetCreateHistogramFunction(f);
  HistogramResetter resetter(this);
  resetter.Start();
}
References v8::internal::StatsTable::SetCreateHistogramFunction(), v8::internal::CountersVisitor::Start(), and stats_table_.
Referenced by v8::Isolate::SetCreateHistogramFunction().
runtime_call_stats()
RuntimeCallStats* v8::internal::Counters::runtime_call_stats () [inline]
Definition at line 635 of file counters.h.
{ return nullptr; }
Referenced by v8::internal::compiler::CompileCWasmEntry(), v8::internal::anonymous_namespace{compiler.cc}::CompileMaglev(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), v8::internal::ProfilerCodeObserver::CreateEntriesForRuntimeCallStats(), v8::internal::Isolate::DumpAndResetStats(), v8::internal::compiler::CodeAssemblerTurboshaftCompilationJob::FinalizeCode(), v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), v8::internal::TickSample::GetStackSample(), v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl(), v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl(), v8::internal::compiler::CodeAssembler::BuiltinCompilationScheduler::QueueJob(), v8::internal::RUNTIME_FUNCTION(), v8::internal::V8FileLogger::RuntimeCallTimerEvent(), and v8::internal::GCTracer::Scope::Scope().
SetAddHistogramSampleFunction()
void v8::internal::Counters::SetAddHistogramSampleFunction (AddHistogramSampleCallback f) [inline]
Definition at line 521 of file counters.h.
                                                                   {
    stats_table_.SetAddHistogramSampleFunction(f);
  }
References v8::internal::StatsTable::SetAddHistogramSampleFunction(), and stats_table_.
worker_thread_runtime_call_stats()
WorkerThreadRuntimeCallStats* v8::internal::Counters::worker_thread_runtime_call_stats () [inline]
Definition at line 637 of file counters.h.
                                                                   {
    return nullptr;
  }
Referenced by v8::internal::Isolate::DumpAndResetStats(), and v8::internal::RUNTIME_FUNCTION().
Friends And Related Function Documentation
CountersVisitor
friend class CountersVisitor [friend]
Definition at line 643 of file counters.h.
Histogram
friend class Histogram [friend]
Definition at line 644 of file counters.h.
NestedTimedHistogramScope
friend class NestedTimedHistogramScope [friend]
Definition at line 645 of file counters.h.
StatsCounter
friend class StatsCounter [friend]
Definition at line 646 of file counters.h.
StatsTable
friend class StatsTable [friend]
Definition at line 647 of file counters.h.
Member Data Documentation
isolate_
Isolate* v8::internal::Counters::isolate_ [private]
Definition at line 700 of file counters.h.
Referenced by isolate().
stats_table_
StatsTable v8::internal::Counters::stats_table_ [private]
Definition at line 701 of file counters.h.
Referenced by AddHistogramSample(), CreateHistogram(), FindLocation(), ResetCounterFunction(), ResetCreateHistogramFunction(), and SetAddHistogramSampleFunction().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/logging/counters.h
/mnt/V8SourceCode/src/logging/counters.cc