v8::internal::compiler::JSFunctionData Class Reference
Public Types
enum UsedField {
kHasFeedbackVector = 1 << 0
, kPrototypeOrInitialMap = 1 << 1
, kHasInitialMap = 1 << 2
, kHasInstancePrototype = 1 << 3
,
kPrototypeRequiresRuntimeLookup = 1 << 4
, kInitialMap = 1 << 5
, kInstancePrototype = 1 << 6
, kFeedbackVector = 1 << 7
,
kFeedbackCell = 1 << 8
, kInitialMapInstanceSizeWithMinSlack = 1 << 9
 }
Public Member Functions
JSFunctionData (JSHeapBroker *broker, ObjectData **storage, IndirectHandle< JSFunction > object, ObjectDataKind kind)
bool IsConsistentWithHeapState (JSHeapBroker *broker) const
bool has_initial_map () const
bool has_instance_prototype () const
bool PrototypeRequiresRuntimeLookup () const
ObjectData * context () const
ObjectData * initial_map () const
ObjectData * instance_prototype () const
ObjectData * shared () const
ObjectData * raw_feedback_cell () const
int initial_map_instance_size_with_min_slack () const
bool has_any_used_field () const
bool has_used_field (UsedField used_field) const
void set_used_field (UsedField used_field)
Private Types
using UsedFields = base::Flags< UsedField >
Private Member Functions
void Cache (JSHeapBroker *broker)
Private Attributes
UsedFields used_fields_
ObjectData * prototype_or_initial_map_ = nullptr
bool has_initial_map_ = false
bool has_instance_prototype_ = false
bool PrototypeRequiresRuntimeLookup_ = false
ObjectData * context_ = nullptr
ObjectData * initial_map_
ObjectData * instance_prototype_
ObjectData * shared_ = nullptr
ObjectData * feedback_cell_ = nullptr
int initial_map_instance_size_with_min_slack_
Detailed Description
Definition at line 442 of file heap-refs.cc.
Member Typedef Documentation
UsedFields
using v8::internal::compiler::JSFunctionData::UsedFields = base::Flags<UsedField> [private]
Definition at line 518 of file heap-refs.cc.
Member Enumeration Documentation
UsedField
enum v8::internal::compiler::JSFunctionData::UsedField
Enumerator
kHasFeedbackVector
kPrototypeOrInitialMap
kHasInitialMap
kHasInstancePrototype
kPrototypeRequiresRuntimeLookup
kInitialMap
kInstancePrototype
kFeedbackVector
kFeedbackCell
kInitialMapInstanceSizeWithMinSlack
Definition at line 492 of file heap-refs.cc.
                 {
    kHasFeedbackVector = 1 << 0,
    kPrototypeOrInitialMap = 1 << 1,
    kHasInitialMap = 1 << 2,
    kHasInstancePrototype = 1 << 3,
    kPrototypeRequiresRuntimeLookup = 1 << 4,
    kInitialMap = 1 << 5,
    kInstancePrototype = 1 << 6,
    kFeedbackVector = 1 << 7,
    kFeedbackCell = 1 << 8,
    kInitialMapInstanceSizeWithMinSlack = 1 << 9,
  };
Constructor & Destructor Documentation
JSFunctionData()
v8::internal::compiler::JSFunctionData::JSFunctionData (JSHeapBroker * broker, ObjectData ** storage, IndirectHandle< JSFunction > object, ObjectDataKind kind) [inline]
Definition at line 444 of file heap-refs.cc.
      : JSObjectData(broker, storage, object, kind) {
    Cache(broker);
  }
References broker(), and Cache().
Member Function Documentation
Cache()
void v8::internal::compiler::JSFunctionData::Cache (JSHeapBroker * broker) [private]
Definition at line 631 of file heap-refs.cc.
                                               {
  DCHECK(!serialized_);
  TraceScope tracer(broker, this, "JSFunctionData::Cache");
  DirectHandle<JSFunction> function = Cast<JSFunction>(object());
  // This function may run on the background thread and thus must be individual
  // fields in a thread-safe manner. Consistency between fields is *not*
  // guaranteed here, instead we verify it in `IsConsistentWithHeapState`,
  // called during job finalization. Relaxed loads are thus okay: we're
  // guaranteed to see an initialized JSFunction object, and after
  // initialization fields remain in a valid state.
  ContextRef context =
      MakeRefAssumeMemoryFence(broker, function->context(kRelaxedLoad));
  context_ = context.data();
  SharedFunctionInfoRef shared =
      MakeRefAssumeMemoryFence(broker, function->shared(kRelaxedLoad));
  shared_ = shared.data();
  if (function->has_prototype_slot()) {
    prototype_or_initial_map_ = broker->GetOrCreateData(
        function->prototype_or_initial_map(kAcquireLoad), kAssumeMemoryFence);
    has_initial_map_ = prototype_or_initial_map_->IsMap();
    if (has_initial_map_) {
      // MapData is not used for initial_map_ because some
      // AlwaysSharedSpaceJSObject subclass constructors (e.g. SharedArray) have
      // initial maps in RO space, which can be accessed directly.
      initial_map_ = prototype_or_initial_map_;
      MapRef initial_map_ref = TryMakeRef<Map>(broker, initial_map_).value();
      if (initial_map_ref.IsInobjectSlackTrackingInProgress()) {
        initial_map_instance_size_with_min_slack_ =
            InstanceSizeWithMinSlack(broker, initial_map_ref);
      } else {
        initial_map_instance_size_with_min_slack_ =
            initial_map_ref.instance_size();
      }
      CHECK_GT(initial_map_instance_size_with_min_slack_, 0);
    }
    if (has_initial_map_) {
      has_instance_prototype_ = true;
      instance_prototype_ =
          MakeRefAssumeMemoryFence(
              broker, Cast<Map>(initial_map_->object())->prototype())
              .data();
    } else if (prototype_or_initial_map_->IsHeapObject() &&
               !IsTheHole(
                   *Cast<HeapObject>(prototype_or_initial_map_->object()))) {
      has_instance_prototype_ = true;
      instance_prototype_ = prototype_or_initial_map_;
    }
  }
  PrototypeRequiresRuntimeLookup_ = function->PrototypeRequiresRuntimeLookup();
  FeedbackCellRef feedback_cell = MakeRefAssumeMemoryFence(
      broker, function->raw_feedback_cell(kAcquireLoad));
  feedback_cell_ = feedback_cell.data();
#ifdef DEBUG
  serialized_ = true;
#endif // DEBUG
}
References broker(), CHECK_GT, context(), context_, v8::internal::DCHECK(), feedback_cell_, has_initial_map_, has_instance_prototype_, initial_map_, initial_map_instance_size_with_min_slack_, instance_prototype_, v8::internal::compiler::MapRef::instance_size(), v8::internal::compiler::anonymous_namespace{heap-refs.cc}::InstanceSizeWithMinSlack(), v8::internal::compiler::MapRef::IsInobjectSlackTrackingInProgress(), v8::kAcquireLoad, v8::internal::compiler::kAssumeMemoryFence, v8::kRelaxedLoad, v8::internal::compiler::MakeRefAssumeMemoryFence(), v8::internal::compiler::ObjectData::object(), prototype_or_initial_map_, PrototypeRequiresRuntimeLookup_, shared(), and shared_.
Referenced by JSFunctionData().
context()
ObjectData* v8::internal::compiler::JSFunctionData::context () const [inline]
Definition at line 465 of file heap-refs.cc.
                              {
    DCHECK(serialized_);
    return context_;
  }
References context_, and v8::internal::DCHECK().
Referenced by Cache().
has_any_used_field()
bool v8::internal::compiler::JSFunctionData::has_any_used_field () const [inline]
Definition at line 505 of file heap-refs.cc.
{ return used_fields_ != 0; }
References used_fields_.
Referenced by v8::internal::compiler::anonymous_namespace{heap-refs.cc}::RecordConsistentJSFunctionViewDependencyIfNeeded().
has_initial_map()
bool v8::internal::compiler::JSFunctionData::has_initial_map () const [inline]
Definition at line 452 of file heap-refs.cc.
                               {
    DCHECK(serialized_);
    return has_initial_map_;
  }
References v8::internal::DCHECK(), and has_initial_map_.
Referenced by IsConsistentWithHeapState().
has_instance_prototype()
bool v8::internal::compiler::JSFunctionData::has_instance_prototype () const [inline]
Definition at line 456 of file heap-refs.cc.
                                      {
    DCHECK(serialized_);
    return has_instance_prototype_;
  }
References v8::internal::DCHECK(), and has_instance_prototype_.
has_used_field()
bool v8::internal::compiler::JSFunctionData::has_used_field (UsedField used_field) const [inline]
Definition at line 506 of file heap-refs.cc.
                                                  {
    return (used_fields_ & used_field) != 0;
  }
References used_fields_.
Referenced by IsConsistentWithHeapState().
initial_map()
ObjectData* v8::internal::compiler::JSFunctionData::initial_map () const [inline]
Definition at line 469 of file heap-refs.cc.
                                  {
    DCHECK(serialized_);
    return initial_map_;
  }
References v8::internal::DCHECK(), and initial_map_.
initial_map_instance_size_with_min_slack()
int v8::internal::compiler::JSFunctionData::initial_map_instance_size_with_min_slack () const [inline]
Definition at line 485 of file heap-refs.cc.
                                                       {
    DCHECK(serialized_);
    return initial_map_instance_size_with_min_slack_;
  }
References v8::internal::DCHECK(), and initial_map_instance_size_with_min_slack_.
instance_prototype()
ObjectData* v8::internal::compiler::JSFunctionData::instance_prototype () const [inline]
Definition at line 473 of file heap-refs.cc.
                                         {
    DCHECK(serialized_);
    return instance_prototype_;
  }
References v8::internal::DCHECK(), and instance_prototype_.
IsConsistentWithHeapState()
bool v8::internal::compiler::JSFunctionData::IsConsistentWithHeapState (JSHeapBroker * broker) const
Definition at line 700 of file heap-refs.cc.
                                                                         {
  DCHECK(serialized_);
  DirectHandle<JSFunction> f = Cast<JSFunction>(object());
  if (*context_->object() != f->context()) {
    TRACE_BROKER_MISSING(broker, "JSFunction::context");
    return false;
  }
  CHECK_EQ(*shared_->object(), f->shared());
  if (f->has_prototype_slot()) {
    if (has_used_field(kPrototypeOrInitialMap) &&
        *prototype_or_initial_map_->object() !=
            f->prototype_or_initial_map(kAcquireLoad)) {
      TRACE_BROKER_MISSING(broker, "JSFunction::prototype_or_initial_map");
      return false;
    }
    if (has_used_field(kHasInitialMap) &&
        has_initial_map_ != f->has_initial_map()) {
      TRACE_BROKER_MISSING(broker, "JSFunction::has_initial_map");
      return false;
    }
    if (has_used_field(kHasInstancePrototype) &&
        has_instance_prototype_ != f->has_instance_prototype()) {
      TRACE_BROKER_MISSING(broker, "JSFunction::has_instance_prototype");
      return false;
    }
  } else {
    DCHECK(!has_initial_map_);
    DCHECK(!has_instance_prototype_);
  }
  if (has_initial_map()) {
    if (has_used_field(kInitialMap) &&
        *initial_map_->object() != f->initial_map()) {
      TRACE_BROKER_MISSING(broker, "JSFunction::initial_map");
      return false;
    }
    if (has_used_field(kInitialMapInstanceSizeWithMinSlack) &&
        initial_map_instance_size_with_min_slack_ !=
            f->ComputeInstanceSizeWithMinSlack(broker->isolate())) {
      TRACE_BROKER_MISSING(broker,
                           "JSFunction::ComputeInstanceSizeWithMinSlack");
      return false;
    }
  } else {
    DCHECK_NULL(initial_map_);
  }
  if (has_instance_prototype_) {
    if (has_used_field(kInstancePrototype) &&
        *instance_prototype_->object() != f->instance_prototype()) {
      TRACE_BROKER_MISSING(broker, "JSFunction::instance_prototype");
      return false;
    }
  } else {
    DCHECK_NULL(instance_prototype_);
  }
  if (has_used_field(kPrototypeRequiresRuntimeLookup) &&
      PrototypeRequiresRuntimeLookup_ != f->PrototypeRequiresRuntimeLookup()) {
    TRACE_BROKER_MISSING(broker, "JSFunction::PrototypeRequiresRuntimeLookup");
    return false;
  }
  if (has_used_field(kFeedbackCell) &&
      *feedback_cell_->object() != f->raw_feedback_cell()) {
    TRACE_BROKER_MISSING(broker, "JSFunction::raw_feedback_cell");
    return false;
  }
  return true;
}
References broker(), CHECK_EQ, context_, v8::internal::DCHECK(), DCHECK_NULL, feedback_cell_, has_initial_map(), has_initial_map_, has_instance_prototype_, has_used_field(), initial_map_, initial_map_instance_size_with_min_slack_, instance_prototype_, v8::kAcquireLoad, kFeedbackCell, kHasInitialMap, kHasInstancePrototype, kInitialMap, kInitialMapInstanceSizeWithMinSlack, kInstancePrototype, kPrototypeOrInitialMap, kPrototypeRequiresRuntimeLookup, v8::internal::compiler::ObjectData::object(), prototype_or_initial_map_, PrototypeRequiresRuntimeLookup_, shared_, and TRACE_BROKER_MISSING.
PrototypeRequiresRuntimeLookup()
bool v8::internal::compiler::JSFunctionData::PrototypeRequiresRuntimeLookup () const [inline]
Definition at line 460 of file heap-refs.cc.
                                              {
    DCHECK(serialized_);
    return PrototypeRequiresRuntimeLookup_;
  }
References v8::internal::DCHECK(), and PrototypeRequiresRuntimeLookup_.
raw_feedback_cell()
ObjectData* v8::internal::compiler::JSFunctionData::raw_feedback_cell () const [inline]
Definition at line 481 of file heap-refs.cc.
                                        {
    DCHECK(serialized_);
    return feedback_cell_;
  }
References v8::internal::DCHECK(), and feedback_cell_.
set_used_field()
void v8::internal::compiler::JSFunctionData::set_used_field (UsedField used_field) [inline]
Definition at line 509 of file heap-refs.cc.
{ used_fields_ |= used_field; }
References used_fields_.
Referenced by v8::internal::compiler::anonymous_namespace{heap-refs.cc}::RecordConsistentJSFunctionViewDependencyIfNeeded().
shared()
ObjectData* v8::internal::compiler::JSFunctionData::shared () const [inline]
Definition at line 477 of file heap-refs.cc.
                             {
    DCHECK(serialized_);
    return shared_;
  }
References v8::internal::DCHECK(), and shared_.
Referenced by Cache().
Member Data Documentation
context_
ObjectData* v8::internal::compiler::JSFunctionData::context_ = nullptr [private]
Definition at line 526 of file heap-refs.cc.
Referenced by Cache(), context(), and IsConsistentWithHeapState().
feedback_cell_
ObjectData* v8::internal::compiler::JSFunctionData::feedback_cell_ = nullptr [private]
Definition at line 532 of file heap-refs.cc.
Referenced by Cache(), IsConsistentWithHeapState(), and raw_feedback_cell().
has_initial_map_
bool v8::internal::compiler::JSFunctionData::has_initial_map_ = false [private]
Definition at line 522 of file heap-refs.cc.
Referenced by Cache(), has_initial_map(), and IsConsistentWithHeapState().
has_instance_prototype_
bool v8::internal::compiler::JSFunctionData::has_instance_prototype_ = false [private]
Definition at line 523 of file heap-refs.cc.
Referenced by Cache(), has_instance_prototype(), and IsConsistentWithHeapState().
initial_map_
ObjectData* v8::internal::compiler::JSFunctionData::initial_map_ [private]
Initial value:
=
      nullptr
Definition at line 527 of file heap-refs.cc.
Referenced by Cache(), initial_map(), and IsConsistentWithHeapState().
initial_map_instance_size_with_min_slack_
int v8::internal::compiler::JSFunctionData::initial_map_instance_size_with_min_slack_ [private]
Definition at line 533 of file heap-refs.cc.
Referenced by Cache(), initial_map_instance_size_with_min_slack(), and IsConsistentWithHeapState().
instance_prototype_
ObjectData* v8::internal::compiler::JSFunctionData::instance_prototype_ [private]
Initial value:
=
      nullptr
Definition at line 529 of file heap-refs.cc.
Referenced by Cache(), instance_prototype(), and IsConsistentWithHeapState().
prototype_or_initial_map_
ObjectData* v8::internal::compiler::JSFunctionData::prototype_or_initial_map_ = nullptr [private]
Definition at line 521 of file heap-refs.cc.
Referenced by Cache(), and IsConsistentWithHeapState().
PrototypeRequiresRuntimeLookup_
bool v8::internal::compiler::JSFunctionData::PrototypeRequiresRuntimeLookup_ = false [private]
Definition at line 524 of file heap-refs.cc.
Referenced by Cache(), IsConsistentWithHeapState(), and PrototypeRequiresRuntimeLookup().
shared_
ObjectData* v8::internal::compiler::JSFunctionData::shared_ = nullptr [private]
Definition at line 531 of file heap-refs.cc.
Referenced by Cache(), IsConsistentWithHeapState(), and shared().
used_fields_
UsedFields v8::internal::compiler::JSFunctionData::used_fields_ [private]
Definition at line 519 of file heap-refs.cc.
Referenced by has_any_used_field(), has_used_field(), and set_used_field().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/heap-refs.cc