cppgc::internal::ConservativeTracingVisitor Class Reference
#include <visitor.h>
Public Member Functions
ConservativeTracingVisitor (HeapBase &, PageBackend &, cppgc::Visitor &)
virtual ~ConservativeTracingVisitor ()=default
ConservativeTracingVisitor (const ConservativeTracingVisitor &)=delete
ConservativeTracingVisitor & operator= (const ConservativeTracingVisitor &)=delete
virtual void TraceConservativelyIfNeeded (const void *)
void TraceConservativelyIfNeeded (HeapObjectHeader &)
void TraceConservatively (const HeapObjectHeader &)
Protected Types
using TraceConservativelyCallback = void(ConservativeTracingVisitor *, const HeapObjectHeader &)
Protected Member Functions
virtual void VisitFullyConstructedConservatively (HeapObjectHeader &)
virtual void VisitInConstructionConservatively (HeapObjectHeader &, TraceConservativelyCallback)
void TryTracePointerConservatively (ConstAddress address)
Protected Attributes
HeapBase & heap_
PageBackend & page_backend_
cppgc::Visitor & visitor_
Detailed Description
Definition at line 49 of file visitor.h.
Member Typedef Documentation
TraceConservativelyCallback
using cppgc::internal::ConservativeTracingVisitor::TraceConservativelyCallback = void(ConservativeTracingVisitor*, const HeapObjectHeader&) [protected]
Definition at line 63 of file visitor.h.
Constructor & Destructor Documentation
ConservativeTracingVisitor() [1/2]
cppgc::internal::ConservativeTracingVisitor::ConservativeTracingVisitor (HeapBase & heap, PageBackend & page_backend, cppgc::Visitor & visitor)
Definition at line 39 of file visitor.cc.
    : heap_(heap), page_backend_(page_backend), visitor_(visitor) {}
 ConservativeTracingVisitor()
virtual cppgc::internal::ConservativeTracingVisitor::~ConservativeTracingVisitor () [virtual], [default]
ConservativeTracingVisitor() [2/2]
cppgc::internal::ConservativeTracingVisitor::ConservativeTracingVisitor (const ConservativeTracingVisitor &) [delete]
Member Function Documentation
operator=()
ConservativeTracingVisitor& cppgc::internal::ConservativeTracingVisitor::operator= (const ConservativeTracingVisitor &) [delete]
TraceConservatively()
DISABLE_ASAN void cppgc::internal::ConservativeTracingVisitor::TraceConservatively (const HeapObjectHeader & header)
Definition at line 47 of file visitor.cc.
                                    {
  const auto object_view = ObjectView<>(header);
  uintptr_t* word = reinterpret_cast<uintptr_t*>(object_view.Start());
  for (size_t i = 0; i < (object_view.Size() / sizeof(uintptr_t)); ++i) {
    uintptr_t maybe_full_ptr = word[i];
    // |object| may be uninitialized by design or just contain padding bytes.
    // Copy into a local variable that is not poisoned for conservative marking.
    // Copy into a temporary variable to maintain the original MSAN state.
    MSAN_MEMORY_IS_INITIALIZED(&maybe_full_ptr, sizeof(maybe_full_ptr));
    // Neither first OS page, nor first cage page contain Oilpan objects.
    if (maybe_full_ptr <= SentinelPointer::kSentinelValue) {
      continue;
    }
    PointerRepresentation::VisitPossiblePointers(
        reinterpret_cast<void*>(maybe_full_ptr),
        [this](const void* raw_pointer) {
          this->TraceConservativelyIfNeeded(raw_pointer);
        });
    // We must also trace full pointers here as the conservative tracing visitor
    // may be overridden to find pointers to other areas conservatively as well.
    // E.g., v8::TracedReference points into a different memory region and is
    // scanned conservatively when the GCed object is in construction. See
    // `UnifiedHeapConservativeMarkingVisitor::TraceConservativelyIfNeeded()`.
    this->TraceConservativelyIfNeeded(reinterpret_cast<void*>(maybe_full_ptr));
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, cppgc::internal::SentinelPointer::kSentinelValue, MSAN_MEMORY_IS_INITIALIZED, TraceConservativelyIfNeeded(), and cppgc::internal::RawPointer::VisitPossiblePointers().
Referenced by TraceConservativelyIfNeeded().
TraceConservativelyIfNeeded() [1/2]
void cppgc::internal::ConservativeTracingVisitor::TraceConservativelyIfNeeded (const void * address) [virtual]
Reimplemented in v8::internal::anonymous_namespace{cpp-heap.cc}::UnifiedHeapConservativeMarkingVisitor.
Definition at line 96 of file visitor.cc.
                         {
  // Neither first OS page, nor first cage page contain Oilpan objects.
  if (reinterpret_cast<ConstAddress>(address) <=
      reinterpret_cast<ConstAddress>(SentinelPointer::kSentinelValue)) {
    return;
  }
  PointerRepresentation::VisitPossiblePointers(
      address, [this](const void* raw_pointer) {
        this->TryTracePointerConservatively(
            reinterpret_cast<ConstAddress>(raw_pointer));
      });
}
References cppgc::internal::SentinelPointer::kSentinelValue, TryTracePointerConservatively(), and cppgc::internal::RawPointer::VisitPossiblePointers().
Referenced by cppgc::internal::MarkerBase::MarkNotFullyConstructedObjects(), TraceConservatively(), TryTracePointerConservatively(), cppgc::internal::MarkingVerifierBase::VisitHeapObjectHeader(), cppgc::internal::MarkingVerifierBase::VisitPointer(), and cppgc::internal::ConservativeMarkingVisitor::VisitPointer().
TraceConservativelyIfNeeded() [2/2]
void cppgc::internal::ConservativeTracingVisitor::TraceConservativelyIfNeeded (HeapObjectHeader & header)
Definition at line 110 of file visitor.cc.
                              {
  if (!header.IsInConstruction<AccessMode::kNonAtomic>()) {
    VisitFullyConstructedConservatively(header);
  } else {
    VisitInConstructionConservatively(
        header,
        [](ConservativeTracingVisitor* v, const HeapObjectHeader& header) {
          v->TraceConservatively(header);
        });
  }
}
References cppgc::internal::HeapObjectHeader::IsInConstruction(), cppgc::internal::kNonAtomic, TraceConservatively(), VisitFullyConstructedConservatively(), and VisitInConstructionConservatively().
TryTracePointerConservatively()
void cppgc::internal::ConservativeTracingVisitor::TryTracePointerConservatively (ConstAddress address) [protected]
Definition at line 75 of file visitor.cc.
                          {
#if defined(CPPGC_CAGED_HEAP)
  // TODO(chromium:1056170): Add support for SIMD in stack scanning.
  if (V8_LIKELY(!CagedHeapBase::IsWithinCage(address))) return;
#endif // defined(CPPGC_CAGED_HEAP)
  const BasePage* page =
      reinterpret_cast<const BasePage*>(page_backend_.Lookup(address));
  if (!page) {
    return;
  }
  DCHECK_EQ(&heap_, &page->heap());
  auto* header = const_cast<HeapObjectHeader*>(
      page->TryObjectHeaderFromInnerAddress(address));
  if (!header) {
    return;
  }
  TraceConservativelyIfNeeded(*header);
}
References DCHECK_EQ, cppgc::internal::BasePage::heap(), heap_, cppgc::internal::PageBackend::Lookup(), page_backend_, TraceConservativelyIfNeeded(), cppgc::internal::BasePage::TryObjectHeaderFromInnerAddress(), and V8_LIKELY.
Referenced by TraceConservativelyIfNeeded().
VisitFullyConstructedConservatively()
void cppgc::internal::ConservativeTracingVisitor::VisitFullyConstructedConservatively (HeapObjectHeader & header) [protected], [virtual]
Reimplemented in v8::internal::anonymous_namespace{cpp-snapshot.cc}::GraphBuildingStackVisitor, and cppgc::internal::ConservativeMarkingVisitor.
Definition at line 123 of file visitor.cc.
                              {
  visitor_.Visit(
      header.ObjectStart(),
      {header.ObjectStart(),
       GlobalGCInfoTable::GCInfoFromIndex(header.GetGCInfoIndex()).trace});
}
References cppgc::internal::HeapObjectHeader::ObjectStart(), cppgc::Visitor::Visit(), and visitor_.
Referenced by TraceConservativelyIfNeeded(), and cppgc::internal::ConservativeMarkingVisitor::VisitFullyConstructedConservatively().
VisitInConstructionConservatively()
virtual void cppgc::internal::ConservativeTracingVisitor::VisitInConstructionConservatively (HeapObjectHeader & , TraceConservativelyCallback) [inline], [protected], [virtual]
Reimplemented in v8::internal::anonymous_namespace{cpp-snapshot.cc}::GraphBuildingStackVisitor, cppgc::internal::ConservativeMarkingVisitor, and cppgc::internal::MarkingVerifierBase.
Definition at line 66 of file visitor.h.
                                                                              {}
Referenced by TraceConservativelyIfNeeded().
Member Data Documentation
heap_
HeapBase& cppgc::internal::ConservativeTracingVisitor::heap_ [protected]
Definition at line 71 of file visitor.h.
Referenced by cppgc::internal::MarkingVerifierBase::ReportDifferences(), cppgc::internal::MarkingVerifierBase::Run(), TryTracePointerConservatively(), and cppgc::internal::ConservativeMarkingVisitor::VisitInConstructionConservatively().
page_backend_
PageBackend& cppgc::internal::ConservativeTracingVisitor::page_backend_ [protected]
Definition at line 72 of file visitor.h.
Referenced by TryTracePointerConservatively().
visitor_
cppgc::Visitor& cppgc::internal::ConservativeTracingVisitor::visitor_ [protected]
Definition at line 73 of file visitor.h.
Referenced by VisitFullyConstructedConservatively(), and cppgc::internal::ConservativeMarkingVisitor::VisitFullyConstructedConservatively().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/visitor.h
/mnt/V8SourceCode/src/heap/cppgc/visitor.cc