v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler Class Reference
Public Member Functions
AsyncGeneratorBuiltinsAssembler (CodeAssemblerState *state)
TNode< Smi > LoadGeneratorState (const TNode< JSGeneratorObject > generator)
TNode< BoolT > IsGeneratorStateClosed (const TNode< Smi > state)
TNode< BoolT > IsGeneratorClosed (const TNode< JSGeneratorObject > generator)
TNode< BoolT > IsGeneratorStateSuspended (const TNode< Smi > state)
TNode< BoolT > IsGeneratorSuspended (const TNode< JSGeneratorObject > generator)
TNode< BoolT > IsGeneratorStateSuspendedAtStart (const TNode< Smi > state)
TNode< BoolT > IsGeneratorStateNotExecuting (const TNode< Smi > state)
TNode< BoolT > IsGeneratorNotExecuting (const TNode< JSGeneratorObject > generator)
TNode< BoolT > IsGeneratorAwaiting (const TNode< JSGeneratorObject > generator)
void SetGeneratorAwaiting (const TNode< JSGeneratorObject > generator)
void SetGeneratorNotAwaiting (const TNode< JSGeneratorObject > generator)
void CloseGenerator (const TNode< JSGeneratorObject > generator)
TNode< HeapObject > LoadFirstAsyncGeneratorRequestFromQueue (const TNode< JSGeneratorObject > generator)
TNode< Smi > LoadResumeTypeFromAsyncGeneratorRequest (const TNode< AsyncGeneratorRequest > request)
TNode< JSPromise > LoadPromiseFromAsyncGeneratorRequest (const TNode< AsyncGeneratorRequest > request)
TNode< Object > LoadValueFromAsyncGeneratorRequest (const TNode< AsyncGeneratorRequest > request)
TNode< BoolT > IsAbruptResumeType (const TNode< Smi > resume_type)
void AsyncGeneratorEnqueue (CodeStubArguments *args, TNode< Context > context, TNode< Object > receiver, TNode< Object > value, JSAsyncGeneratorObject::ResumeMode resume_mode, const char *method_name)
TNode< AsyncGeneratorRequest > TakeFirstAsyncGeneratorRequestFromQueue (TNode< JSAsyncGeneratorObject > generator)
void AddAsyncGeneratorRequestToQueue (TNode< JSAsyncGeneratorObject > generator, TNode< AsyncGeneratorRequest > request)
TNode< AsyncGeneratorRequest > AllocateAsyncGeneratorRequest (JSAsyncGeneratorObject::ResumeMode resume_mode, TNode< Object > resume_value, TNode< JSPromise > promise)
template<typename Descriptor >
void AsyncGeneratorAwait ()
void AsyncGeneratorAwaitResume (TNode< Context > context, TNode< JSAsyncGeneratorObject > async_generator_object, TNode< Object > value, JSAsyncGeneratorObject::ResumeMode resume_mode)
void AsyncGeneratorAwaitResumeClosure (TNode< Context > context, TNode< Object > value, JSAsyncGeneratorObject::ResumeMode resume_mode)
void AsyncGeneratorReturnClosedReject (TNode< Context > context, TNode< JSAsyncGeneratorObject > async_generator_object, TNode< Object > value)
Additional Inherited Members
Detailed Description
Definition at line 20 of file builtins-async-generator-gen.cc.
Constructor & Destructor Documentation
AsyncGeneratorBuiltinsAssembler()
v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::AsyncGeneratorBuiltinsAssembler (CodeAssemblerState * state) [inline], [explicit]
Definition at line 22 of file builtins-async-generator-gen.cc.
      : AsyncBuiltinsAssembler(state) {}
Member Function Documentation
AddAsyncGeneratorRequestToQueue()
void v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::AddAsyncGeneratorRequestToQueue (TNode< JSAsyncGeneratorObject > generator, TNode< AsyncGeneratorRequest > request)
Definition at line 269 of file builtins-async-generator-gen.cc.
                                          {
  TVARIABLE(HeapObject, var_current);
  Label empty(this), loop(this, &var_current), done(this);
  var_current = LoadObjectField<HeapObject>(
      generator, JSAsyncGeneratorObject::kQueueOffset);
  Branch(IsUndefined(var_current.value()), &empty, &loop);
  BIND(&empty);
  {
    StoreObjectField(generator, JSAsyncGeneratorObject::kQueueOffset, request);
    Goto(&done);
  }
  BIND(&loop);
  {
    Label loop_next(this), next_empty(this);
    TNode<AsyncGeneratorRequest> current = CAST(var_current.value());
    TNode<HeapObject> next = LoadObjectField<HeapObject>(
        current, AsyncGeneratorRequest::kNextOffset);
    Branch(IsUndefined(next), &next_empty, &loop_next);
    BIND(&next_empty);
    {
      StoreObjectField(current, AsyncGeneratorRequest::kNextOffset, request);
      Goto(&done);
    }
    BIND(&loop_next);
    {
      var_current = next;
      Goto(&loop);
    }
  }
  BIND(&done);
}
References CAST.
AllocateAsyncGeneratorRequest()
TNode< AsyncGeneratorRequest > v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::AllocateAsyncGeneratorRequest (JSAsyncGeneratorObject::ResumeMode resume_mode, TNode< Object > resume_value, TNode< JSPromise > promise)
Definition at line 201 of file builtins-async-generator-gen.cc.
                              {
  TNode<HeapObject> request = Allocate(AsyncGeneratorRequest::kSize);
  StoreMapNoWriteBarrier(request, RootIndex::kAsyncGeneratorRequestMap);
  StoreObjectFieldNoWriteBarrier(request, AsyncGeneratorRequest::kNextOffset,
                                 UndefinedConstant());
  StoreObjectFieldNoWriteBarrier(request,
                                 AsyncGeneratorRequest::kResumeModeOffset,
                                 SmiConstant(resume_mode));
  StoreObjectFieldNoWriteBarrier(request, AsyncGeneratorRequest::kValueOffset,
                                 resume_value);
  StoreObjectFieldNoWriteBarrier(request, AsyncGeneratorRequest::kPromiseOffset,
                                 promise);
  StoreObjectFieldRoot(request, AsyncGeneratorRequest::kNextOffset,
                       RootIndex::kUndefinedValue);
  return CAST(request);
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), CAST, and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
AsyncGeneratorAwait()
template<typename Descriptor >
void v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::AsyncGeneratorAwait
Definition at line 251 of file builtins-async-generator-gen.cc.
                                                          {
  auto async_generator_object =
      Parameter<JSAsyncGeneratorObject>(Descriptor::kAsyncGeneratorObject);
  auto value = Parameter<JSAny>(Descriptor::kValue);
  auto context = Parameter<Context>(Descriptor::kContext);
  TNode<AsyncGeneratorRequest> request =
      CAST(LoadFirstAsyncGeneratorRequestFromQueue(async_generator_object));
  TNode<JSPromise> outer_promise = LoadObjectField<JSPromise>(
      request, AsyncGeneratorRequest::kPromiseOffset);
  Await(context, async_generator_object, value, outer_promise,
        RootIndex::kAsyncGeneratorAwaitResolveClosureSharedFun,
        RootIndex::kAsyncGeneratorAwaitRejectClosureSharedFun);
  SetGeneratorAwaiting(async_generator_object);
  Return(UndefinedConstant());
}
References CAST, v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::value.
AsyncGeneratorAwaitResume()
void v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::AsyncGeneratorAwaitResume (TNode< Context > context, TNode< JSAsyncGeneratorObject > async_generator_object, TNode< Object > value, JSAsyncGeneratorObject::ResumeMode resume_mode)
Definition at line 220 of file builtins-async-generator-gen.cc.
                                                  {
  SetGeneratorNotAwaiting(async_generator_object);
  CSA_SLOW_DCHECK(this, IsGeneratorSuspended(async_generator_object));
  // Remember the {resume_mode} for the {async_generator_object}.
  StoreObjectFieldNoWriteBarrier(async_generator_object,
                                 JSGeneratorObject::kResumeModeOffset,
                                 SmiConstant(resume_mode));
  CallBuiltin(Builtin::kResumeGeneratorTrampoline, context, value,
              async_generator_object);
  TailCallBuiltin(Builtin::kAsyncGeneratorResumeNext, context,
                  async_generator_object);
}
References v8::internal::value.
AsyncGeneratorAwaitResumeClosure()
void v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::AsyncGeneratorAwaitResumeClosure (TNode< Context > context, TNode< Object > value, JSAsyncGeneratorObject::ResumeMode resume_mode)
Definition at line 240 of file builtins-async-generator-gen.cc.
                                                  {
  const TNode<JSAsyncGeneratorObject> async_generator_object =
      CAST(LoadContextElementNoCell(context, Context::EXTENSION_INDEX));
  AsyncGeneratorAwaitResume(context, async_generator_object, value,
                            resume_mode);
}
References CAST, v8::internal::Context::EXTENSION_INDEX, and v8::internal::value.
AsyncGeneratorEnqueue()
void v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::AsyncGeneratorEnqueue (CodeStubArguments * args, TNode< Context > context, TNode< Object > receiver, TNode< Object > value, JSAsyncGeneratorObject::ResumeMode resume_mode, const char * method_name)
Definition at line 149 of file builtins-async-generator-gen.cc.
                             {
  // AsyncGeneratorEnqueue produces a new Promise, and appends it to the list
  // of async generator requests to be executed. If the generator is not
  // presently executing, then this method will loop through, processing each
  // request from front to back.
  // This loop resides in AsyncGeneratorResumeNext.
  TNode<JSPromise> promise = NewJSPromise(context);
  Label if_receiverisincompatible(this, Label::kDeferred);
  GotoIf(TaggedIsSmi(receiver), &if_receiverisincompatible);
  GotoIfNot(HasInstanceType(CAST(receiver), JS_ASYNC_GENERATOR_OBJECT_TYPE),
            &if_receiverisincompatible);
  {
    Label done(this);
    const TNode<JSAsyncGeneratorObject> generator = CAST(receiver);
    const TNode<AsyncGeneratorRequest> req =
        AllocateAsyncGeneratorRequest(resume_mode, value, promise);
    AddAsyncGeneratorRequestToQueue(generator, req);
    // Let state be generator.[[AsyncGeneratorState]]
    // If state is not "executing", then
    // Perform AsyncGeneratorResumeNext(Generator)
    // Check if the {receiver} is running or already closed.
    TNode<Smi> continuation = LoadGeneratorState(generator);
    GotoIf(SmiEqual(continuation,
                    SmiConstant(JSAsyncGeneratorObject::kGeneratorExecuting)),
           &done);
    CallBuiltin(Builtin::kAsyncGeneratorResumeNext, context, generator);
    Goto(&done);
    BIND(&done);
    args->PopAndReturn(promise);
  }
  BIND(&if_receiverisincompatible);
  {
    CallBuiltin(Builtin::kRejectPromise, context, promise,
                MakeTypeError(MessageTemplate::kIncompatibleMethodReceiver,
                              context, StringConstant(method_name), receiver),
                TrueConstant());
    args->PopAndReturn(promise);
  }
}
References v8::base::args, CAST, and v8::internal::value.
AsyncGeneratorReturnClosedReject()
void v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::AsyncGeneratorReturnClosedReject (TNode< Context > context, TNode< JSAsyncGeneratorObject > async_generator_object, TNode< Object > value)
Definition at line 323 of file builtins-async-generator-gen.cc.
                         {
  SetGeneratorNotAwaiting(generator);
  // https://tc39.github.io/proposal-async-iteration/
  // #async-generator-resume-next-return-processor-rejected step 2:
  // Return ! AsyncGeneratorReject(_F_.[[Generator]], _reason_).
  CallBuiltin(Builtin::kAsyncGeneratorReject, context, generator, value);
  TailCallBuiltin(Builtin::kAsyncGeneratorResumeNext, context, generator);
}
References v8::internal::value.
CloseGenerator()
void v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::CloseGenerator (const TNode< JSGeneratorObject > generator) [inline]
Definition at line 83 of file builtins-async-generator-gen.cc.
                                                                       {
    StoreObjectFieldNoWriteBarrier(
        generator, JSGeneratorObject::kContinuationOffset,
        SmiConstant(JSGeneratorObject::kGeneratorClosed));
  }
References v8::internal::JSGeneratorObject::kGeneratorClosed.
IsAbruptResumeType()
TNode<BoolT> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::IsAbruptResumeType (const TNode< Smi > resume_type) [inline]
Definition at line 112 of file builtins-async-generator-gen.cc.
                                                                       {
    return SmiNotEqual(resume_type, SmiConstant(JSGeneratorObject::kNext));
  }
References v8::internal::JSGeneratorObject::kNext.
IsGeneratorAwaiting()
TNode<BoolT> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::IsGeneratorAwaiting (const TNode< JSGeneratorObject > generator) [inline]
Definition at line 61 of file builtins-async-generator-gen.cc.
                                                {
    TNode<Object> is_generator_awaiting =
        LoadObjectField(generator, JSAsyncGeneratorObject::kIsAwaitingOffset);
    return TaggedEqual(is_generator_awaiting, SmiConstant(1));
  }
IsGeneratorClosed()
TNode<BoolT> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::IsGeneratorClosed (const TNode< JSGeneratorObject > generator) [inline]
Definition at line 34 of file builtins-async-generator-gen.cc.
                                                {
    return IsGeneratorStateClosed(LoadGeneratorState(generator));
  }
IsGeneratorNotExecuting()
TNode<BoolT> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::IsGeneratorNotExecuting (const TNode< JSGeneratorObject > generator) [inline]
Definition at line 56 of file builtins-async-generator-gen.cc.
                                                {
    return IsGeneratorStateNotExecuting(LoadGeneratorState(generator));
  }
IsGeneratorStateClosed()
TNode<BoolT> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::IsGeneratorStateClosed (const TNode< Smi > state) [inline]
Definition at line 31 of file builtins-async-generator-gen.cc.
                                                                     {
    return SmiEqual(state, SmiConstant(JSGeneratorObject::kGeneratorClosed));
  }
References v8::internal::JSGeneratorObject::kGeneratorClosed.
IsGeneratorStateNotExecuting()
TNode<BoolT> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::IsGeneratorStateNotExecuting (const TNode< Smi > state) [inline]
Definition at line 52 of file builtins-async-generator-gen.cc.
                                                                           {
    return SmiNotEqual(state,
                       SmiConstant(JSGeneratorObject::kGeneratorExecuting));
  }
References v8::internal::JSGeneratorObject::kGeneratorExecuting.
IsGeneratorStateSuspended()
TNode<BoolT> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::IsGeneratorStateSuspended (const TNode< Smi > state) [inline]
Definition at line 39 of file builtins-async-generator-gen.cc.
                                                                        {
    return SmiGreaterThanOrEqual(state, SmiConstant(0));
  }
IsGeneratorStateSuspendedAtStart()
TNode<BoolT> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::IsGeneratorStateSuspendedAtStart (const TNode< Smi > state) [inline]
Definition at line 48 of file builtins-async-generator-gen.cc.
                                                                               {
    return SmiEqual(state, SmiConstant(0));
  }
IsGeneratorSuspended()
TNode<BoolT> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::IsGeneratorSuspended (const TNode< JSGeneratorObject > generator) [inline]
Definition at line 43 of file builtins-async-generator-gen.cc.
                                                {
    return IsGeneratorStateSuspended(LoadGeneratorState(generator));
  }
LoadFirstAsyncGeneratorRequestFromQueue()
TNode<HeapObject> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::LoadFirstAsyncGeneratorRequestFromQueue (const TNode< JSGeneratorObject > generator) [inline]
Definition at line 89 of file builtins-async-generator-gen.cc.
                                                {
    return LoadObjectField<HeapObject>(generator,
                                       JSAsyncGeneratorObject::kQueueOffset);
  }
LoadGeneratorState()
TNode<Smi> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::LoadGeneratorState (const TNode< JSGeneratorObject > generator) [inline]
Definition at line 25 of file builtins-async-generator-gen.cc.
                                                {
    return LoadObjectField<Smi>(generator,
                                JSGeneratorObject::kContinuationOffset);
  }
LoadPromiseFromAsyncGeneratorRequest()
TNode<JSPromise> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::LoadPromiseFromAsyncGeneratorRequest (const TNode< AsyncGeneratorRequest > request) [inline]
Definition at line 101 of file builtins-async-generator-gen.cc.
                                                  {
    return LoadObjectField<JSPromise>(request,
                                      AsyncGeneratorRequest::kPromiseOffset);
  }
LoadResumeTypeFromAsyncGeneratorRequest()
TNode<Smi> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::LoadResumeTypeFromAsyncGeneratorRequest (const TNode< AsyncGeneratorRequest > request) [inline]
Definition at line 95 of file builtins-async-generator-gen.cc.
                                                  {
    return LoadObjectField<Smi>(request,
                                AsyncGeneratorRequest::kResumeModeOffset);
  }
LoadValueFromAsyncGeneratorRequest()
TNode<Object> v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::LoadValueFromAsyncGeneratorRequest (const TNode< AsyncGeneratorRequest > request) [inline]
Definition at line 107 of file builtins-async-generator-gen.cc.
                                                  {
    return LoadObjectField(request, AsyncGeneratorRequest::kValueOffset);
  }
SetGeneratorAwaiting()
void v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::SetGeneratorAwaiting (const TNode< JSGeneratorObject > generator) [inline]
Definition at line 68 of file builtins-async-generator-gen.cc.
                                                                             {
    CSA_DCHECK(this, Word32BinaryNot(IsGeneratorAwaiting(generator)));
    StoreObjectFieldNoWriteBarrier(
        generator, JSAsyncGeneratorObject::kIsAwaitingOffset, SmiConstant(1));
    CSA_DCHECK(this, IsGeneratorAwaiting(generator));
  }
SetGeneratorNotAwaiting()
void v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::SetGeneratorNotAwaiting (const TNode< JSGeneratorObject > generator) [inline]
Definition at line 75 of file builtins-async-generator-gen.cc.
                                                {
    CSA_DCHECK(this, IsGeneratorAwaiting(generator));
    StoreObjectFieldNoWriteBarrier(
        generator, JSAsyncGeneratorObject::kIsAwaitingOffset, SmiConstant(0));
    CSA_DCHECK(this, Word32BinaryNot(IsGeneratorAwaiting(generator)));
  }
TakeFirstAsyncGeneratorRequestFromQueue()
TNode< AsyncGeneratorRequest > v8::internal::anonymous_namespace{builtins-async-generator-gen.cc}::AsyncGeneratorBuiltinsAssembler::TakeFirstAsyncGeneratorRequestFromQueue (TNode< JSAsyncGeneratorObject > generator)
Definition at line 309 of file builtins-async-generator-gen.cc.
                                             {
  // Removes and returns the first AsyncGeneratorRequest from a
  // JSAsyncGeneratorObject's queue. Asserts that the queue is not empty.
  TNode<AsyncGeneratorRequest> request = LoadObjectField<AsyncGeneratorRequest>(
      generator, JSAsyncGeneratorObject::kQueueOffset);
  TNode<Object> next =
      LoadObjectField(request, AsyncGeneratorRequest::kNextOffset);
  StoreObjectField(generator, JSAsyncGeneratorObject::kQueueOffset, next);
  return request;
}
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-async-generator-gen.cc