v8::internal::WasmScript Class Reference
#include <wasm-objects.h>
Static Public Member Functions
static V8_EXPORT_PRIVATE bool SetBreakPoint (DirectHandle< Script >, int *position, DirectHandle< BreakPoint > break_point)
static V8_EXPORT_PRIVATE void SetInstrumentationBreakpoint (DirectHandle< Script >, DirectHandle< BreakPoint > break_point)
static V8_EXPORT_PRIVATE bool SetBreakPointOnFirstBreakableForFunction (DirectHandle< Script >, int function_index, DirectHandle< BreakPoint > break_point)
static V8_EXPORT_PRIVATE bool SetBreakPointForFunction (DirectHandle< Script >, int function_index, int breakable_offset, DirectHandle< BreakPoint > break_point)
static V8_EXPORT_PRIVATE bool ClearBreakPoint (DirectHandle< Script >, int position, DirectHandle< BreakPoint > break_point)
static V8_EXPORT_PRIVATE bool ClearBreakPointById (DirectHandle< Script >, int breakpoint_id)
static void ClearAllBreakpoints (Tagged< Script >)
static V8_EXPORT_PRIVATE bool GetPossibleBreakpoints (wasm::NativeModule *native_module, const debug::Location &start, const debug::Location &end, std::vector< debug::BreakLocation > *locations)
static MaybeDirectHandle< FixedArray > CheckBreakPoints (Isolate *, DirectHandle< Script >, int position, StackFrameId stack_frame_id)
Static Public Attributes
static constexpr int kOnEntryBreakpointPosition = -1
Static Private Member Functions
static void AddBreakpointToInfo (DirectHandle< Script >, int position, DirectHandle< BreakPoint > break_point)
Detailed Description
Definition at line 1282 of file wasm-objects.h.
Member Function Documentation
AddBreakpointToInfo()
void v8::internal::WasmScript::AddBreakpointToInfo (DirectHandle< Script > script, int position, DirectHandle< BreakPoint > break_point) [static], [private]
Definition at line 1126 of file wasm-debug.cc.
                                                                           {
  Isolate* isolate = Isolate::Current();
  DirectHandle<FixedArray> breakpoint_infos;
  if (script->has_wasm_breakpoint_infos()) {
    breakpoint_infos = direct_handle(script->wasm_breakpoint_infos(), isolate);
  } else {
    breakpoint_infos =
        isolate->factory()->NewFixedArray(4, AllocationType::kOld);
    script->set_wasm_breakpoint_infos(*breakpoint_infos);
  }
  int insert_pos =
      FindBreakpointInfoInsertPos(isolate, breakpoint_infos, position);
  // If a BreakPointInfo object already exists for this position, add the new
  // breakpoint object and return.
  if (insert_pos < breakpoint_infos->length() &&
      GetBreakpointPos(isolate, breakpoint_infos->get(insert_pos)) ==
          position) {
    DirectHandle<BreakPointInfo> old_info(
        Cast<BreakPointInfo>(breakpoint_infos->get(insert_pos)), isolate);
    BreakPointInfo::SetBreakPoint(isolate, old_info, break_point);
    return;
  }
  // Enlarge break positions array if necessary.
  bool need_realloc = !IsUndefined(
      breakpoint_infos->get(breakpoint_infos->length() - 1), isolate);
  DirectHandle<FixedArray> new_breakpoint_infos = breakpoint_infos;
  if (need_realloc) {
    new_breakpoint_infos = isolate->factory()->NewFixedArray(
        2 * breakpoint_infos->length(), AllocationType::kOld);
    script->set_wasm_breakpoint_infos(*new_breakpoint_infos);
    // Copy over the entries [0, insert_pos).
    for (int i = 0; i < insert_pos; ++i)
      new_breakpoint_infos->set(i, breakpoint_infos->get(i));
  }
  // Move elements [insert_pos, ...] up by one.
  for (int i = breakpoint_infos->length() - 1; i >= insert_pos; --i) {
    Tagged<Object> entry = breakpoint_infos->get(i);
    if (IsUndefined(entry, isolate)) continue;
    new_breakpoint_infos->set(i + 1, entry);
  }
  // Generate new BreakpointInfo.
  DirectHandle<BreakPointInfo> breakpoint_info =
      isolate->factory()->NewBreakPointInfo(position);
  BreakPointInfo::SetBreakPoint(isolate, breakpoint_info, break_point);
  // Now insert new position at insert_pos.
  new_breakpoint_infos->set(insert_pos, *breakpoint_info);
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindBreakpointInfoInsertPos(), v8::internal::anonymous_namespace{wasm-debug.cc}::GetBreakpointPos(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kOld, v8::internal::length, v8::internal::Factory::NewBreakPointInfo(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::script, and v8::internal::BreakPointInfo::SetBreakPoint().
Referenced by SetBreakPointForFunction(), and SetInstrumentationBreakpoint().
CheckBreakPoints()
MaybeDirectHandle< FixedArray > v8::internal::WasmScript::CheckBreakPoints (Isolate * isolate, DirectHandle< Script > script, int position, StackFrameId stack_frame_id) [static]
Definition at line 1273 of file wasm-debug.cc.
                           {
  if (!script->has_wasm_breakpoint_infos()) return {};
  DirectHandle<FixedArray> breakpoint_infos(script->wasm_breakpoint_infos(),
                                            isolate);
  int insert_pos =
      FindBreakpointInfoInsertPos(isolate, breakpoint_infos, position);
  if (insert_pos >= breakpoint_infos->length()) return {};
  DirectHandle<Object> maybe_breakpoint_info(breakpoint_infos->get(insert_pos),
                                             isolate);
  if (IsUndefined(*maybe_breakpoint_info, isolate)) return {};
  auto breakpoint_info = Cast<BreakPointInfo>(maybe_breakpoint_info);
  if (breakpoint_info->source_position() != position) return {};
  DirectHandle<Object> break_points(breakpoint_info->break_points(), isolate);
  if (!IsFixedArray(*break_points)) {
    if (!CheckBreakPoint(isolate, Cast<BreakPoint>(break_points), frame_id)) {
      // A breakpoint that doesn't break mutes traps. (Rule enables the
      // "Never Pause Here" feature.)
      isolate->debug()->SetMutedWasmLocation(script, position);
      return {};
    }
    // If breakpoint does fire, clear any prior muting behavior.
    isolate->debug()->ClearMutedLocation();
    DirectHandle<FixedArray> break_points_hit =
        isolate->factory()->NewFixedArray(1);
    break_points_hit->set(0, *break_points);
    return break_points_hit;
  }
  auto array = Cast<FixedArray>(break_points);
  DirectHandle<FixedArray> break_points_hit =
      isolate->factory()->NewFixedArray(array->length());
  int break_points_hit_count = 0;
  for (int i = 0; i < array->length(); ++i) {
    DirectHandle<BreakPoint> break_point(Cast<BreakPoint>(array->get(i)),
                                         isolate);
    if (CheckBreakPoint(isolate, break_point, frame_id)) {
      break_points_hit->set(break_points_hit_count++, *break_point);
    }
  }
  if (break_points_hit_count == 0) return {};
  break_points_hit->RightTrim(isolate, break_points_hit_count);
  return break_points_hit;
}
References v8::internal::anonymous_namespace{wasm-debug.cc}::CheckBreakPoint(), v8::internal::Debug::ClearMutedLocation(), v8::internal::Isolate::debug(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindBreakpointInfoInsertPos(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::FactoryBase< Impl >::NewFixedArray(), and v8::internal::script.
Referenced by v8::internal::anonymous_namespace{runtime-wasm.cc}::ExecuteWasmDebugBreaks().
ClearAllBreakpoints()
void v8::internal::WasmScript::ClearAllBreakpoints (Tagged< Script > script) [static]
Definition at line 1119 of file wasm-debug.cc.
                                                          {
  script->set_wasm_breakpoint_infos(
      ReadOnlyRoots(Isolate::Current()).empty_fixed_array());
  SetBreakOnEntryFlag(script, false);
}
References v8::internal::Isolate::Current(), v8::internal::script, and v8::internal::anonymous_namespace{wasm-debug.cc}::SetBreakOnEntryFlag().
Referenced by v8::internal::Debug::ClearAllBreakPoints().
ClearBreakPoint()
bool v8::internal::WasmScript::ClearBreakPoint (DirectHandle< Script > script, int position, DirectHandle< BreakPoint > break_point) [static]
Definition at line 1042 of file wasm-debug.cc.
                                                                       {
  if (!script->has_wasm_breakpoint_infos()) return false;
  Isolate* isolate = Isolate::Current();
  DirectHandle<FixedArray> breakpoint_infos(script->wasm_breakpoint_infos(),
                                            isolate);
  int pos = FindBreakpointInfoInsertPos(isolate, breakpoint_infos, position);
  // Does a BreakPointInfo object already exist for this position?
  if (pos == breakpoint_infos->length()) return false;
  DirectHandle<BreakPointInfo> info(
      Cast<BreakPointInfo>(breakpoint_infos->get(pos)), isolate);
  BreakPointInfo::ClearBreakPoint(isolate, info, break_point);
  // Check if there are no more breakpoints at this location.
  if (info->GetBreakPointCount(isolate) == 0) {
    // Update array by moving breakpoints up one position.
    for (int i = pos; i < breakpoint_infos->length() - 1; i++) {
      Tagged<Object> entry = breakpoint_infos->get(i + 1);
      breakpoint_infos->set(i, entry);
      if (IsUndefined(entry, isolate)) break;
    }
    // Make sure last array element is empty as a result.
    breakpoint_infos->set(breakpoint_infos->length() - 1,
                          ReadOnlyRoots{isolate}.undefined_value(),
                          SKIP_WRITE_BARRIER);
  }
  if (break_point->id() == v8::internal::Debug::kInstrumentationId) {
    // Special handling for instrumentation breakpoints.
    SetBreakOnEntryFlag(*script, false);
  } else {
    // Remove the breakpoint from DebugInfo and recompile.
    wasm::NativeModule* native_module = script->wasm_native_module();
    const wasm::WasmModule* module = native_module->module();
    int func_index = GetContainingWasmFunction(module, position);
    native_module->GetDebugInfo()->RemoveBreakpoint(func_index, position,
                                                    isolate);
  }
  return true;
}
References v8::internal::BreakPointInfo::ClearBreakPoint(), v8::internal::Isolate::Current(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindBreakpointInfoInsertPos(), v8::internal::wasm::GetContainingWasmFunction(), v8::internal::wasm::NativeModule::GetDebugInfo(), v8::internal::Debug::kInstrumentationId, v8::internal::wasm::NativeModule::module(), v8::internal::wasm::DebugInfo::RemoveBreakpoint(), v8::internal::script, v8::internal::anonymous_namespace{wasm-debug.cc}::SetBreakOnEntryFlag(), and v8::internal::SKIP_WRITE_BARRIER.
Referenced by ClearBreakPointById().
ClearBreakPointById()
bool v8::internal::WasmScript::ClearBreakPointById (DirectHandle< Script > script, int breakpoint_id) [static]
Definition at line 1089 of file wasm-debug.cc.
                                                        {
  if (!script->has_wasm_breakpoint_infos()) {
    return false;
  }
  Isolate* isolate = Isolate::Current();
  DirectHandle<FixedArray> breakpoint_infos(script->wasm_breakpoint_infos(),
                                            isolate);
  // If the array exists, it should not be empty.
  DCHECK_LT(0, breakpoint_infos->length());
  for (int i = 0, e = breakpoint_infos->length(); i < e; ++i) {
    DirectHandle<Object> obj(breakpoint_infos->get(i), isolate);
    if (IsUndefined(*obj, isolate)) {
      continue;
    }
    auto breakpoint_info = Cast<BreakPointInfo>(obj);
    DirectHandle<BreakPoint> breakpoint;
    if (BreakPointInfo::GetBreakPointById(isolate, breakpoint_info,
                                          breakpoint_id)
            .ToHandle(&breakpoint)) {
      DCHECK(breakpoint->id() == breakpoint_id);
      return WasmScript::ClearBreakPoint(
          script, breakpoint_info->source_position(), breakpoint);
    }
  }
  return false;
}
References ClearBreakPoint(), v8::internal::Isolate::Current(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::BreakPointInfo::GetBreakPointById(), v8::internal::script, and v8::anonymous_namespace{api.cc}::ToHandle().
GetPossibleBreakpoints()
bool v8::internal::WasmScript::GetPossibleBreakpoints (wasm::NativeModule * native_module, const debug::Location & start, const debug::Location & end, std::vector< debug::BreakLocation > * locations) [static]
Definition at line 1182 of file wasm-debug.cc.
                                                {
  DisallowGarbageCollection no_gc;
  const wasm::WasmModule* module = native_module->module();
  const std::vector<wasm::WasmFunction>& functions = module->functions;
  if (start.GetLineNumber() != 0 || start.GetColumnNumber() < 0 ||
      (!end.IsEmpty() &&
       (end.GetLineNumber() != 0 || end.GetColumnNumber() < 0 ||
        end.GetColumnNumber() < start.GetColumnNumber())))
    return false;
  // start_func_index, start_offset and end_func_index is inclusive.
  // end_offset is exclusive.
  // start_offset and end_offset are module-relative byte offsets.
  // We set strict to false because offsets may be between functions.
  int start_func_index =
      GetNearestWasmFunction(module, start.GetColumnNumber());
  if (start_func_index < 0) return false;
  uint32_t start_offset = start.GetColumnNumber();
  int end_func_index;
  uint32_t end_offset;
  if (end.IsEmpty()) {
    // Default: everything till the end of the Script.
    end_func_index = static_cast<uint32_t>(functions.size() - 1);
    end_offset = functions[end_func_index].code.end_offset();
  } else {
    // If end is specified: Use it and check for valid input.
    end_offset = end.GetColumnNumber();
    end_func_index = GetNearestWasmFunction(module, end_offset);
    DCHECK_GE(end_func_index, start_func_index);
  }
  if (start_func_index == end_func_index &&
      start_offset > functions[end_func_index].code.end_offset())
    return false;
  Zone zone{wasm::GetWasmEngine()->allocator(), ZONE_NAME};
  const uint8_t* module_start = native_module->wire_bytes().begin();
  for (int func_idx = start_func_index; func_idx <= end_func_index;
       ++func_idx) {
    const wasm::WasmFunction& func = functions[func_idx];
    if (func.code.length() == 0) continue;
    wasm::BodyLocalDecls locals;
    wasm::BytecodeIterator iterator(module_start + func.code.offset(),
                                    module_start + func.code.end_offset(),
                                    &locals, &zone);
    DCHECK_LT(0u, locals.encoded_size);
    for (; iterator.has_next(); iterator.next()) {
      uint32_t total_offset = func.code.offset() + iterator.pc_offset();
      if (total_offset >= end_offset) {
        DCHECK_EQ(end_func_index, func_idx);
        break;
      }
      if (total_offset < start_offset) continue;
      if (!wasm::WasmOpcodes::IsBreakable(iterator.current())) continue;
      locations->emplace_back(0, total_offset, debug::kCommonBreakLocation);
    }
  }
  return true;
}
References v8::internal::wasm::WasmEngine::allocator(), v8::base::Vector< T >::begin(), code, v8::internal::wasm::WasmFunction::code, v8::internal::wasm::BytecodeIterator::current(), DCHECK_EQ, DCHECK_GE, DCHECK_LT, v8::internal::wasm::BodyLocalDecls::encoded_size, v8::internal::compiler::end(), v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::wasm::WasmModule::functions, v8::debug::Location::GetColumnNumber(), v8::debug::Location::GetLineNumber(), v8::internal::wasm::GetNearestWasmFunction(), v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::BytecodeIterator::has_next(), v8::internal::wasm::WasmOpcodes::IsBreakable(), v8::debug::kCommonBreakLocation, v8::internal::wasm::WireBytesRef::length(), v8::internal::wasm::NativeModule::module(), v8::internal::wasm::BytecodeIterator::next(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::wasm::WireBytesRef::offset(), v8::internal::wasm::NativeModule::wire_bytes(), and ZONE_NAME.
Referenced by v8::debug::Script::GetPossibleBreakpoints().
SetBreakPoint()
bool v8::internal::WasmScript::SetBreakPoint (DirectHandle< Script > script, int * position, DirectHandle< BreakPoint > break_point) [static]
Definition at line 941 of file wasm-debug.cc.
                                                                     {
  DCHECK_NE(kOnEntryBreakpointPosition, *position);
  // Find the function for this breakpoint.
  const wasm::WasmModule* module = script->wasm_native_module()->module();
  int func_index = GetContainingWasmFunction(module, *position);
  if (func_index < 0) return false;
  const wasm::WasmFunction& func = module->functions[func_index];
  int offset_in_func = *position - func.code.offset();
  int breakable_offset = FindNextBreakablePosition(script->wasm_native_module(),
                                                   func_index, offset_in_func);
  if (breakable_offset == 0) return false;
  *position = func.code.offset() + breakable_offset;
  return WasmScript::SetBreakPointForFunction(script, func_index,
                                              breakable_offset, break_point);
}
References v8::internal::wasm::WasmFunction::code, DCHECK_NE, v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::GetContainingWasmFunction(), kOnEntryBreakpointPosition, v8::internal::wasm::WireBytesRef::offset(), v8::internal::script, and SetBreakPointForFunction().
Referenced by v8::internal::Debug::SetBreakPointForScript().
SetBreakPointForFunction()
bool v8::internal::WasmScript::SetBreakPointForFunction (DirectHandle< Script > script, int function_index, int breakable_offset, DirectHandle< BreakPoint > break_point) [static]
Definition at line 986 of file wasm-debug.cc.
                                          {
  Isolate* isolate = Isolate::Current();
  DCHECK_LE(0, func_index);
  DCHECK_NE(0, offset);
  // Find the function for this breakpoint.
  wasm::NativeModule* native_module = script->wasm_native_module();
  const wasm::WasmModule* module = native_module->module();
  const wasm::WasmFunction& func = module->functions[func_index];
  // Insert new break point into {wasm_breakpoint_infos} of the script.
  AddBreakpointToInfo(script, func.code.offset() + offset, break_point);
  native_module->GetDebugInfo()->SetBreakpoint(func_index, offset, isolate);
  return true;
}
References AddBreakpointToInfo(), v8::internal::wasm::WasmFunction::code, v8::internal::Isolate::Current(), DCHECK_LE, DCHECK_NE, v8::internal::wasm::WasmModule::functions, v8::internal::wasm::NativeModule::GetDebugInfo(), v8::internal::wasm::NativeModule::module(), v8::internal::wasm::WireBytesRef::offset(), v8::internal::script, and v8::internal::wasm::DebugInfo::SetBreakpoint().
Referenced by SetBreakPoint(), and SetBreakPointOnFirstBreakableForFunction().
SetBreakPointOnFirstBreakableForFunction()
bool v8::internal::WasmScript::SetBreakPointOnFirstBreakableForFunction (DirectHandle< Script > script, int function_index, DirectHandle< BreakPoint > break_point) [static]
Definition at line 972 of file wasm-debug.cc.
                                          {
  if (func_index < 0) return false;
  int offset_in_func = 0;
  int breakable_offset = FindNextBreakablePosition(script->wasm_native_module(),
                                                   func_index, offset_in_func);
  if (breakable_offset == 0) return false;
  return WasmScript::SetBreakPointForFunction(script, func_index,
                                              breakable_offset, break_point);
}
References v8::internal::anonymous_namespace{wasm-debug.cc}::FindNextBreakablePosition(), v8::internal::script, and SetBreakPointForFunction().
Referenced by v8::internal::Debug::SetBreakpointForFunction().
SetInstrumentationBreakpoint()
void v8::internal::WasmScript::SetInstrumentationBreakpoint (DirectHandle< Script > script, DirectHandle< BreakPoint > break_point) [static]
Definition at line 962 of file wasm-debug.cc.
                                                                       {
  // Special handling for on-entry breakpoints.
  AddBreakpointToInfo(script, kOnEntryBreakpointPosition, break_point);
  // Update the "break_on_entry" flag on all live instances.
  SetBreakOnEntryFlag(*script, true);
}
References AddBreakpointToInfo(), kOnEntryBreakpointPosition, v8::internal::script, and v8::internal::anonymous_namespace{wasm-debug.cc}::SetBreakOnEntryFlag().
Member Data Documentation
kOnEntryBreakpointPosition
constexpr int v8::internal::WasmScript::kOnEntryBreakpointPosition = -1 [static], [constexpr]
Definition at line 1286 of file wasm-objects.h.
Referenced by v8::internal::anonymous_namespace{runtime-wasm.cc}::ExecuteWasmDebugBreaks(), v8::internal::anonymous_namespace{wasm-debug.cc}::FindBreakpointInfoInsertPos(), SetBreakPoint(), and SetInstrumentationBreakpoint().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-debug.cc