v8::internal::BuiltinArguments Class Reference
#include <builtins-utils.h>
Public Member Functions
BuiltinArguments (int length, Address *arguments)
Tagged< Object > operator[] (int index) const
template<class S = Object>
Handle< S > at (int index) const
void set_at (int index, Tagged< Object > value)
Address * address_of_first_argument () const
Handle< Object > atOrUndefined (Isolate *isolate, int index) const
Handle< JSAny > receiver () const
Handle< JSFunction > target () const
Handle< HeapObject > new_target () const
int length () const
Static Public Attributes
static constexpr int kNewTargetIndex = 0
static constexpr int kTargetIndex = 1
static constexpr int kArgcIndex = 2
static constexpr int kPaddingIndex = 3
static constexpr int kNumExtraArgs = 4
static constexpr int kNumExtraArgsWithReceiver = 5
static constexpr int kArgsIndex = kNumExtraArgs
static constexpr int kReceiverIndex = kArgsIndex
static constexpr int kFirstArgsIndex = kArgsIndex + 1
static constexpr int kReceiverArgsIndex = kArgsIndex - kFirstArgsIndex
Detailed Description
Definition at line 20 of file builtins-utils.h.
Constructor & Destructor Documentation
BuiltinArguments()
v8::internal::BuiltinArguments::BuiltinArguments (int length, Address * arguments) [inline]
Definition at line 22 of file builtins-utils.h.
      : Arguments(length, arguments) {
    // Check we have at least the receiver.
    DCHECK_LE(1, this->length());
    DCHECK(Tagged<Object>((*at(0)).ptr()).IsObject());
  }
References at(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::IsObject(), and length().
Member Function Documentation
address_of_first_argument()
Address* v8::internal::BuiltinArguments::address_of_first_argument () const [inline]
Definition at line 50 of file builtins-utils.h.
                                                    {
    return address_of_arg_at(kFirstArgsIndex);
  }
References v8::internal::Arguments< arguments_type >::address_of_arg_at(), and kFirstArgsIndex.
at()
template<class S = Object>
Handle<S> v8::internal::BuiltinArguments::at (int index) const [inline]
Definition at line 37 of file builtins-utils.h.
                                {
    DCHECK_LT(index, length());
    return Handle<S>(address_of_arg_at(index + kArgsIndex));
  }
References v8::internal::Arguments< arguments_type >::address_of_arg_at(), DCHECK_LT, v8::internal::index, kArgsIndex, and length().
Referenced by BuiltinArguments().
atOrUndefined()
Handle< Object > v8::internal::BuiltinArguments::atOrUndefined (Isolate * isolate, int index) const [inline]
Definition at line 16 of file builtins-utils-inl.h.
                                                                {
  if (index >= length()) {
    return isolate->factory()->undefined_value();
  }
  return at<Object>(index);
}
References v8::internal::Isolate::factory(), v8::internal::index, and length().
length()
int v8::internal::BuiltinArguments::length () const [inline]
Definition at line 78 of file builtins-utils.h.
{ return Arguments::length() - kNumExtraArgs; }
References kNumExtraArgs, and v8::internal::Arguments< arguments_type >::length().
Referenced by at(), atOrUndefined(), BuiltinArguments(), operator[](), and set_at().
new_target()
Handle< HeapObject > v8::internal::BuiltinArguments::new_target () const [inline]
Definition at line 32 of file builtins-utils-inl.h.
                                                      {
  return Handle<JSFunction>(address_of_arg_at(kNewTargetIndex));
}
References v8::internal::Arguments< arguments_type >::address_of_arg_at(), and kNewTargetIndex.
operator[]()
Tagged<Object> v8::internal::BuiltinArguments::operator[] (int index) const [inline]
Definition at line 30 of file builtins-utils.h.
                                             {
    DCHECK_LT(index, length());
    return Tagged<Object>(*address_of_arg_at(index + kArgsIndex));
  }
References v8::internal::Arguments< arguments_type >::address_of_arg_at(), DCHECK_LT, v8::internal::index, kArgsIndex, length(), and v8::internal::Tagged< Object >.
receiver()
Handle< JSAny > v8::internal::BuiltinArguments::receiver () const [inline]
Definition at line 24 of file builtins-utils-inl.h.
                                               {
  return Handle<JSAny>(address_of_arg_at(kReceiverIndex));
}
References v8::internal::Arguments< arguments_type >::address_of_arg_at(), and kReceiverIndex.
set_at()
void v8::internal::BuiltinArguments::set_at (int index, Tagged< Object > value) [inline]
Definition at line 43 of file builtins-utils.h.
                                                      {
    DCHECK_LT(index, length());
    *address_of_arg_at(index + kArgsIndex) = value.ptr();
  }
References v8::internal::Arguments< arguments_type >::address_of_arg_at(), DCHECK_LT, v8::internal::index, kArgsIndex, length(), and v8::internal::value.
target()
Handle< JSFunction > v8::internal::BuiltinArguments::target () const [inline]
Definition at line 28 of file builtins-utils-inl.h.
                                                  {
  return Handle<JSFunction>(address_of_arg_at(kTargetIndex));
}
References v8::internal::Arguments< arguments_type >::address_of_arg_at(), and kTargetIndex.
Member Data Documentation
kArgcIndex
constexpr int v8::internal::BuiltinArguments::kArgcIndex = 2 [static], [constexpr]
Definition at line 56 of file builtins-utils.h.
Referenced by v8::internal::CppBuiltinsAdaptorAssembler::GenerateAdaptor(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), and v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin().
kArgsIndex
constexpr int v8::internal::BuiltinArguments::kArgsIndex = kNumExtraArgs [static], [constexpr]
Definition at line 63 of file builtins-utils.h.
Referenced by at(), operator[](), and set_at().
kFirstArgsIndex
constexpr int v8::internal::BuiltinArguments::kFirstArgsIndex = kArgsIndex + 1 [static], [constexpr]
Definition at line 65 of file builtins-utils.h.
Referenced by address_of_first_argument().
kNewTargetIndex
constexpr int v8::internal::BuiltinArguments::kNewTargetIndex = 0 [static], [constexpr]
Definition at line 54 of file builtins-utils.h.
Referenced by v8::internal::CppBuiltinsAdaptorAssembler::GenerateAdaptor(), new_target(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), and v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin().
kNumExtraArgs
constexpr int v8::internal::BuiltinArguments::kNumExtraArgs = 4 [static], [constexpr]
Definition at line 60 of file builtins-utils.h.
Referenced by length().
kNumExtraArgsWithReceiver
constexpr int v8::internal::BuiltinArguments::kNumExtraArgsWithReceiver = 5 [static], [constexpr]
Definition at line 61 of file builtins-utils.h.
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), and v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin().
kPaddingIndex
constexpr int v8::internal::BuiltinArguments::kPaddingIndex = 3 [static], [constexpr]
Definition at line 58 of file builtins-utils.h.
Referenced by v8::internal::CppBuiltinsAdaptorAssembler::GenerateAdaptor(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), and v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin().
kReceiverArgsIndex
constexpr int v8::internal::BuiltinArguments::kReceiverArgsIndex = kArgsIndex - kFirstArgsIndex [static], [constexpr]
Definition at line 68 of file builtins-utils.h.
Referenced by v8::internal::anonymous_namespace{builtins-api.cc}::HandleApiCallHelper().
kReceiverIndex
constexpr int v8::internal::BuiltinArguments::kReceiverIndex = kArgsIndex [static], [constexpr]
Definition at line 64 of file builtins-utils.h.
Referenced by receiver().
kTargetIndex
constexpr int v8::internal::BuiltinArguments::kTargetIndex = 1 [static], [constexpr]
Definition at line 55 of file builtins-utils.h.
Referenced by v8::internal::CppBuiltinsAdaptorAssembler::GenerateAdaptor(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), and target().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-utils.h
/mnt/V8SourceCode/src/builtins/builtins-utils-inl.h