v8::internal::KeyedLoadIC Class Reference
#include <ic.h>
Public Member Functions
KeyedLoadIC (Isolate *isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > Load (Handle< JSAny > object, Handle< Object > key)
Protected Member Functions
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > RuntimeLoad (DirectHandle< JSAny > object, DirectHandle< Object > key, bool *is_found=nullptr)
V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > LoadName (Handle< JSAny > object, DirectHandle< Object > key, Handle< Name > name)
void UpdateLoadElement (DirectHandle< HeapObject > receiver, KeyedAccessLoadMode new_load_mode)
Private Member Functions
Handle< Object > LoadElementHandler (DirectHandle< Map > receiver_map, KeyedAccessLoadMode new_load_mode, MaybeDirectHandle< Map > maybe_transition_target={})
void LoadElementPolymorphicHandlers (MapHandles *receiver_maps, MaybeObjectHandles *handlers, KeyedAccessLoadMode new_load_mode)
KeyedAccessLoadMode GetKeyedAccessLoadModeFor (DirectHandle< Map > receiver_map) const
Friends
class IC
Additional Inherited Members
Detailed Description
Definition at line 228 of file ic.h.
Constructor & Destructor Documentation
KeyedLoadIC()
v8::internal::KeyedLoadIC::KeyedLoadIC (Isolate * isolate, Handle< FeedbackVector > vector, FeedbackSlot slot, FeedbackSlotKind kind) [inline]
Definition at line 230 of file ic.h.
      : LoadIC(isolate, vector, slot, kind) {}
Member Function Documentation
GetKeyedAccessLoadModeFor()
KeyedAccessLoadMode v8::internal::KeyedLoadIC::GetKeyedAccessLoadModeFor (DirectHandle< Map > receiver_map) const [private]
Definition at line 1155 of file ic.cc.
                                          {
  const MaybeObjectDirectHandle& handler =
      nexus()->FindHandlerForMap(receiver_map);
  if (handler.is_null()) return KeyedAccessLoadMode::kInBounds;
  return LoadHandler::GetKeyedAccessLoadMode(*handler);
}
References v8::internal::FeedbackNexus::FindHandlerForMap(), v8::internal::LoadHandler::GetKeyedAccessLoadMode(), v8::internal::MaybeObjectDirectHandle::is_null(), v8::internal::kInBounds, and v8::internal::IC::nexus().
Referenced by UpdateLoadElement().
Load()
MaybeDirectHandle< Object > v8::internal::KeyedLoadIC::Load (Handle< JSAny > object, Handle< Object > key)
Definition at line 1603 of file ic.cc.
                                                                {
  if (MigrateDeprecated(isolate(), object)) {
    return RuntimeLoad(object, key);
  }
  intptr_t maybe_index;
  Handle<Name> maybe_name;
  KeyType key_type = TryConvertKey(key, isolate(), &maybe_index, &maybe_name);
  if (key_type == kName) return LoadName(object, key, maybe_name);
  bool is_found = false;
  MaybeDirectHandle<Object> result = RuntimeLoad(object, key, &is_found);
  size_t index;
  if (key_type == kIntPtr && CanCache(object, state()) &&
      IntPtrKeyToSize(maybe_index, Cast<HeapObject>(object), &index)) {
    DirectHandle<HeapObject> receiver = Cast<HeapObject>(object);
    KeyedAccessLoadMode load_mode =
        GetNewKeyedLoadMode(isolate(), receiver, index, is_found, result);
    UpdateLoadElement(receiver, load_mode);
    if (is_vector_set()) {
      TraceIC("LoadIC", key);
    }
  }
  if (vector_needs_update()) {
    ConfigureVectorState(MEGAMORPHIC, key);
    TraceIC("LoadIC", key);
  }
  return result;
}
References v8::internal::anonymous_namespace{ic.cc}::CanCache(), v8::internal::IC::ConfigureVectorState(), v8::internal::anonymous_namespace{ic.cc}::GetNewKeyedLoadMode(), v8::internal::index, v8::internal::anonymous_namespace{ic.cc}::IntPtrKeyToSize(), v8::internal::IC::is_vector_set(), v8::internal::IC::isolate(), v8::internal::key, v8::internal::anonymous_namespace{ic.cc}::kName, LoadName(), v8::internal::MEGAMORPHIC, v8::internal::anonymous_namespace{ic.cc}::MigrateDeprecated(), v8::base::internal::result, RuntimeLoad(), v8::internal::IC::state(), v8::internal::IC::TraceIC(), v8::internal::anonymous_namespace{ic.cc}::TryConvertKey(), UpdateLoadElement(), and v8::internal::IC::vector_needs_update().
Referenced by v8::internal::RUNTIME_FUNCTION().
LoadElementHandler()
Handle< Object > v8::internal::KeyedLoadIC::LoadElementHandler (DirectHandle< Map > receiver_map, KeyedAccessLoadMode new_load_mode, MaybeDirectHandle< Map > maybe_transition_target = {}) [private]
Definition at line 1391 of file ic.cc.
                                                    {
  // Has a getter interceptor, or is any has and has a query interceptor.
  if (receiver_map->has_indexed_interceptor() &&
      (receiver_map->GetIndexedInterceptor()->has_getter() ||
       (IsAnyHas() && receiver_map->GetIndexedInterceptor()->has_query())) &&
      !receiver_map->GetIndexedInterceptor()->non_masking()) {
    // TODO(jgruber): Update counter name.
    TRACE_HANDLER_STATS(isolate(), KeyedLoadIC_LoadIndexedInterceptorStub);
    return IsAnyHas() ? BUILTIN_CODE(isolate(), HasIndexedInterceptorIC)
                      : BUILTIN_CODE(isolate(), LoadIndexedInterceptorIC);
  }
  InstanceType instance_type = receiver_map->instance_type();
  if (instance_type < FIRST_NONSTRING_TYPE) {
    TRACE_HANDLER_STATS(isolate(), KeyedLoadIC_LoadIndexedStringDH);
    if (IsAnyHas()) return LoadHandler::LoadSlow(isolate());
    return LoadHandler::LoadIndexedString(isolate(), new_load_mode);
  }
  if (instance_type < FIRST_JS_RECEIVER_TYPE) {
    TRACE_HANDLER_STATS(isolate(), KeyedLoadIC_SlowStub);
    return LoadHandler::LoadSlow(isolate());
  }
  if (instance_type == JS_PROXY_TYPE) {
    return LoadHandler::LoadProxy(isolate());
  }
#if V8_ENABLE_WEBASSEMBLY
  if (InstanceTypeChecker::IsWasmObject(instance_type)) {
    // TODO(jgruber): Update counter name.
    TRACE_HANDLER_STATS(isolate(), KeyedLoadIC_SlowStub);
    return LoadHandler::LoadSlow(isolate());
  }
#endif // V8_ENABLE_WEBASSEMBLY
  ElementsKind elements_kind = receiver_map->elements_kind();
  if (IsSloppyArgumentsElementsKind(elements_kind)) {
    // TODO(jgruber): Update counter name.
    TRACE_HANDLER_STATS(isolate(), KeyedLoadIC_KeyedLoadSloppyArgumentsStub);
    return IsAnyHas() ? BUILTIN_CODE(isolate(), KeyedHasIC_SloppyArguments)
                      : BUILTIN_CODE(isolate(), KeyedLoadIC_SloppyArguments);
  }
  bool is_js_array = instance_type == JS_ARRAY_TYPE;
  if (elements_kind == DICTIONARY_ELEMENTS) {
    TRACE_HANDLER_STATS(isolate(), KeyedLoadIC_LoadElementDH);
    return LoadHandler::LoadElement(isolate(), elements_kind, is_js_array,
                                    new_load_mode);
  }
  DCHECK(IsFastElementsKind(elements_kind) ||
         IsAnyNonextensibleElementsKind(elements_kind) ||
         IsTypedArrayOrRabGsabTypedArrayElementsKind(elements_kind));
  DCHECK_IMPLIES(
      LoadModeHandlesHoles(new_load_mode),
      AllowReadingHoleElement(elements_kind) &&
          AllowConvertHoleElementToUndefined(isolate(), receiver_map));
  DirectHandle<Map> transition_target;
  if (is_js_array && maybe_transition_target.ToHandle(&transition_target)) {
    DCHECK(IsFastElementsKind(elements_kind));
    return LoadHandler::TransitionAndLoadElement(
        isolate(), transition_target->elements_kind(), new_load_mode);
  }
  TRACE_HANDLER_STATS(isolate(), KeyedLoadIC_LoadElementDH);
  return LoadHandler::LoadElement(isolate(), elements_kind, is_js_array,
                                  new_load_mode);
}
References v8::internal::anonymous_namespace{ic.cc}::AllowConvertHoleElementToUndefined(), v8::internal::anonymous_namespace{ic.cc}::AllowReadingHoleElement(), BUILTIN_CODE, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::DICTIONARY_ELEMENTS, v8::internal::FIRST_NONSTRING_TYPE, v8::internal::IC::IsAnyHas(), v8::internal::IsAnyNonextensibleElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::IC::isolate(), v8::internal::IsSloppyArgumentsElementsKind(), v8::internal::IsTypedArrayOrRabGsabTypedArrayElementsKind(), v8::internal::IsWasmObject(), v8::internal::LoadHandler::LoadElement(), v8::internal::LoadHandler::LoadIndexedString(), v8::internal::LoadModeHandlesHoles(), v8::internal::LoadHandler::LoadProxy(), v8::internal::LoadHandler::LoadSlow(), v8::internal::MaybeDirectHandle< T >::ToHandle(), TRACE_HANDLER_STATS, and v8::internal::LoadHandler::TransitionAndLoadElement().
Referenced by LoadElementPolymorphicHandlers(), and UpdateLoadElement().
LoadElementPolymorphicHandlers()
void v8::internal::KeyedLoadIC::LoadElementPolymorphicHandlers (MapHandles * receiver_maps, MaybeObjectHandles * handlers, KeyedAccessLoadMode new_load_mode) [private]
Definition at line 1458 of file ic.cc.
                                       {
  // Filter out deprecated maps to ensure their instances get migrated.
  auto new_end = std::remove_if(
      receiver_maps->begin(), receiver_maps->end(),
      [](const DirectHandle<Map>& map) { return map->is_deprecated(); });
  receiver_maps->erase(new_end, receiver_maps->end());
  for (DirectHandle<Map> receiver_map : *receiver_maps) {
      Tagged<Map> tmap = receiver_map->FindElementsKindTransitionedMap(
          isolate(),
          MapHandlesSpan(receiver_maps->begin(), receiver_maps->end()),
          ConcurrencyMode::kSynchronous);
      if (!tmap.is_null()) {
        // Mark all stable receiver maps that have elements kind transition map
        // among receiver_maps as unstable because the ICs and the optimizing
        // compilers may perform an elements kind transition for this kind of
        // receivers.
        if (receiver_map->is_stable()) {
          receiver_map->NotifyLeafMapLayoutChange(isolate());
        }
        handlers->push_back(MaybeObjectHandle(LoadElementHandler(
            receiver_map,
            GetUpdatedLoadModeForMap(isolate(), receiver_map, new_load_mode),
            handle(tmap, isolate()))));
      } else {
        handlers->push_back(MaybeObjectHandle(LoadElementHandler(
            receiver_map,
            GetUpdatedLoadModeForMap(isolate(), receiver_map, new_load_mode))));
      }
  }
}
References v8::internal::DirectHandleSmallVector< T, kSize >::begin(), v8::internal::DirectHandleSmallVector< T, kSize >::end(), v8::internal::DirectHandleSmallVector< T, kSize >::erase(), v8::internal::anonymous_namespace{ic.cc}::GetUpdatedLoadModeForMap(), v8::internal::handle(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::IC::isolate(), v8::internal::kSynchronous, and LoadElementHandler().
Referenced by UpdateLoadElement().
LoadName()
MaybeDirectHandle< Object > v8::internal::KeyedLoadIC::LoadName (Handle< JSAny > object, DirectHandle< Object > key, Handle< Name > name) [protected]
Definition at line 1587 of file ic.cc.
                                                                   {
  DirectHandle<Object> load_handle;
  ASSIGN_RETURN_ON_EXCEPTION(isolate(), load_handle,
                             LoadIC::Load(object, name));
  if (vector_needs_update()) {
    ConfigureVectorState(MEGAMORPHIC, key);
    TraceIC("LoadIC", key);
  }
  DCHECK(!load_handle.is_null());
  return load_handle;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::IC::ConfigureVectorState(), v8::internal::DCHECK(), v8::internal::DirectHandle< T >::is_null(), v8::internal::IC::isolate(), v8::internal::key, v8::internal::LoadIC::Load(), v8::internal::MEGAMORPHIC, v8::internal::name, v8::internal::IC::TraceIC(), and v8::internal::IC::vector_needs_update().
Referenced by Load().
RuntimeLoad()
MaybeDirectHandle< Object > v8::internal::KeyedLoadIC::RuntimeLoad (DirectHandle< JSAny > object, DirectHandle< Object > key, bool * is_found = nullptr) [protected]
Definition at line 1569 of file ic.cc.
                                                                   {
  DirectHandle<Object> result;
  if (IsKeyedLoadIC()) {
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate(), result,
        Runtime::GetObjectProperty(isolate(), object, key,
                                   DirectHandle<JSAny>(), is_found));
  } else {
    DCHECK(IsKeyedHasIC());
    ASSIGN_RETURN_ON_EXCEPTION(isolate(), result,
                               Runtime::HasProperty(isolate(), object, key));
  }
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::DCHECK(), v8::internal::Runtime::GetObjectProperty(), v8::internal::Runtime::HasProperty(), v8::internal::IC::IsKeyedHasIC(), v8::internal::IC::IsKeyedLoadIC(), v8::internal::IC::isolate(), v8::internal::key, and v8::base::internal::result.
Referenced by Load().
UpdateLoadElement()
void v8::internal::KeyedLoadIC::UpdateLoadElement (DirectHandle< HeapObject > receiver, KeyedAccessLoadMode new_load_mode) [protected]
Definition at line 1174 of file ic.cc.
                                                                             {
  Handle<Map> receiver_map(receiver->map(), isolate());
  DCHECK(receiver_map->instance_type() !=
         JS_PRIMITIVE_WRAPPER_TYPE); // Checked by caller.
  MapHandles target_receiver_maps(isolate());
  TargetMaps(&target_receiver_maps);
  if (target_receiver_maps.empty()) {
    DirectHandle<Object> handler =
        LoadElementHandler(receiver_map, new_load_mode);
    return ConfigureVectorState(DirectHandle<Name>(), receiver_map, handler);
  }
  for (DirectHandle<Map> map : target_receiver_maps) {
    if (map.is_null()) continue;
    if (map->instance_type() == JS_PRIMITIVE_WRAPPER_TYPE) {
      set_slow_stub_reason("JSPrimitiveWrapper");
      return;
    }
    if (map->instance_type() == JS_PROXY_TYPE) {
      set_slow_stub_reason("JSProxy");
      return;
    }
  }
  // The first time a receiver is seen that is a transitioned version of the
  // previous monomorphic receiver type, assume the new ElementsKind is the
  // monomorphic type. This benefits global arrays that only transition
  // once, and all call sites accessing them are faster if they remain
  // monomorphic. If this optimistic assumption is not true, the IC will
  // miss again and it will become polymorphic and support both the
  // untransitioned and transitioned maps.
  if (state() == MONOMORPHIC) {
    if ((IsJSObject(*receiver) &&
         IsMoreGeneralElementsKindTransition(
             target_receiver_maps.at(0)->elements_kind(),
             Cast<JSObject>(receiver)->GetElementsKind())) ||
        IsWasmObject(*receiver)) {
      DirectHandle<Object> handler =
          LoadElementHandler(receiver_map, new_load_mode);
      return ConfigureVectorState(DirectHandle<Name>(), receiver_map, handler);
    }
  }
  DCHECK(state() != GENERIC);
  // Determine the list of receiver maps that this call site has seen,
  // adding the map that was just encountered.
  KeyedAccessLoadMode old_load_mode = KeyedAccessLoadMode::kInBounds;
  if (!AddOneReceiverMapIfMissing(&target_receiver_maps, receiver_map)) {
    old_load_mode = GetKeyedAccessLoadModeFor(receiver_map);
    if (!AllowedHandlerChange(old_load_mode, new_load_mode)) {
      set_slow_stub_reason("same map added twice");
      return;
    }
  }
  // If the maximum number of receiver maps has been exceeded, use the generic
  // version of the IC.
  if (static_cast<int>(target_receiver_maps.size()) >
      v8_flags.max_valid_polymorphic_map_count) {
    set_slow_stub_reason("max polymorph exceeded");
    return;
  }
  MaybeObjectHandles handlers;
  handlers.reserve(target_receiver_maps.size());
  KeyedAccessLoadMode load_mode =
      GeneralizeKeyedAccessLoadMode(old_load_mode, new_load_mode);
  LoadElementPolymorphicHandlers(&target_receiver_maps, &handlers, load_mode);
  if (target_receiver_maps.empty()) {
    DirectHandle<Object> handler =
        LoadElementHandler(receiver_map, new_load_mode);
    ConfigureVectorState(DirectHandle<Name>(), receiver_map, handler);
  } else if (target_receiver_maps.size() == 1) {
    ConfigureVectorState(DirectHandle<Name>(), target_receiver_maps[0],
                         handlers[0]);
  } else {
    ConfigureVectorState(DirectHandle<Name>(),
                         MapHandlesSpan(target_receiver_maps.begin(),
                                        target_receiver_maps.end()),
                         &handlers);
  }
}
References v8::internal::anonymous_namespace{ic.cc}::AddOneReceiverMapIfMissing(), v8::internal::AllowedHandlerChange(), v8::internal::DirectHandleSmallVector< T, kSize >::at(), v8::internal::DirectHandleSmallVector< T, kSize >::begin(), v8::internal::IC::ConfigureVectorState(), v8::internal::DCHECK(), v8::internal::DirectHandleSmallVector< T, kSize >::empty(), v8::internal::DirectHandleSmallVector< T, kSize >::end(), v8::internal::GeneralizeKeyedAccessLoadMode(), v8::internal::GENERIC, GetKeyedAccessLoadModeFor(), v8::internal::IsMoreGeneralElementsKindTransition(), v8::internal::IC::isolate(), v8::internal::IsWasmObject(), v8::internal::kInBounds, LoadElementHandler(), LoadElementPolymorphicHandlers(), v8::internal::MONOMORPHIC, v8::internal::IC::set_slow_stub_reason(), v8::internal::DirectHandleSmallVector< T, kSize >::size(), v8::internal::IC::state(), v8::internal::IC::TargetMaps(), and v8::internal::v8_flags.
Referenced by Load().
Friends And Related Function Documentation
IC
friend class IC [friend]
Definition at line 250 of file ic.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ic/ic.h
/mnt/V8SourceCode/src/ic/ic.cc