v8::internal::Tagged< T > Class Template Reference
#include <tagged.h>
Public Member Functions
constexpr Tagged ()=default
template<typename U = T>
Tagged (const T *ptr)
template<typename U >
constexpr Tagged & operator= (Tagged< U > other) requires(is_subtype_v< U
template<typename U >
constexpr Tagged (Tagged< U > other) requires(is_subtype_v< U
constexpr decltype(auto) operator-> () const
template<typename U >
constexpr Tagged (U raw) requires(is_subtype_v< U
Static Public Member Functions
template<typename U >
static constexpr Tagged< T > cast (U other)
Public Attributes
constexpr Tagged T
return * this
constexpr T: Base(other) {} inline constexpr decltype(auto) operator*() const { return operator_star_impl()
Private Types
using Base = typename detail::BaseForTagged< T >::type
Private Member Functions
constexpr Tagged (Address ptr)
T & operator_star_impl () const requires(std
T * operator_arrow_impl () const requires(std
constexpr T operator_star_impl () const requires(!std
constexpr detail::TaggedOperatorArrowRef< T > operator_arrow_impl () const requires(!std
template<typename U = T>
T * ToRawPtr () const requires(std
template<typename U = T>
constexpr T ToRawPtr () const requires(!std
Private Attributes
friend T
Friends
class Handle< T >
template<typename TFieldType , int kFieldOffset, typename CompressionScheme >
class TaggedField
template<typename TFieldType , typename CompressionScheme >
class TaggedMember
template<typename To , typename From >
Tagged< To > UncheckedCast (Tagged< From > value)
Tagged< T > MakeStrong (Tagged< T > value)
Tagged< T > MakeStrong (Tagged< MaybeWeak< T >> value)
Additional Inherited Members
Detailed Description
template<typename T>
class v8::internal::Tagged< T >
Definition at line 707 of file tagged.h.
Member Typedef Documentation
Base
template<typename T >
using v8::internal::Tagged< T >::Base = typename detail::BaseForTagged<T>::type [private]
Definition at line 708 of file tagged.h.
Constructor & Destructor Documentation
Tagged() [1/5]
template<typename T >
constexpr v8::internal::Tagged< T >::Tagged () [inline], [constexpr], [default]
Referenced by v8::internal::Tagged< Object >::operator=(), and v8::internal::Tagged< MaybeWeak< Object > >::operator=().
Tagged() [2/5]
template<typename T >
template<typename U = T>
v8::internal::Tagged< T >::Tagged (const T * ptr) [inline]
Definition at line 717 of file tagged.h.
      : Tagged(reinterpret_cast<Address>(ptr) + kHeapObjectTag) {
    static_assert(std::is_base_of_v<HeapObjectLayout, U>);
  }
Tagged() [3/5]
template<typename T >
template<typename U >
constexpr v8::internal::Tagged< T >::Tagged (Tagged< U > other) [inline], [constexpr]
Tagged() [4/5]
template<typename T >
template<typename U >
constexpr v8::internal::Tagged< T >::Tagged (U raw) [inline], [constexpr]
References v8::internal::kTaggedCanConvertToRawObjects.
Tagged() [5/5]
template<typename T >
constexpr v8::internal::Tagged< T >::Tagged (Address ptr) [inline], [explicit], [constexpr], [private]
Definition at line 783 of file tagged.h.
: Base(ptr) {}
Member Function Documentation
cast()
template<typename T >
template<typename U >
static constexpr Tagged<T> v8::internal::Tagged< T >::cast (U other) [inline], [static], [constexpr]
Definition at line 761 of file tagged.h.
                                           {
    static_assert(kTaggedCanConvertToRawObjects);
    return Cast<T>(Tagged<U>(other));
  }
References v8::internal::kTaggedCanConvertToRawObjects.
operator->()
template<typename T >
constexpr decltype(auto) v8::internal::Tagged< T >::operator-> () const [inline], [constexpr]
Definition at line 744 of file tagged.h.
                                                        {
    // Indirect operator-> through a helper, which has a couple of
    // implementations for old- and new-layout objects, so that gdb only sees
    // this single operator-> overload.
    return operator_arrow_impl();
  }
References v8::internal::Tagged< T >::operator_arrow_impl().
operator=()
template<typename T >
template<typename U >
constexpr Tagged& v8::internal::Tagged< T >::operator= (Tagged< U > other) [inline], [constexpr]
operator_arrow_impl() [1/2]
template<typename T >
constexpr detail::TaggedOperatorArrowRef<T> v8::internal::Tagged< T >::operator_arrow_impl () const [inline], [constexpr], [private]
Definition at line 801 of file tagged.h.
  {
    return detail::TaggedOperatorArrowRef<T>{ToRawPtr()};
  }
References v8::internal::Tagged< T >::ToRawPtr().
operator_arrow_impl() [2/2]
template<typename T >
T* v8::internal::Tagged< T >::operator_arrow_impl () const [inline], [private]
Definition at line 790 of file tagged.h.
  {
    return ToRawPtr();
  }
References v8::internal::Tagged< T >::ToRawPtr().
Referenced by v8::internal::Tagged< T >::operator->().
operator_star_impl() [1/2]
template<typename T >
constexpr T v8::internal::Tagged< T >::operator_star_impl () const [inline], [constexpr], [private]
Definition at line 796 of file tagged.h.
  {
    return ToRawPtr();
  }
References v8::internal::Tagged< T >::ToRawPtr().
operator_star_impl() [2/2]
template<typename T >
T& v8::internal::Tagged< T >::operator_star_impl () const [inline], [private]
Definition at line 785 of file tagged.h.
  {
    return *ToRawPtr();
  }
References v8::internal::Tagged< T >::ToRawPtr().
ToRawPtr() [1/2]
template<typename T >
template<typename U = T>
constexpr T v8::internal::Tagged< T >::ToRawPtr () const [inline], [constexpr], [private]
Definition at line 819 of file tagged.h.
  {
    // Check whether T is taggable on raw ptr access rather than top-level, to
    // allow forward declarations.
    static_assert(is_taggable_v<T>);
    return T(this->ptr(), typename T::SkipTypeCheckTag{});
  }
References v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::ptr(), and v8::internal::Tagged< T >::T.
ToRawPtr() [2/2]
template<typename T >
template<typename U = T>
T* v8::internal::Tagged< T >::ToRawPtr () const [inline], [private]
Definition at line 809 of file tagged.h.
  {
    // Check whether T is taggable on raw ptr access rather than top-level, to
    // allow forward declarations.
    static_assert(is_taggable_v<T>);
    return reinterpret_cast<T*>(this->ptr() - kHeapObjectTag);
  }
References v8::internal::kHeapObjectTag, and v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::ptr().
Referenced by v8::internal::Tagged< HeapObject >::operator->(), v8::internal::Tagged< T >::operator_arrow_impl(), and v8::internal::Tagged< T >::operator_star_impl().
Friends And Related Function Documentation
Handle< T >
template<typename T >
friend class Handle< T > [friend]
Definition at line 767 of file tagged.h.
MakeStrong [1/2]
template<typename T >
Tagged<T> MakeStrong (Tagged< MaybeWeak< T >> value) [friend]
Definition at line 908 of file tagged.h.
                                                        {
  return Tagged<T>(value.ptr() & (~kWeakHeapObjectTag | kHeapObjectTag));
}
MakeStrong [2/2]
template<typename T >
Tagged<T> MakeStrong (Tagged< T > value) [friend]
Definition at line 903 of file tagged.h.
                                             {
  return Tagged<T>(value.ptr() & (~kWeakHeapObjectTag | kHeapObjectTag));
}
TaggedField
template<typename T >
template<typename TFieldType , int kFieldOffset, typename CompressionScheme >
friend class TaggedField [friend]
Definition at line 774 of file tagged.h.
TaggedMember
template<typename T >
template<typename TFieldType , typename CompressionScheme >
friend class TaggedMember [friend]
Definition at line 776 of file tagged.h.
UncheckedCast
template<typename T >
template<typename To , typename From >
Tagged<To> UncheckedCast (Tagged< From > value) [friend]
Definition at line 61 of file casting.h.
                                                    {
  return Tagged<To>(value.ptr());
}
Member Data Documentation
T [1/3]
template<typename T >
constexpr v8::internal::Tagged< T >::T
Initial value:
{
    *this = Tagged(other)
Definition at line 725 of file tagged.h.
Referenced by v8::internal::Tagged< T >::ToRawPtr().
T [2/3]
template<typename T >
constexpr v8::internal::Tagged< T >::T
Definition at line 735 of file tagged.h.
T [3/3]
template<typename T >
friend v8::internal::Tagged< T >::T [private]
Definition at line 767 of file tagged.h.
this
template<typename T >
return* v8::internal::Tagged< T >::this
Definition at line 728 of file tagged.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/globals.h
/mnt/V8SourceCode/src/objects/tagged.h