v8::internal::compiler::turboshaft::TypeInferenceAnalysis Class Reference
#include <type-inference-analysis.h>
Public Member Functions
TypeInferenceAnalysis (const Graph &graph, Zone *phase_zone)
GrowingOpIndexSidetable< Type > Run (GrowingBlockSidetable< std::vector< std::pair< OpIndex, Type >>> *block_refinements=nullptr)
template<bool revisit_loop_header>
void ProcessBlock (const Block &block, uint32_t *unprocessed_index)
void ProcessCheckTurboshaftTypeOf (OpIndex index, const CheckTurboshaftTypeOfOp &check)
void ProcessComparison (OpIndex index, const ComparisonOp &comparison)
void ProcessConstant (OpIndex index, const ConstantOp &constant)
void ProcessFloatBinop (OpIndex index, const FloatBinopOp &binop)
bool ProcessLoopPhi (OpIndex index, const PhiOp &phi)
void ProcessOverflowCheckedBinop (OpIndex index, const OverflowCheckedBinopOp &binop)
void ProcessPhi (OpIndex index, const PhiOp &phi)
void ProcessProjection (OpIndex index, const ProjectionOp &projection)
void ProcessWordBinop (V< Word > index, const WordBinopOp &binop)
Type ComputeTypeForPhi (const PhiOp &phi)
void RefineTypesAfterBranch (const BranchOp *branch, const Block *new_block, bool then_branch)
void RefineOperationType (const Block *new_block, OpIndex op, const Type &type, char case_for_tracing)
void SetType (OpIndex index, Type result_type, bool allow_narrowing=false, bool is_fallback_for_unsupported_operation=false)
Type GetTypeOrInvalid (const OpIndex index)
Type GetTypeOrDefault (OpIndex index, const Type &default_type)
Type GetType (OpIndex index)
Type GetTypeAtDefinition (OpIndex index) const
Type Widen (const Type &old_type, const Type &new_type)
Private Types
using table_t = SnapshotTable< Type >
Private Attributes
const Graph & graph_
GrowingOpIndexSidetable< Type > types_
table_t table_
const Block * current_block_ = nullptr
GrowingOpIndexSidetable< std::optional< table_t::Key > > op_to_key_mapping_
GrowingBlockSidetable< std::optional< table_t::Snapshot > > block_to_snapshot_mapping_
ZoneVector< table_t::Snapshot > predecessors_
Zone * graph_zone_
Detailed Description
Definition at line 39 of file type-inference-analysis.h.
Member Typedef Documentation
table_t
using v8::internal::compiler::turboshaft::TypeInferenceAnalysis::table_t = SnapshotTable<Type> [private]
Definition at line 541 of file type-inference-analysis.h.
Constructor & Destructor Documentation
TypeInferenceAnalysis()
v8::internal::compiler::turboshaft::TypeInferenceAnalysis::TypeInferenceAnalysis (const Graph & graph, Zone * phase_zone) [inline], [explicit]
Definition at line 41 of file type-inference-analysis.h.
      : graph_(graph),
        // TODO(nicohartmann@): Might put types back into phase_zone once we
        // don't store them in the graph anymore.
        types_(graph.op_id_count(), Type{}, graph.graph_zone(), &graph),
        table_(phase_zone),
        op_to_key_mapping_(phase_zone, &graph),
        block_to_snapshot_mapping_(graph.block_count(), std::nullopt,
                                   phase_zone),
        predecessors_(phase_zone),
        graph_zone_(graph.graph_zone()) {}
Member Function Documentation
ComputeTypeForPhi()
Type v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ComputeTypeForPhi (const PhiOp & phi) [inline]
Definition at line 389 of file type-inference-analysis.h.
                                           {
    // Word64 values are truncated to word32 implicitly, we need to handle this
    // here.
    auto MaybeTruncate = [&](Type t) -> Type {
      if (t.IsNone()) return t;
      if (phi.rep == RegisterRepresentation::Word32()) {
        return Typer::TruncateWord32Input(t, true, graph_zone_);
      }
      return t;
    };
    Type result_type =
        MaybeTruncate(GetTypeOrDefault(phi.inputs()[0], Type::None()));
    for (size_t i = 1; i < phi.inputs().size(); ++i) {
      Type input_type =
          MaybeTruncate(GetTypeOrDefault(phi.inputs()[i], Type::None()));
      result_type = Type::LeastUpperBound(result_type, input_type, graph_zone_);
    }
    return result_type;
  }
References GetTypeOrDefault(), graph_zone_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::OperationT< Derived >::inputs(), v8::internal::compiler::turboshaft::Type::LeastUpperBound(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::turboshaft::PhiOp::rep, size(), v8::internal::compiler::turboshaft::Typer::TruncateWord32Input(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
Referenced by ProcessLoopPhi(), and ProcessPhi().
GetType()
Type v8::internal::compiler::turboshaft::TypeInferenceAnalysis::GetType (OpIndex index) [inline]
Definition at line 491 of file type-inference-analysis.h.
                              {
    Type t = GetTypeOrInvalid(index);
    if (t.IsInvalid()) {
      // TODO(nicohartmann@): This is a fallback mechanism as long as not all
      // operations are properly typed. Remove this once typing is complete.
      const Operation& op = graph_.Get(index);
      return Typer::TypeForRepresentation(op.outputs_rep(), graph_zone_);
    }
    return t;
  }
References v8::internal::compiler::turboshaft::Graph::Get(), GetTypeOrInvalid(), graph_, graph_zone_, v8::internal::index, v8::internal::compiler::turboshaft::Type::IsInvalid(), v8::internal::compiler::turboshaft::Operation::outputs_rep(), and v8::internal::compiler::turboshaft::Typer::TypeForRepresentation().
Referenced by ProcessCheckTurboshaftTypeOf(), ProcessComparison(), ProcessFloatBinop(), ProcessOverflowCheckedBinop(), ProcessProjection(), ProcessWordBinop(), and RefineTypesAfterBranch().
GetTypeAtDefinition()
Type v8::internal::compiler::turboshaft::TypeInferenceAnalysis::GetTypeAtDefinition (OpIndex index) const [inline]
Definition at line 502 of file type-inference-analysis.h.
{ return types_[index]; }
References v8::internal::index, and types_.
Referenced by ProcessLoopPhi().
GetTypeOrDefault()
Type v8::internal::compiler::turboshaft::TypeInferenceAnalysis::GetTypeOrDefault (OpIndex index, const Type & default_type) [inline]
Definition at line 485 of file type-inference-analysis.h.
                                                                 {
    Type t = GetTypeOrInvalid(index);
    if (t.IsInvalid()) return default_type;
    return t;
  }
References GetTypeOrInvalid(), v8::internal::index, and v8::internal::compiler::turboshaft::Type::IsInvalid().
Referenced by ComputeTypeForPhi().
GetTypeOrInvalid()
Type v8::internal::compiler::turboshaft::TypeInferenceAnalysis::GetTypeOrInvalid (const OpIndex index) [inline]
Definition at line 480 of file type-inference-analysis.h.
                                             {
    if (auto key = op_to_key_mapping_[index]) return table_.Get(*key);
    return Type::Invalid();
  }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Get(), v8::internal::index, v8::internal::compiler::turboshaft::Type::Invalid(), v8::internal::key, op_to_key_mapping_, and table_.
Referenced by GetType(), and GetTypeOrDefault().
ProcessBlock()
template<bool revisit_loop_header>
void v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock (const Block & block, uint32_t * unprocessed_index) [inline]
Definition at line 82 of file type-inference-analysis.h.
                                                                     {
    DCHECK_IMPLIES(revisit_loop_header, block.IsLoop());
    // Seal the current block first.
    if (table_.IsSealed()) {
      DCHECK_NULL(current_block_);
    } else {
      // If we process a new block while the previous one is still unsealed, we
      // finalize it.
      DCHECK_NOT_NULL(current_block_);
      DCHECK(current_block_->index().valid());
      block_to_snapshot_mapping_[current_block_->index()] = table_.Seal();
      current_block_ = nullptr;
    }
    // Collect the snapshots of all predecessors.
    {
      predecessors_.clear();
      for (const Block* pred : block.PredecessorsIterable()) {
        std::optional<table_t::Snapshot> pred_snapshot =
            block_to_snapshot_mapping_[pred->index()];
        if (pred_snapshot.has_value()) {
          predecessors_.push_back(pred_snapshot.value());
        } else {
          // The only case where we might not have a snapshot for the
          // predecessor is when we visit a loop header for the first time.
          DCHECK(block.IsLoop() && pred == block.LastPredecessor() &&
                 !revisit_loop_header);
        }
      }
      std::reverse(predecessors_.begin(), predecessors_.end());
    }
    // Start a new snapshot for this block by merging information from
    // predecessors.
    {
      auto MergeTypes = [&](table_t::Key,
                            base::Vector<const Type> predecessors) -> Type {
        DCHECK_GT(predecessors.size(), 0);
        Type result_type = predecessors[0];
        for (size_t i = 1; i < predecessors.size(); ++i) {
          result_type =
              Type::LeastUpperBound(result_type, predecessors[i], graph_zone_);
        }
        return result_type;
      };
      table_.StartNewSnapshot(base::VectorOf(predecessors_), MergeTypes);
    }
    // Check if the predecessor is a branch that allows us to refine a few
    // types.
    DCHECK_IMPLIES(revisit_loop_header, block.PredecessorCount() == 2);
    if (block.PredecessorCount() == 1) {
      Block* predecessor = block.LastPredecessor();
      const Operation& terminator = predecessor->LastOperation(graph_);
      if (const BranchOp* branch = terminator.TryCast<BranchOp>()) {
        DCHECK(branch->if_true == &block || branch->if_false == &block);
        RefineTypesAfterBranch(branch, &block, branch->if_true == &block);
      }
    }
    current_block_ = &block;
    bool loop_needs_revisit = false;
    auto op_range = graph_.OperationIndices(block);
    for (auto it = op_range.begin(); it != op_range.end(); ++it) {
      OpIndex index = *it;
      const Operation& op = graph_.Get(index);
      switch (op.opcode) {
        case Opcode::kBranch:
        case Opcode::kDeoptimize:
        case Opcode::kDeoptimizeIf:
        case Opcode::kFrameState:
        case Opcode::kReturn:
        case Opcode::kStore:
        case Opcode::kRetain:
        case Opcode::kUnreachable:
        case Opcode::kSwitch:
        case Opcode::kTuple:
        case Opcode::kStaticAssert:
        case Opcode::kDebugBreak:
        case Opcode::kDebugPrint:
#if V8_ENABLE_WEBASSEMBLY
        case Opcode::kGlobalSet:
        case Opcode::kTrapIf:
#endif
        case Opcode::kCheckException:
          // These operations do not produce any output that needs to be typed.
          DCHECK_EQ(0, op.outputs_rep().size());
          break;
        case Opcode::kCheckTurboshaftTypeOf:
          ProcessCheckTurboshaftTypeOf(index,
                                       op.Cast<CheckTurboshaftTypeOfOp>());
          break;
        case Opcode::kComparison:
          ProcessComparison(index, op.Cast<ComparisonOp>());
          break;
        case Opcode::kConstant:
          ProcessConstant(index, op.Cast<ConstantOp>());
          break;
        case Opcode::kFloatBinop:
          ProcessFloatBinop(index, op.Cast<FloatBinopOp>());
          break;
        case Opcode::kOverflowCheckedBinop:
          ProcessOverflowCheckedBinop(index, op.Cast<OverflowCheckedBinopOp>());
          break;
        case Opcode::kProjection:
          ProcessProjection(index, op.Cast<ProjectionOp>());
          break;
        case Opcode::kWordBinop:
          ProcessWordBinop(V<Word>::Cast(index), op.Cast<WordBinopOp>());
          break;
        case Opcode::kWord32PairBinop:
        case Opcode::kAtomicWord32Pair:
        case Opcode::kPendingLoopPhi:
          // Input graph must not contain these op codes.
          UNREACHABLE();
        case Opcode::kPhi:
          if constexpr (revisit_loop_header) {
            loop_needs_revisit =
                ProcessLoopPhi(index, op.Cast<PhiOp>()) || loop_needs_revisit;
          } else {
            ProcessPhi(index, op.Cast<PhiOp>());
          }
          break;
        case Opcode::kGoto: {
          const GotoOp& gto = op.Cast<GotoOp>();
          // Check if this is a backedge.
          if (gto.destination->IsLoop()) {
            if (gto.destination->index() < current_block_->index()) {
              ProcessBlock<true>(*gto.destination, unprocessed_index);
            } else if (gto.destination->index() == current_block_->index()) {
              // This is a single block loop. We must only revisit the current
              // header block if we actually need to, in order to prevent
              // infinite recursion.
              if (!revisit_loop_header || loop_needs_revisit) {
                ProcessBlock<true>(*gto.destination, unprocessed_index);
              }
            }
          }
          break;
        }
        default:
          // TODO(nicohartmann@): Support remaining operations. For now we
          // compute fallback types.
          if (op.outputs_rep().size() > 0) {
            constexpr bool allow_narrowing = false;
            constexpr bool is_fallback_for_unsupported_operation = true;
            SetType(index,
                    Typer::TypeForRepresentation(op.outputs_rep(), graph_zone_),
                    allow_narrowing, is_fallback_for_unsupported_operation);
          }
          break;
        case Opcode::kLoadRootRegister:
          SetType(index,
                  Typer::TypeForRepresentation(op.outputs_rep(), graph_zone_));
          break;
      }
    }
    if constexpr (revisit_loop_header) {
      if (loop_needs_revisit) {
        // This is a loop header and the loop body needs to be revisited. Reset
        // {unprocessed_index} to the loop header's successor.
        *unprocessed_index =
            std::min(*unprocessed_index, block.index().id() + 1);
      }
    }
  }
References v8::internal::ZoneVector< T >::begin(), block_to_snapshot_mapping_, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::ZoneVector< T >::clear(), current_block_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GT, DCHECK_IMPLIES, DCHECK_NOT_NULL, DCHECK_NULL, v8::internal::compiler::turboshaft::GotoOp::destination, v8::internal::ZoneVector< T >::end(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, graph_zone_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::index, v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::IsSealed(), v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::kConstant, v8::internal::wasm::kSwitch, v8::internal::wasm::kUnreachable, v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), v8::internal::compiler::turboshaft::Type::LeastUpperBound(), v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::Graph::OperationIndices(), v8::internal::compiler::turboshaft::Operation::outputs_rep(), v8::internal::compiler::turboshaft::Block::PredecessorCount(), predecessors_, v8::internal::compiler::turboshaft::Block::PredecessorsIterable(), ProcessCheckTurboshaftTypeOf(), ProcessComparison(), ProcessConstant(), ProcessFloatBinop(), ProcessLoopPhi(), ProcessOverflowCheckedBinop(), ProcessPhi(), ProcessProjection(), ProcessWordBinop(), v8::internal::ZoneVector< T >::push_back(), RefineTypesAfterBranch(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal(), SetType(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot(), table_, v8::internal::compiler::turboshaft::Operation::TryCast(), v8::internal::compiler::turboshaft::Typer::TypeForRepresentation(), v8::internal::UNREACHABLE(), v8::internal::compiler::turboshaft::BlockIndex::valid(), and v8::base::VectorOf().
ProcessCheckTurboshaftTypeOf()
void v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessCheckTurboshaftTypeOf (OpIndex index, const CheckTurboshaftTypeOfOp & check) [inline]
Definition at line 254 of file type-inference-analysis.h.
                                                                          {
    Type input_type = GetType(check.input());
    if (input_type.IsSubtypeOf(check.type)) {
      TURBOSHAFT_TRACE_TYPING_OK(
          "CTOF %3d:%-40s\n P: %3d:%-40s ~~> %s\n", index.id(),
          graph_.Get(index).ToString().substr(0, 40).c_str(),
          check.input().id(),
          graph_.Get(check.input()).ToString().substr(0, 40).c_str(),
          input_type.ToString().c_str());
    } else if (check.successful) {
      FATAL(
          "Checking type %s of operation %d:%s failed after it passed in a "
          "previous phase",
          check.type.ToString().c_str(), check.input().id(),
          graph_.Get(check.input()).ToString().c_str());
    } else {
      TURBOSHAFT_TRACE_TYPING_FAIL(
          "CTOF %3d:%-40s\n F: %3d:%-40s ~~> %s\n", index.id(),
          graph_.Get(index).ToString().substr(0, 40).c_str(),
          check.input().id(),
          graph_.Get(check.input()).ToString().substr(0, 40).c_str(),
          input_type.ToString().c_str());
    }
  }
References FATAL, v8::internal::compiler::turboshaft::Graph::Get(), GetType(), graph_, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::index, v8::internal::compiler::turboshaft::CheckTurboshaftTypeOfOp::input(), v8::internal::compiler::turboshaft::Type::IsSubtypeOf(), v8::internal::compiler::turboshaft::CheckTurboshaftTypeOfOp::successful, v8::internal::compiler::turboshaft::Operation::ToString(), v8::internal::compiler::turboshaft::Type::ToString(), TURBOSHAFT_TRACE_TYPING_FAIL, TURBOSHAFT_TRACE_TYPING_OK, and v8::internal::compiler::turboshaft::CheckTurboshaftTypeOfOp::type.
Referenced by ProcessBlock().
ProcessComparison()
void v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessComparison (OpIndex index, const ComparisonOp & comparison) [inline]
Definition at line 281 of file type-inference-analysis.h.
                                                                        {
    Type left_type = GetType(comparison.left());
    Type right_type = GetType(comparison.right());
    Type result_type = Typer::TypeComparison(
        left_type, right_type, comparison.rep, comparison.kind, graph_zone_);
    SetType(index, result_type);
  }
References GetType(), graph_zone_, v8::internal::index, v8::internal::compiler::turboshaft::ComparisonOp::kind, v8::internal::compiler::turboshaft::ComparisonOp::left(), v8::internal::compiler::turboshaft::ComparisonOp::rep, v8::internal::compiler::turboshaft::ComparisonOp::right(), SetType(), and v8::internal::compiler::turboshaft::Typer::TypeComparison().
Referenced by ProcessBlock().
ProcessConstant()
void v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessConstant (OpIndex index, const ConstantOp & constant) [inline]
Definition at line 290 of file type-inference-analysis.h.
                                                                  {
    if (constant.kind == ConstantOp::Kind::kFloat64 &&
        constant.float64().is_hole_nan()) {
      // TODO(nicohartmann): figure out how to type Float64 NaN holes. Typing
      // them simply as NaN is not always correct and can lead to replacing NaN
      // holes with regular NaNs.
      SetType(index, Type::Any());
      return;
    }
    Type type = Typer::TypeConstant(constant.kind, constant.storage);
    SetType(index, type);
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::turboshaft::ConstantOp::float64(), v8::internal::index, v8::internal::Float64::is_hole_nan(), v8::internal::compiler::turboshaft::ConstantOp::kFloat64, v8::internal::compiler::turboshaft::ConstantOp::kind, SetType(), v8::internal::compiler::turboshaft::ConstantOp::storage, v8::internal::tracing::type, and v8::internal::compiler::turboshaft::Typer::TypeConstant().
Referenced by ProcessBlock().
ProcessFloatBinop()
void v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessFloatBinop (OpIndex index, const FloatBinopOp & binop) [inline]
Definition at line 303 of file type-inference-analysis.h.
                                                                   {
    Type left_type = GetType(binop.left());
    Type right_type = GetType(binop.right());
    Type result_type = Typer::TypeFloatBinop(left_type, right_type, binop.kind,
                                             binop.rep, graph_zone_);
    SetType(index, result_type);
  }
References GetType(), graph_zone_, v8::internal::index, v8::internal::compiler::turboshaft::FloatBinopOp::kind, v8::internal::compiler::turboshaft::FloatBinopOp::left(), v8::internal::compiler::turboshaft::FloatBinopOp::rep, v8::internal::compiler::turboshaft::FloatBinopOp::right(), SetType(), and v8::internal::compiler::turboshaft::Typer::TypeFloatBinop().
Referenced by ProcessBlock().
ProcessLoopPhi()
bool v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessLoopPhi (OpIndex index, const PhiOp & phi) [inline]
Definition at line 312 of file type-inference-analysis.h.
                                                       {
    Type old_type = GetTypeAtDefinition(index);
    Type new_type = ComputeTypeForPhi(phi);
    if (old_type.IsInvalid()) {
      SetType(index, new_type);
      return true;
    }
    // If the new type is smaller, we narrow it without revisiting the loop.
    if (new_type.IsSubtypeOf(old_type)) {
      TURBOSHAFT_TRACE_TYPING_OK(
          "LOOP %3d:%-40s (FIXPOINT)\n N: %-40s ~~> %-40s\n", index.id(),
          graph_.Get(index).ToString().substr(0, 40).c_str(),
          old_type.ToString().c_str(), new_type.ToString().c_str());
      constexpr bool allow_narrowing = true;
      SetType(index, new_type, allow_narrowing);
      return false;
    }
    // Otherwise, the new type is larger and we widen and revisit the loop.
    TURBOSHAFT_TRACE_TYPING_OK(
        "LOOP %3d:%-40s (REVISIT)\n W: %-40s ~~> %-40s\n", index.id(),
        graph_.Get(index).ToString().substr(0, 40).c_str(),
        old_type.ToString().c_str(), new_type.ToString().c_str());
    if (!old_type.IsNone()) {
      new_type = Widen(old_type, new_type);
    }
    SetType(index, new_type);
    return true;
  }
References ComputeTypeForPhi(), v8::internal::compiler::turboshaft::Graph::Get(), GetTypeAtDefinition(), graph_, v8::internal::index, v8::internal::compiler::turboshaft::Type::IsInvalid(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::Type::IsSubtypeOf(), SetType(), v8::internal::compiler::turboshaft::Operation::ToString(), v8::internal::compiler::turboshaft::Type::ToString(), TURBOSHAFT_TRACE_TYPING_OK, and Widen().
Referenced by ProcessBlock().
ProcessOverflowCheckedBinop()
void v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessOverflowCheckedBinop (OpIndex index, const OverflowCheckedBinopOp & binop) [inline]
Definition at line 346 of file type-inference-analysis.h.
                                                                        {
    Type left_type = GetType(binop.left());
    Type right_type = GetType(binop.right());
    Type result_type = Typer::TypeOverflowCheckedBinop(
        left_type, right_type, binop.kind, binop.rep, graph_zone_);
    SetType(index, result_type);
  }
References GetType(), graph_zone_, v8::internal::index, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kind, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::left(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::rep, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::right(), SetType(), and v8::internal::compiler::turboshaft::Typer::TypeOverflowCheckedBinop().
Referenced by ProcessBlock().
ProcessPhi()
void v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessPhi (OpIndex index, const PhiOp & phi) [inline]
Definition at line 356 of file type-inference-analysis.h.
                                                   {
    Type result_type = ComputeTypeForPhi(phi);
    SetType(index, result_type);
  }
References ComputeTypeForPhi(), v8::internal::index, and SetType().
Referenced by ProcessBlock().
ProcessProjection()
void v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessProjection (OpIndex index, const ProjectionOp & projection) [inline]
Definition at line 361 of file type-inference-analysis.h.
                                                                        {
    Type input_type = GetType(projection.input());
    Type result_type;
    if (input_type.IsNone()) {
      result_type = Type::None();
    } else if (input_type.IsTuple()) {
      const TupleType& tuple = input_type.AsTuple();
      DCHECK_LT(projection.index, tuple.size());
      result_type = tuple.element(projection.index);
      DCHECK(result_type.IsSubtypeOf(
          Typer::TypeForRepresentation(projection.rep)));
    } else {
      result_type = Typer::TypeForRepresentation(projection.rep);
    }
    SetType(index, result_type);
  }
References v8::internal::compiler::turboshaft::Type::AsTuple(), v8::internal::DCHECK(), DCHECK_LT, v8::internal::compiler::turboshaft::TupleType::element(), GetType(), v8::internal::compiler::turboshaft::ProjectionOp::index, v8::internal::index, v8::internal::compiler::turboshaft::ProjectionOp::input(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::Type::IsSubtypeOf(), v8::internal::compiler::turboshaft::Type::IsTuple(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::turboshaft::ProjectionOp::rep, SetType(), v8::internal::compiler::turboshaft::TupleType::size(), and v8::internal::compiler::turboshaft::Typer::TypeForRepresentation().
Referenced by ProcessBlock().
ProcessWordBinop()
void v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessWordBinop (V< Word > index, const WordBinopOp & binop) [inline]
Definition at line 380 of file type-inference-analysis.h.
                                                                 {
    Type left_type = GetType(binop.left());
    Type right_type = GetType(binop.right());
    Type result_type = Typer::TypeWordBinop(left_type, right_type, binop.kind,
                                            binop.rep, graph_zone_);
    SetType(index, result_type);
  }
References GetType(), graph_zone_, v8::internal::index, v8::internal::compiler::turboshaft::WordBinopOp::kind, v8::internal::compiler::turboshaft::WordBinopOp::left(), v8::internal::compiler::turboshaft::WordBinopOp::rep, v8::internal::compiler::turboshaft::WordBinopOp::right(), SetType(), and v8::internal::compiler::turboshaft::Typer::TypeWordBinop().
Referenced by ProcessBlock().
RefineOperationType()
void v8::internal::compiler::turboshaft::TypeInferenceAnalysis::RefineOperationType (const Block * new_block, OpIndex op, const Type & type, char case_for_tracing) [inline]
Definition at line 427 of file type-inference-analysis.h.
                                                  {
    DCHECK(op.valid());
    DCHECK(!type.IsInvalid());
    TURBOSHAFT_TRACE_TYPING_OK(" %c: %3d:%-40s ~~> %s\n", case_for_tracing,
                               op.id(),
                               graph_.Get(op).ToString().substr(0, 40).c_str(),
                               type.ToString().c_str());
    auto key_opt = op_to_key_mapping_[op];
    DCHECK(key_opt.has_value());
    table_.Set(*key_opt, type);
#ifdef DEBUG
    if (block_refinements_) {
      (*block_refinements_)[new_block->index()].emplace_back(op, type);
    }
#endif
    // TODO(nicohartmann@): One could push the refined type deeper into the
    // operations.
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::Block::index(), op_to_key_mapping_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Set(), table_, v8::internal::compiler::turboshaft::Operation::ToString(), TURBOSHAFT_TRACE_TYPING_OK, v8::internal::tracing::type, and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by RefineTypesAfterBranch().
RefineTypesAfterBranch()
void v8::internal::compiler::turboshaft::TypeInferenceAnalysis::RefineTypesAfterBranch (const BranchOp * branch, const Block * new_block, bool then_branch) [inline]
Definition at line 410 of file type-inference-analysis.h.
                                                {
    TURBOSHAFT_TRACE_TYPING_OK("Br %3d:%-40s\n", graph_.Index(*branch).id(),
                               branch->ToString().substr(0, 40).c_str());
    Typer::BranchRefinements refinements(
        [this](OpIndex index) { return GetType(index); },
        [&](OpIndex index, const Type& refined_type) {
          RefineOperationType(new_block, index, refined_type,
                              then_branch ? 'T' : 'F');
        });
    // Inspect branch condition.
    const Operation& condition = graph_.Get(branch->condition());
    refinements.RefineTypes(condition, then_branch, graph_zone_);
  }
References v8::internal::compiler::turboshaft::BranchOp::condition(), v8::internal::compiler::turboshaft::Graph::Get(), GetType(), graph_, graph_zone_, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::Graph::Index(), v8::internal::index, RefineOperationType(), v8::internal::compiler::turboshaft::Operation::ToString(), and TURBOSHAFT_TRACE_TYPING_OK.
Referenced by ProcessBlock().
Run()
GrowingOpIndexSidetable<Type> v8::internal::compiler::turboshaft::TypeInferenceAnalysis::Run (GrowingBlockSidetable< std::vector< std::pair< OpIndex, Type >>> * block_refinements = nullptr) [inline]
Definition at line 53 of file type-inference-analysis.h.
                                       {
#ifdef DEBUG
    block_refinements_ = block_refinements;
#endif // DEBUG
    TURBOSHAFT_TRACE_TYPING("=== Running Type Inference Analysis ===\n");
    for (uint32_t unprocessed_index = 0;
         unprocessed_index < graph_.block_count();) {
      BlockIndex block_index = static_cast<BlockIndex>(unprocessed_index);
      ++unprocessed_index;
      const Block& block = graph_.Get(block_index);
#ifdef DEBUG
      if (V8_UNLIKELY(v8_flags.turboshaft_trace_typing)) {
        std::stringstream os;
        os << block.kind() << " " << block.index().id();
        TURBOSHAFT_TRACE_TYPING("=== %s ===\n", os.str().c_str());
      }
#endif // DEBUG
      ProcessBlock<false>(block, &unprocessed_index);
    }
    TURBOSHAFT_TRACE_TYPING("=== Completed Type Inference Analysis ===\n");
    return std::move(types_);
  }
References v8::internal::compiler::turboshaft::Graph::block_count(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::BlockIndex::id(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Block::kind(), TURBOSHAFT_TRACE_TYPING, types_, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::compiler::turboshaft::TypeInferenceReducer< Next >::Analyze().
SetType()
void v8::internal::compiler::turboshaft::TypeInferenceAnalysis::SetType (OpIndex index, Type result_type, bool allow_narrowing = false, bool is_fallback_for_unsupported_operation = false) [inline]
Definition at line 451 of file type-inference-analysis.h.
                                                                   {
    DCHECK(!result_type.IsInvalid());
    if (auto key_opt = op_to_key_mapping_[index]) {
      table_.Set(*key_opt, result_type);
      types_[index] = result_type;
    } else {
      auto key = table_.NewKey(Type::None());
      op_to_key_mapping_[index] = key;
      table_.Set(key, result_type);
      types_[index] = result_type;
    }
    if (!is_fallback_for_unsupported_operation) {
      TURBOSHAFT_TRACE_TYPING_OK(
          "Type %3d:%-40s ==> %s\n", index.id(),
          graph_.Get(index).ToString().substr(0, 40).c_str(),
          result_type.ToString().c_str());
    } else {
      // TODO(nicohartmann@): Remove the fallback case once all operations are
      // supported.
      TURBOSHAFT_TRACE_TYPING_FAIL(
          "TODO %3d:%-40s ==> %s\n", index.id(),
          graph_.Get(index).ToString().substr(0, 40).c_str(),
          result_type.ToString().c_str());
    }
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::index, v8::internal::compiler::turboshaft::Type::IsInvalid(), v8::internal::key, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::NewKey(), v8::internal::compiler::turboshaft::Type::None(), op_to_key_mapping_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Set(), table_, v8::internal::compiler::turboshaft::Operation::ToString(), v8::internal::compiler::turboshaft::Type::ToString(), TURBOSHAFT_TRACE_TYPING_FAIL, TURBOSHAFT_TRACE_TYPING_OK, and types_.
Referenced by ProcessBlock(), ProcessComparison(), ProcessConstant(), ProcessFloatBinop(), ProcessLoopPhi(), ProcessOverflowCheckedBinop(), ProcessPhi(), ProcessProjection(), and ProcessWordBinop().
Widen()
Type v8::internal::compiler::turboshaft::TypeInferenceAnalysis::Widen (const Type & old_type, const Type & new_type) [inline]
Definition at line 504 of file type-inference-analysis.h.
                                                         {
    if (new_type.IsAny()) return new_type;
    // We might have to relax this eventually and widen different types.
    DCHECK_EQ(old_type.kind(), new_type.kind());
    switch (old_type.kind()) {
      case Type::Kind::kWord32:
        // TODO(nicohartmann@): Reevaluate whether exponential widening is
        // better here.
        //
        // return WordOperationTyper<32>::WidenExponential(old_type.AsWord32(),
        // new_type.AsWord32(), graph_zone_);
        return WordOperationTyper<32>::WidenMaximal(
            old_type.AsWord32(), new_type.AsWord32(), graph_zone_);
      case Type::Kind::kWord64:
        // TODO(nicohartmann@): Reevaluate whether exponential widening is
        // better here.
        //
        // return WordOperationTyper<64>::WidenExponential(old_type.AsWord64(),
        // new_type.AsWord64(), graph_zone_);
        return WordOperationTyper<64>::WidenMaximal(
            old_type.AsWord64(), new_type.AsWord64(), graph_zone_);
      case Type::Kind::kFloat32:
        // TODO(nicohartmann@): Implement proper widening.
        return Float32Type::Any();
      case Type::Kind::kFloat64:
        // TODO(nicohartmann@): Implement proper widening.
        return Float64Type::Any();
      default:
        // TODO(nicohartmann@): Handle remaining cases.
        UNREACHABLE();
    }
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::turboshaft::Type::AsWord32(), v8::internal::compiler::turboshaft::Type::AsWord64(), DCHECK_EQ, graph_zone_, v8::internal::compiler::turboshaft::Type::IsAny(), v8::internal::compiler::turboshaft::Type::kFloat32, v8::internal::compiler::turboshaft::Type::kFloat64, v8::internal::compiler::turboshaft::Type::kind(), v8::internal::compiler::turboshaft::Type::kWord32, v8::internal::compiler::turboshaft::Type::kWord64, v8::internal::UNREACHABLE(), and v8::internal::compiler::turboshaft::WordOperationTyper< Bits >::WidenMaximal().
Referenced by ProcessLoopPhi().
Member Data Documentation
block_to_snapshot_mapping_
GrowingBlockSidetable<std::optional<table_t::Snapshot> > v8::internal::compiler::turboshaft::TypeInferenceAnalysis::block_to_snapshot_mapping_ [private]
Definition at line 546 of file type-inference-analysis.h.
Referenced by ProcessBlock().
current_block_
const Block* v8::internal::compiler::turboshaft::TypeInferenceAnalysis::current_block_ = nullptr [private]
Definition at line 543 of file type-inference-analysis.h.
Referenced by ProcessBlock().
graph_
const Graph& v8::internal::compiler::turboshaft::TypeInferenceAnalysis::graph_ [private]
Definition at line 539 of file type-inference-analysis.h.
Referenced by GetType(), ProcessBlock(), ProcessCheckTurboshaftTypeOf(), ProcessLoopPhi(), RefineOperationType(), RefineTypesAfterBranch(), Run(), and SetType().
graph_zone_
Zone* v8::internal::compiler::turboshaft::TypeInferenceAnalysis::graph_zone_ [private]
Definition at line 550 of file type-inference-analysis.h.
Referenced by ComputeTypeForPhi(), GetType(), ProcessBlock(), ProcessComparison(), ProcessFloatBinop(), ProcessOverflowCheckedBinop(), ProcessWordBinop(), RefineTypesAfterBranch(), and Widen().
op_to_key_mapping_
GrowingOpIndexSidetable<std::optional<table_t::Key> > v8::internal::compiler::turboshaft::TypeInferenceAnalysis::op_to_key_mapping_ [private]
Definition at line 544 of file type-inference-analysis.h.
Referenced by GetTypeOrInvalid(), RefineOperationType(), and SetType().
predecessors_
ZoneVector<table_t::Snapshot> v8::internal::compiler::turboshaft::TypeInferenceAnalysis::predecessors_ [private]
Definition at line 549 of file type-inference-analysis.h.
Referenced by ProcessBlock().
table_
table_t v8::internal::compiler::turboshaft::TypeInferenceAnalysis::table_ [private]
Definition at line 542 of file type-inference-analysis.h.
Referenced by GetTypeOrInvalid(), ProcessBlock(), RefineOperationType(), and SetType().
types_
GrowingOpIndexSidetable<Type> v8::internal::compiler::turboshaft::TypeInferenceAnalysis::types_ [private]
Definition at line 540 of file type-inference-analysis.h.
Referenced by GetTypeAtDefinition(), Run(), and SetType().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/type-inference-analysis.h