v8::internal::SmallOrderedHashTable< Derived > Class Template Reference
#include <ordered-hash-table.h>
Public Types
using Offset = int
using ByteIndex = int
Public Member Functions
void Initialize (Isolate *isolate, int capacity)
bool HasKey (Isolate *isolate, DirectHandle< Object > key)
InternalIndex FindEntry (Isolate *isolate, Tagged< Object > key)
int Capacity () const
int NumberOfElements () const
int NumberOfDeletedElements () const
int NumberOfBuckets () const
Tagged< Object > KeyAt (InternalIndex entry) const
InternalIndex::Range IterateEntries ()
Handle< SmallOrderedHashSet > Allocate (Isolate *isolate, int capacity, AllocationType allocation)
Handle< SmallOrderedHashMap > Allocate (Isolate *isolate, int capacity, AllocationType allocation)
Handle< SmallOrderedNameDictionary > Allocate (Isolate *isolate, int capacity, AllocationType allocation)
InternalIndex V8_EXPORT_PRIVATE FindEntry (Isolate *isolate, Tagged< Object > key)
Static Public Member Functions
static Handle< Derived > Allocate (Isolate *isolate, int capacity, AllocationType allocation=AllocationType::kYoung)
static bool Delete (Isolate *isolate, Tagged< Derived > table, Tagged< Object > key)
static MaybeHandle< Derived > Grow (Isolate *isolate, Handle< Derived > table)
static Handle< Derived > Shrink (Isolate *isolate, Handle< Derived > table)
static int SizeFor (int capacity)
Static Public Attributes
static const int kMinCapacity = 4
static const uint8_t kNotFound = 0xFF
static const int kMaxCapacity = 254
static const int kLoadFactor = 2
static const int kGrowthHack = 256
Protected Member Functions
void SetDataEntry (int entry, int relative_index, Tagged< Object > value)
Offset GetBucketsStartOffset () const
Address GetHashTableStartAddress (int capacity) const
void SetFirstEntry (int bucket, uint8_t value)
int GetFirstEntry (int bucket) const
Offset GetChainTableOffset () const
void SetNextEntry (int entry, int next_entry)
int GetNextEntry (int entry) const
Tagged< Object > GetDataEntry (int entry, int relative_index)
int HashToBucket (int hash) const
int HashToFirstEntry (int hash) const
void SetNumberOfBuckets (int num)
void SetNumberOfElements (int num)
void SetNumberOfDeletedElements (int num)
uint8_t getByte (Offset offset, ByteIndex index) const
void setByte (Offset offset, ByteIndex index, uint8_t value)
Offset GetDataEntryOffset (int entry, int relative_index) const
int UsedCapacity () const
Static Protected Member Functions
static Handle< Derived > Rehash (Isolate *isolate, Handle< Derived > table, int new_capacity)
static constexpr Offset PrefixOffset ()
static constexpr Offset NumberOfElementsOffset ()
static constexpr Offset NumberOfDeletedElementsOffset ()
static constexpr Offset NumberOfBucketsOffset ()
static constexpr Offset PaddingOffset ()
static constexpr size_t PaddingSize ()
static constexpr Offset DataTableStartOffset ()
static constexpr int DataTableSizeFor (int capacity)
Private Member Functions
OBJECT_CONSTRUCTORS (SmallOrderedHashTable, HeapObject)
Friends
class OrderedHashMapHandler
class OrderedHashSetHandler
class OrderedNameDictionaryHandler
class CodeStubAssembler
Detailed Description
template<class Derived>
class v8::internal::SmallOrderedHashTable< Derived >
Definition at line 418 of file ordered-hash-table.h.
Member Typedef Documentation
ByteIndex
template<class Derived >
using v8::internal::SmallOrderedHashTable< Derived >::ByteIndex = int
Definition at line 425 of file ordered-hash-table.h.
Offset
template<class Derived >
using v8::internal::SmallOrderedHashTable< Derived >::Offset = int
Definition at line 421 of file ordered-hash-table.h.
Member Function Documentation
Allocate() [1/4]
Handle< SmallOrderedHashSet > v8::internal::SmallOrderedHashTable< SmallOrderedHashSet >::Allocate (Isolate * isolate, int capacity, AllocationType allocation)
Definition at line 664 of file ordered-hash-table.cc.
                                                               {
  return isolate->factory()->NewSmallOrderedHashSet(capacity, allocation);
}
References v8::internal::Isolate::factory(), and v8::internal::Factory::NewSmallOrderedHashSet().
Allocate() [2/4]
Handle< SmallOrderedHashMap > v8::internal::SmallOrderedHashTable< SmallOrderedHashMap >::Allocate (Isolate * isolate, int capacity, AllocationType allocation)
Definition at line 671 of file ordered-hash-table.cc.
                                                               {
  return isolate->factory()->NewSmallOrderedHashMap(capacity, allocation);
}
References v8::internal::Isolate::factory(), and v8::internal::Factory::NewSmallOrderedHashMap().
Allocate() [3/4]
Handle< SmallOrderedNameDictionary > v8::internal::SmallOrderedHashTable< SmallOrderedNameDictionary >::Allocate (Isolate * isolate, int capacity, AllocationType allocation)
Definition at line 678 of file ordered-hash-table.cc.
                                                               {
  return isolate->factory()->NewSmallOrderedNameDictionary(capacity,
                                                           allocation);
}
References v8::internal::Isolate::factory(), and v8::internal::Factory::NewSmallOrderedNameDictionary().
Allocate() [4/4]
template<class Derived >
static Handle<Derived> v8::internal::SmallOrderedHashTable< Derived >::Allocate (Isolate * isolate, int capacity, AllocationType allocation = AllocationType::kYoung) [static]
Capacity()
template<class Derived >
int v8::internal::SmallOrderedHashTable< Derived >::Capacity () const [inline]
Definition at line 468 of file ordered-hash-table.h.
                       {
    int capacity = NumberOfBuckets() * kLoadFactor;
    DCHECK_GE(capacity, kMinCapacity);
    DCHECK_LE(capacity, kMaxCapacity);
    return capacity;
  }
References DCHECK_GE, and DCHECK_LE.
DataTableSizeFor()
template<class Derived >
static constexpr int v8::internal::SmallOrderedHashTable< Derived >::DataTableSizeFor (int capacity) [inline], [static], [constexpr], [protected]
Definition at line 625 of file ordered-hash-table.h.
                                                      {
    return capacity * Derived::kEntrySize * kTaggedSize;
  }
References cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, and v8::internal::kTaggedSize.
DataTableStartOffset()
template<class Derived >
static constexpr Offset v8::internal::SmallOrderedHashTable< Derived >::DataTableStartOffset () [inline], [static], [constexpr], [protected]
Definition at line 621 of file ordered-hash-table.h.
                                                 {
    return PaddingOffset() + PaddingSize();
  }
Delete()
template<class Derived >
template V8_EXPORT_PRIVATE bool v8::internal::SmallOrderedHashTable< Derived >::Delete (Isolate * isolate, Tagged< Derived > table, Tagged< Object > key) [static]
FindEntry() [1/2]
InternalIndex V8_EXPORT_PRIVATE v8::internal::SmallOrderedHashTable< SmallOrderedNameDictionary >::FindEntry (Isolate * isolate, Tagged< Object > key)
Definition at line 816 of file ordered-hash-table.cc.
                                          {
  DisallowGarbageCollection no_gc;
  DCHECK(IsUniqueName(key));
  Tagged<Name> raw_key = Cast<Name>(key);
  int raw_entry = HashToFirstEntry(raw_key->hash());
  // Walk the chain in the bucket to find the key.
  while (raw_entry != kNotFound) {
    InternalIndex entry(raw_entry);
    Tagged<Object> candidate_key = KeyAt(entry);
    if (candidate_key == key) return entry;
    raw_entry = GetNextEntry(raw_entry);
  }
  return InternalIndex::NotFound();
}
References DCHECK, v8::internal::IsUniqueName(), v8::internal::key, v8::internal::kNotFound, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
FindEntry() [2/2]
template<class Derived >
InternalIndex v8::internal::SmallOrderedHashTable< Derived >::FindEntry (Isolate * isolate, Tagged< Object > key)
GetBucketsStartOffset()
template<class Derived >
Offset v8::internal::SmallOrderedHashTable< Derived >::GetBucketsStartOffset () const [inline], [protected]
Definition at line 532 of file ordered-hash-table.h.
                                       {
    int capacity = Capacity();
    int data_table_size = DataTableSizeFor(capacity);
    return DataTableStartOffset() + data_table_size;
  }
getByte()
template<class Derived >
uint8_t v8::internal::SmallOrderedHashTable< Derived >::getByte (Offset offset, ByteIndex index) const [inline], [protected]
Definition at line 631 of file ordered-hash-table.h.
                                                        {
    DCHECK(offset < DataTableStartOffset() ||
           offset >= GetBucketsStartOffset());
    return ReadField<uint8_t>(offset + (index * kOneByteSize));
  }
References v8::internal::DCHECK(), v8::internal::index, and v8::internal::kOneByteSize.
GetChainTableOffset()
template<class Derived >
Offset v8::internal::SmallOrderedHashTable< Derived >::GetChainTableOffset () const [inline], [protected]
Definition at line 554 of file ordered-hash-table.h.
                                     {
    int nof_buckets = NumberOfBuckets();
    int capacity = nof_buckets * kLoadFactor;
    DCHECK_EQ(Capacity(), capacity);
    int data_table_size = DataTableSizeFor(capacity);
    int hash_table_size = nof_buckets;
    return DataTableStartOffset() + data_table_size + hash_table_size;
  }
References DCHECK_EQ.
GetDataEntry()
template<class Derived >
Tagged<Object> v8::internal::SmallOrderedHashTable< Derived >::GetDataEntry (int entry, int relative_index) [inline], [protected]
GetDataEntryOffset()
template<class Derived >
Offset v8::internal::SmallOrderedHashTable< Derived >::GetDataEntryOffset (int entry, int relative_index) const [inline], [protected]
Definition at line 643 of file ordered-hash-table.h.
                                                                 {
    DCHECK_LT(entry, Capacity());
    int offset_in_datatable = entry * Derived::kEntrySize * kTaggedSize;
    int offset_in_entry = relative_index * kTaggedSize;
    return DataTableStartOffset() + offset_in_datatable + offset_in_entry;
  }
References DCHECK_LT, cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, and v8::internal::kTaggedSize.
GetFirstEntry()
template<class Derived >
int v8::internal::SmallOrderedHashTable< Derived >::GetFirstEntry (int bucket) const [inline], [protected]
Definition at line 547 of file ordered-hash-table.h.
                                      {
    DCHECK_LE(static_cast<unsigned>(bucket), NumberOfBuckets());
    return getByte(GetBucketsStartOffset(), bucket);
  }
References DCHECK_LE.
GetHashTableStartAddress()
template<class Derived >
Address v8::internal::SmallOrderedHashTable< Derived >::GetHashTableStartAddress (int capacity) const [inline], [protected]
Definition at line 538 of file ordered-hash-table.h.
                                                       {
    return field_address(DataTableStartOffset() + DataTableSizeFor(capacity));
  }
GetNextEntry()
template<class Derived >
int v8::internal::SmallOrderedHashTable< Derived >::GetNextEntry (int entry) const [inline], [protected]
Definition at line 571 of file ordered-hash-table.h.
                                    {
    DCHECK_LT(entry, Capacity());
    return getByte(GetChainTableOffset(), entry);
  }
References DCHECK_LT.
Grow()
template<class Derived >
template V8_EXPORT_PRIVATE MaybeHandle< SmallOrderedHashMap > v8::internal::SmallOrderedHashTable< Derived >::Grow (Isolate * isolate, Handle< Derived > table) [static]
HashToBucket()
template<class Derived >
int v8::internal::SmallOrderedHashTable< Derived >::HashToBucket (int hash) const [inline], [protected]
Definition at line 578 of file ordered-hash-table.h.
{ return hash & (NumberOfBuckets() - 1); }
HashToFirstEntry()
template<class Derived >
int v8::internal::SmallOrderedHashTable< Derived >::HashToFirstEntry (int hash) const [inline], [protected]
Definition at line 580 of file ordered-hash-table.h.
                                       {
    int bucket = HashToBucket(hash);
    int entry = GetFirstEntry(bucket);
    DCHECK(entry < Capacity() || entry == kNotFound);
    return entry;
  }
References v8::internal::DCHECK(), and v8::internal::kNotFound.
HasKey()
template<class Derived >
template V8_EXPORT_PRIVATE bool v8::internal::SmallOrderedHashTable< Derived >::HasKey (Isolate * isolate, DirectHandle< Object > key)
Initialize()
template<class Derived >
template V8_EXPORT_PRIVATE void v8::internal::SmallOrderedHashTable< Derived >::Initialize (Isolate * isolate, int capacity)
IterateEntries()
template<class Derived >
InternalIndex::Range v8::internal::SmallOrderedHashTable< Derived >::IterateEntries () [inline]
Definition at line 495 of file ordered-hash-table.h.
                                      {
    return InternalIndex::Range(UsedCapacity());
  }
References v8::internal::compiler::turboshaft::Range().
KeyAt()
template<class Derived >
Tagged<Object> v8::internal::SmallOrderedHashTable< Derived >::KeyAt (InternalIndex entry) const [inline]
NumberOfBuckets()
template<class Derived >
int v8::internal::SmallOrderedHashTable< Derived >::NumberOfBuckets () const [inline]
Definition at line 491 of file ordered-hash-table.h.
{ return getByte(NumberOfBucketsOffset(), 0); }
NumberOfBucketsOffset()
template<class Derived >
static constexpr Offset v8::internal::SmallOrderedHashTable< Derived >::NumberOfBucketsOffset () [inline], [static], [constexpr], [protected]
Definition at line 609 of file ordered-hash-table.h.
                                                  {
    return NumberOfDeletedElementsOffset() + kOneByteSize;
  }
References v8::internal::kOneByteSize.
NumberOfDeletedElements()
template<class Derived >
int v8::internal::SmallOrderedHashTable< Derived >::NumberOfDeletedElements () const [inline]
Definition at line 484 of file ordered-hash-table.h.
                                      {
    int nof_deleted_elements = getByte(NumberOfDeletedElementsOffset(), 0);
    DCHECK_LE(nof_deleted_elements, Capacity());
    return nof_deleted_elements;
  }
References DCHECK_LE.
NumberOfDeletedElementsOffset()
template<class Derived >
static constexpr Offset v8::internal::SmallOrderedHashTable< Derived >::NumberOfDeletedElementsOffset () [inline], [static], [constexpr], [protected]
Definition at line 605 of file ordered-hash-table.h.
                                                          {
    return NumberOfElementsOffset() + kOneByteSize;
  }
References v8::internal::kOneByteSize.
NumberOfElements()
template<class Derived >
int v8::internal::SmallOrderedHashTable< Derived >::NumberOfElements () const [inline]
Definition at line 477 of file ordered-hash-table.h.
                               {
    int nof_elements = getByte(NumberOfElementsOffset(), 0);
    DCHECK_LE(nof_elements, Capacity());
    return nof_elements;
  }
References DCHECK_LE.
NumberOfElementsOffset()
template<class Derived >
static constexpr Offset v8::internal::SmallOrderedHashTable< Derived >::NumberOfElementsOffset () [inline], [static], [constexpr], [protected]
Definition at line 601 of file ordered-hash-table.h.
                                                   {
    return PrefixOffset() + (Derived::kPrefixSize * kTaggedSize);
  }
References v8::internal::kTaggedSize.
OBJECT_CONSTRUCTORS()
template<class Derived >
v8::internal::SmallOrderedHashTable< Derived >::OBJECT_CONSTRUCTORS (SmallOrderedHashTable< Derived > , HeapObject) [private]
PaddingOffset()
template<class Derived >
static constexpr Offset v8::internal::SmallOrderedHashTable< Derived >::PaddingOffset () [inline], [static], [constexpr], [protected]
Definition at line 613 of file ordered-hash-table.h.
                                          {
    return NumberOfBucketsOffset() + kOneByteSize;
  }
References v8::internal::kOneByteSize.
PaddingSize()
template<class Derived >
static constexpr size_t v8::internal::SmallOrderedHashTable< Derived >::PaddingSize () [inline], [static], [constexpr], [protected]
Definition at line 617 of file ordered-hash-table.h.
                                        {
    return RoundUp<kTaggedSize>(PaddingOffset()) - PaddingOffset();
  }
PrefixOffset()
template<class Derived >
static constexpr Offset v8::internal::SmallOrderedHashTable< Derived >::PrefixOffset () [inline], [static], [constexpr], [protected]
Definition at line 599 of file ordered-hash-table.h.
{ return kHeaderSize; }
Rehash()
template<class Derived >
template V8_EXPORT_PRIVATE Handle< SmallOrderedHashMap > v8::internal::SmallOrderedHashTable< Derived >::Rehash (Isolate * isolate, Handle< Derived > table, int new_capacity) [static], [protected]
setByte()
template<class Derived >
void v8::internal::SmallOrderedHashTable< Derived >::setByte (Offset offset, ByteIndex index, uint8_t value) [inline], [protected]
Definition at line 637 of file ordered-hash-table.h.
                                                              {
    DCHECK(offset < DataTableStartOffset() ||
           offset >= GetBucketsStartOffset());
    WriteField<uint8_t>(offset + (index * kOneByteSize), value);
  }
References v8::internal::DCHECK(), v8::internal::index, v8::internal::kOneByteSize, and v8::internal::value.
SetDataEntry()
template<class Derived >
void v8::internal::SmallOrderedHashTable< Derived >::SetDataEntry (int entry, int relative_index, Tagged< Object > value) [protected]
SetFirstEntry()
template<class Derived >
void v8::internal::SmallOrderedHashTable< Derived >::SetFirstEntry (int bucket, uint8_t value) [inline], [protected]
Definition at line 542 of file ordered-hash-table.h.
                                                {
    DCHECK_LE(static_cast<unsigned>(bucket), NumberOfBuckets());
    setByte(GetBucketsStartOffset(), bucket, value);
  }
References DCHECK_LE, and v8::internal::value.
SetNextEntry()
template<class Derived >
void v8::internal::SmallOrderedHashTable< Derived >::SetNextEntry (int entry, int next_entry) [inline], [protected]
Definition at line 564 of file ordered-hash-table.h.
                                               {
    DCHECK_LT(static_cast<unsigned>(entry), Capacity());
    DCHECK_GE(static_cast<unsigned>(next_entry), 0);
    DCHECK(next_entry <= Capacity() || next_entry == kNotFound);
    setByte(GetChainTableOffset(), entry, next_entry);
  }
References v8::internal::DCHECK(), DCHECK_GE, DCHECK_LT, and v8::internal::kNotFound.
SetNumberOfBuckets()
template<class Derived >
void v8::internal::SmallOrderedHashTable< Derived >::SetNumberOfBuckets (int num) [inline], [protected]
Definition at line 587 of file ordered-hash-table.h.
{ setByte(NumberOfBucketsOffset(), 0, num); }
SetNumberOfDeletedElements()
template<class Derived >
void v8::internal::SmallOrderedHashTable< Derived >::SetNumberOfDeletedElements (int num) [inline], [protected]
Definition at line 594 of file ordered-hash-table.h.
                                           {
    DCHECK_LE(static_cast<unsigned>(num), Capacity());
    setByte(NumberOfDeletedElementsOffset(), 0, num);
  }
References DCHECK_LE.
SetNumberOfElements()
template<class Derived >
void v8::internal::SmallOrderedHashTable< Derived >::SetNumberOfElements (int num) [inline], [protected]
Definition at line 589 of file ordered-hash-table.h.
                                    {
    DCHECK_LE(static_cast<unsigned>(num), Capacity());
    setByte(NumberOfElementsOffset(), 0, num);
  }
References DCHECK_LE.
Shrink()
template<class Derived >
template V8_EXPORT_PRIVATE Handle< SmallOrderedNameDictionary > v8::internal::SmallOrderedHashTable< Derived >::Shrink (Isolate * isolate, Handle< Derived > table) [static]
SizeFor()
template<class Derived >
static int v8::internal::SmallOrderedHashTable< Derived >::SizeFor (int capacity) [inline], [static]
Definition at line 454 of file ordered-hash-table.h.
                                   {
    DCHECK_GE(capacity, kMinCapacity);
    DCHECK_LE(capacity, kMaxCapacity);
    int data_table_size = DataTableSizeFor(capacity);
    int hash_table_size = capacity / kLoadFactor;
    int chain_table_size = capacity;
    int total_size = DataTableStartOffset() + data_table_size +
                     hash_table_size + chain_table_size;
    return RoundUp(total_size, kTaggedSize);
  }
References DCHECK_GE, DCHECK_LE, v8::internal::kTaggedSize, and RoundUp().
UsedCapacity()
template<class Derived >
int v8::internal::SmallOrderedHashTable< Derived >::UsedCapacity () const [inline], [protected]
Definition at line 650 of file ordered-hash-table.h.
                           {
    int used = NumberOfElements() + NumberOfDeletedElements();
    DCHECK_LE(used, Capacity());
    return used;
  }
References DCHECK_LE.
Friends And Related Function Documentation
CodeStubAssembler
template<class Derived >
friend class CodeStubAssembler [friend]
Definition at line 661 of file ordered-hash-table.h.
OrderedHashMapHandler
template<class Derived >
friend class OrderedHashMapHandler [friend]
Definition at line 658 of file ordered-hash-table.h.
OrderedHashSetHandler
template<class Derived >
friend class OrderedHashSetHandler [friend]
Definition at line 659 of file ordered-hash-table.h.
OrderedNameDictionaryHandler
template<class Derived >
friend class OrderedNameDictionaryHandler [friend]
Definition at line 660 of file ordered-hash-table.h.
Member Data Documentation
kGrowthHack
template<class Derived >
const int v8::internal::SmallOrderedHashTable< Derived >::kGrowthHack = 256 [static]
Definition at line 522 of file ordered-hash-table.h.
kLoadFactor
template<class Derived >
const int v8::internal::SmallOrderedHashTable< Derived >::kLoadFactor = 2 [static]
Definition at line 515 of file ordered-hash-table.h.
kMaxCapacity
template<class Derived >
const int v8::internal::SmallOrderedHashTable< Derived >::kMaxCapacity = 254 [static]
Definition at line 507 of file ordered-hash-table.h.
kMinCapacity
template<class Derived >
const int v8::internal::SmallOrderedHashTable< Derived >::kMinCapacity = 4 [static]
Definition at line 501 of file ordered-hash-table.h.
kNotFound
template<class Derived >
const uint8_t v8::internal::SmallOrderedHashTable< Derived >::kNotFound = 0xFF [static]
Definition at line 502 of file ordered-hash-table.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/ordered-hash-table.h
/mnt/V8SourceCode/src/objects/ordered-hash-table.cc