v8::internal::LargeObjectSpace Class Reference
#include <large-spaces.h>
Public Types
using iterator = LargePageIterator
using const_iterator = ConstLargePageIterator
Public Member Functions
~LargeObjectSpace () override
void TearDown ()
size_t Available () const override
size_t Size () const override
size_t SizeOfObjects () const override
size_t CommittedPhysicalMemory () const override
int PageCount () const
void ShrinkPageToObjectSize (LargePageMetadata *page, Tagged< HeapObject > object, size_t object_size)
bool Contains (Tagged< HeapObject > obj) const
bool ContainsSlow (Address addr) const
bool IsEmpty () const
virtual void AddPage (LargePageMetadata *page, size_t object_size)
virtual void RemovePage (LargePageMetadata *page)
LargePageMetadata * first_page () override
const LargePageMetadata * first_page () const override
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
std::unique_ptr< ObjectIterator > GetObjectIterator (Heap *heap) override
void AddAllocationObserver (AllocationObserver *observer)
void RemoveAllocationObserver (AllocationObserver *observer)
Address pending_object () const
void ResetPendingObject ()
base::Mutex * pending_allocation_mutex ()
void UpdateAccountingAfterResizingObject (size_t old_size, size_t new_size)
void set_objects_size (size_t objects_size)
Protected Member Functions
LargeObjectSpace (Heap *heap, AllocationSpace id)
void AdvanceAndInvokeAllocationObservers (Address soon_object, size_t size)
LargePageMetadata * AllocateLargePage (int object_size, Executability executable, AllocationHint hint)
void UpdatePendingObject (Tagged< HeapObject > object)
Protected Attributes
std::atomic< size_t > size_
int page_count_
std::atomic< size_t > objects_size_
base::RecursiveMutex allocation_mutex_
std::atomic< Address > pending_object_
base::Mutex pending_allocation_mutex_
AllocationCounter allocation_counter_
Friends
class LargeObjectSpaceObjectIterator
Additional Inherited Members
Detailed Description
Definition at line 33 of file large-spaces.h.
Member Typedef Documentation
const_iterator
using v8::internal::LargeObjectSpace::const_iterator = ConstLargePageIterator
Definition at line 36 of file large-spaces.h.
iterator
using v8::internal::LargeObjectSpace::iterator = LargePageIterator
Definition at line 35 of file large-spaces.h.
Constructor & Destructor Documentation
 LargeObjectSpace()
v8::internal::LargeObjectSpace::~LargeObjectSpace () [inline], [override]
Definition at line 38 of file large-spaces.h.
{ TearDown(); }
LargeObjectSpace()
v8::internal::LargeObjectSpace::LargeObjectSpace (Heap * heap, AllocationSpace id) [protected]
Definition at line 53 of file large-spaces.cc.
    : Space(heap, id, nullptr),
      size_(0),
      page_count_(0),
      objects_size_(0),
      pending_object_(0) {}
Member Function Documentation
AddAllocationObserver()
void v8::internal::LargeObjectSpace::AddAllocationObserver (AllocationObserver * observer)
Definition at line 94 of file large-spaces.cc.
                                                                         {
  allocation_counter_.AddAllocationObserver(observer);
}
References v8::internal::AllocationCounter::AddAllocationObserver(), and allocation_counter_.
Referenced by v8::internal::HeapAllocator::AddAllocationObserver().
AddPage()
void v8::internal::LargeObjectSpace::AddPage (LargePageMetadata * page, size_t object_size) [virtual]
Reimplemented in v8::internal::CodeLargeObjectSpace.
Definition at line 196 of file large-spaces.cc.
                                                                          {
  size_ += static_cast<int>(page->size());
  AccountCommitted(page->size());
  objects_size_ += object_size;
  page_count_++;
  memory_chunk_list_.PushBack(page);
  page->set_owner(this);
  ForAll<ExternalBackingStoreType>(
      [this, page](ExternalBackingStoreType type, int index) {
        IncrementExternalBackingStoreBytes(
            type, page->ExternalBackingStoreBytes(type));
      });
}
References v8::internal::BaseSpace::AccountCommitted(), v8::internal::MutablePageMetadata::ExternalBackingStoreBytes(), v8::internal::Space::IncrementExternalBackingStoreBytes(), v8::internal::index, v8::internal::Space::memory_chunk_list_, objects_size_, page_count_, v8::internal::MemoryChunkMetadata::set_owner(), v8::internal::MemoryChunkMetadata::size(), size_, and v8::internal::tracing::type.
Referenced by v8::internal::CodeLargeObjectSpace::AddPage(), AllocateLargePage(), and v8::internal::OldLargeObjectSpace::PromoteNewLargeObject().
AdvanceAndInvokeAllocationObservers()
void v8::internal::LargeObjectSpace::AdvanceAndInvokeAllocationObservers (Address soon_object, size_t size) [protected]
Definition at line 78 of file large-spaces.cc.
                                                                               {
  if (!heap()->IsAllocationObserverActive()) return;
  if (object_size >= allocation_counter_.NextBytes()) {
    // Ensure that there is a valid object
    heap_->CreateFillerObjectAt(soon_object, static_cast<int>(object_size));
    allocation_counter_.InvokeAllocationObservers(soon_object, object_size,
                                                  object_size);
  }
  // Large objects can be accounted immediately since no LAB is involved.
  allocation_counter_.AdvanceAllocationObservers(object_size);
}
References v8::internal::AllocationCounter::AdvanceAllocationObservers(), allocation_counter_, v8::internal::Heap::CreateFillerObjectAt(), v8::internal::BaseSpace::heap(), v8::internal::BaseSpace::heap_, v8::internal::AllocationCounter::InvokeAllocationObservers(), and v8::internal::AllocationCounter::NextBytes().
Referenced by v8::internal::NewLargeObjectSpace::AllocateRaw(), and v8::internal::OldLargeObjectSpace::AllocateRaw().
AllocateLargePage()
LargePageMetadata * v8::internal::LargeObjectSpace::AllocateLargePage (int object_size, Executability executable, AllocationHint hint) [protected]
Definition at line 152 of file large-spaces.cc.
                                                                            {
  base::MutexGuard expansion_guard(heap_->heap_expansion_mutex());
  if (identity() != NEW_LO_SPACE &&
      !heap()->IsOldGenerationExpansionAllowed(object_size, expansion_guard)) {
    return nullptr;
  }
  LargePageMetadata* page = heap()->memory_allocator()->AllocateLargePage(
      this, object_size, executable, hint);
  if (page == nullptr) return nullptr;
  DCHECK_GE(page->area_size(), static_cast<size_t>(object_size));
  {
    base::RecursiveMutexGuard guard(&allocation_mutex_);
    AddPage(page, object_size);
  }
  return page;
}
References AddPage(), v8::internal::MemoryAllocator::AllocateLargePage(), allocation_mutex_, v8::internal::MemoryChunkMetadata::area_size(), DCHECK_GE, v8::internal::BaseSpace::heap(), v8::internal::BaseSpace::heap_, v8::internal::Heap::heap_expansion_mutex(), v8::internal::BaseSpace::identity(), v8::internal::Heap::memory_allocator(), and v8::internal::NEW_LO_SPACE.
Referenced by v8::internal::NewLargeObjectSpace::AllocateRaw(), and v8::internal::OldLargeObjectSpace::AllocateRaw().
Available()
size_t v8::internal::LargeObjectSpace::Available () const [override], [virtual]
Implements v8::internal::Space.
Reimplemented in v8::internal::NewLargeObjectSpace.
Definition at line 60 of file large-spaces.cc.
                                         {
  // We return zero here since we cannot take advantage of already allocated
  // large object memory.
  return 0;
}
Referenced by v8::internal::Heap::PrintShortHeapStatistics().
begin() [1/2]
iterator v8::internal::LargeObjectSpace::begin () [inline]
Definition at line 77 of file large-spaces.h.
{ return iterator(first_page()); }
Referenced by v8::internal::NewLargeObjectSpace::FreeDeadObjects(), v8::internal::OldGenerationMemoryChunkIterator::next(), and v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace().
begin() [2/2]
const_iterator v8::internal::LargeObjectSpace::begin () const [inline]
Definition at line 80 of file large-spaces.h.
{ return const_iterator(first_page()); }
CommittedPhysicalMemory()
size_t v8::internal::LargeObjectSpace::CommittedPhysicalMemory () const [override], [virtual]
Implements v8::internal::BaseSpace.
Definition at line 175 of file large-spaces.cc.
                                                       {
  // On a platform that provides lazy committing of memory, we over-account
  // the actually committed memory. There is no easy way right now to support
  // precise accounting of committed memory in large object space.
  return CommittedMemory();
}
References v8::internal::BaseSpace::CommittedMemory().
Contains()
bool v8::internal::LargeObjectSpace::Contains (Tagged< HeapObject > obj) const
Definition at line 275 of file large-spaces.cc.
                                                               {
  MemoryChunkMetadata* chunk = MemoryChunkMetadata::FromHeapObject(object);
  bool owned = (chunk->owner() == this);
  SLOW_DCHECK(!owned || ContainsSlow(object.address()));
  return owned;
}
References ContainsSlow(), v8::internal::MemoryChunkMetadata::FromHeapObject(), v8::internal::MemoryChunkMetadata::owner(), and SLOW_DCHECK.
Referenced by v8::internal::Heap::Contains(), v8::internal::Heap::ContainsCode(), v8::internal::Heap::InSpace(), and v8::internal::Heap::SharedHeapContains().
ContainsSlow()
bool v8::internal::LargeObjectSpace::ContainsSlow (Address addr) const
Definition at line 285 of file large-spaces.cc.
                                                      {
  MemoryChunk* chunk = MemoryChunk::FromAddress(addr);
  for (const LargePageMetadata* page : *this) {
    if (page->Chunk() == chunk) return true;
  }
  return false;
}
References v8::internal::MemoryChunkMetadata::Chunk(), and v8::internal::MemoryChunk::FromAddress().
Referenced by Contains(), and v8::internal::Heap::InSpaceSlow().
end() [1/2]
iterator v8::internal::LargeObjectSpace::end () [inline]
Definition at line 78 of file large-spaces.h.
{ return iterator(nullptr); }
Referenced by v8::internal::NewLargeObjectSpace::FreeDeadObjects(), v8::internal::OldGenerationMemoryChunkIterator::next(), and v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace().
end() [2/2]
const_iterator v8::internal::LargeObjectSpace::end () const [inline]
Definition at line 81 of file large-spaces.h.
{ return const_iterator(nullptr); }
first_page() [1/2]
const LargePageMetadata* v8::internal::LargeObjectSpace::first_page () const [inline], [override], [virtual]
Reimplemented from v8::internal::Space.
Definition at line 72 of file large-spaces.h.
                                                       {
    return reinterpret_cast<const LargePageMetadata*>(
        memory_chunk_list_.front());
  }
first_page() [2/2]
LargePageMetadata* v8::internal::LargeObjectSpace::first_page () [inline], [override], [virtual]
Reimplemented from v8::internal::Space.
Definition at line 69 of file large-spaces.h.
                                           {
    return reinterpret_cast<LargePageMetadata*>(memory_chunk_list_.front());
  }
Referenced by v8::internal::NewLargeObjectSpace::Flip(), and TearDown().
GetObjectIterator()
std::unique_ptr< ObjectIterator > v8::internal::LargeObjectSpace::GetObjectIterator (Heap * heap) [override], [virtual]
Implements v8::internal::Space.
Definition at line 293 of file large-spaces.cc.
                {
  return std::unique_ptr<ObjectIterator>(
      new LargeObjectSpaceObjectIterator(this));
}
References LargeObjectSpaceObjectIterator.
Referenced by v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap(), and v8::internal::anonymous_namespace{deoptimizer.cc}::DeoptimizableCodeIterator::Next().
IsEmpty()
bool v8::internal::LargeObjectSpace::IsEmpty () const [inline]
Definition at line 64 of file large-spaces.h.
{ return first_page() == nullptr; }
PageCount()
int v8::internal::LargeObjectSpace::PageCount () const [inline]
Definition at line 52 of file large-spaces.h.
{ return page_count_; }
pending_allocation_mutex()
base::Mutex* v8::internal::LargeObjectSpace::pending_allocation_mutex () [inline]
Definition at line 106 of file large-spaces.h.
{ return &pending_allocation_mutex_; }
Referenced by v8::internal::Heap::IsPendingAllocationInternal().
pending_object()
Address v8::internal::LargeObjectSpace::pending_object () const [inline]
Definition at line 98 of file large-spaces.h.
                                 {
    return pending_object_.load(std::memory_order_acquire);
  }
Referenced by v8::internal::OldLargeObjectSpace::AllocateRaw(), v8::internal::Heap::IsPendingAllocationInternal(), v8::internal::anonymous_namespace{concurrent-marking.cc}::IsYoungObjectInLab(), v8::internal::ConcurrentMarking::RunMajor(), and v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace().
RemoveAllocationObserver()
void v8::internal::LargeObjectSpace::RemoveAllocationObserver (AllocationObserver * observer)
Definition at line 98 of file large-spaces.cc.
                                                                            {
  allocation_counter_.RemoveAllocationObserver(observer);
}
References allocation_counter_, and v8::internal::AllocationCounter::RemoveAllocationObserver().
Referenced by v8::internal::HeapAllocator::RemoveAllocationObserver().
RemovePage()
void v8::internal::LargeObjectSpace::RemovePage (LargePageMetadata * page) [virtual]
Reimplemented in v8::internal::CodeLargeObjectSpace.
Definition at line 210 of file large-spaces.cc.
                                                         {
  size_ -= static_cast<int>(page->size());
  AccountUncommitted(page->size());
  page_count_--;
  memory_chunk_list_.Remove(page);
  page->set_owner(nullptr);
  ForAll<ExternalBackingStoreType>(
      [this, page](ExternalBackingStoreType type, int index) {
        DecrementExternalBackingStoreBytes(
            type, page->ExternalBackingStoreBytes(type));
      });
}
References v8::internal::BaseSpace::AccountUncommitted(), v8::internal::Space::DecrementExternalBackingStoreBytes(), v8::internal::MutablePageMetadata::ExternalBackingStoreBytes(), v8::internal::index, v8::internal::Space::memory_chunk_list_, page_count_, v8::internal::MemoryChunkMetadata::set_owner(), v8::internal::MemoryChunkMetadata::size(), size_, and v8::internal::tracing::type.
Referenced by v8::internal::NewLargeObjectSpace::FreeDeadObjects(), v8::internal::OldLargeObjectSpace::PromoteNewLargeObject(), v8::internal::CodeLargeObjectSpace::RemovePage(), and v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace().
ResetPendingObject()
void v8::internal::LargeObjectSpace::ResetPendingObject () [inline]
Definition at line 102 of file large-spaces.h.
                            {
    pending_object_.store(0, std::memory_order_release);
  }
Referenced by v8::internal::MinorMarkSweepCollector::CollectGarbage(), v8::internal::ScavengerCollector::CollectGarbage(), and v8::internal::HeapAllocator::PublishPendingAllocations().
set_objects_size()
void v8::internal::LargeObjectSpace::set_objects_size (size_t objects_size) [inline]
Definition at line 110 of file large-spaces.h.
{ objects_size_ = objects_size; }
Referenced by v8::internal::ScavengerCollector::HandleSurvivingNewLargeObjects(), and v8::internal::MinorMarkSweepCollector::SweepNewLargeSpace().
ShrinkPageToObjectSize()
void v8::internal::LargeObjectSpace::ShrinkPageToObjectSize (LargePageMetadata * page, Tagged< HeapObject > object, size_t object_size)
Definition at line 223 of file large-spaces.cc.
                                                                  {
  MemoryChunk* chunk = page->Chunk();
#ifdef DEBUG
  PtrComprCageBase cage_base(heap()->isolate());
  DCHECK_EQ(object, page->GetObject());
  DCHECK_EQ(object_size, page->GetObject()->Size(cage_base));
  DCHECK_EQ(chunk->executable(), NOT_EXECUTABLE);
#endif // DEBUG
  const size_t used_committed_size =
      ::RoundUp(chunk->Offset(object.address()) + object_size,
                MemoryAllocator::GetCommitPageSize());
  // Object shrunk since last GC.
  if (object_size < page->area_size()) {
    page->ClearOutOfLiveRangeSlots(object.address() + object_size);
    const Address new_area_end = page->area_start() + object_size;
    // Object shrunk enough that we can even free some OS pages.
    if (used_committed_size < page->size()) {
      const size_t bytes_to_free = page->size() - used_committed_size;
      heap()->memory_allocator()->PartialFreeMemory(
          page, chunk->address() + used_committed_size, bytes_to_free,
          new_area_end);
      size_ -= bytes_to_free;
      AccountUncommitted(bytes_to_free);
    } else {
      // Can't free OS page but keep object area up-to-date.
      page->set_area_end(new_area_end);
    }
  }
  DCHECK_EQ(used_committed_size, page->size());
  DCHECK_EQ(object_size, page->area_size());
}
References v8::internal::BaseSpace::AccountUncommitted(), v8::internal::MemoryChunk::address(), v8::internal::MemoryChunkMetadata::area_size(), v8::internal::MemoryChunkMetadata::area_start(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::LargePageMetadata::ClearOutOfLiveRangeSlots(), DCHECK_EQ, v8::internal::MemoryChunk::executable(), v8::internal::MemoryAllocator::GetCommitPageSize(), v8::internal::LargePageMetadata::GetObject(), v8::internal::BaseSpace::heap(), v8::internal::Heap::memory_allocator(), v8::internal::NOT_EXECUTABLE, v8::internal::MemoryChunk::Offset(), v8::internal::MemoryAllocator::PartialFreeMemory(), RoundUp(), v8::internal::MemoryChunkMetadata::set_area_end(), v8::internal::MemoryChunkMetadata::size(), size(), and size_.
Size()
size_t v8::internal::LargeObjectSpace::Size () const [inline], [override], [virtual]
Implements v8::internal::BaseSpace.
Definition at line 46 of file large-spaces.h.
{ return size_; }
Referenced by v8::internal::Heap::CanPromoteYoungAndExpandOldGeneration(), v8::internal::Heap::CommittedMemory(), v8::internal::Heap::CommittedOldGenerationMemory(), v8::internal::Heap::RecordStats(), v8::internal::MinorMarkSweepCollector::Sweep(), v8::internal::MarkCompactCollector::SweepArrayBufferExtensions(), and v8::internal::ScavengerCollector::SweepArrayBufferExtensions().
SizeOfObjects()
size_t v8::internal::LargeObjectSpace::SizeOfObjects () const [inline], [override], [virtual]
Reimplemented from v8::internal::Space.
Definition at line 47 of file large-spaces.h.
{ return objects_size_; }
Referenced by v8::internal::NewLargeObjectSpace::AllocateRaw(), v8::internal::NewLargeObjectSpace::Available(), v8::internal::Heap::OldGenerationCapacity(), v8::internal::Heap::OldGenerationSizeOfObjects(), v8::internal::IncrementalMarking::OldGenerationSizeOfObjects(), v8::internal::Heap::PerformGarbageCollection(), v8::internal::Heap::PrintShortHeapStatistics(), v8::internal::NewLargeObjectSpace::SetCapacity(), v8::internal::GCTracer::StartInSafepoint(), v8::internal::Heap::YoungGenerationConsumedBytes(), and v8::internal::Heap::YoungGenerationSizeOfObjects().
TearDown()
void v8::internal::LargeObjectSpace::TearDown ()
Definition at line 66 of file large-spaces.cc.
                                {
  while (!memory_chunk_list_.Empty()) {
    LargePageMetadata* page = first_page();
    LOG(heap()->isolate(),
        DeleteEvent("LargeObjectChunk",
                    reinterpret_cast<void*>(page->ChunkAddress())));
    memory_chunk_list_.Remove(page);
    heap()->memory_allocator()->Free(MemoryAllocator::FreeMode::kImmediately,
                                     page);
  }
}
References v8::internal::MemoryChunkMetadata::ChunkAddress(), first_page(), v8::internal::MemoryAllocator::Free(), v8::internal::BaseSpace::heap(), v8::internal::MemoryAllocator::kImmediately, LOG, v8::internal::Heap::memory_allocator(), and v8::internal::Space::memory_chunk_list_.
UpdateAccountingAfterResizingObject()
void v8::internal::LargeObjectSpace::UpdateAccountingAfterResizingObject (size_t old_size, size_t new_size)
Definition at line 261 of file large-spaces.cc.
                                                    {
  DCHECK_GE(new_object_size, old_object_size);
  size_t old_size_committed =
      ::RoundUp(old_object_size, MemoryAllocator::GetCommitPageSize());
  size_t new_size_committed =
      ::RoundUp(new_object_size, MemoryAllocator::GetCommitPageSize());
  DCHECK_GE(new_size_committed, old_size_committed);
  size_ += new_size_committed - old_size_committed;
  AccountCommitted(new_size_committed - old_size_committed);
  objects_size_.fetch_add(new_object_size - old_object_size);
}
References v8::internal::BaseSpace::AccountCommitted(), DCHECK_GE, v8::internal::MemoryAllocator::GetCommitPageSize(), objects_size_, RoundUp(), and size_.
Referenced by v8::internal::HeapAllocator::TryResizeLargeObject().
UpdatePendingObject()
void v8::internal::LargeObjectSpace::UpdatePendingObject (Tagged< HeapObject > object) [protected]
Definition at line 360 of file large-spaces.cc.
                                                                    {
  base::MutexGuard guard(&pending_allocation_mutex_);
  pending_object_.store(object.address(), std::memory_order_release);
}
References pending_allocation_mutex_, and pending_object_.
Referenced by v8::internal::NewLargeObjectSpace::AllocateRaw(), and v8::internal::OldLargeObjectSpace::AllocateRaw().
Friends And Related Function Documentation
LargeObjectSpaceObjectIterator
friend class LargeObjectSpaceObjectIterator [friend]
Definition at line 142 of file large-spaces.h.
Referenced by GetObjectIterator().
Member Data Documentation
allocation_counter_
AllocationCounter v8::internal::LargeObjectSpace::allocation_counter_ [protected]
Definition at line 139 of file large-spaces.h.
Referenced by AddAllocationObserver(), AdvanceAndInvokeAllocationObservers(), v8::internal::OldLargeObjectSpace::AllocateRaw(), and RemoveAllocationObserver().
allocation_mutex_
base::RecursiveMutex v8::internal::LargeObjectSpace::allocation_mutex_ [protected]
Definition at line 130 of file large-spaces.h.
Referenced by AllocateLargePage().
objects_size_
std::atomic<size_t> v8::internal::LargeObjectSpace::objects_size_ [protected]
Definition at line 125 of file large-spaces.h.
Referenced by AddPage(), v8::internal::NewLargeObjectSpace::FreeDeadObjects(), and UpdateAccountingAfterResizingObject().
page_count_
int v8::internal::LargeObjectSpace::page_count_ [protected]
Definition at line 124 of file large-spaces.h.
Referenced by AddPage(), and RemovePage().
pending_allocation_mutex_
base::Mutex v8::internal::LargeObjectSpace::pending_allocation_mutex_ [protected]
Definition at line 137 of file large-spaces.h.
Referenced by UpdatePendingObject().
pending_object_
std::atomic<Address> v8::internal::LargeObjectSpace::pending_object_ [protected]
Definition at line 134 of file large-spaces.h.
Referenced by UpdatePendingObject().
size_
std::atomic<size_t> v8::internal::LargeObjectSpace::size_ [protected]
Definition at line 123 of file large-spaces.h.
Referenced by AddPage(), RemovePage(), ShrinkPageToObjectSize(), and UpdateAccountingAfterResizingObject().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/large-spaces.h
/mnt/V8SourceCode/src/heap/large-spaces.cc