v8::internal::maglev::NodeMultiProcessor< Processor, Processors... > Class Template Reference
#include <maglev-graph-processor.h>
Public Member Functions
template<typename... Args>
NodeMultiProcessor (Processor &&processor, Args &&... processors)
template<typename... Args>
NodeMultiProcessor (Args &&... processors)
template<typename Node >
ProcessResult Process (Node *node, const ProcessingState &state)
void PreProcessGraph (Graph *graph)
void PostProcessGraph (Graph *graph)
void PostProcessBasicBlock (BasicBlock *block)
BlockProcessResult PreProcessBasicBlock (BasicBlock *block)
void PostPhiProcessing ()
Private Types
using Base = NodeMultiProcessor< Processors... >
Private Attributes
Processor processor_
Detailed Description
template<typename Processor, typename... Processors>
class v8::internal::maglev::NodeMultiProcessor< Processor, Processors... >
Definition at line 273 of file maglev-graph-processor.h.
Member Typedef Documentation
Base
template<typename Processor , typename... Processors>
using v8::internal::maglev::NodeMultiProcessor< Processor, Processors... >::Base = NodeMultiProcessor<Processors...> [private]
Definition at line 275 of file maglev-graph-processor.h.
Constructor & Destructor Documentation
NodeMultiProcessor() [1/2]
template<typename Processor , typename... Processors>
template<typename... Args>
v8::internal::maglev::NodeMultiProcessor< Processor, Processors... >::NodeMultiProcessor (Processor && processor, Args &&... processors) [inline], [explicit]
Definition at line 279 of file maglev-graph-processor.h.
      : Base(std::forward<Args>(processors)...),
        processor_(std::forward<Processor>(processor)) {}
NodeMultiProcessor() [2/2]
template<typename Processor , typename... Processors>
template<typename... Args>
v8::internal::maglev::NodeMultiProcessor< Processor, Processors... >::NodeMultiProcessor (Args &&... processors) [inline], [explicit]
Definition at line 283 of file maglev-graph-processor.h.
      : Base(std::forward<Args>(processors)...) {}
Member Function Documentation
PostPhiProcessing()
template<typename Processor , typename... Processors>
void v8::internal::maglev::NodeMultiProcessor< Processor, Processors... >::PostPhiProcessing () [inline]
Definition at line 324 of file maglev-graph-processor.h.
                           {
    processor_.PostPhiProcessing();
    Base::PostPhiProcessing();
  }
PostProcessBasicBlock()
template<typename Processor , typename... Processors>
void v8::internal::maglev::NodeMultiProcessor< Processor, Processors... >::PostProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 311 of file maglev-graph-processor.h.
                                                {
    Base::PostProcessBasicBlock(block);
    processor_.PostProcessBasicBlock(block);
  }
PostProcessGraph()
template<typename Processor , typename... Processors>
void v8::internal::maglev::NodeMultiProcessor< Processor, Processors... >::PostProcessGraph (Graph * graph) [inline]
Definition at line 306 of file maglev-graph-processor.h.
                                      {
    // Post process in reverse order because that kind of makes sense.
    Base::PostProcessGraph(graph);
    processor_.PostProcessGraph(graph);
  }
References graph().
PreProcessBasicBlock()
template<typename Processor , typename... Processors>
BlockProcessResult v8::internal::maglev::NodeMultiProcessor< Processor, Processors... >::PreProcessBasicBlock (BasicBlock * block) [inline]
Definition at line 315 of file maglev-graph-processor.h.
                                                             {
    BlockProcessResult res = processor_.PreProcessBasicBlock(block);
    switch (res) {
      [[likely]] case BlockProcessResult::kContinue:
        return Base::PreProcessBasicBlock(block);
      case BlockProcessResult::kSkip:
        return res;
    }
  }
References v8::internal::maglev::kContinue, and v8::internal::maglev::kSkip.
PreProcessGraph()
template<typename Processor , typename... Processors>
void v8::internal::maglev::NodeMultiProcessor< Processor, Processors... >::PreProcessGraph (Graph * graph) [inline]
Definition at line 302 of file maglev-graph-processor.h.
                                     {
    processor_.PreProcessGraph(graph);
    Base::PreProcessGraph(graph);
  }
References graph().
Process()
template<typename Processor , typename... Processors>
template<typename Node >
ProcessResult v8::internal::maglev::NodeMultiProcessor< Processor, Processors... >::Process (Node * node, const ProcessingState & state) [inline]
Definition at line 287 of file maglev-graph-processor.h.
                                                                  {
    auto res = processor_.Process(node, state);
    switch (res) {
      [[likely]] case ProcessResult::kContinue:
        return Base::Process(node, state);
      case ProcessResult::kAbort:
      case ProcessResult::kRemove:
        return res;
      case ProcessResult::kHoist:
      case ProcessResult::kSkipBlock:
        // TODO(olivf): How to combine these with multiple processors depends on
        // the needs of the actual processors. Implement once needed.
        UNREACHABLE();
    }
  }
References v8::internal::maglev::kAbort, v8::internal::maglev::kContinue, v8::internal::maglev::kHoist, v8::internal::maglev::kRemove, v8::internal::maglev::kSkipBlock, and v8::internal::UNREACHABLE().
Member Data Documentation
processor_
template<typename Processor , typename... Processors>
Processor v8::internal::maglev::NodeMultiProcessor< Processor, Processors... >::processor_ [private]
Definition at line 330 of file maglev-graph-processor.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph-processor.h