v8::internal::PodArray< T > Class Template Reference
#include <fixed-array.h>
Static Public Member Functions
static Handle< PodArray< T > > New (Isolate *isolate, int length, AllocationType allocation=AllocationType::kYoung)
static Handle< PodArray< T > > New (LocalIsolate *isolate, int length, AllocationType allocation=AllocationType::kOld)
Additional Inherited Members
Detailed Description
template<class T>
class v8::internal::PodArray< T >
Definition at line 933 of file fixed-array.h.
Member Function Documentation
New() [1/2]
template<class T >
Handle< PodArray< T > > v8::internal::PodArray< T >::New (Isolate * isolate, int length, AllocationType allocation = AllocationType::kYoung) [static]
Definition at line 884 of file fixed-array-inl.h.
                                                                {
  int byte_length;
  CHECK(!base::bits::SignedMulOverflow32(length, sizeof(T), &byte_length));
  return Cast<PodArray<T>>(
      isolate->factory()->NewByteArray(byte_length, allocation));
}
References CHECK, v8::internal::Isolate::factory(), v8::internal::length, v8::internal::FactoryBase< Impl >::NewByteArray(), and v8::base::bits::SignedMulOverflow32().
Referenced by v8::internal::MathRandom::InitializeContext(), and v8::internal::WasmTagObject::New().
New() [2/2]
template<class T >
Handle< PodArray< T > > v8::internal::PodArray< T >::New (LocalIsolate * isolate, int length, AllocationType allocation = AllocationType::kOld) [static]
Definition at line 894 of file fixed-array-inl.h.
                                                                {
  int byte_length;
  CHECK(!base::bits::SignedMulOverflow32(length, sizeof(T), &byte_length));
  return Cast<PodArray<T>>(
      isolate->factory()->NewByteArray(byte_length, allocation));
}
References CHECK, v8::internal::LocalIsolate::factory(), v8::internal::length, v8::internal::FactoryBase< Impl >::NewByteArray(), and v8::base::bits::SignedMulOverflow32().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/factory-base.h
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h