v8::internal::EmbedderDataArray Class Reference
#include <embedder-data-array.h>
Classes
class BodyDescriptor
Public Member Functions
Address slots_start ()
Address slots_end ()
Static Public Member Functions
static constexpr int SizeFor (int length)
static DirectHandle< EmbedderDataArray > EnsureCapacity (Isolate *isolate, DirectHandle< EmbedderDataArray > array, int index)
static constexpr int OffsetOfElementAt (int index)
Static Public Attributes
static const int kHeaderSize = kSize
static const int kMaxSize = kMaxRegularHeapObjectSize
static constexpr int kMaxLength
Detailed Description
Definition at line 24 of file embedder-data-array.h.
Member Function Documentation
EnsureCapacity()
DirectHandle< EmbedderDataArray > v8::internal::EmbedderDataArray::EnsureCapacity (Isolate * isolate, DirectHandle< EmbedderDataArray > array, int index) [static]
Definition at line 29 of file embedder-data-array.cc.
                                                                        {
  if (index < array->length()) return array;
  DCHECK_LT(index, kMaxLength);
  DirectHandle<EmbedderDataArray> new_array =
      isolate->factory()->NewEmbedderDataArray(index + 1);
  DisallowGarbageCollection no_gc;
  // Last new space allocation does not require any write barriers.
#ifdef V8_ENABLE_SANDBOX
  for (int i = 0; i < array->length(); i++) {
    EmbedderDataSlot src(*array, i);
    EmbedderDataSlot dest(*new_array, i);
    ExternalPointerHandle src_handle = LoadExternalPointerHandle(src);
    if (src_handle != kNullExternalPointerHandle) {
      void* value;
      CHECK(src.ToAlignedPointer(isolate, &value));
      CHECK(dest.store_aligned_pointer(isolate, *new_array, value));
    } else {
      StoreTaggedWithoutBarrier(dest, src.load_tagged());
    }
  }
#else
  size_t size = array->length() * kEmbedderDataSlotSize;
  MemCopy(reinterpret_cast<void*>(new_array->slots_start()),
          reinterpret_cast<void*>(array->slots_start()), size);
#endif // V8_ENABLE_SANDBOX
  return new_array;
}
References CHECK, DCHECK_LT, v8::internal::Isolate::factory(), v8::internal::index, v8::internal::kEmbedderDataSlotSize, kMaxLength, v8::internal::kNullExternalPointerHandle, v8::internal::length, v8::internal::EmbedderDataSlot::load_tagged(), v8::internal::MemCopy(), v8::internal::Factory::NewEmbedderDataArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), v8::internal::EmbedderDataSlot::store_aligned_pointer(), v8::internal::EmbedderDataSlot::ToAlignedPointer(), and v8::internal::value.
Referenced by v8::EmbedderDataFor().
OffsetOfElementAt()
static constexpr int v8::internal::EmbedderDataArray::OffsetOfElementAt (int index) [inline], [static], [constexpr]
Definition at line 40 of file embedder-data-array.h.
{ return SizeFor(index); }
References v8::internal::index, and SizeFor().
Referenced by v8::internal::EmbedderDataArray::BodyDescriptor::IterateBody(), slots_end(), and v8::internal::EmbedderDataSlot::store_tagged().
SizeFor()
static constexpr int v8::internal::EmbedderDataArray::SizeFor (int length) [inline], [static], [constexpr]
Definition at line 31 of file embedder-data-array.h.
                                           {
    return kHeaderSize + length * kEmbedderDataSlotSize;
  }
References v8::internal::kEmbedderDataSlotSize, kHeaderSize, and v8::internal::length.
Referenced by v8::internal::Factory::NewEmbedderDataArray(), OffsetOfElementAt(), and v8::internal::HeapObject::SizeFromMap().
slots_end()
Address v8::internal::EmbedderDataArray::slots_end () [inline]
Definition at line 30 of file embedder-data-array-inl.h.
                                     {
  return field_address(OffsetOfElementAt(length()));
}
References v8::internal::length, and OffsetOfElementAt().
slots_start()
Address v8::internal::EmbedderDataArray::slots_start () [inline]
Definition at line 26 of file embedder-data-array-inl.h.
                                       {
  return field_address(OffsetOfElementAt(0));
}
References v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::OffsetOfElementAt().
Member Data Documentation
kHeaderSize
const int v8::internal::EmbedderDataArray::kHeaderSize = kSize [static]
Definition at line 28 of file embedder-data-array.h.
Referenced by v8::internal::EmbedderDataArray::BodyDescriptor::IterateBody(), and SizeFor().
kMaxLength
constexpr int v8::internal::EmbedderDataArray::kMaxLength [static], [constexpr]
Initial value:
=
      (kMaxSize - kHeaderSize) / kEmbedderDataSlotSize
Definition at line 55 of file embedder-data-array.h.
Referenced by v8::EmbedderDataFor(), EnsureCapacity(), and v8::anonymous_namespace{api.cc}::GetAlignedPointerFromEmbedderDataInCreationContextImpl().
kMaxSize
const int v8::internal::EmbedderDataArray::kMaxSize = kMaxRegularHeapObjectSize [static]
Definition at line 54 of file embedder-data-array.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/embedder-data-array.h
/mnt/V8SourceCode/src/objects/embedder-data-array-inl.h
/mnt/V8SourceCode/src/objects/embedder-data-array.cc