v8::internal::ParkedMutexGuardIf Class Reference
#include <parked-scope.h>
Public Member Functions
ParkedMutexGuardIf (LocalIsolate *local_isolate, base::Mutex *mutex, bool enable_mutex)
ParkedMutexGuardIf (LocalHeap *local_heap, base::Mutex *mutex, bool enable_mutex)
ParkedMutexGuardIf (const ParkedMutexGuardIf &)=delete
ParkedMutexGuardIf & operator= (const ParkedMutexGuardIf &)=delete
~ParkedMutexGuardIf ()
Private Attributes
base::Mutex * mutex_ = nullptr
Detailed Description
Definition at line 108 of file parked-scope.h.
Constructor & Destructor Documentation
ParkedMutexGuardIf() [1/3]
v8::internal::ParkedMutexGuardIf::ParkedMutexGuardIf (LocalIsolate * local_isolate, base::Mutex * mutex, bool enable_mutex) [inline]
Definition at line 46 of file parked-scope-inl.h.
    : ParkedMutexGuardIf(local_isolate -> heap(), mutex, enable_mutex) {}
ParkedMutexGuardIf() [2/3]
v8::internal::ParkedMutexGuardIf::ParkedMutexGuardIf (LocalHeap * local_heap, base::Mutex * mutex, bool enable_mutex) [inline]
Definition at line 50 of file parked-scope-inl.h.
                                                                    {
  DCHECK(AllowGarbageCollection::IsAllowed());
  if (!enable_mutex) return;
  mutex_ = mutex;
  if (!mutex_->TryLock()) {
    local_heap->ExecuteWhileParked([this]() { mutex_->Lock(); });
  }
}
References v8::internal::DCHECK(), v8::internal::LocalHeap::ExecuteWhileParked(), v8::base::Mutex::Lock(), mutex_, and v8::base::Mutex::TryLock().
ParkedMutexGuardIf() [3/3]
v8::internal::ParkedMutexGuardIf::ParkedMutexGuardIf (const ParkedMutexGuardIf &) [delete]
 ParkedMutexGuardIf()
v8::internal::ParkedMutexGuardIf::~ParkedMutexGuardIf () [inline]
Definition at line 118 of file parked-scope.h.
                        {
    if (!mutex_) return;
    mutex_->Unlock();
  }
Member Function Documentation
operator=()
ParkedMutexGuardIf& v8::internal::ParkedMutexGuardIf::operator= (const ParkedMutexGuardIf &) [delete]
Member Data Documentation
mutex_
base::Mutex* v8::internal::ParkedMutexGuardIf::mutex_ = nullptr [private]
Definition at line 125 of file parked-scope.h.
Referenced by ParkedMutexGuardIf().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/parked-scope.h
/mnt/V8SourceCode/src/heap/parked-scope-inl.h