v8::internal::compiler::CheckMinusZeroParameters Class Reference
#include <simplified-operator.h>
Public Member Functions
CheckMinusZeroParameters (CheckForMinusZeroMode mode, const FeedbackSource &feedback)
CheckForMinusZeroMode mode () const
const FeedbackSource & feedback () const
Private Attributes
CheckForMinusZeroMode mode_
FeedbackSource feedback_
Detailed Description
Definition at line 417 of file simplified-operator.h.
Constructor & Destructor Documentation
CheckMinusZeroParameters()
v8::internal::compiler::CheckMinusZeroParameters::CheckMinusZeroParameters (CheckForMinusZeroMode mode, const FeedbackSource & feedback) [inline]
Definition at line 419 of file simplified-operator.h.
      : mode_(mode), feedback_(feedback) {}
Member Function Documentation
feedback()
const FeedbackSource& v8::internal::compiler::CheckMinusZeroParameters::feedback () const [inline]
Definition at line 424 of file simplified-operator.h.
{ return feedback_; }
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
mode()
CheckForMinusZeroMode v8::internal::compiler::CheckMinusZeroParameters::mode () const [inline]
Definition at line 423 of file simplified-operator.h.
{ return mode_; }
Referenced by v8::internal::compiler::anonymous_namespace{redundancy-elimination.cc}::CheckSubsumes(), v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), v8::internal::compiler::operator==(), and v8::internal::compiler::turboshaft::anonymous_namespace{graph-builder.cc}::GraphBuilder::Process().
Member Data Documentation
feedback_
FeedbackSource v8::internal::compiler::CheckMinusZeroParameters::feedback_ [private]
Definition at line 428 of file simplified-operator.h.
mode_
CheckForMinusZeroMode v8::internal::compiler::CheckMinusZeroParameters::mode_ [private]
Definition at line 427 of file simplified-operator.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.h