v8::internal::wasm::ImmediatesPrinter< ValidationTag > Class Template Reference
Public Member Functions
ImmediatesPrinter (StringBuilder &out, FunctionBodyDisassembler *owner)
void PrintDepthAsLabel (int imm_depth)
void PrintSignature (ModuleTypeIndex sig_index)
void BlockType (BlockTypeImmediate &imm)
void HeapType (HeapTypeImmediate &imm)
void ValueType (ValueType type)
void BrOnCastFlags (BrOnCastImmediate &flags)
void BranchDepth (BranchDepthImmediate &imm)
void BranchTable (BranchTableImmediate &imm)
const char * CatchKindToString (CatchKind kind)
void TryTable (TryTableImmediate &imm)
void EffectHandlerTable (EffectHandlerTableImmediate &imm)
void CallIndirect (CallIndirectImmediate &imm)
void SelectType (SelectTypeImmediate &imm)
void MemoryAccess (MemoryAccessImmediate &imm)
void MemoryOrder (const MemoryOrderImmediate &memory_order)
void SimdLane (SimdLaneImmediate &imm)
void Field (FieldImmediate &imm)
void Length (IndexImmediate &imm)
void TagIndex (TagIndexImmediate &imm)
void FunctionIndex (IndexImmediate &imm)
void TypeIndex (TypeIndexImmediate &imm)
void LocalIndex (IndexImmediate &imm)
void GlobalIndex (IndexImmediate &imm)
void TableIndex (TableIndexImmediate &imm)
void MemoryIndex (MemoryIndexImmediate &imm)
void DataSegmentIndex (IndexImmediate &imm)
void ElemSegmentIndex (IndexImmediate &imm)
void I32Const (ImmI32Immediate &imm)
void I64Const (ImmI64Immediate &imm)
void F32Const (ImmF32Immediate &imm)
void F64Const (ImmF64Immediate &imm)
void S128Const (Simd128Immediate &imm)
void StringConst (StringConstImmediate &imm)
void MemoryInit (MemoryInitImmediate &imm)
void MemoryCopy (MemoryCopyImmediate &imm)
void TableInit (TableInitImmediate &imm)
void TableCopy (TableCopyImmediate &imm)
void ArrayCopy (TypeIndexImmediate &dst, TypeIndexImmediate &src)
Private Member Functions
void use_type (ModuleTypeIndex type_index)
NamesProvider * names ()
uint32_t func_index ()
Private Attributes
StringBuilder & out_
FunctionBodyDisassembler * owner_
Detailed Description
template<typename ValidationTag>
class v8::internal::wasm::ImmediatesPrinter< ValidationTag >
Definition at line 355 of file wasm-disassembler.cc.
Constructor & Destructor Documentation
ImmediatesPrinter()
template<typename ValidationTag >
v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ImmediatesPrinter (StringBuilder & out, FunctionBodyDisassembler * owner) [inline]
Definition at line 357 of file wasm-disassembler.cc.
      : out_(out), owner_(owner) {}
Member Function Documentation
ArrayCopy()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ArrayCopy (TypeIndexImmediate & dst, TypeIndexImmediate & src) [inline]
Definition at line 708 of file wasm-disassembler.cc.
                                                                   {
    out_ << " ";
    names()->PrintTypeName(out_, dst.index);
    out_ << " ";
    names()->PrintTypeName(out_, src.index);
    use_type(dst.index);
    use_type(src.index);
  }
References v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::NamesProvider::PrintTypeName(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::use_type().
BlockType()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::BlockType (BlockTypeImmediate & imm) [inline]
Definition at line 394 of file wasm-disassembler.cc.
                                          {
    if (imm.sig.all().begin() == nullptr) {
      PrintSignature(imm.sig_index);
    } else {
      PrintSignatureOneLine(out_, &imm.sig, 0 /* ignored */, names(), false);
    }
  }
References v8::internal::Signature< T >::all(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintSignature(), v8::internal::wasm::PrintSignatureOneLine(), v8::internal::wasm::BlockTypeImmediate::sig, and v8::internal::wasm::BlockTypeImmediate::sig_index.
BranchDepth()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::BranchDepth (BranchDepthImmediate & imm) [inline]
Definition at line 419 of file wasm-disassembler.cc.
{ PrintDepthAsLabel(imm.depth); }
References v8::internal::wasm::BranchDepthImmediate::depth, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel().
BranchTable()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::BranchTable (BranchTableImmediate & imm) [inline]
Definition at line 421 of file wasm-disassembler.cc.
                                              {
    const uint8_t* pc = imm.table;
    for (uint32_t i = 0; i <= imm.table_count; i++) {
      auto [target, length] = owner_->read_u32v<ValidationTag>(pc);
      PrintDepthAsLabel(target);
      pc += length;
    }
  }
References v8::internal::length, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel(), v8::internal::wasm::Decoder::read_u32v(), v8::internal::wasm::BranchTableImmediate::table, and v8::internal::wasm::BranchTableImmediate::table_count.
BrOnCastFlags()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::BrOnCastFlags (BrOnCastImmediate & flags) [inline]
Definition at line 414 of file wasm-disassembler.cc.
                                               {
    // Ignored here. For printing text format, we do all the work via the
    // two calls to {ValueType()} that we get for a br_on_cast.
  }
CallIndirect()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::CallIndirect (CallIndirectImmediate & imm) [inline]
Definition at line 484 of file wasm-disassembler.cc.
                                                {
    PrintSignature(imm.sig_imm.index);
    if (imm.table_imm.index != 0) TableIndex(imm.table_imm);
  }
References v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintSignature(), v8::internal::wasm::CallIndirectImmediate::sig_imm, v8::internal::wasm::CallIndirectImmediate::table_imm, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TableIndex().
CatchKindToString()
template<typename ValidationTag >
const char* v8::internal::wasm::ImmediatesPrinter< ValidationTag >::CatchKindToString (CatchKind kind) [inline]
Definition at line 430 of file wasm-disassembler.cc.
                                                {
    switch (kind) {
      case kCatch:
        return "catch";
      case kCatchRef:
        return "catch_ref";
      case kCatchAll:
        return "catch_all";
      case kCatchAllRef:
        return "catch_all_ref";
      default:
        return "<invalid>";
    }
  }
References v8::internal::wasm::kCatch, v8::internal::wasm::kCatchAll, v8::internal::wasm::kCatchAllRef, and v8::internal::wasm::kCatchRef.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TryTable().
DataSegmentIndex()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::DataSegmentIndex (IndexImmediate & imm) [inline]
Definition at line 562 of file wasm-disassembler.cc.
                                             {
    if (kSkipDataSegmentNames) {
      out_ << " " << imm.index;
    } else {
      out_ << " ";
      names()->PrintDataSegmentName(out_, imm.index);
    }
  }
References v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::kSkipDataSegmentNames, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, and v8::internal::wasm::NamesProvider::PrintDataSegmentName().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryInit().
EffectHandlerTable()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::EffectHandlerTable (EffectHandlerTableImmediate & imm) [inline]
Definition at line 463 of file wasm-disassembler.cc.
                                                            {
    const uint8_t* pc = imm.table;
    for (uint32_t i = 0; i < imm.table_count; i++) {
      uint8_t kind = owner_->read_u8<ValidationTag>(pc);
      pc += 1;
      auto [tag, length] = owner_->read_u32v<ValidationTag>(pc);
      out_ << "(on ";
      names()->PrintTagName(out_, tag);
      out_ << " ";
      pc += length;
      if (kind == kOnSuspend) {
        auto [target, tlen] = owner_->read_u32v<ValidationTag>(pc);
        PrintDepthAsLabel(target);
        pc += tlen;
        out_ << ")";
      } else {
        out_ << " switch)";
      }
    }
  }
References v8::internal::wasm::kOnSuspend, v8::internal::length, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel(), v8::internal::wasm::NamesProvider::PrintTagName(), v8::internal::wasm::Decoder::read_u32v(), v8::internal::wasm::Decoder::read_u8(), v8::internal::wasm::BranchTableImmediate::table, and v8::internal::wasm::BranchTableImmediate::table_count.
ElemSegmentIndex()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ElemSegmentIndex (IndexImmediate & imm) [inline]
Definition at line 571 of file wasm-disassembler.cc.
                                             {
    out_ << " ";
    names()->PrintElementSegmentName(out_, imm.index);
  }
References v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, and v8::internal::wasm::NamesProvider::PrintElementSegmentName().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TableInit().
F32Const()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::F32Const (ImmF32Immediate & imm) [inline]
Definition at line 588 of file wasm-disassembler.cc.
                                      {
    float f = imm.value;
    if (f == 0) {
      out_ << (1 / f < 0 ? " -0.0" : " 0.0");
    } else if (std::isinf(f)) {
      out_ << (f > 0 ? " inf" : " -inf");
    } else if (std::isnan(f)) {
      uint32_t bits = base::bit_cast<uint32_t>(f);
      uint32_t payload = bits & 0x7F'FFFFu;
      uint32_t signbit = bits >> 31;
      if (payload == 0x40'0000u) {
        out_ << (signbit == 1 ? " -nan" : " nan");
      } else {
        out_ << (signbit == 1 ? " -nan:" : " +nan:");
        owner_->PrintHexNumber(out_, payload);
      }
    } else {
      std::ostringstream o;
      // TODO(dlehmann): Change to `std::format` (C++20) or to `std::to_chars`
      // (C++17) once available, so that `0.1` isn't printed as `0.100000001`
      // any more.
      o << std::setprecision(std::numeric_limits<float>::max_digits10) << f;
      out_ << " " << o.str();
    }
  }
References v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_, v8::internal::wasm::FunctionBodyDisassembler::PrintHexNumber(), and v8::internal::wasm::ImmF32Immediate::value.
F64Const()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::F64Const (ImmF64Immediate & imm) [inline]
Definition at line 614 of file wasm-disassembler.cc.
                                      {
    double d = imm.value;
    if (d == 0) {
      out_ << (1 / d < 0 ? " -0.0" : " 0.0");
    } else if (std::isinf(d)) {
      out_ << (d > 0 ? " inf" : " -inf");
    } else if (std::isnan(d)) {
      uint64_t bits = base::bit_cast<uint64_t>(d);
      uint64_t payload = bits & 0xF'FFFF'FFFF'FFFFull;
      uint64_t signbit = bits >> 63;
      if (payload == 0x8'0000'0000'0000ull) {
        out_ << (signbit == 1 ? " -nan" : " nan");
      } else {
        out_ << (signbit == 1 ? " -nan:" : " +nan:");
        owner_->PrintHexNumber(out_, payload);
      }
    } else {
      char buffer[100];
      std::string_view str =
          DoubleToStringView(d, base::VectorOf(buffer, 100u));
      out_ << " " << str;
    }
  }
References v8::internal::DoubleToStringView(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_, v8::internal::wasm::FunctionBodyDisassembler::PrintHexNumber(), v8::internal::wasm::ImmF64Immediate::value, and v8::base::VectorOf().
Field()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::Field (FieldImmediate & imm) [inline]
Definition at line 515 of file wasm-disassembler.cc.
                                  {
    TypeIndex(imm.struct_imm);
    out_ << " ";
    names()->PrintFieldName(out_, imm.struct_imm.index.index,
                            imm.field_imm.index);
  }
References v8::internal::wasm::FieldImmediate::field_imm, v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::TypeIndex::index, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::NamesProvider::PrintFieldName(), v8::internal::wasm::FieldImmediate::struct_imm, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TypeIndex().
func_index()
template<typename ValidationTag >
uint32_t v8::internal::wasm::ImmediatesPrinter< ValidationTag >::func_index () [inline], [private]
Definition at line 724 of file wasm-disassembler.cc.
{ return owner_->func_index_; }
References v8::internal::wasm::FunctionBodyDisassembler::func_index_, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::LocalIndex().
FunctionIndex()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::FunctionIndex (IndexImmediate & imm) [inline]
Definition at line 531 of file wasm-disassembler.cc.
                                          {
    out_ << " ";
    names()->PrintFunctionName(out_, imm.index, NamesProvider::kDevTools);
  }
References v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::NamesProvider::kDevTools, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, and v8::internal::wasm::NamesProvider::PrintFunctionName().
GlobalIndex()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::GlobalIndex (IndexImmediate & imm) [inline]
Definition at line 547 of file wasm-disassembler.cc.
                                        {
    out_ << " ";
    names()->PrintGlobalName(out_, imm.index);
  }
References v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, and v8::internal::wasm::NamesProvider::PrintGlobalName().
HeapType()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::HeapType (HeapTypeImmediate & imm) [inline]
Definition at line 402 of file wasm-disassembler.cc.
                                        {
    out_ << " ";
    names()->PrintHeapType(out_, imm.type);
    if (imm.type.is_index()) use_type(imm.type.ref_index());
  }
References v8::internal::wasm::HeapType::is_index(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::NamesProvider::PrintHeapType(), v8::internal::wasm::HeapType::ref_index(), v8::internal::wasm::HeapTypeImmediate::type, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::use_type().
I32Const()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::I32Const (ImmI32Immediate & imm) [inline]
Definition at line 576 of file wasm-disassembler.cc.
                                      {
    out_ << " " << imm.value; // --
  }
References v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, and v8::internal::wasm::ImmI32Immediate::value.
I64Const()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::I64Const (ImmI64Immediate & imm) [inline]
Definition at line 580 of file wasm-disassembler.cc.
                                      {
    if (imm.value >= 0) {
      out_ << " " << static_cast<uint64_t>(imm.value);
    } else {
      out_ << " -" << ((~static_cast<uint64_t>(imm.value)) + 1);
    }
  }
References v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, and v8::internal::wasm::ImmI64Immediate::value.
Length()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::Length (IndexImmediate & imm) [inline]
Definition at line 522 of file wasm-disassembler.cc.
                                   {
    out_ << " " << imm.index; // --
  }
References v8::internal::wasm::IndexImmediate::index, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_.
LocalIndex()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::LocalIndex (IndexImmediate & imm) [inline]
Definition at line 542 of file wasm-disassembler.cc.
                                       {
    out_ << " ";
    names()->PrintLocalName(out_, func_index(), imm.index);
  }
References v8::internal::wasm::ImmediatesPrinter< ValidationTag >::func_index(), v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, and v8::internal::wasm::NamesProvider::PrintLocalName().
MemoryAccess()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryAccess (MemoryAccessImmediate & imm) [inline]
Definition at line 494 of file wasm-disassembler.cc.
                                                {
    if (imm.offset != 0) out_ << " offset=" << imm.offset;
    if (imm.alignment != GetDefaultAlignment(owner_->current_opcode_)) {
      out_ << " align=" << (1u << imm.alignment);
    }
  }
References v8::internal::wasm::MemoryAccessImmediate::alignment, v8::internal::wasm::FunctionBodyDisassembler::current_opcode_, v8::internal::wasm::GetDefaultAlignment(), v8::internal::wasm::MemoryAccessImmediate::offset, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_.
MemoryCopy()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryCopy (MemoryCopyImmediate & imm) [inline]
Definition at line 689 of file wasm-disassembler.cc.
                                            {
    if (imm.memory_dst.index == 0 && imm.memory_src.index == 0) return;
    out_ << " " << uint32_t{imm.memory_dst.index};
    out_ << " " << uint32_t{imm.memory_src.index};
  }
References v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::MemoryCopyImmediate::memory_dst, v8::internal::wasm::MemoryCopyImmediate::memory_src, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_.
MemoryIndex()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryIndex (MemoryIndexImmediate & imm) [inline]
Definition at line 557 of file wasm-disassembler.cc.
                                              {
    if (imm.index == 0) return;
    out_ << " " << imm.index;
  }
References v8::internal::wasm::IndexImmediate::index, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_.
MemoryInit()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryInit (MemoryInitImmediate & imm) [inline]
Definition at line 684 of file wasm-disassembler.cc.
                                            {
    DataSegmentIndex(imm.data_segment);
    if (imm.memory.index != 0) out_ << " " << uint32_t{imm.memory.index};
  }
References v8::internal::wasm::MemoryInitImmediate::data_segment, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::DataSegmentIndex(), v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::MemoryInitImmediate::memory, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_.
MemoryOrder()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryOrder (const MemoryOrderImmediate & memory_order) [inline]
Definition at line 501 of file wasm-disassembler.cc.
                                                             {
    switch (memory_order.order) {
      case AtomicMemoryOrder::kAcqRel:
        out_ << " acqrel";
        return;
      case AtomicMemoryOrder::kSeqCst:
        out_ << " seqcst";
        return;
    }
    out_ << " INVALID(" << static_cast<int>(memory_order.order) << ')';
  }
References v8::internal::kAcqRel, v8::internal::kSeqCst, v8::internal::wasm::MemoryOrderImmediate::order, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_.
names()
template<typename ValidationTag >
NamesProvider* v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names () [inline], [private]
Definition at line 722 of file wasm-disassembler.cc.
{ return owner_->names_; }
References v8::internal::wasm::FunctionBodyDisassembler::names_, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ArrayCopy(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::BlockType(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::DataSegmentIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::EffectHandlerTable(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ElemSegmentIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::Field(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::FunctionIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::GlobalIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::HeapType(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::LocalIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintSignature(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::SelectType(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TableCopy(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TableIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TagIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TryTable(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TypeIndex(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ValueType().
PrintDepthAsLabel()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel (int imm_depth) [inline]
Definition at line 360 of file wasm-disassembler.cc.
                                        {
    out_ << " ";
    size_t label_start_position = out_.length();
    int depth = imm_depth;
    if (owner_->current_opcode_ == kExprDelegate) depth++;
    // Be robust: if the module is invalid, print what we got.
    if (depth < 0 || depth >= static_cast<int>(owner_->label_stack_.size())) {
      out_ << imm_depth;
      return;
    }
    // If the label's name has already been determined and backpatched, just
    // copy it here.
    LabelInfo& label_info = owner_->label_info(depth);
    if (label_info.start != nullptr) {
      out_.write(label_info.start, label_info.length);
      return;
    }
    // Determine the label's name and backpatch the line that opened the block.
    names()->PrintLabelName(out_, owner_->func_index_,
                            label_info.name_section_index,
                            owner_->label_generation_index_++);
    label_info.length = out_.length() - label_start_position;
    owner_->out_->PatchLabel(label_info, out_.start() + label_start_position);
  }
References v8::internal::wasm::FunctionBodyDisassembler::current_opcode_, v8::internal::wasm::FunctionBodyDisassembler::func_index_, v8::internal::wasm::FunctionBodyDisassembler::label_generation_index_, v8::internal::wasm::FunctionBodyDisassembler::label_info(), v8::internal::wasm::FunctionBodyDisassembler::label_stack_, v8::internal::wasm::LabelInfo::length, v8::internal::wasm::StringBuilder::length(), v8::internal::wasm::LabelInfo::name_section_index, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::FunctionBodyDisassembler::out_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_, v8::internal::wasm::MultiLineStringBuilder::PatchLabel(), v8::internal::wasm::NamesProvider::PrintLabelName(), v8::internal::wasm::LabelInfo::start, v8::internal::wasm::StringBuilder::start(), and v8::internal::wasm::StringBuilder::write().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::BranchDepth(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::BranchTable(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::EffectHandlerTable(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TryTable().
PrintSignature()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintSignature (ModuleTypeIndex sig_index) [inline]
Definition at line 385 of file wasm-disassembler.cc.
                                                 {
    if (owner_->module_->has_signature(sig_index)) {
      const FunctionSig* sig = owner_->module_->signature(sig_index);
      PrintSignatureOneLine(out_, sig, 0 /* ignored */, names(), false);
    } else {
      out_ << " (signature: " << sig_index << " INVALID)";
    }
  }
References v8::internal::wasm::WasmModule::has_signature(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_, v8::internal::wasm::PrintSignatureOneLine(), v8::internal::sig, and v8::internal::wasm::WasmModule::signature().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::BlockType(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::CallIndirect().
S128Const()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::S128Const (Simd128Immediate & imm) [inline]
Definition at line 638 of file wasm-disassembler.cc.
                                        {
    if (owner_->current_opcode_ == kExprI8x16Shuffle) {
      for (int i = 0; i < 16; i++) {
        out_ << " " << uint32_t{imm.value[i]};
      }
    } else {
      DCHECK_EQ(owner_->current_opcode_, kExprS128Const);
      out_ << " i32x4";
      for (int i = 0; i < 4; i++) {
        out_ << " 0x";
        for (int j = 3; j >= 0; j--) { // Little endian.
          uint8_t b = imm.value[i * 4 + j];
          out_ << kUpperHexChars[b >> 4];
          out_ << kUpperHexChars[b & 0xF];
        }
      }
    }
  }
References v8::internal::wasm::FunctionBodyDisassembler::current_opcode_, DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::kUpperHexChars, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_, and v8::internal::wasm::Simd128Immediate::value.
SelectType()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::SelectType (SelectTypeImmediate & imm) [inline]
Definition at line 489 of file wasm-disassembler.cc.
                                            {
    out_ << " ";
    names()->PrintValueType(out_, imm.type);
  }
References v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::NamesProvider::PrintValueType(), and v8::internal::wasm::SelectTypeImmediate::type.
SimdLane()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::SimdLane (SimdLaneImmediate & imm) [inline]
Definition at line 513 of file wasm-disassembler.cc.
{ out_ << " " << uint32_t{imm.lane}; }
References v8::internal::wasm::SimdLaneImmediate::lane, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_.
StringConst()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::StringConst (StringConstImmediate & imm) [inline]
Definition at line 657 of file wasm-disassembler.cc.
                                              {
    if (imm.index >= owner_->module_->stringref_literals.size()) {
      out_ << " " << imm.index << " INVALID";
      return;
    }
    if (owner_->wire_bytes_.start() == nullptr) {
      out_ << " " << imm.index;
      return;
    }
    out_ << " \"";
    const WasmStringRefLiteral& lit =
        owner_->module_->stringref_literals[imm.index];
    const uint8_t* start = owner_->wire_bytes_.start() + lit.source.offset();
    static constexpr uint32_t kMaxCharsPrinted = 40;
    if (lit.source.length() <= kMaxCharsPrinted) {
      const uint8_t* end =
          owner_->wire_bytes_.start() + lit.source.end_offset();
      PrintStringRaw(out_, start, end);
    } else {
      const uint8_t* end = start + kMaxCharsPrinted - 1;
      PrintStringRaw(out_, start, end);
      out_ << "";
    }
    out_ << '"';
    if (kIndicesAsComments) out_ << " (;" << imm.index << ";)";
  }
References v8::internal::compiler::end(), v8::internal::wasm::WireBytesRef::end_offset(), v8::internal::wasm::StringConstImmediate::index, v8::internal::wasm::kIndicesAsComments, v8::internal::wasm::WireBytesRef::length(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::module_, v8::internal::wasm::WireBytesRef::offset(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_, v8::internal::wasm::PrintStringRaw(), v8::internal::wasm::WasmStringRefLiteral::source, v8::internal::wasm::ModuleWireBytes::start(), v8::internal::wasm::WasmModule::stringref_literals, and v8::internal::wasm::FunctionBodyDisassembler::wire_bytes_.
TableCopy()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TableCopy (TableCopyImmediate & imm) [inline]
Definition at line 700 of file wasm-disassembler.cc.
                                          {
    if (imm.table_dst.index == 0 && imm.table_src.index == 0) return;
    out_ << " ";
    names()->PrintTableName(out_, imm.table_dst.index);
    out_ << " ";
    names()->PrintTableName(out_, imm.table_src.index);
  }
References v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::NamesProvider::PrintTableName(), v8::internal::wasm::TableCopyImmediate::table_dst, and v8::internal::wasm::TableCopyImmediate::table_src.
TableIndex()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TableIndex (TableIndexImmediate & imm) [inline]
Definition at line 552 of file wasm-disassembler.cc.
                                            {
    out_ << " ";
    names()->PrintTableName(out_, imm.index);
  }
References v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, and v8::internal::wasm::NamesProvider::PrintTableName().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::CallIndirect(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TableInit().
TableInit()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TableInit (TableInitImmediate & imm) [inline]
Definition at line 695 of file wasm-disassembler.cc.
                                          {
    if (imm.table.index != 0) TableIndex(imm.table);
    ElemSegmentIndex(imm.element_segment);
  }
References v8::internal::wasm::TableInitImmediate::element_segment, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ElemSegmentIndex(), v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::TableInitImmediate::table, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TableIndex().
TagIndex()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TagIndex (TagIndexImmediate & imm) [inline]
Definition at line 526 of file wasm-disassembler.cc.
                                        {
    out_ << " ";
    names()->PrintTagName(out_, imm.index);
  }
References v8::internal::wasm::IndexImmediate::index, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, and v8::internal::wasm::NamesProvider::PrintTagName().
TryTable()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TryTable (TryTableImmediate & imm) [inline]
Definition at line 445 of file wasm-disassembler.cc.
                                        {
    const uint8_t* pc = imm.table;
    for (uint32_t i = 0; i < imm.table_count; i++) {
      uint8_t kind = owner_->read_u8<ValidationTag>(pc);
      pc += 1;
      out_ << " " << CatchKindToString(static_cast<CatchKind>(kind));
      if (kind == kCatch || kind == kCatchRef) {
        auto [tag, length] = owner_->read_u32v<ValidationTag>(pc);
        out_ << " ";
        names()->PrintTagName(out_, tag);
        pc += length;
      }
      auto [target, length] = owner_->read_u32v<ValidationTag>(pc);
      PrintDepthAsLabel(target);
      pc += length;
    }
  }
References v8::internal::wasm::ImmediatesPrinter< ValidationTag >::CatchKindToString(), v8::internal::wasm::kCatch, v8::internal::wasm::kCatchRef, v8::internal::length, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel(), v8::internal::wasm::NamesProvider::PrintTagName(), v8::internal::wasm::Decoder::read_u32v(), v8::internal::wasm::Decoder::read_u8(), v8::internal::wasm::BranchTableImmediate::table, and v8::internal::wasm::BranchTableImmediate::table_count.
TypeIndex()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TypeIndex (TypeIndexImmediate & imm) [inline]
Definition at line 536 of file wasm-disassembler.cc.
                                          {
    out_ << " ";
    names()->PrintTypeName(out_, imm.index);
    use_type(imm.index);
  }
References v8::internal::wasm::TypeIndexImmediate::index, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::NamesProvider::PrintTypeName(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::use_type().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::Field().
use_type()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::use_type (ModuleTypeIndex type_index) [inline], [private]
Definition at line 718 of file wasm-disassembler.cc.
                                            {
    owner_->used_types_.insert(type_index.index);
  }
References v8::internal::wasm::TypeIndex::index, v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_, and v8::internal::wasm::FunctionBodyDisassembler::used_types_.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ArrayCopy(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::HeapType(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TypeIndex(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ValueType().
ValueType()
template<typename ValidationTag >
void v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ValueType (ValueType type) [inline]
Definition at line 408 of file wasm-disassembler.cc.
                                 {
    out_ << " ";
    names()->PrintValueType(out_, type);
    if (type.has_index()) use_type(type.ref_index());
  }
References v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_, v8::internal::wasm::NamesProvider::PrintValueType(), v8::internal::tracing::type, and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::use_type().
Member Data Documentation
out_
template<typename ValidationTag >
StringBuilder& v8::internal::wasm::ImmediatesPrinter< ValidationTag >::out_ [private]
Definition at line 726 of file wasm-disassembler.cc.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ArrayCopy(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::BlockType(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::DataSegmentIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::EffectHandlerTable(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ElemSegmentIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::F32Const(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::F64Const(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::Field(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::FunctionIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::GlobalIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::HeapType(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::I32Const(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::I64Const(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::Length(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::LocalIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryAccess(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryCopy(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryInit(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryOrder(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintSignature(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::S128Const(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::SelectType(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::SimdLane(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::StringConst(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TableCopy(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TableIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TagIndex(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TryTable(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TypeIndex(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::ValueType().
owner_
template<typename ValidationTag >
FunctionBodyDisassembler* v8::internal::wasm::ImmediatesPrinter< ValidationTag >::owner_ [private]
Definition at line 727 of file wasm-disassembler.cc.
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::BranchTable(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::EffectHandlerTable(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::F32Const(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::F64Const(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::func_index(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::MemoryAccess(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::names(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintSignature(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::S128Const(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::StringConst(), v8::internal::wasm::ImmediatesPrinter< ValidationTag >::TryTable(), and v8::internal::wasm::ImmediatesPrinter< ValidationTag >::use_type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-disassembler-impl.h
/mnt/V8SourceCode/src/wasm/wasm-disassembler.cc