v8::internal::PlainBuffer< T > Class Template Reference
Public Member Functions
T * data ()
void EnsureCapacity (size_t new_capacity)
Private Attributes
std::unique_ptr< T[]> data_
size_t capacity_ {0}
Detailed Description
template<typename T>
class v8::internal::PlainBuffer< T >
Definition at line 79 of file context-deserializer.cc.
Member Function Documentation
data()
template<typename T >
T* v8::internal::PlainBuffer< T >::data () [inline]
Definition at line 81 of file context-deserializer.cc.
{ return data_.get(); }
References v8::internal::PlainBuffer< T >::data_.
Referenced by v8::internal::ContextDeserializer::DeserializeApiWrapperFields(), and v8::internal::ContextDeserializer::DeserializeEmbedderFields().
EnsureCapacity()
template<typename T >
void v8::internal::PlainBuffer< T >::EnsureCapacity (size_t new_capacity) [inline]
Definition at line 83 of file context-deserializer.cc.
                                           {
    if (new_capacity > capacity_) {
      data_.reset(new T[new_capacity]);
      capacity_ = new_capacity;
    }
  }
References v8::internal::PlainBuffer< T >::capacity_, and v8::internal::PlainBuffer< T >::data_.
Referenced by v8::internal::ContextDeserializer::DeserializeApiWrapperFields(), and v8::internal::ContextDeserializer::DeserializeEmbedderFields().
Member Data Documentation
capacity_
template<typename T >
size_t v8::internal::PlainBuffer< T >::capacity_ {0} [private]
Definition at line 92 of file context-deserializer.cc.
Referenced by v8::internal::PlainBuffer< T >::EnsureCapacity().
data_
template<typename T >
std::unique_ptr<T[]> v8::internal::PlainBuffer< T >::data_ [private]
Definition at line 91 of file context-deserializer.cc.
Referenced by v8::internal::PlainBuffer< T >::data(), and v8::internal::PlainBuffer< T >::EnsureCapacity().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/snapshot/context-deserializer.cc