v8::internal::torque::ImplementationVisitor Class Reference
#include <implementation-visitor.h>
Classes
struct BindingsManagersScope
class BreakContinueActivator
class MacroInliningScope
class StackScope
Public Member Functions
void GenerateBuiltinDefinitionsAndInterfaceDescriptors (const std::string &output_directory)
void GenerateVisitorLists (const std::string &output_directory)
void GenerateBitFields (const std::string &output_directory)
void GeneratePrintDefinitions (const std::string &output_directory)
void GenerateClassDefinitions (const std::string &output_directory)
void GenerateBodyDescriptors (const std::string &output_directory)
void GenerateInstanceTypes (const std::string &output_directory)
void GenerateClassVerifiers (const std::string &output_directory)
void GenerateEnumVerifiers (const std::string &output_directory)
void GenerateClassDebugReaders (const std::string &output_directory)
void GenerateExportedMacrosAssembler (const std::string &output_directory)
void GenerateCSATypes (const std::string &output_directory)
VisitResult Visit (Expression *expr)
const Type * Visit (Statement *stmt)
template<typename T >
void CheckInitializersWellformed (const std::string &aggregate_name, const std::vector< T > &aggregate_fields, const std::vector< NameAndExpression > &initializers, bool ignore_first_field=false)
InitializerResults VisitInitializerResults (const ClassType *class_type, const std::vector< NameAndExpression > &expressions)
LocationReference GenerateFieldReference (VisitResult object, const Field &field, const ClassType *class_type, bool treat_optional_as_indexed=false)
LocationReference GenerateFieldReferenceForInit (VisitResult object, const Field &field, const LayoutForInitialization &layout)
VisitResult GenerateArrayLength (Expression *array_length, Namespace *nspace, const std::map< std::string, LocalValue > &bindings)
VisitResult GenerateArrayLength (VisitResult object, const Field &field)
VisitResult GenerateArrayLength (const ClassType *class_type, const InitializerResults &initializer_results, const Field &field)
LayoutForInitialization GenerateLayoutForInitialization (const ClassType *class_type, const InitializerResults &initializer_results)
void InitializeClass (const ClassType *class_type, VisitResult allocate_result, const InitializerResults &initializer_results, const LayoutForInitialization &layout)
VisitResult Visit (StructExpression *decl)
LocationReference GetLocationReference (Expression *location)
LocationReference LookupLocalValue (const std::string &name)
LocationReference GetLocationReference (IdentifierExpression *expr)
LocationReference GetLocationReference (DereferenceExpression *expr)
LocationReference GetLocationReference (FieldAccessExpression *expr)
LocationReference GenerateFieldAccess (LocationReference reference, const std::string &fieldname, bool ignore_stuct_field_constness=false, std::optional< SourcePosition > pos={})
LocationReference GetLocationReference (ElementAccessExpression *expr)
LocationReference GenerateReferenceToItemInHeapSlice (LocationReference slice, VisitResult index)
VisitResult GenerateFetchFromLocation (const LocationReference &reference)
VisitResult GetBuiltinCode (Builtin *builtin)
VisitResult Visit (LocationExpression *expr)
VisitResult Visit (FieldAccessExpression *expr)
void VisitAllDeclarables ()
void Visit (Declarable *delarable, std::optional< SourceId > file={})
void Visit (TypeAlias *decl)
VisitResult InlineMacro (Macro *macro, std::optional< LocationReference > this_reference, const std::vector< VisitResult > &arguments, const std::vector< Block * > label_blocks)
void VisitMacroCommon (Macro *macro)
void Visit (ExternMacro *macro)
void Visit (TorqueMacro *macro)
void Visit (Method *macro)
void Visit (Builtin *builtin)
void Visit (NamespaceConstant *decl)
VisitResult Visit (CallExpression *expr, bool is_tail=false)
VisitResult Visit (CallMethodExpression *expr)
VisitResult Visit (IntrinsicCallExpression *intrinsic)
const Type * Visit (TailCallStatement *stmt)
VisitResult Visit (ConditionalExpression *expr)
VisitResult Visit (LogicalOrExpression *expr)
VisitResult Visit (LogicalAndExpression *expr)
VisitResult Visit (IncrementDecrementExpression *expr)
VisitResult Visit (AssignmentExpression *expr)
VisitResult Visit (StringLiteralExpression *expr)
VisitResult Visit (FloatingPointLiteralExpression *expr)
VisitResult Visit (IntegerLiteralExpression *expr)
VisitResult Visit (AssumeTypeImpossibleExpression *expr)
VisitResult Visit (TryLabelExpression *expr)
VisitResult Visit (StatementExpression *expr)
VisitResult Visit (NewExpression *expr)
VisitResult Visit (SpreadExpression *expr)
const Type * Visit (ReturnStatement *stmt)
const Type * Visit (GotoStatement *stmt)
const Type * Visit (IfStatement *stmt)
const Type * Visit (WhileStatement *stmt)
const Type * Visit (BreakStatement *stmt)
const Type * Visit (ContinueStatement *stmt)
const Type * Visit (ForLoopStatement *stmt)
const Type * Visit (VarDeclarationStatement *stmt)
const Type * Visit (VarDeclarationStatement *stmt, BlockBindings< LocalValue > *block_bindings)
const Type * Visit (BlockStatement *block)
const Type * Visit (ExpressionStatement *stmt)
const Type * Visit (DebugStatement *stmt)
const Type * Visit (AssertStatement *stmt)
void BeginGeneratedFiles ()
void EndGeneratedFiles ()
void BeginDebugMacrosFile ()
void EndDebugMacrosFile ()
void GenerateImplementation (const std::string &dir)
DECLARE_CONTEXTUAL_VARIABLE (ValueBindingsManager, BindingsManager< LocalValue >)
DECLARE_CONTEXTUAL_VARIABLE (LabelBindingsManager, BindingsManager< LocalLabel >)
DECLARE_CONTEXTUAL_VARIABLE (CurrentCallable, Callable *)
DECLARE_CONTEXTUAL_VARIABLE (CurrentFileStreams, GlobalContext::PerFileStreams *)
DECLARE_CONTEXTUAL_VARIABLE (CurrentReturnValue, std::optional< VisitResult >)
void SetDryRun (bool is_dry_run)
Private Member Functions
std::optional< Block * > GetCatchBlock ()
void GenerateCatchBlock (std::optional< Block * > catch_block)
std::optional< Binding< LocalValue > * > TryLookupLocalValue (const std::string &name)
std::optional< Binding< LocalLabel > * > TryLookupLabel (const std::string &name)
Binding< LocalLabel > * LookupLabel (const std::string &name)
Block * LookupSimpleLabel (const std::string &name)
template<class Container >
Callable * LookupCallable (const QualifiedName &name, const Container &declaration_container, const TypeVector &types, const std::vector< Binding< LocalLabel > * > &labels, const TypeVector &specialization_types, bool silence_errors=false)
bool TestLookupCallable (const QualifiedName &name, const TypeVector &parameter_types)
template<class Container >
Callable * LookupCallable (const QualifiedName &name, const Container &declaration_container, const Arguments &arguments, const TypeVector &specialization_types)
Method * LookupMethod (const std::string &name, const AggregateType *receiver_type, const Arguments &arguments, const TypeVector &specialization_types)
TypeArgumentInference InferSpecializationTypes (GenericCallable *generic, const TypeVector &explicit_specialization_types, const TypeVector &explicit_arguments)
const Type * GetCommonType (const Type *left, const Type *right)
VisitResult GenerateCopy (const VisitResult &to_copy)
void GenerateAssignToLocation (const LocationReference &reference, const VisitResult &assignment_value)
void AddCallParameter (Callable *callable, VisitResult parameter, const Type *parameter_type, std::vector< VisitResult > *converted_arguments, StackRange *argument_range, std::vector< std::string > *constexpr_arguments, bool inline_macro)
VisitResult GenerateCall (Callable *callable, std::optional< LocationReference > this_parameter, Arguments parameters, const TypeVector &specialization_types={}, bool tail_call=false)
VisitResult GenerateCall (const QualifiedName &callable_name, Arguments parameters, const TypeVector &specialization_types={}, bool tail_call=false)
VisitResult GenerateCall (std::string callable_name, Arguments parameters, const TypeVector &specialization_types={}, bool tail_call=false)
VisitResult GeneratePointerCall (Expression *callee, const Arguments &parameters, bool tail_call)
void GenerateBranch (const VisitResult &condition, Block *true_block, Block *false_block)
VisitResult GenerateBoolConstant (bool constant)
void GenerateExpressionBranch (Expression *expression, Block *true_block, Block *false_block)
cpp::Function GenerateMacroFunctionDeclaration (Macro *macro)
cpp::Function GenerateFunction (cpp::Class *owner, const std::string &name, const Signature &signature, const NameVector &parameter_names, bool pass_code_assembler_state=true, std::vector< std::string > *generated_parameter_names=nullptr)
VisitResult GenerateImplicitConvert (const Type *destination_type, VisitResult source)
StackRange GenerateLabelGoto (LocalLabel *label, std::optional< StackRange > arguments={})
VisitResult GenerateSetBitField (const Type *bitfield_struct_type, const BitField &bitfield, VisitResult bitfield_struct, VisitResult value, bool starts_as_zero=false)
std::vector< Binding< LocalLabel > * > LabelsFromIdentifiers (const std::vector< Identifier * > &names)
StackRange LowerParameter (const Type *type, const std::string &parameter_name, Stack< std::string > *lowered_parameters)
void LowerLabelParameter (const Type *type, const std::string &parameter_name, std::vector< std::string > *lowered_parameters)
std::string ExternalLabelName (const std::string &label_name)
std::string ExternalLabelParameterName (const std::string &label_name, size_t i)
std::string ExternalParameterName (const std::string &name)
std::ostream & csa_ccfile ()
std::ostream & csa_headerfile ()
CfgAssembler & assembler ()
void SetReturnValue (VisitResult return_value)
VisitResult GetAndClearReturnValue ()
void WriteFile (const std::string &file, const std::string &content)
const Identifier * TryGetSourceForBitfieldExpression (const Expression *expr) const
void PropagateBitfieldMark (const Expression *original, const Expression *derived)
Private Attributes
std::optional< CfgAssembler > assembler_
NullOStream null_stream_
bool is_dry_run_
std::unordered_map< const Expression *, const Identifier * > bitfield_expressions_
std::unordered_set< const Macro * > inlining_macros_
std::stringstream debug_macros_cc_
std::stringstream debug_macros_h_
OutputType output_type_ = OutputType::kCSA
Detailed Description
Definition at line 449 of file implementation-visitor.h.
Member Function Documentation
AddCallParameter()
void v8::internal::torque::ImplementationVisitor::AddCallParameter (Callable * callable, VisitResult parameter, const Type * parameter_type, std::vector< VisitResult > * converted_arguments, StackRange * argument_range, std::vector< std::string > * constexpr_arguments, bool inline_macro) [private]
Definition at line 2740 of file implementation-visitor.cc.
                                                                  {
  VisitResult converted;
  if ((converted_arguments->size() < callable->signature().implicit_count) &&
      parameter.type()->IsTopType()) {
    converted = GenerateCopy(parameter);
  } else {
    converted = GenerateImplicitConvert(parameter_type, parameter);
  }
  converted_arguments->push_back(converted);
  if (!inline_macro) {
    if (converted.IsOnStack()) {
      argument_range->Extend(converted.stack_range());
    } else {
      constexpr_arguments->push_back(converted.constexpr_value());
    }
  }
}
References v8::internal::torque::VisitResult::constexpr_value(), v8::internal::torque::StackRange::Extend(), v8::internal::torque::VisitResult::IsOnStack(), v8::internal::torque::Callable::signature(), v8::internal::torque::VisitResult::stack_range(), and v8::internal::torque::VisitResult::type().
assembler()
CfgAssembler& v8::internal::torque::ImplementationVisitor::assembler () [inline], [private]
Definition at line 828 of file implementation-visitor.h.
{ return *assembler_; }
References assembler_.
Referenced by GenerateCopy(), GenerateFetchFromLocation(), GenerateFieldAccess(), GenerateFieldReferenceForInit(), GenerateSetBitField(), GetLocationReference(), and Visit().
BeginDebugMacrosFile()
void v8::internal::torque::ImplementationVisitor::BeginDebugMacrosFile ()
Definition at line 175 of file implementation-visitor.cc.
                                                 {
  // TODO(torque-builer): Can use builder for debug_macros_*_
  std::ostream& source = debug_macros_cc_;
  std::ostream& header = debug_macros_h_;
  source << "#include \"torque-generated/debug-macros.h\"\n\n";
  source << "\n";
  source << "// The following includes are here to provide some constants "
            "definitions.\n";
  source << "#include \"src/objects/swiss-name-dictionary.h\"\n";
  source << "#include \"src/objects/ordered-hash-table.h\"\n";
  source << "#include \"src/objects/prototype-info.h\"\n";
  source << "\n";
  source << "#include \"src/torque/runtime-support.h\"\n";
  source << "#include \"tools/debug_helper/debug-macro-shims.h\"\n";
  source << "#include \"include/v8-internal.h\"\n";
  source << "\n";
  source << "namespace v8 {\n"
         << "namespace internal {\n"
         << "namespace debug_helper_internal {\n"
         << "\n";
  const char* kHeaderDefine = "V8_GEN_TORQUE_GENERATED_DEBUG_MACROS_H_";
  header << "#ifndef " << kHeaderDefine << "\n";
  header << "#define " << kHeaderDefine << "\n\n";
  header << "#include \"tools/debug_helper/debug-helper-internal.h\"\n";
  header << "#include \"src/numbers/integer-literal.h\"\n";
  header << "\n";
  header << "namespace v8 {\n"
         << "namespace internal {\n"
         << "namespace debug_helper_internal {\n"
         << "\n";
}
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
BeginGeneratedFiles()
void v8::internal::torque::ImplementationVisitor::BeginGeneratedFiles ()
Definition at line 76 of file implementation-visitor.cc.
                                                {
  std::set<SourceId> contains_class_definitions;
  std::set<SourceId> contains_class_asserts;
  for (const ClassType* type : TypeOracle::GetClasses()) {
    if (type->ShouldGenerateCppClassDefinitions()) {
      contains_class_definitions.insert(type->AttributedToFile());
    }
    if (type->ShouldGenerateCppObjectDefinitionAsserts() ||
        type->ShouldGenerateCppObjectLayoutDefinitionAsserts()) {
      contains_class_asserts.insert(type->AttributedToFile());
    }
  }
  for (SourceId source : SourceFileMap::AllSources()) {
    auto& streams = GlobalContext::GeneratedPerFile(source);
    // Output beginning of CSA .cc file.
    {
      cpp::File& file = streams.csa_cc;
      for (const std::string& include_path : GlobalContext::CppIncludes()) {
        file << "#include " << StringLiteralQuote(include_path) << "\n";
      }
      file << "#include \"src/codegen/code-stub-assembler-inl.h\"\n";
      file << "// Required Builtins:\n";
      file << "#include \"torque-generated/" +
                  SourceFileMap::PathFromV8RootWithoutExtension(source) +
                  "-tq-csa.h\"\n";
      // Now that required include files are collected while generating the
      // file, we only know the full set at the end. Insert a marker here that
      // is replaced with the list of includes at the very end.
      // TODO(nicohartmann@): This is not the most beautiful way to do this,
      // replace once the cpp file builder is available, where this can be
      // handled easily.
      file << BuiltinIncludesMarker;
      file << "\n";
      streams.csa_cc.BeginNamespace("v8", "internal");
      streams.csa_ccfile << "\n";
    }
    // Output beginning of CSA .h file.
    {
      cpp::File& file = streams.csa_header;
      std::string header_define =
          "V8_GEN_TORQUE_GENERATED_" +
          UnderlinifyPath(SourceFileMap::PathFromV8Root(source)) + "_CSA_H_";
      streams.csa_header.BeginIncludeGuard(header_define);
      file << "#include \"src/builtins/torque-csa-header-includes.h\"\n";
      file << "\n";
      streams.csa_header.BeginNamespace("v8", "internal");
      streams.csa_headerfile << "\n";
    }
    // Output beginning of class definition .cc file.
    {
      cpp::File& file = streams.class_definition_cc;
      if (contains_class_definitions.count(source) != 0) {
        file << "#include \""
             << SourceFileMap::PathFromV8RootWithoutExtension(source)
             << "-inl.h\"\n\n";
        file << "#include \"torque-generated/class-verifiers.h\"\n";
        file << "#include \"src/objects/objects-inl.h\"\n\n";
        file << "#include \"src/objects/instance-type-inl.h\"\n\n";
      }
      if (contains_class_asserts.count(source) != 0) {
        file << "#include \""
             << SourceFileMap::PathFromV8RootWithoutExtension(source)
             << ".h\"\n\n";
      }
      streams.class_definition_cc.BeginNamespace("v8", "internal");
      streams.class_definition_ccfile << "\n";
    }
  }
}
References v8::internal::torque::SourceFileMap::AllSources(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::BuiltinIncludesMarker, v8::internal::torque::GlobalContext::CppIncludes(), file(), v8::internal::torque::GlobalContext::GeneratedPerFile(), v8::internal::torque::TypeOracle::GetClasses(), v8::internal::torque::SourceFileMap::PathFromV8Root(), v8::internal::torque::SourceFileMap::PathFromV8RootWithoutExtension(), v8::internal::string, v8::internal::torque::StringLiteralQuote(), v8::internal::tracing::type, and v8::internal::torque::UnderlinifyPath().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
CheckInitializersWellformed()
template<typename T >
void v8::internal::torque::ImplementationVisitor::CheckInitializersWellformed (const std::string & aggregate_name, const std::vector< T > & aggregate_fields, const std::vector< NameAndExpression > & initializers, bool ignore_first_field = false) [inline]
Definition at line 469 of file implementation-visitor.h.
                                       {
    size_t fields_offset = ignore_first_field ? 1 : 0;
    size_t fields_size = aggregate_fields.size() - fields_offset;
    for (size_t i = 0; i < std::min(fields_size, initializers.size()); i++) {
      const std::string& field_name =
          aggregate_fields[i + fields_offset].name_and_type.name;
      Identifier* found_name = initializers[i].name;
      if (field_name != found_name->value) {
        Error("Expected field name \"", field_name, "\" instead of \"",
              found_name->value, "\"")
            .Position(found_name->pos)
            .Throw();
      }
    }
    if (fields_size != initializers.size()) {
      ReportError("expected ", fields_size, " initializers for ",
                  aggregate_name, " found ", initializers.size());
    }
  }
References v8::internal::torque::Error(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::AstNode::pos, v8::internal::torque::MessageBuilder::Position(), v8::internal::torque::ReportError(), v8::internal::string, v8::internal::torque::MessageBuilder::Throw(), and v8::internal::torque::Identifier::value.
Referenced by Visit().
csa_ccfile()
std::ostream& v8::internal::torque::ImplementationVisitor::csa_ccfile () [inline], [private]
Definition at line 797 of file implementation-visitor.h.
                           {
    if (auto* streams = CurrentFileStreams::Get()) {
      switch (output_type_) {
        case OutputType::kCSA:
          return streams->csa_ccfile;
        case OutputType::kCC:
          return streams->class_definition_inline_headerfile_macro_definitions;
        case OutputType::kCCDebug:
          return debug_macros_cc_;
        default:
          UNREACHABLE();
      }
    }
    return null_stream_;
  }
References debug_macros_cc_, v8::internal::compiler::turboshaft::Get(), v8::internal::torque::kCC, v8::internal::torque::kCCDebug, v8::internal::torque::kCSA, null_stream_, output_type_, and v8::internal::UNREACHABLE().
csa_headerfile()
std::ostream& v8::internal::torque::ImplementationVisitor::csa_headerfile () [inline], [private]
Definition at line 812 of file implementation-visitor.h.
                               {
    if (auto* streams = CurrentFileStreams::Get()) {
      switch (output_type_) {
        case OutputType::kCSA:
          return streams->csa_headerfile;
        case OutputType::kCC:
          return streams->class_definition_inline_headerfile_macro_declarations;
        case OutputType::kCCDebug:
          return debug_macros_h_;
        default:
          UNREACHABLE();
      }
    }
    return null_stream_;
  }
References debug_macros_h_, v8::internal::compiler::turboshaft::Get(), v8::internal::torque::kCC, v8::internal::torque::kCCDebug, v8::internal::torque::kCSA, null_stream_, output_type_, and v8::internal::UNREACHABLE().
DECLARE_CONTEXTUAL_VARIABLE() [1/5]
v8::internal::torque::ImplementationVisitor::DECLARE_CONTEXTUAL_VARIABLE (CurrentCallable , Callable *)
DECLARE_CONTEXTUAL_VARIABLE() [2/5]
v8::internal::torque::ImplementationVisitor::DECLARE_CONTEXTUAL_VARIABLE (CurrentFileStreams , GlobalContext::PerFileStreams *)
DECLARE_CONTEXTUAL_VARIABLE() [3/5]
v8::internal::torque::ImplementationVisitor::DECLARE_CONTEXTUAL_VARIABLE (CurrentReturnValue , std::optional< VisitResult >)
DECLARE_CONTEXTUAL_VARIABLE() [4/5]
v8::internal::torque::ImplementationVisitor::DECLARE_CONTEXTUAL_VARIABLE (LabelBindingsManager , BindingsManager< LocalLabel >)
DECLARE_CONTEXTUAL_VARIABLE() [5/5]
v8::internal::torque::ImplementationVisitor::DECLARE_CONTEXTUAL_VARIABLE (ValueBindingsManager , BindingsManager< LocalValue >)
EndDebugMacrosFile()
void v8::internal::torque::ImplementationVisitor::EndDebugMacrosFile ()
Definition at line 211 of file implementation-visitor.cc.
                                               {
  // TODO(torque-builder): Can use builder for debug_macros_*_
  std::ostream& source = debug_macros_cc_;
  std::ostream& header = debug_macros_h_;
  source << "} // namespace internal\n"
         << "} // namespace v8\n"
         << "} // namespace debug_helper_internal\n"
         << "\n";
  header << "\n} // namespace internal\n"
         << "} // namespace v8\n"
         << "} // namespace debug_helper_internal\n"
         << "\n";
  header << "#endif // V8_GEN_TORQUE_GENERATED_DEBUG_MACROS_H_\n";
}
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
EndGeneratedFiles()
void v8::internal::torque::ImplementationVisitor::EndGeneratedFiles ()
Definition at line 152 of file implementation-visitor.cc.
                                              {
  for (SourceId file : SourceFileMap::AllSources()) {
    auto& streams = GlobalContext::GeneratedPerFile(file);
    // Output ending of CSA .cc file.
    streams.csa_cc.EndNamespace("v8", "internal");
    // Output ending of CSA .h file.
    {
      std::string header_define =
          "V8_GEN_TORQUE_GENERATED_" +
          UnderlinifyPath(SourceFileMap::PathFromV8Root(file)) + "_CSA_H_";
      streams.csa_header.EndNamespace("v8", "internal");
      streams.csa_headerfile << "\n";
      streams.csa_header.EndIncludeGuard(header_define);
    }
    // Output ending of class definition .cc file.
    streams.class_definition_cc.EndNamespace("v8", "internal");
  }
}
References v8::internal::torque::SourceFileMap::AllSources(), file(), v8::internal::torque::GlobalContext::GeneratedPerFile(), v8::internal::torque::SourceFileMap::PathFromV8Root(), v8::internal::string, and v8::internal::torque::UnderlinifyPath().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
ExternalLabelName()
std::string v8::internal::torque::ImplementationVisitor::ExternalLabelName (const std::string & label_name) [private]
Definition at line 3476 of file implementation-visitor.cc.
                                 {
  return "label_" + label_name;
}
Referenced by GenerateFunction().
ExternalLabelParameterName()
std::string v8::internal::torque::ImplementationVisitor::ExternalLabelParameterName (const std::string & label_name, size_t i) [private]
Definition at line 3481 of file implementation-visitor.cc.
                                           {
  return "label_" + label_name + "_parameter_" + std::to_string(i);
}
Referenced by GenerateFunction().
ExternalParameterName()
std::string v8::internal::torque::ImplementationVisitor::ExternalParameterName (const std::string & name) [private]
Definition at line 3486 of file implementation-visitor.cc.
                           {
  return std::string("p_") + name;
}
References v8::internal::name, and v8::internal::string.
Referenced by GenerateFunction().
GenerateArrayLength() [1/3]
VisitResult v8::internal::torque::ImplementationVisitor::GenerateArrayLength (const ClassType * class_type, const InitializerResults & initializer_results, const Field & field)
Definition at line 1614 of file implementation-visitor.cc.
                        {
  DCHECK(field.index);
  StackScope stack_scope(this);
  std::map<std::string, LocalValue> bindings;
  for (const Field& f : class_type->ComputeAllFields()) {
    if (f.index) break;
    const std::string& fieldname = f.name_and_type.name;
    VisitResult value = initializer_results.field_value_map.at(fieldname);
    bindings.insert(
        {fieldname,
         f.const_qualified
             ? LocalValue{LocationReference::Temporary(
                   value, "initial field " + fieldname)}
             : LocalValue(
                   "Non-const fields cannot be used for array lengths.")});
  }
  return stack_scope.Yield(
      GenerateArrayLength(field.index->expr, class_type->nspace(), bindings));
}
References v8_inspector::V8RuntimeAgentImplState::bindings, v8::internal::torque::ClassType::ComputeAllFields(), v8::internal::DCHECK(), v8::internal::torque::InitializerResults::field_value_map, GenerateArrayLength(), v8::internal::torque::Field::index, v8::internal::torque::AggregateType::nspace(), v8::internal::string, v8::internal::torque::LocationReference::Temporary(), v8::internal::value, and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
GenerateArrayLength() [2/3]
VisitResult v8::internal::torque::ImplementationVisitor::GenerateArrayLength (Expression * array_length, Namespace * nspace, const std::map< std::string, LocalValue > & bindings)
Definition at line 1561 of file implementation-visitor.cc.
                                                   {
  StackScope stack_scope(this);
  CurrentSourcePosition::Scope pos_scope(array_length->pos);
  // Switch to the namespace where the class was declared.
  CurrentScope::Scope current_scope_scope(nspace);
  // Reset local bindings and install local binding for the preceding fields.
  BindingsManagersScope bindings_managers_scope;
  BlockBindings<LocalValue> field_bindings(&ValueBindingsManager::Get());
  for (auto& p : bindings) {
    field_bindings.Add(p.first, LocalValue{p.second}, true);
  }
  VisitResult length = Visit(array_length);
  VisitResult converted_length =
      GenerateCall("Convert", Arguments{{length}, {}},
                   {TypeOracle::GetIntPtrType(), length.type()}, false);
  return stack_scope.Yield(converted_length);
}
References v8::internal::torque::BlockBindings< T >::Add(), v8_inspector::V8RuntimeAgentImplState::bindings, GenerateCall(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::TypeOracle::GetIntPtrType(), v8::internal::length, v8::internal::torque::AstNode::pos, Visit(), and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Referenced by GenerateArrayLength(), and GenerateLayoutForInitialization().
GenerateArrayLength() [3/3]
VisitResult v8::internal::torque::ImplementationVisitor::GenerateArrayLength (VisitResult object, const Field & field)
Definition at line 1581 of file implementation-visitor.cc.
                                                                           {
  DCHECK(field.index);
  StackScope stack_scope(this);
  const ClassType* class_type = *object.type()->ClassSupertype();
  std::map<std::string, LocalValue> bindings;
  bool before_current = true;
  for (const Field& f : class_type->ComputeAllFields()) {
    if (field.name_and_type.name == f.name_and_type.name) {
      before_current = false;
    }
    // We can't generate field references eagerly here, because some preceding
    // fields might be optional, and attempting to get a reference to an
    // optional field can crash the program if the field isn't present.
    // Instead, we use the lazy form of LocalValue to only generate field
    // references if they are used in the length expression.
    bindings.insert(
        {f.name_and_type.name,
         f.const_qualified
             ? (before_current
                    ? LocalValue{[this, object, f, class_type]() {
                        return GenerateFieldReference(object, f, class_type);
                      }}
                    : LocalValue("Array lengths may only refer to fields "
                                 "defined earlier"))
             : LocalValue(
                   "Non-const fields cannot be used for array lengths.")});
  }
  return stack_scope.Yield(
      GenerateArrayLength(field.index->expr, class_type->nspace(), bindings));
}
References v8_inspector::V8RuntimeAgentImplState::bindings, v8::internal::torque::Type::ClassSupertype(), v8::internal::torque::ClassType::ComputeAllFields(), v8::internal::DCHECK(), GenerateArrayLength(), GenerateFieldReference(), v8::internal::torque::Field::index, v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::internal::torque::AggregateType::nspace(), and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
GenerateAssignToLocation()
void v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation (const LocationReference & reference, const VisitResult & assignment_value) [private]
Definition at line 2606 of file implementation-visitor.cc.
                                                                             {
  if (reference.IsCallAccess()) {
    Arguments arguments{reference.call_arguments(), {}};
    arguments.parameters.push_back(assignment_value);
    GenerateCall(reference.assign_function(), arguments);
  } else if (reference.IsVariableAccess()) {
    VisitResult variable = reference.variable();
    VisitResult converted_value =
        GenerateImplicitConvert(variable.type(), assignment_value);
    assembler().Poke(variable.stack_range(), converted_value.stack_range(),
                     variable.type());
    // Local variables are detected by the existence of a binding. Assignment
    // to local variables is recorded to support lint errors.
    if (reference.binding()) {
      (*reference.binding())->SetWritten();
    }
  } else if (reference.IsHeapSlice()) {
    ReportError("assigning a value directly to an indexed field isn't allowed");
  } else if (reference.IsHeapReference()) {
    const Type* referenced_type = *reference.ReferencedType();
    if (reference.IsConst()) {
      Error("cannot assign to const value of type ", *referenced_type).Throw();
    }
    if (referenced_type == TypeOracle::GetFloat64OrUndefinedOrHoleType()) {
      GenerateCall(
          QualifiedName({TORQUE_INTERNAL_NAMESPACE_STRING},
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
                        "StoreFloat64OrUndefinedOrHole"
#else
                        "StoreFloat64OrHole"
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
                        ),
          Arguments{{reference.heap_reference(), assignment_value}, {}});
    } else if (auto struct_type = referenced_type->StructSupertype()) {
      if (!assignment_value.type()->IsSubtypeOf(referenced_type)) {
        ReportError("Cannot assign to ", *referenced_type,
                    " with value of type ", *assignment_value.type());
      }
      for (const Field& field : (*struct_type)->fields()) {
        const std::string& fieldname = field.name_and_type.name;
        // Allow assignment of structs even if they contain const fields.
        // Const on struct fields just disallows direct writes to them.
        bool ignore_stuct_field_constness = true;
        GenerateAssignToLocation(
            GenerateFieldAccess(reference, fieldname,
                                ignore_stuct_field_constness),
            ProjectStructField(assignment_value, fieldname));
      }
    } else {
      GenerateCopy(reference.heap_reference());
      VisitResult converted_assignment_value =
          GenerateImplicitConvert(referenced_type, assignment_value);
      if (referenced_type == TypeOracle::GetFloat64Type()) {
        VisitResult silenced_float_value = GenerateCall(
            "Float64SilenceNaN", Arguments{{assignment_value}, {}});
        assembler().Poke(converted_assignment_value.stack_range(),
                         silenced_float_value.stack_range(), referenced_type);
      }
      assembler().Emit(StoreReferenceInstruction{referenced_type});
    }
  } else if (reference.IsBitFieldAccess()) {
    // First fetch the bitfield struct, then set the updated bits, then store
    // it back to where we found it.
    VisitResult bit_field_struct =
        GenerateFetchFromLocation(reference.bit_field_struct_location());
    VisitResult converted_value =
        GenerateImplicitConvert(*reference.ReferencedType(), assignment_value);
    VisitResult updated_bit_field_struct =
        GenerateSetBitField(bit_field_struct.type(), reference.bit_field(),
                            bit_field_struct, converted_value);
    GenerateAssignToLocation(reference.bit_field_struct_location(),
                             updated_bit_field_struct);
  } else {
    DCHECK(reference.IsTemporary());
    ReportError("cannot assign to const-bound or temporary ",
                reference.temporary_description());
  }
}
References v8::internal::torque::LocationReference::assign_function(), v8::internal::torque::LocationReference::binding(), v8::internal::torque::LocationReference::bit_field(), v8::internal::torque::LocationReference::bit_field_struct_location(), v8::internal::torque::LocationReference::call_arguments(), v8::internal::DCHECK(), v8::internal::torque::Error(), v8::internal::torque::LocationReference::heap_reference(), v8::internal::torque::LocationReference::IsBitFieldAccess(), v8::internal::torque::LocationReference::IsCallAccess(), v8::internal::torque::LocationReference::IsConst(), v8::internal::torque::LocationReference::IsHeapReference(), v8::internal::torque::LocationReference::IsHeapSlice(), v8::internal::compiler::turboshaft::Type::IsSubtypeOf(), v8::internal::torque::LocationReference::IsTemporary(), v8::internal::torque::LocationReference::IsVariableAccess(), v8::internal::torque::ProjectStructField(), v8::internal::torque::LocationReference::ReferencedType(), v8::internal::torque::ReportError(), v8::internal::torque::VisitResult::stack_range(), v8::internal::string, v8::internal::torque::Type::StructSupertype(), v8::internal::torque::LocationReference::temporary_description(), v8::internal::torque::MessageBuilder::Throw(), v8::internal::torque::TORQUE_INTERNAL_NAMESPACE_STRING, v8::internal::torque::VisitResult::type(), and v8::internal::torque::LocationReference::variable().
Referenced by InitializeClass().
GenerateBitFields()
void v8::internal::torque::ImplementationVisitor::GenerateBitFields (const std::string & output_directory)
Definition at line 3973 of file implementation-visitor.cc.
                                       {
  std::stringstream header;
  std::string file_name = "bit-fields.h";
  {
    IncludeGuardScope include_guard(header, file_name);
    header << "#include \"src/base/bit-field.h\"\n\n";
    NamespaceScope namespaces(header, {"v8", "internal"});
    for (const auto& type : TypeOracle::GetBitFieldStructTypes()) {
      bool all_single_bits = true; // Track whether every field is one bit.
      header << "// " << type->GetPosition() << "\n";
      header << "#define DEFINE_TORQUE_GENERATED_"
             << CapifyStringWithUnderscores(type->name()) << "() \\\n";
      std::string type_name = type->GetConstexprGeneratedTypeName();
      for (const auto& field : type->fields()) {
        const char* suffix = field.num_bits == 1 ? "Bit" : "Bits";
        all_single_bits = all_single_bits && field.num_bits == 1;
        std::string field_type_name =
            field.name_and_type.type->GetConstexprGeneratedTypeName();
        header << " using " << CamelifyString(field.name_and_type.name)
               << suffix << " = base::BitField<" << field_type_name << ", "
               << field.offset << ", " << field.num_bits << ", " << type_name
               << ">; \\\n";
      }
      // If every field is one bit, we can also generate a convenient enum.
      if (all_single_bits) {
        header << " enum Flag: " << type_name << " { \\\n";
        header << " kNone = 0, \\\n";
        for (const auto& field : type->fields()) {
          header << " k" << CamelifyString(field.name_and_type.name) << " = "
                 << type_name << "{1} << " << field.offset << ", \\\n";
        }
        header << " }; \\\n";
        header << " using Flags = base::Flags<Flag>; \\\n";
        header << " static constexpr int kFlagCount = "
               << type->fields().size() << "; \\\n";
      }
      header << "\n";
    }
  }
  const std::string output_header_path = output_directory + "/" + file_name;
  WriteFile(output_header_path, header.str());
}
References v8::internal::torque::CamelifyString(), v8::internal::torque::CapifyStringWithUnderscores(), v8::internal::string, and v8::internal::tracing::type.
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
GenerateBodyDescriptors()
void v8::internal::torque::ImplementationVisitor::GenerateBodyDescriptors (const std::string & output_directory)
Definition at line 5149 of file implementation-visitor.cc.
                                       {
  std::string file_name = "objects-body-descriptors-inl.inc";
  std::stringstream h_contents;
    for (const ClassType* type : TypeOracle::GetClasses()) {
      std::string name = type->name();
      if (!type->ShouldGenerateBodyDescriptor()) continue;
      bool has_array_fields = !type->HasStaticSize();
      std::vector<ObjectSlotKind> header_slot_kinds =
          type->ComputeHeaderSlotKinds();
      std::optional<ObjectSlotKind> array_slot_kind =
          type->ComputeArraySlotKind();
      DCHECK_EQ(has_array_fields, array_slot_kind.has_value());
      h_contents << "class " << name << "::BodyDescriptor final : public ";
      if (auto descriptor_name = MatchSimpleBodyDescriptor(type)) {
        h_contents << *descriptor_name << " {\n";
        h_contents << " public:\n";
      } else {
        h_contents << "BodyDescriptorBase {\n";
        h_contents << " public:\n";
        h_contents << " template <typename ObjectVisitor>\n";
        h_contents
            << " static inline void IterateBody(Tagged<Map> map, "
               "Tagged<HeapObject> obj, int object_size, ObjectVisitor* v) {\n";
        std::vector<ObjectSlotKind> slots = std::move(header_slot_kinds);
        if (has_array_fields) slots.push_back(*array_slot_kind);
        // Skip the map slot.
        slots.erase(slots.begin());
        size_t start_offset = TargetArchitecture::TaggedSize();
        size_t end_offset = start_offset;
        ObjectSlotKind section_kind;
        for (size_t i = 0; i <= slots.size(); ++i) {
          std::optional<ObjectSlotKind> next_section_kind;
          bool finished_section = false;
          if (i == 0) {
            next_section_kind = slots[i];
          } else if (i < slots.size()) {
            if (auto combined = Combine(section_kind, slots[i])) {
              next_section_kind = *combined;
            } else {
              next_section_kind = slots[i];
              finished_section = true;
            }
          } else {
            finished_section = true;
          }
          if (finished_section) {
            bool is_array_slot = i == slots.size() && has_array_fields;
            bool multiple_slots =
                is_array_slot ||
                (end_offset - start_offset > TargetArchitecture::TaggedSize());
            std::optional<std::string> iterate_command;
            switch (section_kind) {
              case ObjectSlotKind::kStrongPointer:
                iterate_command = "IteratePointer";
                break;
              case ObjectSlotKind::kMaybeObjectPointer:
                iterate_command = "IterateMaybeWeakPointer";
                break;
              case ObjectSlotKind::kCustomWeakPointer:
                iterate_command = "IterateCustomWeakPointer";
                break;
              case ObjectSlotKind::kNoPointer:
                break;
            }
            if (iterate_command) {
              if (multiple_slots) *iterate_command += "s";
              h_contents << " " << *iterate_command << "(obj, "
                         << start_offset;
              if (multiple_slots) {
                h_contents << ", "
                           << (i == slots.size() ? "object_size"
                                                 : std::to_string(end_offset));
              }
              h_contents << ", v);\n";
            }
            start_offset = end_offset;
          }
          if (i < slots.size()) section_kind = *next_section_kind;
          end_offset += TargetArchitecture::TaggedSize();
        }
        h_contents << " }\n\n";
      }
      h_contents << " static inline int SizeOf(Tagged<Map> map, "
                    "Tagged<HeapObject> raw_object) {\n";
      if (type->size().SingleValue()) {
        h_contents << " return " << *type->size().SingleValue() << ";\n";
      } else {
        // We use an UncheckedCast here because this is used for concurrent
        // marking, where we shouldn't re-read the map.
        h_contents << " return UncheckedCast<" << name
                   << ">(raw_object)->AllocatedSize();\n";
      }
      h_contents << " }\n\n";
      h_contents << "};\n";
    }
    WriteFile(output_directory + "/" + file_name, h_contents.str());
}
References v8::internal::Combine(), DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::MatchSimpleBodyDescriptor(), v8::internal::name, v8::internal::string, and v8::internal::tracing::type.
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
GenerateBoolConstant()
VisitResult v8::internal::torque::ImplementationVisitor::GenerateBoolConstant (bool constant) [private]
Definition at line 3370 of file implementation-visitor.cc.
                                                                     {
  return GenerateImplicitConvert(TypeOracle::GetBoolType(),
                                 VisitResult(TypeOracle::GetConstexprBoolType(),
                                             constant ? "true" : "false"));
}
Referenced by Visit().
GenerateBranch()
void v8::internal::torque::ImplementationVisitor::GenerateBranch (const VisitResult & condition, Block * true_block, Block * false_block) [private]
Definition at line 3362 of file implementation-visitor.cc.
                                                               {
  DCHECK_EQ(condition,
            VisitResult(TypeOracle::GetBoolType(), assembler().TopRange(1)));
  assembler().Branch(true_block, false_block);
}
References DCHECK_EQ.
GenerateBuiltinDefinitionsAndInterfaceDescriptors()
void v8::internal::torque::ImplementationVisitor::GenerateBuiltinDefinitionsAndInterfaceDescriptors (const std::string & output_directory)
Definition at line 3630 of file implementation-visitor.cc.
                                       {
  std::stringstream builtin_definitions;
  std::string builtin_definitions_file_name = "builtin-definitions.h";
  // This file contains plain interface descriptor definitions and has to be
  // included in the middle of interface-descriptors.h. Thus it is not a normal
  // header file and uses the .inc suffix instead of the .h suffix.
  std::stringstream interface_descriptors;
  std::string interface_descriptors_file_name = "interface-descriptors.inc";
  {
    IncludeGuardScope builtin_definitions_include_guard(
        builtin_definitions, builtin_definitions_file_name);
    builtin_definitions
        << "\n"
           "#define BUILTIN_LIST_FROM_TORQUE(CPP, TFJ, TFC, TFS, TFH, "
           "ASM) "
           "\\\n";
    for (auto& declarable : GlobalContext::AllDeclarables()) {
      Builtin* builtin = Builtin::DynamicCast(declarable.get());
      if (!builtin || builtin->IsExternal()) continue;
      if (builtin->IsStub()) {
        builtin_definitions << "TFC(" << builtin->ExternalName() << ", "
                            << builtin->ExternalName();
        if (!builtin->HasCustomInterfaceDescriptor()) {
          std::string descriptor_name = builtin->ExternalName() + "Descriptor";
          bool has_context_parameter =
              builtin->signature().HasContextParameter();
          size_t kFirstNonContextParameter = has_context_parameter ? 1 : 0;
          TypeVector return_types = LowerType(builtin->signature().return_type);
          interface_descriptors << "class " << descriptor_name
                                << " : public StaticCallInterfaceDescriptor<"
                                << descriptor_name << "> {\n";
          interface_descriptors << " public:\n";
          // Currently, no torque-defined builtins are directly exposed to
          // objects inside the sandbox via the code pointer table.
          interface_descriptors << " INTERNAL_DESCRIPTOR()\n";
          interface_descriptors << " SANDBOXING_MODE(kSandboxed)\n";
          if (has_context_parameter) {
            interface_descriptors << " DEFINE_RESULT_AND_PARAMETERS(";
          } else {
            interface_descriptors
                << " DEFINE_RESULT_AND_PARAMETERS_NO_CONTEXT(";
          }
          interface_descriptors << return_types.size();
          for (size_t i = kFirstNonContextParameter;
               i < builtin->parameter_names().size(); ++i) {
            Identifier* parameter = builtin->parameter_names()[i];
            interface_descriptors << ", k" << CamelifyString(parameter->value);
          }
          interface_descriptors << ")\n";
          interface_descriptors << " DEFINE_RESULT_AND_PARAMETER_TYPES(";
          PrintCommaSeparatedList(interface_descriptors, return_types,
                                  MachineTypeString);
          bool is_first = return_types.empty();
          for (size_t i = kFirstNonContextParameter;
               i < builtin->parameter_names().size(); ++i) {
            const Type* type = builtin->signature().parameter_types.types[i];
            interface_descriptors << (is_first ? "" : ", ")
                                  << MachineTypeString(type);
            is_first = false;
          }
          interface_descriptors << ")\n";
          interface_descriptors << " DECLARE_DEFAULT_DESCRIPTOR("
                                << descriptor_name << ")\n";
          interface_descriptors << "};\n\n";
        }
      } else {
        builtin_definitions << "TFJ(" << builtin->ExternalName();
        if (builtin->IsVarArgsJavaScript()) {
          builtin_definitions << ", kDontAdaptArgumentsSentinel";
        } else {
          DCHECK(builtin->IsFixedArgsJavaScript());
          // FixedArg javascript builtins need to offer the parameter
          // count.
          int parameter_count =
              static_cast<int>(builtin->signature().ExplicitCount());
          builtin_definitions << ", JSParameterCount(" << parameter_count
                              << ")";
          // And the receiver is explicitly declared.
          builtin_definitions << ", kReceiver";
          for (size_t i = builtin->signature().implicit_count;
               i < builtin->parameter_names().size(); ++i) {
            Identifier* parameter = builtin->parameter_names()[i];
            builtin_definitions << ", k" << CamelifyString(parameter->value);
          }
        }
      }
      builtin_definitions << ") \\\n";
    }
    builtin_definitions << "\n";
    builtin_definitions
        << "#define TORQUE_FUNCTION_POINTER_TYPE_TO_BUILTIN_MAP(V) \\\n";
    for (const BuiltinPointerType* type :
         TypeOracle::AllBuiltinPointerTypes()) {
      Builtin* example_builtin =
          Declarations::FindSomeInternalBuiltinWithType(type);
      if (!example_builtin) {
        CurrentSourcePosition::Scope current_source_position(
            SourcePosition{CurrentSourceFile::Get(), LineAndColumn::Invalid(),
                           LineAndColumn::Invalid()});
        ReportError("unable to find any builtin with type \"", *type, "\"");
      }
      builtin_definitions << " V(" << type->function_pointer_type_id() << ","
                          << example_builtin->ExternalName() << ")\\\n";
    }
    builtin_definitions << "\n";
  }
  WriteFile(output_directory + "/" + builtin_definitions_file_name,
            builtin_definitions.str());
  WriteFile(output_directory + "/" + interface_descriptors_file_name,
            interface_descriptors.str());
}
References v8::internal::torque::CamelifyString(), v8::internal::DCHECK(), v8::internal::torque::Callable::ExternalName(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::Builtin::HasCustomInterfaceDescriptor(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::Callable::IsExternal(), v8::internal::torque::Builtin::IsFixedArgsJavaScript(), v8::internal::torque::Builtin::IsStub(), v8::internal::torque::Builtin::IsVarArgsJavaScript(), v8::internal::torque::LowerType(), v8::internal::torque::MachineTypeString(), v8::internal::torque::Callable::parameter_names(), v8::internal::torque::PrintCommaSeparatedList(), v8::internal::torque::ReportError(), v8::internal::torque::Callable::signature(), size(), v8::internal::string, v8::internal::tracing::type, and v8::internal::torque::Identifier::value.
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
GenerateCall() [1/3]
VisitResult v8::internal::torque::ImplementationVisitor::GenerateCall (Callable * callable, std::optional< LocationReference > this_parameter, Arguments parameters, const TypeVector & specialization_types = {}, bool tail_call = false) [private]
Definition at line 2784 of file implementation-visitor.cc.
                      {
  CHECK(callable->Position().source.IsValid());
  if (auto stream = CurrentFileStreams::Get()) {
    stream->required_builtin_includes.insert(callable->Position().source);
  }
  const Type* return_type = callable->signature().return_type;
  if (is_tailcall) {
    if (Builtin* builtin = Builtin::DynamicCast(CurrentCallable::Get())) {
      const Type* outer_return_type = builtin->signature().return_type;
      if (!return_type->IsSubtypeOf(outer_return_type)) {
        Error("Cannot tailcall, type of result is ", *return_type,
              " but should be a subtype of ", *outer_return_type, ".");
      }
    } else {
      Error("Tail calls are only allowed from builtins");
    }
  }
  bool inline_macro = callable->ShouldBeInlined(output_type_);
  std::vector<VisitResult> implicit_arguments;
  for (size_t i = 0; i < callable->signature().implicit_count; ++i) {
    std::string implicit_name = callable->signature().parameter_names[i]->value;
    std::optional<Binding<LocalValue>*> val =
        TryLookupLocalValue(implicit_name);
    if (val) {
      implicit_arguments.push_back(
          GenerateFetchFromLocation((*val)->GetLocationReference(*val)));
    } else {
      VisitResult unititialized = VisitResult::TopTypeResult(
          "implicit parameter '" + implicit_name +
              "' is not defined when invoking " + callable->ReadableName() +
              " at " + PositionAsString(CurrentSourcePosition::Get()),
          callable->signature().parameter_types.types[i]);
      implicit_arguments.push_back(unititialized);
    }
    const Type* type = implicit_arguments.back().type();
    if (const TopType* top_type = TopType::DynamicCast(type)) {
      if (!callable->IsMacro() || callable->IsExternal()) {
        ReportError(
            "unititialized implicit parameters can only be passed to "
            "Torque-defined macros: the ",
            top_type->reason());
      }
      inline_macro = true;
    }
  }
  std::vector<VisitResult> converted_arguments;
  StackRange argument_range = assembler().TopRange(0);
  std::vector<std::string> constexpr_arguments;
  size_t current = 0;
  for (; current < callable->signature().implicit_count; ++current) {
    AddCallParameter(callable, implicit_arguments[current],
                     callable->signature().parameter_types.types[current],
                     &converted_arguments, &argument_range,
                     &constexpr_arguments, inline_macro);
  }
  if (this_reference) {
    DCHECK(callable->IsMethod());
    Method* method = Method::cast(callable);
    // By now, the this reference should either be a variable, a temporary or
    // a Slice. In either case the fetch of the VisitResult should succeed.
    VisitResult this_value = this_reference->GetVisitResult();
    if (inline_macro) {
      if (!this_value.type()->IsSubtypeOf(method->aggregate_type())) {
        ReportError("this parameter must be a subtype of ",
                    *method->aggregate_type(), " but it is of type ",
                    *this_value.type());
      }
    } else {
      AddCallParameter(callable, this_value, method->aggregate_type(),
                       &converted_arguments, &argument_range,
                       &constexpr_arguments, inline_macro);
    }
    ++current;
  }
  for (const auto& arg : arguments.parameters) {
    const Type* to_type = (current >= callable->signature().types().size())
                              ? TypeOracle::GetObjectType()
                              : callable->signature().types()[current++];
    AddCallParameter(callable, arg, to_type, &converted_arguments,
                     &argument_range, &constexpr_arguments, inline_macro);
  }
  size_t label_count = callable->signature().labels.size();
  if (label_count != arguments.labels.size()) {
    std::stringstream s;
    s << "unexpected number of otherwise labels for "
      << callable->ReadableName() << " (expected "
      << std::to_string(label_count) << " found "
      << std::to_string(arguments.labels.size()) << ")";
    ReportError(s.str());
  }
  if (callable->IsTransitioning()) {
    if (!CurrentCallable::Get()->IsTransitioning()) {
      std::stringstream s;
      s << *CurrentCallable::Get()
        << " isn't marked transitioning but calls the transitioning "
        << *callable;
      ReportError(s.str());
    }
  }
  if (auto* builtin = Builtin::DynamicCast(callable)) {
    std::optional<Block*> catch_block = GetCatchBlock();
    assembler().Emit(CallBuiltinInstruction{
        is_tailcall, builtin, argument_range.Size(), catch_block});
    GenerateCatchBlock(catch_block);
    if (is_tailcall) {
      return VisitResult::NeverResult();
    } else if (return_type->IsNever()) {
      assembler().Emit(AbortInstruction{AbortInstruction::Kind::kUnreachable});
      return VisitResult::NeverResult();
    } else {
      size_t slot_count = LoweredSlotCount(return_type);
      if (builtin->IsStub()) {
        if (slot_count < 1 || slot_count > 2) {
          ReportError(
              "Builtin with stub linkage is expected to return one or two "
              "values but returns ",
              slot_count);
        }
      } else {
        if (slot_count != 1) {
          ReportError(
              "Builtin with JS linkage is expected to return one value but "
              "returns ",
              slot_count);
        }
      }
      return VisitResult(return_type, assembler().TopRange(slot_count));
    }
  } else if (auto* macro = Macro::DynamicCast(callable)) {
    if (is_tailcall) {
      ReportError("can't tail call a macro");
    }
    macro->SetUsed();
    // If we're currently generating a C++ macro and it's calling another macro,
    // then we need to make sure that we also generate C++ code for the called
    // macro within the same -inl.inc file.
    if ((output_type_ == OutputType::kCC ||
         output_type_ == OutputType::kCCDebug) &&
        !inline_macro) {
      if (auto* torque_macro = TorqueMacro::DynamicCast(macro)) {
        auto* streams = CurrentFileStreams::Get();
        SourceId file = streams ? streams->file : SourceId::Invalid();
        GlobalContext::EnsureInCCOutputList(torque_macro, file);
      }
    }
    // TODO(torque-builder): Consider a function builder here.
    if (return_type->IsConstexpr()) {
      DCHECK_EQ(0, arguments.labels.size());
      std::stringstream result;
      result << "(";
      bool first = true;
      switch (output_type_) {
        case OutputType::kCSA: {
          if (auto* extern_macro = ExternMacro::DynamicCast(macro)) {
            result << extern_macro->external_assembler_name() << "(state_)."
                   << extern_macro->ExternalName() << "(";
          } else {
            result << macro->ExternalName() << "(state_";
            first = false;
          }
          break;
        }
        case OutputType::kCC: {
          auto* extern_macro = ExternMacro::DynamicCast(macro);
          CHECK_NOT_NULL(extern_macro);
          result << extern_macro->CCName() << "(";
          break;
        }
        case OutputType::kCCDebug: {
          auto* extern_macro = ExternMacro::DynamicCast(macro);
          CHECK_NOT_NULL(extern_macro);
          result << extern_macro->CCDebugName() << "(accessor";
          first = false;
          break;
        }
      }
      for (const VisitResult& arg : converted_arguments) {
        DCHECK(!arg.IsOnStack());
        if (!first) {
          result << ", ";
        }
        first = false;
        result << arg.constexpr_value();
      }
      result << "))";
      return VisitResult(return_type, result.str());
    } else if (inline_macro) {
      std::vector<Block*> label_blocks;
      label_blocks.reserve(arguments.labels.size());
      for (Binding<LocalLabel>* label : arguments.labels) {
        label_blocks.push_back(label->block);
      }
      return InlineMacro(macro, this_reference, converted_arguments,
                         std::move(label_blocks));
    } else if (arguments.labels.empty() &&
               return_type != TypeOracle::GetNeverType()) {
      std::optional<Block*> catch_block = GetCatchBlock();
      assembler().Emit(CallCsaMacroInstruction{
          macro, std::move(constexpr_arguments), catch_block});
      GenerateCatchBlock(catch_block);
      size_t return_slot_count = LoweredSlotCount(return_type);
      return VisitResult(return_type, assembler().TopRange(return_slot_count));
    } else {
      std::optional<Block*> return_continuation;
      if (return_type != TypeOracle::GetNeverType()) {
        return_continuation = assembler().NewBlock();
      }
      std::vector<Block*> label_blocks;
      for (size_t i = 0; i < label_count; ++i) {
        label_blocks.push_back(assembler().NewBlock());
      }
      std::optional<Block*> catch_block = GetCatchBlock();
      assembler().Emit(CallCsaMacroAndBranchInstruction{
          macro, constexpr_arguments, return_continuation, label_blocks,
          catch_block});
      GenerateCatchBlock(catch_block);
      for (size_t i = 0; i < label_count; ++i) {
        Binding<LocalLabel>* label = arguments.labels[i];
        size_t callee_label_parameters =
            callable->signature().labels[i].types.size();
        if (label->parameter_types.size() != callee_label_parameters) {
          std::stringstream s;
          s << "label " << label->name()
            << " doesn't have the right number of parameters (found "
            << std::to_string(label->parameter_types.size()) << " expected "
            << std::to_string(callee_label_parameters) << ")";
          ReportError(s.str());
        }
        assembler().Bind(label_blocks[i]);
        assembler().Goto(
            label->block,
            LowerParameterTypes(callable->signature().labels[i].types).size());
        size_t j = 0;
        for (auto t : callable->signature().labels[i].types) {
          const Type* parameter_type = label->parameter_types[j];
          if (!t->IsSubtypeOf(parameter_type)) {
            ReportError("mismatch of label parameters (label expects ",
                        *parameter_type, " but macro produces ", *t,
                        " for parameter ", i + 1, ")");
          }
          j++;
        }
      }
      if (return_continuation) {
        assembler().Bind(*return_continuation);
        size_t return_slot_count = LoweredSlotCount(return_type);
        return VisitResult(return_type,
                           assembler().TopRange(return_slot_count));
      } else {
        return VisitResult::NeverResult();
      }
    }
  } else if (auto* runtime_function = RuntimeFunction::DynamicCast(callable)) {
    std::optional<Block*> catch_block = GetCatchBlock();
    assembler().Emit(CallRuntimeInstruction{
        is_tailcall, runtime_function, argument_range.Size(), catch_block});
    GenerateCatchBlock(catch_block);
    if (is_tailcall || return_type == TypeOracle::GetNeverType()) {
      return VisitResult::NeverResult();
    } else {
      size_t slot_count = LoweredSlotCount(return_type);
      DCHECK_LE(slot_count, 1);
      // TODO(turbofan): Actually, runtime functions have to return a value, so
      // we should assert slot_count == 1 here.
      return VisitResult(return_type, assembler().TopRange(slot_count));
    }
  } else if (auto* intrinsic = Intrinsic::DynamicCast(callable)) {
    if (intrinsic->ExternalName() == "%SizeOf") {
      if (specialization_types.size() != 1) {
        ReportError("%SizeOf must take a single type parameter");
      }
      const Type* type = specialization_types[0];
      std::string size_string;
      if (std::optional<std::tuple<size_t, std::string>> size = SizeOf(type)) {
        size_string = std::get<1>(*size);
      } else {
        Error("size of ", *type, " is not known.");
      }
      return VisitResult(return_type, size_string);
    } else if (intrinsic->ExternalName() == "%ClassHasMapConstant") {
      const Type* type = specialization_types[0];
      const ClassType* class_type = ClassType::DynamicCast(type);
      if (!class_type) {
        ReportError("%ClassHasMapConstant must take a class type parameter");
      }
      // If the class isn't actually used as the parameter to a TNode,
      // then we can't rely on the class existing in C++ or being of the same
      // type (e.g. it could be a template), so don't use the template CSA
      // machinery for accessing the class' map.
      if (class_type->name() != class_type->GetGeneratedTNodeTypeName()) {
        return VisitResult(return_type, std::string("false"));
      } else {
        return VisitResult(
            return_type,
            std::string("CodeStubAssembler(state_).ClassHasMapConstant<") +
                class_type->name() + ">()");
      }
    } else if (intrinsic->ExternalName() == "%MinInstanceType") {
      if (specialization_types.size() != 1) {
        ReportError("%MinInstanceType must take a single type parameter");
      }
      const Type* type = specialization_types[0];
      const ClassType* class_type = ClassType::DynamicCast(type);
      if (!class_type) {
        ReportError("%MinInstanceType must take a class type parameter");
      }
      std::pair<std::string, std::string> instance_types =
          GetClassInstanceTypeRange(class_type);
      return VisitResult(return_type, instance_types.first);
    } else if (intrinsic->ExternalName() == "%MaxInstanceType") {
      if (specialization_types.size() != 1) {
        ReportError("%MaxInstanceType must take a single type parameter");
      }
      const Type* type = specialization_types[0];
      const ClassType* class_type = ClassType::DynamicCast(type);
      if (!class_type) {
        ReportError("%MaxInstanceType must take a class type parameter");
      }
      std::pair<std::string, std::string> instance_types =
          GetClassInstanceTypeRange(class_type);
      return VisitResult(return_type, instance_types.second);
    } else if (intrinsic->ExternalName() == "%RawConstexprCast") {
      if (intrinsic->signature().parameter_types.types.size() != 1 ||
          constexpr_arguments.size() != 1) {
        ReportError(
            "%RawConstexprCast must take a single parameter with constexpr "
            "type");
      }
      if (!return_type->IsConstexpr()) {
        std::stringstream s;
        s << *return_type
          << " return type for %RawConstexprCast is not constexpr";
        ReportError(s.str());
      }
      std::stringstream result;
      result << "static_cast<" << return_type->GetGeneratedTypeName() << ">(";
      result << constexpr_arguments[0];
      result << ")";
      return VisitResult(return_type, result.str());
    } else if (intrinsic->ExternalName() == "%IndexedFieldLength") {
      const Type* type = specialization_types[0];
      const ClassType* class_type = ClassType::DynamicCast(type);
      if (!class_type) {
        ReportError("%IndexedFieldLength must take a class type parameter");
      }
      const Field& field =
          class_type->LookupField(StringLiteralUnquote(constexpr_arguments[0]));
      return GenerateArrayLength(VisitResult(type, argument_range), field);
    } else if (intrinsic->ExternalName() == "%MakeLazy") {
      if (specialization_types[0]->IsStructType()) {
        ReportError("%MakeLazy can't use macros that return structs");
      }
      std::string getter_name = StringLiteralUnquote(constexpr_arguments[0]);
      // Normally the parser would split namespace names for us, but we
      // sidestepped it by putting the macro name in a string literal.
      QualifiedName qualified_getter_name = QualifiedName::Parse(getter_name);
      // converted_arguments contains all of the arguments to %MakeLazy. We're
      // looking for a function that takes all but the first.
      Arguments arguments_to_getter;
      arguments_to_getter.parameters.insert(
          arguments_to_getter.parameters.begin(),
          converted_arguments.begin() + 1, converted_arguments.end());
      Callable* callable_macro = LookupCallable(
          qualified_getter_name, Declarations::Lookup(qualified_getter_name),
          arguments_to_getter, {});
      Macro* getter = Macro::DynamicCast(callable_macro);
      if (!getter || getter->IsMethod()) {
        ReportError(
            "%MakeLazy expects a macro, not builtin or other type of callable");
      }
      if (!getter->signature().labels.empty()) {
        ReportError("%MakeLazy requires a macro with no labels");
      }
      if (!getter->signature().return_type->IsSubtypeOf(
              specialization_types[0])) {
        ReportError("%MakeLazy expected return type ", *specialization_types[0],
                    " but found ", *getter->signature().return_type);
      }
      if (getter->signature().implicit_count > 0) {
        ReportError("Implicit parameters are not yet supported in %MakeLazy");
      }
      getter->SetUsed(); // Prevent warnings about unused macros.
      // Now that we've looked up the getter macro, we have to convert the
      // arguments again, so that, for example, constexpr arguments can be
      // coerced to non-constexpr types and put on the stack.
      std::vector<VisitResult> converted_arguments_for_getter;
      StackRange argument_range_for_getter = assembler().TopRange(0);
      std::vector<std::string> constexpr_arguments_for_getter;
      size_t arg_count = 0;
      for (const auto& arg : arguments_to_getter.parameters) {
        DCHECK_LT(arg_count, getter->signature().types().size());
        const Type* to_type = getter->signature().types()[arg_count++];
        AddCallParameter(getter, arg, to_type, &converted_arguments_for_getter,
                         &argument_range_for_getter,
                         &constexpr_arguments_for_getter,
                         /*inline_macro=*/false);
      }
      // Now that the arguments are prepared, emit the instruction that consumes
      // them.
      assembler().Emit(MakeLazyNodeInstruction{
          getter, return_type, std::move(constexpr_arguments_for_getter)});
      return VisitResult(return_type, assembler().TopRange(1));
    } else if (intrinsic->ExternalName() == "%FieldSlice") {
      const Type* type = specialization_types[0];
      const ClassType* class_type = ClassType::DynamicCast(type);
      if (!class_type) {
        ReportError("The first type parameter to %FieldSlice must be a class");
      }
      const Field& field =
          class_type->LookupField(StringLiteralUnquote(constexpr_arguments[0]));
      const Type* expected_slice_type =
          field.const_qualified
              ? TypeOracle::GetConstSliceType(field.name_and_type.type)
              : TypeOracle::GetMutableSliceType(field.name_and_type.type);
      const Type* declared_slice_type = specialization_types[1];
      if (expected_slice_type != declared_slice_type) {
        Error(
            "The second type parameter to %FieldSlice must be the precise "
            "slice type for the named field");
      }
      LocationReference ref = GenerateFieldReference(
          VisitResult(type, argument_range), field, class_type,
          /*treat_optional_as_indexed=*/true);
      if (!ref.IsHeapSlice()) {
        ReportError("%FieldSlice expected an indexed or optional field");
      }
      return ref.heap_slice();
    } else {
      assembler().Emit(CallIntrinsicInstruction{intrinsic, specialization_types,
                                                constexpr_arguments});
      size_t return_slot_count =
          LoweredSlotCount(intrinsic->signature().return_type);
      return VisitResult(return_type, assembler().TopRange(return_slot_count));
    }
  } else {
    UNREACHABLE();
  }
}
References v8::internal::torque::Method::aggregate_type(), CHECK, CHECK_NOT_NULL, v8::internal::torque::Field::const_qualified, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_LT, v8::internal::torque::Error(), file(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GetClassInstanceTypeRange(), v8::internal::torque::Type::GetGeneratedTNodeTypeName(), v8::internal::torque::Type::GetGeneratedTypeName(), v8::internal::torque::LocationReference::heap_slice(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::Type::IsConstexpr(), v8::internal::torque::Callable::IsExternal(), v8::internal::torque::LocationReference::IsHeapSlice(), v8::internal::torque::Declarable::IsMacro(), v8::internal::torque::Declarable::IsMethod(), v8::internal::torque::Type::IsNever(), v8::internal::compiler::turboshaft::Type::IsSubtypeOf(), v8::internal::torque::Type::IsSubtypeOf(), v8::internal::torque::Callable::IsTransitioning(), v8::internal::wasm::kUnreachable, v8::internal::torque::Arguments::labels, v8::internal::torque::AggregateType::LookupField(), v8::internal::torque::LoweredSlotCount(), v8::internal::torque::LowerParameterTypes(), v8::internal::torque::Binding< T >::name(), v8::internal::torque::AggregateType::name(), v8::internal::torque::Field::name_and_type, v8::internal::torque::Arguments::parameters, v8::internal::anonymous_namespace{gc-extension.cc}::Parse(), v8::internal::torque::Declarable::Position(), v8::internal::torque::PositionAsString(), v8::internal::torque::Callable::ReadableName(), v8::internal::torque::ReportError(), v8::base::internal::result, v8::internal::torque::Callable::ShouldBeInlined(), v8::internal::torque::Callable::signature(), v8::internal::torque::StackRange::Size(), size(), v8::internal::torque::SizeOf(), v8::internal::string, v8::internal::torque::StringLiteralUnquote(), v8::internal::torque::NameAndType::type, v8::internal::torque::VisitResult::type(), v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by GenerateArrayLength(), GenerateFetchFromLocation(), GenerateFieldAccess(), GenerateLayoutForInitialization(), GenerateReferenceToItemInHeapSlice(), InitializeClass(), and Visit().
GenerateCall() [2/3]
VisitResult v8::internal::torque::ImplementationVisitor::GenerateCall (const QualifiedName & callable_name, Arguments parameters, const TypeVector & specialization_types = {}, bool tail_call = false) [private]
Definition at line 3252 of file implementation-visitor.cc.
                                                              {
  Callable* callable =
      LookupCallable(callable_name, Declarations::Lookup(callable_name),
                     arguments, specialization_types);
  return GenerateCall(callable, std::nullopt, arguments, specialization_types,
                      is_tailcall);
}
GenerateCall() [3/3]
VisitResult v8::internal::torque::ImplementationVisitor::GenerateCall (std::string callable_name, Arguments parameters, const TypeVector & specialization_types = {}, bool tail_call = false) [inline], [private]
Definition at line 747 of file implementation-visitor.h.
                                                                    {},
                           bool tail_call = false) {
    return GenerateCall(QualifiedName(std::move(callable_name)),
                        std::move(parameters), specialization_types, tail_call);
  }
GenerateCatchBlock()
void v8::internal::torque::ImplementationVisitor::GenerateCatchBlock (std::optional< Block * > catch_block) [private]
Definition at line 3516 of file implementation-visitor.cc.
                                     {
  if (catch_block) {
    std::optional<Binding<LocalLabel>*> catch_handler =
        TryLookupLabel(kCatchLabelName);
    // Reset the local scopes to prevent the macro calls below from using the
    // current catch handler.
    BindingsManagersScope bindings_managers_scope;
    if (assembler().CurrentBlockIsComplete()) {
      assembler().Bind(*catch_block);
      GenerateCall(QualifiedName({TORQUE_INTERNAL_NAMESPACE_STRING},
                                 "GetAndResetPendingMessage"),
                   Arguments{{}, {}}, {}, false);
      assembler().Goto((*catch_handler)->block, 2);
    } else {
      CfgAssemblerScopedTemporaryBlock temp(&assembler(), *catch_block);
      GenerateCall(QualifiedName({TORQUE_INTERNAL_NAMESPACE_STRING},
                                 "GetAndResetPendingMessage"),
                   Arguments{{}, {}}, {}, false);
      assembler().Goto((*catch_handler)->block, 2);
    }
  }
}
References v8::internal::torque::kCatchLabelName, and v8::internal::torque::TORQUE_INTERNAL_NAMESPACE_STRING.
GenerateClassDebugReaders()
void v8::internal::torque::ImplementationVisitor::GenerateClassDebugReaders (const std::string & output_directory)
Definition at line 523 of file class-debug-reader-generator.cc.
                                       {
  const std::string file_name = "class-debug-readers";
  std::stringstream h_contents;
  std::stringstream cc_contents;
  h_contents << "// Provides the ability to read object properties in\n";
  h_contents << "// postmortem or remote scenarios, where the debuggee's\n";
  h_contents << "// memory is not part of the current process's address\n";
  h_contents << "// space and must be read using a callback function.\n\n";
  {
    IncludeGuardScope include_guard(h_contents, file_name + ".h");
    h_contents << "#include <cstdint>\n";
    h_contents << "#include <vector>\n\n";
    for (const std::string& include_path : GlobalContext::CppIncludes()) {
      h_contents << "#include " << StringLiteralQuote(include_path) << "\n";
    }
    h_contents
        << "\n#include \"tools/debug_helper/debug-helper-internal.h\"\n\n";
    const char* kWingdiWorkaround =
        "// Unset a wingdi.h macro that causes conflicts.\n"
        "#ifdef GetBValue\n"
        "#undef GetBValue\n"
        "#endif\n\n";
    h_contents << kWingdiWorkaround;
    cc_contents << "#include \"torque-generated/" << file_name << ".h\"\n\n";
    cc_contents << "#include \"src/objects/all-objects-inl.h\"\n";
    cc_contents << "#include \"torque-generated/debug-macros.h\"\n\n";
    cc_contents << kWingdiWorkaround;
    cc_contents << "namespace i = v8::internal;\n\n";
    NamespaceScope h_namespaces(h_contents,
                                {"v8", "internal", "debug_helper_internal"});
    NamespaceScope cc_namespaces(cc_contents,
                                 {"v8", "internal", "debug_helper_internal"});
    std::stringstream visitor;
    visitor << "\nclass TqObjectVisitor {\n";
    visitor << " public:\n";
    visitor << " virtual void VisitObject(const TqObject* object) {}\n";
    std::unordered_set<const ClassType*> done;
    for (const ClassType* type : TypeOracle::GetClasses()) {
      GenerateClassDebugReader(*type, h_contents, cc_contents, visitor, &done);
    }
    visitor << "};\n";
    h_contents << visitor.str();
  }
  WriteFile(output_directory + "/" + file_name + ".h", h_contents.str());
  WriteFile(output_directory + "/" + file_name + ".cc", cc_contents.str());
}
References v8::internal::torque::GlobalContext::CppIncludes(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::GenerateClassDebugReader(), v8::internal::torque::TypeOracle::GetClasses(), v8::internal::string, v8::internal::torque::StringLiteralQuote(), v8::internal::tracing::type, and WriteFile().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
GenerateClassDefinitions()
void v8::internal::torque::ImplementationVisitor::GenerateClassDefinitions (const std::string & output_directory)
Definition at line 4837 of file implementation-visitor.cc.
                                       {
  std::stringstream factory_header;
  std::stringstream factory_impl;
  std::string factory_basename = "factory";
  std::stringstream forward_declarations;
  std::string forward_declarations_filename = "class-forward-declarations.h";
  {
    factory_impl << "#include \"src/heap/factory-base.h\"\n";
    factory_impl << "#include \"src/heap/factory-base-inl.h\"\n";
    factory_impl << "#include \"src/heap/heap.h\"\n";
    factory_impl << "#include \"src/heap/heap-inl.h\"\n";
    factory_impl << "#include \"src/execution/isolate.h\"\n";
    factory_impl << "#include "
                    "\"src/objects/all-objects-inl.h\"\n\n";
    NamespaceScope factory_impl_namespaces(factory_impl, {"v8", "internal"});
    factory_impl << "\n";
    IncludeGuardScope include_guard(forward_declarations,
                                    forward_declarations_filename);
    NamespaceScope forward_declarations_namespaces(forward_declarations,
                                                   {"v8", "internal"});
    std::set<const StructType*, TypeLess> structs_used_in_classes;
    // Emit forward declarations.
    for (const ClassType* type : TypeOracle::GetClasses()) {
      CurrentSourcePosition::Scope position_activator(type->GetPosition());
      auto& streams = GlobalContext::GeneratedPerFile(type->AttributedToFile());
      std::ostream& header = streams.class_definition_headerfile;
      std::string name = type->ShouldGenerateCppClassDefinitions()
                             ? type->name()
                             : type->GetGeneratedTNodeTypeName();
      if (type->ShouldGenerateCppClassDefinitions()) {
        header << "class " << name << ";\n";
      }
      forward_declarations << "class " << name << ";\n";
    }
    for (const ClassType* type : TypeOracle::GetClasses()) {
      CurrentSourcePosition::Scope position_activator(type->GetPosition());
      auto& streams = GlobalContext::GeneratedPerFile(type->AttributedToFile());
      std::ostream& header = streams.class_definition_headerfile;
      std::ostream& inline_header = streams.class_definition_inline_headerfile;
      std::ostream& implementation = streams.class_definition_ccfile;
      if (type->ShouldGenerateCppClassDefinitions()) {
        CppClassGenerator g(type, header, inline_header, implementation);
        g.GenerateClass();
      } else if (type->ShouldGenerateCppObjectDefinitionAsserts()) {
        CppClassGenerator g(type, header, inline_header, implementation);
        g.GenerateCppObjectDefinitionAsserts();
      } else if (type->ShouldGenerateCppObjectLayoutDefinitionAsserts()) {
        CppClassGenerator g(type, header, inline_header, implementation);
        g.GenerateCppObjectLayoutDefinitionAsserts();
      }
      for (const Field& f : type->fields()) {
        const Type* field_type = f.name_and_type.type;
        if (auto field_as_struct = field_type->StructSupertype()) {
          structs_used_in_classes.insert(*field_as_struct);
        }
      }
      if (type->ShouldGenerateFactoryFunction()) {
        std::string return_type =
            type->HandlifiedCppTypeName(Type::HandleKind::kIndirect);
        std::string function_name = "New" + type->name();
        std::stringstream parameters;
        for (const Field& f : type->ComputeAllFields()) {
          if (f.name_and_type.name == "map") continue;
          if (f.name_and_type.name == "self_indirect_pointer") continue;
          if (!f.index) {
            std::string type_string =
                f.name_and_type.type->HandlifiedCppTypeName(
                    Type::HandleKind::kDirect);
            parameters << type_string << " " << f.name_and_type.name << ", ";
          }
        }
        parameters << "AllocationType allocation_type";
        factory_header << return_type << " " << function_name << "("
                       << parameters.str() << ");\n";
        factory_impl << "template <typename Impl>\n";
        factory_impl << return_type
                     << " TorqueGeneratedFactory<Impl>::" << function_name
                     << "(" << parameters.str() << ") {\n";
        factory_impl << " int size = ";
        const ClassType* super = type->GetSuperClass();
        std::string gen_name = "TorqueGenerated" + type->name();
        std::string gen_name_T =
            gen_name + "<" + type->name() + ", " + super->name() + ">";
        factory_impl << gen_name_T << "::SizeFor(";
        bool first = true;
        auto index_fields = GetOrderedUniqueIndexFields(*type);
        CHECK(index_fields.has_value());
        for (const auto& index_field : *index_fields) {
          if (!first) {
            factory_impl << ", ";
          }
          factory_impl << index_field.name_and_type.name;
          first = false;
        }
        factory_impl << ");\n";
        factory_impl << " Tagged<Map> map = factory()->read_only_roots()."
                     << SnakeifyString(type->name()) << "_map();\n";
        factory_impl << " Tagged<HeapObject> raw_object =\n";
        factory_impl << " factory()->AllocateRawWithImmortalMap(size, "
                        "allocation_type, map);\n";
        factory_impl << " " << type->TagglifiedCppTypeName()
                     << " result = Cast<"
                     << type->GetConstexprGeneratedTypeName()
                     << ">(raw_object);\n";
        factory_impl << " DisallowGarbageCollection no_gc;\n";
        factory_impl << " WriteBarrierMode write_barrier_mode =\n"
                     << " allocation_type == AllocationType::kYoung\n"
                     << " ? SKIP_WRITE_BARRIER : UPDATE_WRITE_BARRIER;\n"
                     << " USE(write_barrier_mode);\n";
        for (const Field& f : type->ComputeAllFields()) {
          if (f.name_and_type.name == "map") continue;
          if (f.name_and_type.name == "self_indirect_pointer") {
            factory_impl << " "
                            "result->init_self_indirect_pointer(factory()->"
                            "isolate());\n";
          } else if (!f.index) {
            factory_impl << " result->TorqueGeneratedClass::set_"
                         << SnakeifyString(f.name_and_type.name) << "(";
            if (f.name_and_type.type->IsSubtypeOf(
                    TypeOracle::GetTaggedType()) &&
                !f.name_and_type.type->IsSubtypeOf(TypeOracle::GetSmiType())) {
              factory_impl << "*" << f.name_and_type.name
                           << ", write_barrier_mode";
            } else {
              factory_impl << f.name_and_type.name;
            }
            factory_impl << ");\n";
          }
        }
        factory_impl << " return handle(result, factory()->isolate());\n";
        factory_impl << "}\n\n";
        factory_impl << "template EXPORT_TEMPLATE_DEFINE(V8_EXPORT_PRIVATE) "
                     << return_type
                     << " TorqueGeneratedFactory<Factory>::" << function_name
                     << "(" << parameters.str() << ");\n";
        factory_impl << "template EXPORT_TEMPLATE_DEFINE(V8_EXPORT_PRIVATE) "
                     << return_type << " TorqueGeneratedFactory<LocalFactory>::"
                     << function_name << "(" << parameters.str() << ");\n";
        factory_impl << "\n\n";
      }
    }
    for (const StructType* type : structs_used_in_classes) {
      CurrentSourcePosition::Scope position_activator(type->GetPosition());
      std::ostream& header =
          GlobalContext::GeneratedPerFile(type->GetPosition().source)
              .class_definition_headerfile;
      if (type != TypeOracle::GetFloat64OrUndefinedOrHoleType()) {
        GenerateStructLayoutDescription(header, type);
      }
    }
  }
  WriteFile(output_directory + "/" + factory_basename + ".inc",
            factory_header.str());
  WriteFile(output_directory + "/" + factory_basename + ".cc",
            factory_impl.str());
  WriteFile(output_directory + "/" + forward_declarations_filename,
            forward_declarations.str());
}
References CHECK, v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GenerateStructLayoutDescription(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GetOrderedUniqueIndexFields(), v8::internal::name, v8::internal::torque::AggregateType::name(), v8::internal::torque::SnakeifyString(), v8::internal::string, v8::internal::torque::Type::StructSupertype(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
GenerateClassVerifiers()
void v8::internal::torque::ImplementationVisitor::GenerateClassVerifiers (const std::string & output_directory)
Definition at line 5370 of file implementation-visitor.cc.
                                       {
  std::string file_name = "class-verifiers";
  std::stringstream h_contents;
  std::stringstream cc_contents;
  {
    IncludeGuardScope include_guard(h_contents, file_name + ".h");
    IfDefScope verify_heap_h(h_contents, "VERIFY_HEAP");
    IfDefScope verify_heap_cc(cc_contents, "VERIFY_HEAP");
    h_contents << "#include \"src/base/macros.h\"\n\n";
    cc_contents << "#include \"torque-generated/" << file_name << ".h\"\n\n";
    cc_contents << "#include \"src/objects/all-objects-inl.h\"\n";
    IncludeObjectMacrosScope object_macros(cc_contents);
    NamespaceScope h_namespaces(h_contents, {"v8", "internal"});
    NamespaceScope cc_namespaces(cc_contents, {"v8", "internal"});
    cc_contents
        << "#include \"torque-generated/test/torque/test-torque-tq-inl.inc\"\n";
    // Generate forward declarations to avoid including any headers.
    h_contents << "class Isolate;\n";
    h_contents << "template<typename T>\nclass Tagged;\n";
    for (const ClassType* type : TypeOracle::GetClasses()) {
      if (!type->ShouldGenerateVerify()) continue;
      h_contents << "class " << type->name() << ";\n";
    }
    const char* verifier_class = "TorqueGeneratedClassVerifiers";
    h_contents << "class V8_EXPORT_PRIVATE " << verifier_class << "{\n";
    h_contents << " public:\n";
    for (const ClassType* type : TypeOracle::GetClasses()) {
      std::string name = type->name();
      std::string cpp_name = type->TagglifiedCppTypeName();
      if (!type->ShouldGenerateVerify()) continue;
      std::string method_name = name + "Verify";
      h_contents << " static void " << method_name << "(" << cpp_name
                 << " o, Isolate* isolate);\n";
      cc_contents << "void " << verifier_class << "::" << method_name << "("
                  << cpp_name << " o, Isolate* isolate) {\n";
      // First, do any verification for the super class. Not all classes have
      // verifiers, so skip to the nearest super class that has one.
      const ClassType* super_type = type->GetSuperClass();
      while (super_type && !super_type->ShouldGenerateVerify()) {
        super_type = super_type->GetSuperClass();
      }
      if (super_type) {
        std::string super_name = super_type->name();
        cc_contents << " o->" << super_name << "Verify(isolate);\n";
      }
      // Second, verify that this object is what it claims to be.
      cc_contents << " CHECK(Is" << name << "(o, isolate));\n";
      // Third, verify its properties.
      for (const auto& f : type->fields()) {
        GenerateClassFieldVerifier(name, *type, f, h_contents, cc_contents);
      }
      cc_contents << "}\n";
    }
    h_contents << "};\n";
  }
  WriteFile(output_directory + "/" + file_name + ".h", h_contents.str());
  WriteFile(output_directory + "/" + file_name + ".cc", cc_contents.str());
}
References v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GenerateClassFieldVerifier(), v8::internal::torque::ClassType::GetSuperClass(), v8::internal::name, v8::internal::torque::AggregateType::name(), v8::internal::torque::ClassType::ShouldGenerateVerify(), v8::internal::string, and v8::internal::tracing::type.
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
GenerateCopy()
VisitResult v8::internal::torque::ImplementationVisitor::GenerateCopy (const VisitResult & to_copy) [private]
Definition at line 2213 of file implementation-visitor.cc.
                                                                          {
  if (to_copy.IsOnStack()) {
    return VisitResult(to_copy.type(),
                       assembler().Peek(to_copy.stack_range(), to_copy.type()));
  }
  return to_copy;
}
References assembler(), v8::internal::torque::VisitResult::IsOnStack(), v8::internal::torque::VisitResult::stack_range(), and v8::internal::torque::VisitResult::type().
Referenced by GenerateFetchFromLocation(), GenerateFieldAccess(), GenerateFieldReferenceForInit(), and GenerateSetBitField().
GenerateCSATypes()
void v8::internal::torque::ImplementationVisitor::GenerateCSATypes (const std::string & output_directory)
Definition at line 5570 of file implementation-visitor.cc.
                                       {
  std::string file_name = "csa-types";
  std::stringstream h_contents;
  {
    IncludeGuardScope include_guard(h_contents, file_name + ".h");
    h_contents << "#include \"src/compiler/code-assembler.h\"\n\n";
    NamespaceScope h_namespaces(h_contents, {"v8", "internal"});
    // Generates headers for all structs in a topologically-sorted order, since
    // TypeOracle keeps them in the order of their resolution
    for (const auto& type : TypeOracle::GetAggregateTypes()) {
      const StructType* struct_type = StructType::DynamicCast(type.get());
      if (!struct_type) continue;
      h_contents << "struct " << struct_type->GetGeneratedTypeNameImpl()
                 << " {\n";
      for (auto& field : struct_type->fields()) {
        h_contents << " " << field.name_and_type.type->GetGeneratedTypeName();
        h_contents << " " << field.name_and_type.name << ";\n";
      }
      h_contents << "\n std::tuple<";
      bool first = true;
      for (const Type* lowered_type : LowerType(struct_type)) {
        if (!first) {
          h_contents << ", ";
        }
        first = false;
        h_contents << lowered_type->GetGeneratedTypeName();
      }
      std::vector<std::string> all_fields;
      for (auto& field : struct_type->fields()) {
        CollectAllFields("", field, all_fields);
      }
      h_contents << "> Flatten() const {\n"
                    " return std::make_tuple(";
      PrintCommaSeparatedList(h_contents, all_fields);
      h_contents << ");\n";
      h_contents << " }\n";
      h_contents << "};\n";
    }
  }
  WriteFile(output_directory + "/" + file_name + ".h", h_contents.str());
}
References v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CollectAllFields(), v8::internal::torque::AggregateType::fields(), v8::internal::torque::StructType::GetGeneratedTypeNameImpl(), v8::internal::torque::LowerType(), v8::internal::torque::PrintCommaSeparatedList(), v8::internal::string, and v8::internal::tracing::type.
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
GenerateEnumVerifiers()
void v8::internal::torque::ImplementationVisitor::GenerateEnumVerifiers (const std::string & output_directory)
Definition at line 5447 of file implementation-visitor.cc.
                                       {
  std::string file_name = "enum-verifiers";
  std::stringstream cc_contents;
  {
    cc_contents << "#include \"src/compiler/code-assembler.h\"\n";
    for (const std::string& include_path : GlobalContext::CppIncludes()) {
      cc_contents << "#include " << StringLiteralQuote(include_path) << "\n";
    }
    cc_contents << "\n";
    NamespaceScope cc_namespaces(cc_contents, {"v8", "internal", ""});
    cc_contents << "class EnumVerifier {\n";
    for (const auto& desc : GlobalContext::Get().ast()->EnumDescriptions()) {
      std::stringstream alias_checks;
      cc_contents << " // " << desc.name << " (" << desc.pos << ")\n";
      cc_contents << " void VerifyEnum_" << desc.name << "("
                  << desc.constexpr_generates
                  << " x) {\n"
                     " switch(x) {\n";
      for (const auto& entry : desc.entries) {
        if (entry.alias_entry.empty()) {
          cc_contents << " case " << entry.name << ": break;\n";
        } else {
          // We don't add a case for this, because it aliases another entry, so
          // we would have two cases for the same value.
          alias_checks << " static_assert(" << entry.name
                       << " == " << entry.alias_entry << ");\n";
        }
      }
      if (desc.is_open) cc_contents << " default: break;\n";
      cc_contents << " }\n";
      cc_contents << alias_checks.str();
      cc_contents << " }\n\n";
    }
    cc_contents << "};\n";
  }
  WriteFile(output_directory + "/" + file_name + ".cc", cc_contents.str());
}
References v8::internal::compiler::turboshaft::Get(), v8::internal::string, and v8::internal::torque::StringLiteralQuote().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
GenerateExportedMacrosAssembler()
void v8::internal::torque::ImplementationVisitor::GenerateExportedMacrosAssembler (const std::string & output_directory)
Definition at line 5489 of file implementation-visitor.cc.
                                       {
  std::string file_name = "exported-macros-assembler";
  std::stringstream h_contents;
  std::stringstream cc_contents;
  {
    IncludeGuardScope include_guard(h_contents, file_name + ".h");
    h_contents << "#include \"src/compiler/code-assembler.h\"\n";
    h_contents << "#include \"src/execution/frames.h\"\n";
    h_contents << "#include \"torque-generated/csa-types.h\"\n";
    for (const std::string& include_path : GlobalContext::CppIncludes()) {
      cc_contents << "#include " << StringLiteralQuote(include_path) << "\n";
    }
    cc_contents << "#include \"torque-generated/" << file_name << ".h\"\n";
    for (SourceId file : SourceFileMap::AllSources()) {
      cc_contents << "#include \"torque-generated/" +
                         SourceFileMap::PathFromV8RootWithoutExtension(file) +
                         "-tq-csa.h\"\n";
    }
    NamespaceScope h_namespaces(h_contents, {"v8", "internal"});
    NamespaceScope cc_namespaces(cc_contents, {"v8", "internal"});
    h_contents << "class V8_EXPORT_PRIVATE "
                  "TorqueGeneratedExportedMacrosAssembler {\n"
               << " public:\n"
               << " explicit TorqueGeneratedExportedMacrosAssembler"
                  "(compiler::CodeAssemblerState* state) : state_(state) {\n"
               << " USE(state_);\n"
               << " }\n";
    for (auto& declarable : GlobalContext::AllDeclarables()) {
      TorqueMacro* macro = TorqueMacro::DynamicCast(declarable.get());
      if (!(macro && macro->IsExportedToCSA())) continue;
      CurrentSourcePosition::Scope position_activator(macro->Position());
      cpp::Class assembler("TorqueGeneratedExportedMacrosAssembler");
      std::vector<std::string> generated_parameter_names;
      cpp::Function f = GenerateFunction(
          &assembler, macro->ReadableName(), macro->signature(),
          macro->parameter_names(), false, &generated_parameter_names);
      f.PrintDeclaration(h_contents);
      f.PrintDefinition(cc_contents, [&](std::ostream& stream) {
        stream << "return " << macro->ExternalName() << "(state_";
        for (const auto& name : generated_parameter_names) {
          stream << ", " << name;
        }
        stream << ");";
      });
    }
    h_contents << " private:\n"
               << " compiler::CodeAssemblerState* state_;\n"
               << "};\n";
  }
  WriteFile(output_directory + "/" + file_name + ".h", h_contents.str());
  WriteFile(output_directory + "/" + file_name + ".cc", cc_contents.str());
}
References v8::internal::torque::Callable::ExternalName(), file(), v8::internal::torque::TorqueMacro::IsExportedToCSA(), v8::internal::name, v8::internal::torque::Callable::parameter_names(), v8::internal::torque::Declarable::Position(), v8::internal::torque::cpp::Function::PrintDeclaration(), v8::internal::torque::cpp::Function::PrintDefinition(), v8::internal::torque::Callable::ReadableName(), v8::internal::torque::Callable::signature(), v8::internal::string, and v8::internal::torque::StringLiteralQuote().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
GenerateExpressionBranch()
void v8::internal::torque::ImplementationVisitor::GenerateExpressionBranch (Expression * expression, Block * true_block, Block * false_block) [private]
Definition at line 3376 of file implementation-visitor.cc.
                                                                         {
  StackScope stack_scope(this);
  VisitResult expression_result = this->Visit(expression);
  expression_result = stack_scope.Yield(
      GenerateImplicitConvert(TypeOracle::GetBoolType(), expression_result));
  GenerateBranch(expression_result, true_block, false_block);
}
References v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Referenced by Visit().
GenerateFetchFromLocation()
VisitResult v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation (const LocationReference & reference)
Definition at line 2554 of file implementation-visitor.cc.
                                        {
  if (reference.IsTemporary()) {
    return GenerateCopy(reference.temporary());
  } else if (reference.IsVariableAccess()) {
    return GenerateCopy(reference.variable());
  } else if (reference.IsHeapReference()) {
    const Type* referenced_type = *reference.ReferencedType();
    if (referenced_type == TypeOracle::GetFloat64OrUndefinedOrHoleType()) {
      return GenerateCall(QualifiedName({TORQUE_INTERNAL_NAMESPACE_STRING},
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
                                        "LoadFloat64OrUndefinedOrHole"
#else
                                        "LoadFloat64OrHole"
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
                                        ),
                          Arguments{{reference.heap_reference()}, {}});
    } else if (auto struct_type = referenced_type->StructSupertype()) {
      StackRange result_range = assembler().TopRange(0);
      for (const Field& field : (*struct_type)->fields()) {
        StackScope scope(this);
        const std::string& fieldname = field.name_and_type.name;
        VisitResult field_value = scope.Yield(GenerateFetchFromLocation(
            GenerateFieldAccess(reference, fieldname)));
        result_range.Extend(field_value.stack_range());
      }
      return VisitResult(referenced_type, result_range);
    } else {
      GenerateCopy(reference.heap_reference());
      FieldSynchronization sync = reference.heap_reference_synchronization();
      assembler().Emit(LoadReferenceInstruction{referenced_type, sync});
      DCHECK_EQ(1, LoweredSlotCount(referenced_type));
      return VisitResult(referenced_type, assembler().TopRange(1));
    }
  } else if (reference.IsBitFieldAccess()) {
    // First fetch the bitfield struct, then get the bits out of it.
    VisitResult bit_field_struct =
        GenerateFetchFromLocation(reference.bit_field_struct_location());
    assembler().Emit(LoadBitFieldInstruction{bit_field_struct.type(),
                                             reference.bit_field()});
    return VisitResult(*reference.ReferencedType(), assembler().TopRange(1));
  } else {
    if (reference.IsHeapSlice()) {
      ReportError(
          "fetching a value directly from an indexed field isn't allowed");
    }
    DCHECK(reference.IsCallAccess());
    return GenerateCall(reference.eval_function(),
                        Arguments{reference.call_arguments(), {}});
  }
}
References assembler(), v8::internal::torque::LocationReference::bit_field(), v8::internal::torque::LocationReference::bit_field_struct_location(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::torque::CfgAssembler::Emit(), v8::internal::torque::LocationReference::eval_function(), v8::internal::torque::StackRange::Extend(), GenerateCall(), GenerateCopy(), GenerateFieldAccess(), v8::internal::torque::TypeOracle::GetFloat64OrUndefinedOrHoleType(), v8::internal::torque::LocationReference::heap_reference(), v8::internal::torque::LocationReference::heap_reference_synchronization(), v8::internal::torque::LocationReference::IsBitFieldAccess(), v8::internal::torque::LocationReference::IsCallAccess(), v8::internal::torque::LocationReference::IsHeapReference(), v8::internal::torque::LocationReference::IsHeapSlice(), v8::internal::torque::LocationReference::IsTemporary(), v8::internal::torque::LocationReference::IsVariableAccess(), v8::internal::torque::LoweredSlotCount(), v8::internal::torque::LocationReference::ReferencedType(), v8::internal::torque::ReportError(), v8::internal::torque::VisitResult::stack_range(), v8::internal::string, v8::internal::torque::Type::StructSupertype(), v8::internal::torque::LocationReference::temporary(), v8::internal::torque::CfgAssembler::TopRange(), v8::internal::torque::TORQUE_INTERNAL_NAMESPACE_STRING, v8::internal::torque::VisitResult::type(), v8::internal::torque::LocationReference::variable(), and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Referenced by GenerateFieldAccess(), and GetLocationReference().
GenerateFieldAccess()
LocationReference v8::internal::torque::ImplementationVisitor::GenerateFieldAccess (LocationReference reference, const std::string & fieldname, bool ignore_stuct_field_constness = false, std::optional< SourcePosition > pos = {})
Definition at line 2316 of file implementation-visitor.cc.
                                                                        {
  if (reference.IsVariableAccess() &&
      reference.variable().type()->StructSupertype()) {
    const StructType* type = *reference.variable().type()->StructSupertype();
    const Field& field = type->LookupField(fieldname);
    if (GlobalContext::collect_language_server_data() && pos.has_value()) {
      LanguageServerData::AddDefinition(*pos, field.pos);
    }
    if (GlobalContext::collect_kythe_data() && pos.has_value()) {
      KytheData::AddClassFieldUse(*pos, &field);
    }
    if (field.const_qualified) {
      VisitResult t_value = ProjectStructField(reference.variable(), fieldname);
      return LocationReference::Temporary(
          t_value, "for constant field '" + field.name_and_type.name + "'");
    } else {
      return LocationReference::VariableAccess(
          ProjectStructField(reference.variable(), fieldname));
    }
  }
  if (reference.IsTemporary() &&
      reference.temporary().type()->StructSupertype()) {
    if (GlobalContext::collect_language_server_data() && pos.has_value()) {
      const StructType* type = *reference.temporary().type()->StructSupertype();
      const Field& field = type->LookupField(fieldname);
      LanguageServerData::AddDefinition(*pos, field.pos);
    }
    return LocationReference::Temporary(
        ProjectStructField(reference.temporary(), fieldname),
        reference.temporary_description());
  }
  if (std::optional<const Type*> referenced_type = reference.ReferencedType()) {
    if ((*referenced_type)->IsBitFieldStructType()) {
      const BitFieldStructType* bitfield_struct =
          BitFieldStructType::cast(*referenced_type);
      const BitField& field = bitfield_struct->LookupField(fieldname);
      return LocationReference::BitFieldAccess(reference, field);
    }
    if (const auto type_wrapped_in_smi = Type::MatchUnaryGeneric(
            (*referenced_type), TypeOracle::GetSmiTaggedGeneric())) {
      const BitFieldStructType* bitfield_struct =
          BitFieldStructType::DynamicCast(*type_wrapped_in_smi);
      if (bitfield_struct == nullptr) {
        ReportError(
            "When a value of type SmiTagged<T> is used in a field access "
            "expression, T is expected to be a bitfield struct type. Instead, "
            "T "
            "is ",
            **type_wrapped_in_smi);
      }
      const BitField& field = bitfield_struct->LookupField(fieldname);
      return LocationReference::BitFieldAccess(reference, field);
    }
  }
  if (reference.IsHeapReference()) {
    VisitResult ref = reference.heap_reference();
    bool is_const;
    auto generic_type =
        TypeOracle::MatchReferenceGeneric(ref.type(), &is_const);
    if (!generic_type) {
      ReportError(
          "Left-hand side of field access expression is marked as a reference "
          "but is not of type Reference<...>. Found type: ",
          ref.type()->ToString());
    }
    if (auto struct_type = (*generic_type)->StructSupertype()) {
      const Field& field = (*struct_type)->LookupField(fieldname);
      // Update the Reference's type to refer to the field type within the
      // struct.
      ref.SetType(TypeOracle::GetReferenceType(
          field.name_and_type.type,
          is_const ||
              (field.const_qualified && !ignore_stuct_field_constness)));
      if (!field.offset.has_value()) {
        Error("accessing field with unknown offset").Throw();
      }
      if (*field.offset != 0) {
        // Copy the Reference struct up the stack and update the new copy's
        // |offset| value to point to the struct field.
        StackScope scope(this);
        ref = GenerateCopy(ref);
        VisitResult ref_offset = ProjectStructField(ref, "offset");
        VisitResult struct_offset{
            TypeOracle::GetIntPtrType()->ConstexprVersion(),
            std::to_string(*field.offset)};
        VisitResult updated_offset =
            GenerateCall("+", Arguments{{ref_offset, struct_offset}, {}});
        assembler().Poke(ref_offset.stack_range(), updated_offset.stack_range(),
                         ref_offset.type());
        ref = scope.Yield(ref);
      }
      return LocationReference::HeapReference(ref);
    }
  }
  VisitResult object_result = GenerateFetchFromLocation(reference);
  if (std::optional<const ClassType*> class_type =
          object_result.type()->ClassSupertype()) {
    // This is a hack to distinguish the situation where we want to use
    // overloaded field accessors from when we want to create a reference.
    bool has_explicit_overloads = TestLookupCallable(
        QualifiedName{"." + fieldname}, {object_result.type()});
    if ((*class_type)->HasField(fieldname) && !has_explicit_overloads) {
      const Field& field = (*class_type)->LookupField(fieldname);
      if (GlobalContext::collect_language_server_data() && pos.has_value()) {
        LanguageServerData::AddDefinition(*pos, field.pos);
      }
      if (GlobalContext::collect_kythe_data()) {
        KytheData::AddClassFieldUse(*pos, &field);
      }
      return GenerateFieldReference(object_result, field, *class_type);
    }
  }
  return LocationReference::FieldAccess(object_result, fieldname);
}
References v8::internal::torque::KytheData::AddClassFieldUse(), v8::internal::torque::LanguageServerData::AddDefinition(), assembler(), v8::internal::torque::LocationReference::BitFieldAccess(), v8::internal::torque::Type::ClassSupertype(), v8::internal::torque::GlobalContext::collect_kythe_data(), v8::internal::torque::GlobalContext::collect_language_server_data(), v8::internal::torque::Field::const_qualified, v8::internal::torque::Type::ConstexprVersion(), v8::internal::torque::Error(), v8::internal::torque::LocationReference::FieldAccess(), GenerateCall(), GenerateCopy(), GenerateFetchFromLocation(), GenerateFieldReference(), v8::internal::torque::TypeOracle::GetIntPtrType(), v8::internal::torque::TypeOracle::GetReferenceType(), v8::internal::torque::TypeOracle::GetSmiTaggedGeneric(), v8::internal::torque::LocationReference::heap_reference(), v8::internal::torque::LocationReference::HeapReference(), v8::internal::torque::LocationReference::IsHeapReference(), v8::internal::torque::LocationReference::IsTemporary(), v8::internal::torque::LocationReference::IsVariableAccess(), v8::internal::torque::BitFieldStructType::LookupField(), v8::internal::torque::TypeOracle::MatchReferenceGeneric(), v8::internal::torque::Type::MatchUnaryGeneric(), v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::internal::torque::Field::offset, v8::internal::torque::CfgAssembler::Poke(), v8::internal::torque::Field::pos, v8::internal::torque::ProjectStructField(), v8::internal::torque::LocationReference::ReferencedType(), v8::internal::torque::ReportError(), v8::internal::torque::VisitResult::SetType(), v8::internal::torque::VisitResult::stack_range(), v8::internal::torque::Type::StructSupertype(), v8::internal::torque::LocationReference::temporary(), v8::internal::torque::LocationReference::Temporary(), v8::internal::torque::LocationReference::temporary_description(), TestLookupCallable(), v8::internal::torque::MessageBuilder::Throw(), v8::internal::torque::Type::ToString(), v8::internal::torque::NameAndType::type, v8::internal::torque::VisitResult::type(), v8::internal::tracing::type, v8::internal::torque::LocationReference::variable(), v8::internal::torque::LocationReference::VariableAccess(), and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Referenced by GenerateFetchFromLocation(), and GetLocationReference().
GenerateFieldReference()
LocationReference v8::internal::torque::ImplementationVisitor::GenerateFieldReference (VisitResult object, const Field & field, const ClassType * class_type, bool treat_optional_as_indexed = false)
Definition at line 1480 of file implementation-visitor.cc.
                                    {
  if (field.index.has_value()) {
    LocationReference slice = LocationReference::HeapSlice(
        GenerateCall(class_type->GetSliceMacroName(field), {{object}, {}}));
    if (field.index->optional && !treat_optional_as_indexed) {
      // This field was declared using optional syntax, so any reference to it
      // is implicitly a reference to the first item.
      return GenerateReferenceToItemInHeapSlice(
          slice, {TypeOracle::GetConstInt31Type(), "0"});
    } else {
      return slice;
    }
  }
  DCHECK(field.offset.has_value());
  StackRange result_range = assembler().TopRange(0);
  result_range.Extend(GenerateCopy(object).stack_range());
  VisitResult offset =
      VisitResult(TypeOracle::GetConstInt31Type(), ToString(*field.offset));
  offset = GenerateImplicitConvert(TypeOracle::GetIntPtrType(), offset);
  result_range.Extend(offset.stack_range());
  const Type* type = TypeOracle::GetReferenceType(field.name_and_type.type,
                                                  field.const_qualified);
  return LocationReference::HeapReference(VisitResult(type, result_range),
                                          field.synchronization);
}
References v8::internal::torque::TypeOracle::GetConstInt31Type(), v8::internal::torque::ClassType::GetSliceMacroName(), v8::internal::torque::LocationReference::HeapSlice(), and v8::internal::torque::Field::index.
Referenced by GenerateArrayLength(), and GenerateFieldAccess().
GenerateFieldReferenceForInit()
LocationReference v8::internal::torque::ImplementationVisitor::GenerateFieldReferenceForInit (VisitResult object, const Field & field, const LayoutForInitialization & layout)
Definition at line 1510 of file implementation-visitor.cc.
                                           {
  StackRange result_range = assembler().TopRange(0);
  result_range.Extend(GenerateCopy(object).stack_range());
  VisitResult offset = GenerateImplicitConvert(
      TypeOracle::GetIntPtrType(), layout.offsets.at(field.name_and_type.name));
  result_range.Extend(offset.stack_range());
  if (field.index) {
    VisitResult length =
        GenerateCopy(layout.array_lengths.at(field.name_and_type.name));
    result_range.Extend(length.stack_range());
    const Type* slice_type =
        TypeOracle::GetMutableSliceType(field.name_and_type.type);
    return LocationReference::HeapSlice(VisitResult(slice_type, result_range));
  } else {
    // Const fields are writable during initialization.
    VisitResult heap_reference(
        TypeOracle::GetMutableReferenceType(field.name_and_type.type),
        result_range);
    return LocationReference::HeapReference(heap_reference);
  }
}
References v8::internal::torque::LayoutForInitialization::array_lengths, assembler(), v8::internal::torque::StackRange::Extend(), GenerateCopy(), GenerateImplicitConvert(), v8::internal::torque::TypeOracle::GetIntPtrType(), v8::internal::torque::TypeOracle::GetMutableReferenceType(), v8::internal::torque::TypeOracle::GetMutableSliceType(), v8::internal::torque::LocationReference::HeapReference(), v8::internal::torque::LocationReference::HeapSlice(), v8::internal::torque::Field::index, v8::internal::length, v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::internal::torque::LayoutForInitialization::offsets, v8::internal::torque::VisitResult::stack_range(), v8::internal::torque::CfgAssembler::TopRange(), and v8::internal::torque::NameAndType::type.
Referenced by InitializeClass().
GenerateFunction()
cpp::Function v8::internal::torque::ImplementationVisitor::GenerateFunction (cpp::Class * owner, const std::string & name, const Signature & signature, const NameVector & parameter_names, bool pass_code_assembler_state = true, std::vector< std::string > * generated_parameter_names = nullptr) [private]
Definition at line 1890 of file implementation-visitor.cc.
                                                     {
  cpp::Function f(owner, name);
  f.SetInline(output_type_ == OutputType::kCC);
  // Set return type.
  // TODO(torque-builder): Consider an overload of SetReturnType that handles
  // this.
  if (signature.return_type->IsVoidOrNever()) {
    f.SetReturnType("void");
  } else if (output_type_ == OutputType::kCCDebug) {
    f.SetReturnType(std::string("Value<") +
                    signature.return_type->GetDebugType() + ">");
  } else if (output_type_ == OutputType::kCC) {
    f.SetReturnType(signature.return_type->GetRuntimeType());
  } else {
    DCHECK_EQ(output_type_, OutputType::kCSA);
    f.SetReturnType(signature.return_type->IsConstexpr()
                        ? signature.return_type->TagglifiedCppTypeName()
                        : signature.return_type->GetGeneratedTypeName());
  }
  bool ignore_first_parameter = true;
  if (output_type_ == OutputType::kCCDebug) {
    f.AddParameter("d::MemoryAccessor", "accessor");
  } else if (output_type_ == OutputType::kCSA && pass_code_assembler_state) {
    f.AddParameter("compiler::CodeAssemblerState*", "state_");
  } else {
    ignore_first_parameter = false;
  }
  // TODO(torque-builder): Consider an overload for AddParameter that handles
  // this.
  DCHECK_GE(signature.types().size(), parameter_names.size());
  for (std::size_t i = 0; i < signature.types().size(); ++i) {
    const Type* parameter_type = signature.types()[i];
    std::string type;
    if (output_type_ == OutputType::kCC) {
      type = parameter_type->GetRuntimeType();
    } else if (output_type_ == OutputType::kCCDebug) {
      type = parameter_type->GetDebugType();
    } else {
      DCHECK_EQ(output_type_, OutputType::kCSA);
      if (parameter_type->IsConstexpr()) {
        type = parameter_type->TagglifiedCppTypeName();
      } else {
        type = parameter_type->GetGeneratedTypeName();
      }
    }
    f.AddParameter(std::move(type),
                   ExternalParameterName(i < parameter_names.size()
                                             ? parameter_names[i]->value
                                             : std::to_string(i)));
  }
  for (const LabelDeclaration& label_info : signature.labels) {
    if (output_type_ == OutputType::kCC ||
        output_type_ == OutputType::kCCDebug) {
      ReportError("Macros that generate runtime code can't have label exits");
    }
    f.AddParameter("compiler::CodeAssemblerLabel*",
                   ExternalLabelName(label_info.name->value));
    size_t i = 0;
    for (const Type* type : label_info.types) {
      std::string generated_type_name;
      if (type->StructSupertype()) {
        generated_type_name = "\n#error no structs allowed in labels\n";
      } else {
        generated_type_name = "compiler::TypedCodeAssemblerVariable<";
        generated_type_name += type->GetGeneratedTNodeTypeName();
        generated_type_name += ">*";
      }
      f.AddParameter(generated_type_name,
                     ExternalLabelParameterName(label_info.name->value, i));
      ++i;
    }
  }
  if (generated_parameter_names) {
    *generated_parameter_names = f.GetParameterNames();
    if (ignore_first_parameter) {
      DCHECK(!generated_parameter_names->empty());
      generated_parameter_names->erase(generated_parameter_names->begin());
    }
  }
  return f;
}
References v8::internal::torque::cpp::Function::AddParameter(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, ExternalLabelName(), ExternalLabelParameterName(), ExternalParameterName(), v8::internal::torque::Type::GetDebugType(), v8::internal::torque::Type::GetGeneratedTypeName(), v8::internal::torque::cpp::Function::GetParameterNames(), v8::internal::torque::Type::GetRuntimeType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::Type::IsConstexpr(), v8::internal::torque::Type::IsVoidOrNever(), v8::internal::torque::kCC, v8::internal::torque::kCCDebug, v8::internal::torque::kCSA, v8::internal::torque::Signature::labels, v8::internal::name, v8::internal::torque::LabelDeclaration::name, output_type_, v8::internal::torque::ReportError(), v8::internal::torque::Signature::return_type, v8::internal::torque::cpp::Function::SetReturnType(), size(), v8::internal::size_t, v8::internal::string, v8::internal::torque::Type::TagglifiedCppTypeName(), v8::internal::tracing::type, v8::internal::torque::LabelDeclaration::types, v8::internal::torque::Signature::types(), and v8::internal::torque::Identifier::value.
Referenced by GenerateMacroFunctionDeclaration().
GenerateImplementation()
void v8::internal::torque::ImplementationVisitor::GenerateImplementation (const std::string & dir)
Definition at line 1839 of file implementation-visitor.cc.
                                                                       {
  for (SourceId file : SourceFileMap::AllSources()) {
    std::string base_filename =
        dir + "/" + SourceFileMap::PathFromV8RootWithoutExtension(file);
    GlobalContext::PerFileStreams& streams =
        GlobalContext::GeneratedPerFile(file);
    std::string csa_cc = streams.csa_ccfile.str();
    // Insert missing builtin includes where the marker is.
    {
      auto pos = csa_cc.find(BuiltinIncludesMarker);
      CHECK_NE(pos, std::string::npos);
      std::string includes;
      for (const SourceId& include : streams.required_builtin_includes) {
        std::string include_file =
            SourceFileMap::PathFromV8RootWithoutExtension(include);
        includes += "#include \"torque-generated/";
        includes += include_file;
        includes += "-tq-csa.h\"\n";
      }
      csa_cc.replace(pos, strlen(BuiltinIncludesMarker), std::move(includes));
    }
    // TODO(torque-builder): Pass file directly.
    WriteFile(base_filename + "-tq-csa.cc", std::move(csa_cc));
    WriteFile(base_filename + "-tq-csa.h", streams.csa_headerfile.str());
    WriteFile(base_filename + "-tq.inc",
              streams.class_definition_headerfile.str());
    WriteFile(
        base_filename + "-tq-inl.inc",
        streams.class_definition_inline_headerfile_macro_declarations.str() +
            streams.class_definition_inline_headerfile_macro_definitions.str() +
            streams.class_definition_inline_headerfile.str());
    WriteFile(base_filename + "-tq.cc", streams.class_definition_ccfile.str());
  }
  WriteFile(dir + "/debug-macros.h", debug_macros_h_.str());
  WriteFile(dir + "/debug-macros.cc", debug_macros_cc_.str());
}
References v8::internal::torque::SourceFileMap::AllSources(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::BuiltinIncludesMarker, CHECK_NE, v8::internal::torque::GlobalContext::PerFileStreams::class_definition_ccfile, v8::internal::torque::GlobalContext::PerFileStreams::class_definition_headerfile, v8::internal::torque::GlobalContext::PerFileStreams::class_definition_inline_headerfile, v8::internal::torque::GlobalContext::PerFileStreams::class_definition_inline_headerfile_macro_declarations, v8::internal::torque::GlobalContext::PerFileStreams::class_definition_inline_headerfile_macro_definitions, v8::internal::torque::GlobalContext::PerFileStreams::csa_ccfile, v8::internal::torque::GlobalContext::PerFileStreams::csa_headerfile, debug_macros_cc_, debug_macros_h_, file(), v8::internal::torque::GlobalContext::GeneratedPerFile(), v8::internal::torque::SourceFileMap::PathFromV8RootWithoutExtension(), v8::internal::torque::GlobalContext::PerFileStreams::required_builtin_includes, v8::internal::string, and WriteFile().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
GenerateImplicitConvert()
VisitResult v8::internal::torque::ImplementationVisitor::GenerateImplicitConvert (const Type * destination_type, VisitResult source) [private]
Definition at line 3386 of file implementation-visitor.cc.
                                                      {
  StackScope scope(this);
  if (source.type() == TypeOracle::GetNeverType()) {
    ReportError("it is not allowed to use a value of type never");
  }
  if (destination_type == source.type()) {
    return scope.Yield(GenerateCopy(source));
  }
  if (auto from = TypeOracle::ImplicitlyConvertableFrom(destination_type,
                                                        source.type())) {
    return scope.Yield(GenerateCall(kFromConstexprMacroName,
                                    Arguments{{source}, {}},
                                    {destination_type, *from}, false));
  } else if (IsAssignableFrom(destination_type, source.type())) {
    source.SetType(destination_type);
    return scope.Yield(GenerateCopy(source));
  } else {
    std::stringstream s;
    if (const TopType* top_type = TopType::DynamicCast(source.type())) {
      s << "undefined expression of type " << *destination_type << ": the "
        << top_type->reason();
    } else {
      s << "cannot use expression of type " << *source.type()
        << " as a value of type " << *destination_type;
    }
    ReportError(s.str());
  }
}
References v8::internal::torque::IsAssignableFrom(), v8::internal::torque::kFromConstexprMacroName, v8::internal::torque::ReportError(), v8::internal::torque::VisitResult::SetType(), v8::internal::torque::VisitResult::type(), and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Referenced by GenerateFieldReferenceForInit(), and Visit().
GenerateInstanceTypes()
void v8::internal::torque::ImplementationVisitor::GenerateInstanceTypes (const std::string & output_directory)
Definition at line 374 of file instance-type-generator.cc.
                                       {
  std::stringstream header;
  std::string file_name = "instance-types.h";
  {
    IncludeGuardScope guard(header, file_name);
    header << "// Instance types for all classes except for those that use "
              "InstanceType as flags.\n";
    header << "#define TORQUE_ASSIGNED_INSTANCE_TYPES(V) \\\n";
    std::unique_ptr<InstanceTypeTree> instance_types = AssignInstanceTypes();
    std::stringstream values_list;
    std::stringstream fully_defined_single_instance_types;
    std::stringstream fully_defined_multiple_instance_types;
    std::stringstream only_declared_single_instance_types;
    std::stringstream only_declared_multiple_instance_types;
    std::stringstream fully_defined_range_instance_types;
    std::stringstream only_declared_range_instance_types;
    if (instance_types != nullptr) {
      PrintInstanceTypes(instance_types.get(), header, values_list,
                         fully_defined_single_instance_types,
                         fully_defined_multiple_instance_types,
                         only_declared_single_instance_types,
                         only_declared_multiple_instance_types,
                         fully_defined_range_instance_types,
                         only_declared_range_instance_types, " ");
    }
    header << "\n";
    header << "// Instance types for all classes except for those that use\n";
    header << "// InstanceType as flags.\n";
    header << "#define TORQUE_ASSIGNED_INSTANCE_TYPE_LIST(V) \\\n";
    header << values_list.str();
    header << "\n";
    header << "// Pairs of (ClassName, INSTANCE_TYPE) for classes that have\n";
    header << "// full Torque definitions.\n";
    header << "#define TORQUE_INSTANCE_CHECKERS_SINGLE_FULLY_DEFINED(V) \\\n";
    header << fully_defined_single_instance_types.str();
    header << "\n";
    header << "// Pairs of (ClassName, INSTANCE_TYPE) for classes that have\n";
    header << "// full Torque definitions and subclasses.\n";
    header << "#define TORQUE_INSTANCE_CHECKERS_MULTIPLE_FULLY_DEFINED(V) \\\n";
    header << fully_defined_multiple_instance_types.str();
    header << "\n";
    header << "// Pairs of (ClassName, INSTANCE_TYPE) for classes that are\n";
    header << "// declared but not defined in Torque. These classes may\n";
    header << "// correspond with actual C++ classes, but they are not\n";
    header << "// guaranteed to.\n";
    header << "#define TORQUE_INSTANCE_CHECKERS_SINGLE_ONLY_DECLARED(V) \\\n";
    header << only_declared_single_instance_types.str();
    header << "\n";
    header << "// Pairs of (ClassName, INSTANCE_TYPE) for classes that are\n";
    header << "// declared but not defined in Torque, and have subclasses.\n";
    header << "// These classes may correspond with actual C++ classes, but\n";
    header << "// they are not guaranteed to.\n";
    header << "#define TORQUE_INSTANCE_CHECKERS_MULTIPLE_ONLY_DECLARED(V) \\\n";
    header << only_declared_multiple_instance_types.str();
    header << "\n";
    header << "// Triples of (ClassName, FIRST_TYPE, LAST_TYPE) for classes\n";
    header << "// that have full Torque definitions.\n";
    header << "#define TORQUE_INSTANCE_CHECKERS_RANGE_FULLY_DEFINED(V) \\\n";
    header << fully_defined_range_instance_types.str();
    header << "\n";
    header << "// Triples of (ClassName, FIRST_TYPE, LAST_TYPE) for classes\n";
    header << "// that are declared but not defined in Torque. These classes\n";
    header << "// may correspond with actual C++ classes, but they are not\n";
    header << "// guaranteed to.\n";
    header << "#define TORQUE_INSTANCE_CHECKERS_RANGE_ONLY_DECLARED(V) \\\n";
    header << only_declared_range_instance_types.str();
    header << "\n";
    std::stringstream torque_defined_class_list;
    std::stringstream torque_defined_varsize_instance_type_list;
    std::stringstream torque_defined_fixed_instance_type_list;
    std::stringstream torque_defined_map_csa_list;
    std::stringstream torque_defined_map_root_list;
    for (const ClassType* type : TypeOracle::GetClasses()) {
      std::string upper_case_name = type->name();
      std::string lower_case_name = SnakeifyString(type->name());
      std::string instance_type_name =
          CapifyStringWithUnderscores(type->name()) + "_TYPE";
      if (!type->IsExtern()) {
        torque_defined_class_list << " V(" << upper_case_name << ") \\\n";
      }
      if (type->ShouldGenerateUniqueMap()) {
        torque_defined_map_csa_list << " V(_, " << upper_case_name << "Map, "
                                    << lower_case_name << "_map, "
                                    << upper_case_name << ") \\\n";
        torque_defined_map_root_list << " V(Map, " << lower_case_name
                                     << "_map, " << upper_case_name
                                     << "Map) \\\n";
        std::stringstream& list =
            type->HasStaticSize() ? torque_defined_fixed_instance_type_list
                                  : torque_defined_varsize_instance_type_list;
        list << " V(" << instance_type_name << ", " << upper_case_name << ", "
             << lower_case_name << ") \\\n";
      }
    }
    header << "// Fully Torque-defined classes (both internal and exported).\n";
    header << "#define TORQUE_DEFINED_CLASS_LIST(V) \\\n";
    header << torque_defined_class_list.str();
    header << "\n";
    header << "#define TORQUE_DEFINED_VARSIZE_INSTANCE_TYPE_LIST(V) \\\n";
    header << torque_defined_varsize_instance_type_list.str();
    header << "\n";
    header << "#define TORQUE_DEFINED_FIXED_INSTANCE_TYPE_LIST(V) \\\n";
    header << torque_defined_fixed_instance_type_list.str();
    header << "\n";
    header << "#define TORQUE_DEFINED_INSTANCE_TYPE_LIST(V) \\\n";
    header << " TORQUE_DEFINED_VARSIZE_INSTANCE_TYPE_LIST(V) \\\n";
    header << " TORQUE_DEFINED_FIXED_INSTANCE_TYPE_LIST(V) \\\n";
    header << "\n";
    header << "#define TORQUE_DEFINED_MAP_CSA_LIST_GENERATOR(V, _) \\\n";
    header << torque_defined_map_csa_list.str();
    header << "\n";
    header << "#define TORQUE_DEFINED_MAP_ROOT_LIST(V) \\\n";
    header << torque_defined_map_root_list.str();
    header << "\n";
  }
  std::string output_header_path = output_directory + "/" + file_name;
  WriteFile(output_header_path, header.str());
  GlobalContext::SetInstanceTypesInitialized();
}
References v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::AssignInstanceTypes(), v8::internal::torque::CapifyStringWithUnderscores(), v8::internal::torque::TypeOracle::GetClasses(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PrintInstanceTypes(), v8::internal::torque::GlobalContext::SetInstanceTypesInitialized(), v8::internal::torque::SnakeifyString(), v8::internal::string, v8::internal::tracing::type, and WriteFile().
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
GenerateLabelGoto()
StackRange v8::internal::torque::ImplementationVisitor::GenerateLabelGoto (LocalLabel * label, std::optional< StackRange > arguments = {}) [private]
Definition at line 3418 of file implementation-visitor.cc.
                                                          {
  return assembler().Goto(label->block, arguments ? arguments->Size() : 0);
}
References v8::internal::torque::LocalLabel::block.
GenerateLayoutForInitialization()
LayoutForInitialization v8::internal::torque::ImplementationVisitor::GenerateLayoutForInitialization (const ClassType * class_type, const InitializerResults & initializer_results)
Definition at line 1637 of file implementation-visitor.cc.
                                                   {
  LayoutForInitialization layout;
  VisitResult offset;
  for (Field f : class_type->ComputeAllFields()) {
    if (f.offset.has_value()) {
      offset =
          VisitResult(TypeOracle::GetConstInt31Type(), ToString(*f.offset));
    }
    layout.offsets[f.name_and_type.name] = offset;
    if (f.index) {
      size_t element_size;
      std::string element_size_string;
      std::tie(element_size, element_size_string) =
          *SizeOf(f.name_and_type.type);
      VisitResult array_element_size =
          VisitResult(TypeOracle::GetConstInt31Type(), element_size_string);
      VisitResult array_length =
          GenerateArrayLength(class_type, initializer_results, f);
      layout.array_lengths[f.name_and_type.name] = array_length;
      Arguments arguments;
      arguments.parameters = {offset, array_length, array_element_size};
      offset = GenerateCall(QualifiedName({TORQUE_INTERNAL_NAMESPACE_STRING},
                                          "AddIndexedFieldSizeToObjectSize"),
                            arguments);
    } else {
      DCHECK(f.offset.has_value());
    }
  }
  if (class_type->size().SingleValue()) {
    layout.size = VisitResult(TypeOracle::GetConstInt31Type(),
                              ToString(*class_type->size().SingleValue()));
  } else {
    layout.size = offset;
  }
  if ((size_t{1} << class_type->size().AlignmentLog2()) <
      TargetArchitecture::TaggedSize()) {
    Arguments arguments;
    arguments.parameters = {layout.size};
    layout.size = GenerateCall(
        QualifiedName({TORQUE_INTERNAL_NAMESPACE_STRING}, "AlignTagged"),
        arguments);
  }
  return layout;
}
References v8::internal::torque::LayoutForInitialization::array_lengths, v8::internal::torque::ClassType::ComputeAllFields(), v8::internal::DCHECK(), GenerateArrayLength(), GenerateCall(), v8::internal::torque::TypeOracle::GetConstInt31Type(), v8::internal::torque::LayoutForInitialization::offsets, v8::internal::torque::Arguments::parameters, v8::internal::torque::ResidueClass::SingleValue(), v8::internal::torque::LayoutForInitialization::size, v8::internal::torque::ClassType::size(), v8::internal::torque::SizeOf(), v8::internal::string, v8::internal::torque::TargetArchitecture::TaggedSize(), v8::internal::torque::TORQUE_INTERNAL_NAMESPACE_STRING, and v8::internal::torque::ToString().
Referenced by Visit().
GenerateMacroFunctionDeclaration()
cpp::Function v8::internal::torque::ImplementationVisitor::GenerateMacroFunctionDeclaration (Macro * macro) [private]
Definition at line 1879 of file implementation-visitor.cc.
                  {
  return GenerateFunction(nullptr,
                          output_type_ == OutputType::kCC
                              ? macro->CCName()
                              : output_type_ == OutputType::kCCDebug
                                    ? macro->CCDebugName()
                                    : macro->ExternalName(),
                          macro->signature(), macro->parameter_names());
}
References v8::internal::torque::Callable::CCDebugName(), v8::internal::torque::Callable::CCName(), v8::internal::torque::Callable::ExternalName(), GenerateFunction(), v8::internal::torque::kCC, v8::internal::torque::kCCDebug, output_type_, v8::internal::torque::Callable::parameter_names(), and v8::internal::torque::Callable::signature().
GeneratePointerCall()
VisitResult v8::internal::torque::ImplementationVisitor::GeneratePointerCall (Expression * callee, const Arguments & parameters, bool tail_call) [private]
Definition at line 2687 of file implementation-visitor.cc.
                                                                      {
  StackScope scope(this);
  TypeVector parameter_types(arguments.parameters.ComputeTypeVector());
  VisitResult callee_result = Visit(callee);
  if (!callee_result.type()->IsBuiltinPointerType()) {
    std::stringstream stream;
    stream << "Expected a function pointer type but found "
           << *callee_result.type();
    ReportError(stream.str());
  }
  const BuiltinPointerType* type =
      BuiltinPointerType::cast(callee_result.type());
  if (type->parameter_types().size() != parameter_types.size()) {
    std::stringstream stream;
    stream << "parameter count mismatch calling function pointer with Type: "
           << *type << " - expected "
           << std::to_string(type->parameter_types().size()) << ", found "
           << std::to_string(parameter_types.size());
    ReportError(stream.str());
  }
  ParameterTypes types{type->parameter_types(), false};
  Signature sig;
  sig.parameter_types = types;
  if (!IsCompatibleSignature(sig, parameter_types, 0)) {
    std::stringstream stream;
    stream << "parameters do not match function pointer signature. Expected: ("
           << type->parameter_types() << ") but got: (" << parameter_types
           << ")";
    ReportError(stream.str());
  }
  callee_result = GenerateCopy(callee_result);
  StackRange arg_range = assembler().TopRange(0);
  for (size_t current = 0; current < arguments.parameters.size(); ++current) {
    const Type* to_type = type->parameter_types()[current];
    arg_range.Extend(
        GenerateImplicitConvert(to_type, arguments.parameters[current])
            .stack_range());
  }
  assembler().Emit(
      CallBuiltinPointerInstruction{is_tailcall, type, arg_range.Size()});
  if (is_tailcall) {
    return VisitResult::NeverResult();
  }
  DCHECK_EQ(1, LoweredSlotCount(type->return_type()));
  return scope.Yield(VisitResult(type->return_type(), assembler().TopRange(1)));
}
References v8::internal::torque::VisitResultVector::ComputeTypeVector(), DCHECK_EQ, v8::internal::torque::StackRange::Extend(), v8::internal::torque::IsCompatibleSignature(), v8::internal::torque::LoweredSlotCount(), v8::internal::torque::Arguments::parameters, v8::internal::torque::ReportError(), v8::internal::sig, v8::internal::torque::StackRange::Size(), v8::internal::torque::VisitResult::type(), v8::internal::tracing::type, and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
GeneratePrintDefinitions()
void v8::internal::torque::ImplementationVisitor::GeneratePrintDefinitions (const std::string & output_directory)
Definition at line 5078 of file implementation-visitor.cc.
                                       {
  std::stringstream impl;
  std::string file_name = "objects-printer.cc";
  {
    IfDefScope object_print(impl, "OBJECT_PRINT");
    impl << "#include <iosfwd>\n\n";
    impl << "#include \"src/objects/all-objects-inl.h\"\n\n";
    NamespaceScope impl_namespaces(impl, {"v8", "internal"});
    for (const ClassType* type : TypeOracle::GetClasses()) {
      if (!type->ShouldGeneratePrint()) continue;
      DCHECK(type->ShouldGenerateCppClassDefinitions());
      const ClassType* super = type->GetSuperClass();
      std::string gen_name = "TorqueGenerated" + type->name();
      std::string gen_name_T =
          gen_name + "<" + type->name() + ", " + super->name() + ">";
      std::string template_decl = "template <>";
      GeneratePrintDefinitionsForClass(impl, type, gen_name, gen_name_T,
                                       template_decl);
    }
  }
  std::string new_contents(impl.str());
  WriteFile(output_directory + "/" + file_name, new_contents);
}
References v8::internal::DCHECK(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GeneratePrintDefinitionsForClass(), wasm::impl(), v8::internal::torque::AggregateType::name(), v8::internal::string, and v8::internal::tracing::type.
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
GenerateReferenceToItemInHeapSlice()
LocationReference v8::internal::torque::ImplementationVisitor::GenerateReferenceToItemInHeapSlice (LocationReference slice, VisitResult index)
Definition at line 2445 of file implementation-visitor.cc.
                                                {
  DCHECK(slice.IsHeapSlice());
  Arguments arguments{{index}, {}};
  const StructType* slice_type = *slice.heap_slice().type()->StructSupertype();
  Method* method = LookupMethod("AtIndex", slice_type, arguments, {});
  // The reference has to be treated like a normal value when calling methods
  // on the underlying slice implementation.
  LocationReference slice_value =
      LocationReference::Temporary(slice.GetVisitResult(), "slice as value");
  return LocationReference::HeapReference(
      GenerateCall(method, std::move(slice_value), arguments, {}, false));
}
References v8::internal::DCHECK(), GenerateCall(), v8::internal::torque::LocationReference::GetVisitResult(), v8::internal::torque::LocationReference::heap_slice(), v8::internal::torque::LocationReference::HeapReference(), v8::internal::index, v8::internal::torque::LocationReference::IsHeapSlice(), LookupMethod(), v8::internal::torque::Type::StructSupertype(), v8::internal::torque::LocationReference::Temporary(), and v8::internal::torque::VisitResult::type().
Referenced by GetLocationReference().
GenerateSetBitField()
VisitResult v8::internal::torque::ImplementationVisitor::GenerateSetBitField (const Type * bitfield_struct_type, const BitField & bitfield, VisitResult bitfield_struct, VisitResult value, bool starts_as_zero = false) [private]
Definition at line 2281 of file implementation-visitor.cc.
                                                                         {
  GenerateCopy(bitfield_struct);
  GenerateCopy(value);
  assembler().Emit(
      StoreBitFieldInstruction{bitfield_struct_type, bitfield, starts_as_zero});
  return VisitResult(bitfield_struct_type, assembler().TopRange(1));
}
References assembler(), v8::internal::torque::CfgAssembler::Emit(), GenerateCopy(), and v8::internal::value.
Referenced by Visit().
GenerateVisitorLists()
void v8::internal::torque::ImplementationVisitor::GenerateVisitorLists (const std::string & output_directory)
Definition at line 3934 of file implementation-visitor.cc.
                                       {
  std::stringstream header;
  std::string file_name = "visitor-lists.h";
  {
    IncludeGuardScope include_guard(header, file_name);
    header << "#define TORQUE_INSTANCE_TYPE_TO_BODY_DESCRIPTOR_LIST(V)\\\n";
    for (const ClassType* type : TypeOracle::GetClasses()) {
      if (type->ShouldGenerateBodyDescriptor() && type->OwnInstanceType()) {
        std::string type_name =
            CapifyStringWithUnderscores(type->name()) + "_TYPE";
        header << "V(" << type_name << "," << type->name() << ")\\\n";
      }
    }
    header << "\n";
    header << "#define TORQUE_DATA_ONLY_VISITOR_ID_LIST(V)\\\n";
    for (const ClassType* type : TypeOracle::GetClasses()) {
      if (type->ShouldGenerateBodyDescriptor() &&
          type->HasNoPointerSlotsExceptMap()) {
        header << "V(" << type->name() << ")\\\n";
      }
    }
    header << "\n";
    header << "#define TORQUE_POINTER_VISITOR_ID_LIST(V)\\\n";
    for (const ClassType* type : TypeOracle::GetClasses()) {
      if (type->ShouldGenerateBodyDescriptor() &&
          !type->HasNoPointerSlotsExceptMap()) {
        header << "V(" << type->name() << ")\\\n";
      }
    }
    header << "\n";
  }
  const std::string output_header_path = output_directory + "/" + file_name;
  WriteFile(output_header_path, header.str());
}
References v8::internal::torque::CapifyStringWithUnderscores(), v8::internal::string, and v8::internal::tracing::type.
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
GetAndClearReturnValue()
VisitResult v8::internal::torque::ImplementationVisitor::GetAndClearReturnValue () [inline], [private]
Definition at line 837 of file implementation-visitor.h.
                                       {
    VisitResult return_value = *CurrentReturnValue::Get();
    CurrentReturnValue::Get() = std::nullopt;
    return return_value;
  }
References v8::internal::compiler::turboshaft::Get().
GetBuiltinCode()
VisitResult v8::internal::torque::ImplementationVisitor::GetBuiltinCode (Builtin * builtin)
Definition at line 1032 of file implementation-visitor.cc.
                                                                  {
  if (builtin->IsExternal() || builtin->kind() != Builtin::kStub) {
    ReportError(
        "creating function pointers is only allowed for internal builtins with "
        "stub linkage");
  }
  const Type* type = TypeOracle::GetBuiltinPointerType(
      builtin->signature().parameter_types.types,
      builtin->signature().return_type);
  assembler().Emit(
      PushBuiltinPointerInstruction{builtin->ExternalName(), type});
  return VisitResult(type, assembler().TopRange(1));
}
References v8::internal::torque::Callable::ExternalName(), v8::internal::torque::TypeOracle::GetBuiltinPointerType(), v8::internal::torque::Callable::IsExternal(), v8::internal::torque::Builtin::kind(), v8::internal::torque::Builtin::kStub, v8::internal::torque::Signature::parameter_types, v8::internal::torque::ReportError(), v8::internal::torque::Signature::return_type, v8::internal::torque::Callable::signature(), v8::internal::tracing::type, and v8::internal::torque::ParameterTypes::types.
Referenced by GetLocationReference().
GetCatchBlock()
std::optional< Block * > v8::internal::torque::ImplementationVisitor::GetCatchBlock () [private]
Definition at line 3508 of file implementation-visitor.cc.
                                                         {
  std::optional<Block*> catch_block;
  if (TryLookupLabel(kCatchLabelName)) {
    catch_block = assembler().NewBlock(std::nullopt, true);
  }
  return catch_block;
}
References v8::internal::torque::kCatchLabelName.
GetCommonType()
const Type * v8::internal::torque::ImplementationVisitor::GetCommonType (const Type * left, const Type * right) [private]
Definition at line 2199 of file implementation-visitor.cc.
                                                                    {
  const Type* common_type;
  if (IsAssignableFrom(left, right)) {
    common_type = left;
  } else if (IsAssignableFrom(right, left)) {
    common_type = right;
  } else {
    common_type = TypeOracle::GetUnionType(left, right);
  }
  common_type = common_type->NonConstexprVersion();
  return common_type;
}
References v8::internal::torque::TypeOracle::GetUnionType(), v8::internal::torque::IsAssignableFrom(), and v8::internal::torque::Type::NonConstexprVersion().
GetLocationReference() [1/5]
LocationReference v8::internal::torque::ImplementationVisitor::GetLocationReference (DereferenceExpression * expr)
Definition at line 2543 of file implementation-visitor.cc.
                                 {
  VisitResult ref = Visit(expr->reference);
  if (!TypeOracle::MatchReferenceGeneric(ref.type())) {
    Error("Operator * expects a reference type but found a value of type ",
          *ref.type())
        .Throw();
  }
  return LocationReference::HeapReference(ref);
}
References v8::internal::torque::Error(), v8::internal::torque::LocationReference::HeapReference(), v8::internal::torque::TypeOracle::MatchReferenceGeneric(), v8::internal::torque::DereferenceExpression::reference, v8::internal::torque::MessageBuilder::Throw(), v8::internal::torque::VisitResult::type(), and Visit().
GetLocationReference() [2/5]
LocationReference v8::internal::torque::ImplementationVisitor::GetLocationReference (ElementAccessExpression * expr)
Definition at line 2433 of file implementation-visitor.cc.
                                   {
  LocationReference reference = GetLocationReference(expr->array);
  VisitResult index = Visit(expr->index);
  if (reference.IsHeapSlice()) {
    return GenerateReferenceToItemInHeapSlice(reference, index);
  } else {
    return LocationReference::ArrayAccess(GenerateFetchFromLocation(reference),
                                          index);
  }
}
References v8::internal::torque::ElementAccessExpression::array, v8::internal::torque::LocationReference::ArrayAccess(), GenerateFetchFromLocation(), GenerateReferenceToItemInHeapSlice(), GetLocationReference(), v8::internal::index, v8::internal::torque::ElementAccessExpression::index, v8::internal::torque::LocationReference::IsHeapSlice(), and Visit().
GetLocationReference() [3/5]
LocationReference v8::internal::torque::ImplementationVisitor::GetLocationReference (Expression * location)
Definition at line 2291 of file implementation-visitor.cc.
                          {
  switch (location->kind) {
    case AstNode::Kind::kIdentifierExpression:
      return GetLocationReference(static_cast<IdentifierExpression*>(location));
    case AstNode::Kind::kFieldAccessExpression:
      return GetLocationReference(
          static_cast<FieldAccessExpression*>(location));
    case AstNode::Kind::kElementAccessExpression:
      return GetLocationReference(
          static_cast<ElementAccessExpression*>(location));
    case AstNode::Kind::kDereferenceExpression:
      return GetLocationReference(
          static_cast<DereferenceExpression*>(location));
    default:
      return LocationReference::Temporary(Visit(location), "expression");
  }
}
References v8::internal::torque::AstNode::kind, v8::internal::torque::LocationReference::Temporary(), and Visit().
Referenced by GetLocationReference().
GetLocationReference() [4/5]
LocationReference v8::internal::torque::ImplementationVisitor::GetLocationReference (FieldAccessExpression * expr)
Definition at line 2310 of file implementation-visitor.cc.
                                 {
  return GenerateFieldAccess(GetLocationReference(expr->object),
                             expr->field->value, false, expr->field->pos);
}
References v8::internal::torque::FieldAccessExpression::field, GenerateFieldAccess(), GetLocationReference(), v8::internal::torque::FieldAccessExpression::object, v8::internal::torque::AstNode::pos, and v8::internal::torque::Identifier::value.
GetLocationReference() [5/5]
LocationReference v8::internal::torque::ImplementationVisitor::GetLocationReference (IdentifierExpression * expr)
Definition at line 2459 of file implementation-visitor.cc.
                                {
  if (expr->namespace_qualification.empty()) {
    if (std::optional<Binding<LocalValue>*> value =
            TryLookupLocalValue(expr->name->value)) {
      if (GlobalContext::collect_language_server_data()) {
        LanguageServerData::AddDefinition(expr->name->pos,
                                          (*value)->declaration_position());
      }
      if (GlobalContext::collect_kythe_data()) {
        if (!expr->IsThis()) {
          DCHECK_EQ(expr->name->pos.end.column - expr->name->pos.start.column,
                    expr->name->value.length());
          KytheData::AddBindingUse(expr->name->pos, *value);
        }
      }
      if (!expr->generic_arguments.empty()) {
        ReportError("cannot have generic parameters on local name ",
                    expr->name);
      }
      return (*value)->GetLocationReference(*value);
    }
  }
  if (expr->IsThis()) {
    ReportError("\"this\" cannot be qualified");
  }
  QualifiedName name =
      QualifiedName(expr->namespace_qualification, expr->name->value);
  if (std::optional<Builtin*> builtin = Declarations::TryLookupBuiltin(name)) {
    if (GlobalContext::collect_language_server_data()) {
      LanguageServerData::AddDefinition(expr->name->pos,
                                        (*builtin)->Position());
    }
    // TODO(v8:12261): Consider collecting KytheData here.
    return LocationReference::Temporary(GetBuiltinCode(*builtin),
                                        "builtin " + expr->name->value);
  }
  if (!expr->generic_arguments.empty()) {
    GenericCallable* generic = Declarations::LookupUniqueGeneric(name);
    Callable* specialization =
        GetOrCreateSpecialization(SpecializationKey<GenericCallable>{
            generic, TypeVisitor::ComputeTypeVector(expr->generic_arguments)});
    if (Builtin* builtin = Builtin::DynamicCast(specialization)) {
      DCHECK(!builtin->IsExternal());
      return LocationReference::Temporary(GetBuiltinCode(builtin),
                                          "builtin " + expr->name->value);
    } else {
      ReportError("cannot create function pointer for non-builtin ",
                  generic->name());
    }
  }
  Value* value = Declarations::LookupValue(name);
  CHECK(value->Position().source.IsValid());
  if (auto stream = CurrentFileStreams::Get()) {
    stream->required_builtin_includes.insert(value->Position().source);
  }
  if (GlobalContext::collect_language_server_data()) {
    LanguageServerData::AddDefinition(expr->name->pos, value->name()->pos);
  }
  if (auto* constant = NamespaceConstant::DynamicCast(value)) {
    if (GlobalContext::collect_kythe_data()) {
      KytheData::AddConstantUse(expr->name->pos, constant);
    }
    if (constant->type()->IsConstexpr()) {
      return LocationReference::Temporary(
          VisitResult(constant->type(), constant->external_name() + "(state_)"),
          "namespace constant " + expr->name->value);
    }
    assembler().Emit(NamespaceConstantInstruction{constant});
    StackRange stack_range =
        assembler().TopRange(LoweredSlotCount(constant->type()));
    return LocationReference::Temporary(
        VisitResult(constant->type(), stack_range),
        "namespace constant " + expr->name->value);
  }
  ExternConstant* constant = ExternConstant::cast(value);
  if (GlobalContext::collect_kythe_data()) {
    KytheData::AddConstantUse(expr->name->pos, constant);
  }
  return LocationReference::Temporary(constant->value(),
                                      "extern value " + expr->name->value);
}
References v8::internal::torque::KytheData::AddBindingUse(), v8::internal::torque::KytheData::AddConstantUse(), v8::internal::torque::LanguageServerData::AddDefinition(), assembler(), CHECK, v8::internal::torque::GlobalContext::collect_kythe_data(), v8::internal::torque::GlobalContext::collect_language_server_data(), v8::internal::torque::LineAndColumn::column, v8::internal::torque::TypeVisitor::ComputeTypeVector(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::torque::CfgAssembler::Emit(), v8::internal::torque::SourcePosition::end, v8::internal::torque::IdentifierExpression::generic_arguments, v8::internal::compiler::turboshaft::Get(), GetBuiltinCode(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GetOrCreateSpecialization(), v8::internal::torque::IdentifierExpression::IsThis(), v8::internal::torque::Declarations::LookupUniqueGeneric(), v8::internal::torque::Declarations::LookupValue(), v8::internal::torque::LoweredSlotCount(), v8::internal::name, v8::internal::torque::IdentifierExpression::name, v8::internal::torque::IdentifierExpression::namespace_qualification, v8::internal::torque::AstNode::pos, v8::internal::torque::ReportError(), v8::internal::torque::SourcePosition::start, v8::internal::torque::LocationReference::Temporary(), v8::internal::torque::CfgAssembler::TopRange(), v8::internal::torque::Declarations::TryLookupBuiltin(), TryLookupLocalValue(), v8::internal::value, v8::internal::torque::Identifier::value, and v8::internal::torque::Value::value().
InferSpecializationTypes()
TypeArgumentInference v8::internal::torque::ImplementationVisitor::InferSpecializationTypes (GenericCallable * generic, const TypeVector & explicit_specialization_types, const TypeVector & explicit_arguments) [private]
Definition at line 2062 of file implementation-visitor.cc.
                                          {
  std::vector<std::optional<const Type*>> all_arguments;
  const ParameterList& parameters = generic->declaration()->parameters;
  for (size_t i = 0; i < parameters.implicit_count; ++i) {
    std::optional<Binding<LocalValue>*> val =
        TryLookupLocalValue(parameters.names[i]->value);
    all_arguments.push_back(
        val ? (*val)->GetLocationReference(*val).ReferencedType()
            : std::nullopt);
  }
  for (const Type* explicit_argument : explicit_arguments) {
    all_arguments.push_back(explicit_argument);
  }
  return generic->InferSpecializationTypes(explicit_specialization_types,
                                           all_arguments);
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::ParameterList::implicit_count, v8::internal::torque::ParameterList::names, and TryLookupLocalValue().
Referenced by LookupCallable().
InitializeClass()
void v8::internal::torque::ImplementationVisitor::InitializeClass (const ClassType * class_type, VisitResult allocate_result, const InitializerResults & initializer_results, const LayoutForInitialization & layout)
Definition at line 1534 of file implementation-visitor.cc.
                                           {
  if (const ClassType* super = class_type->GetSuperClass()) {
    InitializeClass(super, allocate_result, initializer_results, layout);
  }
  for (const Field& f : class_type->fields()) {
    // Support optional padding fields.
    if (f.name_and_type.type->IsVoid()) continue;
    VisitResult initializer_value =
        initializer_results.field_value_map.at(f.name_and_type.name);
    LocationReference field =
        GenerateFieldReferenceForInit(allocate_result, f, layout);
    if (f.index) {
      DCHECK(field.IsHeapSlice());
      VisitResult slice = field.GetVisitResult();
      GenerateCall(QualifiedName({TORQUE_INTERNAL_NAMESPACE_STRING},
                                 "InitializeFieldsFromIterator"),
                   {{slice, initializer_value}, {}});
    } else {
      GenerateAssignToLocation(field, initializer_value);
    }
  }
}
References v8::internal::DCHECK(), v8::internal::torque::InitializerResults::field_value_map, v8::internal::torque::AggregateType::fields(), GenerateAssignToLocation(), GenerateCall(), GenerateFieldReferenceForInit(), v8::internal::torque::ClassType::GetSuperClass(), v8::internal::torque::LocationReference::GetVisitResult(), v8::internal::torque::LocationReference::IsHeapSlice(), and v8::internal::torque::TORQUE_INTERNAL_NAMESPACE_STRING.
Referenced by Visit().
InlineMacro()
VisitResult v8::internal::torque::ImplementationVisitor::InlineMacro (Macro * macro, std::optional< LocationReference > this_reference, const std::vector< VisitResult > & arguments, const std::vector< Block * > label_blocks)
Definition at line 289 of file implementation-visitor.cc.
                                          {
  MacroInliningScope macro_inlining_scope(this, macro);
  CurrentScope::Scope current_scope(macro);
  BindingsManagersScope bindings_managers_scope;
  CurrentCallable::Scope current_callable(macro);
  CurrentReturnValue::Scope current_return_value;
  const Signature& signature = macro->signature();
  const Type* return_type = macro->signature().return_type;
  bool can_return = return_type != TypeOracle::GetNeverType();
  BlockBindings<LocalValue> parameter_bindings(&ValueBindingsManager::Get());
  BlockBindings<LocalLabel> label_bindings(&LabelBindingsManager::Get());
  DCHECK_EQ(macro->signature().parameter_names.size(),
            arguments.size() + (this_reference ? 1 : 0));
  DCHECK_EQ(this_reference.has_value(), macro->IsMethod());
  // Bind the this for methods. Methods that modify a struct-type "this" must
  // only be called if the this is in a variable, in which case the
  // LocalValue is non-const. Otherwise, the LocalValue used for the parameter
  // binding is const, and thus read-only, which will cause errors if
  // modified, e.g. when called by a struct method that sets the structs
  // fields. This prevents using temporary struct values for anything other
  // than read operations.
  if (this_reference) {
    DCHECK(macro->IsMethod());
    parameter_bindings.Add(kThisParameterName, LocalValue{*this_reference},
                           true);
    // TODO(v8:12261): Tracking 'this'-binding for kythe led to a few weird
    // issues. Review to fully support 'this' in methods.
  }
  size_t count = 0;
  for (const auto& arg : arguments) {
    if (this_reference && count == signature.implicit_count) count++;
    const bool mark_as_used = signature.implicit_count > count;
    const Identifier* name = macro->parameter_names()[count++];
    Binding<LocalValue>* binding =
        parameter_bindings.Add(name,
                               LocalValue{LocationReference::Temporary(
                                   arg, "parameter " + name->value)},
                               mark_as_used);
    if (GlobalContext::collect_kythe_data()) {
      KytheData::AddBindingDefinition(binding);
    }
  }
  DCHECK_EQ(label_blocks.size(), signature.labels.size());
  for (size_t i = 0; i < signature.labels.size(); ++i) {
    const LabelDeclaration& label_info = signature.labels[i];
    Binding<LocalLabel>* binding = label_bindings.Add(
        label_info.name, LocalLabel{label_blocks[i], label_info.types});
    if (GlobalContext::collect_kythe_data()) {
      KytheData::AddBindingDefinition(binding);
    }
  }
  Block* macro_end;
  std::optional<Binding<LocalLabel>> macro_end_binding;
  if (can_return) {
    Stack<const Type*> stack = assembler().CurrentStack();
    std::vector<const Type*> lowered_return_types = LowerType(return_type);
    stack.PushMany(lowered_return_types);
    if (!return_type->IsConstexpr()) {
      SetReturnValue(VisitResult(return_type,
                                 stack.TopRange(lowered_return_types.size())));
    }
    // The stack copy used to initialize the _macro_end block is only used
    // as a template for the actual gotos generated by return statements. It
    // doesn't correspond to any real return values, and thus shouldn't contain
    // top types, because these would pollute actual return value types that get
    // unioned with them for return statements, erroneously forcing them to top.
    for (auto i = stack.begin(); i != stack.end(); ++i) {
      if ((*i)->IsTopType()) {
        *i = TopType::cast(*i)->source_type();
      }
    }
    macro_end = assembler().NewBlock(std::move(stack));
    macro_end_binding.emplace(&LabelBindingsManager::Get(), kMacroEndLabelName,
                              LocalLabel{macro_end, {return_type}});
  } else {
    SetReturnValue(VisitResult::NeverResult());
  }
  const Type* result = Visit(*macro->body());
  if (result->IsNever()) {
    if (!return_type->IsNever() && !macro->HasReturns()) {
      std::stringstream s;
      s << "macro " << macro->ReadableName()
        << " that never returns must have return type never";
      ReportError(s.str());
    }
  } else {
    if (return_type->IsNever()) {
      std::stringstream s;
      s << "macro " << macro->ReadableName()
        << " has implicit return at end of its declartion but return type "
           "never";
      ReportError(s.str());
    } else if (!macro->signature().return_type->IsVoid()) {
      std::stringstream s;
      s << "macro " << macro->ReadableName()
        << " expects to return a value but doesn't on all paths";
      ReportError(s.str());
    }
  }
  if (!result->IsNever()) {
    assembler().Goto(macro_end);
  }
  if (macro->HasReturns() || !result->IsNever()) {
    assembler().Bind(macro_end);
  }
  return GetAndClearReturnValue();
}
References v8::internal::torque::BlockBindings< T >::Add(), v8::internal::torque::KytheData::AddBindingDefinition(), v8::internal::torque::Callable::body(), v8::internal::torque::GlobalContext::collect_kythe_data(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::Get(), v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::Callable::HasReturns(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::Signature::implicit_count, v8::internal::torque::Type::IsConstexpr(), v8::internal::torque::Declarable::IsMethod(), v8::internal::torque::Type::IsNever(), v8::internal::torque::Type::IsVoid(), v8::internal::torque::kMacroEndLabelName, v8::internal::torque::kThisParameterName, v8::internal::torque::Signature::labels, v8::internal::torque::LowerType(), v8::internal::name, v8::internal::torque::LabelDeclaration::name, v8::internal::torque::VisitResult::NeverResult(), v8::internal::torque::Callable::parameter_names(), v8::internal::torque::Signature::parameter_names, v8::internal::torque::Callable::ReadableName(), v8::internal::torque::ReportError(), v8::base::internal::result, v8::internal::torque::Signature::return_type, v8::debug::SetReturnValue(), v8::internal::torque::Callable::signature(), v8::internal::stack, and v8::internal::torque::LocationReference::Temporary().
LabelsFromIdentifiers()
std::vector< Binding< LocalLabel > * > v8::internal::torque::ImplementationVisitor::LabelsFromIdentifiers (const std::vector< Identifier * > & names) [private]
Definition at line 3423 of file implementation-visitor.cc.
                                         {
  std::vector<Binding<LocalLabel>*> result;
  result.reserve(names.size());
  for (const auto& name : names) {
    Binding<LocalLabel>* label = LookupLabel(name->value);
    result.push_back(label);
    // Link up labels in "otherwise" part of the call expression with
    // either the label in the signature of the calling macro or the label
    // block ofa surrounding "try".
    if (GlobalContext::collect_language_server_data()) {
      LanguageServerData::AddDefinition(name->pos,
                                        label->declaration_position());
    }
    // TODO(v8:12261): Might have to track KytheData here.
  }
  return result;
}
References v8::internal::torque::Binding< T >::declaration_position(), v8::internal::name, and v8::base::internal::result.
LookupCallable() [1/2]
template<class Container >
Callable * v8::internal::torque::ImplementationVisitor::LookupCallable (const QualifiedName & name, const Container & declaration_container, const Arguments & arguments, const TypeVector & specialization_types) [private]
Definition at line 2181 of file implementation-visitor.cc.
                                                                        {
  return LookupCallable(name, declaration_container,
                        arguments.parameters.ComputeTypeVector(),
                        arguments.labels, specialization_types);
}
References v8::internal::torque::VisitResultVector::ComputeTypeVector(), v8::internal::torque::Arguments::labels, LookupCallable(), v8::internal::name, and v8::internal::torque::Arguments::parameters.
LookupCallable() [2/2]
template<class Container >
Callable * v8::internal::torque::ImplementationVisitor::LookupCallable (const QualifiedName & name, const Container & declaration_container, const TypeVector & types, const std::vector< Binding< LocalLabel > * > & labels, const TypeVector & specialization_types, bool silence_errors = false) [private]
Definition at line 2082 of file implementation-visitor.cc.
                                                                 {
  Callable* result = nullptr;
  std::vector<Declarable*> overloads;
  std::vector<Signature> overload_signatures;
  std::vector<std::pair<GenericCallable*, std::string>> inapplicable_generics;
  for (auto* declarable : declaration_container) {
    if (GenericCallable* generic = GenericCallable::DynamicCast(declarable)) {
      TypeArgumentInference inference = InferSpecializationTypes(
          generic, specialization_types, parameter_types);
      if (inference.HasFailed()) {
        inapplicable_generics.push_back(
            std::make_pair(generic, inference.GetFailureReason()));
        continue;
      }
      overloads.push_back(generic);
      overload_signatures.push_back(
          DeclarationVisitor::MakeSpecializedSignature(
              SpecializationKey<GenericCallable>{generic,
                                                 inference.GetResult()}));
    } else if (Callable* callable = Callable::DynamicCast(declarable)) {
      overloads.push_back(callable);
      overload_signatures.push_back(callable->signature());
    }
  }
  // Indices of candidates in overloads/overload_signatures.
  std::vector<size_t> candidates;
  for (size_t i = 0; i < overloads.size(); ++i) {
    const Signature& signature = overload_signatures[i];
    if (IsCompatibleSignature(signature, parameter_types, labels.size())) {
      candidates.push_back(i);
    }
  }
  if (overloads.empty() && inapplicable_generics.empty()) {
    if (silence_errors) return nullptr;
    std::stringstream stream;
    stream << "no matching declaration found for " << name;
    ReportError(stream.str());
  } else if (candidates.empty()) {
    if (silence_errors) return nullptr;
    FailCallableLookup("cannot find suitable callable with name", name,
                       parameter_types, labels, overload_signatures,
                       inapplicable_generics);
  }
  auto is_better_candidate = [&](size_t a, size_t b) {
    return ParameterDifference(overload_signatures[a].GetExplicitTypes(),
                               parameter_types)
        .StrictlyBetterThan(ParameterDifference(
            overload_signatures[b].GetExplicitTypes(), parameter_types));
  };
  size_t best = *std::min_element(candidates.begin(), candidates.end(),
                                  is_better_candidate);
  // This check is contained in libstdc++'s std::min_element.
  DCHECK(!is_better_candidate(best, best));
  for (size_t candidate : candidates) {
    if (candidate != best && !is_better_candidate(best, candidate)) {
      std::vector<Signature> candidate_signatures;
      candidate_signatures.reserve(candidates.size());
      for (size_t i : candidates) {
        candidate_signatures.push_back(overload_signatures[i]);
      }
      FailCallableLookup("ambiguous callable ", name, parameter_types, labels,
                         candidate_signatures, inapplicable_generics);
    }
  }
  if (GenericCallable* generic =
          GenericCallable::DynamicCast(overloads[best])) {
    TypeArgumentInference inference = InferSpecializationTypes(
        generic, specialization_types, parameter_types);
    result = GetOrCreateSpecialization(
        SpecializationKey<GenericCallable>{generic, inference.GetResult()});
  } else {
    result = Callable::cast(overloads[best]);
  }
  size_t caller_size = parameter_types.size();
  size_t callee_size =
      result->signature().types().size() - result->signature().implicit_count;
  if (caller_size != callee_size &&
      !result->signature().parameter_types.var_args) {
    std::stringstream stream;
    stream << "parameter count mismatch calling " << *result << " - expected "
           << std::to_string(callee_size) << ", found "
           << std::to_string(caller_size);
    ReportError(stream.str());
  }
  return result;
}
References v8::internal::DCHECK(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FailCallableLookup(), v8::internal::torque::TypeArgumentInference::GetFailureReason(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::GetOrCreateSpecialization(), v8::internal::torque::TypeArgumentInference::GetResult(), v8::internal::torque::TypeArgumentInference::HasFailed(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, InferSpecializationTypes(), v8::internal::torque::IsCompatibleSignature(), v8::internal::torque::DeclarationVisitor::MakeSpecializedSignature(), v8::internal::name, v8::internal::torque::ReportError(), v8::base::internal::result, and v8::internal::torque::ParameterDifference::StrictlyBetterThan().
Referenced by LookupCallable(), LookupMethod(), and TestLookupCallable().
LookupLabel()
Binding< LocalLabel > * v8::internal::torque::ImplementationVisitor::LookupLabel (const std::string & name) [private]
Definition at line 2036 of file implementation-visitor.cc.
                           {
  std::optional<Binding<LocalLabel>*> label = TryLookupLabel(name);
  if (!label) ReportError("cannot find label ", name);
  return *label;
}
References v8::internal::name, v8::internal::torque::ReportError(), and TryLookupLabel().
Referenced by LookupSimpleLabel().
LookupLocalValue()
LocationReference v8::internal::torque::ImplementationVisitor::LookupLocalValue (const std::string & name)
LookupMethod()
Method * v8::internal::torque::ImplementationVisitor::LookupMethod (const std::string & name, const AggregateType * receiver_type, const Arguments & arguments, const TypeVector & specialization_types) [private]
Definition at line 2189 of file implementation-visitor.cc.
                                                                        {
  TypeVector types(arguments.parameters.ComputeTypeVector());
  types.insert(types.begin(), receiver_type);
  return Method::cast(LookupCallable({{}, name}, receiver_type->Methods(name),
                                     types, arguments.labels,
                                     specialization_types));
}
References v8::internal::torque::VisitResultVector::ComputeTypeVector(), v8::internal::torque::Arguments::labels, LookupCallable(), v8::internal::torque::AggregateType::Methods(), v8::internal::name, and v8::internal::torque::Arguments::parameters.
Referenced by GenerateReferenceToItemInHeapSlice().
LookupSimpleLabel()
Block * v8::internal::torque::ImplementationVisitor::LookupSimpleLabel (const std::string & name) [private]
Definition at line 2043 of file implementation-visitor.cc.
                                                                     {
  LocalLabel* label = LookupLabel(name);
  if (!label->parameter_types.empty()) {
    ReportError("label ", name,
                "was expected to have no parameters, but has parameters (",
                label->parameter_types, ")");
  }
  return label->block;
}
References v8::internal::torque::LocalLabel::block, LookupLabel(), v8::internal::name, v8::internal::torque::LocalLabel::parameter_types, and v8::internal::torque::ReportError().
LowerLabelParameter()
void v8::internal::torque::ImplementationVisitor::LowerLabelParameter (const Type * type, const std::string & parameter_name, std::vector< std::string > * lowered_parameters) [private]
Definition at line 3461 of file implementation-visitor.cc.
                                              {
  if (std::optional<const StructType*> struct_type = type->StructSupertype()) {
    for (auto& field : (*struct_type)->fields()) {
      LowerLabelParameter(
          field.name_and_type.type,
          "&((*" + parameter_name + ")." + field.name_and_type.name + ")",
          lowered_parameters);
    }
  } else {
    lowered_parameters->push_back(parameter_name);
  }
}
References v8::internal::tracing::type.
LowerParameter()
StackRange v8::internal::torque::ImplementationVisitor::LowerParameter (const Type * type, const std::string & parameter_name, Stack< std::string > * lowered_parameters) [private]
Definition at line 3443 of file implementation-visitor.cc.
                                          {
  if (std::optional<const StructType*> struct_type = type->StructSupertype()) {
    StackRange range = lowered_parameters->TopRange(0);
    for (auto& field : (*struct_type)->fields()) {
      StackRange parameter_range = LowerParameter(
          field.name_and_type.type,
          parameter_name + "." + field.name_and_type.name, lowered_parameters);
      range.Extend(parameter_range);
    }
    return range;
  } else {
    lowered_parameters->Push(parameter_name);
    return lowered_parameters->TopRange(1);
  }
}
References v8::internal::torque::StackRange::Extend(), v8::internal::torque::Stack< T >::Push(), v8::internal::torque::Stack< T >::TopRange(), and v8::internal::tracing::type.
PropagateBitfieldMark()
void v8::internal::torque::ImplementationVisitor::PropagateBitfieldMark (const Expression * original, const Expression * derived) [inline], [private]
Definition at line 855 of file implementation-visitor.h.
                                                        {
    if (const Identifier* source =
            TryGetSourceForBitfieldExpression(original)) {
      bitfield_expressions_[derived] = source;
    }
  }
References bitfield_expressions_, and TryGetSourceForBitfieldExpression().
SetDryRun()
void v8::internal::torque::ImplementationVisitor::SetDryRun (bool is_dry_run) [inline]
Definition at line 612 of file implementation-visitor.h.
{ is_dry_run_ = is_dry_run; }
References is_dry_run_.
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
SetReturnValue()
void v8::internal::torque::ImplementationVisitor::SetReturnValue (VisitResult return_value) [inline], [private]
Definition at line 830 of file implementation-visitor.h.
                                                {
    std::optional<VisitResult>& current_return_value =
        CurrentReturnValue::Get();
    DCHECK_IMPLIES(current_return_value, *current_return_value == return_value);
    current_return_value = std::move(return_value);
  }
References DCHECK_IMPLIES, and v8::internal::compiler::turboshaft::Get().
TestLookupCallable()
bool v8::internal::torque::ImplementationVisitor::TestLookupCallable (const QualifiedName & name, const TypeVector & parameter_types) [private]
Definition at line 2056 of file implementation-visitor.cc.
                                                                  {
  return LookupCallable(name, Declarations::TryLookup(name), parameter_types,
                        {}, {}, true) != nullptr;
}
References LookupCallable(), v8::internal::name, and v8::internal::torque::Declarations::TryLookup().
Referenced by GenerateFieldAccess().
TryGetSourceForBitfieldExpression()
const Identifier* v8::internal::torque::ImplementationVisitor::TryGetSourceForBitfieldExpression (const Expression * expr) const [inline], [private]
Definition at line 848 of file implementation-visitor.h.
                                    {
    auto it = bitfield_expressions_.find(expr);
    if (it == bitfield_expressions_.end()) return nullptr;
    return it->second;
  }
References bitfield_expressions_.
Referenced by PropagateBitfieldMark().
TryLookupLabel()
std::optional< Binding< LocalLabel > * > v8::internal::torque::ImplementationVisitor::TryLookupLabel (const std::string & name) [private]
Definition at line 2031 of file implementation-visitor.cc.
                           {
  return LabelBindingsManager::Get().TryLookup(name);
}
References v8::internal::compiler::turboshaft::Get(), and v8::internal::name.
Referenced by LookupLabel(), and Visit().
TryLookupLocalValue()
std::optional< Binding< LocalValue > * > v8::internal::torque::ImplementationVisitor::TryLookupLocalValue (const std::string & name) [private]
Definition at line 2026 of file implementation-visitor.cc.
                           {
  return ValueBindingsManager::Get().TryLookup(name);
}
References v8::internal::compiler::turboshaft::Get(), and v8::internal::name.
Referenced by GetLocationReference(), and InferSpecializationTypes().
Visit() [1/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (AssertStatement * stmt)
Definition at line 1265 of file implementation-visitor.cc.
                                                              {
  if (stmt->kind == AssertStatement::AssertKind::kStaticAssert) {
    std::string message =
        "static_assert(" + stmt->source + ") at " + ToString(stmt->pos);
    GenerateCall(QualifiedName({"", TORQUE_INTERNAL_NAMESPACE_STRING},
                               STATIC_ASSERT_MACRO_STRING),
                 Arguments{{Visit(stmt->expression),
                            VisitResult(TypeOracle::GetConstexprStringType(),
                                        StringLiteralQuote(message))},
                           {}});
    return TypeOracle::GetVoidType();
  }
  // When the sandbox is off, sbxchecks become dchecks.
  DCHECK_IMPLIES(stmt->kind == AssertStatement::AssertKind::kSbxCheck,
                 V8_ENABLE_SANDBOX_BOOL);
  bool do_check = stmt->kind != AssertStatement::AssertKind::kDcheck ||
                  GlobalContext::force_assert_statements();
#if defined(DEBUG)
  do_check = true;
#endif
  Block* resume_block;
  if (!do_check) {
    Block* unreachable_block = assembler().NewBlock(assembler().CurrentStack());
    resume_block = assembler().NewBlock(assembler().CurrentStack());
    assembler().Goto(resume_block);
    assembler().Bind(unreachable_block);
  }
  // CSA_DCHECK & co. are not used here on purpose for two reasons. First,
  // Torque allows and handles two types of expressions in the if protocol
  // automagically, ones that return TNode<BoolT> and those that use the
  // BranchIf(..., Label* true, Label* false) idiom. Because the machinery to
  // handle this is embedded in the expression handling and to it's not
  // possible to make the decision to use CSA_DCHECK or CSA_DCHECK_BRANCH
  // isn't trivial up-front. Secondly, on failure, the assert text should be
  // the corresponding Torque code, not the -gen.cc code, which would be the
  // case when using CSA_DCHECK_XXX.
  Block* true_block = assembler().NewBlock(assembler().CurrentStack());
  Block* false_block = assembler().NewBlock(assembler().CurrentStack(), true);
  GenerateExpressionBranch(stmt->expression, true_block, false_block);
  assembler().Bind(false_block);
  assembler().Emit(AbortInstruction{
      AbortInstruction::Kind::kAssertionFailure,
      "Torque assert '" + FormatAssertSource(stmt->source) + "' failed"});
  assembler().Bind(true_block);
  if (!do_check) {
    assembler().Bind(resume_block);
  }
  return TypeOracle::GetVoidType();
}
References DCHECK_IMPLIES, v8::internal::torque::AssertStatement::expression, v8::internal::torque::GlobalContext::force_assert_statements(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FormatAssertSource(), v8::internal::torque::TypeOracle::GetConstexprStringType(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::torque::AbortInstruction::kAssertionFailure, v8::internal::torque::AssertStatement::kDcheck, v8::internal::torque::AssertStatement::kind, v8::internal::torque::AssertStatement::kSbxCheck, v8::internal::torque::AssertStatement::kStaticAssert, v8::internal::torque::AstNode::pos, v8::internal::torque::AssertStatement::source, v8::internal::torque::STATIC_ASSERT_MACRO_STRING, v8::internal::string, v8::internal::torque::StringLiteralQuote(), v8::internal::torque::TORQUE_INTERNAL_NAMESPACE_STRING, v8::internal::torque::ToString(), and V8_ENABLE_SANDBOX_BOOL.
Visit() [2/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (AssignmentExpression * expr)
Definition at line 978 of file implementation-visitor.cc.
                                                                   {
  StackScope scope(this);
  LocationReference location_ref = GetLocationReference(expr->location);
  VisitResult assignment_value;
  if (expr->op) {
    VisitResult location_value = GenerateFetchFromLocation(location_ref);
    assignment_value = Visit(expr->value);
    Arguments args;
    args.parameters = {location_value, assignment_value};
    assignment_value = GenerateCall(*expr->op, args);
    GenerateAssignToLocation(location_ref, assignment_value);
  } else {
    assignment_value = Visit(expr->value);
    GenerateAssignToLocation(location_ref, assignment_value);
  }
  return scope.Yield(assignment_value);
}
References v8::base::args, v8::internal::torque::AssignmentExpression::location, v8::internal::torque::AssignmentExpression::op, v8::internal::torque::AssignmentExpression::value, and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [3/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (AssumeTypeImpossibleExpression * expr)
Definition at line 1013 of file implementation-visitor.cc.
                                                                             {
  VisitResult result = Visit(expr->expression);
  const Type* result_type = SubtractType(
      result.type(), TypeVisitor::ComputeType(expr->excluded_type));
  if (result_type->IsNever()) {
    ReportError("unreachable code");
  }
  CHECK_EQ(LowerType(result_type), TypeVector{result_type});
  assembler().Emit(UnsafeCastInstruction{result_type});
  result.SetType(result_type);
  return result;
}
References CHECK_EQ, v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::AssumeTypeImpossibleExpression::excluded_type, v8::internal::torque::AssumeTypeImpossibleExpression::expression, v8::internal::torque::Type::IsNever(), v8::internal::torque::LowerType(), v8::internal::torque::ReportError(), v8::base::internal::result, and v8::internal::torque::SubtractType().
Visit() [4/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (BlockStatement * block)
Definition at line 1204 of file implementation-visitor.cc.
                                                              {
  BlockBindings<LocalValue> block_bindings(&ValueBindingsManager::Get());
  const Type* type = TypeOracle::GetVoidType();
  for (Statement* s : block->statements) {
    CurrentSourcePosition::Scope source_position(s->pos);
    if (type->IsNever()) {
      ReportError("statement after non-returning statement");
    }
    if (auto* var_declaration = VarDeclarationStatement::DynamicCast(s)) {
      type = Visit(var_declaration, &block_bindings);
    } else {
      type = Visit(s);
    }
  }
  return type;
}
References v8::internal::compiler::turboshaft::Get(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::torque::AstNode::pos, v8::internal::torque::ReportError(), v8::internal::torque::BlockStatement::statements, and v8::internal::tracing::type.
Visit() [5/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (BreakStatement * stmt)
Definition at line 1761 of file implementation-visitor.cc.
                                                             {
  std::optional<Binding<LocalLabel>*> break_label =
      TryLookupLabel(kBreakLabelName);
  if (!break_label) {
    ReportError("break used outside of loop");
  }
  assembler().Goto((*break_label)->block);
  return TypeOracle::GetNeverType();
}
References assembler(), v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::CfgAssembler::Goto(), v8::internal::torque::kBreakLabelName, v8::internal::torque::ReportError(), and TryLookupLabel().
Visit() [6/42]
void v8::internal::torque::ImplementationVisitor::Visit (Builtin * builtin)
Definition at line 593 of file implementation-visitor.cc.
                                                  {
  if (builtin->IsExternal()) return;
  CurrentScope::Scope current_scope(builtin);
  CurrentCallable::Scope current_callable(builtin);
  CurrentReturnValue::Scope current_return_value;
  const std::string& name = builtin->ExternalName();
  const Signature& signature = builtin->signature();
  csa_ccfile() << "TF_BUILTIN(" << name << ", CodeStubAssembler) {\n"
               << " compiler::CodeAssemblerState* state_ = state();"
               << " compiler::CodeAssembler ca_(state());\n";
  Stack<const Type*> parameter_types;
  Stack<std::string> parameters;
  BindingsManagersScope bindings_managers_scope;
  BlockBindings<LocalValue> parameter_bindings(&ValueBindingsManager::Get());
  if (builtin->IsVarArgsJavaScript() || builtin->IsFixedArgsJavaScript()) {
    if (builtin->IsVarArgsJavaScript()) {
      DCHECK(signature.parameter_types.var_args);
      if (signature.ExplicitCount() > 0) {
        Error("Cannot mix explicit parameters with varargs.")
            .Position(signature.parameter_names[signature.implicit_count]->pos);
      }
      csa_ccfile() << " TNode<Word32T> argc = UncheckedParameter<Word32T>("
                   << "Descriptor::kJSActualArgumentsCount);\n";
      csa_ccfile() << " TNode<IntPtrT> "
                      "arguments_length(ChangeInt32ToIntPtr(UncheckedCast<"
                      "Int32T>(argc)));\n";
      csa_ccfile() << " TNode<RawPtrT> arguments_frame = "
                      "UncheckedCast<RawPtrT>(LoadFramePointer());\n";
      csa_ccfile()
          << " TorqueStructArguments "
             "torque_arguments(GetFrameArguments(arguments_frame, "
             "arguments_length, FrameArgumentsArgcType::kCountIncludesReceiver"
          << "));\n";
      csa_ccfile()
          << " CodeStubArguments arguments(this, torque_arguments);\n";
      parameters.Push("torque_arguments.frame");
      parameters.Push("torque_arguments.base");
      parameters.Push("torque_arguments.length");
      parameters.Push("torque_arguments.actual_count");
      const Type* arguments_type = TypeOracle::GetArgumentsType();
      StackRange range = parameter_types.PushMany(LowerType(arguments_type));
      parameter_bindings.Add(*signature.arguments_variable,
                             LocalValue{LocationReference::Temporary(
                                 VisitResult(arguments_type, range),
                                 "parameter " + *signature.arguments_variable)},
                             true);
    }
    for (size_t i = 0; i < signature.implicit_count; ++i) {
      const std::string& param_name = signature.parameter_names[i]->value;
      SourcePosition param_pos = signature.parameter_names[i]->pos;
      std::string generated_name = AddParameter(
          i, builtin, &parameters, &parameter_types, &parameter_bindings, true);
      const Type* actual_type = signature.parameter_types.types[i];
      std::vector<const Type*> expected_types;
      if (param_name == "context") {
        csa_ccfile() << " TNode<NativeContext> " << generated_name
                     << " = UncheckedParameter<NativeContext>("
                     << "Descriptor::kContext);\n";
        csa_ccfile() << " USE(" << generated_name << ");\n";
        expected_types = {TypeOracle::GetNativeContextType(),
                          TypeOracle::GetContextType()};
      } else if (param_name == "receiver") {
        csa_ccfile()
            << " TNode<JSAny> " << generated_name << " = "
            << (builtin->IsVarArgsJavaScript()
                    ? "arguments.GetReceiver()"
                    : "UncheckedParameter<JSAny>(Descriptor::kReceiver)")
            << ";\n";
        csa_ccfile() << " USE(" << generated_name << ");\n";
        expected_types = {TypeOracle::GetJSAnyType()};
      } else if (param_name == "newTarget") {
        csa_ccfile() << " TNode<JSAny> " << generated_name
                     << " = UncheckedParameter<JSAny>("
                     << "Descriptor::kJSNewTarget);\n";
        csa_ccfile() << " USE(" << generated_name << ");\n";
        expected_types = {TypeOracle::GetJSAnyType()};
      } else if (param_name == "target") {
        csa_ccfile() << " TNode<JSFunction> " << generated_name
                     << " = UncheckedParameter<JSFunction>("
                     << "Descriptor::kJSTarget);\n";
        csa_ccfile() << " USE(" << generated_name << ");\n";
        expected_types = {TypeOracle::GetJSFunctionType()};
      } else if (param_name == "dispatchHandle") {
        if (V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL) {
          csa_ccfile() << " TNode<JSDispatchHandleT> " << generated_name
                       << " = "
                          "UncheckedParameter<JSDispatchHandleT>(Descriptor::"
                          "kJSDispatchHandle);\n";
        } else if (V8_ENABLE_LEAPTIERING_BOOL) {
          csa_ccfile() << " TNode<JSDispatchHandleT> " << generated_name
                       << " = "
                          "ReinterpretCast<JSDispatchHandleT>("
                          "LoadJSFunctionDispatchHandle("
                          "UncheckedParameter<JSFunction>("
                       << "Descriptor::kJSTarget)));\n";
        } else {
          csa_ccfile() << " TNode<JSDispatchHandleT> " << generated_name
                       << " = InvalidDispatchHandleConstant();\n";
        }
        csa_ccfile() << " USE(" << generated_name << ");\n";
        expected_types = {TypeOracle::GetDispatchHandleType()};
      } else {
        Error(
            "Unexpected implicit parameter \"", param_name,
            "\" for JavaScript calling convention, "
            "expected \"context\", \"receiver\", \"target\", or \"newTarget\"")
            .Position(param_pos);
        expected_types = {actual_type};
      }
      if (std::find(expected_types.begin(), expected_types.end(),
                    actual_type) == expected_types.end()) {
        Error("According to JavaScript calling convention, expected parameter ",
              param_name, " to have type ", PrintList(expected_types, " or "),
              " but found type ", *actual_type)
            .Position(param_pos);
      }
    }
    for (size_t i = signature.implicit_count;
         i < signature.parameter_names.size(); ++i) {
      const std::string& parameter_name = signature.parameter_names[i]->value;
      const Type* type = signature.types()[i];
      const bool mark_as_used = signature.implicit_count > i;
      std::string var = AddParameter(i, builtin, &parameters, &parameter_types,
                                     &parameter_bindings, mark_as_used);
      csa_ccfile() << " " << type->GetGeneratedTypeName() << " " << var
                   << " = "
                   << "UncheckedParameter<" << type->GetGeneratedTNodeTypeName()
                   << ">(Descriptor::k" << CamelifyString(parameter_name)
                   << ");\n";
      csa_ccfile() << " USE(" << var << ");\n";
    }
  } else {
    DCHECK(builtin->IsStub());
    for (size_t i = 0; i < signature.parameter_names.size(); ++i) {
      const std::string& parameter_name = signature.parameter_names[i]->value;
      const Type* type = signature.types()[i];
      const bool mark_as_used = signature.implicit_count > i;
      std::string var = AddParameter(i, builtin, &parameters, &parameter_types,
                                     &parameter_bindings, mark_as_used);
      csa_ccfile() << " " << type->GetGeneratedTypeName() << " " << var
                   << " = "
                   << "UncheckedParameter<" << type->GetGeneratedTNodeTypeName()
                   << ">(Descriptor::k" << CamelifyString(parameter_name)
                   << ");\n";
      csa_ccfile() << " USE(" << var << ");\n";
    }
  }
  if (builtin->use_counter_name()) {
    DCHECK(!signature.parameter_types.types.empty());
    DCHECK(signature.parameter_types.types[0] ==
               TypeOracle::GetNativeContextType() ||
           signature.parameter_types.types[0] == TypeOracle::GetContextType());
    csa_ccfile() << " CodeStubAssembler(state_).CallRuntime("
                 << "Runtime::kIncrementUseCounter, parameter0, "
                 << "CodeStubAssembler(state_).SmiConstant("
                 << *builtin->use_counter_name() << "));\n";
  }
  assembler_ = CfgAssembler(parameter_types);
  const Type* body_result = Visit(*builtin->body());
  if (body_result != TypeOracle::GetNeverType()) {
    ReportError("control reaches end of builtin, expected return of a value");
  }
  CSAGenerator csa_generator{assembler().Result(), csa_ccfile(),
                             builtin->kind()};
  csa_generator.EmitGraph(parameters);
  assembler_ = std::nullopt;
  csa_ccfile() << "}\n\n";
}
References v8::internal::torque::BlockBindings< T >::Add(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::AddParameter(), v8::internal::torque::Signature::arguments_variable, v8::internal::torque::Callable::body(), v8::internal::torque::CamelifyString(), v8::internal::DCHECK(), v8::internal::torque::Error(), v8::internal::torque::Signature::ExplicitCount(), v8::internal::torque::Callable::ExternalName(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::TypeOracle::GetArgumentsType(), v8::internal::torque::TypeOracle::GetContextType(), v8::internal::torque::TypeOracle::GetDispatchHandleType(), v8::internal::torque::TypeOracle::GetJSAnyType(), v8::internal::torque::TypeOracle::GetJSFunctionType(), v8::internal::torque::TypeOracle::GetNativeContextType(), v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::Signature::implicit_count, v8::internal::torque::Callable::IsExternal(), v8::internal::torque::Builtin::IsFixedArgsJavaScript(), v8::internal::torque::Builtin::IsStub(), v8::internal::torque::Builtin::IsVarArgsJavaScript(), v8::internal::torque::Builtin::kind(), v8::internal::torque::LowerType(), v8::internal::name, v8::internal::torque::Signature::parameter_names, v8::internal::torque::Signature::parameter_types, v8::internal::torque::MessageBuilder::Position(), v8::internal::torque::PrintList(), v8::internal::torque::Stack< T >::Push(), v8::internal::torque::Stack< T >::PushMany(), v8::internal::torque::ReportError(), v8::internal::torque::Callable::signature(), v8::internal::string, v8::internal::tracing::type, v8::internal::torque::ParameterTypes::types, v8::internal::torque::Signature::types(), v8::internal::torque::Builtin::use_counter_name(), V8_ENABLE_LEAPTIERING_BOOL, V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE_BOOL, and v8::internal::torque::ParameterTypes::var_args.
Visit() [7/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (CallExpression * expr, bool is_tail = false)
Definition at line 3262 of file implementation-visitor.cc.
                                                           {
  StackScope scope(this);
  if (expr->callee->name->value == "&" && expr->arguments.size() == 1) {
    if (auto* loc_expr = LocationExpression::DynamicCast(expr->arguments[0])) {
      LocationReference ref = GetLocationReference(loc_expr);
      if (ref.IsHeapReference()) return scope.Yield(ref.heap_reference());
      if (ref.IsHeapSlice()) return scope.Yield(ref.heap_slice());
    }
    ReportError("Unable to create a heap reference.");
  }
  Arguments arguments;
  QualifiedName name = QualifiedName(expr->callee->namespace_qualification,
                                     expr->callee->name->value);
  TypeVector specialization_types =
      TypeVisitor::ComputeTypeVector(expr->callee->generic_arguments);
  bool has_template_arguments = !specialization_types.empty();
  for (Expression* arg : expr->arguments)
    arguments.parameters.push_back(Visit(arg));
  arguments.labels = LabelsFromIdentifiers(expr->labels);
  if (!has_template_arguments && name.namespace_qualification.empty() &&
      TryLookupLocalValue(name.name)) {
    return scope.Yield(
        GeneratePointerCall(expr->callee, arguments, is_tailcall));
  } else {
    if (GlobalContext::collect_language_server_data()) {
      Callable* callable = LookupCallable(name, Declarations::Lookup(name),
                                          arguments, specialization_types);
      LanguageServerData::AddDefinition(expr->callee->name->pos,
                                        callable->IdentifierPosition());
    }
    if (GlobalContext::collect_kythe_data()) {
      Callable* callable = LookupCallable(name, Declarations::Lookup(name),
                                          arguments, specialization_types);
      Callable* caller = CurrentCallable::Get();
      KytheData::AddCall(caller, expr->callee->name->pos, callable);
    }
    if (expr->callee->name->value == "!" && arguments.parameters.size() == 1) {
      PropagateBitfieldMark(expr->arguments[0], expr);
    }
    if (expr->callee->name->value == "==" && arguments.parameters.size() == 2) {
      if (arguments.parameters[0].type()->IsConstexpr()) {
        PropagateBitfieldMark(expr->arguments[1], expr);
      } else if (arguments.parameters[1].type()->IsConstexpr()) {
        PropagateBitfieldMark(expr->arguments[0], expr);
      }
    }
    return scope.Yield(
        GenerateCall(name, arguments, specialization_types, is_tailcall));
  }
}
References v8::internal::torque::CallExpression::arguments, v8::internal::torque::CallExpression::callee, v8::internal::torque::IdentifierExpression::generic_arguments, v8::internal::compiler::turboshaft::Get(), v8::internal::torque::LocationReference::heap_reference(), v8::internal::torque::LocationReference::heap_slice(), v8::internal::torque::Declarable::IdentifierPosition(), v8::internal::torque::LocationReference::IsHeapReference(), v8::internal::torque::LocationReference::IsHeapSlice(), v8::internal::torque::CallExpression::labels, v8::internal::torque::Arguments::labels, v8::internal::name, v8::internal::torque::IdentifierExpression::name, v8::internal::torque::IdentifierExpression::namespace_qualification, v8::internal::torque::Arguments::parameters, v8::internal::torque::AstNode::pos, v8::internal::torque::ReportError(), v8::internal::torque::Identifier::value, and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [8/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (CallMethodExpression * expr)
Definition at line 3316 of file implementation-visitor.cc.
                                                                   {
  StackScope scope(this);
  Arguments arguments;
  std::string method_name = expr->method->name->value;
  TypeVector specialization_types =
      TypeVisitor::ComputeTypeVector(expr->method->generic_arguments);
  LocationReference target = GetLocationReference(expr->target);
  if (!target.IsVariableAccess()) {
    VisitResult result = GenerateFetchFromLocation(target);
    target = LocationReference::Temporary(result, "this parameter");
  }
  const AggregateType* target_type =
      (*target.ReferencedType())->AggregateSupertype().value_or(nullptr);
  if (!target_type) {
    ReportError("target of method call not a struct or class type");
  }
  for (Expression* arg : expr->arguments) {
    arguments.parameters.push_back(Visit(arg));
  }
  arguments.labels = LabelsFromIdentifiers(expr->labels);
  TypeVector argument_types = arguments.parameters.ComputeTypeVector();
  DCHECK_EQ(expr->method->namespace_qualification.size(), 0);
  QualifiedName qualified_name = QualifiedName(method_name);
  Callable* callable = LookupMethod(method_name, target_type, arguments, {});
  if (GlobalContext::collect_language_server_data()) {
    LanguageServerData::AddDefinition(expr->method->name->pos,
                                      callable->IdentifierPosition());
  }
  if (GlobalContext::collect_kythe_data()) {
    Callable* caller = CurrentCallable::Get();
    KytheData::AddCall(caller, expr->method->name->pos, callable);
  }
  return scope.Yield(GenerateCall(callable, target, arguments, {}, false));
}
References v8::internal::torque::CallMethodExpression::arguments, v8::internal::torque::VisitResultVector::ComputeTypeVector(), DCHECK_EQ, v8::internal::torque::IdentifierExpression::generic_arguments, v8::internal::compiler::turboshaft::Get(), v8::internal::torque::Declarable::IdentifierPosition(), v8::internal::torque::LocationReference::IsVariableAccess(), v8::internal::torque::CallMethodExpression::labels, v8::internal::torque::Arguments::labels, v8::internal::torque::CallMethodExpression::method, v8::internal::torque::IdentifierExpression::name, v8::internal::torque::IdentifierExpression::namespace_qualification, v8::internal::torque::Arguments::parameters, v8::internal::torque::AstNode::pos, v8::internal::torque::LocationReference::ReferencedType(), v8::internal::torque::ReportError(), v8::base::internal::result, v8::internal::string, v8::internal::torque::CallMethodExpression::target, v8::internal::torque::Identifier::value, and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [9/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (ConditionalExpression * expr)
Definition at line 834 of file implementation-visitor.cc.
                                                                    {
  Block* true_block = assembler().NewBlock(assembler().CurrentStack());
  Block* false_block = assembler().NewBlock(assembler().CurrentStack());
  Block* done_block = assembler().NewBlock();
  Block* true_conversion_block = assembler().NewBlock();
  GenerateExpressionBranch(expr->condition, true_block, false_block);
  VisitResult left;
  VisitResult right;
  {
    // The code for both paths of the conditional need to be generated first
    // before evaluating the conditional expression because the common type of
    // the result of both the true and false of the condition needs to be known
    // to convert both branches to a common type.
    assembler().Bind(true_block);
    StackScope left_scope(this);
    left = Visit(expr->if_true);
    assembler().Goto(true_conversion_block);
    const Type* common_type;
    {
      assembler().Bind(false_block);
      StackScope right_scope(this);
      right = Visit(expr->if_false);
      common_type = GetCommonType(left.type(), right.type());
      right = right_scope.Yield(GenerateImplicitConvert(common_type, right));
      assembler().Goto(done_block);
    }
    assembler().Bind(true_conversion_block);
    left = left_scope.Yield(GenerateImplicitConvert(common_type, left));
    assembler().Goto(done_block);
  }
  assembler().Bind(done_block);
  CHECK_EQ(left, right);
  return left;
}
References CHECK_EQ, v8::internal::torque::ConditionalExpression::condition, v8::internal::torque::ConditionalExpression::if_false, v8::internal::torque::ConditionalExpression::if_true, v8::internal::torque::VisitResult::type(), and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [10/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (ContinueStatement * stmt)
Definition at line 1771 of file implementation-visitor.cc.
                                                                {
  std::optional<Binding<LocalLabel>*> continue_label =
      TryLookupLabel(kContinueLabelName);
  if (!continue_label) {
    ReportError("continue used outside of loop");
  }
  assembler().Goto((*continue_label)->block);
  return TypeOracle::GetNeverType();
}
References assembler(), v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::CfgAssembler::Goto(), v8::internal::torque::kContinueLabelName, v8::internal::torque::ReportError(), and TryLookupLabel().
Visit() [11/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (DebugStatement * stmt)
Definition at line 1221 of file implementation-visitor.cc.
                                                             {
  std::string reason;
  const Type* return_type;
  AbortInstruction::Kind kind;
  switch (stmt->kind) {
    case DebugStatement::Kind::kUnreachable:
      // Use the same string as in C++ to simplify fuzzer pattern-matching.
      reason = base::kUnreachableCodeMessage;
      return_type = TypeOracle::GetNeverType();
      kind = AbortInstruction::Kind::kUnreachable;
      break;
    case DebugStatement::Kind::kDebug:
      reason = "debug break";
      return_type = TypeOracle::GetVoidType();
      kind = AbortInstruction::Kind::kDebugBreak;
      break;
  }
#if defined(DEBUG)
  assembler().Emit(PrintErrorInstruction{"halting because of " + reason +
                                         " at " + PositionAsString(stmt->pos)});
#endif
  assembler().Emit(AbortInstruction{kind});
  return return_type;
}
References v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::torque::DebugStatement::kDebug, v8::internal::torque::AbortInstruction::kDebugBreak, v8::internal::torque::DebugStatement::kind, v8::internal::torque::DebugStatement::kUnreachable, v8::internal::torque::AbortInstruction::kUnreachable, v8::base::kUnreachableCodeMessage, v8::internal::torque::AstNode::pos, v8::internal::torque::PositionAsString(), and v8::internal::string.
Visit() [12/42]
void v8::internal::torque::ImplementationVisitor::Visit (Declarable * delarable, std::optional< SourceId > file = {})
Definition at line 3583 of file implementation-visitor.cc.
                                                              {
  CurrentScope::Scope current_scope(declarable->ParentScope());
  CurrentSourcePosition::Scope current_source_position(declarable->Position());
  CurrentFileStreams::Scope current_file_streams(
      &GlobalContext::GeneratedPerFile(file ? *file
                                            : declarable->Position().source));
  if (Callable* callable = Callable::DynamicCast(declarable)) {
    if (!callable->ShouldGenerateExternalCode(output_type_))
      CurrentFileStreams::Get() = nullptr;
  }
  switch (declarable->kind()) {
    case Declarable::kExternMacro:
      return Visit(ExternMacro::cast(declarable));
    case Declarable::kTorqueMacro:
      return Visit(TorqueMacro::cast(declarable));
    case Declarable::kMethod:
      return Visit(Method::cast(declarable));
    case Declarable::kBuiltin:
      return Visit(Builtin::cast(declarable));
    case Declarable::kTypeAlias:
      return Visit(TypeAlias::cast(declarable));
    case Declarable::kNamespaceConstant:
      return Visit(NamespaceConstant::cast(declarable));
    case Declarable::kRuntimeFunction:
    case Declarable::kIntrinsic:
    case Declarable::kExternConstant:
    case Declarable::kNamespace:
    case Declarable::kGenericCallable:
    case Declarable::kGenericType:
      return;
  }
}
References file(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::Declarable::kind(), v8::internal::torque::ls::kMethod, v8::internal::torque::ls::kNamespace, v8::internal::torque::Declarable::ParentScope(), and v8::internal::torque::Declarable::Position().
Visit() [13/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (Expression * expr)
Definition at line 44 of file implementation-visitor.cc.
                                                         {
  CurrentSourcePosition::Scope scope(expr->pos);
  switch (expr->kind) {
#define ENUM_ITEM(name) \
  case AstNode::Kind::k##name: \
    return Visit(name::cast(expr));
    AST_EXPRESSION_NODE_KIND_LIST(ENUM_ITEM)
#undef ENUM_ITEM
    default:
      UNREACHABLE();
  }
}
References AST_EXPRESSION_NODE_KIND_LIST, ENUM_ITEM, v8::internal::torque::AstNode::kind, v8::internal::torque::AstNode::pos, and v8::internal::UNREACHABLE().
Referenced by GenerateArrayLength(), GetLocationReference(), and Visit().
Visit() [14/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (ExpressionStatement * stmt)
Definition at line 1322 of file implementation-visitor.cc.
                                                                  {
  const Type* type = Visit(stmt->expression).type();
  return type->IsNever() ? type : TypeOracle::GetVoidType();
}
References v8::internal::torque::ExpressionStatement::expression, v8::internal::torque::TypeOracle::GetVoidType(), and v8::internal::tracing::type.
Visit() [15/42]
void v8::internal::torque::ImplementationVisitor::Visit (ExternMacro * macro) [inline]
Definition at line 546 of file implementation-visitor.h.
{}
Visit() [16/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (FieldAccessExpression * expr)
Definition at line 1051 of file implementation-visitor.cc.
                                                                    {
  StackScope scope(this);
  LocationReference location = GetLocationReference(expr);
  if (location.IsBitFieldAccess()) {
    if (auto* identifier = IdentifierExpression::DynamicCast(expr->object)) {
      bitfield_expressions_[expr] = identifier->name;
    }
  }
  return scope.Yield(GenerateFetchFromLocation(location));
}
References v8::internal::torque::LocationReference::IsBitFieldAccess(), v8::internal::torque::FieldAccessExpression::object, and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [17/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (FloatingPointLiteralExpression * expr)
Definition at line 996 of file implementation-visitor.cc.
                                                                             {
  const Type* result_type = TypeOracle::GetConstFloat64Type();
  std::stringstream str;
  str << std::setprecision(std::numeric_limits<double>::digits10 + 1)
      << expr->value;
  return VisitResult{result_type, str.str()};
}
References v8::internal::torque::TypeOracle::GetConstFloat64Type(), and v8::internal::torque::FloatingPointLiteralExpression::value.
Visit() [18/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (ForLoopStatement * stmt)
Definition at line 1781 of file implementation-visitor.cc.
                                                               {
  BlockBindings<LocalValue> loop_bindings(&ValueBindingsManager::Get());
  if (stmt->var_declaration) Visit(*stmt->var_declaration, &loop_bindings);
  Block* body_block = assembler().NewBlock(assembler().CurrentStack());
  Block* exit_block = assembler().NewBlock(assembler().CurrentStack());
  Block* header_block = assembler().NewBlock();
  assembler().Goto(header_block);
  assembler().Bind(header_block);
  // The continue label is where "continue" statements jump to. If no action
  // expression is provided, we jump directly to the header.
  Block* continue_block = header_block;
  // The action label is only needed when an action expression was provided.
  Block* action_block = nullptr;
  if (stmt->action) {
    action_block = assembler().NewBlock();
    // The action expression needs to be executed on a continue.
    continue_block = action_block;
  }
  if (stmt->test) {
    GenerateExpressionBranch(*stmt->test, body_block, exit_block);
  } else {
    assembler().Goto(body_block);
  }
  assembler().Bind(body_block);
  {
    BreakContinueActivator activator(exit_block, continue_block);
    const Type* body_result = Visit(stmt->body);
    if (body_result != TypeOracle::GetNeverType()) {
      assembler().Goto(continue_block);
    }
  }
  if (stmt->action) {
    assembler().Bind(action_block);
    const Type* action_result = Visit(*stmt->action);
    if (action_result != TypeOracle::GetNeverType()) {
      assembler().Goto(header_block);
    }
  }
  assembler().Bind(exit_block);
  return TypeOracle::GetVoidType();
}
References v8::internal::torque::ForLoopStatement::action, assembler(), v8::internal::torque::CfgAssembler::Bind(), v8::internal::torque::ForLoopStatement::body, GenerateExpressionBranch(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::torque::CfgAssembler::Goto(), v8::internal::torque::CfgAssembler::NewBlock(), v8::internal::torque::ForLoopStatement::test, v8::internal::torque::ForLoopStatement::var_declaration, and Visit().
Visit() [19/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (GotoStatement * stmt)
Definition at line 1062 of file implementation-visitor.cc.
                                                            {
  Binding<LocalLabel>* label = LookupLabel(stmt->label->value);
  size_t parameter_count = label->parameter_types.size();
  if (stmt->arguments.size() != parameter_count) {
    ReportError("goto to label has incorrect number of parameters (expected ",
                parameter_count, " found ", stmt->arguments.size(), ")");
  }
  if (GlobalContext::collect_language_server_data()) {
    LanguageServerData::AddDefinition(stmt->label->pos,
                                      label->declaration_position());
  }
  if (GlobalContext::collect_kythe_data()) {
    KytheData::AddBindingUse(stmt->label->pos, label);
  }
  size_t i = 0;
  StackRange arguments = assembler().TopRange(0);
  for (Expression* e : stmt->arguments) {
    StackScope scope(this);
    VisitResult result = Visit(e);
    const Type* parameter_type = label->parameter_types[i++];
    result = GenerateImplicitConvert(parameter_type, result);
    arguments.Extend(scope.Yield(result).stack_range());
  }
  assembler().Goto(label->block, arguments.Size());
  return TypeOracle::GetNeverType();
}
References v8::internal::torque::KytheData::AddBindingUse(), v8::internal::torque::LanguageServerData::AddDefinition(), v8::internal::torque::GotoStatement::arguments, v8::internal::torque::GlobalContext::collect_kythe_data(), v8::internal::torque::GlobalContext::collect_language_server_data(), v8::internal::torque::Binding< T >::declaration_position(), v8::internal::torque::StackRange::Extend(), v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::GotoStatement::label, v8::internal::torque::AstNode::pos, v8::internal::torque::ReportError(), v8::base::internal::result, v8::internal::torque::StackRange::Size(), v8::internal::torque::VisitResult::stack_range(), v8::internal::torque::Identifier::value, and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [20/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (IfStatement * stmt)
Definition at line 1092 of file implementation-visitor.cc.
                                                          {
  bool has_else = stmt->if_false.has_value();
  if (stmt->is_constexpr) {
    VisitResult expression_result = Visit(stmt->condition);
    if (!(expression_result.type() == TypeOracle::GetConstexprBoolType())) {
      std::stringstream stream;
      stream << "expression should return type constexpr bool "
             << "but returns type " << *expression_result.type();
      ReportError(stream.str());
    }
    Block* true_block = assembler().NewBlock();
    Block* false_block = assembler().NewBlock();
    Block* done_block = assembler().NewBlock();
    assembler().Emit(ConstexprBranchInstruction{
        expression_result.constexpr_value(), true_block, false_block});
    assembler().Bind(true_block);
    const Type* left_result = Visit(stmt->if_true);
    if (left_result == TypeOracle::GetVoidType()) {
      assembler().Goto(done_block);
    }
    assembler().Bind(false_block);
    const Type* right_result = TypeOracle::GetVoidType();
    if (has_else) {
      right_result = Visit(*stmt->if_false);
    }
    if (right_result == TypeOracle::GetVoidType()) {
      assembler().Goto(done_block);
    }
    if (left_result->IsNever() != right_result->IsNever()) {
      std::stringstream stream;
      stream << "either both or neither branches in a constexpr if statement "
                "must reach their end at"
             << PositionAsString(stmt->pos);
      ReportError(stream.str());
    }
    if (left_result != TypeOracle::GetNeverType()) {
      assembler().Bind(done_block);
    }
    return left_result;
  } else {
    Block* true_block = assembler().NewBlock(assembler().CurrentStack(),
                                             IsDeferred(stmt->if_true));
    Block* false_block =
        assembler().NewBlock(assembler().CurrentStack(),
                             stmt->if_false && IsDeferred(*stmt->if_false));
    GenerateExpressionBranch(stmt->condition, true_block, false_block);
    Block* done_block;
    bool live = false;
    if (has_else) {
      done_block = assembler().NewBlock();
    } else {
      done_block = false_block;
      live = true;
    }
    assembler().Bind(true_block);
    {
      const Type* result = Visit(stmt->if_true);
      if (result == TypeOracle::GetVoidType()) {
        live = true;
        assembler().Goto(done_block);
      }
    }
    if (has_else) {
      assembler().Bind(false_block);
      const Type* result = Visit(*stmt->if_false);
      if (result == TypeOracle::GetVoidType()) {
        live = true;
        assembler().Goto(done_block);
      }
    }
    if (live) {
      assembler().Bind(done_block);
    }
    return live ? TypeOracle::GetVoidType() : TypeOracle::GetNeverType();
  }
}
References v8::internal::torque::IfStatement::condition, v8::internal::torque::VisitResult::constexpr_value(), v8::internal::torque::TypeOracle::GetConstexprBoolType(), v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::torque::IfStatement::if_false, v8::internal::torque::IfStatement::if_true, v8::internal::torque::IfStatement::is_constexpr, v8::internal::torque::IsDeferred(), v8::internal::torque::Type::IsNever(), v8::internal::torque::AstNode::pos, v8::internal::torque::PositionAsString(), v8::internal::torque::ReportError(), v8::base::internal::result, and v8::internal::torque::VisitResult::type().
Visit() [21/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (IncrementDecrementExpression * expr)
Definition at line 965 of file implementation-visitor.cc.
                                                                           {
  StackScope scope(this);
  LocationReference location_ref = GetLocationReference(expr->location);
  VisitResult current_value = GenerateFetchFromLocation(location_ref);
  VisitResult one = {TypeOracle::GetConstInt31Type(), "1"};
  Arguments args;
  args.parameters = {current_value, one};
  VisitResult assignment_value = GenerateCall(
      expr->op == IncrementDecrementOperator::kIncrement ? "+" : "-", args);
  GenerateAssignToLocation(location_ref, assignment_value);
  return scope.Yield(expr->postfix ? current_value : assignment_value);
}
References v8::base::args, v8::internal::torque::TypeOracle::GetConstInt31Type(), v8::internal::torque::kIncrement, v8::internal::torque::IncrementDecrementExpression::location, one, v8::internal::torque::IncrementDecrementExpression::op, v8::internal::torque::IncrementDecrementExpression::postfix, and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [22/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (IntegerLiteralExpression * expr)
Definition at line 1004 of file implementation-visitor.cc.
                                                                       {
  const Type* result_type = TypeOracle::GetIntegerLiteralType();
  std::stringstream str;
  str << "IntegerLiteral("
      << (expr->value.is_negative() ? "true, 0x" : "false, 0x") << std::hex
      << expr->value.absolute_value() << std::dec << "ull)";
  return VisitResult{result_type, str.str()};
}
References v8::internal::IntegerLiteral::absolute_value(), v8::internal::torque::TypeOracle::GetIntegerLiteralType(), v8::internal::IntegerLiteral::is_negative(), and v8::internal::torque::IntegerLiteralExpression::value.
Visit() [23/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (IntrinsicCallExpression * intrinsic)
Definition at line 3351 of file implementation-visitor.cc.
                                                                      {
  StackScope scope(this);
  Arguments arguments;
  TypeVector specialization_types =
      TypeVisitor::ComputeTypeVector(expr->generic_arguments);
  for (Expression* arg : expr->arguments)
    arguments.parameters.push_back(Visit(arg));
  return scope.Yield(
      GenerateCall(expr->name->value, arguments, specialization_types, false));
}
References v8::internal::torque::IntrinsicCallExpression::arguments, v8::internal::torque::IntrinsicCallExpression::generic_arguments, v8::internal::torque::IntrinsicCallExpression::name, v8::internal::torque::Arguments::parameters, v8::internal::torque::Identifier::value, and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [24/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (LocationExpression * expr)
Definition at line 1046 of file implementation-visitor.cc.
                                                                 {
  StackScope scope(this);
  return scope.Yield(GenerateFetchFromLocation(GetLocationReference(expr)));
}
References v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [25/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (LogicalAndExpression * expr)
Definition at line 915 of file implementation-visitor.cc.
                                                                   {
  StackScope outer_scope(this);
  VisitResult left_result = Visit(expr->left);
  if (left_result.type()->IsConstexprBool()) {
    VisitResult right_result = Visit(expr->right);
    if (!right_result.type()->IsConstexprBool()) {
      ReportError(
          "expected type constexpr bool on right-hand side of operator "
          "&&");
    }
    return VisitResult(TypeOracle::GetConstexprBoolType(),
                       std::string("(") + left_result.constexpr_value() +
                           " && " + right_result.constexpr_value() + ")");
  }
  Block* true_block = assembler().NewBlock();
  Block* false_block = assembler().NewBlock();
  Block* done_block = assembler().NewBlock();
  left_result = GenerateImplicitConvert(TypeOracle::GetBoolType(), left_result);
  GenerateBranch(left_result, true_block, false_block);
  assembler().Bind(true_block);
  VisitResult true_result;
  {
    StackScope true_block_scope(this);
    VisitResult right_result = Visit(expr->right);
    if (TryGetSourceForBitfieldExpression(expr->left) != nullptr &&
        TryGetSourceForBitfieldExpression(expr->right) != nullptr &&
        TryGetSourceForBitfieldExpression(expr->left)->value ==
            TryGetSourceForBitfieldExpression(expr->right)->value) {
      Lint(
          "Please use & rather than && when checking multiple bitfield "
          "values, to avoid complexity in generated code.");
    }
    true_result = true_block_scope.Yield(
        GenerateImplicitConvert(TypeOracle::GetBoolType(), right_result));
  }
  assembler().Goto(done_block);
  assembler().Bind(false_block);
  VisitResult false_result = GenerateBoolConstant(false);
  assembler().Goto(done_block);
  assembler().Bind(done_block);
  DCHECK_EQ(true_result, false_result);
  return outer_scope.Yield(true_result);
}
References v8::internal::torque::VisitResult::constexpr_value(), DCHECK_EQ, v8::internal::torque::TypeOracle::GetBoolType(), v8::internal::torque::TypeOracle::GetConstexprBoolType(), v8::internal::torque::Type::IsConstexprBool(), v8::internal::torque::LogicalAndExpression::left, v8::internal::torque::Lint(), v8::internal::torque::ReportError(), v8::internal::torque::LogicalAndExpression::right, v8::internal::string, v8::internal::torque::VisitResult::type(), and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [26/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (LogicalOrExpression * expr)
Definition at line 874 of file implementation-visitor.cc.
                                                                  {
  StackScope outer_scope(this);
  VisitResult left_result = Visit(expr->left);
  if (left_result.type()->IsConstexprBool()) {
    VisitResult right_result = Visit(expr->right);
    if (!right_result.type()->IsConstexprBool()) {
      ReportError(
          "expected type constexpr bool on right-hand side of operator "
          "||");
    }
    return VisitResult(TypeOracle::GetConstexprBoolType(),
                       std::string("(") + left_result.constexpr_value() +
                           " || " + right_result.constexpr_value() + ")");
  }
  Block* true_block = assembler().NewBlock();
  Block* false_block = assembler().NewBlock();
  Block* done_block = assembler().NewBlock();
  left_result = GenerateImplicitConvert(TypeOracle::GetBoolType(), left_result);
  GenerateBranch(left_result, true_block, false_block);
  assembler().Bind(true_block);
  VisitResult true_result = GenerateBoolConstant(true);
  assembler().Goto(done_block);
  assembler().Bind(false_block);
  VisitResult false_result;
  {
    StackScope false_block_scope(this);
    false_result = false_block_scope.Yield(
        GenerateImplicitConvert(TypeOracle::GetBoolType(), Visit(expr->right)));
  }
  assembler().Goto(done_block);
  assembler().Bind(done_block);
  DCHECK_EQ(true_result, false_result);
  return outer_scope.Yield(true_result);
}
References v8::internal::torque::VisitResult::constexpr_value(), DCHECK_EQ, v8::internal::torque::TypeOracle::GetBoolType(), v8::internal::torque::TypeOracle::GetConstexprBoolType(), v8::internal::torque::Type::IsConstexprBool(), v8::internal::torque::LogicalOrExpression::left, v8::internal::torque::ReportError(), v8::internal::torque::LogicalOrExpression::right, v8::internal::string, v8::internal::torque::VisitResult::type(), and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [27/42]
void v8::internal::torque::ImplementationVisitor::Visit (Method * macro)
Definition at line 563 of file implementation-visitor.cc.
                                                {
  DCHECK(!method->IsExternal());
  VisitMacroCommon(method);
}
References v8::internal::DCHECK(), and v8::internal::torque::Callable::IsExternal().
Visit() [28/42]
void v8::internal::torque::ImplementationVisitor::Visit (NamespaceConstant * decl)
Definition at line 228 of file implementation-visitor.cc.
                                                         {
  Signature signature{{}, std::nullopt, {{}, false}, 0,
                      decl->type(), {}, false};
  BindingsManagersScope bindings_managers_scope;
  cpp::Function f =
      GenerateFunction(nullptr, decl->external_name(), signature, {});
  f.PrintDeclaration(csa_headerfile());
  f.PrintDefinition(csa_ccfile(), [&](std::ostream& stream) {
    stream << " compiler::CodeAssembler ca_(state_);\n";
    DCHECK(!signature.return_type->IsVoidOrNever());
    assembler_ = CfgAssembler(Stack<const Type*>{});
    VisitResult expression_result = Visit(decl->body());
    VisitResult return_result =
        GenerateImplicitConvert(signature.return_type, expression_result);
    CSAGenerator csa_generator{assembler().Result(), stream};
    Stack<std::string> values = *csa_generator.EmitGraph(Stack<std::string>{});
    assembler_ = std::nullopt;
    stream << " return ";
    CSAGenerator::EmitCSAValue(return_result, values, stream);
    stream << ";";
  });
}
References v8::internal::torque::NamespaceConstant::body(), v8::internal::DCHECK(), v8::internal::torque::CSAGenerator::EmitCSAValue(), v8::internal::torque::NamespaceConstant::external_name(), v8::internal::torque::cpp::Function::PrintDeclaration(), v8::internal::torque::cpp::Function::PrintDefinition(), and v8::internal::torque::Value::type().
Visit() [29/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (NewExpression * expr)
Definition at line 1684 of file implementation-visitor.cc.
                                                            {
  StackScope stack_scope(this);
  const Type* type = TypeVisitor::ComputeType(expr->type);
  const ClassType* class_type = ClassType::DynamicCast(type);
  if (class_type == nullptr) {
    ReportError("type for new expression must be a class, \"", *type,
                "\" is not");
  }
  if (!class_type->AllowInstantiation()) {
    // Classes that are only used for testing should never be instantiated.
    ReportError(*class_type,
                " cannot be allocated with new (it's used for testing)");
  }
  InitializerResults initializer_results =
      VisitInitializerResults(class_type, expr->initializers);
  const Field& map_field = class_type->LookupField("map");
  if (*map_field.offset != 0) {
    ReportError("class initializers must have a map as first parameter");
  }
  const std::map<std::string, VisitResult>& initializer_fields =
      initializer_results.field_value_map;
  auto it_object_map = initializer_fields.find(map_field.name_and_type.name);
  VisitResult object_map;
  if (class_type->IsExtern()) {
    if (it_object_map == initializer_fields.end()) {
      ReportError("Constructor for ", class_type->name(),
                  " needs Map argument!");
    }
    object_map = it_object_map->second;
  } else {
    if (it_object_map != initializer_fields.end()) {
      ReportError(
          "Constructor for ", class_type->name(),
          " must not specify Map argument; it is automatically inserted.");
    }
    Arguments get_struct_map_arguments;
    get_struct_map_arguments.parameters.push_back(
        VisitResult(TypeOracle::GetConstexprInstanceTypeType(),
                    CapifyStringWithUnderscores(class_type->name()) + "_TYPE"));
    object_map = GenerateCall(
        QualifiedName({TORQUE_INTERNAL_NAMESPACE_STRING}, "GetInstanceTypeMap"),
        get_struct_map_arguments, {}, false);
    CurrentSourcePosition::Scope current_pos(expr->pos);
    initializer_results.names.insert(initializer_results.names.begin(),
                                     MakeNode<Identifier>("map"));
    initializer_results.field_value_map[map_field.name_and_type.name] =
        object_map;
  }
  CheckInitializersWellformed(class_type->name(),
                              class_type->ComputeAllFields(),
                              expr->initializers, !class_type->IsExtern());
  LayoutForInitialization layout =
      GenerateLayoutForInitialization(class_type, initializer_results);
  Arguments allocate_arguments;
  allocate_arguments.parameters.push_back(layout.size);
  allocate_arguments.parameters.push_back(object_map);
  allocate_arguments.parameters.push_back(
      GenerateBoolConstant(expr->pretenured));
  allocate_arguments.parameters.push_back(
      GenerateBoolConstant(expr->clear_padding));
  VisitResult allocate_result = GenerateCall(
      QualifiedName({TORQUE_INTERNAL_NAMESPACE_STRING}, "AllocateFromNew"),
      allocate_arguments, {class_type}, false);
  DCHECK(allocate_result.IsOnStack());
  InitializeClass(class_type, allocate_result, initializer_results, layout);
  return stack_scope.Yield(GenerateCall(
      "%RawDownCast", Arguments{{allocate_result}, {}}, {class_type}));
}
References v8::internal::torque::ClassType::AllowInstantiation(), v8::internal::torque::CapifyStringWithUnderscores(), CheckInitializersWellformed(), v8::internal::torque::NewExpression::clear_padding, v8::internal::torque::ClassType::ComputeAllFields(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::DCHECK(), v8::internal::torque::InitializerResults::field_value_map, GenerateBoolConstant(), GenerateCall(), GenerateLayoutForInitialization(), v8::internal::torque::TypeOracle::GetConstexprInstanceTypeType(), InitializeClass(), v8::internal::torque::NewExpression::initializers, v8::internal::torque::ClassType::IsExtern(), v8::internal::torque::VisitResult::IsOnStack(), v8::internal::torque::AggregateType::LookupField(), v8::internal::torque::NameAndType::name, v8::internal::torque::AggregateType::name(), v8::internal::torque::Field::name_and_type, v8::internal::torque::InitializerResults::names, v8::internal::torque::Field::offset, v8::internal::torque::Arguments::parameters, v8::internal::torque::AstNode::pos, v8::internal::torque::NewExpression::pretenured, v8::internal::torque::ReportError(), v8::internal::torque::LayoutForInitialization::size, v8::internal::torque::TORQUE_INTERNAL_NAMESPACE_STRING, v8::internal::torque::NewExpression::type, v8::internal::tracing::type, VisitInitializerResults(), and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [30/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (ReturnStatement * stmt)
Definition at line 1327 of file implementation-visitor.cc.
                                                              {
  Callable* current_callable = CurrentCallable::Get();
  if (current_callable->signature().return_type->IsNever()) {
    std::stringstream s;
    s << "cannot return from a function with return type never";
    ReportError(s.str());
  }
  LocalLabel* end =
      current_callable->IsMacro() ? LookupLabel(kMacroEndLabelName) : nullptr;
  if (current_callable->HasReturnValue()) {
    if (!stmt->value) {
      std::stringstream s;
      s << "return expression needs to be specified for a return type of "
        << *current_callable->signature().return_type;
      ReportError(s.str());
    }
    VisitResult expression_result = Visit(*stmt->value);
    VisitResult return_result = GenerateImplicitConvert(
        current_callable->signature().return_type, expression_result);
    if (current_callable->IsMacro()) {
      if (return_result.IsOnStack()) {
        StackRange return_value_range =
            GenerateLabelGoto(end, return_result.stack_range());
        SetReturnValue(VisitResult(return_result.type(), return_value_range));
      } else {
        GenerateLabelGoto(end);
        SetReturnValue(return_result);
      }
    } else if (current_callable->IsBuiltin()) {
      assembler().Emit(ReturnInstruction{
          LoweredSlotCount(current_callable->signature().return_type)});
    } else {
      UNREACHABLE();
    }
  } else {
    if (stmt->value) {
      std::stringstream s;
      s << "return expression can't be specified for a void or never return "
           "type";
      ReportError(s.str());
    }
    GenerateLabelGoto(end);
  }
  current_callable->IncrementReturns();
  return TypeOracle::GetNeverType();
}
References v8::internal::compiler::end(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::Callable::HasReturnValue(), v8::internal::torque::Callable::IncrementReturns(), v8::internal::torque::Declarable::IsBuiltin(), v8::internal::torque::Declarable::IsMacro(), v8::internal::torque::Type::IsNever(), v8::internal::torque::VisitResult::IsOnStack(), v8::internal::torque::kMacroEndLabelName, v8::internal::torque::LoweredSlotCount(), v8::internal::torque::ReportError(), v8::internal::torque::Signature::return_type, v8::debug::SetReturnValue(), v8::internal::torque::Callable::signature(), v8::internal::torque::VisitResult::stack_range(), v8::internal::torque::VisitResult::type(), v8::internal::UNREACHABLE(), and v8::internal::torque::ReturnStatement::value.
Visit() [31/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (SpreadExpression * expr)
Definition at line 1833 of file implementation-visitor.cc.
                                                               {
  ReportError(
      "spread operators are only currently supported in indexed class field "
      "initialization expressions");
}
References v8::internal::torque::ReportError().
Visit() [32/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (Statement * stmt)
Definition at line 57 of file implementation-visitor.cc.
                                                        {
  CurrentSourcePosition::Scope scope(stmt->pos);
  StackScope stack_scope(this);
  const Type* result;
  switch (stmt->kind) {
#define ENUM_ITEM(name) \
  case AstNode::Kind::k##name: \
    result = Visit(name::cast(stmt)); \
    break;
    AST_STATEMENT_NODE_KIND_LIST(ENUM_ITEM)
#undef ENUM_ITEM
    default:
      UNREACHABLE();
  }
  DCHECK_EQ(result == TypeOracle::GetNeverType(),
            assembler().CurrentBlockIsComplete());
  return result;
}
References AST_STATEMENT_NODE_KIND_LIST, DCHECK_EQ, ENUM_ITEM, v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::AstNode::kind, v8::internal::torque::AstNode::pos, v8::base::internal::result, and v8::internal::UNREACHABLE().
Visit() [33/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (StatementExpression * expr)
Definition at line 1450 of file implementation-visitor.cc.
                                                                  {
  return VisitResult{Visit(expr->statement), assembler().TopRange(0)};
}
References v8::internal::torque::StatementExpression::statement.
Visit() [34/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (StringLiteralExpression * expr)
Definition at line 1026 of file implementation-visitor.cc.
                                                                      {
  return VisitResult{
      TypeOracle::GetConstStringType(),
      "\"" + expr->literal.substr(1, expr->literal.size() - 2) + "\""};
}
References v8::internal::torque::TypeOracle::GetConstStringType(), and v8::internal::torque::StringLiteralExpression::literal.
Visit() [35/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (StructExpression * decl)
Definition at line 2221 of file implementation-visitor.cc.
                                                               {
  StackScope stack_scope(this);
  auto& initializers = expr->initializers;
  std::vector<VisitResult> values;
  std::vector<const Type*> term_argument_types;
  values.reserve(initializers.size());
  term_argument_types.reserve(initializers.size());
  // Compute values and types of all initializer arguments
  for (const NameAndExpression& initializer : initializers) {
    VisitResult value = Visit(initializer.expression);
    values.push_back(value);
    term_argument_types.push_back(value.type());
  }
  // Compute and check struct type from given struct name and argument types
  const Type* type = TypeVisitor::ComputeTypeForStructExpression(
      expr->type, term_argument_types);
  if (const auto* struct_type = StructType::DynamicCast(type)) {
    CheckInitializersWellformed(struct_type->name(), struct_type->fields(),
                                initializers);
    // Implicitly convert values and thereby build the struct on the stack
    StackRange struct_range = assembler().TopRange(0);
    auto& fields = struct_type->fields();
    for (size_t i = 0; i < values.size(); i++) {
      values[i] =
          GenerateImplicitConvert(fields[i].name_and_type.type, values[i]);
      struct_range.Extend(values[i].stack_range());
    }
    return stack_scope.Yield(VisitResult(struct_type, struct_range));
  } else {
    const auto* bitfield_struct_type = BitFieldStructType::cast(type);
    CheckInitializersWellformed(bitfield_struct_type->name(),
                                bitfield_struct_type->fields(), initializers);
    // Create a zero and cast it to the desired bitfield struct type.
    VisitResult result{TypeOracle::GetConstInt32Type(), "0"};
    result = GenerateImplicitConvert(TypeOracle::GetInt32Type(), result);
    result = GenerateCall("Unsigned", Arguments{{result}, {}}, {});
    result = GenerateCall("%RawDownCast", Arguments{{result}, {}},
                          {bitfield_struct_type});
    // Set each field in the result. If these fields are constexpr, then all of
    // this initialization will end up reduced to a single value during TurboFan
    // optimization.
    auto& fields = bitfield_struct_type->fields();
    for (size_t i = 0; i < values.size(); i++) {
      values[i] =
          GenerateImplicitConvert(fields[i].name_and_type.type, values[i]);
      result = GenerateSetBitField(bitfield_struct_type, fields[i], result,
                                   values[i], /*starts_as_zero=*/true);
    }
    return stack_scope.Yield(result);
  }
}
References assembler(), CheckInitializersWellformed(), v8::internal::torque::TypeVisitor::ComputeTypeForStructExpression(), v8::internal::torque::StackRange::Extend(), GenerateCall(), GenerateImplicitConvert(), GenerateSetBitField(), v8::internal::torque::TypeOracle::GetConstInt32Type(), v8::internal::torque::TypeOracle::GetInt32Type(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::StructExpression::initializers, v8::base::internal::result, v8::internal::torque::CfgAssembler::TopRange(), v8::internal::torque::StructExpression::type, v8::internal::tracing::type, v8::internal::value, Visit(), and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [36/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (TailCallStatement * stmt)
Definition at line 830 of file implementation-visitor.cc.
                                                                {
  return Visit(stmt->call, true).type();
}
References v8::internal::torque::TailCallStatement::call, and v8::internal::torque::VisitResult::type().
Visit() [37/42]
void v8::internal::torque::ImplementationVisitor::Visit (TorqueMacro * macro)
Definition at line 559 of file implementation-visitor.cc.
                                                    {
  VisitMacroCommon(macro);
}
Visit() [38/42]
VisitResult v8::internal::torque::ImplementationVisitor::Visit (TryLabelExpression * expr)
Definition at line 1374 of file implementation-visitor.cc.
                                                                 {
  size_t parameter_count = expr->label_block->parameters.names.size();
  std::vector<VisitResult> parameters;
  Block* label_block = nullptr;
  Block* done_block = assembler().NewBlock();
  VisitResult try_result;
  {
    CurrentSourcePosition::Scope source_position(expr->label_block->pos);
    if (expr->label_block->parameters.has_varargs) {
      ReportError("cannot use ... for label parameters");
    }
    Stack<const Type*> label_input_stack = assembler().CurrentStack();
    TypeVector parameter_types;
    for (size_t i = 0; i < parameter_count; ++i) {
      const Type* type =
          TypeVisitor::ComputeType(expr->label_block->parameters.types[i]);
      parameter_types.push_back(type);
      if (type->IsConstexpr()) {
        ReportError("no constexpr type allowed for label arguments");
      }
      StackRange range = label_input_stack.PushMany(LowerType(type));
      parameters.push_back(VisitResult(type, range));
    }
    label_block = assembler().NewBlock(label_input_stack,
                                       IsDeferred(expr->label_block->body));
    Binding<LocalLabel> label_binding{
        &LabelBindingsManager::Get(), expr->label_block->label,
        LocalLabel{label_block, std::move(parameter_types)}};
    // Visit try
    StackScope stack_scope(this);
    try_result = Visit(expr->try_expression);
    if (try_result.type() != TypeOracle::GetNeverType()) {
      try_result = stack_scope.Yield(try_result);
      assembler().Goto(done_block);
    }
  }
  // Visit and output the code for the label block. If the label block falls
  // through, then the try must not return a value. Also, if the try doesn't
  // fall through, but the label does, then overall the try-label block
  // returns type void.
  assembler().Bind(label_block);
  const Type* label_result;
  {
    BlockBindings<LocalValue> parameter_bindings(&ValueBindingsManager::Get());
    for (size_t i = 0; i < parameter_count; ++i) {
      Identifier* name = expr->label_block->parameters.names[i];
      parameter_bindings.Add(name,
                             LocalValue{LocationReference::Temporary(
                                 parameters[i], "parameter " + name->value)});
    }
    label_result = Visit(expr->label_block->body);
  }
  if (!try_result.type()->IsVoidOrNever() && label_result->IsVoid()) {
    ReportError(
        "otherwise clauses cannot fall through in a non-void expression");
  }
  if (label_result != TypeOracle::GetNeverType()) {
    assembler().Goto(done_block);
  }
  if (label_result->IsVoid() && try_result.type()->IsNever()) {
    try_result =
        VisitResult(TypeOracle::GetVoidType(), try_result.stack_range());
  }
  if (!try_result.type()->IsNever()) {
    assembler().Bind(done_block);
  }
  return try_result;
}
References v8::internal::torque::BlockBindings< T >::Add(), v8::internal::torque::TryHandler::body, v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::compiler::turboshaft::Get(), v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::torque::ParameterList::has_varargs, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::IsDeferred(), v8::internal::torque::Type::IsNever(), v8::internal::torque::Type::IsVoid(), v8::internal::torque::Type::IsVoidOrNever(), v8::internal::torque::TryHandler::label, v8::internal::torque::TryLabelExpression::label_block, v8::internal::torque::LowerType(), v8::internal::name, v8::internal::torque::ParameterList::names, v8::internal::torque::TryHandler::parameters, v8::internal::torque::AstNode::pos, v8::internal::torque::Stack< T >::PushMany(), v8::internal::torque::ReportError(), v8::internal::torque::VisitResult::stack_range(), v8::internal::torque::LocationReference::Temporary(), v8::internal::torque::TryLabelExpression::try_expression, v8::internal::torque::VisitResult::type(), v8::internal::tracing::type, v8::internal::torque::ParameterList::types, and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [39/42]
void v8::internal::torque::ImplementationVisitor::Visit (TypeAlias * decl)
Definition at line 261 of file implementation-visitor.cc.
                                                  {
  if (alias->IsRedeclaration()) return;
  if (const ClassType* class_type = ClassType::DynamicCast(alias->type())) {
    if (class_type->IsExtern() && !class_type->nspace()->IsDefaultNamespace()) {
      Error(
          "extern classes are currently only supported in the default "
          "namespace");
    }
  }
}
References v8::internal::torque::Error(), v8::internal::torque::TypeAlias::IsRedeclaration(), and v8::internal::torque::TypeAlias::type().
Visit() [40/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (VarDeclarationStatement * stmt)
Definition at line 775 of file implementation-visitor.cc.
                                                                      {
  BlockBindings<LocalValue> block_bindings(&ValueBindingsManager::Get());
  return Visit(stmt, &block_bindings);
}
References v8::internal::compiler::turboshaft::Get().
Visit() [41/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (VarDeclarationStatement * stmt, BlockBindings< LocalValue > * block_bindings)
Definition at line 780 of file implementation-visitor.cc.
                                                                              {
  // const qualified variables are required to be initialized properly.
  if (stmt->const_qualified && !stmt->initializer) {
    ReportError("local constant \"", stmt->name, "\" is not initialized.");
  }
  std::optional<const Type*> type;
  if (stmt->type) {
    type = TypeVisitor::ComputeType(*stmt->type);
  }
  std::optional<VisitResult> init_result;
  if (stmt->initializer) {
    StackScope scope(this);
    init_result = Visit(*stmt->initializer);
    if (type) {
      init_result = GenerateImplicitConvert(*type, *init_result);
    }
    type = init_result->type();
    if ((*type)->IsConstexpr() && !stmt->const_qualified) {
      Error("Use 'const' instead of 'let' for variable '", stmt->name->value,
            "' of constexpr type '", (*type)->ToString(), "'.")
          .Position(stmt->name->pos)
          .Throw();
    }
    init_result = scope.Yield(*init_result);
  } else {
    DCHECK(type.has_value());
    if ((*type)->IsConstexpr()) {
      ReportError("constexpr variables need an initializer");
    }
    TypeVector lowered_types = LowerType(*type);
    for (const Type* t : lowered_types) {
      assembler().Emit(PushUninitializedInstruction{TypeOracle::GetTopType(
          "uninitialized variable '" + stmt->name->value + "' of type " +
              t->ToString() + " originally defined at " +
              PositionAsString(stmt->pos),
          t)});
    }
    init_result =
        VisitResult(*type, assembler().TopRange(lowered_types.size()));
  }
  LocationReference ref = stmt->const_qualified
                              ? LocationReference::Temporary(
                                    *init_result, "const " + stmt->name->value)
                              : LocationReference::VariableAccess(*init_result);
  block_bindings->Add(stmt->name, LocalValue{std::move(ref)});
  return TypeOracle::GetVoidType();
}
References v8::internal::torque::BlockBindings< T >::Add(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::VarDeclarationStatement::const_qualified, v8::internal::DCHECK(), v8::internal::torque::Error(), v8::internal::torque::TypeOracle::GetTopType(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::torque::VarDeclarationStatement::initializer, v8::internal::torque::LowerType(), v8::internal::torque::VarDeclarationStatement::name, v8::internal::torque::AstNode::pos, v8::internal::torque::MessageBuilder::Position(), v8::internal::torque::PositionAsString(), v8::internal::torque::ReportError(), v8::internal::torque::LocationReference::Temporary(), v8::internal::torque::MessageBuilder::Throw(), v8::internal::torque::VarDeclarationStatement::type, v8::internal::tracing::type, v8::internal::torque::Identifier::value, v8::internal::torque::LocationReference::VariableAccess(), and v8::internal::torque::ImplementationVisitor::StackScope::Yield().
Visit() [42/42]
const Type * v8::internal::torque::ImplementationVisitor::Visit (WhileStatement * stmt)
Definition at line 1181 of file implementation-visitor.cc.
                                                             {
  Block* body_block = assembler().NewBlock(assembler().CurrentStack());
  Block* exit_block = assembler().NewBlock(assembler().CurrentStack());
  Block* header_block = assembler().NewBlock();
  assembler().Goto(header_block);
  assembler().Bind(header_block);
  GenerateExpressionBranch(stmt->condition, body_block, exit_block);
  assembler().Bind(body_block);
  {
    BreakContinueActivator activator{exit_block, header_block};
    const Type* body_result = Visit(stmt->body);
    if (body_result != TypeOracle::GetNeverType()) {
      assembler().Goto(header_block);
    }
  }
  assembler().Bind(exit_block);
  return TypeOracle::GetVoidType();
}
References v8::internal::torque::WhileStatement::body, v8::internal::torque::WhileStatement::condition, v8::internal::torque::TypeOracle::GetNeverType(), and v8::internal::torque::TypeOracle::GetVoidType().
VisitAllDeclarables()
void v8::internal::torque::ImplementationVisitor::VisitAllDeclarables ()
Definition at line 3539 of file implementation-visitor.cc.
                                                {
  CurrentCallable::Scope current_callable(nullptr);
  const std::vector<std::unique_ptr<Declarable>>& all_declarables =
      GlobalContext::AllDeclarables();
  // This has to be an index-based loop because all_declarables can be extended
  // during the loop.
  for (size_t i = 0; i < all_declarables.size(); ++i) {
    try {
      Visit(all_declarables[i].get());
    } catch (TorqueAbortCompilation&) {
      // Recover from compile errors here. The error is recorded already.
    }
  }
  // Do the same for macros which generate C++ code.
  output_type_ = OutputType::kCC;
  const std::vector<std::pair<TorqueMacro*, SourceId>>& cc_macros =
      GlobalContext::AllMacrosForCCOutput();
  for (size_t i = 0; i < cc_macros.size(); ++i) {
    try {
      Visit(static_cast<Declarable*>(cc_macros[i].first), cc_macros[i].second);
    } catch (TorqueAbortCompilation&) {
      // Recover from compile errors here. The error is recorded already.
    }
  }
  // Do the same for macros which generate C++ debug code.
  // The set of macros is the same as C++ macros.
  output_type_ = OutputType::kCCDebug;
  const std::vector<std::pair<TorqueMacro*, SourceId>>& cc_debug_macros =
      GlobalContext::AllMacrosForCCDebugOutput();
  for (size_t i = 0; i < cc_debug_macros.size(); ++i) {
    try {
      Visit(static_cast<Declarable*>(cc_debug_macros[i].first),
            cc_debug_macros[i].second);
    } catch (TorqueAbortCompilation&) {
      // Recover from compile errors here. The error is recorded already.
    }
  }
  output_type_ = OutputType::kCSA;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::torque::anonymous_namespace{torque-compiler.cc}::CompileCurrentAst().
VisitInitializerResults()
InitializerResults v8::internal::torque::ImplementationVisitor::VisitInitializerResults (const ClassType * class_type, const std::vector< NameAndExpression > & expressions)
Definition at line 1454 of file implementation-visitor.cc.
                                                      {
  InitializerResults result;
  for (const NameAndExpression& initializer : initializers) {
    result.names.push_back(initializer.name);
    Expression* e = initializer.expression;
    const Field& field = class_type->LookupField(initializer.name->value);
    bool has_index = field.index.has_value();
    if (SpreadExpression* s = SpreadExpression::DynamicCast(e)) {
      if (!has_index) {
        ReportError(
            "spread expressions can only be used to initialize indexed class "
            "fields ('",
            initializer.name->value, "' is not)");
      }
      e = s->spreadee;
    } else if (has_index) {
      ReportError("the indexed class field '", initializer.name->value,
                  "' must be initialized with a spread operator");
    }
    result.field_value_map[field.name_and_type.name] = Visit(e);
  }
  return result;
}
References v8::internal::torque::Field::index, v8::internal::torque::AggregateType::LookupField(), v8::internal::torque::NameAndType::name, v8::internal::torque::Field::name_and_type, v8::internal::torque::ReportError(), and v8::base::internal::result.
Referenced by Visit().
VisitMacroCommon()
void v8::internal::torque::ImplementationVisitor::VisitMacroCommon (Macro * macro)
Definition at line 409 of file implementation-visitor.cc.
                                                         {
  CurrentCallable::Scope current_callable(macro);
  const Signature& signature = macro->signature();
  const Type* return_type = macro->signature().return_type;
  bool can_return = return_type != TypeOracle::GetNeverType();
  bool has_return_value =
      can_return && return_type != TypeOracle::GetVoidType();
  cpp::Function f = GenerateMacroFunctionDeclaration(macro);
  f.PrintDeclaration(csa_headerfile());
  csa_headerfile() << "\n";
  cpp::File csa_cc(csa_ccfile());
  // Avoid multiple-definition errors since it is possible for multiple
  // generated -inl.inc files to all contain function definitions for the same
  // Torque macro.
  std::optional<cpp::IncludeGuardScope> include_guard;
  if (output_type_ == OutputType::kCC) {
    include_guard.emplace(&csa_cc, "V8_INTERNAL_DEFINED_"s + macro->CCName());
  } else if (output_type_ == OutputType::kCCDebug) {
    include_guard.emplace(&csa_cc,
                          "V8_INTERNAL_DEFINED_"s + macro->CCDebugName());
  }
  f.PrintBeginDefinition(csa_ccfile());
  if (output_type_ == OutputType::kCC) {
    // For now, generated C++ is only for field offset computations. If we ever
    // generate C++ code that can allocate, then it should be handlified.
    csa_ccfile() << " DisallowGarbageCollection no_gc;\n";
  } else if (output_type_ == OutputType::kCSA) {
    csa_ccfile() << " compiler::CodeAssembler ca_(state_);\n";
    csa_ccfile()
        << " compiler::CodeAssembler::SourcePositionScope pos_scope(&ca_);\n";
  }
  Stack<std::string> lowered_parameters;
  Stack<const Type*> lowered_parameter_types;
  std::vector<VisitResult> arguments;
  std::optional<LocationReference> this_reference;
  if (Method* method = Method::DynamicCast(macro)) {
    const Type* this_type = method->aggregate_type();
    LowerParameter(this_type, ExternalParameterName(kThisParameterName),
                   &lowered_parameters);
    StackRange range = lowered_parameter_types.PushMany(LowerType(this_type));
    VisitResult this_result = VisitResult(this_type, range);
    // For classes, mark 'this' as a temporary to prevent assignment to it.
    // Note that using a VariableAccess for non-class types is technically
    // incorrect because changes to the 'this' variable do not get reflected
    // to the caller. Therefore struct methods should always be inlined and a
    // C++ version should never be generated, since it would be incorrect.
    // However, in order to be able to type- and semantics-check even unused
    // struct methods, set the this_reference to be the local variable copy of
    // the passed-in this, which allows the visitor to at least find and report
    // errors.
    this_reference =
        (this_type->IsClassType())
            ? LocationReference::Temporary(this_result, "this parameter")
            : LocationReference::VariableAccess(this_result);
  }
  for (size_t i = 0; i < macro->signature().parameter_names.size(); ++i) {
    if (this_reference && i == macro->signature().implicit_count) continue;
    const std::string& name = macro->parameter_names()[i]->value;
    std::string external_name = ExternalParameterName(name);
    const Type* type = macro->signature().types()[i];
    if (type->IsConstexpr()) {
      arguments.push_back(VisitResult(type, external_name));
    } else {
      LowerParameter(type, external_name, &lowered_parameters);
      StackRange range = lowered_parameter_types.PushMany(LowerType(type));
      arguments.push_back(VisitResult(type, range));
    }
  }
  DCHECK_EQ(lowered_parameters.Size(), lowered_parameter_types.Size());
  assembler_ = CfgAssembler(lowered_parameter_types);
  std::vector<Block*> label_blocks;
  for (const LabelDeclaration& label_info : signature.labels) {
    Stack<const Type*> label_input_stack;
    for (const Type* type : label_info.types) {
      label_input_stack.PushMany(LowerType(type));
    }
    Block* block = assembler().NewBlock(std::move(label_input_stack));
    label_blocks.push_back(block);
  }
  VisitResult return_value =
      InlineMacro(macro, this_reference, arguments, label_blocks);
  Block* end = assembler().NewBlock();
  if (return_type != TypeOracle::GetNeverType()) {
    assembler().Goto(end);
  }
  for (size_t i = 0; i < label_blocks.size(); ++i) {
    Block* label_block = label_blocks[i];
    const LabelDeclaration& label_info = signature.labels[i];
    assembler().Bind(label_block);
    std::vector<std::string> label_parameter_variables;
    for (size_t j = 0; j < label_info.types.size(); ++j) {
      LowerLabelParameter(label_info.types[j],
                          ExternalLabelParameterName(label_info.name->value, j),
                          &label_parameter_variables);
    }
    assembler().Emit(
        GotoExternalInstruction{ExternalLabelName(label_info.name->value),
                                std::move(label_parameter_variables)});
  }
  if (return_type != TypeOracle::GetNeverType()) {
    assembler().Bind(end);
  }
  std::optional<Stack<std::string>> values;
  if (output_type_ == OutputType::kCC) {
    CCGenerator cc_generator{assembler().Result(), csa_ccfile()};
    values = cc_generator.EmitGraph(lowered_parameters);
  } else if (output_type_ == OutputType::kCCDebug) {
    CCGenerator cc_generator{assembler().Result(), csa_ccfile(), true};
    values = cc_generator.EmitGraph(lowered_parameters);
  } else {
    CSAGenerator csa_generator{assembler().Result(), csa_ccfile()};
    values = csa_generator.EmitGraph(lowered_parameters);
  }
  assembler_ = std::nullopt;
  if (has_return_value) {
    csa_ccfile() << " return ";
    if (output_type_ == OutputType::kCCDebug) {
      csa_ccfile() << "{d::MemoryAccessResult::kOk, ";
      CCGenerator::EmitCCValue(return_value, *values, csa_ccfile());
      csa_ccfile() << "}";
    } else if (output_type_ == OutputType::kCC) {
      CCGenerator::EmitCCValue(return_value, *values, csa_ccfile());
    } else {
      CSAGenerator::EmitCSAValue(return_value, *values, csa_ccfile());
    }
    csa_ccfile() << ";\n";
  }
  f.PrintEndDefinition(csa_ccfile());
  include_guard.reset();
}
References v8::internal::torque::Callable::CCDebugName(), v8::internal::torque::Callable::CCName(), DCHECK_EQ, v8::internal::torque::CCGenerator::EmitCCValue(), v8::internal::torque::CSAGenerator::EmitCSAValue(), v8::internal::torque::CCGenerator::EmitGraph(), v8::internal::torque::CSAGenerator::EmitGraph(), v8::internal::compiler::end(), v8::internal::torque::TypeOracle::GetNeverType(), v8::internal::torque::TypeOracle::GetVoidType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::Signature::implicit_count, v8::internal::torque::TypeBase::IsClassType(), v8::internal::torque::kCC, v8::internal::torque::kCCDebug, v8::internal::torque::kCSA, v8::internal::torque::kThisParameterName, v8::internal::torque::Signature::labels, v8::internal::torque::LowerType(), v8::internal::name, v8::internal::torque::LabelDeclaration::name, v8::internal::torque::Callable::parameter_names(), v8::internal::torque::cpp::Function::PrintBeginDefinition(), v8::internal::torque::cpp::Function::PrintDeclaration(), v8::internal::torque::cpp::Function::PrintEndDefinition(), v8::internal::torque::Stack< T >::PushMany(), v8::internal::torque::Signature::return_type, v8::internal::torque::Callable::signature(), v8::internal::torque::Stack< T >::Size(), v8::internal::string, v8::internal::torque::LocationReference::Temporary(), v8::internal::tracing::type, v8::internal::torque::LabelDeclaration::types, v8::internal::torque::Signature::types(), v8::internal::torque::Identifier::value, and v8::internal::torque::LocationReference::VariableAccess().
WriteFile()
void v8::internal::torque::ImplementationVisitor::WriteFile (const std::string & file, const std::string & content) [inline], [private]
Definition at line 843 of file implementation-visitor.h.
                                                                  {
    if (is_dry_run_) return;
    ReplaceFileContentsIfDifferent(file, content);
  }
References file(), is_dry_run_, and v8::internal::torque::ReplaceFileContentsIfDifferent().
Referenced by GenerateClassDebugReaders(), GenerateImplementation(), and GenerateInstanceTypes().
Member Data Documentation
assembler_
std::optional<CfgAssembler> v8::internal::torque::ImplementationVisitor::assembler_ [private]
Definition at line 865 of file implementation-visitor.h.
Referenced by assembler().
bitfield_expressions_
std::unordered_map<const Expression*, const Identifier*> v8::internal::torque::ImplementationVisitor::bitfield_expressions_ [private]
Definition at line 875 of file implementation-visitor.h.
Referenced by PropagateBitfieldMark(), and TryGetSourceForBitfieldExpression().
debug_macros_cc_
std::stringstream v8::internal::torque::ImplementationVisitor::debug_macros_cc_ [private]
Definition at line 883 of file implementation-visitor.h.
Referenced by csa_ccfile(), and GenerateImplementation().
debug_macros_h_
std::stringstream v8::internal::torque::ImplementationVisitor::debug_macros_h_ [private]
Definition at line 884 of file implementation-visitor.h.
Referenced by csa_headerfile(), and GenerateImplementation().
inlining_macros_
std::unordered_set<const Macro*> v8::internal::torque::ImplementationVisitor::inlining_macros_ [private]
Definition at line 879 of file implementation-visitor.h.
is_dry_run_
bool v8::internal::torque::ImplementationVisitor::is_dry_run_ [private]
Definition at line 867 of file implementation-visitor.h.
Referenced by SetDryRun(), and WriteFile().
null_stream_
NullOStream v8::internal::torque::ImplementationVisitor::null_stream_ [private]
Definition at line 866 of file implementation-visitor.h.
Referenced by csa_ccfile(), and csa_headerfile().
output_type_
OutputType v8::internal::torque::ImplementationVisitor::output_type_ = OutputType::kCSA [private]
Definition at line 886 of file implementation-visitor.h.
Referenced by csa_ccfile(), csa_headerfile(), GenerateFunction(), and GenerateMacroFunctionDeclaration().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/implementation-visitor.h
/mnt/V8SourceCode/src/torque/class-debug-reader-generator.cc
/mnt/V8SourceCode/src/torque/implementation-visitor.cc
/mnt/V8SourceCode/src/torque/instance-type-generator.cc