v8::internal::torque::LocationReference Class Reference
#include <implementation-visitor.h>
Public Member Functions
bool IsConst () const
bool IsVariableAccess () const
const VisitResult & variable () const
bool IsTemporary () const
const VisitResult & temporary () const
bool IsHeapReference () const
const VisitResult & heap_reference () const
FieldSynchronization heap_reference_synchronization () const
bool IsHeapSlice () const
const VisitResult & heap_slice () const
bool IsBitFieldAccess () const
const LocationReference & bit_field_struct_location () const
const BitField & bit_field () const
std::optional< const Type * > ReferencedType () const
const VisitResult & GetVisitResult () const
const std::string & temporary_description () const
bool IsCallAccess () const
const VisitResultVector & call_arguments () const
const std::string & eval_function () const
const std::string & assign_function () const
std::optional< Binding< LocalValue > * > binding () const
Static Public Member Functions
static LocationReference VariableAccess (VisitResult variable, std::optional< Binding< LocalValue > * > binding=std::nullopt)
static LocationReference Temporary (VisitResult temporary, std::string description)
static LocationReference HeapReference (VisitResult heap_reference, FieldSynchronization synchronization=FieldSynchronization::kNone)
static LocationReference HeapSlice (VisitResult heap_slice)
static LocationReference ArrayAccess (VisitResult base, VisitResult offset)
static LocationReference FieldAccess (VisitResult object, std::string fieldname)
static LocationReference BitFieldAccess (const LocationReference &object, BitField field)
Private Member Functions
LocationReference ()=default
Private Attributes
std::optional< VisitResult > variable_
std::optional< VisitResult > temporary_
std::optional< std::string > temporary_description_
std::optional< VisitResult > heap_reference_
FieldSynchronization heap_reference_synchronization_
std::optional< VisitResult > heap_slice_
std::optional< std::string > eval_function_
std::optional< std::string > assign_function_
VisitResultVector call_arguments_
std::optional< Binding< LocalValue > * > binding_
std::shared_ptr< const LocationReference > bit_field_struct_
std::optional< BitField > bit_field_
Detailed Description
Definition at line 34 of file implementation-visitor.h.
Constructor & Destructor Documentation
LocationReference()
v8::internal::torque::LocationReference::LocationReference () [private], [default]
Member Function Documentation
ArrayAccess()
static LocationReference v8::internal::torque::LocationReference::ArrayAccess (VisitResult base, VisitResult offset) [inline], [static]
Definition at line 76 of file implementation-visitor.h.
                                                                             {
    LocationReference result;
    result.eval_function_ = std::string{"[]"};
    result.assign_function_ = std::string{"[]="};
    result.call_arguments_ = {base, offset};
    return result;
  }
References v8::base::internal::result, and v8::internal::string.
Referenced by v8::internal::torque::ImplementationVisitor::GetLocationReference().
assign_function()
const std::string& v8::internal::torque::LocationReference::assign_function () const [inline]
Definition at line 196 of file implementation-visitor.h.
                                           {
    DCHECK(IsCallAccess());
    return *assign_function_;
  }
References assign_function_, v8::internal::DCHECK(), and IsCallAccess().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation().
binding()
std::optional<Binding<LocalValue>*> v8::internal::torque::LocationReference::binding () const [inline]
Definition at line 200 of file implementation-visitor.h.
                                                    {
    DCHECK(IsVariableAccess());
    return binding_;
  }
References binding_, v8::internal::DCHECK(), and IsVariableAccess().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), and VariableAccess().
bit_field()
const BitField& v8::internal::torque::LocationReference::bit_field () const [inline]
Definition at line 144 of file implementation-visitor.h.
                                    {
    DCHECK(IsBitFieldAccess());
    return *bit_field_;
  }
References bit_field_, v8::internal::DCHECK(), and IsBitFieldAccess().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), and v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation().
bit_field_struct_location()
const LocationReference& v8::internal::torque::LocationReference::bit_field_struct_location () const [inline]
Definition at line 140 of file implementation-visitor.h.
                                                             {
    DCHECK(IsBitFieldAccess());
    return *bit_field_struct_;
  }
References bit_field_struct_, v8::internal::DCHECK(), and IsBitFieldAccess().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), and v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation().
BitFieldAccess()
static LocationReference v8::internal::torque::LocationReference::BitFieldAccess (const LocationReference & object, BitField field) [inline], [static]
Definition at line 91 of file implementation-visitor.h.
                                                          {
    LocationReference result;
    result.bit_field_struct_ = std::make_shared<LocationReference>(object);
    result.bit_field_ = std::move(field);
    return result;
  }
References v8::base::internal::result.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldAccess().
call_arguments()
const VisitResultVector& v8::internal::torque::LocationReference::call_arguments () const [inline]
Definition at line 188 of file implementation-visitor.h.
                                                  {
    DCHECK(IsCallAccess());
    return call_arguments_;
  }
References call_arguments_, v8::internal::DCHECK(), and IsCallAccess().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation().
eval_function()
const std::string& v8::internal::torque::LocationReference::eval_function () const [inline]
Definition at line 192 of file implementation-visitor.h.
                                         {
    DCHECK(IsCallAccess());
    return *eval_function_;
  }
References v8::internal::DCHECK(), eval_function_, and IsCallAccess().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation().
FieldAccess()
static LocationReference v8::internal::torque::LocationReference::FieldAccess (VisitResult object, std::string fieldname) [inline], [static]
Definition at line 83 of file implementation-visitor.h.
                                                            {
    LocationReference result;
    result.eval_function_ = "." + fieldname;
    result.assign_function_ = "." + fieldname + "=";
    result.call_arguments_ = {object};
    return result;
  }
References v8::base::internal::result.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldAccess().
GetVisitResult()
const VisitResult& v8::internal::torque::LocationReference::GetVisitResult () const [inline]
Definition at line 170 of file implementation-visitor.h.
                                            {
    if (IsVariableAccess()) return variable();
    if (IsHeapSlice()) return heap_slice();
    DCHECK(IsTemporary());
    return temporary();
  }
References v8::internal::DCHECK(), heap_slice(), IsHeapSlice(), IsTemporary(), IsVariableAccess(), temporary(), and variable().
Referenced by v8::internal::torque::Binding< T >::CheckWritten(), v8::internal::torque::ImplementationVisitor::GenerateReferenceToItemInHeapSlice(), v8::internal::torque::LocalValue::GetLocationReference(), v8::internal::torque::ImplementationVisitor::InitializeClass(), and ReferencedType().
heap_reference()
const VisitResult& v8::internal::torque::LocationReference::heap_reference () const [inline]
Definition at line 122 of file implementation-visitor.h.
                                            {
    DCHECK(IsHeapReference());
    return *heap_reference_;
  }
References v8::internal::DCHECK(), heap_reference_, and IsHeapReference().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), HeapReference(), IsConst(), ReferencedType(), and v8::internal::torque::ImplementationVisitor::Visit().
heap_reference_synchronization()
FieldSynchronization v8::internal::torque::LocationReference::heap_reference_synchronization () const [inline]
Definition at line 126 of file implementation-visitor.h.
                                                              {
    DCHECK(IsHeapReference());
    return heap_reference_synchronization_;
  }
References v8::internal::DCHECK(), heap_reference_synchronization_, and IsHeapReference().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation().
heap_slice()
const VisitResult& v8::internal::torque::LocationReference::heap_slice () const [inline]
Definition at line 131 of file implementation-visitor.h.
                                        {
    DCHECK(IsHeapSlice());
    return *heap_slice_;
  }
References v8::internal::DCHECK(), heap_slice_, and IsHeapSlice().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GenerateReferenceToItemInHeapSlice(), GetVisitResult(), HeapSlice(), ReferencedType(), and v8::internal::torque::ImplementationVisitor::Visit().
HeapReference()
static LocationReference v8::internal::torque::LocationReference::HeapReference (VisitResult heap_reference, FieldSynchronization synchronization = FieldSynchronization::kNone) [inline], [static]
Definition at line 56 of file implementation-visitor.h.
                                                                        {
    LocationReference result;
    DCHECK(TypeOracle::MatchReferenceGeneric(heap_reference.type()));
    result.heap_reference_ = std::move(heap_reference);
    result.heap_reference_synchronization_ = synchronization;
    return result;
  }
References v8::internal::DCHECK(), heap_reference(), v8::internal::torque::TypeOracle::MatchReferenceGeneric(), v8::base::internal::result, and v8::internal::torque::VisitResult::type().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::ImplementationVisitor::GenerateFieldReferenceForInit(), v8::internal::torque::ImplementationVisitor::GenerateReferenceToItemInHeapSlice(), and v8::internal::torque::ImplementationVisitor::GetLocationReference().
HeapSlice()
static LocationReference v8::internal::torque::LocationReference::HeapSlice (VisitResult heap_slice) [inline], [static]
Definition at line 67 of file implementation-visitor.h.
                                                             {
    LocationReference result;
    DCHECK(Type::MatchUnaryGeneric(heap_slice.type(),
                                   TypeOracle::GetConstSliceGeneric()) ||
           Type::MatchUnaryGeneric(heap_slice.type(),
                                   TypeOracle::GetMutableSliceGeneric()));
    result.heap_slice_ = std::move(heap_slice);
    return result;
  }
References v8::internal::DCHECK(), v8::internal::torque::TypeOracle::GetConstSliceGeneric(), v8::internal::torque::TypeOracle::GetMutableSliceGeneric(), heap_slice(), v8::internal::torque::Type::MatchUnaryGeneric(), v8::base::internal::result, and v8::internal::torque::VisitResult::type().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldReference(), and v8::internal::torque::ImplementationVisitor::GenerateFieldReferenceForInit().
IsBitFieldAccess()
bool v8::internal::torque::LocationReference::IsBitFieldAccess () const [inline]
Definition at line 135 of file implementation-visitor.h.
                                {
    bool is_bitfield_access = bit_field_struct_ != nullptr;
    DCHECK_EQ(is_bitfield_access, bit_field_.has_value());
    return is_bitfield_access;
  }
References bit_field_, bit_field_struct_, and DCHECK_EQ.
Referenced by bit_field(), bit_field_struct_location(), v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), ReferencedType(), and v8::internal::torque::ImplementationVisitor::Visit().
IsCallAccess()
bool v8::internal::torque::LocationReference::IsCallAccess () const [inline]
Definition at line 183 of file implementation-visitor.h.
                            {
    bool is_call_access = eval_function_.has_value();
    DCHECK_EQ(is_call_access, assign_function_.has_value());
    return is_call_access;
  }
References assign_function_, DCHECK_EQ, and eval_function_.
Referenced by assign_function(), call_arguments(), eval_function(), v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), and v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation().
IsConst()
bool v8::internal::torque::LocationReference::IsConst () const [inline]
Definition at line 99 of file implementation-visitor.h.
                       {
    if (IsHeapReference()) {
      bool is_const;
      bool success =
          TypeOracle::MatchReferenceGeneric(heap_reference().type(), &is_const)
              .has_value();
      CHECK(success);
      return is_const;
    }
    return IsTemporary();
  }
References CHECK, heap_reference(), IsHeapReference(), IsTemporary(), v8::internal::torque::TypeOracle::MatchReferenceGeneric(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation().
IsHeapReference()
bool v8::internal::torque::LocationReference::IsHeapReference () const [inline]
Definition at line 121 of file implementation-visitor.h.
{ return heap_reference_.has_value(); }
References heap_reference_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), heap_reference(), heap_reference_synchronization(), IsConst(), ReferencedType(), and v8::internal::torque::ImplementationVisitor::Visit().
IsHeapSlice()
bool v8::internal::torque::LocationReference::IsHeapSlice () const [inline]
Definition at line 130 of file implementation-visitor.h.
{ return heap_slice_.has_value(); }
References heap_slice_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateCall(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateReferenceToItemInHeapSlice(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), GetVisitResult(), heap_slice(), v8::internal::torque::ImplementationVisitor::InitializeClass(), ReferencedType(), and v8::internal::torque::ImplementationVisitor::Visit().
IsTemporary()
bool v8::internal::torque::LocationReference::IsTemporary () const [inline]
Definition at line 116 of file implementation-visitor.h.
{ return temporary_.has_value(); }
References temporary_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), GetVisitResult(), IsConst(), ReferencedType(), temporary(), and temporary_description().
IsVariableAccess()
bool v8::internal::torque::LocationReference::IsVariableAccess () const [inline]
Definition at line 111 of file implementation-visitor.h.
{ return variable_.has_value(); }
References variable_.
Referenced by binding(), v8::internal::torque::Binding< T >::CheckWritten(), v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::LocalValue::GetLocationReference(), GetVisitResult(), ReferencedType(), variable(), and v8::internal::torque::ImplementationVisitor::Visit().
ReferencedType()
std::optional<const Type*> v8::internal::torque::LocationReference::ReferencedType () const [inline]
Definition at line 149 of file implementation-visitor.h.
                                                  {
    if (IsHeapReference()) {
      return *TypeOracle::MatchReferenceGeneric(heap_reference().type());
    }
    if (IsHeapSlice()) {
      if (auto type = Type::MatchUnaryGeneric(
              heap_slice().type(), TypeOracle::GetMutableSliceGeneric())) {
        return *type;
      }
      return Type::MatchUnaryGeneric(heap_slice().type(),
                                     TypeOracle::GetConstSliceGeneric());
    }
    if (IsBitFieldAccess()) {
      return bit_field_->name_and_type.type;
    }
    if (IsVariableAccess() || IsHeapSlice() || IsTemporary()) {
      return GetVisitResult().type();
    }
    return std::nullopt;
  }
References bit_field_, v8::internal::torque::TypeOracle::GetConstSliceGeneric(), v8::internal::torque::TypeOracle::GetMutableSliceGeneric(), GetVisitResult(), heap_reference(), heap_slice(), IsBitFieldAccess(), IsHeapReference(), IsHeapSlice(), IsTemporary(), IsVariableAccess(), v8::internal::torque::TypeOracle::MatchReferenceGeneric(), v8::internal::torque::Type::MatchUnaryGeneric(), v8::internal::torque::VisitResult::type(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), and v8::internal::torque::ImplementationVisitor::Visit().
temporary()
const VisitResult& v8::internal::torque::LocationReference::temporary () const [inline]
Definition at line 117 of file implementation-visitor.h.
                                       {
    DCHECK(IsTemporary());
    return *temporary_;
  }
References v8::internal::DCHECK(), IsTemporary(), and temporary_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), GetVisitResult(), and Temporary().
Temporary()
static LocationReference v8::internal::torque::LocationReference::Temporary (VisitResult temporary, std::string description) [inline], [static]
Definition at line 47 of file implementation-visitor.h.
                                                            {
    LocationReference result;
    result.temporary_ = std::move(temporary);
    result.temporary_description_ = std::move(description);
    return result;
  }
References v8::base::internal::result, and temporary().
Referenced by v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::AddParameter(), v8::internal::torque::ImplementationVisitor::GenerateArrayLength(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::ImplementationVisitor::GenerateReferenceToItemInHeapSlice(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), v8::internal::torque::ImplementationVisitor::InlineMacro(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
temporary_description()
const std::string& v8::internal::torque::LocationReference::temporary_description () const [inline]
Definition at line 178 of file implementation-visitor.h.
                                                 {
    DCHECK(IsTemporary());
    return *temporary_description_;
  }
References v8::internal::DCHECK(), IsTemporary(), and temporary_description_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), and v8::internal::torque::ImplementationVisitor::GenerateFieldAccess().
variable()
const VisitResult& v8::internal::torque::LocationReference::variable () const [inline]
Definition at line 112 of file implementation-visitor.h.
                                      {
    DCHECK(IsVariableAccess());
    return *variable_;
  }
References v8::internal::DCHECK(), IsVariableAccess(), and variable_.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), GetVisitResult(), and VariableAccess().
VariableAccess()
static LocationReference v8::internal::torque::LocationReference::VariableAccess (VisitResult variable, std::optional< Binding< LocalValue > * > binding = std::nullopt) [inline], [static]
Definition at line 37 of file implementation-visitor.h.
                                                              {
    DCHECK(variable.IsOnStack());
    LocationReference result;
    result.variable_ = std::move(variable);
    result.binding_ = binding;
    return result;
  }
References binding(), v8::internal::DCHECK(), v8::internal::torque::VisitResult::IsOnStack(), v8::base::internal::result, and variable().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::LocalValue::GetLocationReference(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::ImplementationVisitor::VisitMacroCommon().
Member Data Documentation
assign_function_
std::optional<std::string> v8::internal::torque::LocationReference::assign_function_ [private]
Definition at line 214 of file implementation-visitor.h.
Referenced by assign_function(), and IsCallAccess().
binding_
std::optional<Binding<LocalValue>*> v8::internal::torque::LocationReference::binding_ [private]
Definition at line 216 of file implementation-visitor.h.
Referenced by binding().
bit_field_
std::optional<BitField> v8::internal::torque::LocationReference::bit_field_ [private]
Definition at line 223 of file implementation-visitor.h.
Referenced by bit_field(), IsBitFieldAccess(), and ReferencedType().
bit_field_struct_
std::shared_ptr<const LocationReference> v8::internal::torque::LocationReference::bit_field_struct_ [private]
Definition at line 222 of file implementation-visitor.h.
Referenced by bit_field_struct_location(), and IsBitFieldAccess().
call_arguments_
VisitResultVector v8::internal::torque::LocationReference::call_arguments_ [private]
Definition at line 215 of file implementation-visitor.h.
Referenced by call_arguments().
eval_function_
std::optional<std::string> v8::internal::torque::LocationReference::eval_function_ [private]
Definition at line 213 of file implementation-visitor.h.
Referenced by eval_function(), and IsCallAccess().
heap_reference_
std::optional<VisitResult> v8::internal::torque::LocationReference::heap_reference_ [private]
Definition at line 209 of file implementation-visitor.h.
Referenced by heap_reference(), and IsHeapReference().
heap_reference_synchronization_
FieldSynchronization v8::internal::torque::LocationReference::heap_reference_synchronization_ [private]
Initial value:
=
      FieldSynchronization::kNone
Definition at line 210 of file implementation-visitor.h.
Referenced by heap_reference_synchronization().
heap_slice_
std::optional<VisitResult> v8::internal::torque::LocationReference::heap_slice_ [private]
Definition at line 212 of file implementation-visitor.h.
Referenced by heap_slice(), and IsHeapSlice().
temporary_
std::optional<VisitResult> v8::internal::torque::LocationReference::temporary_ [private]
Definition at line 207 of file implementation-visitor.h.
Referenced by IsTemporary(), and temporary().
temporary_description_
std::optional<std::string> v8::internal::torque::LocationReference::temporary_description_ [private]
Definition at line 208 of file implementation-visitor.h.
Referenced by temporary_description().
variable_
std::optional<VisitResult> v8::internal::torque::LocationReference::variable_ [private]
Definition at line 206 of file implementation-visitor.h.
Referenced by IsVariableAccess(), and variable().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/implementation-visitor.h