v8::internal::PendingCompilationErrorHandler Class Reference
#include <pending-compilation-error-handler.h>
Classes
class MessageDetails
Public Member Functions
PendingCompilationErrorHandler ()=default
PendingCompilationErrorHandler (const PendingCompilationErrorHandler &)=delete
PendingCompilationErrorHandler & operator= (const PendingCompilationErrorHandler &)=delete
void ReportMessageAt (int start_position, int end_position, MessageTemplate message, const char *arg=nullptr)
void ReportMessageAt (int start_position, int end_position, MessageTemplate message, const AstRawString *arg)
void ReportMessageAt (int start_position, int end_position, MessageTemplate message, const AstRawString *arg0, const char *arg1)
void ReportMessageAt (int start_position, int end_position, MessageTemplate message, const AstRawString *arg0, const AstRawString *arg1, const char *arg2)
void ReportWarningAt (int start_position, int end_position, MessageTemplate message, const char *arg=nullptr)
bool stack_overflow () const
void set_stack_overflow ()
bool has_pending_error () const
bool has_pending_warnings () const
template<typename IsolateT >
void PrepareErrors (IsolateT *isolate, AstValueFactory *ast_value_factory)
V8_EXPORT_PRIVATE void ReportErrors (Isolate *isolate, Handle< Script > script) const
template<typename IsolateT >
void PrepareWarnings (IsolateT *isolate)
void ReportWarnings (Isolate *isolate, Handle< Script > script) const
V8_EXPORT_PRIVATE DirectHandle< String > FormatErrorMessageForTest (Isolate *isolate)
void set_unidentifiable_error ()
void clear_unidentifiable_error ()
bool has_error_unidentifiable_by_preparser () const
Private Member Functions
void ThrowPendingError (Isolate *isolate, Handle< Script > script) const
Private Attributes
bool has_pending_error_ = false
bool stack_overflow_ = false
bool unidentifiable_error_ = false
MessageDetails error_details_
std::forward_list< MessageDetails > warning_messages_
Detailed Description
Definition at line 26 of file pending-compilation-error-handler.h.
Constructor & Destructor Documentation
PendingCompilationErrorHandler() [1/2]
v8::internal::PendingCompilationErrorHandler::PendingCompilationErrorHandler () [default]
PendingCompilationErrorHandler() [2/2]
v8::internal::PendingCompilationErrorHandler::PendingCompilationErrorHandler (const PendingCompilationErrorHandler &) [delete]
Member Function Documentation
clear_unidentifiable_error()
void v8::internal::PendingCompilationErrorHandler::clear_unidentifiable_error () [inline]
Definition at line 80 of file pending-compilation-error-handler.h.
                                    {
    has_pending_error_ = false;
    unidentifiable_error_ = false;
  }
References has_pending_error_, and unidentifiable_error_.
FormatErrorMessageForTest()
DirectHandle< String > v8::internal::PendingCompilationErrorHandler::FormatErrorMessageForTest (Isolate * isolate)
Definition at line 205 of file pending-compilation-error-handler.cc.
                      {
  error_details_.Prepare(isolate);
  int num_args = 0;
  DirectHandle<Object> args[MessageDetails::kMaxArgumentCount];
  for (; num_args < MessageDetails::kMaxArgumentCount; ++num_args) {
    args[num_args] = error_details_.ArgString(isolate, num_args);
    if (args[num_args].is_null()) break;
  }
  return MessageFormatter::Format(isolate, error_details_.message(),
                                  base::VectorOf(args, num_args));
}
References v8::base::args, v8::internal::PendingCompilationErrorHandler::MessageDetails::ArgString(), error_details_, v8::internal::MessageFormatter::Format(), v8::internal::PendingCompilationErrorHandler::MessageDetails::kMaxArgumentCount, v8::internal::PendingCompilationErrorHandler::MessageDetails::message(), v8::internal::PendingCompilationErrorHandler::MessageDetails::Prepare(), and v8::base::VectorOf().
has_error_unidentifiable_by_preparser()
bool v8::internal::PendingCompilationErrorHandler::has_error_unidentifiable_by_preparser () const [inline]
Definition at line 84 of file pending-compilation-error-handler.h.
                                                     {
    return unidentifiable_error_;
  }
References unidentifiable_error_.
has_pending_error()
bool v8::internal::PendingCompilationErrorHandler::has_pending_error () const [inline]
Definition at line 58 of file pending-compilation-error-handler.h.
{ return has_pending_error_; }
References has_pending_error_.
Referenced by v8::internal::DeclarationScope::AllocateVariables(), v8::internal::anonymous_namespace{compiler.cc}::FailWithPreparedException(), PrepareErrors(), v8::internal::anonymous_namespace{compiler.cc}::PrepareException(), PrepareWarnings(), and ReportWarnings().
has_pending_warnings()
bool v8::internal::PendingCompilationErrorHandler::has_pending_warnings () const [inline]
Definition at line 59 of file pending-compilation-error-handler.h.
{ return !warning_messages_.empty(); }
References warning_messages_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::FinalizeDeferredUnoptimizedCompilationJobs(), v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation(), and v8::internal::anonymous_namespace{compiler.cc}::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs().
operator=()
PendingCompilationErrorHandler& v8::internal::PendingCompilationErrorHandler::operator= (const PendingCompilationErrorHandler &) [delete]
PrepareErrors()
template<typename IsolateT >
template void v8::internal::PendingCompilationErrorHandler::PrepareErrors (IsolateT * isolate, AstValueFactory * ast_value_factory)
Definition at line 160 of file pending-compilation-error-handler.cc.
                                                           {
  if (stack_overflow()) return;
  DCHECK(has_pending_error());
  // Internalize ast values for throwing the pending error.
  ast_value_factory->Internalize(isolate);
  error_details_.Prepare(isolate);
}
References v8::internal::DCHECK(), error_details_, has_pending_error(), v8::internal::AstValueFactory::Internalize(), v8::internal::PendingCompilationErrorHandler::MessageDetails::Prepare(), and stack_overflow().
Referenced by v8::Shell::ExecuteString(), v8::internal::anonymous_namespace{liveedit.cc}::ParseScript(), and v8::internal::anonymous_namespace{compiler.cc}::PrepareException().
PrepareWarnings()
template<typename IsolateT >
template void v8::internal::PendingCompilationErrorHandler::PrepareWarnings (IsolateT * isolate)
Definition at line 133 of file pending-compilation-error-handler.cc.
                                                                      {
  DCHECK(!has_pending_error());
  for (MessageDetails& warning : warning_messages_) {
    warning.Prepare(isolate);
  }
}
References v8::internal::DCHECK(), has_pending_error(), and warning_messages_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::FinalizeDeferredUnoptimizedCompilationJobs(), and v8::internal::anonymous_namespace{compiler.cc}::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs().
ReportErrors()
V8_EXPORT_PRIVATE void v8::internal::PendingCompilationErrorHandler::ReportErrors (Isolate * isolate, Handle< Script > script) const
Referenced by v8::Shell::ExecuteString(), v8::internal::anonymous_namespace{compiler.cc}::FailWithPreparedException(), and v8::internal::anonymous_namespace{liveedit.cc}::ParseScript().
ReportMessageAt() [1/4]
void v8::internal::PendingCompilationErrorHandler::ReportMessageAt (int start_position, int end_position, MessageTemplate message, const AstRawString * arg)
Definition at line 91 of file pending-compilation-error-handler.cc.
                                                                              {
  if (has_pending_error_ && end_position >= error_details_.start_pos()) return;
  has_pending_error_ = true;
  error_details_ = MessageDetails(start_position, end_position, message, arg);
}
References error_details_, has_pending_error_, and v8::internal::PendingCompilationErrorHandler::MessageDetails::start_pos().
ReportMessageAt() [2/4]
void v8::internal::PendingCompilationErrorHandler::ReportMessageAt (int start_position, int end_position, MessageTemplate message, const AstRawString * arg0, const AstRawString * arg1, const char * arg2)
Definition at line 114 of file pending-compilation-error-handler.cc.
                                                                          {
  if (has_pending_error_ && end_position >= error_details_.start_pos()) return;
  has_pending_error_ = true;
  error_details_ =
      MessageDetails(start_position, end_position, message, arg0, arg1, arg2);
}
References error_details_, has_pending_error_, and v8::internal::PendingCompilationErrorHandler::MessageDetails::start_pos().
ReportMessageAt() [3/4]
void v8::internal::PendingCompilationErrorHandler::ReportMessageAt (int start_position, int end_position, MessageTemplate message, const AstRawString * arg0, const char * arg1)
Definition at line 102 of file pending-compilation-error-handler.cc.
                                                                       {
  if (has_pending_error_ && end_position >= error_details_.start_pos()) return;
  has_pending_error_ = true;
  error_details_ =
      MessageDetails(start_position, end_position, message, arg0, arg1);
}
References error_details_, has_pending_error_, and v8::internal::PendingCompilationErrorHandler::MessageDetails::start_pos().
ReportMessageAt() [4/4]
void v8::internal::PendingCompilationErrorHandler::ReportMessageAt (int start_position, int end_position, MessageTemplate message, const char * arg = nullptr)
Definition at line 80 of file pending-compilation-error-handler.cc.
                                                                      {
  if (has_pending_error_ && end_position >= error_details_.start_pos()) return;
  has_pending_error_ = true;
  error_details_ = MessageDetails(start_position, end_position, message, arg);
}
References error_details_, has_pending_error_, and v8::internal::PendingCompilationErrorHandler::MessageDetails::start_pos().
Referenced by v8::internal::ClassScope::ResolvePrivateNames(), and v8::internal::SourceTextModuleDescriptor::Validate().
ReportWarningAt()
void v8::internal::PendingCompilationErrorHandler::ReportWarningAt (int start_position, int end_position, MessageTemplate message, const char * arg = nullptr)
Definition at line 124 of file pending-compilation-error-handler.cc.
                                                                      {
  warning_messages_.emplace_front(
      MessageDetails(start_position, end_position, message, arg));
}
References warning_messages_.
Referenced by v8::internal::anonymous_namespace{asm-js.cc}::ReportCompilationFailure().
ReportWarnings()
void v8::internal::PendingCompilationErrorHandler::ReportWarnings (Isolate * isolate, Handle< Script > script) const
Definition at line 144 of file pending-compilation-error-handler.cc.
                                                   {
  DCHECK(!has_pending_error());
  for (const MessageDetails& warning : warning_messages_) {
    MessageLocation location = warning.GetLocation(script);
    DirectHandle<String> argument = warning.ArgString(isolate, 0);
    DCHECK_LT(warning.ArgCount(), 2); // Arg1 is only used for errors.
    DirectHandle<JSMessageObject> message = MessageHandler::MakeMessageObject(
        isolate, warning.message(), &location, argument);
    message->set_error_level(v8::Isolate::kMessageWarning);
    MessageHandler::ReportMessage(isolate, &location, message);
  }
}
References v8::internal::DCHECK(), DCHECK_LT, has_pending_error(), v8::Isolate::kMessageWarning, v8::internal::MessageHandler::MakeMessageObject(), v8::internal::MessageHandler::ReportMessage(), v8::internal::script, and warning_messages_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation().
set_stack_overflow()
void v8::internal::PendingCompilationErrorHandler::set_stack_overflow () [inline]
Definition at line 53 of file pending-compilation-error-handler.h.
                            {
    has_pending_error_ = true;
    stack_overflow_ = true;
  }
References has_pending_error_, and stack_overflow_.
Referenced by v8::internal::ParserBase< Impl >::set_stack_overflow().
set_unidentifiable_error()
void v8::internal::PendingCompilationErrorHandler::set_unidentifiable_error () [inline]
Definition at line 76 of file pending-compilation-error-handler.h.
                                  {
    has_pending_error_ = true;
    unidentifiable_error_ = true;
  }
References has_pending_error_, and unidentifiable_error_.
Referenced by v8::internal::PreParser::ReportUnidentifiableError().
stack_overflow()
bool v8::internal::PendingCompilationErrorHandler::stack_overflow () const [inline]
Definition at line 51 of file pending-compilation-error-handler.h.
{ return stack_overflow_; }
References stack_overflow_.
Referenced by v8::internal::Parser::ParseREPLProgram(), PrepareErrors(), and v8::internal::ParserBase< Impl >::stack_overflow().
ThrowPendingError()
void v8::internal::PendingCompilationErrorHandler::ThrowPendingError (Isolate * isolate, Handle< Script > script) const [private]
Definition at line 186 of file pending-compilation-error-handler.cc.
                                                   {
  if (!has_pending_error_) return;
  MessageLocation location = error_details_.GetLocation(script);
  int num_args = 0;
  DirectHandle<Object> args[MessageDetails::kMaxArgumentCount];
  for (; num_args < MessageDetails::kMaxArgumentCount; ++num_args) {
    args[num_args] = error_details_.ArgString(isolate, num_args);
    if (args[num_args].is_null()) break;
  }
  isolate->debug()->OnCompileError(script);
  Factory* factory = isolate->factory();
  DirectHandle<JSObject> error = factory->NewSyntaxError(
      error_details_.message(), base::VectorOf(args, num_args));
  isolate->ThrowAt(error, &location);
}
References v8::base::args, v8::internal::PendingCompilationErrorHandler::MessageDetails::ArgString(), v8::internal::Isolate::debug(), error_details_, v8::internal::Isolate::factory(), v8::internal::PendingCompilationErrorHandler::MessageDetails::GetLocation(), has_pending_error_, v8::internal::PendingCompilationErrorHandler::MessageDetails::kMaxArgumentCount, v8::internal::PendingCompilationErrorHandler::MessageDetails::message(), v8::internal::Debug::OnCompileError(), v8::internal::script, v8::internal::Isolate::ThrowAt(), and v8::base::VectorOf().
Member Data Documentation
error_details_
MessageDetails v8::internal::PendingCompilationErrorHandler::error_details_ [private]
Definition at line 192 of file pending-compilation-error-handler.h.
Referenced by FormatErrorMessageForTest(), PrepareErrors(), ReportMessageAt(), and ThrowPendingError().
has_pending_error_
bool v8::internal::PendingCompilationErrorHandler::has_pending_error_ = false [private]
Definition at line 188 of file pending-compilation-error-handler.h.
Referenced by clear_unidentifiable_error(), has_pending_error(), ReportMessageAt(), set_stack_overflow(), set_unidentifiable_error(), and ThrowPendingError().
stack_overflow_
bool v8::internal::PendingCompilationErrorHandler::stack_overflow_ = false [private]
Definition at line 189 of file pending-compilation-error-handler.h.
Referenced by set_stack_overflow(), and stack_overflow().
unidentifiable_error_
bool v8::internal::PendingCompilationErrorHandler::unidentifiable_error_ = false [private]
Definition at line 190 of file pending-compilation-error-handler.h.
Referenced by clear_unidentifiable_error(), has_error_unidentifiable_by_preparser(), and set_unidentifiable_error().
warning_messages_
std::forward_list<MessageDetails> v8::internal::PendingCompilationErrorHandler::warning_messages_ [private]
Definition at line 194 of file pending-compilation-error-handler.h.
Referenced by has_pending_warnings(), PrepareWarnings(), ReportWarningAt(), and ReportWarnings().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/pending-compilation-error-handler.h
/mnt/V8SourceCode/src/parsing/pending-compilation-error-handler.cc