v8::internal::compiler::RegisterAllocationData::PhiMapValue Class Reference
#include <register-allocator.h>
Public Member Functions
PhiMapValue (PhiInstruction *phi, const InstructionBlock *block, Zone *zone)
const PhiInstruction * phi () const
const InstructionBlock * block () const
int assigned_register () const
void set_assigned_register (int register_code)
void UnsetAssignedRegister ()
void AddOperand (InstructionOperand *operand)
void CommitAssignment (const InstructionOperand &operand)
Private Attributes
PhiInstruction *const phi_
const InstructionBlock *const block_
ZoneVector< InstructionOperand * > incoming_operands_
int assigned_register_
Detailed Description
Definition at line 208 of file register-allocator.h.
Constructor & Destructor Documentation
PhiMapValue()
v8::internal::compiler::RegisterAllocationData::PhiMapValue::PhiMapValue (PhiInstruction * phi, const InstructionBlock * block, Zone * zone)
Definition at line 1150 of file register-allocator.cc.
    : phi_(phi),
      block_(block),
      incoming_operands_(zone),
      assigned_register_(kUnassignedRegister) {
  incoming_operands_.reserve(phi->operands().size());
}
References incoming_operands_, v8::internal::compiler::PhiInstruction::operands(), phi(), and v8::internal::ZoneVector< T >::size().
Member Function Documentation
AddOperand()
void v8::internal::compiler::RegisterAllocationData::PhiMapValue::AddOperand (InstructionOperand * operand)
Definition at line 1160 of file register-allocator.cc.
                                 {
  incoming_operands_.push_back(operand);
}
Referenced by v8::internal::compiler::ConstraintBuilder::ResolvePhis().
assigned_register()
int v8::internal::compiler::RegisterAllocationData::PhiMapValue::assigned_register () const [inline]
Definition at line 216 of file register-allocator.h.
{ return assigned_register_; }
References assigned_register_.
Referenced by v8::internal::compiler::UsePosition::HintRegister().
block()
const InstructionBlock* v8::internal::compiler::RegisterAllocationData::PhiMapValue::block () const [inline]
Definition at line 213 of file register-allocator.h.
{ return block_; }
References block_.
Referenced by v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
CommitAssignment()
void v8::internal::compiler::RegisterAllocationData::PhiMapValue::CommitAssignment (const InstructionOperand & operand)
Definition at line 1165 of file register-allocator.cc.
                                        {
  for (InstructionOperand* operand : incoming_operands_) {
    InstructionOperand::ReplaceWith(operand, &assigned);
  }
}
References v8::internal::compiler::InstructionOperand::ReplaceWith().
Referenced by v8::internal::compiler::OperandAssigner::CommitAssignment().
phi()
const PhiInstruction* v8::internal::compiler::RegisterAllocationData::PhiMapValue::phi () const [inline]
Definition at line 212 of file register-allocator.h.
{ return phi_; }
References phi_.
Referenced by PhiMapValue(), and v8::internal::compiler::LinearScanAllocator::TryReuseSpillForPhi().
set_assigned_register()
void v8::internal::compiler::RegisterAllocationData::PhiMapValue::set_assigned_register (int register_code) [inline]
Definition at line 217 of file register-allocator.h.
                                                  {
      DCHECK_EQ(assigned_register_, kUnassignedRegister);
      assigned_register_ = register_code;
    }
References assigned_register_, DCHECK_EQ, and v8::internal::compiler::kUnassignedRegister.
Referenced by v8::internal::compiler::LinearScanAllocator::SetLiveRangeAssignedRegister().
UnsetAssignedRegister()
void v8::internal::compiler::RegisterAllocationData::PhiMapValue::UnsetAssignedRegister () [inline]
Definition at line 221 of file register-allocator.h.
{ assigned_register_ = kUnassignedRegister; }
References assigned_register_, and v8::internal::compiler::kUnassignedRegister.
Member Data Documentation
assigned_register_
int v8::internal::compiler::RegisterAllocationData::PhiMapValue::assigned_register_ [private]
Definition at line 230 of file register-allocator.h.
Referenced by assigned_register(), set_assigned_register(), and UnsetAssignedRegister().
block_
const InstructionBlock* const v8::internal::compiler::RegisterAllocationData::PhiMapValue::block_ [private]
Definition at line 228 of file register-allocator.h.
Referenced by block().
incoming_operands_
ZoneVector<InstructionOperand*> v8::internal::compiler::RegisterAllocationData::PhiMapValue::incoming_operands_ [private]
Definition at line 229 of file register-allocator.h.
Referenced by PhiMapValue().
phi_
PhiInstruction* const v8::internal::compiler::RegisterAllocationData::PhiMapValue::phi_ [private]
Definition at line 227 of file register-allocator.h.
Referenced by phi().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h
/mnt/V8SourceCode/src/compiler/backend/register-allocator.cc