v8::internal::FixedDoubleArray Class Reference
#include <fixed-array.h>
Classes
class BodyDescriptor
Public Member Functions
double get_scalar (int index)
uint64_t get_representation (int index)
void set (int index, double value)
void set_the_hole (Isolate *isolate, int index)
void set_the_hole (int index)
bool is_the_hole (Isolate *isolate, int index)
bool is_the_hole (int index)
void MoveElements (Isolate *isolate, int dst_index, int src_index, int len, WriteBarrierMode)
void FillWithHoles (int from, int to)
Static Public Member Functions
template<class IsolateT >
static Handle< FixedArrayBase > New (IsolateT *isolate, int capacity, AllocationType allocation=AllocationType::kYoung)
static Handle< Object > get (Tagged< FixedDoubleArray > array, int index, Isolate *isolate)
Private Types
using Super = PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >
Additional Inherited Members
Detailed Description
Definition at line 455 of file fixed-array.h.
Member Typedef Documentation
Super
using v8::internal::FixedDoubleArray::Super = PrimitiveArrayBase<FixedDoubleArray, FixedDoubleArrayShape> [private]
Definition at line 457 of file fixed-array.h.
Member Function Documentation
FillWithHoles()
void v8::internal::FixedDoubleArray::FillWithHoles (int from, int to) [inline]
Definition at line 616 of file fixed-array-inl.h.
                                                     {
  for (int i = from; i < to; i++) {
    set_the_hole(i);
  }
}
References set_the_hole().
get()
Handle< Object > v8::internal::FixedDoubleArray::get (Tagged< FixedDoubleArray > array, int index, Isolate * isolate) [inline], [static]
Definition at line 559 of file fixed-array-inl.h.
                                                       {
  if (array->is_the_hole(index)) {
    return isolate->factory()->the_hole_value();
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
  } else if (array->is_undefined(index)) {
    return isolate->factory()->undefined_value();
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
  } else {
    return isolate->factory()->NewNumber(array->get_scalar(index));
  }
}
References v8::internal::Isolate::factory(), v8::internal::index, and v8::internal::FactoryBase< Impl >::NewNumber().
Referenced by v8::internal::anonymous_namespace{elements.cc}::CopyDoubleToObjectElements(), and v8::internal::anonymous_namespace{elements.cc}::FastDoubleElementsAccessor< Subclass, KindTraits >::GetImpl().
get_representation()
uint64_t v8::internal::FixedDoubleArray::get_representation (int index) [inline]
Definition at line 554 of file fixed-array-inl.h.
                                                       {
  DCHECK(IsInBounds(index));
  return values()[index].value_as_bits();
}
References v8::internal::DCHECK(), v8::internal::index, and v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::IsInBounds().
Referenced by is_the_hole().
get_scalar()
double v8::internal::FixedDoubleArray::get_scalar (int index) [inline]
Definition at line 549 of file fixed-array-inl.h.
                                             {
  DCHECK(!is_the_hole(index));
  return values()[index].value();
}
References v8::internal::DCHECK(), v8::internal::index, and is_the_hole().
is_the_hole() [1/2]
bool v8::internal::FixedDoubleArray::is_the_hole (int index) [inline]
Definition at line 605 of file fixed-array-inl.h.
                                            {
  return get_representation(index) == kHoleNanInt64;
}
References get_representation(), v8::internal::index, and v8::internal::kHoleNanInt64.
is_the_hole() [2/2]
bool v8::internal::FixedDoubleArray::is_the_hole (Isolate * isolate, int index) [inline]
Definition at line 601 of file fixed-array-inl.h.
                                                              {
  return is_the_hole(index);
}
References v8::internal::index.
Referenced by get_scalar(), and set().
MoveElements()
void v8::internal::FixedDoubleArray::MoveElements (Isolate * isolate, int dst_index, int src_index, int len, WriteBarrierMode mode) [inline]
Definition at line 609 of file fixed-array-inl.h.
                                                           {
  DCHECK_EQ(SKIP_WRITE_BARRIER, mode);
  MemMove(&values()[dst_index], &values()[src_index], len * kElementSize);
}
References DCHECK_EQ, v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::kElementSize, v8::internal::MemMove(), mode(), and v8::internal::SKIP_WRITE_BARRIER.
New()
template<class IsolateT >
Handle< FixedArrayBase > v8::internal::FixedDoubleArray::New (IsolateT * isolate, int capacity, AllocationType allocation = AllocationType::kYoung) [inline], [static]
Definition at line 509 of file fixed-array-inl.h.
                                                                        {
  if (V8_UNLIKELY(static_cast<unsigned>(length) > kMaxLength)) {
    FATAL("Fatal JavaScript invalid size error %d (see crbug.com/1201626)",
          length);
  } else if (V8_UNLIKELY(length == 0)) {
    return isolate->factory()->empty_fixed_array();
  }
  std::optional<DisallowGarbageCollection> no_gc;
  return Cast<FixedDoubleArray>(Allocate(isolate, length, &no_gc, allocation));
}
References v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::Allocate(), FATAL, v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::kMaxLength, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and V8_UNLIKELY.
Referenced by v8::internal::FactoryBase< Impl >::NewFixedDoubleArray().
set()
void v8::internal::FixedDoubleArray::set (int index, double value) [inline]
Definition at line 572 of file fixed-array-inl.h.
                                                  {
  if (std::isnan(value)) {
    value = std::numeric_limits<double>::quiet_NaN();
  }
  values()[index].set_value(value);
  DCHECK(!is_the_hole(index));
}
References v8::internal::DCHECK(), v8::internal::index, is_the_hole(), and v8::internal::value.
set_the_hole() [1/2]
void v8::internal::FixedDoubleArray::set_the_hole (int index) [inline]
Definition at line 596 of file fixed-array-inl.h.
                                             {
  DCHECK(IsInBounds(index));
  values()[index].set_value_as_bits(kHoleNanInt64);
}
References v8::internal::DCHECK(), v8::internal::index, v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::IsInBounds(), and v8::internal::kHoleNanInt64.
set_the_hole() [2/2]
void v8::internal::FixedDoubleArray::set_the_hole (Isolate * isolate, int index) [inline]
Definition at line 592 of file fixed-array-inl.h.
                                                               {
  set_the_hole(index);
}
References v8::internal::index.
Referenced by FillWithHoles().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h