v8::internal::compiler::InstructionSelector::LoadView Class Reference
#include <instruction-selector.h>
Public Member Functions
LoadView (turboshaft::Graph *graph, turboshaft::OpIndex node)
LoadRepresentation loaded_rep () const
turboshaft::MemoryRepresentation ts_loaded_rep () const
turboshaft::RegisterRepresentation ts_result_rep () const
bool is_protected (bool *traps_on_null) const
bool is_atomic () const
turboshaft::OpIndex base () const
turboshaft::OpIndex index () const
int32_t displacement () const
uint8_t element_size_log2 () const
operator turboshaft::OpIndex () const
Private Member Functions
turboshaft::LoadOp::Kind kind () const
Private Attributes
turboshaft::OpIndex node_
const turboshaft::LoadOp * load_ = nullptr
Detailed Description
Definition at line 759 of file instruction-selector.h.
Constructor & Destructor Documentation
LoadView()
v8::internal::compiler::InstructionSelector::LoadView::LoadView (turboshaft::Graph * graph, turboshaft::OpIndex node) [inline]
Definition at line 761 of file instruction-selector.h.
                                                             : node_(node) {
      switch (graph->Get(node_).opcode) {
        case turboshaft::Opcode::kLoad:
          load_ = &graph->Get(node_).Cast<turboshaft::LoadOp>();
          break;
#if V8_ENABLE_WEBASSEMBLY
        case turboshaft::Opcode::kSimd128LoadTransform:
          load_transform_ =
              &graph->Get(node_).Cast<turboshaft::Simd128LoadTransformOp>();
          break;
#if V8_ENABLE_WASM_SIMD256_REVEC
        case turboshaft::Opcode::kSimd256LoadTransform:
          load_transform256_ =
              &graph->Get(node_).Cast<turboshaft::Simd256LoadTransformOp>();
          break;
#endif // V8_ENABLE_WASM_SIMD256_REVEC
#endif // V8_ENABLE_WEBASSEMBLY
        default:
          UNREACHABLE();
      }
    }
References graph(), and v8::internal::UNREACHABLE().
Member Function Documentation
base()
turboshaft::OpIndex v8::internal::compiler::InstructionSelector::LoadView::base () const [inline]
Definition at line 818 of file instruction-selector.h.
                                   {
      if (load_) return load_->base();
#if V8_ENABLE_WEBASSEMBLY
      if (load_transform_) return load_transform_->base();
#if V8_ENABLE_WASM_SIMD256_REVEC
      if (load_transform256_) return load_transform256_->base();
#endif // V8_ENABLE_WASM_SIMD256_REVEC
#endif
      UNREACHABLE();
    }
References v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::InstructionSelector::VisitLoad().
displacement()
int32_t v8::internal::compiler::InstructionSelector::LoadView::displacement () const [inline]
Definition at line 838 of file instruction-selector.h.
                                 {
      static_assert(
          std::is_same_v<decltype(turboshaft::StoreOp::offset), int32_t>);
      if (load_) {
        int32_t offset = load_->offset;
        if (load_->kind.tagged_base) {
          CHECK_GE(offset,
                   std::numeric_limits<int32_t>::min() + kHeapObjectTag);
          offset -= kHeapObjectTag;
        }
        return offset;
#if V8_ENABLE_WEBASSEMBLY
      } else if (load_transform_) {
        int32_t offset = load_transform_->offset;
        DCHECK(!load_transform_->load_kind.tagged_base);
        return offset;
#if V8_ENABLE_WASM_SIMD256_REVEC
      } else if (load_transform256_) {
        int32_t offset = load_transform256_->offset;
        DCHECK(!load_transform256_->load_kind.tagged_base);
        return offset;
#endif // V8_ENABLE_WASM_SIMD256_REVEC
#endif
      }
      UNREACHABLE();
    }
References CHECK_GE, v8::internal::DCHECK(), v8::internal::kHeapObjectTag, v8::internal::compiler::turboshaft::StoreOp::offset, and v8::internal::UNREACHABLE().
element_size_log2()
uint8_t v8::internal::compiler::InstructionSelector::LoadView::element_size_log2 () const [inline]
Definition at line 864 of file instruction-selector.h.
                                      {
      static_assert(
          std::is_same_v<decltype(turboshaft::StoreOp::element_size_log2),
                         uint8_t>);
      if (load_) return load_->element_size_log2;
#if V8_ENABLE_WEBASSEMBLY
      if (load_transform_) return 0;
#if V8_ENABLE_WASM_SIMD256_REVEC
      if (load_transform256_) return 0;
#endif // V8_ENABLE_WASM_SIMD256_REVEC
#endif
      UNREACHABLE();
    }
References v8::internal::compiler::turboshaft::StoreOp::element_size_log2, and v8::internal::UNREACHABLE().
index()
turboshaft::OpIndex v8::internal::compiler::InstructionSelector::LoadView::index () const [inline]
Definition at line 828 of file instruction-selector.h.
                                    {
      if (load_) return load_->index().value_or_invalid();
#if V8_ENABLE_WEBASSEMBLY
      if (load_transform_) return load_transform_->index();
#if V8_ENABLE_WASM_SIMD256_REVEC
      if (load_transform256_) return load_transform256_->index();
#endif // V8_ENABLE_WASM_SIMD256_REVEC
#endif
      UNREACHABLE();
    }
References v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::InstructionSelector::VisitLoad().
is_atomic()
bool v8::internal::compiler::InstructionSelector::LoadView::is_atomic () const [inline]
Definition at line 816 of file instruction-selector.h.
{ return kind().is_atomic; }
is_protected()
bool v8::internal::compiler::InstructionSelector::LoadView::is_protected (bool * traps_on_null) const [inline]
Definition at line 794 of file instruction-selector.h.
                                                 {
      if (kind().with_trap_handler) {
        if (load_) {
          *traps_on_null = load_->kind.trap_on_null;
#if V8_ENABLE_WEBASSEMBLY
        } else {
#if V8_ENABLE_WASM_SIMD256_REVEC
          DCHECK(
              (load_transform_ && !load_transform_->load_kind.trap_on_null) ||
              (load_transform256_ &&
               !load_transform256_->load_kind.trap_on_null));
#else
          DCHECK(load_transform_);
          DCHECK(!load_transform_->load_kind.trap_on_null);
#endif // V8_ENABLE_WASM_SIMD256_REVEC
          *traps_on_null = false;
#endif // V8_ENABLE_WEBASSEMBLY
        }
        return true;
      }
      return false;
    }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::InstructionSelector::IsProtectedLoad().
kind()
turboshaft::LoadOp::Kind v8::internal::compiler::InstructionSelector::LoadView::kind () const [inline], [private]
Definition at line 881 of file instruction-selector.h.
                                      {
      if (load_) return load_->kind;
#if V8_ENABLE_WEBASSEMBLY
      if (load_transform_) return load_transform_->load_kind;
#if V8_ENABLE_WASM_SIMD256_REVEC
      if (load_transform256_) return load_transform256_->load_kind;
#endif // V8_ENABLE_WASM_SIMD256_REVEC
#endif
      UNREACHABLE();
    }
References v8::internal::UNREACHABLE().
loaded_rep()
LoadRepresentation v8::internal::compiler::InstructionSelector::LoadView::loaded_rep () const [inline]
Definition at line 782 of file instruction-selector.h.
                                          {
      DCHECK_NOT_NULL(load_);
      return load_->machine_type();
    }
References DCHECK_NOT_NULL.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsCompressed(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result(), and v8::internal::compiler::InstructionSelector::VisitLoad().
operator turboshaft::OpIndex()
v8::internal::compiler::InstructionSelector::LoadView::operator turboshaft::OpIndex () const [inline]
Definition at line 878 of file instruction-selector.h.
{ return node_; }
ts_loaded_rep()
turboshaft::MemoryRepresentation v8::internal::compiler::InstructionSelector::LoadView::ts_loaded_rep () const [inline]
Definition at line 786 of file instruction-selector.h.
                                                         {
      DCHECK_NOT_NULL(load_);
      return load_->loaded_rep;
    }
References DCHECK_NOT_NULL.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands().
ts_result_rep()
turboshaft::RegisterRepresentation v8::internal::compiler::InstructionSelector::LoadView::ts_result_rep () const [inline]
Definition at line 790 of file instruction-selector.h.
                                                           {
      DCHECK_NOT_NULL(load_);
      return load_->result_rep;
    }
References DCHECK_NOT_NULL.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands().
Member Data Documentation
load_
const turboshaft::LoadOp* v8::internal::compiler::InstructionSelector::LoadView::load_ = nullptr [private]
Definition at line 893 of file instruction-selector.h.
node_
turboshaft::OpIndex v8::internal::compiler::InstructionSelector::LoadView::node_ [private]
Definition at line 892 of file instruction-selector.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction-selector.h