v8::internal::FactoryBase< Impl > Class Template Reference
#include <factory-base.h>
Public Member Functions
Handle< Code > NewCode (const NewCodeOptions &options)
DirectHandle< CodeWrapper > NewCodeWrapper ()
Handle< Boolean > ToBoolean (bool value)
template<AllocationType allocation = AllocationType::kYoung>
Handle< Number > NewNumber (double value)
template<AllocationType allocation = AllocationType::kYoung>
Handle< Number > NewNumberFromInt (int32_t value)
template<AllocationType allocation = AllocationType::kYoung>
Handle< Number > NewNumberFromUint (uint32_t value)
template<AllocationType allocation = AllocationType::kYoung>
DirectHandle< Number > NewNumberFromSize (size_t value)
template<AllocationType allocation = AllocationType::kYoung>
DirectHandle< Number > NewNumberFromInt64 (int64_t value)
template<AllocationType allocation = AllocationType::kYoung>
Handle< HeapNumber > NewHeapNumber (double value)
template<AllocationType allocation = AllocationType::kYoung>
Handle< HeapNumber > NewHeapNumberFromBits (uint64_t bits)
template<AllocationType allocation = AllocationType::kYoung>
Handle< HeapNumber > NewHeapNumberWithHoleNaN ()
template<AllocationType allocation = AllocationType::kYoung>
Handle< HeapNumber > NewHeapInt32 (int32_t value)
template<AllocationType allocation>
Handle< HeapNumber > NewHeapNumber ()
Handle< Struct > NewStruct (InstanceType type, AllocationType allocation=AllocationType::kYoung)
Handle< AccessorPair > NewAccessorPair ()
Handle< FixedArray > NewFixedArray (int length, AllocationType allocation=AllocationType::kYoung)
Handle< TrustedFixedArray > NewTrustedFixedArray (int length, AllocationType allocation=AllocationType::kTrusted)
Handle< ProtectedFixedArray > NewProtectedFixedArray (int length, bool shared=false)
Handle< FixedArray > NewFixedArrayWithMap (DirectHandle< Map > map, int length, AllocationType allocation=AllocationType::kYoung)
Handle< FixedArray > NewFixedArrayWithHoles (int length, AllocationType allocation=AllocationType::kYoung)
DirectHandle< FixedArray > NewFixedArrayWithZeroes (int length, AllocationType allocation=AllocationType::kYoung)
Handle< FixedArrayBase > NewFixedDoubleArray (int length, AllocationType allocation=AllocationType::kYoung)
Handle< WeakFixedArray > NewWeakFixedArrayWithMap (Tagged< Map > map, int length, AllocationType allocation=AllocationType::kYoung)
Handle< WeakFixedArray > NewWeakFixedArray (int length, AllocationType allocation=AllocationType::kYoung)
Handle< TrustedWeakFixedArray > NewTrustedWeakFixedArray (int length)
Handle< ProtectedWeakFixedArray > NewProtectedWeakFixedArray (int length)
Handle< ByteArray > NewByteArray (int length, AllocationType allocation=AllocationType::kYoung)
Handle< TrustedByteArray > NewTrustedByteArray (int length, AllocationType allocation_type=AllocationType::kTrusted)
DirectHandle< DeoptimizationLiteralArray > NewDeoptimizationLiteralArray (int length)
DirectHandle< DeoptimizationFrameTranslation > NewDeoptimizationFrameTranslation (int length)
Handle< BytecodeArray > NewBytecodeArray (int length, const uint8_t *raw_bytecodes, int frame_size, uint16_t parameter_count, uint16_t max_arguments, DirectHandle< TrustedFixedArray > constant_pool, DirectHandle< TrustedByteArray > handler_table, AllocationType allocation=AllocationType::kTrusted)
DirectHandle< BytecodeWrapper > NewBytecodeWrapper (AllocationType allocation=AllocationType::kOld)
Handle< ObjectBoilerplateDescription > NewObjectBoilerplateDescription (int boilerplate, int all_properties, int index_keys, bool has_seen_proto)
Handle< ArrayBoilerplateDescription > NewArrayBoilerplateDescription (ElementsKind elements_kind, DirectHandle< FixedArrayBase > constant_values)
DirectHandle< RegExpDataWrapper > NewRegExpDataWrapper ()
DirectHandle< RegExpBoilerplateDescription > NewRegExpBoilerplateDescription (DirectHandle< RegExpData > data, DirectHandle< String > source, Tagged< Smi > flags)
Handle< TemplateObjectDescription > NewTemplateObjectDescription (DirectHandle< FixedArray > raw_strings, DirectHandle< FixedArray > cooked_strings)
Handle< Script > NewScript (DirectHandle< UnionOf< String, Undefined >> source, ScriptEventType event_type=ScriptEventType::kCreate)
Handle< Script > NewScriptWithId (DirectHandle< UnionOf< String, Undefined >> source, int script_id, ScriptEventType event_type=ScriptEventType::kCreate)
DirectHandle< SloppyArgumentsElements > NewSloppyArgumentsElements (int length, DirectHandle< Context > context, DirectHandle< FixedArray > arguments, AllocationType allocation=AllocationType::kYoung)
DirectHandle< ArrayList > NewArrayList (int size, AllocationType allocation=AllocationType::kYoung)
Handle< SharedFunctionInfo > NewSharedFunctionInfoForLiteral (FunctionLiteral *literal, DirectHandle< Script > script, bool is_toplevel)
Handle< SharedFunctionInfo > CloneSharedFunctionInfo (DirectHandle< SharedFunctionInfo > other)
DirectHandle< SharedFunctionInfoWrapper > NewSharedFunctionInfoWrapper (DirectHandle< SharedFunctionInfo > sfi)
Handle< PreparseData > NewPreparseData (int data_length, int children_length)
DirectHandle< UncompiledDataWithoutPreparseData > NewUncompiledDataWithoutPreparseData (Handle< String > inferred_name, int32_t start_position, int32_t end_position)
DirectHandle< UncompiledDataWithPreparseData > NewUncompiledDataWithPreparseData (Handle< String > inferred_name, int32_t start_position, int32_t end_position, Handle< PreparseData >)
DirectHandle< UncompiledDataWithoutPreparseDataWithJob > NewUncompiledDataWithoutPreparseDataWithJob (Handle< String > inferred_name, int32_t start_position, int32_t end_position)
DirectHandle< UncompiledDataWithPreparseDataAndJob > NewUncompiledDataWithPreparseDataAndJob (Handle< String > inferred_name, int32_t start_position, int32_t end_position, Handle< PreparseData >)
Handle< FeedbackMetadata > NewFeedbackMetadata (int slot_count, int create_closure_slot_count, AllocationType allocation=AllocationType::kOld)
Handle< CoverageInfo > NewCoverageInfo (const ZoneVector< SourceRange > &slots)
Handle< String > InternalizeString (base::Vector< const uint8_t > string, bool convert_encoding=false)
Handle< String > InternalizeString (base::Vector< const uint16_t > string, bool convert_encoding=false)
template<class StringTableKey >
Handle< String > InternalizeStringWithKey (StringTableKey *key)
Handle< SeqOneByteString > NewOneByteInternalizedString (base::Vector< const uint8_t > str, uint32_t raw_hash_field)
Handle< SeqTwoByteString > NewTwoByteInternalizedString (base::Vector< const base::uc16 > str, uint32_t raw_hash_field)
DirectHandle< SeqOneByteString > NewOneByteInternalizedStringFromTwoByte (base::Vector< const base::uc16 > str, uint32_t raw_hash_field)
Handle< SeqOneByteString > AllocateRawOneByteInternalizedString (int length, uint32_t raw_hash_field)
Handle< SeqTwoByteString > AllocateRawTwoByteInternalizedString (int length, uint32_t raw_hash_field)
Handle< String > LookupSingleCharacterStringFromCode (uint16_t code)
MaybeHandle< String > NewStringFromOneByte (base::Vector< const uint8_t > string, AllocationType allocation=AllocationType::kYoung)
Handle< String > NewStringFromAsciiChecked (const char *str, AllocationType allocation=AllocationType::kYoung)
Handle< String > NewStringFromAsciiChecked (std::string_view str, AllocationType allocation=AllocationType::kYoung)
V8_WARN_UNUSED_RESULT MaybeHandle< SeqOneByteString > NewRawOneByteString (int length, AllocationType allocation=AllocationType::kYoung, AllocationHint hint=AllocationHint())
V8_WARN_UNUSED_RESULT MaybeHandle< SeqTwoByteString > NewRawTwoByteString (int length, AllocationType allocation=AllocationType::kYoung, AllocationHint hint=AllocationHint())
template<template< typename > typename HandleType>
requires(std::is_convertible_v< HandleType< String >, DirectHandle< String >>) V8_WARN_UNUSED_RESULT HandleType< String > V8_WARN_UNUSED_RESULT Handle< String > NewConsString (DirectHandle< String > left, DirectHandle< String > right, int length, bool one_byte, AllocationType allocation=AllocationType::kYoung)
V8_WARN_UNUSED_RESULT Handle< String > NumberToString (DirectHandle< Object > number, NumberCacheMode mode=NumberCacheMode::kBoth)
V8_WARN_UNUSED_RESULT Handle< String > DoubleToString (double value, bool canonicalize=true, NumberCacheMode mode=NumberCacheMode::kBoth)
V8_WARN_UNUSED_RESULT Handle< String > SmiToString (Tagged< Smi > number, NumberCacheMode mode=NumberCacheMode::kBoth)
V8_WARN_UNUSED_RESULT MaybeHandle< SeqOneByteString > NewRawSharedOneByteString (int length)
V8_WARN_UNUSED_RESULT MaybeHandle< SeqTwoByteString > NewRawSharedTwoByteString (int length)
Handle< FreshlyAllocatedBigInt > NewBigInt (uint32_t length, AllocationType allocation=AllocationType::kYoung)
Handle< ScopeInfo > NewScopeInfo (int length, AllocationType type=AllocationType::kOld)
DirectHandle< SourceTextModuleInfo > NewSourceTextModuleInfo ()
Handle< DescriptorArray > NewDescriptorArray (int number_of_descriptors, int slack=0, AllocationType allocation=AllocationType::kYoung)
Handle< ClassPositions > NewClassPositions (int start, int end)
Handle< SwissNameDictionary > NewSwissNameDictionary (int at_least_space_for=kSwissNameDictionaryInitialCapacity, AllocationType allocation=AllocationType::kYoung)
Handle< SwissNameDictionary > NewSwissNameDictionaryWithCapacity (int capacity, AllocationType allocation)
DirectHandle< FunctionTemplateRareData > NewFunctionTemplateRareData ()
MaybeDirectHandle< Map > GetInPlaceInternalizedStringMap (Tagged< Map > from_string_map)
AllocationType RefineAllocationTypeForInPlaceInternalizableString (AllocationType allocation, Tagged< Map > string_map)
template<typename Impl >
Handle< String > NewConsString (DirectHandle< String > left, DirectHandle< String > right, int length, bool one_byte, AllocationType allocation)
Protected Member Functions
Tagged< HeapObject > AllocateRawArray (int size, AllocationType allocation)
Tagged< HeapObject > AllocateRawFixedArray (int length, AllocationType allocation)
Tagged< HeapObject > AllocateRawWeakArrayList (int length, AllocationType allocation)
template<typename StructType >
Tagged< StructType > NewStructInternal (InstanceType type, AllocationType allocation)
Tagged< Struct > NewStructInternal (ReadOnlyRoots roots, Tagged< Map > map, int size, AllocationType allocation)
Tagged< HeapObject > AllocateRawWithImmortalMap (int size, AllocationType allocation, Tagged< Map > map, AllocationAlignment alignment=kTaggedAligned, AllocationHint hint=AllocationHint())
Tagged< HeapObject > NewWithImmortalMap (Tagged< Map > map, AllocationType allocation)
Handle< FixedArray > NewFixedArrayWithFiller (DirectHandle< Map > map, int length, DirectHandle< HeapObject > filler, AllocationType allocation)
Handle< SharedFunctionInfo > NewSharedFunctionInfo (AllocationType allocation)
Handle< SharedFunctionInfo > NewSharedFunctionInfo (MaybeDirectHandle< String > maybe_name, MaybeDirectHandle< HeapObject > maybe_function_data, Builtin builtin, int len, AdaptArguments adapt, FunctionKind kind=FunctionKind::kNormalFunction)
Handle< String > MakeOrFindTwoCharacterString (uint16_t c1, uint16_t c2)
template<typename SeqStringT >
MaybeHandle< SeqStringT > NewRawStringWithMap (int length, Tagged< Map > map, AllocationType allocation, AllocationHint hint=AllocationHint())
Static Protected Attributes
static constexpr int kNumberToStringBufferSize = 32
Private Member Functions
Impl * impl ()
auto isolate ()
ReadOnlyRoots read_only_roots ()
Tagged< HeapObject > AllocateRaw (int size, AllocationType allocation, AllocationAlignment alignment=kTaggedAligned, AllocationHint hint=AllocationHint())
Private Attributes
friend TorqueGeneratedFactory< Impl >
Friends
template<class Derived , class Shape , class Super >
class TaggedArrayBase
template<class Derived , class Shape , class Super >
class PrimitiveArrayBase
class DoubleStringCache
Detailed Description
template<typename Impl>
class v8::internal::FactoryBase< Impl >
Definition at line 102 of file factory-base.h.
Member Function Documentation
AllocateRaw()
template<typename Impl >
Tagged< HeapObject > v8::internal::FactoryBase< Impl >::AllocateRaw (int size, AllocationType allocation, AllocationAlignment alignment = kTaggedAligned, AllocationHint hint = AllocationHint()) [private]
Definition at line 1336 of file factory-base.cc.
                                                                       {
  return impl()->AllocateRaw(size, allocation, alignment, hint);
}
References wasm::impl(), and size().
AllocateRawArray()
template<typename Impl >
Tagged< HeapObject > v8::internal::FactoryBase< Impl >::AllocateRawArray (int size, AllocationType allocation) [protected]
Definition at line 1282 of file factory-base.cc.
                                         {
  Tagged<HeapObject> result = AllocateRaw(size, allocation);
  if ((size >
       isolate()->heap()->AsHeap()->MaxRegularHeapObjectSize(allocation)) &&
      v8_flags.use_marking_progress_bar) {
    LargePageMetadata::FromHeapObject(result)
        ->marking_progress_tracker()
        .Enable(size);
  }
  return result;
}
References v8::internal::maglev::anonymous_namespace{maglev-assembler-arm.cc}::AllocateRaw(), v8::internal::MarkingProgressTracker::Enable(), v8::internal::LargePageMetadata::FromHeapObject(), heap(), v8::internal::MutablePageMetadata::marking_progress_tracker(), v8::base::internal::result, size(), and v8::internal::v8_flags.
AllocateRawFixedArray()
template<typename Impl >
Tagged< HeapObject > v8::internal::FactoryBase< Impl >::AllocateRawFixedArray (int length, AllocationType allocation) [protected]
Definition at line 1296 of file factory-base.cc.
                                           {
  if (length < 0 || length > FixedArray::kMaxLength) {
    FATAL("Fatal JavaScript invalid size error %d", length);
    UNREACHABLE();
  }
  return AllocateRawArray(FixedArray::SizeFor(length), allocation);
}
References FATAL, v8::internal::FixedArray::kMaxLength, v8::internal::length, v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::SizeFor(), and v8::internal::UNREACHABLE().
AllocateRawOneByteInternalizedString()
template<typename Impl >
Handle< SeqOneByteString > v8::internal::FactoryBase< Impl >::AllocateRawOneByteInternalizedString (int length, uint32_t raw_hash_field)
Definition at line 1235 of file factory-base.cc.
                                         {
  CHECK_GE(String::kMaxLength, length);
  // The canonical empty_string is the only zero-length string we allow.
  DCHECK_IMPLIES(length == 0, !impl()->EmptyStringRootIsInitialized());
  Tagged<Map> map = read_only_roots().internalized_one_byte_string_map();
  const int size = SeqOneByteString::SizeFor(length);
  const AllocationType allocation =
      RefineAllocationTypeForInPlaceInternalizableString(
          impl()->CanAllocateInReadOnlySpace() ? AllocationType::kReadOnly
                                               : AllocationType::kOld,
          map);
  Tagged<HeapObject> result = AllocateRawWithImmortalMap(size, allocation, map);
  Tagged<SeqOneByteString> answer = Cast<SeqOneByteString>(result);
  DisallowGarbageCollection no_gc;
  answer->clear_padding_destructively(length);
  answer->set_length(length);
  answer->set_raw_hash_field(raw_hash_field);
  DCHECK_EQ(size, answer->Size());
  return handle(answer, isolate());
}
References CHECK_GE, DCHECK_EQ, DCHECK_IMPLIES, v8::internal::handle(), wasm::impl(), v8::internal::String::kMaxLength, v8::internal::kOld, v8::internal::kReadOnly, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, size(), and v8::internal::SeqOneByteString::SizeFor().
Referenced by v8::internal::SeqSubStringKey< SeqString >::PrepareForInsertion().
AllocateRawTwoByteInternalizedString()
template<typename Impl >
Handle< SeqTwoByteString > v8::internal::FactoryBase< Impl >::AllocateRawTwoByteInternalizedString (int length, uint32_t raw_hash_field)
Definition at line 1260 of file factory-base.cc.
                                         {
  CHECK_GE(String::kMaxLength, length);
  DCHECK_NE(0, length); // Use Heap::empty_string() instead.
  Tagged<Map> map = read_only_roots().internalized_two_byte_string_map();
  int size = SeqTwoByteString::SizeFor(length);
  Tagged<SeqTwoByteString> answer =
      Cast<SeqTwoByteString>(AllocateRawWithImmortalMap(
          size,
          RefineAllocationTypeForInPlaceInternalizableString(
              AllocationType::kOld, map),
          map));
  DisallowGarbageCollection no_gc;
  answer->clear_padding_destructively(length);
  answer->set_length(length);
  answer->set_raw_hash_field(raw_hash_field);
  DCHECK_EQ(size, answer->Size());
  return handle(answer, isolate());
}
References CHECK_GE, DCHECK_EQ, DCHECK_NE, v8::internal::handle(), v8::internal::String::kMaxLength, v8::internal::kOld, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), and v8::internal::SeqTwoByteString::SizeFor().
Referenced by v8::internal::SeqSubStringKey< SeqString >::PrepareForInsertion().
AllocateRawWeakArrayList()
template<typename Impl >
Tagged< HeapObject > v8::internal::FactoryBase< Impl >::AllocateRawWeakArrayList (int length, AllocationType allocation) [protected]
Definition at line 1306 of file factory-base.cc.
                                             {
  if (capacity < 0 || capacity > WeakArrayList::kMaxCapacity) {
    FATAL("Fatal JavaScript invalid size error %d", capacity);
    UNREACHABLE();
  }
  return AllocateRawArray(WeakArrayList::SizeForCapacity(capacity), allocation);
}
References FATAL, v8::internal::WeakArrayList::kMaxCapacity, v8::internal::WeakArrayList::SizeForCapacity(), and v8::internal::UNREACHABLE().
AllocateRawWithImmortalMap()
template<typename Impl >
Tagged< HeapObject > v8::internal::FactoryBase< Impl >::AllocateRawWithImmortalMap (int size, AllocationType allocation, Tagged< Map > map, AllocationAlignment alignment = kTaggedAligned, AllocationHint hint = AllocationHint()) [protected]
Definition at line 1322 of file factory-base.cc.
                                                        {
  // TODO(delphick): Potentially you could also pass an immortal immovable Map
  // from OLD_SPACE here, like external_map or message_object_map, but currently
  // no one does so this check is sufficient.
  DCHECK(ReadOnlyHeap::Contains(map));
  Tagged<HeapObject> result = AllocateRaw(size, allocation, alignment, hint);
  DisallowGarbageCollection no_gc;
  result->set_map_after_allocation(isolate(), map, SKIP_WRITE_BARRIER);
  return result;
}
References v8::internal::maglev::anonymous_namespace{maglev-assembler-arm.cc}::AllocateRaw(), v8::internal::ReadOnlyHeap::Contains(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, size(), and v8::internal::SKIP_WRITE_BARRIER.
CloneSharedFunctionInfo()
template<typename Impl >
Handle< SharedFunctionInfo > v8::internal::FactoryBase< Impl >::CloneSharedFunctionInfo (DirectHandle< SharedFunctionInfo > other)
Definition at line 472 of file factory-base.cc.
                                            {
  Tagged<Map> map = read_only_roots().shared_function_info_map();
  Tagged<SharedFunctionInfo> shared =
      Cast<SharedFunctionInfo>(NewWithImmortalMap(map, AllocationType::kOld));
  DisallowGarbageCollection no_gc;
  shared->clear_padding();
  shared->CopyFrom(*other, isolate());
  return handle(shared, isolate());
}
References v8::internal::handle(), v8::internal::kOld, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::BackgroundCompileTask::Run().
DoubleToString()
template<typename Impl >
Handle< String > v8::internal::FactoryBase< Impl >::DoubleToString (double value, bool canonicalize = true, NumberCacheMode mode = NumberCacheMode::kBoth)
Definition at line 1035 of file factory-base.cc.
                                                                       {
  if (canonicalize) {
    // Try to canonicalize doubles.
    int smi_value;
    if (DoubleToSmiInteger(value, &smi_value)) {
      return SmiToString(Smi::FromInt(smi_value), mode);
    }
  }
  // LocalFactory does not have access to number string cache, only
  // main thread Factory does (since it's a mutable root).
  constexpr bool kCanUseCache = std::is_same_v<Impl, Factory>;
  InternalIndex entry = InternalIndex::NotFound();
  uint64_t value_bits = 0;
  if constexpr (kCanUseCache) {
    if (mode != NumberCacheMode::kIgnore) {
      value_bits = base::bit_cast<uint64_t>(value);
      entry = DoubleStringCache::GetEntryFor(isolate(), value_bits);
    }
    if (mode == NumberCacheMode::kBoth) {
      Handle<Object> cached =
          DoubleStringCache::Get(isolate(), entry, value_bits);
      if (!IsUndefined(*cached, isolate())) return Cast<String>(cached);
    }
  }
  Handle<String> result;
  if (value == 0) {
    result = zero_string();
  } else if (std::isnan(value)) {
    result = NaN_string();
  } else {
    char arr[kNumberToStringBufferSize];
    base::Vector<char> buffer(arr, arraysize(arr));
    std::string_view string = DoubleToStringView(value, buffer);
    result = StringViewToString(this, string, mode);
  }
  if constexpr (kCanUseCache) {
    if (mode != NumberCacheMode::kIgnore) {
      DoubleStringCache::Set(isolate(), entry, value_bits, result);
    }
  }
  return result;
}
References arraysize, v8::internal::DoubleToSmiInteger(), v8::internal::DoubleToStringView(), v8::internal::Smi::FromInt(), v8::internal::DoubleStringCache::Get(), v8::internal::DoubleStringCache::GetEntryFor(), v8::internal::kBoth, v8::internal::kIgnore, mode(), v8::internal::InternalIndex::NotFound(), v8::base::internal::result, v8::internal::DoubleStringCache::Set(), v8::internal::anonymous_namespace{factory-base.cc}::StringViewToString(), and v8::internal::value.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::CreateStringConstant(), v8::internal::PropertyKey::PropertyKey(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString().
GetInPlaceInternalizedStringMap()
template<typename Impl >
MaybeDirectHandle< Map > v8::internal::FactoryBase< Impl >::GetInPlaceInternalizedStringMap (Tagged< Map > from_string_map)
Definition at line 1395 of file factory-base.cc.
                                 {
  InstanceType instance_type = from_string_map->instance_type();
  MaybeDirectHandle<Map> map;
  switch (instance_type) {
    case SEQ_TWO_BYTE_STRING_TYPE:
    case SHARED_SEQ_TWO_BYTE_STRING_TYPE:
      map = internalized_two_byte_string_map();
      break;
    case SEQ_ONE_BYTE_STRING_TYPE:
    case SHARED_SEQ_ONE_BYTE_STRING_TYPE:
      map = internalized_one_byte_string_map();
      break;
    case SHARED_EXTERNAL_TWO_BYTE_STRING_TYPE:
    case EXTERNAL_TWO_BYTE_STRING_TYPE:
      map = external_internalized_two_byte_string_map();
      break;
    case SHARED_EXTERNAL_ONE_BYTE_STRING_TYPE:
    case EXTERNAL_ONE_BYTE_STRING_TYPE:
      map = external_internalized_one_byte_string_map();
      break;
    default:
      break;
  }
  DCHECK_EQ(!map.is_null(), String::IsInPlaceInternalizable(instance_type));
  return map;
}
References DCHECK_EQ, v8::internal::EXTERNAL_ONE_BYTE_STRING_TYPE, v8::internal::EXTERNAL_TWO_BYTE_STRING_TYPE, v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::String::IsInPlaceInternalizable(), v8::internal::SEQ_ONE_BYTE_STRING_TYPE, v8::internal::SEQ_TWO_BYTE_STRING_TYPE, v8::internal::SHARED_EXTERNAL_ONE_BYTE_STRING_TYPE, v8::internal::SHARED_EXTERNAL_TWO_BYTE_STRING_TYPE, v8::internal::SHARED_SEQ_ONE_BYTE_STRING_TYPE, and v8::internal::SHARED_SEQ_TWO_BYTE_STRING_TYPE.
impl()
template<typename Impl >
Impl* v8::internal::FactoryBase< Impl >::impl () [inline], [private]
Definition at line 454 of file factory-base.h.
{ return static_cast<Impl*>(this); }
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::Impl().
InternalizeString() [1/2]
template<typename Impl >
Handle< String > v8::internal::FactoryBase< Impl >::InternalizeString (base::Vector< const uint16_t > string, bool convert_encoding = false)
Definition at line 763 of file factory-base.cc.
                                                              {
  SequentialStringKey<uint16_t> key(string, HashSeed(read_only_roots()),
                                    convert_encoding);
  return InternalizeStringWithKey(&key);
}
References v8::internal::HashSeed(), and v8::internal::key.
InternalizeString() [2/2]
template<typename Impl >
Handle<String> v8::internal::FactoryBase< Impl >::InternalizeString (base::Vector< const uint8_t > string, bool convert_encoding = false)
InternalizeStringWithKey()
template<typename Impl >
template<class StringTableKey >
Handle< String > v8::internal::FactoryBase< Impl >::InternalizeStringWithKey (StringTableKey * key)
Definition at line 728 of file factory-base.cc.
                         {
  return indirect_handle(isolate()->string_table()->LookupKey(isolate(), key),
                         isolate());
}
References v8::internal::indirect_handle(), and v8::internal::key.
isolate()
template<typename Impl >
auto v8::internal::FactoryBase< Impl >::isolate () [inline], [private]
Definition at line 455 of file factory-base.h.
{ return impl()->isolate(); }
References wasm::impl().
LookupSingleCharacterStringFromCode()
template<typename Impl >
Handle< String > v8::internal::FactoryBase< Impl >::LookupSingleCharacterStringFromCode (uint16_t code)
Definition at line 976 of file factory-base.cc.
                   {
  if (code <= String::kMaxOneByteCharCode) {
    return Cast<String>(
        isolate()->root_handle(RootsTable::SingleCharacterStringIndex(code)));
  }
  uint16_t buffer[] = {code};
  return InternalizeString(base::Vector<const uint16_t>(buffer, 1));
}
References code, v8::internal::String::kMaxOneByteCharCode, and v8::internal::RootsTable::SingleCharacterStringIndex().
Referenced by v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::AddElementsToKeyAccumulatorImpl(), v8::internal::JsonParser< Char >::GetErrorMessageWithEllipses(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetImpl(), v8::internal::LookupIterator::GetStringPropertyValue(), v8::internal::String::GetSubstitution(), v8::internal::anonymous_namespace{factory.cc}::NewStringFromBytes(), v8::internal::JSSegmentIterator::Next(), and v8::internal::RUNTIME_FUNCTION().
MakeOrFindTwoCharacterString()
template<typename Impl >
Handle< String > v8::internal::FactoryBase< Impl >::MakeOrFindTwoCharacterString (uint16_t c1, uint16_t c2) [protected]
Definition at line 716 of file factory-base.cc.
                                                                            {
  if ((c1 | c2) <= unibrow::Latin1::kMaxChar) {
    uint8_t buffer[] = {static_cast<uint8_t>(c1), static_cast<uint8_t>(c2)};
    return InternalizeString(base::Vector<const uint8_t>(buffer, 2));
  }
  uint16_t buffer[] = {c1, c2};
  return InternalizeString(base::Vector<const uint16_t>(buffer, 2));
}
References unibrow::Latin1::kMaxChar.
NewAccessorPair()
template<typename Impl >
Handle< AccessorPair > v8::internal::FactoryBase< Impl >::NewAccessorPair
Definition at line 74 of file factory-base.cc.
                                                        {
  auto accessors =
      NewStructInternal<AccessorPair>(ACCESSOR_PAIR_TYPE, AllocationType::kOld);
  DisallowGarbageCollection no_gc;
  accessors->set_getter(read_only_roots().null_value(), SKIP_WRITE_BARRIER);
  accessors->set_setter(read_only_roots().null_value(), SKIP_WRITE_BARRIER);
  return handle(accessors, isolate());
}
References v8::internal::handle(), v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::Genesis::AddRestrictedFunctionProperties(), v8::internal::AccessorPair::Copy(), v8::internal::Genesis::InitializeGlobal(), v8::internal::InstallError(), v8::internal::LookupIterator::TransitionToAccessorProperty(), and v8::internal::Map::TransitionToAccessorProperty().
NewArrayBoilerplateDescription()
template<typename Impl >
Handle< ArrayBoilerplateDescription > v8::internal::FactoryBase< Impl >::NewArrayBoilerplateDescription (ElementsKind elements_kind, DirectHandle< FixedArrayBase > constant_values)
Definition at line 629 of file factory-base.cc.
                                                                              {
  auto result = NewStructInternal<ArrayBoilerplateDescription>(
      ARRAY_BOILERPLATE_DESCRIPTION_TYPE, AllocationType::kOld);
  DisallowGarbageCollection no_gc;
  result->set_elements_kind(elements_kind);
  result->set_constant_elements(*constant_values);
  return handle(result, isolate());
}
References v8::internal::handle(), v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
NewArrayList()
template<typename Impl >
DirectHandle< ArrayList > v8::internal::FactoryBase< Impl >::NewArrayList (int size, AllocationType allocation = AllocationType::kYoung)
Definition at line 450 of file factory-base.cc.
                                         {
  return ArrayList::New(isolate(), size, allocation);
}
References v8::internal::ArrayList::New(), and size().
Referenced by v8::internal::TemplateObjectDescription::GetTemplateObject().
NewBigInt()
template<typename Impl >
Handle< FreshlyAllocatedBigInt > v8::internal::FactoryBase< Impl >::NewBigInt (uint32_t length, AllocationType allocation = AllocationType::kYoung)
Definition at line 1144 of file factory-base.cc.
                                                {
  if (length > BigInt::kMaxLength) {
    FATAL("Fatal JavaScript invalid size error %d", length);
    UNREACHABLE();
  }
  Tagged<HeapObject> result = AllocateRawWithImmortalMap(
      BigInt::SizeFor(length), allocation, read_only_roots().bigint_map());
  DisallowGarbageCollection no_gc;
  Tagged<FreshlyAllocatedBigInt> bigint = Cast<FreshlyAllocatedBigInt>(result);
  bigint->clear_padding();
  return handle(bigint, isolate());
}
References FATAL, v8::internal::handle(), v8::internal::BigIntBase::kMaxLength, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, v8::internal::BigInt::SizeFor(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::BigInt::FromInt64(), v8::internal::BigInt::FromSerializedDigits(), v8::internal::BigInt::FromUint64(), v8::internal::MutableBigInt::NewFromDouble(), and v8::internal::MutableBigInt::NewFromInt().
NewByteArray()
template<typename Impl >
Handle< ByteArray > v8::internal::FactoryBase< Impl >::NewByteArray (int length, AllocationType allocation = AllocationType::kYoung)
Definition at line 305 of file factory-base.cc.
                                                                             {
  return ByteArray::New(isolate(), length, allocation);
}
Referenced by v8::internal::TranslatedState::AllocateStorageFor(), v8::internal::Heap::CreateImportantReadOnlyObjects(), v8::internal::BoyerMooreLookahead::EmitSkipInstructions(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitUseLookupTable(), v8::internal::FoldedMutableHeapNumberAllocation::FoldedMutableHeapNumberAllocation(), v8::internal::PodArray< T >::New(), and v8::internal::RUNTIME_FUNCTION().
NewBytecodeArray()
template<typename Impl >
Handle< BytecodeArray > v8::internal::FactoryBase< Impl >::NewBytecodeArray (int length, const uint8_t * raw_bytecodes, int frame_size, uint16_t parameter_count, uint16_t max_arguments, DirectHandle< TrustedFixedArray > constant_pool, DirectHandle< TrustedByteArray > handler_table, AllocationType allocation = AllocationType::kTrusted)
Definition at line 330 of file factory-base.cc.
                                                                             {
  DCHECK(allocation == AllocationType::kTrusted ||
         allocation == AllocationType::kSharedTrusted);
  if (length < 0 || length > BytecodeArray::kMaxLength) {
    FATAL("Fatal JavaScript invalid size error %d", length);
    UNREACHABLE();
  }
  DirectHandle<BytecodeWrapper> wrapper = NewBytecodeWrapper();
  int size = BytecodeArray::SizeFor(length);
  Tagged<HeapObject> result = AllocateRawWithImmortalMap(
      size, allocation, read_only_roots().bytecode_array_map());
  DisallowGarbageCollection no_gc;
  Tagged<BytecodeArray> instance = Cast<BytecodeArray>(result);
  instance->init_self_indirect_pointer(isolate());
  instance->set_length(length);
  instance->set_frame_size(frame_size);
  instance->set_parameter_count(parameter_count);
  instance->set_max_arguments(max_arguments);
  instance->set_incoming_new_target_or_generator_register(
      interpreter::Register::invalid_value());
  instance->set_constant_pool(*constant_pool);
  instance->set_handler_table(*handler_table);
  instance->clear_source_position_table(kReleaseStore);
  instance->set_wrapper(*wrapper);
  CopyBytes(reinterpret_cast<uint8_t*>(instance->GetFirstBytecodeAddress()),
            raw_bytecodes, length);
  instance->clear_padding();
  wrapper->set_bytecode(instance);
  return handle(instance, isolate());
}
References v8::internal::DCHECK(), FATAL, v8::internal::BytecodeArray::kMaxLength, v8::internal::kSharedTrusted, v8::internal::kTrusted, v8::internal::length, and v8::internal::UNREACHABLE().
NewBytecodeWrapper()
template<typename Impl >
DirectHandle< BytecodeWrapper > v8::internal::FactoryBase< Impl >::NewBytecodeWrapper (AllocationType allocation = AllocationType::kOld)
Definition at line 366 of file factory-base.cc.
                               {
  DCHECK(allocation == AllocationType::kOld ||
         allocation == AllocationType::kSharedOld);
  DirectHandle<BytecodeWrapper> wrapper(
      Cast<BytecodeWrapper>(NewWithImmortalMap(
          read_only_roots().bytecode_wrapper_map(), allocation)),
      isolate());
  // The BytecodeWrapper is typically created before the BytecodeArray it
  // wraps, so the bytecode field cannot yet be set. However, as a heap
  // verifier might see the wrapper before the field can be set, we need to
  // clear the field here.
  wrapper->clear_bytecode();
  return wrapper;
}
NewClassPositions()
template<typename Impl >
Handle< ClassPositions > v8::internal::FactoryBase< Impl >::NewClassPositions (int start, int end)
Definition at line 1224 of file factory-base.cc.
                                                                     {
  auto result = NewStructInternal<ClassPositions>(CLASS_POSITIONS_TYPE,
                                                  AllocationType::kOld);
  result->set_start(start);
  result->set_end(end);
  return handle(result, isolate());
}
References v8::internal::compiler::end(), v8::internal::handle(), v8::internal::kOld, and v8::base::internal::result.
NewCode()
template<typename Impl >
Handle< Code > v8::internal::FactoryBase< Impl >::NewCode (const NewCodeOptions & options)
Definition at line 84 of file factory-base.cc.
                                                                     {
  DirectHandle<CodeWrapper> wrapper = NewCodeWrapper();
  Tagged<Map> map = read_only_roots().code_map();
  int size = map->instance_size();
  Tagged<Code> code = Cast<Code>(
      AllocateRawWithImmortalMap(size, AllocationType::kTrusted, map));
  DisallowGarbageCollection no_gc;
  code->init_self_indirect_pointer(isolate());
  code->initialize_flags(options.kind, options.is_context_specialized,
                         options.is_turbofanned);
  code->set_builtin_id(options.builtin);
  code->set_instruction_size(options.instruction_size);
  code->set_metadata_size(options.metadata_size);
  code->set_inlined_bytecode_size(options.inlined_bytecode_size);
  code->set_osr_offset(options.osr_offset);
  SBXCHECK_IMPLIES(options.deoptimization_data.is_null(),
                   options.osr_offset.IsNone());
  code->set_handler_table_offset(options.handler_table_offset);
  code->set_constant_pool_offset(options.constant_pool_offset);
  code->set_code_comments_offset(options.code_comments_offset);
  code->set_jump_table_info_offset(options.jump_table_info_offset);
  code->set_unwinding_info_offset(options.unwinding_info_offset);
  code->set_parameter_count(options.parameter_count);
#ifdef V8_ENABLE_LEAPTIERING
  code->set_js_dispatch_handle(kNullJSDispatchHandle);
#endif // V8_ENABLE_LEAPTIERING
  // Set bytecode/interpreter data or deoptimization data.
  if (CodeKindUsesBytecodeOrInterpreterData(options.kind)) {
    DCHECK(options.deoptimization_data.is_null());
    Tagged<TrustedObject> data =
        *options.bytecode_or_interpreter_data.ToHandleChecked();
    DCHECK(IsBytecodeArray(data) || IsInterpreterData(data));
    code->set_bytecode_or_interpreter_data(data);
  } else if (CodeKindUsesDeoptimizationData(options.kind)) {
    DCHECK(options.bytecode_or_interpreter_data.is_null());
    code->set_deoptimization_data(
        *options.deoptimization_data.ToHandleChecked());
  } else {
    DCHECK(options.deoptimization_data.is_null());
    DCHECK(options.bytecode_or_interpreter_data.is_null());
    code->clear_deoptimization_data_and_interpreter_data();
  }
  // Set bytecode offset table or source position table.
  if (CodeKindUsesBytecodeOffsetTable(options.kind)) {
    DCHECK(options.source_position_table.is_null());
    code->set_bytecode_offset_table(
        *options.bytecode_offset_table.ToHandleChecked());
  } else if (CodeKindMayLackSourcePositionTable(options.kind)) {
    DCHECK(options.bytecode_offset_table.is_null());
    Handle<TrustedByteArray> table;
    if (options.source_position_table.ToHandle(&table)) {
      code->set_source_position_table(*table);
    } else {
      code->clear_source_position_table_and_bytecode_offset_table();
    }
  } else {
    DCHECK(options.bytecode_offset_table.is_null());
    code->set_source_position_table(
        *options.source_position_table.ToHandleChecked());
  }
  // Set instruction stream and entrypoint.
  Handle<InstructionStream> istream;
  if (options.instruction_stream.ToHandle(&istream)) {
    DCHECK_EQ(options.instruction_start, kNullAddress);
    code->SetInstructionStreamAndInstructionStart(isolate(), *istream);
  } else {
    DCHECK_NE(options.instruction_start, kNullAddress);
    code->set_raw_instruction_stream(Smi::zero(), SKIP_WRITE_BARRIER);
    code->SetInstructionStartForOffHeapBuiltin(isolate(),
                                               options.instruction_start);
  }
  wrapper->set_code(code);
  code->set_wrapper(*wrapper);
  code->clear_padding();
  return handle(code, isolate());
}
References v8::internal::NewCodeOptions::builtin, code, v8::internal::NewCodeOptions::code_comments_offset, v8::internal::NewCodeOptions::constant_pool_offset, v8::internal::NewCodeOptions::deoptimization_data, v8::internal::NewCodeOptions::handler_table_offset, v8::internal::NewCodeOptions::inlined_bytecode_size, v8::internal::NewCodeOptions::instruction_size, v8::internal::NewCodeOptions::is_context_specialized, v8::internal::NewCodeOptions::is_turbofanned, v8::internal::BytecodeOffset::IsNone(), v8::internal::NewCodeOptions::kind, v8::internal::kTrusted, v8::internal::NewCodeOptions::metadata_size, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::NewCodeOptions::osr_offset, SBXCHECK_IMPLIES, and size().
NewCodeWrapper()
template<typename Impl >
DirectHandle< CodeWrapper > v8::internal::FactoryBase< Impl >::NewCodeWrapper
Definition at line 167 of file factory-base.cc.
                                                            {
  DirectHandle<CodeWrapper> wrapper(
      Cast<CodeWrapper>(NewWithImmortalMap(read_only_roots().code_wrapper_map(),
                                           AllocationType::kOld)),
      isolate());
  // The CodeWrapper is typically created before the Code object it wraps, so
  // the code field cannot yet be set. However, as a heap verifier might see
  // the wrapper before the field can be set, we need to clear the field here.
  wrapper->clear_code();
  return wrapper;
}
NewConsString() [1/2]
template<typename Impl >
template<typename Impl >
Handle<String> v8::internal::FactoryBase< Impl >::NewConsString (DirectHandle< String > left, DirectHandle< String > right, int length, bool one_byte, AllocationType allocation)
Definition at line 951 of file factory-base.cc.
                                                                           {
  DCHECK(!IsThinString(*left));
  DCHECK(!IsThinString(*right));
  DCHECK_GE(length, ConsString::kMinLength);
  DCHECK_LE(length, String::kMaxLength);
  Tagged<ConsString> result = Cast<ConsString>(
      one_byte ? NewWithImmortalMap(
                     read_only_roots().cons_one_byte_string_map(), allocation)
               : NewWithImmortalMap(
                     read_only_roots().cons_two_byte_string_map(), allocation));
  DisallowGarbageCollection no_gc;
  WriteBarrierMode mode = result->GetWriteBarrierMode(no_gc);
  result->set_raw_hash_field(String::kEmptyHashField);
  result->set_length(length);
  result->set_first(*left, mode);
  result->set_second(*right, mode);
  return handle(result, isolate());
}
References v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, v8::internal::handle(), v8::internal::InstanceTypeChecker::IsThinString(), v8::internal::Name::kEmptyHashField, v8::internal::String::kMaxLength, v8::internal::ConsString::kMinLength, v8::internal::length, mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
NewConsString() [2/2]
template<typename Impl >
template<template< typename > typename HandleType>
requires (std::is_convertible_v<HandleType<String>, DirectHandle<String>>) V8_WARN_UNUSED_RESULT HandleType<String> V8_WARN_UNUSED_RESULT Handle<String> v8::internal::FactoryBase< Impl >::NewConsString (DirectHandle< String > left, DirectHandle< String > right, int length, bool one_byte, AllocationType allocation = AllocationType::kYoung)
Referenced by v8::internal::IncrementalStringBuilder::Accumulate(), v8::internal::Object::Add(), v8::String::Concat(), v8::internal::compiler::JSNativeContextSpecialization::Concatenate(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CopyConsStringToOld(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::debug::GetBigIntDescription(), v8::debug::anonymous_namespace{debug-interface.cc}::GetBigIntStringPresentationHandle(), v8::internal::JSBoundFunction::GetName(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd(), v8::internal::requires(), v8::internal::TranslatedState::ResolveStringConcat(), v8::internal::RUNTIME_FUNCTION(), v8::internal::StringReplaceOneCharWithString(), and v8::internal::anonymous_namespace{uri.cc}::UnescapeSlow().
NewCoverageInfo()
template<typename Impl >
Handle< CoverageInfo > v8::internal::FactoryBase< Impl >::NewCoverageInfo (const ZoneVector< SourceRange > & slots)
Definition at line 699 of file factory-base.cc.
                                          {
  const int slot_count = static_cast<int>(slots.size());
  int size = CoverageInfo::SizeFor(slot_count);
  Tagged<Map> map = read_only_roots().coverage_info_map();
  Tagged<CoverageInfo> info = Cast<CoverageInfo>(
      AllocateRawWithImmortalMap(size, AllocationType::kOld, map));
  info->set_slot_count(slot_count);
  for (int i = 0; i < slot_count; i++) {
    SourceRange range = slots[i];
    info->InitializeSlot(i, range.start, range.end);
  }
  return handle(info, isolate());
}
References v8::internal::SourceRange::end, v8::internal::handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kOld, v8::internal::ZoneVector< T >::size(), size(), v8::internal::CoverageInfo::SizeFor(), and v8::internal::SourceRange::start.
NewDeoptimizationFrameTranslation()
template<typename Impl >
DirectHandle< DeoptimizationFrameTranslation > v8::internal::FactoryBase< Impl >::NewDeoptimizationFrameTranslation (int length)
Definition at line 325 of file factory-base.cc.
                                                               {
  return Cast<DeoptimizationFrameTranslation>(NewTrustedByteArray(length));
}
References v8::internal::length.
Referenced by v8::internal::FrameTranslationBuilder::ToFrameTranslation().
NewDeoptimizationLiteralArray()
template<typename Impl >
DirectHandle< DeoptimizationLiteralArray > v8::internal::FactoryBase< Impl >::NewDeoptimizationLiteralArray (int length)
Definition at line 319 of file factory-base.cc.
                                                           {
  return Cast<DeoptimizationLiteralArray>(NewTrustedWeakFixedArray(length));
}
Referenced by v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), and v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData().
NewDescriptorArray()
template<typename Impl >
Handle< DescriptorArray > v8::internal::FactoryBase< Impl >::NewDescriptorArray (int number_of_descriptors, int slack = 0, AllocationType allocation = AllocationType::kYoung)
Definition at line 1194 of file factory-base.cc.
                                                                     {
  int number_of_all_descriptors = number_of_descriptors + slack;
  // Zero-length case must be handled outside.
  DCHECK_LT(0, number_of_all_descriptors);
  int size = DescriptorArray::SizeFor(number_of_all_descriptors);
  Tagged<HeapObject> obj = AllocateRawWithImmortalMap(
      size, allocation, read_only_roots().descriptor_array_map());
  Tagged<DescriptorArray> array = Cast<DescriptorArray>(obj);
  auto raw_gc_state = DescriptorArrayMarkingState::kInitialGCState;
  if (allocation != AllocationType::kYoung &&
      allocation != AllocationType::kReadOnly) {
    auto* local_heap = allocation == AllocationType::kSharedOld
                           ? isolate()->shared_space_isolate()->heap()
                           : isolate()->heap();
    Heap* heap = local_heap->AsHeap();
    if (heap->incremental_marking()->IsMajorMarking()) {
      // Black allocation: We must create a full marked state.
      raw_gc_state = DescriptorArrayMarkingState::GetFullyMarkedState(
          heap->mark_compact_collector()->epoch(), number_of_descriptors);
    }
  }
  array->Initialize(read_only_roots().empty_enum_cache(),
                    read_only_roots().undefined_value(), number_of_descriptors,
                    slack, raw_gc_state);
  return handle(array, isolate());
}
References DCHECK_LT, v8::internal::DescriptorArrayMarkingState::GetFullyMarkedState(), v8::internal::handle(), v8::internal::DescriptorArrayMarkingState::kInitialGCState, v8::internal::kReadOnly, v8::internal::kSharedOld, v8::internal::kYoung, v8::internal::number_of_descriptors, size(), and v8::internal::DescriptorArray::SizeFor().
Referenced by v8::internal::Heap::CreateLateReadOnlyJSReceiverMaps().
NewFeedbackMetadata()
template<typename Impl >
Handle< FeedbackMetadata > v8::internal::FactoryBase< Impl >::NewFeedbackMetadata (int slot_count, int create_closure_slot_count, AllocationType allocation = AllocationType::kOld)
Definition at line 679 of file factory-base.cc.
                                                                              {
  DCHECK_LE(0, slot_count);
  int size = FeedbackMetadata::SizeFor(slot_count, create_closure_slot_count);
  Tagged<FeedbackMetadata> result =
      Cast<FeedbackMetadata>(AllocateRawWithImmortalMap(
          size, allocation, read_only_roots().feedback_metadata_map()));
  result->set_slot_count(slot_count);
  result->set_create_closure_slot_count(create_closure_slot_count);
  // Initialize the data section to 0.
  int data_size = size - FeedbackMetadata::kHeaderSize;
  Address data_start = result->address() + FeedbackMetadata::kHeaderSize;
  memset(reinterpret_cast<uint8_t*>(data_start), 0, data_size);
  // Fields have been zeroed out but not initialized, so this object will not
  // pass object verification at this point.
  return handle(result, isolate());
}
References DCHECK_LE, v8::internal::handle(), v8::internal::HeapObject::kHeaderSize, v8::base::internal::result, size(), and v8::internal::FeedbackMetadata::SizeFor().
Referenced by v8::internal::Heap::CreateReadOnlyObjects().
NewFixedArray()
template<typename Impl >
Handle< FixedArray > v8::internal::FactoryBase< Impl >::NewFixedArray (int length, AllocationType allocation = AllocationType::kYoung)
Definition at line 180 of file factory-base.cc.
                                                                               {
  return FixedArray::New(isolate(), length, allocation);
}
Referenced by v8::internal::SourceCodeCache::Add(), v8::internal::WasmScript::AddBreakpointToInfo(), v8::Isolate::AddMessageListenerWithErrorLevel(), v8::internal::AddWasmTableObjectInternalProperties(), v8::internal::JSObject::AllocateStorageForMap(), v8::internal::anonymous_namespace{accessors.cc}::ArgumentsFromDeoptInfo(), v8::internal::anonymous_namespace{compilation-cache-table.cc}::EvalCacheKey::AsHandle(), v8::internal::anonymous_namespace{intl-objects.cc}::AvailableUnits(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::CallSiteBuilder(), v8::internal::WasmScript::CheckBreakPoints(), v8::internal::Debug::CheckBreakPointsForLocations(), v8::internal::BreakPointInfo::ClearBreakPoint(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{keys.cc}::CollectKeysFromDictionary(), v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::anonymous_namespace{keys.cc}::CombineKeys(), v8::ScriptCompiler::CompileFunction(), v8::internal::anonymous_namespace{api-natives.cc}::ConfigureInstance(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ConvertElementsWithCapacity(), v8::internal::DictionaryTemplateInfo::Create(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::LocalsProxy::Create(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::StackProxy::Create(), v8::internal::SnapshotCreatorImpl::CreateBlob(), v8::internal::Debug::CreateBreakInfo(), v8::internal::RegExp::CreateCaptureNameMap(), v8::internal::Heap::CreateInitialMutableObjects(), v8::internal::Object::CreateListFromArrayLike(), v8::internal::anonymous_namespace{elements.cc}::FastElementsAccessor< Subclass, KindTraits >::CreateListFromArrayLikeImpl(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::CreateListFromArrayLikeImpl(), v8::internal::Heap::CreateReadOnlyObjects(), v8::Module::CreateSyntheticModule(), v8::internal::MaterializedObjectStore::EnsureStackEntries(), v8::internal::FastGetOwnValuesOrEntries(), v8::internal::anonymous_namespace{runtime-test.cc}::FillUpOneNewSpacePage(), v8::internal::BuiltinsConstantsTableBuilder::Finalize(), v8::internal::wasm::GetCustomSections(), v8::internal::anonymous_namespace{isolate.cc}::GetDetailedStackTraceFromCallSiteInfos(), v8::internal::JSWeakCollection::GetEntries(), v8::internal::wasm::GetExports(), v8::internal::anonymous_namespace{accessors.cc}::GetFrameArguments(), v8::internal::Debug::GetHitBreakPoints(), v8::internal::JSLocale::GetHourCycles(), v8::internal::Isolate::GetImportAttributesFromArgument(), v8::internal::wasm::GetImports(), v8::internal::GetKeywordValuesFromLocale(), v8::internal::Debug::GetLoadedScripts(), v8::internal::JSLocale::GetNumberingSystems(), v8::internal::anonymous_namespace{keys.cc}::GetOwnEnumPropertyDictionaryKeys(), v8::internal::GetOwnValuesOrEntries(), v8::internal::CommonFrameWithJSLinkage::GetParameters(), v8::internal::BuiltinExitFrame::GetParameters(), v8::internal::ApiCallbackExitFrame::GetParameters(), v8::internal::Debug::GetSourceBreakLocations(), v8::internal::anonymous_namespace{messages.cc}::GetStackFrames(), v8::internal::wasm::GetTypeForFunction(), v8::internal::JSLocale::GetWeekInfo(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedEnumerator(), v8::internal::wasm::InitializeElementSegment(), v8::internal::FastKeyAccumulator::InitializeFastPropertyEnumCache(), v8::internal::JSDisposableStackBase::InitializeJSDisposableStackBase(), v8::internal::MakeEntryPair(), v8::anonymous_namespace{api.cc}::MapAsArray(), v8::internal::ScopeIterator::MaterializeScopeDetails(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), v8::internal::WasmTrustedInstanceData::New(), v8::internal::WasmExceptionPackage::New(), v8::internal::WasmGlobalObject::New(), v8::internal::WasmTableObject::New(), v8::PrimitiveArray::New(), v8::Array::New(), v8::internal::anonymous_namespace{runtime-scopes.cc}::NewSloppyArguments(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::PrependElementIndicesImpl(), v8::internal::SourceTextModule::Reset(), v8::internal::JSPluralRules::ResolvedOptions(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), v8::anonymous_namespace{api.cc}::SetAsArray(), v8::internal::BreakPointInfo::SetBreakPoint(), v8::internal::DebugInfo::SetBreakPoint(), v8::FunctionTemplate::SetCallHandler(), v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), v8::internal::ObjectCacheIndexMap::Values(), v8::internal::anonymous_namespace{intl-objects.cc}::VectorToJSArray(), v8::internal::ValueSerializer::WriteJSMap(), and v8::internal::ValueSerializer::WriteJSSet().
NewFixedArrayWithFiller()
template<typename Impl >
Handle< FixedArray > v8::internal::FactoryBase< Impl >::NewFixedArrayWithFiller (DirectHandle< Map > map, int length, DirectHandle< HeapObject > filler, AllocationType allocation) [protected]
Definition at line 223 of file factory-base.cc.
                               {
  Tagged<HeapObject> result = AllocateRawFixedArray(length, allocation);
  DisallowGarbageCollection no_gc;
  DCHECK(ReadOnlyHeap::Contains(*map));
  DCHECK(ReadOnlyHeap::Contains(*filler));
  result->set_map_after_allocation(isolate(), *map, SKIP_WRITE_BARRIER);
  Tagged<FixedArray> array = Cast<FixedArray>(result);
  array->set_length(length);
  MemsetTagged(array->RawFieldOfFirstElement(), *filler, length);
  return handle(array, isolate());
}
NewFixedArrayWithHoles()
template<typename Impl >
Handle< FixedArray > v8::internal::FactoryBase< Impl >::NewFixedArrayWithHoles (int length, AllocationType allocation = AllocationType::kYoung)
Definition at line 214 of file factory-base.cc.
                                           {
  DCHECK_LE(0, length);
  if (length == 0) return impl()->empty_fixed_array();
  return NewFixedArrayWithFiller(fixed_array_map(), length, the_hole_value(),
                                 allocation);
}
References DCHECK_LE, wasm::impl(), and v8::internal::length.
Referenced by v8::internal::ArrayConstructInitializeElements(), v8::internal::FixedArrayBuilder::EnsureCapacity(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateDebugMaps(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateInstanceProxyCache(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::FrameState::SetCaughtException(), and v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat().
NewFixedArrayWithMap()
template<typename Impl >
Handle< FixedArray > v8::internal::FactoryBase< Impl >::NewFixedArrayWithMap (DirectHandle< Map > map, int length, AllocationType allocation = AllocationType::kYoung)
Definition at line 205 of file factory-base.cc.
                                                                  {
  // Zero-length case must be handled outside, where the knowledge about
  // the map is.
  DCHECK_LT(0, length);
  return NewFixedArrayWithFiller(map, length, undefined_value(), allocation);
}
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::Allocate().
NewFixedArrayWithZeroes()
template<typename Impl >
DirectHandle< FixedArray > v8::internal::FactoryBase< Impl >::NewFixedArrayWithZeroes (int length, AllocationType allocation = AllocationType::kYoung)
Definition at line 238 of file factory-base.cc.
                                           {
  DCHECK_LE(0, length);
  if (length == 0) return impl()->empty_fixed_array();
  if (length > FixedArray::kMaxLength) {
    FATAL("Invalid FixedArray size %d", length);
  }
  Tagged<HeapObject> result = AllocateRawFixedArray(length, allocation);
  DisallowGarbageCollection no_gc;
  result->set_map_after_allocation(
      isolate(), read_only_roots().fixed_array_map(), SKIP_WRITE_BARRIER);
  Tagged<FixedArray> array = Cast<FixedArray>(result);
  array->set_length(length);
  MemsetTagged(array->RawFieldOfFirstElement(), Smi::zero(), length);
  return direct_handle(array, isolate());
}
References DCHECK_LE, wasm::impl(), and v8::internal::length.
Referenced by v8::internal::anonymous_namespace{runtime-wasm.cc}::AllocateFeedbackVector(), v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::WasmTrustedInstanceData::New(), and v8::internal::anonymous_namespace{builtins-array.cc}::TryFastArrayFill().
NewFixedDoubleArray()
template<typename Impl >
Handle< FixedArrayBase > v8::internal::FactoryBase< Impl >::NewFixedDoubleArray (int length, AllocationType allocation = AllocationType::kYoung)
Definition at line 256 of file factory-base.cc.
                                           {
  return FixedDoubleArray::New(isolate(), length, allocation);
}
References v8::internal::length, and v8::internal::FixedDoubleArray::New().
Referenced by v8::internal::ArrayConstructInitializeElements(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::ConvertElementsWithCapacity(), v8::internal::MathRandom::InitializeContext(), v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat(), and v8::internal::anonymous_namespace{builtins-array.cc}::TryFastArrayFill().
NewFunctionTemplateRareData()
template<typename Impl >
DirectHandle< FunctionTemplateRareData > v8::internal::FactoryBase< Impl >::NewFunctionTemplateRareData
Definition at line 1384 of file factory-base.cc.
                                               {
  auto function_template_rare_data =
      NewStructInternal<FunctionTemplateRareData>(
          FUNCTION_TEMPLATE_RARE_DATA_TYPE, AllocationType::kOld);
  DisallowGarbageCollection no_gc;
  function_template_rare_data->set_c_function_overloads(
      *impl()->empty_fixed_array(), SKIP_WRITE_BARRIER);
  return direct_handle(function_template_rare_data, isolate());
}
References v8::internal::direct_handle(), wasm::impl(), v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::SKIP_WRITE_BARRIER.
Referenced by v8::internal::FunctionTemplateInfo::AllocateFunctionTemplateRareData().
NewHeapInt32()
template<typename Impl >
template<AllocationType allocation>
Handle< HeapNumber > v8::internal::FactoryBase< Impl >::NewHeapInt32 (int32_t value) [inline]
Definition at line 124 of file factory-base-inl.h.
                                                                {
  Handle<HeapNumber> heap_number = NewHeapNumber<allocation>();
  heap_number->set_value_as_bits(
      (static_cast<uint64_t>(kHoleNanUpper32) << 32) | value);
  return heap_number;
}
NewHeapNumber() [1/2]
template<typename Impl >
template<AllocationType allocation>
template V8_EXPORT_PRIVATE Handle< HeapNumber > v8::internal::FactoryBase< Impl >::NewHeapNumber< AllocationType::kOld > ()
Definition at line 42 of file factory-base.cc.
                                                    {
  static_assert(sizeof(HeapNumber) <= kMaxRegularHeapObjectSize);
  Tagged<Map> map = read_only_roots().heap_number_map();
  Tagged<HeapObject> result = AllocateRawWithImmortalMap(
      sizeof(HeapNumber), allocation, map,
      USE_ALLOCATION_ALIGNMENT_HEAP_NUMBER_BOOL ? kDoubleUnaligned
                                                : kTaggedAligned);
  return handle(Cast<HeapNumber>(result), isolate());
}
References v8::internal::handle(), v8::internal::kDoubleUnaligned, v8::internal::kMaxRegularHeapObjectSize, v8::internal::kTaggedAligned, v8::base::internal::result, and USE_ALLOCATION_ALIGNMENT_HEAP_NUMBER_BOOL.
NewHeapNumber() [2/2]
template<typename Impl >
template<AllocationType allocation>
Handle< HeapNumber > v8::internal::FactoryBase< Impl >::NewHeapNumber (double value) [inline]
Definition at line 102 of file factory-base-inl.h.
                                                                {
  Handle<HeapNumber> heap_number = NewHeapNumber<allocation>();
  heap_number->set_value(value);
  return heap_number;
}
References v8::internal::value.
Referenced by v8::internal::Assembler::AllocateAndInstallRequestedHeapNumbers(), v8::internal::anonymous_namespace{wasm-objects.cc}::CanonicalizeHeapNumber(), v8::internal::anonymous_namespace{wasm-objects.cc}::CanonicalizeSmi(), v8::internal::Heap::CreateImportantReadOnlyObjects(), v8::internal::Context::Get(), v8::internal::TranslatedValue::GetValue(), v8::internal::TranslatedState::MaterializeHeapNumber(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), v8::internal::DictionaryTemplateInfo::NewInstance(), v8::internal::JSSegmentIterator::Next(), v8::internal::TranslatedState::StoreMaterializedValuesAndDeopt(), v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::ToHandle(), and v8::internal::BigInt::ToNumber().
NewHeapNumberFromBits()
template<typename Impl >
template<AllocationType allocation>
Handle< HeapNumber > v8::internal::FactoryBase< Impl >::NewHeapNumberFromBits (uint64_t bits) [inline]
Definition at line 110 of file factory-base-inl.h.
                                                                         {
  Handle<HeapNumber> heap_number = NewHeapNumber<allocation>();
  heap_number->set_value_as_bits(bits);
  return heap_number;
}
Referenced by v8::internal::Heap::CreateImportantReadOnlyObjects(), v8::internal::AsmJsCompilationJob::FinalizeJobImpl(), and v8::internal::anonymous_namespace{runtime-literals.cc}::JSObjectWalkVisitor< ContextObject >::StructureWalk().
NewHeapNumberWithHoleNaN()
template<typename Impl >
template<AllocationType allocation>
Handle< HeapNumber > v8::internal::FactoryBase< Impl >::NewHeapNumberWithHoleNaN [inline]
Definition at line 118 of file factory-base-inl.h.
                                                               {
  return NewHeapNumberFromBits<allocation>(kHoleNanInt64);
}
Referenced by v8::internal::JSObject::AllocateStorageForMap(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToFast(), and v8::internal::Object::NewStorageFor().
NewNumber()
template<typename Impl >
template<AllocationType allocation>
Handle< Number > v8::internal::FactoryBase< Impl >::NewNumber (double value) [inline]
Definition at line 50 of file factory-base-inl.h.
                                                        {
  // Materialize as a SMI if possible.
  int32_t int_value;
  if (DoubleToSmiInteger(value, &int_value)) {
    return handle(Smi::FromInt(int_value), isolate());
  }
  return NewHeapNumber<allocation>(value);
}
References v8::internal::DoubleToSmiInteger(), v8::internal::Smi::FromInt(), v8::internal::handle(), and v8::internal::value.
Referenced by v8::internal::Object::Add(), v8::internal::Object::ConvertToLength(), v8::internal::JSFunctionOrBoundFunctionOrWrappedFunction::CopyNameAndLength(), v8::internal::maglev::Float64Constant::DoReify(), v8::internal::IntlMathematicalValue::From(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPop(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPush(), v8::internal::FixedDoubleArray::get(), v8::internal::Genesis::InitializeGlobal(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::WasmValueObject::New(), v8::internal::WasmTableObject::New(), v8::NumberObject::New(), v8::Number::New(), v8::Integer::New(), v8::Integer::NewFromUnsigned(), v8::internal::ValueDeserializer::ReadJSPrimitiveWrapper(), v8::internal::ValueDeserializer::ReadObjectInternal(), v8::internal::WasmObject::ReadValueAt(), v8::internal::DeoptimizationLiteral::Reify(), v8::internal::anonymous_namespace{builtins-date.cc}::SetDateValue(), v8::internal::anonymous_namespace{builtins-array.cc}::SetLengthProperty(), v8::internal::anonymous_namespace{builtins-date.cc}::SetLocalDateValue(), v8::internal::SliceHelper(), v8::Value::ToArrayIndex(), and v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::ToHandle().
NewNumberFromInt()
template<typename Impl >
template<AllocationType allocation>
Handle< Number > v8::internal::FactoryBase< Impl >::NewNumberFromInt (int32_t value) [inline]
Definition at line 61 of file factory-base-inl.h.
                                                                {
  if (Smi::IsValid(value)) return handle(Smi::FromInt(value), isolate());
  // Bypass NewNumber to avoid various redundant checks.
  return NewHeapNumber<allocation>(FastI2D(value));
}
References v8::internal::FastI2D(), v8::internal::Smi::FromInt(), v8::internal::handle(), v8::internal::Smi::IsValid(), and v8::internal::value.
Referenced by v8::internal::JSSegments::CreateSegmentDataObject(), v8::internal::JSV8BreakIterator::Current(), v8::internal::maglev::Int32Constant::DoReify(), v8::internal::anonymous_namespace{runtime-wasm.cc}::EncodeWtf8(), v8::internal::JSV8BreakIterator::First(), v8::internal::anonymous_namespace{builtins-console.cc}::Formatter(), v8::internal::anonymous_namespace{builtins-array.cc}::GenericArrayPush(), v8::HeapGraphEdge::GetName(), v8::internal::JSLocale::GetWeekInfo(), v8::internal::anonymous_namespace{runtime-debug.cc}::MakeRangeObject(), v8::internal::WasmValueObject::New(), v8::Array::New(), v8::internal::JSV8BreakIterator::Next(), v8::internal::anonymous_namespace{builtins-callsite.cc}::PositiveNumberOrNull(), v8::internal::ValueDeserializer::ReadObjectInternal(), v8::internal::WasmObject::ReadValueAt(), v8::internal::JSDateTimeFormat::ResolvedOptions(), v8::internal::JSNumberFormat::ResolvedOptions(), v8::internal::JSNumberFormat::RoundingIncrement(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::ToHandle().
NewNumberFromInt64()
template<typename Impl >
template<AllocationType allocation>
DirectHandle< Number > v8::internal::FactoryBase< Impl >::NewNumberFromInt64 (int64_t value) [inline]
Definition at line 91 of file factory-base-inl.h.
                                                                        {
  if (value <= std::numeric_limits<int32_t>::max() &&
      value >= std::numeric_limits<int32_t>::min() &&
      Smi::IsValid(static_cast<int32_t>(value))) {
    return direct_handle(Smi::FromInt(static_cast<int32_t>(value)), isolate());
  }
  return NewHeapNumber<allocation>(static_cast<double>(value));
}
References v8::internal::direct_handle(), v8::internal::Smi::FromInt(), v8::internal::Smi::IsValid(), and v8::internal::value.
Referenced by v8::internal::maglev::IntPtrConstant::DoReify(), v8::internal::JSTemporalInstant::EpochMilliseconds(), v8::internal::JSDateTimeFormat::FormatToParts(), and v8::internal::RegExpUtils::SetLastIndex().
NewNumberFromSize()
template<typename Impl >
template<AllocationType allocation>
DirectHandle< Number > v8::internal::FactoryBase< Impl >::NewNumberFromSize (size_t value) [inline]
Definition at line 79 of file factory-base-inl.h.
                                                                      {
  // We can't use Smi::IsValid() here because that operates on a signed
  // intptr_t, and casting from size_t could create a bogus sign bit.
  if (value <= static_cast<size_t>(Smi::kMaxValue)) {
    return direct_handle(Smi::FromIntptr(static_cast<intptr_t>(value)),
                         isolate());
  }
  return NewHeapNumber<allocation>(static_cast<double>(value));
}
References v8::internal::direct_handle(), v8::internal::Smi::FromIntptr(), v8::internal::Smi::kMaxValue, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::CollectElementIndicesImpl(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::DirectCollectElementIndicesImpl(), v8::internal::interpreter::Interpreter::GetDispatchCountersObject(), and v8::internal::Runtime::GetInternalProperties().
NewNumberFromUint()
template<typename Impl >
template<AllocationType allocation>
Handle< Number > v8::internal::FactoryBase< Impl >::NewNumberFromUint (uint32_t value) [inline]
Definition at line 69 of file factory-base-inl.h.
                                                                  {
  int32_t int32v = static_cast<int32_t>(value);
  if (int32v >= 0 && Smi::IsValid(int32v)) {
    return handle(Smi::FromInt(int32v), isolate());
  }
  return NewHeapNumber<allocation>(FastUI2D(value));
}
References v8::internal::FastUI2D(), v8::internal::Smi::FromInt(), v8::internal::handle(), v8::internal::Smi::IsValid(), and v8::internal::value.
Referenced by v8::internal::JSObject::AddDataElement(), v8::internal::KeyAccumulator::AddKey(), v8::internal::JSArray::ArraySetLength(), v8::internal::NumberDictionaryBaseShape::AsHandle(), v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::CollectElementIndicesImpl(), v8::internal::ArrayProxy::Create(), v8::internal::JSArray::DefineOwnProperty(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::DirectCollectElementIndicesImpl(), v8::internal::maglev::Uint32Constant::DoReify(), v8::internal::Runtime::GetInternalProperties(), v8::internal::wasm::GetTypeForTable(), v8::internal::anonymous_namespace{runtime-debug.cc}::MakeRangeObject(), v8::internal::ValueDeserializer::ReadObjectInternal(), v8::internal::anonymous_namespace{elements.cc}::DictionaryElementsAccessor::SetLengthImpl(), and v8::internal::anonymous_namespace{elements.cc}::TypedElementsAccessor< Kind, ElementType >::ToHandle().
NewObjectBoilerplateDescription()
template<typename Impl >
Handle< ObjectBoilerplateDescription > v8::internal::FactoryBase< Impl >::NewObjectBoilerplateDescription (int boilerplate, int all_properties, int index_keys, bool has_seen_proto)
Definition at line 618 of file factory-base.cc.
                                                                        {
  return ObjectBoilerplateDescription::New(
      isolate(), boilerplate, all_properties, index_keys, has_seen_proto,
      AllocationType::kOld);
}
References v8::internal::kOld, and v8::internal::ObjectBoilerplateDescription::New().
NewOneByteInternalizedString()
template<typename Impl >
Handle< SeqOneByteString > v8::internal::FactoryBase< Impl >::NewOneByteInternalizedString (base::Vector< const uint8_t > str, uint32_t raw_hash_field)
Definition at line 771 of file factory-base.cc.
                                                            {
  Handle<SeqOneByteString> result =
      AllocateRawOneByteInternalizedString(str.length(), raw_hash_field);
  // No synchronization is needed since the shared string hasn't yet escaped to
  // script.
  DisallowGarbageCollection no_gc;
  MemCopy(result->GetChars(no_gc, SharedStringAccessGuardIfNeeded::NotNeeded()),
          str.begin(), str.length());
  return result;
}
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::length(), v8::internal::MemCopy(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SharedStringAccessGuardIfNeeded::NotNeeded(), and v8::base::internal::result.
NewOneByteInternalizedStringFromTwoByte()
template<typename Impl >
DirectHandle< SeqOneByteString > v8::internal::FactoryBase< Impl >::NewOneByteInternalizedStringFromTwoByte (base::Vector< const base::uc16 > str, uint32_t raw_hash_field)
Definition at line 798 of file factory-base.cc.
                                                             {
  DirectHandle<SeqOneByteString> result =
      AllocateRawOneByteInternalizedString(str.length(), raw_hash_field);
  DisallowGarbageCollection no_gc;
  CopyChars(
      result->GetChars(no_gc, SharedStringAccessGuardIfNeeded::NotNeeded()),
      str.begin(), str.length());
  return result;
}
References v8::base::Vector< T >::begin(), v8::internal::CopyChars(), v8::base::Vector< T >::length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SharedStringAccessGuardIfNeeded::NotNeeded(), and v8::base::internal::result.
NewPreparseData()
template<typename Impl >
Handle< PreparseData > v8::internal::FactoryBase< Impl >::NewPreparseData (int data_length, int children_length)
Definition at line 500 of file factory-base.cc.
                                                                             {
  int size = PreparseData::SizeFor(data_length, children_length);
  Tagged<PreparseData> result = Cast<PreparseData>(AllocateRawWithImmortalMap(
      size, AllocationType::kOld, read_only_roots().preparse_data_map()));
  DisallowGarbageCollection no_gc;
  result->set_data_length(data_length);
  result->set_children_length(children_length);
  MemsetTagged(result->inner_data_start(), read_only_roots().null_value(),
               children_length);
  result->clear_padding();
  return handle(result, isolate());
}
References v8::internal::handle(), v8::internal::kOld, v8::internal::MemsetTagged(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, size(), and v8::internal::PreparseData::SizeFor().
Referenced by v8::internal::PreparseDataBuilder::ByteData::CopyToHeap(), v8::internal::PreparseDataBuilder::ByteData::CopyToLocalHeap(), and v8::internal::ZonePreparseData::Serialize().
NewProtectedFixedArray()
template<typename Impl >
Handle< ProtectedFixedArray > v8::internal::FactoryBase< Impl >::NewProtectedFixedArray (int length, bool shared = false)
Definition at line 198 of file factory-base.cc.
                             {
  if (length == 0) return empty_protected_fixed_array();
  return ProtectedFixedArray::New(isolate(), length, shared);
}
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), and v8::internal::DeoptimizationData::New().
NewProtectedWeakFixedArray()
template<typename Impl >
Handle< ProtectedWeakFixedArray > v8::internal::FactoryBase< Impl >::NewProtectedWeakFixedArray (int length)
Definition at line 296 of file factory-base.cc.
                {
  // TODO(saelo): Move this check to ProtectedWeakFixedArray::New once we have
  // a RO trusted space.
  if (length == 0) return empty_protected_weak_fixed_array();
  return ProtectedWeakFixedArray::New(isolate(), length);
}
Referenced by v8::internal::WasmDispatchTable::MaybeGrowUsesList().
NewRawOneByteString()
template<typename Impl >
MaybeHandle< SeqOneByteString > v8::internal::FactoryBase< Impl >::NewRawOneByteString (int length, AllocationType allocation = AllocationType::kYoung, AllocationHint hint = AllocationHint())
Definition at line 836 of file factory-base.cc.
                                                                {
  Tagged<Map> map = read_only_roots().seq_one_byte_string_map();
  return NewRawStringWithMap<SeqOneByteString>(
      length, map,
      RefineAllocationTypeForInPlaceInternalizableString(allocation, map),
      hint);
}
References v8::internal::length.
Referenced by v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCase(), v8::internal::Intl::ConvertToLower(), v8::internal::Intl::ConvertToUpper(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CreateExternalizableString(), v8::internal::anonymous_namespace{uri.cc}::EscapePrivate(), v8::internal::anonymous_namespace{js-regexp.cc}::EscapeRegExpSource(), v8::internal::IncrementalStringBuilder::Extend(), v8::internal::anonymous_namespace{json-stringifier.cc}::FastJsonStringify(), v8::internal::IncrementalStringBuilder::IncrementalStringBuilder(), v8::internal::anonymous_namespace{factory.cc}::NewStringFromBytes(), v8::internal::BigInt::NoSideEffectsToString(), v8::internal::StringReplaceGlobalAtomRegExpWithString(), v8::internal::StringReplaceGlobalRegExpWithEmptyString(), v8::internal::ReplacementStringBuilder::ToString(), v8::internal::BigInt::ToString(), and v8::internal::anonymous_namespace{uri.cc}::UnescapeSlow().
NewRawSharedOneByteString()
template<typename Impl >
MaybeHandle< SeqOneByteString > v8::internal::FactoryBase< Impl >::NewRawSharedOneByteString (int length)
Definition at line 856 of file factory-base.cc.
                {
  return NewRawStringWithMap<SeqOneByteString>(
      length, read_only_roots().shared_seq_one_byte_string_map(),
      AllocationType::kSharedOld, AllocationHint());
}
References v8::internal::kSharedOld, and v8::internal::length.
NewRawSharedTwoByteString()
template<typename Impl >
MaybeHandle< SeqTwoByteString > v8::internal::FactoryBase< Impl >::NewRawSharedTwoByteString (int length)
Definition at line 864 of file factory-base.cc.
                {
  return NewRawStringWithMap<SeqTwoByteString>(
      length, read_only_roots().shared_seq_two_byte_string_map(),
      AllocationType::kSharedOld, AllocationHint());
}
References v8::internal::kSharedOld, and v8::internal::length.
NewRawStringWithMap()
template<typename Impl >
template<typename SeqStringT >
MaybeHandle< SeqStringT > v8::internal::FactoryBase< Impl >::NewRawStringWithMap (int length, Tagged< Map > map, AllocationType allocation, AllocationHint hint = AllocationHint()) [protected]
Definition at line 811 of file factory-base.cc.
                         {
  DCHECK(SeqStringT::IsCompatibleMap(map, read_only_roots()));
  DCHECK_IMPLIES(!StringShape(map).IsShared(),
                 RefineAllocationTypeForInPlaceInternalizableString(
                     allocation, map) == allocation);
  if (length < 0 || static_cast<uint32_t>(length) > String::kMaxLength) {
    THROW_NEW_ERROR(isolate(), NewInvalidStringLengthError());
  }
  DCHECK_GT(length, 0); // Use Factory::empty_string() instead.
  int size = SeqStringT::SizeFor(length);
  DCHECK_GE(ObjectTraits<SeqStringT>::kMaxSize, size);
  Tagged<SeqStringT> string = Cast<SeqStringT>(AllocateRawWithImmortalMap(
      size, allocation, map, AllocationAlignment::kTaggedAligned, hint));
  DisallowGarbageCollection no_gc;
  string->clear_padding_destructively(length);
  string->set_length(length);
  string->set_raw_hash_field(String::kEmptyHashField);
  DCHECK_EQ(size, string->Size());
  return handle(string, isolate());
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_GT, DCHECK_IMPLIES, v8::internal::handle(), v8::internal::IsShared(), v8::internal::Name::kEmptyHashField, v8::internal::String::kMaxLength, v8::internal::kTaggedAligned, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), v8::internal::string, and THROW_NEW_ERROR.
NewRawTwoByteString()
template<typename Impl >
MaybeHandle< SeqTwoByteString > v8::internal::FactoryBase< Impl >::NewRawTwoByteString (int length, AllocationType allocation = AllocationType::kYoung, AllocationHint hint = AllocationHint())
Definition at line 846 of file factory-base.cc.
                                                                {
  Tagged<Map> map = read_only_roots().seq_two_byte_string_map();
  return NewRawStringWithMap<SeqTwoByteString>(
      length, map,
      RefineAllocationTypeForInPlaceInternalizableString(allocation, map),
      hint);
}
References v8::internal::length.
Referenced by v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCase(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CreateExternalizableString(), v8::internal::Uri::Decode(), v8::internal::anonymous_namespace{js-regexp.cc}::EscapeRegExpSource(), v8::internal::IncrementalStringBuilder::Extend(), v8::internal::anonymous_namespace{json-stringifier.cc}::FastJsonStringify(), v8::internal::anonymous_namespace{intl-objects.cc}::LocaleConvertCase(), v8::internal::anonymous_namespace{factory.cc}::NewStringFromBytes(), v8::internal::Factory::NewSurrogatePairString(), v8::internal::ValueDeserializer::ReadTwoByteString(), v8::internal::requires(), v8::internal::RUNTIME_FUNCTION(), v8::internal::StringReplaceGlobalAtomRegExpWithString(), v8::internal::StringReplaceGlobalRegExpWithEmptyString(), v8::internal::ReplacementStringBuilder::ToString(), and v8::internal::anonymous_namespace{uri.cc}::UnescapeSlow().
NewRegExpBoilerplateDescription()
template<typename Impl >
DirectHandle< RegExpBoilerplateDescription > v8::internal::FactoryBase< Impl >::NewRegExpBoilerplateDescription (DirectHandle< RegExpData > data, DirectHandle< String > source, Tagged< Smi > flags)
Definition at line 651 of file factory-base.cc.
                       {
  auto result = NewStructInternal<RegExpBoilerplateDescription>(
      REG_EXP_BOILERPLATE_DESCRIPTION_TYPE, AllocationType::kOld);
  DisallowGarbageCollection no_gc;
  result->set_data(*data);
  result->set_source(*source);
  result->set_flags(flags.value());
  return direct_handle(result, isolate());
}
References v8::internal::direct_handle(), v8::internal::flags, v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
NewRegExpDataWrapper()
template<typename Impl >
DirectHandle< RegExpDataWrapper > v8::internal::FactoryBase< Impl >::NewRegExpDataWrapper
Definition at line 640 of file factory-base.cc.
                                                                        {
  DirectHandle<RegExpDataWrapper> wrapper(
      Cast<RegExpDataWrapper>(NewWithImmortalMap(
          read_only_roots().regexp_data_wrapper_map(), AllocationType::kOld)),
      isolate());
  wrapper->clear_data();
  return wrapper;
}
References v8::internal::kOld.
NewScopeInfo()
template<typename Impl >
Handle< ScopeInfo > v8::internal::FactoryBase< Impl >::NewScopeInfo (int length, AllocationType type = AllocationType::kOld)
Definition at line 1159 of file factory-base.cc.
                                                                       {
  DCHECK(type == AllocationType::kOld || type == AllocationType::kReadOnly);
  int size = ScopeInfo::SizeFor(length);
  Tagged<HeapObject> obj = AllocateRawWithImmortalMap(
      size, type, read_only_roots().scope_info_map());
  Tagged<ScopeInfo> scope_info = Cast<ScopeInfo>(obj);
  MemsetTagged(scope_info->data_start(), read_only_roots().undefined_value(),
               length);
#if TAGGED_SIZE_8_BYTES
  scope_info->set_optional_padding(0);
#endif
  return handle(scope_info, isolate());
}
References v8::internal::DCHECK(), v8::internal::handle(), v8::internal::kOld, v8::internal::kReadOnly, v8::internal::length, v8::internal::MemsetTagged(), size(), v8::internal::ScopeInfo::SizeFor(), and v8::internal::tracing::type.
Referenced by v8::internal::ScopeInfo::CreateForBootstrapping().
NewScript()
template<typename Impl >
Handle< Script > v8::internal::FactoryBase< Impl >::NewScript (DirectHandle< UnionOf< String, Undefined >> source, ScriptEventType event_type = ScriptEventType::kCreate)
Definition at line 384 of file factory-base.cc.
                                       {
  return NewScriptWithId(source, isolate()->GetNextScriptId(),
                         script_event_type);
}
Referenced by v8::internal::Genesis::CreateEmptyFunction(), v8::internal::Heap::CreateInitialMutableObjects(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), and v8::internal::JsonParser< Char >::ReportUnexpectedToken().
NewScriptWithId()
template<typename Impl >
Handle< Script > v8::internal::FactoryBase< Impl >::NewScriptWithId (DirectHandle< UnionOf< String, Undefined >> source, int script_id, ScriptEventType event_type = ScriptEventType::kCreate)
Definition at line 392 of file factory-base.cc.
                                       {
  DCHECK(IsString(*source) || IsUndefined(*source));
  // Create and initialize script object.
  ReadOnlyRoots roots = read_only_roots();
  Handle<Script> script = handle(
      NewStructInternal<Script>(SCRIPT_TYPE, AllocationType::kOld), isolate());
  {
    DisallowGarbageCollection no_gc;
    Tagged<Script> raw = *script;
    raw->set_source(*source);
    raw->set_name(roots.undefined_value(), SKIP_WRITE_BARRIER);
    raw->set_id(script_id);
    raw->set_line_offset(0);
    raw->set_column_offset(0);
    raw->set_context_data(roots.undefined_value(), SKIP_WRITE_BARRIER);
    raw->set_type(Script::Type::kNormal);
    raw->set_line_ends(Smi::zero());
    raw->set_eval_from_shared_or_wrapped_arguments(roots.undefined_value(),
                                                   SKIP_WRITE_BARRIER);
    raw->set_eval_from_position(0);
    raw->set_infos(roots.empty_weak_fixed_array(), SKIP_WRITE_BARRIER);
    raw->set_flags(0);
    raw->set_host_defined_options(roots.empty_fixed_array(),
                                  SKIP_WRITE_BARRIER);
    raw->set_source_hash(roots.undefined_value(), SKIP_WRITE_BARRIER);
    raw->set_compiled_lazy_function_positions(roots.undefined_value(),
                                              SKIP_WRITE_BARRIER);
#ifdef V8_SCRIPTORMODULE_LEGACY_LIFETIME
    raw->set_script_or_modules(roots.empty_array_list());
#endif
  }
  impl()->ProcessNewScript(script, script_event_type);
  return script;
}
NewSharedFunctionInfo() [1/2]
template<typename Impl >
Handle< SharedFunctionInfo > v8::internal::FactoryBase< Impl >::NewSharedFunctionInfo (AllocationType allocation) [protected]
Definition at line 1182 of file factory-base.cc.
                               {
  Tagged<Map> map = read_only_roots().shared_function_info_map();
  Tagged<SharedFunctionInfo> shared =
      Cast<SharedFunctionInfo>(NewWithImmortalMap(map, allocation));
  DisallowGarbageCollection no_gc;
  shared->Init(read_only_roots(), isolate()->GetAndIncNextUniqueSfiId());
  return handle(shared, isolate());
}
References v8::internal::handle(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
NewSharedFunctionInfo() [2/2]
template<typename Impl >
Handle< SharedFunctionInfo > v8::internal::FactoryBase< Impl >::NewSharedFunctionInfo (MaybeDirectHandle< String > maybe_name, MaybeDirectHandle< HeapObject > maybe_function_data, Builtin builtin, int len, AdaptArguments adapt, FunctionKind kind = FunctionKind::kNormalFunction) [protected]
Definition at line 555 of file factory-base.cc.
                                             {
  Handle<SharedFunctionInfo> shared =
      NewSharedFunctionInfo(AllocationType::kOld);
  DisallowGarbageCollection no_gc;
  Tagged<SharedFunctionInfo> raw = *shared;
  // Function names are assumed to be flat elsewhere.
  DirectHandle<String> shared_name;
  bool has_shared_name = maybe_name.ToHandle(&shared_name);
  if (has_shared_name) {
    DCHECK(shared_name->IsFlat());
    raw->set_name_or_scope_info(*shared_name, kReleaseStore);
  } else {
    DCHECK_EQ(raw->name_or_scope_info(kAcquireLoad),
              SharedFunctionInfo::kNoSharedNameSentinel);
  }
  DirectHandle<HeapObject> function_data;
  if (maybe_function_data.ToHandle(&function_data)) {
    // If we pass function_data then we shouldn't pass a builtin index, and
    // the function_data should not be code with a builtin.
    DCHECK(!Builtins::IsBuiltinId(builtin));
    DCHECK(!IsInstructionStream(*function_data));
    DCHECK(!IsCode(*function_data));
    if (IsExposedTrustedObject(*function_data)) {
      raw->SetTrustedData(Cast<ExposedTrustedObject>(*function_data));
    } else {
      raw->SetUntrustedData(*function_data);
    }
  } else if (Builtins::IsBuiltinId(builtin)) {
    raw->set_builtin_id(builtin);
  } else {
    DCHECK(raw->HasBuiltinId());
    DCHECK_EQ(Builtin::kIllegal, raw->builtin_id());
  }
  raw->CalculateConstructAsBuiltin();
  raw->set_kind(kind);
  switch (adapt) {
    case AdaptArguments::kYes:
      raw->set_formal_parameter_count(JSParameterCount(len));
      break;
    case AdaptArguments::kNo:
      raw->DontAdaptArguments();
      break;
  }
  raw->set_length(len);
  DCHECK_IMPLIES(raw->HasBuiltinId(),
                 Builtins::CheckFormalParameterCount(
                     raw->builtin_id(), raw->length(),
                     raw->internal_formal_parameter_count_with_receiver()));
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) raw->SharedFunctionInfoVerify(isolate());
#endif // VERIFY_HEAP
  return shared;
}
References v8::internal::Builtins::CheckFormalParameterCount(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Builtins::IsBuiltinId(), v8::internal::JSParameterCount(), v8::kAcquireLoad, v8::internal::kNo, v8::internal::SharedFunctionInfo::kNoSharedNameSentinel, v8::internal::kOld, v8::kReleaseStore, v8::internal::kYes, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::MaybeDirectHandle< T >::ToHandle(), and v8::internal::v8_flags.
NewSharedFunctionInfoForLiteral()
template<typename Impl >
Handle< SharedFunctionInfo > v8::internal::FactoryBase< Impl >::NewSharedFunctionInfoForLiteral (FunctionLiteral * literal, DirectHandle< Script > script, bool is_toplevel)
Definition at line 456 of file factory-base.cc.
                                                                             {
  FunctionKind kind = literal->kind();
  Handle<SharedFunctionInfo> shared =
      NewSharedFunctionInfo(literal->GetName(isolate()), {},
                            Builtin::kCompileLazy, 0, kDontAdapt, kind);
  shared->set_function_literal_id(literal->function_literal_id(),
                                  kRelaxedStore);
  literal->set_shared_function_info(shared);
  SharedFunctionInfo::InitFromFunctionLiteral(isolate(), literal, is_toplevel);
  shared->SetScript(isolate(), read_only_roots(), *script,
                    literal->function_literal_id(), false);
  return shared;
}
NewSharedFunctionInfoWrapper()
template<typename Impl >
DirectHandle< SharedFunctionInfoWrapper > v8::internal::FactoryBase< Impl >::NewSharedFunctionInfoWrapper (DirectHandle< SharedFunctionInfo > sfi)
Definition at line 488 of file factory-base.cc.
                                          {
  Tagged<Map> map = read_only_roots().shared_function_info_wrapper_map();
  Tagged<SharedFunctionInfoWrapper> wrapper = Cast<SharedFunctionInfoWrapper>(
      NewWithImmortalMap(map, AllocationType::kTrusted));
  wrapper->set_shared_info(*sfi);
  return direct_handle(wrapper, isolate());
}
References v8::internal::direct_handle(), and v8::internal::kTrusted.
Referenced by v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), and v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData().
NewSloppyArgumentsElements()
template<typename Impl >
DirectHandle< SloppyArgumentsElements > v8::internal::FactoryBase< Impl >::NewSloppyArgumentsElements (int length, DirectHandle< Context > context, DirectHandle< FixedArray > arguments, AllocationType allocation = AllocationType::kYoung)
Definition at line 431 of file factory-base.cc.
                                                                   {
  Tagged<SloppyArgumentsElements> result =
      Cast<SloppyArgumentsElements>(AllocateRawWithImmortalMap(
          SloppyArgumentsElements::SizeFor(length), allocation,
          read_only_roots().sloppy_arguments_elements_map()));
  DisallowGarbageCollection no_gc;
  WriteBarrierMode write_barrier_mode = allocation == AllocationType::kYoung
                                            ? SKIP_WRITE_BARRIER
                                            : UPDATE_WRITE_BARRIER;
  result->set_length(length);
  result->set_context(*context, write_barrier_mode);
  result->set_arguments(*arguments, write_barrier_mode);
  return direct_handle(result, isolate());
}
Referenced by v8::internal::anonymous_namespace{runtime-scopes.cc}::NewSloppyArguments().
NewSourceTextModuleInfo()
template<typename Impl >
DirectHandle< SourceTextModuleInfo > v8::internal::FactoryBase< Impl >::NewSourceTextModuleInfo
Definition at line 1176 of file factory-base.cc.
                                           {
  return Cast<SourceTextModuleInfo>(NewFixedArrayWithMap(
      module_info_map(), SourceTextModuleInfo::kLength, AllocationType::kOld));
}
References v8::internal::SourceTextModuleInfo::kLength, and v8::internal::kOld.
NewStringFromAsciiChecked() [1/2]
template<typename Impl >
Handle<String> v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked (const char * str, AllocationType allocation = AllocationType::kYoung) [inline]
Definition at line 325 of file factory-base.h.
                                                                         {
    return NewStringFromOneByte(base::OneByteVector(str), allocation)
        .ToHandleChecked();
  }
References v8::base::OneByteVector().
Referenced by v8::internal::anonymous_namespace{runtime-debug.cc}::AddIteratorInternalProperties(), v8::internal::AddWasmInstanceObjectInternalProperties(), v8::ValueSerializer::Delegate::AdoptSharedValueConveyor(), v8::internal::anonymous_namespace{builtins-arraybuffer.cc}::ArrayBufferTransfer(), v8::internal::anonymous_namespace{intl-objects.cc}::AvailableUnits(), v8::internal::JSLocale::BaseName(), v8::internal::BUILTIN(), v8::internal::anonymous_namespace{builtins-sharedarraybuffer.cc}::CheckAtomicsPauseIterationNumber(), v8::internal::JSTemporalInstant::Constructor(), v8::internal::JSTemporalPlainTime::Constructor(), v8::internal::JSTemporalPlainMonthDay::Constructor(), v8::internal::JSTemporalPlainYearMonth::Constructor(), v8::internal::JSTemporalPlainDate::Constructor(), v8::internal::JSTemporalPlainDateTime::Constructor(), v8::internal::JSTemporalDuration::Constructor(), v8::internal::anonymous_namespace{externalize-string-extension.cc}::CopyConsStringToOld(), v8::internal::anonymous_namespace{basic-block-profiler.cc}::CopyStringToJSHeap(), v8::internal::anonymous_namespace{js-plural-rules.cc}::CreateDataPropertyForOptions(), v8::internal::anonymous_namespace{js-collator.cc}::CreateDataPropertyForOptions(), v8::internal::JSDateTimeFormat::CreateDateTimeFormat(), v8::internal::Object::CreateListFromArrayLike(), v8::internal::anonymous_namespace{builtins-intl.cc}::DisallowCallConstructor(), v8::internal::DoWait(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::FailAssert(), v8::internal::wasm::JSToWasmWrapperCompilationUnit::Finalize(), v8::internal::anonymous_namespace{js-relative-time-format.cc}::FormatCommon(), v8::internal::FormattedListToJSArray(), v8::debug::anonymous_namespace{debug-interface.cc}::GetBigIntStringPresentationHandle(), v8::internal::GetBoolOption(), v8::internal::anonymous_namespace{js-date-time-format.cc}::GetCalendar(), v8::internal::CallSiteInfo::GetFunctionName(), v8::internal::JSLocale::GetHourCycles(), v8::internal::Runtime::GetInternalProperties(), v8::internal::GetKeywordValuesFromLocale(), v8::internal::JSLocale::GetNumberingSystems(), wasm::anonymous_namespace{c-api.cc}::GetProperException(), v8::internal::Script::GetScriptHash(), v8::internal::GetStringOption(), v8::internal::GetStringOrBooleanOption(), v8::internal::temporal::GetTemporalUnit(), v8::internal::String::IndexOf(), v8::internal::JSProxy::IsArray(), v8::internal::JSLocale::Language(), v8::internal::String::LastIndexOf(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::JSV8BreakIterator::New(), v8::internal::JSListFormat::New(), v8::internal::JSPluralRules::New(), v8::internal::JSRelativeTimeFormat::New(), v8::internal::JSSegmenter::New(), v8::internal::JSCollator::New(), v8::internal::JSNumberFormat::New(), v8::internal::WasmGlobalObject::New(), v8::internal::Object::NoSideEffectsToString(), v8::internal::RegExpUtils::RegExpExec(), v8::internal::JSLocale::Region(), v8::internal::ResizeHelper(), v8::internal::JSDateTimeFormat::ResolvedOptions(), v8::internal::JSDisplayNames::ResolvedOptions(), v8::internal::JSDurationFormat::ResolvedOptions(), v8::internal::JSNumberFormat::ResolvedOptions(), v8::internal::RUNTIME_FUNCTION(), v8::internal::JSLocale::Script(), v8::internal::SliceHelper(), v8::internal::Isolate::StackOverflow(), v8::internal::JSRegExp::StringFromFlags(), v8::internal::anonymous_namespace{factory-base.cc}::StringViewToString(), v8::internal::anonymous_namespace{builtins-bigint.cc}::ThisBigIntValue(), v8::internal::Object::ToObjectImpl(), v8::internal::JSLocale::ToString(), v8::internal::ErrorUtils::ToString(), v8::internal::anonymous_namespace{js-locale.cc}::UnicodeKeywordValue(), v8::internal::JSDateTimeFormat::UnwrapDateTimeFormat(), v8::internal::JSNumberFormat::UnwrapNumberFormat(), v8::anonymous_namespace{wasm-js.cc}::v8_str(), v8::internal::JSTypedArray::Validate(), v8::internal::Intl::ValidateAndCanonicalizeUnicodeLocaleId(), v8::Isolate::ValidateAndCanonicalizeUnicodeLocaleId(), v8::internal::ValidateIntegerTypedArray(), v8::internal::anonymous_namespace{intl-objects.cc}::VectorToJSArray(), and v8::internal::anonymous_namespace{debug-wasm-objects.cc}::WasmSimd128ToString().
NewStringFromAsciiChecked() [2/2]
template<typename Impl >
Handle<String> v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked (std::string_view str, AllocationType allocation = AllocationType::kYoung) [inline]
Definition at line 331 of file factory-base.h.
                                                        {
    return NewStringFromOneByte(base::OneByteVector(str.data(), str.length()),
                                allocation)
        .ToHandleChecked();
  }
References v8::base::OneByteVector().
NewStringFromOneByte()
template<typename Impl >
MaybeHandle< String > v8::internal::FactoryBase< Impl >::NewStringFromOneByte (base::Vector< const uint8_t > string, AllocationType allocation = AllocationType::kYoung)
Definition at line 987 of file factory-base.cc.
                                                                 {
  DCHECK_NE(allocation, AllocationType::kReadOnly);
  int length = string.length();
  if (length == 0) return empty_string();
  if (length == 1) return LookupSingleCharacterStringFromCode(string[0]);
  Handle<SeqOneByteString> result;
  ASSIGN_RETURN_ON_EXCEPTION(isolate(), result,
                             NewRawOneByteString(string.length(), allocation));
  DisallowGarbageCollection no_gc;
  // Copy the characters into the new object.
  // SharedStringAccessGuardIfNeeded is NotNeeded because {result} is freshly
  // allocated and hasn't escaped the factory yet, so it can't be concurrently
  // accessed.
  CopyChars(Cast<SeqOneByteString>(*result)->GetChars(
                no_gc, SharedStringAccessGuardIfNeeded::NotNeeded()),
            string.begin(), length);
  return result;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::CopyChars(), DCHECK_NE, v8::internal::kReadOnly, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SharedStringAccessGuardIfNeeded::NotNeeded(), and v8::base::internal::result.
Referenced by v8::internal::SourceCodeCache::Add(), v8::internal::Uri::Decode(), v8::internal::Uri::Encode(), v8::internal::WasmExportedFunction::New(), v8::anonymous_namespace{api.cc}::NewString(), v8::internal::ValueDeserializer::ReadOneByteString(), v8::internal::JsonStringifier::Stringify(), and v8::internal::RegExp::ThrowRegExpException().
NewStruct()
template<typename Impl >
Handle< Struct > v8::internal::FactoryBase< Impl >::NewStruct (InstanceType type, AllocationType allocation = AllocationType::kYoung)
Definition at line 65 of file factory-base.cc.
                                                                       {
  ReadOnlyRoots roots = read_only_roots();
  Tagged<Map> map = Map::GetMapFor(roots, type);
  int size = map->instance_size();
  return handle(NewStructInternal(roots, map, size, allocation), isolate());
}
References v8::internal::Map::GetMapFor(), v8::internal::handle(), size(), and v8::internal::tracing::type.
Referenced by v8::internal::WasmExceptionTag::New(), v8::internal::AsmWasmData::New(), v8::ObjectTemplate::SetAccessCheckCallback(), and v8::ObjectTemplate::SetAccessCheckCallbackAndHandler().
NewStructInternal() [1/2]
template<typename Impl >
template<typename StructType >
Tagged< StructType > v8::internal::FactoryBase< Impl >::NewStructInternal (InstanceType type, AllocationType allocation) [inline], [protected]
Definition at line 133 of file factory-base-inl.h.
                                                  {
  ReadOnlyRoots roots = read_only_roots();
  Tagged<Map> map = Map::GetMapFor(roots, type);
  int size;
  if constexpr (std::is_base_of_v<StructLayout, StructType>) {
    size = sizeof(StructType);
  } else {
    size = StructType::kSize;
  }
  return Cast<StructType>(NewStructInternal(roots, map, size, allocation));
}
NewStructInternal() [2/2]
template<typename Impl >
Tagged< Struct > v8::internal::FactoryBase< Impl >::NewStructInternal (ReadOnlyRoots roots, Tagged< Map > map, int size, AllocationType allocation) [protected]
Definition at line 147 of file factory-base-inl.h.
                                                                               {
  DCHECK_EQ(size, map->instance_size());
  Tagged<HeapObject> result = AllocateRawWithImmortalMap(size, allocation, map);
  Tagged<Struct> str = Cast<Struct>(result);
  Tagged<Undefined> undefined = roots.undefined_value();
  int length = (size >> kTaggedSizeLog2) - 1;
  MemsetTagged(str->RawField(Struct::kHeaderSize), undefined, length);
  return str;
}
References DCHECK_EQ, v8::internal::kTaggedSizeLog2, v8::internal::length, v8::internal::MemsetTagged(), v8::base::internal::result, size(), and v8::internal::undefined.
NewSwissNameDictionary()
template<typename Impl >
Handle< SwissNameDictionary > v8::internal::FactoryBase< Impl >::NewSwissNameDictionary (int at_least_space_for = kSwissNameDictionaryInitialCapacity, AllocationType allocation = AllocationType::kYoung)
Definition at line 1376 of file factory-base.cc.
                                                       {
  return NewSwissNameDictionaryWithCapacity(
      SwissNameDictionary::CapacityFor(at_least_space_for), allocation);
}
References v8::internal::SwissNameDictionary::CapacityFor().
Referenced by v8::internal::JSRegExpResultIndices::BuildIndices(), v8::internal::anonymous_namespace{js-objects.cc}::MigrateFastToSlow(), and v8::Object::New().
NewSwissNameDictionaryWithCapacity()
template<typename Impl >
Handle< SwissNameDictionary > v8::internal::FactoryBase< Impl >::NewSwissNameDictionaryWithCapacity (int capacity, AllocationType allocation)
Definition at line 1345 of file factory-base.cc.
                                             {
  DCHECK(SwissNameDictionary::IsValidCapacity(capacity));
  if (capacity == 0) {
    DCHECK_NE(
        read_only_roots().address_at(RootIndex::kEmptySwissPropertyDictionary),
        kNullAddress);
    return empty_swiss_property_dictionary();
  }
  if (capacity < 0 || capacity > SwissNameDictionary::MaxCapacity()) {
    FATAL("Fatal JavaScript invalid size error %d", capacity);
    UNREACHABLE();
  }
  int meta_table_length = SwissNameDictionary::MetaTableSizeFor(capacity);
  DirectHandle<ByteArray> meta_table =
      impl()->NewByteArray(meta_table_length, allocation);
  Tagged<Map> map = read_only_roots().swiss_name_dictionary_map();
  int size = SwissNameDictionary::SizeFor(capacity);
  Tagged<SwissNameDictionary> table = Cast<SwissNameDictionary>(
      AllocateRawWithImmortalMap(size, allocation, map));
  DisallowGarbageCollection no_gc;
  table->Initialize(isolate(), *meta_table, capacity);
  return handle(table, isolate());
}
References v8::internal::DCHECK(), DCHECK_NE, FATAL, v8::internal::handle(), wasm::impl(), v8::internal::SwissNameDictionary::IsValidCapacity(), v8::internal::kNullAddress, v8::internal::SwissNameDictionary::MaxCapacity(), v8::internal::SwissNameDictionary::MetaTableSizeFor(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, size(), v8::internal::SwissNameDictionary::SizeFor(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::SwissNameDictionary::ShallowCopy().
NewTemplateObjectDescription()
template<typename Impl >
Handle< TemplateObjectDescription > v8::internal::FactoryBase< Impl >::NewTemplateObjectDescription (DirectHandle< FixedArray > raw_strings, DirectHandle< FixedArray > cooked_strings)
Definition at line 665 of file factory-base.cc.
                                             {
  DCHECK_EQ(raw_strings->length(), cooked_strings->length());
  DCHECK_LT(0, raw_strings->length());
  auto result = NewStructInternal<TemplateObjectDescription>(
      TEMPLATE_OBJECT_DESCRIPTION_TYPE, AllocationType::kOld);
  DisallowGarbageCollection no_gc;
  result->set_raw_strings(*raw_strings);
  result->set_cooked_strings(*cooked_strings);
  return handle(result, isolate());
}
References DCHECK_EQ, DCHECK_LT, v8::internal::handle(), v8::internal::kOld, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::base::internal::result.
NewTrustedByteArray()
template<typename Impl >
Handle< TrustedByteArray > v8::internal::FactoryBase< Impl >::NewTrustedByteArray (int length, AllocationType allocation_type = AllocationType::kTrusted)
Definition at line 311 of file factory-base.cc.
                                                {
  if (length == 0) return empty_trusted_byte_array();
  return TrustedByteArray::New(isolate(), length, allocation_type);
}
Referenced by v8::internal::RegExpBytecodeGenerator::GetCode(), v8::internal::TrustedPodArray< T >::New(), v8::internal::RegExpBytecodePeepholeOptimization::OptimizeBytecode(), and v8::internal::VectorToByteArray().
NewTrustedFixedArray()
template<typename Impl >
Handle< TrustedFixedArray > v8::internal::FactoryBase< Impl >::NewTrustedFixedArray (int length, AllocationType allocation = AllocationType::kTrusted)
Definition at line 186 of file factory-base.cc.
                                           {
  DCHECK(allocation == AllocationType::kTrusted ||
         allocation == AllocationType::kSharedTrusted);
  // TODO(saelo): Move this check to TrustedFixedArray::New once we have a RO
  // trusted space.
  if (length == 0) return empty_trusted_fixed_array();
  return TrustedFixedArray::New(isolate(), length, allocation);
}
NewTrustedWeakFixedArray()
template<typename Impl >
Handle< TrustedWeakFixedArray > v8::internal::FactoryBase< Impl >::NewTrustedWeakFixedArray (int length)
Definition at line 287 of file factory-base.cc.
                {
  // TODO(saelo): Move this check to TrustedWeakFixedArray::New once we have a
  // RO trusted space.
  if (length == 0) return empty_trusted_weak_fixed_array();
  return TrustedWeakFixedArray::New(isolate(), length);
}
NewTwoByteInternalizedString()
template<typename Impl >
Handle< SeqTwoByteString > v8::internal::FactoryBase< Impl >::NewTwoByteInternalizedString (base::Vector< const base::uc16 > str, uint32_t raw_hash_field)
Definition at line 784 of file factory-base.cc.
                                                             {
  Handle<SeqTwoByteString> result =
      AllocateRawTwoByteInternalizedString(str.length(), raw_hash_field);
  // No synchronization is needed since the shared string hasn't yet escaped to
  // script.
  DisallowGarbageCollection no_gc;
  MemCopy(result->GetChars(no_gc, SharedStringAccessGuardIfNeeded::NotNeeded()),
          str.begin(), str.length() * base::kUC16Size);
  return result;
}
References v8::base::Vector< T >::begin(), v8::base::kUC16Size, v8::base::Vector< T >::length(), v8::internal::MemCopy(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SharedStringAccessGuardIfNeeded::NotNeeded(), and v8::base::internal::result.
NewUncompiledDataWithoutPreparseData()
template<typename Impl >
DirectHandle< UncompiledDataWithoutPreparseData > v8::internal::FactoryBase< Impl >::NewUncompiledDataWithoutPreparseData (Handle< String > inferred_name, int32_t start_position, int32_t end_position)
Definition at line 516 of file factory-base.cc.
                          {
  return TorqueGeneratedFactory<Impl>::NewUncompiledDataWithoutPreparseData(
      inferred_name, start_position, end_position, AllocationType::kTrusted);
}
References v8::internal::kTrusted.
Referenced by v8::internal::SharedFunctionInfo::DiscardCompiled().
NewUncompiledDataWithoutPreparseDataWithJob()
template<typename Impl >
DirectHandle< UncompiledDataWithoutPreparseDataWithJob > v8::internal::FactoryBase< Impl >::NewUncompiledDataWithoutPreparseDataWithJob (Handle< String > inferred_name, int32_t start_position, int32_t end_position)
Definition at line 535 of file factory-base.cc.
                          {
  return TorqueGeneratedFactory<Impl>::
      NewUncompiledDataWithoutPreparseDataWithJob(inferred_name, start_position,
                                                  end_position, kNullAddress,
                                                  AllocationType::kTrusted);
}
References v8::internal::kNullAddress, and v8::internal::kTrusted.
Referenced by v8::internal::anonymous_namespace{lazy-compile-dispatcher.cc}::SetUncompiledDataJobPointer().
NewUncompiledDataWithPreparseData()
template<typename Impl >
DirectHandle< UncompiledDataWithPreparseData > v8::internal::FactoryBase< Impl >::NewUncompiledDataWithPreparseData (Handle< String > inferred_name, int32_t start_position, int32_t end_position, Handle< PreparseData > preparse_data)
Definition at line 525 of file factory-base.cc.
                                        {
  return TorqueGeneratedFactory<Impl>::NewUncompiledDataWithPreparseData(
      inferred_name, start_position, end_position, preparse_data,
      AllocationType::kTrusted);
}
References v8::internal::kTrusted.
NewUncompiledDataWithPreparseDataAndJob()
template<typename Impl >
DirectHandle< UncompiledDataWithPreparseDataAndJob > v8::internal::FactoryBase< Impl >::NewUncompiledDataWithPreparseDataAndJob (Handle< String > inferred_name, int32_t start_position, int32_t end_position, Handle< PreparseData > preparse_data)
Definition at line 546 of file factory-base.cc.
                                        {
  return TorqueGeneratedFactory<Impl>::NewUncompiledDataWithPreparseDataAndJob(
      inferred_name, start_position, end_position, preparse_data, kNullAddress,
      AllocationType::kTrusted);
}
References v8::internal::kNullAddress, and v8::internal::kTrusted.
Referenced by v8::internal::anonymous_namespace{lazy-compile-dispatcher.cc}::SetUncompiledDataJobPointer().
NewWeakFixedArray()
template<typename Impl >
Handle< WeakFixedArray > v8::internal::FactoryBase< Impl >::NewWeakFixedArray (int length, AllocationType allocation = AllocationType::kYoung)
Definition at line 281 of file factory-base.cc.
                                           {
  return WeakFixedArray::New(isolate(), length, allocation);
}
References v8::internal::length, and v8::internal::WeakFixedArray::New().
Referenced by v8::internal::anonymous_namespace{compilation-cache-table.cc}::AddToJSFunctionMap(), v8::internal::ScriptCacheKey::AsHandle(), v8::internal::FeedbackNexus::CreateArrayOfSize(), v8::internal::Genesis::CreateEmptyFunction(), v8::internal::MemoryMeasurement::EnqueueRequest(), v8::internal::baseline::BaselineBatchCompiler::EnsureQueueCapacity(), v8::internal::Genesis::InitializeMapCaches(), and v8::internal::NormalizedMapCache::New().
NewWeakFixedArrayWithMap()
template<typename Impl >
Handle< WeakFixedArray > v8::internal::FactoryBase< Impl >::NewWeakFixedArrayWithMap (Tagged< Map > map, int length, AllocationType allocation = AllocationType::kYoung)
Definition at line 262 of file factory-base.cc.
                                                            {
  // Zero-length case must be handled outside.
  DCHECK_LT(0, length);
  DCHECK(ReadOnlyHeap::Contains(map));
  Tagged<HeapObject> result =
      AllocateRawArray(WeakFixedArray::SizeFor(length), allocation);
  result->set_map_after_allocation(isolate(), map, SKIP_WRITE_BARRIER);
  DisallowGarbageCollection no_gc;
  Tagged<WeakFixedArray> array = Cast<WeakFixedArray>(result);
  array->set_length(length);
  MemsetTagged(ObjectSlot(array->RawFieldOfFirstElement()),
               read_only_roots().undefined_value(), length);
  return handle(array, isolate());
}
NewWithImmortalMap()
template<typename Impl >
Tagged< HeapObject > v8::internal::FactoryBase< Impl >::NewWithImmortalMap (Tagged< Map > map, AllocationType allocation) [protected]
Definition at line 1316 of file factory-base.cc.
                                                {
  return AllocateRawWithImmortalMap(map->instance_size(), allocation, map);
}
NumberToString()
template<typename Impl >
Handle< String > v8::internal::FactoryBase< Impl >::NumberToString (DirectHandle< Object > number, NumberCacheMode mode = NumberCacheMode::kBoth)
Definition at line 1024 of file factory-base.cc.
                                                                       {
  SLOW_DCHECK(IsNumber(*number));
  if (IsSmi(*number)) return SmiToString(Cast<Smi>(*number), mode);
  double double_value = Cast<HeapNumber>(number)->value();
  // Try to canonicalize doubles.
  return DoubleToString(double_value, true, mode);
}
References v8::internal::IsNumber(), v8::internal::IsSmi(), mode(), and SLOW_DCHECK.
Referenced by v8::internal::anonymous_namespace{messages.cc}::BuildDefaultCallSite(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JsonParseInternalizer::InternalizeJsonProperty(), v8::internal::CallPrinter::PrintLiteral(), and v8::internal::IntlMathematicalValue::ToString().
read_only_roots()
template<typename Impl >
ReadOnlyRoots v8::internal::FactoryBase< Impl >::read_only_roots () [inline], [private]
Definition at line 456 of file factory-base.h.
{ return impl()->read_only_roots(); }
References wasm::impl().
RefineAllocationTypeForInPlaceInternalizableString()
template<typename Impl >
AllocationType v8::internal::FactoryBase< Impl >::RefineAllocationTypeForInPlaceInternalizableString (AllocationType allocation, Tagged< Map > string_map)
Definition at line 1425 of file factory-base.cc.
                                                       {
#ifdef DEBUG
  InstanceType instance_type = string_map->instance_type();
  DCHECK(InstanceTypeChecker::IsInternalizedString(instance_type) ||
         String::IsInPlaceInternalizable(instance_type));
#endif
  if (v8_flags.single_generation && allocation == AllocationType::kYoung) {
    allocation = AllocationType::kOld;
  }
  if (allocation != AllocationType::kOld) return allocation;
  return impl()->AllocationTypeForInPlaceInternalizableString();
}
References v8::internal::DCHECK(), wasm::impl(), v8::internal::String::IsInPlaceInternalizable(), v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::kOld, v8::internal::kYoung, and v8::internal::v8_flags.
SmiToString()
template<typename Impl >
Handle< String > v8::internal::FactoryBase< Impl >::SmiToString (Tagged< Smi > number, NumberCacheMode mode = NumberCacheMode::kBoth) [inline]
Definition at line 1084 of file factory-base.cc.
                                                                           {
  // LINT.IfChange(CheckPreallocatedNumberStrings)
  {
    DCHECK_EQ(kPreallocatedNumberStringTableSize,
              preallocated_number_string_table()->length());
    int index = number.value();
    if (static_cast<unsigned>(index) < kPreallocatedNumberStringTableSize) {
      return handle(
          Cast<String>(preallocated_number_string_table()->get(index)),
          isolate());
    }
  }
  // LINT.ThenChange(/src/codegen/code-stub-assembler.cc:CheckPreallocatedNumberStrings)
  // LocalFactory does not have access to the number_string_cache, only
  // main thread Factory does (since it's a mutable root).
  constexpr bool kCanUseCache = std::is_same_v<Impl, Factory>;
  InternalIndex entry = InternalIndex::NotFound();
  if constexpr (kCanUseCache) {
    if (mode != NumberCacheMode::kIgnore) {
      entry = SmiStringCache::GetEntryFor(isolate(), number);
    }
    if (mode == NumberCacheMode::kBoth) {
      Handle<Object> cached = SmiStringCache::Get(isolate(), entry, number);
      if (!IsUndefined(*cached, isolate())) return Cast<String>(cached);
    }
  }
  Handle<String> result;
  {
    char arr[kNumberToStringBufferSize];
    base::Vector<char> buffer(arr, arraysize(arr));
    std::string_view string = IntToStringView(number.value(), buffer);
    result = StringViewToString(this, string, mode);
  }
  if constexpr (kCanUseCache) {
    if (mode != NumberCacheMode::kIgnore) {
      SmiStringCache::Set(isolate(), entry, number, result);
    }
  }
  // Compute the hash here (rather than letting the caller take care of it) so
  // that the "cache hit" case above doesn't have to bother with it.
  static_assert(Smi::kMaxValue <= std::numeric_limits<uint32_t>::max());
  {
    DisallowGarbageCollection no_gc;
    Tagged<String> raw = *result;
    if (raw->raw_hash_field() == String::kEmptyHashField &&
        number.value() >= 0) {
      uint32_t raw_hash_field = StringHasher::MakeArrayIndexHash(
          static_cast<uint32_t>(number.value()), raw->length());
      raw->set_raw_hash_field(raw_hash_field);
    }
  }
  return result;
}
References arraysize, DCHECK_EQ, v8::internal::SmiStringCache::Get(), v8::internal::SmiStringCache::GetEntryFor(), v8::internal::handle(), v8::internal::index, v8::internal::IntToStringView(), v8::internal::kBoth, v8::internal::Name::kEmptyHashField, v8::internal::kIgnore, v8::internal::Smi::kMaxValue, v8::internal::kPreallocatedNumberStringTableSize, v8::internal::length, v8::internal::StringHasher::MakeArrayIndexHash(), mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::InternalIndex::NotFound(), v8::base::internal::result, v8::internal::SmiStringCache::Set(), v8::internal::anonymous_namespace{factory-base.cc}::StringViewToString(), and v8::internal::Tagged< Smi >::value().
Referenced by v8::internal::JsonStringifier::ApplyReplacerFunction(), and v8::internal::JsonStringifier::ApplyToJsonFunction().
ToBoolean()
template<typename Impl >
Handle< Boolean > v8::internal::FactoryBase< Impl >::ToBoolean (bool value) [inline]
Definition at line 43 of file factory-base-inl.h.
                                                       {
  return value ? Cast<Boolean>(impl()->true_value())
               : Cast<Boolean>(impl()->false_value());
}
References wasm::impl(), and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{runtime-debug.cc}::AddIteratorInternalProperties(), v8::internal::JSTemporalDuration::Blank(), v8::internal::compiler::CodeAssembler::BooleanConstant(), v8::internal::anonymous_namespace{js-collator.cc}::CreateDataPropertyForOptions(), v8::internal::JSAtomicsMutex::CreateResultObject(), v8::internal::JSSegments::CreateSegmentDataObject(), v8::internal::JSTemporalInstant::Equals(), v8::internal::Runtime::GetInternalProperties(), v8::internal::wasm::GetTypeForGlobal(), v8::internal::Runtime::HasProperty(), v8::internal::Object::InstanceOf(), v8::internal::JSProxy::IsExtensible(), v8::internal::LoadIC::Load(), v8::BooleanObject::New(), v8::internal::JSLocale::Numeric(), v8::internal::Object::OrdinaryHasInstance(), v8::internal::RUNTIME_FUNCTION(), v8::Value::ToBoolean(), and v8::internal::PropertyDescriptor::ToObject().
Friends And Related Function Documentation
DoubleStringCache
template<typename Impl >
friend class DoubleStringCache [friend]
Definition at line 467 of file factory-base.h.
PrimitiveArrayBase
template<typename Impl >
template<class Derived , class Shape , class Super >
friend class PrimitiveArrayBase [friend]
Definition at line 466 of file factory-base.h.
TaggedArrayBase
template<typename Impl >
template<class Derived , class Shape , class Super >
friend class TaggedArrayBase [friend]
Definition at line 464 of file factory-base.h.
Member Data Documentation
kNumberToStringBufferSize
template<typename Impl >
constexpr int v8::internal::FactoryBase< Impl >::kNumberToStringBufferSize = 32 [static], [constexpr], [protected]
Definition at line 413 of file factory-base.h.
TorqueGeneratedFactory< Impl >
template<typename Impl >
friend v8::internal::FactoryBase< Impl >::TorqueGeneratedFactory< Impl > [private]
Definition at line 462 of file factory-base.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/factory-base.h
/mnt/V8SourceCode/src/heap/factory-base-inl.h
/mnt/V8SourceCode/src/heap/factory-base.cc