v8::internal::compiler::turboshaft::Int64LoweringReducer< Next > Class Template Reference
#include <int64-lowering-reducer.h>
Public Types
using Word32OrWord32Pair = OpIndex
Public Member Functions
Int64LoweringReducer ()
Word32OrWord32Pair REDUCE() WordBinop (Word32OrWord32Pair left, Word32OrWord32Pair right, WordBinopOp::Kind kind, WordRepresentation rep)
Word32OrWord32Pair REDUCE() Shift (Word32OrWord32Pair left, V< Word32 > right, ShiftOp::Kind kind, WordRepresentation rep)
V< Word32 > REDUCE() Comparison (V< Any > left, V< Any > right, ComparisonOp::Kind kind, RegisterRepresentation rep)
V< Any > REDUCE() Call (V< CallTarget > callee, OptionalV< FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor *descriptor, OpEffects effects)
OpIndex REDUCE() TailCall (OpIndex callee, base::Vector< const OpIndex > arguments, const TSCallDescriptor *descriptor)
OpIndex REDUCE() Constant (ConstantOp::Kind kind, ConstantOp::Storage value)
OpIndex REDUCE() Parameter (int32_t parameter_index, RegisterRepresentation rep, const char *debug_name=``)
V< None > REDUCE() Return (V< Word32 > pop_count, base::Vector< const OpIndex > return_values, bool spill_caller_frame_slots)
Word32OrWord32Pair REDUCE() WordUnary (Word32OrWord32Pair input, WordUnaryOp::Kind kind, WordRepresentation rep)
OpIndex REDUCE() Change (OpIndex input, ChangeOp::Kind kind, ChangeOp::Assumption assumption, RegisterRepresentation from, RegisterRepresentation to)
std::pair< OptionalV< Word32 >, int32_t > IncreaseOffset (OptionalV< Word32 > index, int32_t offset, int32_t add_offset, bool tagged_base)
OpIndex REDUCE() Load (OpIndex base, OptionalOpIndex index, LoadOp::Kind kind, MemoryRepresentation loaded_rep, RegisterRepresentation result_rep, int32_t offset, uint8_t element_scale)
V< None > REDUCE() Store (OpIndex base, OptionalOpIndex index, OpIndex value, StoreOp::Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset, uint8_t element_size_log2, bool maybe_initializing_or_transitioning, IndirectPointerTag maybe_indirect_pointer_tag)
OpIndex REDUCE() AtomicRMW (OpIndex base, OpIndex index, OpIndex value, OptionalOpIndex expected, AtomicRMWOp::BinOp bin_op, RegisterRepresentation in_out_rep, MemoryRepresentation memory_rep, MemoryAccessKind kind, RegisterRepresentation base_rep)
OpIndex REDUCE() Phi (base::Vector< const OpIndex > inputs, RegisterRepresentation rep)
OpIndex REDUCE() PendingLoopPhi (OpIndex input, RegisterRepresentation rep)
void FixLoopPhi (const PhiOp &input_phi, OpIndex output_index, Block *output_graph_loop)
V< Simd128 > REDUCE() Simd128Splat (V< Any > input, Simd128SplatOp::Kind kind)
V< Any > REDUCE() Simd128ExtractLane (V< Simd128 > input, Simd128ExtractLaneOp::Kind kind, uint8_t lane)
V< Simd128 > REDUCE() Simd128ReplaceLane (V< Simd128 > into, V< Any > new_lane, Simd128ReplaceLaneOp::Kind kind, uint8_t lane)
V< turboshaft::FrameState > REDUCE() FrameState (base::Vector< const OpIndex > inputs, bool inlined, const FrameStateData *data)
Private Member Functions
bool CheckPairOrPairOp (V< Word32Pair > input)
std::pair< V< Word32 >, V< Word32 > > Unpack (V< Word32Pair > input)
V< Word32Pair > LowerSignExtend (V< Word32 > input)
V< Word32Pair > LowerClz (V< Word32Pair > input)
V< Word32Pair > LowerCtz (V< Word32Pair > input)
V< Word32Pair > LowerPopCount (V< Word32Pair > input)
V< Word32Pair > LowerPairBinOp (V< Word32Pair > left, V< Word32Pair > right, Word32PairBinopOp::Kind kind)
V< Word32Pair > LowerPairShiftOp (V< Word32Pair > left, V< Word32 > right, Word32PairBinopOp::Kind kind)
V< Word32Pair > LowerBitwiseAnd (V< Word32Pair > left, V< Word32Pair > right)
V< Word32Pair > LowerBitwiseOr (V< Word32Pair > left, V< Word32Pair > right)
V< Word32Pair > LowerBitwiseXor (V< Word32Pair > left, V< Word32Pair > right)
V< Word32Pair > LowerRotateRight (V< Word32Pair > left, V< Word32 > right)
V< Any > LowerCall (V< CallTarget > callee, OptionalV< FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor *descriptor, OpEffects effects, bool is_tail_call)
void InitializeIndexMaps ()
Private Attributes
const Signature< MachineRepresentation > * sig_
Zone * zone_ = __ graph_zone()
ZoneVector< int32_t > param_index_map_ {__ phase_zone()}
bool returns_i64_ = false
const OperationMatcher & matcher_ {__ matcher()}
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >
Definition at line 27 of file int64-lowering-reducer.h.
Member Typedef Documentation
Word32OrWord32Pair
template<class Next >
using v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Word32OrWord32Pair = OpIndex
Definition at line 34 of file int64-lowering-reducer.h.
Constructor & Destructor Documentation
Int64LoweringReducer()
template<class Next >
v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Int64LoweringReducer () [inline]
Definition at line 36 of file int64-lowering-reducer.h.
                         {
    wasm::CallOrigin origin = __ data() -> is_js_to_wasm()
                                  ? wasm::kCalledFromJS
                                  : wasm::kCalledFromWasm;
    // To compute the machine signature, it doesn't matter whether types
    // are canonicalized, just use whichever signature is present (functions
    // will have one and wrappers the other).
    if (__ data()->wasm_module_sig()) {
      sig_ =
          CreateMachineSignature(zone_, __ data()->wasm_module_sig(), origin);
    } else {
      sig_ = CreateMachineSignature(zone_, __ data()->wasm_canonical_sig(),
                                    origin);
    }
    InitializeIndexMaps();
  }
References __, v8::internal::compiler::CreateMachineSignature(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::InitializeIndexMaps(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::sig_, and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::zone_.
Member Function Documentation
AtomicRMW()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::AtomicRMW (OpIndex base, OpIndex index, OpIndex value, OptionalOpIndex expected, AtomicRMWOp::BinOp bin_op, RegisterRepresentation in_out_rep, MemoryRepresentation memory_rep, MemoryAccessKind kind, RegisterRepresentation base_rep) [inline]
Definition at line 405 of file int64-lowering-reducer.h.
                                                             {
    if (in_out_rep != RegisterRepresentation::Word64()) {
      return Next::ReduceAtomicRMW(base, index, value, expected, bin_op,
                                   in_out_rep, memory_rep, kind, base_rep);
    }
    auto [value_low, value_high] = Unpack(value);
    if (memory_rep == MemoryRepresentation::Int64() ||
        memory_rep == MemoryRepresentation::Uint64()) {
      if (base_rep == RegisterRepresentation::Tagged()) {
        DCHECK_EQ(__ output_graph().Get(base).outputs_rep()[0],
                  RegisterRepresentation::Tagged());
        base = __ BitcastTaggedToWordPtr(base);
      }
      if (bin_op == AtomicRMWOp::BinOp::kCompareExchange) {
        auto [expected_low, expected_high] = Unpack(expected.value());
        return __ AtomicWord32PairCompareExchange(
            base, index, value_low, value_high, expected_low, expected_high);
      } else {
        return __ AtomicWord32PairBinop(base, index, value_low, value_high,
                                        bin_op);
      }
    }
    OpIndex new_expected = OpIndex::Invalid();
    if (bin_op == AtomicRMWOp::BinOp::kCompareExchange) {
      auto [expected_low, expected_high] = Unpack(expected.value());
      new_expected = expected_low;
    }
    return __ Tuple(
        Next::ReduceAtomicRMW(base, index, value_low, new_expected, bin_op,
                              RegisterRepresentation::Word32(), memory_rep,
                              kind, base_rep),
        __ Word32Constant(0));
  }
References __, DCHECK_EQ, v8::internal::compiler::turboshaft::Get(), v8::internal::index, v8::internal::compiler::turboshaft::MemoryRepresentation::Int64(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::AtomicRMWOp::kCompareExchange, v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack(), v8::internal::value, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Call()
template<class Next >
V<Any> REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Call (V< CallTarget > callee, OptionalV< FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor * descriptor, OpEffects effects) [inline]
Definition at line 151 of file int64-lowering-reducer.h.
                                                                             {
    const bool is_tail_call = false;
    return LowerCall(callee, frame_state, arguments, descriptor, effects,
                     is_tail_call);
  }
References v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall().
Change()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Change (OpIndex input, ChangeOp::Kind kind, ChangeOp::Assumption assumption, RegisterRepresentation from, RegisterRepresentation to) [inline]
Definition at line 254 of file int64-lowering-reducer.h.
                                                    {
    auto word32 = RegisterRepresentation::Word32();
    auto word64 = RegisterRepresentation::Word64();
    auto float64 = RegisterRepresentation::Float64();
    using Kind = ChangeOp::Kind;
    if (from != word64 && to != word64) {
      return Next::ReduceChange(input, kind, assumption, from, to);
    }
    if (from == word32 && to == word64) {
      if (kind == Kind::kZeroExtend) {
        return __ Tuple(V<Word32>::Cast(input), __ Word32Constant(0));
      }
      if (kind == Kind::kSignExtend) {
        return LowerSignExtend(input);
      }
    }
    if (from == float64 && to == word64) {
      if (kind == Kind::kBitcast) {
        return __ Tuple(__ Float64ExtractLowWord32(input),
                        __ Float64ExtractHighWord32(input));
      }
    }
    if (from == word64 && to == float64) {
      if (kind == Kind::kBitcast) {
        auto input_w32p = V<Word32Pair>::Cast(input);
        return __ BitcastWord32PairToFloat64(
            __ template Projection<1>(input_w32p),
            __ template Projection<0>(input_w32p));
      }
    }
    if (from == word64 && to == word32 && kind == Kind::kTruncate) {
      auto input_w32p = V<Word32Pair>::Cast(input);
      return __ template Projection<0>(input_w32p);
    }
    std::stringstream str;
    str << "ChangeOp " << kind << " from " << from << " to " << to
        << "not supported by int64 lowering";
    FATAL("%s", str.str().c_str());
  }
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), FATAL, v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerSignExtend(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
CheckPairOrPairOp()
template<class Next >
bool v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::CheckPairOrPairOp (V< Word32Pair > input) [inline], [private]
Definition at line 613 of file int64-lowering-reducer.h.
                                              {
#ifdef DEBUG
    if (const TupleOp* tuple = matcher_.TryCast<TupleOp>(input)) {
      DCHECK_EQ(2, tuple->input_count);
      RegisterRepresentation word32 = RegisterRepresentation::Word32();
      ValidateOpInputRep(__ output_graph(), tuple->input(0), word32);
      ValidateOpInputRep(__ output_graph(), tuple->input(1), word32);
    } else if (const DidntThrowOp* didnt_throw =
                   matcher_.TryCast<DidntThrowOp>(input)) {
      // If it's a call, it must be a call that returns exactly one i64.
      // (Note that the CallDescriptor has already been lowered to [i32, i32].)
      const CallOp& call =
          __ Get(didnt_throw->throwing_operation()).template Cast<CallOp>();
      DCHECK_EQ(call.descriptor->descriptor->ReturnCount(), 2);
      DCHECK_EQ(call.descriptor->descriptor->GetReturnType(0),
                MachineType::Int32());
      DCHECK_EQ(call.descriptor->descriptor->GetReturnType(1),
                MachineType::Int32());
    } else {
      DCHECK(matcher_.Is<Word32PairBinopOp>(input));
    }
#endif
    return true;
  }
References __, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::TSCallDescriptor::descriptor, v8::internal::compiler::turboshaft::CallOp::descriptor, v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::CallDescriptor::GetReturnType(), v8::internal::MachineType::Int32(), v8::internal::compiler::turboshaft::OperationMatcher::Is(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::matcher_, v8::internal::compiler::CallDescriptor::ReturnCount(), v8::internal::compiler::turboshaft::OperationMatcher::TryCast(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack().
Comparison()
template<class Next >
V<Word32> REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Comparison (V< Any > left, V< Any > right, ComparisonOp::Kind kind, RegisterRepresentation rep) [inline]
Definition at line 109 of file int64-lowering-reducer.h.
                                                           {
    if (rep != WordRepresentation::Word64()) {
      return Next::ReduceComparison(left, right, kind, rep);
    }
    auto [left_low, left_high] = Unpack(V<Word32Pair>::Cast(left));
    auto [right_low, right_high] = Unpack(V<Word32Pair>::Cast(right));
    V<Word32> high_comparison;
    V<Word32> low_comparison;
    switch (kind) {
      case ComparisonOp::Kind::kEqual:
        // TODO(wasm): Use explicit comparisons and && here?
        return __ Word32Equal(
            __ Word32BitwiseOr(__ Word32BitwiseXor(left_low, right_low),
                               __ Word32BitwiseXor(left_high, right_high)),
            0);
      case ComparisonOp::Kind::kSignedLessThan:
        high_comparison = __ Int32LessThan(left_high, right_high);
        low_comparison = __ Uint32LessThan(left_low, right_low);
        break;
      case ComparisonOp::Kind::kSignedLessThanOrEqual:
        high_comparison = __ Int32LessThan(left_high, right_high);
        low_comparison = __ Uint32LessThanOrEqual(left_low, right_low);
        break;
      case ComparisonOp::Kind::kUnsignedLessThan:
        high_comparison = __ Uint32LessThan(left_high, right_high);
        low_comparison = __ Uint32LessThan(left_low, right_low);
        break;
      case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
        high_comparison = __ Uint32LessThan(left_high, right_high);
        low_comparison = __ Uint32LessThanOrEqual(left_low, right_low);
        break;
    }
    return __ Word32BitwiseOr(
        high_comparison,
        __ Word32BitwiseAnd(__ Word32Equal(left_high, right_high),
                            low_comparison));
  }
References __, v8::internal::compiler::turboshaft::ComparisonOp::kEqual, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kUnsignedLessThanOrEqual, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Constant()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Constant (ConstantOp::Kind kind, ConstantOp::Storage value) [inline]
Definition at line 168 of file int64-lowering-reducer.h.
                                                                         {
    if (kind == ConstantOp::Kind::kWord64) {
      uint32_t high = value.integral >> 32;
      uint32_t low = value.integral & std::numeric_limits<uint32_t>::max();
      return __ Tuple(__ Word32Constant(low), __ Word32Constant(high));
    }
    return Next::ReduceConstant(kind, value);
  }
References __, v8::internal::compiler::turboshaft::ConstantOp::kWord64, and v8::internal::value.
FixLoopPhi()
template<class Next >
void v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FixLoopPhi (const PhiOp & input_phi, OpIndex output_index, Block * output_graph_loop) [inline]
Definition at line 474 of file int64-lowering-reducer.h.
                                            {
    if (input_phi.rep == RegisterRepresentation::Word64()) {
      const TupleOp& tuple = __ Get(output_index).template Cast<TupleOp>();
      DCHECK_EQ(tuple.input_count, 2);
      OpIndex new_inputs[2] = {__ MapToNewGraph(input_phi.input(0)),
                               __ MapToNewGraph(input_phi.input(1))};
      for (size_t i = 0; i < 2; ++i) {
        OpIndex phi_index = tuple.input(i);
        if (!output_graph_loop->Contains(phi_index)) {
          continue;
        }
#ifdef DEBUG
        const PendingLoopPhiOp& pending_phi =
            __ Get(phi_index).template Cast<PendingLoopPhiOp>();
        DCHECK_EQ(pending_phi.rep, RegisterRepresentation::Word32());
        DCHECK_EQ(
            pending_phi.first(),
            __ Projection(new_inputs[0], i, RegisterRepresentation::Word32()));
#endif
        __ output_graph().template Replace<PhiOp>(
            phi_index,
            base::VectorOf({__ Projection(new_inputs[0], i,
                                          RegisterRepresentation::Word32()),
                            __ Projection(new_inputs[1], i,
                                          RegisterRepresentation::Word32())}),
            RegisterRepresentation::Word32());
      }
      return;
    }
    return Next::FixLoopPhi(input_phi, output_index, output_graph_loop);
  }
References __, v8::internal::compiler::turboshaft::Block::Contains(), DCHECK_EQ, v8::internal::compiler::turboshaft::PendingLoopPhiOp::first(), v8::internal::compiler::turboshaft::Get(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::OperationT< Derived >::input(), v8::internal::compiler::turboshaft::Operation::input_count, v8::internal::compiler::turboshaft::PhiOp::rep, v8::internal::compiler::turboshaft::PendingLoopPhiOp::rep, v8::base::VectorOf(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
FrameState()
template<class Next >
V<turboshaft::FrameState> REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState (base::Vector< const OpIndex > inputs, bool inlined, const FrameStateData * data) [inline]
Definition at line 547 of file int64-lowering-reducer.h.
                                  {
    bool has_int64_input = false;
    for (MachineType type : data->machine_types) {
      if (RegisterRepresentation::FromMachineType(type) ==
          RegisterRepresentation::Word64()) {
        has_int64_input = true;
        break;
      }
    }
    if (!has_int64_input) {
      return Next::ReduceFrameState(inputs, inlined, data);
    }
    FrameStateData::Builder builder;
    if (inlined) {
      builder.AddParentFrameState(V<turboshaft::FrameState>(inputs[0]));
    }
    const FrameStateFunctionInfo* function_info =
        data->frame_state_info.function_info();
    uint16_t lowered_parameter_count = function_info->parameter_count();
    int lowered_local_count = function_info->local_count();
    for (size_t i = inlined; i < inputs.size(); ++i) {
      // In case of inlining the parent FrameState is an additional input,
      // however, it doesn't have an entry in the machine_types vector, so that
      // index has to be adapted.
      size_t machine_type_index = i - inlined;
      if (RegisterRepresentation::FromMachineType(
              data->machine_types[machine_type_index]) ==
          RegisterRepresentation::Word64()) {
        auto [low, high] = Unpack(V<Word32Pair>::Cast(inputs[i]));
        builder.AddInput(MachineType::Int32(), low);
        builder.AddInput(MachineType::Int32(), high);
        // Note that the first input (after the optional parent FrameState) is
        // the JSClosure, so the first parameter is at index 1 (+1 in case of
        // nested inlining).
        if (i <= inlined + function_info->parameter_count()) {
          ++lowered_parameter_count;
        } else {
          ++lowered_local_count;
        }
      } else {
        // Just copy over the existing input.
        builder.AddInput(data->machine_types[machine_type_index], inputs[i]);
      }
    }
    Zone* zone = Asm().data()->compilation_zone();
    auto* function_info_lowered = zone->New<compiler::FrameStateFunctionInfo>(
        compiler::FrameStateType::kLiftoffFunction, lowered_parameter_count,
        function_info->max_arguments(), lowered_local_count,
        function_info->shared_info(), kNullMaybeHandle,
        function_info->wasm_liftoff_frame_size(),
        function_info->wasm_function_index());
    const FrameStateInfo& frame_state_info = data->frame_state_info;
    auto* frame_state_info_lowered = zone->New<compiler::FrameStateInfo>(
        frame_state_info.bailout_id(), frame_state_info.state_combine(),
        function_info_lowered);
    return Next::ReduceFrameState(
        builder.Inputs(), builder.inlined(),
        builder.AllocateFrameStateData(*frame_state_info_lowered, zone));
  }
References v8::internal::compiler::turboshaft::FrameStateData::Builder::AddInput(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AddParentFrameState(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AllocateFrameStateData(), v8::internal::compiler::turboshaft::RegisterRepresentation::FromMachineType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::FrameStateData::Builder::inlined(), v8::internal::compiler::turboshaft::FrameStateData::Builder::Inputs(), v8::internal::MachineType::Int32(), v8::internal::kNullMaybeHandle, v8::internal::compiler::FrameStateFunctionInfo::local_count(), v8::internal::compiler::FrameStateFunctionInfo::max_arguments(), v8::internal::Zone::New(), v8::internal::compiler::FrameStateFunctionInfo::parameter_count(), v8::internal::compiler::FrameStateFunctionInfo::shared_info(), v8::internal::tracing::type, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack(), v8::internal::compiler::FrameStateFunctionInfo::wasm_function_index(), v8::internal::compiler::FrameStateFunctionInfo::wasm_liftoff_frame_size(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
IncreaseOffset()
template<class Next >
std::pair<OptionalV<Word32>, int32_t> v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::IncreaseOffset (OptionalV< Word32 > index, int32_t offset, int32_t add_offset, bool tagged_base) [inline]
Definition at line 298 of file int64-lowering-reducer.h.
                                                                         {
    // Note that the offset will just wrap around. Still, we need to always
    // use an offset that is not std::numeric_limits<int32_t>::min() on tagged
    // loads.
    // TODO(dmercadier): Replace LoadOp::OffsetIsValid by taking care of this
    // special case in the LoadStoreSimplificationReducer instead.
    int32_t new_offset =
        static_cast<uint32_t>(offset) + static_cast<uint32_t>(add_offset);
    OptionalV<Word32> new_index = index;
    if (!LoadOp::OffsetIsValid(new_offset, tagged_base)) {
      // We cannot encode the new offset so we use the old offset
      // instead and use the Index to represent the extra offset.
      new_offset = offset;
      if (index.has_value()) {
        new_index = __ Word32Add(new_index.value(), add_offset);
      } else {
        new_index = __ Word32Constant(sizeof(int32_t));
      }
    }
    return {new_index, new_offset};
  }
References __, v8::internal::index, v8::internal::compiler::turboshaft::LoadOp::OffsetIsValid(), and v8::internal::compiler::turboshaft::OptionalV< T >::value().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Load(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Store().
InitializeIndexMaps()
template<class Next >
void v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::InitializeIndexMaps () [inline], [private]
Definition at line 902 of file int64-lowering-reducer.h.
                             {
    // Add one implicit parameter in front.
    param_index_map_.push_back(0);
    int32_t new_index = 0;
    for (size_t i = 0; i < sig_->parameter_count(); ++i) {
      param_index_map_.push_back(++new_index);
      if (sig_->GetParam(i) == MachineRepresentation::kWord64) {
        // i64 becomes [i32 low, i32 high], so the next parameter index is
        // shifted by one.
        ++new_index;
      }
    }
    returns_i64_ = std::any_of(sig_->returns().begin(), sig_->returns().end(),
                               [](const MachineRepresentation rep) {
                                 return rep == MachineRepresentation::kWord64;
                               });
  }
References v8::base::any_of(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kWord64, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::param_index_map_, v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::returns_i64_, and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::sig_.
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Int64LoweringReducer().
Load()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Load (OpIndex base, OptionalOpIndex index, LoadOp::Kind kind, MemoryRepresentation loaded_rep, RegisterRepresentation result_rep, int32_t offset, uint8_t element_scale) [inline]
Definition at line 323 of file int64-lowering-reducer.h.
                                              {
    if (kind.is_atomic) {
      if (loaded_rep == MemoryRepresentation::Int64() ||
          loaded_rep == MemoryRepresentation::Uint64()) {
        // TODO(jkummerow): Support non-zero scales in AtomicWord32PairOp, and
        // remove the corresponding bailout in MachineOptimizationReducer to
        // allow generating them.
        if (element_scale != 0 && index.has_value()) {
          DCHECK_EQ(element_scale, 3);
          index = __ Word32ShiftLeft(index.value(), element_scale);
        }
        // Manually subtract the pointer tag if present.
        offset -= kind.tagged_base;
        return __ AtomicWord32PairLoad(base, index, offset);
      }
      if (result_rep == RegisterRepresentation::Word64()) {
        return __ Tuple(
            __ Load(base, index, kind, loaded_rep,
                    RegisterRepresentation::Word32(), offset, element_scale),
            __ Word32Constant(0));
      }
    }
    if (loaded_rep == MemoryRepresentation::Int64() ||
        loaded_rep == MemoryRepresentation::Uint64()) {
      auto [high_index, high_offset] =
          IncreaseOffset(index, offset, sizeof(int32_t), kind.tagged_base);
      return __ Tuple(
          Next::ReduceLoad(base, index, kind, MemoryRepresentation::Int32(),
                           RegisterRepresentation::Word32(), offset,
                           element_scale),
          Next::ReduceLoad(
              base, high_index, kind, MemoryRepresentation::Int32(),
              RegisterRepresentation::Word32(), high_offset, element_scale));
    }
    return Next::ReduceLoad(base, index, kind, loaded_rep, result_rep, offset,
                            element_scale);
  }
References __, DCHECK_EQ, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::IncreaseOffset(), v8::internal::index, v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
LowerBitwiseAnd()
template<class Next >
V<Word32Pair> v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerBitwiseAnd (V< Word32Pair > left, V< Word32Pair > right) [inline], [private]
Definition at line 696 of file int64-lowering-reducer.h.
                                                                         {
    auto [left_low, left_high] = Unpack(left);
    auto [right_low, right_high] = Unpack(right);
    V<Word32> low_result = __ Word32BitwiseAnd(left_low, right_low);
    V<Word32> high_result = __ Word32BitwiseAnd(left_high, right_high);
    return __ Tuple(low_result, high_result);
  }
References __, and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordBinop().
LowerBitwiseOr()
template<class Next >
V<Word32Pair> v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerBitwiseOr (V< Word32Pair > left, V< Word32Pair > right) [inline], [private]
Definition at line 704 of file int64-lowering-reducer.h.
                                                                        {
    auto [left_low, left_high] = Unpack(left);
    auto [right_low, right_high] = Unpack(right);
    V<Word32> low_result = __ Word32BitwiseOr(left_low, right_low);
    V<Word32> high_result = __ Word32BitwiseOr(left_high, right_high);
    return __ Tuple(low_result, high_result);
  }
References __, and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordBinop().
LowerBitwiseXor()
template<class Next >
V<Word32Pair> v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerBitwiseXor (V< Word32Pair > left, V< Word32Pair > right) [inline], [private]
Definition at line 712 of file int64-lowering-reducer.h.
                                                                         {
    auto [left_low, left_high] = Unpack(left);
    auto [right_low, right_high] = Unpack(right);
    V<Word32> low_result = __ Word32BitwiseXor(left_low, right_low);
    V<Word32> high_result = __ Word32BitwiseXor(left_high, right_high);
    return __ Tuple(low_result, high_result);
  }
References __, and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordBinop().
LowerCall()
template<class Next >
V<Any> v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall (V< CallTarget > callee, OptionalV< FrameState > frame_state, base::Vector< const OpIndex > arguments, const TSCallDescriptor * descriptor, OpEffects effects, bool is_tail_call) [inline], [private]
Definition at line 792 of file int64-lowering-reducer.h.
                                      {
    // Iterate over the call descriptor to skip lowering if the signature does
    // not contain an i64.
    const CallDescriptor* call_descriptor = descriptor->descriptor;
    size_t param_count = call_descriptor->ParameterCount();
    size_t i64_params = 0;
    for (size_t i = 0; i < param_count; ++i) {
      i64_params += call_descriptor->GetParameterType(i).representation() ==
                    MachineRepresentation::kWord64;
    }
    size_t return_count = call_descriptor->ReturnCount();
    size_t i64_returns = 0;
    for (size_t i = 0; i < return_count; ++i) {
      i64_returns += call_descriptor->GetReturnType(i).representation() ==
                     MachineRepresentation::kWord64;
    }
    if (i64_params + i64_returns == 0) {
      // No lowering required.
      return is_tail_call ? Next::ReduceTailCall(callee, arguments, descriptor)
                          : Next::ReduceCall(callee, frame_state, arguments,
                                             descriptor, effects);
    }
    // Transform the BigIntToI64 call descriptor into BigIntToI32Pair (this is
    // the only use case currently, it may be extended in the future).
    // The correct target is already set during graph building.
    CallDescriptor* maybe_special_replacement =
        wasm::GetWasmEngine()->call_descriptors()->GetLoweredCallDescriptor(
            call_descriptor);
    if (maybe_special_replacement) call_descriptor = maybe_special_replacement;
    // Create descriptor with 2 i32s for every i64.
    const CallDescriptor* lowered_descriptor =
        GetI32WasmCallDescriptor(__ graph_zone(), call_descriptor);
    // Map the arguments by unpacking i64 arguments (which have already been
    // lowered to Tuple(i32, i32).)
    base::SmallVector<OpIndex, 16> lowered_args;
    lowered_args.reserve(param_count + i64_params);
    DCHECK_EQ(param_count, arguments.size());
    for (size_t i = 0; i < param_count; ++i) {
      if (call_descriptor->GetParameterType(i).representation() ==
          MachineRepresentation::kWord64) {
        auto [low, high] = Unpack(arguments[i]);
        lowered_args.push_back(low);
        lowered_args.push_back(high);
      } else {
        lowered_args.push_back(arguments[i]);
      }
    }
    auto lowered_ts_descriptor =
        TSCallDescriptor::Create(lowered_descriptor, descriptor->can_throw,
                                 LazyDeoptOnThrow::kNo, __ graph_zone());
    OpIndex call =
        is_tail_call
            ? Next::ReduceTailCall(callee, base::VectorOf(lowered_args),
                                   lowered_ts_descriptor)
            : Next::ReduceCall(callee, frame_state,
                               base::VectorOf(lowered_args),
                               lowered_ts_descriptor, effects);
    if (is_tail_call) {
      // Tail calls don't return anything to the calling function.
      return call;
    }
    if (i64_returns == 0 || return_count == 0) {
      return call;
    } else if (return_count == 1) {
      // There isn't any projection in the input graph for calls returning
      // exactly one value. Return a tuple of projections for the int64.
      DCHECK_EQ(i64_returns, 1);
      return call;
    }
    // Wrap the call node with a tuple of projections of the lowered call.
    // Example for a call returning [int64, int32]:
    // In: Call(...) -> [int64, int32]
    // Out: call = Call() -> [int32, int32, int32]
    // Tuple(
    // Tuple(Projection(call, 0), Projection(call, 1)),
    // Projection(call, 2))
    //
    // This way projections on the original call node will be automatically
    // "rewired" to the correct projection of the lowered call.
    auto word32 = RegisterRepresentation::Word32();
    base::SmallVector<V<Any>, 16> tuple_inputs;
    tuple_inputs.reserve(return_count);
    size_t projection_index = 0; // index of the lowered call results.
    for (size_t i = 0; i < return_count; ++i) {
      MachineRepresentation machine_rep =
          call_descriptor->GetReturnType(i).representation();
      if (machine_rep == MachineRepresentation::kWord64) {
        tuple_inputs.push_back(
            __ Tuple(__ Projection(call, projection_index, word32),
                     __ Projection(call, projection_index + 1, word32)));
        projection_index += 2;
      } else {
        tuple_inputs.push_back(__ Projection(
            call, projection_index++,
            RegisterRepresentation::FromMachineRepresentation(machine_rep)));
      }
    }
    DCHECK_EQ(projection_index, return_count + i64_returns);
    return __ Tuple(base::VectorOf(tuple_inputs));
  }
References __, v8::internal::wasm::WasmEngine::call_descriptors(), v8::internal::compiler::turboshaft::TSCallDescriptor::can_throw, v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), DCHECK_EQ, v8::internal::compiler::turboshaft::TSCallDescriptor::descriptor, v8::internal::compiler::turboshaft::RegisterRepresentation::FromMachineRepresentation(), v8::internal::compiler::WasmCallDescriptors::GetLoweredCallDescriptor(), v8::internal::compiler::CallDescriptor::GetParameterType(), v8::internal::compiler::CallDescriptor::GetReturnType(), v8::internal::wasm::GetWasmEngine(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::kNo, v8::internal::kWord64, v8::internal::compiler::CallDescriptor::ParameterCount(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::MachineType::representation(), v8::base::SmallVector< T, kSize, Allocator >::reserve(), v8::internal::compiler::CallDescriptor::ReturnCount(), v8::base::Vector< T >::size(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack(), v8::base::VectorOf(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Call(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::TailCall().
LowerClz()
template<class Next >
V<Word32Pair> v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerClz (V< Word32Pair > input) [inline], [private]
Definition at line 648 of file int64-lowering-reducer.h.
                                              {
    auto [low, high] = Unpack(input);
    ScopedVar<Word32> result(this);
    IF (__ Word32Equal(high, 0)) {
      result = __ Word32Add(32, __ Word32CountLeadingZeros(low));
    } ELSE {
      result = __ Word32CountLeadingZeros(high);
    }
    return __ Tuple<Word32, Word32>(result, __ Word32Constant(0));
  }
References __, v8::base::internal::result, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordUnary().
LowerCtz()
template<class Next >
V<Word32Pair> v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCtz (V< Word32Pair > input) [inline], [private]
Definition at line 660 of file int64-lowering-reducer.h.
                                              {
    DCHECK(SupportedOperations::word32_ctz());
    auto [low, high] = Unpack(input);
    ScopedVar<Word32> result(this);
    IF (__ Word32Equal(low, 0)) {
      result = __ Word32Add(32, __ Word32CountTrailingZeros(high));
    } ELSE {
      result = __ Word32CountTrailingZeros(low);
    }
    return __ Tuple<Word32, Word32>(result, __ Word32Constant(0));
  }
References __, v8::internal::DCHECK(), v8::base::internal::result, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack(), and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::Word32Equal().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordUnary().
LowerPairBinOp()
template<class Next >
V<Word32Pair> v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerPairBinOp (V< Word32Pair > left, V< Word32Pair > right, Word32PairBinopOp::Kind kind) [inline], [private]
Definition at line 681 of file int64-lowering-reducer.h.
                                                           {
    auto [left_low, left_high] = Unpack(left);
    auto [right_low, right_high] = Unpack(right);
    return __ Word32PairBinop(left_low, left_high, right_low, right_high, kind);
  }
References __, and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordBinop().
LowerPairShiftOp()
template<class Next >
V<Word32Pair> v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerPairShiftOp (V< Word32Pair > left, V< Word32 > right, Word32PairBinopOp::Kind kind) [inline], [private]
Definition at line 688 of file int64-lowering-reducer.h.
                                                             {
    auto [left_low, left_high] = Unpack(left);
    // Note: The rhs of a 64 bit shift is a 32 bit value in turboshaft.
    V<Word32> right_high = __ Word32Constant(0);
    return __ Word32PairBinop(left_low, left_high, right, right_high, kind);
  }
References __, and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Shift().
LowerPopCount()
template<class Next >
V<Word32Pair> v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerPopCount (V< Word32Pair > input) [inline], [private]
Definition at line 673 of file int64-lowering-reducer.h.
                                                   {
    DCHECK(SupportedOperations::word32_popcnt());
    auto [low, high] = Unpack(input);
    return __ Tuple(
        __ Word32Add(__ Word32PopCount(low), __ Word32PopCount(high)),
        __ Word32Constant(0));
  }
References __, v8::internal::DCHECK(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordUnary().
LowerRotateRight()
template<class Next >
V<Word32Pair> v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerRotateRight (V< Word32Pair > left, V< Word32 > right) [inline], [private]
Definition at line 720 of file int64-lowering-reducer.h.
                                                                      {
    // This reducer assumes that all rotates are mapped to rotate right.
    DCHECK(!SupportedOperations::word64_rol());
    auto [left_low, left_high] = Unpack(left);
    V<Word32> shift = right;
    uint32_t constant_shift = 0;
    if (matcher_.MatchIntegralWord32Constant(shift, &constant_shift)) {
      // Precondition: 0 <= shift < 64.
      uint32_t shift_value = constant_shift & 0x3F;
      if (shift_value == 0) {
        // No-op, return original tuple.
        return left;
      }
      if (shift_value == 32) {
        // Swap low and high of left.
        return __ Tuple(left_high, left_low);
      }
      V<Word32> low_input = left_high;
      V<Word32> high_input = left_low;
      if (shift_value < 32) {
        low_input = left_low;
        high_input = left_high;
      }
      uint32_t masked_shift_value = shift_value & 0x1F;
      V<Word32> masked_shift = __ Word32Constant(masked_shift_value);
      V<Word32> inv_shift = __ Word32Constant(32 - masked_shift_value);
      V<Word32> low_node = __ Word32BitwiseOr(
          __ Word32ShiftRightLogical(low_input, masked_shift),
          __ Word32ShiftLeft(high_input, inv_shift));
      V<Word32> high_node = __ Word32BitwiseOr(
          __ Word32ShiftRightLogical(high_input, masked_shift),
          __ Word32ShiftLeft(low_input, inv_shift));
      return __ Tuple(low_node, high_node);
    }
    V<Word32> safe_shift = shift;
    if (!SupportedOperations::word32_shift_is_safe()) {
      // safe_shift = shift % 32
      safe_shift = __ Word32BitwiseAnd(shift, 0x1F);
    }
    V<Word32> all_bits_set = __ Word32Constant(-1);
    V<Word32> inv_mask = __ Word32BitwiseXor(
        __ Word32ShiftRightLogical(all_bits_set, safe_shift), all_bits_set);
    V<Word32> bit_mask = __ Word32BitwiseXor(inv_mask, all_bits_set);
    V<Word32> less_than_32 = __ Int32LessThan(shift, 32);
    // The low word and the high word can be swapped either at the input or
    // at the output. We swap the inputs so that shift does not have to be
    // kept for so long in a register.
    ScopedVar<Word32> var_low(this, left_high);
    ScopedVar<Word32> var_high(this, left_low);
    IF (less_than_32) {
      var_low = left_low;
      var_high = left_high;
    }
    V<Word32> rotate_low = __ Word32RotateRight(var_low, safe_shift);
    V<Word32> rotate_high = __ Word32RotateRight(var_high, safe_shift);
    V<Word32> low_node =
        __ Word32BitwiseOr(__ Word32BitwiseAnd(rotate_low, bit_mask),
                           __ Word32BitwiseAnd(rotate_high, inv_mask));
    V<Word32> high_node =
        __ Word32BitwiseOr(__ Word32BitwiseAnd(rotate_high, bit_mask),
                           __ Word32BitwiseAnd(rotate_low, inv_mask));
    return __ Tuple(low_node, high_node);
  }
References __, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::matcher_, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralWord32Constant(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Shift().
LowerSignExtend()
template<class Next >
V<Word32Pair> v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerSignExtend (V< Word32 > input) [inline], [private]
Definition at line 643 of file int64-lowering-reducer.h.
                                                 {
    // We use SAR to preserve the sign in the high word.
    return __ Tuple(input, __ Word32ShiftRightArithmetic(input, 31));
  }
References __.
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Change(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordUnary().
Parameter()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Parameter (int32_t parameter_index, RegisterRepresentation rep, const char * debug_name = ``) [inline]
Definition at line 177 of file int64-lowering-reducer.h.
                                                         {
    int32_t param_count = static_cast<int32_t>(sig_->parameter_count());
    // Handle special indices (closure, context).
    if (parameter_index < 0) {
      return Next::ReduceParameter(parameter_index, rep, debug_name);
    }
    if (parameter_index > param_count) {
      DCHECK_NE(rep, RegisterRepresentation::Word64());
      int param_offset =
          std::count(sig_->parameters().begin(), sig_->parameters().end(),
                     MachineRepresentation::kWord64);
      return Next::ReduceParameter(parameter_index + param_offset, rep,
                                   debug_name);
    }
    int32_t new_index = param_index_map_[parameter_index];
    if (rep == RegisterRepresentation::Word64()) {
      rep = RegisterRepresentation::Word32();
      return __ Tuple(Next::ReduceParameter(new_index, rep),
                      Next::ReduceParameter(new_index + 1, rep));
    }
    return Next::ReduceParameter(new_index, rep, debug_name);
  }
References __, DCHECK_NE, v8::internal::kWord64, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::param_index_map_, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::sig_, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
PendingLoopPhi()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::PendingLoopPhi (OpIndex input, RegisterRepresentation rep) [inline]
Definition at line 464 of file int64-lowering-reducer.h.
                                                                            {
    if (rep == RegisterRepresentation::Word64()) {
      auto input_w32p = V<Word32Pair>::Cast(input);
      V<Word32> low = __ PendingLoopPhi(__ template Projection<0>(input_w32p));
      V<Word32> high = __ PendingLoopPhi(__ template Projection<1>(input_w32p));
      return __ Tuple(low, high);
    }
    return Next::ReducePendingLoopPhi(input, rep);
  }
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Phi()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Phi (base::Vector< const OpIndex > inputs, RegisterRepresentation rep) [inline]
Definition at line 445 of file int64-lowering-reducer.h.
                                                  {
    if (rep == RegisterRepresentation::Word64()) {
      base::SmallVector<OpIndex, 8> inputs_low;
      base::SmallVector<OpIndex, 8> inputs_high;
      auto word32 = RegisterRepresentation::Word32();
      inputs_low.reserve(inputs.size());
      inputs_high.reserve(inputs.size());
      for (OpIndex input : inputs) {
        auto input_w32p = V<Word32Pair>::Cast(input);
        inputs_low.push_back(__ template Projection<0>(input_w32p));
        inputs_high.push_back(__ template Projection<1>(input_w32p));
      }
      return __ Tuple(Next::ReducePhi(base::VectorOf(inputs_low), word32),
                      Next::ReducePhi(base::VectorOf(inputs_high), word32));
    }
    return Next::ReducePhi(inputs, rep);
  }
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::base::SmallVector< T, kSize, Allocator >::reserve(), v8::base::VectorOf(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Return()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Return (V< Word32 > pop_count, base::Vector< const OpIndex > return_values, bool spill_caller_frame_slots) [inline]
Definition at line 201 of file int64-lowering-reducer.h.
                                                        {
    if (!returns_i64_) {
      return Next::ReduceReturn(pop_count, return_values,
                                spill_caller_frame_slots);
    }
    base::SmallVector<OpIndex, 8> lowered_values;
    for (size_t i = 0; i < sig_->return_count(); ++i) {
      if (sig_->GetReturn(i) == MachineRepresentation::kWord64) {
        auto [low, high] = Unpack(return_values[i]);
        lowered_values.push_back(low);
        lowered_values.push_back(high);
      } else {
        lowered_values.push_back(return_values[i]);
      }
    }
    return Next::ReduceReturn(pop_count, base::VectorOf(lowered_values),
                              spill_caller_frame_slots);
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kWord64, v8::base::SmallVector< T, kSize, Allocator >::push_back(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::returns_i64_, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::sig_, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack(), and v8::base::VectorOf().
Shift()
template<class Next >
Word32OrWord32Pair REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Shift (Word32OrWord32Pair left, V< Word32 > right, ShiftOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 85 of file int64-lowering-reducer.h.
                                                                             {
    if (rep == WordRepresentation::Word64()) {
      V<Word32Pair> left_pair = V<Word32Pair>::Cast(left);
      switch (kind) {
        case ShiftOp::Kind::kShiftLeft:
          return LowerPairShiftOp(left_pair, right,
                                  Word32PairBinopOp::Kind::kShiftLeft);
        case ShiftOp::Kind::kShiftRightArithmetic:
          return LowerPairShiftOp(
              left_pair, right, Word32PairBinopOp::Kind::kShiftRightArithmetic);
        case ShiftOp::Kind::kShiftRightLogical:
          return LowerPairShiftOp(left_pair, right,
                                  Word32PairBinopOp::Kind::kShiftRightLogical);
        case ShiftOp::Kind::kRotateRight:
          return LowerRotateRight(left_pair, right);
        default:
          FATAL("Shiftop kind %d not supported by int64 lowering",
                static_cast<int>(kind));
      }
    }
    return Next::ReduceShift(left, right, kind, rep);
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), FATAL, v8::internal::compiler::turboshaft::Word32PairBinopOp::kShiftLeft, v8::internal::compiler::turboshaft::Word32PairBinopOp::kShiftRightArithmetic, v8::internal::compiler::turboshaft::Word32PairBinopOp::kShiftRightLogical, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerPairShiftOp(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerRotateRight(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Simd128ExtractLane()
template<class Next >
V<Any> REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Simd128ExtractLane (V< Simd128 > input, Simd128ExtractLaneOp::Kind kind, uint8_t lane) [inline]
Definition at line 520 of file int64-lowering-reducer.h.
                                                  {
    if (kind != Simd128ExtractLaneOp::Kind::kI64x2) {
      return Next::ReduceSimd128ExtractLane(input, kind, lane);
    }
    V<Word32> low = V<Word32>::Cast(__ Simd128ExtractLane(
        input, Simd128ExtractLaneOp::Kind::kI32x4, 2 * lane));
    V<Word32> high = V<Word32>::Cast(__ Simd128ExtractLane(
        input, Simd128ExtractLaneOp::Kind::kI32x4, 2 * lane + 1));
    return __ Tuple(low, high);
  }
References __, and v8::internal::compiler::turboshaft::V< T >::Cast().
Simd128ReplaceLane()
template<class Next >
V<Simd128> REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Simd128ReplaceLane (V< Simd128 > into, V< Any > new_lane, Simd128ReplaceLaneOp::Kind kind, uint8_t lane) [inline]
Definition at line 533 of file int64-lowering-reducer.h.
                                                      {
    // TODO(14108): Introduce I32-pair lane replacement for better codegen.
    if (kind != Simd128ReplaceLaneOp::Kind::kI64x2) {
      return Next::ReduceSimd128ReplaceLane(into, new_lane, kind, lane);
    }
    auto [low, high] = Unpack(V<Word32Pair>::Cast(new_lane));
    V<Simd128> low_replaced = __ Simd128ReplaceLane(
        into, low, Simd128ReplaceLaneOp::Kind::kI32x4, 2 * lane);
    return __ Simd128ReplaceLane(
        low_replaced, high, Simd128ReplaceLaneOp::Kind::kI32x4, 2 * lane + 1);
  }
References __, and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Simd128Splat().
Simd128Splat()
template<class Next >
V<Simd128> REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Simd128Splat (V< Any > input, Simd128SplatOp::Kind kind) [inline]
Definition at line 507 of file int64-lowering-reducer.h.
                                                                         {
    // TODO(14108): Introduce I32-pair splat for better codegen.
    if (kind != Simd128SplatOp::Kind::kI64x2) {
      return Next::ReduceSimd128Splat(input, kind);
    }
    auto [low, high] = Unpack(V<Word32Pair>::Cast(input));
    V<Simd128> base = __ Simd128Splat(low, Simd128SplatOp::Kind::kI32x4);
    V<Simd128> first_replaced = __ Simd128ReplaceLane(
        base, high, Simd128ReplaceLaneOp::Kind::kI32x4, 1);
    return __ Simd128ReplaceLane(first_replaced, high,
                                 Simd128ReplaceLaneOp::Kind::kI32x4, 3);
  }
References __, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Simd128ReplaceLane(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack().
Store()
template<class Next >
V<None> REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Store (OpIndex base, OptionalOpIndex index, OpIndex value, StoreOp::Kind kind, MemoryRepresentation stored_rep, WriteBarrierKind write_barrier, int32_t offset, uint8_t element_size_log2, bool maybe_initializing_or_transitioning, IndirectPointerTag maybe_indirect_pointer_tag) [inline]
Definition at line 364 of file int64-lowering-reducer.h.
                                                                       {
    if (stored_rep == MemoryRepresentation::Int64() ||
        stored_rep == MemoryRepresentation::Uint64()) {
      auto [low, high] = Unpack(value);
      if (kind.is_atomic) {
        // TODO(jkummerow): Support non-zero scales in AtomicWord32PairOp, and
        // remove the corresponding bailout in MachineOptimizationReducer to
        // allow generating them.
        if (element_size_log2 != 0 && index.has_value()) {
          DCHECK_EQ(element_size_log2, 3);
          index = __ Word32ShiftLeft(index.value(), element_size_log2);
        }
        // Manually subtract the pointer tag if present.
        offset -= kind.tagged_base;
        return __ AtomicWord32PairStore(base, index, low, high, offset);
      }
      // low store
      Next::ReduceStore(base, index, low, kind, MemoryRepresentation::Int32(),
                        write_barrier, offset, element_size_log2,
                        maybe_initializing_or_transitioning,
                        maybe_indirect_pointer_tag);
      // high store
      auto [high_index, high_offset] =
          IncreaseOffset(index, offset, sizeof(int32_t), kind.tagged_base);
      Next::ReduceStore(
          base, high_index, high, kind, MemoryRepresentation::Int32(),
          write_barrier, high_offset, element_size_log2,
          maybe_initializing_or_transitioning, maybe_indirect_pointer_tag);
      return V<None>::Invalid();
    }
    return Next::ReduceStore(base, index, value, kind, stored_rep,
                             write_barrier, offset, element_size_log2,
                             maybe_initializing_or_transitioning,
                             maybe_indirect_pointer_tag);
  }
References __, DCHECK_EQ, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::IncreaseOffset(), v8::internal::index, v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int64(), v8::internal::compiler::turboshaft::V< T >::Invalid(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack(), and v8::internal::value.
TailCall()
template<class Next >
OpIndex REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::TailCall (OpIndex callee, base::Vector< const OpIndex > arguments, const TSCallDescriptor * descriptor) [inline]
Definition at line 159 of file int64-lowering-reducer.h.
                                                               {
    const bool is_tail_call = true;
    OptionalV<FrameState> frame_state = OptionalV<FrameState>::Nullopt();
    return LowerCall(callee, frame_state, arguments, descriptor,
                     OpEffects().CanCallAnything(), is_tail_call);
  }
References v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), and v8::internal::compiler::turboshaft::OptionalV< T >::Nullopt().
Unpack()
template<class Next >
std::pair<V<Word32>, V<Word32> > v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack (V< Word32Pair > input) [inline], [private]
Definition at line 638 of file int64-lowering-reducer.h.
                                                            {
    DCHECK(CheckPairOrPairOp(input));
    return {__ template Projection<0>(input), __ template Projection<1>(input)};
  }
References __, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::CheckPairOrPairOp(), and v8::internal::DCHECK().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::AtomicRMW(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Comparison(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerBitwiseAnd(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerBitwiseOr(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerBitwiseXor(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerClz(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCtz(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerPairBinOp(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerPairShiftOp(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerPopCount(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerRotateRight(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Return(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Simd128ReplaceLane(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Simd128Splat(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Store(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordUnary().
WordBinop()
template<class Next >
Word32OrWord32Pair REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordBinop (Word32OrWord32Pair left, Word32OrWord32Pair right, WordBinopOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 54 of file int64-lowering-reducer.h.
                                                               {
    if (rep == WordRepresentation::Word64()) {
      V<Word32Pair> left_pair = V<Word32Pair>::Cast(left);
      V<Word32Pair> right_pair = V<Word32Pair>::Cast(right);
      switch (kind) {
        case WordBinopOp::Kind::kAdd:
          return LowerPairBinOp(left_pair, right_pair,
                                Word32PairBinopOp::Kind::kAdd);
        case WordBinopOp::Kind::kSub:
          return LowerPairBinOp(left_pair, right_pair,
                                Word32PairBinopOp::Kind::kSub);
        case WordBinopOp::Kind::kMul:
          return LowerPairBinOp(left_pair, right_pair,
                                Word32PairBinopOp::Kind::kMul);
        case WordBinopOp::Kind::kBitwiseAnd:
          return LowerBitwiseAnd(left_pair, right_pair);
        case WordBinopOp::Kind::kBitwiseOr:
          return LowerBitwiseOr(left_pair, right_pair);
        case WordBinopOp::Kind::kBitwiseXor:
          return LowerBitwiseXor(left_pair, right_pair);
        default:
          FATAL("WordBinopOp kind %d not supported by int64 lowering",
                static_cast<int>(kind));
      }
    }
    return Next::ReduceWordBinop(left, right, kind, rep);
  }
References v8::internal::compiler::turboshaft::V< T >::Cast(), FATAL, v8::internal::compiler::turboshaft::WordBinopOp::kAdd, v8::internal::compiler::turboshaft::Word32PairBinopOp::kAdd, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseAnd, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseOr, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseXor, v8::internal::compiler::turboshaft::WordBinopOp::kMul, v8::internal::compiler::turboshaft::Word32PairBinopOp::kMul, v8::internal::compiler::turboshaft::WordBinopOp::kSub, v8::internal::compiler::turboshaft::Word32PairBinopOp::kSub, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerBitwiseAnd(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerBitwiseOr(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerBitwiseXor(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerPairBinOp(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
WordUnary()
template<class Next >
Word32OrWord32Pair REDUCE() v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::WordUnary (Word32OrWord32Pair input, WordUnaryOp::Kind kind, WordRepresentation rep) [inline]
Definition at line 222 of file int64-lowering-reducer.h.
                                                               {
    if (rep == RegisterRepresentation::Word64()) {
      V<Word32Pair> input_pair = V<Word32Pair>::Cast(input);
      switch (kind) {
        case WordUnaryOp::Kind::kCountLeadingZeros:
          return LowerClz(input_pair);
        case WordUnaryOp::Kind::kCountTrailingZeros:
          return LowerCtz(input_pair);
        case WordUnaryOp::Kind::kPopCount:
          return LowerPopCount(input_pair);
        case WordUnaryOp::Kind::kSignExtend8:
          return LowerSignExtend(
              __ Word32SignExtend8(Unpack(input_pair).first));
        case WordUnaryOp::Kind::kSignExtend16:
          return LowerSignExtend(
              __ Word32SignExtend16(Unpack(input_pair).first));
        case WordUnaryOp::Kind::kReverseBytes: {
          auto [low, high] = Unpack(input_pair);
          V<Word32> reversed_low = __ Word32ReverseBytes(low);
          V<Word32> reversed_high = __ Word32ReverseBytes(high);
          return __ Tuple(reversed_high, reversed_low);
        }
        default:
          FATAL("WordUnaryOp kind %d not supported by int64 lowering",
                static_cast<int>(kind));
      }
    }
    return Next::ReduceWordUnary(input, kind, rep);
  }
References __, v8::internal::compiler::turboshaft::V< T >::Cast(), FATAL, v8::internal::compiler::turboshaft::WordUnaryOp::kCountLeadingZeros, v8::internal::compiler::turboshaft::WordUnaryOp::kCountTrailingZeros, v8::internal::compiler::turboshaft::WordUnaryOp::kPopCount, v8::internal::compiler::turboshaft::WordUnaryOp::kReverseBytes, v8::internal::compiler::turboshaft::WordUnaryOp::kSignExtend16, v8::internal::compiler::turboshaft::WordUnaryOp::kSignExtend8, v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerClz(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCtz(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerPopCount(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerSignExtend(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Unpack(), and v8::internal::compiler::turboshaft::RegisterRepresentation::Word64().
Member Data Documentation
matcher_
template<class Next >
const OperationMatcher& v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::matcher_ {__ matcher()} [private]
Definition at line 925 of file int64-lowering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::CheckPairOrPairOp(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerRotateRight().
param_index_map_
template<class Next >
ZoneVector<int32_t> v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::param_index_map_ {__ phase_zone()} [private]
Definition at line 923 of file int64-lowering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::InitializeIndexMaps(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Parameter().
returns_i64_
template<class Next >
bool v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::returns_i64_ = false [private]
Definition at line 924 of file int64-lowering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::InitializeIndexMaps(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Return().
sig_
template<class Next >
const Signature<MachineRepresentation>* v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::sig_ [private]
Definition at line 921 of file int64-lowering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::InitializeIndexMaps(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Int64LoweringReducer(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Parameter(), and v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Return().
zone_
template<class Next >
Zone* v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::zone_ = __ graph_zone() [private]
Definition at line 922 of file int64-lowering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::Int64LoweringReducer().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/int64-lowering-reducer.h