v8::internal::ReadOnlySpace Class Reference
#include <read-only-spaces.h>
Public Types
enum class SealMode { kDetachFromHeap
, kDetachFromHeapAndUnregisterMemory
, kDoNotDetachFromHeap
 }
Public Member Functions
V8_EXPORT_PRIVATE ReadOnlySpace (Heap *heap)
void DetachPagesAndAddToArtifacts (ReadOnlyArtifacts *artifacts)
V8_EXPORT_PRIVATE ~ReadOnlySpace () override
virtual V8_EXPORT_PRIVATE void TearDown (MemoryAllocator *memory_allocator)
bool IsDetached () const
bool writable () const
bool Contains (Address a)=delete
bool Contains (Tagged< Object > o)=delete
V8_EXPORT_PRIVATE AllocationResult AllocateRaw (int size_in_bytes, AllocationAlignment alignment)
V8_EXPORT_PRIVATE void ClearStringPaddingIfNeeded ()
V8_EXPORT_PRIVATE void Seal (SealMode ro_mode)
void RepairFreeSpacesAfterDeserialization ()
size_t Size () const override
V8_EXPORT_PRIVATE size_t CommittedPhysicalMemory () const override
const std::vector< ReadOnlyPageMetadata * > & pages () const
Address top () const
Address limit () const
size_t Capacity () const
size_t IndexOf (const MemoryChunkMetadata *chunk) const
bool ContainsSlow (Address addr) const
V8_EXPORT_PRIVATE void ShrinkPages ()
Address FirstPageAddress () const
void EnsurePage ()
Protected Member Functions
void SetPermissionsForPages (MemoryAllocator *memory_allocator, PageAllocator::Permission access)
Protected Attributes
bool is_marked_read_only_ = false
AllocationStats accounting_stats_
std::vector< ReadOnlyPageMetadata * > pages_
Address top_ = kNullAddress
Address limit_ = kNullAddress
Private Member Functions
AllocationResult AllocateRawUnaligned (int size_in_bytes)
AllocationResult AllocateRawAligned (int size_in_bytes, AllocationAlignment alignment)
Tagged< HeapObject > TryAllocateLinearlyAligned (int size_in_bytes, AllocationAlignment alignment)
size_t AllocateNextPage ()
size_t AllocateNextPageAt (Address pos)
void InitializePageForDeserialization (ReadOnlyPageMetadata *page, size_t area_size_in_bytes)
void FinalizeSpaceForDeserialization ()
void EnsureSpaceForAllocation (int size_in_bytes)
void FreeLinearAllocationArea ()
Private Attributes
size_t capacity_ = 0
Friends
class Heap
class ReadOnlyHeapImageDeserializer
Additional Inherited Members
Detailed Description
Definition at line 148 of file read-only-spaces.h.
Member Enumeration Documentation
SealMode
enum v8::internal::ReadOnlySpace::SealMode [strong]
Enumerator
kDetachFromHeap
kDetachFromHeapAndUnregisterMemory
kDoNotDetachFromHeap
Definition at line 173 of file read-only-spaces.h.
                      {
    kDetachFromHeap,
    kDetachFromHeapAndUnregisterMemory,
    kDoNotDetachFromHeap
  };
Constructor & Destructor Documentation
ReadOnlySpace()
v8::internal::ReadOnlySpace::ReadOnlySpace (Heap * heap) [explicit]
Definition at line 109 of file read-only-spaces.cc.
: BaseSpace(heap, RO_SPACE) {}
 ReadOnlySpace()
v8::internal::ReadOnlySpace::~ReadOnlySpace () [override], [default]
Member Function Documentation
AllocateNextPage()
size_t v8::internal::ReadOnlySpace::AllocateNextPage () [private]
Definition at line 526 of file read-only-spaces.cc.
                                       {
  ReadOnlyPageMetadata* page =
      heap_->memory_allocator()->AllocateReadOnlyPage(this);
  capacity_ += ReadOnlyAreaSize();
  AccountCommitted(page->size());
  pages_.push_back(page);
  return pages_.size() - 1;
}
References v8::internal::BaseSpace::AccountCommitted(), v8::internal::MemoryAllocator::AllocateReadOnlyPage(), capacity_, v8::internal::BaseSpace::heap_, v8::internal::Heap::memory_allocator(), pages_, v8::internal::anonymous_namespace{read-only-spaces.cc}::ReadOnlyAreaSize(), and v8::internal::MemoryChunkMetadata::size().
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::AllocatePage().
AllocateNextPageAt()
size_t v8::internal::ReadOnlySpace::AllocateNextPageAt (Address pos) [private]
Definition at line 535 of file read-only-spaces.cc.
                                                    {
  CHECK(IsAligned(pos, kRegularPageSize));
  ReadOnlyPageMetadata* page =
      heap_->memory_allocator()->AllocateReadOnlyPage(this, pos);
  if (!page) {
    heap_->FatalProcessOutOfMemory("ReadOnly allocation failure");
  }
  // If this fails we got a wrong page. This means something allocated a page in
  // the shared cage before us, stealing our required page (i.e.,
  // ReadOnlyHeap::SetUp was called too late).
  CHECK_EQ(pos, page->ChunkAddress());
  capacity_ += ReadOnlyAreaSize();
  AccountCommitted(page->size());
  pages_.push_back(page);
  return pages_.size() - 1;
}
References v8::internal::BaseSpace::AccountCommitted(), v8::internal::MemoryAllocator::AllocateReadOnlyPage(), capacity_, CHECK, CHECK_EQ, v8::internal::MemoryChunkMetadata::ChunkAddress(), v8::internal::Heap::FatalProcessOutOfMemory(), v8::internal::BaseSpace::heap_, IsAligned(), kRegularPageSize, v8::internal::Heap::memory_allocator(), pages_, v8::internal::anonymous_namespace{read-only-spaces.cc}::ReadOnlyAreaSize(), and v8::internal::MemoryChunkMetadata::size().
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::AllocatePage().
AllocateRaw()
AllocationResult v8::internal::ReadOnlySpace::AllocateRaw (int size_in_bytes, AllocationAlignment alignment)
Definition at line 460 of file read-only-spaces.cc.
                                                                           {
  return alignment != kTaggedAligned
             ? AllocateRawAligned(size_in_bytes, alignment)
             : AllocateRawUnaligned(size_in_bytes);
}
References AllocateRawAligned(), AllocateRawUnaligned(), and v8::internal::kTaggedAligned.
Referenced by v8::internal::HeapAllocator::AllocateRaw(), and v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::CopyToReadOnlyHeap().
AllocateRawAligned()
AllocationResult v8::internal::ReadOnlySpace::AllocateRawAligned (int size_in_bytes, AllocationAlignment alignment) [private]
Definition at line 417 of file read-only-spaces.cc.
                                                      {
  DCHECK(!IsDetached());
  size_in_bytes = ALIGN_TO_ALLOCATION_ALIGNMENT(size_in_bytes);
  int allocation_size = size_in_bytes;
  Tagged<HeapObject> object =
      TryAllocateLinearlyAligned(allocation_size, alignment);
  if (object.is_null()) {
    // We don't know exactly how much filler we need to align until space is
    // allocated, so assume the worst case.
    EnsureSpaceForAllocation(allocation_size +
                             Heap::GetMaximumFillToAlign(alignment));
    allocation_size = size_in_bytes;
    object = TryAllocateLinearlyAligned(size_in_bytes, alignment);
    CHECK(!object.is_null());
  }
  MSAN_ALLOCATED_UNINITIALIZED_MEMORY(object.address(), size_in_bytes);
  return AllocationResult::FromObject(object);
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, CHECK, v8::internal::DCHECK(), EnsureSpaceForAllocation(), v8::internal::AllocationResult::FromObject(), v8::internal::Heap::GetMaximumFillToAlign(), IsDetached(), MSAN_ALLOCATED_UNINITIALIZED_MEMORY, and TryAllocateLinearlyAligned().
Referenced by AllocateRaw().
AllocateRawUnaligned()
AllocationResult v8::internal::ReadOnlySpace::AllocateRawUnaligned (int size_in_bytes) [private]
Definition at line 439 of file read-only-spaces.cc.
                                                                      {
  DCHECK(!IsDetached());
  size_in_bytes = ALIGN_TO_ALLOCATION_ALIGNMENT(size_in_bytes);
  EnsureSpaceForAllocation(size_in_bytes);
  Address current_top = top_;
  Address new_top = current_top + size_in_bytes;
  DCHECK_LE(new_top, limit_);
  top_ = new_top;
  Tagged<HeapObject> object = HeapObject::FromAddress(current_top);
  DCHECK(!object.is_null());
  MSAN_ALLOCATED_UNINITIALIZED_MEMORY(object.address(), size_in_bytes);
  // Allocation always occurs in the last chunk for RO_SPACE.
  MemoryChunkMetadata* chunk = pages_.back();
  accounting_stats_.IncreaseAllocatedBytes(size_in_bytes, chunk);
  chunk->IncreaseAllocatedBytes(size_in_bytes);
  return AllocationResult::FromObject(object);
}
References accounting_stats_, ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::DCHECK(), DCHECK_LE, EnsureSpaceForAllocation(), v8::internal::HeapObject::FromAddress(), v8::internal::AllocationResult::FromObject(), v8::internal::MemoryChunkMetadata::IncreaseAllocatedBytes(), v8::internal::AllocationStats::IncreaseAllocatedBytes(), IsDetached(), limit_, MSAN_ALLOCATED_UNINITIALIZED_MEMORY, pages_, and top_.
Referenced by AllocateRaw().
Capacity()
size_t v8::internal::ReadOnlySpace::Capacity () const [inline]
Definition at line 194 of file read-only-spaces.h.
{ return capacity_; }
References capacity_.
Referenced by v8::internal::Heap::RecordStats().
ClearStringPaddingIfNeeded()
V8_EXPORT_PRIVATE void v8::internal::ReadOnlySpace::ClearStringPaddingIfNeeded ()
CommittedPhysicalMemory()
size_t v8::internal::ReadOnlySpace::CommittedPhysicalMemory () const [override], [virtual]
Implements v8::internal::BaseSpace.
Definition at line 320 of file read-only-spaces.cc.
                                                    {
  if (!base::OS::HasLazyCommits()) return CommittedMemory();
  MemoryChunkMetadata::UpdateHighWaterMark(top_);
  size_t size = 0;
  for (auto* chunk : pages_) {
    size += chunk->size();
  }
  return size;
}
References v8::internal::BaseSpace::CommittedMemory(), v8::base::OS::HasLazyCommits(), pages_, size(), top_, and v8::internal::MemoryChunkMetadata::UpdateHighWaterMark().
Referenced by v8::internal::ReadOnlyHeap::PopulateReadOnlySpaceStatistics().
Contains() [1/2]
bool v8::internal::ReadOnlySpace::Contains (Address a) [delete]
Contains() [2/2]
bool v8::internal::ReadOnlySpace::Contains (Tagged< Object > o) [delete]
ContainsSlow()
bool v8::internal::ReadOnlySpace::ContainsSlow (Address addr) const
Definition at line 211 of file read-only-spaces.cc.
                                                   {
  MemoryChunk* chunk = MemoryChunk::FromAddress(addr);
  for (MemoryChunkMetadata* metadata : pages_) {
    if (metadata->Chunk() == chunk) return true;
  }
  return false;
}
References v8::internal::MemoryChunk::FromAddress(), and pages_.
Referenced by v8::internal::Heap::InSpaceSlow().
DetachPagesAndAddToArtifacts()
void v8::internal::ReadOnlySpace::DetachPagesAndAddToArtifacts (ReadOnlyArtifacts * artifacts)
Definition at line 130 of file read-only-spaces.cc.
                                                                             {
  Heap* heap = ReadOnlySpace::heap();
  // ReadOnlySpace pages are directly shared between all heaps in
  // the isolate group and so must be unregistered from
  // their originating allocator.
  Seal(SealMode::kDetachFromHeapAndUnregisterMemory);
  artifacts->Initialize(heap->isolate(), std::move(pages_), accounting_stats_);
}
References accounting_stats_, v8::internal::BaseSpace::heap(), v8::internal::ReadOnlyArtifacts::Initialize(), kDetachFromHeapAndUnregisterMemory, pages_, and Seal().
Referenced by v8::internal::ReadOnlyHeap::InitFromIsolate().
EnsurePage()
void v8::internal::ReadOnlySpace::EnsurePage ()
Definition at line 347 of file read-only-spaces.cc.
                               {
  if (pages_.empty()) {
    EnsureSpaceForAllocation(1);
  }
  CHECK(!pages_.empty());
  // For all configurations where static roots are supported the read only roots
  // are currently allocated in the first page of the cage.
  CHECK_IMPLIES(V8_STATIC_ROOTS_BOOL,
                heap_->isolate()->cage_base() == pages_.back()->ChunkAddress());
}
References v8::internal::Isolate::cage_base(), CHECK, CHECK_IMPLIES, EnsureSpaceForAllocation(), v8::internal::BaseSpace::heap_, v8::internal::Heap::isolate(), pages_, and V8_STATIC_ROOTS_BOOL.
Referenced by v8::internal::ReadOnlyHeap::SetUp().
EnsureSpaceForAllocation()
void v8::internal::ReadOnlySpace::EnsureSpaceForAllocation (int size_in_bytes) [private]
Definition at line 367 of file read-only-spaces.cc.
                                                              {
  if (top_ + size_in_bytes <= limit_) {
    return;
  }
  DCHECK_GE(size_in_bytes, 0);
  FreeLinearAllocationArea();
  ReadOnlyPageMetadata* metadata =
      heap()->memory_allocator()->AllocateReadOnlyPage(this);
  CHECK_NOT_NULL(metadata);
  capacity_ += ReadOnlyAreaSize();
  accounting_stats_.IncreaseCapacity(metadata->area_size());
  AccountCommitted(metadata->size());
  pages_.push_back(metadata);
  heap()->CreateFillerObjectAt(metadata->area_start(),
                               static_cast<int>(metadata->area_size()));
  top_ = metadata->area_start();
  limit_ = metadata->area_end();
}
References v8::internal::BaseSpace::AccountCommitted(), accounting_stats_, v8::internal::MemoryAllocator::AllocateReadOnlyPage(), v8::internal::MemoryChunkMetadata::area_end(), v8::internal::MemoryChunkMetadata::area_size(), v8::internal::MemoryChunkMetadata::area_start(), capacity_, CHECK_NOT_NULL, v8::internal::Heap::CreateFillerObjectAt(), DCHECK_GE, FreeLinearAllocationArea(), v8::internal::BaseSpace::heap(), v8::internal::AllocationStats::IncreaseCapacity(), limit_, v8::internal::Heap::memory_allocator(), pages_, v8::internal::anonymous_namespace{read-only-spaces.cc}::ReadOnlyAreaSize(), v8::internal::MemoryChunkMetadata::size(), and top_.
Referenced by AllocateRawAligned(), AllocateRawUnaligned(), v8::internal::Heap::CreateReadOnlyObjects(), and EnsurePage().
FinalizeSpaceForDeserialization()
void v8::internal::ReadOnlySpace::FinalizeSpaceForDeserialization () [private]
Definition at line 559 of file read-only-spaces.cc.
                                                    {
  // The ReadOnlyRoots table is now initialized. Create fillers, shrink pages,
  // and update accounting stats.
  for (ReadOnlyPageMetadata* page : pages_) {
    Address top = page->ChunkAddress() + page->high_water_mark_;
    heap()->CreateFillerObjectAt(top, static_cast<int>(page->area_end() - top));
    page->ShrinkToHighWaterMark();
    accounting_stats_.IncreaseCapacity(page->area_size());
    accounting_stats_.IncreaseAllocatedBytes(page->allocated_bytes(), page);
  }
}
References accounting_stats_, v8::internal::Heap::CreateFillerObjectAt(), v8::internal::BaseSpace::heap(), v8::internal::AllocationStats::IncreaseAllocatedBytes(), v8::internal::AllocationStats::IncreaseCapacity(), pages_, and top().
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::DeserializeImpl().
FirstPageAddress()
Address v8::internal::ReadOnlySpace::FirstPageAddress () const [inline]
Definition at line 209 of file read-only-spaces.h.
{ return pages_.front()->ChunkAddress(); }
References pages_.
Referenced by v8::internal::Isolate::AddCrashKeysForIsolateAndHeapPointers().
FreeLinearAllocationArea()
void v8::internal::ReadOnlySpace::FreeLinearAllocationArea () [private]
Definition at line 331 of file read-only-spaces.cc.
                                             {
  // Mark the old linear allocation area with a free space map so it can be
  // skipped when scanning the heap.
  if (top_ == kNullAddress) {
    DCHECK_EQ(kNullAddress, limit_);
    return;
  }
  heap()->CreateFillerObjectAt(top_, static_cast<int>(limit_ - top_));
  MemoryChunkMetadata::UpdateHighWaterMark(top_);
  top_ = kNullAddress;
  limit_ = kNullAddress;
}
References v8::internal::Heap::CreateFillerObjectAt(), DCHECK_EQ, v8::internal::BaseSpace::heap(), v8::internal::kNullAddress, limit_, top_, and v8::internal::MemoryChunkMetadata::UpdateHighWaterMark().
Referenced by EnsureSpaceForAllocation(), and Seal().
IndexOf()
size_t v8::internal::ReadOnlySpace::IndexOf (const MemoryChunkMetadata * chunk) const
Definition at line 519 of file read-only-spaces.cc.
                                                                    {
  for (size_t i = 0; i < pages_.size(); i++) {
    if (chunk == pages_[i]) return i;
  }
  UNREACHABLE();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, pages_, and v8::internal::UNREACHABLE().
Referenced by v8::internal::anonymous_namespace{read-only-serializer.cc}::Encode(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::IndexOf(), and v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlySegmentForSerialization::ReadOnlySegmentForSerialization().
InitializePageForDeserialization()
void v8::internal::ReadOnlySpace::InitializePageForDeserialization (ReadOnlyPageMetadata * page, size_t area_size_in_bytes) [private]
Definition at line 552 of file read-only-spaces.cc.
                                                           {
  page->IncreaseAllocatedBytes(area_size_in_bytes);
  limit_ = top_ = page->area_start() + area_size_in_bytes;
  page->high_water_mark_ = page->Offset(top_);
}
References v8::internal::MemoryChunkMetadata::area_start(), v8::internal::MemoryChunkMetadata::high_water_mark_, v8::internal::MemoryChunkMetadata::IncreaseAllocatedBytes(), limit_, v8::internal::MemoryChunkMetadata::Offset(), and top_.
Referenced by v8::internal::ReadOnlyHeapImageDeserializer::AllocatePage().
IsDetached()
bool v8::internal::ReadOnlySpace::IsDetached () const [inline]
Definition at line 160 of file read-only-spaces.h.
{ return heap_ == nullptr; }
References v8::internal::BaseSpace::heap_.
Referenced by AllocateRawAligned(), and AllocateRawUnaligned().
limit()
Address v8::internal::ReadOnlySpace::limit () const [inline]
Definition at line 193 of file read-only-spaces.h.
{ return limit_; }
References limit_.
pages()
const std::vector<ReadOnlyPageMetadata*>& v8::internal::ReadOnlySpace::pages () const [inline]
Definition at line 191 of file read-only-spaces.h.
{ return pages_; }
References pages_.
Referenced by v8::internal::ReadOnlyHeapObjectIterator::Next(), v8::internal::ReadOnlyHeapImageDeserializer::PageAt(), v8::internal::Deserializer< IsolateT >::ReadReadOnlyHeapRef(), v8::internal::anonymous_namespace{read-only-serializer.cc}::ReadOnlyHeapImageSerializer::SerializeImpl(), and v8::internal::Serializer::SerializeReadOnlyObjectReference().
RepairFreeSpacesAfterDeserialization()
void v8::internal::ReadOnlySpace::RepairFreeSpacesAfterDeserialization ()
Definition at line 175 of file read-only-spaces.cc.
                                                         {
  MemoryChunkMetadata::UpdateHighWaterMark(top_);
  // Each page may have a small free space that is not tracked by a free list.
  // Those free spaces still contain null as their map pointer.
  // Overwrite them with new fillers.
  for (MemoryChunkMetadata* chunk : pages_) {
    Address start = chunk->HighWaterMark();
    Address end = chunk->area_end();
    // Put a filler object in the gap between the end of the allocated objects
    // and the end of the allocatable area.
    if (start < end) {
      heap()->CreateFillerObjectAt(start, static_cast<int>(end - start));
    }
  }
}
References v8::internal::Heap::CreateFillerObjectAt(), v8::internal::compiler::end(), v8::internal::BaseSpace::heap(), pages_, top_, and v8::internal::MemoryChunkMetadata::UpdateHighWaterMark().
Referenced by v8::internal::ReadOnlyDeserializer::DeserializeIntoIsolate().
Seal()
void v8::internal::ReadOnlySpace::Seal (SealMode ro_mode)
Definition at line 191 of file read-only-spaces.cc.
                                         {
  DCHECK(!is_marked_read_only_);
  FreeLinearAllocationArea();
  is_marked_read_only_ = true;
  auto* memory_allocator = heap()->memory_allocator();
  if (ro_mode != SealMode::kDoNotDetachFromHeap) {
    heap_ = nullptr;
    for (ReadOnlyPageMetadata* p : pages_) {
      if (ro_mode == SealMode::kDetachFromHeapAndUnregisterMemory) {
        memory_allocator->UnregisterReadOnlyPage(p);
      }
      p->MakeHeaderRelocatable();
    }
  }
  SetPermissionsForPages(memory_allocator, PageAllocator::kRead);
}
References v8::internal::DCHECK(), FreeLinearAllocationArea(), v8::internal::BaseSpace::heap(), v8::internal::BaseSpace::heap_, is_marked_read_only_, kDetachFromHeapAndUnregisterMemory, kDoNotDetachFromHeap, v8::PageAllocator::kRead, v8::internal::Heap::memory_allocator(), pages_, and SetPermissionsForPages().
Referenced by DetachPagesAndAddToArtifacts().
SetPermissionsForPages()
void v8::internal::ReadOnlySpace::SetPermissionsForPages (MemoryAllocator * memory_allocator, PageAllocator::Permission access) [protected]
Definition at line 159 of file read-only-spaces.cc.
                                                                           {
  for (MemoryChunkMetadata* chunk : pages_) {
    // Read only pages don't have valid reservation object so we get proper
    // page allocator manually.
    v8::PageAllocator* page_allocator =
        memory_allocator->page_allocator(RO_SPACE);
    CHECK(SetPermissions(page_allocator, chunk->ChunkAddress(), chunk->size(),
                         access));
  }
}
References CHECK, v8::internal::MemoryAllocator::page_allocator(), pages_, v8::internal::RO_SPACE, and v8::internal::SetPermissions().
Referenced by Seal().
ShrinkPages()
void v8::internal::ReadOnlySpace::ShrinkPages ()
Definition at line 498 of file read-only-spaces.cc.
                                {
  MemoryChunkMetadata::UpdateHighWaterMark(top_);
  heap()->CreateFillerObjectAt(top_, static_cast<int>(limit_ - top_));
  for (ReadOnlyPageMetadata* page : pages_) {
    DCHECK(page->Chunk()->IsFlagSet(MemoryChunk::NEVER_EVACUATE));
    size_t unused = page->ShrinkToHighWaterMark();
    capacity_ -= unused;
    accounting_stats_.DecreaseCapacity(static_cast<intptr_t>(unused));
    AccountUncommitted(unused);
  }
  limit_ = pages_.back()->area_end();
}
References accounting_stats_, v8::internal::BaseSpace::AccountUncommitted(), capacity_, v8::internal::Heap::CreateFillerObjectAt(), v8::internal::DCHECK(), v8::internal::AllocationStats::DecreaseCapacity(), v8::internal::BaseSpace::heap(), limit_, v8::internal::MemoryChunk::NEVER_EVACUATE, pages_, top_, and v8::internal::MemoryChunkMetadata::UpdateHighWaterMark().
Referenced by v8::internal::ReadOnlyHeap::InitFromIsolate().
Size()
size_t v8::internal::ReadOnlySpace::Size () const [inline], [override], [virtual]
Implements v8::internal::BaseSpace.
Definition at line 188 of file read-only-spaces.h.
{ return accounting_stats_.Size(); }
References accounting_stats_, and v8::internal::AllocationStats::Size().
Referenced by v8::internal::ReadOnlyHeap::PopulateReadOnlySpaceStatistics(), v8::internal::Heap::PrintShortHeapStatistics(), and v8::internal::Heap::RecordStats().
TearDown()
void v8::internal::ReadOnlySpace::TearDown (MemoryAllocator * memory_allocator) [virtual]
Reimplemented in v8::internal::SharedReadOnlySpace.
Definition at line 122 of file read-only-spaces.cc.
                                                              {
  for (ReadOnlyPageMetadata* chunk : pages_) {
    memory_allocator->FreeReadOnlyPage(chunk);
  }
  pages_.clear();
  accounting_stats_.Clear();
}
References accounting_stats_, v8::internal::AllocationStats::Clear(), v8::internal::MemoryAllocator::FreeReadOnlyPage(), and pages_.
Referenced by v8::internal::Heap::ReplaceReadOnlySpace().
top()
Address v8::internal::ReadOnlySpace::top () const [inline]
Definition at line 192 of file read-only-spaces.h.
{ return top_; }
References top_.
Referenced by v8::internal::Heap::CreateReadOnlyHeapObjects(), v8::internal::Heap::CreateReadOnlyObjects(), and FinalizeSpaceForDeserialization().
TryAllocateLinearlyAligned()
Tagged< HeapObject > v8::internal::ReadOnlySpace::TryAllocateLinearlyAligned (int size_in_bytes, AllocationAlignment alignment) [private]
Definition at line 393 of file read-only-spaces.cc.
                                                      {
  size_in_bytes = ALIGN_TO_ALLOCATION_ALIGNMENT(size_in_bytes);
  Address current_top = top_;
  int filler_size = Heap::GetFillToAlign(current_top, alignment);
  Address new_top = current_top + filler_size + size_in_bytes;
  if (new_top > limit_) return HeapObject();
  // Allocation always occurs in the last chunk for RO_SPACE.
  MemoryChunkMetadata* chunk = pages_.back();
  int allocated_size = filler_size + size_in_bytes;
  accounting_stats_.IncreaseAllocatedBytes(allocated_size, chunk);
  chunk->IncreaseAllocatedBytes(allocated_size);
  top_ = new_top;
  if (filler_size > 0) {
    return heap()->PrecedeWithFiller(HeapObject::FromAddress(current_top),
                                     filler_size);
  }
  return HeapObject::FromAddress(current_top);
}
References accounting_stats_, ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::HeapObject::FromAddress(), v8::internal::Heap::GetFillToAlign(), v8::internal::BaseSpace::heap(), v8::internal::MemoryChunkMetadata::IncreaseAllocatedBytes(), v8::internal::AllocationStats::IncreaseAllocatedBytes(), limit_, pages_, v8::internal::Heap::PrecedeWithFiller(), and top_.
Referenced by AllocateRawAligned().
writable()
bool v8::internal::ReadOnlySpace::writable () const [inline]
Definition at line 162 of file read-only-spaces.h.
{ return !is_marked_read_only_; }
References is_marked_read_only_.
Referenced by v8::internal::HeapAllocator::CanAllocateInReadOnlySpace(), v8::internal::SnapshotCreatorImpl::CreateBlob(), v8::internal::ETWJITInterface::EtwIsolateOperations::HeapReadOnlySpaceWritable(), v8::internal::Serializer::SerializeReadOnlyObjectReference(), and v8::internal::SnapshotCreatorImpl::~SnapshotCreatorImpl().
Friends And Related Function Documentation
Heap
friend class Heap [friend]
Definition at line 247 of file read-only-spaces.h.
ReadOnlyHeapImageDeserializer
friend class ReadOnlyHeapImageDeserializer [friend]
Definition at line 248 of file read-only-spaces.h.
Member Data Documentation
accounting_stats_
AllocationStats v8::internal::ReadOnlySpace::accounting_stats_ [protected]
Definition at line 221 of file read-only-spaces.h.
Referenced by AllocateRawUnaligned(), DetachPagesAndAddToArtifacts(), EnsureSpaceForAllocation(), FinalizeSpaceForDeserialization(), v8::internal::SharedReadOnlySpace::SharedReadOnlySpace(), ShrinkPages(), Size(), TearDown(), v8::internal::SharedReadOnlySpace::TearDown(), and TryAllocateLinearlyAligned().
capacity_
size_t v8::internal::ReadOnlySpace::capacity_ = 0 [private]
Definition at line 245 of file read-only-spaces.h.
Referenced by AllocateNextPage(), AllocateNextPageAt(), Capacity(), EnsureSpaceForAllocation(), and ShrinkPages().
is_marked_read_only_
bool v8::internal::ReadOnlySpace::is_marked_read_only_ = false [protected]
Definition at line 218 of file read-only-spaces.h.
Referenced by Seal(), v8::internal::SharedReadOnlySpace::SharedReadOnlySpace(), and writable().
limit_
Address v8::internal::ReadOnlySpace::limit_ = kNullAddress [protected]
Definition at line 226 of file read-only-spaces.h.
Referenced by AllocateRawUnaligned(), EnsureSpaceForAllocation(), FreeLinearAllocationArea(), InitializePageForDeserialization(), limit(), ShrinkPages(), and TryAllocateLinearlyAligned().
pages_
std::vector<ReadOnlyPageMetadata*> v8::internal::ReadOnlySpace::pages_ [protected]
Definition at line 223 of file read-only-spaces.h.
Referenced by AllocateNextPage(), AllocateNextPageAt(), AllocateRawUnaligned(), CommittedPhysicalMemory(), ContainsSlow(), DetachPagesAndAddToArtifacts(), EnsurePage(), EnsureSpaceForAllocation(), FinalizeSpaceForDeserialization(), FirstPageAddress(), IndexOf(), pages(), RepairFreeSpacesAfterDeserialization(), Seal(), SetPermissionsForPages(), v8::internal::SharedReadOnlySpace::SharedReadOnlySpace(), ShrinkPages(), TearDown(), v8::internal::SharedReadOnlySpace::TearDown(), and TryAllocateLinearlyAligned().
top_
Address v8::internal::ReadOnlySpace::top_ = kNullAddress [protected]
Definition at line 225 of file read-only-spaces.h.
Referenced by AllocateRawUnaligned(), CommittedPhysicalMemory(), EnsureSpaceForAllocation(), FreeLinearAllocationArea(), InitializePageForDeserialization(), RepairFreeSpacesAfterDeserialization(), ShrinkPages(), top(), and TryAllocateLinearlyAligned().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/read-only-spaces.h
/mnt/V8SourceCode/src/heap/read-only-spaces.cc