v8::base::Time Class Reference
#include <time.h>
Public Member Functions
constexpr Time ()
struct timespec ToTimespec () const
struct timeval ToTimeval () const
struct _FILETIME ToFiletime () const
double ToJsTime () const
Static Public Member Functions
static Time Now ()
static Time NowFromSystemTime ()
static Time UnixEpoch ()
static Time FromTimespec (struct timespec ts)
static Time FromTimeval (struct timeval tv)
static Time FromFiletime (struct _FILETIME ft)
static Time FromJsTime (double ms_since_epoch)
Private Member Functions
constexpr Time (int64_t us)
Friends
class time_internal::TimeBase< Time >
Additional Inherited Members
Detailed Description
Definition at line 334 of file time.h.
Constructor & Destructor Documentation
Time() [1/2]
constexpr v8::base::Time::Time () [inline], [constexpr]
Definition at line 337 of file time.h.
: TimeBase(0) {}
Referenced by FromJsTime().
Time() [2/2]
constexpr v8::base::Time::Time (int64_t us) [inline], [explicit], [constexpr], [private]
Definition at line 372 of file time.h.
: TimeBase(us) {}
Member Function Documentation
FromFiletime()
static Time v8::base::Time::FromFiletime (struct _FILETIME ft) [static]
FromJsTime()
Time v8::base::Time::FromJsTime (double ms_since_epoch) [static]
Definition at line 491 of file time.cc.
                                           {
  // The epoch is a valid time, so this constructor doesn't interpret
  // 0 as the null time.
  if (ms_since_epoch == std::numeric_limits<double>::max()) {
    return Max();
  }
  return Time(
      static_cast<int64_t>(ms_since_epoch * kMicrosecondsPerMillisecond));
}
References v8::base::TimeConstants::kMicrosecondsPerMillisecond, v8::base::time_internal::TimeBase< Time >::Max(), and Time().
FromTimespec()
static Time v8::base::Time::FromTimespec (struct timespec ts) [static]
FromTimeval()
static Time v8::base::Time::FromTimeval (struct timeval tv) [static]
Now()
static Time v8::base::Time::Now () [static]
Referenced by v8::base::OS::TimeCurrentMillis().
NowFromSystemTime()
static Time v8::base::Time::NowFromSystemTime () [static]
Referenced by v8::base::RandomNumberGenerator::RandomNumberGenerator().
ToFiletime()
struct _FILETIME v8::base::Time::ToFiletime () const
ToJsTime()
double v8::base::Time::ToJsTime () const
Definition at line 502 of file time.cc.
                            {
  if (IsNull()) {
    // Preserve 0 so the invalid result doesn't depend on the platform.
    return 0;
  }
  if (IsMax()) {
    // Preserve max without offset to prevent overflow.
    return std::numeric_limits<double>::max();
  }
  return static_cast<double>(us_) / kMicrosecondsPerMillisecond;
}
References v8::base::time_internal::TimeBase< Time >::IsMax(), v8::base::time_internal::TimeBase< Time >::IsNull(), v8::base::TimeConstants::kMicrosecondsPerMillisecond, and v8::base::time_internal::TimeBase< Time >::us_.
Referenced by v8::base::OS::TimeCurrentMillis().
ToTimespec()
struct timespec v8::base::Time::ToTimespec () const
ToTimeval()
struct timeval v8::base::Time::ToTimeval () const
UnixEpoch()
static Time v8::base::Time::UnixEpoch () [inline], [static]
Definition at line 351 of file time.h.
{ return Time(0); }
Friends And Related Function Documentation
time_internal::TimeBase< Time >
friend class time_internal::TimeBase< Time > [friend]
Definition at line 368 of file time.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/platform/time.h
/mnt/V8SourceCode/src/base/platform/time.cc