v8::internal::PerThreadAssertScope< kAllow, kTypes > Class Template Reference
#include <assert-scope.h>
Public Member Functions
V8_EXPORT_PRIVATE PerThreadAssertScope ()
V8_EXPORT_PRIVATE ~PerThreadAssertScope ()
PerThreadAssertScope (const PerThreadAssertScope &)=delete
PerThreadAssertScope & operator= (const PerThreadAssertScope &)=delete
void Release ()
Static Public Member Functions
static V8_EXPORT_PRIVATE bool IsAllowed ()
Private Attributes
PerThreadAsserts old_data_
Detailed Description
template<bool kAllow, PerThreadAssertType... kTypes>
class v8::internal::PerThreadAssertScope< kAllow, kTypes >
Definition at line 59 of file assert-scope.h.
Constructor & Destructor Documentation
PerThreadAssertScope() [1/2]
template<bool kAllow, PerThreadAssertType... kTypes>
v8::internal::PerThreadAssertScope< kAllow, kTypes >::PerThreadAssertScope
Definition at line 32 of file assert-scope.cc.
    : old_data_(current_per_thread_assert_data) {
  static_assert(((kTypes != ASSERT_TYPE_IS_VALID_MARKER) && ...),
                "PerThreadAssertScope types should not include the "
                "ASSERT_TYPE_IS_VALID_MARKER");
  DCHECK(old_data_.contains(ASSERT_TYPE_IS_VALID_MARKER));
  if (kAllow) {
    current_per_thread_assert_data = old_data_ | PerThreadAsserts({kTypes...});
  } else {
    current_per_thread_assert_data = old_data_ - PerThreadAsserts({kTypes...});
  }
}
References v8::internal::ASSERT_TYPE_IS_VALID_MARKER, v8::base::EnumSet< E, T >::contains(), v8::internal::anonymous_namespace{assert-scope.cc}::current_per_thread_assert_data(), v8::internal::DCHECK(), and v8::internal::PerThreadAssertScope< kAllow, kTypes >::old_data_.
 PerThreadAssertScope()
template<bool kAllow, PerThreadAssertType... kTypes>
v8::internal::PerThreadAssertScope< kAllow, kTypes >::~PerThreadAssertScope
Definition at line 46 of file assert-scope.cc.
                                                               {
  Release();
}
PerThreadAssertScope() [2/2]
template<bool kAllow, PerThreadAssertType... kTypes>
v8::internal::PerThreadAssertScope< kAllow, kTypes >::PerThreadAssertScope (const PerThreadAssertScope< kAllow, kTypes > &) [delete]
Member Function Documentation
IsAllowed()
template<bool kAllow, PerThreadAssertType... kTypes>
bool v8::internal::PerThreadAssertScope< kAllow, kTypes >::IsAllowed [static]
Definition at line 59 of file assert-scope.cc.
                                                        {
  return current_per_thread_assert_data.contains_all({kTypes...});
}
References v8::base::EnumSet< E, T >::contains_all(), and v8::internal::anonymous_namespace{assert-scope.cc}::current_per_thread_assert_data().
Referenced by v8::internal::HeapAllocator::AllocateRaw().
operator=()
template<bool kAllow, PerThreadAssertType... kTypes>
PerThreadAssertScope& v8::internal::PerThreadAssertScope< kAllow, kTypes >::operator= (const PerThreadAssertScope< kAllow, kTypes > &) [delete]
Release()
template<bool kAllow, PerThreadAssertType... kTypes>
void v8::internal::PerThreadAssertScope< kAllow, kTypes >::Release
Definition at line 51 of file assert-scope.cc.
                                                      {
  if (old_data_ == kClearedValue) return;
  current_per_thread_assert_data = old_data_;
  old_data_ = kClearedValue;
}
References v8::internal::anonymous_namespace{assert-scope.cc}::current_per_thread_assert_data(), and v8::internal::anonymous_namespace{assert-scope.cc}::kClearedValue.
Member Data Documentation
old_data_
template<bool kAllow, PerThreadAssertType... kTypes>
PerThreadAsserts v8::internal::PerThreadAssertScope< kAllow, kTypes >::old_data_ [private]
Definition at line 73 of file assert-scope.h.
Referenced by v8::internal::PerThreadAssertScope< kAllow, kTypes >::PerThreadAssertScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/assert-scope.h
/mnt/V8SourceCode/src/common/assert-scope.cc