v8::internal::ExternalTwoByteString Class Reference
#include <string.h>
Public Types
using Char = uint16_t
using Resource = v8::String::ExternalStringResource
Public Member Functions
const Resource * resource () const
void SetResource (Isolate *isolate, const Resource *buffer)
void set_resource (Isolate *isolate, const Resource *buffer)
void update_data_cache (Isolate *isolate)
const uint16_t * GetChars () const
uint16_t Get (uint32_t index, const SharedStringAccessGuardIfNeeded &access_guard) const
const uint16_t * ExternalTwoByteStringGetData (uint32_t start)
Static Public Attributes
static const bool kHasOneByteEncoding = false
Private Member Functions
Resource * mutable_resource ()
Additional Inherited Members
Detailed Description
Definition at line 1271 of file string.h.
Member Typedef Documentation
Char
using v8::internal::ExternalTwoByteString::Char = uint16_t
Definition at line 1274 of file string.h.
Resource
using v8::internal::ExternalTwoByteString::Resource = v8::String::ExternalStringResource
Definition at line 1276 of file string.h.
Member Function Documentation
ExternalTwoByteStringGetData()
const uint16_t * v8::internal::ExternalTwoByteString::ExternalTwoByteStringGetData (uint32_t start) [inline]
Definition at line 1613 of file string-inl.h.
                    {
  return GetChars() + start;
}
Get()
uint16_t v8::internal::ExternalTwoByteString::Get (uint32_t index, const SharedStringAccessGuardIfNeeded & access_guard) const [inline]
Definition at line 1606 of file string-inl.h.
                                                                               {
  USE(access_guard);
  DCHECK(index >= 0 && index < length());
  return GetChars()[index];
}
References v8::internal::DCHECK(), v8::internal::index, v8::internal::String::length(), and USE.
GetChars()
const uint16_t * v8::internal::ExternalTwoByteString::GetChars () const [inline]
Definition at line 1583 of file string-inl.h.
                                                      {
  DisallowGarbageCollection no_gc;
  auto res = resource();
  if (is_uncached()) {
    if (res->IsCacheable()) {
      // TODO(solanes): Teach TurboFan/CSA to not bailout to the runtime to
      // avoid this call.
      return res->cached_data();
    }
#if DEBUG
    // Check that this method is called only from the main thread if we have an
    // uncached string with an uncacheable resource.
    {
      Isolate* isolate;
      DCHECK_IMPLIES(GetIsolateFromHeapObject(this, &isolate),
                     ThreadId::Current() == isolate->thread_id());
    }
#endif
  }
  return res->data();
}
References v8::internal::ThreadId::Current(), DCHECK_IMPLIES, v8::internal::GetIsolateFromHeapObject(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Isolate::thread_id().
mutable_resource()
ExternalTwoByteString::Resource * v8::internal::ExternalTwoByteString::mutable_resource () [inline], [private]
Definition at line 1554 of file string-inl.h.
                                                                       {
  return reinterpret_cast<Resource*>(resource_as_address());
}
resource()
const ExternalTwoByteString::Resource * v8::internal::ExternalTwoByteString::resource () const [inline]
Definition at line 1550 of file string-inl.h.
                                                                           {
  return reinterpret_cast<const Resource*>(resource_as_address());
}
set_resource()
void v8::internal::ExternalTwoByteString::set_resource (Isolate * isolate, const Resource * buffer) [inline]
Definition at line 1577 of file string-inl.h.
                                                                     {
  resource_.store(isolate, reinterpret_cast<Address>(resource));
  if (resource != nullptr) update_data_cache(isolate);
}
SetResource()
void v8::internal::ExternalTwoByteString::SetResource (Isolate * isolate, const Resource * buffer) [inline]
Definition at line 1568 of file string-inl.h.
                                                                     {
  set_resource(isolate, resource);
  size_t new_payload = resource == nullptr ? 0 : resource->length() * 2;
  if (new_payload > 0) {
    isolate->heap()->UpdateExternalString(this, 0, new_payload);
  }
}
References v8::internal::Isolate::heap(), v8::String::ExternalStringResource::length(), and v8::internal::Heap::UpdateExternalString().
update_data_cache()
void v8::internal::ExternalTwoByteString::update_data_cache (Isolate * isolate) [inline]
Definition at line 1558 of file string-inl.h.
                                                              {
  DisallowGarbageCollection no_gc;
  if (is_uncached()) {
    if (resource()->IsCacheable()) mutable_resource()->UpdateDataCache();
  } else {
    resource_data_.store(isolate,
                         reinterpret_cast<Address>(resource()->data()));
  }
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Member Data Documentation
kHasOneByteEncoding
const bool v8::internal::ExternalTwoByteString::kHasOneByteEncoding = false [static]
Definition at line 1273 of file string.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string.h
/mnt/V8SourceCode/src/objects/string-inl.h