v8::internal::compiler::BitsetType Class Reference
#include <turbofan-types.h>
Classes
struct Boundary
Public Types
enum : bitset { kUnusedEOL = 0
 }
using bitset = uint64_t
Public Member Functions
template<typename MapRefLike >
Type::bitset Lub (MapRefLike map, JSHeapBroker *broker)
Static Public Member Functions
static bitset SignedSmall ()
static bitset UnsignedSmall ()
static bool IsNone (bitset bits)
static bool Is (bitset bits1, bitset bits2)
static double Min (bitset)
static double Max (bitset)
static bitset Glb (double min, double max)
static bitset Lub (HeapObjectType const &type, JSHeapBroker *broker)
static bitset Lub (MapRef map, JSHeapBroker *broker)
static bitset Lub (double value)
static bitset Lub (double min, double max)
static bitset ExpandInternals (bitset bits)
static const char * Name (bitset)
static void Print (std::ostream &os, bitset)
static bitset NumberBits (bitset bits)
Static Private Member Functions
static const Boundary * Boundaries ()
static size_t BoundariesSize ()
template<typename MapRefLike >
static bitset Lub (MapRefLike map, JSHeapBroker *broker)
Static Private Attributes
static const Boundary BoundariesArray []
Detailed Description
Definition at line 263 of file turbofan-types.h.
Member Typedef Documentation
bitset
using v8::internal::compiler::BitsetType::bitset = uint64_t
Definition at line 265 of file turbofan-types.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : bitset
Enumerator
kUnusedEOL
Definition at line 267 of file turbofan-types.h.
       : bitset {
#define DECLARE_TYPE(type, value) k##type = (value),
    BITSET_TYPE_LIST(DECLARE_TYPE)
#undef DECLARE_TYPE
        kUnusedEOL = 0
  };
Member Function Documentation
Boundaries()
const BitsetType::Boundary * v8::internal::compiler::BitsetType::Boundaries () [inline], [static], [private]
Definition at line 453 of file turbofan-types.cc.
{ return BoundariesArray; }
BoundariesSize()
size_t v8::internal::compiler::BitsetType::BoundariesSize () [inline], [static], [private]
Definition at line 455 of file turbofan-types.cc.
                                  {
  // Windows doesn't like arraysize here.
  // return arraysize(BoundariesArray);
  return 7;
}
ExpandInternals()
Type::bitset v8::internal::compiler::BitsetType::ExpandInternals (Type::bitset bits) [static]
Definition at line 461 of file turbofan-types.cc.
                                                      {
  DCHECK_IMPLIES(bits & kOtherString, (bits & kString) == kString);
  DisallowGarbageCollection no_gc;
  if (!(bits & kPlainNumber)) return bits; // Shortcut.
  const Boundary* boundaries = Boundaries();
  for (size_t i = 0; i < BoundariesSize(); ++i) {
    DCHECK(BitsetType::Is(boundaries[i].internal, boundaries[i].external));
    if (bits & boundaries[i].internal) bits |= boundaries[i].external;
  }
  return bits;
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::compiler::BitsetType::Boundary::external, v8::internal::anonymous_namespace{json-stringifier.cc}::i, Is(), v8::internal::kString, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::compiler::Type::For().
Glb()
Type::bitset v8::internal::compiler::BitsetType::Glb (double min, double max) [static]
Definition at line 489 of file turbofan-types.cc.
                                                 {
  DisallowGarbageCollection no_gc;
  bitset glb = kNone;
  const Boundary* mins = Boundaries();
  // If the range does not touch 0, the bound is empty.
  if (max < -1 || min > 0) return glb;
  for (size_t i = 1; i + 1 < BoundariesSize(); ++i) {
    if (min <= mins[i].min) {
      if (max + 1 < mins[i + 1].min) break;
      glb |= mins[i].external;
    }
  }
  // OtherNumber also contains float numbers, so it can never be
  // in the greatest lower bound.
  return glb & ~(kOtherNumber);
}
References v8::internal::compiler::BitsetType::Boundary::external, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kNone, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Is()
static bool v8::internal::compiler::BitsetType::Is (bitset bits1, bitset bits2) [inline], [static]
Definition at line 279 of file turbofan-types.h.
                                             {
    return (bits1 | bits2) == bits2;
  }
Referenced by ExpandInternals(), and Max().
IsNone()
static bool v8::internal::compiler::BitsetType::IsNone (bitset bits) [inline], [static]
Definition at line 277 of file turbofan-types.h.
{ return bits == kNone; }
References v8::internal::kNone.
Lub() [1/6]
Type::bitset v8::internal::compiler::BitsetType::Lub (double min, double max) [static]
Definition at line 473 of file turbofan-types.cc.
                                                 {
  DisallowGarbageCollection no_gc;
  bitset lub = kNone;
  const Boundary* mins = Boundaries();
  for (size_t i = 1; i < BoundariesSize(); ++i) {
    if (min < mins[i].min) {
      lub |= mins[i - 1].internal;
      if (max < mins[i].min) return lub;
    }
  }
  return lub | mins[BoundariesSize() - 1].internal;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::BitsetType::Boundary::internal, v8::internal::kNone, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Lub() [2/6]
Type::bitset v8::internal::compiler::BitsetType::Lub (double value) [static]
Definition at line 435 of file turbofan-types.cc.
                                       {
  DisallowGarbageCollection no_gc;
  if (IsMinusZero(value)) return kMinusZero;
  if (std::isnan(value)) return kNaN;
  if (IsUint32Double(value) || IsInt32Double(value)) return Lub(value, value);
  return kOtherNumber;
}
References v8::internal::IsInt32Double(), v8::internal::IsMinusZero(), v8::internal::IsUint32Double(), v8::internal::compiler::turboshaft::kMinusZero, v8::internal::compiler::turboshaft::kNaN, v8::internal::compiler::RangeType::Lub(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
Lub() [3/6]
static bitset v8::internal::compiler::BitsetType::Lub (HeapObjectType const & type, JSHeapBroker * broker) [inline], [static]
Definition at line 287 of file turbofan-types.h.
                                                                      {
    return Lub<HeapObjectType>(type, broker);
  }
References broker(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::Type::For(), and v8::internal::compiler::RangeType::New().
Lub() [4/6]
template Type::bitset v8::internal::compiler::BitsetType::Lub< MapRef > (MapRef map, JSHeapBroker * broker) [inline], [static]
Definition at line 290 of file turbofan-types.h.
                                                      {
    return Lub<MapRef>(map, broker);
  }
References broker().
Lub() [5/6]
template<typename MapRefLike >
Type::bitset v8::internal::compiler::BitsetType::Lub (MapRefLike map, JSHeapBroker * broker)
Definition at line 148 of file turbofan-types.cc.
                                                               {
  switch (map.instance_type()) {
    case CONS_TWO_BYTE_STRING_TYPE:
    case CONS_ONE_BYTE_STRING_TYPE:
    case THIN_TWO_BYTE_STRING_TYPE:
    case THIN_ONE_BYTE_STRING_TYPE:
    case SLICED_TWO_BYTE_STRING_TYPE:
    case SLICED_ONE_BYTE_STRING_TYPE:
    case EXTERNAL_TWO_BYTE_STRING_TYPE:
    case EXTERNAL_ONE_BYTE_STRING_TYPE:
    case UNCACHED_EXTERNAL_TWO_BYTE_STRING_TYPE:
    case UNCACHED_EXTERNAL_ONE_BYTE_STRING_TYPE:
    case SEQ_TWO_BYTE_STRING_TYPE:
    case SEQ_ONE_BYTE_STRING_TYPE:
    case SHARED_SEQ_TWO_BYTE_STRING_TYPE:
    case SHARED_SEQ_ONE_BYTE_STRING_TYPE:
    case SHARED_EXTERNAL_TWO_BYTE_STRING_TYPE:
    case SHARED_EXTERNAL_ONE_BYTE_STRING_TYPE:
    case SHARED_UNCACHED_EXTERNAL_TWO_BYTE_STRING_TYPE:
    case SHARED_UNCACHED_EXTERNAL_ONE_BYTE_STRING_TYPE:
      return kString;
    case EXTERNAL_INTERNALIZED_TWO_BYTE_STRING_TYPE:
    case EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE:
    case UNCACHED_EXTERNAL_INTERNALIZED_TWO_BYTE_STRING_TYPE:
    case UNCACHED_EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE:
    case INTERNALIZED_TWO_BYTE_STRING_TYPE:
    case INTERNALIZED_ONE_BYTE_STRING_TYPE:
      return kInternalizedString;
    case SYMBOL_TYPE:
      return kSymbol;
    case BIGINT_TYPE:
      return kBigInt;
    case ODDBALL_TYPE:
      switch (map.oddball_type(broker)) {
        case OddballType::kNone:
          break;
        case OddballType::kBoolean:
          return kBoolean;
        case OddballType::kNull:
          return kNull;
        case OddballType::kUndefined:
          return kUndefined;
      }
      UNREACHABLE();
    case HOLE_TYPE:
      // Holes have a single map and we should have distinguished them earlier
      // by pointer comparison on the value.
      UNREACHABLE();
    case HEAP_NUMBER_TYPE:
      return kNumber;
    case CPP_HEAP_EXTERNAL_OBJECT_TYPE:
    case JS_ARRAY_ITERATOR_PROTOTYPE_TYPE:
    case JS_ITERATOR_PROTOTYPE_TYPE:
    case JS_MAP_ITERATOR_PROTOTYPE_TYPE:
    case JS_OBJECT_PROTOTYPE_TYPE:
    case JS_OBJECT_TYPE:
    case JS_PROMISE_PROTOTYPE_TYPE:
    case JS_REG_EXP_PROTOTYPE_TYPE:
    case JS_SET_ITERATOR_PROTOTYPE_TYPE:
    case JS_SET_PROTOTYPE_TYPE:
    case JS_STRING_ITERATOR_PROTOTYPE_TYPE:
    case JS_ARGUMENTS_OBJECT_TYPE:
    case JS_ERROR_TYPE:
    case JS_EXTERNAL_OBJECT_TYPE:
    case JS_GLOBAL_OBJECT_TYPE:
    case JS_GLOBAL_PROXY_TYPE:
    case JS_API_OBJECT_TYPE:
    case JS_SPECIAL_API_OBJECT_TYPE:
    case JS_TYPED_ARRAY_PROTOTYPE_TYPE:
      if (map.is_undetectable()) {
        // Currently we assume that every undetectable receiver is also
        // callable, which is what we need to support document.all. We
        // could add another Type bit to support other use cases in the
        // future if necessary.
        DCHECK(map.is_callable());
        return kOtherUndetectable;
      }
      if (map.is_callable()) {
        return kOtherCallable;
      }
      return kOtherObject;
    case JS_ARRAY_TYPE:
      return kArray;
    case JS_PRIMITIVE_WRAPPER_TYPE: {
      DCHECK(!map.is_callable());
      DCHECK(!map.is_undetectable());
      auto elements_kind = map.elements_kind();
      if (elements_kind == ElementsKind::FAST_STRING_WRAPPER_ELEMENTS ||
          elements_kind == ElementsKind::SLOW_STRING_WRAPPER_ELEMENTS) {
        return kStringWrapper;
      }
      return kOtherObject;
    }
    case JS_MESSAGE_OBJECT_TYPE:
    case JS_DATE_TYPE:
#ifdef V8_INTL_SUPPORT
    case JS_V8_BREAK_ITERATOR_TYPE:
    case JS_COLLATOR_TYPE:
    case JS_DATE_TIME_FORMAT_TYPE:
    case JS_DISPLAY_NAMES_TYPE:
    case JS_DURATION_FORMAT_TYPE:
    case JS_LIST_FORMAT_TYPE:
    case JS_LOCALE_TYPE:
    case JS_NUMBER_FORMAT_TYPE:
    case JS_PLURAL_RULES_TYPE:
    case JS_RELATIVE_TIME_FORMAT_TYPE:
    case JS_SEGMENT_ITERATOR_TYPE:
    case JS_SEGMENTER_TYPE:
    case JS_SEGMENTS_TYPE:
#endif // V8_INTL_SUPPORT
    case JS_CONTEXT_EXTENSION_OBJECT_TYPE:
    case JS_DISPOSABLE_STACK_BASE_TYPE:
    case JS_ASYNC_DISPOSABLE_STACK_TYPE:
    case JS_SYNC_DISPOSABLE_STACK_TYPE:
    case JS_GENERATOR_OBJECT_TYPE:
    case JS_ASYNC_FUNCTION_OBJECT_TYPE:
    case JS_ASYNC_GENERATOR_OBJECT_TYPE:
    case JS_MODULE_NAMESPACE_TYPE:
    case JS_ARRAY_BUFFER_TYPE:
    case JS_ARRAY_ITERATOR_TYPE:
    case JS_REG_EXP_TYPE:
    case JS_REG_EXP_STRING_ITERATOR_TYPE:
    case JS_DATA_VIEW_TYPE:
    case JS_RAB_GSAB_DATA_VIEW_TYPE:
    case JS_SET_TYPE:
    case JS_MAP_TYPE:
    case JS_SET_KEY_VALUE_ITERATOR_TYPE:
    case JS_SET_VALUE_ITERATOR_TYPE:
    case JS_MAP_KEY_ITERATOR_TYPE:
    case JS_MAP_KEY_VALUE_ITERATOR_TYPE:
    case JS_MAP_VALUE_ITERATOR_TYPE:
    case JS_STRING_ITERATOR_TYPE:
    case JS_ASYNC_FROM_SYNC_ITERATOR_TYPE:
    case JS_ITERATOR_MAP_HELPER_TYPE:
    case JS_ITERATOR_FILTER_HELPER_TYPE:
    case JS_ITERATOR_TAKE_HELPER_TYPE:
    case JS_ITERATOR_DROP_HELPER_TYPE:
    case JS_ITERATOR_FLAT_MAP_HELPER_TYPE:
    case JS_VALID_ITERATOR_WRAPPER_TYPE:
    case JS_FINALIZATION_REGISTRY_TYPE:
    case JS_WEAK_MAP_TYPE:
    case JS_WEAK_REF_TYPE:
    case JS_WEAK_SET_TYPE:
    case JS_PROMISE_TYPE:
    case JS_SHADOW_REALM_TYPE:
    case JS_SHARED_ARRAY_TYPE:
    case JS_SHARED_STRUCT_TYPE:
    case JS_ATOMICS_CONDITION_TYPE:
    case JS_ATOMICS_MUTEX_TYPE:
#ifdef V8_TEMPORAL_SUPPORT
    case JS_TEMPORAL_DURATION_TYPE:
    case JS_TEMPORAL_INSTANT_TYPE:
    case JS_TEMPORAL_PLAIN_DATE_TYPE:
    case JS_TEMPORAL_PLAIN_DATE_TIME_TYPE:
    case JS_TEMPORAL_PLAIN_MONTH_DAY_TYPE:
    case JS_TEMPORAL_PLAIN_TIME_TYPE:
    case JS_TEMPORAL_PLAIN_YEAR_MONTH_TYPE:
    case JS_TEMPORAL_ZONED_DATE_TIME_TYPE:
#endif // V8_TEMPORAL_SUPPORT
    case JS_RAW_JSON_TYPE:
#if V8_ENABLE_WEBASSEMBLY
    case WASM_GLOBAL_OBJECT_TYPE:
    case WASM_INSTANCE_OBJECT_TYPE:
    case WASM_MEMORY_OBJECT_TYPE:
    case WASM_MODULE_OBJECT_TYPE:
    case WASM_SUSPENDER_OBJECT_TYPE:
    case WASM_SUSPENDING_OBJECT_TYPE:
    case WASM_TABLE_OBJECT_TYPE:
    case WASM_TAG_OBJECT_TYPE:
    case WASM_EXCEPTION_PACKAGE_TYPE:
    case WASM_VALUE_OBJECT_TYPE:
#endif // V8_ENABLE_WEBASSEMBLY
    case WEAK_CELL_TYPE:
      DCHECK(!map.is_callable());
      DCHECK(!map.is_undetectable());
      return kOtherObject;
#if V8_ENABLE_WEBASSEMBLY
    case WASM_STRUCT_TYPE:
    case WASM_ARRAY_TYPE:
      return kWasmObject;
#endif // V8_ENABLE_WEBASSEMBLY
    case JS_BOUND_FUNCTION_TYPE:
      DCHECK(!map.is_undetectable());
      return kBoundFunction;
    case JS_WRAPPED_FUNCTION_TYPE:
      DCHECK(!map.is_undetectable());
      return kOtherCallable;
    case JS_FUNCTION_TYPE:
    case JS_PROMISE_CONSTRUCTOR_TYPE:
    case JS_REG_EXP_CONSTRUCTOR_TYPE:
    case JS_ARRAY_CONSTRUCTOR_TYPE:
#define TYPED_ARRAY_CONSTRUCTORS_SWITCH(Type, type, TYPE, Ctype) \
  case TYPE##_TYPED_ARRAY_CONSTRUCTOR_TYPE:
      TYPED_ARRAYS(TYPED_ARRAY_CONSTRUCTORS_SWITCH)
#undef TYPED_ARRAY_CONSTRUCTORS_SWITCH
      DCHECK(!map.is_undetectable());
      return kCallableFunction;
    case JS_TYPED_ARRAY_TYPE:
      DCHECK(!map.is_callable());
      DCHECK(!map.is_undetectable());
      return kTypedArray;
    case JS_CLASS_CONSTRUCTOR_TYPE:
      return kClassConstructor;
    case JS_PROXY_TYPE:
      DCHECK(!map.is_undetectable());
      if (map.is_callable()) return kCallableProxy;
      return kOtherProxy;
    case MAP_TYPE:
    case ALLOCATION_SITE_TYPE:
    case ACCESSOR_INFO_TYPE:
    case SHARED_FUNCTION_INFO_TYPE:
    case FUNCTION_TEMPLATE_INFO_TYPE:
    case FUNCTION_TEMPLATE_RARE_DATA_TYPE:
    case ACCESSOR_PAIR_TYPE:
    case EMBEDDER_DATA_ARRAY_TYPE:
    case FIXED_ARRAY_TYPE:
    case CLASS_BOILERPLATE_TYPE:
    case PROPERTY_DESCRIPTOR_OBJECT_TYPE:
    case HASH_TABLE_TYPE:
    case ORDERED_HASH_MAP_TYPE:
    case ORDERED_HASH_SET_TYPE:
    case ORDERED_NAME_DICTIONARY_TYPE:
    case NAME_DICTIONARY_TYPE:
    case GLOBAL_DICTIONARY_TYPE:
    case NUMBER_DICTIONARY_TYPE:
    case SIMPLE_NUMBER_DICTIONARY_TYPE:
    case EPHEMERON_HASH_TABLE_TYPE:
    case WEAK_FIXED_ARRAY_TYPE:
    case WEAK_ARRAY_LIST_TYPE:
    case FIXED_DOUBLE_ARRAY_TYPE:
    case FEEDBACK_METADATA_TYPE:
    case BYTE_ARRAY_TYPE:
    case BYTECODE_ARRAY_TYPE:
    case OBJECT_BOILERPLATE_DESCRIPTION_TYPE:
    case ARRAY_BOILERPLATE_DESCRIPTION_TYPE:
    case REG_EXP_BOILERPLATE_DESCRIPTION_TYPE:
    case TRANSITION_ARRAY_TYPE:
    case FEEDBACK_CELL_TYPE:
    case CLOSURE_FEEDBACK_CELL_ARRAY_TYPE:
    case FEEDBACK_VECTOR_TYPE:
    case PROPERTY_ARRAY_TYPE:
    case FOREIGN_TYPE:
    case SCOPE_INFO_TYPE:
    case SCRIPT_CONTEXT_TABLE_TYPE:
    case AWAIT_CONTEXT_TYPE:
    case BLOCK_CONTEXT_TYPE:
    case CATCH_CONTEXT_TYPE:
    case DEBUG_EVALUATE_CONTEXT_TYPE:
    case EVAL_CONTEXT_TYPE:
    case FUNCTION_CONTEXT_TYPE:
    case MODULE_CONTEXT_TYPE:
    case MODULE_REQUEST_TYPE:
    case NATIVE_CONTEXT_TYPE:
    case SCRIPT_CONTEXT_TYPE:
    case WITH_CONTEXT_TYPE:
    case SCRIPT_TYPE:
    case INSTRUCTION_STREAM_TYPE:
    case CODE_TYPE:
    case PROPERTY_CELL_TYPE:
    case SOURCE_TEXT_MODULE_TYPE:
    case SOURCE_TEXT_MODULE_INFO_ENTRY_TYPE:
    case SYNTHETIC_MODULE_TYPE:
    case CELL_TYPE:
    case PREPARSE_DATA_TYPE:
    case UNCOMPILED_DATA_WITHOUT_PREPARSE_DATA_TYPE:
    case UNCOMPILED_DATA_WITH_PREPARSE_DATA_TYPE:
    case COVERAGE_INFO_TYPE:
    case REG_EXP_DATA_TYPE:
    case ATOM_REG_EXP_DATA_TYPE:
    case IR_REG_EXP_DATA_TYPE:
    case CONTEXT_CELL_TYPE:
#if V8_ENABLE_WEBASSEMBLY
    case WASM_TYPE_INFO_TYPE:
#endif // V8_ENABLE_WEBASSEMBLY
      return kOtherInternal;
    // Remaining instance types are unsupported for now. If any of them do
    // require bit set types, they should get kOtherInternal.
    default:
      UNREACHABLE();
  }
  UNREACHABLE();
}
References v8::internal::BIGINT_TYPE, broker(), v8::internal::CONS_ONE_BYTE_STRING_TYPE, v8::internal::CONS_TWO_BYTE_STRING_TYPE, v8::internal::DCHECK(), v8::internal::EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE, v8::internal::EXTERNAL_INTERNALIZED_TWO_BYTE_STRING_TYPE, v8::internal::EXTERNAL_ONE_BYTE_STRING_TYPE, v8::internal::EXTERNAL_TWO_BYTE_STRING_TYPE, v8::internal::FAST_STRING_WRAPPER_ELEMENTS, v8::internal::INTERNALIZED_ONE_BYTE_STRING_TYPE, v8::internal::INTERNALIZED_TWO_BYTE_STRING_TYPE, v8::internal::compiler::kBigInt, v8::internal::kBoolean, v8::internal::compiler::kBoolean, v8::internal::kInternalizedString, v8::internal::compiler::kNone, v8::internal::compiler::kNull, v8::internal::kNumber, v8::internal::kString, v8::internal::kSymbol, v8::internal::compiler::kUndefined, v8::internal::SEQ_ONE_BYTE_STRING_TYPE, v8::internal::SEQ_TWO_BYTE_STRING_TYPE, v8::internal::SHARED_EXTERNAL_ONE_BYTE_STRING_TYPE, v8::internal::SHARED_EXTERNAL_TWO_BYTE_STRING_TYPE, v8::internal::SHARED_SEQ_ONE_BYTE_STRING_TYPE, v8::internal::SHARED_SEQ_TWO_BYTE_STRING_TYPE, v8::internal::SHARED_UNCACHED_EXTERNAL_ONE_BYTE_STRING_TYPE, v8::internal::SHARED_UNCACHED_EXTERNAL_TWO_BYTE_STRING_TYPE, v8::internal::SLICED_ONE_BYTE_STRING_TYPE, v8::internal::SLICED_TWO_BYTE_STRING_TYPE, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, v8::internal::THIN_ONE_BYTE_STRING_TYPE, v8::internal::THIN_TWO_BYTE_STRING_TYPE, TYPED_ARRAY_CONSTRUCTORS_SWITCH, TYPED_ARRAYS, v8::internal::UNCACHED_EXTERNAL_INTERNALIZED_ONE_BYTE_STRING_TYPE, v8::internal::UNCACHED_EXTERNAL_INTERNALIZED_TWO_BYTE_STRING_TYPE, v8::internal::UNCACHED_EXTERNAL_ONE_BYTE_STRING_TYPE, v8::internal::UNCACHED_EXTERNAL_TWO_BYTE_STRING_TYPE, and v8::internal::UNREACHABLE().
Lub() [6/6]
template<typename MapRefLike >
static bitset v8::internal::compiler::BitsetType::Lub (MapRefLike map, JSHeapBroker * broker) [static], [private]
Max()
double v8::internal::compiler::BitsetType::Max (bitset bits) [static]
Definition at line 523 of file turbofan-types.cc.
                                  {
  DisallowGarbageCollection no_gc;
  DCHECK(Is(bits, kNumber));
  DCHECK(!Is(bits, kNaN));
  const Boundary* mins = Boundaries();
  bool mz = bits & kMinusZero;
  if (BitsetType::Is(mins[BoundariesSize() - 1].internal, bits)) {
    return +V8_INFINITY;
  }
  for (size_t i = BoundariesSize() - 1; i-- > 0;) {
    if (Is(mins[i].internal, bits)) {
      return mz ? std::max(0.0, mins[i + 1].min - 1) : mins[i + 1].min - 1;
    }
  }
  DCHECK(mz);
  return 0;
}
References v8::internal::DCHECK(), Is(), v8::internal::Is(), v8::internal::compiler::turboshaft::kMinusZero, v8::internal::compiler::turboshaft::kNaN, v8::internal::kNumber, v8::internal::compiler::BitsetType::Boundary::min, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and V8_INFINITY.
Min()
double v8::internal::compiler::BitsetType::Min (bitset bits) [static]
Definition at line 508 of file turbofan-types.cc.
                                  {
  DisallowGarbageCollection no_gc;
  DCHECK(Is(bits, kNumber));
  DCHECK(!Is(bits, kNaN));
  const Boundary* mins = Boundaries();
  bool mz = bits & kMinusZero;
  for (size_t i = 0; i < BoundariesSize(); ++i) {
    if (Is(mins[i].internal, bits)) {
      return mz ? std::min(0.0, mins[i].min) : mins[i].min;
    }
  }
  DCHECK(mz);
  return 0;
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Is(), v8::internal::compiler::turboshaft::kMinusZero, v8::internal::compiler::turboshaft::kNaN, v8::internal::kNumber, v8::internal::compiler::BitsetType::Boundary::min, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Name()
const char * v8::internal::compiler::BitsetType::Name (bitset bits) [static]
Definition at line 1061 of file turbofan-types.cc.
                                        {
  switch (bits) {
#define RETURN_NAMED_TYPE(type, value) \
  case k##type: \
    return #type;
    PROPER_BITSET_TYPE_LIST(RETURN_NAMED_TYPE)
    INTERNAL_BITSET_TYPE_LIST(RETURN_NAMED_TYPE)
#undef RETURN_NAMED_TYPE
    default:
      return nullptr;
  }
}
References INTERNAL_BITSET_TYPE_LIST, PROPER_BITSET_TYPE_LIST, and RETURN_NAMED_TYPE.
Referenced by Print().
NumberBits()
Type::bitset v8::internal::compiler::BitsetType::NumberBits (bitset bits) [static]
Definition at line 487 of file turbofan-types.cc.
{ return bits & kPlainNumber; }
Referenced by v8::internal::compiler::UnionType::Wellformed().
Print()
void v8::internal::compiler::BitsetType::Print (std::ostream & os, bitset bits) [static]
Definition at line 1075 of file turbofan-types.cc.
                                                  {
  DisallowGarbageCollection no_gc;
  const char* name = Name(bits);
  if (name != nullptr) {
    os << name;
    return;
  }
  // clang-format off
  static const bitset named_bitsets[] = {
#define BITSET_CONSTANT(type, value) k##type,
    INTERNAL_BITSET_TYPE_LIST(BITSET_CONSTANT)
    PROPER_BITSET_TYPE_LIST(BITSET_CONSTANT)
#undef BITSET_CONSTANT
  };
  // clang-format on
  bool is_first = true;
  os << "(";
  for (int i(arraysize(named_bitsets) - 1); bits != 0 && i >= 0; --i) {
    bitset subset = named_bitsets[i];
    if ((bits & subset) == subset) {
      if (!is_first) os << " | ";
      is_first = false;
      os << Name(subset);
      bits -= subset;
    }
  }
  DCHECK_EQ(0, bits);
  os << ")";
}
References arraysize, BITSET_CONSTANT, DCHECK_EQ, v8::internal::anonymous_namespace{json-stringifier.cc}::i, INTERNAL_BITSET_TYPE_LIST, Name(), v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and PROPER_BITSET_TYPE_LIST.
SignedSmall()
BitsetType::bitset v8::internal::compiler::BitsetType::SignedSmall () [static]
Definition at line 1161 of file turbofan-types.cc.
                                         {
  return SmiValuesAre31Bits() ? kSigned31 : kSigned32;
}
References v8::internal::compiler::kSigned32, and v8::internal::SmiValuesAre31Bits().
Referenced by v8::internal::compiler::Type::SignedSmall().
UnsignedSmall()
BitsetType::bitset v8::internal::compiler::BitsetType::UnsignedSmall () [static]
Definition at line 1165 of file turbofan-types.cc.
                                           {
  return SmiValuesAre31Bits() ? kUnsigned30 : kUnsigned31;
}
References v8::internal::SmiValuesAre31Bits().
Referenced by v8::internal::compiler::Type::UnsignedSmall().
Member Data Documentation
BoundariesArray
const BitsetType::Boundary v8::internal::compiler::BitsetType::BoundariesArray [static], [private]
Initial value:
= {
    {kOtherNumber, kPlainNumber, -V8_INFINITY},
    {kOtherSigned32, kNegative32, kMinInt},
    {kNegative31, kNegative31, -0x40000000},
    {kUnsigned30, kUnsigned30, 0},
    {kOtherUnsigned31, kUnsigned31, 0x40000000},
    {kOtherUnsigned32, kUnsigned32, 0x80000000},
    {kOtherNumber, kPlainNumber, static_cast<double>(kMaxUInt32) + 1}}
Definition at line 311 of file turbofan-types.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turbofan-types.h
/mnt/V8SourceCode/src/compiler/turbofan-types.cc