v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer Class Reference
#include <late-load-elimination-reducer.h>
Classes
struct Snapshot
Public Types
enum class RawBaseAssumption { kNoInnerPointer
, kMaybeInnerPointer
 }
using AliasTable = SparseOpIndexSnapshotTable< bool >
using AliasKey = AliasTable::Key
using AliasSnapshot = AliasTable::Snapshot
using MapTable = SparseOpIndexSnapshotTable< MapMaskAndOr >
using MapKey = MapTable::Key
using MapSnapshot = MapTable::Snapshot
using MemoryKey = MemoryContentTable::Key
using MemorySnapshot = MemoryContentTable::Snapshot
using Replacement = LoadEliminationReplacement
Public Member Functions
LateLoadEliminationAnalyzer (PipelineData *data, Graph &graph, Zone *phase_zone, JSHeapBroker *broker, RawBaseAssumption raw_base_assumption)
void Run ()
Replacement GetReplacement (OpIndex index)
Private Member Functions
void ProcessBlock (const Block &block, bool compute_start_snapshot)
void ProcessLoad (OpIndex op_idx, const LoadOp &op)
void ProcessStore (OpIndex op_idx, const StoreOp &op)
void ProcessAtomicRMW (OpIndex op_idx, const AtomicRMWOp &op)
void ProcessAllocate (OpIndex op_idx, const AllocateOp &op)
void ProcessCall (OpIndex op_idx, const CallOp &op)
void ProcessAssumeMap (OpIndex op_idx, const AssumeMapOp &op)
void ProcessChange (OpIndex op_idx, const ChangeOp &change)
void DcheckWordBinop (OpIndex op_idx, const WordBinopOp &binop)
template<bool for_loop_revisit = false>
bool BeginBlock (const Block *block)
void FinishBlock (const Block *block)
void SealAndDiscard ()
void StoreLoopSnapshotInForwardPredecessor (const Block &loop_header)
bool BackedgeHasSnapshot (const Block &loop_header) const
void InvalidateAllNonAliasingInputs (const Operation &op)
void InvalidateIfAlias (OpIndex op_idx)
Private Attributes
PipelineData * data_
Graph & graph_
Zone * phase_zone_
JSHeapBroker * broker_
RawBaseAssumption raw_base_assumption_
FixedOpIndexSidetable< Replacement > replacements_
std::map< OpIndex, base::SmallMap< std::map< OpIndex, OpIndex >, 4 > > int32_truncated_loads_
AliasTable non_aliasing_objects_
MapTable object_maps_
MemoryContentTable memory_
FixedBlockSidetable< std::optional< Snapshot > > block_to_snapshot_mapping_
ZoneVector< AliasSnapshot > predecessor_alias_snapshots_
ZoneVector< MapSnapshot > predecessor_maps_snapshots_
ZoneVector< MemorySnapshot > predecessor_memory_snapshots_
Detailed Description
Definition at line 669 of file late-load-elimination-reducer.h.
Member Typedef Documentation
AliasKey
using v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::AliasKey = AliasTable::Key
Definition at line 672 of file late-load-elimination-reducer.h.
AliasSnapshot
using v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::AliasSnapshot = AliasTable::Snapshot
Definition at line 673 of file late-load-elimination-reducer.h.
AliasTable
using v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::AliasTable = SparseOpIndexSnapshotTable<bool>
Definition at line 671 of file late-load-elimination-reducer.h.
MapKey
using v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::MapKey = MapTable::Key
Definition at line 676 of file late-load-elimination-reducer.h.
MapSnapshot
using v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::MapSnapshot = MapTable::Snapshot
Definition at line 677 of file late-load-elimination-reducer.h.
MapTable
using v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::MapTable = SparseOpIndexSnapshotTable<MapMaskAndOr>
Definition at line 675 of file late-load-elimination-reducer.h.
MemoryKey
using v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::MemoryKey = MemoryContentTable::Key
Definition at line 679 of file late-load-elimination-reducer.h.
MemorySnapshot
using v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::MemorySnapshot = MemoryContentTable::Snapshot
Definition at line 680 of file late-load-elimination-reducer.h.
Replacement
using v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Replacement = LoadEliminationReplacement
Definition at line 682 of file late-load-elimination-reducer.h.
Member Enumeration Documentation
RawBaseAssumption
enum v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::RawBaseAssumption [strong]
Enumerator
kNoInnerPointer
kMaybeInnerPointer
Definition at line 684 of file late-load-elimination-reducer.h.
                               {
    kNoInnerPointer,
    kMaybeInnerPointer,
  };
Constructor & Destructor Documentation
LateLoadEliminationAnalyzer()
v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::LateLoadEliminationAnalyzer (PipelineData * data, Graph & graph, Zone * phase_zone, JSHeapBroker * broker, RawBaseAssumption raw_base_assumption) [inline]
Definition at line 689 of file late-load-elimination-reducer.h.
      : data_(data),
        graph_(graph),
        phase_zone_(phase_zone),
        broker_(broker),
        raw_base_assumption_(raw_base_assumption),
        replacements_(graph.op_id_count(), phase_zone, &graph),
        non_aliasing_objects_(phase_zone),
        object_maps_(phase_zone),
        memory_(phase_zone, non_aliasing_objects_, object_maps_, replacements_),
        block_to_snapshot_mapping_(graph.block_count(), phase_zone),
        predecessor_alias_snapshots_(phase_zone),
        predecessor_maps_snapshots_(phase_zone),
        predecessor_memory_snapshots_(phase_zone) {
    USE(data_);
  }
References USE.
Member Function Documentation
BackedgeHasSnapshot()
bool v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BackedgeHasSnapshot (const Block & loop_header) const [private]
Definition at line 656 of file late-load-elimination-reducer.cc.
                                    {
  DCHECK(loop_header.IsLoop());
  return block_to_snapshot_mapping_[loop_header.LastPredecessor()->index()]
      .has_value();
}
References block_to_snapshot_mapping_, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Block::IsLoop(), and v8::internal::compiler::turboshaft::Block::LastPredecessor().
Referenced by ProcessBlock().
BeginBlock()
template<bool for_loop_revisit>
template bool v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::BeginBlock< false > (const Block * block) [private]
Definition at line 664 of file late-load-elimination-reducer.cc.
                                                               {
  DCHECK_IMPLIES(
      for_loop_revisit,
      block->IsLoop() &&
          block_to_snapshot_mapping_[block->LastPredecessor()->index()]
              .has_value());
  // Collect the snapshots of all predecessors.
  {
    predecessor_alias_snapshots_.clear();
    predecessor_maps_snapshots_.clear();
    predecessor_memory_snapshots_.clear();
    for (const Block* p : block->PredecessorsIterable()) {
      auto pred_snapshots = block_to_snapshot_mapping_[p->index()];
      // When we visit the loop for the first time, the loop header hasn't
      // been visited yet, so we ignore it.
      DCHECK_IMPLIES(!pred_snapshots.has_value(),
                     block->IsLoop() && block->LastPredecessor() == p);
      if (!pred_snapshots.has_value()) {
        DCHECK(!for_loop_revisit);
        continue;
      }
      // Note that the backedge snapshot of an inner loop in kFirstVisit will
      // also be taken into account if we are in the kSecondVisit of an outer
      // loop. The data in the backedge snapshot could be out-dated, but if it
      // is, then it's fine: if the backedge of the outer-loop was more
      // restrictive than its forward incoming edge, then the forward incoming
      // edge of the inner loop should reflect this restriction.
      predecessor_alias_snapshots_.push_back(pred_snapshots->alias_snapshot);
      predecessor_memory_snapshots_.push_back(pred_snapshots->memory_snapshot);
      if (p->NeighboringPredecessor() != nullptr || !block->IsLoop() ||
          block->LastPredecessor() != p) {
        // We only add a MapSnapshot predecessor for non-backedge predecessor.
        // This is because maps coming from inside of the loop may be wrong
        // until a specific check has been executed.
        predecessor_maps_snapshots_.push_back(pred_snapshots->maps_snapshot);
      }
    }
  }
  // Note that predecessors are in reverse order, which means that the backedge
  // is at offset 0.
  constexpr int kBackedgeOffset = 0;
  constexpr int kForwardEdgeOffset = 1;
  bool loop_needs_revisit = false;
  // Start a new snapshot for this block by merging information from
  // predecessors.
  auto merge_aliases = [&](AliasKey key,
                           base::Vector<const bool> predecessors) -> bool {
    if (for_loop_revisit && predecessors[kForwardEdgeOffset] &&
        !predecessors[kBackedgeOffset]) {
      // The backedge doesn't think that {key} is no-alias, but the loop
      // header previously thought it was --> need to revisit.
      loop_needs_revisit = true;
    }
    return base::all_of(predecessors);
  };
  non_aliasing_objects_.StartNewSnapshot(
      base::VectorOf(predecessor_alias_snapshots_), merge_aliases);
  auto merge_maps =
      [&](MapKey key,
          base::Vector<const MapMaskAndOr> predecessors) -> MapMaskAndOr {
    MapMaskAndOr minmax;
    for (const MapMaskAndOr pred : predecessors) {
      if (is_empty(pred)) {
        // One of the predecessors doesn't have maps for this object, so we have
        // to assume that this object could have any map.
        return MapMaskAndOr{};
      }
      minmax = CombineMinMax(minmax, pred);
    }
    return minmax;
  };
  object_maps_.StartNewSnapshot(base::VectorOf(predecessor_maps_snapshots_),
                                merge_maps);
  // Merging for {memory_} means setting values to Invalid unless all
  // predecessors have the same value.
  // TODO(dmercadier): we could insert of Phis during the pass to merge existing
  // information. This is a bit hard, because we are currently in an analyzer
  // rather than a reducer. Still, we could "prepare" the insertion now and then
  // really insert them during the Reduce phase of the CopyingPhase.
  auto merge_memory = [&](MemoryKey key,
                          base::Vector<const OpIndex> predecessors) -> OpIndex {
    if (for_loop_revisit && predecessors[kForwardEdgeOffset].valid() &&
        predecessors[kBackedgeOffset] != predecessors[kForwardEdgeOffset]) {
      // {key} had a value in the loop header, but the backedge and the forward
      // edge don't agree on its value, which means that the loop invalidated
      // some memory data, and thus needs to be revisited.
      loop_needs_revisit = true;
    }
    return base::all_equal(predecessors) ? predecessors[0] : OpIndex::Invalid();
  };
  memory_.StartNewSnapshot(base::VectorOf(predecessor_memory_snapshots_),
                           merge_memory);
  if (block->IsLoop()) return loop_needs_revisit;
  return false;
}
References v8::base::all_equal(), v8::base::all_of(), block_to_snapshot_mapping_, v8::internal::ZoneVector< T >::clear(), v8::internal::compiler::turboshaft::CombineMinMax(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::is_empty(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::key, v8::internal::compiler::turboshaft::Block::LastPredecessor(), memory_, non_aliasing_objects_, object_maps_, predecessor_alias_snapshots_, predecessor_maps_snapshots_, predecessor_memory_snapshots_, v8::internal::compiler::turboshaft::Block::PredecessorsIterable(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot(), and v8::base::VectorOf().
Referenced by ProcessBlock().
DcheckWordBinop()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::DcheckWordBinop (OpIndex op_idx, const WordBinopOp & binop) [private]
Definition at line 521 of file late-load-elimination-reducer.cc.
                                                                            {
#ifdef DEBUG
  auto check = [&](V<Word> left, V<Word> right) {
    if (auto key = non_aliasing_objects_.TryGetKeyFor(left);
        key.has_value() && non_aliasing_objects_.Get(*key)) {
      int64_t cst;
      DCHECK_EQ(binop.kind, WordBinopOp::Kind::kBitwiseAnd);
      DCHECK(OperationMatcher(graph_).MatchSignedIntegralConstant(right, &cst));
      DCHECK_EQ(cst, kSmiTagMask);
    }
  };
  check(binop.left(), binop.right());
  check(binop.right(), binop.left());
#endif
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), graph_, v8::internal::compiler::turboshaft::WordBinopOp::kBitwiseAnd, v8::internal::key, v8::internal::compiler::turboshaft::WordBinopOp::kind, v8::internal::kSmiTagMask, v8::internal::compiler::turboshaft::WordBinopOp::left(), non_aliasing_objects_, v8::internal::compiler::turboshaft::WordBinopOp::right(), and v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::TryGetKeyFor().
Referenced by ProcessBlock().
FinishBlock()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::FinishBlock (const Block * block) [private]
Definition at line 629 of file late-load-elimination-reducer.cc.
                                                                {
  block_to_snapshot_mapping_[block->index()] = Snapshot{
      non_aliasing_objects_.Seal(), object_maps_.Seal(), memory_.Seal()};
}
References block_to_snapshot_mapping_, v8::internal::compiler::turboshaft::Block::index(), memory_, non_aliasing_objects_, object_maps_, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal().
Referenced by ProcessBlock(), and Run().
GetReplacement()
Replacement v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::GetReplacement (OpIndex index) [inline]
Definition at line 710 of file late-load-elimination-reducer.h.
{ return replacements_[index]; }
References v8::internal::index.
Referenced by Run().
InvalidateAllNonAliasingInputs()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::InvalidateAllNonAliasingInputs (const Operation & op) [private]
Definition at line 538 of file late-load-elimination-reducer.cc.
                         {
  TRACE(">> InvalidateAllNonAliasingInputs for " << op);
  for (OpIndex input : op.inputs()) {
    InvalidateIfAlias(input);
  }
}
References v8::internal::compiler::turboshaft::Operation::inputs(), InvalidateIfAlias(), and v8::internal::TRACE().
Referenced by ProcessBlock(), and ProcessCall().
InvalidateIfAlias()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::InvalidateIfAlias (OpIndex op_idx) [private]
Definition at line 546 of file late-load-elimination-reducer.cc.
                                                                  {
  if (auto key = non_aliasing_objects_.TryGetKeyFor(op_idx);
      key.has_value() && non_aliasing_objects_.Get(*key)) {
    // An known non-aliasing object was passed as input to the Call; the Call
    // could create aliases, so we have to consider going forward that this
    // object could actually have aliases.
    TRACE(">> InvalidateIfAlias: invalidating for id=" << op_idx);
    non_aliasing_objects_.Set(*key, false);
  }
  if (const FrameStateOp* frame_state =
          graph_.Get(op_idx).TryCast<FrameStateOp>()) {
    TRACE(
        ">> InvalidateIfAlias: recursively invalidating for FrameState inputs "
        "(FrameState id="
        << op_idx << ")");
    // We also mark the arguments of FrameState passed on to calls as
    // potentially-aliasing, because they could be accessed by the caller with a
    // function_name.arguments[index].
    // TODO(dmercadier): this is more conservative that we'd like, since only a
    // few functions use .arguments. Using a native-context-specific protector
    // for .arguments might allow to avoid invalidating frame states' content.
    for (OpIndex input : frame_state->inputs()) {
      InvalidateIfAlias(input);
    }
  }
}
References v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), graph_, v8::internal::key, non_aliasing_objects_, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set(), v8::internal::TRACE(), v8::internal::compiler::turboshaft::Operation::TryCast(), and v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::TryGetKeyFor().
Referenced by InvalidateAllNonAliasingInputs(), and ProcessChange().
ProcessAllocate()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessAllocate (OpIndex op_idx, const AllocateOp & op) [private]
Definition at line 573 of file late-load-elimination-reducer.cc.
                                                                     {
  TRACE("> ProcessAllocate(" << op_idx << ") ==> Fresh non-aliasing object");
  non_aliasing_objects_.Set(op_idx, true);
}
References non_aliasing_objects_, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set(), and v8::internal::TRACE().
Referenced by ProcessBlock().
ProcessAssumeMap()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessAssumeMap (OpIndex op_idx, const AssumeMapOp & op) [private]
Definition at line 579 of file late-load-elimination-reducer.cc.
                                                   {
  TRACE("> ProcessAssumeMap(" << op_idx << ")");
  OpIndex object = assume_map.heap_object();
  object_maps_.Set(object, CombineMinMax(object_maps_.Get(object),
                                         ComputeMinMaxHash(assume_map.maps)));
}
References v8::internal::compiler::turboshaft::CombineMinMax(), v8::internal::compiler::turboshaft::ComputeMinMaxHash(), v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Get(), v8::internal::compiler::turboshaft::AssumeMapOp::heap_object(), v8::internal::compiler::turboshaft::AssumeMapOp::maps, object_maps_, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set(), and v8::internal::TRACE().
Referenced by ProcessBlock().
ProcessAtomicRMW()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessAtomicRMW (OpIndex op_idx, const AtomicRMWOp & op) [private]
Definition at line 430 of file late-load-elimination-reducer.cc.
                                                                             {
#if V8_ENABLE_WEBASSEMBLY
  TRACE("> ProcessAtomicRMW(" << op_idx << ")");
  // With shared-everything-treads atomic rmw operations are also used for heap
  // operations. If the atomic operation is not operating on linear memory, we
  // need to invalidate it. TODO(mliedtke): Only invalidate the potentially
  // aliasing information.
  if (!v8_flags.experimental_wasm_shared ||
      store.base_rep == RegisterRepresentation::WordPtr()) {
    TRACE(">> Skipping operation on linear memory");
    return;
  }
  TRACE(">> Invalidating whole maybe-aliasing memory");
  memory_.InvalidateMaybeAliasing();
#endif
}
References v8::internal::compiler::turboshaft::MemoryContentTable::InvalidateMaybeAliasing(), memory_, store(), v8::internal::TRACE(), v8::internal::v8_flags, and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
Referenced by ProcessBlock().
ProcessBlock()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessBlock (const Block & block, bool compute_start_snapshot) [private]
Definition at line 163 of file late-load-elimination-reducer.cc.
                                                                            {
  TRACE("> ProcessBlock(" << block.index() << ")");
  if (compute_start_snapshot) {
    BeginBlock(&block);
  }
  if (block.IsLoop() && BackedgeHasSnapshot(block)) {
    // Update the associated snapshot for the forward edge with the merged
    // snapshot information from the forward- and backward edge.
    // This will make sure that when evaluating whether a loop needs to be
    // revisited, the inner loop compares the merged state with the backedge
    // preventing us from exponential revisits for loops where the backedge
    // invalidates loads which are eliminatable on the forward edge.
    StoreLoopSnapshotInForwardPredecessor(block);
  }
  for (OpIndex op_idx : graph_.OperationIndices(block)) {
    Operation& op = graph_.Get(op_idx);
    if (ShouldSkipOptimizationStep()) continue;
    if (ShouldSkipOperation(op)) continue;
    switch (op.opcode) {
      case Opcode::kLoad:
        // Eliminate load or update state
        ProcessLoad(op_idx, op.Cast<LoadOp>());
        break;
      case Opcode::kStore:
        // Update state (+ maybe invalidate aliases)
        ProcessStore(op_idx, op.Cast<StoreOp>());
        break;
      case Opcode::kAllocate:
        // Create new non-alias
        ProcessAllocate(op_idx, op.Cast<AllocateOp>());
        break;
      case Opcode::kCall:
        // Invalidate state (+ maybe invalidate aliases)
        ProcessCall(op_idx, op.Cast<CallOp>());
        break;
      case Opcode::kAssumeMap:
        // Update known maps
        ProcessAssumeMap(op_idx, op.Cast<AssumeMapOp>());
        break;
      case Opcode::kChange:
        // Check for tagged -> word32 load replacement
        ProcessChange(op_idx, op.Cast<ChangeOp>());
        break;
      case Opcode::kWordBinop:
        // A WordBinop should never invalidate aliases (since the only time when
        // it should take a non-aliasing object as input is for Smi checks).
        DcheckWordBinop(op_idx, op.Cast<WordBinopOp>());
        break;
      case Opcode::kFrameState:
      case Opcode::kDeoptimizeIf:
      case Opcode::kComparison:
#ifdef V8_ENABLE_WEBASSEMBLY
      case Opcode::kTrapIf:
#endif
        // We explicitly break for these opcodes so that we don't call
        // InvalidateAllNonAliasingInputs on their inputs, since they don't
        // really create aliases. (and also, they don't write so it's
        // fine to break)
        DCHECK(!op.Effects().can_write());
        break;
      case Opcode::kDeoptimize:
      case Opcode::kReturn:
        // We explicitly break for these opcodes so that we don't call
        // InvalidateAllNonAliasingInputs on their inputs, since they are block
        // terminators without successors, meaning that it's not useful for the
        // rest of the analysis to invalidate anything here.
        DCHECK(op.IsBlockTerminator() && SuccessorBlocks(op).empty());
        break;
      case Opcode::kAtomicRMW:
        ProcessAtomicRMW(op_idx, op.Cast<AtomicRMWOp>());
        break;
      case Opcode::kCatchBlockBegin:
      case Opcode::kRetain:
      case Opcode::kDidntThrow:
      case Opcode::kCheckException:
      case Opcode::kAtomicWord32Pair:
      case Opcode::kMemoryBarrier:
      case Opcode::kParameter:
      case Opcode::kDebugBreak:
      case Opcode::kJSStackCheck:
#ifdef V8_ENABLE_WEBASSEMBLY
      case Opcode::kWasmStackCheck:
      case Opcode::kSimd128LaneMemory:
      case Opcode::kGlobalSet:
      case Opcode::kArraySet:
      case Opcode::kStructSet:
      case Opcode::kSetStackPointer:
#endif // V8_ENABLE_WEBASSEMBLY
        // We explicitly break for those operations that have can_write effects
        // but don't actually write, or cannot interfere with load elimination.
        break;
      default:
        // Operations that `can_write` should invalidate the state. All such
        // operations should be already handled above, which means that we don't
        // need a `if (can_write) { Invalidate(); }` here.
        CHECK(!op.Effects().can_write());
        // Even if the operation doesn't write, it could create an alias to its
        // input by returning it. This happens for instance in Phis and in
        // Change (although ChangeOp is already handled earlier by calling
        // ProcessChange). We are conservative here by calling
        // InvalidateAllNonAliasingInputs for all operations even though only
        // few can actually create aliases to fresh allocations, the reason
        // being that missing such a case would be a security issue, and it
        // should be rare for fresh allocations to be used outside of
        // Call/Store/Load/Change anyways.
        TRACE("> Process other op (id=" << op_idx << ")");
        InvalidateAllNonAliasingInputs(op);
        break;
    }
  }
  FinishBlock(&block);
}
References BackedgeHasSnapshot(), BeginBlock(), v8::internal::compiler::turboshaft::OpEffects::can_write(), v8::internal::compiler::turboshaft::Operation::Cast(), CHECK, v8::internal::DCHECK(), DcheckWordBinop(), v8::internal::compiler::turboshaft::Operation::Effects(), FinishBlock(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::Block::index(), InvalidateAllNonAliasingInputs(), v8::internal::compiler::turboshaft::Operation::IsBlockTerminator(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::Graph::OperationIndices(), ProcessAllocate(), ProcessAssumeMap(), ProcessAtomicRMW(), ProcessCall(), ProcessChange(), ProcessLoad(), ProcessStore(), v8::internal::compiler::turboshaft::ShouldSkipOperation(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), StoreLoopSnapshotInForwardPredecessor(), v8::internal::compiler::turboshaft::SuccessorBlocks(), and v8::internal::TRACE().
Referenced by Run().
ProcessCall()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessCall (OpIndex op_idx, const CallOp & op) [private]
Definition at line 452 of file late-load-elimination-reducer.cc.
                                                                {
  TRACE("> ProcessCall(" << op_idx << ")");
  const Operation& callee = graph_.Get(op.callee());
#ifdef DEBUG
  if (const ConstantOp* external_constant =
          callee.template TryCast<Opmask::kExternalConstant>()) {
    if (external_constant->external_reference() ==
        ExternalReference::check_object_type()) {
      return;
    }
  }
#endif
  // Some builtins do not create aliases and do not invalidate existing
  // memory, and some even return fresh objects. For such cases, we don't
  // invalidate the state, and record the non-alias if any.
  if (!op.Effects().can_write()) {
    TRACE(">> Call doesn't write, skipping");
    return;
  }
  auto builtin_id = TryGetBuiltinId(callee.TryCast<ConstantOp>(), broker_);
  if (builtin_id) {
    switch (*builtin_id) {
      // TODO(dmercadier): extend this list.
      case Builtin::kCopyFastSmiOrObjectElements:
        // This function just replaces the Elements array of an object.
        // It doesn't invalidate any alias or any other memory than this
        // Elements array.
        TRACE(
            ">> Call is CopyFastSmiOrObjectElements, invalidating only "
            "Elements for "
            << op.arguments()[0]);
        memory_.Invalidate(op.arguments()[0], OpIndex::Invalid(),
                           JSObject::kElementsOffset);
        return;
      default:
        break;
    }
  }
  // Not a builtin call, or not a builtin that we know doesn't invalidate
  // memory.
  InvalidateAllNonAliasingInputs(op);
  if (builtin_id) {
    switch (*builtin_id) {
      case Builtin::kCreateShallowObjectLiteral:
        // This builtin creates a fresh non-aliasing object.
        non_aliasing_objects_.Set(op_idx, true);
        break;
      default:
        break;
    }
  }
  // The call could modify arbitrary memory, so we invalidate every
  // potentially-aliasing object.
  memory_.InvalidateMaybeAliasing();
}
References v8::internal::compiler::turboshaft::CallOp::arguments(), broker_, v8::internal::compiler::turboshaft::CallOp::callee(), v8::internal::compiler::turboshaft::OpEffects::can_write(), v8::internal::compiler::turboshaft::CallOp::Effects(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::MemoryContentTable::Invalidate(), InvalidateAllNonAliasingInputs(), v8::internal::compiler::turboshaft::MemoryContentTable::InvalidateMaybeAliasing(), memory_, non_aliasing_objects_, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set(), v8::internal::TRACE(), v8::internal::compiler::turboshaft::Operation::TryCast(), and v8::internal::compiler::turboshaft::TryGetBuiltinId().
Referenced by ProcessBlock().
ProcessChange()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessChange (OpIndex op_idx, const ChangeOp & change) [private]
Definition at line 613 of file late-load-elimination-reducer.cc.
                                                                        {
  TRACE("> ProcessChange(" << op_idx << ")");
  // We look for this special case:
  // TruncateWord64ToWord32(BitcastTaggedToWordPtrForTagAndSmiBits(Load(x))) =>
  // Load(x)
  // where the new Load uses Int32 rather than the tagged representation.
  OpIndex bitcast_idx, load_idx;
  if (IsInt32TruncatedLoadPattern(graph_, op_idx, change, &bitcast_idx,
                                  &load_idx)) {
    int32_truncated_loads_[load_idx][op_idx] = bitcast_idx;
  }
  InvalidateIfAlias(change.input());
}
References graph_, v8::internal::compiler::turboshaft::ChangeOp::input(), int32_truncated_loads_, InvalidateIfAlias(), v8::internal::compiler::turboshaft::IsInt32TruncatedLoadPattern(), and v8::internal::TRACE().
Referenced by ProcessBlock().
ProcessLoad()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad (OpIndex op_idx, const LoadOp & op) [private]
Definition at line 317 of file late-load-elimination-reducer.cc.
                                                                  {
  TRACE("> ProcessLoad(" << op_idx << ")");
  if (!load.kind.load_eliminable) {
    // We don't optimize Loads/Stores to addresses that could be accessed
    // non-canonically.
    TRACE(">> Not load-eliminable; skipping");
    return;
  }
  if (load.kind.is_atomic) {
    // Atomic loads cannot be eliminated away, but potential concurrency
    // invalidates known stored values.
    TRACE(">> Atomic load, invalidating related memory");
    memory_.Invalidate(load.base(), load.index(), load.offset);
    return;
  }
  // We need to insert the load into the truncation mapping as a key, because
  // all loads need to be revisited during processing.
  int32_truncated_loads_[op_idx];
  if (OpIndex existing = memory_.Find(load); existing.valid()) {
    const Operation& replacement = graph_.Get(existing);
    // We need to make sure that {load} and {replacement} have the same output
    // representation. In particular, in unreachable code, it's possible that
    // the two of them have incompatible representations (like one could be
    // Tagged and the other one Float64).
    DCHECK_EQ(replacement.outputs_rep().size(), 1);
    DCHECK_EQ(load.outputs_rep().size(), 1);
    TRACE(">> Found potential replacement at offset " << existing);
    if (RepIsCompatible(replacement.outputs_rep()[0], load.outputs_rep()[0],
                        load.loaded_rep)) {
      TRACE(">>> Confirming replacement");
      replacements_[op_idx] = Replacement::LoadElimination(existing);
      return;
    } else {
      TRACE(">>> Replacement has wrong representation: "
            << replacement.outputs_rep()[0] << " instead of "
            << load.outputs_rep()[0]);
    }
  }
  // Reset the replacement of {op_idx} to Invalid, in case a previous visit of a
  // loop has set it to something else.
  replacements_[op_idx] = Replacement::None();
  // TODO(dmercadier): if we precisely track maps, then we could know from the
  // map what we are loading in some cases. For instance, if the elements_kind
  // of the map is *_DOUBLE_ELEMENTS, then a load at offset
  // JSObject::kElementsOffset always load a FixedDoubleArray, with map
  // fixed_double_array_map.
  if (const ConstantOp* base = graph_.Get(load.base()).TryCast<ConstantOp>();
      base != nullptr && base->kind == ConstantOp::Kind::kExternal) {
    // External constants can be written by other threads, so we don't
    // load-eliminate them, in order to always reload them.
    TRACE(">> Ignoring load from External constant");
    return;
  }
  memory_.Insert(load, op_idx);
}
References v8::internal::compiler::turboshaft::LoadOp::base(), DCHECK_EQ, v8::internal::compiler::turboshaft::MemoryContentTable::Find(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::LoadOp::index(), v8::internal::compiler::turboshaft::MemoryContentTable::Insert(), int32_truncated_loads_, v8::internal::compiler::turboshaft::MemoryContentTable::Invalidate(), v8::internal::compiler::turboshaft::LoadOp::Kind::is_atomic, v8::internal::compiler::turboshaft::ConstantOp::kExternal, v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::LoadOp::kind, v8::internal::compiler::turboshaft::LoadOp::Kind::load_eliminable, v8::internal::compiler::turboshaft::LoadOp::loaded_rep, v8::internal::compiler::turboshaft::LoadEliminationReplacement::LoadElimination(), memory_, v8::internal::compiler::turboshaft::LoadEliminationReplacement::None(), v8::internal::compiler::turboshaft::LoadOp::offset, v8::internal::compiler::turboshaft::Operation::outputs_rep(), v8::internal::compiler::turboshaft::LoadOp::outputs_rep(), v8::internal::compiler::turboshaft::RepIsCompatible(), replacements_, v8::internal::TRACE(), v8::internal::compiler::turboshaft::Operation::TryCast(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by ProcessBlock().
ProcessStore()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessStore (OpIndex op_idx, const StoreOp & op) [private]
Definition at line 380 of file late-load-elimination-reducer.cc.
                                                                     {
  TRACE("> ProcessStore(" << op_idx << ")");
  // If we have a raw base and we allow those to be inner pointers, we can
  // overwrite arbitrary values and need to invalidate anything that is
  // potentially aliasing.
  const bool invalidate_maybe_aliasing =
      !store.kind.tagged_base &&
      raw_base_assumption_ == RawBaseAssumption::kMaybeInnerPointer;
  if (invalidate_maybe_aliasing) {
    TRACE(
        ">> Raw base or maybe inner pointer ==> Invalidating whole "
        "maybe-aliasing memory");
    memory_.InvalidateMaybeAliasing();
  }
  if (!store.kind.load_eliminable) {
    // We don't optimize Loads/Stores to addresses that could be accessed
    // non-canonically.
    TRACE(">> Not load-eliminable; skipping");
    return;
  }
  // Updating the known stored values.
  if (!invalidate_maybe_aliasing) memory_.Invalidate(store);
  memory_.Insert(store);
  // Updating aliases if the value stored was known as non-aliasing.
  OpIndex value = store.value();
  if (non_aliasing_objects_.HasKeyFor(value)) {
    TRACE(">> Invalidate non-alias for value=" << value);
    non_aliasing_objects_.Set(value, false);
  }
  // If we just stored a map, invalidate all object_maps_.
  if (store.offset == HeapObject::kMapOffset && !store.index().valid()) {
    // TODO(dmercadier): can we only do this for objects that are potentially
    // aliasing with the `base` (based on their maps and the maps of `base`)?
    // Also, it might be worth to record a new map if this is actually a map
    // store.
    // TODO(dmercadier): do this only if `value` is a Constant with kind
    // kHeapObject, since all map stores should store a known constant maps.
    TRACE(">> Wiping all maps\n");
    for (auto it : object_maps_) {
      object_maps_.Set(it.second, MapMaskAndOr{});
    }
  }
}
References v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::HasKeyFor(), v8::internal::compiler::turboshaft::MemoryContentTable::Insert(), v8::internal::compiler::turboshaft::MemoryContentTable::Invalidate(), v8::internal::compiler::turboshaft::MemoryContentTable::InvalidateMaybeAliasing(), v8::internal::HeapObject::kMapOffset, kMaybeInnerPointer, memory_, non_aliasing_objects_, object_maps_, raw_base_assumption_, v8::internal::compiler::turboshaft::SparseOpIndexSnapshotTable< Value, KeyData >::Set(), store(), v8::internal::TRACE(), and v8::internal::value.
Referenced by ProcessBlock().
Run()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run ()
Definition at line 35 of file late-load-elimination-reducer.cc.
                                      {
  TRACE("LateLoadElimination: Starting analysis");
  LoopFinder loop_finder(phase_zone_, &graph_, LoopFinder::Config{});
  AnalyzerIterator iterator(phase_zone_, graph_, loop_finder);
  bool compute_start_snapshot = true;
  while (iterator.HasNext()) {
    const Block* block = iterator.Next();
    ProcessBlock(*block, compute_start_snapshot);
    compute_start_snapshot = true;
    // Consider re-processing for loops.
    if (const GotoOp* last = block->LastOperation(graph_).TryCast<GotoOp>()) {
      if (last->destination->IsLoop() &&
          last->destination->LastPredecessor() == block) {
        TRACE("> Considering reprocessing loop header " << last->destination);
        const Block* loop_header = last->destination;
        // {block} is the backedge of a loop. We recompute the loop header's
        // initial snapshots, and if they differ from its original snapshot,
        // then we revisit the loop.
        if (BeginBlock<true>(loop_header)) {
          TRACE(">> Will need to revisit loop");
          // We set the snapshot of the loop's 1st predecessor to the newly
          // computed snapshot. It's not quite correct, but this predecessor
          // is guaranteed to end with a Goto, and we are now visiting the
          // loop, which means that we don't really care about this
          // predecessor anymore.
          // The reason for saving this snapshot is to prevent infinite
          // looping, since the next time we reach this point, the backedge
          // snapshot could still invalidate things from the forward edge
          // snapshot. By restricting the forward edge snapshot, we prevent
          // this.
          const Block* loop_1st_pred =
              loop_header->LastPredecessor()->NeighboringPredecessor();
          FinishBlock(loop_1st_pred);
          // And we start a new fresh snapshot from this predecessor.
          auto pred_snapshots =
              block_to_snapshot_mapping_[loop_1st_pred->index()];
          non_aliasing_objects_.StartNewSnapshot(
              pred_snapshots->alias_snapshot);
          object_maps_.StartNewSnapshot(pred_snapshots->maps_snapshot);
          memory_.StartNewSnapshot(pred_snapshots->memory_snapshot);
          iterator.MarkLoopForRevisit();
          compute_start_snapshot = false;
        } else {
          TRACE(">> No need to revisit loop");
          SealAndDiscard();
        }
      }
    }
  }
  FixedOpIndexSidetable<SaturatedUint8> total_use_counts(graph_.op_id_count(),
                                                         phase_zone_, &graph_);
  // Incorpoare load elimination decisions into int32-truncation data.
  for (auto it = int32_truncated_loads_.begin();
       it != int32_truncated_loads_.end();) {
    OpIndex load_idx = it->first;
    auto& truncations = it->second;
    Replacement replacement = GetReplacement(load_idx);
    // We distinguish a few different cases.
    if (!replacement.IsLoadElimination()) {
      // Case 1: This load is not going to be eliminated.
      total_use_counts[load_idx] += graph_.Get(load_idx).saturated_use_count;
      // Check if all uses we know so far, are all truncating uses.
      if (total_use_counts[load_idx].IsSaturated() ||
          total_use_counts[load_idx].Get() > truncations.size()) {
        // We do know that we cannot int32-truncate this load, so eliminate
        // it from the candidates.
        int32_truncated_loads_.erase(it++);
        continue;
      }
      // Otherwise, keep this candidate.
      ++it;
      continue;
    } else {
      OpIndex replaced_by_idx = replacement.replacement();
      const Operation& replaced_by = graph_.Get(replaced_by_idx);
      if (!replaced_by.Is<LoadOp>()) {
        // Case 2: This load is replaced by a non-load (e.g. by the value
        // stored that the load would read). This load cannot be truncated
        // (because we are not going to have a load anymore), so eliminate it
        // from the candidates.
        int32_truncated_loads_.erase(it++);
        continue;
      } else {
        // Case 3: This load is replaced by another load, so the truncating
        // and the total uses have to be merged into the replacing use.
        auto it2 = int32_truncated_loads_.find(replaced_by_idx);
        if (it2 == int32_truncated_loads_.end()) {
          // Case 3a: The replacing load is not tracked, so we assume it has
          // non-truncating uses, so we can also ignore this load.
          int32_truncated_loads_.erase(it++);
          continue;
        } else {
          // Case 3b: The replacing load might have be a candidate for int32
          // truncation, we merge the information into that load.
          total_use_counts[replaced_by_idx] +=
              graph_.Get(load_idx).saturated_use_count;
          it2->second.insert(truncations.begin(), truncations.end());
          int32_truncated_loads_.erase(it++);
          continue;
        }
      }
    }
  }
  // We have prepared everything and now extract the necessary replacement
  // information.
  for (const auto& [load_idx, int32_truncations] : int32_truncated_loads_) {
    if (int32_truncations.empty()) continue;
    if (!total_use_counts[load_idx].IsSaturated() &&
        total_use_counts[load_idx].Get() == int32_truncations.size()) {
      // All uses of this load are int32-truncating loads, so we replace them.
      DCHECK(GetReplacement(load_idx).IsNone() ||
             GetReplacement(load_idx).IsTaggedLoadToInt32Load());
      for (const auto [change_idx, bitcast_idx] : int32_truncations) {
        replacements_[change_idx] =
            Replacement::Int32TruncationElimination(load_idx);
        replacements_[bitcast_idx] = Replacement::TaggedBitcastElimination();
        replacements_[load_idx] = Replacement::TaggedLoadToInt32Load();
      }
    }
  }
}
References block_to_snapshot_mapping_, v8::internal::DCHECK(), FinishBlock(), v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::Graph::Get(), GetReplacement(), graph_, v8::internal::compiler::turboshaft::Block::index(), int32_truncated_loads_, v8::internal::compiler::turboshaft::LoadEliminationReplacement::Int32TruncationElimination(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::LoadEliminationReplacement::IsLoadElimination(), v8::internal::IsNone(), v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), memory_, v8::internal::compiler::turboshaft::Block::NeighboringPredecessor(), non_aliasing_objects_, object_maps_, v8::internal::compiler::turboshaft::Graph::op_id_count(), phase_zone_, ProcessBlock(), v8::internal::compiler::turboshaft::LoadEliminationReplacement::replacement(), replacements_, v8::internal::compiler::turboshaft::Operation::saturated_use_count, SealAndDiscard(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot(), v8::internal::compiler::turboshaft::LoadEliminationReplacement::TaggedBitcastElimination(), v8::internal::compiler::turboshaft::LoadEliminationReplacement::TaggedLoadToInt32Load(), v8::internal::TRACE(), and v8::internal::compiler::turboshaft::Operation::TryCast().
SealAndDiscard()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::SealAndDiscard () [private]
Definition at line 634 of file late-load-elimination-reducer.cc.
                                                 {
  non_aliasing_objects_.Seal();
  object_maps_.Seal();
  memory_.Seal();
}
References memory_, non_aliasing_objects_, object_maps_, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal().
Referenced by Run().
StoreLoopSnapshotInForwardPredecessor()
void v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::StoreLoopSnapshotInForwardPredecessor (const Block & loop_header) [private]
Definition at line 640 of file late-load-elimination-reducer.cc.
                              {
  auto non_aliasing_snapshot = non_aliasing_objects_.Seal();
  auto object_maps_snapshot = object_maps_.Seal();
  auto memory_snapshot = memory_.Seal();
  block_to_snapshot_mapping_
      [loop_header.LastPredecessor()->NeighboringPredecessor()->index()] =
          Snapshot{non_aliasing_snapshot, object_maps_snapshot,
                   memory_snapshot};
  non_aliasing_objects_.StartNewSnapshot(non_aliasing_snapshot);
  object_maps_.StartNewSnapshot(object_maps_snapshot);
  memory_.StartNewSnapshot(memory_snapshot);
}
References block_to_snapshot_mapping_, v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), memory_, v8::internal::compiler::turboshaft::Block::NeighboringPredecessor(), non_aliasing_objects_, object_maps_, v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Seal(), v8::internal::compiler::turboshaft::ChangeTrackingSnapshotTable< Derived, Value, KeyData >::StartNewSnapshot(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::StartNewSnapshot().
Referenced by ProcessBlock().
Member Data Documentation
block_to_snapshot_mapping_
FixedBlockSidetable<std::optional<Snapshot> > v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::block_to_snapshot_mapping_ [private]
Definition at line 772 of file late-load-elimination-reducer.h.
Referenced by BackedgeHasSnapshot(), BeginBlock(), FinishBlock(), Run(), and StoreLoopSnapshotInForwardPredecessor().
broker_
JSHeapBroker* v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::broker_ [private]
Definition at line 747 of file late-load-elimination-reducer.h.
Referenced by ProcessCall().
data_
PipelineData* v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::data_ [private]
Definition at line 744 of file late-load-elimination-reducer.h.
graph_
Graph& v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::graph_ [private]
Definition at line 745 of file late-load-elimination-reducer.h.
Referenced by DcheckWordBinop(), InvalidateIfAlias(), ProcessBlock(), ProcessCall(), ProcessChange(), ProcessLoad(), and Run().
int32_truncated_loads_
std::map<OpIndex, base::SmallMap<std::map<OpIndex, OpIndex>, 4> > v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::int32_truncated_loads_ [private]
Definition at line 753 of file late-load-elimination-reducer.h.
Referenced by ProcessChange(), ProcessLoad(), and Run().
memory_
MemoryContentTable v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::memory_ [private]
Definition at line 765 of file late-load-elimination-reducer.h.
Referenced by BeginBlock(), FinishBlock(), ProcessAtomicRMW(), ProcessCall(), ProcessLoad(), ProcessStore(), Run(), SealAndDiscard(), and StoreLoopSnapshotInForwardPredecessor().
non_aliasing_objects_
AliasTable v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::non_aliasing_objects_ [private]
Definition at line 763 of file late-load-elimination-reducer.h.
Referenced by BeginBlock(), DcheckWordBinop(), FinishBlock(), InvalidateIfAlias(), ProcessAllocate(), ProcessCall(), ProcessStore(), Run(), SealAndDiscard(), and StoreLoopSnapshotInForwardPredecessor().
object_maps_
MapTable v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::object_maps_ [private]
Definition at line 764 of file late-load-elimination-reducer.h.
Referenced by BeginBlock(), FinishBlock(), ProcessAssumeMap(), ProcessStore(), Run(), SealAndDiscard(), and StoreLoopSnapshotInForwardPredecessor().
phase_zone_
Zone* v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::phase_zone_ [private]
Definition at line 746 of file late-load-elimination-reducer.h.
Referenced by Run().
predecessor_alias_snapshots_
ZoneVector<AliasSnapshot> v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::predecessor_alias_snapshots_ [private]
Definition at line 777 of file late-load-elimination-reducer.h.
Referenced by BeginBlock().
predecessor_maps_snapshots_
ZoneVector<MapSnapshot> v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::predecessor_maps_snapshots_ [private]
Definition at line 778 of file late-load-elimination-reducer.h.
Referenced by BeginBlock().
predecessor_memory_snapshots_
ZoneVector<MemorySnapshot> v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::predecessor_memory_snapshots_ [private]
Definition at line 779 of file late-load-elimination-reducer.h.
Referenced by BeginBlock().
raw_base_assumption_
RawBaseAssumption v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::raw_base_assumption_ [private]
Definition at line 748 of file late-load-elimination-reducer.h.
Referenced by ProcessStore().
replacements_
FixedOpIndexSidetable<Replacement> v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::replacements_ [private]
Definition at line 750 of file late-load-elimination-reducer.h.
Referenced by ProcessLoad(), and Run().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/late-load-elimination-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/late-load-elimination-reducer.cc