v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache Class Reference
Public Member Functions
InstanceCache (Assembler &assembler)
void Initialize (V< WasmTrustedInstanceData > trusted_instance_data, const WasmModule *mod)
void ReloadCachedMemory ()
V< WasmTrustedInstanceData > trusted_instance_data ()
V< FixedArray > managed_object_maps ()
V< NativeContext > native_context ()
V< WordPtr > memory0_start ()
V< WordPtr > memory0_size ()
Private Member Functions
V< WordPtr > LoadMemStart ()
V< WordPtr > LoadMemSize ()
bool memory_can_move ()
Assembler & Asm ()
Private Attributes
V< WasmTrustedInstanceData > trusted_data_
V< FixedArray > managed_object_maps_
V< NativeContext > native_context_
ScopedVar< WordPtr > mem_start_
ScopedVar< WordPtr > mem_size_
Assembler & asm_
bool memory_is_shared_ {false}
bool memory_can_grow_ {false}
bool memory_can_move_ {false}
bool memory_size_cached_ {false}
Static Private Attributes
static constexpr uint8_t kUnused = ~uint8_t{0}
Detailed Description
Definition at line 6072 of file turboshaft-graph-interface.cc.
Constructor & Destructor Documentation
InstanceCache()
v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::InstanceCache (Assembler & assembler) [inline], [explicit]
Definition at line 6074 of file turboshaft-graph-interface.cc.
        : mem_start_(assembler), mem_size_(assembler), asm_(assembler) {}
Member Function Documentation
Asm()
Assembler& v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::Asm () [inline], [private]
Definition at line 6166 of file turboshaft-graph-interface.cc.
{ return asm_; }
References v8::internal::wasm::WasmGraphBuilderBase::asm_.
Initialize()
void v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::Initialize (V< WasmTrustedInstanceData > trusted_instance_data, const WasmModule * mod) [inline]
Definition at line 6077 of file turboshaft-graph-interface.cc.
                                           {
      DCHECK(!trusted_data_.valid()); // Only call {Initialize()} once.
      trusted_data_ = trusted_instance_data;
      managed_object_maps_ =
          __ Load(trusted_instance_data, LoadOp::Kind::TaggedBase().Immutable(),
                  MemoryRepresentation::TaggedPointer(),
                  WasmTrustedInstanceData::kManagedObjectMapsOffset);
      native_context_ =
          __ Load(trusted_instance_data, LoadOp::Kind::TaggedBase().Immutable(),
                  MemoryRepresentation::TaggedPointer(),
                  WasmTrustedInstanceData::kNativeContextOffset);
      if (!mod->memories.empty()) {
#if DEBUG
        has_memory_ = true;
#endif
        const WasmMemory& mem = mod->memories[0];
        memory_can_grow_ = mem.initial_pages != mem.maximum_pages;
        // For now, we don't cache the size of shared growable memories.
        // If we wanted to support this case, we would have to reload the
        // memory size when loop stack checks detect an interrupt request.
        // Since memory size caching is particularly important for asm.js,
        // which never uses growable or shared memories, this limitation is
        // considered acceptable for now.
        memory_size_cached_ = !mem.is_shared || !memory_can_grow_;
        // Trap handler enabled memories never move.
        // Memories that can't grow have no reason to move.
        // Shared memories can only be grown in-place.
        memory_can_move_ = mem.bounds_checks != kTrapHandler &&
                           memory_can_grow_ && !mem.is_shared;
        memory_is_shared_ = mem.is_shared;
        if (memory_size_cached_) {
          mem_size_ = LoadMemSize();
        }
        mem_start_ = LoadMemStart();
      }
    }
References __, v8::internal::wasm::WasmMemory::bounds_checks, v8::internal::DCHECK(), v8::internal::wasm::WasmMemory::initial_pages, v8::internal::wasm::WasmMemory::is_shared, v8::internal::wasm::kTrapHandler, v8::Load(), v8::internal::wasm::WasmMemory::maximum_pages, v8::internal::wasm::WasmModule::memories, v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), v8::internal::compiler::turboshaft::MemoryRepresentation::TaggedPointer(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::trusted_instance_data().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::StartFunction().
LoadMemSize()
V<WordPtr> v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::LoadMemSize () [inline], [private]
Definition at line 6150 of file turboshaft-graph-interface.cc.
                             {
      DCHECK(has_memory_);
      LoadOp::Kind kind = LoadOp::Kind::TaggedBase();
      if (memory_is_shared_ && memory_can_grow_) {
        // Memory size loads should not be load-eliminated as the memory size
        // can be modified by another thread.
        kind = kind.NotLoadEliminable();
      }
      if (!memory_can_grow_) kind = kind.Immutable();
      return __ Load(trusted_data_, kind, MemoryRepresentation::UintPtr(),
                     WasmTrustedInstanceData::kMemory0SizeOffset);
    }
References __, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::LoadOp::Kind::Immutable(), v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::NotLoadEliminable(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
LoadMemStart()
V<WordPtr> v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::LoadMemStart () [inline], [private]
Definition at line 6139 of file turboshaft-graph-interface.cc.
                              {
      DCHECK(has_memory_);
      // In contrast to memory size loads, we can mark memory start loads as
      // eliminable: shared memories never move, and non-shared memories can't
      // have their start modified by other threads.
      LoadOp::Kind kind = LoadOp::Kind::TaggedBase();
      if (!memory_can_move()) kind = kind.Immutable();
      return __ Load(trusted_data_, kind, MemoryRepresentation::UintPtr(),
                     WasmTrustedInstanceData::kMemory0StartOffset);
    }
References __, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::LoadOp::Kind::Immutable(), v8::Load(), v8::internal::compiler::turboshaft::LoadOp::Kind::TaggedBase(), and v8::internal::compiler::turboshaft::MemoryRepresentation::UintPtr().
managed_object_maps()
V<FixedArray> v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::managed_object_maps () [inline]
Definition at line 6124 of file turboshaft-graph-interface.cc.
{ return managed_object_maps_; }
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::managed_object_maps().
memory0_size()
V<WordPtr> v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::memory0_size () [inline]
Definition at line 6130 of file turboshaft-graph-interface.cc.
                              {
      DCHECK(has_memory_);
      if (!memory_size_cached_) return LoadMemSize();
      return mem_size_;
    }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::MemSize().
memory0_start()
V<WordPtr> v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::memory0_start () [inline]
Definition at line 6126 of file turboshaft-graph-interface.cc.
                               {
      DCHECK(has_memory_);
      return mem_start_;
    }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::MemStart().
memory_can_move()
bool v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::memory_can_move () [inline], [private]
Definition at line 6163 of file turboshaft-graph-interface.cc.
{ return memory_can_move_; }
native_context()
V<NativeContext> v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::native_context () [inline]
Definition at line 6125 of file turboshaft-graph-interface.cc.
{ return native_context_; }
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchCase(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CatchException(), v8::internal::wasm::TurboshaftGraphBuildingInterface::HandleWellKnownImport(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringConcat(), v8::internal::wasm::TurboshaftGraphBuildingInterface::UnpackWasmException(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::WellKnown_FastApi().
ReloadCachedMemory()
void v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::ReloadCachedMemory () [inline]
Definition at line 6118 of file turboshaft-graph-interface.cc.
                              {
      if (memory_can_move()) mem_start_ = LoadMemStart();
      if (memory_can_grow_ && memory_size_cached_) mem_size_ = LoadMemSize();
    }
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildWasmCall(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CallAndMaybeCatchException(), v8::internal::wasm::TurboshaftGraphBuildingInterface::InlineWasmCall(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::MemoryGrow().
trusted_instance_data()
V<WasmTrustedInstanceData> v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::trusted_instance_data () [inline]
Definition at line 6123 of file turboshaft-graph-interface.cc.
{ return trusted_data_; }
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::trusted_instance_data().
Member Data Documentation
asm_
Assembler& v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::asm_ [private]
Definition at line 6178 of file turboshaft-graph-interface.cc.
kUnused
constexpr uint8_t v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::kUnused = ~uint8_t{0} [static], [constexpr], [private]
Definition at line 6137 of file turboshaft-graph-interface.cc.
managed_object_maps_
V<FixedArray> v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::managed_object_maps_ [private]
Definition at line 6170 of file turboshaft-graph-interface.cc.
mem_size_
ScopedVar<WordPtr> v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::mem_size_ [private]
Definition at line 6175 of file turboshaft-graph-interface.cc.
mem_start_
ScopedVar<WordPtr> v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::mem_start_ [private]
Definition at line 6174 of file turboshaft-graph-interface.cc.
memory_can_grow_
bool v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::memory_can_grow_ {false} [private]
Definition at line 6180 of file turboshaft-graph-interface.cc.
memory_can_move_
bool v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::memory_can_move_ {false} [private]
Definition at line 6181 of file turboshaft-graph-interface.cc.
memory_is_shared_
bool v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::memory_is_shared_ {false} [private]
Definition at line 6179 of file turboshaft-graph-interface.cc.
memory_size_cached_
bool v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::memory_size_cached_ {false} [private]
Definition at line 6182 of file turboshaft-graph-interface.cc.
native_context_
V<NativeContext> v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::native_context_ [private]
Definition at line 6171 of file turboshaft-graph-interface.cc.
trusted_data_
V<WasmTrustedInstanceData> v8::internal::wasm::TurboshaftGraphBuildingInterface::InstanceCache::trusted_data_ [private]
Definition at line 6169 of file turboshaft-graph-interface.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/turboshaft-graph-interface.cc