v8::internal::MinorGCHeapGrowing Class Reference
Public Member Functions
MinorGCHeapGrowing (cppgc::internal::StatsCollector &stats_collector)
virtual ~MinorGCHeapGrowing ()=default
void AllocatedObjectSizeIncreased (size_t) final
void AllocatedObjectSizeDecreased (size_t) final
void ResetAllocatedObjectSize (size_t allocated_object_size) final
bool LimitReached () const
Private Member Functions
void ConfigureLimit (size_t allocated_object_size)
Private Attributes
cppgc::internal::StatsCollector & stats_collector_
size_t initial_heap_size_ = 1 * cppgc::internal::kMB
size_t limit_for_atomic_gc_ = 0
Detailed Description
Definition at line 61 of file cpp-heap.cc.
Constructor & Destructor Documentation
MinorGCHeapGrowing()
v8::internal::MinorGCHeapGrowing::MinorGCHeapGrowing (cppgc::internal::StatsCollector & stats_collector) [inline], [explicit]
Definition at line 64 of file cpp-heap.cc.
      : stats_collector_(stats_collector) {
    stats_collector.RegisterObserver(this);
  }
References cppgc::internal::StatsCollector::RegisterObserver().
 MinorGCHeapGrowing()
virtual v8::internal::MinorGCHeapGrowing::~MinorGCHeapGrowing () [virtual], [default]
Member Function Documentation
AllocatedObjectSizeDecreased()
void v8::internal::MinorGCHeapGrowing::AllocatedObjectSizeDecreased (size_t) [inline], [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 71 of file cpp-heap.cc.
{}
AllocatedObjectSizeIncreased()
void v8::internal::MinorGCHeapGrowing::AllocatedObjectSizeIncreased (size_t) [inline], [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 70 of file cpp-heap.cc.
{}
ConfigureLimit()
void v8::internal::MinorGCHeapGrowing::ConfigureLimit (size_t allocated_object_size) [inline], [private]
Definition at line 81 of file cpp-heap.cc.
                                                    {
    // Constant growing factor for growing the heap limit.
    static constexpr double kGrowingFactor = 1.5;
    // For smaller heaps, allow allocating at least LAB in each regular space
    // before triggering GC again.
    static constexpr size_t kMinLimitIncrease =
        cppgc::internal::kPageSize *
        cppgc::internal::RawHeap::kNumberOfRegularSpaces;
    const size_t size = std::max(allocated_object_size, initial_heap_size_);
    limit_for_atomic_gc_ = std::max(static_cast<size_t>(size * kGrowingFactor),
                                    size + kMinLimitIncrease);
  }
References initial_heap_size_, cppgc::internal::RawHeap::kNumberOfRegularSpaces, cppgc::internal::kPageSize, limit_for_atomic_gc_, and size().
Referenced by ResetAllocatedObjectSize().
LimitReached()
bool v8::internal::MinorGCHeapGrowing::LimitReached () const [inline]
Definition at line 76 of file cpp-heap.cc.
                            {
    return stats_collector_.allocated_object_size() >= limit_for_atomic_gc_;
  }
References cppgc::internal::StatsCollector::allocated_object_size(), limit_for_atomic_gc_, and stats_collector_.
ResetAllocatedObjectSize()
void v8::internal::MinorGCHeapGrowing::ResetAllocatedObjectSize (size_t allocated_object_size) [inline], [final], [virtual]
Reimplemented from cppgc::internal::StatsCollector::AllocationObserver.
Definition at line 72 of file cpp-heap.cc.
                                                                    {
    ConfigureLimit(allocated_object_size);
  }
References ConfigureLimit().
Member Data Documentation
initial_heap_size_
size_t v8::internal::MinorGCHeapGrowing::initial_heap_size_ = 1 * cppgc::internal::kMB [private]
Definition at line 96 of file cpp-heap.cc.
Referenced by ConfigureLimit().
limit_for_atomic_gc_
size_t v8::internal::MinorGCHeapGrowing::limit_for_atomic_gc_ = 0 [private]
Definition at line 97 of file cpp-heap.cc.
Referenced by ConfigureLimit(), and LimitReached().
stats_collector_
cppgc::internal::StatsCollector& v8::internal::MinorGCHeapGrowing::stats_collector_ [private]
Definition at line 95 of file cpp-heap.cc.
Referenced by LimitReached().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc-js/cpp-heap.cc