v8::internal::torque::MessageBuilder Class Reference
#include <utils.h>
Public Member Functions
MessageBuilder ()=delete
MessageBuilder (const std::string &message, TorqueMessage::Kind kind)
MessageBuilder & Position (SourcePosition position)
void Throw () const
~MessageBuilder ()
Private Member Functions
void Report () const
Private Attributes
TorqueMessage message_
std::vector< TorqueMessage > extra_messages_
Detailed Description
Definition at line 47 of file utils.h.
Constructor & Destructor Documentation
MessageBuilder() [1/2]
v8::internal::torque::MessageBuilder::MessageBuilder () [delete]
MessageBuilder() [2/2]
v8::internal::torque::MessageBuilder::MessageBuilder (const std::string & message, TorqueMessage::Kind kind)
Definition at line 125 of file utils.cc.
                                                       {
  std::optional<SourcePosition> position;
  if (CurrentSourcePosition::HasScope()) {
    position = CurrentSourcePosition::Get();
  }
  message_ = TorqueMessage{message, position, kind};
  if (CurrentScope::HasScope()) {
    // Traverse the parent scopes to find one that was created to represent a
    // specialization of something generic. If we find one, then log it and
    // continue walking the scope tree of the code that requested that
    // specialization. This allows us to collect the stack of locations that
    // caused a specialization.
    Scope* scope = CurrentScope::Get();
    while (scope) {
      SpecializationRequester requester = scope->GetSpecializationRequester();
      if (!requester.IsNone()) {
        extra_messages_.push_back(
            {"Note: in specialization " + requester.name + " requested here",
             requester.position, kind});
        scope = requester.scope;
      } else {
        scope = scope->ParentScope();
      }
    }
  }
}
References extra_messages_, v8::internal::compiler::turboshaft::Get(), v8::internal::torque::Scope::GetSpecializationRequester(), v8::internal::torque::SpecializationRequester::IsNone(), message_, v8::internal::torque::SpecializationRequester::name, v8::internal::torque::Declarable::ParentScope(), v8::internal::torque::SpecializationRequester::position, and v8::internal::torque::SpecializationRequester::scope.
 MessageBuilder()
v8::internal::torque::MessageBuilder::~MessageBuilder () [inline]
Definition at line 59 of file utils.h.
                    {
    // This will also get called in case the error is thrown.
    Report();
  }
References v8::internal::anonymous_namespace{asm-js.cc}::Report().
Member Function Documentation
Position()
MessageBuilder& v8::internal::torque::MessageBuilder::Position (SourcePosition position) [inline]
Definition at line 52 of file utils.h.
                                                    {
    message_.position = position;
    return *this;
  }
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::AnnotationSet(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::BuildInstanceTypeTree(), v8::internal::torque::ImplementationVisitor::CheckInitializersWellformed(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::DeclarationVisitor::CreateBuiltin(), v8::internal::torque::Field::GetFieldSizeInformation(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::GetIntParam(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::GetSectionFor(), v8::internal::torque::anonymous_namespace{class-debug-reader-generator.cc}::DebugFieldType::GetSize(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::GetStringParam(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GetTypeNameForAccessor(), v8::internal::torque::MacroDeclaration::MacroDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTryLabelExpression(), v8::internal::torque::TypeArgumentInference::MatchGeneric(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::NamingConventionError(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::PropagateInstanceTypeConstraints(), v8::internal::torque::ReportAllUnusedMacros(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::SelectOwnValues(), v8::internal::torque::anonymous_namespace{instance-type-generator.cc}::SolveInstanceTypeConstraints(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::FieldOffsetsGenerator::UpdateSection(), v8::internal::torque::Field::ValidateAlignment(), v8::internal::torque::ImplementationVisitor::Visit(), v8::internal::torque::TypeVisitor::VisitClassFieldsAndMethods(), and v8::internal::torque::Binding< T >::~Binding().
Report()
void v8::internal::torque::MessageBuilder::Report () const [private]
Definition at line 153 of file utils.cc.
                                  {
  TorqueMessages::Get().push_back(message_);
  for (const auto& message : extra_messages_) {
    TorqueMessages::Get().push_back(message);
  }
}
References extra_messages_, v8::internal::compiler::turboshaft::Get(), and message_.
Throw()
void v8::internal::torque::MessageBuilder::Throw () const
Definition at line 160 of file utils.cc.
                                              {
  throw TorqueAbortCompilation{};
}
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::AddConstexpr(), v8::internal::torque::GenericDeclarable< SpecializationType, DeclarationType >::AddSpecialization(), v8::internal::torque::ImplementationVisitor::CheckInitializersWellformed(), v8::internal::torque::ClassType::ComputeArraySlotKind(), v8::internal::torque::TypeVisitor::ComputeType(), v8::internal::torque::ImplementationVisitor::GenerateAssignToLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldAccess(), v8::internal::torque::Field::GetFieldSizeInformation(), v8::internal::torque::LocalValue::GetLocationReference(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), v8::internal::torque::anonymous_namespace{implementation-visitor.cc}::CppClassGenerator::GetTypeNameForAccessor(), v8::internal::torque::TypeArgumentInference::MatchGeneric(), v8::internal::torque::SourceFileMap::PathFromV8RootWithoutExtension(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::ProcessTorqueImportDeclaration(), v8::internal::torque::anonymous_namespace{torque-compiler.cc}::ReadAndParseTorqueFile(), v8::internal::torque::ReportError(), v8::internal::torque::ImplementationVisitor::Visit(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::YieldIntegerLiteral().
Member Data Documentation
extra_messages_
std::vector<TorqueMessage> v8::internal::torque::MessageBuilder::extra_messages_ [private]
Definition at line 68 of file utils.h.
Referenced by MessageBuilder(), and Report().
message_
TorqueMessage v8::internal::torque::MessageBuilder::message_ [private]
Definition at line 67 of file utils.h.
Referenced by MessageBuilder(), and Report().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/utils.h
/mnt/V8SourceCode/src/torque/utils.cc