v8::internal::maglev::Node Class Reference
#include <maglev-ir.h>
Public Member Functions
ValueLocation & result ()
Static Public Member Functions
static constexpr bool participate_in_cse (Opcode op)
static constexpr bool needs_epoch_check (Opcode op)
Protected Member Functions
NodeBase (uint64_t bitfield)
Additional Inherited Members
Detailed Description
Definition at line 2587 of file maglev-ir.h.
Member Function Documentation
needs_epoch_check()
static constexpr bool v8::internal::maglev::Node::needs_epoch_check (Opcode op) [inline], [static], [constexpr]
Definition at line 2599 of file maglev-ir.h.
                                                     {
    return StaticPropertiesForOpcode(op).can_read();
  }
References v8::internal::maglev::OpProperties::can_read(), and v8::internal::maglev::StaticPropertiesForOpcode().
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddNewNodeOrGetEquivalent().
NodeBase()
v8::internal::maglev::NodeBase::NodeBase [inline], [explicit], [protected]
Definition at line 2334 of file maglev-ir.h.
: bitfield_(bitfield) {}
participate_in_cse()
static constexpr bool v8::internal::maglev::Node::participate_in_cse (Opcode op) [inline], [static], [constexpr]
Definition at line 2591 of file maglev-ir.h.
                                                      {
    return StaticPropertiesForOpcode(op).can_participate_in_cse() &&
           !IsConstantNode(op) && !IsControlNode(op) && !IsZeroCostNode(op) &&
           // The following are already precisely tracked by known_node_aspects
           // and tracking them with CSE would just waste time.
           op != Opcode::kCheckMaps;
  }
References v8::internal::maglev::OpProperties::can_participate_in_cse(), v8::internal::maglev::IsConstantNode(), v8::internal::maglev::IsControlNode(), v8::internal::maglev::IsZeroCostNode(), and v8::internal::maglev::StaticPropertiesForOpcode().
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddNewNode(), and v8::internal::maglev::MaglevGraphBuilder::AddNewNodeOrGetEquivalent().
result()
ValueLocation & v8::internal::maglev::Node::result () [inline]
Definition at line 2934 of file maglev-ir.h.
                            {
  DCHECK(Is<ValueNode>());
  return Cast<ValueNode>()->result();
}
References v8::internal::DCHECK().
Referenced by v8::internal::maglev::DefineAsConstant(), v8::internal::maglev::DefineAsFixed(), v8::internal::maglev::DefineAsRegister(), and v8::internal::maglev::DefineSameAsFirst().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h