v8::internal::TracedNodeBlock::NodeIteratorImpl Class Reference
Public Member Functions
NodeIteratorImpl (TracedNodeBlock *block)
NodeIteratorImpl (TracedNodeBlock *block, TracedNode::IndexType current_index)
NodeIteratorImpl (const NodeIteratorImpl &other) V8_NOEXCEPT
TracedNode * operator* ()
bool operator== (const NodeIteratorImpl &rhs) const
bool operator!= (const NodeIteratorImpl &rhs) const
NodeIteratorImpl & operator++ ()
NodeIteratorImpl operator++ (int)
Private Attributes
TracedNodeBlock * block_
TracedNode::IndexType current_index_ = 0
Additional Inherited Members
Detailed Description
Definition at line 114 of file traced-handles.h.
Constructor & Destructor Documentation
NodeIteratorImpl() [1/3]
v8::internal::TracedNodeBlock::NodeIteratorImpl::NodeIteratorImpl (TracedNodeBlock * block) [inline], [explicit]
Definition at line 117 of file traced-handles.h.
: block_(block) {}
NodeIteratorImpl() [2/3]
v8::internal::TracedNodeBlock::NodeIteratorImpl::NodeIteratorImpl (TracedNodeBlock * block, TracedNode::IndexType current_index) [inline]
Definition at line 118 of file traced-handles.h.
        : block_(block), current_index_(current_index) {}
NodeIteratorImpl() [3/3]
v8::internal::TracedNodeBlock::NodeIteratorImpl::NodeIteratorImpl (const NodeIteratorImpl & other) [inline]
Definition at line 121 of file traced-handles.h.
        : block_(other.block_),
          current_index_(other.current_index_) {}
Member Function Documentation
operator!=()
bool v8::internal::TracedNodeBlock::NodeIteratorImpl::operator!= (const NodeIteratorImpl & rhs) const [inline]
Definition at line 129 of file traced-handles.h.
                                                       {
      return !(*this == rhs);
    }
operator*()
TracedNode* v8::internal::TracedNodeBlock::NodeIteratorImpl::operator* () [inline]
Definition at line 125 of file traced-handles.h.
{ return block_->at(current_index_); }
References v8::internal::TracedNodeBlock::at(), block_, and current_index_.
operator++() [1/2]
NodeIteratorImpl& v8::internal::TracedNodeBlock::NodeIteratorImpl::operator++ () [inline]
Definition at line 132 of file traced-handles.h.
                                          {
      current_index_++;
      return *this;
    }
References current_index_.
Referenced by operator++().
operator++() [2/2]
NodeIteratorImpl v8::internal::TracedNodeBlock::NodeIteratorImpl::operator++ (int) [inline]
Definition at line 136 of file traced-handles.h.
                                            {
      NodeIteratorImpl tmp(*this);
      operator++();
      return tmp;
    }
References operator++().
operator==()
bool v8::internal::TracedNodeBlock::NodeIteratorImpl::operator== (const NodeIteratorImpl & rhs) const [inline]
Definition at line 126 of file traced-handles.h.
                                                       {
      return rhs.block_ == block_ && rhs.current_index_ == current_index_;
    }
References block_, and current_index_.
Member Data Documentation
block_
TracedNodeBlock* v8::internal::TracedNodeBlock::NodeIteratorImpl::block_ [private]
Definition at line 143 of file traced-handles.h.
Referenced by operator*(), and operator==().
current_index_
TracedNode::IndexType v8::internal::TracedNodeBlock::NodeIteratorImpl::current_index_ = 0 [private]
Definition at line 144 of file traced-handles.h.
Referenced by operator*(), operator++(), and operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/handles/traced-handles.h