v8::internal::VirtualMemory Class Reference
#include <allocation.h>
Public Member Functions
V8_EXPORT_PRIVATE VirtualMemory ()
VirtualMemory (const VirtualMemory &)=delete
VirtualMemory & operator= (const VirtualMemory &)=delete
V8_EXPORT_PRIVATE VirtualMemory (v8::PageAllocator *page_allocator, size_t size, PageAllocator::AllocationHint hint={}, size_t alignment=1, PageAllocator::Permission permissions=PageAllocator::kNoAccess)
VirtualMemory (v8::PageAllocator *page_allocator, Address address, size_t size)
V8_EXPORT_PRIVATE ~VirtualMemory ()
VirtualMemory (VirtualMemory &&other) V8_NOEXCEPT
VirtualMemory & operator= (VirtualMemory &&other) V8_NOEXCEPT
bool IsReserved () const
V8_EXPORT_PRIVATE void Reset ()
v8::PageAllocator * page_allocator ()
const base::AddressRegion & region () const
Address address () const
Address end () const
size_t size () const
V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT bool SetPermissions (Address address, size_t size, PageAllocator::Permission access)
V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT bool RecommitPages (Address address, size_t size, PageAllocator::Permission access)
V8_EXPORT_PRIVATE V8_WARN_UNUSED_RESULT bool Resize (Address address, size_t new_size, PageAllocator::Permission access)
V8_EXPORT_PRIVATE bool DiscardSystemPages (Address address, size_t size)
V8_EXPORT_PRIVATE size_t Release (Address free_start)
V8_EXPORT_PRIVATE void Free ()
bool InVM (Address address, size_t size) const
Private Attributes
v8::PageAllocator * page_allocator_ = nullptr
base::AddressRegion region_
Detailed Description
Definition at line 193 of file allocation.h.
Constructor & Destructor Documentation
VirtualMemory() [1/5]
v8::internal::VirtualMemory::VirtualMemory () [default]
VirtualMemory() [2/5]
v8::internal::VirtualMemory::VirtualMemory (const VirtualMemory &) [delete]
VirtualMemory() [3/5]
v8::internal::VirtualMemory::VirtualMemory (v8::PageAllocator * page_allocator, size_t size, PageAllocator::AllocationHint hint = {}, size_t alignment = 1, PageAllocator::Permission permissions = PageAllocator::kNoAccess)
Definition at line 213 of file allocation.cc.
    : page_allocator_(page_allocator) {
  DCHECK_NOT_NULL(page_allocator);
  DCHECK(IsAligned(size, page_allocator_->CommitPageSize()));
  const size_t page_size = page_allocator_->AllocatePageSize();
  alignment = RoundUp(alignment, page_size);
  Address address = reinterpret_cast<Address>(AllocatePages(
      page_allocator_, RoundUp(size, page_size), alignment, permissions, hint));
  if (address != kNullAddress) {
    DCHECK(IsAligned(address, alignment));
    region_ = base::AddressRegion(address, size);
  }
}
References address(), v8::internal::AllocatePages(), v8::PageAllocator::AllocatePageSize(), v8::PageAllocator::CommitPageSize(), v8::internal::DCHECK(), DCHECK_NOT_NULL, IsAligned(), v8::internal::kNullAddress, page_allocator(), page_allocator_, region_, RoundUp(), and size().
VirtualMemory() [4/5]
v8::internal::VirtualMemory::VirtualMemory (v8::PageAllocator * page_allocator, Address address, size_t size) [inline]
Definition at line 212 of file allocation.h.
      : page_allocator_(page_allocator), region_(address, size) {
    DCHECK_NOT_NULL(page_allocator);
    DCHECK(IsAligned(address, page_allocator->AllocatePageSize()));
    DCHECK(IsAligned(size, page_allocator->CommitPageSize()));
  }
References address(), v8::PageAllocator::AllocatePageSize(), v8::PageAllocator::CommitPageSize(), v8::internal::DCHECK(), DCHECK_NOT_NULL, IsAligned(), page_allocator(), and size().
 VirtualMemory()
v8::internal::VirtualMemory::~VirtualMemory ()
Definition at line 230 of file allocation.cc.
                              {
  if (IsReserved()) {
    Free();
  }
}
References Free(), and IsReserved().
VirtualMemory() [5/5]
v8::internal::VirtualMemory::VirtualMemory (VirtualMemory && other) [inline]
Definition at line 224 of file allocation.h.
{ *this = std::move(other); }
Member Function Documentation
address()
Address v8::internal::VirtualMemory::address () const [inline]
Definition at line 249 of file allocation.h.
                          {
    DCHECK(IsReserved());
    return region_.begin();
  }
References v8::base::AddressRegion::begin(), v8::internal::DCHECK(), IsReserved(), and region_.
Referenced by v8::internal::MemoryAllocator::AllocateAlignedMemory(), v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::AllocateSegment(), DiscardSystemPages(), v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::GetOrCreateMemoryForSegment(), v8::internal::VirtualMemoryCage::InitReservation(), InVM(), RecommitPages(), Resize(), SetPermissions(), v8::internal::wasm::WasmCodeManager::TryAllocate(), and VirtualMemory().
DiscardSystemPages()
bool v8::internal::VirtualMemory::DiscardSystemPages (Address address, size_t size)
Definition at line 269 of file allocation.cc.
                                                                   {
  CHECK(InVM(address, size));
  bool result = page_allocator_->DiscardSystemPages(
      reinterpret_cast<void*>(address), size);
  DCHECK(result);
  return result;
}
References address(), CHECK, v8::internal::DCHECK(), v8::PageAllocator::DiscardSystemPages(), InVM(), page_allocator_, v8::base::internal::result, and size().
Referenced by v8::internal::MemoryAllocator::PartialFreeMemory().
end()
Address v8::internal::VirtualMemory::end () const [inline]
Definition at line 254 of file allocation.h.
                      {
    DCHECK(IsReserved());
    return region_.end();
  }
References v8::internal::DCHECK(), v8::base::AddressRegion::end(), IsReserved(), and region_.
Referenced by v8::internal::MemoryAllocator::ResizeLargePage(), and v8::internal::wasm::WasmCodeManager::TryAllocate().
Free()
void v8::internal::VirtualMemory::Free ()
Definition at line 292 of file allocation.cc.
                         {
  DCHECK(IsReserved());
  // Notice: Order is important here. The VirtualMemory object might live
  // inside the allocated region.
  v8::PageAllocator* page_allocator = page_allocator_;
  base::AddressRegion region = region_;
  Reset();
  // FreePages expects size to be aligned to allocation granularity however
  // ReleasePages may leave size at only commit granularity. Align it here.
  FreePages(page_allocator, reinterpret_cast<void*>(region.begin()),
            RoundUp(region.size(), page_allocator->AllocatePageSize()));
}
References v8::PageAllocator::AllocatePageSize(), v8::base::AddressRegion::begin(), v8::internal::DCHECK(), v8::internal::FreePages(), IsReserved(), page_allocator(), page_allocator_, region(), region_, Reset(), RoundUp(), and v8::base::AddressRegion::size().
Referenced by v8::internal::VirtualMemoryCage::Free(), v8::internal::MemoryAllocator::FreeReadOnlyPage(), and ~VirtualMemory().
InVM()
bool v8::internal::VirtualMemory::InVM (Address address, size_t size) const [inline]
Definition at line 295 of file allocation.h.
                                                {
    return region_.contains(address, size);
  }
References address(), v8::base::AddressRegion::contains(), region_, and size().
Referenced by DiscardSystemPages(), RecommitPages(), Release(), and SetPermissions().
IsReserved()
bool v8::internal::VirtualMemory::IsReserved () const [inline]
Definition at line 236 of file allocation.h.
{ return region_.begin() != kNullAddress; }
References v8::base::AddressRegion::begin(), v8::internal::kNullAddress, and region_.
Referenced by address(), v8::internal::MemoryAllocator::AllocateAlignedMemory(), v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::AllocateSegment(), v8::internal::MemoryAllocator::DeleteMemoryChunk(), end(), Free(), v8::internal::MemoryAllocator::FreeReadOnlyPage(), v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::GetOrCreateMemoryForSegment(), v8::internal::wasm::WasmCodeAllocator::Init(), v8::internal::VirtualMemoryCage::InitReservation(), v8::internal::VirtualMemoryCage::IsReserved(), v8::internal::wasm::WasmImportWrapperCache::LazyInitialize(), v8::internal::wasm::WasmCodeManager::NewNativeModule(), operator=(), v8::internal::MemoryAllocator::PartialFreeMemory(), Release(), v8::internal::wasm::WasmCodeManager::TryAllocate(), v8::internal::MemoryAllocator::UnregisterMemoryChunk(), v8::internal::MemoryAllocator::UnregisterSharedMemoryChunk(), and ~VirtualMemory().
operator=() [1/2]
VirtualMemory& v8::internal::VirtualMemory::operator= (const VirtualMemory &) [delete]
operator=() [2/2]
VirtualMemory& v8::internal::VirtualMemory::operator= (VirtualMemory && other) [inline]
Definition at line 227 of file allocation.h.
                                                              {
    DCHECK(!IsReserved());
    page_allocator_ = other.page_allocator_;
    region_ = other.region_;
    other.Reset();
    return *this;
  }
References v8::internal::DCHECK(), IsReserved(), page_allocator_, and region_.
page_allocator()
v8::PageAllocator* v8::internal::VirtualMemory::page_allocator () [inline]
Definition at line 241 of file allocation.h.
{ return page_allocator_; }
References page_allocator_.
Referenced by Free(), and VirtualMemory().
RecommitPages()
bool v8::internal::VirtualMemory::RecommitPages (Address address, size_t size, PageAllocator::Permission access)
Definition at line 249 of file allocation.cc.
                                                                  {
  CHECK(InVM(address, size));
  bool result = page_allocator_->RecommitPages(reinterpret_cast<void*>(address),
                                               size, access);
  return result;
}
References address(), CHECK, InVM(), page_allocator_, v8::PageAllocator::RecommitPages(), v8::base::internal::result, and size().
Referenced by v8::internal::MemoryAllocator::SetPermissionsOnExecutableMemoryChunk().
region()
const base::AddressRegion& v8::internal::VirtualMemory::region () const [inline]
Definition at line 243 of file allocation.h.
{ return region_; }
References region_.
Referenced by v8::internal::wasm::WasmCodeAllocator::AllocateForCodeInRegion(), Free(), v8::internal::wasm::WasmCodeAllocator::Init(), v8::internal::wasm::WasmImportWrapperCache::LazyInitialize(), v8::internal::wasm::NativeModule::NativeModule(), v8::internal::wasm::WasmCodeManager::NewNativeModule(), and v8::internal::wasm::WasmCodeManager::TryAllocate().
Release()
size_t v8::internal::VirtualMemory::Release (Address free_start)
Definition at line 277 of file allocation.cc.
                                                {
  DCHECK(IsReserved());
  DCHECK(IsAligned(free_start, page_allocator_->CommitPageSize()));
  // Notice: Order is important here. The VirtualMemory object might live
  // inside the allocated region.
  const size_t old_size = region_.size();
  const size_t free_size = old_size - (free_start - region_.begin());
  CHECK(InVM(free_start, free_size));
  region_.set_size(old_size - free_size);
  ReleasePages(page_allocator_, reinterpret_cast<void*>(region_.begin()),
               old_size, region_.size());
  return free_size;
}
References v8::base::AddressRegion::begin(), CHECK, v8::PageAllocator::CommitPageSize(), v8::internal::DCHECK(), InVM(), IsAligned(), IsReserved(), page_allocator_, region_, v8::internal::ReleasePages(), v8::base::AddressRegion::set_size(), and v8::base::AddressRegion::size().
Referenced by v8::internal::MemoryAllocator::PartialFreeMemory().
Reset()
void v8::internal::VirtualMemory::Reset ()
Definition at line 236 of file allocation.cc.
                          {
  page_allocator_ = nullptr;
  region_ = base::AddressRegion();
}
References page_allocator_, and region_.
Referenced by v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::AllocateSegment(), Free(), and v8::internal::ReadOnlyPageMetadata::MakeHeaderRelocatable().
Resize()
bool v8::internal::VirtualMemory::Resize (Address address, size_t new_size, PageAllocator::Permission access)
Definition at line 257 of file allocation.cc.
                                                           {
  DCHECK(IsAligned(new_size, page_allocator_->CommitPageSize()));
  DCHECK_LE(region_.size(), new_size);
  if (!page_allocator_->ResizeAllocationAt(reinterpret_cast<void*>(address),
                                           region_.size(), new_size, access)) {
    return false;
  }
  region_.set_size(new_size);
  return true;
}
References address(), v8::PageAllocator::CommitPageSize(), v8::internal::DCHECK(), DCHECK_LE, IsAligned(), page_allocator_, region_, v8::PageAllocator::ResizeAllocationAt(), v8::base::AddressRegion::set_size(), and v8::base::AddressRegion::size().
Referenced by v8::internal::MemoryAllocator::ResizeLargePage().
SetPermissions()
bool v8::internal::VirtualMemory::SetPermissions (Address address, size_t size, PageAllocator::Permission access)
Definition at line 241 of file allocation.cc.
                                                                   {
  CHECK(InVM(address, size));
  bool result = page_allocator_->SetPermissions(
      reinterpret_cast<void*>(address), size, access);
  return result;
}
References address(), CHECK, InVM(), page_allocator_, v8::base::internal::result, v8::PageAllocator::SetPermissions(), and size().
Referenced by v8::internal::MemoryAllocator::PartialFreeMemory(), and v8::internal::MemoryAllocator::SetPermissionsOnExecutableMemoryChunk().
size()
size_t v8::internal::VirtualMemory::size () const [inline]
Definition at line 263 of file allocation.h.
{ return region_.size(); }
References region_, and v8::base::AddressRegion::size().
Referenced by v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::AllocateSegment(), v8::internal::MemoryAllocator::AllocateUninitializedChunkAt(), DiscardSystemPages(), v8::internal::VirtualMemoryCage::InitReservation(), InVM(), v8::internal::wasm::WasmCodeManager::NewNativeModule(), RecommitPages(), v8::internal::MemoryAllocator::ResizeLargePage(), v8::internal::anonymous_namespace{accounting-allocator.cc}::ManagedZones::ReturnSegment(), SetPermissions(), v8::internal::wasm::WasmCodeManager::TryAllocate(), v8::internal::MemoryAllocator::UnregisterMemoryChunk(), v8::internal::MemoryAllocator::UnregisterSharedMemoryChunk(), and VirtualMemory().
Member Data Documentation
page_allocator_
v8::PageAllocator* v8::internal::VirtualMemory::page_allocator_ = nullptr [private]
Definition at line 301 of file allocation.h.
Referenced by DiscardSystemPages(), Free(), operator=(), page_allocator(), RecommitPages(), Release(), Reset(), Resize(), SetPermissions(), and VirtualMemory().
region_
base::AddressRegion v8::internal::VirtualMemory::region_ [private]
Definition at line 302 of file allocation.h.
Referenced by address(), end(), Free(), InVM(), IsReserved(), operator=(), region(), Release(), Reset(), Resize(), size(), and VirtualMemory().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/utils/allocation.h
/mnt/V8SourceCode/src/utils/allocation.cc