v8::internal::PropertyDescriptor Class Reference
#include <property-descriptor.h>
Public Member Functions
PropertyDescriptor ()
DirectHandle< JSObject > ToObject (Isolate *isolate)
DirectHandle< PropertyDescriptorObject > ToPropertyDescriptorObject (Isolate *isolate)
bool is_empty () const
bool IsRegularAccessorProperty () const
bool IsRegularDataProperty () const
bool enumerable () const
void set_enumerable (bool enumerable)
bool has_enumerable () const
bool configurable () const
void set_configurable (bool configurable)
bool has_configurable () const
Handle< JSAny > value () const
void set_value (DirectHandle< JSAny > value)
bool has_value () const
bool writable () const
void set_writable (bool writable)
bool has_writable () const
Handle< UnionOf< JSAny, FunctionTemplateInfo > > get () const
void set_get (DirectHandle< UnionOf< JSAny, FunctionTemplateInfo >> get)
bool has_get () const
Handle< UnionOf< JSAny, FunctionTemplateInfo > > set () const
void set_set (DirectHandle< UnionOf< JSAny, FunctionTemplateInfo >> set)
bool has_set () const
DirectHandle< JSAny > name () const
void set_name (DirectHandle< JSAny > name)
PropertyAttributes ToAttributes ()
Static Public Member Functions
static bool IsAccessorDescriptor (PropertyDescriptor *desc)
static bool IsDataDescriptor (PropertyDescriptor *desc)
static bool IsGenericDescriptor (PropertyDescriptor *desc)
static bool ToPropertyDescriptor (Isolate *isolate, Handle< JSAny > obj, PropertyDescriptor *desc)
static void CompletePropertyDescriptor (Isolate *isolate, PropertyDescriptor *desc)
Private Attributes
bool enumerable_: 1
bool has_enumerable_: 1
bool configurable_: 1
bool has_configurable_: 1
bool writable_: 1
bool has_writable_: 1
IndirectHandle< JSAny > value_
IndirectHandle< UnionOf< JSAny, FunctionTemplateInfo > > get_
IndirectHandle< UnionOf< JSAny, FunctionTemplateInfo > > set_
IndirectHandle< JSAny > name_
Detailed Description
Definition at line 18 of file property-descriptor.h.
Constructor & Destructor Documentation
PropertyDescriptor()
v8::internal::PropertyDescriptor::PropertyDescriptor () [inline]
Definition at line 20 of file property-descriptor.h.
      : enumerable_(false),
        has_enumerable_(false),
        configurable_(false),
        has_configurable_(false),
        writable_(false),
        has_writable_(false) {}
Member Function Documentation
CompletePropertyDescriptor()
void v8::internal::PropertyDescriptor::CompletePropertyDescriptor (Isolate * isolate, PropertyDescriptor * desc) [static]
Definition at line 314 of file property-descriptor.cc.
                                                                              {
  // 1. ReturnIfAbrupt(Desc).
  // 2. Assert: Desc is a Property Descriptor.
  // 3. Let like be Record{
  // [[Value]]: undefined, [[Writable]]: false,
  // [[Get]]: undefined, [[Set]]: undefined,
  // [[Enumerable]]: false, [[Configurable]]: false}.
  // 4. If either IsGenericDescriptor(Desc) or IsDataDescriptor(Desc) is true,
  // then:
  if (!IsAccessorDescriptor(desc)) {
    // 4a. If Desc does not have a [[Value]] field, set Desc.[[Value]] to
    // like.[[Value]].
    if (!desc->has_value()) {
      desc->set_value(isolate->factory()->undefined_value());
    }
    // 4b. If Desc does not have a [[Writable]] field, set Desc.[[Writable]]
    // to like.[[Writable]].
    if (!desc->has_writable()) desc->set_writable(false);
  } else {
    // 5. Else,
    // 5a. If Desc does not have a [[Get]] field, set Desc.[[Get]] to
    // like.[[Get]].
    if (!desc->has_get()) {
      desc->set_get(isolate->factory()->undefined_value());
    }
    // 5b. If Desc does not have a [[Set]] field, set Desc.[[Set]] to
    // like.[[Set]].
    if (!desc->has_set()) {
      desc->set_set(isolate->factory()->undefined_value());
    }
  }
  // 6. If Desc does not have an [[Enumerable]] field, set
  // Desc.[[Enumerable]] to like.[[Enumerable]].
  if (!desc->has_enumerable()) desc->set_enumerable(false);
  // 7. If Desc does not have a [[Configurable]] field, set
  // Desc.[[Configurable]] to like.[[Configurable]].
  if (!desc->has_configurable()) desc->set_configurable(false);
  // 8. Return Desc.
}
References v8::internal::Isolate::factory(), has_configurable(), has_enumerable(), has_get(), has_set(), has_value(), has_writable(), IsAccessorDescriptor(), set_configurable(), set_enumerable(), set_get(), set_set(), set_value(), and set_writable().
Referenced by v8::internal::JSProxy::GetOwnPropertyDescriptor().
configurable()
bool v8::internal::PropertyDescriptor::configurable () const [inline]
Definition at line 79 of file property-descriptor.h.
{ return configurable_; }
References configurable_.
Referenced by v8::internal::JSArray::ArraySetLength(), v8::internal::JSProxy::CheckDeleteTrap(), v8::internal::JSProxy::CheckGetSetTrapResult(), v8::internal::JSProxy::CheckHasTrap(), v8::internal::KeyAccumulator::CollectOwnJSProxyKeys(), v8::internal::JSModuleNamespace::DefineOwnProperty(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::anonymous_namespace{js-objects.cc}::GenericTestIntegrityLevel(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), set_configurable(), ToAttributes(), ToObject(), ToPropertyDescriptor(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
enumerable()
bool v8::internal::PropertyDescriptor::enumerable () const [inline]
Definition at line 72 of file property-descriptor.h.
{ return enumerable_; }
References enumerable_.
Referenced by v8::internal::JSArray::ArraySetLength(), v8::internal::JSModuleNamespace::DefineOwnProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::FilterProxyKeys(), v8::internal::GetOwnValuesOrEntries(), set_enumerable(), v8::internal::JSReceiver::SetOrCopyDataProperties(), ToAttributes(), ToObject(), ToPropertyDescriptor(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
get()
Handle<UnionOf<JSAny, FunctionTemplateInfo> > v8::internal::PropertyDescriptor::get () const [inline]
Definition at line 97 of file property-descriptor.h.
{ return get_; }
References get_.
Referenced by v8::internal::JSProxy::CheckGetSetTrapResult(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor(), set_get(), ToObject(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
has_configurable()
bool v8::internal::PropertyDescriptor::has_configurable () const [inline]
Definition at line 84 of file property-descriptor.h.
{ return has_configurable_; }
References has_configurable_.
Referenced by CompletePropertyDescriptor(), v8::internal::JSModuleNamespace::DefineOwnProperty(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), is_empty(), IsRegularAccessorProperty(), IsRegularDataProperty(), ToAttributes(), ToObject(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
has_enumerable()
bool v8::internal::PropertyDescriptor::has_enumerable () const [inline]
Definition at line 77 of file property-descriptor.h.
{ return has_enumerable_; }
References has_enumerable_.
Referenced by v8::internal::JSArray::ArraySetLength(), CompletePropertyDescriptor(), v8::internal::JSModuleNamespace::DefineOwnProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), is_empty(), IsRegularAccessorProperty(), IsRegularDataProperty(), ToAttributes(), ToObject(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
has_get()
bool v8::internal::PropertyDescriptor::has_get () const [inline]
Definition at line 101 of file property-descriptor.h.
{ return !get_.is_null(); }
References get_.
Referenced by CompletePropertyDescriptor(), is_empty(), IsAccessorDescriptor(), IsRegularAccessorProperty(), IsRegularDataProperty(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor(), ToObject(), ToPropertyDescriptor(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), ToPropertyDescriptorObject(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
has_set()
bool v8::internal::PropertyDescriptor::has_set () const [inline]
Definition at line 107 of file property-descriptor.h.
{ return !set_.is_null(); }
References set_.
Referenced by CompletePropertyDescriptor(), is_empty(), IsAccessorDescriptor(), IsRegularAccessorProperty(), IsRegularDataProperty(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor(), ToObject(), ToPropertyDescriptor(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), ToPropertyDescriptorObject(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
has_value()
bool v8::internal::PropertyDescriptor::has_value () const [inline]
Definition at line 88 of file property-descriptor.h.
{ return !value_.is_null(); }
References value_.
Referenced by v8::internal::JSArray::ArraySetLength(), CompletePropertyDescriptor(), v8::internal::AlwaysSharedSpaceJSObject::DefineOwnProperty(), v8::internal::JSModuleNamespace::DefineOwnProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), is_empty(), IsDataDescriptor(), IsRegularAccessorProperty(), IsRegularDataProperty(), v8::internal::JSProxy::SetPrivateSymbol(), ToObject(), ToPropertyDescriptor(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), ToPropertyDescriptorObject(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
has_writable()
bool v8::internal::PropertyDescriptor::has_writable () const [inline]
Definition at line 95 of file property-descriptor.h.
{ return has_writable_; }
References has_writable_.
Referenced by v8::internal::JSArray::ArraySetLength(), CompletePropertyDescriptor(), v8::internal::JSArray::DefineOwnProperty(), v8::internal::JSModuleNamespace::DefineOwnProperty(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), is_empty(), IsDataDescriptor(), IsRegularAccessorProperty(), IsRegularDataProperty(), ToAttributes(), ToObject(), ToPropertyDescriptor(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
is_empty()
bool v8::internal::PropertyDescriptor::is_empty () const [inline]
Definition at line 57 of file property-descriptor.h.
                        {
    return !has_enumerable() && !has_configurable() && !has_writable() &&
           !has_value() && !has_get() && !has_set();
  }
References has_configurable(), has_enumerable(), has_get(), has_set(), has_value(), and has_writable().
Referenced by v8::internal::JSProxy::GetOwnPropertyDescriptor(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), ToPropertyDescriptor(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
IsAccessorDescriptor()
static bool v8::internal::PropertyDescriptor::IsAccessorDescriptor (PropertyDescriptor * desc) [inline], [static]
Definition at line 29 of file property-descriptor.h.
                                                             {
    return desc->has_get() || desc->has_set();
  }
References has_get(), and has_set().
Referenced by v8::internal::JSProxy::CheckGetSetTrapResult(), CompletePropertyDescriptor(), v8::internal::JSModuleNamespace::DefineOwnProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), IsGenericDescriptor(), v8::internal::JSReceiver::SetIntegrityLevel(), v8::internal::Object::SetSuperProperty(), ToObject(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
IsDataDescriptor()
static bool v8::internal::PropertyDescriptor::IsDataDescriptor (PropertyDescriptor * desc) [inline], [static]
Definition at line 34 of file property-descriptor.h.
                                                         {
    return desc->has_value() || desc->has_writable();
  }
References has_value(), and has_writable().
Referenced by v8::internal::JSProxy::CheckGetSetTrapResult(), v8::internal::AlwaysSharedSpaceJSObject::DefineOwnProperty(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::anonymous_namespace{js-objects.cc}::GenericTestIntegrityLevel(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), IsGenericDescriptor(), v8::internal::JSProxy::SetPrivateSymbol(), ToObject(), v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor(), and v8::internal::ValueSerializer::WriteJSError().
IsGenericDescriptor()
static bool v8::internal::PropertyDescriptor::IsGenericDescriptor (PropertyDescriptor * desc) [inline], [static]
Definition at line 39 of file property-descriptor.h.
                                                            {
    return !IsAccessorDescriptor(desc) && !IsDataDescriptor(desc);
  }
References IsAccessorDescriptor(), and IsDataDescriptor().
Referenced by v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
IsRegularAccessorProperty()
bool v8::internal::PropertyDescriptor::IsRegularAccessorProperty () const [inline]
Definition at line 62 of file property-descriptor.h.
                                         {
    return has_configurable() && has_enumerable() && !has_value() &&
           !has_writable() && has_get() && has_set();
  }
References has_configurable(), has_enumerable(), has_get(), has_set(), has_value(), and has_writable().
Referenced by ToObject().
IsRegularDataProperty()
bool v8::internal::PropertyDescriptor::IsRegularDataProperty () const [inline]
Definition at line 67 of file property-descriptor.h.
                                     {
    return has_configurable() && has_enumerable() && has_value() &&
           has_writable() && !has_get() && !has_set();
  }
References has_configurable(), has_enumerable(), has_get(), has_set(), has_value(), and has_writable().
Referenced by ToObject().
name()
DirectHandle<JSAny> v8::internal::PropertyDescriptor::name () const [inline]
Definition at line 109 of file property-descriptor.h.
{ return name_; }
References name_.
Referenced by v8::internal::JSReceiver::DefineProperties(), and set_name().
set()
Handle<UnionOf<JSAny, FunctionTemplateInfo> > v8::internal::PropertyDescriptor::set () const [inline]
Definition at line 103 of file property-descriptor.h.
{ return set_; }
References set_.
Referenced by v8::internal::JSProxy::CheckGetSetTrapResult(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectLookupAccessor(), set_set(), ToObject(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
set_configurable()
void v8::internal::PropertyDescriptor::set_configurable (bool configurable) [inline]
Definition at line 80 of file property-descriptor.h.
                                           {
    configurable_ = configurable;
    has_configurable_ = true;
  }
References configurable(), configurable_, and has_configurable_.
Referenced by v8::internal::JSReceiver::AddPrivateField(), v8::internal::ErrorUtils::CaptureStackTrace(), CompletePropertyDescriptor(), v8::internal::JSReceiver::CreateDataProperty(), v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::Object::DefineOwnProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedDescriptor(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::wasm::JSPrototypesSetup::InstallMethodImpl(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectDefineAccessor(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::JsonParseInternalizer::RecurseAndApply(), v8::Object::SetAccessorProperty(), v8::internal::JSReceiver::SetIntegrityLevel(), v8::Object::SetPrivate(), ToPropertyDescriptor(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
set_enumerable()
void v8::internal::PropertyDescriptor::set_enumerable (bool enumerable) [inline]
Definition at line 73 of file property-descriptor.h.
                                       {
    enumerable_ = enumerable;
    has_enumerable_ = true;
  }
References enumerable(), enumerable_, and has_enumerable_.
Referenced by v8::internal::JSReceiver::AddPrivateField(), v8::internal::ErrorUtils::CaptureStackTrace(), CompletePropertyDescriptor(), v8::internal::JSReceiver::CreateDataProperty(), v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::Object::DefineOwnProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedDescriptor(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::wasm::JSPrototypesSetup::InstallMethodImpl(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectDefineAccessor(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::JsonParseInternalizer::RecurseAndApply(), v8::Object::SetAccessorProperty(), v8::Object::SetPrivate(), ToPropertyDescriptor(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
set_get()
void v8::internal::PropertyDescriptor::set_get (DirectHandle< UnionOf< JSAny, FunctionTemplateInfo >> get) [inline]
Definition at line 98 of file property-descriptor.h.
                                                                       {
    get_ = indirect_handle(get);
  }
References get(), get_, and v8::internal::indirect_handle().
Referenced by v8::internal::ErrorUtils::CaptureStackTrace(), CompletePropertyDescriptor(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::wasm::JSPrototypesSetup::InstallMethodImpl(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectDefineAccessor(), v8::PropertyDescriptor::PropertyDescriptor(), v8::Object::SetAccessorProperty(), ToPropertyDescriptor(), and v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath().
set_name()
void v8::internal::PropertyDescriptor::set_name (DirectHandle< JSAny > name) [inline]
Definition at line 110 of file property-descriptor.h.
{ name_ = indirect_handle(name); }
References v8::internal::indirect_handle(), name(), and name_.
set_set()
void v8::internal::PropertyDescriptor::set_set (DirectHandle< UnionOf< JSAny, FunctionTemplateInfo >> set) [inline]
Definition at line 104 of file property-descriptor.h.
                                                                       {
    set_ = indirect_handle(set);
  }
References v8::internal::indirect_handle(), set(), and set_.
Referenced by v8::internal::ErrorUtils::CaptureStackTrace(), CompletePropertyDescriptor(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::wasm::JSPrototypesSetup::InstallMethodImpl(), v8::internal::anonymous_namespace{builtins-object.cc}::ObjectDefineAccessor(), v8::PropertyDescriptor::PropertyDescriptor(), v8::Object::SetAccessorProperty(), ToPropertyDescriptor(), and v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath().
set_value()
void v8::internal::PropertyDescriptor::set_value (DirectHandle< JSAny > value) [inline]
Definition at line 87 of file property-descriptor.h.
{ value_ = indirect_handle(value); }
References v8::internal::indirect_handle(), value(), and value_.
Referenced by v8::internal::JSReceiver::AddPrivateField(), v8::internal::JSArray::ArraySetLength(), CompletePropertyDescriptor(), v8::internal::JSReceiver::CreateDataProperty(), v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), v8::internal::JSArray::DefineOwnProperty(), v8::Object::DefineOwnProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedDescriptor(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::wasm::JSPrototypesSetup::InstallMethodImpl(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::PropertyDescriptor::PropertyDescriptor(), v8::internal::JsonParseInternalizer::RecurseAndApply(), v8::Object::SetPrivate(), v8::internal::Object::SetSuperProperty(), ToPropertyDescriptor(), and v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath().
set_writable()
void v8::internal::PropertyDescriptor::set_writable (bool writable) [inline]
Definition at line 91 of file property-descriptor.h.
                                   {
    writable_ = writable;
    has_writable_ = true;
  }
References has_writable_, writable(), and writable_.
Referenced by v8::internal::JSReceiver::AddPrivateField(), v8::internal::JSArray::ArraySetLength(), CompletePropertyDescriptor(), v8::internal::JSReceiver::CreateDataProperty(), v8::internal::anonymous_namespace{ic.cc}::DefineOwnDataProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::Object::DefineOwnProperty(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedDescriptor(), v8::internal::Genesis::InstallABunchOfRandomThings(), v8::internal::wasm::JSPrototypesSetup::InstallMethodImpl(), v8::internal::anonymous_namespace{builtins-intl.cc}::LegacyFormatConstructor(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::PropertyDescriptor::PropertyDescriptor(), v8::internal::JsonParseInternalizer::RecurseAndApply(), v8::internal::JSReceiver::SetIntegrityLevel(), v8::Object::SetPrivate(), ToPropertyDescriptor(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
ToAttributes()
PropertyAttributes v8::internal::PropertyDescriptor::ToAttributes () [inline]
Definition at line 112 of file property-descriptor.h.
                                    {
    return static_cast<PropertyAttributes>(
        (has_enumerable() && !enumerable() ? DONT_ENUM : NONE) |
        (has_configurable() && !configurable() ? DONT_DELETE : NONE) |
        (has_writable() && !writable() ? READ_ONLY : NONE));
  }
References configurable(), v8::internal::DONT_DELETE, v8::internal::DONT_ENUM, enumerable(), has_configurable(), has_enumerable(), has_writable(), v8::internal::NONE, v8::internal::READ_ONLY, and writable().
Referenced by v8::internal::AlwaysSharedSpaceJSObject::DefineOwnProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::internal::JSProxy::GetPropertyAttributes(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::JSProxy::SetPrivateSymbol(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
ToObject()
DirectHandle< JSObject > v8::internal::PropertyDescriptor::ToObject (Isolate * isolate)
Definition at line 133 of file property-descriptor.cc.
                                                                    {
  DCHECK(!(PropertyDescriptor::IsAccessorDescriptor(this) &&
           PropertyDescriptor::IsDataDescriptor(this)));
  Factory* factory = isolate->factory();
  if (IsRegularAccessorProperty()) {
    // Fast case for regular accessor properties.
    DirectHandle<JSObject> result = factory->NewJSObjectFromMap(
        isolate->accessor_property_descriptor_map());
    result->InObjectPropertyAtPut(JSAccessorPropertyDescriptor::kGetIndex,
                                  *get());
    result->InObjectPropertyAtPut(JSAccessorPropertyDescriptor::kSetIndex,
                                  *set());
    result->InObjectPropertyAtPut(
        JSAccessorPropertyDescriptor::kEnumerableIndex,
        isolate->heap()->ToBoolean(enumerable()));
    result->InObjectPropertyAtPut(
        JSAccessorPropertyDescriptor::kConfigurableIndex,
        isolate->heap()->ToBoolean(configurable()));
    return result;
  }
  if (IsRegularDataProperty()) {
    // Fast case for regular data properties.
    DirectHandle<JSObject> result =
        factory->NewJSObjectFromMap(isolate->data_property_descriptor_map());
    result->InObjectPropertyAtPut(JSDataPropertyDescriptor::kValueIndex,
                                  *value());
    result->InObjectPropertyAtPut(JSDataPropertyDescriptor::kWritableIndex,
                                  isolate->heap()->ToBoolean(writable()));
    result->InObjectPropertyAtPut(JSDataPropertyDescriptor::kEnumerableIndex,
                                  isolate->heap()->ToBoolean(enumerable()));
    result->InObjectPropertyAtPut(JSDataPropertyDescriptor::kConfigurableIndex,
                                  isolate->heap()->ToBoolean(configurable()));
    return result;
  }
  DirectHandle<JSObject> result =
      factory->NewJSObject(isolate->object_function());
  if (has_value()) {
    CreateDataProperty(isolate, result, factory->value_string(), value());
  }
  if (has_writable()) {
    CreateDataProperty(isolate, result, factory->writable_string(),
                       factory->ToBoolean(writable()));
  }
  if (has_get()) {
    CreateDataProperty(isolate, result, factory->get_string(), get());
  }
  if (has_set()) {
    CreateDataProperty(isolate, result, factory->set_string(), set());
  }
  if (has_enumerable()) {
    CreateDataProperty(isolate, result, factory->enumerable_string(),
                       factory->ToBoolean(enumerable()));
  }
  if (has_configurable()) {
    CreateDataProperty(isolate, result, factory->configurable_string(),
                       factory->ToBoolean(configurable()));
  }
  return result;
}
References configurable(), v8::internal::anonymous_namespace{property-descriptor.cc}::CreateDataProperty(), v8::internal::DCHECK(), enumerable(), v8::internal::Isolate::factory(), get(), has_configurable(), has_enumerable(), has_get(), has_set(), has_value(), has_writable(), v8::internal::Isolate::heap(), IsAccessorDescriptor(), IsDataDescriptor(), IsRegularAccessorProperty(), IsRegularDataProperty(), v8::internal::JSAccessorPropertyDescriptor::kConfigurableIndex, v8::internal::JSDataPropertyDescriptor::kConfigurableIndex, v8::internal::JSAccessorPropertyDescriptor::kEnumerableIndex, v8::internal::JSDataPropertyDescriptor::kEnumerableIndex, v8::internal::JSAccessorPropertyDescriptor::kSetIndex, v8::internal::JSDataPropertyDescriptor::kWritableIndex, v8::internal::Factory::NewJSObject(), v8::internal::Factory::NewJSObjectFromMap(), v8::base::internal::result, set(), v8::internal::Heap::ToBoolean(), v8::internal::FactoryBase< Impl >::ToBoolean(), value(), and writable().
Referenced by v8::internal::BUILTIN(), v8::internal::JSProxy::DefineOwnProperty(), v8::Object::GetOwnPropertyDescriptor(), and v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::IndexedDescriptor().
ToPropertyDescriptor()
bool v8::internal::PropertyDescriptor::ToPropertyDescriptor (Isolate * isolate, Handle< JSAny > obj, PropertyDescriptor * desc) [static]
Definition at line 196 of file property-descriptor.cc.
                                                                        {
  // 1. ReturnIfAbrupt(Obj).
  // 2. If Type(Obj) is not Object, throw a TypeError exception.
  if (!IsJSReceiver(*obj)) {
    isolate->Throw(*isolate->factory()->NewTypeError(
        MessageTemplate::kPropertyDescObject, obj));
    return false;
  }
  // 3. Let desc be a new Property Descriptor that initially has no fields.
  DCHECK(desc->is_empty());
  DirectHandle<JSReceiver> receiver = Cast<JSReceiver>(obj);
  if (ToPropertyDescriptorFastPath(isolate, receiver, desc)) {
    return true;
  }
  // enumerable?
  Handle<JSAny> enumerable;
  // 4 through 6b.
  if (!GetPropertyIfPresent(isolate, receiver,
                            isolate->factory()->enumerable_string(),
                            &enumerable)) {
    return false;
  }
  // 6c. Set the [[Enumerable]] field of desc to enum.
  if (!enumerable.is_null()) {
    desc->set_enumerable(Object::BooleanValue(*enumerable, isolate));
  }
  // configurable?
  Handle<JSAny> configurable;
  // 7 through 9b.
  if (!GetPropertyIfPresent(isolate, receiver,
                            isolate->factory()->configurable_string(),
                            &configurable)) {
    return false;
  }
  // 9c. Set the [[Configurable]] field of desc to conf.
  if (!configurable.is_null()) {
    desc->set_configurable(Object::BooleanValue(*configurable, isolate));
  }
  // value?
  Handle<JSAny> value;
  // 10 through 12b.
  if (!GetPropertyIfPresent(isolate, receiver,
                            isolate->factory()->value_string(), &value)) {
    return false;
  }
  // 12c. Set the [[Value]] field of desc to value.
  if (!value.is_null()) desc->set_value(value);
  // writable?
  Handle<JSAny> writable;
  // 13 through 15b.
  if (!GetPropertyIfPresent(isolate, receiver,
                            isolate->factory()->writable_string(), &writable)) {
    return false;
  }
  // 15c. Set the [[Writable]] field of desc to writable.
  if (!writable.is_null())
    desc->set_writable(Object::BooleanValue(*writable, isolate));
  // getter?
  Handle<JSAny> getter;
  // 16 through 18b.
  if (!GetPropertyIfPresent(isolate, receiver, isolate->factory()->get_string(),
                            &getter)) {
    return false;
  }
  if (!getter.is_null()) {
    // 18c. If IsCallable(getter) is false and getter is not undefined,
    // throw a TypeError exception.
    if (!IsCallable(*getter) && !IsUndefined(*getter, isolate)) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kObjectGetterCallable, getter));
      return false;
    }
    // 18d. Set the [[Get]] field of desc to getter.
    desc->set_get(getter);
  }
  // setter?
  Handle<JSAny> setter;
  // 19 through 21b.
  if (!GetPropertyIfPresent(isolate, receiver, isolate->factory()->set_string(),
                            &setter)) {
    return false;
  }
  if (!setter.is_null()) {
    // 21c. If IsCallable(setter) is false and setter is not undefined,
    // throw a TypeError exception.
    if (!IsCallable(*setter) && !IsUndefined(*setter, isolate)) {
      isolate->Throw(*isolate->factory()->NewTypeError(
          MessageTemplate::kObjectSetterCallable, setter));
      return false;
    }
    // 21d. Set the [[Set]] field of desc to setter.
    desc->set_set(setter);
  }
  // 22. If either desc.[[Get]] or desc.[[Set]] is present, then
  // 22a. If either desc.[[Value]] or desc.[[Writable]] is present,
  // throw a TypeError exception.
  if ((desc->has_get() || desc->has_set()) &&
      (desc->has_value() || desc->has_writable())) {
    isolate->Throw(*isolate->factory()->NewTypeError(
        MessageTemplate::kValueAndAccessor, obj));
    return false;
  }
  // 23. Return desc.
  return true;
}
References v8::internal::Object::BooleanValue(), configurable(), v8::internal::DCHECK(), enumerable(), v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{property-descriptor.cc}::GetPropertyIfPresent(), has_get(), has_set(), has_value(), has_writable(), is_empty(), v8::internal::HandleBase::is_null(), set_configurable(), set_enumerable(), set_get(), set_set(), set_value(), set_writable(), v8::internal::setter, v8::internal::Isolate::Throw(), v8::internal::anonymous_namespace{property-descriptor.cc}::ToPropertyDescriptorFastPath(), value(), and writable().
Referenced by v8::internal::BUILTIN(), v8::internal::JSReceiver::DefineProperties(), v8::internal::JSReceiver::DefineProperty(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), and v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor().
ToPropertyDescriptorObject()
DirectHandle< PropertyDescriptorObject > v8::internal::PropertyDescriptor::ToPropertyDescriptorObject (Isolate * isolate)
Definition at line 356 of file property-descriptor.cc.
                                                               {
  DirectHandle<PropertyDescriptorObject> obj =
      isolate->factory()->NewPropertyDescriptorObject();
  int flags =
      PropertyDescriptorObject::IsEnumerableBit::encode(enumerable_) |
      PropertyDescriptorObject::HasEnumerableBit::encode(has_enumerable_) |
      PropertyDescriptorObject::IsConfigurableBit::encode(configurable_) |
      PropertyDescriptorObject::HasConfigurableBit::encode(has_configurable_) |
      PropertyDescriptorObject::IsWritableBit::encode(writable_) |
      PropertyDescriptorObject::HasWritableBit::encode(has_writable_) |
      PropertyDescriptorObject::HasValueBit::encode(has_value()) |
      PropertyDescriptorObject::HasGetBit::encode(has_get()) |
      PropertyDescriptorObject::HasSetBit::encode(has_set());
  obj->set_flags(flags);
  if (has_value()) obj->set_value(*value_);
  if (has_get()) obj->set_get(*get_);
  if (has_set()) obj->set_set(*set_);
  return obj;
}
References configurable_, enumerable_, v8::internal::Isolate::factory(), v8::internal::flags, get_, has_configurable_, has_enumerable_, has_get(), has_set(), has_value(), has_writable_, v8::internal::Factory::NewPropertyDescriptorObject(), set_, value_, and writable_.
value()
Handle<JSAny> v8::internal::PropertyDescriptor::value () const [inline]
Definition at line 86 of file property-descriptor.h.
{ return value_; }
References value_.
Referenced by v8::internal::JSArray::ArraySetLength(), v8::internal::JSProxy::CheckGetSetTrapResult(), v8::internal::AlwaysSharedSpaceJSObject::DefineOwnProperty(), v8::internal::JSArray::DefineOwnProperty(), v8::internal::JSModuleNamespace::DefineOwnProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), set_value(), v8::internal::JSProxy::SetPrivateSymbol(), ToObject(), ToPropertyDescriptor(), v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor(), and v8::internal::ValueSerializer::WriteJSError().
writable()
bool v8::internal::PropertyDescriptor::writable () const [inline]
Definition at line 90 of file property-descriptor.h.
{ return writable_; }
References writable_.
Referenced by v8::internal::JSArray::ArraySetLength(), v8::internal::JSProxy::CheckGetSetTrapResult(), v8::internal::JSArray::DefineOwnProperty(), v8::internal::JSModuleNamespace::DefineOwnProperty(), v8::internal::JSProxy::DefineOwnProperty(), v8::internal::JSTypedArray::DefineOwnProperty(), v8::internal::anonymous_namespace{js-objects.cc}::DefinePropertyWithInterceptorInternal(), v8::internal::anonymous_namespace{js-objects.cc}::GenericTestIntegrityLevel(), v8::internal::JSProxy::GetOwnPropertyDescriptor(), set_writable(), v8::internal::Object::SetSuperProperty(), ToAttributes(), ToObject(), ToPropertyDescriptor(), and v8::internal::JSReceiver::ValidateAndApplyPropertyDescriptor().
Member Data Documentation
configurable_
bool v8::internal::PropertyDescriptor::configurable_ [private]
Definition at line 122 of file property-descriptor.h.
Referenced by configurable(), set_configurable(), and ToPropertyDescriptorObject().
enumerable_
bool v8::internal::PropertyDescriptor::enumerable_ [private]
Definition at line 120 of file property-descriptor.h.
Referenced by enumerable(), set_enumerable(), and ToPropertyDescriptorObject().
get_
IndirectHandle<UnionOf<JSAny, FunctionTemplateInfo> > v8::internal::PropertyDescriptor::get_ [private]
Definition at line 130 of file property-descriptor.h.
Referenced by get(), has_get(), set_get(), and ToPropertyDescriptorObject().
has_configurable_
bool v8::internal::PropertyDescriptor::has_configurable_ [private]
Definition at line 123 of file property-descriptor.h.
Referenced by has_configurable(), set_configurable(), and ToPropertyDescriptorObject().
has_enumerable_
bool v8::internal::PropertyDescriptor::has_enumerable_ [private]
Definition at line 121 of file property-descriptor.h.
Referenced by has_enumerable(), set_enumerable(), and ToPropertyDescriptorObject().
has_writable_
bool v8::internal::PropertyDescriptor::has_writable_ [private]
Definition at line 125 of file property-descriptor.h.
Referenced by has_writable(), set_writable(), and ToPropertyDescriptorObject().
name_
IndirectHandle<JSAny> v8::internal::PropertyDescriptor::name_ [private]
Definition at line 132 of file property-descriptor.h.
Referenced by name(), and set_name().
set_
IndirectHandle<UnionOf<JSAny, FunctionTemplateInfo> > v8::internal::PropertyDescriptor::set_ [private]
Definition at line 131 of file property-descriptor.h.
Referenced by has_set(), set(), set_set(), and ToPropertyDescriptorObject().
value_
IndirectHandle<JSAny> v8::internal::PropertyDescriptor::value_ [private]
Definition at line 129 of file property-descriptor.h.
Referenced by has_value(), set_value(), ToPropertyDescriptorObject(), and value().
writable_
bool v8::internal::PropertyDescriptor::writable_ [private]
Definition at line 124 of file property-descriptor.h.
Referenced by set_writable(), ToPropertyDescriptorObject(), and writable().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/property-descriptor.h
/mnt/V8SourceCode/src/objects/property-descriptor.cc