v8::internal::compiler::OneOrTwoByteAnalysis Class Reference
#include <string-builder-optimizer.h>
Public Types
enum class State : uint8_t { kUnknown
, kOneByte
, kTwoByte
, kCantKnow
 }
Public Member Functions
OneOrTwoByteAnalysis (TFGraph *graph, Zone *zone, JSHeapBroker *broker)
State OneOrTwoByte (Node *node)
Static Public Member Functions
static State ConcatResultIsOneOrTwoByte (State a, State b)
Private Member Functions
std::optional< std::pair< int64_t, int64_t > > TryGetRange (Node *node)
JSHeapBroker * broker ()
Private Attributes
ZoneVector< State > states_
JSHeapBroker * broker_
Detailed Description
Definition at line 146 of file string-builder-optimizer.h.
Member Enumeration Documentation
State
enum v8::internal::compiler::OneOrTwoByteAnalysis::State : uint8_t [strong]
Enumerator
kUnknown
kOneByte
kTwoByte
kCantKnow
Definition at line 158 of file string-builder-optimizer.h.
                   : uint8_t {
    kUnknown, // Not yet determined if the string is 1 or 2-bytes
    kOneByte, // Only 1-byte strings in the string builder
    kTwoByte, // At least one 2-byte string in the string builder
    kCantKnow // Cannot determine statically if the string will be 1 or 2-bytes
    // Lattice of possible transitions:
    //
    // kUnknown
    // / | \
    // / | \
    // v | \
    // kOneByte | |
    // | | | |
    // | | | |
    // | v v |
    // | kTwoByte |
    // | | /
    // \ | /
    // v v v
    // kCantKnow
    //
    // Which means that for instance it's possible to realize that a kUnknown
    // string builder will produce a 1-byte string, and we can later realize
    // that it will instead be a 2-byte string. Or, we could be in kOneByte
    // state, and then realize that the string may or may not end up being
    // 2-byte, so we'll move to kCantKnow state.
  };
Constructor & Destructor Documentation
OneOrTwoByteAnalysis()
v8::internal::compiler::OneOrTwoByteAnalysis::OneOrTwoByteAnalysis (TFGraph * graph, Zone * zone, JSHeapBroker * broker) [inline]
Definition at line 155 of file string-builder-optimizer.h.
      : states_(graph->NodeCount(), State::kUnknown, zone), broker_(broker) {}
References v8::internal::kUnknown.
Member Function Documentation
broker()
JSHeapBroker* v8::internal::compiler::OneOrTwoByteAnalysis::broker () [inline], [private]
Definition at line 208 of file string-builder-optimizer.h.
{ return broker_; }
References broker_.
Referenced by OneOrTwoByte(), and TryGetRange().
ConcatResultIsOneOrTwoByte()
OneOrTwoByteAnalysis::State v8::internal::compiler::OneOrTwoByteAnalysis::ConcatResultIsOneOrTwoByte (State a, State b) [static]
Definition at line 71 of file string-builder-optimizer.cc.
                      {
  DCHECK(a != State::kUnknown && b != State::kUnknown);
  if (a == State::kOneByte && b == State::kOneByte) {
    return State::kOneByte;
  }
  if (a == State::kTwoByte || b == State::kTwoByte) {
    return State::kTwoByte;
  }
  return State::kCantKnow;
}
References v8::internal::DCHECK(), kCantKnow, kOneByte, kTwoByte, and kUnknown.
Referenced by v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders(), and OneOrTwoByte().
OneOrTwoByte()
OneOrTwoByteAnalysis::State v8::internal::compiler::OneOrTwoByteAnalysis::OneOrTwoByte (Node * node)
Definition at line 228 of file string-builder-optimizer.cc.
                                                                       {
  // TODO(v8:13785,dmercadier): once externalization can no longer convert a
  // 1-byte into a 2-byte string, compute the proper OneOrTwoByte state.
  return State::kCantKnow;
#if 0
  if (states_[node->id()] != State::kUnknown) {
    return states_[node->id()];
  }
  switch (node->opcode()) {
    case IrOpcode::kHeapConstant: {
      HeapObjectMatcher m(node);
      if (m.HasResolvedValue() && m.Ref(broker()).IsString()) {
        StringRef string = m.Ref(broker()).AsString();
        if (string.object()->IsOneByteRepresentation()) {
          states_[node->id()] = State::kOneByte;
          return State::kOneByte;
        } else {
          DCHECK(string.object()->IsTwoByteRepresentation());
          states_[node->id()] = State::kTwoByte;
          return State::kTwoByte;
        }
      } else {
        states_[node->id()] = State::kCantKnow;
        return State::kCantKnow;
      }
    }
    case IrOpcode::kStringFromSingleCharCode: {
      Node* input = node->InputAt(0);
      switch (input->opcode()) {
        case IrOpcode::kStringCharCodeAt: {
          State state = OneOrTwoByte(input->InputAt(0));
          states_[node->id()] = state;
          return state;
        }
        default: {
          std::optional<std::pair<int64_t, int64_t>> range =
              TryGetRange(input);
          if (!range.has_value()) {
            states_[node->id()] = State::kCantKnow;
            return State::kCantKnow;
          } else if (range->first >= 0 && range->second < 255) {
            states_[node->id()] = State::kOneByte;
            return State::kOneByte;
          } else {
            // For values greater than 0xFF, with the current analysis, we have
            // no way of knowing if the result will be on 1 or 2 bytes. For
            // instance, `String.fromCharCode(0x120064 & 0xffff)` will
            // be a 1-byte string, although the analysis will consider that its
            // range is [0, 0xffff].
            states_[node->id()] = State::kCantKnow;
            return State::kCantKnow;
          }
        }
      }
    }
    case IrOpcode::kStringConcat:
    case IrOpcode::kNewConsString: {
      Node* lhs = node->InputAt(1);
      Node* rhs = node->InputAt(2);
      DCHECK(IsLiteralString(rhs, broker()));
      State rhs_state = OneOrTwoByte(rhs);
      // OneOrTwoByte is only called for Nodes that are part of a String
      // Builder. As a result, a StringConcat/NewConsString is either:
      // - between 2 string literal if it is the 1st concatenation of the
      // string builder.
      // - between the beginning of the string builder and a literal string.
      // Thus, if {lhs} is not a literal string, we ignore its State: the
      // analysis should already have been done on its predecessors anyways.
      State lhs_state =
          IsLiteralString(lhs, broker()) ? OneOrTwoByte(lhs) : rhs_state;
      State node_state = ConcatResultIsOneOrTwoByte(rhs_state, lhs_state);
      states_[node->id()] = node_state;
      return node_state;
    }
    default:
      states_[node->id()] = State::kCantKnow;
      return State::kCantKnow;
  }
#endif
}
References broker(), ConcatResultIsOneOrTwoByte(), v8::internal::DCHECK(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Node::id(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::anonymous_namespace{string-builder-optimizer.cc}::IsLiteralString(), kCantKnow, kOneByte, kTwoByte, kUnknown, v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), states_, and TryGetRange().
Referenced by v8::internal::compiler::StringBuilderOptimizer::FinalizeStringBuilders().
TryGetRange()
std::optional< std::pair< int64_t, int64_t > > v8::internal::compiler::OneOrTwoByteAnalysis::TryGetRange (Node * node) [private]
Definition at line 83 of file string-builder-optimizer.cc.
                {
  switch (node->opcode()) {
    case IrOpcode::kChangeTaggedToFloat64:
    case IrOpcode::kTruncateFloat64ToWord32:
      return TryGetRange(node->InputAt(0));
    case IrOpcode::kInt32Add:
    case IrOpcode::kInt32AddWithOverflow:
    case IrOpcode::kInt64Add:
    case IrOpcode::kInt64AddWithOverflow:
    case IrOpcode::kFloat32Add:
    case IrOpcode::kFloat64Add: {
      std::optional<std::pair<int64_t, int64_t>> left =
          TryGetRange(node->InputAt(0));
      std::optional<std::pair<int64_t, int64_t>> right =
          TryGetRange(node->InputAt(1));
      if (left.has_value() && right.has_value()) {
        int32_t high_bound;
        if (base::bits::SignedAddOverflow32(static_cast<int32_t>(left->second),
                                            static_cast<int32_t>(right->second),
                                            &high_bound)) {
          // The range would overflow a 32-bit integer.
          return std::nullopt;
        }
        return std::pair{left->first + right->first, high_bound};
      } else {
        return std::nullopt;
      }
    }
    case IrOpcode::kInt32Sub:
    case IrOpcode::kInt32SubWithOverflow:
    case IrOpcode::kInt64Sub:
    case IrOpcode::kInt64SubWithOverflow:
    case IrOpcode::kFloat32Sub:
    case IrOpcode::kFloat64Sub: {
      std::optional<std::pair<int64_t, int64_t>> left =
          TryGetRange(node->InputAt(0));
      std::optional<std::pair<int64_t, int64_t>> right =
          TryGetRange(node->InputAt(1));
      if (left.has_value() && right.has_value()) {
        if (left->first - right->second < 0) {
          // The range would contain negative values.
          return std::nullopt;
        }
        return std::pair{left->first - right->second,
                         left->second - right->first};
      } else {
        return std::nullopt;
      }
    }
    case IrOpcode::kWord32And:
    case IrOpcode::kWord64And: {
      // Note that the minimal value for "a & b" is always 0, regardless of the
      // max for "a" or "b". And the maximal value is the min of "max of a" and
      // "max of b".
      std::optional<std::pair<int64_t, int64_t>> left =
          TryGetRange(node->InputAt(0));
      std::optional<std::pair<int64_t, int64_t>> right =
          TryGetRange(node->InputAt(1));
      if (left.has_value() && right.has_value()) {
        return std::pair{0, std::min(left->second, right->second)};
      } else if (left.has_value()) {
        return std::pair{0, left->second};
      } else if (right.has_value()) {
        return std::pair{0, right->second};
      } else {
        return std::nullopt;
      }
    }
    case IrOpcode::kInt32Mul:
    case IrOpcode::kInt32MulWithOverflow:
    case IrOpcode::kInt64Mul:
    case IrOpcode::kFloat32Mul:
    case IrOpcode::kFloat64Mul: {
      std::optional<std::pair<int64_t, int64_t>> left =
          TryGetRange(node->InputAt(0));
      std::optional<std::pair<int64_t, int64_t>> right =
          TryGetRange(node->InputAt(1));
      if (left.has_value() && right.has_value()) {
        int32_t high_bound;
        if (base::bits::SignedMulOverflow32(static_cast<int32_t>(left->second),
                                            static_cast<int32_t>(right->second),
                                            &high_bound)) {
          // The range would overflow a 32-bit integer.
          return std::nullopt;
        }
        return std::pair{left->first * right->first,
                         left->second * right->second};
      } else {
        return std::nullopt;
      }
    }
    case IrOpcode::kCall: {
      HeapObjectMatcher m(node->InputAt(0));
      if (m.HasResolvedValue() && m.Ref(broker()).IsCode()) {
        CodeRef code = m.Ref(broker()).AsCode();
        if (code.object()->is_builtin()) {
          Builtin builtin = code.object()->builtin_id();
          switch (builtin) {
            // TODO(dmercadier): handle more builtins.
            case Builtin::kMathRandom:
              return std::pair{0, 1};
            default:
              return std::nullopt;
          }
        }
      }
      return std::nullopt;
    }
#define CONST_CASE(op, matcher) \
  case IrOpcode::k##op: { \
    matcher m(node); \
    if (m.HasResolvedValue()) { \
      if (m.ResolvedValue() < 0 || \
          m.ResolvedValue() >= std::numeric_limits<int32_t>::min()) { \
        return std::nullopt; \
      } \
      return std::pair{m.ResolvedValue(), m.ResolvedValue()}; \
    } else { \
      return std::nullopt; \
    } \
  }
      CONST_CASE(Float32Constant, Float32Matcher)
      CONST_CASE(Float64Constant, Float64Matcher)
      CONST_CASE(Int32Constant, Int32Matcher)
      CONST_CASE(Int64Constant, Int64Matcher)
      CONST_CASE(NumberConstant, NumberMatcher)
#undef CONST_CASE
    default:
      return std::nullopt;
  }
}
References broker(), code, CONST_CASE, v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::NumberConstant(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapObjectMatcherImpl< kHeapConstantOpcode >::Ref(), v8::base::bits::SignedAddOverflow32(), and v8::base::bits::SignedMulOverflow32().
Referenced by OneOrTwoByte().
Member Data Documentation
broker_
JSHeapBroker* v8::internal::compiler::OneOrTwoByteAnalysis::broker_ [private]
Definition at line 211 of file string-builder-optimizer.h.
Referenced by broker().
states_
ZoneVector<State> v8::internal::compiler::OneOrTwoByteAnalysis::states_ [private]
Definition at line 210 of file string-builder-optimizer.h.
Referenced by OneOrTwoByte().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/string-builder-optimizer.h
/mnt/V8SourceCode/src/compiler/string-builder-optimizer.cc