v8::base::PageAllocator Class Reference
#include <page-allocator.h>
Public Member Functions
PageAllocator ()
~PageAllocator () override=default
size_t AllocatePageSize () override
size_t CommitPageSize () override
void SetRandomMmapSeed (int64_t seed) override
void * GetRandomMmapAddr () override
void * AllocatePages (void *hint, size_t size, size_t alignment, PageAllocator::Permission access) override
bool CanAllocateSharedPages () override
std::unique_ptr< v8::PageAllocator::SharedMemory > AllocateSharedPages (size_t size, const void *original_address) override
bool FreePages (void *address, size_t size) override
bool ReleasePages (void *address, size_t size, size_t new_size) override
bool SetPermissions (void *address, size_t size, PageAllocator::Permission access) override
bool RecommitPages (void *address, size_t size, PageAllocator::Permission access) override
bool DiscardSystemPages (void *address, size_t size) override
bool DecommitPages (void *address, size_t size) override
bool SealPages (void *address, size_t size) override
Private Member Functions
void * RemapShared (void *old_address, void *new_address, size_t size)
Private Attributes
const size_t allocate_page_size_
const size_t commit_page_size_
Friends
class v8::base::SharedMemory
Detailed Description
Definition at line 19 of file page-allocator.h.
Constructor & Destructor Documentation
PageAllocator()
v8::base::PageAllocator::PageAllocator ()
Definition at line 33 of file page-allocator.cc.
    : allocate_page_size_(base::OS::AllocatePageSize()),
      commit_page_size_(base::OS::CommitPageSize()) {}
 PageAllocator()
v8::base::PageAllocator::~PageAllocator () [override], [default]
Member Function Documentation
AllocatePages()
void * v8::base::PageAllocator::AllocatePages (void * hint, size_t size, size_t alignment, PageAllocator::Permission access) [override]
Definition at line 45 of file page-allocator.cc.
                                                                   {
#if !V8_HAS_PTHREAD_JIT_WRITE_PROTECT && !V8_HAS_BECORE_JIT_WRITE_PROTECT
  // kNoAccessWillJitLater is only used on Apple Silicon. Map it to regular
  // kNoAccess on other platforms, so code doesn't have to handle both enum
  // values.
  if (access == PageAllocator::kNoAccessWillJitLater) {
    access = PageAllocator::kNoAccess;
  }
#endif
  return base::OS::Allocate(hint, size, alignment,
                            static_cast<base::OS::MemoryPermission>(access));
}
References v8::base::OS::Allocate(), v8::PageAllocator::kNoAccess, v8::PageAllocator::kNoAccessWillJitLater, and size().
AllocatePageSize()
size_t v8::base::PageAllocator::AllocatePageSize () [inline], [override]
Definition at line 25 of file page-allocator.h.
{ return allocate_page_size_; }
AllocateSharedPages()
std::unique_ptr< v8::PageAllocator::SharedMemory > v8::base::PageAllocator::AllocateSharedPages (size_t size, const void * original_address) [override]
Definition at line 106 of file page-allocator.cc.
                                                                            {
#ifdef V8_OS_LINUX
  void* ptr =
      base::OS::AllocateShared(size, base::OS::MemoryPermission::kReadWrite);
  CHECK_NOT_NULL(ptr);
  memcpy(ptr, original_address, size);
  bool success = base::OS::SetPermissions(
      ptr, size, base::OS::MemoryPermission::kReadWrite);
  CHECK(success);
  auto shared_memory =
      std::make_unique<v8::base::SharedMemory>(this, ptr, size);
  return shared_memory;
#else
  return {};
#endif
}
References v8::base::OS::AllocateShared(), CHECK, CHECK_NOT_NULL, v8::base::OS::kReadWrite, v8::base::OS::SetPermissions(), and size().
CanAllocateSharedPages()
bool v8::base::PageAllocator::CanAllocateSharedPages () [override]
Definition at line 97 of file page-allocator.cc.
                                           {
#ifdef V8_OS_LINUX
  return true;
#else
  return false;
#endif
}
CommitPageSize()
size_t v8::base::PageAllocator::CommitPageSize () [inline], [override]
Definition at line 27 of file page-allocator.h.
{ return commit_page_size_; }
DecommitPages()
bool v8::base::PageAllocator::DecommitPages (void * address, size_t size) [override]
Definition at line 161 of file page-allocator.cc.
                                                            {
  return base::OS::DecommitPages(address, size);
}
References v8::base::OS::DecommitPages(), and size().
DiscardSystemPages()
bool v8::base::PageAllocator::DiscardSystemPages (void * address, size_t size) [override]
Definition at line 157 of file page-allocator.cc.
                                                                 {
  return base::OS::DiscardSystemPages(address, size);
}
References v8::base::OS::DiscardSystemPages(), and size().
FreePages()
bool v8::base::PageAllocator::FreePages (void * address, size_t size) [override]
Definition at line 133 of file page-allocator.cc.
                                                        {
  base::OS::Free(address, size);
  return true;
}
References v8::base::OS::Free(), and size().
Referenced by v8::base::SharedMemory::~SharedMemory(), and v8::base::SharedMemoryMapping::~SharedMemoryMapping().
GetRandomMmapAddr()
void * v8::base::PageAllocator::GetRandomMmapAddr () [override]
Definition at line 41 of file page-allocator.cc.
                                       {
  return base::OS::GetRandomMmapAddr();
}
References v8::base::OS::GetRandomMmapAddr().
RecommitPages()
bool v8::base::PageAllocator::RecommitPages (void * address, size_t size, PageAllocator::Permission access) [override]
Definition at line 151 of file page-allocator.cc.
                                                                  {
  return base::OS::RecommitPages(
      address, size, static_cast<base::OS::MemoryPermission>(access));
}
References v8::base::OS::RecommitPages(), and size().
ReleasePages()
bool v8::base::PageAllocator::ReleasePages (void * address, size_t size, size_t new_size) [override]
Definition at line 138 of file page-allocator.cc.
                                                                            {
  DCHECK_LT(new_size, size);
  base::OS::Release(reinterpret_cast<uint8_t*>(address) + new_size,
                    size - new_size);
  return true;
}
References DCHECK_LT, v8::base::OS::Release(), and size().
RemapShared()
void * v8::base::PageAllocator::RemapShared (void * old_address, void * new_address, size_t size) [private]
Definition at line 124 of file page-allocator.cc.
                                              {
#ifdef V8_OS_LINUX
  return base::OS::RemapShared(old_address, new_address, size);
#else
  return nullptr;
#endif
}
References v8::base::OS::RemapShared(), and size().
Referenced by v8::base::SharedMemory::RemapTo().
SealPages()
bool v8::base::PageAllocator::SealPages (void * address, size_t size) [override]
Definition at line 165 of file page-allocator.cc.
                                                        {
  return base::OS::SealPages(address, size);
}
References v8::base::OS::SealPages(), and size().
SetPermissions()
bool v8::base::PageAllocator::SetPermissions (void * address, size_t size, PageAllocator::Permission access) [override]
Definition at line 145 of file page-allocator.cc.
                                                                   {
  return base::OS::SetPermissions(
      address, size, static_cast<base::OS::MemoryPermission>(access));
}
References v8::base::OS::SetPermissions(), and size().
SetRandomMmapSeed()
void v8::base::PageAllocator::SetRandomMmapSeed (int64_t seed) [override]
Definition at line 37 of file page-allocator.cc.
                                                  {
  base::OS::SetRandomMmapSeed(seed);
}
References v8::base::OS::SetRandomMmapSeed().
Friends And Related Function Documentation
v8::base::SharedMemory
friend class v8::base::SharedMemory [friend]
Definition at line 58 of file page-allocator.h.
Member Data Documentation
allocate_page_size_
const size_t v8::base::PageAllocator::allocate_page_size_ [private]
Definition at line 62 of file page-allocator.h.
commit_page_size_
const size_t v8::base::PageAllocator::commit_page_size_ [private]
Definition at line 63 of file page-allocator.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/page-allocator.h
/mnt/V8SourceCode/src/base/page-allocator.cc