v8::internal::Utf8ExternalStreamingStream Class Reference
Classes
struct Chunk
struct Position
struct StreamPosition
Public Member Functions
Utf8ExternalStreamingStream (ScriptCompiler::ExternalSourceStream *source_stream)
~Utf8ExternalStreamingStream () final=default
bool can_access_heap () const final
bool can_be_cloned () const final
std::unique_ptr< Utf16CharacterStream > Clone () const override
Protected Member Functions
size_t FillBuffer (size_t position) final
Private Member Functions
Utf8ExternalStreamingStream (const Utf8ExternalStreamingStream &source_stream) V8_NOEXCEPT
bool SkipToPosition (size_t position)
void FillBufferFromCurrentChunk ()
bool FetchChunk ()
void SearchPosition (size_t position)
Chunk & GetChunk (size_t chunk_no)
Private Attributes
std::shared_ptr< std::vector< Chunk > > chunks_
Position current_
ScriptCompiler::ExternalSourceStream * source_stream_
Additional Inherited Members
Detailed Description
Definition at line 526 of file scanner-character-streams.cc.
Constructor & Destructor Documentation
Utf8ExternalStreamingStream() [1/2]
v8::internal::Utf8ExternalStreamingStream::Utf8ExternalStreamingStream (ScriptCompiler::ExternalSourceStream * source_stream) [inline]
Definition at line 528 of file scanner-character-streams.cc.
      : chunks_(std::make_shared<std::vector<Chunk>>()),
        current_({0, {0, 0, 0, unibrow::Utf8::State::kAccept}}),
        source_stream_(source_stream) {}
Referenced by Clone().
 Utf8ExternalStreamingStream()
v8::internal::Utf8ExternalStreamingStream::~Utf8ExternalStreamingStream () [final], [default]
Utf8ExternalStreamingStream() [2/2]
v8::internal::Utf8ExternalStreamingStream::Utf8ExternalStreamingStream (const Utf8ExternalStreamingStream & source_stream) [inline], [private]
Definition at line 578 of file scanner-character-streams.cc.
                  : chunks_(source_stream.chunks_),
                    current_({0, {0, 0, 0, unibrow::Utf8::State::kAccept}}),
                    source_stream_(nullptr) {}
Member Function Documentation
can_access_heap()
bool v8::internal::Utf8ExternalStreamingStream::can_access_heap () const [inline], [final], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 535 of file scanner-character-streams.cc.
{ return false; }
can_be_cloned()
bool v8::internal::Utf8ExternalStreamingStream::can_be_cloned () const [inline], [final], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 537 of file scanner-character-streams.cc.
{ return true; }
Clone()
std::unique_ptr<Utf16CharacterStream> v8::internal::Utf8ExternalStreamingStream::Clone () const [inline], [override], [virtual]
Implements v8::internal::Utf16CharacterStream.
Definition at line 539 of file scanner-character-streams.cc.
                                                             {
    return std::unique_ptr<Utf16CharacterStream>(
        new Utf8ExternalStreamingStream(*this));
  }
References Utf8ExternalStreamingStream().
FetchChunk()
bool v8::internal::Utf8ExternalStreamingStream::FetchChunk () [private]
Definition at line 737 of file scanner-character-streams.cc.
                                             {
  RCS_SCOPE(runtime_call_stats(), RuntimeCallCounterId::kGetMoreDataCallback);
  DCHECK_EQ(current_.chunk_no, chunks_->size());
  DCHECK(chunks_->empty() || chunks_->back().length != 0);
  // Clone Utf8ExternalStreamingStreams have a null source stream, and
  // therefore can't fetch any new data.
  DCHECK_NOT_NULL(source_stream_);
  // Utf8ExternalStreamingStreams that have been cloned are not allowed to fetch
  // any more.
  DCHECK_EQ(chunks_.use_count(), 1);
  const uint8_t* chunk = nullptr;
  size_t length = source_stream_->GetMoreData(&chunk);
  chunks_->emplace_back(chunk, length, current_.pos);
  return length > 0;
}
References v8::internal::Utf8ExternalStreamingStream::Position::chunk_no, chunks_, current_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::ScriptCompiler::ExternalSourceStream::GetMoreData(), v8::internal::length, v8::internal::Utf8ExternalStreamingStream::Position::pos, RCS_SCOPE, v8::internal::Utf16CharacterStream::runtime_call_stats(), and source_stream_.
Referenced by FillBuffer(), and SearchPosition().
FillBuffer()
size_t v8::internal::Utf8ExternalStreamingStream::FillBuffer (size_t position) [final], [protected], [virtual]
Implements v8::internal::BufferedUtf16CharacterStream.
Definition at line 836 of file scanner-character-streams.cc.
                                                              {
  buffer_cursor_ = buffer_;
  buffer_end_ = buffer_;
  SearchPosition(position);
  bool out_of_data = current_.chunk_no != chunks_->size() &&
                     GetChunk(current_.chunk_no).length == 0 &&
                     current_.pos.incomplete_char == 0;
  if (out_of_data) return 0;
  // Fill the buffer, until we have at least one char (or are out of data).
  // (The embedder might give us 1-byte blocks within a utf-8 char, so we
  // can't guarantee progress with one chunk. Thus we iterate.)
  while (!out_of_data && buffer_cursor_ == buffer_end_) {
    // At end of current data, but there might be more? Then fetch it.
    if (current_.chunk_no == chunks_->size()) {
      out_of_data = !FetchChunk();
    }
    FillBufferFromCurrentChunk();
  }
  DCHECK_EQ(current_.pos.chars - position,
            static_cast<size_t>(buffer_end_ - buffer_cursor_));
  return buffer_end_ - buffer_cursor_;
}
References v8::internal::BufferedUtf16CharacterStream::buffer_, v8::internal::Utf16CharacterStream::buffer_cursor_, v8::internal::Utf16CharacterStream::buffer_end_, v8::internal::Utf8ExternalStreamingStream::StreamPosition::chars, v8::internal::Utf8ExternalStreamingStream::Position::chunk_no, chunks_, current_, DCHECK_EQ, FetchChunk(), FillBufferFromCurrentChunk(), GetChunk(), v8::internal::Utf8ExternalStreamingStream::StreamPosition::incomplete_char, v8::internal::Utf8ExternalStreamingStream::Chunk::length, v8::internal::Utf8ExternalStreamingStream::Position::pos, and SearchPosition().
FillBufferFromCurrentChunk()
void v8::internal::Utf8ExternalStreamingStream::FillBufferFromCurrentChunk () [private]
Definition at line 648 of file scanner-character-streams.cc.
                                                             {
  DCHECK_LT(current_.chunk_no, chunks_->size());
  DCHECK_EQ(buffer_start_, buffer_cursor_);
  DCHECK_LT(buffer_end_ + 1, buffer_start_ + kBufferSize);
  const Chunk& chunk = GetChunk(current_.chunk_no);
  // The buffer_ is writable, but buffer_*_ members are const. So we get a
  // non-const pointer into buffer that points to the same char as buffer_end_.
  uint16_t* output_cursor = buffer_ + (buffer_end_ - buffer_start_);
  DCHECK_EQ(output_cursor, buffer_end_);
  unibrow::Utf8::State state = current_.pos.state;
  uint32_t incomplete_char = current_.pos.incomplete_char;
  // If the current chunk is the last (empty) chunk we'll have to process
  // any left-over, partial characters.
  if (chunk.length == 0) {
    unibrow::uchar t = unibrow::Utf8::ValueOfIncrementalFinish(&state);
    if (t != unibrow::Utf8::kBufferEmpty) {
      DCHECK_EQ(t, unibrow::Utf8::kBadChar);
      *output_cursor = static_cast<base::uc16>(t);
      buffer_end_++;
      current_.pos.chars++;
      current_.pos.incomplete_char = 0;
      current_.pos.state = state;
    }
    return;
  }
  size_t it = current_.pos.bytes - chunk.start.bytes;
  const uint8_t* cursor = chunk.data.get() + it;
  const uint8_t* end = chunk.data.get() + chunk.length;
  // Deal with possible BOM.
  if (V8_UNLIKELY(current_.pos.bytes < 3 && current_.pos.chars == 0)) {
    while (cursor < end) {
      unibrow::uchar t =
          unibrow::Utf8::ValueOfIncremental(&cursor, &state, &incomplete_char);
      if (V8_LIKELY(t < kUtf8Bom)) {
        *(output_cursor++) =
            static_cast<base::uc16>(t); // The most frequent case.
      } else if (t == unibrow::Utf8::kIncomplete) {
        continue;
      } else if (t == kUtf8Bom) {
        // BOM detected at beginning of the stream. Don't copy it.
      } else if (t <= unibrow::Utf16::kMaxNonSurrogateCharCode) {
        *(output_cursor++) = static_cast<base::uc16>(t);
      } else {
        *(output_cursor++) = unibrow::Utf16::LeadSurrogate(t);
        *(output_cursor++) = unibrow::Utf16::TrailSurrogate(t);
      }
      break;
    }
  }
  const uint16_t* max_buffer_end = buffer_start_ + kBufferSize;
  while (cursor < end && output_cursor + 1 < max_buffer_end) {
    unibrow::uchar t =
        unibrow::Utf8::ValueOfIncremental(&cursor, &state, &incomplete_char);
    if (V8_LIKELY(t <= unibrow::Utf16::kMaxNonSurrogateCharCode)) {
      *(output_cursor++) =
          static_cast<base::uc16>(t); // The most frequent case.
    } else if (t == unibrow::Utf8::kIncomplete) {
      continue;
    } else {
      *(output_cursor++) = unibrow::Utf16::LeadSurrogate(t);
      *(output_cursor++) = unibrow::Utf16::TrailSurrogate(t);
    }
    // Fast path for ascii sequences.
    size_t remaining = end - cursor;
    size_t max_buffer = max_buffer_end - output_cursor;
    int max_length = static_cast<int>(std::min(remaining, max_buffer));
    DCHECK_EQ(state, unibrow::Utf8::State::kAccept);
    int ascii_length = NonAsciiStart(cursor, max_length);
    CopyChars(output_cursor, cursor, ascii_length);
    cursor += ascii_length;
    output_cursor += ascii_length;
  }
  current_.pos.bytes = chunk.start.bytes + (cursor - chunk.data.get());
  current_.pos.chars += (output_cursor - buffer_end_);
  current_.pos.incomplete_char = incomplete_char;
  current_.pos.state = state;
  current_.chunk_no += (cursor == end);
  buffer_end_ = output_cursor;
}
References v8::internal::BufferedUtf16CharacterStream::buffer_, v8::internal::Utf16CharacterStream::buffer_cursor_, v8::internal::Utf16CharacterStream::buffer_end_, v8::internal::Utf16CharacterStream::buffer_start_, v8::internal::Utf8ExternalStreamingStream::StreamPosition::bytes, v8::internal::Utf8ExternalStreamingStream::StreamPosition::chars, v8::internal::Utf8ExternalStreamingStream::Position::chunk_no, chunks_, v8::internal::CopyChars(), current_, v8::internal::Utf8ExternalStreamingStream::Chunk::data, DCHECK_EQ, DCHECK_LT, v8::internal::compiler::end(), GetChunk(), v8::internal::Utf8ExternalStreamingStream::StreamPosition::incomplete_char, unibrow::Utf8::kBadChar, unibrow::Utf8::kBufferEmpty, v8::internal::BufferedUtf16CharacterStream::kBufferSize, unibrow::Utf8::kIncomplete, unibrow::Utf16::kMaxNonSurrogateCharCode, v8::internal::anonymous_namespace{scanner-character-streams.cc}::kUtf8Bom, unibrow::Utf16::LeadSurrogate(), v8::internal::Utf8ExternalStreamingStream::Chunk::length, v8::internal::NonAsciiStart(), v8::internal::Utf8ExternalStreamingStream::Position::pos, v8::internal::Utf8ExternalStreamingStream::Chunk::start, v8::internal::Utf8ExternalStreamingStream::StreamPosition::state, unibrow::Utf16::TrailSurrogate(), V8_LIKELY, V8_UNLIKELY, unibrow::Utf8::ValueOfIncremental(), and unibrow::Utf8::ValueOfIncrementalFinish().
Referenced by FillBuffer().
GetChunk()
Chunk& v8::internal::Utf8ExternalStreamingStream::GetChunk (size_t chunk_no) [inline], [private]
Definition at line 593 of file scanner-character-streams.cc.
{ return (*chunks_)[chunk_no]; }
References chunks_.
Referenced by FillBuffer(), FillBufferFromCurrentChunk(), SearchPosition(), and SkipToPosition().
SearchPosition()
void v8::internal::Utf8ExternalStreamingStream::SearchPosition (size_t position) [private]
Definition at line 756 of file scanner-character-streams.cc.
                                                                {
  // If current_ already points to the right position, we're done.
  //
  // This is expected to be the common case, since we typically call
  // FillBuffer right after the current buffer.
  if (current_.pos.chars == position) return;
  // No chunks. Fetch at least one, so we can assume !chunks_->empty() below.
  if (chunks_->empty()) {
    DCHECK_EQ(current_.chunk_no, 0u);
    DCHECK_EQ(current_.pos.bytes, 0u);
    DCHECK_EQ(current_.pos.chars, 0u);
    FetchChunk();
  }
  // Search for the last chunk whose start position is less or equal to
  // position.
  size_t chunk_no = chunks_->size() - 1;
  while (chunk_no > 0 && GetChunk(chunk_no).start.chars > position) {
    chunk_no--;
  }
  // Did we find the terminating (zero-length) chunk? Then we're seeking
  // behind the end of the data, and position does not exist.
  // Set current_ to point to the terminating chunk.
  if (GetChunk(chunk_no).length == 0) {
    current_ = {chunk_no, GetChunk(chunk_no).start};
    return;
  }
  // Did we find the non-last chunk? Then our position must be within chunk_no.
  if (chunk_no + 1 < chunks_->size()) {
    // Fancy-pants optimization for ASCII chunks within a utf-8 stream.
    // (Many web sites declare utf-8 encoding, but use only (or almost only) the
    // ASCII subset for their JavaScript sources. We can exploit this, by
    // checking whether the # bytes in a chunk are equal to the # chars, and if
    // so avoid the expensive SkipToPosition.)
    bool ascii_only_chunk =
        GetChunk(chunk_no).start.incomplete_char == 0 &&
        (GetChunk(chunk_no + 1).start.bytes - GetChunk(chunk_no).start.bytes) ==
            (GetChunk(chunk_no + 1).start.chars -
             GetChunk(chunk_no).start.chars);
    if (ascii_only_chunk) {
      size_t skip = position - GetChunk(chunk_no).start.chars;
      current_ = {chunk_no,
                  {GetChunk(chunk_no).start.bytes + skip,
                   GetChunk(chunk_no).start.chars + skip, 0,
                   unibrow::Utf8::State::kAccept}};
    } else {
      current_ = {chunk_no, GetChunk(chunk_no).start};
      SkipToPosition(position);
    }
    // Since position was within the chunk, SkipToPosition should have found
    // something.
    DCHECK_EQ(position, current_.pos.chars);
    return;
  }
  // What's left: We're in the last, non-terminating chunk. Our position
  // may be in the chunk, but it may also be in 'future' chunks, which we'll
  // have to obtain.
  DCHECK_EQ(chunk_no, chunks_->size() - 1);
  current_ = {chunk_no, GetChunk(chunk_no).start};
  bool have_more_data = true;
  bool found = SkipToPosition(position);
  while (have_more_data && !found) {
    DCHECK_EQ(current_.chunk_no, chunks_->size());
    have_more_data = FetchChunk();
    found = have_more_data && SkipToPosition(position);
  }
  // We'll return with a postion != the desired position only if we're out
  // of data. In that case, we'll point to the terminating chunk.
  DCHECK_EQ(found, current_.pos.chars == position);
  DCHECK_EQ(have_more_data, chunks_->back().length != 0);
  DCHECK_IMPLIES(!found, !have_more_data);
  DCHECK_IMPLIES(!found, current_.chunk_no == chunks_->size() - 1);
}
References v8::internal::Utf8ExternalStreamingStream::StreamPosition::bytes, v8::internal::Utf8ExternalStreamingStream::StreamPosition::chars, v8::internal::Utf8ExternalStreamingStream::Position::chunk_no, chunks_, current_, DCHECK_EQ, DCHECK_IMPLIES, FetchChunk(), GetChunk(), v8::internal::Utf8ExternalStreamingStream::StreamPosition::incomplete_char, v8::internal::length, v8::internal::Utf8ExternalStreamingStream::Position::pos, SkipToPosition(), and v8::internal::Utf8ExternalStreamingStream::Chunk::start.
Referenced by FillBuffer().
SkipToPosition()
bool v8::internal::Utf8ExternalStreamingStream::SkipToPosition (size_t position) [private]
Definition at line 600 of file scanner-character-streams.cc.
                                                                {
  DCHECK_LE(current_.pos.chars, position); // We can only skip forward.
  // Already there? Then return immediately.
  if (current_.pos.chars == position) return true;
  const Chunk& chunk = GetChunk(current_.chunk_no);
  DCHECK(current_.pos.bytes >= chunk.start.bytes);
  unibrow::Utf8::State state = chunk.start.state;
  uint32_t incomplete_char = chunk.start.incomplete_char;
  size_t it = current_.pos.bytes - chunk.start.bytes;
  const uint8_t* cursor = &chunk.data.get()[it];
  const uint8_t* end = &chunk.data.get()[chunk.length];
  size_t chars = current_.pos.chars;
  if (V8_UNLIKELY(current_.pos.bytes < 3 && chars == 0)) {
    while (cursor < end) {
      unibrow::uchar t =
          unibrow::Utf8::ValueOfIncremental(&cursor, &state, &incomplete_char);
      if (t == unibrow::Utf8::kIncomplete) continue;
      if (t != kUtf8Bom) {
        chars++;
        if (t > unibrow::Utf16::kMaxNonSurrogateCharCode) chars++;
      }
      break;
    }
  }
  while (cursor < end && chars < position) {
    unibrow::uchar t =
        unibrow::Utf8::ValueOfIncremental(&cursor, &state, &incomplete_char);
    if (t != unibrow::Utf8::kIncomplete) {
      chars++;
      if (t > unibrow::Utf16::kMaxNonSurrogateCharCode) chars++;
    }
  }
  current_.pos.bytes = chunk.start.bytes + (cursor - chunk.data.get());
  current_.pos.chars = chars;
  current_.pos.incomplete_char = incomplete_char;
  current_.pos.state = state;
  current_.chunk_no += (cursor == end);
  return current_.pos.chars == position;
}
References v8::internal::Utf8ExternalStreamingStream::StreamPosition::bytes, v8::internal::Utf8ExternalStreamingStream::StreamPosition::chars, v8::internal::Utf8ExternalStreamingStream::Position::chunk_no, current_, v8::internal::Utf8ExternalStreamingStream::Chunk::data, v8::internal::DCHECK(), DCHECK_LE, v8::internal::compiler::end(), GetChunk(), v8::internal::Utf8ExternalStreamingStream::StreamPosition::incomplete_char, unibrow::Utf8::kIncomplete, unibrow::Utf16::kMaxNonSurrogateCharCode, v8::internal::anonymous_namespace{scanner-character-streams.cc}::kUtf8Bom, v8::internal::Utf8ExternalStreamingStream::Chunk::length, v8::internal::Utf8ExternalStreamingStream::Position::pos, v8::internal::Utf8ExternalStreamingStream::Chunk::start, v8::internal::Utf8ExternalStreamingStream::StreamPosition::state, V8_UNLIKELY, and unibrow::Utf8::ValueOfIncremental().
Referenced by SearchPosition().
Member Data Documentation
chunks_
std::shared_ptr<std::vector<Chunk> > v8::internal::Utf8ExternalStreamingStream::chunks_ [private]
Definition at line 595 of file scanner-character-streams.cc.
Referenced by FetchChunk(), FillBuffer(), FillBufferFromCurrentChunk(), GetChunk(), and SearchPosition().
current_
Position v8::internal::Utf8ExternalStreamingStream::current_ [private]
Definition at line 596 of file scanner-character-streams.cc.
Referenced by FetchChunk(), FillBuffer(), FillBufferFromCurrentChunk(), SearchPosition(), and SkipToPosition().
source_stream_
ScriptCompiler::ExternalSourceStream* v8::internal::Utf8ExternalStreamingStream::source_stream_ [private]
Definition at line 597 of file scanner-character-streams.cc.
Referenced by FetchChunk().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/scanner-character-streams.cc