v8::internal::OptimizedCompilationInfo Class Reference
#include <optimized-compilation-info.h>
Classes
struct InlinedFunctionHolder
Public Types
enum Flag
using InlinedFunctionList = std::vector< InlinedFunctionHolder >
Public Member Functions
OptimizedCompilationInfo (Zone *zone, Isolate *isolate, IndirectHandle< SharedFunctionInfo > shared, IndirectHandle< JSFunction > closure, CodeKind code_kind, BytecodeOffset osr_offset)
OptimizedCompilationInfo (Zone *zone, Isolate *isolate, IndirectHandle< SharedFunctionInfo > shared, IndirectHandle< JSFunction > closure, CodeKind code_kind)
OptimizedCompilationInfo (base::Vector< const char > debug_name, Zone *zone, CodeKind code_kind, Builtin builtin=Builtin::kNoBuiltinId)
OptimizedCompilationInfo (const OptimizedCompilationInfo &)=delete
OptimizedCompilationInfo & operator= (const OptimizedCompilationInfo &)=delete
~OptimizedCompilationInfo ()
Zone * zone ()
bool is_osr () const
IndirectHandle< SharedFunctionInfo > shared_info () const
bool has_shared_info () const
IndirectHandle< BytecodeArray > bytecode_array () const
bool has_bytecode_array () const
IndirectHandle< JSFunction > closure () const
IndirectHandle< Code > code () const
CodeKind code_kind () const
Builtin builtin () const
void set_builtin (Builtin builtin)
BytecodeOffset osr_offset () const
void SetNodeObserver (compiler::NodeObserver *observer)
compiler::NodeObserver * node_observer () const
void SetCode (IndirectHandle< Code > code)
bool has_context () const
Tagged< Context > context () const
bool has_native_context () const
Tagged< NativeContext > native_context () const
bool has_global_object () const
Tagged< JSGlobalObject > global_object () const
bool IsOptimizing () const
void set_persistent_handles (std::unique_ptr< PersistentHandles > persistent_handles)
void set_canonical_handles (std::unique_ptr< CanonicalHandlesMap > canonical_handles)
template<typename T >
IndirectHandle< T > CanonicalHandle (Tagged< T > object, Isolate *isolate)
void ReopenAndCanonicalizeHandlesInNewScope (Isolate *isolate)
void AbortOptimization (BailoutReason reason)
void RetryOptimization (BailoutReason reason)
BailoutReason bailout_reason () const
int optimization_id () const
unsigned inlined_bytecode_size () const
void set_inlined_bytecode_size (unsigned size)
InlinedFunctionList & inlined_functions ()
int AddInlinedFunction (IndirectHandle< SharedFunctionInfo > inlined_function, IndirectHandle< BytecodeArray > inlined_bytecode, SourcePosition pos)
std::unique_ptr< char[]> GetDebugName () const
StackFrame::Type GetOutputStackFrameType () const
const char * trace_turbo_filename () const
void set_trace_turbo_filename (std::unique_ptr< char[]> filename)
TickCounter & tick_counter ()
bool was_cancelled () const
void mark_cancelled ()
BasicBlockProfilerData * profiler_data () const
void set_profiler_data (BasicBlockProfilerData *profiler_data)
std::unique_ptr< PersistentHandles > DetachPersistentHandles ()
std::unique_ptr< CanonicalHandlesMap > DetachCanonicalHandles ()
Private Member Functions
void ConfigureFlags ()
void SetFlag (Flag flag)
bool GetFlag (Flag flag) const
void SetTracingFlags (bool passes_filter)
CanonicalHandlesMap * canonical_handles ()
Private Attributes
unsigned flags_ = 0
Isolate *const isolate_unsafe_
const CodeKind code_kind_
Builtin builtin_ = Builtin::kNoBuiltinId
IndirectHandle< BytecodeArray > bytecode_array_
IndirectHandle< SharedFunctionInfo > shared_info_
IndirectHandle< JSFunction > closure_
IndirectHandle< Code > code_
BasicBlockProfilerData * profiler_data_ = nullptr
const BytecodeOffset osr_offset_ = BytecodeOffset::None()
Zone *const zone_
compiler::NodeObserver * node_observer_ = nullptr
BailoutReason bailout_reason_ = BailoutReason::kNoReason
InlinedFunctionList inlined_functions_
const int optimization_id_
unsigned inlined_bytecode_size_ = 0
base::Vector< const char > debug_name_
std::unique_ptr< char[]> trace_turbo_filename_
TickCounter tick_counter_
std::atomic< bool > was_cancelled_ = false
std::unique_ptr< PersistentHandles > ph_
std::unique_ptr< CanonicalHandlesMap > canonical_handles_
Static Private Attributes
static constexpr int kNoOptimizationId = -1
Friends
class compiler::JSHeapBroker
Detailed Description
Definition at line 54 of file optimized-compilation-info.h.
Member Typedef Documentation
InlinedFunctionList
using v8::internal::OptimizedCompilationInfo::InlinedFunctionList = std::vector<InlinedFunctionHolder>
Definition at line 236 of file optimized-compilation-info.h.
Member Enumeration Documentation
Flag
enum v8::internal::OptimizedCompilationInfo::Flag
Definition at line 82 of file optimized-compilation-info.h.
            {
#define DEF_ENUM(Camel, Lower, Bit) k##Camel = 1 << Bit,
    FLAGS(DEF_ENUM)
#undef DEF_ENUM
  };
Constructor & Destructor Documentation
OptimizedCompilationInfo() [1/4]
v8::internal::OptimizedCompilationInfo::OptimizedCompilationInfo (Zone * zone, Isolate * isolate, IndirectHandle< SharedFunctionInfo > shared, IndirectHandle< JSFunction > closure, CodeKind code_kind, BytecodeOffset osr_offset)
Definition at line 24 of file optimized-compilation-info.cc.
    : isolate_unsafe_(isolate),
      code_kind_(code_kind),
      osr_offset_(osr_offset),
      zone_(zone),
      optimization_id_(isolate->NextOptimizationId()) {
  DCHECK_EQ(*shared, closure->shared());
  DCHECK(shared->is_compiled());
  DCHECK_IMPLIES(is_osr(), IsOptimizing());
  bytecode_array_ = handle(shared->GetBytecodeArray(isolate), isolate);
  shared_info_ = shared;
  closure_ = closure;
  canonical_handles_ = std::make_unique<CanonicalHandlesMap>(
      isolate->heap(), ZoneAllocationPolicy(zone));
  // Collect source positions for optimized code when profiling or if debugger
  // is active, to be able to get more precise source positions at the price of
  // more memory consumption.
  if (isolate->NeedsDetailedOptimizedCodeLineInfo()) {
    // We might not have source positions if collection fails (e.g. because we
    // run out of stack space).
    if (bytecode_array_->HasSourcePositionTable()) {
      set_source_positions();
    }
  }
  SetTracingFlags(shared->PassesFilter(v8_flags.trace_turbo_filter));
  ConfigureFlags();
  if (isolate->node_observer()) {
    SetNodeObserver(isolate->node_observer());
  }
}
References bytecode_array_, canonical_handles_, closure(), closure_, ConfigureFlags(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::handle(), v8::internal::Isolate::heap(), is_osr(), IsOptimizing(), v8::internal::Isolate::NeedsDetailedOptimizedCodeLineInfo(), SetNodeObserver(), SetTracingFlags(), shared_info_, v8::internal::v8_flags, and zone().
OptimizedCompilationInfo() [2/4]
v8::internal::OptimizedCompilationInfo::OptimizedCompilationInfo (Zone * zone, Isolate * isolate, IndirectHandle< SharedFunctionInfo > shared, IndirectHandle< JSFunction > closure, CodeKind code_kind) [inline]
Definition at line 108 of file optimized-compilation-info.h.
      : OptimizedCompilationInfo(zone, isolate, shared, closure, code_kind,
                                 BytecodeOffset::None()) {}
OptimizedCompilationInfo() [3/4]
v8::internal::OptimizedCompilationInfo::OptimizedCompilationInfo (base::Vector< const char > debug_name, Zone * zone, CodeKind code_kind, Builtin builtin = Builtin::kNoBuiltinId)
Definition at line 61 of file optimized-compilation-info.cc.
    : isolate_unsafe_(nullptr),
      code_kind_(code_kind),
      builtin_(builtin),
      zone_(zone),
      optimization_id_(kNoOptimizationId),
      debug_name_(debug_name) {
  DCHECK_IMPLIES(builtin_ != Builtin::kNoBuiltinId,
                 (code_kind_ == CodeKind::BUILTIN ||
                  code_kind_ == CodeKind::BYTECODE_HANDLER));
  SetTracingFlags(
      PassesFilter(debug_name, base::CStrVector(v8_flags.trace_turbo_filter)));
  ConfigureFlags();
  DCHECK(!has_shared_info());
}
References BUILTIN, builtin_, code_kind_, ConfigureFlags(), v8::base::CStrVector(), v8::internal::DCHECK(), DCHECK_IMPLIES, has_shared_info(), v8::internal::kNoBuiltinId, v8::internal::PassesFilter(), SetTracingFlags(), and v8::internal::v8_flags.
OptimizedCompilationInfo() [4/4]
v8::internal::OptimizedCompilationInfo::OptimizedCompilationInfo (const OptimizedCompilationInfo &) [delete]
 OptimizedCompilationInfo()
v8::internal::OptimizedCompilationInfo::~OptimizedCompilationInfo ()
Definition at line 131 of file optimized-compilation-info.cc.
                                                    {
  if (disable_future_optimization() && has_shared_info()) {
    DCHECK_NOT_NULL(isolate_unsafe_);
    shared_info()->DisableOptimization(isolate_unsafe_, bailout_reason());
  }
}
References bailout_reason(), DCHECK_NOT_NULL, has_shared_info(), isolate_unsafe_, and shared_info().
Member Function Documentation
AbortOptimization()
void v8::internal::OptimizedCompilationInfo::AbortOptimization (BailoutReason reason)
Definition at line 152 of file optimized-compilation-info.cc.
                                                                     {
  DCHECK_NE(reason, BailoutReason::kNoReason);
  if (bailout_reason_ == BailoutReason::kNoReason) {
    bailout_reason_ = reason;
  }
  if (IsTerminalBailoutReasonForTurbofan(reason)) {
    set_disable_future_optimization();
  }
}
References bailout_reason_, DCHECK_NE, and v8::internal::IsTerminalBailoutReasonForTurbofan().
Referenced by v8::internal::TurbofanCompilationJob::AbortOptimization().
AddInlinedFunction()
int v8::internal::OptimizedCompilationInfo::AddInlinedFunction (IndirectHandle< SharedFunctionInfo > inlined_function, IndirectHandle< BytecodeArray > inlined_bytecode, SourcePosition pos)
Definition at line 235 of file optimized-compilation-info.cc.
                                                                        {
  int id = static_cast<int>(inlined_functions_.size());
  inlined_functions_.push_back(
      InlinedFunctionHolder(inlined_function, inlined_bytecode, pos));
  return id;
}
References inlined_functions_.
Referenced by v8::internal::compiler::JSInliner::ReduceJSCall().
bailout_reason()
BailoutReason v8::internal::OptimizedCompilationInfo::bailout_reason () const [inline]
Definition at line 208 of file optimized-compilation-info.h.
{ return bailout_reason_; }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceAbortedJob(), and ~OptimizedCompilationInfo().
builtin()
Builtin v8::internal::OptimizedCompilationInfo::builtin () const [inline]
Definition at line 137 of file optimized-compilation-info.h.
{ return builtin_; }
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::compiler::CodeGenerator::FinalizeCode(), v8::internal::compiler::CodeAssemblerCompilationJob::FinalizeJobImpl(), v8::internal::compiler::Pipeline::GenerateCodeForTurboshaftBuiltin(), v8::internal::compiler::TFPipelineData::InitializeCodeGenerator(), v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl(), v8::internal::compiler::turboshaft::CsaEffectsComputationPhase::Run(), and v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph().
bytecode_array()
IndirectHandle<BytecodeArray> v8::internal::OptimizedCompilationInfo::bytecode_array () const [inline]
Definition at line 130 of file optimized-compilation-info.h.
                                                       {
    return bytecode_array_;
  }
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::compiler::Linkage::ComputeIncoming(), v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), v8::internal::compiler::PipelineImpl::InitializeHeapBroker(), and v8::internal::compiler::JsonPrintAllBytecodeSources().
canonical_handles()
CanonicalHandlesMap* v8::internal::OptimizedCompilationInfo::canonical_handles () [inline], [private]
Definition at line 292 of file optimized-compilation-info.h.
{ return canonical_handles_.get(); }
CanonicalHandle()
template<typename T >
IndirectHandle<T> v8::internal::OptimizedCompilationInfo::CanonicalHandle (Tagged< T > object, Isolate * isolate) [inline]
Definition at line 192 of file optimized-compilation-info.h.
                                                                        {
    DCHECK_NOT_NULL(canonical_handles_);
    DCHECK(PersistentHandlesScope::IsActive(isolate));
    auto find_result = canonical_handles_->FindOrInsert(object);
    if (!find_result.already_exists) {
      *find_result.entry = IndirectHandle<T>(object, isolate).location();
    }
    return IndirectHandle<T>(*find_result.entry);
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::PersistentHandlesScope::IsActive(), and v8::internal::HandleBase::location().
Referenced by v8::internal::compiler::GetModuleContext(), and ReopenAndCanonicalizeHandlesInNewScope().
closure()
IndirectHandle<JSFunction> v8::internal::OptimizedCompilationInfo::closure () const [inline]
Definition at line 134 of file optimized-compilation-info.h.
{ return closure_; }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_Concurrent(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), v8::internal::compiler::Linkage::ComputeIncoming(), context(), v8::internal::Compiler::DisposeTurbofanCompilationJob(), v8::internal::Compiler::FinalizeTurbofanCompilationJob(), v8::internal::compiler::GetModuleContext(), has_context(), has_native_context(), v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions(), v8::internal::compiler::JsonPrintAllBytecodeSources(), native_context(), OptimizedCompilationInfo(), and v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::PrintTracePrefix().
code()
IndirectHandle<Code> v8::internal::OptimizedCompilationInfo::code () const [inline]
Definition at line 135 of file optimized-compilation-info.h.
{ return code_; }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), v8::internal::wasm::JSToWasmWrapperCompilationUnit::Finalize(), v8::internal::Compiler::FinalizeTurbofanCompilationJob(), and SetCode().
code_kind()
CodeKind v8::internal::OptimizedCompilationInfo::code_kind () const [inline]
Definition at line 136 of file optimized-compilation-info.h.
{ return code_kind_; }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_Concurrent(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), v8::internal::compiler::CodeGenerator::DetermineStubCallMode(), GetOutputStackFrameType(), v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::PrintTracePrefix(), v8::internal::compiler::JSInliner::ReduceJSCall(), and SetCode().
ConfigureFlags()
void v8::internal::OptimizedCompilationInfo::ConfigureFlags () [private]
Definition at line 79 of file optimized-compilation-info.cc.
                                              {
  if (v8_flags.turbo_inline_js_wasm_calls) set_inline_js_wasm_calls();
  if (v8_flags.cet_compatible) {
    set_shadow_stack_compliant_lazy_deopt();
  }
  switch (code_kind_) {
    case CodeKind::TURBOFAN_JS:
      set_called_with_code_start_register();
      set_switch_jump_table();
      if (v8_flags.analyze_environment_liveness) {
        set_analyze_environment_liveness();
      }
      if (v8_flags.turbo_splitting) set_splitting();
      break;
    case CodeKind::BYTECODE_HANDLER:
      set_called_with_code_start_register();
#ifdef V8_ENABLE_BUILTIN_JUMP_TABLE_SWITCH
      set_switch_jump_table();
#endif // V8_ENABLE_BUILTIN_JUMP_TABLE_SWITCH
      if (v8_flags.turbo_splitting) set_splitting();
      if (v8_flags.enable_allocation_folding) set_allocation_folding();
      break;
    case CodeKind::BUILTIN:
#ifdef V8_ENABLE_BUILTIN_JUMP_TABLE_SWITCH
      set_switch_jump_table();
#endif // V8_ENABLE_BUILTIN_JUMP_TABLE_SWITCH
      [[fallthrough]];
    case CodeKind::FOR_TESTING:
      if (v8_flags.turbo_splitting) set_splitting();
      if (v8_flags.enable_allocation_folding) set_allocation_folding();
#if ENABLE_GDB_JIT_INTERFACE && DEBUG
      set_source_positions();
#endif // ENABLE_GDB_JIT_INTERFACE && DEBUG
      break;
    case CodeKind::WASM_FUNCTION:
    case CodeKind::WASM_TO_CAPI_FUNCTION:
      set_switch_jump_table();
      break;
    case CodeKind::C_WASM_ENTRY:
    case CodeKind::JS_TO_WASM_FUNCTION:
    case CodeKind::WASM_TO_JS_FUNCTION:
      break;
    case CodeKind::BASELINE:
    case CodeKind::MAGLEV:
    case CodeKind::INTERPRETED_FUNCTION:
    case CodeKind::REGEXP:
      UNREACHABLE();
  }
}
References BUILTIN, code_kind_, v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by OptimizedCompilationInfo().
context()
Tagged< Context > v8::internal::OptimizedCompilationInfo::context () const
Definition at line 212 of file optimized-compilation-info.cc.
                                                        {
  DCHECK(has_context());
  return closure()->context();
}
References closure(), v8::internal::DCHECK(), and has_context().
DetachCanonicalHandles()
std::unique_ptr<CanonicalHandlesMap> v8::internal::OptimizedCompilationInfo::DetachCanonicalHandles () [inline]
Definition at line 274 of file optimized-compilation-info.h.
                                                              {
    DCHECK_NOT_NULL(canonical_handles_);
    return std::move(canonical_handles_);
  }
References DCHECK_NOT_NULL.
DetachPersistentHandles()
std::unique_ptr<PersistentHandles> v8::internal::OptimizedCompilationInfo::DetachPersistentHandles () [inline]
Definition at line 269 of file optimized-compilation-info.h.
                                                             {
    DCHECK_NOT_NULL(ph_);
    return std::move(ph_);
  }
References DCHECK_NOT_NULL.
Referenced by v8::internal::compiler::JSHeapBroker::AttachLocalIsolate().
GetDebugName()
std::unique_ptr< char[]> v8::internal::OptimizedCompilationInfo::GetDebugName () const
Definition at line 168 of file optimized-compilation-info.cc.
                                                                   {
  if (!shared_info().is_null()) {
    return shared_info()->DebugNameCStr();
  }
  base::Vector<const char> name_vec = debug_name_;
  if (name_vec.empty()) name_vec = base::ArrayVector("unknown");
  std::unique_ptr<char[]> name(new char[name_vec.length() + 1]);
  memcpy(name.get(), name_vec.begin(), name_vec.length());
  name[name_vec.length()] = '\0';
  return name;
}
References v8::base::ArrayVector(), v8::base::Vector< T >::begin(), debug_name_, v8::base::Vector< T >::empty(), v8::base::Vector< T >::length(), v8::internal::name, and shared_info().
Referenced by v8::internal::compiler::anonymous_namespace{pipeline.cc}::CreatePipelineStatistics(), v8::internal::wasm::JSToWasmWrapperCompilationUnit::Finalize(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), v8::internal::compiler::GetVisualizerLogFileName(), v8::internal::compiler::BasicBlockInstrumentor::Instrument(), v8::internal::compiler::CodeAssemblerCompilationJob::PrepareJobImpl(), v8::internal::compiler::PrintCode(), and v8::internal::compiler::GraphC1Visualizer::PrintCompilation().
GetFlag()
bool v8::internal::OptimizedCompilationInfo::GetFlag (Flag flag) const [inline], [private]
Definition at line 283 of file optimized-compilation-info.h.
{ return (flags_ & flag) != 0; }
GetOutputStackFrameType()
StackFrame::Type v8::internal::OptimizedCompilationInfo::GetOutputStackFrameType () const
Definition at line 180 of file optimized-compilation-info.cc.
                                                                       {
  switch (code_kind()) {
    case CodeKind::FOR_TESTING:
    case CodeKind::BYTECODE_HANDLER:
    case CodeKind::BUILTIN:
      return StackFrame::STUB;
#if V8_ENABLE_WEBASSEMBLY
    case CodeKind::WASM_FUNCTION:
      return StackFrame::WASM;
    case CodeKind::WASM_TO_CAPI_FUNCTION:
      return StackFrame::WASM_EXIT;
    case CodeKind::JS_TO_WASM_FUNCTION:
      return StackFrame::JS_TO_WASM;
    case CodeKind::WASM_TO_JS_FUNCTION:
      return StackFrame::WASM_TO_JS;
    case CodeKind::C_WASM_ENTRY:
      return StackFrame::C_WASM_ENTRY;
#endif // V8_ENABLE_WEBASSEMBLY
    default:
      UNIMPLEMENTED();
  }
}
References BUILTIN, code_kind(), and v8::internal::UNIMPLEMENTED().
global_object()
Tagged< JSGlobalObject > v8::internal::OptimizedCompilationInfo::global_object () const
Definition at line 230 of file optimized-compilation-info.cc.
                                                                     {
  DCHECK(has_global_object());
  return native_context()->global_object();
}
References v8::internal::DCHECK(), has_global_object(), and native_context().
has_bytecode_array()
bool v8::internal::OptimizedCompilationInfo::has_bytecode_array () const [inline]
Definition at line 133 of file optimized-compilation-info.h.
{ return !bytecode_array_.is_null(); }
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::compiler::Linkage::ComputeIncoming(), and v8::internal::compiler::PipelineImpl::InitializeHeapBroker().
has_context()
bool v8::internal::OptimizedCompilationInfo::has_context () const
Definition at line 208 of file optimized-compilation-info.cc.
                                                 {
  return !closure().is_null();
}
References closure().
Referenced by context().
has_global_object()
bool v8::internal::OptimizedCompilationInfo::has_global_object () const
Definition at line 226 of file optimized-compilation-info.cc.
                                                       {
  return has_native_context();
}
References has_native_context().
Referenced by global_object().
has_native_context()
bool v8::internal::OptimizedCompilationInfo::has_native_context () const
Definition at line 217 of file optimized-compilation-info.cc.
                                                        {
  return !closure().is_null() && !closure()->native_context().is_null();
}
References closure().
Referenced by has_global_object(), and native_context().
has_shared_info()
bool v8::internal::OptimizedCompilationInfo::has_shared_info () const [inline]
Definition at line 129 of file optimized-compilation-info.h.
{ return !shared_info().is_null(); }
Referenced by v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), v8::internal::compiler::GetVisualizerLogFileName(), OptimizedCompilationInfo(), v8::internal::compiler::TurbofanPipelineStatistics::TurbofanPipelineStatistics(), and ~OptimizedCompilationInfo().
inlined_bytecode_size()
unsigned v8::internal::OptimizedCompilationInfo::inlined_bytecode_size () const [inline]
Definition at line 215 of file optimized-compilation-info.h.
{ return inlined_bytecode_size_; }
inlined_functions()
InlinedFunctionList& v8::internal::OptimizedCompilationInfo::inlined_functions () [inline]
Definition at line 237 of file optimized-compilation-info.h.
{ return inlined_functions_; }
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::compiler::anonymous_namespace{code-generator.cc}::CreateInliningPositions(), v8::internal::SourcePosition::InliningStack(), v8::internal::compiler::JsonPrintAllBytecodeSources(), v8::internal::compiler::JsonPrintAllSourceWithPositions(), and v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintParticipatingSource().
is_osr()
bool v8::internal::OptimizedCompilationInfo::is_osr () const [inline]
Definition at line 125 of file optimized-compilation-info.h.
{ return !osr_offset_.IsNone(); }
Referenced by v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::AdjustStackPointerForTailCall(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), v8::internal::compiler::Linkage::ComputeIncoming(), v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions(), OptimizedCompilationInfo(), v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl(), v8::internal::TurbofanCompilationJob::RecordCompilationStats(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceAbortedJob(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceCompletedJob(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceFinishTurbofanCompile(), and v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TracePrepareJob().
IsOptimizing()
bool v8::internal::OptimizedCompilationInfo::IsOptimizing () const [inline]
Definition at line 160 of file optimized-compilation-info.h.
                            {
    return CodeKindIsOptimizedJSFunction(code_kind());
  }
References v8::internal::CodeKindIsOptimizedJSFunction().
Referenced by v8::internal::TurbofanCompilationJob::AbortOptimization(), v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::compiler::CodeGenerator::AssembleSourcePosition(), v8::internal::compiler::Linkage::ComputeIncoming(), v8::internal::compiler::GetVisualizerLogFileName(), OptimizedCompilationInfo(), v8::internal::compiler::PrintCode(), v8::internal::compiler::GraphC1Visualizer::PrintCompilation(), v8::internal::TurbofanCompilationJob::RetryOptimization(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceFinishTurbofanCompile(), and v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TracePrepareJob().
mark_cancelled()
void v8::internal::OptimizedCompilationInfo::mark_cancelled ()
Definition at line 254 of file optimized-compilation-info.cc.
                                              {
  was_cancelled_.store(true, std::memory_order_relaxed);
}
References was_cancelled_.
Referenced by v8::internal::TurbofanCompilationJob::Cancel().
native_context()
Tagged< NativeContext > v8::internal::OptimizedCompilationInfo::native_context () const
Definition at line 221 of file optimized-compilation-info.cc.
                                                                     {
  DCHECK(has_native_context());
  return closure()->native_context();
}
References closure(), v8::internal::DCHECK(), and has_native_context().
Referenced by global_object().
node_observer()
compiler::NodeObserver* v8::internal::OptimizedCompilationInfo::node_observer () const [inline]
Definition at line 144 of file optimized-compilation-info.h.
{ return node_observer_; }
Referenced by v8::internal::compiler::TFPipelineData::TFPipelineData().
operator=()
OptimizedCompilationInfo& v8::internal::OptimizedCompilationInfo::operator= (const OptimizedCompilationInfo &) [delete]
optimization_id()
int v8::internal::OptimizedCompilationInfo::optimization_id () const [inline]
Definition at line 210 of file optimized-compilation-info.h.
                              {
    DCHECK(IsOptimizing());
    return optimization_id_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), v8::internal::compiler::GetVisualizerLogFileName(), v8::internal::compiler::PrintCode(), v8::internal::compiler::GraphC1Visualizer::PrintCompilation(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintFunctionSource(), and v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintInlinedFunctionInfo().
osr_offset()
BytecodeOffset v8::internal::OptimizedCompilationInfo::osr_offset () const [inline]
Definition at line 139 of file optimized-compilation-info.h.
{ return osr_offset_; }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_Concurrent(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_NotConcurrent(), v8::internal::Compiler::DisposeTurbofanCompilationJob(), v8::internal::Compiler::FinalizeTurbofanCompilationJob(), and v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData().
profiler_data()
BasicBlockProfilerData* v8::internal::OptimizedCompilationInfo::profiler_data () const [inline]
Definition at line 264 of file optimized-compilation-info.h.
{ return profiler_data_; }
Referenced by v8::internal::compiler::turboshaft::Pipeline::GenerateCode().
ReopenAndCanonicalizeHandlesInNewScope()
void v8::internal::OptimizedCompilationInfo::ReopenAndCanonicalizeHandlesInNewScope (Isolate * isolate)
Definition at line 138 of file optimized-compilation-info.cc.
                      {
  if (!shared_info_.is_null()) {
    shared_info_ = CanonicalHandle(*shared_info_, isolate);
  }
  if (!bytecode_array_.is_null()) {
    bytecode_array_ = CanonicalHandle(*bytecode_array_, isolate);
  }
  if (!closure_.is_null()) {
    closure_ = CanonicalHandle(*closure_, isolate);
  }
  DCHECK(code_.is_null());
}
References bytecode_array_, CanonicalHandle(), closure_, code_, v8::internal::DCHECK(), and shared_info_.
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTesting(), and v8::internal::anonymous_namespace{compiler.cc}::PrepareJobWithHandleScope().
RetryOptimization()
void v8::internal::OptimizedCompilationInfo::RetryOptimization (BailoutReason reason)
Definition at line 162 of file optimized-compilation-info.cc.
                                                                     {
  DCHECK_NE(reason, BailoutReason::kNoReason);
  if (disable_future_optimization()) return;
  bailout_reason_ = reason;
}
References bailout_reason_, and DCHECK_NE.
Referenced by v8::internal::TurbofanCompilationJob::RetryOptimization().
set_builtin()
void v8::internal::OptimizedCompilationInfo::set_builtin (Builtin builtin) [inline]
Definition at line 138 of file optimized-compilation-info.h.
{ builtin_ = builtin; }
Referenced by v8::internal::compiler::CodeAssemblerCompilationJob::CodeAssemblerCompilationJob().
set_canonical_handles()
void v8::internal::OptimizedCompilationInfo::set_canonical_handles (std::unique_ptr< CanonicalHandlesMap > canonical_handles) [inline]
Definition at line 184 of file optimized-compilation-info.h.
                                                            {
    DCHECK_NULL(canonical_handles_);
    canonical_handles_ = std::move(canonical_handles);
    DCHECK_NOT_NULL(canonical_handles_);
  }
References DCHECK_NOT_NULL, and DCHECK_NULL.
set_inlined_bytecode_size()
void v8::internal::OptimizedCompilationInfo::set_inlined_bytecode_size (unsigned size) [inline]
Definition at line 217 of file optimized-compilation-info.h.
                                                {
    inlined_bytecode_size_ = size;
  }
References size().
Referenced by v8::internal::compiler::InliningPhase::Run().
set_persistent_handles()
void v8::internal::OptimizedCompilationInfo::set_persistent_handles (std::unique_ptr< PersistentHandles > persistent_handles) [inline]
Definition at line 177 of file optimized-compilation-info.h.
                                                           {
    DCHECK_NULL(ph_);
    ph_ = std::move(persistent_handles);
    DCHECK_NOT_NULL(ph_);
  }
References DCHECK_NOT_NULL, and DCHECK_NULL.
Referenced by v8::internal::compiler::JSHeapBroker::DetachLocalIsolate(), and v8::internal::CompilationHandleScope::~CompilationHandleScope().
set_profiler_data()
void v8::internal::OptimizedCompilationInfo::set_profiler_data (BasicBlockProfilerData * profiler_data) [inline]
Definition at line 265 of file optimized-compilation-info.h.
                                                                {
    profiler_data_ = profiler_data;
  }
set_trace_turbo_filename()
void v8::internal::OptimizedCompilationInfo::set_trace_turbo_filename (std::unique_ptr< char[]> filename) [inline]
Definition at line 252 of file optimized-compilation-info.h.
                                                                {
    trace_turbo_filename_ = std::move(filename);
  }
Referenced by v8::internal::compiler::get_cached_trace_turbo_filename().
SetCode()
void v8::internal::OptimizedCompilationInfo::SetCode (IndirectHandle< Code > code)
Definition at line 203 of file optimized-compilation-info.cc.
                                                                {
  DCHECK_EQ(code->kind(), code_kind());
  code_ = code;
}
References code(), code_, code_kind(), and DCHECK_EQ.
Referenced by v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl().
SetFlag()
void v8::internal::OptimizedCompilationInfo::SetFlag (Flag flag) [inline], [private]
Definition at line 282 of file optimized-compilation-info.h.
{ flags_ |= flag; }
SetNodeObserver()
void v8::internal::OptimizedCompilationInfo::SetNodeObserver (compiler::NodeObserver * observer) [inline]
Definition at line 140 of file optimized-compilation-info.h.
                                                       {
    DCHECK_NULL(node_observer_);
    node_observer_ = observer;
  }
References DCHECK_NULL.
Referenced by OptimizedCompilationInfo().
SetTracingFlags()
void v8::internal::OptimizedCompilationInfo::SetTracingFlags (bool passes_filter) [private]
Definition at line 244 of file optimized-compilation-info.cc.
                                                                 {
  if (!passes_filter) return;
  if (v8_flags.trace_turbo) set_trace_turbo_json();
  if (v8_flags.trace_turbo_graph) set_trace_turbo_graph();
  if (v8_flags.trace_turbo_scheduled) set_trace_turbo_scheduled();
  if (v8_flags.trace_turbo_alloc) set_trace_turbo_allocation();
  if (v8_flags.trace_heap_broker) set_trace_heap_broker();
  if (v8_flags.turboshaft_trace_reduction) set_turboshaft_trace_reduction();
}
References v8::internal::v8_flags.
Referenced by OptimizedCompilationInfo().
shared_info()
IndirectHandle<SharedFunctionInfo> v8::internal::OptimizedCompilationInfo::shared_info () const [inline]
Definition at line 126 of file optimized-compilation-info.h.
                                                         {
    return shared_info_;
  }
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor(), v8::internal::anonymous_namespace{compiler.cc}::CompileTurbofan_Concurrent(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::CreatePipelineStatistics(), v8::internal::Compiler::FinalizeTurbofanCompilationJob(), v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), GetDebugName(), v8::internal::compiler::GetVisualizerLogFileName(), v8::internal::SourcePosition::InliningStack(), v8::internal::compiler::JsonPrintAllBytecodeSources(), v8::internal::compiler::JsonPrintAllSourceWithPositions(), v8::internal::compiler::PrintCode(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::PrintParticipatingSource(), v8::internal::TurbofanCompilationJob::RecordCompilationStats(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::TurbofanPipelineStatistics::TurbofanPipelineStatistics(), and ~OptimizedCompilationInfo().
tick_counter()
TickCounter& v8::internal::OptimizedCompilationInfo::tick_counter () [inline]
Definition at line 256 of file optimized-compilation-info.h.
{ return tick_counter_; }
Referenced by v8::internal::compiler::Pipeline::GenerateTurboshaftCodeForTesting(), v8::internal::compiler::TFPipelineData::InitializeRegisterAllocationData(), v8::internal::compiler::turboshaft::PipelineData::InitializeRegisterComponent(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run(), v8::internal::compiler::InliningPhase::Run(), and v8::internal::compiler::PrintGraphPhase::Run().
trace_turbo_filename()
const char* v8::internal::OptimizedCompilationInfo::trace_turbo_filename () const [inline]
Definition at line 248 of file optimized-compilation-info.h.
                                           {
    return trace_turbo_filename_.get();
  }
Referenced by v8::internal::compiler::get_cached_trace_turbo_filename().
was_cancelled()
bool v8::internal::OptimizedCompilationInfo::was_cancelled () const [inline]
Definition at line 258 of file optimized-compilation-info.h.
                             {
    return was_cancelled_.load(std::memory_order_relaxed);
  }
Referenced by v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(), and v8::internal::compiler::PipelineImpl::Run().
zone()
Zone* v8::internal::OptimizedCompilationInfo::zone () [inline]
Definition at line 124 of file optimized-compilation-info.h.
{ return zone_; }
Referenced by v8::internal::compiler::Pipeline::GenerateCodeForTesting(), OptimizedCompilationInfo(), v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl(), v8::internal::compiler::InliningPhase::Run(), and v8::internal::compiler::TFPipelineData::TFPipelineData().
Friends And Related Function Documentation
compiler::JSHeapBroker
friend class compiler::JSHeapBroker [friend]
Definition at line 293 of file optimized-compilation-info.h.
Member Data Documentation
bailout_reason_
BailoutReason v8::internal::OptimizedCompilationInfo::bailout_reason_ = BailoutReason::kNoReason [private]
Definition at line 325 of file optimized-compilation-info.h.
Referenced by AbortOptimization(), and RetryOptimization().
builtin_
Builtin v8::internal::OptimizedCompilationInfo::builtin_ = Builtin::kNoBuiltinId [private]
Definition at line 302 of file optimized-compilation-info.h.
Referenced by OptimizedCompilationInfo().
bytecode_array_
IndirectHandle<BytecodeArray> v8::internal::OptimizedCompilationInfo::bytecode_array_ [private]
Definition at line 306 of file optimized-compilation-info.h.
Referenced by OptimizedCompilationInfo(), and ReopenAndCanonicalizeHandlesInNewScope().
canonical_handles_
std::unique_ptr<CanonicalHandlesMap> v8::internal::OptimizedCompilationInfo::canonical_handles_ [private]
Definition at line 355 of file optimized-compilation-info.h.
Referenced by OptimizedCompilationInfo().
closure_
IndirectHandle<JSFunction> v8::internal::OptimizedCompilationInfo::closure_ [private]
Definition at line 308 of file optimized-compilation-info.h.
Referenced by OptimizedCompilationInfo(), and ReopenAndCanonicalizeHandlesInNewScope().
code_
IndirectHandle<Code> v8::internal::OptimizedCompilationInfo::code_ [private]
Definition at line 311 of file optimized-compilation-info.h.
Referenced by ReopenAndCanonicalizeHandlesInNewScope(), and SetCode().
code_kind_
const CodeKind v8::internal::OptimizedCompilationInfo::code_kind_ [private]
Definition at line 301 of file optimized-compilation-info.h.
Referenced by ConfigureFlags(), and OptimizedCompilationInfo().
debug_name_
base::Vector<const char> v8::internal::OptimizedCompilationInfo::debug_name_ [private]
Definition at line 333 of file optimized-compilation-info.h.
Referenced by GetDebugName().
flags_
unsigned v8::internal::OptimizedCompilationInfo::flags_ = 0 [private]
Definition at line 296 of file optimized-compilation-info.h.
inlined_bytecode_size_
unsigned v8::internal::OptimizedCompilationInfo::inlined_bytecode_size_ = 0 [private]
Definition at line 331 of file optimized-compilation-info.h.
inlined_functions_
InlinedFunctionList v8::internal::OptimizedCompilationInfo::inlined_functions_ [private]
Definition at line 327 of file optimized-compilation-info.h.
Referenced by AddInlinedFunction().
isolate_unsafe_
Isolate* const v8::internal::OptimizedCompilationInfo::isolate_unsafe_ [private]
Definition at line 299 of file optimized-compilation-info.h.
Referenced by ~OptimizedCompilationInfo().
kNoOptimizationId
constexpr int v8::internal::OptimizedCompilationInfo::kNoOptimizationId = -1 [static], [constexpr], [private]
Definition at line 329 of file optimized-compilation-info.h.
node_observer_
compiler::NodeObserver* v8::internal::OptimizedCompilationInfo::node_observer_ = nullptr [private]
Definition at line 323 of file optimized-compilation-info.h.
optimization_id_
const int v8::internal::OptimizedCompilationInfo::optimization_id_ [private]
Definition at line 330 of file optimized-compilation-info.h.
osr_offset_
const BytecodeOffset v8::internal::OptimizedCompilationInfo::osr_offset_ = BytecodeOffset::None() [private]
Definition at line 317 of file optimized-compilation-info.h.
ph_
std::unique_ptr<PersistentHandles> v8::internal::OptimizedCompilationInfo::ph_ [private]
Definition at line 350 of file optimized-compilation-info.h.
profiler_data_
BasicBlockProfilerData* v8::internal::OptimizedCompilationInfo::profiler_data_ = nullptr [private]
Definition at line 314 of file optimized-compilation-info.h.
shared_info_
IndirectHandle<SharedFunctionInfo> v8::internal::OptimizedCompilationInfo::shared_info_ [private]
Definition at line 307 of file optimized-compilation-info.h.
Referenced by OptimizedCompilationInfo(), and ReopenAndCanonicalizeHandlesInNewScope().
tick_counter_
TickCounter v8::internal::OptimizedCompilationInfo::tick_counter_ [private]
Definition at line 336 of file optimized-compilation-info.h.
trace_turbo_filename_
std::unique_ptr<char[]> v8::internal::OptimizedCompilationInfo::trace_turbo_filename_ [private]
Definition at line 334 of file optimized-compilation-info.h.
was_cancelled_
std::atomic<bool> v8::internal::OptimizedCompilationInfo::was_cancelled_ = false [private]
Definition at line 338 of file optimized-compilation-info.h.
Referenced by mark_cancelled().
zone_
Zone* const v8::internal::OptimizedCompilationInfo::zone_ [private]
Definition at line 321 of file optimized-compilation-info.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/optimized-compilation-info.h
/mnt/V8SourceCode/src/codegen/optimized-compilation-info.cc