unibrow::Mapping< T, size > Class Template Reference
#include <unicode.h>
Classes
struct CacheEntry
Public Member Functions
Mapping ()=default
int get (uchar c, uchar n, uchar *result)
Private Member Functions
int CalculateValue (uchar c, uchar n, uchar *result)
Private Attributes
CacheEntry entries_ [kSize]
Static Private Attributes
static const int kSize = size
static const int kMask = kSize - 1
Friends
class Test
Detailed Description
template<class T, int size = 256>
class unibrow::Mapping< T, size >
Definition at line 70 of file unicode.h.
Constructor & Destructor Documentation
Mapping()
template<class T , int size = 256>
unibrow::Mapping< T, size >::Mapping () [inline], [default]
Member Function Documentation
CalculateValue()
template<class T , int s>
int unibrow::Mapping< T, s >::CalculateValue (uchar c, uchar n, uchar * result) [private]
Definition at line 48 of file unicode-inl.h.
                                                                 {
  bool allow_caching = true;
  int length = T::Convert(c, n, result, &allow_caching);
  if (allow_caching) {
    if (length == 1) {
      entries_[c & kMask] = CacheEntry(c, result[0] - c);
      return 1;
    } else {
      entries_[c & kMask] = CacheEntry(c, 0);
      return 0;
    }
  } else {
    return length;
  }
}
References v8::internal::length, and v8::base::internal::result.
get()
template<class T , int s>
int unibrow::Mapping< T, s >::get (uchar c, uchar n, uchar * result) [inline]
Definition at line 33 of file unicode-inl.h.
                                                      {
  CacheEntry entry = entries_[c & kMask];
  if (entry.code_point_ == c) {
    if (entry.offset_ == 0) {
      return 0;
    } else {
      result[0] = c + entry.offset_;
      return 1;
    }
  } else {
    return CalculateValue(c, n, result);
  }
}
References unibrow::Mapping< T, size >::CacheEntry::code_point_, unibrow::Mapping< T, size >::CacheEntry::offset_, and v8::base::internal::result.
Referenced by v8::internal::CharacterRange::AddCaseEquivalents(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::Canonical(), v8::internal::RegExpMacroAssembler::CaseInsensitiveCompareUnicode(), v8::internal::anonymous_namespace{builtins-string.cc}::ConvertCaseHelper(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::GetCaseIndependentLetters().
Friends And Related Function Documentation
Test
template<class T , int size = 256>
friend class Test [friend]
Definition at line 76 of file unicode.h.
Member Data Documentation
entries_
template<class T , int size = 256>
CacheEntry unibrow::Mapping< T, size >::entries_[kSize] [private]
Definition at line 88 of file unicode.h.
kMask
template<class T , int size = 256>
const int unibrow::Mapping< T, size >::kMask = kSize - 1 [static], [private]
Definition at line 87 of file unicode.h.
kSize
template<class T , int size = 256>
const int unibrow::Mapping< T, size >::kSize = size [static], [private]
Definition at line 86 of file unicode.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/strings/unicode.h
/mnt/V8SourceCode/src/strings/unicode-inl.h