v8::internal::CommonFrameWithJSLinkage Class Reference
#include <frames.h>
Public Member Functions
virtual Tagged< JSFunction > function () const =0
virtual Tagged< Object > receiver () const
virtual Tagged< Object > GetParameter (int index) const
virtual int ComputeParametersCount () const
DirectHandle< FixedArray > GetParameters () const
virtual int GetActualArgumentCount () const
Tagged< HeapObject > unchecked_code () const override
virtual int LookupExceptionHandlerInTable (int *data, HandlerTable::CatchPrediction *prediction)
virtual bool IsConstructor () const
FrameSummaries Summarize () const override
Protected Member Functions
CommonFrameWithJSLinkage (StackFrameIteratorBase *iterator)
Address GetParameterSlot (int index) const
Static Protected Member Functions
static bool IsConstructFrame (Address fp)
Additional Inherited Members
Detailed Description
Definition at line 713 of file frames.h.
Constructor & Destructor Documentation
CommonFrameWithJSLinkage()
v8::internal::CommonFrameWithJSLinkage::CommonFrameWithJSLinkage (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 119 of file frames-inl.h.
    : CommonFrame(iterator) {}
Member Function Documentation
ComputeParametersCount()
int v8::internal::CommonFrameWithJSLinkage::ComputeParametersCount () const [virtual]
Reimplemented in v8::internal::JavaScriptBuiltinContinuationFrame, v8::internal::BuiltinFrame, and v8::internal::TurbofanJSFrame.
Definition at line 2620 of file frames.cc.
                                                           {
  DCHECK(!iterator_->IsStackFrameIteratorForProfiler() &&
         isolate()->heap()->gc_state() == Heap::NOT_IN_GC);
  return function()
      ->shared()
      ->internal_formal_parameter_count_without_receiver();
}
References v8::internal::DCHECK(), heap(), v8::internal::StackFrame::isolate(), v8::internal::StackFrame::iterator_, and v8::internal::Heap::NOT_IN_GC.
Referenced by v8::internal::TurbofanJSFrame::ComputeParametersCount(), GetParameters(), GetParameterSlot(), and v8::internal::JavaScriptFrame::PrintTop().
function()
virtual Tagged<JSFunction> v8::internal::CommonFrameWithJSLinkage::function () const [pure virtual]
Implemented in v8::internal::JavaScriptBuiltinContinuationFrame, v8::internal::BuiltinFrame, and v8::internal::JavaScriptFrame.
GetActualArgumentCount()
int v8::internal::CommonFrameWithJSLinkage::GetActualArgumentCount () const [inline], [virtual]
Reimplemented in v8::internal::JavaScriptFrame.
Definition at line 277 of file frames-inl.h.
                                                                  {
  return 0;
}
Referenced by GetParameterSlot().
GetParameter()
Tagged< Object > v8::internal::CommonFrameWithJSLinkage::GetParameter (int index) const [virtual]
Definition at line 2616 of file frames.cc.
                                                                     {
  return Tagged<Object>(Memory<Address>(GetParameterSlot(index)));
}
References GetParameterSlot(), v8::internal::index, and v8::internal::Tagged< Object >.
Referenced by v8::internal::anonymous_namespace{runtime-scopes.cc}::GetCallerArguments(), v8::internal::anonymous_namespace{accessors.cc}::GetFrameArguments(), GetParameters(), v8::internal::JavaScriptFrame::PrintTop(), and receiver().
GetParameters()
DirectHandle< FixedArray > v8::internal::CommonFrameWithJSLinkage::GetParameters () const
Definition at line 2634 of file frames.cc.
                                                                       {
  if (V8_LIKELY(!v8_flags.detailed_error_stack_trace)) {
    return isolate()->factory()->empty_fixed_array();
  }
  int param_count = ComputeParametersCount();
  DirectHandle<FixedArray> parameters =
      isolate()->factory()->NewFixedArray(param_count);
  for (int i = 0; i < param_count; i++) {
    parameters->set(i, GetParameter(i));
  }
  return parameters;
}
References ComputeParametersCount(), v8::internal::Isolate::factory(), GetParameter(), v8::internal::StackFrame::isolate(), v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::v8_flags, and V8_LIKELY.
Referenced by Summarize().
GetParameterSlot()
Address v8::internal::CommonFrameWithJSLinkage::GetParameterSlot (int index) const [inline], [protected]
Definition at line 269 of file frames-inl.h.
                                                                  {
  DCHECK_LE(-1, index);
  DCHECK_LT(index,
            std::max(GetActualArgumentCount(), ComputeParametersCount()));
  int parameter_offset = (index + 1) * kSystemPointerSize;
  return caller_sp() + parameter_offset;
}
References v8::internal::StackFrame::caller_sp(), ComputeParametersCount(), DCHECK_LE, DCHECK_LT, GetActualArgumentCount(), v8::internal::index, and v8::internal::kSystemPointerSize.
Referenced by GetParameter(), v8::internal::JavaScriptFrame::set_receiver(), and v8::internal::JavaScriptFrame::SetParameterValue().
IsConstructFrame()
bool v8::internal::CommonFrameWithJSLinkage::IsConstructFrame (Address fp) [inline], [static], [protected]
Definition at line 259 of file frames-inl.h.
                                                                 {
  intptr_t frame_type =
      base::Memory<intptr_t>(fp + TypedFrameConstants::kFrameTypeOffset);
  return frame_type == StackFrame::TypeToMarker(StackFrame::CONSTRUCT) ||
         frame_type == StackFrame::TypeToMarker(StackFrame::FAST_CONSTRUCT);
}
References v8::internal::StackFrame::fp(), v8::internal::TypedFrameConstants::kFrameTypeOffset, and v8::internal::StackFrame::TypeToMarker().
Referenced by IsConstructor(), and v8::internal::JavaScriptFrame::IsConstructor().
IsConstructor()
bool v8::internal::CommonFrameWithJSLinkage::IsConstructor () const [virtual]
Reimplemented in v8::internal::JavaScriptFrame.
Definition at line 2471 of file frames.cc.
                                                   {
  return IsConstructFrame(caller_fp());
}
References v8::internal::CommonFrame::caller_fp(), and IsConstructFrame().
Referenced by Summarize().
LookupExceptionHandlerInTable()
int v8::internal::CommonFrameWithJSLinkage::LookupExceptionHandlerInTable (int * data, HandlerTable::CatchPrediction * prediction) [virtual]
Reimplemented in v8::internal::UnoptimizedJSFrame, and v8::internal::OptimizedJSFrame.
Definition at line 2517 of file frames.cc.
                                                               {
  if (DEBUG_BOOL) {
    Tagged<Code> code_lookup_result = LookupCode();
    CHECK(!code_lookup_result->has_handler_table());
    CHECK(!code_lookup_result->is_optimized_code() ||
          code_lookup_result->kind() == CodeKind::BASELINE);
  }
  return -1;
}
References CHECK, DEBUG_BOOL, and v8::internal::StackFrame::LookupCode().
Referenced by v8::internal::Debug::PrepareStepOnThrow().
receiver()
Tagged< Object > v8::internal::CommonFrameWithJSLinkage::receiver () const [virtual]
Definition at line 2501 of file frames.cc.
                                                        {
  // TODO(cbruni): document this better
  return GetParameter(-1);
}
References GetParameter().
Referenced by v8::internal::JavaScriptFrame::PrintTop(), Summarize(), and v8::internal::DebugEvaluate::WithTopmostArguments().
Summarize()
FrameSummaries v8::internal::CommonFrameWithJSLinkage::Summarize () const [override], [virtual]
Reimplemented from v8::internal::CommonFrame.
Reimplemented in v8::internal::UnoptimizedJSFrame, and v8::internal::OptimizedJSFrame.
Definition at line 2475 of file frames.cc.
                                                         {
  Tagged<GcSafeCode> code;
  int offset = -1;
  std::tie(code, offset) = GcSafeLookupCodeAndOffset();
  DirectHandle<AbstractCode> abstract_code(
      Cast<AbstractCode>(code->UnsafeCastToCode()), isolate());
  DirectHandle<FixedArray> params = GetParameters();
  FrameSummary::JavaScriptFrameSummary summary(
      isolate(), receiver(), function(), *abstract_code, offset,
      IsConstructor(), *params);
  return FrameSummaries(summary);
}
References code, v8::internal::StackFrame::GcSafeLookupCodeAndOffset(), GetParameters(), IsConstructor(), v8::internal::StackFrame::isolate(), and receiver().
Referenced by v8::internal::anonymous_namespace{messages.cc}::ComputeLocation(), v8::internal::anonymous_namespace{accessors.cc}::FindFunctionInFrame(), v8::internal::FrameFunctionIterator::GetFrames(), v8::internal::anonymous_namespace{isolate.cc}::StackFrameSummaryIterator::InitSummaries(), v8::internal::Debug::PrepareStepOnThrow(), and v8::internal::OptimizedJSFrame::Summarize().
unchecked_code()
Tagged< HeapObject > v8::internal::CommonFrameWithJSLinkage::unchecked_code () const [override], [virtual]
Implements v8::internal::StackFrame.
Definition at line 2414 of file frames.cc.
                                                                  {
  return function()->code(isolate());
}
References code, and v8::internal::StackFrame::isolate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc