v8::internal::compiler::turboshaft::Graph Class Reference
#include <graph.h>
Classes
class OperationIterator
class OpIndexIterator
Public Types
using MutableOperationIterator = OperationIterator< Operation, Graph >
using ConstOperationIterator = OperationIterator< const Operation, const Graph >
Public Member Functions
Graph (Zone *graph_zone, size_t initial_capacity=2048)
void Reset ()
const Operation & Get (OpIndex i) const
Operation & Get (OpIndex i)
void KillOperation (OpIndex i)
Block & StartBlock ()
const Block & StartBlock () const
Block & Get (BlockIndex i)
const Block & Get (BlockIndex i) const
OpIndex Index (const Operation &op) const
BlockIndex BlockOf (OpIndex index) const
void SetBlockOf (BlockIndex block, OpIndex op)
BlockIndex BlockIndexOf (OpIndex op) const
BlockIndex BlockIndexOf (const Operation &op) const
OpIndex NextIndex (const OpIndex idx) const
OpIndex PreviousIndex (const OpIndex idx) const
OpIndex LastOperation () const
OperationStorageSlot * Allocate (size_t slot_count)
void RemoveLast ()
template<class Op , class... Args>
Op & Add (Args... args)
template<class Op , class... Args>
void Replace (OpIndex replaced, Args... args)
Block * NewLoopHeader (const Block *origin=nullptr)
Block * NewBlock (const Block *origin=nullptr)
Block * NewBlock (Block::Kind kind, const Block *origin=nullptr)
bool Add (Block *block)
void Finalize (Block *block)
void TurnLoopIntoMerge (Block *loop)
OpIndex next_operation_index () const
BlockIndex next_block_index () const
Block * last_block ()
Zone * graph_zone () const
uint32_t block_count () const
uint32_t op_id_count () const
uint32_t NumberOfOperationsForDebugging () const
uint32_t op_id_capacity () const
OpIndex BeginIndex () const
OpIndex EndIndex () const
base::iterator_range< MutableOperationIterator > AllOperations ()
base::iterator_range< ConstOperationIterator > AllOperations () const
base::iterator_range< OpIndexIterator > AllOperationIndices () const
base::iterator_range< MutableOperationIterator > operations (const Block &block)
base::iterator_range< ConstOperationIterator > operations (const Block &block) const
base::iterator_range< OpIndexIterator > OperationIndices (const Block &block) const
base::iterator_range< ConstOperationIterator > operations (OpIndex begin, OpIndex end) const
base::iterator_range< MutableOperationIterator > operations (OpIndex begin, OpIndex end)
base::iterator_range< OpIndexIterator > OperationIndices (OpIndex begin, OpIndex end) const
base::iterator_range< base::DerefPtrIterator< Block > > blocks ()
base::iterator_range< base::DerefPtrIterator< const Block > > blocks () const
const ZoneVector< Block * > & blocks_vector () const
bool IsLoopBackedge (const GotoOp &op) const
bool IsValid (OpIndex i) const
const GrowingOpIndexSidetable< SourcePosition > & source_positions () const
GrowingOpIndexSidetable< SourcePosition > & source_positions ()
const GrowingOpIndexSidetable< OpIndex > & operation_origins () const
GrowingOpIndexSidetable< OpIndex > & operation_origins ()
uint32_t DominatorTreeDepth () const
const GrowingOpIndexSidetable< Type > & operation_types () const
GrowingOpIndexSidetable< Type > & operation_types ()
void ReorderBlocks (base::Vector< uint32_t > permutation)
Graph & GetOrCreateCompanion ()
void SwapWithCompanion ()
void set_loop_unrolling_analyzer (LoopUnrollingAnalyzer *loop_unrolling_analyzer)
void clear_loop_unrolling_analyzer ()
LoopUnrollingAnalyzer * loop_unrolling_analyzer () const
void clear_stack_checks_to_remove ()
ZoneAbslFlatHashSet< uint32_t > & stack_checks_to_remove ()
const ZoneAbslFlatHashSet< uint32_t > & stack_checks_to_remove () const
Private Member Functions
bool InputsValid (const Operation &op) const
template<class Op >
void IncrementInputUses (const Op &op)
template<class Op >
void DecrementInputUses (const Op &op)
V8_NOINLINE V8_PRESERVE_MOST void AllocateNewBlocks ()
Private Attributes
OperationBuffer operations_
ZoneVector< Block * > bound_blocks_
base::Vector< Block * > all_blocks_
size_t next_block_ = 0
GrowingOpIndexSidetable< BlockIndex > op_to_block_
ZoneVector< Block * > block_permutation_
Zone * graph_zone_
GrowingOpIndexSidetable< SourcePosition > source_positions_
GrowingOpIndexSidetable< OpIndex > operation_origins_
uint32_t dominator_tree_depth_ = 0
GrowingOpIndexSidetable< Type > operation_types_
Graph * companion_ = nullptr
LoopUnrollingAnalyzer * loop_unrolling_analyzer_ = nullptr
ZoneAbslFlatHashSet< uint32_t > stack_checks_to_remove_
Detailed Description
Definition at line 578 of file graph.h.
Member Typedef Documentation
ConstOperationIterator
using v8::internal::compiler::turboshaft::Graph::ConstOperationIterator = OperationIterator<const Operation, const Graph>
Definition at line 934 of file graph.h.
MutableOperationIterator
using v8::internal::compiler::turboshaft::Graph::MutableOperationIterator = OperationIterator<Operation, Graph>
Definition at line 933 of file graph.h.
Constructor & Destructor Documentation
Graph()
v8::internal::compiler::turboshaft::Graph::Graph (Zone * graph_zone, size_t initial_capacity = 2048) [inline], [explicit]
Definition at line 582 of file graph.h.
      : operations_(graph_zone, initial_capacity),
        bound_blocks_(graph_zone),
        all_blocks_(),
        op_to_block_(graph_zone, this),
        block_permutation_(graph_zone),
        graph_zone_(graph_zone),
        source_positions_(graph_zone, this),
        operation_origins_(graph_zone, this),
        operation_types_(graph_zone, this),
#ifdef DEBUG
        block_type_refinement_(graph_zone),
#endif
        stack_checks_to_remove_(graph_zone) {
  }
Member Function Documentation
Add() [1/2]
template<class Op , class... Args>
Op& v8::internal::compiler::turboshaft::Graph::Add (Args... args) [inline]
Definition at line 721 of file graph.h.
                                  {
#ifdef DEBUG
    OpIndex result = next_operation_index();
#endif // DEBUG
    Op& op = Op::New(this, args...);
    IncrementInputUses(op);
    DCHECK_EQ(result, Index(op));
#ifdef DEBUG
    for (OpIndex input : op.inputs()) {
      DCHECK_LT(input, result);
      DCHECK(BelongsToThisGraph(input));
    }
    if (v8_flags.turboshaft_trace_emitted) {
      std::cout << "Emitted: " << result << " => " << op << "\n";
    }
#endif // DEBUG
    return op;
  }
References v8::base::args, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, IncrementInputUses(), Index(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), next_operation_index(), v8::base::internal::result, and v8::internal::v8_flags.
Add() [2/2]
bool v8::internal::compiler::turboshaft::Graph::Add (Block * block) [inline]
Definition at line 783 of file graph.h.
                                   {
    DCHECK_EQ(block->graph_generation_, generation_);
    if (!bound_blocks_.empty() && !block->HasPredecessors()) return false;
    DCHECK(!block->begin_.valid());
    block->begin_ = next_operation_index();
    DCHECK_EQ(block->index_, BlockIndex::Invalid());
    block->index_ = next_block_index();
    bound_blocks_.push_back(block);
    uint32_t depth = block->ComputeDominator();
    dominator_tree_depth_ = std::max<uint32_t>(dominator_tree_depth_, depth);
#ifdef DEBUG
    if (v8_flags.turboshaft_trace_emitted) {
      std::cout << "\nBound: " << block->index() << " [predecessors: ";
      auto preds = block->Predecessors();
      if (preds.size() >= 1) std::cout << preds[0]->index();
      for (size_t i = 1; i < preds.size(); i++) {
        std::cout << ", " << preds[i]->index();
      }
      std::cout << "]\n";
    }
#endif
    return true;
  }
References v8::internal::compiler::turboshaft::Block::begin_, bound_blocks_, v8::internal::compiler::turboshaft::Block::ComputeDominator(), v8::internal::DCHECK(), DCHECK_EQ, dominator_tree_depth_, v8::internal::compiler::turboshaft::Block::HasPredecessors(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Block::index_, v8::internal::compiler::turboshaft::BlockIndex::Invalid(), next_block_index(), next_operation_index(), v8::internal::compiler::turboshaft::Block::Predecessors(), v8::internal::v8_flags, and v8::internal::compiler::turboshaft::OpIndex::valid().
Allocate()
OperationStorageSlot* v8::internal::compiler::turboshaft::Graph::Allocate (size_t slot_count) [inline]
Definition at line 706 of file graph.h.
                                                    {
    return operations_.Allocate(slot_count);
  }
References v8::internal::compiler::turboshaft::OperationBuffer::Allocate(), and operations_.
AllocateNewBlocks()
V8_NOINLINE V8_PRESERVE_MOST void v8::internal::compiler::turboshaft::Graph::AllocateNewBlocks () [inline], [private]
Definition at line 1162 of file graph.h.
                                                        {
    constexpr size_t kMinCapacity = 32;
    size_t next_capacity = std::max(kMinCapacity, all_blocks_.size() * 2);
    size_t new_block_count = next_capacity - all_blocks_.size();
    DCHECK_GT(new_block_count, 0);
    base::Vector<Block> block_storage =
        graph_zone_->AllocateVector<Block>(new_block_count);
    base::Vector<Block*> new_all_blocks =
        graph_zone_->AllocateVector<Block*>(next_capacity);
    DCHECK_EQ(new_all_blocks.size(), all_blocks_.size() + new_block_count);
    std::copy(all_blocks_.begin(), all_blocks_.end(), new_all_blocks.begin());
    Block** insert_begin = new_all_blocks.begin() + all_blocks_.size();
    DCHECK_EQ(insert_begin + new_block_count, new_all_blocks.end());
    for (size_t i = 0; i < new_block_count; ++i) {
      insert_begin[i] = &block_storage[i];
    }
    base::Vector<Block*> old_all_blocks = all_blocks_;
    all_blocks_ = new_all_blocks;
    if (!old_all_blocks.empty()) {
      graph_zone_->DeleteArray(old_all_blocks.data(), old_all_blocks.length());
    }
    // Eventually most new blocks will be bound anyway, so pre-allocate as well.
    DCHECK_LE(bound_blocks_.size(), all_blocks_.size());
    bound_blocks_.reserve(all_blocks_.size());
  }
References all_blocks_, v8::internal::Zone::AllocateVector(), v8::internal::compiler::turboshaft::Block::begin(), bound_blocks_, v8::base::Vector< T >::data(), DCHECK_EQ, DCHECK_GT, DCHECK_LE, v8::internal::Zone::DeleteArray(), v8::base::Vector< T >::empty(), v8::internal::compiler::turboshaft::Block::end(), graph_zone_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::Vector< T >::length().
Referenced by NewBlock().
AllOperationIndices()
base::iterator_range<OpIndexIterator> v8::internal::compiler::turboshaft::Graph::AllOperationIndices () const [inline]
Definition at line 944 of file graph.h.
                                                                  {
    return OperationIndices(BeginIndex(), EndIndex());
  }
References BeginIndex(), EndIndex(), and OperationIndices().
AllOperations() [1/2]
base::iterator_range<MutableOperationIterator> v8::internal::compiler::turboshaft::Graph::AllOperations () [inline]
Definition at line 937 of file graph.h.
                                                               {
    return operations(BeginIndex(), EndIndex());
  }
References BeginIndex(), EndIndex(), and operations().
Referenced by v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::BuildStoreInputGraph(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::CollectUsesAndAllocations(), NumberOfOperationsForDebugging(), RemoveLast(), and v8::internal::compiler::turboshaft::CsaEffectsComputationPhase::Run().
AllOperations() [2/2]
base::iterator_range<ConstOperationIterator> v8::internal::compiler::turboshaft::Graph::AllOperations () const [inline]
Definition at line 940 of file graph.h.
                                                                   {
    return operations(BeginIndex(), EndIndex());
  }
References BeginIndex(), EndIndex(), and operations().
BeginIndex()
OpIndex v8::internal::compiler::turboshaft::Graph::BeginIndex () const [inline]
Definition at line 857 of file graph.h.
                             {
    OpIndex begin = operations_.BeginIndex();
#ifdef DEBUG
    begin.set_generation_mod2(generation_mod2());
#endif
    return begin;
  }
References v8::internal::compiler::begin(), v8::internal::compiler::turboshaft::OperationBuffer::BeginIndex(), and operations_.
Referenced by AllOperationIndices(), and AllOperations().
block_count()
uint32_t v8::internal::compiler::turboshaft::Graph::block_count () const [inline]
Definition at line 840 of file graph.h.
                               {
    return static_cast<uint32_t>(bound_blocks_.size());
  }
References bound_blocks_.
Referenced by v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeBlockPermutation(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::Run(), v8::internal::compiler::turboshaft::MemoryAnalyzer::Run(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::Run(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::Run(), and v8::internal::compiler::turboshaft::RedundantStoreAnalysis::Run().
BlockIndexOf() [1/2]
BlockIndex v8::internal::compiler::turboshaft::Graph::BlockIndexOf (const Operation & op) const [inline]
Definition at line 684 of file graph.h.
                                                     {
    return op_to_block_[Index(op)];
  }
References Index(), and op_to_block_.
BlockIndexOf() [2/2]
BlockIndex v8::internal::compiler::turboshaft::Graph::BlockIndexOf (OpIndex op) const [inline]
Definition at line 682 of file graph.h.
{ return op_to_block_[op]; }
References op_to_block_.
BlockOf()
BlockIndex v8::internal::compiler::turboshaft::Graph::BlockOf (OpIndex index) const [inline]
Definition at line 662 of file graph.h.
                                          {
    ZoneVector<Block*>::const_iterator it;
    if (block_permutation_.empty()) {
      it = std::upper_bound(
          bound_blocks_.begin(), bound_blocks_.end(), index,
          [](OpIndex value, const Block* b) { return value < b->begin_; });
      DCHECK_NE(it, bound_blocks_.begin());
    } else {
      it = std::upper_bound(
          block_permutation_.begin(), block_permutation_.end(), index,
          [](OpIndex value, const Block* b) { return value < b->begin_; });
      DCHECK_NE(it, block_permutation_.begin());
    }
    it = std::prev(it);
    DCHECK((*it)->Contains(index));
    return (*it)->index();
  }
References block_permutation_, bound_blocks_, v8::internal::DCHECK(), DCHECK_NE, v8::internal::index, and v8::internal::value.
Referenced by v8::internal::compiler::InstructionSelector::block().
blocks() [1/2]
base::iterator_range<base::DerefPtrIterator<Block> > v8::internal::compiler::turboshaft::Graph::blocks () [inline]
Definition at line 984 of file graph.h.
                                                           {
    return {base::DerefPtrIterator<Block>(bound_blocks_.data()),
            base::DerefPtrIterator<Block>(bound_blocks_.data() +
                                          bound_blocks_.size())};
  }
References bound_blocks_.
Referenced by v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintBlocks(), v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintEdges(), v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintNodes(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::Run(), v8::internal::compiler::turboshaft::LoopFinder::Run(), and v8::internal::compiler::turboshaft::WasmRevecAnalyzer::Run().
blocks() [2/2]
base::iterator_range<base::DerefPtrIterator<const Block> > v8::internal::compiler::turboshaft::Graph::blocks () const [inline]
Definition at line 989 of file graph.h.
                                                                       {
    return {base::DerefPtrIterator<const Block>(bound_blocks_.data()),
            base::DerefPtrIterator<const Block>(bound_blocks_.data() +
                                                bound_blocks_.size())};
  }
References bound_blocks_.
blocks_vector()
const ZoneVector<Block*>& v8::internal::compiler::turboshaft::Graph::blocks_vector () const [inline]
Definition at line 994 of file graph.h.
{ return bound_blocks_; }
References bound_blocks_.
Referenced by v8::internal::compiler::InstructionSelector::rpo_order().
clear_loop_unrolling_analyzer()
void v8::internal::compiler::turboshaft::Graph::clear_loop_unrolling_analyzer () [inline]
Definition at line 1103 of file graph.h.
{ loop_unrolling_analyzer_ = nullptr; }
References loop_unrolling_analyzer_.
clear_stack_checks_to_remove()
void v8::internal::compiler::turboshaft::Graph::clear_stack_checks_to_remove () [inline]
Definition at line 1114 of file graph.h.
{ stack_checks_to_remove_.clear(); }
References stack_checks_to_remove_.
DecrementInputUses()
template<class Op >
void v8::internal::compiler::turboshaft::Graph::DecrementInputUses (const Op & op) [inline], [private]
Definition at line 1150 of file graph.h.
                                        {
    for (OpIndex input : op.inputs()) {
      // Tuples should never be used as input, except in other tuples (which is
      // used for instance in Int64Lowering::LowerCall).
      DCHECK_IMPLIES(Get(input).Is<TupleOp>(), op.template Is<TupleOp>());
      Get(input).saturated_use_count.Decr();
    }
  }
References DCHECK_IMPLIES, v8::internal::compiler::turboshaft::SaturatedUint8::Decr(), Get(), and v8::internal::compiler::turboshaft::Operation::saturated_use_count.
Referenced by RemoveLast(), and Replace().
DominatorTreeDepth()
uint32_t v8::internal::compiler::turboshaft::Graph::DominatorTreeDepth () const [inline]
Definition at line 1017 of file graph.h.
{ return dominator_tree_depth_; }
References dominator_tree_depth_.
EndIndex()
OpIndex v8::internal::compiler::turboshaft::Graph::EndIndex () const [inline]
Definition at line 864 of file graph.h.
                           {
    OpIndex end = operations_.EndIndex();
#ifdef DEBUG
    end.set_generation_mod2(generation_mod2());
#endif
    return end;
  }
References v8::internal::compiler::end(), v8::internal::compiler::turboshaft::OperationBuffer::EndIndex(), and operations_.
Referenced by AllOperationIndices(), AllOperations(), and next_operation_index().
Finalize()
void v8::internal::compiler::turboshaft::Graph::Finalize (Block * block) [inline]
Definition at line 810 of file graph.h.
                              {
    DCHECK(!block->end_.valid());
    block->end_ = next_operation_index();
    // Upading mapping from Operations to Blocks for the Operations in {block}.
    for (const Operation& op : operations(*block)) {
      SetBlockOf(block->index(), Index(op));
    }
  }
References v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Block::end_, v8::internal::compiler::turboshaft::Block::index(), Index(), next_operation_index(), operations(), SetBlockOf(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Get() [1/4]
Block& v8::internal::compiler::turboshaft::Graph::Get (BlockIndex i) [inline]
Definition at line 646 of file graph.h.
                           {
    DCHECK_LT(i.id(), bound_blocks_.size());
    return *bound_blocks_[i.id()];
  }
References bound_blocks_, and DCHECK_LT.
Get() [2/4]
const Block& v8::internal::compiler::turboshaft::Graph::Get (BlockIndex i) const [inline]
Definition at line 650 of file graph.h.
                                       {
    DCHECK_LT(i.id(), bound_blocks_.size());
    return *bound_blocks_[i.id()];
  }
References bound_blocks_, and DCHECK_LT.
Get() [3/4]
Operation& v8::internal::compiler::turboshaft::Graph::Get (OpIndex i) [inline]
Definition at line 629 of file graph.h.
                                      {
    DCHECK(i.valid());
    DCHECK(BelongsToThisGraph(i));
    // `Operation` contains const fields and can be overwritten with placement
    // new. Therefore, std::launder is necessary to avoid undefined behavior.
    Operation* ptr =
        std::launder(reinterpret_cast<Operation*>(operations_.Get(i)));
    // Detect invalid memory by checking if opcode is valid.
    DCHECK_LT(OpcodeIndex(ptr->opcode), kNumberOfOpcodes);
    return *ptr;
  }
References v8::internal::DCHECK(), DCHECK_LT, v8::internal::compiler::turboshaft::OperationBuffer::Get(), v8::internal::compiler::turboshaft::kNumberOfOpcodes, v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::OpcodeIndex(), and operations_.
Get() [4/4]
const Operation& v8::internal::compiler::turboshaft::Graph::Get (OpIndex i) const [inline]
Definition at line 618 of file graph.h.
                                                  {
    DCHECK(i.valid());
    DCHECK(BelongsToThisGraph(i));
    // `Operation` contains const fields and can be overwritten with placement
    // new. Therefore, std::launder is necessary to avoid undefined behavior.
    const Operation* ptr =
        std::launder(reinterpret_cast<const Operation*>(operations_.Get(i)));
    // Detect invalid memory by checking if opcode is valid.
    DCHECK_LT(OpcodeIndex(ptr->opcode), kNumberOfOpcodes);
    return *ptr;
  }
References v8::internal::DCHECK(), DCHECK_LT, v8::internal::compiler::turboshaft::OperationBuffer::Get(), v8::internal::compiler::turboshaft::kNumberOfOpcodes, v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::OpcodeIndex(), and operations_.
Referenced by v8::internal::compiler::turboshaft::DemandedElementAnalysis::AddBinaryOp(), v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor(), v8::internal::compiler::turboshaft::DemandedElementAnalysis::AddUnaryOp(), v8::internal::compiler::InstructionSelector::block(), v8::internal::compiler::turboshaft::SLPTree::BuildTreeRec(), v8::internal::compiler::turboshaft::SLPTree::CanBePacked(), v8::internal::compiler::InstructionSelector::CanDoBranchIfOverflowFusion(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::CollectUsesAndAllocations(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ComputeFrameStatesToReconstruct(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::DecideVectorize(), DecrementInputUses(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::EscapesThroughUse(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::FindRemovableAllocations(), v8::internal::compiler::InstructionSelector::GetFrameStateDescriptor(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::GetStartOperation(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::GetType(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetTypeForPhiInput(), v8::internal::compiler::turboshaft::SLPTree::HasInputDependencies(), IncrementInputUses(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::InvalidateIfAlias(), v8::internal::compiler::turboshaft::SLPTree::IsEqual(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::IsEscaping(), v8::internal::compiler::turboshaft::MemoryAnalyzer::IsFoldedAllocation(), v8::internal::compiler::InstructionSelector::IsOnlyUserOfNodeInSameBlock(), v8::internal::compiler::turboshaft::SLPTree::IsSideEffectFree(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::MarkAllInputsAsEscaping(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::MarkAsEscaping(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::MarkToRemove(), v8::internal::compiler::turboshaft::SLPTree::NewBundlePackNode(), v8::internal::compiler::turboshaft::SLPTree::NewCommutativePackNodeAndRecurs(), v8::internal::compiler::turboshaft::SLPTree::NewForcePackNode(), v8::internal::compiler::turboshaft::SLPTree::NewIntersectPackNode(), v8::internal::compiler::turboshaft::SLPTree::NewPackNode(), v8::internal::compiler::turboshaft::SLPTree::NewPackNodeAndRecurs(), v8::internal::compiler::turboshaft::SLPTree::NewShufflePackNode(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::OldifySubgraph(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::OperandForDeopt(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateArray(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateStruct(), v8::internal::compiler::turboshaft::MemoryAnalyzer::ProcessAllocation(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAnyConvertExtern(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessArrayLength(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessAssertNotNull(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessCall(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessCall(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessCheckTurboshaftTypeOf(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ProcessFrameState(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessLoad(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessLoopPhi(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessOperations(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::ProcessShuffle(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessStore(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringAsWtf16(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStringPrepareForGetCodeUnit(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessStructGet(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::RecordAllocateUse(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursivelyMarkAllStringConcatInputsAsEscaping(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::RecursiveMarkAsShouldReconstruct(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::RefineOperationType(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::RefineTypesAfterBranch(), Replace(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ReprocessStringConcats(), v8::internal::compiler::turboshaft::MemoryAnalyzer::ReservedSize(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ResolveAliases(), v8::internal::compiler::turboshaft::wle::WasmMemoryContentTable::ResolveBase(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::Run(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run(), v8::internal::compiler::turboshaft::MemoryAnalyzer::Run(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::Run(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::Run(), v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::Run(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::Run(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::Run(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::SetType(), v8::internal::compiler::turboshaft::MemoryAnalyzer::SkipWriteBarrier(), StartBlock(), v8::internal::compiler::turboshaft::SLPTree::Try256ShuffleMatchLoad8x8U(), v8::internal::compiler::turboshaft::SLPTree::TryGetExtendIntToF32x4Info(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero(), and v8::internal::compiler::InstructionSelector::VisitReturn().
GetOrCreateCompanion()
Graph& v8::internal::compiler::turboshaft::Graph::GetOrCreateCompanion () [inline]
Definition at line 1049 of file graph.h.
                                {
    if (!companion_) {
      companion_ = graph_zone_->New<Graph>(graph_zone_, operations_.size());
#ifdef DEBUG
      companion_->generation_ = generation_ + 1;
      if (IsCreatedFromTurbofan()) companion_->SetCreatedFromTurbofan();
      companion_->broker_ = broker_;
#endif // DEBUG
    }
    return *companion_;
  }
References companion_, graph_zone_, v8::internal::Zone::New(), operations_, and v8::internal::compiler::turboshaft::OperationBuffer::size().
Referenced by v8::internal::compiler::turboshaft::CopyingPhaseImpl< Reducers >::Run(), v8::internal::compiler::turboshaft::LoopUnrollingPhase::Run(), and SwapWithCompanion().
graph_zone()
Zone* v8::internal::compiler::turboshaft::Graph::graph_zone () const [inline]
Definition at line 839 of file graph.h.
{ return graph_zone_; }
References graph_zone_.
IncrementInputUses()
template<class Op >
void v8::internal::compiler::turboshaft::Graph::IncrementInputUses (const Op & op) [inline], [private]
Definition at line 1140 of file graph.h.
                                        {
    for (OpIndex input : op.inputs()) {
      // Tuples should never be used as input, except in other tuples (which is
      // used for instance in Int64Lowering::LowerCall).
      DCHECK_IMPLIES(Get(input).Is<TupleOp>(), op.template Is<TupleOp>());
      Get(input).saturated_use_count.Incr();
    }
  }
References DCHECK_IMPLIES, Get(), v8::internal::compiler::turboshaft::SaturatedUint8::Incr(), and v8::internal::compiler::turboshaft::Operation::saturated_use_count.
Referenced by Add(), and Replace().
Index()
OpIndex v8::internal::compiler::turboshaft::Graph::Index (const Operation & op) const [inline]
Definition at line 655 of file graph.h.
                                           {
    OpIndex result = operations_.Index(op);
#ifdef DEBUG
    result.set_generation_mod2(generation_mod2());
#endif
    return result;
  }
References v8::internal::compiler::turboshaft::OperationBuffer::Index(), operations_, and v8::base::internal::result.
Referenced by Add(), BlockIndexOf(), v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::CollectUsesAndAllocations(), Finalize(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::GetTypeForPhiInput(), IsLoopBackedge(), v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintEdges(), v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintNodes(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessAllocate(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateArray(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateStruct(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessArrayGet(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessArrayLength(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAssertNotNull(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessGlobalGet(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessIsNull(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessNull(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessParameter(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessPhi(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessRefFunc(), v8::internal::compiler::turboshaft::MemoryAnalyzer::ProcessStore(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessStructGet(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessStructSet(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessTypeCast(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessTypeCheck(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::RefineTypesAfterBranch(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::Run(), v8::internal::compiler::turboshaft::MemoryAnalyzer::SkipWriteBarrier(), TurnLoopIntoMerge(), and v8::internal::compiler::InstructionSelector::VisitControl().
InputsValid()
bool v8::internal::compiler::turboshaft::Graph::InputsValid (const Operation & op) const [inline], [private]
Definition at line 1132 of file graph.h.
                                              {
    for (OpIndex i : op.inputs()) {
      if (!IsValid(i)) return false;
    }
    return true;
  }
References v8::internal::compiler::turboshaft::Operation::inputs(), and IsValid().
IsLoopBackedge()
bool v8::internal::compiler::turboshaft::Graph::IsLoopBackedge (const GotoOp & op) const [inline]
Definition at line 996 of file graph.h.
                                              {
    DCHECK(op.destination->IsBound());
    return op.destination->begin() <= Index(op);
  }
References v8::internal::compiler::turboshaft::Block::begin(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::GotoOp::destination, Index(), and v8::internal::compiler::turboshaft::Block::IsBound().
Referenced by v8::internal::compiler::turboshaft::MemoryAnalyzer::ProcessBlockTerminator().
IsValid()
bool v8::internal::compiler::turboshaft::Graph::IsValid (OpIndex i) const [inline]
Definition at line 1001 of file graph.h.
{ return i < next_operation_index(); }
References next_operation_index().
Referenced by InputsValid().
KillOperation()
void v8::internal::compiler::turboshaft::Graph::KillOperation (OpIndex i) [inline]
Definition at line 641 of file graph.h.
{ Replace<DeadOp>(i); }
Referenced by v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::MarkToRemove().
last_block()
Block* v8::internal::compiler::turboshaft::Graph::last_block () [inline]
Definition at line 837 of file graph.h.
{ return bound_blocks_.back(); }
References bound_blocks_.
LastOperation()
OpIndex v8::internal::compiler::turboshaft::Graph::LastOperation () const [inline]
Definition at line 702 of file graph.h.
                                {
    return PreviousIndex(next_operation_index());
  }
References next_operation_index(), and PreviousIndex().
loop_unrolling_analyzer()
LoopUnrollingAnalyzer* v8::internal::compiler::turboshaft::Graph::loop_unrolling_analyzer () const [inline]
Definition at line 1104 of file graph.h.
                                                         {
    DCHECK_NOT_NULL(loop_unrolling_analyzer_);
    return loop_unrolling_analyzer_;
  }
References DCHECK_NOT_NULL, and loop_unrolling_analyzer_.
Referenced by set_loop_unrolling_analyzer().
NewBlock() [1/2]
Block* v8::internal::compiler::turboshaft::Graph::NewBlock (Block::Kind kind, const Block * origin = nullptr) [inline]
Definition at line 770 of file graph.h.
                                                                           {
    if (V8_UNLIKELY(next_block_ == all_blocks_.size())) {
      AllocateNewBlocks();
    }
    Block* result = all_blocks_[next_block_++];
    new (result) Block(kind);
#ifdef DEBUG
    result->graph_generation_ = generation_;
#endif
    result->SetOrigin(origin);
    return result;
  }
References all_blocks_, AllocateNewBlocks(), next_block_, v8::base::internal::result, and V8_UNLIKELY.
NewBlock() [2/2]
Block* v8::internal::compiler::turboshaft::Graph::NewBlock (const Block * origin = nullptr) [inline]
Definition at line 766 of file graph.h.
                                                           {
    return NewBlock(Block::Kind::kMerge, origin);
  }
References v8::internal::compiler::turboshaft::Block::kMerge.
Referenced by NewLoopHeader().
NewLoopHeader()
Block* v8::internal::compiler::turboshaft::Graph::NewLoopHeader (const Block * origin = nullptr) [inline]
Definition at line 763 of file graph.h.
                                                                {
    return NewBlock(Block::Kind::kLoopHeader, origin);
  }
References v8::internal::compiler::turboshaft::Block::kLoopHeader, and NewBlock().
next_block_index()
BlockIndex v8::internal::compiler::turboshaft::Graph::next_block_index () const [inline]
Definition at line 833 of file graph.h.
                                      {
    return BlockIndex(static_cast<uint32_t>(bound_blocks_.size()));
  }
References bound_blocks_.
Referenced by Add().
next_operation_index()
OpIndex v8::internal::compiler::turboshaft::Graph::next_operation_index () const [inline]
Definition at line 832 of file graph.h.
{ return EndIndex(); }
References EndIndex().
Referenced by Add(), Finalize(), IsValid(), and LastOperation().
NextIndex()
OpIndex v8::internal::compiler::turboshaft::Graph::NextIndex (const OpIndex idx) const [inline]
Definition at line 688 of file graph.h.
                                             {
    OpIndex next = operations_.Next(idx);
#ifdef DEBUG
    next.set_generation_mod2(generation_mod2());
#endif
    return next;
  }
References v8::internal::compiler::turboshaft::OperationBuffer::Next(), and operations_.
Referenced by v8::internal::compiler::turboshaft::Graph::OpIndexIterator::operator++(), and v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock().
NumberOfOperationsForDebugging()
uint32_t v8::internal::compiler::turboshaft::Graph::NumberOfOperationsForDebugging () const [inline]
Definition at line 846 of file graph.h.
                                                  {
    uint32_t number_of_operations = 0;
    for ([[maybe_unused]] auto& op : AllOperations()) {
      ++number_of_operations;
    }
    return number_of_operations;
  }
References AllOperations().
op_id_capacity()
uint32_t v8::internal::compiler::turboshaft::Graph::op_id_capacity () const [inline]
Definition at line 853 of file graph.h.
                                  {
    return operations_.capacity() / kSlotsPerId;
  }
References v8::internal::compiler::turboshaft::OperationBuffer::capacity(), v8::internal::compiler::turboshaft::kSlotsPerId, and operations_.
op_id_count()
uint32_t v8::internal::compiler::turboshaft::Graph::op_id_count () const [inline]
Definition at line 843 of file graph.h.
                               {
    return (operations_.size() + (kSlotsPerId - 1)) / kSlotsPerId;
  }
References v8::internal::compiler::turboshaft::kSlotsPerId, operations_, and v8::internal::compiler::turboshaft::OperationBuffer::size().
Referenced by v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::Run().
operation_origins() [1/2]
GrowingOpIndexSidetable<OpIndex>& v8::internal::compiler::turboshaft::Graph::operation_origins () [inline]
Definition at line 1013 of file graph.h.
                                                        {
    return operation_origins_;
  }
References operation_origins_.
operation_origins() [2/2]
const GrowingOpIndexSidetable<OpIndex>& v8::internal::compiler::turboshaft::Graph::operation_origins () const [inline]
Definition at line 1010 of file graph.h.
                                                                    {
    return operation_origins_;
  }
References operation_origins_.
operation_types() [1/2]
GrowingOpIndexSidetable<Type>& v8::internal::compiler::turboshaft::Graph::operation_types () [inline]
Definition at line 1022 of file graph.h.
{ return operation_types_; }
References operation_types_.
operation_types() [2/2]
const GrowingOpIndexSidetable<Type>& v8::internal::compiler::turboshaft::Graph::operation_types () const [inline]
Definition at line 1019 of file graph.h.
                                                               {
    return operation_types_;
  }
References operation_types_.
OperationIndices() [1/2]
base::iterator_range<OpIndexIterator> v8::internal::compiler::turboshaft::Graph::OperationIndices (const Block & block) const [inline]
Definition at line 957 of file graph.h.
                                {
    return OperationIndices(block.begin_, block.end_);
  }
References v8::internal::compiler::turboshaft::Block::begin_, and v8::internal::compiler::turboshaft::Block::end_.
Referenced by AllOperationIndices(), v8::internal::compiler::turboshaft::RedundantStoreAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::StringEscapeAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::LateLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::WasmLoadEliminationAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::TypeInferenceAnalysis::ProcessBlock(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessOperations(), v8::internal::compiler::turboshaft::DeadCodeAnalysis::Run(), and v8::internal::compiler::turboshaft::WasmShuffleAnalyzer::Run().
OperationIndices() [2/2]
base::iterator_range<OpIndexIterator> v8::internal::compiler::turboshaft::Graph::OperationIndices (OpIndex begin, OpIndex end) const [inline]
Definition at line 977 of file graph.h.
                                                                            {
    DCHECK(begin.valid());
    DCHECK(end.valid());
    return {OpIndexIterator(begin, this), OpIndexIterator(end, this)};
  }
References v8::internal::compiler::begin(), v8::internal::DCHECK(), and v8::internal::compiler::end().
operations() [1/4]
base::iterator_range<MutableOperationIterator> v8::internal::compiler::turboshaft::Graph::operations (const Block & block) [inline]
Definition at line 948 of file graph.h.
                          {
    return operations(block.begin_, block.end_);
  }
References v8::internal::compiler::turboshaft::Block::begin_, and v8::internal::compiler::turboshaft::Block::end_.
Referenced by AllOperations(), v8::internal::compiler::turboshaft::LoopFinder::CollectLoopInfo(), Finalize(), operations(), v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintEdges(), v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintNodes(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::ProcessBlock(), v8::internal::compiler::turboshaft::MemoryAnalyzer::ProcessBlockTerminator(), v8::internal::compiler::turboshaft::MemoryAnalyzer::Run(), and TurnLoopIntoMerge().
operations() [2/4]
base::iterator_range<ConstOperationIterator> v8::internal::compiler::turboshaft::Graph::operations (const Block & block) const [inline]
Definition at line 952 of file graph.h.
                                {
    return operations(block.begin_, block.end_);
  }
References v8::internal::compiler::turboshaft::Block::begin_, v8::internal::compiler::turboshaft::Block::end_, and operations().
operations() [3/4]
base::iterator_range<MutableOperationIterator> v8::internal::compiler::turboshaft::Graph::operations (OpIndex begin, OpIndex end) [inline]
Definition at line 969 of file graph.h.
                                                                         {
    DCHECK(begin.valid());
    DCHECK(end.valid());
    return {MutableOperationIterator(begin, this),
            MutableOperationIterator(end, this)};
  }
References v8::internal::compiler::begin(), v8::internal::DCHECK(), and v8::internal::compiler::end().
operations() [4/4]
base::iterator_range<ConstOperationIterator> v8::internal::compiler::turboshaft::Graph::operations (OpIndex begin, OpIndex end) const [inline]
Definition at line 962 of file graph.h.
                                                                             {
    DCHECK(begin.valid());
    DCHECK(end.valid());
    return {ConstOperationIterator(begin, this),
            ConstOperationIterator(end, this)};
  }
References v8::internal::compiler::begin(), v8::internal::DCHECK(), and v8::internal::compiler::end().
PreviousIndex()
OpIndex v8::internal::compiler::turboshaft::Graph::PreviousIndex (const OpIndex idx) const [inline]
Definition at line 695 of file graph.h.
                                                 {
    OpIndex prev = operations_.Previous(idx);
#ifdef DEBUG
    prev.set_generation_mod2(generation_mod2());
#endif
    return prev;
  }
References operations_, and v8::internal::compiler::turboshaft::OperationBuffer::Previous().
Referenced by v8::internal::compiler::turboshaft::SLPTree::IsSideEffectFree(), LastOperation(), and v8::internal::compiler::turboshaft::Graph::OpIndexIterator::operator--().
RemoveLast()
void v8::internal::compiler::turboshaft::Graph::RemoveLast () [inline]
Definition at line 710 of file graph.h.
                    {
    DecrementInputUses(*AllOperations().rbegin());
    operations_.RemoveLast();
#ifdef DEBUG
    if (v8_flags.turboshaft_trace_emitted) {
      std::cout << "/!\\ Removed last emitted operation /!\\\n";
    }
#endif
  }
References AllOperations(), DecrementInputUses(), operations_, v8::internal::compiler::turboshaft::OperationBuffer::RemoveLast(), and v8::internal::v8_flags.
ReorderBlocks()
void v8::internal::compiler::turboshaft::Graph::ReorderBlocks (base::Vector< uint32_t > permutation) [inline]
Definition at line 1036 of file graph.h.
                                                       {
    DCHECK_EQ(permutation.size(), bound_blocks_.size());
    block_permutation_.resize(bound_blocks_.size());
    std::swap(block_permutation_, bound_blocks_);
    for (size_t i = 0; i < permutation.size(); ++i) {
      DCHECK_LE(0, permutation[i]);
      DCHECK_LT(permutation[i], block_permutation_.size());
      bound_blocks_[i] = block_permutation_[permutation[i]];
      bound_blocks_[i]->index_ = BlockIndex(static_cast<uint32_t>(i));
    }
  }
References block_permutation_, bound_blocks_, DCHECK_EQ, DCHECK_LE, DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::Vector< T >::size().
Replace()
template<class Op , class... Args>
void v8::internal::compiler::turboshaft::Graph::Replace (OpIndex replaced, Args... args) [inline]
Definition at line 745 of file graph.h.
                                               {
    static_assert((std::is_base_of_v<Operation, Op>));
    static_assert(std::is_trivially_destructible_v<Op>);
    const Operation& old_op = Get(replaced);
    DecrementInputUses(old_op);
    auto old_uses = old_op.saturated_use_count;
    Op* new_op;
    {
      OperationBuffer::ReplaceScope replace_scope(&operations_, replaced);
      new_op = &Op::New(this, args...);
    }
    if (!std::is_same_v<Op, DeadOp>) {
      new_op->saturated_use_count = old_uses;
    }
    IncrementInputUses(*new_op);
  }
References v8::base::args, DecrementInputUses(), Get(), IncrementInputUses(), v8::internal::anonymous_namespace{intl-objects.cc}::New(), operations_, and v8::internal::compiler::turboshaft::Operation::saturated_use_count.
Reset()
void v8::internal::compiler::turboshaft::Graph::Reset () [inline]
Definition at line 599 of file graph.h.
               {
    operations_.Reset();
    bound_blocks_.clear();
    // No need to explicitly reset `all_blocks_`, since we will placement-new
    // new blocks into it, reusing the already allocated backing storage.
    next_block_ = 0;
    op_to_block_.Reset();
    block_permutation_.clear();
    source_positions_.Reset();
    operation_origins_.Reset();
    operation_types_.Reset();
    dominator_tree_depth_ = 0;
#ifdef DEBUG
    block_type_refinement_.Reset();
    // Do not reset of graph_created_from_turbofan_ as it is propagated along
    // the phases.
#endif
  }
References block_permutation_, bound_blocks_, dominator_tree_depth_, next_block_, op_to_block_, operation_origins_, operation_types_, operations_, v8::internal::compiler::turboshaft::OperationBuffer::Reset(), and source_positions_.
set_loop_unrolling_analyzer()
void v8::internal::compiler::turboshaft::Graph::set_loop_unrolling_analyzer (LoopUnrollingAnalyzer * loop_unrolling_analyzer) [inline]
Definition at line 1098 of file graph.h.
                                                      {
    DCHECK_NULL(loop_unrolling_analyzer_);
    loop_unrolling_analyzer_ = loop_unrolling_analyzer;
  }
References DCHECK_NULL, loop_unrolling_analyzer(), and loop_unrolling_analyzer_.
Referenced by v8::internal::compiler::turboshaft::LoopUnrollingPhase::Run().
SetBlockOf()
void v8::internal::compiler::turboshaft::Graph::SetBlockOf (BlockIndex block, OpIndex op) [inline]
Definition at line 680 of file graph.h.
{ op_to_block_[op] = block; }
References op_to_block_.
Referenced by Finalize().
source_positions() [1/2]
GrowingOpIndexSidetable<SourcePosition>& v8::internal::compiler::turboshaft::Graph::source_positions () [inline]
Definition at line 1006 of file graph.h.
                                                              {
    return source_positions_;
  }
References source_positions_.
source_positions() [2/2]
const GrowingOpIndexSidetable<SourcePosition>& v8::internal::compiler::turboshaft::Graph::source_positions () const [inline]
Definition at line 1003 of file graph.h.
                                                                          {
    return source_positions_;
  }
References source_positions_.
Referenced by v8::internal::compiler::turboshaft::PipelineData::InitializeGraphComponent(), v8::internal::compiler::turboshaft::PipelineData::InitializeGraphComponentWithGraphZone(), and v8::internal::compiler::turboshaft::JSONTurboshaftGraphWriter::PrintNodes().
stack_checks_to_remove() [1/2]
ZoneAbslFlatHashSet<uint32_t>& v8::internal::compiler::turboshaft::Graph::stack_checks_to_remove () [inline]
Definition at line 1115 of file graph.h.
                                                          {
    return stack_checks_to_remove_;
  }
References stack_checks_to_remove_.
stack_checks_to_remove() [2/2]
const ZoneAbslFlatHashSet<uint32_t>& v8::internal::compiler::turboshaft::Graph::stack_checks_to_remove () const [inline]
Definition at line 1118 of file graph.h.
                                                                      {
    return stack_checks_to_remove_;
  }
References stack_checks_to_remove_.
StartBlock() [1/2]
Block& v8::internal::compiler::turboshaft::Graph::StartBlock () [inline]
Definition at line 643 of file graph.h.
{ return Get(BlockIndex(0)); }
References Get().
Referenced by v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeSpecialRPO().
StartBlock() [2/2]
const Block& v8::internal::compiler::turboshaft::Graph::StartBlock () const [inline]
Definition at line 644 of file graph.h.
{ return Get(BlockIndex(0)); }
References Get().
SwapWithCompanion()
void v8::internal::compiler::turboshaft::Graph::SwapWithCompanion () [inline]
Definition at line 1063 of file graph.h.
                           {
    Graph& companion = GetOrCreateCompanion();
    std::swap(operations_, companion.operations_);
    std::swap(bound_blocks_, companion.bound_blocks_);
    std::swap(all_blocks_, companion.all_blocks_);
    std::swap(next_block_, companion.next_block_);
    std::swap(block_permutation_, companion.block_permutation_);
    std::swap(graph_zone_, companion.graph_zone_);
    op_to_block_.SwapData(companion.op_to_block_);
    source_positions_.SwapData(companion.source_positions_);
    operation_origins_.SwapData(companion.operation_origins_);
    operation_types_.SwapData(companion.operation_types_);
#ifdef DEBUG
    std::swap(block_type_refinement_, companion.block_type_refinement_);
    // Update generation index.
    DCHECK_EQ(generation_ + 1, companion.generation_);
    generation_ = companion.generation_++;
#endif // DEBUG
    // Reseting phase-specific fields.
    loop_unrolling_analyzer_ = nullptr;
    stack_checks_to_remove_.clear();
  }
References all_blocks_, block_permutation_, bound_blocks_, DCHECK_EQ, GetOrCreateCompanion(), graph_zone_, loop_unrolling_analyzer_, next_block_, op_to_block_, operation_origins_, operation_types_, operations_, source_positions_, and stack_checks_to_remove_.
Referenced by v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::Finalize().
TurnLoopIntoMerge()
void v8::internal::compiler::turboshaft::Graph::TurnLoopIntoMerge (Block * loop) [inline]
Definition at line 819 of file graph.h.
                                      {
    DCHECK(loop->IsLoop());
    DCHECK_EQ(loop->PredecessorCount(), 1);
    loop->kind_ = Block::Kind::kMerge;
    for (Operation& op : operations(*loop)) {
      if (auto* pending_phi = op.TryCast<PendingLoopPhiOp>()) {
        Replace<PhiOp>(Index(*pending_phi),
                       base::VectorOf({pending_phi->first()}),
                       pending_phi->rep);
      }
    }
  }
References v8::internal::DCHECK(), DCHECK_EQ, Index(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::Block::kind_, v8::internal::compiler::turboshaft::Block::kMerge, operations(), v8::internal::compiler::turboshaft::Block::PredecessorCount(), and v8::base::VectorOf().
Member Data Documentation
all_blocks_
base::Vector<Block*> v8::internal::compiler::turboshaft::Graph::all_blocks_ [private]
Definition at line 1196 of file graph.h.
Referenced by AllocateNewBlocks(), NewBlock(), and SwapWithCompanion().
block_permutation_
ZoneVector<Block*> v8::internal::compiler::turboshaft::Graph::block_permutation_ [private]
Definition at line 1202 of file graph.h.
Referenced by BlockOf(), ReorderBlocks(), Reset(), and SwapWithCompanion().
bound_blocks_
ZoneVector<Block*> v8::internal::compiler::turboshaft::Graph::bound_blocks_ [private]
Definition at line 1190 of file graph.h.
Referenced by Add(), AllocateNewBlocks(), block_count(), BlockOf(), blocks(), blocks_vector(), Get(), last_block(), next_block_index(), ReorderBlocks(), Reset(), and SwapWithCompanion().
companion_
Graph* v8::internal::compiler::turboshaft::Graph::companion_ = nullptr [private]
Definition at line 1214 of file graph.h.
Referenced by GetOrCreateCompanion().
dominator_tree_depth_
uint32_t v8::internal::compiler::turboshaft::Graph::dominator_tree_depth_ = 0 [private]
Definition at line 1206 of file graph.h.
Referenced by Add(), DominatorTreeDepth(), and Reset().
graph_zone_
Zone* v8::internal::compiler::turboshaft::Graph::graph_zone_ [private]
Definition at line 1203 of file graph.h.
Referenced by AllocateNewBlocks(), GetOrCreateCompanion(), graph_zone(), and SwapWithCompanion().
loop_unrolling_analyzer_
LoopUnrollingAnalyzer* v8::internal::compiler::turboshaft::Graph::loop_unrolling_analyzer_ = nullptr [private]
Definition at line 1223 of file graph.h.
Referenced by clear_loop_unrolling_analyzer(), loop_unrolling_analyzer(), set_loop_unrolling_analyzer(), and SwapWithCompanion().
next_block_
size_t v8::internal::compiler::turboshaft::Graph::next_block_ = 0 [private]
Definition at line 1197 of file graph.h.
Referenced by NewBlock(), Reset(), and SwapWithCompanion().
op_to_block_
GrowingOpIndexSidetable<BlockIndex> v8::internal::compiler::turboshaft::Graph::op_to_block_ [private]
Definition at line 1198 of file graph.h.
Referenced by BlockIndexOf(), Reset(), SetBlockOf(), and SwapWithCompanion().
operation_origins_
GrowingOpIndexSidetable<OpIndex> v8::internal::compiler::turboshaft::Graph::operation_origins_ [private]
Definition at line 1205 of file graph.h.
Referenced by operation_origins(), Reset(), and SwapWithCompanion().
operation_types_
GrowingOpIndexSidetable<Type> v8::internal::compiler::turboshaft::Graph::operation_types_ [private]
Definition at line 1207 of file graph.h.
Referenced by operation_types(), Reset(), and SwapWithCompanion().
operations_
OperationBuffer v8::internal::compiler::turboshaft::Graph::operations_ [private]
Definition at line 1189 of file graph.h.
Referenced by Allocate(), BeginIndex(), EndIndex(), Get(), GetOrCreateCompanion(), Index(), NextIndex(), op_id_capacity(), op_id_count(), PreviousIndex(), RemoveLast(), Replace(), Reset(), and SwapWithCompanion().
source_positions_
GrowingOpIndexSidetable<SourcePosition> v8::internal::compiler::turboshaft::Graph::source_positions_ [private]
Definition at line 1204 of file graph.h.
Referenced by Reset(), source_positions(), and SwapWithCompanion().
stack_checks_to_remove_
ZoneAbslFlatHashSet<uint32_t> v8::internal::compiler::turboshaft::Graph::stack_checks_to_remove_ [private]
Definition at line 1234 of file graph.h.
Referenced by clear_stack_checks_to_remove(), stack_checks_to_remove(), and SwapWithCompanion().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/graph.h