v8::internal::wasm::WasmImportWrapperCache::ModificationScope Class Reference
#include <wasm-import-wrapper-cache.h>
Public Member Functions
ModificationScope (WasmImportWrapperCache *cache)
WasmCode * AddWrapper (WasmCompilationResult result, WasmCode::Kind kind, uint64_t signature_hash, std::shared_ptr< wasm::WasmImportWrapperHandle > wrapper_handle)
Private Attributes
WasmImportWrapperCache *const cache_
base::MutexGuard guard_
Detailed Description
Definition at line 52 of file wasm-import-wrapper-cache.h.
Constructor & Destructor Documentation
ModificationScope()
v8::internal::wasm::WasmImportWrapperCache::ModificationScope::ModificationScope (WasmImportWrapperCache * cache) [inline], [explicit]
Definition at line 54 of file wasm-import-wrapper-cache.h.
        : cache_(cache), guard_(&cache->mutex_) {}
Member Function Documentation
AddWrapper()
WasmCode * v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper (WasmCompilationResult result, WasmCode::Kind kind, uint64_t signature_hash, std::shared_ptr< wasm::WasmImportWrapperHandle > wrapper_handle)
Definition at line 87 of file wasm-import-wrapper-cache.cc.
                                                               {
  cache_->mutex_.AssertHeld();
  DCHECK_NOT_NULL(wrapper_handle);
  // Equivalent of NativeModule::AddCode().
  const CodeDesc& desc = result.code_desc;
  base::Vector<uint8_t> code_space =
      cache_->code_allocator_->AllocateForWrapper(desc.instr_size);
  // Equivalent of NativeModule::AddCodeWithCodeSpace().
  base::Vector<uint8_t> reloc_info{
      desc.buffer + desc.buffer_size - desc.reloc_size,
      static_cast<size_t>(desc.reloc_size)};
  // Contrary to the NativeModule, we don't track code size here, because we
  // have no source to attribute it to.
  const int safepoint_table_offset =
      desc.safepoint_table_size == 0 ? 0 : desc.safepoint_table_offset;
  const int handler_table_offset = desc.handler_table_offset;
  const int constant_pool_offset = desc.constant_pool_offset;
  const int code_comments_offset = desc.code_comments_offset;
  const int jump_table_info_offset = desc.jump_table_info_offset;
  const int instr_size = desc.instr_size;
  {
    WritableJitAllocation jit_allocation =
        ThreadIsolation::RegisterJitAllocation(
            reinterpret_cast<Address>(code_space.begin()), code_space.size(),
            ThreadIsolation::JitAllocationType::kWasmCode, true);
    jit_allocation.CopyCode(0, desc.buffer, desc.instr_size);
    intptr_t delta = code_space.begin() - desc.buffer;
    Address code_start = reinterpret_cast<Address>(code_space.begin());
    Address constant_pool_start = code_start + constant_pool_offset;
    for (WritableRelocIterator it(jit_allocation, code_space, reloc_info,
                                  constant_pool_start, RelocInfo::kApplyMask);
         !it.done(); it.next()) {
      // Wrappers should contain no direct calls to Wasm functions.
      DCHECK(!RelocInfo::IsWasmCall(it.rinfo()->rmode()));
      // Wrappers should not call builtins via a Wasm jump table.
      DCHECK(!RelocInfo::IsWasmStubCall(it.rinfo()->rmode()));
      it.rinfo()->apply(delta);
    }
    jit_allocation.UpdateWasmCodePointer(wrapper_handle->code_pointer(),
                                         signature_hash);
  }
  FlushInstructionCache(code_space.begin(), code_space.size());
  const int frame_slot_count = result.frame_slot_count;
  const int ool_spill_count = result.ool_spill_count;
  constexpr bool frame_has_feedback_slot = false;
  WasmCode* code = new WasmCode{nullptr /* no NativeModule */,
                                kAnonymousFuncIndex,
                                code_space,
                                frame_slot_count,
                                ool_spill_count,
                                result.tagged_parameter_slots,
                                safepoint_table_offset,
                                handler_table_offset,
                                constant_pool_offset,
                                code_comments_offset,
                                jump_table_info_offset,
                                instr_size,
                                result.protected_instructions_data.as_vector(),
                                reloc_info,
                                result.source_positions.as_vector(),
                                result.inlining_positions.as_vector(),
                                result.deopt_data.as_vector(),
                                kind,
                                ExecutionTier::kNone,
                                wasm::kNotForDebugging,
                                signature_hash,
                                frame_has_feedback_slot};
  code->Validate();
  wrapper_handle->set_code(code);
  // As an optimization, we assume that wrappers are allocated in increasing
  // memory locations.
  std::map<Address, WasmCode*>& codes = cache_->codes_;
  codes.emplace_hint(codes.end(), code->instruction_start(), code);
  return code;
}
References v8::base::Mutex::AssertHeld(), v8::base::Vector< T >::begin(), v8::internal::CodeDesc::buffer, v8::internal::CodeDesc::buffer_size, cache_, code, v8::internal::wasm::WasmImportWrapperCache::code_allocator_, v8::internal::CodeDesc::code_comments_offset, v8::internal::wasm::WasmImportWrapperCache::codes_, v8::internal::CodeDesc::constant_pool_offset, v8::internal::WritableJitAllocation::CopyCode(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::FlushInstructionCache(), v8::internal::CodeDesc::handler_table_offset, v8::internal::CodeDesc::instr_size, v8::internal::RelocInfo::IsWasmCall(), v8::internal::RelocInfo::IsWasmStubCall(), v8::internal::CodeDesc::jump_table_info_offset, v8::internal::wasm::kAnonymousFuncIndex, v8::internal::RelocInfo::kApplyMask, v8::internal::wasm::kNone, v8::internal::wasm::kNotForDebugging, v8::internal::ThreadIsolation::kWasmCode, v8::internal::wasm::WasmImportWrapperCache::mutex_, v8::internal::ThreadIsolation::RegisterJitAllocation(), v8::internal::CodeDesc::reloc_size, v8::base::internal::result, v8::internal::CodeDesc::safepoint_table_offset, v8::internal::CodeDesc::safepoint_table_size, and v8::base::Vector< T >::size().
Referenced by v8::internal::wasm::WasmImportWrapperCache::CompileWasmJsFastCallWrapper(), and v8::internal::wasm::WasmImportWrapperCache::CompileWrapper().
Member Data Documentation
cache_
WasmImportWrapperCache* const v8::internal::wasm::WasmImportWrapperCache::ModificationScope::cache_ [private]
Definition at line 63 of file wasm-import-wrapper-cache.h.
Referenced by AddWrapper().
guard_
base::MutexGuard v8::internal::wasm::WasmImportWrapperCache::ModificationScope::guard_ [private]
Definition at line 64 of file wasm-import-wrapper-cache.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-import-wrapper-cache.h
/mnt/V8SourceCode/src/wasm/wasm-import-wrapper-cache.cc