v8::internal::maglev::LoadFloat64 Class Reference
#include <maglev-ir.h>
Public Member Functions
LoadFloat64 (uint64_t bitfield, int offset)
int offset () const
Input & object_input ()
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
static constexpr int kObjectIndex = 0
Private Types
using Base = FixedInputValueNodeT< 1, LoadFloat64 >
Private Attributes
const int offset_
Additional Inherited Members
Detailed Description
Definition at line 8230 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::LoadFloat64::Base = FixedInputValueNodeT<1, LoadFloat64> [private]
Definition at line 8231 of file maglev-ir.h.
Constructor & Destructor Documentation
LoadFloat64()
v8::internal::maglev::LoadFloat64::LoadFloat64 (uint64_t bitfield, int offset) [inline], [explicit]
Definition at line 8234 of file maglev-ir.h.
      : Base(bitfield), offset_(offset) {}
Member Function Documentation
GenerateCode()
void v8::internal::maglev::LoadFloat64::GenerateCode (MaglevAssembler * , const ProcessingState &)
object_input()
Input& v8::internal::maglev::LoadFloat64::object_input () [inline]
Definition at line 8245 of file maglev-ir.h.
{ return input(kObjectIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
offset()
int v8::internal::maglev::LoadFloat64::offset () const [inline]
Definition at line 8242 of file maglev-ir.h.
{ return offset_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
options()
auto v8::internal::maglev::LoadFloat64::options () const [inline]
Definition at line 8251 of file maglev-ir.h.
{ return std::tuple{offset()}; }
PrintParams()
void v8::internal::maglev::LoadFloat64::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8196 of file maglev-ir.cc.
                                                                         {
  os << "(0x" << std::hex << offset() << std::dec << ")";
}
References offset().
SetValueLocationConstraints()
void v8::internal::maglev::LoadFloat64::SetValueLocationConstraints ()
Member Data Documentation
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::LoadFloat64::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 8240 of file maglev-ir.h.
kObjectIndex
constexpr int v8::internal::maglev::LoadFloat64::kObjectIndex = 0 [static], [constexpr]
Definition at line 8244 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::LoadFloat64::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::CanRead() | OpProperties::Float64()
Definition at line 8237 of file maglev-ir.h.
offset_
const int v8::internal::maglev::LoadFloat64::offset_ [private]
Definition at line 8254 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc