v8::internal::ClassPositions Class Reference
#include <struct.h>
Public Member Functions
int start () const
void set_start (int value)
int end () const
void set_end (int value)
void BriefPrintDetails (std::ostream &os)
Private Attributes
TaggedMember< Smi > start_
TaggedMember< Smi > end_
Friends
class TorqueGeneratedClassPositionsAsserts
Additional Inherited Members
Detailed Description
Definition at line 117 of file struct.h.
Member Function Documentation
BriefPrintDetails()
void v8::internal::ClassPositions::BriefPrintDetails (std::ostream & os)
Definition at line 1931 of file objects.cc.
                                                     {
  os << " " << start() << ", " << end();
}
References end(), and start().
end()
int v8::internal::ClassPositions::end () const [inline]
Definition at line 98 of file struct-inl.h.
{ return end_.load().value(); }
References end_.
Referenced by BriefPrintDetails().
set_end()
void v8::internal::ClassPositions::set_end (int value) [inline]
Definition at line 99 of file struct-inl.h.
                                      {
  end_.store(this, Smi::FromInt(value));
}
References end_, v8::internal::Smi::FromInt(), and v8::internal::value.
set_start()
void v8::internal::ClassPositions::set_start (int value) [inline]
Definition at line 94 of file struct-inl.h.
                                        {
  start_.store(this, Smi::FromInt(value));
}
References v8::internal::Smi::FromInt(), start_, and v8::internal::value.
start()
int v8::internal::ClassPositions::start () const [inline]
Definition at line 93 of file struct-inl.h.
{ return start_.load().value(); }
References start_.
Referenced by BriefPrintDetails().
Friends And Related Function Documentation
TorqueGeneratedClassPositionsAsserts
friend class TorqueGeneratedClassPositionsAsserts [friend]
Definition at line 132 of file struct.h.
Member Data Documentation
end_
TaggedMember<Smi> v8::internal::ClassPositions::end_ [private]
Definition at line 135 of file struct.h.
Referenced by end(), and set_end().
start_
TaggedMember<Smi> v8::internal::ClassPositions::start_ [private]
Definition at line 134 of file struct.h.
Referenced by set_start(), and start().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/struct.h
/mnt/V8SourceCode/src/objects/objects.cc
/mnt/V8SourceCode/src/objects/struct-inl.h