v8::internal::BaselineLeaveFrameDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_PARAMETER_TYPES (MachineType::Int32(), MachineType::Int32()) static const expr inline Register ParamsSizeRegister()
Static Public Member Functions
static constexpr Register WeightRegister ()
static constexpr auto registers ()
Additional Inherited Members
Detailed Description
Definition at line 2381 of file interface-descriptors.h.
Member Function Documentation
DEFINE_PARAMETER_TYPES()
v8::internal::BaselineLeaveFrameDescriptor::DEFINE_PARAMETER_TYPES (MachineType::Int32() , MachineType::Int32()) const
registers()
constexpr auto v8::internal::BaselineLeaveFrameDescriptor::registers () [inline], [static], [constexpr]
Definition at line 487 of file interface-descriptors-inl.h.
                                                       {
  // TODO(v8:11421): Implement on other platforms.
#if V8_TARGET_ARCH_IA32 || V8_TARGET_ARCH_X64 || V8_TARGET_ARCH_ARM64 || \
    V8_TARGET_ARCH_ARM || V8_TARGET_ARCH_PPC64 || V8_TARGET_ARCH_S390X || \
    V8_TARGET_ARCH_RISCV64 || V8_TARGET_ARCH_MIPS64 || \
    V8_TARGET_ARCH_LOONG64 || V8_TARGET_ARCH_RISCV32
  return RegisterArray(ParamsSizeRegister(), WeightRegister());
#else
  return DefaultRegisterArray();
#endif
}
References v8::internal::CallInterfaceDescriptor::DefaultRegisterArray(), v8::internal::RegisterArray(), and WeightRegister().
WeightRegister()
constexpr Register v8::internal::BaselineLeaveFrameDescriptor::WeightRegister () [inline], [static], [constexpr]
Definition at line 155 of file interface-descriptors-riscv-inl.h.
{ return a3; }
Referenced by v8::internal::baseline::BaselineAssembler::EmitReturn(), and registers().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h
/mnt/V8SourceCode/src/codegen/riscv/interface-descriptors-riscv-inl.h