v8::internal::compiler::turboshaft::ValueNumberingReducer< Next > Class Template Reference
#include <value-numbering-reducer.h>
Classes
struct Entry
Public Member Functions
ValueNumberingReducer ()
template<typename Op >
void UpdateEpoch (OpIndex idx)
void Bind (Block *block)
void RecordOldEpochAndSetNew (Block *block)
void ResetToBlock (Block *block)
template<class Op >
bool WillGVNOp (const Op &op)
ScopeCounter * gvn_disabled_scope ()
Static Public Member Functions
template<typename Op >
static constexpr bool CanBeGVNed ()
Private Member Functions
bool CanGVN (OpEffects effects)
template<class Op >
OpIndex AddOrFind (OpIndex op_idx)
template<class Op >
Entry * Find (const Op &op, size_t *hash_ret=nullptr)
void ClearCurrentDepthEntries ()
void RehashIfNeeded ()
template<bool same_block_only, class Op >
size_t ComputeHash (const Op &op, bool needs_epoch_check)
size_t NextEntryIndex (size_t index)
Entry * NextEntry (Entry *entry)
Entry * PrevEntry (Entry *entry)
bool is_disabled ()
Private Attributes
ZoneVector< Block * > dominator_path_ {Asm().phase_zone()}
base::Vector< Entry > table_
size_t mask_ = table_.size() - 1
size_t entry_count_ = 0
ZoneVector< Entry * > depths_heads_ {Asm().phase_zone()}
ScopeCounter disabled_scope_
int current_epoch_ = 0
Block * current_block_ = nullptr
GrowingBlockSidetable< int > block_end_epochs_
Static Private Attributes
static constexpr int kMaxEpoch = std::numeric_limits<int>::max()
Detailed Description
template<class Next>
class v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >
Definition at line 112 of file value-numbering-reducer.h.
Constructor & Destructor Documentation
ValueNumberingReducer()
template<class Next >
v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ValueNumberingReducer () [inline]
Definition at line 121 of file value-numbering-reducer.h.
: block_end_epochs_(Asm().phase_zone()) {}
Member Function Documentation
AddOrFind()
template<class Next >
template<class Op >
OpIndex v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::AddOrFind (OpIndex op_idx) [inline], [private]
Definition at line 259 of file value-numbering-reducer.h.
                                    {
    if (is_disabled()) return op_idx;
    const Op& op = Asm().output_graph().Get(op_idx).template Cast<Op>();
    if (std::is_same_v<Op, PendingLoopPhiOp> || op.IsBlockTerminator() ||
        (!CanGVN(op.Effects()) && !std::is_same_v<Op, DeoptimizeIfOp>)) {
      // GVNing DeoptimizeIf is safe, despite the fact that it has the CanDeopt
      // property, which implies CanLeaveCurrentFunction, which is generally not
      // safe to GVN.
      return op_idx;
    }
    RehashIfNeeded();
    size_t hash;
    Entry* entry = Find(op, &hash);
    if (entry->IsEmpty()) {
      // {op} is not present in the state, inserting it.
      *entry = Entry{op_idx, Asm().current_block()->index(), hash,
                     depths_heads_.back(), current_epoch_};
      depths_heads_.back() = entry;
      ++entry_count_;
      return op_idx;
    } else {
      // {op} is already present, removing it from the graph and returning the
      // previous one.
      Next::RemoveLast(op_idx);
      return entry->value;
    }
  }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::CanGVN(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::current_epoch_, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::depths_heads_, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::entry_count_, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Find(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::is_disabled(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Entry::IsEmpty(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RehashIfNeeded(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Entry::value.
Bind()
template<class Next >
void v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Bind (Block * block) [inline]
Definition at line 176 of file value-numbering-reducer.h.
                          {
    RecordOldEpochAndSetNew(block);
    Next::Bind(block);
    ResetToBlock(block);
    dominator_path_.push_back(block);
    depths_heads_.push_back(nullptr);
  }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::depths_heads_, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::dominator_path_, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RecordOldEpochAndSetNew(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ResetToBlock().
CanBeGVNed()
template<class Next >
template<typename Op >
static constexpr bool v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::CanBeGVNed () [inline], [static], [constexpr]
Definition at line 124 of file value-numbering-reducer.h.
                                     {
    constexpr Opcode opcode = operation_to_opcode_v<Op>;
    /* Throwing operations have a non-trivial lowering, so they don't work
     * with value numbering. */
    if constexpr (MayThrow(opcode)) return false;
    if constexpr (opcode == Opcode::kCatchBlockBegin) {
      /* CatchBlockBegin are never interesting to GVN, but additionally
       * split-edge can transform CatchBlockBeginOp into PhiOp, which means
       * that there is no guarantee here than {result} is indeed a
       * CatchBlockBegin. */
      return false;
    }
    if constexpr (opcode == Opcode::kComment) {
      /* We don't want to GVN comments. */
      return false;
    }
    return true;
  }
References v8::internal::compiler::turboshaft::MayThrow().
CanGVN()
template<class Next >
bool v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::CanGVN (OpEffects effects) [inline], [private]
Definition at line 250 of file value-numbering-reducer.h.
                                 {
    return effects.IsSubsetOf(OpEffects()
                                  .CanDependOnChecks()
                                  .CanChangeControlFlow()
                                  .CanAllocateWithoutIdentity()
                                  .CanReadMemory());
  }
References v8::internal::compiler::turboshaft::OpEffects::IsSubsetOf().
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::AddOrFind().
ClearCurrentDepthEntries()
template<class Next >
void v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ClearCurrentDepthEntries () [inline], [private]
Definition at line 319 of file value-numbering-reducer.h.
                                  {
    for (Entry* entry = depths_heads_.back(); entry != nullptr;) {
      entry->hash = 0;
      Entry* next_entry = entry->depth_neighboring_entry;
      entry->depth_neighboring_entry = nullptr;
      entry = next_entry;
      --entry_count_;
    }
    depths_heads_.pop_back();
    dominator_path_.pop_back();
  }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Entry::depth_neighboring_entry, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::depths_heads_, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::dominator_path_, and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::entry_count_.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ResetToBlock().
ComputeHash()
template<class Next >
template<bool same_block_only, class Op >
size_t v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ComputeHash (const Op & op, bool needs_epoch_check) [inline], [private]
Definition at line 390 of file value-numbering-reducer.h.
                                                           {
    size_t hash = op.hash_value();
    if (same_block_only) {
      hash = fast_hash_combine(Asm().current_block()->index(), hash);
    }
    if (needs_epoch_check) {
      hash = fast_hash_combine(current_epoch_, hash);
    }
    if (V8_UNLIKELY(hash == 0)) return 1;
    return hash;
  }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::current_epoch_, v8::internal::compiler::turboshaft::fast_hash_combine(), v8::internal::index, and V8_UNLIKELY.
Find()
template<class Next >
template<class Op >
Entry* v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Find (const Op & op, size_t * hash_ret = nullptr) [inline], [private]
Definition at line 290 of file value-numbering-reducer.h.
                                                        {
    bool needs_epoch_check = op.Effects().can_read_mutable_memory();
    constexpr bool same_block_only = std::is_same_v<Op, PhiOp>;
    size_t hash = ComputeHash<same_block_only>(op, needs_epoch_check);
    size_t start_index = hash & mask_;
    for (size_t i = start_index;; i = NextEntryIndex(i)) {
      Entry& entry = table_[i];
      if (entry.IsEmpty()) {
        // We didn't find {op} in {table_}. Returning where it could be
        // inserted.
        if (hash_ret) *hash_ret = hash;
        return &entry;
      }
      if (entry.hash == hash) {
        const Operation& entry_op = Asm().output_graph().Get(entry.value);
        if (entry_op.Is<Op>() &&
            (!same_block_only ||
             entry.block == Asm().current_block()->index()) &&
            (!needs_epoch_check || (current_epoch_ == entry.epoch)) &&
            entry_op.Cast<Op>().EqualsForGVN(op)) {
          return &entry;
        }
      }
      // Making sure that we don't have an infinite loop.
      DCHECK_NE(start_index, NextEntryIndex(i));
    }
  }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Entry::block, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::current_epoch_, DCHECK_NE, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Entry::epoch, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Entry::hash, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Entry::IsEmpty(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::mask_, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::NextEntryIndex(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::table_, and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Entry::value.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::AddOrFind(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::WillGVNOp().
gvn_disabled_scope()
template<class Next >
ScopeCounter* v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::gvn_disabled_scope () [inline]
Definition at line 233 of file value-numbering-reducer.h.
{ return &disabled_scope_; }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::disabled_scope_.
is_disabled()
template<class Next >
bool v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::is_disabled () [inline], [private]
Definition at line 410 of file value-numbering-reducer.h.
{ return disabled_scope_.is_active(); }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::disabled_scope_, and v8::internal::compiler::turboshaft::ScopeCounter::is_active().
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::AddOrFind().
NextEntry()
template<class Next >
Entry* v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::NextEntry (Entry * entry) [inline], [private]
Definition at line 403 of file value-numbering-reducer.h.
                                 {
    return V8_LIKELY(entry + 1 < table_.end()) ? entry + 1 : &table_[0];
  }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::table_, and V8_LIKELY.
NextEntryIndex()
template<class Next >
size_t v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::NextEntryIndex (size_t index) [inline], [private]
Definition at line 402 of file value-numbering-reducer.h.
{ return (index + 1) & mask_; }
References v8::internal::index, and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::mask_.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Find(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RehashIfNeeded().
PrevEntry()
template<class Next >
Entry* v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::PrevEntry (Entry * entry) [inline], [private]
Definition at line 406 of file value-numbering-reducer.h.
                                 {
    return V8_LIKELY(entry > table_.begin()) ? entry - 1 : table_.end() - 1;
  }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::table_, and V8_LIKELY.
RecordOldEpochAndSetNew()
template<class Next >
void v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RecordOldEpochAndSetNew (Block * block) [inline]
Definition at line 184 of file value-numbering-reducer.h.
                                             {
    // Recording epoch for previous block.
    if (current_block_ != nullptr) {
      block_end_epochs_[current_block_->index()] = current_epoch_;
    }
    int max_predecessor_epoch = 0;
    for (Block* pred : block->Predecessors()) {
      if (block_end_epochs_[pred->index()] != 0) {
        max_predecessor_epoch = std::max<int>(max_predecessor_epoch,
                                              block_end_epochs_[pred->index()]);
      }
    }
    current_epoch_ = max_predecessor_epoch;
    current_block_ = block;
    if (block->IsLoop()) {
      // We assume that the backedge might invalidate everything that requires
      // an epoch check. So, we increment the current_epoch, thus guaranteeing
      // that we won't replace any CanRead operation in the loop by an operation
      // from before the loop.
      current_epoch_++;
    }
  }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::block_end_epochs_, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::current_block_, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::current_epoch_, v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::Block::IsLoop(), and v8::internal::compiler::turboshaft::Block::Predecessors().
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Bind().
RehashIfNeeded()
template<class Next >
void v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RehashIfNeeded () [inline], [private]
Definition at line 332 of file value-numbering-reducer.h.
                        {
    if (V8_LIKELY(table_.size() - (table_.size() / 4) > entry_count_)) return;
    base::Vector<Entry> new_table = table_ =
        Asm().phase_zone()->template NewVector<Entry>(table_.size() * 2);
    size_t mask = mask_ = table_.size() - 1;
    for (size_t depth_idx = 0; depth_idx < depths_heads_.size(); depth_idx++) {
      // It's important to fill the new hash by inserting data in increasing
      // depth order, in order to avoid holes when later calling
      // ClearCurrentDepthEntries. Consider for instance:
      //
      // ---+------+------+------+----
      // | a1 | a2 | a3 |
      // ---+------+------+------+----
      //
      // Where a1, a2 and a3 have the same hash. By construction, we know that
      // depth(a1) <= depth(a2) <= depth(a3). If, when re-hashing, we were to
      // insert them in another order, say:
      //
      // ---+------+------+------+----
      // | a3 | a1 | a2 |
      // ---+------+------+------+----
      //
      // Then, when we'll call ClearCurrentDepthEntries to remove entries from
      // a3's depth, we'll get this:
      //
      // ---+------+------+------+----
      // | null | a1 | a2 |
      // ---+------+------+------+----
      //
      // And, when looking if a1 is in the hash, we'd find a "null" where we
      // expect it, and assume that it's not present. If, instead, we always
      // conserve the increasing depth order, then when removing a3, we'd get:
      //
      // ---+------+------+------+----
      // | a1 | a2 | null |
      // ---+------+------+------+----
      //
      // Where we can still find a1 and a2.
      Entry* entry = depths_heads_[depth_idx];
      depths_heads_[depth_idx] = nullptr;
      while (entry != nullptr) {
        for (size_t i = entry->hash & mask;; i = NextEntryIndex(i)) {
          if (new_table[i].hash == 0) {
            new_table[i] = *entry;
            Entry* next_entry = entry->depth_neighboring_entry;
            new_table[i].depth_neighboring_entry = depths_heads_[depth_idx];
            depths_heads_[depth_idx] = &new_table[i];
            entry = next_entry;
            break;
          }
        }
      }
    }
  }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Entry::depth_neighboring_entry, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::depths_heads_, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::entry_count_, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Entry::hash, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::mask_, v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::NextEntryIndex(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::table_, and V8_LIKELY.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::AddOrFind().
ResetToBlock()
template<class Next >
void v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ResetToBlock (Block * block) [inline]
Definition at line 210 of file value-numbering-reducer.h.
                                  {
    Block* target = block->GetDominator();
    while (!dominator_path_.empty() && target != nullptr &&
           dominator_path_.back() != target) {
      if (dominator_path_.back()->Depth() > target->Depth()) {
        ClearCurrentDepthEntries();
      } else if (dominator_path_.back()->Depth() < target->Depth()) {
        target = target->GetDominator();
      } else {
        // {target} and {dominator_path.back} have the same depth but are not
        // equal, so we go one level up for both.
        ClearCurrentDepthEntries();
        target = target->GetDominator();
      }
    }
  }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ClearCurrentDepthEntries(), v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::Depth(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::dominator_path_, and v8::internal::compiler::turboshaft::RandomAccessStackDominatorNode< Derived >::GetDominator().
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Bind().
UpdateEpoch()
template<class Next >
template<typename Op >
void v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::UpdateEpoch (OpIndex idx) [inline]
Definition at line 159 of file value-numbering-reducer.h.
                                {
    if constexpr (std::is_same_v<Op, RetainOp>) {
      // RetainOp has CanWrite property but doesn't actually write.
      return;
    }
    if (std::optional<OpEffects> effects = Op::EffectsIfStatic()) {
      if (effects.value().can_write()) {
        current_epoch_++;
      }
    } else {
      const Op& op = Asm().Get(idx).template Cast<Op>();
      if (op.Effects().can_write()) {
        current_epoch_++;
      }
    }
  }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::current_epoch_.
WillGVNOp()
template<class Next >
template<class Op >
bool v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::WillGVNOp (const Op & op) [inline]
Definition at line 228 of file value-numbering-reducer.h.
                               {
    Entry* entry = Find(op);
    return !entry->IsEmpty();
  }
References v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Find(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Entry::IsEmpty().
Member Data Documentation
block_end_epochs_
template<class Next >
GrowingBlockSidetable<int> v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::block_end_epochs_ [private]
Definition at line 423 of file value-numbering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RecordOldEpochAndSetNew().
current_block_
template<class Next >
Block* v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::current_block_ = nullptr [private]
Definition at line 422 of file value-numbering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RecordOldEpochAndSetNew().
current_epoch_
template<class Next >
int v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::current_epoch_ = 0 [private]
Definition at line 420 of file value-numbering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::AddOrFind(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ComputeHash(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Find(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RecordOldEpochAndSetNew(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::UpdateEpoch().
depths_heads_
template<class Next >
ZoneVector<Entry*> v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::depths_heads_ {Asm().phase_zone()} [private]
Definition at line 418 of file value-numbering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::AddOrFind(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Bind(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ClearCurrentDepthEntries(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RehashIfNeeded().
disabled_scope_
template<class Next >
ScopeCounter v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::disabled_scope_ [private]
Definition at line 419 of file value-numbering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::gvn_disabled_scope(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::is_disabled().
dominator_path_
template<class Next >
ZoneVector<Block*> v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::dominator_path_ {Asm().phase_zone()} [private]
Definition at line 412 of file value-numbering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Bind(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ClearCurrentDepthEntries(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ResetToBlock().
entry_count_
template<class Next >
size_t v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::entry_count_ = 0 [private]
Definition at line 417 of file value-numbering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::AddOrFind(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::ClearCurrentDepthEntries(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RehashIfNeeded().
kMaxEpoch
template<class Next >
constexpr int v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::kMaxEpoch = std::numeric_limits<int>::max() [static], [constexpr], [private]
Definition at line 236 of file value-numbering-reducer.h.
mask_
template<class Next >
size_t v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::mask_ = table_.size() - 1 [private]
Definition at line 416 of file value-numbering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Find(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::NextEntryIndex(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RehashIfNeeded().
table_
template<class Next >
base::Vector<Entry> v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::table_ [private]
Initial value:
= Asm().phase_zone()->template NewVector<Entry>(
      base::bits::RoundUpToPowerOfTwo(
          std::max<size_t>(128, Asm().input_graph().op_id_capacity() / 2)))
Definition at line 413 of file value-numbering-reducer.h.
Referenced by v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::Find(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::NextEntry(), v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::PrevEntry(), and v8::internal::compiler::turboshaft::ValueNumberingReducer< Next >::RehashIfNeeded().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/assembler.h
/mnt/V8SourceCode/src/compiler/turboshaft/value-numbering-reducer.h