v8::internal::LoopChoiceNode Class Reference
#include <regexp-nodes.h>
Public Member Functions
LoopChoiceNode (bool body_can_be_zero_length, bool read_backward, int min_loop_iterations, Zone *zone)
void AddLoopAlternative (GuardedAlternative alt)
void AddContinueAlternative (GuardedAlternative alt)
void Emit (RegExpCompiler *compiler, Trace *trace) override
void GetQuickCheckDetails (QuickCheckDetails *details, RegExpCompiler *compiler, int characters_filled_in, bool not_at_start) override
void GetQuickCheckDetailsFromLoopEntry (QuickCheckDetails *details, RegExpCompiler *compiler, int characters_filled_in, bool not_at_start) override
void FillInBMInfo (Isolate *isolate, int offset, int budget, BoyerMooreLookahead *bm, bool not_at_start) override
EatsAtLeastInfo EatsAtLeastFromLoopEntry () override
RegExpNode * loop_node ()
RegExpNode * continue_node ()
bool body_can_be_zero_length ()
int min_loop_iterations () const
bool read_backward () override
LoopChoiceNode * AsLoopChoiceNode () override
void Accept (NodeVisitor *visitor) override
RegExpNode * FilterOneByte (int depth, RegExpCompiler *compiler) override
Private Member Functions
void AddAlternative (GuardedAlternative node)
Private Attributes
RegExpNode * loop_node_
RegExpNode * continue_node_
bool body_can_be_zero_length_
bool read_backward_
bool traversed_loop_initialization_node_
int min_loop_iterations_
Friends
class IterationDecrementer
class LoopInitializationMarker
Additional Inherited Members
Detailed Description
Definition at line 764 of file regexp-nodes.h.
Constructor & Destructor Documentation
LoopChoiceNode()
v8::internal::LoopChoiceNode::LoopChoiceNode (bool body_can_be_zero_length, bool read_backward, int min_loop_iterations, Zone * zone) [inline]
Definition at line 766 of file regexp-nodes.h.
      : ChoiceNode(2, zone),
        loop_node_(nullptr),
        continue_node_(nullptr),
        body_can_be_zero_length_(body_can_be_zero_length),
        read_backward_(read_backward),
        traversed_loop_initialization_node_(false),
        min_loop_iterations_(min_loop_iterations) {}
Member Function Documentation
Accept()
void v8::internal::LoopChoiceNode::Accept (NodeVisitor * visitor) [override], [virtual]
Reimplemented from v8::internal::ChoiceNode.
AddAlternative()
void v8::internal::LoopChoiceNode::AddAlternative (GuardedAlternative node) [inline], [private]
Definition at line 801 of file regexp-nodes.h.
                                               {
    ChoiceNode::AddAlternative(node);
  }
References v8::internal::ChoiceNode::AddAlternative().
Referenced by AddContinueAlternative(), and AddLoopAlternative().
AddContinueAlternative()
void v8::internal::LoopChoiceNode::AddContinueAlternative (GuardedAlternative alt)
Definition at line 2703 of file regexp-compiler.cc.
                                                                  {
  DCHECK_NULL(continue_node_);
  AddAlternative(alt);
  continue_node_ = alt.node();
}
References AddAlternative(), continue_node_, DCHECK_NULL, and v8::internal::GuardedAlternative::node().
AddLoopAlternative()
void v8::internal::LoopChoiceNode::AddLoopAlternative (GuardedAlternative alt)
Definition at line 2697 of file regexp-compiler.cc.
                                                              {
  DCHECK_NULL(loop_node_);
  AddAlternative(alt);
  loop_node_ = alt.node();
}
References AddAlternative(), DCHECK_NULL, loop_node_, and v8::internal::GuardedAlternative::node().
AsLoopChoiceNode()
LoopChoiceNode* v8::internal::LoopChoiceNode::AsLoopChoiceNode () [inline], [override]
Definition at line 793 of file regexp-nodes.h.
{ return this; }
body_can_be_zero_length()
bool v8::internal::LoopChoiceNode::body_can_be_zero_length () [inline]
Definition at line 790 of file regexp-nodes.h.
{ return body_can_be_zero_length_; }
continue_node()
RegExpNode* v8::internal::LoopChoiceNode::continue_node () [inline]
Definition at line 789 of file regexp-nodes.h.
{ return continue_node_; }
Referenced by v8::internal::Analysis< Propagators >::VisitLoopChoice(), v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitLoopChoiceContinueNode(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitLoopChoiceContinueNode().
EatsAtLeastFromLoopEntry()
EatsAtLeastInfo v8::internal::LoopChoiceNode::EatsAtLeastFromLoopEntry () [override], [virtual]
Reimplemented from v8::internal::RegExpNode.
Definition at line 1526 of file regexp-compiler.cc.
                                                         {
  DCHECK_EQ(alternatives_->length(), 2); // There's just loop and continue.
  if (read_backward()) {
    // The eats_at_least value is not used if reading backward. The
    // EatsAtLeastPropagator should've zeroed it as well.
    DCHECK_EQ(eats_at_least_info()->eats_at_least_from_possibly_start, 0);
    DCHECK_EQ(eats_at_least_info()->eats_at_least_from_not_start, 0);
    return {};
  }
  // Figure out how much the loop body itself eats, not including anything in
  // the continuation case. In general, the nodes in the loop body should report
  // that they eat at least the number eaten by the continuation node, since any
  // successful match in the loop body must also include the continuation node.
  // However, in some cases involving positive lookaround, the loop body under-
  // reports its appetite, so use saturated math here to avoid negative numbers.
  // For this to work correctly, we explicitly need to use signed integers here.
  uint8_t loop_body_from_not_start = base::saturated_cast<uint8_t>(
      static_cast<int>(loop_node_->EatsAtLeast(true)) -
      static_cast<int>(continue_node_->EatsAtLeast(true)));
  uint8_t loop_body_from_possibly_start = base::saturated_cast<uint8_t>(
      static_cast<int>(loop_node_->EatsAtLeast(false)) -
      static_cast<int>(continue_node_->EatsAtLeast(true)));
  // Limit the number of loop iterations to avoid overflow in subsequent steps.
  int loop_iterations = base::saturated_cast<uint8_t>(min_loop_iterations());
  EatsAtLeastInfo result;
  result.eats_at_least_from_not_start =
      base::saturated_cast<uint8_t>(loop_iterations * loop_body_from_not_start +
                                    continue_node_->EatsAtLeast(true));
  if (loop_iterations > 0 && loop_body_from_possibly_start > 0) {
    // First loop iteration eats at least one, so all subsequent iterations
    // and the after-loop chunk are guaranteed to not be at the start.
    result.eats_at_least_from_possibly_start = base::saturated_cast<uint8_t>(
        loop_body_from_possibly_start +
        (loop_iterations - 1) * loop_body_from_not_start +
        continue_node_->EatsAtLeast(true));
  } else {
    // Loop body might eat nothing, so only continue node contributes.
    result.eats_at_least_from_possibly_start =
        continue_node_->EatsAtLeast(false);
  }
  return result;
}
References v8::internal::ChoiceNode::alternatives_, continue_node_, DCHECK_EQ, v8::internal::RegExpNode::eats_at_least_info(), v8::internal::RegExpNode::EatsAtLeast(), loop_node_, min_loop_iterations(), read_backward(), and v8::base::internal::result.
Emit()
void v8::internal::LoopChoiceNode::Emit (RegExpCompiler * compiler, Trace * trace) [override], [virtual]
Reimplemented from v8::internal::ChoiceNode.
Definition at line 2709 of file regexp-compiler.cc.
                                                                {
  RegExpMacroAssembler* macro_assembler = compiler->macro_assembler();
  if (trace->fixed_length_loop_state() != nullptr &&
      trace->fixed_length_loop_state()->loop_choice_node() == this) {
    // Back edge of fixed length optimized loop node graph.
    int text_length =
        FixedLengthLoopLengthForAlternative(&(alternatives_->at(0)));
    DCHECK_NE(kNodeIsTooComplexForFixedLengthLoops, text_length);
    // Update the counter-based backtracking info on the stack. This is an
    // optimization for fixed length loops (see below).
    DCHECK(trace->cp_offset() == text_length);
    macro_assembler->AdvanceCurrentPosition(text_length);
    trace->fixed_length_loop_state()->GoToLoopTopLabel(macro_assembler);
    return;
  }
  DCHECK_NULL(trace->fixed_length_loop_state());
  if (!trace->is_trivial()) {
    trace->Flush(compiler, this);
    return;
  }
  ChoiceNode::Emit(compiler, trace);
}
References v8::internal::RegExpMacroAssembler::AdvanceCurrentPosition(), v8::internal::ChoiceNode::alternatives_, v8::internal::Trace::cp_offset(), v8::internal::DCHECK(), DCHECK_NE, DCHECK_NULL, v8::internal::ChoiceNode::Emit(), v8::internal::Trace::fixed_length_loop_state(), v8::internal::ChoiceNode::FixedLengthLoopLengthForAlternative(), v8::internal::Trace::Flush(), v8::internal::FixedLengthLoopState::GoToLoopTopLabel(), v8::internal::Trace::is_trivial(), v8::internal::RegExpNode::kNodeIsTooComplexForFixedLengthLoops, v8::internal::FixedLengthLoopState::loop_choice_node(), and v8::internal::RegExpCompiler::macro_assembler().
FillInBMInfo()
void v8::internal::LoopChoiceNode::FillInBMInfo (Isolate * isolate, int offset, int budget, BoyerMooreLookahead * bm, bool not_at_start) [override], [virtual]
Reimplemented from v8::internal::ChoiceNode.
Definition at line 2141 of file regexp-compiler.cc.
                                                                              {
  if (body_can_be_zero_length_ || budget <= 0) {
    bm->SetRest(offset);
    SaveBMInfo(bm, not_at_start, offset);
    return;
  }
  ChoiceNode::FillInBMInfo(isolate, offset, budget - 1, bm, not_at_start);
  SaveBMInfo(bm, not_at_start, offset);
}
References body_can_be_zero_length_, v8::internal::ChoiceNode::FillInBMInfo(), v8::internal::ChoiceNode::not_at_start(), v8::internal::RegExpNode::SaveBMInfo(), and v8::internal::BoyerMooreLookahead::SetRest().
FilterOneByte()
RegExpNode * v8::internal::LoopChoiceNode::FilterOneByte (int depth, RegExpCompiler * compiler) [override], [virtual]
Reimplemented from v8::internal::ChoiceNode.
Definition at line 2002 of file regexp-compiler.cc.
                                                                             {
  if (info()->replacement_calculated) return replacement();
  if (depth < 0) return this;
  if (info()->visited) return this;
  {
    VisitMarker marker(info());
    RegExpNode* continue_replacement =
        continue_node_->FilterOneByte(depth - 1, compiler);
    // If we can't continue after the loop then there is no sense in doing the
    // loop.
    if (continue_replacement == nullptr) return set_replacement(nullptr);
  }
  return ChoiceNode::FilterOneByte(depth - 1, compiler);
}
References continue_node_, v8::internal::RegExpNode::FilterOneByte(), v8::internal::ChoiceNode::FilterOneByte(), v8::internal::RegExpNode::info(), v8::internal::RegExpNode::replacement(), and v8::internal::RegExpNode::set_replacement().
GetQuickCheckDetails()
void v8::internal::LoopChoiceNode::GetQuickCheckDetails (QuickCheckDetails * details, RegExpCompiler * compiler, int characters_filled_in, bool not_at_start) [override], [virtual]
Reimplemented from v8::internal::ChoiceNode.
Definition at line 2092 of file regexp-compiler.cc.
                                                             {
  if (body_can_be_zero_length_ || info()->visited) return;
  not_at_start = not_at_start || this->not_at_start();
  DCHECK_EQ(alternatives_->length(), 2); // There's just loop and continue.
  if (traversed_loop_initialization_node_ && min_loop_iterations_ > 0 &&
      loop_node_->EatsAtLeast(not_at_start) >
          continue_node_->EatsAtLeast(true)) {
    // Loop body is guaranteed to execute at least once, and consume characters
    // when it does, meaning the only possible quick checks from this point
    // begin with the loop body. We may recursively visit this LoopChoiceNode,
    // but we temporarily decrease its minimum iteration counter so we know when
    // to check the continue case.
    IterationDecrementer next_iteration(this);
    loop_node_->GetQuickCheckDetails(details, compiler, characters_filled_in,
                                     not_at_start);
  } else {
    // Might not consume anything in the loop body, so treat it like a normal
    // ChoiceNode (and don't recursively visit this node again).
    VisitMarker marker(info());
    ChoiceNode::GetQuickCheckDetails(details, compiler, characters_filled_in,
                                     not_at_start);
  }
}
References v8::internal::ChoiceNode::alternatives_, body_can_be_zero_length_, continue_node_, DCHECK_EQ, v8::internal::RegExpNode::EatsAtLeast(), v8::internal::ChoiceNode::GetQuickCheckDetails(), v8::internal::RegExpNode::GetQuickCheckDetails(), v8::internal::RegExpNode::info(), loop_node_, min_loop_iterations_, v8::internal::ChoiceNode::not_at_start(), and traversed_loop_initialization_node_.
Referenced by GetQuickCheckDetailsFromLoopEntry().
GetQuickCheckDetailsFromLoopEntry()
void v8::internal::LoopChoiceNode::GetQuickCheckDetailsFromLoopEntry (QuickCheckDetails * details, RegExpCompiler * compiler, int characters_filled_in, bool not_at_start) [override], [virtual]
Reimplemented from v8::internal::RegExpNode.
Definition at line 2119 of file regexp-compiler.cc.
                                                 {
  if (traversed_loop_initialization_node_) {
    // We already entered this loop once, exited via its continuation node, and
    // followed an outer loop's back-edge to before the loop entry point. We
    // could try to reset the minimum iteration count to its starting value at
    // this point, but that seems like more trouble than it's worth. It's safe
    // to keep going with the current (possibly reduced) minimum iteration
    // count.
    GetQuickCheckDetails(details, compiler, characters_filled_in, not_at_start);
  } else {
    // We are entering a loop via its counter initialization action, meaning we
    // are guaranteed to run the loop body at least some minimum number of times
    // before running the continuation node. Set a flag so that this node knows
    // (now and any times we visit it again recursively) that it was entered
    // from the top.
    LoopInitializationMarker marker(this);
    GetQuickCheckDetails(details, compiler, characters_filled_in, not_at_start);
  }
}
References GetQuickCheckDetails(), v8::internal::ChoiceNode::not_at_start(), and traversed_loop_initialization_node_.
loop_node()
RegExpNode* v8::internal::LoopChoiceNode::loop_node () [inline]
Definition at line 788 of file regexp-nodes.h.
{ return loop_node_; }
Referenced by v8::internal::Analysis< Propagators >::VisitLoopChoice(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::AssertionPropagator::VisitLoopChoiceLoopNode().
min_loop_iterations()
int v8::internal::LoopChoiceNode::min_loop_iterations () const [inline]
Definition at line 791 of file regexp-nodes.h.
{ return min_loop_iterations_; }
Referenced by EatsAtLeastFromLoopEntry().
read_backward()
bool v8::internal::LoopChoiceNode::read_backward () [inline], [override], [virtual]
Reimplemented from v8::internal::ChoiceNode.
Definition at line 792 of file regexp-nodes.h.
{ return read_backward_; }
Referenced by EatsAtLeastFromLoopEntry(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitLoopChoiceContinueNode().
Friends And Related Function Documentation
IterationDecrementer
friend class IterationDecrementer [friend]
Definition at line 823 of file regexp-nodes.h.
LoopInitializationMarker
friend class LoopInitializationMarker [friend]
Definition at line 824 of file regexp-nodes.h.
Member Data Documentation
body_can_be_zero_length_
bool v8::internal::LoopChoiceNode::body_can_be_zero_length_ [private]
Definition at line 807 of file regexp-nodes.h.
Referenced by FillInBMInfo(), and GetQuickCheckDetails().
continue_node_
RegExpNode* v8::internal::LoopChoiceNode::continue_node_ [private]
Definition at line 806 of file regexp-nodes.h.
Referenced by AddContinueAlternative(), EatsAtLeastFromLoopEntry(), FilterOneByte(), and GetQuickCheckDetails().
loop_node_
RegExpNode* v8::internal::LoopChoiceNode::loop_node_ [private]
Definition at line 805 of file regexp-nodes.h.
Referenced by AddLoopAlternative(), EatsAtLeastFromLoopEntry(), and GetQuickCheckDetails().
min_loop_iterations_
int v8::internal::LoopChoiceNode::min_loop_iterations_ [private]
Definition at line 821 of file regexp-nodes.h.
Referenced by GetQuickCheckDetails(), v8::internal::IterationDecrementer::IterationDecrementer(), and v8::internal::IterationDecrementer::~IterationDecrementer().
read_backward_
bool v8::internal::LoopChoiceNode::read_backward_ [private]
Definition at line 808 of file regexp-nodes.h.
traversed_loop_initialization_node_
bool v8::internal::LoopChoiceNode::traversed_loop_initialization_node_ [private]
Definition at line 815 of file regexp-nodes.h.
Referenced by GetQuickCheckDetails(), GetQuickCheckDetailsFromLoopEntry(), v8::internal::LoopInitializationMarker::LoopInitializationMarker(), and v8::internal::LoopInitializationMarker::~LoopInitializationMarker().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-nodes.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc