v8::internal::StringForwardingTable::BlockVector Class Reference
#include <string-forwarding-table-inl.h>
Public Types
using Block = StringForwardingTable::Block
using Allocator = std::allocator< Block * >
Public Member Functions
BlockVector (size_t capacity)
~BlockVector ()
size_t capacity () const
Block * LoadBlock (size_t index, AcquireLoadTag)
Block * LoadBlock (size_t index)
void AddBlock (std::unique_ptr< Block > block)
size_t size () const
Static Public Member Functions
static std::unique_ptr< BlockVector > Grow (BlockVector *data, size_t capacity, const base::Mutex &mutex)
Private Attributes
V8_NO_UNIQUE_ADDRESS Allocator allocator_
const size_t capacity_
std::atomic< size_t > size_
Block ** begin_
Detailed Description
Definition at line 262 of file string-forwarding-table-inl.h.
Member Typedef Documentation
Allocator
using v8::internal::StringForwardingTable::BlockVector::Allocator = std::allocator<Block*>
Definition at line 265 of file string-forwarding-table-inl.h.
Block
using v8::internal::StringForwardingTable::BlockVector::Block = StringForwardingTable::Block
Definition at line 264 of file string-forwarding-table-inl.h.
Constructor & Destructor Documentation
BlockVector()
v8::internal::StringForwardingTable::BlockVector::BlockVector (size_t capacity) [explicit]
Definition at line 135 of file string-forwarding-table.cc.
    : allocator_(Allocator()), capacity_(capacity), size_(0) {
  begin_ = allocator_.allocate(capacity);
}
References allocator_, begin_, and capacity().
 BlockVector()
v8::internal::StringForwardingTable::BlockVector::~BlockVector ()
Definition at line 140 of file string-forwarding-table.cc.
                                               {
  allocator_.deallocate(begin_, capacity());
}
Member Function Documentation
AddBlock()
void v8::internal::StringForwardingTable::BlockVector::AddBlock (std::unique_ptr< Block > block) [inline]
Definition at line 281 of file string-forwarding-table-inl.h.
                                            {
    DCHECK_LT(size(), capacity());
    base::AsAtomicPointer::Release_Store(&begin_[size_], block.release());
    size_++;
  }
References DCHECK_LT, v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store(), and v8::internal::StringForwardingTable::size().
Referenced by v8::internal::StringForwardingTable::EnsureCapacity(), and v8::internal::StringForwardingTable::InitializeBlockVector().
capacity()
size_t v8::internal::StringForwardingTable::BlockVector::capacity () const [inline]
Definition at line 269 of file string-forwarding-table-inl.h.
{ return capacity_; }
Referenced by BlockVector(), and v8::internal::StringForwardingTable::EnsureCapacity().
Grow()
std::unique_ptr< StringForwardingTable::BlockVector > v8::internal::StringForwardingTable::BlockVector::Grow (StringForwardingTable::BlockVector * data, size_t capacity, const base::Mutex & mutex) [static]
Definition at line 146 of file string-forwarding-table.cc.
                            {
  mutex.AssertHeld();
  std::unique_ptr<BlockVector> new_data =
      std::make_unique<BlockVector>(capacity);
  // Copy pointers to blocks from the old to the new vector.
  for (size_t i = 0; i < data->size(); i++) {
    new_data->begin_[i] = data->LoadBlock(i);
  }
  new_data->size_ = data->size();
  return new_data;
}
References v8::base::Mutex::AssertHeld(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, LoadBlock(), and size().
Referenced by v8::internal::StringForwardingTable::EnsureCapacity().
LoadBlock() [1/2]
Block* v8::internal::StringForwardingTable::BlockVector::LoadBlock (size_t index) [inline]
Definition at line 276 of file string-forwarding-table-inl.h.
                                 {
    DCHECK_LT(index, size());
    return begin_[index];
  }
References DCHECK_LT, v8::internal::index, and v8::internal::StringForwardingTable::size().
LoadBlock() [2/2]
Block* v8::internal::StringForwardingTable::BlockVector::LoadBlock (size_t index, AcquireLoadTag) [inline]
Definition at line 271 of file string-forwarding-table-inl.h.
                                                 {
    DCHECK_LT(index, size());
    return base::AsAtomicPointer::Acquire_Load(&begin_[index]);
  }
References v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load(), DCHECK_LT, v8::internal::index, and v8::internal::StringForwardingTable::size().
Referenced by v8::internal::StringForwardingTable::AddExternalResourceAndHash(), v8::internal::StringForwardingTable::AddForwardString(), Grow(), v8::internal::StringForwardingTable::IterateElements(), v8::internal::StringForwardingTable::Reset(), v8::internal::StringForwardingTable::UpdateAfterFullEvacuation(), v8::internal::StringForwardingTable::UpdateAfterYoungEvacuation(), and v8::internal::StringForwardingTable::~StringForwardingTable().
size()
size_t v8::internal::StringForwardingTable::BlockVector::size () const [inline]
Definition at line 290 of file string-forwarding-table-inl.h.
{ return size_; }
Referenced by v8::internal::StringForwardingTable::EnsureCapacity(), Grow(), v8::internal::StringForwardingTable::IterateElements(), v8::internal::StringForwardingTable::Reset(), v8::internal::StringForwardingTable::UpdateAfterFullEvacuation(), v8::internal::StringForwardingTable::UpdateAfterYoungEvacuation(), and v8::internal::StringForwardingTable::~StringForwardingTable().
Member Data Documentation
allocator_
V8_NO_UNIQUE_ADDRESS Allocator v8::internal::StringForwardingTable::BlockVector::allocator_ [private]
Definition at line 293 of file string-forwarding-table-inl.h.
Referenced by BlockVector().
begin_
Block** v8::internal::StringForwardingTable::BlockVector::begin_ [private]
Definition at line 296 of file string-forwarding-table-inl.h.
Referenced by BlockVector().
capacity_
const size_t v8::internal::StringForwardingTable::BlockVector::capacity_ [private]
Definition at line 294 of file string-forwarding-table-inl.h.
size_
std::atomic<size_t> v8::internal::StringForwardingTable::BlockVector::size_ [private]
Definition at line 295 of file string-forwarding-table-inl.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string-forwarding-table-inl.h
/mnt/V8SourceCode/src/objects/string-forwarding-table.cc