v8::internal::compiler::JSTypedArrayRef Class Reference
#include <heap-refs.h>
Public Member Functions
IndirectHandle< JSTypedArray > object () const
bool is_on_heap () const
size_t length (JSHeapBroker *broker) const
size_t byte_length () const
ElementsKind elements_kind (JSHeapBroker *broker) const
void * data_ptr () const
HeapObjectRef buffer (JSHeapBroker *broker) const
bool is_off_heap_non_rab_gsab (JSHeapBroker *broker) const
Detailed Description
Definition at line 1223 of file heap-refs.h.
Member Function Documentation
buffer()
HeapObjectRef v8::internal::compiler::JSTypedArrayRef::buffer (JSHeapBroker * broker) const
Definition at line 1850 of file heap-refs.cc.
                                                                {
  CHECK(!is_on_heap());
  // Immutable after initialization.
  return MakeRef<HeapObject>(broker, object()->buffer());
}
References broker(), CHECK, and is_on_heap().
byte_length()
size_t v8::internal::compiler::JSTypedArrayRef::byte_length () const
Definition at line 1840 of file heap-refs.cc.
                                          {
  // Immutable after initialization (since this is not used for RAB/GSAB).
  return object()->byte_length();
}
References object().
Referenced by v8::internal::compiler::TypedOptimization::ReduceTypedArrayLength().
data_ptr()
void * v8::internal::compiler::JSTypedArrayRef::data_ptr () const
Definition at line 1856 of file heap-refs.cc.
                                      {
  CHECK(!is_on_heap());
  // Underlying field written 1. during initialization or 2. protected by the
  // is_on_heap release/acquire semantics (external_pointer store happens-before
  // base_pointer store, and this external_pointer load happens-after
  // base_pointer load).
  static_assert(JSTypedArray::kOffHeapDataPtrEqualsExternalPointer);
  return object()->DataPtr();
}
References CHECK, is_on_heap(), v8::internal::JSTypedArray::kOffHeapDataPtrEqualsExternalPointer, and object().
elements_kind()
ElementsKind v8::internal::compiler::JSTypedArrayRef::elements_kind (JSHeapBroker * broker) const
Definition at line 1845 of file heap-refs.cc.
                                                                      {
  // Immutable after initialization.
  return map(broker).elements_kind();
}
References broker(), v8::internal::compiler::MapRef::elements_kind(), and v8::internal::compiler::HeapObjectRef::map().
Referenced by length(), and v8::internal::compiler::TypedOptimization::ReduceTypedArrayLength().
is_off_heap_non_rab_gsab()
bool v8::internal::compiler::JSTypedArrayRef::is_off_heap_non_rab_gsab (JSHeapBroker * broker) const [inline]
Definition at line 1236 of file heap-refs.h.
                                                            {
    return !is_on_heap() &&
           !IsRabGsabTypedArrayElementsKind(elements_kind(broker));
  }
References broker(), and v8::internal::IsRabGsabTypedArrayElementsKind().
is_on_heap()
bool v8::internal::compiler::JSTypedArrayRef::is_on_heap () const
Definition at line 1830 of file heap-refs.cc.
                                       {
  // Underlying field written 1. during initialization or 2. with release-store.
  return object()->is_on_heap(kAcquireLoad);
}
References v8::kAcquireLoad, and object().
Referenced by buffer(), data_ptr(), and v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::GetTypedArrayConstant().
length()
size_t v8::internal::compiler::JSTypedArrayRef::length (JSHeapBroker * broker) const
Definition at line 1835 of file heap-refs.cc.
                                                         {
  return object()->byte_length() /
         ElementsKindToByteSize(elements_kind(broker));
}
References broker(), elements_kind(), v8::internal::ElementsKindToByteSize(), and object().
object()
IndirectHandle<JSTypedArray> v8::internal::compiler::JSTypedArrayRef::object () const
Referenced by byte_length(), data_ptr(), is_on_heap(), and length().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/heap-refs.h
/mnt/V8SourceCode/src/compiler/heap-refs.cc