v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope Class Reference
#include <maglev-assembler-arm-inl.h>
Classes
struct SavedData
Public Member Functions
TemporaryRegisterScope (MaglevAssembler *masm)
TemporaryRegisterScope (MaglevAssembler *masm, const SavedData &saved_data)
Register AcquireScratch ()
DoubleRegister AcquireScratchDouble ()
void IncludeScratch (Register reg)
SavedData CopyForDefer ()
void ResetToDefaultImpl ()
TemporaryRegisterScope (MaglevAssembler *masm)
TemporaryRegisterScope (MaglevAssembler *masm, const SavedData &saved_data)
Register AcquireScratch ()
DoubleRegister AcquireScratchDouble ()
void IncludeScratch (Register reg)
SavedData CopyForDefer ()
void ResetToDefaultImpl ()
TemporaryRegisterScope (MaglevAssembler *masm)
TemporaryRegisterScope (MaglevAssembler *masm, const SavedData &saved_data)
Register AcquireScratch ()
DoubleRegister AcquireScratchDouble ()
void IncludeScratch (Register reg)
SavedData CopyForDefer ()
void ResetToDefaultImpl ()
TemporaryRegisterScope (MaglevAssembler *masm)
TemporaryRegisterScope (MaglevAssembler *masm, const SavedData &saved_data)
Register AcquireScratch ()
DoubleRegister AcquireScratchDouble ()
void IncludeScratch (Register reg)
SavedData CopyForDefer ()
void ResetToDefaultImpl ()
TemporaryRegisterScope (MaglevAssembler *masm)
TemporaryRegisterScope (MaglevAssembler *masm, const SavedData &saved_data)
Register AcquireScratch ()
DoubleRegister AcquireScratchDouble ()
void IncludeScratch (Register reg)
SavedData CopyForDefer ()
void ResetToDefaultImpl ()
Private Types
using Base = TemporaryRegisterScopeBase< TemporaryRegisterScope >
using Base = TemporaryRegisterScopeBase< TemporaryRegisterScope >
using Base = TemporaryRegisterScopeBase< TemporaryRegisterScope >
using Base = TemporaryRegisterScopeBase< TemporaryRegisterScope >
using Base = TemporaryRegisterScopeBase< TemporaryRegisterScope >
Private Attributes
UseScratchRegisterScope scratch_scope_
bool has_scratch_register_
bool has_double_scratch_register_
Additional Inherited Members
Detailed Description
Definition at line 42 of file maglev-assembler-arm-inl.h.
Member Typedef Documentation
Base [1/5]
using v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::Base = TemporaryRegisterScopeBase<TemporaryRegisterScope> [private]
Definition at line 44 of file maglev-assembler-arm-inl.h.
Base [2/5]
using v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::Base = TemporaryRegisterScopeBase<TemporaryRegisterScope> [private]
Definition at line 45 of file maglev-assembler-arm64-inl.h.
Base [3/5]
using v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::Base = TemporaryRegisterScopeBase<TemporaryRegisterScope> [private]
Definition at line 67 of file maglev-assembler-riscv-inl.h.
Base [4/5]
using v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::Base = TemporaryRegisterScopeBase<TemporaryRegisterScope> [private]
Definition at line 45 of file maglev-assembler-s390-inl.h.
Base [5/5]
using v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::Base = TemporaryRegisterScopeBase<TemporaryRegisterScope> [private]
Definition at line 62 of file maglev-assembler-x64-inl.h.
Constructor & Destructor Documentation
TemporaryRegisterScope() [1/10]
v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope (MaglevAssembler * masm) [inline], [explicit]
Definition at line 52 of file maglev-assembler-arm-inl.h.
      : Base(masm), scratch_scope_(masm) {
    if (prev_scope_ == nullptr) {
      // Add extra scratch register if no previous scope.
      scratch_scope_.Include(kMaglevExtraScratchRegister);
    }
  }
References v8::internal::UseScratchRegisterScope::Include(), v8::internal::kMaglevExtraScratchRegister, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::prev_scope_, and scratch_scope_.
TemporaryRegisterScope() [2/10]
v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope (MaglevAssembler * masm, const SavedData & saved_data) [inline], [explicit]
Definition at line 59 of file maglev-assembler-arm-inl.h.
      : Base(masm, saved_data), scratch_scope_(masm) {
    scratch_scope_.SetAvailable(saved_data.available_scratch_);
    scratch_scope_.SetAvailableVfp(saved_data.available_fp_scratch_);
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::SavedData::available_fp_scratch_, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::SavedData::available_scratch_, scratch_scope_, v8::internal::UseScratchRegisterScope::SetAvailable(), and v8::internal::UseScratchRegisterScope::SetAvailableVfp().
TemporaryRegisterScope() [3/10]
v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope (MaglevAssembler * masm) [inline], [explicit]
Definition at line 53 of file maglev-assembler-arm64-inl.h.
      : Base(masm), scratch_scope_(masm) {}
TemporaryRegisterScope() [4/10]
v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope (MaglevAssembler * masm, const SavedData & saved_data) [inline], [explicit]
Definition at line 55 of file maglev-assembler-arm64-inl.h.
      : Base(masm, saved_data), scratch_scope_(masm) {
    scratch_scope_.SetAvailable(saved_data.available_scratch_);
    scratch_scope_.SetAvailableFP(saved_data.available_fp_scratch_);
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::SavedData::available_fp_scratch_, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::SavedData::available_scratch_, scratch_scope_, v8::internal::UseScratchRegisterScope::SetAvailable(), and v8::internal::UseScratchRegisterScope::SetAvailableFP().
TemporaryRegisterScope() [5/10]
v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope (MaglevAssembler * masm) [inline], [explicit]
Definition at line 75 of file maglev-assembler-riscv-inl.h.
      : Base(masm), scratch_scope_(masm) {
    if (prev_scope_ == nullptr) {
      // Add extra scratch register if no previous scope.
      scratch_scope_.Include(kMaglevExtraScratchRegister);
    }
  }
References v8::internal::UseScratchRegisterScope::Include(), v8::internal::kMaglevExtraScratchRegister, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::prev_scope_, and scratch_scope_.
TemporaryRegisterScope() [6/10]
v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope (MaglevAssembler * masm, const SavedData & saved_data) [inline], [explicit]
Definition at line 82 of file maglev-assembler-riscv-inl.h.
      : Base(masm, saved_data), scratch_scope_(masm) {
    scratch_scope_.SetAvailable(saved_data.available_scratch_);
    scratch_scope_.SetAvailableDouble(saved_data.available_fp_scratch_);
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::SavedData::available_fp_scratch_, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::SavedData::available_scratch_, scratch_scope_, v8::internal::UseScratchRegisterScope::SetAvailable(), and v8::internal::UseScratchRegisterScope::SetAvailableDouble().
TemporaryRegisterScope() [7/10]
v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope (MaglevAssembler * masm) [inline], [explicit]
Definition at line 53 of file maglev-assembler-s390-inl.h.
      : Base(masm), scratch_scope_(masm) {
    if (prev_scope_ == nullptr) {
      // Add extra scratch register if no previous scope.
      // scratch_scope_.Include(kMaglevExtraScratchRegister);
    }
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::prev_scope_.
TemporaryRegisterScope() [8/10]
v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope (MaglevAssembler * masm, const SavedData & saved_data) [inline], [explicit]
Definition at line 60 of file maglev-assembler-s390-inl.h.
      : Base(masm, saved_data), scratch_scope_(masm) {
    scratch_scope_.SetAvailable(saved_data.available_scratch_);
    scratch_scope_.SetAvailableDoubleRegList(saved_data.available_fp_scratch_);
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::SavedData::available_fp_scratch_, v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::SavedData::available_scratch_, scratch_scope_, v8::internal::UseScratchRegisterScope::SetAvailable(), and v8::internal::UseScratchRegisterScope::SetAvailableDoubleRegList().
TemporaryRegisterScope() [9/10]
v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope (MaglevAssembler * masm) [inline], [explicit]
Definition at line 70 of file maglev-assembler-x64-inl.h.
      : Base(masm),
        has_scratch_register_(prev_scope_ ? prev_scope_->has_scratch_register_
                                          : true),
        has_double_scratch_register_(
            prev_scope_ ? prev_scope_->has_double_scratch_register_ : true) {}
TemporaryRegisterScope() [10/10]
v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::TemporaryRegisterScope (MaglevAssembler * masm, const SavedData & saved_data) [inline], [explicit]
Definition at line 76 of file maglev-assembler-x64-inl.h.
      : Base(masm, saved_data),
        has_scratch_register_(saved_data.has_scratch_register_),
        has_double_scratch_register_(saved_data.has_double_scratch_register_) {}
Member Function Documentation
AcquireScratch() [1/5]
Register v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch () [inline]
Definition at line 66 of file maglev-assembler-arm-inl.h.
                            {
    Register reg = scratch_scope_.Acquire();
    CHECK(!available_.has(reg));
    return reg;
  }
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::available_, CHECK, v8::internal::RegListBase< RegisterT >::has(), and scratch_scope_.
Referenced by v8::internal::maglev::anonymous_namespace{maglev-assembler-arm.cc}::AllocateRaw(), v8::internal::maglev::anonymous_namespace{maglev-assembler-arm64.cc}::AllocateRaw(), v8::internal::maglev::AllocateRaw(), v8::internal::maglev::anonymous_namespace{maglev-assembler-s390.cc}::AllocateRaw(), v8::internal::maglev::MaglevAssembler::AssertContextCellState(), v8::internal::maglev::MaglevAssembler::AssertObjectType(), v8::internal::maglev::MaglevAssembler::AssertObjectTypeInRange(), v8::internal::maglev::MaglevAssembler::AssertStackSizeCorrect(), v8::internal::maglev::MaglevAssembler::BranchOnObjectType(), v8::internal::maglev::MaglevAssembler::BranchOnObjectTypeInRange(), v8::internal::maglev::MaglevAssembler::BuildTypedArrayDataPointer(), v8::internal::maglev::MaglevAssembler::CheckAndEmitDeferredWriteBarrier(), v8::internal::maglev::MaglevAssembler::CheckInt32IsSmi(), v8::internal::maglev::MaglevAssembler::CompareInstanceType(), v8::internal::maglev::MaglevAssembler::CompareInstanceTypeRange(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor(), v8::internal::maglev::MaglevAssembler::FunctionEntryStackCheck(), v8::internal::maglev::MapCompare::Generate(), v8::internal::maglev::CheckFloat64SameValue::GenerateCode(), v8::internal::maglev::anonymous_namespace{maglev-ir-s390.cc}::GenerateReduceInterruptBudget(), v8::internal::maglev::MaglevAssembler::IsRootConstant(), v8::internal::maglev::MaglevAssembler::JumpIfJSAnyIsNotPrimitive(), v8::internal::maglev::MaglevAssembler::JumpIfNotHoleNan(), v8::internal::maglev::MaglevAssembler::JumpIfNotObjectType(), v8::internal::maglev::MaglevAssembler::JumpIfNotSeqOneByteString(), v8::internal::maglev::MaglevAssembler::JumpIfNotString(), v8::internal::maglev::MaglevAssembler::JumpIfObjectType(), v8::internal::maglev::MaglevAssembler::JumpIfObjectTypeInRange(), v8::internal::maglev::MaglevAssembler::JumpIfObjectTypeNotInRange(), v8::internal::maglev::MaglevAssembler::JumpIfSeqOneByteStringMap(), v8::internal::maglev::MaglevAssembler::JumpIfString(), v8::internal::maglev::MaglevAssembler::LoadFixedDoubleArrayElement(), v8::internal::maglev::MaglevAssembler::LoadThinStringValue(), v8::internal::maglev::MaglevAssembler::LoadUnalignedFloat64(), v8::internal::maglev::MaglevAssembler::LoadUnalignedFloat64AndReverseByteOrder(), v8::internal::maglev::MaglevAssembler::MaterialiseValueNode(), v8::internal::maglev::MaglevAssembler::MoveRepr(), v8::internal::maglev::MaglevAssembler::OSRPrologue(), v8::internal::maglev::MaglevAssembler::Prologue(), v8::internal::maglev::detail::PushInput(), v8::internal::maglev::MaglevAssembler::ReverseByteOrderAndStoreUnalignedFloat64(), v8::internal::maglev::MaglevAssembler::SeqOneByteStringCharCodeAt(), v8::internal::maglev::MaglevAssembler::SetMapAsRoot(), v8::internal::maglev::MaglevAssembler::StoreFixedArrayElementNoWriteBarrier(), v8::internal::maglev::MaglevAssembler::StoreFixedDoubleArrayElement(), v8::internal::maglev::MaglevAssembler::StoreInt32Field(), v8::internal::maglev::MaglevAssembler::StoreTaggedSignedField(), v8::internal::maglev::MaglevAssembler::StoreUnalignedFloat64(), v8::internal::maglev::MaglevAssembler::StringCharCodeOrCodePointAt(), v8::internal::maglev::MaglevAssembler::TestInt32AndJumpIfAllClear(), v8::internal::maglev::MaglevAssembler::TestInt32AndJumpIfAnySet(), v8::internal::maglev::MaglevAssembler::TestTypeOf(), v8::internal::maglev::MaglevAssembler::TestUint8AndJumpIfAllClear(), v8::internal::maglev::MaglevAssembler::TestUint8AndJumpIfAnySet(), v8::internal::maglev::MaglevAssembler::ToBoolean(), v8::internal::maglev::MaglevAssembler::TryMigrateInstance(), and v8::internal::maglev::anonymous_namespace{maglev-ir-arm.cc}::Uint32Mod().
AcquireScratch() [2/5]
Register v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch () [inline]
Definition at line 62 of file maglev-assembler-arm64-inl.h.
                            {
    Register reg = scratch_scope_.AcquireX();
    CHECK(!available_.has(reg));
    return reg;
  }
References v8::internal::UseScratchRegisterScope::AcquireX(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::available_, CHECK, v8::internal::RegListBase< RegisterT >::has(), and scratch_scope_.
AcquireScratch() [3/5]
Register v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch () [inline]
Definition at line 89 of file maglev-assembler-riscv-inl.h.
                            {
    Register reg = scratch_scope_.Acquire();
    CHECK(!available_.has(reg));
    return reg;
  }
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::available_, CHECK, v8::internal::RegListBase< RegisterT >::has(), and scratch_scope_.
AcquireScratch() [4/5]
Register v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch () [inline]
Definition at line 67 of file maglev-assembler-s390-inl.h.
                            {
    Register reg = scratch_scope_.Acquire();
    CHECK(!available_.has(reg));
    return reg;
  }
References v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::available_, CHECK, v8::internal::RegListBase< RegisterT >::has(), and scratch_scope_.
AcquireScratch() [5/5]
Register v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratch () [inline]
Definition at line 82 of file maglev-assembler-x64-inl.h.
                            {
    CHECK(has_scratch_register_);
    has_scratch_register_ = false;
    return kScratchRegister;
  }
References CHECK, has_scratch_register_, and v8::internal::kScratchRegister.
AcquireScratchDouble() [1/5]
DoubleRegister v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratchDouble () [inline]
Definition at line 71 of file maglev-assembler-arm-inl.h.
                                        {
    DoubleRegister reg = scratch_scope_.AcquireD();
    CHECK(!available_double_.has(reg));
    return reg;
  }
References v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::available_double_, CHECK, v8::internal::RegListBase< RegisterT >::has(), and scratch_scope_.
Referenced by v8::internal::maglev::MaglevAssembler::CompareDoubleAndJumpIfZeroOrNaN(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::EmitBlockEndGapMoves(), v8::internal::maglev::CheckFloat64SameValue::GenerateCode(), and v8::internal::maglev::MaglevAssembler::ToUint8Clamped().
AcquireScratchDouble() [2/5]
DoubleRegister v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratchDouble () [inline]
Definition at line 67 of file maglev-assembler-arm64-inl.h.
                                        {
    DoubleRegister reg = scratch_scope_.AcquireD();
    CHECK(!available_double_.has(reg));
    return reg;
  }
References v8::internal::UseScratchRegisterScope::AcquireD(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::available_double_, CHECK, v8::internal::RegListBase< RegisterT >::has(), and scratch_scope_.
AcquireScratchDouble() [3/5]
DoubleRegister v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratchDouble () [inline]
Definition at line 94 of file maglev-assembler-riscv-inl.h.
                                        {
    DoubleRegister reg = scratch_scope_.AcquireDouble();
    CHECK(!available_double_.has(reg));
    return reg;
  }
References v8::internal::UseScratchRegisterScope::AcquireDouble(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::available_double_, CHECK, v8::internal::RegListBase< RegisterT >::has(), and scratch_scope_.
AcquireScratchDouble() [4/5]
DoubleRegister v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratchDouble () [inline]
Definition at line 72 of file maglev-assembler-s390-inl.h.
                                        {
    DoubleRegister reg = scratch_scope_.AcquireDouble();
    CHECK(!available_double_.has(reg));
    return reg;
  }
References v8::internal::UseScratchRegisterScope::AcquireDouble(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::available_double_, CHECK, v8::internal::RegListBase< RegisterT >::has(), and scratch_scope_.
AcquireScratchDouble() [5/5]
DoubleRegister v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::AcquireScratchDouble () [inline]
Definition at line 87 of file maglev-assembler-x64-inl.h.
                                        {
    CHECK(has_double_scratch_register_);
    has_double_scratch_register_ = false;
    return kScratchDoubleReg;
  }
References CHECK, has_double_scratch_register_, and v8::internal::kScratchDoubleReg.
CopyForDefer() [1/5]
SavedData v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::CopyForDefer () [inline]
Definition at line 78 of file maglev-assembler-arm-inl.h.
                           {
    return SavedData{
        CopyForDeferBase(),
        scratch_scope_.Available(),
        scratch_scope_.AvailableVfp(),
    };
  }
References v8::internal::UseScratchRegisterScope::Available(), v8::internal::UseScratchRegisterScope::AvailableVfp(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::CopyForDeferBase(), and scratch_scope_.
Referenced by v8::internal::maglev::MaglevAssembler::MakeDeferredCode().
CopyForDefer() [2/5]
SavedData v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::CopyForDefer () [inline]
Definition at line 74 of file maglev-assembler-arm64-inl.h.
                           {
    return SavedData{
        CopyForDeferBase(),
        *scratch_scope_.Available(),
        *scratch_scope_.AvailableFP(),
    };
  }
References v8::internal::UseScratchRegisterScope::Available(), v8::internal::UseScratchRegisterScope::AvailableFP(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::CopyForDeferBase(), and scratch_scope_.
CopyForDefer() [3/5]
SavedData v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::CopyForDefer () [inline]
Definition at line 101 of file maglev-assembler-riscv-inl.h.
                           {
    return SavedData{
        CopyForDeferBase(),
        scratch_scope_.Available(),
        scratch_scope_.AvailableDouble(),
    };
  }
References v8::internal::UseScratchRegisterScope::Available(), v8::internal::UseScratchRegisterScope::AvailableDouble(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::CopyForDeferBase(), and scratch_scope_.
CopyForDefer() [4/5]
SavedData v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::CopyForDefer () [inline]
Definition at line 79 of file maglev-assembler-s390-inl.h.
                           {
    return SavedData{
        CopyForDeferBase(),
        scratch_scope_.Available(),
        scratch_scope_.AvailableDoubleRegList(),
    };
  }
References v8::internal::UseScratchRegisterScope::Available(), v8::internal::UseScratchRegisterScope::AvailableDoubleRegList(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::CopyForDeferBase(), and scratch_scope_.
CopyForDefer() [5/5]
SavedData v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::CopyForDefer () [inline]
Definition at line 97 of file maglev-assembler-x64-inl.h.
                           {
    return SavedData{
        CopyForDeferBase(),
        has_scratch_register_,
        has_double_scratch_register_,
    };
  }
References v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::CopyForDeferBase(), has_double_scratch_register_, and has_scratch_register_.
IncludeScratch() [1/5]
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::IncludeScratch (Register reg) [inline]
Definition at line 76 of file maglev-assembler-arm-inl.h.
{ scratch_scope_.Include(reg); }
References v8::internal::UseScratchRegisterScope::Include(), and scratch_scope_.
Referenced by v8::internal::maglev::MaglevAssembler::ToBoolean().
IncludeScratch() [2/5]
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::IncludeScratch (Register reg) [inline]
Definition at line 72 of file maglev-assembler-arm64-inl.h.
{ scratch_scope_.Include(reg); }
References v8::internal::UseScratchRegisterScope::Include(), and scratch_scope_.
IncludeScratch() [3/5]
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::IncludeScratch (Register reg) [inline]
Definition at line 99 of file maglev-assembler-riscv-inl.h.
{ scratch_scope_.Include(reg); }
References v8::internal::UseScratchRegisterScope::Include(), and scratch_scope_.
IncludeScratch() [4/5]
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::IncludeScratch (Register reg) [inline]
Definition at line 77 of file maglev-assembler-s390-inl.h.
{ scratch_scope_.Include(reg); }
References v8::internal::UseScratchRegisterScope::Include(), and scratch_scope_.
IncludeScratch() [5/5]
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::IncludeScratch (Register reg) [inline]
Definition at line 92 of file maglev-assembler-x64-inl.h.
                                    {
    DCHECK_EQ(reg, kScratchRegister);
    has_scratch_register_ = true;
  }
References DCHECK_EQ, has_scratch_register_, and v8::internal::kScratchRegister.
ResetToDefaultImpl() [1/5]
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::ResetToDefaultImpl () [inline]
Definition at line 86 of file maglev-assembler-arm-inl.h.
                            {
    scratch_scope_.SetAvailable(Assembler::DefaultTmpList() |
                                kMaglevExtraScratchRegister);
    scratch_scope_.SetAvailableVfp(Assembler::DefaultFPTmpList());
  }
References v8::internal::Assembler::DefaultFPTmpList(), v8::internal::Assembler::DefaultTmpList(), v8::internal::kMaglevExtraScratchRegister, scratch_scope_, v8::internal::UseScratchRegisterScope::SetAvailable(), and v8::internal::UseScratchRegisterScope::SetAvailableVfp().
ResetToDefaultImpl() [2/5]
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::ResetToDefaultImpl () [inline]
Definition at line 82 of file maglev-assembler-arm64-inl.h.
                            {
    scratch_scope_.SetAvailable(masm_->DefaultTmpList());
    scratch_scope_.SetAvailableFP(masm_->DefaultFPTmpList());
  }
References v8::internal::MacroAssembler::DefaultFPTmpList(), v8::internal::MacroAssembler::DefaultTmpList(), v8::internal::maglev::MaglevAssembler::TemporaryRegisterScopeBase< TemporaryRegisterScope >::masm_, scratch_scope_, v8::internal::UseScratchRegisterScope::SetAvailable(), and v8::internal::UseScratchRegisterScope::SetAvailableFP().
ResetToDefaultImpl() [3/5]
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::ResetToDefaultImpl () [inline]
Definition at line 109 of file maglev-assembler-riscv-inl.h.
                            {
    scratch_scope_.SetAvailable(Assembler::DefaultTmpList() |
                                kMaglevExtraScratchRegister);
    scratch_scope_.SetAvailableDouble(Assembler::DefaultFPTmpList());
  }
References v8::internal::Assembler::DefaultFPTmpList(), v8::internal::Assembler::DefaultTmpList(), v8::internal::kMaglevExtraScratchRegister, scratch_scope_, v8::internal::UseScratchRegisterScope::SetAvailable(), and v8::internal::UseScratchRegisterScope::SetAvailableDouble().
ResetToDefaultImpl() [4/5]
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::ResetToDefaultImpl () [inline]
Definition at line 87 of file maglev-assembler-s390-inl.h.
                            {
    scratch_scope_.SetAvailable(Assembler::DefaultTmpList());
    scratch_scope_.SetAvailableDoubleRegList(Assembler::DefaultFPTmpList());
  }
References v8::internal::Assembler::DefaultFPTmpList(), v8::internal::Assembler::DefaultTmpList(), scratch_scope_, v8::internal::UseScratchRegisterScope::SetAvailable(), and v8::internal::UseScratchRegisterScope::SetAvailableDoubleRegList().
ResetToDefaultImpl() [5/5]
void v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::ResetToDefaultImpl () [inline]
Definition at line 105 of file maglev-assembler-x64-inl.h.
                            {
    has_scratch_register_ = true;
    has_double_scratch_register_ = true;
  }
References has_double_scratch_register_, and has_scratch_register_.
Member Data Documentation
has_double_scratch_register_
bool v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::has_double_scratch_register_ [private]
Definition at line 112 of file maglev-assembler-x64-inl.h.
Referenced by AcquireScratchDouble(), CopyForDefer(), and ResetToDefaultImpl().
has_scratch_register_
bool v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::has_scratch_register_ [private]
Definition at line 111 of file maglev-assembler-x64-inl.h.
Referenced by AcquireScratch(), CopyForDefer(), IncludeScratch(), and ResetToDefaultImpl().
scratch_scope_
UseScratchRegisterScope v8::internal::maglev::MaglevAssembler::TemporaryRegisterScope::scratch_scope_ [private]
Definition at line 93 of file maglev-assembler-arm-inl.h.
Referenced by AcquireScratch(), AcquireScratchDouble(), CopyForDefer(), IncludeScratch(), ResetToDefaultImpl(), and TemporaryRegisterScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/arm/maglev-assembler-arm-inl.h
/mnt/V8SourceCode/src/maglev/arm64/maglev-assembler-arm64-inl.h
/mnt/V8SourceCode/src/maglev/riscv/maglev-assembler-riscv-inl.h
/mnt/V8SourceCode/src/maglev/s390/maglev-assembler-s390-inl.h
/mnt/V8SourceCode/src/maglev/x64/maglev-assembler-x64-inl.h