v8::internal::MinorGCJob::Task Class Reference
Public Member Functions
Task (Isolate *isolate, MinorGCJob *job)
void RunInternal () override
Isolate * isolate () const
Private Attributes
Isolate *const isolate_
MinorGCJob *const job_
Additional Inherited Members
Detailed Description
Definition at line 118 of file minor-gc-job.cc.
Constructor & Destructor Documentation
Task()
v8::internal::MinorGCJob::Task::Task (Isolate * isolate, MinorGCJob * job) [inline]
Definition at line 120 of file minor-gc-job.cc.
      : CancelableTask(isolate), isolate_(isolate), job_(job) {}
Member Function Documentation
isolate()
Isolate* v8::internal::MinorGCJob::Task::isolate () const [inline]
Definition at line 126 of file minor-gc-job.cc.
{ return isolate_; }
References isolate_.
Referenced by RunInternal().
RunInternal()
void v8::internal::MinorGCJob::Task::RunInternal () [override], [virtual]
Implements v8::internal::CancelableTask.
Definition at line 163 of file minor-gc-job.cc.
                                 {
  VMState<GC> state(isolate());
  TRACE_EVENT_CALL_STATS_SCOPED(isolate(), "v8", "V8.MinorGCJob.Task");
  DCHECK_EQ(job_->current_task_id_, id());
  job_->current_task_id_ = CancelableTaskManager::kInvalidTaskId;
  // Set the current isolate such that trusted pointer tables etc are
  // available and the cage base is set correctly for multi-cage mode.
  SetCurrentIsolateScope isolate_scope(isolate());
  Heap* heap = isolate()->heap();
  if (heap->incremental_marking()->IsMajorMarking()) {
    // Don't trigger a minor GC while major incremental marking is active.
    return;
  }
  heap->CollectGarbageWithRetry(
      NEW_SPACE, GCFlags(), GarbageCollectionReason::kTask, kNoGCCallbackFlags);
}
References v8::internal::MinorGCJob::current_task_id_, DCHECK_EQ, v8::internal::Isolate::heap(), isolate(), job_, v8::internal::CancelableTaskManager::kInvalidTaskId, v8::kNoGCCallbackFlags, v8::internal::kTask, v8::internal::NEW_SPACE, and TRACE_EVENT_CALL_STATS_SCOPED.
Member Data Documentation
isolate_
Isolate* const v8::internal::MinorGCJob::Task::isolate_ [private]
Definition at line 129 of file minor-gc-job.cc.
Referenced by isolate().
job_
MinorGCJob* const v8::internal::MinorGCJob::Task::job_ [private]
Definition at line 130 of file minor-gc-job.cc.
Referenced by RunInternal().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/minor-gc-job.cc