v8::internal::compiler::JSCreateLowering Class Reference
#include <js-create-lowering.h>
Public Member Functions
JSCreateLowering (Editor *editor, JSGraph *jsgraph, JSHeapBroker *broker, Zone *zone)
~JSCreateLowering () final=default
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
Reduction ReduceJSCreate (Node *node)
Reduction ReduceJSCreateArguments (Node *node)
Reduction ReduceJSCreateArray (Node *node)
Reduction ReduceJSCreateArrayIterator (Node *node)
Reduction ReduceJSCreateAsyncFunctionObject (Node *node)
Reduction ReduceJSCreateCollectionIterator (Node *node)
Reduction ReduceJSCreateBoundFunction (Node *node)
Reduction ReduceJSCreateClosure (Node *node)
Reduction ReduceJSCreateIterResultObject (Node *node)
Reduction ReduceJSCreateStringIterator (Node *node)
Reduction ReduceJSCreateKeyValueArray (Node *node)
Reduction ReduceJSCreatePromise (Node *node)
Reduction ReduceJSCreateLiteralArrayOrObject (Node *node)
Reduction ReduceJSCreateEmptyLiteralObject (Node *node)
Reduction ReduceJSCreateEmptyLiteralArray (Node *node)
Reduction ReduceJSCreateLiteralRegExp (Node *node)
Reduction ReduceJSCreateFunctionContext (Node *node)
Reduction ReduceJSCreateWithContext (Node *node)
Reduction ReduceJSCreateCatchContext (Node *node)
Reduction ReduceJSCreateBlockContext (Node *node)
Reduction ReduceJSCreateGeneratorObject (Node *node)
Reduction ReduceJSGetTemplateObject (Node *node)
Reduction ReduceNewArray (Node *node, Node *length, MapRef initial_map, ElementsKind elements_kind, AllocationType allocation, const SlackTrackingPrediction &slack_tracking_prediction, const FeedbackSource &feedback)
Reduction ReduceNewArray (Node *node, Node *length, int capacity, MapRef initial_map, ElementsKind elements_kind, AllocationType allocation, const SlackTrackingPrediction &slack_tracking_prediction, const FeedbackSource &feedback)
Reduction ReduceNewArray (Node *node, std::vector< Node * > values, MapRef initial_map, ElementsKind elements_kind, AllocationType allocation, const SlackTrackingPrediction &slack_tracking_prediction, const FeedbackSource &feedback)
Reduction ReduceJSCreateObject (Node *node)
Reduction ReduceJSCreateStringWrapper (Node *node)
Node * TryAllocateArguments (Node *effect, Node *control, FrameState frame_state)
Node * TryAllocateRestArguments (Node *effect, Node *control, FrameState frame_state, int start_index)
Node * TryAllocateAliasedArguments (Node *effect, Node *control, FrameState frame_state, Node *context, SharedFunctionInfoRef shared, bool *has_aliased_arguments)
Node * TryAllocateAliasedArguments (Node *effect, Node *control, Node *context, Node *arguments_length, SharedFunctionInfoRef shared, bool *has_aliased_arguments)
std::optional< Node * > TryAllocateFastLiteral (Node *effect, Node *control, JSObjectRef boilerplate, AllocationType allocation, int max_depth, int *max_properties)
std::optional< Node * > TryAllocateFastLiteralElements (Node *effect, Node *control, JSObjectRef boilerplate, AllocationType allocation, int max_depth, int *max_properties)
Node * AllocateElements (Node *effect, Node *control, ElementsKind elements_kind, int capacity, AllocationType allocation)
Node * AllocateElements (Node *effect, Node *control, ElementsKind elements_kind, Node *capacity_and_length)
Node * AllocateElements (Node *effect, Node *control, ElementsKind elements_kind, std::vector< Node * > const &values, AllocationType allocation)
Node * AllocateLiteralRegExp (Node *effect, Node *control, RegExpBoilerplateDescriptionRef boilerplate)
Factory * factory () const
TFGraph * graph () const
JSGraph * jsgraph () const
NativeContextRef native_context () const
CommonOperatorBuilder * common () const
SimplifiedOperatorBuilder * simplified () const
CompilationDependencies * dependencies () const
JSHeapBroker * broker () const
Zone * zone () const
Private Attributes
JSGraph *const jsgraph_
JSHeapBroker *const broker_
Zone *const zone_
Detailed Description
Definition at line 36 of file js-create-lowering.h.
Constructor & Destructor Documentation
JSCreateLowering()
v8::internal::compiler::JSCreateLowering::JSCreateLowering (Editor * editor, JSGraph * jsgraph, JSHeapBroker * broker, Zone * zone) [inline]
Definition at line 39 of file js-create-lowering.h.
      : AdvancedReducer(editor),
        jsgraph_(jsgraph),
        broker_(broker),
        zone_(zone) {}
 JSCreateLowering()
v8::internal::compiler::JSCreateLowering::~JSCreateLowering () [final], [default]
Member Function Documentation
AllocateElements() [1/3]
Node * v8::internal::compiler::JSCreateLowering::AllocateElements (Node * effect, Node * control, ElementsKind elements_kind, int capacity, AllocationType allocation) [private]
Definition at line 1691 of file js-create-lowering.cc.
                                                                    {
  DCHECK_LE(1, capacity);
  DCHECK_LE(capacity, JSArray::kInitialMaxFastElementArray);
  Handle<Map> elements_map = IsDoubleElementsKind(elements_kind)
                                 ? factory()->fixed_double_array_map()
                                 : factory()->fixed_array_map();
  ElementAccess access = IsDoubleElementsKind(elements_kind)
                             ? AccessBuilder::ForFixedDoubleArrayElement()
                             : AccessBuilder::ForFixedArrayElement();
  Node* value = jsgraph()->TheHoleConstant();
  // Actually allocate the backing store.
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.AllocateArray(capacity, MakeRef(broker(), elements_map), allocation);
  for (int i = 0; i < capacity; ++i) {
    Node* index = jsgraph()->ConstantNoHole(i);
    a.Store(access, index, value);
  }
  return a.Finish();
}
References v8::internal::compiler::AllocationBuilder::AllocateArray(), broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_LE, factory(), v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForFixedDoubleArrayElement(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::IsDoubleElementsKind(), jsgraph(), v8::internal::JSArray::kInitialMaxFastElementArray, v8::internal::compiler::MakeRef(), v8::internal::compiler::AllocationBuilder::Store(), and v8::internal::value.
Referenced by ReduceNewArray().
AllocateElements() [2/3]
Node* v8::internal::compiler::JSCreateLowering::AllocateElements (Node * effect, Node * control, ElementsKind elements_kind, Node * capacity_and_length) [private]
AllocateElements() [3/3]
Node * v8::internal::compiler::JSCreateLowering::AllocateElements (Node * effect, Node * control, ElementsKind elements_kind, std::vector< Node * > const & values, AllocationType allocation) [private]
Definition at line 1716 of file js-create-lowering.cc.
                                                                    {
  int const capacity = static_cast<int>(values.size());
  DCHECK_LE(1, capacity);
  DCHECK_LE(capacity, JSArray::kInitialMaxFastElementArray);
  Handle<Map> elements_map = IsDoubleElementsKind(elements_kind)
                                 ? factory()->fixed_double_array_map()
                                 : factory()->fixed_array_map();
  ElementAccess access = IsDoubleElementsKind(elements_kind)
                             ? AccessBuilder::ForFixedDoubleArrayElement()
                             : AccessBuilder::ForFixedArrayElement();
  // Actually allocate the backing store.
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.AllocateArray(capacity, MakeRef(broker(), elements_map), allocation);
  for (int i = 0; i < capacity; ++i) {
    Node* index = jsgraph()->ConstantNoHole(i);
    a.Store(access, index, values[i]);
  }
  return a.Finish();
}
References v8::internal::compiler::AllocationBuilder::AllocateArray(), broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_LE, factory(), v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForFixedDoubleArrayElement(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::IsDoubleElementsKind(), jsgraph(), v8::internal::JSArray::kInitialMaxFastElementArray, v8::internal::compiler::MakeRef(), and v8::internal::compiler::AllocationBuilder::Store().
AllocateLiteralRegExp()
Node * v8::internal::compiler::JSCreateLowering::AllocateLiteralRegExp (Node * effect, Node * control, RegExpBoilerplateDescriptionRef boilerplate) [private]
Definition at line 1990 of file js-create-lowering.cc.
                                                                              {
  MapRef initial_map =
      native_context().regexp_function(broker()).initial_map(broker());
  // Sanity check that JSRegExp object layout hasn't changed.
  static_assert(JSRegExp::kDataOffset == JSObject::kHeaderSize);
  static_assert(JSRegExp::kSourceOffset == JSRegExp::kDataOffset + kTaggedSize);
  static_assert(JSRegExp::kFlagsOffset ==
                JSRegExp::kSourceOffset + kTaggedSize);
  static_assert(JSRegExp::kHeaderSize == JSRegExp::kFlagsOffset + kTaggedSize);
  static_assert(JSRegExp::kLastIndexOffset == JSRegExp::kHeaderSize);
  DCHECK_EQ(JSRegExp::Size(), JSRegExp::kLastIndexOffset + kTaggedSize);
  AllocationBuilder builder(jsgraph(), broker(), effect, control);
  builder.Allocate(JSRegExp::Size(), AllocationType::kYoung,
                   Type::For(initial_map, broker()));
  builder.Store(AccessBuilder::ForMap(), initial_map);
  builder.Store(AccessBuilder::ForJSObjectPropertiesOrHash(),
                jsgraph()->EmptyFixedArrayConstant());
  builder.Store(AccessBuilder::ForJSObjectElements(),
                jsgraph()->EmptyFixedArrayConstant());
  builder.Store(AccessBuilder::ForJSRegExpData(), boilerplate.data(broker()));
  builder.Store(AccessBuilder::ForJSRegExpSource(),
                boilerplate.source(broker()));
  builder.Store(AccessBuilder::ForJSRegExpFlags(),
                jsgraph()->SmiConstant(boilerplate.flags()));
  builder.Store(AccessBuilder::ForJSRegExpLastIndex(),
                jsgraph()->SmiConstant(JSRegExp::kInitialLastIndexValue));
  return builder.Finish();
}
References v8::internal::compiler::AllocationBuilder::Allocate(), broker(), v8::internal::compiler::RegExpBoilerplateDescriptionRef::data(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::RegExpBoilerplateDescriptionRef::flags(), v8::internal::compiler::Type::For(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHash(), v8::internal::compiler::AccessBuilder::ForJSRegExpData(), v8::internal::compiler::AccessBuilder::ForJSRegExpFlags(), v8::internal::compiler::AccessBuilder::ForJSRegExpLastIndex(), v8::internal::compiler::AccessBuilder::ForJSRegExpSource(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::initial_map, jsgraph(), v8::internal::JSRegExp::kInitialLastIndexValue, v8::internal::JSRegExp::kLastIndexOffset, v8::internal::kTaggedSize, v8::internal::kYoung, native_context(), v8::internal::JSRegExp::Size(), v8::internal::compiler::RegExpBoilerplateDescriptionRef::source(), and v8::internal::compiler::AllocationBuilder::Store().
Referenced by ReduceJSCreateLiteralRegExp().
broker()
JSHeapBroker* v8::internal::compiler::JSCreateLowering::broker () const [inline], [private]
Definition at line 134 of file js-create-lowering.h.
{ return broker_; }
Referenced by AllocateElements(), AllocateLiteralRegExp(), dependencies(), native_context(), ReduceJSCreate(), ReduceJSCreateArguments(), ReduceJSCreateArray(), ReduceJSCreateArrayIterator(), ReduceJSCreateAsyncFunctionObject(), ReduceJSCreateBlockContext(), ReduceJSCreateBoundFunction(), ReduceJSCreateCatchContext(), ReduceJSCreateClosure(), ReduceJSCreateCollectionIterator(), ReduceJSCreateEmptyLiteralArray(), ReduceJSCreateEmptyLiteralObject(), ReduceJSCreateFunctionContext(), ReduceJSCreateGeneratorObject(), ReduceJSCreateIterResultObject(), ReduceJSCreateKeyValueArray(), ReduceJSCreateLiteralArrayOrObject(), ReduceJSCreateLiteralRegExp(), ReduceJSCreateObject(), ReduceJSCreatePromise(), ReduceJSCreateStringIterator(), ReduceJSCreateStringWrapper(), ReduceJSCreateWithContext(), ReduceJSGetTemplateObject(), ReduceNewArray(), TryAllocateAliasedArguments(), TryAllocateArguments(), TryAllocateFastLiteral(), TryAllocateFastLiteralElements(), and TryAllocateRestArguments().
common()
CommonOperatorBuilder * v8::internal::compiler::JSCreateLowering::common () const [private]
Definition at line 2030 of file js-create-lowering.cc.
                                                      {
  return jsgraph()->common();
}
References v8::internal::compiler::MachineGraph::common(), and jsgraph().
Referenced by TryAllocateAliasedArguments().
dependencies()
CompilationDependencies * v8::internal::compiler::JSCreateLowering::dependencies () const [private]
Definition at line 2034 of file js-create-lowering.cc.
                                                              {
  return broker()->dependencies();
}
References broker(), and v8::internal::compiler::JSHeapBroker::dependencies().
Referenced by ReduceJSCreate(), ReduceJSCreateArray(), ReduceJSCreateEmptyLiteralArray(), ReduceJSCreateGeneratorObject(), ReduceJSCreateLiteralArrayOrObject(), TryAllocateFastLiteral(), and TryAllocateFastLiteralElements().
factory()
Factory * v8::internal::compiler::JSCreateLowering::factory () const [private]
Definition at line 2024 of file js-create-lowering.cc.
                                         {
  return jsgraph()->isolate()->factory();
}
References v8::internal::Isolate::factory(), v8::internal::compiler::JSGraph::isolate(), and jsgraph().
Referenced by AllocateElements(), and TryAllocateFastLiteral().
graph()
TFGraph * v8::internal::compiler::JSCreateLowering::graph () const [private]
Definition at line 2028 of file js-create-lowering.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by ReduceJSCreateArguments(), ReduceJSCreateClosure(), ReduceJSCreateCollectionIterator(), ReduceJSCreateIterResultObject(), ReduceJSCreateKeyValueArray(), ReduceJSCreatePromise(), ReduceJSCreateStringIterator(), ReduceJSCreateStringWrapper(), ReduceNewArray(), and TryAllocateAliasedArguments().
jsgraph()
JSGraph* v8::internal::compiler::JSCreateLowering::jsgraph () const [inline], [private]
Definition at line 129 of file js-create-lowering.h.
{ return jsgraph_; }
Referenced by AllocateElements(), AllocateLiteralRegExp(), common(), factory(), graph(), ReduceJSCreate(), ReduceJSCreateArguments(), ReduceJSCreateArray(), ReduceJSCreateArrayIterator(), ReduceJSCreateAsyncFunctionObject(), ReduceJSCreateBlockContext(), ReduceJSCreateBoundFunction(), ReduceJSCreateCatchContext(), ReduceJSCreateClosure(), ReduceJSCreateCollectionIterator(), ReduceJSCreateEmptyLiteralArray(), ReduceJSCreateEmptyLiteralObject(), ReduceJSCreateFunctionContext(), ReduceJSCreateGeneratorObject(), ReduceJSCreateIterResultObject(), ReduceJSCreateKeyValueArray(), ReduceJSCreateObject(), ReduceJSCreatePromise(), ReduceJSCreateStringIterator(), ReduceJSCreateStringWrapper(), ReduceJSCreateWithContext(), ReduceJSGetTemplateObject(), ReduceNewArray(), simplified(), TryAllocateAliasedArguments(), TryAllocateArguments(), TryAllocateFastLiteral(), TryAllocateFastLiteralElements(), and TryAllocateRestArguments().
native_context()
NativeContextRef v8::internal::compiler::JSCreateLowering::native_context () const [private]
Definition at line 2042 of file js-create-lowering.cc.
                                                        {
  return broker()->target_native_context();
}
References broker(), and v8::internal::compiler::JSHeapBroker::target_native_context().
Referenced by AllocateLiteralRegExp(), ReduceJSCreateArguments(), ReduceJSCreateArrayIterator(), ReduceJSCreateAsyncFunctionObject(), ReduceJSCreateBlockContext(), ReduceJSCreateCatchContext(), ReduceJSCreateClosure(), ReduceJSCreateCollectionIterator(), ReduceJSCreateEmptyLiteralArray(), ReduceJSCreateEmptyLiteralObject(), ReduceJSCreateFunctionContext(), ReduceJSCreateIterResultObject(), ReduceJSCreateKeyValueArray(), ReduceJSCreatePromise(), ReduceJSCreateStringIterator(), ReduceJSCreateStringWrapper(), and ReduceJSCreateWithContext().
Reduce()
Reduction v8::internal::compiler::JSCreateLowering::Reduce (Node * node) [final]
Definition at line 57 of file js-create-lowering.cc.
                                             {
  switch (node->opcode()) {
    case IrOpcode::kJSCreate:
      return ReduceJSCreate(node);
    case IrOpcode::kJSCreateArguments:
      return ReduceJSCreateArguments(node);
    case IrOpcode::kJSCreateArray:
      return ReduceJSCreateArray(node);
    case IrOpcode::kJSCreateArrayIterator:
      return ReduceJSCreateArrayIterator(node);
    case IrOpcode::kJSCreateAsyncFunctionObject:
      return ReduceJSCreateAsyncFunctionObject(node);
    case IrOpcode::kJSCreateBoundFunction:
      return ReduceJSCreateBoundFunction(node);
    case IrOpcode::kJSCreateClosure:
      return ReduceJSCreateClosure(node);
    case IrOpcode::kJSCreateCollectionIterator:
      return ReduceJSCreateCollectionIterator(node);
    case IrOpcode::kJSCreateIterResultObject:
      return ReduceJSCreateIterResultObject(node);
    case IrOpcode::kJSCreateStringIterator:
      return ReduceJSCreateStringIterator(node);
    case IrOpcode::kJSCreateKeyValueArray:
      return ReduceJSCreateKeyValueArray(node);
    case IrOpcode::kJSCreatePromise:
      return ReduceJSCreatePromise(node);
    case IrOpcode::kJSCreateLiteralArray:
    case IrOpcode::kJSCreateLiteralObject:
      return ReduceJSCreateLiteralArrayOrObject(node);
    case IrOpcode::kJSCreateLiteralRegExp:
      return ReduceJSCreateLiteralRegExp(node);
    case IrOpcode::kJSGetTemplateObject:
      return ReduceJSGetTemplateObject(node);
    case IrOpcode::kJSCreateEmptyLiteralArray:
      return ReduceJSCreateEmptyLiteralArray(node);
    case IrOpcode::kJSCreateEmptyLiteralObject:
      return ReduceJSCreateEmptyLiteralObject(node);
    case IrOpcode::kJSCreateFunctionContext:
      return ReduceJSCreateFunctionContext(node);
    case IrOpcode::kJSCreateWithContext:
      return ReduceJSCreateWithContext(node);
    case IrOpcode::kJSCreateCatchContext:
      return ReduceJSCreateCatchContext(node);
    case IrOpcode::kJSCreateBlockContext:
      return ReduceJSCreateBlockContext(node);
    case IrOpcode::kJSCreateGeneratorObject:
      return ReduceJSCreateGeneratorObject(node);
    case IrOpcode::kJSCreateObject:
      return ReduceJSCreateObject(node);
    case IrOpcode::kJSCreateStringWrapper:
      return ReduceJSCreateStringWrapper(node);
    default:
      break;
  }
  return NoChange();
}
References v8::internal::compiler::Node::opcode(), ReduceJSCreate(), ReduceJSCreateArguments(), ReduceJSCreateArray(), ReduceJSCreateArrayIterator(), ReduceJSCreateAsyncFunctionObject(), ReduceJSCreateBlockContext(), ReduceJSCreateBoundFunction(), ReduceJSCreateCatchContext(), ReduceJSCreateClosure(), ReduceJSCreateCollectionIterator(), ReduceJSCreateEmptyLiteralArray(), ReduceJSCreateEmptyLiteralObject(), ReduceJSCreateFunctionContext(), ReduceJSCreateGeneratorObject(), ReduceJSCreateIterResultObject(), ReduceJSCreateKeyValueArray(), ReduceJSCreateLiteralArrayOrObject(), ReduceJSCreateLiteralRegExp(), ReduceJSCreateObject(), ReduceJSCreatePromise(), ReduceJSCreateStringIterator(), ReduceJSCreateStringWrapper(), ReduceJSCreateWithContext(), and ReduceJSGetTemplateObject().
ReduceJSCreate()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreate (Node * node) [private]
Definition at line 114 of file js-create-lowering.cc.
                                                     {
  DCHECK_EQ(IrOpcode::kJSCreate, node->opcode());
  Node* const new_target = NodeProperties::GetValueInput(node, 1);
  Node* const effect = NodeProperties::GetEffectInput(node);
  Node* const control = NodeProperties::GetControlInput(node);
  OptionalMapRef initial_map = NodeProperties::GetJSCreateMap(broker(), node);
  if (!initial_map.has_value()) return NoChange();
  JSFunctionRef original_constructor =
      HeapObjectMatcher(new_target).Ref(broker()).AsJSFunction();
  SlackTrackingPrediction slack_tracking_prediction =
      dependencies()->DependOnInitialMapInstanceSizePrediction(
          original_constructor);
  // Emit code to allocate the JSObject instance for the
  // {original_constructor}.
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.Allocate(slack_tracking_prediction.instance_size());
  a.Store(AccessBuilder::ForMap(), *initial_map);
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(),
          jsgraph()->EmptyFixedArrayConstant());
  for (int i = 0; i < slack_tracking_prediction.inobject_property_count();
       ++i) {
    a.Store(AccessBuilder::ForJSObjectInObjectProperty(*initial_map, i),
            jsgraph()->UndefinedConstant());
  }
  RelaxControls(node);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), broker(), DCHECK_EQ, dependencies(), v8::internal::compiler::CompilationDependencies::DependOnInitialMapInstanceSizePrediction(), v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectInObjectProperty(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetJSCreateMap(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::initial_map, v8::internal::compiler::SlackTrackingPrediction::inobject_property_count(), v8::internal::compiler::SlackTrackingPrediction::instance_size(), jsgraph(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::AllocationBuilder::Store(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by Reduce().
ReduceJSCreateArguments()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateArguments (Node * node) [private]
Definition at line 149 of file js-create-lowering.cc.
                                                              {
  DCHECK_EQ(IrOpcode::kJSCreateArguments, node->opcode());
  CreateArgumentsType type = CreateArgumentsTypeOf(node->op());
  FrameState frame_state{NodeProperties::GetFrameStateInput(node)};
  Node* const control = graph()->start();
  FrameStateInfo state_info = frame_state.frame_state_info();
  SharedFunctionInfoRef shared =
      MakeRef(broker(), state_info.shared_info().ToHandleChecked());
  // Use the ArgumentsAccessStub for materializing both mapped and unmapped
  // arguments object, but only for non-inlined (i.e. outermost) frames.
  if (frame_state.outer_frame_state()->opcode() != IrOpcode::kFrameState) {
    switch (type) {
      case CreateArgumentsType::kMappedArguments: {
        // TODO(turbofan): Duplicate parameters are not handled yet.
        if (shared.has_duplicate_parameters()) return NoChange();
        Node* const callee = NodeProperties::GetValueInput(node, 0);
        Node* const context = NodeProperties::GetContextInput(node);
        Node* effect = NodeProperties::GetEffectInput(node);
        Node* const arguments_length =
            graph()->NewNode(simplified()->ArgumentsLength());
        // Allocate the elements backing store.
        bool has_aliased_arguments = false;
        Node* const elements = effect = TryAllocateAliasedArguments(
            effect, control, context, arguments_length, shared,
            &has_aliased_arguments);
        if (elements == nullptr) return NoChange();
        // Load the arguments object map.
        Node* const arguments_map = jsgraph()->ConstantNoHole(
            has_aliased_arguments
                ? native_context().fast_aliased_arguments_map(broker())
                : native_context().sloppy_arguments_map(broker()),
            broker());
        // Actually allocate and initialize the arguments object.
        AllocationBuilder a(jsgraph(), broker(), effect, control);
        static_assert(JSSloppyArgumentsObject::kSize == 5 * kTaggedSize);
        a.Allocate(JSSloppyArgumentsObject::kSize);
        a.Store(AccessBuilder::ForMap(), arguments_map);
        a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
                jsgraph()->EmptyFixedArrayConstant());
        a.Store(AccessBuilder::ForJSObjectElements(), elements);
        a.Store(AccessBuilder::ForArgumentsLength(), arguments_length);
        a.Store(AccessBuilder::ForArgumentsCallee(), callee);
        RelaxControls(node);
        a.FinishAndChange(node);
        return Changed(node);
      }
      case CreateArgumentsType::kUnmappedArguments: {
        Node* effect = NodeProperties::GetEffectInput(node);
        Node* const arguments_length =
            graph()->NewNode(simplified()->ArgumentsLength());
        // Allocate the elements backing store.
        int parameter_count_without_receiver =
            shared
                .internal_formal_parameter_count_without_receiver_deprecated();
        Node* const elements = effect =
            graph()->NewNode(simplified()->NewArgumentsElements(
                                 CreateArgumentsType::kUnmappedArguments,
                                 parameter_count_without_receiver),
                             arguments_length, effect);
        // Load the arguments object map.
        Node* const arguments_map = jsgraph()->ConstantNoHole(
            native_context().strict_arguments_map(broker()), broker());
        // Actually allocate and initialize the arguments object.
        AllocationBuilder a(jsgraph(), broker(), effect, control);
        static_assert(JSStrictArgumentsObject::kSize == 4 * kTaggedSize);
        a.Allocate(JSStrictArgumentsObject::kSize);
        a.Store(AccessBuilder::ForMap(), arguments_map);
        a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
                jsgraph()->EmptyFixedArrayConstant());
        a.Store(AccessBuilder::ForJSObjectElements(), elements);
        a.Store(AccessBuilder::ForArgumentsLength(), arguments_length);
        RelaxControls(node);
        a.FinishAndChange(node);
        return Changed(node);
      }
      case CreateArgumentsType::kRestParameter: {
        Node* effect = NodeProperties::GetEffectInput(node);
        Node* const arguments_length =
            graph()->NewNode(simplified()->ArgumentsLength());
        Node* const rest_length = graph()->NewNode(simplified()->RestLength(
            state_info.parameter_count_without_receiver()));
        // Allocate the elements backing store.
        int parameter_count_without_receiver =
            shared
                .internal_formal_parameter_count_without_receiver_deprecated();
        Node* const elements = effect =
            graph()->NewNode(simplified()->NewArgumentsElements(
                                 CreateArgumentsType::kRestParameter,
                                 parameter_count_without_receiver),
                             arguments_length, effect);
        // Load the JSArray object map.
        Node* const jsarray_map = jsgraph()->ConstantNoHole(
            native_context().js_array_packed_elements_map(broker()), broker());
        // Actually allocate and initialize the jsarray.
        AllocationBuilder a(jsgraph(), broker(), effect, control);
        static_assert(JSArray::kHeaderSize == 4 * kTaggedSize);
        a.Allocate(JSArray::kHeaderSize);
        a.Store(AccessBuilder::ForMap(), jsarray_map);
        a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
                jsgraph()->EmptyFixedArrayConstant());
        a.Store(AccessBuilder::ForJSObjectElements(), elements);
        a.Store(AccessBuilder::ForJSArrayLength(PACKED_ELEMENTS), rest_length);
        RelaxControls(node);
        a.FinishAndChange(node);
        return Changed(node);
      }
    }
    UNREACHABLE();
  }
  // Use inline allocation for all mapped arguments objects within inlined
  // (i.e. non-outermost) frames, independent of the object size.
  DCHECK_EQ(frame_state.outer_frame_state()->opcode(), IrOpcode::kFrameState);
  switch (type) {
    case CreateArgumentsType::kMappedArguments: {
      Node* const callee = NodeProperties::GetValueInput(node, 0);
      Node* const context = NodeProperties::GetContextInput(node);
      Node* effect = NodeProperties::GetEffectInput(node);
      // TODO(turbofan): Duplicate parameters are not handled yet.
      if (shared.has_duplicate_parameters()) return NoChange();
      // Choose the correct frame state and frame state info depending on
      // whether there conceptually is an inlined arguments frame in the call
      // chain.
      FrameState args_state = GetArgumentsFrameState(frame_state);
      if (args_state.parameters()->opcode() == IrOpcode::kDeadValue) {
        // This protects against an incompletely propagated DeadValue node.
        // If the FrameState has a DeadValue input, then this node will be
        // pruned anyway.
        return NoChange();
      }
      FrameStateInfo args_state_info = args_state.frame_state_info();
      int length = args_state_info.parameter_count_without_receiver();
      // Prepare element backing store to be used by arguments object.
      bool has_aliased_arguments = false;
      Node* const elements = TryAllocateAliasedArguments(
          effect, control, args_state, context, shared, &has_aliased_arguments);
      if (elements == nullptr) return NoChange();
      effect = elements->op()->EffectOutputCount() > 0 ? elements : effect;
      // Load the arguments object map.
      Node* const arguments_map = jsgraph()->ConstantNoHole(
          has_aliased_arguments
              ? native_context().fast_aliased_arguments_map(broker())
              : native_context().sloppy_arguments_map(broker()),
          broker());
      // Actually allocate and initialize the arguments object.
      AllocationBuilder a(jsgraph(), broker(), effect, control);
      static_assert(JSSloppyArgumentsObject::kSize == 5 * kTaggedSize);
      a.Allocate(JSSloppyArgumentsObject::kSize);
      a.Store(AccessBuilder::ForMap(), arguments_map);
      a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
              jsgraph()->EmptyFixedArrayConstant());
      a.Store(AccessBuilder::ForJSObjectElements(), elements);
      a.Store(AccessBuilder::ForArgumentsLength(),
              jsgraph()->ConstantNoHole(length));
      a.Store(AccessBuilder::ForArgumentsCallee(), callee);
      RelaxControls(node);
      a.FinishAndChange(node);
      return Changed(node);
    }
    case CreateArgumentsType::kUnmappedArguments: {
      // Use inline allocation for all unmapped arguments objects within inlined
      // (i.e. non-outermost) frames, independent of the object size.
      Node* effect = NodeProperties::GetEffectInput(node);
      // Choose the correct frame state and frame state info depending on
      // whether there conceptually is an inlined arguments frame in the call
      // chain.
      FrameState args_state = GetArgumentsFrameState(frame_state);
      if (args_state.parameters()->opcode() == IrOpcode::kDeadValue) {
        // This protects against an incompletely propagated DeadValue node.
        // If the FrameState has a DeadValue input, then this node will be
        // pruned anyway.
        return NoChange();
      }
      FrameStateInfo args_state_info = args_state.frame_state_info();
      int length = args_state_info.parameter_count_without_receiver();
      // Prepare element backing store to be used by arguments object.
      Node* const elements = TryAllocateArguments(effect, control, args_state);
      if (elements == nullptr) return NoChange();
      effect = elements->op()->EffectOutputCount() > 0 ? elements : effect;
      // Load the arguments object map.
      Node* const arguments_map = jsgraph()->ConstantNoHole(
          native_context().strict_arguments_map(broker()), broker());
      // Actually allocate and initialize the arguments object.
      AllocationBuilder a(jsgraph(), broker(), effect, control);
      static_assert(JSStrictArgumentsObject::kSize == 4 * kTaggedSize);
      a.Allocate(JSStrictArgumentsObject::kSize);
      a.Store(AccessBuilder::ForMap(), arguments_map);
      a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
              jsgraph()->EmptyFixedArrayConstant());
      a.Store(AccessBuilder::ForJSObjectElements(), elements);
      a.Store(AccessBuilder::ForArgumentsLength(),
              jsgraph()->ConstantNoHole(length));
      RelaxControls(node);
      a.FinishAndChange(node);
      return Changed(node);
    }
    case CreateArgumentsType::kRestParameter: {
      int start_index =
          shared.internal_formal_parameter_count_without_receiver_deprecated();
      // Use inline allocation for all unmapped arguments objects within inlined
      // (i.e. non-outermost) frames, independent of the object size.
      Node* effect = NodeProperties::GetEffectInput(node);
      // Choose the correct frame state and frame state info depending on
      // whether there conceptually is an inlined arguments frame in the call
      // chain.
      FrameState args_state = GetArgumentsFrameState(frame_state);
      if (args_state.parameters()->opcode() == IrOpcode::kDeadValue) {
        // This protects against an incompletely propagated DeadValue node.
        // If the FrameState has a DeadValue input, then this node will be
        // pruned anyway.
        return NoChange();
      }
      FrameStateInfo args_state_info = args_state.frame_state_info();
      // Prepare element backing store to be used by the rest array.
      Node* const elements =
          TryAllocateRestArguments(effect, control, args_state, start_index);
      if (elements == nullptr) return NoChange();
      effect = elements->op()->EffectOutputCount() > 0 ? elements : effect;
      // Load the JSArray object map.
      Node* const jsarray_map = jsgraph()->ConstantNoHole(
          native_context().js_array_packed_elements_map(broker()), broker());
      // Actually allocate and initialize the jsarray.
      AllocationBuilder a(jsgraph(), broker(), effect, control);
      int argument_count = args_state_info.parameter_count_without_receiver();
      int length = std::max(0, argument_count - start_index);
      static_assert(JSArray::kHeaderSize == 4 * kTaggedSize);
      a.Allocate(ALIGN_TO_ALLOCATION_ALIGNMENT(JSArray::kHeaderSize));
      a.Store(AccessBuilder::ForMap(), jsarray_map);
      a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
              jsgraph()->EmptyFixedArrayConstant());
      a.Store(AccessBuilder::ForJSObjectElements(), elements);
      a.Store(AccessBuilder::ForJSArrayLength(PACKED_ELEMENTS),
              jsgraph()->ConstantNoHole(length));
      RelaxControls(node);
      a.FinishAndChange(node);
      return Changed(node);
    }
  }
  UNREACHABLE();
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::compiler::AllocationBuilder::Allocate(), broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::CreateArgumentsTypeOf(), DCHECK_EQ, v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForArgumentsCallee(), v8::internal::compiler::AccessBuilder::ForArgumentsLength(), v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::FrameState::frame_state_info(), v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::GetArgumentsFrameState(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetFrameStateInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::SharedFunctionInfoRef::internal_formal_parameter_count_without_receiver_deprecated(), jsgraph(), v8::internal::kMappedArguments, v8::internal::kRestParameter, v8::internal::kTaggedSize, v8::internal::kUnmappedArguments, v8::internal::length, v8::internal::compiler::MakeRef(), native_context(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::PACKED_ELEMENTS, v8::internal::compiler::FrameStateInfo::parameter_count_without_receiver(), v8::internal::compiler::FrameState::parameters(), v8::internal::compiler::FrameStateInfo::shared_info(), simplified(), v8::internal::compiler::TFGraph::start(), v8::internal::compiler::AllocationBuilder::Store(), TryAllocateAliasedArguments(), TryAllocateArguments(), TryAllocateRestArguments(), v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by Reduce().
ReduceJSCreateArray()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray (Node * node) [private]
Definition at line 640 of file js-create-lowering.cc.
                                                          {
  DCHECK_EQ(IrOpcode::kJSCreateArray, node->opcode());
  CreateArrayParameters const& p = CreateArrayParametersOf(node->op());
  int const arity = static_cast<int>(p.arity());
  OptionalAllocationSiteRef site_ref = p.site();
  AllocationType allocation = AllocationType::kYoung;
  OptionalMapRef initial_map = NodeProperties::GetJSCreateMap(broker(), node);
  if (!initial_map.has_value()) return NoChange();
  Node* new_target = NodeProperties::GetValueInput(node, 1);
  JSFunctionRef original_constructor =
      HeapObjectMatcher(new_target).Ref(broker()).AsJSFunction();
  SlackTrackingPrediction slack_tracking_prediction =
      dependencies()->DependOnInitialMapInstanceSizePrediction(
          original_constructor);
  // Tells whether we are protected by either the {site} or a
  // protector cell to do certain speculative optimizations.
  bool can_inline_call = false;
  // Check if we have a feedback {site} on the {node}.
  ElementsKind elements_kind = initial_map->elements_kind();
  if (site_ref) {
    elements_kind = site_ref->GetElementsKind();
    can_inline_call = site_ref->CanInlineCall();
    allocation = dependencies()->DependOnPretenureMode(*site_ref);
    dependencies()->DependOnElementsKind(*site_ref);
  } else {
    // If there is no allocation site, only inline the constructor when there is
    // overall speculation feedback that can be disabled on a deopt.
    can_inline_call = p.call_feedback().IsValid();
  }
  if (arity == 0) {
    Node* length = jsgraph()->ZeroConstant();
    int capacity = JSArray::kPreallocatedArrayElements;
    return ReduceNewArray(node, length, capacity, *initial_map, elements_kind,
                          allocation, slack_tracking_prediction,
                          p.call_feedback());
  } else if (arity == 1) {
    Node* length = NodeProperties::GetValueInput(node, 2);
    Type length_type = NodeProperties::GetType(length);
    if (!length_type.Maybe(Type::Number())) {
      // Handle the single argument case, where we know that the value
      // cannot be a valid Array length.
      elements_kind = GetMoreGeneralElementsKind(
          elements_kind, IsHoleyElementsKind(elements_kind) ? HOLEY_ELEMENTS
                                                            : PACKED_ELEMENTS);
      return ReduceNewArray(node, std::vector<Node*>{length}, *initial_map,
                            elements_kind, allocation,
                            slack_tracking_prediction, p.call_feedback());
    }
    if (length_type.Is(Type::SignedSmall()) && length_type.Min() >= 0 &&
        length_type.Max() <= kElementLoopUnrollLimit &&
        length_type.Min() == length_type.Max()) {
      int capacity = static_cast<int>(length_type.Max());
      // Replace length with a constant in order to protect against a potential
      // typer bug leading to length > capacity.
      length = jsgraph()->ConstantNoHole(capacity);
      return ReduceNewArray(node, length, capacity, *initial_map, elements_kind,
                            allocation, slack_tracking_prediction,
                            p.call_feedback());
    }
    if (length_type.Maybe(Type::UnsignedSmall()) && can_inline_call) {
      return ReduceNewArray(node, length, *initial_map, elements_kind,
                            allocation, slack_tracking_prediction,
                            p.call_feedback());
    }
  } else if (arity <= JSArray::kInitialMaxFastElementArray) {
    // Gather the values to store into the newly created array.
    bool values_all_smis = true, values_all_numbers = true,
         values_any_nonnumber = false;
    std::vector<Node*> values;
    values.reserve(p.arity());
    for (int i = 0; i < arity; ++i) {
      Node* value = NodeProperties::GetValueInput(node, 2 + i);
      Type value_type = NodeProperties::GetType(value);
      if (!value_type.Is(Type::SignedSmall())) {
        values_all_smis = false;
      }
      if (!value_type.Is(Type::Number())) {
        values_all_numbers = false;
      }
      if (!value_type.Maybe(Type::Number())) {
        values_any_nonnumber = true;
      }
      values.push_back(value);
    }
    // Try to figure out the ideal elements kind statically.
    if (values_all_smis) {
      // Smis can be stored with any elements kind.
    } else if (values_all_numbers) {
      elements_kind = GetMoreGeneralElementsKind(
          elements_kind, IsHoleyElementsKind(elements_kind)
                             ? HOLEY_DOUBLE_ELEMENTS
                             : PACKED_DOUBLE_ELEMENTS);
    } else if (values_any_nonnumber) {
      elements_kind = GetMoreGeneralElementsKind(
          elements_kind, IsHoleyElementsKind(elements_kind) ? HOLEY_ELEMENTS
                                                            : PACKED_ELEMENTS);
    } else if (!can_inline_call) {
      // We have some crazy combination of types for the {values} where
      // there's no clear decision on the elements kind statically. And
      // we don't have a protection against deoptimization loops for the
      // checks that are introduced in the call to ReduceNewArray, so
      // we cannot inline this invocation of the Array constructor here.
      return NoChange();
    }
    return ReduceNewArray(node, values, *initial_map, elements_kind, allocation,
                          slack_tracking_prediction, p.call_feedback());
  }
  return NoChange();
}
References v8::internal::compiler::CreateArrayParameters::arity(), broker(), v8::internal::compiler::CreateArrayParameters::call_feedback(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::CreateArrayParametersOf(), DCHECK_EQ, dependencies(), v8::internal::compiler::CompilationDependencies::DependOnElementsKind(), v8::internal::compiler::CompilationDependencies::DependOnInitialMapInstanceSizePrediction(), v8::internal::compiler::CompilationDependencies::DependOnPretenureMode(), v8::internal::compiler::NodeProperties::GetJSCreateMap(), v8::internal::GetMoreGeneralElementsKind(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::initial_map, v8::internal::compiler::Type::Is(), v8::internal::IsHoleyElementsKind(), v8::internal::compiler::FeedbackSource::IsValid(), jsgraph(), v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::kElementLoopUnrollLimit, v8::internal::JSArray::kInitialMaxFastElementArray, v8::internal::JSArray::kPreallocatedArrayElements, v8::internal::kYoung, v8::internal::length, v8::internal::compiler::Type::Max(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::Type::Min(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, ReduceNewArray(), v8::internal::compiler::Type::SignedSmall(), v8::internal::compiler::CreateArrayParameters::site(), v8::internal::compiler::Type::UnsignedSmall(), v8::internal::value, and v8::internal::wasm::value_type().
Referenced by Reduce().
ReduceJSCreateArrayIterator()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateArrayIterator (Node * node) [private]
Definition at line 756 of file js-create-lowering.cc.
                                                                  {
  DCHECK_EQ(IrOpcode::kJSCreateArrayIterator, node->opcode());
  CreateArrayIteratorParameters const& p =
      CreateArrayIteratorParametersOf(node->op());
  Node* iterated_object = NodeProperties::GetValueInput(node, 0);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  // Create the JSArrayIterator result.
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.Allocate(JSArrayIterator::kHeaderSize, AllocationType::kYoung,
             Type::OtherObject());
  a.Store(AccessBuilder::ForMap(),
          native_context().initial_array_iterator_map(broker()));
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSArrayIteratorIteratedObject(), iterated_object);
  a.Store(AccessBuilder::ForJSArrayIteratorNextIndex(),
          jsgraph()->ZeroConstant());
  a.Store(AccessBuilder::ForJSArrayIteratorKind(),
          jsgraph()->ConstantNoHole(static_cast<int>(p.kind())));
  RelaxControls(node);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), broker(), v8::internal::compiler::CreateArrayIteratorParametersOf(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForJSArrayIteratorIteratedObject(), v8::internal::compiler::AccessBuilder::ForJSArrayIteratorKind(), v8::internal::compiler::AccessBuilder::ForJSArrayIteratorNextIndex(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), jsgraph(), v8::internal::compiler::CreateArrayIteratorParameters::kind(), v8::internal::kYoung, native_context(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::AllocationBuilder::Store().
Referenced by Reduce().
ReduceJSCreateAsyncFunctionObject()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateAsyncFunctionObject (Node * node) [private]
Definition at line 784 of file js-create-lowering.cc.
                                                                        {
  DCHECK_EQ(IrOpcode::kJSCreateAsyncFunctionObject, node->opcode());
  int const register_count = RegisterCountOf(node->op());
  Node* closure = NodeProperties::GetValueInput(node, 0);
  Node* receiver = NodeProperties::GetValueInput(node, 1);
  Node* promise = NodeProperties::GetValueInput(node, 2);
  Node* context = NodeProperties::GetContextInput(node);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  // Create the register file.
  MapRef fixed_array_map = broker()->fixed_array_map();
  AllocationBuilder ab(jsgraph(), broker(), effect, control);
  CHECK(ab.CanAllocateArray(register_count, fixed_array_map));
  ab.AllocateArray(register_count, fixed_array_map);
  for (int i = 0; i < register_count; ++i) {
    ab.Store(AccessBuilder::ForFixedArraySlot(i),
             jsgraph()->UndefinedConstant());
  }
  Node* parameters_and_registers = effect = ab.Finish();
  // Create the JSAsyncFunctionObject result.
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.Allocate(JSAsyncFunctionObject::kHeaderSize);
  a.Store(AccessBuilder::ForMap(),
          native_context().async_function_object_map(broker()));
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSGeneratorObjectContext(), context);
  a.Store(AccessBuilder::ForJSGeneratorObjectFunction(), closure);
  a.Store(AccessBuilder::ForJSGeneratorObjectReceiver(), receiver);
  a.Store(AccessBuilder::ForJSGeneratorObjectInputOrDebugPos(),
          jsgraph()->UndefinedConstant());
  a.Store(AccessBuilder::ForJSGeneratorObjectResumeMode(),
          jsgraph()->ConstantNoHole(JSGeneratorObject::kNext));
  a.Store(AccessBuilder::ForJSGeneratorObjectContinuation(),
          jsgraph()->ConstantNoHole(JSGeneratorObject::kGeneratorExecuting));
  a.Store(AccessBuilder::ForJSGeneratorObjectParametersAndRegisters(),
          parameters_and_registers);
  a.Store(AccessBuilder::ForJSAsyncFunctionObjectPromise(), promise);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), v8::internal::compiler::AllocationBuilder::AllocateArray(), broker(), v8::internal::compiler::AllocationBuilder::CanAllocateArray(), CHECK, DCHECK_EQ, v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForFixedArraySlot(), v8::internal::compiler::AccessBuilder::ForJSAsyncFunctionObjectPromise(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContext(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContinuation(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectFunction(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectInputOrDebugPos(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectParametersAndRegisters(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectReceiver(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectResumeMode(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, jsgraph(), v8::internal::JSGeneratorObject::kGeneratorExecuting, v8::internal::JSGeneratorObject::kNext, native_context(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::RegisterCountOf(), v8::internal::compiler::AllocationBuilder::Store(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by Reduce().
ReduceJSCreateBlockContext()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateBlockContext (Node * node) [private]
Definition at line 1342 of file js-create-lowering.cc.
                                                                 {
  DCHECK_EQ(IrOpcode::kJSCreateBlockContext, node->opcode());
  ScopeInfoRef scope_info = ScopeInfoOf(node->op());
  int const context_length = scope_info.ContextLength();
  // Use inline allocation for block contexts up to a size limit.
  if (context_length < kBlockContextAllocationLimit) {
    // JSCreateBlockContext[scope[length < limit]](fun)
    Node* effect = NodeProperties::GetEffectInput(node);
    Node* control = NodeProperties::GetControlInput(node);
    Node* context = NodeProperties::GetContextInput(node);
    AllocationBuilder a(jsgraph(), broker(), effect, control);
    static_assert(Context::MIN_CONTEXT_SLOTS == 2); // Ensure fully covered.
    a.AllocateContext(context_length,
                      native_context().block_context_map(broker()));
    a.Store(AccessBuilder::ForContextSlot(Context::SCOPE_INFO_INDEX),
            scope_info);
    a.Store(AccessBuilder::ForContextSlot(Context::PREVIOUS_INDEX), context);
    for (int i = Context::MIN_CONTEXT_SLOTS; i < context_length; ++i) {
      a.Store(AccessBuilder::ForContextSlot(i), jsgraph()->UndefinedConstant());
    }
    RelaxControls(node);
    a.FinishAndChange(node);
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::AllocationBuilder::AllocateContext(), broker(), v8::internal::compiler::ScopeInfoRef::ContextLength(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, jsgraph(), v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::kBlockContextAllocationLimit, v8::internal::Context::MIN_CONTEXT_SLOTS, native_context(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::Context::PREVIOUS_INDEX, v8::internal::Context::SCOPE_INFO_INDEX, v8::internal::compiler::ScopeInfoOf(), v8::internal::compiler::AllocationBuilder::Store(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by Reduce().
ReduceJSCreateBoundFunction()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateBoundFunction (Node * node) [private]
Definition at line 896 of file js-create-lowering.cc.
                                                                  {
  DCHECK_EQ(IrOpcode::kJSCreateBoundFunction, node->opcode());
  CreateBoundFunctionParameters const& p =
      CreateBoundFunctionParametersOf(node->op());
  int const arity = static_cast<int>(p.arity());
  MapRef const map = p.map();
  Node* bound_target_function = NodeProperties::GetValueInput(node, 0);
  Node* bound_this = NodeProperties::GetValueInput(node, 1);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  // Create the [[BoundArguments]] for the result.
  Node* bound_arguments = jsgraph()->EmptyFixedArrayConstant();
  if (arity > 0) {
    MapRef fixed_array_map = broker()->fixed_array_map();
    AllocationBuilder ab(jsgraph(), broker(), effect, control);
    CHECK(ab.CanAllocateArray(arity, fixed_array_map));
    ab.AllocateArray(arity, fixed_array_map);
    for (int i = 0; i < arity; ++i) {
      ab.Store(AccessBuilder::ForFixedArraySlot(i),
               NodeProperties::GetValueInput(node, 2 + i));
    }
    bound_arguments = effect = ab.Finish();
  }
  // Create the JSBoundFunction result.
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.Allocate(JSBoundFunction::kHeaderSize, AllocationType::kYoung,
             Type::BoundFunction());
  a.Store(AccessBuilder::ForMap(), map);
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSBoundFunctionBoundTargetFunction(),
          bound_target_function);
  a.Store(AccessBuilder::ForJSBoundFunctionBoundThis(), bound_this);
  a.Store(AccessBuilder::ForJSBoundFunctionBoundArguments(), bound_arguments);
  RelaxControls(node);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), v8::internal::compiler::AllocationBuilder::AllocateArray(), v8::internal::compiler::CreateBoundFunctionParameters::arity(), broker(), v8::internal::compiler::AllocationBuilder::CanAllocateArray(), CHECK, v8::internal::compiler::CreateBoundFunctionParametersOf(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForFixedArraySlot(), v8::internal::compiler::AccessBuilder::ForJSBoundFunctionBoundArguments(), v8::internal::compiler::AccessBuilder::ForJSBoundFunctionBoundTargetFunction(), v8::internal::compiler::AccessBuilder::ForJSBoundFunctionBoundThis(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, jsgraph(), v8::internal::kYoung, v8::internal::compiler::CreateBoundFunctionParameters::map(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::AllocationBuilder::Store().
Referenced by Reduce().
ReduceJSCreateCatchContext()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateCatchContext (Node * node) [private]
Definition at line 1321 of file js-create-lowering.cc.
                                                                 {
  DCHECK_EQ(IrOpcode::kJSCreateCatchContext, node->opcode());
  ScopeInfoRef scope_info = ScopeInfoOf(node->op());
  Node* exception = NodeProperties::GetValueInput(node, 0);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* context = NodeProperties::GetContextInput(node);
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  static_assert(Context::MIN_CONTEXT_SLOTS == 2); // Ensure fully covered.
  a.AllocateContext(Context::MIN_CONTEXT_SLOTS + 1,
                    native_context().catch_context_map(broker()));
  a.Store(AccessBuilder::ForContextSlot(Context::SCOPE_INFO_INDEX), scope_info);
  a.Store(AccessBuilder::ForContextSlot(Context::PREVIOUS_INDEX), context);
  a.Store(AccessBuilder::ForContextSlot(Context::THROWN_OBJECT_INDEX),
          exception);
  RelaxControls(node);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::AllocateContext(), broker(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), jsgraph(), v8::internal::Context::MIN_CONTEXT_SLOTS, native_context(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::Context::PREVIOUS_INDEX, v8::internal::Context::SCOPE_INFO_INDEX, v8::internal::compiler::ScopeInfoOf(), v8::internal::compiler::AllocationBuilder::Store(), and v8::internal::Context::THROWN_OBJECT_INDEX.
Referenced by Reduce().
ReduceJSCreateClosure()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateClosure (Node * node) [private]
Definition at line 939 of file js-create-lowering.cc.
                                                            {
  JSCreateClosureNode n(node);
  CreateClosureParameters const& p = n.Parameters();
  SharedFunctionInfoRef shared = p.shared_info();
  FeedbackCellRef feedback_cell = n.GetFeedbackCellRefChecked(broker());
#ifndef V8_ENABLE_LEAPTIERING
  HeapObjectRef code = p.code();
#endif
  Effect effect = n.effect();
  Control control = n.control();
  Node* context = n.context();
  // Use inline allocation of closures only for instantiation sites that have
  // seen more than one instantiation, this simplifies the generated code and
  // also serves as a heuristic of which allocation sites benefit from it.
  if (!feedback_cell.map(broker()).equals(broker()->many_closures_cell_map())) {
    return NoChange();
  }
  // Don't inline anything for class constructors.
  if (IsClassConstructor(shared.kind())) return NoChange();
  MapRef function_map = native_context().GetFunctionMapFromIndex(
      broker(), shared.function_map_index());
  DCHECK(!function_map.IsInobjectSlackTrackingInProgress());
  DCHECK(!function_map.is_dictionary_map());
#ifdef V8_ENABLE_LEAPTIERING
  // TODO(saelo): we should embed the dispatch handle directly into the
  // generated code instead of loading it at runtime from the FeedbackCell.
  // This will likely first require GC support though.
  Node* feedback_cell_node = jsgraph()->ConstantNoHole(feedback_cell, broker());
  Node* dispatch_handle;
  if (shared.HasBuiltinId()) {
    // This uses a smi constant to store the static dispatch handle, since
    // currently we expect dispatch handles to be encoded as numbers in the
    // deopt metadata.
    // TODO(olivf): Dispatch handles should be supported in deopt metadata.
    dispatch_handle = jsgraph()->SmiConstant(
        jsgraph()
            ->isolate()
            ->builtin_dispatch_handle(shared.builtin_id())
            .value());
  } else {
    DCHECK(feedback_cell.object()->dispatch_handle() != kNullJSDispatchHandle);
    dispatch_handle = effect = graph()->NewNode(
        simplified()->LoadField(
            AccessBuilder::ForFeedbackCellDispatchHandleNoWriteBarrier()),
        feedback_cell_node, effect, control);
  }
#endif // V8_ENABLE_LEAPTIERING
  // TODO(turbofan): We should use the pretenure flag from {p} here,
  // but currently the heuristic in the parser works against us, as
  // it marks closures like
  //
  // args[l] = function(...) { ... }
  //
  // for old-space allocation, which doesn't always make sense. For
  // example in case of the bluebird-parallel benchmark, where this
  // is a core part of the *promisify* logic (see crbug.com/810132).
  AllocationType allocation = AllocationType::kYoung;
  // Emit code to allocate the JSFunction instance.
  static_assert(JSFunction::kSizeWithoutPrototype == 7 * kTaggedSize);
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.Allocate(function_map.instance_size(), allocation,
             Type::CallableFunction());
  a.Store(AccessBuilder::ForMap(), function_map);
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSFunctionSharedFunctionInfo(), shared);
  a.Store(AccessBuilder::ForJSFunctionContext(), context);
  a.Store(AccessBuilder::ForJSFunctionFeedbackCell(), feedback_cell);
#ifdef V8_ENABLE_LEAPTIERING
  a.Store(AccessBuilder::ForJSFunctionDispatchHandleNoWriteBarrier(),
          dispatch_handle);
#else
  a.Store(AccessBuilder::ForJSFunctionCode(), code);
#endif // V8_ENABLE_LEAPTIERING
  static_assert(JSFunction::kSizeWithoutPrototype == 7 * kTaggedSize);
  if (function_map.has_prototype_slot()) {
    a.Store(AccessBuilder::ForJSFunctionPrototypeOrInitialMap(),
            jsgraph()->TheHoleConstant());
    static_assert(JSFunction::kSizeWithPrototype == 8 * kTaggedSize);
  }
  for (int i = 0; i < function_map.GetInObjectProperties(); i++) {
    a.Store(AccessBuilder::ForJSObjectInObjectProperty(function_map, i),
            jsgraph()->UndefinedConstant());
  }
  RelaxControls(node);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), broker(), v8::internal::compiler::SharedFunctionInfoRef::builtin_id(), v8::internal::compiler::CreateClosureParameters::code(), code, v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::JSNodeWrapperBase::context(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::DCHECK(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForJSFunctionCode(), v8::internal::compiler::AccessBuilder::ForJSFunctionContext(), v8::internal::compiler::AccessBuilder::ForJSFunctionFeedbackCell(), v8::internal::compiler::AccessBuilder::ForJSFunctionPrototypeOrInitialMap(), v8::internal::compiler::AccessBuilder::ForJSFunctionSharedFunctionInfo(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectInObjectProperty(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::libvtune::function_map, v8::internal::compiler::JSCreateClosureNode::GetFeedbackCellRefChecked(), v8::internal::compiler::NativeContextRef::GetFunctionMapFromIndex(), graph(), v8::internal::IsClassConstructor(), jsgraph(), v8::internal::kNullJSDispatchHandle(), v8::internal::JSFunction::kSizeWithoutPrototype, v8::internal::JSFunction::kSizeWithPrototype, v8::internal::kTaggedSize, v8::internal::kYoung, v8::internal::compiler::HeapObjectRef::map(), native_context(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::FeedbackCellRef::object(), v8::internal::compiler::JSCreateClosureNode::Parameters(), v8::internal::compiler::CreateClosureParameters::shared_info(), simplified(), v8::internal::compiler::JSGraph::SmiConstant(), v8::internal::compiler::AllocationBuilder::Store(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by Reduce().
ReduceJSCreateCollectionIterator()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateCollectionIterator (Node * node) [private]
Definition at line 863 of file js-create-lowering.cc.
                                                                       {
  DCHECK_EQ(IrOpcode::kJSCreateCollectionIterator, node->opcode());
  CreateCollectionIteratorParameters const& p =
      CreateCollectionIteratorParametersOf(node->op());
  Node* iterated_object = NodeProperties::GetValueInput(node, 0);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  // Load the OrderedHashTable from the {receiver}.
  Node* table = effect = graph()->NewNode(
      simplified()->LoadField(AccessBuilder::ForJSCollectionTable()),
      iterated_object, effect, control);
  // Create the JSCollectionIterator result.
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.Allocate(JSCollectionIterator::kHeaderSize, AllocationType::kYoung,
             Type::OtherObject());
  a.Store(
      AccessBuilder::ForMap(),
      MapForCollectionIterationKind(broker(), native_context(),
                                    p.collection_kind(), p.iteration_kind()));
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSCollectionIteratorTable(), table);
  a.Store(AccessBuilder::ForJSCollectionIteratorIndex(),
          jsgraph()->ZeroConstant());
  RelaxControls(node);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), broker(), v8::internal::compiler::CreateCollectionIteratorParameters::collection_kind(), v8::internal::compiler::CreateCollectionIteratorParametersOf(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForJSCollectionIteratorIndex(), v8::internal::compiler::AccessBuilder::ForJSCollectionIteratorTable(), v8::internal::compiler::AccessBuilder::ForJSCollectionTable(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::CreateCollectionIteratorParameters::iteration_kind(), jsgraph(), v8::internal::kYoung, v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::MapForCollectionIterationKind(), native_context(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), simplified(), and v8::internal::compiler::AllocationBuilder::Store().
Referenced by Reduce().
ReduceJSCreateEmptyLiteralArray()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralArray (Node * node) [private]
Definition at line 1168 of file js-create-lowering.cc.
                                                                      {
  JSCreateEmptyLiteralArrayNode n(node);
  FeedbackParameter const& p = n.Parameters();
  ProcessedFeedback const& feedback =
      broker()->GetFeedbackForArrayOrObjectLiteral(p.feedback());
  if (!feedback.IsInsufficient()) {
    AllocationSiteRef site = feedback.AsLiteral().value();
    DCHECK(!site.PointsToLiteral());
    MapRef initial_map =
        native_context().GetInitialJSArrayMap(broker(), site.GetElementsKind());
    AllocationType const allocation =
        dependencies()->DependOnPretenureMode(site);
    dependencies()->DependOnElementsKind(site);
    Node* length = jsgraph()->ZeroConstant();
    DCHECK(!initial_map.IsInobjectSlackTrackingInProgress());
    SlackTrackingPrediction slack_tracking_prediction(
        initial_map, initial_map.instance_size());
    return ReduceNewArray(node, length, 0, initial_map,
                          initial_map.elements_kind(), allocation,
                          slack_tracking_prediction, FeedbackSource());
  }
  return NoChange();
}
References v8::internal::compiler::ProcessedFeedback::AsLiteral(), broker(), v8::internal::DCHECK(), dependencies(), v8::internal::compiler::CompilationDependencies::DependOnElementsKind(), v8::internal::compiler::CompilationDependencies::DependOnPretenureMode(), v8::internal::compiler::FeedbackParameter::feedback(), v8::internal::compiler::AllocationSiteRef::GetElementsKind(), v8::internal::compiler::JSHeapBroker::GetFeedbackForArrayOrObjectLiteral(), v8::internal::compiler::NativeContextRef::GetInitialJSArrayMap(), v8::internal::compiler::initial_map, v8::internal::compiler::ProcessedFeedback::IsInsufficient(), jsgraph(), v8::internal::length, native_context(), v8::internal::compiler::JSCreateEmptyLiteralArrayNode::Parameters(), v8::internal::compiler::AllocationSiteRef::PointsToLiteral(), ReduceNewArray(), and v8::internal::compiler::SingleValueFeedback< T, K >::value().
Referenced by Reduce().
ReduceJSCreateEmptyLiteralObject()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateEmptyLiteralObject (Node * node) [private]
Definition at line 1192 of file js-create-lowering.cc.
                                                                       {
  DCHECK_EQ(IrOpcode::kJSCreateEmptyLiteralObject, node->opcode());
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  // Retrieve the initial map for the object.
  MapRef map = native_context().object_function(broker()).initial_map(broker());
  DCHECK(!map.is_dictionary_map());
  DCHECK(!map.IsInobjectSlackTrackingInProgress());
  Node* js_object_map = jsgraph()->ConstantNoHole(map, broker());
  // Setup elements and properties.
  Node* elements = jsgraph()->EmptyFixedArrayConstant();
  // Perform the allocation of the actual JSArray object.
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.Allocate(map.instance_size());
  a.Store(AccessBuilder::ForMap(), js_object_map);
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(), elements);
  for (int i = 0; i < map.GetInObjectProperties(); i++) {
    a.Store(AccessBuilder::ForJSObjectInObjectProperty(map, i),
            jsgraph()->UndefinedConstant());
  }
  RelaxControls(node);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectInObjectProperty(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::MapRef::GetInObjectProperties(), v8::internal::compiler::MapRef::instance_size(), v8::internal::compiler::MapRef::is_dictionary_map(), v8::internal::compiler::MapRef::IsInobjectSlackTrackingInProgress(), jsgraph(), native_context(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::AllocationBuilder::Store(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by Reduce().
ReduceJSCreateFunctionContext()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateFunctionContext (Node * node) [private]
Definition at line 1257 of file js-create-lowering.cc.
                                                                    {
  DCHECK_EQ(IrOpcode::kJSCreateFunctionContext, node->opcode());
  const CreateFunctionContextParameters& parameters =
      CreateFunctionContextParametersOf(node->op());
  ScopeInfoRef scope_info = parameters.scope_info();
  int slot_count = parameters.slot_count();
  ScopeType scope_type = parameters.scope_type();
  // Use inline allocation for function contexts up to a size limit.
  if (slot_count < kFunctionContextAllocationLimit) {
    // JSCreateFunctionContext[slot_count < limit]](fun)
    Node* effect = NodeProperties::GetEffectInput(node);
    Node* control = NodeProperties::GetControlInput(node);
    Node* context = NodeProperties::GetContextInput(node);
    AllocationBuilder a(jsgraph(), broker(), effect, control);
    static_assert(Context::MIN_CONTEXT_SLOTS == 2); // Ensure fully covered.
    int context_length = slot_count + Context::MIN_CONTEXT_SLOTS;
    switch (scope_type) {
      case EVAL_SCOPE:
        a.AllocateContext(context_length,
                          native_context().eval_context_map(broker()));
        break;
      case FUNCTION_SCOPE:
        a.AllocateContext(context_length,
                          native_context().function_context_map(broker()));
        break;
      default:
        UNREACHABLE();
    }
    a.Store(AccessBuilder::ForContextSlot(Context::SCOPE_INFO_INDEX),
            scope_info);
    a.Store(AccessBuilder::ForContextSlot(Context::PREVIOUS_INDEX), context);
    for (int i = Context::MIN_CONTEXT_SLOTS; i < context_length; ++i) {
      a.Store(AccessBuilder::ForContextSlot(i), jsgraph()->UndefinedConstant());
    }
    RelaxControls(node);
    a.FinishAndChange(node);
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::AllocationBuilder::AllocateContext(), broker(), v8::internal::compiler::CreateFunctionContextParametersOf(), DCHECK_EQ, v8::internal::EVAL_SCOPE, v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::FUNCTION_SCOPE, v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, jsgraph(), v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::kFunctionContextAllocationLimit, v8::internal::Context::MIN_CONTEXT_SLOTS, native_context(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::Context::PREVIOUS_INDEX, v8::internal::compiler::CreateFunctionContextParameters::scope_info(), v8::internal::Context::SCOPE_INFO_INDEX, v8::internal::compiler::CreateFunctionContextParameters::scope_type(), v8::internal::compiler::CreateFunctionContextParameters::slot_count(), v8::internal::compiler::AllocationBuilder::Store(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::UNREACHABLE().
Referenced by Reduce().
ReduceJSCreateGeneratorObject()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateGeneratorObject (Node * node) [private]
Definition at line 392 of file js-create-lowering.cc.
                                                                    {
  DCHECK_EQ(IrOpcode::kJSCreateGeneratorObject, node->opcode());
  Node* const closure = NodeProperties::GetValueInput(node, 0);
  Node* const receiver = NodeProperties::GetValueInput(node, 1);
  Node* const context = NodeProperties::GetContextInput(node);
  Type const closure_type = NodeProperties::GetType(closure);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* const control = NodeProperties::GetControlInput(node);
  if (closure_type.IsHeapConstant()) {
    DCHECK(closure_type.AsHeapConstant()->Ref().IsJSFunction());
    JSFunctionRef js_function =
        closure_type.AsHeapConstant()->Ref().AsJSFunction();
    if (!js_function.has_initial_map(broker())) return NoChange();
    SlackTrackingPrediction slack_tracking_prediction =
        dependencies()->DependOnInitialMapInstanceSizePrediction(js_function);
    MapRef initial_map = js_function.initial_map(broker());
    DCHECK(initial_map.instance_type() == JS_GENERATOR_OBJECT_TYPE ||
           initial_map.instance_type() == JS_ASYNC_GENERATOR_OBJECT_TYPE);
    // Allocate a register file.
    SharedFunctionInfoRef shared = js_function.shared(broker());
    DCHECK(shared.HasBytecodeArray());
    int parameter_count_no_receiver =
        shared.internal_formal_parameter_count_without_receiver_deprecated();
    int length = parameter_count_no_receiver +
                 shared.GetBytecodeArray(broker()).register_count();
    MapRef fixed_array_map = broker()->fixed_array_map();
    AllocationBuilder ab(jsgraph(), broker(), effect, control);
    if (!ab.CanAllocateArray(length, fixed_array_map)) {
      return NoChange();
    }
    ab.AllocateArray(length, fixed_array_map);
    for (int i = 0; i < length; ++i) {
      ab.Store(AccessBuilder::ForFixedArraySlot(i),
               jsgraph()->UndefinedConstant());
    }
    Node* parameters_and_registers = effect = ab.Finish();
    // Emit code to allocate the JS[Async]GeneratorObject instance.
    AllocationBuilder a(jsgraph(), broker(), effect, control);
    a.Allocate(slack_tracking_prediction.instance_size());
    Node* undefined = jsgraph()->UndefinedConstant();
    a.Store(AccessBuilder::ForMap(), initial_map);
    a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
            jsgraph()->EmptyFixedArrayConstant());
    a.Store(AccessBuilder::ForJSObjectElements(),
            jsgraph()->EmptyFixedArrayConstant());
    a.Store(AccessBuilder::ForJSGeneratorObjectContext(), context);
    a.Store(AccessBuilder::ForJSGeneratorObjectFunction(), closure);
    a.Store(AccessBuilder::ForJSGeneratorObjectReceiver(), receiver);
    a.Store(AccessBuilder::ForJSGeneratorObjectInputOrDebugPos(), undefined);
    a.Store(AccessBuilder::ForJSGeneratorObjectResumeMode(),
            jsgraph()->ConstantNoHole(JSGeneratorObject::kNext));
    a.Store(AccessBuilder::ForJSGeneratorObjectContinuation(),
            jsgraph()->ConstantNoHole(JSGeneratorObject::kGeneratorExecuting));
    a.Store(AccessBuilder::ForJSGeneratorObjectParametersAndRegisters(),
            parameters_and_registers);
    if (initial_map.instance_type() == JS_ASYNC_GENERATOR_OBJECT_TYPE) {
      a.Store(AccessBuilder::ForJSAsyncGeneratorObjectQueue(), undefined);
      a.Store(AccessBuilder::ForJSAsyncGeneratorObjectIsAwaiting(),
              jsgraph()->ZeroConstant());
    }
    // Handle in-object properties, too.
    for (int i = 0; i < slack_tracking_prediction.inobject_property_count();
         ++i) {
      a.Store(AccessBuilder::ForJSObjectInObjectProperty(initial_map, i),
              undefined);
    }
    a.FinishAndChange(node);
    return Changed(node);
  }
  return NoChange();
}
References v8::internal::compiler::AllocationBuilder::Allocate(), v8::internal::compiler::AllocationBuilder::AllocateArray(), v8::internal::compiler::Type::AsHeapConstant(), broker(), v8::internal::compiler::AllocationBuilder::CanAllocateArray(), v8::internal::DCHECK(), DCHECK_EQ, dependencies(), v8::internal::compiler::CompilationDependencies::DependOnInitialMapInstanceSizePrediction(), v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForFixedArraySlot(), v8::internal::compiler::AccessBuilder::ForJSAsyncGeneratorObjectIsAwaiting(), v8::internal::compiler::AccessBuilder::ForJSAsyncGeneratorObjectQueue(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContext(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectContinuation(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectFunction(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectInputOrDebugPos(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectParametersAndRegisters(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectReceiver(), v8::internal::compiler::AccessBuilder::ForJSGeneratorObjectResumeMode(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectInObjectProperty(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::SharedFunctionInfoRef::GetBytecodeArray(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::JSFunctionRef::has_initial_map(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::initial_map, v8::internal::compiler::JSFunctionRef::initial_map(), v8::internal::compiler::SlackTrackingPrediction::inobject_property_count(), v8::internal::compiler::SlackTrackingPrediction::instance_size(), v8::internal::compiler::SharedFunctionInfoRef::internal_formal_parameter_count_without_receiver_deprecated(), v8::internal::compiler::Type::IsHeapConstant(), jsgraph(), v8::internal::JSGeneratorObject::kGeneratorExecuting, v8::internal::JSGeneratorObject::kNext, v8::internal::length, v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapConstantType::Ref(), v8::internal::compiler::BytecodeArrayRef::register_count(), v8::internal::compiler::JSFunctionRef::shared(), v8::internal::compiler::AllocationBuilder::Store(), v8::internal::undefined, and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by Reduce().
ReduceJSCreateIterResultObject()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateIterResultObject (Node * node) [private]
Definition at line 1036 of file js-create-lowering.cc.
                                                                     {
  DCHECK_EQ(IrOpcode::kJSCreateIterResultObject, node->opcode());
  Node* value = NodeProperties::GetValueInput(node, 0);
  Node* done = NodeProperties::GetValueInput(node, 1);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* iterator_result_map = jsgraph()->ConstantNoHole(
      native_context().iterator_result_map(broker()), broker());
  // Emit code to allocate the JSIteratorResult instance.
  AllocationBuilder a(jsgraph(), broker(), effect, graph()->start());
  a.Allocate(JSIteratorResult::kSize);
  a.Store(AccessBuilder::ForMap(), iterator_result_map);
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSIteratorResultValue(), value);
  a.Store(AccessBuilder::ForJSIteratorResultDone(), done);
  static_assert(JSIteratorResult::kSize == 5 * kTaggedSize);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForJSIteratorResultDone(), v8::internal::compiler::AccessBuilder::ForJSIteratorResultValue(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), jsgraph(), v8::internal::kTaggedSize, native_context(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::AllocationBuilder::Store(), and v8::internal::value.
Referenced by Reduce().
ReduceJSCreateKeyValueArray()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateKeyValueArray (Node * node) [private]
Definition at line 1083 of file js-create-lowering.cc.
                                                                  {
  DCHECK_EQ(IrOpcode::kJSCreateKeyValueArray, node->opcode());
  Node* key = NodeProperties::GetValueInput(node, 0);
  Node* value = NodeProperties::GetValueInput(node, 1);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* array_map = jsgraph()->ConstantNoHole(
      native_context().js_array_packed_elements_map(broker()), broker());
  Node* length = jsgraph()->ConstantNoHole(2);
  AllocationBuilder aa(jsgraph(), broker(), effect, graph()->start());
  aa.AllocateArray(2, broker()->fixed_array_map());
  aa.Store(AccessBuilder::ForFixedArrayElement(PACKED_ELEMENTS),
           jsgraph()->ZeroConstant(), key);
  aa.Store(AccessBuilder::ForFixedArrayElement(PACKED_ELEMENTS),
           jsgraph()->OneConstant(), value);
  Node* elements = aa.Finish();
  AllocationBuilder a(jsgraph(), broker(), elements, graph()->start());
  a.Allocate(ALIGN_TO_ALLOCATION_ALIGNMENT(JSArray::kHeaderSize));
  a.Store(AccessBuilder::ForMap(), array_map);
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(), elements);
  a.Store(AccessBuilder::ForJSArrayLength(PACKED_ELEMENTS), length);
  static_assert(JSArray::kHeaderSize == 4 * kTaggedSize);
  a.FinishAndChange(node);
  return Changed(node);
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, v8::internal::compiler::AllocationBuilder::Allocate(), v8::internal::compiler::AllocationBuilder::AllocateArray(), broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), jsgraph(), v8::internal::key, v8::internal::kTaggedSize, v8::internal::length, native_context(), v8::internal::compiler::Node::opcode(), v8::internal::PACKED_ELEMENTS, v8::internal::compiler::AllocationBuilder::Store(), and v8::internal::value.
Referenced by Reduce().
ReduceJSCreateLiteralArrayOrObject()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralArrayOrObject (Node * node) [private]
Definition at line 1142 of file js-create-lowering.cc.
                                                                         {
  DCHECK(node->opcode() == IrOpcode::kJSCreateLiteralArray ||
         node->opcode() == IrOpcode::kJSCreateLiteralObject);
  JSCreateLiteralOpNode n(node);
  CreateLiteralParameters const& p = n.Parameters();
  Effect effect = n.effect();
  Control control = n.control();
  ProcessedFeedback const& feedback =
      broker()->GetFeedbackForArrayOrObjectLiteral(p.feedback());
  if (!feedback.IsInsufficient()) {
    AllocationSiteRef site = feedback.AsLiteral().value();
    if (!site.boilerplate(broker()).has_value()) return NoChange();
    AllocationType allocation = dependencies()->DependOnPretenureMode(site);
    int max_properties = kMaxFastLiteralProperties;
    std::optional<Node*> maybe_value = TryAllocateFastLiteral(
        effect, control, *site.boilerplate(broker()), allocation,
        kMaxFastLiteralDepth, &max_properties);
    if (!maybe_value.has_value()) return NoChange();
    dependencies()->DependOnElementsKinds(site);
    Node* value = effect = maybe_value.value();
    ReplaceWithValue(node, value, effect, control);
    return Replace(value);
  }
  return NoChange();
}
References v8::internal::compiler::ProcessedFeedback::AsLiteral(), v8::internal::compiler::AllocationSiteRef::boilerplate(), broker(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::DCHECK(), dependencies(), v8::internal::compiler::CompilationDependencies::DependOnElementsKinds(), v8::internal::compiler::CompilationDependencies::DependOnPretenureMode(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CreateLiteralParameters::feedback(), v8::internal::compiler::JSHeapBroker::GetFeedbackForArrayOrObjectLiteral(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::compiler::kMaxFastLiteralDepth, v8::internal::compiler::kMaxFastLiteralProperties, v8::internal::compiler::Node::opcode(), v8::internal::compiler::JSCreateLiteralOpNode::Parameters(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), TryAllocateFastLiteral(), v8::internal::compiler::SingleValueFeedback< T, K >::value(), and v8::internal::value.
Referenced by Reduce().
ReduceJSCreateLiteralRegExp()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateLiteralRegExp (Node * node) [private]
Definition at line 1223 of file js-create-lowering.cc.
                                                                  {
  JSCreateLiteralRegExpNode n(node);
  CreateLiteralParameters const& p = n.Parameters();
  Effect effect = n.effect();
  Control control = n.control();
  ProcessedFeedback const& feedback =
      broker()->GetFeedbackForRegExpLiteral(p.feedback());
  if (!feedback.IsInsufficient()) {
    RegExpBoilerplateDescriptionRef literal =
        feedback.AsRegExpLiteral().value();
    Node* value = effect = AllocateLiteralRegExp(effect, control, literal);
    ReplaceWithValue(node, value, effect, control);
    return Replace(value);
  }
  return NoChange();
}
References AllocateLiteralRegExp(), v8::internal::compiler::ProcessedFeedback::AsRegExpLiteral(), broker(), v8::internal::compiler::JSNodeWrapperBase::control(), v8::internal::compiler::JSNodeWrapperBase::effect(), v8::internal::compiler::CreateLiteralParameters::feedback(), v8::internal::compiler::JSHeapBroker::GetFeedbackForRegExpLiteral(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::compiler::JSCreateLiteralOpNode::Parameters(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::SingleValueFeedback< T, K >::value(), and v8::internal::value.
Referenced by Reduce().
ReduceJSCreateObject()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateObject (Node * node) [private]
Definition at line 1394 of file js-create-lowering.cc.
                                                           {
  DCHECK_EQ(IrOpcode::kJSCreateObject, node->opcode());
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* prototype = NodeProperties::GetValueInput(node, 0);
  Type prototype_type = NodeProperties::GetType(prototype);
  if (!prototype_type.IsHeapConstant()) return NoChange();
  HeapObjectRef prototype_const = prototype_type.AsHeapConstant()->Ref();
  auto maybe_instance_map = GetObjectCreateMap(broker(), prototype_const);
  if (!maybe_instance_map) return NoChange();
  MapRef instance_map = maybe_instance_map.value();
  Node* properties = jsgraph()->EmptyFixedArrayConstant();
  if (instance_map.is_dictionary_map()) {
    DCHECK_EQ(prototype_const.map(broker()).oddball_type(broker()),
              OddballType::kNull);
    // Allocate an empty NameDictionary as backing store for the properties.
    MapRef map = broker()->name_dictionary_map();
    int capacity =
        NameDictionary::ComputeCapacity(NameDictionary::kInitialCapacity);
    DCHECK(base::bits::IsPowerOfTwo(capacity));
    int length = NameDictionary::EntryToIndex(InternalIndex(capacity));
    int size = NameDictionary::SizeFor(length);
    AllocationBuilder a(jsgraph(), broker(), effect, control);
    a.Allocate(size, AllocationType::kYoung, Type::Any());
    a.Store(AccessBuilder::ForMap(), map);
    // Initialize FixedArray fields.
    a.Store(AccessBuilder::ForFixedArrayLength(),
            jsgraph()->SmiConstant(length));
    // Initialize HashTable fields.
    a.Store(AccessBuilder::ForHashTableBaseNumberOfElements(),
            jsgraph()->SmiConstant(0));
    a.Store(AccessBuilder::ForHashTableBaseNumberOfDeletedElement(),
            jsgraph()->SmiConstant(0));
    a.Store(AccessBuilder::ForHashTableBaseCapacity(),
            jsgraph()->SmiConstant(capacity));
    // Initialize Dictionary fields.
    a.Store(AccessBuilder::ForDictionaryNextEnumerationIndex(),
            jsgraph()->SmiConstant(PropertyDetails::kInitialIndex));
    a.Store(AccessBuilder::ForDictionaryObjectHashIndex(),
            jsgraph()->SmiConstant(PropertyArray::kNoHashSentinel));
    // Initialize NameDictionary fields.
    a.Store(AccessBuilder::ForNameDictionaryFlagsIndex(),
            jsgraph()->SmiConstant(NameDictionary::kFlagsDefault));
    // Initialize the Properties fields.
    Node* undefined = jsgraph()->UndefinedConstant();
    static_assert(NameDictionary::kElementsStartIndex ==
                  NameDictionary::kFlagsIndex + 1);
    for (int index = NameDictionary::kElementsStartIndex; index < length;
         index++) {
      a.Store(AccessBuilder::ForFixedArraySlot(index, kNoWriteBarrier),
              undefined);
    }
    properties = effect = a.Finish();
  }
  int const instance_size = instance_map.instance_size();
  if (instance_size > kMaxRegularHeapObjectSize) return NoChange();
  CHECK(!instance_map.IsInobjectSlackTrackingInProgress());
  // Emit code to allocate the JSObject instance for the given
  // {instance_map}.
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.Allocate(instance_size, AllocationType::kYoung, Type::Any());
  a.Store(AccessBuilder::ForMap(), instance_map);
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHash(), properties);
  a.Store(AccessBuilder::ForJSObjectElements(),
          jsgraph()->EmptyFixedArrayConstant());
  // Initialize Object fields.
  Node* undefined = jsgraph()->UndefinedConstant();
  for (int offset = JSObject::kHeaderSize; offset < instance_size;
       offset += kTaggedSize) {
    a.Store(AccessBuilder::ForJSObjectOffset(offset, kNoWriteBarrier),
            undefined);
  }
  Node* value = effect = a.Finish();
  ReplaceWithValue(node, value, effect, control);
  return Replace(value);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::Type::AsHeapConstant(), broker(), CHECK, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::AccessBuilder::ForDictionaryNextEnumerationIndex(), v8::internal::compiler::AccessBuilder::ForDictionaryObjectHashIndex(), v8::internal::compiler::AccessBuilder::ForFixedArrayLength(), v8::internal::compiler::AccessBuilder::ForFixedArraySlot(), v8::internal::compiler::AccessBuilder::ForHashTableBaseCapacity(), v8::internal::compiler::AccessBuilder::ForHashTableBaseNumberOfDeletedElement(), v8::internal::compiler::AccessBuilder::ForHashTableBaseNumberOfElements(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectOffset(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHash(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::AccessBuilder::ForNameDictionaryFlagsIndex(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::anonymous_namespace{js-create-lowering.cc}::GetObjectCreateMap(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::index, v8::internal::compiler::MapRef::instance_size(), v8::internal::compiler::MapRef::is_dictionary_map(), v8::internal::compiler::Type::IsHeapConstant(), v8::internal::compiler::MapRef::IsInobjectSlackTrackingInProgress(), v8::base::bits::IsPowerOfTwo(), jsgraph(), v8::internal::NameDictionary::kFlagsDefault, v8::internal::NameDictionary::kFlagsIndex, v8::internal::NameDictionary::kInitialCapacity, v8::internal::PropertyDetails::kInitialIndex, v8::internal::kMaxRegularHeapObjectSize, v8::internal::PropertyArray::kNoHashSentinel, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kNull, v8::internal::kTaggedSize, v8::internal::kYoung, v8::internal::length, v8::internal::compiler::HeapObjectRef::map(), v8::internal::compiler::Node::opcode(), v8::internal::prototype, v8::internal::compiler::HeapConstantType::Ref(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), size(), v8::internal::compiler::AllocationBuilder::Store(), v8::internal::undefined, and v8::internal::value.
Referenced by Reduce().
ReduceJSCreatePromise()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreatePromise (Node * node) [private]
Definition at line 1113 of file js-create-lowering.cc.
                                                            {
  DCHECK_EQ(IrOpcode::kJSCreatePromise, node->opcode());
  Node* effect = NodeProperties::GetEffectInput(node);
  MapRef promise_map =
      native_context().promise_function(broker()).initial_map(broker());
  AllocationBuilder a(jsgraph(), broker(), effect, graph()->start());
  a.Allocate(promise_map.instance_size());
  a.Store(AccessBuilder::ForMap(), promise_map);
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectOffset(JSPromise::kReactionsOrResultOffset),
          jsgraph()->ZeroConstant());
  static_assert(v8::Promise::kPending == 0);
  a.Store(AccessBuilder::ForJSObjectOffset(JSPromise::kFlagsOffset),
          jsgraph()->ZeroConstant());
  static_assert(JSPromise::kHeaderSize == 5 * kTaggedSize);
  for (int offset = JSPromise::kHeaderSize;
       offset < JSPromise::kSizeWithEmbedderFields; offset += kTaggedSize) {
    a.Store(AccessBuilder::ForJSObjectOffset(offset),
            jsgraph()->ZeroConstant());
  }
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), broker(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectOffset(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetEffectInput(), graph(), v8::internal::compiler::MapRef::instance_size(), jsgraph(), v8::Promise::kPending, v8::internal::JSPromise::kSizeWithEmbedderFields, v8::internal::kTaggedSize, native_context(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::AllocationBuilder::Store().
Referenced by Reduce().
ReduceJSCreateStringIterator()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringIterator (Node * node) [private]
Definition at line 1060 of file js-create-lowering.cc.
                                                                   {
  DCHECK_EQ(IrOpcode::kJSCreateStringIterator, node->opcode());
  Node* string = NodeProperties::GetValueInput(node, 0);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* map = jsgraph()->ConstantNoHole(
      native_context().initial_string_iterator_map(broker()), broker());
  // Allocate new iterator and attach the iterator to this string.
  AllocationBuilder a(jsgraph(), broker(), effect, graph()->start());
  a.Allocate(JSStringIterator::kHeaderSize, AllocationType::kYoung,
             Type::OtherObject());
  a.Store(AccessBuilder::ForMap(), map);
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSStringIteratorString(), string);
  a.Store(AccessBuilder::ForJSStringIteratorIndex(), jsgraph()->SmiConstant(0));
  static_assert(JSIteratorResult::kSize == 5 * kTaggedSize);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForJSStringIteratorIndex(), v8::internal::compiler::AccessBuilder::ForJSStringIteratorString(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), jsgraph(), v8::internal::kTaggedSize, v8::internal::kYoung, native_context(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::AllocationBuilder::Store().
Referenced by Reduce().
ReduceJSCreateStringWrapper()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateStringWrapper (Node * node) [private]
Definition at line 1477 of file js-create-lowering.cc.
                                                                  {
  DCHECK_EQ(IrOpcode::kJSCreateStringWrapper, node->opcode());
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* primitive_value = NodeProperties::GetValueInput(node, 0);
  MapRef map = native_context().string_function(broker()).initial_map(broker());
  DCHECK_EQ(map.instance_size(), JSPrimitiveWrapper::kHeaderSize);
  CHECK(!map.IsInobjectSlackTrackingInProgress());
  // Emit code to allocate the JSPrimitiveWrapper instance for the given {map}.
  AllocationBuilder a(jsgraph(), broker(), effect, graph()->start());
  a.Allocate(JSPrimitiveWrapper::kHeaderSize, AllocationType::kYoung,
             Type::StringWrapper());
  a.Store(AccessBuilder::ForMap(), map);
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHash(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSPrimitiveWrapperValue(), primitive_value);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), broker(), CHECK, DCHECK_EQ, v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHash(), v8::internal::compiler::AccessBuilder::ForJSPrimitiveWrapperValue(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::MapRef::instance_size(), v8::internal::compiler::MapRef::IsInobjectSlackTrackingInProgress(), jsgraph(), v8::internal::kYoung, native_context(), v8::internal::compiler::Node::opcode(), and v8::internal::compiler::AllocationBuilder::Store().
Referenced by Reduce().
ReduceJSCreateWithContext()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSCreateWithContext (Node * node) [private]
Definition at line 1300 of file js-create-lowering.cc.
                                                                {
  DCHECK_EQ(IrOpcode::kJSCreateWithContext, node->opcode());
  ScopeInfoRef scope_info = ScopeInfoOf(node->op());
  Node* extension = NodeProperties::GetValueInput(node, 0);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  Node* context = NodeProperties::GetContextInput(node);
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  static_assert(Context::MIN_CONTEXT_EXTENDED_SLOTS ==
                3); // Ensure fully covered.
  a.AllocateContext(Context::MIN_CONTEXT_EXTENDED_SLOTS,
                    native_context().with_context_map(broker()));
  a.Store(AccessBuilder::ForContextSlot(Context::SCOPE_INFO_INDEX), scope_info);
  a.Store(AccessBuilder::ForContextSlot(Context::PREVIOUS_INDEX), context);
  a.Store(AccessBuilder::ForContextSlot(Context::EXTENSION_INDEX), extension);
  RelaxControls(node);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::AllocateContext(), broker(), DCHECK_EQ, v8::internal::Context::EXTENSION_INDEX, v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForContextSlot(), v8::internal::compiler::NodeProperties::GetContextInput(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), jsgraph(), v8::internal::Context::MIN_CONTEXT_EXTENDED_SLOTS, native_context(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::Context::PREVIOUS_INDEX, v8::internal::Context::SCOPE_INFO_INDEX, v8::internal::compiler::ScopeInfoOf(), and v8::internal::compiler::AllocationBuilder::Store().
Referenced by Reduce().
ReduceJSGetTemplateObject()
Reduction v8::internal::compiler::JSCreateLowering::ReduceJSGetTemplateObject (Node * node) [private]
Definition at line 1240 of file js-create-lowering.cc.
                                                                {
  JSGetTemplateObjectNode n(node);
  GetTemplateObjectParameters const& parameters = n.Parameters();
  const ProcessedFeedback& feedback =
      broker()->GetFeedbackForTemplateObject(parameters.feedback());
  // TODO(v8:7790): Consider not generating JSGetTemplateObject operator
  // in the BytecodeGraphBuilder in the first place, if template_object is not
  // available.
  if (feedback.IsInsufficient()) return NoChange();
  JSArrayRef template_object = feedback.AsTemplateObject().value();
  Node* value = jsgraph()->ConstantNoHole(template_object, broker());
  ReplaceWithValue(node, value);
  return Replace(value);
}
References v8::internal::compiler::ProcessedFeedback::AsTemplateObject(), broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::compiler::GetTemplateObjectParameters::feedback(), v8::internal::compiler::JSHeapBroker::GetFeedbackForTemplateObject(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), jsgraph(), v8::internal::compiler::JSGetTemplateObjectNode::Parameters(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::SingleValueFeedback< T, K >::value(), and v8::internal::value.
Referenced by Reduce().
ReduceNewArray() [1/3]
Reduction v8::internal::compiler::JSCreateLowering::ReduceNewArray (Node * node, Node * length, int capacity, MapRef initial_map, ElementsKind elements_kind, AllocationType allocation, const SlackTrackingPrediction & slack_tracking_prediction, const FeedbackSource & feedback) [private]
Definition at line 529 of file js-create-lowering.cc.
                                    {
  DCHECK(node->opcode() == IrOpcode::kJSCreateArray ||
         node->opcode() == IrOpcode::kJSCreateEmptyLiteralArray);
  DCHECK(NodeProperties::GetType(length).Is(Type::Number()));
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  // Determine the appropriate elements kind.
  if (NodeProperties::GetType(length).Max() > 0.0) {
    elements_kind = GetHoleyElementsKind(elements_kind);
  }
  OptionalMapRef maybe_initial_map =
      initial_map.AsElementsKind(broker(), elements_kind);
  if (!maybe_initial_map.has_value()) return NoChange();
  initial_map = maybe_initial_map.value();
  DCHECK(IsFastElementsKind(elements_kind));
  // Setup elements and properties.
  Node* elements;
  if (capacity == 0) {
    elements = jsgraph()->EmptyFixedArrayConstant();
  } else {
    elements = effect =
        AllocateElements(effect, control, elements_kind, capacity, allocation);
  }
  // Perform the allocation of the actual JSArray object.
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.Allocate(slack_tracking_prediction.instance_size(), allocation);
  a.Store(AccessBuilder::ForMap(), initial_map);
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(), elements);
  a.Store(AccessBuilder::ForJSArrayLength(elements_kind), length);
  for (int i = 0; i < slack_tracking_prediction.inobject_property_count();
       ++i) {
    a.Store(AccessBuilder::ForJSObjectInObjectProperty(initial_map, i),
            jsgraph()->UndefinedConstant());
  }
  RelaxControls(node);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), AllocateElements(), broker(), v8::internal::DCHECK(), v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectInObjectProperty(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::GetHoleyElementsKind(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::initial_map, v8::internal::compiler::SlackTrackingPrediction::inobject_property_count(), v8::internal::compiler::SlackTrackingPrediction::instance_size(), v8::internal::Is(), v8::internal::IsFastElementsKind(), jsgraph(), v8::internal::length, v8::internal::compiler::Node::opcode(), v8::internal::compiler::AllocationBuilder::Store(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
ReduceNewArray() [2/3]
Reduction v8::internal::compiler::JSCreateLowering::ReduceNewArray (Node * node, Node * length, MapRef initial_map, ElementsKind elements_kind, AllocationType allocation, const SlackTrackingPrediction & slack_tracking_prediction, const FeedbackSource & feedback) [private]
Definition at line 472 of file js-create-lowering.cc.
                                    {
  DCHECK_EQ(IrOpcode::kJSCreateArray, node->opcode());
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  // Constructing an Array via new Array(N) where N is an unsigned
  // integer, always creates a holey backing store.
  OptionalMapRef maybe_initial_map =
      initial_map.AsElementsKind(broker(), GetHoleyElementsKind(elements_kind));
  if (!maybe_initial_map.has_value()) return NoChange();
  initial_map = maybe_initial_map.value();
  // Because CheckBounds performs implicit conversion from string to number, an
  // additional CheckNumber is required to behave correctly for calls with a
  // single string argument.
  length = effect = graph()->NewNode(simplified()->CheckNumber(feedback),
                                     length, effect, control);
  // Check that the {limit} is an unsigned integer in the valid range.
  // This has to be kept in sync with src/runtime/runtime-array.cc,
  // where this limit is protected.
  length = effect = graph()->NewNode(
      simplified()->CheckBounds(feedback), length,
      jsgraph()->ConstantNoHole(JSArray::kInitialMaxFastElementArray), effect,
      control);
  // Construct elements and properties for the resulting JSArray.
  Node* elements = effect =
      graph()->NewNode(IsDoubleElementsKind(initial_map.elements_kind())
                           ? simplified()->NewDoubleElements(allocation)
                           : simplified()->NewSmiOrObjectElements(allocation),
                       length, effect, control);
  // Perform the allocation of the actual JSArray object.
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.Allocate(slack_tracking_prediction.instance_size(), allocation);
  a.Store(AccessBuilder::ForMap(), initial_map);
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(), elements);
  a.Store(AccessBuilder::ForJSArrayLength(initial_map.elements_kind()), length);
  for (int i = 0; i < slack_tracking_prediction.inobject_property_count();
       ++i) {
    a.Store(AccessBuilder::ForJSObjectInObjectProperty(initial_map, i),
            jsgraph()->UndefinedConstant());
  }
  RelaxControls(node);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), broker(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectInObjectProperty(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::GetHoleyElementsKind(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::initial_map, v8::internal::compiler::SlackTrackingPrediction::inobject_property_count(), v8::internal::compiler::SlackTrackingPrediction::instance_size(), v8::internal::IsDoubleElementsKind(), jsgraph(), v8::internal::JSArray::kInitialMaxFastElementArray, v8::internal::length, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::opcode(), simplified(), v8::internal::compiler::AllocationBuilder::Store(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by ReduceJSCreateArray(), and ReduceJSCreateEmptyLiteralArray().
ReduceNewArray() [3/3]
Reduction v8::internal::compiler::JSCreateLowering::ReduceNewArray (Node * node, std::vector< Node * > values, MapRef initial_map, ElementsKind elements_kind, AllocationType allocation, const SlackTrackingPrediction & slack_tracking_prediction, const FeedbackSource & feedback) [private]
Definition at line 579 of file js-create-lowering.cc.
                                    {
  DCHECK_EQ(IrOpcode::kJSCreateArray, node->opcode());
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  // Determine the appropriate elements kind.
  DCHECK(IsFastElementsKind(elements_kind));
  OptionalMapRef maybe_initial_map =
      initial_map.AsElementsKind(broker(), elements_kind);
  if (!maybe_initial_map.has_value()) return NoChange();
  initial_map = maybe_initial_map.value();
  // Check {values} based on the {elements_kind}. These checks are guarded
  // by the {elements_kind} feedback on the {site}, so it's safe to just
  // deoptimize in this case.
  if (IsSmiElementsKind(elements_kind)) {
    for (auto& value : values) {
      if (!NodeProperties::GetType(value).Is(Type::SignedSmall())) {
        value = effect = graph()->NewNode(simplified()->CheckSmi(feedback),
                                          value, effect, control);
      }
    }
  } else if (IsDoubleElementsKind(elements_kind)) {
    for (auto& value : values) {
      if (!NodeProperties::GetType(value).Is(Type::Number())) {
        value = effect = graph()->NewNode(simplified()->CheckNumber(feedback),
                                          value, effect, control);
      }
      // Make sure we do not store signaling NaNs into double arrays.
      value = graph()->NewNode(simplified()->NumberSilenceNaN(), value);
    }
  }
  // Setup elements, properties and length.
  Node* elements = effect =
      AllocateElements(effect, control, elements_kind, values, allocation);
  Node* length = jsgraph()->ConstantNoHole(static_cast<int>(values.size()));
  // Perform the allocation of the actual JSArray object.
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.Allocate(slack_tracking_prediction.instance_size(), allocation);
  a.Store(AccessBuilder::ForMap(), initial_map);
  a.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
          jsgraph()->EmptyFixedArrayConstant());
  a.Store(AccessBuilder::ForJSObjectElements(), elements);
  a.Store(AccessBuilder::ForJSArrayLength(elements_kind), length);
  for (int i = 0; i < slack_tracking_prediction.inobject_property_count();
       ++i) {
    a.Store(AccessBuilder::ForJSObjectInObjectProperty(initial_map, i),
            jsgraph()->UndefinedConstant());
  }
  RelaxControls(node);
  a.FinishAndChange(node);
  return Changed(node);
}
References v8::internal::compiler::AllocationBuilder::Allocate(), AllocateElements(), broker(), v8::internal::compiler::JSGraph::ConstantNoHole(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::AllocationBuilder::FinishAndChange(), v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectInObjectProperty(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::initial_map, v8::internal::compiler::SlackTrackingPrediction::inobject_property_count(), v8::internal::compiler::SlackTrackingPrediction::instance_size(), v8::internal::Is(), v8::internal::IsDoubleElementsKind(), v8::internal::IsFastElementsKind(), v8::internal::IsSmiElementsKind(), jsgraph(), v8::internal::length, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Type::SignedSmall(), simplified(), v8::internal::compiler::AllocationBuilder::Store(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::value.
reducer_name()
const char* v8::internal::compiler::JSCreateLowering::reducer_name () const [inline], [override]
Definition at line 47 of file js-create-lowering.h.
{ return "JSCreateLowering"; }
simplified()
SimplifiedOperatorBuilder * v8::internal::compiler::JSCreateLowering::simplified () const [private]
Definition at line 2038 of file js-create-lowering.cc.
                                                              {
  return jsgraph()->simplified();
}
References jsgraph(), and v8::internal::compiler::JSGraph::simplified().
Referenced by ReduceJSCreateArguments(), ReduceJSCreateClosure(), ReduceJSCreateCollectionIterator(), ReduceNewArray(), and TryAllocateAliasedArguments().
TryAllocateAliasedArguments() [1/2]
Node * v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments (Node * effect, Node * control, FrameState frame_state, Node * context, SharedFunctionInfoRef shared, bool * has_aliased_arguments) [private]
Definition at line 1562 of file js-create-lowering.cc.
                                                               {
  FrameStateInfo state_info = frame_state.frame_state_info();
  int argument_count = state_info.parameter_count_without_receiver();
  if (argument_count == 0) return jsgraph()->EmptyFixedArrayConstant();
  // If there is no aliasing, the arguments object elements are not special in
  // any way, we can just return an unmapped backing store instead.
  int parameter_count =
      shared.internal_formal_parameter_count_without_receiver_deprecated();
  if (parameter_count == 0) {
    return TryAllocateArguments(effect, control, frame_state);
  }
  // Calculate number of argument values being aliased/mapped.
  int mapped_count = std::min(argument_count, parameter_count);
  *has_aliased_arguments = true;
  MapRef sloppy_arguments_elements_map =
      broker()->sloppy_arguments_elements_map();
  AllocationBuilder ab(jsgraph(), broker(), effect, control);
  if (!ab.CanAllocateSloppyArgumentElements(mapped_count,
                                            sloppy_arguments_elements_map)) {
    return nullptr;
  }
  MapRef fixed_array_map = broker()->fixed_array_map();
  if (!ab.CanAllocateArray(argument_count, fixed_array_map)) {
    return nullptr;
  }
  // Prepare an iterator over argument values recorded in the frame state.
  Node* const parameters = frame_state.parameters();
  StateValuesAccess parameters_access(parameters);
  auto parameters_it =
      parameters_access.begin_without_receiver_and_skip(mapped_count);
  // The unmapped argument values recorded in the frame state are stored yet
  // another indirection away and then linked into the parameter map below,
  // whereas mapped argument values are replaced with a hole instead.
  ab.AllocateArray(argument_count, fixed_array_map);
  for (int i = 0; i < mapped_count; ++i) {
    ab.Store(AccessBuilder::ForFixedArrayElement(),
             jsgraph()->ConstantNoHole(i), jsgraph()->TheHoleConstant());
  }
  for (int i = mapped_count; i < argument_count; ++i, ++parameters_it) {
    DCHECK_NOT_NULL(parameters_it.node());
    ab.Store(AccessBuilder::ForFixedArrayElement(),
             jsgraph()->ConstantNoHole(i), parameters_it.node());
  }
  Node* arguments = ab.Finish();
  // Actually allocate the backing store.
  AllocationBuilder a(jsgraph(), broker(), arguments, control);
  a.AllocateSloppyArgumentElements(mapped_count, sloppy_arguments_elements_map);
  a.Store(AccessBuilder::ForSloppyArgumentsElementsContext(), context);
  a.Store(AccessBuilder::ForSloppyArgumentsElementsArguments(), arguments);
  for (int i = 0; i < mapped_count; ++i) {
    int idx = shared.context_parameters_start() + parameter_count - 1 - i;
    a.Store(AccessBuilder::ForSloppyArgumentsElementsMappedEntry(),
            jsgraph()->ConstantNoHole(i), jsgraph()->ConstantNoHole(idx));
  }
  return a.Finish();
}
References v8::internal::compiler::AllocationBuilder::AllocateArray(), v8::internal::compiler::AllocationBuilder::AllocateSloppyArgumentElements(), v8::internal::compiler::StateValuesAccess::begin_without_receiver_and_skip(), broker(), v8::internal::compiler::AllocationBuilder::CanAllocateArray(), v8::internal::compiler::AllocationBuilder::CanAllocateSloppyArgumentElements(), v8::internal::compiler::SharedFunctionInfoRef::context_parameters_start(), DCHECK_NOT_NULL, v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsArguments(), v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsContext(), v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsMappedEntry(), v8::internal::compiler::FrameState::frame_state_info(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::SharedFunctionInfoRef::internal_formal_parameter_count_without_receiver_deprecated(), jsgraph(), v8::internal::compiler::FrameStateInfo::parameter_count_without_receiver(), v8::internal::compiler::FrameState::parameters(), v8::internal::compiler::AllocationBuilder::Store(), and TryAllocateArguments().
Referenced by ReduceJSCreateArguments().
TryAllocateAliasedArguments() [2/2]
Node * v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments (Node * effect, Node * control, Node * context, Node * arguments_length, SharedFunctionInfoRef shared, bool * has_aliased_arguments) [private]
Definition at line 1633 of file js-create-lowering.cc.
                                                               {
  // If there is no aliasing, the arguments object elements are not
  // special in any way, we can just return an unmapped backing store.
  int parameter_count =
      shared.internal_formal_parameter_count_without_receiver_deprecated();
  if (parameter_count == 0) {
    return graph()->NewNode(
        simplified()->NewArgumentsElements(
            CreateArgumentsType::kUnmappedArguments, parameter_count),
        arguments_length, effect);
  }
  int mapped_count = parameter_count;
  MapRef sloppy_arguments_elements_map =
      broker()->sloppy_arguments_elements_map();
  {
    AllocationBuilder ab(jsgraph(), broker(), effect, control);
    if (!ab.CanAllocateSloppyArgumentElements(mapped_count,
                                              sloppy_arguments_elements_map)) {
      return nullptr;
    }
  }
  // From here on we are going to allocate a mapped (aka. aliased) elements
  // backing store. We do not statically know how many arguments exist, but
  // dynamically selecting the hole for some of the "mapped" elements allows
  // using a static shape for the parameter map.
  *has_aliased_arguments = true;
  // The unmapped argument values are stored yet another indirection away and
  // then linked into the parameter map below, whereas mapped argument values
  // (i.e. the first {mapped_count} elements) are replaced with a hole instead.
  Node* arguments = effect =
      graph()->NewNode(simplified()->NewArgumentsElements(
                           CreateArgumentsType::kMappedArguments, mapped_count),
                       arguments_length, effect);
  // Actually allocate the backing store.
  AllocationBuilder a(jsgraph(), broker(), effect, control);
  a.AllocateSloppyArgumentElements(mapped_count, sloppy_arguments_elements_map);
  a.Store(AccessBuilder::ForSloppyArgumentsElementsContext(), context);
  a.Store(AccessBuilder::ForSloppyArgumentsElementsArguments(), arguments);
  for (int i = 0; i < mapped_count; ++i) {
    int idx = shared.context_parameters_start() + parameter_count - 1 - i;
    Node* value = graph()->NewNode(
        common()->Select(MachineRepresentation::kTagged),
        graph()->NewNode(simplified()->NumberLessThan(),
                         jsgraph()->ConstantNoHole(i), arguments_length),
        jsgraph()->ConstantNoHole(idx), jsgraph()->TheHoleConstant());
    a.Store(AccessBuilder::ForSloppyArgumentsElementsMappedEntry(),
            jsgraph()->ConstantNoHole(i), value);
  }
  return a.Finish();
}
References v8::internal::compiler::AllocationBuilder::AllocateSloppyArgumentElements(), broker(), v8::internal::compiler::AllocationBuilder::CanAllocateSloppyArgumentElements(), common(), v8::internal::compiler::SharedFunctionInfoRef::context_parameters_start(), v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsArguments(), v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsContext(), v8::internal::compiler::AccessBuilder::ForSloppyArgumentsElementsMappedEntry(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::SharedFunctionInfoRef::internal_formal_parameter_count_without_receiver_deprecated(), jsgraph(), v8::internal::kMappedArguments, v8::internal::kTagged, v8::internal::kUnmappedArguments, v8::internal::compiler::TFGraph::NewNode(), simplified(), v8::internal::compiler::AllocationBuilder::Store(), and v8::internal::value.
TryAllocateArguments()
Node * v8::internal::compiler::JSCreateLowering::TryAllocateArguments (Node * effect, Node * control, FrameState frame_state) [private]
Definition at line 1502 of file js-create-lowering.cc.
                                                                     {
  FrameStateInfo state_info = frame_state.frame_state_info();
  int argument_count = state_info.parameter_count_without_receiver();
  if (argument_count == 0) return jsgraph()->EmptyFixedArrayConstant();
  // Prepare an iterator over argument values recorded in the frame state.
  Node* const parameters = frame_state.parameters();
  StateValuesAccess parameters_access(parameters);
  auto parameters_it = parameters_access.begin_without_receiver();
  // Actually allocate the backing store.
  MapRef fixed_array_map = broker()->fixed_array_map();
  AllocationBuilder ab(jsgraph(), broker(), effect, control);
  if (!ab.CanAllocateArray(argument_count, fixed_array_map)) {
    return nullptr;
  }
  ab.AllocateArray(argument_count, fixed_array_map);
  for (int i = 0; i < argument_count; ++i, ++parameters_it) {
    DCHECK_NOT_NULL(parameters_it.node());
    ab.Store(AccessBuilder::ForFixedArrayElement(),
             jsgraph()->ConstantNoHole(i), parameters_it.node());
  }
  return ab.Finish();
}
References v8::internal::compiler::AllocationBuilder::AllocateArray(), v8::internal::compiler::StateValuesAccess::begin_without_receiver(), broker(), v8::internal::compiler::AllocationBuilder::CanAllocateArray(), DCHECK_NOT_NULL, v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::FrameState::frame_state_info(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, jsgraph(), v8::internal::compiler::FrameStateInfo::parameter_count_without_receiver(), v8::internal::compiler::FrameState::parameters(), and v8::internal::compiler::AllocationBuilder::Store().
Referenced by ReduceJSCreateArguments(), and TryAllocateAliasedArguments().
TryAllocateFastLiteral()
std::optional< Node * > v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteral (Node * effect, Node * control, JSObjectRef boilerplate, AllocationType allocation, int max_depth, int * max_properties) [private]
Definition at line 1741 of file js-create-lowering.cc.
                                                                   {
  DCHECK_GE(max_depth, 0);
  DCHECK_GE(*max_properties, 0);
  if (max_depth == 0) return {};
  // Prevent concurrent migrations of boilerplate objects.
  JSHeapBroker::BoilerplateMigrationGuardIfNeeded boilerplate_access_guard(
      broker());
  // Now that we hold the migration lock, get the current map.
  MapRef boilerplate_map = boilerplate.map(broker());
  // Protect against concurrent changes to the boilerplate object by checking
  // for an identical value at the end of the compilation.
  dependencies()->DependOnObjectSlotValue(boilerplate, HeapObject::kMapOffset,
                                          boilerplate_map);
  {
    OptionalMapRef current_boilerplate_map =
        boilerplate.map_direct_read(broker());
    if (!current_boilerplate_map.has_value() ||
        !current_boilerplate_map->equals(boilerplate_map)) {
      return {};
    }
  }
  // Bail out if the boilerplate map has been deprecated. The map could of
  // course be deprecated at some point after the line below, but it's not a
  // correctness issue -- it only means the literal won't be created with the
  // most up to date map(s).
  if (boilerplate_map.is_deprecated()) return {};
  // We currently only support in-object properties.
  if (boilerplate.map(broker()).elements_kind() == DICTIONARY_ELEMENTS ||
      boilerplate.map(broker()).is_dictionary_map() ||
      !boilerplate.raw_properties_or_hash(broker()).has_value()) {
    return {};
  }
  {
    ObjectRef properties = *boilerplate.raw_properties_or_hash(broker());
    bool const empty = properties.IsSmi() ||
                       properties.equals(broker()->empty_fixed_array()) ||
                       properties.equals(broker()->empty_property_array());
    if (!empty) return {};
  }
  // Compute the in-object properties to store first (might have effects).
  ZoneVector<std::pair<FieldAccess, Node*>> inobject_fields(zone());
  inobject_fields.reserve(boilerplate_map.GetInObjectProperties());
  int const boilerplate_nof = boilerplate_map.NumberOfOwnDescriptors();
  for (InternalIndex i : InternalIndex::Range(boilerplate_nof)) {
    PropertyDetails const property_details =
        boilerplate_map.GetPropertyDetails(broker(), i);
    if (property_details.location() != PropertyLocation::kField) continue;
    DCHECK_EQ(PropertyKind::kData, property_details.kind());
    if ((*max_properties)-- == 0) return {};
    NameRef property_name = boilerplate_map.GetPropertyKey(broker(), i);
    FieldIndex index =
        FieldIndex::ForDetails(*boilerplate_map.object(), property_details);
    ConstFieldInfo const_field_info(boilerplate_map);
    FieldAccess access = {kTaggedBase,
                          index.offset(),
                          property_name.object(),
                          OptionalMapRef(),
                          Type::Any(),
                          MachineType::AnyTagged(),
                          kFullWriteBarrier,
                          "TryAllocateFastLiteral",
                          const_field_info};
    // Note: the use of RawInobjectPropertyAt (vs. the higher-level
    // GetOwnFastConstantDataProperty) here is necessary, since the underlying
    // value may be `uninitialized`, which the latter explicitly does not
    // support.
    OptionalObjectRef maybe_boilerplate_value =
        boilerplate.RawInobjectPropertyAt(broker(), index);
    if (!maybe_boilerplate_value.has_value()) return {};
    // Note: We don't need to take a compilation dependency verifying the value
    // of `boilerplate_value`, since boilerplate properties are constant after
    // initialization modulo map migration. We protect against concurrent map
    // migrations (other than elements kind transition, which don't affect us)
    // via the boilerplate_migration_access lock.
    ObjectRef boilerplate_value = maybe_boilerplate_value.value();
    // Uninitialized fields are marked through the `uninitialized_value` marker
    // (even for Smi representation!), or in the case of Double representation
    // through a HeapNumber containing the hole-NaN. Since Double-to-Tagged
    // representation changes are done in-place, we may even encounter these
    // HeapNumbers in Tagged representation.
    // Note that although we create nodes to write `uninitialized_value` into
    // the object, the field should be overwritten immediately with a real
    // value, and `uninitialized_value` should never be exposed to JS.
    ObjectRef uninitialized_marker = broker()->uninitialized_value();
    if (boilerplate_value.equals(uninitialized_marker) ||
        (boilerplate_value.IsHeapNumber() &&
         boilerplate_value.AsHeapNumber().value_as_bits() == kHoleNanInt64)) {
      access.const_field_info = ConstFieldInfo::None();
    }
    Node* value;
    if (boilerplate_value.IsJSObject()) {
      JSObjectRef boilerplate_object = boilerplate_value.AsJSObject();
      std::optional<Node*> maybe_value =
          TryAllocateFastLiteral(effect, control, boilerplate_object,
                                 allocation, max_depth - 1, max_properties);
      if (!maybe_value.has_value()) return {};
      value = effect = maybe_value.value();
    } else if (property_details.representation().IsDouble()) {
      double number = boilerplate_value.AsHeapNumber().value();
      // Allocate a mutable HeapNumber box and store the value into it.
      AllocationBuilder builder(jsgraph(), broker(), effect, control);
      builder.Allocate(sizeof(HeapNumber), allocation);
      builder.Store(AccessBuilder::ForMap(), broker()->heap_number_map());
      builder.Store(AccessBuilder::ForHeapNumberValue(),
                    jsgraph()->ConstantMaybeHole(number));
      value = effect = builder.Finish();
    } else {
      // It's fine to store the 'uninitialized' marker into a Smi field since
      // it will get overwritten anyways and the store's MachineType (AnyTagged)
      // is compatible with it.
      DCHECK_IMPLIES(property_details.representation().IsSmi() &&
                         !boilerplate_value.IsSmi(),
                     boilerplate_value.equals(uninitialized_marker));
      value = jsgraph()->ConstantMaybeHole(boilerplate_value, broker());
    }
    inobject_fields.push_back(std::make_pair(access, value));
  }
  // Fill slack at the end of the boilerplate object with filler maps.
  int const boilerplate_length = boilerplate_map.GetInObjectProperties();
  for (int index = static_cast<int>(inobject_fields.size());
       index < boilerplate_length; ++index) {
    DCHECK(!V8_MAP_PACKING_BOOL);
    // TODO(wenyuzhao): Fix incorrect MachineType when V8_MAP_PACKING is
    // enabled.
    FieldAccess access =
        AccessBuilder::ForJSObjectInObjectProperty(boilerplate_map, index);
    Node* value =
        jsgraph()->HeapConstantNoHole(factory()->one_pointer_filler_map());
    inobject_fields.push_back(std::make_pair(access, value));
  }
  // Setup the elements backing store.
  std::optional<Node*> maybe_elements = TryAllocateFastLiteralElements(
      effect, control, boilerplate, allocation, max_depth, max_properties);
  if (!maybe_elements.has_value()) return {};
  Node* elements = maybe_elements.value();
  if (elements->op()->EffectOutputCount() > 0) effect = elements;
  // Actually allocate and initialize the object.
  AllocationBuilder builder(jsgraph(), broker(), effect, control);
  builder.Allocate(boilerplate_map.instance_size(), allocation,
                   Type::For(boilerplate_map, broker()));
  builder.Store(AccessBuilder::ForMap(), boilerplate_map);
  builder.Store(AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(),
                jsgraph()->EmptyFixedArrayConstant());
  builder.Store(AccessBuilder::ForJSObjectElements(), elements);
  if (boilerplate.IsJSArray()) {
    JSArrayRef boilerplate_array = boilerplate.AsJSArray();
    builder.Store(AccessBuilder::ForJSArrayLength(
                      boilerplate_array.map(broker()).elements_kind()),
                  boilerplate_array.GetBoilerplateLength(broker()));
  }
  for (auto const& inobject_field : inobject_fields) {
    builder.Store(inobject_field.first, inobject_field.second);
  }
  return builder.Finish();
}
References v8::internal::compiler::AllocationBuilder::Allocate(), v8::internal::compiler::turboshaft::Type::Any(), v8::internal::MachineType::AnyTagged(), broker(), v8::internal::compiler::FieldAccess::const_field_info, v8::internal::compiler::JSGraph::ConstantMaybeHole(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_IMPLIES, dependencies(), v8::internal::compiler::CompilationDependencies::DependOnObjectSlotValue(), v8::internal::DICTIONARY_ELEMENTS, v8::internal::compiler::Operator::EffectOutputCount(), factory(), v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::Type::For(), v8::internal::FieldIndex::ForDetails(), v8::internal::compiler::AccessBuilder::ForHeapNumberValue(), v8::internal::compiler::AccessBuilder::ForJSArrayLength(), v8::internal::compiler::AccessBuilder::ForJSObjectElements(), v8::internal::compiler::AccessBuilder::ForJSObjectInObjectProperty(), v8::internal::compiler::AccessBuilder::ForJSObjectPropertiesOrHashKnownPointer(), v8::internal::compiler::AccessBuilder::ForMap(), v8::internal::compiler::JSArrayRef::GetBoilerplateLength(), v8::internal::compiler::MapRef::GetInObjectProperties(), v8::internal::compiler::MapRef::GetPropertyDetails(), v8::internal::compiler::MapRef::GetPropertyKey(), v8::internal::compiler::JSGraph::HeapConstantNoHole(), v8::internal::index, v8::internal::compiler::MapRef::instance_size(), v8::internal::compiler::MapRef::is_deprecated(), v8::internal::Representation::IsDouble(), v8::internal::Representation::IsSmi(), jsgraph(), v8::internal::kData, v8::internal::kField, v8::internal::compiler::kFullWriteBarrier, v8::internal::kHoleNanInt64, v8::internal::PropertyDetails::kind(), v8::internal::HeapObject::kMapOffset, v8::internal::compiler::kTaggedBase, v8::internal::PropertyDetails::location(), v8::internal::compiler::HeapObjectRef::map(), v8::internal::compiler::HeapObjectRef::map_direct_read(), v8::internal::compiler::ConstFieldInfo::None(), v8::internal::compiler::MapRef::NumberOfOwnDescriptors(), v8::internal::compiler::NameRef::object(), v8::internal::compiler::MapRef::object(), v8::internal::compiler::Node::op(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::JSObjectRef::raw_properties_or_hash(), v8::internal::compiler::JSObjectRef::RawInobjectPropertyAt(), v8::internal::PropertyDetails::representation(), v8::internal::ZoneVector< T >::reserve(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::AllocationBuilder::Store(), TryAllocateFastLiteralElements(), V8_MAP_PACKING_BOOL, v8::internal::value, and zone().
Referenced by ReduceJSCreateLiteralArrayOrObject(), and TryAllocateFastLiteralElements().
TryAllocateFastLiteralElements()
std::optional< Node * > v8::internal::compiler::JSCreateLowering::TryAllocateFastLiteralElements (Node * effect, Node * control, JSObjectRef boilerplate, AllocationType allocation, int max_depth, int * max_properties) [private]
Definition at line 1913 of file js-create-lowering.cc.
                                                                   {
  DCHECK_GT(max_depth, 0);
  DCHECK_GE(*max_properties, 0);
  OptionalFixedArrayBaseRef maybe_boilerplate_elements =
      boilerplate.elements(broker(), kRelaxedLoad);
  if (!maybe_boilerplate_elements.has_value()) return {};
  FixedArrayBaseRef boilerplate_elements = maybe_boilerplate_elements.value();
  // Protect against concurrent changes to the boilerplate object by checking
  // for an identical value at the end of the compilation.
  dependencies()->DependOnObjectSlotValue(
      boilerplate, JSObject::kElementsOffset, boilerplate_elements);
  // Empty or copy-on-write elements just store a constant.
  const uint32_t elements_length = boilerplate_elements.length();
  MapRef elements_map = boilerplate_elements.map(broker());
  // Protect against concurrent changes to the boilerplate object by checking
  // for an identical value at the end of the compilation.
  dependencies()->DependOnObjectSlotValue(boilerplate_elements,
                                          HeapObject::kMapOffset, elements_map);
  if (boilerplate_elements.length() == 0 ||
      elements_map.IsFixedCowArrayMap(broker())) {
    if (allocation == AllocationType::kOld &&
        !boilerplate.IsElementsTenured(boilerplate_elements)) {
      return {};
    }
    return jsgraph()->ConstantNoHole(boilerplate_elements, broker());
  }
  // Compute the elements to store first (might have effects).
  ZoneVector<Node*> elements_values(elements_length, zone());
  if (boilerplate_elements.IsFixedDoubleArray()) {
    uint32_t const size =
        FixedDoubleArray::SizeFor(boilerplate_elements.length());
    if (size > kMaxRegularHeapObjectSize) return {};
    FixedDoubleArrayRef elements = boilerplate_elements.AsFixedDoubleArray();
    for (uint32_t i = 0; i < elements_length; ++i) {
      Float64 value = elements.GetFromImmutableFixedDoubleArray(i);
      elements_values[i] = value.is_hole_nan()
                               ? jsgraph()->TheHoleConstant()
                               : jsgraph()->ConstantNoHole(value.get_scalar());
    }
  } else {
    FixedArrayRef elements = boilerplate_elements.AsFixedArray();
    for (uint32_t i = 0; i < elements_length; ++i) {
      if ((*max_properties)-- == 0) return {};
      OptionalObjectRef element_value = elements.TryGet(broker(), i);
      if (!element_value.has_value()) return {};
      if (element_value->IsJSObject()) {
        std::optional<Node*> object =
            TryAllocateFastLiteral(effect, control, element_value->AsJSObject(),
                                   allocation, max_depth - 1, max_properties);
        if (!object.has_value()) return {};
        elements_values[i] = effect = *object;
      } else {
        elements_values[i] =
            jsgraph()->ConstantMaybeHole(*element_value, broker());
      }
    }
  }
  // Allocate the backing store array and store the elements.
  AllocationBuilder ab(jsgraph(), broker(), effect, control);
  CHECK(ab.CanAllocateArray(elements_length, elements_map, allocation));
  ab.AllocateArray(elements_length, elements_map, allocation);
  ElementAccess const access = boilerplate_elements.IsFixedDoubleArray()
                                   ? AccessBuilder::ForFixedDoubleArrayElement()
                                   : AccessBuilder::ForFixedArrayElement();
  for (uint32_t i = 0; i < elements_length; ++i) {
    ab.Store(access, jsgraph()->ConstantNoHole(i), elements_values[i]);
  }
  return ab.Finish();
}
References v8::internal::compiler::AllocationBuilder::AllocateArray(), broker(), v8::internal::compiler::AllocationBuilder::CanAllocateArray(), CHECK, v8::internal::compiler::JSGraph::ConstantMaybeHole(), v8::internal::compiler::JSGraph::ConstantNoHole(), DCHECK_GE, DCHECK_GT, dependencies(), v8::internal::compiler::CompilationDependencies::DependOnObjectSlotValue(), v8::internal::compiler::JSObjectRef::elements(), v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::AccessBuilder::ForFixedDoubleArrayElement(), v8::internal::compiler::FixedDoubleArrayRef::GetFromImmutableFixedDoubleArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::JSObjectRef::IsElementsTenured(), v8::internal::compiler::MapRef::IsFixedCowArrayMap(), jsgraph(), v8::internal::HeapObject::kMapOffset, v8::internal::kMaxRegularHeapObjectSize, v8::internal::kOld, v8::kRelaxedLoad, v8::internal::compiler::FixedArrayBaseRef::length(), v8::internal::compiler::HeapObjectRef::map(), size(), v8::internal::PrimitiveArrayBase< FixedDoubleArray, FixedDoubleArrayShape >::SizeFor(), v8::internal::compiler::AllocationBuilder::Store(), TryAllocateFastLiteral(), v8::internal::compiler::FixedArrayRef::TryGet(), v8::internal::value, and zone().
Referenced by TryAllocateFastLiteral().
TryAllocateRestArguments()
Node * v8::internal::compiler::JSCreateLowering::TryAllocateRestArguments (Node * effect, Node * control, FrameState frame_state, int start_index) [private]
Definition at line 1530 of file js-create-lowering.cc.
                                                                  {
  FrameStateInfo state_info = frame_state.frame_state_info();
  int argument_count = state_info.parameter_count_without_receiver();
  int num_elements = std::max(0, argument_count - start_index);
  if (num_elements == 0) return jsgraph()->EmptyFixedArrayConstant();
  // Prepare an iterator over argument values recorded in the frame state.
  Node* const parameters = frame_state.parameters();
  StateValuesAccess parameters_access(parameters);
  auto parameters_it =
      parameters_access.begin_without_receiver_and_skip(start_index);
  // Actually allocate the backing store.
  MapRef fixed_array_map = broker()->fixed_array_map();
  AllocationBuilder ab(jsgraph(), broker(), effect, control);
  if (!ab.CanAllocateArray(num_elements, fixed_array_map)) {
    return nullptr;
  }
  ab.AllocateArray(num_elements, fixed_array_map);
  for (int i = 0; i < num_elements; ++i, ++parameters_it) {
    DCHECK_NOT_NULL(parameters_it.node());
    ab.Store(AccessBuilder::ForFixedArrayElement(),
             jsgraph()->ConstantNoHole(i), parameters_it.node());
  }
  return ab.Finish();
}
References v8::internal::compiler::AllocationBuilder::AllocateArray(), v8::internal::compiler::StateValuesAccess::begin_without_receiver_and_skip(), broker(), v8::internal::compiler::AllocationBuilder::CanAllocateArray(), DCHECK_NOT_NULL, v8::internal::compiler::AllocationBuilder::Finish(), v8::internal::compiler::AccessBuilder::ForFixedArrayElement(), v8::internal::compiler::FrameState::frame_state_info(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, jsgraph(), v8::internal::compiler::FrameStateInfo::parameter_count_without_receiver(), v8::internal::compiler::FrameState::parameters(), and v8::internal::compiler::AllocationBuilder::Store().
Referenced by ReduceJSCreateArguments().
zone()
Zone* v8::internal::compiler::JSCreateLowering::zone () const [inline], [private]
Definition at line 135 of file js-create-lowering.h.
{ return zone_; }
Referenced by TryAllocateFastLiteral(), and TryAllocateFastLiteralElements().
Member Data Documentation
broker_
JSHeapBroker* const v8::internal::compiler::JSCreateLowering::broker_ [private]
Definition at line 138 of file js-create-lowering.h.
jsgraph_
JSGraph* const v8::internal::compiler::JSCreateLowering::jsgraph_ [private]
Definition at line 137 of file js-create-lowering.h.
zone_
Zone* const v8::internal::compiler::JSCreateLowering::zone_ [private]
Definition at line 139 of file js-create-lowering.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/js-create-lowering.h
/mnt/V8SourceCode/src/compiler/js-create-lowering.cc