v8::internal::SeqTwoByteString Class Reference
#include <string.h>
Classes
class BodyDescriptor
Public Types
using Char = uint16_t
Public Member Functions
uint16_t Get (uint32_t index, const SharedStringAccessGuardIfNeeded &access_guard) const
void SeqTwoByteStringSet (uint32_t index, uint16_t value)
Address GetCharsAddress () const
base::uc16 * GetChars (const DisallowGarbageCollection &no_gc)
base::uc16 * GetChars (const DisallowGarbageCollection &no_gc, const SharedStringAccessGuardIfNeeded &access_guard)
DataAndPaddingSizes GetDataAndPaddingSizes () const
void clear_padding_destructively (uint32_t length)
int AllocatedSize () const
Static Public Member Functions
static constexpr int32_t DataSizeFor (int32_t length)
static constexpr int32_t SizeFor (int32_t length)
static bool IsCompatibleMap (Tagged< Map > map, ReadOnlyRoots roots)
Static Public Attributes
static const bool kHasOneByteEncoding = false
static const uint32_t kMaxCharsSize = kMaxLength * sizeof(Char)
Private Member Functions
FLEXIBLE_ARRAY_MEMBER (Char, chars)
Friends
struct OffsetsForDebug
class CodeStubAssembler
class ToDirectStringAssembler
class IntlBuiltinsAssembler
class StringBuiltinsAssembler
class StringFromCharCodeAssembler
class maglev::MaglevAssembler
class maglev::BuiltinStringFromCharCode
class compiler::AccessBuilder
class TorqueGeneratedSeqTwoByteStringAsserts
Additional Inherited Members
Detailed Description
Definition at line 936 of file string.h.
Member Typedef Documentation
Char
using v8::internal::SeqTwoByteString::Char = uint16_t
Definition at line 939 of file string.h.
Member Function Documentation
AllocatedSize()
int v8::internal::SeqTwoByteString::AllocatedSize () const [inline]
Definition at line 1373 of file string-inl.h.
                                                 {
  return SizeFor(length(kAcquireLoad));
}
References v8::kAcquireLoad, and v8::internal::String::length().
clear_padding_destructively()
void v8::internal::SeqTwoByteString::clear_padding_destructively (uint32_t length) [inline]
Definition at line 1849 of file string-inl.h.
                                                                  {
  // Ensure we are not killing the map word, which is already set at this point
  static_assert(SizeFor(0) >= kObjectAlignment + kTaggedSize);
  memset(reinterpret_cast<void*>(reinterpret_cast<char*>(this) +
                                 SizeFor(length) - kObjectAlignment),
         0, kObjectAlignment);
}
References v8::internal::kObjectAlignment, v8::internal::kTaggedSize, v8::internal::String::length(), and SizeFor().
DataSizeFor()
constexpr int32_t v8::internal::SeqTwoByteString::DataSizeFor (int32_t length) [inline], [static], [constexpr]
Definition at line 1354 of file string-inl.h.
                                                                        {
  return sizeof(SeqTwoByteString) + length * sizeof(Char);
}
References v8::internal::String::length().
Referenced by SizeFor().
FLEXIBLE_ARRAY_MEMBER()
v8::internal::SeqTwoByteString::FLEXIBLE_ARRAY_MEMBER (Char , chars) [private]
Get()
uint16_t v8::internal::SeqTwoByteString::Get (uint32_t index, const SharedStringAccessGuardIfNeeded & access_guard) const [inline]
Definition at line 1335 of file string-inl.h.
                                                                               {
  USE(access_guard);
  DCHECK(index >= 0 && index < length());
  return chars()[index];
}
References v8::internal::DCHECK(), v8::internal::index, v8::internal::String::length(), and USE.
GetChars() [1/2]
base::uc16 * v8::internal::SeqTwoByteString::GetChars (const DisallowGarbageCollection & no_gc) [inline]
Definition at line 1321 of file string-inl.h.
                                                                           {
  USE(no_gc);
  DCHECK(!SharedStringAccessGuardIfNeeded::IsNeeded(this));
  return chars();
}
References v8::internal::DCHECK(), v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and USE.
GetChars() [2/2]
base::uc16 * v8::internal::SeqTwoByteString::GetChars (const DisallowGarbageCollection & no_gc, const SharedStringAccessGuardIfNeeded & access_guard) [inline]
Definition at line 1327 of file string-inl.h.
                                                         {
  USE(no_gc);
  USE(access_guard);
  return chars();
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and USE.
GetCharsAddress()
Address v8::internal::SeqTwoByteString::GetCharsAddress () const [inline]
Definition at line 1317 of file string-inl.h.
                                                {
  return reinterpret_cast<Address>(&chars()[0]);
}
GetDataAndPaddingSizes()
SeqString::DataAndPaddingSizes v8::internal::SeqTwoByteString::GetDataAndPaddingSizes () const
Definition at line 1973 of file string.cc.
          {
  int data_size = sizeof(SeqTwoByteString) + length() * base::kUC16Size;
  int padding_size = SizeFor(length()) - data_size;
  return DataAndPaddingSizes{data_size, padding_size};
}
References v8::base::kUC16Size, and v8::internal::length.
IsCompatibleMap()
bool v8::internal::SeqTwoByteString::IsCompatibleMap (Tagged< Map > map, ReadOnlyRoots roots) [inline], [static]
Definition at line 1384 of file string-inl.h.
                                                                           {
  return map == roots.seq_two_byte_string_map() ||
         map == roots.shared_seq_two_byte_string_map();
}
References v8::internal::HeapObjectLayout::map().
SeqTwoByteStringSet()
void v8::internal::SeqTwoByteString::SeqTwoByteStringSet (uint32_t index, uint16_t value) [inline]
Definition at line 1342 of file string-inl.h.
                                                                         {
  DisallowGarbageCollection no_gc;
  DCHECK(index >= 0 && index < length());
  chars()[index] = value;
}
References v8::internal::DCHECK(), v8::internal::index, v8::internal::String::length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::value.
SizeFor()
constexpr int32_t v8::internal::SeqTwoByteString::SizeFor (int32_t length) [inline], [static], [constexpr]
Definition at line 1364 of file string-inl.h.
                                                                    {
  return OBJECT_POINTER_ALIGN(SeqTwoByteString::DataSizeFor(length));
}
References DataSizeFor(), v8::internal::String::length(), and OBJECT_POINTER_ALIGN.
Referenced by v8::internal::FactoryBase< Impl >::AllocateRawTwoByteInternalizedString(), v8::internal::CodeStubAssembler::AllocateSeqTwoByteString(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::AllocateSeqTwoByteString(), v8::internal::maglev::MaglevAssembler::AllocateTwoByteString(), clear_padding_destructively(), v8::internal::TranslatedValue::GetRawValue(), v8::internal::Serializer::ObjectSerializer::SerializeExternalStringAsSequentialString(), and v8::internal::HeapObject::SizeFromMap().
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 980 of file string.h.
compiler::AccessBuilder
friend class compiler::AccessBuilder [friend]
Definition at line 987 of file string.h.
IntlBuiltinsAssembler
friend class IntlBuiltinsAssembler [friend]
Definition at line 982 of file string.h.
maglev::BuiltinStringFromCharCode
friend class maglev::BuiltinStringFromCharCode [friend]
Definition at line 986 of file string.h.
maglev::MaglevAssembler
friend class maglev::MaglevAssembler [friend]
Definition at line 985 of file string.h.
OffsetsForDebug
friend struct OffsetsForDebug [friend]
Definition at line 979 of file string.h.
StringBuiltinsAssembler
friend class StringBuiltinsAssembler [friend]
Definition at line 983 of file string.h.
StringFromCharCodeAssembler
friend class StringFromCharCodeAssembler [friend]
Definition at line 984 of file string.h.
ToDirectStringAssembler
friend class ToDirectStringAssembler [friend]
Definition at line 981 of file string.h.
TorqueGeneratedSeqTwoByteStringAsserts
friend class TorqueGeneratedSeqTwoByteStringAsserts [friend]
Definition at line 988 of file string.h.
Member Data Documentation
kHasOneByteEncoding
const bool v8::internal::SeqTwoByteString::kHasOneByteEncoding = false [static]
Definition at line 938 of file string.h.
kMaxCharsSize
const uint32_t v8::internal::SeqTwoByteString::kMaxCharsSize = kMaxLength * sizeof(Char) [static]
Definition at line 969 of file string.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string.h
/mnt/V8SourceCode/src/objects/string-inl.h
/mnt/V8SourceCode/src/objects/string.cc