v8::internal::compiler::Edge Class Reference
#include <node.h>
Public Member Functions
Node * from () const
Node * to () const
int index () const
bool operator== (const Edge &other)
bool operator!= (const Edge &other)
void UpdateTo (Node *new_to)
Private Member Functions
Edge (Node::Use *use, ZoneNodePtr *input_ptr)
Private Attributes
Node::Use * use_
ZoneNodePtr * input_ptr_
Friends
class Node::UseEdges::iterator
class Node::InputEdges
class Node::InputEdges::iterator
Detailed Description
Definition at line 423 of file node.h.
Constructor & Destructor Documentation
Edge()
v8::internal::compiler::Edge::Edge (Node::Use * use, ZoneNodePtr * input_ptr) [inline], [private]
Definition at line 450 of file node.h.
      : use_(use), input_ptr_(input_ptr) {
    DCHECK_NOT_NULL(use);
    DCHECK_NOT_NULL(input_ptr);
    DCHECK_EQ(input_ptr, use->input_ptr());
  }
References DCHECK_EQ, DCHECK_NOT_NULL, and use().
Member Function Documentation
from()
Node* v8::internal::compiler::Edge::from () const [inline]
Definition at line 425 of file node.h.
{ return use_->from(); }
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::GetBlockForUse(), v8::internal::compiler::NodeProperties::IsContextEdge(), v8::internal::compiler::NodeProperties::IsControlEdge(), v8::internal::compiler::NodeProperties::IsEffectEdge(), v8::internal::compiler::NodeProperties::IsFrameStateEdge(), v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::IsStore(), v8::internal::compiler::NodeProperties::IsValueEdge(), and v8::internal::compiler::ControlEquivalence::RunUndirectedDFS().
index()
int v8::internal::compiler::Edge::index () const [inline]
Definition at line 427 of file node.h.
                    {
    int const index = use_->input_index();
    DCHECK_LT(index, use_->from()->InputCount());
    return index;
  }
References DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::compiler::MemoryOptimizer::AllocationTypeNeedsUpdateToOld(), v8::internal::compiler::ScheduleLateNodeVisitor::GetBlockForUse(), v8::internal::compiler::NodeProperties::IsInputRange(), and v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::IsStore().
operator!=()
bool v8::internal::compiler::Edge::operator!= (const Edge & other) [inline]
Definition at line 434 of file node.h.
{ return !(*this == other); }
operator==()
bool v8::internal::compiler::Edge::operator== (const Edge & other) [inline]
Definition at line 433 of file node.h.
{ return input_ptr_ == other.input_ptr_; }
References input_ptr_.
to()
Node* v8::internal::compiler::Edge::to () const [inline]
Definition at line 426 of file node.h.
{ return *input_ptr_; }
Referenced by v8::internal::compiler::ScheduleLateNodeVisitor::GetBlockForUse(), v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::IsEscapingAllocationWitness(), v8::internal::compiler::anonymous_namespace{late-escape-analysis.cc}::IsStore(), and v8::internal::compiler::ControlEquivalence::RunUndirectedDFS().
UpdateTo()
void v8::internal::compiler::Edge::UpdateTo (Node * new_to) [inline]
Definition at line 436 of file node.h.
                              {
    Node* old_to = *input_ptr_;
    if (old_to != new_to) {
      if (old_to) old_to->RemoveUse(use_);
      *input_ptr_ = new_to;
      if (new_to) new_to->AppendUse(use_);
    }
  }
References v8::internal::compiler::Node::AppendUse(), and v8::internal::compiler::Node::RemoveUse().
Friends And Related Function Documentation
Node::InputEdges
friend class Node::InputEdges [friend]
Definition at line 447 of file node.h.
Node::InputEdges::iterator
friend class Node::InputEdges::iterator [friend]
Definition at line 448 of file node.h.
Node::UseEdges::iterator
friend class Node::UseEdges::iterator [friend]
Definition at line 446 of file node.h.
Member Data Documentation
input_ptr_
ZoneNodePtr* v8::internal::compiler::Edge::input_ptr_ [private]
Definition at line 458 of file node.h.
Referenced by operator==().
use_
Node::Use* v8::internal::compiler::Edge::use_ [private]
Definition at line 457 of file node.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/node.h