v8::internal::EnumeratedKeyedLoadBaselineDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_PARAMETER_TYPES (MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::TaggedSigned(), MachineType::AnyTagged(), MachineType::TaggedSigned()) static const expr inline Register EnumIndexRegister()
Static Public Member Functions
static constexpr Register CacheTypeRegister ()
static constexpr Register SlotRegister ()
static constexpr auto registers ()
Additional Inherited Members
Detailed Description
Definition at line 1414 of file interface-descriptors.h.
Member Function Documentation
CacheTypeRegister()
constexpr Register v8::internal::EnumeratedKeyedLoadBaselineDescriptor::CacheTypeRegister () [inline], [static], [constexpr]
Definition at line 93 of file interface-descriptors-riscv-inl.h.
                                                                            {
  return a5;
}
Referenced by registers().
DEFINE_PARAMETER_TYPES()
v8::internal::EnumeratedKeyedLoadBaselineDescriptor::DEFINE_PARAMETER_TYPES (MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::TaggedSigned() , MachineType::AnyTagged() , MachineType::TaggedSigned()) const
registers()
constexpr auto v8::internal::EnumeratedKeyedLoadBaselineDescriptor::registers () [static], [constexpr]
Definition at line 649 of file interface-descriptors-inl.h.
                                                                {
  return RegisterArray(KeyedLoadBaselineDescriptor::ReceiverRegister(),
                       KeyedLoadBaselineDescriptor::NameRegister(),
                       EnumIndexRegister(), CacheTypeRegister(),
                       SlotRegister());
}
References CacheTypeRegister(), v8::internal::KeyedLoadBaselineDescriptor::NameRegister(), v8::internal::RegisterArray(), and SlotRegister().
SlotRegister()
constexpr Register v8::internal::EnumeratedKeyedLoadBaselineDescriptor::SlotRegister () [inline], [static], [constexpr]
Definition at line 98 of file interface-descriptors-riscv-inl.h.
                                                                       {
  return a2;
}
Referenced by registers().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h
/mnt/V8SourceCode/src/codegen/riscv/interface-descriptors-riscv-inl.h