v8::internal::wasm::WasmCodeManager Class Reference
#include <wasm-code-manager.h>
Public Member Functions
WasmCodeManager ()
WasmCodeManager (const WasmCodeManager &)=delete
WasmCodeManager & operator= (const WasmCodeManager &)=delete
~WasmCodeManager ()
NativeModule * LookupNativeModule (Address pc) const
WasmCode * LookupCode (Isolate *isolate, Address pc) const
std::pair< WasmCode *, SafepointEntry > LookupCodeAndSafepoint (Isolate *isolate, Address pc)
void FlushCodeLookupCache (Isolate *isolate)
size_t committed_code_space () const
Static Public Member Functions
static size_t EstimateLiftoffCodeSize (int body_size)
static size_t EstimateNativeModuleCodeSize (const WasmModule *)
static size_t EstimateNativeModuleCodeSize (int num_functions, int code_section_length)
static size_t EstimateNativeModuleMetaDataSize (const WasmModule *)
static bool HasMemoryProtectionKeySupport ()
static bool MemoryProtectionKeysEnabled ()
static bool MemoryProtectionKeyWritable ()
Private Member Functions
std::shared_ptr< NativeModule > NewNativeModule (Isolate *isolate, WasmEnabledFeatures enabled_features, WasmDetectedFeatures detected_features, CompileTimeImports compile_imports, size_t code_size_estimate, std::shared_ptr< const WasmModule > module)
V8_WARN_UNUSED_RESULT VirtualMemory TryAllocate (size_t size)
void Commit (base::AddressRegion)
void Decommit (base::AddressRegion)
void FreeNativeModule (base::Vector< VirtualMemory > owned_code, size_t committed_size)
void AssignRange (base::AddressRegion, NativeModule *)
WasmCode * LookupCode (Address pc) const
Private Attributes
const size_t max_committed_code_space_
std::atomic< size_t > total_committed_code_space_ {0}
std::atomic< size_t > critical_committed_code_space_
base::Mutex native_modules_mutex_
std::map< Address, std::pair< Address, NativeModule * > > lookup_map_
std::atomic< Address > next_code_space_hint_
Friends
class WasmCodeAllocator
class WasmCodeLookupCache
class WasmEngine
class WasmImportWrapperCache
Detailed Description
Definition at line 1170 of file wasm-code-manager.h.
Constructor & Destructor Documentation
WasmCodeManager() [1/2]
v8::internal::wasm::WasmCodeManager::WasmCodeManager ()
Definition at line 2179 of file wasm-code-manager.cc.
    : max_committed_code_space_(v8_flags.wasm_max_committed_code_mb * MB),
      critical_committed_code_space_(max_committed_code_space_ / 2),
      next_code_space_hint_(reinterpret_cast<Address>(
          GetPlatformPageAllocator()->GetRandomMmapAddr())) {
  // Check that --wasm-max-code-space-size-mb is not set bigger than the default
  // value. Otherwise we run into DCHECKs or other crashes later.
  CHECK_GE(kDefaultMaxWasmCodeSpaceSizeMb,
           v8_flags.wasm_max_code_space_size_mb);
}
References CHECK_GE, v8::internal::kDefaultMaxWasmCodeSpaceSizeMb, and v8::internal::v8_flags.
WasmCodeManager() [2/2]
v8::internal::wasm::WasmCodeManager::WasmCodeManager (const WasmCodeManager &) [delete]
 WasmCodeManager()
v8::internal::wasm::WasmCodeManager::~WasmCodeManager ()
Definition at line 2190 of file wasm-code-manager.cc.
                                  {
  // No more committed code space.
  DCHECK_EQ(0, total_committed_code_space_.load());
}
References DCHECK_EQ, and total_committed_code_space_.
Member Function Documentation
AssignRange()
void v8::internal::wasm::WasmCodeManager::AssignRange (base::AddressRegion region, NativeModule * native_module) [private]
Definition at line 2260 of file wasm-code-manager.cc.
                                                               {
  base::MutexGuard lock(&native_modules_mutex_);
  lookup_map_.insert(std::make_pair(
      region.begin(), std::make_pair(region.end(), native_module)));
}
References v8::base::AddressRegion::begin(), v8::base::AddressRegion::end(), lookup_map_, and native_modules_mutex_.
Commit()
void v8::internal::wasm::WasmCodeManager::Commit (base::AddressRegion region) [private]
Definition at line 2203 of file wasm-code-manager.cc.
                                                     {
  DCHECK(IsAligned(region.begin(), CommitPageSize()));
  DCHECK(IsAligned(region.size(), CommitPageSize()));
  // Reserve the size. Use CAS loop to avoid overflow on
  // {total_committed_code_space_}.
  size_t old_value = total_committed_code_space_.load();
  while (true) {
    DCHECK_GE(max_committed_code_space_, old_value);
    if (region.size() > max_committed_code_space_ - old_value) {
      auto oom_detail = base::FormattedString{}
                        << "trying to commit " << region.size()
                        << ", already committed " << old_value;
      V8::FatalProcessOutOfMemory(nullptr,
                                  "Exceeding maximum wasm committed code space",
                                  oom_detail.PrintToArray().data());
      UNREACHABLE();
    }
    if (total_committed_code_space_.compare_exchange_weak(
            old_value, old_value + region.size())) {
      break;
    }
  }
  TRACE_HEAP("Setting rwx permissions for 0x%" PRIxPTR ":0x%" PRIxPTR "\n",
             region.begin(), region.end());
  bool success = GetPlatformPageAllocator()->RecommitPages(
      reinterpret_cast<void*>(region.begin()), region.size(),
      PageAllocator::kReadWriteExecute);
  if (V8_UNLIKELY(!success)) {
    auto oom_detail = base::FormattedString{} << "region size: "
                                              << region.size();
    V8::FatalProcessOutOfMemory(nullptr, "Commit wasm code space",
                                oom_detail.PrintToArray().data());
    UNREACHABLE();
  }
}
References v8::base::AddressRegion::begin(), v8::internal::CommitPageSize(), v8::internal::DCHECK(), DCHECK_GE, v8::base::AddressRegion::end(), v8::internal::V8::FatalProcessOutOfMemory(), v8::internal::GetPlatformPageAllocator(), IsAligned(), v8::PageAllocator::kReadWriteExecute, max_committed_code_space_, v8::PageAllocator::RecommitPages(), v8::base::AddressRegion::size(), total_committed_code_space_, TRACE_HEAP, v8::internal::UNREACHABLE(), and V8_UNLIKELY.
committed_code_space()
size_t v8::internal::wasm::WasmCodeManager::committed_code_space () const [inline]
Definition at line 1193 of file wasm-code-manager.h.
                                      {
    return total_committed_code_space_.load();
  }
Referenced by v8::internal::wasm::WasmEngine::AddPotentiallyDeadCode(), and v8::internal::MemoryMeasurement::FinishProcessing().
Decommit()
void v8::internal::wasm::WasmCodeManager::Decommit (base::AddressRegion region) [private]
Definition at line 2241 of file wasm-code-manager.cc.
                                                       {
  PageAllocator* allocator = GetPlatformPageAllocator();
  DCHECK(IsAligned(region.begin(), allocator->CommitPageSize()));
  DCHECK(IsAligned(region.size(), allocator->CommitPageSize()));
  [[maybe_unused]] size_t old_committed =
      total_committed_code_space_.fetch_sub(region.size());
  DCHECK_LE(region.size(), old_committed);
  TRACE_HEAP("Decommitting system pages 0x%" PRIxPTR ":0x%" PRIxPTR "\n",
             region.begin(), region.end());
  if (V8_UNLIKELY(!allocator->DecommitPages(
          reinterpret_cast<void*>(region.begin()), region.size()))) {
    // Decommit can fail in near-OOM situations.
    auto oom_detail = base::FormattedString{} << "region size: "
                                              << region.size();
    V8::FatalProcessOutOfMemory(nullptr, "Decommit Wasm code space",
                                oom_detail.PrintToArray().data());
  }
}
References v8::base::AddressRegion::begin(), v8::PageAllocator::CommitPageSize(), v8::internal::DCHECK(), DCHECK_LE, v8::PageAllocator::DecommitPages(), v8::base::AddressRegion::end(), v8::internal::V8::FatalProcessOutOfMemory(), v8::internal::GetPlatformPageAllocator(), IsAligned(), v8::base::AddressRegion::size(), total_committed_code_space_, TRACE_HEAP, and V8_UNLIKELY.
EstimateLiftoffCodeSize()
size_t v8::internal::wasm::WasmCodeManager::EstimateLiftoffCodeSize (int body_size) [static]
Definition at line 2380 of file wasm-code-manager.cc.
                                                             {
  return kLiftoffFunctionOverhead + kCodeAlignment / 2 +
         body_size * kLiftoffCodeSizeMultiplier;
}
References v8::internal::kCodeAlignment, v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kLiftoffCodeSizeMultiplier, and v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kLiftoffFunctionOverhead.
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::NewLiftoffAssemblerBuffer().
EstimateNativeModuleCodeSize() [1/2]
size_t v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize (const WasmModule * module) [static]
Definition at line 2386 of file wasm-code-manager.cc.
                                                                             {
  int code_section_length = 0;
  if (module->num_declared_functions > 0) {
    DCHECK_EQ(module->functions.size(),
              module->num_imported_functions + module->num_declared_functions);
    auto* first_fn = &module->functions[module->num_imported_functions];
    auto* last_fn = &module->functions.back();
    code_section_length =
        static_cast<int>(last_fn->code.end_offset() - first_fn->code.offset());
  }
  return EstimateNativeModuleCodeSize(module->num_declared_functions,
                                      code_section_length);
}
References DCHECK_EQ, v8::internal::wasm::WasmModule::functions, v8::internal::wasm::WasmModule::num_declared_functions, and v8::internal::wasm::WasmModule::num_imported_functions.
Referenced by v8::internal::wasm::DeserializeNativeModule(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::GetOrCompileNewNativeModule(), v8::internal::AsmWasmData::New(), v8::internal::wasm::AsyncStreamingProcessor::OnFinishedStream(), v8::internal::wasm::AsyncStreamingProcessor::ProcessCodeSectionHeader(), and v8::internal::wasm::AsyncCompileJob::DecodeModule::RunInBackground().
EstimateNativeModuleCodeSize() [2/2]
size_t v8::internal::wasm::WasmCodeManager::EstimateNativeModuleCodeSize (int num_functions, int code_section_length) [static]
Definition at line 2401 of file wasm-code-manager.cc.
                                                                              {
  // It can happen that even without any functions we still have a code section
  // of size 1, defining 0 function bodies. Still report 0 overall in this case.
  if (num_functions == 0) return 0;
  // The size for the jump table and far jump table is added later, per code
  // space (see {OverheadPerCodeSpace}). We still need to add the overhead for
  // the lazy compile table once, though. There are configurations where we do
  // not need it (non-asm.js, no dynamic tiering and no lazy compilation), but
  // we ignore this here as most of the time we will need it.
  const size_t lazy_compile_table_size =
      JumpTableAssembler::SizeForNumberOfLazyFunctions(num_functions);
  const size_t overhead_per_function_turbofan =
      kTurbofanFunctionOverhead + kCodeAlignment / 2;
  size_t size_of_turbofan = overhead_per_function_turbofan * num_functions +
                            kTurbofanCodeSizeMultiplier * code_section_length;
  const size_t overhead_per_function_liftoff =
      kLiftoffFunctionOverhead + kCodeAlignment / 2;
  // Note: For asm.js we do not have Liftoff support, but this corner case is
  // being ignored here.
  size_t size_of_liftoff =
      v8_flags.liftoff ? overhead_per_function_liftoff * num_functions +
                             kLiftoffCodeSizeMultiplier * code_section_length
                       : 0;
  // Expect that typically not more than half of the functions are actually
  // compiled.
  if (v8_flags.wasm_lazy_compilation) size_of_liftoff /= 2;
  // With dynamic tiering we don't expect to compile more than 25% with
  // TurboFan. If there is no liftoff though then all code will get generated
  // by TurboFan.
  if (v8_flags.liftoff && v8_flags.wasm_dynamic_tiering) size_of_turbofan /= 4;
  return lazy_compile_table_size + size_of_liftoff + size_of_turbofan;
}
References v8::internal::kCodeAlignment, v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kLiftoffCodeSizeMultiplier, v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kLiftoffFunctionOverhead, v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kTurbofanCodeSizeMultiplier, v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::kTurbofanFunctionOverhead, v8::internal::wasm::JumpTableAssembler::SizeForNumberOfLazyFunctions(), and v8::internal::v8_flags.
EstimateNativeModuleMetaDataSize()
size_t v8::internal::wasm::WasmCodeManager::EstimateNativeModuleMetaDataSize (const WasmModule * module) [static]
Definition at line 2441 of file wasm-code-manager.cc.
                              {
  size_t wasm_module_estimate = module->EstimateStoredSize();
  uint32_t num_wasm_functions = module->num_declared_functions;
  // TODO(wasm): Include wire bytes size.
  size_t native_module_estimate =
      sizeof(NativeModule) + // NativeModule struct
      (sizeof(WasmCode*) * num_wasm_functions) + // code table size
      (sizeof(WasmCode) * num_wasm_functions); // code object size
  size_t jump_table_size = RoundUp<kCodeAlignment>(
      JumpTableAssembler::SizeForNumberOfSlots(num_wasm_functions));
  size_t far_jump_table_size =
      RoundUp<kCodeAlignment>(JumpTableAssembler::SizeForNumberOfFarJumpSlots(
          BuiltinLookup::BuiltinCount(),
          NumWasmFunctionsInFarJumpTable(num_wasm_functions)));
  return wasm_module_estimate + native_module_estimate + jump_table_size +
         far_jump_table_size;
}
References v8::internal::wasm::BuiltinLookup::BuiltinCount(), v8::internal::wasm::WasmModule::EstimateStoredSize(), v8::internal::wasm::WasmModule::num_declared_functions, v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::NumWasmFunctionsInFarJumpTable(), v8::internal::wasm::JumpTableAssembler::SizeForNumberOfFarJumpSlots(), and v8::internal::wasm::JumpTableAssembler::SizeForNumberOfSlots().
Referenced by v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::CreateWasmScript(), v8::internal::AsmWasmData::New(), and v8::internal::WasmModuleObject::New().
FlushCodeLookupCache()
void v8::internal::wasm::WasmCodeManager::FlushCodeLookupCache (Isolate * isolate)
Definition at line 3025 of file wasm-code-manager.cc.
                                                           {
  return isolate->wasm_code_look_up_cache()->Flush();
}
Referenced by v8::internal::wasm::WasmEngine::FreeNativeModule(), and v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC().
FreeNativeModule()
void v8::internal::wasm::WasmCodeManager::FreeNativeModule (base::Vector< VirtualMemory > owned_code, size_t committed_size) [private]
Definition at line 2934 of file wasm-code-manager.cc.
                                                                       {
  base::MutexGuard lock(&native_modules_mutex_);
  for (auto& code_space : owned_code_space) {
    DCHECK(code_space.IsReserved());
    TRACE_HEAP("VMem Release: 0x%" PRIxPTR ":0x%" PRIxPTR " (%zu)\n",
               code_space.address(), code_space.end(), code_space.size());
#if defined(V8_OS_WIN64)
    if (CanRegisterUnwindInfoForNonABICompliantCodeRange()) {
      win64_unwindinfo::UnregisterNonABICompliantCodeRange(
          reinterpret_cast<void*>(code_space.address()));
    }
#endif // V8_OS_WIN64
    lookup_map_.erase(code_space.address());
    ThreadIsolation::UnregisterJitPage(code_space.address(), code_space.size());
    code_space.Free();
    DCHECK(!code_space.IsReserved());
  }
  DCHECK(IsAligned(committed_size, CommitPageSize()));
  [[maybe_unused]] size_t old_committed =
      total_committed_code_space_.fetch_sub(committed_size);
  DCHECK_LE(committed_size, old_committed);
}
References v8::internal::win64_unwindinfo::CanRegisterUnwindInfoForNonABICompliantCodeRange(), v8::internal::CommitPageSize(), v8::internal::DCHECK(), DCHECK_LE, IsAligned(), lookup_map_, native_modules_mutex_, total_committed_code_space_, TRACE_HEAP, v8::internal::ThreadIsolation::UnregisterJitPage(), and v8::internal::win64_unwindinfo::UnregisterNonABICompliantCodeRange().
Referenced by v8::internal::wasm::WasmCodeAllocator::~WasmCodeAllocator().
HasMemoryProtectionKeySupport()
bool v8::internal::wasm::WasmCodeManager::HasMemoryProtectionKeySupport () [static]
Definition at line 2465 of file wasm-code-manager.cc.
                                                    {
#if V8_HAS_PKU_JIT_WRITE_PROTECT
  return RwxMemoryWriteScope::IsSupported();
#else
  return false;
#endif // V8_HAS_PKU_JIT_WRITE_PROTECT
}
References v8::internal::RwxMemoryWriteScope::IsSupported().
Referenced by MemoryProtectionKeysEnabled(), and v8::internal::wasm::WasmEngine::NewNativeModule().
LookupCode() [1/2]
WasmCode * v8::internal::wasm::WasmCodeManager::LookupCode (Address pc) const [private]
Definition at line 2976 of file wasm-code-manager.cc.
                                                      {
  NativeModule* candidate = LookupNativeModule(pc);
  if (candidate) return candidate->Lookup(pc);
  return GetWasmImportWrapperCache()->Lookup(pc);
}
References v8::internal::wasm::GetWasmImportWrapperCache(), v8::internal::wasm::WasmImportWrapperCache::Lookup(), v8::internal::wasm::NativeModule::Lookup(), and LookupNativeModule().
LookupCode() [2/2]
WasmCode * v8::internal::wasm::WasmCodeManager::LookupCode (Isolate * isolate, Address pc) const
Definition at line 2982 of file wasm-code-manager.cc.
                                                                        {
  // Since kNullAddress is used as a sentinel value, we should not try
  // to look it up in the cache
  if (pc == kNullAddress) return nullptr;
  // If 'isolate' is nullptr, do not use a cache. This can happen when
  // called from function V8NameConverter::NameOfAddress
  if (isolate) {
    return isolate->wasm_code_look_up_cache()->GetCacheEntry(pc)->code;
  } else {
    wasm::WasmCodeRefScope code_ref_scope;
    return LookupCode(pc);
  }
}
References v8::internal::kNullAddress.
Referenced by v8::internal::wasm::FeedbackMaker::AddCallIndirectCandidate(), v8::internal::Deoptimizer::Deoptimizer(), v8::internal::Deoptimizer::EnsureValidReturnAddress(), v8::internal::wasm::WasmCodeLookupCache::GetCacheEntry(), v8::internal::anonymous_namespace{frames.cc}::GetStateForFastCCallCallerFP(), v8::internal::CommonFrame::HasTaggedOutgoingParams(), v8::internal::wasm::anonymous_namespace{wasm-engine.cc}::ReportLiveCodeFromFrameForGC(), and v8::internal::Isolate::UnwindAndFindHandler().
LookupCodeAndSafepoint()
std::pair< WasmCode *, SafepointEntry > v8::internal::wasm::WasmCodeManager::LookupCodeAndSafepoint (Isolate * isolate, Address pc)
Definition at line 2996 of file wasm-code-manager.cc.
                                  {
  auto* entry = isolate->wasm_code_look_up_cache()->GetCacheEntry(pc);
  WasmCode* code = entry->code;
  DCHECK_NOT_NULL(code);
  // For protected instructions we usually do not emit a safepoint because the
  // frame will be unwound anyway. The exception is debugging code, where the
  // frame might be inspected if "pause on exception" is set.
  // For those instructions, we thus need to explicitly return an empty
  // safepoint; using any previously registered safepoint can lead to crashes
  // when we try to visit spill slots that do not hold tagged values at this
  // point.
  // Evaluate this condition only on demand (the fast path does not need it).
  auto expect_safepoint = [code, pc]() {
    const bool is_protected_instruction = code->IsProtectedInstruction(
        pc - WasmFrameConstants::kProtectedInstructionReturnAddressOffset);
    return !is_protected_instruction || code->for_debugging();
  };
  if (!entry->safepoint_entry.is_initialized() && expect_safepoint()) {
    entry->safepoint_entry = SafepointTable{code}.TryFindEntry(pc);
    CHECK(entry->safepoint_entry.is_initialized());
  } else if (expect_safepoint()) {
    DCHECK_EQ(entry->safepoint_entry, SafepointTable{code}.TryFindEntry(pc));
  } else {
    DCHECK(!entry->safepoint_entry.is_initialized());
  }
  return std::make_pair(code, entry->safepoint_entry);
}
References CHECK, code, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, and v8::internal::SafepointTable::TryFindEntry().
LookupNativeModule()
NativeModule * v8::internal::wasm::WasmCodeManager::LookupNativeModule (Address pc) const
Definition at line 2961 of file wasm-code-manager.cc.
                                                                  {
  base::MutexGuard lock(&native_modules_mutex_);
  if (lookup_map_.empty()) return nullptr;
  auto iter = lookup_map_.upper_bound(pc);
  if (iter == lookup_map_.begin()) return nullptr;
  --iter;
  Address region_start = iter->first;
  Address region_end = iter->second.first;
  NativeModule* candidate = iter->second.second;
  DCHECK_NOT_NULL(candidate);
  return region_start <= pc && pc < region_end ? candidate : nullptr;
}
References DCHECK_NOT_NULL, lookup_map_, and native_modules_mutex_.
Referenced by LookupCode().
MemoryProtectionKeysEnabled()
bool v8::internal::wasm::WasmCodeManager::MemoryProtectionKeysEnabled () [static]
Definition at line 2474 of file wasm-code-manager.cc.
                                                  {
  return HasMemoryProtectionKeySupport();
}
References HasMemoryProtectionKeySupport().
Referenced by TryAllocate().
MemoryProtectionKeyWritable()
bool v8::internal::wasm::WasmCodeManager::MemoryProtectionKeyWritable () [static]
Definition at line 2479 of file wasm-code-manager.cc.
                                                  {
#if V8_HAS_PKU_JIT_WRITE_PROTECT
  return RwxMemoryWriteScope::IsPKUWritable();
#else
  return false;
#endif // V8_HAS_PKU_JIT_WRITE_PROTECT
}
NewNativeModule()
std::shared_ptr< NativeModule > v8::internal::wasm::WasmCodeManager::NewNativeModule (Isolate * isolate, WasmEnabledFeatures enabled_features, WasmDetectedFeatures detected_features, CompileTimeImports compile_imports, size_t code_size_estimate, std::shared_ptr< const WasmModule > module) [private]
Definition at line 2487 of file wasm-code-manager.cc.
                                                                       {
#if V8_ENABLE_DRUMBRAKE
  if (v8_flags.wasm_jitless) {
    VirtualMemory code_space;
    std::shared_ptr<NativeModule> ret;
    new NativeModule(enabled_features, detected_features, compile_imports,
                     std::move(code_space), std::move(module),
                     isolate->async_counters(), &ret);
    // The constructor initialized the shared_ptr.
    DCHECK_NOT_NULL(ret);
    TRACE_HEAP("New NativeModule (wasm-jitless) %p\n", ret.get());
    return ret;
  }
#endif // V8_ENABLE_DRUMBRAKE
  if (total_committed_code_space_.load() >
      critical_committed_code_space_.load()) {
    // Flush Liftoff code and record the flushed code size.
    if (v8_flags.flush_liftoff_code) {
      wasm::GetWasmEngine()->FlushLiftoffCode();
    }
    (reinterpret_cast<v8::Isolate*>(isolate))
        ->MemoryPressureNotification(MemoryPressureLevel::kCritical);
    size_t committed = total_committed_code_space_.load();
    DCHECK_GE(max_committed_code_space_, committed);
    critical_committed_code_space_.store(
        committed + (max_committed_code_space_ - committed) / 2);
  }
  // On 32-bit platforms where no far jumps are needed between code spaces, use
  // a reduced code size estimate. This saves some precious address space at the
  // cost of needing more code spaces, but those are cheaper if they do not
  // result in more far jumps.
  // For now it is the case that far jumps are only needed on 64-bit platforms,
  // so those two conditions can be interchanged. Think about which logic to use
  // once those diverge.
  static_assert(NativeModule::kNeedsFarJumpsBetweenCodeSpaces ==
                (kSystemPointerSize == kInt64Size));
  if constexpr (!NativeModule::kNeedsFarJumpsBetweenCodeSpaces) {
    code_size_estimate /= 2;
  }
  size_t code_vmem_size = ReservationSizeForWasmCode(
      code_size_estimate, module->num_declared_functions, 0);
  DCHECK_EQ(code_vmem_size == 0, module->num_declared_functions == 0);
  // The '--wasm-max-initial-code-space-reservation' testing flag can be used to
  // reduce the maximum size of the initial code space reservation (in MB).
  if (v8_flags.wasm_max_initial_code_space_reservation > 0) {
    size_t flag_max_bytes =
        static_cast<size_t>(v8_flags.wasm_max_initial_code_space_reservation) *
        MB;
    if (flag_max_bytes < code_vmem_size) code_vmem_size = flag_max_bytes;
  }
  // Try up to two times; getting rid of dead JSArrayBuffer allocations might
  // require two GCs because the first GC maybe incremental and may have
  // floating garbage.
  static constexpr int kAllocationRetries = 2;
  VirtualMemory code_space;
  base::AddressRegion code_space_region;
  if (code_vmem_size != 0) {
    for (int retries = 0;; ++retries) {
      code_space = TryAllocate(code_vmem_size);
      if (code_space.IsReserved()) break;
      if (retries == kAllocationRetries) {
        auto oom_detail = base::FormattedString{}
                          << "NewNativeModule cannot allocate code space of "
                          << code_vmem_size << " bytes";
        V8::FatalProcessOutOfMemory(isolate, "Allocate initial wasm code space",
                                    oom_detail.PrintToArray().data());
        UNREACHABLE();
      }
      // Run one GC, then try the allocation again.
      isolate->heap()->MemoryPressureNotification(
          MemoryPressureLevel::kCritical, true);
    }
    code_space_region = code_space.region();
    DCHECK_LE(code_vmem_size, code_space.size());
  }
  std::shared_ptr<NativeModule> ret;
  new NativeModule(enabled_features, detected_features,
                   std::move(compile_imports),
                   std::move(code_space), std::move(module),
                   isolate->async_counters(), &ret);
  // The constructor initialized the shared_ptr.
  DCHECK_NOT_NULL(ret);
  TRACE_HEAP("New NativeModule %p: Mem: 0x%" PRIxPTR ",+%zu\n", ret.get(),
             code_space_region.begin(), code_space_region.size());
  base::MutexGuard lock(&native_modules_mutex_);
  lookup_map_.insert(
      std::make_pair(code_space_region.begin(),
                     std::make_pair(code_space_region.end(), ret.get())));
  return ret;
}
References v8::internal::Isolate::async_counters(), v8::base::AddressRegion::begin(), critical_committed_code_space_, DCHECK_EQ, DCHECK_GE, DCHECK_LE, DCHECK_NOT_NULL, v8::base::AddressRegion::end(), v8::internal::V8::FatalProcessOutOfMemory(), v8::internal::wasm::WasmEngine::FlushLiftoffCode(), v8::internal::wasm::GetWasmEngine(), v8::internal::Isolate::heap(), v8::internal::VirtualMemory::IsReserved(), v8::kCritical, v8::internal::kInt64Size, v8::internal::wasm::NativeModule::kNeedsFarJumpsBetweenCodeSpaces, v8::internal::kSystemPointerSize, lookup_map_, max_committed_code_space_, v8::internal::MB, v8::internal::Heap::MemoryPressureNotification(), native_modules_mutex_, v8::internal::VirtualMemory::region(), v8::internal::wasm::anonymous_namespace{wasm-code-manager.cc}::ReservationSizeForWasmCode(), v8::base::AddressRegion::size(), v8::internal::VirtualMemory::size(), total_committed_code_space_, TRACE_HEAP, TryAllocate(), v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmEngine::NewNativeModule().
operator=()
WasmCodeManager& v8::internal::wasm::WasmCodeManager::operator= (const WasmCodeManager &) [delete]
TryAllocate()
VirtualMemory v8::internal::wasm::WasmCodeManager::TryAllocate (size_t size) [private]
Definition at line 2267 of file wasm-code-manager.cc.
                                                      {
  v8::PageAllocator* page_allocator = GetPlatformPageAllocator();
  DCHECK_GT(size, 0);
  size_t allocate_page_size = page_allocator->AllocatePageSize();
  size = RoundUp(size, allocate_page_size);
  Address hint =
      next_code_space_hint_.fetch_add(size, std::memory_order_relaxed);
  // When we start exposing Wasm in jitless mode, then the jitless flag
  // will have to determine whether we set kMapAsJittable or not.
  DCHECK(!v8_flags.jitless);
  VirtualMemory mem(page_allocator, size,
                    PageAllocator::AllocationHint().WithAddress(
                        reinterpret_cast<void*>(hint)),
                    allocate_page_size,
                    PageAllocator::Permission::kNoAccessWillJitLater);
  if (!mem.IsReserved()) {
    // Try resetting {next_code_space_hint_}, which might fail if another thread
    // bumped it in the meantime.
    Address bumped_hint = hint + size;
    next_code_space_hint_.compare_exchange_weak(bumped_hint, hint,
                                                std::memory_order_relaxed);
    return {};
  }
  TRACE_HEAP("VMem alloc: 0x%" PRIxPTR ":0x%" PRIxPTR " (%zu)\n", mem.address(),
             mem.end(), mem.size());
  if (mem.address() != hint) {
    // If the hint was ignored, just store the end of the new vmem area
    // unconditionally, potentially racing with other concurrent allocations (it
    // does not really matter which end pointer we keep in that case).
    next_code_space_hint_.store(mem.end(), std::memory_order_relaxed);
  }
  // Don't pre-commit the code cage on Windows since it uses memory and it's not
  // required for recommit.
  // iOS cannot adjust page permissions for MAP_JIT'd pages, they are set as RWX
  // at the start.
#if !defined(V8_OS_WIN) && !defined(V8_OS_IOS)
  if (MemoryProtectionKeysEnabled()) {
#if V8_HAS_PKU_JIT_WRITE_PROTECT
    if (ThreadIsolation::Enabled()) {
      CHECK(ThreadIsolation::MakeExecutable(mem.address(), mem.size()));
    } else {
      CHECK(base::MemoryProtectionKey::SetPermissionsAndKey(
          mem.region(), PageAllocator::kReadWriteExecute,
          RwxMemoryWriteScope::memory_protection_key()));
    }
#else
    UNREACHABLE();
#endif
  } else {
    CHECK(SetPermissions(GetPlatformPageAllocator(), mem.address(), mem.size(),
                         PageAllocator::kReadWriteExecute));
  }
  page_allocator->DiscardSystemPages(reinterpret_cast<void*>(mem.address()),
                                     mem.size());
#endif // !defined(V8_OS_WIN) && !defined(V8_OS_IOS)
  ThreadIsolation::RegisterJitPage(mem.address(), mem.size());
  return mem;
}
References v8::internal::VirtualMemory::address(), v8::PageAllocator::AllocatePageSize(), CHECK, v8::internal::DCHECK(), DCHECK_GT, v8::PageAllocator::DiscardSystemPages(), v8::internal::ThreadIsolation::Enabled(), v8::internal::VirtualMemory::end(), v8::internal::GetPlatformPageAllocator(), v8::internal::VirtualMemory::IsReserved(), v8::PageAllocator::kReadWriteExecute, v8::internal::ThreadIsolation::MakeExecutable(), MemoryProtectionKeysEnabled(), next_code_space_hint_, v8::internal::VirtualMemory::region(), v8::internal::ThreadIsolation::RegisterJitPage(), RoundUp(), v8::internal::SetPermissions(), v8::internal::VirtualMemory::size(), size(), TRACE_HEAP, v8::internal::UNREACHABLE(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmImportWrapperCache::LazyInitialize(), and NewNativeModule().
Friends And Related Function Documentation
WasmCodeAllocator
friend class WasmCodeAllocator [friend]
Definition at line 1224 of file wasm-code-manager.h.
WasmCodeLookupCache
friend class WasmCodeLookupCache [friend]
Definition at line 1225 of file wasm-code-manager.h.
WasmEngine
friend class WasmEngine [friend]
Definition at line 1226 of file wasm-code-manager.h.
WasmImportWrapperCache
friend class WasmImportWrapperCache [friend]
Definition at line 1227 of file wasm-code-manager.h.
Member Data Documentation
critical_committed_code_space_
std::atomic<size_t> v8::internal::wasm::WasmCodeManager::critical_committed_code_space_ [private]
Definition at line 1253 of file wasm-code-manager.h.
Referenced by NewNativeModule().
lookup_map_
std::map<Address, std::pair<Address, NativeModule*> > v8::internal::wasm::WasmCodeManager::lookup_map_ [private]
Definition at line 1260 of file wasm-code-manager.h.
Referenced by AssignRange(), FreeNativeModule(), LookupNativeModule(), and NewNativeModule().
max_committed_code_space_
const size_t v8::internal::wasm::WasmCodeManager::max_committed_code_space_ [private]
Definition at line 1246 of file wasm-code-manager.h.
Referenced by Commit(), and NewNativeModule().
native_modules_mutex_
base::Mutex v8::internal::wasm::WasmCodeManager::native_modules_mutex_ [mutable], [private]
Definition at line 1255 of file wasm-code-manager.h.
Referenced by AssignRange(), FreeNativeModule(), LookupNativeModule(), and NewNativeModule().
next_code_space_hint_
std::atomic<Address> v8::internal::wasm::WasmCodeManager::next_code_space_hint_ [private]
Definition at line 1271 of file wasm-code-manager.h.
Referenced by TryAllocate().
total_committed_code_space_
std::atomic<size_t> v8::internal::wasm::WasmCodeManager::total_committed_code_space_ {0} [private]
Definition at line 1248 of file wasm-code-manager.h.
Referenced by Commit(), Decommit(), FreeNativeModule(), NewNativeModule(), and ~WasmCodeManager().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-code-manager.h
/mnt/V8SourceCode/src/wasm/wasm-code-manager.cc