v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next > Class Template Reference
#include <typed-optimizations-reducer.h>
Public Types
using Adapter = UniformReducerAdapter< TypedOptimizationsReducer, Next >
Public Member Functions
OpIndex ReduceInputGraphBranch (OpIndex ig_index, const BranchOp &operation)
template<typename Op , typename Continuation >
OpIndex ReduceInputGraphOperation (OpIndex ig_index, const Op &operation)
Private Member Functions
OpIndex TryAssembleConstantForType (const Type &type)
Type GetType (const OpIndex index)
Detailed Description
template<typename Next>
class v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >
Definition at line 20 of file typed-optimizations-reducer.h.
Member Typedef Documentation
Adapter
template<typename Next >
using v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::Adapter = UniformReducerAdapter<TypedOptimizationsReducer, Next>
Definition at line 30 of file typed-optimizations-reducer.h.
Member Function Documentation
GetType()
template<typename Next >
Type v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::GetType (const OpIndex index) [inline], [private]
Definition at line 123 of file typed-optimizations-reducer.h.
                                    {
    // Typed optimizations use the types of the input graph.
    return Asm().GetInputGraphType(index);
  }
References v8::internal::index.
Referenced by v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphBranch(), and v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphOperation().
ReduceInputGraphBranch()
template<typename Next >
OpIndex v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphBranch (OpIndex ig_index, const BranchOp & operation) [inline]
Definition at line 32 of file typed-optimizations-reducer.h.
                                                                              {
    if (!ShouldSkipOptimizationStep()) {
      Type condition_type = GetType(operation.condition());
      if (!condition_type.IsInvalid()) {
        if (condition_type.IsNone()) {
          Asm().Unreachable();
          return OpIndex::Invalid();
        }
        condition_type = Typer::TruncateWord32Input(condition_type, true,
                                                    Asm().graph_zone());
        DCHECK(condition_type.IsWord32());
        if (auto c = condition_type.AsWord32().try_get_constant()) {
          Block* goto_target = *c == 0 ? operation.if_false : operation.if_true;
          Asm().Goto(Asm().MapToNewGraph(goto_target));
          return OpIndex::Invalid();
        }
      }
    }
    return Adapter::ReduceInputGraphBranch(ig_index, operation);
  }
References v8::internal::compiler::turboshaft::Type::AsWord32(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::GetType(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::Type::IsInvalid(), v8::internal::compiler::turboshaft::Type::IsNone(), v8::internal::compiler::turboshaft::Type::IsWord32(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::compiler::turboshaft::Typer::TruncateWord32Input(), and v8::internal::compiler::turboshaft::WordType< Bits >::try_get_constant().
ReduceInputGraphOperation()
template<typename Next >
template<typename Op , typename Continuation >
OpIndex v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphOperation (OpIndex ig_index, const Op & operation) [inline]
Definition at line 54 of file typed-optimizations-reducer.h.
                                                                           {
    if (!ShouldSkipOptimizationStep()) {
      Type type = GetType(ig_index);
      if (type.IsNone()) {
        // This operation is dead. Remove it.
        DCHECK(CanBeTyped(operation));
        Asm().Unreachable();
        return OpIndex::Invalid();
      } else if (!type.IsInvalid()) {
        // See if we can replace the operation by a constant.
        if (OpIndex constant = TryAssembleConstantForType(type);
            constant.valid()) {
          return constant;
        }
      }
    }
    // Otherwise just continue with reduction.
    return Continuation{this}.ReduceInputGraph(ig_index, operation);
  }
References v8::internal::compiler::turboshaft::CanBeTyped(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::GetType(), v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::TryAssembleConstantForType(), v8::internal::tracing::type, and v8::internal::compiler::turboshaft::OpIndex::valid().
TryAssembleConstantForType()
template<typename Next >
OpIndex v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::TryAssembleConstantForType (const Type & type) [inline], [private]
Definition at line 79 of file typed-optimizations-reducer.h.
                                                       {
    switch (type.kind()) {
      case Type::Kind::kWord32: {
        auto w32 = type.AsWord32();
        if (auto c = w32.try_get_constant()) {
          return Asm().Word32Constant(*c);
        }
        break;
      }
      case Type::Kind::kWord64: {
        auto w64 = type.AsWord64();
        if (auto c = w64.try_get_constant()) {
          return Asm().Word64Constant(*c);
        }
        break;
      }
      case Type::Kind::kFloat32: {
        auto f32 = type.AsFloat32();
        if (f32.is_only_nan()) {
          return Asm().Float32Constant(nan_v<32>);
        } else if (f32.is_only_minus_zero()) {
          return Asm().Float32Constant(-0.0f);
        } else if (auto c = f32.try_get_constant()) {
          return Asm().Float32Constant(*c);
        }
        break;
      }
      case Type::Kind::kFloat64: {
        auto f64 = type.AsFloat64();
        if (f64.is_only_nan()) {
          return Asm().Float64Constant(nan_v<64>);
        } else if (f64.is_only_minus_zero()) {
          return Asm().Float64Constant(-0.0);
        } else if (auto c = f64.try_get_constant()) {
          return Asm().Float64Constant(*c);
        }
        break;
      }
      default:
        break;
    }
    return OpIndex::Invalid();
  }
References v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::Type::kFloat32, v8::internal::compiler::turboshaft::Type::kFloat64, v8::internal::compiler::turboshaft::Type::kWord32, v8::internal::compiler::turboshaft::Type::kWord64, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::turboshaft::TypedOptimizationsReducer< Next >::ReduceInputGraphOperation().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/typed-optimizations-reducer.h