v8::internal::compiler::Arm64OperandGenerator Class Reference
Public Member Functions
Arm64OperandGenerator (InstructionSelector *selector)
InstructionOperand UseOperand (OpIndex node, ImmediateMode mode)
bool IsImmediateZero (OpIndex node)
InstructionOperand UseRegisterOrImmediateZero (OpIndex node)
InstructionOperand UseRegisterAtEndOrImmediateZero (OpIndex node)
InstructionOperand UseImmediateOrTemp (OpIndex node, int32_t value)
bool IsIntegerConstant (OpIndex node) const
std::optional< int64_t > GetOptionalIntegerConstant (OpIndex operation)
bool CanBeImmediate (OpIndex node, ImmediateMode mode)
bool CanBeImmediate (int64_t value, ImmediateMode mode)
bool CanBeLoadStoreShiftImmediate (OpIndex node, MemoryRepresentation rep)
Private Member Functions
bool IsLoadStoreImmediate (int64_t value, unsigned size)
Additional Inherited Members
Detailed Description
Definition at line 44 of file instruction-selector-arm64.cc.
Constructor & Destructor Documentation
Arm64OperandGenerator()
v8::internal::compiler::Arm64OperandGenerator::Arm64OperandGenerator (InstructionSelector * selector) [inline], [explicit]
Definition at line 46 of file instruction-selector-arm64.cc.
      : OperandGenerator(selector) {}
Member Function Documentation
CanBeImmediate() [1/2]
bool v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate (int64_t value, ImmediateMode mode) [inline]
Definition at line 136 of file instruction-selector-arm64.cc.
                                                         {
    unsigned ignored;
    switch (mode) {
      case kLogical32Imm:
        // TODO(dcarney): some unencodable values can be handled by
        // switching instructions.
        return internal::Assembler::IsImmLogical(
            static_cast<uint32_t>(value), 32, &ignored, &ignored, &ignored);
      case kLogical64Imm:
        return internal::Assembler::IsImmLogical(
            static_cast<uint64_t>(value), 64, &ignored, &ignored, &ignored);
      case kArithmeticImm:
        return internal::Assembler::IsImmAddSub(value);
      case kLoadStoreImm8:
        return IsLoadStoreImmediate(value, 0);
      case kLoadStoreImm16:
        return IsLoadStoreImmediate(value, 1);
      case kLoadStoreImm32:
        return IsLoadStoreImmediate(value, 2);
      case kLoadStoreImm64:
        return IsLoadStoreImmediate(value, 3);
      case kLoadStoreImm128:
        return IsLoadStoreImmediate(value, 4);
      case kNoImmediate:
        return false;
      case kConditionalCompareImm:
        return internal::Assembler::IsImmConditionalCompare(value);
      case kShift32Imm: // Fall through.
      case kShift64Imm:
        // Shift operations only observe the bottom 5 or 6 bits of the value.
        // All possible shifts can be encoded by discarding bits which have no
        // effect.
        return true;
    }
    return false;
  }
References v8::internal::Assembler::IsImmAddSub(), v8::internal::Assembler::IsImmConditionalCompare(), v8::internal::Assembler::IsImmLogical(), v8::internal::compiler::kArithmeticImm, v8::internal::compiler::kConditionalCompareImm, v8::internal::compiler::kLoadStoreImm128, v8::internal::compiler::kLoadStoreImm16, v8::internal::compiler::kLoadStoreImm32, v8::internal::compiler::kLoadStoreImm64, v8::internal::compiler::kLoadStoreImm8, v8::internal::compiler::kLogical32Imm, v8::internal::compiler::kLogical64Imm, v8::internal::compiler::kNoImmediate, v8::internal::compiler::kShift32Imm, v8::internal::compiler::kShift64Imm, mode(), and v8::internal::value.
CanBeImmediate() [2/2]
bool v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate (OpIndex node, ImmediateMode mode) [inline]
Definition at line 110 of file instruction-selector-arm64.cc.
                                                        {
    const ConstantOp* constant = selector()->Get(node).TryCast<ConstantOp>();
    if (!constant) return false;
    if (constant->kind == ConstantOp::Kind::kCompressedHeapObject) {
      if (!COMPRESS_POINTERS_BOOL) return false;
      // For builtin code we need static roots
      if (selector()->isolate()->bootstrapper() && !V8_STATIC_ROOTS_BOOL) {
        return false;
      }
      const RootsTable& roots_table = selector()->isolate()->roots_table();
      RootIndex root_index;
      Handle<HeapObject> value = constant->handle();
      if (roots_table.IsRootHandle(value, &root_index)) {
        if (!RootsTable::IsReadOnly(root_index)) return false;
        return CanBeImmediate(MacroAssemblerBase::ReadOnlyRootPtr(
                                  root_index, selector()->isolate()),
                              mode);
      }
      return false;
    }
    int64_t value;
    return selector()->MatchSignedIntegralConstant(node, &value) &&
           CanBeImmediate(value, mode);
  }
References v8::internal::compiler::CanBeImmediate(), COMPRESS_POINTERS_BOOL, v8::internal::compiler::turboshaft::ConstantOp::handle(), v8::internal::RootsTable::IsReadOnly(), v8::internal::RootsTable::IsRootHandle(), v8::internal::compiler::turboshaft::ConstantOp::kCompressedHeapObject, v8::internal::compiler::turboshaft::ConstantOp::kind, mode(), v8::internal::MacroAssemblerBase::ReadOnlyRootPtr(), v8::internal::compiler::turboshaft::Operation::TryCast(), V8_STATIC_ROOTS_BOOL, and v8::internal::value.
Referenced by v8::internal::compiler::turboshaft::CombineFlagSettingOps(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAddSub(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::turboshaft::VisitCompareChain(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWordCompare().
CanBeLoadStoreShiftImmediate()
bool v8::internal::compiler::Arm64OperandGenerator::CanBeLoadStoreShiftImmediate (OpIndex node, MemoryRepresentation rep) [inline]
Definition at line 173 of file instruction-selector-arm64.cc.
                                                                            {
    if (uint64_t constant;
        selector()->MatchUnsignedIntegralConstant(node, &constant) &&
        constant == static_cast<uint64_t>(rep.SizeInBytesLog2())) {
      return true;
    }
    return false;
  }
References v8::internal::compiler::turboshaft::MemoryRepresentation::SizeInBytesLog2().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchLoadStoreShift().
GetOptionalIntegerConstant()
std::optional<int64_t> v8::internal::compiler::Arm64OperandGenerator::GetOptionalIntegerConstant (OpIndex operation) [inline]
Definition at line 103 of file instruction-selector-arm64.cc.
                                                                     {
    if (int64_t constant; MatchSignedIntegralConstant(operation, &constant)) {
      return constant;
    }
    return std::nullopt;
  }
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::LeftShiftForReducedMultiply(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAddSub().
IsImmediateZero()
bool v8::internal::compiler::Arm64OperandGenerator::IsImmediateZero (OpIndex node) [inline]
Definition at line 56 of file instruction-selector-arm64.cc.
                                     {
    if (const ConstantOp* constant =
            selector()->Get(node).TryCast<ConstantOp>()) {
      if (constant->IsIntegral() && constant->integral() == 0) return true;
      if (constant->kind == ConstantOp::Kind::kFloat32) {
        return constant->float32().get_bits() == 0;
      }
      if (constant->kind == ConstantOp::Kind::kFloat64) {
        return constant->float64().get_bits() == 0;
      }
    }
    return false;
  }
References v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::ConstantOp::kFloat32, and v8::internal::compiler::turboshaft::ConstantOp::kFloat64.
IsIntegerConstant()
bool v8::internal::compiler::Arm64OperandGenerator::IsIntegerConstant (OpIndex node) const [inline]
Definition at line 98 of file instruction-selector-arm64.cc.
                                             {
    int64_t unused;
    return selector()->MatchSignedIntegralConstant(node, &unused);
  }
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchAnyShift().
IsLoadStoreImmediate()
bool v8::internal::compiler::Arm64OperandGenerator::IsLoadStoreImmediate (int64_t value, unsigned size) [inline], [private]
Definition at line 183 of file instruction-selector-arm64.cc.
                                                          {
    return internal::Assembler::IsImmLSScaled(value, size) ||
           internal::Assembler::IsImmLSUnscaled(value);
  }
References v8::internal::Assembler::IsImmLSScaled(), v8::internal::Assembler::IsImmLSUnscaled(), size(), and v8::internal::value.
UseImmediateOrTemp()
InstructionOperand v8::internal::compiler::Arm64OperandGenerator::UseImmediateOrTemp (OpIndex node, int32_t value) [inline]
Definition at line 91 of file instruction-selector-arm64.cc.
                                                                     {
    if (selector()->Get(node).Cast<ConstantOp>().signed_integral() == value) {
      return UseImmediate(node);
    }
    return TempImmediate(value);
  }
References v8::internal::compiler::turboshaft::Get(), and v8::internal::value.
UseOperand()
InstructionOperand v8::internal::compiler::Arm64OperandGenerator::UseOperand (OpIndex node, ImmediateMode mode) [inline]
Definition at line 49 of file instruction-selector-arm64.cc.
                                                                  {
    if (CanBeImmediate(node, mode)) {
      return UseImmediate(node);
    }
    return UseRegister(node);
  }
References v8::internal::compiler::CanBeImmediate(), mode(), and v8::internal::maglev::UseRegister().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRO(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitWordCompare().
UseRegisterAtEndOrImmediateZero()
InstructionOperand v8::internal::compiler::Arm64OperandGenerator::UseRegisterAtEndOrImmediateZero (OpIndex node) [inline]
Definition at line 82 of file instruction-selector-arm64.cc.
                                                                   {
    if (IsImmediateZero(node)) {
      return UseImmediate(node);
    }
    return this->UseRegisterAtEnd(node);
  }
UseRegisterOrImmediateZero()
InstructionOperand v8::internal::compiler::Arm64OperandGenerator::UseRegisterOrImmediateZero (OpIndex node) [inline]
Definition at line 72 of file instruction-selector-arm64.cc.
                                                              {
    if (IsImmediateZero(node)) {
      return UseImmediate(node);
    }
    return UseRegister(node);
  }
References v8::internal::maglev::UseRegister().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitCompare(), and v8::internal::compiler::turboshaft::VisitCompareChain().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/arm64/instruction-selector-arm64.cc