v8::internal::JSArrayBufferView::BodyDescriptor Class Reference
#include <objects-body-descriptors-inl.h>
Public Types
using Base = JSAPIObjectWithEmbedderSlots::BodyDescriptor
Static Public Member Functions
template<typename ObjectVisitor >
static void IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor *v)
Additional Inherited Members
Detailed Description
Definition at line 631 of file objects-body-descriptors-inl.h.
Member Typedef Documentation
Base
using v8::internal::JSArrayBufferView::BodyDescriptor::Base = JSAPIObjectWithEmbedderSlots::BodyDescriptor
Definition at line 634 of file objects-body-descriptors-inl.h.
Member Function Documentation
IterateBody()
template<typename ObjectVisitor >
static void v8::internal::JSArrayBufferView::BodyDescriptor::IterateBody (Tagged< Map > map, Tagged< HeapObject > obj, int object_size, ObjectVisitor * v) [inline], [static]
Definition at line 637 of file objects-body-descriptors-inl.h.
                                                                    {
    // JSObject with wrapper field.
    IterateJSAPIObjectWithEmbedderSlotsHeader(map, obj, object_size, v);
    // JSArrayBufferView.
    IteratePointers(obj, JSArrayBufferView::kStartOfStrongFieldsOffset,
                    JSArrayBufferView::kEndOfStrongFieldsOffset, v);
  }
References v8::internal::JSAPIObjectWithEmbedderSlotsOrJSSpecialObjectBodyDescriptor::IterateJSAPIObjectWithEmbedderSlotsHeader(), and v8::internal::BodyDescriptorBase::IteratePointers().
Referenced by v8::internal::JSTypedArray::BodyDescriptor::IterateBody(), and v8::internal::JSDataViewOrRabGsabDataView::BodyDescriptor::IterateBody().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/objects-body-descriptors-inl.h