v8::internal::Tuple2 Class Reference
#include <struct.h>
Public Member Functions
void BriefPrintDetails (std::ostream &os)
Tagged< Object > value1 () const
void set_value1 (Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< Object > value2 () const
void set_value2 (Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Private Attributes
TaggedMember< Object > value1_
TaggedMember< Object > value2_
Friends
class TorqueGeneratedTuple2Asserts
Additional Inherited Members
Detailed Description
Definition at line 43 of file struct.h.
Member Function Documentation
BriefPrintDetails()
void v8::internal::Tuple2::BriefPrintDetails (std::ostream & os)
Definition at line 1923 of file objects.cc.
                                             {
  os << " " << Brief(value1()) << ", " << Brief(value2());
}
References value1(), and value2().
set_value1()
void v8::internal::Tuple2::set_value1 (Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 27 of file struct-inl.h.
                                                                   {
  value1_.store(this, value, mode);
}
References mode(), v8::internal::value, and value1_.
set_value2()
void v8::internal::Tuple2::set_value2 (Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 32 of file struct-inl.h.
                                                                   {
  value2_.store(this, value, mode);
}
References mode(), v8::internal::value, and value2_.
value1()
Tagged< Object > v8::internal::Tuple2::value1 () const [inline]
Definition at line 26 of file struct-inl.h.
{ return value1_.load(); }
Referenced by BriefPrintDetails().
value2()
Tagged< Object > v8::internal::Tuple2::value2 () const [inline]
Definition at line 31 of file struct-inl.h.
{ return value2_.load(); }
References value2_.
Referenced by BriefPrintDetails().
Friends And Related Function Documentation
TorqueGeneratedTuple2Asserts
friend class TorqueGeneratedTuple2Asserts [friend]
Definition at line 59 of file struct.h.
Member Data Documentation
value1_
TaggedMember<Object> v8::internal::Tuple2::value1_ [private]
Definition at line 60 of file struct.h.
Referenced by set_value1().
value2_
TaggedMember<Object> v8::internal::Tuple2::value2_ [private]
Definition at line 61 of file struct.h.
Referenced by set_value2(), and value2().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/struct.h
/mnt/V8SourceCode/src/objects/objects.cc
/mnt/V8SourceCode/src/objects/struct-inl.h