v8::internal::Space Class Reference
#include <spaces.h>
Public Member Functions
Space (Heap *heap, AllocationSpace id, std::unique_ptr< FreeList > free_list)
~Space () override=default
Space (const Space &)=delete
Space & operator= (const Space &)=delete
virtual size_t SizeOfObjects () const
virtual size_t Available () const =0
virtual std::unique_ptr< ObjectIterator > GetObjectIterator (Heap *heap)=0
void IncrementExternalBackingStoreBytes (ExternalBackingStoreType type, size_t amount)
void DecrementExternalBackingStoreBytes (ExternalBackingStoreType type, size_t amount)
virtual size_t ExternalBackingStoreBytes (ExternalBackingStoreType type) const
virtual MutablePageMetadata * first_page ()
virtual MutablePageMetadata * last_page ()
virtual const MutablePageMetadata * first_page () const
virtual const MutablePageMetadata * last_page () const
virtual heap::List< MutablePageMetadata > & memory_chunk_list ()
virtual PageMetadata * InitializePage (MutablePageMetadata *chunk)
virtual void NotifyBlackAreaCreated (size_t size)
virtual void NotifyBlackAreaDestroyed (size_t size)
FreeList * free_list ()
Address FirstPageAddress () const
Static Public Member Functions
static void MoveExternalBackingStoreBytes (ExternalBackingStoreType type, Space *from, Space *to, size_t amount)
Protected Attributes
heap::List< MutablePageMetadata > memory_chunk_list_
std::atomic< size_t > external_backing_store_bytes_ [static_cast< int >(ExternalBackingStoreType::kNumValues)] = {0}
std::unique_ptr< FreeList > free_list_
Additional Inherited Members
Detailed Description
Definition at line 67 of file spaces.h.
Constructor & Destructor Documentation
Space() [1/2]
v8::internal::Space::Space (Heap * heap, AllocationSpace id, std::unique_ptr< FreeList > free_list) [inline]
Definition at line 72 of file spaces.h.
      : BaseSpace(heap, id), free_list_(std::move(free_list)) {}
 Space()
v8::internal::Space::~Space () [override], [default]
Space() [2/2]
v8::internal::Space::Space (const Space &) [delete]
Member Function Documentation
Available()
virtual size_t v8::internal::Space::Available () const [pure virtual]
Implemented in v8::internal::NewLargeObjectSpace, v8::internal::LargeObjectSpace, and v8::internal::SemiSpace.
DecrementExternalBackingStoreBytes()
void v8::internal::Space::DecrementExternalBackingStoreBytes (ExternalBackingStoreType type, size_t amount) [inline]
Definition at line 43 of file spaces-inl.h.
                                                              {
  base::CheckedDecrement(&external_backing_store_bytes_[static_cast<int>(type)],
                         amount);
  heap()->DecrementExternalBackingStoreBytes(type, amount);
}
References v8::internal::Heap::DecrementExternalBackingStoreBytes(), external_backing_store_bytes_, v8::internal::BaseSpace::heap(), and v8::internal::tracing::type.
Referenced by v8::internal::MutablePageMetadata::DecrementExternalBackingStoreBytes(), v8::internal::LargeObjectSpace::RemovePage(), and v8::internal::SemiSpace::RemovePage().
ExternalBackingStoreBytes()
virtual size_t v8::internal::Space::ExternalBackingStoreBytes (ExternalBackingStoreType type) const [inline], [virtual]
Definition at line 95 of file spaces.h.
                                           {
    return external_backing_store_bytes_[static_cast<int>(type)];
  }
References v8::internal::tracing::type.
first_page() [1/2]
virtual MutablePageMetadata* v8::internal::Space::first_page () [inline], [virtual]
Reimplemented in v8::internal::LargeObjectSpace, and v8::internal::SemiSpace.
Definition at line 100 of file spaces.h.
                                            {
    return memory_chunk_list_.front();
  }
first_page() [2/2]
virtual const MutablePageMetadata* v8::internal::Space::first_page () const [inline], [virtual]
Reimplemented in v8::internal::LargeObjectSpace, and v8::internal::SemiSpace.
Definition at line 105 of file spaces.h.
                                                        {
    return memory_chunk_list_.front();
  }
FirstPageAddress()
Address v8::internal::Space::FirstPageAddress () const [inline]
Definition at line 125 of file spaces.h.
                                   {
    DCHECK_NOT_NULL(first_page());
    return first_page()->ChunkAddress();
  }
References DCHECK_NOT_NULL.
free_list()
FreeList* v8::internal::Space::free_list () [inline]
Definition at line 123 of file spaces.h.
{ return free_list_.get(); }
Referenced by v8::internal::PageMetadata::AllocateFreeListCategories(), v8::internal::MutablePageMetadata::ComputeFreeListsLength(), v8::internal::PageMetadata::ForAllFreeListCategories(), v8::internal::PageMetadata::InitializeFreeListCategories(), v8::internal::PageMetadata::ReleaseFreeListCategories(), and v8::internal::anonymous_namespace{sweeper.cc}::VerifyPreparedPage().
GetObjectIterator()
virtual std::unique_ptr<ObjectIterator> v8::internal::Space::GetObjectIterator (Heap * heap) [pure virtual]
Implemented in v8::internal::LargeObjectSpace, and v8::internal::SemiSpace.
Referenced by v8::internal::HeapObjectIterator::HeapObjectIterator(), and v8::internal::HeapObjectIterator::NextObject().
IncrementExternalBackingStoreBytes()
void v8::internal::Space::IncrementExternalBackingStoreBytes (ExternalBackingStoreType type, size_t amount) [inline]
Definition at line 36 of file spaces-inl.h.
                                                              {
  base::CheckedIncrement(&external_backing_store_bytes_[static_cast<int>(type)],
                         amount);
  heap()->IncrementExternalBackingStoreBytes(type, amount);
}
References v8::base::CheckedIncrement(), external_backing_store_bytes_, v8::internal::BaseSpace::heap(), v8::internal::Heap::IncrementExternalBackingStoreBytes(), and v8::internal::tracing::type.
Referenced by v8::internal::LargeObjectSpace::AddPage(), and v8::internal::MutablePageMetadata::IncrementExternalBackingStoreBytes().
InitializePage()
virtual PageMetadata* v8::internal::Space::InitializePage (MutablePageMetadata * chunk) [inline], [virtual]
Reimplemented in v8::internal::SemiSpace.
Definition at line 116 of file spaces.h.
                                                                   {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
last_page() [1/2]
virtual MutablePageMetadata* v8::internal::Space::last_page () [inline], [virtual]
Reimplemented in v8::internal::SemiSpace.
Definition at line 103 of file spaces.h.
{ return memory_chunk_list_.back(); }
last_page() [2/2]
virtual const MutablePageMetadata* v8::internal::Space::last_page () const [inline], [virtual]
Reimplemented in v8::internal::SemiSpace.
Definition at line 108 of file spaces.h.
                                                       {
    return memory_chunk_list_.back();
  }
memory_chunk_list()
virtual heap::List<MutablePageMetadata>& v8::internal::Space::memory_chunk_list () [inline], [virtual]
Definition at line 112 of file spaces.h.
                                                             {
    return memory_chunk_list_;
  }
Referenced by v8::internal::NewLargeObjectSpace::FreeDeadObjects().
MoveExternalBackingStoreBytes()
void v8::internal::Space::MoveExternalBackingStoreBytes (ExternalBackingStoreType type, Space * from, Space * to, size_t amount) [inline], [static]
Definition at line 50 of file spaces-inl.h.
                                                         {
  if (from == to) return;
  base::CheckedDecrement(
      &(from->external_backing_store_bytes_[static_cast<int>(type)]), amount);
  base::CheckedIncrement(
      &(to->external_backing_store_bytes_[static_cast<int>(type)]), amount);
}
References v8::base::CheckedIncrement(), external_backing_store_bytes_, and v8::internal::tracing::type.
Referenced by v8::internal::MutablePageMetadata::MoveExternalBackingStoreBytes().
NotifyBlackAreaCreated()
virtual void v8::internal::Space::NotifyBlackAreaCreated (size_t size) [inline], [virtual]
Definition at line 120 of file spaces.h.
{}
Referenced by v8::internal::PageMetadata::CreateBlackArea().
NotifyBlackAreaDestroyed()
virtual void v8::internal::Space::NotifyBlackAreaDestroyed (size_t size) [inline], [virtual]
Definition at line 121 of file spaces.h.
{}
Referenced by v8::internal::PageMetadata::DestroyBlackArea().
operator=()
Space& v8::internal::Space::operator= (const Space &) [delete]
SizeOfObjects()
virtual size_t v8::internal::Space::SizeOfObjects () const [inline], [virtual]
Reimplemented in v8::internal::LargeObjectSpace, and v8::internal::SemiSpace.
Definition at line 82 of file spaces.h.
{ return Size(); }
Member Data Documentation
external_backing_store_bytes_
std::atomic<size_t> v8::internal::Space::external_backing_store_bytes_[static_cast< int >(ExternalBackingStoreType::kNumValues)] = {0} [protected]
Definition at line 138 of file spaces.h.
Referenced by DecrementExternalBackingStoreBytes(), IncrementExternalBackingStoreBytes(), MoveExternalBackingStoreBytes(), and v8::internal::SemiSpace::Swap().
free_list_
std::unique_ptr<FreeList> v8::internal::Space::free_list_ [protected]
Definition at line 140 of file spaces.h.
memory_chunk_list_
heap::List<MutablePageMetadata> v8::internal::Space::memory_chunk_list_ [protected]
Definition at line 136 of file spaces.h.
Referenced by v8::internal::LargeObjectSpace::AddPage(), v8::internal::SemiSpace::AdvancePage(), v8::internal::SemiSpace::AllocateFreshPage(), v8::internal::SemiSpace::first_page(), v8::internal::SemiSpace::IsCommitted(), v8::internal::SemiSpace::last_page(), v8::internal::SemiSpace::MovePageToTheEnd(), v8::internal::SemiSpace::MoveQuarantinedPage(), v8::internal::LargeObjectSpace::RemovePage(), v8::internal::SemiSpace::RemovePage(), v8::internal::SemiSpace::RewindPages(), v8::internal::SemiSpace::ShrinkCapacityTo(), v8::internal::SemiSpace::Swap(), v8::internal::LargeObjectSpace::TearDown(), v8::internal::SemiSpace::Uncommit(), and v8::internal::SemiSpace::~SemiSpace().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/spaces.h
/mnt/V8SourceCode/src/heap/spaces-inl.h