v8::internal::WeakArrayList::Iterator Class Reference
#include <fixed-array.h>
Public Member Functions
Iterator (Tagged< WeakArrayList > array)
Iterator (const Iterator &)=delete
Iterator & operator= (const Iterator &)=delete
Tagged< HeapObject > Next ()
Private Attributes
int index_
Tagged< WeakArrayList > array_
Detailed Description
Definition at line 685 of file fixed-array.h.
Constructor & Destructor Documentation
Iterator() [1/2]
v8::internal::WeakArrayList::Iterator::Iterator (Tagged< WeakArrayList > array) [inline], [explicit]
Definition at line 687 of file fixed-array.h.
: index_(0), array_(array) {}
Iterator() [2/2]
v8::internal::WeakArrayList::Iterator::Iterator (const Iterator &) [delete]
Member Function Documentation
Next()
Tagged< HeapObject > v8::internal::WeakArrayList::Iterator::Next () [inline]
Definition at line 713 of file fixed-array-inl.h.
                                               {
  if (!array_.is_null()) {
    while (index_ < array_->length()) {
      Tagged<MaybeObject> item = array_->Get(index_++);
      DCHECK(item.IsWeakOrCleared());
      if (!item.IsCleared()) return item.GetHeapObjectAssumeWeak();
    }
    array_ = WeakArrayList();
  }
  return Tagged<HeapObject>();
}
References array_, v8::internal::DCHECK(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak(), index_, v8::internal::TaggedImpl< kRefType, StorageType >::IsCleared(), v8::internal::TaggedImpl< kRefType, StorageType >::IsWeakOrCleared(), v8::internal::length, and v8::internal::Tagged< HeapObject >.
operator=()
Iterator& v8::internal::WeakArrayList::Iterator::operator= (const Iterator &) [delete]
Member Data Documentation
array_
Tagged<WeakArrayList> v8::internal::WeakArrayList::Iterator::array_ [private]
Definition at line 695 of file fixed-array.h.
Referenced by Next().
index_
int v8::internal::WeakArrayList::Iterator::index_ [private]
Definition at line 694 of file fixed-array.h.
Referenced by Next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/fixed-array.h
/mnt/V8SourceCode/src/objects/fixed-array-inl.h