v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived > Class Template Reference
#include <graph.h>
Public Member Functions
void AddChild (Derived *next)
Derived * LastChild () const
Derived * NeighboringChild () const
bool HasChildren () const
base::SmallVector< Derived *, 8 > Children () const
Private Attributes
Derived * neighboring_child_ = nullptr
Derived * last_child_ = nullptr
Detailed Description
template<class Derived>
class v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >
Definition at line 199 of file graph.h.
Member Function Documentation
AddChild()
template<class Derived >
void v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::AddChild (Derived * next) [inline]
Definition at line 204 of file graph.h.
                               {
    DCHECK_EQ(static_cast<Derived*>(this)->len_ + 1, next->len_);
    next->neighboring_child_ = last_child_;
    last_child_ = next;
  }
References DCHECK_EQ, and v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::last_child_.
Children()
template<class Derived >
base::SmallVector<Derived*, 8> v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::Children () const [inline]
Definition at line 214 of file graph.h.
                                                {
    base::SmallVector<Derived*, 8> result;
    for (Derived* child = last_child_; child != nullptr;
         child = child->neighboring_child_) {
      result.push_back(child);
    }
    std::reverse(result.begin(), result.end());
    return result;
  }
References v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::last_child_, and v8::base::internal::result.
Referenced by v8::internal::compiler::turboshaft::Block::PrintDominatorTree().
HasChildren()
template<class Derived >
bool v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::HasChildren () const [inline]
Definition at line 212 of file graph.h.
{ return last_child_ != nullptr; }
References v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::last_child_.
LastChild()
template<class Derived >
Derived* v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::LastChild () const [inline]
Definition at line 210 of file graph.h.
{ return last_child_; }
References v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::last_child_.
Referenced by v8::internal::compiler::turboshaft::AnalyzerIterator::MarkLoopForRevisitSkipHeader(), v8::internal::compiler::turboshaft::AnalyzerIterator::Next(), and v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::VisitAllBlocks().
NeighboringChild()
template<class Derived >
Derived* v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::NeighboringChild () const [inline]
Definition at line 211 of file graph.h.
{ return neighboring_child_; }
References v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::neighboring_child_.
Member Data Documentation
last_child_
template<class Derived >
Derived* v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::last_child_ = nullptr [private]
Definition at line 229 of file graph.h.
Referenced by v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::AddChild(), v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::Children(), v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::HasChildren(), and v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::LastChild().
neighboring_child_
template<class Derived >
Derived* v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::neighboring_child_ = nullptr [private]
Definition at line 228 of file graph.h.
Referenced by v8::internal::compiler::turboshaft::DominatorForwardTreeNode< Derived >::NeighboringChild().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/graph.h