v8::internal::ProfilerListener Class Reference
#include <profiler-listener.h>
Public Member Functions
ProfilerListener (Isolate *, CodeEventObserver *, CodeEntryStorage &code_entry_storage, WeakCodeRegistry &weak_code_registry, CpuProfilingNamingMode mode=kDebugNaming)
~ProfilerListener () override
ProfilerListener (const ProfilerListener &)=delete
ProfilerListener & operator= (const ProfilerListener &)=delete
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, const char *name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< Name > name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name) override
void CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name, int line, int column) override
void CallbackEvent (DirectHandle< Name > name, Address entry_point) override
void GetterCallbackEvent (DirectHandle< Name > name, Address entry_point) override
void SetterCallbackEvent (DirectHandle< Name > name, Address entry_point) override
void RegExpCodeCreateEvent (DirectHandle< AbstractCode > code, DirectHandle< String > source, RegExpFlags flags) override
void CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) override
void BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) override
void SharedFunctionInfoMoveEvent (Address from, Address to) override
void NativeContextMoveEvent (Address from, Address to) override
void CodeMovingGCEvent () override
void CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) override
void CodeDeoptEvent (DirectHandle< Code > code, DeoptimizeKind kind, Address pc, int fp_to_sp_delta) override
void CodeDependencyChangeEvent (DirectHandle< Code > code, DirectHandle< SharedFunctionInfo > sfi, const char *reason) override
void WeakCodeClearEvent () override
void OnHeapObjectDeletion (CodeEntry *) override
void CodeSweepEvent ()
const char * GetName (Tagged< Name > name)
const char * GetName (int args_count)
const char * GetName (const char *name)
const char * GetName (base::Vector< const char > name)
const char * GetConsName (const char *prefix, Tagged< Name > name)
void set_observer (CodeEventObserver *observer)
Private Member Functions
const char * GetFunctionName (Tagged< SharedFunctionInfo >)
void AttachDeoptInlinedFrames (DirectHandle< Code > code, CodeDeoptEventRecord *rec)
Tagged< Name > InferScriptName (Tagged< Name > name, Tagged< SharedFunctionInfo > info)
void DispatchCodeEvent (const CodeEventsContainer &evt_rec)
Private Attributes
Isolate * isolate_
CodeEventObserver * observer_
CodeEntryStorage & code_entries_
WeakCodeRegistry & weak_code_registry_
const CpuProfilingNamingMode naming_mode_
Additional Inherited Members
Detailed Description
Definition at line 27 of file profiler-listener.h.
Constructor & Destructor Documentation
ProfilerListener() [1/2]
v8::internal::ProfilerListener::ProfilerListener (Isolate * isolate, CodeEventObserver * observer, CodeEntryStorage & code_entry_storage, WeakCodeRegistry & weak_code_registry, CpuProfilingNamingMode mode = kDebugNaming)
Definition at line 30 of file profiler-listener.cc.
    : isolate_(isolate),
      observer_(observer),
      code_entries_(code_entry_storage),
      weak_code_registry_(weak_code_registry),
      naming_mode_(naming_mode) {}
 ProfilerListener()
v8::internal::ProfilerListener::~ProfilerListener () [override], [default]
ProfilerListener() [2/2]
v8::internal::ProfilerListener::ProfilerListener (const ProfilerListener &) [delete]
Member Function Documentation
AttachDeoptInlinedFrames()
void v8::internal::ProfilerListener::AttachDeoptInlinedFrames (DirectHandle< Code > code, CodeDeoptEventRecord * rec) [private]
Definition at line 406 of file profiler-listener.cc.
                                                                           {
  int deopt_id = rec->deopt_id;
  SourcePosition last_position = SourcePosition::Unknown();
  int mask = RelocInfo::ModeMask(RelocInfo::DEOPT_ID) |
             RelocInfo::ModeMask(RelocInfo::DEOPT_SCRIPT_OFFSET) |
             RelocInfo::ModeMask(RelocInfo::DEOPT_INLINING_ID);
  rec->deopt_frames = nullptr;
  rec->deopt_frame_count = 0;
  for (RelocIterator it(*code, mask); !it.done(); it.next()) {
    RelocInfo* info = it.rinfo();
    if (info->rmode() == RelocInfo::DEOPT_SCRIPT_OFFSET) {
      int script_offset = static_cast<int>(info->data());
      it.next();
      DCHECK(it.rinfo()->rmode() == RelocInfo::DEOPT_INLINING_ID);
      int inlining_id = static_cast<int>(it.rinfo()->data());
      last_position = SourcePosition(script_offset, inlining_id);
      continue;
    }
    if (info->rmode() == RelocInfo::DEOPT_ID) {
      if (deopt_id != static_cast<int>(info->data())) continue;
      if (!last_position.IsKnown()) continue;
      // SourcePosition::InliningStack allocates a handle for the SFI of each
      // frame. These don't escape this function, but quickly add up. This
      // scope limits their lifetime.
      HandleScope scope(isolate_);
      std::vector<SourcePositionInfo> stack =
          last_position.InliningStack(isolate_, *code);
      CpuProfileDeoptFrame* deopt_frames =
          new CpuProfileDeoptFrame[stack.size()];
      int deopt_frame_count = 0;
      for (SourcePositionInfo& pos_info : stack) {
        if (pos_info.position.ScriptOffset() == kNoSourcePosition) continue;
        if (pos_info.script.is_null()) continue;
        int script_id = pos_info.script->id();
        size_t offset = static_cast<size_t>(pos_info.position.ScriptOffset());
        deopt_frames[deopt_frame_count++] = {script_id, offset};
      }
      rec->deopt_frames = deopt_frames;
      rec->deopt_frame_count = deopt_frame_count;
      break;
    }
  }
}
References code, v8::internal::RelocInfo::data(), v8::internal::DCHECK(), v8::internal::CodeDeoptEventRecord::deopt_frame_count, v8::internal::CodeDeoptEventRecord::deopt_frames, v8::internal::RelocInfo::DEOPT_ID, v8::internal::CodeDeoptEventRecord::deopt_id, v8::internal::RelocInfo::DEOPT_INLINING_ID, v8::internal::RelocInfo::DEOPT_SCRIPT_OFFSET, v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::SourcePosition::InliningStack(), v8::internal::SourcePosition::IsKnown(), isolate_, v8::internal::kNoSourcePosition, v8::internal::RelocInfo::ModeMask(), v8::internal::RelocInfo::rmode(), v8::internal::stack, and v8::internal::SourcePosition::Unknown().
Referenced by CodeDeoptEvent().
BytecodeMoveEvent()
void v8::internal::ProfilerListener::BytecodeMoveEvent (Tagged< BytecodeArray > from, Tagged< BytecodeArray > to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 317 of file profiler-listener.cc.
                                                                   {
  DisallowGarbageCollection no_gc;
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kCodeMove);
  CodeMoveEventRecord* rec = &evt_rec.CodeMoveEventRecord_;
  rec->from_instruction_start = from->GetFirstBytecodeAddress();
  rec->to_instruction_start = to->GetFirstBytecodeAddress();
  DispatchCodeEvent(evt_rec);
}
References DispatchCodeEvent(), v8::internal::CodeMoveEventRecord::from_instruction_start, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::CodeMoveEventRecord::to_instruction_start.
CallbackEvent()
void v8::internal::ProfilerListener::CallbackEvent (DirectHandle< Name > name, Address entry_point) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 259 of file profiler-listener.cc.
                                                          {
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kCodeCreation);
  CodeCreateEventRecord* rec = &evt_rec.CodeCreateEventRecord_;
  rec->instruction_start = entry_point;
  rec->entry = code_entries_.Create(LogEventListener::CodeTag::kCallback,
                                    GetName(*name));
  rec->instruction_size = 1;
  DispatchCodeEvent(evt_rec);
}
References code_entries_, v8::internal::CodeEntryStorage::Create(), DispatchCodeEvent(), v8::internal::CodeCreateEventRecord::entry, GetName(), v8::internal::CodeCreateEventRecord::instruction_size, v8::internal::CodeCreateEventRecord::instruction_start, and v8::internal::name.
CodeCreateEvent() [1/4]
void v8::internal::ProfilerListener::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, const char * name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 43 of file profiler-listener.cc.
                                                         {
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kCodeCreation);
  CodeCreateEventRecord* rec = &evt_rec.CodeCreateEventRecord_;
  PtrComprCageBase cage_base(isolate_);
  rec->instruction_start = code->InstructionStart(cage_base);
  rec->entry =
      code_entries_.Create(tag, GetName(name), CodeEntry::kEmptyResourceName,
                           LineAndColumn{}, nullptr);
  rec->instruction_size = code->InstructionSize(cage_base);
  weak_code_registry_.Track(rec->entry, code);
  DispatchCodeEvent(evt_rec);
}
References code, code_entries_, v8::internal::CodeEntryStorage::Create(), DispatchCodeEvent(), v8::internal::CodeCreateEventRecord::entry, GetName(), v8::internal::CodeCreateEventRecord::instruction_size, v8::internal::CodeCreateEventRecord::instruction_start, isolate_, v8::internal::CodeEntry::kEmptyResourceName, v8::internal::name, v8::internal::WeakCodeRegistry::Track(), and weak_code_registry_.
CodeCreateEvent() [2/4]
void v8::internal::ProfilerListener::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< Name > name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 58 of file profiler-listener.cc.
                                                                {
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kCodeCreation);
  CodeCreateEventRecord* rec = &evt_rec.CodeCreateEventRecord_;
  PtrComprCageBase cage_base(isolate_);
  rec->instruction_start = code->InstructionStart(cage_base);
  rec->entry =
      code_entries_.Create(tag, GetName(*name), CodeEntry::kEmptyResourceName,
                           LineAndColumn{}, nullptr);
  rec->instruction_size = code->InstructionSize(cage_base);
  weak_code_registry_.Track(rec->entry, code);
  DispatchCodeEvent(evt_rec);
}
References code, code_entries_, v8::internal::CodeEntryStorage::Create(), DispatchCodeEvent(), v8::internal::CodeCreateEventRecord::entry, GetName(), v8::internal::CodeCreateEventRecord::instruction_size, v8::internal::CodeCreateEventRecord::instruction_start, isolate_, v8::internal::CodeEntry::kEmptyResourceName, v8::internal::name, v8::internal::WeakCodeRegistry::Track(), and weak_code_registry_.
CodeCreateEvent() [3/4]
void v8::internal::ProfilerListener::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 73 of file profiler-listener.cc.
                                                                       {
  PtrComprCageBase cage_base(isolate_);
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kCodeCreation);
  CodeCreateEventRecord* rec = &evt_rec.CodeCreateEventRecord_;
  rec->instruction_start = code->InstructionStart(cage_base);
  rec->entry =
      code_entries_.Create(tag, GetName(shared->DebugNameCStr().get()),
                           GetName(InferScriptName(*script_name, *shared)),
                           LineAndColumn{}, nullptr);
  rec->entry->FillFunctionInfo(*shared);
  rec->instruction_size = code->InstructionSize(cage_base);
  weak_code_registry_.Track(rec->entry, code);
  DispatchCodeEvent(evt_rec);
}
References code, code_entries_, v8::internal::CodeEntryStorage::Create(), DispatchCodeEvent(), v8::internal::CodeCreateEventRecord::entry, v8::internal::CodeEntry::FillFunctionInfo(), GetName(), InferScriptName(), v8::internal::CodeCreateEventRecord::instruction_size, v8::internal::CodeCreateEventRecord::instruction_start, isolate_, v8::internal::WeakCodeRegistry::Track(), and weak_code_registry_.
CodeCreateEvent() [4/4]
void v8::internal::ProfilerListener::CodeCreateEvent (CodeTag tag, DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared, DirectHandle< Name > script_name, int line, int column) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 108 of file profiler-listener.cc.
                                                   {
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kCodeCreation);
  CodeCreateEventRecord* rec = &evt_rec.CodeCreateEventRecord_;
  PtrComprCageBase cage_base(isolate_);
  rec->instruction_start = abstract_code->InstructionStart(cage_base);
  std::unique_ptr<SourcePositionTable> line_table;
  std::unordered_map<int, std::vector<CodeEntryAndPosition>> inline_stacks;
  std::unordered_set<CodeEntry*, CodeEntry::Hasher, CodeEntry::Equals>
      cached_inline_entries;
  bool is_shared_cross_origin = false;
  if (IsScript(shared->script(cage_base), cage_base)) {
    DirectHandle<Script> script(Cast<Script>(shared->script(cage_base)),
                                isolate_);
    line_table.reset(new SourcePositionTable());
    is_shared_cross_origin = script->origin_options().IsSharedCrossOrigin();
    bool is_baseline = abstract_code->kind(cage_base) == CodeKind::BASELINE;
    Handle<TrustedByteArray> source_position_table(
        abstract_code->SourcePositionTable(isolate_, *shared), isolate_);
    std::unique_ptr<baseline::BytecodeOffsetIterator> baseline_iterator;
    if (is_baseline) {
      Handle<BytecodeArray> bytecodes(shared->GetBytecodeArray(isolate_),
                                      isolate_);
      Handle<TrustedByteArray> bytecode_offsets(
          abstract_code->GetCode()->bytecode_offset_table(), isolate_);
      baseline_iterator = std::make_unique<baseline::BytecodeOffsetIterator>(
          bytecode_offsets, bytecodes);
    }
    // Add each position to the source position table and store inlining stacks
    // for inline positions. We store almost the same information in the
    // profiler as is stored on the code object, except that we transform source
    // positions to line numbers here, because we only care about attributing
    // ticks to a given line.
    for (SourcePositionTableIterator it(source_position_table); !it.done();
         it.Advance()) {
      int position = it.source_position().ScriptOffset();
      int inlining_id = it.source_position().InliningId();
      int code_offset = it.code_offset();
      if (is_baseline) {
        // Use the bytecode offset to calculate pc offset for baseline code.
        baseline_iterator->AdvanceToBytecodeOffset(code_offset);
        code_offset =
            static_cast<int>(baseline_iterator->current_pc_start_offset());
      }
      if (inlining_id == SourcePosition::kNotInlined) {
        Script::PositionInfo info;
        script->GetPositionInfo(position, &info,
                                Script::OffsetFlag::kWithOffset);
        line_table->SetPosition(code_offset, {info.line + 1, info.column + 1},
                                inlining_id);
      } else {
        DCHECK(!is_baseline);
        DCHECK(IsCode(*abstract_code, cage_base));
        std::vector<SourcePositionInfo> stack =
            it.source_position().InliningStack(isolate_,
                                               abstract_code->GetCode());
        DCHECK(!stack.empty());
        // When we have an inlining id and we are doing cross-script inlining,
        // then the script of the inlined frames may be different to the script
        // of |shared|.
        LineAndColumn line_and_column{stack.front().line + 1,
                                      stack.front().column + 1};
        line_table->SetPosition(code_offset, line_and_column, inlining_id);
        std::vector<CodeEntryAndPosition> inline_stack;
        for (SourcePositionInfo& pos_info : stack) {
          if (pos_info.position.ScriptOffset() == kNoSourcePosition) continue;
          if (pos_info.script.is_null()) continue;
          Script::PositionInfo script_pos_info;
          pos_info.script->GetPositionInfo(pos_info.position.ScriptOffset(),
                                           &script_pos_info,
                                           Script::OffsetFlag::kWithOffset);
          line_and_column = {script_pos_info.line + 1,
                             script_pos_info.column + 1};
          const char* resource_name =
              (IsName(pos_info.script->name()))
                  ? GetName(Cast<Name>(pos_info.script->name()))
                  : CodeEntry::kEmptyResourceName;
          bool inline_is_shared_cross_origin =
              pos_info.script->origin_options().IsSharedCrossOrigin();
          // We need the start line number and column number of the function for
          // kLeafNodeLineNumbers mode. Creating a SourcePositionInfo is a handy
          // way of getting both easily.
          SourcePositionInfo start_pos_info(
              isolate_, SourcePosition(pos_info.shared->StartPosition()),
              pos_info.shared);
          CodeEntry* inline_entry = code_entries_.Create(
              tag, GetFunctionName(*pos_info.shared), resource_name,
              LineAndColumn{start_pos_info.line + 1, start_pos_info.column + 1},
              nullptr, inline_is_shared_cross_origin);
          inline_entry->FillFunctionInfo(*pos_info.shared);
          // Create a canonical CodeEntry for each inlined frame and then reuse
          // them for subsequent inline stacks to avoid a lot of duplication.
          CodeEntry* cached_entry = GetOrInsertCachedEntry(
              &cached_inline_entries, inline_entry, code_entries_);
          inline_stack.push_back({cached_entry, line_and_column});
        }
        DCHECK(!inline_stack.empty());
        inline_stacks.emplace(inlining_id, std::move(inline_stack));
      }
    }
  }
  rec->entry =
      code_entries_.Create(tag, GetFunctionName(*shared),
                           GetName(InferScriptName(*script_name, *shared)),
                           LineAndColumn{line, column}, std::move(line_table),
                           is_shared_cross_origin);
  if (!inline_stacks.empty()) {
    rec->entry->SetInlineStacks(std::move(cached_inline_entries),
                                std::move(inline_stacks));
  }
  rec->entry->FillFunctionInfo(*shared);
  rec->instruction_size = abstract_code->InstructionSize(cage_base);
  weak_code_registry_.Track(rec->entry, abstract_code);
  DispatchCodeEvent(evt_rec);
}
References code_entries_, v8::internal::Script::PositionInfo::column, v8::internal::CodeEntryStorage::Create(), v8::internal::DCHECK(), DispatchCodeEvent(), v8::internal::SourcePositionTableIterator::done(), v8::internal::CodeCreateEventRecord::entry, v8::internal::CodeEntry::FillFunctionInfo(), GetFunctionName(), GetName(), v8::internal::anonymous_namespace{profiler-listener.cc}::GetOrInsertCachedEntry(), InferScriptName(), v8::internal::CodeCreateEventRecord::instruction_size, v8::internal::CodeCreateEventRecord::instruction_start, isolate_, v8::internal::CodeEntry::kEmptyResourceName, v8::internal::kNoSourcePosition, v8::internal::SourcePosition::kNotInlined, v8::internal::Script::kWithOffset, v8::internal::Script::PositionInfo::line, v8::internal::script, v8::internal::CodeEntry::SetInlineStacks(), v8::internal::stack, v8::internal::WeakCodeRegistry::Track(), and weak_code_registry_.
CodeDeoptEvent()
void v8::internal::ProfilerListener::CodeDeoptEvent (DirectHandle< Code > code, DeoptimizeKind kind, Address pc, int fp_to_sp_delta) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 345 of file profiler-listener.cc.
                                                          {
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kCodeDeopt);
  CodeDeoptEventRecord* rec = &evt_rec.CodeDeoptEventRecord_;
  Deoptimizer::DeoptInfo info = Deoptimizer::GetDeoptInfo(*code, pc);
  rec->instruction_start = code->instruction_start();
  rec->deopt_reason = DeoptimizeReasonToString(info.deopt_reason);
  rec->deopt_id = info.deopt_id;
  rec->pc = pc;
  rec->fp_to_sp_delta = fp_to_sp_delta;
  // When a function is deoptimized, we store the deoptimized frame information
  // for the use of GetDeoptInfos().
  AttachDeoptInlinedFrames(code, rec);
  DispatchCodeEvent(evt_rec);
}
References AttachDeoptInlinedFrames(), code, v8::internal::Deoptimizer::DeoptInfo::deopt_id, v8::internal::CodeDeoptEventRecord::deopt_id, v8::internal::Deoptimizer::DeoptInfo::deopt_reason, v8::internal::CodeDeoptEventRecord::deopt_reason, v8::internal::DeoptimizeReasonToString(), DispatchCodeEvent(), v8::internal::CodeDeoptEventRecord::fp_to_sp_delta, v8::internal::Deoptimizer::GetDeoptInfo(), v8::internal::CodeDeoptEventRecord::instruction_start, and v8::internal::CodeDeoptEventRecord::pc.
CodeDependencyChangeEvent()
void v8::internal::ProfilerListener::CodeDependencyChangeEvent (DirectHandle< Code > code, DirectHandle< SharedFunctionInfo > sfi, const char * reason) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 74 of file profiler-listener.h.
                                                              {}
CodeDisableOptEvent()
void v8::internal::ProfilerListener::CodeDisableOptEvent (DirectHandle< AbstractCode > code, DirectHandle< SharedFunctionInfo > shared) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 334 of file profiler-listener.cc.
                                                                              {
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kCodeDisableOpt);
  CodeDisableOptEventRecord* rec = &evt_rec.CodeDisableOptEventRecord_;
  PtrComprCageBase cage_base(isolate_);
  rec->instruction_start = code->InstructionStart(cage_base);
  rec->bailout_reason =
      GetBailoutReason(shared->disabled_optimization_reason());
  DispatchCodeEvent(evt_rec);
}
References v8::internal::CodeDisableOptEventRecord::bailout_reason, code, DispatchCodeEvent(), v8::internal::GetBailoutReason(), v8::internal::CodeDisableOptEventRecord::instruction_start, and isolate_.
CodeMoveEvent()
void v8::internal::ProfilerListener::CodeMoveEvent (Tagged< InstructionStream > from, Tagged< InstructionStream > to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 307 of file profiler-listener.cc.
                                                                   {
  DisallowGarbageCollection no_gc;
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kCodeMove);
  CodeMoveEventRecord* rec = &evt_rec.CodeMoveEventRecord_;
  rec->from_instruction_start = from->instruction_start();
  rec->to_instruction_start = to->instruction_start();
  DispatchCodeEvent(evt_rec);
}
References DispatchCodeEvent(), v8::internal::CodeMoveEventRecord::from_instruction_start, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::CodeMoveEventRecord::to_instruction_start.
CodeMovingGCEvent()
void v8::internal::ProfilerListener::CodeMovingGCEvent () [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 69 of file profiler-listener.h.
{}
CodeSweepEvent()
void v8::internal::ProfilerListener::CodeSweepEvent ()
Definition at line 371 of file profiler-listener.cc.
{ weak_code_registry_.Sweep(this); }
References v8::internal::WeakCodeRegistry::Sweep(), and weak_code_registry_.
DispatchCodeEvent()
void v8::internal::ProfilerListener::DispatchCodeEvent (const CodeEventsContainer & evt_rec) [inline], [private]
Definition at line 107 of file profiler-listener.h.
                                                                       {
    observer_->CodeEventHandler(evt_rec);
  }
Referenced by BytecodeMoveEvent(), CallbackEvent(), CodeCreateEvent(), CodeDeoptEvent(), CodeDisableOptEvent(), CodeMoveEvent(), GetterCallbackEvent(), NativeContextMoveEvent(), OnHeapObjectDeletion(), RegExpCodeCreateEvent(), and SetterCallbackEvent().
GetConsName()
const char* v8::internal::ProfilerListener::GetConsName (const char * prefix, Tagged< Name > name) [inline]
Definition at line 94 of file profiler-listener.h.
                                                                 {
    return code_entries_.strings().GetConsName(prefix, name);
  }
References v8::internal::name.
Referenced by GetterCallbackEvent(), RegExpCodeCreateEvent(), and SetterCallbackEvent().
GetFunctionName()
const char * v8::internal::ProfilerListener::GetFunctionName (Tagged< SharedFunctionInfo > shared) [private]
Definition at line 394 of file profiler-listener.cc.
                                       {
  switch (naming_mode_) {
    case kDebugNaming:
      return GetName(shared->DebugNameCStr().get());
    case kStandardNaming:
      return GetName(shared->Name());
    default:
      UNREACHABLE();
  }
}
References GetName(), v8::kDebugNaming, v8::kStandardNaming, naming_mode_, and v8::internal::UNREACHABLE().
Referenced by CodeCreateEvent().
GetName() [1/4]
const char * v8::internal::ProfilerListener::GetName (base::Vector< const char > name)
Definition at line 373 of file profiler-listener.cc.
                                                                 {
  // TODO(all): Change {StringsStorage} to accept non-null-terminated strings.
  base::OwnedVector<char> null_terminated =
      base::OwnedVector<char>::New(name.size() + 1);
#if defined(__GNUC__) && !defined(__clang__)
  // Work around a spurious GCC-12 warning (-Werror=array-bounds).
  if (name.end() < name.begin()) return nullptr;
#endif
  std::copy(name.begin(), name.end(), null_terminated.begin());
  null_terminated[name.size()] = '\0';
  return GetName(null_terminated.begin());
}
References v8::base::OwnedVector< T >::begin(), GetName(), v8::internal::name, and v8::base::OwnedVector< T >::New().
GetName() [2/4]
const char* v8::internal::ProfilerListener::GetName (const char * name) [inline]
Definition at line 90 of file profiler-listener.h.
                                        {
    return code_entries_.strings().GetCopy(name);
  }
References v8::internal::name.
GetName() [3/4]
const char* v8::internal::ProfilerListener::GetName (int args_count) [inline]
Definition at line 87 of file profiler-listener.h.
                                      {
    return code_entries_.strings().GetName(args_count);
  }
GetName() [4/4]
const char* v8::internal::ProfilerListener::GetName (Tagged< Name > name) [inline]
Definition at line 84 of file profiler-listener.h.
                                         {
    return code_entries_.strings().GetName(name);
  }
References v8::internal::name.
Referenced by CallbackEvent(), CodeCreateEvent(), GetFunctionName(), and GetName().
GetterCallbackEvent()
void v8::internal::ProfilerListener::GetterCallbackEvent (DirectHandle< Name > name, Address entry_point) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 270 of file profiler-listener.cc.
                                                                {
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kCodeCreation);
  CodeCreateEventRecord* rec = &evt_rec.CodeCreateEventRecord_;
  rec->instruction_start = entry_point;
  rec->entry = code_entries_.Create(LogEventListener::CodeTag::kCallback,
                                    GetConsName("get ", *name));
  rec->instruction_size = 1;
  DispatchCodeEvent(evt_rec);
}
References code_entries_, v8::internal::CodeEntryStorage::Create(), DispatchCodeEvent(), v8::internal::CodeCreateEventRecord::entry, GetConsName(), v8::internal::CodeCreateEventRecord::instruction_size, v8::internal::CodeCreateEventRecord::instruction_start, and v8::internal::name.
InferScriptName()
Tagged< Name > v8::internal::ProfilerListener::InferScriptName (Tagged< Name > name, Tagged< SharedFunctionInfo > info) [private]
Definition at line 386 of file profiler-listener.cc.
                                                        {
  if (IsString(name) && Cast<String>(name)->length()) return name;
  if (!IsScript(info->script())) return name;
  Tagged<Object> source_url = Cast<Script>(info->script())->source_url();
  return IsName(source_url) ? Cast<Name>(source_url) : name;
}
References v8::internal::length, and v8::internal::name.
Referenced by CodeCreateEvent().
NativeContextMoveEvent()
void v8::internal::ProfilerListener::NativeContextMoveEvent (Address from, Address to) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 327 of file profiler-listener.cc.
                                                                      {
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kNativeContextMove);
  evt_rec.NativeContextMoveEventRecord_.from_address = from;
  evt_rec.NativeContextMoveEventRecord_.to_address = to;
  DispatchCodeEvent(evt_rec);
}
References DispatchCodeEvent().
OnHeapObjectDeletion()
void v8::internal::ProfilerListener::OnHeapObjectDeletion (CodeEntry * entry) [override], [virtual]
Implements v8::internal::WeakCodeRegistry::Listener.
Definition at line 365 of file profiler-listener.cc.
                                                            {
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kCodeDelete);
  evt_rec.CodeDeleteEventRecord_.entry = entry;
  DispatchCodeEvent(evt_rec);
}
References DispatchCodeEvent().
operator=()
ProfilerListener& v8::internal::ProfilerListener::operator= (const ProfilerListener &) [delete]
RegExpCodeCreateEvent()
void v8::internal::ProfilerListener::RegExpCodeCreateEvent (DirectHandle< AbstractCode > code, DirectHandle< String > source, RegExpFlags flags) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 292 of file profiler-listener.cc.
                                                                {
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kCodeCreation);
  CodeCreateEventRecord* rec = &evt_rec.CodeCreateEventRecord_;
  PtrComprCageBase cage_base(isolate_);
  rec->instruction_start = code->InstructionStart(cage_base);
  rec->entry = code_entries_.Create(
      LogEventListener::CodeTag::kRegExp, GetConsName("RegExp: ", *source),
      CodeEntry::kEmptyResourceName, LineAndColumn{}, nullptr);
  rec->instruction_size = code->InstructionSize(cage_base);
  weak_code_registry_.Track(rec->entry, code);
  DispatchCodeEvent(evt_rec);
}
References code, code_entries_, v8::internal::CodeEntryStorage::Create(), DispatchCodeEvent(), v8::internal::CodeCreateEventRecord::entry, GetConsName(), v8::internal::CodeCreateEventRecord::instruction_size, v8::internal::CodeCreateEventRecord::instruction_start, isolate_, v8::internal::CodeEntry::kEmptyResourceName, v8::internal::WeakCodeRegistry::Track(), and weak_code_registry_.
set_observer()
void v8::internal::ProfilerListener::set_observer (CodeEventObserver * observer) [inline]
Definition at line 98 of file profiler-listener.h.
{ observer_ = observer; }
SetterCallbackEvent()
void v8::internal::ProfilerListener::SetterCallbackEvent (DirectHandle< Name > name, Address entry_point) [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 281 of file profiler-listener.cc.
                                                                {
  CodeEventsContainer evt_rec(CodeEventRecord::Type::kCodeCreation);
  CodeCreateEventRecord* rec = &evt_rec.CodeCreateEventRecord_;
  rec->instruction_start = entry_point;
  rec->entry = code_entries_.Create(LogEventListener::CodeTag::kCallback,
                                    GetConsName("set ", *name));
  rec->instruction_size = 1;
  DispatchCodeEvent(evt_rec);
}
References code_entries_, v8::internal::CodeEntryStorage::Create(), DispatchCodeEvent(), v8::internal::CodeCreateEventRecord::entry, GetConsName(), v8::internal::CodeCreateEventRecord::instruction_size, v8::internal::CodeCreateEventRecord::instruction_start, and v8::internal::name.
SharedFunctionInfoMoveEvent()
void v8::internal::ProfilerListener::SharedFunctionInfoMoveEvent (Address from, Address to) [inline], [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 67 of file profiler-listener.h.
{}
WeakCodeClearEvent()
void v8::internal::ProfilerListener::WeakCodeClearEvent () [override], [virtual]
Implements v8::internal::LogEventListener.
Definition at line 363 of file profiler-listener.cc.
{ weak_code_registry_.Sweep(this); }
References v8::internal::WeakCodeRegistry::Sweep(), and weak_code_registry_.
Member Data Documentation
code_entries_
CodeEntryStorage& v8::internal::ProfilerListener::code_entries_ [private]
Definition at line 113 of file profiler-listener.h.
Referenced by CallbackEvent(), CodeCreateEvent(), GetterCallbackEvent(), RegExpCodeCreateEvent(), and SetterCallbackEvent().
isolate_
Isolate* v8::internal::ProfilerListener::isolate_ [private]
Definition at line 111 of file profiler-listener.h.
Referenced by AttachDeoptInlinedFrames(), CodeCreateEvent(), CodeDisableOptEvent(), and RegExpCodeCreateEvent().
naming_mode_
const CpuProfilingNamingMode v8::internal::ProfilerListener::naming_mode_ [private]
Definition at line 115 of file profiler-listener.h.
Referenced by GetFunctionName().
observer_
CodeEventObserver* v8::internal::ProfilerListener::observer_ [private]
Definition at line 112 of file profiler-listener.h.
weak_code_registry_
WeakCodeRegistry& v8::internal::ProfilerListener::weak_code_registry_ [private]
Definition at line 114 of file profiler-listener.h.
Referenced by CodeCreateEvent(), CodeSweepEvent(), RegExpCodeCreateEvent(), and WeakCodeClearEvent().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/profiler-listener.h
/mnt/V8SourceCode/src/profiler/profiler-listener.cc