v8::internal::CPURegister Class Reference
#include <register-arm64.h>
Public Types
enum RegisterType : int8_t { kRegister
, kVRegister
, kNoRegister
 }
Public Member Functions
RegisterType type () const
int SizeInBits () const
int SizeInBytes () const
bool Is8Bits () const
bool Is16Bits () const
bool Is32Bits () const
bool Is64Bits () const
bool Is128Bits () const
bool IsNone () const
constexpr bool Aliases (const CPURegister &other) const
constexpr bool operator== (const CPURegister &other) const
constexpr bool operator!= (const CPURegister &other) const
bool IsZero () const
bool IsSP () const
bool IsRegister () const
bool IsVRegister () const
bool IsFPRegister () const
bool IsW () const
bool IsX () const
bool IsV () const
bool IsB () const
bool IsH () const
bool IsS () const
bool IsD () const
bool IsQ () const
Register Reg () const
VRegister VReg () const
Register X () const
Register W () const
VRegister V () const
VRegister B () const
VRegister H () const
VRegister D () const
VRegister S () const
VRegister Q () const
bool IsSameSizeAndType (const CPURegister &other) const
constexpr bool IsEven () const
int MaxCode () const
Static Public Member Functions
static constexpr CPURegister no_reg ()
static constexpr CPURegister Create (int code, int size, RegisterType type)
Protected Member Functions
constexpr CPURegister (int code, int size, RegisterType type)
Static Protected Member Functions
static constexpr bool IsValidRegister (int code, int size)
static constexpr bool IsValidVRegister (int code, int size)
static constexpr bool IsValid (int code, int size, RegisterType type)
static constexpr bool IsNone (int code, int size, RegisterType type)
Protected Attributes
uint8_t reg_size_
RegisterType reg_type_
Friends
class RegisterBase
Additional Inherited Members
Detailed Description
Definition at line 102 of file register-arm64.h.
Member Enumeration Documentation
RegisterType
enum v8::internal::CPURegister::RegisterType : int8_t
Enumerator
kRegister
kVRegister
kNoRegister
Definition at line 104 of file register-arm64.h.
: int8_t { kRegister, kVRegister, kNoRegister };
Constructor & Destructor Documentation
CPURegister()
constexpr v8::internal::CPURegister::CPURegister (int code, int size, RegisterType type) [inline], [constexpr], [protected]
Definition at line 217 of file register-arm64.h.
      : RegisterBase(code), reg_size_(size), reg_type_(type) {}
Member Function Documentation
Aliases()
constexpr bool v8::internal::CPURegister::Aliases (const CPURegister & other) const [inline], [constexpr]
Definition at line 146 of file register-arm64.h.
                                                         {
    return RegisterBase::operator==(other) && reg_type_ == other.reg_type_;
  }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::operator==(), and reg_type_.
B()
VRegister v8::internal::CPURegister::B () const [inline]
Definition at line 172 of file assembler-arm64-inl.h.
                                      {
  DCHECK(IsVRegister());
  return VRegister::BRegFromCode(code());
}
References v8::internal::VRegister::BRegFromCode(), v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::DCHECK(), and IsVRegister().
Create()
static constexpr CPURegister v8::internal::CPURegister::Create (int code, int size, RegisterType type) [inline], [static], [constexpr]
Definition at line 110 of file register-arm64.h.
                                                                             {
    DCHECK(IsValid(code, size, type));
    return CPURegister{code, size, type};
  }
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::DCHECK(), IsValid(), size(), and type().
Referenced by v8::internal::CPURegList::Combine(), v8::internal::Register::Create(), v8::internal::VRegister::Create(), and v8::internal::CPURegList::Remove().
D()
VRegister v8::internal::CPURegister::D () const [inline]
Definition at line 187 of file assembler-arm64-inl.h.
                                      {
  DCHECK(IsVRegister());
  return VRegister::DRegFromCode(code());
}
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::DCHECK(), v8::internal::VRegister::DRegFromCode(), and IsVRegister().
Referenced by v8::internal::UseScratchRegisterScope::AcquireD(), and v8::internal::MacroAssembler::Fmov().
H()
VRegister v8::internal::CPURegister::H () const [inline]
Definition at line 177 of file assembler-arm64-inl.h.
                                      {
  DCHECK(IsVRegister());
  return VRegister::HRegFromCode(code());
}
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::DCHECK(), v8::internal::VRegister::HRegFromCode(), and IsVRegister().
Is128Bits()
bool v8::internal::CPURegister::Is128Bits () const [inline]
Definition at line 141 of file register-arm64.h.
                         {
    DCHECK(is_valid());
    return reg_size_ == 128;
  }
References v8::internal::DCHECK(), v8::internal::RegisterBase< CPURegister, kRegAfterLast >::is_valid(), and reg_size_.
Referenced by v8::internal::Assembler::FPFormat(), v8::internal::VRegister::Is16B(), v8::internal::VRegister::Is1Q(), v8::internal::VRegister::Is2D(), v8::internal::VRegister::Is4S(), v8::internal::VRegister::Is8H(), IsQ(), v8::internal::Assembler::LSVFormat(), and v8::internal::Assembler::VFormat().
Is16Bits()
bool v8::internal::CPURegister::Is16Bits () const [inline]
Definition at line 129 of file register-arm64.h.
                        {
    DCHECK(is_valid());
    return reg_size_ == 16;
  }
References v8::internal::DCHECK(), v8::internal::RegisterBase< CPURegister, kRegAfterLast >::is_valid(), and reg_size_.
Referenced by v8::internal::VRegister::Is1H(), and IsH().
Is32Bits()
bool v8::internal::CPURegister::Is32Bits () const [inline]
Definition at line 133 of file register-arm64.h.
                        {
    DCHECK(is_valid());
    return reg_size_ == 32;
  }
References v8::internal::DCHECK(), v8::internal::RegisterBase< CPURegister, kRegAfterLast >::is_valid(), and reg_size_.
Referenced by v8::internal::Assembler::FPFormat(), v8::internal::VRegister::Is1S(), IsS(), IsW(), and v8::internal::Operand::Operand().
Is64Bits()
bool v8::internal::CPURegister::Is64Bits () const [inline]
Definition at line 137 of file register-arm64.h.
                        {
    DCHECK(is_valid());
    return reg_size_ == 64;
  }
References v8::internal::DCHECK(), v8::internal::RegisterBase< CPURegister, kRegAfterLast >::is_valid(), and reg_size_.
Referenced by v8::internal::Assembler::AppropriateZeroRegFor(), v8::internal::MacroAssembler::CmovX(), v8::internal::MacroAssembler::CzeroX(), v8::internal::MacroAssembler::Fmov(), v8::internal::Assembler::FPFormat(), v8::internal::Assembler::FPType(), v8::internal::VRegister::Is1D(), v8::internal::VRegister::Is2S(), v8::internal::VRegister::Is4H(), v8::internal::VRegister::Is8B(), IsD(), IsX(), v8::internal::Assembler::LSVFormat(), v8::internal::MemOperand::MemOperand(), v8::internal::Operand::Operand(), v8::internal::Assembler::SF(), v8::internal::MacroAssembler::SmiTag(), v8::internal::MacroAssembler::SmiUntag(), v8::internal::Operand::ToExtendedRegister(), v8::internal::Operand::ToW(), and v8::internal::Assembler::VFormat().
Is8Bits()
bool v8::internal::CPURegister::Is8Bits () const [inline]
Definition at line 125 of file register-arm64.h.
                       {
    DCHECK(is_valid());
    return reg_size_ == 8;
  }
References v8::internal::DCHECK(), v8::internal::RegisterBase< CPURegister, kRegAfterLast >::is_valid(), and reg_size_.
Referenced by v8::internal::VRegister::Is1B(), and IsB().
IsB()
bool v8::internal::CPURegister::IsB () const [inline]
Definition at line 176 of file register-arm64.h.
{ return IsV() && Is8Bits(); }
References Is8Bits(), and IsV().
IsD()
bool v8::internal::CPURegister::IsD () const [inline]
Definition at line 179 of file register-arm64.h.
{ return IsV() && Is64Bits(); }
References Is64Bits(), and IsV().
Referenced by IsFPRegister().
IsEven()
constexpr bool v8::internal::CPURegister::IsEven () const [inline], [constexpr]
Definition at line 196 of file register-arm64.h.
{ return (code() % 2) == 0; }
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code().
IsFPRegister()
bool v8::internal::CPURegister::IsFPRegister () const [inline]
Definition at line 164 of file register-arm64.h.
{ return IsS() || IsD(); }
References IsD(), and IsS().
IsH()
bool v8::internal::CPURegister::IsH () const [inline]
Definition at line 177 of file register-arm64.h.
{ return IsV() && Is16Bits(); }
References Is16Bits(), and IsV().
IsNone() [1/2]
bool v8::internal::CPURegister::IsNone () const [inline]
Definition at line 145 of file register-arm64.h.
{ return reg_type_ == kNoRegister; }
References kNoRegister, and reg_type_.
Referenced by v8::internal::CPURegList::IncludesAliasOf(), and v8::internal::CPURegList::Remove().
IsNone() [2/2]
static constexpr bool v8::internal::CPURegister::IsNone (int code, int size, RegisterType type) [inline], [static], [constexpr], [protected]
Definition at line 237 of file register-arm64.h.
                                                                      {
    return type == kNoRegister && code == 0 && size == 0;
  }
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), kNoRegister, size(), and type().
IsQ()
bool v8::internal::CPURegister::IsQ () const [inline]
Definition at line 180 of file register-arm64.h.
{ return IsV() && Is128Bits(); }
References Is128Bits(), and IsV().
IsRegister()
bool v8::internal::CPURegister::IsRegister () const [inline]
Definition at line 161 of file register-arm64.h.
{ return reg_type_ == kRegister; }
References kRegister, and reg_type_.
Referenced by IsSP(), IsW(), IsX(), IsZero(), MaxCode(), Reg(), W(), and X().
IsS()
bool v8::internal::CPURegister::IsS () const [inline]
Definition at line 178 of file register-arm64.h.
{ return IsV() && Is32Bits(); }
References Is32Bits(), and IsV().
Referenced by IsFPRegister().
IsSameSizeAndType()
bool v8::internal::CPURegister::IsSameSizeAndType (const CPURegister & other) const [inline]
Definition at line 46 of file assembler-arm64-inl.h.
                                                                         {
  return (reg_size_ == other.reg_size_) && (reg_type_ == other.reg_type_);
}
References reg_size_, and reg_type_.
IsSP()
bool v8::internal::CPURegister::IsSP () const [inline]
Definition at line 55 of file assembler-arm64-inl.h.
                                    {
  DCHECK(is_valid());
  return IsRegister() && (code() == kSPRegInternalCode);
}
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::DCHECK(), v8::internal::RegisterBase< CPURegister, kRegAfterLast >::is_valid(), IsRegister(), and v8::internal::kSPRegInternalCode.
Referenced by v8::internal::MacroAssembler::Add(), v8::internal::MacroAssembler::CmovX(), v8::internal::MacroAssembler::Cmp(), v8::internal::MacroAssembler::CzeroX(), v8::internal::MemOperand::MemOperand(), v8::internal::Operand::Operand(), and v8::internal::MacroAssembler::Sub().
IsV()
bool v8::internal::CPURegister::IsV () const [inline]
Definition at line 175 of file register-arm64.h.
{ return IsVRegister(); }
References IsVRegister().
Referenced by IsB(), IsD(), IsH(), IsQ(), and IsS().
IsValid()
static constexpr bool v8::internal::CPURegister::IsValid (int code, int size, RegisterType type) [inline], [static], [constexpr], [protected]
Definition at line 232 of file register-arm64.h.
                                                                       {
    return (type == kRegister && IsValidRegister(code, size)) ||
           (type == kVRegister && IsValidVRegister(code, size));
  }
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), IsValidRegister(), IsValidVRegister(), kRegister, kVRegister, size(), and type().
Referenced by Create().
IsValidRegister()
static constexpr bool v8::internal::CPURegister::IsValidRegister (int code, int size) [inline], [static], [constexpr], [protected]
Definition at line 220 of file register-arm64.h.
                                                            {
    return (size == kWRegSizeInBits || size == kXRegSizeInBits) &&
           (code < kNumberOfRegisters || code == kSPRegInternalCode);
  }
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::kNumberOfRegisters, v8::internal::kSPRegInternalCode, v8::internal::kWRegSizeInBits, v8::internal::kXRegSizeInBits, and size().
Referenced by IsValid().
IsValidVRegister()
static constexpr bool v8::internal::CPURegister::IsValidVRegister (int code, int size) [inline], [static], [constexpr], [protected]
Definition at line 225 of file register-arm64.h.
                                                             {
    return (size == kBRegSizeInBits || size == kHRegSizeInBits ||
            size == kSRegSizeInBits || size == kDRegSizeInBits ||
            size == kQRegSizeInBits) &&
           code < kNumberOfVRegisters;
  }
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::kBRegSizeInBits, v8::internal::kDRegSizeInBits, v8::internal::kHRegSizeInBits, v8::internal::kNumberOfVRegisters, v8::internal::kQRegSizeInBits, v8::internal::kSRegSizeInBits, and size().
Referenced by IsValid().
IsVRegister()
bool v8::internal::CPURegister::IsVRegister () const [inline]
Definition at line 162 of file register-arm64.h.
{ return reg_type_ == kVRegister; }
References kVRegister, and reg_type_.
Referenced by B(), D(), H(), IsV(), MaxCode(), Q(), S(), V(), and VReg().
IsW()
bool v8::internal::CPURegister::IsW () const [inline]
Definition at line 166 of file register-arm64.h.
{ return IsRegister() && Is32Bits(); }
References Is32Bits(), and IsRegister().
IsX()
bool v8::internal::CPURegister::IsX () const [inline]
Definition at line 167 of file register-arm64.h.
{ return IsRegister() && Is64Bits(); }
References Is64Bits(), and IsRegister().
IsZero()
bool v8::internal::CPURegister::IsZero () const [inline]
Definition at line 50 of file assembler-arm64-inl.h.
                                      {
  DCHECK(is_valid());
  return IsRegister() && (code() == kZeroRegCode);
}
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::DCHECK(), v8::internal::RegisterBase< CPURegister, kRegAfterLast >::is_valid(), IsRegister(), and v8::internal::kZeroRegCode.
Referenced by v8::internal::MacroAssembler::Abs(), v8::internal::MacroAssembler::Adc(), v8::internal::MacroAssembler::Adcs(), v8::internal::MacroAssembler::Add(), v8::internal::MacroAssembler::And(), v8::internal::MacroAssembler::Ands(), v8::internal::MacroAssembler::Asr(), v8::internal::MacroAssembler::Bfi(), v8::internal::MacroAssembler::Bfxil(), v8::internal::MacroAssembler::Bic(), v8::internal::MacroAssembler::Bics(), v8::internal::MacroAssembler::Blr(), v8::internal::MacroAssembler::Br(), v8::internal::MacroAssembler::Cinc(), v8::internal::MacroAssembler::Cinv(), v8::internal::MacroAssembler::Cls(), v8::internal::MacroAssembler::Clz(), v8::internal::MacroAssembler::Cneg(), v8::internal::MacroAssembler::Cnt(), v8::internal::MacroAssembler::Cset(), v8::internal::MacroAssembler::Csetm(), v8::internal::MacroAssembler::Csinc(), v8::internal::MacroAssembler::Csinv(), v8::internal::MacroAssembler::Csneg(), v8::internal::MacroAssembler::Ctz(), v8::internal::MacroAssembler::Eon(), v8::internal::MacroAssembler::Eor(), v8::internal::MacroAssembler::Extr(), v8::internal::MacroAssembler::Fcvtas(), v8::internal::MacroAssembler::Fcvtau(), v8::internal::MacroAssembler::Fcvtms(), v8::internal::MacroAssembler::Fcvtmu(), v8::internal::MacroAssembler::Fcvtns(), v8::internal::MacroAssembler::Fcvtnu(), v8::internal::MacroAssembler::Fcvtzs(), v8::internal::MacroAssembler::Fcvtzu(), v8::internal::MacroAssembler::Fjcvtzs(), v8::internal::MacroAssembler::Fmov(), v8::internal::Operand::IsZero(), v8::internal::MacroAssembler::Lsl(), v8::internal::MacroAssembler::Lsr(), v8::internal::MacroAssembler::Madd(), v8::internal::MemOperand::MemOperand(), v8::internal::MacroAssembler::Movk(), v8::internal::MacroAssembler::Msub(), v8::internal::MacroAssembler::Mul(), v8::internal::MacroAssembler::Mvn(), v8::internal::MacroAssembler::Neg(), v8::internal::MacroAssembler::Ngc(), v8::internal::MacroAssembler::Ngcs(), v8::internal::MacroAssembler::Orn(), v8::internal::MacroAssembler::Orr(), v8::internal::MacroAssembler::Rbit(), v8::internal::Assembler::RdSP(), v8::internal::MacroAssembler::Ret(), v8::internal::MacroAssembler::Rev(), v8::internal::MacroAssembler::Rev16(), v8::internal::MacroAssembler::Rev32(), v8::internal::Assembler::RmNot31(), v8::internal::Assembler::RnSP(), v8::internal::MacroAssembler::Ror(), v8::internal::MacroAssembler::Sbc(), v8::internal::MacroAssembler::Sbcs(), v8::internal::MacroAssembler::Sbfiz(), v8::internal::MacroAssembler::Sbfx(), v8::internal::MacroAssembler::Sdiv(), v8::internal::MacroAssembler::Smaddl(), v8::internal::MacroAssembler::Smsubl(), v8::internal::MacroAssembler::Smulh(), v8::internal::MacroAssembler::Smull(), v8::internal::MacroAssembler::Sub(), v8::internal::MacroAssembler::Sxtb(), v8::internal::MacroAssembler::Sxth(), v8::internal::MacroAssembler::Sxtw(), v8::internal::MacroAssembler::Ubfiz(), v8::internal::MacroAssembler::Ubfx(), v8::internal::MacroAssembler::Udiv(), v8::internal::MacroAssembler::Umaddl(), v8::internal::MacroAssembler::Umsubl(), v8::internal::MacroAssembler::Umulh(), v8::internal::MacroAssembler::Umull(), v8::internal::MacroAssembler::Uxtb(), v8::internal::MacroAssembler::Uxth(), and v8::internal::MacroAssembler::Uxtw().
MaxCode()
int v8::internal::CPURegister::MaxCode () const [inline]
Definition at line 198 of file register-arm64.h.
                      {
    if (IsVRegister()) {
      return kNumberOfVRegisters - 1;
    }
    DCHECK(IsRegister());
    return kNumberOfRegisters - 1;
  }
References v8::internal::DCHECK(), IsRegister(), IsVRegister(), v8::internal::kNumberOfRegisters, and v8::internal::kNumberOfVRegisters.
no_reg()
static constexpr CPURegister v8::internal::CPURegister::no_reg () [inline], [static], [constexpr]
Definition at line 106 of file register-arm64.h.
                                        {
    return CPURegister{kCode_no_reg, 0, kNoRegister};
  }
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::kCode_no_reg, and kNoRegister.
Referenced by v8::internal::Register::no_reg(), and v8::internal::VRegister::no_reg().
operator!=()
constexpr bool v8::internal::CPURegister::operator!= (const CPURegister & other) const [inline], [constexpr]
Definition at line 154 of file register-arm64.h.
                                                            {
    return !operator==(other);
  }
References operator==().
operator==()
constexpr bool v8::internal::CPURegister::operator== (const CPURegister & other) const [inline], [constexpr]
Definition at line 150 of file register-arm64.h.
                                                            {
    return RegisterBase::operator==(other) && reg_size_ == other.reg_size_ &&
           reg_type_ == other.reg_type_;
  }
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::operator==(), reg_size_, and reg_type_.
Referenced by operator!=().
Q()
VRegister v8::internal::CPURegister::Q () const [inline]
Definition at line 192 of file assembler-arm64-inl.h.
                                      {
  DCHECK(IsVRegister());
  return VRegister::QRegFromCode(code());
}
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::DCHECK(), IsVRegister(), and v8::internal::VRegister::QRegFromCode().
Referenced by v8::internal::UseScratchRegisterScope::AcquireQ().
Reg()
Register v8::internal::CPURegister::Reg () const [inline]
Definition at line 152 of file assembler-arm64-inl.h.
                                       {
  DCHECK(IsRegister());
  return Register::Create(code(), reg_size_);
}
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::Register::Create(), v8::internal::DCHECK(), IsRegister(), and reg_size_.
S()
VRegister v8::internal::CPURegister::S () const [inline]
Definition at line 182 of file assembler-arm64-inl.h.
                                      {
  DCHECK(IsVRegister());
  return VRegister::SRegFromCode(code());
}
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::DCHECK(), IsVRegister(), and v8::internal::VRegister::SRegFromCode().
Referenced by v8::internal::UseScratchRegisterScope::AcquireS().
SizeInBits()
int v8::internal::CPURegister::SizeInBits () const [inline]
Definition at line 116 of file register-arm64.h.
                         {
    DCHECK(is_valid());
    return reg_size_;
  }
References v8::internal::DCHECK(), v8::internal::RegisterBase< CPURegister, kRegAfterLast >::is_valid(), and reg_size_.
Referenced by v8::internal::UseScratchRegisterScope::AcquireSameSizeAs(), v8::internal::Assembler::asr(), v8::internal::Assembler::bfi(), v8::internal::Assembler::bfxil(), v8::internal::CPURegList::Combine(), v8::internal::MacroAssembler::CompareAndBranch(), v8::internal::Assembler::lsl(), v8::internal::Assembler::lsr(), v8::internal::Assembler::sbfiz(), v8::internal::Assembler::sbfx(), SizeInBytes(), v8::internal::MacroAssembler::TestAndBranchIfAllClear(), v8::internal::MacroAssembler::TestAndBranchIfAnySet(), v8::internal::Assembler::ubfiz(), and v8::internal::Assembler::ubfx().
SizeInBytes()
int v8::internal::CPURegister::SizeInBytes () const [inline]
Definition at line 120 of file register-arm64.h.
                          {
    DCHECK(is_valid());
    DCHECK_EQ(SizeInBits() % 8, 0);
    return reg_size_ / 8;
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::RegisterBase< CPURegister, kRegAfterLast >::is_valid(), reg_size_, and SizeInBits().
Referenced by v8::internal::VRegister::LaneSizeInBytes(), v8::internal::MacroAssembler::Pop(), v8::internal::MacroAssembler::Push(), and v8::internal::Assembler::SFormat().
type()
RegisterType v8::internal::CPURegister::type () const [inline]
Definition at line 115 of file register-arm64.h.
{ return reg_type_; }
References reg_type_.
Referenced by v8::internal::CPURegList::Combine(), Create(), v8::internal::CPURegList::IncludesAliasOf(), IsNone(), IsValid(), and v8::internal::CPURegList::Remove().
V()
VRegister v8::internal::CPURegister::V () const [inline]
Definition at line 167 of file assembler-arm64-inl.h.
                                      {
  DCHECK(IsVRegister());
  return VRegister::VRegFromCode(code());
}
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::DCHECK(), IsVRegister(), and v8::internal::VRegister::VRegFromCode().
VReg()
VRegister v8::internal::CPURegister::VReg () const [inline]
Definition at line 157 of file assembler-arm64-inl.h.
                                         {
  DCHECK(IsVRegister());
  return VRegister::Create(code(), reg_size_);
}
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::VRegister::Create(), v8::internal::DCHECK(), IsVRegister(), and reg_size_.
W()
Register v8::internal::CPURegister::W () const [inline]
Definition at line 147 of file assembler-arm64-inl.h.
                                     {
  DCHECK(IsRegister());
  return Register::WRegFromCode(code());
}
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::DCHECK(), IsRegister(), and v8::internal::Register::WRegFromCode().
Referenced by v8::internal::UseScratchRegisterScope::AcquireW(), v8::internal::wasm::liftoff::AtomicBinop(), v8::internal::MacroAssembler::CcmpTagged(), v8::internal::MacroAssembler::CmpTagged(), v8::internal::MacroAssembler::CompareTaggedAndBranch(), v8::internal::wasm::liftoff::EmitAllTrue(), v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::GenerateReduceInterruptBudget(), v8::internal::wasm::liftoff::GetMemOp(), v8::internal::wasm::liftoff::GetRegFromType(), v8::internal::MacroAssembler::SmiUntag(), and v8::internal::Operand::ToW().
X()
Register v8::internal::CPURegister::X () const [inline]
Definition at line 162 of file assembler-arm64-inl.h.
                                     {
  DCHECK(IsRegister());
  return Register::XRegFromCode(code());
}
References v8::internal::RegisterBase< CPURegister, kRegAfterLast >::code(), v8::internal::DCHECK(), IsRegister(), and v8::internal::Register::XRegFromCode().
Referenced by v8::internal::UseScratchRegisterScope::AcquireX(), v8::internal::wasm::liftoff::AtomicBinop(), v8::internal::wasm::LiftoffAssembler::emit_i64_and(), v8::internal::wasm::LiftoffAssembler::emit_i64_andi(), v8::internal::wasm::LiftoffAssembler::emit_i64_muli(), v8::internal::wasm::LiftoffAssembler::emit_i64_or(), v8::internal::wasm::LiftoffAssembler::emit_i64_ori(), v8::internal::wasm::LiftoffAssembler::emit_i64_xor(), v8::internal::wasm::LiftoffAssembler::emit_i64_xori(), v8::internal::wasm::LiftoffAssembler::emit_ptrsize_cond_jumpi(), v8::internal::wasm::liftoff::GetMemOp(), and v8::internal::wasm::liftoff::GetRegFromType().
Friends And Related Function Documentation
RegisterBase
friend class RegisterBase [friend]
Definition at line 214 of file register-arm64.h.
Member Data Documentation
reg_size_
uint8_t v8::internal::CPURegister::reg_size_ [protected]
Definition at line 207 of file register-arm64.h.
Referenced by Is128Bits(), Is16Bits(), Is32Bits(), Is64Bits(), Is8Bits(), v8::internal::VRegister::IsSameFormat(), IsSameSizeAndType(), operator==(), Reg(), SizeInBits(), SizeInBytes(), and VReg().
reg_type_
RegisterType v8::internal::CPURegister::reg_type_ [protected]
Definition at line 208 of file register-arm64.h.
Referenced by Aliases(), IsNone(), IsRegister(), IsSameSizeAndType(), IsVRegister(), operator==(), and type().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/arm64/register-arm64.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64-inl.h