v8::internal::compiler::WasmAddressReassociation Class Reference
#include <memory-optimizer.h>
Classes
class CandidateBaseAddr
class CandidateMemOps
Public Member Functions
WasmAddressReassociation (JSGraph *jsgraph, Zone *zone)
void Optimize ()
void VisitProtectedMemOp (Node *node, uint32_t effect_chain)
WasmAddressReassociation (JSGraph *jsgraph, Zone *zone)
WasmAddressReassociation (const WasmAddressReassociation &)=delete
WasmAddressReassociation & operator= (const WasmAddressReassociation &)=delete
void Optimize ()
void VisitProtectedMemOp (Node *node, NodeId effect_chain)
Private Types
using CandidateAddressKey = std::tuple< NodeId, NodeId, NodeId >
Private Member Functions
bool ShouldTryOptimize (const CandidateAddressKey &key) const
Node * CreateNewBase (const CandidateAddressKey &key)
bool HasCandidateBaseAddr (const CandidateAddressKey &key) const
void AddCandidate (Node *mem_op, Node *base, Node *reg_offset, int64_t imm_offset, NodeId effect_chain)
void ReplaceInputs (Node *mem_op, Node *object, Node *index)
Private Attributes
TFGraph *const graph_
CommonOperatorBuilder * common_
MachineOperatorBuilder * machine_
ZoneMap< CandidateAddressKey, CandidateBaseAddr > candidate_base_addrs_
ZoneMap< CandidateAddressKey, CandidateMemOps > candidates_
Zone *const zone_
Detailed Description
Definition at line 19 of file memory-optimizer.h.
Member Typedef Documentation
CandidateAddressKey
using v8::internal::compiler::WasmAddressReassociation::CandidateAddressKey = std::tuple<NodeId, NodeId, NodeId> [private]
Definition at line 35 of file wasm-address-reassociation.h.
Constructor & Destructor Documentation
WasmAddressReassociation() [1/3]
v8::internal::compiler::WasmAddressReassociation::WasmAddressReassociation (JSGraph * jsgraph, Zone * zone) [inline]
Definition at line 21 of file memory-optimizer.h.
{}
WasmAddressReassociation() [2/3]
v8::internal::compiler::WasmAddressReassociation::WasmAddressReassociation (JSGraph * jsgraph, Zone * zone)
WasmAddressReassociation() [3/3]
v8::internal::compiler::WasmAddressReassociation::WasmAddressReassociation (const WasmAddressReassociation &) [delete]
Member Function Documentation
AddCandidate()
void v8::internal::compiler::WasmAddressReassociation::AddCandidate (Node * mem_op, Node * base, Node * reg_offset, int64_t imm_offset, NodeId effect_chain) [private]
Definition at line 146 of file wasm-address-reassociation.cc.
                                                                 {
  // Sort base and offset so that the key is the same for either permutation.
  if (base->id() > reg_offset->id()) {
    std::swap(base, reg_offset);
  }
  CandidateAddressKey key =
      std::make_tuple(base->id(), reg_offset->id(), effect_chain);
  bool is_new =
      candidate_base_addrs_.emplace(key, CandidateBaseAddr(base, reg_offset))
          .second;
  auto it = is_new ? candidates_.emplace(key, CandidateMemOps(zone_)).first
                   : candidates_.find(key);
  it->second.AddCandidate(mem_op, imm_offset);
}
References v8::internal::compiler::Node::id(), and v8::internal::key.
CreateNewBase()
Node * v8::internal::compiler::WasmAddressReassociation::CreateNewBase (const CandidateAddressKey & key) [private]
Definition at line 86 of file wasm-address-reassociation.cc.
                                                                            {
  CandidateBaseAddr& candidate_base_addr = candidate_base_addrs_.at(key);
  Node* base = candidate_base_addr.base();
  Node* reg_offset = candidate_base_addr.offset();
  return graph_->NewNode(machine_->Int64Add(), base, reg_offset);
}
References v8::internal::compiler::WasmAddressReassociation::CandidateBaseAddr::base(), v8::internal::key, and v8::internal::compiler::WasmAddressReassociation::CandidateBaseAddr::offset().
HasCandidateBaseAddr()
bool v8::internal::compiler::WasmAddressReassociation::HasCandidateBaseAddr (const CandidateAddressKey & key) const [private]
Definition at line 164 of file wasm-address-reassociation.cc.
                                          {
  return candidate_base_addrs_.count(key);
}
References v8::internal::key.
operator=()
WasmAddressReassociation& v8::internal::compiler::WasmAddressReassociation::operator= (const WasmAddressReassociation &) [delete]
Optimize() [1/2]
void v8::internal::compiler::WasmAddressReassociation::Optimize () [inline]
Definition at line 22 of file memory-optimizer.h.
{}
Referenced by v8::internal::compiler::MemoryOptimizer::Optimize().
Optimize() [2/2]
void v8::internal::compiler::WasmAddressReassociation::Optimize ()
ReplaceInputs()
void v8::internal::compiler::WasmAddressReassociation::ReplaceInputs (Node * mem_op, Node * object, Node * index) [private]
Definition at line 93 of file wasm-address-reassociation.cc.
                                                           {
  DCHECK_GT(mem_op->InputCount(), 1);
  DCHECK(NodeProperties::IsConstant(offset));
  mem_op->ReplaceInput(0, base);
  mem_op->ReplaceInput(1, offset);
}
References DCHECK, DCHECK_GT, v8::internal::compiler::Node::InputCount(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::IsConstant(), and v8::internal::compiler::Node::ReplaceInput().
ShouldTryOptimize()
bool v8::internal::compiler::WasmAddressReassociation::ShouldTryOptimize (const CandidateAddressKey & key) const [private]
Definition at line 75 of file wasm-address-reassociation.cc.
                                          {
  // We already process the graph in terms of effect chains in an attempt to
  // reduce the risk of creating large live-ranges, but also set a lower
  // bound for the number of required users so that the benefits are more
  // likely to outweigh any detrimental affects, such as additions being shared
  // and so the number of operations is increased. Benchmarking showed two or
  // more was a good heuristic.
  return candidates_.at(key).GetNumNodes() > 1;
}
References v8::internal::key.
VisitProtectedMemOp() [1/2]
void v8::internal::compiler::WasmAddressReassociation::VisitProtectedMemOp (Node * node, NodeId effect_chain)
VisitProtectedMemOp() [2/2]
void v8::internal::compiler::WasmAddressReassociation::VisitProtectedMemOp (Node * node, uint32_t effect_chain) [inline]
Definition at line 23 of file memory-optimizer.h.
{}
Referenced by v8::internal::compiler::MemoryOptimizer::VisitProtectedLoad(), and v8::internal::compiler::MemoryOptimizer::VisitProtectedStore().
Member Data Documentation
candidate_base_addrs_
ZoneMap<CandidateAddressKey, CandidateBaseAddr> v8::internal::compiler::WasmAddressReassociation::candidate_base_addrs_ [private]
Definition at line 77 of file wasm-address-reassociation.h.
candidates_
ZoneMap<CandidateAddressKey, CandidateMemOps> v8::internal::compiler::WasmAddressReassociation::candidates_ [private]
Definition at line 78 of file wasm-address-reassociation.h.
common_
CommonOperatorBuilder* v8::internal::compiler::WasmAddressReassociation::common_ [private]
Definition at line 75 of file wasm-address-reassociation.h.
graph_
TFGraph* const v8::internal::compiler::WasmAddressReassociation::graph_ [private]
Definition at line 74 of file wasm-address-reassociation.h.
machine_
MachineOperatorBuilder* v8::internal::compiler::WasmAddressReassociation::machine_ [private]
Definition at line 76 of file wasm-address-reassociation.h.
zone_
Zone* const v8::internal::compiler::WasmAddressReassociation::zone_ [private]
Definition at line 79 of file wasm-address-reassociation.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/memory-optimizer.h
/mnt/V8SourceCode/src/compiler/wasm-address-reassociation.h
/mnt/V8SourceCode/src/compiler/wasm-address-reassociation.cc