v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder Class Reference
Public Member Functions
template<typename IsolateT >
Handle< FixedArray > AllocateDeclarations (UnoptimizedCompilationInfo *info, BytecodeGenerator *generator, Handle< Script > script, IsolateT *isolate)
size_t constant_pool_entry ()
void set_constant_pool_entry (size_t constant_pool_entry)
void record_global_variable_declaration ()
void record_global_function_declaration ()
void record_module_variable_declaration ()
void record_module_function_declaration ()
bool has_top_level_declaration ()
bool processed ()
void mark_processed ()
Private Attributes
const int kGlobalVariableDeclarationSize = 1
const int kGlobalFunctionDeclarationSize = 2
const int kModuleVariableDeclarationSize = 1
const int kModuleFunctionDeclarationSize = 3
size_t constant_pool_entry_ = 0
int entry_slots_ = 0
bool has_constant_pool_entry_ = false
bool processed_ = false
Detailed Description
Definition at line 853 of file bytecode-generator.cc.
Member Function Documentation
AllocateDeclarations()
template<typename IsolateT >
Handle<FixedArray> v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::AllocateDeclarations (UnoptimizedCompilationInfo * info, BytecodeGenerator * generator, Handle< Script > script, IsolateT * isolate) [inline]
Definition at line 856 of file bytecode-generator.cc.
                                                             {
    DCHECK(has_constant_pool_entry_);
    Handle<FixedArray> data =
        isolate->factory()->NewFixedArray(entry_slots_, AllocationType::kOld);
    int array_index = 0;
    if (info->scope()->is_module_scope()) {
      for (Declaration* decl : *info->scope()->declarations()) {
        Variable* var = decl->var();
        if (!var->is_used()) continue;
        if (var->location() != VariableLocation::MODULE) continue;
#ifdef DEBUG
        int start = array_index;
#endif
        if (decl->IsFunctionDeclaration()) {
          FunctionLiteral* f = static_cast<FunctionDeclaration*>(decl)->fun();
          DirectHandle<SharedFunctionInfo> sfi(
              Compiler::GetSharedFunctionInfo(f, script, isolate));
          // Return a null handle if any initial values can't be created. Caller
          // will set stack overflow.
          if (sfi.is_null()) return Handle<FixedArray>();
          data->set(array_index++, *sfi);
          int literal_index = generator->GetCachedCreateClosureSlot(f);
          data->set(array_index++, Smi::FromInt(literal_index));
          DCHECK(var->IsExport());
          data->set(array_index++, Smi::FromInt(var->index()));
          DCHECK_EQ(start + kModuleFunctionDeclarationSize, array_index);
        } else if (var->IsExport() && var->binding_needs_init()) {
          data->set(array_index++, Smi::FromInt(var->index()));
          DCHECK_EQ(start + kModuleVariableDeclarationSize, array_index);
        }
      }
    } else {
      for (Declaration* decl : *info->scope()->declarations()) {
        Variable* var = decl->var();
        if (!var->is_used()) continue;
        if (var->location() != VariableLocation::UNALLOCATED) continue;
#ifdef DEBUG
        int start = array_index;
#endif
        if (decl->IsVariableDeclaration()) {
          data->set(array_index++, *var->raw_name()->string());
          DCHECK_EQ(start + kGlobalVariableDeclarationSize, array_index);
        } else {
          FunctionLiteral* f = static_cast<FunctionDeclaration*>(decl)->fun();
          DirectHandle<SharedFunctionInfo> sfi(
              Compiler::GetSharedFunctionInfo(f, script, isolate));
          // Return a null handle if any initial values can't be created. Caller
          // will set stack overflow.
          if (sfi.is_null()) return Handle<FixedArray>();
          data->set(array_index++, *sfi);
          int literal_index = generator->GetCachedCreateClosureSlot(f);
          data->set(array_index++, Smi::FromInt(literal_index));
          DCHECK_EQ(start + kGlobalFunctionDeclarationSize, array_index);
        }
      }
    }
    DCHECK_EQ(array_index, data->length());
    return data;
  }
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Scope::declarations(), v8::internal::Smi::FromInt(), v8::internal::interpreter::BytecodeGenerator::GetCachedCreateClosureSlot(), v8::internal::Compiler::GetSharedFunctionInfo(), v8::internal::interpreter::BytecodeGenerator::info(), v8::internal::Scope::is_module_scope(), v8::internal::DirectHandle< T >::is_null(), v8::internal::kOld, v8::internal::MODULE, v8::internal::UnoptimizedCompilationInfo::scope(), v8::internal::script, and v8::internal::UNALLOCATED.
Referenced by v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants().
constant_pool_entry()
size_t v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::constant_pool_entry () [inline]
Definition at line 921 of file bytecode-generator.cc.
                               {
    DCHECK(has_constant_pool_entry_);
    return constant_pool_entry_;
  }
References v8::internal::DCHECK().
has_top_level_declaration()
bool v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::has_top_level_declaration () [inline]
Definition at line 945 of file bytecode-generator.cc.
{ return entry_slots_ > 0; }
mark_processed()
void v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::mark_processed () [inline]
Definition at line 947 of file bytecode-generator.cc.
{ processed_ = true; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDeclareCall().
processed()
bool v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::processed () [inline]
Definition at line 946 of file bytecode-generator.cc.
{ return processed_; }
record_global_function_declaration()
void v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::record_global_function_declaration () [inline]
Definition at line 936 of file bytecode-generator.cc.
                                            {
    entry_slots_ += kGlobalFunctionDeclarationSize;
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitGlobalDeclarations().
record_global_variable_declaration()
void v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::record_global_variable_declaration () [inline]
Definition at line 933 of file bytecode-generator.cc.
                                            {
    entry_slots_ += kGlobalVariableDeclarationSize;
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitGlobalDeclarations().
record_module_function_declaration()
void v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::record_module_function_declaration () [inline]
Definition at line 942 of file bytecode-generator.cc.
                                            {
    entry_slots_ += kModuleFunctionDeclarationSize;
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitModuleDeclarations().
record_module_variable_declaration()
void v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::record_module_variable_declaration () [inline]
Definition at line 939 of file bytecode-generator.cc.
                                            {
    entry_slots_ += kModuleVariableDeclarationSize;
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitModuleDeclarations().
set_constant_pool_entry()
void v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::set_constant_pool_entry (size_t constant_pool_entry) [inline]
Definition at line 926 of file bytecode-generator.cc.
                                                           {
    DCHECK(has_top_level_declaration());
    DCHECK(!has_constant_pool_entry_);
    constant_pool_entry_ = constant_pool_entry;
    has_constant_pool_entry_ = true;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildDeclareCall().
Member Data Documentation
constant_pool_entry_
size_t v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::constant_pool_entry_ = 0 [private]
Definition at line 955 of file bytecode-generator.cc.
entry_slots_
int v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::entry_slots_ = 0 [private]
Definition at line 956 of file bytecode-generator.cc.
has_constant_pool_entry_
bool v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::has_constant_pool_entry_ = false [private]
Definition at line 957 of file bytecode-generator.cc.
kGlobalFunctionDeclarationSize
const int v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::kGlobalFunctionDeclarationSize = 2 [private]
Definition at line 951 of file bytecode-generator.cc.
kGlobalVariableDeclarationSize
const int v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::kGlobalVariableDeclarationSize = 1 [private]
Definition at line 950 of file bytecode-generator.cc.
kModuleFunctionDeclarationSize
const int v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::kModuleFunctionDeclarationSize = 3 [private]
Definition at line 953 of file bytecode-generator.cc.
kModuleVariableDeclarationSize
const int v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::kModuleVariableDeclarationSize = 1 [private]
Definition at line 952 of file bytecode-generator.cc.
processed_
bool v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::processed_ = false [private]
Definition at line 958 of file bytecode-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc