v8::internal::NewSpace Class Reference
#include <new-spaces.h>
Public Types
using iterator = PageIterator
using const_iterator = ConstPageIterator
Public Member Functions
NewSpace (Heap *heap)
base::Mutex * mutex ()
bool Contains (Tagged< Object > o) const
bool Contains (Tagged< HeapObject > o) const
virtual bool ContainsSlow (Address a) const =0
size_t ExternalBackingStoreOverallBytes () const
void PromotePageToOldSpace (PageMetadata *page, FreeMode free_mode)
virtual size_t Capacity () const =0
virtual size_t TotalCapacity () const =0
virtual size_t MinimumCapacity () const =0
virtual size_t MaximumCapacity () const =0
virtual size_t AllocatedSinceLastGC () const =0
virtual void Grow (size_t new_capacity)=0
virtual void MakeIterable ()=0
virtual iterator begin ()=0
virtual iterator end ()=0
virtual const_iterator begin () const =0
virtual const_iterator end () const =0
virtual Address first_allocatable_address () const =0
virtual void GarbageCollectionPrologue ()
virtual void GarbageCollectionEpilogue ()=0
virtual bool IsPromotionCandidate (const MutablePageMetadata *page) const =0
virtual void GrowToMaximumCapacityForTesting ()=0
Protected Member Functions
virtual void RemovePage (PageMetadata *page)=0
Protected Attributes
base::Mutex mutex_
Static Protected Attributes
static const int kAllocationBufferParkingThreshold = 4 * KB
Detailed Description
Definition at line 190 of file new-spaces.h.
Member Typedef Documentation
const_iterator
using v8::internal::NewSpace::const_iterator = ConstPageIterator
Definition at line 193 of file new-spaces.h.
iterator
using v8::internal::NewSpace::iterator = PageIterator
Definition at line 192 of file new-spaces.h.
Constructor & Destructor Documentation
NewSpace()
v8::internal::NewSpace::NewSpace (Heap * heap) [explicit]
Definition at line 401 of file new-spaces.cc.
    : SpaceWithLinearArea(heap, NEW_SPACE, nullptr) {}
Member Function Documentation
AllocatedSinceLastGC()
virtual size_t v8::internal::NewSpace::AllocatedSinceLastGC () const [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
Referenced by v8::internal::Heap::NewSpaceAllocationCounter().
begin() [1/2]
virtual const_iterator v8::internal::NewSpace::begin () const [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
begin() [2/2]
virtual iterator v8::internal::NewSpace::begin () [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
Capacity()
virtual size_t v8::internal::NewSpace::Capacity () const [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
Referenced by v8::internal::Heap::CanPromoteYoungAndExpandOldGeneration(), v8::internal::Heap::NewSpaceCapacity(), and v8::internal::StressScavengeObserver::Step().
Contains() [1/2]
bool v8::internal::NewSpace::Contains (Tagged< HeapObject > o) const [inline]
Definition at line 57 of file new-spaces-inl.h.
                                                  {
  return MemoryChunk::FromHeapObject(o)->InNewSpace();
}
References v8::internal::MemoryChunk::FromHeapObject(), and v8::internal::MemoryChunk::InNewSpace().
Contains() [2/2]
bool v8::internal::NewSpace::Contains (Tagged< Object > o) const [inline]
Definition at line 53 of file new-spaces-inl.h.
                                              {
  return IsHeapObject(o) && Contains(Cast<HeapObject>(o));
}
References v8::internal::IsHeapObject().
Referenced by v8::internal::Heap::Contains(), and v8::internal::Heap::InSpace().
ContainsSlow()
virtual bool v8::internal::NewSpace::ContainsSlow (Address a) const [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
Referenced by v8::internal::Heap::InSpaceSlow().
end() [1/2]
virtual const_iterator v8::internal::NewSpace::end () const [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
end() [2/2]
virtual iterator v8::internal::NewSpace::end () [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
ExternalBackingStoreOverallBytes()
size_t v8::internal::NewSpace::ExternalBackingStoreOverallBytes () const [inline]
Definition at line 203 of file new-spaces.h.
                                                  {
    size_t result = 0;
    ForAll<ExternalBackingStoreType>(
        [this, &result](ExternalBackingStoreType type, int index) {
          result += ExternalBackingStoreBytes(type);
        });
    return result;
  }
References v8::internal::index, v8::base::internal::result, and v8::internal::tracing::type.
Referenced by v8::internal::Heap::AllocateExternalBackingStore().
first_allocatable_address()
virtual Address v8::internal::NewSpace::first_allocatable_address () const [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
GarbageCollectionEpilogue()
virtual void v8::internal::NewSpace::GarbageCollectionEpilogue () [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
Referenced by v8::internal::MarkCompactCollector::Finish(), and v8::internal::MinorMarkSweepCollector::Finish().
GarbageCollectionPrologue()
virtual void v8::internal::NewSpace::GarbageCollectionPrologue () [inline], [virtual]
Reimplemented in v8::internal::SemiSpaceNewSpace.
Definition at line 233 of file new-spaces.h.
{}
Grow()
virtual void v8::internal::NewSpace::Grow (size_t new_capacity) [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
Referenced by v8::internal::Heap::ExpandNewSpaceSize().
GrowToMaximumCapacityForTesting()
virtual void v8::internal::NewSpace::GrowToMaximumCapacityForTesting () [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
IsPromotionCandidate()
virtual bool v8::internal::NewSpace::IsPromotionCandidate (const MutablePageMetadata * page) const [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
MakeIterable()
virtual void v8::internal::NewSpace::MakeIterable () [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
Referenced by v8::internal::Heap::CreateMutableHeapObjects().
MaximumCapacity()
virtual size_t v8::internal::NewSpace::MaximumCapacity () const [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
Referenced by v8::internal::anonymous_namespace{heap.cc}::ComputeReducedNewSpaceSize(), v8::internal::Heap::ExpandNewSpaceSize(), v8::internal::PretenuringHandler::ProcessPretenuringFeedback(), and v8::internal::Heap::ShouldResizeNewSpace().
MinimumCapacity()
virtual size_t v8::internal::NewSpace::MinimumCapacity () const [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
Referenced by v8::internal::anonymous_namespace{heap.cc}::ComputeReducedNewSpaceSize().
mutex()
base::Mutex* v8::internal::NewSpace::mutex () [inline]
Definition at line 197 of file new-spaces.h.
{ return &mutex_; }
References mutex_.
Referenced by v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation(), and v8::internal::SemiSpaceNewSpaceAllocatorPolicy::FreeLinearAllocationArea().
PromotePageToOldSpace()
void v8::internal::NewSpace::PromotePageToOldSpace (PageMetadata * page, FreeMode free_mode)
Definition at line 404 of file new-spaces.cc.
                                                                           {
  DCHECK(!page->Chunk()->IsFlagSet(MemoryChunk::PAGE_NEW_OLD_PROMOTION));
  DCHECK(page->Chunk()->InYoungGeneration());
  RemovePage(page);
  PageMetadata* new_page = PageMetadata::ConvertNewToOld(page, free_mode);
  DCHECK(!new_page->Chunk()->InYoungGeneration());
  USE(new_page);
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::PageMetadata::ConvertNewToOld(), v8::internal::DCHECK(), v8::internal::MemoryChunk::InYoungGeneration(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::PAGE_NEW_OLD_PROMOTION, RemovePage(), and USE.
Referenced by v8::internal::EvacuateNewToOldSpacePageVisitor::Move(), v8::internal::anonymous_namespace{scavenger.cc}::QuarantinePinnedPages(), and v8::internal::MinorMarkSweepCollector::StartSweepNewSpace().
RemovePage()
virtual void v8::internal::NewSpace::RemovePage (PageMetadata * page) [protected], [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
Referenced by PromotePageToOldSpace().
TotalCapacity()
virtual size_t v8::internal::NewSpace::TotalCapacity () const [pure virtual]
Implemented in v8::internal::PagedNewSpace, and v8::internal::SemiSpaceNewSpace.
Referenced by v8::internal::anonymous_namespace{heap.cc}::ComputeReducedNewSpaceSize(), v8::internal::Heap::ExpandNewSpaceSize(), v8::internal::Heap::NewSpaceTargetCapacity(), v8::internal::GCTracer::PrintNVP(), v8::internal::StressScavengeObserver::RequestedGCDone(), v8::internal::Heap::ShouldResizeNewSpace(), and v8::internal::StressScavengeObserver::Step().
Member Data Documentation
kAllocationBufferParkingThreshold
const int v8::internal::NewSpace::kAllocationBufferParkingThreshold = 4 * KB [static], [protected]
Definition at line 241 of file new-spaces.h.
Referenced by v8::internal::SemiSpaceNewSpace::Allocate().
mutex_
base::Mutex v8::internal::NewSpace::mutex_ [protected]
Definition at line 243 of file new-spaces.h.
Referenced by mutex().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/new-spaces.h
/mnt/V8SourceCode/src/heap/new-spaces-inl.h
/mnt/V8SourceCode/src/heap/new-spaces.cc