cppgc::internal::ObjectAllocator Class Reference
#include <object-allocator.h>
Public Types
using AlignVal = std::align_val_t
Public Member Functions
ObjectAllocator (RawHeap &, PageBackend &, StatsCollector &, PreFinalizerHandler &, FatalOutOfMemoryHandler &, GarbageCollector &)
void * AllocateObject (size_t size, GCInfoIndex gcinfo)
void * AllocateObject (size_t size, AlignVal alignment, GCInfoIndex gcinfo)
void * AllocateObject (size_t size, GCInfoIndex gcinfo, CustomSpaceIndex space_index)
void * AllocateObject (size_t size, AlignVal alignment, GCInfoIndex gcinfo, CustomSpaceIndex space_index)
void ResetLinearAllocationBuffers ()
void MarkAllPagesAsYoung ()
Static Public Attributes
static constexpr size_t kSmallestSpaceSize = 32
Private Member Functions
bool in_disallow_gc_scope () const
void * AllocateObjectOnSpace (NormalPageSpace &, size_t, GCInfoIndex)
void * AllocateObjectOnSpace (NormalPageSpace &, size_t, AlignVal, GCInfoIndex)
void * OutOfLineAllocate (NormalPageSpace &, size_t, AlignVal, GCInfoIndex)
void V8_PRESERVE_MOST OutOfLineAllocateGCSafePoint (NormalPageSpace &, size_t, AlignVal, GCInfoIndex, void **)
void * OutOfLineAllocateImpl (NormalPageSpace &, size_t, AlignVal, GCInfoIndex)
bool TryRefillLinearAllocationBuffer (NormalPageSpace &, size_t)
bool TryRefillLinearAllocationBufferFromFreeList (NormalPageSpace &, size_t)
bool TryExpandAndRefillLinearAllocationBuffer (NormalPageSpace &)
Static Private Member Functions
static RawHeap::RegularSpaceType GetInitialSpaceIndexForSize (size_t size)
Private Attributes
RawHeap & raw_heap_
PageBackend & page_backend_
StatsCollector & stats_collector_
PreFinalizerHandler & prefinalizer_handler_
FatalOutOfMemoryHandler & oom_handler_
GarbageCollector & garbage_collector_
Detailed Description
Definition at line 40 of file object-allocator.h.
Member Typedef Documentation
AlignVal
using cppgc::internal::ObjectAllocator::AlignVal = std::align_val_t
Definition at line 42 of file object-allocator.h.
Constructor & Destructor Documentation
ObjectAllocator()
cppgc::internal::ObjectAllocator::ObjectAllocator (RawHeap & heap, PageBackend & page_backend, StatsCollector & stats_collector, PreFinalizerHandler & prefinalizer_handler, FatalOutOfMemoryHandler & oom_handler, GarbageCollector & garbage_collector)
Definition at line 135 of file object-allocator.cc.
    : raw_heap_(heap),
      page_backend_(page_backend),
      stats_collector_(stats_collector),
      prefinalizer_handler_(prefinalizer_handler),
      oom_handler_(oom_handler),
      garbage_collector_(garbage_collector) {}
Member Function Documentation
AllocateObject() [1/4]
void * cppgc::internal::ObjectAllocator::AllocateObject (size_t size, AlignVal alignment, GCInfoIndex gcinfo) [inline]
Definition at line 125 of file object-allocator.h.
                                                          {
  DCHECK(!in_disallow_gc_scope());
#ifdef V8_ENABLE_ALLOCATION_TIMEOUT
  TriggerGCOnAllocationTimeoutIfNeeded();
#endif // V8_ENABLE_ALLOCATION_TIMEOUT
  const size_t allocation_size =
      RoundUp<kAllocationGranularity>(size + sizeof(HeapObjectHeader));
  const RawHeap::RegularSpaceType type =
      GetInitialSpaceIndexForSize(allocation_size);
  return AllocateObjectOnSpace(NormalPageSpace::From(*raw_heap_.Space(type)),
                               allocation_size, alignment, gcinfo);
}
References AllocateObjectOnSpace(), DCHECK, cppgc::internal::NormalPageSpace::From(), GetInitialSpaceIndexForSize(), in_disallow_gc_scope(), raw_heap_, size(), cppgc::internal::RawHeap::Space(), and v8::internal::tracing::type.
AllocateObject() [2/4]
void * cppgc::internal::ObjectAllocator::AllocateObject (size_t size, AlignVal alignment, GCInfoIndex gcinfo, CustomSpaceIndex space_index) [inline]
Definition at line 152 of file object-allocator.h.
                                                                    {
  DCHECK(!in_disallow_gc_scope());
#ifdef V8_ENABLE_ALLOCATION_TIMEOUT
  TriggerGCOnAllocationTimeoutIfNeeded();
#endif // V8_ENABLE_ALLOCATION_TIMEOUT
  const size_t allocation_size =
      RoundUp<kAllocationGranularity>(size + sizeof(HeapObjectHeader));
  return AllocateObjectOnSpace(
      NormalPageSpace::From(*raw_heap_.CustomSpace(space_index)),
      allocation_size, alignment, gcinfo);
}
References AllocateObjectOnSpace(), cppgc::internal::RawHeap::CustomSpace(), DCHECK, cppgc::internal::NormalPageSpace::From(), in_disallow_gc_scope(), raw_heap_, and size().
AllocateObject() [3/4]
void * cppgc::internal::ObjectAllocator::AllocateObject (size_t size, GCInfoIndex gcinfo) [inline]
Definition at line 112 of file object-allocator.h.
                                                                     {
  DCHECK(!in_disallow_gc_scope());
#ifdef V8_ENABLE_ALLOCATION_TIMEOUT
  TriggerGCOnAllocationTimeoutIfNeeded();
#endif // V8_ENABLE_ALLOCATION_TIMEOUT
  const size_t allocation_size =
      RoundUp<kAllocationGranularity>(size + sizeof(HeapObjectHeader));
  const RawHeap::RegularSpaceType type =
      GetInitialSpaceIndexForSize(allocation_size);
  return AllocateObjectOnSpace(NormalPageSpace::From(*raw_heap_.Space(type)),
                               allocation_size, gcinfo);
}
References AllocateObjectOnSpace(), DCHECK, cppgc::internal::NormalPageSpace::From(), GetInitialSpaceIndexForSize(), in_disallow_gc_scope(), raw_heap_, size(), cppgc::internal::RawHeap::Space(), and v8::internal::tracing::type.
AllocateObject() [4/4]
void * cppgc::internal::ObjectAllocator::AllocateObject (size_t size, GCInfoIndex gcinfo, CustomSpaceIndex space_index) [inline]
Definition at line 139 of file object-allocator.h.
                                                                    {
  DCHECK(!in_disallow_gc_scope());
#ifdef V8_ENABLE_ALLOCATION_TIMEOUT
  TriggerGCOnAllocationTimeoutIfNeeded();
#endif // V8_ENABLE_ALLOCATION_TIMEOUT
  const size_t allocation_size =
      RoundUp<kAllocationGranularity>(size + sizeof(HeapObjectHeader));
  return AllocateObjectOnSpace(
      NormalPageSpace::From(*raw_heap_.CustomSpace(space_index)),
      allocation_size, gcinfo);
}
References AllocateObjectOnSpace(), cppgc::internal::RawHeap::CustomSpace(), DCHECK, cppgc::internal::NormalPageSpace::From(), in_disallow_gc_scope(), raw_heap_, and size().
AllocateObjectOnSpace() [1/2]
void * cppgc::internal::ObjectAllocator::AllocateObjectOnSpace (NormalPageSpace & space, size_t size, AlignVal alignment, GCInfoIndex gcinfo) [inline], [private]
Definition at line 187 of file object-allocator.h.
                                                                 {
  // The APIs are set up to support general alignment. Since we want to keep
  // track of the actual usage there the alignment support currently only covers
  // double-world alignment (8 bytes on 32bit and 16 bytes on 64bit
  // architectures). This is enforced on the public API via static_asserts
  // against alignof(T).
  static_assert(2 * kAllocationGranularity ==
                api_constants::kMaxSupportedAlignment);
  static_assert(kAllocationGranularity == sizeof(HeapObjectHeader));
  static_assert(kAllocationGranularity ==
                api_constants::kAllocationGranularity);
  DCHECK_EQ(2 * sizeof(HeapObjectHeader), static_cast<size_t>(alignment));
  constexpr size_t kAlignment = 2 * kAllocationGranularity;
  constexpr size_t kAlignmentMask = kAlignment - 1;
  constexpr size_t kPaddingSize = kAlignment - sizeof(HeapObjectHeader);
  NormalPageSpace::LinearAllocationBuffer& current_lab =
      space.linear_allocation_buffer();
  const size_t current_lab_size = current_lab.size();
  // Case 1: The LAB fits the request and the LAB start is already properly
  // aligned.
  bool lab_allocation_will_succeed =
      current_lab_size >= size &&
      (reinterpret_cast<uintptr_t>(current_lab.start() +
                                   sizeof(HeapObjectHeader)) &
       kAlignmentMask) == 0;
  // Case 2: The LAB fits an extended request to manually align the second
  // allocation.
  if (!lab_allocation_will_succeed &&
      (current_lab_size >= (size + kPaddingSize))) {
    void* filler_memory = current_lab.Allocate(kPaddingSize);
    auto& filler = Filler::CreateAt(filler_memory, kPaddingSize);
    NormalPage::From(BasePage::FromPayload(&filler))
        ->object_start_bitmap()
        .SetBit<AccessMode::kAtomic>(reinterpret_cast<ConstAddress>(&filler));
    lab_allocation_will_succeed = true;
  }
  if (V8_UNLIKELY(!lab_allocation_will_succeed)) {
    return OutOfLineAllocate(space, size, alignment, gcinfo);
  }
  void* object = AllocateObjectOnSpace(space, size, gcinfo);
  DCHECK_NOT_NULL(object);
  DCHECK_EQ(0u, reinterpret_cast<uintptr_t>(object) & kAlignmentMask);
  return object;
}
References AllocateObjectOnSpace(), cppgc::internal::Filler::CreateAt(), DCHECK_EQ, DCHECK_NOT_NULL, cppgc::internal::NormalPage::From(), cppgc::internal::BasePage::FromPayload(), v8::kAlignmentMask, cppgc::internal::api_constants::kAllocationGranularity, cppgc::internal::kAllocationGranularity, cppgc::internal::kAtomic, cppgc::internal::api_constants::kMaxSupportedAlignment, cppgc::internal::NormalPage::object_start_bitmap(), OutOfLineAllocate(), cppgc::internal::PlatformAwareObjectStartBitmap::SetBit(), size(), space, and V8_UNLIKELY.
AllocateObjectOnSpace() [2/2]
void * cppgc::internal::ObjectAllocator::AllocateObjectOnSpace (NormalPageSpace & space, size_t size, GCInfoIndex gcinfo) [inline], [private]
Definition at line 235 of file object-allocator.h.
                                                                              {
  DCHECK_LT(0u, gcinfo);
  NormalPageSpace::LinearAllocationBuffer& current_lab =
      space.linear_allocation_buffer();
  if (V8_UNLIKELY(current_lab.size() < size)) {
    return OutOfLineAllocate(
        space, size, static_cast<AlignVal>(kAllocationGranularity), gcinfo);
  }
  void* raw = current_lab.Allocate(size);
#if !defined(V8_USE_MEMORY_SANITIZER) && !defined(V8_USE_ADDRESS_SANITIZER) && \
    DEBUG
  // For debug builds, unzap only the payload.
  SetMemoryAccessible(static_cast<char*>(raw) + sizeof(HeapObjectHeader),
                      size - sizeof(HeapObjectHeader));
#else
  SetMemoryAccessible(raw, size);
#endif
  auto* header = new (raw) HeapObjectHeader(size, gcinfo);
  // The marker needs to find the object start concurrently.
  NormalPage::From(BasePage::FromPayload(header))
      ->object_start_bitmap()
      .SetBit<AccessMode::kAtomic>(reinterpret_cast<ConstAddress>(header));
  return header->ObjectStart();
}
References cppgc::internal::NormalPageSpace::LinearAllocationBuffer::Allocate(), DCHECK_LT, cppgc::internal::NormalPage::From(), cppgc::internal::BasePage::FromPayload(), cppgc::internal::kAllocationGranularity, cppgc::internal::kAtomic, cppgc::internal::NormalPage::object_start_bitmap(), OutOfLineAllocate(), cppgc::internal::PlatformAwareObjectStartBitmap::SetBit(), cppgc::internal::SetMemoryAccessible(), cppgc::internal::NormalPageSpace::LinearAllocationBuffer::size(), size(), space, and V8_UNLIKELY.
Referenced by AllocateObject(), AllocateObjectOnSpace(), and OutOfLineAllocateImpl().
GetInitialSpaceIndexForSize()
RawHeap::RegularSpaceType cppgc::internal::ObjectAllocator::GetInitialSpaceIndexForSize (size_t size) [inline], [static], [private]
Definition at line 167 of file object-allocator.h.
                 {
  static_assert(kSmallestSpaceSize == 32,
                "should be half the next larger size");
  if (size < 64) {
    if (size < kSmallestSpaceSize) return RawHeap::RegularSpaceType::kNormal1;
    return RawHeap::RegularSpaceType::kNormal2;
  }
  if (size < 128) return RawHeap::RegularSpaceType::kNormal3;
  return RawHeap::RegularSpaceType::kNormal4;
}
References cppgc::internal::RawHeap::kNormal1, cppgc::internal::RawHeap::kNormal2, cppgc::internal::RawHeap::kNormal3, cppgc::internal::RawHeap::kNormal4, kSmallestSpaceSize, and size().
Referenced by AllocateObject().
in_disallow_gc_scope()
bool cppgc::internal::ObjectAllocator::in_disallow_gc_scope () const [private]
Definition at line 370 of file object-allocator.cc.
                                                 {
  return raw_heap_.heap()->IsGCForbidden();
}
References cppgc::internal::RawHeap::heap(), cppgc::internal::HeapBase::IsGCForbidden(), and raw_heap_.
Referenced by AllocateObject(), and OutOfLineAllocateImpl().
MarkAllPagesAsYoung()
void cppgc::internal::ObjectAllocator::MarkAllPagesAsYoung ()
Definition at line 350 of file object-allocator.cc.
                                          {
  class YoungMarker : public HeapVisitor<YoungMarker> {
   public:
    bool VisitNormalPage(NormalPage& page) {
      MarkRangeAsYoung(page, page.PayloadStart(), page.PayloadEnd());
      return true;
    }
    bool VisitLargePage(LargePage& page) {
      MarkRangeAsYoung(page, page.PayloadStart(), page.PayloadEnd());
      return true;
    }
  } visitor;
  USE(visitor);
#if defined(CPPGC_YOUNG_GENERATION)
  visitor.Traverse(raw_heap_);
#endif // defined(CPPGC_YOUNG_GENERATION)
}
References cppgc::internal::anonymous_namespace{object-allocator.cc}::MarkRangeAsYoung(), cppgc::internal::NormalPage::PayloadEnd(), cppgc::internal::LargePage::PayloadEnd(), cppgc::internal::NormalPage::PayloadStart(), cppgc::internal::LargePage::PayloadStart(), raw_heap_, and USE.
OutOfLineAllocate()
void * cppgc::internal::ObjectAllocator::OutOfLineAllocate (NormalPageSpace & space, size_t size, AlignVal alignment, GCInfoIndex gcinfo) [inline], [private]
Definition at line 179 of file object-allocator.h.
                                                             {
  void* object;
  OutOfLineAllocateGCSafePoint(space, size, alignment, gcinfo, &object);
  return object;
}
References OutOfLineAllocateGCSafePoint(), size(), and space.
Referenced by AllocateObjectOnSpace().
OutOfLineAllocateGCSafePoint()
void cppgc::internal::ObjectAllocator::OutOfLineAllocateGCSafePoint (NormalPageSpace & space, size_t size, AlignVal alignment, GCInfoIndex gcinfo, void ** object) [private]
Definition at line 147 of file object-allocator.cc.
                                                                  {
  *object = OutOfLineAllocateImpl(space, size, alignment, gcinfo);
  stats_collector_.NotifySafePointForConservativeCollection();
  if (prefinalizer_handler_.IsInvokingPreFinalizers()) {
    // Objects allocated during pre finalizers should be allocated as black
    // since marking is already done. Atomics are not needed because there is
    // no concurrent marking in the background.
    HeapObjectHeader::FromObject(*object).MarkNonAtomic();
    // Resetting the allocation buffer forces all further allocations in pre
    // finalizers to go through this slow path.
    ReplaceLinearAllocationBuffer(space, stats_collector_, nullptr, 0);
    prefinalizer_handler_.NotifyAllocationInPrefinalizer(size);
  }
}
References cppgc::internal::HeapObjectHeader::FromObject(), cppgc::internal::PreFinalizerHandler::IsInvokingPreFinalizers(), cppgc::internal::HeapObjectHeader::MarkNonAtomic(), cppgc::internal::PreFinalizerHandler::NotifyAllocationInPrefinalizer(), cppgc::internal::StatsCollector::NotifySafePointForConservativeCollection(), OutOfLineAllocateImpl(), prefinalizer_handler_, cppgc::internal::anonymous_namespace{object-allocator.cc}::ReplaceLinearAllocationBuffer(), size(), space, and stats_collector_.
Referenced by OutOfLineAllocate().
OutOfLineAllocateImpl()
void * cppgc::internal::ObjectAllocator::OutOfLineAllocateImpl (NormalPageSpace & space, size_t size, AlignVal alignment, GCInfoIndex gcinfo) [private]
Definition at line 174 of file object-allocator.cc.
                                                                 {
  DCHECK_EQ(0, size & kAllocationMask);
  DCHECK_LE(kFreeListEntrySize, size);
  // Out-of-line allocation allows for checking this is all situations.
  CHECK(!in_disallow_gc_scope());
  // If this allocation is big enough, allocate a large object.
  if (size >= kLargeObjectSizeThreshold) {
    auto& large_space = LargePageSpace::From(
        *raw_heap_.Space(RawHeap::RegularSpaceType::kLarge));
    // LargePage has a natural alignment that already satisfies
    // `kMaxSupportedAlignment`.
    void* result = TryAllocateLargeObject(page_backend_, large_space,
                                          stats_collector_, size, gcinfo);
    if (!result) {
      for (int i = 0; i < 2; i++) {
        auto config = kOnAllocationFailureGCConfig;
        garbage_collector_.CollectGarbage(config);
        result = TryAllocateLargeObject(page_backend_, large_space,
                                        stats_collector_, size, gcinfo);
        if (result) {
          return result;
        }
      }
#if defined(CPPGC_CAGED_HEAP)
      const auto last_alloc_status =
          CagedHeap::Instance().page_allocator().get_last_allocation_status();
      const std::string suffix =
          v8::base::BoundedPageAllocator::AllocationStatusToString(
              last_alloc_status);
      oom_handler_("Oilpan: Large allocation. " + suffix);
#else
      oom_handler_("Oilpan: Large allocation.");
#endif
    }
    return result;
  }
  size_t request_size = size;
  // Adjust size to be able to accommodate alignment.
  const size_t dynamic_alignment = static_cast<size_t>(alignment);
  if (dynamic_alignment != kAllocationGranularity) {
    CHECK_EQ(2 * sizeof(HeapObjectHeader), dynamic_alignment);
    request_size += kAllocationGranularity;
  }
  bool success = TryRefillLinearAllocationBuffer(space, request_size);
  if (!success) {
    for (int i = 0; i < 2; i++) {
      auto config = kOnAllocationFailureGCConfig;
      garbage_collector_.CollectGarbage(config);
      success = TryRefillLinearAllocationBuffer(space, request_size);
      if (success) {
        break;
      }
    }
    if (!success) {
#if defined(CPPGC_CAGED_HEAP)
      const auto last_alloc_status =
          CagedHeap::Instance().page_allocator().get_last_allocation_status();
      const std::string suffix =
          v8::base::BoundedPageAllocator::AllocationStatusToString(
              last_alloc_status);
      oom_handler_("Oilpan: Normal allocation. " + suffix);
#else
      oom_handler_("Oilpan: Normal allocation.");
#endif
    }
  }
  // The allocation must succeed, as we just refilled the LAB.
  void* result = (dynamic_alignment == kAllocationGranularity)
                     ? AllocateObjectOnSpace(space, size, gcinfo)
                     : AllocateObjectOnSpace(space, size, alignment, gcinfo);
  CHECK(result);
  return result;
}
References AllocateObjectOnSpace(), v8::base::BoundedPageAllocator::AllocationStatusToString(), CHECK, CHECK_EQ, cppgc::internal::GarbageCollector::CollectGarbage(), DCHECK_EQ, DCHECK_LE, cppgc::internal::LargePageSpace::From(), garbage_collector_, v8::base::BoundedPageAllocator::get_last_allocation_status(), in_disallow_gc_scope(), cppgc::internal::CagedHeap::Instance(), cppgc::internal::kAllocationGranularity, cppgc::internal::kAllocationMask, cppgc::internal::kFreeListEntrySize, cppgc::internal::RawHeap::kLarge, cppgc::internal::kLargeObjectSizeThreshold, cppgc::internal::anonymous_namespace{object-allocator.cc}::kOnAllocationFailureGCConfig, oom_handler_, cppgc::internal::CagedHeap::page_allocator(), page_backend_, raw_heap_, v8::base::internal::result, size(), space, cppgc::internal::RawHeap::Space(), stats_collector_, v8::internal::string, cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObject(), and TryRefillLinearAllocationBuffer().
Referenced by OutOfLineAllocateGCSafePoint().
ResetLinearAllocationBuffers()
void cppgc::internal::ObjectAllocator::ResetLinearAllocationBuffers ()
Definition at line 331 of file object-allocator.cc.
                                                   {
  class Resetter : public HeapVisitor<Resetter> {
   public:
    explicit Resetter(StatsCollector& stats) : stats_collector_(stats) {}
    bool VisitLargePageSpace(LargePageSpace&) { return true; }
    bool VisitNormalPageSpace(NormalPageSpace& space) {
      ReplaceLinearAllocationBuffer(space, stats_collector_, nullptr, 0);
      return true;
    }
   private:
    StatsCollector& stats_collector_;
  } visitor(stats_collector_);
  visitor.Traverse(raw_heap_);
}
References raw_heap_, cppgc::internal::anonymous_namespace{object-allocator.cc}::ReplaceLinearAllocationBuffer(), space, and stats_collector_.
Referenced by cppgc::internal::HeapBase::CollectStatistics(), cppgc::internal::PreFinalizerHandler::InvokePreFinalizers(), cppgc::internal::HeapBase::Terminate(), and cppgc::internal::MarkerBase::VisitLocalRoots().
TryExpandAndRefillLinearAllocationBuffer()
bool cppgc::internal::ObjectAllocator::TryExpandAndRefillLinearAllocationBuffer (NormalPageSpace & space) [private]
Definition at line 254 of file object-allocator.cc.
                            {
  auto* const new_page = NormalPage::TryCreate(page_backend_, space);
  if (!new_page) return false;
  space.AddPage(new_page);
  // Set linear allocation buffer to new page.
  ReplaceLinearAllocationBuffer(space, stats_collector_,
                                new_page->PayloadStart(),
                                new_page->PayloadSize());
  return true;
}
References page_backend_, cppgc::internal::anonymous_namespace{object-allocator.cc}::ReplaceLinearAllocationBuffer(), space, stats_collector_, and cppgc::internal::NormalPage::TryCreate().
Referenced by TryRefillLinearAllocationBuffer().
TryRefillLinearAllocationBuffer()
bool cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBuffer (NormalPageSpace & space, size_t size) [private]
Definition at line 267 of file object-allocator.cc.
                                                                   {
  // Try to allocate from the freelist.
  if (TryRefillLinearAllocationBufferFromFreeList(space, size)) return true;
  Sweeper& sweeper = raw_heap_.heap()->sweeper();
  // Lazily sweep pages of this heap. This is not exhaustive to limit jank on
  // allocation. Allocation from the free list may still fail as actual buckets
  // are not exhaustively searched for a suitable block. Instead, buckets are
  // tested from larger sizes that are guaranteed to fit the block to smaller
  // bucket sizes that may only potentially fit the block. For the bucket that
  // may exactly fit the allocation of `size` bytes (no overallocation), only
  // the first entry is checked.
  if (sweeper.SweepForAllocationIfRunning(
          &space, size, v8::base::TimeDelta::FromMicroseconds(500)) &&
      TryRefillLinearAllocationBufferFromFreeList(space, size)) {
    return true;
  }
  // Sweeping was off or did not yield in any memory within limited
  // contributing. We expand at this point as that's cheaper than possibly
  // continuing sweeping the whole heap.
  if (TryExpandAndRefillLinearAllocationBuffer(space)) return true;
  // Expansion failed. Before finishing all sweeping, finish sweeping of a given
  // space which is cheaper.
  if (sweeper.SweepForAllocationIfRunning(&space, size,
                                          v8::base::TimeDelta::Max()) &&
      TryRefillLinearAllocationBufferFromFreeList(space, size)) {
    return true;
  }
  // Heap expansion and sweeping of a space failed. At this point the caller
  // could run OOM or do a full GC which needs to finish sweeping if it's
  // running. Hence, we may as well finish sweeping here. Note that this is
  // possibly very expensive but not more expensive than running a full GC as
  // the alternative is OOM.
  if (sweeper.FinishIfRunning()) {
    // Sweeping may have added memory to the free list.
    if (TryRefillLinearAllocationBufferFromFreeList(space, size)) return true;
    // Sweeping may have freed pages completely.
    if (TryExpandAndRefillLinearAllocationBuffer(space)) return true;
  }
  return false;
}
References cppgc::internal::Sweeper::FinishIfRunning(), v8::base::TimeDelta::FromMicroseconds(), cppgc::internal::RawHeap::heap(), v8::base::TimeDelta::Max(), raw_heap_, size(), space, cppgc::internal::HeapBase::sweeper(), cppgc::internal::Sweeper::SweepForAllocationIfRunning(), TryExpandAndRefillLinearAllocationBuffer(), and TryRefillLinearAllocationBufferFromFreeList().
Referenced by OutOfLineAllocateImpl().
TryRefillLinearAllocationBufferFromFreeList()
bool cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBufferFromFreeList (NormalPageSpace & space, size_t size) [private]
Definition at line 314 of file object-allocator.cc.
                                         {
  const FreeList::Block entry = space.free_list().Allocate(size);
  if (!entry.address) return false;
  // Assume discarded memory on that page is now zero.
  auto& page = *NormalPage::From(BasePage::FromPayload(entry.address));
  if (page.discarded_memory()) {
    stats_collector_.DecrementDiscardedMemory(page.discarded_memory());
    page.ResetDiscardedMemory();
  }
  ReplaceLinearAllocationBuffer(
      space, stats_collector_, static_cast<Address>(entry.address), entry.size);
  return true;
}
References cppgc::internal::FreeList::Block::address, cppgc::internal::StatsCollector::DecrementDiscardedMemory(), cppgc::internal::NormalPage::From(), cppgc::internal::BasePage::FromPayload(), cppgc::internal::anonymous_namespace{object-allocator.cc}::ReplaceLinearAllocationBuffer(), size(), cppgc::internal::FreeList::Block::size, space, and stats_collector_.
Referenced by TryRefillLinearAllocationBuffer().
Member Data Documentation
garbage_collector_
GarbageCollector& cppgc::internal::ObjectAllocator::garbage_collector_ [private]
Definition at line 104 of file object-allocator.h.
Referenced by OutOfLineAllocateImpl().
kSmallestSpaceSize
constexpr size_t cppgc::internal::ObjectAllocator::kSmallestSpaceSize = 32 [static], [constexpr]
Definition at line 43 of file object-allocator.h.
Referenced by GetInitialSpaceIndexForSize(), and cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink().
oom_handler_
FatalOutOfMemoryHandler& cppgc::internal::ObjectAllocator::oom_handler_ [private]
Definition at line 103 of file object-allocator.h.
Referenced by OutOfLineAllocateImpl().
page_backend_
PageBackend& cppgc::internal::ObjectAllocator::page_backend_ [private]
Definition at line 100 of file object-allocator.h.
Referenced by OutOfLineAllocateImpl(), and TryExpandAndRefillLinearAllocationBuffer().
prefinalizer_handler_
PreFinalizerHandler& cppgc::internal::ObjectAllocator::prefinalizer_handler_ [private]
Definition at line 102 of file object-allocator.h.
Referenced by OutOfLineAllocateGCSafePoint().
raw_heap_
RawHeap& cppgc::internal::ObjectAllocator::raw_heap_ [private]
Definition at line 99 of file object-allocator.h.
Referenced by AllocateObject(), in_disallow_gc_scope(), MarkAllPagesAsYoung(), OutOfLineAllocateImpl(), ResetLinearAllocationBuffers(), and TryRefillLinearAllocationBuffer().
stats_collector_
StatsCollector& cppgc::internal::ObjectAllocator::stats_collector_ [private]
Definition at line 101 of file object-allocator.h.
Referenced by OutOfLineAllocateGCSafePoint(), OutOfLineAllocateImpl(), ResetLinearAllocationBuffers(), TryExpandAndRefillLinearAllocationBuffer(), and TryRefillLinearAllocationBufferFromFreeList().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/object-allocator.h
/mnt/V8SourceCode/src/heap/cppgc/object-allocator.cc