v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet Class Reference
Public Member Functions
AnnotationSet (ParseResultIterator *iter, const std::set< std::string > &allowed_without_param, const std::set< std::string > &allowed_with_param)
bool Contains (const std::string &s) const
std::optional< std::string > GetStringParam (const std::string &s) const
std::optional< int32_t > GetIntParam (const std::string &s) const
Private Attributes
std::set< std::string > set_
std::map< std::string, std::pair< AnnotationParameter, SourcePosition > > map_
Detailed Description
Definition at line 671 of file torque-parser.cc.
Constructor & Destructor Documentation
AnnotationSet()
v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::AnnotationSet (ParseResultIterator * iter, const std::set< std::string > & allowed_without_param, const std::set< std::string > & allowed_with_param) [inline]
Definition at line 673 of file torque-parser.cc.
                                                             {
    auto list = iter->NextAs<std::vector<Annotation>>();
    for (const Annotation& a : list) {
      if (a.param.has_value()) {
        if (allowed_with_param.find(a.name->value) ==
            allowed_with_param.end()) {
          const char* error_message =
              allowed_without_param.find(a.name->value) ==
                      allowed_without_param.end()
                  ? " is not allowed here"
                  : " cannot have parameter here";
          Lint("Annotation ", a.name->value, error_message)
              .Position(a.name->pos);
        }
        if (!map_.insert({a.name->value, {*a.param, a.name->pos}}).second) {
          Lint("Duplicate annotation ", a.name->value).Position(a.name->pos);
        }
      } else {
        if (allowed_without_param.find(a.name->value) ==
            allowed_without_param.end()) {
          const char* error_message =
              allowed_with_param.find(a.name->value) == allowed_with_param.end()
                  ? " is not allowed here"
                  : " requires a parameter here";
          Lint("Annotation ", a.name->value, error_message)
              .Position(a.name->pos);
        }
        if (!set_.insert(a.name->value).second) {
          Lint("Duplicate annotation ", a.name->value).Position(a.name->pos);
        }
      }
    }
  }
References v8::internal::torque::Lint(), v8::internal::torque::ParseResultIterator::NextAs(), and v8::internal::torque::MessageBuilder::Position().
Member Function Documentation
Contains()
bool v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::Contains (const std::string & s) const [inline]
Definition at line 709 of file torque-parser.cc.
                                          {
    return set_.find(s) != set_.end();
  }
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassField(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueBuiltinDeclaration(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueMacroDeclaration().
GetIntParam()
std::optional<int32_t> v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::GetIntParam (const std::string & s) const [inline]
Definition at line 723 of file torque-parser.cc.
                                                             {
    auto it = map_.find(s);
    if (it == map_.end()) {
      return {};
    }
    if (!it->second.first.is_int) {
      Error("Annotation ", s, " requires an int parameter but has a string")
          .Position(it->second.second);
    }
    return it->second.first.int_value;
  }
References v8::internal::torque::Error(), and v8::internal::torque::MessageBuilder::Position().
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::GetAnnotationValue().
GetStringParam()
std::optional<std::string> v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::GetStringParam (const std::string & s) const [inline]
Definition at line 712 of file torque-parser.cc.
                                                                  {
    auto it = map_.find(s);
    if (it == map_.end()) {
      return {};
    }
    if (it->second.first.is_int) {
      Error("Annotation ", s, " requires a string parameter but has an int")
          .Position(it->second.second);
    }
    return it->second.first.string_value;
  }
References v8::internal::torque::Error(), and v8::internal::torque::MessageBuilder::Position().
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassField(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumEntry(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueBuiltinDeclaration(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::ProcessIfAnnotation().
Member Data Documentation
map_
std::map<std::string, std::pair<AnnotationParameter, SourcePosition> > v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::map_ [private]
Definition at line 737 of file torque-parser.cc.
set_
std::set<std::string> v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::set_ [private]
Definition at line 736 of file torque-parser.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/torque-parser.cc