v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders > Class Template Reference
#include <v8-fast-api-calls.h>
Classes
struct GetArgBuilder
struct GetArgBuilder< false, N, Flags... >
struct GetArgBuilder< true, N, Flags... >
Public Member Functions
constexpr CFunctionBuilderWithFunction (const void *fn)
template<CTypeInfo::Flags... Flags>
constexpr auto Ret ()
template<unsigned int N, CTypeInfo::Flags... Flags>
constexpr auto Arg ()
template<typename Ret , typename... Args>
auto Patch (Ret(*patching_func)(Args...))
template<CFunctionInfo::Int64Representation Representation = CFunctionInfo::Int64Representation::kNumber>
auto Build ()
Private Member Functions
template<unsigned int N, CTypeInfo::Flags... Flags, size_t... I>
constexpr auto ArgImpl (std::index_sequence< I... >)
Private Attributes
const void * fn_
Detailed Description
template<typename RetBuilder, typename... ArgBuilders>
class v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >
Definition at line 672 of file v8-fast-api-calls.h.
Constructor & Destructor Documentation
CFunctionBuilderWithFunction()
template<typename RetBuilder , typename... ArgBuilders>
constexpr v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::CFunctionBuilderWithFunction (const void * fn) [inline], [explicit], [constexpr]
Definition at line 674 of file v8-fast-api-calls.h.
: fn_(fn) {}
Member Function Documentation
Arg()
template<typename RetBuilder , typename... ArgBuilders>
template<unsigned int N, CTypeInfo::Flags... Flags>
constexpr auto v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::Arg () [inline], [constexpr]
Definition at line 684 of file v8-fast-api-calls.h.
                       {
    // Return a copy of the builder with the Nth arg builder merged with
    // template parameter pack Flags.
    return ArgImpl<N, Flags...>(
        std::make_index_sequence<sizeof...(ArgBuilders)>());
  }
References v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::ArgImpl(), v8::internal::Flags(), and v8::internal::N.
ArgImpl()
template<typename RetBuilder , typename... ArgBuilders>
template<unsigned int N, CTypeInfo::Flags... Flags, size_t... I>
constexpr auto v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::ArgImpl (std::index_sequence< I... >) [inline], [constexpr], [private]
Definition at line 734 of file v8-fast-api-calls.h.
                                                  {
    return CFunctionBuilderWithFunction<
        RetBuilder, typename GetArgBuilder<N == I, I, Flags...>::type...>(fn_);
  }
References v8::internal::Flags(), v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::fn_, v8::internal::I, v8::internal::N, and v8::internal::tracing::type.
Referenced by v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::Arg().
Build()
template<typename RetBuilder , typename... ArgBuilders>
template<CFunctionInfo::Int64Representation Representation = CFunctionInfo::Int64Representation::kNumber>
auto v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::Build () [inline]
Definition at line 703 of file v8-fast-api-calls.h.
               {
    static CFunctionInfoImpl<Representation, RetBuilder, ArgBuilders...>
        instance;
    return CFunction(fn_, &instance);
  }
References v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::fn_.
Patch()
template<typename RetBuilder , typename... ArgBuilders>
template<typename Ret , typename... Args>
auto v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::Patch (Ret(*)(Args...) patching_func) [inline]
Definition at line 693 of file v8-fast-api-calls.h.
                                            {
    static_assert(
        sizeof...(Args) == sizeof...(ArgBuilders),
        "The patching function must have the same number of arguments.");
    fn_ = reinterpret_cast<void*>(patching_func);
    return *this;
  }
References v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::fn_.
Ret()
template<typename RetBuilder , typename... ArgBuilders>
template<CTypeInfo::Flags... Flags>
constexpr auto v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::Ret () [inline], [constexpr]
Definition at line 677 of file v8-fast-api-calls.h.
                       {
    return CFunctionBuilderWithFunction<
        CTypeInfoBuilder<typename RetBuilder::BaseType, Flags...>,
        ArgBuilders...>(fn_);
  }
References v8::internal::Flags(), and v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::fn_.
Member Data Documentation
fn_
template<typename RetBuilder , typename... ArgBuilders>
const void* v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::fn_ [private]
Definition at line 739 of file v8-fast-api-calls.h.
Referenced by v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::ArgImpl(), v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::Build(), v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::Patch(), and v8::internal::CFunctionBuilderWithFunction< RetBuilder, ArgBuilders >::Ret().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-fast-api-calls.h