v8::internal::GlobalDictionary Class Reference
#include <dictionary.h>
Public Member Functions
Tagged< Object > ValueAt (InternalIndex entry)
Tagged< Object > ValueAt (PtrComprCageBase cage_base, InternalIndex entry)
Tagged< PropertyCell > CellAt (InternalIndex entry)
Tagged< PropertyCell > CellAt (PtrComprCageBase cage_base, InternalIndex entry)
void SetEntry (InternalIndex entry, Tagged< Object > key, Tagged< Object > value, PropertyDetails details)
void ClearEntry (InternalIndex entry)
Tagged< Name > NameAt (InternalIndex entry)
Tagged< Name > NameAt (PtrComprCageBase cage_base, InternalIndex entry)
void ValueAtPut (InternalIndex entry, Tagged< Object > value)
std::optional< Tagged< PropertyCell > > TryFindPropertyCellForConcurrentLookupIterator (Isolate *isolate, DirectHandle< Name > name, RelaxedLoadTag tag)
Static Public Member Functions
static DirectHandle< Map > GetMap (RootsTable &roots)
Detailed Description
Definition at line 338 of file dictionary.h.
Member Function Documentation
CellAt() [1/2]
Tagged<PropertyCell> v8::internal::GlobalDictionary::CellAt (InternalIndex entry) [inline]
Referenced by v8::internal::BIT_FIELD_ACCESSORS(), NameAt(), and ValueAt().
CellAt() [2/2]
Tagged< PropertyCell > v8::internal::GlobalDictionary::CellAt (PtrComprCageBase cage_base, InternalIndex entry) [inline]
Definition at line 244 of file dictionary-inl.h.
                                                                   {
  DCHECK(IsPropertyCell(KeyAt(cage_base, entry), cage_base));
  return Cast<PropertyCell>(KeyAt(cage_base, entry));
}
References v8::internal::DCHECK().
ClearEntry()
void v8::internal::GlobalDictionary::ClearEntry (InternalIndex entry) [inline]
Definition at line 277 of file dictionary-inl.h.
                                                     {
  Tagged<Hole> the_hole = GetReadOnlyRoots().the_hole_value();
  set(EntryToIndex(entry) + kEntryKeyIndex, the_hole);
}
References v8::internal::GetReadOnlyRoots().
GetMap()
DirectHandle< Map > v8::internal::GlobalDictionary::GetMap (RootsTable & roots) [inline], [static]
Definition at line 210 of file dictionary-inl.h.
                                                            {
  return roots.global_dictionary_map();
}
NameAt() [1/2]
Tagged< Name > v8::internal::GlobalDictionary::NameAt (InternalIndex entry) [inline]
Definition at line 250 of file dictionary-inl.h.
                                                         {
  PtrComprCageBase cage_base = GetPtrComprCageBase();
  return NameAt(cage_base, entry);
}
References v8::internal::GetPtrComprCageBase().
NameAt() [2/2]
Tagged< Name > v8::internal::GlobalDictionary::NameAt (PtrComprCageBase cage_base, InternalIndex entry) [inline]
Definition at line 255 of file dictionary-inl.h.
                                                           {
  return CellAt(cage_base, entry)->name(cage_base);
}
References CellAt().
SetEntry()
void v8::internal::GlobalDictionary::SetEntry (InternalIndex entry, Tagged< Object > key, Tagged< Object > value, PropertyDetails details) [inline]
Definition at line 270 of file dictionary-inl.h.
                                                                               {
  DCHECK_EQ(key, Cast<PropertyCell>(value)->name());
  set(EntryToIndex(entry) + kEntryKeyIndex, value);
  DetailsAtPut(entry, details);
}
References DCHECK_EQ, v8::internal::key, v8::internal::name, and v8::internal::value.
TryFindPropertyCellForConcurrentLookupIterator()
std::optional< Tagged< PropertyCell > > v8::internal::GlobalDictionary::TryFindPropertyCellForConcurrentLookupIterator (Isolate * isolate, DirectHandle< Name > name, RelaxedLoadTag tag)
Definition at line 5617 of file objects.cc.
                                                                   {
  // This reimplements HashTable::FindEntry for use in a concurrent setting.
  // 1) Atomic loads.
  // 2) IsPendingAllocation checks.
  // 3) Return the PropertyCell value instead of the InternalIndex to avoid a
  // repeated load (unsafe with concurrent modifications).
  DisallowGarbageCollection no_gc;
  PtrComprCageBase cage_base{isolate};
  ReadOnlyRoots roots(isolate);
  const int32_t hash = TodoShape::Hash(roots, name);
  const uint32_t capacity = Capacity();
  uint32_t count = 1;
  Tagged<Object> undefined = roots.undefined_value();
  Tagged<Object> the_hole = roots.the_hole_value();
  // EnsureCapacity will guarantee the hash table is never full.
  for (InternalIndex entry = FirstProbe(hash, capacity);;
       entry = NextProbe(entry, count++, capacity)) {
    Tagged<Object> element = KeyAt(cage_base, entry, kRelaxedLoad);
    if (isolate->heap()->IsPendingAllocation(element)) return {};
    if (element == undefined) return {};
    if (TodoShape::kMatchNeedsHoleCheck && element == the_hole) continue;
    if (!TodoShape::IsMatch(name, element)) continue;
    CHECK(IsPropertyCell(element, cage_base));
    return Cast<PropertyCell>(element);
  }
}
References CHECK, v8::internal::Hash(), v8::internal::Isolate::heap(), v8::internal::Heap::IsPendingAllocation(), v8::kRelaxedLoad, v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::undefined.
ValueAt() [1/2]
Tagged< Object > v8::internal::GlobalDictionary::ValueAt (InternalIndex entry) [inline]
Definition at line 260 of file dictionary-inl.h.
                                                            {
  PtrComprCageBase cage_base = GetPtrComprCageBase();
  return ValueAt(cage_base, entry);
}
References v8::internal::GetPtrComprCageBase().
ValueAt() [2/2]
Tagged< Object > v8::internal::GlobalDictionary::ValueAt (PtrComprCageBase cage_base, InternalIndex entry) [inline]
Definition at line 265 of file dictionary-inl.h.
                                                              {
  return CellAt(cage_base, entry)->value(cage_base);
}
References CellAt().
ValueAtPut()
void v8::internal::GlobalDictionary::ValueAtPut (InternalIndex entry, Tagged< Object > value) [inline]
Definition at line 282 of file dictionary-inl.h.
                                                                           {
  set(EntryToIndex(entry), value);
}
References v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/dictionary.h
/mnt/V8SourceCode/src/objects/dictionary-inl.h
/mnt/V8SourceCode/src/objects/objects.cc