v8::internal::RegExpStackScope Class Reference
#include <regexp-stack.h>
Public Member Functions
RegExpStackScope (Isolate *isolate)
~RegExpStackScope ()
RegExpStackScope (const RegExpStackScope &)=delete
RegExpStackScope & operator= (const RegExpStackScope &)=delete
RegExpStack * stack () const
Private Attributes
RegExpStack *const regexp_stack_
const ptrdiff_t old_sp_top_delta_
Detailed Description
Definition at line 19 of file regexp-stack.h.
Constructor & Destructor Documentation
RegExpStackScope() [1/2]
v8::internal::RegExpStackScope::RegExpStackScope (Isolate * isolate) [explicit]
Definition at line 13 of file regexp-stack.cc.
    : regexp_stack_(isolate->regexp_stack()),
      old_sp_top_delta_(regexp_stack_->sp_top_delta()) {
  DCHECK(regexp_stack_->IsValid());
}
References v8::internal::DCHECK(), v8::internal::RegExpStack::IsValid(), and regexp_stack_.
 RegExpStackScope()
v8::internal::RegExpStackScope::~RegExpStackScope ()
Definition at line 19 of file regexp-stack.cc.
                                    {
  CHECK_EQ(old_sp_top_delta_, regexp_stack_->sp_top_delta());
  regexp_stack_->ResetIfEmpty();
}
References CHECK_EQ, old_sp_top_delta_, regexp_stack_, v8::internal::RegExpStack::ResetIfEmpty(), and v8::internal::RegExpStack::sp_top_delta().
RegExpStackScope() [2/2]
v8::internal::RegExpStackScope::RegExpStackScope (const RegExpStackScope &) [delete]
Member Function Documentation
operator=()
RegExpStackScope& v8::internal::RegExpStackScope::operator= (const RegExpStackScope &) [delete]
stack()
RegExpStack* v8::internal::RegExpStackScope::stack () const [inline]
Definition at line 29 of file regexp-stack.h.
{ return regexp_stack_; }
Member Data Documentation
old_sp_top_delta_
const ptrdiff_t v8::internal::RegExpStackScope::old_sp_top_delta_ [private]
Definition at line 33 of file regexp-stack.h.
Referenced by ~RegExpStackScope().
regexp_stack_
RegExpStack* const v8::internal::RegExpStackScope::regexp_stack_ [private]
Definition at line 32 of file regexp-stack.h.
Referenced by RegExpStackScope(), and ~RegExpStackScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-stack.h
/mnt/V8SourceCode/src/regexp/regexp-stack.cc