v8::internal::torque::ParseResultIterator Class Reference
#include <earley-parser.h>
Public Member Functions
ParseResultIterator (std::vector< ParseResult > results, MatchedInput matched_input)
ParseResultIterator (const ParseResultIterator &)=delete
ParseResultIterator & operator= (const ParseResultIterator &)=delete
ParseResult Next ()
template<class T >
T NextAs ()
bool HasNext () const
const MatchedInput & matched_input () const
Private Attributes
std::vector< ParseResult > results_
size_t i_ = 0
MatchedInput matched_input_
Detailed Description
Definition at line 161 of file earley-parser.h.
Constructor & Destructor Documentation
ParseResultIterator() [1/2]
v8::internal::torque::ParseResultIterator::ParseResultIterator (std::vector< ParseResult > results, MatchedInput matched_input) [inline], [explicit]
Definition at line 163 of file earley-parser.h.
      : results_(std::move(results)), matched_input_(matched_input) {}
ParseResultIterator() [2/2]
v8::internal::torque::ParseResultIterator::ParseResultIterator (const ParseResultIterator &) [delete]
Member Function Documentation
HasNext()
bool v8::internal::torque::ParseResultIterator::HasNext () const [inline]
Definition at line 178 of file earley-parser.h.
{ return i_ < results_.size(); }
References i_, and results_.
Referenced by v8::internal::torque::DefaultAction(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeVarDeclarationStatement(), and v8::internal::torque::Rule::RunAction().
matched_input()
const MatchedInput& v8::internal::torque::ParseResultIterator::matched_input () const [inline]
Definition at line 180 of file earley-parser.h.
{ return matched_input_; }
References matched_input_.
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExpressionWithSource(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIdentifierFromMatchedInput(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeRightShiftIdentifier(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTypeswitchCase(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTypeswitchStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::YieldDouble(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::YieldInt32(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::YieldIntegerLiteral(), and v8::internal::torque::Grammar::YieldMatchedInput().
Next()
ParseResult v8::internal::torque::ParseResultIterator::Next () [inline]
Definition at line 170 of file earley-parser.h.
                     {
    CHECK_LT(i_, results_.size());
    return std::move(results_[i_++]);
  }
References CHECK_LT, i_, and results_.
Referenced by v8::internal::torque::DefaultAction(), and NextAs().
NextAs()
template<class T >
T v8::internal::torque::ParseResultIterator::NextAs () [inline]
Definition at line 175 of file earley-parser.h.
             {
    return std::move(Next().Cast<T>());
  }
References Next().
Referenced by v8::internal::torque::anonymous_namespace{torque-parser.cc}::AddGlobalDeclarations(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::AnnotationSet::AnnotationSet(), v8::internal::torque::Grammar::CastParseResult(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::ConcatList(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::ExtractAssignmentOperator(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::anonymous_namespace{torque-parser.cc}::HasAnnotation(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeAbstractTypeDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeAnnotation(), v8::internal::torque::ls::MakeArray(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeAssertStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeAssignmentExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBasicTypeExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBinaryOperator(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBitFieldDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBitFieldStructDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeBlockStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeCall(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeCatchBlock(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassBody(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeClassField(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeConditionalExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeConstDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeCppIncludeDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeDebugStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeDereferenceExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeElementAccessExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeEnumEntry(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExpressionStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExpressionWithSource(), v8::internal::torque::Grammar::MakeExtendedVector(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::TorqueGrammar::MakeExtendedVectorIfAnnotation(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternalBuiltin(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternalMacro(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternalRuntime(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeExternConstDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeFieldAccessExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeFloatingPointLiteralExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeForLoopStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeFunctionTypeExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeGenericParameter(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeGotoStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIdentifier(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIdentifierExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIfStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeImplicitParameterList(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIncrementDecrementExpressionPostfix(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIncrementDecrementExpressionPrefix(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIntAnnotationParameter(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIntegerLiteralExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIntrinsicCallExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeIntrinsicDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeLabelAndTypes(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeLabelBlock(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeLogicalAndExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeLogicalOrExpression(), v8::internal::torque::ls::MakeMember(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeMethodCall(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeMethodDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNameAndExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNameAndExpressionFromExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNameAndType(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNamespaceDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNamespaceQualification(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeNewExpression(), v8::internal::torque::ls::MakeNumberLiteral(), v8::internal::torque::ls::MakeObject(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeParameterList(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeReferenceFieldAccessExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeReferenceTypeExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeReturnStatement(), v8::internal::torque::Grammar::MakeSingletonVector(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeSpecializationDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeSpreadExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStringAnnotationParameter(), v8::internal::torque::ls::MakeStringLiteral(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStringLiteralExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStructDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStructExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeStructField(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTailCallStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueBuiltinDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTorqueMacroDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTryLabelExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTypeAliasDeclaration(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTypeswitchCase(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeTypeswitchStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeUnaryOperator(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeUnionTypeExpression(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeVarDeclarationStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::MakeWhileStatement(), v8::internal::torque::anonymous_namespace{torque-parser.cc}::ProcessTorqueImportDeclaration(), and v8::internal::torque::anonymous_namespace{torque-parser.cc}::StringLiteralUnquoteAction().
operator=()
ParseResultIterator& v8::internal::torque::ParseResultIterator::operator= (const ParseResultIterator &) [delete]
Member Data Documentation
i_
size_t v8::internal::torque::ParseResultIterator::i_ = 0 [private]
Definition at line 184 of file earley-parser.h.
Referenced by HasNext(), and Next().
matched_input_
MatchedInput v8::internal::torque::ParseResultIterator::matched_input_ [private]
Definition at line 185 of file earley-parser.h.
Referenced by matched_input().
results_
std::vector<ParseResult> v8::internal::torque::ParseResultIterator::results_ [private]
Definition at line 183 of file earley-parser.h.
Referenced by HasNext(), and Next().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/earley-parser.h