v8::internal::compiler::ScheduleLateNodeVisitor Class Reference
Public Member Functions
ScheduleLateNodeVisitor (Zone *zone, Scheduler *scheduler)
void Run (NodeVector *roots)
Private Member Functions
void ProcessQueue (Node *root)
void VisitNode (Node *node)
bool IsMarked (BasicBlock *block) const
void Mark (BasicBlock *block)
void MarkBlock (BasicBlock *block)
BasicBlock * SplitNode (BasicBlock *block, Node *node)
BasicBlock * GetHoistBlock (BasicBlock *block)
BasicBlock * GetCommonDominatorOfUses (Node *node)
BasicBlock * FindPredecessorBlock (Node *node)
BasicBlock * GetBlockForUse (Edge edge)
void ScheduleFloatingControl (BasicBlock *block, Node *node)
void ScheduleRegion (BasicBlock *block, Node *region_end)
void ScheduleNode (BasicBlock *block, Node *node)
Node * CloneNode (Node *node)
Private Attributes
Zone * zone_
Scheduler * scheduler_
Schedule * schedule_
BitVector marked_
ZoneDeque< BasicBlock * > marking_queue_
Detailed Description
Definition at line 1500 of file scheduler.cc.
Constructor & Destructor Documentation
ScheduleLateNodeVisitor()
v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleLateNodeVisitor (Zone * zone, Scheduler * scheduler) [inline]
Definition at line 1502 of file scheduler.cc.
      : zone_(zone),
        scheduler_(scheduler),
        schedule_(scheduler_->schedule_),
        marking_queue_(scheduler->zone_) {}
Member Function Documentation
CloneNode()
Node* v8::internal::compiler::ScheduleLateNodeVisitor::CloneNode (Node * node) [inline], [private]
Definition at line 1820 of file scheduler.cc.
                              {
    int const input_count = node->InputCount();
    std::optional<int> coupled_control_edge =
        scheduler_->GetCoupledControlEdge(node);
    for (int index = 0; index < input_count; ++index) {
      if (index != coupled_control_edge) {
        Node* const input = node->InputAt(index);
        scheduler_->IncrementUnscheduledUseCount(input, node);
      }
    }
    Node* const copy = scheduler_->graph_->CloneNode(node);
    TRACE(("clone #%d:%s -> #%d\n"), node->id(), node->op()->mnemonic(),
          copy->id());
    scheduler_->node_data_.resize(copy->id() + 1,
                                  scheduler_->DefaultSchedulerData());
    scheduler_->node_data_[copy->id()] = scheduler_->node_data_[node->id()];
    return copy;
  }
References v8::internal::compiler::TFGraph::CloneNode(), v8::internal::compiler::Scheduler::DefaultSchedulerData(), v8::internal::compiler::Scheduler::GetCoupledControlEdge(), v8::internal::compiler::Scheduler::graph_, v8::internal::compiler::Node::id(), v8::internal::compiler::Scheduler::IncrementUnscheduledUseCount(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Scheduler::node_data_, v8::internal::compiler::Node::op(), scheduler_, and v8::internal::TRACE().
Referenced by SplitNode().
FindPredecessorBlock()
BasicBlock* v8::internal::compiler::ScheduleLateNodeVisitor::FindPredecessorBlock (Node * node) [inline], [private]
Definition at line 1734 of file scheduler.cc.
                                               {
    return scheduler_->control_flow_builder_->FindPredecessorBlock(node);
  }
References v8::internal::compiler::Scheduler::control_flow_builder_, v8::internal::compiler::CFGBuilder::FindPredecessorBlock(), and scheduler_.
Referenced by GetBlockForUse().
GetBlockForUse()
BasicBlock* v8::internal::compiler::ScheduleLateNodeVisitor::GetBlockForUse (Edge edge) [inline], [private]
Definition at line 1738 of file scheduler.cc.
                                        {
    // TODO(titzer): ignore uses from dead nodes (not visited in PrepareUses()).
    // Dead uses only occur if the graph is not trimmed before scheduling.
    Node* use = edge.from();
    if (IrOpcode::IsPhiOpcode(use->opcode())) {
      // If the use is from a coupled (i.e. floating) phi, compute the common
      // dominator of its uses. This will not recurse more than one level.
      if (scheduler_->GetPlacement(use) == Scheduler::kCoupled) {
        TRACE(" inspecting uses of coupled #%d:%s\n", use->id(),
              use->op()->mnemonic());
        // TODO(titzer): reenable once above TODO is addressed.
        // DCHECK_EQ(edge.to(), NodeProperties::GetControlInput(use));
        return GetCommonDominatorOfUses(use);
      }
      // If the use is from a fixed (i.e. non-floating) phi, we use the
      // predecessor block of the corresponding control input to the merge.
      if (scheduler_->GetPlacement(use) == Scheduler::kFixed) {
        TRACE(" input@%d into a fixed phi #%d:%s\n", edge.index(), use->id(),
              use->op()->mnemonic());
        Node* merge = NodeProperties::GetControlInput(use, 0);
        DCHECK(IrOpcode::IsMergeOpcode(merge->opcode()));
        Node* input = NodeProperties::GetControlInput(merge, edge.index());
        return FindPredecessorBlock(input);
      }
    } else if (IrOpcode::IsMergeOpcode(use->opcode())) {
      // If the use is from a fixed (i.e. non-floating) merge, we use the
      // predecessor block of the current input to the merge.
      if (scheduler_->GetPlacement(use) == Scheduler::kFixed) {
        TRACE(" input@%d into a fixed merge #%d:%s\n", edge.index(), use->id(),
              use->op()->mnemonic());
        return FindPredecessorBlock(edge.to());
      }
    }
    BasicBlock* result = schedule_->block(use);
    if (result == nullptr) return nullptr;
    TRACE(" must dominate use #%d:%s in id:%d\n", use->id(),
          use->op()->mnemonic(), result->id().ToInt());
    return result;
  }
References v8::internal::compiler::Schedule::block(), v8::internal::DCHECK(), FindPredecessorBlock(), v8::internal::compiler::Edge::from(), GetCommonDominatorOfUses(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Scheduler::GetPlacement(), v8::internal::compiler::Edge::index(), v8::internal::compiler::IrOpcode::IsMergeOpcode(), v8::internal::compiler::IrOpcode::IsPhiOpcode(), v8::internal::compiler::Scheduler::kCoupled, v8::internal::compiler::Scheduler::kFixed, v8::internal::compiler::Node::opcode(), v8::base::internal::result, schedule_, scheduler_, v8::internal::compiler::Edge::to(), v8::internal::TRACE(), and use().
Referenced by GetCommonDominatorOfUses(), and SplitNode().
GetCommonDominatorOfUses()
BasicBlock* v8::internal::compiler::ScheduleLateNodeVisitor::GetCommonDominatorOfUses (Node * node) [inline], [private]
Definition at line 1720 of file scheduler.cc.
                                                   {
    BasicBlock* block = nullptr;
    for (Edge edge : node->use_edges()) {
      if (!scheduler_->IsLive(edge.from())) continue;
      BasicBlock* use_block = GetBlockForUse(edge);
      block = block == nullptr
                  ? use_block
                  : use_block == nullptr
                        ? block
                        : scheduler_->GetCommonDominator(block, use_block);
    }
    return block;
  }
References GetBlockForUse(), v8::internal::compiler::Scheduler::GetCommonDominator(), v8::internal::compiler::Scheduler::IsLive(), scheduler_, and v8::internal::compiler::Node::use_edges().
Referenced by GetBlockForUse(), SplitNode(), and VisitNode().
GetHoistBlock()
BasicBlock* v8::internal::compiler::ScheduleLateNodeVisitor::GetHoistBlock (BasicBlock * block) [inline], [private]
Definition at line 1700 of file scheduler.cc.
                                               {
    if (!scheduler_->special_rpo_->HasLoopBlocks()) return nullptr;
    if (block->IsLoopHeader()) return block->dominator();
    // We have to check to make sure that the {block} dominates all
    // of the outgoing blocks. If it doesn't, then there is a path
    // out of the loop which does not execute this {block}, so we
    // can't hoist operations from this {block} out of the loop, as
    // that would introduce additional computations.
    if (BasicBlock* header_block = block->loop_header()) {
      for (BasicBlock* outgoing_block :
           scheduler_->special_rpo_->GetOutgoingBlocks(header_block)) {
        if (scheduler_->GetCommonDominator(block, outgoing_block) != block) {
          return nullptr;
        }
      }
      return header_block->dominator();
    }
    return nullptr;
  }
References v8::internal::compiler::BasicBlock::dominator(), v8::internal::compiler::Scheduler::GetCommonDominator(), v8::internal::compiler::SpecialRPONumberer::GetOutgoingBlocks(), v8::internal::compiler::SpecialRPONumberer::HasLoopBlocks(), v8::internal::compiler::BasicBlock::IsLoopHeader(), v8::internal::compiler::BasicBlock::loop_header(), scheduler_, and v8::internal::compiler::Scheduler::special_rpo_.
Referenced by VisitNode().
IsMarked()
bool v8::internal::compiler::ScheduleLateNodeVisitor::IsMarked (BasicBlock * block) const [inline], [private]
Definition at line 1592 of file scheduler.cc.
                                         {
    return marked_.Contains(block->id().ToInt());
  }
References v8::internal::BitVector::Contains(), v8::internal::compiler::BasicBlock::id(), marked_, and v8::internal::compiler::BasicBlock::Id::ToInt().
Referenced by MarkBlock(), and SplitNode().
Mark()
void v8::internal::compiler::ScheduleLateNodeVisitor::Mark (BasicBlock * block) [inline], [private]
Definition at line 1596 of file scheduler.cc.
{ marked_.Add(block->id().ToInt()); }
References v8::internal::BitVector::Add(), v8::internal::compiler::BasicBlock::id(), marked_, and v8::internal::compiler::BasicBlock::Id::ToInt().
Referenced by MarkBlock().
MarkBlock()
void v8::internal::compiler::ScheduleLateNodeVisitor::MarkBlock (BasicBlock * block) [inline], [private]
Definition at line 1599 of file scheduler.cc.
                                    {
    Mark(block);
    for (BasicBlock* pred_block : block->predecessors()) {
      if (IsMarked(pred_block)) continue;
      marking_queue_.push_back(pred_block);
    }
  }
References IsMarked(), Mark(), marking_queue_, and v8::internal::compiler::BasicBlock::predecessors().
Referenced by SplitNode().
ProcessQueue()
void v8::internal::compiler::ScheduleLateNodeVisitor::ProcessQueue (Node * root) [inline], [private]
Definition at line 1516 of file scheduler.cc.
                                {
    ZoneQueue<Node*>* queue = &(scheduler_->schedule_queue_);
    for (Node* node : root->inputs()) {
      // Don't schedule coupled nodes on their own.
      if (scheduler_->GetPlacement(node) == Scheduler::kCoupled) {
        node = NodeProperties::GetControlInput(node);
      }
      // Test schedulability condition by looking at unscheduled use count.
      if (scheduler_->GetData(node)->unscheduled_count_ != 0) continue;
      queue->push(node);
      do {
        scheduler_->tick_counter_->TickAndMaybeEnterSafepoint();
        Node* const n = queue->front();
        queue->pop();
        VisitNode(n);
      } while (!queue->empty());
    }
  }
References v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::Scheduler::GetData(), v8::internal::compiler::Scheduler::GetPlacement(), v8::internal::compiler::Node::inputs(), v8::internal::compiler::Scheduler::kCoupled, v8::internal::compiler::Scheduler::schedule_queue_, scheduler_, v8::internal::compiler::Scheduler::tick_counter_, v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), v8::internal::compiler::Scheduler::SchedulerData::unscheduled_count_, and VisitNode().
Referenced by Run().
Run()
void v8::internal::compiler::ScheduleLateNodeVisitor::Run (NodeVector * roots) [inline]
Definition at line 1509 of file scheduler.cc.
                              {
    for (Node* const root : *roots) {
      ProcessQueue(root);
    }
  }
References ProcessQueue().
Referenced by v8::internal::compiler::Scheduler::ScheduleLate().
ScheduleFloatingControl()
void v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleFloatingControl (BasicBlock * block, Node * node) [inline], [private]
Definition at line 1778 of file scheduler.cc.
                                                              {
    scheduler_->FuseFloatingControl(block, node);
  }
References v8::internal::compiler::Scheduler::FuseFloatingControl(), and scheduler_.
Referenced by VisitNode().
ScheduleNode()
void v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleNode (BasicBlock * block, Node * node) [inline], [private]
Definition at line 1810 of file scheduler.cc.
                                                   {
    schedule_->PlanNode(block, node);
    size_t block_id = block->id().ToSize();
    if (!scheduler_->scheduled_nodes_[block_id]) {
      scheduler_->scheduled_nodes_[block_id] = zone_->New<NodeVector>(zone_);
    }
    scheduler_->scheduled_nodes_[block_id]->push_back(node);
    scheduler_->UpdatePlacement(node, Scheduler::kScheduled);
  }
References v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::Scheduler::kScheduled, v8::internal::Zone::New(), v8::internal::compiler::Schedule::PlanNode(), schedule_, v8::internal::compiler::Scheduler::scheduled_nodes_, scheduler_, v8::internal::compiler::BasicBlock::Id::ToSize(), v8::internal::compiler::Scheduler::UpdatePlacement(), and zone_.
Referenced by ScheduleRegion(), and VisitNode().
ScheduleRegion()
void v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleRegion (BasicBlock * block, Node * region_end) [inline], [private]
Definition at line 1782 of file scheduler.cc.
                                                           {
    // We only allow regions of instructions connected into a linear
    // effect chain. The only value allowed to be produced by a node
    // in the chain must be the value consumed by the FinishRegion node.
    // We schedule back to front; we first schedule FinishRegion.
    CHECK_EQ(IrOpcode::kFinishRegion, region_end->opcode());
    ScheduleNode(block, region_end);
    // Schedule the chain.
    Node* node = NodeProperties::GetEffectInput(region_end);
    while (node->opcode() != IrOpcode::kBeginRegion) {
      DCHECK_EQ(0, scheduler_->GetData(node)->unscheduled_count_);
      DCHECK_EQ(1, node->op()->EffectInputCount());
      DCHECK_EQ(1, node->op()->EffectOutputCount());
      DCHECK_EQ(0, node->op()->ControlOutputCount());
      // The value output (if there is any) must be consumed
      // by the EndRegion node.
      DCHECK(node->op()->ValueOutputCount() == 0 ||
             node == region_end->InputAt(0));
      ScheduleNode(block, node);
      node = NodeProperties::GetEffectInput(node);
    }
    // Schedule the BeginRegion node.
    DCHECK_EQ(0, scheduler_->GetData(node)->unscheduled_count_);
    ScheduleNode(block, node);
  }
References CHECK_EQ, v8::internal::compiler::Operator::ControlOutputCount(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::Scheduler::GetData(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), ScheduleNode(), scheduler_, v8::internal::compiler::Scheduler::SchedulerData::unscheduled_count_, and v8::internal::compiler::Operator::ValueOutputCount().
Referenced by VisitNode().
SplitNode()
BasicBlock* v8::internal::compiler::ScheduleLateNodeVisitor::SplitNode (BasicBlock * block, Node * node) [inline], [private]
Definition at line 1607 of file scheduler.cc.
                                                       {
    // For now, we limit splitting to pure nodes.
    if (!node->op()->HasProperty(Operator::kPure)) return block;
    // TODO(titzer): fix the special case of splitting of projections.
    if (node->opcode() == IrOpcode::kProjection) return block;
    // The {block} is common dominator of all uses of {node}, so we cannot
    // split anything unless the {block} has at least two successors.
    DCHECK_EQ(block, GetCommonDominatorOfUses(node));
    if (block->SuccessorCount() < 2) return block;
    // Clear marking bits.
    DCHECK(marking_queue_.empty());
    marked_.Clear();
    int new_size = static_cast<int>(schedule_->BasicBlockCount() + 1);
    if (marked_.length() < new_size) {
      marked_.Resize(new_size, scheduler_->zone_);
    }
    // Check if the {node} has uses in {block}.
    for (Edge edge : node->use_edges()) {
      if (!scheduler_->IsLive(edge.from())) continue;
      BasicBlock* use_block = GetBlockForUse(edge);
      if (use_block == nullptr || IsMarked(use_block)) continue;
      if (use_block == block) {
        TRACE(" not splitting #%d:%s, it is used in id:%d\n", node->id(),
              node->op()->mnemonic(), block->id().ToInt());
        marking_queue_.clear();
        return block;
      }
      MarkBlock(use_block);
    }
    // Compute transitive marking closure; a block is marked if all its
    // successors are marked.
    do {
      BasicBlock* top_block = marking_queue_.front();
      marking_queue_.pop_front();
      if (IsMarked(top_block)) continue;
      bool marked = true;
      if (top_block->loop_depth() == block->loop_depth()) {
        for (BasicBlock* successor : top_block->successors()) {
          if (!IsMarked(successor)) {
            marked = false;
            break;
          }
        }
      }
      if (marked) MarkBlock(top_block);
    } while (!marking_queue_.empty());
    // If the (common dominator) {block} is marked, we know that all paths from
    // {block} to the end contain at least one use of {node}, and hence there's
    // no point in splitting the {node} in this case.
    if (IsMarked(block)) {
      TRACE(" not splitting #%d:%s, its common dominator id:%d is perfect\n",
            node->id(), node->op()->mnemonic(), block->id().ToInt());
      return block;
    }
    // Split {node} for uses according to the previously computed marking
    // closure. Every marking partition has a unique dominator, which get's a
    // copy of the {node} with the exception of the first partition, which get's
    // the {node} itself.
    ZoneMap<BasicBlock*, Node*> dominators(scheduler_->zone_);
    for (Edge edge : node->use_edges()) {
      if (!scheduler_->IsLive(edge.from())) continue;
      BasicBlock* use_block = GetBlockForUse(edge);
      if (use_block == nullptr) continue;
      while (IsMarked(use_block->dominator())) {
        use_block = use_block->dominator();
      }
      auto& use_node = dominators[use_block];
      if (use_node == nullptr) {
        if (dominators.size() == 1u) {
          // Place the {node} at {use_block}.
          block = use_block;
          use_node = node;
          TRACE(" pushing #%d:%s down to id:%d\n", node->id(),
                node->op()->mnemonic(), block->id().ToInt());
        } else {
          // Place a copy of {node} at {use_block}.
          use_node = CloneNode(node);
          TRACE(" cloning #%d:%s for id:%d\n", use_node->id(),
                use_node->op()->mnemonic(), use_block->id().ToInt());
          scheduler_->schedule_queue_.push(use_node);
        }
      }
      edge.UpdateTo(use_node);
    }
    return block;
  }
References v8::internal::compiler::Schedule::BasicBlockCount(), v8::internal::BitVector::Clear(), CloneNode(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::BasicBlock::dominator(), GetBlockForUse(), GetCommonDominatorOfUses(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::Node::id(), v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::Scheduler::IsLive(), IsMarked(), v8::internal::compiler::Operator::kPure, v8::internal::BitVector::length(), v8::internal::compiler::BasicBlock::loop_depth(), MarkBlock(), marked_, marking_queue_, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::BitVector::Resize(), schedule_, v8::internal::compiler::Scheduler::schedule_queue_, scheduler_, v8::internal::compiler::BasicBlock::SuccessorCount(), v8::internal::compiler::BasicBlock::successors(), v8::internal::compiler::BasicBlock::Id::ToInt(), v8::internal::TRACE(), v8::internal::compiler::Node::use_edges(), and v8::internal::compiler::Scheduler::zone_.
Referenced by VisitNode().
VisitNode()
void v8::internal::compiler::ScheduleLateNodeVisitor::VisitNode (Node * node) [inline], [private]
Definition at line 1540 of file scheduler.cc.
                             {
    DCHECK_EQ(0, scheduler_->GetData(node)->unscheduled_count_);
    // Don't schedule nodes that are already scheduled.
    if (schedule_->IsScheduled(node)) return;
    DCHECK_EQ(Scheduler::kSchedulable, scheduler_->GetPlacement(node));
    // Determine the dominating block for all of the uses of this node. It is
    // the latest block that this node can be scheduled in.
    TRACE("Scheduling #%d:%s\n", node->id(), node->op()->mnemonic());
    BasicBlock* block = GetCommonDominatorOfUses(node);
    DCHECK_NOT_NULL(block);
    // The schedule early block dominates the schedule late block.
    BasicBlock* min_block = scheduler_->GetData(node)->minimum_block_;
    DCHECK_EQ(min_block, BasicBlock::GetCommonDominator(block, min_block));
    TRACE(
        "Schedule late of #%d:%s is id:%d at loop depth %d, minimum = id:%d\n",
        node->id(), node->op()->mnemonic(), block->id().ToInt(),
        block->loop_depth(), min_block->id().ToInt());
    // Hoist nodes out of loops if possible. Nodes can be hoisted iteratively
    // into enclosing loop pre-headers until they would precede their schedule
    // early position.
    BasicBlock* hoist_block = GetHoistBlock(block);
    if (hoist_block &&
        hoist_block->dominator_depth() >= min_block->dominator_depth()) {
      DCHECK(scheduler_->special_rpo_->HasLoopBlocks());
      do {
        TRACE(" hoisting #%d:%s to block id:%d\n", node->id(),
              node->op()->mnemonic(), hoist_block->id().ToInt());
        DCHECK_LT(hoist_block->loop_depth(), block->loop_depth());
        block = hoist_block;
        hoist_block = GetHoistBlock(hoist_block);
      } while (hoist_block &&
               hoist_block->dominator_depth() >= min_block->dominator_depth());
    } else if (scheduler_->flags_ & Scheduler::kSplitNodes) {
      // Split the {node} if beneficial and return the new {block} for it.
      block = SplitNode(block, node);
    }
    // Schedule the node or a floating control structure.
    if (IrOpcode::IsMergeOpcode(node->opcode())) {
      ScheduleFloatingControl(block, node);
    } else if (node->opcode() == IrOpcode::kFinishRegion) {
      ScheduleRegion(block, node);
    } else {
      ScheduleNode(block, node);
    }
  }
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, DCHECK_NOT_NULL, v8::internal::compiler::BasicBlock::dominator_depth(), v8::internal::compiler::Scheduler::flags_, v8::internal::compiler::BasicBlock::GetCommonDominator(), GetCommonDominatorOfUses(), v8::internal::compiler::Scheduler::GetData(), GetHoistBlock(), v8::internal::compiler::Scheduler::GetPlacement(), v8::internal::compiler::SpecialRPONumberer::HasLoopBlocks(), v8::internal::compiler::Node::id(), v8::internal::compiler::BasicBlock::id(), v8::internal::compiler::IrOpcode::IsMergeOpcode(), v8::internal::compiler::Schedule::IsScheduled(), v8::internal::compiler::Scheduler::kSchedulable, v8::internal::compiler::Scheduler::kSplitNodes, v8::internal::compiler::BasicBlock::loop_depth(), v8::internal::compiler::Scheduler::SchedulerData::minimum_block_, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), schedule_, ScheduleFloatingControl(), ScheduleNode(), scheduler_, ScheduleRegion(), v8::internal::compiler::Scheduler::special_rpo_, SplitNode(), v8::internal::compiler::BasicBlock::Id::ToInt(), v8::internal::TRACE(), and v8::internal::compiler::Scheduler::SchedulerData::unscheduled_count_.
Referenced by ProcessQueue().
Member Data Documentation
marked_
BitVector v8::internal::compiler::ScheduleLateNodeVisitor::marked_ [private]
Definition at line 1842 of file scheduler.cc.
Referenced by IsMarked(), Mark(), and SplitNode().
marking_queue_
ZoneDeque<BasicBlock*> v8::internal::compiler::ScheduleLateNodeVisitor::marking_queue_ [private]
Definition at line 1843 of file scheduler.cc.
Referenced by MarkBlock(), and SplitNode().
schedule_
Schedule* v8::internal::compiler::ScheduleLateNodeVisitor::schedule_ [private]
Definition at line 1841 of file scheduler.cc.
Referenced by GetBlockForUse(), ScheduleNode(), SplitNode(), and VisitNode().
scheduler_
Scheduler* v8::internal::compiler::ScheduleLateNodeVisitor::scheduler_ [private]
Definition at line 1840 of file scheduler.cc.
Referenced by CloneNode(), FindPredecessorBlock(), GetBlockForUse(), GetCommonDominatorOfUses(), GetHoistBlock(), ProcessQueue(), ScheduleFloatingControl(), ScheduleNode(), ScheduleRegion(), SplitNode(), and VisitNode().
zone_
Zone* v8::internal::compiler::ScheduleLateNodeVisitor::zone_ [private]
Definition at line 1839 of file scheduler.cc.
Referenced by ScheduleNode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/scheduler.cc