v8::internal::compiler::TypedStateValueInfo Class Reference
#include <common-operator.h>
Public Member Functions
TypedStateValueInfo (ZoneVector< MachineType > const *machine_types, SparseInputMask sparse_input_mask)
ZoneVector< MachineType > const * machine_types () const
SparseInputMask sparse_input_mask () const
Private Attributes
ZoneVector< MachineType > const * machine_types_
SparseInputMask sparse_input_mask_
Detailed Description
Definition at line 374 of file common-operator.h.
Constructor & Destructor Documentation
TypedStateValueInfo()
v8::internal::compiler::TypedStateValueInfo::TypedStateValueInfo (ZoneVector< MachineType > const * machine_types, SparseInputMask sparse_input_mask) [inline]
Definition at line 376 of file common-operator.h.
      : machine_types_(machine_types), sparse_input_mask_(sparse_input_mask) {}
Member Function Documentation
machine_types()
ZoneVector<MachineType> const* v8::internal::compiler::TypedStateValueInfo::machine_types () const [inline]
Definition at line 380 of file common-operator.h.
                                                       {
    return machine_types_;
  }
References machine_types_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
sparse_input_mask()
SparseInputMask v8::internal::compiler::TypedStateValueInfo::sparse_input_mask () const [inline]
Definition at line 383 of file common-operator.h.
{ return sparse_input_mask_; }
References sparse_input_mask_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
Member Data Documentation
machine_types_
ZoneVector<MachineType> const* v8::internal::compiler::TypedStateValueInfo::machine_types_ [private]
Definition at line 386 of file common-operator.h.
Referenced by machine_types().
sparse_input_mask_
SparseInputMask v8::internal::compiler::TypedStateValueInfo::sparse_input_mask_ [private]
Definition at line 387 of file common-operator.h.
Referenced by sparse_input_mask().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/common-operator.h