v8::internal::Guard Class Reference
#include <regexp-nodes.h>
Public Types
enum Relation { LT
, GEQ
 }
Public Member Functions
Guard (int reg, Relation op, int value)
int reg ()
Relation op ()
int value ()
Private Attributes
int reg_
Relation op_
int value_
Detailed Description
Definition at line 627 of file regexp-nodes.h.
Member Enumeration Documentation
Relation
enum v8::internal::Guard::Relation
Enumerator
LT
GEQ
Definition at line 629 of file regexp-nodes.h.
{ LT, GEQ };
Constructor & Destructor Documentation
Guard()
v8::internal::Guard::Guard (int reg, Relation op, int value) [inline]
Definition at line 630 of file regexp-nodes.h.
: reg_(reg), op_(op), value_(value) {}
Member Function Documentation
op()
Relation v8::internal::Guard::op () [inline]
Definition at line 632 of file regexp-nodes.h.
{ return op_; }
References op_.
Referenced by v8::internal::ChoiceNode::GenerateGuard().
reg()
int v8::internal::Guard::reg () [inline]
Definition at line 631 of file regexp-nodes.h.
{ return reg_; }
References reg_.
Referenced by v8::internal::ChoiceNode::GenerateGuard().
value()
int v8::internal::Guard::value () [inline]
Definition at line 633 of file regexp-nodes.h.
{ return value_; }
References value_.
Referenced by v8::internal::ChoiceNode::GenerateGuard().
Member Data Documentation
op_
Relation v8::internal::Guard::op_ [private]
Definition at line 637 of file regexp-nodes.h.
Referenced by op().
reg_
int v8::internal::Guard::reg_ [private]
Definition at line 636 of file regexp-nodes.h.
Referenced by reg().
value_
int v8::internal::Guard::value_ [private]
Definition at line 638 of file regexp-nodes.h.
Referenced by value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/regexp-nodes.h