v8::internal::WasmToJSWrapperDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_RESULT_AND_PARAMETER_TYPES (MachineType::IntPtr(), MachineType::IntPtr(), MachineType::Float64(), MachineType::Float64(), MachineType::AnyTagged()) static const expr int kMaxRegisterParams
Static Public Member Functions
static constexpr auto registers ()
static constexpr auto return_registers ()
static constexpr auto return_double_registers ()
Additional Inherited Members
Detailed Description
Definition at line 2649 of file interface-descriptors.h.
Member Function Documentation
DEFINE_RESULT_AND_PARAMETER_TYPES()
v8::internal::WasmToJSWrapperDescriptor::DEFINE_RESULT_AND_PARAMETER_TYPES (MachineType::IntPtr() , MachineType::IntPtr() , MachineType::Float64() , MachineType::Float64() , MachineType::AnyTagged()) const
registers()
constexpr auto v8::internal::WasmToJSWrapperDescriptor::registers () [inline], [static], [constexpr]
Definition at line 786 of file interface-descriptors-inl.h.
                                                    {
#if V8_ENABLE_WEBASSEMBLY
  return RegisterArray(wasm::kGpParamRegisters[0]);
#else
  return EmptyRegisterArray();
#endif
}
References v8::internal::wasm::kGpParamRegisters, and v8::internal::RegisterArray().
return_double_registers()
constexpr auto v8::internal::WasmToJSWrapperDescriptor::return_double_registers () [inline], [static], [constexpr]
Definition at line 804 of file interface-descriptors-inl.h.
                                                                  {
#if V8_ENABLE_WEBASSEMBLY
  return DoubleRegisterArray(no_dreg, no_dreg, wasm::kFpReturnRegisters[0],
                             wasm::kFpReturnRegisters[1]);
#else
  // An arbitrary register array so that the code compiles.
  return CallInterfaceDescriptor::DefaultDoubleRegisterArray();
#endif
}
References v8::internal::CallInterfaceDescriptor::DefaultDoubleRegisterArray(), v8::internal::DoubleRegisterArray(), v8::internal::wasm::kFpReturnRegisters, and v8::internal::no_dreg.
return_registers()
constexpr auto v8::internal::WasmToJSWrapperDescriptor::return_registers () [inline], [static], [constexpr]
Definition at line 794 of file interface-descriptors-inl.h.
                                                           {
#if V8_ENABLE_WEBASSEMBLY
  return RegisterArray(wasm::kGpReturnRegisters[0], wasm::kGpReturnRegisters[1],
                       no_reg, no_reg);
#else
  // An arbitrary register array so that the code compiles.
  return CallInterfaceDescriptor::DefaultRegisterArray();
#endif
}
References v8::internal::CallInterfaceDescriptor::DefaultRegisterArray(), v8::internal::wasm::kGpReturnRegisters, v8::internal::no_reg, and v8::internal::RegisterArray().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h