v8_inspector::internal::V8DebuggerId Class Reference
#include <v8-debugger-id.h>
Public Member Functions
V8DebuggerId ()=default
V8DebuggerId (std::pair< int64_t, int64_t >)
V8DebuggerId (const String16 &)
V8DebuggerId (const V8DebuggerId &) V8_NOEXCEPT=default
V8DebuggerId & operator= (const V8DebuggerId &) V8_NOEXCEPT=default
v8_inspector::V8DebuggerId toV8DebuggerId () const
String16 toString () const
bool isValid () const
std::pair< int64_t, int64_t > pair () const
Static Public Member Functions
static V8DebuggerId generate (V8InspectorImpl *)
Private Attributes
v8_inspector::V8DebuggerId m_debugger_id
Detailed Description
Definition at line 19 of file v8-debugger-id.h.
Constructor & Destructor Documentation
V8DebuggerId() [1/4]
v8_inspector::internal::V8DebuggerId::V8DebuggerId () [default]
Referenced by generate().
V8DebuggerId() [2/4]
v8_inspector::internal::V8DebuggerId::V8DebuggerId (std::pair< int64_t, int64_t > pair) [explicit]
Definition at line 29 of file v8-debugger-id.cc.
    : m_debugger_id(pair) {}
V8DebuggerId() [3/4]
v8_inspector::internal::V8DebuggerId::V8DebuggerId (const String16 & debuggerId) [explicit]
Definition at line 38 of file v8-debugger-id.cc.
                                                     {
  const UChar dot = '.';
  size_t pos = debuggerId.find(dot);
  if (pos == String16::kNotFound) return;
  bool ok = false;
  int64_t first = debuggerId.substring(0, pos).toInteger64(&ok);
  if (!ok) return;
  int64_t second = debuggerId.substring(pos + 1).toInteger64(&ok);
  if (!ok) return;
  m_debugger_id = v8_inspector::V8DebuggerId(std::make_pair(first, second));
}
References v8_inspector::String16::find(), v8_inspector::String16::kNotFound, m_debugger_id, v8_inspector::String16::substring(), and v8_inspector::String16::toInteger64().
V8DebuggerId() [4/4]
v8_inspector::internal::V8DebuggerId::V8DebuggerId (const V8DebuggerId &) [default]
Member Function Documentation
generate()
V8DebuggerId v8_inspector::internal::V8DebuggerId::generate (V8InspectorImpl * inspector) [static]
Definition at line 33 of file v8-debugger-id.cc.
                                                              {
  return V8DebuggerId(std::make_pair(inspector->generateUniqueId(),
                                     inspector->generateUniqueId()));
}
References v8_inspector::V8InspectorImpl::generateUniqueId(), and V8DebuggerId().
Referenced by v8_inspector::V8Debugger::debuggerIdFor().
isValid()
bool v8_inspector::internal::V8DebuggerId::isValid () const
Definition at line 54 of file v8-debugger-id.cc.
{ return m_debugger_id.isValid(); }
References v8_inspector::V8DebuggerId::isValid(), and m_debugger_id.
Referenced by v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::ensureContext(), v8_inspector::V8DebuggerAgentImpl::getStackTrace(), and v8_inspector::V8StackTraceId::V8StackTraceId().
operator=()
V8DebuggerId& v8_inspector::internal::V8DebuggerId::operator= (const V8DebuggerId &) [default]
pair()
std::pair< int64_t, int64_t > v8_inspector::internal::V8DebuggerId::pair () const
Definition at line 56 of file v8-debugger-id.cc.
                                                   {
  return m_debugger_id.pair();
}
References m_debugger_id, and v8_inspector::V8DebuggerId::pair().
Referenced by v8_inspector::V8DebuggerAgentImpl::getStackTrace(), v8_inspector::V8InspectorImpl::resolveUniqueContextId(), and v8_inspector::V8StackTraceId::V8StackTraceId().
toString()
String16 v8_inspector::internal::V8DebuggerId::toString () const
Definition at line 50 of file v8-debugger-id.cc.
                                      {
  return toString16(m_debugger_id.toString()->string());
}
References m_debugger_id, v8_inspector::V8DebuggerId::toString(), and v8_inspector::toString16().
Referenced by v8_inspector::anonymous_namespace{v8-stack-trace-impl.cc}::buildInspectorObjectCommon(), v8_inspector::V8DebuggerAgentImpl::currentExternalStackTrace(), v8_inspector::V8DebuggerAgentImpl::enable(), v8_inspector::V8DebuggerAgentImpl::isFunctionBlackboxed(), v8_inspector::V8RuntimeAgentImpl::reportExecutionContextCreated(), and v8_inspector::V8RuntimeAgentImpl::reportExecutionContextDestroyed().
toV8DebuggerId()
v8_inspector::V8DebuggerId v8_inspector::internal::V8DebuggerId::toV8DebuggerId () const [inline]
Definition at line 29 of file v8-debugger-id.h.
{ return m_debugger_id; }
References m_debugger_id.
Referenced by v8_inspector::V8InspectorImpl::uniqueDebuggerId().
Member Data Documentation
m_debugger_id
v8_inspector::V8DebuggerId v8_inspector::internal::V8DebuggerId::m_debugger_id [private]
Definition at line 35 of file v8-debugger-id.h.
Referenced by isValid(), pair(), toString(), toV8DebuggerId(), and V8DebuggerId().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-debugger-id.h
/mnt/V8SourceCode/src/inspector/v8-debugger-id.cc