v8::internal::TryFinallyStatementSourceRanges Class Reference
#include <ast-source-ranges.h>
Public Member Functions
TryFinallyStatementSourceRanges (const SourceRange &finally_range)
SourceRange GetRange (SourceRangeKind kind) override
bool HasRange (SourceRangeKind kind) override
void RemoveContinuationRange () override
Private Attributes
SourceRange finally_range_
bool has_continuation_ = true
Detailed Description
Definition at line 388 of file ast-source-ranges.h.
Constructor & Destructor Documentation
TryFinallyStatementSourceRanges()
v8::internal::TryFinallyStatementSourceRanges::TryFinallyStatementSourceRanges (const SourceRange & finally_range) [inline], [explicit]
Definition at line 390 of file ast-source-ranges.h.
      : finally_range_(finally_range) {}
Member Function Documentation
GetRange()
SourceRange v8::internal::TryFinallyStatementSourceRanges::GetRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 393 of file ast-source-ranges.h.
                                                      {
    DCHECK(HasRange(kind));
    switch (kind) {
      case SourceRangeKind::kFinally:
        return finally_range_;
      case SourceRangeKind::kContinuation:
        if (!has_continuation_) return SourceRange::Empty();
        return SourceRange::ContinuationOf(finally_range_);
      default:
        UNREACHABLE();
    }
  }
References v8::internal::SourceRange::ContinuationOf(), v8::internal::DCHECK(), v8::internal::SourceRange::Empty(), finally_range_, has_continuation_, HasRange(), v8::internal::kContinuation, v8::internal::kFinally, and v8::internal::UNREACHABLE().
HasRange()
bool v8::internal::TryFinallyStatementSourceRanges::HasRange (SourceRangeKind kind) [inline], [override], [virtual]
Implements v8::internal::AstNodeSourceRanges.
Definition at line 406 of file ast-source-ranges.h.
                                               {
    return kind == SourceRangeKind::kFinally ||
           kind == SourceRangeKind::kContinuation;
  }
References v8::internal::kContinuation, and v8::internal::kFinally.
Referenced by GetRange(), and RemoveContinuationRange().
RemoveContinuationRange()
void v8::internal::TryFinallyStatementSourceRanges::RemoveContinuationRange () [inline], [override], [virtual]
Reimplemented from v8::internal::AstNodeSourceRanges.
Definition at line 411 of file ast-source-ranges.h.
                                          {
    DCHECK(HasRange(SourceRangeKind::kContinuation));
    has_continuation_ = false;
  }
References v8::internal::DCHECK(), has_continuation_, HasRange(), and v8::internal::kContinuation.
Member Data Documentation
finally_range_
SourceRange v8::internal::TryFinallyStatementSourceRanges::finally_range_ [private]
Definition at line 417 of file ast-source-ranges.h.
Referenced by GetRange().
has_continuation_
bool v8::internal::TryFinallyStatementSourceRanges::has_continuation_ = true [private]
Definition at line 418 of file ast-source-ranges.h.
Referenced by GetRange(), and RemoveContinuationRange().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast-source-ranges.h