v8::internal::TriggerFailureExtension Class Reference
#include <trigger-failure-extension.h>
Public Member Functions
TriggerFailureExtension ()
v8::Local< v8::FunctionTemplate > GetNativeFunctionTemplate (v8::Isolate *isolate, v8::Local< v8::String > name) override
Static Public Member Functions
static void TriggerCheckFalse (const v8::FunctionCallbackInfo< v8::Value > &info)
static void TriggerAssertFalse (const v8::FunctionCallbackInfo< v8::Value > &info)
static void TriggerSlowAssertFalse (const v8::FunctionCallbackInfo< v8::Value > &info)
Static Private Attributes
static const char *const kSource
Detailed Description
Definition at line 17 of file trigger-failure-extension.h.
Constructor & Destructor Documentation
TriggerFailureExtension()
v8::internal::TriggerFailureExtension::TriggerFailureExtension () [inline]
Definition at line 19 of file trigger-failure-extension.h.
: v8::Extension("v8/trigger-failure", kSource) {}
Member Function Documentation
GetNativeFunctionTemplate()
v8::Local< v8::FunctionTemplate > v8::internal::TriggerFailureExtension::GetNativeFunctionTemplate (v8::Isolate * isolate, v8::Local< v8::String > name) [override], [virtual]
Reimplemented from v8::Extension.
Definition at line 22 of file trigger-failure-extension.cc.
                                                                          {
  if (strcmp(*v8::String::Utf8Value(isolate, str), "triggerCheckFalse") == 0) {
    return v8::FunctionTemplate::New(
        isolate,
        TriggerFailureExtension::TriggerCheckFalse);
  } else if (strcmp(*v8::String::Utf8Value(isolate, str),
                    "triggerAssertFalse") == 0) {
    return v8::FunctionTemplate::New(
        isolate,
        TriggerFailureExtension::TriggerAssertFalse);
  } else {
    CHECK_EQ(0, strcmp(*v8::String::Utf8Value(isolate, str),
                       "triggerSlowAssertFalse"));
    return v8::FunctionTemplate::New(
        isolate,
        TriggerFailureExtension::TriggerSlowAssertFalse);
  }
}
References CHECK_EQ, v8::FunctionTemplate::New(), TriggerAssertFalse(), TriggerCheckFalse(), and TriggerSlowAssertFalse().
TriggerAssertFalse()
void v8::internal::TriggerFailureExtension::TriggerAssertFalse (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 47 of file trigger-failure-extension.cc.
                                                 {
  DCHECK(false);
}
References v8::internal::DCHECK().
Referenced by GetNativeFunctionTemplate().
TriggerCheckFalse()
void v8::internal::TriggerFailureExtension::TriggerCheckFalse (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 42 of file trigger-failure-extension.cc.
                                                 {
  CHECK(false);
}
References CHECK.
Referenced by GetNativeFunctionTemplate().
TriggerSlowAssertFalse()
void v8::internal::TriggerFailureExtension::TriggerSlowAssertFalse (const v8::FunctionCallbackInfo< v8::Value > & info) [static]
Definition at line 52 of file trigger-failure-extension.cc.
                                                 {
  SLOW_DCHECK(false);
}
References SLOW_DCHECK.
Referenced by GetNativeFunctionTemplate().
Member Data Documentation
kSource
const char *const v8::internal::TriggerFailureExtension::kSource [static], [private]
Initial value:
=
    "native function triggerCheckFalse();"
    "native function triggerAssertFalse();"
    "native function triggerSlowAssertFalse();"
Definition at line 30 of file trigger-failure-extension.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/extensions/trigger-failure-extension.h
/mnt/V8SourceCode/src/extensions/trigger-failure-extension.cc