v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier Class Reference
#include <maglev-ir.h>
Public Member Functions
StoreFixedArrayElementNoWriteBarrier (uint64_t bitfield)
Input & elements_input ()
Input & index_input ()
Input & value_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes
static constexpr int kElementsIndex = 0
static constexpr int kIndexIndex = 1
static constexpr int kValueIndex = 2
Private Types
using Base = FixedInputNodeT< 3, StoreFixedArrayElementNoWriteBarrier >
Additional Inherited Members
Detailed Description
Definition at line 8462 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::Base = FixedInputNodeT<3, StoreFixedArrayElementNoWriteBarrier> [private]
Definition at line 8464 of file maglev-ir.h.
Constructor & Destructor Documentation
StoreFixedArrayElementNoWriteBarrier()
v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::StoreFixedArrayElementNoWriteBarrier (uint64_t bitfield) [inline], [explicit]
Definition at line 8467 of file maglev-ir.h.
      : Base(bitfield) {}
Member Function Documentation
elements_input()
Input& v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::elements_input () [inline]
Definition at line 8479 of file maglev-ir.h.
{ return input(kElementsIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::GenerateCode (MaglevAssembler * , const ProcessingState &)
index_input()
Input& v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::index_input () [inline]
Definition at line 8480 of file maglev-ir.h.
{ return input(kIndexIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::MaxCallStackArgs () const [inline]
Definition at line 8483 of file maglev-ir.h.
                               {
    // StoreFixedArrayElementNoWriteBarrier never really does any call.
    return 0;
  }
PrintParams()
void v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 8489 of file maglev-ir.h.
{}
SetValueLocationConstraints()
void v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::SetValueLocationConstraints ()
value_input()
Input& v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::value_input () [inline]
Definition at line 8481 of file maglev-ir.h.
{ return input(kValueIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
Member Data Documentation
kElementsIndex
constexpr int v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::kElementsIndex = 0 [static], [constexpr]
Definition at line 8476 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput().
kIndexIndex
constexpr int v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::kIndexIndex = 1 [static], [constexpr]
Definition at line 8477 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput().
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kInt32,
      ValueRepresentation::kTagged}
Definition at line 8472 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::kProperties [static], [constexpr]
Initial value:
=
      OpProperties::CanWrite() | OpProperties::DeferredCall()
Definition at line 8470 of file maglev-ir.h.
kValueIndex
constexpr int v8::internal::maglev::StoreFixedArrayElementNoWriteBarrier::kValueIndex = 2 [static], [constexpr]
Definition at line 8478 of file maglev-ir.h.
Referenced by v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodePhiInput().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h