v8::internal::GlobalHandles::NodeBlock< _NodeType > Class Template Reference
Public Types
using BlockType = NodeBlock< _NodeType >
using NodeType = _NodeType
Public Member Functions
NodeBlock (GlobalHandles *global_handles, GlobalHandles::NodeSpace< NodeType > *space, NodeBlock *next) V8_NOEXCEPT
NodeBlock (const NodeBlock &)=delete
NodeBlock & operator= (const NodeBlock &)=delete
NodeType * at (size_t index)
const NodeType * at (size_t index) const
GlobalHandles::NodeSpace< NodeType > * space () const
GlobalHandles * global_handles () const
bool IncreaseUsage ()
bool DecreaseUsage ()
void ListAdd (NodeBlock **top)
void ListRemove (NodeBlock **top)
NodeBlock * next () const
NodeBlock * next_used () const
const void * begin_address () const
const void * end_address () const
Static Public Member Functions
static const NodeBlock * From (const NodeType *node)
static NodeBlock * From (NodeType *node)
Private Attributes
NodeType nodes_ [kBlockSize]
NodeBlock *const next_
GlobalHandles *const global_handles_
GlobalHandles::NodeSpace< NodeType > *const space_
NodeBlock * next_used_ = nullptr
NodeBlock * prev_used_ = nullptr
uint32_t used_nodes_ = 0
Detailed Description
template<class _NodeType>
class v8::internal::GlobalHandles::NodeBlock< _NodeType >
Definition at line 61 of file global-handles.cc.
Member Typedef Documentation
BlockType
template<class _NodeType >
using v8::internal::GlobalHandles::NodeBlock< _NodeType >::BlockType = NodeBlock<_NodeType>
Definition at line 63 of file global-handles.cc.
NodeType
template<class _NodeType >
using v8::internal::GlobalHandles::NodeBlock< _NodeType >::NodeType = _NodeType
Definition at line 64 of file global-handles.cc.
Constructor & Destructor Documentation
NodeBlock() [1/2]
template<class _NodeType >
v8::internal::GlobalHandles::NodeBlock< _NodeType >::NodeBlock (GlobalHandles * global_handles, GlobalHandles::NodeSpace< NodeType > * space, NodeBlock< _NodeType > * next) [inline]
Definition at line 69 of file global-handles.cc.
                                         : next_(next),
                                           global_handles_(global_handles),
                                           space_(space) {}
NodeBlock() [2/2]
template<class _NodeType >
v8::internal::GlobalHandles::NodeBlock< _NodeType >::NodeBlock (const NodeBlock< _NodeType > &) [delete]
Member Function Documentation
at() [1/2]
template<class _NodeType >
NodeType* v8::internal::GlobalHandles::NodeBlock< _NodeType >::at (size_t index) [inline]
Definition at line 78 of file global-handles.cc.
{ return &nodes_[index]; }
References v8::internal::index, and v8::internal::GlobalHandles::NodeBlock< _NodeType >::nodes_.
Referenced by v8::internal::GlobalHandles::NodeBlock< _NodeType >::From(), and v8::internal::GlobalHandles::NodeSpace< NodeType >::PutNodesOnFreeList().
at() [2/2]
template<class _NodeType >
const NodeType* v8::internal::GlobalHandles::NodeBlock< _NodeType >::at (size_t index) const [inline]
Definition at line 79 of file global-handles.cc.
{ return &nodes_[index]; }
References v8::internal::index, and v8::internal::GlobalHandles::NodeBlock< _NodeType >::nodes_.
begin_address()
template<class _NodeType >
const void* v8::internal::GlobalHandles::NodeBlock< _NodeType >::begin_address () const [inline]
Definition at line 92 of file global-handles.cc.
{ return nodes_; }
References v8::internal::GlobalHandles::NodeBlock< _NodeType >::nodes_.
DecreaseUsage()
template<class _NodeType >
bool v8::internal::GlobalHandles::NodeBlock< NodeType >::DecreaseUsage () [inline]
Definition at line 141 of file global-handles.cc.
                                                     {
  DCHECK_GT(used_nodes_, 0);
  return --used_nodes_ == 0;
}
References DCHECK_GT.
Referenced by v8::internal::GlobalHandles::NodeSpace< NodeType >::Free().
end_address()
template<class _NodeType >
const void* v8::internal::GlobalHandles::NodeBlock< _NodeType >::end_address () const [inline]
Definition at line 93 of file global-handles.cc.
{ return &nodes_[kBlockSize]; }
References v8::internal::anonymous_namespace{global-handles.cc}::kBlockSize, and v8::internal::GlobalHandles::NodeBlock< _NodeType >::nodes_.
From() [1/2]
template<class _NodeType >
const GlobalHandles::NodeBlock< NodeType > * v8::internal::GlobalHandles::NodeBlock< NodeType >::From (const NodeType * node) [inline], [static]
Definition at line 107 of file global-handles.cc.
                                                           {
  const NodeType* firstNode = node - node->index();
  const BlockType* block = reinterpret_cast<const BlockType*>(firstNode);
  DCHECK_EQ(node, block->at(node->index()));
  return block;
}
References v8::internal::GlobalHandles::NodeBlock< _NodeType >::at(), and DCHECK_EQ.
Referenced by v8::internal::GlobalHandles::Node::global_handles().
From() [2/2]
template<class _NodeType >
GlobalHandles::NodeBlock< NodeType > * v8::internal::GlobalHandles::NodeBlock< NodeType >::From (NodeType * node) [inline], [static]
Definition at line 115 of file global-handles.cc.
                    {
  NodeType* firstNode = node - node->index();
  BlockType* block = reinterpret_cast<BlockType*>(firstNode);
  DCHECK_EQ(node, block->at(node->index()));
  return block;
}
References v8::internal::GlobalHandles::NodeBlock< _NodeType >::at(), and DCHECK_EQ.
global_handles()
template<class _NodeType >
GlobalHandles* v8::internal::GlobalHandles::NodeBlock< _NodeType >::global_handles () const [inline]
Definition at line 81 of file global-handles.cc.
{ return global_handles_; }
References v8::internal::GlobalHandles::NodeBlock< _NodeType >::global_handles_.
Referenced by v8::internal::GlobalHandles::Node::global_handles().
IncreaseUsage()
template<class _NodeType >
bool v8::internal::GlobalHandles::NodeBlock< NodeType >::IncreaseUsage () [inline]
Definition at line 124 of file global-handles.cc.
                                                     {
  DCHECK_LT(used_nodes_, kBlockSize);
  return used_nodes_++ == 0;
}
References DCHECK_LT, and v8::internal::anonymous_namespace{global-handles.cc}::kBlockSize.
Referenced by v8::internal::GlobalHandles::NodeSpace< NodeType >::Allocate().
ListAdd()
template<class _NodeType >
void v8::internal::GlobalHandles::NodeBlock< NodeType >::ListAdd (NodeBlock< _NodeType > ** top) [inline]
Definition at line 130 of file global-handles.cc.
                                                              {
  BlockType* old_top = *top;
  *top = this;
  next_used_ = old_top;
  prev_used_ = nullptr;
  if (old_top != nullptr) {
    old_top->prev_used_ = this;
  }
}
References v8::internal::GlobalHandles::NodeBlock< _NodeType >::prev_used_.
Referenced by v8::internal::GlobalHandles::NodeSpace< NodeType >::Allocate().
ListRemove()
template<class _NodeType >
void v8::internal::GlobalHandles::NodeBlock< NodeType >::ListRemove (NodeBlock< _NodeType > ** top) [inline]
Definition at line 147 of file global-handles.cc.
                                                                 {
  if (next_used_ != nullptr) next_used_->prev_used_ = prev_used_;
  if (prev_used_ != nullptr) prev_used_->next_used_ = next_used_;
  if (this == *top) {
    *top = next_used_;
  }
}
Referenced by v8::internal::GlobalHandles::NodeSpace< NodeType >::Free().
next()
template<class _NodeType >
NodeBlock* v8::internal::GlobalHandles::NodeBlock< _NodeType >::next () const [inline]
Definition at line 89 of file global-handles.cc.
{ return next_; }
References v8::internal::GlobalHandles::NodeBlock< _NodeType >::next_.
next_used()
template<class _NodeType >
NodeBlock* v8::internal::GlobalHandles::NodeBlock< _NodeType >::next_used () const [inline]
Definition at line 90 of file global-handles.cc.
{ return next_used_; }
References v8::internal::GlobalHandles::NodeBlock< _NodeType >::next_used_.
operator=()
template<class _NodeType >
NodeBlock& v8::internal::GlobalHandles::NodeBlock< _NodeType >::operator= (const NodeBlock< _NodeType > &) [delete]
space()
template<class _NodeType >
GlobalHandles::NodeSpace<NodeType>* v8::internal::GlobalHandles::NodeBlock< _NodeType >::space () const [inline]
Definition at line 80 of file global-handles.cc.
{ return space_; }
References v8::internal::GlobalHandles::NodeBlock< _NodeType >::space_.
Referenced by v8::internal::GlobalHandles::NodeSpace< NodeType >::Release().
Member Data Documentation
global_handles_
template<class _NodeType >
GlobalHandles* const v8::internal::GlobalHandles::NodeBlock< _NodeType >::global_handles_ [private]
Definition at line 98 of file global-handles.cc.
Referenced by v8::internal::GlobalHandles::NodeBlock< _NodeType >::global_handles().
next_
template<class _NodeType >
NodeBlock* const v8::internal::GlobalHandles::NodeBlock< _NodeType >::next_ [private]
Definition at line 97 of file global-handles.cc.
Referenced by v8::internal::GlobalHandles::NodeBlock< _NodeType >::next().
next_used_
template<class _NodeType >
NodeBlock* v8::internal::GlobalHandles::NodeBlock< _NodeType >::next_used_ = nullptr [private]
Definition at line 100 of file global-handles.cc.
Referenced by v8::internal::GlobalHandles::NodeBlock< _NodeType >::next_used().
nodes_
template<class _NodeType >
NodeType v8::internal::GlobalHandles::NodeBlock< _NodeType >::nodes_[kBlockSize] [private]
Definition at line 96 of file global-handles.cc.
Referenced by v8::internal::GlobalHandles::NodeBlock< _NodeType >::at(), v8::internal::GlobalHandles::NodeBlock< _NodeType >::begin_address(), and v8::internal::GlobalHandles::NodeBlock< _NodeType >::end_address().
prev_used_
template<class _NodeType >
NodeBlock* v8::internal::GlobalHandles::NodeBlock< _NodeType >::prev_used_ = nullptr [private]
Definition at line 101 of file global-handles.cc.
Referenced by v8::internal::GlobalHandles::NodeBlock< _NodeType >::ListAdd().
space_
template<class _NodeType >
GlobalHandles::NodeSpace<NodeType>* const v8::internal::GlobalHandles::NodeBlock< _NodeType >::space_ [private]
Definition at line 99 of file global-handles.cc.
Referenced by v8::internal::GlobalHandles::NodeBlock< _NodeType >::space().
used_nodes_
template<class _NodeType >
uint32_t v8::internal::GlobalHandles::NodeBlock< _NodeType >::used_nodes_ = 0 [private]
Definition at line 102 of file global-handles.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/handles/global-handles.cc