v8::internal::compiler::WasmLoadElimination Class Reference
#include <wasm-load-elimination.h>
Classes
struct AbstractState
struct FieldOrElementValue
class HalfState
Public Member Functions
WasmLoadElimination (Editor *editor, JSGraph *jsgraph, Zone *zone)
~WasmLoadElimination () final=default
WasmLoadElimination (const WasmLoadElimination &)=delete
WasmLoadElimination & operator= (const WasmLoadElimination &)=delete
const char * reducer_name () const override
Reduction Reduce (Node *node) final
Private Member Functions
Reduction ReduceWasmStructGet (Node *node)
Reduction ReduceWasmStructSet (Node *node)
Reduction ReduceWasmArrayLength (Node *node)
Reduction ReduceWasmArrayInitializeLength (Node *node)
Reduction ReduceStringPrepareForGetCodeunit (Node *node)
Reduction ReduceStringAsWtf16 (Node *node)
Reduction ReduceAnyConvertExtern (Node *node)
Reduction ReduceEffectPhi (Node *node)
Reduction ReduceStart (Node *node)
Reduction ReduceOtherNode (Node *node)
Reduction ReduceLoadLikeFromImmutable (Node *node, int index)
Reduction UpdateState (Node *node, AbstractState const *state)
AbstractState const * ComputeLoopState (Node *node, AbstractState const *state) const
std::tuple< Node *, Node * > TruncateAndExtendOrType (Node *value, Node *effect, Node *control, wasm::ValueType field_type, bool is_signed)
Reduction AssertUnreachable (Node *node)
CommonOperatorBuilder * common () const
MachineOperatorBuilder * machine () const
Isolate * isolate () const
TFGraph * graph () const
JSGraph * jsgraph () const
Node * dead () const
Zone * zone () const
AbstractState const * empty_state () const
Private Attributes
AbstractState const empty_state_
NodeAuxData< AbstractState const * > node_states_
JSGraph *const jsgraph_
Node * dead_
Zone * zone_
Detailed Description
Definition at line 23 of file wasm-load-elimination.h.
Constructor & Destructor Documentation
WasmLoadElimination() [1/2]
v8::internal::compiler::WasmLoadElimination::WasmLoadElimination (Editor * editor, JSGraph * jsgraph, Zone * zone)
Definition at line 583 of file wasm-load-elimination.cc.
    : AdvancedReducer(editor),
      empty_state_(zone),
      node_states_(jsgraph->graph()->NodeCount(), zone),
      jsgraph_(jsgraph),
      dead_(jsgraph->Dead()),
      zone_(zone) {}
 WasmLoadElimination()
v8::internal::compiler::WasmLoadElimination::~WasmLoadElimination () [final], [default]
WasmLoadElimination() [2/2]
v8::internal::compiler::WasmLoadElimination::WasmLoadElimination (const WasmLoadElimination &) [delete]
Member Function Documentation
AssertUnreachable()
Reduction v8::internal::compiler::WasmLoadElimination::AssertUnreachable (Node * node) [private]
common()
CommonOperatorBuilder * v8::internal::compiler::WasmLoadElimination::common () const [private]
Definition at line 592 of file wasm-load-elimination.cc.
                                                         {
  return jsgraph()->common();
}
References v8::internal::compiler::MachineGraph::common(), and jsgraph().
Referenced by ReduceWasmStructGet(), ReduceWasmStructSet(), and TruncateAndExtendOrType().
ComputeLoopState()
WasmLoadElimination::AbstractState const * v8::internal::compiler::WasmLoadElimination::ComputeLoopState (Node * node, AbstractState const * state) const [private]
Definition at line 520 of file wasm-load-elimination.cc.
                                                  {
  DCHECK_EQ(node->opcode(), IrOpcode::kEffectPhi);
  if (state->mutable_state.IsEmpty()) return state;
  std::queue<Node*> queue;
  AccountingAllocator allocator;
  Zone temp_set_zone(&allocator, ZONE_NAME);
  ZoneUnorderedSet<Node*> visited(&temp_set_zone);
  visited.insert(node);
  for (int i = 1; i < node->InputCount() - 1; ++i) {
    queue.push(node->InputAt(i));
  }
  while (!queue.empty()) {
    Node* const current = queue.front();
    queue.pop();
    if (visited.insert(current).second) {
      if (current->opcode() == IrOpcode::kWasmStructSet) {
        Node* object = NodeProperties::GetValueInput(current, 0);
        if (object->opcode() == IrOpcode::kDead ||
            object->opcode() == IrOpcode::kDeadValue) {
          // We are in dead code. Bail out with no mutable state.
          return zone()->New<AbstractState>(HalfState(zone()),
                                            state->immutable_state);
        }
        WasmFieldInfo field_info = OpParameter<WasmFieldInfo>(current->op());
        bool is_mutable = field_info.type->mutability(field_info.field_index);
        if (is_mutable) {
          const HalfState* new_mutable_state =
              state->mutable_state.KillField(field_info.field_index, object);
          state = zone()->New<AbstractState>(*new_mutable_state,
                                             state->immutable_state);
        } else {
          // TODO(manoskouk): DCHECK
        }
      } else if (current->opcode() == IrOpcode::kCall &&
                 !current->op()->HasProperty(Operator::kNoWrite)) {
        return zone()->New<AbstractState>(HalfState(zone()),
                                          state->immutable_state);
      }
      for (int i = 0; i < current->op()->EffectInputCount(); ++i) {
        queue.push(NodeProperties::GetEffectInput(current, i));
      }
    }
  }
  return state;
}
References DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::Operator::HasProperty(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::WasmLoadElimination::AbstractState::immutable_state, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::WasmLoadElimination::HalfState::IsEmpty(), v8::internal::compiler::WasmLoadElimination::HalfState::KillField(), v8::internal::compiler::Operator::kNoWrite, v8::internal::compiler::WasmLoadElimination::AbstractState::mutable_state, v8::internal::Zone::New(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), zone(), and ZONE_NAME.
Referenced by ReduceEffectPhi().
dead()
Node* v8::internal::compiler::WasmLoadElimination::dead () const [inline], [private]
Definition at line 153 of file wasm-load-elimination.h.
{ return dead_; }
Referenced by ReduceWasmStructGet(), ReduceWasmStructSet(), and TruncateAndExtendOrType().
empty_state()
AbstractState const* v8::internal::compiler::WasmLoadElimination::empty_state () const [inline], [private]
Definition at line 155 of file wasm-load-elimination.h.
{ return &empty_state_; }
Referenced by ReduceStart().
graph()
TFGraph * v8::internal::compiler::WasmLoadElimination::graph () const [private]
Definition at line 600 of file wasm-load-elimination.cc.
{ return jsgraph()->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph().
Referenced by ReduceWasmStructGet(), ReduceWasmStructSet(), and TruncateAndExtendOrType().
isolate()
Isolate * v8::internal::compiler::WasmLoadElimination::isolate () const [private]
Definition at line 602 of file wasm-load-elimination.cc.
{ return jsgraph()->isolate(); }
References v8::internal::compiler::JSGraph::isolate(), and jsgraph().
jsgraph()
JSGraph* v8::internal::compiler::WasmLoadElimination::jsgraph () const [inline], [private]
Definition at line 152 of file wasm-load-elimination.h.
{ return jsgraph_; }
Referenced by common(), graph(), isolate(), machine(), and TruncateAndExtendOrType().
machine()
MachineOperatorBuilder * v8::internal::compiler::WasmLoadElimination::machine () const [private]
Definition at line 596 of file wasm-load-elimination.cc.
                                                           {
  return jsgraph()->machine();
}
References jsgraph(), and v8::internal::compiler::MachineGraph::machine().
Referenced by TruncateAndExtendOrType().
operator=()
WasmLoadElimination& v8::internal::compiler::WasmLoadElimination::operator= (const WasmLoadElimination &) [delete]
Reduce()
Reduction v8::internal::compiler::WasmLoadElimination::Reduce (Node * node) [final]
Definition at line 139 of file wasm-load-elimination.cc.
                                                {
  if (v8_flags.trace_turbo_load_elimination) {
    // TODO(manoskouk): Add some tracing.
  }
  switch (node->opcode()) {
    case IrOpcode::kWasmStructGet:
      return ReduceWasmStructGet(node);
    case IrOpcode::kWasmStructSet:
      return ReduceWasmStructSet(node);
    case IrOpcode::kWasmArrayLength:
      return ReduceWasmArrayLength(node);
    case IrOpcode::kWasmArrayInitializeLength:
      return ReduceWasmArrayInitializeLength(node);
    case IrOpcode::kStringPrepareForGetCodeunit:
      return ReduceStringPrepareForGetCodeunit(node);
    case IrOpcode::kStringAsWtf16:
      return ReduceStringAsWtf16(node);
    case IrOpcode::kWasmAnyConvertExtern:
      return ReduceAnyConvertExtern(node);
    case IrOpcode::kEffectPhi:
      return ReduceEffectPhi(node);
    case IrOpcode::kDead:
      return NoChange();
    case IrOpcode::kStart:
      return ReduceStart(node);
    default:
      return ReduceOtherNode(node);
  }
}
References v8::kStart, v8::internal::compiler::Node::opcode(), ReduceAnyConvertExtern(), ReduceEffectPhi(), ReduceOtherNode(), ReduceStart(), ReduceStringAsWtf16(), ReduceStringPrepareForGetCodeunit(), ReduceWasmArrayInitializeLength(), ReduceWasmArrayLength(), ReduceWasmStructGet(), ReduceWasmStructSet(), and v8::internal::v8_flags.
ReduceAnyConvertExtern()
Reduction v8::internal::compiler::WasmLoadElimination::ReduceAnyConvertExtern (Node * node) [private]
Definition at line 422 of file wasm-load-elimination.cc.
                                                                {
  DCHECK_EQ(node->opcode(), IrOpcode::kWasmAnyConvertExtern);
  // An externref is not immutable meaning it could change. However, the values
  // relevant for any.convert_extern (null, HeapNumber, Smi) are immutable, so
  // we can treat the externref as immutable.
  return ReduceLoadLikeFromImmutable(node, kAnyConvertExternIndex);
}
References DCHECK_EQ, v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::kAnyConvertExternIndex, v8::internal::compiler::Node::opcode(), and ReduceLoadLikeFromImmutable().
Referenced by Reduce().
ReduceEffectPhi()
Reduction v8::internal::compiler::WasmLoadElimination::ReduceEffectPhi (Node * node) [private]
Definition at line 457 of file wasm-load-elimination.cc.
                                                         {
  DCHECK_EQ(node->opcode(), IrOpcode::kEffectPhi);
  Node* const effect0 = NodeProperties::GetEffectInput(node, 0);
  Node* const control = NodeProperties::GetControlInput(node);
  AbstractState const* state0 = node_states_.Get(effect0);
  if (state0 == nullptr) return NoChange();
  if (control->opcode() == IrOpcode::kLoop) {
    // Here we rely on having only reducible loops:
    // The loop entry edge always dominates the header, so we can just take
    // the state from the first input, and compute the loop state based on it.
    AbstractState const* state = ComputeLoopState(node, state0);
    return UpdateState(node, state);
  }
  DCHECK_EQ(IrOpcode::kMerge, control->opcode());
  // Shortcut for the case when we do not know anything about some input.
  int const input_count = node->op()->EffectInputCount();
  for (int i = 1; i < input_count; ++i) {
    Node* const effect = NodeProperties::GetEffectInput(node, i);
    if (node_states_.Get(effect) == nullptr) return NoChange();
  }
  // Make a copy of the first input's state and intersect it with the state
  // from other inputs.
  // TODO(manoskouk): Consider computing phis for at least a subset of the
  // state.
  AbstractState* state = zone()->New<AbstractState>(*state0);
  for (int i = 1; i < input_count; ++i) {
    Node* const input = NodeProperties::GetEffectInput(node, i);
    state->IntersectWith(node_states_.Get(input));
  }
  return UpdateState(node, state);
}
References ComputeLoopState(), DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::WasmLoadElimination::AbstractState::IntersectWith(), v8::internal::Zone::New(), node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), UpdateState(), and zone().
Referenced by Reduce().
ReduceLoadLikeFromImmutable()
Reduction v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable (Node * node, int index) [private]
Definition at line 324 of file wasm-load-elimination.cc.
                                                                      {
  // The index must be negative as it is not a real load, to not confuse it with
  // actual loads.
  DCHECK_LT(index, 0);
  Node* object = ResolveAliases(NodeProperties::GetValueInput(node, 0));
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  if (object->opcode() == IrOpcode::kDead) return NoChange();
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  HalfState const* immutable_state = &state->immutable_state;
  FieldOrElementValue lookup_result =
      immutable_state->LookupField(index, object);
  if (!lookup_result.IsEmpty() && !lookup_result.value->IsDead()) {
    ReplaceWithValue(node, lookup_result.value, effect, control);
    node->Kill();
    return Replace(lookup_result.value);
  }
  immutable_state = immutable_state->AddField(index, object, node);
  AbstractState const* new_state =
      zone()->New<AbstractState>(state->mutable_state, *immutable_state);
  return UpdateState(node, new_state);
}
References v8::internal::compiler::WasmLoadElimination::HalfState::AddField(), DCHECK_LT, v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::WasmLoadElimination::AbstractState::immutable_state, v8::internal::index, v8::internal::compiler::Node::IsDead(), v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::IsEmpty(), v8::internal::compiler::Node::Kill(), v8::internal::compiler::WasmLoadElimination::HalfState::LookupField(), v8::internal::compiler::WasmLoadElimination::AbstractState::mutable_state, v8::internal::Zone::New(), node_states_, v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::ResolveAliases(), UpdateState(), v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::value, and zone().
Referenced by ReduceAnyConvertExtern(), ReduceStringAsWtf16(), and ReduceWasmArrayLength().
ReduceOtherNode()
Reduction v8::internal::compiler::WasmLoadElimination::ReduceOtherNode (Node * node) [private]
Definition at line 430 of file wasm-load-elimination.cc.
                                                         {
  if (node->op()->EffectOutputCount() == 0) return NoChange();
  DCHECK_EQ(node->op()->EffectInputCount(), 1);
  Node* const effect = NodeProperties::GetEffectInput(node);
  AbstractState const* state = node_states_.Get(effect);
  // If we do not know anything about the predecessor, do not propagate just
  // yet because we will have to recompute anyway once we compute the
  // predecessor.
  if (state == nullptr) return NoChange();
  // If this {node} has some uncontrolled side effects (i.e. it is a call
  // without {kNoWrite}), set its state to the immutable half-state of its
  // input state, otherwise to its input state.
  // Any cached StringPrepareForGetCodeUnit nodes must be killed at any point
  // that can cause internalization of strings (i.e. that can turn sequential
  // strings into thin strings). Currently, that can only happen in JS, so
  // from Wasm's point of view only in calls.
  return UpdateState(node, node->opcode() == IrOpcode::kCall &&
                                   !node->op()->HasProperty(Operator::kNoWrite)
                               ? zone()->New<AbstractState>(
                                     HalfState(zone()), state->immutable_state)
                               : state);
}
References DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::WasmLoadElimination::AbstractState::immutable_state, v8::internal::compiler::Operator::kNoWrite, node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), UpdateState(), and zone().
Referenced by Reduce().
reducer_name()
const char* v8::internal::compiler::WasmLoadElimination::reducer_name () const [inline], [override]
Definition at line 31 of file wasm-load-elimination.h.
{ return "WasmLoadElimination"; }
ReduceStart()
Reduction v8::internal::compiler::WasmLoadElimination::ReduceStart (Node * node) [private]
Definition at line 453 of file wasm-load-elimination.cc.
                                                     {
  return UpdateState(node, empty_state());
}
References empty_state(), and UpdateState().
Referenced by Reduce().
ReduceStringAsWtf16()
Reduction v8::internal::compiler::WasmLoadElimination::ReduceStringAsWtf16 (Node * node) [private]
Definition at line 417 of file wasm-load-elimination.cc.
                                                             {
  DCHECK_EQ(node->opcode(), IrOpcode::kStringAsWtf16);
  return ReduceLoadLikeFromImmutable(node, kStringAsWtf16Index);
}
References DCHECK_EQ, v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::kStringAsWtf16Index, v8::internal::compiler::Node::opcode(), and ReduceLoadLikeFromImmutable().
Referenced by Reduce().
ReduceStringPrepareForGetCodeunit()
Reduction v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit (Node * node) [private]
Definition at line 381 of file wasm-load-elimination.cc.
                                                                           {
  DCHECK_EQ(node->opcode(), IrOpcode::kStringPrepareForGetCodeunit);
  Node* object = ResolveAliases(NodeProperties::GetValueInput(node, 0));
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  if (object->opcode() == IrOpcode::kDead) return NoChange();
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  HalfState const* mutable_state = &state->mutable_state;
  FieldOrElementValue lookup_result =
      mutable_state->LookupField(kStringPrepareForGetCodeunitIndex, object);
  if (!lookup_result.IsEmpty() && !lookup_result.value->IsDead()) {
    for (size_t i : {0, 1, 2}) {
      Node* proj_to_replace = NodeProperties::FindProjection(node, i);
      ReplaceWithValue(proj_to_replace,
                       NodeProperties::FindProjection(lookup_result.value, i));
      proj_to_replace->Kill();
    }
    ReplaceWithValue(node, lookup_result.value, effect, control);
    node->Kill();
    return Replace(lookup_result.value);
  }
  mutable_state =
      mutable_state->AddField(kStringPrepareForGetCodeunitIndex, object, node);
  AbstractState const* new_state =
      zone()->New<AbstractState>(*mutable_state, state->immutable_state);
  return UpdateState(node, new_state);
}
References v8::internal::compiler::WasmLoadElimination::HalfState::AddField(), DCHECK_EQ, v8::internal::compiler::NodeProperties::FindProjection(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::WasmLoadElimination::AbstractState::immutable_state, v8::internal::compiler::Node::IsDead(), v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::IsEmpty(), v8::internal::compiler::Node::Kill(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::kStringPrepareForGetCodeunitIndex, v8::internal::compiler::WasmLoadElimination::HalfState::LookupField(), v8::internal::compiler::WasmLoadElimination::AbstractState::mutable_state, v8::internal::Zone::New(), node_states_, v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::ResolveAliases(), UpdateState(), v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::value, and zone().
Referenced by Reduce().
ReduceWasmArrayInitializeLength()
Reduction v8::internal::compiler::WasmLoadElimination::ReduceWasmArrayInitializeLength (Node * node) [private]
Definition at line 361 of file wasm-load-elimination.cc.
                                                                         {
  DCHECK_EQ(node->opcode(), IrOpcode::kWasmArrayInitializeLength);
  Node* object = ResolveAliases(NodeProperties::GetValueInput(node, 0));
  Node* value = NodeProperties::GetValueInput(node, 1);
  Node* effect = NodeProperties::GetEffectInput(node);
  if (object->opcode() == IrOpcode::kDead) return NoChange();
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  // We should not initialize the length twice.
  DCHECK(state->immutable_state.LookupField(kArrayLengthFieldIndex, object)
             .IsEmpty());
  HalfState const* immutable_state =
      state->immutable_state.AddField(kArrayLengthFieldIndex, object, value);
  AbstractState const* new_state =
      zone()->New<AbstractState>(state->mutable_state, *immutable_state);
  return UpdateState(node, new_state);
}
References v8::internal::compiler::WasmLoadElimination::HalfState::AddField(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetValueInput(), v8::internal::compiler::WasmLoadElimination::AbstractState::immutable_state, v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::IsEmpty(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::kArrayLengthFieldIndex, v8::internal::compiler::WasmLoadElimination::HalfState::LookupField(), v8::internal::compiler::WasmLoadElimination::AbstractState::mutable_state, v8::internal::Zone::New(), node_states_, v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::ResolveAliases(), UpdateState(), v8::internal::value, and zone().
Referenced by Reduce().
ReduceWasmArrayLength()
Reduction v8::internal::compiler::WasmLoadElimination::ReduceWasmArrayLength (Node * node) [private]
Definition at line 356 of file wasm-load-elimination.cc.
                                                               {
  DCHECK_EQ(node->opcode(), IrOpcode::kWasmArrayLength);
  return ReduceLoadLikeFromImmutable(node, kArrayLengthFieldIndex);
}
References DCHECK_EQ, v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::kArrayLengthFieldIndex, v8::internal::compiler::Node::opcode(), and ReduceLoadLikeFromImmutable().
Referenced by Reduce().
ReduceWasmStructGet()
Reduction v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet (Node * node) [private]
Definition at line 169 of file wasm-load-elimination.cc.
                                                             {
  DCHECK_EQ(node->opcode(), IrOpcode::kWasmStructGet);
  Node* input_struct = NodeProperties::GetValueInput(node, 0);
  Node* object = ResolveAliases(input_struct);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  if (object->opcode() == IrOpcode::kDead) return NoChange();
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  const WasmFieldInfo& field_info = OpParameter<WasmFieldInfo>(node->op());
  bool is_mutable = field_info.type->mutability(field_info.field_index);
  if (!NodeProperties::IsTyped(input_struct) ||
      !NodeProperties::GetType(input_struct).IsWasm()) {
    // The input should always be typed. https://crbug.com/1507106 reported
    // that we can end up with Type None here instead of a wasm type.
    // In the worst case this only means that we miss a potential optimization,
    // still the assumption is that all inputs into StructGet should be typed.
    return NoChange();
  }
  // Skip reduction if the input type is nullref. in this case, the struct get
  // will always trap.
  wasm::ValueType struct_type =
      NodeProperties::GetType(input_struct).AsWasm().type;
  if (struct_type == wasm::kWasmNullRef) {
    return NoChange();
  }
  // The node is in unreachable code if its input is uninhabitable (bottom or
  // ref none type). It can also be treated as unreachable if the field index is
  // in the wrong half state. This can happen if an object gets cast to two
  // unrelated types subsequently (as the state only tracks the field index)
  // independent of the underlying type.
  if (struct_type.is_uninhabited() ||
      !(is_mutable ? state->immutable_state : state->mutable_state)
           .LookupField(field_info.field_index, object)
           .IsEmpty()) {
    ReplaceWithValue(node, dead(), dead(), dead());
    MergeControlToEnd(graph(), common(),
                      graph()->NewNode(common()->Throw(), effect, control));
    node->Kill();
    return Replace(dead());
  }
  // If the input type is not (ref null? none) or bottom and we don't have type
  // inconsistencies, then the result type must be valid.
  DCHECK(!NodeProperties::GetType(node).AsWasm().type.is_bottom());
  HalfState const* half_state =
      is_mutable ? &state->mutable_state : &state->immutable_state;
  FieldOrElementValue lookup_result =
      half_state->LookupField(field_info.field_index, object);
  if (!lookup_result.IsEmpty() && !lookup_result.value->IsDead()) {
    std::tuple<Node*, Node*> replacement = TruncateAndExtendOrType(
        lookup_result.value, effect, control,
        field_info.type->field(field_info.field_index), field_info.is_signed);
    if (std::get<0>(replacement) == dead()) {
      // If the value is dead (unreachable), this whole code path is unreachable
      // and we can mark this control flow path as dead.
      ReplaceWithValue(node, dead(), dead(), dead());
      MergeControlToEnd(graph(), common(),
                        graph()->NewNode(common()->Throw(), effect, control));
      node->Kill();
      return Replace(dead());
    }
    ReplaceWithValue(node, std::get<0>(replacement), std::get<1>(replacement),
                     control);
    node->Kill();
    return Replace(std::get<0>(replacement));
  }
  half_state = half_state->AddField(field_info.field_index, object, node);
  AbstractState const* new_state =
      is_mutable
          ? zone()->New<AbstractState>(*half_state, state->immutable_state)
          : zone()->New<AbstractState>(state->mutable_state, *half_state);
  return UpdateState(node, new_state);
}
References v8::internal::compiler::WasmLoadElimination::HalfState::AddField(), common(), v8::internal::DCHECK(), DCHECK_EQ, dead(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::WasmLoadElimination::AbstractState::immutable_state, v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::compiler::Node::IsDead(), v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::IsEmpty(), v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::compiler::Node::Kill(), v8::internal::wasm::kWasmNullRef, v8::internal::compiler::WasmLoadElimination::HalfState::LookupField(), v8::internal::compiler::WasmLoadElimination::AbstractState::mutable_state, v8::internal::Zone::New(), node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::ResolveAliases(), TruncateAndExtendOrType(), v8::internal::compiler::Node::type(), v8::internal::tracing::type, UpdateState(), v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::value, and zone().
Referenced by Reduce().
ReduceWasmStructSet()
Reduction v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet (Node * node) [private]
Definition at line 252 of file wasm-load-elimination.cc.
                                                             {
  DCHECK_EQ(node->opcode(), IrOpcode::kWasmStructSet);
  Node* input_struct = NodeProperties::GetValueInput(node, 0);
  Node* object = ResolveAliases(input_struct);
  Node* value = NodeProperties::GetValueInput(node, 1);
  Node* effect = NodeProperties::GetEffectInput(node);
  Node* control = NodeProperties::GetControlInput(node);
  if (object->opcode() == IrOpcode::kDead) return NoChange();
  AbstractState const* state = node_states_.Get(effect);
  if (state == nullptr) return NoChange();
  if (!NodeProperties::IsTyped(input_struct) ||
      !NodeProperties::GetType(input_struct).IsWasm()) {
    // Also see the same pattern in ReduceWasmStructGet. Note that this is
    // reached for cases where the StructSet has a value input that is
    // DeadValue(). Above we check for `object->opcode() == IrOpcode::kDead.
    // As an alternative that check could be extended to also check for
    // ... || object->opcode() == IrOpcode::kDeadValue.
    // It seems that the DeadValue may be caused by
    // DeadCodeElimination::ReducePureNode. If that finds any input that is a
    // Dead() node, it will replace that input with a DeadValue().
    return NoChange();
  }
  // Skip reduction if the input type is nullref. in this case, the struct get
  // will always trap.
  wasm::ValueType struct_type =
      NodeProperties::GetType(input_struct).AsWasm().type;
  if (struct_type == wasm::kWasmNullRef) {
    return NoChange();
  }
  const WasmFieldInfo& field_info = OpParameter<WasmFieldInfo>(node->op());
  bool is_mutable = field_info.type->mutability(field_info.field_index);
  // The struct.set is unreachable if its input struct is an uninhabitable type.
  // It can also be treated as unreachable if the field index is in the wrong
  // half state. This can happen if an object gets cast to two unrelated types
  // subsequently (as the state only tracks the field index) independent of the
  // underlying type.
  if (struct_type.is_uninhabited() ||
      !(is_mutable ? state->immutable_state : state->mutable_state)
           .LookupField(field_info.field_index, object)
           .IsEmpty()) {
    ReplaceWithValue(node, dead(), dead(), dead());
    MergeControlToEnd(graph(), common(),
                      graph()->NewNode(common()->Throw(), effect, control));
    node->Kill();
    return Replace(dead());
  }
  if (is_mutable) {
    HalfState const* mutable_state =
        state->mutable_state.KillField(field_info.field_index, object);
    mutable_state =
        mutable_state->AddField(field_info.field_index, object, value);
    AbstractState const* new_state =
        zone()->New<AbstractState>(*mutable_state, state->immutable_state);
    return UpdateState(node, new_state);
  } else {
    // We should not initialize the same immutable field twice.
    DCHECK(state->immutable_state.LookupField(field_info.field_index, object)
               .IsEmpty());
    HalfState const* immutable_state =
        state->immutable_state.AddField(field_info.field_index, object, value);
    AbstractState const* new_state =
        zone()->New<AbstractState>(state->mutable_state, *immutable_state);
    return UpdateState(node, new_state);
  }
}
References v8::internal::compiler::WasmLoadElimination::HalfState::AddField(), common(), v8::internal::DCHECK(), DCHECK_EQ, dead(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::WasmLoadElimination::AbstractState::immutable_state, v8::internal::wasm::ValueTypeBase::is_uninhabited(), v8::internal::compiler::WasmLoadElimination::FieldOrElementValue::IsEmpty(), v8::internal::compiler::NodeProperties::IsTyped(), v8::internal::compiler::Node::Kill(), v8::internal::compiler::WasmLoadElimination::HalfState::KillField(), v8::internal::wasm::kWasmNullRef, v8::internal::compiler::WasmLoadElimination::HalfState::LookupField(), v8::internal::compiler::WasmLoadElimination::AbstractState::mutable_state, v8::internal::Zone::New(), node_states_, v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::anonymous_namespace{bitcast-elider.cc}::Replace(), v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::ResolveAliases(), UpdateState(), v8::internal::value, and zone().
Referenced by Reduce().
TruncateAndExtendOrType()
std::tuple< Node *, Node * > v8::internal::compiler::WasmLoadElimination::TruncateAndExtendOrType (Node * value, Node * effect, Node * control, wasm::ValueType field_type, bool is_signed) [private]
Definition at line 85 of file wasm-load-elimination.cc.
                    {
  if (field_type == wasm::kWasmI8 || field_type == wasm::kWasmI16) {
    Node* ret = nullptr;
    if (is_signed) {
      int shift = 32 - 8 * field_type.value_kind_size();
      ret = graph()->NewNode(machine()->Word32Sar(),
                             graph()->NewNode(machine()->Word32Shl(), value,
                                              jsgraph()->Int32Constant(shift)),
                             jsgraph()->Int32Constant(shift));
    } else {
      int mask = (1 << 8 * field_type.value_kind_size()) - 1;
      ret = graph()->NewNode(machine()->Word32And(), value,
                             jsgraph()->Int32Constant(mask));
    }
    NodeProperties::SetType(ret, NodeProperties::GetType(value));
    return {ret, effect};
  }
  // The value might be untyped in case of wasm inlined into JS if the value
  // comes from a JS node.
  if (!NodeProperties::IsTyped(value)) {
    return {value, effect};
  }
  Type value_type = NodeProperties::GetType(value);
  if (!value_type.IsWasm()) {
    return {value, effect};
  }
  wasm::TypeInModule node_type = value_type.AsWasm();
  if (TypesUnrelated(node_type.type, field_type, node_type.module)) {
    // Unrelated types can occur as a result of unreachable code.
    // Example: Storing a value x of type A in a struct, then casting the struct
    // to a different struct type to then load type B from the same offset
    // results in trying to replace the load with value x.
    return {dead(), dead()};
  }
  if (!wasm::IsSubtypeOf(node_type.type, field_type, node_type.module)) {
    Type type = Type::Wasm({field_type, node_type.module}, graph()->zone());
    Node* ret =
        graph()->NewNode(common()->TypeGuard(type), value, effect, control);
    NodeProperties::SetType(ret, type);
    return {ret, ret};
  }
  return {value, effect};
}
References common(), dead(), v8::internal::compiler::NodeProperties::GetType(), graph(), v8::internal::is_signed(), v8::internal::wasm::IsSubtypeOf(), v8::internal::compiler::NodeProperties::IsTyped(), jsgraph(), v8::internal::wasm::kWasmI16, v8::internal::wasm::kWasmI8, machine(), v8::internal::wasm::TypeInModule::module, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::NodeProperties::SetType(), v8::internal::tracing::type, v8::internal::wasm::TypeInModule::type, v8::internal::compiler::anonymous_namespace{wasm-load-elimination.cc}::TypesUnrelated(), v8::internal::value, v8::internal::wasm::ValueTypeBase::value_kind_size(), v8::internal::wasm::value_type(), and v8::internal::compiler::TFGraph::zone().
Referenced by ReduceWasmStructGet().
UpdateState()
Reduction v8::internal::compiler::WasmLoadElimination::UpdateState (Node * node, AbstractState const * state) [private]
Definition at line 71 of file wasm-load-elimination.cc.
                                                                       {
  AbstractState const* original = node_states_.Get(node);
  // Only signal that the {node} has Changed, if the information about {state}
  // has changed wrt. the {original}.
  if (state != original) {
    if (original == nullptr || !state->Equals(original)) {
      node_states_.Set(node, state);
      return Changed(node);
    }
  }
  return NoChange();
}
References v8::internal::compiler::WasmLoadElimination::AbstractState::Equals(), and node_states_.
Referenced by ReduceEffectPhi(), ReduceLoadLikeFromImmutable(), ReduceOtherNode(), ReduceStart(), ReduceStringPrepareForGetCodeunit(), ReduceWasmArrayInitializeLength(), ReduceWasmStructGet(), and ReduceWasmStructSet().
zone()
Zone* v8::internal::compiler::WasmLoadElimination::zone () const [inline], [private]
Definition at line 154 of file wasm-load-elimination.h.
{ return zone_; }
Referenced by ComputeLoopState(), ReduceEffectPhi(), ReduceLoadLikeFromImmutable(), ReduceOtherNode(), ReduceStringPrepareForGetCodeunit(), ReduceWasmArrayInitializeLength(), ReduceWasmStructGet(), and ReduceWasmStructSet().
Member Data Documentation
dead_
Node* v8::internal::compiler::WasmLoadElimination::dead_ [private]
Definition at line 160 of file wasm-load-elimination.h.
empty_state_
AbstractState const v8::internal::compiler::WasmLoadElimination::empty_state_ [private]
Definition at line 157 of file wasm-load-elimination.h.
jsgraph_
JSGraph* const v8::internal::compiler::WasmLoadElimination::jsgraph_ [private]
Definition at line 159 of file wasm-load-elimination.h.
node_states_
NodeAuxData<AbstractState const*> v8::internal::compiler::WasmLoadElimination::node_states_ [private]
Definition at line 158 of file wasm-load-elimination.h.
Referenced by ReduceEffectPhi(), ReduceLoadLikeFromImmutable(), ReduceOtherNode(), ReduceStringPrepareForGetCodeunit(), ReduceWasmArrayInitializeLength(), ReduceWasmStructGet(), ReduceWasmStructSet(), and UpdateState().
zone_
Zone* v8::internal::compiler::WasmLoadElimination::zone_ [private]
Definition at line 161 of file wasm-load-elimination.h.
Referenced by v8::internal::compiler::WasmLoadElimination::HalfState::AddField(), and v8::internal::compiler::WasmLoadElimination::HalfState::KillField().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/wasm-load-elimination.h
/mnt/V8SourceCode/src/compiler/wasm-load-elimination.cc