v8::internal::UnifiedHeapVerificationState Class Reference
#include <unified-heap-marking-verifier.h>
Public Member Functions
void VerifyMarkedTracedReference (const TracedReferenceBase &ref) const
Additional Inherited Members
Detailed Description
Definition at line 14 of file unified-heap-marking-verifier.h.
Member Function Documentation
VerifyMarkedTracedReference()
void v8::internal::UnifiedHeapVerificationState::VerifyMarkedTracedReference (const TracedReferenceBase & ref) const
Definition at line 60 of file unified-heap-marking-verifier.cc.
                                          {
  // The following code will crash with null pointer derefs when finding a
  // non-empty `TracedReferenceBase` when `CppHeap` is in detached mode.
  Address* traced_handle_location =
      BasicTracedReferenceExtractor::GetObjectSlotForMarking(ref);
  // We cannot assume that the reference is non-null as we may get here by
  // tracing an ephemeron which doesn't have early bailouts, see
  // `cppgc::Visitor::TraceEphemeron()` for non-Member values.
  if (!traced_handle_location) {
    return;
  }
  // Verification runs after unamrked nodes are freed. The node for this
  // TracedReference should still be marked as in use.
  if (!TracedHandles::IsValidInUseNode(traced_handle_location)) {
    FATAL(
        "MarkingVerifier: Encountered unmarked TracedReference.\n"
        "#\n"
        "# Hint:\n"
        "# %s (%p)\n"
        "# \\-> TracedReference (%p)",
        parent_
            ? parent_
                  ->GetName(cppgc::internal::HeapObjectNameForUnnamedObject::
                                kUseClassNameIfSupported)
                  .value
            : "Stack",
        parent_ ? parent_->ObjectStart() : nullptr, &ref);
  }
}
References FATAL, v8::internal::BasicTracedReferenceExtractor::GetObjectSlotForMarking(), v8::internal::TracedHandles::IsValidInUseNode(), cppgc::internal::HeapObjectHeader::ObjectStart(), cppgc::internal::VerificationState::parent_, and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc-js/unified-heap-marking-verifier.h
/mnt/V8SourceCode/src/heap/cppgc-js/unified-heap-marking-verifier.cc