v8::internal::Register Class Reference
#include <register-arm.h>
Public Member Functions
bool is_byte_register () const
constexpr bool is_byte_register () const
constexpr int high_bit () const
constexpr int low_bits () const
Static Public Member Functions
static constexpr Register no_reg ()
static constexpr Register Create (int code, int size)
static Register XRegFromCode (unsigned code)
static Register WRegFromCode (unsigned code)
static constexpr Register from_code (int code)
static const char * GetSpecialRegisterName (int code)
Static Public Attributes
static constexpr int kMantissaOffset = 0
static constexpr int kExponentOffset = 4
Private Member Functions
constexpr Register (int code)
constexpr Register (const CPURegister &r)
constexpr Register (int code)
constexpr Register (int code)
constexpr Register (int code)
constexpr Register (int code)
constexpr Register (int code)
constexpr Register (int code)
constexpr Register (int code)
Friends
class RegisterBase
class RegisterBase< Register, kRegAfterLast >
Additional Inherited Members
Detailed Description
Definition at line 70 of file register-arm.h.
Constructor & Destructor Documentation
Register() [1/9]
constexpr v8::internal::Register::Register (int code) [inline], [explicit], [constexpr], [private]
Definition at line 73 of file register-arm.h.
: RegisterBase(code) {}
Referenced by Create(), and no_reg().
Register() [2/9]
constexpr v8::internal::Register::Register (const CPURegister & r) [inline], [explicit], [constexpr], [private]
Definition at line 267 of file register-arm64.h.
: CPURegister(r) {}
Register() [3/9]
constexpr v8::internal::Register::Register (int code) [inline], [explicit], [constexpr], [private]
Definition at line 68 of file register-ia32.h.
: RegisterBase(code) {}
Register() [4/9]
constexpr v8::internal::Register::Register (int code) [inline], [explicit], [constexpr], [private]
Definition at line 104 of file register-loong64.h.
: RegisterBase(code) {}
Register() [5/9]
constexpr v8::internal::Register::Register (int code) [inline], [explicit], [constexpr], [private]
Definition at line 105 of file register-mips64.h.
: RegisterBase(code) {}
Register() [6/9]
constexpr v8::internal::Register::Register (int code) [inline], [explicit], [constexpr], [private]
Definition at line 141 of file register-ppc.h.
: RegisterBase(code) {}
Register() [7/9]
constexpr v8::internal::Register::Register (int code) [inline], [explicit], [constexpr], [private]
Definition at line 166 of file register-riscv.h.
: RegisterBase(code) {}
Register() [8/9]
constexpr v8::internal::Register::Register (int code) [inline], [explicit], [constexpr], [private]
Definition at line 136 of file register-s390.h.
: RegisterBase(code) {}
Register() [9/9]
constexpr v8::internal::Register::Register (int code) [inline], [explicit], [constexpr], [private]
Definition at line 73 of file register-x64.h.
: RegisterBase(code) {}
Member Function Documentation
Create()
static constexpr Register v8::internal::Register::Create (int code, int size) [inline], [static], [constexpr]
Definition at line 250 of file register-arm64.h.
                                                       {
    return Register(CPURegister::Create(code, size, CPURegister::kRegister));
  }
References v8::internal::RegisterBase< Register, kRegAfterLast >::code(), v8::internal::CPURegister::Create(), v8::internal::CPURegister::kRegister, Register(), and size().
Referenced by v8::internal::UseScratchRegisterScope::AcquireSameSizeAs(), from_code(), v8::internal::CPURegister::Reg(), WRegFromCode(), and XRegFromCode().
from_code()
static constexpr Register v8::internal::Register::from_code (int code) [inline], [static], [constexpr]
Definition at line 257 of file register-arm64.h.
                                                {
    // Always return an X register.
    return Register::Create(code, kXRegSizeInBits);
  }
References v8::internal::RegisterBase< Register, kRegAfterLast >::code(), Create(), and v8::internal::kXRegSizeInBits.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNodeResult(), v8::internal::maglev::StraightForwardRegisterAllocator::AssignFixedInput(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::wasm::LiftoffRegister::from_code(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_ContinueToBuiltinHelper(), v8::internal::compiler::LocationOperand::GetRegister(), v8::internal::GetRegisterThatIsNotOneOf(), v8::internal::wasm::LiftoffRegister::gp(), v8::internal::wasm::LiftoffRegister::high_gp(), v8::internal::wasm::LiftoffRegister::low_gp(), v8::internal::Operand::Operand(), v8::internal::compiler::operator<<(), v8::internal::MacroAssembler::PopAll(), v8::internal::wasm::LiftoffAssembler::PrepareCall(), v8::internal::compiler::GraphC1Visualizer::PrintLiveRange(), v8::internal::MacroAssembler::PushAll(), v8::internal::compiler::RegisterAllocator::RegisterName(), v8::internal::RegisterConfiguration::RestrictGeneralRegisters(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunctionBody(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::RegisterAllocator::WithAllocatableGeneralRegisters().
GetSpecialRegisterName()
static const char* v8::internal::Register::GetSpecialRegisterName (int code) [inline], [static]
Definition at line 262 of file register-arm64.h.
                                                      {
    return (code == kSPRegInternalCode) ? "sp" : "UNKNOWN";
  }
References v8::internal::RegisterBase< Register, kRegAfterLast >::code(), and v8::internal::kSPRegInternalCode.
Referenced by v8::internal::compiler::operator<<().
high_bit()
constexpr int v8::internal::Register::high_bit () const [inline], [constexpr]
Definition at line 66 of file register-x64.h.
{ return code() >> 3; }
References v8::internal::RegisterBase< Register, kRegAfterLast >::code().
Referenced by v8::internal::Assembler::emit_optional_rex_32(), v8::internal::Assembler::emit_rex_32(), v8::internal::Assembler::emit_rex_64(), v8::internal::Operand::set_modrm(), and v8::internal::Operand::set_sib().
is_byte_register() [1/2]
bool v8::internal::Register::is_byte_register () const [inline]
Definition at line 64 of file register-ia32.h.
{ return code() <= 3; }
References v8::internal::RegisterBase< Register, kRegAfterLast >::code().
Referenced by v8::internal::wasm::liftoff::AtomicBinop32(), v8::internal::Assembler::cmpb(), v8::internal::Assembler::emit_optional_rex_8(), and v8::internal::wasm::liftoff::GetTmpByteRegister().
is_byte_register() [2/2]
constexpr bool v8::internal::Register::is_byte_register () const [inline], [constexpr]
Definition at line 63 of file register-x64.h.
{ return code() <= 3; }
References v8::internal::RegisterBase< Register, kRegAfterLast >::code().
low_bits()
constexpr int v8::internal::Register::low_bits () const [inline], [constexpr]
Definition at line 69 of file register-x64.h.
{ return code() & 0x7; }
References v8::internal::RegisterBase< Register, kRegAfterLast >::code().
Referenced by v8::internal::Assembler::emit_modrm(), v8::internal::Assembler::emit_operand(), v8::internal::Operand::set_modrm(), and v8::internal::Operand::set_sib().
no_reg()
static constexpr Register v8::internal::Register::no_reg () [inline], [static], [constexpr]
Definition at line 248 of file register-arm64.h.
{ return Register(CPURegister::no_reg()); }
References v8::internal::CPURegister::no_reg(), and Register().
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), v8::internal::maglev::MaglevAssembler::CheckInt32IsSmi(), v8::internal::ReassignRegister(), v8::internal::baseline::BaselineAssembler::Switch(), and v8::internal::maglev::MaglevAssembler::TryMigrateInstance().
WRegFromCode()
Register v8::internal::Register::WRegFromCode (unsigned code) [inline], [static]
Definition at line 108 of file assembler-arm64-inl.h.
                                                    {
  if (code == kSPRegInternalCode) {
    return wsp;
  } else {
    DCHECK_LT(code, static_cast<unsigned>(kNumberOfRegisters));
    return Register::Create(code, kWRegSizeInBits);
  }
}
References v8::internal::RegisterBase< Register, kRegAfterLast >::code(), Create(), DCHECK_LT, v8::internal::kNumberOfRegisters, v8::internal::kSPRegInternalCode, and v8::internal::kWRegSizeInBits.
Referenced by v8::internal::CPURegister::W().
XRegFromCode()
Register v8::internal::Register::XRegFromCode (unsigned code) [inline], [static]
Definition at line 99 of file assembler-arm64-inl.h.
                                                    {
  if (code == kSPRegInternalCode) {
    return sp;
  } else {
    DCHECK_LT(code, static_cast<unsigned>(kNumberOfRegisters));
    return Register::Create(code, kXRegSizeInBits);
  }
}
References v8::internal::RegisterBase< Register, kRegAfterLast >::code(), Create(), DCHECK_LT, v8::internal::kNumberOfRegisters, v8::internal::kSPRegInternalCode, and v8::internal::kXRegSizeInBits.
Referenced by v8::internal::CPURegister::X().
Friends And Related Function Documentation
RegisterBase
RegisterBase [friend]
Definition at line 71 of file register-arm.h.
RegisterBase< Register, kRegAfterLast >
friend class RegisterBase< Register, kRegAfterLast > [friend]
Definition at line 64 of file register-ia32.h.
Member Data Documentation
kExponentOffset
static constexpr int v8::internal::Register::kExponentOffset = 4 [static], [constexpr]
Definition at line 100 of file register-loong64.h.
kMantissaOffset
static constexpr int v8::internal::Register::kMantissaOffset = 0 [static], [constexpr]
Definition at line 99 of file register-loong64.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/arm/register-arm.h
/mnt/V8SourceCode/src/codegen/ia32/register-ia32.h
/mnt/V8SourceCode/src/codegen/loong64/register-loong64.h
/mnt/V8SourceCode/src/codegen/mips64/register-mips64.h
/mnt/V8SourceCode/src/codegen/ppc/register-ppc.h
/mnt/V8SourceCode/src/codegen/riscv/register-riscv.h
/mnt/V8SourceCode/src/codegen/s390/register-s390.h
/mnt/V8SourceCode/src/codegen/x64/register-x64.h
/mnt/V8SourceCode/src/codegen/arm64/register-arm64.h
/mnt/V8SourceCode/src/codegen/arm64/assembler-arm64-inl.h