v8::internal::OrderedHashTable< Derived, entrysize > Class Template Reference
#include <ordered-hash-table.h>
Public Member Functions
template<template< typename > typename HandleType>
requires(std::is_convertible_v< HandleType< Derived >, DirectHandle< Derived >>) static HandleType< Derived > requires (std::is_convertible_v< HandleType< Derived >, DirectHandle< Derived >>) static HandleType< Derived > Shrink(Isolate *isolate
InternalIndex FindEntry (Isolate *isolate, Tagged< Object > key)
int NumberOfElements () const
int NumberOfDeletedElements () const
int UsedCapacity () const
int Capacity ()
int NumberOfBuckets () const
InternalIndex::Range IterateEntries ()
Tagged< Object > KeyAt (InternalIndex entry)
bool ToKey (ReadOnlyRoots roots, InternalIndex entry, Tagged< Object > *out_key)
bool IsObsolete ()
Tagged< Derived > NextTable ()
int RemovedIndexAt (int index)
Static Public Member Functions
static Handle< Derived > Clear (Isolate *isolate, Handle< Derived > table)
static bool HasKey (Isolate *isolate, Tagged< Derived > table, Tagged< Object > key)
static bool IsKey (ReadOnlyRoots roots, Tagged< Object > k)
static bool Delete (Isolate *isolate, Tagged< Derived > table, Tagged< Object > key)
static constexpr int PrefixIndex ()
static constexpr int NumberOfElementsIndex ()
static constexpr int NextTableIndex ()
static constexpr int NumberOfDeletedElementsIndex ()
static constexpr int NumberOfBucketsIndex ()
static constexpr int HashTableStartIndex ()
static constexpr int RemovedHolesIndex ()
static constexpr int NumberOfElementsOffset ()
static constexpr int NextTableOffset ()
static constexpr int NumberOfDeletedElementsOffset ()
static constexpr int NumberOfBucketsOffset ()
static constexpr int HashTableStartOffset ()
static constexpr int MaxCapacity ()
Public Attributes
requires(std::is_convertible_v< HandleType< Derived >, DirectHandle< Derived >>) static HandleType< Derived > HandleType< Derived > table
Static Public Attributes
static const int kEntrySize = entrysize + 1
static const int kEntrySizeWithoutChain = entrysize
static const int kChainOffset = entrysize
static const int kNotFound = -1
static const int kInitialCapacity = 4
static const int kLoadFactor = 2
static const int kClearedTableSentinel = -1
Protected Member Functions
template<template< typename > typename HandleType>
requires(std::is_convertible_v< HandleType< Derived >, DirectHandle< Derived >>) static HandleType< Derived > requires(std::is_convertible_v< HandleType< Derived >, DirectHandle< Derived >>) static HandleType< Derived > int HashToEntryRaw (int hash)
int NextChainEntryRaw (int entry)
int EntryToIndexRaw (int entry)
int EntryToIndex (InternalIndex entry)
int HashToBucket (int hash)
void SetNumberOfBuckets (int num)
void SetNumberOfElements (int num)
void SetNumberOfDeletedElements (int num)
void SetNextTable (Tagged< Derived > next_table)
void SetRemovedIndexAt (int index, int removed_index)
Static Protected Member Functions
static MaybeHandle< Derived > Allocate (Isolate *isolate, int capacity, AllocationType allocation=AllocationType::kYoung)
static MaybeHandle< Derived > AllocateEmpty (Isolate *isolate, AllocationType allocation, RootIndex root_ndex)
Friends
class OrderedNameDictionaryHandler
Additional Inherited Members
Detailed Description
template<class Derived, int entrysize>
class v8::internal::OrderedHashTable< Derived, entrysize >
Definition at line 67 of file ordered-hash-table.h.
Member Function Documentation
Allocate()
template<class Derived , int entrysize>
MaybeHandle< Derived > v8::internal::OrderedHashTable< Derived, entrysize >::Allocate (Isolate * isolate, int capacity, AllocationType allocation = AllocationType::kYoung) [static], [protected]
Definition at line 19 of file ordered-hash-table.cc.
                                                               {
  // Capacity must be a power of two, since we depend on being able
  // to divide and multiple by 2 (kLoadFactor) to derive capacity
  // from number of buckets. If we decide to change kLoadFactor
  // to something other than 2, capacity should be stored as another
  // field of this object.
  capacity =
      base::bits::RoundUpToPowerOfTwo32(std::max({kInitialCapacity, capacity}));
  if (capacity > MaxCapacity()) {
    // Throw RangeError with a generic message.
    THROW_NEW_ERROR_RETURN_VALUE(
        isolate,
        NewRangeError(MessageTemplate::kCollectionGrowFailed,
                      isolate->factory()->empty_string()),
        {});
  }
  int num_buckets = capacity / kLoadFactor;
  Handle<FixedArray> backing_store = isolate->factory()->NewFixedArrayWithMap(
      Derived::GetMap(isolate->roots_table()),
      HashTableStartIndex() + num_buckets + (capacity * kEntrySize),
      allocation);
  Handle<Derived> table = Cast<Derived>(backing_store);
  DisallowGarbageCollection no_gc;
  Tagged<Derived> raw_table = *table;
  for (int i = 0; i < num_buckets; ++i) {
    raw_table->set(HashTableStartIndex() + i, Smi::FromInt(kNotFound));
  }
  raw_table->SetNumberOfBuckets(num_buckets);
  raw_table->SetNumberOfElements(0);
  raw_table->SetNumberOfDeletedElements(0);
  return table;
}
References v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, v8::internal::kNotFound, v8::internal::FactoryBase< Impl >::NewFixedArrayWithMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Isolate::roots_table(), and THROW_NEW_ERROR_RETURN_VALUE.
AllocateEmpty()
template<class Derived , int entrysize>
MaybeHandle< Derived > v8::internal::OrderedHashTable< Derived, entrysize >::AllocateEmpty (Isolate * isolate, AllocationType allocation, RootIndex root_ndex) [static], [protected]
Definition at line 54 of file ordered-hash-table.cc.
                                                                       {
  // This is only supposed to be used to create the canonical empty versions
  // of each ordered structure, and should not be used afterwards.
  // Requires that the map has already been set up in the roots table.
  DCHECK(!ReadOnlyRoots(isolate).is_initialized(root_index));
  Handle<FixedArray> backing_store = isolate->factory()->NewFixedArrayWithMap(
      Derived::GetMap(isolate->roots_table()), HashTableStartIndex(),
      allocation);
  Handle<Derived> table = Cast<Derived>(backing_store);
  DisallowHandleAllocation no_gc;
  Tagged<Derived> raw_table = *table;
  raw_table->SetNumberOfBuckets(0);
  raw_table->SetNumberOfElements(0);
  raw_table->SetNumberOfDeletedElements(0);
  return table;
}
Capacity()
template<class Derived , int entrysize>
int v8::internal::OrderedHashTable< Derived, entrysize >::Capacity () [inline]
Definition at line 116 of file ordered-hash-table.h.
{ return NumberOfBuckets() * kLoadFactor; }
References v8::internal::OrderedHashTable< Derived, entrysize >::kLoadFactor, and v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBuckets().
Clear()
template<class Derived , int entrysize>
Handle< Derived > v8::internal::OrderedHashTable< Derived, entrysize >::Clear (Isolate * isolate, Handle< Derived > table) [static]
Definition at line 116 of file ordered-hash-table.cc.
                                             {
  DCHECK(!table->IsObsolete());
  AllocationType allocation_type = HeapLayout::InYoungGeneration(*table)
                                       ? AllocationType::kYoung
                                       : AllocationType::kOld;
  Handle<Derived> new_table =
      Allocate(isolate, kInitialCapacity, allocation_type).ToHandleChecked();
  if (table->NumberOfBuckets() > 0) {
    // Don't try to modify the empty canonical table which lives in RO space.
    table->SetNextTable(*new_table);
    table->SetNumberOfDeletedElements(kClearedTableSentinel);
  }
  return new_table;
}
References v8::base::anonymous_namespace{platform-posix.cc}::Allocate(), v8::internal::DCHECK(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::kOld, and v8::internal::kYoung.
Delete()
template<class Derived , int entrysize>
bool v8::internal::OrderedHashTable< Derived, entrysize >::Delete (Isolate * isolate, Tagged< Derived > table, Tagged< Object > key) [static]
Definition at line 415 of file ordered-hash-table.cc.
                                                                      {
  DisallowGarbageCollection no_gc;
  InternalIndex entry = table->FindEntry(isolate, key);
  if (entry.is_not_found()) return false;
  int nof = table->NumberOfElements();
  int nod = table->NumberOfDeletedElements();
  int index = table->EntryToIndex(entry);
  Tagged<Object> hash_table_hole =
      ReadOnlyRoots(isolate).hash_table_hole_value();
  for (int i = 0; i < entrysize; ++i) {
    table->set(index + i, hash_table_hole);
  }
  table->SetNumberOfElements(nof - 1);
  table->SetNumberOfDeletedElements(nod + 1);
  return true;
}
References v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::InternalIndex::is_not_found(), v8::internal::key, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
EntryToIndex()
template<class Derived , int entrysize>
int v8::internal::OrderedHashTable< Derived, entrysize >::EntryToIndex (InternalIndex entry) [inline], [protected]
Definition at line 250 of file ordered-hash-table.h.
                                        {
    return EntryToIndexRaw(entry.as_int());
  }
References v8::internal::InternalIndex::as_int(), and v8::internal::OrderedHashTable< Derived, entrysize >::EntryToIndexRaw().
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::KeyAt().
EntryToIndexRaw()
template<class Derived , int entrysize>
int v8::internal::OrderedHashTable< Derived, entrysize >::EntryToIndexRaw (int entry) [inline], [protected]
Definition at line 246 of file ordered-hash-table.h.
                                 {
    return HashTableStartIndex() + NumberOfBuckets() + (entry * kEntrySize);
  }
References v8::internal::OrderedHashTable< Derived, entrysize >::HashTableStartIndex(), v8::internal::OrderedHashTable< Derived, entrysize >::kEntrySize, and v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBuckets().
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::EntryToIndex(), and v8::internal::OrderedHashTable< Derived, entrysize >::NextChainEntryRaw().
FindEntry()
template<class Derived , int entrysize>
InternalIndex v8::internal::OrderedHashTable< Derived, entrysize >::FindEntry (Isolate * isolate, Tagged< Object > key)
Definition at line 148 of file ordered-hash-table.cc.
                                          {
  if (NumberOfElements() == 0) {
    // This is not just an optimization but also ensures that we do the right
    // thing if Capacity() == 0
    return InternalIndex::NotFound();
  }
  int raw_entry;
  // This special cases for Smi, so that we avoid the HandleScope
  // creation below.
  if (IsSmi(key)) {
    uint32_t hash = ComputeUnseededHash(Smi::ToInt(key));
    raw_entry = HashToEntryRaw(hash & Smi::kMaxValue);
  } else {
    HandleScope scope(isolate);
    Tagged<Object> hash = Object::GetHash(key);
    // If the object does not have an identity hash, it was never used as a key
    if (IsUndefined(hash, isolate)) return InternalIndex::NotFound();
    raw_entry = HashToEntryRaw(Smi::ToInt(hash));
  }
  // Walk the chain in the bucket to find the key.
  while (raw_entry != kNotFound) {
    Tagged<Object> candidate_key = KeyAt(InternalIndex(raw_entry));
    if (Object::SameValueZero(candidate_key, key))
      return InternalIndex(raw_entry);
    raw_entry = NextChainEntryRaw(raw_entry);
  }
  return InternalIndex::NotFound();
}
References v8::internal::ComputeUnseededHash(), v8::internal::Object::GetHash(), v8::internal::IsSmi(), v8::internal::key, v8::internal::Smi::kMaxValue, v8::internal::kNotFound, v8::internal::InternalIndex::NotFound(), v8::internal::Object::SameValueZero(), and v8::internal::Smi::ToInt().
HashTableStartIndex()
template<class Derived , int entrysize>
static constexpr int v8::internal::OrderedHashTable< Derived, entrysize >::HashTableStartIndex () [inline], [static], [constexpr]
Definition at line 172 of file ordered-hash-table.h.
                                             {
    return NumberOfBucketsIndex() + 1;
  }
References v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBucketsIndex().
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::EntryToIndexRaw(), v8::internal::OrderedHashTable< Derived, entrysize >::HashTableStartOffset(), v8::internal::OrderedHashTable< Derived, entrysize >::HashToEntryRaw(), v8::internal::OrderedHashTable< Derived, entrysize >::MaxCapacity(), and v8::internal::OrderedHashTable< Derived, entrysize >::RemovedHolesIndex().
HashTableStartOffset()
template<class Derived , int entrysize>
static constexpr int v8::internal::OrderedHashTable< Derived, entrysize >::HashTableStartOffset () [inline], [static], [constexpr]
Definition at line 194 of file ordered-hash-table.h.
                                              {
    return FixedArray::OffsetOfElementAt(HashTableStartIndex());
  }
References v8::internal::OrderedHashTable< Derived, entrysize >::HashTableStartIndex(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt().
HashToBucket()
template<class Derived , int entrysize>
int v8::internal::OrderedHashTable< Derived, entrysize >::HashToBucket (int hash) [inline], [protected]
Definition at line 254 of file ordered-hash-table.h.
{ return hash & (NumberOfBuckets() - 1); }
References v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBuckets().
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::HashToEntryRaw().
HashToEntryRaw()
template<class Derived , int entrysize>
template<template< typename > typename HandleType>
requires (std::is_convertible_v<HandleType<Derived>, DirectHandle<Derived>>) static HandleType<Derived> requires (std::is_convertible_v<HandleType<Derived>, DirectHandle<Derived>>) static HandleType<Derived> int v8::internal::OrderedHashTable< Derived, entrysize >::HashToEntryRaw (int hash) [inline], [protected]
Definition at line 229 of file ordered-hash-table.h.
                               {
    int bucket = HashToBucket(hash);
    Tagged<Object> entry = this->get(HashTableStartIndex() + bucket);
    int entry_int = Smi::ToInt(entry);
    DCHECK(entry_int == kNotFound || entry_int >= 0);
    return entry_int;
  }
References v8::internal::DCHECK(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), v8::internal::OrderedHashTable< Derived, entrysize >::HashTableStartIndex(), v8::internal::OrderedHashTable< Derived, entrysize >::HashToBucket(), v8::internal::OrderedHashTable< Derived, entrysize >::kNotFound, and v8::internal::Smi::ToInt().
HasKey()
template<class Derived , int entrysize>
bool v8::internal::OrderedHashTable< Derived, entrysize >::HasKey (Isolate * isolate, Tagged< Derived > table, Tagged< Object > key) [static]
Definition at line 137 of file ordered-hash-table.cc.
                                                                      {
  DCHECK_IMPLIES(entrysize == 1, IsOrderedHashSet(table));
  DCHECK_IMPLIES(entrysize == 2, IsOrderedHashMap(table));
  DisallowGarbageCollection no_gc;
  InternalIndex entry = table->FindEntry(isolate, key);
  return entry.is_found();
}
References DCHECK_IMPLIES, v8::internal::InternalIndex::is_found(), v8::internal::key, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
IsKey()
template<class Derived , int entrysize>
bool v8::internal::OrderedHashTable< Derived, entrysize >::IsKey (ReadOnlyRoots roots, Tagged< Object > k) [inline], [static]
Definition at line 27 of file ordered-hash-table-inl.h.
                                                                   {
  return k != roots.the_hole_value();
}
IsObsolete()
template<class Derived , int entrysize>
bool v8::internal::OrderedHashTable< Derived, entrysize >::IsObsolete () [inline]
Definition at line 137 of file ordered-hash-table.h.
{ return !IsSmi(get(NextTableIndex())); }
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), v8::internal::IsSmi(), and v8::internal::OrderedHashTable< Derived, entrysize >::NextTableIndex().
IterateEntries()
template<class Derived , int entrysize>
InternalIndex::Range v8::internal::OrderedHashTable< Derived, entrysize >::IterateEntries () [inline]
Definition at line 122 of file ordered-hash-table.h.
                                      {
    return InternalIndex::Range(UsedCapacity());
  }
References v8::internal::compiler::turboshaft::Range(), and v8::internal::OrderedHashTable< Derived, entrysize >::UsedCapacity().
KeyAt()
template<class Derived , int entrysize>
Tagged<Object> v8::internal::OrderedHashTable< Derived, entrysize >::KeyAt (InternalIndex entry) [inline]
Definition at line 127 of file ordered-hash-table.h.
                                            {
    DCHECK_LT(entry.as_int(), this->UsedCapacity());
    return get(EntryToIndex(entry));
  }
References v8::internal::InternalIndex::as_int(), DCHECK_LT, v8::internal::OrderedHashTable< Derived, entrysize >::EntryToIndex(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), and v8::internal::this.
MaxCapacity()
template<class Derived , int entrysize>
static constexpr int v8::internal::OrderedHashTable< Derived, entrysize >::MaxCapacity () [inline], [static], [constexpr]
Definition at line 204 of file ordered-hash-table.h.
                                     {
    return (FixedArray::kMaxLength - HashTableStartIndex()) /
           (1 + (kEntrySize * kLoadFactor));
  }
References v8::internal::OrderedHashTable< Derived, entrysize >::HashTableStartIndex(), v8::internal::OrderedHashTable< Derived, entrysize >::kEntrySize, v8::internal::OrderedHashTable< Derived, entrysize >::kLoadFactor, and v8::internal::FixedArray::kMaxLength.
NextChainEntryRaw()
template<class Derived , int entrysize>
int v8::internal::OrderedHashTable< Derived, entrysize >::NextChainEntryRaw (int entry) [inline], [protected]
Definition at line 237 of file ordered-hash-table.h.
                                   {
    DCHECK_LT(entry, this->UsedCapacity());
    Tagged<Object> next_entry = get(EntryToIndexRaw(entry) + kChainOffset);
    int next_entry_int = Smi::ToInt(next_entry);
    DCHECK(next_entry_int == kNotFound || next_entry_int >= 0);
    return next_entry_int;
  }
References v8::internal::DCHECK(), DCHECK_LT, v8::internal::OrderedHashTable< Derived, entrysize >::EntryToIndexRaw(), v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), v8::internal::OrderedHashTable< Derived, entrysize >::kChainOffset, v8::internal::OrderedHashTable< Derived, entrysize >::kNotFound, v8::internal::Smi::ToInt(), and v8::internal::OrderedHashTable< Derived, entrysize >::UsedCapacity().
NextTable()
template<class Derived , int entrysize>
Tagged<Derived> v8::internal::OrderedHashTable< Derived, entrysize >::NextTable () [inline]
Definition at line 140 of file ordered-hash-table.h.
{ return Cast<Derived>(get(NextTableIndex())); }
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), and v8::internal::OrderedHashTable< Derived, entrysize >::NextTableIndex().
NextTableIndex()
template<class Derived , int entrysize>
static constexpr int v8::internal::OrderedHashTable< Derived, entrysize >::NextTableIndex () [inline], [static], [constexpr]
Definition at line 162 of file ordered-hash-table.h.
{ return NumberOfElementsIndex(); }
References v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfElementsIndex().
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::IsObsolete(), v8::internal::OrderedHashTable< Derived, entrysize >::NextTable(), v8::internal::OrderedHashTable< Derived, entrysize >::NextTableOffset(), and v8::internal::OrderedHashTable< Derived, entrysize >::SetNextTable().
NextTableOffset()
template<class Derived , int entrysize>
static constexpr int v8::internal::OrderedHashTable< Derived, entrysize >::NextTableOffset () [inline], [static], [constexpr]
Definition at line 182 of file ordered-hash-table.h.
                                         {
    return FixedArray::OffsetOfElementAt(NextTableIndex());
  }
References v8::internal::OrderedHashTable< Derived, entrysize >::NextTableIndex(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt().
NumberOfBuckets()
template<class Derived , int entrysize>
int v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBuckets () const [inline]
Definition at line 118 of file ordered-hash-table.h.
                              {
    return Smi::ToInt(get(NumberOfBucketsIndex()));
  }
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBucketsIndex(), and v8::internal::Smi::ToInt().
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::Capacity(), v8::internal::OrderedHashTable< Derived, entrysize >::EntryToIndexRaw(), and v8::internal::OrderedHashTable< Derived, entrysize >::HashToBucket().
NumberOfBucketsIndex()
template<class Derived , int entrysize>
static constexpr int v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBucketsIndex () [inline], [static], [constexpr]
Definition at line 168 of file ordered-hash-table.h.
                                              {
    return NumberOfDeletedElementsIndex() + 1;
  }
References v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfDeletedElementsIndex().
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::HashTableStartIndex(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBuckets(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBucketsOffset(), and v8::internal::OrderedHashTable< Derived, entrysize >::SetNumberOfBuckets().
NumberOfBucketsOffset()
template<class Derived , int entrysize>
static constexpr int v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBucketsOffset () [inline], [static], [constexpr]
Definition at line 190 of file ordered-hash-table.h.
                                               {
    return FixedArray::OffsetOfElementAt(NumberOfBucketsIndex());
  }
References v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBucketsIndex(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt().
NumberOfDeletedElements()
template<class Derived , int entrysize>
int v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfDeletedElements () const [inline]
Definition at line 106 of file ordered-hash-table.h.
                                      {
    return Smi::ToInt(get(NumberOfDeletedElementsIndex()));
  }
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfDeletedElementsIndex(), and v8::internal::Smi::ToInt().
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::UsedCapacity().
NumberOfDeletedElementsIndex()
template<class Derived , int entrysize>
static constexpr int v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfDeletedElementsIndex () [inline], [static], [constexpr]
Definition at line 164 of file ordered-hash-table.h.
                                                      {
    return NumberOfElementsIndex() + 1;
  }
References v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfElementsIndex().
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBucketsIndex(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfDeletedElements(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfDeletedElementsOffset(), and v8::internal::OrderedHashTable< Derived, entrysize >::SetNumberOfDeletedElements().
NumberOfDeletedElementsOffset()
template<class Derived , int entrysize>
static constexpr int v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfDeletedElementsOffset () [inline], [static], [constexpr]
Definition at line 186 of file ordered-hash-table.h.
                                                       {
    return FixedArray::OffsetOfElementAt(NumberOfDeletedElementsIndex());
  }
References v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfDeletedElementsIndex(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt().
NumberOfElements()
template<class Derived , int entrysize>
int v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfElements () const [inline]
Definition at line 102 of file ordered-hash-table.h.
                               {
    return Smi::ToInt(get(NumberOfElementsIndex()));
  }
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfElementsIndex(), and v8::internal::Smi::ToInt().
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::UsedCapacity().
NumberOfElementsIndex()
template<class Derived , int entrysize>
static constexpr int v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfElementsIndex () [inline], [static], [constexpr]
Definition at line 159 of file ordered-hash-table.h.
{ return Derived::kPrefixSize; }
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::NextTableIndex(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfDeletedElementsIndex(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfElements(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfElementsOffset(), and v8::internal::OrderedHashTable< Derived, entrysize >::SetNumberOfElements().
NumberOfElementsOffset()
template<class Derived , int entrysize>
static constexpr int v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfElementsOffset () [inline], [static], [constexpr]
Definition at line 178 of file ordered-hash-table.h.
                                                {
    return FixedArray::OffsetOfElementAt(NumberOfElementsIndex());
  }
References v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfElementsIndex(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::OffsetOfElementAt().
PrefixIndex()
template<class Derived , int entrysize>
static constexpr int v8::internal::OrderedHashTable< Derived, entrysize >::PrefixIndex () [inline], [static], [constexpr]
Definition at line 157 of file ordered-hash-table.h.
{ return 0; }
RemovedHolesIndex()
template<class Derived , int entrysize>
static constexpr int v8::internal::OrderedHashTable< Derived, entrysize >::RemovedHolesIndex () [inline], [static], [constexpr]
Definition at line 176 of file ordered-hash-table.h.
{ return HashTableStartIndex(); }
References v8::internal::OrderedHashTable< Derived, entrysize >::HashTableStartIndex().
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::RemovedIndexAt(), and v8::internal::OrderedHashTable< Derived, entrysize >::SetRemovedIndexAt().
RemovedIndexAt()
template<class Derived , int entrysize>
int v8::internal::OrderedHashTable< Derived, entrysize >::RemovedIndexAt (int index) [inline]
Definition at line 143 of file ordered-hash-table.h.
                                {
    return Smi::ToInt(get(RemovedHolesIndex() + index));
  }
References v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::get(), v8::internal::FixedArray::index, v8::internal::OrderedHashTable< Derived, entrysize >::RemovedHolesIndex(), and v8::internal::Smi::ToInt().
requires()
template<class Derived , int entrysize>
template<template< typename > typename HandleType>
requires (std::is_convertible_v<HandleType<Derived>, DirectHandle<Derived>>) static HandleType<Derived> v8::internal::OrderedHashTable< Derived, entrysize >::requires (std::is_convertible_v< HandleType< Derived >, DirectHandle< Derived >>)
SetNextTable()
template<class Derived , int entrysize>
void v8::internal::OrderedHashTable< Derived, entrysize >::SetNextTable (Tagged< Derived > next_table) [inline], [protected]
Definition at line 268 of file ordered-hash-table.h.
                                                {
    set(NextTableIndex(), next_table);
  }
References v8::internal::OrderedHashTable< Derived, entrysize >::NextTableIndex(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::set().
SetNumberOfBuckets()
template<class Derived , int entrysize>
void v8::internal::OrderedHashTable< Derived, entrysize >::SetNumberOfBuckets (int num) [inline], [protected]
Definition at line 256 of file ordered-hash-table.h.
                                   {
    set(NumberOfBucketsIndex(), Smi::FromInt(num));
  }
References v8::internal::Smi::FromInt(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfBucketsIndex(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::set().
SetNumberOfDeletedElements()
template<class Derived , int entrysize>
void v8::internal::OrderedHashTable< Derived, entrysize >::SetNumberOfDeletedElements (int num) [inline], [protected]
Definition at line 264 of file ordered-hash-table.h.
                                           {
    set(NumberOfDeletedElementsIndex(), Smi::FromInt(num));
  }
References v8::internal::Smi::FromInt(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfDeletedElementsIndex(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::set().
SetNumberOfElements()
template<class Derived , int entrysize>
void v8::internal::OrderedHashTable< Derived, entrysize >::SetNumberOfElements (int num) [inline], [protected]
Definition at line 260 of file ordered-hash-table.h.
                                    {
    set(NumberOfElementsIndex(), Smi::FromInt(num));
  }
References v8::internal::Smi::FromInt(), v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfElementsIndex(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::set().
SetRemovedIndexAt()
template<class Derived , int entrysize>
void v8::internal::OrderedHashTable< Derived, entrysize >::SetRemovedIndexAt (int index, int removed_index) [inline], [protected]
Definition at line 272 of file ordered-hash-table.h.
                                                       {
    return set(RemovedHolesIndex() + index, Smi::FromInt(removed_index));
  }
References v8::internal::Smi::FromInt(), v8::internal::FixedArray::index, v8::internal::OrderedHashTable< Derived, entrysize >::RemovedHolesIndex(), and v8::internal::TaggedArrayBase< FixedArray, TaggedArrayShape >::set().
ToKey()
template<class Derived , int entrysize>
bool v8::internal::OrderedHashTable< Derived, entrysize >::ToKey (ReadOnlyRoots roots, InternalIndex entry, Tagged< Object > * out_key) [inline]
Definition at line 100 of file ordered-hash-table-inl.h.
                                                                          {
  Tagged<Object> k = KeyAt(entry);
  if (!IsKey(roots, k)) return false;
  *out_key = k;
  return true;
}
UsedCapacity()
template<class Derived , int entrysize>
int v8::internal::OrderedHashTable< Derived, entrysize >::UsedCapacity () const [inline]
Definition at line 112 of file ordered-hash-table.h.
                           {
    return NumberOfElements() + NumberOfDeletedElements();
  }
References v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfDeletedElements(), and v8::internal::OrderedHashTable< Derived, entrysize >::NumberOfElements().
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::IterateEntries(), and v8::internal::OrderedHashTable< Derived, entrysize >::NextChainEntryRaw().
Friends And Related Function Documentation
OrderedNameDictionaryHandler
template<class Derived , int entrysize>
friend class OrderedNameDictionaryHandler [friend]
Definition at line 277 of file ordered-hash-table.h.
Member Data Documentation
kChainOffset
template<class Derived , int entrysize>
const int v8::internal::OrderedHashTable< Derived, entrysize >::kChainOffset = entrysize [static]
Definition at line 150 of file ordered-hash-table.h.
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::NextChainEntryRaw().
kClearedTableSentinel
template<class Derived , int entrysize>
const int v8::internal::OrderedHashTable< Derived, entrysize >::kClearedTableSentinel = -1 [static]
Definition at line 203 of file ordered-hash-table.h.
kEntrySize
template<class Derived , int entrysize>
const int v8::internal::OrderedHashTable< Derived, entrysize >::kEntrySize = entrysize + 1 [static]
Definition at line 148 of file ordered-hash-table.h.
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::EntryToIndexRaw(), and v8::internal::OrderedHashTable< Derived, entrysize >::MaxCapacity().
kEntrySizeWithoutChain
template<class Derived , int entrysize>
const int v8::internal::OrderedHashTable< Derived, entrysize >::kEntrySizeWithoutChain = entrysize [static]
Definition at line 149 of file ordered-hash-table.h.
kInitialCapacity
template<class Derived , int entrysize>
const int v8::internal::OrderedHashTable< Derived, entrysize >::kInitialCapacity = 4 [static]
Definition at line 155 of file ordered-hash-table.h.
kLoadFactor
template<class Derived , int entrysize>
const int v8::internal::OrderedHashTable< Derived, entrysize >::kLoadFactor = 2 [static]
Definition at line 198 of file ordered-hash-table.h.
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::Capacity(), and v8::internal::OrderedHashTable< Derived, entrysize >::MaxCapacity().
kNotFound
template<class Derived , int entrysize>
const int v8::internal::OrderedHashTable< Derived, entrysize >::kNotFound = -1 [static]
Definition at line 152 of file ordered-hash-table.h.
Referenced by v8::internal::OrderedHashTable< Derived, entrysize >::HashToEntryRaw(), and v8::internal::OrderedHashTable< Derived, entrysize >::NextChainEntryRaw().
table
template<class Derived , int entrysize>
requires (std::is_convertible_v<HandleType<Derived>, DirectHandle<Derived>>) static HandleType<Derived> HandleType<Derived> v8::internal::OrderedHashTable< Derived, entrysize >::table
Definition at line 81 of file ordered-hash-table.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/ordered-hash-table.h
/mnt/V8SourceCode/src/objects/ordered-hash-table-inl.h
/mnt/V8SourceCode/src/objects/ordered-hash-table.cc