v8::internal::DebugInfoCollection::Iterator Class Reference
#include <debug.h>
Public Member Functions
Iterator (DebugInfoCollection *collection)
bool HasNext () const
Tagged< DebugInfo > Next () const
void Advance ()
void DeleteNext ()
Private Types
using HandleLocation = DebugInfoCollection::HandleLocation
Private Attributes
DebugInfoCollection *const collection_
int index_ = 0
Detailed Description
Definition at line 200 of file debug.h.
Member Typedef Documentation
HandleLocation
using v8::internal::DebugInfoCollection::Iterator::HandleLocation = DebugInfoCollection::HandleLocation [private]
Definition at line 228 of file debug.h.
Constructor & Destructor Documentation
Iterator()
v8::internal::DebugInfoCollection::Iterator::Iterator (DebugInfoCollection * collection) [inline], [explicit]
Definition at line 202 of file debug.h.
        : collection_(collection) {}
Member Function Documentation
Advance()
void v8::internal::DebugInfoCollection::Iterator::Advance () [inline]
Definition at line 215 of file debug.h.
                   {
      DCHECK(HasNext());
      index_++;
    }
References v8::internal::DCHECK(), HasNext(), and index_.
Referenced by v8::internal::Debug::ClearAllDebugInfos(), v8::internal::Debug::ClearBreakPoint(), v8::internal::Debug::ClearOneShot(), v8::internal::DebugInfoCollection::DeleteSlow(), v8::internal::Debug::InstallDebugBreakTrampoline(), and v8::internal::Debug::UpdateDebugInfosForExecutionMode().
DeleteNext()
void v8::internal::DebugInfoCollection::Iterator::DeleteNext () [inline]
Definition at line 220 of file debug.h.
                      {
      DCHECK_GE(index_, 0);
      DCHECK(HasNext());
      collection_->DeleteIndex(index_);
      index_--; // `Advance` must be called next.
    }
References collection_, v8::internal::DCHECK(), DCHECK_GE, v8::internal::DebugInfoCollection::DeleteIndex(), HasNext(), and index_.
Referenced by v8::internal::Debug::ClearAllDebugInfos(), v8::internal::Debug::ClearBreakPoint(), and v8::internal::DebugInfoCollection::DeleteSlow().
HasNext()
bool v8::internal::DebugInfoCollection::Iterator::HasNext () const [inline]
Definition at line 205 of file debug.h.
                         {
      return index_ < static_cast<int>(collection_->list_.size());
    }
References collection_, and v8::internal::DebugInfoCollection::list_.
Referenced by Advance(), v8::internal::Debug::ClearAllDebugInfos(), v8::internal::Debug::ClearBreakPoint(), v8::internal::Debug::ClearOneShot(), DeleteNext(), v8::internal::DebugInfoCollection::DeleteSlow(), v8::internal::Debug::InstallDebugBreakTrampoline(), Next(), and v8::internal::Debug::UpdateDebugInfosForExecutionMode().
Next()
Tagged<DebugInfo> v8::internal::DebugInfoCollection::Iterator::Next () const [inline]
Definition at line 209 of file debug.h.
                                   {
      DCHECK_GE(index_, 0);
      if (!HasNext()) return {};
      return collection_->EntryAsDebugInfo(index_);
    }
References collection_, DCHECK_GE, v8::internal::DebugInfoCollection::EntryAsDebugInfo(), HasNext(), and index_.
Referenced by v8::internal::Debug::ClearAllDebugInfos(), v8::internal::Debug::ClearBreakPoint(), v8::internal::Debug::ClearOneShot(), v8::internal::DebugInfoCollection::DeleteSlow(), v8::internal::Debug::InstallDebugBreakTrampoline(), and v8::internal::Debug::UpdateDebugInfosForExecutionMode().
Member Data Documentation
collection_
DebugInfoCollection* const v8::internal::DebugInfoCollection::Iterator::collection_ [private]
Definition at line 229 of file debug.h.
Referenced by DeleteNext(), HasNext(), and Next().
index_
int v8::internal::DebugInfoCollection::Iterator::index_ = 0 [private]
Definition at line 230 of file debug.h.
Referenced by Advance(), DeleteNext(), and Next().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/debug/debug.h