v8::internal::compiler::WasmCallDescriptors Class Reference
#include <wasm-call-descriptors.h>
Public Member Functions
WasmCallDescriptors (AccountingAllocator *allocator)
compiler::CallDescriptor * GetBigIntToI64Descriptor (bool needs_frame_state)
V8_EXPORT_PRIVATE compiler::CallDescriptor * GetLoweredCallDescriptor (const compiler::CallDescriptor *original)
Private Attributes
std::unique_ptr< Zone > zone_
compiler::CallDescriptor * bigint_to_i64_descriptor_
compiler::CallDescriptor * bigint_to_i64_descriptor_with_framestate_
Detailed Description
Definition at line 24 of file wasm-call-descriptors.h.
Constructor & Destructor Documentation
WasmCallDescriptors()
v8::internal::compiler::WasmCallDescriptors::WasmCallDescriptors (AccountingAllocator * allocator) [explicit]
Definition at line 13 of file wasm-call-descriptors.cc.
    : zone_(new Zone(allocator, "wasm_call_descriptors")) {
  bigint_to_i64_descriptor_ = compiler::GetBuiltinCallDescriptor(
      Builtin::kBigIntToI64, zone_.get(), StubCallMode::kCallBuiltinPointer);
  bigint_to_i64_descriptor_with_framestate_ =
      compiler::GetBuiltinCallDescriptor(Builtin::kBigIntToI64, zone_.get(),
                                         StubCallMode::kCallBuiltinPointer,
                                         true);
#if V8_TARGET_ARCH_32_BIT
  bigint_to_i32pair_descriptor_ =
      compiler::GetBuiltinCallDescriptor(Builtin::kBigIntToI32Pair, zone_.get(),
                                         StubCallMode::kCallBuiltinPointer);
  bigint_to_i32pair_descriptor_with_framestate_ =
      compiler::GetBuiltinCallDescriptor(Builtin::kBigIntToI32Pair, zone_.get(),
                                         StubCallMode::kCallBuiltinPointer,
                                         true);
#endif // V8_TARGET_ARCH_32_BIT
}
References bigint_to_i64_descriptor_, bigint_to_i64_descriptor_with_framestate_, v8::internal::compiler::GetBuiltinCallDescriptor(), v8::internal::kCallBuiltinPointer, and zone_.
Member Function Documentation
GetBigIntToI64Descriptor()
compiler::CallDescriptor* v8::internal::compiler::WasmCallDescriptors::GetBigIntToI64Descriptor (bool needs_frame_state) [inline]
Definition at line 28 of file wasm-call-descriptors.h.
                                                                           {
    if (needs_frame_state) {
      return bigint_to_i64_descriptor_with_framestate_;
    }
    return bigint_to_i64_descriptor_;
  }
References bigint_to_i64_descriptor_, and bigint_to_i64_descriptor_with_framestate_.
Referenced by v8::internal::wasm::WasmWrapperTSGraphBuilder::GetBigIntToI64CallDescriptor().
GetLoweredCallDescriptor()
V8_EXPORT_PRIVATE compiler::CallDescriptor* v8::internal::compiler::WasmCallDescriptors::GetLoweredCallDescriptor (const compiler::CallDescriptor * original) [inline]
Definition at line 39 of file wasm-call-descriptors.h.
                                              {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::LowerCall().
Member Data Documentation
bigint_to_i64_descriptor_
compiler::CallDescriptor* v8::internal::compiler::WasmCallDescriptors::bigint_to_i64_descriptor_ [private]
Definition at line 48 of file wasm-call-descriptors.h.
Referenced by GetBigIntToI64Descriptor(), and WasmCallDescriptors().
bigint_to_i64_descriptor_with_framestate_
compiler::CallDescriptor* v8::internal::compiler::WasmCallDescriptors::bigint_to_i64_descriptor_with_framestate_ [private]
Definition at line 49 of file wasm-call-descriptors.h.
Referenced by GetBigIntToI64Descriptor(), and WasmCallDescriptors().
zone_
std::unique_ptr<Zone> v8::internal::compiler::WasmCallDescriptors::zone_ [private]
Definition at line 46 of file wasm-call-descriptors.h.
Referenced by WasmCallDescriptors().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/wasm-call-descriptors.h
/mnt/V8SourceCode/src/compiler/wasm-call-descriptors.cc