v8::internal::BuiltinsSorter Class Reference
#include <sort-builtins.h>
Classes
struct BuiltinDensitySlot
Public Member Functions
BuiltinsSorter ()
~BuiltinsSorter ()
std::vector< Builtin > SortBuiltins (const char *profiling_file, const std::vector< uint32_t > &builtin_size)
Private Member Functions
void InitializeCallGraph (const char *profiling_file, const std::vector< uint32_t > &size)
void InitializeClusters ()
void MergeBestPredecessors ()
void SortClusters ()
Builtin FindBestPredecessorOf (Builtin callee)
void ProcessBlockCountLineInfo (std::istringstream &line_stream, std::unordered_map< std::string, Builtin > &name2id)
void ProcessBuiltinDensityLineInfo (std::istringstream &line_stream, std::unordered_map< std::string, Builtin > &name2id)
Private Attributes
const int32_t kMinEdgeProbabilityThreshold = 10
const uint32_t kMaxClusterSize = 1 * MB
const uint32_t kMaxDensityDecreaseThreshold = 8
const std::string kBuiltinCallBlockDensityMarker = `block_count`
const std::string kBuiltinDensityMarker = `builtin_count`
std::vector< Cluster * > clusters_
std::vector< BuiltinDensitySlot > builtin_density_order_
CallGraph call_graph_
BuiltinDensityMap builtin_density_map_
BuiltinSize builtin_size_
BuiltinClusterMap builtin_cluster_map_
Friends
class Cluster
Detailed Description
Definition at line 73 of file sort-builtins.h.
Constructor & Destructor Documentation
BuiltinsSorter()
v8::internal::BuiltinsSorter::BuiltinsSorter ()
Definition at line 24 of file sort-builtins.cc.
{}
 BuiltinsSorter()
v8::internal::BuiltinsSorter::~BuiltinsSorter ()
Definition at line 26 of file sort-builtins.cc.
                                {
  for (Cluster* cls : clusters_) {
    delete cls;
  }
}
References clusters_.
Member Function Documentation
FindBestPredecessorOf()
Builtin v8::internal::BuiltinsSorter::FindBestPredecessorOf (Builtin callee) [private]
Definition at line 73 of file sort-builtins.cc.
                                                            {
  Builtin bestPred = Builtin::kNoBuiltinId;
  int32_t bestProb = 0;
  for (auto caller_it = call_graph_.begin(); caller_it != call_graph_.end();
       caller_it++) {
    Builtin caller = caller_it->first;
    const CallProbabilities& callees_prob = caller_it->second;
    if (callees_prob.count(callee) > 0) {
      int32_t incoming_prob = callees_prob.at(callee).incoming_;
      if (incoming_prob == -1) {
        // We dont want to merge any cluster with -1 prob, because it means it's
        // either a non TurboFan compiled builtin or its execution count too
        // small.
        continue;
      }
      if (bestPred == Builtin::kNoBuiltinId || incoming_prob > bestProb) {
        bestPred = caller;
        bestProb = incoming_prob;
      }
    }
    if (bestProb < kMinEdgeProbabilityThreshold ||
        bestPred == Builtin::kNoBuiltinId)
      continue;
    Cluster* predCls = builtin_cluster_map_[bestPred];
    Cluster* succCls = builtin_cluster_map_[callee];
    // Don't merge if the caller and callee are already in same cluster.
    if (predCls == succCls) continue;
    // Don't merge clusters if the combined size is too big.
    if (predCls->size_ + succCls->size_ > kMaxClusterSize) continue;
    if (predCls->density_ == 0) {
      // Some density of cluster after normalized may be 0, in that case we dont
      // merge them.
      continue;
    }
    CHECK(predCls->size_);
    uint32_t new_density = static_cast<uint32_t>(
        (predCls->time_approximation() + succCls->time_approximation()) /
        (predCls->size_ + succCls->size_));
    // Don't merge clusters if the new merged density is lower too many times
    // than current cluster, to avoid a huge dropping in cluster density, it
    // will harm locality of builtins.
    if (predCls->density_ / kMaxDensityDecreaseThreshold > new_density)
      continue;
  }
  return bestPred;
}
References builtin_cluster_map_, call_graph_, CHECK, v8::internal::Cluster::density_, kMaxClusterSize, kMaxDensityDecreaseThreshold, kMinEdgeProbabilityThreshold, v8::internal::kNoBuiltinId, v8::internal::Cluster::size_, and v8::internal::Cluster::time_approximation().
Referenced by MergeBestPredecessors().
InitializeCallGraph()
void v8::internal::BuiltinsSorter::InitializeCallGraph (const char * profiling_file, const std::vector< uint32_t > & size) [private]
Definition at line 271 of file sort-builtins.cc.
                                                                          {
  std::ifstream file(profiling_file);
  CHECK_WITH_MSG(file.good(), "Can't read log file");
  std::unordered_map<std::string, Builtin> name2id;
  for (Builtin i = Builtins::kFirst; i <= Builtins::kLast; ++i) {
    std::string name = Builtins::name(i);
    name2id.emplace(name, i);
    builtin_size_.push_back(size.at(static_cast<uint32_t>(i)));
  }
  for (std::string line; std::getline(file, line);) {
    std::string token;
    std::istringstream line_stream(line);
    // We must put lines start with kBuiltinDensityMarker before lines start
    // with kBuiltinCallBlockDensityMarker, because we have to density to
    // calculate call prob.
    if (!std::getline(line_stream, token, ',')) continue;
    if (token == kBuiltinCallBlockDensityMarker) {
      ProcessBlockCountLineInfo(line_stream, name2id);
    } else if (token == kBuiltinDensityMarker) {
      ProcessBuiltinDensityLineInfo(line_stream, name2id);
    }
  }
}
References builtin_size_, CHECK_WITH_MSG, file(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, kBuiltinCallBlockDensityMarker, kBuiltinDensityMarker, v8::internal::Builtins::kFirst, v8::internal::Builtins::kLast, v8::internal::Builtins::name(), v8::internal::name, ProcessBlockCountLineInfo(), ProcessBuiltinDensityLineInfo(), size(), and v8::internal::string.
Referenced by SortBuiltins().
InitializeClusters()
void v8::internal::BuiltinsSorter::InitializeClusters () [private]
Definition at line 50 of file sort-builtins.cc.
                                        {
  for (uint32_t i = 0; i < static_cast<uint32_t>(builtin_size_.size()); i++) {
    Builtin id = Builtins::FromInt(i);
    Builtins::Kind kind = Builtins::KindOf(id);
    if (kind == Builtins::Kind::ASM || kind == Builtins::Kind::CPP) {
      // CHECK there is no data for execution count for non TurboFan compiled
      // builtin.
      CHECK_EQ(builtin_density_map_[id], 0);
      continue;
    }
    Cluster* cls =
        new Cluster(builtin_density_map_[id], builtin_size_[i], id, this);
    clusters_.push_back(cls);
    builtin_density_order_.push_back(
        BuiltinDensitySlot{builtin_density_map_[id], id});
  }
  std::sort(builtin_density_order_.begin(), builtin_density_order_.end(),
            [](const BuiltinDensitySlot& x, const BuiltinDensitySlot& y) {
              return x.density_ > y.density_;
            });
}
References builtin_density_map_, builtin_density_order_, builtin_size_, CHECK_EQ, Cluster, clusters_, v8::internal::Builtins::FromInt(), v8::internal::Builtins::KindOf(), v8::base::sort(), and v8::internal::y.
Referenced by SortBuiltins().
MergeBestPredecessors()
void v8::internal::BuiltinsSorter::MergeBestPredecessors () [private]
Definition at line 127 of file sort-builtins.cc.
                                           {
  for (size_t i = 0; i < builtin_density_order_.size(); i++) {
    Builtin id = builtin_density_order_[i].builtin_;
    Cluster* succ_cluster = builtin_cluster_map_[id];
    Builtin bestPred = FindBestPredecessorOf(id);
    if (bestPred != Builtin::kNoBuiltinId) {
      Cluster* pred_cluster = builtin_cluster_map_[bestPred];
      pred_cluster->Merge(succ_cluster);
    }
  }
}
References builtin_cluster_map_, builtin_density_order_, FindBestPredecessorOf(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kNoBuiltinId, and v8::internal::Cluster::Merge().
Referenced by SortBuiltins().
ProcessBlockCountLineInfo()
void v8::internal::BuiltinsSorter::ProcessBlockCountLineInfo (std::istringstream & line_stream, std::unordered_map< std::string, Builtin > & name2id) [private]
Definition at line 162 of file sort-builtins.cc.
                                                   {
  // Any line starting with kBuiltinCallBlockDensityMarker is a normalized
  // execution count of block with call. The format is:
  // literal kBuiltinCallBlockDensityMarker , caller , block ,
  // normalized_count
  std::string token;
  std::string caller_name;
  CHECK(std::getline(line_stream, caller_name, ','));
  Builtin caller_id = name2id[caller_name];
  BuiltinsCallGraph* profiler = BuiltinsCallGraph::Get();
  char* end = nullptr;
  errno = 0;
  CHECK(std::getline(line_stream, token, ','));
  int32_t block_id = static_cast<int32_t>(strtoul(token.c_str(), &end, 0));
  CHECK(errno == 0 && end != token.c_str());
  CHECK(std::getline(line_stream, token, ','));
  int32_t normalized_count =
      static_cast<int32_t>(strtoul(token.c_str(), &end, 0));
  CHECK(errno == 0 && end != token.c_str());
  CHECK(line_stream.eof());
  const BuiltinCallees* block_callees = profiler->GetBuiltinCallees(caller_id);
  if (block_callees) {
    int32_t outgoing_prob = 0;
    int32_t incoming_prob = 0;
    int caller_density = 0;
    int callee_density = 0;
    CHECK(builtin_density_map_.count(caller_id));
    caller_density = builtin_density_map_.at(caller_id);
    // TODO(v8:13938): Remove the below if check when we just store
    // interesting blocks (contain call other builtins) execution count into
    // profiling file.
    if (block_callees->count(block_id)) {
      // If the line of block density make sense (means it contain call to
      // other builtins in this block).
      for (const auto& callee_id : block_callees->at(block_id)) {
        if (caller_density != 0) {
          outgoing_prob = normalized_count * 100 / caller_density;
        } else {
          // If the caller density was normalized as 0 but the block density
          // was not, we set caller prob as 100, otherwise it's 0. Because in
          // the normalization, we may loss fidelity.
          // For example, a caller was executed 8 times, but after
          // normalization, it may be 0 time. At that time, if the
          // normalized_count of this block (it may be a loop body) is a
          // positive number, we could think normalized_count is bigger than the
          // execution count of caller, hence we set it as 100, otherwise it's
          // smaller than execution count of caller, we could set it as 0.
          outgoing_prob = normalized_count ? 100 : 0;
        }
        if (builtin_density_map_.count(callee_id)) {
          callee_density = builtin_density_map_.at(callee_id);
          if (callee_density != 0) {
            incoming_prob = normalized_count * 100 / callee_density;
          } else {
            // Same as caller prob when callee density exists but is 0.
            incoming_prob = normalized_count ? 100 : 0;
          }
        } else {
          // If callee_density does not exist, it means the callee was not
          // compiled by TurboFan or execution count is too small (0 after
          // normalization), we couldn't get the callee count, so we set it as
          // -1. In that case we could avoid merging this callee builtin into
          // any other cluster.
          incoming_prob = -1;
        }
        CallProbability probs = CallProbability(incoming_prob, outgoing_prob);
        if (call_graph_.count(caller_id) == 0) {
          call_graph_.emplace(caller_id, CallProbabilities());
        }
        CallProbabilities& call_probs = call_graph_.at(caller_id);
        call_probs.emplace(callee_id, probs);
      }
    }
  }
  CHECK(line_stream.eof());
}
References builtin_density_map_, call_graph_, CHECK, v8::internal::compiler::end(), v8::internal::BuiltinsCallGraph::Get(), v8::internal::BuiltinsCallGraph::GetBuiltinCallees(), and v8::internal::string.
Referenced by InitializeCallGraph().
ProcessBuiltinDensityLineInfo()
void v8::internal::BuiltinsSorter::ProcessBuiltinDensityLineInfo (std::istringstream & line_stream, std::unordered_map< std::string, Builtin > & name2id) [private]
Definition at line 250 of file sort-builtins.cc.
                                                   {
  // Any line starting with kBuiltinDensityMarker is normalized execution count
  // for block 0 of a builtin, we take it as density of this builtin. The format
  // is:
  // literal kBuiltinDensityMarker , builtin_name , density
  std::string token;
  std::string builtin_name;
  CHECK(std::getline(line_stream, builtin_name, ','));
  std::getline(line_stream, token, ',');
  CHECK(line_stream.eof());
  char* end = nullptr;
  errno = 0;
  int density = static_cast<int>(strtol(token.c_str(), &end, 0));
  CHECK(errno == 0 && end != token.c_str());
  Builtin builtin_id = name2id[builtin_name];
  builtin_density_map_.emplace(builtin_id, density);
}
References builtin_density_map_, CHECK, v8::internal::compiler::end(), and v8::internal::string.
Referenced by InitializeCallGraph().
SortBuiltins()
std::vector< Builtin > v8::internal::BuiltinsSorter::SortBuiltins (const char * profiling_file, const std::vector< uint32_t > & builtin_size)
Definition at line 298 of file sort-builtins.cc.
                                                                         {
  InitializeCallGraph(profiling_file, builtin_size);
  // Step 1: initialization.
  InitializeClusters();
  // Step 2: Merge best predecessors.
  MergeBestPredecessors();
  // Step 3: Sort clusters again.
  SortClusters();
  std::unordered_set<Builtin> processed_builtins;
  std::vector<Builtin> builtin_order;
  // For functions in the sorted cluster from step 3.
  for (size_t i = 0; i < clusters_.size(); i++) {
    Cluster* cls = clusters_.at(i);
    for (size_t j = 0; j < cls->targets_.size(); j++) {
      Builtin builtin = cls->targets_[j];
      CHECK(
          AddBuiltinIfNotProcessed(builtin, builtin_order, processed_builtins));
    }
  }
  // For the remaining builtins.
  for (Builtin i = Builtins::kFirst; i <= Builtins::kLast; ++i) {
    AddBuiltinIfNotProcessed(i, builtin_order, processed_builtins);
  }
  return builtin_order;
}
References v8::internal::AddBuiltinIfNotProcessed(), CHECK, clusters_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, InitializeCallGraph(), InitializeClusters(), v8::internal::Builtins::kFirst, v8::internal::Builtins::kLast, MergeBestPredecessors(), SortClusters(), and v8::internal::Cluster::targets_.
Referenced by v8::internal::EmbeddedData::NewFromIsolate().
SortClusters()
void v8::internal::BuiltinsSorter::SortClusters () [private]
Definition at line 140 of file sort-builtins.cc.
                                  {
  std::sort(clusters_.begin(), clusters_.end(),
            [](const Cluster* x, const Cluster* y) {
              return x->density_ > y->density_;
            });
  clusters_.erase(
      std::remove_if(clusters_.begin(), clusters_.end(),
                     [](const Cluster* x) { return x->targets_.empty(); }),
      clusters_.end());
}
References clusters_, v8::base::sort(), and v8::internal::y.
Referenced by SortBuiltins().
Friends And Related Function Documentation
Cluster
friend class Cluster [friend]
Definition at line 122 of file sort-builtins.h.
Referenced by InitializeClusters().
Member Data Documentation
builtin_cluster_map_
BuiltinClusterMap v8::internal::BuiltinsSorter::builtin_cluster_map_ [private]
Definition at line 120 of file sort-builtins.h.
Referenced by v8::internal::Cluster::Cluster(), FindBestPredecessorOf(), v8::internal::Cluster::Merge(), and MergeBestPredecessors().
builtin_density_map_
BuiltinDensityMap v8::internal::BuiltinsSorter::builtin_density_map_ [private]
Definition at line 116 of file sort-builtins.h.
Referenced by InitializeClusters(), ProcessBlockCountLineInfo(), and ProcessBuiltinDensityLineInfo().
builtin_density_order_
std::vector<BuiltinDensitySlot> v8::internal::BuiltinsSorter::builtin_density_order_ [private]
Definition at line 112 of file sort-builtins.h.
Referenced by InitializeClusters(), and MergeBestPredecessors().
builtin_size_
BuiltinSize v8::internal::BuiltinsSorter::builtin_size_ [private]
Definition at line 118 of file sort-builtins.h.
Referenced by InitializeCallGraph(), and InitializeClusters().
call_graph_
CallGraph v8::internal::BuiltinsSorter::call_graph_ [private]
Definition at line 114 of file sort-builtins.h.
Referenced by FindBestPredecessorOf(), and ProcessBlockCountLineInfo().
clusters_
std::vector<Cluster*> v8::internal::BuiltinsSorter::clusters_ [private]
Definition at line 110 of file sort-builtins.h.
Referenced by InitializeClusters(), SortBuiltins(), SortClusters(), and ~BuiltinsSorter().
kBuiltinCallBlockDensityMarker
const std::string v8::internal::BuiltinsSorter::kBuiltinCallBlockDensityMarker = `block_count` [private]
Definition at line 78 of file sort-builtins.h.
Referenced by InitializeCallGraph().
kBuiltinDensityMarker
const std::string v8::internal::BuiltinsSorter::kBuiltinDensityMarker = `builtin_count` [private]
Definition at line 79 of file sort-builtins.h.
Referenced by InitializeCallGraph().
kMaxClusterSize
const uint32_t v8::internal::BuiltinsSorter::kMaxClusterSize = 1 * MB [private]
Definition at line 75 of file sort-builtins.h.
Referenced by FindBestPredecessorOf().
kMaxDensityDecreaseThreshold
const uint32_t v8::internal::BuiltinsSorter::kMaxDensityDecreaseThreshold = 8 [private]
Definition at line 76 of file sort-builtins.h.
Referenced by FindBestPredecessorOf().
kMinEdgeProbabilityThreshold
const int32_t v8::internal::BuiltinsSorter::kMinEdgeProbabilityThreshold = 10 [private]
Definition at line 74 of file sort-builtins.h.
Referenced by FindBestPredecessorOf().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/sort-builtins.h
/mnt/V8SourceCode/src/snapshot/sort-builtins.cc