cppgc::internal::HeapStatisticsCollector Class Reference
#include <heap-statistics-collector.h>
Public Member Functions
HeapStatistics CollectDetailedStatistics (HeapBase *)
Private Member Functions
bool VisitNormalPageSpace (NormalPageSpace &)
bool VisitLargePageSpace (LargePageSpace &)
bool VisitNormalPage (NormalPage &)
bool VisitLargePage (LargePage &)
bool VisitHeapObjectHeader (HeapObjectHeader &)
Private Attributes
HeapStatistics * current_stats_
HeapStatistics::SpaceStatistics * current_space_stats_ = nullptr
HeapStatistics::PageStatistics * current_page_stats_ = nullptr
std::unordered_map< const void *, size_t > type_name_to_index_map_
Friends
class HeapVisitor< HeapStatisticsCollector >
Detailed Description
Definition at line 16 of file heap-statistics-collector.h.
Member Function Documentation
CollectDetailedStatistics()
HeapStatistics cppgc::internal::HeapStatisticsCollector::CollectDetailedStatistics (HeapBase * heap)
Definition at line 95 of file heap-statistics-collector.cc.
                    {
  HeapStatistics stats;
  stats.detail_level = HeapStatistics::DetailLevel::kDetailed;
  current_stats_ = &stats;
  ClassNameAsHeapObjectNameScope class_names_scope(*heap);
  Traverse(heap->raw_heap());
  FinalizeSpace(current_stats_, &current_space_stats_, &current_page_stats_);
  if (NameProvider::SupportsCppClassNamesAsObjectNames()) {
    stats.type_names.resize(type_name_to_index_map_.size());
    for (auto& it : type_name_to_index_map_) {
      stats.type_names[it.second] = reinterpret_cast<const char*>(it.first);
    }
  }
  // Resident set size may be smaller than the than the recorded size in
  // `StatsCollector` due to discarded memory that is tracked on page level.
  // This only holds before we account for pooled memory.
  DCHECK_GE(heap->stats_collector()->allocated_memory_size(),
            stats.resident_size_bytes);
  size_t pooled_memory = heap->page_backend()->page_pool().PooledMemory();
  stats.committed_size_bytes += pooled_memory;
  stats.resident_size_bytes += pooled_memory;
  stats.pooled_memory_size_bytes = pooled_memory;
  return stats;
}
References cppgc::HeapStatistics::committed_size_bytes, current_page_stats_, current_space_stats_, current_stats_, DCHECK_GE, cppgc::HeapStatistics::detail_level, cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::FinalizeSpace(), cppgc::HeapStatistics::pooled_memory_size_bytes, cppgc::HeapStatistics::resident_size_bytes, cppgc::NameProvider::SupportsCppClassNamesAsObjectNames(), cppgc::internal::HeapVisitor< HeapStatisticsCollector >::Traverse(), type_name_to_index_map_, and cppgc::HeapStatistics::type_names.
Referenced by cppgc::internal::HeapBase::CollectStatistics().
VisitHeapObjectHeader()
bool cppgc::internal::HeapStatisticsCollector::VisitHeapObjectHeader (HeapObjectHeader & header) [private]
Definition at line 171 of file heap-statistics-collector.cc.
                                                                            {
  if (header.IsFree()) return true;
  DCHECK_NOT_NULL(current_space_stats_);
  DCHECK_NOT_NULL(current_page_stats_);
  // For the purpose of heap statistics, the header counts towards the allocated
  // object size.
  const size_t allocated_object_size =
      header.IsLargeObject()
          ? LargePage::From(
                BasePage::FromPayload(const_cast<HeapObjectHeader*>(&header)))
                ->PayloadSize()
          : header.AllocatedSize();
  RecordObjectType(type_name_to_index_map_,
                   current_page_stats_->object_statistics, &header,
                   allocated_object_size);
  current_page_stats_->used_size_bytes += allocated_object_size;
  return true;
}
References cppgc::internal::HeapObjectHeader::AllocatedSize(), current_page_stats_, current_space_stats_, DCHECK_NOT_NULL, cppgc::internal::LargePage::From(), cppgc::internal::BasePage::FromPayload(), cppgc::internal::HeapObjectHeader::IsFree(), cppgc::internal::HeapObjectHeader::IsLargeObject(), cppgc::HeapStatistics::PageStatistics::object_statistics, cppgc::internal::LargePage::PayloadSize(), cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::RecordObjectType(), type_name_to_index_map_, and cppgc::HeapStatistics::PageStatistics::used_size_bytes.
VisitLargePage()
bool cppgc::internal::HeapStatisticsCollector::VisitLargePage (LargePage & page) [private]
Definition at line 159 of file heap-statistics-collector.cc.
                                                            {
  DCHECK_NOT_NULL(current_space_stats_);
  FinalizePage(current_space_stats_, &current_page_stats_);
  const size_t object_size = page.PayloadSize();
  const size_t allocated_size = LargePage::AllocationSize(object_size);
  current_page_stats_ = InitializePage(current_space_stats_);
  current_page_stats_->committed_size_bytes = allocated_size;
  current_page_stats_->resident_size_bytes = allocated_size;
  return false;
}
References cppgc::internal::LargePage::AllocationSize(), cppgc::HeapStatistics::PageStatistics::committed_size_bytes, current_page_stats_, current_space_stats_, DCHECK_NOT_NULL, cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::FinalizePage(), cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::InitializePage(), cppgc::internal::LargePage::PayloadSize(), and cppgc::HeapStatistics::PageStatistics::resident_size_bytes.
VisitLargePageSpace()
bool cppgc::internal::HeapStatisticsCollector::VisitLargePageSpace (LargePageSpace & space) [private]
Definition at line 140 of file heap-statistics-collector.cc.
                                                                       {
  FinalizeSpace(current_stats_, &current_space_stats_, &current_page_stats_);
  current_space_stats_ = InitializeSpace(current_stats_, "LargePageSpace");
  return false;
}
References current_page_stats_, current_space_stats_, current_stats_, cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::FinalizeSpace(), and cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::InitializeSpace().
VisitNormalPage()
bool cppgc::internal::HeapStatisticsCollector::VisitNormalPage (NormalPage & page) [private]
Definition at line 148 of file heap-statistics-collector.cc.
                                                              {
  DCHECK_NOT_NULL(current_space_stats_);
  FinalizePage(current_space_stats_, &current_page_stats_);
  current_page_stats_ = InitializePage(current_space_stats_);
  current_page_stats_->committed_size_bytes = kPageSize;
  current_page_stats_->resident_size_bytes =
      kPageSize - page.discarded_memory();
  return false;
}
References cppgc::HeapStatistics::PageStatistics::committed_size_bytes, current_page_stats_, current_space_stats_, DCHECK_NOT_NULL, cppgc::internal::BasePage::discarded_memory(), cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::FinalizePage(), cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::InitializePage(), cppgc::internal::kPageSize, and cppgc::HeapStatistics::PageStatistics::resident_size_bytes.
VisitNormalPageSpace()
bool cppgc::internal::HeapStatisticsCollector::VisitNormalPageSpace (NormalPageSpace & space) [private]
Definition at line 127 of file heap-statistics-collector.cc.
                                                                         {
  DCHECK_EQ(0u, space.linear_allocation_buffer().size());
  FinalizeSpace(current_stats_, &current_space_stats_, &current_page_stats_);
  current_space_stats_ =
      InitializeSpace(current_stats_, GetNormalPageSpaceName(space.index()));
  space.free_list().CollectStatistics(current_space_stats_->free_list_stats);
  return false;
}
References current_page_stats_, current_space_stats_, current_stats_, DCHECK_EQ, cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::FinalizeSpace(), cppgc::HeapStatistics::SpaceStatistics::free_list_stats, cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::GetNormalPageSpaceName(), cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::InitializeSpace(), and space.
Friends And Related Function Documentation
HeapVisitor< HeapStatisticsCollector >
friend class HeapVisitor< HeapStatisticsCollector > [friend]
Definition at line 1 of file heap-statistics-collector.h.
Member Data Documentation
current_page_stats_
HeapStatistics::PageStatistics* cppgc::internal::HeapStatisticsCollector::current_page_stats_ = nullptr [private]
Definition at line 31 of file heap-statistics-collector.h.
Referenced by CollectDetailedStatistics(), VisitHeapObjectHeader(), VisitLargePage(), VisitLargePageSpace(), VisitNormalPage(), and VisitNormalPageSpace().
current_space_stats_
HeapStatistics::SpaceStatistics* cppgc::internal::HeapStatisticsCollector::current_space_stats_ = nullptr [private]
Definition at line 30 of file heap-statistics-collector.h.
Referenced by CollectDetailedStatistics(), VisitHeapObjectHeader(), VisitLargePage(), VisitLargePageSpace(), VisitNormalPage(), and VisitNormalPageSpace().
current_stats_
HeapStatistics* cppgc::internal::HeapStatisticsCollector::current_stats_ [private]
Definition at line 29 of file heap-statistics-collector.h.
Referenced by CollectDetailedStatistics(), VisitLargePageSpace(), and VisitNormalPageSpace().
type_name_to_index_map_
std::unordered_map<const void*, size_t> cppgc::internal::HeapStatisticsCollector::type_name_to_index_map_ [private]
Definition at line 36 of file heap-statistics-collector.h.
Referenced by CollectDetailedStatistics(), and VisitHeapObjectHeader().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/heap-statistics-collector.h
/mnt/V8SourceCode/src/heap/cppgc/heap-statistics-collector.cc