v8::internal::interpreter::BytecodeGenerator::TestResultScope Class Reference
Public Member Functions
TestResultScope (BytecodeGenerator *generator, BytecodeLabels *then_labels, BytecodeLabels *else_labels, TestFallthrough fallthrough)
TestResultScope (const TestResultScope &)=delete
TestResultScope & operator= (const TestResultScope &)=delete
void SetResultConsumedByTest ()
bool result_consumed_by_test ()
void InvertControlFlow ()
BytecodeLabel * NewThenLabel ()
BytecodeLabel * NewElseLabel ()
BytecodeLabels * then_labels () const
BytecodeLabels * else_labels () const
void set_then_labels (BytecodeLabels *then_labels)
void set_else_labels (BytecodeLabels *else_labels)
TestFallthrough fallthrough () const
TestFallthrough inverted_fallthrough () const
void set_fallthrough (TestFallthrough fallthrough)
Private Attributes
bool result_consumed_by_test_
TestFallthrough fallthrough_
BytecodeLabels * then_labels_
BytecodeLabels * else_labels_
Additional Inherited Members
Detailed Description
Definition at line 791 of file bytecode-generator.cc.
Constructor & Destructor Documentation
TestResultScope() [1/2]
v8::internal::interpreter::BytecodeGenerator::TestResultScope::TestResultScope (BytecodeGenerator * generator, BytecodeLabels * then_labels, BytecodeLabels * else_labels, TestFallthrough fallthrough) [inline]
Definition at line 794 of file bytecode-generator.cc.
      : ExpressionResultScope(generator, kTest),
        result_consumed_by_test_(false),
        fallthrough_(fallthrough),
        then_labels_(then_labels),
        else_labels_(else_labels) {}
TestResultScope() [2/2]
v8::internal::interpreter::BytecodeGenerator::TestResultScope::TestResultScope (const TestResultScope &) [delete]
Member Function Documentation
else_labels()
BytecodeLabels* v8::internal::interpreter::BytecodeGenerator::TestResultScope::else_labels () const [inline]
Definition at line 821 of file bytecode-generator.cc.
{ return else_labels_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitForTest(), v8::internal::interpreter::BytecodeGenerator::VisitInSameTestExecutionScope(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalTest(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalTest().
fallthrough()
TestFallthrough v8::internal::interpreter::BytecodeGenerator::TestResultScope::fallthrough () const [inline]
Definition at line 830 of file bytecode-generator.cc.
{ return fallthrough_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLiteralCompareNil(), v8::internal::interpreter::BytecodeGenerator::VisitForTest(), v8::internal::interpreter::BytecodeGenerator::VisitInSameTestExecutionScope(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalTest(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalTest().
InvertControlFlow()
void v8::internal::interpreter::BytecodeGenerator::TestResultScope::InvertControlFlow () [inline]
Definition at line 812 of file bytecode-generator.cc.
                           {
    std::swap(then_labels_, else_labels_);
    fallthrough_ = inverted_fallthrough();
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitNot().
inverted_fallthrough()
TestFallthrough v8::internal::interpreter::BytecodeGenerator::TestResultScope::inverted_fallthrough () const [inline]
Definition at line 831 of file bytecode-generator.cc.
                                               {
    switch (fallthrough_) {
      case TestFallthrough::kThen:
        return TestFallthrough::kElse;
      case TestFallthrough::kElse:
        return TestFallthrough::kThen;
      default:
        return TestFallthrough::kNone;
    }
  }
References v8::internal::interpreter::BytecodeGenerator::kElse, v8::internal::interpreter::BytecodeGenerator::kNone, and v8::internal::interpreter::BytecodeGenerator::kThen.
NewElseLabel()
BytecodeLabel* v8::internal::interpreter::BytecodeGenerator::TestResultScope::NewElseLabel () [inline]
Definition at line 818 of file bytecode-generator.cc.
{ return else_labels_->New(); }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLiteralCompareNil(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalAndExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNullishExpression().
NewThenLabel()
BytecodeLabel* v8::internal::interpreter::BytecodeGenerator::TestResultScope::NewThenLabel () [inline]
Definition at line 817 of file bytecode-generator.cc.
{ return then_labels_->New(); }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLiteralCompareNil(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryNullishExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNullishExpression().
operator=()
TestResultScope& v8::internal::interpreter::BytecodeGenerator::TestResultScope::operator= (const TestResultScope &) [delete]
result_consumed_by_test()
bool v8::internal::interpreter::BytecodeGenerator::TestResultScope::result_consumed_by_test () [inline]
Definition at line 808 of file bytecode-generator.cc.
{ return result_consumed_by_test_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitForTest().
set_else_labels()
void v8::internal::interpreter::BytecodeGenerator::TestResultScope::set_else_labels (BytecodeLabels * else_labels) [inline]
Definition at line 826 of file bytecode-generator.cc.
                                                    {
    else_labels_ = else_labels;
  }
set_fallthrough()
void v8::internal::interpreter::BytecodeGenerator::TestResultScope::set_fallthrough (TestFallthrough fallthrough) [inline]
Definition at line 841 of file bytecode-generator.cc.
                                                    {
    fallthrough_ = fallthrough;
  }
set_then_labels()
void v8::internal::interpreter::BytecodeGenerator::TestResultScope::set_then_labels (BytecodeLabels * then_labels) [inline]
Definition at line 823 of file bytecode-generator.cc.
                                                    {
    then_labels_ = then_labels;
  }
SetResultConsumedByTest()
void v8::internal::interpreter::BytecodeGenerator::TestResultScope::SetResultConsumedByTest () [inline]
Definition at line 807 of file bytecode-generator.cc.
{ result_consumed_by_test_ = true; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildLiteralCompareNil(), v8::internal::interpreter::BytecodeGenerator::VisitInSameTestExecutionScope(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryNullishExpression(), and v8::internal::interpreter::BytecodeGenerator::VisitNullishExpression().
then_labels()
BytecodeLabels* v8::internal::interpreter::BytecodeGenerator::TestResultScope::then_labels () const [inline]
Definition at line 820 of file bytecode-generator.cc.
{ return then_labels_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::VisitForTest(), v8::internal::interpreter::BytecodeGenerator::VisitInSameTestExecutionScope(), v8::internal::interpreter::BytecodeGenerator::VisitLogicalTest(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalTest().
Member Data Documentation
else_labels_
BytecodeLabels* v8::internal::interpreter::BytecodeGenerator::TestResultScope::else_labels_ [private]
Definition at line 849 of file bytecode-generator.cc.
fallthrough_
TestFallthrough v8::internal::interpreter::BytecodeGenerator::TestResultScope::fallthrough_ [private]
Definition at line 847 of file bytecode-generator.cc.
result_consumed_by_test_
bool v8::internal::interpreter::BytecodeGenerator::TestResultScope::result_consumed_by_test_ [private]
Definition at line 846 of file bytecode-generator.cc.
then_labels_
BytecodeLabels* v8::internal::interpreter::BytecodeGenerator::TestResultScope::then_labels_ [private]
Definition at line 848 of file bytecode-generator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/interpreter/bytecode-generator.cc