v8::internal::HeapObjectLayout Class Reference
#include <heap-object.h>
Public Member Functions
HeapObjectLayout ()=delete
Tagged< Map > map () const
Tagged< Map > map (AcquireLoadTag) const
MapWord map_word (RelaxedLoadTag) const
void set_map (Isolate *isolate, Tagged< Map > value)
template<typename IsolateT >
void set_map (IsolateT *isolate, Tagged< Map > value, ReleaseStoreTag)
template<typename IsolateT >
void set_map_safe_transition (IsolateT *isolate, Tagged< Map > value, ReleaseStoreTag)
ObjectSlot map_slot () const
void set_map_safe_transition_no_write_barrier (Isolate *isolate, Tagged< Map > value, RelaxedStoreTag=kRelaxedStore)
template<typename IsolateT >
void set_map_after_allocation (IsolateT *isolate, Tagged< Map > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void set_map_no_write_barrier (Isolate *isolate, Tagged< Map > value, RelaxedStoreTag=kRelaxedStore)
void set_map_word_forwarded (Tagged< HeapObject > target_object, ReleaseStoreTag)
void set_map_word_forwarded (Tagged< HeapObject > target_object, RelaxedStoreTag)
Address ptr () const
Address address () const
ReadOnlyRoots EarlyGetReadOnlyRoots () const
int Size () const
V8_EXPORT_PRIVATE int SizeFromMap (Tagged< Map > map) const
WriteBarrierMode GetWriteBarrierMode (const DisallowGarbageCollection &promise)
Private Member Functions
HeapObjectLayout (HeapObjectLayout &&) V8_NOEXCEPT=delete
HeapObjectLayout (const HeapObjectLayout &) V8_NOEXCEPT=delete
HeapObjectLayout & operator= (HeapObjectLayout &&) V8_NOEXCEPT=delete
HeapObjectLayout & operator= (const HeapObjectLayout &) V8_NOEXCEPT=delete
Private Attributes
TaggedMember< Map > map_
Friends
class HeapObject
class Heap
class CodeStubAssembler
Detailed Description
Definition at line 31 of file heap-object.h.
Constructor & Destructor Documentation
HeapObjectLayout() [1/3]
v8::internal::HeapObjectLayout::HeapObjectLayout () [delete]
HeapObjectLayout() [2/3]
v8::internal::HeapObjectLayout::HeapObjectLayout (HeapObjectLayout &&) [private], [delete]
HeapObjectLayout() [3/3]
v8::internal::HeapObjectLayout::HeapObjectLayout (const HeapObjectLayout &) [private], [delete]
Member Function Documentation
address()
Address v8::internal::HeapObjectLayout::address () const [inline]
Definition at line 84 of file heap-object.h.
{ return reinterpret_cast<Address>(this); }
Referenced by v8::internal::HeapObject::FromAddress(), v8::internal::ExternalString::InitExternalPointerFields(), v8::internal::ExternalString::InitExternalPointerFieldsDuringExternalization(), ptr(), and v8::internal::SeqOneByteString::SeqOneByteStringSetChars().
EarlyGetReadOnlyRoots()
ReadOnlyRoots v8::internal::HeapObjectLayout::EarlyGetReadOnlyRoots () const [inline]
Definition at line 1367 of file objects-inl.h.
                                                            {
  return ReadOnlyHeap::EarlyGetReadOnlyRoots(Tagged(this));
}
References v8::internal::ReadOnlyHeap::EarlyGetReadOnlyRoots(), and v8::internal::Tagged().
GetWriteBarrierMode()
WriteBarrierMode v8::internal::HeapObjectLayout::GetWriteBarrierMode (const DisallowGarbageCollection & promise) [inline]
Definition at line 1711 of file objects-inl.h.
                                              {
  return WriteBarrier::GetWriteBarrierModeForObject(this, promise);
}
References v8::internal::WriteBarrier::GetWriteBarrierModeForObject().
map() [1/2]
Tagged< Map > v8::internal::HeapObjectLayout::map () const [inline]
Definition at line 1384 of file objects-inl.h.
                                        {
  // TODO(leszeks): Support MapWord members and access via that instead.
  return Tagged<HeapObject>(this)->map();
}
References v8::internal::Tagged< HeapObject >.
Referenced by v8::internal::DataHandler::data_field_count(), v8::internal::AllocationSite::HasWeakNext(), v8::internal::ExternalString::is_uncached(), v8::internal::SeqOneByteString::IsCompatibleMap(), v8::internal::SeqTwoByteString::IsCompatibleMap(), v8::internal::String::IsOneByteRepresentation(), v8::internal::String::IsTwoByteRepresentation(), v8::internal::String::MakeThin(), SizeFromMap(), v8::internal::AllocationSite::BodyDescriptor::SizeOf(), v8::internal::ExternalString::BodyDescriptor::SizeOf(), and v8::internal::DataHandler::BodyDescriptor::SizeOf().
map() [2/2]
Tagged< Map > v8::internal::HeapObjectLayout::map (AcquireLoadTag) const [inline]
Definition at line 1389 of file objects-inl.h.
                                                      {
  // TODO(leszeks): Support MapWord members and access via that instead.
  return Tagged<HeapObject>(this)->map(kAcquireLoad);
}
References v8::kAcquireLoad, and v8::internal::Tagged< HeapObject >.
map_slot()
ObjectSlot v8::internal::HeapObjectLayout::map_slot () const [inline]
Definition at line 1560 of file objects-inl.h.
                                            {
  return Tagged<HeapObject>(this)->map_slot();
}
References v8::internal::Tagged< HeapObject >.
Referenced by v8::internal::Heap::IsFreeSpaceValid().
map_word()
MapWord v8::internal::HeapObjectLayout::map_word (RelaxedLoadTag) const [inline]
Definition at line 1394 of file objects-inl.h.
                                                       {
  // TODO(leszeks): Support MapWord members and access via that instead.
  return Tagged<HeapObject>(this)->map_word(kRelaxedLoad);
}
References v8::kRelaxedLoad, and v8::internal::Tagged< HeapObject >.
operator=() [1/2]
HeapObjectLayout& v8::internal::HeapObjectLayout::operator= (const HeapObjectLayout &) [private], [delete]
operator=() [2/2]
HeapObjectLayout& v8::internal::HeapObjectLayout::operator= (HeapObjectLayout &&) [private], [delete]
ptr()
Address v8::internal::HeapObjectLayout::ptr () const [inline]
Definition at line 81 of file heap-object.h.
{ return address() + kHeapObjectTag; }
References address(), and v8::internal::kHeapObjectTag.
Referenced by v8::internal::HeapObject::address(), v8::internal::HeapObject::field_address(), v8::internal::FreeSpace::next(), v8::internal::operator!=(), v8::internal::operator==(), and v8::internal::FreeSpace::SetNext().
set_map() [1/2]
void v8::internal::HeapObjectLayout::set_map (Isolate * isolate, Tagged< Map > value) [inline]
Definition at line 1399 of file objects-inl.h.
                                                                  {
  // TODO(leszeks): Support MapWord members and access via that instead.
  return Tagged<HeapObject>(this)->set_map(isolate, value);
}
References v8::internal::Tagged< HeapObject >, and v8::internal::value.
Referenced by v8::internal::String::MakeExternal(), v8::internal::String::MakeExternalDuringGC(), and v8::internal::String::MakeThin().
set_map() [2/2]
template<typename IsolateT >
void v8::internal::HeapObjectLayout::set_map (IsolateT * isolate, Tagged< Map > value, ReleaseStoreTag) [inline]
Definition at line 1405 of file objects-inl.h.
                                                {
  // TODO(leszeks): Support MapWord members and access via that instead.
  return Tagged<HeapObject>(this)->set_map(isolate, value, kReleaseStore);
}
References v8::kReleaseStore, v8::internal::Tagged< HeapObject >, and v8::internal::value.
set_map_after_allocation()
template<typename IsolateT >
void v8::internal::HeapObjectLayout::set_map_after_allocation (IsolateT * isolate, Tagged< Map > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 1526 of file objects-inl.h.
                                                                       {
  // TODO(leszeks): Support MapWord members and access via that instead.
  Tagged<HeapObject>(this)->set_map_after_allocation(isolate, value, mode);
}
References mode(), v8::internal::Tagged< HeapObject >, and v8::internal::value.
set_map_no_write_barrier()
void v8::internal::HeapObjectLayout::set_map_no_write_barrier (Isolate * isolate, Tagged< Map > value, RelaxedStoreTag tag = kRelaxedStore) [inline]
Definition at line 1466 of file objects-inl.h.
                                                                     {
  // TODO(leszeks): Support MapWord members and access via that instead.
  Tagged<HeapObject>(this)->set_map_no_write_barrier(isolate, value, tag);
}
References v8::internal::Tagged< HeapObject >, and v8::internal::value.
set_map_safe_transition()
template<typename IsolateT >
void v8::internal::HeapObjectLayout::set_map_safe_transition (IsolateT * isolate, Tagged< Map > value, ReleaseStoreTag) [inline]
Definition at line 1412 of file objects-inl.h.
                                                                {
  // TODO(leszeks): Support MapWord members and access via that instead.
  return Tagged<HeapObject>(this)->set_map_safe_transition(isolate, value,
                                                           kReleaseStore);
}
References v8::kReleaseStore, v8::internal::Tagged< HeapObject >, and v8::internal::value.
Referenced by v8::internal::String::MakeThin().
set_map_safe_transition_no_write_barrier()
void v8::internal::HeapObjectLayout::set_map_safe_transition_no_write_barrier (Isolate * isolate, Tagged< Map > value, RelaxedStoreTag tag = kRelaxedStore) [inline]
Definition at line 1445 of file objects-inl.h.
                                                              {
  // TODO(leszeks): Support MapWord members and access via that instead.
  return Tagged<HeapObject>(this)->set_map_safe_transition_no_write_barrier(
      isolate, value, tag);
}
References v8::internal::Tagged< HeapObject >, and v8::internal::value.
set_map_word_forwarded() [1/2]
void v8::internal::HeapObjectLayout::set_map_word_forwarded (Tagged< HeapObject > target_object, RelaxedStoreTag tag) [inline]
Definition at line 1614 of file objects-inl.h.
                                                                   {
  // TODO(leszeks): Support MapWord members and access via that instead.
  Tagged<HeapObject>(this)->set_map_word_forwarded(target_object, tag);
}
References v8::internal::Tagged< HeapObject >.
set_map_word_forwarded() [2/2]
void v8::internal::HeapObjectLayout::set_map_word_forwarded (Tagged< HeapObject > target_object, ReleaseStoreTag tag) [inline]
Definition at line 1608 of file objects-inl.h.
                                                                   {
  // TODO(leszeks): Support MapWord members and access via that instead.
  Tagged<HeapObject>(this)->set_map_word_forwarded(target_object, tag);
}
References v8::internal::Tagged< HeapObject >.
Size()
int v8::internal::HeapObjectLayout::Size () const [inline]
Definition at line 1642 of file objects-inl.h.
{ return Tagged<HeapObject>(this)->Size(); }
References v8::internal::Tagged< HeapObject >.
Referenced by v8::internal::String::MakeExternal(), v8::internal::String::MakeExternalDuringGC(), and v8::internal::String::SupportsExternalization().
SizeFromMap()
int v8::internal::HeapObjectLayout::SizeFromMap (Tagged< Map > map) const
Definition at line 1939 of file objects.cc.
                                                       {
  return Tagged<HeapObject>(this)->SizeFromMap(map);
}
References map(), and v8::internal::Tagged< HeapObject >.
Referenced by v8::internal::String::MakeExternal(), v8::internal::String::MakeExternalDuringGC(), and v8::internal::String::MakeThin().
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 113 of file heap-object.h.
Heap
friend class Heap [friend]
Definition at line 112 of file heap-object.h.
HeapObject
friend class HeapObject [friend]
Definition at line 111 of file heap-object.h.
Member Data Documentation
map_
TaggedMember<Map> v8::internal::HeapObjectLayout::map_ [private]
Definition at line 123 of file heap-object.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/heap-object.h
/mnt/V8SourceCode/src/objects/objects-inl.h
/mnt/V8SourceCode/src/objects/objects.cc