v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues Class Reference
Classes
struct BigUnit
struct BigUnitsQueue
struct Queue
struct QueueImpl
struct TopTierPriorityUnit
Public Member Functions
CompilationUnitQueues (int num_imported_functions, int num_declared_functions)
Queue * GetQueueForTask (int task_id)
std::optional< WasmCompilationUnit > GetNextUnit (Queue *queue, CompilationTier tier)
void AddUnits (base::Vector< WasmCompilationUnit > baseline_units, base::Vector< WasmCompilationUnit > top_tier_units, const WasmModule *module)
void AddTopTierPriorityUnit (WasmCompilationUnit unit, size_t priority)
size_t GetSizeForTier (CompilationTier tier) const
void AllowAnotherTopTierJob (uint32_t func_index)
size_t EstimateCurrentMemoryConsumption () const
Private Member Functions
int next_task_id (int task_id, size_t num_queues) const
std::optional< WasmCompilationUnit > GetNextUnitOfTier (Queue *public_queue, int tier)
std::optional< WasmCompilationUnit > GetBigUnitOfTier (int tier)
std::optional< WasmCompilationUnit > GetTopTierPriorityUnit (QueueImpl *queue)
std::optional< WasmCompilationUnit > StealUnitsAndGetFirst (QueueImpl *queue, int steal_from_task_id, int wanted_tier)
std::optional< WasmCompilationUnit > StealTopTierPriorityUnit (QueueImpl *queue, int steal_from_task_id)
int declared_function_index (int func_index) const
Private Attributes
base::Mutex queues_mutex_
std::vector< std::unique_ptr< QueueImpl > > queues_
const int num_imported_functions_
const int num_declared_functions_
BigUnitsQueue big_units_queue_
std::atomic< size_t > num_units_ [CompilationTier::kNumTiers]
std::atomic< size_t > num_priority_units_ {0}
std::unique_ptr< std::atomic< bool >[]> top_tier_compiled_
std::atomic< int > next_queue_to_add {0}
Static Private Attributes
static constexpr size_t kBigUnitsLimit = 4096
Detailed Description
Definition at line 108 of file module-compiler.cc.
Constructor & Destructor Documentation
CompilationUnitQueues()
v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::CompilationUnitQueues (int num_imported_functions, int num_declared_functions) [inline], [explicit]
Definition at line 115 of file module-compiler.cc.
      : num_imported_functions_(num_imported_functions),
        num_declared_functions_(num_declared_functions) {
    // Add one first queue, to add units to.
    queues_.emplace_back(std::make_unique<QueueImpl>(0));
#if !defined(__cpp_lib_atomic_value_initialization) || \
    __cpp_lib_atomic_value_initialization < 201911L
    for (auto& atomic_counter : num_units_) {
      std::atomic_init(&atomic_counter, size_t{0});
    }
#endif
    top_tier_compiled_ =
        std::make_unique<std::atomic<bool>[]>(num_declared_functions);
#if !defined(__cpp_lib_atomic_value_initialization) || \
    __cpp_lib_atomic_value_initialization < 201911L
    for (int i = 0; i < num_declared_functions; i++) {
      std::atomic_init(&top_tier_compiled_.get()[i], false);
    }
#endif
  }
Member Function Documentation
AddTopTierPriorityUnit()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::AddTopTierPriorityUnit (WasmCompilationUnit unit, size_t priority) [inline]
Definition at line 234 of file module-compiler.cc.
                                                                         {
    base::MutexGuard queues_guard{&queues_mutex_};
    // Add to the individual queues in a round-robin fashion. No special care is
    // taken to balance them; they will be balanced by work stealing.
    // Priorities should only be seen as a hint here; without balancing, we
    // might pop a unit with lower priority from one queue while other queues
    // still hold higher-priority units.
    // Since updating priorities in a std::priority_queue is difficult, we just
    // add new units with higher priorities, and use the
    // {CompilationUnitQueues::top_tier_compiled_} array to discard units for
    // functions which are already being compiled.
    int queue_to_add = next_queue_to_add.load(std::memory_order_relaxed);
    while (!next_queue_to_add.compare_exchange_weak(
        queue_to_add, next_task_id(queue_to_add, queues_.size()),
        std::memory_order_relaxed)) {
      // Retry with updated {queue_to_add}.
    }
    {
      auto* queue = queues_[queue_to_add].get();
      base::MutexGuard guard(&queue->mutex);
      queue->top_tier_priority_units.emplace(priority, unit);
      num_priority_units_.fetch_add(1, std::memory_order_relaxed);
      num_units_[CompilationTier::kTopTier].fetch_add(
          1, std::memory_order_relaxed);
    }
  }
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kTopTier.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::AddTopTierPriorityCompilationUnit().
AddUnits()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::AddUnits (base::Vector< WasmCompilationUnit > baseline_units, base::Vector< WasmCompilationUnit > top_tier_units, const WasmModule * module) [inline]
Definition at line 191 of file module-compiler.cc.
                                          {
    DCHECK_LT(0, baseline_units.size() + top_tier_units.size());
    // Add to the individual queues in a round-robin fashion. No special care is
    // taken to balance them; they will be balanced by work stealing.
    QueueImpl* queue;
    {
      int queue_to_add = next_queue_to_add.load(std::memory_order_relaxed);
      base::MutexGuard queues_guard{&queues_mutex_};
      while (!next_queue_to_add.compare_exchange_weak(
          queue_to_add, next_task_id(queue_to_add, queues_.size()),
          std::memory_order_relaxed)) {
        // Retry with updated {queue_to_add}.
      }
      queue = queues_[queue_to_add].get();
    }
    base::MutexGuard guard(&queue->mutex);
    std::optional<base::MutexGuard> big_units_guard;
    for (auto pair :
         {std::make_pair(CompilationTier::kBaseline, baseline_units),
          std::make_pair(CompilationTier::kTopTier, top_tier_units)}) {
      int tier = pair.first;
      base::Vector<WasmCompilationUnit> units = pair.second;
      if (units.empty()) continue;
      num_units_[tier].fetch_add(units.size(), std::memory_order_relaxed);
      for (WasmCompilationUnit unit : units) {
        size_t func_size = module->functions[unit.func_index()].code.length();
        if (func_size <= kBigUnitsLimit) {
          queue->units[tier].push_back(unit);
        } else {
          if (!big_units_guard) {
            big_units_guard.emplace(&big_units_queue_.mutex);
          }
          big_units_queue_.has_units[tier].store(true,
                                                 std::memory_order_relaxed);
          big_units_queue_.units[tier].emplace(func_size, unit);
        }
      }
    }
  }
References DCHECK_LT, v8::base::Vector< T >::empty(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kBaseline, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kTopTier, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::QueueImpl::mutex, v8::base::Vector< T >::size(), and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::QueueImpl::units.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::CommitCompilationUnits().
AllowAnotherTopTierJob()
void v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::AllowAnotherTopTierJob (uint32_t func_index) [inline]
Definition at line 270 of file module-compiler.cc.
                                                   {
    top_tier_compiled_[declared_function_index(func_index)].store(
        false, std::memory_order_relaxed);
  }
References v8::internal::wasm::declared_function_index().
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::OnFinishedUnits().
declared_function_index()
int v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::declared_function_index (int func_index) const [inline], [private]
Definition at line 509 of file module-compiler.cc.
                                                    {
    DCHECK_LE(num_imported_functions_, func_index);
    DCHECK_LT(func_index, num_imported_functions_ + num_declared_functions_);
    return func_index - num_imported_functions_;
  }
References DCHECK_LE, and DCHECK_LT.
EstimateCurrentMemoryConsumption()
size_t v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::EstimateCurrentMemoryConsumption () const
Definition at line 530 of file module-compiler.cc.
                                                                     {
  UPDATE_WHEN_CLASS_CHANGES(CompilationUnitQueues, 176);
  UPDATE_WHEN_CLASS_CHANGES(QueueImpl, 112);
  UPDATE_WHEN_CLASS_CHANGES(BigUnitsQueue, 88);
  // Not including sizeof(CompilationUnitQueues) because that's included in
  // sizeof(CompilationStateImpl).
  size_t result = 0;
  {
    base::MutexGuard mutex_guard(&queues_mutex_);
    result += ContentSize(queues_) + queues_.size() * sizeof(QueueImpl);
    for (const auto& q : queues_) {
      base::MutexGuard guard(&q->mutex);
      result += ContentSize(*q->units);
      result += q->top_tier_priority_units.size() * sizeof(TopTierPriorityUnit);
    }
  }
  {
    base::MutexGuard lock(&big_units_queue_.mutex);
    result += big_units_queue_.units[0].size() * sizeof(BigUnit);
    result += big_units_queue_.units[1].size() * sizeof(BigUnit);
  }
  // For {top_tier_compiled_}.
  result += sizeof(std::atomic<bool>) * num_declared_functions_;
  return result;
}
References v8::internal::wasm::ContentSize(), v8::base::internal::result, and UPDATE_WHEN_CLASS_CHANGES.
GetBigUnitOfTier()
std::optional<WasmCompilationUnit> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::GetBigUnitOfTier (int tier) [inline], [private]
Definition at line 392 of file module-compiler.cc.
                                                              {
    // Fast path without locking.
    if (!big_units_queue_.has_units[tier].load(std::memory_order_relaxed)) {
      return {};
    }
    base::MutexGuard guard(&big_units_queue_.mutex);
    if (big_units_queue_.units[tier].empty()) return {};
    WasmCompilationUnit unit = big_units_queue_.units[tier].top().unit;
    big_units_queue_.units[tier].pop();
    if (big_units_queue_.units[tier].empty()) {
      big_units_queue_.has_units[tier].store(false, std::memory_order_relaxed);
    }
    return unit;
  }
GetNextUnit()
std::optional<WasmCompilationUnit> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::GetNextUnit (Queue * queue, CompilationTier tier) [inline]
Definition at line 179 of file module-compiler.cc.
                                                                       {
    DCHECK_LT(tier, CompilationTier::kNumTiers);
    if (auto unit = GetNextUnitOfTier(queue, tier)) {
      [[maybe_unused]] size_t old_units_count =
          num_units_[tier].fetch_sub(1, std::memory_order_relaxed);
      DCHECK_LE(1, old_units_count);
      return unit;
    }
    return {};
  }
References DCHECK_LE, DCHECK_LT, and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kNumTiers.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::GetNextCompilationUnit().
GetNextUnitOfTier()
std::optional<WasmCompilationUnit> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::GetNextUnitOfTier (Queue * public_queue, int tier) [inline], [private]
Definition at line 346 of file module-compiler.cc.
                                                                 {
    QueueImpl* queue = static_cast<QueueImpl*>(public_queue);
    // First check whether there is a priority unit. Execute that first.
    if (tier == CompilationTier::kTopTier) {
      if (auto unit = GetTopTierPriorityUnit(queue)) {
        return unit;
      }
    }
    // Then check whether there is a big unit of that tier.
    if (auto unit = GetBigUnitOfTier(tier)) return unit;
    // Finally check whether our own queue has a unit of the wanted tier. If
    // so, return it, otherwise get the task id to steal from.
    int steal_task_id;
    {
      base::MutexGuard mutex_guard(&queue->mutex);
      if (!queue->units[tier].empty()) {
        auto unit = queue->units[tier].back();
        queue->units[tier].pop_back();
        return unit;
      }
      steal_task_id = queue->next_steal_task_id;
    }
    // Try to steal from all other queues. If this succeeds, return one of the
    // stolen units.
    {
      base::MutexGuard guard{&queues_mutex_};
      for (size_t steal_trials = 0; steal_trials < queues_.size();
           ++steal_trials, ++steal_task_id) {
        if (steal_task_id >= static_cast<int>(queues_.size())) {
          steal_task_id = 0;
        }
        if (auto unit = StealUnitsAndGetFirst(queue, steal_task_id, tier)) {
          return unit;
        }
      }
    }
    // If we reach here, we didn't find any unit of the requested tier.
    return {};
  }
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kTopTier, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::QueueImpl::mutex, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::QueueImpl::next_steal_task_id, and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::QueueImpl::units.
GetQueueForTask()
Queue* v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::GetQueueForTask (int task_id) [inline]
Definition at line 140 of file module-compiler.cc.
                                      {
    int required_queues = task_id + 1;
    {
      base::MutexGuard queues_guard{&queues_mutex_};
      if (V8_LIKELY(static_cast<int>(queues_.size()) >= required_queues)) {
        return queues_[task_id].get();
      }
    }
    // Otherwise increase the number of queues.
    base::MutexGuard queues_guard{&queues_mutex_};
    int num_queues = static_cast<int>(queues_.size());
    while (num_queues < required_queues) {
      int steal_from = num_queues + 1;
      queues_.emplace_back(std::make_unique<QueueImpl>(steal_from));
      ++num_queues;
    }
    // Update the {publish_limit}s of all queues.
    // We want background threads to publish regularly (to avoid contention when
    // they are all publishing at the end). On the other side, each publishing
    // has some overhead (part of it for synchronizing between threads), so it
    // should not happen *too* often. Thus aim for 4-8 publishes per thread, but
    // distribute it such that publishing is likely to happen at different
    // times.
    int units_per_thread = num_declared_functions_ / num_queues;
    int min = std::max(10, units_per_thread / 8);
    int queue_id = 0;
    for (auto& queue : queues_) {
      // Set a limit between {min} and {2*min}, but not smaller than {10}.
      int limit = min + (min * queue_id / num_queues);
      queue->publish_limit.store(limit, std::memory_order_relaxed);
      ++queue_id;
    }
    return queues_[task_id].get();
  }
References V8_LIKELY.
Referenced by v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationStateImpl::GetQueueForCompileTask().
GetSizeForTier()
size_t v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::GetSizeForTier (CompilationTier tier) const [inline]
Definition at line 265 of file module-compiler.cc.
                                                    {
    DCHECK_LT(tier, CompilationTier::kNumTiers);
    return num_units_[tier].load(std::memory_order_relaxed);
  }
References DCHECK_LT, and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kNumTiers.
GetTopTierPriorityUnit()
std::optional<WasmCompilationUnit> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::GetTopTierPriorityUnit (QueueImpl * queue) [inline], [private]
Definition at line 407 of file module-compiler.cc.
                                                                            {
    // Fast path without locking.
    if (num_priority_units_.load(std::memory_order_relaxed) == 0) {
      return {};
    }
    int steal_task_id;
    {
      base::MutexGuard mutex_guard(&queue->mutex);
      while (!queue->top_tier_priority_units.empty()) {
        auto unit = queue->top_tier_priority_units.top().unit;
        queue->top_tier_priority_units.pop();
        num_priority_units_.fetch_sub(1, std::memory_order_relaxed);
        if (!top_tier_compiled_[declared_function_index(unit.func_index())]
                 .exchange(true, std::memory_order_relaxed)) {
          return unit;
        }
        num_units_[CompilationTier::kTopTier].fetch_sub(
            1, std::memory_order_relaxed);
      }
      steal_task_id = queue->next_steal_task_id;
    }
    // Try to steal from all other queues. If this succeeds, return one of the
    // stolen units.
    {
      base::MutexGuard guard{&queues_mutex_};
      for (size_t steal_trials = 0; steal_trials < queues_.size();
           ++steal_trials, ++steal_task_id) {
        if (steal_task_id >= static_cast<int>(queues_.size())) {
          steal_task_id = 0;
        }
        if (auto unit = StealTopTierPriorityUnit(queue, steal_task_id)) {
          return unit;
        }
      }
    }
    return {};
  }
References v8::internal::wasm::declared_function_index(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kTopTier, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::QueueImpl::mutex, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::QueueImpl::next_steal_task_id, and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::QueueImpl::top_tier_priority_units.
next_task_id()
int v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::next_task_id (int task_id, size_t num_queues) const [inline], [private]
Definition at line 341 of file module-compiler.cc.
                                                         {
    int next = task_id + 1;
    return next == static_cast<int>(num_queues) ? 0 : next;
  }
StealTopTierPriorityUnit()
std::optional<WasmCompilationUnit> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::StealTopTierPriorityUnit (QueueImpl * queue, int steal_from_task_id) [inline], [private]
Definition at line 480 of file module-compiler.cc.
                                                {
    auto* steal_queue = queues_[steal_from_task_id].get();
    // Cannot steal from own queue.
    if (steal_queue == queue) return {};
    std::optional<WasmCompilationUnit> returned_unit;
    {
      base::MutexGuard guard(&steal_queue->mutex);
      while (true) {
        if (steal_queue->top_tier_priority_units.empty()) return {};
        auto unit = steal_queue->top_tier_priority_units.top().unit;
        steal_queue->top_tier_priority_units.pop();
        num_priority_units_.fetch_sub(1, std::memory_order_relaxed);
        if (!top_tier_compiled_[declared_function_index(unit.func_index())]
                 .exchange(true, std::memory_order_relaxed)) {
          returned_unit = unit;
          break;
        }
        num_units_[CompilationTier::kTopTier].fetch_sub(
            1, std::memory_order_relaxed);
      }
    }
    base::MutexGuard guard(&queue->mutex);
    queue->next_steal_task_id = steal_from_task_id + 1;
    return returned_unit;
  }
References v8::internal::wasm::declared_function_index(), v8::internal::wasm::anonymous_namespace{module-compiler.cc}::kTopTier, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::QueueImpl::mutex, and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::QueueImpl::next_steal_task_id.
StealUnitsAndGetFirst()
std::optional<WasmCompilationUnit> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::StealUnitsAndGetFirst (QueueImpl * queue, int steal_from_task_id, int wanted_tier) [inline], [private]
Definition at line 453 of file module-compiler.cc.
                                                                 {
    auto* steal_queue = queues_[steal_from_task_id].get();
    // Cannot steal from own queue.
    if (steal_queue == queue) return {};
    std::vector<WasmCompilationUnit> stolen;
    std::optional<WasmCompilationUnit> returned_unit;
    {
      base::MutexGuard guard(&steal_queue->mutex);
      auto* steal_from_vector = &steal_queue->units[wanted_tier];
      if (steal_from_vector->empty()) return {};
      size_t remaining = steal_from_vector->size() / 2;
      auto steal_begin = steal_from_vector->begin() + remaining;
      returned_unit = *steal_begin;
      stolen.assign(steal_begin + 1, steal_from_vector->end());
      steal_from_vector->erase(steal_begin, steal_from_vector->end());
    }
    base::MutexGuard guard(&queue->mutex);
    auto* target_queue = &queue->units[wanted_tier];
    target_queue->insert(target_queue->end(), stolen.begin(), stolen.end());
    queue->next_steal_task_id = steal_from_task_id + 1;
    return returned_unit;
  }
References v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::QueueImpl::mutex, v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::QueueImpl::next_steal_task_id, and v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::QueueImpl::units.
Member Data Documentation
big_units_queue_
BigUnitsQueue v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::big_units_queue_ [private]
Definition at line 522 of file module-compiler.cc.
kBigUnitsLimit
constexpr size_t v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::kBigUnitsLimit = 4096 [static], [constexpr], [private]
Definition at line 280 of file module-compiler.cc.
next_queue_to_add
std::atomic<int> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::next_queue_to_add {0} [private]
Definition at line 527 of file module-compiler.cc.
num_declared_functions_
const int v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::num_declared_functions_ [private]
Definition at line 520 of file module-compiler.cc.
num_imported_functions_
const int v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::num_imported_functions_ [private]
Definition at line 519 of file module-compiler.cc.
num_priority_units_
std::atomic<size_t> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::num_priority_units_ {0} [private]
Definition at line 525 of file module-compiler.cc.
num_units_
std::atomic<size_t> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::num_units_[CompilationTier::kNumTiers] [private]
Definition at line 524 of file module-compiler.cc.
queues_
std::vector<std::unique_ptr<QueueImpl> > v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::queues_ [private]
Definition at line 517 of file module-compiler.cc.
queues_mutex_
base::Mutex v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::queues_mutex_ [mutable], [private]
Definition at line 516 of file module-compiler.cc.
top_tier_compiled_
std::unique_ptr<std::atomic<bool>[]> v8::internal::wasm::anonymous_namespace{module-compiler.cc}::CompilationUnitQueues::top_tier_compiled_ [private]
Definition at line 526 of file module-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc