v8::internal::wasm::ArrayType Class Reference
#include <struct-types.h>
Public Member Functions
constexpr ArrayType (ValueType rep, bool mutability)
bool operator== (const ArrayType &other) const
ValueType element_type () const
ValueType * element_type_writable_ptr ()
Private Attributes
ValueType rep_
Additional Inherited Members
Detailed Description
Definition at line 324 of file struct-types.h.
Constructor & Destructor Documentation
ArrayType()
constexpr v8::internal::wasm::ArrayType::ArrayType (ValueType rep, bool mutability) [inline], [constexpr]
Definition at line 326 of file struct-types.h.
      : ArrayTypeBase(mutability), rep_(rep) {}
Member Function Documentation
element_type()
ValueType v8::internal::wasm::ArrayType::element_type () const [inline]
Definition at line 333 of file struct-types.h.
{ return rep_; }
References rep_.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_data(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_elem(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_set(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicRMW(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicSet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayCopy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayFill(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayInitSegment(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayInitSegment(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNew(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayNewDefault(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNewFixed(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNewSegment(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayNewSegment(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArraySet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArraySet(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateArrayInitExpr(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseArrayGet(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopPackedArray(), v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition(), v8::internal::compiler::WasmTyper::Reduce(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNew(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewDefault(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewFixed(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayNew(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::ValidArraySubtypeDefinition(), and v8::internal::wasm::WasmModuleBuilder::WriteTo().
element_type_writable_ptr()
ValueType* v8::internal::wasm::ArrayType::element_type_writable_ptr () [inline]
Definition at line 335 of file struct-types.h.
{ return &rep_; }
References rep_.
Referenced by v8::internal::wasm::ModuleDecoderImpl::FinalizeRecgroup().
operator==()
bool v8::internal::wasm::ArrayType::operator== (const ArrayType & other) const [inline]
Definition at line 329 of file struct-types.h.
                                                {
    return rep_ == other.rep_ && mutability_ == other.mutability_;
  }
References v8::internal::wasm::ArrayTypeBase::mutability_, and rep_.
Member Data Documentation
rep_
ValueType v8::internal::wasm::ArrayType::rep_ [private]
Definition at line 338 of file struct-types.h.
Referenced by element_type(), element_type_writable_ptr(), and operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/struct-types.h