v8::internal::wasm::WasmFunctionBuilder Class Reference
#include <wasm-module-builder.h>
Classes
struct DirectCallIndex
Public Member Functions
void SetSignature (const FunctionSig *sig)
void SetSignature (ModuleTypeIndex sig_index)
uint32_t AddLocal (ValueType type)
void EmitByte (uint8_t b)
void EmitI32V (int32_t val)
void EmitI32V (ModuleTypeIndex index)
void EmitU32V (uint32_t val)
void EmitU32V (ModuleTypeIndex index)
void EmitU64V (uint64_t val)
void EmitCode (const uint8_t *code, uint32_t code_size)
void EmitCode (std::initializer_list< const uint8_t > code)
void Emit (WasmOpcode opcode)
void EmitWithPrefix (WasmOpcode opcode)
void EmitGetLocal (uint32_t index)
void EmitSetLocal (uint32_t index)
void EmitTeeLocal (uint32_t index)
void EmitI32Const (int32_t val)
void EmitI64Const (int64_t val)
void EmitF32Const (float val)
void EmitF64Const (double val)
void EmitS128Const (Simd128 val)
void EmitWithU8 (WasmOpcode opcode, const uint8_t immediate)
void EmitWithU8U8 (WasmOpcode opcode, const uint8_t imm1, const uint8_t imm2)
void EmitWithI32V (WasmOpcode opcode, int32_t immediate)
void EmitWithU32V (WasmOpcode opcode, uint32_t immediate)
void EmitWithU32V (WasmOpcode opcode, ModuleTypeIndex index)
void EmitHeapType (HeapType type)
void EmitValueType (ValueType type)
void EmitDirectCallIndex (uint32_t index)
void EmitFromInitializerExpression (const WasmInitExpr &init_expr)
void SetName (base::Vector< const char > name)
void AddAsmWasmOffset (size_t call_position, size_t to_number_position)
void SetAsmFunctionStartPosition (size_t function_position)
void SetCompilationHint (WasmCompilationHintStrategy strategy, WasmCompilationHintTier baseline, WasmCompilationHintTier top_tier)
size_t GetPosition () const
void FixupByte (size_t position, uint8_t value)
void DeleteCodeAfter (size_t position)
void WriteSignature (ZoneBuffer *buffer) const
void WriteBody (ZoneBuffer *buffer) const
void WriteAsmWasmOffsetTable (ZoneBuffer *buffer) const
WasmModuleBuilder * builder () const
uint32_t func_index () const
ModuleTypeIndex sig_index () const
const FunctionSig * signature () const
Private Member Functions
WasmFunctionBuilder (WasmModuleBuilder *builder)
Private Attributes
friend Zone
WasmModuleBuilder * builder_
LocalDeclEncoder locals_
ModuleTypeIndex signature_index_
uint32_t func_index_
ZoneBuffer body_
base::Vector< const char > name_
ZoneVector< uint32_t > i32_temps_
ZoneVector< uint32_t > i64_temps_
ZoneVector< uint32_t > f32_temps_
ZoneVector< uint32_t > f64_temps_
ZoneVector< DirectCallIndex > direct_calls_
ZoneBuffer asm_offsets_
uint32_t last_asm_byte_offset_ = 0
uint32_t last_asm_source_position_ = 0
uint32_t asm_func_start_source_position_ = 0
uint8_t hint_ = kNoCompilationHint
Friends
class WasmModuleBuilder
Detailed Description
Definition at line 168 of file wasm-module-builder.h.
Constructor & Destructor Documentation
WasmFunctionBuilder()
v8::internal::wasm::WasmFunctionBuilder::WasmFunctionBuilder (WasmModuleBuilder * builder) [explicit], [private]
Definition at line 189 of file wasm-module-builder.cc.
    : builder_(builder),
      locals_(builder->zone()),
      signature_index_{0},
      func_index_(static_cast<uint32_t>(builder->functions_.size())),
      body_(builder->zone(), 256),
      i32_temps_(builder->zone()),
      i64_temps_(builder->zone()),
      f32_temps_(builder->zone()),
      f64_temps_(builder->zone()),
      direct_calls_(builder->zone()),
      asm_offsets_(builder->zone(), 8) {}
Member Function Documentation
AddAsmWasmOffset()
void v8::internal::wasm::WasmFunctionBuilder::AddAsmWasmOffset (size_t call_position, size_t to_number_position)
Definition at line 349 of file wasm-module-builder.cc.
                                                                      {
  // We only want to emit one mapping per byte offset.
  DCHECK(asm_offsets_.size() == 0 || body_.size() > last_asm_byte_offset_);
  DCHECK_LE(body_.size(), kMaxUInt32);
  uint32_t byte_offset = static_cast<uint32_t>(body_.size());
  asm_offsets_.write_u32v(byte_offset - last_asm_byte_offset_);
  last_asm_byte_offset_ = byte_offset;
  DCHECK_GE(std::numeric_limits<uint32_t>::max(), call_position);
  uint32_t call_position_u32 = static_cast<uint32_t>(call_position);
  asm_offsets_.write_i32v(call_position_u32 - last_asm_source_position_);
  DCHECK_GE(std::numeric_limits<uint32_t>::max(), to_number_position);
  uint32_t to_number_position_u32 = static_cast<uint32_t>(to_number_position);
  asm_offsets_.write_i32v(to_number_position_u32 - call_position_u32);
  last_asm_source_position_ = to_number_position_u32;
}
References asm_offsets_, body_, v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, v8::internal::kMaxUInt32, last_asm_byte_offset_, last_asm_source_position_, v8::internal::wasm::ZoneBuffer::size(), v8::internal::wasm::ZoneBuffer::write_i32v(), and v8::internal::wasm::ZoneBuffer::write_u32v().
Referenced by v8::internal::wasm::AsmJsParser::Loop(), v8::internal::wasm::AsmJsParser::ValidateCall(), and v8::internal::wasm::AsmJsParser::ValidateFunction().
AddLocal()
uint32_t v8::internal::wasm::WasmFunctionBuilder::AddLocal (ValueType type)
Definition at line 223 of file wasm-module-builder.cc.
                                                     {
  DCHECK(locals_.has_sig());
  return locals_.AddLocals(1, type);
}
References v8::internal::wasm::LocalDeclEncoder::AddLocals(), v8::internal::DCHECK(), v8::internal::wasm::LocalDeclEncoder::has_sig(), locals_, and v8::internal::tracing::type.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BodyGen(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), and v8::internal::wasm::AsmJsParser::ValidateFunction().
builder()
WasmModuleBuilder* v8::internal::wasm::WasmFunctionBuilder::builder () const [inline]
Definition at line 222 of file wasm-module-builder.h.
{ return builder_; }
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec().
DeleteCodeAfter()
void v8::internal::wasm::WasmFunctionBuilder::DeleteCodeAfter (size_t position)
Definition at line 390 of file wasm-module-builder.cc.
                                                         {
  DCHECK_LE(position, body_.size());
  body_.Truncate(position);
}
References body_, DCHECK_LE, v8::internal::wasm::ZoneBuffer::size(), and v8::internal::wasm::ZoneBuffer::Truncate().
Referenced by v8::internal::wasm::AsmJsParser::BitwiseORExpression(), and v8::internal::wasm::AsmJsParser::ValidateHeapAccess().
Emit()
void v8::internal::wasm::WasmFunctionBuilder::Emit (WasmOpcode opcode)
Definition at line 248 of file wasm-module-builder.cc.
                                                {
  DCHECK_LE(opcode, 0xFF);
  body_.write_u8(opcode);
}
References body_, DCHECK_LE, and v8::internal::wasm::ZoneBuffer::write_u8().
Referenced by v8::internal::wasm::AsmJsParser::AdditiveExpression(), v8::internal::wasm::AsmJsParser::AssignmentExpression(), v8::internal::wasm::AsmJsParser::BitwiseANDExpression(), v8::internal::wasm::AsmJsParser::BitwiseORExpression(), v8::internal::wasm::AsmJsParser::BitwiseXORExpression(), v8::internal::wasm::AsmJsParser::ConditionalExpression(), v8::internal::wasm::AsmJsParser::DoStatement(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues(), v8::internal::wasm::AsmJsParser::End(), v8::internal::wasm::AsmJsParser::Expression(), v8::internal::wasm::AsmJsParser::ExpressionStatement(), v8::internal::wasm::AsmJsParser::ForStatement(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), v8::internal::wasm::AsmJsParser::IfStatement(), v8::internal::wasm::AsmJsParser::MultiplicativeExpression(), v8::internal::wasm::AsmJsParser::ReturnStatement(), v8::internal::wasm::AsmJsParser::ShiftExpression(), v8::internal::wasm::AsmJsParser::SwitchStatement(), v8::internal::wasm::AsmJsParser::UnaryExpression(), v8::internal::wasm::AsmJsParser::ValidateCall(), v8::internal::wasm::AsmJsParser::ValidateFloatCoercion(), v8::internal::wasm::AsmJsParser::ValidateFunction(), v8::internal::wasm::AsmJsParser::ValidateHeapAccess(), v8::internal::wasm::AsmJsParser::ValidateModule(), and v8::internal::wasm::AsmJsParser::WhileStatement().
EmitByte()
void v8::internal::wasm::WasmFunctionBuilder::EmitByte (uint8_t b)
Definition at line 202 of file wasm-module-builder.cc.
{ body_.write_u8(val); }
References body_, and v8::internal::wasm::ZoneBuffer::write_u8().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec().
EmitCode() [1/2]
void v8::internal::wasm::WasmFunctionBuilder::EmitCode (const uint8_t * code, uint32_t code_size)
Definition at line 240 of file wasm-module-builder.cc.
                                                                          {
  body_.write(code, code_size);
}
References body_, code, and v8::internal::wasm::ZoneBuffer::write().
Referenced by EmitDirectCallIndex().
EmitCode() [2/2]
void v8::internal::wasm::WasmFunctionBuilder::EmitCode (std::initializer_list< const uint8_t > code)
Definition at line 244 of file wasm-module-builder.cc.
                                                                          {
  body_.write(code.begin(), code.size());
}
References body_, code, and v8::internal::wasm::ZoneBuffer::write().
EmitDirectCallIndex()
void v8::internal::wasm::WasmFunctionBuilder::EmitDirectCallIndex (uint32_t index)
Definition at line 331 of file wasm-module-builder.cc.
                                                            {
  DirectCallIndex call;
  call.offset = body_.size();
  call.direct_index = index;
  direct_calls_.push_back(call);
  uint8_t placeholder_bytes[kMaxVarInt32Size] = {0};
  EmitCode(placeholder_bytes, arraysize(placeholder_bytes));
}
References arraysize, body_, direct_calls_, v8::internal::wasm::WasmFunctionBuilder::DirectCallIndex::direct_index, EmitCode(), v8::internal::index, v8::internal::wasm::kMaxVarInt32Size, v8::internal::wasm::WasmFunctionBuilder::DirectCallIndex::offset, and v8::internal::wasm::ZoneBuffer::size().
Referenced by v8::internal::wasm::AsmJsParser::ValidateCall().
EmitF32Const()
void v8::internal::wasm::WasmFunctionBuilder::EmitF32Const (float val)
Definition at line 321 of file wasm-module-builder.cc.
                                                  {
  body_.write_u8(kExprF32Const);
  body_.write_f32(value);
}
References body_, v8::internal::value, v8::internal::wasm::ZoneBuffer::write_f32(), and v8::internal::wasm::ZoneBuffer::write_u8().
Referenced by v8::internal::wasm::AsmJsParser::ValidateFunctionLocals().
EmitF64Const()
void v8::internal::wasm::WasmFunctionBuilder::EmitF64Const (double val)
Definition at line 326 of file wasm-module-builder.cc.
                                                   {
  body_.write_u8(kExprF64Const);
  body_.write_f64(value);
}
References body_, v8::internal::value, v8::internal::wasm::ZoneBuffer::write_f64(), and v8::internal::wasm::ZoneBuffer::write_u8().
Referenced by v8::internal::wasm::AsmJsParser::NumericLiteral(), v8::internal::wasm::AsmJsParser::UnaryExpression(), and v8::internal::wasm::AsmJsParser::ValidateFunctionLocals().
EmitFromInitializerExpression()
void v8::internal::wasm::WasmFunctionBuilder::EmitFromInitializerExpression (const WasmInitExpr & init_expr)
Definition at line 340 of file wasm-module-builder.cc.
                                   {
  WriteInitializerExpression(&body_, init_expr);
}
References body_, and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpression().
Referenced by v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions().
EmitGetLocal()
void v8::internal::wasm::WasmFunctionBuilder::EmitGetLocal (uint32_t index)
Definition at line 228 of file wasm-module-builder.cc.
                                                           {
  EmitWithU32V(kExprLocalGet, local_index);
}
References EmitWithU32V().
Referenced by v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), v8::internal::wasm::AsmJsParser::Identifier(), v8::internal::wasm::AsmJsParser::SwitchStatement(), v8::internal::wasm::AsmJsParser::UnaryExpression(), and v8::internal::wasm::AsmJsParser::ValidateCall().
EmitHeapType()
void v8::internal::wasm::WasmFunctionBuilder::EmitHeapType (HeapType type)
Definition at line 304 of file wasm-module-builder.cc.
                                                    {
  WriteHeapType(&body_, type);
}
References body_, v8::internal::tracing::type, and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteHeapType().
EmitI32Const()
void v8::internal::wasm::WasmFunctionBuilder::EmitI32Const (int32_t val)
Definition at line 312 of file wasm-module-builder.cc.
                                                    {
  EmitWithI32V(kExprI32Const, value);
}
References EmitWithI32V(), and v8::internal::value.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), v8::internal::wasm::AsmJsParser::MultiplicativeExpression(), v8::internal::wasm::AsmJsParser::NumericLiteral(), v8::internal::wasm::AsmJsParser::SwitchStatement(), v8::internal::wasm::AsmJsParser::UnaryExpression(), v8::internal::wasm::AsmJsParser::ValidateCall(), v8::internal::wasm::AsmJsParser::ValidateFunctionLocals(), and v8::internal::wasm::AsmJsParser::ValidateHeapAccess().
EmitI32V() [1/2]
void v8::internal::wasm::WasmFunctionBuilder::EmitI32V (int32_t val)
Definition at line 204 of file wasm-module-builder.cc.
{ body_.write_i32v(val); }
References body_, and v8::internal::wasm::ZoneBuffer::write_i32v().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues().
EmitI32V() [2/2]
void v8::internal::wasm::WasmFunctionBuilder::EmitI32V (ModuleTypeIndex index) [inline]
Definition at line 177 of file wasm-module-builder.h.
{ EmitI32V(index.index); }
References EmitI32V(), and v8::internal::index.
Referenced by EmitI32V().
EmitI64Const()
void v8::internal::wasm::WasmFunctionBuilder::EmitI64Const (int64_t val)
Definition at line 316 of file wasm-module-builder.cc.
                                                    {
  body_.write_u8(kExprI64Const);
  body_.write_i64v(value);
}
References body_, v8::internal::value, v8::internal::wasm::ZoneBuffer::write_i64v(), and v8::internal::wasm::ZoneBuffer::write_u8().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues().
EmitS128Const()
void v8::internal::wasm::WasmFunctionBuilder::EmitS128Const (Simd128 val)
EmitSetLocal()
void v8::internal::wasm::WasmFunctionBuilder::EmitSetLocal (uint32_t index)
Definition at line 232 of file wasm-module-builder.cc.
                                                           {
  EmitWithU32V(kExprLocalSet, local_index);
}
References EmitWithU32V().
Referenced by v8::internal::wasm::AsmJsParser::SwitchStatement(), v8::internal::wasm::AsmJsParser::UnaryExpression(), v8::internal::wasm::AsmJsParser::ValidateCall(), and v8::internal::wasm::AsmJsParser::ValidateFunctionLocals().
EmitTeeLocal()
void v8::internal::wasm::WasmFunctionBuilder::EmitTeeLocal (uint32_t index)
Definition at line 236 of file wasm-module-builder.cc.
                                                           {
  EmitWithU32V(kExprLocalTee, local_index);
}
References EmitWithU32V().
Referenced by v8::internal::wasm::AsmJsParser::AssignmentExpression(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), and v8::internal::wasm::AsmJsParser::ValidateCall().
EmitU32V() [1/2]
void v8::internal::wasm::WasmFunctionBuilder::EmitU32V (ModuleTypeIndex index) [inline]
Definition at line 180 of file wasm-module-builder.h.
{ EmitU32V(index.index); }
References EmitU32V(), and v8::internal::index.
Referenced by EmitU32V().
EmitU32V() [2/2]
void v8::internal::wasm::WasmFunctionBuilder::EmitU32V (uint32_t val)
Definition at line 206 of file wasm-module-builder.cc.
{ body_.write_u32v(val); }
References body_, and v8::internal::wasm::ZoneBuffer::write_u32v().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), and v8::internal::wasm::AsmJsParser::ValidateCall().
EmitU64V()
void v8::internal::wasm::WasmFunctionBuilder::EmitU64V (uint64_t val)
Definition at line 208 of file wasm-module-builder.cc.
{ body_.write_u64v(val); }
References body_, and v8::internal::wasm::ZoneBuffer::write_u64v().
Referenced by v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec().
EmitValueType()
void v8::internal::wasm::WasmFunctionBuilder::EmitValueType (ValueType type)
Definition at line 308 of file wasm-module-builder.cc.
                                                      {
  WriteValueType(&body_, type);
}
References body_, v8::internal::tracing::type, and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteValueType().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BlockScope::BlockScope().
EmitWithI32V()
void v8::internal::wasm::WasmFunctionBuilder::EmitWithI32V (WasmOpcode opcode, int32_t immediate)
Definition at line 278 of file wasm-module-builder.cc.
                                                                           {
  body_.write_u8(opcode);
  body_.write_i32v(immediate);
}
References body_, v8::internal::wasm::ZoneBuffer::write_i32v(), and v8::internal::wasm::ZoneBuffer::write_u8().
Referenced by EmitI32Const().
EmitWithPrefix()
void v8::internal::wasm::WasmFunctionBuilder::EmitWithPrefix (WasmOpcode opcode)
Definition at line 253 of file wasm-module-builder.cc.
                                                          {
  DCHECK_GT(opcode, 0xFF);
  if (opcode > 0xFFFF) {
    DCHECK_EQ(kSimdPrefix, opcode >> 12);
    body_.write_u8(kSimdPrefix);
    body_.write_u32v(opcode & 0xFFF);
  } else {
    body_.write_u8(opcode >> 8); // Prefix.
    body_.write_u32v(opcode & 0xff); // LEB encoded tail.
  }
}
References body_, DCHECK_EQ, DCHECK_GT, v8::internal::wasm::ZoneBuffer::write_u32v(), and v8::internal::wasm::ZoneBuffer::write_u8().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues(), v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec(), v8::internal::wasm::AsmJsParser::MultiplicativeExpression(), and v8::internal::wasm::AsmJsParser::UnaryExpression().
EmitWithU32V() [1/2]
void v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V (WasmOpcode opcode, ModuleTypeIndex index) [inline]
Definition at line 198 of file wasm-module-builder.h.
                                                              {
    EmitWithU32V(opcode, index.index);
  }
References v8::internal::index.
EmitWithU32V() [2/2]
void v8::internal::wasm::WasmFunctionBuilder::EmitWithU32V (WasmOpcode opcode, uint32_t immediate)
Definition at line 283 of file wasm-module-builder.cc.
                                                                            {
  body_.write_u8(opcode);
  body_.write_u32v(immediate);
}
References body_, v8::internal::wasm::ZoneBuffer::write_u32v(), and v8::internal::wasm::ZoneBuffer::write_u8().
Referenced by v8::internal::wasm::AsmJsParser::AssignmentExpression(), v8::internal::wasm::AsmJsParser::BreakStatement(), v8::internal::wasm::AsmJsParser::ContinueStatement(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues(), EmitGetLocal(), EmitSetLocal(), EmitTeeLocal(), v8::internal::wasm::AsmJsParser::Identifier(), v8::internal::wasm::AsmJsParser::SwitchStatement(), v8::internal::wasm::AsmJsParser::ValidateCall(), v8::internal::wasm::AsmJsParser::ValidateFunctionLocals(), and v8::internal::wasm::AsmJsParser::ValidateModule().
EmitWithU8()
void v8::internal::wasm::WasmFunctionBuilder::EmitWithU8 (WasmOpcode opcode, const uint8_t immediate)
Definition at line 265 of file wasm-module-builder.cc.
                                                              {
  body_.write_u8(opcode);
  body_.write_u8(immediate);
}
References body_, and v8::internal::wasm::ZoneBuffer::write_u8().
Referenced by v8::internal::wasm::AsmJsParser::Begin(), v8::internal::wasm::AsmJsParser::Block(), v8::internal::wasm::AsmJsParser::ConditionalExpression(), v8::internal::wasm::AsmJsParser::DoStatement(), v8::internal::wasm::AsmJsParser::ForStatement(), v8::internal::wasm::AsmJsParser::IfStatement(), v8::internal::wasm::AsmJsParser::Loop(), v8::internal::wasm::AsmJsParser::SwitchStatement(), v8::internal::wasm::AsmJsParser::ValidateCall(), and v8::internal::wasm::AsmJsParser::WhileStatement().
EmitWithU8U8()
void v8::internal::wasm::WasmFunctionBuilder::EmitWithU8U8 (WasmOpcode opcode, const uint8_t imm1, const uint8_t imm2)
Definition at line 271 of file wasm-module-builder.cc.
                                                           {
  body_.write_u8(opcode);
  body_.write_u8(imm1);
  body_.write_u8(imm2);
}
References body_, and v8::internal::wasm::ZoneBuffer::write_u8().
FixupByte()
void v8::internal::wasm::WasmFunctionBuilder::FixupByte (size_t position, uint8_t value) [inline]
Definition at line 213 of file wasm-module-builder.h.
                                                 {
    body_.patch_u8(position, value);
  }
References v8::internal::value.
Referenced by v8::internal::wasm::AsmJsParser::ConditionalExpression().
func_index()
uint32_t v8::internal::wasm::WasmFunctionBuilder::func_index () const [inline]
Definition at line 223 of file wasm-module-builder.h.
{ return func_index_; }
Referenced by v8::internal::wasm::WasmModuleBuilder::AddExport(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), v8::internal::wasm::AsmJsParser::ValidateCall(), and v8::internal::wasm::AsmJsParser::ValidateFunction().
GetPosition()
size_t v8::internal::wasm::WasmFunctionBuilder::GetPosition () const [inline]
Definition at line 212 of file wasm-module-builder.h.
{ return body_.size(); }
Referenced by v8::internal::wasm::AsmJsParser::BitwiseORExpression(), v8::internal::wasm::AsmJsParser::ConditionalExpression(), v8::internal::wasm::AsmJsParser::ShiftExpression(), and v8::internal::wasm::AsmJsParser::ValidateFunction().
SetAsmFunctionStartPosition()
void v8::internal::wasm::WasmFunctionBuilder::SetAsmFunctionStartPosition (size_t function_position)
Definition at line 369 of file wasm-module-builder.cc.
                              {
  DCHECK_EQ(0, asm_func_start_source_position_);
  DCHECK_GE(std::numeric_limits<uint32_t>::max(), function_position);
  uint32_t function_position_u32 = static_cast<uint32_t>(function_position);
  // Must be called before emitting any asm.js source position.
  DCHECK_EQ(0, asm_offsets_.size());
  asm_func_start_source_position_ = function_position_u32;
  last_asm_source_position_ = function_position_u32;
}
References asm_func_start_source_position_, asm_offsets_, DCHECK_EQ, DCHECK_GE, last_asm_source_position_, and v8::internal::wasm::ZoneBuffer::size().
Referenced by v8::internal::wasm::AsmJsParser::ValidateFunction().
SetCompilationHint()
void v8::internal::wasm::WasmFunctionBuilder::SetCompilationHint (WasmCompilationHintStrategy strategy, WasmCompilationHintTier baseline, WasmCompilationHintTier top_tier)
Definition at line 380 of file wasm-module-builder.cc.
                                      {
  uint8_t hint_byte = static_cast<uint8_t>(strategy) |
                      static_cast<uint8_t>(baseline) << 2 |
                      static_cast<uint8_t>(top_tier) << 4;
  DCHECK_NE(hint_byte, kNoCompilationHint);
  hint_ = hint_byte;
}
References DCHECK_NE, hint_, and v8::internal::wasm::kNoCompilationHint.
SetName()
void v8::internal::wasm::WasmFunctionBuilder::SetName (base::Vector< const char > name)
Definition at line 345 of file wasm-module-builder.cc.
                                                             {
  name_ = name;
}
References v8::internal::wasm::name(), and name_.
Referenced by v8::internal::wasm::AsmJsParser::ValidateFunction().
SetSignature() [1/2]
void v8::internal::wasm::WasmFunctionBuilder::SetSignature (const FunctionSig * sig)
Definition at line 210 of file wasm-module-builder.cc.
                                                             {
  DCHECK(!locals_.has_sig());
  locals_.set_sig(sig);
  signature_index_ = builder_->AddSignature(sig, true);
}
References v8::internal::wasm::WasmModuleBuilder::AddSignature(), builder_, v8::internal::DCHECK(), v8::internal::wasm::LocalDeclEncoder::has_sig(), locals_, v8::internal::wasm::LocalDeclEncoder::set_sig(), v8::internal::sig, and signature_index_.
Referenced by v8::internal::wasm::AsmJsParser::ValidateFunction(), and v8::internal::wasm::AsmJsParser::ValidateModule().
SetSignature() [2/2]
void v8::internal::wasm::WasmFunctionBuilder::SetSignature (ModuleTypeIndex sig_index)
Definition at line 216 of file wasm-module-builder.cc.
                                                                {
  DCHECK(!locals_.has_sig());
  DCHECK_EQ(builder_->types_[sig_index.index].kind, TypeDefinition::kFunction);
  signature_index_ = sig_index;
  locals_.set_sig(builder_->types_[sig_index.index].function_sig);
}
References builder_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::LocalDeclEncoder::has_sig(), v8::internal::wasm::TypeIndex::index, v8::internal::wasm::TypeDefinition::kFunction, locals_, v8::internal::wasm::LocalDeclEncoder::set_sig(), sig_index(), signature_index_, and v8::internal::wasm::WasmModuleBuilder::types_.
sig_index()
ModuleTypeIndex v8::internal::wasm::WasmFunctionBuilder::sig_index () const [inline]
Definition at line 224 of file wasm-module-builder.h.
{ return signature_index_; }
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateInitExpr(), and SetSignature().
signature()
const FunctionSig * v8::internal::wasm::WasmFunctionBuilder::signature () const [inline]
Definition at line 563 of file wasm-module-builder.h.
                                                        {
  return builder_->types_[signature_index_.index].function_sig;
}
References builder_, v8::internal::wasm::TypeIndex::index, signature_index_, and v8::internal::wasm::WasmModuleBuilder::types_.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::BodyGen(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitCallAndReturnValues(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::EmitDeoptAndReturnValues(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), and v8::internal::wasm::fuzzing::GenerateWasmModuleForRevec().
WriteAsmWasmOffsetTable()
void v8::internal::wasm::WasmFunctionBuilder::WriteAsmWasmOffsetTable (ZoneBuffer * buffer) const
Definition at line 418 of file wasm-module-builder.cc.
                                                                          {
  if (asm_func_start_source_position_ == 0 && asm_offsets_.size() == 0) {
    buffer->write_size(0);
    return;
  }
  size_t locals_enc_size = LEBHelper::sizeof_u32v(locals_.Size());
  size_t func_start_size =
      LEBHelper::sizeof_u32v(asm_func_start_source_position_);
  buffer->write_size(asm_offsets_.size() + locals_enc_size + func_start_size);
  // Offset of the recorded byte offsets.
  DCHECK_GE(kMaxUInt32, locals_.Size());
  buffer->write_u32v(static_cast<uint32_t>(locals_.Size()));
  // Start position of the function.
  buffer->write_u32v(asm_func_start_source_position_);
  buffer->write(asm_offsets_.begin(), asm_offsets_.size());
}
References asm_func_start_source_position_, asm_offsets_, v8::internal::wasm::ZoneBuffer::begin(), DCHECK_GE, v8::internal::kMaxUInt32, locals_, v8::internal::wasm::LocalDeclEncoder::Size(), v8::internal::wasm::ZoneBuffer::size(), v8::internal::wasm::LEBHelper::sizeof_u32v(), v8::internal::wasm::ZoneBuffer::write(), v8::internal::wasm::ZoneBuffer::write_size(), and v8::internal::wasm::ZoneBuffer::write_u32v().
WriteBody()
void v8::internal::wasm::WasmFunctionBuilder::WriteBody (ZoneBuffer * buffer) const
Definition at line 399 of file wasm-module-builder.cc.
                                                            {
  size_t locals_size = locals_.Size();
  buffer->write_size(locals_size + body_.size());
  buffer->EnsureSpace(locals_size);
  uint8_t** ptr = buffer->pos_ptr();
  locals_.Emit(*ptr);
  (*ptr) += locals_size; // UGLY: manual bump of position pointer
  if (body_.size() > 0) {
    size_t base = buffer->offset();
    buffer->write(body_.begin(), body_.size());
    for (DirectCallIndex call : direct_calls_) {
      buffer->patch_u32v(
          base + call.offset,
          call.direct_index +
              static_cast<uint32_t>(builder_->function_imports_.size()));
    }
  }
}
References v8::internal::wasm::ZoneBuffer::begin(), body_, builder_, direct_calls_, v8::internal::wasm::LocalDeclEncoder::Emit(), v8::internal::wasm::ZoneBuffer::EnsureSpace(), v8::internal::wasm::WasmModuleBuilder::function_imports_, locals_, v8::internal::wasm::ZoneBuffer::offset(), v8::internal::wasm::ZoneBuffer::patch_u32v(), v8::internal::wasm::ZoneBuffer::pos_ptr(), v8::internal::wasm::LocalDeclEncoder::Size(), v8::internal::wasm::ZoneBuffer::size(), v8::internal::wasm::ZoneBuffer::write(), and v8::internal::wasm::ZoneBuffer::write_size().
WriteSignature()
void v8::internal::wasm::WasmFunctionBuilder::WriteSignature (ZoneBuffer * buffer) const
Definition at line 395 of file wasm-module-builder.cc.
                                                                 {
  buffer->write_u32v(signature_index_);
}
References signature_index_, and v8::internal::wasm::ZoneBuffer::write_u32v().
Friends And Related Function Documentation
WasmModuleBuilder
friend class WasmModuleBuilder [friend]
Definition at line 229 of file wasm-module-builder.h.
Member Data Documentation
asm_func_start_source_position_
uint32_t v8::internal::wasm::WasmFunctionBuilder::asm_func_start_source_position_ = 0 [private]
Definition at line 253 of file wasm-module-builder.h.
Referenced by SetAsmFunctionStartPosition(), and WriteAsmWasmOffsetTable().
asm_offsets_
ZoneBuffer v8::internal::wasm::WasmFunctionBuilder::asm_offsets_ [private]
Definition at line 250 of file wasm-module-builder.h.
Referenced by AddAsmWasmOffset(), SetAsmFunctionStartPosition(), and WriteAsmWasmOffsetTable().
body_
ZoneBuffer v8::internal::wasm::WasmFunctionBuilder::body_ [private]
Definition at line 241 of file wasm-module-builder.h.
Referenced by AddAsmWasmOffset(), DeleteCodeAfter(), Emit(), EmitByte(), EmitCode(), EmitDirectCallIndex(), EmitF32Const(), EmitF64Const(), EmitFromInitializerExpression(), EmitHeapType(), EmitI32V(), EmitI64Const(), EmitU32V(), EmitU64V(), EmitValueType(), EmitWithI32V(), EmitWithPrefix(), EmitWithU32V(), EmitWithU8(), EmitWithU8U8(), and WriteBody().
builder_
WasmModuleBuilder* v8::internal::wasm::WasmFunctionBuilder::builder_ [private]
Definition at line 237 of file wasm-module-builder.h.
Referenced by SetSignature(), signature(), and WriteBody().
direct_calls_
ZoneVector<DirectCallIndex> v8::internal::wasm::WasmFunctionBuilder::direct_calls_ [private]
Definition at line 247 of file wasm-module-builder.h.
Referenced by EmitDirectCallIndex(), and WriteBody().
f32_temps_
ZoneVector<uint32_t> v8::internal::wasm::WasmFunctionBuilder::f32_temps_ [private]
Definition at line 245 of file wasm-module-builder.h.
f64_temps_
ZoneVector<uint32_t> v8::internal::wasm::WasmFunctionBuilder::f64_temps_ [private]
Definition at line 246 of file wasm-module-builder.h.
func_index_
uint32_t v8::internal::wasm::WasmFunctionBuilder::func_index_ [private]
Definition at line 240 of file wasm-module-builder.h.
hint_
uint8_t v8::internal::wasm::WasmFunctionBuilder::hint_ = kNoCompilationHint [private]
Definition at line 254 of file wasm-module-builder.h.
Referenced by SetCompilationHint().
i32_temps_
ZoneVector<uint32_t> v8::internal::wasm::WasmFunctionBuilder::i32_temps_ [private]
Definition at line 243 of file wasm-module-builder.h.
i64_temps_
ZoneVector<uint32_t> v8::internal::wasm::WasmFunctionBuilder::i64_temps_ [private]
Definition at line 244 of file wasm-module-builder.h.
last_asm_byte_offset_
uint32_t v8::internal::wasm::WasmFunctionBuilder::last_asm_byte_offset_ = 0 [private]
Definition at line 251 of file wasm-module-builder.h.
Referenced by AddAsmWasmOffset().
last_asm_source_position_
uint32_t v8::internal::wasm::WasmFunctionBuilder::last_asm_source_position_ = 0 [private]
Definition at line 252 of file wasm-module-builder.h.
Referenced by AddAsmWasmOffset(), and SetAsmFunctionStartPosition().
locals_
LocalDeclEncoder v8::internal::wasm::WasmFunctionBuilder::locals_ [private]
Definition at line 238 of file wasm-module-builder.h.
Referenced by AddLocal(), SetSignature(), WriteAsmWasmOffsetTable(), and WriteBody().
name_
base::Vector<const char> v8::internal::wasm::WasmFunctionBuilder::name_ [private]
Definition at line 242 of file wasm-module-builder.h.
Referenced by SetName().
signature_index_
ModuleTypeIndex v8::internal::wasm::WasmFunctionBuilder::signature_index_ [private]
Definition at line 239 of file wasm-module-builder.h.
Referenced by SetSignature(), signature(), and WriteSignature().
Zone
friend v8::internal::wasm::WasmFunctionBuilder::Zone [private]
Definition at line 230 of file wasm-module-builder.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-module-builder.h
/mnt/V8SourceCode/src/wasm/wasm-module-builder.cc