v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr > Class Template Reference
#include <scope-info-inl.h>
Classes
class Iterator
Public Member Functions
bool inlined () const
InternalIndex max_index () const
LocalNamesRange (ScopeInfoPtr scope_info)
Iterator begin () const
Iterator end () const
Private Attributes
ScopeInfoPtr scope_info_
Detailed Description
template<typename ScopeInfoPtr>
class v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >
Definition at line 53 of file scope-info-inl.h.
Constructor & Destructor Documentation
LocalNamesRange()
template<typename ScopeInfoPtr >
v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::LocalNamesRange (ScopeInfoPtr scope_info) [inline], [explicit]
Definition at line 134 of file scope-info-inl.h.
: scope_info_(scope_info) {}
Member Function Documentation
begin()
template<typename ScopeInfoPtr >
Iterator v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::begin () const [inline]
Definition at line 136 of file scope-info-inl.h.
{ return Iterator(this, InternalIndex(0)); }
end()
template<typename ScopeInfoPtr >
Iterator v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::end () const [inline]
Definition at line 138 of file scope-info-inl.h.
{ return Iterator(this, max_index()); }
References v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::max_index().
inlined()
template<typename ScopeInfoPtr >
bool v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::inlined () const [inline]
Definition at line 125 of file scope-info-inl.h.
{ return scope_info_->HasInlinedLocalNames(); }
References v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::scope_info_.
Referenced by v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::index(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::Iterator(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::max_index(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::name(), and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::operator++().
max_index()
template<typename ScopeInfoPtr >
InternalIndex v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::max_index () const [inline]
Definition at line 127 of file scope-info-inl.h.
                                  {
    int max = inlined()
                  ? scope_info_->ContextLocalCount()
                  : scope_info_->context_local_names_hashtable()->Capacity();
    return InternalIndex(max);
  }
References v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::inlined(), and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::scope_info_.
Referenced by v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::advance_hashtable_index(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::end(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::name(), and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::operator++().
Member Data Documentation
scope_info_
template<typename ScopeInfoPtr >
ScopeInfoPtr v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::scope_info_ [private]
Definition at line 141 of file scope-info-inl.h.
Referenced by v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::inlined(), v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::max_index(), and v8::internal::ScopeInfo::LocalNamesRange< ScopeInfoPtr >::Iterator::scope_info().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/scope-info-inl.h