v8::internal::MaglevSafepointTableBuilder Class Reference
#include <maglev-safepoint-table.h>
Classes
struct EntryBuilder
class Safepoint
Public Member Functions
MaglevSafepointTableBuilder (Zone *zone, uint32_t num_tagged_slots)
MaglevSafepointTableBuilder (const MaglevSafepointTableBuilder &)=delete
MaglevSafepointTableBuilder & operator= (const MaglevSafepointTableBuilder &)=delete
Safepoint DefineSafepoint (Assembler *assembler)
V8_EXPORT_PRIVATE void Emit (Assembler *assembler, int stack_slots)
int UpdateDeoptimizationInfo (int pc, int trampoline, int start, int deopt_index)
Private Attributes
const uint32_t num_tagged_slots_
ZoneChunkList< EntryBuilder > entries_
Additional Inherited Members
Detailed Description
Definition at line 185 of file maglev-safepoint-table.h.
Constructor & Destructor Documentation
MaglevSafepointTableBuilder() [1/2]
v8::internal::MaglevSafepointTableBuilder::MaglevSafepointTableBuilder (Zone * zone, uint32_t num_tagged_slots) [inline], [explicit]
Definition at line 197 of file maglev-safepoint-table.h.
       :
  explicit MaglevSafepointTableBuilder(Zone* zone, uint32_t num_tagged_slots)
MaglevSafepointTableBuilder() [2/2]
v8::internal::MaglevSafepointTableBuilder::MaglevSafepointTableBuilder (const MaglevSafepointTableBuilder &) [delete]
Member Function Documentation
DefineSafepoint()
MaglevSafepointTableBuilder::Safepoint v8::internal::MaglevSafepointTableBuilder::DefineSafepoint (Assembler * assembler)
Definition at line 124 of file maglev-safepoint-table.cc.
                                                                 {
  entries_.push_back(EntryBuilder(assembler->pc_offset_for_safepoint()));
  return MaglevSafepointTableBuilder::Safepoint(&entries_.back());
}
References entries_, and v8::internal::Assembler::pc_offset_for_safepoint().
Referenced by v8::internal::maglev::MaglevAssembler::DefineLazyDeoptPoint(), and v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint().
Emit()
void v8::internal::MaglevSafepointTableBuilder::Emit (Assembler * assembler, int stack_slots)
Definition at line 145 of file maglev-safepoint-table.cc.
                                                                            {
#ifdef DEBUG
  int last_pc = -1;
  int last_trampoline = -1;
  for (const EntryBuilder& entry : entries_) {
    // Entries are ordered by PC.
    DCHECK_LT(last_pc, entry.pc);
    last_pc = entry.pc;
    // Trampoline PCs are increasing, and larger than regular PCs.
    if (entry.trampoline != MaglevSafepointEntry::kNoTrampolinePC) {
      DCHECK_LT(last_trampoline, entry.trampoline);
      DCHECK_LT(entries_.back().pc, entry.trampoline);
      last_trampoline = entry.trampoline;
    }
    // An entry either has trampoline and deopt index, or none of the two.
    DCHECK_EQ(entry.trampoline == MaglevSafepointEntry::kNoTrampolinePC,
              entry.deopt_index == MaglevSafepointEntry::kNoDeoptIndex);
  }
#endif // DEBUG
#if V8_TARGET_ARCH_ARM || V8_TARGET_ARCH_ARM64
  // We cannot emit a const pool within the safepoint table.
  Assembler::BlockConstPoolScope block_const_pool(assembler);
#endif
  // Make sure the safepoint table is properly aligned. Pad with nops.
  assembler->Align(InstructionStream::kMetadataAlignment);
  assembler->RecordComment(";;; Maglev safepoint table.");
  set_safepoint_table_offset(assembler->pc_offset());
  // Compute the required sizes of the fields.
  int used_register_indexes = 0;
  static_assert(MaglevSafepointEntry::kNoTrampolinePC == -1);
  int max_pc = MaglevSafepointEntry::kNoTrampolinePC;
  static_assert(MaglevSafepointEntry::kNoDeoptIndex == -1);
  int max_deopt_index = MaglevSafepointEntry::kNoDeoptIndex;
  for (const EntryBuilder& entry : entries_) {
    used_register_indexes |= entry.tagged_register_indexes;
    max_pc = std::max(max_pc, std::max(entry.pc, entry.trampoline));
    max_deopt_index = std::max(max_deopt_index, entry.deopt_index);
  }
  // Derive the bytes and bools for the entry configuration from the values.
  auto value_to_bytes = [](int value) {
    DCHECK_LE(0, value);
    if (value == 0) return 0;
    if (value <= 0xff) return 1;
    if (value <= 0xffff) return 2;
    if (value <= 0xffffff) return 3;
    return 4;
  };
  bool has_deopt_data = max_deopt_index != -1;
  int register_indexes_size = value_to_bytes(used_register_indexes);
  // Add 1 so all values (including kNoDeoptIndex and kNoTrampolinePC) are
  // non-negative.
  static_assert(MaglevSafepointEntry::kNoDeoptIndex == -1);
  static_assert(MaglevSafepointEntry::kNoTrampolinePC == -1);
  int pc_size = value_to_bytes(max_pc + 1);
  int deopt_index_size = value_to_bytes(max_deopt_index + 1);
  // Add a CHECK to ensure we never overflow the space in the bitfield, even for
  // huge functions which might not be covered by tests.
  CHECK(MaglevSafepointTable::RegisterIndexesSizeField::is_valid(
      register_indexes_size));
  CHECK(MaglevSafepointTable::PcSizeField::is_valid(pc_size));
  CHECK(MaglevSafepointTable::DeoptIndexSizeField::is_valid(deopt_index_size));
  uint32_t entry_configuration =
      MaglevSafepointTable::HasDeoptDataField::encode(has_deopt_data) |
      MaglevSafepointTable::RegisterIndexesSizeField::encode(
          register_indexes_size) |
      MaglevSafepointTable::PcSizeField::encode(pc_size) |
      MaglevSafepointTable::DeoptIndexSizeField::encode(deopt_index_size);
  // Emit the table header.
  static_assert(MaglevSafepointTable::kStackSlotsOffset == 0 * kIntSize);
  static_assert(MaglevSafepointTable::kLengthOffset == 1 * kIntSize);
  static_assert(MaglevSafepointTable::kEntryConfigurationOffset ==
                2 * kIntSize);
  static_assert(MaglevSafepointTable::kNumTaggedSlotsOffset == 3 * kIntSize);
  static_assert(MaglevSafepointTable::kHeaderSize == 4 * kIntSize);
  int length = static_cast<int>(entries_.size());
  assembler->dd(stack_slots);
  assembler->dd(length);
  assembler->dd(entry_configuration);
  assembler->dd(num_tagged_slots_);
  auto emit_bytes = [assembler](int value, int bytes) {
    DCHECK_LE(0, value);
    for (; bytes > 0; --bytes, value >>= 8) assembler->db(value);
    DCHECK_EQ(0, value);
  };
  // Emit entries, sorted by pc offsets.
  for (const EntryBuilder& entry : entries_) {
    emit_bytes(entry.pc, pc_size);
    if (has_deopt_data) {
      // Add 1 so all values (including kNoDeoptIndex and kNoTrampolinePC) are
      // non-negative.
      static_assert(MaglevSafepointEntry::kNoDeoptIndex == -1);
      static_assert(MaglevSafepointEntry::kNoTrampolinePC == -1);
      emit_bytes(entry.deopt_index + 1, deopt_index_size);
      emit_bytes(entry.trampoline + 1, pc_size);
    }
    assembler->db(entry.num_extra_spill_slots);
    emit_bytes(entry.tagged_register_indexes, register_indexes_size);
  }
}
References v8::internal::Assembler::Align(), CHECK, v8::internal::Assembler::db(), DCHECK_EQ, DCHECK_LE, DCHECK_LT, v8::internal::Assembler::dd(), v8::base::BitField< T, shift, size, U >::encode(), entries_, v8::base::BitField< T, shift, size, U >::is_valid(), v8::internal::kIntSize, v8::internal::InstructionStream::kMetadataAlignment, v8::internal::MaglevSafepointEntry::kNoDeoptIndex, v8::internal::MaglevSafepointEntry::kNoTrampolinePC, v8::internal::length, num_tagged_slots_, v8::internal::AssemblerBase::pc_offset(), v8::internal::AssemblerBase::RecordComment(), v8::internal::SafepointTableBuilderBase::set_safepoint_table_offset(), and v8::internal::value.
Referenced by v8::internal::maglev::MaglevCodeGenerator::EmitMetadata().
operator=()
MaglevSafepointTableBuilder& v8::internal::MaglevSafepointTableBuilder::operator= (const MaglevSafepointTableBuilder &) [delete]
UpdateDeoptimizationInfo()
int v8::internal::MaglevSafepointTableBuilder::UpdateDeoptimizationInfo (int pc, int trampoline, int start, int deopt_index)
Definition at line 129 of file maglev-safepoint-table.cc.
                                                                           {
  DCHECK_NE(MaglevSafepointEntry::kNoTrampolinePC, trampoline);
  DCHECK_NE(MaglevSafepointEntry::kNoDeoptIndex, deopt_index);
  auto it = entries_.Find(start);
  DCHECK(std::any_of(it, entries_.end(),
                     [pc](auto& entry) { return entry.pc == pc; }));
  int index = start;
  while (it->pc != pc) ++it, ++index;
  it->trampoline = trampoline;
  it->deopt_index = deopt_index;
  return index;
}
References v8::base::any_of(), v8::internal::DCHECK(), DCHECK_NE, entries_, v8::internal::index, v8::internal::MaglevSafepointEntry::kNoDeoptIndex, and v8::internal::MaglevSafepointEntry::kNoTrampolinePC.
Referenced by v8::internal::maglev::MaglevCodeGenerator::EmitDeopts().
Member Data Documentation
entries_
ZoneChunkList<EntryBuilder> v8::internal::MaglevSafepointTableBuilder::entries_ [private]
Definition at line 236 of file maglev-safepoint-table.h.
Referenced by DefineSafepoint(), Emit(), and UpdateDeoptimizationInfo().
num_tagged_slots_
const uint32_t v8::internal::MaglevSafepointTableBuilder::num_tagged_slots_ [private]
Definition at line 235 of file maglev-safepoint-table.h.
Referenced by Emit().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/maglev-safepoint-table.h
/mnt/V8SourceCode/src/codegen/maglev-safepoint-table.cc