v8::internal::compiler::CreateArrayParameters Class Reference
#include <js-operator.h>
Public Member Functions
CreateArrayParameters (size_t arity, OptionalAllocationSiteRef site, const FeedbackSource &feedback)
size_t arity () const
OptionalAllocationSiteRef site () const
const FeedbackSource & call_feedback () const
Private Attributes
size_t const arity_
OptionalAllocationSiteRef const site_
FeedbackSource const feedback_
Friends
bool operator== (CreateArrayParameters const &, CreateArrayParameters const &)
bool operator!= (CreateArrayParameters const &, CreateArrayParameters const &)
size_t hash_value (CreateArrayParameters const &)
std::ostream & operator<< (std::ostream &, CreateArrayParameters const &)
Detailed Description
Definition at line 565 of file js-operator.h.
Constructor & Destructor Documentation
CreateArrayParameters()
v8::internal::compiler::CreateArrayParameters::CreateArrayParameters (size_t arity, OptionalAllocationSiteRef site, const FeedbackSource & feedback) [inline]
Definition at line 567 of file js-operator.h.
      : arity_(arity), site_(site), feedback_(feedback) {}
Member Function Documentation
arity()
size_t v8::internal::compiler::CreateArrayParameters::arity () const [inline]
Definition at line 571 of file js-operator.h.
{ return arity_; }
References arity_.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray().
call_feedback()
const FeedbackSource& v8::internal::compiler::CreateArrayParameters::call_feedback () const [inline]
Definition at line 573 of file js-operator.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray().
site()
OptionalAllocationSiteRef v8::internal::compiler::CreateArrayParameters::site () const [inline]
Definition at line 572 of file js-operator.h.
{ return site_; }
References site_.
Referenced by v8::internal::compiler::JSCreateLowering::ReduceJSCreateArray().
Friends And Related Function Documentation
hash_value
size_t hash_value (CreateArrayParameters const & p) [friend]
Definition at line 421 of file js-operator.cc.
                                                  {
  return base::hash_combine(p.arity(), AddressOrNull(p.site_),
                            FeedbackSource::Hash()(p.feedback_));
}
operator!=
bool operator!= (CreateArrayParameters const & lhs, CreateArrayParameters const & rhs) [friend]
Definition at line 415 of file js-operator.cc.
                                                  {
  return !(lhs == rhs);
}
operator<<
std::ostream& operator<< (std::ostream & os, CreateArrayParameters const & p) [friend]
Definition at line 427 of file js-operator.cc.
                                                                       {
  os << p.arity();
  if (p.site_.has_value()) {
    os << ", " << Brief(*p.site_->object());
  }
  os << ", " << p.call_feedback();
  return os;
}
operator==
bool operator== (CreateArrayParameters const & lhs, CreateArrayParameters const & rhs) [friend]
Definition at line 407 of file js-operator.cc.
                                                  {
  return lhs.arity() == rhs.arity() &&
         AddressOrNull(lhs.site_) == AddressOrNull(rhs.site_) &&
         lhs.call_feedback() == rhs.call_feedback();
}
Member Data Documentation
arity_
size_t const v8::internal::compiler::CreateArrayParameters::arity_ [private]
Definition at line 576 of file js-operator.h.
Referenced by arity().
feedback_
FeedbackSource const v8::internal::compiler::CreateArrayParameters::feedback_ [private]
Definition at line 578 of file js-operator.h.
Referenced by call_feedback().
site_
OptionalAllocationSiteRef const v8::internal::compiler::CreateArrayParameters::site_ [private]
Definition at line 577 of file js-operator.h.
Referenced by site().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h