v8::internal::Zone Class Reference
#include <zone.h>
Public Member Functions
Zone (AccountingAllocator *allocator, const char *name)
~Zone ()
template<typename TypeTag >
void * Allocate (size_t size)
template<typename TypeTag = void>
void Delete (void *pointer, size_t size)
template<typename T , typename... Args>
T * New (Args &&... args)
template<typename T , typename TypeTag = T[]>
T * AllocateArray (size_t length)
template<typename T , typename TypeTag = T[]>
base::Vector< T > AllocateVector (size_t length)
template<typename T , typename TypeTag = T[]>
base::Vector< T > NewVector (size_t length)
template<typename T , typename TypeTag = T[]>
base::Vector< T > NewVector (size_t length, T value)
template<typename T , typename TypeTag = std::remove_const_t<T>[]>
base::Vector< std::remove_const_t< T > > CloneVector (base::Vector< T > v)
template<typename T , typename TypeTag = T[]>
void DeleteArray (T *pointer, size_t length)
void Seal ()
void Reset ()
size_t segment_bytes_allocated () const
const char * name () const
size_t allocation_size () const
size_t allocation_size_for_tracing () const
size_t freed_size_for_tracing () const
AccountingAllocator * allocator () const
V8_WARN_UNUSED_RESULT ZoneSnapshot Snapshot () const
Private Member Functions
void * AsanNew (size_t size)
void DeleteAll ()
void ReleaseSegment (Segment *segment)
V8_NOINLINE V8_PRESERVE_MOST void Expand (size_t size)
Private Attributes
std::atomic< size_t > allocation_size_ = {0}
std::atomic< size_t > segment_bytes_allocated_ = {0}
Address position_ = 0
Address limit_ = 0
AccountingAllocator * allocator_
Segment * segment_head_ = nullptr
const char * name_
bool sealed_ = false
Static Private Attributes
static const size_t kAlignmentInBytes = 8
static const size_t kMinimumSegmentSize = 8 * KB
static const size_t kMaximumSegmentSize = 32 * KB
Friends
class ZoneSnapshot
Detailed Description
Definition at line 43 of file zone.h.
Constructor & Destructor Documentation
Zone()
v8::internal::Zone::Zone (AccountingAllocator * allocator, const char * name)
Definition at line 32 of file zone.cc.
    : allocator_(allocator), name_(name) {
  allocator_->TraceZoneCreation(this);
}
References allocator_, and v8::internal::AccountingAllocator::TraceZoneCreation().
 Zone()
v8::internal::Zone::~Zone ()
Definition at line 37 of file zone.cc.
            {
  DeleteAll();
  DCHECK_EQ(segment_bytes_allocated_.load(), 0);
}
References DCHECK_EQ, DeleteAll(), and segment_bytes_allocated_.
Member Function Documentation
Allocate()
template<typename TypeTag >
void* v8::internal::Zone::Allocate (size_t size) [inline]
Definition at line 55 of file zone.h.
                              {
#ifdef V8_USE_ADDRESS_SANITIZER
    return AsanNew(size);
#else
    size = RoundUp(size, kAlignmentInBytes);
#ifdef V8_ENABLE_PRECISE_ZONE_STATS
    if (V8_UNLIKELY(TracingFlags::is_zone_stats_enabled())) {
      type_stats_.AddAllocated<TypeTag>(size);
    }
    allocation_size_for_tracing_ += size;
#endif
    if (V8_UNLIKELY(size > limit_ - position_)) {
      Expand(size);
    }
    DCHECK_LE(position_, limit_);
    DCHECK_LE(size, limit_ - position_);
    DCHECK_EQ(0, position_ % kAlignmentInBytes);
    void* result = reinterpret_cast<void*>(position_);
    position_ += size;
    return result;
#endif // V8_USE_ADDRESS_SANITIZER
  }
References DCHECK_EQ, DCHECK_LE, v8::internal::TracingFlags::is_zone_stats_enabled(), v8::base::internal::result, RoundUp(), size(), and V8_UNLIKELY.
Referenced by v8::internal::maglev::NodeBase::Allocate(), v8::internal::compiler::Instruction::New(), v8::internal::compiler::Node::OutOfLineInputs::New(), v8::internal::ZoneChunkList< T >::NewChunk(), v8::internal::compiler::Node::NewImpl(), and v8::internal::SignatureBuilder< SigT, T >::SignatureBuilder().
AllocateArray()
template<typename T , typename TypeTag = T[]>
T* v8::internal::Zone::AllocateArray (size_t length) [inline]
Definition at line 121 of file zone.h.
                                  {
    static_assert(alignof(T) <= kAlignmentInBytes);
    // Defense-in-depth: ensure that the multiplication does not overflow as
    // that would result in a too-small allocation and (likely) memory
    // corruption afterwards.
    CHECK_LT(length, std::numeric_limits<size_t>::max() / sizeof(T));
    return static_cast<T*>(Allocate<TypeTag>(length * sizeof(T)));
  }
References CHECK_LT, and v8::internal::length.
Referenced by v8::internal::ZoneAllocator< T >::allocate(), v8::internal::ZoneAllocationPolicy::AllocateArray(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::AllocatePhiInputs(), v8::internal::BitVector::BitVector(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BlockPhis::BlockPhis(), v8::internal::compiler::fast_api_call::FastApiCallBuilder::Build(), v8::internal::compiler::CFGBuilder::BuildBlocksForSuccessors(), v8::internal::maglev::VirtualObject::Clone(), v8::internal::CloneVector(), v8::internal::compiler::RawMachineAssembler::Comment(), v8::internal::compiler::InstructionSequence::ComputeAssemblyOrder(), v8::internal::compiler::CFGBuilder::ConnectSwitch(), v8::internal::wasm::ModuleDecoderImpl::consume_sig(), v8::internal::wasm::ModuleDecoderImpl::consume_struct(), v8::internal::Scanner::CurrentLiteralAsCString(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::DecodeLocals(), v8::internal::wasm::ZoneBuffer::EnsureSpace(), v8::internal::PreparseDataBuilder::ByteData::Finalize(), v8::internal::compiler::GetDebugName(), v8::internal::compiler::CallDescriptor::GetMachineSignature(), v8::internal::compiler::SpillPlacer::GetOrCreateIndexForLatestVreg(), v8::internal::compiler::turboshaft::OperationBuffer::Grow(), v8::internal::ZoneVector< T >::Grow(), v8::internal::compiler::DoubleEndedSplitVector< T >::GrowAt(), v8::internal::maglev::DeoptInfo::InitializeInputLocations(), v8::internal::compiler::JSInliningHeuristic::InlineCandidate(), v8::internal::compiler::InstructionSequence::InstructionBlocksFor(), v8::internal::compiler::turboshaft::TupleType::LeastUpperBound(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::MostlySmallValueKindSig::MakeKinds(), v8::internal::maglev::MergePointInterpreterFrameState::New(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), v8::internal::ZoneCompactSet< T >::NewList(), v8::internal::compiler::turboshaft::OperationBuffer::OperationBuffer(), v8::internal::ZoneVector< T >::operator=(), v8::internal::compiler::RawMachineAssembler::Phi(), v8::internal::ZoneVector< T >::PrepareForInsertion(), v8::internal::wasm::LocalDeclEncoder::Prepend(), v8::internal::compiler::DeadCodeElimination::ReduceBranchOrSwitch(), v8::internal::compiler::JSCallReducer::ReduceFunctionPrototypeBind(), v8::internal::compiler::CommonOperatorReducer::ReduceSwitch(), v8::internal::compiler::RegisterAllocatorVerifier::RegisterAllocatorVerifier(), v8::internal::maglev::RegisterFrameArray< T >::RegisterFrameArray(), v8::internal::ZoneList< T >::Resize(), v8::internal::BitVector::Resize(), v8::internal::compiler::LoopFinderImpl::ResizeBackwardMarks(), v8::internal::compiler::LoopFinderImpl::ResizeForwardMarks(), v8::internal::compiler::turboshaft::FloatType< Bits >::Set(), v8::internal::compiler::turboshaft::WordType< Bits >::Set(), v8::internal::compiler::WasmGraphBuilder::Start(), v8::internal::compiler::StructuralType::StructuralType(), v8::internal::compiler::CodeAssembler::Switch(), v8::internal::compiler::RawMachineAssembler::Switch(), v8::internal::compiler::turboshaft::TupleType::Tuple(), v8::internal::compiler::UnrollLoop(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::WasmIntoJSInlinerImpl(), v8::internal::ZoneList< T >::ZoneList(), and v8::internal::ZoneVector< T >::ZoneVector().
AllocateVector()
template<typename T , typename TypeTag = T[]>
base::Vector<T> v8::internal::Zone::AllocateVector (size_t length) [inline]
Definition at line 132 of file zone.h.
                                              {
    T* new_array = AllocateArray<T, TypeTag>(length);
    return {new_array, length};
  }
References v8::internal::length.
Referenced by v8::internal::compiler::turboshaft::Graph::AllocateNewBlocks(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), v8::internal::wasm::InliningTree::Inline(), and v8::internal::maglev::LiveRangeAndNextUseProcessor::MarkInputUses().
allocation_size()
size_t v8::internal::Zone::allocation_size () const [inline]
Definition at line 185 of file zone.h.
                                 {
    size_t extra = segment_head_ ? position_ - segment_head_->start() : 0;
    return allocation_size_ + extra;
  }
Referenced by DeleteAll(), v8::internal::wasm::ExecuteLiftoffCompilation(), Expand(), v8::internal::compiler::ZoneStats::StatsScope::GetCurrentAllocatedBytes(), v8::internal::compiler::PipelineStatisticsBase::OuterZoneSize(), Reset(), v8::internal::compiler::ZoneStats::ReturnZone(), and v8::internal::compiler::ZoneStats::StatsScope::StatsScope().
allocation_size_for_tracing()
size_t v8::internal::Zone::allocation_size_for_tracing () const [inline]
Definition at line 193 of file zone.h.
                                             {
#ifdef V8_ENABLE_PRECISE_ZONE_STATS
    return allocation_size_for_tracing_;
#else
    return allocation_size_;
#endif
  }
Referenced by v8::internal::wasm::WasmModule::EstimateStoredSize().
allocator()
AccountingAllocator* v8::internal::Zone::allocator () const [inline]
Definition at line 212 of file zone.h.
{ return allocator_; }
Referenced by v8::internal::compiler::ScheduleVerifier::Run().
AsanNew()
void * v8::internal::Zone::AsanNew (size_t size) [private]
Definition at line 42 of file zone.cc.
                               {
  CHECK(!sealed_);
  // Round up the requested size to fit the alignment.
  size = RoundUp(size, kAlignmentInBytes);
  // Check if the requested size is available without expanding.
  const size_t size_with_redzone = size + kASanRedzoneBytes;
  DCHECK_LE(position_, limit_);
  if (V8_UNLIKELY(size_with_redzone > limit_ - position_)) {
    Expand(size_with_redzone);
  }
  DCHECK_LE(size_with_redzone, limit_ - position_);
  Address result = position_;
  position_ += size_with_redzone;
  Address redzone_position = result + size;
  DCHECK_EQ(redzone_position + kASanRedzoneBytes, position_);
  ASAN_POISON_MEMORY_REGION(reinterpret_cast<void*>(redzone_position),
                            kASanRedzoneBytes);
  // Check that the result has the proper alignment and return it.
  DCHECK(IsAligned(result, kAlignmentInBytes));
  return reinterpret_cast<void*>(result);
}
References ASAN_POISON_MEMORY_REGION, CHECK, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, Expand(), IsAligned(), kAlignmentInBytes, v8::internal::anonymous_namespace{zone.cc}::kASanRedzoneBytes, limit_, position_, v8::base::internal::result, RoundUp(), sealed_, size(), and V8_UNLIKELY.
CloneVector()
template<typename T , typename TypeTag = std::remove_const_t<T>[]>
base::Vector<std::remove_const_t<T> > v8::internal::Zone::CloneVector (base::Vector< T > v) [inline]
Definition at line 155 of file zone.h.
                                                                {
    auto* new_array = AllocateArray<std::remove_const_t<T>, TypeTag>(v.size());
    std::uninitialized_copy(v.begin(), v.end(), new_array);
    return {new_array, v.size()};
  }
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::end(), and v8::base::Vector< T >::size().
Referenced by v8::internal::compiler::turboshaft::FrameStateData::Builder::AllocateFrameStateData(), and v8::internal::wasm::AsmJsParser::CopyCurrentIdentifierString().
Delete()
template<typename TypeTag = void>
void v8::internal::Zone::Delete (void * pointer, size_t size) [inline]
Definition at line 85 of file zone.h.
                                          {
    DCHECK_NOT_NULL(pointer);
    DCHECK_NE(size, 0);
    size = RoundUp(size, kAlignmentInBytes);
#ifdef V8_ENABLE_PRECISE_ZONE_STATS
    if (V8_UNLIKELY(TracingFlags::is_zone_stats_enabled())) {
      type_stats_.AddDeallocated<TypeTag>(size);
    }
    freed_size_for_tracing_ += size;
#endif
#ifdef DEBUG
    static const unsigned char kZapDeadByte = 0xcd;
    memset(pointer, kZapDeadByte, size);
#endif
  }
References DCHECK_NE, DCHECK_NOT_NULL, v8::internal::TracingFlags::is_zone_stats_enabled(), RoundUp(), size(), and V8_UNLIKELY.
DeleteAll()
void v8::internal::Zone::DeleteAll () [private]
Definition at line 110 of file zone.cc.
                     {
  Segment* current = segment_head_;
  if (current) {
    // Commit the allocation_size_ of segment_head_ and disconnect the segments
    // list from the zone in order to ensure that tracing accounting allocator
    // will observe value including memory from the head segment.
    allocation_size_ = allocation_size();
    segment_head_ = nullptr;
  }
  allocator_->TraceZoneDestruction(this);
  // Traverse the chained list of segments and return them all to the allocator.
  while (current) {
    Segment* next = current->next();
    segment_bytes_allocated_ -= current->total_size();
    ReleaseSegment(current);
    current = next;
  }
  position_ = limit_ = 0;
  allocation_size_ = 0;
#ifdef V8_ENABLE_PRECISE_ZONE_STATS
  allocation_size_for_tracing_ = 0;
#endif
}
References allocation_size(), allocation_size_, allocator_, limit_, v8::internal::Segment::next(), position_, ReleaseSegment(), segment_bytes_allocated_, segment_head_, v8::internal::Segment::total_size(), and v8::internal::AccountingAllocator::TraceZoneDestruction().
Referenced by Reset(), and ~Zone().
DeleteArray()
template<typename T , typename TypeTag = T[]>
void v8::internal::Zone::DeleteArray (T * pointer, size_t length) [inline]
Definition at line 167 of file zone.h.
                                              {
    Delete<TypeTag>(pointer, length * sizeof(T));
  }
References v8::internal::length.
Referenced by v8::internal::ZoneList< v8::internal::interpreter::BytecodeLabels >::AddAll(), v8::internal::compiler::turboshaft::Graph::AllocateNewBlocks(), v8::internal::ZoneAllocator< T >::deallocate(), v8::internal::ZoneAllocationPolicy::DeleteArray(), v8::internal::wasm::FastZoneVector< T >::Grow(), v8::internal::ZoneVector< T >::Grow(), v8::internal::ZoneVector< T >::operator=(), v8::internal::ZoneVector< T >::PrepareForInsertion(), v8::internal::wasm::FastZoneVector< T >::Reset(), v8::internal::ZoneList< T >::Resize(), and v8::internal::ZoneVector< T >::~ZoneVector().
Expand()
void v8::internal::Zone::Expand (size_t size) [private]
Definition at line 143 of file zone.cc.
                             {
  // Make sure the requested size is already properly aligned and that
  // there isn't enough room in the Zone to satisfy the request.
  DCHECK_EQ(size, RoundDown(size, kAlignmentInBytes));
  DCHECK_LT(limit_ - position_, size);
  // Compute the new segment size. We use a 'high water mark'
  // strategy, where we increase the segment size every time we expand
  // except that we employ a maximum segment size when we delete. This
  // is to avoid excessive malloc() and free() overhead.
  //
  // TODO(409953791): This can be simplified when using the page pool for
  // managing zone memory as it works with equal-sized segments.
  Segment* head = segment_head_;
  const size_t old_size = head ? head->total_size() : 0;
  static const size_t kSegmentOverhead = sizeof(Segment) + kAlignmentInBytes;
  const size_t new_size_no_overhead = size + (old_size << 1);
  size_t new_size = kSegmentOverhead + new_size_no_overhead;
  const size_t min_new_size = kSegmentOverhead + size;
  // Guard against integer overflow.
  if (new_size_no_overhead < size || new_size < kSegmentOverhead) {
    V8::FatalProcessOutOfMemory(nullptr, "Zone");
  }
  if (new_size < kMinimumSegmentSize) {
    new_size = kMinimumSegmentSize;
  } else if (new_size >= kMaximumSegmentSize) {
    // Limit the size of new segments to avoid growing the segment size
    // exponentially, thus putting pressure on contiguous virtual address space.
    // All the while making sure to allocate a segment large enough to hold the
    // requested size.
    new_size = std::max({min_new_size, kMaximumSegmentSize});
  }
  if (new_size > INT_MAX) {
    V8::FatalProcessOutOfMemory(nullptr, "Zone");
  }
  Segment* segment = allocator_->AllocateSegment(new_size);
  if (segment == nullptr) {
    V8::FatalProcessOutOfMemory(nullptr, "Zone");
  }
  DCHECK_GE(segment->total_size(), new_size);
  segment_bytes_allocated_ += segment->total_size();
  segment->set_zone(this);
  segment->set_next(segment_head_);
  // Commit the allocation_size_ of segment_head_ if any, in order to ensure
  // that tracing accounting allocator will observe value including memory
  // from the previous head segment.
  allocation_size_ = allocation_size();
  segment_head_ = segment;
  allocator_->TraceAllocateSegment(segment);
  // Recompute 'top' and 'limit' based on the new segment.
  position_ = RoundUp(segment->start(), kAlignmentInBytes);
  limit_ = segment->end();
  DCHECK_LE(position_, limit_);
  DCHECK_LE(size, limit_ - position_);
}
References v8::internal::AccountingAllocator::AllocateSegment(), allocation_size(), allocation_size_, allocator_, DCHECK_EQ, DCHECK_GE, DCHECK_LE, DCHECK_LT, v8::internal::Segment::end(), v8::internal::V8::FatalProcessOutOfMemory(), kAlignmentInBytes, kMaximumSegmentSize, kMinimumSegmentSize, limit_, position_, RoundDown(), RoundUp(), segment_bytes_allocated_, segment_head_, v8::internal::Segment::set_next(), v8::internal::Segment::set_zone(), size(), v8::internal::Segment::start(), v8::internal::Segment::total_size(), and v8::internal::AccountingAllocator::TraceAllocateSegment().
Referenced by AsanNew().
freed_size_for_tracing()
size_t v8::internal::Zone::freed_size_for_tracing () const [inline]
Definition at line 204 of file zone.h.
                                        {
#ifdef V8_ENABLE_PRECISE_ZONE_STATS
    return freed_size_for_tracing_;
#else
    return 0;
#endif
  }
name()
const char* v8::internal::Zone::name () const [inline]
Definition at line 181 of file zone.h.
{ return name_; }
Referenced by v8::internal::FuncNameInferrer::MakeNameFromStack().
New()
template<typename T , typename... Args>
T* v8::internal::Zone::New (Args &&... args) [inline]
Definition at line 108 of file zone.h.
                         {
    static_assert(alignof(T) <= kAlignmentInBytes);
    void* memory = Allocate<T>(sizeof(T));
    return new (memory) T(std::forward<Args>(args)...);
  }
References v8::base::args, and T.
Referenced by v8::internal::compiler::RedundancyElimination::EffectPathChecks::AddCheck(), v8::internal::CharacterRange::AddClassEscape(), v8::internal::compiler::SourcePositionTable::AddDecorator(), v8::internal::compiler::NodeOriginTable::AddDecorator(), v8::internal::compiler::BlockAssessments::AddDefinition(), v8::internal::compiler::LoadElimination::AbstractState::AddElement(), v8::internal::SourceTextModuleDescriptor::AddExport(), v8::internal::compiler::WasmLoadElimination::HalfState::AddField(), v8::internal::compiler::LoadElimination::AbstractState::AddField(), v8::internal::compiler::CsaLoadElimination::HalfState::AddField(), v8::internal::Parser::AddFormalParameter(), v8::internal::wasm::WasmModuleBuilder::AddFunction(), v8::internal::GuardedAlternative::AddGuard(), v8::internal::SourceTextModuleDescriptor::AddImport(), v8::internal::maglev::MaglevGraphBuilder::AddInlinedArgumentsToDeoptFrame(), v8::internal::compiler::InstructionScheduler::AddInstruction(), v8::internal::compiler::InstructionSequence::AddInstruction(), v8::internal::compiler::CodeGenerator::AddJumpTable(), v8::internal::SourceTextModuleDescriptor::AddModuleRequest(), v8::internal::compiler::ParallelMove::AddMove(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::AddNonBmpSurrogatePairs(), v8::internal::compiler::SpecialRPONumberer::LoopInfo::AddOutgoing(), v8::internal::wasm::TypeCanonicalizer::AddPredefinedArrayTypes(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::AddReducer(), v8::internal::SourceTextModuleDescriptor::AddStarExport(), v8::internal::SourceTextModuleDescriptor::AddStarImport(), v8::internal::AstConsString::AddString(), v8::internal::compiler::InstructionScheduler::AddTerminator(), v8::internal::AssertionNode::AfterNewline(), v8::internal::compiler::SimplifiedOperatorBuilder::Allocate(), v8::internal::compiler::turboshaft::FrameStateData::Builder::AllocateFrameStateData(), v8::internal::interpreter::BytecodeArrayBuilder::AllocateJumpTable(), v8::internal::compiler::SimplifiedOperatorBuilder::AllocateRaw(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::AnalyzeLoopAssignment(), v8::internal::compiler::CommonOperatorBuilder::ArgumentsElementsState(), v8::internal::compiler::SimplifiedOperatorBuilder::ArgumentsLength(), v8::internal::compiler::CommonOperatorBuilder::ArgumentsLengthState(), v8::internal::compiler::CodeGenerator::AssembleArchInstruction(), v8::internal::compiler::CodeGenerator::AssembleConstructFrame(), v8::internal::compiler::CommonOperatorBuilder::Assert(), v8::internal::compiler::SimplifiedOperatorBuilder::AssertType(), v8::internal::compiler::RegisterAllocationData::AssignSpillRangeToLiveRange(), v8::internal::AstValueFactory::AstValueFactory(), v8::internal::AssertionNode::AtBoundary(), v8::internal::AssertionNode::AtEnd(), v8::internal::AssertionNode::AtNonBoundary(), v8::internal::AssertionNode::AtStart(), v8::internal::ActionNode::BeginNegativeSubmatch(), v8::internal::ActionNode::BeginPositiveSubmatch(), v8::internal::compiler::SpecialRPONumberer::BeyondEndSentinel(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::BoundaryAssertionAsLookaround(), v8::internal::BoyerMooreLookahead::BoyerMooreLookahead(), v8::internal::compiler::CodeAssembler::BreakOnNode(), v8::internal::wasm::StructTypeBase::BuilderImpl< Subclass, ValueTypeSubclass >::Build(), v8::internal::compiler::BundleBuilder::BuildBundles(), v8::internal::compiler::Scheduler::BuildCFG(), v8::internal::interpreter::BytecodeGenerator::BuildCreateArrayLiteral(), v8::internal::RegExpLookaround::Builder::Builder(), v8::internal::compiler::CodeGenerator::BuildTranslation(), v8::internal::interpreter::BytecodeArrayBuilder::BytecodeArrayBuilder(), v8::internal::interpreter::BytecodeGenerator::BytecodeGenerator(), v8::internal::interpreter::BytecodeRegisterOptimizer::BytecodeRegisterOptimizer(), v8::internal::compiler::CommonOperatorBuilder::Call(), v8::internal::compiler::JSOperatorBuilder::Call(), v8::internal::compiler::JSOperatorBuilder::CallForwardVarargs(), v8::internal::compiler::JSOperatorBuilder::CallRuntime(), v8::internal::compiler::JSOperatorBuilder::CallWithArrayLike(), v8::internal::compiler::JSOperatorBuilder::CallWithSpread(), v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), v8::internal::compiler::CommonOperatorBuilder::Chained(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckBounds(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckClosure(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedFloat64ToAdditiveSafeInteger(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedFloat64ToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedFloat64ToInt64(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToAdditiveSafeInteger(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToFloat64(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToInt32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTaggedToInt64(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckedTruncateTaggedToWord32(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckFloat64Hole(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckIf(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckMaps(), v8::internal::compiler::SimplifiedOperatorBuilder::CheckTurboshaftTypeOf(), v8::internal::ActionNode::ClearCaptures(), v8::internal::ActionNode::ClearPosition(), v8::internal::compiler::turboshaft::StringEscapeAnalysisReducer< Next >::Deduplicator::clone(), v8::internal::maglev::KnownNodeAspects::Clone(), v8::internal::maglev::KnownNodeAspects::CloneForLoopHeader(), v8::internal::compiler::JSOperatorBuilder::CloneObject(), v8::internal::compiler::MemoryLowering::AllocationState::Closed(), v8::internal::compiler::CodeAssemblerLabel::CodeAssemblerLabel(), v8::internal::compiler::Revectorizer::CollectSeeds(), v8::internal::compiler::MachineOperatorBuilder::Comment(), v8::internal::compiler::SimplifiedOperatorBuilder::CompareMaps(), v8::internal::compiler::CommonOperatorBuilder::CompressedHeapConstant(), v8::internal::compiler::LiveRangeBuilder::ComputeLiveOut(), v8::internal::compiler::turboshaft::TurboshaftSpecialRPONumberer::ComputeLoopInfo(), v8::internal::compiler::SpecialRPONumberer::ComputeLoopInfo(), v8::internal::compiler::CsaLoadElimination::ComputeLoopState(), v8::internal::compiler::WasmLoadElimination::ComputeLoopState(), v8::internal::compiler::Scheduler::ComputeSchedule(), v8::internal::compiler::Scheduler::ComputeSpecialRPONumbering(), v8::internal::interpreter::ConditionalChainControlFlowBuilder::ConditionalChainControlFlowBuilder(), v8::internal::compiler::LiveRangeConnector::ConnectRanges(), v8::internal::interpreter::ConstantArrayBuilder::ConstantArrayBuilder(), v8::internal::compiler::JSOperatorBuilder::Construct(), v8::internal::compiler::JSOperatorBuilder::ConstructForwardAllArgs(), v8::internal::compiler::JSOperatorBuilder::ConstructForwardVarargs(), v8::internal::compiler::JSOperatorBuilder::ConstructWithArrayLike(), v8::internal::compiler::JSOperatorBuilder::ConstructWithSpread(), v8::internal::wasm::ModuleDecoderImpl::consume_array(), v8::internal::wasm::ModuleDecoderImpl::consume_sig(), v8::internal::wasm::ModuleDecoderImpl::consume_struct(), v8::internal::compiler::RedundancyElimination::EffectPathChecks::Copy(), v8::internal::PreparseDataBuilder::ByteData::CopyToZone(), v8::internal::AstNodeFactory::CopyVariable(), v8::internal::AstNodeFactory::CopyVariableProxy(), v8::internal::compiler::turboshaft::TSCallDescriptor::Create(), v8::internal::compiler::turboshaft::FastApiCallParameters::Create(), v8::internal::compiler::turboshaft::PretenuringPropagationAnalyzer::Create(), v8::internal::compiler::JSOperatorBuilder::CreateArguments(), v8::internal::compiler::JSOperatorBuilder::CreateArray(), v8::internal::compiler::JSOperatorBuilder::CreateArrayFromIterable(), v8::internal::compiler::JSOperatorBuilder::CreateArrayIterator(), v8::internal::compiler::JSOperatorBuilder::CreateAsyncFunctionObject(), v8::internal::compiler::JSOperatorBuilder::CreateBlockContext(), v8::internal::compiler::JSOperatorBuilder::CreateBoundFunction(), v8::internal::compiler::JSOperatorBuilder::CreateCatchContext(), v8::internal::compiler::JSOperatorBuilder::CreateClosure(), v8::internal::compiler::JSOperatorBuilder::CreateCollectionIterator(), v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::CreateCommonMachineGraph(), v8::internal::maglev::MaglevGraphBuilder::CreateEdgeSplitBlock(), v8::internal::compiler::JSOperatorBuilder::CreateEmptyLiteralArray(), v8::internal::compiler::JSOperatorBuilder::CreateEmptyLiteralObject(), v8::internal::compiler::RegisterAllocatorVerifier::CreateForBlock(), v8::internal::TextNode::CreateForCharacterRanges(), v8::internal::TextNode::CreateForSurrogatePair(), v8::internal::compiler::CodeGenerator::CreateFrameAccessState(), v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::compiler::CommonOperatorBuilder::CreateFrameStateFunctionInfo(), v8::internal::compiler::JSOperatorBuilder::CreateFunctionContext(), v8::internal::compiler::JSOperatorBuilder::CreateGeneratorObject(), v8::internal::compiler::JSOperatorBuilder::CreateLiteralArray(), v8::internal::compiler::JSOperatorBuilder::CreateLiteralObject(), v8::internal::compiler::JSOperatorBuilder::CreateLiteralRegExp(), v8::internal::wasm::InliningTree::CreateRoot(), v8::internal::compiler::JSOperatorBuilder::CreateWithContext(), v8::internal::compiler::CommonOperatorBuilder::DeadValue(), v8::internal::VariableMap::Declare(), v8::internal::DeclarationScope::DeclareFunctionVar(), v8::internal::DeclarationScope::DeclareThis(), v8::internal::compiler::JSOperatorBuilder::DefineKeyedOwnProperty(), v8::internal::compiler::JSOperatorBuilder::DefineKeyedOwnPropertyInLiteral(), v8::internal::compiler::JSOperatorBuilder::DefineNamedOwnProperty(), v8::internal::compiler::JSOperatorBuilder::DeleteProperty(), v8::internal::compiler::CommonOperatorBuilder::Deoptimize(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::Deoptimize(), v8::internal::compiler::CommonOperatorBuilder::DeoptimizeIf(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DeoptimizeIf(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::DeoptimizeIfNot(), v8::internal::compiler::CommonOperatorBuilder::DeoptimizeUnless(), v8::internal::compiler::CompilationDependencies::DependOnConsistentJSFunctionView(), v8::internal::compiler::CompilationDependencies::DependOnConstantInDictionaryPrototypeChain(), v8::internal::compiler::CompilationDependencies::DependOnContextCell(), v8::internal::compiler::CompilationDependencies::DependOnElementsKind(), v8::internal::compiler::CompilationDependencies::DependOnEmptyContextExtension(), v8::internal::compiler::CompilationDependencies::DependOnFieldConstness(), v8::internal::compiler::CompilationDependencies::DependOnGlobalProperty(), v8::internal::compiler::CompilationDependencies::DependOnInitialMap(), v8::internal::compiler::CompilationDependencies::DependOnInitialMapInstanceSizePrediction(), v8::internal::compiler::CompilationDependencies::DependOnNoSlackTrackingChange(), v8::internal::compiler::CompilationDependencies::DependOnObjectSlotValue(), v8::internal::compiler::CompilationDependencies::DependOnOwnConstantDataProperty(), v8::internal::compiler::CompilationDependencies::DependOnOwnConstantDictionaryProperty(), v8::internal::compiler::CompilationDependencies::DependOnOwnConstantDoubleProperty(), v8::internal::compiler::CompilationDependencies::DependOnOwnConstantElement(), v8::internal::compiler::CompilationDependencies::DependOnPretenureMode(), v8::internal::compiler::CompilationDependencies::DependOnProtector(), v8::internal::compiler::CompilationDependencies::DependOnPrototypeProperty(), v8::internal::compiler::CompilationDependencies::DependOnStableMap(), v8::internal::Scope::DeserializeScopeChain(), v8::internal::compiler::JSOperatorBuilder::DetachContextCell(), v8::internal::compiler::CommonOperatorBuilder::EffectPhi(), v8::internal::AssertionNode::EmitBoundaryCheck(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitClassRanges(), v8::internal::ChoiceNode::EmitOptimizedUnanchoredSearch(), v8::internal::compiler::MemoryLowering::AllocationState::Empty(), v8::internal::compiler::RedundancyElimination::EffectPathChecks::Empty(), v8::internal::ActionNode::EmptyMatchCheck(), v8::internal::compiler::CommonOperatorBuilder::End(), v8::internal::compiler::UnwindingInfoWriter::EndInstructionBlock(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::EnsureOutLivenessIsNotAlias(), v8::internal::DeclarationScope::EnsureRareData(), v8::internal::compiler::CommonOperatorBuilder::EnterMachineGraph(), v8::internal::AsmJsCompilationJob::ExecuteJobImpl(), v8::internal::compiler::CommonOperatorBuilder::ExitMachineGraph(), v8::internal::compiler::LoadElimination::AbstractField::Extend(), v8::internal::compiler::LoadElimination::AbstractElements::Extend(), v8::internal::compiler::LoadElimination::AbstractMaps::Extend(), v8::internal::compiler::CommonOperatorBuilder::ExternalConstant(), v8::internal::compiler::SimplifiedOperatorBuilder::FastApiCall(), v8::internal::compiler::CompilationDependencies::FieldConstnessDependencyOffTheRecord(), v8::internal::compiler::CompilationDependencies::FieldRepresentationDependencyOffTheRecord(), v8::internal::compiler::CompilationDependencies::FieldTypeDependencyOffTheRecord(), v8::internal::ChoiceNode::FilterOneByte(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::RegExpDisjunction::FixSingleCharacterDisjunctions(), v8::internal::compiler::CommonOperatorBuilder::Float32Constant(), v8::internal::compiler::CommonOperatorBuilder::Float64Constant(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::FlushTerms(), v8::internal::anonymous_namespace{regexp-bytecode-peephole.cc}::BytecodeSequenceNode::FollowedBy(), v8::internal::ProducedPreparseData::For(), v8::internal::compiler::JSOperatorBuilder::ForInNext(), v8::internal::compiler::JSOperatorBuilder::ForInPrepare(), v8::internal::RegExpLookaround::Builder::ForMatch(), v8::internal::compiler::turboshaft::Int64LoweringReducer< Next >::FrameState(), v8::internal::compiler::CommonOperatorBuilder::FrameState(), v8::internal::wasm::AsmType::FroundType(), v8::internal::wasm::AsmType::Function(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateArrayInitExpr(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), v8::internal::wasm::fuzzing::GenerateRandomWasmModule(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateStructNewInitExpr(), v8::internal::wasm::fuzzing::GenerateWasmModuleForDeopt(), v8::internal::wasm::fuzzing::GenerateWasmModuleForInitExpressions(), v8::internal::compiler::JSOperatorBuilder::GeneratorRestoreRegister(), v8::internal::compiler::JSOperatorBuilder::GeneratorStore(), v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), v8::internal::compiler::Linkage::GetCEntryStubCallDescriptor(), v8::internal::compiler::Scheduler::GetCommonDominator(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForEagerCall(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), v8::internal::compiler::JSOperatorBuilder::GetImportMeta(), v8::internal::compiler::JSOperatorBuilder::GetIterator(), v8::internal::compiler::Linkage::GetJSCallDescriptor(), v8::internal::compiler::CallDescriptor::GetMachineSignature(), v8::internal::compiler::turboshaft::Graph::GetOrCreateCompanion(), v8::internal::compiler::Instruction::GetOrCreateParallelMove(), v8::internal::compiler::Linkage::GetSimplifiedCDescriptor(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::JSOperatorBuilder::GetTemplateObject(), v8::internal::compiler::StateValuesCache::GetValuesNodeFromCache(), v8::internal::compiler::GetWasmCallDescriptor(), v8::internal::interpreter::BytecodeRegisterOptimizer::GrowRegisterMap(), v8::internal::compiler::JSOperatorBuilder::HasContextExtension(), v8::internal::compiler::JSOperatorBuilder::HasProperty(), v8::internal::compiler::CommonOperatorBuilder::HeapConstant(), v8::internal::compiler::CommonOperatorBuilder::IfDefault(), v8::internal::compiler::CommonOperatorBuilder::IfValue(), v8::internal::ActionNode::IncrementRegister(), v8::internal::compiler::CommonOperatorBuilder::InductionVariablePhi(), v8::internal::compiler::JSHeapBroker::InitializeAndStartSerializing(), v8::internal::compiler::TFPipelineData::InitializeFrameData(), v8::internal::compiler::TFPipelineData::InitializeInstructionSequence(), v8::internal::compiler::RegisterAllocationData::InitializePhiMap(), v8::internal::compiler::TFPipelineData::InitializeRegisterAllocationData(), v8::internal::wasm::InliningTree::Inline(), v8::internal::SparseBitVector::InsertBitAfter(), v8::internal::compiler::InstructionBlockFor(), v8::internal::compiler::CommonOperatorBuilder::Int32Constant(), v8::internal::compiler::CommonOperatorBuilder::Int64Constant(), v8::internal::compiler::LoadElimination::AbstractField::Kill(), v8::internal::compiler::LoadElimination::AbstractMaps::Kill(), v8::internal::compiler::LoadElimination::AbstractElements::Kill(), v8::internal::compiler::LoadElimination::AbstractState::KillAll(), v8::internal::compiler::LoadElimination::AbstractField::KillConst(), v8::internal::compiler::LoadElimination::AbstractState::KillConstField(), v8::internal::compiler::LoadElimination::AbstractState::KillElement(), v8::internal::compiler::LoadElimination::AbstractState::KillField(), v8::internal::compiler::WasmLoadElimination::HalfState::KillField(), v8::internal::compiler::CsaLoadElimination::HalfState::KillField(), v8::internal::compiler::LoadElimination::AbstractState::KillFields(), v8::internal::compiler::LoadElimination::AbstractState::KillMaps(), v8::internal::CharacterRange::List(), v8::internal::compiler::JSOperatorBuilder::LoadContext(), v8::internal::compiler::JSOperatorBuilder::LoadContextNoCell(), v8::internal::compiler::JSOperatorBuilder::LoadGlobal(), v8::internal::compiler::SimplifiedOperatorBuilder::LoadMessage(), v8::internal::compiler::JSOperatorBuilder::LoadModule(), v8::internal::compiler::JSOperatorBuilder::LoadNamed(), v8::internal::compiler::JSOperatorBuilder::LoadNamedFromSuper(), v8::internal::compiler::JSOperatorBuilder::LoadProperty(), v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::AccessorTable< PropertyT >::LookupOrInsert(), v8::internal::compiler::CommonOperatorBuilder::Loop(), v8::internal::compiler::CommonOperatorBuilder::LoopExitValue(), v8::internal::compiler::SimplifiedLowering::LowerAllNodes(), v8::internal::maglev::MaglevCompilationInfo::MaglevCompilationInfo(), v8::internal::maglev::MaglevAssembler::MakeDeferredCode(), v8::internal::compiler::SimplifiedOperatorBuilder::MapGuard(), v8::internal::compiler::SimplifiedOperatorBuilder::MaybeGrowFastElements(), v8::internal::compiler::ConstraintBuilder::MeetConstraintsBefore(), v8::internal::compiler::LoadElimination::AbstractElements::Merge(), v8::internal::compiler::LoadElimination::AbstractField::Merge(), v8::internal::compiler::LoadElimination::AbstractMaps::Merge(), v8::internal::compiler::CommonOperatorBuilder::Merge(), v8::internal::maglev::MergePointInterpreterFrameState::MergeLoop(), v8::internal::maglev::MergePointInterpreterFrameState::MergeValue(), v8::internal::wasm::AsmType::MinMaxType(), v8::internal::ActionNode::ModifyFlags(), v8::internal::maglev::MergePointInterpreterFrameState::New(), v8::internal::compiler::OtherNumberConstantType::New(), v8::internal::compiler::HeapConstantType::New(), v8::internal::compiler::TupleType::New(), v8::internal::compiler::UnionType::New(), v8::internal::compiler::RangeType::New(), v8::internal::maglev::Graph::New(), v8::internal::compiler::InstructionOperand::New(), v8::internal::maglev::MaglevCompilationUnit::New(), v8::internal::compiler::SimplifiedOperatorBuilder::NewArgumentsElements(), v8::internal::AstNodeFactory::NewArrayLiteral(), v8::internal::AstNodeFactory::NewAssignment(), v8::internal::AstNodeFactory::NewAsyncReturnStatement(), v8::internal::AstNodeFactory::NewAutoAccessorGetterBody(), v8::internal::AstNodeFactory::NewAutoAccessorInfo(), v8::internal::AstNodeFactory::NewAutoAccessorSetterBody(), v8::internal::AstNodeFactory::NewAwait(), v8::internal::compiler::Schedule::NewBasicBlock(), v8::internal::AstNodeFactory::NewBigIntLiteral(), v8::internal::AstNodeFactory::NewBinaryOperation(), v8::internal::AstNodeFactory::NewBlock(), v8::internal::AstNodeFactory::NewBooleanLiteral(), v8::internal::AstNodeFactory::NewBreakStatement(), v8::internal::compiler::turboshaft::SLPTree::NewBundlePackNode(), v8::internal::AstNodeFactory::NewCall(), v8::internal::AstNodeFactory::NewCallNew(), v8::internal::AstNodeFactory::NewCallRuntime(), v8::internal::AstNodeFactory::NewCaseClause(), v8::internal::AstNodeFactory::NewClassLiteral(), v8::internal::AstNodeFactory::NewClassLiteralProperty(), v8::internal::AstNodeFactory::NewClassLiteralStaticElement(), v8::internal::AstNodeFactory::NewCompareOperation(), v8::internal::AstNodeFactory::NewConditional(), v8::internal::AstNodeFactory::NewConditionalChain(), v8::internal::AstValueFactory::NewConsString(), v8::internal::AstNodeFactory::NewConsStringLiteral(), v8::internal::AstNodeFactory::NewContinueStatement(), v8::internal::AstNodeFactory::NewCountOperation(), v8::internal::AstNodeFactory::NewDebuggerStatement(), v8::internal::compiler::SimplifiedOperatorBuilder::NewDoubleElements(), v8::internal::maglev::MaglevCompilationUnit::NewDummy(), v8::internal::AstNodeFactory::NewEmptyParentheses(), v8::internal::AstNodeFactory::NewExpressionStatement(), v8::internal::maglev::MergePointInterpreterFrameState::NewForCatchBlock(), v8::internal::compiler::turboshaft::SLPTree::NewForcePackNode(), v8::internal::AstNodeFactory::NewForEachStatement(), v8::internal::maglev::MergePointInterpreterFrameState::NewForLoop(), v8::internal::AstNodeFactory::NewForOfStatement(), v8::internal::AstNodeFactory::NewFunctionDeclaration(), v8::internal::AstNodeFactory::NewFunctionLiteral(), v8::internal::AstNodeFactory::NewGetTemplateObject(), v8::internal::AstNodeFactory::NewIfStatement(), v8::internal::AstNodeFactory::NewImportCallExpression(), v8::internal::AstNodeFactory::NewInitializeClassMembersStatement(), v8::internal::AstNodeFactory::NewInitializeClassStaticElementsStatement(), v8::internal::maglev::MaglevCompilationUnit::NewInner(), v8::internal::compiler::JSHeapBroker::NewInsufficientFeedback(), v8::internal::compiler::turboshaft::SLPTree::NewIntersectPackNode(), v8::internal::ZoneCompactSet< T >::NewList(), v8::internal::compiler::RegisterAllocationData::NewLiveRange(), v8::internal::AstNodeFactory::NewNaryOperation(), v8::internal::AstNodeFactory::NewNativeFunctionLiteral(), v8::internal::AstNodeFactory::NewNestedVariableDeclaration(), v8::internal::AstNodeFactory::NewNullLiteral(), v8::internal::AstNodeFactory::NewNumberLiteral(), v8::internal::AstNodeFactory::NewObjectLiteral(), v8::internal::AstNodeFactory::NewObjectLiteralProperty(), v8::internal::AstNodeFactory::NewOptionalChain(), v8::internal::compiler::turboshaft::SLPTree::NewPackNode(), v8::internal::compiler::SLPTree::NewPackNode(), v8::internal::AstNodeFactory::NewParameterInitializationBlock(), v8::internal::AstNodeFactory::NewProperty(), v8::internal::AstNodeFactory::NewRegExpLiteral(), v8::internal::AstNodeFactory::NewReturnStatement(), v8::internal::AstNodeFactory::NewScriptOrEvalFunctionLiteral(), v8::internal::compiler::turboshaft::SLPTree::NewShufflePackNode(), v8::internal::AstNodeFactory::NewSloppyBlockFunctionStatement(), v8::internal::AstNodeFactory::NewSmiLiteral(), v8::internal::compiler::SimplifiedOperatorBuilder::NewSmiOrObjectElements(), v8::internal::AstNodeFactory::NewSpread(), v8::internal::AstNodeFactory::NewStringLiteral(), v8::internal::AstNodeFactory::NewSuperCallForwardArgs(), v8::internal::AstNodeFactory::NewSuperCallReference(), v8::internal::AstNodeFactory::NewSuperPropertyReference(), v8::internal::AstNodeFactory::NewSwitchStatement(), v8::internal::AstNodeFactory::NewSyntheticAsyncReturnStatement(), v8::internal::AstNodeFactory::NewTaggedTemplate(), v8::internal::AstNodeFactory::NewTemplateLiteral(), v8::internal::Scope::NewTemporary(), v8::internal::AstNodeFactory::NewTheHoleLiteral(), v8::internal::AstNodeFactory::NewThisExpression(), v8::internal::AstNodeFactory::NewThrow(), v8::internal::AstNodeFactory::NewTryCatchStatement(), v8::internal::AstNodeFactory::NewTryCatchStatementForAsyncAwait(), v8::internal::AstNodeFactory::NewTryCatchStatementForReplAsyncAwait(), v8::internal::AstNodeFactory::NewTryCatchStatementForReThrow(), v8::internal::AstNodeFactory::NewTryFinallyStatement(), v8::internal::AstNodeFactory::NewUnaryOperation(), v8::internal::AstNodeFactory::NewUndefinedLiteral(), v8::internal::compiler::LiveRangeBuilder::NewUsePosition(), v8::internal::AstNodeFactory::NewVariableDeclaration(), v8::internal::AstNodeFactory::NewVariableProxy(), v8::internal::compiler::EscapeAnalysisTracker::NewVirtualObject(), v8::internal::AstNodeFactory::NewWithStatement(), v8::internal::AstNodeFactory::NewYield(), v8::internal::AstNodeFactory::NewYieldStar(), v8::internal::compiler::CommonOperatorBuilder::NumberConstant(), v8::internal::compiler::CommonOperatorBuilder::ObjectId(), v8::internal::compiler::CommonOperatorBuilder::ObjectState(), v8::internal::compiler::MemoryLowering::AllocationState::Open(), v8::internal::RegExpCompiler::OptionallyStepBackToLeadSurrogate(), v8::internal::compiler::CommonOperatorBuilder::OsrValue(), v8::internal::wasm::AsmType::OverloadedFunction(), v8::internal::compiler::CommonOperatorBuilder::Parameter(), v8::internal::compiler::LoopPeeler::Peel(), v8::internal::compiler::CommonOperatorBuilder::Phi(), v8::internal::compiler::CommonOperatorBuilder::PointerConstant(), v8::internal::ActionNode::PositiveSubmatchSuccess(), v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl(), v8::internal::Parser::PrepareWrappedArguments(), v8::internal::RegExpCompiler::PreprocessRegExp(), v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForElementAccess(), v8::internal::compiler::JSHeapBroker::ProcessFeedbackMapsForKeyedPropertyAccess(), v8::internal::compiler::CommonOperatorBuilder::Projection(), v8::internal::compiler::FunctionalList< A >::PushFront(), v8::internal::compiler::StateValueList::PushRecursiveField(), v8::internal::compiler::StateValueList::PushStringConcat(), v8::internal::CharacterSet::ranges(), v8::internal::RegExpDisjunction::RationalizeConsecutiveAtoms(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForArrayOrObjectLiteral(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForBinaryOperation(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCall(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForCompareOperation(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForForIn(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForGlobalAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForInstanceOf(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForPropertyAccess(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForRegExpLiteral(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForTemplateObject(), v8::internal::compiler::JSHeapBroker::ReadFeedbackForTypeOf(), v8::internal::compiler::TopLevelLiveRange::RecordSpillLocation(), v8::internal::compiler::MemoryLowering::ReduceAllocateRaw(), v8::internal::compiler::CsaLoadElimination::ReduceEffectPhi(), v8::internal::compiler::LoadElimination::ReduceEffectPhi(), v8::internal::compiler::WasmLoadElimination::ReduceEffectPhi(), v8::internal::compiler::CsaLoadElimination::ReduceLoadFromObject(), v8::internal::compiler::WasmLoadElimination::ReduceLoadLikeFromImmutable(), v8::internal::compiler::CsaLoadElimination::ReduceStoreToObject(), v8::internal::compiler::WasmLoadElimination::ReduceStringPrepareForGetCodeunit(), v8::internal::compiler::WasmLoadElimination::ReduceWasmArrayInitializeLength(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet(), v8::internal::RegExpCompiler::RegExpCompiler(), v8::internal::compiler::RegisterAllocationData::RegisterAllocationData(), v8::internal::compiler::CommonOperatorBuilder::RelocatableInt32Constant(), v8::internal::compiler::CommonOperatorBuilder::RelocatableInt64Constant(), v8::internal::wasm::TypeCanonicalizer::CanonicalTypeVector::reserve(), v8::internal::SourceTextModule::ResolveExport(), v8::internal::compiler::SimplifiedOperatorBuilder::RestLength(), v8::internal::ActionNode::RestorePosition(), v8::internal::compiler::CommonOperatorBuilder::Return(), v8::internal::compiler::Revectorizer::Revectorizer(), v8::internal::compiler::turboshaft::WasmRevecAnalyzer::Run(), v8::internal::compiler::ScheduleVerifier::Run(), v8::internal::compiler::SimplifiedOperatorBuilder::RuntimeAbort(), v8::internal::compiler::ScheduleLateNodeVisitor::ScheduleNode(), v8::internal::compiler::CommonOperatorBuilder::Select(), v8::internal::DynamicBitSet::Set(), v8::internal::compiler::JSOperatorBuilder::SetKeyedProperty(), v8::internal::compiler::LoadElimination::AbstractState::SetMaps(), v8::internal::compiler::JSOperatorBuilder::SetNamedProperty(), v8::internal::ActionNode::SetRegisterForLoop(), v8::internal::compiler::PerIsolateCompilerCache::SetSnapshot(), v8::internal::compiler::PerIsolateCompilerCache::Setup(), v8::internal::compiler::SLPTree::SLPTree(), v8::internal::compiler::CommonOperatorBuilder::SLVerifierHint(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntAsIntN(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntAsUintN(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeBigIntNegate(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeToBigInt(), v8::internal::compiler::SimplifiedOperatorBuilder::SpeculativeToNumber(), v8::internal::compiler::LiveRange::SplitAt(), v8::internal::compiler::JSOperatorBuilder::StackCheck(), v8::internal::compiler::MachineOperatorBuilder::StackSlot(), v8::internal::PreparseDataBuilder::DataGatheringScope::Start(), v8::internal::compiler::CommonOperatorBuilder::Start(), v8::internal::compiler::ObserveNodeManager::StartObserving(), v8::internal::maglev::MaglevGraphBuilder::StartPrologue(), v8::internal::compiler::CommonOperatorBuilder::StateValues(), v8::internal::compiler::CommonOperatorBuilder::StaticAssert(), v8::internal::compiler::JSOperatorBuilder::StoreContext(), v8::internal::compiler::JSOperatorBuilder::StoreContextNoCell(), v8::internal::compiler::SimplifiedOperatorBuilder::StoreField(), v8::internal::compiler::JSOperatorBuilder::StoreGlobal(), v8::internal::compiler::JSOperatorBuilder::StoreInArrayLiteral(), v8::internal::compiler::SimplifiedOperatorBuilder::StoreMessage(), v8::internal::compiler::JSOperatorBuilder::StoreModule(), v8::internal::compiler::SimplifiedOperatorBuilder::StoreSignedSmallElement(), v8::internal::compiler::CommonOperatorBuilder::Switch(), v8::internal::compiler::CommonOperatorBuilder::TaggedIndexConstant(), v8::internal::compiler::CommonOperatorBuilder::TailCall(), v8::internal::compiler::TFPipelineData::TFPipelineData(), v8::internal::anonymous_namespace{regexp-compiler-tonode.cc}::ToCanonicalZoneList(), v8::internal::anonymous_namespace{regexp-parser.cc}::RegExpBuilder::ToRegExp(), v8::internal::compiler::MachineOperatorBuilder::TraceInstruction(), v8::internal::compiler::SimplifiedOperatorBuilder::TransitionAndStoreElement(), v8::internal::compiler::SimplifiedOperatorBuilder::TransitionAndStoreNonNumberElement(), v8::internal::compiler::SimplifiedOperatorBuilder::TransitionAndStoreNumberElement(), v8::internal::compiler::CompilationDependencies::TransitionDependencyOffTheRecord(), v8::internal::compiler::SimplifiedOperatorBuilder::TransitionElementsKind(), v8::internal::compiler::SimplifiedOperatorBuilder::TransitionElementsKindOrCheckMap(), v8::internal::compiler::TopLevelLiveRange::TransitionRangeToDeferredSpill(), v8::internal::compiler::TopLevelLiveRange::TreatAsSpilledInDeferredBlock(), v8::internal::compiler::CommonOperatorBuilder::TrustedHeapConstant(), v8::internal::compiler::LoopVariableOptimizer::TryGetInductionVariable(), v8::internal::maglev::MergePointInterpreterFrameState::TryMergeLoop(), v8::internal::compiler::SimplifiedOperatorBuilder::TypedArrayLength(), v8::internal::compiler::CommonOperatorBuilder::TypedObjectState(), v8::internal::compiler::CommonOperatorBuilder::TypedStateValues(), v8::internal::compiler::CommonOperatorBuilder::TypeGuard(), v8::internal::compiler::Typer::Typer(), v8::internal::SparseBitVector::Union(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateLiveness(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness(), v8::internal::wasm::AsmJsParser::ValidateModuleVarImport(), v8::internal::compiler::RegisterAllocatorVerifier::ValidatePendingAssessment(), v8::internal::compiler::SimplifiedOperatorBuilder::VerifyType(), v8::internal::compiler::RepresentationSelector::VisitFrameState(), v8::internal::compiler::RepresentationSelector::VisitObjectState(), v8::internal::compiler::RepresentationSelector::VisitStateValues(), v8::internal::compiler::MachineOperatorBuilder::Word32AtomicPairLoad(), and v8::internal::compiler::MachineOperatorBuilder::Word32AtomicPairStore().
NewVector() [1/2]
template<typename T , typename TypeTag = T[]>
base::Vector<T> v8::internal::Zone::NewVector (size_t length) [inline]
Definition at line 139 of file zone.h.
                                         {
    T* new_array = AllocateArray<T, TypeTag>(length);
    std::uninitialized_value_construct_n(new_array, length);
    return {new_array, length};
  }
References v8::internal::length.
Referenced by v8::internal::wasm::AsmJsParser::GetVarInfo(), v8::internal::compiler::turboshaft::LayeredHashMap< Key, Value >::LayeredHashMap(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
NewVector() [2/2]
template<typename T , typename TypeTag = T[]>
base::Vector<T> v8::internal::Zone::NewVector (size_t length, T value) [inline]
Definition at line 148 of file zone.h.
                                                  {
    T* new_array = AllocateArray<T, TypeTag>(length);
    std::uninitialized_fill_n(new_array, length, value);
    return {new_array, length};
  }
References v8::internal::length, and v8::internal::value.
ReleaseSegment()
void v8::internal::Zone::ReleaseSegment (Segment * segment) [private]
Definition at line 136 of file zone.cc.
                                          {
  // Un-poison the segment content so we can reuse or zap it later.
  ASAN_UNPOISON_MEMORY_REGION(reinterpret_cast<void*>(segment->start()),
                              segment->capacity());
  allocator_->ReturnSegment(segment);
}
References allocator_, ASAN_UNPOISON_MEMORY_REGION, v8::internal::Segment::capacity(), v8::internal::AccountingAllocator::ReturnSegment(), and v8::internal::Segment::start().
Referenced by DeleteAll(), and v8::internal::ZoneSnapshot::Restore().
Reset()
void v8::internal::Zone::Reset ()
Definition at line 69 of file zone.cc.
                 {
  if (!segment_head_) return;
  Segment* keep = segment_head_;
  segment_head_ = segment_head_->next();
  if (segment_head_ != nullptr) {
    // Reset the position to the end of the new head, and uncommit its
    // allocation size (which will be re-committed in DeleteAll).
    position_ = segment_head_->end();
    allocation_size_ -= segment_head_->end() - segment_head_->start();
  }
  keep->set_next(nullptr);
  DeleteAll();
  allocator_->TraceZoneCreation(this);
  // Un-poison the kept segment content so we can zap and reuse it.
  ASAN_UNPOISON_MEMORY_REGION(reinterpret_cast<void*>(keep->start()),
                              keep->capacity());
  keep->ZapContents();
  segment_head_ = keep;
  position_ = RoundUp(keep->start(), kAlignmentInBytes);
  limit_ = keep->end();
  DCHECK_LT(allocation_size(), kAlignmentInBytes);
  DCHECK_EQ(segment_bytes_allocated_, keep->total_size());
}
References allocation_size(), allocation_size_, allocator_, ASAN_UNPOISON_MEMORY_REGION, v8::internal::Segment::capacity(), DCHECK_EQ, DCHECK_LT, DeleteAll(), v8::internal::Segment::end(), kAlignmentInBytes, limit_, v8::internal::Segment::next(), position_, RoundUp(), segment_bytes_allocated_, segment_head_, v8::internal::Segment::set_next(), v8::internal::Segment::start(), v8::internal::Segment::total_size(), v8::internal::AccountingAllocator::TraceZoneCreation(), and v8::internal::Segment::ZapContents().
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_init_expr(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::ConsumeElementSegmentEntry(), v8::internal::wasm::TypeCanonicalizer::EmptyStorageForTesting(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::DeclarationScope::ResetAfterPreparsing(), and v8::internal::wasm::anonymous_namespace{module-decoder.cc}::ValidateFunctionsTask::Run().
Seal()
void v8::internal::Zone::Seal () [inline]
Definition at line 172 of file zone.h.
{ sealed_ = true; }
segment_bytes_allocated()
size_t v8::internal::Zone::segment_bytes_allocated () const [inline]
Definition at line 179 of file zone.h.
{ return segment_bytes_allocated_; }
Referenced by v8::internal::TracingAccountingAllocator::TraceZoneDestructionImpl().
Snapshot()
ZoneSnapshot v8::internal::Zone::Snapshot () const
Definition at line 108 of file zone.cc.
{ return ZoneSnapshot{this}; }
Referenced by v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), and v8::internal::wasm::TypeCanonicalizer::AddRecursiveSingletonGroup().
Friends And Related Function Documentation
ZoneSnapshot
friend class ZoneSnapshot [friend]
Definition at line 276 of file zone.h.
Member Data Documentation
allocation_size_
std::atomic<size_t> v8::internal::Zone::allocation_size_ = {0} [private]
Definition at line 245 of file zone.h.
Referenced by DeleteAll(), Expand(), Reset(), and v8::internal::ZoneSnapshot::Restore().
allocator_
AccountingAllocator* v8::internal::Zone::allocator_ [private]
Definition at line 262 of file zone.h.
Referenced by DeleteAll(), Expand(), ReleaseSegment(), Reset(), and Zone().
kAlignmentInBytes
const size_t v8::internal::Zone::kAlignmentInBytes = 8 [static], [private]
Definition at line 236 of file zone.h.
Referenced by AsanNew(), Expand(), and Reset().
kMaximumSegmentSize
const size_t v8::internal::Zone::kMaximumSegmentSize = 32 * KB [static], [private]
Definition at line 242 of file zone.h.
Referenced by Expand().
kMinimumSegmentSize
const size_t v8::internal::Zone::kMinimumSegmentSize = 8 * KB [static], [private]
Definition at line 239 of file zone.h.
Referenced by Expand().
limit_
Address v8::internal::Zone::limit_ = 0 [private]
Definition at line 260 of file zone.h.
Referenced by AsanNew(), DeleteAll(), Expand(), Reset(), and v8::internal::ZoneSnapshot::Restore().
name_
const char* v8::internal::Zone::name_ [private]
Definition at line 265 of file zone.h.
position_
Address v8::internal::Zone::position_ = 0 [private]
Definition at line 259 of file zone.h.
Referenced by AsanNew(), DeleteAll(), Expand(), Reset(), and v8::internal::ZoneSnapshot::Restore().
sealed_
bool v8::internal::Zone::sealed_ = false [private]
Definition at line 266 of file zone.h.
Referenced by AsanNew().
segment_bytes_allocated_
std::atomic<size_t> v8::internal::Zone::segment_bytes_allocated_ = {0} [private]
Definition at line 250 of file zone.h.
Referenced by DeleteAll(), Expand(), Reset(), v8::internal::ZoneSnapshot::Restore(), and ~Zone().
segment_head_
Segment* v8::internal::Zone::segment_head_ = nullptr [private]
Definition at line 264 of file zone.h.
Referenced by DeleteAll(), Expand(), Reset(), and v8::internal::ZoneSnapshot::Restore().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/zone/zone.h
/mnt/V8SourceCode/src/zone/zone.cc