v8::internal::anonymous_namespace{gc-extension.cc}::AsyncGC Class Reference
Public Member Functions
~AsyncGC () final=default
AsyncGC (v8::Isolate *isolate, v8::Local< v8::Promise::Resolver > resolver, GCOptions options)
AsyncGC (const AsyncGC &)=delete
AsyncGC & operator= (const AsyncGC &)=delete
void RunInternal () final
Private Attributes
v8::Isolate * isolate_
v8::Global< v8::Context > ctx_
v8::Global< v8::Promise::Resolver > resolver_
GCOptions options_
Additional Inherited Members
Detailed Description
Definition at line 232 of file gc-extension.cc.
Constructor & Destructor Documentation
 AsyncGC()
v8::internal::anonymous_namespace{gc-extension.cc}::AsyncGC::~AsyncGC () [final], [default]
AsyncGC() [1/2]
v8::internal::anonymous_namespace{gc-extension.cc}::AsyncGC::AsyncGC (v8::Isolate * isolate, v8::Local< v8::Promise::Resolver > resolver, GCOptions options) [inline]
Definition at line 236 of file gc-extension.cc.
      : CancelableTask(reinterpret_cast<Isolate*>(isolate)),
        isolate_(isolate),
        ctx_(isolate, isolate->GetCurrentContext()),
        resolver_(isolate, resolver),
        options_(options) {}
AsyncGC() [2/2]
v8::internal::anonymous_namespace{gc-extension.cc}::AsyncGC::AsyncGC (const AsyncGC &) [delete]
Member Function Documentation
operator=()
AsyncGC& v8::internal::anonymous_namespace{gc-extension.cc}::AsyncGC::operator= (const AsyncGC &) [delete]
RunInternal()
void v8::internal::anonymous_namespace{gc-extension.cc}::AsyncGC::RunInternal () [inline], [final], [virtual]
Implements v8::internal::CancelableTask.
Definition at line 246 of file gc-extension.cc.
                           {
    v8::HandleScope scope(isolate_);
    InvokeGC(isolate_, options_);
    auto resolver = v8::Local<v8::Promise::Resolver>::New(isolate_, resolver_);
    auto ctx = Local<v8::Context>::New(isolate_, ctx_);
    v8::MicrotasksScope microtasks_scope(
        ctx, v8::MicrotasksScope::kDoNotRunMicrotasks);
    resolver->Resolve(ctx, v8::Undefined(isolate_)).ToChecked();
  }
References v8::internal::anonymous_namespace{gc-extension.cc}::InvokeGC(), v8::MicrotasksScope::kDoNotRunMicrotasks, v8::Local< T >::New(), and v8::Undefined().
Member Data Documentation
ctx_
v8::Global<v8::Context> v8::internal::anonymous_namespace{gc-extension.cc}::AsyncGC::ctx_ [private]
Definition at line 258 of file gc-extension.cc.
isolate_
v8::Isolate* v8::internal::anonymous_namespace{gc-extension.cc}::AsyncGC::isolate_ [private]
Definition at line 257 of file gc-extension.cc.
options_
GCOptions v8::internal::anonymous_namespace{gc-extension.cc}::AsyncGC::options_ [private]
Definition at line 260 of file gc-extension.cc.
resolver_
v8::Global<v8::Promise::Resolver> v8::internal::anonymous_namespace{gc-extension.cc}::AsyncGC::resolver_ [private]
Definition at line 259 of file gc-extension.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/extensions/gc-extension.cc