v8::internal::compiler::JSDefineKeyedOwnPropertyInLiteralNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSDefineKeyedOwnPropertyInLiteralNode (Node *node)
const FeedbackParameter & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1679 of file js-operator.h.
Constructor & Destructor Documentation
JSDefineKeyedOwnPropertyInLiteralNode()
constexpr v8::internal::compiler::JSDefineKeyedOwnPropertyInLiteralNode::JSDefineKeyedOwnPropertyInLiteralNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1681 of file js-operator.h.
      : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSDefineKeyedOwnPropertyInLiteral, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const FeedbackParameter& v8::internal::compiler::JSDefineKeyedOwnPropertyInLiteralNode::Parameters () const [inline]
Definition at line 1686 of file js-operator.h.
                                              {
    return FeedbackParameterOf(node()->op());
  }
References v8::internal::compiler::FeedbackParameterOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSDefineKeyedOwnPropertyInLiteral().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h