v8::internal::WritableJitAllocation Class Reference
#include <code-memory-access.h>
Public Member Functions
WritableJitAllocation (const WritableJitAllocation &)=delete
WritableJitAllocation & operator= (const WritableJitAllocation &)=delete
~WritableJitAllocation ()
template<typename T , size_t offset>
void WriteHeaderSlot (T value)
template<typename T , size_t offset>
void WriteHeaderSlot (Tagged< T > value, ReleaseStoreTag)
template<typename T , size_t offset>
void WriteHeaderSlot (Tagged< T > value, RelaxedStoreTag)
template<typename T , size_t offset>
void WriteProtectedPointerHeaderSlot (Tagged< T > value, ReleaseStoreTag)
template<typename T , size_t offset>
void WriteProtectedPointerHeaderSlot (Tagged< T > value, RelaxedStoreTag)
template<typename T >
void WriteHeaderSlot (Address address, T value, RelaxedStoreTag)
void CopyCode (size_t dst_offset, const uint8_t *src, size_t num_bytes)
void CopyData (size_t dst_offset, const uint8_t *src, size_t num_bytes)
template<typename T >
void WriteUnalignedValue (Address address, T value)
template<typename T >
void WriteValue (Address address, T value)
template<typename T >
void WriteValue (Address address, T value, RelaxedStoreTag)
void ClearBytes (size_t offset, size_t len)
Address address () const
size_t size () const
Static Public Member Functions
static WritableJitAllocation ForInstructionStream (Tagged< InstructionStream > istream)
static WritableJitAllocation ForNonExecutableMemory (Address addr, size_t size, ThreadIsolation::JitAllocationType type)
Private Types
enum class JitAllocationSource { kRegister
, kLookup
 }
Private Member Functions
WritableJitAllocation (Address addr, size_t size, ThreadIsolation::JitAllocationType type, JitAllocationSource source, bool enforce_write_api=false)
WritableJitAllocation (Address addr, size_t size, ThreadIsolation::JitAllocationType type, bool enforce_write_api)
ThreadIsolation::JitPageReference & page_ref ()
std::optional< RwxMemoryWriteScope > WriteScopeForApiEnforcement () const
Private Attributes
const Address address_
std::optional< RwxMemoryWriteScope > write_scope_
std::optional< ThreadIsolation::JitPageReference > page_ref_
const ThreadIsolation::JitAllocation allocation_
bool enforce_write_api_ = false
Friends
class ThreadIsolation
class WritableJitPage
class WritableJumpTablePair
Detailed Description
Definition at line 387 of file code-memory-access.h.
Member Enumeration Documentation
JitAllocationSource
enum v8::internal::WritableJitAllocation::JitAllocationSource [strong], [private]
Enumerator
kRegister
kLookup
Definition at line 448 of file code-memory-access.h.
                                 {
    kRegister,
    kLookup,
  };
Constructor & Destructor Documentation
WritableJitAllocation() [1/3]
v8::internal::WritableJitAllocation::WritableJitAllocation (const WritableJitAllocation &) [delete]
Referenced by ForNonExecutableMemory().
 WritableJitAllocation()
v8::internal::WritableJitAllocation::~WritableJitAllocation () [inline]
Definition at line 40 of file code-memory-access-inl.h.
                                              {
#ifdef DEBUG
  if (enforce_write_api_ && page_ref_.has_value()) {
    // We disabled RWX write access for debugging. But we'll need it in the
    // destructor again to release the jit page reference.
    write_scope_.emplace("~WritableJitAllocation");
  }
#endif
}
References enforce_write_api_, page_ref_, and write_scope_.
WritableJitAllocation() [2/3]
v8::internal::WritableJitAllocation::WritableJitAllocation (Address addr, size_t size, ThreadIsolation::JitAllocationType type, JitAllocationSource source, bool enforce_write_api = false) [inline], [private]
Definition at line 50 of file code-memory-access-inl.h.
    : address_(addr),
      // The order of these is important. We need to create the write scope
      // before we lookup the Jit page, since the latter will take a mutex in
      // protected memory.
      write_scope_("WritableJitAllocation"),
      page_ref_(ThreadIsolation::LookupJitPage(addr, size)),
      allocation_(source == JitAllocationSource::kRegister
                      ? page_ref_->RegisterAllocation(addr, size, type)
                      : page_ref_->LookupAllocation(addr, size, type)),
      enforce_write_api_(enforce_write_api) {
#ifdef DEBUG
  if (enforce_write_api_) {
    // Reset the write scope for debugging. We'll create fine-grained scopes in
    // all Write functions of this class instead.
    write_scope_.reset();
  }
#else
  // Suppress -Wunused-private-field warning.
  (void)enforce_write_api_;
#endif
}
References enforce_write_api_, v8::internal::wasm::void(), and write_scope_.
WritableJitAllocation() [3/3]
v8::internal::WritableJitAllocation::WritableJitAllocation (Address addr, size_t size, ThreadIsolation::JitAllocationType type, bool enforce_write_api) [inline], [private]
Definition at line 75 of file code-memory-access-inl.h.
    : address_(addr),
      allocation_(size, type),
      enforce_write_api_(enforce_write_api) {}
Member Function Documentation
address()
Address v8::internal::WritableJitAllocation::address () const [inline]
Definition at line 444 of file code-memory-access.h.
{ return address_; }
References address_.
Referenced by WriteHeaderSlot(), WriteUnalignedValue(), and WriteValue().
ClearBytes()
void v8::internal::WritableJitAllocation::ClearBytes (size_t offset, size_t len) [inline]
Definition at line 259 of file code-memory-access-inl.h.
                                                                {
  std::optional<RwxMemoryWriteScope> write_scope =
      WriteScopeForApiEnforcement();
  memset(reinterpret_cast<void*>(address_ + offset), 0, len);
}
References address_, and WriteScopeForApiEnforcement().
Referenced by v8::internal::wasm::NativeModule::CreateEmptyJumpTableInRegionLocked(), and v8::internal::InstructionStream::Initialize().
CopyCode()
void v8::internal::WritableJitAllocation::CopyCode (size_t dst_offset, const uint8_t * src, size_t num_bytes) [inline]
Definition at line 245 of file code-memory-access-inl.h.
                                                       {
  std::optional<RwxMemoryWriteScope> write_scope =
      WriteScopeForApiEnforcement();
  CopyBytes(reinterpret_cast<uint8_t*>(address_ + dst_offset), src, num_bytes);
}
References address_, v8::internal::CopyBytes(), and WriteScopeForApiEnforcement().
Referenced by v8::internal::wasm::NativeModule::AddCodeForTesting(), v8::internal::wasm::NativeModule::AddCodeWithCodeSpace(), v8::internal::wasm::WasmImportWrapperCache::ModificationScope::AddWrapper(), v8::internal::wasm::NativeModuleDeserializer::CopyAndRelocate(), v8::internal::InstructionStream::Finalize(), and v8::internal::EvacuateVisitorBase::RawMigrateObject().
CopyData()
void v8::internal::WritableJitAllocation::CopyData (size_t dst_offset, const uint8_t * src, size_t num_bytes) [inline]
Definition at line 252 of file code-memory-access-inl.h.
                                                       {
  std::optional<RwxMemoryWriteScope> write_scope =
      WriteScopeForApiEnforcement();
  CopyBytes(reinterpret_cast<uint8_t*>(address_ + dst_offset), src, num_bytes);
}
References address_, v8::internal::CopyBytes(), and WriteScopeForApiEnforcement().
Referenced by v8::internal::InstructionStream::Finalize(), and v8::internal::EvacuateVisitorBase::RawMigrateObject().
ForInstructionStream()
WritableJitAllocation v8::internal::WritableJitAllocation::ForInstructionStream (Tagged< InstructionStream > istream) [static]
Definition at line 673 of file code-memory-access.cc.
                                       {
  return WritableJitAllocation(
      istream->address(), istream->Size(),
      ThreadIsolation::JitAllocationType::kInstructionStream,
      JitAllocationSource::kLookup);
}
References v8::internal::Tagged< HeapObject >::address(), v8::internal::ThreadIsolation::kInstructionStream, and v8::internal::ThreadIsolation::WritableJitAllocation.
Referenced by v8::internal::EvacuateVisitorBase::RawMigrateObject().
ForNonExecutableMemory()
WritableJitAllocation v8::internal::WritableJitAllocation::ForNonExecutableMemory (Address addr, size_t size, ThreadIsolation::JitAllocationType type) [inline], [static]
Definition at line 83 of file code-memory-access-inl.h.
                                                                      {
  return WritableJitAllocation(addr, size, type, false);
}
References size(), v8::internal::tracing::type, and WritableJitAllocation().
Referenced by v8::internal::wasm::NativeModuleSerializer::WriteCode().
operator=()
WritableJitAllocation& v8::internal::WritableJitAllocation::operator= (const WritableJitAllocation &) [delete]
page_ref()
ThreadIsolation::JitPageReference& v8::internal::WritableJitAllocation::page_ref () [inline], [private]
Definition at line 461 of file code-memory-access.h.
{ return page_ref_.value(); }
References page_ref_.
size()
size_t v8::internal::WritableJitAllocation::size () const [inline]
Definition at line 445 of file code-memory-access.h.
{ return allocation_.Size(); }
References allocation_, and v8::internal::ThreadIsolation::JitAllocation::Size().
Referenced by ForNonExecutableMemory(), v8::internal::InstructionStream::Initialize(), WriteUnalignedValue(), and WriteValue().
WriteHeaderSlot() [1/4]
template<typename T >
void v8::internal::WritableJitAllocation::WriteHeaderSlot (Address address, T value, RelaxedStoreTag tag) [inline]
Definition at line 194 of file code-memory-access-inl.h.
                                                                           {
  CHECK_EQ(allocation_.Type(),
           ThreadIsolation::JitAllocationType::kInstructionStream);
  size_t offset = address - address_;
  Tagged<T> tagged(value);
  switch (offset) {
    case InstructionStream::kCodeOffset:
      WriteProtectedPointerHeaderSlot<T, InstructionStream::kCodeOffset>(tagged,
                                                                         tag);
      break;
    case InstructionStream::kRelocationInfoOffset:
      WriteProtectedPointerHeaderSlot<T,
                                      InstructionStream::kRelocationInfoOffset>(
          tagged, tag);
      break;
    default:
      UNREACHABLE();
  }
}
References address(), address_, allocation_, CHECK_EQ, v8::internal::ThreadIsolation::kInstructionStream, T, v8::internal::ThreadIsolation::JitAllocation::Type(), v8::internal::UNREACHABLE(), v8::internal::value, and WriteProtectedPointerHeaderSlot().
WriteHeaderSlot() [2/4]
template<typename T , size_t offset>
void v8::internal::WritableJitAllocation::WriteHeaderSlot (T value) [inline]
Definition at line 133 of file code-memory-access-inl.h.
                                                   {
  std::optional<RwxMemoryWriteScope> write_scope =
      WriteScopeForApiEnforcement();
  // This assert is no strict requirement, it just guards against
  // non-implemented functionality.
  static_assert(!is_taggable_v<T>);
  if constexpr (offset == HeapObject::kMapOffset) {
    TaggedField<T, offset>::Relaxed_Store_Map_Word(
        HeapObject::FromAddress(address_), value);
  } else {
    WriteMaybeUnalignedValue<T>(address_ + offset, value);
  }
}
References address_, v8::internal::HeapObject::FromAddress(), v8::internal::HeapObject::kMapOffset, v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store_Map_Word(), v8::internal::value, and WriteScopeForApiEnforcement().
Referenced by v8::internal::InstructionStream::Initialize(), and v8::internal::EvacuateVisitorBase::RawMigrateObject().
WriteHeaderSlot() [3/4]
template<typename T , size_t offset>
void v8::internal::WritableJitAllocation::WriteHeaderSlot (Tagged< T > value, RelaxedStoreTag) [inline]
Definition at line 161 of file code-memory-access-inl.h.
                                                                            {
  std::optional<RwxMemoryWriteScope> write_scope =
      WriteScopeForApiEnforcement();
  if constexpr (offset == HeapObject::kMapOffset) {
    TaggedField<T, offset>::Relaxed_Store_Map_Word(
        HeapObject::FromAddress(address_), value);
  } else {
    TaggedField<T, offset>::Relaxed_Store(HeapObject::FromAddress(address_),
                                          value);
  }
}
References address_, v8::internal::HeapObject::FromAddress(), v8::internal::HeapObject::kMapOffset, v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store_Map_Word(), v8::internal::value, and WriteScopeForApiEnforcement().
WriteHeaderSlot() [4/4]
template<typename T , size_t offset>
void v8::internal::WritableJitAllocation::WriteHeaderSlot (Tagged< T > value, ReleaseStoreTag) [inline]
Definition at line 149 of file code-memory-access-inl.h.
                                                                            {
  std::optional<RwxMemoryWriteScope> write_scope =
      WriteScopeForApiEnforcement();
  // These asserts are no strict requirements, they just guard against
  // non-implemented functionality.
  static_assert(offset != HeapObject::kMapOffset);
  TaggedField<T, offset>::Release_Store(HeapObject::FromAddress(address_),
                                        value);
}
References address_, v8::internal::HeapObject::FromAddress(), v8::internal::HeapObject::kMapOffset, v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store(), v8::internal::value, and WriteScopeForApiEnforcement().
WriteProtectedPointerHeaderSlot() [1/2]
template<typename T , size_t offset>
void v8::internal::WritableJitAllocation::WriteProtectedPointerHeaderSlot (Tagged< T > value, RelaxedStoreTag) [inline]
Definition at line 174 of file code-memory-access-inl.h.
                                                                             {
  static_assert(offset != HeapObject::kMapOffset);
  std::optional<RwxMemoryWriteScope> write_scope =
      WriteScopeForApiEnforcement();
  TaggedField<T, offset, TrustedSpaceCompressionScheme>::Relaxed_Store(
      HeapObject::FromAddress(address_), value);
}
References address_, v8::internal::HeapObject::FromAddress(), v8::internal::HeapObject::kMapOffset, v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store(), v8::internal::value, and WriteScopeForApiEnforcement().
WriteProtectedPointerHeaderSlot() [2/2]
template<typename T , size_t offset>
void v8::internal::WritableJitAllocation::WriteProtectedPointerHeaderSlot (Tagged< T > value, ReleaseStoreTag) [inline]
Definition at line 184 of file code-memory-access-inl.h.
                                                                             {
  static_assert(offset != HeapObject::kMapOffset);
  std::optional<RwxMemoryWriteScope> write_scope =
      WriteScopeForApiEnforcement();
  TaggedField<T, offset, TrustedSpaceCompressionScheme>::Release_Store(
      HeapObject::FromAddress(address_), value);
}
References address_, v8::internal::HeapObject::FromAddress(), v8::internal::HeapObject::kMapOffset, v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store(), v8::internal::value, and WriteScopeForApiEnforcement().
Referenced by v8::internal::InstructionStream::Finalize(), v8::internal::InstructionStream::Initialize(), and WriteHeaderSlot().
WriteScopeForApiEnforcement()
std::optional< RwxMemoryWriteScope > v8::internal::WritableJitAllocation::WriteScopeForApiEnforcement () const [inline], [private]
Definition at line 89 of file code-memory-access-inl.h.
                                                         {
#ifdef DEBUG
  if (enforce_write_api_) {
    return std::optional<RwxMemoryWriteScope>("WriteScopeForApiEnforcement");
  }
#endif
  return {};
}
References enforce_write_api_.
Referenced by ClearBytes(), CopyCode(), CopyData(), WriteHeaderSlot(), WriteProtectedPointerHeaderSlot(), WriteUnalignedValue(), and WriteValue().
WriteUnalignedValue()
template<typename T >
void v8::internal::WritableJitAllocation::WriteUnalignedValue (Address address, T value) [inline]
Definition at line 216 of file code-memory-access-inl.h.
                                                                   {
  std::optional<RwxMemoryWriteScope> write_scope =
      WriteScopeForApiEnforcement();
  DCHECK_GE(address, address_);
  DCHECK_LT(address - address_, size());
  base::WriteUnalignedValue<T>(address, value);
}
References address(), address_, DCHECK_GE, DCHECK_LT, size(), v8::internal::value, and WriteScopeForApiEnforcement().
Referenced by v8::internal::wasm::JumpTableAssembler::emit(), and v8::internal::Assembler::RelocateInternalReference().
WriteValue() [1/2]
template<typename T >
void v8::internal::WritableJitAllocation::WriteValue (Address address, T value) [inline]
Definition at line 226 of file code-memory-access-inl.h.
                                                                         {
  std::optional<RwxMemoryWriteScope> write_scope =
      WriteScopeForApiEnforcement();
  DCHECK_GE(address, address_);
  DCHECK_LT(address - address_, size());
  base::Memory<T>(address) = value;
}
References address(), address_, DCHECK_GE, DCHECK_LT, size(), v8::internal::value, and WriteScopeForApiEnforcement().
Referenced by v8::internal::WritableRelocInfo::apply(), v8::internal::Assembler::deserialization_set_target_internal_reference_at(), v8::internal::Assembler::set_target_address_at(), v8::internal::Assembler::set_target_compressed_address_at(), and v8::internal::UpdateTypedSlotHelper::UpdateTypedSlot().
WriteValue() [2/2]
template<typename T >
void v8::internal::WritableJitAllocation::WriteValue (Address address, T value, RelaxedStoreTag) [inline]
Definition at line 235 of file code-memory-access-inl.h.
                                                                  {
  std::optional<RwxMemoryWriteScope> write_scope =
      WriteScopeForApiEnforcement();
  DCHECK_GE(address, address_);
  DCHECK_LT(address - address_, size());
  reinterpret_cast<std::atomic<T>*>(address)->store(value,
                                                    std::memory_order_relaxed);
}
References address(), address_, DCHECK_GE, DCHECK_LT, size(), store(), v8::internal::value, and WriteScopeForApiEnforcement().
Friends And Related Function Documentation
ThreadIsolation
friend class ThreadIsolation [friend]
Definition at line 481 of file code-memory-access.h.
WritableJitPage
friend class WritableJitPage [friend]
Definition at line 482 of file code-memory-access.h.
WritableJumpTablePair
friend class WritableJumpTablePair [friend]
Definition at line 483 of file code-memory-access.h.
Member Data Documentation
address_
const Address v8::internal::WritableJitAllocation::address_ [private]
Definition at line 469 of file code-memory-access.h.
Referenced by address(), ClearBytes(), CopyCode(), CopyData(), WriteHeaderSlot(), WriteProtectedPointerHeaderSlot(), WriteUnalignedValue(), and WriteValue().
allocation_
const ThreadIsolation::JitAllocation v8::internal::WritableJitAllocation::allocation_ [private]
Definition at line 478 of file code-memory-access.h.
Referenced by size(), and WriteHeaderSlot().
enforce_write_api_
bool v8::internal::WritableJitAllocation::enforce_write_api_ = false [private]
Definition at line 479 of file code-memory-access.h.
Referenced by WritableJitAllocation(), WriteScopeForApiEnforcement(), and ~WritableJitAllocation().
page_ref_
std::optional<ThreadIsolation::JitPageReference> v8::internal::WritableJitAllocation::page_ref_ [private]
Definition at line 477 of file code-memory-access.h.
Referenced by page_ref(), and ~WritableJitAllocation().
write_scope_
std::optional<RwxMemoryWriteScope> v8::internal::WritableJitAllocation::write_scope_ [private]
Definition at line 476 of file code-memory-access.h.
Referenced by WritableJitAllocation(), and ~WritableJitAllocation().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/code-memory-access.h
/mnt/V8SourceCode/src/common/code-memory-access-inl.h
/mnt/V8SourceCode/src/common/code-memory-access.cc