v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor Class Reference
Static Public Member Functions
static Handle< Object > ConvertArgumentsStoreResult (Isolate *isolate, DirectHandle< SloppyArgumentsElements > parameter_map, Handle< Object > result)
static DirectHandle< FixedArray > GetArguments (Isolate *isolate, Tagged< FixedArrayBase > store)
static DirectHandle< NumberDictionary > NormalizeImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > elements)
static DirectHandle< NumberDictionary > NormalizeArgumentsElements (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< SloppyArgumentsElements > elements, InternalIndex *entry)
static void SloppyDeleteImpl (Isolate *isolate, DirectHandle< JSObject > obj, DirectHandle< SloppyArgumentsElements > elements, InternalIndex entry)
static Maybe< bool > AddImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity)
static void ReconfigureImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes)
static void CopyElementsImpl (Isolate *isolate, Tagged< FixedArrayBase > from, uint32_t from_start, Tagged< FixedArrayBase > to, ElementsKind from_kind, uint32_t to_start, int packed_size, int copy_size)
static Maybe< bool > GrowCapacityAndConvertImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t capacity)
Additional Inherited Members
Detailed Description
Definition at line 5328 of file elements.cc.
Member Function Documentation
AddImpl()
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::AddImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity) [inline], [static]
Definition at line 5381 of file elements.cc.
                                                    {
    DCHECK_EQ(NONE, attributes);
    DirectHandle<SloppyArgumentsElements> elements(
        Cast<SloppyArgumentsElements>(object->elements()), isolate);
    DirectHandle<FixedArray> old_arguments(elements->arguments(), isolate);
    if (IsNumberDictionary(*old_arguments) ||
        static_cast<uint32_t>(old_arguments->length()) < new_capacity) {
      MAYBE_RETURN(GrowCapacityAndConvertImpl(isolate, object, new_capacity),
                   Nothing<bool>());
    }
    Tagged<FixedArray> arguments = elements->arguments();
    // For fast holey objects, the entry equals the index. The code above made
    // sure that there's enough space to store the value. We cannot convert
    // index to entry explicitly since the slot still contains the hole, so the
    // current EntryForIndex would indicate that it is "absent" by returning
    // kMaxUInt32.
    FastHoleyObjectElementsAccessor::SetImpl(arguments, InternalIndex(index),
                                             *value);
    return Just(true);
  }
References DCHECK_EQ, v8::internal::index, v8::Just(), MAYBE_RETURN, v8::internal::NONE, and v8::internal::value.
ConvertArgumentsStoreResult()
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::ConvertArgumentsStoreResult (Isolate * isolate, DirectHandle< SloppyArgumentsElements > parameter_map, Handle< Object > result) [inline], [static]
Definition at line 5333 of file elements.cc.
                             {
    DCHECK(!IsAliasedArgumentsEntry(*result));
    return result;
  }
References v8::internal::DCHECK(), and v8::base::internal::result.
CopyElementsImpl()
static void v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::CopyElementsImpl (Isolate * isolate, Tagged< FixedArrayBase > from, uint32_t from_start, Tagged< FixedArrayBase > to, ElementsKind from_kind, uint32_t to_start, int packed_size, int copy_size) [inline], [static]
Definition at line 5417 of file elements.cc.
                                                               {
    DCHECK(!IsNumberDictionary(to));
    if (from_kind == SLOW_SLOPPY_ARGUMENTS_ELEMENTS) {
      CopyDictionaryToObjectElements(isolate, from, from_start, to,
                                     HOLEY_ELEMENTS, to_start, copy_size);
    } else {
      DCHECK_EQ(FAST_SLOPPY_ARGUMENTS_ELEMENTS, from_kind);
      CopyObjectToObjectElements(isolate, from, HOLEY_ELEMENTS, from_start, to,
                                 HOLEY_ELEMENTS, to_start, copy_size);
    }
  }
References v8::internal::anonymous_namespace{elements.cc}::CopyDictionaryToObjectElements(), v8::internal::anonymous_namespace{elements.cc}::CopyObjectToObjectElements(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::HOLEY_ELEMENTS, and v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS.
GetArguments()
static DirectHandle<FixedArray> v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::GetArguments (Isolate * isolate, Tagged< FixedArrayBase > store) [inline], [static]
Definition at line 5340 of file elements.cc.
                                                                             {
    Tagged<SloppyArgumentsElements> elements =
        Cast<SloppyArgumentsElements>(store);
    return DirectHandle<FixedArray>(elements->arguments(), isolate);
  }
References store().
GrowCapacityAndConvertImpl()
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::GrowCapacityAndConvertImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t capacity) [inline], [static]
Definition at line 5432 of file elements.cc.
                                                                   {
    DirectHandle<SloppyArgumentsElements> elements(
        Cast<SloppyArgumentsElements>(object->elements()), isolate);
    DirectHandle<FixedArray> old_arguments(
        Cast<FixedArray>(elements->arguments()), isolate);
    ElementsKind from_kind = object->GetElementsKind();
    // This method should only be called if there's a reason to update the
    // elements.
    DCHECK(from_kind == SLOW_SLOPPY_ARGUMENTS_ELEMENTS ||
           static_cast<uint32_t>(old_arguments->length()) < capacity);
    DirectHandle<FixedArrayBase> arguments;
    ASSIGN_RETURN_ON_EXCEPTION_VALUE(
        isolate, arguments,
        ConvertElementsWithCapacity(isolate, object, old_arguments, from_kind,
                                    capacity),
        Nothing<bool>());
    DirectHandle<Map> new_map = JSObject::GetElementsTransitionMap(
        isolate, object, FAST_SLOPPY_ARGUMENTS_ELEMENTS);
    JSObject::MigrateToMap(isolate, object, new_map);
    elements->set_arguments(Cast<FixedArray>(*arguments));
    JSObject::ValidateElements(isolate, *object);
    return Just(true);
  }
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::DCHECK(), v8::internal::FAST_SLOPPY_ARGUMENTS_ELEMENTS, v8::internal::JSObject::GetElementsTransitionMap(), v8::Just(), v8::internal::JSObject::MigrateToMap(), v8::internal::SLOW_SLOPPY_ARGUMENTS_ELEMENTS, and v8::internal::JSObject::ValidateElements().
NormalizeArgumentsElements()
static DirectHandle<NumberDictionary> v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::NormalizeArgumentsElements (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< SloppyArgumentsElements > elements, InternalIndex * entry) [inline], [static]
Definition at line 5355 of file elements.cc.
                                                                            {
    DirectHandle<NumberDictionary> dictionary =
        JSObject::NormalizeElements(isolate, object);
    elements->set_arguments(*dictionary);
    // kMaxUInt32 indicates that a context mapped element got deleted. In this
    // case we only normalize the elements (aka. migrate to SLOW_SLOPPY).
    if (entry->is_not_found()) return dictionary;
    uint32_t length = elements->length();
    if (entry->as_uint32() >= length) {
      *entry = dictionary->FindEntry(isolate, entry->as_uint32() - length)
                   .adjust_up(length);
    }
    return dictionary;
  }
References v8::internal::InternalIndex::as_uint32(), v8::internal::InternalIndex::is_not_found(), v8::internal::length, and v8::internal::JSObject::NormalizeElements().
NormalizeImpl()
static DirectHandle<NumberDictionary> v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::NormalizeImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > elements) [inline], [static]
Definition at line 5347 of file elements.cc.
                                             {
    DirectHandle<FixedArray> arguments = GetArguments(isolate, *elements);
    return FastHoleyObjectElementsAccessor::NormalizeImpl(isolate, object,
                                                          arguments);
  }
ReconfigureImpl()
static void v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::ReconfigureImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes) [inline], [static]
Definition at line 5405 of file elements.cc.
                                                             {
    DCHECK_EQ(object->elements(), *store);
    DirectHandle<SloppyArgumentsElements> elements(
        Cast<SloppyArgumentsElements>(*store), isolate);
    NormalizeArgumentsElements(isolate, object, elements, &entry);
    SlowSloppyArgumentsElementsAccessor::ReconfigureImpl(
        isolate, object, store, entry, value, attributes);
  }
References DCHECK_EQ, store(), and v8::internal::value.
SloppyDeleteImpl()
static void v8::internal::anonymous_namespace{elements.cc}::FastSloppyArgumentsElementsAccessor::SloppyDeleteImpl (Isolate * isolate, DirectHandle< JSObject > obj, DirectHandle< SloppyArgumentsElements > elements, InternalIndex entry) [inline], [static]
Definition at line 5372 of file elements.cc.
                                                    {
    // Always normalize element on deleting an entry.
    NormalizeArgumentsElements(isolate, obj, elements, &entry);
    SlowSloppyArgumentsElementsAccessor::SloppyDeleteImpl(isolate, obj,
                                                          elements, entry);
  }
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/elements.cc