v8::internal::wasm::AsyncCompileJob::CompilationStateCallback Class Reference
Public Member Functions
CompilationStateCallback (AsyncCompileJob *job)
void call (CompilationEvent event) override
Private Attributes
AsyncCompileJob * job_
Additional Inherited Members
Detailed Description
Definition at line 2860 of file module-compiler.cc.
Constructor & Destructor Documentation
CompilationStateCallback()
v8::internal::wasm::AsyncCompileJob::CompilationStateCallback::CompilationStateCallback (AsyncCompileJob * job) [inline], [explicit]
Definition at line 2863 of file module-compiler.cc.
: job_(job) {}
Member Function Documentation
call()
void v8::internal::wasm::AsyncCompileJob::CompilationStateCallback::call (CompilationEvent event) [inline], [override], [virtual]
Implements v8::internal::wasm::CompilationEventCallback.
Definition at line 2865 of file module-compiler.cc.
                                             {
    // This callback is only being called from a foreground task.
    switch (event) {
      case CompilationEvent::kFinishedBaselineCompilation:
        DCHECK(!last_event_.has_value());
        if (job_->DecrementAndCheckFinisherCount()) {
          // Install the native module in the cache, or reuse a conflicting one.
          // If we get a conflicting module, wait until we are back in the
          // main thread to update {job_->native_module_} to avoid a data race.
          std::shared_ptr<NativeModule> cached_native_module =
              GetWasmEngine()->UpdateNativeModuleCache(
                  false, job_->native_module_, job_->isolate_);
          if (cached_native_module == job_->native_module_) {
            // There was no cached module.
            cached_native_module = nullptr;
          }
          job_->DoSync<FinishCompilation>(std::move(cached_native_module));
        }
        break;
      case CompilationEvent::kFinishedCompilationChunk:
        DCHECK(CompilationEvent::kFinishedBaselineCompilation == last_event_ ||
               CompilationEvent::kFinishedCompilationChunk == last_event_);
        break;
      case CompilationEvent::kFailedCompilation:
        DCHECK(!last_event_.has_value());
        if (job_->DecrementAndCheckFinisherCount()) {
          // Don't update {job_->native_module_} to avoid data races with other
          // compilation threads. Use a copy of the shared pointer instead.
          GetWasmEngine()->UpdateNativeModuleCache(true, job_->native_module_,
                                                   job_->isolate_);
          job_->DoSync<Fail>();
        }
        break;
    }
#ifdef DEBUG
    last_event_ = event;
#endif
  }
References v8::internal::DCHECK(), v8::internal::wasm::AsyncCompileJob::DecrementAndCheckFinisherCount(), v8::internal::wasm::AsyncCompileJob::DoSync(), v8::internal::wasm::GetWasmEngine(), v8::internal::wasm::AsyncCompileJob::isolate_, job_, v8::internal::wasm::kFailedCompilation, v8::internal::wasm::kFinishedBaselineCompilation, v8::internal::wasm::kFinishedCompilationChunk, v8::internal::wasm::AsyncCompileJob::native_module_, and v8::internal::wasm::WasmEngine::UpdateNativeModuleCache().
Member Data Documentation
job_
AsyncCompileJob* v8::internal::wasm::AsyncCompileJob::CompilationStateCallback::job_ [private]
Definition at line 2905 of file module-compiler.cc.
Referenced by call().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-compiler.cc