v8::internal::FullMarkingVisitorBase< ConcreteVisitor > Class Template Reference
#include <marking-visitor.h>
Public Member Functions
FullMarkingVisitorBase (MarkingWorklists::Local *local_marking_worklists, WeakObjects::Local *local_weak_objects, Heap *heap, unsigned mark_compact_epoch, base::EnumSet< CodeFlushMode > code_flush_mode, bool should_keep_ages_unchanged, uint16_t code_flushing_increase)
void AddStrongReferenceForReferenceSummarizer (Tagged< HeapObject > host, Tagged< HeapObject > obj)
void AddWeakReferenceForReferenceSummarizer (Tagged< HeapObject > host, Tagged< HeapObject > obj)
constexpr bool CanUpdateValuesInHeap ()
MarkingState * marking_state () const
void MarkPointerTableEntry (Tagged< HeapObject > obj, IndirectPointerSlot slot)
Private Attributes
MarkingState * marking_state_
Additional Inherited Members
Detailed Description
template<typename ConcreteVisitor>
class v8::internal::FullMarkingVisitorBase< ConcreteVisitor >
Definition at line 256 of file marking-visitor.h.
Constructor & Destructor Documentation
FullMarkingVisitorBase()
template<typename ConcreteVisitor >
v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::FullMarkingVisitorBase (MarkingWorklists::Local * local_marking_worklists, WeakObjects::Local * local_weak_objects, Heap * heap, unsigned mark_compact_epoch, base::EnumSet< CodeFlushMode > code_flush_mode, bool should_keep_ages_unchanged, uint16_t code_flushing_increase) [inline]
Definition at line 258 of file marking-visitor.h.
      : MarkingVisitorBase<ConcreteVisitor>(
            local_marking_worklists, local_weak_objects, heap,
            mark_compact_epoch, code_flush_mode, should_keep_ages_unchanged,
            code_flushing_increase),
        marking_state_(heap->marking_state()) {}
Member Function Documentation
AddStrongReferenceForReferenceSummarizer()
template<typename ConcreteVisitor >
void v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::AddStrongReferenceForReferenceSummarizer (Tagged< HeapObject > host, Tagged< HeapObject > obj) [inline]
Definition at line 270 of file marking-visitor.h.
                                                       {}
AddWeakReferenceForReferenceSummarizer()
template<typename ConcreteVisitor >
void v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::AddWeakReferenceForReferenceSummarizer (Tagged< HeapObject > host, Tagged< HeapObject > obj) [inline]
Definition at line 273 of file marking-visitor.h.
                                                       {}
CanUpdateValuesInHeap()
template<typename ConcreteVisitor >
constexpr bool v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::CanUpdateValuesInHeap () [inline], [constexpr]
Definition at line 276 of file marking-visitor.h.
{ return true; }
marking_state()
template<typename ConcreteVisitor >
MarkingState* v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::marking_state () const [inline]
Definition at line 278 of file marking-visitor.h.
{ return marking_state_; }
References v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::marking_state_.
MarkPointerTableEntry()
template<typename ConcreteVisitor >
void v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::MarkPointerTableEntry (Tagged< HeapObject > obj, IndirectPointerSlot slot)
Definition at line 894 of file marking-visitor-inl.h.
                                                       {
#ifdef V8_ENABLE_SANDBOX
  IndirectPointerTag tag = slot.tag();
  DCHECK_NE(tag, kUnknownIndirectPointerTag);
  IndirectPointerHandle handle = slot.Relaxed_LoadHandle();
  // We must not see an uninitialized 'self' indirect pointer as we might
  // otherwise fail to mark the table entry as alive.
  DCHECK_NE(handle, kNullIndirectPointerHandle);
  if (tag == kCodeIndirectPointerTag) {
    CodePointerTable* table = IsolateGroup::current()->code_pointer_table();
    CodePointerTable::Space* space = this->heap_->code_pointer_space();
    table->Mark(space, handle);
  } else {
    bool use_shared_table = IsSharedTrustedPointerType(tag);
    DCHECK_EQ(use_shared_table, HeapLayout::InWritableSharedSpace(host));
    TrustedPointerTable* table = use_shared_table
                                     ? this->shared_trusted_pointer_table_
                                     : this->trusted_pointer_table_;
    TrustedPointerTable::Space* space =
        use_shared_table
            ? this->heap_->isolate()->shared_trusted_pointer_space()
            : this->heap_->trusted_pointer_space();
    table->Mark(space, handle);
  }
#else
  UNREACHABLE();
#endif
}
References v8::internal::IsolateGroup::current(), DCHECK_EQ, DCHECK_NE, v8::internal::handle(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::IsSharedTrustedPointerType(), v8::internal::kNullIndirectPointerHandle, v8::internal::kUnknownIndirectPointerTag, v8::internal::IndirectPointerSlot::Relaxed_LoadHandle(), space, v8::internal::IndirectPointerSlot::tag(), and v8::internal::UNREACHABLE().
Member Data Documentation
marking_state_
template<typename ConcreteVisitor >
MarkingState* v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::marking_state_ [private]
Definition at line 283 of file marking-visitor.h.
Referenced by v8::internal::FullMarkingVisitorBase< ConcreteVisitor >::marking_state().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/marking-visitor.h
/mnt/V8SourceCode/src/heap/marking-visitor-inl.h