cppgc::internal::PageMemoryRegionTree Class Reference
#include <page-memory.h>
Public Member Functions
PageMemoryRegionTree ()
~PageMemoryRegionTree ()
void Add (PageMemoryRegion *)
void Remove (PageMemoryRegion *)
PageMemoryRegion * Lookup (ConstAddress) const
Private Attributes
std::map< ConstAddress, PageMemoryRegion * > set_
Detailed Description
Definition at line 80 of file page-memory.h.
Constructor & Destructor Documentation
PageMemoryRegionTree()
cppgc::internal::PageMemoryRegionTree::PageMemoryRegionTree () [default]
 PageMemoryRegionTree()
cppgc::internal::PageMemoryRegionTree::~PageMemoryRegionTree () [default]
Member Function Documentation
Add()
void cppgc::internal::PageMemoryRegionTree::Add (PageMemoryRegion * region)
Definition at line 101 of file page-memory.cc.
                                                       {
  DCHECK(region);
  const auto result = set_.emplace(region->region().base(), region);
  USE(result);
  DCHECK(result.second);
}
References cppgc::internal::MemoryRegion::base(), DCHECK, cppgc::internal::PageMemoryRegion::region(), v8::base::internal::result, set_, and USE.
Referenced by cppgc::internal::PageBackend::TryAllocateLargePageMemory(), and cppgc::internal::PageBackend::TryAllocateNormalPageMemory().
Lookup()
PageMemoryRegion * cppgc::internal::PageMemoryRegionTree::Lookup (ConstAddress address) const [inline]
Definition at line 195 of file page-memory.h.
                                                                         {
  auto it = set_.upper_bound(address);
  // This check also covers set_.size() > 0, since for empty container it is
  // guaranteed that begin() == end().
  if (it == set_.begin()) {
    return nullptr;
  }
  auto* result = std::next(it, -1)->second;
  if (address < result->region().end()) {
    return result;
  }
  return nullptr;
}
References v8::internal::compiler::end(), v8::base::internal::result, and set_.
Referenced by cppgc::internal::PageBackend::FreeLargePageMemory(), cppgc::internal::PageBackend::FreeNormalPageMemory(), and cppgc::internal::PageBackend::Lookup().
Remove()
void cppgc::internal::PageMemoryRegionTree::Remove (PageMemoryRegion * region)
Definition at line 108 of file page-memory.cc.
                                                          {
  DCHECK(region);
  const auto size = set_.erase(region->region().base());
  USE(size);
  DCHECK_EQ(1u, size);
}
References cppgc::internal::MemoryRegion::base(), DCHECK, DCHECK_EQ, cppgc::internal::PageMemoryRegion::region(), set_, size(), and USE.
Referenced by cppgc::internal::PageBackend::FreeLargePageMemory(), and cppgc::internal::PageBackend::FreeNormalPageMemory().
Member Data Documentation
set_
std::map<ConstAddress, PageMemoryRegion*> cppgc::internal::PageMemoryRegionTree::set_ [private]
Definition at line 91 of file page-memory.h.
Referenced by Add(), Lookup(), and Remove().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/page-memory.h
/mnt/V8SourceCode/src/heap/cppgc/page-memory.cc