v8::internal::torque::KytheConsumer Class Reference
#include <kythe-data.h>
Public Types
enum class Kind {
Unspecified
, Constant
, Function
, ClassField
,
Variable
, Type
 }
Public Member Functions
virtual ~KytheConsumer ()=0
virtual kythe_entity_t AddDefinition (Kind kind, std::string name, KythePosition pos)=0
virtual void AddUse (Kind kind, kythe_entity_t entity, KythePosition use_pos)=0
virtual void AddCall (Kind kind, kythe_entity_t caller_entity, KythePosition call_pos, kythe_entity_t callee_entity)=0
Detailed Description
Definition at line 25 of file kythe-data.h.
Member Enumeration Documentation
Kind
enum v8::internal::torque::KytheConsumer::Kind [strong]
Enumerator
Unspecified
Constant
Function
ClassField
Variable
Type
Definition at line 27 of file kythe-data.h.
                  {
    Unspecified,
    Constant,
    Function,
    ClassField,
    Variable,
    Type,
  };
Constructor & Destructor Documentation
 KytheConsumer()
v8::internal::torque::KytheConsumer::~KytheConsumer () [inline], [pure virtual], [default]
Member Function Documentation
AddCall()
virtual void v8::internal::torque::KytheConsumer::AddCall (Kind kind, kythe_entity_t caller_entity, KythePosition call_pos, kythe_entity_t callee_entity) [pure virtual]
Referenced by v8::internal::torque::KytheData::AddCall().
AddDefinition()
virtual kythe_entity_t v8::internal::torque::KytheConsumer::AddDefinition (Kind kind, std::string name, KythePosition pos) [pure virtual]
Referenced by v8::internal::torque::KytheData::AddBindingDefinitionImpl(), v8::internal::torque::KytheData::AddClassFieldDefinition(), v8::internal::torque::KytheData::AddConstantDefinition(), v8::internal::torque::KytheData::AddFunctionDefinition(), and v8::internal::torque::KytheData::AddTypeDefinition().
AddUse()
virtual void v8::internal::torque::KytheConsumer::AddUse (Kind kind, kythe_entity_t entity, KythePosition use_pos) [pure virtual]
Referenced by v8::internal::torque::KytheData::AddBindingUse(), v8::internal::torque::KytheData::AddClassFieldUse(), v8::internal::torque::KytheData::AddConstantUse(), and v8::internal::torque::KytheData::AddTypeUse().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/kythe-data.h