v8::internal::ArrayIncludesIndexofAssembler Class Reference
Public Types
enum SearchVariant { kIncludes
, kIndexOf
 }
enum class SimpleElementKind { kSmiOrHole
, kAny
 }
Public Member Functions
ArrayIncludesIndexofAssembler (compiler::CodeAssemblerState *state)
void Generate (SearchVariant variant, TNode< IntPtrT > argc, TNode< Context > context)
void GenerateSmiOrObject (SearchVariant variant, TNode< Context > context, TNode< FixedArray > elements, TNode< Object > search_element, TNode< Smi > array_length, TNode< Smi > from_index, SimpleElementKind array_kind)
void GeneratePackedDoubles (SearchVariant variant, TNode< FixedDoubleArray > elements, TNode< Object > search_element, TNode< Smi > array_length, TNode< Smi > from_index)
void GenerateHoleyDoubles (SearchVariant variant, TNode< FixedDoubleArray > elements, TNode< Object > search_element, TNode< Smi > array_length, TNode< Smi > from_index)
void ReturnIfEmpty (TNode< Smi > length, TNode< Object > value)
Private Attributes
const int kSIMDThreshold = 48
const bool kCanVectorize = false
Additional Inherited Members
Detailed Description
Definition at line 672 of file builtins-array-gen.cc.
Member Enumeration Documentation
SearchVariant
enum v8::internal::ArrayIncludesIndexofAssembler::SearchVariant
Enumerator
kIncludes
kIndexOf
Definition at line 677 of file builtins-array-gen.cc.
{ kIncludes, kIndexOf };
SimpleElementKind
enum v8::internal::ArrayIncludesIndexofAssembler::SimpleElementKind [strong]
Enumerator
kSmiOrHole
kAny
Definition at line 679 of file builtins-array-gen.cc.
{ kSmiOrHole, kAny };
Constructor & Destructor Documentation
ArrayIncludesIndexofAssembler()
v8::internal::ArrayIncludesIndexofAssembler::ArrayIncludesIndexofAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 674 of file builtins-array-gen.cc.
      : CodeStubAssembler(state) {}
Member Function Documentation
Generate()
void v8::internal::ArrayIncludesIndexofAssembler::Generate (SearchVariant variant, TNode< IntPtrT > argc, TNode< Context > context)
Definition at line 721 of file builtins-array-gen.cc.
                                                                     {
  const int kSearchElementArg = 0;
  const int kFromIndexArg = 1;
  CodeStubArguments args(this, argc);
  TNode<Object> receiver = args.GetReceiver();
  TNode<Object> search_element =
      args.GetOptionalArgumentValue(kSearchElementArg);
  TNode<IntPtrT> intptr_zero = IntPtrConstant(0);
  Label init_index(this), return_not_found(this), call_runtime(this);
  // Take slow path if not a JSArray, if retrieving elements requires
  // traversing prototype, or if access checks are required.
  BranchIfFastJSArrayForRead(receiver, context, &init_index, &call_runtime);
  BIND(&init_index);
  TVARIABLE(IntPtrT, index_var, intptr_zero);
  TNode<JSArray> array = CAST(receiver);
  // JSArray length is always a positive Smi for fast arrays.
  CSA_DCHECK(this, TaggedIsPositiveSmi(LoadJSArrayLength(array)));
  TNode<Smi> array_length = LoadFastJSArrayLength(array);
  TNode<IntPtrT> array_length_untagged = PositiveSmiUntag(array_length);
  {
    // Initialize fromIndex.
    Label is_smi(this), is_nonsmi(this), done(this);
    // If no fromIndex was passed, default to 0.
    GotoIf(IntPtrLessThanOrEqual(args.GetLengthWithoutReceiver(),
                                 IntPtrConstant(kFromIndexArg)),
           &done);
    TNode<Object> start_from = args.AtIndex(kFromIndexArg);
    // Handle Smis and undefined here and everything else in runtime.
    // We must be very careful with side effects from the ToInteger conversion,
    // as the side effects might render previously checked assumptions about
    // the receiver being a fast JSArray and its length invalid.
    Branch(TaggedIsSmi(start_from), &is_smi, &is_nonsmi);
    BIND(&is_nonsmi);
    {
      GotoIfNot(IsUndefined(start_from), &call_runtime);
      Goto(&done);
    }
    BIND(&is_smi);
    {
      TNode<IntPtrT> intptr_start_from = SmiUntag(CAST(start_from));
      index_var = intptr_start_from;
      GotoIf(IntPtrGreaterThanOrEqual(index_var.value(), intptr_zero), &done);
      // The fromIndex is negative: add it to the array's length.
      index_var = IntPtrAdd(array_length_untagged, index_var.value());
      // Clamp negative results at zero.
      GotoIf(IntPtrGreaterThanOrEqual(index_var.value(), intptr_zero), &done);
      index_var = intptr_zero;
      Goto(&done);
    }
    BIND(&done);
  }
  // Fail early if startIndex >= array.length.
  GotoIf(IntPtrGreaterThanOrEqual(index_var.value(), array_length_untagged),
         &return_not_found);
  Label if_smi(this), if_smiorobjects(this), if_packed_doubles(this),
      if_holey_doubles(this);
  TNode<Int32T> elements_kind = LoadElementsKind(array);
  TNode<FixedArrayBase> elements = LoadElements(array);
  static_assert(PACKED_SMI_ELEMENTS == 0);
  static_assert(HOLEY_SMI_ELEMENTS == 1);
  static_assert(PACKED_ELEMENTS == 2);
  static_assert(HOLEY_ELEMENTS == 3);
  GotoIf(IsElementsKindLessThanOrEqual(elements_kind, HOLEY_SMI_ELEMENTS),
         &if_smi);
  GotoIf(IsElementsKindLessThanOrEqual(elements_kind, HOLEY_ELEMENTS),
         &if_smiorobjects);
  GotoIf(
      ElementsKindEqual(elements_kind, Int32Constant(PACKED_DOUBLE_ELEMENTS)),
      &if_packed_doubles);
  GotoIf(ElementsKindEqual(elements_kind, Int32Constant(HOLEY_DOUBLE_ELEMENTS)),
         &if_holey_doubles);
  GotoIf(IsElementsKindLessThanOrEqual(elements_kind,
                                       LAST_ANY_NONEXTENSIBLE_ELEMENTS_KIND),
         &if_smiorobjects);
  Goto(&return_not_found);
  BIND(&if_smi);
  {
    Builtin builtin = (variant == kIncludes) ? Builtin::kArrayIncludesSmi
                                             : Builtin::kArrayIndexOfSmi;
    TNode<JSAny> result =
        CallBuiltin<JSAny>(builtin, context, elements, search_element,
                           array_length, SmiTag(index_var.value()));
    args.PopAndReturn(result);
  }
  BIND(&if_smiorobjects);
  {
    Builtin builtin = (variant == kIncludes)
                          ? Builtin::kArrayIncludesSmiOrObject
                          : Builtin::kArrayIndexOfSmiOrObject;
    TNode<JSAny> result =
        CallBuiltin<JSAny>(builtin, context, elements, search_element,
                           array_length, SmiTag(index_var.value()));
    args.PopAndReturn(result);
  }
  BIND(&if_packed_doubles);
  {
    Builtin builtin = (variant == kIncludes)
                          ? Builtin::kArrayIncludesPackedDoubles
                          : Builtin::kArrayIndexOfPackedDoubles;
    TNode<JSAny> result =
        CallBuiltin<JSAny>(builtin, context, elements, search_element,
                           array_length, SmiTag(index_var.value()));
    args.PopAndReturn(result);
  }
  BIND(&if_holey_doubles);
  {
    Builtin builtin = (variant == kIncludes)
                          ? Builtin::kArrayIncludesHoleyDoubles
                          : Builtin::kArrayIndexOfHoleyDoubles;
    TNode<JSAny> result =
        CallBuiltin<JSAny>(builtin, context, elements, search_element,
                           array_length, SmiTag(index_var.value()));
    args.PopAndReturn(result);
  }
  BIND(&return_not_found);
  if (variant == kIncludes) {
    args.PopAndReturn(FalseConstant());
  } else {
    args.PopAndReturn(NumberConstant(-1));
  }
  BIND(&call_runtime);
  {
    TNode<Object> start_from = args.GetOptionalArgumentValue(kFromIndexArg);
    Runtime::FunctionId function = variant == kIncludes
                                       ? Runtime::kArrayIncludes_Slow
                                       : Runtime::kArrayIndexOf;
    args.PopAndReturn(CallRuntime<JSAny>(function, context, array,
                                         search_element, start_from));
  }
}
References v8::base::args, v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::builtin(), CAST, v8::internal::CodeStubAssembler::ElementsKindEqual(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::IntPtrGreaterThanOrEqual, v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThanOrEqual(), v8::internal::CodeStubAssembler::IsElementsKindLessThanOrEqual(), kIncludes, v8::internal::LAST_ANY_NONEXTENSIBLE_ELEMENTS_KIND, v8::internal::CodeStubAssembler::LoadElements(), v8::internal::CodeStubAssembler::LoadElementsKind(), v8::internal::CodeStubAssembler::LoadFastJSArrayLength(), v8::internal::compiler::CodeAssembler::NumberConstant(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::base::internal::result, v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::SmiUntag(), v8::internal::CodeStubAssembler::TaggedIsPositiveSmi(), and v8::internal::CodeStubAssembler::TaggedIsSmi().
GenerateHoleyDoubles()
void v8::internal::ArrayIncludesIndexofAssembler::GenerateHoleyDoubles (SearchVariant variant, TNode< FixedDoubleArray > elements, TNode< Object > search_element, TNode< Smi > array_length, TNode< Smi > from_index)
Definition at line 1190 of file builtins-array-gen.cc.
                           {
  TVARIABLE(IntPtrT, index_var, SmiUntag(from_index));
  TNode<IntPtrT> array_length_untagged = PositiveSmiUntag(array_length);
  Label nan_loop(this, &index_var), not_nan_case(this),
      not_nan_loop(this, &index_var), hole_loop(this, &index_var),
      search_notnan(this), return_found(this), return_not_found(this);
  TVARIABLE(Float64T, search_num);
  search_num = Float64Constant(0);
  GotoIfNot(TaggedIsSmi(search_element), &search_notnan);
  search_num = SmiToFloat64(CAST(search_element));
  Goto(&not_nan_case);
  BIND(&search_notnan);
  if (variant == kIncludes || V8_EXPERIMENTAL_UNDEFINED_DOUBLE_BOOL) {
    GotoIf(IsUndefined(search_element), &hole_loop);
  }
  GotoIfNot(IsHeapNumber(CAST(search_element)), &return_not_found);
  search_num = LoadHeapNumberValue(CAST(search_element));
  Label* nan_handling = variant == kIncludes ? &nan_loop : &return_not_found;
  BranchIfFloat64IsNaN(search_num.value(), nan_handling, &not_nan_case);
  BIND(&not_nan_case);
  // Use UniqueInt32Constant instead of BoolConstant here in order to ensure
  // that the graph structure does not depend on the value of the predicate
  // (BoolConstant uses cached nodes).
  GotoIfNot(UniqueInt32Constant(kCanVectorize), &not_nan_loop);
  {
    Label simd_call(this);
    Branch(
        UintPtrLessThan(array_length_untagged, IntPtrConstant(kSIMDThreshold)),
        &not_nan_loop, &simd_call);
    BIND(&simd_call);
    TNode<ExternalReference> simd_function =
        ExternalConstant(ExternalReference::array_indexof_includes_double());
    TNode<IntPtrT> result = UncheckedCast<IntPtrT>(CallCFunction(
        simd_function, MachineType::UintPtr(),
        std::make_pair(MachineType::TaggedPointer(), elements),
        std::make_pair(MachineType::UintPtr(), array_length_untagged),
        std::make_pair(MachineType::UintPtr(), index_var.value()),
        std::make_pair(MachineType::TaggedPointer(), search_element)));
    index_var = ReinterpretCast<IntPtrT>(result);
    Branch(IntPtrLessThan(index_var.value(), IntPtrConstant(0)),
           &return_not_found, &return_found);
  }
  BIND(&not_nan_loop);
  {
    Label continue_loop(this);
    GotoIfNot(UintPtrLessThan(index_var.value(), array_length_untagged),
              &return_not_found);
    // No need for hole checking here; the following Float64Equal will
    // return 'not equal' for holes anyway.
    TNode<Float64T> element_k = LoadFixedDoubleArrayElement(
        elements, index_var.value(), nullptr, nullptr);
    Branch(Float64Equal(element_k, search_num.value()), &return_found,
           &continue_loop);
    BIND(&continue_loop);
    Increment(&index_var);
    Goto(&not_nan_loop);
  }
  // Array.p.includes uses SameValueZero comparisons, where NaN == NaN.
  if (variant == kIncludes) {
    BIND(&nan_loop);
    Label continue_loop(this);
    GotoIfNot(UintPtrLessThan(index_var.value(), array_length_untagged),
              &return_not_found);
    // Load double value or continue if it's the hole NaN.
    TNode<Float64T> element_k = LoadFixedDoubleArrayElement(
        elements, index_var.value(), &continue_loop, &continue_loop);
    BranchIfFloat64IsNaN(element_k, &return_found, &continue_loop);
    BIND(&continue_loop);
    Increment(&index_var);
    Goto(&nan_loop);
  }
  // Array.p.includes treats the hole as undefined.
  if (variant == kIncludes || V8_EXPERIMENTAL_UNDEFINED_DOUBLE_BOOL) {
    BIND(&hole_loop);
    GotoIfNot(UintPtrLessThan(index_var.value(), array_length_untagged),
              &return_not_found);
    // Try to find undefined. If we find an explicit double encoded undefined,
    // go to `return_found`. For double holes, go to `return_found` only if we
    // check for existance of undefined. When computing the index, holes are
    // ignored (we don't pass a label).
    LoadFixedDoubleArrayElement(
        elements, index_var.value(), &return_found,
        (variant == kIncludes ? &return_found : nullptr), MachineType::None());
    Increment(&index_var);
    Goto(&hole_loop);
  }
  BIND(&return_found);
  if (variant == kIncludes) {
    Return(TrueConstant());
  } else {
    Return(SmiTag(index_var.value()));
  }
  BIND(&return_not_found);
  if (variant == kIncludes) {
    Return(FalseConstant());
  } else {
    Return(NumberConstant(-1));
  }
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::CodeStubAssembler::BranchIfFloat64IsNaN(), v8::internal::compiler::CodeAssembler::CallCFunction(), CAST, v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Float64Constant(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::Increment(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThan(), kCanVectorize, kIncludes, kSIMDThreshold, v8::internal::CodeStubAssembler::LoadFixedDoubleArrayElement(), v8::internal::CodeStubAssembler::LoadHeapNumberValue(), v8::internal::MachineType::None(), v8::internal::compiler::CodeAssembler::NumberConstant(), v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::base::internal::result, v8::internal::compiler::CodeAssembler::Return(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::SmiToFloat64(), v8::internal::CodeStubAssembler::SmiUntag(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::MachineType::TaggedPointer(), v8::internal::MachineType::UintPtr(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan(), v8::internal::compiler::CodeAssembler::UniqueInt32Constant(), and V8_EXPERIMENTAL_UNDEFINED_DOUBLE_BOOL.
GeneratePackedDoubles()
void v8::internal::ArrayIncludesIndexofAssembler::GeneratePackedDoubles (SearchVariant variant, TNode< FixedDoubleArray > elements, TNode< Object > search_element, TNode< Smi > array_length, TNode< Smi > from_index)
Definition at line 1098 of file builtins-array-gen.cc.
                           {
  TVARIABLE(IntPtrT, index_var, SmiUntag(from_index));
  TNode<IntPtrT> array_length_untagged = PositiveSmiUntag(array_length);
  Label nan_loop(this, &index_var), not_nan_case(this),
      not_nan_loop(this, &index_var), hole_loop(this, &index_var),
      search_notnan(this), return_found(this), return_not_found(this);
  TVARIABLE(Float64T, search_num);
  search_num = Float64Constant(0);
  GotoIfNot(TaggedIsSmi(search_element), &search_notnan);
  search_num = SmiToFloat64(CAST(search_element));
  Goto(&not_nan_case);
  BIND(&search_notnan);
  GotoIfNot(IsHeapNumber(CAST(search_element)), &return_not_found);
  search_num = LoadHeapNumberValue(CAST(search_element));
  Label* nan_handling = variant == kIncludes ? &nan_loop : &return_not_found;
  BranchIfFloat64IsNaN(search_num.value(), nan_handling, &not_nan_case);
  BIND(&not_nan_case);
  // Use UniqueInt32Constant instead of BoolConstant here in order to ensure
  // that the graph structure does not depend on the value of the predicate
  // (BoolConstant uses cached nodes).
  GotoIfNot(UniqueInt32Constant(kCanVectorize), &not_nan_loop);
  {
    Label simd_call(this);
    Branch(
        UintPtrLessThan(array_length_untagged, IntPtrConstant(kSIMDThreshold)),
        &not_nan_loop, &simd_call);
    BIND(&simd_call);
    TNode<ExternalReference> simd_function =
        ExternalConstant(ExternalReference::array_indexof_includes_double());
    TNode<IntPtrT> result = UncheckedCast<IntPtrT>(CallCFunction(
        simd_function, MachineType::UintPtr(),
        std::make_pair(MachineType::TaggedPointer(), elements),
        std::make_pair(MachineType::UintPtr(), array_length_untagged),
        std::make_pair(MachineType::UintPtr(), index_var.value()),
        std::make_pair(MachineType::TaggedPointer(), search_element)));
    index_var = ReinterpretCast<IntPtrT>(result);
    Branch(IntPtrLessThan(index_var.value(), IntPtrConstant(0)),
           &return_not_found, &return_found);
  }
  BIND(&not_nan_loop);
  {
    Label continue_loop(this);
    GotoIfNot(UintPtrLessThan(index_var.value(), array_length_untagged),
              &return_not_found);
    TNode<Float64T> element_k = LoadFixedDoubleArrayElement(
        elements, index_var.value(), nullptr, nullptr);
    Branch(Float64Equal(element_k, search_num.value()), &return_found,
           &continue_loop);
    BIND(&continue_loop);
    Increment(&index_var);
    Goto(&not_nan_loop);
  }
  // Array.p.includes uses SameValueZero comparisons, where NaN == NaN.
  if (variant == kIncludes) {
    BIND(&nan_loop);
    Label continue_loop(this);
    GotoIfNot(UintPtrLessThan(index_var.value(), array_length_untagged),
              &return_not_found);
    TNode<Float64T> element_k = LoadFixedDoubleArrayElement(
        elements, index_var.value(), nullptr, nullptr);
    BranchIfFloat64IsNaN(element_k, &return_found, &continue_loop);
    BIND(&continue_loop);
    Increment(&index_var);
    Goto(&nan_loop);
  }
  BIND(&return_found);
  if (variant == kIncludes) {
    Return(TrueConstant());
  } else {
    Return(SmiTag(index_var.value()));
  }
  BIND(&return_not_found);
  if (variant == kIncludes) {
    Return(FalseConstant());
  } else {
    Return(NumberConstant(-1));
  }
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::CodeStubAssembler::BranchIfFloat64IsNaN(), v8::internal::compiler::CodeAssembler::CallCFunction(), CAST, v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Float64Constant(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::Increment(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThan(), kCanVectorize, kIncludes, kSIMDThreshold, v8::internal::CodeStubAssembler::LoadFixedDoubleArrayElement(), v8::internal::CodeStubAssembler::LoadHeapNumberValue(), v8::internal::compiler::CodeAssembler::NumberConstant(), v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::base::internal::result, v8::internal::compiler::CodeAssembler::Return(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::SmiToFloat64(), v8::internal::CodeStubAssembler::SmiUntag(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::MachineType::TaggedPointer(), v8::internal::MachineType::UintPtr(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan(), and v8::internal::compiler::CodeAssembler::UniqueInt32Constant().
GenerateSmiOrObject()
void v8::internal::ArrayIncludesIndexofAssembler::GenerateSmiOrObject (SearchVariant variant, TNode< Context > context, TNode< FixedArray > elements, TNode< Object > search_element, TNode< Smi > array_length, TNode< Smi > from_index, SimpleElementKind array_kind)
Definition at line 875 of file builtins-array-gen.cc.
                                                         {
  TVARIABLE(IntPtrT, index_var, SmiUntag(from_index));
  TVARIABLE(Float64T, search_num);
  TNode<IntPtrT> array_length_untagged = PositiveSmiUntag(array_length);
  Label ident_loop(this, &index_var), heap_num_loop(this, &search_num),
      string_loop(this), bigint_loop(this, &index_var),
      undef_loop(this, &index_var), not_smi(this), not_heap_num(this),
      return_found(this), return_not_found(this);
  GotoIfNot(TaggedIsSmi(search_element), &not_smi);
  search_num = SmiToFloat64(CAST(search_element));
  Goto(&heap_num_loop);
  BIND(&not_smi);
  if (variant == kIncludes) {
    GotoIf(IsUndefined(search_element), &undef_loop);
  }
  TNode<Map> map = LoadMap(CAST(search_element));
  GotoIfNot(IsHeapNumberMap(map), &not_heap_num);
  search_num = LoadHeapNumberValue(CAST(search_element));
  Goto(&heap_num_loop);
  BIND(&not_heap_num);
  TNode<Uint16T> search_type = LoadMapInstanceType(map);
  GotoIf(IsStringInstanceType(search_type), &string_loop);
  GotoIf(IsBigIntInstanceType(search_type), &bigint_loop);
  // Use UniqueInt32Constant instead of BoolConstant here in order to ensure
  // that the graph structure does not depend on the value of the predicate
  // (BoolConstant uses cached nodes).
  GotoIfNot(UniqueInt32Constant(kCanVectorize), &ident_loop);
  {
    Label simd_call(this);
    Branch(
        UintPtrLessThan(array_length_untagged, IntPtrConstant(kSIMDThreshold)),
        &ident_loop, &simd_call);
    BIND(&simd_call);
    TNode<ExternalReference> simd_function = ExternalConstant(
        ExternalReference::array_indexof_includes_smi_or_object());
    TNode<IntPtrT> result = UncheckedCast<IntPtrT>(CallCFunction(
        simd_function, MachineType::UintPtr(),
        std::make_pair(MachineType::TaggedPointer(), elements),
        std::make_pair(MachineType::UintPtr(), array_length_untagged),
        std::make_pair(MachineType::UintPtr(), index_var.value()),
        std::make_pair(MachineType::TaggedPointer(), search_element)));
    index_var = ReinterpretCast<IntPtrT>(result);
    Branch(IntPtrLessThan(index_var.value(), IntPtrConstant(0)),
           &return_not_found, &return_found);
  }
  BIND(&ident_loop);
  {
    GotoIfNot(UintPtrLessThan(index_var.value(), array_length_untagged),
              &return_not_found);
    TNode<Object> element_k =
        UnsafeLoadFixedArrayElement(elements, index_var.value());
    GotoIf(TaggedEqual(element_k, search_element), &return_found);
    Increment(&index_var);
    Goto(&ident_loop);
  }
  if (variant == kIncludes) {
    BIND(&undef_loop);
    GotoIfNot(UintPtrLessThan(index_var.value(), array_length_untagged),
              &return_not_found);
    TNode<Object> element_k =
        UnsafeLoadFixedArrayElement(elements, index_var.value());
    GotoIf(IsUndefined(element_k), &return_found);
    GotoIf(IsTheHole(element_k), &return_found);
    Increment(&index_var);
    Goto(&undef_loop);
  }
  BIND(&heap_num_loop);
  {
    Label nan_loop(this, &index_var), not_nan_loop(this, &index_var);
    Label* nan_handling = variant == kIncludes ? &nan_loop : &return_not_found;
    GotoIfNot(Float64Equal(search_num.value(), search_num.value()),
              nan_handling);
    // Use UniqueInt32Constant instead of BoolConstant here in order to ensure
    // that the graph structure does not depend on the value of the predicate
    // (BoolConstant uses cached nodes).
    GotoIfNot(UniqueInt32Constant(kCanVectorize &&
                                  array_kind == SimpleElementKind::kSmiOrHole),
              &not_nan_loop);
    {
      Label smi_check(this), simd_call(this);
      Branch(UintPtrLessThan(array_length_untagged,
                             IntPtrConstant(kSIMDThreshold)),
             &not_nan_loop, &smi_check);
      BIND(&smi_check);
      Branch(TaggedIsSmi(search_element), &simd_call, &not_nan_loop);
      BIND(&simd_call);
      TNode<ExternalReference> simd_function = ExternalConstant(
          ExternalReference::array_indexof_includes_smi_or_object());
      TNode<IntPtrT> result = UncheckedCast<IntPtrT>(CallCFunction(
          simd_function, MachineType::UintPtr(),
          std::make_pair(MachineType::TaggedPointer(), elements),
          std::make_pair(MachineType::UintPtr(), array_length_untagged),
          std::make_pair(MachineType::UintPtr(), index_var.value()),
          std::make_pair(MachineType::TaggedPointer(), search_element)));
      index_var = ReinterpretCast<IntPtrT>(result);
      Branch(IntPtrLessThan(index_var.value(), IntPtrConstant(0)),
             &return_not_found, &return_found);
    }
    BIND(&not_nan_loop);
    {
      Label continue_loop(this), element_k_not_smi(this);
      GotoIfNot(UintPtrLessThan(index_var.value(), array_length_untagged),
                &return_not_found);
      TNode<Object> element_k =
          UnsafeLoadFixedArrayElement(elements, index_var.value());
      GotoIfNot(TaggedIsSmi(element_k), &element_k_not_smi);
      Branch(Float64Equal(search_num.value(), SmiToFloat64(CAST(element_k))),
             &return_found, &continue_loop);
      BIND(&element_k_not_smi);
      GotoIfNot(IsHeapNumber(CAST(element_k)), &continue_loop);
      Branch(Float64Equal(search_num.value(),
                          LoadHeapNumberValue(CAST(element_k))),
             &return_found, &continue_loop);
      BIND(&continue_loop);
      Increment(&index_var);
      Goto(&not_nan_loop);
    }
    // Array.p.includes uses SameValueZero comparisons, where NaN == NaN.
    if (variant == kIncludes) {
      BIND(&nan_loop);
      Label continue_loop(this);
      GotoIfNot(UintPtrLessThan(index_var.value(), array_length_untagged),
                &return_not_found);
      TNode<Object> element_k =
          UnsafeLoadFixedArrayElement(elements, index_var.value());
      GotoIf(TaggedIsSmi(element_k), &continue_loop);
      GotoIfNot(IsHeapNumber(CAST(element_k)), &continue_loop);
      BranchIfFloat64IsNaN(LoadHeapNumberValue(CAST(element_k)), &return_found,
                           &continue_loop);
      BIND(&continue_loop);
      Increment(&index_var);
      Goto(&nan_loop);
    }
  }
  BIND(&string_loop);
  {
    TNode<String> search_element_string = CAST(search_element);
    Label continue_loop(this), next_iteration(this, &index_var),
        slow_compare(this), runtime(this, Label::kDeferred);
    TNode<IntPtrT> search_length =
        LoadStringLengthAsWord(search_element_string);
    Goto(&next_iteration);
    BIND(&next_iteration);
    GotoIfNot(UintPtrLessThan(index_var.value(), array_length_untagged),
              &return_not_found);
    TNode<Object> element_k =
        UnsafeLoadFixedArrayElement(elements, index_var.value());
    GotoIf(TaggedIsSmi(element_k), &continue_loop);
    GotoIf(TaggedEqual(search_element_string, element_k), &return_found);
    TNode<Uint16T> element_k_type = LoadInstanceType(CAST(element_k));
    GotoIfNot(IsStringInstanceType(element_k_type), &continue_loop);
    Branch(IntPtrEqual(search_length, LoadStringLengthAsWord(CAST(element_k))),
           &slow_compare, &continue_loop);
    BIND(&slow_compare);
    StringBuiltinsAssembler string_asm(state());
    string_asm.StringEqual_Core(search_element_string, search_type,
                                CAST(element_k), element_k_type, search_length,
                                &return_found, &continue_loop, &runtime);
    BIND(&runtime);
    TNode<Object> result = CallRuntime(Runtime::kStringEqual, context,
                                       search_element_string, element_k);
    Branch(TaggedEqual(result, TrueConstant()), &return_found, &continue_loop);
    BIND(&continue_loop);
    Increment(&index_var);
    Goto(&next_iteration);
  }
  BIND(&bigint_loop);
  {
    GotoIfNot(UintPtrLessThan(index_var.value(), array_length_untagged),
              &return_not_found);
    TNode<Object> element_k =
        UnsafeLoadFixedArrayElement(elements, index_var.value());
    Label continue_loop(this);
    GotoIf(TaggedIsSmi(element_k), &continue_loop);
    GotoIfNot(IsBigInt(CAST(element_k)), &continue_loop);
    TNode<Object> result = CallRuntime(Runtime::kBigIntEqualToBigInt, context,
                                       search_element, element_k);
    Branch(TaggedEqual(result, TrueConstant()), &return_found, &continue_loop);
    BIND(&continue_loop);
    Increment(&index_var);
    Goto(&bigint_loop);
  }
  BIND(&return_found);
  if (variant == kIncludes) {
    Return(TrueConstant());
  } else {
    Return(SmiTag(index_var.value()));
  }
  BIND(&return_not_found);
  if (variant == kIncludes) {
    Return(FalseConstant());
  } else {
    Return(NumberConstant(-1));
  }
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::CodeStubAssembler::BranchIfFloat64IsNaN(), v8::internal::compiler::CodeAssembler::CallCFunction(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::compiler::CodeAssembler::ExternalConstant(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::Increment(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::IntPtrLessThan(), v8::internal::CodeStubAssembler::IsBigInt(), v8::internal::CodeStubAssembler::IsBigIntInstanceType(), v8::internal::CodeStubAssembler::IsStringInstanceType(), kCanVectorize, v8::internal::compiler::CodeAssemblerLabel::kDeferred, kIncludes, kSIMDThreshold, kSmiOrHole, v8::internal::CodeStubAssembler::LoadHeapNumberValue(), v8::internal::CodeStubAssembler::LoadInstanceType(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapInstanceType(), v8::internal::CodeStubAssembler::LoadStringLengthAsWord(), v8::internal::compiler::CodeAssembler::NumberConstant(), v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::base::internal::result, v8::internal::compiler::CodeAssembler::Return(), v8::internal::search_length, v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::SmiToFloat64(), v8::internal::CodeStubAssembler::SmiUntag(), v8::internal::compiler::CodeAssembler::state(), v8::internal::StringBuiltinsAssembler::StringEqual_Core(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::MachineType::TaggedPointer(), v8::internal::MachineType::UintPtr(), v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::UintPtrLessThan(), v8::internal::compiler::CodeAssembler::UniqueInt32Constant(), and v8::internal::CodeStubAssembler::UnsafeLoadFixedArrayElement().
ReturnIfEmpty()
void v8::internal::ArrayIncludesIndexofAssembler::ReturnIfEmpty (TNode< Smi > length, TNode< Object > value) [inline]
Definition at line 697 of file builtins-array-gen.cc.
                                                             {
    Label done(this);
    GotoIf(SmiGreaterThan(length, SmiConstant(0)), &done);
    Return(value);
    BIND(&done);
  }
References v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::length, v8::internal::compiler::CodeAssembler::Return(), v8::internal::compiler::CodeAssembler::SmiConstant(), and v8::internal::value.
Member Data Documentation
kCanVectorize
const bool v8::internal::ArrayIncludesIndexofAssembler::kCanVectorize = false [private]
Definition at line 717 of file builtins-array-gen.cc.
Referenced by GenerateHoleyDoubles(), GeneratePackedDoubles(), and GenerateSmiOrObject().
kSIMDThreshold
const int v8::internal::ArrayIncludesIndexofAssembler::kSIMDThreshold = 48 [private]
Definition at line 707 of file builtins-array-gen.cc.
Referenced by GenerateHoleyDoubles(), GeneratePackedDoubles(), and GenerateSmiOrObject().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-array-gen.cc