v8::sampler::Sampler Class Reference
#include <sampler.h>
Public Member Functions
Sampler (Isolate *isolate)
virtual ~Sampler ()
Isolate * isolate () const
virtual void SampleStack (const v8::RegisterState &regs)=0
void Start ()
void Stop ()
bool IsActive () const
bool ShouldRecordSample ()
void DoSample ()
unsigned js_sample_count () const
unsigned external_sample_count () const
void StartCountingSamples ()
PlatformData * platform_data () const
Static Public Attributes
static const int kMaxFramesCountLog2 = 8
static const unsigned kMaxFramesCount = (1u << kMaxFramesCountLog2) - 1
Protected Member Functions
void SetActive (bool value)
void SetShouldRecordSample ()
DISALLOW_IMPLICIT_CONSTRUCTORS (Sampler)
Protected Attributes
bool is_counting_samples_ = false
unsigned js_sample_count_ = 0
unsigned external_sample_count_ = 0
Isolate * isolate_
std::atomic_bool active_ {false}
std::atomic_bool record_sample_ {false}
std::unique_ptr< PlatformData > data_
Detailed Description
Definition at line 34 of file sampler.h.
Constructor & Destructor Documentation
Sampler()
v8::sampler::Sampler::Sampler (Isolate * isolate) [explicit]
Definition at line 575 of file sampler.cc.
    : isolate_(isolate), data_(std::make_unique<PlatformData>()) {
  // Abseil's deadlock detection uses locks. If we end up taking a sample absl
  // internally holds this lock, we can end up deadlocking.
  SetMutexDeadlockDetectionMode(absl::OnDeadlockCycle::kIgnore);
}
 Sampler()
v8::sampler::Sampler::~Sampler () [virtual]
Definition at line 582 of file sampler.cc.
{ DCHECK(!IsActive()); }
References DCHECK, and IsActive().
Member Function Documentation
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::sampler::Sampler::DISALLOW_IMPLICIT_CONSTRUCTORS (Sampler) [protected]
DoSample()
void v8::sampler::Sampler::DoSample ()
Referenced by v8::internal::SamplingThread::Run().
external_sample_count()
unsigned v8::sampler::Sampler::external_sample_count () const [inline]
Definition at line 67 of file sampler.h.
{ return external_sample_count_; }
IsActive()
bool v8::sampler::Sampler::IsActive () const [inline]
Definition at line 55 of file sampler.h.
{ return active_.load(std::memory_order_relaxed); }
Referenced by v8::internal::Ticker::ClearProfiler(), v8::internal::Isolate::Deinit(), v8::internal::SamplingThread::Run(), v8::internal::Ticker::SetProfiler(), Start(), Stop(), ~Sampler(), and v8::internal::Ticker::~Ticker().
isolate()
Isolate* v8::sampler::Sampler::isolate () const [inline]
Definition at line 43 of file sampler.h.
{ return isolate_; }
Referenced by v8::internal::CpuSampler::SampleStack(), and v8::internal::Ticker::SampleStack().
js_sample_count()
unsigned v8::sampler::Sampler::js_sample_count () const [inline]
Definition at line 66 of file sampler.h.
{ return js_sample_count_; }
platform_data()
PlatformData* v8::sampler::Sampler::platform_data () const [inline]
Definition at line 75 of file sampler.h.
{ return data_.get(); }
SampleStack()
virtual void v8::sampler::Sampler::SampleStack (const v8::RegisterState & regs) [pure virtual]
Implemented in v8::internal::Ticker, and v8::internal::CpuSampler.
SetActive()
void v8::sampler::Sampler::SetActive (bool value) [inline], [protected]
Definition at line 83 of file sampler.h.
                             {
    active_.store(value, std::memory_order_relaxed);
  }
References v8::internal::value.
Referenced by Start(), and Stop().
SetShouldRecordSample()
void v8::sampler::Sampler::SetShouldRecordSample () [inline], [protected]
Definition at line 87 of file sampler.h.
                               {
    record_sample_.store(true, std::memory_order_relaxed);
  }
ShouldRecordSample()
bool v8::sampler::Sampler::ShouldRecordSample () [inline]
Definition at line 59 of file sampler.h.
                            {
    return record_sample_.exchange(false, std::memory_order_relaxed);
  }
Start()
void v8::sampler::Sampler::Start ()
Definition at line 584 of file sampler.cc.
                    {
  DCHECK(!IsActive());
  SetActive(true);
#if defined(USE_SIGNALS)
  SignalHandler::IncreaseSamplerCount();
  SamplerManager::instance()->AddSampler(this);
#endif
}
References DCHECK, IsActive(), and SetActive().
Referenced by v8::internal::Ticker::SetProfiler().
StartCountingSamples()
void v8::sampler::Sampler::StartCountingSamples () [inline]
Definition at line 68 of file sampler.h.
                              {
    js_sample_count_ = 0;
    external_sample_count_ = 0;
    is_counting_samples_ = true;
  }
Stop()
void v8::sampler::Sampler::Stop ()
Definition at line 593 of file sampler.cc.
                   {
#if defined(USE_SIGNALS)
  SamplerManager::instance()->RemoveSampler(this);
  SignalHandler::DecreaseSamplerCount();
#endif
  DCHECK(IsActive());
  SetActive(false);
}
References DCHECK, IsActive(), and SetActive().
Referenced by v8::internal::Ticker::ClearProfiler(), v8::internal::Isolate::Deinit(), and v8::internal::Ticker::~Ticker().
Member Data Documentation
active_
std::atomic_bool v8::sampler::Sampler::active_ {false} [protected]
Definition at line 92 of file sampler.h.
data_
std::unique_ptr<PlatformData> v8::sampler::Sampler::data_ [protected]
Definition at line 94 of file sampler.h.
external_sample_count_
unsigned v8::sampler::Sampler::external_sample_count_ = 0 [protected]
Definition at line 81 of file sampler.h.
Referenced by v8::internal::CpuSampler::SampleStack().
is_counting_samples_
bool v8::sampler::Sampler::is_counting_samples_ = false [protected]
Definition at line 79 of file sampler.h.
Referenced by v8::internal::CpuSampler::SampleStack().
isolate_
Isolate* v8::sampler::Sampler::isolate_ [protected]
Definition at line 91 of file sampler.h.
js_sample_count_
unsigned v8::sampler::Sampler::js_sample_count_ = 0 [protected]
Definition at line 80 of file sampler.h.
Referenced by v8::internal::CpuSampler::SampleStack().
kMaxFramesCount
const unsigned v8::sampler::Sampler::kMaxFramesCount = (1u << kMaxFramesCountLog2) - 1 [static]
Definition at line 37 of file sampler.h.
kMaxFramesCountLog2
const int v8::sampler::Sampler::kMaxFramesCountLog2 = 8 [static]
Definition at line 36 of file sampler.h.
record_sample_
std::atomic_bool v8::sampler::Sampler::record_sample_ {false} [protected]
Definition at line 93 of file sampler.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/libsampler/sampler.h
/mnt/V8SourceCode/src/libsampler/sampler.cc