v8::internal::wasm::CanonicalValueType Class Reference
#include <value-type.h>
Public Member Functions
constexpr CanonicalValueType AsExact (Exactness exact=Exactness::kExact) const
CanonicalValueType AsExactIfEnabled (WasmEnabledFeatures enabled, Exactness exact=Exactness::kExact) const
constexpr CanonicalTypeIndex ref_index () const
constexpr bool operator== (CanonicalValueType other) const
constexpr bool is_equal_except_index (CanonicalValueType other) const
constexpr bool IsFunctionType () const
constexpr HeapType::Representation heap_representation () const
constexpr HeapType::Representation heap_representation_non_shared () const
constexpr bool is_reference_to (HeapType::Representation repr) const
Static Public Member Functions
static constexpr CanonicalValueType Primitive (NumericKind kind)
static constexpr CanonicalValueType Ref (CanonicalTypeIndex index, bool shared, RefTypeKind kind)
static constexpr CanonicalValueType RefNull (CanonicalTypeIndex index, bool shared, RefTypeKind kind)
static constexpr CanonicalValueType RefMaybeNull (CanonicalValueType type, Nullability nullable)
static constexpr CanonicalValueType FromRawBitField (uint32_t bits)
Additional Inherited Members
Detailed Description
Definition at line 1025 of file value-type.h.
Member Function Documentation
AsExact()
constexpr CanonicalValueType v8::internal::wasm::CanonicalValueType::AsExact (Exactness exact = Exactness::kExact) const [inline], [constexpr]
Definition at line 1053 of file value-type.h.
                                               {
    DCHECK(exact == Exactness::kAnySubtype || has_index());
    return CanonicalValueType{ValueTypeBase(
        value_type_impl::IsExactField::update(raw_bit_field(), exact))};
  }
References v8::internal::DCHECK(), v8::internal::wasm::ValueTypeBase::has_index(), v8::internal::wasm::kAnySubtype, v8::internal::wasm::ValueTypeBase::raw_bit_field(), v8::base::BitField< T, shift, size, U >::update(), and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by AsExactIfEnabled().
AsExactIfEnabled()
CanonicalValueType v8::internal::wasm::CanonicalValueType::AsExactIfEnabled (WasmEnabledFeatures enabled, Exactness exact = Exactness::kExact) const [inline]
Definition at line 1062 of file value-type.h.
                                                                            {
    if V8_LIKELY (!enabled.has_custom_descriptors()) return *this;
    return AsExact(exact);
  }
References AsExact(), and V8_LIKELY.
FromRawBitField()
static constexpr CanonicalValueType v8::internal::wasm::CanonicalValueType::FromRawBitField (uint32_t bits) [inline], [static], [constexpr]
Definition at line 1049 of file value-type.h.
                                                                     {
    return CanonicalValueType{ValueTypeBase(bits)};
  }
References v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::WasmTypeInfo::element_type(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::WasmTypeInfo::type().
heap_representation()
constexpr HeapType::Representation v8::internal::wasm::CanonicalValueType::heap_representation () const [inline], [constexpr]
Definition at line 1085 of file value-type.h.
                                                               {
    return static_cast<HeapType::Representation>(raw_heap_representation(true));
  }
References v8::internal::wasm::ValueTypeBase::raw_heap_representation().
Referenced by is_reference_to(), and v8::internal::wasm::JSToWasmObject().
heap_representation_non_shared()
constexpr HeapType::Representation v8::internal::wasm::CanonicalValueType::heap_representation_non_shared () const [inline], [constexpr]
Definition at line 1090 of file value-type.h.
                                                                          {
    return static_cast<HeapType::Representation>(
        raw_heap_representation(false));
  }
References v8::internal::wasm::ValueTypeBase::raw_heap_representation().
Referenced by v8::internal::wasm::JSToWasmObject().
is_equal_except_index()
constexpr bool v8::internal::wasm::CanonicalValueType::is_equal_except_index (CanonicalValueType other) const [inline], [constexpr]
Definition at line 1076 of file value-type.h.
                                                                       {
    return (bit_field_ & ~kIndexBits) == (other.bit_field_ & ~kIndexBits);
  }
References v8::internal::wasm::ValueTypeBase::bit_field_, and v8::internal::wasm::ValueTypeBase::kIndexBits.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualValueType().
is_reference_to()
constexpr bool v8::internal::wasm::CanonicalValueType::is_reference_to (HeapType::Representation repr) const [inline], [constexpr]
Definition at line 1096 of file value-type.h.
                                                                    {
    return is_ref() && heap_representation() == repr;
  }
References heap_representation(), and v8::internal::wasm::ValueTypeBase::is_ref().
IsFunctionType()
constexpr bool v8::internal::wasm::CanonicalValueType::IsFunctionType () const [inline], [constexpr]
Definition at line 1080 of file value-type.h.
                                        {
    return ref_type_kind() == RefTypeKind::kFunction;
  }
References v8::internal::wasm::kFunction, and v8::internal::wasm::ValueTypeBase::ref_type_kind().
Referenced by v8::internal::WasmTableObject::New().
operator==()
constexpr bool v8::internal::wasm::CanonicalValueType::operator== (CanonicalValueType other) const [inline], [constexpr]
Definition at line 1072 of file value-type.h.
                                                            {
    return bit_field_ == other.bit_field_;
  }
References v8::internal::wasm::ValueTypeBase::bit_field_.
Primitive()
static constexpr CanonicalValueType v8::internal::wasm::CanonicalValueType::Primitive (NumericKind kind) [inline], [static], [constexpr]
Definition at line 1027 of file value-type.h.
                                                                  {
    return CanonicalValueType{ValueTypeBase(kind)};
  }
References v8::internal::wasm::ValueTypeBase::kind(), and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup().
Ref()
static constexpr CanonicalValueType v8::internal::wasm::CanonicalValueType::Ref (CanonicalTypeIndex index, bool shared, RefTypeKind kind) [inline], [static], [constexpr]
Definition at line 1030 of file value-type.h.
                                                            {
    return CanonicalValueType{ValueTypeBase(
        index, kNonNullable, Exactness::kAnySubtype, shared, kind)};
  }
References v8::internal::index, v8::internal::wasm::kAnySubtype, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::kNonNullable, and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
Referenced by v8::internal::CreateArrayMap(), v8::internal::CreateFuncRefMap(), and v8::internal::CreateStructMap().
ref_index()
constexpr CanonicalTypeIndex v8::internal::wasm::CanonicalValueType::ref_index () const [inline], [constexpr]
Definition at line 1068 of file value-type.h.
                                                 {
    return CanonicalTypeIndex{raw_index()};
  }
References v8::internal::wasm::ValueTypeBase::raw_index().
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualValueType(), v8::internal::wasm::ConstantExpressionInterface::GetRtt(), v8::internal::wasm::IsSubtypeOfImpl(), v8::internal::wasm::JSToWasmObject(), and v8::internal::WasmTypeInfo::type_index().
RefMaybeNull()
static constexpr CanonicalValueType v8::internal::wasm::CanonicalValueType::RefMaybeNull (CanonicalValueType type, Nullability nullable) [inline], [static], [constexpr]
Definition at line 1042 of file value-type.h.
                                                                         {
    return CanonicalValueType{
        ValueTypeBase(value_type_impl::IsNullableField::update(
            type.raw_bit_field(), nullable))};
  }
References v8::internal::tracing::type, v8::base::BitField< T, shift, size, U >::update(), and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
RefNull()
static constexpr CanonicalValueType v8::internal::wasm::CanonicalValueType::RefNull (CanonicalTypeIndex index, bool shared, RefTypeKind kind) [inline], [static], [constexpr]
Definition at line 1035 of file value-type.h.
                                                                             {
    return CanonicalValueType{
        ValueTypeBase(index, kNullable, Exactness::kAnySubtype, shared, kind)};
  }
References v8::internal::index, v8::internal::wasm::kAnySubtype, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::kNullable, and v8::internal::wasm::ValueTypeBase::ValueTypeBase().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/value-type.h