v8::internal::wasm::Handlers< Compressed > Class Template Reference
Public Member Functions
template<> slot_offset_t Read (const uint8_t *&code)
template<> void push (uint32_t *&sp, const uint8_t *&code, WasmInterpreterRuntime *wasm_runtime, WasmRef ref)
template<> WasmRef pop (uint32_t *&sp, const uint8_t *&code, WasmInterpreterRuntime *wasm_runtime)
template<typename IntT >
INSTRUCTION_HANDLER_FUNC s2r_GlobalGetI (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename FloatT >
INSTRUCTION_HANDLER_FUNC s2r_GlobalGetF (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T >
INSTRUCTION_HANDLER_FUNC s2s_GlobalGet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefGlobalGet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename IntT >
INSTRUCTION_HANDLER_FUNC r2s_GlobalSetI (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename FloatT >
INSTRUCTION_HANDLER_FUNC r2s_GlobalSetF (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T >
INSTRUCTION_HANDLER_FUNC s2s_GlobalSet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefGlobalSet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T >
INSTRUCTION_HANDLER_FUNC r2s_Drop (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_RefDrop (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T >
INSTRUCTION_HANDLER_FUNC s2s_Drop (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefDrop (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename IntT , typename IntU = IntT, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC r2r_LoadMemI (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename FloatT , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC r2r_LoadMemF (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T , typename U = T, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC r2s_LoadMem (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename IntT , typename IntU = IntT, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC s2r_LoadMemI (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename FloatT , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC s2r_LoadMemF (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T , typename U = T, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC s2s_LoadMem (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T , typename U = T, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC s2s_LoadMem_LocalSet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename IntT , typename IntU = IntT, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC r2s_StoreMemI (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename FloatT , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC r2s_StoreMemF (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T , typename U = T, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC s2s_StoreMem (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC r2s_LoadStoreMem (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC s2s_LoadStoreMem (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename IntT >
INSTRUCTION_HANDLER_FUNC r2r_SelectI (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename FloatT >
INSTRUCTION_HANDLER_FUNC r2r_SelectF (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T >
INSTRUCTION_HANDLER_FUNC r2s_Select (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_RefSelect (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename IntT >
INSTRUCTION_HANDLER_FUNC s2r_SelectI (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename FloatT >
INSTRUCTION_HANDLER_FUNC s2r_SelectF (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T >
INSTRUCTION_HANDLER_FUNC s2s_Select (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefSelect (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2r_I32ConvertI64 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_I32ConvertI64 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2r_I32ConvertI64 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_I32ConvertI64 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_MemoryGrow (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Memory64Grow (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_MemorySize (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Memory64Size (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Return (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Branch (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_BranchIf (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_BranchIf (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_BranchIfWithParams (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_BranchIfWithParams (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_If (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_If (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Else (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Catch (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CallFunction (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_ReturnCall (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CallImportedFunction (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_ReturnCallImportedFunction (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CallIndirect (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CallIndirect64 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_ReturnCallIndirect (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_ReturnCallIndirect64 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_BrTable (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_BrTable (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CopySlotMulti (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CopySlot_ll (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CopySlot_lq (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CopySlot_ql (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CopySlot_qq (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CopySlot32 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CopySlot32x2 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CopySlot64 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CopySlot128 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CopySlot64x2 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CopySlotRef (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_PreserveCopySlot32 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_PreserveCopySlot64 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_PreserveCopySlot128 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_CopyR0ToSlot32 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_CopyR0ToSlot64 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_CopyFp0ToSlot32 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_CopyFp0ToSlot64 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_PreserveCopyR0ToSlot32 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_PreserveCopyR0ToSlot64 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_PreserveCopyFp0ToSlot32 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC r2s_PreserveCopyFp0ToSlot64 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefNull (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefIsNull (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefFunc (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefEq (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_MemoryInit (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Memory64Init (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_DataDrop (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_MemoryCopy (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Memory64Copy (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_MemoryFill (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Memory64Fill (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_TableGet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Table64Get (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_TableSet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Table64Set (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_TableInit (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Table64Init (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_ElemDrop (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_TableCopy (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename IntN , typename IntM , typename IntK >
INSTRUCTION_HANDLER_FUNC s2s_Table64CopyImpl (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_TableGrow (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Table64Grow (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_TableSize (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Table64Size (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_TableFill (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Table64Fill (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_OnLoopBegin (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_OnLoopBeginNoRefSlots (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC s2s_AtomicNotify (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC s2s_I32AtomicWait (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC s2s_I64AtomicWait (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_AtomicFence (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
BINOP_CASE (I32x4MinU, i32x4, int32x4, 4, static_cast< uint32_t >(a)< static_cast< uint32_t >(b) ? a :b) BINOP_CASE(I32x4MaxU
static_cast (a) > static_cast< uint32_t >(b) ? a
template<typename MemIdx , typename MemOffsetT >
INSTRUCTION_HANDLER_FUNC s2s_SimdS128StoreMemI (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
SHIFT_CASE (I64x2Shl, i64x2, int64x2, 2, static_cast< uint64_t >(a)<<(shift % 64)) SHIFT_CASE(I64x2ShrU
static_cast (a) >>(shift % 64)) SHIFT_CASE(I32x4Shl
static_cast (a)<<(shift % 32)) SHIFT_CASE(I32x4ShrU
static_cast (a) >>(shift % 32)) SHIFT_CASE(I16x8Shl
static_cast (a)<<(shift % 16)) SHIFT_CASE(I16x8ShrU
static_cast (a) >>(shift % 16)) SHIFT_CASE(I8x16Shl
static_cast (a)<<(shift % 8)) SHIFT_CASE(I8x16ShrU
static_cast (a) >>(shift % 8)) template< typename s_type
uint32_t start INSTRUCTION_HANDLER_FUNC s2s_DoSimdExtMul (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
CONVERT_CASE (F32x4SConvertI32x4, int32x4, i32x4, float32x4, 4, 0, int32_t, static_cast< float >(a)) CONVERT_CASE(F32x4UConvertI32x4
static_cast (a)) CONVERT_CASE(I32x4SConvertF32x4
base::saturated_cast (a)) CONVERT_CASE(I32x4UConvertF32x4
base::saturated_cast (a)) CONVERT_CASE(I32x4RelaxedTruncF32x4S
base::saturated_cast (a)) CONVERT_CASE(I32x4RelaxedTruncF32x4U
base::saturated_cast (a)) CONVERT_CASE(I64x2SConvertI32x4High
a CONVERT_CASE (I64x2UConvertI32x4Low, int32x4, i32x4, int64x2, 2, 0, uint32_t, a) CONVERT_CASE(I64x2UConvertI32x4High
a a CONVERT_CASE (I32x4SConvertI16x8High, int16x8, i16x8, int32x4, 4, 4, int16_t, a) CONVERT_CASE(I32x4UConvertI16x8High
a a a CONVERT_CASE (I32x4UConvertI16x8Low, int16x8, i16x8, int32x4, 4, 0, uint16_t, a) CONVERT_CASE(I16x8UConvertI8x16High
a a a a CONVERT_CASE (F64x2ConvertLowI32x4S, int32x4, i32x4, float64x2, 2, 0, int32_t, static_cast< double >(a)) CONVERT_CASE(F64x2ConvertLowI32x4U
a a a a static_cast (a)) CONVERT_CASE(I32x4TruncSatF64x2SZero
a a a a base::saturated_cast (a)) CONVERT_CASE(I32x4TruncSatF64x2UZero
a a a a base::saturated_cast (a)) CONVERT_CASE(I32x4RelaxedTruncF64x2SZero
a a a a base::saturated_cast (a)) CONVERT_CASE(I32x4RelaxedTruncF64x2UZero
a a a a base::saturated_cast (a)) CONVERT_CASE(F32x4DemoteF64x2Zero
a a a a DoubleToFloat32 (a)) CONVERT_CASE(F64x2PromoteLowF32x4
a a a a static_cast (a)) INSTRUCTION_HANDLER_FUNC s2s_DoSimdSelect(const uint8_t *code
for (size_t i=0;i< 4;++i)
push (sp, code, wasm_runtime, Simd128(res))
NextOp ()
INSTRUCTION_HANDLER_FUNC s2s_SimdI32x4DotI16x8S (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_SimdI16x8DotI8x16I7x16S (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_SimdI32x4DotI8x16I7x16AddS (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_SimdI8x16Swizzle (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_SimdI8x16Shuffle (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_SimdV128AnyTrue (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename s_type , typename load_type , typename MemIdx , typename MemOffsetT >
INSTRUCTION_HANDLER_FUNC s2s_DoSimdLoadSplat (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename s_type , typename wide_type , typename narrow_type , typename MemIdx , typename MemOffsetT >
INSTRUCTION_HANDLER_FUNC s2s_DoSimdLoadExtend (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename s_type , typename load_type , typename MemIdx , typename MemOffsetT >
INSTRUCTION_HANDLER_FUNC s2s_DoSimdLoadZeroExtend (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename s_type , typename memory_type , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC s2s_DoSimdLoadLane (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename s_type , typename memory_type , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC s2s_DoSimdStoreLane (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename DstSimdType , typename SrcSimdType , typename Wide , typename Narrow >
INSTRUCTION_HANDLER_FUNC s2s_DoSimdExtAddPairwise (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Throw (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_Rethrow (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_BranchOnNull (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_BranchOnNullWithParams (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_BranchOnNonNull (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_BranchOnNonNullWithParams (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_BranchOnCast (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_BranchOnCastFail (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_CallRef (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_ReturnCallRef (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_StructNew (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_StructNewDefault (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T , typename U = T>
INSTRUCTION_HANDLER_FUNC s2s_StructGet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefStructGet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T , typename U = T>
INSTRUCTION_HANDLER_FUNC s2s_StructSet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefStructSet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T , typename U = T>
INSTRUCTION_HANDLER_FUNC s2s_ArrayNew (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefArrayNew (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_ArrayNewFixed (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_ArrayNewDefault (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<TrapReason OutOfBoundsError>
INSTRUCTION_HANDLER_FUNC s2s_ArrayNewSegment (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<bool init_data>
INSTRUCTION_HANDLER_FUNC s2s_ArrayInitSegment (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_ArrayLen (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_ArrayCopy (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T , typename U = T>
INSTRUCTION_HANDLER_FUNC s2s_ArrayGet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefArrayGet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T , typename U = T>
INSTRUCTION_HANDLER_FUNC s2s_ArraySet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefArraySet (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<typename T , typename U = T>
INSTRUCTION_HANDLER_FUNC s2s_ArrayFill (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefArrayFill (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefI31 (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_I31GetS (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_I31GetU (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<bool null_succeeds>
INSTRUCTION_HANDLER_FUNC RefCast (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
template<bool null_succeeds>
INSTRUCTION_HANDLER_FUNC RefTest (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_AssertNullTypecheck (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_AssertNotNullTypecheck (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_TrapIllegalCast (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefTestSucceeds (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefTestFails (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefIsNonNull (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_RefAsNonNull (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_AnyConvertExtern (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
INSTRUCTION_HANDLER_FUNC s2s_ExternConvertAny (const uint8_t *code, uint32_t *sp, WasmInterpreterRuntime *wasm_runtime, int64_t r0, double fp0)
Static Public Member Functions
template<typename T >
static T Read (const uint8_t *&code)
template<typename T >
static T JSMax (T x, T y)
template<typename T >
static T JSMin (T x, T y)
static uint8_t * ReadMemoryAddress (uint8_t *&code)
static uint32_t ReadGlobalIndex (const uint8_t *&code)
template<typename T >
static void push (uint32_t *&sp, const uint8_t *&code, WasmInterpreterRuntime *wasm_runtime, T val)
template<typename T >
static T pop (uint32_t *&sp, const uint8_t *&code, WasmInterpreterRuntime *wasm_runtime)
template<typename T >
static T ExecuteRemS (T lval, T rval)
template<typename T >
static T ExecuteRemU (T lval, T rval)
static bool DoRefCast (WasmRef ref, ValueType ref_type, HeapType target_type, bool null_succeeds, WasmInterpreterRuntime *wasm_runtime)
static void StoreRefIntoMemory (Tagged< HeapObject > host, Address dst_addr, uint32_t offset, Tagged< Object > value, WriteBarrierMode mode)
Public Attributes
i32x4
int32x4
i64x2
int64x2
i16x8
int16x8
i8x16
int8x16
d_type
narrow
wide
float32x4
uint32_t
f32x4
float
int32_t
a int32x4
a i32x4
a int64x2
a uint32_t
a a int16x8
a a i16x8
a a int32x4
a a uint16_t
a a a int8x16
a a a i8x16
a a a int16x8
a a a uint8_t
a a a a int32x4
a a a a i32x4
a a a a float64x2
a a a a uint32_t
a a a a f64x2
a a a a double
a a a a float32x4
a a a a float
a a a a f32x4
a a a a uint32_t * sp
a a a a uint32_t WasmInterpreterRuntime * wasm_runtime
a a a a uint32_t WasmInterpreterRuntime int64_t r0
a a a a uint32_t WasmInterpreterRuntime int64_t double fp0
int32x4 v2 = pop<Simd128>(sp, code, wasm_runtime).to_i32x4()
int32x4 v1 = pop<Simd128>(sp, code, wasm_runtime).to_i32x4()
int32x4 res
Static Public Attributes
static constexpr auto s2r_I32GlobalGet = s2r_GlobalGetI<int32_t>
static constexpr auto s2r_I64GlobalGet = s2r_GlobalGetI<int64_t>
static constexpr auto s2r_F32GlobalGet = s2r_GlobalGetF<float>
static constexpr auto s2r_F64GlobalGet = s2r_GlobalGetF<double>
static constexpr auto s2s_I32GlobalGet = s2s_GlobalGet<int32_t>
static constexpr auto s2s_I64GlobalGet = s2s_GlobalGet<int64_t>
static constexpr auto s2s_F32GlobalGet = s2s_GlobalGet<float>
static constexpr auto s2s_F64GlobalGet = s2s_GlobalGet<double>
static constexpr auto s2s_S128GlobalGet = s2s_GlobalGet<Simd128>
static constexpr auto r2s_I32GlobalSet = r2s_GlobalSetI<int32_t>
static constexpr auto r2s_I64GlobalSet = r2s_GlobalSetI<int64_t>
static constexpr auto r2s_F32GlobalSet = r2s_GlobalSetF<float>
static constexpr auto r2s_F64GlobalSet = r2s_GlobalSetF<double>
static constexpr auto s2s_I32GlobalSet = s2s_GlobalSet<int32_t>
static constexpr auto s2s_I64GlobalSet = s2s_GlobalSet<int64_t>
static constexpr auto s2s_F32GlobalSet = s2s_GlobalSet<float>
static constexpr auto s2s_F64GlobalSet = s2s_GlobalSet<double>
static constexpr auto s2s_S128GlobalSet = s2s_GlobalSet<Simd128>
static constexpr auto r2s_I32Drop = r2s_Drop<int32_t>
static constexpr auto r2s_I64Drop = r2s_Drop<int64_t>
static constexpr auto r2s_F32Drop = r2s_Drop<float>
static constexpr auto r2s_F64Drop = r2s_Drop<double>
static constexpr auto s2s_I32Drop = s2s_Drop<int32_t>
static constexpr auto s2s_I64Drop = s2s_Drop<int64_t>
static constexpr auto s2s_F32Drop = s2s_Drop<float>
static constexpr auto s2s_F64Drop = s2s_Drop<double>
static constexpr auto s2s_S128Drop = s2s_Drop<Simd128>
static constexpr auto r2r_I32LoadMem8S_Idx64
static constexpr auto r2r_I32LoadMem8U_Idx64
static constexpr auto r2r_I32LoadMem16S_Idx64
static constexpr auto r2r_I32LoadMem16U_Idx64
static constexpr auto r2r_I64LoadMem8S_Idx64
static constexpr auto r2r_I64LoadMem8U_Idx64
static constexpr auto r2r_I64LoadMem16S_Idx64
static constexpr auto r2r_I64LoadMem16U_Idx64
static constexpr auto r2r_I64LoadMem32S_Idx64
static constexpr auto r2r_I64LoadMem32U_Idx64
static constexpr auto r2r_I32LoadMem_Idx64
static constexpr auto r2r_I64LoadMem_Idx64
static constexpr auto r2r_F32LoadMem_Idx64
static constexpr auto r2r_F64LoadMem_Idx64
static constexpr auto r2s_I32LoadMem8S_Idx64
static constexpr auto r2s_I32LoadMem8U_Idx64
static constexpr auto r2s_I32LoadMem16S_Idx64
static constexpr auto r2s_I32LoadMem16U_Idx64
static constexpr auto r2s_I64LoadMem8S_Idx64
static constexpr auto r2s_I64LoadMem8U_Idx64
static constexpr auto r2s_I64LoadMem16S_Idx64
static constexpr auto r2s_I64LoadMem16U_Idx64
static constexpr auto r2s_I64LoadMem32S_Idx64
static constexpr auto r2s_I64LoadMem32U_Idx64
static constexpr auto r2s_I32LoadMem_Idx64
static constexpr auto r2s_I64LoadMem_Idx64
static constexpr auto r2s_F32LoadMem_Idx64
static constexpr auto r2s_F64LoadMem_Idx64
static constexpr auto s2r_I32LoadMem8S_Idx64
static constexpr auto s2r_I32LoadMem8U_Idx64
static constexpr auto s2r_I32LoadMem16S_Idx64
static constexpr auto s2r_I32LoadMem16U_Idx64
static constexpr auto s2r_I64LoadMem8S_Idx64
static constexpr auto s2r_I64LoadMem8U_Idx64
static constexpr auto s2r_I64LoadMem16S_Idx64
static constexpr auto s2r_I64LoadMem16U_Idx64
static constexpr auto s2r_I64LoadMem32S_Idx64
static constexpr auto s2r_I64LoadMem32U_Idx64
static constexpr auto s2r_I32LoadMem_Idx64
static constexpr auto s2r_I64LoadMem_Idx64
static constexpr auto s2r_F32LoadMem_Idx64
static constexpr auto s2r_F64LoadMem_Idx64
static constexpr auto s2s_I32LoadMem8S_Idx64
static constexpr auto s2s_I32LoadMem8U_Idx64
static constexpr auto s2s_I32LoadMem16S_Idx64
static constexpr auto s2s_I32LoadMem16U_Idx64
static constexpr auto s2s_I64LoadMem8S_Idx64
static constexpr auto s2s_I64LoadMem8U_Idx64
static constexpr auto s2s_I64LoadMem16S_Idx64
static constexpr auto s2s_I64LoadMem16U_Idx64
static constexpr auto s2s_I64LoadMem32S_Idx64
static constexpr auto s2s_I64LoadMem32U_Idx64
static constexpr auto s2s_I32LoadMem_Idx64
static constexpr auto s2s_I64LoadMem_Idx64
static constexpr auto s2s_F32LoadMem_Idx64
static constexpr auto s2s_F64LoadMem_Idx64
static constexpr auto s2s_I32LoadMem8S_LocalSet_Idx64
static constexpr auto s2s_I32LoadMem8U_LocalSet_Idx64
static constexpr auto s2s_I32LoadMem16S_LocalSet_Idx64
static constexpr auto s2s_I32LoadMem16U_LocalSet_Idx64
static constexpr auto s2s_I64LoadMem8S_LocalSet_Idx64
static constexpr auto s2s_I64LoadMem8U_LocalSet_Idx64
static constexpr auto s2s_I64LoadMem16S_LocalSet_Idx64
static constexpr auto s2s_I64LoadMem16U_LocalSet_Idx64
static constexpr auto s2s_I64LoadMem32S_LocalSet_Idx64
static constexpr auto s2s_I64LoadMem32U_LocalSet_Idx64
static constexpr auto s2s_I32LoadMem_LocalSet_Idx64
static constexpr auto s2s_I64LoadMem_LocalSet_Idx64
static constexpr auto s2s_F32LoadMem_LocalSet_Idx64
static constexpr auto s2s_F64LoadMem_LocalSet_Idx64
static constexpr auto r2s_I32StoreMem8_Idx64
static constexpr auto r2s_I32StoreMem16_Idx64
static constexpr auto r2s_I64StoreMem8_Idx64
static constexpr auto r2s_I64StoreMem16_Idx64
static constexpr auto r2s_I64StoreMem32_Idx64
static constexpr auto r2s_I32StoreMem_Idx64
static constexpr auto r2s_I64StoreMem_Idx64
static constexpr auto r2s_F32StoreMem_Idx64
static constexpr auto r2s_F64StoreMem_Idx64
static constexpr auto s2s_I32StoreMem8_Idx64
static constexpr auto s2s_I32StoreMem16_Idx64
static constexpr auto s2s_I64StoreMem8_Idx64
static constexpr auto s2s_I64StoreMem16_Idx64
static constexpr auto s2s_I64StoreMem32_Idx64
static constexpr auto s2s_I32StoreMem_Idx64
static constexpr auto s2s_I64StoreMem_Idx64
static constexpr auto s2s_F32StoreMem_Idx64
static constexpr auto s2s_F64StoreMem_Idx64
static constexpr auto r2s_I32LoadStoreMem_Idx64
static constexpr auto r2s_I64LoadStoreMem_Idx64
static constexpr auto r2s_F32LoadStoreMem_Idx64
static constexpr auto r2s_F64LoadStoreMem_Idx64
static constexpr auto s2s_I32LoadStoreMem_Idx64
static constexpr auto s2s_I64LoadStoreMem_Idx64
static constexpr auto s2s_F32LoadStoreMem_Idx64
static constexpr auto s2s_F64LoadStoreMem_Idx64
static constexpr auto r2r_I32Select = r2r_SelectI<int32_t>
static constexpr auto r2r_I64Select = r2r_SelectI<int64_t>
static constexpr auto r2r_F32Select = r2r_SelectF<float>
static constexpr auto r2r_F64Select = r2r_SelectF<double>
static constexpr auto r2s_I32Select = r2s_Select<int32_t>
static constexpr auto r2s_I64Select = r2s_Select<int64_t>
static constexpr auto r2s_F32Select = r2s_Select<float>
static constexpr auto r2s_F64Select = r2s_Select<double>
static constexpr auto r2s_S128Select = r2s_Select<Simd128>
static constexpr auto s2r_I32Select = s2r_SelectI<int32_t>
static constexpr auto s2r_I64Select = s2r_SelectI<int64_t>
static constexpr auto s2r_F32Select = s2r_SelectF<float>
static constexpr auto s2r_F64Select = s2r_SelectF<double>
static constexpr auto s2s_I32Select = s2s_Select<int32_t>
static constexpr auto s2s_I64Select = s2s_Select<int64_t>
static constexpr auto s2s_F32Select = s2s_Select<float>
static constexpr auto s2s_F64Select = s2s_Select<double>
static constexpr auto s2s_S128Select = s2s_Select<Simd128>
static constexpr auto s2s_Table64Copy_32_64_32
static constexpr auto s2s_Table64Copy_64_32_32
static constexpr auto s2s_Table64Copy_64_64_64
static constexpr auto s2s_AtomicNotify_Idx64
static constexpr auto s2s_I32AtomicWait_Idx64
static constexpr auto s2s_I64AtomicWait_Idx64
static constexpr auto s2s_SimdS128LoadMem
static constexpr auto s2s_SimdS128LoadMem_Idx64
static constexpr auto s2s_SimdS128StoreMem
static constexpr auto s2s_SimdS128StoreMem_Idx64
static constexpr auto s2s_SimdI16x8ExtMulLowI8x16S
static constexpr auto s2s_SimdI16x8ExtMulHighI8x16S
static constexpr auto s2s_SimdI16x8ExtMulLowI8x16U
static constexpr auto s2s_SimdI16x8ExtMulHighI8x16U
static constexpr auto s2s_SimdI32x4ExtMulLowI16x8S
static constexpr auto s2s_SimdI32x4ExtMulHighI16x8S
static constexpr auto s2s_SimdI32x4ExtMulLowI16x8U
static constexpr auto s2s_SimdI32x4ExtMulHighI16x8U
static constexpr auto s2s_SimdI64x2ExtMulLowI32x4S
static constexpr auto s2s_SimdI64x2ExtMulHighI32x4S
static constexpr auto s2s_SimdI64x2ExtMulLowI32x4U
static constexpr auto s2s_SimdI64x2ExtMulHighI32x4U
static constexpr auto s2s_SimdI8x16RelaxedLaneSelect = s2s_DoSimdSelect
static constexpr auto s2s_SimdI16x8RelaxedLaneSelect = s2s_DoSimdSelect
static constexpr auto s2s_SimdI32x4RelaxedLaneSelect = s2s_DoSimdSelect
static constexpr auto s2s_SimdI64x2RelaxedLaneSelect = s2s_DoSimdSelect
static constexpr auto s2s_SimdS128Select = s2s_DoSimdSelect
static constexpr auto s2s_SimdI8x16RelaxedSwizzle = s2s_SimdI8x16Swizzle
static constexpr auto s2s_SimdS128Load8Splat
static constexpr auto s2s_SimdS128Load8Splat_Idx64
static constexpr auto s2s_SimdS128Load16Splat
static constexpr auto s2s_SimdS128Load16Splat_Idx64
static constexpr auto s2s_SimdS128Load32Splat
static constexpr auto s2s_SimdS128Load32Splat_Idx64
static constexpr auto s2s_SimdS128Load64Splat
static constexpr auto s2s_SimdS128Load64Splat_Idx64
static constexpr auto s2s_SimdS128Load8x8S
static constexpr auto s2s_SimdS128Load8x8S_Idx64
static constexpr auto s2s_SimdS128Load8x8U
static constexpr auto s2s_SimdS128Load8x8U_Idx64
static constexpr auto s2s_SimdS128Load16x4S
static constexpr auto s2s_SimdS128Load16x4S_Idx64
static constexpr auto s2s_SimdS128Load16x4U
static constexpr auto s2s_SimdS128Load16x4U_Idx64
static constexpr auto s2s_SimdS128Load32x2S
static constexpr auto s2s_SimdS128Load32x2S_Idx64
static constexpr auto s2s_SimdS128Load32x2U
static constexpr auto s2s_SimdS128Load32x2U_Idx64
static constexpr auto s2s_SimdS128Load32Zero
static constexpr auto s2s_SimdS128Load32Zero_Idx64
static constexpr auto s2s_SimdS128Load64Zero
static constexpr auto s2s_SimdS128Load64Zero_Idx64
static constexpr auto s2s_SimdS128Load8Lane
static constexpr auto s2s_SimdS128Load16Lane
static constexpr auto s2s_SimdS128Load32Lane
static constexpr auto s2s_SimdS128Load64Lane
static constexpr auto s2s_SimdS128Load8Lane_Idx64
static constexpr auto s2s_SimdS128Load16Lane_Idx64
static constexpr auto s2s_SimdS128Load32Lane_Idx64
static constexpr auto s2s_SimdS128Load64Lane_Idx64
static constexpr auto s2s_SimdS128Store8Lane
static constexpr auto s2s_SimdS128Store16Lane
static constexpr auto s2s_SimdS128Store32Lane
static constexpr auto s2s_SimdS128Store64Lane
static constexpr auto s2s_SimdS128Store8Lane_Idx64
static constexpr auto s2s_SimdS128Store16Lane_Idx64
static constexpr auto s2s_SimdS128Store32Lane_Idx64
static constexpr auto s2s_SimdS128Store64Lane_Idx64
static constexpr auto s2s_SimdI32x4ExtAddPairwiseI16x8S
static constexpr auto s2s_SimdI32x4ExtAddPairwiseI16x8U
static constexpr auto s2s_SimdI16x8ExtAddPairwiseI8x16S
static constexpr auto s2s_SimdI16x8ExtAddPairwiseI8x16U
static constexpr auto s2s_I8SStructGet = s2s_StructGet<int32_t, int8_t>
static constexpr auto s2s_I8UStructGet = s2s_StructGet<uint32_t, uint8_t>
static constexpr auto s2s_I16SStructGet = s2s_StructGet<int32_t, int16_t>
static constexpr auto s2s_I16UStructGet = s2s_StructGet<uint32_t, uint16_t>
static constexpr auto s2s_I32StructGet = s2s_StructGet<int32_t>
static constexpr auto s2s_I64StructGet = s2s_StructGet<int64_t>
static constexpr auto s2s_F32StructGet = s2s_StructGet<float>
static constexpr auto s2s_F64StructGet = s2s_StructGet<double>
static constexpr auto s2s_S128StructGet = s2s_StructGet<Simd128>
static constexpr auto s2s_I8StructSet = s2s_StructSet<int32_t, int8_t>
static constexpr auto s2s_I16StructSet = s2s_StructSet<int32_t, int16_t>
static constexpr auto s2s_I32StructSet = s2s_StructSet<int32_t>
static constexpr auto s2s_I64StructSet = s2s_StructSet<int64_t>
static constexpr auto s2s_F32StructSet = s2s_StructSet<float>
static constexpr auto s2s_F64StructSet = s2s_StructSet<double>
static constexpr auto s2s_S128StructSet = s2s_StructSet<Simd128>
static constexpr auto s2s_I8ArrayNew = s2s_ArrayNew<int32_t, int8_t>
static constexpr auto s2s_I16ArrayNew = s2s_ArrayNew<int32_t, int16_t>
static constexpr auto s2s_I32ArrayNew = s2s_ArrayNew<int32_t>
static constexpr auto s2s_I64ArrayNew = s2s_ArrayNew<int64_t>
static constexpr auto s2s_F32ArrayNew = s2s_ArrayNew<float>
static constexpr auto s2s_F64ArrayNew = s2s_ArrayNew<double>
static constexpr auto s2s_S128ArrayNew = s2s_ArrayNew<Simd128>
static constexpr auto s2s_ArrayNewData
static constexpr auto s2s_ArrayNewElem
static constexpr auto s2s_ArrayInitData = s2s_ArrayInitSegment<true>
static constexpr auto s2s_ArrayInitElem = s2s_ArrayInitSegment<false>
static constexpr auto s2s_I8SArrayGet = s2s_ArrayGet<int32_t, int8_t>
static constexpr auto s2s_I8UArrayGet = s2s_ArrayGet<uint32_t, uint8_t>
static constexpr auto s2s_I16SArrayGet = s2s_ArrayGet<int32_t, int16_t>
static constexpr auto s2s_I16UArrayGet = s2s_ArrayGet<uint32_t, uint16_t>
static constexpr auto s2s_I32ArrayGet = s2s_ArrayGet<int32_t>
static constexpr auto s2s_I64ArrayGet = s2s_ArrayGet<int64_t>
static constexpr auto s2s_F32ArrayGet = s2s_ArrayGet<float>
static constexpr auto s2s_F64ArrayGet = s2s_ArrayGet<double>
static constexpr auto s2s_S128ArrayGet = s2s_ArrayGet<Simd128>
static constexpr auto s2s_I8ArraySet = s2s_ArraySet<int32_t, int8_t>
static constexpr auto s2s_I16ArraySet = s2s_ArraySet<int32_t, int16_t>
static constexpr auto s2s_I32ArraySet = s2s_ArraySet<int32_t>
static constexpr auto s2s_I64ArraySet = s2s_ArraySet<int64_t>
static constexpr auto s2s_F32ArraySet = s2s_ArraySet<float>
static constexpr auto s2s_F64ArraySet = s2s_ArraySet<double>
static constexpr auto s2s_S128ArraySet = s2s_ArraySet<Simd128>
static constexpr auto s2s_I8ArrayFill = s2s_ArrayFill<int8_t, int32_t>
static constexpr auto s2s_I16ArrayFill = s2s_ArrayFill<int16_t, int32_t>
static constexpr auto s2s_I32ArrayFill = s2s_ArrayFill<int32_t>
static constexpr auto s2s_I64ArrayFill = s2s_ArrayFill<int64_t>
static constexpr auto s2s_F32ArrayFill = s2s_ArrayFill<float>
static constexpr auto s2s_F64ArrayFill = s2s_ArrayFill<double>
static constexpr auto s2s_S128ArrayFill = s2s_ArrayFill<Simd128>
static constexpr auto s2s_RefCast = RefCast<false>
static constexpr auto s2s_RefCastNull = RefCast<true>
static constexpr auto s2s_RefTest = RefTest<false>
static constexpr auto s2s_RefTestNull = RefTest<true>
Private Types
using traits = handler_traits< Compressed >
using slot_offset_t = traits::slot_offset_t
using memory_offset32_t = traits::memory_offset32_t
using memory_offset64_t = traits::memory_offset64_t
Detailed Description
template<bool Compressed>
class v8::internal::wasm::Handlers< Compressed >
Definition at line 787 of file wasm-interpreter.cc.
Member Typedef Documentation
memory_offset32_t
template<bool Compressed>
using v8::internal::wasm::Handlers< Compressed >::memory_offset32_t = traits::memory_offset32_t [private]
Definition at line 790 of file wasm-interpreter.cc.
memory_offset64_t
template<bool Compressed>
using v8::internal::wasm::Handlers< Compressed >::memory_offset64_t = traits::memory_offset64_t [private]
Definition at line 791 of file wasm-interpreter.cc.
slot_offset_t
template<bool Compressed>
using v8::internal::wasm::Handlers< Compressed >::slot_offset_t = traits::slot_offset_t [private]
Definition at line 789 of file wasm-interpreter.cc.
traits
template<bool Compressed>
using v8::internal::wasm::Handlers< Compressed >::traits = handler_traits<Compressed> [private]
Definition at line 788 of file wasm-interpreter.cc.
Member Function Documentation
base::saturated_cast() [1/8]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::base::saturated_cast (a)
base::saturated_cast() [2/8]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::base::saturated_cast (a)
base::saturated_cast() [3/8]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::base::saturated_cast (a)
base::saturated_cast() [4/8]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::base::saturated_cast (a)
base::saturated_cast() [5/8]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::base::saturated_cast (a)
base::saturated_cast() [6/8]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::base::saturated_cast (a)
base::saturated_cast() [7/8]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::base::saturated_cast (a)
base::saturated_cast() [8/8]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::base::saturated_cast (a)
BINOP_CASE()
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::BINOP_CASE (I32x4MinU , i32x4 , int32x4 , 4)
CONVERT_CASE() [1/5]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::CONVERT_CASE (F32x4SConvertI32x4 , int32x4 , i32x4 , float32x4 , 4 , 0 , int32_t , static_cast< float > a)
CONVERT_CASE() [2/5]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::CONVERT_CASE (F64x2ConvertLowI32x4S , int32x4 , i32x4 , float64x2 , 2 , 0 , int32_t , static_cast< double > a)
CONVERT_CASE() [3/5]
template<bool Compressed>
a a v8::internal::wasm::Handlers< Compressed >::CONVERT_CASE (I32x4SConvertI16x8High , int16x8 , i16x8 , int32x4 , 4 , 4 , int16_t , a)
CONVERT_CASE() [4/5]
template<bool Compressed>
a a a v8::internal::wasm::Handlers< Compressed >::CONVERT_CASE (I32x4UConvertI16x8Low , int16x8 , i16x8 , int32x4 , 4 , 0 , uint16_t , a)
CONVERT_CASE() [5/5]
template<bool Compressed>
a v8::internal::wasm::Handlers< Compressed >::CONVERT_CASE (I64x2UConvertI32x4Low , int32x4 , i32x4 , int64x2 , 2 , 0 , uint32_t , a)
DoRefCast()
template<bool Compressed>
static bool v8::internal::wasm::Handlers< Compressed >::DoRefCast (WasmRef ref, ValueType ref_type, HeapType target_type, bool null_succeeds, WasmInterpreterRuntime * wasm_runtime) [inline], [static]
Definition at line 5743 of file wasm-interpreter.cc.
                                                              {
    if (target_type.is_index()) {
      DirectHandle<Map> rtt =
          wasm_runtime->RttCanon(target_type.ref_index().index);
      return wasm_runtime->SubtypeCheck(ref, ref_type, rtt,
                                        target_type.ref_index(), null_succeeds);
    } else {
      switch (target_type.representation()) {
        case HeapType::kEq:
          return wasm_runtime->RefIsEq(ref, ref_type, null_succeeds);
        case HeapType::kI31:
          return wasm_runtime->RefIsI31(ref, ref_type, null_succeeds);
        case HeapType::kStruct:
          return wasm_runtime->RefIsStruct(ref, ref_type, null_succeeds);
        case HeapType::kArray:
          return wasm_runtime->RefIsArray(ref, ref_type, null_succeeds);
        case HeapType::kString:
          return wasm_runtime->RefIsString(ref, ref_type, null_succeeds);
        case HeapType::kNone:
        case HeapType::kNoExtern:
        case HeapType::kNoFunc:
          DCHECK(null_succeeds);
          return wasm_runtime->IsNullTypecheck(ref, ref_type);
        case HeapType::kAny:
          // Any may never need a cast as it is either implicitly convertible or
          // never convertible for any given type.
        default:
          UNREACHABLE();
      }
    }
  }
References v8::internal::DCHECK(), v8::internal::wasm::TypeIndex::index, v8::internal::wasm::HeapType::is_index(), v8::internal::wasm::HeapType::kAny, v8::internal::wasm::HeapType::kArray, v8::internal::wasm::HeapType::kEq, v8::internal::wasm::HeapType::kI31, v8::internal::wasm::HeapType::kNoExtern, v8::internal::wasm::HeapType::kNoFunc, v8::internal::wasm::HeapType::kNone, v8::internal::wasm::HeapType::kString, v8::internal::wasm::HeapType::kStruct, v8::internal::wasm::HeapType::ref_index(), v8::internal::wasm::HeapType::representation(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::Handlers< Compressed >::RefCast(), v8::internal::wasm::Handlers< Compressed >::RefTest(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCast(), and v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCastFail().
DoubleToFloat32()
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::DoubleToFloat32 (a)
ExecuteRemS()
template<bool Compressed>
template<typename T >
static T v8::internal::wasm::Handlers< Compressed >::ExecuteRemS (T lval, T rval) [inline], [static]
Definition at line 895 of file wasm-interpreter.cc.
                                              {
    if (rval == -1) return 0;
    return lval % rval;
  }
ExecuteRemU()
template<bool Compressed>
template<typename T >
static T v8::internal::wasm::Handlers< Compressed >::ExecuteRemU (T lval, T rval) [inline], [static]
Definition at line 901 of file wasm-interpreter.cc.
                                              {
    return lval % rval;
  }
for()
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::for () [inline]
Definition at line 5132 of file wasm-interpreter.cc.
                                   {
      res.val[LANE(i, res)] =
          v2.val[LANE(i, v2)] ^ ((v1.val[LANE(i, v1)] ^ v2.val[LANE(i, v2)]) &
                                 bool_val.val[LANE(i, bool_val)]);
    }
References LANE, v8::internal::wasm::Handlers< Compressed >::res, v8::internal::wasm::Handlers< Compressed >::v1, and v8::internal::wasm::Handlers< Compressed >::v2.
JSMax()
template<bool Compressed>
template<typename T >
static T v8::internal::wasm::Handlers< Compressed >::JSMax (T x, T y) [inline], [static]
Definition at line 816 of file wasm-interpreter.cc.
                                  {
    if (std::isnan(x) || std::isnan(y)) {
      return std::numeric_limits<T>::quiet_NaN();
    }
    if (std::signbit(x) < std::signbit(y)) return x;
    return x > y ? x : y;
  }
References v8::internal::y.
JSMin()
template<bool Compressed>
template<typename T >
static T v8::internal::wasm::Handlers< Compressed >::JSMin (T x, T y) [inline], [static]
Definition at line 827 of file wasm-interpreter.cc.
                                  {
    if (std::isnan(x) || std::isnan(y)) {
      return std::numeric_limits<T>::quiet_NaN();
    }
    if (std::signbit(x) < std::signbit(y)) return y;
    return x > y ? y : x;
  }
References v8::internal::y.
NextOp()
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::NextOp ()
Referenced by v8::internal::wasm::Handlers< Compressed >::r2r_I32ConvertI64(), v8::internal::wasm::Handlers< Compressed >::r2r_LoadMemF(), v8::internal::wasm::Handlers< Compressed >::r2r_LoadMemI(), v8::internal::wasm::Handlers< Compressed >::r2r_SelectF(), v8::internal::wasm::Handlers< Compressed >::r2r_SelectI(), v8::internal::wasm::Handlers< Compressed >::r2s_BranchIf(), v8::internal::wasm::Handlers< Compressed >::r2s_BranchIfWithParams(), v8::internal::wasm::Handlers< Compressed >::r2s_BrTable(), v8::internal::wasm::Handlers< Compressed >::r2s_CopyFp0ToSlot32(), v8::internal::wasm::Handlers< Compressed >::r2s_CopyFp0ToSlot64(), v8::internal::wasm::Handlers< Compressed >::r2s_CopyR0ToSlot32(), v8::internal::wasm::Handlers< Compressed >::r2s_CopyR0ToSlot64(), v8::internal::wasm::Handlers< Compressed >::r2s_Drop(), v8::internal::wasm::Handlers< Compressed >::r2s_GlobalSetF(), v8::internal::wasm::Handlers< Compressed >::r2s_GlobalSetI(), v8::internal::wasm::Handlers< Compressed >::r2s_I32ConvertI64(), v8::internal::wasm::Handlers< Compressed >::r2s_If(), v8::internal::wasm::Handlers< Compressed >::r2s_LoadMem(), v8::internal::wasm::Handlers< Compressed >::r2s_LoadStoreMem(), v8::internal::wasm::Handlers< Compressed >::r2s_PreserveCopyFp0ToSlot32(), v8::internal::wasm::Handlers< Compressed >::r2s_PreserveCopyFp0ToSlot64(), v8::internal::wasm::Handlers< Compressed >::r2s_PreserveCopyR0ToSlot32(), v8::internal::wasm::Handlers< Compressed >::r2s_PreserveCopyR0ToSlot64(), v8::internal::wasm::Handlers< Compressed >::r2s_RefSelect(), v8::internal::wasm::Handlers< Compressed >::r2s_Select(), v8::internal::wasm::Handlers< Compressed >::r2s_StoreMemF(), v8::internal::wasm::Handlers< Compressed >::r2s_StoreMemI(), v8::internal::wasm::Handlers< Compressed >::RefCast(), v8::internal::wasm::Handlers< Compressed >::RefTest(), v8::internal::wasm::Handlers< Compressed >::s2r_GlobalGetF(), v8::internal::wasm::Handlers< Compressed >::s2r_GlobalGetI(), v8::internal::wasm::Handlers< Compressed >::s2r_I32ConvertI64(), v8::internal::wasm::Handlers< Compressed >::s2r_LoadMemF(), v8::internal::wasm::Handlers< Compressed >::s2r_LoadMemI(), v8::internal::wasm::Handlers< Compressed >::s2r_SelectF(), v8::internal::wasm::Handlers< Compressed >::s2r_SelectI(), v8::internal::wasm::Handlers< Compressed >::s2s_AnyConvertExtern(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayCopy(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayFill(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayGet(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayInitSegment(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayLen(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNew(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewDefault(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewFixed(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewSegment(), v8::internal::wasm::Handlers< Compressed >::s2s_ArraySet(), v8::internal::wasm::Handlers< Compressed >::s2s_AssertNotNullTypecheck(), v8::internal::wasm::Handlers< Compressed >::s2s_AssertNullTypecheck(), v8::internal::wasm::Handlers< Compressed >::s2s_AtomicFence(), v8::internal::wasm::Handlers< Compressed >::s2s_AtomicNotify(), v8::internal::wasm::Handlers< Compressed >::s2s_Branch(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchIf(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchIfWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCast(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCastFail(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNull(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNullWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNull(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNullWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BrTable(), v8::internal::wasm::Handlers< Compressed >::s2s_CallFunction(), v8::internal::wasm::Handlers< Compressed >::s2s_CallImportedFunction(), v8::internal::wasm::Handlers< Compressed >::s2s_CallIndirect(), v8::internal::wasm::Handlers< Compressed >::s2s_CallIndirect64(), v8::internal::wasm::Handlers< Compressed >::s2s_CallRef(), v8::internal::wasm::Handlers< Compressed >::s2s_Catch(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot128(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot32(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot32x2(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot64(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot64x2(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_ll(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_lq(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_ql(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_qq(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlotMulti(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlotRef(), v8::internal::wasm::Handlers< Compressed >::s2s_DataDrop(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdExtAddPairwise(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdExtMul(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadExtend(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadLane(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadSplat(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadZeroExtend(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdStoreLane(), v8::internal::wasm::Handlers< Compressed >::s2s_Drop(), v8::internal::wasm::Handlers< Compressed >::s2s_ElemDrop(), v8::internal::wasm::Handlers< Compressed >::s2s_Else(), v8::internal::wasm::Handlers< Compressed >::s2s_ExternConvertAny(), v8::internal::wasm::Handlers< Compressed >::s2s_GlobalGet(), v8::internal::wasm::Handlers< Compressed >::s2s_GlobalSet(), v8::internal::wasm::Handlers< Compressed >::s2s_I31GetS(), v8::internal::wasm::Handlers< Compressed >::s2s_I31GetU(), v8::internal::wasm::Handlers< Compressed >::s2s_I32AtomicWait(), v8::internal::wasm::Handlers< Compressed >::s2s_I32ConvertI64(), v8::internal::wasm::Handlers< Compressed >::s2s_I64AtomicWait(), v8::internal::wasm::Handlers< Compressed >::s2s_If(), v8::internal::wasm::Handlers< Compressed >::s2s_LoadMem(), v8::internal::wasm::Handlers< Compressed >::s2s_LoadMem_LocalSet(), v8::internal::wasm::Handlers< Compressed >::s2s_LoadStoreMem(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Copy(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Fill(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Grow(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Init(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Size(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryCopy(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryFill(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryGrow(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryInit(), v8::internal::wasm::Handlers< Compressed >::s2s_MemorySize(), v8::internal::wasm::Handlers< Compressed >::s2s_OnLoopBegin(), v8::internal::wasm::Handlers< Compressed >::s2s_OnLoopBeginNoRefSlots(), v8::internal::wasm::Handlers< Compressed >::s2s_PreserveCopySlot128(), v8::internal::wasm::Handlers< Compressed >::s2s_PreserveCopySlot32(), v8::internal::wasm::Handlers< Compressed >::s2s_PreserveCopySlot64(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayFill(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayGet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayNew(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArraySet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefAsNonNull(), v8::internal::wasm::Handlers< Compressed >::s2s_RefDrop(), v8::internal::wasm::Handlers< Compressed >::s2s_RefEq(), v8::internal::wasm::Handlers< Compressed >::s2s_RefFunc(), v8::internal::wasm::Handlers< Compressed >::s2s_RefGlobalGet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefGlobalSet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefI31(), v8::internal::wasm::Handlers< Compressed >::s2s_RefIsNonNull(), v8::internal::wasm::Handlers< Compressed >::s2s_RefIsNull(), v8::internal::wasm::Handlers< Compressed >::s2s_RefNull(), v8::internal::wasm::Handlers< Compressed >::s2s_RefSelect(), v8::internal::wasm::Handlers< Compressed >::s2s_RefStructGet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefStructSet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefTestFails(), v8::internal::wasm::Handlers< Compressed >::s2s_RefTestSucceeds(), v8::internal::wasm::Handlers< Compressed >::s2s_Rethrow(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCall(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallImportedFunction(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallIndirect(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallIndirect64(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallRef(), v8::internal::wasm::Handlers< Compressed >::s2s_Select(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8DotI8x16I7x16S(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI16x8S(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI8x16I7x16AddS(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Shuffle(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Swizzle(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128StoreMemI(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdV128AnyTrue(), v8::internal::wasm::Handlers< Compressed >::s2s_StoreMem(), v8::internal::wasm::Handlers< Compressed >::s2s_StructGet(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNew(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNewDefault(), v8::internal::wasm::Handlers< Compressed >::s2s_StructSet(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64CopyImpl(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Fill(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Get(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Grow(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Init(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Set(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Size(), v8::internal::wasm::Handlers< Compressed >::s2s_TableCopy(), v8::internal::wasm::Handlers< Compressed >::s2s_TableFill(), v8::internal::wasm::Handlers< Compressed >::s2s_TableGet(), v8::internal::wasm::Handlers< Compressed >::s2s_TableGrow(), v8::internal::wasm::Handlers< Compressed >::s2s_TableInit(), v8::internal::wasm::Handlers< Compressed >::s2s_TableSet(), v8::internal::wasm::Handlers< Compressed >::s2s_TableSize(), and v8::internal::wasm::Handlers< Compressed >::s2s_Throw().
pop() [1/2]
template<bool Compressed>
template<typename T >
static T v8::internal::wasm::Handlers< Compressed >::pop (uint32_t *& sp, const uint8_t *& code, WasmInterpreterRuntime * wasm_runtime) [inline], [static]
Definition at line 875 of file wasm-interpreter.cc.
                                                            {
    slot_offset_t offset = Read<slot_offset_t>(code);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) wasm_runtime->TracePop();
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    return base::ReadUnalignedValue<T>(reinterpret_cast<Address>(sp + offset));
  }
References code, and v8::internal::v8_flags.
pop() [2/2]
template<bool Compressed>
template<>
WasmRef v8::internal::wasm::Handlers< Compressed >::pop (uint32_t *& sp, const uint8_t *& code, WasmInterpreterRuntime * wasm_runtime) [inline]
Definition at line 885 of file wasm-interpreter.cc.
                                                           {
    uint32_t ref_stack_index = Read<int32_t>(code);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) wasm_runtime->TracePop();
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    return wasm_runtime->ExtractWasmRef(ref_stack_index);
  }
References code, v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
push() [1/3]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::push (sp , code , wasm_runtime , Simd128(res))
push() [2/3]
template<bool Compressed>
template<typename T >
static void v8::internal::wasm::Handlers< Compressed >::push (uint32_t *& sp, const uint8_t *& code, WasmInterpreterRuntime * wasm_runtime, T val) [inline], [static]
Definition at line 850 of file wasm-interpreter.cc.
                                                                       {
    slot_offset_t offset = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<T>(reinterpret_cast<Address>(sp + offset), val);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution)
      wasm_runtime->TracePush<T>(offset * kSlotSize);
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  }
References code, v8::internal::wasm::kSlotSize, and v8::internal::v8_flags.
push() [3/3]
template<bool Compressed>
template<>
void v8::internal::wasm::Handlers< Compressed >::push (uint32_t *& sp, const uint8_t *& code, WasmInterpreterRuntime * wasm_runtime, WasmRef ref) [inline]
Definition at line 861 of file wasm-interpreter.cc.
                                                                      {
    slot_offset_t offset = Read<slot_offset_t>(code);
    uint32_t ref_stack_index = Read<int32_t>(code);
    base::WriteUnalignedValue<uint64_t>(reinterpret_cast<Address>(sp + offset),
                                        kSlotsZapValue);
    wasm_runtime->StoreWasmRef(ref_stack_index, ref);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution)
      wasm_runtime->TracePush<WasmRef>(offset * kSlotSize);
#endif // V8_ENABLE_DRUMBRAKE_TRACING
  }
References code, v8::internal::wasm::kSlotSize, v8::internal::kSlotsZapValue, v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
r2r_I32ConvertI64()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2r_I32ConvertI64 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2405 of file wasm-interpreter.cc.
                              {
    r0 &= 0xffffffff;
    NextOp();
  }
References v8::internal::wasm::Handlers< Compressed >::NextOp().
r2r_LoadMemF()
template<bool Compressed>
template<typename FloatT , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2r_LoadMemF (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1111 of file wasm-interpreter.cc.
                                                                {
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    MemOffsetT offset = Read<MemOffsetT>(code);
    MemIdx index = static_cast<MemIdx>(r0);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(FloatT),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    fp0 = base::ReadUnalignedValue<FloatT>(reinterpret_cast<Address>(address));
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::r0, TRAP, v8::internal::wasm::Handlers< Compressed >::uint8_t, and V8_UNLIKELY.
r2r_LoadMemI()
template<bool Compressed>
template<typename IntT , typename IntU = IntT, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2r_LoadMemI (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1061 of file wasm-interpreter.cc.
                                                                {
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    uint64_t offset = Read<MemOffsetT>(code);
    MemIdx index = static_cast<MemIdx>(r0);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(IntU),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    IntU value =
        base::ReadUnalignedValue<IntU>(reinterpret_cast<Address>(address));
    r0 = static_cast<IntT>(value);
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::r0, TRAP, v8::internal::wasm::Handlers< Compressed >::uint8_t, V8_UNLIKELY, and v8::internal::value.
r2r_SelectF()
template<bool Compressed>
template<typename FloatT >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2r_SelectF (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1834 of file wasm-interpreter.cc.
                                                               {
    FloatT val2 = pop<FloatT>(sp, code, wasm_runtime);
    FloatT val1 = pop<FloatT>(sp, code, wasm_runtime);
    // r0: condition
    fp0 = r0 ? val1 : val2;
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
r2r_SelectI()
template<bool Compressed>
template<typename IntT >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2r_SelectI (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1819 of file wasm-interpreter.cc.
                                                               {
    IntT val2 = pop<IntT>(sp, code, wasm_runtime);
    IntT val1 = pop<IntT>(sp, code, wasm_runtime);
    // r0: condition
    r0 = r0 ? val1 : val2;
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
r2s_BranchIf()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_BranchIf (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2861 of file wasm-interpreter.cc.
                                                                {
    int64_t cond = r0;
    int32_t if_true_offset = Read<int32_t>(code);
    if (cond) {
      // If condition is true, jump to the target branch.
      code += (if_true_offset - kCodeOffsetSize);
    }
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::r0.
r2s_BranchIfWithParams()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_BranchIfWithParams (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2889 of file wasm-interpreter.cc.
                              {
    int64_t cond = r0;
    int32_t if_false_offset = Read<int32_t>(code);
    if (!cond) {
      // If condition is not true, jump to the false branch.
      code += (if_false_offset - kCodeOffsetSize);
    }
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::r0.
r2s_BrTable()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_BrTable (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3178 of file wasm-interpreter.cc.
                                                               {
    uint32_t cond = static_cast<int32_t>(r0);
    uint32_t table_length = Read<int32_t>(code);
    uint32_t index = cond < table_length ? cond : table_length;
    int32_t target_offset = base::ReadUnalignedValue<int32_t>(
        reinterpret_cast<Address>(code + index * kCodeOffsetSize));
    code += (target_offset + index * kCodeOffsetSize);
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::r0, and v8::internal::wasm::Handlers< Compressed >::uint32_t.
r2s_CopyFp0ToSlot32()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_CopyFp0ToSlot32 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3691 of file wasm-interpreter.cc.
                              {
    slot_offset_t to = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<float>(reinterpret_cast<Address>(sp + to),
                                     static_cast<float>(fp0));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYFP0TOSLOT32 %d %08x\n", to,
                          base::ReadUnalignedValue<uint32_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
r2s_CopyFp0ToSlot64()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_CopyFp0ToSlot64 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3710 of file wasm-interpreter.cc.
                              {
    slot_offset_t to = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<double>(reinterpret_cast<Address>(sp + to), fp0);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYFP0TOSLOT64 %d %" PRIx64 "\n", to,
                          base::ReadUnalignedValue<uint64_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
r2s_CopyR0ToSlot32()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_CopyR0ToSlot32 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3654 of file wasm-interpreter.cc.
                              {
    slot_offset_t to = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<int32_t>(reinterpret_cast<Address>(sp + to),
                                       static_cast<int32_t>(r0));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYR0TOSLOT32 %d %08x\n", to,
                          base::ReadUnalignedValue<int32_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
r2s_CopyR0ToSlot64()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_CopyR0ToSlot64 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3673 of file wasm-interpreter.cc.
                              {
    slot_offset_t to = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<int64_t>(reinterpret_cast<Address>(sp + to), r0);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYR0TOSLOT64 %d %" PRIx64 "\n", to,
                          base::ReadUnalignedValue<int64_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
r2s_Drop()
template<bool Compressed>
template<typename T >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_Drop (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1018 of file wasm-interpreter.cc.
                                                            {
    NextOp();
  }
References v8::internal::wasm::Handlers< Compressed >::NextOp().
r2s_GlobalSetF()
template<bool Compressed>
template<typename FloatT >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_GlobalSetF (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 977 of file wasm-interpreter.cc.
                                                                  {
    uint32_t index = ReadGlobalIndex(code);
    uint8_t* dst_addr = wasm_runtime->GetGlobalAddress(index);
    base::WriteUnalignedValue<FloatT>(reinterpret_cast<Address>(dst_addr),
                                      static_cast<FloatT>(fp0)); // fp0: value
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::ReadGlobalIndex(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::wasm::Handlers< Compressed >::uint8_t.
r2s_GlobalSetI()
template<bool Compressed>
template<typename IntT >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_GlobalSetI (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 964 of file wasm-interpreter.cc.
                                                                  {
    uint32_t index = ReadGlobalIndex(code);
    uint8_t* dst_addr = wasm_runtime->GetGlobalAddress(index);
    base::WriteUnalignedValue<IntT>(reinterpret_cast<Address>(dst_addr),
                                    static_cast<IntT>(r0)); // r0: value
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::ReadGlobalIndex(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::wasm::Handlers< Compressed >::uint8_t.
r2s_I32ConvertI64()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_I32ConvertI64 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2411 of file wasm-interpreter.cc.
                              {
    push<int32_t>(sp, code, wasm_runtime, r0 & 0xffffffff);
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
r2s_If()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_If (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2917 of file wasm-interpreter.cc.
                                                          {
    int64_t cond = r0;
    int32_t target_offset = Read<int32_t>(code);
    if (!cond) {
      code += (target_offset - kCodeOffsetSize);
    }
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::r0.
r2s_LoadMem()
template<bool Compressed>
template<typename T , typename U = T, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_LoadMem (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1139 of file wasm-interpreter.cc.
                                                               {
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    MemOffsetT offset = Read<MemOffsetT>(code);
    MemIdx index = static_cast<MemIdx>(r0);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(U),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    U value = base::ReadUnalignedValue<U>(reinterpret_cast<Address>(address));
    push<T>(sp, code, wasm_runtime, value);
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::r0, TRAP, v8::internal::U, v8::internal::wasm::Handlers< Compressed >::uint8_t, V8_UNLIKELY, and v8::internal::value.
r2s_LoadStoreMem()
template<bool Compressed>
template<typename T , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_LoadStoreMem (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1504 of file wasm-interpreter.cc.
                              {
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    MemOffsetT load_offset = Read<MemOffsetT>(code);
    uint64_t load_index = r0;
    uint64_t effective_load_index = load_offset + load_index;
    MemOffsetT store_offset = Read<MemOffsetT>(code);
    uint64_t store_index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_store_index = store_offset + store_index;
    if (V8_UNLIKELY(
            effective_load_index < load_index ||
            !base::IsInBounds<uint64_t>(effective_load_index, sizeof(T),
                                        wasm_runtime->GetMemorySize()) ||
            effective_store_index < store_offset ||
            !base::IsInBounds<uint64_t>(effective_store_index, sizeof(T),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* load_address = memory_start + effective_load_index;
    uint8_t* store_address = memory_start + effective_store_index;
    base::WriteUnalignedValue<T>(
        reinterpret_cast<Address>(store_address),
        base::ReadUnalignedValue<T>(reinterpret_cast<Address>(load_address)));
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::r0, TRAP, v8::internal::wasm::Handlers< Compressed >::uint8_t, and V8_UNLIKELY.
r2s_PreserveCopyFp0ToSlot32()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_PreserveCopyFp0ToSlot32 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3774 of file wasm-interpreter.cc.
                              {
    slot_offset_t to = Read<slot_offset_t>(code);
    slot_offset_t preserve = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<float>(
        reinterpret_cast<Address>(sp + preserve),
        base::ReadUnalignedValue<float>(reinterpret_cast<Address>(sp + to)));
    base::WriteUnalignedValue<float>(reinterpret_cast<Address>(sp + to),
                                     static_cast<float>(fp0));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("PRESERVECOPYFP0TOSLOT32 %d %d %08x\n", to, preserve,
                          base::ReadUnalignedValue<uint32_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
r2s_PreserveCopyFp0ToSlot64()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_PreserveCopyFp0ToSlot64 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3797 of file wasm-interpreter.cc.
                              {
    slot_offset_t to = Read<slot_offset_t>(code);
    slot_offset_t preserve = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<double>(
        reinterpret_cast<Address>(sp + preserve),
        base::ReadUnalignedValue<double>(reinterpret_cast<Address>(sp + to)));
    base::WriteUnalignedValue<double>(reinterpret_cast<Address>(sp + to), fp0);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("PRESERVECOPYFP0TOSLOT64 %d %d %" PRIx64 "\n", to,
                          preserve,
                          base::ReadUnalignedValue<uint64_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
r2s_PreserveCopyR0ToSlot32()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_PreserveCopyR0ToSlot32 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3728 of file wasm-interpreter.cc.
                              {
    slot_offset_t to = Read<slot_offset_t>(code);
    slot_offset_t preserve = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<int32_t>(
        reinterpret_cast<Address>(sp + preserve),
        base::ReadUnalignedValue<int32_t>(reinterpret_cast<Address>(sp + to)));
    base::WriteUnalignedValue<int32_t>(reinterpret_cast<Address>(sp + to),
                                       static_cast<int32_t>(r0));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("PRESERVECOPYR0TOSLOT32 %d %d %08x\n", to, preserve,
                          base::ReadUnalignedValue<uint32_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
r2s_PreserveCopyR0ToSlot64()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_PreserveCopyR0ToSlot64 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3751 of file wasm-interpreter.cc.
                              {
    slot_offset_t to = Read<slot_offset_t>(code);
    slot_offset_t preserve = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<int64_t>(
        reinterpret_cast<Address>(sp + preserve),
        base::ReadUnalignedValue<int64_t>(reinterpret_cast<Address>(sp + to)));
    base::WriteUnalignedValue<int64_t>(reinterpret_cast<Address>(sp + to), r0);
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("PRESERVECOPYR0TOSLOT64 %d %d %" PRIx64 "\n", to,
                          preserve,
                          base::ReadUnalignedValue<uint64_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
r2s_RefDrop()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_RefDrop (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1028 of file wasm-interpreter.cc.
                                                               {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
r2s_RefSelect()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_RefSelect (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1865 of file wasm-interpreter.cc.
                                                                 {
    WasmRef val2 = pop<WasmRef>(sp, code, wasm_runtime);
    WasmRef val1 = pop<WasmRef>(sp, code, wasm_runtime);
    push<WasmRef>(sp, code, wasm_runtime, r0 ? val1 : val2);
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
r2s_Select()
template<bool Compressed>
template<typename T >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_Select (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1849 of file wasm-interpreter.cc.
                                                              {
    T val2 = pop<T>(sp, code, wasm_runtime);
    T val1 = pop<T>(sp, code, wasm_runtime);
    push<T>(sp, code, wasm_runtime, r0 ? val1 : val2);
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
r2s_StoreMemF()
template<bool Compressed>
template<typename FloatT , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_StoreMemF (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1425 of file wasm-interpreter.cc.
                                                                 {
    FloatT value = static_cast<FloatT>(fp0);
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    MemOffsetT offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(FloatT),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    base::WriteUnalignedValue<FloatT>(
        reinterpret_cast<Address>(address),
        base::ReadUnalignedValue<FloatT>(reinterpret_cast<Address>(&value)));
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::fp0, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint8_t, V8_UNLIKELY, and v8::internal::value.
r2s_StoreMemI()
template<bool Compressed>
template<typename IntT , typename IntU = IntT, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::r2s_StoreMemI (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1383 of file wasm-interpreter.cc.
                                                                 {
    IntT value = static_cast<IntT>(r0);
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    MemOffsetT offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(IntU),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    base::WriteUnalignedValue<IntU>(
        reinterpret_cast<Address>(address),
        base::ReadUnalignedValue<IntU>(reinterpret_cast<Address>(&value)));
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::r0, TRAP, v8::internal::wasm::Handlers< Compressed >::uint8_t, V8_UNLIKELY, and v8::internal::value.
Read() [1/2]
template<bool Compressed>
template<typename T >
static T v8::internal::wasm::Handlers< Compressed >::Read (const uint8_t *& code) [inline], [static]
Definition at line 795 of file wasm-interpreter.cc.
                                             {
    T res = base::ReadUnalignedValue<T>(reinterpret_cast<Address>(code));
    code += sizeof(T);
    return res;
  }
References code, v8::internal::wasm::Handlers< Compressed >::res, and T.
Read() [2/2]
template<bool Compressed>
template<>
slot_offset_t v8::internal::wasm::Handlers< Compressed >::Read (const uint8_t *& code) [inline]
Definition at line 801 of file wasm-interpreter.cc.
                                                          {
    slot_offset_t res = base::ReadUnalignedValue<slot_offset_t>(
        reinterpret_cast<Address>(code));
#if V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_compact_bytecode) {
      printf("Read slot_offset_t %d\n", res);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    code += sizeof(slot_offset_t);
    return res;
  }
References code, v8::internal::wasm::Handlers< Compressed >::res, and v8::internal::v8_flags.
ReadGlobalIndex()
template<bool Compressed>
static uint32_t v8::internal::wasm::Handlers< Compressed >::ReadGlobalIndex (const uint8_t *& code) [inline], [static]
Definition at line 842 of file wasm-interpreter.cc.
                                                               {
    uint32_t res =
        base::ReadUnalignedValue<uint32_t>(reinterpret_cast<Address>(code));
    code += sizeof(uint32_t);
    return res;
  }
References code, v8::internal::wasm::Handlers< Compressed >::res, and v8::internal::wasm::Handlers< Compressed >::uint32_t.
Referenced by v8::internal::wasm::Handlers< Compressed >::r2s_GlobalSetF(), v8::internal::wasm::Handlers< Compressed >::r2s_GlobalSetI(), v8::internal::wasm::Handlers< Compressed >::s2r_GlobalGetF(), v8::internal::wasm::Handlers< Compressed >::s2r_GlobalGetI(), v8::internal::wasm::Handlers< Compressed >::s2s_GlobalGet(), v8::internal::wasm::Handlers< Compressed >::s2s_GlobalSet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefGlobalGet(), and v8::internal::wasm::Handlers< Compressed >::s2s_RefGlobalSet().
ReadMemoryAddress()
template<bool Compressed>
static uint8_t* v8::internal::wasm::Handlers< Compressed >::ReadMemoryAddress (uint8_t *& code) [inline], [static]
Definition at line 835 of file wasm-interpreter.cc.
                                                           {
    Address res =
        base::ReadUnalignedValue<Address>(reinterpret_cast<Address>(code));
    code += sizeof(Address);
    return reinterpret_cast<uint8_t*>(res);
  }
References code, v8::internal::wasm::Handlers< Compressed >::res, and v8::internal::wasm::Handlers< Compressed >::uint8_t.
RefCast()
template<bool Compressed>
template<bool null_succeeds>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::RefCast (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6757 of file wasm-interpreter.cc.
                                                           {
    HeapType target_type =
        HeapType::FromBits(static_cast<uint32_t>(Read<int32_t>(code)));
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    const uint32_t ref_bitfield = Read<int32_t>(code);
    ValueType ref_type = ValueType::FromRawBitField(ref_bitfield);
    if (!DoRefCast(ref, ref_type, target_type, null_succeeds, wasm_runtime)) {
      TRAP(TrapReason::kTrapIllegalCast)
    }
    push<WasmRef>(sp, code, wasm_runtime, ref);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::DoRefCast(), v8::internal::wasm::HeapType::FromBits(), v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, and v8::internal::wasm::Handlers< Compressed >::uint32_t.
RefTest()
template<bool Compressed>
template<bool null_succeeds>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::RefTest (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6780 of file wasm-interpreter.cc.
                                                           {
    HeapType target_type =
        HeapType::FromBits(static_cast<uint32_t>(Read<int32_t>(code)));
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    const uint32_t ref_bitfield = Read<int32_t>(code);
    ValueType ref_type = ValueType::FromRawBitField(ref_bitfield);
    bool cast_succeeds =
        DoRefCast(ref, ref_type, target_type, null_succeeds, wasm_runtime);
    push<int32_t>(sp, code, wasm_runtime, cast_succeeds ? 1 : 0);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::DoRefCast(), v8::internal::wasm::HeapType::FromBits(), v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2r_GlobalGetF()
template<bool Compressed>
template<typename FloatT >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2r_GlobalGetF (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 922 of file wasm-interpreter.cc.
                                                                  {
    uint32_t index = ReadGlobalIndex(code);
    uint8_t* src_addr = wasm_runtime->GetGlobalAddress(index);
    fp0 = base::ReadUnalignedValue<FloatT>(reinterpret_cast<Address>(src_addr));
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::ReadGlobalIndex(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::wasm::Handlers< Compressed >::uint8_t.
s2r_GlobalGetI()
template<bool Compressed>
template<typename IntT >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2r_GlobalGetI (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 909 of file wasm-interpreter.cc.
                                                                  {
    uint32_t index = ReadGlobalIndex(code);
    uint8_t* src_addr = wasm_runtime->GetGlobalAddress(index);
    r0 = base::ReadUnalignedValue<IntT>(reinterpret_cast<Address>(src_addr));
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::ReadGlobalIndex(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::wasm::Handlers< Compressed >::uint8_t.
s2r_I32ConvertI64()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2r_I32ConvertI64 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2417 of file wasm-interpreter.cc.
                              {
    r0 = 0xffffffff & pop<int64_t>(sp, code, wasm_runtime);
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2r_LoadMemF()
template<bool Compressed>
template<typename FloatT , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2r_LoadMemF (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1242 of file wasm-interpreter.cc.
                                                                {
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    MemOffsetT offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(FloatT),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    fp0 = static_cast<FloatT>(
        base::ReadUnalignedValue<FloatT>(reinterpret_cast<Address>(address)));
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint8_t, and V8_UNLIKELY.
s2r_LoadMemI()
template<bool Compressed>
template<typename IntT , typename IntU = IntT, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2r_LoadMemI (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1193 of file wasm-interpreter.cc.
                                                                {
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    MemOffsetT offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(IntU),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    r0 = static_cast<IntT>(
        base::ReadUnalignedValue<IntU>(reinterpret_cast<Address>(address)));
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint8_t, and V8_UNLIKELY.
s2r_SelectF()
template<bool Compressed>
template<typename FloatT >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2r_SelectF (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1891 of file wasm-interpreter.cc.
                                                               {
    int32_t cond = pop<int32_t>(sp, code, wasm_runtime);
    FloatT val2 = pop<FloatT>(sp, code, wasm_runtime);
    FloatT val1 = pop<FloatT>(sp, code, wasm_runtime);
    fp0 = cond ? val1 : val2;
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2r_SelectI()
template<bool Compressed>
template<typename IntT >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2r_SelectI (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1876 of file wasm-interpreter.cc.
                                                               {
    int32_t cond = pop<int32_t>(sp, code, wasm_runtime);
    IntT val2 = pop<IntT>(sp, code, wasm_runtime);
    IntT val1 = pop<IntT>(sp, code, wasm_runtime);
    r0 = cond ? val1 : val2;
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_AnyConvertExtern()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_AnyConvertExtern (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6875 of file wasm-interpreter.cc.
                              {
    WasmRef extern_ref = pop<WasmRef>(sp, code, wasm_runtime);
    // Pass 0 as canonical type index; see implementation of builtin
    // WasmAnyConvertExtern.
    WasmRef result = wasm_runtime->WasmJSToWasmObject(
        extern_ref, kWasmAnyRef, 0 /* canonical type index */);
    if (V8_UNLIKELY(result.is_null())) {
      wasm::TrapReason reason = WasmInterpreterThread::GetRuntimeLastWasmError(
          wasm_runtime->GetIsolate());
      INLINED_TRAP(reason)
    }
    push<WasmRef>(sp, code, wasm_runtime, result);
    NextOp();
  }
References code, v8::internal::wasm::WasmInterpreterThread::GetRuntimeLastWasmError(), INLINED_TRAP, v8::internal::wasm::kWasmAnyRef, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::base::internal::result, and V8_UNLIKELY.
s2s_ArrayCopy()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ArrayCopy (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6492 of file wasm-interpreter.cc.
                                                                 {
    const uint32_t dest_array_index = Read<int32_t>(code);
    const uint32_t src_array_index = Read<int32_t>(code);
    // TODO(paolosev@microsoft.com): already validated?
    if (V8_UNLIKELY(!Smi::IsValid(dest_array_index) ||
                    !Smi::IsValid(src_array_index))) {
      TRAP(TrapReason::kTrapArrayOutOfBounds)
    }
    uint32_t size = pop<int32_t>(sp, code, wasm_runtime);
    uint32_t src_offset = pop<int32_t>(sp, code, wasm_runtime);
    WasmRef src_array = pop<WasmRef>(sp, code, wasm_runtime);
    uint32_t dest_offset = pop<int32_t>(sp, code, wasm_runtime);
    WasmRef dest_array = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(!Smi::IsValid(size) || !Smi::IsValid(src_offset) ||
                    !Smi::IsValid(dest_offset))) {
      TRAP(TrapReason::kTrapArrayOutOfBounds)
    } else if (V8_UNLIKELY(wasm_runtime->IsRefNull(dest_array))) {
      TRAP(TrapReason::kTrapNullDereference)
    } else if (V8_UNLIKELY(dest_offset + size >
                           Cast<WasmArray>(*dest_array)->length())) {
      TRAP(TrapReason::kTrapArrayOutOfBounds)
    } else if (V8_UNLIKELY(wasm_runtime->IsRefNull(src_array))) {
      TRAP(TrapReason::kTrapNullDereference)
    } else if (V8_UNLIKELY(src_offset + size >
                           Cast<WasmArray>(*src_array)->length())) {
      TRAP(TrapReason::kTrapArrayOutOfBounds)
    }
    bool ok = true;
    if (size > 0) {
      ok = wasm_runtime->WasmArrayCopy(dest_array, dest_offset, src_array,
                                       src_offset, size);
    }
    if (V8_UNLIKELY(!ok)) {
      wasm::TrapReason reason = WasmInterpreterThread::GetRuntimeLastWasmError(
          wasm_runtime->GetIsolate());
      INLINED_TRAP(reason)
    }
    NextOp();
  }
References code, v8::internal::wasm::WasmInterpreterThread::GetRuntimeLastWasmError(), INLINED_TRAP, v8::internal::Smi::IsValid(), v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, and V8_UNLIKELY.
s2s_ArrayFill()
template<bool Compressed>
template<typename T , typename U = T>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ArrayFill (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6648 of file wasm-interpreter.cc.
                                                                 {
    uint32_t size = pop<uint32_t>(sp, code, wasm_runtime);
    T value = pop<U>(sp, code, wasm_runtime);
    uint32_t offset = pop<uint32_t>(sp, code, wasm_runtime);
    WasmRef array_obj = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(array_obj))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    DCHECK(IsWasmArray(*array_obj));
    Tagged<WasmArray> array = Cast<WasmArray>(*array_obj);
    if (V8_UNLIKELY(static_cast<uint64_t>(offset) + size > array->length())) {
      TRAP(TrapReason::kTrapArrayOutOfBounds)
    }
    Address element_addr = array->ElementAddress(offset);
    for (uint32_t i = 0; i < size; i++) {
      base::WriteUnalignedValue<T>(element_addr, value);
      element_addr += sizeof(T);
    }
    NextOp();
  }
References code, v8::internal::DCHECK(), v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), T, TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, V8_UNLIKELY, and v8::internal::value.
s2s_ArrayGet()
template<bool Compressed>
template<typename T , typename U = T>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ArrayGet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6540 of file wasm-interpreter.cc.
                                                                {
    uint32_t index = pop<uint32_t>(sp, code, wasm_runtime);
    WasmRef array_obj = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(array_obj))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    DCHECK(IsWasmArray(*array_obj));
    Tagged<WasmArray> array = Cast<WasmArray>(*array_obj);
    if (V8_UNLIKELY(index >= array->length())) {
      TRAP(TrapReason::kTrapArrayOutOfBounds)
    }
    Address element_addr = array->ElementAddress(index);
    push<T>(sp, code, wasm_runtime, base::ReadUnalignedValue<U>(element_addr));
    NextOp();
  }
References code, v8::internal::DCHECK(), v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, and V8_UNLIKELY.
s2s_ArrayInitSegment()
template<bool Compressed>
template<bool init_data>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ArrayInitSegment (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6426 of file wasm-interpreter.cc.
                              {
    const uint32_t array_index = Read<int32_t>(code);
    // TODO(paolosev@microsoft.com): already validated?
    if (V8_UNLIKELY(!Smi::IsValid(array_index))) {
      TRAP(TrapReason::kTrapArrayOutOfBounds)
    }
    const uint32_t data_index = Read<int32_t>(code);
    // TODO(paolosev@microsoft.com): already validated?
    if (V8_UNLIKELY(!Smi::IsValid(data_index))) {
      TRAP(TrapReason::kTrapElementSegmentOutOfBounds)
    }
    uint32_t size = pop<int32_t>(sp, code, wasm_runtime);
    uint32_t src_offset = pop<int32_t>(sp, code, wasm_runtime);
    uint32_t dest_offset = pop<int32_t>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(!Smi::IsValid(size)) || !Smi::IsValid(dest_offset)) {
      TRAP(TrapReason::kTrapArrayOutOfBounds)
    }
    if (V8_UNLIKELY(!Smi::IsValid(src_offset))) {
      TrapReason reason = init_data
                              ? TrapReason::kTrapDataSegmentOutOfBounds
                              : TrapReason::kTrapElementSegmentOutOfBounds;
      INLINED_TRAP(reason);
    }
    WasmRef array = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(array))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    bool ok = wasm_runtime->WasmArrayInitSegment(data_index, array, dest_offset,
                                                 src_offset, size);
    if (V8_UNLIKELY(!ok)) {
      TrapReason reason = WasmInterpreterThread::GetRuntimeLastWasmError(
          wasm_runtime->GetIsolate());
      INLINED_TRAP(reason)
    }
    NextOp();
  }
References code, v8::internal::wasm::WasmInterpreterThread::GetRuntimeLastWasmError(), INLINED_TRAP, v8::internal::Smi::IsValid(), v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, and V8_UNLIKELY.
s2s_ArrayLen()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ArrayLen (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6477 of file wasm-interpreter.cc.
                                                                {
    WasmRef array_obj = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(array_obj))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    DCHECK(IsWasmArray(*array_obj));
    Tagged<WasmArray> array = Cast<WasmArray>(*array_obj);
    push<int32_t>(sp, code, wasm_runtime, array->length());
    NextOp();
  }
References code, v8::internal::DCHECK(), v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, and V8_UNLIKELY.
s2s_ArrayNew()
template<bool Compressed>
template<typename T , typename U = T>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNew (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6151 of file wasm-interpreter.cc.
                                                                {
    const uint32_t array_index = Read<int32_t>(code);
    const uint32_t elem_count = pop<int32_t>(sp, code, wasm_runtime);
    const T value = pop<T>(sp, code, wasm_runtime);
    std::pair<DirectHandle<WasmArray>, const ArrayType*> array_new_result =
        wasm_runtime->ArrayNewUninitialized(elem_count, array_index);
    DirectHandle<WasmArray> array = array_new_result.first;
    if (V8_UNLIKELY(array.is_null())) {
      TRAP(TrapReason::kTrapArrayTooLarge)
    }
    {
      // The new array is uninitialized, which means GC might fail until
      // initialization.
      DisallowHeapAllocation no_gc;
      const ArrayType* array_type = array_new_result.second;
      const ValueKind kind = array_type->element_type().kind();
      const uint32_t element_size = value_kind_size(kind);
      DCHECK_EQ(element_size, sizeof(U));
      Address element_addr = array->ElementAddress(0);
      for (uint32_t i = 0; i < elem_count; i++) {
        base::WriteUnalignedValue<U>(element_addr, value);
        element_addr += element_size;
      }
    }
    push<WasmRef>(sp, code, wasm_runtime, array);
    NextOp();
  }
References code, DCHECK_EQ, v8::internal::wasm::ArrayType::element_type(), v8::internal::DirectHandle< T >::is_null(), v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, TRAP, v8::internal::U, v8::internal::wasm::Handlers< Compressed >::uint32_t, V8_UNLIKELY, v8::internal::value, and v8::internal::wasm::value_kind_size().
s2s_ArrayNewDefault()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewDefault (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6311 of file wasm-interpreter.cc.
                                  {
    const uint32_t array_index = Read<int32_t>(code);
    const uint32_t elem_count = pop<int32_t>(sp, code, wasm_runtime);
    std::pair<DirectHandle<WasmArray>, const ArrayType*> array_new_result =
        wasm_runtime->ArrayNewUninitialized(elem_count, array_index);
    DirectHandle<WasmArray> array = array_new_result.first;
    if (V8_UNLIKELY(array.is_null())) {
      TRAP(TrapReason::kTrapArrayTooLarge)
    }
    {
      // The new array is uninitialized, which means GC might fail until
      // initialization.
      DisallowHeapAllocation no_gc;
      const ArrayType* array_type = array_new_result.second;
      const ValueType element_type = array_type->element_type();
      const ValueKind kind = element_type.kind();
      const uint32_t element_size = value_kind_size(kind);
      Address element_addr = array->ElementAddress(0);
      uint32_t element_offset = array->element_offset(0);
      for (uint32_t i = 0; i < elem_count; i++) {
        switch (kind) {
          case kI8:
            *reinterpret_cast<int8_t*>(element_addr) = int8_t{};
            break;
          case kI16:
            base::WriteUnalignedValue<int16_t>(element_addr, int16_t{});
            break;
          case kI32:
            base::WriteUnalignedValue<int32_t>(element_addr, int32_t{});
            break;
          case kI64:
            base::WriteUnalignedValue<int64_t>(element_addr, int64_t{});
            break;
          case kF32:
            base::WriteUnalignedValue<float>(element_addr, float{});
            break;
          case kF64:
            base::WriteUnalignedValue<double>(element_addr, double{});
            break;
          case kS128:
            base::WriteUnalignedValue<Simd128>(element_addr, Simd128{});
            break;
          case kRef:
          case kRefNull:
            StoreRefIntoMemory(
                Cast<HeapObject>(*array), element_addr, element_offset,
                wasm_runtime->GetNullValue(element_type), SKIP_WRITE_BARRIER);
            break;
          default:
            UNREACHABLE();
        }
        element_addr += element_size;
        element_offset += element_size;
      }
    }
    push<WasmRef>(sp, code, wasm_runtime, array);
    NextOp();
  }
References code, v8::internal::wasm::ArrayType::element_type(), v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::DirectHandle< T >::is_null(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, v8::internal::wasm::Handlers< Compressed >::StoreRefIntoMemory(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, v8::internal::UNREACHABLE(), V8_UNLIKELY, and v8::internal::wasm::value_kind_size().
s2s_ArrayNewFixed()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewFixed (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6234 of file wasm-interpreter.cc.
                              {
    const uint32_t array_index = Read<int32_t>(code);
    const uint32_t elem_count = Read<int32_t>(code);
    std::pair<DirectHandle<WasmArray>, const ArrayType*> array_new_result =
        wasm_runtime->ArrayNewUninitialized(elem_count, array_index);
    DirectHandle<WasmArray> array = array_new_result.first;
    if (V8_UNLIKELY(array.is_null())) {
      TRAP(TrapReason::kTrapArrayTooLarge)
    }
    {
      // The new array is uninitialized, which means GC might fail until
      // initialization.
      DisallowHeapAllocation no_gc;
      if (elem_count > 0) {
        const ArrayType* array_type = array_new_result.second;
        const ValueKind kind = array_type->element_type().kind();
        const uint32_t element_size = value_kind_size(kind);
        Address element_addr = array->ElementAddress(elem_count - 1);
        uint32_t element_offset = array->element_offset(elem_count - 1);
        for (uint32_t i = 0; i < elem_count; i++) {
          switch (kind) {
            case kI8:
              *reinterpret_cast<int8_t*>(element_addr) =
                  pop<int32_t>(sp, code, wasm_runtime);
              break;
            case kI16:
              base::WriteUnalignedValue<int16_t>(
                  element_addr, pop<int32_t>(sp, code, wasm_runtime));
              break;
            case kI32:
              base::WriteUnalignedValue<int32_t>(
                  element_addr, pop<int32_t>(sp, code, wasm_runtime));
              break;
            case kI64:
              base::WriteUnalignedValue<int64_t>(
                  element_addr, pop<int64_t>(sp, code, wasm_runtime));
              break;
            case kF32:
              base::WriteUnalignedValue<float>(
                  element_addr, pop<float>(sp, code, wasm_runtime));
              break;
            case kF64:
              base::WriteUnalignedValue<double>(
                  element_addr, pop<double>(sp, code, wasm_runtime));
              break;
            case kS128:
              base::WriteUnalignedValue<Simd128>(
                  element_addr, pop<Simd128>(sp, code, wasm_runtime));
              break;
            case kRef:
            case kRefNull: {
              WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
              StoreRefIntoMemory(Cast<HeapObject>(*array), element_addr,
                                 element_offset, *ref, SKIP_WRITE_BARRIER);
              break;
            }
            default:
              UNREACHABLE();
          }
          element_addr -= element_size;
          element_offset -= element_size;
        }
      }
    }
    push<WasmRef>(sp, code, wasm_runtime, array);
    NextOp();
  }
References code, v8::internal::wasm::ArrayType::element_type(), v8::internal::DirectHandle< T >::is_null(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, v8::internal::wasm::Handlers< Compressed >::StoreRefIntoMemory(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, v8::internal::UNREACHABLE(), V8_UNLIKELY, and v8::internal::wasm::value_kind_size().
s2s_ArrayNewSegment()
template<bool Compressed>
template<TrapReason OutOfBoundsError>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewSegment (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6379 of file wasm-interpreter.cc.
                              {
    const uint32_t array_index = Read<int32_t>(code);
    // TODO(paolosev@microsoft.com): already validated?
    if (V8_UNLIKELY(!Smi::IsValid(array_index))) {
      TRAP(TrapReason::kTrapArrayOutOfBounds)
    }
    const uint32_t data_index = Read<int32_t>(code);
    // TODO(paolosev@microsoft.com): already validated?
    if (V8_UNLIKELY(!Smi::IsValid(data_index))) {
      TRAP(OutOfBoundsError)
    }
    uint32_t length = pop<int32_t>(sp, code, wasm_runtime);
    uint32_t offset = pop<int32_t>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(!Smi::IsValid(offset))) {
      TRAP(OutOfBoundsError)
    }
    if (V8_UNLIKELY(length >= static_cast<uint32_t>(WasmArray::MaxLength(
                                  wasm_runtime->GetArrayType(array_index))))) {
      TRAP(TrapReason::kTrapArrayTooLarge)
    }
    WasmRef result = wasm_runtime->WasmArrayNewSegment(array_index, data_index,
                                                       offset, length);
    if (V8_UNLIKELY(result.is_null())) {
      wasm::TrapReason reason = WasmInterpreterThread::GetRuntimeLastWasmError(
          wasm_runtime->GetIsolate());
      INLINED_TRAP(reason)
    }
    push<WasmRef>(sp, code, wasm_runtime, result);
    NextOp();
  }
References code, v8::internal::wasm::WasmInterpreterThread::GetRuntimeLastWasmError(), INLINED_TRAP, v8::internal::Smi::IsValid(), v8::internal::length, v8::internal::WasmArray::MaxLength(), v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::base::internal::result, TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, and V8_UNLIKELY.
s2s_ArraySet()
template<bool Compressed>
template<typename T , typename U = T>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ArraySet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6594 of file wasm-interpreter.cc.
                                                                {
    const T value = pop<T>(sp, code, wasm_runtime);
    const uint32_t index = pop<uint32_t>(sp, code, wasm_runtime);
    WasmRef array_obj = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(array_obj))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    DCHECK(IsWasmArray(*array_obj));
    Tagged<WasmArray> array = Cast<WasmArray>(*array_obj);
    if (V8_UNLIKELY(index >= array->length())) {
      TRAP(TrapReason::kTrapArrayOutOfBounds)
    }
    Address element_addr = array->ElementAddress(index);
    base::WriteUnalignedValue<U>(element_addr, value);
    NextOp();
  }
References code, v8::internal::DCHECK(), v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, V8_UNLIKELY, and v8::internal::value.
s2s_AssertNotNullTypecheck()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_AssertNotNullTypecheck (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6815 of file wasm-interpreter.cc.
                              {
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    const uint32_t ref_bitfield = Read<int32_t>(code);
    ValueType ref_type = ValueType::FromRawBitField(ref_bitfield);
    if (wasm_runtime->IsNullTypecheck(ref, ref_type)) {
      TRAP(TrapReason::kTrapIllegalCast)
    }
    push<WasmRef>(sp, code, wasm_runtime, ref);
    NextOp();
  }
References code, v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_AssertNullTypecheck()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_AssertNullTypecheck (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6800 of file wasm-interpreter.cc.
                              {
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    const uint32_t ref_bitfield = Read<int32_t>(code);
    ValueType ref_type = ValueType::FromRawBitField(ref_bitfield);
    if (!wasm_runtime->IsNullTypecheck(ref, ref_type)) {
      TRAP(TrapReason::kTrapIllegalCast)
    }
    push<WasmRef>(sp, code, wasm_runtime, ref);
    NextOp();
  }
References code, v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_AtomicFence()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_AtomicFence (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4326 of file wasm-interpreter.cc.
                                                                   {
    std::atomic_thread_fence(std::memory_order_seq_cst);
    NextOp();
  }
References v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_AtomicNotify()
template<bool Compressed>
template<typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_AtomicNotify (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4227 of file wasm-interpreter.cc.
                              {
    int32_t val = pop<int32_t>(sp, code, wasm_runtime);
    uint64_t offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    // Check alignment.
    const uint32_t align_mask = sizeof(int32_t) - 1;
    if (V8_UNLIKELY((effective_index & align_mask) != 0)) {
      TRAP(TrapReason::kTrapUnalignedAccess)
    }
    // Check bounds.
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(uint64_t),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    int32_t result = wasm_runtime->AtomicNotify(effective_index, val);
    push<int32_t>(sp, code, wasm_runtime, result);
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::base::internal::result, TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, and V8_UNLIKELY.
s2s_Branch()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Branch (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2852 of file wasm-interpreter.cc.
                                                              {
    int32_t target_offset = Read<int32_t>(code);
    code += (target_offset - kCodeOffsetSize);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_BranchIf()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_BranchIf (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2875 of file wasm-interpreter.cc.
                                                                {
    int32_t cond = pop<int32_t>(sp, code, wasm_runtime);
    int32_t if_true_offset = Read<int32_t>(code);
    if (cond) {
      // If condition is true, jump to the target branch.
      code += (if_true_offset - kCodeOffsetSize);
    }
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_BranchIfWithParams()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_BranchIfWithParams (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2903 of file wasm-interpreter.cc.
                              {
    int32_t cond = pop<int32_t>(sp, code, wasm_runtime);
    int32_t if_false_offset = Read<int32_t>(code);
    if (!cond) {
      // If condition is not true, jump to the false branch.
      code += (if_false_offset - kCodeOffsetSize);
    }
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_BranchOnCast()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCast (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5794 of file wasm-interpreter.cc.
                              {
    bool null_succeeds = Read<int32_t>(code);
    HeapType target_type =
        HeapType::FromBits(static_cast<uint32_t>(Read<int32_t>(code)));
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    const uint32_t ref_bitfield = Read<int32_t>(code);
    ValueType ref_type = ValueType::FromRawBitField(ref_bitfield);
    push<WasmRef>(sp, code, wasm_runtime, ref);
    int32_t no_branch_offset = Read<int32_t>(code);
    if (!DoRefCast(ref, ref_type, target_type, null_succeeds, wasm_runtime)) {
      // If condition is not true, jump to the 'false' branch.
      code += (no_branch_offset - kCodeOffsetSize);
    }
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::DoRefCast(), v8::internal::wasm::HeapType::FromBits(), v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_BranchOnCastFail()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCastFail (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5833 of file wasm-interpreter.cc.
                              {
    bool null_succeeds = Read<int32_t>(code);
    HeapType target_type =
        HeapType::FromBits(static_cast<uint32_t>(Read<int32_t>(code)));
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    const uint32_t ref_bitfield = Read<int32_t>(code);
    ValueType ref_type = ValueType::FromRawBitField(ref_bitfield);
    push<WasmRef>(sp, code, wasm_runtime, ref);
    int32_t branch_offset = Read<int32_t>(code);
    if (DoRefCast(ref, ref_type, target_type, null_succeeds, wasm_runtime)) {
      // If condition is true, jump to the 'true' branch.
      code += (branch_offset - kCodeOffsetSize);
    }
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::DoRefCast(), v8::internal::wasm::HeapType::FromBits(), v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_BranchOnNonNull()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNull (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5703 of file wasm-interpreter.cc.
                              {
    // TO(paolosev@microsoft.com): Implement peek<T>?
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    const uint32_t ref_bitfield = Read<int32_t>(code);
    ValueType ref_type = ValueType::FromRawBitField(ref_bitfield);
    push<WasmRef>(sp, code, wasm_runtime, ref);
    int32_t if_non_null_offset = Read<int32_t>(code);
    if (!wasm_runtime->IsNullTypecheck(ref, ref_type)) {
      // If condition is true (ref is not null), jump to the target branch.
      code += (if_non_null_offset - kCodeOffsetSize);
    }
    NextOp();
  }
References code, v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_BranchOnNonNullWithParams()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNullWithParams (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5723 of file wasm-interpreter.cc.
                              {
    // TO(paolosev@microsoft.com): Implement peek<T>?
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    const uint32_t ref_bitfield = Read<int32_t>(code);
    ValueType ref_type = ValueType::FromRawBitField(ref_bitfield);
    push<WasmRef>(sp, code, wasm_runtime, ref);
    int32_t if_non_null_offset = Read<int32_t>(code);
    if (wasm_runtime->IsNullTypecheck(ref, ref_type)) {
      // If condition is false (ref is null), jump to the false branch.
      code += (if_non_null_offset - kCodeOffsetSize);
    }
    NextOp();
  }
References code, v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_BranchOnNull()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNull (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5648 of file wasm-interpreter.cc.
                              {
    // TODO(paolosev@microsoft.com): Implement peek<T>?
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    const uint32_t ref_bitfield = Read<int32_t>(code);
    ValueType ref_type = ValueType::FromRawBitField(ref_bitfield);
    push<WasmRef>(sp, code, wasm_runtime, ref);
    int32_t if_null_offset = Read<int32_t>(code);
    if (wasm_runtime->IsNullTypecheck(ref, ref_type)) {
      // If condition is true (ref is null), jump to the target branch.
      code += (if_null_offset - kCodeOffsetSize);
    }
    NextOp();
  }
References code, v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_BranchOnNullWithParams()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNullWithParams (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5683 of file wasm-interpreter.cc.
                              {
    // TO(paolosev@microsoft.com): Implement peek<T>?
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    const uint32_t ref_bitfield = Read<int32_t>(code);
    ValueType ref_type = ValueType::FromRawBitField(ref_bitfield);
    push<WasmRef>(sp, code, wasm_runtime, ref);
    int32_t if_null_offset = Read<int32_t>(code);
    if (!wasm_runtime->IsNullTypecheck(ref, ref_type)) {
      // If condition is false (ref is not null), jump to the false branch.
      code += (if_null_offset - kCodeOffsetSize);
    }
    NextOp();
  }
References code, v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_BrTable()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_BrTable (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3193 of file wasm-interpreter.cc.
                                                               {
    uint32_t cond = pop<uint32_t>(sp, code, wasm_runtime);
    uint32_t table_length = Read<int32_t>(code);
    uint32_t index = cond < table_length ? cond : table_length;
    int32_t target_offset = base::ReadUnalignedValue<int32_t>(
        reinterpret_cast<Address>(code + index * kCodeOffsetSize));
    code += (target_offset + index * kCodeOffsetSize);
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_CallFunction()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CallFunction (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2961 of file wasm-interpreter.cc.
                              {
    uint32_t function_index = Read<int32_t>(code);
    uint32_t stack_pos = Read<int32_t>(code);
    slot_offset_t slot_offset = Read<slot_offset_t>(code);
    uint32_t ref_stack_fp_offset = Read<int32_t>(code);
    slot_offset_t return_slot_offset = 0;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) {
      return_slot_offset = Read<slot_offset_t>(code);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    wasm_runtime->ExecuteFunction(code, function_index, stack_pos,
                                  ref_stack_fp_offset, slot_offset,
                                  return_slot_offset);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_CallImportedFunction()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CallImportedFunction (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3011 of file wasm-interpreter.cc.
                              {
    uint32_t function_index = Read<int32_t>(code);
    uint32_t stack_pos = Read<int32_t>(code);
    slot_offset_t slot_offset = Read<slot_offset_t>(code);
    uint32_t ref_stack_fp_offset = Read<int32_t>(code);
    slot_offset_t return_slot_offset = 0;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) {
      return_slot_offset = Read<slot_offset_t>(code);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    wasm_runtime->ExecuteImportedFunction(code, function_index, stack_pos,
                                          ref_stack_fp_offset, slot_offset,
                                          return_slot_offset);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_CallIndirect()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CallIndirect (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3060 of file wasm-interpreter.cc.
                              {
    uint32_t entry_index = pop<uint32_t>(sp, code, wasm_runtime);
    uint32_t table_index = Read<int32_t>(code);
    uint32_t sig_index = Read<int32_t>(code);
    uint32_t stack_pos = Read<int32_t>(code);
    slot_offset_t slot_offset = Read<slot_offset_t>(code);
    uint32_t ref_stack_fp_offset = Read<int32_t>(code);
    slot_offset_t return_slot_offset = 0;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) {
      return_slot_offset = Read<slot_offset_t>(code);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    // This function can trap.
    wasm_runtime->ExecuteIndirectCall(code, table_index, sig_index, entry_index,
                                      stack_pos, sp, ref_stack_fp_offset,
                                      slot_offset, return_slot_offset, false);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_CallIndirect64()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CallIndirect64 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3083 of file wasm-interpreter.cc.
                              {
    uint64_t entry_index_64 = pop<uint64_t>(sp, code, wasm_runtime);
    if (entry_index_64 > std::numeric_limits<uint32_t>::max()) {
      TRAP(TrapReason::kTrapTableOutOfBounds)
    }
    uint32_t entry_index = static_cast<uint32_t>(entry_index_64);
    uint32_t table_index = Read<int32_t>(code);
    uint32_t sig_index = Read<int32_t>(code);
    uint32_t stack_pos = Read<int32_t>(code);
    slot_offset_t slot_offset = Read<slot_offset_t>(code);
    uint32_t ref_stack_fp_offset = Read<int32_t>(code);
    slot_offset_t return_slot_offset = 0;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) {
      return_slot_offset = Read<slot_offset_t>(code);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    // This function can trap.
    wasm_runtime->ExecuteIndirectCall(code, table_index, sig_index, entry_index,
                                      stack_pos, sp, ref_stack_fp_offset,
                                      slot_offset, return_slot_offset, false);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_CallRef()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CallRef (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5855 of file wasm-interpreter.cc.
                                                               {
    WasmRef func_ref = pop<WasmRef>(sp, code, wasm_runtime);
    uint32_t sig_index = Read<int32_t>(code);
    uint32_t stack_pos = Read<int32_t>(code);
    slot_offset_t slot_offset = Read<slot_offset_t>(code);
    uint32_t ref_stack_fp_offset = Read<int32_t>(code);
    slot_offset_t return_slot_offset = 0;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) {
      return_slot_offset = Read<slot_offset_t>(code);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(func_ref))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    // This can trap.
    wasm_runtime->ExecuteCallRef(code, func_ref, sig_index, stack_pos, sp,
                                 ref_stack_fp_offset, slot_offset,
                                 return_slot_offset, false);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, v8::internal::v8_flags, and V8_UNLIKELY.
s2s_Catch()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Catch (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2952 of file wasm-interpreter.cc.
                                                             {
    int32_t target_offset = Read<int32_t>(code);
    code += (target_offset - kCodeOffsetSize);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_CopySlot128()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot128 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3492 of file wasm-interpreter.cc.
                                                                   {
    slot_offset_t from = Read<slot_offset_t>(code);
    slot_offset_t to = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<Simd128>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<Simd128>(
            reinterpret_cast<Address>(sp + from)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace(
          "COPYSLOT128 %d %d %" PRIx64 "`%" PRIx64 "\n", from, to,
          base::ReadUnalignedValue<uint64_t>(
              reinterpret_cast<Address>(sp + to)),
          base::ReadUnalignedValue<uint64_t>(
              reinterpret_cast<Address>(sp + to + sizeof(uint64_t))));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
s2s_CopySlot32()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot32 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3413 of file wasm-interpreter.cc.
                                                                  {
    slot_offset_t from = Read<slot_offset_t>(code);
    slot_offset_t to = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<uint32_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(sp + from)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT32 %d %d %08x\n", from, to,
                          *reinterpret_cast<int32_t*>(sp + to));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
s2s_CopySlot32x2()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot32x2 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3434 of file wasm-interpreter.cc.
                              {
    slot_offset_t from = Read<slot_offset_t>(code);
    slot_offset_t to = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<uint32_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(sp + from)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT32 %d %d %08x\n", from, to,
                          base::ReadUnalignedValue<int32_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    from = Read<slot_offset_t>(code);
    to = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<uint32_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(sp + from)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT32 %d %d %08x\n", from, to,
                          base::ReadUnalignedValue<int32_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
s2s_CopySlot64()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot64 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3470 of file wasm-interpreter.cc.
                                                                  {
    slot_offset_t from = Read<slot_offset_t>(code);
    slot_offset_t to = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<uint64_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint64_t>(
            reinterpret_cast<Address>(sp + from)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT64 %d %d %" PRIx64 "\n", from, to,
                          base::ReadUnalignedValue<uint64_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
s2s_CopySlot64x2()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot64x2 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3517 of file wasm-interpreter.cc.
                              {
    slot_offset_t from = Read<slot_offset_t>(code);
    slot_offset_t to = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<uint64_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint64_t>(
            reinterpret_cast<Address>(sp + from)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT64 %d %d %" PRIx64 "\n", from, to,
                          base::ReadUnalignedValue<uint64_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    from = Read<slot_offset_t>(code);
    to = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<uint64_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint64_t>(
            reinterpret_cast<Address>(sp + from)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT64 %d %d %" PRIx64 "\n", from, to,
                          base::ReadUnalignedValue<uint64_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
s2s_CopySlot_ll()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_ll (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3257 of file wasm-interpreter.cc.
                                                                   {
    slot_offset_t to = Read<slot_offset_t>(code);
    slot_offset_t from0 = Read<slot_offset_t>(code);
    slot_offset_t from1 = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<uint32_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(sp + from0)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT32 %d %d %08x\n", from0, to,
                          *reinterpret_cast<int32_t*>(sp + to));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    to += sizeof(uint32_t) / sizeof(uint32_t);
    base::WriteUnalignedValue<uint32_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(sp + from1)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT32 %d %d %08x\n", from1, to,
                          *reinterpret_cast<int32_t*>(sp + to));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_CopySlot_lq()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_lq (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3295 of file wasm-interpreter.cc.
                                                                   {
    slot_offset_t to = Read<slot_offset_t>(code);
    slot_offset_t from0 = Read<slot_offset_t>(code);
    slot_offset_t from1 = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<uint64_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint64_t>(
            reinterpret_cast<Address>(sp + from0)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT64 %d %d %" PRIx64 "\n", from0, to,
                          base::ReadUnalignedValue<uint64_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    to += sizeof(uint64_t) / sizeof(uint32_t);
    base::WriteUnalignedValue<uint32_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(sp + from1)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT32 %d %d %08x\n", from1, to,
                          *reinterpret_cast<int32_t*>(sp + to));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_CopySlot_ql()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_ql (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3334 of file wasm-interpreter.cc.
                                                                   {
    slot_offset_t to = Read<slot_offset_t>(code);
    slot_offset_t from0 = Read<slot_offset_t>(code);
    slot_offset_t from1 = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<uint32_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(sp + from0)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT32 %d %d %08x\n", from0, to,
                          *reinterpret_cast<int32_t*>(sp + to));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    to += sizeof(uint32_t) / sizeof(uint32_t);
    base::WriteUnalignedValue<uint64_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint64_t>(
            reinterpret_cast<Address>(sp + from1)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT64 %d %d %" PRIx64 "\n", from1, to,
                          base::ReadUnalignedValue<uint64_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_CopySlot_qq()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_qq (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3373 of file wasm-interpreter.cc.
                                                                   {
    slot_offset_t to = Read<slot_offset_t>(code);
    slot_offset_t from0 = Read<slot_offset_t>(code);
    slot_offset_t from1 = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<uint64_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint64_t>(
            reinterpret_cast<Address>(sp + from0)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT64 %d %d %" PRIx64 "\n", from0, to,
                          base::ReadUnalignedValue<uint64_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    to += sizeof(uint64_t) / sizeof(uint32_t);
    base::WriteUnalignedValue<uint64_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint64_t>(
            reinterpret_cast<Address>(sp + from1)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOT64 %d %d %" PRIx64 "\n", from1, to,
                          base::ReadUnalignedValue<uint64_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_CopySlotMulti()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CopySlotMulti (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3208 of file wasm-interpreter.cc.
                              {
    uint32_t params_count = Read<int32_t>(code);
    DCHECK(params_count > 1 && params_count < 32);
    uint32_t arg_size_mask = Read<int32_t>(code);
    slot_offset_t to = Read<slot_offset_t>(code);
    for (uint32_t i = 0; i < params_count; i++) {
      slot_offset_t from = Read<slot_offset_t>(code);
      bool is_64 = arg_size_mask & (1 << i);
      if (is_64) {
        base::WriteUnalignedValue<uint64_t>(
            reinterpret_cast<Address>(sp + to),
            base::ReadUnalignedValue<uint64_t>(
                reinterpret_cast<Address>(sp + from)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
        if (v8_flags.trace_drumbrake_execution &&
            v8_flags.trace_drumbrake_execution_verbose) {
          wasm_runtime->Trace("COPYSLOT64 %d %d %" PRIx64 "\n", from, to,
                              base::ReadUnalignedValue<uint64_t>(
                                  reinterpret_cast<Address>(sp + to)));
        }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
        to += sizeof(uint64_t) / sizeof(uint32_t);
      } else {
        base::WriteUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(sp + to),
            base::ReadUnalignedValue<uint32_t>(
                reinterpret_cast<Address>(sp + from)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
        if (v8_flags.trace_drumbrake_execution &&
            v8_flags.trace_drumbrake_execution_verbose) {
          wasm_runtime->Trace("COPYSLOT32 %d %d %08x\n", from, to,
                              *reinterpret_cast<int32_t*>(sp + to));
        }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
        to += sizeof(uint32_t) / sizeof(uint32_t);
      }
    }
    NextOp();
  }
References code, v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_CopySlotRef()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_CopySlotRef (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3553 of file wasm-interpreter.cc.
                                                                   {
    uint32_t from = Read<int32_t>(code);
    uint32_t to = Read<int32_t>(code);
    wasm_runtime->StoreWasmRef(to, wasm_runtime->ExtractWasmRef(from));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("COPYSLOTREF %d %d\n", from, to);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_DataDrop()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_DataDrop (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3889 of file wasm-interpreter.cc.
                                                                {
    uint32_t index = Read<int32_t>(code);
    wasm_runtime->DataDrop(index);
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_DoSimdExtAddPairwise()
template<bool Compressed>
template<typename DstSimdType , typename SrcSimdType , typename Wide , typename Narrow >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdExtAddPairwise (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5535 of file wasm-interpreter.cc.
                              {
    constexpr int lanes = kSimd128Size / sizeof(DstSimdType::val[0]);
    auto v = pop<Simd128>(sp, code, wasm_runtime).template to<SrcSimdType>();
    DstSimdType res;
    for (int i = 0; i < lanes; ++i) {
      res.val[LANE(i, res)] =
          AddLong<Wide>(static_cast<Narrow>(v.val[LANE(i * 2, v)]),
                        static_cast<Narrow>(v.val[LANE(i * 2 + 1, v)]));
    }
    push<Simd128>(sp, code, wasm_runtime, Simd128(res));
    NextOp();
  }
References code, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kSimd128Size, LANE, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::res.
s2s_DoSimdExtMul()
template<bool Compressed>
uint32_t start INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdExtMul (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4998 of file wasm-interpreter.cc.
                              {
    s_type s2 = pop<Simd128>(sp, code, wasm_runtime).template to<s_type>();
    s_type s1 = pop<Simd128>(sp, code, wasm_runtime).template to<s_type>();
    auto end = start + (kSimd128Size / sizeof(wide));
    d_type res;
    uint32_t i = start;
    for (size_t dst = 0; i < end; ++i, ++dst) {
      // Need static_cast for unsigned narrow types.
      res.val[LANE(dst, res)] =
          MultiplyLong<wide>(static_cast<narrow>(s1.val[LANE(start, s1)]),
                             static_cast<narrow>(s2.val[LANE(start, s2)]));
    }
    push<Simd128>(sp, code, wasm_runtime, Simd128(res));
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::d_type, v8::internal::compiler::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kSimd128Size, LANE, v8::internal::wasm::Handlers< Compressed >::narrow, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::res, v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::wasm::Handlers< Compressed >::wide.
s2s_DoSimdLoadExtend()
template<bool Compressed>
template<typename s_type , typename wide_type , typename narrow_type , typename MemIdx , typename MemOffsetT >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadExtend (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5328 of file wasm-interpreter.cc.
                              {
    static_assert(sizeof(wide_type) == sizeof(narrow_type) * 2,
                  "size mismatch for wide and narrow types");
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    uint64_t offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    // Load 8 bytes and sign/zero extend to 16 bytes.
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(uint64_t),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    uint64_t v =
        base::ReadUnalignedValue<uint64_t>(reinterpret_cast<Address>(address));
    constexpr int lanes = kSimd128Size / sizeof(wide_type);
    s_type s;
    for (int i = 0; i < lanes; i++) {
      uint8_t shift = i * (sizeof(narrow_type) * 8);
      narrow_type el = static_cast<narrow_type>(v >> shift);
      s.val[LANE(i, s)] = static_cast<wide_type>(el);
    }
    push<Simd128>(sp, code, wasm_runtime, Simd128(s));
    NextOp();
  }
References code, v8::internal::index, v8::internal::kSimd128Size, LANE, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint8_t, and V8_UNLIKELY.
s2s_DoSimdLoadLane()
template<bool Compressed>
template<typename s_type , typename memory_type , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadLane (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5443 of file wasm-interpreter.cc.
                              {
    s_type value = pop<Simd128>(sp, code, wasm_runtime).template to<s_type>();
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    uint64_t offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(memory_type),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    memory_type loaded = base::ReadUnalignedValue<memory_type>(
        reinterpret_cast<Address>(address));
    uint16_t lane = Read<uint16_t>(code);
    value.val[LANE(lane, value)] = loaded;
    push<Simd128>(sp, code, wasm_runtime, Simd128(value));
    NextOp();
  }
References code, v8::internal::index, LANE, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint16_t, v8::internal::wasm::Handlers< Compressed >::uint8_t, V8_UNLIKELY, and v8::internal::value.
s2s_DoSimdLoadSplat()
template<bool Compressed>
template<typename s_type , typename load_type , typename MemIdx , typename MemOffsetT >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadSplat (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5282 of file wasm-interpreter.cc.
                              {
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    uint64_t offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(load_type),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    load_type v =
        base::ReadUnalignedValue<load_type>(reinterpret_cast<Address>(address));
    s_type s;
    for (size_t i = 0; i < arraysize(s.val); i++) {
      s.val[LANE(i, s)] = v;
    }
    push<Simd128>(sp, code, wasm_runtime, Simd128(s));
    NextOp();
  }
References arraysize, code, v8::internal::index, LANE, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint8_t, and V8_UNLIKELY.
s2s_DoSimdLoadZeroExtend()
template<bool Compressed>
template<typename s_type , typename load_type , typename MemIdx , typename MemOffsetT >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadZeroExtend (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5400 of file wasm-interpreter.cc.
                              {
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    uint64_t offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    // Load a single 32-bit or 64-bit element into the lowest bits of a v128
    // vector, and initialize all other bits of the v128 vector to zero.
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(load_type),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    load_type v =
        base::ReadUnalignedValue<load_type>(reinterpret_cast<Address>(address));
    s_type s;
    // All lanes are 0.
    for (size_t i = 0; i < arraysize(s.val); i++) {
      s.val[LANE(i, s)] = 0;
    }
    // Lane 0 is set to the loaded value.
    s.val[LANE(0, s)] = v;
    push<Simd128>(sp, code, wasm_runtime, Simd128(s));
    NextOp();
  }
References arraysize, code, v8::internal::index, LANE, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint8_t, and V8_UNLIKELY.
s2s_DoSimdStoreLane()
template<bool Compressed>
template<typename s_type , typename memory_type , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdStoreLane (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5489 of file wasm-interpreter.cc.
                              {
    // Extract a single lane, push it onto the stack, then store the lane.
    s_type value = pop<Simd128>(sp, code, wasm_runtime).template to<s_type>();
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    uint64_t offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(memory_type),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    uint16_t lane = Read<uint16_t>(code);
    memory_type res = value.val[LANE(lane, value)];
    base::WriteUnalignedValue<memory_type>(reinterpret_cast<Address>(address),
                                           res);
    NextOp();
  }
References code, v8::internal::index, LANE, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::res, TRAP, v8::internal::wasm::Handlers< Compressed >::uint16_t, v8::internal::wasm::Handlers< Compressed >::uint8_t, V8_UNLIKELY, and v8::internal::value.
s2s_Drop()
template<bool Compressed>
template<typename T >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Drop (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1035 of file wasm-interpreter.cc.
                                                            {
    pop<T>(sp, code, wasm_runtime);
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_ElemDrop()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ElemDrop (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4057 of file wasm-interpreter.cc.
                                                                {
    uint32_t index = Read<int32_t>(code);
    wasm_runtime->ElemDrop(index);
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_Else()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Else (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2943 of file wasm-interpreter.cc.
                                                            {
    int32_t target_offset = Read<int32_t>(code);
    code += (target_offset - kCodeOffsetSize);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_ExternConvertAny()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ExternConvertAny (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6893 of file wasm-interpreter.cc.
                              {
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    if (wasm_runtime->IsNullTypecheck(ref, kWasmAnyRef)) {
      ref = handle(wasm_runtime->GetNullValue(kWasmExternRef),
                   wasm_runtime->GetIsolate());
    }
    push<WasmRef>(sp, code, wasm_runtime, ref);
    NextOp();
  }
References code, v8::internal::handle(), v8::internal::wasm::kWasmAnyRef, v8::internal::wasm::kWasmExternRef, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_GlobalGet()
template<bool Compressed>
template<typename T >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_GlobalGet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 935 of file wasm-interpreter.cc.
                                                                 {
    uint32_t index = ReadGlobalIndex(code);
    uint8_t* src_addr = wasm_runtime->GetGlobalAddress(index);
    push<T>(sp, code, wasm_runtime,
            base::ReadUnalignedValue<T>(reinterpret_cast<Address>(src_addr)));
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::ReadGlobalIndex(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::wasm::Handlers< Compressed >::uint8_t.
s2s_GlobalSet()
template<bool Compressed>
template<typename T >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_GlobalSet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 990 of file wasm-interpreter.cc.
                                                                 {
    uint32_t index = ReadGlobalIndex(code);
    uint8_t* dst_addr = wasm_runtime->GetGlobalAddress(index);
    base::WriteUnalignedValue<T>(reinterpret_cast<Address>(dst_addr),
                                 pop<T>(sp, code, wasm_runtime));
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::ReadGlobalIndex(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::wasm::Handlers< Compressed >::uint8_t.
s2s_I31GetS()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_I31GetS (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6729 of file wasm-interpreter.cc.
                                                               {
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(ref))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    DCHECK(IsSmi(*ref));
    push<int32_t>(sp, code, wasm_runtime, i::Smi::ToInt(*ref));
    NextOp();
  }
References code, v8::internal::DCHECK(), v8::internal::IsSmi(), v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::Smi::ToInt(), TRAP, and V8_UNLIKELY.
s2s_I31GetU()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_I31GetU (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6742 of file wasm-interpreter.cc.
                                                               {
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(ref))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    DCHECK(IsSmi(*ref));
    push<uint32_t>(sp, code, wasm_runtime,
                   0x7fffffff & static_cast<uint32_t>(i::Smi::ToInt(*ref)));
    NextOp();
  }
References code, v8::internal::DCHECK(), v8::internal::IsSmi(), v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::Smi::ToInt(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, and V8_UNLIKELY.
s2s_I32AtomicWait()
template<bool Compressed>
template<typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_I32AtomicWait (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4257 of file wasm-interpreter.cc.
                              {
    int64_t timeout = pop<int64_t>(sp, code, wasm_runtime);
    int32_t val = pop<int32_t>(sp, code, wasm_runtime);
    uint64_t offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    // Check alignment.
    const uint32_t align_mask = sizeof(int32_t) - 1;
    if (V8_UNLIKELY((effective_index & align_mask) != 0)) {
      TRAP(TrapReason::kTrapUnalignedAccess)
    }
    // Check bounds.
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(uint64_t),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    // Check atomics wait allowed.
    if (!wasm_runtime->AllowsAtomicsWait()) {
      TRAP(TrapReason::kTrapUnreachable)
    }
    int32_t result = wasm_runtime->I32AtomicWait(effective_index, val, timeout);
    push<int32_t>(sp, code, wasm_runtime, result);
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::base::internal::result, TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, and V8_UNLIKELY.
s2s_I32ConvertI64()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_I32ConvertI64 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2423 of file wasm-interpreter.cc.
                              {
    push<int32_t>(sp, code, wasm_runtime,
                  0xffffffff & pop<int64_t>(sp, code, wasm_runtime));
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_I64AtomicWait()
template<bool Compressed>
template<typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_I64AtomicWait (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4292 of file wasm-interpreter.cc.
                              {
    int64_t timeout = pop<int64_t>(sp, code, wasm_runtime);
    int64_t val = pop<int64_t>(sp, code, wasm_runtime);
    uint64_t offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    // Check alignment.
    const uint32_t align_mask = sizeof(int64_t) - 1;
    if (V8_UNLIKELY((effective_index & align_mask) != 0)) {
      TRAP(TrapReason::kTrapUnalignedAccess)
    }
    // Check bounds.
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(uint64_t),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    // Check atomics wait allowed.
    if (!wasm_runtime->AllowsAtomicsWait()) {
      TRAP(TrapReason::kTrapUnreachable)
    }
    int32_t result = wasm_runtime->I64AtomicWait(effective_index, val, timeout);
    push<int32_t>(sp, code, wasm_runtime, result);
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::base::internal::result, TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, and V8_UNLIKELY.
s2s_If()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_If (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2930 of file wasm-interpreter.cc.
                                                          {
    int32_t cond = pop<int32_t>(sp, code, wasm_runtime);
    int32_t target_offset = Read<int32_t>(code);
    if (!cond) {
      code += (target_offset - kCodeOffsetSize);
    }
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::kCodeOffsetSize, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_LoadMem()
template<bool Compressed>
template<typename T , typename U = T, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_LoadMem (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1271 of file wasm-interpreter.cc.
                                                               {
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    MemOffsetT offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(U),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    U value = base::ReadUnalignedValue<U>(reinterpret_cast<Address>(address));
    push<T>(sp, code, wasm_runtime, value);
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::U, v8::internal::wasm::Handlers< Compressed >::uint8_t, V8_UNLIKELY, and v8::internal::value.
s2s_LoadMem_LocalSet()
template<bool Compressed>
template<typename T , typename U = T, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_LoadMem_LocalSet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1326 of file wasm-interpreter.cc.
                              {
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    MemOffsetT offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(U),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    U value = base::ReadUnalignedValue<U>(reinterpret_cast<Address>(address));
    slot_offset_t to = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<T>(reinterpret_cast<Address>(sp + to),
                                 static_cast<T>(value));
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::U, v8::internal::wasm::Handlers< Compressed >::uint8_t, V8_UNLIKELY, and v8::internal::value.
s2s_LoadStoreMem()
template<bool Compressed>
template<typename T , typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_LoadStoreMem (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1547 of file wasm-interpreter.cc.
                              {
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    MemOffsetT load_offset = Read<MemOffsetT>(code);
    uint64_t load_index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_load_index = load_offset + load_index;
    MemOffsetT store_offset = Read<MemOffsetT>(code);
    uint64_t store_index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_store_index = store_offset + store_index;
    if (V8_UNLIKELY(
            effective_load_index < load_index ||
            !base::IsInBounds<uint64_t>(effective_load_index, sizeof(T),
                                        wasm_runtime->GetMemorySize()) ||
            effective_store_index < store_offset ||
            !base::IsInBounds<uint64_t>(effective_store_index, sizeof(T),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* load_address = memory_start + effective_load_index;
    uint8_t* store_address = memory_start + effective_store_index;
    base::WriteUnalignedValue<T>(
        reinterpret_cast<Address>(store_address),
        base::ReadUnalignedValue<T>(reinterpret_cast<Address>(load_address)));
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint8_t, and V8_UNLIKELY.
s2s_Memory64Copy()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Copy (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3912 of file wasm-interpreter.cc.
                              {
    uint64_t size = pop<uint64_t>(sp, code, wasm_runtime);
    uint64_t value = pop<uint64_t>(sp, code, wasm_runtime);
    uint64_t dst = pop<uint64_t>(sp, code, wasm_runtime);
    // This function can trap.
    wasm_runtime->MemoryCopy(code, dst, value, size);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), and v8::internal::value.
s2s_Memory64Fill()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Fill (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3938 of file wasm-interpreter.cc.
                              {
    uint64_t size = pop<uint64_t>(sp, code, wasm_runtime);
    uint32_t value = pop<uint32_t>(sp, code, wasm_runtime);
    uint64_t dst = pop<uint64_t>(sp, code, wasm_runtime);
    // This function can trap.
    wasm_runtime->MemoryFill(code, dst, value, size);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::value.
s2s_Memory64Grow()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Grow (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2811 of file wasm-interpreter.cc.
                              {
    int64_t result = -1;
    uint64_t delta_pages = pop<uint64_t>(sp, code, wasm_runtime);
    if (delta_pages <= std::numeric_limits<uint32_t>::max()) {
      result = wasm_runtime->MemoryGrow(static_cast<uint32_t>(delta_pages));
    }
    push<int64_t>(sp, code, wasm_runtime, result);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::base::internal::result, and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_Memory64Init()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Init (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3875 of file wasm-interpreter.cc.
                              {
    uint32_t data_segment_index = Read<int32_t>(code);
    uint64_t size = pop<uint32_t>(sp, code, wasm_runtime);
    uint64_t src = pop<uint32_t>(sp, code, wasm_runtime);
    uint64_t dst = pop<uint64_t>(sp, code, wasm_runtime);
    // This function can trap.
    wasm_runtime->MemoryInit(code, data_segment_index, dst, src, size);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_Memory64Size()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Size (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2836 of file wasm-interpreter.cc.
                              {
    uint64_t result = wasm_runtime->MemorySize();
    push<uint64_t>(sp, code, wasm_runtime, result);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::base::internal::result.
s2s_MemoryCopy()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_MemoryCopy (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3899 of file wasm-interpreter.cc.
                                                                  {
    uint64_t size = pop<uint32_t>(sp, code, wasm_runtime);
    uint64_t src = pop<uint32_t>(sp, code, wasm_runtime);
    uint64_t dst = pop<uint32_t>(sp, code, wasm_runtime);
    // This function can trap.
    wasm_runtime->MemoryCopy(code, dst, src, size);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and size().
s2s_MemoryFill()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_MemoryFill (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3925 of file wasm-interpreter.cc.
                                                                  {
    uint64_t size = pop<uint32_t>(sp, code, wasm_runtime);
    uint32_t value = pop<uint32_t>(sp, code, wasm_runtime);
    uint64_t dst = pop<uint32_t>(sp, code, wasm_runtime);
    // This function can trap.
    wasm_runtime->MemoryFill(code, dst, value, size);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::value.
s2s_MemoryGrow()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_MemoryGrow (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2799 of file wasm-interpreter.cc.
                                                                  {
    uint32_t delta_pages = pop<uint32_t>(sp, code, wasm_runtime);
    int32_t result = wasm_runtime->MemoryGrow(delta_pages);
    push<int32_t>(sp, code, wasm_runtime, result);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::base::internal::result, and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_MemoryInit()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_MemoryInit (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3861 of file wasm-interpreter.cc.
                                                                  {
    uint32_t data_segment_index = Read<int32_t>(code);
    uint64_t size = pop<uint32_t>(sp, code, wasm_runtime);
    uint64_t src = pop<uint32_t>(sp, code, wasm_runtime);
    uint64_t dst = pop<uint32_t>(sp, code, wasm_runtime);
    // This function can trap.
    wasm_runtime->MemoryInit(code, data_segment_index, dst, src, size);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_MemorySize()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_MemorySize (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2827 of file wasm-interpreter.cc.
                                                                  {
    uint64_t result = wasm_runtime->MemorySize();
    push<uint32_t>(sp, code, wasm_runtime, static_cast<uint32_t>(result));
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::base::internal::result, and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_OnLoopBegin()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_OnLoopBegin (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4206 of file wasm-interpreter.cc.
                                                                   {
    wasm_runtime->WasmStackCheck(code, code);
    wasm_runtime->ResetCurrentHandleScope();
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_OnLoopBeginNoRefSlots()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_OnLoopBeginNoRefSlots (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4215 of file wasm-interpreter.cc.
                              {
    wasm_runtime->WasmStackCheck(code, code);
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_PreserveCopySlot128()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_PreserveCopySlot128 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3624 of file wasm-interpreter.cc.
                              {
    slot_offset_t from = Read<slot_offset_t>(code);
    slot_offset_t to = Read<slot_offset_t>(code);
    slot_offset_t preserve = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<Simd128>(
        reinterpret_cast<Address>(sp + preserve),
        base::ReadUnalignedValue<Simd128>(reinterpret_cast<Address>(sp + to)));
    base::WriteUnalignedValue<Simd128>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<Simd128>(
            reinterpret_cast<Address>(sp + from)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace(
          "PRESERVECOPYSLOT64 %d %d %" PRIx64 "`%" PRIx64 "\n", from, to,
          base::ReadUnalignedValue<uint64_t>(
              reinterpret_cast<Address>(sp + to)),
          base::ReadUnalignedValue<uint64_t>(
              reinterpret_cast<Address>(sp + to + sizeof(uint64_t))));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
s2s_PreserveCopySlot32()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_PreserveCopySlot32 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3570 of file wasm-interpreter.cc.
                              {
    slot_offset_t from = Read<slot_offset_t>(code);
    slot_offset_t to = Read<slot_offset_t>(code);
    slot_offset_t preserve = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<uint32_t>(
        reinterpret_cast<Address>(sp + preserve),
        base::ReadUnalignedValue<uint32_t>(reinterpret_cast<Address>(sp + to)));
    base::WriteUnalignedValue<uint32_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint32_t>(
            reinterpret_cast<Address>(sp + from)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("PRESERVECOPYSLOT32 %d %d %08x\n", from, to,
                          base::ReadUnalignedValue<int32_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
s2s_PreserveCopySlot64()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_PreserveCopySlot64 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3597 of file wasm-interpreter.cc.
                              {
    slot_offset_t from = Read<slot_offset_t>(code);
    slot_offset_t to = Read<slot_offset_t>(code);
    slot_offset_t preserve = Read<slot_offset_t>(code);
    base::WriteUnalignedValue<uint64_t>(
        reinterpret_cast<Address>(sp + preserve),
        base::ReadUnalignedValue<uint64_t>(reinterpret_cast<Address>(sp + to)));
    base::WriteUnalignedValue<uint64_t>(
        reinterpret_cast<Address>(sp + to),
        base::ReadUnalignedValue<uint64_t>(
            reinterpret_cast<Address>(sp + from)));
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution &&
        v8_flags.trace_drumbrake_execution_verbose) {
      wasm_runtime->Trace("PRESERVECOPYSLOT64 %d %d %" PRIx64 "\n", from, to,
                          base::ReadUnalignedValue<uint64_t>(
                              reinterpret_cast<Address>(sp + to)));
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::v8_flags.
s2s_RefArrayFill()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayFill (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6682 of file wasm-interpreter.cc.
                              {
    // DrumBrake currently only works with pointer compression.
    static_assert(COMPRESS_POINTERS_BOOL);
    uint32_t size = pop<uint32_t>(sp, code, wasm_runtime);
    WasmRef value = pop<WasmRef>(sp, code, wasm_runtime);
    Tagged<Object> tagged_value = *value;
    uint32_t offset = pop<uint32_t>(sp, code, wasm_runtime);
    WasmRef array_obj = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(array_obj))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    DCHECK(IsWasmArray(*array_obj));
    Tagged<WasmArray> array = Cast<WasmArray>(*array_obj);
    if (V8_UNLIKELY(static_cast<uint64_t>(offset) + size > array->length())) {
      TRAP(TrapReason::kTrapArrayOutOfBounds)
    }
    Address element_addr = array->ElementAddress(offset);
    uint32_t element_offset = array->element_offset(offset);
    for (uint32_t i = 0; i < size; i++) {
      StoreRefIntoMemory(array, element_addr, element_offset, tagged_value,
                         UPDATE_WRITE_BARRIER);
      element_addr += kTaggedSize;
      element_offset += kTaggedSize;
    }
    NextOp();
  }
References code, COMPRESS_POINTERS_BOOL, v8::internal::DCHECK(), v8::internal::kTaggedSize, v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), v8::internal::wasm::Handlers< Compressed >::StoreRefIntoMemory(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, v8::internal::UPDATE_WRITE_BARRIER, V8_UNLIKELY, and v8::internal::value.
s2s_RefArrayGet()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayGet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6570 of file wasm-interpreter.cc.
                                                                   {
    uint32_t index = pop<uint32_t>(sp, code, wasm_runtime);
    WasmRef array_obj = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(array_obj))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    DCHECK(IsWasmArray(*array_obj));
    Tagged<WasmArray> array = Cast<WasmArray>(*array_obj);
    if (V8_UNLIKELY(index >= array->length())) {
      TRAP(TrapReason::kTrapArrayOutOfBounds)
    }
    WasmRef element =
        Handle<Object>(*wasm_runtime->GetWasmArrayRefElement(array, index),
                       wasm_runtime->GetIsolate());
    push<WasmRef>(sp, code, wasm_runtime, element);
    NextOp();
  }
References code, v8::internal::DCHECK(), v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, and V8_UNLIKELY.
s2s_RefArrayNew()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayNew (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6194 of file wasm-interpreter.cc.
                                                                   {
    const uint32_t array_index = Read<int32_t>(code);
    const uint32_t elem_count = pop<int32_t>(sp, code, wasm_runtime);
    const WasmRef value = pop<WasmRef>(sp, code, wasm_runtime);
    std::pair<DirectHandle<WasmArray>, const ArrayType*> array_new_result =
        wasm_runtime->ArrayNewUninitialized(elem_count, array_index);
    DirectHandle<WasmArray> array = array_new_result.first;
    if (V8_UNLIKELY(array.is_null())) {
      TRAP(TrapReason::kTrapArrayTooLarge)
    }
#if DEBUG
    const ArrayType* array_type = array_new_result.second;
    DCHECK_EQ(value_kind_size(array_type->element_type().kind()),
              sizeof(Tagged_t));
#endif
    {
      // The new array is uninitialized, which means GC might fail until
      // initialization.
      DisallowHeapAllocation no_gc;
      Address element_addr = array->ElementAddress(0);
      uint32_t element_offset = array->element_offset(0);
      for (uint32_t i = 0; i < elem_count; i++) {
        StoreRefIntoMemory(Cast<HeapObject>(*array), element_addr,
                           element_offset, *value, SKIP_WRITE_BARRIER);
        element_addr += sizeof(Tagged_t);
        element_offset += sizeof(Tagged_t);
      }
    }
    push<WasmRef>(sp, code, wasm_runtime, array);
    NextOp();
  }
References code, DCHECK_EQ, v8::internal::wasm::ArrayType::element_type(), v8::internal::DirectHandle< T >::is_null(), v8::internal::wasm::ValueTypeBase::kind(), v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, v8::internal::wasm::Handlers< Compressed >::StoreRefIntoMemory(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, V8_UNLIKELY, v8::internal::value, and v8::internal::wasm::value_kind_size().
s2s_RefArraySet()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefArraySet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6623 of file wasm-interpreter.cc.
                                                                   {
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    const uint32_t index = pop<uint32_t>(sp, code, wasm_runtime);
    WasmRef array_obj = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(array_obj))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    DCHECK(IsWasmArray(*array_obj));
    Tagged<WasmArray> array = Cast<WasmArray>(*array_obj);
    if (V8_UNLIKELY(index >= array->length())) {
      TRAP(TrapReason::kTrapArrayOutOfBounds)
    }
    Address element_addr = array->ElementAddress(index);
    uint32_t element_offset = array->element_offset(index);
    StoreRefIntoMemory(array, element_addr, element_offset, *ref,
                       UPDATE_WRITE_BARRIER);
    NextOp();
  }
References code, v8::internal::DCHECK(), v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::StoreRefIntoMemory(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, v8::internal::UPDATE_WRITE_BARRIER, and V8_UNLIKELY.
s2s_RefAsNonNull()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefAsNonNull (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6863 of file wasm-interpreter.cc.
                              {
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(ref))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    push<WasmRef>(sp, code, wasm_runtime, ref);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, and V8_UNLIKELY.
s2s_RefDrop()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefDrop (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1048 of file wasm-interpreter.cc.
                                                               {
    pop<WasmRef>(sp, code, wasm_runtime);
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_RefEq()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefEq (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3851 of file wasm-interpreter.cc.
                                                             {
    WasmRef lhs = pop<WasmRef>(sp, code, wasm_runtime);
    WasmRef rhs = pop<WasmRef>(sp, code, wasm_runtime);
    push<int32_t>(sp, code, wasm_runtime, lhs.is_identical_to(rhs) ? 1 : 0);
    NextOp();
  }
References code, v8::internal::DirectHandle< T >::is_identical_to(), and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_RefFunc()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefFunc (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3842 of file wasm-interpreter.cc.
                                                               {
    uint32_t index = Read<int32_t>(code);
    push<WasmRef>(sp, code, wasm_runtime, wasm_runtime->GetFunctionRef(index));
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_RefGlobalGet()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefGlobalGet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 951 of file wasm-interpreter.cc.
                              {
    uint32_t index = ReadGlobalIndex(code);
    push<WasmRef>(sp, code, wasm_runtime, wasm_runtime->GetGlobalRef(index));
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::ReadGlobalIndex(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_RefGlobalSet()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefGlobalSet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1005 of file wasm-interpreter.cc.
                              {
    uint32_t index = ReadGlobalIndex(code);
    wasm_runtime->SetGlobalRef(index, pop<WasmRef>(sp, code, wasm_runtime));
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::ReadGlobalIndex(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_RefI31()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefI31 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6716 of file wasm-interpreter.cc.
                                                              {
    uint32_t value = pop<int32_t>(sp, code, wasm_runtime);
    // Truncate high bit.
    Tagged<Smi> smi(Internals::IntToSmi(value & 0x7fffffff));
    push<WasmRef>(sp, code, wasm_runtime,
                  handle(smi, wasm_runtime->GetIsolate()));
    NextOp();
  }
References code, v8::internal::handle(), v8::internal::Internals::IntToSmi(), v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::value.
s2s_RefIsNonNull()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefIsNonNull (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6854 of file wasm-interpreter.cc.
                              {
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    push<int32_t>(sp, code, wasm_runtime, wasm_runtime->IsRefNull(ref) ? 0 : 1);
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_RefIsNull()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefIsNull (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3833 of file wasm-interpreter.cc.
                                                                 {
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    push<int32_t>(sp, code, wasm_runtime, wasm_runtime->IsRefNull(ref) ? 1 : 0);
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_RefNull()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefNull (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3820 of file wasm-interpreter.cc.
                                                               {
    const uint32_t ref_bitfield = Read<int32_t>(code);
    ValueType ref_type = ValueType::FromRawBitField(ref_bitfield);
    push<WasmRef>(sp, code, wasm_runtime,
                  handle(wasm_runtime->GetNullValue(ref_type),
                         wasm_runtime->GetIsolate()));
    NextOp();
  }
References code, v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::handle(), v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_RefSelect()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefSelect (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1923 of file wasm-interpreter.cc.
                                                                 {
    int32_t cond = pop<int32_t>(sp, code, wasm_runtime);
    WasmRef val2 = pop<WasmRef>(sp, code, wasm_runtime);
    WasmRef val1 = pop<WasmRef>(sp, code, wasm_runtime);
    push<WasmRef>(sp, code, wasm_runtime, cond ? val1 : val2);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_RefStructGet()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefStructGet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6088 of file wasm-interpreter.cc.
                              {
    WasmRef struct_obj = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(struct_obj))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    int offset = Read<int32_t>(code);
    Address field_addr = (*struct_obj).ptr() + offset;
    // DrumBrake expects pointer compression.
    Tagged_t ref_tagged = base::ReadUnalignedValue<uint32_t>(field_addr);
    Isolate* isolate = Isolate::Current();
    Tagged<Object> ref_uncompressed(
        V8HeapCompressionScheme::DecompressTagged(ref_tagged));
    WasmRef ref_handle = handle(ref_uncompressed, isolate);
    push<WasmRef>(sp, code, wasm_runtime, ref_handle);
    NextOp();
  }
References code, v8::internal::Isolate::Current(), v8::internal::V8HeapCompressionSchemeImpl< Cage >::DecompressTagged(), v8::internal::handle(), v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, and V8_UNLIKELY.
s2s_RefStructSet()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefStructSet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6131 of file wasm-interpreter.cc.
                              {
    int field_offset = Read<int32_t>(code);
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    WasmRef struct_obj = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(struct_obj))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    Address field_addr = (*struct_obj).ptr() + field_offset;
    StoreRefIntoMemory(
        Cast<HeapObject>(*struct_obj), field_addr,
        field_offset +
            kHeapObjectTag, // field_offset is offset into tagged object.
        *ref, UPDATE_WRITE_BARRIER);
    NextOp();
  }
References code, v8::internal::kHeapObjectTag, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::StoreRefIntoMemory(), TRAP, v8::internal::UPDATE_WRITE_BARRIER, and V8_UNLIKELY.
s2s_RefTestFails()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefTestFails (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6845 of file wasm-interpreter.cc.
                               {
    pop<WasmRef>(sp, code, wasm_runtime);
    push<int32_t>(sp, code, wasm_runtime, 0); // false
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_RefTestSucceeds()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_RefTestSucceeds (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6835 of file wasm-interpreter.cc.
                                      {
    pop<WasmRef>(sp, code, wasm_runtime);
    push<int32_t>(sp, code, wasm_runtime, 1); // true
    NextOp();
  }
References code, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_Rethrow()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Rethrow (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5636 of file wasm-interpreter.cc.
                                                               {
    uint32_t catch_block_index = Read<int32_t>(code);
    wasm_runtime->RethrowException(code, sp, catch_block_index);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_Return()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Return (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2845 of file wasm-interpreter.cc.
                                                              {
    // Break the chain of calls.
    Read<int32_t>(code);
  }
References code.
s2s_ReturnCall()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCall (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 2981 of file wasm-interpreter.cc.
                                                                  {
    slot_offset_t rets_size = Read<slot_offset_t>(code);
    slot_offset_t args_size = Read<slot_offset_t>(code);
    uint32_t rets_refs = Read<int32_t>(code);
    uint32_t args_refs = Read<int32_t>(code);
    uint32_t function_index = Read<int32_t>(code);
    uint32_t stack_pos = Read<int32_t>(code);
    slot_offset_t slot_offset = Read<slot_offset_t>(code);
    uint32_t ref_stack_fp_offset = Read<int32_t>(code);
    slot_offset_t return_slot_offset = 0;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) {
      return_slot_offset = Read<slot_offset_t>(code);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    // Moves back the stack frame to the caller stack frame.
    wasm_runtime->UnwindCurrentStackFrame(sp, slot_offset, rets_size, args_size,
                                          rets_refs, args_refs,
                                          ref_stack_fp_offset);
    // Do not call wasm_runtime->ExecuteFunction(), which would add a
    // new C++ stack frame.
    wasm_runtime->PrepareTailCall(code, function_index, stack_pos,
                                  return_slot_offset);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_ReturnCallImportedFunction()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallImportedFunction (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3031 of file wasm-interpreter.cc.
                              {
    slot_offset_t rets_size = Read<slot_offset_t>(code);
    slot_offset_t args_size = Read<slot_offset_t>(code);
    uint32_t rets_refs = Read<int32_t>(code);
    uint32_t args_refs = Read<int32_t>(code);
    uint32_t function_index = Read<int32_t>(code);
    uint32_t stack_pos = Read<int32_t>(code);
    slot_offset_t slot_offset = Read<slot_offset_t>(code);
    uint32_t ref_stack_fp_offset = Read<int32_t>(code);
    slot_offset_t return_slot_offset = 0;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) {
      return_slot_offset = Read<slot_offset_t>(code);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    // Moves back the stack frame to the caller stack frame.
    wasm_runtime->UnwindCurrentStackFrame(sp, slot_offset, rets_size, args_size,
                                          rets_refs, args_refs,
                                          ref_stack_fp_offset);
    wasm_runtime->ExecuteImportedFunction(code, function_index, stack_pos, 0, 0,
                                          return_slot_offset, true);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_ReturnCallIndirect()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallIndirect (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3110 of file wasm-interpreter.cc.
                              {
    slot_offset_t rets_size = Read<slot_offset_t>(code);
    slot_offset_t args_size = Read<slot_offset_t>(code);
    uint32_t rets_refs = Read<int32_t>(code);
    uint32_t args_refs = Read<int32_t>(code);
    uint32_t entry_index = pop<uint32_t>(sp, code, wasm_runtime);
    uint32_t table_index = Read<int32_t>(code);
    uint32_t sig_index = Read<int32_t>(code);
    uint32_t stack_pos = Read<int32_t>(code);
    slot_offset_t slot_offset = Read<slot_offset_t>(code);
    uint32_t ref_stack_fp_offset = Read<int32_t>(code);
    slot_offset_t return_slot_offset = 0;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) {
      return_slot_offset = Read<slot_offset_t>(code);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    // Moves back the stack frame to the caller stack frame.
    wasm_runtime->UnwindCurrentStackFrame(sp, slot_offset, rets_size, args_size,
                                          rets_refs, args_refs,
                                          ref_stack_fp_offset);
    // This function can trap.
    wasm_runtime->ExecuteIndirectCall(code, table_index, sig_index, entry_index,
                                      stack_pos, sp, 0, 0, return_slot_offset,
                                      true);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_ReturnCallIndirect64()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallIndirect64 (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3142 of file wasm-interpreter.cc.
                              {
    slot_offset_t rets_size = Read<slot_offset_t>(code);
    slot_offset_t args_size = Read<slot_offset_t>(code);
    uint32_t rets_refs = Read<int32_t>(code);
    uint32_t args_refs = Read<int32_t>(code);
    uint64_t entry_index_64 = pop<uint64_t>(sp, code, wasm_runtime);
    if (entry_index_64 > std::numeric_limits<uint32_t>::max()) {
      TRAP(TrapReason::kTrapTableOutOfBounds)
    }
    uint32_t entry_index = static_cast<uint32_t>(entry_index_64);
    uint32_t table_index = Read<int32_t>(code);
    uint32_t sig_index = Read<int32_t>(code);
    uint32_t stack_pos = Read<int32_t>(code);
    slot_offset_t slot_offset = Read<slot_offset_t>(code);
    uint32_t ref_stack_fp_offset = Read<int32_t>(code);
    slot_offset_t return_slot_offset = 0;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) {
      return_slot_offset = Read<slot_offset_t>(code);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    // Moves back the stack frame to the caller stack frame.
    wasm_runtime->UnwindCurrentStackFrame(sp, slot_offset, rets_size, args_size,
                                          rets_refs, args_refs,
                                          ref_stack_fp_offset);
    // This function can trap.
    wasm_runtime->ExecuteIndirectCall(code, table_index, sig_index, entry_index,
                                      stack_pos, sp, 0, 0, return_slot_offset,
                                      true);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::v8_flags.
s2s_ReturnCallRef()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallRef (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5881 of file wasm-interpreter.cc.
                              {
    slot_offset_t rets_size = Read<slot_offset_t>(code);
    slot_offset_t args_size = Read<slot_offset_t>(code);
    uint32_t rets_refs = Read<int32_t>(code);
    uint32_t args_refs = Read<int32_t>(code);
    WasmRef func_ref = pop<WasmRef>(sp, code, wasm_runtime);
    uint32_t sig_index = Read<int32_t>(code);
    uint32_t stack_pos = Read<int32_t>(code);
    slot_offset_t slot_offset = Read<slot_offset_t>(code);
    uint32_t ref_stack_fp_offset = Read<int32_t>(code);
    slot_offset_t return_slot_offset = 0;
#ifdef V8_ENABLE_DRUMBRAKE_TRACING
    if (v8_flags.trace_drumbrake_execution) {
      return_slot_offset = Read<slot_offset_t>(code);
    }
#endif // V8_ENABLE_DRUMBRAKE_TRACING
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(func_ref))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    // Moves back the stack frame to the caller stack frame.
    wasm_runtime->UnwindCurrentStackFrame(sp, slot_offset, rets_size, args_size,
                                          rets_refs, args_refs,
                                          ref_stack_fp_offset);
    // TODO(paolosev@microsoft.com) - This calls adds a new C++ stack frame,
    // which is not ideal in a tail-call.
    wasm_runtime->ExecuteCallRef(code, func_ref, sig_index, stack_pos, sp, 0, 0,
                                 return_slot_offset, true);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, v8::internal::v8_flags, and V8_UNLIKELY.
s2s_Select()
template<bool Compressed>
template<typename T >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Select (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1906 of file wasm-interpreter.cc.
                                                              {
    int32_t cond = pop<int32_t>(sp, code, wasm_runtime);
    T val2 = pop<T>(sp, code, wasm_runtime);
    T val1 = pop<T>(sp, code, wasm_runtime);
    push<T>(sp, code, wasm_runtime, cond ? val1 : val2);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, and v8::internal::wasm::Handlers< Compressed >::NextOp().
s2s_SimdI16x8DotI8x16I7x16S()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8DotI8x16I7x16S (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5162 of file wasm-interpreter.cc.
                              {
    int8x16 v2 = pop<Simd128>(sp, code, wasm_runtime).to_i8x16();
    int8x16 v1 = pop<Simd128>(sp, code, wasm_runtime).to_i8x16();
    int16x8 res;
    for (size_t i = 0; i < 8; i++) {
      int16_t lo = (v1.val[LANE(i * 2, v1)] * v2.val[LANE(i * 2, v2)]);
      int16_t hi = (v1.val[LANE(i * 2 + 1, v1)] * v2.val[LANE(i * 2 + 1, v2)]);
      res.val[LANE(i, res)] = base::AddWithWraparound(lo, hi);
    }
    push<Simd128>(sp, code, wasm_runtime, Simd128(res));
    NextOp();
  }
References code, v8::internal::hi, v8::internal::wasm::Handlers< Compressed >::int16x8, v8::internal::wasm::Handlers< Compressed >::int8x16, LANE, v8::internal::lo, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::res, v8::internal::wasm::Handlers< Compressed >::v1, and v8::internal::wasm::Handlers< Compressed >::v2.
s2s_SimdI32x4DotI16x8S()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI16x8S (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5147 of file wasm-interpreter.cc.
                              {
    int16x8 v2 = pop<Simd128>(sp, code, wasm_runtime).to_i16x8();
    int16x8 v1 = pop<Simd128>(sp, code, wasm_runtime).to_i16x8();
    int32x4 res;
    for (size_t i = 0; i < 4; i++) {
      int32_t lo = (v1.val[LANE(i * 2, v1)] * v2.val[LANE(i * 2, v2)]);
      int32_t hi = (v1.val[LANE(i * 2 + 1, v1)] * v2.val[LANE(i * 2 + 1, v2)]);
      res.val[LANE(i, res)] = base::AddWithWraparound(lo, hi);
    }
    push<Simd128>(sp, code, wasm_runtime, Simd128(res));
    NextOp();
  }
References code, v8::internal::hi, v8::internal::wasm::Handlers< Compressed >::int16x8, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::int32x4, LANE, v8::internal::lo, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::res, v8::internal::wasm::Handlers< Compressed >::v1, and v8::internal::wasm::Handlers< Compressed >::v2.
s2s_SimdI32x4DotI8x16I7x16AddS()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI8x16I7x16AddS (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5177 of file wasm-interpreter.cc.
                              {
    int32x4 v3 = pop<Simd128>(sp, code, wasm_runtime).to_i32x4();
    int8x16 v2 = pop<Simd128>(sp, code, wasm_runtime).to_i8x16();
    int8x16 v1 = pop<Simd128>(sp, code, wasm_runtime).to_i8x16();
    int32x4 res;
    for (size_t i = 0; i < 4; i++) {
      int32_t a = (v1.val[LANE(i * 4, v1)] * v2.val[LANE(i * 4, v2)]);
      int32_t b = (v1.val[LANE(i * 4 + 1, v1)] * v2.val[LANE(i * 4 + 1, v2)]);
      int32_t c = (v1.val[LANE(i * 4 + 2, v1)] * v2.val[LANE(i * 4 + 2, v2)]);
      int32_t d = (v1.val[LANE(i * 4 + 3, v1)] * v2.val[LANE(i * 4 + 3, v2)]);
      int32_t acc = v3.val[LANE(i, v3)];
      // a + b + c + d should not wrap
      res.val[LANE(i, res)] = base::AddWithWraparound(a + b + c + d, acc);
    }
    push<Simd128>(sp, code, wasm_runtime, Simd128(res));
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::int32x4, v8::internal::wasm::Handlers< Compressed >::int8x16, LANE, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::res, v8::internal::wasm::Handlers< Compressed >::v1, and v8::internal::wasm::Handlers< Compressed >::v2.
s2s_SimdI8x16Shuffle()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Shuffle (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5213 of file wasm-interpreter.cc.
                              {
    int8x16 value = pop<Simd128>(sp, code, wasm_runtime).to_i8x16();
    int8x16 v2 = pop<Simd128>(sp, code, wasm_runtime).to_i8x16();
    int8x16 v1 = pop<Simd128>(sp, code, wasm_runtime).to_i8x16();
    int8x16 res;
    for (size_t i = 0; i < kSimd128Size; ++i) {
      int lane = value.val[i];
      res.val[LANE(i, res)] = lane < kSimd128Size
                                  ? v1.val[LANE(lane, v1)]
                                  : v2.val[LANE(lane - kSimd128Size, v2)];
    }
    push<Simd128>(sp, code, wasm_runtime, Simd128(res));
    NextOp();
  }
References code, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::Handlers< Compressed >::int8x16, v8::internal::kSimd128Size, LANE, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::res, v8::internal::wasm::Handlers< Compressed >::v1, v8::internal::wasm::Handlers< Compressed >::v2, and v8::internal::value.
s2s_SimdI8x16Swizzle()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Swizzle (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5197 of file wasm-interpreter.cc.
                              {
    int8x16 v2 = pop<Simd128>(sp, code, wasm_runtime).to_i8x16();
    int8x16 v1 = pop<Simd128>(sp, code, wasm_runtime).to_i8x16();
    int8x16 res;
    for (size_t i = 0; i < kSimd128Size; ++i) {
      int lane = v2.val[LANE(i, v2)];
      res.val[LANE(i, res)] =
          lane < kSimd128Size && lane >= 0 ? v1.val[LANE(lane, v1)] : 0;
    }
    push<Simd128>(sp, code, wasm_runtime, Simd128(res));
    NextOp();
  }
References code, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::Handlers< Compressed >::int8x16, v8::internal::kSimd128Size, LANE, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::res, v8::internal::wasm::Handlers< Compressed >::v1, and v8::internal::wasm::Handlers< Compressed >::v2.
s2s_SimdS128StoreMemI()
template<bool Compressed>
template<typename MemIdx , typename MemOffsetT >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128StoreMemI (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4932 of file wasm-interpreter.cc.
                              {
    Simd128 val = pop<Simd128>(sp, code, wasm_runtime);
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    uint64_t offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(Simd128),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    base::WriteUnalignedValue<Simd128>(reinterpret_cast<Address>(address), val);
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint8_t, and V8_UNLIKELY.
s2s_SimdV128AnyTrue()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_SimdV128AnyTrue (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5230 of file wasm-interpreter.cc.
                              {
    int32x4 s = pop<Simd128>(sp, code, wasm_runtime).to_i32x4();
    bool res = s.val[LANE(0, s)] | s.val[LANE(1, s)] | s.val[LANE(2, s)] |
               s.val[LANE(3, s)];
    push<int32_t>(sp, code, wasm_runtime, res);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32x4, LANE, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::res.
s2s_StoreMem()
template<bool Compressed>
template<typename T , typename U = T, typename MemIdx = uint32_t, typename MemOffsetT = memory_offset32_t>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_StoreMem (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 1457 of file wasm-interpreter.cc.
                                                                {
    T value = pop<T>(sp, code, wasm_runtime);
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    MemOffsetT offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(U),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    base::WriteUnalignedValue<U>(
        reinterpret_cast<Address>(address),
        base::ReadUnalignedValue<U>(reinterpret_cast<Address>(&value)));
    NextOp();
  }
References code, v8::internal::index, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::U, v8::internal::wasm::Handlers< Compressed >::uint8_t, V8_UNLIKELY, and v8::internal::value.
s2s_StructGet()
template<bool Compressed>
template<typename T , typename U = T>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_StructGet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6064 of file wasm-interpreter.cc.
                                                                 {
    WasmRef struct_obj = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(struct_obj))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    int offset = Read<int32_t>(code);
    Address field_addr = (*struct_obj).ptr() + offset;
    push<T>(sp, code, wasm_runtime, base::ReadUnalignedValue<U>(field_addr));
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, and V8_UNLIKELY.
s2s_StructNew()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_StructNew (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5931 of file wasm-interpreter.cc.
                                                                 {
    uint32_t index = Read<int32_t>(code);
    std::pair<DirectHandle<WasmStruct>, const StructType*> struct_new_result =
        wasm_runtime->StructNewUninitialized(index);
    DirectHandle<HeapObject> struct_obj = struct_new_result.first;
    const StructType* struct_type = struct_new_result.second;
    {
      // The new struct is uninitialized, which means GC might fail until
      // initialization.
      DisallowHeapAllocation no_gc;
      for (uint32_t i = struct_type->field_count(); i > 0;) {
        i--;
        int field_offset = StructFieldOffset(struct_type, i);
        Address field_addr = (*struct_obj).ptr() + field_offset;
        ValueKind kind = struct_type->field(i).kind();
        switch (kind) {
          case kI8:
            *reinterpret_cast<int8_t*>(field_addr) =
                pop<int32_t>(sp, code, wasm_runtime);
            break;
          case kI16:
            base::WriteUnalignedValue<int16_t>(
                field_addr, pop<int32_t>(sp, code, wasm_runtime));
            break;
          case kI32:
            base::WriteUnalignedValue<int32_t>(
                field_addr, pop<int32_t>(sp, code, wasm_runtime));
            break;
          case kI64:
            base::WriteUnalignedValue<int64_t>(
                field_addr, pop<int64_t>(sp, code, wasm_runtime));
            break;
          case kF32:
            base::WriteUnalignedValue<float>(
                field_addr, pop<float>(sp, code, wasm_runtime));
            break;
          case kF64:
            base::WriteUnalignedValue<double>(
                field_addr, pop<double>(sp, code, wasm_runtime));
            break;
          case kS128:
            base::WriteUnalignedValue<Simd128>(
                field_addr, pop<Simd128>(sp, code, wasm_runtime));
            break;
          case kRef:
          case kRefNull: {
            WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
            StoreRefIntoMemory(
                *struct_obj, field_addr,
                field_offset + kHeapObjectTag, // field_offset is offset into
                                                // tagged object.
                *ref, SKIP_WRITE_BARRIER);
            break;
          }
          default:
            UNREACHABLE();
        }
      }
    }
    push<WasmRef>(sp, code, wasm_runtime, struct_obj);
    NextOp();
  }
References code, v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::index, v8::internal::kF32, v8::internal::kF64, v8::internal::kHeapObjectTag, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, v8::internal::wasm::Handlers< Compressed >::StoreRefIntoMemory(), v8::internal::wasm::StructFieldOffset(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::UNREACHABLE().
s2s_StructNewDefault()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_StructNewDefault (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6001 of file wasm-interpreter.cc.
                              {
    uint32_t index = Read<int32_t>(code);
    std::pair<DirectHandle<WasmStruct>, const StructType*> struct_new_result =
        wasm_runtime->StructNewUninitialized(index);
    DirectHandle<HeapObject> struct_obj = struct_new_result.first;
    const StructType* struct_type = struct_new_result.second;
    {
      // The new struct is uninitialized, which means GC might fail until
      // initialization.
      DisallowHeapAllocation no_gc;
      for (uint32_t i = struct_type->field_count(); i > 0;) {
        i--;
        int field_offset = StructFieldOffset(struct_type, i);
        Address field_addr = (*struct_obj).ptr() + field_offset;
        const ValueType value_type = struct_type->field(i);
        const ValueKind kind = value_type.kind();
        switch (kind) {
          case kI8:
            *reinterpret_cast<int8_t*>(field_addr) = int8_t{};
            break;
          case kI16:
            base::WriteUnalignedValue<int16_t>(field_addr, int16_t{});
            break;
          case kI32:
            base::WriteUnalignedValue<int32_t>(field_addr, int32_t{});
            break;
          case kI64:
            base::WriteUnalignedValue<int64_t>(field_addr, int64_t{});
            break;
          case kF32:
            base::WriteUnalignedValue<float>(field_addr, float{});
            break;
          case kF64:
            base::WriteUnalignedValue<double>(field_addr, double{});
            break;
          case kS128:
            base::WriteUnalignedValue<Simd128>(field_addr, Simd128{});
            break;
          case kRef:
          case kRefNull:
            StoreRefIntoMemory(
                *struct_obj, field_addr,
                field_offset + kHeapObjectTag, // field_offset is offset into
                                                // tagged object.
                wasm_runtime->GetNullValue(value_type), SKIP_WRITE_BARRIER);
            break;
          default:
            UNREACHABLE();
        }
      }
    }
    push<WasmRef>(sp, code, wasm_runtime, struct_obj);
    NextOp();
  }
References code, v8::internal::wasm::StructType::field(), v8::internal::wasm::StructTypeBase::field_count(), v8::internal::index, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::kF32, v8::internal::kF64, v8::internal::kHeapObjectTag, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::wasm::ValueTypeBase::kind(), v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::SKIP_WRITE_BARRIER, v8::internal::wasm::Handlers< Compressed >::StoreRefIntoMemory(), v8::internal::wasm::StructFieldOffset(), v8::internal::wasm::Handlers< Compressed >::uint32_t, v8::internal::UNREACHABLE(), and v8::internal::wasm::value_type().
s2s_StructSet()
template<bool Compressed>
template<typename T , typename U = T>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_StructSet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6109 of file wasm-interpreter.cc.
                                                                 {
    int offset = Read<int32_t>(code);
    T value = pop<T>(sp, code, wasm_runtime);
    WasmRef struct_obj = pop<WasmRef>(sp, code, wasm_runtime);
    if (V8_UNLIKELY(wasm_runtime->IsRefNull(struct_obj))) {
      TRAP(TrapReason::kTrapNullDereference)
    }
    Address field_addr = (*struct_obj).ptr() + offset;
    base::WriteUnalignedValue<U>(field_addr, value);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, V8_UNLIKELY, and v8::internal::value.
s2s_Table64CopyImpl()
template<bool Compressed>
template<typename IntN , typename IntM , typename IntK >
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Table64CopyImpl (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4084 of file wasm-interpreter.cc.
                              {
    uint32_t dst_table_index = Read<int32_t>(code);
    uint32_t src_table_index = Read<int32_t>(code);
    auto size_64 = pop<IntK>(sp, code, wasm_runtime);
    auto src_64 = pop<IntM>(sp, code, wasm_runtime);
    auto dst_64 = pop<IntN>(sp, code, wasm_runtime);
    if (src_64 > std::numeric_limits<uint32_t>::max() ||
        dst_64 > std::numeric_limits<uint32_t>::max() ||
        size_64 > std::numeric_limits<uint32_t>::max()) {
      TRAP(TrapReason::kTrapTableOutOfBounds)
    }
    uint32_t size = static_cast<uint32_t>(size_64);
    uint32_t src = static_cast<uint32_t>(src_64);
    uint32_t dst = static_cast<uint32_t>(dst_64);
    // This function can trap.
    wasm_runtime->TableCopy(code, dst_table_index, src_table_index, dst, src,
                            size);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), TRAP, and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_Table64Fill()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Table64Fill (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4184 of file wasm-interpreter.cc.
                                                                   {
    uint32_t table_index = Read<int32_t>(code);
    uint64_t count_64 = pop<uint64_t>(sp, code, wasm_runtime);
    WasmRef value = pop<WasmRef>(sp, code, wasm_runtime);
    uint64_t start_64 = pop<uint64_t>(sp, code, wasm_runtime);
    if (count_64 > std::numeric_limits<uint32_t>::max() ||
        start_64 > std::numeric_limits<uint32_t>::max()) {
      TRAP(TrapReason::kTrapTableOutOfBounds)
    }
    uint32_t count = static_cast<uint32_t>(count_64);
    uint32_t start = static_cast<uint32_t>(start_64);
    // This function can trap.
    wasm_runtime->TableFill(code, table_index, count, value, start);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::value.
s2s_Table64Get()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Table64Get (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3966 of file wasm-interpreter.cc.
                                                                  {
    uint32_t table_index = Read<int32_t>(code);
    uint64_t entry_index_64 = pop<uint64_t>(sp, code, wasm_runtime);
    if (entry_index_64 > std::numeric_limits<uint32_t>::max()) {
      TRAP(TrapReason::kTrapTableOutOfBounds)
    }
    uint32_t entry_index = static_cast<uint32_t>(entry_index_64);
    // This function can trap.
    WasmRef ref;
    if (wasm_runtime->TableGet(code, table_index, entry_index, &ref)) {
      push<WasmRef>(sp, code, wasm_runtime, ref);
    }
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_Table64Grow()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Table64Grow (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4129 of file wasm-interpreter.cc.
                                                                   {
    uint32_t table_index = Read<int32_t>(code);
    uint64_t delta_64 = pop<uint64_t>(sp, code, wasm_runtime);
    WasmRef value = pop<WasmRef>(sp, code, wasm_runtime);
    if (delta_64 > std::numeric_limits<uint32_t>::max()) {
      push<int64_t>(sp, code, wasm_runtime, -1);
    } else {
      uint32_t delta = static_cast<uint32_t>(delta_64);
      uint32_t result = wasm_runtime->TableGrow(table_index, delta, value);
      push<int64_t>(sp, code, wasm_runtime,
                    static_cast<int64_t>(static_cast<int32_t>(result)));
    }
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::int32_t, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::base::internal::result, v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::value.
s2s_Table64Init()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Table64Init (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4035 of file wasm-interpreter.cc.
                                                                   {
    uint32_t table_index = Read<int32_t>(code);
    uint32_t element_segment_index = Read<int32_t>(code);
    uint32_t size = pop<uint32_t>(sp, code, wasm_runtime);
    uint32_t src = pop<uint32_t>(sp, code, wasm_runtime);
    uint64_t dst_64 = pop<uint64_t>(sp, code, wasm_runtime);
    if (dst_64 > std::numeric_limits<uint32_t>::max()) {
      TRAP(TrapReason::kTrapTableOutOfBounds)
    }
    uint32_t dst = static_cast<uint32_t>(dst_64);
    // This function can trap.
    wasm_runtime->TableInit(code, table_index, element_segment_index, dst, src,
                            size);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), TRAP, and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_Table64Set()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Table64Set (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4000 of file wasm-interpreter.cc.
                                                                  {
    uint32_t table_index = Read<int32_t>(code);
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    uint64_t entry_index_64 = pop<uint64_t>(sp, code, wasm_runtime);
    if (entry_index_64 > std::numeric_limits<uint32_t>::max()) {
      TRAP(TrapReason::kTrapTableOutOfBounds)
    }
    uint32_t entry_index = static_cast<uint32_t>(entry_index_64);
    // This function can trap.
    wasm_runtime->TableSet(code, table_index, entry_index, ref);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), TRAP, and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_Table64Size()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Table64Size (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4159 of file wasm-interpreter.cc.
                                                                   {
    uint32_t table_index = Read<int32_t>(code);
    uint64_t size = wasm_runtime->TableSize(table_index);
    push<uint64_t>(sp, code, wasm_runtime, size);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_TableCopy()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_TableCopy (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4067 of file wasm-interpreter.cc.
                                                                 {
    uint32_t dst_table_index = Read<int32_t>(code);
    uint32_t src_table_index = Read<int32_t>(code);
    auto size = pop<uint32_t>(sp, code, wasm_runtime);
    auto src = pop<uint32_t>(sp, code, wasm_runtime);
    auto dst = pop<uint32_t>(sp, code, wasm_runtime);
    // This function can trap.
    wasm_runtime->TableCopy(code, dst_table_index, src_table_index, dst, src,
                            size);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_TableFill()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_TableFill (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4170 of file wasm-interpreter.cc.
                                                                 {
    uint32_t table_index = Read<int32_t>(code);
    uint32_t count = pop<uint32_t>(sp, code, wasm_runtime);
    WasmRef value = pop<WasmRef>(sp, code, wasm_runtime);
    uint32_t start = pop<uint32_t>(sp, code, wasm_runtime);
    // This function can trap.
    wasm_runtime->TableFill(code, table_index, count, value, start);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::value.
s2s_TableGet()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_TableGet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3951 of file wasm-interpreter.cc.
                                                                {
    uint32_t table_index = Read<int32_t>(code);
    uint32_t entry_index = pop<uint32_t>(sp, code, wasm_runtime);
    // This function can trap.
    WasmRef ref;
    if (wasm_runtime->TableGet(code, table_index, entry_index, &ref)) {
      push<WasmRef>(sp, code, wasm_runtime, ref);
    }
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_TableGrow()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_TableGrow (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4116 of file wasm-interpreter.cc.
                                                                 {
    uint32_t table_index = Read<int32_t>(code);
    uint32_t delta = pop<uint32_t>(sp, code, wasm_runtime);
    WasmRef value = pop<WasmRef>(sp, code, wasm_runtime);
    uint32_t result = wasm_runtime->TableGrow(table_index, delta, value);
    push<int32_t>(sp, code, wasm_runtime, result);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::base::internal::result, v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::value.
s2s_TableInit()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_TableInit (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4019 of file wasm-interpreter.cc.
                                                                 {
    uint32_t table_index = Read<int32_t>(code);
    uint32_t element_segment_index = Read<int32_t>(code);
    uint32_t size = pop<uint32_t>(sp, code, wasm_runtime);
    uint32_t src = pop<uint32_t>(sp, code, wasm_runtime);
    uint32_t dst = pop<uint32_t>(sp, code, wasm_runtime);
    // This function can trap.
    wasm_runtime->TableInit(code, table_index, element_segment_index, dst, src,
                            size);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_TableSet()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_TableSet (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 3987 of file wasm-interpreter.cc.
                                                                {
    uint32_t table_index = Read<int32_t>(code);
    WasmRef ref = pop<WasmRef>(sp, code, wasm_runtime);
    uint32_t entry_index = pop<uint32_t>(sp, code, wasm_runtime);
    // This function can trap.
    wasm_runtime->TableSet(code, table_index, entry_index, ref);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_TableSize()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_TableSize (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 4148 of file wasm-interpreter.cc.
                                                                 {
    uint32_t table_index = Read<int32_t>(code);
    uint32_t size = wasm_runtime->TableSize(table_index);
    push<int32_t>(sp, code, wasm_runtime, size);
    NextOp();
  }
References code, v8::internal::wasm::Handlers< Compressed >::NextOp(), size(), and v8::internal::wasm::Handlers< Compressed >::uint32_t.
s2s_Throw()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_Throw (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 5563 of file wasm-interpreter.cc.
                                                             {
    Isolate* isolate = Isolate::Current();
    {
      HandleScope handle_scope(isolate); // Avoid leaking handles.
      uint32_t tag_index = Read<int32_t>(code);
      DirectHandle<WasmExceptionPackage> exception_object =
          wasm_runtime->CreateWasmExceptionPackage(tag_index);
      DirectHandle<FixedArray> encoded_values = Cast<FixedArray>(
          WasmExceptionPackage::GetExceptionValues(isolate, exception_object));
      // Encode the exception values on the operand stack into the exception
      // package allocated above.
      const WasmTagSig* sig = wasm_runtime->GetWasmTag(tag_index).sig;
      uint32_t encoded_index = 0;
      for (size_t index = 0; index < sig->parameter_count(); index++) {
        switch (sig->GetParam(index).kind()) {
          case kI32: {
            uint32_t u32 = pop<uint32_t>(sp, code, wasm_runtime);
            EncodeI32ExceptionValue(encoded_values, &encoded_index, u32);
            break;
          }
          case kF32: {
            float f32 = pop<float>(sp, code, wasm_runtime);
            EncodeI32ExceptionValue(encoded_values, &encoded_index,
                                    *reinterpret_cast<uint32_t*>(&f32));
            break;
          }
          case kI64: {
            uint64_t u64 = pop<uint64_t>(sp, code, wasm_runtime);
            EncodeI64ExceptionValue(encoded_values, &encoded_index, u64);
            break;
          }
          case kF64: {
            double f64 = pop<double>(sp, code, wasm_runtime);
            EncodeI64ExceptionValue(encoded_values, &encoded_index,
                                    *reinterpret_cast<uint64_t*>(&f64));
            break;
          }
          case kS128: {
            int32x4 s128 = pop<Simd128>(sp, code, wasm_runtime).to_i32x4();
            EncodeI32ExceptionValue(encoded_values, &encoded_index,
                                    s128.val[0]);
            EncodeI32ExceptionValue(encoded_values, &encoded_index,
                                    s128.val[1]);
            EncodeI32ExceptionValue(encoded_values, &encoded_index,
                                    s128.val[2]);
            EncodeI32ExceptionValue(encoded_values, &encoded_index,
                                    s128.val[3]);
            break;
          }
          case kRef:
          case kRefNull: {
            DirectHandle<Object> ref = pop<WasmRef>(sp, code, wasm_runtime);
            if (IsWasmNull(*ref, isolate)) {
              ref = direct_handle(ReadOnlyRoots(isolate).null_value(), isolate);
            }
            encoded_values->set(encoded_index++, *ref);
            break;
          }
          default:
            UNREACHABLE();
        }
      }
      wasm_runtime->ThrowException(code, sp, *exception_object);
    }
    NextOp();
  }
References code, v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::EncodeI32ExceptionValue(), v8::internal::EncodeI64ExceptionValue(), v8::internal::WasmExceptionPackage::GetExceptionValues(), v8::internal::index, v8::internal::wasm::Handlers< Compressed >::int32x4, v8::internal::kF32, v8::internal::kF64, v8::internal::kI32, v8::internal::kI64, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::wasm::Handlers< Compressed >::NextOp(), v8::internal::sig, v8::internal::wasm::Handlers< Compressed >::uint32_t, and v8::internal::UNREACHABLE().
s2s_TrapIllegalCast()
template<bool Compressed>
INSTRUCTION_HANDLER_FUNC v8::internal::wasm::Handlers< Compressed >::s2s_TrapIllegalCast (const uint8_t * code, uint32_t * sp, WasmInterpreterRuntime * wasm_runtime, int64_t r0, double fp0) [inline]
Definition at line 6830 of file wasm-interpreter.cc.
                             {TRAP(TrapReason::kTrapIllegalCast)}
References TRAP.
SHIFT_CASE()
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::SHIFT_CASE (I64x2Shl , i64x2 , int64x2 , 2 , static_cast< uint64_t > a)<<(shift % 64)
static_cast() [1/11]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::static_cast (a) [inline]
Definition at line 4701 of file wasm-interpreter.cc.
                                                                     : b)
  BINOP_CASE(S128And, i32x4, int32x4, 4, a& b)
  BINOP_CASE(S128Or, i32x4, int32x4, 4, a | b)
  BINOP_CASE(S128Xor, i32x4, int32x4, 4, a ^ b)
  BINOP_CASE(S128AndNot, i32x4, int32x4, 4, a & ~b)
  BINOP_CASE(I16x8Add, i16x8, int16x8, 8, base::AddWithWraparound(a, b))
  BINOP_CASE(I16x8Sub, i16x8, int16x8, 8, base::SubWithWraparound(a, b))
  BINOP_CASE(I16x8Mul, i16x8, int16x8, 8, base::MulWithWraparound(a, b))
  BINOP_CASE(I16x8MinS, i16x8, int16x8, 8, a < b ? a : b)
  BINOP_CASE(I16x8MinU, i16x8, int16x8, 8,
             static_cast<uint16_t>(a) < static_cast<uint16_t>(b) ? a : b)
  BINOP_CASE(I16x8MaxS, i16x8, int16x8, 8, a > b ? a : b)
  BINOP_CASE(I16x8MaxU, i16x8, int16x8, 8,
             static_cast<uint16_t>(a) > static_cast<uint16_t>(b) ? a : b)
  BINOP_CASE(I16x8AddSatS, i16x8, int16x8, 8, SaturateAdd<int16_t>(a, b))
  BINOP_CASE(I16x8AddSatU, i16x8, int16x8, 8, SaturateAdd<uint16_t>(a, b))
  BINOP_CASE(I16x8SubSatS, i16x8, int16x8, 8, SaturateSub<int16_t>(a, b))
  BINOP_CASE(I16x8SubSatU, i16x8, int16x8, 8, SaturateSub<uint16_t>(a, b))
  BINOP_CASE(I16x8RoundingAverageU, i16x8, int16x8, 8,
             RoundingAverageUnsigned<uint16_t>(a, b))
  BINOP_CASE(I16x8Q15MulRSatS, i16x8, int16x8, 8,
             SaturateRoundingQMul<int16_t>(a, b))
  BINOP_CASE(I16x8RelaxedQ15MulRS, i16x8, int16x8, 8,
             SaturateRoundingQMul<int16_t>(a, b))
  BINOP_CASE(I8x16Add, i8x16, int8x16, 16, base::AddWithWraparound(a, b))
  BINOP_CASE(I8x16Sub, i8x16, int8x16, 16, base::SubWithWraparound(a, b))
  BINOP_CASE(I8x16MinS, i8x16, int8x16, 16, a < b ? a : b)
  BINOP_CASE(I8x16MinU, i8x16, int8x16, 16,
             static_cast<uint8_t>(a) < static_cast<uint8_t>(b) ? a : b)
  BINOP_CASE(I8x16MaxS, i8x16, int8x16, 16, a > b ? a : b)
  BINOP_CASE(I8x16MaxU, i8x16, int8x16, 16,
             static_cast<uint8_t>(a) > static_cast<uint8_t>(b) ? a : b)
  BINOP_CASE(I8x16AddSatS, i8x16, int8x16, 16, SaturateAdd<int8_t>(a, b))
  BINOP_CASE(I8x16AddSatU, i8x16, int8x16, 16, SaturateAdd<uint8_t>(a, b))
  BINOP_CASE(I8x16SubSatS, i8x16, int8x16, 16, SaturateSub<int8_t>(a, b))
  BINOP_CASE(I8x16SubSatU, i8x16, int8x16, 16, SaturateSub<uint8_t>(a, b))
  BINOP_CASE(I8x16RoundingAverageU, i8x16, int8x16, 16,
             RoundingAverageUnsigned<uint8_t>(a, b))
#undef BINOP_CASE
#define UNOP_CASE(op, name, stype, count, expr) \
  INSTRUCTION_HANDLER_FUNC s2s_Simd##op(const uint8_t* code, uint32_t* sp, \
                                        WasmInterpreterRuntime* wasm_runtime, \
                                        int64_t r0, double fp0) { \
    stype s = pop<Simd128>(sp, code, wasm_runtime).to_##name(); \
    stype res; \
    for (size_t i = 0; i < count; ++i) { \
      auto a = s.val[LANE(i, s)]; \
      res.val[LANE(i, res)] = expr; \
    } \
    push<Simd128>(sp, code, wasm_runtime, Simd128(res)); \
    NextOp(); \
  }
  UNOP_CASE(F64x2Abs, f64x2, float64x2, 2, std::abs(a))
  UNOP_CASE(F64x2Neg, f64x2, float64x2, 2, -a)
  UNOP_CASE(F64x2Sqrt, f64x2, float64x2, 2, std::sqrt(a))
  UNOP_CASE(F64x2Ceil, f64x2, float64x2, 2, ceil(a))
  UNOP_CASE(F64x2Floor, f64x2, float64x2, 2, floor(a))
  UNOP_CASE(F64x2Trunc, f64x2, float64x2, 2, trunc(a))
  UNOP_CASE(F64x2NearestInt, f64x2, float64x2, 2, nearbyint(a))
  UNOP_CASE(F32x4Abs, f32x4, float32x4, 4, std::abs(a))
  UNOP_CASE(F32x4Neg, f32x4, float32x4, 4, -a)
  UNOP_CASE(F32x4Sqrt, f32x4, float32x4, 4, std::sqrt(a))
  UNOP_CASE(F32x4Ceil, f32x4, float32x4, 4, ceilf(a))
  UNOP_CASE(F32x4Floor, f32x4, float32x4, 4, floorf(a))
  UNOP_CASE(F32x4Trunc, f32x4, float32x4, 4, truncf(a))
  UNOP_CASE(F32x4NearestInt, f32x4, float32x4, 4, nearbyintf(a))
  UNOP_CASE(I64x2Neg, i64x2, int64x2, 2, base::NegateWithWraparound(a))
  UNOP_CASE(I32x4Neg, i32x4, int32x4, 4, base::NegateWithWraparound(a))
  // Use llabs which will work correctly on both 64-bit and 32-bit.
  UNOP_CASE(I64x2Abs, i64x2, int64x2, 2, std::llabs(a))
  UNOP_CASE(I32x4Abs, i32x4, int32x4, 4, std::abs(a))
  UNOP_CASE(S128Not, i32x4, int32x4, 4, ~a)
  UNOP_CASE(I16x8Neg, i16x8, int16x8, 8, base::NegateWithWraparound(a))
  UNOP_CASE(I16x8Abs, i16x8, int16x8, 8, std::abs(a))
  UNOP_CASE(I8x16Neg, i8x16, int8x16, 16, base::NegateWithWraparound(a))
  UNOP_CASE(I8x16Abs, i8x16, int8x16, 16, std::abs(a))
  UNOP_CASE(I8x16Popcnt, i8x16, int8x16, 16,
            base::bits::CountPopulation<uint8_t>(a))
#undef UNOP_CASE
#define BITMASK_CASE(op, name, stype, count) \
  INSTRUCTION_HANDLER_FUNC s2s_Simd##op(const uint8_t* code, uint32_t* sp, \
                                        WasmInterpreterRuntime* wasm_runtime, \
                                        int64_t r0, double fp0) { \
    stype s = pop<Simd128>(sp, code, wasm_runtime).to_##name(); \
    int32_t res = 0; \
    for (size_t i = 0; i < count; ++i) { \
      bool sign = std::signbit(static_cast<double>(s.val[LANE(i, s)])); \
      res |= (sign << i); \
    } \
    push<int32_t>(sp, code, wasm_runtime, res); \
    NextOp(); \
  }
  BITMASK_CASE(I8x16BitMask, i8x16, int8x16, 16)
  BITMASK_CASE(I16x8BitMask, i16x8, int16x8, 8)
  BITMASK_CASE(I32x4BitMask, i32x4, int32x4, 4)
  BITMASK_CASE(I64x2BitMask, i64x2, int64x2, 2)
#undef BITMASK_CASE
#define CMPOP_CASE(op, name, stype, out_stype, count, expr) \
  INSTRUCTION_HANDLER_FUNC s2s_Simd##op(const uint8_t* code, uint32_t* sp, \
                                        WasmInterpreterRuntime* wasm_runtime, \
                                        int64_t r0, double fp0) { \
    stype s2 = pop<Simd128>(sp, code, wasm_runtime).to_##name(); \
    stype s1 = pop<Simd128>(sp, code, wasm_runtime).to_##name(); \
    out_stype res; \
    for (size_t i = 0; i < count; ++i) { \
      auto a = s1.val[LANE(i, s1)]; \
      auto b = s2.val[LANE(i, s2)]; \
      auto result = expr; \
      res.val[LANE(i, res)] = result ? -1 : 0; \
    } \
    push<Simd128>(sp, code, wasm_runtime, Simd128(res)); \
    NextOp(); \
  }
  CMPOP_CASE(F64x2Eq, f64x2, float64x2, int64x2, 2, a == b)
  CMPOP_CASE(F64x2Ne, f64x2, float64x2, int64x2, 2, a != b)
  CMPOP_CASE(F64x2Gt, f64x2, float64x2, int64x2, 2, a > b)
  CMPOP_CASE(F64x2Ge, f64x2, float64x2, int64x2, 2, a >= b)
  CMPOP_CASE(F64x2Lt, f64x2, float64x2, int64x2, 2, a < b)
  CMPOP_CASE(F64x2Le, f64x2, float64x2, int64x2, 2, a <= b)
  CMPOP_CASE(F32x4Eq, f32x4, float32x4, int32x4, 4, a == b)
  CMPOP_CASE(F32x4Ne, f32x4, float32x4, int32x4, 4, a != b)
  CMPOP_CASE(F32x4Gt, f32x4, float32x4, int32x4, 4, a > b)
  CMPOP_CASE(F32x4Ge, f32x4, float32x4, int32x4, 4, a >= b)
  CMPOP_CASE(F32x4Lt, f32x4, float32x4, int32x4, 4, a < b)
  CMPOP_CASE(F32x4Le, f32x4, float32x4, int32x4, 4, a <= b)
  CMPOP_CASE(I64x2Eq, i64x2, int64x2, int64x2, 2, a == b)
  CMPOP_CASE(I64x2Ne, i64x2, int64x2, int64x2, 2, a != b)
  CMPOP_CASE(I64x2LtS, i64x2, int64x2, int64x2, 2, a < b)
  CMPOP_CASE(I64x2GtS, i64x2, int64x2, int64x2, 2, a > b)
  CMPOP_CASE(I64x2LeS, i64x2, int64x2, int64x2, 2, a <= b)
  CMPOP_CASE(I64x2GeS, i64x2, int64x2, int64x2, 2, a >= b)
  CMPOP_CASE(I32x4Eq, i32x4, int32x4, int32x4, 4, a == b)
  CMPOP_CASE(I32x4Ne, i32x4, int32x4, int32x4, 4, a != b)
  CMPOP_CASE(I32x4GtS, i32x4, int32x4, int32x4, 4, a > b)
  CMPOP_CASE(I32x4GeS, i32x4, int32x4, int32x4, 4, a >= b)
  CMPOP_CASE(I32x4LtS, i32x4, int32x4, int32x4, 4, a < b)
  CMPOP_CASE(I32x4LeS, i32x4, int32x4, int32x4, 4, a <= b)
  CMPOP_CASE(I32x4GtU, i32x4, int32x4, int32x4, 4,
             static_cast<uint32_t>(a) > static_cast<uint32_t>(b))
  CMPOP_CASE(I32x4GeU, i32x4, int32x4, int32x4, 4,
             static_cast<uint32_t>(a) >= static_cast<uint32_t>(b))
  CMPOP_CASE(I32x4LtU, i32x4, int32x4, int32x4, 4,
             static_cast<uint32_t>(a) < static_cast<uint32_t>(b))
  CMPOP_CASE(I32x4LeU, i32x4, int32x4, int32x4, 4,
             static_cast<uint32_t>(a) <= static_cast<uint32_t>(b))
  CMPOP_CASE(I16x8Eq, i16x8, int16x8, int16x8, 8, a == b)
  CMPOP_CASE(I16x8Ne, i16x8, int16x8, int16x8, 8, a != b)
  CMPOP_CASE(I16x8GtS, i16x8, int16x8, int16x8, 8, a > b)
  CMPOP_CASE(I16x8GeS, i16x8, int16x8, int16x8, 8, a >= b)
  CMPOP_CASE(I16x8LtS, i16x8, int16x8, int16x8, 8, a < b)
  CMPOP_CASE(I16x8LeS, i16x8, int16x8, int16x8, 8, a <= b)
  CMPOP_CASE(I16x8GtU, i16x8, int16x8, int16x8, 8,
             static_cast<uint16_t>(a) > static_cast<uint16_t>(b))
  CMPOP_CASE(I16x8GeU, i16x8, int16x8, int16x8, 8,
             static_cast<uint16_t>(a) >= static_cast<uint16_t>(b))
  CMPOP_CASE(I16x8LtU, i16x8, int16x8, int16x8, 8,
             static_cast<uint16_t>(a) < static_cast<uint16_t>(b))
  CMPOP_CASE(I16x8LeU, i16x8, int16x8, int16x8, 8,
             static_cast<uint16_t>(a) <= static_cast<uint16_t>(b))
  CMPOP_CASE(I8x16Eq, i8x16, int8x16, int8x16, 16, a == b)
  CMPOP_CASE(I8x16Ne, i8x16, int8x16, int8x16, 16, a != b)
  CMPOP_CASE(I8x16GtS, i8x16, int8x16, int8x16, 16, a > b)
  CMPOP_CASE(I8x16GeS, i8x16, int8x16, int8x16, 16, a >= b)
  CMPOP_CASE(I8x16LtS, i8x16, int8x16, int8x16, 16, a < b)
  CMPOP_CASE(I8x16LeS, i8x16, int8x16, int8x16, 16, a <= b)
  CMPOP_CASE(I8x16GtU, i8x16, int8x16, int8x16, 16,
             static_cast<uint8_t>(a) > static_cast<uint8_t>(b))
  CMPOP_CASE(I8x16GeU, i8x16, int8x16, int8x16, 16,
             static_cast<uint8_t>(a) >= static_cast<uint8_t>(b))
  CMPOP_CASE(I8x16LtU, i8x16, int8x16, int8x16, 16,
             static_cast<uint8_t>(a) < static_cast<uint8_t>(b))
  CMPOP_CASE(I8x16LeU, i8x16, int8x16, int8x16, 16,
             static_cast<uint8_t>(a) <= static_cast<uint8_t>(b))
#undef CMPOP_CASE
#define REPLACE_LANE_CASE(format, name, stype, ctype, op_type) \
  INSTRUCTION_HANDLER_FUNC s2s_Simd##format##ReplaceLane(\
      const uint8_t* code, uint32_t* sp, WasmInterpreterRuntime* wasm_runtime, \
      int64_t r0, double fp0) { \
    uint16_t lane = Read<int16_t>(code); \
    DCHECK_LT(lane, 16); \
    ctype new_val = pop<ctype>(sp, code, wasm_runtime); \
    Simd128 simd_val = pop<Simd128>(sp, code, wasm_runtime); \
    stype s = simd_val.to_##name(); \
    s.val[LANE(lane, s)] = new_val; \
    push<Simd128>(sp, code, wasm_runtime, Simd128(s)); \
    NextOp(); \
  }
  REPLACE_LANE_CASE(F64x2, f64x2, float64x2, double, F64)
  REPLACE_LANE_CASE(F32x4, f32x4, float32x4, float, F32)
  REPLACE_LANE_CASE(I64x2, i64x2, int64x2, int64_t, I64)
  REPLACE_LANE_CASE(I32x4, i32x4, int32x4, int32_t, I32)
  REPLACE_LANE_CASE(I16x8, i16x8, int16x8, int32_t, I32)
  REPLACE_LANE_CASE(I8x16, i8x16, int8x16, int32_t, I32)
#undef REPLACE_LANE_CASE
  template <typename MemIdx, typename MemOffsetT>
  INSTRUCTION_HANDLER_FUNC s2s_SimdS128LoadMemI(
      const uint8_t* code, uint32_t* sp, WasmInterpreterRuntime* wasm_runtime,
      int64_t r0, double fp0) {
    uint8_t* memory_start = wasm_runtime->GetMemoryStart();
    uint64_t offset = Read<MemOffsetT>(code);
    uint64_t index = pop<MemIdx>(sp, code, wasm_runtime);
    uint64_t effective_index = offset + index;
    if (V8_UNLIKELY(
            effective_index < index ||
            !base::IsInBounds<uint64_t>(effective_index, sizeof(Simd128),
                                        wasm_runtime->GetMemorySize()))) {
      TRAP(TrapReason::kTrapMemOutOfBounds)
    }
    uint8_t* address = memory_start + effective_index;
    Simd128 s =
        base::ReadUnalignedValue<Simd128>(reinterpret_cast<Address>(address));
    push<Simd128>(sp, code, wasm_runtime, Simd128(s));
    NextOp();
  }
static_cast() [2/11]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::static_cast (a)
static_cast() [3/11]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::static_cast (a)
static_cast() [4/11]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::static_cast (a)
static_cast() [5/11]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::static_cast (a)
static_cast() [6/11]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::static_cast (a)
static_cast() [7/11]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::static_cast (a)
static_cast() [8/11]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::static_cast (a) const
static_cast() [9/11]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::static_cast (a)
static_cast() [10/11]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::static_cast (a)
static_cast() [11/11]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::static_cast (a)
StoreRefIntoMemory()
template<bool Compressed>
static void v8::internal::wasm::Handlers< Compressed >::StoreRefIntoMemory (Tagged< HeapObject > host, Address dst_addr, uint32_t offset, Tagged< Object > value, WriteBarrierMode mode) [inline], [static]
Definition at line 5918 of file wasm-interpreter.cc.
                                                        {
    DCHECK_EQ(dst_addr, host.ptr() + offset - kHeapObjectTag);
    // Only stores the lower 32-bit.
    base::WriteUnalignedValue<Tagged_t>(
        dst_addr, V8HeapCompressionScheme::CompressObject(value.ptr()));
    // Need to generate a GC write barrier.
    CONDITIONAL_WRITE_BARRIER(host, offset, value, mode);
  }
References v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressObject(), CONDITIONAL_WRITE_BARRIER, DCHECK_EQ, v8::internal::kHeapObjectTag, mode(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::value.
Referenced by v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewDefault(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewFixed(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayFill(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayNew(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArraySet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefStructSet(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNew(), and v8::internal::wasm::Handlers< Compressed >::s2s_StructNewDefault().
Member Data Documentation
d_type
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::d_type
Definition at line 4996 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdExtMul().
double
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::double
Definition at line 5090 of file wasm-interpreter.cc.
f32x4 [1/2]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::f32x4
Definition at line 5059 of file wasm-interpreter.cc.
f32x4 [2/2]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::f32x4
Definition at line 5100 of file wasm-interpreter.cc.
f64x2
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::f64x2
Definition at line 5090 of file wasm-interpreter.cc.
float [1/2]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::float
Definition at line 5059 of file wasm-interpreter.cc.
float [2/2]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::float
Definition at line 5098 of file wasm-interpreter.cc.
float32x4 [1/2]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::float32x4
Definition at line 5057 of file wasm-interpreter.cc.
float32x4 [2/2]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::float32x4
Definition at line 5098 of file wasm-interpreter.cc.
float64x2
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::float64x2
Definition at line 5088 of file wasm-interpreter.cc.
fp0
template<bool Compressed>
a a a a uint32_t WasmInterpreterRuntime int64_t double v8::internal::wasm::Handlers< Compressed >::fp0
Initial value:
{
    int32x4 bool_val = pop<Simd128>(sp, code, wasm_runtime).to_i32x4()
Definition at line 5127 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::r2s_StoreMemF().
i16x8 [1/2]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::i16x8
Definition at line 4984 of file wasm-interpreter.cc.
i16x8 [2/2]
template<bool Compressed>
a a v8::internal::wasm::Handlers< Compressed >::i16x8
Definition at line 5076 of file wasm-interpreter.cc.
i32x4 [1/3]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::i32x4
Definition at line 4701 of file wasm-interpreter.cc.
i32x4 [2/3]
template<bool Compressed>
a v8::internal::wasm::Handlers< Compressed >::i32x4
Definition at line 5072 of file wasm-interpreter.cc.
i32x4 [3/3]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::i32x4
Definition at line 5088 of file wasm-interpreter.cc.
i64x2
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::i64x2
Definition at line 4977 of file wasm-interpreter.cc.
i8x16 [1/2]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::i8x16
Definition at line 4989 of file wasm-interpreter.cc.
i8x16 [2/2]
template<bool Compressed>
a a a v8::internal::wasm::Handlers< Compressed >::i8x16
Definition at line 5082 of file wasm-interpreter.cc.
int16x8 [1/3]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::int16x8
Definition at line 4984 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8DotI8x16I7x16S(), and v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI16x8S().
int16x8 [2/3]
template<bool Compressed>
a a v8::internal::wasm::Handlers< Compressed >::int16x8
Definition at line 5076 of file wasm-interpreter.cc.
int16x8 [3/3]
template<bool Compressed>
a a a v8::internal::wasm::Handlers< Compressed >::int16x8
Definition at line 5082 of file wasm-interpreter.cc.
int32_t
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::int32_t
Definition at line 5068 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::r2s_BranchIf(), v8::internal::wasm::Handlers< Compressed >::r2s_BranchIfWithParams(), v8::internal::wasm::Handlers< Compressed >::r2s_BrTable(), v8::internal::wasm::Handlers< Compressed >::r2s_CopyR0ToSlot32(), v8::internal::wasm::Handlers< Compressed >::r2s_If(), v8::internal::wasm::Handlers< Compressed >::r2s_PreserveCopyR0ToSlot32(), v8::internal::wasm::Handlers< Compressed >::s2r_SelectF(), v8::internal::wasm::Handlers< Compressed >::s2r_SelectI(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewDefault(), v8::internal::wasm::Handlers< Compressed >::s2s_AtomicNotify(), v8::internal::wasm::Handlers< Compressed >::s2s_Branch(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchIf(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchIfWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCast(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCastFail(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNull(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNullWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNull(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNullWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BrTable(), v8::internal::wasm::Handlers< Compressed >::s2s_Catch(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot32(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_ll(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_lq(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_ql(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlotMulti(), v8::internal::wasm::Handlers< Compressed >::s2s_Else(), v8::internal::wasm::Handlers< Compressed >::s2s_I32AtomicWait(), v8::internal::wasm::Handlers< Compressed >::s2s_I64AtomicWait(), v8::internal::wasm::Handlers< Compressed >::s2s_If(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryGrow(), v8::internal::wasm::Handlers< Compressed >::s2s_RefSelect(), v8::internal::wasm::Handlers< Compressed >::s2s_Select(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI16x8S(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI8x16I7x16AddS(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNewDefault(), and v8::internal::wasm::Handlers< Compressed >::s2s_Table64Grow().
int32x4 [1/4]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::int32x4
Definition at line 4701 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI16x8S(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI8x16I7x16AddS(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdV128AnyTrue(), and v8::internal::wasm::Handlers< Compressed >::s2s_Throw().
int32x4 [2/4]
template<bool Compressed>
a v8::internal::wasm::Handlers< Compressed >::int32x4
Definition at line 5072 of file wasm-interpreter.cc.
int32x4 [3/4]
template<bool Compressed>
a a v8::internal::wasm::Handlers< Compressed >::int32x4
Definition at line 5076 of file wasm-interpreter.cc.
int32x4 [4/4]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::int32x4
Definition at line 5088 of file wasm-interpreter.cc.
int64x2 [1/2]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::int64x2
Definition at line 4977 of file wasm-interpreter.cc.
int64x2 [2/2]
template<bool Compressed>
a v8::internal::wasm::Handlers< Compressed >::int64x2
Definition at line 5072 of file wasm-interpreter.cc.
int8x16 [1/2]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::int8x16
Definition at line 4989 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8DotI8x16I7x16S(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI8x16I7x16AddS(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Shuffle(), and v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Swizzle().
int8x16 [2/2]
template<bool Compressed>
a a a v8::internal::wasm::Handlers< Compressed >::int8x16
Definition at line 5082 of file wasm-interpreter.cc.
narrow
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::narrow
Definition at line 4996 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdExtMul().
r0
template<bool Compressed>
a a a a uint32_t WasmInterpreterRuntime int64_t v8::internal::wasm::Handlers< Compressed >::r0
Definition at line 5127 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::r2r_LoadMemF(), v8::internal::wasm::Handlers< Compressed >::r2r_LoadMemI(), v8::internal::wasm::Handlers< Compressed >::r2s_BranchIf(), v8::internal::wasm::Handlers< Compressed >::r2s_BranchIfWithParams(), v8::internal::wasm::Handlers< Compressed >::r2s_BrTable(), v8::internal::wasm::Handlers< Compressed >::r2s_If(), v8::internal::wasm::Handlers< Compressed >::r2s_LoadMem(), v8::internal::wasm::Handlers< Compressed >::r2s_LoadStoreMem(), and v8::internal::wasm::Handlers< Compressed >::r2s_StoreMemI().
r2r_F32LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_F32LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemF<float, uint64_t, memory_offset64_t>
Definition at line 1132 of file wasm-interpreter.cc.
r2r_F32Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_F32Select = r2r_SelectF<float> [static], [constexpr]
Definition at line 1845 of file wasm-interpreter.cc.
r2r_F64LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_F64LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemF<double, uint64_t, memory_offset64_t>
Definition at line 1134 of file wasm-interpreter.cc.
r2r_F64Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_F64Select = r2r_SelectF<double> [static], [constexpr]
Definition at line 1846 of file wasm-interpreter.cc.
r2r_I32LoadMem16S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I32LoadMem16S_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemI<int32_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1088 of file wasm-interpreter.cc.
r2r_I32LoadMem16U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I32LoadMem16U_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemI<int32_t, uint16_t, uint64_t, memory_offset64_t>
Definition at line 1090 of file wasm-interpreter.cc.
r2r_I32LoadMem8S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I32LoadMem8S_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemI<int32_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1084 of file wasm-interpreter.cc.
r2r_I32LoadMem8U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I32LoadMem8U_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemI<int32_t, uint8_t, uint64_t, memory_offset64_t>
Definition at line 1086 of file wasm-interpreter.cc.
r2r_I32LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I32LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemI<int32_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1104 of file wasm-interpreter.cc.
r2r_I32Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I32Select = r2r_SelectI<int32_t> [static], [constexpr]
Definition at line 1830 of file wasm-interpreter.cc.
r2r_I64LoadMem16S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I64LoadMem16S_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemI<int64_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1096 of file wasm-interpreter.cc.
r2r_I64LoadMem16U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I64LoadMem16U_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemI<int64_t, uint16_t, uint64_t, memory_offset64_t>
Definition at line 1098 of file wasm-interpreter.cc.
r2r_I64LoadMem32S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I64LoadMem32S_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemI<int64_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1100 of file wasm-interpreter.cc.
r2r_I64LoadMem32U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I64LoadMem32U_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemI<int64_t, uint32_t, uint64_t, memory_offset64_t>
Definition at line 1102 of file wasm-interpreter.cc.
r2r_I64LoadMem8S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I64LoadMem8S_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemI<int64_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1092 of file wasm-interpreter.cc.
r2r_I64LoadMem8U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I64LoadMem8U_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemI<int64_t, uint8_t, uint64_t, memory_offset64_t>
Definition at line 1094 of file wasm-interpreter.cc.
r2r_I64LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I64LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      r2r_LoadMemI<int64_t, int64_t, uint64_t, memory_offset64_t>
Definition at line 1106 of file wasm-interpreter.cc.
r2r_I64Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2r_I64Select = r2r_SelectI<int64_t> [static], [constexpr]
Definition at line 1831 of file wasm-interpreter.cc.
r2s_F32Drop
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_F32Drop = r2s_Drop<float> [static], [constexpr]
Definition at line 1025 of file wasm-interpreter.cc.
r2s_F32GlobalSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_F32GlobalSet = r2s_GlobalSetF<float> [static], [constexpr]
Definition at line 986 of file wasm-interpreter.cc.
r2s_F32LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_F32LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<float, float, uint64_t, memory_offset64_t>
Definition at line 1186 of file wasm-interpreter.cc.
r2s_F32LoadStoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_F32LoadStoreMem_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadStoreMem<float, uint64_t, memory_offset64_t>
Definition at line 1540 of file wasm-interpreter.cc.
r2s_F32Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_F32Select = r2s_Select<float> [static], [constexpr]
Definition at line 1861 of file wasm-interpreter.cc.
r2s_F32StoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_F32StoreMem_Idx64 [static], [constexpr]
Initial value:
=
      r2s_StoreMemF<float, uint64_t, memory_offset64_t>
Definition at line 1450 of file wasm-interpreter.cc.
r2s_F64Drop
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_F64Drop = r2s_Drop<double> [static], [constexpr]
Definition at line 1026 of file wasm-interpreter.cc.
r2s_F64GlobalSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_F64GlobalSet = r2s_GlobalSetF<double> [static], [constexpr]
Definition at line 987 of file wasm-interpreter.cc.
r2s_F64LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_F64LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<double, double, uint64_t, memory_offset64_t>
Definition at line 1188 of file wasm-interpreter.cc.
r2s_F64LoadStoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_F64LoadStoreMem_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadStoreMem<double, uint64_t, memory_offset64_t>
Definition at line 1542 of file wasm-interpreter.cc.
r2s_F64Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_F64Select = r2s_Select<double> [static], [constexpr]
Definition at line 1862 of file wasm-interpreter.cc.
r2s_F64StoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_F64StoreMem_Idx64 [static], [constexpr]
Initial value:
=
      r2s_StoreMemF<double, uint64_t, memory_offset64_t>
Definition at line 1452 of file wasm-interpreter.cc.
r2s_I32Drop
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I32Drop = r2s_Drop<int32_t> [static], [constexpr]
Definition at line 1023 of file wasm-interpreter.cc.
r2s_I32GlobalSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I32GlobalSet = r2s_GlobalSetI<int32_t> [static], [constexpr]
Definition at line 973 of file wasm-interpreter.cc.
r2s_I32LoadMem16S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I32LoadMem16S_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<int32_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1166 of file wasm-interpreter.cc.
r2s_I32LoadMem16U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I32LoadMem16U_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<int32_t, uint16_t, uint64_t, memory_offset64_t>
Definition at line 1168 of file wasm-interpreter.cc.
r2s_I32LoadMem8S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I32LoadMem8S_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<int32_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1162 of file wasm-interpreter.cc.
r2s_I32LoadMem8U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I32LoadMem8U_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<int32_t, uint8_t, uint64_t, memory_offset64_t>
Definition at line 1164 of file wasm-interpreter.cc.
r2s_I32LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I32LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<int32_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1182 of file wasm-interpreter.cc.
r2s_I32LoadStoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I32LoadStoreMem_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadStoreMem<int32_t, uint64_t, memory_offset64_t>
Definition at line 1536 of file wasm-interpreter.cc.
r2s_I32Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I32Select = r2s_Select<int32_t> [static], [constexpr]
Definition at line 1859 of file wasm-interpreter.cc.
r2s_I32StoreMem16_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I32StoreMem16_Idx64 [static], [constexpr]
Initial value:
=
      r2s_StoreMemI<int32_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1410 of file wasm-interpreter.cc.
r2s_I32StoreMem8_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I32StoreMem8_Idx64 [static], [constexpr]
Initial value:
=
      r2s_StoreMemI<int32_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1408 of file wasm-interpreter.cc.
r2s_I32StoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I32StoreMem_Idx64 [static], [constexpr]
Initial value:
=
      r2s_StoreMemI<int32_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1418 of file wasm-interpreter.cc.
r2s_I64Drop
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64Drop = r2s_Drop<int64_t> [static], [constexpr]
Definition at line 1024 of file wasm-interpreter.cc.
r2s_I64GlobalSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64GlobalSet = r2s_GlobalSetI<int64_t> [static], [constexpr]
Definition at line 974 of file wasm-interpreter.cc.
r2s_I64LoadMem16S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64LoadMem16S_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<int64_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1174 of file wasm-interpreter.cc.
r2s_I64LoadMem16U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64LoadMem16U_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<int64_t, uint16_t, uint64_t, memory_offset64_t>
Definition at line 1176 of file wasm-interpreter.cc.
r2s_I64LoadMem32S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64LoadMem32S_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<int64_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1178 of file wasm-interpreter.cc.
r2s_I64LoadMem32U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64LoadMem32U_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<int64_t, uint32_t, uint64_t, memory_offset64_t>
Definition at line 1180 of file wasm-interpreter.cc.
r2s_I64LoadMem8S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64LoadMem8S_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<int64_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1170 of file wasm-interpreter.cc.
r2s_I64LoadMem8U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64LoadMem8U_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<int64_t, uint8_t, uint64_t, memory_offset64_t>
Definition at line 1172 of file wasm-interpreter.cc.
r2s_I64LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadMem<int64_t, int64_t, uint64_t, memory_offset64_t>
Definition at line 1184 of file wasm-interpreter.cc.
r2s_I64LoadStoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64LoadStoreMem_Idx64 [static], [constexpr]
Initial value:
=
      r2s_LoadStoreMem<int64_t, uint64_t, memory_offset64_t>
Definition at line 1538 of file wasm-interpreter.cc.
r2s_I64Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64Select = r2s_Select<int64_t> [static], [constexpr]
Definition at line 1860 of file wasm-interpreter.cc.
r2s_I64StoreMem16_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64StoreMem16_Idx64 [static], [constexpr]
Initial value:
=
      r2s_StoreMemI<int64_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1414 of file wasm-interpreter.cc.
r2s_I64StoreMem32_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64StoreMem32_Idx64 [static], [constexpr]
Initial value:
=
      r2s_StoreMemI<int64_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1416 of file wasm-interpreter.cc.
r2s_I64StoreMem8_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64StoreMem8_Idx64 [static], [constexpr]
Initial value:
=
      r2s_StoreMemI<int64_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1412 of file wasm-interpreter.cc.
r2s_I64StoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_I64StoreMem_Idx64 [static], [constexpr]
Initial value:
=
      r2s_StoreMemI<int64_t, int64_t, uint64_t, memory_offset64_t>
Definition at line 1420 of file wasm-interpreter.cc.
r2s_S128Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::r2s_S128Select = r2s_Select<Simd128> [static], [constexpr]
Definition at line 1863 of file wasm-interpreter.cc.
res
template<bool Compressed>
int32x4 v8::internal::wasm::Handlers< Compressed >::res
Definition at line 5131 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::for(), v8::internal::wasm::Handlers< Compressed >::Read(), v8::internal::wasm::Handlers< Compressed >::ReadGlobalIndex(), v8::internal::wasm::Handlers< Compressed >::ReadMemoryAddress(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdExtAddPairwise(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdExtMul(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdStoreLane(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8DotI8x16I7x16S(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI16x8S(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI8x16I7x16AddS(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Shuffle(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Swizzle(), and v8::internal::wasm::Handlers< Compressed >::s2s_SimdV128AnyTrue().
s2r_F32GlobalGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_F32GlobalGet = s2r_GlobalGetF<float> [static], [constexpr]
Definition at line 931 of file wasm-interpreter.cc.
s2r_F32LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_F32LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemF<float, uint64_t, memory_offset64_t>
Definition at line 1264 of file wasm-interpreter.cc.
s2r_F32Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_F32Select = s2r_SelectF<float> [static], [constexpr]
Definition at line 1902 of file wasm-interpreter.cc.
s2r_F64GlobalGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_F64GlobalGet = s2r_GlobalGetF<double> [static], [constexpr]
Definition at line 932 of file wasm-interpreter.cc.
s2r_F64LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_F64LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemF<double, uint64_t, memory_offset64_t>
Definition at line 1266 of file wasm-interpreter.cc.
s2r_F64Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_F64Select = s2r_SelectF<double> [static], [constexpr]
Definition at line 1903 of file wasm-interpreter.cc.
s2r_I32GlobalGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I32GlobalGet = s2r_GlobalGetI<int32_t> [static], [constexpr]
Definition at line 918 of file wasm-interpreter.cc.
s2r_I32LoadMem16S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I32LoadMem16S_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemI<int32_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1219 of file wasm-interpreter.cc.
s2r_I32LoadMem16U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I32LoadMem16U_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemI<int32_t, uint16_t, uint64_t, memory_offset64_t>
Definition at line 1221 of file wasm-interpreter.cc.
s2r_I32LoadMem8S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I32LoadMem8S_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemI<int32_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1215 of file wasm-interpreter.cc.
s2r_I32LoadMem8U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I32LoadMem8U_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemI<int32_t, uint8_t, uint64_t, memory_offset64_t>
Definition at line 1217 of file wasm-interpreter.cc.
s2r_I32LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I32LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemI<int32_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1235 of file wasm-interpreter.cc.
s2r_I32Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I32Select = s2r_SelectI<int32_t> [static], [constexpr]
Definition at line 1887 of file wasm-interpreter.cc.
s2r_I64GlobalGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I64GlobalGet = s2r_GlobalGetI<int64_t> [static], [constexpr]
Definition at line 919 of file wasm-interpreter.cc.
s2r_I64LoadMem16S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I64LoadMem16S_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemI<int64_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1227 of file wasm-interpreter.cc.
s2r_I64LoadMem16U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I64LoadMem16U_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemI<int64_t, uint16_t, uint64_t, memory_offset64_t>
Definition at line 1229 of file wasm-interpreter.cc.
s2r_I64LoadMem32S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I64LoadMem32S_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemI<int64_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1231 of file wasm-interpreter.cc.
s2r_I64LoadMem32U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I64LoadMem32U_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemI<int64_t, uint32_t, uint64_t, memory_offset64_t>
Definition at line 1233 of file wasm-interpreter.cc.
s2r_I64LoadMem8S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I64LoadMem8S_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemI<int64_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1223 of file wasm-interpreter.cc.
s2r_I64LoadMem8U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I64LoadMem8U_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemI<int64_t, uint8_t, uint64_t, memory_offset64_t>
Definition at line 1225 of file wasm-interpreter.cc.
s2r_I64LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I64LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      s2r_LoadMemI<int64_t, int64_t, uint64_t, memory_offset64_t>
Definition at line 1237 of file wasm-interpreter.cc.
s2r_I64Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2r_I64Select = s2r_SelectI<int64_t> [static], [constexpr]
Definition at line 1888 of file wasm-interpreter.cc.
s2s_ArrayInitData
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_ArrayInitData = s2s_ArrayInitSegment<true> [static], [constexpr]
Definition at line 6474 of file wasm-interpreter.cc.
s2s_ArrayInitElem
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_ArrayInitElem = s2s_ArrayInitSegment<false> [static], [constexpr]
Definition at line 6475 of file wasm-interpreter.cc.
s2s_ArrayNewData
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewData [static], [constexpr]
Initial value:
=
      s2s_ArrayNewSegment<kTrapDataSegmentOutOfBounds>
Definition at line 6420 of file wasm-interpreter.cc.
s2s_ArrayNewElem
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewElem [static], [constexpr]
Initial value:
=
      s2s_ArrayNewSegment<kTrapElementSegmentOutOfBounds>
Definition at line 6422 of file wasm-interpreter.cc.
s2s_AtomicNotify_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_AtomicNotify_Idx64 [static], [constexpr]
Initial value:
=
      s2s_AtomicNotify<uint64_t, memory_offset64_t>
Definition at line 4253 of file wasm-interpreter.cc.
s2s_F32ArrayFill
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32ArrayFill = s2s_ArrayFill<float> [static], [constexpr]
Definition at line 6678 of file wasm-interpreter.cc.
s2s_F32ArrayGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32ArrayGet = s2s_ArrayGet<float> [static], [constexpr]
Definition at line 6566 of file wasm-interpreter.cc.
s2s_F32ArrayNew
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32ArrayNew = s2s_ArrayNew<float> [static], [constexpr]
Definition at line 6190 of file wasm-interpreter.cc.
s2s_F32ArraySet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32ArraySet = s2s_ArraySet<float> [static], [constexpr]
Definition at line 6619 of file wasm-interpreter.cc.
s2s_F32Drop
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32Drop = s2s_Drop<float> [static], [constexpr]
Definition at line 1044 of file wasm-interpreter.cc.
s2s_F32GlobalGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32GlobalGet = s2s_GlobalGet<float> [static], [constexpr]
Definition at line 947 of file wasm-interpreter.cc.
s2s_F32GlobalSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32GlobalSet = s2s_GlobalSet<float> [static], [constexpr]
Definition at line 1001 of file wasm-interpreter.cc.
s2s_F32LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<float, float, uint64_t, memory_offset64_t>
Definition at line 1318 of file wasm-interpreter.cc.
s2s_F32LoadMem_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32LoadMem_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<float, float, uint64_t, memory_offset64_t>
Definition at line 1375 of file wasm-interpreter.cc.
s2s_F32LoadStoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32LoadStoreMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadStoreMem<float, uint64_t, memory_offset64_t>
Definition at line 1583 of file wasm-interpreter.cc.
s2s_F32Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32Select = s2s_Select<float> [static], [constexpr]
Definition at line 1919 of file wasm-interpreter.cc.
s2s_F32StoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32StoreMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_StoreMem<float, float, uint64_t, memory_offset64_t>
Definition at line 1496 of file wasm-interpreter.cc.
s2s_F32StructGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32StructGet = s2s_StructGet<float> [static], [constexpr]
Definition at line 6084 of file wasm-interpreter.cc.
s2s_F32StructSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F32StructSet = s2s_StructSet<float> [static], [constexpr]
Definition at line 6127 of file wasm-interpreter.cc.
s2s_F64ArrayFill
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64ArrayFill = s2s_ArrayFill<double> [static], [constexpr]
Definition at line 6679 of file wasm-interpreter.cc.
s2s_F64ArrayGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64ArrayGet = s2s_ArrayGet<double> [static], [constexpr]
Definition at line 6567 of file wasm-interpreter.cc.
s2s_F64ArrayNew
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64ArrayNew = s2s_ArrayNew<double> [static], [constexpr]
Definition at line 6191 of file wasm-interpreter.cc.
s2s_F64ArraySet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64ArraySet = s2s_ArraySet<double> [static], [constexpr]
Definition at line 6620 of file wasm-interpreter.cc.
s2s_F64Drop
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64Drop = s2s_Drop<double> [static], [constexpr]
Definition at line 1045 of file wasm-interpreter.cc.
s2s_F64GlobalGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64GlobalGet = s2s_GlobalGet<double> [static], [constexpr]
Definition at line 948 of file wasm-interpreter.cc.
s2s_F64GlobalSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64GlobalSet = s2s_GlobalSet<double> [static], [constexpr]
Definition at line 1002 of file wasm-interpreter.cc.
s2s_F64LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<double, double, uint64_t, memory_offset64_t>
Definition at line 1320 of file wasm-interpreter.cc.
s2s_F64LoadMem_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64LoadMem_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<double, double, uint64_t, memory_offset64_t>
Definition at line 1377 of file wasm-interpreter.cc.
s2s_F64LoadStoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64LoadStoreMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadStoreMem<double, uint64_t, memory_offset64_t>
Definition at line 1585 of file wasm-interpreter.cc.
s2s_F64Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64Select = s2s_Select<double> [static], [constexpr]
Definition at line 1920 of file wasm-interpreter.cc.
s2s_F64StoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64StoreMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_StoreMem<double, double, uint64_t, memory_offset64_t>
Definition at line 1498 of file wasm-interpreter.cc.
s2s_F64StructGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64StructGet = s2s_StructGet<double> [static], [constexpr]
Definition at line 6085 of file wasm-interpreter.cc.
s2s_F64StructSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_F64StructSet = s2s_StructSet<double> [static], [constexpr]
Definition at line 6128 of file wasm-interpreter.cc.
s2s_I16ArrayFill
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I16ArrayFill = s2s_ArrayFill<int16_t, int32_t> [static], [constexpr]
Definition at line 6675 of file wasm-interpreter.cc.
s2s_I16ArrayNew
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I16ArrayNew = s2s_ArrayNew<int32_t, int16_t> [static], [constexpr]
Definition at line 6187 of file wasm-interpreter.cc.
s2s_I16ArraySet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I16ArraySet = s2s_ArraySet<int32_t, int16_t> [static], [constexpr]
Definition at line 6616 of file wasm-interpreter.cc.
s2s_I16SArrayGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I16SArrayGet = s2s_ArrayGet<int32_t, int16_t> [static], [constexpr]
Definition at line 6562 of file wasm-interpreter.cc.
s2s_I16SStructGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I16SStructGet = s2s_StructGet<int32_t, int16_t> [static], [constexpr]
Definition at line 6080 of file wasm-interpreter.cc.
s2s_I16StructSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I16StructSet = s2s_StructSet<int32_t, int16_t> [static], [constexpr]
Definition at line 6124 of file wasm-interpreter.cc.
s2s_I16UArrayGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I16UArrayGet = s2s_ArrayGet<uint32_t, uint16_t> [static], [constexpr]
Definition at line 6563 of file wasm-interpreter.cc.
s2s_I16UStructGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I16UStructGet = s2s_StructGet<uint32_t, uint16_t> [static], [constexpr]
Definition at line 6081 of file wasm-interpreter.cc.
s2s_I32ArrayFill
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32ArrayFill = s2s_ArrayFill<int32_t> [static], [constexpr]
Definition at line 6676 of file wasm-interpreter.cc.
s2s_I32ArrayGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32ArrayGet = s2s_ArrayGet<int32_t> [static], [constexpr]
Definition at line 6564 of file wasm-interpreter.cc.
s2s_I32ArrayNew
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32ArrayNew = s2s_ArrayNew<int32_t> [static], [constexpr]
Definition at line 6188 of file wasm-interpreter.cc.
s2s_I32ArraySet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32ArraySet = s2s_ArraySet<int32_t> [static], [constexpr]
Definition at line 6617 of file wasm-interpreter.cc.
s2s_I32AtomicWait_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32AtomicWait_Idx64 [static], [constexpr]
Initial value:
=
      s2s_I32AtomicWait<uint64_t, memory_offset64_t>
Definition at line 4288 of file wasm-interpreter.cc.
s2s_I32Drop
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32Drop = s2s_Drop<int32_t> [static], [constexpr]
Definition at line 1042 of file wasm-interpreter.cc.
s2s_I32GlobalGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32GlobalGet = s2s_GlobalGet<int32_t> [static], [constexpr]
Definition at line 945 of file wasm-interpreter.cc.
s2s_I32GlobalSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32GlobalSet = s2s_GlobalSet<int32_t> [static], [constexpr]
Definition at line 999 of file wasm-interpreter.cc.
s2s_I32LoadMem16S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32LoadMem16S_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<int32_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1298 of file wasm-interpreter.cc.
s2s_I32LoadMem16S_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32LoadMem16S_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<int32_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1355 of file wasm-interpreter.cc.
s2s_I32LoadMem16U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32LoadMem16U_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<int32_t, uint16_t, uint64_t, memory_offset64_t>
Definition at line 1300 of file wasm-interpreter.cc.
s2s_I32LoadMem16U_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32LoadMem16U_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<int32_t, uint16_t, uint64_t, memory_offset64_t>
Definition at line 1357 of file wasm-interpreter.cc.
s2s_I32LoadMem8S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32LoadMem8S_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<int32_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1294 of file wasm-interpreter.cc.
s2s_I32LoadMem8S_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32LoadMem8S_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<int32_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1351 of file wasm-interpreter.cc.
s2s_I32LoadMem8U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32LoadMem8U_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<int32_t, uint8_t, uint64_t, memory_offset64_t>
Definition at line 1296 of file wasm-interpreter.cc.
s2s_I32LoadMem8U_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32LoadMem8U_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<int32_t, uint8_t, uint64_t, memory_offset64_t>
Definition at line 1353 of file wasm-interpreter.cc.
s2s_I32LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<int32_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1314 of file wasm-interpreter.cc.
s2s_I32LoadMem_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32LoadMem_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<int32_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1371 of file wasm-interpreter.cc.
s2s_I32LoadStoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32LoadStoreMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadStoreMem<int32_t, uint64_t, memory_offset64_t>
Definition at line 1579 of file wasm-interpreter.cc.
s2s_I32Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32Select = s2s_Select<int32_t> [static], [constexpr]
Definition at line 1917 of file wasm-interpreter.cc.
s2s_I32StoreMem16_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32StoreMem16_Idx64 [static], [constexpr]
Initial value:
=
      s2s_StoreMem<int32_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1484 of file wasm-interpreter.cc.
s2s_I32StoreMem8_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32StoreMem8_Idx64 [static], [constexpr]
Initial value:
=
      s2s_StoreMem<int32_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1482 of file wasm-interpreter.cc.
s2s_I32StoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32StoreMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_StoreMem<int32_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1492 of file wasm-interpreter.cc.
s2s_I32StructGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32StructGet = s2s_StructGet<int32_t> [static], [constexpr]
Definition at line 6082 of file wasm-interpreter.cc.
s2s_I32StructSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I32StructSet = s2s_StructSet<int32_t> [static], [constexpr]
Definition at line 6125 of file wasm-interpreter.cc.
s2s_I64ArrayFill
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64ArrayFill = s2s_ArrayFill<int64_t> [static], [constexpr]
Definition at line 6677 of file wasm-interpreter.cc.
s2s_I64ArrayGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64ArrayGet = s2s_ArrayGet<int64_t> [static], [constexpr]
Definition at line 6565 of file wasm-interpreter.cc.
s2s_I64ArrayNew
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64ArrayNew = s2s_ArrayNew<int64_t> [static], [constexpr]
Definition at line 6189 of file wasm-interpreter.cc.
s2s_I64ArraySet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64ArraySet = s2s_ArraySet<int64_t> [static], [constexpr]
Definition at line 6618 of file wasm-interpreter.cc.
s2s_I64AtomicWait_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64AtomicWait_Idx64 [static], [constexpr]
Initial value:
=
      s2s_I64AtomicWait<uint64_t, memory_offset64_t>
Definition at line 4323 of file wasm-interpreter.cc.
s2s_I64Drop
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64Drop = s2s_Drop<int64_t> [static], [constexpr]
Definition at line 1043 of file wasm-interpreter.cc.
s2s_I64GlobalGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64GlobalGet = s2s_GlobalGet<int64_t> [static], [constexpr]
Definition at line 946 of file wasm-interpreter.cc.
s2s_I64GlobalSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64GlobalSet = s2s_GlobalSet<int64_t> [static], [constexpr]
Definition at line 1000 of file wasm-interpreter.cc.
s2s_I64LoadMem16S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem16S_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<int64_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1306 of file wasm-interpreter.cc.
s2s_I64LoadMem16S_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem16S_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<int64_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1363 of file wasm-interpreter.cc.
s2s_I64LoadMem16U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem16U_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<int64_t, uint16_t, uint64_t, memory_offset64_t>
Definition at line 1308 of file wasm-interpreter.cc.
s2s_I64LoadMem16U_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem16U_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<int64_t, uint16_t, uint64_t, memory_offset64_t>
Definition at line 1365 of file wasm-interpreter.cc.
s2s_I64LoadMem32S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem32S_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<int64_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1310 of file wasm-interpreter.cc.
s2s_I64LoadMem32S_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem32S_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<int64_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1367 of file wasm-interpreter.cc.
s2s_I64LoadMem32U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem32U_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<int64_t, uint32_t, uint64_t, memory_offset64_t>
Definition at line 1312 of file wasm-interpreter.cc.
s2s_I64LoadMem32U_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem32U_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<int64_t, uint32_t, uint64_t, memory_offset64_t>
Definition at line 1369 of file wasm-interpreter.cc.
s2s_I64LoadMem8S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem8S_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<int64_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1302 of file wasm-interpreter.cc.
s2s_I64LoadMem8S_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem8S_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<int64_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1359 of file wasm-interpreter.cc.
s2s_I64LoadMem8U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem8U_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<int64_t, uint8_t, uint64_t, memory_offset64_t>
Definition at line 1304 of file wasm-interpreter.cc.
s2s_I64LoadMem8U_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem8U_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<int64_t, uint8_t, uint64_t, memory_offset64_t>
Definition at line 1361 of file wasm-interpreter.cc.
s2s_I64LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem<int64_t, int64_t, uint64_t, memory_offset64_t>
Definition at line 1316 of file wasm-interpreter.cc.
s2s_I64LoadMem_LocalSet_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadMem_LocalSet_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadMem_LocalSet<int64_t, int64_t, uint64_t, memory_offset64_t>
Definition at line 1373 of file wasm-interpreter.cc.
s2s_I64LoadStoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64LoadStoreMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_LoadStoreMem<int64_t, uint64_t, memory_offset64_t>
Definition at line 1581 of file wasm-interpreter.cc.
s2s_I64Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64Select = s2s_Select<int64_t> [static], [constexpr]
Definition at line 1918 of file wasm-interpreter.cc.
s2s_I64StoreMem16_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64StoreMem16_Idx64 [static], [constexpr]
Initial value:
=
      s2s_StoreMem<int64_t, int16_t, uint64_t, memory_offset64_t>
Definition at line 1488 of file wasm-interpreter.cc.
s2s_I64StoreMem32_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64StoreMem32_Idx64 [static], [constexpr]
Initial value:
=
      s2s_StoreMem<int64_t, int32_t, uint64_t, memory_offset64_t>
Definition at line 1490 of file wasm-interpreter.cc.
s2s_I64StoreMem8_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64StoreMem8_Idx64 [static], [constexpr]
Initial value:
=
      s2s_StoreMem<int64_t, int8_t, uint64_t, memory_offset64_t>
Definition at line 1486 of file wasm-interpreter.cc.
s2s_I64StoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64StoreMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_StoreMem<int64_t, int64_t, uint64_t, memory_offset64_t>
Definition at line 1494 of file wasm-interpreter.cc.
s2s_I64StructGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64StructGet = s2s_StructGet<int64_t> [static], [constexpr]
Definition at line 6083 of file wasm-interpreter.cc.
s2s_I64StructSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I64StructSet = s2s_StructSet<int64_t> [static], [constexpr]
Definition at line 6126 of file wasm-interpreter.cc.
s2s_I8ArrayFill
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I8ArrayFill = s2s_ArrayFill<int8_t, int32_t> [static], [constexpr]
Definition at line 6674 of file wasm-interpreter.cc.
s2s_I8ArrayNew
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I8ArrayNew = s2s_ArrayNew<int32_t, int8_t> [static], [constexpr]
Definition at line 6186 of file wasm-interpreter.cc.
s2s_I8ArraySet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I8ArraySet = s2s_ArraySet<int32_t, int8_t> [static], [constexpr]
Definition at line 6615 of file wasm-interpreter.cc.
s2s_I8SArrayGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I8SArrayGet = s2s_ArrayGet<int32_t, int8_t> [static], [constexpr]
Definition at line 6560 of file wasm-interpreter.cc.
s2s_I8SStructGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I8SStructGet = s2s_StructGet<int32_t, int8_t> [static], [constexpr]
Definition at line 6078 of file wasm-interpreter.cc.
s2s_I8StructSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I8StructSet = s2s_StructSet<int32_t, int8_t> [static], [constexpr]
Definition at line 6123 of file wasm-interpreter.cc.
s2s_I8UArrayGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I8UArrayGet = s2s_ArrayGet<uint32_t, uint8_t> [static], [constexpr]
Definition at line 6561 of file wasm-interpreter.cc.
s2s_I8UStructGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_I8UStructGet = s2s_StructGet<uint32_t, uint8_t> [static], [constexpr]
Definition at line 6079 of file wasm-interpreter.cc.
s2s_RefCast
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_RefCast = RefCast<false> [static], [constexpr]
Definition at line 6776 of file wasm-interpreter.cc.
s2s_RefCastNull
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_RefCastNull = RefCast<true> [static], [constexpr]
Definition at line 6777 of file wasm-interpreter.cc.
s2s_RefTest
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_RefTest = RefTest<false> [static], [constexpr]
Definition at line 6797 of file wasm-interpreter.cc.
s2s_RefTestNull
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_RefTestNull = RefTest<true> [static], [constexpr]
Definition at line 6798 of file wasm-interpreter.cc.
s2s_S128ArrayFill
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_S128ArrayFill = s2s_ArrayFill<Simd128> [static], [constexpr]
Definition at line 6680 of file wasm-interpreter.cc.
s2s_S128ArrayGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_S128ArrayGet = s2s_ArrayGet<Simd128> [static], [constexpr]
Definition at line 6568 of file wasm-interpreter.cc.
s2s_S128ArrayNew
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_S128ArrayNew = s2s_ArrayNew<Simd128> [static], [constexpr]
Definition at line 6192 of file wasm-interpreter.cc.
s2s_S128ArraySet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_S128ArraySet = s2s_ArraySet<Simd128> [static], [constexpr]
Definition at line 6621 of file wasm-interpreter.cc.
s2s_S128Drop
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_S128Drop = s2s_Drop<Simd128> [static], [constexpr]
Definition at line 1046 of file wasm-interpreter.cc.
s2s_S128GlobalGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_S128GlobalGet = s2s_GlobalGet<Simd128> [static], [constexpr]
Definition at line 949 of file wasm-interpreter.cc.
s2s_S128GlobalSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_S128GlobalSet = s2s_GlobalSet<Simd128> [static], [constexpr]
Definition at line 1003 of file wasm-interpreter.cc.
s2s_S128Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_S128Select = s2s_Select<Simd128> [static], [constexpr]
Definition at line 1921 of file wasm-interpreter.cc.
s2s_S128StructGet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_S128StructGet = s2s_StructGet<Simd128> [static], [constexpr]
Definition at line 6086 of file wasm-interpreter.cc.
s2s_S128StructSet
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_S128StructSet = s2s_StructSet<Simd128> [static], [constexpr]
Definition at line 6129 of file wasm-interpreter.cc.
s2s_SimdI16x8ExtAddPairwiseI8x16S
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8ExtAddPairwiseI8x16S [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtAddPairwise<int16x8, int8x16, int16_t, int8_t>
Definition at line 5554 of file wasm-interpreter.cc.
s2s_SimdI16x8ExtAddPairwiseI8x16U
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8ExtAddPairwiseI8x16U [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtAddPairwise<int16x8, int8x16, uint16_t, uint8_t>
Definition at line 5556 of file wasm-interpreter.cc.
s2s_SimdI16x8ExtMulHighI8x16S
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8ExtMulHighI8x16S [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtMul<int8x16, int16x8, int8_t, int16_t, 8>
Definition at line 5017 of file wasm-interpreter.cc.
s2s_SimdI16x8ExtMulHighI8x16U
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8ExtMulHighI8x16U [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtMul<int8x16, int16x8, uint8_t, uint16_t, 8>
Definition at line 5021 of file wasm-interpreter.cc.
s2s_SimdI16x8ExtMulLowI8x16S
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8ExtMulLowI8x16S [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtMul<int8x16, int16x8, int8_t, int16_t, 0>
Definition at line 5015 of file wasm-interpreter.cc.
s2s_SimdI16x8ExtMulLowI8x16U
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8ExtMulLowI8x16U [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtMul<int8x16, int16x8, uint8_t, uint16_t, 0>
Definition at line 5019 of file wasm-interpreter.cc.
s2s_SimdI16x8RelaxedLaneSelect
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8RelaxedLaneSelect = s2s_DoSimdSelect [static], [constexpr]
Definition at line 5142 of file wasm-interpreter.cc.
s2s_SimdI32x4ExtAddPairwiseI16x8S
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4ExtAddPairwiseI16x8S [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtAddPairwise<int32x4, int16x8, int32_t, int16_t>
Definition at line 5550 of file wasm-interpreter.cc.
s2s_SimdI32x4ExtAddPairwiseI16x8U
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4ExtAddPairwiseI16x8U [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtAddPairwise<int32x4, int16x8, uint32_t, uint16_t>
Definition at line 5552 of file wasm-interpreter.cc.
s2s_SimdI32x4ExtMulHighI16x8S
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4ExtMulHighI16x8S [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtMul<int16x8, int32x4, int16_t, int32_t, 4>
Definition at line 5025 of file wasm-interpreter.cc.
s2s_SimdI32x4ExtMulHighI16x8U
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4ExtMulHighI16x8U [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtMul<int16x8, int32x4, uint16_t, uint32_t, 4>
Definition at line 5029 of file wasm-interpreter.cc.
s2s_SimdI32x4ExtMulLowI16x8S
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4ExtMulLowI16x8S [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtMul<int16x8, int32x4, int16_t, int32_t, 0>
Definition at line 5023 of file wasm-interpreter.cc.
s2s_SimdI32x4ExtMulLowI16x8U
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4ExtMulLowI16x8U [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtMul<int16x8, int32x4, uint16_t, uint32_t, 0>
Definition at line 5027 of file wasm-interpreter.cc.
s2s_SimdI32x4RelaxedLaneSelect
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4RelaxedLaneSelect = s2s_DoSimdSelect [static], [constexpr]
Definition at line 5143 of file wasm-interpreter.cc.
s2s_SimdI64x2ExtMulHighI32x4S
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI64x2ExtMulHighI32x4S [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtMul<int32x4, int64x2, int32_t, int64_t, 2>
Definition at line 5033 of file wasm-interpreter.cc.
s2s_SimdI64x2ExtMulHighI32x4U
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI64x2ExtMulHighI32x4U [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtMul<int32x4, int64x2, uint32_t, uint64_t, 2>
Definition at line 5037 of file wasm-interpreter.cc.
s2s_SimdI64x2ExtMulLowI32x4S
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI64x2ExtMulLowI32x4S [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtMul<int32x4, int64x2, int32_t, int64_t, 0>
Definition at line 5031 of file wasm-interpreter.cc.
s2s_SimdI64x2ExtMulLowI32x4U
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI64x2ExtMulLowI32x4U [static], [constexpr]
Initial value:
=
      s2s_DoSimdExtMul<int32x4, int64x2, uint32_t, uint64_t, 0>
Definition at line 5035 of file wasm-interpreter.cc.
s2s_SimdI64x2RelaxedLaneSelect
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI64x2RelaxedLaneSelect = s2s_DoSimdSelect [static], [constexpr]
Definition at line 5144 of file wasm-interpreter.cc.
s2s_SimdI8x16RelaxedLaneSelect
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16RelaxedLaneSelect = s2s_DoSimdSelect [static], [constexpr]
Definition at line 5141 of file wasm-interpreter.cc.
s2s_SimdI8x16RelaxedSwizzle
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16RelaxedSwizzle = s2s_SimdI8x16Swizzle [static], [constexpr]
Definition at line 5211 of file wasm-interpreter.cc.
s2s_SimdS128Load16Lane
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load16Lane [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadLane<int16x8, int16_t>
Definition at line 5472 of file wasm-interpreter.cc.
s2s_SimdS128Load16Lane_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load16Lane_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadLane<int16x8, int16_t, uint64_t, memory_offset64_t>
Definition at line 5480 of file wasm-interpreter.cc.
s2s_SimdS128Load16Splat
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load16Splat [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadSplat<int16x8, int16_t, uint32_t, memory_offset32_t>
Definition at line 5313 of file wasm-interpreter.cc.
s2s_SimdS128Load16Splat_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load16Splat_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadSplat<int16x8, int16_t, uint64_t, memory_offset64_t>
Definition at line 5315 of file wasm-interpreter.cc.
s2s_SimdS128Load16x4S
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load16x4S [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadExtend<int32x4, int32_t, int16_t, uint32_t,
                           memory_offset32_t>
Definition at line 5373 of file wasm-interpreter.cc.
s2s_SimdS128Load16x4S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load16x4S_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadExtend<int32x4, int32_t, int16_t, uint64_t,
                           memory_offset64_t>
Definition at line 5376 of file wasm-interpreter.cc.
s2s_SimdS128Load16x4U
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load16x4U [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadExtend<int32x4, uint32_t, uint16_t, uint32_t,
                           memory_offset32_t>
Definition at line 5379 of file wasm-interpreter.cc.
s2s_SimdS128Load16x4U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load16x4U_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadExtend<int32x4, uint32_t, uint16_t, uint64_t,
                           memory_offset64_t>
Definition at line 5382 of file wasm-interpreter.cc.
s2s_SimdS128Load32Lane
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load32Lane [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadLane<int32x4, int32_t>
Definition at line 5474 of file wasm-interpreter.cc.
s2s_SimdS128Load32Lane_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load32Lane_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadLane<int32x4, int32_t, uint64_t, memory_offset64_t>
Definition at line 5482 of file wasm-interpreter.cc.
s2s_SimdS128Load32Splat
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load32Splat [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadSplat<int32x4, int32_t, uint32_t, memory_offset32_t>
Definition at line 5317 of file wasm-interpreter.cc.
s2s_SimdS128Load32Splat_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load32Splat_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadSplat<int32x4, int32_t, uint64_t, memory_offset64_t>
Definition at line 5319 of file wasm-interpreter.cc.
s2s_SimdS128Load32x2S
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load32x2S [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadExtend<int64x2, int64_t, int32_t, uint32_t,
                           memory_offset32_t>
Definition at line 5385 of file wasm-interpreter.cc.
s2s_SimdS128Load32x2S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load32x2S_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadExtend<int64x2, int64_t, int32_t, uint64_t,
                           memory_offset64_t>
Definition at line 5388 of file wasm-interpreter.cc.
s2s_SimdS128Load32x2U
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load32x2U [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadExtend<int64x2, uint64_t, uint32_t, uint32_t,
                           memory_offset32_t>
Definition at line 5391 of file wasm-interpreter.cc.
s2s_SimdS128Load32x2U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load32x2U_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadExtend<int64x2, uint64_t, uint32_t, uint64_t,
                           memory_offset64_t>
Definition at line 5394 of file wasm-interpreter.cc.
s2s_SimdS128Load32Zero
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load32Zero [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadZeroExtend<int32x4, uint32_t, uint32_t, memory_offset32_t>
Definition at line 5432 of file wasm-interpreter.cc.
s2s_SimdS128Load32Zero_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load32Zero_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadZeroExtend<int32x4, uint32_t, uint64_t, memory_offset64_t>
Definition at line 5434 of file wasm-interpreter.cc.
s2s_SimdS128Load64Lane
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load64Lane [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadLane<int64x2, uint64_t>
Definition at line 5476 of file wasm-interpreter.cc.
s2s_SimdS128Load64Lane_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load64Lane_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadLane<int64x2, int64_t, uint64_t, memory_offset64_t>
Definition at line 5484 of file wasm-interpreter.cc.
s2s_SimdS128Load64Splat
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load64Splat [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadSplat<int64x2, int64_t, uint32_t, memory_offset32_t>
Definition at line 5321 of file wasm-interpreter.cc.
s2s_SimdS128Load64Splat_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load64Splat_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadSplat<int64x2, int64_t, uint64_t, memory_offset64_t>
Definition at line 5323 of file wasm-interpreter.cc.
s2s_SimdS128Load64Zero
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load64Zero [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadZeroExtend<int64x2, uint64_t, uint32_t, memory_offset32_t>
Definition at line 5436 of file wasm-interpreter.cc.
s2s_SimdS128Load64Zero_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load64Zero_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadZeroExtend<int64x2, uint64_t, uint64_t, memory_offset64_t>
Definition at line 5438 of file wasm-interpreter.cc.
s2s_SimdS128Load8Lane
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load8Lane [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadLane<int8x16, int8_t>
Definition at line 5470 of file wasm-interpreter.cc.
s2s_SimdS128Load8Lane_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load8Lane_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadLane<int8x16, int8_t, uint64_t, memory_offset64_t>
Definition at line 5478 of file wasm-interpreter.cc.
s2s_SimdS128Load8Splat
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load8Splat [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadSplat<int8x16, int8_t, uint32_t, memory_offset32_t>
Definition at line 5309 of file wasm-interpreter.cc.
s2s_SimdS128Load8Splat_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load8Splat_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadSplat<int8x16, int8_t, uint64_t, memory_offset64_t>
Definition at line 5311 of file wasm-interpreter.cc.
s2s_SimdS128Load8x8S
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load8x8S [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadExtend<int16x8, int16_t, int8_t, uint32_t,
                           memory_offset32_t>
Definition at line 5361 of file wasm-interpreter.cc.
s2s_SimdS128Load8x8S_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load8x8S_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadExtend<int16x8, int16_t, int8_t, uint64_t,
                           memory_offset64_t>
Definition at line 5364 of file wasm-interpreter.cc.
s2s_SimdS128Load8x8U
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load8x8U [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadExtend<int16x8, uint16_t, uint8_t, uint32_t,
                           memory_offset32_t>
Definition at line 5367 of file wasm-interpreter.cc.
s2s_SimdS128Load8x8U_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Load8x8U_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdLoadExtend<int16x8, uint16_t, uint8_t, uint64_t,
                           memory_offset64_t>
Definition at line 5370 of file wasm-interpreter.cc.
s2s_SimdS128LoadMem
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128LoadMem [static], [constexpr]
Initial value:
=
      s2s_SimdS128LoadMemI<uint32_t, memory_offset32_t>
Definition at line 4926 of file wasm-interpreter.cc.
s2s_SimdS128LoadMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128LoadMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_SimdS128LoadMemI<uint64_t, memory_offset64_t>
Definition at line 4928 of file wasm-interpreter.cc.
s2s_SimdS128Select
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Select = s2s_DoSimdSelect [static], [constexpr]
Definition at line 5145 of file wasm-interpreter.cc.
s2s_SimdS128Store16Lane
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Store16Lane [static], [constexpr]
Initial value:
=
      s2s_DoSimdStoreLane<int16x8, int16_t>
Definition at line 5518 of file wasm-interpreter.cc.
s2s_SimdS128Store16Lane_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Store16Lane_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdStoreLane<int16x8, int16_t, uint64_t, memory_offset64_t>
Definition at line 5526 of file wasm-interpreter.cc.
s2s_SimdS128Store32Lane
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Store32Lane [static], [constexpr]
Initial value:
=
      s2s_DoSimdStoreLane<int32x4, int32_t>
Definition at line 5520 of file wasm-interpreter.cc.
s2s_SimdS128Store32Lane_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Store32Lane_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdStoreLane<int32x4, int32_t, uint64_t, memory_offset64_t>
Definition at line 5528 of file wasm-interpreter.cc.
s2s_SimdS128Store64Lane
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Store64Lane [static], [constexpr]
Initial value:
=
      s2s_DoSimdStoreLane<int64x2, uint64_t>
Definition at line 5522 of file wasm-interpreter.cc.
s2s_SimdS128Store64Lane_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Store64Lane_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdStoreLane<int64x2, int64_t, uint64_t, memory_offset64_t>
Definition at line 5530 of file wasm-interpreter.cc.
s2s_SimdS128Store8Lane
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Store8Lane [static], [constexpr]
Initial value:
=
      s2s_DoSimdStoreLane<int8x16, int8_t>
Definition at line 5516 of file wasm-interpreter.cc.
s2s_SimdS128Store8Lane_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128Store8Lane_Idx64 [static], [constexpr]
Initial value:
=
      s2s_DoSimdStoreLane<int8x16, int8_t, uint64_t, memory_offset64_t>
Definition at line 5524 of file wasm-interpreter.cc.
s2s_SimdS128StoreMem
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128StoreMem [static], [constexpr]
Initial value:
=
      s2s_SimdS128StoreMemI<uint32_t, memory_offset32_t>
Definition at line 4955 of file wasm-interpreter.cc.
s2s_SimdS128StoreMem_Idx64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128StoreMem_Idx64 [static], [constexpr]
Initial value:
=
      s2s_SimdS128StoreMemI<uint64_t, memory_offset64_t>
Definition at line 4957 of file wasm-interpreter.cc.
s2s_Table64Copy_32_64_32
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_Table64Copy_32_64_32 [static], [constexpr]
Initial value:
=
      s2s_Table64CopyImpl<uint32_t, uint64_t, uint32_t>
Definition at line 4109 of file wasm-interpreter.cc.
s2s_Table64Copy_64_32_32
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_Table64Copy_64_32_32 [static], [constexpr]
Initial value:
=
      s2s_Table64CopyImpl<uint64_t, uint32_t, uint32_t>
Definition at line 4111 of file wasm-interpreter.cc.
s2s_Table64Copy_64_64_64
template<bool Compressed>
constexpr auto v8::internal::wasm::Handlers< Compressed >::s2s_Table64Copy_64_64_64 [static], [constexpr]
Initial value:
=
      s2s_Table64CopyImpl<uint64_t, uint64_t, uint64_t>
Definition at line 4113 of file wasm-interpreter.cc.
sp
template<bool Compressed>
a a a a uint32_t* v8::internal::wasm::Handlers< Compressed >::sp
Definition at line 5126 of file wasm-interpreter.cc.
uint16_t
template<bool Compressed>
a a v8::internal::wasm::Handlers< Compressed >::uint16_t
Definition at line 5076 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadLane(), and v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdStoreLane().
uint32_t [1/3]
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::uint32_t
Definition at line 5057 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::pop(), v8::internal::wasm::Handlers< Compressed >::push(), v8::internal::wasm::Handlers< Compressed >::r2s_BrTable(), v8::internal::wasm::Handlers< Compressed >::r2s_GlobalSetF(), v8::internal::wasm::Handlers< Compressed >::r2s_GlobalSetI(), v8::internal::wasm::Handlers< Compressed >::ReadGlobalIndex(), v8::internal::wasm::Handlers< Compressed >::RefCast(), v8::internal::wasm::Handlers< Compressed >::RefTest(), v8::internal::wasm::Handlers< Compressed >::s2r_GlobalGetF(), v8::internal::wasm::Handlers< Compressed >::s2r_GlobalGetI(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayCopy(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayFill(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayGet(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayInitSegment(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNew(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewDefault(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewFixed(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewSegment(), v8::internal::wasm::Handlers< Compressed >::s2s_ArraySet(), v8::internal::wasm::Handlers< Compressed >::s2s_AssertNotNullTypecheck(), v8::internal::wasm::Handlers< Compressed >::s2s_AssertNullTypecheck(), v8::internal::wasm::Handlers< Compressed >::s2s_AtomicNotify(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCast(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnCastFail(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNull(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNonNullWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNull(), v8::internal::wasm::Handlers< Compressed >::s2s_BranchOnNullWithParams(), v8::internal::wasm::Handlers< Compressed >::s2s_BrTable(), v8::internal::wasm::Handlers< Compressed >::s2s_CallFunction(), v8::internal::wasm::Handlers< Compressed >::s2s_CallImportedFunction(), v8::internal::wasm::Handlers< Compressed >::s2s_CallIndirect(), v8::internal::wasm::Handlers< Compressed >::s2s_CallIndirect64(), v8::internal::wasm::Handlers< Compressed >::s2s_CallRef(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_ll(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_lq(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_ql(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlot_qq(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlotMulti(), v8::internal::wasm::Handlers< Compressed >::s2s_CopySlotRef(), v8::internal::wasm::Handlers< Compressed >::s2s_DataDrop(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdExtMul(), v8::internal::wasm::Handlers< Compressed >::s2s_ElemDrop(), v8::internal::wasm::Handlers< Compressed >::s2s_GlobalGet(), v8::internal::wasm::Handlers< Compressed >::s2s_GlobalSet(), v8::internal::wasm::Handlers< Compressed >::s2s_I31GetU(), v8::internal::wasm::Handlers< Compressed >::s2s_I32AtomicWait(), v8::internal::wasm::Handlers< Compressed >::s2s_I64AtomicWait(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Fill(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Grow(), v8::internal::wasm::Handlers< Compressed >::s2s_Memory64Init(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryFill(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryGrow(), v8::internal::wasm::Handlers< Compressed >::s2s_MemoryInit(), v8::internal::wasm::Handlers< Compressed >::s2s_MemorySize(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayFill(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayGet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayNew(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArraySet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefFunc(), v8::internal::wasm::Handlers< Compressed >::s2s_RefGlobalGet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefGlobalSet(), v8::internal::wasm::Handlers< Compressed >::s2s_RefI31(), v8::internal::wasm::Handlers< Compressed >::s2s_RefNull(), v8::internal::wasm::Handlers< Compressed >::s2s_Rethrow(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCall(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallImportedFunction(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallIndirect(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallIndirect64(), v8::internal::wasm::Handlers< Compressed >::s2s_ReturnCallRef(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNew(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNewDefault(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64CopyImpl(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Fill(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Get(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Grow(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Init(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Set(), v8::internal::wasm::Handlers< Compressed >::s2s_Table64Size(), v8::internal::wasm::Handlers< Compressed >::s2s_TableCopy(), v8::internal::wasm::Handlers< Compressed >::s2s_TableFill(), v8::internal::wasm::Handlers< Compressed >::s2s_TableGet(), v8::internal::wasm::Handlers< Compressed >::s2s_TableGrow(), v8::internal::wasm::Handlers< Compressed >::s2s_TableInit(), v8::internal::wasm::Handlers< Compressed >::s2s_TableSet(), v8::internal::wasm::Handlers< Compressed >::s2s_TableSize(), and v8::internal::wasm::Handlers< Compressed >::s2s_Throw().
uint32_t [2/3]
template<bool Compressed>
a v8::internal::wasm::Handlers< Compressed >::uint32_t
Definition at line 5072 of file wasm-interpreter.cc.
uint32_t [3/3]
template<bool Compressed>
a a a a v8::internal::wasm::Handlers< Compressed >::uint32_t
Definition at line 5088 of file wasm-interpreter.cc.
uint8_t
template<bool Compressed>
a a a v8::internal::wasm::Handlers< Compressed >::uint8_t
Definition at line 5082 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::r2r_LoadMemF(), v8::internal::wasm::Handlers< Compressed >::r2r_LoadMemI(), v8::internal::wasm::Handlers< Compressed >::r2s_GlobalSetF(), v8::internal::wasm::Handlers< Compressed >::r2s_GlobalSetI(), v8::internal::wasm::Handlers< Compressed >::r2s_LoadMem(), v8::internal::wasm::Handlers< Compressed >::r2s_LoadStoreMem(), v8::internal::wasm::Handlers< Compressed >::r2s_StoreMemF(), v8::internal::wasm::Handlers< Compressed >::r2s_StoreMemI(), v8::internal::wasm::Handlers< Compressed >::ReadMemoryAddress(), v8::internal::wasm::Handlers< Compressed >::s2r_GlobalGetF(), v8::internal::wasm::Handlers< Compressed >::s2r_GlobalGetI(), v8::internal::wasm::Handlers< Compressed >::s2r_LoadMemF(), v8::internal::wasm::Handlers< Compressed >::s2r_LoadMemI(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadExtend(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadLane(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadSplat(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdLoadZeroExtend(), v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdStoreLane(), v8::internal::wasm::Handlers< Compressed >::s2s_GlobalGet(), v8::internal::wasm::Handlers< Compressed >::s2s_GlobalSet(), v8::internal::wasm::Handlers< Compressed >::s2s_LoadMem(), v8::internal::wasm::Handlers< Compressed >::s2s_LoadMem_LocalSet(), v8::internal::wasm::Handlers< Compressed >::s2s_LoadStoreMem(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdS128StoreMemI(), and v8::internal::wasm::Handlers< Compressed >::s2s_StoreMem().
v1
template<bool Compressed>
int32x4 v8::internal::wasm::Handlers< Compressed >::v1 = pop<Simd128>(sp, code, wasm_runtime).to_i32x4()
Definition at line 5130 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::for(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8DotI8x16I7x16S(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI16x8S(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI8x16I7x16AddS(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Shuffle(), and v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Swizzle().
v2
template<bool Compressed>
int32x4 v8::internal::wasm::Handlers< Compressed >::v2 = pop<Simd128>(sp, code, wasm_runtime).to_i32x4()
Definition at line 5129 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::for(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI16x8DotI8x16I7x16S(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI16x8S(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI32x4DotI8x16I7x16AddS(), v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Shuffle(), and v8::internal::wasm::Handlers< Compressed >::s2s_SimdI8x16Swizzle().
wasm_runtime
template<bool Compressed>
a a a a uint32_t WasmInterpreterRuntime* v8::internal::wasm::Handlers< Compressed >::wasm_runtime
Definition at line 5126 of file wasm-interpreter.cc.
wide
template<bool Compressed>
v8::internal::wasm::Handlers< Compressed >::wide
Definition at line 4996 of file wasm-interpreter.cc.
Referenced by v8::internal::wasm::Handlers< Compressed >::s2s_DoSimdExtMul().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.cc