wasm::RefImpl< Ref, JSType > Class Template Reference
Public Member Functions
~RefImpl ()
own< Ref > copy () const
StoreImpl * store () const
i::Isolate * isolate () const
i::DirectHandle< JSType > v8_object () const
void * get_host_info () const
void set_host_info (void *info, void(*finalizer)(void *))
Static Public Member Functions
static own< Ref > make (StoreImpl *store, i::DirectHandle< JSType > obj)
Private Member Functions
RefImpl ()=default
i::Address * location () const
Private Attributes
i::IndirectHandle< i::JSReceiver > val_
StoreImpl * store_
Detailed Description
template<class Ref, class JSType>
class wasm::RefImpl< Ref, JSType >
Definition at line 960 of file c-api.cc.
Constructor & Destructor Documentation
 RefImpl()
template<class Ref , class JSType >
wasm::RefImpl< Ref, JSType >::~RefImpl () [inline]
Definition at line 971 of file c-api.cc.
{ i::GlobalHandles::Destroy(location()); }
References v8::internal::GlobalHandles::Destroy(), and wasm::RefImpl< Ref, JSType >::location().
RefImpl()
template<class Ref , class JSType >
wasm::RefImpl< Ref, JSType >::RefImpl () [private], [default]
Referenced by wasm::RefImpl< Ref, JSType >::make().
Member Function Documentation
copy()
template<class Ref , class JSType >
own<Ref> wasm::RefImpl< Ref, JSType >::copy () const [inline]
Definition at line 973 of file c-api.cc.
                        {
    v8::Isolate::Scope isolate_scope(store()->isolate());
    return make(store(), v8_object());
  }
References wasm::RefImpl< Ref, JSType >::isolate(), wasm::RefImpl< Ref, JSType >::make(), wasm::RefImpl< Ref, JSType >::store(), and wasm::RefImpl< Ref, JSType >::v8_object().
get_host_info()
template<class Ref , class JSType >
void* wasm::RefImpl< Ref, JSType >::get_host_info () const [inline]
Definition at line 984 of file c-api.cc.
                              {
    v8::Isolate::Scope isolate_scope(store()->isolate());
    return store()->GetHostInfo(v8_object());
  }
References wasm::StoreImpl::GetHostInfo(), wasm::RefImpl< Ref, JSType >::isolate(), wasm::RefImpl< Ref, JSType >::store(), and wasm::RefImpl< Ref, JSType >::v8_object().
isolate()
template<class Ref , class JSType >
i::Isolate* wasm::RefImpl< Ref, JSType >::isolate () const [inline]
Definition at line 980 of file c-api.cc.
{ return store()->i_isolate(); }
References wasm::StoreImpl::i_isolate(), and wasm::RefImpl< Ref, JSType >::store().
Referenced by wasm::RefImpl< Ref, JSType >::copy(), wasm::RefImpl< Ref, JSType >::get_host_info(), and wasm::RefImpl< Ref, JSType >::set_host_info().
location()
template<class Ref , class JSType >
i::Address* wasm::RefImpl< Ref, JSType >::location () const [inline], [private]
Definition at line 997 of file c-api.cc.
                             {
    return reinterpret_cast<i::Address*>(val_.address());
  }
References wasm::RefImpl< Ref, JSType >::val_.
Referenced by wasm::RefImpl< Ref, JSType >::~RefImpl().
make()
template<class Ref , class JSType >
static own<Ref> wasm::RefImpl< Ref, JSType >::make (StoreImpl * store, i::DirectHandle< JSType > obj) [inline], [static]
Definition at line 962 of file c-api.cc.
                                                                    {
    RefImpl* self = new (std::nothrow) RefImpl();
    if (!self) return nullptr;
    self->store_ = store;
    v8::Isolate::Scope isolate_scope(store->isolate());
    self->val_ = store->i_isolate()->global_handles()->Create(*obj);
    return make_own(seal<Ref>(self));
  }
References v8::internal::GlobalHandles::Create(), v8::internal::Isolate::global_handles(), wasm::StoreImpl::i_isolate(), wasm::StoreImpl::isolate(), wasm::RefImpl< Ref, JSType >::RefImpl(), and wasm::RefImpl< Ref, JSType >::store().
Referenced by wasm::RefImpl< Ref, JSType >::copy().
set_host_info()
template<class Ref , class JSType >
void wasm::RefImpl< Ref, JSType >::set_host_info (void * info, void(*)(void *) finalizer) [inline]
Definition at line 989 of file c-api.cc.
                                                           {
    v8::Isolate::Scope isolate_scope(store()->isolate());
    store()->SetHostInfo(v8_object(), info, finalizer);
  }
References wasm::RefImpl< Ref, JSType >::isolate(), wasm::StoreImpl::SetHostInfo(), wasm::RefImpl< Ref, JSType >::store(), and wasm::RefImpl< Ref, JSType >::v8_object().
store()
template<class Ref , class JSType >
StoreImpl* wasm::RefImpl< Ref, JSType >::store () const [inline]
Definition at line 978 of file c-api.cc.
{ return store_; }
References wasm::RefImpl< Ref, JSType >::store_.
Referenced by wasm::RefImpl< Ref, JSType >::copy(), wasm::RefImpl< Ref, JSType >::get_host_info(), wasm::RefImpl< Ref, JSType >::isolate(), wasm::RefImpl< Ref, JSType >::make(), and wasm::RefImpl< Ref, JSType >::set_host_info().
v8_object()
template<class Ref , class JSType >
i::DirectHandle<JSType> wasm::RefImpl< Ref, JSType >::v8_object () const [inline]
Definition at line 982 of file c-api.cc.
{ return i::Cast<JSType>(val_); }
References wasm::RefImpl< Ref, JSType >::val_.
Referenced by wasm::RefImpl< Ref, JSType >::copy(), wasm::RefImpl< Ref, JSType >::get_host_info(), and wasm::RefImpl< Ref, JSType >::set_host_info().
Member Data Documentation
store_
template<class Ref , class JSType >
StoreImpl* wasm::RefImpl< Ref, JSType >::store_ [private]
Definition at line 1002 of file c-api.cc.
Referenced by wasm::RefImpl< Ref, JSType >::store().
val_
template<class Ref , class JSType >
i::IndirectHandle<i::JSReceiver> wasm::RefImpl< Ref, JSType >::val_ [private]
Definition at line 1001 of file c-api.cc.
Referenced by wasm::RefImpl< Ref, JSType >::location(), and wasm::RefImpl< Ref, JSType >::v8_object().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/c-api.cc