v8::internal::ObjectStatsCollectorImpl Class Reference
Public Types
enum Phase { kPhase1
, kPhase2
 }
enum class CollectFieldStats { kNo
, kYes
 }
Public Member Functions
ObjectStatsCollectorImpl (Heap *heap, ObjectStats *stats)
void CollectGlobalStatistics ()
void CollectStatistics (Tagged< HeapObject > obj, Phase phase, CollectFieldStats collect_field_stats)
Static Public Attributes
static const int kNumberOfPhases = kPhase2 + 1
Private Types
enum CowMode { kCheckCow
, kIgnoreCow
 }
Private Member Functions
Isolate * isolate ()
bool RecordVirtualObjectStats (Tagged< HeapObject > parent, Tagged< HeapObject > obj, ObjectStats::VirtualInstanceType type, size_t size, size_t over_allocated, CowMode check_cow_array=kCheckCow)
void RecordExternalResourceStats (Address resource, ObjectStats::VirtualInstanceType type, size_t size)
bool RecordSimpleVirtualObjectStats (Tagged< HeapObject > parent, Tagged< HeapObject > obj, ObjectStats::VirtualInstanceType type)
void RecordPotentialDescriptorArraySavingsStats (Tagged< DescriptorArray > obj)
template<typename Dictionary >
void RecordHashTableVirtualObjectStats (Tagged< HeapObject > parent, Tagged< Dictionary > hash_table, ObjectStats::VirtualInstanceType type)
bool SameLiveness (Tagged< HeapObject > obj1, Tagged< HeapObject > obj2)
bool CanRecordFixedArray (Tagged< FixedArrayBase > array)
bool IsCowArray (Tagged< FixedArrayBase > array)
bool ShouldRecordObject (Tagged< HeapObject > object, CowMode check_cow_array)
bool RecordObjectStats (Tagged< HeapObject > obj, InstanceType type, size_t size, size_t over_allocated=ObjectStats::kNoOverAllocation)
void RecordVirtualObjectsForConstantPoolOrEmbeddedObjects (Tagged< HeapObject > parent, Tagged< HeapObject > object, ObjectStats::VirtualInstanceType type)
void RecordVirtualAllocationSiteDetails (Tagged< AllocationSite > site)
void RecordVirtualBytecodeArrayDetails (Tagged< BytecodeArray > bytecode)
void RecordVirtualCodeDetails (Tagged< InstructionStream > code)
void RecordVirtualContext (Tagged< Context > context)
void RecordVirtualFeedbackVectorDetails (Tagged< FeedbackVector > vector)
void RecordVirtualFixedArrayDetails (Tagged< FixedArray > array)
void RecordVirtualFunctionTemplateInfoDetails (Tagged< FunctionTemplateInfo > fti)
void RecordVirtualJSGlobalObjectDetails (Tagged< JSGlobalObject > object)
void RecordVirtualJSObjectDetails (Tagged< JSObject > object)
void RecordVirtualMapDetails (Tagged< Map > map)
void RecordVirtualScriptDetails (Tagged< Script > script)
void RecordVirtualExternalStringDetails (Tagged< ExternalString > script)
void RecordVirtualSharedFunctionInfoDetails (Tagged< SharedFunctionInfo > info)
void RecordVirtualArrayBoilerplateDescription (Tagged< ArrayBoilerplateDescription > description)
PtrComprCageBase cage_base () const
Private Attributes
Heap *const heap_
ObjectStats *const stats_
NonAtomicMarkingState *const marking_state_
std::unordered_set< Tagged< HeapObject >, Object::Hasher, Object::KeyEqualSafe > virtual_objects_
std::unordered_set< Address > external_resources_
FieldStatsCollector field_stats_collector_
Detailed Description
Definition at line 384 of file object-stats.cc.
Member Enumeration Documentation
CollectFieldStats
enum v8::internal::ObjectStatsCollectorImpl::CollectFieldStats [strong]
Enumerator
kNo
kYes
Definition at line 396 of file object-stats.cc.
{ kNo, kYes };
CowMode
enum v8::internal::ObjectStatsCollectorImpl::CowMode [private]
Enumerator
kCheckCow
kIgnoreCow
Definition at line 401 of file object-stats.cc.
               {
    kCheckCow,
    kIgnoreCow,
  };
Phase
enum v8::internal::ObjectStatsCollectorImpl::Phase
Enumerator
kPhase1
kPhase2
Definition at line 386 of file object-stats.cc.
             {
    kPhase1,
    kPhase2,
  };
Constructor & Destructor Documentation
ObjectStatsCollectorImpl()
v8::internal::ObjectStatsCollectorImpl::ObjectStatsCollectorImpl (Heap * heap, ObjectStats * stats)
Definition at line 481 of file object-stats.cc.
    : heap_(heap),
      stats_(stats),
      marking_state_(heap->non_atomic_marking_state()),
      field_stats_collector_(
          heap_, &stats->tagged_fields_count_, &stats->embedder_fields_count_,
          &stats->inobject_smi_fields_count_,
          &stats->boxed_double_fields_count_, &stats->string_data_count_,
          &stats->raw_fields_count_) {}
Member Function Documentation
cage_base()
PtrComprCageBase v8::internal::ObjectStatsCollectorImpl::cage_base () const [inline], [private]
Definition at line 468 of file object-stats.cc.
                                     {
    return field_stats_collector_.cage_base();
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), and field_stats_collector_.
Referenced by CollectStatistics(), RecordSimpleVirtualObjectStats(), RecordVirtualCodeDetails(), RecordVirtualContext(), RecordVirtualFeedbackVectorDetails(), RecordVirtualMapDetails(), RecordVirtualObjectsForConstantPoolOrEmbeddedObjects(), and RecordVirtualScriptDetails().
CanRecordFixedArray()
bool v8::internal::ObjectStatsCollectorImpl::CanRecordFixedArray (Tagged< FixedArrayBase > array) [private]
Definition at line 895 of file object-stats.cc.
                                  {
  ReadOnlyRoots roots(heap_);
  return array != roots.empty_fixed_array() &&
         array != roots.empty_slow_element_dictionary() &&
         array != roots.empty_property_dictionary();
}
References heap_.
Referenced by ShouldRecordObject().
CollectGlobalStatistics()
void v8::internal::ObjectStatsCollectorImpl::CollectGlobalStatistics ()
Definition at line 858 of file object-stats.cc.
                                                       {
  // Iterate boilerplates first to disambiguate them from regular JS objects.
  Tagged<Object> list = heap_->allocation_sites_list();
  Tagged<AllocationSiteWithWeakNext> site;
  while (TryCast(list, &site)) {
    RecordVirtualAllocationSiteDetails(site);
    list = site->weak_next();
  }
  // FixedArray.
  RecordSimpleVirtualObjectStats(HeapObject(), heap_->serialized_objects(),
                                 StatsEnum::SERIALIZED_OBJECTS_TYPE);
  RecordSimpleVirtualObjectStats(HeapObject(), heap_->smi_string_cache(),
                                 StatsEnum::NUMBER_STRING_CACHE_TYPE);
  RecordSimpleVirtualObjectStats(HeapObject(), heap_->double_string_cache(),
                                 StatsEnum::NUMBER_STRING_CACHE_TYPE);
  RecordSimpleVirtualObjectStats(HeapObject(), heap_->string_split_cache(),
                                 StatsEnum::STRING_SPLIT_CACHE_TYPE);
  RecordSimpleVirtualObjectStats(HeapObject(), heap_->regexp_multiple_cache(),
                                 StatsEnum::REGEXP_MULTIPLE_CACHE_TYPE);
  // WeakArrayList.
  RecordSimpleVirtualObjectStats(HeapObject(),
                                 Cast<WeakArrayList>(heap_->script_list()),
                                 StatsEnum::SCRIPT_LIST_TYPE);
}
References v8::internal::Heap::allocation_sites_list(), heap_, RecordSimpleVirtualObjectStats(), RecordVirtualAllocationSiteDetails(), and v8::internal::TryCast().
Referenced by v8::internal::ObjectStatsCollector::Collect().
CollectStatistics()
void v8::internal::ObjectStatsCollectorImpl::CollectStatistics (Tagged< HeapObject > obj, Phase phase, CollectFieldStats collect_field_stats)
Definition at line 792 of file object-stats.cc.
                                           {
  DisallowGarbageCollection no_gc;
  Tagged<Map> map = obj->map(cage_base());
  InstanceType instance_type = map->instance_type();
  switch (phase) {
    case kPhase1:
      if (InstanceTypeChecker::IsFeedbackVector(instance_type)) {
        RecordVirtualFeedbackVectorDetails(Cast<FeedbackVector>(obj));
      } else if (InstanceTypeChecker::IsMap(instance_type)) {
        RecordVirtualMapDetails(Cast<Map>(obj));
      } else if (InstanceTypeChecker::IsBytecodeArray(instance_type)) {
        RecordVirtualBytecodeArrayDetails(Cast<BytecodeArray>(obj));
      } else if (InstanceTypeChecker::IsInstructionStream(instance_type)) {
        RecordVirtualCodeDetails(Cast<InstructionStream>(obj));
      } else if (InstanceTypeChecker::IsFunctionTemplateInfo(instance_type)) {
        RecordVirtualFunctionTemplateInfoDetails(
            Cast<FunctionTemplateInfo>(obj));
      } else if (InstanceTypeChecker::IsJSGlobalObject(instance_type)) {
        RecordVirtualJSGlobalObjectDetails(Cast<JSGlobalObject>(obj));
      } else if (InstanceTypeChecker::IsJSObject(instance_type)) {
        // This phase needs to come after RecordVirtualAllocationSiteDetails
        // to properly split among boilerplates.
        RecordVirtualJSObjectDetails(Cast<JSObject>(obj));
      } else if (InstanceTypeChecker::IsSharedFunctionInfo(instance_type)) {
        RecordVirtualSharedFunctionInfoDetails(Cast<SharedFunctionInfo>(obj));
      } else if (InstanceTypeChecker::IsContext(instance_type)) {
        RecordVirtualContext(Cast<Context>(obj));
      } else if (InstanceTypeChecker::IsScript(instance_type)) {
        RecordVirtualScriptDetails(Cast<Script>(obj));
      } else if (InstanceTypeChecker::IsArrayBoilerplateDescription(
                     instance_type)) {
        RecordVirtualArrayBoilerplateDescription(
            Cast<ArrayBoilerplateDescription>(obj));
      } else if (InstanceTypeChecker::IsFixedArrayExact(instance_type)) {
        // Has to go last as it triggers too eagerly.
        RecordVirtualFixedArrayDetails(Cast<FixedArray>(obj));
      }
      break;
    case kPhase2:
      size_t over_allocated = ObjectStats::kNoOverAllocation;
      if (InstanceTypeChecker::IsExternalString(instance_type)) {
        // This has to be in Phase2 to avoid conflicting with recording Script
        // sources. We still want to run RecordObjectStats after though.
        RecordVirtualExternalStringDetails(Cast<ExternalString>(obj));
      } else if (InstanceTypeChecker::IsJSObject(instance_type)) {
        over_allocated = map->instance_size() - map->UsedInstanceSize();
      }
      bool recorded = RecordObjectStats(obj, instance_type,
                                        obj->Size(cage_base()), over_allocated);
      if (recorded && InstanceTypeChecker::IsDescriptorArray(instance_type)) {
        // This DescriptorArray has just been recorded, append stats about
        // potentially wasted memory in the object.
        RecordPotentialDescriptorArraySavingsStats(Cast<DescriptorArray>(obj));
      }
      if (collect_field_stats == CollectFieldStats::kYes) {
        field_stats_collector_.RecordStats(obj);
      }
      break;
  }
}
References cage_base(), field_stats_collector_, v8::internal::InstanceTypeChecker::IsExternalString(), v8::internal::ObjectStats::kNoOverAllocation, kPhase1, kPhase2, kYes, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, RecordObjectStats(), RecordPotentialDescriptorArraySavingsStats(), v8::internal::FieldStatsCollector::RecordStats(), RecordVirtualArrayBoilerplateDescription(), RecordVirtualBytecodeArrayDetails(), RecordVirtualCodeDetails(), RecordVirtualContext(), RecordVirtualExternalStringDetails(), RecordVirtualFeedbackVectorDetails(), RecordVirtualFixedArrayDetails(), RecordVirtualFunctionTemplateInfoDetails(), RecordVirtualJSGlobalObjectDetails(), RecordVirtualJSObjectDetails(), RecordVirtualMapDetails(), RecordVirtualScriptDetails(), and RecordVirtualSharedFunctionInfoDetails().
Referenced by v8::internal::ObjectStatsVisitor::Visit().
IsCowArray()
bool v8::internal::ObjectStatsCollectorImpl::IsCowArray (Tagged< FixedArrayBase > array) [private]
Definition at line 903 of file object-stats.cc.
                                                                      {
  return array->map() == ReadOnlyRoots(heap_).fixed_cow_array_map();
}
References heap_.
Referenced by RecordVirtualFixedArrayDetails(), and ShouldRecordObject().
isolate()
Isolate* v8::internal::ObjectStatsCollectorImpl::isolate () [inline], [private]
Definition at line 406 of file object-stats.cc.
{ return heap_->isolate(); }
References heap_, and v8::internal::Heap::isolate().
Referenced by RecordVirtualFunctionTemplateInfoDetails(), and RecordVirtualJSObjectDetails().
RecordExternalResourceStats()
void v8::internal::ObjectStatsCollectorImpl::RecordExternalResourceStats (Address resource, ObjectStats::VirtualInstanceType type, size_t size) [private]
Definition at line 570 of file object-stats.cc.
                                                                        {
  if (external_resources_.find(resource) == external_resources_.end()) {
    external_resources_.insert(resource);
    stats_->RecordVirtualObjectStats(type, size, 0);
  }
}
References external_resources_, v8::internal::ObjectStats::RecordVirtualObjectStats(), size(), stats_, and v8::internal::tracing::type.
Referenced by RecordVirtualExternalStringDetails(), and RecordVirtualScriptDetails().
RecordHashTableVirtualObjectStats()
template<typename Dictionary >
void v8::internal::ObjectStatsCollectorImpl::RecordHashTableVirtualObjectStats (Tagged< HeapObject > parent, Tagged< Dictionary > hash_table, ObjectStats::VirtualInstanceType type) [private]
Definition at line 504 of file object-stats.cc.
                                         {
  size_t over_allocated =
      (hash_table->Capacity() - (hash_table->NumberOfElements() +
                                 hash_table->NumberOfDeletedElements())) *
      Dictionary::kEntrySize * kTaggedSize;
  RecordVirtualObjectStats(parent, hash_table, type, hash_table->Size(),
                           over_allocated);
}
References cppgc::internal::anonymous_namespace{gc-info-table.cc}::kEntrySize, v8::internal::kTaggedSize, RecordVirtualObjectStats(), and v8::internal::tracing::type.
Referenced by RecordVirtualJSGlobalObjectDetails(), and RecordVirtualJSObjectDetails().
RecordObjectStats()
bool v8::internal::ObjectStatsCollectorImpl::RecordObjectStats (Tagged< HeapObject > obj, InstanceType type, size_t size, size_t over_allocated = ObjectStats::kNoOverAllocation) [private]
Definition at line 885 of file object-stats.cc.
                                                                        {
  if (virtual_objects_.find(obj) == virtual_objects_.end()) {
    stats_->RecordObjectStats(type, size, over_allocated);
    return true;
  }
  return false;
}
References v8::internal::ObjectStats::RecordObjectStats(), size(), stats_, v8::internal::tracing::type, and virtual_objects_.
Referenced by CollectStatistics(), and RecordVirtualContext().
RecordPotentialDescriptorArraySavingsStats()
void v8::internal::ObjectStatsCollectorImpl::RecordPotentialDescriptorArraySavingsStats (Tagged< DescriptorArray > obj) [private]
Definition at line 522 of file object-stats.cc.
                                 {
  // The caller ensures that these stats were not recorded for this object yet.
  int wasted_value_slots_count = obj->number_of_slack_descriptors();
  for (InternalIndex i : InternalIndex::Range(obj->number_of_descriptors())) {
    if (!obj->IsInitializedDescriptor(i)) {
      // This is a half-initialized DescriptorArray, don't read from it.
      return;
    }
    PropertyDetails details = obj->GetDetails(i);
    if (details.location() != PropertyLocation::kField) continue;
    Tagged<FieldType> field_type = obj->GetFieldType(i);
    if (IsAny(field_type)) {
      ++wasted_value_slots_count;
    }
  }
  if (wasted_value_slots_count == 0) return;
  int wasted_value_slots_size = wasted_value_slots_count * kTaggedSize;
  stats_->RecordVirtualObjectStats(
      StatsEnum::WASTED_DESCRIPTOR_ARRAY_VALUES_TYPE, wasted_value_slots_size,
      ObjectStats::kNoOverAllocation);
  // It should be possible to pack PropertyDetails into one byte.
  int wasted_details_space =
      obj->number_of_all_descriptors() * (kTaggedSize - 1);
  stats_->RecordVirtualObjectStats(
      StatsEnum::WASTED_DESCRIPTOR_ARRAY_DETAILS_TYPE, wasted_details_space,
      ObjectStats::kNoOverAllocation);
}
References v8::internal::IsAny(), v8::internal::kField, v8::internal::ObjectStats::kNoOverAllocation, v8::internal::kTaggedSize, v8::internal::PropertyDetails::location(), v8::internal::ObjectStats::RecordVirtualObjectStats(), and stats_.
Referenced by CollectStatistics(), and RecordVirtualMapDetails().
RecordSimpleVirtualObjectStats()
bool v8::internal::ObjectStatsCollectorImpl::RecordSimpleVirtualObjectStats (Tagged< HeapObject > parent, Tagged< HeapObject > obj, ObjectStats::VirtualInstanceType type) [private]
Definition at line 515 of file object-stats.cc.
                                         {
  return RecordVirtualObjectStats(parent, obj, type, obj->Size(cage_base()),
                                  ObjectStats::kNoOverAllocation, kCheckCow);
}
References cage_base(), kCheckCow, v8::internal::ObjectStats::kNoOverAllocation, RecordVirtualObjectStats(), and v8::internal::tracing::type.
Referenced by CollectGlobalStatistics(), RecordVirtualAllocationSiteDetails(), RecordVirtualBytecodeArrayDetails(), RecordVirtualCodeDetails(), RecordVirtualContext(), RecordVirtualFeedbackVectorDetails(), RecordVirtualFunctionTemplateInfoDetails(), RecordVirtualJSGlobalObjectDetails(), RecordVirtualJSObjectDetails(), RecordVirtualMapDetails(), RecordVirtualObjectsForConstantPoolOrEmbeddedObjects(), RecordVirtualScriptDetails(), and RecordVirtualSharedFunctionInfoDetails().
RecordVirtualAllocationSiteDetails()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualAllocationSiteDetails (Tagged< AllocationSite > site) [private]
Definition at line 578 of file object-stats.cc.
                                 {
  if (!site->PointsToLiteral()) return;
  Tagged<JSObject> boilerplate = site->boilerplate();
  if (IsJSArray(boilerplate)) {
    RecordSimpleVirtualObjectStats(site, boilerplate,
                                   StatsEnum::JS_ARRAY_BOILERPLATE_TYPE);
    // Array boilerplates cannot have properties.
  } else {
    RecordVirtualObjectStats(
        site, boilerplate, StatsEnum::JS_OBJECT_BOILERPLATE_TYPE,
        boilerplate->Size(), ObjectStats::kNoOverAllocation);
    if (boilerplate->HasFastProperties()) {
      // We'll mis-classify the empty_property_array here. Given that there is a
      // single instance, this is negligible.
      Tagged<PropertyArray> properties = boilerplate->property_array();
      RecordSimpleVirtualObjectStats(
          site, properties, StatsEnum::BOILERPLATE_PROPERTY_ARRAY_TYPE);
    } else {
      Tagged<NameDictionary> properties = boilerplate->property_dictionary();
      RecordSimpleVirtualObjectStats(
          site, properties, StatsEnum::BOILERPLATE_PROPERTY_DICTIONARY_TYPE);
    }
  }
  Tagged<FixedArrayBase> elements = boilerplate->elements();
  RecordSimpleVirtualObjectStats(site, elements,
                                 StatsEnum::BOILERPLATE_ELEMENTS_TYPE);
}
References v8::internal::ObjectStats::kNoOverAllocation, RecordSimpleVirtualObjectStats(), and RecordVirtualObjectStats().
Referenced by CollectGlobalStatistics().
RecordVirtualArrayBoilerplateDescription()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualArrayBoilerplateDescription (Tagged< ArrayBoilerplateDescription > description) [private]
Definition at line 1042 of file object-stats.cc.
                                                     {
  RecordVirtualObjectsForConstantPoolOrEmbeddedObjects(
      description, description->constant_elements(),
      StatsEnum::ARRAY_BOILERPLATE_DESCRIPTION_ELEMENTS_TYPE);
}
References RecordVirtualObjectsForConstantPoolOrEmbeddedObjects().
Referenced by CollectStatistics().
RecordVirtualBytecodeArrayDetails()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualBytecodeArrayDetails (Tagged< BytecodeArray > bytecode) [private]
Definition at line 1065 of file object-stats.cc.
                                    {
  RecordSimpleVirtualObjectStats(bytecode, bytecode->constant_pool(),
                                 StatsEnum::BYTECODE_ARRAY_CONSTANT_POOL_TYPE);
  // FixedArrays on constant pool are used for holding descriptor information.
  // They are shared with optimized code.
  Tagged<TrustedFixedArray> constant_pool =
      Cast<TrustedFixedArray>(bytecode->constant_pool());
  for (int i = 0; i < constant_pool->length(); i++) {
    Tagged<Object> entry = constant_pool->get(i);
    if (IsFixedArrayExact(entry)) {
      RecordVirtualObjectsForConstantPoolOrEmbeddedObjects(
          constant_pool, Cast<HeapObject>(entry),
          StatsEnum::EMBEDDED_OBJECT_TYPE);
    }
  }
  RecordSimpleVirtualObjectStats(bytecode, bytecode->handler_table(),
                                 StatsEnum::BYTECODE_ARRAY_HANDLER_TABLE_TYPE);
  if (bytecode->HasSourcePositionTable()) {
    RecordSimpleVirtualObjectStats(bytecode, bytecode->SourcePositionTable(),
                                   StatsEnum::SOURCE_POSITION_TABLE_TYPE);
  }
}
References v8::internal::constant_pool, RecordSimpleVirtualObjectStats(), and RecordVirtualObjectsForConstantPoolOrEmbeddedObjects().
Referenced by CollectStatistics().
RecordVirtualCodeDetails()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualCodeDetails (Tagged< InstructionStream > code) [private]
Definition at line 1104 of file object-stats.cc.
                                       {
  Tagged<Code> code;
  if (!istream->TryGetCode(&code, kAcquireLoad)) return;
  RecordSimpleVirtualObjectStats(HeapObject(), istream,
                                 CodeKindToVirtualInstanceType(code->kind()));
  RecordSimpleVirtualObjectStats(istream, istream->relocation_info(),
                                 StatsEnum::RELOC_INFO_TYPE);
  if (CodeKindIsOptimizedJSFunction(code->kind())) {
    Tagged<Object> source_position_table = code->source_position_table();
    if (IsHeapObject(source_position_table)) {
      RecordSimpleVirtualObjectStats(istream,
                                     Cast<HeapObject>(source_position_table),
                                     StatsEnum::SOURCE_POSITION_TABLE_TYPE);
    }
    RecordSimpleVirtualObjectStats(istream, code->deoptimization_data(),
                                   StatsEnum::DEOPTIMIZATION_DATA_TYPE);
    Tagged<DeoptimizationData> input_data =
        Cast<DeoptimizationData>(code->deoptimization_data());
    if (input_data->length() > 0) {
      RecordSimpleVirtualObjectStats(code->deoptimization_data(),
                                     input_data->LiteralArray(),
                                     StatsEnum::OPTIMIZED_CODE_LITERALS_TYPE);
    }
  }
  int const mode_mask = RelocInfo::EmbeddedObjectModeMask();
  for (RelocIterator it(code, mode_mask); !it.done(); it.next()) {
    DCHECK(RelocInfo::IsEmbeddedObjectMode(it.rinfo()->rmode()));
    Tagged<Object> target = it.rinfo()->target_object(cage_base());
    if (IsFixedArrayExact(target, cage_base())) {
      RecordVirtualObjectsForConstantPoolOrEmbeddedObjects(
          istream, Cast<HeapObject>(target), StatsEnum::EMBEDDED_OBJECT_TYPE);
    }
  }
}
References cage_base(), code, v8::internal::CodeKindIsOptimizedJSFunction(), v8::internal::anonymous_namespace{object-stats.cc}::CodeKindToVirtualInstanceType(), v8::internal::DCHECK(), v8::internal::RelocIteratorBase< RelocInfoT >::done(), v8::internal::RelocInfo::EmbeddedObjectModeMask(), v8::internal::RelocInfo::IsEmbeddedObjectMode(), v8::internal::IsHeapObject(), v8::kAcquireLoad, RecordSimpleVirtualObjectStats(), and RecordVirtualObjectsForConstantPoolOrEmbeddedObjects().
Referenced by CollectStatistics().
RecordVirtualContext()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualContext (Tagged< Context > context) [private]
Definition at line 1140 of file object-stats.cc.
                                                                           {
  if (IsNativeContext(context)) {
    RecordObjectStats(context, NATIVE_CONTEXT_TYPE, context->Size());
    if (IsWeakArrayList(context->retained_maps(), cage_base())) {
      RecordSimpleVirtualObjectStats(
          context, Cast<WeakArrayList>(context->retained_maps()),
          StatsEnum::RETAINED_MAPS_TYPE);
    }
  } else if (context->IsFunctionContext()) {
    RecordObjectStats(context, FUNCTION_CONTEXT_TYPE, context->Size());
  } else {
    RecordSimpleVirtualObjectStats(HeapObject(), context,
                                   StatsEnum::OTHER_CONTEXT_TYPE);
  }
}
References cage_base(), RecordObjectStats(), and RecordSimpleVirtualObjectStats().
Referenced by CollectStatistics().
RecordVirtualExternalStringDetails()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualExternalStringDetails (Tagged< ExternalString > script) [private]
Definition at line 1019 of file object-stats.cc.
                                   {
  // Track the external string resource size in a separate category.
  Address resource = string->resource_as_address();
  size_t off_heap_size = string->ExternalPayloadSize();
  RecordExternalResourceStats(
      resource,
      string->IsOneByteRepresentation()
          ? StatsEnum::STRING_EXTERNAL_RESOURCE_ONE_BYTE_TYPE
          : StatsEnum::STRING_EXTERNAL_RESOURCE_TWO_BYTE_TYPE,
      off_heap_size);
}
References RecordExternalResourceStats(), and v8::internal::string.
Referenced by CollectStatistics().
RecordVirtualFeedbackVectorDetails()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualFeedbackVectorDetails (Tagged< FeedbackVector > vector) [private]
Definition at line 738 of file object-stats.cc.
                                   {
  if (virtual_objects_.find(vector) != virtual_objects_.end()) return;
  // Manually insert the feedback vector into the virtual object list, since
  // we're logging its component parts separately.
  virtual_objects_.insert(vector);
  size_t calculated_size = 0;
  // Log the feedback vector's header (fixed fields).
  size_t header_size = vector->slots_start().address() - vector.address();
  stats_->RecordVirtualObjectStats(StatsEnum::FEEDBACK_VECTOR_HEADER_TYPE,
                                   header_size, ObjectStats::kNoOverAllocation);
  calculated_size += header_size;
  // Iterate over the feedback slots and log each one.
  if (!vector->shared_function_info()->HasFeedbackMetadata()) return;
  FeedbackMetadataIterator it(vector->metadata());
  while (it.HasNext()) {
    FeedbackSlot slot = it.Next();
    // Log the entry (or entries) taken up by this slot.
    size_t slot_size = it.entry_size() * kTaggedSize;
    stats_->RecordVirtualObjectStats(
        GetFeedbackSlotType(vector->Get(slot), it.kind(), heap_->isolate()),
        slot_size, ObjectStats::kNoOverAllocation);
    calculated_size += slot_size;
    // Log the monomorphic/polymorphic helper objects that this slot owns.
    for (int i = 0; i < it.entry_size(); i++) {
      Tagged<MaybeObject> raw_object = vector->Get(slot.WithOffset(i));
      Tagged<HeapObject> object;
      if (raw_object.GetHeapObject(&object)) {
        if (IsCell(object, cage_base()) ||
            IsWeakFixedArray(object, cage_base())) {
          RecordSimpleVirtualObjectStats(vector, object,
                                         StatsEnum::FEEDBACK_VECTOR_ENTRY_TYPE);
        }
      }
    }
  }
  CHECK_EQ(calculated_size, vector->Size());
}
References v8::internal::Tagged< HeapObject >::address(), cage_base(), CHECK_EQ, v8::internal::FeedbackMetadataIterator::entry_size(), v8::internal::GetFeedbackSlotType(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::FeedbackMetadataIterator::HasNext(), heap_, v8::internal::Heap::isolate(), v8::internal::FeedbackMetadataIterator::kind(), v8::internal::ObjectStats::kNoOverAllocation, v8::internal::kTaggedSize, v8::internal::FeedbackMetadataIterator::Next(), RecordSimpleVirtualObjectStats(), v8::internal::ObjectStats::RecordVirtualObjectStats(), stats_, virtual_objects_, and v8::internal::FeedbackSlot::WithOffset().
Referenced by CollectStatistics().
RecordVirtualFixedArrayDetails()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualFixedArrayDetails (Tagged< FixedArray > array) [private]
Definition at line 783 of file object-stats.cc.
                              {
  if (IsCowArray(array)) {
    RecordVirtualObjectStats(HeapObject(), array, StatsEnum::COW_ARRAY_TYPE,
                             array->Size(), ObjectStats::kNoOverAllocation,
                             kIgnoreCow);
  }
}
References IsCowArray(), kIgnoreCow, v8::internal::ObjectStats::kNoOverAllocation, and RecordVirtualObjectStats().
Referenced by CollectStatistics().
RecordVirtualFunctionTemplateInfoDetails()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualFunctionTemplateInfoDetails (Tagged< FunctionTemplateInfo > fti) [private]
Definition at line 607 of file object-stats.cc.
                                      {
  // named_property_handler and indexed_property_handler are recorded as
  // INTERCEPTOR_INFO_TYPE.
  if (!IsUndefined(fti->GetInstanceCallHandler(), isolate())) {
    RecordSimpleVirtualObjectStats(
        fti, Cast<FunctionTemplateInfo>(fti->GetInstanceCallHandler()),
        StatsEnum::FUNCTION_TEMPLATE_INFO_ENTRIES_TYPE);
  }
}
References isolate(), and RecordSimpleVirtualObjectStats().
Referenced by CollectStatistics().
RecordVirtualJSGlobalObjectDetails()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualJSGlobalObjectDetails (Tagged< JSGlobalObject > object) [private]
Definition at line 618 of file object-stats.cc.
                                   {
  // Properties.
  Tagged<GlobalDictionary> properties = object->global_dictionary(kAcquireLoad);
  RecordHashTableVirtualObjectStats(object, properties,
                                    StatsEnum::GLOBAL_PROPERTIES_TYPE);
  // Elements.
  Tagged<FixedArrayBase> elements = object->elements();
  RecordSimpleVirtualObjectStats(object, elements,
                                 StatsEnum::GLOBAL_ELEMENTS_TYPE);
}
References v8::kAcquireLoad, RecordHashTableVirtualObjectStats(), and RecordSimpleVirtualObjectStats().
Referenced by CollectStatistics().
RecordVirtualJSObjectDetails()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualJSObjectDetails (Tagged< JSObject > object) [private]
Definition at line 630 of file object-stats.cc.
                             {
  // JSGlobalObject is recorded separately.
  if (IsJSGlobalObject(object)) return;
  // Uncompiled JSFunction has a separate type.
  if (IsJSFunction(object) &&
      !Cast<JSFunction>(object)->is_compiled(isolate())) {
    RecordSimpleVirtualObjectStats(HeapObject(), object,
                                   StatsEnum::JS_UNCOMPILED_FUNCTION_TYPE);
  }
  // Properties.
  if (object->HasFastProperties()) {
    Tagged<PropertyArray> properties = object->property_array();
    if (properties != ReadOnlyRoots(heap_).empty_property_array()) {
      size_t over_allocated =
          object->map()->UnusedPropertyFields() * kTaggedSize;
      RecordVirtualObjectStats(object, properties,
                               object->map()->is_prototype_map()
                                   ? StatsEnum::PROTOTYPE_PROPERTY_ARRAY_TYPE
                                   : StatsEnum::OBJECT_PROPERTY_ARRAY_TYPE,
                               properties->Size(), over_allocated);
    }
  } else {
    Tagged<NameDictionary> properties = object->property_dictionary();
    RecordHashTableVirtualObjectStats(
        object, properties,
        object->map()->is_prototype_map()
            ? StatsEnum::PROTOTYPE_PROPERTY_DICTIONARY_TYPE
            : StatsEnum::OBJECT_PROPERTY_DICTIONARY_TYPE);
  }
  // Elements.
  Tagged<FixedArrayBase> elements = object->elements();
  if (object->HasDictionaryElements()) {
    RecordHashTableVirtualObjectStats(
        object, Cast<NumberDictionary>(elements),
        IsJSArray(object) ? StatsEnum::ARRAY_DICTIONARY_ELEMENTS_TYPE
                          : StatsEnum::OBJECT_DICTIONARY_ELEMENTS_TYPE);
  } else if (IsJSArray(object)) {
    if (elements != ReadOnlyRoots(heap_).empty_fixed_array()) {
      size_t element_size =
          (elements->Size() - FixedArrayBase::kHeaderSize) / elements->length();
      uint32_t length = Object::NumberValue(Cast<JSArray>(object)->length());
      size_t over_allocated = (elements->length() - length) * element_size;
      RecordVirtualObjectStats(object, elements, StatsEnum::ARRAY_ELEMENTS_TYPE,
                               elements->Size(), over_allocated);
    }
  } else {
    RecordSimpleVirtualObjectStats(object, elements,
                                   StatsEnum::OBJECT_ELEMENTS_TYPE);
  }
  // JSCollections.
  if (IsJSCollection(object)) {
    Tagged<Object> maybe_table = Cast<JSCollection>(object)->table();
    if (!IsUndefined(maybe_table, isolate())) {
      DCHECK(IsFixedArray(maybe_table, isolate()));
      // TODO(bmeurer): Properly compute over-allocation here.
      RecordSimpleVirtualObjectStats(object, Cast<HeapObject>(maybe_table),
                                     StatsEnum::JS_COLLECTION_TABLE_TYPE);
    }
  }
}
References v8::internal::Cast< NumberDictionary >(), v8::internal::DCHECK(), heap_, isolate(), v8::internal::FixedArrayBase::kHeaderSize, v8::internal::kTaggedSize, v8::internal::length, v8::internal::Object::NumberValue(), RecordHashTableVirtualObjectStats(), RecordSimpleVirtualObjectStats(), and RecordVirtualObjectStats().
Referenced by CollectStatistics().
RecordVirtualMapDetails()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualMapDetails (Tagged< Map > map) [private]
Definition at line 917 of file object-stats.cc.
                                                                      {
  // TODO(mlippautz): map->dependent_code(): DEPENDENT_CODE_TYPE.
  // For Map we want to distinguish between various different states
  // to get a better picture of what's going on in MapSpace. This
  // method computes the virtual instance type to use for a given map,
  // using MAP_TYPE for regular maps that aren't special in any way.
  if (map->is_prototype_map()) {
    if (map->is_dictionary_map()) {
      RecordSimpleVirtualObjectStats(HeapObject(), map,
                                     StatsEnum::MAP_PROTOTYPE_DICTIONARY_TYPE);
    } else if (map->is_abandoned_prototype_map()) {
      RecordSimpleVirtualObjectStats(HeapObject(), map,
                                     StatsEnum::MAP_ABANDONED_PROTOTYPE_TYPE);
    } else {
      RecordSimpleVirtualObjectStats(HeapObject(), map,
                                     StatsEnum::MAP_PROTOTYPE_TYPE);
    }
  } else if (map->is_deprecated()) {
    RecordSimpleVirtualObjectStats(HeapObject(), map,
                                   StatsEnum::MAP_DEPRECATED_TYPE);
  } else if (map->is_dictionary_map()) {
    RecordSimpleVirtualObjectStats(HeapObject(), map,
                                   StatsEnum::MAP_DICTIONARY_TYPE);
  } else if (map->is_stable()) {
    RecordSimpleVirtualObjectStats(HeapObject(), map,
                                   StatsEnum::MAP_STABLE_TYPE);
  } else {
    // This will be logged as MAP_TYPE in Phase2.
  }
  Tagged<DescriptorArray> array = map->instance_descriptors(cage_base());
  if (map->owns_descriptors() &&
      array != ReadOnlyRoots(heap_).empty_descriptor_array()) {
    // Generally DescriptorArrays have their own instance type already
    // (DESCRIPTOR_ARRAY_TYPE), but we'd like to be able to tell which
    // of those are for (abandoned) prototypes, and which of those are
    // owned by deprecated maps.
    bool recorded = false;
    if (map->is_prototype_map()) {
      recorded = RecordSimpleVirtualObjectStats(
          map, array, StatsEnum::PROTOTYPE_DESCRIPTOR_ARRAY_TYPE);
    } else if (map->is_deprecated()) {
      recorded = RecordSimpleVirtualObjectStats(
          map, array, StatsEnum::DEPRECATED_DESCRIPTOR_ARRAY_TYPE);
    }
    if (recorded) {
      // This DescriptorArray has just been recorded, append stats about
      // potentially wasted memory in the object.
      RecordPotentialDescriptorArraySavingsStats(array);
    }
    Tagged<EnumCache> enum_cache = array->enum_cache();
    RecordSimpleVirtualObjectStats(array, enum_cache->keys(),
                                   StatsEnum::ENUM_KEYS_CACHE_TYPE);
    RecordSimpleVirtualObjectStats(array, enum_cache->indices(),
                                   StatsEnum::ENUM_INDICES_CACHE_TYPE);
  }
  if (map->is_prototype_map()) {
    Tagged<PrototypeInfo> prototype_info;
    if (map->TryGetPrototypeInfo(&prototype_info)) {
      Tagged<Object> users = prototype_info->prototype_users();
      if (IsWeakFixedArray(users, cage_base())) {
        RecordSimpleVirtualObjectStats(map, Cast<WeakArrayList>(users),
                                       StatsEnum::PROTOTYPE_USERS_TYPE);
      }
    }
  }
}
References cage_base(), heap_, RecordPotentialDescriptorArraySavingsStats(), and RecordSimpleVirtualObjectStats().
Referenced by CollectStatistics().
RecordVirtualObjectsForConstantPoolOrEmbeddedObjects()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualObjectsForConstantPoolOrEmbeddedObjects (Tagged< HeapObject > parent, Tagged< HeapObject > object, ObjectStats::VirtualInstanceType type) [private]
Definition at line 1049 of file object-stats.cc.
                                             {
  if (!RecordSimpleVirtualObjectStats(parent, object, type)) return;
  if (IsFixedArrayExact(object, cage_base())) {
    Tagged<FixedArray> array = Cast<FixedArray>(object);
    for (int i = 0; i < array->length(); i++) {
      Tagged<Object> entry = array->get(i);
      if (!IsHeapObject(entry)) continue;
      RecordVirtualObjectsForConstantPoolOrEmbeddedObjects(
          array, Cast<HeapObject>(entry), type);
    }
  }
}
References cage_base(), v8::internal::IsHeapObject(), RecordSimpleVirtualObjectStats(), and v8::internal::tracing::type.
Referenced by RecordVirtualArrayBoilerplateDescription(), RecordVirtualBytecodeArrayDetails(), and RecordVirtualCodeDetails().
RecordVirtualObjectStats()
bool v8::internal::ObjectStatsCollectorImpl::RecordVirtualObjectStats (Tagged< HeapObject > parent, Tagged< HeapObject > obj, ObjectStats::VirtualInstanceType type, size_t size, size_t over_allocated, CowMode check_cow_array = kCheckCow) [private]
Definition at line 553 of file object-stats.cc.
                             {
  CHECK_LT(over_allocated, size);
  if (!SameLiveness(parent, obj) || !ShouldRecordObject(obj, check_cow_array)) {
    return false;
  }
  if (virtual_objects_.find(obj) == virtual_objects_.end()) {
    virtual_objects_.insert(obj);
    stats_->RecordVirtualObjectStats(type, size, over_allocated);
    return true;
  }
  return false;
}
References CHECK_LT, v8::internal::ObjectStats::RecordVirtualObjectStats(), SameLiveness(), ShouldRecordObject(), size(), stats_, v8::internal::tracing::type, and virtual_objects_.
Referenced by RecordHashTableVirtualObjectStats(), RecordSimpleVirtualObjectStats(), RecordVirtualAllocationSiteDetails(), RecordVirtualFixedArrayDetails(), and RecordVirtualJSObjectDetails().
RecordVirtualScriptDetails()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualScriptDetails (Tagged< Script > script) [private]
Definition at line 989 of file object-stats.cc.
                           {
  RecordSimpleVirtualObjectStats(script, script->infos(),
                                 StatsEnum::SCRIPT_INFOS_TYPE);
  // Log the size of external source code.
  Tagged<Object> raw_source = script->source();
  if (IsExternalString(raw_source, cage_base())) {
    // The contents of external strings aren't on the heap, so we have to record
    // them manually. The on-heap String object is recorded independently in
    // the normal pass.
    Tagged<ExternalString> string = Cast<ExternalString>(raw_source);
    Address resource = string->resource_as_address();
    size_t off_heap_size = string->ExternalPayloadSize();
    RecordExternalResourceStats(
        resource,
        string->IsOneByteRepresentation()
            ? StatsEnum::SCRIPT_SOURCE_EXTERNAL_ONE_BYTE_TYPE
            : StatsEnum::SCRIPT_SOURCE_EXTERNAL_TWO_BYTE_TYPE,
        off_heap_size);
  } else if (IsString(raw_source, cage_base())) {
    Tagged<String> source = Cast<String>(raw_source);
    RecordSimpleVirtualObjectStats(
        script, source,
        source->IsOneByteRepresentation()
            ? StatsEnum::SCRIPT_SOURCE_NON_EXTERNAL_ONE_BYTE_TYPE
            : StatsEnum::SCRIPT_SOURCE_NON_EXTERNAL_TWO_BYTE_TYPE);
  }
}
References cage_base(), v8::internal::InstanceTypeChecker::IsExternalString(), RecordExternalResourceStats(), RecordSimpleVirtualObjectStats(), v8::internal::script, and v8::internal::string.
Referenced by CollectStatistics().
RecordVirtualSharedFunctionInfoDetails()
void v8::internal::ObjectStatsCollectorImpl::RecordVirtualSharedFunctionInfoDetails (Tagged< SharedFunctionInfo > info) [private]
Definition at line 1033 of file object-stats.cc.
                                     {
  // Uncompiled SharedFunctionInfo gets its own category.
  if (!info->is_compiled()) {
    RecordSimpleVirtualObjectStats(
        HeapObject(), info, StatsEnum::UNCOMPILED_SHARED_FUNCTION_INFO_TYPE);
  }
}
References RecordSimpleVirtualObjectStats().
Referenced by CollectStatistics().
SameLiveness()
bool v8::internal::ObjectStatsCollectorImpl::SameLiveness (Tagged< HeapObject > obj1, Tagged< HeapObject > obj2) [private]
Definition at line 907 of file object-stats.cc.
                                                                     {
  if (obj1.is_null() || obj2.is_null()) return true;
  const auto obj1_marked =
      MarkingHelper::IsMarkedOrAlwaysLive(heap_, marking_state_, obj1);
  const auto obj2_marked =
      MarkingHelper::IsMarkedOrAlwaysLive(heap_, marking_state_, obj2);
  return obj1_marked == obj2_marked;
}
References heap_, v8::internal::Tagged< HeapObject >::is_null(), v8::internal::MarkingHelper::IsMarkedOrAlwaysLive(), and marking_state_.
Referenced by RecordVirtualObjectStats().
ShouldRecordObject()
bool v8::internal::ObjectStatsCollectorImpl::ShouldRecordObject (Tagged< HeapObject > object, CowMode check_cow_array) [private]
Definition at line 492 of file object-stats.cc.
                                                                           {
  if (IsFixedArrayExact(obj)) {
    Tagged<FixedArray> fixed_array = Cast<FixedArray>(obj);
    bool cow_check = check_cow_array == kIgnoreCow || !IsCowArray(fixed_array);
    return CanRecordFixedArray(fixed_array) && cow_check;
  }
  if (obj.SafeEquals(ReadOnlyRoots(heap_).empty_property_array())) return false;
  return true;
}
References CanRecordFixedArray(), heap_, IsCowArray(), kIgnoreCow, and v8::internal::TaggedImpl< kRefType, StorageType >::SafeEquals().
Referenced by RecordVirtualObjectStats().
Member Data Documentation
external_resources_
std::unordered_set<Address> v8::internal::ObjectStatsCollectorImpl::external_resources_ [private]
Definition at line 477 of file object-stats.cc.
Referenced by RecordExternalResourceStats().
field_stats_collector_
FieldStatsCollector v8::internal::ObjectStatsCollectorImpl::field_stats_collector_ [private]
Definition at line 478 of file object-stats.cc.
Referenced by cage_base(), and CollectStatistics().
heap_
Heap* const v8::internal::ObjectStatsCollectorImpl::heap_ [private]
Definition at line 472 of file object-stats.cc.
Referenced by CanRecordFixedArray(), CollectGlobalStatistics(), IsCowArray(), isolate(), RecordVirtualFeedbackVectorDetails(), RecordVirtualJSObjectDetails(), RecordVirtualMapDetails(), SameLiveness(), and ShouldRecordObject().
kNumberOfPhases
const int v8::internal::ObjectStatsCollectorImpl::kNumberOfPhases = kPhase2 + 1 [static]
Definition at line 390 of file object-stats.cc.
Referenced by v8::internal::ObjectStatsCollector::Collect().
marking_state_
NonAtomicMarkingState* const v8::internal::ObjectStatsCollectorImpl::marking_state_ [private]
Definition at line 474 of file object-stats.cc.
Referenced by SameLiveness().
stats_
ObjectStats* const v8::internal::ObjectStatsCollectorImpl::stats_ [private]
Definition at line 473 of file object-stats.cc.
Referenced by RecordExternalResourceStats(), RecordObjectStats(), RecordPotentialDescriptorArraySavingsStats(), RecordVirtualFeedbackVectorDetails(), and RecordVirtualObjectStats().
virtual_objects_
std::unordered_set<Tagged<HeapObject>, Object::Hasher, Object::KeyEqualSafe> v8::internal::ObjectStatsCollectorImpl::virtual_objects_ [private]
Definition at line 476 of file object-stats.cc.
Referenced by RecordObjectStats(), RecordVirtualFeedbackVectorDetails(), and RecordVirtualObjectStats().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/object-stats.cc