v8_inspector::V8StackTraceImpl::StackFrameIterator Class Reference
Public Member Functions
StackFrameIterator (const V8StackTraceImpl *stackTrace)
void next ()
StackFrame * frame ()
bool done ()
Private Attributes
std::vector< std::shared_ptr< StackFrame > >::const_iterator m_currentIt
std::vector< std::shared_ptr< StackFrame > >::const_iterator m_currentEnd
AsyncStackTrace * m_parent
Detailed Description
Definition at line 95 of file v8-stack-trace-impl.h.
Constructor & Destructor Documentation
StackFrameIterator()
v8_inspector::V8StackTraceImpl::StackFrameIterator::StackFrameIterator (const V8StackTraceImpl * stackTrace) [explicit]
Definition at line 374 of file v8-stack-trace-impl.cc.
    : m_currentIt(stackTrace->m_frames.begin()),
      m_currentEnd(stackTrace->m_frames.end()),
      m_parent(stackTrace->m_asyncParent.lock().get()) {}
Member Function Documentation
done()
bool v8_inspector::V8StackTraceImpl::StackFrameIterator::done ()
Definition at line 391 of file v8-stack-trace-impl.cc.
                                              {
  return m_currentIt == m_currentEnd;
}
Referenced by v8_inspector::V8StackTraceImpl::firstNonEmptySourceURL(), and v8_inspector::V8StackTraceImpl::isEqualIgnoringTopFrame().
frame()
StackFrame * v8_inspector::V8StackTraceImpl::StackFrameIterator::frame ()
Definition at line 395 of file v8-stack-trace-impl.cc.
                                                      {
  return m_currentIt->get();
}
Referenced by v8_inspector::V8StackTraceImpl::firstNonEmptySourceURL(), and v8_inspector::V8StackTraceImpl::isEqualIgnoringTopFrame().
next()
void v8_inspector::V8StackTraceImpl::StackFrameIterator::next ()
Definition at line 380 of file v8-stack-trace-impl.cc.
                                              {
  if (m_currentIt == m_currentEnd) return;
  ++m_currentIt;
  while (m_currentIt == m_currentEnd && m_parent) {
    const std::vector<std::shared_ptr<StackFrame>>& frames = m_parent->frames();
    m_currentIt = frames.begin();
    m_currentEnd = frames.end();
    m_parent = m_parent->parent().lock().get();
  }
}
References v8_inspector::V8StackTraceImpl::frames().
Referenced by v8_inspector::V8StackTraceImpl::firstNonEmptySourceURL(), and v8_inspector::V8StackTraceImpl::isEqualIgnoringTopFrame().
Member Data Documentation
m_currentEnd
std::vector<std::shared_ptr<StackFrame> >::const_iterator v8_inspector::V8StackTraceImpl::StackFrameIterator::m_currentEnd [private]
Definition at line 105 of file v8-stack-trace-impl.h.
m_currentIt
std::vector<std::shared_ptr<StackFrame> >::const_iterator v8_inspector::V8StackTraceImpl::StackFrameIterator::m_currentIt [private]
Definition at line 104 of file v8-stack-trace-impl.h.
m_parent
AsyncStackTrace* v8_inspector::V8StackTraceImpl::StackFrameIterator::m_parent [private]
Definition at line 106 of file v8-stack-trace-impl.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/v8-stack-trace-impl.h
/mnt/V8SourceCode/src/inspector/v8-stack-trace-impl.cc