v8::internal::LoadDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_PARAMETER_TYPES (MachineType::AnyTagged(), MachineType::AnyTagged(), MachineType::TaggedSigned()) static const expr inline Register ReceiverRegister()
Static Public Member Functions
static constexpr Register NameRegister ()
static constexpr Register SlotRegister ()
static constexpr auto registers ()
Additional Inherited Members
Detailed Description
Definition at line 990 of file interface-descriptors.h.
Member Function Documentation
DEFINE_PARAMETER_TYPES()
v8::internal::LoadDescriptor::DEFINE_PARAMETER_TYPES (MachineType::AnyTagged() , MachineType::AnyTagged() , MachineType::TaggedSigned()) const
NameRegister()
constexpr Register v8::internal::LoadDescriptor::NameRegister () [inline], [static], [constexpr]
Definition at line 64 of file interface-descriptors-riscv-inl.h.
{ return a2; }
Referenced by registers(), v8::internal::LoadGlobalNoFeedbackDescriptor::registers(), v8::internal::LoadNoFeedbackDescriptor::registers(), v8::internal::LoadWithVectorDescriptor::registers(), and v8::internal::LoadWithReceiverAndVectorDescriptor::registers().
registers()
constexpr auto v8::internal::LoadDescriptor::registers () [static], [constexpr]
Definition at line 394 of file interface-descriptors-inl.h.
                                         {
  return RegisterArray(ReceiverRegister(), NameRegister(), SlotRegister());
}
References NameRegister(), v8::internal::RegisterArray(), and SlotRegister().
SlotRegister()
constexpr Register v8::internal::LoadDescriptor::SlotRegister () [inline], [static], [constexpr]
Definition at line 66 of file interface-descriptors-riscv-inl.h.
{ return a0; }
Referenced by registers(), v8::internal::LoadWithVectorDescriptor::registers(), and v8::internal::LoadWithReceiverAndVectorDescriptor::registers().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h
/mnt/V8SourceCode/src/codegen/riscv/interface-descriptors-riscv-inl.h