v8::internal::PreparseDataBuilder::ByteData Class Reference
#include <preparse-data.h>
Public Member Functions
ByteData ()
void Start (std::vector< uint8_t > *buffer)
void Finalize (Zone *zone)
Handle< PreparseData > CopyToHeap (Isolate *isolate, int children_length)
Handle< PreparseData > CopyToLocalHeap (LocalIsolate *isolate, int children_length)
ZonePreparseData * CopyToZone (Zone *zone, int children_length)
void Reserve (size_t bytes)
void Add (uint8_t byte)
int length () const
void WriteVarint32 (uint32_t data)
void WriteUint8 (uint8_t data)
void WriteQuarter (uint8_t data)
Private Attributes
xx xx xx xx xx xx xx xx xx
union {
 struct {
  std::vector< uint8_t > * byte_data_
  int index_
 }
 base::Vector< uint8_t > zone_byte_data_
};
uint8_t free_quarters_in_last_byte_
Additional Inherited Members
Detailed Description
Definition at line 134 of file preparse-data.h.
Constructor & Destructor Documentation
ByteData()
v8::internal::PreparseDataBuilder::ByteData::ByteData () [inline]
Definition at line 137 of file preparse-data.h.
        : byte_data_(nullptr), index_(0), free_quarters_in_last_byte_(0) {}
Member Function Documentation
Add()
void v8::internal::PreparseDataBuilder::ByteData::Add (uint8_t byte)
Definition at line 157 of file preparse-data.cc.
                                                  {
  DCHECK_LE(0, index_);
  DCHECK_LT(index_, byte_data_->size());
  (*byte_data_)[index_++] = byte;
}
References v8::internal::PreparseDataBuilder::byte_data_, DCHECK_LE, and DCHECK_LT.
CopyToHeap()
Handle< PreparseData > v8::internal::PreparseDataBuilder::ByteData::CopyToHeap (Isolate * isolate, int children_length)
Definition at line 431 of file preparse-data.cc.
                                           {
  DCHECK(is_finalized_);
  int data_length = zone_byte_data_.length();
  Handle<PreparseData> data =
      isolate->factory()->NewPreparseData(data_length, children_length);
  data->copy_in(0, zone_byte_data_.begin(), data_length);
  return data;
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), and v8::internal::FactoryBase< Impl >::NewPreparseData().
Referenced by v8::internal::PreparseDataBuilder::Serialize().
CopyToLocalHeap()
Handle< PreparseData > v8::internal::PreparseDataBuilder::ByteData::CopyToLocalHeap (LocalIsolate * isolate, int children_length)
Definition at line 441 of file preparse-data.cc.
                                                {
  DCHECK(is_finalized_);
  int data_length = zone_byte_data_.length();
  Handle<PreparseData> data =
      isolate->factory()->NewPreparseData(data_length, children_length);
  data->copy_in(0, zone_byte_data_.begin(), data_length);
  return data;
}
References v8::internal::DCHECK(), v8::internal::LocalIsolate::factory(), and v8::internal::FactoryBase< Impl >::NewPreparseData().
Referenced by v8::internal::PreparseDataBuilder::Serialize().
CopyToZone()
ZonePreparseData * v8::internal::PreparseDataBuilder::ByteData::CopyToZone (Zone * zone, int children_length) [inline]
Definition at line 234 of file preparse-data-impl.h.
                                     {
  DCHECK(is_finalized_);
  return zone->New<ZonePreparseData>(zone, &zone_byte_data_, children_length);
}
References v8::internal::DCHECK(), v8::internal::Zone::New(), and zone_byte_data_.
Referenced by v8::internal::PreparseDataBuilder::Serialize().
Finalize()
void v8::internal::PreparseDataBuilder::ByteData::Finalize (Zone * zone)
Definition at line 135 of file preparse-data.cc.
                                                     {
  uint8_t* raw_zone_data =
      zone->AllocateArray<uint8_t, RawPreparseData>(index_);
  memcpy(raw_zone_data, byte_data_->data(), index_);
  byte_data_->resize(0);
  zone_byte_data_ = base::Vector<uint8_t>(raw_zone_data, index_);
#ifdef DEBUG
  is_finalized_ = true;
#endif
}
References v8::internal::Zone::AllocateArray(), and v8::internal::PreparseDataBuilder::byte_data_.
Referenced by v8::internal::PreparseDataBuilder::SaveScopeAllocationData().
length()
int v8::internal::PreparseDataBuilder::ByteData::length () const
Definition at line 155 of file preparse-data.cc.
{ return index_; }
Referenced by v8::internal::PreparseDataBuilder::SaveScopeAllocationData().
Reserve()
void v8::internal::PreparseDataBuilder::ByteData::Reserve (size_t bytes)
Definition at line 146 of file preparse-data.cc.
                                                      {
  // Make sure we have at least {bytes} capacity left in the buffer_.
  DCHECK_LE(length(), byte_data_->size());
  size_t capacity = byte_data_->size() - length();
  if (capacity >= bytes) return;
  size_t delta = bytes - capacity;
  byte_data_->insert(byte_data_->end(), delta, 0);
}
References v8::internal::PreparseDataBuilder::byte_data_, DCHECK_LE, and v8::internal::length.
Referenced by v8::internal::PreparseDataBuilder::SaveDataForScope(), v8::internal::PreparseDataBuilder::SaveDataForVariable(), and v8::internal::PreparseDataBuilder::SaveScopeAllocationData().
Start()
void v8::internal::PreparseDataBuilder::ByteData::Start (std::vector< uint8_t > * buffer)
Definition at line 125 of file preparse-data.cc.
                                                                  {
  DCHECK(!is_finalized_);
  byte_data_ = buffer;
  DCHECK_EQ(byte_data_->size(), 0);
  DCHECK_EQ(index_, 0);
}
References v8::internal::PreparseDataBuilder::byte_data_, v8::internal::DCHECK(), and DCHECK_EQ.
Referenced by v8::internal::PreparseDataBuilder::SaveScopeAllocationData().
WriteQuarter()
void v8::internal::PreparseDataBuilder::ByteData::WriteQuarter (uint8_t data)
Definition at line 212 of file preparse-data.cc.
                                                           {
  DCHECK(!is_finalized_);
  DCHECK_LE(data, 3);
  if (free_quarters_in_last_byte_ == 0) {
#ifdef DEBUG
    // Save a marker in debug mode.
    Add(kQuarterMarker);
#endif
    Add(0);
    free_quarters_in_last_byte_ = 3;
  } else {
    --free_quarters_in_last_byte_;
  }
  uint8_t shift_amount = free_quarters_in_last_byte_ * 2;
  DCHECK_EQ(byte_data_->at(index_ - 1) & (3 << shift_amount), 0);
  (*byte_data_)[index_ - 1] |= (data << shift_amount);
}
References v8::bigint::Add(), v8::internal::PreparseDataBuilder::byte_data_, v8::internal::DCHECK(), DCHECK_EQ, and DCHECK_LE.
Referenced by v8::internal::PreparseDataBuilder::SaveDataForSkippableFunction(), and v8::internal::PreparseDataBuilder::SaveDataForVariable().
WriteUint8()
void v8::internal::PreparseDataBuilder::ByteData::WriteUint8 (uint8_t data)
Definition at line 202 of file preparse-data.cc.
                                                         {
  DCHECK(!is_finalized_);
#ifdef DEBUG
  // Save expected item size in debug mode.
  Add(kUint8Size);
#endif
  Add(data);
  free_quarters_in_last_byte_ = 0;
}
References v8::bigint::Add(), v8::internal::DCHECK(), and v8::internal::PreparseByteDataConstants::kUint8Size.
Referenced by v8::internal::PreparseDataBuilder::SaveDataForScope(), and v8::internal::PreparseDataBuilder::SaveDataForVariable().
WriteVarint32()
void v8::internal::PreparseDataBuilder::ByteData::WriteVarint32 (uint32_t data)
Definition at line 183 of file preparse-data.cc.
                                                             {
#ifdef DEBUG
  // Save expected item size in debug mode.
  Add(kVarint32MinSize);
#endif
  // See ValueSerializer::WriteVarint.
  do {
    uint8_t next_byte = (data & 0x7F);
    data >>= 7;
    // Add continue bit.
    if (data) next_byte |= 0x80;
    Add(next_byte & 0xFF);
  } while (data);
#ifdef DEBUG
  Add(kVarint32EndMarker);
#endif
  free_quarters_in_last_byte_ = 0;
}
References v8::bigint::Add(), and v8::internal::PreparseByteDataConstants::kVarint32MinSize.
Referenced by v8::internal::PreparseDataBuilder::SaveDataForSkippableFunction().
Member Data Documentation
union { ... } [private]
byte_data_
std::vector<uint8_t>* v8::internal::PreparseDataBuilder::ByteData::byte_data_
Definition at line 166 of file preparse-data.h.
free_quarters_in_last_byte_
uint8_t v8::internal::PreparseDataBuilder::ByteData::free_quarters_in_last_byte_ [private]
Definition at line 173 of file preparse-data.h.
index_
int v8::internal::PreparseDataBuilder::ByteData::index_
Definition at line 167 of file preparse-data.h.
zone_byte_data_
base::Vector<uint8_t> v8::internal::PreparseDataBuilder::ByteData::zone_byte_data_
Definition at line 171 of file preparse-data.h.
Referenced by CopyToZone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/preparse-data.h
/mnt/V8SourceCode/src/parsing/preparse-data-impl.h
/mnt/V8SourceCode/src/parsing/preparse-data.cc