v8::internal::JSSegmenter Class Reference
#include <js-segmenter.h>
Public Types
enum class Granularity { GRAPHEME
, WORD
, SENTENCE
 }
Public Member Functions
Handle< String > GranularityAsString (Isolate *isolate) const
void set_granularity (Granularity granularity)
Granularity granularity () const
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSSegmenter > New (Isolate *isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options)
static V8_WARN_UNUSED_RESULT DirectHandle< JSObject > ResolvedOptions (Isolate *isolate, DirectHandle< JSSegmenter > segmenter_holder)
static V8_EXPORT_PRIVATE const std::set< std::string > & GetAvailableLocales ()
static Handle< String > GetGranularityString (Isolate *isolate, Granularity granularity)
Detailed Description
Definition at line 34 of file js-segmenter.h.
Member Enumeration Documentation
Granularity
enum v8::internal::JSSegmenter::Granularity [strong]
Enumerator
GRAPHEME
WORD
SENTENCE
Definition at line 55 of file js-segmenter.h.
                         {
    GRAPHEME, // for character-breaks
    WORD, // for word-breaks
    SENTENCE // for sentence-breaks
  };
Member Function Documentation
GetAvailableLocales()
const std::set< std::string > & v8::internal::JSSegmenter::GetAvailableLocales () [static]
Definition at line 170 of file js-segmenter.cc.
                                                          {
  return Intl::GetAvailableLocales();
}
References v8::internal::Intl::GetAvailableLocales().
Referenced by v8::internal::BUILTIN(), and New().
GetGranularityString()
Handle< String > v8::internal::JSSegmenter::GetGranularityString (Isolate * isolate, Granularity granularity) [static]
Definition at line 156 of file js-segmenter.cc.
                                                                          {
  Factory* factory = isolate->factory();
  switch (granularity) {
    case Granularity::GRAPHEME:
      return factory->grapheme_string();
    case Granularity::WORD:
      return factory->word_string();
    case Granularity::SENTENCE:
      return factory->sentence_string();
  }
  UNREACHABLE();
}
References v8::internal::Isolate::factory(), granularity(), GRAPHEME, SENTENCE, v8::internal::UNREACHABLE(), and WORD.
Referenced by v8::internal::JSSegmentIterator::GranularityAsString(), GranularityAsString(), and v8::internal::JSSegments::GranularityAsString().
granularity()
JSSegmenter::Granularity v8::internal::JSSegmenter::granularity () const [inline]
Definition at line 38 of file js-segmenter-inl.h.
                                                             {
  return GranularityBits::decode(flags());
}
References v8::internal::flags.
Referenced by GetGranularityString(), and GranularityAsString().
GranularityAsString()
Handle< String > v8::internal::JSSegmenter::GranularityAsString (Isolate * isolate) const
Definition at line 152 of file js-segmenter.cc.
                                                                      {
  return GetGranularityString(isolate, granularity());
}
References GetGranularityString(), and granularity().
New()
MaybeDirectHandle< JSSegmenter > v8::internal::JSSegmenter::New (Isolate * isolate, DirectHandle< Map > map, DirectHandle< Object > locales, DirectHandle< Object > options) [static]
Definition at line 27 of file js-segmenter.cc.
                                        {
  // 4. Let requestedLocales be ? CanonicalizeLocaleList(locales).
  Maybe<std::vector<std::string>> maybe_requested_locales =
      Intl::CanonicalizeLocaleList(isolate, locales);
  MAYBE_RETURN(maybe_requested_locales, DirectHandle<JSSegmenter>());
  std::vector<std::string> requested_locales =
      maybe_requested_locales.FromJust();
  DirectHandle<JSReceiver> options;
  const char* service = "Intl.Segmenter";
  // 5. Let options be GetOptionsObject(_options_).
  ASSIGN_RETURN_ON_EXCEPTION(isolate, options,
                             GetOptionsObject(isolate, input_options, service));
  // 7. Let opt be a new Record.
  // 8. Let matcher be ? GetOption(options, "localeMatcher", "string",
  // « "lookup", "best fit" », "best fit").
  // 9. Set opt.[[localeMatcher]] to matcher.
  Maybe<Intl::MatcherOption> maybe_locale_matcher =
      Intl::GetLocaleMatcher(isolate, options, service);
  MAYBE_RETURN(maybe_locale_matcher, MaybeDirectHandle<JSSegmenter>());
  Intl::MatcherOption matcher = maybe_locale_matcher.FromJust();
  // 10. Let localeData be %Segmenter%.[[LocaleData]].
  // 11. Let r be ResolveLocale(%Segmenter%.[[AvailableLocales]],
  // requestedLocales, opt, %Segmenter%.[[RelevantExtensionKeys]]).
  Intl::ResolvedLocale r;
  if (!Intl::ResolveLocale(isolate, JSSegmenter::GetAvailableLocales(),
                           requested_locales, matcher, {})
           .To(&r)) {
    THROW_NEW_ERROR(isolate, NewRangeError(MessageTemplate::kIcuError));
  }
  // 12. Set segmenter.[[Locale]] to the value of r.[[locale]].
  DirectHandle<String> locale_str =
      isolate->factory()->NewStringFromAsciiChecked(r.locale.c_str());
  // 13. Let granularity be ? GetOption(options, "granularity", "string", «
  // "grapheme", "word", "sentence" », "grapheme").
  Maybe<Granularity> maybe_granularity = GetStringOption<Granularity>(
      isolate, options, "granularity", service,
      std::to_array<const std::string_view>({"grapheme", "word", "sentence"}),
      std::array{Granularity::GRAPHEME, Granularity::WORD,
                 Granularity::SENTENCE},
      Granularity::GRAPHEME);
  MAYBE_RETURN(maybe_granularity, MaybeDirectHandle<JSSegmenter>());
  Granularity granularity_enum = maybe_granularity.FromJust();
  icu::Locale icu_locale = r.icu_locale;
  DCHECK(!icu_locale.isBogus());
  UErrorCode status = U_ZERO_ERROR;
  std::unique_ptr<icu::BreakIterator> icu_break_iterator;
  switch (granularity_enum) {
    case Granularity::GRAPHEME:
      icu_break_iterator.reset(
          icu::BreakIterator::createCharacterInstance(icu_locale, status));
      break;
    case Granularity::WORD:
      icu_break_iterator.reset(
          icu::BreakIterator::createWordInstance(icu_locale, status));
      break;
    case Granularity::SENTENCE:
      icu_break_iterator.reset(
          icu::BreakIterator::createSentenceInstance(icu_locale, status));
      break;
  }
  DCHECK(U_SUCCESS(status));
  DCHECK_NOT_NULL(icu_break_iterator.get());
  DirectHandle<Managed<icu::BreakIterator>> managed_break_iterator =
      Managed<icu::BreakIterator>::From(isolate, 0,
                                        std::move(icu_break_iterator));
  // Now all properties are ready, so we can allocate the result object.
  DirectHandle<JSSegmenter> segmenter =
      Cast<JSSegmenter>(isolate->factory()->NewFastOrSlowJSObjectFromMap(map));
  DisallowGarbageCollection no_gc;
  segmenter->set_flags(0);
  // 12. Set segmenter.[[Locale]] to the value of r.[[Locale]].
  segmenter->set_locale(*locale_str);
  // 14. Set segmenter.[[SegmenterGranularity]] to granularity.
  segmenter->set_granularity(granularity_enum);
  segmenter->set_icu_break_iterator(*managed_break_iterator);
  // 15. Return segmenter.
  return segmenter;
}
References ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Intl::CanonicalizeLocaleList(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::Isolate::factory(), v8::internal::Managed< CppType >::From(), v8::Maybe< T >::FromJust(), GetAvailableLocales(), v8::internal::Intl::GetLocaleMatcher(), v8::internal::GetOptionsObject(), GRAPHEME, v8::internal::Intl::ResolvedLocale::icu_locale, v8::internal::Intl::ResolvedLocale::locale, MAYBE_RETURN, v8::internal::Factory::NewFastOrSlowJSObjectFromMap(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Intl::ResolveLocale(), SENTENCE, v8::internal::status, THROW_NEW_ERROR, and WORD.
ResolvedOptions()
DirectHandle< JSObject > v8::internal::JSSegmenter::ResolvedOptions (Isolate * isolate, DirectHandle< JSSegmenter > segmenter_holder) [static]
Definition at line 125 of file js-segmenter.cc.
                                                           {
  Factory* factory = isolate->factory();
  // 3. Let options be ! ObjectCreate(%ObjectPrototype%).
  DirectHandle<JSObject> result =
      factory->NewJSObject(isolate->object_function());
  // 4. For each row of Table 1, except the header row, do
  // a. Let p be the Property value of the current row.
  // b. Let v be the value of pr's internal slot whose name is the Internal Slot
  // value of the current row.
  //
  // c. If v is not undefined, then
  // i. Perform ! CreateDataPropertyOrThrow(options, p, v).
  // Table 1: Resolved Options of Segmenter Instances
  // Internal Slot Property
  // [[Locale]] "locale"
  // [[SegmenterGranularity]] "granularity"
  DirectHandle<String> locale(segmenter->locale(), isolate);
  JSObject::AddProperty(isolate, result, factory->locale_string(), locale,
                        NONE);
  JSObject::AddProperty(isolate, result, factory->granularity_string(),
                        segmenter->GranularityAsString(isolate), NONE);
  // 5. Return options.
  return result;
}
References v8::internal::JSObject::AddProperty(), v8::internal::Isolate::factory(), v8::internal::Factory::NewJSObject(), v8::internal::NONE, and v8::base::internal::result.
Referenced by v8::internal::BUILTIN().
set_granularity()
void v8::internal::JSSegmenter::set_granularity (Granularity granularity) [inline]
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-segmenter.h
/mnt/V8SourceCode/src/objects/js-segmenter-inl.h
/mnt/V8SourceCode/src/objects/js-segmenter.cc