v8::internal::MathRandom Class Reference
#include <math-random.h>
Classes
struct State
Static Public Member Functions
static void InitializeContext (Isolate *isolate, DirectHandle< Context > native_context)
static void ResetContext (Tagged< Context > native_context)
static Address RefillCache (Isolate *isolate, Address raw_native_context)
Static Public Attributes
static const int kCacheSize = 64
static const int kStateSize = 2 * kInt64Size
Detailed Description
Definition at line 14 of file math-random.h.
Member Function Documentation
InitializeContext()
void v8::internal::MathRandom::InitializeContext (Isolate * isolate, DirectHandle< Context > native_context) [static]
Definition at line 17 of file math-random.cc.
                                                                         {
  auto cache = Cast<FixedDoubleArray>(
      isolate->factory()->NewFixedDoubleArray(kCacheSize));
  for (int i = 0; i < kCacheSize; i++) cache->set(i, 0);
  native_context->set_math_random_cache(*cache);
  DirectHandle<PodArray<State>> pod =
      PodArray<State>::New(isolate, 1, AllocationType::kOld);
  native_context->set_math_random_state(*pod);
  ResetContext(*native_context);
}
References v8::internal::Isolate::factory(), kCacheSize, v8::internal::kOld, v8::internal::native_context, v8::internal::PodArray< T >::New(), v8::internal::FactoryBase< Impl >::NewFixedDoubleArray(), and ResetContext().
Referenced by v8::internal::Genesis::Genesis().
RefillCache()
Address v8::internal::MathRandom::RefillCache (Isolate * isolate, Address raw_native_context) [static]
Definition at line 35 of file math-random.cc.
                                                                            {
  Tagged<Context> native_context =
      Cast<Context>(Tagged<Object>(raw_native_context));
  DisallowGarbageCollection no_gc;
  Tagged<PodArray<State>> pod =
      Cast<PodArray<State>>(native_context->math_random_state());
  State state = pod->get(0);
  // Initialize state if not yet initialized. If a fixed random seed was
  // requested, use it to reset our state the first time a script asks for
  // random numbers in this context. This ensures the script sees a consistent
  // sequence.
  if (state.s0 == 0 && state.s1 == 0) {
    uint64_t seed;
    if (v8_flags.random_seed != 0) {
      seed = v8_flags.random_seed;
    } else {
      isolate->random_number_generator()->NextBytes(&seed, sizeof(seed));
    }
    state.s0 = base::RandomNumberGenerator::MurmurHash3(seed);
    state.s1 = base::RandomNumberGenerator::MurmurHash3(~seed);
    CHECK(state.s0 != 0 || state.s1 != 0);
  }
  Tagged<FixedDoubleArray> cache =
      Cast<FixedDoubleArray>(native_context->math_random_cache());
  // Create random numbers.
  for (int i = 0; i < kCacheSize; i++) {
    // Generate random numbers using xorshift128+.
    base::RandomNumberGenerator::XorShift128(&state.s0, &state.s1);
    cache->set(i, base::RandomNumberGenerator::ToDouble(state.s0));
  }
  pod->set(0, state);
  Tagged<Smi> new_index = Smi::FromInt(kCacheSize);
  native_context->set_math_random_index(new_index);
  return new_index.ptr();
}
References CHECK, v8::internal::Smi::FromInt(), kCacheSize, v8::base::RandomNumberGenerator::MurmurHash3(), v8::internal::native_context, v8::base::RandomNumberGenerator::NextBytes(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::Isolate::random_number_generator(), v8::base::RandomNumberGenerator::ToDouble(), v8::internal::v8_flags, and v8::base::RandomNumberGenerator::XorShift128().
ResetContext()
void v8::internal::MathRandom::ResetContext (Tagged< Context > native_context) [static]
Definition at line 29 of file math-random.cc.
                                                            {
  native_context->set_math_random_index(Smi::zero());
  State state = {0, 0};
  Cast<PodArray<State>>(native_context->math_random_state())->set(0, state);
}
References v8::internal::native_context, and v8::internal::Smi::zero().
Referenced by InitializeContext(), and v8::internal::ContextSerializer::Serialize().
Member Data Documentation
kCacheSize
const int v8::internal::MathRandom::kCacheSize = 64 [static]
Definition at line 24 of file math-random.h.
Referenced by InitializeContext(), and RefillCache().
kStateSize
const int v8::internal::MathRandom::kStateSize = 2 * kInt64Size [static]
Definition at line 25 of file math-random.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/numbers/math-random.h
/mnt/V8SourceCode/src/numbers/math-random.cc