v8::internal::ReadOnlyDeserializer Class Reference
#include <read-only-deserializer.h>
Public Member Functions
ReadOnlyDeserializer (Isolate *isolate, const SnapshotData *data, bool can_rehash)
void DeserializeIntoIsolate ()
Private Member Functions
void PostProcessNewObjects ()
Additional Inherited Members
Detailed Description
Definition at line 16 of file read-only-deserializer.h.
Constructor & Destructor Documentation
ReadOnlyDeserializer()
v8::internal::ReadOnlyDeserializer::ReadOnlyDeserializer (Isolate * isolate, const SnapshotData * data, bool can_rehash)
Definition at line 151 of file read-only-deserializer.cc.
    : Deserializer(isolate, data->Payload(), data->GetMagicNumber(), false,
                   can_rehash) {}
Member Function Documentation
DeserializeIntoIsolate()
void v8::internal::ReadOnlyDeserializer::DeserializeIntoIsolate ()
Definition at line 157 of file read-only-deserializer.cc.
                                                  {
  base::ElapsedTimer timer;
  if (V8_UNLIKELY(v8_flags.profile_deserialization)) timer.Start();
  NestedTimedHistogramScope histogram_timer(
      isolate()->counters()->snapshot_deserialize_rospace());
  HandleScope scope(isolate());
  ReadOnlyHeapImageDeserializer::Deserialize(isolate(), source());
  ReadOnlyHeap* ro_heap = isolate()->read_only_heap();
  ro_heap->read_only_space()->RepairFreeSpacesAfterDeserialization();
  PostProcessNewObjects();
  ReadOnlyRoots roots(isolate());
  roots.VerifyNameForProtectorsPages();
#ifdef DEBUG
  roots.VerifyTypes();
  roots.VerifyNameForProtectors();
#endif
  if (should_rehash()) {
    isolate()->heap()->InitializeHashSeed();
    Rehash();
  }
  if (V8_UNLIKELY(v8_flags.profile_deserialization)) {
    // ATTENTION: The Memory.json benchmark greps for this exact output. Do not
    // change it without also updating Memory.json.
    const int bytes = source()->length();
    const double ms = timer.Elapsed().InMillisecondsF();
    PrintF("[Deserializing read-only space (%d bytes) took %0.3f ms]\n", bytes,
           ms);
  }
}
References v8::internal::ReadOnlyHeapImageDeserializer::Deserialize(), v8::base::ElapsedTimer::Elapsed(), v8::internal::Isolate::heap(), v8::internal::Heap::InitializeHashSeed(), v8::base::TimeDelta::InMillisecondsF(), v8::internal::Deserializer< Isolate >::isolate(), v8::internal::SnapshotByteSource::length(), PostProcessNewObjects(), v8::internal::PrintF(), v8::internal::Isolate::read_only_heap(), v8::internal::ReadOnlyHeap::read_only_space(), v8::internal::Deserializer< Isolate >::Rehash(), v8::internal::ReadOnlySpace::RepairFreeSpacesAfterDeserialization(), v8::internal::Deserializer< Isolate >::should_rehash(), v8::internal::Deserializer< Isolate >::source(), v8::base::ElapsedTimer::Start(), v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::ReadOnlyRoots::VerifyNameForProtectorsPages().
Referenced by v8::internal::ReadOnlyHeap::DeserializeIntoIsolate().
PostProcessNewObjects()
void v8::internal::ReadOnlyDeserializer::PostProcessNewObjects () [private]
Definition at line 400 of file read-only-deserializer.cc.
                                                 {
  // Since we are not deserializing individual objects we need to scan the
  // heap and search for objects that need post-processing.
  //
  // See also Deserializer<IsolateT>::PostProcessNewObject.
  PtrComprCageBase cage_base(isolate());
#ifdef V8_COMPRESS_POINTERS
  ExternalPointerTable::UnsealReadOnlySegmentScope unseal_scope(
      &isolate()->external_pointer_table());
#endif // V8_COMPRESS_POINTERS
  ObjectPostProcessor post_processor(isolate());
  ReadOnlyHeapObjectIterator it(isolate()->read_only_heap());
  for (Tagged<HeapObject> o = it.Next(); !o.is_null(); o = it.Next()) {
    const InstanceType instance_type = o->map(cage_base)->instance_type();
    if (should_rehash()) {
      if (InstanceTypeChecker::IsString(instance_type)) {
        Tagged<String> str = Cast<String>(o);
        str->set_raw_hash_field(Name::kEmptyHashField);
        PushObjectToRehash(direct_handle(str, isolate()));
      } else if (o->NeedsRehashing(instance_type)) {
        PushObjectToRehash(direct_handle(o, isolate()));
      }
    }
    post_processor.PostProcessIfNeeded(o, instance_type);
  }
  post_processor.Finalize();
}
References v8::internal::direct_handle(), v8::internal::ObjectPostProcessor::Finalize(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::Deserializer< Isolate >::isolate(), v8::internal::Name::kEmptyHashField, v8::internal::ReadOnlyHeapObjectIterator::Next(), v8::internal::ObjectPostProcessor::PostProcessIfNeeded(), v8::internal::Deserializer< Isolate >::PushObjectToRehash(), and v8::internal::Deserializer< Isolate >::should_rehash().
Referenced by DeserializeIntoIsolate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/read-only-deserializer.h
/mnt/V8SourceCode/src/snapshot/read-only-deserializer.cc