v8::internal::wasm::WasmExecutionTimer Class Reference
#include <wasm-interpreter.h>
Public Member Functions
WasmExecutionTimer (Isolate *isolate, bool track_jitless_wasm)
void Start ()
void Stop ()
void Terminate ()
Private Member Functions
void StartInternal ()
void StopInternal ()
void BeginInterval (bool start_timer)
void EndInterval ()
void AddSample (int running_ratio)
Private Attributes
Histogram * execute_ratio_histogram_
Histogram * slow_wasm_histogram_
base::ElapsedTimer window_execute_timer_
bool window_has_started_
base::TimeTicks next_interval_time_
base::TimeTicks start_interval_time_
base::TimeDelta window_running_time_
const base::TimeDelta sample_duration_
base::TimeDelta cooldown_interval_
const int slow_threshold_
const size_t slow_threshold_samples_count_
std::vector< int > samples_
Isolate * isolate_
Static Private Attributes
static const int kMaxPercentValue = 100000
Detailed Description
Definition at line 147 of file wasm-interpreter.h.
Constructor & Destructor Documentation
WasmExecutionTimer()
v8::internal::wasm::WasmExecutionTimer::WasmExecutionTimer (Isolate * isolate, bool track_jitless_wasm)
Definition at line 216 of file wasm-interpreter.cc.
    : execute_ratio_histogram_(
          track_jitless_wasm
              ? isolate->counters()->wasm_jitless_execution_ratio()
              : isolate->counters()->wasm_jit_execution_ratio()),
      slow_wasm_histogram_(
          track_jitless_wasm
              ? isolate->counters()->wasm_jitless_execution_too_slow()
              : isolate->counters()->wasm_jit_execution_too_slow()),
      window_has_started_(false),
      next_interval_time_(),
      start_interval_time_(),
      window_running_time_(),
      sample_duration_(base::TimeDelta::FromMilliseconds(std::max(
          0, v8_flags.wasm_exec_time_histogram_sample_duration.value()))),
      slow_threshold_(v8_flags.wasm_exec_time_histogram_slow_threshold.value()),
      slow_threshold_samples_count_(std::max(
          1, v8_flags.wasm_exec_time_slow_threshold_samples_count.value())),
      isolate_(isolate) {
  int cooldown_interval_in_msec = std::max(
      0, v8_flags.wasm_exec_time_histogram_sample_period.value() -
             v8_flags.wasm_exec_time_histogram_sample_duration.value());
  cooldown_interval_ =
      base::TimeDelta::FromMilliseconds(cooldown_interval_in_msec);
}
References cooldown_interval_, v8::base::TimeDelta::FromMilliseconds(), and v8::internal::v8_flags.
Member Function Documentation
AddSample()
void v8::internal::wasm::WasmExecutionTimer::AddSample (int running_ratio) [private]
Definition at line 261 of file wasm-interpreter.cc.
                                                    {
  DCHECK(v8_flags.wasm_enable_exec_time_histograms && v8_flags.slow_histograms);
  execute_ratio_histogram_->AddSample(running_ratio);
  // Emit a Jit[less]WasmExecutionTooSlow sample if the average of the last
  // {v8_flags.wasm_exec_time_slow_threshold_samples_count} samples is above
  // {v8_flags.wasm_exec_time_histogram_slow_threshold}.
  samples_.push_back(running_ratio);
  if (samples_.size() == slow_threshold_samples_count_) {
    int sum = 0;
    for (int sample : samples_) sum += sample;
    int average = sum / slow_threshold_samples_count_;
    if (average >= slow_threshold_) {
      slow_wasm_histogram_->AddSample(average);
      if (isolate_ && !isolate_->context().is_null()) {
        // Skip this event because not(yet) supported by Chromium.
        // HandleScope scope(isolate_);
        // v8::metrics::WasmInterpreterSlowExecution event;
        // event.slow_execution = true;
        // event.jitless = v8_flags.wasm_jitless;
        // event.cpu_percentage = average;
        // v8::metrics::Recorder::ContextId context_id =
        // isolate_->GetOrRegisterRecorderContextId(
        // isolate_->native_context());
        // isolate_->metrics_recorder()->DelayMainThreadEvent(event,
        // context_id);
      }
    }
    samples_.clear();
  }
}
References v8::internal::Histogram::AddSample(), v8::internal::Isolate::context(), v8::internal::DCHECK(), execute_ratio_histogram_, isolate_, samples_, slow_threshold_, slow_threshold_samples_count_, slow_wasm_histogram_, and v8::internal::v8_flags.
Referenced by EndInterval().
BeginInterval()
void v8::internal::wasm::WasmExecutionTimer::BeginInterval (bool start_timer) [private]
Definition at line 243 of file wasm-interpreter.cc.
                                                       {
  window_has_started_ = true;
  start_interval_time_ = base::TimeTicks::Now();
  window_running_time_ = base::TimeDelta();
  if (start_timer) {
    window_execute_timer_.Start();
  }
}
References v8::base::TimeTicks::Now(), v8::base::ElapsedTimer::Start(), start_interval_time_, window_execute_timer_, window_has_started_, and window_running_time_.
Referenced by StartInternal(), and StopInternal().
EndInterval()
void v8::internal::wasm::WasmExecutionTimer::EndInterval () [private]
Definition at line 252 of file wasm-interpreter.cc.
                                     {
  window_has_started_ = false;
  base::TimeTicks now = base::TimeTicks::Now();
  next_interval_time_ = now + cooldown_interval_;
  int running_ratio = kMaxPercentValue *
                      window_running_time_.TimesOf(now - start_interval_time_);
  AddSample(running_ratio);
}
References AddSample(), cooldown_interval_, kMaxPercentValue, next_interval_time_, v8::base::TimeTicks::Now(), start_interval_time_, v8::base::TimeDelta::TimesOf(), window_has_started_, and window_running_time_.
Referenced by StartInternal(), StopInternal(), and Terminate().
Start()
void v8::internal::wasm::WasmExecutionTimer::Start () [inline]
Definition at line 151 of file wasm-interpreter.h.
                         {
    if (execute_ratio_histogram_->Enabled()) StartInternal();
  }
References v8::internal::Histogram::Enabled(), execute_ratio_histogram_, and StartInternal().
Referenced by v8::internal::wasm::WasmInterpreterThread::StartExecutionTimer().
StartInternal()
void v8::internal::wasm::WasmExecutionTimer::StartInternal () [private]
Definition at line 297 of file wasm-interpreter.cc.
                                       {
  DCHECK(v8_flags.wasm_enable_exec_time_histograms && v8_flags.slow_histograms);
  DCHECK(!window_execute_timer_.IsStarted());
  base::TimeTicks now = base::TimeTicks::Now();
  if (window_has_started_) {
    if (now - start_interval_time_ > sample_duration_) {
      EndInterval();
    } else {
      window_execute_timer_.Start();
    }
  } else {
    if (now >= next_interval_time_) {
      BeginInterval(true);
    } else {
      // Ignore this start event.
    }
  }
}
References BeginInterval(), v8::internal::DCHECK(), EndInterval(), v8::base::ElapsedTimer::IsStarted(), next_interval_time_, v8::base::TimeTicks::Now(), sample_duration_, v8::base::ElapsedTimer::Start(), start_interval_time_, v8::internal::v8_flags, window_execute_timer_, and window_has_started_.
Referenced by Start().
Stop()
void v8::internal::wasm::WasmExecutionTimer::Stop () [inline]
Definition at line 155 of file wasm-interpreter.h.
                        {
    if (execute_ratio_histogram_->Enabled()) StopInternal();
  }
References v8::internal::Histogram::Enabled(), execute_ratio_histogram_, and StopInternal().
Referenced by v8::internal::wasm::WasmInterpreterThread::StopExecutionTimer().
StopInternal()
void v8::internal::wasm::WasmExecutionTimer::StopInternal () [private]
Definition at line 317 of file wasm-interpreter.cc.
                                      {
  DCHECK(v8_flags.wasm_enable_exec_time_histograms && v8_flags.slow_histograms);
  base::TimeTicks now = base::TimeTicks::Now();
  if (window_has_started_) {
    DCHECK(window_execute_timer_.IsStarted());
    base::TimeDelta elapsed = window_execute_timer_.Elapsed();
    window_running_time_ += elapsed;
    window_execute_timer_.Stop();
    if (now - start_interval_time_ > sample_duration_) {
      EndInterval();
    }
  } else {
    if (now >= next_interval_time_) {
      BeginInterval(false);
    } else {
      // Ignore this stop event.
    }
  }
}
References BeginInterval(), v8::internal::DCHECK(), v8::base::ElapsedTimer::Elapsed(), EndInterval(), v8::base::ElapsedTimer::IsStarted(), next_interval_time_, v8::base::TimeTicks::Now(), sample_duration_, start_interval_time_, v8::base::ElapsedTimer::Stop(), v8::internal::v8_flags, window_execute_timer_, window_has_started_, and window_running_time_.
Referenced by Stop().
Terminate()
void v8::internal::wasm::WasmExecutionTimer::Terminate ()
Definition at line 338 of file wasm-interpreter.cc.
                                   {
  if (execute_ratio_histogram_->Enabled()) {
    if (window_has_started_) {
      if (window_execute_timer_.IsStarted()) {
        window_execute_timer_.Stop();
      }
      EndInterval();
    }
  }
}
References v8::internal::Histogram::Enabled(), EndInterval(), execute_ratio_histogram_, v8::base::ElapsedTimer::IsStarted(), v8::base::ElapsedTimer::Stop(), window_execute_timer_, and window_has_started_.
Referenced by v8::internal::wasm::WasmInterpreterThread::TerminateExecutionTimers().
Member Data Documentation
cooldown_interval_
base::TimeDelta v8::internal::wasm::WasmExecutionTimer::cooldown_interval_ [private]
Definition at line 178 of file wasm-interpreter.h.
Referenced by EndInterval(), and WasmExecutionTimer().
execute_ratio_histogram_
Histogram* v8::internal::wasm::WasmExecutionTimer::execute_ratio_histogram_ [private]
Definition at line 170 of file wasm-interpreter.h.
Referenced by AddSample(), Start(), Stop(), and Terminate().
isolate_
Isolate* v8::internal::wasm::WasmExecutionTimer::isolate_ [private]
Definition at line 182 of file wasm-interpreter.h.
Referenced by AddSample().
kMaxPercentValue
const int v8::internal::wasm::WasmExecutionTimer::kMaxPercentValue = 100000 [static], [private]
Definition at line 184 of file wasm-interpreter.h.
Referenced by EndInterval().
next_interval_time_
base::TimeTicks v8::internal::wasm::WasmExecutionTimer::next_interval_time_ [private]
Definition at line 174 of file wasm-interpreter.h.
Referenced by EndInterval(), StartInternal(), and StopInternal().
sample_duration_
const base::TimeDelta v8::internal::wasm::WasmExecutionTimer::sample_duration_ [private]
Definition at line 177 of file wasm-interpreter.h.
Referenced by StartInternal(), and StopInternal().
samples_
std::vector<int> v8::internal::wasm::WasmExecutionTimer::samples_ [private]
Definition at line 181 of file wasm-interpreter.h.
Referenced by AddSample().
slow_threshold_
const int v8::internal::wasm::WasmExecutionTimer::slow_threshold_ [private]
Definition at line 179 of file wasm-interpreter.h.
Referenced by AddSample().
slow_threshold_samples_count_
const size_t v8::internal::wasm::WasmExecutionTimer::slow_threshold_samples_count_ [private]
Definition at line 180 of file wasm-interpreter.h.
Referenced by AddSample().
slow_wasm_histogram_
Histogram* v8::internal::wasm::WasmExecutionTimer::slow_wasm_histogram_ [private]
Definition at line 171 of file wasm-interpreter.h.
Referenced by AddSample().
start_interval_time_
base::TimeTicks v8::internal::wasm::WasmExecutionTimer::start_interval_time_ [private]
Definition at line 175 of file wasm-interpreter.h.
Referenced by BeginInterval(), EndInterval(), StartInternal(), and StopInternal().
window_execute_timer_
base::ElapsedTimer v8::internal::wasm::WasmExecutionTimer::window_execute_timer_ [private]
Definition at line 172 of file wasm-interpreter.h.
Referenced by BeginInterval(), StartInternal(), StopInternal(), and Terminate().
window_has_started_
bool v8::internal::wasm::WasmExecutionTimer::window_has_started_ [private]
Definition at line 173 of file wasm-interpreter.h.
Referenced by BeginInterval(), EndInterval(), StartInternal(), StopInternal(), and Terminate().
window_running_time_
base::TimeDelta v8::internal::wasm::WasmExecutionTimer::window_running_time_ [private]
Definition at line 176 of file wasm-interpreter.h.
Referenced by BeginInterval(), EndInterval(), and StopInternal().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.cc