v8::internal::EvacuateVisitorBase Class Reference
Public Member Functions
void AddObserver (MigrationObserver *observer)
Protected Types
enum MigrationMode { kFast
, kObserved
 }
using MigrateFunction = void(*)(EvacuateVisitorBase *base, Tagged< HeapObject > dst, Tagged< HeapObject > src, int size, AllocationSpace dest)
Protected Member Functions
PtrComprCageBase cage_base ()
EvacuateVisitorBase (Heap *heap, EvacuationAllocator *local_allocator, RecordMigratedSlotVisitor *record_visitor)
bool TryEvacuateObject (AllocationSpace target_space, Tagged< HeapObject > object, int size, Tagged< HeapObject > *target_object)
bool ShouldPromoteIntoSharedHeap (Tagged< Map > map)
void ExecuteMigrationObservers (AllocationSpace dest, Tagged< HeapObject > src, Tagged< HeapObject > dst, int size)
void MigrateObject (Tagged< HeapObject > dst, Tagged< HeapObject > src, int size, AllocationSpace dest)
Static Protected Member Functions
template<MigrationMode mode>
static void RawMigrateObject (EvacuateVisitorBase *base, Tagged< HeapObject > dst, Tagged< HeapObject > src, int size, AllocationSpace dest)
Protected Attributes
Heap * heap_
EvacuationAllocator * local_allocator_
RecordMigratedSlotVisitor * record_visitor_
std::vector< MigrationObserver * > observers_
MigrateFunction migration_function_
const bool shared_string_table_
std::optional< base::RandomNumberGenerator > rng_
Detailed Description
Definition at line 1452 of file mark-compact.cc.
Member Typedef Documentation
MigrateFunction
using v8::internal::EvacuateVisitorBase::MigrateFunction = void (*)(EvacuateVisitorBase* base, Tagged<HeapObject> dst, Tagged<HeapObject> src, int size, AllocationSpace dest) [protected]
Definition at line 1494 of file mark-compact.cc.
Member Enumeration Documentation
MigrationMode
enum v8::internal::EvacuateVisitorBase::MigrationMode [protected]
Enumerator
kFast
kObserved
Definition at line 1484 of file mark-compact.cc.
{ kFast, kObserved };
Constructor & Destructor Documentation
EvacuateVisitorBase()
v8::internal::EvacuateVisitorBase::EvacuateVisitorBase (Heap * heap, EvacuationAllocator * local_allocator, RecordMigratedSlotVisitor * record_visitor) [inline], [protected]
Definition at line 1581 of file mark-compact.cc.
      : heap_(heap),
        local_allocator_(local_allocator),
        record_visitor_(record_visitor),
        shared_string_table_(v8_flags.shared_string_table &&
                             heap->isolate()->has_shared_space()) {
    migration_function_ = RawMigrateObject<MigrationMode::kFast>;
#if DEBUG
    rng_.emplace(heap_->isolate()->fuzzer_rng()->NextInt64());
#endif // DEBUG
  }
References v8::internal::Isolate::fuzzer_rng(), heap_, v8::internal::Heap::isolate(), migration_function_, v8::base::RandomNumberGenerator::NextInt64(), and rng_.
Member Function Documentation
AddObserver()
void v8::internal::EvacuateVisitorBase::AddObserver (MigrationObserver * observer) [inline]
Definition at line 1454 of file mark-compact.cc.
                                                {
    migration_function_ = RawMigrateObject<MigrationMode::kObserved>;
    observers_.push_back(observer);
  }
References migration_function_, and observers_.
cage_base()
PtrComprCageBase v8::internal::EvacuateVisitorBase::cage_base () [inline], [protected]
Definition at line 1486 of file mark-compact.cc.
                               {
#if V8_COMPRESS_POINTERS
    return PtrComprCageBase{heap_->isolate()};
#else
    return PtrComprCageBase{};
#endif // V8_COMPRESS_POINTERS
  }
References heap_, and v8::internal::Heap::isolate().
Referenced by RawMigrateObject(), and TryEvacuateObject().
ExecuteMigrationObservers()
void v8::internal::EvacuateVisitorBase::ExecuteMigrationObservers (AllocationSpace dest, Tagged< HeapObject > src, Tagged< HeapObject > dst, int size) [inline], [protected]
Definition at line 1634 of file mark-compact.cc.
                                                                          {
    for (MigrationObserver* obs : observers_) {
      obs->Move(dest, src, dst, size);
    }
  }
References observers_, and size().
Referenced by RawMigrateObject().
MigrateObject()
void v8::internal::EvacuateVisitorBase::MigrateObject (Tagged< HeapObject > dst, Tagged< HeapObject > src, int size, AllocationSpace dest) [inline], [protected]
Definition at line 1642 of file mark-compact.cc.
                                                            {
    migration_function_(this, dst, src, size, dest);
  }
References migration_function_, and size().
Referenced by TryEvacuateObject().
RawMigrateObject()
template<MigrationMode mode>
static void v8::internal::EvacuateVisitorBase::RawMigrateObject (EvacuateVisitorBase * base, Tagged< HeapObject > dst, Tagged< HeapObject > src, int size, AllocationSpace dest) [inline], [static], [protected]
Definition at line 1500 of file mark-compact.cc.
                                                               {
    Address dst_addr = dst.address();
    Address src_addr = src.address();
    PtrComprCageBase cage_base = base->cage_base();
    DCHECK(base->heap_->AllowedToBeMigrated(src->map(cage_base), src, dest));
    DCHECK_NE(dest, LO_SPACE);
    DCHECK_NE(dest, CODE_LO_SPACE);
    DCHECK_NE(dest, TRUSTED_LO_SPACE);
    if (dest == OLD_SPACE) {
      DCHECK_OBJECT_SIZE(size);
      DCHECK(IsAligned(size, kTaggedSize));
      base->heap_->CopyBlock(dst_addr, src_addr, size);
      if (mode != MigrationMode::kFast) {
        base->ExecuteMigrationObservers(dest, src, dst, size);
      }
      // In case the object's map gets relocated during GC we load the old map
      // here. This is fine since they store the same content.
      base->record_visitor_->Visit(dst->map(cage_base), dst, size);
    } else if (dest == SHARED_SPACE) {
      DCHECK_OBJECT_SIZE(size);
      DCHECK(IsAligned(size, kTaggedSize));
      base->heap_->CopyBlock(dst_addr, src_addr, size);
      if (mode != MigrationMode::kFast) {
        base->ExecuteMigrationObservers(dest, src, dst, size);
      }
      base->record_visitor_->Visit(dst->map(cage_base), dst, size);
    } else if (dest == TRUSTED_SPACE) {
      DCHECK_OBJECT_SIZE(size);
      DCHECK(IsAligned(size, kTaggedSize));
      base->heap_->CopyBlock(dst_addr, src_addr, size);
      if (mode != MigrationMode::kFast) {
        base->ExecuteMigrationObservers(dest, src, dst, size);
      }
      // In case the object's map gets relocated during GC we load the old map
      // here. This is fine since they store the same content.
      base->record_visitor_->Visit(dst->map(cage_base), dst, size);
    } else if (dest == CODE_SPACE) {
      DCHECK_CODEOBJECT_SIZE(size);
      {
        WritableJitAllocation writable_allocation =
            ThreadIsolation::RegisterInstructionStreamAllocation(dst_addr,
                                                                 size);
        DCHECK_GT(size, InstructionStream::kHeaderSize);
        writable_allocation.CopyData(0, reinterpret_cast<uint8_t*>(src_addr),
                                     InstructionStream::kHeaderSize);
        writable_allocation.CopyCode(
            InstructionStream::kHeaderSize,
            reinterpret_cast<uint8_t*>(src_addr +
                                       InstructionStream::kHeaderSize),
            size - InstructionStream::kHeaderSize);
        Tagged<InstructionStream> istream = Cast<InstructionStream>(dst);
        istream->Relocate(writable_allocation, dst_addr - src_addr);
      }
      if (mode != MigrationMode::kFast) {
        base->ExecuteMigrationObservers(dest, src, dst, size);
      }
      // In case the object's map gets relocated during GC we load the old map
      // here. This is fine since they store the same content.
      base->record_visitor_->Visit(dst->map(cage_base), dst, size);
    } else {
      DCHECK_OBJECT_SIZE(size);
      DCHECK(dest == NEW_SPACE);
      base->heap_->CopyBlock(dst_addr, src_addr, size);
      if (mode != MigrationMode::kFast) {
        base->ExecuteMigrationObservers(dest, src, dst, size);
      }
    }
    if (dest == CODE_SPACE) {
      WritableJitAllocation jit_allocation =
          WritableJitAllocation::ForInstructionStream(
              Cast<InstructionStream>(src));
      jit_allocation.WriteHeaderSlot<MapWord, HeapObject::kMapOffset>(
          MapWord::FromForwardingAddress(src, dst));
    } else {
      src->set_map_word_forwarded(dst, kRelaxedStore);
    }
  }
References v8::internal::Tagged< HeapObject >::address(), v8::internal::Heap::AllowedToBeMigrated(), cage_base(), v8::internal::CODE_LO_SPACE, v8::internal::CODE_SPACE, v8::internal::Heap::CopyBlock(), v8::internal::WritableJitAllocation::CopyCode(), v8::internal::WritableJitAllocation::CopyData(), v8::internal::DCHECK(), DCHECK_CODEOBJECT_SIZE, DCHECK_GT, DCHECK_NE, DCHECK_OBJECT_SIZE, ExecuteMigrationObservers(), v8::internal::WritableJitAllocation::ForInstructionStream(), v8::internal::MapWord::FromForwardingAddress(), heap_, IsAligned(), v8::internal::TrustedObject::kHeaderSize, v8::internal::HeapObject::kMapOffset, v8::kRelaxedStore, v8::internal::kTaggedSize, v8::internal::LO_SPACE, mode(), v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, record_visitor_, v8::internal::ThreadIsolation::RegisterInstructionStreamAllocation(), v8::internal::SHARED_SPACE, size(), v8::internal::TRUSTED_LO_SPACE, v8::internal::TRUSTED_SPACE, v8::internal::HeapVisitor< ConcreteVisitor >::Visit(), and v8::internal::WritableJitAllocation::WriteHeaderSlot().
ShouldPromoteIntoSharedHeap()
bool v8::internal::EvacuateVisitorBase::ShouldPromoteIntoSharedHeap (Tagged< Map > map) [inline], [protected]
Definition at line 1626 of file mark-compact.cc.
                                                           {
    if (shared_string_table_) {
      return String::IsInPlaceInternalizableExcludingExternal(
          map->instance_type());
    }
    return false;
  }
References v8::internal::String::IsInPlaceInternalizableExcludingExternal(), and shared_string_table_.
Referenced by TryEvacuateObject().
TryEvacuateObject()
bool v8::internal::EvacuateVisitorBase::TryEvacuateObject (AllocationSpace target_space, Tagged< HeapObject > object, int size, Tagged< HeapObject > * target_object) [inline], [protected]
Definition at line 1594 of file mark-compact.cc.
                                                                   {
#if DEBUG
    DCHECK_LE(abort_evacuation_at_address_,
              MutablePageMetadata::FromHeapObject(object)->area_end());
    DCHECK_GE(abort_evacuation_at_address_,
              MutablePageMetadata::FromHeapObject(object)->area_start());
    if (V8_UNLIKELY(object.address() >= abort_evacuation_at_address_)) {
      return false;
    }
#endif // DEBUG
    Tagged<Map> map = object->map(cage_base());
    AllocationResult allocation;
    if (target_space == OLD_SPACE && ShouldPromoteIntoSharedHeap(map)) {
      AllocationAlignment alignment =
          HeapObject::RequiredAlignment(SHARED_SPACE, map);
      allocation = local_allocator_->Allocate(SHARED_SPACE, size, alignment);
    } else {
      AllocationAlignment alignment =
          HeapObject::RequiredAlignment(target_space, map);
      allocation = local_allocator_->Allocate(target_space, size, alignment);
    }
    if (allocation.To(target_object)) {
      MigrateObject(*target_object, object, size, target_space);
      return true;
    }
    return false;
  }
References v8::internal::EvacuationAllocator::Allocate(), cage_base(), DCHECK_GE, DCHECK_LE, v8::internal::MutablePageMetadata::FromHeapObject(), local_allocator_, MigrateObject(), v8::internal::OLD_SPACE, v8::internal::HeapObject::RequiredAlignment(), v8::internal::SHARED_SPACE, ShouldPromoteIntoSharedHeap(), size(), v8::internal::AllocationResult::To(), and V8_UNLIKELY.
Referenced by v8::internal::EvacuateNewSpaceVisitor::Visit(), and v8::internal::EvacuateOldSpaceVisitor::Visit().
Member Data Documentation
heap_
Heap* v8::internal::EvacuateVisitorBase::heap_ [protected]
Definition at line 1647 of file mark-compact.cc.
Referenced by v8::internal::EvacuateNewSpaceVisitor::AllocateInOldSpace(), cage_base(), EvacuateVisitorBase(), RawMigrateObject(), v8::internal::EvacuateNewSpaceVisitor::Visit(), and v8::internal::EvacuateOldSpaceVisitor::Visit().
local_allocator_
EvacuationAllocator* v8::internal::EvacuateVisitorBase::local_allocator_ [protected]
Definition at line 1648 of file mark-compact.cc.
Referenced by v8::internal::EvacuateNewSpaceVisitor::AllocateInOldSpace(), v8::internal::EvacuateNewSpaceVisitor::AllocateTargetObject(), and TryEvacuateObject().
migration_function_
MigrateFunction v8::internal::EvacuateVisitorBase::migration_function_ [protected]
Definition at line 1651 of file mark-compact.cc.
Referenced by AddObserver(), EvacuateVisitorBase(), and MigrateObject().
observers_
std::vector<MigrationObserver*> v8::internal::EvacuateVisitorBase::observers_ [protected]
Definition at line 1650 of file mark-compact.cc.
Referenced by AddObserver(), and ExecuteMigrationObservers().
record_visitor_
RecordMigratedSlotVisitor* v8::internal::EvacuateVisitorBase::record_visitor_ [protected]
Definition at line 1649 of file mark-compact.cc.
Referenced by RawMigrateObject().
rng_
std::optional<base::RandomNumberGenerator> v8::internal::EvacuateVisitorBase::rng_ [protected]
Definition at line 1656 of file mark-compact.cc.
Referenced by EvacuateVisitorBase().
shared_string_table_
const bool v8::internal::EvacuateVisitorBase::shared_string_table_ [protected]
Definition at line 1652 of file mark-compact.cc.
Referenced by ShouldPromoteIntoSharedHeap().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc