v8::internal::maglev::CallCPPBuiltin Class Reference
#include <maglev-ir.h>
Public Member Functions
CallCPPBuiltin (uint64_t bitfield, Builtin builtin, ValueNode *target, ValueNode *new_target, ValueNode *context)
Builtin builtin () const
Input & target ()
const Input & target () const
Input & new_target ()
const Input & new_target () const
Input & context ()
const Input & context () const
int num_args () const
Input & arg (int i)
void set_arg (int i, ValueNode *node)
auto args ()
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
Static Public Attributes
static constexpr int kTargetIndex = 0
static constexpr int kNewTargetIndex = 1
static constexpr int kContextIndex = 2
static constexpr int kFixedInputCount = 3
static constexpr OpProperties kProperties = OpProperties::JSCall()
Private Types
using Base = ValueNodeT< CallCPPBuiltin >
Private Attributes
Builtin builtin_
Static Private Attributes
static constexpr Builtin kCEntry_Builtin
Additional Inherited Members
Detailed Description
Definition at line 10218 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CallCPPBuiltin::Base = ValueNodeT<CallCPPBuiltin> [private]
Definition at line 10219 of file maglev-ir.h.
Constructor & Destructor Documentation
CallCPPBuiltin()
v8::internal::maglev::CallCPPBuiltin::CallCPPBuiltin (uint64_t bitfield, Builtin builtin, ValueNode * target, ValueNode * new_target, ValueNode * context) [inline]
Definition at line 10230 of file maglev-ir.h.
      : Base(bitfield), builtin_(builtin) {
    DCHECK(Builtins::CallInterfaceDescriptorFor(builtin).HasContextParameter());
    DCHECK_EQ(Builtins::CallInterfaceDescriptorFor(builtin).GetReturnCount(),
              1);
    set_input(kTargetIndex, target);
    set_input(kNewTargetIndex, new_target);
    set_input(kContextIndex, context);
  }
References DCHECK, and DCHECK_EQ.
Member Function Documentation
arg()
Input& v8::internal::maglev::CallCPPBuiltin::arg (int i) [inline]
Definition at line 10254 of file maglev-ir.h.
{ return input(i + kFixedInputCount); }
args()
auto v8::internal::maglev::CallCPPBuiltin::args () [inline]
Definition at line 10259 of file maglev-ir.h.
              {
    return base::make_iterator_range(
        std::make_reverse_iterator(&arg(-1)),
        std::make_reverse_iterator(&arg(num_args() - 1)));
  }
References v8::base::make_iterator_range().
builtin()
Builtin v8::internal::maglev::CallCPPBuiltin::builtin () const [inline]
Definition at line 10244 of file maglev-ir.h.
{ return builtin_; }
Referenced by PrintParams().
context() [1/2]
Input& v8::internal::maglev::CallCPPBuiltin::context () [inline]
Definition at line 10250 of file maglev-ir.h.
{ return input(kContextIndex); }
context() [2/2]
const Input& v8::internal::maglev::CallCPPBuiltin::context () const [inline]
Definition at line 10251 of file maglev-ir.h.
{ return input(kContextIndex); }
GenerateCode()
void v8::internal::maglev::CallCPPBuiltin::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::CallCPPBuiltin::MaxCallStackArgs () const
new_target() [1/2]
Input& v8::internal::maglev::CallCPPBuiltin::new_target () [inline]
Definition at line 10248 of file maglev-ir.h.
{ return input(kNewTargetIndex); }
new_target() [2/2]
const Input& v8::internal::maglev::CallCPPBuiltin::new_target () const [inline]
Definition at line 10249 of file maglev-ir.h.
{ return input(kNewTargetIndex); }
num_args()
int v8::internal::maglev::CallCPPBuiltin::num_args () const [inline]
Definition at line 10253 of file maglev-ir.h.
{ return input_count() - kFixedInputCount; }
References v8::internal::compiler::turboshaft::detail::input_count().
PrintParams()
void v8::internal::maglev::CallCPPBuiltin::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8412 of file maglev-ir.cc.
                                                                            {
  os << "(" << Builtins::name(builtin()) << ")";
}
References builtin(), and v8::internal::Builtins::name().
set_arg()
void v8::internal::maglev::CallCPPBuiltin::set_arg (int i, ValueNode * node) [inline]
Definition at line 10255 of file maglev-ir.h.
                                       {
    set_input(i + kFixedInputCount, node);
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCallCPPBuiltin().
SetValueLocationConstraints()
void v8::internal::maglev::CallCPPBuiltin::SetValueLocationConstraints ()
target() [1/2]
Input& v8::internal::maglev::CallCPPBuiltin::target () [inline]
Definition at line 10246 of file maglev-ir.h.
{ return input(kTargetIndex); }
target() [2/2]
const Input& v8::internal::maglev::CallCPPBuiltin::target () const [inline]
Definition at line 10247 of file maglev-ir.h.
{ return input(kTargetIndex); }
VerifyInputs()
void v8::internal::maglev::CallCPPBuiltin::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 1103 of file maglev-ir.cc.
                                                                           {
  for (int i = 0; i < input_count(); i++) {
    CheckValueInputIs(this, i, ValueRepresentation::kTagged, graph_labeller);
  }
}
References v8::internal::maglev::CheckValueInputIs(), v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::maglev::kTagged.
Member Data Documentation
builtin_
Builtin v8::internal::maglev::CallCPPBuiltin::builtin_ [private]
Definition at line 10275 of file maglev-ir.h.
kCEntry_Builtin
constexpr Builtin v8::internal::maglev::CallCPPBuiltin::kCEntry_Builtin [static], [constexpr], [private]
Initial value:
=
      Builtin::kCEntry_Return1_ArgvOnStack_BuiltinExit
Definition at line 10221 of file maglev-ir.h.
kContextIndex
constexpr int v8::internal::maglev::CallCPPBuiltin::kContextIndex = 2 [static], [constexpr]
Definition at line 10227 of file maglev-ir.h.
kFixedInputCount
constexpr int v8::internal::maglev::CallCPPBuiltin::kFixedInputCount = 3 [static], [constexpr]
Definition at line 10228 of file maglev-ir.h.
kNewTargetIndex
constexpr int v8::internal::maglev::CallCPPBuiltin::kNewTargetIndex = 1 [static], [constexpr]
Definition at line 10226 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CallCPPBuiltin::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 10242 of file maglev-ir.h.
kTargetIndex
constexpr int v8::internal::maglev::CallCPPBuiltin::kTargetIndex = 0 [static], [constexpr]
Definition at line 10225 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc