v8::internal::PagedSpaceForNewSpace Class Reference
#include <new-spaces.h>
Public Member Functions
PagedSpaceForNewSpace (Heap *heap, size_t initial_capacity, size_t min_capacity, size_t max_capacity)
void TearDown ()
void Grow (size_t new_capacity)
void GrowToMaximumCapacityForTesting ()
bool StartShrinking (size_t new_target_capacity)
void FinishShrinking ()
size_t AllocatedSinceLastGC () const
size_t MinimumCapacity () const
size_t MaximumCapacity () const
size_t TotalCapacity () const
Address first_allocatable_address () const
void GarbageCollectionEpilogue ()
PageMetadata * InitializePage (MutablePageMetadata *chunk) final
size_t AddPage (PageMetadata *page) final
void RemovePage (PageMetadata *page) final
void RemovePageFromSpace (PageMetadata *page) final
size_t ExternalBackingStoreBytes (ExternalBackingStoreType type) const final
void MakeIterable ()
bool ShouldReleaseEmptyPage () const
void AllocatePageUpToCapacityForTesting ()
bool IsPromotionCandidate (const MutablePageMetadata *page) const
size_t Available () const final
size_t UsableCapacity () const
AllocatorPolicy * CreateAllocatorPolicy (MainAllocator *allocator) final
Private Member Functions
bool AllocatePage ()
Private Attributes
const size_t min_capacity_
const size_t max_capacity_
size_t target_capacity_ = 0
size_t current_capacity_ = 0
PageMetadata * last_lab_page_ = nullptr
Friends
class PagedNewSpaceAllocatorPolicy
Additional Inherited Members
Detailed Description
Definition at line 504 of file new-spaces.h.
Constructor & Destructor Documentation
PagedSpaceForNewSpace()
v8::internal::PagedSpaceForNewSpace::PagedSpaceForNewSpace (Heap * heap, size_t initial_capacity, size_t min_capacity, size_t max_capacity) [explicit]
Definition at line 831 of file new-spaces.cc.
    : PagedSpaceBase(heap, NEW_SPACE, NOT_EXECUTABLE,
                     FreeList::CreateFreeListForNewSpace(),
                     CompactionSpaceKind::kNone),
      min_capacity_(min_capacity),
      max_capacity_(max_capacity),
      target_capacity_(initial_capacity) {
  DCHECK(IsAligned(target_capacity_, PageMetadata::kPageSize));
  DCHECK(IsAligned(min_capacity_, PageMetadata::kPageSize));
  DCHECK(IsAligned(max_capacity_, PageMetadata::kPageSize));
  DCHECK_LE(min_capacity_, target_capacity_);
  DCHECK_LE(target_capacity_, max_capacity_);
}
References v8::internal::DCHECK(), DCHECK_LE, IsAligned(), v8::internal::kNone, v8::internal::MutablePageMetadata::kPageSize, max_capacity_, min_capacity_, and target_capacity_.
Member Function Documentation
AddPage()
size_t v8::internal::PagedSpaceForNewSpace::AddPage (PageMetadata * page) [final], [virtual]
Reimplemented from v8::internal::PagedSpaceBase.
Definition at line 903 of file new-spaces.cc.
                                                        {
  current_capacity_ += PageMetadata::kPageSize;
  return PagedSpaceBase::AddPage(page);
}
References v8::internal::PagedSpaceBase::AddPage(), current_capacity_, and v8::internal::MutablePageMetadata::kPageSize.
AllocatedSinceLastGC()
size_t v8::internal::PagedSpaceForNewSpace::AllocatedSinceLastGC () const
Definition at line 949 of file new-spaces.cc.
                                                         {
  return Size() - size_at_last_gc_;
}
References v8::internal::PagedSpaceBase::Size(), and v8::internal::PagedSpaceBase::size_at_last_gc_.
AllocatePage()
bool v8::internal::PagedSpaceForNewSpace::AllocatePage () [private]
Definition at line 930 of file new-spaces.cc.
                                         {
  // Verify that the free space map is already initialized. Otherwise, new free
  // list entries will be invalid.
  DCHECK_NE(kNullAddress,
            heap()->isolate()->root(RootIndex::kFreeSpaceMap).ptr());
  return TryExpand(heap()->main_thread_local_heap(),
                   AllocationOrigin::kRuntime);
}
References DCHECK_NE, heap(), v8::internal::kNullAddress, v8::internal::kRuntime, and v8::internal::PagedSpaceBase::TryExpand().
Referenced by AllocatePageUpToCapacityForTesting(), and v8::internal::PagedNewSpaceAllocatorPolicy::TryAllocatePage().
AllocatePageUpToCapacityForTesting()
void v8::internal::PagedSpaceForNewSpace::AllocatePageUpToCapacityForTesting ()
Definition at line 924 of file new-spaces.cc.
                                                               {
  while (current_capacity_ < target_capacity_) {
    if (!AllocatePage()) return;
  }
}
References AllocatePage(), current_capacity_, and target_capacity_.
Available()
size_t v8::internal::PagedSpaceForNewSpace::Available () const [final]
Definition at line 953 of file new-spaces.cc.
                                              {
  return PagedSpaceBase::Available();
}
References v8::internal::PagedSpaceBase::Available().
CreateAllocatorPolicy()
AllocatorPolicy* v8::internal::PagedSpaceForNewSpace::CreateAllocatorPolicy (MainAllocator * allocator) [inline], [final]
Definition at line 576 of file new-spaces.h.
                                                                         {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
ExternalBackingStoreBytes()
size_t v8::internal::PagedSpaceForNewSpace::ExternalBackingStoreBytes (ExternalBackingStoreType type) const [inline], [final]
Definition at line 549 of file new-spaces.h.
                                                                              {
    if (type == ExternalBackingStoreType::kArrayBuffer)
      return heap()->YoungArrayBufferBytes();
    return external_backing_store_bytes_[static_cast<int>(type)];
  }
References heap(), v8::internal::kArrayBuffer, and v8::internal::tracing::type.
FinishShrinking()
void v8::internal::PagedSpaceForNewSpace::FinishShrinking ()
Definition at line 886 of file new-spaces.cc.
                                            {
  DCHECK(heap()->tracer()->IsInAtomicPause());
  if (current_capacity_ > target_capacity_) {
#if DEBUG
    // If `current_capacity_` is higher than `target_capacity_`, i.e. the
    // space could not be shrunk all the way down to `target_capacity_`, it
    // must mean that all pages contain live objects.
    for (PageMetadata* page : *this) {
      DCHECK_NE(0, page->live_bytes());
    }
#endif // DEBUG
    // After a minor GC current_capacity_ could be still above max_capacity_
    // when not enough pages got promoted or died.
    target_capacity_ = std::min(current_capacity_, max_capacity_);
  }
}
References current_capacity_, v8::internal::DCHECK(), DCHECK_NE, heap(), v8::internal::MutablePageMetadata::live_bytes(), max_capacity_, and target_capacity_.
first_allocatable_address()
Address v8::internal::PagedSpaceForNewSpace::first_allocatable_address () const [inline]
Definition at line 533 of file new-spaces.h.
                                            {
    return first_page()->area_start();
  }
GarbageCollectionEpilogue()
void v8::internal::PagedSpaceForNewSpace::GarbageCollectionEpilogue () [inline]
Definition at line 538 of file new-spaces.h.
                                   {
    size_at_last_gc_ = Size();
    last_lab_page_ = nullptr;
  }
Grow()
void v8::internal::PagedSpaceForNewSpace::Grow (size_t new_capacity)
Definition at line 868 of file new-spaces.cc.
                                                    {
  heap()->safepoint()->AssertActive();
  DCHECK_LE(TotalCapacity(), MaximumCapacity());
  DCHECK_LE(new_capacity, MaximumCapacity());
  target_capacity_ = new_capacity;
}
References DCHECK_LE, heap(), MaximumCapacity(), target_capacity_, and TotalCapacity().
Referenced by GrowToMaximumCapacityForTesting().
GrowToMaximumCapacityForTesting()
void v8::internal::PagedSpaceForNewSpace::GrowToMaximumCapacityForTesting ()
Definition at line 875 of file new-spaces.cc.
                                                            {
  Grow(max_capacity_);
}
References Grow(), and max_capacity_.
InitializePage()
PageMetadata * v8::internal::PagedSpaceForNewSpace::InitializePage (MutablePageMetadata * chunk) [final]
Definition at line 849 of file new-spaces.cc.
                                                {
  DCHECK_EQ(identity(), NEW_SPACE);
  MemoryChunk* chunk = mutable_page_metadata->Chunk();
  PageMetadata* page = PageMetadata::cast(mutable_page_metadata);
  DCHECK_EQ(
      MemoryChunkLayout::AllocatableMemoryInMemoryChunk(page->owner_identity()),
      page->area_size());
  // Make sure that categories are initialized before freeing the area.
  page->ResetAllocationStatistics();
  chunk->SetFlagNonExecutable(MemoryChunk::TO_PAGE);
  page->ClearLiveness();
  page->AllocateFreeListCategories();
  page->InitializeFreeListCategories();
  page->list_node().Initialize();
  chunk->InitializationMemoryFence();
  return page;
}
References v8::internal::MemoryChunkLayout::AllocatableMemoryInMemoryChunk(), v8::internal::PageMetadata::AllocateFreeListCategories(), v8::internal::MemoryChunkMetadata::area_size(), v8::internal::PageMetadata::cast(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MutablePageMetadata::ClearLiveness(), DCHECK_EQ, v8::internal::MemoryChunk::InitializationMemoryFence(), v8::internal::PageMetadata::InitializeFreeListCategories(), v8::internal::MutablePageMetadata::list_node(), v8::internal::NEW_SPACE, v8::internal::MutablePageMetadata::owner_identity(), v8::internal::MutablePageMetadata::ResetAllocationStatistics(), v8::internal::MemoryChunk::SetFlagNonExecutable(), and v8::internal::MemoryChunk::TO_PAGE.
IsPromotionCandidate()
bool v8::internal::PagedSpaceForNewSpace::IsPromotionCandidate (const MutablePageMetadata * page) const
Definition at line 939 of file new-spaces.cc.
                                           {
  DCHECK_EQ(this, page->owner());
  if (page == last_lab_page_) return false;
  return page->AllocatedLabSize() <=
         static_cast<size_t>(
             PageMetadata::kPageSize *
             v8_flags.minor_ms_page_promotion_max_lab_threshold / 100);
}
References v8::internal::MutablePageMetadata::AllocatedLabSize(), DCHECK_EQ, v8::internal::MutablePageMetadata::kPageSize, last_lab_page_, v8::internal::MutablePageMetadata::owner(), and v8::internal::v8_flags.
MakeIterable()
void v8::internal::PagedSpaceForNewSpace::MakeIterable () [inline]
Definition at line 559 of file new-spaces.h.
{ free_list()->RepairLists(heap()); }
References heap().
MaximumCapacity()
size_t v8::internal::PagedSpaceForNewSpace::MaximumCapacity () const [inline]
Definition at line 527 of file new-spaces.h.
{ return max_capacity_; }
Referenced by Grow().
MinimumCapacity()
size_t v8::internal::PagedSpaceForNewSpace::MinimumCapacity () const [inline]
Definition at line 524 of file new-spaces.h.
{ return min_capacity_; }
RemovePage()
void v8::internal::PagedSpaceForNewSpace::RemovePage (PageMetadata * page) [final], [virtual]
Reimplemented from v8::internal::PagedSpaceBase.
Definition at line 908 of file new-spaces.cc.
                                                         {
  DCHECK_LE(PageMetadata::kPageSize, current_capacity_);
  current_capacity_ -= PageMetadata::kPageSize;
  PagedSpaceBase::RemovePage(page);
}
References current_capacity_, DCHECK_LE, v8::internal::MutablePageMetadata::kPageSize, and v8::internal::PagedSpaceBase::RemovePage().
RemovePageFromSpace()
void v8::internal::PagedSpaceForNewSpace::RemovePageFromSpace (PageMetadata * page) [final], [virtual]
Reimplemented from v8::internal::PagedSpaceBase.
Definition at line 914 of file new-spaces.cc.
                                                                  {
  DCHECK_LE(PageMetadata::kPageSize, current_capacity_);
  current_capacity_ -= PageMetadata::kPageSize;
  PagedSpaceBase::RemovePageFromSpaceImpl(page);
}
References current_capacity_, DCHECK_LE, v8::internal::MutablePageMetadata::kPageSize, and v8::internal::PagedSpaceBase::RemovePageFromSpaceImpl().
Referenced by v8::internal::MinorMarkSweepCollector::StartSweepNewSpace().
ShouldReleaseEmptyPage()
bool v8::internal::PagedSpaceForNewSpace::ShouldReleaseEmptyPage () const
Definition at line 920 of file new-spaces.cc.
                                                         {
  return current_capacity_ > target_capacity_;
}
References current_capacity_, and target_capacity_.
Referenced by v8::internal::MarkCompactCollector::StartSweepNewSpace(), and v8::internal::MinorMarkSweepCollector::StartSweepNewSpace().
StartShrinking()
bool v8::internal::PagedSpaceForNewSpace::StartShrinking (size_t new_target_capacity)
Definition at line 879 of file new-spaces.cc.
                                                                     {
  DCHECK(heap()->tracer()->IsInAtomicPause());
  if (new_target_capacity > target_capacity_) return false;
  target_capacity_ = new_target_capacity;
  return true;
}
References v8::internal::DCHECK(), heap(), and target_capacity_.
TearDown()
void v8::internal::PagedSpaceForNewSpace::TearDown () [inline]
Definition at line 511 of file new-spaces.h.
{ PagedSpaceBase::TearDown(); }
References v8::internal::PagedSpaceBase::TearDown().
Referenced by v8::internal::PagedNewSpace::~PagedNewSpace().
TotalCapacity()
size_t v8::internal::PagedSpaceForNewSpace::TotalCapacity () const [inline]
Definition at line 529 of file new-spaces.h.
{ return target_capacity_; }
Referenced by Grow().
UsableCapacity()
size_t v8::internal::PagedSpaceForNewSpace::UsableCapacity () const [inline]
Definition at line 571 of file new-spaces.h.
                                {
    DCHECK_LE(free_list_->wasted_bytes(), current_capacity_);
    return current_capacity_ - free_list_->wasted_bytes();
  }
References DCHECK_LE.
Referenced by v8::internal::Heap::StartMinorMSConcurrentMarkingIfNeeded().
Friends And Related Function Documentation
PagedNewSpaceAllocatorPolicy
friend class PagedNewSpaceAllocatorPolicy [friend]
Definition at line 590 of file new-spaces.h.
Member Data Documentation
current_capacity_
size_t v8::internal::PagedSpaceForNewSpace::current_capacity_ = 0 [private]
Definition at line 586 of file new-spaces.h.
Referenced by AddPage(), AllocatePageUpToCapacityForTesting(), FinishShrinking(), RemovePage(), RemovePageFromSpace(), and ShouldReleaseEmptyPage().
last_lab_page_
PageMetadata* v8::internal::PagedSpaceForNewSpace::last_lab_page_ = nullptr [private]
Definition at line 588 of file new-spaces.h.
Referenced by v8::internal::PagedNewSpaceAllocatorPolicy::EnsureAllocation(), and IsPromotionCandidate().
max_capacity_
const size_t v8::internal::PagedSpaceForNewSpace::max_capacity_ [private]
Definition at line 584 of file new-spaces.h.
Referenced by FinishShrinking(), GrowToMaximumCapacityForTesting(), and PagedSpaceForNewSpace().
min_capacity_
const size_t v8::internal::PagedSpaceForNewSpace::min_capacity_ [private]
Definition at line 583 of file new-spaces.h.
Referenced by PagedSpaceForNewSpace().
target_capacity_
size_t v8::internal::PagedSpaceForNewSpace::target_capacity_ = 0 [private]
Definition at line 585 of file new-spaces.h.
Referenced by AllocatePageUpToCapacityForTesting(), FinishShrinking(), Grow(), PagedSpaceForNewSpace(), ShouldReleaseEmptyPage(), and StartShrinking().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/new-spaces.h
/mnt/V8SourceCode/src/heap/new-spaces.cc