v8::internal::AssemblerRISCVD Class Reference
#include <extension-riscv-d.h>
Public Member Functions
void fld (FPURegister rd, Register rs1, int16_t imm12)
void fsd (FPURegister source, Register base, int16_t imm12)
void fmadd_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm=RNE)
void fmsub_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm=RNE)
void fnmsub_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm=RNE)
void fnmadd_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm=RNE)
void fadd_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm=RNE)
void fsub_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm=RNE)
void fmul_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm=RNE)
void fdiv_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm=RNE)
void fsqrt_d (FPURegister rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fsgnj_d (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fsgnjn_d (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fsgnjx_d (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fmin_d (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fmax_d (FPURegister rd, FPURegister rs1, FPURegister rs2)
void fcvt_s_d (FPURegister rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fcvt_d_s (FPURegister rd, FPURegister rs1, FPURoundingMode frm=RNE)
void feq_d (Register rd, FPURegister rs1, FPURegister rs2)
void flt_d (Register rd, FPURegister rs1, FPURegister rs2)
void fle_d (Register rd, FPURegister rs1, FPURegister rs2)
void fclass_d (Register rd, FPURegister rs1)
void fcvt_w_d (Register rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fcvt_wu_d (Register rd, FPURegister rs1, FPURoundingMode frm=RNE)
void fcvt_d_w (FPURegister rd, Register rs1, FPURoundingMode frm=RNE)
void fcvt_d_wu (FPURegister rd, Register rs1, FPURoundingMode frm=RNE)
void fmv_d (FPURegister rd, FPURegister rs)
void fabs_d (FPURegister rd, FPURegister rs)
void fneg_d (FPURegister rd, FPURegister rs)
Additional Inherited Members
Detailed Description
Definition at line 15 of file extension-riscv-d.h.
Member Function Documentation
fabs_d()
void v8::internal::AssemblerRISCVD::fabs_d (FPURegister rd, FPURegister rs) [inline]
Definition at line 64 of file extension-riscv-d.h.
{ fsgnjx_d(rd, rs, rs); }
References fsgnjx_d().
fadd_d()
void v8::internal::AssemblerRISCVD::fadd_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm = RNE)
Definition at line 38 of file extension-riscv-d.cc.
                                                  {
  GenInstrALUFP_rr(0b0000001, frm, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fclass_d()
void v8::internal::AssemblerRISCVD::fclass_d (Register rd, FPURegister rs1)
Definition at line 108 of file extension-riscv-d.cc.
                                                           {
  GenInstrALUFP_rr(0b1110001, 0b001, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fcvt_d_s()
void v8::internal::AssemblerRISCVD::fcvt_d_s (FPURegister rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 91 of file extension-riscv-d.cc.
                                                    {
  GenInstrALUFP_rr(0b0100001, frm, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fcvt_d_w()
void v8::internal::AssemblerRISCVD::fcvt_d_w (FPURegister rd, Register rs1, FPURoundingMode frm = RNE)
Definition at line 122 of file extension-riscv-d.cc.
                                                    {
  GenInstrALUFP_rr(0b1101001, frm, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by v8::internal::MacroAssembler::Cvt_d_w(), v8::internal::MacroAssembler::LoadFPRImmediate(), and v8::internal::MacroAssembler::RoundHelper().
fcvt_d_wu()
void v8::internal::AssemblerRISCVD::fcvt_d_wu (FPURegister rd, Register rs1, FPURoundingMode frm = RNE)
Definition at line 127 of file extension-riscv-d.cc.
                                                     {
  GenInstrALUFP_rr(0b1101001, frm, rd, rs1, ToRegister(1));
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr(), and v8::internal::ToRegister().
Referenced by v8::internal::MacroAssembler::Cvt_d_uw().
fcvt_s_d()
void v8::internal::AssemblerRISCVD::fcvt_s_d (FPURegister rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 86 of file extension-riscv-d.cc.
                                                    {
  GenInstrALUFP_rr(0b0100000, frm, rd, rs1, ToRegister(1));
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr(), and v8::internal::ToRegister().
fcvt_w_d()
void v8::internal::AssemblerRISCVD::fcvt_w_d (Register rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 112 of file extension-riscv-d.cc.
                                                    {
  GenInstrALUFP_rr(0b1100001, frm, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by v8::internal::MacroAssembler::Ceil_w_d(), v8::internal::MacroAssembler::Floor_w_d(), v8::internal::MacroAssembler::Round_w_d(), and v8::internal::MacroAssembler::Trunc_w_d().
fcvt_wu_d()
void v8::internal::AssemblerRISCVD::fcvt_wu_d (Register rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 117 of file extension-riscv-d.cc.
                                                     {
  GenInstrALUFP_rr(0b1100001, frm, rd, rs1, ToRegister(1));
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr(), and v8::internal::ToRegister().
Referenced by v8::internal::MacroAssembler::Trunc_uw_d().
fdiv_d()
void v8::internal::AssemblerRISCVD::fdiv_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm = RNE)
Definition at line 53 of file extension-riscv-d.cc.
                                                  {
  GenInstrALUFP_rr(0b0001101, frm, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
feq_d()
void v8::internal::AssemblerRISCVD::feq_d (Register rd, FPURegister rs1, FPURegister rs2)
Definition at line 96 of file extension-riscv-d.cc.
                                                                         {
  GenInstrALUFP_rr(0b1010001, 0b010, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by v8::internal::MacroAssembler::Clear_if_nan_d(), v8::internal::MacroAssembler::CompareF64(), and v8::internal::MacroAssembler::CompareIsNotNanF64().
fld()
void v8::internal::AssemblerRISCVD::fld (FPURegister rd, Register rs1, int16_t imm12)
Definition at line 10 of file extension-riscv-d.cc.
                                                                     {
  GenInstrLoadFP_ri(0b011, rd, rs1, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrLoadFP_ri().
fle_d()
void v8::internal::AssemblerRISCVD::fle_d (Register rd, FPURegister rs1, FPURegister rs2)
Definition at line 104 of file extension-riscv-d.cc.
                                                                         {
  GenInstrALUFP_rr(0b1010001, 0b000, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by v8::internal::MacroAssembler::CompareF64().
flt_d()
void v8::internal::AssemblerRISCVD::flt_d (Register rd, FPURegister rs1, FPURegister rs2)
Definition at line 100 of file extension-riscv-d.cc.
                                                                         {
  GenInstrALUFP_rr(0b1010001, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by v8::internal::MacroAssembler::CompareF64().
fmadd_d()
void v8::internal::AssemblerRISCVD::fmadd_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm = RNE)
Definition at line 18 of file extension-riscv-d.cc.
                                                                    {
  GenInstrR4(0b01, MADD, rd, rs1, rs2, rs3, frm);
}
References v8::internal::AssemblerRiscvBase::GenInstrR4(), and v8::internal::MADD.
fmax_d()
void v8::internal::AssemblerRISCVD::fmax_d (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 82 of file extension-riscv-d.cc.
                                                                             {
  GenInstrALUFP_rr(0b0010101, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fmin_d()
void v8::internal::AssemblerRISCVD::fmin_d (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 78 of file extension-riscv-d.cc.
                                                                             {
  GenInstrALUFP_rr(0b0010101, 0b000, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fmsub_d()
void v8::internal::AssemblerRISCVD::fmsub_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm = RNE)
Definition at line 23 of file extension-riscv-d.cc.
                                                                    {
  GenInstrR4(0b01, MSUB, rd, rs1, rs2, rs3, frm);
}
References v8::internal::AssemblerRiscvBase::GenInstrR4(), and v8::internal::MSUB.
fmul_d()
void v8::internal::AssemblerRISCVD::fmul_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm = RNE)
Definition at line 48 of file extension-riscv-d.cc.
                                                  {
  GenInstrALUFP_rr(0b0001001, frm, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fmv_d()
void v8::internal::AssemblerRISCVD::fmv_d (FPURegister rd, FPURegister rs) [inline]
Definition at line 63 of file extension-riscv-d.h.
{ fsgnj_d(rd, rs, rs); }
References fsgnj_d().
Referenced by v8::internal::MacroAssembler::FloatMinMaxHelper(), and v8::internal::MacroAssembler::LoadFPRImmediate().
fneg_d()
void v8::internal::AssemblerRISCVD::fneg_d (FPURegister rd, FPURegister rs) [inline]
Definition at line 65 of file extension-riscv-d.h.
{ fsgnjn_d(rd, rs, rs); }
References fsgnjn_d().
fnmadd_d()
void v8::internal::AssemblerRISCVD::fnmadd_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm = RNE)
Definition at line 33 of file extension-riscv-d.cc.
                                                                     {
  GenInstrR4(0b01, NMADD, rd, rs1, rs2, rs3, frm);
}
References v8::internal::AssemblerRiscvBase::GenInstrR4(), and v8::internal::NMADD.
fnmsub_d()
void v8::internal::AssemblerRISCVD::fnmsub_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURegister rs3, FPURoundingMode frm = RNE)
Definition at line 28 of file extension-riscv-d.cc.
                                                                     {
  GenInstrR4(0b01, NMSUB, rd, rs1, rs2, rs3, frm);
}
References v8::internal::AssemblerRiscvBase::GenInstrR4(), and v8::internal::NMSUB.
fsd()
void v8::internal::AssemblerRISCVD::fsd (FPURegister source, Register base, int16_t imm12)
Definition at line 14 of file extension-riscv-d.cc.
                                                                          {
  GenInstrStoreFP_rri(0b011, base, source, imm12);
}
References v8::internal::AssemblerRiscvBase::GenInstrStoreFP_rri().
Referenced by v8::internal::MacroAssembler::StoreDouble(), and v8::internal::MacroAssembler::TruncateDoubleToI().
fsgnj_d()
void v8::internal::AssemblerRISCVD::fsgnj_d (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 63 of file extension-riscv-d.cc.
                                               {
  GenInstrALUFP_rr(0b0010001, 0b000, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by fmv_d().
fsgnjn_d()
void v8::internal::AssemblerRISCVD::fsgnjn_d (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 68 of file extension-riscv-d.cc.
                                                {
  GenInstrALUFP_rr(0b0010001, 0b001, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by fneg_d().
fsgnjx_d()
void v8::internal::AssemblerRISCVD::fsgnjx_d (FPURegister rd, FPURegister rs1, FPURegister rs2)
Definition at line 73 of file extension-riscv-d.cc.
                                                {
  GenInstrALUFP_rr(0b0010001, 0b010, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
Referenced by fabs_d().
fsqrt_d()
void v8::internal::AssemblerRISCVD::fsqrt_d (FPURegister rd, FPURegister rs1, FPURoundingMode frm = RNE)
Definition at line 58 of file extension-riscv-d.cc.
                                                   {
  GenInstrALUFP_rr(0b0101101, frm, rd, rs1, zero_reg);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
fsub_d()
void v8::internal::AssemblerRISCVD::fsub_d (FPURegister rd, FPURegister rs1, FPURegister rs2, FPURoundingMode frm = RNE)
Definition at line 43 of file extension-riscv-d.cc.
                                                  {
  GenInstrALUFP_rr(0b0000101, frm, rd, rs1, rs2);
}
References v8::internal::AssemblerRiscvBase::GenInstrALUFP_rr().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-d.h
/mnt/V8SourceCode/src/codegen/riscv/extension-riscv-d.cc