v8::internal::AccessCheckInfo Class Reference
#include <api-callbacks.h>
Public Types
using BodyDescriptor = StructBodyDescriptor
Static Public Member Functions
static Tagged< AccessCheckInfo > Get (Isolate *isolate, DirectHandle< JSObject > receiver)
Detailed Description
Definition at line 94 of file api-callbacks.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::AccessCheckInfo::BodyDescriptor = StructBodyDescriptor
Definition at line 100 of file api-callbacks.h.
Member Function Documentation
Get()
Tagged< AccessCheckInfo > v8::internal::AccessCheckInfo::Get (Isolate * isolate, DirectHandle< JSObject > receiver) [static]
Definition at line 6629 of file objects.cc.
                                                                              {
  DisallowGarbageCollection no_gc;
  DCHECK(receiver->map()->is_access_check_needed());
  Tagged<Object> maybe_constructor = receiver->map()->GetConstructor();
  if (IsFunctionTemplateInfo(maybe_constructor)) {
    Tagged<Object> data_obj =
        Cast<FunctionTemplateInfo>(maybe_constructor)->GetAccessCheckInfo();
    if (IsUndefined(data_obj, isolate)) return AccessCheckInfo();
    return Cast<AccessCheckInfo>(data_obj);
  }
  // Might happen for a detached context.
  if (!IsJSFunction(maybe_constructor)) return AccessCheckInfo();
  Tagged<JSFunction> constructor = Cast<JSFunction>(maybe_constructor);
  // Might happen for the debug context.
  if (!constructor->shared()->IsApiFunction()) return AccessCheckInfo();
  Tagged<Object> data_obj =
      constructor->shared()->api_func_data()->GetAccessCheckInfo();
  if (IsUndefined(data_obj, isolate)) return AccessCheckInfo();
  return Cast<AccessCheckInfo>(data_obj);
}
References v8::internal::AccessCheckInfo, v8::internal::DCHECK(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::KeyAccumulator::CollectOwnKeys(), v8::internal::LookupIterator::GetInterceptorForFailedAccessCheck(), v8::internal::Isolate::MayAccess(), and v8::internal::Isolate::ReportFailedAccessCheck().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/api-callbacks.h
/mnt/V8SourceCode/src/objects/objects.cc