v8::internal::compiler::JSLoadPropertyNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSLoadPropertyNode (Node *node)
const PropertyAccess & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1293 of file js-operator.h.
Constructor & Destructor Documentation
JSLoadPropertyNode()
constexpr v8::internal::compiler::JSLoadPropertyNode::JSLoadPropertyNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1295 of file js-operator.h.
                                                    : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSLoadProperty, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const PropertyAccess& v8::internal::compiler::JSLoadPropertyNode::Parameters () const [inline]
Definition at line 1299 of file js-operator.h.
                                           {
    return PropertyAccessOf(node()->op());
  }
References v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::PropertyAccessOf().
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadProperty(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadPropertyWithEnumeratedKey().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h