v8::internal::MarkingBarrier Class Reference
#include <marking-barrier.h>
Public Member Functions
MarkingBarrier (LocalHeap *)
~MarkingBarrier ()
void Activate (bool is_compacting, MarkingMode marking_mode)
void Deactivate ()
void PublishIfNeeded ()
void ActivateShared ()
void DeactivateShared ()
void PublishSharedIfNeeded ()
template<typename TSlot >
void Write (Tagged< HeapObject > host, TSlot slot, Tagged< HeapObject > value)
void Write (Tagged< HeapObject > host, IndirectPointerSlot slot)
void Write (Tagged< InstructionStream > host, RelocInfo *, Tagged< HeapObject > value)
void Write (Tagged< JSArrayBuffer > host, ArrayBufferExtension *)
void Write (Tagged< DescriptorArray >, int number_of_own_descriptors)
void WriteWithoutHost (Tagged< HeapObject > value)
void MarkValue (Tagged< HeapObject > host, Tagged< HeapObject > value)
bool is_minor () const
bool is_not_major () const
Heap * heap () const
Static Public Member Functions
static void ActivateAll (Heap *heap, bool is_compacting)
static void DeactivateAll (Heap *heap)
static V8_EXPORT_PRIVATE void PublishAll (Heap *heap)
static void ActivateYoung (Heap *heap)
static void DeactivateYoung (Heap *heap)
static V8_EXPORT_PRIVATE void PublishYoung (Heap *heap)
Private Member Functions
void MarkValueShared (Tagged< HeapObject > value)
void MarkValueLocal (Tagged< HeapObject > value)
void RecordRelocSlot (Tagged< InstructionStream > host, RelocInfo *rinfo, Tagged< HeapObject > target)
bool IsCurrentMarkingBarrier (Tagged< HeapObject > verification_candidate)
template<typename TSlot >
void MarkRange (Tagged< HeapObject > value, TSlot start, TSlot end)
bool IsCompacting (Tagged< HeapObject > object) const
bool is_major () const
Isolate * isolate () const
Private Attributes
Heap * heap_
MarkCompactCollector * major_collector_
MinorMarkSweepCollector * minor_collector_
IncrementalMarking * incremental_marking_
std::unique_ptr< MarkingWorklists::Local > current_worklists_
std::optional< MarkingWorklists::Local > shared_heap_worklists_
MarkingState marking_state_
std::unordered_map< MutablePageMetadata *, std::unique_ptr< TypedSlots >, base::hash< MutablePageMetadata * > > typed_slots_map_
bool is_compacting_ = false
bool is_activated_ = false
const bool is_main_thread_barrier_
const bool uses_shared_heap_
const bool is_shared_space_isolate_
MarkingMode marking_mode_ = MarkingMode::kNoMarking
Detailed Description
Definition at line 26 of file marking-barrier.h.
Constructor & Destructor Documentation
MarkingBarrier()
v8::internal::MarkingBarrier::MarkingBarrier (LocalHeap * local_heap) [explicit]
Definition at line 32 of file marking-barrier.cc.
    : heap_(local_heap->heap()),
      major_collector_(heap_->mark_compact_collector()),
      minor_collector_(heap_->minor_mark_sweep_collector()),
      incremental_marking_(heap_->incremental_marking()),
      marking_state_(isolate()),
      is_main_thread_barrier_(local_heap->is_main_thread()),
      uses_shared_heap_(isolate()->has_shared_space()),
      is_shared_space_isolate_(isolate()->is_shared_space_isolate()) {}
 MarkingBarrier()
v8::internal::MarkingBarrier::~MarkingBarrier ()
Definition at line 42 of file marking-barrier.cc.
{ DCHECK(typed_slots_map_.empty()); }
References v8::internal::DCHECK(), and typed_slots_map_.
Member Function Documentation
Activate()
void v8::internal::MarkingBarrier::Activate (bool is_compacting, MarkingMode marking_mode)
Definition at line 345 of file marking-barrier.cc.
                                                                          {
  DCHECK(!is_activated_);
  is_compacting_ = is_compacting;
  marking_mode_ = marking_mode;
  current_worklists_ = std::make_unique<MarkingWorklists::Local>(
      is_minor() ? minor_collector_->marking_worklists()
                 : major_collector_->marking_worklists());
  is_activated_ = true;
}
References current_worklists_, v8::internal::DCHECK(), is_activated_, is_compacting_, is_minor(), major_collector_, marking_mode_, v8::internal::MarkCompactCollector::marking_worklists(), v8::internal::MinorMarkSweepCollector::marking_worklists(), and minor_collector_.
Referenced by ActivateAll(), and ActivateYoung().
ActivateAll()
void v8::internal::MarkingBarrier::ActivateAll (Heap * heap, bool is_compacting) [static]
Definition at line 312 of file marking-barrier.cc.
                                                               {
  ActivateSpaces(heap, MarkingMode::kMajorMarking);
  heap->safepoint()->IterateLocalHeaps([is_compacting](LocalHeap* local_heap) {
    local_heap->marking_barrier()->Activate(is_compacting,
                                            MarkingMode::kMajorMarking);
  });
  if (heap->isolate()->is_shared_space_isolate()) {
    heap->isolate()
        ->shared_space_isolate()
        ->global_safepoint()
        ->IterateClientIsolates([](Isolate* client) {
          // Force the RecordWrite builtin into the incremental marking code
          // path.
          client->heap()->SetIsMarkingFlag(true);
          client->heap()->safepoint()->IterateLocalHeaps(
              [](LocalHeap* local_heap) {
                local_heap->marking_barrier()->ActivateShared();
              });
        });
  }
}
References Activate(), ActivateShared(), v8::internal::anonymous_namespace{marking-barrier.cc}::ActivateSpaces(), v8::internal::Isolate::heap(), v8::internal::kMajorMarking, and v8::internal::LocalHeap::marking_barrier().
Referenced by v8::internal::IncrementalMarking::StartMarkingMajor().
ActivateShared()
void v8::internal::MarkingBarrier::ActivateShared ()
Definition at line 355 of file marking-barrier.cc.
                                    {
  DCHECK(!shared_heap_worklists_.has_value());
  Isolate* shared_isolate = isolate()->shared_space_isolate();
  shared_heap_worklists_.emplace(
      shared_isolate->heap()->mark_compact_collector()->marking_worklists());
}
References v8::internal::DCHECK(), v8::internal::Isolate::heap(), isolate(), v8::internal::Heap::mark_compact_collector(), v8::internal::MarkCompactCollector::marking_worklists(), shared_heap_worklists_, and v8::internal::Isolate::shared_space_isolate().
Referenced by ActivateAll().
ActivateYoung()
void v8::internal::MarkingBarrier::ActivateYoung (Heap * heap) [static]
Definition at line 337 of file marking-barrier.cc.
                                             {
  ActivateSpaces(heap, MarkingMode::kMinorMarking);
  heap->safepoint()->IterateLocalHeaps([](LocalHeap* local_heap) {
    local_heap->marking_barrier()->Activate(false, MarkingMode::kMinorMarking);
  });
}
References Activate(), v8::internal::anonymous_namespace{marking-barrier.cc}::ActivateSpaces(), v8::internal::kMinorMarking, and v8::internal::LocalHeap::marking_barrier().
Referenced by v8::internal::IncrementalMarking::StartMarkingMinor().
Deactivate()
void v8::internal::MarkingBarrier::Deactivate ()
Definition at line 398 of file marking-barrier.cc.
                                {
  DCHECK(is_activated_);
  is_activated_ = false;
  is_compacting_ = false;
  marking_mode_ = MarkingMode::kNoMarking;
  DCHECK(typed_slots_map_.empty());
  DCHECK(current_worklists_->IsEmpty());
  current_worklists_.reset();
}
References current_worklists_, v8::internal::DCHECK(), is_activated_, is_compacting_, v8::internal::kNoMarking, marking_mode_, and typed_slots_map_.
Referenced by DeactivateAll(), and DeactivateYoung().
DeactivateAll()
void v8::internal::MarkingBarrier::DeactivateAll (Heap * heap) [static]
Definition at line 363 of file marking-barrier.cc.
                                             {
  DeactivateSpaces(heap, MarkingMode::kMajorMarking);
  heap->safepoint()->IterateLocalHeaps([](LocalHeap* local_heap) {
    local_heap->marking_barrier()->Deactivate();
  });
  if (heap->isolate()->is_shared_space_isolate()) {
    heap->isolate()
        ->shared_space_isolate()
        ->global_safepoint()
        ->IterateClientIsolates([](Isolate* client) {
          // We can't just simply disable the marking barrier for all clients. A
          // client may still need it to be set for incremental marking in the
          // local heap.
          const bool is_marking =
              client->heap()->incremental_marking()->IsMarking();
          client->heap()->SetIsMarkingFlag(is_marking);
          client->heap()->safepoint()->IterateLocalHeaps(
              [](LocalHeap* local_heap) {
                local_heap->marking_barrier()->DeactivateShared();
              });
        });
  }
}
References Deactivate(), DeactivateShared(), v8::internal::anonymous_namespace{marking-barrier.cc}::DeactivateSpaces(), v8::internal::Isolate::heap(), v8::internal::kMajorMarking, and v8::internal::LocalHeap::marking_barrier().
DeactivateShared()
void v8::internal::MarkingBarrier::DeactivateShared ()
Definition at line 408 of file marking-barrier.cc.
                                      {
  DCHECK(shared_heap_worklists_->IsEmpty());
  shared_heap_worklists_.reset();
}
References v8::internal::DCHECK(), and shared_heap_worklists_.
Referenced by DeactivateAll().
DeactivateYoung()
void v8::internal::MarkingBarrier::DeactivateYoung (Heap * heap) [static]
Definition at line 390 of file marking-barrier.cc.
                                               {
  DeactivateSpaces(heap, MarkingMode::kMinorMarking);
  heap->safepoint()->IterateLocalHeaps([](LocalHeap* local_heap) {
    local_heap->marking_barrier()->Deactivate();
  });
}
References Deactivate(), v8::internal::anonymous_namespace{marking-barrier.cc}::DeactivateSpaces(), v8::internal::kMinorMarking, and v8::internal::LocalHeap::marking_barrier().
Referenced by v8::internal::MinorMarkSweepCollector::MarkLiveObjects().
heap()
Heap* v8::internal::MarkingBarrier::heap () const [inline]
Definition at line 72 of file marking-barrier.h.
{ return heap_; }
References heap_.
Referenced by v8::internal::WriteBarrier::ForCppHeapPointer(), v8::internal::WriteBarrier::IndirectPointerMarkingFromCode(), v8::internal::WriteBarrier::MarkingFromCode(), v8::internal::WriteBarrier::MarkingSlow(), v8::internal::WriteBarrier::MarkingSlowFromCppHeapWrappable(), and v8::internal::WriteBarrier::SharedMarkingFromCode().
is_major()
bool v8::internal::MarkingBarrier::is_major () const [inline], [private]
Definition at line 94 of file marking-barrier.h.
{ return marking_mode_ == MarkingMode::kMajorMarking; }
References v8::internal::kMajorMarking, and marking_mode_.
Referenced by IsCompacting(), and Write().
is_minor()
bool v8::internal::MarkingBarrier::is_minor () const [inline]
Definition at line 60 of file marking-barrier.h.
{ return marking_mode_ == MarkingMode::kMinorMarking; }
References v8::internal::kMinorMarking, and marking_mode_.
Referenced by Activate(), v8::internal::WriteBarrier::ForCppHeapPointer(), v8::internal::WriteBarrier::MarkingSlow(), MarkValueLocal(), and Write().
is_not_major()
bool v8::internal::MarkingBarrier::is_not_major () const [inline]
Definition at line 62 of file marking-barrier.h.
                            {
    switch (marking_mode_) {
      case MarkingMode::kMajorMarking:
        return false;
      case MarkingMode::kNoMarking:
      case MarkingMode::kMinorMarking:
        return true;
    }
  }
References v8::internal::kMajorMarking, v8::internal::kMinorMarking, v8::internal::kNoMarking, and marking_mode_.
IsCompacting()
bool v8::internal::MarkingBarrier::IsCompacting (Tagged< HeapObject > object) const [inline], [private]
Definition at line 133 of file marking-barrier-inl.h.
                                                                 {
  if (is_compacting_) {
    DCHECK(is_major());
    return true;
  }
  return shared_heap_worklists_.has_value() &&
         HeapLayout::InWritableSharedSpace(object);
}
References v8::internal::DCHECK(), v8::internal::HeapLayout::InWritableSharedSpace(), is_compacting_, is_major(), and shared_heap_worklists_.
Referenced by MarkRange(), and Write().
IsCurrentMarkingBarrier()
bool v8::internal::MarkingBarrier::IsCurrentMarkingBarrier (Tagged< HeapObject > verification_candidate) [private]
Definition at line 461 of file marking-barrier.cc.
                                               {
  return WriteBarrier::CurrentMarkingBarrier(verification_candidate) == this;
}
References v8::internal::WriteBarrier::CurrentMarkingBarrier().
Referenced by MarkValue(), RecordRelocSlot(), and Write().
isolate()
Isolate * v8::internal::MarkingBarrier::isolate () const [private]
Definition at line 466 of file marking-barrier.cc.
{ return heap_->isolate(); }
References heap_, and v8::internal::Heap::isolate().
Referenced by ActivateShared(), MarkRange(), and Write().
MarkRange()
template<typename TSlot >
void v8::internal::MarkingBarrier::MarkRange (Tagged< HeapObject > value, TSlot start, TSlot end) [inline], [private]
Definition at line 114 of file marking-barrier-inl.h.
                                                 {
  auto* isolate = heap_->isolate();
  const bool record_slots =
      IsCompacting(host) &&
      !MemoryChunk::FromHeapObject(host)->ShouldSkipEvacuationSlotRecording();
  for (TSlot slot = start; slot < end; ++slot) {
    typename TSlot::TObject object = slot.Relaxed_Load();
    Tagged<HeapObject> heap_object;
    // Mark both, weak and strong edges.
    if (object.GetHeapObject(isolate, &heap_object)) {
      MarkValue(host, heap_object);
      if (record_slots) {
        major_collector_->RecordSlot(host, HeapObjectSlot(slot), heap_object);
      }
    }
  }
}
References v8::internal::compiler::end(), v8::internal::MemoryChunk::FromHeapObject(), heap_, IsCompacting(), v8::internal::Heap::isolate(), isolate(), major_collector_, MarkValue(), v8::internal::MarkCompactCollector::RecordSlot(), and v8::internal::MemoryChunk::ShouldSkipEvacuationSlotRecording().
MarkValue()
void v8::internal::MarkingBarrier::MarkValue (Tagged< HeapObject > host, Tagged< HeapObject > value) [inline]
Definition at line 34 of file marking-barrier-inl.h.
                                                         {
  if (HeapLayout::InReadOnlySpace(value)) return;
  DCHECK(IsCurrentMarkingBarrier(host));
  DCHECK(is_activated_ || shared_heap_worklists_.has_value());
  // When shared heap isn't enabled all objects are local, we can just run the
  // local marking barrier. Also from the point-of-view of the shared space
  // isolate (= main isolate) also shared objects are considered local.
  if (V8_UNLIKELY(uses_shared_heap_) && !is_shared_space_isolate_) {
    // Check whether incremental marking is enabled for that object's space.
    if (!MemoryChunk::FromHeapObject(host)->IsMarking()) {
      return;
    }
    if (v8_flags.black_allocated_pages &&
        HeapLayout::InBlackAllocatedPage(value)) {
      return;
    }
    if (HeapLayout::InWritableSharedSpace(host)) {
      // Invoking shared marking barrier when storing into shared objects.
      MarkValueShared(value);
      return;
    } else if (HeapLayout::InWritableSharedSpace(value)) {
      // No marking needed when storing shared objects in local objects.
      return;
    }
  }
  DCHECK_IMPLIES(HeapLayout::InWritableSharedSpace(host),
                 is_shared_space_isolate_);
  DCHECK_IMPLIES(HeapLayout::InWritableSharedSpace(value),
                 is_shared_space_isolate_);
  DCHECK(is_activated_);
  MarkValueLocal(value);
}
References v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::MemoryChunk::FromHeapObject(), v8::internal::HeapLayout::InBlackAllocatedPage(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::HeapLayout::InWritableSharedSpace(), is_activated_, is_shared_space_isolate_, IsCurrentMarkingBarrier(), MarkValueLocal(), MarkValueShared(), shared_heap_worklists_, uses_shared_heap_, v8::internal::v8_flags, V8_UNLIKELY, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{heap-write-barrier.cc}::ForRangeImpl(), v8::internal::WriteBarrier::MarkingSlow(), MarkRange(), and Write().
MarkValueLocal()
void v8::internal::MarkingBarrier::MarkValueLocal (Tagged< HeapObject > value) [inline], [private]
Definition at line 88 of file marking-barrier-inl.h.
                                                            {
  DCHECK(!HeapLayout::InReadOnlySpace(value));
  if (is_minor()) {
    // We do not need to insert into RememberedSet<OLD_TO_NEW> here because the
    // C++ marking barrier already does this for us.
    // TODO(v8:13012): Consider updating C++ barriers to respect
    // POINTERS_TO_HERE_ARE_INTERESTING and POINTERS_FROM_HERE_ARE_INTERESTING
    // page flags and make the following branch a DCHECK.
    if (HeapLayout::InYoungGeneration(value)) {
      MarkingHelper::TryMarkAndPush(
          heap_, current_worklists_.get(), &marking_state_,
          MarkingHelper::WorklistTarget::kRegular, value);
    }
  } else {
    // At this point `ShouldMarkObject()` should always succeed here because
    // value has gone through all the necessary filters. However, we do want to
    // push to the right target worklist immediately.
    const auto target_worklist = MarkingHelper::ShouldMarkObject(heap_, value);
    if (!target_worklist) return;
    MarkingHelper::TryMarkAndPush(heap_, current_worklists_.get(),
                                  &marking_state_, target_worklist.value(),
                                  value);
  }
}
References current_worklists_, v8::internal::DCHECK(), heap_, v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::HeapLayout::InYoungGeneration(), is_minor(), v8::internal::MarkingHelper::kRegular, marking_state_, v8::internal::MarkingHelper::ShouldMarkObject(), v8::internal::MarkingHelper::TryMarkAndPush(), and v8::internal::value.
Referenced by MarkValue(), Write(), and WriteWithoutHost().
MarkValueShared()
void v8::internal::MarkingBarrier::MarkValueShared (Tagged< HeapObject > value) [inline], [private]
Definition at line 74 of file marking-barrier-inl.h.
                                                             {
  // Value is either in read-only space or shared heap.
  DCHECK(HeapLayout::InAnySharedSpace(value));
  // We should only reach this on client isolates (= worker isolates).
  DCHECK(!is_shared_space_isolate_);
  DCHECK(shared_heap_worklists_.has_value());
  // Mark shared object and push it onto shared heap worklist.
  if (marking_state_.TryMark(value)) {
    shared_heap_worklists_->Push(value);
  }
}
References v8::internal::DCHECK(), v8::internal::HeapLayout::InAnySharedSpace(), is_shared_space_isolate_, marking_state_, shared_heap_worklists_, v8::internal::MarkingStateBase< ConcreteState, access_mode >::TryMark(), and v8::internal::value.
Referenced by MarkValue(), and Write().
PublishAll()
void v8::internal::MarkingBarrier::PublishAll (Heap * heap) [static]
Definition at line 414 of file marking-barrier.cc.
                                          {
  heap->safepoint()->IterateLocalHeaps([](LocalHeap* local_heap) {
    local_heap->marking_barrier()->PublishIfNeeded();
  });
  if (heap->isolate()->is_shared_space_isolate()) {
    heap->isolate()
        ->shared_space_isolate()
        ->global_safepoint()
        ->IterateClientIsolates([](Isolate* client) {
          client->heap()->safepoint()->IterateLocalHeaps(
              [](LocalHeap* local_heap) {
                local_heap->marking_barrier()->PublishSharedIfNeeded();
              });
        });
  }
}
References v8::internal::Isolate::heap(), v8::internal::LocalHeap::marking_barrier(), PublishIfNeeded(), and PublishSharedIfNeeded().
PublishIfNeeded()
void v8::internal::MarkingBarrier::PublishIfNeeded ()
Definition at line 439 of file marking-barrier.cc.
                                     {
  if (is_activated_) {
    current_worklists_->Publish();
    for (auto& it : typed_slots_map_) {
      MutablePageMetadata* memory_chunk = it.first;
      // Access to TypeSlots need to be protected, since LocalHeaps might
      // publish code in the background thread.
      base::MutexGuard guard(memory_chunk->mutex());
      std::unique_ptr<TypedSlots>& typed_slots = it.second;
      RememberedSet<OLD_TO_OLD>::MergeTyped(memory_chunk,
                                            std::move(typed_slots));
    }
    typed_slots_map_.clear();
  }
}
References current_worklists_, is_activated_, v8::internal::RememberedSet< type >::MergeTyped(), v8::internal::MutablePageMetadata::mutex(), and typed_slots_map_.
Referenced by PublishAll(), PublishYoung(), v8::internal::MarkCompactCollector::TearDown(), and v8::internal::MinorMarkSweepCollector::TearDown().
PublishSharedIfNeeded()
void v8::internal::MarkingBarrier::PublishSharedIfNeeded ()
Definition at line 455 of file marking-barrier.cc.
                                           {
  if (shared_heap_worklists_) {
    shared_heap_worklists_->Publish();
  }
}
References shared_heap_worklists_.
Referenced by PublishAll(), and v8::internal::Heap::TearDownWithSharedHeap().
PublishYoung()
void v8::internal::MarkingBarrier::PublishYoung (Heap * heap) [static]
Definition at line 433 of file marking-barrier.cc.
                                            {
  heap->safepoint()->IterateLocalHeaps([](LocalHeap* local_heap) {
    local_heap->marking_barrier()->PublishIfNeeded();
  });
}
References v8::internal::LocalHeap::marking_barrier(), and PublishIfNeeded().
Referenced by v8::internal::MinorMarkSweepCollector::MarkLiveObjects().
RecordRelocSlot()
void v8::internal::MarkingBarrier::RecordRelocSlot (Tagged< InstructionStream > host, RelocInfo * rinfo, Tagged< HeapObject > target) [private]
Definition at line 199 of file marking-barrier.cc.
                                                                {
  DCHECK(IsCurrentMarkingBarrier(host));
  if (!MarkCompactCollector::ShouldRecordRelocSlot(host, rinfo, target)) return;
  MarkCompactCollector::RecordRelocSlotInfo info =
      MarkCompactCollector::ProcessRelocInfo(host, rinfo, target);
  auto& typed_slots = typed_slots_map_[info.page_metadata];
  if (!typed_slots) {
    typed_slots.reset(new TypedSlots());
  }
  typed_slots->Insert(info.slot_type, info.offset);
}
References v8::internal::DCHECK(), IsCurrentMarkingBarrier(), v8::internal::MarkCompactCollector::RecordRelocSlotInfo::offset, v8::internal::MarkCompactCollector::RecordRelocSlotInfo::page_metadata, v8::internal::MarkCompactCollector::ProcessRelocInfo(), v8::internal::MarkCompactCollector::ShouldRecordRelocSlot(), v8::internal::MarkCompactCollector::RecordRelocSlotInfo::slot_type, and typed_slots_map_.
Referenced by Write().
Write() [1/5]
void v8::internal::MarkingBarrier::Write (Tagged< DescriptorArray > descriptor_array, int number_of_own_descriptors)
Definition at line 143 of file marking-barrier.cc.
                                                          {
  DCHECK(IsCurrentMarkingBarrier(descriptor_array));
  DCHECK(HeapLayout::InReadOnlySpace(descriptor_array->map()));
  DCHECK(MemoryChunk::FromHeapObject(descriptor_array)->IsMarking());
  // Only major GC uses custom liveness.
  if (is_minor() || IsStrongDescriptorArray(descriptor_array)) {
    MarkValueLocal(descriptor_array);
    return;
  }
  unsigned gc_epoch;
  MarkingWorklists::Local* worklist;
  if (V8_UNLIKELY(uses_shared_heap_) &&
      HeapLayout::InWritableSharedSpace(descriptor_array) &&
      !is_shared_space_isolate_) {
    gc_epoch = isolate()
                   ->shared_space_isolate()
                   ->heap()
                   ->mark_compact_collector()
                   ->epoch();
    DCHECK(shared_heap_worklists_.has_value());
    worklist = &*shared_heap_worklists_;
  } else {
#ifdef DEBUG
    if (const auto target_worklist =
            MarkingHelper::ShouldMarkObject(heap_, descriptor_array)) {
      DCHECK_EQ(target_worklist.value(),
                MarkingHelper::WorklistTarget::kRegular);
    } else {
      DCHECK(HeapLayout::InBlackAllocatedPage(descriptor_array));
    }
#endif // DEBUG
    gc_epoch = major_collector_->epoch();
    worklist = current_worklists_.get();
  }
  if (v8_flags.black_allocated_pages) {
    // Make sure to only mark the descriptor array for non black allocated
    // pages. The atomic pause will fix it afterwards.
    if (MarkingHelper::ShouldMarkObject(heap_, descriptor_array)) {
      marking_state_.TryMark(descriptor_array);
    }
  } else {
    marking_state_.TryMark(descriptor_array);
  }
  // `TryUpdateIndicesToMark()` acts as a barrier that publishes the slots'
  // values corresponding to `number_of_own_descriptors`.
  if (DescriptorArrayMarkingState::TryUpdateIndicesToMark(
          gc_epoch, descriptor_array, number_of_own_descriptors)) {
    worklist->Push(descriptor_array);
  }
}
References current_worklists_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MarkCompactCollector::epoch(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::Isolate::heap(), heap_, v8::internal::HeapLayout::InBlackAllocatedPage(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::HeapLayout::InWritableSharedSpace(), is_minor(), is_shared_space_isolate_, IsCurrentMarkingBarrier(), isolate(), v8::internal::MarkingHelper::kRegular, v8::internal::MarkingWorklists::Local(), major_collector_, v8::internal::Heap::mark_compact_collector(), marking_state_, MarkValueLocal(), shared_heap_worklists_, v8::internal::Isolate::shared_space_isolate(), v8::internal::MarkingHelper::ShouldMarkObject(), v8::internal::MarkingStateBase< ConcreteState, access_mode >::TryMark(), v8::internal::DescriptorArrayMarkingState::TryUpdateIndicesToMark(), uses_shared_heap_, v8::internal::v8_flags, and V8_UNLIKELY.
Write() [2/5]
void v8::internal::MarkingBarrier::Write (Tagged< HeapObject > host, IndirectPointerSlot slot)
Definition at line 44 of file marking-barrier.cc.
                                                                            {
#ifdef V8_ENABLE_SANDBOX
  DCHECK(IsCurrentMarkingBarrier(host));
  DCHECK(is_activated_ || shared_heap_worklists_.has_value());
  DCHECK(MemoryChunk::FromHeapObject(host)->IsMarking());
  // An indirect pointer slot can only contain a Smi if it is uninitialized (in
  // which case the vaue will be Smi::zero()). However, at this point the slot
  // must have been initialized because it was just written to.
  Tagged<HeapObject> value = Cast<HeapObject>(slot.load(isolate()));
  // If the host is in shared space, the target must be in the shared trusted
  // space. No other edges indirect pointers are currently possible in shared
  // space.
  DCHECK_IMPLIES(
      HeapLayout::InWritableSharedSpace(host),
      MemoryChunk::FromHeapObject(value)->Metadata()->owner()->identity() ==
          SHARED_TRUSTED_SPACE);
  if (HeapLayout::InReadOnlySpace(value)) return;
  DCHECK(!HeapLayout::InYoungGeneration(value));
  if (V8_UNLIKELY(uses_shared_heap_) && !is_shared_space_isolate_) {
    if (HeapLayout::InWritableSharedSpace(value)) {
      // References to the shared trusted space may only originate from the
      // shared space.
      CHECK(HeapLayout::InWritableSharedSpace(host));
      DCHECK(MemoryChunk::FromHeapObject(value)->IsTrusted());
      MarkValueShared(value);
    } else {
      MarkValueLocal(value);
    }
  } else {
    MarkValueLocal(value);
  }
  // We don't need to record a slot here because the entries in the pointer
  // tables are not compacted and because the pointers stored in the table
  // entries are updated after compacting GC.
  static_assert(!CodePointerTable::kSupportsCompaction);
  static_assert(!TrustedPointerTable::kSupportsCompaction);
#else
  UNREACHABLE();
#endif
}
References CHECK, v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::MemoryChunk::FromHeapObject(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::HeapLayout::InYoungGeneration(), is_activated_, is_shared_space_isolate_, IsCurrentMarkingBarrier(), isolate(), v8::internal::IndirectPointerSlot::load(), MarkValueLocal(), MarkValueShared(), shared_heap_worklists_, v8::internal::SHARED_TRUSTED_SPACE, v8::internal::UNREACHABLE(), uses_shared_heap_, V8_UNLIKELY, and v8::internal::value.
Write() [3/5]
template<typename TSlot >
void v8::internal::MarkingBarrier::Write (Tagged< HeapObject > host, TSlot slot, Tagged< HeapObject > value)
Definition at line 21 of file marking-barrier-inl.h.
                                                     {
  DCHECK(IsCurrentMarkingBarrier(host));
  DCHECK(is_activated_ || shared_heap_worklists_.has_value());
  DCHECK(MemoryChunk::FromHeapObject(host)->IsMarking());
  MarkValue(host, value);
  if (slot.address() && IsCompacting(host)) {
    MarkCompactCollector::RecordSlot(host, slot, value);
  }
}
References v8::internal::DCHECK(), v8::internal::MemoryChunk::FromHeapObject(), is_activated_, IsCompacting(), IsCurrentMarkingBarrier(), MarkValue(), v8::internal::MarkCompactCollector::RecordSlot(), shared_heap_worklists_, and v8::internal::value.
Referenced by v8::internal::WriteBarrier::MarkingSlow().
Write() [4/5]
void v8::internal::MarkingBarrier::Write (Tagged< InstructionStream > host, RelocInfo * reloc_info, Tagged< HeapObject > value)
Definition at line 107 of file marking-barrier.cc.
                                                                            {
  DCHECK(IsCurrentMarkingBarrier(host));
  DCHECK(!HeapLayout::InWritableSharedSpace(host));
  DCHECK(is_activated_ || shared_heap_worklists_.has_value());
  DCHECK(MemoryChunk::FromHeapObject(host)->IsMarking());
  MarkValue(host, value);
  if (is_compacting_) {
    DCHECK(is_major());
    if (is_main_thread_barrier_) {
      // An optimization to avoid allocating additional typed slots for the
      // main thread.
      major_collector_->RecordRelocSlot(host, reloc_info, value);
    } else {
      RecordRelocSlot(host, reloc_info, value);
    }
  }
}
References v8::internal::DCHECK(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::HeapLayout::InWritableSharedSpace(), is_activated_, is_compacting_, is_main_thread_barrier_, is_major(), IsCurrentMarkingBarrier(), major_collector_, MarkValue(), v8::internal::MarkCompactCollector::RecordRelocSlot(), RecordRelocSlot(), shared_heap_worklists_, and v8::internal::value.
Write() [5/5]
void v8::internal::MarkingBarrier::Write (Tagged< JSArrayBuffer > host, ArrayBufferExtension * extension)
Definition at line 128 of file marking-barrier.cc.
                                                            {
  DCHECK(IsCurrentMarkingBarrier(host));
  DCHECK(!HeapLayout::InWritableSharedSpace(host));
  DCHECK(MemoryChunk::FromHeapObject(host)->IsMarking());
  if (is_minor()) {
    if (HeapLayout::InYoungGeneration(host)) {
      extension->YoungMark();
    }
  } else {
    extension->Mark();
  }
}
References v8::internal::DCHECK(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::HeapLayout::InYoungGeneration(), is_minor(), IsCurrentMarkingBarrier(), v8::internal::ArrayBufferExtension::Mark(), and v8::internal::ArrayBufferExtension::YoungMark().
WriteWithoutHost()
void v8::internal::MarkingBarrier::WriteWithoutHost (Tagged< HeapObject > value)
Definition at line 91 of file marking-barrier.cc.
                                                              {
  DCHECK(is_main_thread_barrier_);
  DCHECK(is_activated_);
  // Without a shared heap and on the shared space isolate (= main isolate) all
  // objects are considered local.
  if (V8_UNLIKELY(uses_shared_heap_) && !is_shared_space_isolate_) {
    // On client isolates (= worker isolates) shared values can be ignored.
    if (HeapLayout::InWritableSharedSpace(value)) {
      return;
    }
  }
  if (HeapLayout::InReadOnlySpace(value)) return;
  MarkValueLocal(value);
}
References v8::internal::DCHECK(), v8::internal::HeapLayout::InReadOnlySpace(), v8::internal::HeapLayout::InWritableSharedSpace(), is_activated_, is_main_thread_barrier_, is_shared_space_isolate_, MarkValueLocal(), uses_shared_heap_, V8_UNLIKELY, and v8::internal::value.
Referenced by v8::internal::WriteBarrier::MarkingSlowFromTracedHandle().
Member Data Documentation
current_worklists_
std::unique_ptr<MarkingWorklists::Local> v8::internal::MarkingBarrier::current_worklists_ [private]
Definition at line 102 of file marking-barrier.h.
Referenced by Activate(), Deactivate(), MarkValueLocal(), PublishIfNeeded(), and Write().
heap_
Heap* v8::internal::MarkingBarrier::heap_ [private]
Definition at line 98 of file marking-barrier.h.
Referenced by heap(), isolate(), MarkRange(), MarkValueLocal(), and Write().
incremental_marking_
IncrementalMarking* v8::internal::MarkingBarrier::incremental_marking_ [private]
Definition at line 101 of file marking-barrier.h.
is_activated_
bool v8::internal::MarkingBarrier::is_activated_ = false [private]
Definition at line 109 of file marking-barrier.h.
Referenced by Activate(), Deactivate(), MarkValue(), PublishIfNeeded(), Write(), and WriteWithoutHost().
is_compacting_
bool v8::internal::MarkingBarrier::is_compacting_ = false [private]
Definition at line 108 of file marking-barrier.h.
Referenced by Activate(), Deactivate(), IsCompacting(), and Write().
is_main_thread_barrier_
const bool v8::internal::MarkingBarrier::is_main_thread_barrier_ [private]
Definition at line 110 of file marking-barrier.h.
Referenced by Write(), and WriteWithoutHost().
is_shared_space_isolate_
const bool v8::internal::MarkingBarrier::is_shared_space_isolate_ [private]
Definition at line 112 of file marking-barrier.h.
Referenced by MarkValue(), MarkValueShared(), Write(), and WriteWithoutHost().
major_collector_
MarkCompactCollector* v8::internal::MarkingBarrier::major_collector_ [private]
Definition at line 99 of file marking-barrier.h.
Referenced by Activate(), MarkRange(), and Write().
marking_mode_
MarkingMode v8::internal::MarkingBarrier::marking_mode_ = MarkingMode::kNoMarking [private]
Definition at line 113 of file marking-barrier.h.
Referenced by Activate(), Deactivate(), is_major(), is_minor(), and is_not_major().
marking_state_
MarkingState v8::internal::MarkingBarrier::marking_state_ [private]
Definition at line 104 of file marking-barrier.h.
Referenced by MarkValueLocal(), MarkValueShared(), and Write().
minor_collector_
MinorMarkSweepCollector* v8::internal::MarkingBarrier::minor_collector_ [private]
Definition at line 100 of file marking-barrier.h.
Referenced by Activate().
shared_heap_worklists_
std::optional<MarkingWorklists::Local> v8::internal::MarkingBarrier::shared_heap_worklists_ [private]
Definition at line 103 of file marking-barrier.h.
Referenced by ActivateShared(), DeactivateShared(), IsCompacting(), MarkValue(), MarkValueShared(), PublishSharedIfNeeded(), and Write().
typed_slots_map_
std::unordered_map<MutablePageMetadata*, std::unique_ptr<TypedSlots>, base::hash<MutablePageMetadata*> > v8::internal::MarkingBarrier::typed_slots_map_ [private]
Definition at line 107 of file marking-barrier.h.
Referenced by Deactivate(), PublishIfNeeded(), RecordRelocSlot(), and ~MarkingBarrier().
uses_shared_heap_
const bool v8::internal::MarkingBarrier::uses_shared_heap_ [private]
Definition at line 111 of file marking-barrier.h.
Referenced by MarkValue(), Write(), and WriteWithoutHost().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/marking-barrier.h
/mnt/V8SourceCode/src/heap/marking-barrier-inl.h
/mnt/V8SourceCode/src/heap/marking-barrier.cc