v8::internal::JSDataObjectBuilder Class Reference
Public Types
enum HeapNumberMode { kNormalHeapNumbers
, kHeapNumbersGuaranteedUniquelyOwned
 }
Public Member Functions
JSDataObjectBuilder (Isolate *isolate, ElementsKind elements_kind, int expected_named_properties, DirectHandle< Map > expected_final_map, HeapNumberMode heap_number_mode)
template<typename PropertyIterator >
Handle< JSObject > BuildFromIterator (PropertyIterator &&it, MaybeHandle< FixedArrayBase > maybe_elements={})
template<typename Char , typename GetKeyFunction , typename GetValueFunction >
bool TryAddFastPropertyForValue (base::Vector< const Char > key_chars, GetKeyFunction &&get_key, GetValueFunction &&get_value)
template<typename ValueIterator >
void CreateAndInitialiseObject (ValueIterator value_it, DirectHandle< FixedArrayBase > elements)
void AddSlowProperty (DirectHandle< String > key, Handle< Object > value)
Handle< JSObject > object ()
Private Member Functions
template<typename Char , typename GetKeyFunction >
bool TryFastTransitionToPropertyKey (base::Vector< const Char > key_chars, GetKeyFunction &&get_key, Handle< String > *key_out)
bool TryGeneralizeFieldToValue (DirectHandle< Object > value)
bool TryInitializeMapFromExpectedFinalMap ()
void InitializeMapFromZero ()
bool IsOnExpectedFinalMapFastPath () const
void RewindExpectedFinalMapFastPathToBeforeCurrent ()
void RewindExpectedFinalMapFastPathToIncludeCurrent ()
void RegisterFieldNeedsFreshHeapNumber (DirectHandle< Object > value)
void AdvanceToNextProperty ()
Private Attributes
Isolate * isolate_
ElementsKind elements_kind_
int expected_property_count_
HeapNumberMode heap_number_mode_
DirectHandle< Map > map_
int current_property_index_ = 0
int extra_heap_numbers_needed_ = 0
Handle< JSObject > object_
DirectHandle< Map > expected_final_map_ = {}
int property_count_in_expected_final_map_ = 0
Detailed Description
Definition at line 735 of file json-parser.cc.
Member Enumeration Documentation
HeapNumberMode
enum v8::internal::JSDataObjectBuilder::HeapNumberMode
Enumerator
kNormalHeapNumbers
kHeapNumbersGuaranteedUniquelyOwned
Definition at line 740 of file json-parser.cc.
                      {
    kNormalHeapNumbers,
    kHeapNumbersGuaranteedUniquelyOwned
  };
Constructor & Destructor Documentation
JSDataObjectBuilder()
v8::internal::JSDataObjectBuilder::JSDataObjectBuilder (Isolate * isolate, ElementsKind elements_kind, int expected_named_properties, DirectHandle< Map > expected_final_map, HeapNumberMode heap_number_mode) [inline]
Definition at line 744 of file json-parser.cc.
      : isolate_(isolate),
        elements_kind_(elements_kind),
        expected_property_count_(expected_named_properties),
        heap_number_mode_(heap_number_mode),
        expected_final_map_(expected_final_map) {
    if (!TryInitializeMapFromExpectedFinalMap()) {
      InitializeMapFromZero();
    }
  }
References InitializeMapFromZero(), and TryInitializeMapFromExpectedFinalMap().
Member Function Documentation
AddSlowProperty()
void v8::internal::JSDataObjectBuilder::AddSlowProperty (DirectHandle< String > key, Handle< Object > value) [inline]
Definition at line 979 of file json-parser.cc.
                                                                       {
    DCHECK(!object_.is_null());
    LookupIterator it(isolate_, object_, key, object_, LookupIterator::OWN);
    JSObject::DefineOwnPropertyIgnoreAttributes(&it, value, NONE).Check();
  }
References v8::internal::DCHECK(), v8::internal::JSObject::DefineOwnPropertyIgnoreAttributes(), isolate_, v8::internal::key, v8::internal::NONE, object_, v8::internal::LookupIterator::OWN, and v8::internal::value.
AdvanceToNextProperty()
void v8::internal::JSDataObjectBuilder::AdvanceToNextProperty () [inline], [private]
Definition at line 1193 of file json-parser.cc.
{ current_property_index_++; }
References current_property_index_.
Referenced by TryAddFastPropertyForValue().
BuildFromIterator()
template<typename PropertyIterator >
Handle<JSObject> v8::internal::JSDataObjectBuilder::BuildFromIterator (PropertyIterator && it, MaybeHandle< FixedArrayBase > maybe_elements = {}) [inline]
Definition at line 780 of file json-parser.cc.
                                                                          {}) {
    Handle<String> failed_property_add_key;
    for (; !it.Done(); it.Advance()) {
      Handle<String> property_key;
      if (!TryAddFastPropertyForValue(
              it.GetKeyChars(),
              [&](Handle<String> expected_key) {
                return property_key = it.GetKey(expected_key);
              },
              [&]() { return it.GetValue(true); })) {
        failed_property_add_key = property_key;
        break;
      }
    }
    DirectHandle<FixedArrayBase> elements;
    if (!maybe_elements.ToHandle(&elements)) {
      elements = isolate_->factory()->empty_fixed_array();
    }
    CreateAndInitialiseObject(it.RevisitValues(), elements);
    // Slow path: define remaining named properties.
    for (; !it.Done(); it.Advance()) {
      DirectHandle<String> key;
      if (!failed_property_add_key.is_null()) {
        key = std::exchange(failed_property_add_key, {});
      } else {
        key = it.GetKey({});
      }
#ifdef DEBUG
      uint32_t index;
      DCHECK(!key->AsArrayIndex(&index));
#endif
      Handle<Object> value = it.GetValue(false);
      AddSlowProperty(key, value);
    }
    return object();
  }
Referenced by v8::internal::JsonParser< Char >::BuildJsonObject().
CreateAndInitialiseObject()
template<typename ValueIterator >
void v8::internal::JSDataObjectBuilder::CreateAndInitialiseObject (ValueIterator value_it, DirectHandle< FixedArrayBase > elements) [inline]
Definition at line 883 of file json-parser.cc.
                                                                     {
    // We've created a map for the first `i` property stack values (which might
    // be all of them). We need to write these properties to a newly allocated
    // object.
    DCHECK(object_.is_null());
    if (current_property_index_ < property_count_in_expected_final_map_) {
      // If we were on the expected map fast path all the way, but never reached
      // the expected final map itself, then finalize the map by rewinding to
      // the one whose property is the actual current property index.
      //
      // TODO(leszeks): Do we actually want to use the final map fast path when
      // we know that the current map _can't_ reach the final map? Will we even
      // hit this case given that we check for matching instance size?
      RewindExpectedFinalMapFastPathToBeforeCurrent();
    }
    if (map_->is_dictionary_map()) {
      // It's only safe to emit a dictionary map when we've not set up any
      // properties, as the caller assumes it can set up the first N properties
      // as fast data properties.
      DCHECK_EQ(current_property_index_, 0);
      Handle<JSObject> object = isolate_->factory()->NewSlowJSObjectFromMap(
          map_, expected_property_count_);
      object->set_elements(*elements);
      object_ = object;
      return;
    }
    // The map should have as many own descriptors as the number of properties
    // we've created so far...
    DCHECK_EQ(current_property_index_, map_->NumberOfOwnDescriptors());
    // ... and all of those properties should be in-object data properties.
    DCHECK_EQ(current_property_index_,
              map_->GetInObjectProperties() - map_->UnusedInObjectProperties());
    // Create a folded mutable HeapNumber allocation area before allocating the
    // object -- this ensures that there is no allocation between the object
    // allocation and its initial fields being initialised, where the verifier
    // would see invalid double field state.
    FoldedMutableHeapNumberAllocation hn_allocation(isolate_,
                                                    extra_heap_numbers_needed_);
    // Allocate the object then immediately start a no_gc scope -- again, this
    // is so the verifier doesn't see invalid double field state.
    Handle<JSObject> object = isolate_->factory()->NewJSObjectFromMap(map_);
    DisallowGarbageCollection no_gc;
    Tagged<JSObject> raw_object = *object;
    raw_object->set_elements(*elements);
    Tagged<DescriptorArray> descriptors =
        raw_object->map()->instance_descriptors();
    WriteBarrierMode mode = raw_object->GetWriteBarrierMode(no_gc);
    FoldedMutableHeapNumberAllocator hn_allocator(isolate_, &hn_allocation,
                                                  no_gc);
    ReadOnlyRoots roots(isolate_);
    // Initialize the in-object properties up to the last added property.
    int current_property_offset = raw_object->GetInObjectPropertyOffset(0);
    for (int i = 0; i < current_property_index_; ++i, ++value_it) {
      InternalIndex descriptor_index(i);
      Tagged<Object> value = **value_it;
      // See comment in RegisterFieldNeedsFreshHeapNumber, we need to allocate
      // HeapNumbers for double representation fields when we can't make
      // existing HeapNumbers mutable, or when we only have a Smi value.
      if (heap_number_mode_ != kHeapNumbersGuaranteedUniquelyOwned ||
          IsSmi(value)) {
        PropertyDetails details = descriptors->GetDetails(descriptor_index);
        if (details.representation().IsDouble()) {
          value = hn_allocator.AllocateNext(
              roots, Float64(Object::NumberValue(value)));
        }
      }
      DCHECK(FieldIndex::ForPropertyIndex(object->map(), i).is_inobject());
      DCHECK_EQ(current_property_offset,
                FieldIndex::ForPropertyIndex(object->map(), i).offset());
      DCHECK_EQ(current_property_offset,
                object->map()->GetInObjectPropertyOffset(i));
      FieldIndex index = FieldIndex::ForInObjectOffset(current_property_offset,
                                                       FieldIndex::kTagged);
      raw_object->RawFastInobjectPropertyAtPut(index, value, mode);
      current_property_offset += kTaggedSize;
    }
    DCHECK_EQ(current_property_offset, object->map()->GetInObjectPropertyOffset(
                                           current_property_index_));
    object_ = object;
  }
References v8::internal::FoldedMutableHeapNumberAllocator::AllocateNext(), current_property_index_, v8::internal::DCHECK(), DCHECK_EQ, expected_property_count_, extra_heap_numbers_needed_, v8::internal::Isolate::factory(), v8::internal::FieldIndex::ForInObjectOffset(), v8::internal::FieldIndex::ForPropertyIndex(), heap_number_mode_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::FieldIndex::is_inobject(), v8::internal::Representation::IsDouble(), isolate_, v8::internal::IsSmi(), kHeapNumbersGuaranteedUniquelyOwned, v8::internal::FieldIndex::kTagged, v8::internal::kTaggedSize, map_, mode(), v8::internal::Factory::NewJSObjectFromMap(), v8::internal::Factory::NewSlowJSObjectFromMap(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), object(), object_, v8::internal::FieldIndex::offset(), property_count_in_expected_final_map_, v8::internal::PropertyDetails::representation(), RewindExpectedFinalMapFastPathToBeforeCurrent(), and v8::internal::value.
InitializeMapFromZero()
void v8::internal::JSDataObjectBuilder::InitializeMapFromZero () [inline], [private]
Definition at line 1139 of file json-parser.cc.
                               {
    // Must be called before any properties are registered.
    DCHECK_EQ(current_property_index_, 0);
    map_ = isolate_->factory()->ObjectLiteralMapFromCache(
        isolate_->native_context(), expected_property_count_);
    if (elements_kind_ == DICTIONARY_ELEMENTS) {
      map_ = Map::AsElementsKind(isolate_, map_, elements_kind_);
    } else {
      DCHECK_EQ(map_->elements_kind(), elements_kind_);
    }
  }
References v8::internal::Map::AsElementsKind(), current_property_index_, DCHECK_EQ, v8::internal::DICTIONARY_ELEMENTS, elements_kind_, expected_property_count_, v8::internal::Isolate::factory(), isolate_, map_, v8::internal::Isolate::native_context(), and v8::internal::Factory::ObjectLiteralMapFromCache().
Referenced by JSDataObjectBuilder(), and RewindExpectedFinalMapFastPathToBeforeCurrent().
IsOnExpectedFinalMapFastPath()
bool v8::internal::JSDataObjectBuilder::IsOnExpectedFinalMapFastPath () const [inline], [private]
Definition at line 1152 of file json-parser.cc.
                                                      {
    DCHECK_IMPLIES(property_count_in_expected_final_map_ > 0,
                   !expected_final_map_.is_null());
    return current_property_index_ < property_count_in_expected_final_map_;
  }
References current_property_index_, DCHECK_IMPLIES, expected_final_map_, and property_count_in_expected_final_map_.
Referenced by TryFastTransitionToPropertyKey(), and TryGeneralizeFieldToValue().
object()
Handle<JSObject> v8::internal::JSDataObjectBuilder::object () [inline]
Definition at line 986 of file json-parser.cc.
                            {
    DCHECK(!object_.is_null());
    return object_;
  }
References v8::internal::DCHECK(), and object_.
Referenced by CreateAndInitialiseObject().
RegisterFieldNeedsFreshHeapNumber()
void v8::internal::JSDataObjectBuilder::RegisterFieldNeedsFreshHeapNumber (DirectHandle< Object > value) [inline], [private]
Definition at line 1180 of file json-parser.cc.
                                                                               {
    // We need to allocate a new HeapNumber for double representation fields if
    // the HeapNumber values is not guaranteed to be uniquely owned by this
    // object (and therefore can't be made mutable), or if the value is a Smi
    // and there is no HeapNumber box for this value yet at all.
    if (heap_number_mode_ == kHeapNumbersGuaranteedUniquelyOwned &&
        !IsSmi(*value)) {
      DCHECK(IsHeapNumber(*value));
      return;
    }
    extra_heap_numbers_needed_++;
  }
References v8::internal::DCHECK(), extra_heap_numbers_needed_, heap_number_mode_, v8::internal::IsSmi(), kHeapNumbersGuaranteedUniquelyOwned, and v8::internal::value.
Referenced by TryAddFastPropertyForValue(), and TryGeneralizeFieldToValue().
RewindExpectedFinalMapFastPathToBeforeCurrent()
void v8::internal::JSDataObjectBuilder::RewindExpectedFinalMapFastPathToBeforeCurrent () [inline], [private]
Definition at line 1158 of file json-parser.cc.
                                                       {
    DCHECK_GT(property_count_in_expected_final_map_, 0);
    if (current_property_index_ == 0) {
      InitializeMapFromZero();
      DCHECK_EQ(0, map_->NumberOfOwnDescriptors());
    }
    if (current_property_index_ == 0) {
      return;
    }
    DCHECK_EQ(*map_, *expected_final_map_);
    map_ = handle(map_->FindFieldOwner(
                      isolate_, InternalIndex(current_property_index_ - 1)),
                  isolate_);
  }
References current_property_index_, DCHECK_EQ, DCHECK_GT, expected_final_map_, v8::internal::handle(), InitializeMapFromZero(), isolate_, map_, and property_count_in_expected_final_map_.
Referenced by CreateAndInitialiseObject(), and TryFastTransitionToPropertyKey().
RewindExpectedFinalMapFastPathToIncludeCurrent()
void v8::internal::JSDataObjectBuilder::RewindExpectedFinalMapFastPathToIncludeCurrent () [inline], [private]
Definition at line 1173 of file json-parser.cc.
                                                        {
    DCHECK_EQ(*map_, *expected_final_map_);
    map_ = handle(expected_final_map_->FindFieldOwner(
                      isolate_, InternalIndex(current_property_index_)),
                  isolate_);
  }
References current_property_index_, DCHECK_EQ, expected_final_map_, v8::internal::handle(), isolate_, and map_.
Referenced by TryGeneralizeFieldToValue().
TryAddFastPropertyForValue()
template<typename Char , typename GetKeyFunction , typename GetValueFunction >
bool v8::internal::JSDataObjectBuilder::TryAddFastPropertyForValue (base::Vector< const Char > key_chars, GetKeyFunction && get_key, GetValueFunction && get_value) [inline]
Definition at line 822 of file json-parser.cc.
                                                                          {
    // The fast path is only valid as long as we haven't allocated an object
    // yet.
    DCHECK(object_.is_null());
    Handle<String> key;
    bool existing_map_found =
        TryFastTransitionToPropertyKey(key_chars, get_key, &key);
    // Unconditionally get the value after getting the transition result.
    DirectHandle<Object> value = get_value();
    if (existing_map_found) {
      // We found a map with a field for our value -- now make sure that field
      // is compatible with our value.
      if (!TryGeneralizeFieldToValue(value)) {
        // TODO(leszeks): Try to stay on the fast path if we just deprecate
        // here.
        return false;
      }
      AdvanceToNextProperty();
      return true;
    }
    // Try to stay on a semi-fast path (being able to stamp out the object
    // fields after creating the correct map) by manually creating the next
    // map here.
    Tagged<DescriptorArray> descriptors = map_->instance_descriptors(isolate_);
    InternalIndex descriptor_number =
        descriptors->SearchWithCache(isolate_, *key, *map_);
    if (descriptor_number.is_found()) {
      // Duplicate property, we need to bail out of even the semi-fast path
      // because we can no longer stamp out values linearly.
      return false;
    }
    if (!TransitionsAccessor::CanHaveMoreTransitions(isolate_, map_)) {
      return false;
    }
    Representation representation =
        Object::OptimalRepresentation(*value, isolate_);
    DirectHandle<FieldType> type =
        Object::OptimalType(*value, isolate_, representation);
    MaybeHandle<Map> maybe_map = Map::CopyWithField(
        isolate_, map_, key, type, NONE, PropertyConstness::kConst,
        representation, INSERT_TRANSITION);
    Handle<Map> next_map;
    if (!maybe_map.ToHandle(&next_map)) return false;
    if (next_map->is_dictionary_map()) return false;
    map_ = next_map;
    if (representation.IsDouble()) {
      RegisterFieldNeedsFreshHeapNumber(value);
    }
    AdvanceToNextProperty();
    return true;
  }
References AdvanceToNextProperty(), v8::internal::TransitionsAccessor::CanHaveMoreTransitions(), v8::internal::Map::CopyWithField(), v8::internal::DCHECK(), v8::internal::INSERT_TRANSITION, v8::internal::InternalIndex::is_found(), v8::internal::Representation::IsDouble(), isolate_, v8::internal::kConst, v8::internal::key, map_, v8::internal::NONE, object_, v8::internal::Object::OptimalRepresentation(), v8::internal::Object::OptimalType(), RegisterFieldNeedsFreshHeapNumber(), v8::internal::MaybeHandle< T >::ToHandle(), TryFastTransitionToPropertyKey(), TryGeneralizeFieldToValue(), v8::internal::tracing::type, and v8::internal::value.
TryFastTransitionToPropertyKey()
template<typename Char , typename GetKeyFunction >
bool v8::internal::JSDataObjectBuilder::TryFastTransitionToPropertyKey (base::Vector< const Char > key_chars, GetKeyFunction && get_key, Handle< String > * key_out) [inline], [private]
Definition at line 993 of file json-parser.cc.
                               {
    Handle<String> expected_key;
    DirectHandle<Map> target_map;
    InternalIndex descriptor_index(current_property_index_);
    if (IsOnExpectedFinalMapFastPath()) {
      expected_key = handle(
          Cast<String>(
              expected_final_map_->instance_descriptors(isolate_)->GetKey(
                  descriptor_index)),
          isolate_);
      target_map = expected_final_map_;
    } else {
      TransitionsAccessor transitions(isolate_, *map_);
      auto expected_transition = transitions.ExpectedTransition(key_chars);
      if (!expected_transition.first.is_null()) {
        // Directly read out the target while reading out the key, otherwise it
        // might die if `get_key` can allocate.
        target_map = expected_transition.second;
        // We were successful and we are done.
        DCHECK_EQ(target_map->instance_descriptors()
                      ->GetDetails(descriptor_index)
                      .location(),
                  PropertyLocation::kField);
        map_ = target_map;
        return true;
      }
    }
    DirectHandle<String> key = *key_out = get_key(expected_key);
    if (key.is_identical_to(expected_key)) {
      // We were successful and we are done.
      DCHECK_EQ(target_map->instance_descriptors()
                    ->GetDetails(descriptor_index)
                    .location(),
                PropertyLocation::kField);
      map_ = target_map;
      return true;
    }
    if (IsOnExpectedFinalMapFastPath()) {
      // We were on the expected map fast path, but this missed that fast
      // path, so rewind the optimistic setting of the current map and disable
      // this fast path.
      RewindExpectedFinalMapFastPathToBeforeCurrent();
      property_count_in_expected_final_map_ = 0;
    }
    MaybeHandle<Map> maybe_target =
        TransitionsAccessor(isolate_, *map_).FindTransitionToField(key);
    if (!maybe_target.ToHandle(&target_map)) return false;
    map_ = target_map;
    return true;
  }
References current_property_index_, DCHECK_EQ, expected_final_map_, v8::internal::TransitionsAccessor::ExpectedTransition(), v8::internal::TransitionsAccessor::FindTransitionToField(), v8::internal::handle(), isolate_, IsOnExpectedFinalMapFastPath(), v8::internal::key, v8::internal::kField, map_, property_count_in_expected_final_map_, RewindExpectedFinalMapFastPathToBeforeCurrent(), and v8::internal::MaybeHandle< T >::ToHandle().
Referenced by TryAddFastPropertyForValue().
TryGeneralizeFieldToValue()
bool v8::internal::JSDataObjectBuilder::TryGeneralizeFieldToValue (DirectHandle< Object > value) [inline], [private]
Definition at line 1052 of file json-parser.cc.
                                                                       {
    DCHECK_LT(current_property_index_, map_->NumberOfOwnDescriptors());
    InternalIndex descriptor_index(current_property_index_);
    PropertyDetails current_details =
        map_->instance_descriptors(isolate_)->GetDetails(descriptor_index);
    Representation expected_representation = current_details.representation();
    DCHECK_EQ(current_details.kind(), PropertyKind::kData);
    DCHECK_EQ(current_details.location(), PropertyLocation::kField);
    if (!Object::FitsRepresentation(*value, expected_representation)) {
      Representation representation =
          Object::OptimalRepresentation(*value, isolate_);
      representation = representation.generalize(expected_representation);
      if (!expected_representation.CanBeInPlaceChangedTo(representation)) {
        // Reconfigure the map for the value, deprecating if necessary. This
        // will only happen for double representation fields.
        if (IsOnExpectedFinalMapFastPath()) {
          // If we're on the fast path, we will have advanced the current map
          // all the way to the final expected map. Make sure to rewind to the
          // "real" current map if this happened.
          //
          // An alternative would be to deprecate the expected final map,
          // migrate it to the new representation, and stay on the fast path.
          // However, this would mean allocating all-new maps (with the new
          // representation) all the way between the current map and the new
          // expected final map; if we later fall off the fast path anyway, then
          // all those newly allocated maps will end up unused.
          RewindExpectedFinalMapFastPathToIncludeCurrent();
          property_count_in_expected_final_map_ = 0;
        }
        MapUpdater mu(isolate_, map_);
        Handle<Map> new_map = mu.ReconfigureToDataField(
            descriptor_index, current_details.attributes(),
            current_details.constness(), representation,
            FieldType::Any(isolate_));
        // We only want to stay on the fast path if we got a fast map.
        if (new_map->is_dictionary_map()) return false;
        map_ = new_map;
        DCHECK(representation.IsDouble());
        RegisterFieldNeedsFreshHeapNumber(value);
      } else {
        // Do the in-place reconfiguration.
        DCHECK(!representation.IsDouble());
        DirectHandle<FieldType> value_type =
            Object::OptimalType(*value, isolate_, representation);
        MapUpdater::GeneralizeField(isolate_, map_, descriptor_index,
                                    current_details.constness(), representation,
                                    value_type);
      }
    } else if (expected_representation.IsHeapObject() &&
               !FieldType::NowContains(
                   map_->instance_descriptors(isolate_)->GetFieldType(
                       descriptor_index),
                   value)) {
      DirectHandle<FieldType> value_type =
          Object::OptimalType(*value, isolate_, expected_representation);
      MapUpdater::GeneralizeField(isolate_, map_, descriptor_index,
                                  current_details.constness(),
                                  expected_representation, value_type);
    } else if (expected_representation.IsDouble()) {
      RegisterFieldNeedsFreshHeapNumber(value);
    }
    DCHECK(FieldType::NowContains(
        map_->instance_descriptors(isolate_)->GetFieldType(descriptor_index),
        value));
    return true;
  }
References v8::internal::FieldType::Any(), v8::internal::PropertyDetails::attributes(), v8::internal::Representation::CanBeInPlaceChangedTo(), v8::internal::PropertyDetails::constness(), current_property_index_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, v8::internal::Object::FitsRepresentation(), v8::internal::Representation::generalize(), v8::internal::MapUpdater::GeneralizeField(), v8::internal::Representation::IsDouble(), v8::internal::Representation::IsHeapObject(), isolate_, IsOnExpectedFinalMapFastPath(), v8::internal::kData, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), map_, v8::internal::mu, v8::internal::FieldType::NowContains(), v8::internal::Object::OptimalRepresentation(), v8::internal::Object::OptimalType(), property_count_in_expected_final_map_, RegisterFieldNeedsFreshHeapNumber(), v8::internal::PropertyDetails::representation(), RewindExpectedFinalMapFastPathToIncludeCurrent(), v8::internal::value, and v8::internal::wasm::value_type().
Referenced by TryAddFastPropertyForValue().
TryInitializeMapFromExpectedFinalMap()
bool v8::internal::JSDataObjectBuilder::TryInitializeMapFromExpectedFinalMap () [inline], [private]
Definition at line 1124 of file json-parser.cc.
                                              {
    if (expected_final_map_.is_null()) return false;
    if (expected_final_map_->elements_kind() != elements_kind_) return false;
    int property_count_in_expected_final_map =
        expected_final_map_->NumberOfOwnDescriptors();
    if (property_count_in_expected_final_map < expected_property_count_)
      return false;
    map_ = expected_final_map_;
    property_count_in_expected_final_map_ =
        property_count_in_expected_final_map;
    return true;
  }
References elements_kind_, expected_final_map_, expected_property_count_, map_, and property_count_in_expected_final_map_.
Referenced by JSDataObjectBuilder().
Member Data Documentation
current_property_index_
int v8::internal::JSDataObjectBuilder::current_property_index_ = 0 [private]
Definition at line 1201 of file json-parser.cc.
Referenced by AdvanceToNextProperty(), CreateAndInitialiseObject(), InitializeMapFromZero(), IsOnExpectedFinalMapFastPath(), RewindExpectedFinalMapFastPathToBeforeCurrent(), RewindExpectedFinalMapFastPathToIncludeCurrent(), TryFastTransitionToPropertyKey(), and TryGeneralizeFieldToValue().
elements_kind_
ElementsKind v8::internal::JSDataObjectBuilder::elements_kind_ [private]
Definition at line 1196 of file json-parser.cc.
Referenced by InitializeMapFromZero(), and TryInitializeMapFromExpectedFinalMap().
expected_final_map_
DirectHandle<Map> v8::internal::JSDataObjectBuilder::expected_final_map_ = {} [private]
Definition at line 1206 of file json-parser.cc.
Referenced by IsOnExpectedFinalMapFastPath(), RewindExpectedFinalMapFastPathToBeforeCurrent(), RewindExpectedFinalMapFastPathToIncludeCurrent(), TryFastTransitionToPropertyKey(), and TryInitializeMapFromExpectedFinalMap().
expected_property_count_
int v8::internal::JSDataObjectBuilder::expected_property_count_ [private]
Definition at line 1197 of file json-parser.cc.
Referenced by CreateAndInitialiseObject(), InitializeMapFromZero(), and TryInitializeMapFromExpectedFinalMap().
extra_heap_numbers_needed_
int v8::internal::JSDataObjectBuilder::extra_heap_numbers_needed_ = 0 [private]
Definition at line 1202 of file json-parser.cc.
Referenced by CreateAndInitialiseObject(), and RegisterFieldNeedsFreshHeapNumber().
heap_number_mode_
HeapNumberMode v8::internal::JSDataObjectBuilder::heap_number_mode_ [private]
Definition at line 1198 of file json-parser.cc.
Referenced by CreateAndInitialiseObject(), and RegisterFieldNeedsFreshHeapNumber().
isolate_
Isolate* v8::internal::JSDataObjectBuilder::isolate_ [private]
Definition at line 1195 of file json-parser.cc.
Referenced by AddSlowProperty(), CreateAndInitialiseObject(), InitializeMapFromZero(), RewindExpectedFinalMapFastPathToBeforeCurrent(), RewindExpectedFinalMapFastPathToIncludeCurrent(), TryAddFastPropertyForValue(), TryFastTransitionToPropertyKey(), and TryGeneralizeFieldToValue().
map_
DirectHandle<Map> v8::internal::JSDataObjectBuilder::map_ [private]
Definition at line 1200 of file json-parser.cc.
Referenced by CreateAndInitialiseObject(), InitializeMapFromZero(), RewindExpectedFinalMapFastPathToBeforeCurrent(), RewindExpectedFinalMapFastPathToIncludeCurrent(), TryAddFastPropertyForValue(), TryFastTransitionToPropertyKey(), TryGeneralizeFieldToValue(), and TryInitializeMapFromExpectedFinalMap().
object_
Handle<JSObject> v8::internal::JSDataObjectBuilder::object_ [private]
Definition at line 1204 of file json-parser.cc.
Referenced by AddSlowProperty(), CreateAndInitialiseObject(), object(), and TryAddFastPropertyForValue().
property_count_in_expected_final_map_
int v8::internal::JSDataObjectBuilder::property_count_in_expected_final_map_ = 0 [private]
Definition at line 1207 of file json-parser.cc.
Referenced by CreateAndInitialiseObject(), IsOnExpectedFinalMapFastPath(), RewindExpectedFinalMapFastPathToBeforeCurrent(), TryFastTransitionToPropertyKey(), TryGeneralizeFieldToValue(), and TryInitializeMapFromExpectedFinalMap().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/json/json-parser.cc