v8::internal::torque::TopType Class Reference
#include <types.h>
Public Member Functions
std::string GetGeneratedTypeNameImpl () const override
std::string GetGeneratedTNodeTypeNameImpl () const override
std::string ToExplicitString () const override
const Type * source_type () const
const std::string reason () const
Private Member Functions
TopType (std::string reason, const Type *source_type)
std::string SimpleNameImpl () const override
Private Attributes
std::string reason_
const Type * source_type_
Friends
class TypeOracle
Additional Inherited Members
Detailed Description
Definition at line 239 of file types.h.
Constructor & Destructor Documentation
TopType()
v8::internal::torque::TopType::TopType (std::string reason, const Type * source_type) [inline], [explicit], [private]
Definition at line 257 of file types.h.
      : Type(Kind::kTopType, nullptr),
        reason_(std::move(reason)),
        source_type_(source_type) {}
Member Function Documentation
GetGeneratedTNodeTypeNameImpl()
std::string v8::internal::torque::TopType::GetGeneratedTNodeTypeNameImpl () const [inline], [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 243 of file types.h.
                                                           {
    return source_type_->GetGeneratedTNodeTypeName();
  }
References v8::internal::torque::Type::GetGeneratedTNodeTypeName(), and source_type_.
GetGeneratedTypeNameImpl()
std::string v8::internal::torque::TopType::GetGeneratedTypeNameImpl () const [inline], [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 242 of file types.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
reason()
const std::string v8::internal::torque::TopType::reason () const [inline]
Definition at line 253 of file types.h.
{ return reason_; }
References reason_.
SimpleNameImpl()
std::string v8::internal::torque::TopType::SimpleNameImpl () const [inline], [override], [private], [virtual]
Implements v8::internal::torque::Type.
Definition at line 261 of file types.h.
{ return "TopType"; }
source_type()
const Type* v8::internal::torque::TopType::source_type () const [inline]
Definition at line 252 of file types.h.
{ return source_type_; }
References source_type_.
ToExplicitString()
std::string v8::internal::torque::TopType::ToExplicitString () const [inline], [override], [virtual]
Implements v8::internal::torque::Type.
Definition at line 246 of file types.h.
                                              {
    std::stringstream s;
    s << "inaccessible " + source_type_->ToString();
    return s.str();
  }
References source_type_, and v8::internal::torque::Type::ToString().
Friends And Related Function Documentation
TypeOracle
friend class TypeOracle [friend]
Definition at line 256 of file types.h.
Member Data Documentation
reason_
std::string v8::internal::torque::TopType::reason_ [private]
Definition at line 263 of file types.h.
Referenced by reason().
source_type_
const Type* v8::internal::torque::TopType::source_type_ [private]
Definition at line 264 of file types.h.
Referenced by GetGeneratedTNodeTypeNameImpl(), source_type(), and ToExplicitString().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/types.h