v8::platform::DefaultPlatform Class Reference
#include <default-platform.h>
Public Types
using TimeFunction = double(*)()
Public Member Functions
DefaultPlatform (int thread_pool_size=0, IdleTaskSupport idle_task_support=IdleTaskSupport::kDisabled, std::unique_ptr< v8::TracingController > tracing_controller={}, PriorityMode priority_mode=PriorityMode::kDontApply)
~DefaultPlatform () override
DefaultPlatform (const DefaultPlatform &)=delete
DefaultPlatform & operator= (const DefaultPlatform &)=delete
void EnsureBackgroundTaskRunnerInitialized ()
bool PumpMessageLoop (v8::Isolate *isolate, MessageLoopBehavior behavior=MessageLoopBehavior::kDoNotWait)
void RunIdleTasks (v8::Isolate *isolate, double idle_time_in_seconds)
void SetTracingController (std::unique_ptr< v8::TracingController > tracing_controller)
void SetTimeFunctionForTesting (TimeFunction time_function)
int NumberOfWorkerThreads () override
std::shared_ptr< TaskRunner > GetForegroundTaskRunner (v8::Isolate *isolate, TaskPriority priority) override
void PostTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, const SourceLocation &location) override
void PostDelayedTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation &location) override
bool IdleTasksEnabled (Isolate *isolate) override
std::unique_ptr< JobHandle > CreateJobImpl (TaskPriority priority, std::unique_ptr< JobTask > job_state, const SourceLocation &location) override
double MonotonicallyIncreasingTime () override
double CurrentClockTimeMillis () override
v8::TracingController * GetTracingController () override
StackTracePrinter GetStackTracePrinter () override
v8::PageAllocator * GetPageAllocator () override
v8::ThreadIsolatedAllocator * GetThreadIsolatedAllocator () override
void NotifyIsolateShutdown (Isolate *isolate)
Private Member Functions
base::Thread::Priority priority_from_index (int i) const
int priority_to_index (TaskPriority priority) const
int num_worker_runners () const
Private Attributes
base::Mutex lock_
const int thread_pool_size_
IdleTaskSupport idle_task_support_
std::shared_ptr< DefaultWorkerThreadsTaskRunner > worker_threads_task_runners_ [static_cast< int >(TaskPriority::kMaxPriority)+1] = {0}
std::map< v8::Isolate *, std::shared_ptr< DefaultForegroundTaskRunner > > foreground_task_runner_map_
std::unique_ptr< TracingController > tracing_controller_
std::unique_ptr< PageAllocator > page_allocator_
DefaultThreadIsolatedAllocator thread_isolated_allocator_
const PriorityMode priority_mode_
TimeFunction time_function_for_testing_ = nullptr
Detailed Description
Definition at line 28 of file default-platform.h.
Member Typedef Documentation
TimeFunction
using v8::platform::DefaultPlatform::TimeFunction = double (*)()
Definition at line 52 of file default-platform.h.
Constructor & Destructor Documentation
DefaultPlatform() [1/2]
v8::platform::DefaultPlatform::DefaultPlatform (int thread_pool_size = 0, IdleTaskSupport idle_task_support = IdleTaskSupport::kDisabled, std::unique_ptr< v8::TracingController > tracing_controller = {}, PriorityMode priority_mode = PriorityMode::kDontApply) [explicit]
Definition at line 95 of file default-platform.cc.
    : thread_pool_size_(thread_pool_size),
      idle_task_support_(idle_task_support),
      tracing_controller_(std::move(tracing_controller)),
      page_allocator_(std::make_unique<v8::base::PageAllocator>()),
      priority_mode_(priority_mode) {
  if (!tracing_controller_) {
    tracing::TracingController* controller = new tracing::TracingController();
#if !defined(V8_USE_PERFETTO)
    controller->Initialize(nullptr);
#endif
    tracing_controller_.reset(controller);
  }
  if (thread_pool_size_ > 0) {
    EnsureBackgroundTaskRunnerInitialized();
  }
}
References EnsureBackgroundTaskRunnerInitialized(), v8::platform::tracing::TracingController::Initialize(), thread_pool_size_, and tracing_controller_.
 DefaultPlatform()
v8::platform::DefaultPlatform::~DefaultPlatform () [override]
Definition at line 116 of file default-platform.cc.
                                  {
  base::MutexGuard guard(&lock_);
  if (worker_threads_task_runners_[0]) {
    for (int i = 0; i < num_worker_runners(); i++) {
      worker_threads_task_runners_[i]->Terminate();
    }
  }
  for (const auto& it : foreground_task_runner_map_) {
    it.second->Terminate();
  }
}
References foreground_task_runner_map_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, lock_, num_worker_runners(), and worker_threads_task_runners_.
DefaultPlatform() [2/2]
v8::platform::DefaultPlatform::DefaultPlatform (const DefaultPlatform &) [delete]
Member Function Documentation
CreateJobImpl()
std::unique_ptr< JobHandle > v8::platform::DefaultPlatform::CreateJobImpl (TaskPriority priority, std::unique_ptr< JobTask > job_state, const SourceLocation & location) [override]
Definition at line 245 of file default-platform.cc.
                                    {
  size_t num_worker_threads = NumberOfWorkerThreads();
  if (priority == TaskPriority::kBestEffort && num_worker_threads > 2) {
    num_worker_threads = 2;
  }
  return NewDefaultJobHandle(this, priority, std::move(job_task),
                             num_worker_threads);
}
References v8::kBestEffort, v8::platform::NewDefaultJobHandle(), and NumberOfWorkerThreads().
CurrentClockTimeMillis()
double v8::platform::DefaultPlatform::CurrentClockTimeMillis () [override]
Definition at line 261 of file default-platform.cc.
                                               {
  return base::OS::TimeCurrentMillis();
}
References v8::base::OS::TimeCurrentMillis().
EnsureBackgroundTaskRunnerInitialized()
void v8::platform::DefaultPlatform::EnsureBackgroundTaskRunnerInitialized ()
Definition at line 137 of file default-platform.cc.
                                                            {
  DCHECK_NULL(worker_threads_task_runners_[0]);
  for (int i = 0; i < num_worker_runners(); i++) {
    worker_threads_task_runners_[i] =
        std::make_shared<DefaultWorkerThreadsTaskRunner>(
            thread_pool_size_,
            time_function_for_testing_ ? time_function_for_testing_
                                       : DefaultTimeFunction,
            priority_from_index(i));
  }
  DCHECK_NOT_NULL(worker_threads_task_runners_[0]);
}
References DCHECK_NOT_NULL, DCHECK_NULL, v8::platform::anonymous_namespace{default-platform.cc}::DefaultTimeFunction(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, num_worker_runners(), priority_from_index(), thread_pool_size_, time_function_for_testing_, and worker_threads_task_runners_.
Referenced by DefaultPlatform().
GetForegroundTaskRunner()
std::shared_ptr< TaskRunner > v8::platform::DefaultPlatform::GetForegroundTaskRunner (v8::Isolate * isolate, TaskPriority priority) [override]
Definition at line 200 of file default-platform.cc.
                                               {
  base::MutexGuard guard(&lock_);
  if (foreground_task_runner_map_.find(isolate) ==
      foreground_task_runner_map_.end()) {
    foreground_task_runner_map_.insert(std::make_pair(
        isolate, std::make_shared<DefaultForegroundTaskRunner>(
                     idle_task_support_, time_function_for_testing_
                                             ? time_function_for_testing_
                                             : DefaultTimeFunction)));
  }
  return foreground_task_runner_map_[isolate];
}
References v8::platform::anonymous_namespace{default-platform.cc}::DefaultTimeFunction(), foreground_task_runner_map_, idle_task_support_, lock_, and time_function_for_testing_.
GetPageAllocator()
v8::PageAllocator * v8::platform::DefaultPlatform::GetPageAllocator () [override]
Definition at line 281 of file default-platform.cc.
                                                   {
  return page_allocator_.get();
}
References page_allocator_.
GetStackTracePrinter()
Platform::StackTracePrinter v8::platform::DefaultPlatform::GetStackTracePrinter () [override]
Definition at line 277 of file default-platform.cc.
                                                                {
  return PrintStackTrace;
}
References v8::platform::anonymous_namespace{default-platform.cc}::PrintStackTrace().
GetThreadIsolatedAllocator()
v8::ThreadIsolatedAllocator * v8::platform::DefaultPlatform::GetThreadIsolatedAllocator () [override]
Definition at line 285 of file default-platform.cc.
                                                                       {
  if (thread_isolated_allocator_.Valid()) {
    return &thread_isolated_allocator_;
  }
  return nullptr;
}
References thread_isolated_allocator_, and v8::platform::DefaultThreadIsolatedAllocator::Valid().
GetTracingController()
TracingController * v8::platform::DefaultPlatform::GetTracingController () [override]
Definition at line 265 of file default-platform.cc.
                                                         {
  return tracing_controller_.get();
}
References tracing_controller_.
IdleTasksEnabled()
bool v8::platform::DefaultPlatform::IdleTasksEnabled (Isolate * isolate) [override]
Definition at line 241 of file default-platform.cc.
                                                       {
  return idle_task_support_ == IdleTaskSupport::kEnabled;
}
References idle_task_support_, and v8::platform::kEnabled.
MonotonicallyIncreasingTime()
double v8::platform::DefaultPlatform::MonotonicallyIncreasingTime () [override]
Definition at line 256 of file default-platform.cc.
                                                    {
  if (time_function_for_testing_) return time_function_for_testing_();
  return DefaultTimeFunction();
}
References v8::platform::anonymous_namespace{default-platform.cc}::DefaultTimeFunction(), and time_function_for_testing_.
Referenced by RunIdleTasks().
NotifyIsolateShutdown()
void v8::platform::DefaultPlatform::NotifyIsolateShutdown (Isolate * isolate)
Definition at line 292 of file default-platform.cc.
                                                            {
  std::shared_ptr<DefaultForegroundTaskRunner> taskrunner;
  {
    base::MutexGuard guard(&lock_);
    auto it = foreground_task_runner_map_.find(isolate);
    if (it != foreground_task_runner_map_.end()) {
      taskrunner = it->second;
      foreground_task_runner_map_.erase(it);
    }
  }
  taskrunner->Terminate();
}
References foreground_task_runner_map_, and lock_.
num_worker_runners()
int v8::platform::DefaultPlatform::num_worker_runners () const [inline], [private]
Definition at line 101 of file default-platform.h.
                                 {
    return priority_to_index(TaskPriority::kMaxPriority) + 1;
  }
References v8::kMaxPriority.
Referenced by EnsureBackgroundTaskRunnerInitialized(), and ~DefaultPlatform().
NumberOfWorkerThreads()
int v8::platform::DefaultPlatform::NumberOfWorkerThreads () [override]
Definition at line 275 of file default-platform.cc.
{ return thread_pool_size_; }
References thread_pool_size_.
Referenced by CreateJobImpl().
operator=()
DefaultPlatform& v8::platform::DefaultPlatform::operator= (const DefaultPlatform &) [delete]
PostDelayedTaskOnWorkerThreadImpl()
void v8::platform::DefaultPlatform::PostDelayedTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation & location) [override]
Definition at line 227 of file default-platform.cc.
                                    {
  // If this DCHECK fires, then this means that either
  // - V8 is running without the --single-threaded flag but
  // but the platform was created as a single-threaded platform.
  // - or some component in V8 is ignoring --single-threaded
  // and posting a background task.
  int index = priority_to_index(priority);
  DCHECK_NOT_NULL(worker_threads_task_runners_[index]);
  worker_threads_task_runners_[index]->PostDelayedTask(std::move(task),
                                                       delay_in_seconds);
}
References DCHECK_NOT_NULL, v8::internal::index, priority_to_index(), and worker_threads_task_runners_.
PostTaskOnWorkerThreadImpl()
void v8::platform::DefaultPlatform::PostTaskOnWorkerThreadImpl (TaskPriority priority, std::unique_ptr< Task > task, const SourceLocation & location) [override]
Definition at line 214 of file default-platform.cc.
                                    {
  // If this DCHECK fires, then this means that either
  // - V8 is running without the --single-threaded flag but the platform was
  // created as a single-threaded platform or
  // - some component in V8 is ignoring --single-threaded and posting a
  // background task.
  int index = priority_to_index(priority);
  DCHECK_NOT_NULL(worker_threads_task_runners_[index]);
  worker_threads_task_runners_[index]->PostTask(std::move(task));
}
References DCHECK_NOT_NULL, v8::internal::index, priority_to_index(), and worker_threads_task_runners_.
priority_from_index()
base::Thread::Priority v8::platform::DefaultPlatform::priority_from_index (int i) const [inline], [private]
Definition at line 80 of file default-platform.h.
                                                      {
    if (priority_mode_ == PriorityMode::kDontApply) {
      return base::Thread::Priority::kDefault;
    }
    switch (static_cast<TaskPriority>(i)) {
      case TaskPriority::kUserBlocking:
        return base::Thread::Priority::kUserBlocking;
      case TaskPriority::kUserVisible:
        return base::Thread::Priority::kUserVisible;
      case TaskPriority::kBestEffort:
        return base::Thread::Priority::kBestEffort;
    }
  }
References v8::kBestEffort, v8::base::Thread::kBestEffort, v8::base::Thread::kDefault, v8::platform::kDontApply, v8::kUserBlocking, v8::base::Thread::kUserBlocking, v8::kUserVisible, and v8::base::Thread::kUserVisible.
Referenced by EnsureBackgroundTaskRunnerInitialized().
priority_to_index()
int v8::platform::DefaultPlatform::priority_to_index (TaskPriority priority) const [inline], [private]
Definition at line 94 of file default-platform.h.
                                                     {
    if (priority_mode_ == PriorityMode::kDontApply) {
      return 0;
    }
    return static_cast<int>(priority);
  }
References v8::platform::kDontApply.
Referenced by PostDelayedTaskOnWorkerThreadImpl(), and PostTaskOnWorkerThreadImpl().
PumpMessageLoop()
bool v8::platform::DefaultPlatform::PumpMessageLoop (v8::Isolate * isolate, MessageLoopBehavior behavior = MessageLoopBehavior::kDoNotWait)
Definition at line 158 of file default-platform.cc.
                                                                         {
  bool failed_result = wait_for_work == MessageLoopBehavior::kWaitForWork;
  std::shared_ptr<DefaultForegroundTaskRunner> task_runner;
  {
    base::MutexGuard guard(&lock_);
    auto it = foreground_task_runner_map_.find(isolate);
    if (it == foreground_task_runner_map_.end()) return failed_result;
    task_runner = it->second;
  }
  std::unique_ptr<Task> task = task_runner->PopTaskFromQueue(wait_for_work);
  if (!task) return failed_result;
  DefaultForegroundTaskRunner::RunTaskScope scope(task_runner);
  task->Run();
  return true;
}
References foreground_task_runner_map_, v8::platform::kWaitForWork, and lock_.
RunIdleTasks()
void v8::platform::DefaultPlatform::RunIdleTasks (v8::Isolate * isolate, double idle_time_in_seconds)
Definition at line 177 of file default-platform.cc.
                                                                {
  DCHECK_EQ(IdleTaskSupport::kEnabled, idle_task_support_);
  std::shared_ptr<DefaultForegroundTaskRunner> task_runner;
  {
    base::MutexGuard guard(&lock_);
    if (foreground_task_runner_map_.find(isolate) ==
        foreground_task_runner_map_.end()) {
      return;
    }
    task_runner = foreground_task_runner_map_[isolate];
  }
  double deadline_in_seconds =
      MonotonicallyIncreasingTime() + idle_time_in_seconds;
  while (deadline_in_seconds > MonotonicallyIncreasingTime()) {
    std::unique_ptr<IdleTask> task = task_runner->PopTaskFromIdleQueue();
    if (!task) return;
    DefaultForegroundTaskRunner::RunTaskScope scope(task_runner);
    task->Run(deadline_in_seconds);
  }
}
References DCHECK_EQ, foreground_task_runner_map_, idle_task_support_, v8::platform::kEnabled, lock_, and MonotonicallyIncreasingTime().
SetTimeFunctionForTesting()
void v8::platform::DefaultPlatform::SetTimeFunctionForTesting (DefaultPlatform::TimeFunction time_function)
Definition at line 150 of file default-platform.cc.
                                               {
  base::MutexGuard guard(&lock_);
  time_function_for_testing_ = time_function;
  // The time function has to be right after the construction of the platform.
  DCHECK(foreground_task_runner_map_.empty());
}
References DCHECK, foreground_task_runner_map_, lock_, and time_function_for_testing_.
SetTracingController()
void v8::platform::DefaultPlatform::SetTracingController (std::unique_ptr< v8::TracingController > tracing_controller)
Definition at line 269 of file default-platform.cc.
                                                           {
  DCHECK_NOT_NULL(tracing_controller.get());
  tracing_controller_ = std::move(tracing_controller);
}
References DCHECK_NOT_NULL, and tracing_controller_.
Member Data Documentation
foreground_task_runner_map_
std::map<v8::Isolate*, std::shared_ptr<DefaultForegroundTaskRunner> > v8::platform::DefaultPlatform::foreground_task_runner_map_ [private]
Definition at line 111 of file default-platform.h.
Referenced by GetForegroundTaskRunner(), NotifyIsolateShutdown(), PumpMessageLoop(), RunIdleTasks(), SetTimeFunctionForTesting(), and ~DefaultPlatform().
idle_task_support_
IdleTaskSupport v8::platform::DefaultPlatform::idle_task_support_ [private]
Definition at line 107 of file default-platform.h.
Referenced by GetForegroundTaskRunner(), IdleTasksEnabled(), and RunIdleTasks().
lock_
base::Mutex v8::platform::DefaultPlatform::lock_ [private]
Definition at line 105 of file default-platform.h.
Referenced by GetForegroundTaskRunner(), NotifyIsolateShutdown(), PumpMessageLoop(), RunIdleTasks(), SetTimeFunctionForTesting(), and ~DefaultPlatform().
page_allocator_
std::unique_ptr<PageAllocator> v8::platform::DefaultPlatform::page_allocator_ [private]
Definition at line 114 of file default-platform.h.
Referenced by GetPageAllocator().
priority_mode_
const PriorityMode v8::platform::DefaultPlatform::priority_mode_ [private]
Definition at line 117 of file default-platform.h.
thread_isolated_allocator_
DefaultThreadIsolatedAllocator v8::platform::DefaultPlatform::thread_isolated_allocator_ [private]
Definition at line 115 of file default-platform.h.
Referenced by GetThreadIsolatedAllocator().
thread_pool_size_
const int v8::platform::DefaultPlatform::thread_pool_size_ [private]
Definition at line 106 of file default-platform.h.
Referenced by DefaultPlatform(), EnsureBackgroundTaskRunnerInitialized(), and NumberOfWorkerThreads().
time_function_for_testing_
TimeFunction v8::platform::DefaultPlatform::time_function_for_testing_ = nullptr [private]
Definition at line 118 of file default-platform.h.
Referenced by EnsureBackgroundTaskRunnerInitialized(), GetForegroundTaskRunner(), MonotonicallyIncreasingTime(), and SetTimeFunctionForTesting().
tracing_controller_
std::unique_ptr<TracingController> v8::platform::DefaultPlatform::tracing_controller_ [private]
Definition at line 113 of file default-platform.h.
Referenced by DefaultPlatform(), GetTracingController(), and SetTracingController().
worker_threads_task_runners_
std::shared_ptr<DefaultWorkerThreadsTaskRunner> v8::platform::DefaultPlatform::worker_threads_task_runners_[static_cast< int >(TaskPriority::kMaxPriority)+1] = {0} [private]
Definition at line 108 of file default-platform.h.
Referenced by EnsureBackgroundTaskRunnerInitialized(), PostDelayedTaskOnWorkerThreadImpl(), PostTaskOnWorkerThreadImpl(), and ~DefaultPlatform().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/libplatform/default-platform.h
/mnt/V8SourceCode/src/libplatform/default-platform.cc