v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNonNumberElementParameters Class Reference
Public Member Functions
TransitionAndStoreNonNumberElementParameters (MapRef fast_map, Type value_type)
MapRef fast_map () const
Type value_type () const
Private Attributes
MapRef const fast_map_
Type value_type_
Detailed Description
Definition at line 464 of file simplified-operator.cc.
Constructor & Destructor Documentation
TransitionAndStoreNonNumberElementParameters()
v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNonNumberElementParameters::TransitionAndStoreNonNumberElementParameters (MapRef fast_map, Type value_type)
Definition at line 477 of file simplified-operator.cc.
    : fast_map_(fast_map), value_type_(value_type) {}
Member Function Documentation
fast_map()
MapRef v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNonNumberElementParameters::fast_map () const [inline]
Definition at line 469 of file simplified-operator.cc.
{ return fast_map_; }
References fast_map_.
Referenced by v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::hash_value(), v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator<<(), and v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator==().
value_type()
Type v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNonNumberElementParameters::value_type () const [inline]
Definition at line 470 of file simplified-operator.cc.
{ return value_type_; }
References value_type_.
Referenced by v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::hash_value(), v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator<<(), and v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator==().
Member Data Documentation
fast_map_
MapRef const v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNonNumberElementParameters::fast_map_ [private]
Definition at line 473 of file simplified-operator.cc.
Referenced by fast_map().
value_type_
Type v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreNonNumberElementParameters::value_type_ [private]
Definition at line 474 of file simplified-operator.cc.
Referenced by value_type().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.cc