v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency Class Reference
Public Member Functions
InitialMapInstanceSizePredictionDependency (JSFunctionRef function, int instance_size)
bool IsValid (JSHeapBroker *broker) const override
void PrepareInstall (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
const JSFunctionRef function_
const int instance_size_
Additional Inherited Members
Detailed Description
Definition at line 1155 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
InitialMapInstanceSizePredictionDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency::InitialMapInstanceSizePredictionDependency (JSFunctionRef function, int instance_size) [inline]
Definition at line 1158 of file compilation-dependencies.cc.
      : CompilationDependency(kInitialMapInstanceSizePrediction),
        function_(function),
        instance_size_(instance_size) {}
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1192 of file compilation-dependencies.cc.
                                                                {
    const InitialMapInstanceSizePredictionDependency* const zat =
        that->AsInitialMapInstanceSizePrediction();
    return function_.equals(zat->function_) &&
           instance_size_ == zat->instance_size_;
  }
References function_, and instance_size_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1187 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(function_), instance_size_);
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 1179 of file compilation-dependencies.cc.
                                                                               {
    SLOW_DCHECK(IsValid(broker));
    DCHECK(!function_.object()
                ->initial_map()
                ->IsInobjectSlackTrackingInProgress());
  }
References broker(), v8::internal::DCHECK(), and SLOW_DCHECK.
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 1164 of file compilation-dependencies.cc.
                                                    {
    // The dependency is valid if the prediction is the same as the current
    // slack tracking result.
    if (!function_.object()->has_initial_map()) return false;
    int instance_size =
        function_.object()->ComputeInstanceSizeWithMinSlack(broker->isolate());
    return instance_size == instance_size_;
  }
References broker().
PrepareInstall()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency::PrepareInstall (JSHeapBroker * broker) const [inline], [override], [virtual]
Reimplemented from v8::internal::compiler::CompilationDependency.
Definition at line 1173 of file compilation-dependencies.cc.
                                                           {
    SLOW_DCHECK(IsValid(broker));
    function_.object()->CompleteInobjectSlackTrackingIfActive(
        broker->isolate());
  }
References broker(), and SLOW_DCHECK.
Member Data Documentation
function_
const JSFunctionRef v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency::function_ [private]
Definition at line 1199 of file compilation-dependencies.cc.
Referenced by Equals().
instance_size_
const int v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::InitialMapInstanceSizePredictionDependency::instance_size_ [private]
Definition at line 1200 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc