v8::internal::maglev::MaglevCodeGenState Class Reference
#include <maglev-code-gen-state.h>
Public Member Functions
MaglevCodeGenState (MaglevCompilationInfo *compilation_info, MaglevSafepointTableBuilder *safepoint_table_builder, uint32_t max_block_id)
void set_tagged_slots (int slots)
void set_untagged_slots (int slots)
void PushDeferredCode (DeferredCodeInfo *deferred_code)
const std::vector< DeferredCodeInfo * > & deferred_code () const
std::vector< DeferredCodeInfo * > TakeDeferredCode ()
void PushEagerDeopt (EagerDeoptInfo *info)
void PushLazyDeopt (LazyDeoptInfo *info)
const std::vector< EagerDeoptInfo * > & eager_deopts () const
const std::vector< LazyDeoptInfo * > & lazy_deopts () const
void PushHandlerInfo (NodeBase *node)
const std::vector< NodeBase * > & handlers () const
compiler::NativeContextRef native_context () const
compiler::JSHeapBroker * broker () const
MaglevGraphLabeller * graph_labeller () const
int stack_slots () const
int tagged_slots () const
uint16_t parameter_count () const
MaglevSafepointTableBuilder * safepoint_table_builder () const
MaglevCompilationInfo * compilation_info () const
Label * entry_label ()
void set_max_deopted_stack_size (uint32_t max_deopted_stack_size)
void set_max_call_stack_args_ (uint32_t max_call_stack_args)
uint32_t stack_check_offset ()
Label * osr_entry ()
BasicBlock * RealJumpTarget (BasicBlock *block)
Private Attributes
MaglevCompilationInfo *const compilation_info_
MaglevSafepointTableBuilder *const safepoint_table_builder_
std::vector< DeferredCodeInfo * > deferred_code_
std::vector< EagerDeoptInfo * > eager_deopts_
std::vector< LazyDeoptInfo * > lazy_deopts_
std::vector< NodeBase * > handlers_
int untagged_slots_ = 0
int tagged_slots_ = 0
uint32_t max_deopted_stack_size_ = kMaxUInt32
uint32_t max_call_stack_args_ = kMaxUInt32
Label entry_label_
Label osr_entry_
std::vector< BasicBlock * > real_jump_target_
Detailed Description
Definition at line 33 of file maglev-code-gen-state.h.
Constructor & Destructor Documentation
MaglevCodeGenState()
v8::internal::maglev::MaglevCodeGenState::MaglevCodeGenState (MaglevCompilationInfo * compilation_info, MaglevSafepointTableBuilder * safepoint_table_builder, uint32_t max_block_id) [inline]
Definition at line 35 of file maglev-code-gen-state.h.
      : compilation_info_(compilation_info),
        safepoint_table_builder_(safepoint_table_builder),
        real_jump_target_(max_block_id) {}
Member Function Documentation
broker()
compiler::JSHeapBroker* v8::internal::maglev::MaglevCodeGenState::broker () const [inline]
Definition at line 69 of file maglev-code-gen-state.h.
{ return compilation_info_->broker(); }
References v8::internal::maglev::MaglevCompilationInfo::broker(), and compilation_info_.
Referenced by native_context().
compilation_info()
MaglevCompilationInfo* v8::internal::maglev::MaglevCodeGenState::compilation_info () const [inline]
Definition at line 83 of file maglev-code-gen-state.h.
{ return compilation_info_; }
References compilation_info_.
Referenced by v8::internal::maglev::MaglevCodeGenerator::BuildCodeObject(), and v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData().
deferred_code()
const std::vector<DeferredCodeInfo*>& v8::internal::maglev::MaglevCodeGenState::deferred_code () const [inline]
Definition at line 48 of file maglev-code-gen-state.h.
                                                            {
    return deferred_code_;
  }
References deferred_code_.
Referenced by v8::internal::maglev::MaglevCodeGenerator::EmitDeferredCode(), and PushDeferredCode().
eager_deopts()
const std::vector<EagerDeoptInfo*>& v8::internal::maglev::MaglevCodeGenState::eager_deopts () const [inline]
Definition at line 56 of file maglev-code-gen-state.h.
                                                         {
    return eager_deopts_;
  }
References eager_deopts_.
Referenced by v8::internal::maglev::MaglevCodeGenerator::EmitDeopts(), v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), and v8::internal::maglev::MaglevAssembler::IsDeoptLabel().
entry_label()
Label* v8::internal::maglev::MaglevCodeGenState::entry_label () [inline]
Definition at line 85 of file maglev-code-gen-state.h.
{ return &entry_label_; }
References entry_label_.
graph_labeller()
MaglevGraphLabeller* v8::internal::maglev::MaglevCodeGenState::graph_labeller () const [inline]
Definition at line 70 of file maglev-code-gen-state.h.
                                              {
    return compilation_info_->graph_labeller();
  }
References compilation_info_, and v8::internal::maglev::MaglevCompilationInfo::graph_labeller().
handlers()
const std::vector<NodeBase*>& v8::internal::maglev::MaglevCodeGenState::handlers () const [inline]
Definition at line 64 of file maglev-code-gen-state.h.
{ return handlers_; }
References handlers_.
Referenced by v8::internal::maglev::MaglevCodeGenerator::EmitExceptionHandlerTrampolines(), and v8::internal::maglev::MaglevCodeGenerator::EmitMetadata().
lazy_deopts()
const std::vector<LazyDeoptInfo*>& v8::internal::maglev::MaglevCodeGenState::lazy_deopts () const [inline]
Definition at line 59 of file maglev-code-gen-state.h.
                                                       {
    return lazy_deopts_;
  }
References lazy_deopts_.
Referenced by v8::internal::maglev::MaglevCodeGenerator::EmitDeopts(), and v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData().
native_context()
compiler::NativeContextRef v8::internal::maglev::MaglevCodeGenState::native_context () const [inline]
Definition at line 66 of file maglev-code-gen-state.h.
                                                  {
    return broker()->target_native_context();
  }
References broker(), and v8::internal::compiler::JSHeapBroker::target_native_context().
osr_entry()
Label* v8::internal::maglev::MaglevCodeGenState::osr_entry () [inline]
Definition at line 117 of file maglev-code-gen-state.h.
{ return &osr_entry_; }
References osr_entry_.
Referenced by v8::internal::maglev::MaglevCodeGenerator::EmitCode(), and v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData().
parameter_count()
uint16_t v8::internal::maglev::MaglevCodeGenState::parameter_count () const [inline]
Definition at line 76 of file maglev-code-gen-state.h.
                                   {
    return compilation_info_->toplevel_compilation_unit()->parameter_count();
  }
References compilation_info_, v8::internal::maglev::MaglevCompilationUnit::parameter_count(), and v8::internal::maglev::MaglevCompilationInfo::toplevel_compilation_unit().
Referenced by v8::internal::maglev::MaglevCodeGenerator::parameter_count().
PushDeferredCode()
void v8::internal::maglev::MaglevCodeGenState::PushDeferredCode (DeferredCodeInfo * deferred_code) [inline]
Definition at line 45 of file maglev-code-gen-state.h.
                                                         {
    deferred_code_.push_back(deferred_code);
  }
References deferred_code(), and deferred_code_.
Referenced by v8::internal::maglev::MaglevAssembler::MakeDeferredCode().
PushEagerDeopt()
void v8::internal::maglev::MaglevCodeGenState::PushEagerDeopt (EagerDeoptInfo * info) [inline]
Definition at line 54 of file maglev-code-gen-state.h.
{ eager_deopts_.push_back(info); }
References eager_deopts_.
Referenced by v8::internal::maglev::MaglevAssembler::GetDeoptLabel().
PushHandlerInfo()
void v8::internal::maglev::MaglevCodeGenState::PushHandlerInfo (NodeBase * node) [inline]
Definition at line 63 of file maglev-code-gen-state.h.
{ handlers_.push_back(node); }
References handlers_.
Referenced by v8::internal::maglev::MaglevAssembler::DefineExceptionHandlerPoint().
PushLazyDeopt()
void v8::internal::maglev::MaglevCodeGenState::PushLazyDeopt (LazyDeoptInfo * info) [inline]
Definition at line 55 of file maglev-code-gen-state.h.
{ lazy_deopts_.push_back(info); }
References lazy_deopts_.
Referenced by v8::internal::maglev::MaglevAssembler::DefineLazyDeoptPoint(), and v8::internal::maglev::SaveRegisterStateForCall::DefineSafepointWithLazyDeopt().
RealJumpTarget()
BasicBlock * v8::internal::maglev::MaglevCodeGenState::RealJumpTarget (BasicBlock * block) [inline]
Definition at line 15 of file maglev-code-gen-state-inl.h.
                                                                       {
  if (!real_jump_target_[block->id()]) {
    real_jump_target_[block->id()] = block->ComputeRealJumpTarget();
  }
  return real_jump_target_[block->id()];
}
References v8::internal::maglev::BasicBlock::ComputeRealJumpTarget(), v8::internal::maglev::BasicBlock::id(), and real_jump_target_.
safepoint_table_builder()
MaglevSafepointTableBuilder* v8::internal::maglev::MaglevCodeGenState::safepoint_table_builder () const [inline]
Definition at line 80 of file maglev-code-gen-state.h.
                                                               {
    return safepoint_table_builder_;
  }
References safepoint_table_builder_.
set_max_call_stack_args_()
void v8::internal::maglev::MaglevCodeGenState::set_max_call_stack_args_ (uint32_t max_call_stack_args) [inline]
Definition at line 91 of file maglev-code-gen-state.h.
                                                              {
    max_call_stack_args_ = max_call_stack_args;
  }
References max_call_stack_args_.
set_max_deopted_stack_size()
void v8::internal::maglev::MaglevCodeGenState::set_max_deopted_stack_size (uint32_t max_deopted_stack_size) [inline]
Definition at line 87 of file maglev-code-gen-state.h.
                                                                   {
    max_deopted_stack_size_ = max_deopted_stack_size;
  }
References max_deopted_stack_size_.
set_tagged_slots()
void v8::internal::maglev::MaglevCodeGenState::set_tagged_slots (int slots) [inline]
Definition at line 42 of file maglev-code-gen-state.h.
{ tagged_slots_ = slots; }
References tagged_slots_.
set_untagged_slots()
void v8::internal::maglev::MaglevCodeGenState::set_untagged_slots (int slots) [inline]
Definition at line 43 of file maglev-code-gen-state.h.
{ untagged_slots_ = slots; }
References untagged_slots_.
stack_check_offset()
uint32_t v8::internal::maglev::MaglevCodeGenState::stack_check_offset () [inline]
Definition at line 95 of file maglev-code-gen-state.h.
                                {
    int32_t parameter_slots =
        compilation_info_->toplevel_compilation_unit()->parameter_count();
    uint32_t stack_slots = tagged_slots_ + untagged_slots_;
    DCHECK(is_int32(stack_slots));
    int32_t optimized_frame_height = parameter_slots * kSystemPointerSize +
                                     StandardFrameConstants::kFixedFrameSize +
                                     stack_slots * kSystemPointerSize;
    DCHECK(is_int32(max_deopted_stack_size_));
    int32_t signed_max_unoptimized_frame_height =
        static_cast<int32_t>(max_deopted_stack_size_);
    // The offset is either the delta between the optimized frames and the
    // interpreted frame, or the maximal number of bytes pushed to the stack
    // while preparing for function calls, whichever is bigger.
    uint32_t frame_height_delta = static_cast<uint32_t>(std::max(
        signed_max_unoptimized_frame_height - optimized_frame_height, 0));
    uint32_t max_pushed_argument_bytes =
        static_cast<uint32_t>(max_call_stack_args_ * kSystemPointerSize);
    return std::max(frame_height_delta, max_pushed_argument_bytes);
  }
References compilation_info_, v8::internal::DCHECK(), v8::internal::StandardFrameConstants::kFixedFrameSize, v8::internal::kSystemPointerSize, max_call_stack_args_, max_deopted_stack_size_, v8::internal::maglev::MaglevCompilationUnit::parameter_count(), stack_slots(), tagged_slots_, v8::internal::maglev::MaglevCompilationInfo::toplevel_compilation_unit(), and untagged_slots_.
stack_slots()
int v8::internal::maglev::MaglevCodeGenState::stack_slots () const [inline]
Definition at line 73 of file maglev-code-gen-state.h.
{ return untagged_slots_ + tagged_slots_; }
References tagged_slots_, and untagged_slots_.
Referenced by stack_check_offset(), and v8::internal::maglev::MaglevCodeGenerator::stack_slot_count().
tagged_slots()
int v8::internal::maglev::MaglevCodeGenState::tagged_slots () const [inline]
Definition at line 74 of file maglev-code-gen-state.h.
{ return tagged_slots_; }
References tagged_slots_.
TakeDeferredCode()
std::vector<DeferredCodeInfo*> v8::internal::maglev::MaglevCodeGenState::TakeDeferredCode () [inline]
Definition at line 51 of file maglev-code-gen-state.h.
                                                  {
    return std::exchange(deferred_code_, std::vector<DeferredCodeInfo*>());
  }
References deferred_code_.
Referenced by v8::internal::maglev::MaglevCodeGenerator::EmitDeferredCode().
Member Data Documentation
compilation_info_
MaglevCompilationInfo* const v8::internal::maglev::MaglevCodeGenState::compilation_info_ [private]
Definition at line 122 of file maglev-code-gen-state.h.
Referenced by broker(), compilation_info(), graph_labeller(), parameter_count(), and stack_check_offset().
deferred_code_
std::vector<DeferredCodeInfo*> v8::internal::maglev::MaglevCodeGenState::deferred_code_ [private]
Definition at line 125 of file maglev-code-gen-state.h.
Referenced by deferred_code(), PushDeferredCode(), and TakeDeferredCode().
eager_deopts_
std::vector<EagerDeoptInfo*> v8::internal::maglev::MaglevCodeGenState::eager_deopts_ [private]
Definition at line 126 of file maglev-code-gen-state.h.
Referenced by eager_deopts(), and PushEagerDeopt().
entry_label_
Label v8::internal::maglev::MaglevCodeGenState::entry_label_ [private]
Definition at line 136 of file maglev-code-gen-state.h.
Referenced by entry_label().
handlers_
std::vector<NodeBase*> v8::internal::maglev::MaglevCodeGenState::handlers_ [private]
Definition at line 128 of file maglev-code-gen-state.h.
Referenced by handlers(), and PushHandlerInfo().
lazy_deopts_
std::vector<LazyDeoptInfo*> v8::internal::maglev::MaglevCodeGenState::lazy_deopts_ [private]
Definition at line 127 of file maglev-code-gen-state.h.
Referenced by lazy_deopts(), and PushLazyDeopt().
max_call_stack_args_
uint32_t v8::internal::maglev::MaglevCodeGenState::max_call_stack_args_ = kMaxUInt32 [private]
Definition at line 133 of file maglev-code-gen-state.h.
Referenced by set_max_call_stack_args_(), and stack_check_offset().
max_deopted_stack_size_
uint32_t v8::internal::maglev::MaglevCodeGenState::max_deopted_stack_size_ = kMaxUInt32 [private]
Definition at line 132 of file maglev-code-gen-state.h.
Referenced by set_max_deopted_stack_size(), and stack_check_offset().
osr_entry_
Label v8::internal::maglev::MaglevCodeGenState::osr_entry_ [private]
Definition at line 137 of file maglev-code-gen-state.h.
Referenced by osr_entry().
real_jump_target_
std::vector<BasicBlock*> v8::internal::maglev::MaglevCodeGenState::real_jump_target_ [private]
Definition at line 140 of file maglev-code-gen-state.h.
Referenced by RealJumpTarget().
safepoint_table_builder_
MaglevSafepointTableBuilder* const v8::internal::maglev::MaglevCodeGenState::safepoint_table_builder_ [private]
Definition at line 123 of file maglev-code-gen-state.h.
Referenced by safepoint_table_builder().
tagged_slots_
int v8::internal::maglev::MaglevCodeGenState::tagged_slots_ = 0 [private]
Definition at line 131 of file maglev-code-gen-state.h.
Referenced by set_tagged_slots(), stack_check_offset(), stack_slots(), and tagged_slots().
untagged_slots_
int v8::internal::maglev::MaglevCodeGenState::untagged_slots_ = 0 [private]
Definition at line 130 of file maglev-code-gen-state.h.
Referenced by set_untagged_slots(), stack_check_offset(), and stack_slots().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-code-gen-state.h
/mnt/V8SourceCode/src/maglev/maglev-code-gen-state-inl.h