v8::internal::BytecodeOffset Class Reference
#include <utils.h>
Public Member Functions
constexpr BytecodeOffset (int id)
constexpr int ToInt () const
constexpr bool IsNone () const
bool operator== (const BytecodeOffset &other) const
bool operator!= (const BytecodeOffset &other) const
Static Public Member Functions
static constexpr BytecodeOffset None ()
static BytecodeOffset ConstructStubCreate ()
static BytecodeOffset ConstructStubInvoke ()
Private Attributes
int id_
Static Private Attributes
static const int kNoneId = -1
static const int kFirstBuiltinContinuationId = 1
Friends
class Builtins
size_t hash_value (BytecodeOffset)
V8_EXPORT_PRIVATE friend std::ostream & operator<< (std::ostream &, BytecodeOffset)
Detailed Description
Definition at line 674 of file utils.h.
Constructor & Destructor Documentation
BytecodeOffset()
constexpr v8::internal::BytecodeOffset::BytecodeOffset (int id) [inline], [explicit], [constexpr]
Definition at line 676 of file utils.h.
: id_(id) {}
Referenced by ConstructStubCreate(), ConstructStubInvoke(), and None().
Member Function Documentation
ConstructStubCreate()
static BytecodeOffset v8::internal::BytecodeOffset::ConstructStubCreate () [inline], [static]
Definition at line 685 of file utils.h.
{ return BytecodeOffset(1); }
References BytecodeOffset().
ConstructStubInvoke()
static BytecodeOffset v8::internal::BytecodeOffset::ConstructStubInvoke () [inline], [static]
Definition at line 686 of file utils.h.
{ return BytecodeOffset(2); }
References BytecodeOffset().
IsNone()
constexpr bool v8::internal::BytecodeOffset::IsNone () const [inline], [constexpr]
Definition at line 688 of file utils.h.
{ return id_ == kNoneId; }
References id_, and kNoneId.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), v8::internal::anonymous_namespace{runtime-compiler.cc}::DeoptAllOsrLoopsContainingDeoptExit(), v8::internal::Deoptimizer::DeoptExitIsInsideOsrLoop(), v8::internal::anonymous_namespace{runtime-compiler.cc}::GetOsrOffsetAndFunctionForOSR(), v8::internal::anonymous_namespace{compiler.cc}::IsOSR(), v8::internal::FactoryBase< Impl >::NewCode(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Factory::CodeBuilder::set_osr_offset(), and v8::internal::JSFunction::SetTieringInProgress().
None()
static constexpr BytecodeOffset v8::internal::BytecodeOffset::None () [inline], [static], [constexpr]
Definition at line 679 of file utils.h.
{ return BytecodeOffset(kNoneId); }
References BytecodeOffset(), and kNoneId.
Referenced by v8::internal::GcSafeCode::CanDeoptAt(), v8::internal::compiler::JSInliner::CreateArtificialFrameState(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::CreateConstructInvokeStubFrameState(), v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), v8::internal::maglev::DeoptFrame::GetBytecodeOffset(), v8::internal::MaglevFrame::GetBytecodeOffsetForOSR(), v8::internal::maglev::MaglevGraphBuilder::MaglevGraphBuilder(), v8::internal::Factory::NewCodeObjectForEmbeddedBuiltin(), v8::internal::anonymous_namespace{runtime-test.cc}::OffsetOfNextJumpLoop(), v8::internal::anonymous_namespace{builtins-riscv.cc}::OnStackReplacement(), v8::internal::maglev::MaglevCompilationUnit::osr_offset(), v8::internal::compiler::JSInliner::ReduceJSCall(), v8::internal::maglev::MaglevGraphLabeller::RegisterNode(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{compiler.cc}::SpawnDuplicateConcurrentJobForStressTesting(), v8::internal::maglev::anonymous_namespace{maglev-compilation-info.cc}::SpecializeToFunctionContext(), and v8::internal::maglev::MaglevCompilationInfo::toplevel_is_osr().
operator!=()
bool v8::internal::BytecodeOffset::operator!= (const BytecodeOffset & other) const [inline]
Definition at line 692 of file utils.h.
                                                     {
    return id_ != other.id_;
  }
References id_.
operator==()
bool v8::internal::BytecodeOffset::operator== (const BytecodeOffset & other) const [inline]
Definition at line 689 of file utils.h.
                                                     {
    return id_ == other.id_;
  }
References id_.
ToInt()
constexpr int v8::internal::BytecodeOffset::ToInt () const [inline], [constexpr]
Definition at line 677 of file utils.h.
{ return id_; }
References id_.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), v8::internal::maglev::MaglevGraphBuilder::bailout_for_entrypoint(), v8::internal::FrameTranslationBuilder::BeginBuiltinContinuationFrame(), v8::internal::FrameTranslationBuilder::BeginInterpretedFrame(), v8::internal::FrameTranslationBuilder::BeginJavaScriptBuiltinContinuationFrame(), v8::internal::FrameTranslationBuilder::BeginJavaScriptBuiltinContinuationWithCatchFrame(), v8::internal::anonymous_namespace{runtime-compiler.cc}::CompileOptimizedOSRFromMaglev(), v8::internal::TranslatedState::CreateNextTranslatedFrame(), v8::internal::anonymous_namespace{runtime-compiler.cc}::DeoptAllOsrLoopsContainingDeoptExit(), v8::internal::Deoptimizer::DeoptExitIsInsideOsrLoop(), v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), v8::internal::anonymous_namespace{compiler.cc}::OptimizedCodeCache::Get(), v8::internal::anonymous_namespace{compiler.cc}::OptimizedCodeCache::Insert(), v8::internal::anonymous_namespace{deoptimizer.cc}::LookupCatchHandler(), v8::internal::maglev::MaglevGraphBuilder::MaglevGraphBuilder(), v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameStateForOSREntryStackCheck(), v8::internal::RUNTIME_FUNCTION(), v8::internal::Deoptimizer::TraceDeoptBegin(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizedCodeCacheHit(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRAvailable(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRFinished(), v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRStarted(), and v8::internal::anonymous_namespace{compiler.cc}::CompilerTracer::TraceOptimizeOSRUnavailable().
Friends And Related Function Documentation
Builtins
friend class Builtins [friend]
Definition at line 700 of file utils.h.
hash_value
size_t hash_value (BytecodeOffset id) [friend]
Definition at line 30 of file utils.cc.
                                     {
  base::hash<int> h;
  return h(id.id_);
}
operator<<
V8_EXPORT_PRIVATE friend std::ostream& operator<< (std::ostream & os, BytecodeOffset id) [friend]
Definition at line 35 of file utils.cc.
                                                          {
  return os << id.id_;
}
Member Data Documentation
id_
int v8::internal::BytecodeOffset::id_ [private]
Definition at line 710 of file utils.h.
Referenced by IsNone(), operator!=(), operator==(), and ToInt().
kFirstBuiltinContinuationId
const int v8::internal::BytecodeOffset::kFirstBuiltinContinuationId = 1 [static], [private]
Definition at line 708 of file utils.h.
Referenced by v8::internal::Builtins::GetBuiltinFromBytecodeOffset(), and v8::internal::Builtins::GetContinuationBytecodeOffset().
kNoneId
const int v8::internal::BytecodeOffset::kNoneId = -1 [static], [private]
Definition at line 702 of file utils.h.
Referenced by IsNone(), and None().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/utils.h