v8::internal::CallSiteInfo Class Reference
#include <call-site-info.h>
Classes
class BodyDescriptor
Public Member Functions
bool IsStrict () const
bool IsConstructor () const
bool IsAsync () const
bool IsEval () const
bool IsUserJavaScript () const
bool IsSubjectToDebugging () const
bool IsMethodCall () const
bool IsToplevel () const
bool IsPromiseAll () const
bool IsPromiseAllSettled () const
bool IsPromiseAny () const
bool IsNative () const
Tagged< HeapObject > code_object (IsolateForSandbox isolate) const
void set_code_object (Tagged< HeapObject > code, WriteBarrierMode mode)
int GetScriptId () const
Tagged< Object > GetScriptName () const
Tagged< Object > GetScriptNameOrSourceURL () const
Tagged< Object > GetScriptSource () const
Tagged< Object > GetScriptSourceMappingURL () const
Static Public Member Functions
static V8_EXPORT_PRIVATE int GetLineNumber (DirectHandle< CallSiteInfo > info)
static V8_EXPORT_PRIVATE int GetColumnNumber (DirectHandle< CallSiteInfo > info)
static int GetEnclosingLineNumber (DirectHandle< CallSiteInfo > info)
static int GetEnclosingColumnNumber (DirectHandle< CallSiteInfo > info)
static MaybeDirectHandle< Script > GetScript (Isolate *isolate, DirectHandle< CallSiteInfo > info)
static Handle< PrimitiveHeapObject > GetEvalOrigin (DirectHandle< CallSiteInfo > info)
static V8_EXPORT_PRIVATE DirectHandle< PrimitiveHeapObject > GetFunctionName (DirectHandle< CallSiteInfo > info)
static DirectHandle< String > GetFunctionDebugName (DirectHandle< CallSiteInfo > info)
static DirectHandle< Object > GetMethodName (DirectHandle< CallSiteInfo > info)
static DirectHandle< String > GetScriptHash (DirectHandle< CallSiteInfo > info)
static DirectHandle< Object > GetTypeName (DirectHandle< CallSiteInfo > info)
static int GetSourcePosition (DirectHandle< CallSiteInfo > info)
static bool ComputeLocation (DirectHandle< CallSiteInfo > info, MessageLocation *location)
Static Public Attributes
static constexpr int kUnknown = kNoSourcePosition
Private Member Functions
std::optional< Tagged< Script > > GetScript () const
Tagged< SharedFunctionInfo > GetSharedFunctionInfo () const
Static Private Member Functions
static int ComputeSourcePosition (DirectHandle< CallSiteInfo > info, int offset)
Detailed Description
Definition at line 24 of file call-site-info.h.
Member Function Documentation
code_object()
Tagged< HeapObject > v8::internal::CallSiteInfo::code_object (IsolateForSandbox isolate) const [inline]
Definition at line 40 of file call-site-info-inl.h.
                                                                            {
  DCHECK(!IsTrustedPointerFieldEmpty(kCodeObjectOffset));
  // The field can contain either a Code or a BytecodeArray, so we need to use
  // the kUnknownIndirectPointerTag. Since we can then no longer rely on the
  // type-checking mechanism of trusted pointers we need to perform manual type
  // checks afterwards.
  Tagged<HeapObject> code_object =
      ReadTrustedPointerField<kUnknownIndirectPointerTag>(kCodeObjectOffset,
                                                          isolate);
  CHECK(IsCode(code_object) || IsBytecodeArray(code_object));
  return code_object;
}
References CHECK, and v8::internal::DCHECK().
ComputeLocation()
bool v8::internal::CallSiteInfo::ComputeLocation (DirectHandle< CallSiteInfo > info, MessageLocation * location) [static]
Definition at line 587 of file call-site-info.cc.
                                                              {
  Isolate* isolate = Isolate::Current();
#if V8_ENABLE_WEBASSEMBLY
  if (info->IsWasm()) {
    int pos = GetSourcePosition(info);
    Handle<Script> script(info->GetWasmInstance()->module_object()->script(),
                          isolate);
    *location = MessageLocation(script, pos, pos + 1);
    return true;
  }
  if (info->IsBuiltin()) {
    return false;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  Handle<SharedFunctionInfo> shared(info->GetSharedFunctionInfo(), isolate);
  if (!shared->IsSubjectToDebugging()) return false;
  Handle<Script> script(Cast<Script>(shared->script()), isolate);
  if (IsUndefined(script->source())) return false;
  if (info->flags() & kIsSourcePositionComputed ||
      (shared->HasBytecodeArray() &&
       shared->GetBytecodeArray(isolate)->HasSourcePositionTable())) {
    int pos = GetSourcePosition(info);
    *location = MessageLocation(script, pos, pos + 1, shared);
  } else {
    int code_offset = info->code_offset_or_source_position();
    *location = MessageLocation(script, shared, code_offset);
  }
  return true;
}
References v8::internal::Isolate::Current(), GetSourcePosition(), and v8::internal::script.
Referenced by v8::internal::Isolate::ComputeLocationFromSimpleStackTrace().
ComputeSourcePosition()
int v8::internal::CallSiteInfo::ComputeSourcePosition (DirectHandle< CallSiteInfo > info, int offset) [static], [private]
Definition at line 620 of file call-site-info.cc.
                                                    {
  Isolate* isolate = Isolate::Current();
#if V8_ENABLE_WEBASSEMBLY
#if V8_ENABLE_DRUMBRAKE
  if (info->IsWasmInterpretedFrame()) {
    auto module = info->GetWasmInstance()->module();
    uint32_t func_index = info->GetWasmFunctionIndex();
    return wasm::GetSourcePosition(module, func_index, offset,
                                   info->IsAsmJsAtNumberConversion());
  } else {
#endif // V8_ENABLE_DRUMBRAKE
    if (info->IsWasm()) {
      auto module = info->GetWasmInstance()->trusted_data(isolate)->module();
      uint32_t func_index = info->GetWasmFunctionIndex();
      return wasm::GetSourcePosition(module, func_index, offset,
                                     info->IsAsmJsAtNumberConversion());
    }
#if V8_ENABLE_DRUMBRAKE
  }
#endif // V8_ENABLE_DRUMBRAKE
  if (info->IsBuiltin()) {
    return 0;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  DirectHandle<SharedFunctionInfo> shared(info->GetSharedFunctionInfo(),
                                          isolate);
  SharedFunctionInfo::EnsureSourcePositionsAvailable(isolate, shared);
  Tagged<HeapObject> code = info->code_object(isolate);
  DCHECK(IsCode(code) || IsBytecodeArray(code));
  return Cast<AbstractCode>(code)->SourcePosition(isolate, offset);
}
References code, v8::internal::Isolate::Current(), v8::internal::DCHECK(), v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable(), and v8::internal::wasm::GetSourcePosition().
Referenced by GetSourcePosition().
GetColumnNumber()
int v8::internal::CallSiteInfo::GetColumnNumber (DirectHandle< CallSiteInfo > info) [static]
Definition at line 97 of file call-site-info.cc.
                                                                          {
  Isolate* isolate = Isolate::Current();
  int position = GetSourcePosition(callsite_info);
#if V8_ENABLE_WEBASSEMBLY
  if (callsite_info->IsWasm() && !callsite_info->IsAsmJsWasm()) {
    return position + 1;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  DirectHandle<Script> script;
  if (GetScript(isolate, callsite_info).ToHandle(&script)) {
    Script::PositionInfo position_info;
    Script::GetPositionInfo(script, position, &position_info);
    int column_number = position_info.column + 1;
    if (script->HasSourceURLComment() &&
        position_info.line == script->line_offset()) {
      column_number -= script->column_offset();
    }
    return column_number;
  }
  return Message::kNoColumnInfo;
}
References v8::internal::Script::PositionInfo::column, v8::internal::Isolate::Current(), v8::internal::Script::GetPositionInfo(), GetScript(), GetSourcePosition(), v8::Message::kNoColumnInfo, v8::internal::Script::PositionInfo::line, v8::internal::script, and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::anonymous_namespace{call-site-info.cc}::AppendFileLocation(), and v8::internal::BUILTIN().
GetEnclosingColumnNumber()
int v8::internal::CallSiteInfo::GetEnclosingColumnNumber (DirectHandle< CallSiteInfo > info) [static]
Definition at line 145 of file call-site-info.cc.
                                                                          {
  Isolate* isolate = Isolate::Current();
#if V8_ENABLE_WEBASSEMBLY
  if (info->IsWasm() && !info->IsAsmJsWasm()) {
    auto* module = info->GetWasmInstance()->module();
    auto func_index = info->GetWasmFunctionIndex();
    return GetWasmFunctionOffset(module, func_index);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  DirectHandle<Script> script;
  if (!GetScript(isolate, info).ToHandle(&script)) {
    return Message::kNoColumnInfo;
  }
#if V8_ENABLE_WEBASSEMBLY
  if (info->IsAsmJsWasm()) {
    auto* module = info->GetWasmInstance()->module();
    auto func_index = info->GetWasmFunctionIndex();
    int position = wasm::GetSourcePosition(module, func_index, 0,
                                           info->IsAsmJsAtNumberConversion());
    return Script::GetColumnNumber(script, position) + 1;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  int position = info->GetSharedFunctionInfo()->function_token_position();
  return Script::GetColumnNumber(script, position) + 1;
}
References v8::internal::Isolate::Current(), v8::internal::Script::GetColumnNumber(), GetScript(), v8::internal::wasm::GetSourcePosition(), v8::internal::wasm::GetWasmFunctionOffset(), v8::Message::kNoColumnInfo, v8::internal::script, and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::BUILTIN().
GetEnclosingLineNumber()
int v8::internal::CallSiteInfo::GetEnclosingLineNumber (DirectHandle< CallSiteInfo > info) [static]
Definition at line 120 of file call-site-info.cc.
                                                                        {
  Isolate* isolate = Isolate::Current();
#if V8_ENABLE_WEBASSEMBLY
  if (info->IsWasm() && !info->IsAsmJsWasm()) {
    return 1;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  DirectHandle<Script> script;
  if (!GetScript(isolate, info).ToHandle(&script)) {
    return Message::kNoLineNumberInfo;
  }
#if V8_ENABLE_WEBASSEMBLY
  if (info->IsAsmJsWasm()) {
    auto* module = info->GetWasmInstance()->module();
    auto func_index = info->GetWasmFunctionIndex();
    int position = wasm::GetSourcePosition(module, func_index, 0,
                                           info->IsAsmJsAtNumberConversion());
    return Script::GetLineNumber(script, position) + 1;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  int position = info->GetSharedFunctionInfo()->function_token_position();
  return Script::GetLineNumber(script, position) + 1;
}
References v8::internal::Isolate::Current(), v8::internal::Script::GetLineNumber(), GetScript(), v8::internal::wasm::GetSourcePosition(), v8::Message::kNoLineNumberInfo, v8::internal::script, and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::BUILTIN().
GetEvalOrigin()
Handle< PrimitiveHeapObject > v8::internal::CallSiteInfo::GetEvalOrigin (DirectHandle< CallSiteInfo > info) [static]
Definition at line 279 of file call-site-info.cc.
                                     {
  auto isolate = Isolate::Current();
  DirectHandle<Script> script;
  if (!GetScript(isolate, info).ToHandle(&script) ||
      script->compilation_type() != Script::CompilationType::kEval) {
    return isolate->factory()->undefined_value();
  }
  return FormatEvalOrigin(isolate, script).ToHandleChecked();
}
References v8::internal::Isolate::Current(), v8::internal::anonymous_namespace{call-site-info.cc}::FormatEvalOrigin(), GetScript(), v8::internal::Script::kEval, v8::internal::script, and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::anonymous_namespace{call-site-info.cc}::AppendFileLocation(), and v8::internal::BUILTIN().
GetFunctionDebugName()
DirectHandle< String > v8::internal::CallSiteInfo::GetFunctionDebugName (DirectHandle< CallSiteInfo > info) [static]
Definition at line 333 of file call-site-info.cc.
                                     {
  Isolate* isolate = Isolate::Current();
#if V8_ENABLE_WEBASSEMBLY
  if (info->IsWasm()) {
    return GetWasmFunctionDebugName(
        isolate,
        direct_handle(info->GetWasmInstance()->trusted_data(isolate), isolate),
        info->GetWasmFunctionIndex());
  }
  if (info->IsBuiltin()) {
    return Cast<String>(GetFunctionName(info));
  }
#endif // V8_ENABLE_WEBASSEMBLY
  DirectHandle<JSFunction> function(Cast<JSFunction>(info->function()),
                                    isolate);
  DirectHandle<String> name = JSFunction::GetDebugName(isolate, function);
  if (name->length() == 0 && info->IsEval()) {
    name = isolate->factory()->eval_string();
  }
  return name;
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::JSFunction::GetDebugName(), GetFunctionName(), v8::internal::GetWasmFunctionDebugName(), and v8::internal::name.
Referenced by v8::internal::anonymous_namespace{isolate.cc}::GetDetailedStackTraceFromCallSiteInfos().
GetFunctionName()
DirectHandle< PrimitiveHeapObject > v8::internal::CallSiteInfo::GetFunctionName (DirectHandle< CallSiteInfo > info) [static]
Definition at line 291 of file call-site-info.cc.
                                     {
  Isolate* isolate = Isolate::Current();
#if V8_ENABLE_WEBASSEMBLY
  if (info->IsWasm()) {
    DirectHandle<WasmModuleObject> module_object(
        info->GetWasmInstance()->module_object(), isolate);
    uint32_t func_index = info->GetWasmFunctionIndex();
    DirectHandle<String> name;
    if (WasmModuleObject::GetFunctionNameOrNull(isolate, module_object,
                                                func_index)
            .ToHandle(&name)) {
      return name;
    }
    return isolate->factory()->null_value();
  }
  if (info->IsBuiltin()) {
    Builtin builtin = Builtins::FromInt(Cast<Smi>(info->function()).value());
    return isolate->factory()->NewStringFromAsciiChecked(
        Builtins::NameForStackTrace(isolate, builtin));
  }
#endif // V8_ENABLE_WEBASSEMBLY
  DirectHandle<JSFunction> function(Cast<JSFunction>(info->function()),
                                    isolate);
  if (function->shared()->HasBuiltinId()) {
    Builtin builtin = function->shared()->builtin_id();
    const char* maybe_known_name =
        Builtins::NameForStackTrace(isolate, builtin);
    if (maybe_known_name) {
      // This is for cases where using the builtin's name allows us to print
      // e.g. "String.indexOf", instead of just "indexOf" which is what we
      // would infer below.
      return isolate->factory()->NewStringFromAsciiChecked(maybe_known_name);
    }
  }
  DirectHandle<String> name = JSFunction::GetDebugName(isolate, function);
  if (name->length() != 0) return name;
  if (info->IsEval()) return isolate->factory()->eval_string();
  return isolate->factory()->null_value();
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), v8::internal::Builtins::FromInt(), v8::internal::JSFunction::GetDebugName(), v8::internal::WasmModuleObject::GetFunctionNameOrNull(), v8::internal::name, v8::internal::Builtins::NameForStackTrace(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::anonymous_namespace{call-site-info.cc}::AppendMethodCall(), v8::internal::BUILTIN(), GetFunctionDebugName(), and v8::internal::anonymous_namespace{call-site-info.cc}::SerializeJSStackFrame().
GetLineNumber()
int v8::internal::CallSiteInfo::GetLineNumber (DirectHandle< CallSiteInfo > info) [static]
Definition at line 77 of file call-site-info.cc.
                                                               {
  Isolate* isolate = Isolate::Current();
#if V8_ENABLE_WEBASSEMBLY
  if (info->IsWasm() && !info->IsAsmJsWasm()) {
    return 1;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  DirectHandle<Script> script;
  if (GetScript(isolate, info).ToHandle(&script)) {
    int position = GetSourcePosition(info);
    int line_number = Script::GetLineNumber(script, position) + 1;
    if (script->HasSourceURLComment()) {
      line_number -= script->line_offset();
    }
    return line_number;
  }
  return Message::kNoLineNumberInfo;
}
References v8::internal::Isolate::Current(), v8::internal::Script::GetLineNumber(), GetScript(), GetSourcePosition(), v8::Message::kNoLineNumberInfo, v8::internal::script, and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::anonymous_namespace{call-site-info.cc}::AppendFileLocation(), and v8::internal::BUILTIN().
GetMethodName()
DirectHandle< Object > v8::internal::CallSiteInfo::GetMethodName (DirectHandle< CallSiteInfo > info) [static]
Definition at line 452 of file call-site-info.cc.
                                     {
  Isolate* isolate = Isolate::Current();
  DirectHandle<Object> receiver_or_instance(info->receiver_or_instance(),
                                            isolate);
#if V8_ENABLE_WEBASSEMBLY
  if (info->IsWasm()) return isolate->factory()->null_value();
#endif // V8_ENABLE_WEBASSEMBLY
  if (IsNullOrUndefined(*receiver_or_instance, isolate)) {
    return isolate->factory()->null_value();
  }
  DirectHandle<JSFunction> function(Cast<JSFunction>(info->function()),
                                    isolate);
  // Class members initializer function is not a method.
  if (IsClassMembersInitializerFunction(function->shared()->kind())) {
    return isolate->factory()->null_value();
  }
  DirectHandle<JSReceiver> receiver =
      Object::ToObject(isolate, receiver_or_instance).ToHandleChecked();
  Handle<String> name(function->shared()->Name(), isolate);
  name = String::Flatten(isolate, name);
  // ES2015 gives getters and setters name prefixes which must
  // be stripped to find the property name.
  if (name->HasOneBytePrefix(base::CStrVector("get ")) ||
      name->HasOneBytePrefix(base::CStrVector("set "))) {
    name = isolate->factory()->NewProperSubString(name, 4, name->length());
  } else if (name->length() == 0) {
    // The function doesn't have a meaningful "name" property, however
    // the parser does store an inferred name "o.foo" for the common
    // case of `o.foo = function() {...}`, so see if we can derive a
    // property name to guess from that.
    name = handle(function->shared()->inferred_name(), isolate);
    for (int index = name->length(); --index >= 0;) {
      if (name->Get(index, isolate) == '.') {
        name = isolate->factory()->NewProperSubString(name, index + 1,
                                                      name->length());
        break;
      }
    }
  }
  if (name->length() != 0) {
    PropertyKey key(isolate, Cast<Name>(name));
    LookupIterator it(isolate, receiver, key,
                      LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR);
    if (it.state() == LookupIterator::DATA) {
      if (it.GetDataValue().is_identical_to(function)) {
        return name;
      }
    } else if (it.state() == LookupIterator::ACCESSOR) {
      DirectHandle<Object> accessors = it.GetAccessors();
      if (IsAccessorPair(*accessors)) {
        auto pair = Cast<AccessorPair>(accessors);
        if (pair->getter() == *function || pair->setter() == *function) {
          return name;
        }
      }
    }
  }
  return direct_handle(InferMethodName(isolate, *receiver, *function), isolate);
}
References v8::internal::LookupIterator::ACCESSOR, v8::base::CStrVector(), v8::internal::Isolate::Current(), v8::internal::LookupIterator::DATA, v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::LookupIterator::GetAccessors(), v8::internal::LookupIterator::GetDataValue(), v8::internal::handle(), v8::internal::index, v8::internal::anonymous_namespace{call-site-info.cc}::InferMethodName(), v8::internal::HandleBase::is_identical_to(), v8::internal::IsClassMembersInitializerFunction(), v8::internal::IsNullOrUndefined(), v8::internal::key, v8::internal::name, v8::internal::Factory::NewProperSubString(), v8::internal::LookupIterator::PROTOTYPE_CHAIN_SKIP_INTERCEPTOR, v8::internal::LookupIterator::state(), and v8::Value::ToObject().
Referenced by v8::internal::anonymous_namespace{call-site-info.cc}::AppendMethodCall(), and v8::internal::BUILTIN().
GetScript() [1/2]
std::optional< Tagged< Script > > v8::internal::CallSiteInfo::GetScript () const [private]
Definition at line 653 of file call-site-info.cc.
                                                          {
#if V8_ENABLE_WEBASSEMBLY
  if (IsWasm()) {
    return GetWasmInstance()
        ->trusted_data(Isolate::Current())
        ->module_object()
        ->script();
  }
  if (IsBuiltin()) {
    return std::nullopt;
  }
#endif // V8_ENABLE_WEBASSEMBLY
  Tagged<Object> script = GetSharedFunctionInfo()->script();
  if (IsScript(script)) return Cast<Script>(script);
  return std::nullopt;
}
References v8::internal::Isolate::Current(), GetSharedFunctionInfo(), and v8::internal::script.
Referenced by GetColumnNumber(), v8::internal::anonymous_namespace{isolate.cc}::GetDetailedStackTraceFromCallSiteInfos(), GetEnclosingColumnNumber(), GetEnclosingLineNumber(), GetEvalOrigin(), GetLineNumber(), GetScriptHash(), GetScriptId(), GetScriptName(), GetScriptNameOrSourceURL(), GetScriptSource(), GetScriptSourceMappingURL(), IsEval(), and IsNative().
GetScript() [2/2]
MaybeDirectHandle< Script > v8::internal::CallSiteInfo::GetScript (Isolate * isolate, DirectHandle< CallSiteInfo > info) [static]
Definition at line 679 of file call-site-info.cc.
                                                       {
  if (auto script = info->GetScript()) {
    return direct_handle(*script, isolate);
  }
  return kNullMaybeHandle;
}
References v8::internal::direct_handle(), v8::internal::kNullMaybeHandle, and v8::internal::script.
GetScriptHash()
DirectHandle< String > v8::internal::CallSiteInfo::GetScriptHash (DirectHandle< CallSiteInfo > info) [static]
Definition at line 209 of file call-site-info.cc.
                                     {
  DirectHandle<Script> script;
  Isolate* isolate = Isolate::Current();
  if (!GetScript(isolate, info).ToHandle(&script)) {
    return isolate->factory()->empty_string();
  }
  if (script->HasValidSource()) {
    return Script::GetScriptHash(isolate, script, /*forceForInspector:*/ false);
  }
  return isolate->factory()->empty_string();
}
References v8::internal::Isolate::Current(), v8::internal::Isolate::factory(), GetScript(), v8::internal::Script::GetScriptHash(), v8::internal::script, and v8::anonymous_namespace{api.cc}::ToHandle().
Referenced by v8::internal::BUILTIN().
GetScriptId()
int v8::internal::CallSiteInfo::GetScriptId () const
Definition at line 171 of file call-site-info.cc.
                                    {
  if (auto script = GetScript()) {
    return script.value()->id();
  }
  return Message::kNoScriptIdInfo;
}
References GetScript(), v8::Message::kNoScriptIdInfo, and v8::internal::script.
GetScriptName()
Tagged< Object > v8::internal::CallSiteInfo::GetScriptName () const
Definition at line 178 of file call-site-info.cc.
                                                 {
  if (auto script = GetScript()) {
    return script.value()->name();
  }
  return ReadOnlyRoots(Isolate::Current()).null_value();
}
References v8::internal::Isolate::Current(), GetScript(), and v8::internal::script.
GetScriptNameOrSourceURL()
Tagged< Object > v8::internal::CallSiteInfo::GetScriptNameOrSourceURL () const
Definition at line 185 of file call-site-info.cc.
                                                            {
  if (auto script = GetScript()) {
    return script.value()->GetNameOrSourceURL();
  }
  return ReadOnlyRoots(Isolate::Current()).null_value();
}
References v8::internal::Isolate::Current(), GetScript(), and v8::internal::script.
GetScriptSource()
Tagged< Object > v8::internal::CallSiteInfo::GetScriptSource () const
Definition at line 192 of file call-site-info.cc.
                                                   {
  if (auto script = GetScript()) {
    if (script.value()->HasValidSource()) {
      return script.value()->source();
    }
  }
  return ReadOnlyRoots(Isolate::Current()).null_value();
}
References v8::internal::Isolate::Current(), GetScript(), and v8::internal::script.
GetScriptSourceMappingURL()
Tagged< Object > v8::internal::CallSiteInfo::GetScriptSourceMappingURL () const
Definition at line 201 of file call-site-info.cc.
                                                             {
  if (auto script = GetScript()) {
    return script.value()->source_mapping_url();
  }
  return ReadOnlyRoots(Isolate::Current()).null_value();
}
References v8::internal::Isolate::Current(), GetScript(), and v8::internal::script.
GetSharedFunctionInfo()
Tagged< SharedFunctionInfo > v8::internal::CallSiteInfo::GetSharedFunctionInfo () const [private]
Definition at line 670 of file call-site-info.cc.
                                                                     {
#if V8_ENABLE_WEBASSEMBLY
  DCHECK(!IsWasm());
  DCHECK(!IsBuiltin());
#endif // V8_ENABLE_WEBASSEMBLY
  return Cast<JSFunction>(function())->shared();
}
References v8::internal::DCHECK().
Referenced by GetScript(), and IsUserJavaScript().
GetSourcePosition()
int v8::internal::CallSiteInfo::GetSourcePosition (DirectHandle< CallSiteInfo > info) [static]
Definition at line 572 of file call-site-info.cc.
                                                                   {
  if (info->flags() & kIsSourcePositionComputed) {
    return info->code_offset_or_source_position();
  }
  DCHECK(!info->IsPromiseAll());
  DCHECK(!info->IsPromiseAllSettled());
  DCHECK(!info->IsPromiseAny());
  int source_position =
      ComputeSourcePosition(info, info->code_offset_or_source_position());
  info->set_code_offset_or_source_position(source_position);
  info->set_flags(info->flags() | kIsSourcePositionComputed);
  return source_position;
}
References ComputeSourcePosition(), and v8::internal::DCHECK().
Referenced by v8::internal::BUILTIN(), ComputeLocation(), wasm::anonymous_namespace{c-api.cc}::CreateFrameFromInternal(), GetColumnNumber(), v8::internal::anonymous_namespace{isolate.cc}::GetDetailedStackTraceFromCallSiteInfos(), GetLineNumber(), and v8::internal::anonymous_namespace{call-site-info.cc}::SerializeJSStackFrame().
GetTypeName()
DirectHandle< Object > v8::internal::CallSiteInfo::GetTypeName (DirectHandle< CallSiteInfo > info) [static]
Definition at line 519 of file call-site-info.cc.
                                     {
  Isolate* isolate = Isolate::Current();
  if (!info->IsMethodCall()) {
    return isolate->factory()->null_value();
  }
  DirectHandle<JSReceiver> receiver =
      Object::ToObject(isolate,
                       direct_handle(info->receiver_or_instance(), isolate))
          .ToHandleChecked();
  if (IsJSProxy(*receiver)) {
    return isolate->factory()->Proxy_string();
  }
  if (IsJSFunction(*receiver)) {
    DirectHandle<JSFunction> function = Cast<JSFunction>(receiver);
    DirectHandle<String> class_name =
        JSFunction::GetDebugName(isolate, function);
    if (class_name->length() != 0) {
      return class_name;
    }
  }
  return JSReceiver::GetConstructorName(isolate, receiver);
}
References v8::internal::Isolate::Current(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetConstructorName(), v8::internal::JSFunction::GetDebugName(), and v8::Value::ToObject().
Referenced by v8::internal::anonymous_namespace{call-site-info.cc}::AppendMethodCall(), and v8::internal::BUILTIN().
IsAsync()
bool v8::internal::CallSiteInfo::IsAsync () const [inline]
Referenced by IsPromiseAll(), IsPromiseAllSettled(), and IsPromiseAny().
IsConstructor()
bool v8::internal::CallSiteInfo::IsConstructor () const [inline]
Referenced by IsMethodCall().
IsEval()
bool v8::internal::CallSiteInfo::IsEval () const
Definition at line 48 of file call-site-info.cc.
                                {
  if (auto script = GetScript()) {
    return script.value()->compilation_type() == Script::CompilationType::kEval;
  }
  return false;
}
References GetScript(), v8::internal::Script::kEval, and v8::internal::script.
IsMethodCall()
bool v8::internal::CallSiteInfo::IsMethodCall () const
Definition at line 63 of file call-site-info.cc.
                                      {
#if V8_ENABLE_WEBASSEMBLY
  if (IsWasm()) return false;
  if (IsBuiltin()) return false;
#endif // V8_ENABLE_WEBASSEMBLY
  return !IsToplevel() && !IsConstructor();
}
References IsConstructor(), and IsToplevel().
IsNative()
bool v8::internal::CallSiteInfo::IsNative () const
Definition at line 38 of file call-site-info.cc.
                                  {
#if V8_ENABLE_WEBASSEMBLY
  if (IsBuiltin()) return true;
#endif
  if (auto script = GetScript()) {
    return script.value()->type() == Script::Type::kNative;
  }
  return false;
}
References GetScript(), v8::internal::Script::kNative, and v8::internal::script.
IsPromiseAll()
bool v8::internal::CallSiteInfo::IsPromiseAll () const
Definition at line 20 of file call-site-info.cc.
                                      {
  if (!IsAsync()) return false;
  Tagged<JSFunction> fun = Cast<JSFunction>(function());
  return fun == fun->native_context()->promise_all();
}
References IsAsync().
IsPromiseAllSettled()
bool v8::internal::CallSiteInfo::IsPromiseAllSettled () const
Definition at line 26 of file call-site-info.cc.
                                             {
  if (!IsAsync()) return false;
  Tagged<JSFunction> fun = Cast<JSFunction>(function());
  return fun == fun->native_context()->promise_all_settled();
}
References IsAsync().
IsPromiseAny()
bool v8::internal::CallSiteInfo::IsPromiseAny () const
Definition at line 32 of file call-site-info.cc.
                                      {
  if (!IsAsync()) return false;
  Tagged<JSFunction> fun = Cast<JSFunction>(function());
  return fun == fun->native_context()->promise_any();
}
References IsAsync().
IsStrict()
bool v8::internal::CallSiteInfo::IsStrict () const [inline]
IsSubjectToDebugging()
bool v8::internal::CallSiteInfo::IsSubjectToDebugging () const
IsToplevel()
bool v8::internal::CallSiteInfo::IsToplevel () const
Definition at line 71 of file call-site-info.cc.
                                    {
  return IsJSGlobalProxy(receiver_or_instance()) ||
         IsNullOrUndefined(receiver_or_instance());
}
References v8::internal::IsNullOrUndefined().
Referenced by IsMethodCall().
IsUserJavaScript()
bool v8::internal::CallSiteInfo::IsUserJavaScript () const
Definition at line 55 of file call-site-info.cc.
                                          {
#if V8_ENABLE_WEBASSEMBLY
  if (IsWasm()) return false;
  if (IsBuiltin()) return false;
#endif // V8_ENABLE_WEBASSEMBLY
  return GetSharedFunctionInfo()->IsUserJavaScript();
}
References GetSharedFunctionInfo().
set_code_object()
void v8::internal::CallSiteInfo::set_code_object (Tagged< HeapObject > code, WriteBarrierMode mode) [inline]
Definition at line 53 of file call-site-info-inl.h.
                                                          {
  DCHECK(IsCode(code) || IsBytecodeArray(code) || IsUndefined(code));
  if (IsCode(code) || IsBytecodeArray(code)) {
    WriteTrustedPointerField<kUnknownIndirectPointerTag>(
        kCodeObjectOffset, Cast<ExposedTrustedObject>(code));
    CONDITIONAL_TRUSTED_POINTER_WRITE_BARRIER(
        *this, kCodeObjectOffset, kUnknownIndirectPointerTag, code, mode);
  } else {
    DCHECK(IsUndefined(code));
    ClearTrustedPointerField(kCodeObjectOffset);
  }
}
References code, CONDITIONAL_TRUSTED_POINTER_WRITE_BARRIER, v8::internal::DCHECK(), v8::internal::kUnknownIndirectPointerTag, and mode().
Member Data Documentation
kUnknown
constexpr int v8::internal::CallSiteInfo::kUnknown = kNoSourcePosition [static], [constexpr]
Definition at line 58 of file call-site-info.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/call-site-info.h
/mnt/V8SourceCode/src/objects/call-site-info-inl.h
/mnt/V8SourceCode/src/objects/call-site-info.cc