v8::internal::DeoptimizationLiteralProvider Class Reference
#include <translated-state.h>
Public Member Functions
DeoptimizationLiteralProvider (Tagged< DeoptimizationLiteralArray > literal_array)
DeoptimizationLiteralProvider (std::vector< DeoptimizationLiteral > literals)
~DeoptimizationLiteralProvider ()
DeoptimizationLiteralProvider (const DeoptimizationLiteralProvider &)=delete
void operator= (const DeoptimizationLiteralProvider &)=delete
TranslatedValue Get (TranslatedState *container, int literal_index) const
Tagged< DeoptimizationLiteralArray > get_on_heap_literals () const
Private Attributes
Tagged< DeoptimizationLiteralArray > literals_on_heap_
std::vector< DeoptimizationLiteral > literals_off_heap_
Detailed Description
Definition at line 415 of file translated-state.h.
Constructor & Destructor Documentation
DeoptimizationLiteralProvider() [1/3]
v8::internal::DeoptimizationLiteralProvider::DeoptimizationLiteralProvider (Tagged< DeoptimizationLiteralArray > literal_array) [explicit]
Definition at line 1000 of file translated-state.cc.
    : literals_on_heap_(literal_array) {}
DeoptimizationLiteralProvider() [2/3]
v8::internal::DeoptimizationLiteralProvider::DeoptimizationLiteralProvider (std::vector< DeoptimizationLiteral > literals) [explicit]
Definition at line 1004 of file translated-state.cc.
    : literals_off_heap_(std::move(literals)) {}
 DeoptimizationLiteralProvider()
v8::internal::DeoptimizationLiteralProvider::~DeoptimizationLiteralProvider () [default]
DeoptimizationLiteralProvider() [3/3]
v8::internal::DeoptimizationLiteralProvider::DeoptimizationLiteralProvider (const DeoptimizationLiteralProvider &) [delete]
Member Function Documentation
Get()
TranslatedValue v8::internal::DeoptimizationLiteralProvider::Get (TranslatedState * container, int literal_index) const
Definition at line 1010 of file translated-state.cc.
                                                                            {
  if (V8_LIKELY(!literals_on_heap_.is_null())) {
    return TranslatedValue::NewTagged(container,
                                      literals_on_heap_->get(literal_index));
  }
#if !V8_ENABLE_WEBASSEMBLY
  UNREACHABLE();
#else
  CHECK(v8_flags.wasm_deopt);
  CHECK_LT(literal_index, literals_off_heap_.size());
  const DeoptimizationLiteral& literal = literals_off_heap_[literal_index];
  switch (literal.kind()) {
    case DeoptimizationLiteralKind::kWasmInt32:
      return TranslatedValue::NewInt32(container, literal.GetInt32());
    case DeoptimizationLiteralKind::kWasmInt64:
      return TranslatedValue::NewInt64(container, literal.GetInt64());
    case DeoptimizationLiteralKind::kWasmFloat32:
      return TranslatedValue::NewFloat(container, literal.GetFloat32());
    case DeoptimizationLiteralKind::kWasmFloat64:
      return TranslatedValue::NewDouble(container, literal.GetFloat64());
    case DeoptimizationLiteralKind::kWasmI31Ref:
      return TranslatedValue::NewTagged(container, literal.GetSmi());
    default:
      UNIMPLEMENTED();
  }
#endif
}
References CHECK, CHECK_LT, v8::internal::DeoptimizationLiteral::kind(), v8::internal::kWasmFloat32, v8::internal::kWasmFloat64, v8::internal::kWasmI31Ref, v8::internal::kWasmInt32, v8::internal::kWasmInt64, literals_off_heap_, literals_on_heap_, v8::internal::TranslatedValue::NewDouble(), v8::internal::TranslatedValue::NewFloat(), v8::internal::TranslatedValue::NewInt32(), v8::internal::TranslatedValue::NewInt64(), v8::internal::TranslatedValue::NewTagged(), v8::internal::UNIMPLEMENTED(), v8::internal::UNREACHABLE(), v8::internal::v8_flags, and V8_LIKELY.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedValue().
get_on_heap_literals()
Tagged<DeoptimizationLiteralArray> v8::internal::DeoptimizationLiteralProvider::get_on_heap_literals () const [inline]
Definition at line 430 of file translated-state.h.
                                                                  {
    DCHECK(!literals_on_heap_.is_null());
    return literals_on_heap_;
  }
References v8::internal::DCHECK(), and literals_on_heap_.
Referenced by v8::internal::TranslatedState::CreateNextTranslatedFrame(), and v8::internal::TranslatedState::Init().
operator=()
void v8::internal::DeoptimizationLiteralProvider::operator= (const DeoptimizationLiteralProvider &) [delete]
Member Data Documentation
literals_off_heap_
std::vector<DeoptimizationLiteral> v8::internal::DeoptimizationLiteralProvider::literals_off_heap_ [private]
Definition at line 437 of file translated-state.h.
Referenced by Get().
literals_on_heap_
Tagged<DeoptimizationLiteralArray> v8::internal::DeoptimizationLiteralProvider::literals_on_heap_ [private]
Definition at line 436 of file translated-state.h.
Referenced by Get(), and get_on_heap_literals().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/deoptimizer/translated-state.h
/mnt/V8SourceCode/src/deoptimizer/translated-state.cc