v8::internal::compiler::JSBinaryOpNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSBinaryOpNode (Node *node)
const FeedbackParameter & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1181 of file js-operator.h.
Constructor & Destructor Documentation
JSBinaryOpNode()
constexpr v8::internal::compiler::JSBinaryOpNode::JSBinaryOpNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1183 of file js-operator.h.
                                                : JSNodeWrapperBase(node) {
    DCHECK(JSOperator::IsBinaryWithFeedback(node->opcode()));
  }
References v8::internal::DCHECK(), v8::internal::compiler::JSOperator::IsBinaryWithFeedback(), v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const FeedbackParameter& v8::internal::compiler::JSBinaryOpNode::Parameters () const [inline]
Definition at line 1187 of file js-operator.h.
                                              {
    return FeedbackParameterOf(node()->op());
  }
References v8::internal::compiler::FeedbackParameterOf(), and v8::internal::compiler::NodeWrapper::node().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h