cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask Class Reference
Public Member Functions
ConcurrentMarkingTask (ConcurrentMarkerBase &)
void Run (JobDelegate *delegate) final
size_t GetMaxConcurrency (size_t) const final
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Private Member Functions
void ProcessWorklists (JobDelegate *, ConcurrentMarkingState &, Visitor &)
Private Attributes
ConcurrentMarkerBase & concurrent_marker_
Detailed Description
Definition at line 62 of file concurrent-marker.cc.
Constructor & Destructor Documentation
ConcurrentMarkingTask()
cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ConcurrentMarkingTask (ConcurrentMarkerBase & concurrent_marker) [explicit]
Definition at line 76 of file concurrent-marker.cc.
    : concurrent_marker_(concurrent_marker) {}
Member Function Documentation
GetMaxConcurrency()
size_t cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::GetMaxConcurrency (size_t worker_count) const [final], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 99 of file concurrent-marker.cc.
                                       {
  return WorkSizeForConcurrentMarking(concurrent_marker_.marking_worklists()) +
         current_worker_count;
}
References concurrent_marker_, cppgc::internal::ConcurrentMarkerBase::marking_worklists(), and cppgc::internal::anonymous_namespace{concurrent-marker.cc}::WorkSizeForConcurrentMarking().
ProcessWorklists()
void cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::ProcessWorklists (JobDelegate * job_delegate, ConcurrentMarkingState & concurrent_marking_state, Visitor & concurrent_marking_visitor) [private]
Definition at line 105 of file concurrent-marker.cc.
                                         {
  StatsCollector* stats_collector = concurrent_marker_.heap().stats_collector();
  do {
    if (!DrainWorklistWithYielding<
            StatsCollector::kConcurrentMarkProcessNotFullyconstructedWorklist>(
            job_delegate, stats_collector, concurrent_marking_state,
            concurrent_marker_,
            concurrent_marking_state
                .previously_not_fully_constructed_worklist(),
            [&concurrent_marking_state,
             &concurrent_marking_visitor](HeapObjectHeader* header) {
              BasePage::FromPayload(header)->SynchronizedLoad();
              concurrent_marking_state.AccountMarkedBytes(*header);
              DynamicallyTraceMarkedObject<AccessMode::kAtomic>(
                  concurrent_marking_visitor, *header);
            })) {
      return;
    }
    if (!DrainWorklistWithYielding<
            StatsCollector::kConcurrentMarkProcessMarkingWorklist>(
            job_delegate, stats_collector, concurrent_marking_state,
            concurrent_marker_, concurrent_marking_state.marking_worklist(),
            [&concurrent_marking_state, &concurrent_marking_visitor](
                const MarkingWorklists::MarkingItem& item) {
              BasePage::FromPayload(item.base_object_payload)
                  ->SynchronizedLoad();
              const HeapObjectHeader& header =
                  HeapObjectHeader::FromObject(item.base_object_payload);
              DCHECK(!header.IsInConstruction<AccessMode::kAtomic>());
              DCHECK(header.IsMarked<AccessMode::kAtomic>());
              concurrent_marking_state.AccountMarkedBytes(header);
              item.callback(&concurrent_marking_visitor,
                            item.base_object_payload);
            })) {
      return;
    }
    if (!DrainWorklistWithYielding<
            StatsCollector::kConcurrentMarkProcessWriteBarrierWorklist>(
            job_delegate, stats_collector, concurrent_marking_state,
            concurrent_marker_,
            concurrent_marking_state.write_barrier_worklist(),
            [&concurrent_marking_state,
             &concurrent_marking_visitor](HeapObjectHeader* header) {
              BasePage::FromPayload(header)->SynchronizedLoad();
              concurrent_marking_state.AccountMarkedBytes(*header);
              DynamicallyTraceMarkedObject<AccessMode::kAtomic>(
                  concurrent_marking_visitor, *header);
            })) {
      return;
    }
    if (!DrainWorklistWithYielding<
            StatsCollector::kConcurrentMarkProcessEphemeronWorklist>(
            job_delegate, stats_collector, concurrent_marking_state,
            concurrent_marker_,
            concurrent_marking_state.ephemeron_pairs_for_processing_worklist(),
            [&concurrent_marking_state, &concurrent_marking_visitor](
                const MarkingWorklists::EphemeronPairItem& item) {
              concurrent_marking_state.ProcessEphemeron(
                  item.key, item.value, item.value_desc,
                  concurrent_marking_visitor);
            })) {
      return;
    }
  } while (
      !concurrent_marking_state.marking_worklist().IsLocalAndGlobalEmpty());
}
References cppgc::internal::BasicMarkingState::AccountMarkedBytes(), concurrent_marker_, DCHECK, cppgc::internal::anonymous_namespace{concurrent-marker.cc}::DrainWorklistWithYielding(), cppgc::internal::BasicMarkingState::ephemeron_pairs_for_processing_worklist(), cppgc::internal::HeapObjectHeader::FromObject(), cppgc::internal::BasePage::FromPayload(), cppgc::internal::ConcurrentMarkerBase::heap(), cppgc::internal::HeapObjectHeader::IsInConstruction(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kAtomic, cppgc::internal::MarkingStateBase::marking_worklist(), cppgc::internal::BasicMarkingState::ProcessEphemeron(), cppgc::internal::HeapBase::stats_collector(), cppgc::internal::BasePage::SynchronizedLoad(), and cppgc::internal::BasicMarkingState::write_barrier_worklist().
Referenced by Run().
Run()
void cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::Run (JobDelegate * delegate) [final], [virtual]
Implements v8::JobTask.
Definition at line 80 of file concurrent-marker.cc.
                                                         {
  StatsCollector::EnabledConcurrentScope stats_scope(
      concurrent_marker_.heap().stats_collector(),
      StatsCollector::kConcurrentMark);
  if (!HasWorkForConcurrentMarking(concurrent_marker_.marking_worklists()))
    return;
  ConcurrentMarkingState concurrent_marking_state(
      concurrent_marker_.heap(), concurrent_marker_.marking_worklists(),
      concurrent_marker_.heap().compactor().compaction_worklists());
  std::unique_ptr<Visitor> concurrent_marking_visitor =
      concurrent_marker_.CreateConcurrentMarkingVisitor(
          concurrent_marking_state);
  ProcessWorklists(job_delegate, concurrent_marking_state,
                   *concurrent_marking_visitor);
  concurrent_marker_.AddConcurrentlyMarkedBytes(
      concurrent_marking_state.RecentlyMarkedBytes());
  concurrent_marking_state.Publish();
}
References cppgc::internal::ConcurrentMarkerBase::AddConcurrentlyMarkedBytes(), cppgc::internal::Compactor::compaction_worklists(), cppgc::internal::HeapBase::compactor(), concurrent_marker_, cppgc::internal::ConcurrentMarkerBase::CreateConcurrentMarkingVisitor(), cppgc::internal::anonymous_namespace{concurrent-marker.cc}::HasWorkForConcurrentMarking(), cppgc::internal::ConcurrentMarkerBase::heap(), cppgc::internal::ConcurrentMarkerBase::marking_worklists(), ProcessWorklists(), cppgc::internal::BasicMarkingState::Publish(), cppgc::internal::BasicMarkingState::RecentlyMarkedBytes(), and cppgc::internal::HeapBase::stats_collector().
Member Data Documentation
concurrent_marker_
ConcurrentMarkerBase& cppgc::internal::anonymous_namespace{concurrent-marker.cc}::ConcurrentMarkingTask::concurrent_marker_ [private]
Definition at line 73 of file concurrent-marker.cc.
Referenced by GetMaxConcurrency(), ProcessWorklists(), and Run().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/concurrent-marker.cc