v8::internal::Builtins Class Reference
#include <builtins.h>
Public Types
enum Kind {
CPP
, TSJ
, TFJ
, TSC
,
TFC
, TFS
, TFH
, BCH
,
ASM
 }
enum class ForwardWhichFrame { kCurrentFrame
, kParentFrame
 }
Public Member Functions
Builtins (Isolate *isolate)
Builtins (const Builtins &)=delete
Builtins & operator= (const Builtins &)=delete
void TearDown ()
const char * Lookup (Address pc)
void set_code (Builtin builtin, Tagged< Code > code)
V8_EXPORT_PRIVATE Tagged< Code > code (Builtin builtin)
V8_EXPORT_PRIVATE Handle< Code > code_handle (Builtin builtin)
void PrintBuiltinCode ()
void PrintBuiltinSize ()
bool IsBuiltinHandle (IndirectHandle< HeapObject > maybe_code, Builtin *index) const
bool is_initialized () const
void MarkInitialized ()
int js_entry_handler_offset () const
int jspi_prompt_handler_offset () const
void SetJSEntryHandlerOffset (int offset)
void SetJSPIPromptHandlerOffset (int offset)
FullObjectSlot builtin_slot (Builtin builtin)
FullObjectSlot builtin_tier0_slot (Builtin builtin)
Static Public Member Functions
static constexpr bool IsBuiltinId (Builtin builtin)
static constexpr bool IsBuiltinId (int maybe_id)
static constexpr bool IsTier0 (Builtin builtin)
static constexpr Builtin FromInt (int id)
static constexpr int ToInt (Builtin id)
static BytecodeOffset GetContinuationBytecodeOffset (Builtin builtin)
static Builtin GetBuiltinFromBytecodeOffset (BytecodeOffset)
static constexpr Builtin RecordWrite (SaveFPRegsMode fp_mode)
static constexpr Builtin IndirectPointerBarrier (SaveFPRegsMode fp_mode)
static constexpr Builtin EphemeronKeyBarrier (SaveFPRegsMode fp_mode)
static constexpr Builtin AdaptorWithBuiltinExitFrame (int formal_parameter_count)
static constexpr Builtin CallFunction (ConvertReceiverMode=ConvertReceiverMode::kAny)
static constexpr Builtin Call (ConvertReceiverMode=ConvertReceiverMode::kAny)
static constexpr bool IsAnyCall (Builtin builtin)
static constexpr Builtin NonPrimitiveToPrimitive (ToPrimitiveHint hint=ToPrimitiveHint::kDefault)
static constexpr Builtin OrdinaryToPrimitive (OrdinaryToPrimitiveHint hint)
static constexpr Builtin StringAdd (StringAddFlags flags=STRING_ADD_CHECK_NONE)
static constexpr Builtin LoadGlobalIC (TypeofMode typeof_mode)
static constexpr Builtin LoadGlobalICInOptimizedCode (TypeofMode typeof_mode)
static constexpr Builtin CEntry (int result_size, ArgvMode argv_mode, bool builtin_exit_frame=false, bool switch_to_central_stack=false)
static constexpr Builtin RuntimeCEntry (int result_size, bool switch_to_central_stack=false)
static constexpr Builtin InterpreterCEntry (int result_size)
static constexpr Builtin InterpreterPushArgsThenCall (ConvertReceiverMode receiver_mode, InterpreterPushArgsMode mode)
static constexpr Builtin InterpreterPushArgsThenConstruct (InterpreterPushArgsMode mode)
static CallInterfaceDescriptor CallInterfaceDescriptorFor (Builtin builtin)
static V8_EXPORT_PRIVATE Callable CallableFor (Isolate *isolate, Builtin builtin)
static V8_EXPORT_PRIVATE bool HasJSLinkage (Builtin builtin)
static V8_EXPORT_PRIVATE int GetStackParameterCount (Builtin builtin)
static int GetFormalParameterCount (Builtin builtin)
static bool CheckFormalParameterCount (Builtin builtin, int function_length, int formal_parameter_count_with_receiver)
static V8_EXPORT_PRIVATE const char * name (Builtin builtin)
static V8_EXPORT_PRIVATE const char * NameForStackTrace (Isolate *isolate, Builtin builtin)
static Address CppEntryOf (Builtin builtin)
static Address EntryOf (Builtin builtin, Isolate *isolate)
static V8_EXPORT_PRIVATE Address EmbeddedEntryOf (Builtin builtin)
static V8_EXPORT_PRIVATE Kind KindOf (Builtin builtin)
static const char * KindNameOf (Builtin builtin)
static V8_EXPORT_PRIVATE CodeEntrypointTag EntrypointTagFor (Builtin builtin)
static CodeSandboxingMode SandboxingModeOf (Builtin builtin)
static V8_EXPORT_PRIVATE bool IsCpp (Builtin builtin)
static bool IsBuiltin (const Tagged< Code > code)
static constexpr bool AllBuiltinsAreIsolateIndependent ()
static constexpr bool IsIsolateIndependent (Builtin builtin)
static bool IsIsolateIndependentBuiltin (Tagged< Code > code)
static void InitializeIsolateDataTables (Isolate *isolate)
static void EmitCodeCreateEvents (Isolate *isolate)
static V8_WARN_UNUSED_RESULT MaybeHandle< Object > InvokeApiFunction (Isolate *isolate, bool is_construct, DirectHandle< FunctionTemplateInfo > function, DirectHandle< Object > receiver, base::Vector< const DirectHandle< Object >> args, DirectHandle< HeapObject > new_target)
static void Generate_Adaptor (MacroAssembler *masm, int formal_parameter_count, Address builtin_address)
static void Generate_CEntry (MacroAssembler *masm, int result_size, ArgvMode argv_mode, bool builtin_exit_frame, bool switch_to_central_stack)
static bool AllowDynamicFunction (Isolate *isolate, DirectHandle< JSFunction > target, DirectHandle< JSObject > target_global_proxy)
static DirectHandle< Code > CreateInterpreterEntryTrampolineForProfiling (Isolate *isolate)
static constexpr bool IsJSEntryVariant (Builtin builtin)
Static Public Attributes
static constexpr bool kCodeObjectsAreInROSpace = true
static constexpr int kBuiltinCount
static constexpr int kBuiltinTier0Count
static constexpr Builtin kFirst = static_cast<Builtin>(0)
static constexpr Builtin kLast = static_cast<Builtin>(kBuiltinCount - 1)
static constexpr Builtin kLastTier0
static constexpr int kFirstWideBytecodeHandler
static constexpr int kFirstExtraWideBytecodeHandler
static constexpr int kLastBytecodeHandlerPlusOne
static constexpr bool kBytecodeHandlersAreSortedLast
static constexpr bool kAllBuiltinsAreIsolateIndependent = true
Private Types
enum class CallOrConstructMode { kCall
, kConstruct
 }
enum class InterpreterEntryTrampolineMode { kDefault
, kForProfiling
 }
Private Member Functions
BUILTIN_LIST (IGNORE_BUILTIN, DECLARE_TS, DECLARE_TF, DECLARE_TS, DECLARE_TF, DECLARE_TF, DECLARE_TF, IGNORE_BUILTIN, DECLARE_ASM) Isolate *isolate_
Static Private Member Functions
static void Generate_CallFunction (MacroAssembler *masm, ConvertReceiverMode mode)
static void Generate_CallBoundFunctionImpl (MacroAssembler *masm)
static void Generate_Call (MacroAssembler *masm, ConvertReceiverMode mode)
static void Generate_CallOrConstructVarargs (MacroAssembler *masm, Builtin target_builtin)
static void Generate_CallOrConstructForwardVarargs (MacroAssembler *masm, CallOrConstructMode mode, Builtin target_builtin)
static void Generate_MaglevFunctionEntryStackCheck (MacroAssembler *masm, bool save_new_target)
static void Generate_InterpreterEntryTrampoline (MacroAssembler *masm, InterpreterEntryTrampolineMode mode)
static void Generate_InterpreterPushArgsThenCallImpl (MacroAssembler *masm, ConvertReceiverMode receiver_mode, InterpreterPushArgsMode mode)
static void Generate_InterpreterPushArgsThenConstructImpl (MacroAssembler *masm, InterpreterPushArgsMode mode)
static void Generate_ConstructForwardAllArgsImpl (MacroAssembler *masm, ForwardWhichFrame which_frame)
static void Generate_CallApiCallbackImpl (MacroAssembler *masm, CallApiCallbackMode mode)
Private Attributes
bool initialized_ = false
int js_entry_handler_offset_ = 0
int jspi_prompt_handler_offset_ = 0
Friends
class SetupIsolateDelegate
Detailed Description
Definition at line 92 of file builtins.h.
Member Enumeration Documentation
CallOrConstructMode
enum v8::internal::Builtins::CallOrConstructMode [strong], [private]
Enumerator
kCall
kConstruct
Definition at line 451 of file builtins.h.
{ kCall, kConstruct };
ForwardWhichFrame
enum v8::internal::Builtins::ForwardWhichFrame [strong]
Enumerator
kCurrentFrame
kParentFrame
Definition at line 439 of file builtins.h.
{ kCurrentFrame, kParentFrame };
InterpreterEntryTrampolineMode
enum v8::internal::Builtins::InterpreterEntryTrampolineMode [strong], [private]
Enumerator
kDefault
kForProfiling
Definition at line 459 of file builtins.h.
                                            {
    // The version of InterpreterEntryTrampoline used by default.
    kDefault,
    // The position independent version of InterpreterEntryTrampoline used as
    // a template to create copies of the builtin at runtime. The copies are
    // used to create better profiling information for ticks in bytecode
    // execution. See v8_flags.interpreted_frames_native_stack for details.
    kForProfiling
  };
Kind
enum v8::internal::Builtins::Kind
Enumerator
CPP
TSJ
TFJ
TSC
TFC
TFS
TFH
BCH
ASM
Definition at line 220 of file builtins.h.
{ CPP, TSJ, TFJ, TSC, TFC, TFS, TFH, BCH, ASM };
Constructor & Destructor Documentation
Builtins() [1/2]
v8::internal::Builtins::Builtins (Isolate * isolate) [inline], [explicit]
Definition at line 94 of file builtins.h.
: isolate_(isolate) {}
Builtins() [2/2]
v8::internal::Builtins::Builtins (const Builtins &) [delete]
Member Function Documentation
AdaptorWithBuiltinExitFrame()
constexpr Builtin v8::internal::Builtins::AdaptorWithBuiltinExitFrame (int formal_parameter_count) [inline], [static], [constexpr]
Definition at line 47 of file builtins-inl.h.
                                {
  switch (formal_parameter_count) {
    case kDontAdaptArgumentsSentinel:
    case JSParameterCount(0):
      return Builtin::kAdaptorWithBuiltinExitFrame0;
    case JSParameterCount(1):
      return Builtin::kAdaptorWithBuiltinExitFrame1;
    case JSParameterCount(2):
      return Builtin::kAdaptorWithBuiltinExitFrame2;
    case JSParameterCount(3):
      return Builtin::kAdaptorWithBuiltinExitFrame3;
    case JSParameterCount(4):
      return Builtin::kAdaptorWithBuiltinExitFrame4;
    case JSParameterCount(5):
      return Builtin::kAdaptorWithBuiltinExitFrame5;
  }
  UNREACHABLE();
}
References v8::internal::JSParameterCount(), v8::internal::kDontAdaptArgumentsSentinel, and v8::internal::UNREACHABLE().
Referenced by Generate_Adaptor().
AllBuiltinsAreIsolateIndependent()
static constexpr bool v8::internal::Builtins::AllBuiltinsAreIsolateIndependent () [inline], [static], [constexpr]
Definition at line 346 of file builtins.h.
                                                           {
    return kAllBuiltinsAreIsolateIndependent;
  }
References kAllBuiltinsAreIsolateIndependent.
Referenced by v8::internal::Isolate::HashIsolateForEmbeddedBlob(), and v8::internal::Heap::IterateBuiltins().
AllowDynamicFunction()
bool v8::internal::Builtins::AllowDynamicFunction (Isolate * isolate, DirectHandle< JSFunction > target, DirectHandle< JSObject > target_global_proxy) [static]
Definition at line 569 of file builtins.cc.
                                                {
  if (v8_flags.allow_unsafe_function_constructor) return true;
  HandleScopeImplementer* impl = isolate->handle_scope_implementer();
  DirectHandle<NativeContext> responsible_context = impl->LastEnteredContext();
  // TODO(verwaest): Remove this.
  if (responsible_context.is_null()) {
    return true;
  }
  if (*responsible_context == target->context()) return true;
  return isolate->MayAccess(responsible_context, target_global_proxy);
}
References v8::internal::Isolate::handle_scope_implementer(), wasm::impl(), v8::internal::DirectHandle< T >::is_null(), v8::internal::Isolate::MayAccess(), and v8::internal::v8_flags.
Referenced by v8::internal::BUILTIN(), v8::internal::anonymous_namespace{builtins-function.cc}::CreateDynamicFunction(), and v8::internal::RUNTIME_FUNCTION().
BUILTIN_LIST()
v8::internal::Builtins::BUILTIN_LIST (IGNORE_BUILTIN , DECLARE_TS , DECLARE_TF , DECLARE_TS , DECLARE_TF , DECLARE_TF , DECLARE_TF , IGNORE_BUILTIN , DECLARE_ASM) [private]
Referenced by CallInterfaceDescriptorFor().
builtin_slot()
FullObjectSlot v8::internal::Builtins::builtin_slot (Builtin builtin)
Definition at line 130 of file builtins.cc.
                                                     {
  Address* location = &isolate_->builtin_table()[Builtins::ToInt(builtin)];
  return FullObjectSlot(location);
}
References ToInt().
Referenced by v8::internal::Heap::IterateBuiltins().
builtin_tier0_slot()
FullObjectSlot v8::internal::Builtins::builtin_tier0_slot (Builtin builtin)
Definition at line 135 of file builtins.cc.
                                                           {
  DCHECK(IsTier0(builtin));
  Address* location =
      &isolate_->builtin_tier0_table()[Builtins::ToInt(builtin)];
  return FullObjectSlot(location);
}
References v8::internal::DCHECK(), IsTier0(), and ToInt().
Referenced by v8::internal::Heap::IterateBuiltins().
Call()
constexpr Builtin v8::internal::Builtins::Call (ConvertReceiverMode mode = ConvertReceiverMode::kAny) [inline], [static], [constexpr]
Definition at line 81 of file builtins-inl.h.
                                                         {
  switch (mode) {
    case ConvertReceiverMode::kNullOrUndefined:
      return Builtin::kCall_ReceiverIsNullOrUndefined;
    case ConvertReceiverMode::kNotNullOrUndefined:
      return Builtin::kCall_ReceiverIsNotNullOrUndefined;
    case ConvertReceiverMode::kAny:
      return Builtin::kCall_ReceiverIsAny;
  }
  UNREACHABLE();
}
References v8::internal::kAny, v8::internal::kNotNullOrUndefined, v8::internal::kNullOrUndefined, mode(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::CodeFactory::Call(), v8::internal::CodeStubAssembler::Call(), v8::internal::interpreter::InterpreterAssembler::CallJSAndDispatch(), Generate_CallBoundFunctionImpl(), Generate_InterpreterPushArgsThenCallImpl(), v8::internal::Generate_JSEntryTrampolineHelper(), and v8::internal::TF_BUILTIN().
CallableFor()
Callable v8::internal::Builtins::CallableFor (Isolate * isolate, Builtin builtin) [static]
Definition at line 214 of file builtins.cc.
                                                                {
  Handle<Code> code = isolate->builtins()->code_handle(builtin);
  return Callable{code, CallInterfaceDescriptorFor(builtin)};
}
References v8::internal::Isolate::builtins(), CallInterfaceDescriptorFor(), code(), and code_handle().
Referenced by v8::internal::CodeFactory::Call(), v8::internal::CodeFactory::Call_WithFeedback(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin(), v8::internal::compiler::CodeAssembler::CallBuiltin(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CallBuiltinForBigIntOp(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltinImpl(), v8::internal::compiler::CodeAssembler::CallBuiltinVoid(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltinWithVarStackArgs(), v8::internal::CodeFactory::CallForwardVarargs(), v8::internal::CodeFactory::CallFunction(), v8::internal::CodeFactory::CallFunctionForwardVarargs(), v8::internal::compiler::CodeAssembler::CallJS(), v8::internal::compiler::CodeAssembler::CallJSBuiltin(), v8::internal::CodeFactory::CallWithArrayLike(), v8::internal::CodeFactory::CallWithSpread(), v8::internal::CodeFactory::Construct(), v8::internal::CodeFactory::ConstructForwardVarargs(), v8::internal::CodeFactory::ConstructFunctionForwardVarargs(), v8::internal::compiler::CodeAssembler::ConstructJS(), v8::internal::CodeFactory::ConstructWithSpread(), v8::internal::compiler::JSCallReducer::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::PromiseBuiltinReducerAssembler::CreateClosureFromBuiltinSharedFunctionInfo(), v8::internal::compiler::CreateStubBuiltinContinuationFrameState(), v8::internal::CodeFactory::DefineNamedOwnIC(), v8::internal::CodeFactory::DefineNamedOwnICInOptimizedCode(), v8::internal::CodeFactory::FastNewFunctionContext(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GenerateBuiltinCall(), v8::internal::compiler::anonymous_namespace{js-call-reducer.cc}::GetCallableForArrayIndexOfIncludes(), v8::internal::CodeFactory::LoadGlobalIC(), v8::internal::CodeFactory::LoadGlobalICInOptimizedCode(), v8::internal::compiler::JSGraphAssembler::PlainPrimitiveToNumberOperator(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::JSIntrinsicLowering::ReduceAddLhsIsStringConstantInternalize(), v8::internal::compiler::JSIntrinsicLowering::ReduceAddRhsIsStringConstantInternalize(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncFunctionAwait(), v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncGeneratorAwait(), v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncGeneratorReject(), v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncGeneratorResolve(), v8::internal::compiler::JSIntrinsicLowering::ReduceAsyncGeneratorYieldWithAwait(), v8::internal::compiler::JSCallReducer::ReduceCallApiFunction(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSIntrinsicLowering::ReduceCopyDataProperties(), v8::internal::compiler::JSIntrinsicLowering::ReduceCopyDataPropertiesWithExcludedPropertiesOnStack(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::JSIntrinsicLowering::ReduceIncBlockCounter(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::compiler::JSTypedLowering::ReduceJSConstruct(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::JSGenericLowering::ReplaceWithBuiltinCall(), v8::internal::CodeFactory::StringAdd(), v8::internal::compiler::CodeAssembler::TailCallBuiltin(), v8::internal::compiler::CodeAssembler::TailCallBuiltinThenBytecodeDispatch(), v8::internal::compiler::CodeAssembler::TailCallJSBuiltin(), v8::internal::compiler::SimplifiedLowering::ToNumberCode(), v8::internal::compiler::SimplifiedLowering::ToNumberConvertBigIntCode(), v8::internal::compiler::SimplifiedLowering::ToNumberConvertBigIntOperator(), v8::internal::compiler::SimplifiedLowering::ToNumberOperator(), v8::internal::compiler::SimplifiedLowering::ToNumericCode(), and v8::internal::compiler::SimplifiedLowering::ToNumericOperator().
CallFunction()
constexpr Builtin v8::internal::Builtins::CallFunction (ConvertReceiverMode mode = ConvertReceiverMode::kAny) [inline], [static], [constexpr]
Definition at line 68 of file builtins-inl.h.
                                                                 {
  switch (mode) {
    case ConvertReceiverMode::kNullOrUndefined:
      return Builtin::kCallFunction_ReceiverIsNullOrUndefined;
    case ConvertReceiverMode::kNotNullOrUndefined:
      return Builtin::kCallFunction_ReceiverIsNotNullOrUndefined;
    case ConvertReceiverMode::kAny:
      return Builtin::kCallFunction_ReceiverIsAny;
  }
  UNREACHABLE();
}
References v8::internal::kAny, v8::internal::kNotNullOrUndefined, v8::internal::kNullOrUndefined, mode(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::CodeFactory::CallFunction(), v8::internal::CodeStubAssembler::CallFunction(), and Generate_Call().
CallInterfaceDescriptorFor()
CallInterfaceDescriptor v8::internal::Builtins::CallInterfaceDescriptorFor (Builtin builtin) [static]
Definition at line 189 of file builtins.cc.
                                                                            {
  CallDescriptors::Key key;
  switch (builtin) {
// This macro is deliberately crafted so as to emit very little code,
// in order to keep binary size of this function under control.
#define CASE_OTHER(Name, ...) \
  case Builtin::k##Name: { \
    key = Builtin_##Name##_InterfaceDescriptor::key(); \
    break; \
  }
    BUILTIN_LIST(IGNORE_BUILTIN, IGNORE_BUILTIN, IGNORE_BUILTIN, CASE_OTHER,
                 CASE_OTHER, CASE_OTHER, CASE_OTHER, IGNORE_BUILTIN, CASE_OTHER)
#undef CASE_OTHER
    default:
      Builtins::Kind kind = Builtins::KindOf(builtin);
      DCHECK_NE(BCH, kind);
      if (kind == TSJ || kind == TFJ || kind == CPP) {
        return JSTrampolineDescriptor{};
      }
      UNREACHABLE();
  }
  return CallInterfaceDescriptor{key};
}
References BCH, BUILTIN_LIST(), CASE_OTHER, CPP, DCHECK_NE, IGNORE_BUILTIN, v8::internal::key, KindOf(), TFJ, TSJ, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::WasmGraphBuilderBase::BuildChangeInt64ToBigInt(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), CallableFor(), v8::internal::maglev::MaglevAssembler::CallBuiltin(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallBuiltin(), v8::internal::maglev::MaxCallDepthProcessor::ConservativeFrameSize(), v8::internal::compiler::turboshaft::BuiltinCallDescriptor::Descriptor< Derived >::Create(), v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), EntrypointTagFor(), v8::internal::wasm::anonymous_namespace{wrappers.cc}::GetBuiltinCallDescriptor(), v8::internal::compiler::GetBuiltinCallDescriptor(), v8::internal::compiler::anonymous_namespace{instruction.cc}::GetConservativeFrameSizeInBytes(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame(), HasJSLinkage(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), SandboxingModeOf(), and v8::internal::maglev::CallBuiltin::VerifyInputs().
CEntry()
constexpr Builtin v8::internal::Builtins::CEntry (int result_size, ArgvMode argv_mode, bool builtin_exit_frame = false, bool switch_to_central_stack = false) [inline], [static], [constexpr]
Definition at line 161 of file builtins-inl.h.
                                                                 {
  // Aliases for readability below.
  const int rs = result_size;
  const ArgvMode am = argv_mode;
  const bool be = builtin_exit_frame;
  if (switch_to_central_stack) {
    DCHECK_EQ(result_size, 1);
    DCHECK_EQ(argv_mode, ArgvMode::kStack);
    DCHECK_EQ(builtin_exit_frame, false);
    return Builtin::kWasmCEntry;
  }
  if (rs == 1 && am == ArgvMode::kStack && !be) {
    return Builtin::kCEntry_Return1_ArgvOnStack_NoBuiltinExit;
  } else if (rs == 1 && am == ArgvMode::kStack && be) {
    return Builtin::kCEntry_Return1_ArgvOnStack_BuiltinExit;
  } else if (rs == 1 && am == ArgvMode::kRegister && !be) {
    return Builtin::kCEntry_Return1_ArgvInRegister_NoBuiltinExit;
  } else if (rs == 2 && am == ArgvMode::kStack && !be) {
    return Builtin::kCEntry_Return2_ArgvOnStack_NoBuiltinExit;
  } else if (rs == 2 && am == ArgvMode::kStack && be) {
    return Builtin::kCEntry_Return2_ArgvOnStack_BuiltinExit;
  } else if (rs == 2 && am == ArgvMode::kRegister && !be) {
    return Builtin::kCEntry_Return2_ArgvInRegister_NoBuiltinExit;
  }
  UNREACHABLE();
}
References DCHECK_EQ, v8::internal::kRegister, v8::internal::kStack, and v8::internal::UNREACHABLE().
Referenced by v8::internal::CodeFactory::CEntry(), v8::internal::CppBuiltinsAdaptorAssembler::GenerateAdaptor(), InterpreterCEntry(), v8::internal::MacroAssembler::JumpToExternalReference(), and RuntimeCEntry().
CheckFormalParameterCount()
bool v8::internal::Builtins::CheckFormalParameterCount (Builtin builtin, int function_length, int formal_parameter_count_with_receiver) [static]
Definition at line 166 of file builtins.cc.
                                              {
  DCHECK_LE(0, function_length);
  if (!Builtins::IsBuiltinId(builtin)) {
    return true;
  }
  if (!HasJSLinkage(builtin)) {
    return true;
  }
  // Some special builtins are allowed to be installed on functions with
  // different parameter counts.
  if (builtin == Builtin::kCompileLazy) {
    return true;
  }
  int parameter_count = Builtins::GetFormalParameterCount(builtin);
  return parameter_count == formal_parameter_count_with_receiver;
}
References DCHECK_LE, GetFormalParameterCount(), HasJSLinkage(), and IsBuiltinId().
Referenced by v8::internal::FactoryBase< Impl >::NewSharedFunctionInfo().
code()
Tagged< Code > v8::internal::Builtins::code (Builtin builtin)
Definition at line 149 of file builtins.cc.
                                           {
  Address ptr = isolate_->builtin_table()[Builtins::ToInt(builtin)];
  return Cast<Code>(Tagged<Object>(ptr));
}
References ToInt().
Referenced by CallableFor(), v8::internal::StubCache::Clear(), v8::internal::V8FileLogger::CodeCreateEvent(), CreateInterpreterEntryTrampolineForProfiling(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::Deoptimizer::DoComputeConstructCreateStubFrame(), v8::internal::Deoptimizer::DoComputeConstructInvokeStubFrame(), v8::internal::Deoptimizer::DoComputeUnoptimizedFrame(), EmitCodeCreateEvents(), v8::internal::Deoptimizer::EnsureValidReturnAddress(), v8::internal::BuiltinsConstantsTableBuilder::Finalize(), v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::interpreter::Interpreter::GetBytecodeHandler(), v8::internal::SharedFunctionInfo::GetCode(), v8::Isolate::GetJSEntryStubs(), v8::internal::Isolate::HashIsolateForEmbeddedBlob(), v8::internal::interpreter::Interpreter::Initialize(), v8::internal::Isolate::InitializeBuiltinJSDispatchTable(), InitializeIsolateDataTables(), IsBuiltin(), v8::internal::anonymous_namespace{isolate.cc}::IsBuiltinFunction(), IsIsolateIndependentBuiltin(), v8::internal::ProfilerCodeObserver::LogBuiltins(), Lookup(), v8::NewContext(), v8::internal::EmbeddedData::NewFromIsolate(), v8::internal::EmbeddedFileWriter::PrepareBuiltinSourcePositionMap(), PrintBuiltinCode(), PrintBuiltinSize(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), set_code(), v8::internal::EntryFrame::unchecked_code(), v8::internal::ConstructEntryFrame::unchecked_code(), v8::internal::Isolate::UnwindAndFindHandler(), and v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::Verify().
code_handle()
Handle< Code > v8::internal::Builtins::code_handle (Builtin builtin)
Definition at line 154 of file builtins.cc.
                                                  {
  Address* location = &isolate_->builtin_table()[Builtins::ToInt(builtin)];
  return Handle<Code>(location);
}
References ToInt().
Referenced by v8::internal::compiler::turboshaft::BuiltinCodeHandle(), CallableFor(), v8::internal::MacroAssembler::CallBuiltin(), v8::internal::CodeFactory::CEntry(), v8::internal::wasm::JSToWasmWrapperCompilationUnit::Finalize(), v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects(), v8::internal::WasmExportedFunction::GetWrapper(), v8::internal::WasmJSFunction::New(), and v8::internal::MacroAssembler::TailCallBuiltin().
CppEntryOf()
Address v8::internal::Builtins::CppEntryOf (Builtin builtin) [static]
Definition at line 350 of file builtins.cc.
                                            {
  DCHECK(Builtins::IsCpp(builtin));
  return builtin_metadata[ToInt(builtin)].data.cpp_entry;
}
References v8::internal::anonymous_namespace{builtins.cc}::builtin_metadata, v8::internal::anonymous_namespace{builtins.cc}::BuiltinMetadata::KindSpecificData::cpp_entry, v8::internal::anonymous_namespace{builtins.cc}::BuiltinMetadata::data, v8::internal::DCHECK(), IsCpp(), and ToInt().
Referenced by v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), and v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin().
CreateInterpreterEntryTrampolineForProfiling()
DirectHandle< Code > v8::internal::Builtins::CreateInterpreterEntryTrampolineForProfiling (Isolate * isolate) [static]
Definition at line 439 of file builtins.cc.
                      {
  DCHECK_NOT_NULL(isolate->embedded_blob_code());
  DCHECK_NE(0, isolate->embedded_blob_code_size());
  Tagged<Code> code = isolate->builtins()->code(
      Builtin::kInterpreterEntryTrampolineForProfiling);
  CodeDesc desc;
  desc.buffer = reinterpret_cast<uint8_t*>(code->instruction_start());
  int instruction_size = code->instruction_size();
  desc.buffer_size = instruction_size;
  desc.instr_size = instruction_size;
  // Ensure the code doesn't require creation of metadata, otherwise respective
  // fields of CodeDesc should be initialized.
  DCHECK_EQ(code->safepoint_table_size(), 0);
  DCHECK_EQ(code->handler_table_size(), 0);
  DCHECK_EQ(code->constant_pool_size(), 0);
  // TODO(v8:11036): The following DCHECK currently fails if the mksnapshot is
  // run with enabled code comments, i.e. --interpreted_frames_native_stack is
  // incompatible with --code-comments at mksnapshot-time. If ever needed,
  // implement support.
  DCHECK_EQ(code->code_comments_size(), 0);
  DCHECK_EQ(code->unwinding_info_size(), 0);
  desc.safepoint_table_offset = instruction_size;
  desc.handler_table_offset = instruction_size;
  desc.constant_pool_offset = instruction_size;
  desc.code_comments_offset = instruction_size;
  desc.jump_table_info_offset = instruction_size;
  CodeDesc::Verify(&desc);
  return Factory::CodeBuilder(isolate, desc, CodeKind::BUILTIN)
      // Mimic the InterpreterEntryTrampoline.
      .set_builtin(Builtin::kInterpreterEntryTrampoline)
      .Build();
}
References v8::internal::CodeDesc::buffer, v8::internal::CodeDesc::buffer_size, v8::internal::Factory::CodeBuilder::Build(), BUILTIN, v8::internal::Isolate::builtins(), code(), v8::internal::CodeDesc::code_comments_offset, v8::internal::CodeDesc::constant_pool_offset, DCHECK_EQ, DCHECK_NE, DCHECK_NOT_NULL, v8::internal::Isolate::embedded_blob_code(), v8::internal::Isolate::embedded_blob_code_size(), v8::internal::CodeDesc::handler_table_offset, v8::internal::CodeDesc::instr_size, v8::internal::CodeDesc::jump_table_info_offset, v8::internal::CodeDesc::safepoint_table_offset, v8::internal::Factory::CodeBuilder::set_builtin(), and v8::internal::CodeDesc::Verify().
Referenced by v8::internal::anonymous_namespace{code-serializer.cc}::CreateInterpreterDataForDeserializedCode(), and v8::internal::Compiler::InstallInterpreterTrampolineCopy().
EmbeddedEntryOf()
Address v8::internal::Builtins::EmbeddedEntryOf (Builtin builtin) [static]
Definition at line 355 of file builtins.cc.
                                                 {
  static_assert(Builtins::kAllBuiltinsAreIsolateIndependent);
  return EmbeddedData::FromBlob().InstructionStartOf(builtin);
}
References v8::internal::EmbeddedData::FromBlob(), v8::internal::EmbeddedData::InstructionStartOf(), and kAllBuiltinsAreIsolateIndependent.
Referenced by v8::internal::wasm::WasmImportWrapperCache::Get(), v8::internal::Isolate::Isolate(), v8::internal::ProfilerCodeObserver::LogBuiltins(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::WasmTableObject::UpdateDispatchTable().
EmitCodeCreateEvents()
void v8::internal::Builtins::EmitCodeCreateEvents (Isolate * isolate) [static]
Definition at line 410 of file builtins.cc.
                                                    {
  if (!isolate->IsLoggingCodeCreation()) return;
  Address* builtins = isolate->builtin_table();
  int i = 0;
  HandleScope scope(isolate);
  for (; i < ToInt(Builtin::kFirstBytecodeHandler); i++) {
    auto builtin_code = DirectHandle<Code>::FromSlot(&builtins[i]);
    DirectHandle<AbstractCode> code = Cast<AbstractCode>(builtin_code);
    PROFILE(isolate, CodeCreateEvent(LogEventListener::CodeTag::kBuiltin, code,
                                     Builtins::name(FromInt(i))));
  }
  static_assert(kLastBytecodeHandlerPlusOne == kBuiltinCount);
  for (; i < kBuiltinCount; i++) {
    auto builtin_code = DirectHandle<Code>::FromSlot(&builtins[i]);
    DirectHandle<AbstractCode> code = Cast<AbstractCode>(builtin_code);
    interpreter::Bytecode bytecode =
        builtin_metadata[i].data.bytecode_and_scale.bytecode;
    interpreter::OperandScale scale =
        builtin_metadata[i].data.bytecode_and_scale.scale;
    PROFILE(isolate,
            CodeCreateEvent(
                LogEventListener::CodeTag::kBytecodeHandler, code,
                interpreter::Bytecodes::ToString(bytecode, scale).c_str()));
  }
}
References v8::internal::anonymous_namespace{builtins.cc}::builtin_metadata, v8::internal::Isolate::builtin_table(), v8::internal::anonymous_namespace{builtins.cc}::BuiltinMetadata::BytecodeAndScale::bytecode, v8::internal::anonymous_namespace{builtins.cc}::BuiltinMetadata::KindSpecificData::bytecode_and_scale, code(), v8::internal::anonymous_namespace{builtins.cc}::BuiltinMetadata::data, FromInt(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Isolate::IsLoggingCodeCreation(), kBuiltinCount, kLastBytecodeHandlerPlusOne, name(), PROFILE, v8::internal::anonymous_namespace{builtins.cc}::BuiltinMetadata::BytecodeAndScale::scale, ToInt(), and v8::internal::interpreter::Bytecodes::ToString().
Referenced by v8::internal::V8FileLogger::LateSetup(), and v8::internal::PerfettoLogger::RegisterIsolate().
EntryOf()
Address v8::internal::Builtins::EntryOf (Builtin builtin, Isolate * isolate) [inline], [static]
Definition at line 241 of file builtins-inl.h.
                                                           {
#ifdef V8_ENABLE_WEBASSEMBLY
  // We don't use the isolate-specific copy of the WasmToJS wrapper; use
  // EmbeddedEntryOf() instead to get the isolate-independent copy.
  DCHECK(builtin != Builtin::kWasmToJsWrapperCSA &&
         builtin != Builtin::kWasmToJsWrapperAsm &&
         builtin != Builtin::kWasmToJsWrapperInvalidSig);
#endif
  return isolate->builtin_entry_table()[Builtins::ToInt(builtin)];
}
References v8::internal::Isolate::builtin_entry_table(), v8::internal::DCHECK(), and ToInt().
Referenced by v8::internal::InstructionStream::RelocateFromDesc().
EntrypointTagFor()
CodeEntrypointTag v8::internal::Builtins::EntrypointTagFor (Builtin builtin) [static]
Definition at line 510 of file builtins.cc.
                                                            {
  if (builtin == Builtin::kNoBuiltinId) {
    // Special case needed for example for tests.
    return kDefaultCodeEntrypointTag;
  }
#if V8_ENABLE_DRUMBRAKE
  if (builtin == Builtin::kGenericJSToWasmInterpreterWrapper) {
    return kJSEntrypointTag;
  } else if (builtin == Builtin::kGenericWasmToJSInterpreterWrapper) {
    return kWasmEntrypointTag;
  }
#endif // V8_ENABLE_DRUMBRAKE
  Kind kind = Builtins::KindOf(builtin);
  switch (kind) {
    case CPP:
    case TSJ:
    case TFJ:
      return kJSEntrypointTag;
    case BCH:
      return kBytecodeHandlerEntrypointTag;
    case TFC:
    case TSC:
    case TFS:
    case TFH:
    case ASM:
      return CallInterfaceDescriptorFor(builtin).tag();
  }
  UNREACHABLE();
}
References ASM, BCH, CallInterfaceDescriptorFor(), CPP, v8::internal::kBytecodeHandlerEntrypointTag, v8::internal::kDefaultCodeEntrypointTag, KindOf(), v8::internal::kJSEntrypointTag, v8::internal::kNoBuiltinId, v8::internal::kWasmEntrypointTag, v8::internal::CallInterfaceDescriptor::tag(), TFC, TFH, TFJ, TFS, TSC, TSJ, and v8::internal::UNREACHABLE().
Referenced by v8::internal::Code::entrypoint_tag().
EphemeronKeyBarrier()
constexpr Builtin v8::internal::Builtins::EphemeronKeyBarrier (SaveFPRegsMode fp_mode) [inline], [static], [constexpr]
Definition at line 37 of file builtins-inl.h.
                                                                      {
  switch (fp_mode) {
    case SaveFPRegsMode::kIgnore:
      return Builtin::kEphemeronKeyBarrierIgnoreFP;
    case SaveFPRegsMode::kSave:
      return Builtin::kEphemeronKeyBarrierSaveFP;
  }
}
References v8::internal::kIgnore, and v8::internal::kSave.
Referenced by v8::internal::MacroAssembler::CallEphemeronKeyBarrier().
FromInt()
static constexpr Builtin v8::internal::Builtins::FromInt (int id) [inline], [static], [constexpr]
Definition at line 210 of file builtins.h.
                                           {
    DCHECK(IsBuiltinId(id));
    return static_cast<Builtin>(id);
  }
References v8::internal::DCHECK(), and IsBuiltinId().
Referenced by v8::internal::IsolateData::builtin_slot_offset(), v8::internal::interpreter::anonymous_namespace{interpreter.cc}::BuiltinIndexFromBytecode(), EmitCodeCreateEvents(), GetBuiltinFromBytecodeOffset(), v8::internal::EmbeddedData::GetBuiltinId(), v8::internal::CallSiteInfo::GetFunctionName(), v8::internal::BuiltinsSorter::InitializeClusters(), IsBuiltinHandle(), and v8::internal::EmbeddedData::PrintStatistics().
Generate_Adaptor()
void v8::internal::Builtins::Generate_Adaptor (MacroAssembler * masm, int formal_parameter_count, Address builtin_address) [static]
Definition at line 39 of file builtins-riscv.cc.
                                                                             {
  ASM_CODE_COMMENT(masm);
  __ li(kJavaScriptCallExtraArg1Register, ExternalReference::Create(address));
  __ TailCallBuiltin(
      Builtins::AdaptorWithBuiltinExitFrame(formal_parameter_count));
}
References __, AdaptorWithBuiltinExitFrame(), ASM_CODE_COMMENT, v8::internal::ExternalReference::Create(), and v8::internal::kJavaScriptCallExtraArg1Register.
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildAdaptor().
Generate_Call()
void v8::internal::Builtins::Generate_Call (MacroAssembler * masm, ConvertReceiverMode mode) [static], [private]
Definition at line 2788 of file builtins-riscv.cc.
                                                                           {
  // ----------- S t a t e -------------
  // -- a0 : the number of arguments
  // -- a1 : the target to call (can be any Object).
  // -----------------------------------
  Register target = a1;
  Register map = t1;
  Register instance_type = t2;
  Register scratch = t6;
  DCHECK(!AreAliased(a0, target, map, instance_type, scratch));
  Label non_callable, class_constructor;
  __ JumpIfSmi(target, &non_callable);
  __ LoadMap(map, target);
  __ GetInstanceTypeRange(map, instance_type, FIRST_CALLABLE_JS_FUNCTION_TYPE,
                          scratch);
  __ TailCallBuiltin(Builtins::CallFunction(mode), ule, scratch,
                     Operand(LAST_CALLABLE_JS_FUNCTION_TYPE -
                             FIRST_CALLABLE_JS_FUNCTION_TYPE));
  __ TailCallBuiltin(Builtin::kCallBoundFunction, eq, instance_type,
                     Operand(JS_BOUND_FUNCTION_TYPE));
  // Check if target has a [[Call]] internal method.
  {
    Register flags = t1;
    __ Lbu(flags, FieldMemOperand(map, Map::kBitFieldOffset));
    map = no_reg;
    __ And(flags, flags, Operand(Map::Bits1::IsCallableBit::kMask));
    __ Branch(&non_callable, eq, flags, Operand(zero_reg));
  }
  __ TailCallBuiltin(Builtin::kCallProxy, eq, instance_type,
                     Operand(JS_PROXY_TYPE));
  // Check if target is a wrapped function and call CallWrappedFunction external
  // builtin
  __ TailCallBuiltin(Builtin::kCallWrappedFunction, eq, instance_type,
                     Operand(JS_WRAPPED_FUNCTION_TYPE));
  // ES6 section 9.2.1 [[Call]] (thisArgument, argumentsList)
  // Check that the function is not a "classConstructor".
  __ Branch(&class_constructor, eq, instance_type,
            Operand(JS_CLASS_CONSTRUCTOR_TYPE));
  // 2. Call to something else, which might have a [[Call]] internal method (if
  // not we raise an exception).
  // Overwrite the original receiver with the (original) target.
  __ StoreReceiver(target);
  // Let the "call_as_function_delegate" take care of the rest.
  __ LoadNativeContextSlot(target, Context::CALL_AS_FUNCTION_DELEGATE_INDEX);
  __ TailCallBuiltin(
      Builtins::CallFunction(ConvertReceiverMode::kNotNullOrUndefined));
  // 3. Call to something that is not callable.
  __ bind(&non_callable);
  {
    FrameScope scope(masm, StackFrame::INTERNAL);
    __ Push(target);
    __ CallRuntime(Runtime::kThrowCalledNonCallable);
  }
  // 4. The function is a "classConstructor", need to raise an exception.
  __ bind(&class_constructor);
  {
    FrameScope frame(masm, StackFrame::INTERNAL);
    __ Push(target);
    __ CallRuntime(Runtime::kThrowConstructorNonCallableError);
  }
}
References __, v8::internal::wasm::liftoff::And(), v8::internal::AreAliased(), CallFunction(), v8::internal::DCHECK(), v8::internal::eq, v8::internal::FieldMemOperand(), v8::internal::FIRST_CALLABLE_JS_FUNCTION_TYPE, v8::internal::flags, v8::internal::kNotNullOrUndefined, v8::internal::LAST_CALLABLE_JS_FUNCTION_TYPE, mode(), v8::internal::no_reg, and v8::internal::ule.
Generate_CallApiCallbackImpl()
void v8::internal::Builtins::Generate_CallApiCallbackImpl (MacroAssembler * masm, CallApiCallbackMode mode) [static], [private]
Definition at line 4508 of file builtins-riscv.cc.
                                                                      {
  // ----------- S t a t e -------------
  // CallApiCallbackMode::kOptimizedNoProfiling/kOptimized modes:
  // -- a1 : api function address
  // Both modes:
  // -- a2 : arguments count
  // -- a3 : FunctionTemplateInfo
  // -- cp : context
  // -- sp[0] : receiver
  // -- sp[8] : first argument
  // -- ...
  // -- sp[(argc) * 8] : last argument
  // -----------------------------------
  Register function_callback_info_arg = kCArgRegs[0];
  Register api_function_address = no_reg;
  Register argc = no_reg;
  Register func_templ = no_reg;
  Register topmost_script_having_context = no_reg;
  Register scratch = t0;
  switch (mode) {
    case CallApiCallbackMode::kGeneric:
      topmost_script_having_context = CallApiCallbackGenericDescriptor::
          TopmostScriptHavingContextRegister();
      argc = CallApiCallbackGenericDescriptor::ActualArgumentsCountRegister();
      func_templ =
          CallApiCallbackGenericDescriptor::FunctionTemplateInfoRegister();
      break;
    case CallApiCallbackMode::kOptimizedNoProfiling:
    case CallApiCallbackMode::kOptimized:
      // Caller context is always equal to current context because we don't
      // inline Api calls cross-context.
      topmost_script_having_context = kContextRegister;
      api_function_address =
          CallApiCallbackOptimizedDescriptor::ApiFunctionAddressRegister();
      argc = CallApiCallbackOptimizedDescriptor::ActualArgumentsCountRegister();
      func_templ =
          CallApiCallbackOptimizedDescriptor::FunctionTemplateInfoRegister();
      break;
  }
  DCHECK(!AreAliased(api_function_address, topmost_script_having_context, argc,
                     func_templ, scratch));
  using FCA = FunctionCallbackArguments;
  using ER = ExternalReference;
  using FC = ApiCallbackExitFrameConstants;
  static_assert(FCA::kArgsLength == 6);
  static_assert(FCA::kNewTargetIndex == 5);
  static_assert(FCA::kTargetIndex == 4);
  static_assert(FCA::kReturnValueIndex == 3);
  static_assert(FCA::kContextIndex == 2);
  static_assert(FCA::kIsolateIndex == 1);
  static_assert(FCA::kUnusedIndex == 0);
  // Set up FunctionCallbackInfo's implicit_args on the stack as follows:
  // Target state:
  // sp[0 * kSystemPointerSize]: kUnused <= FCA::implicit_args_
  // sp[1 * kSystemPointerSize]: kIsolate
  // sp[2 * kSystemPointerSize]: kContext
  // sp[3 * kSystemPointerSize]: undefined (kReturnValue)
  // sp[4 * kSystemPointerSize]: kTarget
  // sp[5 * kSystemPointerSize]: undefined (kNewTarget)
  // Existing state:
  // sp[6 * kSystemPointerSize]: <= FCA:::values_
  __ StoreRootRelative(IsolateData::topmost_script_having_context_offset(),
                       topmost_script_having_context);
  if (mode == CallApiCallbackMode::kGeneric) {
    api_function_address = ReassignRegister(topmost_script_having_context);
  }
  // Reserve space on the stack.
  static constexpr int kStackSize = FCA::kArgsLength;
  static_assert(kStackSize % 2 == 0);
  __ SubWord(sp, sp, Operand(kStackSize * kSystemPointerSize));
  // kIsolate.
  __ li(scratch, ER::isolate_address());
  __ StoreWord(scratch,
               MemOperand(sp, FCA::kIsolateIndex * kSystemPointerSize));
  // kContext
  __ StoreWord(cp, MemOperand(sp, FCA::kContextIndex * kSystemPointerSize));
  // kReturnValue
  __ LoadRoot(scratch, RootIndex::kUndefinedValue);
  __ StoreWord(scratch,
               MemOperand(sp, FCA::kReturnValueIndex * kSystemPointerSize));
  // kTarget.
  __ StoreWord(func_templ,
               MemOperand(sp, FCA::kTargetIndex * kSystemPointerSize));
  // kNewTarget.
  __ StoreWord(scratch,
               MemOperand(sp, FCA::kNewTargetIndex * kSystemPointerSize));
  // kUnused.
  __ StoreWord(scratch, MemOperand(sp, FCA::kUnusedIndex * kSystemPointerSize));
  FrameScope frame_scope(masm, StackFrame::MANUAL);
  if (mode == CallApiCallbackMode::kGeneric) {
    __ LoadExternalPointerField(
        api_function_address,
        FieldMemOperand(func_templ,
                        FunctionTemplateInfo::kMaybeRedirectedCallbackOffset),
        kFunctionTemplateInfoCallbackTag);
  }
  __ EnterExitFrame(scratch, FC::getExtraSlotsCountFrom<ExitFrameConstants>(),
                    StackFrame::API_CALLBACK_EXIT);
  MemOperand argc_operand = MemOperand(fp, FC::kFCIArgcOffset);
  {
    ASM_CODE_COMMENT_STRING(masm, "Initialize v8::FunctionCallbackInfo");
    // FunctionCallbackInfo::length_.
    // TODO(ishell): pass JSParameterCount(argc) to simplify things on the
    // caller end.
    __ StoreWord(argc, argc_operand);
    // FunctionCallbackInfo::implicit_args_.
    __ AddWord(scratch, fp, Operand(FC::kImplicitArgsArrayOffset));
    __ StoreWord(scratch, MemOperand(fp, FC::kFCIImplicitArgsOffset));
    // FunctionCallbackInfo::values_ (points at JS arguments on the stack).
    __ AddWord(scratch, fp, Operand(FC::kFirstArgumentOffset));
    __ StoreWord(scratch, MemOperand(fp, FC::kFCIValuesOffset));
  }
  __ RecordComment("v8::FunctionCallback's argument");
  __ AddWord(function_callback_info_arg, fp,
             Operand(FC::kFunctionCallbackInfoOffset));
  DCHECK(!AreAliased(api_function_address, function_callback_info_arg));
  ExternalReference thunk_ref = ER::invoke_function_callback(mode);
  Register no_thunk_arg = no_reg;
  MemOperand return_value_operand = MemOperand(fp, FC::kReturnValueOffset);
  static constexpr int kSlotsToDropOnReturn =
      FC::kFunctionCallbackInfoArgsLength + kJSArgcReceiverSlots;
  const bool with_profiling =
      mode != CallApiCallbackMode::kOptimizedNoProfiling;
  CallApiFunctionAndReturn(masm, with_profiling, api_function_address,
                           thunk_ref, no_thunk_arg, kSlotsToDropOnReturn,
                           &argc_operand, return_value_operand);
}
References __, v8::internal::AreAliased(), ASM_CODE_COMMENT_STRING, v8::internal::CallApiFunctionAndReturn(), v8::internal::cp, v8::internal::DCHECK(), v8::internal::FieldMemOperand(), v8::internal::CallApiCallbackOptimizedDescriptor::FunctionTemplateInfoRegister(), v8::internal::CallApiCallbackGenericDescriptor::FunctionTemplateInfoRegister(), v8::internal::kCArgRegs, v8::internal::kContextRegister, v8::internal::kFunctionTemplateInfoCallbackTag, v8::internal::kGeneric, v8::internal::kJSArgcReceiverSlots, v8::internal::kOptimized, v8::internal::kOptimizedNoProfiling, v8::base::anonymous_namespace{platform-starboard.cc}::kStackSize, v8::internal::kSystemPointerSize, v8::internal::StackFrame::MANUAL, mode(), v8::internal::no_reg, and v8::internal::ReassignRegister().
Generate_CallBoundFunctionImpl()
void v8::internal::Builtins::Generate_CallBoundFunctionImpl (MacroAssembler * masm) [static], [private]
Definition at line 2762 of file builtins-riscv.cc.
                                                                  {
  // ----------- S t a t e -------------
  // -- a0 : the number of arguments
  // -- a1 : the function to call (checked to be a JSBoundFunction)
  // -----------------------------------
  __ AssertBoundFunction(a1);
  // Patch the receiver to [[BoundThis]].
  {
    UseScratchRegisterScope temps(masm);
    Register scratch = temps.Acquire();
    __ LoadTaggedField(scratch,
                       FieldMemOperand(a1, JSBoundFunction::kBoundThisOffset));
    __ StoreReceiver(scratch);
  }
  // Push the [[BoundArguments]] onto the stack.
  Generate_PushBoundArguments(masm);
  // Call the [[BoundTargetFunction]] via the Call builtin.
  __ LoadTaggedField(
      a1, FieldMemOperand(a1, JSBoundFunction::kBoundTargetFunctionOffset));
  __ TailCallBuiltin(Builtins::Call());
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), Call(), v8::internal::FieldMemOperand(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_PushBoundArguments().
Generate_CallFunction()
void v8::internal::Builtins::Generate_CallFunction (MacroAssembler * masm, ConvertReceiverMode mode) [static], [private]
Definition at line 2600 of file builtins-riscv.cc.
                                                               {
  // ----------- S t a t e -------------
  // -- a0 : the number of arguments
  // -- a1 : the function to call (checked to be a JSFunction)
  // -----------------------------------
  __ AssertFunction(a1);
  __ LoadTaggedField(
      a2, FieldMemOperand(a1, JSFunction::kSharedFunctionInfoOffset));
  // Enter the context of the function; ToObject has to run in the function
  // context, and we also need to take the global proxy from the function
  // context in case of conversion.
  __ LoadTaggedField(cp, FieldMemOperand(a1, JSFunction::kContextOffset));
  // We need to convert the receiver for non-native sloppy mode functions.
  Label done_convert;
  __ Load32U(a3, FieldMemOperand(a2, SharedFunctionInfo::kFlagsOffset));
  __ And(kScratchReg, a3,
         Operand(SharedFunctionInfo::IsNativeBit::kMask |
                 SharedFunctionInfo::IsStrictBit::kMask));
  __ Branch(&done_convert, ne, kScratchReg, Operand(zero_reg));
  {
    // ----------- S t a t e -------------
    // -- a0 : the number of arguments
    // -- a1 : the function to call (checked to be a JSFunction)
    // -- a2 : the shared function info.
    // -- cp : the function context.
    // -----------------------------------
    if (mode == ConvertReceiverMode::kNullOrUndefined) {
      // Patch receiver to global proxy.
      __ LoadGlobalProxy(a3);
    } else {
      Label convert_to_object, convert_receiver;
      __ LoadReceiver(a3);
      __ JumpIfSmi(a3, &convert_to_object);
      __ JumpIfJSAnyIsNotPrimitive(a3, a4, &done_convert);
      if (mode != ConvertReceiverMode::kNotNullOrUndefined) {
        Label convert_global_proxy;
        __ JumpIfRoot(a3, RootIndex::kUndefinedValue, &convert_global_proxy);
        __ JumpIfNotRoot(a3, RootIndex::kNullValue, &convert_to_object);
        __ bind(&convert_global_proxy);
        {
          // Patch receiver to global proxy.
          __ LoadGlobalProxy(a3);
        }
        __ Branch(&convert_receiver);
      }
      __ bind(&convert_to_object);
      {
        // Convert receiver using ToObject.
        // TODO(bmeurer): Inline the allocation here to avoid building the frame
        // in the fast case? (fall back to AllocateInNewSpace?)
        FrameScope scope(masm, StackFrame::INTERNAL);
        __ SmiTag(a0);
        __ Push(a0, a1);
        __ Move(a0, a3);
        __ Push(cp);
        __ CallBuiltin(Builtin::kToObject);
        __ Pop(cp);
        __ Move(a3, a0);
        __ Pop(a0, a1);
        __ SmiUntag(a0);
      }
      __ LoadTaggedField(
          a2, FieldMemOperand(a1, JSFunction::kSharedFunctionInfoOffset));
      __ bind(&convert_receiver);
    }
    __ StoreReceiver(a3);
  }
  __ bind(&done_convert);
  // ----------- S t a t e -------------
  // -- a0 : the number of arguments
  // -- a1 : the function to call (checked to be a JSFunction)
  // -- a2 : the shared function info.
  // -- cp : the function context.
  // -----------------------------------
#if defined(V8_ENABLE_LEAPTIERING) && defined(V8_TARGET_ARCH_RISCV64)
  __ InvokeFunctionCode(a1, no_reg, a0, InvokeType::kJump);
#else
  __ Lhu(a2,
         FieldMemOperand(a2, SharedFunctionInfo::kFormalParameterCountOffset));
  __ InvokeFunctionCode(a1, no_reg, a2, a0, InvokeType::kJump);
#endif
}
References __, v8::internal::wasm::liftoff::And(), v8::internal::cp, v8::internal::FieldMemOperand(), kJump, v8::internal::kNotNullOrUndefined, v8::internal::kNullOrUndefined, v8::internal::kScratchReg, mode(), v8::internal::ne, v8::internal::no_reg, and v8::internal::TorqueRuntimeMacroShims::CodeStubAssembler::SmiUntag().
Generate_CallOrConstructForwardVarargs()
void v8::internal::Builtins::Generate_CallOrConstructForwardVarargs (MacroAssembler * masm, CallOrConstructMode mode, Builtin target_builtin) [static], [private]
Definition at line 2514 of file builtins-riscv.cc.
                                                                              {
  // ----------- S t a t e -------------
  // -- a0 : the number of arguments
  // -- a3 : the new.target (for [[Construct]] calls)
  // -- a1 : the target to call (can be any Object)
  // -- a2 : start index (to support rest parameters)
  // -----------------------------------
  UseScratchRegisterScope temps(masm);
  temps.Include(t0, t1);
  temps.Include(t2);
  // Check if new.target has a [[Construct]] internal method.
  if (mode == CallOrConstructMode::kConstruct) {
    Label new_target_constructor, new_target_not_constructor;
    UseScratchRegisterScope temps(masm);
    Register scratch = temps.Acquire();
    __ JumpIfSmi(a3, &new_target_not_constructor);
    __ LoadTaggedField(scratch, FieldMemOperand(a3, HeapObject::kMapOffset));
    __ Lbu(scratch, FieldMemOperand(scratch, Map::kBitFieldOffset));
    __ And(scratch, scratch, Operand(Map::Bits1::IsConstructorBit::kMask));
    __ Branch(&new_target_constructor, ne, scratch, Operand(zero_reg),
              Label::Distance::kNear);
    __ bind(&new_target_not_constructor);
    {
      FrameScope scope(masm, StackFrame::MANUAL);
      __ EnterFrame(StackFrame::INTERNAL);
      __ Push(a3);
      __ CallRuntime(Runtime::kThrowNotConstructor);
    }
    __ bind(&new_target_constructor);
  }
  __ Move(a6, fp);
  __ LoadWord(a7, MemOperand(fp, StandardFrameConstants::kArgCOffset));
  Label stack_done, stack_overflow;
  __ SubWord(a7, a7, Operand(kJSArgcReceiverSlots));
  __ SubWord(a7, a7, a2);
  __ Branch(&stack_done, le, a7, Operand(zero_reg));
  {
    // Check for stack overflow.
    __ StackOverflowCheck(a7, a4, a5, &stack_overflow);
    // Forward the arguments from the caller frame.
    // Point to the first argument to copy (skipping the receiver).
    __ AddWord(a6, a6,
               Operand(CommonFrameConstants::kFixedFrameSizeAboveFp +
                       kSystemPointerSize));
    __ CalcScaledAddress(a6, a6, a2, kSystemPointerSizeLog2);
    // Move the arguments already in the stack,
    // including the receiver and the return address.
    // a7: Number of arguments to make room for.
    // a0: Number of arguments already on the stack.
    // a2: Points to first free slot on the stack after arguments were shifted.
    Generate_AllocateSpaceAndShiftExistingArguments(masm, a7, a0, a2);
    // Copy arguments from the caller frame.
    // TODO(victorgomes): Consider using forward order as potentially more cache
    // friendly.
    {
      Label loop;
      __ bind(&loop);
      {
        UseScratchRegisterScope temps(masm);
        Register scratch = temps.Acquire(), addr = temps.Acquire();
        __ Sub32(a7, a7, Operand(1));
        __ CalcScaledAddress(addr, a6, a7, kSystemPointerSizeLog2);
        __ LoadWord(scratch, MemOperand(addr));
        __ CalcScaledAddress(addr, a2, a7, kSystemPointerSizeLog2);
        __ StoreWord(scratch, MemOperand(addr));
        __ Branch(&loop, ne, a7, Operand(zero_reg));
      }
    }
  }
  __ bind(&stack_done);
  // Tail-call to the actual Call or Construct builtin.
  __ TailCallBuiltin(target_builtin);
  __ bind(&stack_overflow);
  __ TailCallRuntime(Runtime::kThrowStackOverflow);
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), v8::internal::wasm::liftoff::And(), v8::internal::FieldMemOperand(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_AllocateSpaceAndShiftExistingArguments(), v8::internal::UseScratchRegisterScope::Include(), v8::internal::StandardFrameConstants::kArgCOffset, kConstruct, v8::internal::CommonFrameConstants::kFixedFrameSizeAboveFp, v8::internal::kJSArgcReceiverSlots, v8::internal::HeapObject::kMapOffset, v8::internal::kSystemPointerSize, v8::internal::kSystemPointerSizeLog2, v8::internal::le, v8::internal::StackFrame::MANUAL, mode(), and v8::internal::ne.
Generate_CallOrConstructVarargs()
void v8::internal::Builtins::Generate_CallOrConstructVarargs (MacroAssembler * masm, Builtin target_builtin) [static], [private]
Definition at line 2430 of file builtins-riscv.cc.
                                                                       {
  UseScratchRegisterScope temps(masm);
  temps.Include(t1, t0);
  // ----------- S t a t e -------------
  // -- a1 : target
  // -- a0 : number of parameters on the stack
  // -- a2 : arguments list (a FixedArray)
  // -- a4 : len (number of elements to push from args)
  // -- a3 : new.target (for [[Construct]])
  // -----------------------------------
  if (v8_flags.debug_code) {
    // Allow a2 to be a FixedArray, or a FixedDoubleArray if a4 == 0.
    Label ok, fail;
    __ AssertNotSmi(a2);
    __ GetObjectType(a2, kScratchReg, kScratchReg);
    __ Branch(&ok, eq, kScratchReg, Operand(FIXED_ARRAY_TYPE),
              Label::Distance::kNear);
    __ Branch(&fail, ne, kScratchReg, Operand(FIXED_DOUBLE_ARRAY_TYPE),
              Label::Distance::kNear);
    __ Branch(&ok, eq, a4, Operand(zero_reg), Label::Distance::kNear);
    // Fall through.
    __ bind(&fail);
    __ Abort(AbortReason::kOperandIsNotAFixedArray);
    __ bind(&ok);
  }
  Register args = a2;
  Register len = a4;
  // Check for stack overflow.
  Label stack_overflow;
  __ StackOverflowCheck(len, kScratchReg, a5, &stack_overflow);
  // Move the arguments already in the stack,
  // including the receiver and the return address.
  // a4: Number of arguments to make room for.
  // a0: Number of arguments already on the stack.
  // a7: Points to first free slot on the stack after arguments were shifted.
  Generate_AllocateSpaceAndShiftExistingArguments(masm, a4, a0, a7);
  // Push arguments onto the stack (thisArgument is already on the stack).
  {
    Label done, push, loop;
    Register src = a6;
    Register scratch = len;
    UseScratchRegisterScope temps(masm);
    __ AddWord(src, args, OFFSET_OF_DATA_START(FixedArray) - kHeapObjectTag);
    __ Branch(&done, eq, len, Operand(zero_reg), Label::Distance::kNear);
    __ SllWord(scratch, len, kTaggedSizeLog2);
    __ SubWord(scratch, sp, Operand(scratch));
#if !V8_STATIC_ROOTS_BOOL
    // We do not use the Branch(reg, RootIndex) macro without static roots,
    // as it would do a LoadRoot behind the scenes and we want to avoid that
    // in a loop.
    Register hole_value = temps.Acquire();
    __ LoadTaggedRoot(hole_value, RootIndex::kTheHoleValue);
#endif // !V8_STATIC_ROOTS_BOOL
    __ bind(&loop);
    __ LoadTaggedField(a5, MemOperand(src));
    __ AddWord(src, src, kTaggedSize);
#if V8_STATIC_ROOTS_BOOL
    __ CompareRootAndBranch(a5, RootIndex::kTheHoleValue, ne, &push);
#else
    __ CompareTaggedAndBranch(&push, ne, a5, Operand(hole_value));
#endif
    __ LoadRoot(a5, RootIndex::kUndefinedValue);
    __ bind(&push);
    __ StoreWord(a5, MemOperand(a7, 0));
    __ AddWord(a7, a7, Operand(kSystemPointerSize));
    __ AddWord(scratch, scratch, Operand(kTaggedSize));
    __ Branch(&loop, ne, scratch, Operand(sp));
    __ bind(&done);
  }
  // Tail-call to the actual Call or Construct builtin.
  __ TailCallBuiltin(target_builtin);
  __ bind(&stack_overflow);
  __ TailCallRuntime(Runtime::kThrowStackOverflow);
}
References __, v8::internal::UseScratchRegisterScope::Acquire(), v8::base::args, v8::internal::eq, v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_AllocateSpaceAndShiftExistingArguments(), v8::internal::UseScratchRegisterScope::Include(), v8::internal::kHeapObjectTag, v8::internal::kScratchReg, v8::internal::kSystemPointerSize, v8::internal::kTaggedSize, v8::internal::kTaggedSizeLog2, v8::internal::ne, OFFSET_OF_DATA_START, v8::internal::wasm::liftoff::push(), and v8::internal::v8_flags.
Generate_CEntry()
void v8::internal::Builtins::Generate_CEntry (MacroAssembler * masm, int result_size, ArgvMode argv_mode, bool builtin_exit_frame, bool switch_to_central_stack) [static]
Definition at line 3226 of file builtins-riscv.cc.
                                                             {
  // Called from JavaScript; parameters are on stack as if calling JS function
  // a0: number of arguments including receiver
  // a1: pointer to c++ function
  // fp: frame pointer (restored after C call)
  // sp: stack pointer (restored as callee's sp after C call)
  // cp: current context (C callee-saved)
  // If argv_mode == ArgvMode::kRegister:
  // a2: pointer to the first argument
  using ER = ExternalReference;
  static constexpr Register argc_input = a0;
  static constexpr Register target_input = a1;
  // Initialized below if ArgvMode::kStack.
  static constexpr Register argv_input = s1;
  static constexpr Register argc_sav = s3;
  static constexpr Register scratch = a3;
  if (argv_mode == ArgvMode::kRegister) {
    // Move argv into the correct register.
    __ Move(s1, a2);
  } else {
    // Compute the argv pointer in a callee-saved register.
    __ CalcScaledAddress(s1, sp, a0, kSystemPointerSizeLog2);
    __ SubWord(s1, s1, kSystemPointerSize);
  }
  // Enter the exit frame that transitions from JavaScript to C++.
  FrameScope scope(masm, StackFrame::MANUAL);
  __ EnterExitFrame(
      scratch, 0,
      builtin_exit_frame ? StackFrame::BUILTIN_EXIT : StackFrame::EXIT);
  // s3: number of arguments including receiver (C callee-saved)
  // s1: pointer to first argument (C callee-saved)
  // s2: pointer to builtin function (C callee-saved)
  // Prepare arguments for C routine.
  // a0 = argc
  __ Move(argc_sav, argc_input);
  __ Move(s2, target_input);
  // We are calling compiled C/C++ code. a0 and a1 hold our two arguments. We
  // also need to reserve the 4 argument slots on the stack.
  __ AssertStackIsAligned();
#if V8_ENABLE_WEBASSEMBLY
  if (switch_to_central_stack) {
    SwitchToTheCentralStackIfNeeded(masm, argc_input, target_input, argv_input);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  // a0 = argc, a1 = argv, a2 = isolate
  __ li(a2, ER::isolate_address(masm->isolate()));
  __ Move(a1, s1);
  __ StoreReturnAddressAndCall(s2);
  // Check result for exception sentinel.
  Label exception_returned;
  // The returned value may be a trusted object, living outside of the main
  // pointer compression cage, so we need to use full pointer comparison here.
  __ CompareRootAndBranch(a0, RootIndex::kException, eq, &exception_returned,
                          ComparisonMode::kFullPointer);
  // Result returned in a0 or a1:a0 - do not destroy these registers!
#if V8_ENABLE_WEBASSEMBLY
  if (switch_to_central_stack) {
    SwitchFromTheCentralStackIfNeeded(masm);
  }
#endif // V8_ENABLE_WEBASSEMBLY
  // Exit C frame and return.
  // a0:a1: result
  // sp: stack pointer
  // fp: frame pointer
  // s3: still holds argc (C caller-saved).
  __ LeaveExitFrame(scratch);
  if (argv_mode == ArgvMode::kStack) {
    DCHECK(!AreAliased(scratch, argc_sav));
    __ DropArguments(argc_sav);
  }
  __ Ret();
  // Handling of exception.
  __ bind(&exception_returned);
  ER pending_handler_context_address = ER::Create(
      IsolateAddressId::kPendingHandlerContextAddress, masm->isolate());
  ER pending_handler_entrypoint_address = ER::Create(
      IsolateAddressId::kPendingHandlerEntrypointAddress, masm->isolate());
  ER pending_handler_fp_address =
      ER::Create(IsolateAddressId::kPendingHandlerFPAddress, masm->isolate());
  ER pending_handler_sp_address =
      ER::Create(IsolateAddressId::kPendingHandlerSPAddress, masm->isolate());
  // Ask the runtime for help to determine the handler. This will set a0 to
  // contain the current exception, don't clobber it.
  ER find_handler = ER::Create(Runtime::kUnwindAndFindExceptionHandler);
  {
    FrameScope scope(masm, StackFrame::MANUAL);
    __ PrepareCallCFunction(3, 0, a0);
    __ Move(a0, zero_reg);
    __ Move(a1, zero_reg);
    __ li(a2, ER::isolate_address());
    __ CallCFunction(find_handler, 3, SetIsolateDataSlots::kNo);
  }
  // Retrieve the handler context, SP and FP.
  __ li(cp, pending_handler_context_address);
  __ LoadWord(cp, MemOperand(cp));
  __ li(sp, pending_handler_sp_address);
  __ LoadWord(sp, MemOperand(sp));
  __ li(fp, pending_handler_fp_address);
  __ LoadWord(fp, MemOperand(fp));
  // If the handler is a JS frame, restore the context to the frame. Note that
  // the context will be set to (cp == 0) for non-JS frames.
  Label zero;
  __ Branch(&zero, eq, cp, Operand(zero_reg), Label::Distance::kNear);
  __ StoreWord(cp, MemOperand(fp, StandardFrameConstants::kContextOffset));
  __ bind(&zero);
  // Clear c_entry_fp, like we do in `LeaveExitFrame`.
  ER c_entry_fp_address =
      ER::Create(IsolateAddressId::kCEntryFPAddress, masm->isolate());
  __ StoreWord(zero_reg,
               __ ExternalReferenceAsOperand(c_entry_fp_address, no_reg));
  // Compute the handler entry address and jump to it.
  __ LoadWord(scratch, __ ExternalReferenceAsOperand(
                           pending_handler_entrypoint_address, no_reg));
  __ Jump(scratch);
}
References __, v8::internal::AreAliased(), v8::internal::cp, v8::internal::DCHECK(), v8::internal::eq, v8::internal::MacroAssemblerBase::isolate(), v8::internal::StandardFrameConstants::kContextOffset, v8::debug::kException, kFullPointer, kNo, v8::internal::kRegister, v8::internal::kStack, v8::internal::kSystemPointerSize, v8::internal::kSystemPointerSizeLog2, v8::internal::StackFrame::MANUAL, v8::internal::no_reg, v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchFromTheCentralStackIfNeeded(), v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchToTheCentralStackIfNeeded(), and v8::internal::zero.
Generate_ConstructForwardAllArgsImpl()
void v8::internal::Builtins::Generate_ConstructForwardAllArgsImpl (MacroAssembler * masm, ForwardWhichFrame which_frame) [static], [private]
Definition at line 1543 of file builtins-riscv.cc.
                                                         {
  // ----------- S t a t e -------------
  // -- a3 : new target
  // -- a1 : constructor to call
  // -----------------------------------
  Label stack_overflow;
  // Load the frame pointer into a4.
  switch (which_frame) {
    case ForwardWhichFrame::kCurrentFrame:
      __ Move(a4, fp);
      break;
    case ForwardWhichFrame::kParentFrame:
      __ LoadWord(a4, MemOperand(fp, StandardFrameConstants::kCallerFPOffset));
      break;
  }
  // Load the argument count into a0.
  __ LoadWord(a0, MemOperand(a4, StandardFrameConstants::kArgCOffset));
  __ StackOverflowCheck(a0, a5, t0, &stack_overflow);
  // Point a4 to the base of the argument list to forward, excluding the
  // receiver.
  __ AddWord(a4, a4,
             Operand((StandardFrameConstants::kFixedSlotCountAboveFp + 1) *
                     kSystemPointerSize));
  // Copy arguments on the stack. a5 is a scratch register.
  Register argc_without_receiver = a6;
  __ SubWord(argc_without_receiver, a0, Operand(kJSArgcReceiverSlots));
  __ PushArray(a4, argc_without_receiver);
  // Push a slot for the receiver.
  __ push(zero_reg);
  // Call the constructor with a0, a1, and a3 unmodified.
  __ TailCallBuiltin(Builtin::kConstruct);
  __ bind(&stack_overflow);
  {
    __ TailCallRuntime(Runtime::kThrowStackOverflow);
    // Unreachable code.
    __ break_(0xCC);
  }
}
References __, v8::internal::StandardFrameConstants::kArgCOffset, v8::internal::CommonFrameConstants::kCallerFPOffset, kCurrentFrame, v8::internal::CommonFrameConstants::kFixedSlotCountAboveFp, v8::internal::kJSArgcReceiverSlots, kParentFrame, v8::internal::kSystemPointerSize, and v8::internal::wasm::liftoff::push().
Generate_InterpreterEntryTrampoline()
void v8::internal::Builtins::Generate_InterpreterEntryTrampoline (MacroAssembler * masm, InterpreterEntryTrampolineMode mode) [static], [private]
Definition at line 12 of file builtins-interpreter-gen.cc.
                                                                       {
  Generate_InterpreterEntryTrampoline(masm,
                                      InterpreterEntryTrampolineMode::kDefault);
}
References kDefault.
Generate_InterpreterPushArgsThenCallImpl()
void v8::internal::Builtins::Generate_InterpreterPushArgsThenCallImpl (MacroAssembler * masm, ConvertReceiverMode receiver_mode, InterpreterPushArgsMode mode) [static], [private]
Definition at line 1433 of file builtins-riscv.cc.
                                  {
  DCHECK(mode != InterpreterPushArgsMode::kArrayFunction);
  // ----------- S t a t e -------------
  // -- a0 : the number of arguments
  // -- a2 : the address of the first argument to be pushed. Subsequent
  // arguments should be consecutive above this, in the same order as
  // they are to be pushed onto the stack.
  // -- a1 : the target to call (can be any Object).
  // -----------------------------------
  Label stack_overflow;
  if (mode == InterpreterPushArgsMode::kWithFinalSpread) {
    // The spread argument should not be pushed.
    __ SubWord(a0, a0, Operand(1));
  }
  if (receiver_mode == ConvertReceiverMode::kNullOrUndefined) {
    __ SubWord(a3, a0, Operand(kJSArgcReceiverSlots));
  } else {
    __ Move(a3, a0);
  }
  __ StackOverflowCheck(a3, a4, t0, &stack_overflow);
  // This function modifies a2 and a4.
  GenerateInterpreterPushArgs(masm, a3, a2, a4);
  if (receiver_mode == ConvertReceiverMode::kNullOrUndefined) {
    __ PushRoot(RootIndex::kUndefinedValue);
  }
  if (mode == InterpreterPushArgsMode::kWithFinalSpread) {
    // Pass the spread in the register a2.
    // a2 already points to the penultime argument, the spread
    // is below that.
    __ LoadWord(a2, MemOperand(a2, -kSystemPointerSize));
  }
  // Call the target.
  if (mode == InterpreterPushArgsMode::kWithFinalSpread) {
    __ TailCallBuiltin(Builtin::kCallWithSpread);
  } else {
    __ TailCallBuiltin(Builtins::Call(receiver_mode));
  }
  __ bind(&stack_overflow);
  {
    __ TailCallRuntime(Runtime::kThrowStackOverflow);
    // Unreachable code.
    __ break_(0xCC);
  }
}
References __, Call(), v8::internal::DCHECK(), v8::internal::GenerateInterpreterPushArgs(), v8::internal::kArrayFunction, v8::internal::kJSArgcReceiverSlots, v8::internal::kNullOrUndefined, v8::internal::kSystemPointerSize, v8::internal::kWithFinalSpread, and mode().
Generate_InterpreterPushArgsThenConstructImpl()
void v8::internal::Builtins::Generate_InterpreterPushArgsThenConstructImpl (MacroAssembler * masm, InterpreterPushArgsMode mode) [static], [private]
Definition at line 1486 of file builtins-riscv.cc.
                                                        {
  // ----------- S t a t e -------------
  // -- a0 : argument count
  // -- a3 : new target
  // -- a1 : constructor to call
  // -- a2 : allocation site feedback if available, undefined otherwise.
  // -- a4 : address of the first argument
  // -----------------------------------
  Label stack_overflow;
  __ StackOverflowCheck(a0, a5, t0, &stack_overflow);
  if (mode == InterpreterPushArgsMode::kWithFinalSpread) {
    // The spread argument should not be pushed.
    __ SubWord(a0, a0, Operand(1));
  }
  Register argc_without_receiver = a6;
  __ SubWord(argc_without_receiver, a0, Operand(kJSArgcReceiverSlots));
  // Push the arguments, This function modifies a4 and a5.
  GenerateInterpreterPushArgs(masm, argc_without_receiver, a4, a5);
  // Push a slot for the receiver.
  __ push(zero_reg);
  if (mode == InterpreterPushArgsMode::kWithFinalSpread) {
    // Pass the spread in the register a2.
    // a4 already points to the penultimate argument, the spread
    // lies in the next interpreter register.
    __ LoadWord(a2, MemOperand(a4, -kSystemPointerSize));
  } else {
    __ AssertUndefinedOrAllocationSite(a2, t0);
  }
  if (mode == InterpreterPushArgsMode::kArrayFunction) {
    __ AssertFunction(a1);
    // Tail call to the function-specific construct stub (still in the caller
    // context at this point).
    __ TailCallBuiltin(Builtin::kArrayConstructorImpl);
  } else if (mode == InterpreterPushArgsMode::kWithFinalSpread) {
    // Call the constructor with a0, a1, and a3 unmodified.
    __ TailCallBuiltin(Builtin::kConstructWithSpread);
  } else {
    DCHECK_EQ(InterpreterPushArgsMode::kOther, mode);
    // Call the constructor with a0, a1, and a3 unmodified.
    __ TailCallBuiltin(Builtin::kConstruct);
  }
  __ bind(&stack_overflow);
  {
    __ TailCallRuntime(Runtime::kThrowStackOverflow);
    // Unreachable code.
    __ break_(0xCC);
  }
}
References __, DCHECK_EQ, v8::internal::GenerateInterpreterPushArgs(), v8::internal::kArrayFunction, v8::internal::kJSArgcReceiverSlots, v8::internal::kOther, v8::internal::kSystemPointerSize, v8::internal::kWithFinalSpread, mode(), and v8::internal::wasm::liftoff::push().
Generate_MaglevFunctionEntryStackCheck()
void v8::internal::Builtins::Generate_MaglevFunctionEntryStackCheck (MacroAssembler * masm, bool save_new_target) [static], [private]
Definition at line 1476 of file builtins-internal-gen.cc.
                                                                            {
  masm->Trap();
}
References v8::internal::MacroAssembler::Trap().
GetBuiltinFromBytecodeOffset()
Builtin v8::internal::Builtins::GetBuiltinFromBytecodeOffset (BytecodeOffset id) [static]
Definition at line 104 of file builtins.cc.
                                                                {
  Builtin builtin = Builtins::FromInt(
      id.ToInt() - BytecodeOffset::kFirstBuiltinContinuationId);
  DCHECK(Builtins::KindOf(builtin) == TFJ || Builtins::KindOf(builtin) == TFC ||
         Builtins::KindOf(builtin) == TFS);
  return builtin;
}
References v8::internal::DCHECK(), FromInt(), v8::internal::BytecodeOffset::kFirstBuiltinContinuationId, KindOf(), TFC, TFJ, TFS, and ToInt().
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::compiler::anonymous_namespace{instruction.cc}::GetConservativeFrameSizeInBytes(), and v8::internal::OptimizedJSFrame::Summarize().
GetContinuationBytecodeOffset()
BytecodeOffset v8::internal::Builtins::GetContinuationBytecodeOffset (Builtin builtin) [static]
Definition at line 97 of file builtins.cc.
                                                                      {
  DCHECK(Builtins::KindOf(builtin) == TFJ || Builtins::KindOf(builtin) == TFC ||
         Builtins::KindOf(builtin) == TFS);
  return BytecodeOffset(BytecodeOffset::kFirstBuiltinContinuationId +
                        ToInt(builtin));
}
References v8::internal::DCHECK(), v8::internal::BytecodeOffset::kFirstBuiltinContinuationId, KindOf(), TFC, TFJ, TFS, and ToInt().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), v8::internal::compiler::anonymous_namespace{frame-states.cc}::CreateBuiltinContinuationFrameStateCommon(), and v8::internal::maglev::DeoptFrame::GetBytecodeOffset().
GetFormalParameterCount()
int v8::internal::Builtins::GetFormalParameterCount (Builtin builtin) [inline], [static]
Definition at line 266 of file builtins-inl.h.
                                                     {
  CHECK(HasJSLinkage(builtin));
  // TODO(saelo): consider merging GetFormalParameterCount and
  // GetStackParameterCount into a single function.
  if (Builtins::KindOf(builtin) == TSJ || Builtins::KindOf(builtin) == TFJ) {
    return Builtins::GetStackParameterCount(builtin);
  } else if (Builtins::KindOf(builtin) == ASM ||
             Builtins::KindOf(builtin) == TFC) {
    // At the moment, all ASM builtins are varargs builtins. This is verified
    // in CheckFormalParameterCount.
    return kDontAdaptArgumentsSentinel;
  } else if (Builtins::KindOf(builtin) == CPP) {
#define CPP_BUILTIN(Name, Argc) \
  case Builtin::k##Name: \
    return Argc;
    switch (builtin) {
      BUILTIN_LIST_C(CPP_BUILTIN)
      default:
        UNREACHABLE();
    }
#undef CPP_BUILTIN
  } else {
    UNREACHABLE();
  }
}
References ASM, BUILTIN_LIST_C, CHECK, CPP, CPP_BUILTIN, GetStackParameterCount(), HasJSLinkage(), v8::internal::kDontAdaptArgumentsSentinel, KindOf(), TFC, TFJ, TSJ, and v8::internal::UNREACHABLE().
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildAdaptor(), CheckFormalParameterCount(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), and v8::internal::compiler::JSTypedLowering::ReduceJSCall().
GetStackParameterCount()
int v8::internal::Builtins::GetStackParameterCount (Builtin builtin) [static]
Definition at line 160 of file builtins.cc.
                                                    {
  DCHECK(Builtins::KindOf(builtin) == TSJ || Builtins::KindOf(builtin) == TFJ);
  return builtin_metadata[ToInt(builtin)].data.parameter_count;
}
References v8::internal::anonymous_namespace{builtins.cc}::builtin_metadata, v8::internal::anonymous_namespace{builtins.cc}::BuiltinMetadata::data, v8::internal::DCHECK(), KindOf(), v8::internal::anonymous_namespace{builtins.cc}::BuiltinMetadata::KindSpecificData::parameter_count, TFJ, ToInt(), and TSJ.
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), v8::internal::compiler::CodeAssembler::CallJSBuiltin(), v8::internal::compiler::CreateJavaScriptBuiltinContinuationFrameState(), v8::internal::SharedFunctionInfo::DontAdaptArguments(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), GetFormalParameterCount(), and v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame().
HasJSLinkage()
bool v8::internal::Builtins::HasJSLinkage (Builtin builtin) [static]
Definition at line 220 of file builtins.cc.
                                           {
  DCHECK_NE(BCH, Builtins::KindOf(builtin));
  return CallInterfaceDescriptorFor(builtin) == JSTrampolineDescriptor{};
}
References BCH, CallInterfaceDescriptorFor(), DCHECK_NE, and KindOf().
Referenced by v8::internal::compiler::CodeAssembler::CallBuiltin(), v8::internal::compiler::CodeAssembler::CallBuiltinVoid(), v8::internal::compiler::CodeAssembler::CallJSBuiltin(), CheckFormalParameterCount(), v8::internal::anonymous_namespace{bootstrapper.cc}::CreateFunction(), GetFormalParameterCount(), v8::internal::anonymous_namespace{bootstrapper.cc}::InstallFunction(), v8::internal::compiler::JSTypedLowering::ReduceJSCall(), v8::internal::anonymous_namespace{bootstrapper.cc}::SimpleCreateFunction(), v8::internal::compiler::CodeAssembler::TailCallBuiltin(), and v8::internal::compiler::CodeAssembler::TailCallJSBuiltin().
IndirectPointerBarrier()
constexpr Builtin v8::internal::Builtins::IndirectPointerBarrier (SaveFPRegsMode fp_mode) [inline], [static], [constexpr]
Definition at line 27 of file builtins-inl.h.
                                                                         {
  switch (fp_mode) {
    case SaveFPRegsMode::kIgnore:
      return Builtin::kIndirectPointerBarrierIgnoreFP;
    case SaveFPRegsMode::kSave:
      return Builtin::kIndirectPointerBarrierSaveFP;
  }
}
References v8::internal::kIgnore, and v8::internal::kSave.
Referenced by v8::internal::MacroAssembler::CallIndirectPointerBarrier().
InitializeIsolateDataTables()
void v8::internal::Builtins::InitializeIsolateDataTables (Isolate * isolate) [static]
Definition at line 384 of file builtins.cc.
                                                           {
  EmbeddedData embedded_data = EmbeddedData::FromBlob(isolate);
  IsolateData* isolate_data = isolate->isolate_data();
  // The entry table.
  for (Builtin i = Builtins::kFirst; i <= Builtins::kLast; ++i) {
    DCHECK(Builtins::IsBuiltinId(isolate->builtins()->code(i)->builtin_id()));
    DCHECK(!isolate->builtins()->code(i)->has_instruction_stream());
    Builtin builtin_id = i;
#if V8_ENABLE_GEARBOX
    builtin_id = isolate->builtins()->code(i)->builtin_id();
#endif // V8_ENABLE_GEARBOX
    isolate_data->builtin_entry_table()[ToInt(i)] =
        embedded_data.InstructionStartOf(builtin_id);
  }
  // T0 tables.
  for (Builtin i = Builtins::kFirst; i <= Builtins::kLastTier0; ++i) {
    const int ii = ToInt(i);
    isolate_data->builtin_tier0_entry_table()[ii] =
        isolate_data->builtin_entry_table()[ii];
    isolate_data->builtin_tier0_table()[ii] = isolate_data->builtin_table()[ii];
  }
}
References v8::internal::IsolateData::builtin_entry_table(), v8::internal::IsolateData::builtin_table(), v8::internal::IsolateData::builtin_tier0_entry_table(), v8::internal::IsolateData::builtin_tier0_table(), v8::internal::Isolate::builtins(), code(), v8::internal::DCHECK(), v8::internal::EmbeddedData::FromBlob(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::EmbeddedData::InstructionStartOf(), IsBuiltinId(), v8::internal::Isolate::isolate_data(), kFirst, kLast, kLastTier0, and ToInt().
Referenced by v8::internal::Isolate::Init().
InterpreterCEntry()
constexpr Builtin v8::internal::Builtins::InterpreterCEntry (int result_size) [inline], [static], [constexpr]
Definition at line 200 of file builtins-inl.h.
                                                             {
  return CEntry(result_size, ArgvMode::kRegister);
}
References CEntry(), and v8::internal::kRegister.
Referenced by v8::internal::interpreter::InterpreterAssembler::CallRuntimeN().
InterpreterPushArgsThenCall()
constexpr Builtin v8::internal::Builtins::InterpreterPushArgsThenCall (ConvertReceiverMode receiver_mode, InterpreterPushArgsMode mode) [inline], [static], [constexpr]
Definition at line 205 of file builtins-inl.h.
                                                                     {
  switch (mode) {
    case InterpreterPushArgsMode::kArrayFunction:
      // There is no special-case handling of calls to Array. They will all go
      // through the kOther case below.
      UNREACHABLE();
    case InterpreterPushArgsMode::kWithFinalSpread:
      return Builtin::kInterpreterPushArgsThenCallWithFinalSpread;
    case InterpreterPushArgsMode::kOther:
      switch (receiver_mode) {
        case ConvertReceiverMode::kNullOrUndefined:
          return Builtin::kInterpreterPushUndefinedAndArgsThenCall;
        case ConvertReceiverMode::kNotNullOrUndefined:
        case ConvertReceiverMode::kAny:
          return Builtin::kInterpreterPushArgsThenCall;
      }
  }
  UNREACHABLE();
}
References v8::internal::kAny, v8::internal::kArrayFunction, v8::internal::kNotNullOrUndefined, v8::internal::kNullOrUndefined, v8::internal::kOther, v8::internal::kWithFinalSpread, mode(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::InterpreterAssembler::CallJSAndDispatch(), and v8::internal::interpreter::InterpreterAssembler::CallJSWithSpreadAndDispatch().
InterpreterPushArgsThenConstruct()
constexpr Builtin v8::internal::Builtins::InterpreterPushArgsThenConstruct (InterpreterPushArgsMode mode) [inline], [static], [constexpr]
Definition at line 227 of file builtins-inl.h.
                                  {
  switch (mode) {
    case InterpreterPushArgsMode::kArrayFunction:
      return Builtin::kInterpreterPushArgsThenConstructArrayFunction;
    case InterpreterPushArgsMode::kWithFinalSpread:
      return Builtin::kInterpreterPushArgsThenConstructWithFinalSpread;
    case InterpreterPushArgsMode::kOther:
      return Builtin::kInterpreterPushArgsThenConstruct;
  }
  UNREACHABLE();
}
References v8::internal::kArrayFunction, v8::internal::kOther, v8::internal::kWithFinalSpread, mode(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::InterpreterAssembler::Construct(), and v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread().
InvokeApiFunction()
MaybeHandle< Object > v8::internal::Builtins::InvokeApiFunction (Isolate * isolate, bool is_construct, DirectHandle< FunctionTemplateInfo > function, DirectHandle< Object > receiver, base::Vector< const DirectHandle< Object >> args, DirectHandle< HeapObject > new_target) [static]
Definition at line 165 of file builtins-api.cc.
                                         {
  RCS_SCOPE(isolate, RuntimeCallCounterId::kInvokeApiFunction);
  // Do proper receiver conversion for non-strict mode api functions.
  if (!is_construct && !IsJSReceiver(*receiver)) {
    ASSIGN_RETURN_ON_EXCEPTION(isolate, receiver,
                               Object::ConvertReceiver(isolate, receiver));
  }
  // We assume that all lazy accessor pairs have been instantiated when setting
  // a break point on any API function.
  DCHECK(!Cast<FunctionTemplateInfo>(function)->BreakAtEntry(isolate));
  int argc = static_cast<int>(args.size());
  base::SmallVector<Address, 32> argv(argc + 1);
  argv[0] = (*receiver).ptr();
  for (int i = 0; i < argc; ++i) {
    argv[i + 1] = (*args[i]).ptr();
  }
  RelocatableArguments arguments(isolate, argv.size(), argv.data());
  if (is_construct) {
    return HandleApiCallHelper<true>(isolate, new_target, function, receiver,
                                     argv.data() + 1, argc);
  }
  return HandleApiCallHelper<false>(isolate, new_target, function, receiver,
                                    argv.data() + 1, argc);
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Object::ConvertReceiver(), v8::base::SmallVector< T, kSize, Allocator >::data(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, RCS_SCOPE, and v8::base::SmallVector< T, kSize, Allocator >::size().
Referenced by v8::internal::Object::GetPropertyWithAccessor(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), and v8::internal::Object::SetPropertyWithAccessor().
is_initialized()
bool v8::internal::Builtins::is_initialized () const [inline]
Definition at line 362 of file builtins.h.
{ return initialized_; }
References initialized_.
Referenced by v8::internal::Isolate::HashIsolateForEmbeddedBlob(), v8::internal::interpreter::Interpreter::Initialize(), v8::internal::ExistingCodeLogger::LogBuiltins(), and v8::internal::ProfilerCodeObserver::LogBuiltins().
IsAnyCall()
constexpr bool v8::internal::Builtins::IsAnyCall (Builtin builtin) [inline], [static], [constexpr]
Definition at line 94 of file builtins-inl.h.
                                                  {
  switch (builtin) {
    case Builtin::kCallFunction_ReceiverIsNullOrUndefined:
    case Builtin::kCallFunction_ReceiverIsNotNullOrUndefined:
    case Builtin::kCallFunction_ReceiverIsAny:
    case Builtin::kCall_ReceiverIsNullOrUndefined:
    case Builtin::kCall_ReceiverIsNotNullOrUndefined:
    case Builtin::kCall_ReceiverIsAny:
      return true;
    default:
      return false;
  }
}
Referenced by v8::internal::compiler::CodeAssembler::CallJS().
IsBuiltin()
bool v8::internal::Builtins::IsBuiltin (const Tagged< Code > code) [static]
Definition at line 361 of file builtins.cc.
                                                {
  return Builtins::IsBuiltinId(code->builtin_id());
}
References code(), and IsBuiltinId().
IsBuiltinHandle()
bool v8::internal::Builtins::IsBuiltinHandle (IndirectHandle< HeapObject > maybe_code, Builtin * index) const
Definition at line 365 of file builtins.cc.
                                                       {
  Address* handle_location = maybe_code.location();
  Address* builtins_table = isolate_->builtin_table();
  if (handle_location < builtins_table) return false;
  Address* builtins_table_end = &builtins_table[Builtins::kBuiltinCount];
  if (handle_location >= builtins_table_end) return false;
  *builtin = FromInt(static_cast<int>(handle_location - builtins_table));
  return true;
}
References FromInt(), kBuiltinCount, and v8::internal::HandleBase::location().
IsBuiltinId() [1/2]
static constexpr bool v8::internal::Builtins::IsBuiltinId (Builtin builtin) [inline], [static], [constexpr]
Definition at line 198 of file builtins.h.
                                                     {
    return builtin != Builtin::kNoBuiltinId;
  }
References v8::internal::kNoBuiltinId.
Referenced by v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::MacroAssemblerBase::BuiltinEntry(), v8::internal::IsolateData::BuiltinEntrySlotOffset(), v8::internal::anonymous_namespace{feedback-vector.cc}::BuiltinHasKeyedAccessStoreMode(), CheckFormalParameterCount(), v8::internal::compiler::CodeGenerator::FinalizeCode(), FromInt(), v8::internal::DebugEvaluate::FunctionGetSideEffectState(), v8::internal::Heap::GcSafeInstructionStreamContains(), v8::internal::Heap::GcSafeTryFindCodeForInnerPointer(), v8::internal::FeedbackNexus::GetKeyedAccessStoreMode(), v8::internal::SharedFunctionInfo::HasBuiltinId(), v8::internal::MacroAssemblerBase::IndirectLoadConstant(), InitializeIsolateDataTables(), v8::internal::EmbeddedData::InstructionEndOf(), v8::internal::EmbeddedData::InstructionSizeOf(), v8::internal::EmbeddedData::InstructionStartOf(), IsBuiltin(), IsIsolateIndependentBuiltin(), IsTier0(), KindOf(), Lookup(), v8::internal::EmbeddedData::MetadataStartOf(), name(), v8::internal::Factory::NewCodeObjectForEmbeddedBuiltin(), v8::internal::FactoryBase< Impl >::NewSharedFunctionInfo(), v8::internal::compiler::turboshaft::Pipeline::PrepareForInstructionSelection(), v8::internal::RELEASE_ACQUIRE_ACCESSORS(), v8::internal::compiler::BasicBlockCallGraphProfiler::StoreCallGraph(), v8::internal::Assembler::target_builtin_at(), ToInt(), and v8::internal::OffHeapInstructionStream::TryLookupCode().
IsBuiltinId() [2/2]
static constexpr bool v8::internal::Builtins::IsBuiltinId (int maybe_id) [inline], [static], [constexpr]
Definition at line 201 of file builtins.h.
                                                  {
    static_assert(static_cast<int>(Builtin::kNoBuiltinId) == -1);
    return static_cast<uint32_t>(maybe_id) <
           static_cast<uint32_t>(kBuiltinCount);
  }
References kBuiltinCount, and v8::internal::kNoBuiltinId.
IsCpp()
bool v8::internal::Builtins::IsCpp (Builtin builtin) [static]
Definition at line 505 of file builtins.cc.
                                    {
  return Builtins::KindOf(builtin) == CPP;
}
References CPP, and KindOf().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildCallCPPBuiltin(), CppEntryOf(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), and v8::internal::compiler::JSTypedLowering::ReduceJSCall().
IsIsolateIndependent()
static constexpr bool v8::internal::Builtins::IsIsolateIndependent (Builtin builtin) [inline], [static], [constexpr]
Definition at line 349 of file builtins.h.
                                                              {
    static_assert(kAllBuiltinsAreIsolateIndependent);
    return kAllBuiltinsAreIsolateIndependent;
  }
References kAllBuiltinsAreIsolateIndependent.
Referenced by v8::internal::RegExpMacroAssemblerRISCV::CallCheckStackGuardState(), v8::internal::Isolate::InitializeBuiltinJSDispatchTable(), IsIsolateIndependentBuiltin(), and v8::internal::SetupIsolateDelegate::ReplacePlaceholders().
IsIsolateIndependentBuiltin()
bool v8::internal::Builtins::IsIsolateIndependentBuiltin (Tagged< Code > code) [static]
Definition at line 377 of file builtins.cc.
                                                            {
  Builtin builtin = code->builtin_id();
  return Builtins::IsBuiltinId(builtin) &&
         Builtins::IsIsolateIndependent(builtin);
}
References code(), IsBuiltinId(), and IsIsolateIndependent().
Referenced by v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::Code::IsIsolateIndependent(), and v8::internal::Factory::NewCodeObjectForEmbeddedBuiltin().
IsJSEntryVariant()
constexpr bool v8::internal::Builtins::IsJSEntryVariant (Builtin builtin) [inline], [static], [constexpr]
Definition at line 253 of file builtins-inl.h.
                                                         {
  switch (builtin) {
    case Builtin::kJSEntry:
    case Builtin::kJSConstructEntry:
    case Builtin::kJSRunMicrotasksEntry:
      return true;
    default:
      return false;
  }
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler().
IsTier0()
static constexpr bool v8::internal::Builtins::IsTier0 (Builtin builtin) [inline], [static], [constexpr]
Definition at line 206 of file builtins.h.
                                                 {
    return builtin <= kLastTier0 && IsBuiltinId(builtin);
  }
References IsBuiltinId(), and kLastTier0.
Referenced by builtin_tier0_slot(), v8::internal::IsolateData::BuiltinEntrySlotOffset(), and v8::internal::IsolateData::BuiltinSlotOffset().
js_entry_handler_offset()
int v8::internal::Builtins::js_entry_handler_offset () const [inline]
Definition at line 394 of file builtins.h.
                                      {
    DCHECK_NE(js_entry_handler_offset_, 0);
    return js_entry_handler_offset_;
  }
References DCHECK_NE, and js_entry_handler_offset_.
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler().
jspi_prompt_handler_offset()
int v8::internal::Builtins::jspi_prompt_handler_offset () const [inline]
Definition at line 399 of file builtins.h.
                                         {
    DCHECK_NE(jspi_prompt_handler_offset_, 0);
    return jspi_prompt_handler_offset_;
  }
References DCHECK_NE, and jspi_prompt_handler_offset_.
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler().
KindNameOf()
const char * v8::internal::Builtins::KindNameOf (Builtin builtin) [static]
Definition at line 486 of file builtins.cc.
                                                {
  Kind kind = Builtins::KindOf(builtin);
  // clang-format off
  switch (kind) {
    case CPP: return "CPP";
    case TSJ: return "TSJ";
    case TFJ: return "TFJ";
    case TSC: return "TSC";
    case TFC: return "TFC";
    case TFS: return "TFS";
    case TFH: return "TFH";
    case BCH: return "BCH";
    case ASM: return "ASM";
  }
  // clang-format on
  UNREACHABLE();
}
References ASM, BCH, CPP, KindOf(), TFC, TFH, TFJ, TFS, TSC, TSJ, and v8::internal::UNREACHABLE().
Referenced by PrintBuiltinSize().
KindOf()
Builtins::Kind v8::internal::Builtins::KindOf (Builtin builtin) [static]
Definition at line 480 of file builtins.cc.
                                             {
  DCHECK(IsBuiltinId(builtin));
  return builtin_metadata[ToInt(builtin)].kind;
}
References v8::internal::anonymous_namespace{builtins.cc}::builtin_metadata, v8::internal::DCHECK(), IsBuiltinId(), v8::internal::anonymous_namespace{builtins.cc}::BuiltinMetadata::kind, and ToInt().
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler(), CallInterfaceDescriptorFor(), v8::internal::SharedFunctionInfo::DontAdaptArguments(), v8::internal::BuiltinsReducer< Next >::EmitBuiltinProlog(), EntrypointTagFor(), GetBuiltinFromBytecodeOffset(), GetContinuationBytecodeOffset(), GetFormalParameterCount(), GetStackParameterCount(), HasJSLinkage(), v8::internal::BuiltinsSorter::InitializeClusters(), IsCpp(), KindNameOf(), and SandboxingModeOf().
LoadGlobalIC()
constexpr Builtin v8::internal::Builtins::LoadGlobalIC (TypeofMode typeof_mode) [inline], [static], [constexpr]
Definition at line 146 of file builtins-inl.h.
                                                               {
  return typeof_mode == TypeofMode::kNotInside
             ? Builtin::kLoadGlobalICTrampoline
             : Builtin::kLoadGlobalICInsideTypeofTrampoline;
}
References v8::internal::kNotInside.
Referenced by v8::internal::CodeFactory::LoadGlobalIC().
LoadGlobalICInOptimizedCode()
constexpr Builtin v8::internal::Builtins::LoadGlobalICInOptimizedCode (TypeofMode typeof_mode) [inline], [static], [constexpr]
Definition at line 153 of file builtins-inl.h.
                            {
  return typeof_mode == TypeofMode::kNotInside
             ? Builtin::kLoadGlobalIC
             : Builtin::kLoadGlobalICInsideTypeof;
}
References v8::internal::kNotInside.
Referenced by v8::internal::AccessorAssembler::GenerateLoadGlobalICBaseline(), v8::internal::AccessorAssembler::GenerateLoadGlobalICTrampoline(), v8::internal::CodeFactory::LoadGlobalICInOptimizedCode(), and v8::internal::AccessorAssembler::LookupGlobalIC().
Lookup()
const char * v8::internal::Builtins::Lookup (Address pc)
Definition at line 114 of file builtins.cc.
                                       {
  // Off-heap pc's can be looked up through binary search.
  Builtin builtin = OffHeapInstructionStream::TryLookupCode(isolate_, pc);
  if (Builtins::IsBuiltinId(builtin)) return name(builtin);
  // May be called during initialization (disassembler).
  if (!initialized_) return nullptr;
  for (Builtin builtin_ix = Builtins::kFirst; builtin_ix <= Builtins::kLast;
       ++builtin_ix) {
    if (code(builtin_ix)->contains(isolate_, pc)) {
      return name(builtin_ix);
    }
  }
  return nullptr;
}
References code(), v8::base::contains(), initialized_, IsBuiltinId(), kFirst, kLast, name(), and v8::internal::OffHeapInstructionStream::TryLookupCode().
MarkInitialized()
void v8::internal::Builtins::MarkInitialized () [inline]
Definition at line 365 of file builtins.h.
                         {
    DCHECK(!initialized_);
    initialized_ = true;
  }
References v8::internal::DCHECK(), and initialized_.
Referenced by v8::internal::StartupDeserializer::DeserializeIntoIsolate(), and v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal().
name()
const char * v8::internal::Builtins::name (Builtin builtin) [static]
Definition at line 226 of file builtins.cc.
                                          {
  int index = ToInt(builtin);
  DCHECK(IsBuiltinId(index));
  return builtin_metadata[index].name;
}
References v8::internal::anonymous_namespace{builtins.cc}::builtin_metadata, v8::internal::DCHECK(), v8::internal::index, IsBuiltinId(), v8::internal::anonymous_namespace{builtins.cc}::BuiltinMetadata::name, and ToInt().
Referenced by v8::internal::anonymous_namespace{debug-evaluate.cc}::BuiltinGetSideEffectState(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallBuiltin(), v8::internal::MacroAssemblerBase::CommentForOffHeapTrampoline(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileBytecodeHandler(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::ComputeInitialGraphHash(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::SharedFunctionInfo::DontAdaptArguments(), EmitCodeCreateEvents(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateOutOfLineCode(), v8::internal::interpreter::Interpreter::Initialize(), v8::internal::BuiltinsSorter::InitializeCallGraph(), v8::internal::Heap::IterateBuiltins(), v8::internal::ExistingCodeLogger::LogCodeObject(), Lookup(), v8::internal::EmbeddedData::NewFromIsolate(), v8::internal::BuiltinExitFrame::Print(), PrintBuiltinCode(), PrintBuiltinSize(), v8::internal::maglev::CallBuiltin::PrintParams(), v8::internal::maglev::CallCPPBuiltin::PrintParams(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeShift(), v8::internal::compiler::anonymous_namespace{js-typed-lowering.cc}::ReduceBuiltin(), v8::internal::maglev::MaglevGraphBuilder::TryReduceBuiltin(), v8::internal::BuiltinsEffectsAnalyzer::Write(), and v8::internal::EmbeddedFileWriter::WriteBuiltin().
NameForStackTrace()
const char * v8::internal::Builtins::NameForStackTrace (Isolate * isolate, Builtin builtin) [static]
Definition at line 233 of file builtins.cc.
                                                                         {
#if V8_ENABLE_WEBASSEMBLY
  // Most builtins are never shown in stack traces. Those that are exposed
  // to JavaScript get their name from the object referring to them. Here
  // we only support a few internal builtins that have special reasons for
  // being shown on stack traces:
  // - builtins that are allowlisted in {StubFrame::Summarize}.
  // - builtins that throw the same error as one of those above, but would
  // lose information and e.g. print "indexOf" instead of "String.indexOf".
  switch (builtin) {
    case Builtin::kDataViewPrototypeGetBigInt64:
      return "DataView.prototype.getBigInt64";
    case Builtin::kDataViewPrototypeGetBigUint64:
      return "DataView.prototype.getBigUint64";
    case Builtin::kDataViewPrototypeGetFloat16:
      return "DataView.prototype.getFloat16";
    case Builtin::kDataViewPrototypeGetFloat32:
      return "DataView.prototype.getFloat32";
    case Builtin::kDataViewPrototypeGetFloat64:
      return "DataView.prototype.getFloat64";
    case Builtin::kDataViewPrototypeGetInt8:
      return "DataView.prototype.getInt8";
    case Builtin::kDataViewPrototypeGetInt16:
      return "DataView.prototype.getInt16";
    case Builtin::kDataViewPrototypeGetInt32:
      return "DataView.prototype.getInt32";
    case Builtin::kDataViewPrototypeGetUint8:
      return "DataView.prototype.getUint8";
    case Builtin::kDataViewPrototypeGetUint16:
      return "DataView.prototype.getUint16";
    case Builtin::kDataViewPrototypeGetUint32:
      return "DataView.prototype.getUint32";
    case Builtin::kDataViewPrototypeSetBigInt64:
      return "DataView.prototype.setBigInt64";
    case Builtin::kDataViewPrototypeSetBigUint64:
      return "DataView.prototype.setBigUint64";
    case Builtin::kDataViewPrototypeSetFloat16:
      return "DataView.prototype.setFloat16";
    case Builtin::kDataViewPrototypeSetFloat32:
      return "DataView.prototype.setFloat32";
    case Builtin::kDataViewPrototypeSetFloat64:
      return "DataView.prototype.setFloat64";
    case Builtin::kDataViewPrototypeSetInt8:
      return "DataView.prototype.setInt8";
    case Builtin::kDataViewPrototypeSetInt16:
      return "DataView.prototype.setInt16";
    case Builtin::kDataViewPrototypeSetInt32:
      return "DataView.prototype.setInt32";
    case Builtin::kDataViewPrototypeSetUint8:
      return "DataView.prototype.setUint8";
    case Builtin::kDataViewPrototypeSetUint16:
      return "DataView.prototype.setUint16";
    case Builtin::kDataViewPrototypeSetUint32:
      return "DataView.prototype.setUint32";
    case Builtin::kDataViewPrototypeGetByteLength:
      return "get DataView.prototype.byteLength";
    case Builtin::kThrowDataViewDetachedError:
    case Builtin::kThrowDataViewOutOfBounds:
    case Builtin::kThrowDataViewTypeError: {
      DataViewOp op = static_cast<DataViewOp>(isolate->error_message_param());
      return ToString(op);
    }
    case Builtin::kStringPrototypeToLocaleLowerCase:
      return "String.toLocaleLowerCase";
    case Builtin::kStringPrototypeIndexOf:
    case Builtin::kThrowIndexOfCalledOnNull:
      return "String.indexOf";
#if V8_INTL_SUPPORT
    case Builtin::kStringPrototypeToLowerCaseIntl:
#endif
    case Builtin::kThrowToLowerCaseCalledOnNull:
      return "String.toLowerCase";
    case Builtin::kWasmIntToString:
      return "Number.toString";
    default:
      // Callers getting this might well crash, which might be desirable
      // because it's similar to {UNREACHABLE()}, but contrary to that a
      // careful caller can also check the value and use it as an "is a
      // name available for this builtin?" check.
      return nullptr;
  }
#else
  return nullptr;
#endif // V8_ENABLE_WEBASSEMBLY
}
References v8::internal::Isolate::error_message_param(), and v8::internal::ToString().
Referenced by v8::internal::CallSiteInfo::GetFunctionName(), and v8::internal::StubFrame::Summarize().
NonPrimitiveToPrimitive()
constexpr Builtin v8::internal::Builtins::NonPrimitiveToPrimitive (ToPrimitiveHint hint = ToPrimitiveHint::kDefault) [inline], [static], [constexpr]
Definition at line 109 of file builtins-inl.h.
                                                                        {
  switch (hint) {
    case ToPrimitiveHint::kDefault:
      return Builtin::kNonPrimitiveToPrimitive_Default;
    case ToPrimitiveHint::kNumber:
      return Builtin::kNonPrimitiveToPrimitive_Number;
    case ToPrimitiveHint::kString:
      return Builtin::kNonPrimitiveToPrimitive_String;
  }
  UNREACHABLE();
}
References v8::internal::kDefault, v8::internal::kNumber, v8::internal::kString, and v8::internal::UNREACHABLE().
Referenced by v8::internal::CodeStubAssembler::NonNumberToNumberOrNumeric().
operator=()
Builtins& v8::internal::Builtins::operator= (const Builtins &) [delete]
OrdinaryToPrimitive()
constexpr Builtin v8::internal::Builtins::OrdinaryToPrimitive (OrdinaryToPrimitiveHint hint) [inline], [static], [constexpr]
Definition at line 122 of file builtins-inl.h.
                                                                            {
  switch (hint) {
    case OrdinaryToPrimitiveHint::kNumber:
      return Builtin::kOrdinaryToPrimitive_Number;
    case OrdinaryToPrimitiveHint::kString:
      return Builtin::kOrdinaryToPrimitive_String;
  }
  UNREACHABLE();
}
References v8::internal::kNumber, v8::internal::kString, and v8::internal::UNREACHABLE().
Referenced by v8::internal::CodeStubAssembler::OrdinaryToPrimitive(), and v8::internal::TF_BUILTIN().
PrintBuiltinCode()
void v8::internal::Builtins::PrintBuiltinCode ()
Definition at line 319 of file builtins.cc.
                                {
  DCHECK(v8_flags.print_builtin_code);
#ifdef ENABLE_DISASSEMBLER
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
       ++builtin) {
    const char* builtin_name = name(builtin);
    if (PassesFilter(base::CStrVector(builtin_name),
                     base::CStrVector(v8_flags.print_builtin_code_filter))) {
      CodeTracer::Scope trace_scope(isolate_->GetCodeTracer());
      OFStream os(trace_scope.file());
      Tagged<Code> builtin_code = code(builtin);
      builtin_code->Disassemble(builtin_name, os, isolate_);
      os << "\n";
    }
  }
#endif
}
References code(), v8::base::CStrVector(), v8::internal::DCHECK(), v8::internal::CodeTracer::Scope::file(), kFirst, kLast, name(), v8::internal::PassesFilter(), and v8::internal::v8_flags.
Referenced by v8::internal::Isolate::Init().
PrintBuiltinSize()
void v8::internal::Builtins::PrintBuiltinSize ()
Definition at line 337 of file builtins.cc.
                                {
  DCHECK(v8_flags.print_builtin_size);
  for (Builtin builtin = Builtins::kFirst; builtin <= Builtins::kLast;
       ++builtin) {
    const char* builtin_name = name(builtin);
    const char* kind = KindNameOf(builtin);
    Tagged<Code> code = Builtins::code(builtin);
    PrintF(stdout, "%s Builtin, %s, %d\n", kind, builtin_name,
           code->instruction_size());
  }
}
References code(), v8::internal::DCHECK(), kFirst, KindNameOf(), kLast, name(), v8::internal::PrintF(), and v8::internal::v8_flags.
Referenced by v8::internal::Isolate::Init().
RecordWrite()
constexpr Builtin v8::internal::Builtins::RecordWrite (SaveFPRegsMode fp_mode) [inline], [static], [constexpr]
Definition at line 17 of file builtins-inl.h.
                                                              {
  switch (fp_mode) {
    case SaveFPRegsMode::kIgnore:
      return Builtin::kRecordWriteIgnoreFP;
    case SaveFPRegsMode::kSave:
      return Builtin::kRecordWriteSaveFP;
  }
}
References v8::internal::kIgnore, and v8::internal::kSave.
Referenced by v8::internal::MacroAssembler::CallRecordWriteStub().
RuntimeCEntry()
constexpr Builtin v8::internal::Builtins::RuntimeCEntry (int result_size, bool switch_to_central_stack = false) [inline], [static], [constexpr]
Definition at line 194 of file builtins-inl.h.
                                                                        {
  return CEntry(result_size, ArgvMode::kStack, false, switch_to_central_stack);
}
References CEntry(), and v8::internal::kStack.
Referenced by v8::internal::MacroAssembler::CallRuntime(), v8::internal::compiler::CodeAssembler::CallRuntimeImpl(), and v8::internal::compiler::CodeAssembler::TailCallRuntimeImpl().
SandboxingModeOf()
CodeSandboxingMode v8::internal::Builtins::SandboxingModeOf (Builtin builtin) [static]
Definition at line 543 of file builtins.cc.
                                                             {
  Kind kind = Builtins::KindOf(builtin);
  switch (kind) {
    case CPP:
      // CPP builtins are invoked in sandboxed execution mode, but the CEntry
      // trampoline will exit sandboxed mode before calling the actual C++ code.
      // TODO(422994386): investigate running the C++ code in sandboxed mode.
      return CodeSandboxingMode::kSandboxed;
    case TSJ:
    case TFJ:
      // All builtins with JS linkage run sandboxed.
      return CodeSandboxingMode::kSandboxed;
    case TFH:
    case BCH:
      // Bytecode handlers and inline caches run sandboxed.
      return CodeSandboxingMode::kSandboxed;
    case TFS:
      return CodeSandboxingMode::kSandboxed;
    case TSC:
    case TFC:
    case ASM:
      return CallInterfaceDescriptorFor(builtin).sandboxing_mode();
  }
}
References ASM, BCH, CallInterfaceDescriptorFor(), CPP, KindOf(), v8::internal::kSandboxed, v8::internal::CallInterfaceDescriptor::sandboxing_mode(), TFC, TFH, TFJ, TFS, TSC, and TSJ.
Referenced by v8::internal::Code::sandboxing_mode(), and v8::internal::MacroAssemblerBase::set_builtin().
set_code()
void v8::internal::Builtins::set_code (Builtin builtin, Tagged< Code > code)
Definition at line 142 of file builtins.cc.
                                                          {
  DCHECK_EQ(builtin, code->builtin_id());
  DCHECK(Internals::HasHeapObjectTag(code.ptr()));
  // The given builtin may be uninitialized thus we cannot check its type here.
  isolate_->builtin_table()[Builtins::ToInt(builtin)] = code.ptr();
}
References code(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Internals::HasHeapObjectTag(), and ToInt().
Referenced by v8::internal::SetupIsolateDelegate::AddBuiltin(), and v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects().
SetJSEntryHandlerOffset()
void v8::internal::Builtins::SetJSEntryHandlerOffset (int offset) [inline]
Definition at line 404 of file builtins.h.
                                           {
    // Check the stored offset is either uninitialized or unchanged (we
    // generate multiple variants of this builtin but they should all have the
    // same handler offset).
    CHECK(js_entry_handler_offset_ == 0 || js_entry_handler_offset_ == offset);
    js_entry_handler_offset_ = offset;
  }
References CHECK, and js_entry_handler_offset_.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_JSEntryVariant().
SetJSPIPromptHandlerOffset()
void v8::internal::Builtins::SetJSPIPromptHandlerOffset (int offset) [inline]
Definition at line 412 of file builtins.h.
                                              {
    CHECK_EQ(jspi_prompt_handler_offset_, 0);
    jspi_prompt_handler_offset_ = offset;
  }
References CHECK_EQ, and jspi_prompt_handler_offset_.
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::GenerateExceptionHandlingLandingPad().
StringAdd()
constexpr Builtin v8::internal::Builtins::StringAdd (StringAddFlags flags = STRING_ADD_CHECK_NONE) [inline], [static], [constexpr]
Definition at line 133 of file builtins-inl.h.
                                                          {
  switch (flags) {
    case STRING_ADD_CHECK_NONE:
      return Builtin::kStringAdd_CheckNone;
    case STRING_ADD_CONVERT_LEFT:
      return Builtin::kStringAddConvertLeft;
    case STRING_ADD_CONVERT_RIGHT:
      return Builtin::kStringAddConvertRight;
  }
  UNREACHABLE();
}
References v8::internal::flags, v8::internal::STRING_ADD_CHECK_NONE, v8::internal::STRING_ADD_CONVERT_LEFT, v8::internal::STRING_ADD_CONVERT_RIGHT, and v8::internal::UNREACHABLE().
Referenced by v8::internal::ObjectBuiltinsAssembler::ReturnToStringFormat(), and v8::internal::CodeFactory::StringAdd().
TearDown()
void v8::internal::Builtins::TearDown ()
Definition at line 112 of file builtins.cc.
{ initialized_ = false; }
References initialized_.
Referenced by v8::internal::Isolate::Deinit().
ToInt()
static constexpr int v8::internal::Builtins::ToInt (Builtin id) [inline], [static], [constexpr]
Definition at line 214 of file builtins.h.
                                         {
    DCHECK(IsBuiltinId(id));
    return static_cast<int>(id);
  }
References v8::internal::DCHECK(), and IsBuiltinId().
Referenced by builtin_slot(), builtin_tier0_slot(), v8::internal::IsolateData::BuiltinEntrySlotOffset(), v8::internal::IsolateData::BuiltinSlotOffset(), code(), code_handle(), CppEntryOf(), EmitCodeCreateEvents(), EntryOf(), GetBuiltinFromBytecodeOffset(), GetContinuationBytecodeOffset(), GetStackParameterCount(), InitializeIsolateDataTables(), KindOf(), v8::internal::MacroAssembler::MacroAssemblerBase(), name(), set_code(), and v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal().
Friends And Related Function Documentation
SetupIsolateDelegate
friend class SetupIsolateDelegate [friend]
Definition at line 518 of file builtins.h.
Member Data Documentation
initialized_
bool v8::internal::Builtins::initialized_ = false [private]
Definition at line 500 of file builtins.h.
Referenced by is_initialized(), Lookup(), MarkInitialized(), v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal(), and TearDown().
js_entry_handler_offset_
int v8::internal::Builtins::js_entry_handler_offset_ = 0 [private]
Definition at line 505 of file builtins.h.
Referenced by js_entry_handler_offset(), and SetJSEntryHandlerOffset().
jspi_prompt_handler_offset_
int v8::internal::Builtins::jspi_prompt_handler_offset_ = 0 [private]
Definition at line 516 of file builtins.h.
Referenced by jspi_prompt_handler_offset(), and SetJSPIPromptHandlerOffset().
kAllBuiltinsAreIsolateIndependent
constexpr bool v8::internal::Builtins::kAllBuiltinsAreIsolateIndependent = true [static], [constexpr]
Definition at line 345 of file builtins.h.
Referenced by v8::internal::wasm::NativeModule::AddCodeSpaceLocked(), AllBuiltinsAreIsolateIndependent(), EmbeddedEntryOf(), v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects(), v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::wasm::WasmImportWrapperCache::Get(), IsIsolateIndependent(), v8::internal::EmbeddedData::NewFromIsolate(), v8::internal::EmbeddedData::PrintStatistics(), and v8::internal::EmbeddedFileWriter::WriteCodeSection().
kBuiltinCount
constexpr int v8::internal::Builtins::kBuiltinCount [static], [constexpr]
Initial value:
=
      0 BUILTIN_LIST(ADD_ONE, ADD_ONE, ADD_ONE, ADD_ONE, ADD_ONE, ADD_ONE,
                     ADD_ONE, ADD_ONE, ADD_ONE)
Definition at line 112 of file builtins.h.
Referenced by EmitCodeCreateEvents(), IsBuiltinHandle(), IsBuiltinId(), v8::internal::Isolate::IsBuiltinTableHandleLocation(), v8::internal::CodeStubAssembler::LoadBuiltin(), v8::internal::EmbeddedData::NewFromIsolate(), v8::internal::EmbeddedData::PrintStatistics(), v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal(), v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::Verify(), and v8::internal::EmbeddedFileWriter::WriteCodeSection().
kBuiltinTier0Count
constexpr int v8::internal::Builtins::kBuiltinTier0Count [static], [constexpr]
Initial value:
= 0 BUILTIN_LIST_TIER0(
      ADD_ONE, ADD_ONE, ADD_ONE, ADD_ONE, ADD_ONE, ADD_ONE, ADD_ONE)
Definition at line 115 of file builtins.h.
Referenced by v8::internal::Isolate::CheckIsolateLayout().
kBytecodeHandlersAreSortedLast
constexpr bool v8::internal::Builtins::kBytecodeHandlersAreSortedLast [static], [constexpr]
Initial value:
=
      kLastBytecodeHandlerPlusOne == kBuiltinCount
Definition at line 131 of file builtins.h.
Referenced by v8::internal::EmbeddedData::InstructionEndOfBytecodeHandlers().
kCodeObjectsAreInROSpace
constexpr bool v8::internal::Builtins::kCodeObjectsAreInROSpace = true [static], [constexpr]
Definition at line 105 of file builtins.h.
Referenced by v8::internal::anonymous_namespace{read-only-promotion.cc}::Committee::GetPromoRecommendationCode(), v8::internal::Heap::IterateRoots(), and v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::Verify().
kFirst
constexpr Builtin v8::internal::Builtins::kFirst = static_cast<Builtin>(0) [static], [constexpr]
Definition at line 119 of file builtins.h.
Referenced by v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects(), v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::Isolate::HashIsolateForEmbeddedBlob(), v8::internal::BuiltinsSorter::InitializeCallGraph(), InitializeIsolateDataTables(), v8::internal::Heap::IterateBuiltins(), v8::internal::ProfilerCodeObserver::LogBuiltins(), Lookup(), v8::internal::EmbeddedData::NewFromIsolate(), v8::internal::SetupIsolateDelegate::PopulateWithPlaceholders(), v8::internal::EmbeddedFileWriter::PrepareBuiltinSourcePositionMap(), PrintBuiltinCode(), PrintBuiltinSize(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal(), and v8::internal::BuiltinsSorter::SortBuiltins().
kFirstExtraWideBytecodeHandler
constexpr int v8::internal::Builtins::kFirstExtraWideBytecodeHandler [static], [constexpr]
Initial value:
=
      kFirstWideBytecodeHandler + kNumberOfWideBytecodeHandlers
Definition at line 127 of file builtins.h.
kFirstWideBytecodeHandler
constexpr int v8::internal::Builtins::kFirstWideBytecodeHandler [static], [constexpr]
Initial value:
=
      static_cast<int>(Builtin::kFirstBytecodeHandler) +
      kNumberOfBytecodeHandlers
Definition at line 124 of file builtins.h.
kLast
constexpr Builtin v8::internal::Builtins::kLast = static_cast<Builtin>(kBuiltinCount - 1) [static], [constexpr]
Definition at line 120 of file builtins.h.
Referenced by v8::internal::anonymous_namespace{isolate.cc}::FinalizeBuiltinCodeObjects(), v8::internal::anonymous_namespace{embedded-data.cc}::FinalizeEmbeddedCodeTargets(), v8::internal::Isolate::HashIsolateForEmbeddedBlob(), v8::internal::BuiltinsSorter::InitializeCallGraph(), InitializeIsolateDataTables(), v8::internal::Heap::IterateBuiltins(), v8::internal::ProfilerCodeObserver::LogBuiltins(), Lookup(), v8::internal::EmbeddedData::NewFromIsolate(), v8::internal::SetupIsolateDelegate::PopulateWithPlaceholders(), v8::internal::EmbeddedFileWriter::PrepareBuiltinSourcePositionMap(), PrintBuiltinCode(), PrintBuiltinSize(), v8::internal::SetupIsolateDelegate::ReplacePlaceholders(), v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal(), and v8::internal::BuiltinsSorter::SortBuiltins().
kLastBytecodeHandlerPlusOne
constexpr int v8::internal::Builtins::kLastBytecodeHandlerPlusOne [static], [constexpr]
Initial value:
=
      kFirstExtraWideBytecodeHandler + kNumberOfWideBytecodeHandlers
Definition at line 129 of file builtins.h.
Referenced by EmitCodeCreateEvents().
kLastTier0
constexpr Builtin v8::internal::Builtins::kLastTier0 [static], [constexpr]
Initial value:
=
      static_cast<Builtin>(kBuiltinTier0Count - 1)
Definition at line 121 of file builtins.h.
Referenced by InitializeIsolateDataTables(), IsTier0(), and v8::internal::Heap::IterateBuiltins().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins.h
/mnt/V8SourceCode/src/builtins/builtins-api.cc
/mnt/V8SourceCode/src/builtins/builtins-inl.h
/mnt/V8SourceCode/src/builtins/builtins-internal-gen.cc
/mnt/V8SourceCode/src/builtins/builtins-interpreter-gen.cc
/mnt/V8SourceCode/src/builtins/builtins.cc
/mnt/V8SourceCode/src/builtins/riscv/builtins-riscv.cc