v8::internal::torque::ParameterDifference Class Reference
#include <parameter-difference.h>
Public Member Functions
ParameterDifference (const TypeVector &to, const TypeVector &from)
bool StrictlyBetterThan (const ParameterDifference &other) const
Private Member Functions
void AddParameter (const Type *to, const Type *from)
Private Attributes
std::vector< std::optional< const Type * > > difference_
Detailed Description
Definition at line 15 of file parameter-difference.h.
Constructor & Destructor Documentation
ParameterDifference()
v8::internal::torque::ParameterDifference::ParameterDifference (const TypeVector & to, const TypeVector & from) [inline]
Definition at line 17 of file parameter-difference.h.
                                                                    {
    DCHECK_EQ(to.size(), from.size());
    for (size_t i = 0; i < to.size(); ++i) {
      AddParameter(to[i], from[i]);
    }
  }
References AddParameter(), DCHECK_EQ, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Member Function Documentation
AddParameter()
void v8::internal::torque::ParameterDifference::AddParameter (const Type * to, const Type * from) [inline], [private]
Definition at line 61 of file parameter-difference.h.
                                                      {
    if (from->IsSubtypeOf(to)) {
      difference_.push_back(to);
    } else if (IsAssignableFrom(to, from)) {
      difference_.push_back(std::nullopt);
    } else {
      UNREACHABLE();
    }
  }
References difference_, v8::internal::torque::IsAssignableFrom(), v8::internal::torque::Type::IsSubtypeOf(), and v8::internal::UNREACHABLE().
Referenced by ParameterDifference().
StrictlyBetterThan()
bool v8::internal::torque::ParameterDifference::StrictlyBetterThan (const ParameterDifference & other) const [inline]
Definition at line 35 of file parameter-difference.h.
                                                                  {
    DCHECK_EQ(difference_.size(), other.difference_.size());
    bool better_parameter_found = false;
    for (size_t i = 0; i < difference_.size(); ++i) {
      std::optional<const Type*> a = difference_[i];
      std::optional<const Type*> b = other.difference_[i];
      if (a == b) {
        continue;
      } else if (a && b && a != b && (*a)->IsSubtypeOf(*b)) {
        DCHECK(!(*b)->IsSubtypeOf(*a));
        better_parameter_found = true;
      } else if (a && !b) {
        better_parameter_found = true;
      } else {
        return false;
      }
    }
    return better_parameter_found;
  }
References v8::internal::DCHECK(), DCHECK_EQ, difference_, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::torque::ImplementationVisitor::LookupCallable().
Member Data Documentation
difference_
std::vector<std::optional<const Type*> > v8::internal::torque::ParameterDifference::difference_ [private]
Definition at line 59 of file parameter-difference.h.
Referenced by AddParameter(), and StrictlyBetterThan().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/torque/parameter-difference.h