v8::internal::AutoAccessorInfo Class Reference
#include <ast.h>
Public Member Functions
FunctionLiteral * generated_getter () const
FunctionLiteral * generated_setter () const
VariableProxy * accessor_storage_name_proxy () const
VariableProxy * property_private_name_proxy () const
void set_property_private_name_proxy (VariableProxy *property_private_name_proxy)
Private Member Functions
AutoAccessorInfo (FunctionLiteral *generated_getter, FunctionLiteral *generated_setter, VariableProxy *accessor_storage_name_proxy)
Private Attributes
friend Zone
FunctionLiteral * generated_getter_
FunctionLiteral * generated_setter_
VariableProxy * accessor_storage_name_proxy_
VariableProxy * property_private_name_proxy_
Friends
class AstNodeFactory
Detailed Description
Definition at line 2499 of file ast.h.
Constructor & Destructor Documentation
AutoAccessorInfo()
v8::internal::AutoAccessorInfo::AutoAccessorInfo (FunctionLiteral * generated_getter, FunctionLiteral * generated_setter, VariableProxy * accessor_storage_name_proxy) [inline], [private]
Definition at line 2523 of file ast.h.
      : generated_getter_(generated_getter),
        generated_setter_(generated_setter),
        accessor_storage_name_proxy_(accessor_storage_name_proxy),
        property_private_name_proxy_(nullptr) {}
Member Function Documentation
accessor_storage_name_proxy()
VariableProxy* v8::internal::AutoAccessorInfo::accessor_storage_name_proxy () const [inline]
Definition at line 2503 of file ast.h.
                                                     {
    DCHECK_NOT_NULL(accessor_storage_name_proxy_);
    return accessor_storage_name_proxy_;
  }
References accessor_storage_name_proxy_, and DCHECK_NOT_NULL.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::interpreter::BytecodeGenerator::BuildClassProperty().
generated_getter()
FunctionLiteral* v8::internal::AutoAccessorInfo::generated_getter () const [inline]
Definition at line 2501 of file ast.h.
{ return generated_getter_; }
References generated_getter_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral().
generated_setter()
FunctionLiteral* v8::internal::AutoAccessorInfo::generated_setter () const [inline]
Definition at line 2502 of file ast.h.
{ return generated_setter_; }
References generated_setter_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral().
property_private_name_proxy()
VariableProxy* v8::internal::AutoAccessorInfo::property_private_name_proxy () const [inline]
Definition at line 2507 of file ast.h.
                                                     {
    DCHECK_NOT_NULL(property_private_name_proxy_);
    return property_private_name_proxy_;
  }
References DCHECK_NOT_NULL, and property_private_name_proxy_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and set_property_private_name_proxy().
set_property_private_name_proxy()
void v8::internal::AutoAccessorInfo::set_property_private_name_proxy (VariableProxy * property_private_name_proxy) [inline]
Definition at line 2512 of file ast.h.
                                                  {
    DCHECK_NULL(property_private_name_proxy_);
    DCHECK_NOT_NULL(property_private_name_proxy);
    property_private_name_proxy_ = property_private_name_proxy;
  }
References DCHECK_NOT_NULL, DCHECK_NULL, property_private_name_proxy(), and property_private_name_proxy_.
Referenced by v8::internal::ClassLiteralProperty::SetPrivateNameProxy().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 2520 of file ast.h.
Member Data Documentation
accessor_storage_name_proxy_
VariableProxy* v8::internal::AutoAccessorInfo::accessor_storage_name_proxy_ [private]
Definition at line 2535 of file ast.h.
Referenced by accessor_storage_name_proxy().
generated_getter_
FunctionLiteral* v8::internal::AutoAccessorInfo::generated_getter_ [private]
Definition at line 2531 of file ast.h.
Referenced by generated_getter().
generated_setter_
FunctionLiteral* v8::internal::AutoAccessorInfo::generated_setter_ [private]
Definition at line 2532 of file ast.h.
Referenced by generated_setter().
property_private_name_proxy_
VariableProxy* v8::internal::AutoAccessorInfo::property_private_name_proxy_ [private]
Definition at line 2538 of file ast.h.
Referenced by property_private_name_proxy(), and set_property_private_name_proxy().
Zone
friend v8::internal::AutoAccessorInfo::Zone [private]
Definition at line 2521 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h