v8::platform::tracing::JSONTraceWriter Class Reference
#include <trace-writer.h>
Public Member Functions
JSONTraceWriter (std::ostream &stream)
JSONTraceWriter (std::ostream &stream, const std::string &tag)
~JSONTraceWriter () override
void AppendTraceEvent (TraceObject *trace_event) override
void Flush () override
Private Member Functions
void AppendArgValue (uint8_t type, TraceObject::ArgValue value)
void AppendArgValue (v8::ConvertableToTraceFormat *)
Private Attributes
std::ostream & stream_
bool append_comma_ = false
Additional Inherited Members
Detailed Description
Definition at line 16 of file trace-writer.h.
Constructor & Destructor Documentation
JSONTraceWriter() [1/2]
v8::platform::tracing::JSONTraceWriter::JSONTraceWriter (std::ostream & stream) [explicit]
Definition at line 125 of file trace-writer.cc.
    : JSONTraceWriter(stream, "traceEvents") {}
JSONTraceWriter() [2/2]
v8::platform::tracing::JSONTraceWriter::JSONTraceWriter (std::ostream & stream, const std::string & tag)
Definition at line 128 of file trace-writer.cc.
    : stream_(stream) {
  stream_ << "{\"" << tag << "\":[";
}
References stream_.
 JSONTraceWriter()
v8::platform::tracing::JSONTraceWriter::~JSONTraceWriter () [override]
Definition at line 133 of file trace-writer.cc.
{ stream_ << "]}"; }
References stream_.
Member Function Documentation
AppendArgValue() [1/2]
void v8::platform::tracing::JSONTraceWriter::AppendArgValue (uint8_t type, TraceObject::ArgValue value) [private]
Definition at line 62 of file trace-writer.cc.
                                                                {
  switch (type) {
    case TRACE_VALUE_TYPE_BOOL:
      stream_ << (value.as_uint ? "true" : "false");
      break;
    case TRACE_VALUE_TYPE_UINT:
      stream_ << value.as_uint;
      break;
    case TRACE_VALUE_TYPE_INT:
      stream_ << value.as_int;
      break;
    case TRACE_VALUE_TYPE_DOUBLE: {
      std::string real;
      double val = value.as_double;
      if (std::isfinite(val)) {
        std::ostringstream convert_stream;
        convert_stream << val;
        real = convert_stream.str();
        // Ensure that the number has a .0 if there's no decimal or 'e'. This
        // makes sure that when we read the JSON back, it's interpreted as a
        // real rather than an int.
        if (real.find('.') == std::string::npos &&
            real.find('e') == std::string::npos &&
            real.find('E') == std::string::npos) {
          real += ".0";
        }
      } else if (std::isnan(val)) {
        // The JSON spec doesn't allow NaN and Infinity (since these are
        // objects in ECMAScript). Use strings instead.
        real = "\"NaN\"";
      } else if (val < 0) {
        real = "\"-Infinity\"";
      } else {
        real = "\"Infinity\"";
      }
      stream_ << real;
      break;
    }
    case TRACE_VALUE_TYPE_POINTER:
      // JSON only supports double and int numbers.
      // So as not to lose bits from a 64-bit pointer, output as a hex string.
      stream_ << "\"" << value.as_pointer << "\"";
      break;
    case TRACE_VALUE_TYPE_STRING:
    case TRACE_VALUE_TYPE_COPY_STRING:
      if (value.as_string == nullptr) {
        stream_ << "\"nullptr\"";
      } else {
        WriteJSONStringToStream(value.as_string, stream_);
      }
      break;
    default:
      UNREACHABLE();
  }
}
References stream_, v8::internal::string, TRACE_VALUE_TYPE_BOOL, TRACE_VALUE_TYPE_COPY_STRING, TRACE_VALUE_TYPE_DOUBLE, TRACE_VALUE_TYPE_INT, TRACE_VALUE_TYPE_POINTER, TRACE_VALUE_TYPE_STRING, TRACE_VALUE_TYPE_UINT, v8::internal::tracing::type, UNREACHABLE, v8::internal::value, and v8::platform::tracing::WriteJSONStringToStream().
Referenced by AppendTraceEvent().
AppendArgValue() [2/2]
void v8::platform::tracing::JSONTraceWriter::AppendArgValue (v8::ConvertableToTraceFormat * value) [private]
Definition at line 119 of file trace-writer.cc.
                                                                    {
  std::string arg_stringified;
  value->AppendAsTraceFormat(&arg_stringified);
  stream_ << arg_stringified;
}
References stream_, v8::internal::string, and v8::internal::value.
AppendTraceEvent()
void v8::platform::tracing::JSONTraceWriter::AppendTraceEvent (TraceObject * trace_event) [override], [virtual]
Implements v8::platform::tracing::TraceWriter.
Definition at line 135 of file trace-writer.cc.
                                                               {
  if (append_comma_) stream_ << ",";
  append_comma_ = true;
  stream_ << "{\"pid\":" << trace_event->pid()
          << ",\"tid\":" << trace_event->tid()
          << ",\"ts\":" << trace_event->ts()
          << ",\"tts\":" << trace_event->tts() << ",\"ph\":\""
          << trace_event->phase() << "\",\"cat\":\""
          << TracingController::GetCategoryGroupName(
                 trace_event->category_enabled_flag())
          << "\",\"name\":\"" << trace_event->name()
          << "\",\"dur\":" << trace_event->duration()
          << ",\"tdur\":" << trace_event->cpu_duration();
  if (trace_event->flags() &
      (TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT)) {
    stream_ << ",\"bind_id\":\"0x" << std::hex << trace_event->bind_id() << "\""
            << std::dec;
    if (trace_event->flags() & TRACE_EVENT_FLAG_FLOW_IN) {
      stream_ << ",\"flow_in\":true";
    }
    if (trace_event->flags() & TRACE_EVENT_FLAG_FLOW_OUT) {
      stream_ << ",\"flow_out\":true";
    }
  }
  if (trace_event->flags() & TRACE_EVENT_FLAG_HAS_ID) {
    if (trace_event->scope() != nullptr) {
      stream_ << ",\"scope\":\"" << trace_event->scope() << "\"";
    }
    // So as not to lose bits from a 64-bit integer, output as a hex string.
    stream_ << ",\"id\":\"0x" << std::hex << trace_event->id() << "\""
            << std::dec;
  }
  stream_ << ",\"args\":{";
  const char** arg_names = trace_event->arg_names();
  const uint8_t* arg_types = trace_event->arg_types();
  TraceObject::ArgValue* arg_values = trace_event->arg_values();
  std::unique_ptr<v8::ConvertableToTraceFormat>* arg_convertables =
      trace_event->arg_convertables();
  for (int i = 0; i < trace_event->num_args(); ++i) {
    if (i > 0) stream_ << ",";
    stream_ << "\"" << arg_names[i] << "\":";
    if (arg_types[i] == TRACE_VALUE_TYPE_CONVERTABLE) {
      AppendArgValue(arg_convertables[i].get());
    } else {
      AppendArgValue(arg_types[i], arg_values[i]);
    }
  }
  stream_ << "}}";
  // TODO(fmeawad): Add support for Flow Events.
}
References append_comma_, AppendArgValue(), v8::platform::tracing::TraceObject::arg_convertables(), v8::platform::tracing::TraceObject::arg_names(), v8::platform::tracing::TraceObject::arg_types(), v8::platform::tracing::TraceObject::arg_values(), v8::platform::tracing::TraceObject::bind_id(), v8::platform::tracing::TraceObject::category_enabled_flag(), v8::platform::tracing::TraceObject::cpu_duration(), v8::platform::tracing::TraceObject::duration(), v8::platform::tracing::TraceObject::flags(), v8::platform::tracing::TracingController::GetCategoryGroupName(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::platform::tracing::TraceObject::id(), v8::platform::tracing::TraceObject::name(), v8::platform::tracing::TraceObject::num_args(), v8::platform::tracing::TraceObject::phase(), v8::platform::tracing::TraceObject::pid(), v8::platform::tracing::TraceObject::scope(), stream_, v8::platform::tracing::TraceObject::tid(), TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_EVENT_FLAG_HAS_ID, TRACE_VALUE_TYPE_CONVERTABLE, v8::platform::tracing::TraceObject::ts(), and v8::platform::tracing::TraceObject::tts().
Flush()
void v8::platform::tracing::JSONTraceWriter::Flush () [override], [virtual]
Implements v8::platform::tracing::TraceWriter.
Definition at line 186 of file trace-writer.cc.
{}
Member Data Documentation
append_comma_
bool v8::platform::tracing::JSONTraceWriter::append_comma_ = false [private]
Definition at line 29 of file trace-writer.h.
Referenced by AppendTraceEvent().
stream_
std::ostream& v8::platform::tracing::JSONTraceWriter::stream_ [private]
Definition at line 28 of file trace-writer.h.
Referenced by AppendArgValue(), AppendTraceEvent(), JSONTraceWriter(), and ~JSONTraceWriter().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/libplatform/tracing/trace-writer.h
/mnt/V8SourceCode/src/libplatform/tracing/trace-writer.cc