v8::internal::LocalFactory Class Reference
#include <local-factory.h>
Public Member Functions
LocalFactory (Isolate *isolate)
ReadOnlyRoots read_only_roots () const
DirectHandle< Object > NewInvalidStringLengthError ()
DirectHandle< Object > NewRangeError (MessageTemplate template_index)
Private Member Functions
Tagged< HeapObject > AllocateRaw (int size, AllocationType allocation, AllocationAlignment alignment=kTaggedAligned, AllocationHint hint=AllocationHint())
LocalIsolate * isolate ()
bool CanAllocateInReadOnlySpace ()
bool EmptyStringRootIsInitialized ()
AllocationType AllocationTypeForInPlaceInternalizableString ()
void ProcessNewScript (DirectHandle< Script > script, ScriptEventType script_event_type)
Private Attributes
ReadOnlyRoots roots_
Friends
class FactoryBase< LocalFactory >
Additional Inherited Members
Detailed Description
Definition at line 25 of file local-factory.h.
Constructor & Destructor Documentation
LocalFactory()
v8::internal::LocalFactory::LocalFactory (Isolate * isolate) [explicit]
Definition at line 24 of file local-factory.cc.
: roots_(isolate) {}
Member Function Documentation
AllocateRaw()
Tagged< HeapObject > v8::internal::LocalFactory::AllocateRaw (int size, AllocationType allocation, AllocationAlignment alignment = kTaggedAligned, AllocationHint hint = AllocationHint()) [private]
Definition at line 48 of file local-factory.cc.
                                                                  {
  DCHECK(allocation == AllocationType::kOld ||
         allocation == AllocationType::kSharedOld ||
         allocation == AllocationType::kTrusted);
  return HeapObject::FromAddress(isolate()->heap()->AllocateRawOrFail(
      size, allocation, AllocationOrigin::kRuntime, alignment, hint));
}
References v8::internal::DCHECK(), v8::internal::HeapObject::FromAddress(), heap(), isolate(), v8::internal::kOld, v8::internal::kRuntime, v8::internal::kSharedOld, v8::internal::kTrusted, and size().
AllocationTypeForInPlaceInternalizableString()
AllocationType v8::internal::LocalFactory::AllocationTypeForInPlaceInternalizableString () [inline], [private]
Definition at line 25 of file local-factory-inl.h.
                                                                          {
  return isolate()
      ->heap()
      ->AsHeap()
      ->allocation_type_for_in_place_internalizable_strings();
}
References v8::internal::Heap::allocation_type_for_in_place_internalizable_strings(), v8::internal::LocalHeap::AsHeap(), v8::internal::LocalIsolate::heap(), and isolate().
CanAllocateInReadOnlySpace()
bool v8::internal::LocalFactory::CanAllocateInReadOnlySpace () [inline], [private]
Definition at line 63 of file local-factory.h.
{ return false; }
EmptyStringRootIsInitialized()
bool v8::internal::LocalFactory::EmptyStringRootIsInitialized () [inline], [private]
Definition at line 64 of file local-factory.h.
{ return true; }
isolate()
LocalIsolate* v8::internal::LocalFactory::isolate () [inline], [private]
Definition at line 55 of file local-factory.h.
                          {
    // Downcast to the privately inherited sub-class using c-style casts to
    // avoid undefined behavior (as static_cast cannot cast across private
    // bases).
    // NOLINTNEXTLINE (google-readability-casting)
    return (LocalIsolate*)this; // NOLINT(readability/casting)
  }
Referenced by AllocateRaw(), AllocationTypeForInPlaceInternalizableString(), v8::internal::HiddenLocalFactory::LocalFactory(), and v8::internal::LocalIsolate::LocalIsolate().
NewInvalidStringLengthError()
DirectHandle<Object> v8::internal::LocalFactory::NewInvalidStringLengthError () [inline]
Definition at line 41 of file local-factory.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
NewRangeError()
DirectHandle<Object> v8::internal::LocalFactory::NewRangeError (MessageTemplate template_index) [inline]
Definition at line 42 of file local-factory.h.
                                                                     {
    UNREACHABLE();
  }
ProcessNewScript()
void v8::internal::LocalFactory::ProcessNewScript (DirectHandle< Script > script, ScriptEventType script_event_type) [private]
Definition at line 26 of file local-factory.cc.
                                                                       {
  // TODO(leszeks): Actually add the script to the main Isolate's script list,
  // in a thread-safe way.
  //
  // At the moment, we have to do one final fix-up during off-thread
  // finalization, where we add the created script to the script list, but this
  // relies on there being exactly one script created during the lifetime of
  // this LocalFactory.
  //
  // For now, prevent accidentally creating more scripts that don't get added to
  // the script list with a simple DCHECK.
  int script_id = script->id();
#ifdef DEBUG
  if (script_id != Script::kTemporaryScriptId) {
    DCHECK(!a_script_was_added_to_the_script_list_);
    a_script_was_added_to_the_script_list_ = true;
  }
#endif
  LOG(isolate(), ScriptEvent(script_event_type, script_id));
}
read_only_roots()
ReadOnlyRoots v8::internal::LocalFactory::read_only_roots () const [inline]
Definition at line 29 of file local-factory.h.
{ return roots_; }
Friends And Related Function Documentation
FactoryBase< LocalFactory >
friend class FactoryBase< LocalFactory > [friend]
Definition at line 42 of file local-factory.h.
Member Data Documentation
roots_
ReadOnlyRoots v8::internal::LocalFactory::roots_ [private]
Definition at line 72 of file local-factory.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/local-factory.h
/mnt/V8SourceCode/src/heap/local-factory-inl.h
/mnt/V8SourceCode/src/heap/local-factory.cc