v8::internal::WeakCell Class Reference
#include <js-weak-refs.h>
Classes
class BodyDescriptor
Public Member Functions
Tagged< HeapObject > relaxed_target () const
Tagged< HeapObject > relaxed_unregister_token () const
template<typename GCNotifyUpdatedSlotCallback >
void Nullify (Isolate *isolate, GCNotifyUpdatedSlotCallback gc_notify_updated_slot)
void RemoveFromFinalizationRegistryCells (Isolate *isolate)
Detailed Description
Definition at line 85 of file js-weak-refs.h.
Member Function Documentation
Nullify()
template<typename GCNotifyUpdatedSlotCallback >
void v8::internal::WeakCell::Nullify (Isolate * isolate, GCNotifyUpdatedSlotCallback gc_notify_updated_slot) [inline]
Definition at line 170 of file js-weak-refs-inl.h.
                                                                           {
  // Remove from the WeakCell from the "active_cells" list of its
  // JSFinalizationRegistry and insert it into the "cleared_cells" list. This is
  // only called for WeakCells which haven't been unregistered yet, so they will
  // be in the active_cells list. (The caller must guard against calling this
  // for unregistered WeakCells by checking that the target is not undefined.)
  DCHECK(Object::CanBeHeldWeakly(target()));
  set_target(ReadOnlyRoots(isolate).undefined_value());
  Tagged<JSFinalizationRegistry> fr =
      Cast<JSFinalizationRegistry>(finalization_registry());
  if (IsWeakCell(prev())) {
    DCHECK_NE(fr->active_cells(), *this);
    Tagged<WeakCell> prev_cell = Cast<WeakCell>(prev());
    prev_cell->set_next(next());
    gc_notify_updated_slot(prev_cell,
                           prev_cell->RawField(WeakCell::kNextOffset), next());
  } else {
    DCHECK_EQ(fr->active_cells(), *this);
    fr->set_active_cells(next());
    gc_notify_updated_slot(
        fr, fr->RawField(JSFinalizationRegistry::kActiveCellsOffset), next());
  }
  if (IsWeakCell(next())) {
    Tagged<WeakCell> next_cell = Cast<WeakCell>(next());
    next_cell->set_prev(prev());
    gc_notify_updated_slot(next_cell,
                           next_cell->RawField(WeakCell::kPrevOffset), prev());
  }
  set_prev(ReadOnlyRoots(isolate).undefined_value());
  Tagged<UnionOf<Undefined, WeakCell>> cleared_head = fr->cleared_cells();
  if (IsWeakCell(cleared_head)) {
    Tagged<WeakCell> cleared_head_cell = Cast<WeakCell>(cleared_head);
    cleared_head_cell->set_prev(*this);
    gc_notify_updated_slot(cleared_head_cell,
                           cleared_head_cell->RawField(WeakCell::kPrevOffset),
                           *this);
  }
  set_next(fr->cleared_cells());
  gc_notify_updated_slot(*this, RawField(WeakCell::kNextOffset), next());
  fr->set_cleared_cells(*this);
  gc_notify_updated_slot(
      fr, fr->RawField(JSFinalizationRegistry::kClearedCellsOffset), *this);
}
References v8::internal::Object::CanBeHeldWeakly(), v8::internal::DCHECK(), DCHECK_EQ, and DCHECK_NE.
relaxed_target()
Tagged< HeapObject > v8::internal::WeakCell::relaxed_target () const [inline]
Definition at line 161 of file js-weak-refs-inl.h.
                                                  {
  return TaggedField<HeapObject>::Relaxed_Load(*this, kTargetOffset);
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load().
relaxed_unregister_token()
Tagged< HeapObject > v8::internal::WeakCell::relaxed_unregister_token () const [inline]
Definition at line 165 of file js-weak-refs-inl.h.
                                                            {
  return TaggedField<HeapObject>::Relaxed_Load(*this, kUnregisterTokenOffset);
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load().
RemoveFromFinalizationRegistryCells()
void v8::internal::WeakCell::RemoveFromFinalizationRegistryCells (Isolate * isolate) [inline]
Definition at line 217 of file js-weak-refs-inl.h.
                                                                   {
  // Remove the WeakCell from the list it's in (either "active_cells" or
  // "cleared_cells" of its JSFinalizationRegistry).
  // It's important to set_target to undefined here. This guards that we won't
  // call Nullify (which assumes that the WeakCell is in active_cells).
  DCHECK(IsUndefined(target()) || Object::CanBeHeldWeakly(target()));
  set_target(ReadOnlyRoots(isolate).undefined_value());
  Tagged<JSFinalizationRegistry> fr =
      Cast<JSFinalizationRegistry>(finalization_registry());
  if (fr->active_cells() == *this) {
    DCHECK(IsUndefined(prev(), isolate));
    fr->set_active_cells(next());
  } else if (fr->cleared_cells() == *this) {
    DCHECK(!IsWeakCell(prev()));
    fr->set_cleared_cells(next());
  } else {
    DCHECK(IsWeakCell(prev()));
    Tagged<WeakCell> prev_cell = Cast<WeakCell>(prev());
    prev_cell->set_next(next());
  }
  if (IsWeakCell(next())) {
    Tagged<WeakCell> next_cell = Cast<WeakCell>(next());
    next_cell->set_prev(prev());
  }
  set_prev(ReadOnlyRoots(isolate).undefined_value());
  set_next(ReadOnlyRoots(isolate).undefined_value());
}
References v8::internal::Object::CanBeHeldWeakly(), and v8::internal::DCHECK().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-weak-refs.h
/mnt/V8SourceCode/src/objects/js-weak-refs-inl.h