v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::ExternalReferenceList Class Reference
Public Member Functions
ExternalReferenceList (const ExternalReferenceList &)=delete
ExternalReferenceList & operator= (const ExternalReferenceList &)=delete
uint32_t tag_from_address (Address ext_ref_address) const
Address address_from_tag (uint32_t tag) const
Static Public Member Functions
static const ExternalReferenceList & Get ()
Private Member Functions
ExternalReferenceList ()
Private Attributes
Address external_reference_by_tag_ [kNumExternalReferences]
uint32_t tags_ordered_by_address_ [kNumExternalReferences]
Static Private Attributes
static constexpr uint32_t kNumExternalReferencesList
static constexpr uint32_t kNumExternalReferencesIntrinsics
static constexpr uint32_t kNumExternalReferences
Detailed Description
Definition at line 239 of file wasm-serialization.cc.
Constructor & Destructor Documentation
ExternalReferenceList() [1/2]
v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::ExternalReferenceList::ExternalReferenceList (const ExternalReferenceList &) [delete]
ExternalReferenceList() [2/2]
v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::ExternalReferenceList::ExternalReferenceList () [inline], [private]
Definition at line 269 of file wasm-serialization.cc.
                          {
    for (uint32_t i = 0; i < kNumExternalReferences; ++i) {
      tags_ordered_by_address_[i] = i;
    }
    auto addr_by_tag_less_than = [this](uint32_t a, uint32_t b) {
      return external_reference_by_tag_[a] < external_reference_by_tag_[b];
    };
    std::sort(std::begin(tags_ordered_by_address_),
              std::end(tags_ordered_by_address_), addr_by_tag_less_than);
  }
References v8::internal::compiler::begin(), v8::internal::compiler::end(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::base::sort().
Member Function Documentation
address_from_tag()
Address v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::ExternalReferenceList::address_from_tag (uint32_t tag) const [inline]
Definition at line 257 of file wasm-serialization.cc.
                                               {
    DCHECK_GT(kNumExternalReferences, tag);
    return external_reference_by_tag_[tag];
  }
References DCHECK_GT.
Get()
static const ExternalReferenceList& v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::ExternalReferenceList::Get () [inline], [static]
Definition at line 262 of file wasm-serialization.cc.
                                            {
    static ExternalReferenceList list; // Lazily initialized.
    return list;
  }
operator=()
ExternalReferenceList& v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::ExternalReferenceList::operator= (const ExternalReferenceList &) [delete]
tag_from_address()
uint32_t v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::ExternalReferenceList::tag_from_address (Address ext_ref_address) const [inline]
Definition at line 244 of file wasm-serialization.cc.
                                                           {
    auto tag_addr_less_than = [this](uint32_t tag, Address searched_addr) {
      return external_reference_by_tag_[tag] < searched_addr;
    };
    auto it = std::lower_bound(std::begin(tags_ordered_by_address_),
                               std::end(tags_ordered_by_address_),
                               ext_ref_address, tag_addr_less_than);
    DCHECK_NE(std::end(tags_ordered_by_address_), it);
    uint32_t tag = *it;
    DCHECK_EQ(address_from_tag(tag), ext_ref_address);
    return tag;
  }
References v8::internal::compiler::begin(), DCHECK_EQ, DCHECK_NE, and v8::internal::compiler::end().
Member Data Documentation
external_reference_by_tag_
Address v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::ExternalReferenceList::external_reference_by_tag_[kNumExternalReferences] [private]
Initial value:
= {
#define EXT_REF_ADDR(name, desc)
#define RUNTIME_ADDR(name, ...)
  }
Definition at line 289 of file wasm-serialization.cc.
kNumExternalReferences
constexpr uint32_t v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::ExternalReferenceList::kNumExternalReferences [static], [constexpr], [private]
Initial value:
=
      kNumExternalReferencesList + kNumExternalReferencesIntrinsics
Definition at line 285 of file wasm-serialization.cc.
kNumExternalReferencesIntrinsics
constexpr uint32_t v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::ExternalReferenceList::kNumExternalReferencesIntrinsics [static], [constexpr], [private]
Initial value:
=
      FOR_EACH_INTRINSIC(COUNT_EXTERNAL_REFERENCE)
Definition at line 283 of file wasm-serialization.cc.
kNumExternalReferencesList
constexpr uint32_t v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::ExternalReferenceList::kNumExternalReferencesList [static], [constexpr], [private]
Initial value:
=
      EXTERNAL_REFERENCE_LIST(COUNT_EXTERNAL_REFERENCE)
Definition at line 281 of file wasm-serialization.cc.
tags_ordered_by_address_
uint32_t v8::internal::wasm::anonymous_namespace{wasm-serialization.cc}::ExternalReferenceList::tags_ordered_by_address_[kNumExternalReferences] [private]
Definition at line 298 of file wasm-serialization.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/wasm-serialization.cc