v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits > Class Template Reference
Static Public Member Functions
static Handle< Object > GetInternalImpl (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry)
static Handle< Object > GetImpl (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry)
static DirectHandle< Object > GetImpl (Isolate *isolate, Tagged< FixedArrayBase > elements, InternalIndex entry)
static PropertyDetails GetDetailsImpl (Tagged< JSObject > holder, InternalIndex entry)
static InternalIndex GetEntryForIndexImpl (Isolate *isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store, size_t index, PropertyFilter filter)
static void DeleteImpl (Isolate *isolate, DirectHandle< JSObject > holder, InternalIndex entry)
static void SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value)
static Maybe< bool > AddImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity)
static void ReconfigureImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes)
static V8_WARN_UNUSED_RESULT ExceptionStatus AddElementsToKeyAccumulatorImpl (DirectHandle< JSObject > receiver, KeyAccumulator *accumulator, AddKeyConversion convert)
static V8_WARN_UNUSED_RESULT ExceptionStatus CollectElementIndicesImpl (DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, KeyAccumulator *keys)
static Maybe< bool > GrowCapacityAndConvertImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t capacity)
static void CopyElementsImpl (Isolate *isolate, Tagged< FixedArrayBase > from, uint32_t from_start, Tagged< FixedArrayBase > to, ElementsKind from_kind, uint32_t to_start, int packed_size, int copy_size)
static uint32_t NumberOfElementsImpl (Isolate *isolate, Tagged< JSObject > object, Tagged< FixedArrayBase > backing_store)
Static Private Member Functions
static Tagged< String > GetString (Tagged< JSObject > holder)
Additional Inherited Members
Detailed Description
template<typename Subclass, typename BackingStoreAccessor, typename KindTraits>
class v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >
Definition at line 5460 of file elements.cc.
Member Function Documentation
AddElementsToKeyAccumulatorImpl()
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::AddElementsToKeyAccumulatorImpl (DirectHandle< JSObject > receiver, KeyAccumulator * accumulator, AddKeyConversion convert) [inline], [static]
Definition at line 5564 of file elements.cc.
                                {
    Isolate* isolate = accumulator->isolate();
    DirectHandle<String> string(GetString(*receiver), isolate);
    string = String::Flatten(isolate, string);
    uint32_t length = static_cast<uint32_t>(string->length());
    for (uint32_t i = 0; i < length; i++) {
      DirectHandle<String> key =
          isolate->factory()->LookupSingleCharacterStringFromCode(
              string->Get(i));
      RETURN_FAILURE_IF_NOT_SUCCESSFUL(accumulator->AddKey(key, convert));
    }
    return BackingStoreAccessor::AddElementsToKeyAccumulatorImpl(
        receiver, accumulator, convert);
  }
References v8::internal::KeyAccumulator::AddKey(), v8::internal::Isolate::factory(), v8::internal::KeyAccumulator::isolate(), v8::internal::key, v8::internal::length, v8::internal::FactoryBase< Impl >::LookupSingleCharacterStringFromCode(), RETURN_FAILURE_IF_NOT_SUCCESSFUL, and v8::internal::string.
AddImpl()
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::AddImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t index, DirectHandle< Object > value, PropertyAttributes attributes, uint32_t new_capacity) [inline], [static]
Definition at line 5533 of file elements.cc.
                                                    {
    DCHECK(index >= static_cast<uint32_t>(GetString(*object)->length()));
    // Explicitly grow fast backing stores if needed. Dictionaries know how to
    // extend their capacity themselves.
    if (KindTraits::Kind == FAST_STRING_WRAPPER_ELEMENTS &&
        (object->GetElementsKind() == SLOW_STRING_WRAPPER_ELEMENTS ||
         BackingStoreAccessor::GetCapacityImpl(*object, object->elements()) !=
             new_capacity)) {
      MAYBE_RETURN(GrowCapacityAndConvertImpl(isolate, object, new_capacity),
                   Nothing<bool>());
    }
    BackingStoreAccessor::AddImpl(isolate, object, index, value, attributes,
                                  new_capacity);
    return Just(true);
  }
References v8::internal::DCHECK(), v8::internal::FAST_STRING_WRAPPER_ELEMENTS, v8::internal::index, v8::Just(), MAYBE_RETURN, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, and v8::internal::value.
CollectElementIndicesImpl()
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::CollectElementIndicesImpl (DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, KeyAccumulator * keys) [inline], [static]
Definition at line 5581 of file elements.cc.
                            {
    uint32_t length = GetString(*object)->length();
    Factory* factory = keys->isolate()->factory();
    for (uint32_t i = 0; i < length; i++) {
      RETURN_FAILURE_IF_NOT_SUCCESSFUL(
          keys->AddKey(factory->NewNumberFromUint(i)));
    }
    return BackingStoreAccessor::CollectElementIndicesImpl(object,
                                                           backing_store, keys);
  }
References v8::internal::KeyAccumulator::AddKey(), v8::internal::Isolate::factory(), v8::internal::KeyAccumulator::isolate(), v8::internal::length, v8::internal::FactoryBase< Impl >::NewNumberFromUint(), and RETURN_FAILURE_IF_NOT_SUCCESSFUL.
CopyElementsImpl()
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::CopyElementsImpl (Isolate * isolate, Tagged< FixedArrayBase > from, uint32_t from_start, Tagged< FixedArrayBase > to, ElementsKind from_kind, uint32_t to_start, int packed_size, int copy_size) [inline], [static]
Definition at line 5615 of file elements.cc.
                                                               {
    DCHECK(!IsNumberDictionary(to));
    if (from_kind == SLOW_STRING_WRAPPER_ELEMENTS) {
      CopyDictionaryToObjectElements(isolate, from, from_start, to,
                                     HOLEY_ELEMENTS, to_start, copy_size);
    } else {
      DCHECK_EQ(FAST_STRING_WRAPPER_ELEMENTS, from_kind);
      CopyObjectToObjectElements(isolate, from, HOLEY_ELEMENTS, from_start, to,
                                 HOLEY_ELEMENTS, to_start, copy_size);
    }
  }
References v8::internal::anonymous_namespace{elements.cc}::CopyDictionaryToObjectElements(), v8::internal::anonymous_namespace{elements.cc}::CopyObjectToObjectElements(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::FAST_STRING_WRAPPER_ELEMENTS, v8::internal::HOLEY_ELEMENTS, and v8::internal::SLOW_STRING_WRAPPER_ELEMENTS.
DeleteImpl()
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::DeleteImpl (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry) [inline], [static]
Definition at line 5513 of file elements.cc.
                                              {
    uint32_t length = static_cast<uint32_t>(GetString(*holder)->length());
    if (entry.as_uint32() < length) {
      return; // String contents can't be deleted.
    }
    BackingStoreAccessor::DeleteImpl(isolate, holder,
                                     entry.adjust_down(length));
  }
References v8::internal::InternalIndex::adjust_down(), v8::internal::InternalIndex::as_uint32(), and v8::internal::length.
GetDetailsImpl()
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static PropertyDetails v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetDetailsImpl (Tagged< JSObject > holder, InternalIndex entry) [inline], [static]
Definition at line 5487 of file elements.cc.
                                                             {
    uint32_t length = static_cast<uint32_t>(GetString(holder)->length());
    if (entry.as_uint32() < length) {
      PropertyAttributes attributes =
          static_cast<PropertyAttributes>(READ_ONLY | DONT_DELETE);
      return PropertyDetails(PropertyKind::kData, attributes,
                             PropertyCellType::kNoCell);
    }
    return BackingStoreAccessor::GetDetailsImpl(holder,
                                                entry.adjust_down(length));
  }
References v8::internal::InternalIndex::adjust_down(), v8::internal::InternalIndex::as_uint32(), v8::internal::DONT_DELETE, v8::internal::kData, v8::internal::kNoCell, v8::internal::length, and v8::internal::READ_ONLY.
GetEntryForIndexImpl()
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static InternalIndex v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetEntryForIndexImpl (Isolate * isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store, size_t index, PropertyFilter filter) [inline], [static]
Definition at line 5500 of file elements.cc.
                             {
    uint32_t length = static_cast<uint32_t>(GetString(holder)->length());
    if (index < length) return InternalIndex(index);
    InternalIndex backing_store_entry =
        BackingStoreAccessor::GetEntryForIndexImpl(
            isolate, holder, backing_store, index, filter);
    if (backing_store_entry.is_not_found()) return backing_store_entry;
    return backing_store_entry.adjust_up(length);
  }
References v8::internal::InternalIndex::adjust_up(), v8::internal::index, v8::internal::InternalIndex::is_not_found(), and v8::internal::length.
GetImpl() [1/2]
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetImpl (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry) [inline], [static]
Definition at line 5469 of file elements.cc.
                                                     {
    DirectHandle<String> string(GetString(*holder), isolate);
    uint32_t length = static_cast<uint32_t>(string->length());
    if (entry.as_uint32() < length) {
      return isolate->factory()->LookupSingleCharacterStringFromCode(
          String::Flatten(isolate, string)->Get(entry.as_int()));
    }
    return BackingStoreAccessor::GetImpl(isolate, holder->elements(),
                                         entry.adjust_down(length));
  }
References v8::internal::InternalIndex::adjust_down(), v8::internal::InternalIndex::as_int(), v8::internal::InternalIndex::as_uint32(), v8::internal::Isolate::factory(), v8::internal::length, v8::internal::FactoryBase< Impl >::LookupSingleCharacterStringFromCode(), and v8::internal::string.
GetImpl() [2/2]
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static DirectHandle<Object> v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetImpl (Isolate * isolate, Tagged< FixedArrayBase > elements, InternalIndex entry) [inline], [static]
Definition at line 5481 of file elements.cc.
                                                           {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
GetInternalImpl()
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetInternalImpl (Isolate * isolate, DirectHandle< JSObject > holder, InternalIndex entry) [inline], [static]
Definition at line 5463 of file elements.cc.
                                                             {
    return GetImpl(isolate, holder, entry);
  }
GetString()
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static Tagged<String> v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GetString (Tagged< JSObject > holder) [inline], [static], [private]
Definition at line 5639 of file elements.cc.
                                                           {
    DCHECK(IsJSPrimitiveWrapper(holder));
    Tagged<JSPrimitiveWrapper> js_value = Cast<JSPrimitiveWrapper>(holder);
    DCHECK(IsString(js_value->value()));
    return Cast<String>(js_value->value());
  }
References v8::internal::DCHECK().
GrowCapacityAndConvertImpl()
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::GrowCapacityAndConvertImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t capacity) [inline], [static]
Definition at line 5594 of file elements.cc.
                                                                   {
    DirectHandle<FixedArrayBase> old_elements(object->elements(), isolate);
    ElementsKind from_kind = object->GetElementsKind();
    if (from_kind == FAST_STRING_WRAPPER_ELEMENTS) {
      // The optimizing compiler relies on the prototype lookups of String
      // objects always returning undefined. If there's a store to the
      // initial String.prototype object, make sure all the optimizations
      // are invalidated.
      isolate->UpdateNoElementsProtectorOnSetLength(object);
    }
    // This method should only be called if there's a reason to update the
    // elements.
    DCHECK(from_kind == SLOW_STRING_WRAPPER_ELEMENTS ||
           static_cast<uint32_t>(old_elements->length()) < capacity);
    return Subclass::BasicGrowCapacityAndConvertImpl(
        isolate, object, old_elements, from_kind, FAST_STRING_WRAPPER_ELEMENTS,
        capacity);
  }
References v8::internal::DCHECK(), v8::internal::FAST_STRING_WRAPPER_ELEMENTS, v8::internal::SLOW_STRING_WRAPPER_ELEMENTS, and v8::internal::Isolate::UpdateNoElementsProtectorOnSetLength().
NumberOfElementsImpl()
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static uint32_t v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::NumberOfElementsImpl (Isolate * isolate, Tagged< JSObject > object, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 5630 of file elements.cc.
                                                                             {
    uint32_t length = GetString(object)->length();
    return length + BackingStoreAccessor::NumberOfElementsImpl(isolate, object,
                                                               backing_store);
  }
References v8::internal::length.
ReconfigureImpl()
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::ReconfigureImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > store, InternalIndex entry, DirectHandle< Object > value, PropertyAttributes attributes) [inline], [static]
Definition at line 5552 of file elements.cc.
                                                             {
    uint32_t length = static_cast<uint32_t>(GetString(*object)->length());
    if (entry.as_uint32() < length) {
      return; // String contents can't be reconfigured.
    }
    BackingStoreAccessor::ReconfigureImpl(
        isolate, object, store, entry.adjust_down(length), value, attributes);
  }
References v8::internal::InternalIndex::adjust_down(), v8::internal::InternalIndex::as_uint32(), v8::internal::length, store(), and v8::internal::value.
SetImpl()
template<typename Subclass , typename BackingStoreAccessor , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::StringWrapperElementsAccessor< Subclass, BackingStoreAccessor, KindTraits >::SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value) [inline], [static]
Definition at line 5523 of file elements.cc.
                                            {
    uint32_t length = static_cast<uint32_t>(GetString(*holder)->length());
    if (entry.as_uint32() < length) {
      return; // String contents are read-only.
    }
    BackingStoreAccessor::SetImpl(holder->elements(), entry.adjust_down(length),
                                  value);
  }
References v8::internal::InternalIndex::adjust_down(), v8::internal::InternalIndex::as_uint32(), v8::internal::length, and v8::internal::value.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/elements.cc