v8::internal::compiler::turboshaft::FixedOpIndexSidetable< T > Class Template Reference
#include <sidetable.h>
Public Member Functions
FixedOpIndexSidetable (size_t size, Zone *zone, const Graph *graph)
FixedOpIndexSidetable (size_t size, const T &default_value, Zone *zone, const Graph *graph)
T & operator[] (OpIndex index)
const T & operator[] (OpIndex index) const
void SwapData (FixedOpIndexSidetable< T > &other)
Private Types
using Base = detail::FixedSidetable< T, OpIndex >
Additional Inherited Members
Detailed Description
template<class T>
class v8::internal::compiler::turboshaft::FixedOpIndexSidetable< T >
Definition at line 178 of file sidetable.h.
Member Typedef Documentation
Base
template<class T >
using v8::internal::compiler::turboshaft::FixedOpIndexSidetable< T >::Base = detail::FixedSidetable<T, OpIndex> [private]
Definition at line 179 of file sidetable.h.
Constructor & Destructor Documentation
FixedOpIndexSidetable() [1/2]
template<class T >
v8::internal::compiler::turboshaft::FixedOpIndexSidetable< T >::FixedOpIndexSidetable (size_t size, Zone * zone, const Graph * graph) [inline]
Definition at line 182 of file sidetable.h.
      : Base(size, zone)
#ifdef DEBUG
        ,
        graph_(graph)
#endif
  {
  }
FixedOpIndexSidetable() [2/2]
template<class T >
v8::internal::compiler::turboshaft::FixedOpIndexSidetable< T >::FixedOpIndexSidetable (size_t size, const T & default_value, Zone * zone, const Graph * graph) [inline]
Definition at line 190 of file sidetable.h.
      : Base(size, default_value, zone)
#ifdef DEBUG
        ,
        graph_(graph)
#endif
  {
  }
Member Function Documentation
operator[]() [1/2]
template<class T >
T& v8::internal::compiler::turboshaft::FixedOpIndexSidetable< T >::operator[] (OpIndex index) [inline]
Definition at line 200 of file sidetable.h.
                               {
    DCHECK(OpIndexBelongsToTableGraph(graph_, index));
    return Base::operator[](index);
  }
References v8::internal::DCHECK(), v8::internal::index, and v8::internal::compiler::turboshaft::detail::FixedSidetable< T, OpIndex >::operator[]().
operator[]() [2/2]
template<class T >
const T& v8::internal::compiler::turboshaft::FixedOpIndexSidetable< T >::operator[] (OpIndex index) const [inline]
Definition at line 205 of file sidetable.h.
                                           {
    DCHECK(OpIndexBelongsToTableGraph(graph_, index));
    return Base::operator[](index);
  }
References v8::internal::DCHECK(), v8::internal::index, and v8::internal::compiler::turboshaft::detail::FixedSidetable< T, OpIndex >::operator[]().
SwapData()
template<class T >
void v8::internal::compiler::turboshaft::FixedOpIndexSidetable< T >::SwapData (FixedOpIndexSidetable< T > & other) [inline]
Definition at line 210 of file sidetable.h.
                                                 {
    std::swap(Base::table_, other.table_);
  }
References v8::internal::compiler::turboshaft::detail::FixedSidetable< T, Key >::table_, and v8::internal::compiler::turboshaft::detail::FixedSidetable< T, OpIndex >::table_.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/sidetable.h