v8::internal::UnoptimizedCompileFlags Class Reference
#include <parse-info.h>
Classes
struct BitFields
Public Member Functions
int script_id () const
UnoptimizedCompileFlags & set_script_id (int value)
FunctionKind function_kind () const
UnoptimizedCompileFlags & set_function_kind (FunctionKind value)
FunctionSyntaxKind function_syntax_kind () const
UnoptimizedCompileFlags & set_function_syntax_kind (FunctionSyntaxKind value)
ParsingWhileDebugging parsing_while_debugging () const
UnoptimizedCompileFlags & set_parsing_while_debugging (ParsingWhileDebugging value)
Static Public Member Functions
static UnoptimizedCompileFlags ForToplevelCompile (Isolate *isolate, bool is_user_javascript, LanguageMode language_mode, REPLMode repl_mode, ScriptType type, bool lazy)
static UnoptimizedCompileFlags ForFunctionCompile (Isolate *isolate, Tagged< SharedFunctionInfo > shared)
static UnoptimizedCompileFlags ForScriptCompile (Isolate *isolate, Tagged< Script > script)
static UnoptimizedCompileFlags ForToplevelFunction (const UnoptimizedCompileFlags toplevel_flags, const FunctionLiteral *literal)
static UnoptimizedCompileFlags ForTest (Isolate *isolate)
Private Member Functions
UnoptimizedCompileFlags (Isolate *isolate, int script_id)
template<typename T >
void SetFlagsFromFunction (T function)
void SetFlagsForToplevelCompile (bool is_user_javascript, LanguageMode language_mode, REPLMode repl_mode, ScriptType type, bool lazy)
void SetFlagsForFunctionFromScript (Tagged< Script > script)
Private Attributes
uint32_t flags_
int script_id_
FunctionKind function_kind_
FunctionSyntaxKind function_syntax_kind_
ParsingWhileDebugging parsing_while_debugging_
Detailed Description
Definition at line 70 of file parse-info.h.
Constructor & Destructor Documentation
UnoptimizedCompileFlags()
v8::internal::UnoptimizedCompileFlags::UnoptimizedCompileFlags (Isolate * isolate, int script_id) [private]
Definition at line 24 of file parse-info.cc.
    : flags_(0),
      script_id_(script_id),
      function_kind_(FunctionKind::kNormalFunction),
      function_syntax_kind_(FunctionSyntaxKind::kDeclaration),
      parsing_while_debugging_(ParsingWhileDebugging::kNo) {
  set_coverage_enabled(!isolate->is_best_effort_code_coverage());
  set_block_coverage_enabled(isolate->is_block_code_coverage());
  set_might_always_turbofan(v8_flags.always_turbofan ||
                            v8_flags.prepare_always_turbofan);
  set_allow_natives_syntax(v8_flags.allow_natives_syntax);
  set_allow_lazy_compile(true);
  set_collect_source_positions(!v8_flags.enable_lazy_source_positions ||
                               isolate->NeedsDetailedOptimizedCodeLineInfo());
  set_post_parallel_compile_tasks_for_eager_toplevel(
      v8_flags.parallel_compile_tasks_for_eager_toplevel);
  set_post_parallel_compile_tasks_for_lazy(
      v8_flags.parallel_compile_tasks_for_lazy);
}
References v8::internal::Isolate::is_best_effort_code_coverage(), v8::internal::Isolate::is_block_code_coverage(), v8::internal::kDeclaration, v8::internal::Isolate::NeedsDetailedOptimizedCodeLineInfo(), and v8::internal::v8_flags.
Referenced by ForTest().
Member Function Documentation
ForFunctionCompile()
UnoptimizedCompileFlags v8::internal::UnoptimizedCompileFlags::ForFunctionCompile (Isolate * isolate, Tagged< SharedFunctionInfo > shared) [static]
Definition at line 46 of file parse-info.cc.
                                                         {
  Tagged<Script> script = Cast<Script>(shared->script());
  UnoptimizedCompileFlags flags(isolate, script->id());
  flags.SetFlagsForFunctionFromScript(script);
  flags.SetFlagsFromFunction(shared);
  flags.set_allow_lazy_parsing(true);
  flags.set_is_lazy_compile(true);
#if V8_ENABLE_WEBASSEMBLY
  flags.set_is_asm_wasm_broken(shared->is_asm_wasm_broken());
#endif // V8_ENABLE_WEBASSEMBLY
  flags.set_is_repl_mode(script->is_repl_mode());
  // Do not support re-parsing top-level function of a wrapped script.
  DCHECK_IMPLIES(flags.is_toplevel(), !script->is_wrapped());
  return flags;
}
References DCHECK_IMPLIES, v8::internal::flags, and v8::internal::script.
Referenced by v8::internal::Compiler::CollectSourcePositions(), v8::internal::Compiler::Compile(), v8::internal::anonymous_namespace{messages.cc}::RenderCallSite(), v8::internal::ErrorUtils::ThrowLoadFromNullOrUndefined(), v8::internal::ErrorUtils::ThrowSpreadArgError(), and v8::internal::ScopeIterator::TryParseAndRetrieveScopes().
ForScriptCompile()
UnoptimizedCompileFlags v8::internal::UnoptimizedCompileFlags::ForScriptCompile (Isolate * isolate, Tagged< Script > script) [static]
Definition at line 69 of file parse-info.cc.
                                             {
  UnoptimizedCompileFlags flags(isolate, script->id());
  flags.SetFlagsForFunctionFromScript(script);
  flags.SetFlagsForToplevelCompile(
      script->IsUserJavaScript(), flags.outer_language_mode(),
      construct_repl_mode(script->is_repl_mode()),
      script->origin_options().IsModule() ? ScriptType::kModule
                                          : ScriptType::kClassic,
      v8_flags.lazy);
  if (script->is_wrapped()) {
    flags.set_function_syntax_kind(FunctionSyntaxKind::kWrapped);
  }
  return flags;
}
References v8::internal::construct_repl_mode(), v8::internal::flags, v8::kClassic, v8::kModule, v8::internal::kWrapped, v8::internal::script, and v8::internal::v8_flags.
Referenced by v8::internal::anonymous_namespace{debug.cc}::CompileTopLevel(), v8::internal::LiveEdit::PatchScript(), and v8::internal::ScopeIterator::TryParseAndRetrieveScopes().
ForTest()
UnoptimizedCompileFlags v8::internal::UnoptimizedCompileFlags::ForTest (Isolate * isolate) [static]
Definition at line 113 of file parse-info.cc.
                                                                         {
  return UnoptimizedCompileFlags(isolate, Script::kTemporaryScriptId);
}
References v8::internal::Script::kTemporaryScriptId, and UnoptimizedCompileFlags().
ForToplevelCompile()
UnoptimizedCompileFlags v8::internal::UnoptimizedCompileFlags::ForToplevelCompile (Isolate * isolate, bool is_user_javascript, LanguageMode language_mode, REPLMode repl_mode, ScriptType type, bool lazy) [static]
Definition at line 88 of file parse-info.cc.
                                                    {
  UnoptimizedCompileFlags flags(isolate, isolate->GetNextScriptId());
  flags.SetFlagsForToplevelCompile(is_user_javascript, language_mode, repl_mode,
                                   type, lazy);
  LOG(isolate, ScriptEvent(ScriptEventType::kReserveId, flags.script_id()));
  return flags;
}
References v8::internal::flags, v8::internal::Isolate::GetNextScriptId(), v8::internal::kReserveId, LOG, and v8::internal::tracing::type.
Referenced by v8::Shell::ExecuteString(), v8::internal::Compiler::GetFunctionFromEval(), v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), and v8::internal::Compiler::GetWrappedFunction().
ForToplevelFunction()
UnoptimizedCompileFlags v8::internal::UnoptimizedCompileFlags::ForToplevelFunction (const UnoptimizedCompileFlags toplevel_flags, const FunctionLiteral * literal) [static]
Definition at line 99 of file parse-info.cc.
                                    {
  DCHECK(toplevel_flags.is_toplevel());
  DCHECK(!literal->is_toplevel());
  // Replicate the toplevel flags, then setup the function-specific flags.
  UnoptimizedCompileFlags flags = toplevel_flags;
  flags.SetFlagsFromFunction(literal);
  return flags;
}
References v8::internal::DCHECK(), v8::internal::flags, and v8::internal::FunctionLiteral::is_toplevel().
function_kind()
FunctionKind v8::internal::UnoptimizedCompileFlags::function_kind () const [inline]
Definition at line 112 of file parse-info.h.
{ return function_kind_; }
function_syntax_kind()
FunctionSyntaxKind v8::internal::UnoptimizedCompileFlags::function_syntax_kind () const [inline]
Definition at line 118 of file parse-info.h.
                                                  {
    return function_syntax_kind_;
  }
parsing_while_debugging()
ParsingWhileDebugging v8::internal::UnoptimizedCompileFlags::parsing_while_debugging () const [inline]
Definition at line 126 of file parse-info.h.
                                                        {
    return parsing_while_debugging_;
  }
Referenced by v8::internal::ParserBase< Impl >::IsParsingWhileDebugging().
script_id()
int v8::internal::UnoptimizedCompileFlags::script_id () const [inline]
Definition at line 106 of file parse-info.h.
{ return script_id_; }
Referenced by v8::internal::PreParser::ParseFunctionLiteral(), and SetFlagsForFunctionFromScript().
set_function_kind()
UnoptimizedCompileFlags& v8::internal::UnoptimizedCompileFlags::set_function_kind (FunctionKind value) [inline]
Definition at line 113 of file parse-info.h.
                                                                 {
    function_kind_ = value;
    return *this;
  }
References v8::internal::value.
Referenced by SetFlagsFromFunction().
set_function_syntax_kind()
UnoptimizedCompileFlags& v8::internal::UnoptimizedCompileFlags::set_function_syntax_kind (FunctionSyntaxKind value) [inline]
Definition at line 121 of file parse-info.h.
                                                                              {
    function_syntax_kind_ = value;
    return *this;
  }
References v8::internal::value.
Referenced by SetFlagsFromFunction().
set_parsing_while_debugging()
UnoptimizedCompileFlags& v8::internal::UnoptimizedCompileFlags::set_parsing_while_debugging (ParsingWhileDebugging value) [inline]
Definition at line 129 of file parse-info.h.
                                   {
    parsing_while_debugging_ = value;
    return *this;
  }
References v8::internal::value.
set_script_id()
UnoptimizedCompileFlags& v8::internal::UnoptimizedCompileFlags::set_script_id (int value) [inline]
Definition at line 107 of file parse-info.h.
                                                    {
    script_id_ = value;
    return *this;
  }
References v8::internal::value.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnBothBackgroundAndMainThread().
SetFlagsForFunctionFromScript()
void v8::internal::UnoptimizedCompileFlags::SetFlagsForFunctionFromScript (Tagged< Script > script) [private]
Definition at line 147 of file parse-info.cc.
                           {
  DCHECK_EQ(script_id(), script->id());
  set_is_eval(script->compilation_type() == Script::CompilationType::kEval);
  set_is_module(script->origin_options().IsModule());
  DCHECK_IMPLIES(is_eval(), !is_module());
  set_block_coverage_enabled(block_coverage_enabled() &&
                             script->IsUserJavaScript());
}
References DCHECK_EQ, DCHECK_IMPLIES, v8::internal::Script::kEval, v8::internal::script, and script_id().
SetFlagsForToplevelCompile()
void v8::internal::UnoptimizedCompileFlags::SetFlagsForToplevelCompile (bool is_user_javascript, LanguageMode language_mode, REPLMode repl_mode, ScriptType type, bool lazy) [private]
Definition at line 132 of file parse-info.cc.
                                {
  set_is_toplevel(true);
  set_allow_lazy_parsing(lazy);
  set_allow_lazy_compile(lazy);
  set_outer_language_mode(
      stricter_language_mode(outer_language_mode(), language_mode));
  set_is_repl_mode((repl_mode == REPLMode::kYes));
  set_is_module(type == ScriptType::kModule);
  DCHECK_IMPLIES(is_eval(), !is_module());
  set_block_coverage_enabled(block_coverage_enabled() && is_user_javascript);
}
References DCHECK_IMPLIES, v8::kModule, v8::internal::kYes, v8::internal::stricter_language_mode(), and v8::internal::tracing::type.
SetFlagsFromFunction()
template<typename T >
void v8::internal::UnoptimizedCompileFlags::SetFlagsFromFunction (T function) [private]
Definition at line 118 of file parse-info.cc.
                                                             {
  set_outer_language_mode(function->language_mode());
  set_function_kind(function->kind());
  set_function_syntax_kind(function->syntax_kind());
  set_requires_instance_members_initializer(
      function->requires_instance_members_initializer());
  set_class_scope_has_private_brand(function->class_scope_has_private_brand());
  set_has_static_private_methods_or_accessors(
      function->has_static_private_methods_or_accessors());
  set_private_name_lookup_skips_outer_class(
      function->private_name_lookup_skips_outer_class());
  set_is_toplevel(function->is_toplevel());
}
References set_function_kind(), and set_function_syntax_kind().
Member Data Documentation
flags_
uint32_t v8::internal::UnoptimizedCompileFlags::flags_ [private]
Definition at line 152 of file parse-info.h.
function_kind_
FunctionKind v8::internal::UnoptimizedCompileFlags::function_kind_ [private]
Definition at line 154 of file parse-info.h.
function_syntax_kind_
FunctionSyntaxKind v8::internal::UnoptimizedCompileFlags::function_syntax_kind_ [private]
Definition at line 155 of file parse-info.h.
parsing_while_debugging_
ParsingWhileDebugging v8::internal::UnoptimizedCompileFlags::parsing_while_debugging_ [private]
Definition at line 156 of file parse-info.h.
script_id_
int v8::internal::UnoptimizedCompileFlags::script_id_ [private]
Definition at line 153 of file parse-info.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/parse-info.h
/mnt/V8SourceCode/src/parsing/parse-info.cc