v8::internal::ConcurrentLookupIterator Class Reference
#include <lookup.h>
Public Types
enum Result { kPresent
, kNotPresent
, kGaveUp
 }
Static Public Member Functions
static V8_EXPORT_PRIVATE std::optional< Tagged< Object > > TryGetOwnCowElement (Isolate *isolate, Tagged< FixedArray > array_elements, ElementsKind elements_kind, int array_length, size_t index)
static V8_EXPORT_PRIVATE Result TryGetOwnConstantElement (Tagged< Object > *result_out, Isolate *isolate, LocalIsolate *local_isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > elements, ElementsKind elements_kind, size_t index)
static V8_EXPORT_PRIVATE Result TryGetOwnChar (Tagged< String > *result_out, Isolate *isolate, LocalIsolate *local_isolate, Tagged< String > string, size_t index)
static V8_EXPORT_PRIVATE std::optional< Tagged< PropertyCell > > TryGetPropertyCell (Isolate *isolate, LocalIsolate *local_isolate, DirectHandle< JSGlobalObject > holder, DirectHandle< Name > name)
Detailed Description
Definition at line 389 of file lookup.h.
Member Enumeration Documentation
Result
enum v8::internal::ConcurrentLookupIterator::Result
Enumerator
kPresent
kNotPresent
kGaveUp
Definition at line 392 of file lookup.h.
              {
    kPresent, // The value was found.
    kNotPresent, // No value exists.
    kGaveUp, // The operation can't be completed.
  };
Member Function Documentation
TryGetOwnChar()
ConcurrentLookupIterator::Result v8::internal::ConcurrentLookupIterator::TryGetOwnChar (Tagged< String > * result_out, Isolate * isolate, LocalIsolate * local_isolate, Tagged< String > string, size_t index) [static]
Definition at line 1612 of file lookup.cc.
                                         {
  DisallowGarbageCollection no_gc;
  // The access guard below protects string accesses related to internalized
  // strings.
  // TODO(jgruber): Support other string kinds.
  Tagged<Map> string_map = string->map(kAcquireLoad);
  InstanceType type = string_map->instance_type();
  if (!(InstanceTypeChecker::IsInternalizedString(type) ||
        InstanceTypeChecker::IsThinString(type))) {
    return kGaveUp;
  }
  const uint32_t length = static_cast<uint32_t>(string->length());
  if (index >= length) return kGaveUp;
  uint16_t charcode;
  {
    SharedStringAccessGuardIfNeeded access_guard(local_isolate);
    charcode = string->Get(static_cast<int>(index), access_guard);
  }
  if (charcode > unibrow::Latin1::kMaxChar) return kGaveUp;
  ReadOnlyRoots roots(isolate);
  Tagged<String> value = roots.single_character_string(charcode);
  *result_out = value;
  return kPresent;
}
References v8::internal::index, v8::internal::InstanceTypeChecker::IsInternalizedString(), v8::internal::InstanceTypeChecker::IsThinString(), v8::kAcquireLoad, kGaveUp, unibrow::Latin1::kMaxChar, kPresent, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::ReadOnlyRoots::single_character_string(), v8::internal::tracing::type, and v8::internal::value.
Referenced by v8::internal::compiler::StringRef::GetCharAsStringOrUndefined(), and TryGetOwnConstantElement().
TryGetOwnConstantElement()
ConcurrentLookupIterator::Result v8::internal::ConcurrentLookupIterator::TryGetOwnConstantElement (Tagged< Object > * result_out, Isolate * isolate, LocalIsolate * local_isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > elements, ElementsKind elements_kind, size_t index) [static]
Definition at line 1548 of file lookup.cc.
                                              {
  DisallowGarbageCollection no_gc;
  DCHECK_LE(index, JSObject::kMaxElementIndex);
  // Own 'constant' elements (PropertyAttributes READ_ONLY|DONT_DELETE) occur in
  // three main cases:
  //
  // 1. Frozen elements: guaranteed constant.
  // 2. Dictionary elements: may be constant.
  // 3. String wrapper elements: guaranteed constant.
  // Interesting field reads below:
  //
  // - elements.length (immutable on FixedArrays).
  // - elements[i] (immutable if constant; be careful around dictionaries).
  // - holder.AsJSPrimitiveWrapper.value.AsString.length (immutable).
  // - holder.AsJSPrimitiveWrapper.value.AsString[i] (immutable).
  // - roots.single_character_string(charcode).
  if (IsFrozenElementsKind(elements_kind)) {
    if (!IsFixedArray(elements)) return kGaveUp;
    Tagged<FixedArray> elements_fixed_array = Cast<FixedArray>(elements);
    if (index >= static_cast<uint32_t>(elements_fixed_array->length())) {
      return kGaveUp;
    }
    Tagged<Object> result = elements_fixed_array->get(static_cast<int>(index));
    if (IsHoleyElementsKindForRead(elements_kind) &&
        result == ReadOnlyRoots(isolate).the_hole_value()) {
      return kNotPresent;
    }
    *result_out = result;
    return kPresent;
  } else if (IsDictionaryElementsKind(elements_kind)) {
    if (!IsNumberDictionary(elements)) return kGaveUp;
    // TODO(jgruber, v8:7790): Add support. Dictionary elements require racy
    // NumberDictionary lookups. This should be okay in general (slot iteration
    // depends only on the dict's capacity), but 1. we'd need to update
    // NumberDictionary methods to do atomic reads, and 2. the dictionary
    // elements case isn't very important for callers of this function.
    return kGaveUp;
  } else if (IsStringWrapperElementsKind(elements_kind)) {
    // In this case we don't care about the actual `elements`. All in-bounds
    // reads are redirected to the wrapped String.
    Tagged<JSPrimitiveWrapper> js_value = Cast<JSPrimitiveWrapper>(holder);
    Tagged<String> wrapped_string = Cast<String>(js_value->value());
    return ConcurrentLookupIterator::TryGetOwnChar(
        reinterpret_cast<Tagged<String>*>(result_out), isolate, local_isolate,
        wrapped_string, index);
  } else {
    DCHECK(!IsFrozenElementsKind(elements_kind));
    DCHECK(!IsDictionaryElementsKind(elements_kind));
    DCHECK(!IsStringWrapperElementsKind(elements_kind));
    return kGaveUp;
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::index, v8::internal::IsDictionaryElementsKind(), v8::internal::IsFrozenElementsKind(), v8::internal::IsHoleyElementsKindForRead(), v8::internal::IsStringWrapperElementsKind(), kGaveUp, v8::internal::JSObject::kMaxElementIndex, kNotPresent, kPresent, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, TryGetOwnChar(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::JSObjectRef::GetOwnConstantElementFromHeap().
TryGetOwnCowElement()
std::optional< Tagged< Object > > v8::internal::ConcurrentLookupIterator::TryGetOwnCowElement (Isolate * isolate, Tagged< FixedArray > array_elements, ElementsKind elements_kind, int array_length, size_t index) [static]
Definition at line 1503 of file lookup.cc.
                                                                {
  DisallowGarbageCollection no_gc;
  CHECK_EQ(array_elements->map(), ReadOnlyRoots(isolate).fixed_cow_array_map());
  DCHECK(IsFastElementsKind(elements_kind) &&
         IsSmiOrObjectElementsKind(elements_kind));
  USE(elements_kind);
  DCHECK_GE(array_length, 0);
  // ________________________________________
  // (Check against both JSArray::length and)
  // (FixedArray::length.)
  // ----------------------------------------
  // o ^__^
  // o (oo)\_______
  // (__)\)\/\
  // ||----w |
  // || ||
  // The former is the source of truth, but due to concurrent reads it may not
  // match the given `array_elements`.
  if (index >= static_cast<size_t>(array_length)) return {};
  if (index >= static_cast<size_t>(array_elements->length())) return {};
  Tagged<Object> result = array_elements->get(static_cast<int>(index));
  // ______________________________________
  // (Filter out holes irrespective of the)
  // (elements kind.)
  // --------------------------------------
  // o ^__^
  // o (..)\_______
  // (__)\)\/\
  // ||----w |
  // || ||
  // The elements kind may not be consistent with the given elements backing
  // store.
  if (result == ReadOnlyRoots(isolate).the_hole_value()) return {};
  return result;
}
References CHECK_EQ, v8::internal::DCHECK(), DCHECK_GE, v8::internal::index, v8::internal::IsFastElementsKind(), v8::internal::IsSmiOrObjectElementsKind(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, and USE.
Referenced by v8::internal::compiler::JSArrayRef::GetOwnCowElement().
TryGetPropertyCell()
std::optional< Tagged< PropertyCell > > v8::internal::ConcurrentLookupIterator::TryGetPropertyCell (Isolate * isolate, LocalIsolate * local_isolate, DirectHandle< JSGlobalObject > holder, DirectHandle< Name > name) [static]
Definition at line 1646 of file lookup.cc.
                                                                  {
  DisallowGarbageCollection no_gc;
  Tagged<Map> holder_map = holder->map();
  if (holder_map->is_access_check_needed()) return {};
  if (holder_map->has_named_interceptor()) return {};
  Tagged<GlobalDictionary> dict = holder->global_dictionary(kAcquireLoad);
  std::optional<Tagged<PropertyCell>> maybe_cell =
      dict->TryFindPropertyCellForConcurrentLookupIterator(isolate, name,
                                                           kRelaxedLoad);
  if (!maybe_cell.has_value()) return {};
  Tagged<PropertyCell> cell = maybe_cell.value();
  if (cell->property_details(kAcquireLoad).kind() == PropertyKind::kAccessor) {
    Tagged<Object> maybe_accessor_pair = cell->value(kAcquireLoad);
    if (!IsAccessorPair(maybe_accessor_pair)) return {};
    std::optional<Tagged<Name>> maybe_cached_property_name =
        FunctionTemplateInfo::TryGetCachedPropertyName(
            isolate,
            Cast<AccessorPair>(maybe_accessor_pair)->getter(kAcquireLoad));
    if (!maybe_cached_property_name.has_value()) return {};
    maybe_cell = dict->TryFindPropertyCellForConcurrentLookupIterator(
        isolate, direct_handle(*maybe_cached_property_name, local_isolate),
        kRelaxedLoad);
    if (!maybe_cell.has_value()) return {};
    cell = maybe_cell.value();
    if (cell->property_details(kAcquireLoad).kind() != PropertyKind::kData)
      return {};
  }
  DCHECK(maybe_cell.has_value());
  DCHECK_EQ(cell->property_details(kAcquireLoad).kind(), PropertyKind::kData);
  return cell;
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::kAccessor, v8::kAcquireLoad, v8::internal::kData, v8::kRelaxedLoad, v8::internal::name, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::FunctionTemplateInfo::TryGetCachedPropertyName().
Referenced by v8::internal::compiler::JSGlobalObjectRef::GetPropertyCell().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/lookup.h
/mnt/V8SourceCode/src/objects/lookup.cc