v8::internal::maglev::LoadTaggedFieldForContextSlot Class Reference
#include <maglev-ir.h>
Public Member Functions
LoadTaggedFieldForContextSlot (uint64_t bitfield, const int offset)
int offset () const
Input & context ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
Static Public Attributes
static constexpr OpProperties kProperties
static constexpr Base::InputTypes kInputTypes {ValueRepresentation::kTagged}
static constexpr int kContextIndex = 0
Private Types
using Base = FixedInputValueNodeT< 1, LoadTaggedFieldForContextSlot >
Private Attributes
const int offset_
Additional Inherited Members
Detailed Description
Definition at line 8170 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::LoadTaggedFieldForContextSlot::Base = FixedInputValueNodeT<1, LoadTaggedFieldForContextSlot> [private]
Definition at line 8172 of file maglev-ir.h.
Constructor & Destructor Documentation
LoadTaggedFieldForContextSlot()
v8::internal::maglev::LoadTaggedFieldForContextSlot::LoadTaggedFieldForContextSlot (uint64_t bitfield, const int offset) [inline], [explicit]
Definition at line 8175 of file maglev-ir.h.
      : Base(bitfield), offset_(offset) {}
Member Function Documentation
context()
Input& v8::internal::maglev::LoadTaggedFieldForContextSlot::context () [inline]
Definition at line 8188 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::LoadTaggedFieldForContextSlot::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::LoadTaggedFieldForContextSlot::MaxCallStackArgs () const [inline]
Definition at line 8190 of file maglev-ir.h.
{ return 0; }
offset()
int v8::internal::maglev::LoadTaggedFieldForContextSlot::offset () const [inline]
Definition at line 8184 of file maglev-ir.h.
{ return offset_; }
Referenced by PrintParams(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
options()
auto v8::internal::maglev::LoadTaggedFieldForContextSlot::options () const [inline]
Definition at line 8195 of file maglev-ir.h.
{ return std::tuple{offset()}; }
PrintParams()
void v8::internal::maglev::LoadTaggedFieldForContextSlot::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8186 of file maglev-ir.cc.
                                                               {
  os << "(0x" << std::hex << offset() << std::dec << ")";
}
References offset().
SetValueLocationConstraints()
void v8::internal::maglev::LoadTaggedFieldForContextSlot::SetValueLocationConstraints ()
Member Data Documentation
kContextIndex
constexpr int v8::internal::maglev::LoadTaggedFieldForContextSlot::kContextIndex = 0 [static], [constexpr]
Definition at line 8187 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::LoadTaggedFieldForContextSlot::kInputTypes {ValueRepresentation::kTagged} [static], [constexpr]
Definition at line 8182 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::LoadTaggedFieldForContextSlot::kProperties [static], [constexpr]
Initial value:
= OpProperties::CanRead() |
                                              OpProperties::CanAllocate() |
                                              OpProperties::DeferredCall()
Definition at line 8178 of file maglev-ir.h.
offset_
const int v8::internal::maglev::LoadTaggedFieldForContextSlot::offset_ [private]
Definition at line 8200 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc