v8::internal::compiler::PipelineStatisticsBase::CommonStats Class Reference
#include <pipeline-statistics.h>
Public Member Functions
CommonStats ()
CommonStats (const CommonStats &)=delete
CommonStats & operator= (const CommonStats &)=delete
void Begin (PipelineStatisticsBase *pipeline_stats)
void End (PipelineStatisticsBase *pipeline_stats, CompilationStatistics::BasicStats *diff)
Public Attributes
std::unique_ptr< ZoneStats::StatsScope > scope_
base::ElapsedTimer timer_
size_t outer_zone_initial_size_
size_t allocated_bytes_at_start_
size_t graph_size_at_start_ = 0
Detailed Description
Definition at line 45 of file pipeline-statistics.h.
Constructor & Destructor Documentation
CommonStats() [1/2]
v8::internal::compiler::PipelineStatisticsBase::CommonStats::CommonStats () [inline]
Definition at line 47 of file pipeline-statistics.h.
: outer_zone_initial_size_(0) {}
CommonStats() [2/2]
v8::internal::compiler::PipelineStatisticsBase::CommonStats::CommonStats (const CommonStats &) [delete]
Member Function Documentation
Begin()
void v8::internal::compiler::PipelineStatisticsBase::CommonStats::Begin (PipelineStatisticsBase * pipeline_stats)
Definition at line 18 of file pipeline-statistics.cc.
                                            {
  DCHECK(!scope_);
  scope_.reset(new ZoneStats::StatsScope(pipeline_stats->zone_stats_));
  outer_zone_initial_size_ = pipeline_stats->OuterZoneSize();
  allocated_bytes_at_start_ =
      outer_zone_initial_size_ -
      pipeline_stats->total_stats_.outer_zone_initial_size_ +
      pipeline_stats->zone_stats_->GetCurrentAllocatedBytes();
  // TODO(pthier): Move turboshaft specifics out of common class.
  // TODO(nicohartmann): This is a bit more difficult to do cleanly here without
  // the use of contextual variables. Add proper Turboshaft statistics in a
  // follow up CL.
  //
  // if (turboshaft::PipelineData::HasScope()) {
  // graph_size_at_start_ =
  // turboshaft::PipelineData::Get().graph().number_of_operations();
  // }
  timer_.Start();
}
References allocated_bytes_at_start_, v8::internal::DCHECK(), v8::internal::compiler::ZoneStats::GetCurrentAllocatedBytes(), outer_zone_initial_size_, v8::internal::compiler::PipelineStatisticsBase::OuterZoneSize(), scope_, v8::base::ElapsedTimer::Start(), timer_, v8::internal::compiler::PipelineStatisticsBase::total_stats_, and v8::internal::compiler::PipelineStatisticsBase::zone_stats_.
Referenced by v8::internal::compiler::PipelineStatisticsBase::BeginPhase(), v8::internal::compiler::PipelineStatisticsBase::BeginPhaseKind(), and v8::internal::compiler::PipelineStatisticsBase::PipelineStatisticsBase().
End()
void v8::internal::compiler::PipelineStatisticsBase::CommonStats::End (PipelineStatisticsBase * pipeline_stats, CompilationStatistics::BasicStats * diff)
Definition at line 39 of file pipeline-statistics.cc.
                                           {
  DCHECK(scope_);
  diff->function_name_ = pipeline_stats->function_name_;
  diff->delta_ = timer_.Elapsed();
  size_t outer_zone_diff =
      pipeline_stats->OuterZoneSize() - outer_zone_initial_size_;
  diff->max_allocated_bytes_ = outer_zone_diff + scope_->GetMaxAllocatedBytes();
  diff->absolute_max_allocated_bytes_ =
      diff->max_allocated_bytes_ + allocated_bytes_at_start_;
  diff->total_allocated_bytes_ =
      outer_zone_diff + scope_->GetTotalAllocatedBytes();
  diff->input_graph_size_ = graph_size_at_start_;
  // TODO(nicohartmann): This is a bit more difficult to do cleanly here without
  // the use of contextual variables. Add proper Turboshaft statistics in a
  // follow up CL.
  //
  // if (turboshaft::PipelineData::HasScope()) {
  // diff->output_graph_size_ =
  // turboshaft::PipelineData::Get().graph().number_of_operations();
  // }
  scope_.reset();
  timer_.Stop();
}
References v8::internal::CompilationStatistics::BasicStats::absolute_max_allocated_bytes_, v8::internal::DCHECK(), v8::internal::CompilationStatistics::BasicStats::delta_, v8::internal::compiler::PipelineStatisticsBase::function_name_, v8::internal::CompilationStatistics::BasicStats::function_name_, v8::internal::CompilationStatistics::BasicStats::input_graph_size_, v8::internal::CompilationStatistics::BasicStats::max_allocated_bytes_, v8::internal::compiler::PipelineStatisticsBase::OuterZoneSize(), and v8::internal::CompilationStatistics::BasicStats::total_allocated_bytes_.
Referenced by v8::internal::compiler::PipelineStatisticsBase::EndPhase(), v8::internal::compiler::PipelineStatisticsBase::EndPhaseKind(), and v8::internal::compiler::PipelineStatisticsBase::~PipelineStatisticsBase().
operator=()
CommonStats& v8::internal::compiler::PipelineStatisticsBase::CommonStats::operator= (const CommonStats &) [delete]
Member Data Documentation
allocated_bytes_at_start_
size_t v8::internal::compiler::PipelineStatisticsBase::CommonStats::allocated_bytes_at_start_
Definition at line 58 of file pipeline-statistics.h.
Referenced by Begin().
graph_size_at_start_
size_t v8::internal::compiler::PipelineStatisticsBase::CommonStats::graph_size_at_start_ = 0
Definition at line 59 of file pipeline-statistics.h.
outer_zone_initial_size_
size_t v8::internal::compiler::PipelineStatisticsBase::CommonStats::outer_zone_initial_size_
Definition at line 57 of file pipeline-statistics.h.
Referenced by Begin().
scope_
std::unique_ptr<ZoneStats::StatsScope> v8::internal::compiler::PipelineStatisticsBase::CommonStats::scope_
Definition at line 55 of file pipeline-statistics.h.
Referenced by Begin(), v8::internal::compiler::PipelineStatisticsBase::InPhase(), and v8::internal::compiler::PipelineStatisticsBase::InPhaseKind().
timer_
base::ElapsedTimer v8::internal::compiler::PipelineStatisticsBase::CommonStats::timer_
Definition at line 56 of file pipeline-statistics.h.
Referenced by Begin().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/pipeline-statistics.h
/mnt/V8SourceCode/src/compiler/pipeline-statistics.cc