v8::internal::MarkingWorklists Class Reference
#include <marking-worklist.h>
Public Member Functions
MarkingWorklists ()=default
~MarkingWorklists ()=default
MarkingWorklist * shared ()
MarkingWorklist * on_hold ()
MarkingWorklist * other ()
const std::vector< ContextWorklistPair > & context_worklists () const
void CreateContextWorklists (const std::vector< Address > &contexts)
void ReleaseContextWorklists ()
bool IsUsingContextWorklists () const
void Clear ()
void Print ()
Local (MarkingWorklists *global, std::unique_ptr< CppMarkingState > cpp_marking_state=kNoCppMarkingState)
~Local ()=default
void Push (Tagged< HeapObject > object)
bool Pop (Tagged< HeapObject > *object)
void PushOnHold (Tagged< HeapObject > object)
bool PopOnHold (Tagged< HeapObject > *object)
void Publish ()
bool IsEmpty ()
bool IsWrapperEmpty () const
void ShareWork ()
void PublishWork ()
void MergeOnHold ()
void PublishCppHeapObjects ()
Address Context () const
Address SwitchToContext (Address context)
bool IsPerContextMode () const
CppMarkingState * cpp_marking_state () const
Address SwitchToSharedForTesting ()
Static Public Attributes
static constexpr Address kSharedContext = 0
static constexpr Address kOtherContext = 8
static constexpr std::nullptr_t kNoCppMarkingState = nullptr
Private Member Functions
void PrintWorklist (const char *worklist_name, MarkingWorklist *worklist)
void SwitchToContextImpl (Address context, MarkingWorklist::Local *worklist)
bool PopContext (Tagged< HeapObject > *object)
Address SwitchToContextSlow (Address context)
Private Attributes
MarkingWorklist shared_
MarkingWorklist on_hold_
std::vector< ContextWorklistPair > context_worklists_
MarkingWorklist other_
MarkingWorklist::Local * active_
MarkingWorklist::Local shared_
MarkingWorklist::Local on_hold_
Address active_context_
const bool is_per_context_mode_
std::vector< MarkingWorklist::Local > context_worklists_
AddressToIndexHashMap worklist_by_context_
MarkingWorklist::Local other_
std::unique_ptr< CppMarkingState > cpp_marking_state_
Detailed Description
Definition at line 68 of file marking-worklist.h.
Constructor & Destructor Documentation
MarkingWorklists()
v8::internal::MarkingWorklists::MarkingWorklists () [default]
 MarkingWorklists()
v8::internal::MarkingWorklists::~MarkingWorklists () [default]
 Local()
v8::internal::MarkingWorklists::~Local () [default]
Member Function Documentation
Clear()
void v8::internal::MarkingWorklists::Clear ()
Definition at line 24 of file marking-worklist.cc.
                             {
  shared_.Clear();
  on_hold_.Clear();
  other_.Clear();
  for (auto& cw : context_worklists_) {
    cw.worklist->Clear();
  }
  ReleaseContextWorklists();
}
References heap::base::Worklist< EntryType, MinSegmentSize >::Clear(), context_worklists_, on_hold_, other_, ReleaseContextWorklists(), and shared_.
Referenced by v8::internal::MarkCompactCollector::TearDown().
Context()
Address v8::internal::MarkingWorklists::Context () const [inline]
Definition at line 168 of file marking-worklist.h.
{ return active_context_; }
context_worklists()
const std::vector<ContextWorklistPair>& v8::internal::MarkingWorklists::context_worklists () const [inline]
Definition at line 89 of file marking-worklist.h.
                                                                  {
    return context_worklists_;
  }
Referenced by v8::internal::ConcurrentMarking::GetMajorMaxConcurrency().
cpp_marking_state()
CppMarkingState* v8::internal::MarkingWorklists::cpp_marking_state () const [inline]
Definition at line 172 of file marking-worklist.h.
                                             {
    return cpp_marking_state_.get();
  }
CreateContextWorklists()
void v8::internal::MarkingWorklists::CreateContextWorklists (const std::vector< Address > & contexts)
Definition at line 39 of file marking-worklist.cc.
                                        {
  DCHECK(context_worklists_.empty());
  if (contexts.empty()) return;
  context_worklists_.reserve(contexts.size());
  for (Address context : contexts) {
    context_worklists_.push_back(
        {context, std::make_unique<MarkingWorklist>()});
  }
}
References context_worklists_, and v8::internal::DCHECK().
Referenced by v8::internal::MarkCompactCollector::StartMarking().
IsEmpty()
bool v8::internal::MarkingWorklists::IsEmpty ()
IsPerContextMode()
bool v8::internal::MarkingWorklists::IsPerContextMode () const [inline]
Definition at line 170 of file marking-worklist.h.
{ return is_per_context_mode_; }
IsUsingContextWorklists()
bool v8::internal::MarkingWorklists::IsUsingContextWorklists () const [inline]
Definition at line 98 of file marking-worklist.h.
{ return !context_worklists_.empty(); }
Referenced by v8::internal::ConcurrentMarking::GetMinorMaxConcurrency().
IsWrapperEmpty()
bool v8::internal::MarkingWorklists::IsWrapperEmpty () const
Local()
v8::internal::MarkingWorklists::Local (MarkingWorklists * global, std::unique_ptr< CppMarkingState > cpp_marking_state = kNoCppMarkingState) [explicit]
Referenced by v8::internal::ConcurrentMarking::RunMajor(), and v8::internal::MarkingBarrier::Write().
MergeOnHold()
void v8::internal::MarkingWorklists::MergeOnHold ()
on_hold()
MarkingWorklist* v8::internal::MarkingWorklists::on_hold () [inline]
Definition at line 84 of file marking-worklist.h.
{ return &on_hold_; }
other()
MarkingWorklist* v8::internal::MarkingWorklists::other () [inline]
Definition at line 85 of file marking-worklist.h.
{ return &other_; }
Referenced by v8::internal::ConcurrentMarking::GetMajorMaxConcurrency(), and v8::internal::ConcurrentMarking::GetMinorMaxConcurrency().
Pop()
bool v8::internal::MarkingWorklists::Pop (Tagged< HeapObject > * object) [inline]
PopContext()
bool v8::internal::MarkingWorklists::PopContext (Tagged< HeapObject > * object) [private]
PopOnHold()
bool v8::internal::MarkingWorklists::PopOnHold (Tagged< HeapObject > * object) [inline]
Print()
void v8::internal::MarkingWorklists::Print ()
Definition at line 34 of file marking-worklist.cc.
                             {
  PrintWorklist("shared", &shared_);
  PrintWorklist("on_hold", &on_hold_);
}
References on_hold_, PrintWorklist(), and shared_.
PrintWorklist()
void v8::internal::MarkingWorklists::PrintWorklist (const char * worklist_name, MarkingWorklist * worklist) [private]
Definition at line 53 of file marking-worklist.cc.
                                                                {
#ifdef DEBUG
  std::map<InstanceType, int> count;
  int total_count = 0;
  worklist->Iterate([&count, &total_count](Tagged<HeapObject> obj) {
    ++total_count;
    count[obj->map()->instance_type()]++;
  });
  std::vector<std::pair<int, InstanceType>> rank;
  rank.reserve(count.size());
  for (const auto& i : count) {
    rank.emplace_back(i.second, i.first);
  }
  std::map<InstanceType, std::string> instance_type_name;
#define INSTANCE_TYPE_NAME(name) instance_type_name[name] = #name;
  INSTANCE_TYPE_LIST(INSTANCE_TYPE_NAME)
#undef INSTANCE_TYPE_NAME
  std::sort(rank.begin(), rank.end(),
            std::greater<std::pair<int, InstanceType>>());
  PrintF("Worklist %s: %d\n", worklist_name, total_count);
  for (auto i : rank) {
    PrintF(" [%s]: %d\n", instance_type_name[i.second].c_str(), i.first);
  }
#endif
}
References v8::internal::greater, INSTANCE_TYPE_LIST, heap::base::Worklist< EntryType, MinSegmentSize >::Iterate(), v8::internal::PrintF(), and v8::base::sort().
Referenced by Print().
Publish()
void v8::internal::MarkingWorklists::Publish ()
PublishCppHeapObjects()
void v8::internal::MarkingWorklists::PublishCppHeapObjects () [inline]
PublishWork()
void v8::internal::MarkingWorklists::PublishWork ()
Push()
void v8::internal::MarkingWorklists::Push (Tagged< HeapObject > object) [inline]
PushOnHold()
void v8::internal::MarkingWorklists::PushOnHold (Tagged< HeapObject > object) [inline]
ReleaseContextWorklists()
void v8::internal::MarkingWorklists::ReleaseContextWorklists ()
Definition at line 51 of file marking-worklist.cc.
{ context_worklists_.clear(); }
References context_worklists_.
Referenced by Clear(), and v8::internal::MarkCompactCollector::Finish().
shared()
MarkingWorklist* v8::internal::MarkingWorklists::shared () [inline]
Definition at line 83 of file marking-worklist.h.
{ return &shared_; }
Referenced by v8::internal::ConcurrentMarking::GetMajorMaxConcurrency(), v8::internal::ConcurrentMarking::GetMinorMaxConcurrency(), and v8::internal::ConcurrentMarking::IsWorkLeft().
ShareWork()
void v8::internal::MarkingWorklists::ShareWork ()
SwitchToContext()
Address v8::internal::MarkingWorklists::SwitchToContext (Address context) [inline]
SwitchToContextImpl()
void v8::internal::MarkingWorklists::SwitchToContextImpl (Address context, MarkingWorklist::Local * worklist) [inline], [private]
SwitchToContextSlow()
Address v8::internal::MarkingWorklists::SwitchToContextSlow (Address context) [private]
SwitchToSharedForTesting()
Address v8::internal::MarkingWorklists::SwitchToSharedForTesting ()
Member Data Documentation
active_
MarkingWorklist::Local* v8::internal::MarkingWorklists::active_ [private]
Definition at line 186 of file marking-worklist.h.
active_context_
Address v8::internal::MarkingWorklists::active_context_ [private]
Definition at line 189 of file marking-worklist.h.
context_worklists_ [1/2]
std::vector<ContextWorklistPair> v8::internal::MarkingWorklists::context_worklists_ [private]
Definition at line 118 of file marking-worklist.h.
Referenced by Clear(), CreateContextWorklists(), and ReleaseContextWorklists().
context_worklists_ [2/2]
std::vector<MarkingWorklist::Local> v8::internal::MarkingWorklists::context_worklists_ [private]
Definition at line 192 of file marking-worklist.h.
cpp_marking_state_
std::unique_ptr<CppMarkingState> v8::internal::MarkingWorklists::cpp_marking_state_ [private]
Definition at line 195 of file marking-worklist.h.
is_per_context_mode_
const bool v8::internal::MarkingWorklists::is_per_context_mode_ [private]
Definition at line 190 of file marking-worklist.h.
kNoCppMarkingState
constexpr std::nullptr_t v8::internal::MarkingWorklists::kNoCppMarkingState = nullptr [static], [constexpr]
Definition at line 136 of file marking-worklist.h.
kOtherContext
static constexpr Address v8::internal::MarkingWorklists::kOtherContext = 8 [static], [constexpr]
Definition at line 76 of file marking-worklist.h.
kSharedContext
static constexpr Address v8::internal::MarkingWorklists::kSharedContext = 0 [static], [constexpr]
Definition at line 75 of file marking-worklist.h.
Referenced by v8::internal::MemoryMeasurement::FinishProcessing().
on_hold_ [1/2]
MarkingWorklist v8::internal::MarkingWorklists::on_hold_ [private]
Definition at line 115 of file marking-worklist.h.
Referenced by Clear(), and Print().
on_hold_ [2/2]
MarkingWorklist::Local v8::internal::MarkingWorklists::on_hold_ [private]
Definition at line 188 of file marking-worklist.h.
other_ [1/2]
MarkingWorklist v8::internal::MarkingWorklists::other_ [private]
Definition at line 121 of file marking-worklist.h.
Referenced by Clear().
other_ [2/2]
MarkingWorklist::Local v8::internal::MarkingWorklists::other_ [private]
Definition at line 194 of file marking-worklist.h.
shared_ [1/2]
MarkingWorklist v8::internal::MarkingWorklists::shared_ [private]
Definition at line 109 of file marking-worklist.h.
Referenced by Clear(), and Print().
shared_ [2/2]
MarkingWorklist::Local v8::internal::MarkingWorklists::shared_ [private]
Definition at line 187 of file marking-worklist.h.
worklist_by_context_
AddressToIndexHashMap v8::internal::MarkingWorklists::worklist_by_context_ [private]
Definition at line 193 of file marking-worklist.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/marking-worklist.h
/mnt/V8SourceCode/src/heap/marking-worklist.cc