v8::internal::SparseBitVector::Iterator Class Reference
#include <sparse-bit-vector.h>
Classes
struct EndTag
Public Member Functions
Iterator (EndTag)
Iterator (const Segment *segment)
int operator* () const
bool operator== (const Iterator &other) const
bool operator!= (const Iterator &other) const
void operator++ ()
Private Attributes
const Segment * segment_ = nullptr
int bit_in_segment_ = 0
Additional Inherited Members
Detailed Description
Definition at line 45 of file sparse-bit-vector.h.
Constructor & Destructor Documentation
Iterator() [1/2]
v8::internal::SparseBitVector::Iterator::Iterator (EndTag) [inline], [explicit]
Definition at line 49 of file sparse-bit-vector.h.
{}
Iterator() [2/2]
v8::internal::SparseBitVector::Iterator::Iterator (const Segment * segment) [inline], [explicit]
Definition at line 50 of file sparse-bit-vector.h.
                                              {
      // {segment} is {&first_segment_}, so cannot be null initially.
      do {
        for (int word = 0; word < kNumWordsPerSegment; ++word) {
          if (segment->words[word] == 0) continue;
          int bit_in_word =
              base::bits::CountTrailingZeros(segment->words[word]);
          segment_ = segment;
          bit_in_segment_ = word * kBitsPerWord + bit_in_word;
          return;
        }
        segment = segment->next;
      } while (segment != nullptr);
      DCHECK_IMPLIES(!segment_, *this == Iterator{EndTag{}});
      DCHECK_IMPLIES(segment_,
                     contains(segment_, segment_->offset + bit_in_segment_));
    }
References bit_in_segment_, v8::internal::SparseBitVector::contains(), v8::base::bits::CountTrailingZeros(), DCHECK_IMPLIES, v8::internal::SparseBitVector::kBitsPerWord, v8::internal::SparseBitVector::kNumWordsPerSegment, v8::internal::SparseBitVector::Segment::next, v8::internal::SparseBitVector::Segment::offset, segment_, and v8::internal::SparseBitVector::Segment::words.
Member Function Documentation
operator!=()
bool v8::internal::SparseBitVector::Iterator::operator!= (const Iterator & other) const [inline]
Definition at line 80 of file sparse-bit-vector.h.
{ return !(*this == other); }
operator*()
int v8::internal::SparseBitVector::Iterator::operator* () const [inline]
Definition at line 68 of file sparse-bit-vector.h.
                          {
      DCHECK_NOT_NULL(segment_);
      int offset = segment_->offset + bit_in_segment_;
      DCHECK(contains(segment_, offset));
      return offset;
    }
References bit_in_segment_, v8::internal::SparseBitVector::contains(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::SparseBitVector::Segment::offset, and segment_.
operator++()
void v8::internal::SparseBitVector::Iterator::operator++ () [inline]
Definition at line 82 of file sparse-bit-vector.h.
                      {
      int word = bit_in_segment_ / kBitsPerWord;
      int bit_in_word = bit_in_segment_ % kBitsPerWord;
      if (bit_in_word < kBitsPerWord - 1) {
        uintptr_t remaining_bits =
            segment_->words[word] &
            (std::numeric_limits<uintptr_t>::max() << (1 + bit_in_word));
        if (remaining_bits) {
          int next_bit_in_word = base::bits::CountTrailingZeros(remaining_bits);
          DCHECK_LT(bit_in_word, next_bit_in_word);
          bit_in_segment_ = word * kBitsPerWord + next_bit_in_word;
          return;
        }
      }
      // No remaining bits in the current word. Search in succeeding words and
      // segments.
      ++word;
      do {
        for (; word < kNumWordsPerSegment; ++word) {
          if (segment_->words[word] == 0) continue;
          bit_in_word = base::bits::CountTrailingZeros(segment_->words[word]);
          bit_in_segment_ = word * kBitsPerWord + bit_in_word;
          return;
        }
        segment_ = segment_->next;
        word = 0;
      } while (segment_);
      // If we reach here, there are no more bits.
      bit_in_segment_ = 0;
      DCHECK_EQ(*this, Iterator{EndTag{}});
    }
References bit_in_segment_, v8::base::bits::CountTrailingZeros(), DCHECK_EQ, DCHECK_LT, v8::internal::SparseBitVector::kBitsPerWord, v8::internal::SparseBitVector::kNumWordsPerSegment, v8::internal::SparseBitVector::Segment::next, segment_, and v8::internal::SparseBitVector::Segment::words.
operator==()
bool v8::internal::SparseBitVector::Iterator::operator== (const Iterator & other) const [inline]
Definition at line 75 of file sparse-bit-vector.h.
                                                 {
      return segment_ == other.segment_ &&
             bit_in_segment_ == other.bit_in_segment_;
    }
References bit_in_segment_, and segment_.
Member Data Documentation
bit_in_segment_
int v8::internal::SparseBitVector::Iterator::bit_in_segment_ = 0 [private]
Definition at line 116 of file sparse-bit-vector.h.
Referenced by Iterator(), operator*(), operator++(), and operator==().
segment_
const Segment* v8::internal::SparseBitVector::Iterator::segment_ = nullptr [private]
Definition at line 115 of file sparse-bit-vector.h.
Referenced by Iterator(), operator*(), operator++(), and operator==().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/utils/sparse-bit-vector.h