v8::internal::anonymous_namespace{traced-handles.cc}::ParallelWeakHandlesProcessor< Derived >::Job Class Reference
Public Member Functions
Job (Derived &derived)
void Run (JobDelegate *delegate) override
size_t GetMaxConcurrency (size_t worker_count) const override
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Private Member Functions
template<bool IsMainThread>
void RunImpl (JobDelegate *delegate)
Private Attributes
Derived & derived_
Detailed Description
template<typename Derived>
class v8::internal::anonymous_namespace{traced-handles.cc}::ParallelWeakHandlesProcessor< Derived >::Job
Definition at line 387 of file traced-handles.cc.
Constructor & Destructor Documentation
Job()
template<typename Derived >
v8::internal::anonymous_namespace{traced-handles.cc}::ParallelWeakHandlesProcessor< Derived >::Job::Job (Derived & derived) [inline], [explicit]
Definition at line 389 of file traced-handles.cc.
: derived_(derived) {}
Member Function Documentation
GetMaxConcurrency()
template<typename Derived >
size_t v8::internal::anonymous_namespace{traced-handles.cc}::ParallelWeakHandlesProcessor< Derived >::Job::GetMaxConcurrency (size_t worker_count) const [inline], [override], [virtual]
Controls the maximum number of threads calling Run() concurrently, given the number of threads currently assigned to this job and executing Run().
Run() is only invoked if the number of threads previously running Run() was less than the value returned. In general, this should return the latest number of incomplete work items (smallest unit of work) left to process, including items that are currently in progress. |worker_count| is the number of threads currently assigned to this job which some callers may need to determine their return value. Since GetMaxConcurrency() is a leaf function, it must not call back any JobHandle methods.
Implements v8::JobTask.
Definition at line 405 of file traced-handles.cc.
                                                                 {
      const auto processed_young_blocks =
          derived_.processed_young_blocks_.load(std::memory_order_relaxed);
      if (derived_.num_young_blocks_ < processed_young_blocks) {
        return 0;
      }
      if (!v8_flags.parallel_reclaim_unmodified_wrappers) {
        return 1;
      }
      const auto blocks_left =
          derived_.num_young_blocks_ - processed_young_blocks;
      constexpr size_t kMaxParallelTasks = 3;
      constexpr size_t kBlocksPerTask = 8;
      const auto wanted_tasks =
          (blocks_left + (kBlocksPerTask - 1)) / kBlocksPerTask;
      return std::min(kMaxParallelTasks, wanted_tasks);
    }
References v8::internal::v8_flags.
Run()
template<typename Derived >
void v8::internal::anonymous_namespace{traced-handles.cc}::ParallelWeakHandlesProcessor< Derived >::Job::Run (JobDelegate * delegate) [inline], [override], [virtual]
Implements v8::JobTask.
Definition at line 391 of file traced-handles.cc.
                                             {
      if (delegate->IsJoiningThread()) {
        TRACE_GC_WITH_FLOW(derived_.heap()->tracer(), Derived::kMainThreadScope,
                           derived_.trace_id_, TRACE_EVENT_FLAG_FLOW_IN);
        RunImpl</*IsMainThread=*/true>(delegate);
      } else {
        TRACE_GC_EPOCH_WITH_FLOW(derived_.heap()->tracer(),
                                 Derived::kBackgroundThreadScope,
                                 ThreadKind::kBackground, derived_.trace_id_,
                                 TRACE_EVENT_FLAG_FLOW_IN);
        RunImpl</*IsMainThread=*/false>(delegate);
      }
    }
References v8::JobDelegate::IsJoiningThread(), v8::internal::kBackground, TRACE_EVENT_FLAG_FLOW_IN, TRACE_GC_EPOCH_WITH_FLOW, and TRACE_GC_WITH_FLOW.
RunImpl()
template<typename Derived >
template<bool IsMainThread>
void v8::internal::anonymous_namespace{traced-handles.cc}::ParallelWeakHandlesProcessor< Derived >::Job::RunImpl (JobDelegate * delegate) [inline], [private]
Definition at line 425 of file traced-handles.cc.
                                        {
      // The following logic parallelizes the handling of the doubly-linked
      // list. We basically race through the list from begin() with acquiring
      // exclusive access by incrementing a single counter.
      auto it = derived_.young_blocks_.begin();
      size_t current = 0;
      for (size_t index = derived_.processed_young_blocks_.fetch_add(
               1, std::memory_order_relaxed);
           index < derived_.num_young_blocks_;
           index = derived_.processed_young_blocks_.fetch_add(
               +1, std::memory_order_relaxed)) {
        while (current < index) {
          it++;
          current++;
        }
        TracedNodeBlock* block = *it;
        DCHECK(block->InYoungList());
        derived_.template ProcessBlock<IsMainThread>(block);
        // TracedNodeBlock is the minimum granularity of processing.
        if (delegate->ShouldYield()) {
          return;
        }
      }
    }
References v8::internal::DCHECK(), v8::internal::index, v8::internal::TracedNodeBlock::InYoungList(), and v8::JobDelegate::ShouldYield().
Member Data Documentation
derived_
template<typename Derived >
Derived& v8::internal::anonymous_namespace{traced-handles.cc}::ParallelWeakHandlesProcessor< Derived >::Job::derived_ [private]
Definition at line 450 of file traced-handles.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/handles/traced-handles.cc