v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor Class Reference
Public Member Functions
UpdatePointersVisitor (Isolate *isolate, const HeapObjectMap *moves)
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) final
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) final
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) final
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) final
void VisitMapPointer (Tagged< HeapObject > host) final
void VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) final
void VisitIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerMode mode) final
void VisitTrustedPointerTableEntry (Tagged< HeapObject > host, IndirectPointerSlot slot) final
void VisitRootPointers (Root root, const char *description, OffHeapObjectSlot start, OffHeapObjectSlot end) override
Private Member Functions
void ProcessSlot (Root root, FullObjectSlot slot)
void ProcessSlot (Tagged< HeapObject > host, MaybeObjectSlot slot)
void LogUpdatedPointer (Root root, FullObjectSlot slot, Tagged< HeapObject > old_slot_value, Tagged< HeapObject > new_slot_value)
void LogUpdatedPointer (Tagged< HeapObject > host, MaybeObjectSlot slot, Tagged< HeapObject > old_slot_value, Tagged< HeapObject > new_slot_value)
void LogUpdatedExternalPointerTableEntry (Tagged< HeapObject > host, ExternalPointerSlot slot, Address slot_value)
void LogUpdatedCodePointerTableEntry (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerHandle old_handle, IndirectPointerHandle new_handle)
void RecordProcessedSlotIfDebug (Address slot_address) const
Private Attributes
Isolate *const isolate_
const HeapObjectMap * moves_
Additional Inherited Members
Detailed Description
Definition at line 529 of file read-only-promotion.cc.
Constructor & Destructor Documentation
UpdatePointersVisitor()
v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::UpdatePointersVisitor (Isolate * isolate, const HeapObjectMap * moves) [inline]
Definition at line 531 of file read-only-promotion.cc.
        : isolate_(isolate), moves_(moves) {
#ifdef V8_ENABLE_SANDBOX
      for (auto [_src, dst] : *moves_) {
        promoted_objects_.emplace(dst);
        if (IsCode(dst)) {
          PromoteCodePointerEntryFor(Cast<Code>(dst));
        }
      }
#endif // V8_ENABLE_SANDBOX
    }
Member Function Documentation
LogUpdatedCodePointerTableEntry()
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::LogUpdatedCodePointerTableEntry (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerHandle old_handle, IndirectPointerHandle new_handle) [inline], [private]
Definition at line 719 of file read-only-promotion.cc.
                                                                           {
      std::cout << "ro-promotion: updated code pointer table entry {host "
                << reinterpret_cast<void*>(host.address()) << " slot "
                << reinterpret_cast<void*>(slot.address()) << " from "
                << AsHex(old_handle, 8, true) << " to "
                << AsHex(new_handle, 8, true) << "}\n";
    }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), and v8::internal::Tagged< HeapObject >::address().
LogUpdatedExternalPointerTableEntry()
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::LogUpdatedExternalPointerTableEntry (Tagged< HeapObject > host, ExternalPointerSlot slot, Address slot_value) [inline], [private]
Definition at line 711 of file read-only-promotion.cc.
                                                                 {
      std::cout << "ro-promotion: updated external pointer slot {host "
                << reinterpret_cast<void*>(host.address()) << " slot "
                << reinterpret_cast<void*>(slot.address()) << " slot_value "
                << reinterpret_cast<void*>(slot_value) << "}\n";
    }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), and v8::internal::Tagged< HeapObject >::address().
LogUpdatedPointer() [1/2]
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::LogUpdatedPointer (Root root, FullObjectSlot slot, Tagged< HeapObject > old_slot_value, Tagged< HeapObject > new_slot_value) [inline], [private]
Definition at line 693 of file read-only-promotion.cc.
                                                              {
      std::cout << "ro-promotion: updated pointer {root "
                << static_cast<int>(root) << " slot "
                << reinterpret_cast<void*>(slot.address()) << " from "
                << reinterpret_cast<void*>(old_slot_value.ptr()) << " to "
                << reinterpret_cast<void*>(new_slot_value.ptr()) << "}\n";
    }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
LogUpdatedPointer() [2/2]
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::LogUpdatedPointer (Tagged< HeapObject > host, MaybeObjectSlot slot, Tagged< HeapObject > old_slot_value, Tagged< HeapObject > new_slot_value) [inline], [private]
Definition at line 702 of file read-only-promotion.cc.
                                                              {
      std::cout << "ro-promotion: updated pointer {host "
                << reinterpret_cast<void*>(host.address()) << " slot "
                << reinterpret_cast<void*>(slot.address()) << " from "
                << reinterpret_cast<void*>(old_slot_value.ptr()) << " to "
                << reinterpret_cast<void*>(new_slot_value.ptr()) << "}\n";
    }
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), v8::internal::Tagged< HeapObject >::address(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
ProcessSlot() [1/2]
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::ProcessSlot (Root root, FullObjectSlot slot) [inline], [private]
Definition at line 618 of file read-only-promotion.cc.
                                                     {
      Tagged<Object> old_slot_value_obj = slot.load(isolate_);
#ifdef V8_ENABLE_DIRECT_HANDLE
      if (old_slot_value_obj.ptr() == kTaggedNullAddress) return;
#endif
      if (!IsHeapObject(old_slot_value_obj)) return;
      Tagged<HeapObject> old_slot_value = Cast<HeapObject>(old_slot_value_obj);
      auto it = moves_->find(old_slot_value);
      if (it == moves_->end()) return;
      Tagged<HeapObject> new_slot_value = it->second;
      slot.store(new_slot_value);
      if (V8_UNLIKELY(v8_flags.trace_read_only_promotion_verbose)) {
        LogUpdatedPointer(root, slot, old_slot_value, new_slot_value);
      }
    }
References v8::internal::IsHeapObject(), v8::internal::kTaggedNullAddress, v8::internal::FullObjectSlot::load(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::FullObjectSlot::store(), v8::internal::v8_flags, and V8_UNLIKELY.
ProcessSlot() [2/2]
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::ProcessSlot (Tagged< HeapObject > host, MaybeObjectSlot slot) [inline], [private]
Definition at line 633 of file read-only-promotion.cc.
                                                                    {
      Tagged<HeapObject> old_slot_value;
      if (!slot.load(isolate_).GetHeapObject(&old_slot_value)) return;
      auto it = moves_->find(old_slot_value);
      if (it == moves_->end()) return;
      Tagged<HeapObject> new_slot_value = it->second;
      slot.store(new_slot_value);
      if (V8_UNLIKELY(v8_flags.trace_read_only_promotion_verbose)) {
        LogUpdatedPointer(host, slot, old_slot_value, new_slot_value);
      }
    }
References v8::internal::FullMaybeObjectSlot::load(), v8::internal::FullMaybeObjectSlot::store(), v8::internal::v8_flags, and V8_UNLIKELY.
RecordProcessedSlotIfDebug()
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::RecordProcessedSlotIfDebug (Address slot_address) const [inline], [private]
Definition at line 738 of file read-only-promotion.cc.
{}
VisitExternalPointer()
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 569 of file read-only-promotion.cc.
                                                              {
#ifdef V8_ENABLE_SANDBOX
      if (promoted_objects_.find(host) == promoted_objects_.end()) return;
      // If we reach here, `host` is a moved object with external pointer slots
      // located in RO space. To preserve the 1:1 relation between slots and
      // table entries, allocate a new entry (in
      // read_only_external_pointer_space) now.
      RecordProcessedSlotIfDebug(slot.address());
      Address slot_value = slot.load(isolate_);
      DCHECK(slot.ExactTagIsKnown());
      slot.init(isolate_, host, slot_value, slot.exact_tag());
      if (V8_UNLIKELY(v8_flags.trace_read_only_promotion_verbose)) {
        LogUpdatedExternalPointerTableEntry(host, slot, slot_value);
      }
#endif // V8_ENABLE_SANDBOX
    }
References v8::internal::DCHECK(), v8::internal::v8_flags, and V8_UNLIKELY.
VisitIndirectPointer()
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::VisitIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerMode mode) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 588 of file read-only-promotion.cc.
                                                              {
#ifdef V8_ENABLE_SANDBOX
      if (slot.tag() == kCodeIndirectPointerTag) {
        VisitCodePointer(host, slot);
      }
#endif // V8_ENABLE_SANDBOX
    }
VisitInstructionStreamPointer()
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 562 of file read-only-promotion.cc.
                                                                         {
      // InstructionStream objects never move to RO space.
    }
VisitMapPointer()
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::VisitMapPointer (Tagged< HeapObject > host) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 566 of file read-only-promotion.cc.
                                                        {
      ProcessSlot(host, host->RawMaybeWeakField(HeapObject::kMapOffset));
    }
References v8::internal::HeapObject::kMapOffset.
VisitPointers() [1/2]
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 552 of file read-only-promotion.cc.
                                                  {
      for (MaybeObjectSlot slot = start; slot < end; slot++) {
        ProcessSlot(host, slot);
      }
    }
References v8::internal::compiler::end().
VisitPointers() [2/2]
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 558 of file read-only-promotion.cc.
                                             {
      VisitPointers(host, MaybeObjectSlot(start), MaybeObjectSlot(end));
    }
References v8::internal::compiler::end().
VisitRootPointers() [1/2]
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 544 of file read-only-promotion.cc.
                                                                           {
      for (FullObjectSlot slot = start; slot < end; slot++) {
        ProcessSlot(root, slot);
      }
    }
References v8::internal::compiler::end().
VisitRootPointers() [2/2]
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::VisitRootPointers (Root root, const char * description, OffHeapObjectSlot start, OffHeapObjectSlot end) [inline], [override], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 604 of file read-only-promotion.cc.
                                                           {
      // We shouldn't have moved any string table contents or SharedStructType
      // registry contents (which is what OffHeapObjectSlot currently refers
      // to).
      for (OffHeapObjectSlot slot = start; slot < end; slot++) {
        Tagged<Object> o = slot.load(isolate_);
        if (!IsHeapObject(o)) continue;
        CHECK(!Contains(*moves_, Cast<HeapObject>(o)));
      }
    }
References CHECK, v8::internal::anonymous_namespace{read-only-promotion.cc}::Contains(), v8::internal::compiler::end(), and v8::internal::IsHeapObject().
VisitTrustedPointerTableEntry()
void v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::VisitTrustedPointerTableEntry (Tagged< HeapObject > host, IndirectPointerSlot slot) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 596 of file read-only-promotion.cc.
                                                                       {
#ifdef V8_ENABLE_SANDBOX
      if (slot.tag() == kCodeIndirectPointerTag) {
        VisitCodePointer(host, slot);
      }
#endif // V8_ENABLE_SANDBOX
    }
Member Data Documentation
isolate_
Isolate* const v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::isolate_ [private]
Definition at line 741 of file read-only-promotion.cc.
moves_
const HeapObjectMap* v8::internal::anonymous_namespace{read-only-promotion.cc}::ReadOnlyPromotionImpl::UpdatePointersVisitor::moves_ [private]
Definition at line 742 of file read-only-promotion.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/read-only-promotion.cc