heap::base::SmoothedBytesAndDuration Class Reference
#include <bytes.h>
Public Member Functions
SmoothedBytesAndDuration (v8::base::TimeDelta decay)
void Update (BytesAndDuration bytes_and_duration)
double GetThroughput () const
double GetThroughput (v8::base::TimeDelta delay) const
Private Member Functions
double Decay (double throughput, v8::base::TimeDelta delay) const
Private Attributes
double throughput_ = 0.0
const v8::base::TimeDelta decay_
Detailed Description
Definition at line 59 of file bytes.h.
Constructor & Destructor Documentation
SmoothedBytesAndDuration()
heap::base::SmoothedBytesAndDuration::SmoothedBytesAndDuration (v8::base::TimeDelta decay) [inline], [explicit]
Definition at line 61 of file bytes.h.
      : decay_(decay) {}
Member Function Documentation
Decay()
double heap::base::SmoothedBytesAndDuration::Decay (double throughput, v8::base::TimeDelta delay) const [inline], [private]
Definition at line 82 of file bytes.h.
                                                               {
    return throughput *
           exp2(-delay.InMillisecondsF() / decay_.InMillisecondsF());
  }
References decay_, and v8::base::TimeDelta::InMillisecondsF().
Referenced by GetThroughput(), and Update().
GetThroughput() [1/2]
double heap::base::SmoothedBytesAndDuration::GetThroughput () const [inline]
Definition at line 74 of file bytes.h.
{ return throughput_; }
References throughput_.
GetThroughput() [2/2]
double heap::base::SmoothedBytesAndDuration::GetThroughput (v8::base::TimeDelta delay) const [inline]
Definition at line 77 of file bytes.h.
                                                    {
    return Decay(throughput_, delay);
  }
References Decay(), and throughput_.
Update()
void heap::base::SmoothedBytesAndDuration::Update (BytesAndDuration bytes_and_duration) [inline]
Definition at line 64 of file bytes.h.
                                                   {
    if (bytes_and_duration.duration.IsZero()) {
      return;
    }
    const double new_throughput = bytes_and_duration.bytes /
                                  bytes_and_duration.duration.InMillisecondsF();
    throughput_ = new_throughput + Decay(throughput_ - new_throughput,
                                         bytes_and_duration.duration);
  }
References heap::base::BytesAndDuration::bytes, Decay(), heap::base::BytesAndDuration::duration, v8::base::TimeDelta::InMillisecondsF(), v8::base::TimeDelta::IsZero(), and throughput_.
Referenced by v8::internal::GCTracer::SampleAllocation().
Member Data Documentation
decay_
const v8::base::TimeDelta heap::base::SmoothedBytesAndDuration::decay_ [private]
Definition at line 88 of file bytes.h.
Referenced by Decay().
throughput_
double heap::base::SmoothedBytesAndDuration::throughput_ = 0.0 [private]
Definition at line 87 of file bytes.h.
Referenced by GetThroughput(), and Update().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/base/bytes.h