v8::internal::AssemblerBase Class Reference
#include <assembler.h>
Classes
class CodeComment
Public Member Functions
AssemblerBase (const AssemblerOptions &options, std::unique_ptr< AssemblerBuffer >)
virtual ~AssemblerBase ()
const AssemblerOptions & options () const
bool predictable_code_size () const
void set_predictable_code_size (bool value)
uint64_t enabled_cpu_features () const
void set_enabled_cpu_features (uint64_t features)
bool IsEnabled (CpuFeature f)
void EnableCpuFeature (CpuFeature f)
bool is_constant_pool_available () const
JumpOptimizationInfo * jump_optimization_info ()
void set_jump_optimization_info (JumpOptimizationInfo *jump_opt)
void FinalizeJumpOptimizationInfo ()
int pc_offset () const
int pc_offset_for_safepoint ()
uint8_t * buffer_start () const
int buffer_size () const
int instruction_size () const
std::unique_ptr< AssemblerBuffer > ReleaseBuffer ()
virtual void AbortedCodeGeneration ()
void Print (Isolate *isolate)
void RecordComment (const char *comment, const SourceLocation &loc=SourceLocation::Current())
void RecordComment (std::string comment, const SourceLocation &loc=SourceLocation::Current())
Static Public Member Functions
static void QuietNaN (Tagged< HeapObject > nan)
Static Public Attributes
static constexpr int kMinimalBufferSize = 128
static constexpr int kDefaultBufferSize = 4 * KB
Protected Types
using EmbeddedObjectIndex = size_t
Protected Member Functions
int AddCodeTarget (IndirectHandle< Code > target)
IndirectHandle< Code > GetCodeTarget (intptr_t code_target_index) const
EmbeddedObjectIndex AddEmbeddedObject (IndirectHandle< HeapObject > object)
IndirectHandle< HeapObject > GetEmbeddedObject (EmbeddedObjectIndex index) const
void set_constant_pool_available (bool available)
void RequestHeapNumber (HeapNumberRequest request)
bool ShouldRecordRelocInfo (RelocInfo::Mode rmode) const
Protected Attributes
std::unique_ptr< AssemblerBuffer > buffer_
uint8_t * buffer_start_
std::forward_list< HeapNumberRequest > heap_number_requests_
uint8_t * pc_
CodeCommentsWriter code_comments_writer_
Private Attributes
std::vector< IndirectHandle< Code > > code_targets_
std::vector< IndirectHandle< HeapObject > > embedded_objects_
std::unordered_map< IndirectHandle< HeapObject >, EmbeddedObjectIndex, IndirectHandle< HeapObject >::hash, IndirectHandle< HeapObject >::equal_to > embedded_objects_map_
const AssemblerOptions options_
uint64_t enabled_cpu_features_
bool predictable_code_size_
bool constant_pool_available_
JumpOptimizationInfo * jump_optimization_info_
Friends
class FrameAndConstantPoolScope
class ConstantPoolUnavailableScope
Detailed Description
Definition at line 333 of file assembler.h.
Member Typedef Documentation
EmbeddedObjectIndex
using v8::internal::AssemblerBase::EmbeddedObjectIndex = size_t [protected]
Definition at line 499 of file assembler.h.
Constructor & Destructor Documentation
AssemblerBase()
v8::internal::AssemblerBase::AssemblerBase (const AssemblerOptions & options, std::unique_ptr< AssemblerBuffer > buffer)
Definition at line 180 of file assembler.cc.
    : buffer_(std::move(buffer)),
      options_(options),
      enabled_cpu_features_(0),
      predictable_code_size_(false),
      constant_pool_available_(false),
      jump_optimization_info_(nullptr) {
  if (!buffer_) buffer_ = NewAssemblerBuffer(kDefaultBufferSize);
  buffer_start_ = buffer_->start();
  pc_ = buffer_start_;
}
References buffer_, buffer_start_, kDefaultBufferSize, v8::internal::NewAssemblerBuffer(), and pc_.
 AssemblerBase()
v8::internal::AssemblerBase::~AssemblerBase () [virtual], [default]
Member Function Documentation
AbortedCodeGeneration()
virtual void v8::internal::AssemblerBase::AbortedCodeGeneration () [inline], [virtual]
Reimplemented in v8::internal::Assembler, v8::internal::Assembler, and v8::internal::Assembler.
Definition at line 410 of file assembler.h.
{}
AddCodeTarget()
int v8::internal::AssemblerBase::AddCodeTarget (IndirectHandle< Code > target) [protected]
Definition at line 266 of file assembler.cc.
                                                            {
  int current = static_cast<int>(code_targets_.size());
  if (current > 0 && !target.is_null() &&
      code_targets_.back().address() == target.address()) {
    // Optimization if we keep jumping to the same code target.
    return current - 1;
  } else {
    code_targets_.push_back(target);
    return current;
  }
}
References v8::internal::HandleBase::address(), code_targets_, and v8::internal::HandleBase::is_null().
AddEmbeddedObject()
AssemblerBase::EmbeddedObjectIndex v8::internal::AssemblerBase::AddEmbeddedObject (IndirectHandle< HeapObject > object) [protected]
Definition at line 284 of file assembler.cc.
                                       {
  EmbeddedObjectIndex current = embedded_objects_.size();
  // Do not deduplicate invalid handles, they are to heap object requests.
  if (!object.is_null()) {
    auto entry = embedded_objects_map_.find(object);
    if (entry != embedded_objects_map_.end()) {
      return entry->second;
    }
    embedded_objects_map_[object] = current;
  }
  embedded_objects_.push_back(object);
  return current;
}
References embedded_objects_, and embedded_objects_map_.
Referenced by v8::internal::Assembler::AllocateAndInstallRequestedHeapNumbers(), v8::internal::MacroAssembler::CallBuiltin(), v8::internal::MacroAssembler::li(), and v8::internal::MacroAssembler::TailCallBuiltin().
buffer_size()
int v8::internal::AssemblerBase::buffer_size () const [inline]
Definition at line 396 of file assembler.h.
{ return buffer_->size(); }
Referenced by v8::internal::CodeDesc::Initialize().
buffer_start()
uint8_t* v8::internal::AssemblerBase::buffer_start () const [inline]
Definition at line 395 of file assembler.h.
{ return buffer_->start(); }
Referenced by v8::internal::CodeDesc::Initialize().
EnableCpuFeature()
void v8::internal::AssemblerBase::EnableCpuFeature (CpuFeature f) [inline]
Definition at line 355 of file assembler.h.
                                      {
    enabled_cpu_features_ |= (static_cast<uint64_t>(1) << f);
  }
enabled_cpu_features()
uint64_t v8::internal::AssemblerBase::enabled_cpu_features () const [inline]
Definition at line 344 of file assembler.h.
{ return enabled_cpu_features_; }
FinalizeJumpOptimizationInfo()
void v8::internal::AssemblerBase::FinalizeJumpOptimizationInfo () [inline]
Definition at line 377 of file assembler.h.
{}
GetCodeTarget()
IndirectHandle< Code > v8::internal::AssemblerBase::GetCodeTarget (intptr_t code_target_index) const [protected]
Definition at line 278 of file assembler.cc.
                                      {
  DCHECK_LT(static_cast<size_t>(code_target_index), code_targets_.size());
  return code_targets_[code_target_index];
}
References code_targets_, and DCHECK_LT.
Referenced by v8::internal::Assembler::code_target_object_handle_at(), and v8::internal::Assembler::relative_code_target_object_handle_at().
GetEmbeddedObject()
IndirectHandle< HeapObject > v8::internal::AssemblerBase::GetEmbeddedObject (EmbeddedObjectIndex index) const [protected]
Definition at line 299 of file assembler.cc.
                                     {
  DCHECK_LT(index, embedded_objects_.size());
  return embedded_objects_[index];
}
References DCHECK_LT, embedded_objects_, and v8::internal::index.
Referenced by v8::internal::Assembler::code_target_object_handle_at(), v8::internal::Assembler::compressed_embedded_object_handle_at(), v8::internal::Assembler::embedded_object_handle_at(), and v8::internal::Assembler::target_object_handle_at().
instruction_size()
int v8::internal::AssemblerBase::instruction_size () const [inline]
Definition at line 397 of file assembler.h.
{ return pc_offset(); }
Referenced by v8::internal::Assembler::GetCode(), and v8::internal::CodeDesc::Initialize().
is_constant_pool_available()
bool v8::internal::AssemblerBase::is_constant_pool_available () const [inline]
Definition at line 359 of file assembler.h.
                                          {
    if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
      // We need to disable constant pool here for embeded builtins
      // because the metadata section is not adjacent to instructions
      return constant_pool_available_ && !options().isolate_independent_code;
    } else {
      // Embedded constant pool not supported on this architecture.
      UNREACHABLE();
    }
  }
References v8::internal::AssemblerOptions::isolate_independent_code, v8::internal::UNREACHABLE(), and V8_EMBEDDED_CONSTANT_POOL_BOOL.
IsEnabled()
bool v8::internal::AssemblerBase::IsEnabled (CpuFeature f) [inline]
Definition at line 352 of file assembler.h.
                               {
    return (enabled_cpu_features_ & (static_cast<uint64_t>(1) << f)) != 0;
  }
jump_optimization_info()
JumpOptimizationInfo* v8::internal::AssemblerBase::jump_optimization_info () [inline]
Definition at line 370 of file assembler.h.
                                                 {
    return jump_optimization_info_;
  }
options()
const AssemblerOptions& v8::internal::AssemblerBase::options () const [inline]
Definition at line 339 of file assembler.h.
{ return options_; }
Referenced by v8::internal::MacroAssembler::CallBuiltin(), v8::internal::MacroAssembler::CallRuntime(), v8::internal::Assembler::ConstantPoolAddEntry(), v8::internal::MacroAssembler::ExternalReferenceAsOperand(), v8::internal::MacroAssembler::li(), v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchSimulatorStackLimit(), v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchStackPointerAndSimulatorStackLimit(), v8::internal::MacroAssembler::TailCallBuiltin(), and v8::internal::Assembler::WriteCodeComments().
pc_offset()
int v8::internal::AssemblerBase::pc_offset () const [inline]
Definition at line 383 of file assembler.h.
{ return static_cast<int>(pc_ - buffer_start_); }
Referenced by v8::internal::Assembler::Align(), v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::compiler::CodeGenerator::AssembleInstruction(), v8::internal::Assembler::bind(), v8::internal::Assembler::bind_to(), v8::internal::Assembler::BlockTrampolinePoolBefore(), v8::internal::Assembler::BlockTrampolinePoolFor(), v8::internal::Assembler::branch_long_offset(), v8::internal::Assembler::branch_offset(), v8::internal::Assembler::branch_offset_helper(), v8::internal::MacroAssembler::CallCFunctionHelper(), v8::internal::Assembler::CheckTrampolinePool(), v8::internal::Assembler::CheckTrampolinePoolQuick(), v8::internal::Assembler::cmpi_optimization(), v8::internal::MacroAssembler::ComputeCodeStartAddress(), v8::internal::Assembler::ConstantPoolAddEntry(), v8::internal::Assembler::DataAlign(), v8::internal::Assembler::db(), v8::internal::Assembler::dd(), v8::internal::Assembler::dq(), v8::internal::SafepointTableBuilder::Emit(), v8::internal::MaglevSafepointTableBuilder::Emit(), v8::internal::Assembler::emit(), v8::internal::Assembler::emit_disp(), v8::internal::Assembler::emit_near_disp(), v8::internal::Assembler::emit_prefix(), v8::internal::HandlerTable::EmitReturnTableStart(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::EmitStore(), v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::EmitStore< std::memory_order_relaxed >(), v8::internal::Assembler::GetCode(), v8::internal::Assembler::GrowBuffer(), v8::internal::Assembler::is_near(), v8::internal::Assembler::is_near_branch(), v8::internal::Assembler::jump_address(), v8::internal::MacroAssembler::Lb(), v8::internal::MacroAssembler::Lbu(), v8::internal::MacroAssembler::Lh(), v8::internal::MacroAssembler::Lhu(), v8::internal::Assembler::LinkAndGetBranchInstructionOffsetTo(), v8::internal::MacroAssembler::Ll(), v8::internal::MacroAssembler::LoadDouble(), v8::internal::MacroAssembler::LoadFloat(), v8::internal::wasm::LiftoffAssembler::LoadLane(), v8::internal::wasm::LiftoffAssembler::LoadTransform(), v8::internal::MacroAssembler::Lw(), v8::internal::wasm::LiftoffAssembler::PatchPrepareStackFrame(), v8::internal::SharedMacroAssemblerBase::PinsrHelper(), v8::internal::wasm::LiftoffAssembler::PrepareStackFrame(), RequestHeapNumber(), v8::internal::MacroAssembler::Sb(), v8::internal::MacroAssembler::Sc(), v8::internal::MacroAssembler::Sh(), v8::internal::Assembler::SizeOfCodeGeneratedSince(), v8::internal::wasm::LiftoffAssembler::Store(), v8::internal::MacroAssembler::StoreDouble(), v8::internal::MacroAssembler::StoreFloat(), v8::internal::MacroAssembler::StoreLane(), v8::internal::wasm::LiftoffAssembler::StoreLane(), v8::internal::wasm::LiftoffAssembler::StoreTaggedPointer(), v8::internal::MacroAssembler::Sw(), v8::internal::Assembler::TrackBranch(), v8::internal::Assembler::WriteCodeComments(), v8::internal::wasm::GetProtectedInstruction< kLoadOrStore, kExtraEmittedInstructions >::~GetProtectedInstruction(), and v8::internal::PatchingAssembler::~PatchingAssembler().
pc_offset_for_safepoint()
int v8::internal::AssemblerBase::pc_offset_for_safepoint () [inline]
Definition at line 385 of file assembler.h.
                                {
#if defined(V8_TARGET_ARCH_MIPS64) || defined(V8_TARGET_ARCH_LOONG64)
    // MIPS and LOONG need to use their own implementation to avoid trampoline's
    // influence.
    UNREACHABLE();
#else
    return pc_offset();
#endif
  }
References v8::internal::UNREACHABLE().
predictable_code_size()
bool v8::internal::AssemblerBase::predictable_code_size () const [inline]
Definition at line 341 of file assembler.h.
{ return predictable_code_size_; }
Print()
void v8::internal::AssemblerBase::Print (Isolate * isolate)
Definition at line 195 of file assembler.cc.
                                          {
  StdoutStream os;
  v8::internal::Disassembler::Decode(isolate, os, buffer_start_, pc_);
}
References buffer_start_, v8::internal::Disassembler::Decode(), and pc_.
QuietNaN()
static void v8::internal::AssemblerBase::QuietNaN (Tagged< HeapObject > nan) [inline], [static]
Definition at line 381 of file assembler.h.
{}
Referenced by v8::internal::Isolate::Init().
RecordComment() [1/2]
void v8::internal::AssemblerBase::RecordComment (const char * comment, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 417 of file assembler.h.
                                                           {
    // Set explicit dependency on --code-comments for dead-code elimination in
    // release builds.
    if (!v8_flags.code_comments) return;
    if (options().emit_code_comments) {
      std::string comment_str(comment);
      if (loc.FileName()) {
        comment_str += " - " + loc.ToString();
      }
      code_comments_writer_.Add(pc_offset(), comment_str);
    }
  }
References v8::SourceLocation::FileName(), v8::internal::loc, v8::internal::string, v8::SourceLocation::ToString(), and v8::internal::v8_flags.
Referenced by v8::internal::MacroAssembler::Abort(), v8::internal::compiler::CodeGenerator::AssembleCode(), v8::internal::compiler::CodeGenerator::AssembleSourcePosition(), v8::internal::CallApiFunctionAndReturn(), v8::internal::SafepointTableBuilder::Emit(), v8::internal::MaglevSafepointTableBuilder::Emit(), v8::internal::maglev::MaglevCodeGenerator::EmitCode(), v8::internal::maglev::MaglevAssembler::EmitEagerDeopt(), v8::internal::maglev::MaglevAssembler::EmitEagerDeoptIf(), v8::internal::maglev::MaglevAssembler::EmitEagerDeoptIfNotSmi(), v8::internal::maglev::MaglevAssembler::EmitEagerDeoptIfSmi(), v8::internal::HandlerTable::EmitReturnTableStart(), v8::internal::maglev::MaglevAssembler::JumpToDeferredIf(), and v8::internal::wasm::LiftoffAssembler::PatchPrepareStackFrame().
RecordComment() [2/2]
void v8::internal::AssemblerBase::RecordComment (std::string comment, const SourceLocation & loc = SourceLocation::Current()) [inline]
Definition at line 432 of file assembler.h.
                                                           {
    // Set explicit dependency on --code-comments for dead-code elimination in
    // release builds.
    if (!v8_flags.code_comments) return;
    if (options().emit_code_comments) {
      std::string comment_str(comment);
      if (loc.FileName()) {
        comment_str += " - " + loc.ToString();
      }
      code_comments_writer_.Add(pc_offset(), comment_str);
    }
  }
References v8::SourceLocation::FileName(), v8::internal::loc, v8::internal::string, v8::SourceLocation::ToString(), and v8::internal::v8_flags.
ReleaseBuffer()
std::unique_ptr<AssemblerBuffer> v8::internal::AssemblerBase::ReleaseBuffer () [inline]
Definition at line 399 of file assembler.h.
                                                 {
    std::unique_ptr<AssemblerBuffer> buffer = std::move(buffer_);
    DCHECK_NULL(buffer_);
    // Reset fields to prevent accidental further modifications of the buffer.
    buffer_start_ = nullptr;
    pc_ = nullptr;
    return buffer;
  }
References DCHECK_NULL.
RequestHeapNumber()
void v8::internal::AssemblerBase::RequestHeapNumber (HeapNumberRequest request) [protected]
Definition at line 261 of file assembler.cc.
                                                               {
  request.set_offset(pc_offset());
  heap_number_requests_.push_front(request);
}
References heap_number_requests_, pc_offset(), and v8::internal::HeapNumberRequest::set_offset().
Referenced by v8::internal::Assembler::emit(), and v8::internal::MacroAssembler::li().
set_constant_pool_available()
void v8::internal::AssemblerBase::set_constant_pool_available (bool available) [inline], [protected]
Definition at line 512 of file assembler.h.
                                                   {
    if (V8_EMBEDDED_CONSTANT_POOL_BOOL) {
      constant_pool_available_ = available;
    } else {
      // Embedded constant pool not supported on this architecture.
      UNREACHABLE();
    }
  }
References available(), v8::internal::UNREACHABLE(), and V8_EMBEDDED_CONSTANT_POOL_BOOL.
Referenced by v8::internal::ConstantPoolUnavailableScope::ConstantPoolUnavailableScope(), and v8::internal::FrameAndConstantPoolScope::FrameAndConstantPoolScope().
set_enabled_cpu_features()
void v8::internal::AssemblerBase::set_enabled_cpu_features (uint64_t features) [inline]
Definition at line 345 of file assembler.h.
                                                   {
    enabled_cpu_features_ = features;
  }
set_jump_optimization_info()
void v8::internal::AssemblerBase::set_jump_optimization_info (JumpOptimizationInfo * jump_opt) [inline]
Definition at line 373 of file assembler.h.
                                                                  {
    jump_optimization_info_ = jump_opt;
  }
set_predictable_code_size()
void v8::internal::AssemblerBase::set_predictable_code_size (bool value) [inline]
Definition at line 342 of file assembler.h.
{ predictable_code_size_ = value; }
References v8::internal::value.
ShouldRecordRelocInfo()
bool v8::internal::AssemblerBase::ShouldRecordRelocInfo (RelocInfo::Mode rmode) const [inline], [protected]
Definition at line 528 of file assembler.h.
                                                        {
    DCHECK(!RelocInfo::IsNoInfo(rmode));
    if (RelocInfo::IsOnlyForSerializer(rmode) &&
        !options().record_reloc_info_for_serialization &&
        !v8_flags.debug_code && !v8_flags.slow_debug_code) {
      return false;
    }
    return true;
  }
References v8::internal::DCHECK(), v8::internal::RelocInfo::IsNoInfo(), v8::internal::RelocInfo::IsOnlyForSerializer(), and v8::internal::v8_flags.
Referenced by v8::internal::Assembler::RecordRelocInfo().
Friends And Related Function Documentation
ConstantPoolUnavailableScope
friend class ConstantPoolUnavailableScope [friend]
Definition at line 579 of file assembler.h.
FrameAndConstantPoolScope
friend class FrameAndConstantPoolScope [friend]
Definition at line 578 of file assembler.h.
Member Data Documentation
buffer_
std::unique_ptr<AssemblerBuffer> v8::internal::AssemblerBase::buffer_ [protected]
Definition at line 504 of file assembler.h.
Referenced by v8::internal::Assembler::Assembler(), AssemblerBase(), v8::internal::Assembler::GetCode(), v8::internal::Assembler::GrowBuffer(), and v8::internal::PatchingAssembler::~PatchingAssembler().
buffer_start_
uint8_t* v8::internal::AssemblerBase::buffer_start_ [protected]
Definition at line 506 of file assembler.h.
Referenced by v8::internal::Assembler::AllocateAndInstallRequestedHeapNumbers(), v8::internal::Assembler::Assembler(), AssemblerBase(), v8::internal::Assembler::branch_long_offset(), v8::internal::Assembler::branch_offset_helper(), v8::internal::Assembler::CheckTrampolinePool(), v8::internal::Assembler::dd(), v8::internal::Assembler::GrowBuffer(), v8::internal::Assembler::instr_at(), v8::internal::Assembler::instr_at_put(), v8::internal::Assembler::jump_address(), v8::internal::Assembler::label_at_put(), v8::internal::Assembler::next(), v8::internal::wasm::LiftoffAssembler::PatchPrepareStackFrame(), Print(), v8::internal::Assembler::target_at(), and v8::internal::Assembler::target_at_put().
code_comments_writer_
CodeCommentsWriter v8::internal::AssemblerBase::code_comments_writer_ [protected]
Definition at line 538 of file assembler.h.
Referenced by v8::internal::Assembler::WriteCodeComments().
code_targets_
std::vector<IndirectHandle<Code> > v8::internal::AssemblerBase::code_targets_ [private]
Definition at line 547 of file assembler.h.
Referenced by AddCodeTarget(), and GetCodeTarget().
constant_pool_available_
bool v8::internal::AssemblerBase::constant_pool_available_ [private]
Definition at line 569 of file assembler.h.
embedded_objects_
std::vector<IndirectHandle<HeapObject> > v8::internal::AssemblerBase::embedded_objects_ [private]
Definition at line 553 of file assembler.h.
Referenced by AddEmbeddedObject(), and GetEmbeddedObject().
embedded_objects_map_
std::unordered_map<IndirectHandle<HeapObject>, EmbeddedObjectIndex, IndirectHandle<HeapObject>::hash, IndirectHandle<HeapObject>::equal_to> v8::internal::AssemblerBase::embedded_objects_map_ [private]
Definition at line 561 of file assembler.h.
Referenced by AddEmbeddedObject().
enabled_cpu_features_
uint64_t v8::internal::AssemblerBase::enabled_cpu_features_ [private]
Definition at line 564 of file assembler.h.
heap_number_requests_
std::forward_list<HeapNumberRequest> v8::internal::AssemblerBase::heap_number_requests_ [protected]
Definition at line 507 of file assembler.h.
Referenced by v8::internal::Assembler::AllocateAndInstallRequestedHeapNumbers(), and RequestHeapNumber().
jump_optimization_info_
JumpOptimizationInfo* v8::internal::AssemblerBase::jump_optimization_info_ [private]
Definition at line 571 of file assembler.h.
kDefaultBufferSize
constexpr int v8::internal::AssemblerBase::kDefaultBufferSize = 4 * KB [static], [constexpr]
Definition at line 489 of file assembler.h.
Referenced by AssemblerBase(), and v8::internal::wasm::GenerateLiftoffDebugSideTable().
kMinimalBufferSize
constexpr int v8::internal::AssemblerBase::kMinimalBufferSize = 128 [static], [constexpr]
Definition at line 485 of file assembler.h.
options_
const AssemblerOptions v8::internal::AssemblerBase::options_ [private]
Definition at line 563 of file assembler.h.
pc_
uint8_t* v8::internal::AssemblerBase::pc_ [protected]
Definition at line 510 of file assembler.h.
Referenced by v8::internal::Assembler::Assembler(), AssemblerBase(), v8::internal::Assembler::buffer_space(), v8::internal::Assembler::CheckForEmitInForbiddenSlot(), v8::internal::Assembler::cmpi_optimization(), v8::internal::Assembler::db(), v8::internal::Assembler::dd(), v8::internal::Assembler::dq(), v8::internal::Assembler::emit(), v8::internal::Assembler::emit_b(), v8::internal::Assembler::emit_near_disp(), v8::internal::Assembler::emit_q(), v8::internal::Assembler::emit_w(), v8::internal::Assembler::EmitHelper(), v8::internal::Assembler::GetCode(), v8::internal::Assembler::GrowBuffer(), v8::internal::MacroAssembler::PatchAndJump(), Print(), and v8::internal::Assembler::RecordRelocInfo().
predictable_code_size_
bool v8::internal::AssemblerBase::predictable_code_size_ [private]
Definition at line 565 of file assembler.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/assembler.h
/mnt/V8SourceCode/src/codegen/assembler.cc