v8::internal::TaggedField< T, kFieldOffset, CompressionScheme > Class Template Reference
#include <tagged-field.h>
Public Types
using PtrType = std::conditional_t< std::is_same_v< MapWord, T >, MapWord, Tagged< T > >
Static Public Member Functions
static Address address (Tagged< HeapObject > host, int offset=0)
static PtrType load (Tagged< HeapObject > host, int offset=0)
static PtrType load (PtrComprCageBase cage_base, Tagged< HeapObject > host, int offset=0)
static void store (Tagged< HeapObject > host, PtrType value)
static void store (Tagged< HeapObject > host, int offset, PtrType value)
static PtrType Relaxed_Load (Tagged< HeapObject > host, int offset=0)
static PtrType Relaxed_Load (PtrComprCageBase cage_base, Tagged< HeapObject > host, int offset=0)
static void Relaxed_Store (Tagged< HeapObject > host, PtrType value)
static void Relaxed_Store (Tagged< HeapObject > host, int offset, PtrType value)
static PtrType Acquire_Load (Tagged< HeapObject > host, int offset=0)
static PtrType Acquire_Load_No_Unpack (PtrComprCageBase cage_base, Tagged< HeapObject > host, int offset=0)
static PtrType Acquire_Load (PtrComprCageBase cage_base, Tagged< HeapObject > host, int offset=0)
static PtrType SeqCst_Load (Tagged< HeapObject > host, int offset=0)
static PtrType SeqCst_Load (PtrComprCageBase cage_base, Tagged< HeapObject > host, int offset=0)
static void Release_Store (Tagged< HeapObject > host, PtrType value)
static void Release_Store (Tagged< HeapObject > host, int offset, PtrType value)
static void SeqCst_Store (Tagged< HeapObject > host, PtrType value)
static void SeqCst_Store (Tagged< HeapObject > host, int offset, PtrType value)
static PtrType SeqCst_Swap (Tagged< HeapObject > host, int offset, PtrType value)
static PtrType SeqCst_Swap (PtrComprCageBase cage_base, Tagged< HeapObject > host, int offset, PtrType value)
static Tagged_t Release_CompareAndSwap (Tagged< HeapObject > host, PtrType old, PtrType value)
static Tagged_t Relaxed_CompareAndSwap (Tagged< HeapObject > host, PtrType old, PtrType value)
static PtrType SeqCst_CompareAndSwap (Tagged< HeapObject > host, int offset, PtrType old, PtrType value)
static PtrType Relaxed_Load_Map_Word (PtrComprCageBase cage_base, Tagged< HeapObject > host)
static void Relaxed_Store_Map_Word (Tagged< HeapObject > host, PtrType value)
static void Release_Store_Map_Word (Tagged< HeapObject > host, PtrType value)
Static Public Attributes
static constexpr bool kIsSmi = std::is_same_v<Smi, T>
static constexpr bool kIsHeapObject
Static Private Member Functions
static Tagged_t * location (Tagged< HeapObject > host, int offset=0)
template<typename TOnHeapAddress >
static Address tagged_to_full (TOnHeapAddress on_heap_addr, Tagged_t tagged_value)
static Tagged_t full_to_tagged (Address value)
Detailed Description
template<typename T, int kFieldOffset = 0, typename CompressionScheme = V8HeapCompressionScheme>
class v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >
Definition at line 175 of file tagged-field.h.
Member Typedef Documentation
PtrType
template<typename T , int kFieldOffset = 0, typename CompressionScheme = V8HeapCompressionScheme>
using v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::PtrType = std::conditional_t<std::is_same_v<MapWord, T>, MapWord, Tagged<T> >
Definition at line 192 of file tagged-field.h.
Member Function Documentation
Acquire_Load() [1/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
TaggedField< T, kFieldOffset, CompressionScheme >::PtrType v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Acquire_Load (PtrComprCageBase cage_base, Tagged< HeapObject > host, int offset = 0) [inline], [static]
Definition at line 331 of file tagged-field-inl.h.
                                                                     {
  AtomicTagged_t value = AsAtomicTagged::Acquire_Load(location(host, offset));
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  return PtrType(tagged_to_full(cage_base, value));
}
References v8::base::Acquire_Load(), DCHECK_NE, and v8::internal::value.
Acquire_Load() [2/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
TaggedField< T, kFieldOffset, CompressionScheme >::PtrType v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Acquire_Load (Tagged< HeapObject > host, int offset = 0) [inline], [static]
Definition at line 313 of file tagged-field-inl.h.
                                         {
  AtomicTagged_t value = AsAtomicTagged::Acquire_Load(location(host, offset));
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  return PtrType(tagged_to_full(host.ptr(), value));
}
References v8::base::Acquire_Load(), DCHECK_NE, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::value.
Referenced by v8::internal::SharedFunctionInfo::GetUntrustedData(), v8::internal::TrustedObject::IsProtectedPointerFieldEmpty(), v8::internal::HeapObject::ReadMaybeEmptyTrustedPointerField(), v8::internal::FeedbackVector::SynchronizedGet(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::VisitDescriptorsForMap().
Acquire_Load_No_Unpack()
template<typename T , int kFieldOffset, typename CompressionScheme >
TaggedField< T, kFieldOffset, CompressionScheme >::PtrType v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Acquire_Load_No_Unpack (PtrComprCageBase cage_base, Tagged< HeapObject > host, int offset = 0) [inline], [static]
Definition at line 323 of file tagged-field-inl.h.
                                                                     {
  AtomicTagged_t value = AsAtomicTagged::Acquire_Load(location(host, offset));
  return PtrType(tagged_to_full(cage_base, value));
}
References v8::base::Acquire_Load(), and v8::internal::value.
address()
template<typename T , int kFieldOffset, typename CompressionScheme >
Address v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::address (Tagged< HeapObject > host, int offset = 0) [inline], [static]
Definition at line 169 of file tagged-field-inl.h.
                                         {
  return host.address() + kFieldOffset + offset;
}
References v8::internal::Tagged< HeapObject >::address().
Referenced by v8::internal::HeapObject::map_slot().
full_to_tagged()
template<typename T , int kFieldOffset, typename CompressionScheme >
Tagged_t v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::full_to_tagged (Address value) [inline], [static], [private]
Definition at line 200 of file tagged-field-inl.h.
                   {
#ifdef V8_COMPRESS_POINTERS
  if constexpr (kIsSmi) DCHECK(HAS_SMI_TAG(value));
  return CompressionScheme::CompressObject(value);
#else
  return value;
#endif
}
load() [1/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
TaggedField< T, kFieldOffset, CompressionScheme >::PtrType v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::load (PtrComprCageBase cage_base, Tagged< HeapObject > host, int offset = 0) [inline], [static]
Definition at line 223 of file tagged-field-inl.h.
                                                                     {
  Tagged_t value = *location(host, offset);
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  return PtrType(tagged_to_full(cage_base, value));
}
load() [2/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
TaggedField< T, kFieldOffset, CompressionScheme >::PtrType v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::load (Tagged< HeapObject > host, int offset = 0) [inline], [static]
Definition at line 213 of file tagged-field-inl.h.
                                                                  {
  Tagged_t value = *location(host, offset);
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  return PtrType(tagged_to_full(host.ptr(), value));
}
Referenced by v8::internal::JSFunction::context(), v8::internal::DEF_GETTER(), v8::internal::RegExpData::flags(), v8::internal::Code::has_source_position_table_or_bytecode_offset_table(), v8::internal::TrustedObject::IsProtectedPointerFieldEmpty(), v8::internal::TrustedObject::ReadProtectedPointerField(), and v8::internal::RegExpData::type_tag().
location()
template<typename T , int kFieldOffset, typename CompressionScheme >
Tagged_t * v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::location (Tagged< HeapObject > host, int offset = 0) [inline], [static], [private]
Definition at line 176 of file tagged-field-inl.h.
                                         {
  return reinterpret_cast<Tagged_t*>(address(host, offset));
}
Relaxed_CompareAndSwap()
template<typename T , int kFieldOffset, typename CompressionScheme >
Tagged_t v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_CompareAndSwap (Tagged< HeapObject > host, PtrType old, PtrType value) [inline], [static]
Definition at line 379 of file tagged-field-inl.h.
                                                         {
  Tagged_t old_value = full_to_tagged(old.ptr());
  Tagged_t new_value = full_to_tagged(value.ptr());
  Tagged_t result = AsAtomicTagged::Relaxed_CompareAndSwap(
      location(host), old_value, new_value);
  return result;
}
References v8::base::Relaxed_CompareAndSwap(), v8::base::internal::result, and v8::internal::value.
Referenced by v8::internal::HeapObject::relaxed_compare_and_swap_map_word_forwarded().
Relaxed_Load() [1/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
TaggedField< T, kFieldOffset, CompressionScheme >::PtrType v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load (PtrComprCageBase cage_base, Tagged< HeapObject > host, int offset = 0) [inline], [static]
Definition at line 269 of file tagged-field-inl.h.
                                                                     {
  AtomicTagged_t value = AsAtomicTagged::Relaxed_Load(location(host, offset));
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  return PtrType(tagged_to_full(cage_base, value));
}
References DCHECK_NE, v8::base::Relaxed_Load(), and v8::internal::value.
Relaxed_Load() [2/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
TaggedField< T, kFieldOffset, CompressionScheme >::PtrType v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load (Tagged< HeapObject > host, int offset = 0) [inline], [static]
Definition at line 259 of file tagged-field-inl.h.
                                         {
  AtomicTagged_t value = AsAtomicTagged::Relaxed_Load(location(host, offset));
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  return PtrType(tagged_to_full(host.ptr(), value));
}
Referenced by v8::internal::WeakArrayList::capacity(), v8::internal::DEF_RELAXED_GETTER(), v8::internal::Script::flags(), v8::internal::ScopeInfo::get(), v8::internal::Context::get(), v8::internal::DescriptorArray::GetDetails(), v8::internal::DescriptorArray::GetKey(), v8::internal::DescriptorArray::GetValue(), v8::internal::DescriptorArray::IsInitializedDescriptor(), v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::ObjectSlotValueDependency::IsValid(), v8::internal::JSArray::length(), v8::internal::SwissNameDictionary::LoadFromDataTable(), v8::internal::WeakCell::relaxed_target(), v8::internal::WeakCell::relaxed_unregister_token(), and v8::internal::FastJsonStringifier< Char >::ResumeJSObject().
Relaxed_Load_Map_Word()
template<typename T , int kFieldOffset, typename CompressionScheme >
TaggedField< T, kFieldOffset, CompressionScheme >::PtrType v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Load_Map_Word (PtrComprCageBase cage_base, Tagged< HeapObject > host) [inline], [static]
Definition at line 279 of file tagged-field-inl.h.
                                                         {
  AtomicTagged_t value = AsAtomicTagged::Relaxed_Load(location(host, 0));
  return PtrType(tagged_to_full(cage_base, value));
}
References v8::base::Relaxed_Load(), and v8::internal::value.
Relaxed_Store() [1/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
void v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store (Tagged< HeapObject > host, int offset, PtrType value) [inline], [static]
Definition at line 303 of file tagged-field-inl.h.
                                                        {
  Address ptr = value.ptr();
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  AsAtomicTagged::Relaxed_Store(location(host, offset), full_to_tagged(ptr));
}
References DCHECK_NE, v8::base::Relaxed_Store(), and v8::internal::value.
Relaxed_Store() [2/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
void v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store (Tagged< HeapObject > host, PtrType value) [inline], [static]
Definition at line 294 of file tagged-field-inl.h.
                                            {
  Address ptr = value.ptr();
  DCHECK_NE(kFieldOffset, HeapObject::kMapOffset);
  AsAtomicTagged::Relaxed_Store(location(host), full_to_tagged(ptr));
}
References DCHECK_NE, v8::base::Relaxed_Store(), and v8::internal::value.
Referenced by v8::internal::Script::set_flags(), v8::internal::DescriptorArray::SetDetails(), v8::internal::DescriptorArray::SetKey(), v8::internal::DescriptorArray::SetValue(), v8::internal::WritableJitAllocation::WriteHeaderSlot(), v8::internal::WritableFreeSpace::WriteHeaderSlot(), and v8::internal::WritableJitAllocation::WriteProtectedPointerHeaderSlot().
Relaxed_Store_Map_Word()
template<typename T , int kFieldOffset, typename CompressionScheme >
void v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Relaxed_Store_Map_Word (Tagged< HeapObject > host, PtrType value) [inline], [static]
Definition at line 287 of file tagged-field-inl.h.
                                            {
  AsAtomicTagged::Relaxed_Store(location(host), full_to_tagged(value.ptr()));
}
References v8::base::Relaxed_Store(), and v8::internal::value.
Referenced by v8::internal::HeapObject::set_map_word(), v8::internal::HeapObject::set_map_word_forwarded(), v8::internal::WritableJitAllocation::WriteHeaderSlot(), and v8::internal::WritableFreeSpace::WriteHeaderSlot().
Release_CompareAndSwap()
template<typename T , int kFieldOffset, typename CompressionScheme >
Tagged_t v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_CompareAndSwap (Tagged< HeapObject > host, PtrType old, PtrType value) [inline], [static]
Definition at line 367 of file tagged-field-inl.h.
                                                         {
  Tagged_t old_value = full_to_tagged(old.ptr());
  Tagged_t new_value = full_to_tagged(value.ptr());
  Tagged_t result = AsAtomicTagged::Release_CompareAndSwap(
      location(host), old_value, new_value);
  return result;
}
References v8::base::Release_CompareAndSwap(), v8::base::internal::result, and v8::internal::value.
Referenced by v8::internal::HeapObject::release_compare_and_swap_map_word_forwarded().
Release_Store() [1/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
void v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store (Tagged< HeapObject > host, int offset, PtrType value) [inline], [static]
Definition at line 357 of file tagged-field-inl.h.
                                                        {
  Address ptr = value.ptr();
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  AsAtomicTagged::Release_Store(location(host, offset), full_to_tagged(ptr));
}
References DCHECK_NE, v8::base::Release_Store(), and v8::internal::value.
Release_Store() [2/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
void v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store (Tagged< HeapObject > host, PtrType value) [inline], [static]
Definition at line 340 of file tagged-field-inl.h.
                                            {
  Address ptr = value.ptr();
  DCHECK_NE(kFieldOffset, HeapObject::kMapOffset);
  AsAtomicTagged::Release_Store(location(host), full_to_tagged(ptr));
}
References DCHECK_NE, v8::base::Release_Store(), and v8::internal::value.
Referenced by v8::internal::TrustedObject::ClearProtectedPointerField(), v8::internal::HeapObject::ClearTrustedPointerField(), v8::internal::RELEASE_ACQUIRE_ACCESSORS(), v8::internal::BytecodeArray::SetSourcePositionsFailedToCollect(), v8::internal::SharedFunctionInfo::SetUntrustedData(), v8::internal::FeedbackVector::SynchronizedSet(), v8::internal::WritableJitAllocation::WriteHeaderSlot(), v8::internal::TrustedObject::WriteProtectedPointerField(), v8::internal::WritableJitAllocation::WriteProtectedPointerHeaderSlot(), and v8::internal::HeapObject::WriteTrustedPointerField().
Release_Store_Map_Word()
template<typename T , int kFieldOffset, typename CompressionScheme >
void v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store_Map_Word (Tagged< HeapObject > host, PtrType value) [inline], [static]
Definition at line 349 of file tagged-field-inl.h.
                                            {
  Address ptr = value.ptr();
  AsAtomicTagged::Release_Store(location(host), full_to_tagged(ptr));
}
References v8::base::Release_Store(), and v8::internal::value.
Referenced by v8::internal::HeapObject::set_map_word(), and v8::internal::HeapObject::set_map_word_forwarded().
SeqCst_CompareAndSwap()
template<typename T , int kFieldOffset, typename CompressionScheme >
TaggedField< T, kFieldOffset, CompressionScheme >::PtrType v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_CompareAndSwap (Tagged< HeapObject > host, int offset, PtrType old, PtrType value) [inline], [static]
Definition at line 456 of file tagged-field-inl.h.
                                                                     {
  Address ptr = value.ptr();
  Address old_ptr = old.ptr();
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  AtomicTagged_t old_value = AsAtomicTagged::SeqCst_CompareAndSwap(
      location(host, offset), full_to_tagged(old_ptr), full_to_tagged(ptr));
  return TaggedField<T, kFieldOffset, CompressionScheme>::PtrType(
      tagged_to_full(host.ptr(), old_value));
}
References DCHECK_NE, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::base::SeqCst_CompareAndSwap(), and v8::internal::value.
Referenced by v8::internal::PropertyArray::CompareAndSwap().
SeqCst_Load() [1/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
TaggedField< T, kFieldOffset, CompressionScheme >::PtrType v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_Load (PtrComprCageBase cage_base, Tagged< HeapObject > host, int offset = 0) [inline], [static]
Definition at line 401 of file tagged-field-inl.h.
                                                                     {
  AtomicTagged_t value = AsAtomicTagged::SeqCst_Load(location(host, offset));
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  return PtrType(tagged_to_full(cage_base, value));
}
References DCHECK_NE, v8::base::SeqCst_Load(), and v8::internal::value.
SeqCst_Load() [2/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
TaggedField< T, kFieldOffset, CompressionScheme >::PtrType v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_Load (Tagged< HeapObject > host, int offset = 0) [inline], [static]
Definition at line 391 of file tagged-field-inl.h.
                                         {
  AtomicTagged_t value = AsAtomicTagged::SeqCst_Load(location(host, offset));
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  return PtrType(tagged_to_full(host.ptr(), value));
}
References DCHECK_NE, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::base::SeqCst_Load(), and v8::internal::value.
SeqCst_Store() [1/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
void v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_Store (Tagged< HeapObject > host, int offset, PtrType value) [inline], [static]
Definition at line 419 of file tagged-field-inl.h.
                                                        {
  Address ptr = value.ptr();
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  AsAtomicTagged::SeqCst_Store(location(host, offset), full_to_tagged(ptr));
}
References DCHECK_NE, v8::base::SeqCst_Store(), and v8::internal::value.
SeqCst_Store() [2/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
void v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_Store (Tagged< HeapObject > host, PtrType value) [inline], [static]
Definition at line 410 of file tagged-field-inl.h.
                                            {
  Address ptr = value.ptr();
  DCHECK_NE(kFieldOffset, HeapObject::kMapOffset);
  AsAtomicTagged::SeqCst_Store(location(host), full_to_tagged(ptr));
}
References DCHECK_NE, v8::base::SeqCst_Store(), and v8::internal::value.
SeqCst_Swap() [1/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
TaggedField< T, kFieldOffset, CompressionScheme >::PtrType v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_Swap (PtrComprCageBase cage_base, Tagged< HeapObject > host, int offset, PtrType value) [inline], [static]
Definition at line 443 of file tagged-field-inl.h.
                   {
  Address ptr = value.ptr();
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  AtomicTagged_t old_value =
      AsAtomicTagged::SeqCst_Swap(location(host, offset), full_to_tagged(ptr));
  return PtrType(tagged_to_full(cage_base, old_value));
}
References DCHECK_NE, and v8::internal::value.
SeqCst_Swap() [2/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
TaggedField< T, kFieldOffset, CompressionScheme >::PtrType v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::SeqCst_Swap (Tagged< HeapObject > host, int offset, PtrType value) [inline], [static]
Definition at line 430 of file tagged-field-inl.h.
                                                        {
  Address ptr = value.ptr();
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  AtomicTagged_t old_value =
      AsAtomicTagged::SeqCst_Swap(location(host, offset), full_to_tagged(ptr));
  return PtrType(tagged_to_full(host.ptr(), old_value));
}
References DCHECK_NE, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::value.
Referenced by v8::internal::PropertyArray::Swap().
store() [1/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
void v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::store (Tagged< HeapObject > host, int offset, PtrType value) [inline], [static]
Definition at line 245 of file tagged-field-inl.h.
                                                        {
#ifdef V8_ATOMIC_OBJECT_FIELD_WRITES
  Relaxed_Store(host, offset, value);
#else
  Address ptr = value.ptr();
  DCHECK_NE(kFieldOffset + offset, HeapObject::kMapOffset);
  *location(host, offset) = full_to_tagged(ptr);
#endif
}
store() [2/2]
template<typename T , int kFieldOffset, typename CompressionScheme >
void v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::store (Tagged< HeapObject > host, PtrType value) [inline], [static]
Definition at line 232 of file tagged-field-inl.h.
                                            {
#ifdef V8_ATOMIC_OBJECT_FIELD_WRITES
  Relaxed_Store(host, value);
#else
  Address ptr = value.ptr();
  DCHECK_NE(kFieldOffset, HeapObject::kMapOffset);
  *location(host) = full_to_tagged(ptr);
#endif
}
Referenced by v8::internal::Code::clear_source_position_table_and_bytecode_offset_table(), v8::internal::TrustedObject::ClearProtectedPointerField(), v8::internal::RELEASE_ACQUIRE_ACCESSORS(), v8::internal::RegExpData::set_flags(), v8::internal::RegExpData::set_type_tag(), v8::internal::WasmArray::SetTaggedElement(), v8::internal::WasmStruct::SetTaggedFieldValue(), and v8::internal::TrustedObject::WriteProtectedPointerField().
tagged_to_full()
template<typename T , int kFieldOffset, typename CompressionScheme >
template<typename TOnHeapAddress >
Address v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::tagged_to_full (TOnHeapAddress on_heap_addr, Tagged_t tagged_value) [inline], [static], [private]
Definition at line 184 of file tagged-field-inl.h.
                                                        {
#ifdef V8_COMPRESS_POINTERS
  if constexpr (kIsSmi) {
    DCHECK(HAS_SMI_TAG(tagged_value));
    return CompressionScheme::DecompressTaggedSigned(tagged_value);
  } else {
    return CompressionScheme::DecompressTagged(tagged_value);
  }
#else
  return tagged_value;
#endif
}
References DCHECK, and HAS_SMI_TAG.
Member Data Documentation
kIsHeapObject
template<typename T , int kFieldOffset = 0, typename CompressionScheme = V8HeapCompressionScheme>
constexpr bool v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::kIsHeapObject [static], [constexpr]
Initial value:
=
      is_subtype<T, HeapObject>::value || std::is_same_v<MapWord, T>
Definition at line 186 of file tagged-field.h.
kIsSmi
template<typename T , int kFieldOffset = 0, typename CompressionScheme = V8HeapCompressionScheme>
constexpr bool v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::kIsSmi = std::is_same_v<Smi, T> [static], [constexpr]
Definition at line 181 of file tagged-field.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/tagged-field.h
/mnt/V8SourceCode/src/objects/tagged-field-inl.h