v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreElementParameters Class Reference
Public Member Functions
TransitionAndStoreElementParameters (MapRef double_map, MapRef fast_map)
MapRef double_map () const
MapRef fast_map () const
Private Attributes
MapRef const double_map_
MapRef const fast_map_
Detailed Description
Definition at line 427 of file simplified-operator.cc.
Constructor & Destructor Documentation
TransitionAndStoreElementParameters()
v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreElementParameters::TransitionAndStoreElementParameters (MapRef double_map, MapRef fast_map)
Definition at line 439 of file simplified-operator.cc.
    : double_map_(double_map), fast_map_(fast_map) {}
Member Function Documentation
double_map()
MapRef v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreElementParameters::double_map () const [inline]
Definition at line 431 of file simplified-operator.cc.
{ return double_map_; }
Referenced by v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::hash_value(), v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator<<(), and v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator==().
fast_map()
MapRef v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreElementParameters::fast_map () const [inline]
Definition at line 432 of file simplified-operator.cc.
{ return fast_map_; }
Referenced by v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::hash_value(), v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator<<(), and v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::operator==().
Member Data Documentation
double_map_
MapRef const v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreElementParameters::double_map_ [private]
Definition at line 435 of file simplified-operator.cc.
fast_map_
MapRef const v8::internal::compiler::anonymous_namespace{simplified-operator.cc}::TransitionAndStoreElementParameters::fast_map_ [private]
Definition at line 436 of file simplified-operator.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-operator.cc