v8::internal::LazyBuiltinsAssembler Class Reference
#include <builtins-lazy-gen.h>
Public Types
using Descriptor = JSTrampolineDescriptor
Public Member Functions
LazyBuiltinsAssembler (compiler::CodeAssemblerState *state)
void GenerateTailCallToJSFunction (TNode< JSFunction > function)
void GenerateTailCallToJSCode (TNode< Code > code, TNode< JSFunction > function)
void GenerateTailCallToReturnedCode (Runtime::FunctionId function_id, TNode< JSFunction > function)
void TailCallRuntimeIfStateEquals (TNode< Uint32T > state, TieringState expected_state, Runtime::FunctionId function_id, TNode< JSFunction > function)
void MaybeTailCallOptimizedCodeSlot (TNode< JSFunction > function, TNode< FeedbackVector > feedback_vector)
void CompileLazy (TNode< JSFunction > function, TNode< Context > context)
Additional Inherited Members
Detailed Description
Definition at line 13 of file builtins-lazy-gen.h.
Member Typedef Documentation
Descriptor
using v8::internal::LazyBuiltinsAssembler::Descriptor = JSTrampolineDescriptor
Definition at line 15 of file builtins-lazy-gen.h.
Constructor & Destructor Documentation
LazyBuiltinsAssembler()
v8::internal::LazyBuiltinsAssembler::LazyBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 17 of file builtins-lazy-gen.h.
      : CodeStubAssembler(state) {}
Member Function Documentation
CompileLazy()
void v8::internal::LazyBuiltinsAssembler::CompileLazy (TNode< JSFunction > function, TNode< Context > context)
Definition at line 126 of file builtins-lazy-gen.cc.
                                                                {
  // First lookup code, maybe we don't need to compile!
  Label compile_function(this, Label::kDeferred);
  // Check the code object for the SFI. If SFI's code entry points to
  // CompileLazy, then we need to lazy compile regardless of the function or
  // tiering state.
  TNode<SharedFunctionInfo> shared =
      CAST(LoadObjectField(function, JSFunction::kSharedFunctionInfoOffset));
  TVARIABLE(Uint16T, sfi_data_type);
  TNode<Code> sfi_code =
      GetSharedFunctionInfoCode(shared, &sfi_data_type, &compile_function);
  TNode<HeapObject> feedback_cell_value = LoadFeedbackCellValue(function);
  // If feedback cell isn't initialized, compile function
  GotoIf(IsUndefined(feedback_cell_value), &compile_function);
  CSA_DCHECK(this, SafeNotEqual(sfi_code, HeapConstantNoHole(BUILTIN_CODE(
                                              isolate(), CompileLazy))));
  USE(sfi_code);
#ifndef V8_ENABLE_LEAPTIERING
  // In the leaptiering case, the code is installed below, through the
  // InstallSFICode runtime function.
  StoreCodePointerField(function, JSFunction::kCodeOffset, sfi_code);
#endif // V8_ENABLE_LEAPTIERING
  Label maybe_use_sfi_code(this);
  // If there is no feedback, don't check for optimized code.
  GotoIf(HasInstanceType(feedback_cell_value, CLOSURE_FEEDBACK_CELL_ARRAY_TYPE),
         &maybe_use_sfi_code);
  // If it isn't undefined or fixed array it must be a feedback vector.
  CSA_DCHECK(this, IsFeedbackVector(feedback_cell_value));
#ifndef V8_ENABLE_LEAPTIERING
  // Is there a tiering state or optimized code in the feedback vector?
  MaybeTailCallOptimizedCodeSlot(function, CAST(feedback_cell_value));
#endif // !V8_ENABLE_LEAPTIERING
  Goto(&maybe_use_sfi_code);
  // At this point we have a candidate InstructionStream object. It's *not* a
  // cached optimized InstructionStream object (we'd have tail-called it above).
  // A usual case would be the InterpreterEntryTrampoline to start executing
  // existing bytecode.
  BIND(&maybe_use_sfi_code);
#ifdef V8_ENABLE_LEAPTIERING
  // In the leaptiering case, we now simply install the code of the SFI on the
  // function's dispatch table entry and call it. Installing the code is
  // necessary as the dispatch table entry may still contain the CompileLazy
  // builtin at this point (we can only update dispatch table code from C++).
  CallRuntime(Runtime::kInstallSFICode, context, function);
  GenerateTailCallToJSFunction(function);
#else
  Label tailcall_code(this), baseline(this);
  TVARIABLE(Code, code);
  // Check if we have baseline code.
  GotoIf(InstanceTypeEqual(sfi_data_type.value(), CODE_TYPE), &baseline);
  code = sfi_code;
  Goto(&tailcall_code);
  BIND(&baseline);
  // Ensure we have a feedback vector.
  code = Select<Code>(
      IsFeedbackVector(feedback_cell_value), [=]() { return sfi_code; },
      [=, this]() {
        return CAST(CallRuntime(Runtime::kInstallBaselineCode,
                                Parameter<Context>(Descriptor::kContext),
                                function));
      });
  Goto(&tailcall_code);
  BIND(&tailcall_code);
  GenerateTailCallToJSCode(code.value(), function);
#endif // V8_ENABLE_LEAPTIERING
  BIND(&compile_function);
  CallRuntime(Runtime::kCompileLazy, context, function);
  GenerateTailCallToJSFunction(function);
}
References BUILTIN_CODE, v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, code, GenerateTailCallToJSCode(), GenerateTailCallToJSFunction(), v8::internal::CodeStubAssembler::GetSharedFunctionInfoCode(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::CodeStubAssembler::HasInstanceType(), v8::internal::compiler::CodeAssembler::HeapConstantNoHole(), v8::internal::CodeStubAssembler::InstanceTypeEqual(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadFeedbackCellValue(), v8::internal::CodeStubAssembler::LoadObjectField(), MaybeTailCallOptimizedCodeSlot(), v8::internal::CodeStubAssembler::SafeNotEqual(), v8::internal::CodeStubAssembler::StoreCodePointerField(), and USE.
GenerateTailCallToJSCode()
void v8::internal::LazyBuiltinsAssembler::GenerateTailCallToJSCode (TNode< Code > code, TNode< JSFunction > function)
Definition at line 41 of file builtins-lazy-gen.cc.
                                                  {
  auto argc = UncheckedParameter<Int32T>(Descriptor::kActualArgumentsCount);
  auto context = Parameter<Context>(Descriptor::kContext);
  auto new_target = Parameter<Object>(Descriptor::kNewTarget);
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
  auto dispatch_handle =
      UncheckedParameter<JSDispatchHandleT>(Descriptor::kDispatchHandle);
#else
  auto dispatch_handle = InvalidDispatchHandleConstant();
#endif
  TailCallJSCode(code, context, function, new_target, argc, dispatch_handle);
}
References code, v8::internal::CodeStubAssembler::InvalidDispatchHandleConstant(), and v8::internal::compiler::CodeAssembler::TailCallJSCode().
Referenced by CompileLazy(), GenerateTailCallToReturnedCode(), and MaybeTailCallOptimizedCodeSlot().
GenerateTailCallToJSFunction()
void v8::internal::LazyBuiltinsAssembler::GenerateTailCallToJSFunction (TNode< JSFunction > function)
Definition at line 19 of file builtins-lazy-gen.cc.
                                {
  auto argc = UncheckedParameter<Int32T>(Descriptor::kActualArgumentsCount);
  auto context = Parameter<Context>(Descriptor::kContext);
  auto new_target = Parameter<Object>(Descriptor::kNewTarget);
#ifdef V8_JS_LINKAGE_INCLUDES_DISPATCH_HANDLE
  auto dispatch_handle =
      UncheckedParameter<JSDispatchHandleT>(Descriptor::kDispatchHandle);
  CSA_DCHECK(this,
             Word32Equal(dispatch_handle,
                         LoadObjectField<JSDispatchHandleT>(
                             function, JSFunction::kDispatchHandleOffset)));
  TNode<Code> code = LoadCodeObjectFromJSDispatchTable(dispatch_handle);
#else
  auto dispatch_handle = InvalidDispatchHandleConstant();
  TNode<Code> code = LoadJSFunctionCode(function);
#endif
  TailCallJSCode(code, context, function, new_target, argc, dispatch_handle);
}
References code, v8::internal::CodeStubAssembler::InvalidDispatchHandleConstant(), v8::internal::CodeStubAssembler::LoadJSFunctionCode(), v8::internal::compiler::CodeAssembler::TailCallJSCode(), and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by CompileLazy().
GenerateTailCallToReturnedCode()
void v8::internal::LazyBuiltinsAssembler::GenerateTailCallToReturnedCode (Runtime::FunctionId function_id, TNode< JSFunction > function)
Definition at line 55 of file builtins-lazy-gen.cc.
                                                               {
  auto context = Parameter<Context>(Descriptor::kContext);
  TNode<Code> code = CAST(CallRuntime(function_id, context, function));
  GenerateTailCallToJSCode(code, function);
}
References v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, code, and GenerateTailCallToJSCode().
Referenced by MaybeTailCallOptimizedCodeSlot().
MaybeTailCallOptimizedCodeSlot()
void v8::internal::LazyBuiltinsAssembler::MaybeTailCallOptimizedCodeSlot (TNode< JSFunction > function, TNode< FeedbackVector > feedback_vector)
Definition at line 62 of file builtins-lazy-gen.cc.
                                                                       {
  Label fallthrough(this), may_have_optimized_code(this),
      maybe_needs_logging(this);
  TNode<Uint16T> flags =
      LoadObjectField<Uint16T>(feedback_vector, FeedbackVector::kFlagsOffset);
  // Fall through if no optimization trigger or optimized code.
  constexpr uint32_t kFlagMask =
      FeedbackVector::FlagMaskForNeedsProcessingCheckFrom(
          CodeKind::INTERPRETED_FUNCTION);
  GotoIfNot(IsSetWord32(flags, kFlagMask), &fallthrough);
  GotoIfNot(
      IsSetWord32(flags, FeedbackVector::kFlagsTieringStateIsAnyRequested),
      &maybe_needs_logging);
  GenerateTailCallToReturnedCode(Runtime::kCompileOptimized, function);
  BIND(&maybe_needs_logging);
  {
    GotoIfNot(IsSetWord32(flags, FeedbackVector::kFlagsLogNextExecution),
              &may_have_optimized_code);
    GenerateTailCallToReturnedCode(Runtime::kFunctionLogNextExecution,
                                   function);
  }
  BIND(&may_have_optimized_code);
  {
    Label heal_optimized_code_slot(this);
    TNode<MaybeObject> maybe_optimized_code_entry = LoadMaybeWeakObjectField(
        feedback_vector, FeedbackVector::kMaybeOptimizedCodeOffset);
    // Optimized code slot is a weak reference to Code object.
    TNode<CodeWrapper> code_wrapper = CAST(GetHeapObjectAssumeWeak(
        maybe_optimized_code_entry, &heal_optimized_code_slot));
    TNode<Code> optimized_code =
        LoadCodePointerFromObject(code_wrapper, CodeWrapper::kCodeOffset);
    // Check if the optimized code is marked for deopt. If it is, call the
    // runtime to clear it.
    GotoIf(IsMarkedForDeoptimization(optimized_code),
           &heal_optimized_code_slot);
    // Optimized code is good, get it into the closure and link the closure into
    // the optimized functions list, then tail call the optimized code.
    StoreCodePointerField(function, JSFunction::kCodeOffset, optimized_code);
    Comment("MaybeTailCallOptimizedCodeSlot:: GenerateTailCallToJSCode");
    GenerateTailCallToJSCode(optimized_code, function);
    // Optimized code slot contains deoptimized code, or the code is cleared
    // and tiering state hasn't yet been updated. Evict the code, update the
    // state and re-enter the closure's code.
    BIND(&heal_optimized_code_slot);
    GenerateTailCallToReturnedCode(Runtime::kHealOptimizedCodeSlot, function);
  }
  // Fall-through if the optimized code cell is clear and the tiering state is
  // kNone.
  BIND(&fallthrough);
}
References CAST, v8::internal::compiler::CodeAssembler::Comment(), v8::internal::FeedbackVector::FlagMaskForNeedsProcessingCheckFrom(), v8::internal::flags, GenerateTailCallToJSCode(), GenerateTailCallToReturnedCode(), v8::internal::CodeStubAssembler::GetHeapObjectAssumeWeak(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::IsMarkedForDeoptimization(), v8::internal::CodeStubAssembler::IsSetWord32(), v8::internal::FeedbackVector::kFlagsLogNextExecution, v8::internal::FeedbackVector::kFlagsTieringStateIsAnyRequested, v8::internal::CodeStubAssembler::LoadCodePointerFromObject(), v8::internal::CodeStubAssembler::LoadMaybeWeakObjectField(), and v8::internal::CodeStubAssembler::StoreCodePointerField().
Referenced by CompileLazy().
TailCallRuntimeIfStateEquals()
void v8::internal::LazyBuiltinsAssembler::TailCallRuntimeIfStateEquals (TNode< Uint32T > state, TieringState expected_state, Runtime::FunctionId function_id, TNode< JSFunction > function)
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-lazy-gen.h
/mnt/V8SourceCode/src/builtins/builtins-lazy-gen.cc