v8::internal::DateParser::TimeZoneComposer Class Reference
Public Member Functions
TimeZoneComposer ()
void Set (int offset_in_hours)
void SetSign (int sign)
void SetAbsoluteHour (int hour)
void SetAbsoluteMinute (int minute)
bool IsExpecting (int n) const
bool IsUTC () const
bool Write (double *output)
bool IsEmpty ()
Private Attributes
int sign_
int hour_
int minute_
Detailed Description
Definition at line 270 of file dateparser.h.
Constructor & Destructor Documentation
TimeZoneComposer()
v8::internal::DateParser::TimeZoneComposer::TimeZoneComposer () [inline]
Definition at line 272 of file dateparser.h.
: sign_(kNone), hour_(kNone), minute_(kNone) {}
Member Function Documentation
IsEmpty()
bool v8::internal::DateParser::TimeZoneComposer::IsEmpty () [inline]
Definition at line 286 of file dateparser.h.
{ return hour_ == kNone; }
References hour_, and v8::internal::DateParser::kNone.
Referenced by v8::internal::DateParser::ParseES5DateTime().
IsExpecting()
bool v8::internal::DateParser::TimeZoneComposer::IsExpecting (int n) const [inline]
Definition at line 281 of file dateparser.h.
                                  {
      return hour_ != kNone && minute_ == kNone && TimeComposer::IsMinute(n);
    }
References hour_, v8::internal::DateParser::TimeComposer::IsMinute(), v8::internal::DateParser::kNone, and minute_.
Referenced by v8::internal::DateParser::Parse().
IsUTC()
bool v8::internal::DateParser::TimeZoneComposer::IsUTC () const [inline]
Definition at line 284 of file dateparser.h.
{ return hour_ == 0 && minute_ == 0; }
References hour_, and minute_.
Referenced by v8::internal::DateParser::Parse().
Set()
void v8::internal::DateParser::TimeZoneComposer::Set (int offset_in_hours) [inline]
Definition at line 273 of file dateparser.h.
                                  {
      sign_ = offset_in_hours < 0 ? -1 : 1;
      hour_ = offset_in_hours * sign_;
      minute_ = 0;
    }
References hour_, minute_, and sign_.
Referenced by v8::internal::DateParser::Parse(), and v8::internal::DateParser::ParseES5DateTime().
SetAbsoluteHour()
void v8::internal::DateParser::TimeZoneComposer::SetAbsoluteHour (int hour) [inline]
Definition at line 279 of file dateparser.h.
{ hour_ = hour; }
References hour_.
Referenced by v8::internal::DateParser::Parse(), and v8::internal::DateParser::ParseES5DateTime().
SetAbsoluteMinute()
void v8::internal::DateParser::TimeZoneComposer::SetAbsoluteMinute (int minute) [inline]
Definition at line 280 of file dateparser.h.
{ minute_ = minute; }
References minute_.
Referenced by v8::internal::DateParser::Parse(), and v8::internal::DateParser::ParseES5DateTime().
SetSign()
void v8::internal::DateParser::TimeZoneComposer::SetSign (int sign) [inline]
Definition at line 278 of file dateparser.h.
{ sign_ = sign < 0 ? -1 : 1; }
References v8::internal::sign, and sign_.
Referenced by v8::internal::DateParser::Parse(), and v8::internal::DateParser::ParseES5DateTime().
Write()
bool v8::internal::DateParser::TimeZoneComposer::Write (double * output)
Definition at line 99 of file dateparser.cc.
                                                     {
  if (sign_ != kNone) {
    if (hour_ == kNone) hour_ = 0;
    if (minute_ == kNone) minute_ = 0;
    // Avoid signed integer overflow (undefined behavior) by doing unsigned
    // arithmetic.
    unsigned total_seconds_unsigned = hour_ * 3600U + minute_ * 60U;
    if (total_seconds_unsigned > Smi::kMaxValue) return false;
    int total_seconds = static_cast<int>(total_seconds_unsigned);
    if (sign_ < 0) {
      total_seconds = -total_seconds;
    }
    DCHECK(Smi::IsValid(total_seconds));
    output[UTC_OFFSET] = total_seconds;
  } else {
    output[UTC_OFFSET] = std::numeric_limits<double>::quiet_NaN();
  }
  return true;
}
References v8::internal::DCHECK(), v8::internal::Smi::IsValid(), v8::internal::Smi::kMaxValue, v8::internal::DateParser::kNone, and v8::internal::DateParser::UTC_OFFSET.
Referenced by v8::internal::DateParser::Parse().
Member Data Documentation
hour_
int v8::internal::DateParser::TimeZoneComposer::hour_ [private]
Definition at line 290 of file dateparser.h.
Referenced by IsEmpty(), IsExpecting(), IsUTC(), Set(), and SetAbsoluteHour().
minute_
int v8::internal::DateParser::TimeZoneComposer::minute_ [private]
Definition at line 291 of file dateparser.h.
Referenced by IsExpecting(), IsUTC(), Set(), and SetAbsoluteMinute().
sign_
int v8::internal::DateParser::TimeZoneComposer::sign_ [private]
Definition at line 289 of file dateparser.h.
Referenced by Set(), and SetSign().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/date/dateparser.h
/mnt/V8SourceCode/src/date/dateparser.cc