v8::internal::maglev::CallForwardVarargs Class Reference
#include <maglev-ir.h>
Public Member Functions
CallForwardVarargs (uint64_t bitfield, ValueNode *function, ValueNode *context, int start_index, Call::TargetType target_type)
Input & function ()
const Input & function () const
Input & context ()
const Input & context () const
int num_args () const
Input & arg (int i)
void set_arg (int i, ValueNode *node)
auto args ()
void VerifyInputs (MaglevGraphLabeller *graph_labeller) const
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
int start_index () const
Call::TargetType target_type () const
Static Public Attributes
static constexpr int kFunctionIndex = 0
static constexpr int kContextIndex = 1
static constexpr int kFixedInputCount = 2
static constexpr OpProperties kProperties = OpProperties::JSCall()
Private Types
using Base = ValueNodeT< CallForwardVarargs >
Private Attributes
int start_index_
Call::TargetType target_type_
Additional Inherited Members
Detailed Description
Definition at line 10278 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CallForwardVarargs::Base = ValueNodeT<CallForwardVarargs> [private]
Definition at line 10279 of file maglev-ir.h.
Constructor & Destructor Documentation
CallForwardVarargs()
v8::internal::maglev::CallForwardVarargs::CallForwardVarargs (uint64_t bitfield, ValueNode * function, ValueNode * context, int start_index, Call::TargetType target_type) [inline]
Definition at line 10292 of file maglev-ir.h.
      : Base(bitfield), start_index_(start_index), target_type_(target_type) {
    set_input(kFunctionIndex, function);
    set_input(kContextIndex, context);
  }
Member Function Documentation
arg()
Input& v8::internal::maglev::CallForwardVarargs::arg (int i) [inline]
Definition at line 10306 of file maglev-ir.h.
{ return input(i + kFixedInputCount); }
args()
auto v8::internal::maglev::CallForwardVarargs::args () [inline]
Definition at line 10310 of file maglev-ir.h.
              {
    return base::make_iterator_range(
        std::make_reverse_iterator(&arg(-1)),
        std::make_reverse_iterator(&arg(num_args() - 1)));
  }
References v8::base::make_iterator_range().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context() [1/2]
Input& v8::internal::maglev::CallForwardVarargs::context () [inline]
Definition at line 10303 of file maglev-ir.h.
{ return input(kContextIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
context() [2/2]
const Input& v8::internal::maglev::CallForwardVarargs::context () const [inline]
Definition at line 10304 of file maglev-ir.h.
{ return input(kContextIndex); }
function() [1/2]
Input& v8::internal::maglev::CallForwardVarargs::function () [inline]
Definition at line 10301 of file maglev-ir.h.
{ return input(kFunctionIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
function() [2/2]
const Input& v8::internal::maglev::CallForwardVarargs::function () const [inline]
Definition at line 10302 of file maglev-ir.h.
{ return input(kFunctionIndex); }
GenerateCode()
void v8::internal::maglev::CallForwardVarargs::GenerateCode (MaglevAssembler * , const ProcessingState &)
MaxCallStackArgs()
int v8::internal::maglev::CallForwardVarargs::MaxCallStackArgs () const
num_args()
int v8::internal::maglev::CallForwardVarargs::num_args () const [inline]
Definition at line 10305 of file maglev-ir.h.
{ return input_count() - kFixedInputCount; }
References v8::internal::compiler::turboshaft::detail::input_count().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
PrintParams()
void v8::internal::maglev::CallForwardVarargs::PrintParams (std::ostream & os, MaglevGraphLabeller * graph_labeller) const
Definition at line 8417 of file maglev-ir.cc.
                                                               {
  if (start_index_ == 0) return;
  os << "(" << start_index_ << ")";
}
References start_index_.
set_arg()
void v8::internal::maglev::CallForwardVarargs::set_arg (int i, ValueNode * node) [inline]
Definition at line 10307 of file maglev-ir.h.
                                       {
    set_input(i + kFixedInputCount, node);
  }
SetValueLocationConstraints()
void v8::internal::maglev::CallForwardVarargs::SetValueLocationConstraints ()
start_index()
int v8::internal::maglev::CallForwardVarargs::start_index () const [inline]
Definition at line 10325 of file maglev-ir.h.
{ return start_index_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
target_type()
Call::TargetType v8::internal::maglev::CallForwardVarargs::target_type () const [inline]
Definition at line 10326 of file maglev-ir.h.
{ return target_type_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
VerifyInputs()
void v8::internal::maglev::CallForwardVarargs::VerifyInputs (MaglevGraphLabeller * graph_labeller) const
Definition at line 935 of file maglev-ir.cc.
                                               {
  for (int i = 0; i < input_count(); i++) {
    CheckValueInputIs(this, i, ValueRepresentation::kTagged, graph_labeller);
  }
}
References v8::internal::maglev::CheckValueInputIs(), v8::internal::compiler::turboshaft::detail::input_count(), and v8::internal::maglev::kTagged.
Member Data Documentation
kContextIndex
constexpr int v8::internal::maglev::CallForwardVarargs::kContextIndex = 1 [static], [constexpr]
Definition at line 10283 of file maglev-ir.h.
kFixedInputCount
constexpr int v8::internal::maglev::CallForwardVarargs::kFixedInputCount = 2 [static], [constexpr]
Definition at line 10284 of file maglev-ir.h.
kFunctionIndex
constexpr int v8::internal::maglev::CallForwardVarargs::kFunctionIndex = 0 [static], [constexpr]
Definition at line 10282 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CallForwardVarargs::kProperties = OpProperties::JSCall() [static], [constexpr]
Definition at line 10299 of file maglev-ir.h.
start_index_
int v8::internal::maglev::CallForwardVarargs::start_index_ [private]
Definition at line 10329 of file maglev-ir.h.
Referenced by PrintParams().
target_type_
Call::TargetType v8::internal::maglev::CallForwardVarargs::target_type_ [private]
Definition at line 10330 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/maglev-ir.cc