v8::debug::ConsoleCallArguments Class Reference
#include <interface-types.h>
Public Member Functions
int Length () const
v8::Local< v8::Value > operator[] (int i) const
Accessor for the available arguments.
v8::Isolate * GetIsolate () const
ConsoleCallArguments (const v8::FunctionCallbackInfo< v8::Value > &)
ConsoleCallArguments (internal::Isolate *isolate, const internal::BuiltinArguments &)
Private Attributes
v8::Isolate * isolate_
internal::Address * values_
int length_
Detailed Description
Definition at line 96 of file interface-types.h.
Constructor & Destructor Documentation
ConsoleCallArguments() [1/2]
v8::debug::ConsoleCallArguments::ConsoleCallArguments (const v8::FunctionCallbackInfo< v8::Value > & info) [explicit]
Definition at line 1170 of file debug-interface.cc.
    : isolate_(info.GetIsolate()),
      values_(info.values_),
      length_(info.Length()) {}
ConsoleCallArguments() [2/2]
v8::debug::ConsoleCallArguments::ConsoleCallArguments (internal::Isolate * isolate, const internal::BuiltinArguments & args) [explicit]
Definition at line 1176 of file debug-interface.cc.
    : isolate_(reinterpret_cast<v8::Isolate*>(isolate)),
      values_(args.length() > 1 ? args.address_of_first_argument() : nullptr),
      length_(args.length() - 1) {}
Member Function Documentation
GetIsolate()
v8::Isolate* v8::debug::ConsoleCallArguments::GetIsolate () const [inline]
Definition at line 110 of file interface-types.h.
{ return isolate_; }
References isolate_.
Referenced by operator[]().
Length()
int v8::debug::ConsoleCallArguments::Length () const [inline]
Definition at line 98 of file interface-types.h.
{ return length_; }
References length_.
Referenced by v8_inspector::V8Console::Assert(), and v8_inspector::V8Console::TimeStamp().
operator[]()
v8::Local<v8::Value> v8::debug::ConsoleCallArguments::operator[] (int i) const [inline]
Accessor for the available arguments.
Returns undefined if the index is out of bounds.
Definition at line 103 of file interface-types.h.
                                                     {
    // values_ points to the first argument.
    if (i < 0 || length_ <= i) return Undefined(GetIsolate());
    DCHECK_NOT_NULL(values_);
    return Local<Value>::FromSlot(values_ + i);
  }
References DCHECK_NOT_NULL, v8::Local< T >::FromSlot(), GetIsolate(), length_, v8::Undefined(), and values_.
Member Data Documentation
isolate_
v8::Isolate* v8::debug::ConsoleCallArguments::isolate_ [private]
Definition at line 117 of file interface-types.h.
Referenced by GetIsolate().
length_
int v8::debug::ConsoleCallArguments::length_ [private]
Definition at line 119 of file interface-types.h.
Referenced by Length(), and operator[]().
values_
internal::Address* v8::debug::ConsoleCallArguments::values_ [private]
Definition at line 118 of file interface-types.h.
Referenced by operator[]().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/interface-types.h
/mnt/V8SourceCode/src/debug/debug-interface.cc