v8::internal::WriteBarrierDescriptor Class Reference
#include <interface-descriptors.h>
Public Member Functions
DEFINE_PARAMETER_TYPES (MachineType::TaggedPointer(), MachineType::Pointer()) static const expr auto registers()
Static Public Member Functions
static constexpr Register ObjectRegister ()
static constexpr Register SlotAddressRegister ()
static constexpr Register ValueRegister ()
static constexpr RegList ComputeSavedRegisters (Register object, Register slot_address=no_reg)
Static Public Attributes
static constexpr bool kRestrictAllocatableRegisters = true
static constexpr bool kCalleeSaveRegisters = true
Additional Inherited Members
Detailed Description
Definition at line 1560 of file interface-descriptors.h.
Member Function Documentation
ComputeSavedRegisters()
constexpr RegList v8::internal::WriteBarrierDescriptor::ComputeSavedRegisters (Register object, Register slot_address = no_reg) [inline], [static], [constexpr]
Definition at line 307 of file interface-descriptors-inl.h.
                                            {
  DCHECK(!AreAliased(object, slot_address));
  RegList saved_registers;
#if V8_TARGET_ARCH_X64
  // Only push clobbered registers.
  if (object != ObjectRegister()) saved_registers.set(ObjectRegister());
  if (slot_address != no_reg && slot_address != SlotAddressRegister()) {
    saved_registers.set(SlotAddressRegister());
  }
#elif V8_TARGET_ARCH_ARM64 || V8_TARGET_ARCH_ARM || V8_TARGET_ARCH_LOONG64 || \
    V8_TARGET_ARCH_MIPS64
  if (object != ObjectRegister()) saved_registers.set(ObjectRegister());
  // The slot address is always clobbered.
  saved_registers.set(SlotAddressRegister());
#else
  // TODO(cbruni): Enable callee-saved registers for other platforms.
  // This is a temporary workaround to prepare code for callee-saved registers.
  constexpr auto allocated_registers = registers();
  for (size_t i = 0; i < allocated_registers.size(); ++i) {
    saved_registers.set(allocated_registers[i]);
  }
#endif
  return saved_registers;
}
References v8::internal::AreAliased(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::no_reg, ObjectRegister(), v8::internal::StaticCallInterfaceDescriptor< WriteBarrierDescriptor >::registers(), v8::internal::RegListBase< RegisterT >::set(), and SlotAddressRegister().
Referenced by v8::internal::MacroAssembler::CallEphemeronKeyBarrier(), v8::internal::MacroAssembler::CallRecordWriteStubSaveRegisters(), and v8::internal::IndirectPointerWriteBarrierDescriptor::ComputeSavedRegisters().
DEFINE_PARAMETER_TYPES()
v8::internal::WriteBarrierDescriptor::DEFINE_PARAMETER_TYPES (MachineType::TaggedPointer() , MachineType::Pointer()) const
ObjectRegister()
constexpr Register v8::internal::WriteBarrierDescriptor::ObjectRegister () [inline], [static], [constexpr]
Definition at line 293 of file interface-descriptors-inl.h.
                                                          {
  return std::get<kObject>(registers());
}
References v8::internal::StaticCallInterfaceDescriptor< WriteBarrierDescriptor >::registers().
Referenced by v8::internal::MacroAssembler::CallEphemeronKeyBarrier(), v8::internal::MacroAssembler::CallRecordWriteStub(), v8::internal::MacroAssembler::CallRecordWriteStubSaveRegisters(), v8::internal::maglev::MaglevAssembler::CheckAndEmitDeferredWriteBarrier(), ComputeSavedRegisters(), and v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_WasmResumeHelper().
SlotAddressRegister()
constexpr Register v8::internal::WriteBarrierDescriptor::SlotAddressRegister () [inline], [static], [constexpr]
Definition at line 297 of file interface-descriptors-inl.h.
                                                               {
  return std::get<kSlotAddress>(registers());
}
References v8::internal::StaticCallInterfaceDescriptor< WriteBarrierDescriptor >::registers().
Referenced by v8::internal::MacroAssembler::CallEphemeronKeyBarrier(), v8::internal::MacroAssembler::CallRecordWriteStub(), v8::internal::MacroAssembler::CallRecordWriteStubSaveRegisters(), v8::internal::maglev::MaglevAssembler::CheckAndEmitDeferredWriteBarrier(), ComputeSavedRegisters(), and v8::internal::MacroAssembler::RecordWrite().
ValueRegister()
constexpr Register v8::internal::WriteBarrierDescriptor::ValueRegister () [inline], [static], [constexpr]
Definition at line 302 of file interface-descriptors-inl.h.
                                                         {
  return std::get<kSlotAddress + 1>(registers());
}
References v8::internal::StaticCallInterfaceDescriptor< WriteBarrierDescriptor >::registers().
Member Data Documentation
kCalleeSaveRegisters
constexpr bool v8::internal::WriteBarrierDescriptor::kCalleeSaveRegisters = true [static], [constexpr]
Definition at line 1573 of file interface-descriptors.h.
kRestrictAllocatableRegisters
constexpr bool v8::internal::WriteBarrierDescriptor::kRestrictAllocatableRegisters = true [static], [constexpr]
Definition at line 1572 of file interface-descriptors.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h