v8::internal::RecordMigratedSlotVisitor Class Reference
Public Member Functions
RecordMigratedSlotVisitor (Heap *heap)
void VisitPointer (Tagged< HeapObject > host, ObjectSlot p) final
void VisitMapPointer (Tagged< HeapObject > host) final
void VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot p) final
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) final
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) final
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) final
void VisitEphemeron (Tagged< HeapObject > host, int index, ObjectSlot key, ObjectSlot value) override
void VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitExternalReference (Tagged< InstructionStream > host, RelocInfo *rinfo) final
void VisitInternalReference (Tagged< InstructionStream > host, RelocInfo *rinfo) final
void VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) final
void VisitIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerMode mode) final
void VisitTrustedPointerTableEntry (Tagged< HeapObject > host, IndirectPointerSlot slot) final
void VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedPointerSlot slot) final
void VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedMaybeObjectSlot slot) final
Static Public Member Functions
static constexpr bool UsePrecomputedObjectSize ()
Protected Member Functions
void RecordMigratedSlot (Tagged< HeapObject > host, Tagged< MaybeObject > value, Address slot)
Protected Attributes
Heap *const heap_
Additional Inherited Members
Detailed Description
Definition at line 1241 of file mark-compact.cc.
Constructor & Destructor Documentation
RecordMigratedSlotVisitor()
v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlotVisitor (Heap * heap) [inline], [explicit]
Definition at line 1244 of file mark-compact.cc.
      : HeapVisitor(heap->isolate()), heap_(heap) {}
Member Function Documentation
RecordMigratedSlot()
void v8::internal::RecordMigratedSlotVisitor::RecordMigratedSlot (Tagged< HeapObject > host, Tagged< MaybeObject > value, Address slot) [inline], [protected]
Definition at line 1350 of file mark-compact.cc.
                                                                          {
    if (value.IsStrongOrWeak()) {
      MemoryChunk* value_chunk = MemoryChunk::FromAddress(value.ptr());
      MemoryChunk* host_chunk = MemoryChunk::FromHeapObject(host);
      if (HeapLayout::InYoungGeneration(value)) {
        MutablePageMetadata* host_metadata =
            MutablePageMetadata::cast(host_chunk->Metadata());
        DCHECK_IMPLIES(value_chunk->IsToPage(),
                       v8_flags.minor_ms || value_chunk->IsLargePage());
        DCHECK(host_metadata->SweepingDone());
        RememberedSet<OLD_TO_NEW>::Insert<AccessMode::NON_ATOMIC>(
            host_metadata, host_chunk->Offset(slot));
      } else if (value_chunk->IsEvacuationCandidate()) {
        MutablePageMetadata* host_metadata =
            MutablePageMetadata::cast(host_chunk->Metadata());
        if (value_chunk->IsFlagSet(MemoryChunk::IS_EXECUTABLE)) {
          // TODO(377724745): currently needed because flags are untrusted.
          SBXCHECK(!InsideSandbox(value_chunk->address()));
          RememberedSet<TRUSTED_TO_CODE>::Insert<AccessMode::NON_ATOMIC>(
              host_metadata, host_chunk->Offset(slot));
        } else if (value_chunk->IsFlagSet(MemoryChunk::IS_TRUSTED) &&
                   host_chunk->IsFlagSet(MemoryChunk::IS_TRUSTED)) {
          // When the sandbox is disabled, we use plain tagged pointers to
          // reference trusted objects from untrusted ones. However, for these
          // references we want to use the OLD_TO_OLD remembered set, so here
          // we need to check that both the value chunk and the host chunk are
          // trusted space chunks.
          // TODO(377724745): currently needed because flags are untrusted.
          SBXCHECK(!InsideSandbox(value_chunk->address()));
          if (value_chunk->InWritableSharedSpace()) {
            RememberedSet<TRUSTED_TO_SHARED_TRUSTED>::Insert<
                AccessMode::NON_ATOMIC>(host_metadata,
                                        host_chunk->Offset(slot));
          } else {
            RememberedSet<TRUSTED_TO_TRUSTED>::Insert<AccessMode::NON_ATOMIC>(
                host_metadata, host_chunk->Offset(slot));
          }
        } else {
          RememberedSet<OLD_TO_OLD>::Insert<AccessMode::NON_ATOMIC>(
              host_metadata, host_chunk->Offset(slot));
        }
      } else if (value_chunk->InWritableSharedSpace() &&
                 !HeapLayout::InWritableSharedSpace(host)) {
        MutablePageMetadata* host_metadata =
            MutablePageMetadata::cast(host_chunk->Metadata());
        if (value_chunk->IsFlagSet(MemoryChunk::IS_TRUSTED) &&
            host_chunk->IsFlagSet(MemoryChunk::IS_TRUSTED)) {
          RememberedSet<TRUSTED_TO_SHARED_TRUSTED>::Insert<
              AccessMode::NON_ATOMIC>(host_metadata, host_chunk->Offset(slot));
        } else {
          RememberedSet<OLD_TO_SHARED>::Insert<AccessMode::NON_ATOMIC>(
              host_metadata, host_chunk->Offset(slot));
        }
      }
    }
  }
References v8::internal::MemoryChunk::address(), v8::internal::MutablePageMetadata::cast(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::MemoryChunk::FromAddress(), v8::internal::MemoryChunk::FromHeapObject(), v8::internal::InsideSandbox(), v8::internal::MemoryChunk::InWritableSharedSpace(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::MemoryChunk::IS_EXECUTABLE, v8::internal::MemoryChunk::IS_TRUSTED, v8::internal::MemoryChunk::IsEvacuationCandidate(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::IsLargePage(), v8::internal::MemoryChunk::IsToPage(), v8::internal::MemoryChunk::Metadata(), v8::internal::NON_ATOMIC, v8::internal::MemoryChunk::Offset(), SBXCHECK, v8::internal::MutablePageMetadata::SweepingDone(), v8::internal::v8_flags, and v8::internal::value.
Referenced by VisitInstructionStreamPointer(), VisitPointer(), and VisitProtectedPointer().
UsePrecomputedObjectSize()
static constexpr bool v8::internal::RecordMigratedSlotVisitor::UsePrecomputedObjectSize () [inline], [static], [constexpr]
Definition at line 1247 of file mark-compact.cc.
{ return true; }
VisitCodeTarget()
void v8::internal::RecordMigratedSlotVisitor::VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1302 of file mark-compact.cc.
                                                         {
    DCHECK(RelocInfo::IsCodeTargetMode(rinfo->rmode()));
    Tagged<InstructionStream> target =
        InstructionStream::FromTargetAddress(rinfo->target_address());
    // The target is always in old space, we don't have to record the slot in
    // the old-to-new remembered set.
    DCHECK(!HeapLayout::InYoungGeneration(target));
    DCHECK(!HeapLayout::InWritableSharedSpace(target));
    heap_->mark_compact_collector()->RecordRelocSlot(host, rinfo, target);
  }
References v8::internal::DCHECK(), v8::internal::InstructionStream::FromTargetAddress(), heap_, v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::RelocInfo::IsCodeTargetMode(), v8::internal::Heap::mark_compact_collector(), v8::internal::MarkCompactCollector::RecordRelocSlot(), v8::internal::RelocInfo::rmode(), and v8::internal::RelocInfo::target_address().
VisitEmbeddedPointer()
void v8::internal::RecordMigratedSlotVisitor::VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1314 of file mark-compact.cc.
                                                              {
    DCHECK(RelocInfo::IsEmbeddedObjectMode(rinfo->rmode()));
    Tagged<HeapObject> object = rinfo->target_object(cage_base());
    WriteBarrier::GenerationalForRelocInfo(host, rinfo, object);
    WriteBarrier::SharedForRelocInfo(host, rinfo, object);
    heap_->mark_compact_collector()->RecordRelocSlot(host, rinfo, object);
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), v8::internal::DCHECK(), v8::internal::WriteBarrier::GenerationalForRelocInfo(), heap_, v8::internal::RelocInfo::IsEmbeddedObjectMode(), v8::internal::Heap::mark_compact_collector(), v8::internal::MarkCompactCollector::RecordRelocSlot(), v8::internal::RelocInfo::rmode(), v8::internal::WriteBarrier::SharedForRelocInfo(), and v8::internal::RelocInfo::target_object().
VisitEphemeron()
void v8::internal::RecordMigratedSlotVisitor::VisitEphemeron (Tagged< HeapObject > host, int index, ObjectSlot key, ObjectSlot value) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1288 of file mark-compact.cc.
                                                        {
    DCHECK(IsEphemeronHashTable(host));
    DCHECK(!HeapLayout::InYoungGeneration(host));
    // Simply record ephemeron keys in OLD_TO_NEW if it points into the young
    // generation instead of recording it in ephemeron_remembered_set here for
    // migrated objects. OLD_TO_NEW is per page and we can therefore easily
    // record in OLD_TO_NEW on different pages in parallel without merging. Both
    // sets are anyways guaranteed to be empty after a full GC.
    VisitPointer(host, key);
    VisitPointer(host, value);
  }
References v8::internal::DCHECK(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::key, v8::internal::value, and VisitPointer().
VisitExternalPointer()
void v8::internal::RecordMigratedSlotVisitor::VisitExternalPointer (Tagged< HeapObject > host, ExternalPointerSlot slot) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1328 of file mark-compact.cc.
                                                                   {}
VisitExternalReference()
void v8::internal::RecordMigratedSlotVisitor::VisitExternalReference (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1324 of file mark-compact.cc.
                                                             {}
VisitIndirectPointer()
void v8::internal::RecordMigratedSlotVisitor::VisitIndirectPointer (Tagged< HeapObject > host, IndirectPointerSlot slot, IndirectPointerMode mode) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1331 of file mark-compact.cc.
                                                                   {}
VisitInstructionStreamPointer()
void v8::internal::RecordMigratedSlotVisitor::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 1279 of file mark-compact.cc.
                                                                              {
    // This code is similar to the implementation of VisitPointer() modulo
    // new kind of slot.
    DCHECK(!HasWeakHeapObjectTag(slot.load(code_cage_base())));
    Tagged<Object> code = slot.load(code_cage_base());
    RecordMigratedSlot(host, code, slot.address());
  }
References code, v8::internal::ObjectVisitorWithCageBases::code_cage_base(), v8::internal::DCHECK(), v8::internal::HasWeakHeapObjectTag(), and RecordMigratedSlot().
VisitInternalReference()
void v8::internal::RecordMigratedSlotVisitor::VisitInternalReference (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1326 of file mark-compact.cc.
                                                             {}
VisitMapPointer()
void v8::internal::RecordMigratedSlotVisitor::VisitMapPointer (Tagged< HeapObject > host) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1254 of file mark-compact.cc.
                                                             {
    VisitPointer(host, host->map_slot());
  }
References VisitPointer().
VisitPointer() [1/2]
void v8::internal::RecordMigratedSlotVisitor::VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1258 of file mark-compact.cc.
                                                                             {
    DCHECK(!MapWord::IsPacked(p.Relaxed_Load(cage_base()).ptr()));
    RecordMigratedSlot(host, p.load(cage_base()), p.address());
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), v8::internal::DCHECK(), v8::internal::MapWord::IsPacked(), and RecordMigratedSlot().
VisitPointer() [2/2]
void v8::internal::RecordMigratedSlotVisitor::VisitPointer (Tagged< HeapObject > host, ObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1249 of file mark-compact.cc.
                                                                        {
    DCHECK(!HasWeakHeapObjectTag(p.load(cage_base())));
    RecordMigratedSlot(host, p.load(cage_base()), p.address());
  }
References v8::internal::ObjectVisitorWithCageBases::cage_base(), v8::internal::DCHECK(), v8::internal::HasWeakHeapObjectTag(), and RecordMigratedSlot().
Referenced by VisitEphemeron(), VisitMapPointer(), and VisitPointers().
VisitPointers() [1/2]
void v8::internal::RecordMigratedSlotVisitor::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 1271 of file mark-compact.cc.
                                                       {
    while (start < end) {
      VisitPointer(host, start);
      ++start;
    }
  }
References v8::internal::compiler::end(), and VisitPointer().
VisitPointers() [2/2]
void v8::internal::RecordMigratedSlotVisitor::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 1263 of file mark-compact.cc.
                                                  {
    while (start < end) {
      VisitPointer(host, start);
      ++start;
    }
  }
References v8::internal::compiler::end(), and VisitPointer().
VisitProtectedPointer() [1/2]
void v8::internal::RecordMigratedSlotVisitor::VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedMaybeObjectSlot slot) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1343 of file mark-compact.cc.
                                                                         {
    DCHECK(!MapWord::IsPacked(slot.Relaxed_Load().ptr()));
    RecordMigratedSlot(host, slot.load(), slot.address());
  }
References v8::internal::DCHECK(), v8::internal::MapWord::IsPacked(), and RecordMigratedSlot().
VisitProtectedPointer() [2/2]
void v8::internal::RecordMigratedSlotVisitor::VisitProtectedPointer (Tagged< TrustedObject > host, ProtectedPointerSlot slot) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1338 of file mark-compact.cc.
                                                                     {
    RecordMigratedSlot(host, slot.load(), slot.address());
  }
References RecordMigratedSlot().
VisitTrustedPointerTableEntry()
void v8::internal::RecordMigratedSlotVisitor::VisitTrustedPointerTableEntry (Tagged< HeapObject > host, IndirectPointerSlot slot) [inline], [final], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 1335 of file mark-compact.cc.
                                                                            {}
Member Data Documentation
heap_
Heap* const v8::internal::RecordMigratedSlotVisitor::heap_ [protected]
Definition at line 1408 of file mark-compact.cc.
Referenced by VisitCodeTarget(), and VisitEmbeddedPointer().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc