v8::internal::maglev::ExceptionHandlerInfo Class Reference
#include <maglev-ir.h>
Public Types
enum Mode { kNoExceptionHandler = -1
, kLazyDeopt = -2
 }
using List = base::ThreadedList< ExceptionHandlerInfo >
Public Member Functions
ExceptionHandlerInfo (Mode mode=kNoExceptionHandler)
ExceptionHandlerInfo (BasicBlockRef *catch_block_ref, int depth)
ExceptionHandlerInfo (BasicBlock *catch_block_ref, int depth)
bool HasExceptionHandler () const
bool ShouldLazyDeopt () const
Label & trampoline_entry ()
BasicBlockRef * catch_block_ref_address ()
BasicBlock * catch_block () const
int depth () const
int pc_offset () const
void set_pc_offset (int offset)
Private Member Functions
ExceptionHandlerInfo ** next ()
Private Attributes
BasicBlockRef catch_block_
Label trampoline_entry_
int depth_
int pc_offset_
ExceptionHandlerInfo * next_ = nullptr
friend List
Detailed Description
Definition at line 1980 of file maglev-ir.h.
Member Typedef Documentation
List
using v8::internal::maglev::ExceptionHandlerInfo::List = base::ThreadedList<ExceptionHandlerInfo>
Definition at line 1982 of file maglev-ir.h.
Member Enumeration Documentation
Mode
enum v8::internal::maglev::ExceptionHandlerInfo::Mode
Enumerator
kNoExceptionHandler
kLazyDeopt
Definition at line 1983 of file maglev-ir.h.
            {
    kNoExceptionHandler = -1,
    kLazyDeopt = -2,
  };
Constructor & Destructor Documentation
ExceptionHandlerInfo() [1/3]
v8::internal::maglev::ExceptionHandlerInfo::ExceptionHandlerInfo (Mode mode = kNoExceptionHandler) [inline], [explicit]
Definition at line 1988 of file maglev-ir.h.
      : catch_block_(), depth_(static_cast<int>(mode)), pc_offset_(-1) {}
ExceptionHandlerInfo() [2/3]
v8::internal::maglev::ExceptionHandlerInfo::ExceptionHandlerInfo (BasicBlockRef * catch_block_ref, int depth) [inline]
Definition at line 1991 of file maglev-ir.h.
      : catch_block_(catch_block_ref), depth_(depth), pc_offset_(-1) {
    DCHECK_NE(depth, kNoExceptionHandler);
    DCHECK_NE(depth, kLazyDeopt);
  }
References DCHECK_NE, depth(), kLazyDeopt, and kNoExceptionHandler.
ExceptionHandlerInfo() [3/3]
v8::internal::maglev::ExceptionHandlerInfo::ExceptionHandlerInfo (BasicBlock * catch_block_ref, int depth) [inline]
Definition at line 1997 of file maglev-ir.h.
      : catch_block_(catch_block_ref), depth_(depth), pc_offset_(-1) {}
Member Function Documentation
catch_block()
BasicBlock* v8::internal::maglev::ExceptionHandlerInfo::catch_block () const [inline]
Definition at line 2008 of file maglev-ir.h.
{ return catch_block_.block_ptr(); }
References v8::internal::maglev::BasicBlockRef::block_ptr(), and catch_block_.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), v8::internal::maglev::MaglevInliner::BuildInlineFunction(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope().
catch_block_ref_address()
BasicBlockRef* v8::internal::maglev::ExceptionHandlerInfo::catch_block_ref_address () [inline]
Definition at line 2006 of file maglev-ir.h.
{ return &catch_block_; }
References catch_block_.
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetTryCatchBlockForNonEagerInlining().
depth()
int v8::internal::maglev::ExceptionHandlerInfo::depth () const [inline]
Definition at line 2010 of file maglev-ir.h.
                    {
    DCHECK_NE(depth_, kNoExceptionHandler);
    DCHECK_NE(depth_, kLazyDeopt);
    return depth_;
  }
References DCHECK_NE, depth_, kLazyDeopt, and kNoExceptionHandler.
Referenced by ExceptionHandlerInfo(), and v8::internal::maglev::LazyDeoptInfo::GetFrameForExceptionHandler().
HasExceptionHandler()
bool v8::internal::maglev::ExceptionHandlerInfo::HasExceptionHandler () const [inline]
Definition at line 2000 of file maglev-ir.h.
{ return depth_ != kNoExceptionHandler; }
References depth_, and kNoExceptionHandler.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), v8::internal::maglev::MaglevInliner::BuildInlineFunction(), v8::internal::maglev::MaglevAssembler::DefineExceptionHandlerPoint(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope().
next()
ExceptionHandlerInfo** v8::internal::maglev::ExceptionHandlerInfo::next () [inline], [private]
Definition at line 2030 of file maglev-ir.h.
{ return &next_; }
References next_.
pc_offset()
int v8::internal::maglev::ExceptionHandlerInfo::pc_offset () const [inline]
Definition at line 2016 of file maglev-ir.h.
{ return pc_offset_; }
References pc_offset_.
Referenced by v8::internal::maglev::MaglevCodeGenerator::EmitMetadata().
set_pc_offset()
void v8::internal::maglev::ExceptionHandlerInfo::set_pc_offset (int offset) [inline]
Definition at line 2017 of file maglev-ir.h.
                                 {
    DCHECK_EQ(pc_offset_, -1);
    DCHECK_NE(offset, -1);
    pc_offset_ = offset;
  }
References DCHECK_EQ, DCHECK_NE, and pc_offset_.
Referenced by v8::internal::maglev::MaglevAssembler::DefineExceptionHandlerPoint().
ShouldLazyDeopt()
bool v8::internal::maglev::ExceptionHandlerInfo::ShouldLazyDeopt () const [inline]
Definition at line 2002 of file maglev-ir.h.
{ return depth_ == kLazyDeopt; }
References depth_, and kLazyDeopt.
Referenced by v8::internal::maglev::StraightForwardRegisterAllocator::AllocateNode(), v8::internal::maglev::MaglevInliner::BuildInlineFunction(), v8::internal::maglev::MaglevCodeGenerator::EmitMetadata(), v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor(), v8::internal::maglev::MaglevGraphBuilder::GetTryCatchBlockForNonEagerInlining(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::ThrowingScope::ThrowingScope().
trampoline_entry()
Label& v8::internal::maglev::ExceptionHandlerInfo::trampoline_entry () [inline]
Definition at line 2004 of file maglev-ir.h.
{ return trampoline_entry_; }
References trampoline_entry_.
Referenced by v8::internal::maglev::MaglevCodeGenerator::EmitMetadata(), and v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::ExceptionHandlerTrampolineBuilder::EmitTrampolineFor().
Member Data Documentation
catch_block_
BasicBlockRef v8::internal::maglev::ExceptionHandlerInfo::catch_block_ [private]
Definition at line 2024 of file maglev-ir.h.
Referenced by catch_block(), and catch_block_ref_address().
depth_
int v8::internal::maglev::ExceptionHandlerInfo::depth_ [private]
Definition at line 2026 of file maglev-ir.h.
Referenced by depth(), HasExceptionHandler(), and ShouldLazyDeopt().
List
friend v8::internal::maglev::ExceptionHandlerInfo::List [private]
Definition at line 2032 of file maglev-ir.h.
next_
ExceptionHandlerInfo* v8::internal::maglev::ExceptionHandlerInfo::next_ = nullptr [private]
Definition at line 2029 of file maglev-ir.h.
Referenced by next().
pc_offset_
int v8::internal::maglev::ExceptionHandlerInfo::pc_offset_ [private]
Definition at line 2027 of file maglev-ir.h.
Referenced by pc_offset(), and set_pc_offset().
trampoline_entry_
Label v8::internal::maglev::ExceptionHandlerInfo::trampoline_entry_ [private]
Definition at line 2025 of file maglev-ir.h.
Referenced by trampoline_entry().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h