v8::internal::compiler::Word32Adapter Class Reference
Public Types
using IntNBinopMatcher = Int32BinopMatcher
using UintNBinopMatcher = Uint32BinopMatcher
using intN_t = int32_t
using uintN_t = uint32_t
Public Member Functions
Word32Adapter (MachineOperatorReducer *reducer)
const Operator * IntNAdd (MachineOperatorBuilder *machine)
Reduction ReplaceIntN (int32_t value)
Reduction ReduceWordNAnd (Node *node)
Reduction ReduceIntNAdd (Node *node)
Reduction TryMatchWordNRor (Node *node)
Node * IntNConstant (int32_t value)
Node * UintNConstant (uint32_t value)
Node * WordNAnd (Node *lhs, Node *rhs)
Reduction ReduceWordNComparisons (Node *node)
Static Public Member Functions
template<typename T >
static bool IsWordNAnd (const T &x)
template<typename T >
static bool IsWordNShl (const T &x)
template<typename T >
static bool IsWordNShr (const T &x)
template<typename T >
static bool IsWordNSar (const T &x)
static bool IsWordNSarShiftOutZeros (const Operator *op)
template<typename T >
static bool IsWordNXor (const T &x)
template<typename T >
static bool IsIntNAdd (const T &x)
template<typename T >
static bool IsIntNMul (const T &x)
static const Operator * WordNEqual (MachineOperatorBuilder *machine)
Static Public Attributes
static constexpr std::size_t WORD_SIZE = 32
Private Attributes
MachineOperatorReducer * r_
Detailed Description
Definition at line 36 of file machine-operator-reducer.cc.
Member Typedef Documentation
intN_t
using v8::internal::compiler::Word32Adapter::intN_t = int32_t
Definition at line 40 of file machine-operator-reducer.cc.
IntNBinopMatcher
using v8::internal::compiler::Word32Adapter::IntNBinopMatcher = Int32BinopMatcher
Definition at line 38 of file machine-operator-reducer.cc.
uintN_t
using v8::internal::compiler::Word32Adapter::uintN_t = uint32_t
Definition at line 41 of file machine-operator-reducer.cc.
UintNBinopMatcher
using v8::internal::compiler::Word32Adapter::UintNBinopMatcher = Uint32BinopMatcher
Definition at line 39 of file machine-operator-reducer.cc.
Constructor & Destructor Documentation
Word32Adapter()
v8::internal::compiler::Word32Adapter::Word32Adapter (MachineOperatorReducer * reducer) [inline], [explicit]
Definition at line 45 of file machine-operator-reducer.cc.
: r_(reducer) {}
Member Function Documentation
IntNAdd()
const Operator* v8::internal::compiler::Word32Adapter::IntNAdd (MachineOperatorBuilder * machine) [inline]
Definition at line 80 of file machine-operator-reducer.cc.
                                                           {
    return machine->Int32Add();
  }
References v8::internal::compiler::MachineOperatorBuilder::Int32Add().
IntNConstant()
Node* v8::internal::compiler::Word32Adapter::IntNConstant (int32_t value) [inline]
Definition at line 92 of file machine-operator-reducer.cc.
{ return r_->Int32Constant(value); }
References v8::internal::compiler::MachineOperatorReducer::Int32Constant(), r_, and v8::internal::value.
IsIntNAdd()
template<typename T >
static bool v8::internal::compiler::Word32Adapter::IsIntNAdd (const T & x) [inline], [static]
Definition at line 72 of file machine-operator-reducer.cc.
                                    {
    return x.IsInt32Add();
  }
IsIntNMul()
template<typename T >
static bool v8::internal::compiler::Word32Adapter::IsIntNMul (const T & x) [inline], [static]
Definition at line 76 of file machine-operator-reducer.cc.
                                    {
    return x.IsInt32Mul();
  }
IsWordNAnd()
template<typename T >
static bool v8::internal::compiler::Word32Adapter::IsWordNAnd (const T & x) [inline], [static]
Definition at line 48 of file machine-operator-reducer.cc.
                                     {
    return x.IsWord32And();
  }
IsWordNSar()
template<typename T >
static bool v8::internal::compiler::Word32Adapter::IsWordNSar (const T & x) [inline], [static]
Definition at line 60 of file machine-operator-reducer.cc.
                                     {
    return x.IsWord32Sar();
  }
IsWordNSarShiftOutZeros()
static bool v8::internal::compiler::Word32Adapter::IsWordNSarShiftOutZeros (const Operator * op) [inline], [static]
Definition at line 63 of file machine-operator-reducer.cc.
                                                          {
    return op->opcode() == IrOpcode::kWord32Sar &&
           OpParameter<ShiftKind>(op) == ShiftKind::kShiftOutZeros;
  }
References v8::internal::compiler::kShiftOutZeros, and v8::internal::compiler::Operator::opcode().
IsWordNShl()
template<typename T >
static bool v8::internal::compiler::Word32Adapter::IsWordNShl (const T & x) [inline], [static]
Definition at line 52 of file machine-operator-reducer.cc.
                                     {
    return x.IsWord32Shl();
  }
IsWordNShr()
template<typename T >
static bool v8::internal::compiler::Word32Adapter::IsWordNShr (const T & x) [inline], [static]
Definition at line 56 of file machine-operator-reducer.cc.
                                     {
    return x.IsWord32Shr();
  }
IsWordNXor()
template<typename T >
static bool v8::internal::compiler::Word32Adapter::IsWordNXor (const T & x) [inline], [static]
Definition at line 68 of file machine-operator-reducer.cc.
                                     {
    return x.IsWord32Xor();
  }
ReduceIntNAdd()
Reduction v8::internal::compiler::Word32Adapter::ReduceIntNAdd (Node * node) [inline]
Definition at line 89 of file machine-operator-reducer.cc.
{ return r_->ReduceInt32Add(node); }
References r_, and v8::internal::compiler::MachineOperatorReducer::ReduceInt32Add().
ReduceWordNAnd()
Reduction v8::internal::compiler::Word32Adapter::ReduceWordNAnd (Node * node) [inline]
Definition at line 88 of file machine-operator-reducer.cc.
{ return r_->ReduceWord32And(node); }
References r_, and v8::internal::compiler::MachineOperatorReducer::ReduceWord32And().
ReduceWordNComparisons()
Reduction v8::internal::compiler::Word32Adapter::ReduceWordNComparisons (Node * node) [inline]
Definition at line 96 of file machine-operator-reducer.cc.
                                               {
    return r_->ReduceWord32Comparisons(node);
  }
References r_, and v8::internal::compiler::MachineOperatorReducer::ReduceWord32Comparisons().
ReplaceIntN()
Reduction v8::internal::compiler::Word32Adapter::ReplaceIntN (int32_t value) [inline]
Definition at line 87 of file machine-operator-reducer.cc.
{ return r_->ReplaceInt32(value); }
References r_, v8::internal::compiler::MachineOperatorReducer::ReplaceInt32(), and v8::internal::value.
TryMatchWordNRor()
Reduction v8::internal::compiler::Word32Adapter::TryMatchWordNRor (Node * node) [inline]
Definition at line 90 of file machine-operator-reducer.cc.
{ return r_->TryMatchWord32Ror(node); }
References r_, and v8::internal::compiler::MachineOperatorReducer::TryMatchWord32Ror().
UintNConstant()
Node* v8::internal::compiler::Word32Adapter::UintNConstant (uint32_t value) [inline]
Definition at line 93 of file machine-operator-reducer.cc.
{ return r_->Uint32Constant(value); }
References r_, v8::internal::compiler::MachineOperatorReducer::Uint32Constant(), and v8::internal::value.
WordNAnd()
Node* v8::internal::compiler::Word32Adapter::WordNAnd (Node * lhs, Node * rhs) [inline]
Definition at line 94 of file machine-operator-reducer.cc.
{ return r_->Word32And(lhs, rhs); }
References r_, and v8::internal::compiler::MachineOperatorReducer::Word32And().
WordNEqual()
static const Operator* v8::internal::compiler::Word32Adapter::WordNEqual (MachineOperatorBuilder * machine) [inline], [static]
Definition at line 83 of file machine-operator-reducer.cc.
                                                                     {
    return machine->Word32Equal();
  }
References v8::internal::compiler::MachineOperatorBuilder::Word32Equal().
Member Data Documentation
r_
MachineOperatorReducer* v8::internal::compiler::Word32Adapter::r_ [private]
Definition at line 101 of file machine-operator-reducer.cc.
Referenced by IntNConstant(), ReduceIntNAdd(), ReduceWordNAnd(), ReduceWordNComparisons(), ReplaceIntN(), TryMatchWordNRor(), UintNConstant(), and WordNAnd().
WORD_SIZE
constexpr std::size_t v8::internal::compiler::Word32Adapter::WORD_SIZE = 32 [static], [constexpr]
Definition at line 43 of file machine-operator-reducer.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/machine-operator-reducer.cc