v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer Class Reference
#include <late-escape-analysis-reducer.h>
Public Member Functions
LateEscapeAnalysisAnalyzer (Graph &graph, Zone *zone)
void Run ()
Private Member Functions
void RecordAllocateUse (OpIndex alloc, OpIndex use)
void CollectUsesAndAllocations ()
void FindRemovableAllocations ()
bool AllocationIsEscaping (OpIndex alloc)
bool EscapesThroughUse (OpIndex alloc, OpIndex using_op_idx)
void MarkToRemove (OpIndex alloc)
Private Attributes
Graph & graph_
Zone * phase_zone_
ZoneAbslFlatHashMap< OpIndex, ZoneVector< OpIndex > > alloc_uses_
ZoneVector< OpIndex > allocs_
Detailed Description
Definition at line 19 of file late-escape-analysis-reducer.h.
Constructor & Destructor Documentation
LateEscapeAnalysisAnalyzer()
v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::LateEscapeAnalysisAnalyzer (Graph & graph, Zone * zone) [inline]
Definition at line 21 of file late-escape-analysis-reducer.h.
      : graph_(graph), phase_zone_(zone), alloc_uses_(zone), allocs_(zone) {}
Member Function Documentation
AllocationIsEscaping()
bool v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::AllocationIsEscaping (OpIndex alloc) [private]
Definition at line 55 of file late-escape-analysis-reducer.cc.
                                                                   {
  if (alloc_uses_.find(alloc) == alloc_uses_.end()) return false;
  for (OpIndex use : alloc_uses_.at(alloc)) {
    if (EscapesThroughUse(alloc, use)) return true;
  }
  // We haven't found any non-store use
  return false;
}
References alloc_uses_, EscapesThroughUse(), and use().
Referenced by FindRemovableAllocations().
CollectUsesAndAllocations()
void v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::CollectUsesAndAllocations () [private]
Definition at line 24 of file late-escape-analysis-reducer.cc.
                                                           {
  for (auto& op : graph_.AllOperations()) {
    if (ShouldSkipOperation(op)) continue;
    OpIndex op_index = graph_.Index(op);
    for (OpIndex input : op.inputs()) {
      if (graph_.Get(input).Is<AllocateOp>()) {
        RecordAllocateUse(input, op_index);
      }
    }
    if (op.Is<AllocateOp>()) {
      allocs_.push_back(op_index);
    }
  }
}
References allocs_, v8::internal::compiler::turboshaft::Graph::AllOperations(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::Graph::Index(), v8::internal::compiler::turboshaft::Operation::Is(), RecordAllocateUse(), and v8::internal::compiler::turboshaft::ShouldSkipOperation().
Referenced by Run().
EscapesThroughUse()
bool v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::EscapesThroughUse (OpIndex alloc, OpIndex using_op_idx) [private]
Definition at line 66 of file late-escape-analysis-reducer.cc.
                                                                         {
  if (ShouldSkipOperation(graph_.Get(alloc))) {
    // {using_op_idx} is an Allocate itself, which has been removed.
    return false;
  }
  const Operation& op = graph_.Get(using_op_idx);
  if (const StoreOp* store_op = op.TryCast<StoreOp>()) {
    // A StoreOp only makes {alloc} escape if it uses {alloc} as the {value} or
    // the {index}. Put otherwise, StoreOp makes {alloc} escape if it writes
    // {alloc}, but not if it writes **to** {alloc}.
    return store_op->value() == alloc;
  }
  return true;
}
References v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::ShouldSkipOperation(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by AllocationIsEscaping().
FindRemovableAllocations()
void v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::FindRemovableAllocations () [private]
Definition at line 39 of file late-escape-analysis-reducer.cc.
                                                          {
  while (!allocs_.empty()) {
    OpIndex current_alloc = allocs_.back();
    allocs_.pop_back();
    if (ShouldSkipOperation(graph_.Get(current_alloc))) {
      // We are re-visiting an allocation that we've actually already removed.
      continue;
    }
    if (!AllocationIsEscaping(current_alloc)) {
      MarkToRemove(current_alloc);
    }
  }
}
References AllocationIsEscaping(), allocs_, v8::internal::compiler::turboshaft::Graph::Get(), graph_, MarkToRemove(), and v8::internal::compiler::turboshaft::ShouldSkipOperation().
Referenced by Run().
MarkToRemove()
void v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::MarkToRemove (OpIndex alloc) [private]
Definition at line 82 of file late-escape-analysis-reducer.cc.
                                                           {
  if (ShouldSkipOptimizationStep()) return;
  graph_.KillOperation(alloc);
  if (alloc_uses_.find(alloc) == alloc_uses_.end()) {
    return;
  }
  // The uses of {alloc} should also be skipped.
  for (OpIndex use : alloc_uses_.at(alloc)) {
    const StoreOp& store = graph_.Get(use).Cast<StoreOp>();
    if (graph_.Get(store.value()).Is<AllocateOp>()) {
      // This store was storing the result of an allocation. Because we now
      // removed this store, we might be able to remove the other allocation
      // as well.
      allocs_.push_back(store.value());
    }
    graph_.KillOperation(use);
  }
}
References alloc_uses_, allocs_, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::compiler::turboshaft::Graph::KillOperation(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), store(), and use().
Referenced by FindRemovableAllocations().
RecordAllocateUse()
void v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::RecordAllocateUse (OpIndex alloc, OpIndex use) [private]
Definition at line 14 of file late-escape-analysis-reducer.cc.
                                                                             {
  auto [it, new_entry] = alloc_uses_.try_emplace(alloc, phase_zone_);
  auto& uses = it->second;
  if (new_entry) {
    uses.reserve(graph_.Get(alloc).saturated_use_count.Get());
  }
  uses.push_back(use);
}
References alloc_uses_, v8::internal::compiler::turboshaft::SaturatedUint8::Get(), v8::internal::compiler::turboshaft::Graph::Get(), graph_, phase_zone_, v8::internal::compiler::turboshaft::Operation::saturated_use_count, and use().
Referenced by CollectUsesAndAllocations().
Run()
void v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::Run ()
Definition at line 9 of file late-escape-analysis-reducer.cc.
                                     {
  CollectUsesAndAllocations();
  FindRemovableAllocations();
}
References CollectUsesAndAllocations(), and FindRemovableAllocations().
Referenced by v8::internal::compiler::turboshaft::LateEscapeAnalysisReducer< Next >::Analyze().
Member Data Documentation
alloc_uses_
ZoneAbslFlatHashMap<OpIndex, ZoneVector<OpIndex> > v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::alloc_uses_ [private]
Definition at line 39 of file late-escape-analysis-reducer.h.
Referenced by AllocationIsEscaping(), MarkToRemove(), and RecordAllocateUse().
allocs_
ZoneVector<OpIndex> v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::allocs_ [private]
Definition at line 43 of file late-escape-analysis-reducer.h.
Referenced by CollectUsesAndAllocations(), FindRemovableAllocations(), and MarkToRemove().
graph_
Graph& v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::graph_ [private]
Definition at line 35 of file late-escape-analysis-reducer.h.
Referenced by CollectUsesAndAllocations(), EscapesThroughUse(), FindRemovableAllocations(), MarkToRemove(), and RecordAllocateUse().
phase_zone_
Zone* v8::internal::compiler::turboshaft::LateEscapeAnalysisAnalyzer::phase_zone_ [private]
Definition at line 36 of file late-escape-analysis-reducer.h.
Referenced by RecordAllocateUse().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/turboshaft/late-escape-analysis-reducer.h
/mnt/V8SourceCode/src/compiler/turboshaft/late-escape-analysis-reducer.cc