v8::internal::compiler::CloneObjectParameters Class Reference
#include <js-operator.h>
Public Member Functions
CloneObjectParameters (FeedbackSource const &feedback, int flags)
FeedbackSource const & feedback () const
int flags () const
Private Attributes
FeedbackSource const feedback_
int const flags_
Detailed Description
Definition at line 770 of file js-operator.h.
Constructor & Destructor Documentation
CloneObjectParameters()
v8::internal::compiler::CloneObjectParameters::CloneObjectParameters (FeedbackSource const & feedback, int flags) [inline]
Definition at line 772 of file js-operator.h.
      : feedback_(feedback), flags_(flags) {}
Member Function Documentation
feedback()
FeedbackSource const& v8::internal::compiler::CloneObjectParameters::feedback () const [inline]
Definition at line 775 of file js-operator.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::hash_value(), and v8::internal::compiler::operator==().
flags()
int v8::internal::compiler::CloneObjectParameters::flags () const [inline]
Definition at line 776 of file js-operator.h.
{ return flags_; }
References flags_.
Referenced by v8::internal::compiler::hash_value(), v8::internal::compiler::operator<<(), and v8::internal::compiler::operator==().
Member Data Documentation
feedback_
FeedbackSource const v8::internal::compiler::CloneObjectParameters::feedback_ [private]
Definition at line 779 of file js-operator.h.
Referenced by feedback().
flags_
int const v8::internal::compiler::CloneObjectParameters::flags_ [private]
Definition at line 780 of file js-operator.h.
Referenced by flags().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h