v8::internal::MarkCompactCollector Class Reference
#include <mark-compact.h>
Classes
class ClearTrivialWeakRefJobItem
class CustomRootBodyMarkingVisitor
class FilterNonTrivialWeakRefJobItem
struct RecordRelocSlotInfo
class SharedHeapObjectVisitor
Public Types
enum class StartCompactionMode { kIncremental
, kAtomic
 }
enum class MarkingWorklistProcessingMode { kDefault
, kProcessRememberedEphemerons
 }
enum class CallOrigin { kIncrementalMarkingStep
, kAtomicGC
 }
enum class EphemeronResult { kUnresolved
, kMarkedValue
, kResolved
 }
Public Member Functions
template<MarkingWorklistProcessingMode mode = MarkingWorklistProcessingMode::kDefault>
std::pair< size_t, size_t > ProcessMarkingWorklist (v8::base::TimeDelta max_duration, size_t max_bytes_to_process)
void TearDown ()
void CollectGarbage ()
void CollectEvacuationCandidates (PagedSpace *space)
void AddEvacuationCandidate (PageMetadata *p)
void Prepare ()
void FinishConcurrentMarking ()
bool StartCompaction (StartCompactionMode mode)
void StartMarking (std::shared_ptr<::heap::base::IncrementalMarkingSchedule > schedule={})
bool is_compacting () const
void AddTransitionArray (Tagged< TransitionArray > array)
void RecordStrongDescriptorArraysForWeakening (GlobalHandleVector< DescriptorArray > strong_descriptor_arrays)
void VerifyMarking ()
unsigned epoch () const
base::EnumSet< CodeFlushMode > code_flush_mode () const
MarkingWorklists * marking_worklists ()
MarkingWorklists::Local * local_marking_worklists () const
WeakObjects * weak_objects ()
WeakObjects::Local * local_weak_objects ()
bool UseBackgroundThreadsInCycle () const
void MaybeEnableBackgroundThreadsInCycle (CallOrigin origin)
Heap * heap ()
MarkCompactCollector (Heap *heap)
~MarkCompactCollector ()
Static Public Member Functions
static bool IsUnmarkedHeapObject (Heap *heap, FullObjectSlot p)
static bool IsUnmarkedSharedHeapObject (Heap *heap, FullObjectSlot p)
static bool IsOnEvacuationCandidate (Tagged< MaybeObject > obj)
static bool ShouldRecordRelocSlot (Tagged< InstructionStream > host, RelocInfo *rinfo, Tagged< HeapObject > target)
static RecordRelocSlotInfo ProcessRelocInfo (Tagged< InstructionStream > host, RelocInfo *rinfo, Tagged< HeapObject > target)
static void RecordRelocSlot (Tagged< InstructionStream > host, RelocInfo *rinfo, Tagged< HeapObject > target)
template<typename THeapObjectSlot >
static void RecordSlot (Tagged< HeapObject > object, THeapObjectSlot slot, Tagged< HeapObject > target)
template<typename THeapObjectSlot >
static void RecordSlot (MemoryChunk *source_chunk, THeapObjectSlot slot, Tagged< HeapObject > target)
Private Types
using ResizeNewSpaceMode = Heap::ResizeNewSpaceMode
Private Member Functions
void ComputeEvacuationHeuristics (size_t area_size, int *target_fragmentation_percent, size_t *max_evacuated_bytes)
void RecordObjectStats ()
void Finish ()
void SweepArrayBufferExtensions ()
void MarkLiveObjects ()
void MarkObject (Tagged< HeapObject > host, Tagged< HeapObject > obj, MarkingHelper::WorklistTarget target_worklist)
void MarkRootObject (Root root, Tagged< HeapObject > obj, MarkingHelper::WorklistTarget target_worklist)
void MarkRoots (RootVisitor *root_visitor)
void MarkRootsFromConservativeStack (RootVisitor *root_visitor)
void MarkObjectsFromClientHeaps ()
void MarkObjectsFromClientHeap (Isolate *client)
void PinPreciseRootsIfNeeded ()
void UpdatePointersInClientHeaps ()
void UpdatePointersInClientHeap (Isolate *client)
void UpdatePointersInPointerTables ()
void MarkTransitiveClosure ()
void VerifyEphemeronMarking ()
void ProcessTopOptimizedFrame (ObjectVisitor *visitor, Isolate *isolate)
EphemeronResult ApplyEphemeronSemantics (Tagged< HeapObject > key, Tagged< HeapObject > value)
bool ProcessEphemeron (Tagged< HeapObject > key, Tagged< HeapObject > value)
bool MarkTransitiveClosureUntilFixpoint ()
void MarkTransitiveClosureLinear ()
bool ProcessEphemerons ()
void PerformWrapperTracing ()
void RetainMaps ()
void ClearNonLiveReferences ()
void MarkDependentCodeForDeoptimization ()
bool SpecialClearMapSlot (Tagged< HeapObject > host, Tagged< Map > dead_target, HeapObjectSlot slot)
void ClearPotentialSimpleMapTransition (Tagged< Map > dead_target)
void ClearPotentialSimpleMapTransition (Tagged< Map > map, Tagged< Map > dead_target)
void FlushBytecodeFromSFI (Tagged< SharedFunctionInfo > shared_info)
void ProcessOldCodeCandidates ()
bool ProcessOldBytecodeSFI (Tagged< SharedFunctionInfo > flushing_candidate)
bool ProcessOldBaselineSFI (Tagged< SharedFunctionInfo > flushing_candidate)
void FlushSFI (Tagged< SharedFunctionInfo > sfi, bool bytecode_already_decompiled)
void ProcessFlushedBaselineCandidates ()
void ClearFlushedJsFunctions ()
void ClearFullMapTransitions ()
void TrimDescriptorArray (Tagged< Map > map, Tagged< DescriptorArray > descriptors)
void TrimEnumCache (Tagged< Map > map, Tagged< DescriptorArray > descriptors)
bool CompactTransitionArray (Tagged< Map > map, Tagged< TransitionArray > transitions, Tagged< DescriptorArray > descriptors)
bool TransitionArrayNeedsCompaction (Tagged< TransitionArray > transitions, int num_transitions)
void WeakenStrongDescriptorArrays ()
void ClearWeakCollections ()
void ClearTrivialWeakReferences ()
void ClearTrustedWeakReferences ()
template<typename TObjectAndSlot , typename TMaybeSlot >
void ClearWeakReferences (WeakObjects::WeakObjectWorklist< TObjectAndSlot >::Local &worklist, Tagged< HeapObjectReference > cleared_weak_ref)
void FilterNonTrivialWeakReferences ()
void ClearNonTrivialWeakReferences ()
void ClearJSWeakRefs ()
void Sweep ()
void StartSweepSpace (PagedSpace *space)
void EvacuatePrologue ()
void EvacuateEpilogue ()
void Evacuate ()
void EvacuatePagesInParallel ()
void UpdatePointersAfterEvacuation ()
void ReleaseEvacuationCandidates ()
void ReleasePage (PagedSpaceBase *space, PageMetadata *page)
size_t PostProcessAbortedEvacuationCandidates ()
void ReportAbortedEvacuationCandidateDueToOOM (Address failed_start, PageMetadata *page)
void ReportAbortedEvacuationCandidateDueToFlags (PageMetadata *page, MemoryChunk *chunk)
int NumberOfParallelEphemeronVisitingTasks (size_t elements)
void RightTrimDescriptorArray (Tagged< DescriptorArray > array, int descriptors_to_trim)
void StartSweepNewSpace ()
void SweepLargeSpace (LargeObjectSpace *space)
void ResetAndRelinkBlackAllocatedPage (PagedSpace *, PageMetadata *)
Private Attributes
Heap *const heap_
base::Mutex mutex_
base::Semaphore page_parallel_job_semaphore_ {0}
const bool uses_shared_heap_
const bool is_shared_space_isolate_
bool compacting_ = false
bool black_allocation_ = false
bool have_code_to_deoptimize_ = false
bool parallel_marking_ = false
MarkingWorklists marking_worklists_
std::unique_ptr< MarkingWorklists::Local > local_marking_worklists_
WeakObjects weak_objects_
std::unique_ptr< MainMarkingVisitor > marking_visitor_
std::unique_ptr< WeakObjects::Local > local_weak_objects_
NativeContextInferrer native_context_inferrer_
NativeContextStats native_context_stats_
std::vector< GlobalHandleVector< DescriptorArray > > strong_descriptor_arrays_
base::Mutex strong_descriptor_arrays_mutex_
std::vector< PageMetadata * > evacuation_candidates_
std::vector< PageMetadata * > old_space_evacuation_pages_
std::vector< PageMetadata * > new_space_evacuation_pages_
std::vector< std::pair< Address, PageMetadata * > > aborted_evacuation_candidates_due_to_oom_
std::vector< PageMetadata * > aborted_evacuation_candidates_due_to_flags_
std::vector< LargePageMetadata * > promoted_large_pages_
std::vector< MutablePageMetadata * > queued_pages_to_be_freed_
KeyToValues key_to_values_
MarkingState *const marking_state_
NonAtomicMarkingState *const non_atomic_marking_state_
Sweeper *const sweeper_
unsigned epoch_ = 0
base::EnumSet< CodeFlushMode > code_flush_mode_
std::vector< PageMetadata * > empty_new_space_pages_to_be_swept_
bool use_background_threads_in_cycle_ = false
bool in_conservative_stack_scanning_ = false
Static Private Attributes
static const int kEphemeronChunkSize = 8 * KB
Friends
class Evacuator
class RecordMigratedSlotVisitor
class RootMarkingVisitor
class PrecisePagePinningVisitor
Detailed Description
Definition at line 57 of file mark-compact.h.
Member Typedef Documentation
ResizeNewSpaceMode
using v8::internal::MarkCompactCollector::ResizeNewSpaceMode = Heap::ResizeNewSpaceMode [private]
Definition at line 195 of file mark-compact.h.
Member Enumeration Documentation
CallOrigin
enum v8::internal::MarkCompactCollector::CallOrigin [strong]
Enumerator
kIncrementalMarkingStep
kAtomicGC
Definition at line 72 of file mark-compact.h.
                        {
    kIncrementalMarkingStep,
    kAtomicGC,
  };
EphemeronResult
enum v8::internal::MarkCompactCollector::EphemeronResult [strong]
Enumerator
kUnresolved
kMarkedValue
kResolved
Definition at line 77 of file mark-compact.h.
                             {
    // Both key and value are still unmarked.
    kUnresolved,
    // Value got marked because key was already marked.
    kMarkedValue,
    // Value is already marked or always live in this GC.
    kResolved,
  };
MarkingWorklistProcessingMode
enum v8::internal::MarkCompactCollector::MarkingWorklistProcessingMode [strong]
Enumerator
kDefault
kProcessRememberedEphemerons
Definition at line 67 of file mark-compact.h.
                                           {
    kDefault,
    kProcessRememberedEphemerons
  };
StartCompactionMode
enum v8::internal::MarkCompactCollector::StartCompactionMode [strong]
Enumerator
kIncremental
kAtomic
Definition at line 62 of file mark-compact.h.
                                 {
    kIncremental,
    kAtomic,
  };
Constructor & Destructor Documentation
MarkCompactCollector()
v8::internal::MarkCompactCollector::MarkCompactCollector (Heap * heap) [explicit]
Definition at line 282 of file mark-compact.cc.
    : heap_(heap),
#ifdef DEBUG
      state_(IDLE),
#endif
      uses_shared_heap_(heap_->isolate()->has_shared_space()),
      is_shared_space_isolate_(heap_->isolate()->is_shared_space_isolate()),
      marking_state_(heap_->marking_state()),
      non_atomic_marking_state_(heap_->non_atomic_marking_state()),
      sweeper_(heap_->sweeper()) {
}
 MarkCompactCollector()
v8::internal::MarkCompactCollector::~MarkCompactCollector () [default]
Member Function Documentation
AddEvacuationCandidate()
void v8::internal::MarkCompactCollector::AddEvacuationCandidate (PageMetadata * p)
Definition at line 307 of file mark-compact.cc.
                                                                 {
  DCHECK(!p->Chunk()->NeverEvacuate());
  DCHECK(!p->Chunk()->IsFlagSet(MemoryChunk::BLACK_ALLOCATED));
  if (v8_flags.trace_evacuation_candidates) {
    PrintIsolate(
        heap_->isolate(),
        "Evacuation candidate: Free bytes: %6zu. Free Lists length: %4d.\n",
        p->area_size() - p->allocated_bytes(), p->ComputeFreeListsLength());
  }
  p->MarkEvacuationCandidate();
  evacuation_candidates_.push_back(p);
}
References v8::internal::MemoryChunkMetadata::allocated_bytes(), v8::internal::MemoryChunkMetadata::area_size(), v8::internal::MemoryChunk::BLACK_ALLOCATED, v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MutablePageMetadata::ComputeFreeListsLength(), v8::internal::DCHECK(), evacuation_candidates_, heap_, v8::internal::MemoryChunk::IsFlagSet(), v8::internal::Heap::isolate(), v8::internal::PageMetadata::MarkEvacuationCandidate(), v8::internal::MemoryChunk::NeverEvacuate(), v8::internal::PrintIsolate(), and v8::internal::v8_flags.
Referenced by CollectEvacuationCandidates().
AddTransitionArray()
void v8::internal::MarkCompactCollector::AddTransitionArray (Tagged< TransitionArray > array) [inline]
Definition at line 104 of file mark-compact-inl.h.
                                                                           {
  local_weak_objects()->transition_arrays_local.Push(array);
}
References local_weak_objects().
ApplyEphemeronSemantics()
MarkCompactCollector::EphemeronResult v8::internal::MarkCompactCollector::ApplyEphemeronSemantics (Tagged< HeapObject > key, Tagged< HeapObject > value) [private]
Definition at line 2286 of file mark-compact.cc.
                                                                        {
  // Objects in the shared heap are prohibited from being used as keys in
  // WeakMaps and WeakSets and therefore cannot be ephemeron keys, because that
  // would enable thread local -> shared heap edges.
  DCHECK(!HeapLayout::InWritableSharedSpace(key));
  // Usually values that should not be marked are not added to the ephemeron
  // worklist. However, minor collection during incremental marking may promote
  // strings from the younger generation into the shared heap. This
  // ShouldMarkObject call catches those cases.
  const auto target_worklist = MarkingHelper::ShouldMarkObject(heap_, value);
  if (!target_worklist) {
    // The value doesn't need to be marked in this GC, so no need to track
    // ephemeron further.
    return EphemeronResult::kResolved;
  }
  if (MarkingHelper::IsMarkedOrAlwaysLive(heap_, marking_state_, key)) {
    if (MarkingHelper::TryMarkAndPush(heap_, local_marking_worklists_.get(),
                                      marking_state_, target_worklist.value(),
                                      value)) {
      return EphemeronResult::kMarkedValue;
    } else {
      return EphemeronResult::kResolved;
    }
  } else {
    if (marking_state_->IsMarked(value)) {
      return EphemeronResult::kResolved;
    } else {
      return EphemeronResult::kUnresolved;
    }
  }
}
References DCHECK, v8::internal::key, and v8::internal::value.
ClearFlushedJsFunctions()
void v8::internal::MarkCompactCollector::ClearFlushedJsFunctions () [private]
Definition at line 3535 of file mark-compact.cc.
                                                   {
  DCHECK(v8_flags.flush_bytecode ||
         weak_objects_.flushed_js_functions.IsEmpty());
  Tagged<JSFunction> flushed_js_function;
  while (local_weak_objects()->flushed_js_functions_local.Pop(
      &flushed_js_function)) {
    auto gc_notify_updated_slot = [](Tagged<HeapObject> object, ObjectSlot slot,
                                     Tagged<Object> target) {
      RecordSlot(object, slot, Cast<HeapObject>(target));
    };
    flushed_js_function->ResetIfCodeFlushed(heap_->isolate(),
                                            gc_notify_updated_slot);
  }
}
References DCHECK, and v8::internal::v8_flags.
ClearFullMapTransitions()
void v8::internal::MarkCompactCollector::ClearFullMapTransitions () [private]
Definition at line 3580 of file mark-compact.cc.
                                                   {
  Tagged<TransitionArray> array;
  Isolate* const isolate = heap_->isolate();
  ReadOnlyRoots roots(isolate);
  while (local_weak_objects()->transition_arrays_local.Pop(&array)) {
    int num_transitions = array->number_of_transitions();
    if (num_transitions > 0) {
        Tagged<Map> map;
        // The array might contain "undefined" elements because it's not yet
        // filled. Allow it.
        if (array->GetTargetIfExists(0, isolate, &map)) {
          DCHECK(!map.is_null()); // Weak pointers aren't cleared yet.
          Tagged<Object> constructor_or_back_pointer =
              map->constructor_or_back_pointer();
          if (IsSmi(constructor_or_back_pointer)) {
            DCHECK(isolate->has_active_deserializer());
            DCHECK_EQ(constructor_or_back_pointer,
                      Smi::uninitialized_deserialization_value());
            continue;
          }
          Tagged<Map> parent = Cast<Map>(map->constructor_or_back_pointer());
          const bool parent_is_alive = MarkingHelper::IsMarkedOrAlwaysLive(
              heap_, non_atomic_marking_state_, parent);
          Tagged<DescriptorArray> descriptors =
              parent_is_alive ? parent->instance_descriptors(isolate)
                              : Tagged<DescriptorArray>();
          bool descriptors_owner_died =
              CompactTransitionArray(parent, array, descriptors);
          if (descriptors_owner_died) {
            TrimDescriptorArray(parent, descriptors);
          }
        }
      }
  }
}
References v8::internal::constructor_or_back_pointer, DCHECK, DCHECK_EQ, v8::internal::Isolate::has_active_deserializer(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::Factory::isolate(), v8::internal::IsSmi(), and v8::internal::Tagged< DescriptorArray >.
ClearJSWeakRefs()
void v8::internal::MarkCompactCollector::ClearJSWeakRefs () [private]
Definition at line 3938 of file mark-compact.cc.
                                           {
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_CLEAR_JS_WEAK_REFERENCES);
  Tagged<JSWeakRef> weak_ref;
  Isolate* const isolate = heap_->isolate();
  while (local_weak_objects()->js_weak_refs_local.Pop(&weak_ref)) {
    Tagged<HeapObject> target = Cast<HeapObject>(weak_ref->target());
    if (MarkingHelper::IsUnmarkedAndNotAlwaysLive(
            heap_, non_atomic_marking_state_, target)) {
      weak_ref->set_target(ReadOnlyRoots(isolate).undefined_value());
    } else {
      // The value of the JSWeakRef is alive.
      ObjectSlot slot = weak_ref->RawField(JSWeakRef::kTargetOffset);
      RecordSlot(weak_ref, slot, target);
    }
  }
  Tagged<WeakCell> weak_cell;
  while (local_weak_objects()->weak_cells_local.Pop(&weak_cell)) {
    auto gc_notify_updated_slot = [](Tagged<HeapObject> object, ObjectSlot slot,
                                     Tagged<Object> target) {
      if (IsHeapObject(target)) {
        RecordSlot(object, slot, Cast<HeapObject>(target));
      }
    };
    Tagged<HeapObject> target = Cast<HeapObject>(weak_cell->target());
    if (MarkingHelper::IsUnmarkedAndNotAlwaysLive(
            heap_, non_atomic_marking_state_, target)) {
      DCHECK(Object::CanBeHeldWeakly(target));
      // The value of the WeakCell is dead.
      Tagged<JSFinalizationRegistry> finalization_registry =
          Cast<JSFinalizationRegistry>(weak_cell->finalization_registry());
      if (!finalization_registry->scheduled_for_cleanup()) {
        heap_->EnqueueDirtyJSFinalizationRegistry(finalization_registry,
                                                  gc_notify_updated_slot);
      }
      // We're modifying the pointers in WeakCell and JSFinalizationRegistry
      // during GC; thus we need to record the slots it writes. The normal write
      // barrier is not enough, since it's disabled before GC.
      weak_cell->Nullify(isolate, gc_notify_updated_slot);
      DCHECK(finalization_registry->NeedsCleanup());
      DCHECK(finalization_registry->scheduled_for_cleanup());
    } else {
      // The value of the WeakCell is alive.
      ObjectSlot slot = weak_cell->RawField(WeakCell::kTargetOffset);
      RecordSlot(weak_cell, slot, Cast<HeapObject>(*slot));
    }
    Tagged<HeapObject> unregister_token = weak_cell->unregister_token();
    if (MarkingHelper::IsUnmarkedAndNotAlwaysLive(
            heap_, non_atomic_marking_state_, unregister_token)) {
      DCHECK(Object::CanBeHeldWeakly(unregister_token));
      // The unregister token is dead. Remove any corresponding entries in the
      // key map. Multiple WeakCell with the same token will have all their
      // unregister_token field set to undefined when processing the first
      // WeakCell. Like above, we're modifying pointers during GC, so record the
      // slots.
      Tagged<JSFinalizationRegistry> finalization_registry =
          Cast<JSFinalizationRegistry>(weak_cell->finalization_registry());
      finalization_registry->RemoveUnregisterToken(
          unregister_token, isolate,
          JSFinalizationRegistry::kKeepMatchedCellsInRegistry,
          gc_notify_updated_slot);
    } else {
      // The unregister_token is alive.
      ObjectSlot slot = weak_cell->RawField(WeakCell::kUnregisterTokenOffset);
      RecordSlot(weak_cell, slot, Cast<HeapObject>(*slot));
    }
  }
  heap_->PostFinalizationRegistryCleanupTaskIfNeeded();
}
References DCHECK, v8::internal::InstanceTypeChecker::IsHeapObject(), v8::internal::Factory::isolate(), and TRACE_GC.
ClearNonLiveReferences()
void v8::internal::MarkCompactCollector::ClearNonLiveReferences () [private]
Definition at line 2922 of file mark-compact.cc.
                                                  {
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_CLEAR);
  Isolate* const isolate = heap_->isolate();
  if (isolate->OwnsStringTables()) {
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::MC_CLEAR_STRING_FORWARDING_TABLE);
    // Clear string forwarding table. Live strings are transitioned to
    // ThinStrings/ExternalStrings in the cleanup process, if this is a GC
    // without stack.
    // Clearing the string forwarding table must happen before clearing the
    // string table, as entries in the forwarding table can keep internalized
    // strings alive.
    FullStringForwardingTableCleaner forwarding_table_cleaner(heap_);
    if (!heap_->IsGCWithStack() ||
        v8_flags.transition_strings_during_gc_with_stack) {
      forwarding_table_cleaner.TransitionStrings();
    } else {
      forwarding_table_cleaner.ProcessFullWithStack();
    }
  }
  {
    // Clear Isolate::topmost_script_having_context slot if it's not alive.
    Tagged<Object> maybe_caller_context =
        isolate->topmost_script_having_context();
    if (maybe_caller_context.IsHeapObject() &&
        MarkingHelper::IsUnmarkedAndNotAlwaysLive(
            heap_, marking_state_, Cast<HeapObject>(maybe_caller_context))) {
      isolate->clear_topmost_script_having_context();
    }
  }
  std::unique_ptr<JobHandle> clear_string_table_job_handle;
  {
    auto job = std::make_unique<ParallelClearingJob>(this);
    auto job_item = std::make_unique<ClearStringTableJobItem>(isolate);
    const uint64_t trace_id = job_item->trace_id();
    job->Add(std::move(job_item));
    TRACE_GC_NOTE_WITH_FLOW("ClearStringTableJob started", trace_id,
                            TRACE_EVENT_FLAG_FLOW_OUT);
    if (isolate->is_shared_space_isolate() &&
        isolate->shared_struct_type_registry()) {
      auto registry_job_item =
          std::make_unique<ClearSharedStructTypeRegistryJobItem>(isolate);
      job->Add(std::move(registry_job_item));
    }
    clear_string_table_job_handle = V8::GetCurrentPlatform()->CreateJob(
        TaskPriority::kUserBlocking, std::move(job));
  }
  if (v8_flags.parallel_weak_ref_clearing && UseBackgroundThreadsInCycle()) {
    clear_string_table_job_handle->NotifyConcurrencyIncrease();
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_CLEAR_EXTERNAL_STRING_TABLE);
    ExternalStringTableCleanerVisitor<ExternalStringTableCleaningMode::kAll>
        external_visitor(heap_);
    heap_->external_string_table_.IterateAll(&external_visitor);
    heap_->external_string_table_.CleanUpAll();
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_CLEAR_WEAK_GLOBAL_HANDLES);
    // We depend on `IterateWeakRootsForPhantomHandles()` being called before
    // `ProcessOldCodeCandidates()` in order to identify flushed bytecode in the
    // CPU profiler.
    isolate->global_handles()->IterateWeakRootsForPhantomHandles(
        &IsUnmarkedHeapObject);
    isolate->traced_handles()->ResetDeadNodes(&IsUnmarkedHeapObject);
    if (isolate->is_shared_space_isolate()) {
      isolate->global_safepoint()->IterateClientIsolates([](Isolate* client) {
        client->global_handles()->IterateWeakRootsForPhantomHandles(
            &IsUnmarkedSharedHeapObject);
        // No need to reset traced handles since they are always strong.
      });
    }
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_CLEAR_FLUSHABLE_BYTECODE);
    // `ProcessFlushedBaselineCandidates()` must be called after
    // `ProcessOldCodeCandidates()` so that we correctly set the code object on
    // the JSFunction after flushing.
    ProcessOldCodeCandidates();
#ifndef V8_ENABLE_LEAPTIERING
    // With leaptiering this is done during sweeping.
    ProcessFlushedBaselineCandidates();
#endif // !V8_ENABLE_LEAPTIERING
  }
#ifdef V8_ENABLE_LEAPTIERING
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_SWEEP_JS_DISPATCH_TABLE);
    JSDispatchTable* jdt = IsolateGroup::current()->js_dispatch_table();
    Tagged<Code> compile_lazy =
        heap_->isolate()->builtins()->code(Builtin::kCompileLazy);
    jdt->Sweep(heap_->js_dispatch_table_space(), isolate->counters(),
               [&](JSDispatchEntry& entry) {
                 Tagged<Code> code = entry.GetCode();
                 if (MarkingHelper::IsUnmarkedAndNotAlwaysLive(
                         heap_, marking_state_, code)) {
                   // Baseline flushing: if the Code object is no longer alive,
                   // it must have been flushed and so we replace it with the
                   // CompileLazy builtin. Once we use leaptiering on all
                   // platforms, we can probably simplify the other code related
                   // to baseline flushing.
                   // Currently, we can also see optimized code here. This
                   // happens when a FeedbackCell for which no JSFunctions
                   // remain references optimized code. However, in that case we
                   // probably do want to delete the optimized code, so that is
                   // working as intended. It does mean, however, that we cannot
                   // DCHECK here that we only see baseline code.
                   DCHECK(code->kind() == CodeKind::FOR_TESTING ||
                          code->kind() == CodeKind::BASELINE ||
                          code->kind() == CodeKind::MAGLEV ||
                          code->kind() == CodeKind::TURBOFAN_JS);
                   entry.SetCodeAndEntrypointPointer(
                       compile_lazy.ptr(), compile_lazy->instruction_start());
                 }
               });
  }
#endif // V8_ENABLE_LEAPTIERING
  // TODO(olivf, 42204201): If we make the bytecode accessible from the dispatch
  // table this could also be implemented during JSDispatchTable::Sweep.
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_CLEAR_FLUSHED_JS_FUNCTIONS);
    ClearFlushedJsFunctions();
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_CLEAR_WEAK_LISTS);
    // Process the weak references.
    MarkCompactWeakObjectRetainer mark_compact_object_retainer(heap_,
                                                               marking_state_);
    heap_->ProcessAllWeakReferences(&mark_compact_object_retainer);
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_CLEAR_MAPS);
    // ClearFullMapTransitions must be called before weak references are
    // cleared.
    ClearFullMapTransitions();
    // Weaken recorded strong DescriptorArray objects. This phase can
    // potentially move everywhere after `ClearFullMapTransitions()`.
    WeakenStrongDescriptorArrays();
  }
  // Start two parallel jobs: one for clearing trivial weak references and one
  // for filtering out non-trivial weak references that will not be cleared.
  // Both jobs read the values of weak references and the corresponding
  // mark bits. They cannot start before the following methods have finished,
  // because these may change the values of weak references and/or mark more
  // objects, thus creating data races:
  // - ProcessOldCodeCandidates
  // - ProcessAllWeakReferences
  // - ClearFullMapTransitions
  // - WeakenStrongDescriptorArrays
  // The two jobs could be merged but it's convenient to keep them separate,
  // as they are joined at different times. The filtering job must be joined
  // before proceeding to the actual clearing of non-trivial weak references,
  // whereas the job for clearing trivial weak references can be joined at the
  // end of this method.
  std::unique_ptr<JobHandle> clear_trivial_weakrefs_job_handle;
  {
    auto job = std::make_unique<ParallelClearingJob>(this);
    auto job_item = std::make_unique<ClearTrivialWeakRefJobItem>(this);
    const uint64_t trace_id = job_item->trace_id();
    job->Add(std::move(job_item));
    TRACE_GC_NOTE_WITH_FLOW("ClearTrivialWeakRefJob started", trace_id,
                            TRACE_EVENT_FLAG_FLOW_OUT);
    clear_trivial_weakrefs_job_handle = V8::GetCurrentPlatform()->CreateJob(
        TaskPriority::kUserBlocking, std::move(job));
  }
  std::unique_ptr<JobHandle> filter_non_trivial_weakrefs_job_handle;
  {
    auto job = std::make_unique<ParallelClearingJob>(this);
    auto job_item = std::make_unique<FilterNonTrivialWeakRefJobItem>(this);
    const uint64_t trace_id = job_item->trace_id();
    job->Add(std::move(job_item));
    TRACE_GC_NOTE_WITH_FLOW("FilterNonTrivialWeakRefJob started", trace_id,
                            TRACE_EVENT_FLAG_FLOW_OUT);
    filter_non_trivial_weakrefs_job_handle =
        V8::GetCurrentPlatform()->CreateJob(TaskPriority::kUserBlocking,
                                            std::move(job));
  }
  if (v8_flags.parallel_weak_ref_clearing && UseBackgroundThreadsInCycle()) {
    clear_trivial_weakrefs_job_handle->NotifyConcurrencyIncrease();
    filter_non_trivial_weakrefs_job_handle->NotifyConcurrencyIncrease();
  }
#ifdef V8_COMPRESS_POINTERS
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_SWEEP_EXTERNAL_POINTER_TABLE);
    // External pointer table sweeping needs to happen before evacuating live
    // objects as it may perform table compaction, which requires objects to
    // still be at the same location as during marking.
    //
    // Note we explicitly do NOT run SweepAndCompact on
    // read_only_external_pointer_space since these entries are all immortal by
    // definition.
    isolate->external_pointer_table().EvacuateAndSweepAndCompact(
        isolate->heap()->old_external_pointer_space(),
        isolate->heap()->young_external_pointer_space(), isolate->counters());
    isolate->heap()->young_external_pointer_space()->AssertEmpty();
    if (isolate->owns_shareable_data()) {
      isolate->shared_external_pointer_table().SweepAndCompact(
          isolate->shared_external_pointer_space(), isolate->counters());
    }
    isolate->cpp_heap_pointer_table().SweepAndCompact(
        isolate->heap()->cpp_heap_pointer_space(), isolate->counters());
  }
#endif // V8_COMPRESS_POINTERS
#ifdef V8_ENABLE_SANDBOX
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_SWEEP_TRUSTED_POINTER_TABLE);
    isolate->trusted_pointer_table().Sweep(heap_->trusted_pointer_space(),
                                           isolate->counters());
    if (isolate->owns_shareable_data()) {
      isolate->shared_trusted_pointer_table().Sweep(
          isolate->shared_trusted_pointer_space(), isolate->counters());
    }
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_SWEEP_CODE_POINTER_TABLE);
    IsolateGroup::current()->code_pointer_table()->Sweep(
        heap_->code_pointer_space(), isolate->counters());
  }
#endif // V8_ENABLE_SANDBOX
#ifdef V8_ENABLE_WEBASSEMBLY
  {
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::MC_SWEEP_WASM_CODE_POINTER_TABLE);
    wasm::GetProcessWideWasmCodePointerTable()->SweepSegments();
  }
#endif // V8_ENABLE_WEBASSEMBLY
  {
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::MC_CLEAR_WEAK_REFERENCES_JOIN_FILTER_JOB);
    filter_non_trivial_weakrefs_job_handle->Join();
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_WEAKNESS_HANDLING);
    ClearNonTrivialWeakReferences();
    ClearWeakCollections();
    ClearJSWeakRefs();
  }
  PROFILE(heap_->isolate(), WeakCodeClearEvent());
  {
    // This method may be called from within a DisallowDeoptimizations scope.
    // Temporarily allow deopts for marking code for deopt. This is not doing
    // the deopt yet and the actual deopts will be bailed out on later if the
    // current safepoint is not safe for deopts.
    // TODO(357636610): Reconsider whether the DisallowDeoptimization scopes are
    // truly needed.
    AllowDeoptimization allow_deoptimization(heap_->isolate());
    MarkDependentCodeForDeoptimization();
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_CLEAR_JOIN_JOB);
    clear_string_table_job_handle->Join();
    clear_trivial_weakrefs_job_handle->Join();
  }
  if (v8_flags.sticky_mark_bits) {
    // TODO(333906585): Consider adjusting the dchecks that happen on clearing
    // and move this phase into MarkingBarrier::DeactivateAll.
    heap()->DeactivateMajorGCInProgressFlag();
  }
  DCHECK(weak_objects_.transition_arrays.IsEmpty());
  DCHECK(weak_objects_.weak_references_trivial.IsEmpty());
  DCHECK(weak_objects_.weak_references_non_trivial.IsEmpty());
  DCHECK(weak_objects_.weak_references_non_trivial_unmarked.IsEmpty());
  DCHECK(weak_objects_.weak_objects_in_code.IsEmpty());
  DCHECK(weak_objects_.js_weak_refs.IsEmpty());
  DCHECK(weak_objects_.weak_cells.IsEmpty());
  DCHECK(weak_objects_.code_flushing_candidates.IsEmpty());
  DCHECK(weak_objects_.flushed_js_functions.IsEmpty());
#ifndef V8_ENABLE_LEAPTIERING
  DCHECK(weak_objects_.baseline_flushing_candidates.IsEmpty());
#endif // !V8_ENABLE_LEAPTIERING
}
References v8::internal::Isolate::clear_topmost_script_having_context(), v8::internal::Isolate::counters(), v8::Platform::CreateJob(), v8::debug::GetCurrentPlatform(), v8::internal::Isolate::global_handles(), v8::internal::Isolate::global_safepoint(), v8::internal::Isolate::is_shared_space_isolate(), v8::internal::TaggedImpl< kRefType, StorageType >::IsHeapObject(), v8::internal::Factory::isolate(), v8::internal::GlobalSafepoint::IterateClientIsolates(), v8::internal::GlobalHandles::IterateWeakRootsForPhantomHandles(), v8::kUserBlocking, v8::internal::Isolate::OwnsStringTables(), v8::internal::FullStringForwardingTableCleaner::ProcessFullWithStack(), v8::internal::TracedHandles::ResetDeadNodes(), v8::internal::Isolate::shared_struct_type_registry(), v8::internal::Isolate::topmost_script_having_context(), TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC, TRACE_GC_NOTE_WITH_FLOW, v8::internal::Isolate::traced_handles(), v8::internal::FullStringForwardingTableCleaner::TransitionStrings(), and v8::internal::v8_flags.
Referenced by CollectGarbage().
ClearNonTrivialWeakReferences()
void v8::internal::MarkCompactCollector::ClearNonTrivialWeakReferences () [private]
Definition at line 3915 of file mark-compact.cc.
                                                         {
  TRACE_GC(heap_->tracer(),
           GCTracer::Scope::MC_CLEAR_WEAK_REFERENCES_NON_TRIVIAL);
  HeapObjectAndSlot slot;
  Tagged<HeapObjectReference> cleared_weak_ref = ClearedValue(heap_->isolate());
  while (local_weak_objects()->weak_references_non_trivial_unmarked_local.Pop(
      &slot)) {
    // The slot may not have been overwritten since it was filtered, so we can
    // directly read its value.
    Tagged<HeapObject> value = (*slot.slot).GetHeapObjectAssumeWeak();
    DCHECK(!IsWeakCell(value));
    DCHECK(!HeapLayout::InReadOnlySpace(value));
    DCHECK_IMPLIES(v8_flags.black_allocated_pages,
                   !HeapLayout::InBlackAllocatedPage(value));
    DCHECK(!non_atomic_marking_state_->IsMarked(value));
    DCHECK(!MainMarkingVisitor::IsTrivialWeakReferenceValue(slot.heap_object,
                                                            value));
    if (!SpecialClearMapSlot(slot.heap_object, Cast<Map>(value), slot.slot)) {
      slot.slot.store(cleared_weak_ref);
    }
  }
}
References v8::internal::ClearedValue(), DCHECK, DCHECK_IMPLIES, v8::internal::detail::HeapObjectAndSlotPOD< TSlotType >::heap_object, v8::internal::detail::HeapObjectAndSlotPOD< TSlotType >::slot, TRACE_GC, v8::internal::v8_flags, and v8::internal::value.
ClearPotentialSimpleMapTransition() [1/2]
void v8::internal::MarkCompactCollector::ClearPotentialSimpleMapTransition (Tagged< Map > dead_target) [private]
Definition at line 3237 of file mark-compact.cc.
                             {
  DCHECK(non_atomic_marking_state_->IsUnmarked(dead_target));
  Tagged<Object> potential_parent = dead_target->constructor_or_back_pointer();
  if (IsMap(potential_parent)) {
    Tagged<Map> parent = Cast<Map>(potential_parent);
    DisallowGarbageCollection no_gc_obviously;
    if (MarkingHelper::IsMarkedOrAlwaysLive(heap_, non_atomic_marking_state_,
                                            parent) &&
        TransitionsAccessor(heap_->isolate(), parent)
            .HasSimpleTransitionTo(dead_target)) {
      ClearPotentialSimpleMapTransition(parent, dead_target);
    }
  }
}
References DCHECK, and v8::internal::TransitionsAccessor::HasSimpleTransitionTo().
ClearPotentialSimpleMapTransition() [2/2]
void v8::internal::MarkCompactCollector::ClearPotentialSimpleMapTransition (Tagged< Map > map, Tagged< Map > dead_target) [private]
Definition at line 3253 of file mark-compact.cc.
                                              {
  DCHECK(!map->is_prototype_map());
  DCHECK(!dead_target->is_prototype_map());
  DCHECK_EQ(map->raw_transitions(), MakeWeak(dead_target));
  // Take ownership of the descriptor array.
  int number_of_own_descriptors = map->NumberOfOwnDescriptors();
  Tagged<DescriptorArray> descriptors =
      map->instance_descriptors(heap_->isolate());
  if (descriptors == dead_target->instance_descriptors(heap_->isolate()) &&
      number_of_own_descriptors > 0) {
    TrimDescriptorArray(map, descriptors);
    DCHECK(descriptors->number_of_descriptors() == number_of_own_descriptors);
  }
}
References DCHECK, DCHECK_EQ, and v8::api_internal::MakeWeak().
ClearTrivialWeakReferences()
void v8::internal::MarkCompactCollector::ClearTrivialWeakReferences () [private]
Definition at line 3875 of file mark-compact.cc.
                                                      {
  Tagged<HeapObjectReference> cleared_weak_ref = ClearedValue(heap_->isolate());
  ClearWeakReferences<HeapObjectAndSlot, MaybeObjectSlot>(
      local_weak_objects()->weak_references_trivial_local, cleared_weak_ref);
}
References v8::internal::ClearedValue().
ClearTrustedWeakReferences()
void v8::internal::MarkCompactCollector::ClearTrustedWeakReferences () [private]
Definition at line 3881 of file mark-compact.cc.
                                                      {
  Tagged<HeapObjectReference> cleared_weak_ref = ClearedTrustedValue();
  ClearWeakReferences<TrustedObjectAndSlot, ProtectedMaybeObjectSlot>(
      local_weak_objects()->weak_references_trusted_local, cleared_weak_ref);
}
References v8::internal::ClearedTrustedValue().
ClearWeakCollections()
void v8::internal::MarkCompactCollector::ClearWeakCollections () [private]
Definition at line 3809 of file mark-compact.cc.
                                                {
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_CLEAR_WEAK_COLLECTIONS);
  Tagged<EphemeronHashTable> table;
  while (local_weak_objects()->ephemeron_hash_tables_local.Pop(&table)) {
    for (InternalIndex i : table->IterateEntries()) {
      Tagged<HeapObject> key = Cast<HeapObject>(table->KeyAt(i));
#ifdef VERIFY_HEAP
      if (v8_flags.verify_heap) {
        Tagged<Object> value = table->ValueAt(i);
        if (IsHeapObject(value)) {
          Tagged<HeapObject> heap_object = Cast<HeapObject>(value);
          CHECK_IMPLIES(MarkingHelper::IsMarkedOrAlwaysLive(
                            heap_, non_atomic_marking_state_, key),
                        MarkingHelper::IsMarkedOrAlwaysLive(
                            heap_, non_atomic_marking_state_, heap_object));
        }
      }
#endif // VERIFY_HEAP
      if (MarkingHelper::IsUnmarkedAndNotAlwaysLive(
              heap_, non_atomic_marking_state_, key)) {
        table->RemoveEntry(i);
      }
    }
  }
  auto* table_map = heap_->ephemeron_remembered_set()->tables();
  for (auto it = table_map->begin(); it != table_map->end();) {
    if (MarkingHelper::IsUnmarkedAndNotAlwaysLive(
            heap_, non_atomic_marking_state_, it->first)) {
      it = table_map->erase(it);
    } else {
      ++it;
    }
  }
}
References CHECK_IMPLIES, v8::internal::InstanceTypeChecker::IsHeapObject(), v8::internal::key, TRACE_GC, v8::internal::v8_flags, and v8::internal::value.
ClearWeakReferences()
template<typename TObjectAndSlot , typename TMaybeSlot >
void v8::internal::MarkCompactCollector::ClearWeakReferences (WeakObjects::WeakObjectWorklist< TObjectAndSlot >::Local & worklist, Tagged< HeapObjectReference > cleared_weak_ref) [private]
Definition at line 3846 of file mark-compact.cc.
                                                  {
  TObjectAndSlot slot;
  while (worklist.Pop(&slot)) {
    Tagged<HeapObject> value;
    // The slot could have been overwritten, so we have to treat it
    // as [Protected]MaybeObjectSlot.
    TMaybeSlot location(slot.slot);
    if (location.load().GetHeapObjectIfWeak(&value)) {
      DCHECK(!IsWeakCell(value));
      // Values in RO space have already been filtered, but a non-RO value may
      // have been overwritten by a RO value since marking.
      if (MarkingHelper::IsMarkedOrAlwaysLive(heap_, non_atomic_marking_state_,
                                              value)) {
        // The value of the weak reference is alive.
        RecordSlot(slot.heap_object, slot.slot, value);
      } else {
        DCHECK(MainMarkingVisitor::IsTrivialWeakReferenceValue(slot.heap_object,
                                                               value));
        // The value of the weak reference is non-live.
        // This is a non-atomic store, which is fine as long as we only have a
        // single clearing job.
        location.store(cleared_weak_ref);
      }
    }
  }
}
References DCHECK, heap::base::Worklist< EntryType, MinSegmentSize >::Local::Pop(), and v8::internal::value.
code_flush_mode()
base::EnumSet<CodeFlushMode> v8::internal::MarkCompactCollector::code_flush_mode () const [inline]
Definition at line 170 of file mark-compact.h.
                                                     {
    return code_flush_mode_;
  }
References code_flush_mode_.
Referenced by StartMarking(), and v8::internal::ConcurrentMarking::TryScheduleJob().
CollectEvacuationCandidates()
void v8::internal::MarkCompactCollector::CollectEvacuationCandidates (PagedSpace * space)
Definition at line 609 of file mark-compact.cc.
                                                                        {
  DCHECK(space->identity() == OLD_SPACE || space->identity() == CODE_SPACE ||
         space->identity() == SHARED_SPACE ||
         space->identity() == TRUSTED_SPACE);
  int number_of_pages = space->CountTotalPages();
  size_t area_size = space->AreaSize();
  const bool in_standard_path =
      !(v8_flags.manual_evacuation_candidates_selection ||
        v8_flags.stress_compaction_random || v8_flags.stress_compaction ||
        v8_flags.compact_on_every_full_gc);
  // Those variables will only be initialized if |in_standard_path|, and are not
  // used otherwise.
  size_t max_evacuated_bytes;
  int target_fragmentation_percent;
  size_t free_bytes_threshold;
  if (in_standard_path) {
    // We use two conditions to decide whether a page qualifies as an evacuation
    // candidate, or not:
    // * Target fragmentation: How fragmented is a page, i.e., how is the ratio
    // between live bytes and capacity of this page (= area).
    // * Evacuation quota: A global quota determining how much bytes should be
    // compacted.
    ComputeEvacuationHeuristics(area_size, &target_fragmentation_percent,
                                &max_evacuated_bytes);
    free_bytes_threshold = target_fragmentation_percent * (area_size / 100);
  }
  // Pairs of (live_bytes_in_page, page).
  using LiveBytesPagePair = std::pair<size_t, PageMetadata*>;
  std::vector<LiveBytesPagePair> pages;
  pages.reserve(number_of_pages);
  DCHECK(!sweeper_->sweeping_in_progress());
  for (PageMetadata* p : *space) {
    MemoryChunk* chunk = p->Chunk();
    if (chunk->NeverEvacuate() || !chunk->CanAllocate()) continue;
    if (chunk->IsPinned()) {
      DCHECK(!chunk->IsFlagSet(
          MemoryChunk::FORCE_EVACUATION_CANDIDATE_FOR_TESTING));
      continue;
    }
    // Invariant: Evacuation candidates are just created when marking is
    // started. This means that sweeping has finished. Furthermore, at the end
    // of a GC all evacuation candidates are cleared and their slot buffers are
    // released.
    CHECK(!chunk->IsEvacuationCandidate());
    CHECK_NULL(p->slot_set<OLD_TO_OLD>());
    CHECK_NULL(p->typed_slot_set<OLD_TO_OLD>());
    CHECK(p->SweepingDone());
    DCHECK(p->area_size() == area_size);
    if (in_standard_path) {
      // Only the pages with at more than |free_bytes_threshold| free bytes are
      // considered for evacuation.
      if (area_size - p->allocated_bytes() >= free_bytes_threshold) {
        pages.push_back(std::make_pair(p->allocated_bytes(), p));
      }
    } else {
      pages.push_back(std::make_pair(p->allocated_bytes(), p));
    }
  }
  int candidate_count = 0;
  size_t total_live_bytes = 0;
  const bool reduce_memory = heap_->ShouldReduceMemory();
  if (v8_flags.manual_evacuation_candidates_selection) {
    for (size_t i = 0; i < pages.size(); i++) {
      PageMetadata* p = pages[i].second;
      MemoryChunk* chunk = p->Chunk();
      if (chunk->IsFlagSet(
              MemoryChunk::FORCE_EVACUATION_CANDIDATE_FOR_TESTING)) {
        candidate_count++;
        total_live_bytes += pages[i].first;
        chunk->ClearFlagSlow(
            MemoryChunk::FORCE_EVACUATION_CANDIDATE_FOR_TESTING);
        AddEvacuationCandidate(p);
      }
    }
  } else if (v8_flags.stress_compaction_random) {
    double fraction = heap_->isolate()->fuzzer_rng()->NextDouble();
    size_t pages_to_mark_count =
        static_cast<size_t>(fraction * (pages.size() + 1));
    for (uint64_t i : heap_->isolate()->fuzzer_rng()->NextSample(
             pages.size(), pages_to_mark_count)) {
      candidate_count++;
      total_live_bytes += pages[i].first;
      AddEvacuationCandidate(pages[i].second);
    }
  } else if (v8_flags.stress_compaction) {
    for (size_t i = 0; i < pages.size(); i++) {
      PageMetadata* p = pages[i].second;
      if (i % 2 == 0) {
        candidate_count++;
        total_live_bytes += pages[i].first;
        AddEvacuationCandidate(p);
      }
    }
  } else {
    // The following approach determines the pages that should be evacuated.
    //
    // Sort pages from the most free to the least free, then select
    // the first n pages for evacuation such that:
    // - the total size of evacuated objects does not exceed the specified
    // limit.
    // - fragmentation of (n+1)-th page does not exceed the specified limit.
    std::sort(pages.begin(), pages.end(),
              [](const LiveBytesPagePair& a, const LiveBytesPagePair& b) {
                return a.first < b.first;
              });
    for (size_t i = 0; i < pages.size(); i++) {
      size_t live_bytes = pages[i].first;
      DCHECK_GE(area_size, live_bytes);
      if (v8_flags.compact_on_every_full_gc ||
          ((total_live_bytes + live_bytes) <= max_evacuated_bytes)) {
        candidate_count++;
        total_live_bytes += live_bytes;
      }
      if (v8_flags.trace_fragmentation_verbose) {
        PrintIsolate(heap_->isolate(),
                     "compaction-selection-page: space=%s free_bytes_page=%zu "
                     "fragmentation_limit_kb=%zu "
                     "fragmentation_limit_percent=%d sum_compaction_kb=%zu "
                     "compaction_limit_kb=%zu\n",
                     ToString(space->identity()), (area_size - live_bytes) / KB,
                     free_bytes_threshold / KB, target_fragmentation_percent,
                     total_live_bytes / KB, max_evacuated_bytes / KB);
      }
    }
    // How many pages we will allocated for the evacuated objects
    // in the worst case: ceil(total_live_bytes / area_size)
    int estimated_new_pages =
        static_cast<int>((total_live_bytes + area_size - 1) / area_size);
    DCHECK_LE(estimated_new_pages, candidate_count);
    int estimated_released_pages = candidate_count - estimated_new_pages;
    // Avoid (compact -> expand) cycles.
    if ((estimated_released_pages == 0) && !v8_flags.compact_on_every_full_gc) {
      candidate_count = 0;
    }
    for (int i = 0; i < candidate_count; i++) {
      AddEvacuationCandidate(pages[i].second);
    }
  }
  if (v8_flags.trace_fragmentation) {
    PrintIsolate(heap_->isolate(),
                 "compaction-selection: space=%s reduce_memory=%d pages=%d "
                 "total_live_bytes=%zu\n",
                 ToString(space->identity()), reduce_memory, candidate_count,
                 total_live_bytes / KB);
  }
}
References AddEvacuationCandidate(), v8::internal::MemoryChunk::CanAllocate(), CHECK, CHECK_NULL, v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunk::ClearFlagSlow(), v8::internal::CODE_SPACE, ComputeEvacuationHeuristics(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_LE, v8::internal::MemoryChunk::FORCE_EVACUATION_CANDIDATE_FOR_TESTING, v8::internal::Isolate::fuzzer_rng(), heap_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::MemoryChunk::IsEvacuationCandidate(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::Heap::isolate(), v8::internal::MemoryChunk::IsPinned(), v8::internal::KB, v8::internal::MemoryChunk::NeverEvacuate(), v8::base::RandomNumberGenerator::NextDouble(), v8::base::RandomNumberGenerator::NextSample(), v8::internal::OLD_SPACE, v8::internal::OLD_TO_OLD, v8::internal::PrintIsolate(), v8::internal::SHARED_SPACE, v8::internal::Heap::ShouldReduceMemory(), v8::base::sort(), space, sweeper_, v8::internal::Sweeper::sweeping_in_progress(), v8::internal::ToString(), v8::internal::TRUSTED_SPACE, and v8::internal::v8_flags.
Referenced by StartCompaction().
CollectGarbage()
void v8::internal::MarkCompactCollector::CollectGarbage ()
Definition at line 488 of file mark-compact.cc.
                                          {
  // Make sure that Prepare() has been called. The individual steps below will
  // update the state as they proceed.
  DCHECK(state_ == PREPARE_GC);
  MaybeEnableBackgroundThreadsInCycle(CallOrigin::kAtomicGC);
  MarkLiveObjects();
  if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap_)) {
    cpp_heap->ProcessCrossThreadWeakness();
  }
  // This will walk dead object graphs and so requires that all references are
  // still intact.
  RecordObjectStats();
  ClearNonLiveReferences();
  VerifyMarking();
  if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap_)) {
    cpp_heap->FinishMarkingAndProcessWeakness();
  }
  heap_->memory_measurement()->FinishProcessing(native_context_stats_);
  Sweep();
  Evacuate();
  Finish();
}
References ClearNonLiveReferences(), v8::internal::Heap::cpp_heap_, v8::internal::DCHECK(), Evacuate(), Finish(), v8::internal::MemoryMeasurement::FinishProcessing(), v8::internal::CppHeap::From(), heap_, kAtomicGC, MarkLiveObjects(), MaybeEnableBackgroundThreadsInCycle(), v8::internal::Heap::memory_measurement(), native_context_stats_, RecordObjectStats(), Sweep(), and VerifyMarking().
Referenced by v8::internal::Heap::MarkCompact().
CompactTransitionArray()
bool v8::internal::MarkCompactCollector::CompactTransitionArray (Tagged< Map > map, Tagged< TransitionArray > transitions, Tagged< DescriptorArray > descriptors) [private]
Definition at line 3651 of file mark-compact.cc.
                                         {
  DCHECK(!map->is_prototype_map());
  int num_transitions = transitions->number_of_transitions();
  if (!TransitionArrayNeedsCompaction(transitions, num_transitions)) {
    return false;
  }
  ReadOnlyRoots roots(heap_->isolate());
  bool descriptors_owner_died = false;
  int transition_index = 0;
  // Compact all live transitions to the left.
  for (int i = 0; i < num_transitions; ++i) {
    Tagged<Map> target = transitions->GetTarget(i);
    DCHECK_EQ(target->constructor_or_back_pointer(), map);
    if (MarkingHelper::IsUnmarkedAndNotAlwaysLive(
            heap_, non_atomic_marking_state_, target)) {
      if (!descriptors.is_null() &&
          target->instance_descriptors(heap_->isolate()) == descriptors) {
        DCHECK(!target->is_prototype_map());
        descriptors_owner_died = true;
      }
      continue;
    }
    if (i != transition_index) {
      Tagged<Name> key = transitions->GetKey(i);
      transitions->SetKey(transition_index, key);
      HeapObjectSlot key_slot = transitions->GetKeySlot(transition_index);
      RecordSlot(transitions, key_slot, key);
      Tagged<MaybeObject> raw_target = transitions->GetRawTarget(i);
      transitions->SetRawTarget(transition_index, raw_target);
      HeapObjectSlot target_slot = transitions->GetTargetSlot(transition_index);
      RecordSlot(transitions, target_slot, raw_target.GetHeapObject());
    }
    transition_index++;
  }
  // If there are no transitions to be cleared, return.
  if (transition_index == num_transitions) {
    DCHECK(!descriptors_owner_died);
    return false;
  }
  // Note that we never eliminate a transition array, though we might right-trim
  // such that number_of_transitions() == 0. If this assumption changes,
  // TransitionArray::Insert() will need to deal with the case that a transition
  // array disappeared during GC.
  int old_capacity_in_entries = transitions->Capacity();
  if (transition_index < old_capacity_in_entries) {
    int old_capacity = transitions->length();
    static_assert(TransitionArray::kEntryKeyIndex == 0);
    DCHECK_EQ(TransitionArray::ToKeyIndex(old_capacity_in_entries),
              old_capacity);
    int new_capacity = TransitionArray::ToKeyIndex(transition_index);
    heap_->RightTrimArray(transitions, new_capacity, old_capacity);
    transitions->SetNumberOfTransitions(transition_index);
  }
  return descriptors_owner_died;
}
References DCHECK, DCHECK_EQ, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Tagged< HeapObject >::is_null(), and v8::internal::key.
ComputeEvacuationHeuristics()
void v8::internal::MarkCompactCollector::ComputeEvacuationHeuristics (size_t area_size, int * target_fragmentation_percent, size_t * max_evacuated_bytes) [private]
Definition at line 561 of file mark-compact.cc.
                                 {
  // For memory reducing and optimize for memory mode we directly define both
  // constants.
  const int kTargetFragmentationPercentForReduceMemory = 20;
  const size_t kMaxEvacuatedBytesForReduceMemory = 12 * MB;
  const int kTargetFragmentationPercentForOptimizeMemory = 20;
  const size_t kMaxEvacuatedBytesForOptimizeMemory = 6 * MB;
  // For regular mode (which is latency critical) we define less aggressive
  // defaults to start and switch to a trace-based (using compaction speed)
  // approach as soon as we have enough samples.
  const int kTargetFragmentationPercent = 70;
  const size_t kMaxEvacuatedBytes = 4 * MB;
  // Time to take for a single area (=payload of page). Used as soon as there
  // exist enough compaction speed samples.
  const float kTargetMsPerArea = .5;
  if (heap_->ShouldReduceMemory()) {
    *target_fragmentation_percent = kTargetFragmentationPercentForReduceMemory;
    *max_evacuated_bytes = kMaxEvacuatedBytesForReduceMemory;
  } else if (heap_->ShouldOptimizeForMemoryUsage()) {
    *target_fragmentation_percent =
        kTargetFragmentationPercentForOptimizeMemory;
    *max_evacuated_bytes = kMaxEvacuatedBytesForOptimizeMemory;
  } else {
    const std::optional<double> estimated_compaction_speed =
        heap_->tracer()->CompactionSpeedInBytesPerMillisecond();
    if (estimated_compaction_speed.has_value()) {
      // Estimate the target fragmentation based on traced compaction speed
      // and a goal for a single page.
      const double estimated_ms_per_area =
          1 + area_size / *estimated_compaction_speed;
      *target_fragmentation_percent = static_cast<int>(
          100 - 100 * kTargetMsPerArea / estimated_ms_per_area);
      if (*target_fragmentation_percent <
          kTargetFragmentationPercentForReduceMemory) {
        *target_fragmentation_percent =
            kTargetFragmentationPercentForReduceMemory;
      }
    } else {
      *target_fragmentation_percent = kTargetFragmentationPercent;
    }
    *max_evacuated_bytes = kMaxEvacuatedBytes;
  }
}
References v8::internal::GCTracer::CompactionSpeedInBytesPerMillisecond(), heap_, v8::internal::MB, v8::internal::Heap::ShouldOptimizeForMemoryUsage(), v8::internal::Heap::ShouldReduceMemory(), and v8::internal::Heap::tracer().
Referenced by CollectEvacuationCandidates().
epoch()
unsigned v8::internal::MarkCompactCollector::epoch () const [inline]
Definition at line 168 of file mark-compact.h.
{ return epoch_; }
References epoch_.
Referenced by StartMarking(), v8::internal::ConcurrentMarking::TryScheduleJob(), and v8::internal::MarkingBarrier::Write().
Evacuate()
void v8::internal::MarkCompactCollector::Evacuate () [private]
Definition at line 5054 of file mark-compact.cc.
                                    {
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_EVACUATE);
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_EVACUATE_PROLOGUE);
    EvacuatePrologue();
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_EVACUATE_COPY);
    EvacuatePagesInParallel();
  }
  UpdatePointersAfterEvacuation();
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_EVACUATE_CLEAN_UP);
    for (PageMetadata* p : new_space_evacuation_pages_) {
      MemoryChunk* chunk = p->Chunk();
      AllocationSpace owner_identity = p->owner_identity();
      USE(owner_identity);
      if (chunk->IsFlagSet(MemoryChunk::PAGE_NEW_OLD_PROMOTION)) {
        chunk->ClearFlagNonExecutable(MemoryChunk::PAGE_NEW_OLD_PROMOTION);
        // The in-sandbox page flags may be corrupted, so we currently need
        // this check here to make sure that this doesn't lead to further
        // confusion about the state of MemoryChunkMetadata objects.
        // TODO(377724745): if we move (some of) the flags into the trusted
        // MemoryChunkMetadata object, then this wouldn't be necessary.
        SBXCHECK_EQ(OLD_SPACE, owner_identity);
        sweeper_->AddPage(OLD_SPACE, p);
      } else if (v8_flags.minor_ms) {
        // Sweep non-promoted pages to add them back to the free list.
        DCHECK_EQ(NEW_SPACE, owner_identity);
        DCHECK_EQ(0, p->live_bytes());
        DCHECK(p->SweepingDone());
        PagedNewSpace* space = heap_->paged_new_space();
        if (space->ShouldReleaseEmptyPage()) {
          ReleasePage(space->paged_space(), p);
        } else {
          sweeper_->SweepEmptyNewSpacePage(p);
        }
      }
    }
    new_space_evacuation_pages_.clear();
    for (LargePageMetadata* p : promoted_large_pages_) {
      MemoryChunk* chunk = p->Chunk();
      DCHECK(chunk->IsFlagSet(MemoryChunk::PAGE_NEW_OLD_PROMOTION));
      chunk->ClearFlagNonExecutable(MemoryChunk::PAGE_NEW_OLD_PROMOTION);
      Tagged<HeapObject> object = p->GetObject();
      if (!v8_flags.sticky_mark_bits) {
        MarkBit::From(object).Clear();
        p->SetLiveBytes(0);
      }
      p->marking_progress_tracker().ResetIfEnabled();
    }
    promoted_large_pages_.clear();
    for (PageMetadata* p : old_space_evacuation_pages_) {
      MemoryChunk* chunk = p->Chunk();
      if (chunk->IsFlagSet(MemoryChunk::COMPACTION_WAS_ABORTED)) {
        sweeper_->AddPage(p->owner_identity(), p);
        chunk->ClearFlagSlow(MemoryChunk::COMPACTION_WAS_ABORTED);
      }
    }
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_EVACUATE_EPILOGUE);
    EvacuateEpilogue();
  }
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap && !sweeper_->sweeping_in_progress()) {
    EvacuationVerifier verifier(heap_);
    verifier.Run();
  }
#endif // VERIFY_HEAP
}
References v8::internal::MemoryChunk::ClearFlagNonExecutable(), v8::internal::MemoryChunk::ClearFlagSlow(), DCHECK, DCHECK_EQ, v8::internal::MemoryChunk::IsFlagSet(), v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, SBXCHECK_EQ, space, TRACE_GC, USE, and v8::internal::v8_flags.
Referenced by CollectGarbage().
EvacuateEpilogue()
void v8::internal::MarkCompactCollector::EvacuateEpilogue () [private]
Definition at line 4454 of file mark-compact.cc.
                                            {
  aborted_evacuation_candidates_due_to_oom_.clear();
  aborted_evacuation_candidates_due_to_flags_.clear();
  // New space.
  if (heap_->new_space()) {
    DCHECK_EQ(0, heap_->new_space()->Size());
  }
  // Old generation. Deallocate evacuated candidate pages.
  ReleaseEvacuationCandidates();
#ifdef DEBUG
  VerifyRememberedSetsAfterEvacuation(heap_, GarbageCollector::MARK_COMPACTOR);
#endif // DEBUG
}
References DCHECK_EQ.
EvacuatePagesInParallel()
void v8::internal::MarkCompactCollector::EvacuatePagesInParallel () [private]
Definition at line 4933 of file mark-compact.cc.
                                                   {
  std::vector<std::pair<ParallelWorkItem, MutablePageMetadata*>>
      evacuation_items;
  intptr_t live_bytes = 0;
  PinPreciseRootsIfNeeded();
  // Evacuation of new space pages cannot be aborted, so it needs to run
  // before old space evacuation.
  bool force_page_promotion =
      heap_->IsGCWithStack() && !v8_flags.compact_with_stack;
  for (PageMetadata* page : new_space_evacuation_pages_) {
    intptr_t live_bytes_on_page = page->live_bytes();
    DCHECK_LT(0, live_bytes_on_page);
    live_bytes += live_bytes_on_page;
    MemoryReductionMode memory_reduction_mode =
        heap_->ShouldReduceMemory() ? MemoryReductionMode::kShouldReduceMemory
                                    : MemoryReductionMode::kNone;
    if (ShouldMovePage(page, live_bytes_on_page, memory_reduction_mode) ||
        force_page_promotion || page->Chunk()->IsQuarantined()) {
      EvacuateNewToOldSpacePageVisitor::Move(page);
      page->Chunk()->SetFlagNonExecutable(MemoryChunk::PAGE_NEW_OLD_PROMOTION);
      DCHECK_EQ(heap_->old_space(), page->owner());
      // The move added page->allocated_bytes to the old space, but we are
      // going to sweep the page and add page->live_byte_count.
      heap_->old_space()->DecreaseAllocatedBytes(page->allocated_bytes(), page);
    }
    evacuation_items.emplace_back(ParallelWorkItem{}, page);
  }
  if (heap_->IsGCWithStack()) {
    if (!v8_flags.compact_with_stack) {
      for (PageMetadata* page : old_space_evacuation_pages_) {
        ReportAbortedEvacuationCandidateDueToFlags(page, page->Chunk());
      }
    } else if (!v8_flags.compact_code_space_with_stack ||
               heap_->isolate()->InFastCCall()) {
      // For fast C calls we cannot patch the return address in the native stack
      // frame if we would relocate InstructionStream objects.
      for (PageMetadata* page : old_space_evacuation_pages_) {
        if (page->owner_identity() != CODE_SPACE) continue;
        ReportAbortedEvacuationCandidateDueToFlags(page, page->Chunk());
      }
    }
  } else {
    // There should always be a stack when we are in a fast c call.
    DCHECK(!heap_->isolate()->InFastCCall());
  }
  if (v8_flags.stress_compaction || v8_flags.stress_compaction_random) {
    // Stress aborting of evacuation by aborting ~10% of evacuation candidates
    // when stress testing.
    const double kFraction = 0.05;
    for (PageMetadata* page : old_space_evacuation_pages_) {
      if (heap_->isolate()->fuzzer_rng()->NextDouble() < kFraction) {
        ReportAbortedEvacuationCandidateDueToFlags(page, page->Chunk());
      }
    }
  }
  for (PageMetadata* page : old_space_evacuation_pages_) {
    MemoryChunk* chunk = page->Chunk();
    if (chunk->IsFlagSet(MemoryChunk::COMPACTION_WAS_ABORTED)) continue;
    live_bytes += page->live_bytes();
    evacuation_items.emplace_back(ParallelWorkItem{}, page);
  }
  // Promote young generation large objects.
  if (auto* new_lo_space = heap_->new_lo_space()) {
    for (auto it = new_lo_space->begin(); it != new_lo_space->end();) {
      LargePageMetadata* current = *(it++);
      Tagged<HeapObject> object = current->GetObject();
      // The black-allocated flag was already cleared in SweepLargeSpace().
      DCHECK_IMPLIES(v8_flags.black_allocated_pages,
                     !HeapLayout::InBlackAllocatedPage(object));
      if (marking_state_->IsMarked(object)) {
        heap_->lo_space()->PromoteNewLargeObject(current);
        current->Chunk()->SetFlagNonExecutable(
            MemoryChunk::PAGE_NEW_OLD_PROMOTION);
        promoted_large_pages_.push_back(current);
        evacuation_items.emplace_back(ParallelWorkItem{}, current);
      }
    }
    new_lo_space->set_objects_size(0);
  }
  const size_t pages_count = evacuation_items.size();
  size_t wanted_num_tasks = 0;
  if (!evacuation_items.empty()) {
    TRACE_EVENT1(TRACE_DISABLED_BY_DEFAULT("v8.gc"),
                 "MarkCompactCollector::EvacuatePagesInParallel", "pages",
                 evacuation_items.size());
    wanted_num_tasks = CreateAndExecuteEvacuationTasks(
        heap_, this, std::move(evacuation_items));
  }
  const size_t aborted_pages = PostProcessAbortedEvacuationCandidates();
  if (v8_flags.trace_evacuation) {
    TraceEvacuation(heap_->isolate(), pages_count, wanted_num_tasks, live_bytes,
                    aborted_pages);
  }
}
References v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::CODE_SPACE, v8::internal::anonymous_namespace{mark-compact.cc}::CreateAndExecuteEvacuationTasks(), DCHECK, DCHECK_EQ, DCHECK_IMPLIES, DCHECK_LT, v8::internal::LargePageMetadata::GetObject(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::SetFlagNonExecutable(), v8::internal::anonymous_namespace{mark-compact.cc}::ShouldMovePage(), TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT1, v8::internal::anonymous_namespace{mark-compact.cc}::TraceEvacuation(), and v8::internal::v8_flags.
EvacuatePrologue()
void v8::internal::MarkCompactCollector::EvacuatePrologue () [private]
Definition at line 4429 of file mark-compact.cc.
                                            {
  // New space.
  if (NewSpace* new_space = heap_->new_space()) {
    DCHECK(new_space_evacuation_pages_.empty());
    std::copy_if(new_space->begin(), new_space->end(),
                 std::back_inserter(new_space_evacuation_pages_),
                 [](PageMetadata* p) { return p->live_bytes() > 0; });
    if (!v8_flags.minor_ms) {
      SemiSpaceNewSpace::From(new_space)->SwapSemiSpaces();
    }
  }
  // Large new space.
  if (NewLargeObjectSpace* new_lo_space = heap_->new_lo_space()) {
    new_lo_space->Flip();
    new_lo_space->ResetPendingObject();
  }
  // Old space.
  DCHECK(old_space_evacuation_pages_.empty());
  old_space_evacuation_pages_ = std::move(evacuation_candidates_);
  evacuation_candidates_.clear();
  DCHECK(evacuation_candidates_.empty());
}
References DCHECK, and v8::internal::v8_flags.
FilterNonTrivialWeakReferences()
void v8::internal::MarkCompactCollector::FilterNonTrivialWeakReferences () [private]
Definition at line 3887 of file mark-compact.cc.
                                                          {
  HeapObjectAndSlot slot;
  while (local_weak_objects()->weak_references_non_trivial_local.Pop(&slot)) {
    Tagged<HeapObject> value;
    // The slot could have been overwritten, so we have to treat it
    // as MaybeObjectSlot.
    MaybeObjectSlot location(slot.slot);
    if ((*location).GetHeapObjectIfWeak(&value)) {
      DCHECK(!IsWeakCell(value));
      // Values in RO space have already been filtered, but a non-RO value may
      // have been overwritten by a RO value since marking.
      if (MarkingHelper::IsMarkedOrAlwaysLive(heap_, non_atomic_marking_state_,
                                              value)) {
        // The value of the weak reference is alive.
        RecordSlot(slot.heap_object, HeapObjectSlot(location), value);
      } else {
        DCHECK(!MainMarkingVisitor::IsTrivialWeakReferenceValue(
            slot.heap_object, value));
        // The value is non-live, defer the actual clearing.
        // This is non-atomic, which is fine as long as we only have a single
        // filtering job.
        local_weak_objects_->weak_references_non_trivial_unmarked_local.Push(
            slot);
      }
    }
  }
}
References DCHECK, v8::internal::detail::HeapObjectAndSlotPOD< TSlotType >::heap_object, v8::internal::detail::HeapObjectAndSlotPOD< TSlotType >::slot, and v8::internal::value.
Finish()
void v8::internal::MarkCompactCollector::Finish () [private]
Definition at line 849 of file mark-compact.cc.
                                  {
  {
    TRACE_GC_EPOCH_WITH_FLOW(
        heap_->tracer(), GCTracer::Scope::MC_SWEEP, ThreadKind::kMain,
        sweeper_->GetTraceIdForFlowEvent(GCTracer::Scope::MC_SWEEP),
        TRACE_EVENT_FLAG_FLOW_IN | TRACE_EVENT_FLAG_FLOW_OUT);
    // Delay releasing empty new space pages and dead new large object pages
    // until after pointer updating is done because dead old space objects may
    // have slots pointing to these pages and will need to be updated.
    DCHECK_IMPLIES(!v8_flags.minor_ms,
                   empty_new_space_pages_to_be_swept_.empty());
    if (!empty_new_space_pages_to_be_swept_.empty()) {
      GCTracer::Scope sweep_scope(
          heap_->tracer(), GCTracer::Scope::MC_SWEEP_NEW, ThreadKind::kMain);
      for (PageMetadata* p : empty_new_space_pages_to_be_swept_) {
        // Sweeping empty pages already relinks them to the freelist.
        sweeper_->SweepEmptyNewSpacePage(p);
      }
      empty_new_space_pages_to_be_swept_.clear();
    }
    if (heap_->new_lo_space()) {
      TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_SWEEP_NEW_LO);
      SweepLargeSpace(heap_->new_lo_space());
    }
#ifdef DEBUG
    heap_->VerifyCountersBeforeConcurrentSweeping(
        GarbageCollector::MARK_COMPACTOR);
#endif // DEBUG
  }
  if (heap_->new_space()) {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_EVACUATE);
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_EVACUATE_REBALANCE);
    heap_->ResizeNewSpace();
  }
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_FINISH);
  if (heap_->new_space()) {
    DCHECK(!heap_->allocator()->new_space_allocator()->IsLabValid());
    heap_->new_space()->GarbageCollectionEpilogue();
  }
  auto* isolate = heap_->isolate();
  isolate->global_handles()->ClearListOfYoungNodes();
  SweepArrayBufferExtensions();
  marking_visitor_.reset();
  local_marking_worklists_.reset();
  marking_worklists_.ReleaseContextWorklists();
  native_context_stats_.Clear();
  key_to_values_.clear();
  CHECK(weak_objects_.current_ephemerons.IsEmpty());
  local_weak_objects_->next_ephemerons_local.Publish();
  local_weak_objects_.reset();
  weak_objects_.next_ephemerons.Clear();
  sweeper_->StartMajorSweeperTasks();
  // Release empty pages now, when the pointer-update phase is done.
  for (MutablePageMetadata* page : queued_pages_to_be_freed_) {
    heap_->memory_allocator()->Free(MemoryAllocator::FreeMode::kImmediately,
                                    page);
  }
  queued_pages_to_be_freed_.clear();
  // Shrink pages if possible after processing and filtering slots.
  ShrinkPagesToObjectSizes(heap_, heap_->lo_space());
#ifdef DEBUG
  DCHECK(state_ == SWEEP_SPACES || state_ == RELOCATE_OBJECTS);
  state_ = IDLE;
#endif
  if (have_code_to_deoptimize_) {
    // Some code objects were marked for deoptimization during the GC.
    Deoptimizer::DeoptimizeMarkedCode(isolate);
    have_code_to_deoptimize_ = false;
  }
}
References v8::internal::Heap::allocator(), CHECK, v8::internal::NativeContextStats::Clear(), v8::internal::WeakObjects::Clear(), v8::internal::GlobalHandles::ClearListOfYoungNodes(), v8::internal::DCHECK(), DCHECK_IMPLIES, v8::internal::Deoptimizer::DeoptimizeMarkedCode(), empty_new_space_pages_to_be_swept_, v8::internal::MemoryAllocator::Free(), v8::internal::NewSpace::GarbageCollectionEpilogue(), v8::internal::Sweeper::GetTraceIdForFlowEvent(), v8::internal::Isolate::global_handles(), have_code_to_deoptimize_, heap_, v8::IDLE, v8::internal::MainAllocator::IsLabValid(), v8::internal::Heap::isolate(), key_to_values_, v8::internal::MemoryAllocator::kImmediately, v8::internal::kMain, v8::internal::Heap::lo_space(), local_marking_worklists_, local_weak_objects_, v8::internal::MARK_COMPACTOR, marking_visitor_, marking_worklists_, v8::internal::Heap::memory_allocator(), native_context_stats_, v8::internal::Heap::new_lo_space(), v8::internal::Heap::new_space(), v8::internal::HeapAllocator::new_space_allocator(), queued_pages_to_be_freed_, v8::internal::MarkingWorklists::ReleaseContextWorklists(), v8::internal::Heap::ResizeNewSpace(), v8::internal::anonymous_namespace{mark-compact.cc}::ShrinkPagesToObjectSizes(), v8::internal::Sweeper::StartMajorSweeperTasks(), SweepArrayBufferExtensions(), v8::internal::Sweeper::SweepEmptyNewSpacePage(), sweeper_, SweepLargeSpace(), TRACE_EVENT_FLAG_FLOW_IN, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC, TRACE_GC_EPOCH_WITH_FLOW, v8::internal::Heap::tracer(), v8::internal::v8_flags, and weak_objects_.
Referenced by CollectGarbage().
FinishConcurrentMarking()
void v8::internal::MarkCompactCollector::FinishConcurrentMarking ()
Definition at line 799 of file mark-compact.cc.
                                                   {
  // FinishConcurrentMarking is called for both, concurrent and parallel,
  // marking. It is safe to call this function when tasks are already finished.
  DCHECK_EQ(heap_->concurrent_marking()->garbage_collector(),
            GarbageCollector::MARK_COMPACTOR);
  if (v8_flags.parallel_marking || v8_flags.concurrent_marking) {
    heap_->concurrent_marking()->Join();
    heap_->concurrent_marking()->FlushMemoryChunkData();
    heap_->concurrent_marking()->FlushNativeContexts(&native_context_stats_);
  }
  if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap_)) {
    cpp_heap->FinishConcurrentMarkingIfNeeded();
  }
}
References v8::internal::Heap::concurrent_marking(), v8::internal::Heap::cpp_heap_, DCHECK_EQ, v8::internal::ConcurrentMarking::FlushMemoryChunkData(), v8::internal::ConcurrentMarking::FlushNativeContexts(), v8::internal::CppHeap::From(), v8::internal::ConcurrentMarking::garbage_collector(), heap_, v8::internal::ConcurrentMarking::Join(), v8::internal::MARK_COMPACTOR, native_context_stats_, and v8::internal::v8_flags.
FlushBytecodeFromSFI()
void v8::internal::MarkCompactCollector::FlushBytecodeFromSFI (Tagged< SharedFunctionInfo > shared_info) [private]
Definition at line 3303 of file mark-compact.cc.
                                            {
  DCHECK(shared_info->HasBytecodeArray());
  // Retain objects required for uncompiled data.
  Tagged<String> inferred_name = shared_info->inferred_name();
  int start_position = shared_info->StartPosition();
  int end_position = shared_info->EndPosition();
  shared_info->DiscardCompiledMetadata(
      heap_->isolate(),
      [](Tagged<HeapObject> object, ObjectSlot slot,
         Tagged<HeapObject> target) { RecordSlot(object, slot, target); });
  // The size of the bytecode array should always be larger than an
  // UncompiledData object.
  static_assert(BytecodeArray::SizeFor(0) >=
                UncompiledDataWithoutPreparseData::kSize);
  // Replace the bytecode with an uncompiled data object.
  Tagged<BytecodeArray> bytecode_array =
      shared_info->GetBytecodeArray(heap_->isolate());
#ifdef V8_ENABLE_SANDBOX
  DCHECK(!HeapLayout::InWritableSharedSpace(shared_info));
  // Zap the old entry in the trusted pointer table.
  TrustedPointerTable& table = heap_->isolate()->trusted_pointer_table();
  IndirectPointerSlot self_indirect_pointer_slot =
      bytecode_array->RawIndirectPointerField(
          BytecodeArray::kSelfIndirectPointerOffset,
          kBytecodeArrayIndirectPointerTag);
  table.Zap(self_indirect_pointer_slot.Relaxed_LoadHandle());
#endif
  Tagged<HeapObject> compiled_data = bytecode_array;
  Address compiled_data_start = compiled_data.address();
  int compiled_data_size = ALIGN_TO_ALLOCATION_ALIGNMENT(compiled_data->Size());
  MutablePageMetadata* chunk =
      MutablePageMetadata::FromAddress(compiled_data_start);
  // Clear any recorded slots for the compiled data as being invalid.
  RememberedSet<OLD_TO_NEW>::RemoveRange(
      chunk, compiled_data_start, compiled_data_start + compiled_data_size,
      SlotSet::FREE_EMPTY_BUCKETS);
  RememberedSet<OLD_TO_NEW_BACKGROUND>::RemoveRange(
      chunk, compiled_data_start, compiled_data_start + compiled_data_size,
      SlotSet::FREE_EMPTY_BUCKETS);
  RememberedSet<OLD_TO_SHARED>::RemoveRange(
      chunk, compiled_data_start, compiled_data_start + compiled_data_size,
      SlotSet::FREE_EMPTY_BUCKETS);
  RememberedSet<OLD_TO_OLD>::RemoveRange(
      chunk, compiled_data_start, compiled_data_start + compiled_data_size,
      SlotSet::FREE_EMPTY_BUCKETS);
  RememberedSet<TRUSTED_TO_TRUSTED>::RemoveRange(
      chunk, compiled_data_start, compiled_data_start + compiled_data_size,
      SlotSet::FREE_EMPTY_BUCKETS);
  // Swap the map, using set_map_after_allocation to avoid verify heap checks
  // which are not necessary since we are doing this during the GC atomic pause.
  compiled_data->set_map_after_allocation(
      heap_->isolate(),
      ReadOnlyRoots(heap_).uncompiled_data_without_preparse_data_map(),
      SKIP_WRITE_BARRIER);
  // Create a filler object for any left over space in the bytecode array.
  if (!heap_->IsLargeObject(compiled_data)) {
    const int aligned_filler_offset =
        ALIGN_TO_ALLOCATION_ALIGNMENT(UncompiledDataWithoutPreparseData::kSize);
    heap_->CreateFillerObjectAt(compiled_data.address() + aligned_filler_offset,
                                compiled_data_size - aligned_filler_offset);
  }
  // Initialize the uncompiled data.
  Tagged<UncompiledData> uncompiled_data = Cast<UncompiledData>(compiled_data);
  uncompiled_data->InitAfterBytecodeFlush(
      heap_->isolate(), inferred_name, start_position, end_position,
      [](Tagged<HeapObject> object, ObjectSlot slot,
         Tagged<HeapObject> target) { RecordSlot(object, slot, target); });
  // Mark the uncompiled data as black, and ensure all fields have already been
  // marked.
  DCHECK(MarkingHelper::IsMarkedOrAlwaysLive(heap_, marking_state_,
                                             inferred_name));
  if (MarkingHelper::GetLivenessMode(heap_, uncompiled_data) ==
      MarkingHelper::LivenessMode::kMarkbit) {
    marking_state_->TryMarkAndAccountLiveBytes(uncompiled_data);
  }
#ifdef V8_ENABLE_SANDBOX
  // Mark the new entry in the trusted pointer table as alive.
  TrustedPointerTable::Space* space = heap_->trusted_pointer_space();
  table.Mark(space, self_indirect_pointer_slot.Relaxed_LoadHandle());
#endif
  shared_info->set_uncompiled_data(uncompiled_data);
  DCHECK(!shared_info->is_compiled());
}
References v8::internal::Tagged< HeapObject >::address(), ALIGN_TO_ALLOCATION_ALIGNMENT, DCHECK, v8::internal::IndirectPointerSlot::Relaxed_LoadHandle(), v8::internal::SKIP_WRITE_BARRIER, and space.
FlushSFI()
void v8::internal::MarkCompactCollector::FlushSFI (Tagged< SharedFunctionInfo > sfi, bool bytecode_already_decompiled) [private]
Definition at line 3517 of file mark-compact.cc.
                                                                      {
  // If baseline code flushing is disabled we should only flush bytecode
  // from functions that don't have baseline data.
  DCHECK(v8_flags.flush_baseline_code || !sfi->HasBaselineCode());
  if (bytecode_already_decompiled) {
    sfi->DiscardCompiledMetadata(
        heap_->isolate(),
        [](Tagged<HeapObject> object, ObjectSlot slot,
           Tagged<HeapObject> target) { RecordSlot(object, slot, target); });
  } else {
    // If the BytecodeArray is dead, flush it, which will replace the field
    // with an uncompiled data object.
    FlushBytecodeFromSFI(sfi);
  }
}
References DCHECK, and v8::internal::v8_flags.
heap()
Heap* v8::internal::MarkCompactCollector::heap () [inline]
Definition at line 189 of file mark-compact.h.
{ return heap_; }
References heap_.
Referenced by v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::CheckForSharedObject(), v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::MarkObject(), v8::internal::RootMarkingVisitor::MarkObjectByPointer(), MaybeEnableBackgroundThreadsInCycle(), and StartMarking().
is_compacting()
bool v8::internal::MarkCompactCollector::is_compacting () const [inline]
Definition at line 147 of file mark-compact.h.
{ return compacting_; }
References compacting_.
IsOnEvacuationCandidate()
static bool v8::internal::MarkCompactCollector::IsOnEvacuationCandidate (Tagged< MaybeObject > obj) [inline], [static]
Definition at line 119 of file mark-compact.h.
                                                                      {
    return MemoryChunk::FromAddress(obj.ptr())->IsEvacuationCandidate();
  }
References v8::internal::MemoryChunk::FromAddress(), v8::internal::MemoryChunk::IsEvacuationCandidate(), and v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::internal::IterateAndScavengePromotedObjectsVisitor::HandleSlot(), v8::internal::PagedSpaceAllocatorPolicy::TryAllocationFromFreeList(), and v8::internal::EvacuateNewSpaceVisitor::TryEvacuateWithoutCopy().
IsUnmarkedHeapObject()
bool v8::internal::MarkCompactCollector::IsUnmarkedHeapObject (Heap * heap, FullObjectSlot p) [static]
Definition at line 1832 of file mark-compact.cc.
                                                                            {
  Tagged<Object> o = *p;
  if (!IsHeapObject(o)) return false;
  Tagged<HeapObject> heap_object = Cast<HeapObject>(o);
  return MarkingHelper::IsUnmarkedAndNotAlwaysLive(
      heap, heap->non_atomic_marking_state(), heap_object);
}
References v8::internal::IsHeapObject(), and v8::internal::MarkingHelper::IsUnmarkedAndNotAlwaysLive().
IsUnmarkedSharedHeapObject()
bool v8::internal::MarkCompactCollector::IsUnmarkedSharedHeapObject (Heap * heap, FullObjectSlot p) [static]
Definition at line 1841 of file mark-compact.cc.
                                                                        {
  Tagged<Object> o = *p;
  if (!IsHeapObject(o)) return false;
  Tagged<HeapObject> heap_object = Cast<HeapObject>(o);
  Heap* shared_space_heap =
      client_heap->isolate()->shared_space_isolate()->heap();
  if (!HeapLayout::InWritableSharedSpace(heap_object)) return false;
  return MarkingHelper::IsUnmarkedAndNotAlwaysLive(
      shared_space_heap, shared_space_heap->non_atomic_marking_state(),
      heap_object);
}
References v8::internal::Isolate::heap(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::IsHeapObject(), v8::internal::Heap::isolate(), v8::internal::MarkingHelper::IsUnmarkedAndNotAlwaysLive(), v8::internal::Heap::non_atomic_marking_state(), and v8::internal::Isolate::shared_space_isolate().
local_marking_worklists()
MarkingWorklists::Local* v8::internal::MarkCompactCollector::local_marking_worklists () const [inline]
Definition at line 176 of file mark-compact.h.
                                                         {
    return local_marking_worklists_.get();
  }
References local_marking_worklists_.
Referenced by v8::internal::ConcurrentMarking::RescheduleJobIfNeeded(), v8::internal::IncrementalMarking::ShouldFinalize(), v8::internal::IncrementalMarking::StartMarkingMajor(), and v8::internal::ConcurrentMarking::TryScheduleJob().
local_weak_objects()
WeakObjects::Local* v8::internal::MarkCompactCollector::local_weak_objects () [inline]
Definition at line 181 of file mark-compact.h.
{ return local_weak_objects_.get(); }
References local_weak_objects_.
Referenced by AddTransitionArray(), and TearDown().
MarkDependentCodeForDeoptimization()
void v8::internal::MarkCompactCollector::MarkDependentCodeForDeoptimization () [private]
Definition at line 3217 of file mark-compact.cc.
                                                              {
  HeapObjectAndCode weak_object_in_code;
  while (local_weak_objects()->weak_objects_in_code_local.Pop(
      &weak_object_in_code)) {
    Tagged<HeapObject> object = weak_object_in_code.heap_object;
    Tagged<Code> code = weak_object_in_code.code;
    if (MarkingHelper::IsUnmarkedAndNotAlwaysLive(
            heap_, non_atomic_marking_state_, object) &&
        !code->embedded_objects_cleared()) {
      if (!code->marked_for_deoptimization()) {
        code->SetMarkedForDeoptimization(heap_->isolate(),
                                         LazyDeoptimizeReason::kWeakObjects);
        have_code_to_deoptimize_ = true;
      }
      code->ClearEmbeddedObjectsAndJSDispatchHandles(heap_);
      DCHECK(code->embedded_objects_cleared());
    }
  }
}
References code, v8::internal::HeapObjectAndCode::code, DCHECK, and v8::internal::HeapObjectAndCode::heap_object.
marking_worklists()
MarkingWorklists* v8::internal::MarkCompactCollector::marking_worklists () [inline]
Definition at line 174 of file mark-compact.h.
{ return &marking_worklists_; }
References marking_worklists_.
Referenced by v8::internal::MarkingBarrier::Activate(), v8::internal::MarkingBarrier::ActivateShared(), and v8::internal::ConcurrentMarking::TryScheduleJob().
MarkLiveObjects()
void v8::internal::MarkCompactCollector::MarkLiveObjects () [private]
Definition at line 2477 of file mark-compact.cc.
                                           {
  TRACE_GC_ARG1(heap_->tracer(), GCTracer::Scope::MC_MARK,
                "UseBackgroundThreads", UseBackgroundThreadsInCycle());
  const bool was_marked_incrementally =
      !heap_->incremental_marking()->IsStopped();
  if (was_marked_incrementally) {
    auto* incremental_marking = heap_->incremental_marking();
    TRACE_GC_WITH_FLOW(
        heap_->tracer(), GCTracer::Scope::MC_MARK_FINISH_INCREMENTAL,
        incremental_marking->current_trace_id(), TRACE_EVENT_FLAG_FLOW_IN);
    DCHECK(incremental_marking->IsMajorMarking());
    incremental_marking->Stop();
    MarkingBarrier::PublishAll(heap_);
  }
#ifdef DEBUG
  DCHECK(state_ == PREPARE_GC);
  state_ = MARK_LIVE_OBJECTS;
#endif
  if (heap_->cpp_heap_) {
    CppHeap::From(heap_->cpp_heap_)
        ->EnterFinalPause(heap_->embedder_stack_state_);
  }
  RootMarkingVisitor root_visitor(this);
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_MARK_ROOTS);
    MarkRoots(&root_visitor);
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_MARK_CLIENT_HEAPS);
    MarkObjectsFromClientHeaps();
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_MARK_RETAIN_MAPS);
    RetainMaps();
  }
  if (v8_flags.parallel_marking && UseBackgroundThreadsInCycle()) {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_MARK_FULL_CLOSURE_PARALLEL);
    parallel_marking_ = true;
    heap_->concurrent_marking()->RescheduleJobIfNeeded(
        GarbageCollector::MARK_COMPACTOR, TaskPriority::kUserBlocking);
    MarkTransitiveClosure();
    {
      TRACE_GC(heap_->tracer(),
               GCTracer::Scope::MC_MARK_FULL_CLOSURE_PARALLEL_JOIN);
      FinishConcurrentMarking();
    }
    parallel_marking_ = false;
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_MARK_ROOTS);
    MarkRootsFromConservativeStack(&root_visitor);
  }
  {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_MARK_FULL_CLOSURE_SERIAL);
    // Complete the transitive closure single-threaded to avoid races with
    // multiple threads when processing weak maps and embedder heaps.
    CHECK(heap_->concurrent_marking()->IsStopped());
    if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap())) {
      // Lock the process-global mutex here and mark cross-thread roots again.
      // This is done as late as possible to keep locking durations short.
      cpp_heap->EnterProcessGlobalAtomicPause();
    }
    MarkTransitiveClosure();
    CHECK(local_marking_worklists_->IsEmpty());
    CHECK(
        local_weak_objects()->current_ephemerons_local.IsLocalAndGlobalEmpty());
    CHECK(IsCppHeapMarkingFinished(heap_, local_marking_worklists_.get()));
    VerifyEphemeronMarking();
  }
  if (was_marked_incrementally) {
    // Disable the marking barrier after concurrent/parallel marking has
    // finished as it will reset page flags that share the same bitmap as
    // the evacuation candidate bit.
    MarkingBarrier::DeactivateAll(heap_);
    heap_->isolate()->traced_handles()->SetIsMarking(false);
  }
  epoch_++;
}
References CHECK, DCHECK, v8::internal::IsCppHeapMarkingFinished(), v8::kUserBlocking, TRACE_EVENT_FLAG_FLOW_IN, TRACE_GC, TRACE_GC_ARG1, TRACE_GC_WITH_FLOW, and v8::internal::v8_flags.
Referenced by CollectGarbage().
MarkObject()
void v8::internal::MarkCompactCollector::MarkObject (Tagged< HeapObject > host, Tagged< HeapObject > obj, MarkingHelper::WorklistTarget target_worklist) [inline], [private]
Definition at line 28 of file mark-compact-inl.h.
                                                 {
  DCHECK(ReadOnlyHeap::Contains(obj) || heap_->Contains(obj));
  MarkingHelper::TryMarkAndPush(heap_, local_marking_worklists_.get(),
                                marking_state_, target_worklist, obj);
}
References v8::internal::ReadOnlyHeap::Contains(), v8::internal::Heap::Contains(), v8::internal::DCHECK(), heap_, local_marking_worklists_, marking_state_, and v8::internal::MarkingHelper::TryMarkAndPush().
Referenced by v8::internal::MarkCompactCollector::CustomRootBodyMarkingVisitor::MarkObject().
MarkObjectsFromClientHeap()
void v8::internal::MarkCompactCollector::MarkObjectsFromClientHeap (Isolate * client) [private]
Definition at line 1919 of file mark-compact.cc.
                                                                    {
  // There is no OLD_TO_SHARED remembered set for the young generation. We
  // therefore need to iterate each object and check whether it points into the
  // shared heap. As an optimization and to avoid a second heap iteration in the
  // "update pointers" phase, all pointers into the shared heap are recorded in
  // the OLD_TO_SHARED remembered set as well.
  SharedHeapObjectVisitor visitor(this);
  PtrComprCageBase cage_base(client);
  Heap* client_heap = client->heap();
  // Finish sweeping quarantined pages for Scavenger's new space in order to
  // iterate objects in it.
  client_heap->EnsureQuarantinedPagesSweepingCompleted();
  // Finish sweeping for new space in order to iterate objects in it.
  client_heap->sweeper()->FinishMinorJobs();
  // Finish sweeping for old generation in order to iterate OLD_TO_SHARED.
  client_heap->sweeper()->FinishMajorJobs();
  if (auto* new_space = client_heap->new_space()) {
    DCHECK(!client_heap->allocator()->new_space_allocator()->IsLabValid());
    for (PageMetadata* page : *new_space) {
      for (Tagged<HeapObject> obj : HeapObjectRange(page)) {
        visitor.Visit(obj);
      }
    }
  }
  if (client_heap->new_lo_space()) {
    std::unique_ptr<ObjectIterator> iterator =
        client_heap->new_lo_space()->GetObjectIterator(client_heap);
    for (Tagged<HeapObject> obj = iterator->Next(); !obj.is_null();
         obj = iterator->Next()) {
      visitor.Visit(obj);
    }
  }
  // In the old generation we can simply use the OLD_TO_SHARED remembered set to
  // find all incoming pointers into the shared heap.
  OldGenerationMemoryChunkIterator chunk_iterator(client_heap);
  // Tracking OLD_TO_SHARED requires the write barrier.
  DCHECK(!v8_flags.disable_write_barriers);
  for (MutablePageMetadata* chunk = chunk_iterator.next(); chunk;
       chunk = chunk_iterator.next()) {
    const auto slot_count = RememberedSet<OLD_TO_SHARED>::Iterate(
        chunk,
        [collector = this, cage_base](MaybeObjectSlot slot) {
          Tagged<MaybeObject> obj = slot.Relaxed_Load(cage_base);
          Tagged<HeapObject> heap_object;
          if (obj.GetHeapObject(&heap_object) &&
              HeapLayout::InWritableSharedSpace(heap_object)) {
            // If the object points to the black allocated shared page, don't
            // mark the object, but still keep the slot.
            if (MarkingHelper::ShouldMarkObject(collector->heap(),
                                                heap_object)) {
              collector->MarkRootObject(
                  Root::kClientHeap, heap_object,
                  MarkingHelper::WorklistTarget::kRegular);
            }
            return KEEP_SLOT;
          } else {
            return REMOVE_SLOT;
          }
        },
        SlotSet::FREE_EMPTY_BUCKETS);
    if (slot_count == 0) {
      chunk->ReleaseSlotSet(OLD_TO_SHARED);
    }
    const auto typed_slot_count = RememberedSet<OLD_TO_SHARED>::IterateTyped(
        chunk,
        [collector = this, client_heap](SlotType slot_type, Address slot) {
          Tagged<HeapObject> heap_object =
              UpdateTypedSlotHelper::GetTargetObject(client_heap, slot_type,
                                                     slot);
          if (HeapLayout::InWritableSharedSpace(heap_object)) {
            // If the object points to the black allocated shared page, don't
            // mark the object, but still keep the slot.
            if (MarkingHelper::ShouldMarkObject(collector->heap(),
                                                heap_object)) {
              collector->MarkRootObject(
                  Root::kClientHeap, heap_object,
                  MarkingHelper::WorklistTarget::kRegular);
            }
            return KEEP_SLOT;
          } else {
            return REMOVE_SLOT;
          }
        });
    if (typed_slot_count == 0) {
      chunk->ReleaseTypedSlotSet(OLD_TO_SHARED);
    }
    const auto protected_slot_count =
        RememberedSet<TRUSTED_TO_SHARED_TRUSTED>::Iterate(
            chunk,
            [collector = this](MaybeObjectSlot slot) {
              ProtectedPointerSlot protected_slot(slot.address());
              Tagged<MaybeObject> obj = protected_slot.Relaxed_Load();
              Tagged<HeapObject> heap_object;
              if (obj.GetHeapObject(&heap_object) &&
                  HeapLayout::InWritableSharedSpace(heap_object)) {
                // If the object points to the black allocated shared page,
                // don't mark the object, but still keep the slot.
                if (MarkingHelper::ShouldMarkObject(collector->heap(),
                                                    heap_object)) {
                  collector->MarkRootObject(
                      Root::kClientHeap, heap_object,
                      MarkingHelper::WorklistTarget::kRegular);
                }
                return KEEP_SLOT;
              } else {
                return REMOVE_SLOT;
              }
            },
            SlotSet::FREE_EMPTY_BUCKETS);
    if (protected_slot_count == 0) {
      chunk->ReleaseSlotSet(TRUSTED_TO_SHARED_TRUSTED);
    }
  }
#ifdef V8_ENABLE_SANDBOX
  DCHECK(IsSharedExternalPointerType(kExternalStringResourceTag));
  DCHECK(IsSharedExternalPointerType(kExternalStringResourceDataTag));
  // All ExternalString resources are stored in the shared external pointer
  // table. Mark entries from client heaps.
  ExternalPointerTable& shared_table = client->shared_external_pointer_table();
  ExternalPointerTable::Space* shared_space =
      client->shared_external_pointer_space();
  MarkExternalPointerFromExternalStringTable external_string_visitor(
      &shared_table, shared_space);
  client_heap->external_string_table_.IterateAll(&external_string_visitor);
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::Heap::allocator(), v8::internal::DCHECK(), v8::internal::Heap::EnsureQuarantinedPagesSweepingCompleted(), v8::internal::Sweeper::FinishMajorJobs(), v8::internal::Sweeper::FinishMinorJobs(), heap::base::BasicSlotSet< kTaggedSize >::FREE_EMPTY_BUCKETS, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObject(), v8::internal::LargeObjectSpace::GetObjectIterator(), v8::internal::UpdateTypedSlotHelper::GetTargetObject(), v8::internal::Isolate::heap(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::Tagged< HeapObject >::is_null(), v8::internal::MainAllocator::IsLabValid(), v8::internal::RememberedSet< type >::Iterate(), v8::internal::RememberedSet< type >::IterateTyped(), heap::base::KEEP_SLOT, v8::internal::MarkingHelper::kRegular, v8::internal::Heap::new_lo_space(), v8::internal::Heap::new_space(), v8::internal::HeapAllocator::new_space_allocator(), v8::internal::OldGenerationMemoryChunkIterator::next(), v8::internal::OLD_TO_SHARED, v8::internal::FullObjectSlot::Relaxed_Load(), v8::internal::FullMaybeObjectSlot::Relaxed_Load(), heap::base::REMOVE_SLOT, v8::internal::MarkingHelper::ShouldMarkObject(), v8::internal::Heap::sweeper(), v8::internal::TRUSTED_TO_SHARED_TRUSTED, v8::internal::v8_flags, and v8::internal::HeapVisitor< ConcreteVisitor >::Visit().
MarkObjectsFromClientHeaps()
void v8::internal::MarkCompactCollector::MarkObjectsFromClientHeaps () [private]
Definition at line 1909 of file mark-compact.cc.
                                                      {
  Isolate* const isolate = heap_->isolate();
  if (!isolate->is_shared_space_isolate()) return;
  isolate->global_safepoint()->IterateClientIsolates(
      [collector = this](Isolate* client) {
        collector->MarkObjectsFromClientHeap(client);
      });
}
References v8::internal::Isolate::global_safepoint(), heap_, v8::internal::Isolate::is_shared_space_isolate(), v8::internal::Heap::isolate(), and v8::internal::GlobalSafepoint::IterateClientIsolates().
MarkRootObject()
void v8::internal::MarkCompactCollector::MarkRootObject (Root root, Tagged< HeapObject > obj, MarkingHelper::WorklistTarget target_worklist) [inline], [private]
Definition at line 36 of file mark-compact-inl.h.
                                                 {
  DCHECK(ReadOnlyHeap::Contains(obj) || heap_->Contains(obj));
  MarkingHelper::TryMarkAndPush(heap_, local_marking_worklists_.get(),
                                marking_state_, target_worklist, obj);
  if (V8_UNLIKELY(in_conservative_stack_scanning_)) {
    DCHECK_EQ(root, Root::kStackRoots);
    MemoryChunk* chunk = MemoryChunk::FromHeapObject(obj);
    if (chunk->IsEvacuationCandidate()) {
      DCHECK(!chunk->InYoungGeneration());
      ReportAbortedEvacuationCandidateDueToFlags(
          PageMetadata::cast(chunk->Metadata()), chunk);
    } else if (chunk->InYoungGeneration() && !chunk->IsLargePage()) {
      DCHECK(chunk->IsToPage());
      if (!chunk->IsQuarantined()) {
        chunk->SetFlagNonExecutable(MemoryChunk::IS_QUARANTINED);
      }
    }
  }
}
References v8::internal::PageMetadata::cast(), v8::internal::ReadOnlyHeap::Contains(), v8::internal::Heap::Contains(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MemoryChunk::FromHeapObject(), heap_, in_conservative_stack_scanning_, v8::internal::MemoryChunk::InYoungGeneration(), v8::internal::MemoryChunk::IS_QUARANTINED, v8::internal::MemoryChunk::IsEvacuationCandidate(), v8::internal::MemoryChunk::IsLargePage(), v8::internal::MemoryChunk::IsQuarantined(), v8::internal::MemoryChunk::IsToPage(), local_marking_worklists_, marking_state_, v8::internal::MemoryChunk::Metadata(), ReportAbortedEvacuationCandidateDueToFlags(), v8::internal::MemoryChunk::SetFlagNonExecutable(), v8::internal::MarkingHelper::TryMarkAndPush(), and V8_UNLIKELY.
Referenced by v8::internal::MarkCompactCollector::SharedHeapObjectVisitor::CheckForSharedObject(), and v8::internal::RootMarkingVisitor::MarkObjectByPointer().
MarkRoots()
void v8::internal::MarkCompactCollector::MarkRoots (RootVisitor * root_visitor) [private]
Definition at line 1854 of file mark-compact.cc.
                                                              {
  Isolate* const isolate = heap_->isolate();
  // Mark the heap roots including global variables, stack variables,
  // etc., and all objects reachable from them.
  heap_->IterateRoots(
      root_visitor,
      base::EnumSet<SkipRoot>{SkipRoot::kWeak, SkipRoot::kTracedHandles,
                              SkipRoot::kConservativeStack,
                              SkipRoot::kReadOnlyBuiltins});
  // Custom marking for top optimized frame.
  CustomRootBodyMarkingVisitor custom_root_body_visitor(this);
  ProcessTopOptimizedFrame(&custom_root_body_visitor, isolate);
  if (isolate->is_shared_space_isolate()) {
    ClientRootVisitor<> client_root_visitor(root_visitor);
    ClientObjectVisitor<> client_custom_root_body_visitor(
        &custom_root_body_visitor);
    isolate->global_safepoint()->IterateClientIsolates(
        [this, &client_root_visitor,
         &client_custom_root_body_visitor](Isolate* client) {
          client->heap()->IterateRoots(
              &client_root_visitor,
              base::EnumSet<SkipRoot>{SkipRoot::kWeak,
                                      SkipRoot::kConservativeStack,
                                      SkipRoot::kReadOnlyBuiltins});
          ProcessTopOptimizedFrame(&client_custom_root_body_visitor, client);
        });
  }
}
References v8::internal::Isolate::global_safepoint(), v8::internal::Isolate::heap(), heap_, v8::internal::Isolate::is_shared_space_isolate(), v8::internal::Heap::isolate(), v8::internal::GlobalSafepoint::IterateClientIsolates(), v8::internal::Heap::IterateRoots(), v8::internal::kConservativeStack, v8::internal::kReadOnlyBuiltins, v8::internal::kTracedHandles, v8::internal::kWeak, and ProcessTopOptimizedFrame().
MarkRootsFromConservativeStack()
void v8::internal::MarkCompactCollector::MarkRootsFromConservativeStack (RootVisitor * root_visitor) [private]
Definition at line 1887 of file mark-compact.cc.
                               {
  TRACE_GC(heap_->tracer(), GCTracer::Scope::CONSERVATIVE_STACK_SCANNING);
  DCHECK(!in_conservative_stack_scanning_);
  in_conservative_stack_scanning_ = true;
  heap_->IterateConservativeStackRoots(root_visitor,
                                       Heap::IterateRootsMode::kMainIsolate);
  Isolate* const isolate = heap_->isolate();
  if (isolate->is_shared_space_isolate()) {
    ClientRootVisitor<> client_root_visitor(root_visitor);
    // For client isolates, use the stack marker to conservatively scan the
    // stack.
    isolate->global_safepoint()->IterateClientIsolates(
        [v = &client_root_visitor](Isolate* client) {
          client->heap()->IterateConservativeStackRoots(
              v, Heap::IterateRootsMode::kClientIsolate);
        });
  }
  in_conservative_stack_scanning_ = false;
}
References v8::internal::DCHECK(), v8::internal::Isolate::global_safepoint(), v8::internal::Isolate::heap(), heap_, in_conservative_stack_scanning_, v8::internal::Isolate::is_shared_space_isolate(), v8::internal::Heap::isolate(), v8::internal::GlobalSafepoint::IterateClientIsolates(), v8::internal::Heap::IterateConservativeStackRoots(), v8::internal::Heap::kClientIsolate, v8::internal::Heap::kMainIsolate, TRACE_GC, and v8::internal::Heap::tracer().
MarkTransitiveClosure()
void v8::internal::MarkCompactCollector::MarkTransitiveClosure () [private]
Definition at line 2346 of file mark-compact.cc.
                                                 {
  // Incremental marking might leave ephemerons in main task's local
  // buffer, flush it into global pool.
  local_weak_objects()->next_ephemerons_local.Publish();
  if (!MarkTransitiveClosureUntilFixpoint()) {
    // Fixpoint iteration needed too many iterations and was cancelled. Use the
    // guaranteed linear algorithm. But only in the final single-thread marking
    // phase.
    if (!parallel_marking_) MarkTransitiveClosureLinear();
  }
}
MarkTransitiveClosureLinear()
void v8::internal::MarkCompactCollector::MarkTransitiveClosureLinear () [private]
Definition at line 2128 of file mark-compact.cc.
                                                       {
  TRACE_GC(heap_->tracer(),
           GCTracer::Scope::MC_MARK_WEAK_CLOSURE_EPHEMERON_LINEAR);
  // This phase doesn't support parallel marking.
  DCHECK(heap_->concurrent_marking()->IsStopped());
  DCHECK(key_to_values_.empty());
  DCHECK(
      local_weak_objects()->current_ephemerons_local.IsLocalAndGlobalEmpty());
  // Update visitor to directly add new ephemerons to key_to_values_.
  marking_visitor_->SetKeyToValues(&key_to_values_);
  Ephemeron ephemeron;
  while (local_weak_objects()->next_ephemerons_local.Pop(&ephemeron)) {
    if (ApplyEphemeronSemantics(ephemeron.key, ephemeron.value) ==
        EphemeronResult::kUnresolved) {
      auto it = key_to_values_.try_emplace(ephemeron.key).first;
      it->second.push_back(ephemeron.value);
    }
  }
  bool work_to_do;
  do {
    PerformWrapperTracing();
    {
      TRACE_GC(heap_->tracer(),
               GCTracer::Scope::MC_MARK_WEAK_CLOSURE_EPHEMERON_MARKING);
      // Drain marking worklist but:
      // (1) push all new ephemerons directly into key_to_values_.
      // (2) look up all traced objects in key_to_values_.
      ProcessMarkingWorklist<
          MarkingWorklistProcessingMode::kProcessRememberedEphemerons>(
          v8::base::TimeDelta::Max(), SIZE_MAX);
    }
    // Do NOT drain marking worklist here, otherwise the current checks
    // for work_to_do are not sufficient for determining if another iteration
    // is necessary.
    work_to_do =
        !local_marking_worklists_->IsEmpty() ||
        !IsCppHeapMarkingFinished(heap_, local_marking_worklists_.get());
    CHECK(local_weak_objects()->next_ephemerons_local.IsLocalAndGlobalEmpty());
  } while (work_to_do);
  CHECK(local_marking_worklists_->IsEmpty());
  CHECK(weak_objects_.current_ephemerons.IsEmpty());
  CHECK(weak_objects_.next_ephemerons.IsEmpty());
  // Flush local ephemerons for main task to global pool.
  local_weak_objects()->ephemeron_hash_tables_local.Publish();
  local_weak_objects()->next_ephemerons_local.Publish();
}
References CHECK, DCHECK, v8::internal::IsCppHeapMarkingFinished(), v8::internal::Ephemeron::key, v8::base::TimeDelta::Max(), TRACE_GC, and v8::internal::Ephemeron::value.
MarkTransitiveClosureUntilFixpoint()
bool v8::internal::MarkCompactCollector::MarkTransitiveClosureUntilFixpoint () [private]
Definition at line 2058 of file mark-compact.cc.
                                                              {
  int iterations = 0;
  int max_iterations = v8_flags.ephemeron_fixpoint_iterations;
  bool another_ephemeron_iteration_main_thread;
  do {
    if (iterations >= max_iterations) {
      // Give up fixpoint iteration and switch to linear algorithm.
      return false;
    }
    PerformWrapperTracing();
    // Move ephemerons from next_ephemerons into current_ephemerons to
    // drain them in this iteration.
    DCHECK(
        local_weak_objects()->current_ephemerons_local.IsLocalAndGlobalEmpty());
    weak_objects_.current_ephemerons.Merge(weak_objects_.next_ephemerons);
    heap_->concurrent_marking()->set_another_ephemeron_iteration(false);
    {
      TRACE_GC(heap_->tracer(),
               GCTracer::Scope::MC_MARK_WEAK_CLOSURE_EPHEMERON_MARKING);
      another_ephemeron_iteration_main_thread = ProcessEphemerons();
    }
    CHECK(
        local_weak_objects()->current_ephemerons_local.IsLocalAndGlobalEmpty());
    CHECK(local_weak_objects()->next_ephemerons_local.IsLocalEmpty());
    ++iterations;
  } while (another_ephemeron_iteration_main_thread ||
           heap_->concurrent_marking()->another_ephemeron_iteration() ||
           !local_marking_worklists_->IsEmpty() ||
           !IsCppHeapMarkingFinished(heap_, local_marking_worklists_.get()));
  return true;
}
References CHECK, DCHECK, v8::internal::IsCppHeapMarkingFinished(), TRACE_GC, and v8::internal::v8_flags.
MaybeEnableBackgroundThreadsInCycle()
void v8::internal::MarkCompactCollector::MaybeEnableBackgroundThreadsInCycle (CallOrigin origin)
Definition at line 466 of file mark-compact.cc.
                       {
  if (v8_flags.concurrent_marking && !use_background_threads_in_cycle_) {
    // With --parallel_pause_for_gc_in_background we force background threads in
    // the atomic pause.
    const bool force_background_threads =
        v8_flags.parallel_pause_for_gc_in_background &&
        origin == CallOrigin::kAtomicGC;
    use_background_threads_in_cycle_ =
        force_background_threads || heap()->ShouldUseBackgroundThreads();
    if (use_background_threads_in_cycle_) {
      heap_->concurrent_marking()->RescheduleJobIfNeeded(
          GarbageCollector::MARK_COMPACTOR);
      if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap_)) {
        cpp_heap->ReEnableConcurrentMarking();
      }
    }
  }
}
References v8::internal::Heap::concurrent_marking(), v8::internal::Heap::cpp_heap_, v8::internal::CppHeap::From(), heap(), heap_, kAtomicGC, v8::internal::MARK_COMPACTOR, v8::internal::ConcurrentMarking::RescheduleJobIfNeeded(), v8::internal::Heap::ShouldUseBackgroundThreads(), use_background_threads_in_cycle_, and v8::internal::v8_flags.
Referenced by CollectGarbage(), and v8::internal::IncrementalMarking::Step().
NumberOfParallelEphemeronVisitingTasks()
int v8::internal::MarkCompactCollector::NumberOfParallelEphemeronVisitingTasks (size_t elements) [private]
PerformWrapperTracing()
void v8::internal::MarkCompactCollector::PerformWrapperTracing () [private]
Definition at line 2185 of file mark-compact.cc.
                                                 {
  auto* cpp_heap = CppHeap::From(heap_->cpp_heap_);
  if (!cpp_heap) return;
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_MARK_EMBEDDER_TRACING);
  cpp_heap->AdvanceMarking(v8::base::TimeDelta::Max(), SIZE_MAX);
}
References v8::base::TimeDelta::Max(), and TRACE_GC.
PinPreciseRootsIfNeeded()
void v8::internal::MarkCompactCollector::PinPreciseRootsIfNeeded () [private]
Definition at line 4909 of file mark-compact.cc.
                                                   {
  if (!heap_->ShouldUsePrecisePinningForMajorGC()) {
    return;
  }
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_EVACUATE_PIN_PAGES);
  Isolate* const isolate = heap_->isolate();
  PrecisePagePinningVisitor root_visitor(this);
  // Mark the heap roots including global variables, stack variables,
  // etc., and all objects reachable from them.
  heap_->IterateRootsForPrecisePinning(&root_visitor);
  if (isolate->is_shared_space_isolate()) {
    ClientRootVisitor<> client_root_visitor(&root_visitor);
    isolate->global_safepoint()->IterateClientIsolates(
        [&client_root_visitor](Isolate* client) {
          client->heap()->IterateRootsForPrecisePinning(&client_root_visitor);
        });
  }
}
References v8::internal::Isolate::global_safepoint(), v8::internal::Isolate::heap(), v8::internal::Isolate::is_shared_space_isolate(), v8::internal::Factory::isolate(), v8::internal::GlobalSafepoint::IterateClientIsolates(), and TRACE_GC.
PostProcessAbortedEvacuationCandidates()
size_t v8::internal::MarkCompactCollector::PostProcessAbortedEvacuationCandidates () [private]
Definition at line 5926 of file mark-compact.cc.
                                                                    {
  for (auto start_and_page : aborted_evacuation_candidates_due_to_oom_) {
    PageMetadata* page = start_and_page.second;
    MemoryChunk* chunk = page->Chunk();
    DCHECK(!chunk->IsFlagSet(MemoryChunk::COMPACTION_WAS_ABORTED));
    chunk->SetFlagSlow(MemoryChunk::COMPACTION_WAS_ABORTED);
  }
  for (auto start_and_page : aborted_evacuation_candidates_due_to_oom_) {
    ReRecordPage(heap_, start_and_page.first, start_and_page.second);
  }
  for (auto page : aborted_evacuation_candidates_due_to_flags_) {
    ReRecordPage(heap_, page->area_start(), page);
  }
  const size_t aborted_pages =
      aborted_evacuation_candidates_due_to_oom_.size() +
      aborted_evacuation_candidates_due_to_flags_.size();
  size_t aborted_pages_verified = 0;
  for (PageMetadata* p : old_space_evacuation_pages_) {
    MemoryChunk* chunk = p->Chunk();
    if (chunk->IsFlagSet(MemoryChunk::COMPACTION_WAS_ABORTED)) {
      // Only clear EVACUATION_CANDIDATE flag after all slots were re-recorded
      // on all aborted pages. Necessary since repopulating
      // OLD_TO_OLD still requires the EVACUATION_CANDIDATE flag. After clearing
      // the evacuation candidate flag the page is again in a regular state.
      p->ClearEvacuationCandidate();
      aborted_pages_verified++;
    } else {
      DCHECK(chunk->IsEvacuationCandidate());
      DCHECK(p->SweepingDone());
    }
  }
  DCHECK_EQ(aborted_pages_verified, aborted_pages);
  USE(aborted_pages_verified);
  return aborted_pages;
}
References v8::internal::MemoryChunkMetadata::Chunk(), DCHECK, DCHECK_EQ, v8::internal::MemoryChunk::IsEvacuationCandidate(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::anonymous_namespace{mark-compact.cc}::ReRecordPage(), v8::internal::MemoryChunk::SetFlagSlow(), and USE.
Prepare()
void v8::internal::MarkCompactCollector::Prepare ()
Definition at line 765 of file mark-compact.cc.
                                   {
#ifdef DEBUG
  DCHECK(state_ == IDLE);
  state_ = PREPARE_GC;
#endif // DEBUG
  DCHECK(!sweeper_->sweeping_in_progress());
  DCHECK_IMPLIES(heap_->incremental_marking()->IsMarking(),
                 heap_->incremental_marking()->IsMajorMarking());
  if (!heap_->incremental_marking()->IsMarking()) {
    StartCompaction(StartCompactionMode::kAtomic);
    StartMarking();
    if (heap_->cpp_heap_) {
      TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_MARK_EMBEDDER_PROLOGUE);
      // `StartMarking()` immediately starts marking which requires V8 worklists
      // to be set up.
      CppHeap::From(heap_->cpp_heap_)->StartMarking();
    }
  }
  if (auto* new_space = heap_->new_space()) {
    new_space->GarbageCollectionPrologue();
  }
  if (heap_->use_new_space()) {
#ifdef DEBUG
    Address original_top = heap_->allocator()
                               ->new_space_allocator()
                               ->GetOriginalTopAndLimit()
                               .first;
    DCHECK_EQ(heap_->allocator()->new_space_allocator()->top(), original_top);
#endif // DEBUG
  }
}
References v8::internal::Heap::allocator(), v8::internal::Heap::cpp_heap_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, v8::internal::CppHeap::From(), v8::internal::MainAllocator::GetOriginalTopAndLimit(), heap_, v8::IDLE, v8::internal::Heap::incremental_marking(), v8::internal::IncrementalMarking::IsMajorMarking(), v8::internal::IncrementalMarking::IsMarking(), kAtomic, v8::internal::Heap::new_space(), v8::internal::HeapAllocator::new_space_allocator(), StartCompaction(), v8::internal::CppHeap::StartMarking(), StartMarking(), sweeper_, v8::internal::Sweeper::sweeping_in_progress(), v8::internal::MainAllocator::top(), TRACE_GC, v8::internal::Heap::tracer(), and v8::internal::Heap::use_new_space().
Referenced by v8::internal::Heap::MarkCompact().
ProcessEphemeron()
bool v8::internal::MarkCompactCollector::ProcessEphemeron (Tagged< HeapObject > key, Tagged< HeapObject > value) [private]
Definition at line 2273 of file mark-compact.cc.
                                                                      {
  EphemeronResult result = ApplyEphemeronSemantics(key, value);
  if (result == EphemeronResult::kUnresolved) {
    local_weak_objects()->next_ephemerons_local.Push(Ephemeron{key, value});
    return true;
  }
  return result == EphemeronResult::kMarkedValue;
}
References v8::internal::key, v8::base::internal::result, and v8::internal::value.
ProcessEphemerons()
bool v8::internal::MarkCompactCollector::ProcessEphemerons () [private]
Definition at line 2098 of file mark-compact.cc.
                                             {
  Ephemeron ephemeron;
  bool another_ephemeron_iteration = false;
  // Drain current_ephemerons and push ephemerons where key and value are still
  // unreachable into next_ephemerons.
  while (local_weak_objects()->current_ephemerons_local.Pop(&ephemeron)) {
    if (ProcessEphemeron(ephemeron.key, ephemeron.value)) {
      another_ephemeron_iteration = true;
    }
  }
  // Drain marking worklist and push discovered ephemerons into
  // next_ephemerons.
  size_t objects_processed;
  std::tie(std::ignore, objects_processed) =
      ProcessMarkingWorklist(v8::base::TimeDelta::Max(), SIZE_MAX);
  // As soon as a single object was processed and potentially marked another
  // object we need another iteration. Otherwise we might miss to apply
  // ephemeron semantics on it.
  if (objects_processed > 0) another_ephemeron_iteration = true;
  // Flush local ephemerons for main task to global pool.
  local_weak_objects()->ephemeron_hash_tables_local.Publish();
  local_weak_objects()->next_ephemerons_local.Publish();
  return another_ephemeron_iteration;
}
References wasm::ignore(), v8::internal::Ephemeron::key, v8::base::TimeDelta::Max(), and v8::internal::Ephemeron::value.
ProcessFlushedBaselineCandidates()
void v8::internal::MarkCompactCollector::ProcessFlushedBaselineCandidates () [private]
Definition at line 3552 of file mark-compact.cc.
                                                            {
  DCHECK(v8_flags.flush_baseline_code ||
         weak_objects_.baseline_flushing_candidates.IsEmpty());
  Tagged<JSFunction> flushed_js_function;
  while (local_weak_objects()->baseline_flushing_candidates_local.Pop(
      &flushed_js_function)) {
    auto gc_notify_updated_slot = [](Tagged<HeapObject> object, ObjectSlot slot,
                                     Tagged<Object> target) {
      RecordSlot(object, slot, Cast<HeapObject>(target));
    };
    flushed_js_function->ResetIfCodeFlushed(heap_->isolate(),
                                            gc_notify_updated_slot);
#ifndef V8_ENABLE_SANDBOX
    // Record the code slot that has been updated either to CompileLazy,
    // InterpreterEntryTrampoline or baseline code.
    // This is only necessary when the sandbox is not enabled. If it is, the
    // Code objects are referenced through a pointer table indirection and so
    // remembered slots are not necessary as the Code object will update its
    // entry in the pointer table when it is relocated.
    ObjectSlot slot = flushed_js_function->RawField(JSFunction::kCodeOffset);
    RecordSlot(flushed_js_function, slot, Cast<HeapObject>(*slot));
#endif
  }
}
References DCHECK, and v8::internal::v8_flags.
ProcessMarkingWorklist()
template<MarkCompactCollector::MarkingWorklistProcessingMode mode>
std::pair< size_t, size_t > v8::internal::MarkCompactCollector::ProcessMarkingWorklist (v8::base::TimeDelta max_duration, size_t max_bytes_to_process)
Definition at line 2200 of file mark-compact.cc.
                                                               {
  Tagged<HeapObject> object;
  size_t bytes_processed = 0;
  size_t objects_processed = 0;
  bool is_per_context_mode = local_marking_worklists_->IsPerContextMode();
  Isolate* const isolate = heap_->isolate();
  const auto start = v8::base::TimeTicks::Now();
  PtrComprCageBase cage_base(isolate);
  if (parallel_marking_ && UseBackgroundThreadsInCycle()) {
    heap_->concurrent_marking()->RescheduleJobIfNeeded(
        GarbageCollector::MARK_COMPACTOR, TaskPriority::kUserBlocking);
  }
  while (local_marking_worklists_->Pop(&object) ||
         local_marking_worklists_->PopOnHold(&object)) {
    // The marking worklist should never contain filler objects.
    CHECK(!IsFreeSpaceOrFiller(object, cage_base));
    DCHECK(IsHeapObject(object));
    DCHECK(!HeapLayout::InReadOnlySpace(object));
    DCHECK_EQ(HeapUtils::GetOwnerHeap(object), heap_);
    DCHECK(heap_->Contains(object));
    DCHECK(!(marking_state_->IsUnmarked(object)));
    if constexpr (mode ==
                  MarkingWorklistProcessingMode::kProcessRememberedEphemerons) {
      auto it = key_to_values_.find(object);
      if (it != key_to_values_.end()) {
        for (Tagged<HeapObject> value : it->second) {
          const auto target_worklist =
              MarkingHelper::ShouldMarkObject(heap_, value);
          if (target_worklist) {
            MarkObject(object, value, target_worklist.value());
          }
        }
        key_to_values_.erase(it);
      }
    }
    Tagged<Map> map = object->map(cage_base);
    if (is_per_context_mode) {
      Address context;
      if (native_context_inferrer_.Infer(cage_base, map, object, &context)) {
        local_marking_worklists_->SwitchToContext(context);
      }
    }
    const auto visited_size = marking_visitor_->Visit(map, object);
    if (visited_size) {
      MutablePageMetadata::FromHeapObject(object)->IncrementLiveBytesAtomically(
          ALIGN_TO_ALLOCATION_ALIGNMENT(visited_size));
    }
    if (is_per_context_mode) {
      native_context_stats_.IncrementSize(local_marking_worklists_->Context(),
                                          map, object, visited_size);
    }
    bytes_processed += visited_size;
    objects_processed++;
    static_assert(base::bits::IsPowerOfTwo(kDeadlineCheckInterval),
                  "kDeadlineCheckInterval must be power of 2");
    // The below check is an optimized version of
    // `(objects_processed % kDeadlineCheckInterval) == 0`
    if ((objects_processed & (kDeadlineCheckInterval -1)) == 0 &&
        ((v8::base::TimeTicks::Now() - start) > max_duration)) {
      break;
    }
    if (bytes_processed >= max_bytes_to_process) {
      break;
    }
  }
  return std::make_pair(bytes_processed, objects_processed);
}
References ALIGN_TO_ALLOCATION_ALIGNMENT, CHECK, DCHECK, DCHECK_EQ, v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller(), v8::internal::InstanceTypeChecker::IsHeapObject(), v8::internal::Factory::isolate(), v8::base::bits::IsPowerOfTwo(), v8::internal::anonymous_namespace{mark-compact.cc}::kDeadlineCheckInterval, v8::kUserBlocking, v8::internal::anonymous_namespace{traced-handles.cc}::MarkObject(), mode(), v8::base::TimeTicks::Now(), and v8::internal::value.
Referenced by v8::internal::IncrementalMarking::Step().
ProcessOldBaselineSFI()
bool v8::internal::MarkCompactCollector::ProcessOldBaselineSFI (Tagged< SharedFunctionInfo > flushing_candidate) [private]
Definition at line 3462 of file mark-compact.cc.
                                                   {
  Tagged<Code> baseline_code = flushing_candidate->baseline_code(kAcquireLoad);
  // Safe to do a relaxed load here since the Code was acquire-loaded.
  Tagged<InstructionStream> baseline_istream =
      baseline_code->instruction_stream(baseline_code->code_cage_base(),
                                        kRelaxedLoad);
  Tagged<HeapObject> baseline_bytecode_or_interpreter_data =
      baseline_code->bytecode_or_interpreter_data();
  // During flushing a BytecodeArray is transformed into an UncompiledData
  // in place. Seeing an UncompiledData here implies that another
  // SharedFunctionInfo had a reference to the same BytecodeArray and
  // flushed it before processing this candidate. This can happen when using
  // CloneSharedFunctionInfo().
  const bool bytecode_already_decompiled =
      IsUncompiledData(baseline_bytecode_or_interpreter_data, heap_->isolate());
  bool is_bytecode_live = false;
  if (!bytecode_already_decompiled) {
    Tagged<BytecodeArray> bytecode =
        flushing_candidate->GetBytecodeArray(heap_->isolate());
    is_bytecode_live = MarkingHelper::IsMarkedOrAlwaysLive(
        heap_, non_atomic_marking_state_, bytecode);
  }
  if (MarkingHelper::IsMarkedOrAlwaysLive(heap_, non_atomic_marking_state_,
                                          baseline_istream)) {
    // Currently baseline code holds bytecode array strongly and it is
    // always ensured that bytecode is live if baseline code is live. Hence
    // baseline code can safely load bytecode array without any additional
    // checks. In future if this changes we need to update these checks to
    // flush code if the bytecode is not live and also update baseline code
    // to bailout if there is no bytecode.
    DCHECK(is_bytecode_live);
    // Regardless of whether the Code is a Code or
    // the InstructionStream itself, if the InstructionStream is live then
    // the Code has to be live and will have been marked via
    // the owning JSFunction.
    DCHECK(MarkingHelper::IsMarkedOrAlwaysLive(heap_, non_atomic_marking_state_,
                                               baseline_code));
  } else if (is_bytecode_live || bytecode_already_decompiled) {
    // Reset the function_data field to the BytecodeArray, InterpreterData,
    // or UncompiledData found on the baseline code. We can skip this step
    // if the BytecodeArray is not live and not already decompiled, because
    // FlushBytecodeFromSFI below will set the function_data field.
    flushing_candidate->FlushBaselineCode();
  }
  if (!is_bytecode_live) {
    FlushSFI(flushing_candidate, bytecode_already_decompiled);
  }
  return is_bytecode_live;
}
References DCHECK, v8::kAcquireLoad, and v8::kRelaxedLoad.
ProcessOldBytecodeSFI()
bool v8::internal::MarkCompactCollector::ProcessOldBytecodeSFI (Tagged< SharedFunctionInfo > flushing_candidate) [private]
Definition at line 3438 of file mark-compact.cc.
                                                   {
  // During flushing a BytecodeArray is transformed into an UncompiledData
  // in place. Seeing an UncompiledData here implies that another
  // SharedFunctionInfo had a reference to the same BytecodeArray and
  // flushed it before processing this candidate. This can happen when using
  // CloneSharedFunctionInfo().
  Isolate* const isolate = heap_->isolate();
  const bool bytecode_already_decompiled =
      flushing_candidate->HasUncompiledData(isolate);
  if (!bytecode_already_decompiled) {
    // Check if the bytecode is still live.
    Tagged<BytecodeArray> bytecode =
        flushing_candidate->GetBytecodeArray(isolate);
    if (MarkingHelper::IsMarkedOrAlwaysLive(heap_, non_atomic_marking_state_,
                                            bytecode)) {
      return true;
    }
  }
  FlushSFI(flushing_candidate, bytecode_already_decompiled);
  return false;
}
References v8::internal::Factory::isolate().
ProcessOldCodeCandidates()
void v8::internal::MarkCompactCollector::ProcessOldCodeCandidates () [private]
Definition at line 3402 of file mark-compact.cc.
                                                    {
  DCHECK(v8_flags.flush_bytecode || v8_flags.flush_baseline_code ||
         weak_objects_.code_flushing_candidates.IsEmpty());
  Tagged<SharedFunctionInfo> flushing_candidate;
  int number_of_flushed_sfis = 0;
  while (local_weak_objects()->code_flushing_candidates_local.Pop(
      &flushing_candidate)) {
    bool is_bytecode_live;
    if (v8_flags.flush_baseline_code && flushing_candidate->HasBaselineCode()) {
      is_bytecode_live = ProcessOldBaselineSFI(flushing_candidate);
    } else {
      is_bytecode_live = ProcessOldBytecodeSFI(flushing_candidate);
    }
    if (!is_bytecode_live) number_of_flushed_sfis++;
    // Now record the data slots, which have been updated to an uncompiled
    // data, Baseline code or BytecodeArray which is still alive.
#ifndef V8_ENABLE_SANDBOX
    // If the sandbox is enabled, the slot contains an indirect pointer which
    // does not need to be updated during mark-compact (because the pointer in
    // the pointer table will be updated), so no action is needed here.
    ObjectSlot slot = flushing_candidate->RawField(
        SharedFunctionInfo::kTrustedFunctionDataOffset);
    if (IsHeapObject(*slot)) {
      RecordSlot(flushing_candidate, slot, Cast<HeapObject>(*slot));
    }
#endif
  }
  if (v8_flags.trace_flush_code) {
    PrintIsolate(heap_->isolate(), "%d flushed SharedFunctionInfo(s)\n",
                 number_of_flushed_sfis);
  }
}
References DCHECK, v8::internal::InstanceTypeChecker::IsHeapObject(), v8::internal::PrintIsolate(), and v8::internal::v8_flags.
ProcessRelocInfo()
MarkCompactCollector::RecordRelocSlotInfo v8::internal::MarkCompactCollector::ProcessRelocInfo (Tagged< InstructionStream > host, RelocInfo * rinfo, Tagged< HeapObject > target) [static]
Definition at line 4020 of file mark-compact.cc.
                                                                  {
  RecordRelocSlotInfo result;
  const RelocInfo::Mode rmode = rinfo->rmode();
  Address addr;
  SlotType slot_type;
  if (rinfo->IsInConstantPool()) {
    addr = rinfo->constant_pool_entry_address();
    if (RelocInfo::IsCodeTargetMode(rmode)) {
      slot_type = SlotType::kConstPoolCodeEntry;
    } else if (RelocInfo::IsCompressedEmbeddedObject(rmode)) {
      slot_type = SlotType::kConstPoolEmbeddedObjectCompressed;
    } else {
      DCHECK(RelocInfo::IsFullEmbeddedObject(rmode));
      slot_type = SlotType::kConstPoolEmbeddedObjectFull;
    }
  } else {
    addr = rinfo->pc();
    if (RelocInfo::IsCodeTargetMode(rmode)) {
      slot_type = SlotType::kCodeEntry;
    } else if (RelocInfo::IsFullEmbeddedObject(rmode)) {
      slot_type = SlotType::kEmbeddedObjectFull;
    } else {
      DCHECK(RelocInfo::IsCompressedEmbeddedObject(rmode));
      slot_type = SlotType::kEmbeddedObjectCompressed;
    }
  }
  MemoryChunk* const source_chunk = MemoryChunk::FromHeapObject(host);
  MutablePageMetadata* const source_page_metadata =
      MutablePageMetadata::cast(source_chunk->Metadata());
  const uintptr_t offset = source_chunk->Offset(addr);
  DCHECK_LT(offset, static_cast<uintptr_t>(TypedSlotSet::kMaxOffset));
  result.page_metadata = source_page_metadata;
  result.slot_type = slot_type;
  result.offset = static_cast<uint32_t>(offset);
  return result;
}
References v8::internal::RelocInfo::constant_pool_entry_address(), DCHECK, DCHECK_LT, v8::internal::RelocInfo::IsInConstantPool(), v8::internal::compiler::kCodeEntry, v8::internal::MemoryChunk::Metadata(), v8::internal::MemoryChunk::Offset(), v8::internal::RelocInfo::pc(), v8::base::internal::result, and v8::internal::RelocInfo::rmode().
Referenced by v8::internal::WriteBarrier::GenerationalBarrierForCodeSlow(), v8::internal::ConcurrentMarkingVisitor::RecordRelocSlot(), v8::internal::MarkingBarrier::RecordRelocSlot(), and v8::internal::WriteBarrier::SharedSlow().
ProcessTopOptimizedFrame()
void v8::internal::MarkCompactCollector::ProcessTopOptimizedFrame (ObjectVisitor * visitor, Isolate * isolate) [private]
Definition at line 2359 of file mark-compact.cc.
                                                                      {
  for (StackFrameIterator it(isolate, isolate->thread_local_top()); !it.done();
       it.Advance()) {
    if (it.frame()->is_unoptimized_js()) return;
    if (it.frame()->is_optimized_js()) {
      Tagged<GcSafeCode> lookup_result = it.frame()->GcSafeLookupCode();
      if (!lookup_result->has_instruction_stream()) return;
      if (!lookup_result->CanDeoptAt(isolate,
                                     it.frame()->maybe_unauthenticated_pc())) {
        Tagged<InstructionStream> istream = UncheckedCast<InstructionStream>(
            lookup_result->raw_instruction_stream());
        PtrComprCageBase cage_base(isolate);
        InstructionStream::BodyDescriptor::IterateBody(istream->map(cage_base),
                                                       istream, visitor);
      }
      return;
    }
  }
}
References v8::internal::StackFrameIteratorBase::done(), and v8::internal::Isolate::thread_local_top().
Referenced by MarkRoots().
RecordObjectStats()
void v8::internal::MarkCompactCollector::RecordObjectStats () [private]
Definition at line 2380 of file mark-compact.cc.
                                             {
  if (V8_LIKELY(!TracingFlags::is_gc_stats_enabled())) return;
  // Cannot run during bootstrapping due to incomplete objects.
  if (heap_->isolate()->bootstrapper()->IsActive()) return;
  TRACE_EVENT0(TRACE_GC_CATEGORIES, "V8.GC_OBJECT_DUMP_STATISTICS");
  heap_->CreateObjectStats();
  ObjectStatsCollector collector(heap_, heap_->live_object_stats_.get(),
                                 heap_->dead_object_stats_.get());
  collector.Collect();
  if (V8_UNLIKELY(TracingFlags::gc_stats.load(std::memory_order_relaxed) &
                  v8::tracing::TracingCategoryObserver::ENABLED_BY_TRACING)) {
    std::stringstream live, dead;
    heap_->live_object_stats_->Dump(live);
    heap_->dead_object_stats_->Dump(dead);
    TRACE_EVENT_INSTANT2(TRACE_DISABLED_BY_DEFAULT("v8.gc_stats"),
                         "V8.GC_Objects_Stats", TRACE_EVENT_SCOPE_THREAD,
                         "live", TRACE_STR_COPY(live.str().c_str()), "dead",
                         TRACE_STR_COPY(dead.str().c_str()));
  }
  if (v8_flags.trace_gc_object_stats) {
    heap_->live_object_stats_->PrintJSON("live");
    heap_->dead_object_stats_->PrintJSON("dead");
  }
  heap_->live_object_stats_->CheckpointObjectStats();
  heap_->dead_object_stats_->ClearObjectStats();
}
References v8::internal::ObjectStatsCollector::Collect(), v8::tracing::TracingCategoryObserver::ENABLED_BY_TRACING, TRACE_DISABLED_BY_DEFAULT, TRACE_EVENT0, TRACE_EVENT_INSTANT2, TRACE_EVENT_SCOPE_THREAD, TRACE_GC_CATEGORIES, TRACE_STR_COPY, v8::internal::v8_flags, V8_LIKELY, and V8_UNLIKELY.
Referenced by CollectGarbage().
RecordRelocSlot()
void v8::internal::MarkCompactCollector::RecordRelocSlot (Tagged< InstructionStream > host, RelocInfo * rinfo, Tagged< HeapObject > target) [static]
Definition at line 4065 of file mark-compact.cc.
                                                                      {
  if (!ShouldRecordRelocSlot(host, rinfo, target)) return;
  RecordRelocSlotInfo info = ProcessRelocInfo(host, rinfo, target);
  // Access to TypeSlots need to be protected, since LocalHeaps might
  // publish code in the background thread.
  std::optional<base::MutexGuard> opt_guard;
  if (v8_flags.concurrent_sparkplug) {
    opt_guard.emplace(info.page_metadata->mutex());
  }
  RememberedSet<OLD_TO_OLD>::InsertTyped(info.page_metadata, info.slot_type,
                                         info.offset);
}
References v8::internal::MutablePageMetadata::mutex(), v8::internal::MarkCompactCollector::RecordRelocSlotInfo::offset, v8::internal::MarkCompactCollector::RecordRelocSlotInfo::page_metadata, v8::internal::MarkCompactCollector::RecordRelocSlotInfo::slot_type, and v8::internal::v8_flags.
Referenced by v8::internal::RecordMigratedSlotVisitor::VisitCodeTarget(), v8::internal::RecordMigratedSlotVisitor::VisitEmbeddedPointer(), and v8::internal::MarkingBarrier::Write().
RecordSlot() [1/2]
template<typename THeapObjectSlot >
void v8::internal::MarkCompactCollector::RecordSlot (MemoryChunk * source_chunk, THeapObjectSlot slot, Tagged< HeapObject > target) [inline], [static]
Definition at line 71 of file mark-compact-inl.h.
                                                                 {
  MemoryChunk* target_chunk = MemoryChunk::FromHeapObject(target);
  if (target_chunk->IsEvacuationCandidate()) {
    MutablePageMetadata* source_page =
        MutablePageMetadata::cast(source_chunk->Metadata());
    if (target_chunk->IsFlagSet(MemoryChunk::IS_EXECUTABLE)) {
      // TODO(377724745): currently needed because flags are untrusted.
      SBXCHECK(!InsideSandbox(target_chunk->address()));
      RememberedSet<TRUSTED_TO_CODE>::Insert<AccessMode::ATOMIC>(
          source_page, source_chunk->Offset(slot.address()));
    } else if (source_chunk->IsFlagSet(MemoryChunk::IS_TRUSTED) &&
               target_chunk->IsFlagSet(MemoryChunk::IS_TRUSTED)) {
      // TODO(377724745): currently needed because flags are untrusted.
      SBXCHECK(!InsideSandbox(target_chunk->address()));
      RememberedSet<TRUSTED_TO_TRUSTED>::Insert<AccessMode::ATOMIC>(
          source_page, source_chunk->Offset(slot.address()));
    } else if (V8_LIKELY(!target_chunk->InWritableSharedSpace()) ||
               source_page->heap()->isolate()->is_shared_space_isolate()) {
      DCHECK_EQ(source_page->heap(), target_chunk->GetHeap());
      RememberedSet<OLD_TO_OLD>::Insert<AccessMode::ATOMIC>(
          source_page, source_chunk->Offset(slot.address()));
    } else {
      // DCHECK here that we only don't record in case of local->shared
      // references in a client GC.
      DCHECK(!source_page->heap()->isolate()->is_shared_space_isolate());
      DCHECK(target_chunk->GetHeap()->isolate()->is_shared_space_isolate());
      DCHECK(target_chunk->InWritableSharedSpace());
    }
  }
}
References v8::internal::MemoryChunk::address(), v8::internal::MutablePageMetadata::cast(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::MemoryChunk::FromHeapObject(), v8::internal::MemoryChunk::GetHeap(), v8::internal::MemoryChunkMetadata::heap(), v8::internal::InsideSandbox(), v8::internal::MemoryChunk::InWritableSharedSpace(), v8::internal::MemoryChunk::IS_EXECUTABLE, v8::internal::Isolate::is_shared_space_isolate(), v8::internal::MemoryChunk::IS_TRUSTED, v8::internal::MemoryChunk::IsEvacuationCandidate(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::Heap::isolate(), v8::internal::MemoryChunk::Metadata(), v8::internal::MemoryChunk::Offset(), SBXCHECK, and V8_LIKELY.
RecordSlot() [2/2]
template<typename THeapObjectSlot >
void v8::internal::MarkCompactCollector::RecordSlot (Tagged< HeapObject > object, THeapObjectSlot slot, Tagged< HeapObject > target) [inline], [static]
Definition at line 60 of file mark-compact-inl.h.
                                                                 {
  MemoryChunk* source_page = MemoryChunk::FromHeapObject(object);
  if (!source_page->ShouldSkipEvacuationSlotRecording()) {
    RecordSlot(source_page, slot, target);
  }
}
References v8::internal::MemoryChunk::FromHeapObject(), and v8::internal::MemoryChunk::ShouldSkipEvacuationSlotRecording().
Referenced by v8::internal::anonymous_namespace{heap-write-barrier.cc}::ForRangeImpl(), v8::internal::MarkingBarrier::MarkRange(), v8::internal::ConcurrentMarkingVisitor::RecordSlot(), v8::internal::MainMarkingVisitor::RecordSlot(), v8::internal::WeakListVisitor< Context >::VisitLiveObject(), v8::internal::VisitWeakList(), and v8::internal::MarkingBarrier::Write().
RecordStrongDescriptorArraysForWeakening()
void v8::internal::MarkCompactCollector::RecordStrongDescriptorArraysForWeakening (GlobalHandleVector< DescriptorArray > strong_descriptor_arrays)
Definition at line 3747 of file mark-compact.cc.
                                                                  {
  DCHECK(heap_->incremental_marking()->IsMajorMarking());
  base::MutexGuard guard(&strong_descriptor_arrays_mutex_);
  strong_descriptor_arrays_.push_back(std::move(strong_descriptor_arrays));
}
References DCHECK.
Referenced by v8::internal::Heap::WeakenDescriptorArrays().
ReleaseEvacuationCandidates()
void v8::internal::MarkCompactCollector::ReleaseEvacuationCandidates () [private]
Definition at line 5962 of file mark-compact.cc.
                                                       {
  for (PageMetadata* p : old_space_evacuation_pages_) {
    if (!p->Chunk()->IsEvacuationCandidate()) continue;
    PagedSpace* space = static_cast<PagedSpace*>(p->owner());
    p->SetLiveBytes(0);
    CHECK(p->SweepingDone());
    ReleasePage(space, p);
  }
  old_space_evacuation_pages_.clear();
  compacting_ = false;
}
References CHECK, and space.
ReleasePage()
void v8::internal::MarkCompactCollector::ReleasePage (PagedSpaceBase * space, PageMetadata * page) [private]
Definition at line 5974 of file mark-compact.cc.
                                                           {
  space->RemovePageFromSpace(page);
  switch (space->identity()) {
    case SHARED_SPACE: {
      // Old-to-new slots in old objects may be overwritten with references to
      // shared objects. Postpone releasing empty pages so that updating
      // old-to-new slots in dead old objects may access the dead shared
      // objects.
      queued_pages_to_be_freed_.push_back(page);
      break;
    }
    case OLD_SPACE:
    case NEW_SPACE: {
      heap()->memory_allocator()->Free(MemoryAllocator::FreeMode::kPool, page);
      break;
    }
    default: {
      heap()->memory_allocator()->Free(MemoryAllocator::FreeMode::kImmediately,
                                       page);
    }
  }
}
References heap(), v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, v8::internal::SHARED_SPACE, and space.
ReportAbortedEvacuationCandidateDueToFlags()
void v8::internal::MarkCompactCollector::ReportAbortedEvacuationCandidateDueToFlags (PageMetadata * page, MemoryChunk * chunk) [private]
Definition at line 5879 of file mark-compact.cc.
                                            {
  DCHECK_EQ(page->Chunk(), chunk);
  if (chunk->IsFlagSet(MemoryChunk::COMPACTION_WAS_ABORTED)) {
    return;
  }
  chunk->SetFlagSlow(MemoryChunk::COMPACTION_WAS_ABORTED);
  aborted_evacuation_candidates_due_to_flags_.push_back(page);
}
References v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_EQ, v8::internal::MemoryChunk::IsFlagSet(), and v8::internal::MemoryChunk::SetFlagSlow().
Referenced by MarkRootObject().
ReportAbortedEvacuationCandidateDueToOOM()
void v8::internal::MarkCompactCollector::ReportAbortedEvacuationCandidateDueToOOM (Address failed_start, PageMetadata * page) [private]
Definition at line 5872 of file mark-compact.cc.
                                              {
  base::MutexGuard guard(&mutex_);
  aborted_evacuation_candidates_due_to_oom_.push_back(
      std::make_pair(failed_start, page));
}
ResetAndRelinkBlackAllocatedPage()
void v8::internal::MarkCompactCollector::ResetAndRelinkBlackAllocatedPage (PagedSpace * space, PageMetadata * page) [private]
Definition at line 6035 of file mark-compact.cc.
                                           {
  DCHECK(page->Chunk()->IsFlagSet(MemoryChunk::BLACK_ALLOCATED));
  DCHECK_EQ(page->live_bytes(), 0);
  DCHECK_GE(page->allocated_bytes(), 0);
  DCHECK(page->marking_bitmap()->IsClean());
  std::optional<RwxMemoryWriteScope> scope;
  if (page->Chunk()->InCodeSpace()) {
    scope.emplace("For writing flags.");
  }
  page->Chunk()->ClearFlagUnlocked(MemoryChunk::BLACK_ALLOCATED);
  space->IncreaseAllocatedBytes(page->allocated_bytes(), page);
  space->RelinkFreeListCategories(page);
}
References v8::internal::MemoryChunkMetadata::allocated_bytes(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::MemoryChunk::ClearFlagUnlocked(), DCHECK, DCHECK_EQ, DCHECK_GE, v8::internal::MemoryChunk::InCodeSpace(), v8::internal::MarkingBitmap::IsClean(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MutablePageMetadata::live_bytes(), v8::internal::MutablePageMetadata::marking_bitmap(), and space.
RetainMaps()
void v8::internal::MarkCompactCollector::RetainMaps () [private]
Definition at line 2428 of file mark-compact.cc.
                                      {
  // Retaining maps increases the chances of reusing map transitions at some
  // memory cost, hence disable it when trying to reduce memory footprint more
  // aggressively.
  const bool should_retain_maps =
      !heap_->ShouldReduceMemory() && v8_flags.retain_maps_for_n_gc != 0;
  for (Tagged<WeakArrayList> retained_maps : heap_->FindAllRetainedMaps()) {
    DCHECK_EQ(0, retained_maps->length() % 2);
    for (int i = 0; i < retained_maps->length(); i += 2) {
      Tagged<MaybeObject> value = retained_maps->Get(i);
      Tagged<HeapObject> map_heap_object;
      if (!value.GetHeapObjectIfWeak(&map_heap_object)) {
        continue;
      }
      int age = retained_maps->Get(i + 1).ToSmi().value();
      int new_age;
      Tagged<Map> map = Cast<Map>(map_heap_object);
      if (should_retain_maps && MarkingHelper::IsUnmarkedAndNotAlwaysLive(
                                    heap_, marking_state_, map)) {
        if (ShouldRetainMap(heap_, marking_state_, map, age)) {
          if (MarkingHelper::ShouldMarkObject(heap_, map)) {
            MarkingHelper::TryMarkAndPush(
                heap_, local_marking_worklists_.get(), marking_state_,
                MarkingHelper::WorklistTarget::kRegular, map);
          }
        }
        Tagged<Object> prototype = map->prototype();
        if (age > 0 && IsHeapObject(prototype) &&
            MarkingHelper::IsUnmarkedAndNotAlwaysLive(
                heap_, marking_state_, Cast<HeapObject>(prototype))) {
          // The prototype is not marked, age the map.
          new_age = age - 1;
        } else {
          // The prototype and the constructor are marked, this map keeps only
          // transition tree alive, not JSObjects. Do not age the map.
          new_age = age;
        }
      } else {
        new_age = v8_flags.retain_maps_for_n_gc;
      }
      // Compact the array and update the age.
      if (new_age != age) {
        retained_maps->Set(i + 1, Smi::FromInt(new_age));
      }
    }
  }
}
References DCHECK_EQ, v8::internal::InstanceTypeChecker::IsHeapObject(), v8_inspector::anonymous_namespace{v8-console.cc}::kRegular, v8::internal::prototype, v8::internal::anonymous_namespace{mark-compact.cc}::ShouldRetainMap(), v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi(), v8::internal::v8_flags, and v8::internal::value.
RightTrimDescriptorArray()
void v8::internal::MarkCompactCollector::RightTrimDescriptorArray (Tagged< DescriptorArray > array, int descriptors_to_trim) [private]
Definition at line 3711 of file mark-compact.cc.
                                                            {
  int old_nof_all_descriptors = array->number_of_all_descriptors();
  int new_nof_all_descriptors = old_nof_all_descriptors - descriptors_to_trim;
  DCHECK_LT(0, descriptors_to_trim);
  DCHECK_LE(0, new_nof_all_descriptors);
  Address start = array->GetDescriptorSlot(new_nof_all_descriptors).address();
  Address end = array->GetDescriptorSlot(old_nof_all_descriptors).address();
  MutablePageMetadata* chunk = MutablePageMetadata::FromHeapObject(array);
  RememberedSet<OLD_TO_NEW>::RemoveRange(chunk, start, end,
                                         SlotSet::FREE_EMPTY_BUCKETS);
  RememberedSet<OLD_TO_NEW_BACKGROUND>::RemoveRange(
      chunk, start, end, SlotSet::FREE_EMPTY_BUCKETS);
  RememberedSet<OLD_TO_SHARED>::RemoveRange(chunk, start, end,
                                            SlotSet::FREE_EMPTY_BUCKETS);
  RememberedSet<OLD_TO_OLD>::RemoveRange(chunk, start, end,
                                         SlotSet::FREE_EMPTY_BUCKETS);
  if (V8_COMPRESS_POINTERS_8GB_BOOL) {
    Address aligned_start = ALIGN_TO_ALLOCATION_ALIGNMENT(start);
    Address aligned_end = ALIGN_TO_ALLOCATION_ALIGNMENT(end);
    if (aligned_start < aligned_end) {
      heap_->CreateFillerObjectAt(
          aligned_start, static_cast<int>(aligned_end - aligned_start));
    }
    if (heap::ShouldZapGarbage()) {
      Address zap_end = std::min(aligned_start, end);
      MemsetTagged(ObjectSlot(start),
                   Tagged<Object>(static_cast<Address>(kZapValue)),
                   (zap_end - start) >> kTaggedSizeLog2);
    }
  } else {
    heap_->CreateFillerObjectAt(start, static_cast<int>(end - start));
  }
  array->set_number_of_all_descriptors(new_nof_all_descriptors);
}
References v8::internal::Tagged< HeapObject >::address(), ALIGN_TO_ALLOCATION_ALIGNMENT, DCHECK_LE, DCHECK_LT, v8::internal::compiler::end(), v8::internal::kTaggedSizeLog2, v8::internal::kZapValue, v8::internal::MemsetTagged(), v8::internal::heap::ShouldZapGarbage(), and V8_COMPRESS_POINTERS_8GB_BOOL.
ShouldRecordRelocSlot()
bool v8::internal::MarkCompactCollector::ShouldRecordRelocSlot (Tagged< InstructionStream > host, RelocInfo * rinfo, Tagged< HeapObject > target) [static]
Definition at line 4009 of file mark-compact.cc.
                                                                            {
  MemoryChunk* source_chunk = MemoryChunk::FromHeapObject(host);
  MemoryChunk* target_chunk = MemoryChunk::FromHeapObject(target);
  return target_chunk->IsEvacuationCandidate() &&
         !source_chunk->ShouldSkipEvacuationSlotRecording();
}
References v8::internal::MemoryChunk::IsEvacuationCandidate(), and v8::internal::MemoryChunk::ShouldSkipEvacuationSlotRecording().
Referenced by v8::internal::ConcurrentMarkingVisitor::RecordRelocSlot(), and v8::internal::MarkingBarrier::RecordRelocSlot().
SpecialClearMapSlot()
bool v8::internal::MarkCompactCollector::SpecialClearMapSlot (Tagged< HeapObject > host, Tagged< Map > dead_target, HeapObjectSlot slot) [private]
Definition at line 3269 of file mark-compact.cc.
                                                                    {
  ClearPotentialSimpleMapTransition(map);
  // Special handling for clearing field type entries, identified by their host
  // being a descriptor array.
  // TODO(olivf): This whole special handling of field-type clearing
  // could be replaced by eagerly triggering field type dependencies and
  // generalizing field types, as soon as a field-type map becomes
  // unstable.
  if (IsDescriptorArray(host)) {
    // We want to distinguish two cases:
    // 1. There are no instances of the descriptor owner's map left.
    // 2. The field type is not up to date because the stored object
    // migrated away to a different map.
    // In case (1) it makes sense to clear the field type such that we
    // can learn a new one should we ever start creating instances
    // again.
    // In case (2) we must not re-learn a new field type. Doing so could
    // lead us to learning a field type that is not consistent with
    // still existing object's contents. To conservatively identify case
    // (1) we check the stability of the dead map.
    MaybeObjectSlot location(slot);
    if (map->is_stable() && FieldType::kFieldTypesCanBeClearedOnGC) {
      location.store(FieldType::None());
    } else {
      location.store(FieldType::Any());
    }
    return true;
  }
  return false;
}
References v8::None, and v8::internal::FullMaybeObjectSlot::store().
StartCompaction()
bool v8::internal::MarkCompactCollector::StartCompaction (StartCompactionMode mode)
Definition at line 331 of file mark-compact.cc.
                                                                   {
  DCHECK(!compacting_);
  DCHECK(evacuation_candidates_.empty());
  // Bailouts for completely disabled compaction.
  if (!v8_flags.compact ||
      (mode == StartCompactionMode::kAtomic && heap_->IsGCWithStack() &&
       !v8_flags.compact_with_stack) ||
      (v8_flags.gc_experiment_less_compaction &&
       !heap_->ShouldReduceMemory()) ||
      heap_->isolate()->serializer_enabled()) {
    return false;
  }
  CollectEvacuationCandidates(heap_->old_space());
  // Don't compact shared space when CSS is enabled, since there may be
  // DirectHandles on stacks of client isolates.
  if ((heap_->ConservativeStackScanningModeForMajorGC() !=
       Heap::StackScanMode::kFull) &&
      heap_->shared_space()) {
    CollectEvacuationCandidates(heap_->shared_space());
  }
  CollectEvacuationCandidates(heap_->trusted_space());
  if (heap_->isolate()->AllowsCodeCompaction() &&
      (!heap_->IsGCWithStack() || v8_flags.compact_code_space_with_stack)) {
    CollectEvacuationCandidates(heap_->code_space());
  } else if (v8_flags.trace_fragmentation) {
    TraceFragmentation(heap_->code_space());
  }
  compacting_ = !evacuation_candidates_.empty();
  return compacting_;
}
References v8::internal::Isolate::AllowsCodeCompaction(), v8::internal::Heap::code_space(), CollectEvacuationCandidates(), compacting_, v8::internal::Heap::ConservativeStackScanningModeForMajorGC(), v8::internal::DCHECK(), evacuation_candidates_, heap_, v8::internal::Heap::IsGCWithStack(), v8::internal::Heap::isolate(), kAtomic, v8::internal::Heap::kFull, mode(), v8::internal::Heap::old_space(), v8::internal::Isolate::serializer_enabled(), v8::internal::Heap::shared_space(), v8::internal::Heap::ShouldReduceMemory(), v8::internal::TraceFragmentation(), v8::internal::Heap::trusted_space(), and v8::internal::v8_flags.
Referenced by Prepare(), and v8::internal::IncrementalMarking::StartMarkingMajor().
StartMarking()
void v8::internal::MarkCompactCollector::StartMarking (std::shared_ptr<::heap::base::IncrementalMarkingSchedule > schedule = {})
Definition at line 406 of file mark-compact.cc.
                                                                {
  // The state for background thread is saved here and maintained for the whole
  // GC cycle. Both CppHeap and regular V8 heap will refer to this flag.
  use_background_threads_in_cycle_ = heap_->ShouldUseBackgroundThreads();
  if (v8_flags.sticky_mark_bits) {
    heap()->Unmark();
  }
#ifdef V8_COMPRESS_POINTERS
  heap_->young_external_pointer_space()->StartCompactingIfNeeded();
  heap_->old_external_pointer_space()->StartCompactingIfNeeded();
  heap_->cpp_heap_pointer_space()->StartCompactingIfNeeded();
#endif // V8_COMPRESS_POINTERS
  // CppHeap's marker must be initialized before the V8 marker to allow
  // exchanging of worklists.
  if (auto* cpp_heap = CppHeap::From(heap_->cpp_heap())) {
    TRACE_GC(heap()->tracer(), GCTracer::Scope::MC_MARK_EMBEDDER_PROLOGUE);
    cpp_heap->InitializeMarking(CppHeap::CollectionType::kMajor, schedule);
  }
  std::vector<Address> contexts =
      heap_->memory_measurement()->StartProcessing();
  if (v8_flags.stress_per_context_marking_worklist) {
    contexts.clear();
    HandleScope handle_scope(heap_->isolate());
    for (auto context : heap_->FindAllNativeContexts()) {
      contexts.push_back(context->ptr());
    }
  }
  heap_->tracer()->NotifyMarkingStart();
  code_flush_mode_ = GetCodeFlushMode(heap_->isolate());
  marking_worklists_.CreateContextWorklists(contexts);
  auto* cpp_heap = CppHeap::From(heap_->cpp_heap_);
  local_marking_worklists_ = std::make_unique<MarkingWorklists::Local>(
      &marking_worklists_,
      cpp_heap ? cpp_heap->CreateCppMarkingStateForMutatorThread()
               : MarkingWorklists::Local::kNoCppMarkingState);
  local_weak_objects_ = std::make_unique<WeakObjects::Local>(weak_objects());
  marking_visitor_ = std::make_unique<MainMarkingVisitor>(
      local_marking_worklists_.get(), local_weak_objects_.get(), heap_, epoch(),
      code_flush_mode(), heap_->ShouldCurrentGCKeepAgesUnchanged(),
      heap_->tracer()->CodeFlushingIncrease());
  // This method evicts SFIs with flushed bytecode from the cache before
  // iterating the compilation cache as part of the root set. SFIs that get
  // flushed in this GC cycle will get evicted out of the cache in the next GC
  // cycle. The SFI will remain in the cache until then and may remain in the
  // cache even longer in case the SFI is re-compiled.
  heap_->isolate()->compilation_cache()->MarkCompactPrologue();
  // Marking bits are cleared by the sweeper or unmarker (if sticky mark-bits
  // are enabled).
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) {
    VerifyMarkbitsAreClean();
  }
#endif // VERIFY_HEAP
}
References code_flush_mode(), code_flush_mode_, v8::internal::GCTracer::CodeFlushingIncrease(), v8::internal::Isolate::compilation_cache(), v8::internal::Heap::cpp_heap(), v8::internal::Heap::cpp_heap_, v8::internal::MarkingWorklists::CreateContextWorklists(), epoch(), v8::internal::Heap::FindAllNativeContexts(), v8::internal::CppHeap::From(), v8::internal::anonymous_namespace{mark-compact.cc}::GetCodeFlushMode(), heap(), heap_, v8::internal::Heap::isolate(), cppgc::internal::kMajor, local_marking_worklists_, local_weak_objects_, v8::internal::CompilationCache::MarkCompactPrologue(), marking_visitor_, marking_worklists_, v8::internal::Heap::memory_measurement(), v8::internal::GCTracer::NotifyMarkingStart(), v8::internal::Heap::ShouldCurrentGCKeepAgesUnchanged(), v8::internal::Heap::ShouldUseBackgroundThreads(), v8::internal::MemoryMeasurement::StartProcessing(), TRACE_GC, v8::internal::Heap::tracer(), v8::internal::Heap::Unmark(), use_background_threads_in_cycle_, v8::internal::v8_flags, and weak_objects().
Referenced by Prepare(), and v8::internal::IncrementalMarking::StartMarkingMajor().
StartSweepNewSpace()
void v8::internal::MarkCompactCollector::StartSweepNewSpace () [private]
Definition at line 6001 of file mark-compact.cc.
                                              {
  PagedSpaceForNewSpace* paged_space = heap_->paged_new_space()->paged_space();
  paged_space->ClearAllocatorState();
  int will_be_swept = 0;
  heap_->StartResizeNewSpace();
  DCHECK(empty_new_space_pages_to_be_swept_.empty());
  for (auto it = paged_space->begin(); it != paged_space->end();) {
    PageMetadata* p = *(it++);
    DCHECK(p->SweepingDone());
    DCHECK(!p->Chunk()->IsFlagSet(MemoryChunk::BLACK_ALLOCATED));
    if (p->live_bytes() > 0) {
      // Non-empty pages will be evacuated/promoted.
      continue;
    }
    if (paged_space->ShouldReleaseEmptyPage()) {
      ReleasePage(paged_space, p);
    } else {
      empty_new_space_pages_to_be_swept_.push_back(p);
    }
    will_be_swept++;
  }
  if (v8_flags.gc_verbose) {
    PrintIsolate(heap_->isolate(),
                 "sweeping: space=%s initialized_for_sweeping=%d",
                 ToString(paged_space->identity()), will_be_swept);
  }
}
References v8::internal::PagedSpaceBase::begin(), v8::internal::MemoryChunkMetadata::Chunk(), v8::internal::PagedSpaceBase::ClearAllocatorState(), DCHECK, v8::internal::PagedSpaceBase::end(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MutablePageMetadata::live_bytes(), v8::internal::PrintIsolate(), v8::internal::PagedSpaceForNewSpace::ShouldReleaseEmptyPage(), v8::internal::MutablePageMetadata::SweepingDone(), ToString(), and v8::internal::v8_flags.
StartSweepSpace()
void v8::internal::MarkCompactCollector::StartSweepSpace (PagedSpace * space) [private]
Definition at line 6050 of file mark-compact.cc.
                                                            {
  DCHECK_NE(NEW_SPACE, space->identity());
  space->ClearAllocatorState();
  int will_be_swept = 0;
  bool unused_page_present = false;
  Sweeper* sweeper = heap_->sweeper();
  // Loop needs to support deletion if live bytes == 0 for a page.
  for (auto it = space->begin(); it != space->end();) {
    PageMetadata* p = *(it++);
    DCHECK(p->SweepingDone());
    if (p->Chunk()->IsEvacuationCandidate()) {
      DCHECK(!p->Chunk()->IsFlagSet(MemoryChunk::BLACK_ALLOCATED));
      DCHECK_NE(NEW_SPACE, space->identity());
      // Will be processed in Evacuate.
      continue;
    }
    // If the page is black, just reset the flag and don't add the page to the
    // sweeper.
    if (p->Chunk()->IsFlagSet(MemoryChunk::BLACK_ALLOCATED)) {
      ResetAndRelinkBlackAllocatedPage(space, p);
      continue;
    }
    // One unused page is kept, all further are released before sweeping them.
    if (p->live_bytes() == 0) {
      if (unused_page_present) {
        if (v8_flags.gc_verbose) {
          PrintIsolate(heap_->isolate(), "sweeping: released page: %p",
                       static_cast<void*>(p));
        }
        ReleasePage(space, p);
        continue;
      }
      unused_page_present = true;
    }
    sweeper->AddPage(space->identity(), p);
    will_be_swept++;
  }
  if (v8_flags.sticky_mark_bits && space->identity() == OLD_SPACE) {
    static_cast<StickySpace*>(space)->set_old_objects_size(space->Size());
  }
  if (v8_flags.gc_verbose) {
    PrintIsolate(heap_->isolate(),
                 "sweeping: space=%s initialized_for_sweeping=%d",
                 ToString(space->identity()), will_be_swept);
  }
}
References v8::internal::Sweeper::AddPage(), v8::internal::MemoryChunkMetadata::Chunk(), DCHECK, DCHECK_NE, v8::internal::MemoryChunk::IsEvacuationCandidate(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MutablePageMetadata::live_bytes(), v8::internal::NEW_SPACE, v8::internal::OLD_SPACE, v8::internal::PrintIsolate(), space, v8::internal::MutablePageMetadata::SweepingDone(), ToString(), and v8::internal::v8_flags.
Sweep()
void v8::internal::MarkCompactCollector::Sweep () [private]
Definition at line 6162 of file mark-compact.cc.
                                 {
  DCHECK(!sweeper_->sweeping_in_progress());
  DCHECK(queued_pages_to_be_freed_.empty());
  sweeper_->InitializeMajorSweeping();
  TRACE_GC_EPOCH_WITH_FLOW(
      heap_->tracer(), GCTracer::Scope::MC_SWEEP, ThreadKind::kMain,
      sweeper_->GetTraceIdForFlowEvent(GCTracer::Scope::MC_SWEEP),
      TRACE_EVENT_FLAG_FLOW_OUT);
#ifdef DEBUG
  state_ = SWEEP_SPACES;
#endif
  {
    GCTracer::Scope sweep_scope(heap_->tracer(), GCTracer::Scope::MC_SWEEP_LO,
                                ThreadKind::kMain);
    SweepLargeSpace(heap_->lo_space());
  }
  {
    GCTracer::Scope sweep_scope(
        heap_->tracer(), GCTracer::Scope::MC_SWEEP_CODE_LO, ThreadKind::kMain);
    SweepLargeSpace(heap_->code_lo_space());
  }
  if (heap_->shared_space()) {
    GCTracer::Scope sweep_scope(heap_->tracer(),
                                GCTracer::Scope::MC_SWEEP_SHARED_LO,
                                ThreadKind::kMain);
    SweepLargeSpace(heap_->shared_lo_space());
  }
  {
    GCTracer::Scope sweep_scope(heap_->tracer(), GCTracer::Scope::MC_SWEEP_OLD,
                                ThreadKind::kMain);
    StartSweepSpace(heap_->old_space());
  }
  {
    GCTracer::Scope sweep_scope(heap_->tracer(), GCTracer::Scope::MC_SWEEP_CODE,
                                ThreadKind::kMain);
    StartSweepSpace(heap_->code_space());
  }
  if (heap_->shared_space()) {
    GCTracer::Scope sweep_scope(
        heap_->tracer(), GCTracer::Scope::MC_SWEEP_SHARED, ThreadKind::kMain);
    StartSweepSpace(heap_->shared_space());
  }
  {
    GCTracer::Scope sweep_scope(
        heap_->tracer(), GCTracer::Scope::MC_SWEEP_TRUSTED, ThreadKind::kMain);
    StartSweepSpace(heap_->trusted_space());
  }
  if (heap_->shared_trusted_space()) {
    GCTracer::Scope sweep_scope(
        heap_->tracer(), GCTracer::Scope::MC_SWEEP_SHARED, ThreadKind::kMain);
    StartSweepSpace(heap_->shared_trusted_space());
  }
  {
    GCTracer::Scope sweep_scope(heap_->tracer(),
                                GCTracer::Scope::MC_SWEEP_TRUSTED_LO,
                                ThreadKind::kMain);
    SweepLargeSpace(heap_->trusted_lo_space());
  }
  if (v8_flags.minor_ms && heap_->new_space()) {
    GCTracer::Scope sweep_scope(heap_->tracer(), GCTracer::Scope::MC_SWEEP_NEW,
                                ThreadKind::kMain);
    StartSweepNewSpace();
  }
  sweeper_->StartMajorSweeping();
}
References DCHECK, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC_EPOCH_WITH_FLOW, and v8::internal::v8_flags.
Referenced by CollectGarbage().
SweepArrayBufferExtensions()
void v8::internal::MarkCompactCollector::SweepArrayBufferExtensions () [private]
Definition at line 935 of file mark-compact.cc.
                                                      {
  DCHECK_IMPLIES(heap_->new_space(), heap_->new_space()->Size() == 0);
  DCHECK_IMPLIES(heap_->new_lo_space(), heap_->new_lo_space()->Size() == 0);
  heap_->array_buffer_sweeper()->RequestSweep(
      ArrayBufferSweeper::SweepingType::kFull,
      ArrayBufferSweeper::TreatAllYoungAsPromoted::kYes);
}
References v8::internal::Heap::array_buffer_sweeper(), DCHECK_IMPLIES, heap_, v8::internal::ArrayBufferSweeper::kFull, v8::internal::ArrayBufferSweeper::kYes, v8::internal::Heap::new_lo_space(), v8::internal::Heap::new_space(), v8::internal::ArrayBufferSweeper::RequestSweep(), and v8::internal::LargeObjectSpace::Size().
Referenced by Finish().
SweepLargeSpace()
void v8::internal::MarkCompactCollector::SweepLargeSpace (LargeObjectSpace * space) [private]
Definition at line 6120 of file mark-compact.cc.
                                                                  {
  PtrComprCageBase cage_base(heap_->isolate());
  size_t surviving_object_size = 0;
  const bool postpone_freeing = ShouldPostponeFreeingEmptyPages(space);
  const bool add_to_pool =
      v8_flags.large_page_pool && space->identity() == NEW_LO_SPACE;
  DCHECK_IMPLIES(add_to_pool, !postpone_freeing);
  std::vector<LargePageMetadata*> pages_to_pool;
  if (add_to_pool) {
    pages_to_pool.reserve(space->memory_chunk_list().size());
  }
  for (auto it = space->begin(); it != space->end();) {
    LargePageMetadata* current = *(it++);
    DCHECK(!current->Chunk()->IsFlagSet(MemoryChunk::BLACK_ALLOCATED));
    Tagged<HeapObject> object = current->GetObject();
    if (!marking_state_->IsMarked(object)) {
      // Object is dead and page can be released.
      space->RemovePage(current);
      if (postpone_freeing) {
        queued_pages_to_be_freed_.push_back(current);
      } else if (add_to_pool) {
        pages_to_pool.push_back(current);
      } else {
        heap_->memory_allocator()->Free(MemoryAllocator::FreeMode::kImmediately,
                                        current);
      }
      continue;
    }
    if (!v8_flags.sticky_mark_bits) {
      MarkBit::From(object).Clear();
      current->SetLiveBytes(0);
    }
    current->marking_progress_tracker().ResetIfEnabled();
    surviving_object_size += static_cast<size_t>(object->Size(cage_base));
  }
  space->set_objects_size(surviving_object_size);
  if (add_to_pool && !pages_to_pool.empty()) {
    heap()->memory_allocator()->FreeLargePagesPooled(std::move(pages_to_pool));
  }
}
References v8::internal::MemoryChunkMetadata::Chunk(), DCHECK, DCHECK_IMPLIES, v8::internal::LargePageMetadata::GetObject(), heap(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MutablePageMetadata::marking_progress_tracker(), v8::internal::NEW_LO_SPACE, v8::internal::MarkingProgressTracker::ResetIfEnabled(), v8::internal::MutablePageMetadata::SetLiveBytes(), v8::internal::anonymous_namespace{mark-compact.cc}::ShouldPostponeFreeingEmptyPages(), space, and v8::internal::v8_flags.
Referenced by Finish().
TearDown()
void v8::internal::MarkCompactCollector::TearDown ()
Definition at line 296 of file mark-compact.cc.
                                    {
  if (heap_->incremental_marking()->IsMajorMarking()) {
    local_marking_worklists_->Publish();
    heap_->main_thread_local_heap_->marking_barrier()->PublishIfNeeded();
    // Marking barriers of LocalHeaps will be published in their destructors.
    marking_worklists_.Clear();
    local_weak_objects()->Publish();
    weak_objects()->Clear();
  }
}
References v8::internal::MarkingWorklists::Clear(), v8::internal::WeakObjects::Clear(), heap_, v8::internal::Heap::incremental_marking(), v8::internal::IncrementalMarking::IsMajorMarking(), local_marking_worklists_, local_weak_objects(), v8::internal::Heap::main_thread_local_heap_, v8::internal::LocalHeap::marking_barrier(), marking_worklists_, v8::internal::WeakObjects::Local::Publish(), v8::internal::MarkingBarrier::PublishIfNeeded(), and weak_objects().
TransitionArrayNeedsCompaction()
bool v8::internal::MarkCompactCollector::TransitionArrayNeedsCompaction (Tagged< TransitionArray > transitions, int num_transitions) [private]
Definition at line 3618 of file mark-compact.cc.
                                                              {
  ReadOnlyRoots roots(heap_->isolate());
  for (int i = 0; i < num_transitions; ++i) {
    Tagged<MaybeObject> raw_target = transitions->GetRawTarget(i);
    if (raw_target.IsSmi()) {
      // This target is still being deserialized,
      DCHECK(heap_->isolate()->has_active_deserializer());
      DCHECK_EQ(raw_target.ToSmi(), Smi::uninitialized_deserialization_value());
#ifdef DEBUG
      // Targets can only be dead iff this array is fully deserialized.
      for (int j = 0; j < num_transitions; ++j) {
        DCHECK_IMPLIES(
            !transitions->GetRawTarget(j).IsSmi(),
            !non_atomic_marking_state_->IsUnmarked(transitions->GetTarget(j)));
      }
#endif
      return false;
    } else if (MarkingHelper::IsUnmarkedAndNotAlwaysLive(
                   heap_, non_atomic_marking_state_,
                   TransitionsAccessor::GetTargetFromRaw(raw_target))) {
#ifdef DEBUG
      // Targets can only be dead iff this array is fully deserialized.
      for (int j = 0; j < num_transitions; ++j) {
        DCHECK(!transitions->GetRawTarget(j).IsSmi());
      }
#endif
      return true;
    }
  }
  return false;
}
References DCHECK, DCHECK_EQ, DCHECK_IMPLIES, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::Tagged< HeapObject >::IsSmi(), and v8::internal::TaggedImpl< kRefType, StorageType >::ToSmi().
TrimDescriptorArray()
void v8::internal::MarkCompactCollector::TrimDescriptorArray (Tagged< Map > map, Tagged< DescriptorArray > descriptors) [private]
Definition at line 3769 of file mark-compact.cc.
                                                          {
  int number_of_own_descriptors = map->NumberOfOwnDescriptors();
  if (number_of_own_descriptors == 0) {
    DCHECK(descriptors == ReadOnlyRoots(heap_).empty_descriptor_array());
    return;
  }
  int to_trim =
      descriptors->number_of_all_descriptors() - number_of_own_descriptors;
  if (to_trim > 0) {
    descriptors->set_number_of_descriptors(number_of_own_descriptors);
    RightTrimDescriptorArray(descriptors, to_trim);
    TrimEnumCache(map, descriptors);
    descriptors->Sort();
  }
  DCHECK(descriptors->number_of_descriptors() == number_of_own_descriptors);
  map->set_owns_descriptors(true);
}
References DCHECK.
TrimEnumCache()
void v8::internal::MarkCompactCollector::TrimEnumCache (Tagged< Map > map, Tagged< DescriptorArray > descriptors) [private]
Definition at line 3789 of file mark-compact.cc.
                                                                              {
  int live_enum = map->EnumLength();
  if (live_enum == kInvalidEnumCacheSentinel) {
    live_enum = map->NumberOfEnumerableProperties();
  }
  if (live_enum == 0) return descriptors->ClearEnumCache();
  Tagged<EnumCache> enum_cache = descriptors->enum_cache();
  Tagged<FixedArray> keys = enum_cache->keys();
  int keys_length = keys->length();
  if (live_enum >= keys_length) return;
  heap_->RightTrimArray(keys, live_enum, keys_length);
  Tagged<FixedArray> indices = enum_cache->indices();
  int indices_length = indices->length();
  if (live_enum >= indices_length) return;
  heap_->RightTrimArray(indices, live_enum, indices_length);
}
References v8::internal::kInvalidEnumCacheSentinel.
UpdatePointersAfterEvacuation()
void v8::internal::MarkCompactCollector::UpdatePointersAfterEvacuation () [private]
Definition at line 5613 of file mark-compact.cc.
                                                         {
  TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_EVACUATE_UPDATE_POINTERS);
  {
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::MC_EVACUATE_UPDATE_POINTERS_TO_NEW_ROOTS);
    // The external string table is updated at the end.
    PointersUpdatingVisitor updating_visitor(heap_);
    heap_->IterateRootsIncludingClients(
        &updating_visitor,
        base::EnumSet<SkipRoot>{SkipRoot::kExternalStringTable,
                                SkipRoot::kConservativeStack,
                                SkipRoot::kReadOnlyBuiltins});
  }
  {
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::MC_EVACUATE_UPDATE_POINTERS_CLIENT_HEAPS);
    UpdatePointersInClientHeaps();
  }
  {
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::MC_EVACUATE_UPDATE_POINTERS_SLOTS_MAIN);
    std::vector<std::unique_ptr<UpdatingItem>> updating_items;
    CollectRememberedSetUpdatingItems(&updating_items, heap_->old_space());
    CollectRememberedSetUpdatingItems(&updating_items, heap_->code_space());
    if (heap_->shared_space()) {
      CollectRememberedSetUpdatingItems(&updating_items, heap_->shared_space());
    }
    CollectRememberedSetUpdatingItems(&updating_items, heap_->lo_space());
    CollectRememberedSetUpdatingItems(&updating_items, heap_->code_lo_space());
    if (heap_->shared_lo_space()) {
      CollectRememberedSetUpdatingItems(&updating_items,
                                        heap_->shared_lo_space());
    }
    CollectRememberedSetUpdatingItems(&updating_items, heap_->trusted_space());
    CollectRememberedSetUpdatingItems(&updating_items,
                                      heap_->trusted_lo_space());
    if (heap_->shared_trusted_space()) {
      CollectRememberedSetUpdatingItems(&updating_items,
                                        heap_->shared_trusted_space());
    }
    if (heap_->shared_trusted_lo_space()) {
      CollectRememberedSetUpdatingItems(&updating_items,
                                        heap_->shared_trusted_lo_space());
    }
    // Iterating to space may require a valid body descriptor for e.g.
    // WasmStruct which races with updating a slot in Map. Since to space is
    // empty after a full GC, such races can't happen.
    DCHECK_IMPLIES(heap_->new_space(), heap_->new_space()->Size() == 0);
    updating_items.push_back(
        std::make_unique<EphemeronTableUpdatingItem>(heap_));
    auto pointers_updating_job = std::make_unique<PointersUpdatingJob>(
        heap_->isolate(), this, std::move(updating_items));
    TRACE_GC_NOTE_WITH_FLOW("PointersUpdatingJob started",
                            pointers_updating_job->trace_id(),
                            TRACE_EVENT_FLAG_FLOW_OUT);
    V8::GetCurrentPlatform()
        ->CreateJob(v8::TaskPriority::kUserBlocking,
                    std::move(pointers_updating_job))
        ->Join();
  }
  {
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::MC_EVACUATE_UPDATE_POINTERS_WEAK);
    // Update pointers from external string table.
    heap_->UpdateReferencesInExternalStringTable(
        &UpdateReferenceInExternalStringTableEntry);
    // Update pointers in string forwarding table.
    // When GC was performed without a stack, the table was cleared and this
    // does nothing. In the case this was a GC with stack, we need to update
    // the entries for evacuated objects.
    // All entries are objects in shared space (unless
    // --always-use-forwarding-table), so we only need to update pointers during
    // a shared GC.
    if (heap_->isolate()->OwnsStringTables() ||
        V8_UNLIKELY(v8_flags.always_use_string_forwarding_table)) {
      heap_->isolate()->string_forwarding_table()->UpdateAfterFullEvacuation();
    }
    EvacuationWeakObjectRetainer evacuation_object_retainer;
    heap_->ProcessWeakListRoots(&evacuation_object_retainer);
  }
  {
    TRACE_GC(heap_->tracer(),
             GCTracer::Scope::MC_EVACUATE_UPDATE_POINTERS_POINTER_TABLES);
    UpdatePointersInPointerTables();
  }
  // Flush the inner_pointer_to_code_cache which may now have stale contents.
  heap_->isolate()->inner_pointer_to_code_cache()->Flush();
}
References v8::internal::anonymous_namespace{mark-compact.cc}::CollectRememberedSetUpdatingItems(), v8::Platform::CreateJob(), DCHECK_IMPLIES, v8::debug::GetCurrentPlatform(), v8::kUserBlocking, TRACE_EVENT_FLAG_FLOW_OUT, TRACE_GC, TRACE_GC_NOTE_WITH_FLOW, v8::internal::UpdateReferenceInExternalStringTableEntry(), v8::internal::v8_flags, and V8_UNLIKELY.
UpdatePointersInClientHeap()
void v8::internal::MarkCompactCollector::UpdatePointersInClientHeap (Isolate * client) [private]
Definition at line 5722 of file mark-compact.cc.
                                                                     {
  PtrComprCageBase cage_base(client);
  MemoryChunkIterator chunk_iterator(client->heap());
  while (chunk_iterator.HasNext()) {
    MutablePageMetadata* page = chunk_iterator.Next();
    MemoryChunk* chunk = page->Chunk();
    const auto slot_count = RememberedSet<OLD_TO_SHARED>::Iterate(
        page,
        [cage_base](MaybeObjectSlot slot) {
          return UpdateOldToSharedSlot(cage_base, slot);
        },
        SlotSet::FREE_EMPTY_BUCKETS);
    if (slot_count == 0 || chunk->InYoungGeneration()) {
      page->ReleaseSlotSet(OLD_TO_SHARED);
    }
    const PtrComprCageBase unused_cage_base(kNullAddress);
    const auto protected_slot_count =
        RememberedSet<TRUSTED_TO_SHARED_TRUSTED>::Iterate(
            page,
            [unused_cage_base](MaybeObjectSlot slot) {
              ProtectedPointerSlot protected_slot(slot.address());
              return UpdateOldToSharedSlot(unused_cage_base, protected_slot);
            },
            SlotSet::FREE_EMPTY_BUCKETS);
    if (protected_slot_count == 0) {
      page->ReleaseSlotSet(TRUSTED_TO_SHARED_TRUSTED);
    }
    if (!chunk->executable()) {
      DCHECK_NULL(page->typed_slot_set<OLD_TO_SHARED>());
      continue;
    }
    WritableJitPage jit_page = ThreadIsolation::LookupWritableJitPage(
        page->area_start(), page->area_size());
    const auto typed_slot_count = RememberedSet<OLD_TO_SHARED>::IterateTyped(
        page, [this, &jit_page](SlotType slot_type, Address slot) {
          // Using UpdateStrongSlot is OK here, because there are no weak
          // typed slots.
          PtrComprCageBase cage_base = heap_->isolate();
          WritableJitAllocation jit_allocation =
              jit_page.LookupAllocationContaining(slot);
          return UpdateTypedSlotHelper::UpdateTypedSlot(
              jit_allocation, heap_, slot_type, slot,
              [cage_base](FullMaybeObjectSlot slot) {
                return UpdateStrongOldToSharedSlot(cage_base, slot);
              });
        });
    if (typed_slot_count == 0 || chunk->InYoungGeneration())
      page->ReleaseTypedSlotSet(OLD_TO_SHARED);
  }
}
References v8::internal::SlotBase< Subclass, Data, SlotDataAlignment >::address(), v8::internal::MemoryChunkMetadata::area_size(), v8::internal::MemoryChunkMetadata::area_start(), v8::internal::MemoryChunkMetadata::Chunk(), DCHECK_NULL, v8::internal::MemoryChunk::executable(), v8::internal::MemoryChunkIterator::HasNext(), v8::internal::Isolate::heap(), v8::internal::MemoryChunk::InYoungGeneration(), v8::base::kNullAddress, v8::internal::WritableJitPage::LookupAllocationContaining(), v8::internal::MemoryChunkIterator::Next(), v8::internal::OLD_TO_SHARED, v8::internal::MutablePageMetadata::ReleaseSlotSet(), v8::internal::MutablePageMetadata::ReleaseTypedSlotSet(), v8::internal::TRUSTED_TO_SHARED_TRUSTED, v8::internal::MutablePageMetadata::typed_slot_set(), v8::internal::anonymous_namespace{mark-compact.cc}::UpdateOldToSharedSlot(), and v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongOldToSharedSlot().
UpdatePointersInClientHeaps()
void v8::internal::MarkCompactCollector::UpdatePointersInClientHeaps () [private]
Definition at line 5714 of file mark-compact.cc.
                                                       {
  Isolate* const isolate = heap_->isolate();
  if (!isolate->is_shared_space_isolate()) return;
  isolate->global_safepoint()->IterateClientIsolates(
      [this](Isolate* client) { UpdatePointersInClientHeap(client); });
}
References v8::internal::Isolate::global_safepoint(), v8::internal::Isolate::is_shared_space_isolate(), v8::internal::Factory::isolate(), and v8::internal::GlobalSafepoint::IterateClientIsolates().
UpdatePointersInPointerTables()
void v8::internal::MarkCompactCollector::UpdatePointersInPointerTables () [private]
Definition at line 5780 of file mark-compact.cc.
                                                         {
#if defined(V8_ENABLE_SANDBOX) || defined(V8_ENABLE_LEAPTIERING)
  // Process an entry of a pointer table, returning either the relocated object
  // or a null pointer if the object wasn't relocated.
  auto process_entry = [&](Address content) -> Tagged<ExposedTrustedObject> {
    Tagged<HeapObject> heap_obj = Cast<HeapObject>(Tagged<Object>(content));
    MapWord map_word = heap_obj->map_word(kRelaxedLoad);
    if (!map_word.IsForwardingAddress()) return {};
    Tagged<HeapObject> relocated_object =
        map_word.ToForwardingAddress(heap_obj);
    DCHECK(IsExposedTrustedObject(relocated_object));
    return Cast<ExposedTrustedObject>(relocated_object);
  };
#endif // defined(V8_ENABLE_SANDBOX) || defined(V8_ENABLE_LEAPTIERING)
#ifdef V8_ENABLE_SANDBOX
  TrustedPointerTable* const tpt = &heap_->isolate()->trusted_pointer_table();
  tpt->IterateActiveEntriesIn(
      heap_->trusted_pointer_space(),
      [&](TrustedPointerHandle handle, Address content) {
        Tagged<ExposedTrustedObject> relocated_object = process_entry(content);
        if (!relocated_object.is_null()) {
          DCHECK_EQ(handle, relocated_object->self_indirect_pointer_handle());
          auto instance_type = relocated_object->map()->instance_type();
          bool shared = HeapLayout::InAnySharedSpace(relocated_object);
          auto tag = IndirectPointerTagFromInstanceType(instance_type, shared);
          tpt->Set(handle, relocated_object.ptr(), tag);
        }
      });
  TrustedPointerTable* const stpt =
      &heap_->isolate()->shared_trusted_pointer_table();
  stpt->IterateActiveEntriesIn(
      heap_->isolate()->shared_trusted_pointer_space(),
      [&](TrustedPointerHandle handle, Address content) {
        Tagged<ExposedTrustedObject> relocated_object = process_entry(content);
        if (!relocated_object.is_null()) {
          DCHECK_EQ(handle, relocated_object->self_indirect_pointer_handle());
          auto instance_type = relocated_object->map()->instance_type();
          bool shared = HeapLayout::InAnySharedSpace(relocated_object);
          auto tag = IndirectPointerTagFromInstanceType(instance_type, shared);
          DCHECK(IsSharedTrustedPointerType(tag));
          stpt->Set(handle, relocated_object.ptr(), tag);
        }
      });
  CodePointerTable* const cpt = IsolateGroup::current()->code_pointer_table();
  cpt->IterateActiveEntriesIn(
      heap_->code_pointer_space(),
      [&](CodePointerHandle handle, Address content) {
        Tagged<ExposedTrustedObject> relocated_object = process_entry(content);
        if (!relocated_object.is_null()) {
          DCHECK_EQ(handle, relocated_object->self_indirect_pointer_handle());
          cpt->SetCodeObject(handle, relocated_object.address());
        }
      });
#endif // V8_ENABLE_SANDBOX
#ifdef V8_ENABLE_LEAPTIERING
  JSDispatchTable* const jdt = IsolateGroup::current()->js_dispatch_table();
  const EmbeddedData& embedded_data = EmbeddedData::FromBlob(heap_->isolate());
  jdt->IterateActiveEntriesIn(
      heap_->js_dispatch_table_space(), [&](JSDispatchHandle handle) {
        Address code_address = jdt->GetCodeAddress(handle);
        Address entrypoint_address = jdt->GetEntrypoint(handle);
        Tagged<TrustedObject> relocated_code = process_entry(code_address);
        bool code_object_was_relocated = !relocated_code.is_null();
        Tagged<Code> code = Cast<Code>(code_object_was_relocated
                                           ? relocated_code
                                           : Tagged<Object>(code_address));
        bool instruction_stream_was_relocated =
            code->instruction_start() != entrypoint_address;
        if (code_object_was_relocated || instruction_stream_was_relocated) {
          Address old_entrypoint = jdt->GetEntrypoint(handle);
          // Ensure tiering trampolines are not overwritten here.
          Address new_entrypoint = ([&]() {
#define CASE(name, ...) \
  if (old_entrypoint == embedded_data.InstructionStartOf(Builtin::k##name)) { \
    return old_entrypoint; \
  }
            BUILTIN_LIST_BASE_TIERING(CASE)
#undef CASE
            return code->instruction_start();
          })();
          jdt->SetCodeAndEntrypointNoWriteBarrier(handle, code, new_entrypoint);
          CHECK_IMPLIES(jdt->IsTieringRequested(handle),
                        old_entrypoint == new_entrypoint);
        }
      });
#endif // V8_ENABLE_LEAPTIERING
}
References DCHECK, v8::internal::handle(), v8::internal::MapWord::IsForwardingAddress(), v8::kRelaxedLoad, and v8::internal::MapWord::ToForwardingAddress().
UseBackgroundThreadsInCycle()
bool v8::internal::MarkCompactCollector::UseBackgroundThreadsInCycle () const [inline]
Definition at line 183 of file mark-compact.h.
                                           {
    return use_background_threads_in_cycle_;
  }
References use_background_threads_in_cycle_.
Referenced by v8::internal::ConcurrentMarking::Join(), v8::internal::ConcurrentMarking::RescheduleJobIfNeeded(), v8::internal::CppHeap::SelectMarkingType(), and v8::internal::ConcurrentMarking::TryScheduleJob().
VerifyEphemeronMarking()
void v8::internal::MarkCompactCollector::VerifyEphemeronMarking () [private]
Definition at line 2320 of file mark-compact.cc.
                                                  {
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) {
    Ephemeron ephemeron;
    // In the fixpoint iteration all unresolved ephemerons are in
    // `next_ephemerons_`.
    CHECK(
        local_weak_objects()->current_ephemerons_local.IsLocalAndGlobalEmpty());
    weak_objects_.current_ephemerons.Merge(weak_objects_.next_ephemerons);
    while (local_weak_objects()->current_ephemerons_local.Pop(&ephemeron)) {
      CHECK_NE(ApplyEphemeronSemantics(ephemeron.key, ephemeron.value),
               EphemeronResult::kMarkedValue);
    }
    // In the linear-time algorithm ephemerons are kept in `key_to_values_`.
    for (auto& [key, values] : key_to_values_) {
      for (auto value : values) {
        CHECK_NE(ApplyEphemeronSemantics(key, value),
                 EphemeronResult::kMarkedValue);
      }
    }
  }
#endif // VERIFY_HEAP
}
References CHECK, CHECK_NE, v8::internal::key, v8::internal::Ephemeron::key, v8::internal::v8_flags, v8::internal::Ephemeron::value, and v8::internal::value.
VerifyMarking()
void v8::internal::MarkCompactCollector::VerifyMarking ()
Definition at line 814 of file mark-compact.cc.
                                         {
  CHECK(local_marking_worklists_->IsEmpty());
  DCHECK(heap_->incremental_marking()->IsStopped());
#ifdef VERIFY_HEAP
  if (v8_flags.verify_heap) {
    TRACE_GC(heap_->tracer(), GCTracer::Scope::MC_MARK_VERIFY);
    FullMarkingVerifier verifier(heap_);
    verifier.Run();
    heap_->old_space()->VerifyLiveBytes();
    heap_->code_space()->VerifyLiveBytes();
    if (heap_->shared_space()) heap_->shared_space()->VerifyLiveBytes();
    heap_->trusted_space()->VerifyLiveBytes();
    if (v8_flags.minor_ms && heap_->paged_new_space())
      heap_->paged_new_space()->paged_space()->VerifyLiveBytes();
  }
#endif // VERIFY_HEAP
}
References CHECK, v8::internal::Heap::code_space(), v8::internal::DCHECK(), heap_, v8::internal::Heap::incremental_marking(), v8::internal::IncrementalMarking::IsStopped(), local_marking_worklists_, v8::internal::Heap::old_space(), v8::internal::Heap::paged_new_space(), v8::internal::PagedNewSpace::paged_space(), v8::internal::Heap::shared_space(), TRACE_GC, v8::internal::Heap::tracer(), v8::internal::Heap::trusted_space(), and v8::internal::v8_flags.
Referenced by CollectGarbage().
weak_objects()
WeakObjects* v8::internal::MarkCompactCollector::weak_objects () [inline]
Definition at line 180 of file mark-compact.h.
{ return &weak_objects_; }
References weak_objects_.
Referenced by StartMarking(), and TearDown().
WeakenStrongDescriptorArrays()
void v8::internal::MarkCompactCollector::WeakenStrongDescriptorArrays () [private]
Definition at line 3754 of file mark-compact.cc.
                                                        {
  Tagged<Map> descriptor_array_map =
      ReadOnlyRoots(heap_->isolate()).descriptor_array_map();
  for (auto& vec : strong_descriptor_arrays_) {
    for (auto it = vec.begin(); it != vec.end(); ++it) {
      Tagged<DescriptorArray> raw = it.raw();
      DCHECK(IsStrongDescriptorArray(raw));
      raw->set_map_safe_transition_no_write_barrier(heap_->isolate(),
                                                    descriptor_array_map);
      DCHECK_EQ(raw->raw_gc_state(kRelaxedLoad), 0);
    }
  }
  strong_descriptor_arrays_.clear();
}
References DCHECK, DCHECK_EQ, and v8::kRelaxedLoad.
Friends And Related Function Documentation
Evacuator
friend class Evacuator [friend]
Definition at line 477 of file mark-compact.h.
PrecisePagePinningVisitor
friend class PrecisePagePinningVisitor [friend]
Definition at line 480 of file mark-compact.h.
RecordMigratedSlotVisitor
friend class RecordMigratedSlotVisitor [friend]
Definition at line 478 of file mark-compact.h.
RootMarkingVisitor
friend class RootMarkingVisitor [friend]
Definition at line 479 of file mark-compact.h.
Member Data Documentation
aborted_evacuation_candidates_due_to_flags_
std::vector<PageMetadata*> v8::internal::MarkCompactCollector::aborted_evacuation_candidates_due_to_flags_ [private]
Definition at line 444 of file mark-compact.h.
aborted_evacuation_candidates_due_to_oom_
std::vector<std::pair<Address, PageMetadata*> > v8::internal::MarkCompactCollector::aborted_evacuation_candidates_due_to_oom_ [private]
Definition at line 443 of file mark-compact.h.
black_allocation_
bool v8::internal::MarkCompactCollector::black_allocation_ = false [private]
Definition at line 420 of file mark-compact.h.
code_flush_mode_
base::EnumSet<CodeFlushMode> v8::internal::MarkCompactCollector::code_flush_mode_ [private]
Definition at line 469 of file mark-compact.h.
Referenced by code_flush_mode(), and StartMarking().
compacting_
bool v8::internal::MarkCompactCollector::compacting_ = false [private]
Definition at line 419 of file mark-compact.h.
Referenced by is_compacting(), and StartCompaction().
empty_new_space_pages_to_be_swept_
std::vector<PageMetadata*> v8::internal::MarkCompactCollector::empty_new_space_pages_to_be_swept_ [private]
Definition at line 471 of file mark-compact.h.
Referenced by Finish().
epoch_
unsigned v8::internal::MarkCompactCollector::epoch_ = 0 [private]
Definition at line 463 of file mark-compact.h.
Referenced by epoch().
evacuation_candidates_
std::vector<PageMetadata*> v8::internal::MarkCompactCollector::evacuation_candidates_ [private]
Definition at line 438 of file mark-compact.h.
Referenced by AddEvacuationCandidate(), and StartCompaction().
have_code_to_deoptimize_
bool v8::internal::MarkCompactCollector::have_code_to_deoptimize_ = false [private]
Definition at line 421 of file mark-compact.h.
Referenced by Finish().
heap_
Heap* const v8::internal::MarkCompactCollector::heap_ [private]
Definition at line 396 of file mark-compact.h.
Referenced by AddEvacuationCandidate(), CollectEvacuationCandidates(), CollectGarbage(), ComputeEvacuationHeuristics(), Finish(), FinishConcurrentMarking(), heap(), MarkObject(), MarkObjectsFromClientHeaps(), MarkRootObject(), MarkRoots(), MarkRootsFromConservativeStack(), MaybeEnableBackgroundThreadsInCycle(), Prepare(), StartCompaction(), StartMarking(), SweepArrayBufferExtensions(), TearDown(), and VerifyMarking().
in_conservative_stack_scanning_
bool v8::internal::MarkCompactCollector::in_conservative_stack_scanning_ = false [private]
Definition at line 475 of file mark-compact.h.
Referenced by MarkRootObject(), and MarkRootsFromConservativeStack().
is_shared_space_isolate_
const bool v8::internal::MarkCompactCollector::is_shared_space_isolate_ [private]
Definition at line 415 of file mark-compact.h.
kEphemeronChunkSize
const int v8::internal::MarkCompactCollector::kEphemeronChunkSize = 8 * KB [static], [private]
Definition at line 384 of file mark-compact.h.
key_to_values_
KeyToValues v8::internal::MarkCompactCollector::key_to_values_ [private]
Definition at line 452 of file mark-compact.h.
Referenced by Finish().
local_marking_worklists_
std::unique_ptr<MarkingWorklists::Local> v8::internal::MarkCompactCollector::local_marking_worklists_ [private]
Definition at line 425 of file mark-compact.h.
Referenced by Finish(), local_marking_worklists(), MarkObject(), MarkRootObject(), StartMarking(), TearDown(), and VerifyMarking().
local_weak_objects_
std::unique_ptr<WeakObjects::Local> v8::internal::MarkCompactCollector::local_weak_objects_ [private]
Definition at line 430 of file mark-compact.h.
Referenced by Finish(), local_weak_objects(), and StartMarking().
marking_state_
MarkingState* const v8::internal::MarkCompactCollector::marking_state_ [private]
Definition at line 454 of file mark-compact.h.
Referenced by MarkObject(), and MarkRootObject().
marking_visitor_
std::unique_ptr<MainMarkingVisitor> v8::internal::MarkCompactCollector::marking_visitor_ [private]
Definition at line 429 of file mark-compact.h.
Referenced by Finish(), and StartMarking().
marking_worklists_
MarkingWorklists v8::internal::MarkCompactCollector::marking_worklists_ [private]
Definition at line 424 of file mark-compact.h.
Referenced by Finish(), marking_worklists(), StartMarking(), and TearDown().
mutex_
base::Mutex v8::internal::MarkCompactCollector::mutex_ [private]
Definition at line 398 of file mark-compact.h.
native_context_inferrer_
NativeContextInferrer v8::internal::MarkCompactCollector::native_context_inferrer_ [private]
Definition at line 431 of file mark-compact.h.
native_context_stats_
NativeContextStats v8::internal::MarkCompactCollector::native_context_stats_ [private]
Definition at line 432 of file mark-compact.h.
Referenced by CollectGarbage(), Finish(), and FinishConcurrentMarking().
new_space_evacuation_pages_
std::vector<PageMetadata*> v8::internal::MarkCompactCollector::new_space_evacuation_pages_ [private]
Definition at line 441 of file mark-compact.h.
non_atomic_marking_state_
NonAtomicMarkingState* const v8::internal::MarkCompactCollector::non_atomic_marking_state_ [private]
Definition at line 455 of file mark-compact.h.
old_space_evacuation_pages_
std::vector<PageMetadata*> v8::internal::MarkCompactCollector::old_space_evacuation_pages_ [private]
Definition at line 440 of file mark-compact.h.
page_parallel_job_semaphore_
base::Semaphore v8::internal::MarkCompactCollector::page_parallel_job_semaphore_ {0} [private]
Definition at line 399 of file mark-compact.h.
parallel_marking_
bool v8::internal::MarkCompactCollector::parallel_marking_ = false [private]
Definition at line 422 of file mark-compact.h.
promoted_large_pages_
std::vector<LargePageMetadata*> v8::internal::MarkCompactCollector::promoted_large_pages_ [private]
Definition at line 445 of file mark-compact.h.
queued_pages_to_be_freed_
std::vector<MutablePageMetadata*> v8::internal::MarkCompactCollector::queued_pages_to_be_freed_ [private]
Definition at line 449 of file mark-compact.h.
Referenced by Finish().
strong_descriptor_arrays_
std::vector<GlobalHandleVector<DescriptorArray> > v8::internal::MarkCompactCollector::strong_descriptor_arrays_ [private]
Definition at line 434 of file mark-compact.h.
strong_descriptor_arrays_mutex_
base::Mutex v8::internal::MarkCompactCollector::strong_descriptor_arrays_mutex_ [private]
Definition at line 435 of file mark-compact.h.
sweeper_
Sweeper* const v8::internal::MarkCompactCollector::sweeper_ [private]
Definition at line 456 of file mark-compact.h.
Referenced by CollectEvacuationCandidates(), Finish(), and Prepare().
use_background_threads_in_cycle_
bool v8::internal::MarkCompactCollector::use_background_threads_in_cycle_ = false [private]
Definition at line 473 of file mark-compact.h.
Referenced by MaybeEnableBackgroundThreadsInCycle(), StartMarking(), and UseBackgroundThreadsInCycle().
uses_shared_heap_
const bool v8::internal::MarkCompactCollector::uses_shared_heap_ [private]
Definition at line 414 of file mark-compact.h.
weak_objects_
WeakObjects v8::internal::MarkCompactCollector::weak_objects_ [private]
Definition at line 427 of file mark-compact.h.
Referenced by Finish(), and weak_objects().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/mark-compact.h
/mnt/V8SourceCode/src/heap/mark-compact-inl.h
/mnt/V8SourceCode/src/heap/mark-compact.cc