v8::internal::wasm::WasmInterpreterThread Class Reference
#include <wasm-interpreter.h>
Classes
class Activation
struct TrapStatus
Public Types
enum State {
STOPPED
, RUNNING
, FINISHED
, TRAPPED
,
EH_UNWINDING
 }
enum ExceptionHandlingResult { HANDLED
, UNWOUND
 }
Public Member Functions
WasmInterpreterThread (Isolate *isolate)
~WasmInterpreterThread ()
Handle< FixedArray > reference_stack () const
bool ExpandStack (size_t additional_required_size)
const Isolate * GetIsolate () const
State state () const
void Run ()
void Stop ()
void Trap (TrapReason trap_reason, int trap_function_index, int trap_pc, const FrameState &current_frame)
TrapReason GetTrapReason () const
void Unwinding ()
WasmInterpreterThread::Activation * StartActivation (WasmInterpreterRuntime *wasm_runtime, Address frame_pointer, uint8_t *interpreter_fp, const FrameState &frame_state)
void FinishActivation ()
const FrameState * GetCurrentActivationFor (const WasmInterpreterRuntime *wasm_runtime) const
void SetCurrentFrame (const FrameState &frame_state)
void SetCurrentActivationFrame (uint32_t *fp, uint32_t current_frame_size, uint32_t current_stack_size, uint32_t current_ref_stack_fp, uint32_t current_ref_stack_frame_size)
WasmInterpreterThread::Activation * GetActivation (Address frame_pointer) const
uint8_t * NextFrameAddress () const
uint32_t NextRefStackOffset () const
const uint8_t * StackLimitAddress () const
void EnsureRefStackSpace (size_t new_size)
void ClearRefStackValues (size_t index, size_t count)
void StartExecutionTimer ()
void StopExecutionTimer ()
void TerminateExecutionTimers ()
void RaiseException (Isolate *isolate, MessageTemplate message)
Static Public Member Functions
static void Initialize ()
static void Terminate ()
static void NotifyIsolateDisposal (Isolate *isolate)
static WasmInterpreterThread * GetCurrentInterpreterThread (Isolate *isolate)
static void SetRuntimeLastWasmError (Isolate *isolate, MessageTemplate message)
static TrapReason GetRuntimeLastWasmError (Isolate *isolate)
Private Member Functions
void Finish ()
uint8_t * stack_mem () const
Private Attributes
Isolate * isolate_
State state_
TrapReason trap_reason_
uint32_t current_stack_size_
void * stack_mem_
std::vector< std::unique_ptr< Activation > > activations_
Handle< FixedArray > reference_stack_
size_t current_ref_stack_size_
WasmExecutionTimer execution_timer_
Static Private Attributes
static WasmInterpreterThreadMap * thread_interpreter_map_s
static constexpr uint32_t kInitialStackSize = 1 * MB
static constexpr uint32_t kStackSizeIncrement = 1 * MB
static constexpr uint32_t kMaxStackSize = 32 * MB
Detailed Description
Definition at line 201 of file wasm-interpreter.h.
Member Enumeration Documentation
ExceptionHandlingResult
enum v8::internal::wasm::WasmInterpreterThread::ExceptionHandlingResult
Enumerator
HANDLED
UNWOUND
Definition at line 279 of file wasm-interpreter.h.
{ HANDLED, UNWOUND };
State
enum v8::internal::wasm::WasmInterpreterThread::State
Enumerator
STOPPED
RUNNING
FINISHED
TRAPPED
EH_UNWINDING
Definition at line 277 of file wasm-interpreter.h.
{ STOPPED, RUNNING, FINISHED, TRAPPED, EH_UNWINDING };
Constructor & Destructor Documentation
WasmInterpreterThread()
v8::internal::wasm::WasmInterpreterThread::WasmInterpreterThread (Isolate * isolate) [explicit]
Definition at line 441 of file wasm-interpreter.cc.
    : isolate_(isolate),
      state_(State::STOPPED),
      trap_reason_(TrapReason::kTrapUnreachable),
      current_stack_size_(kInitialStackSize),
      stack_mem_(nullptr),
      reference_stack_(isolate_->global_handles()->Create(
          ReadOnlyRoots(isolate_).empty_fixed_array())),
      current_ref_stack_size_(0),
      execution_timer_(isolate, true) {
  PageAllocator* page_allocator = GetPlatformPageAllocator();
  stack_mem_ = AllocatePages(page_allocator, kMaxStackSize,
                             page_allocator->AllocatePageSize(),
                             PageAllocator::kNoAccess);
  if (!stack_mem_ ||
      !SetPermissions(page_allocator, stack_mem_, current_stack_size_,
                      PageAllocator::Permission::kReadWrite)) {
    V8::FatalProcessOutOfMemory(nullptr,
                                "WasmInterpreterThread::WasmInterpreterThread",
                                "Cannot allocate Wasm interpreter stack");
    UNREACHABLE();
  }
}
References v8::internal::AllocatePages(), v8::PageAllocator::AllocatePageSize(), current_stack_size_, v8::internal::V8::FatalProcessOutOfMemory(), v8::internal::GetPlatformPageAllocator(), kMaxStackSize, v8::PageAllocator::kNoAccess, v8::internal::SetPermissions(), stack_mem_, and v8::internal::UNREACHABLE().
 WasmInterpreterThread()
v8::internal::wasm::WasmInterpreterThread::~WasmInterpreterThread ()
Definition at line 465 of file wasm-interpreter.cc.
                                              {
  GlobalHandles::Destroy(reference_stack_.location());
  FreePages(GetPlatformPageAllocator(), stack_mem_, kMaxStackSize);
}
References v8::internal::GlobalHandles::Destroy(), v8::internal::FreePages(), v8::internal::GetPlatformPageAllocator(), kMaxStackSize, reference_stack_, and stack_mem_.
Member Function Documentation
ClearRefStackValues()
void v8::internal::wasm::WasmInterpreterThread::ClearRefStackValues (size_t index, size_t count)
Definition at line 486 of file wasm-interpreter.cc.
                                                                          {
  reference_stack_->FillWithHoles(static_cast<int>(index),
                                  static_cast<int>(index + count));
}
References v8::internal::index, and reference_stack_.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), and v8::internal::wasm::WasmInterpreterRuntime::UnwindCurrentStackFrame().
EnsureRefStackSpace()
void v8::internal::wasm::WasmInterpreterThread::EnsureRefStackSpace (size_t new_size)
Definition at line 470 of file wasm-interpreter.cc.
                                                               {
  if (V8_LIKELY(current_ref_stack_size_ >= new_size)) return;
  size_t requested_size = base::bits::RoundUpToPowerOfTwo64(new_size);
  new_size = std::max(size_t{8},
                      std::max(2 * current_ref_stack_size_, requested_size));
  int grow_by = static_cast<int>(new_size - current_ref_stack_size_);
  HandleScope handle_scope(isolate_); // Avoid leaking handles.
  DirectHandle<FixedArray> new_ref_stack =
      isolate_->factory()->CopyFixedArrayAndGrow(reference_stack_, grow_by);
  new_ref_stack->FillWithHoles(static_cast<int>(current_ref_stack_size_),
                               static_cast<int>(new_size));
  isolate_->global_handles()->Destroy(reference_stack_.location());
  reference_stack_ = isolate_->global_handles()->Create(*new_ref_stack);
  current_ref_stack_size_ = new_size;
}
References v8::internal::Factory::CopyFixedArrayAndGrow(), v8::internal::GlobalHandles::Create(), current_ref_stack_size_, v8::internal::GlobalHandles::Destroy(), v8::internal::Isolate::factory(), v8::internal::Isolate::global_handles(), isolate_, reference_stack_, v8::base::bits::RoundUpToPowerOfTwo64(), and V8_LIKELY.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), and v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall().
ExpandStack()
bool v8::internal::wasm::WasmInterpreterThread::ExpandStack (size_t additional_required_size) [inline]
Definition at line 399 of file wasm-interpreter.h.
                                                    {
    if (current_stack_size_ + additional_required_size > kMaxStackSize) {
      return false;
    }
    uint32_t new_size = current_stack_size_;
    while (new_size < current_stack_size_ + additional_required_size) {
      new_size = std::min(new_size + kStackSizeIncrement, kMaxStackSize);
    }
    if (SetPermissions(GetPlatformPageAllocator(), stack_mem_, new_size,
                       PageAllocator::Permission::kReadWrite)) {
      current_stack_size_ = new_size;
      return true;
    }
    return false;
  }
References v8::internal::GetPlatformPageAllocator(), and v8::internal::SetPermissions().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution().
Finish()
void v8::internal::wasm::WasmInterpreterThread::Finish () [inline], [private]
Definition at line 546 of file wasm-interpreter.h.
{ state_ = State::FINISHED; }
FinishActivation()
void v8::internal::wasm::WasmInterpreterThread::FinishActivation () [inline]
Definition at line 64 of file wasm-interpreter-inl.h.
                                                    {
  DCHECK(!activations_.empty());
  activations_.pop_back();
  if (activations_.empty()) {
    if (state_ != State::TRAPPED && state_ != State::STOPPED) {
      Finish();
    }
  }
}
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution(), and v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution().
GetActivation()
WasmInterpreterThread::Activation* v8::internal::wasm::WasmInterpreterThread::GetActivation (Address frame_pointer) const [inline]
Definition at line 485 of file wasm-interpreter.h.
                                   {
    for (size_t i = 0; i < activations_.size(); i++) {
      if (activations_[i]->GetFramePointer() == frame_pointer) {
        return activations_[i].get();
      }
    }
    return nullptr;
  }
References v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::GetFunctionIndex(), and v8::internal::wasm::WasmInterpreterRuntime::GetInterpretedStack().
GetCurrentActivationFor()
const FrameState * v8::internal::wasm::WasmInterpreterThread::GetCurrentActivationFor (const WasmInterpreterRuntime * wasm_runtime) const [inline]
Definition at line 74 of file wasm-interpreter-inl.h.
                                                      {
  for (int i = static_cast<int>(activations_.size()) - 1; i >= 0; i--) {
    if (activations_[i]->GetWasmRuntime() == wasm_runtime) {
      return &activations_[i]->GetCurrentFrame();
    }
  }
  return nullptr;
}
References v8::internal::wasm::WasmInterpreter::GetWasmRuntime(), and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution().
GetCurrentInterpreterThread()
static WasmInterpreterThread* v8::internal::wasm::WasmInterpreterThread::GetCurrentInterpreterThread (Isolate * isolate) [inline], [static]
Definition at line 432 of file wasm-interpreter.h.
                                                                              {
    DCHECK_NOT_NULL(thread_interpreter_map_s);
    return thread_interpreter_map_s->GetCurrentInterpreterThread(isolate);
  }
References DCHECK_NOT_NULL.
Referenced by GetRuntimeLastWasmError(), v8::internal::WasmInterpreterObject::RunInterpreter(), and SetRuntimeLastWasmError().
GetIsolate()
const Isolate* v8::internal::wasm::WasmInterpreterThread::GetIsolate () const [inline]
Definition at line 437 of file wasm-interpreter.h.
{ return isolate_; }
Referenced by v8::internal::wasm::WasmInterpreterThreadMap::NotifyIsolateDisposal().
GetRuntimeLastWasmError()
TrapReason v8::internal::wasm::WasmInterpreterThread::GetRuntimeLastWasmError (Isolate * isolate) [static]
Definition at line 513 of file wasm-interpreter.cc.
                                                                          {
  WasmInterpreterThread* current_thread = GetCurrentInterpreterThread(isolate);
  // TODO(paolosev@microsoft.com): store in new data member?
  return current_thread->trap_reason_;
}
References GetCurrentInterpreterThread(), and trap_reason_.
Referenced by v8::internal::wasm::Handlers< Compressed >::s2s_AnyConvertExtern(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayCopy(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayInitSegment(), and v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewSegment().
GetTrapReason()
TrapReason v8::internal::wasm::WasmInterpreterThread::GetTrapReason () const [inline]
Definition at line 458 of file wasm-interpreter.h.
{ return trap_reason_; }
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution().
Initialize()
static void v8::internal::wasm::WasmInterpreterThread::Initialize () [inline], [static]
Definition at line 417 of file wasm-interpreter.h.
                           {
    // This function can be called multiple times by fuzzers.
    if (thread_interpreter_map_s) return;
    thread_interpreter_map_s = new WasmInterpreterThreadMap();
  }
Referenced by v8::internal::wasm::WasmInterpreter::InitializeOncePerProcess().
NextFrameAddress()
uint8_t* v8::internal::wasm::WasmInterpreterThread::NextFrameAddress () const [inline]
Definition at line 495 of file wasm-interpreter.h.
                                    {
    if (activations_.empty()) {
      return stack_mem();
    } else {
      return activations_.back()->NextFrameAddress();
    }
  }
Referenced by v8::internal::wasm::InterpreterHandle::Execute().
NextRefStackOffset()
uint32_t v8::internal::wasm::WasmInterpreterThread::NextRefStackOffset () const [inline]
Definition at line 503 of file wasm-interpreter.h.
                                      {
    if (activations_.empty()) {
      return 0;
    } else {
      return activations_.back()->NextRefStackOffset();
    }
  }
Referenced by v8::internal::wasm::WasmInterpreter::BeginExecution(), and v8::internal::wasm::InterpreterHandle::Execute().
NotifyIsolateDisposal()
static void v8::internal::wasm::WasmInterpreterThread::NotifyIsolateDisposal (Isolate * isolate) [inline], [static]
Definition at line 428 of file wasm-interpreter.h.
                                                      {
    thread_interpreter_map_s->NotifyIsolateDisposal(isolate);
  }
Referenced by v8::internal::wasm::WasmInterpreter::NotifyIsolateDisposal().
RaiseException()
void v8::internal::wasm::WasmInterpreterThread::RaiseException (Isolate * isolate, MessageTemplate message)
Definition at line 491 of file wasm-interpreter.cc.
                                                                    {
  DCHECK_EQ(WasmInterpreterThread::TRAPPED, state_);
  if (!isolate->has_exception()) {
    ClearThreadInWasmScope wasm_flag(isolate);
    DirectHandle<JSObject> error_obj =
        isolate->factory()->NewWasmRuntimeError(message);
    JSObject::AddProperty(isolate, error_obj,
                          isolate->factory()->wasm_uncatchable_symbol(),
                          isolate->factory()->true_value(), NONE);
    isolate->Throw(*error_obj);
  }
}
References v8::internal::JSObject::AddProperty(), DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::internal::NONE, state_, v8::internal::Isolate::Throw(), and TRAPPED.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution().
reference_stack()
Handle<FixedArray> v8::internal::wasm::WasmInterpreterThread::reference_stack () const [inline]
Definition at line 397 of file wasm-interpreter.h.
{ return reference_stack_; }
Referenced by v8::internal::wasm::WasmInterpreterRuntime::reference_stack().
Run()
void v8::internal::wasm::WasmInterpreterThread::Run () [inline]
Definition at line 441 of file wasm-interpreter.h.
             {
    if (!trap_handler::IsThreadInWasm()) {
      trap_handler::SetThreadInWasm();
    }
    state_ = State::RUNNING;
  }
References v8::internal::trap_handler::IsThreadInWasm(), and v8::internal::trap_handler::SetThreadInWasm().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallWasmToJSBuiltin(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteCallRef(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteImportedFunction(), and v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall().
SetCurrentActivationFrame()
void v8::internal::wasm::WasmInterpreterThread::SetCurrentActivationFrame (uint32_t * fp, uint32_t current_frame_size, uint32_t current_stack_size, uint32_t current_ref_stack_fp, uint32_t current_ref_stack_frame_size) [inline]
Definition at line 474 of file wasm-interpreter.h.
                                                                               {
    DCHECK(!activations_.empty());
    activations_.back()->SetCurrentActivationFrame(
        reinterpret_cast<uint8_t*>(fp), current_frame_size, current_stack_size,
        current_ref_stack_fp, current_ref_stack_frame_size);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ExecuteCallRef(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteImportedFunction(), and v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall().
SetCurrentFrame()
void v8::internal::wasm::WasmInterpreterThread::SetCurrentFrame (const FrameState & frame_state) [inline]
Definition at line 469 of file wasm-interpreter.h.
                                                             {
    DCHECK(!activations_.empty());
    activations_.back()->SetCurrentFrame(frame_state);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ExecuteCallRef(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteImportedFunction(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall(), v8::internal::wasm::WasmInterpreterRuntime::I32AtomicWait(), v8::internal::wasm::WasmInterpreterRuntime::I64AtomicWait(), v8::internal::wasm::WasmInterpreterRuntime::ThrowException(), v8::internal::wasm::WasmInterpreterRuntime::WasmArrayCopy(), v8::internal::wasm::WasmInterpreterRuntime::WasmArrayInitSegment(), v8::internal::wasm::WasmInterpreterRuntime::WasmArrayNewSegment(), v8::internal::wasm::WasmInterpreterRuntime::WasmJSToWasmObject(), and v8::internal::wasm::WasmInterpreterRuntime::WasmStackCheck().
SetRuntimeLastWasmError()
void v8::internal::wasm::WasmInterpreterThread::SetRuntimeLastWasmError (Isolate * isolate, MessageTemplate message) [static]
Definition at line 506 of file wasm-interpreter.cc.
                                                                             {
  WasmInterpreterThread* current_thread = GetCurrentInterpreterThread(isolate);
  current_thread->trap_reason_ = WasmOpcodes::MessageIdToTrapReason(message);
}
References GetCurrentInterpreterThread(), v8::internal::wasm::WasmOpcodes::MessageIdToTrapReason(), and trap_reason_.
stack_mem()
uint8_t* v8::internal::wasm::WasmInterpreterThread::stack_mem () const [inline], [private]
Definition at line 548 of file wasm-interpreter.h.
                                    {
    return reinterpret_cast<uint8_t*>(stack_mem_);
  }
StackLimitAddress()
const uint8_t* v8::internal::wasm::WasmInterpreterThread::StackLimitAddress () const [inline]
Definition at line 510 of file wasm-interpreter.h.
                                           {
    return stack_mem() + current_stack_size_;
  }
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution().
StartActivation()
WasmInterpreterThread::Activation * v8::internal::wasm::WasmInterpreterThread::StartActivation (WasmInterpreterRuntime * wasm_runtime, Address frame_pointer, uint8_t * interpreter_fp, const FrameState & frame_state) [inline]
Definition at line 54 of file wasm-interpreter-inl.h.
                                                                      {
  Run();
  activations_.emplace_back(std::make_unique<Activation>(
      this, wasm_runtime, frame_pointer, interpreter_fp, frame_state));
  return activations_.back().get();
}
Referenced by v8::internal::wasm::WasmInterpreterRuntime::BeginExecution().
StartExecutionTimer()
void v8::internal::wasm::WasmInterpreterThread::StartExecutionTimer ()
Definition at line 519 of file wasm-interpreter.cc.
                                                {
  if (v8_flags.wasm_enable_exec_time_histograms && v8_flags.slow_histograms) {
    execution_timer_.Start();
  }
}
References execution_timer_, v8::internal::wasm::WasmExecutionTimer::Start(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction(), and v8::internal::wasm::InterpreterHandle::Execute().
state()
State v8::internal::wasm::WasmInterpreterThread::state () const [inline]
Definition at line 439 of file wasm-interpreter.h.
{ return state_; }
Referenced by v8::internal::wasm::WasmInterpreter::ContinueExecution(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteImportedFunction(), v8::internal::wasm::InterpreterHandle::RunExecutionLoop(), and v8::internal::wasm::WasmInterpreterRuntime::state().
Stop()
void v8::internal::wasm::WasmInterpreterThread::Stop () [inline]
Definition at line 447 of file wasm-interpreter.h.
{ state_ = State::STOPPED; }
Referenced by v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteCallRef(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteImportedFunction(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall(), and v8::internal::wasm::InterpreterHandle::RunExecutionLoop().
StopExecutionTimer()
void v8::internal::wasm::WasmInterpreterThread::StopExecutionTimer ()
Definition at line 525 of file wasm-interpreter.cc.
                                               {
  if (v8_flags.wasm_enable_exec_time_histograms && v8_flags.slow_histograms) {
    execution_timer_.Stop();
  }
}
References execution_timer_, v8::internal::wasm::WasmExecutionTimer::Stop(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmInterpreterRuntime::CallExternalJSFunction(), and v8::internal::wasm::InterpreterHandle::Execute().
Terminate()
static void v8::internal::wasm::WasmInterpreterThread::Terminate () [inline], [static]
Definition at line 423 of file wasm-interpreter.h.
                          {
    delete thread_interpreter_map_s;
    thread_interpreter_map_s = nullptr;
  }
Referenced by v8::internal::wasm::WasmInterpreter::GlobalTearDown().
TerminateExecutionTimers()
void v8::internal::wasm::WasmInterpreterThread::TerminateExecutionTimers ()
Definition at line 531 of file wasm-interpreter.cc.
                                                     {
  if (v8_flags.wasm_enable_exec_time_histograms && v8_flags.slow_histograms) {
    execution_timer_.Terminate();
  }
}
References execution_timer_, v8::internal::wasm::WasmExecutionTimer::Terminate(), and v8::internal::v8_flags.
Referenced by v8::internal::wasm::WasmInterpreterThreadMap::NotifyIsolateDisposal().
Trap()
void v8::internal::wasm::WasmInterpreterThread::Trap (TrapReason trap_reason, int trap_function_index, int trap_pc, const FrameState & current_frame) [inline]
Definition at line 449 of file wasm-interpreter.h.
                                             {
    state_ = State::TRAPPED;
    trap_reason_ = trap_reason;
    DCHECK(!activations_.empty());
    activations_.back()->SetCurrentFrame(current_frame);
    activations_.back()->SetTrapped(trap_function_index, trap_pc);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::wasm::WasmInterpreterRuntime::SetTrap().
Unwinding()
void v8::internal::wasm::WasmInterpreterThread::Unwinding () [inline]
Definition at line 460 of file wasm-interpreter.h.
{ state_ = State::EH_UNWINDING; }
Referenced by v8::internal::wasm::WasmInterpreterRuntime::HandleException().
Member Data Documentation
activations_
std::vector<std::unique_ptr<Activation> > v8::internal::wasm::WasmInterpreterThread::activations_ [private]
Definition at line 564 of file wasm-interpreter.h.
current_ref_stack_size_
size_t v8::internal::wasm::WasmInterpreterThread::current_ref_stack_size_ [private]
Definition at line 579 of file wasm-interpreter.h.
Referenced by EnsureRefStackSpace().
current_stack_size_
uint32_t v8::internal::wasm::WasmInterpreterThread::current_stack_size_ [private]
Definition at line 561 of file wasm-interpreter.h.
Referenced by WasmInterpreterThread().
execution_timer_
WasmExecutionTimer v8::internal::wasm::WasmInterpreterThread::execution_timer_ [private]
Definition at line 581 of file wasm-interpreter.h.
Referenced by StartExecutionTimer(), StopExecutionTimer(), and TerminateExecutionTimers().
isolate_
Isolate* v8::internal::wasm::WasmInterpreterThread::isolate_ [private]
Definition at line 554 of file wasm-interpreter.h.
Referenced by EnsureRefStackSpace().
kInitialStackSize
constexpr uint32_t v8::internal::wasm::WasmInterpreterThread::kInitialStackSize = 1 * MB [static], [constexpr], [private]
Definition at line 558 of file wasm-interpreter.h.
kMaxStackSize
constexpr uint32_t v8::internal::wasm::WasmInterpreterThread::kMaxStackSize = 32 * MB [static], [constexpr], [private]
Definition at line 560 of file wasm-interpreter.h.
Referenced by WasmInterpreterThread(), and ~WasmInterpreterThread().
kStackSizeIncrement
constexpr uint32_t v8::internal::wasm::WasmInterpreterThread::kStackSizeIncrement = 1 * MB [static], [constexpr], [private]
Definition at line 559 of file wasm-interpreter.h.
reference_stack_
Handle<FixedArray> v8::internal::wasm::WasmInterpreterThread::reference_stack_ [private]
Definition at line 578 of file wasm-interpreter.h.
Referenced by ClearRefStackValues(), EnsureRefStackSpace(), and ~WasmInterpreterThread().
stack_mem_
void* v8::internal::wasm::WasmInterpreterThread::stack_mem_ [private]
Definition at line 562 of file wasm-interpreter.h.
Referenced by WasmInterpreterThread(), and ~WasmInterpreterThread().
state_
State v8::internal::wasm::WasmInterpreterThread::state_ [private]
Definition at line 555 of file wasm-interpreter.h.
Referenced by RaiseException().
thread_interpreter_map_s
WasmInterpreterThreadMap * v8::internal::wasm::WasmInterpreterThread::thread_interpreter_map_s [static], [private]
Initial value:
=
    nullptr
Definition at line 552 of file wasm-interpreter.h.
trap_reason_
TrapReason v8::internal::wasm::WasmInterpreterThread::trap_reason_ [private]
Definition at line 556 of file wasm-interpreter.h.
Referenced by GetRuntimeLastWasmError(), and SetRuntimeLastWasmError().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter-inl.h
/mnt/V8SourceCode/src/wasm/interpreter/wasm-interpreter.cc