v8::MicrotasksScope Class Reference
This scope is used to control microtasks when MicrotasksPolicy::kScoped is used on Isolate.
#include <v8-microtask-queue.h>
Public Types
enum Type { kRunMicrotasks
, kDoNotRunMicrotasks
 }
Public Member Functions
MicrotasksScope (Local< Context > context, Type type)
MicrotasksScope (Isolate *isolate, MicrotaskQueue *microtask_queue, Type type)
~MicrotasksScope ()
MicrotasksScope (const MicrotasksScope &)=delete
MicrotasksScope & operator= (const MicrotasksScope &)=delete
Static Public Member Functions
static void PerformCheckpoint (Isolate *isolate)
Runs microtasks if no kRunMicrotasks scope is currently active.
static int GetCurrentDepth (Isolate *isolate)
Returns current depth of nested kRunMicrotasks scopes.
static bool IsRunningMicrotasks (Isolate *isolate)
Returns true while microtasks are being executed.
Private Attributes
internal::Isolate *const i_isolate_
internal::MicrotaskQueue *const microtask_queue_
bool run_
Detailed Description
This scope is used to control microtasks when MicrotasksPolicy::kScoped is used on Isolate.
In this mode every non-primitive call to V8 should be done inside some MicrotasksScope. Microtasks are executed when topmost MicrotasksScope marked as kRunMicrotasks exits. kDoNotRunMicrotasks should be used to annotate calls not intended to trigger microtasks.
Definition at line 117 of file v8-microtask-queue.h.
Member Enumeration Documentation
Type
enum v8::MicrotasksScope::Type
Enumerator
kRunMicrotasks
kDoNotRunMicrotasks
Definition at line 119 of file v8-microtask-queue.h.
{ kRunMicrotasks, kDoNotRunMicrotasks };
Constructor & Destructor Documentation
MicrotasksScope() [1/3]
v8::MicrotasksScope::MicrotasksScope (Local< Context > context, MicrotasksScope::Type type)
Definition at line 10998 of file api.cc.
    : MicrotasksScope(v8::Isolate::GetCurrent(),
                      v8_context->GetMicrotaskQueue(), type) {}
MicrotasksScope() [2/3]
v8::MicrotasksScope::MicrotasksScope (Isolate * isolate, MicrotaskQueue * microtask_queue, MicrotasksScope::Type type)
Definition at line 11003 of file api.cc.
    : i_isolate_(reinterpret_cast<i::Isolate*>(v8_isolate)),
      microtask_queue_(microtask_queue
                           ? static_cast<i::MicrotaskQueue*>(microtask_queue)
                           : i_isolate_->default_microtask_queue()),
      run_(type == MicrotasksScope::kRunMicrotasks) {
  if (run_) microtask_queue_->IncrementMicrotasksScopeDepth();
#ifdef DEBUG
  if (!run_) microtask_queue_->IncrementDebugMicrotasksScopeDepth();
#endif
}
References v8::internal::MicrotaskQueue::IncrementMicrotasksScopeDepth(), microtask_queue_, and run_.
 MicrotasksScope()
v8::MicrotasksScope::~MicrotasksScope ()
Definition at line 11017 of file api.cc.
                                  {
  if (run_) {
    microtask_queue_->DecrementMicrotasksScopeDepth();
    if (MicrotasksPolicy::kScoped == microtask_queue_->microtasks_policy() &&
        !i_isolate_->has_exception()) {
      microtask_queue_->PerformCheckpoint(
          reinterpret_cast<Isolate*>(i_isolate_));
      DCHECK_IMPLIES(i_isolate_->has_exception(),
                     i_isolate_->is_execution_terminating());
    }
  }
#ifdef DEBUG
  if (!run_) microtask_queue_->DecrementDebugMicrotasksScopeDepth();
#endif
}
References DCHECK_IMPLIES, v8::internal::MicrotaskQueue::DecrementMicrotasksScopeDepth(), v8::internal::Isolate::has_exception(), i_isolate_, v8::internal::Isolate::is_execution_terminating(), v8::kScoped, microtask_queue_, v8::internal::MicrotaskQueue::microtasks_policy(), v8::internal::MicrotaskQueue::PerformCheckpoint(), and run_.
MicrotasksScope() [3/3]
v8::MicrotasksScope::MicrotasksScope (const MicrotasksScope &) [delete]
Member Function Documentation
GetCurrentDepth()
int v8::MicrotasksScope::GetCurrentDepth (Isolate * isolate) [static]
Returns current depth of nested kRunMicrotasks scopes.
Definition at line 11041 of file api.cc.
                                                        {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  auto* microtask_queue = i_isolate->default_microtask_queue();
  return microtask_queue->GetMicrotasksScopeDepth();
}
IsRunningMicrotasks()
bool v8::MicrotasksScope::IsRunningMicrotasks (Isolate * isolate) [static]
Returns true while microtasks are being executed.
Definition at line 11048 of file api.cc.
                                                             {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  auto* microtask_queue = i_isolate->default_microtask_queue();
  return microtask_queue->IsRunningMicrotasks();
}
operator=()
MicrotasksScope& v8::MicrotasksScope::operator= (const MicrotasksScope &) [delete]
PerformCheckpoint()
void v8::MicrotasksScope::PerformCheckpoint (Isolate * isolate) [static]
Runs microtasks if no kRunMicrotasks scope is currently active.
Definition at line 11034 of file api.cc.
                                                           {
  i::Isolate* i_isolate = reinterpret_cast<i::Isolate*>(v8_isolate);
  auto* microtask_queue = i_isolate->default_microtask_queue();
  microtask_queue->PerformCheckpoint(v8_isolate);
}
Referenced by v8::Worker::ProcessMessages(), v8::anonymous_namespace{d8.cc}::ProcessMessages(), and v8::internal::RUNTIME_FUNCTION().
Member Data Documentation
i_isolate_
internal::Isolate* const v8::MicrotasksScope::i_isolate_ [private]
Definition at line 145 of file v8-microtask-queue.h.
Referenced by ~MicrotasksScope().
microtask_queue_
internal::MicrotaskQueue* const v8::MicrotasksScope::microtask_queue_ [private]
Definition at line 146 of file v8-microtask-queue.h.
Referenced by MicrotasksScope(), and ~MicrotasksScope().
run_
bool v8::MicrotasksScope::run_ [private]
Definition at line 147 of file v8-microtask-queue.h.
Referenced by MicrotasksScope(), and ~MicrotasksScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-microtask-queue.h
/mnt/V8SourceCode/src/api/api.cc