v8::internal::compiler::InstructionScheduler::ScheduleGraphNode Class Reference
Public Member Functions
ScheduleGraphNode (Zone *zone, Instruction *instr)
void AddSuccessor (ScheduleGraphNode *node)
bool HasUnscheduledPredecessor ()
void DropUnscheduledPredecessor ()
Instruction * instruction ()
ZoneDeque< ScheduleGraphNode * > & successors ()
int latency () const
int total_latency () const
void set_total_latency (int latency)
int start_cycle () const
void set_start_cycle (int start_cycle)
Private Attributes
Instruction * instr_
ZoneDeque< ScheduleGraphNode * > successors_
int unscheduled_predecessors_count_
int latency_
int total_latency_
int start_cycle_
Detailed Description
Definition at line 51 of file instruction-scheduler.h.
Constructor & Destructor Documentation
ScheduleGraphNode()
v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::ScheduleGraphNode (Zone * zone, Instruction * instr)
Definition at line 62 of file instruction-scheduler.cc.
    : instr_(instr),
      successors_(zone),
      unscheduled_predecessors_count_(0),
      latency_(GetInstructionLatency(instr)),
      total_latency_(-1),
      start_cycle_(-1) {}
Member Function Documentation
AddSuccessor()
void v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::AddSuccessor (ScheduleGraphNode * node)
Definition at line 71 of file instruction-scheduler.cc.
                             {
  successors_.push_back(node);
  node->unscheduled_predecessors_count_++;
}
References unscheduled_predecessors_count_.
Referenced by v8::internal::compiler::InstructionScheduler::AddInstruction(), and v8::internal::compiler::InstructionScheduler::AddTerminator().
DropUnscheduledPredecessor()
void v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::DropUnscheduledPredecessor () [inline]
Definition at line 66 of file instruction-scheduler.h.
                                      {
      DCHECK_LT(0, unscheduled_predecessors_count_);
      unscheduled_predecessors_count_--;
    }
References DCHECK_LT, and unscheduled_predecessors_count_.
HasUnscheduledPredecessor()
bool v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::HasUnscheduledPredecessor () [inline]
Definition at line 61 of file instruction-scheduler.h.
                                     {
      return unscheduled_predecessors_count_ != 0;
    }
References unscheduled_predecessors_count_.
instruction()
Instruction* v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::instruction () [inline]
Definition at line 71 of file instruction-scheduler.h.
{ return instr_; }
References instr_.
Referenced by v8::internal::compiler::InstructionScheduler::Schedule().
latency()
int v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::latency () const [inline]
Definition at line 73 of file instruction-scheduler.h.
{ return latency_; }
References latency_.
Referenced by v8::internal::compiler::InstructionScheduler::Schedule(), and set_total_latency().
set_start_cycle()
void v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::set_start_cycle (int start_cycle) [inline]
Definition at line 79 of file instruction-scheduler.h.
{ start_cycle_ = start_cycle; }
References start_cycle(), and start_cycle_.
set_total_latency()
void v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::set_total_latency (int latency) [inline]
Definition at line 76 of file instruction-scheduler.h.
{ total_latency_ = latency; }
References latency(), and total_latency_.
start_cycle()
int v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::start_cycle () const [inline]
Definition at line 78 of file instruction-scheduler.h.
{ return start_cycle_; }
References start_cycle_.
Referenced by set_start_cycle().
successors()
ZoneDeque<ScheduleGraphNode*>& v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::successors () [inline]
Definition at line 72 of file instruction-scheduler.h.
{ return successors_; }
References successors_.
Referenced by v8::internal::compiler::InstructionScheduler::ComputeTotalLatencies(), and v8::internal::compiler::InstructionScheduler::Schedule().
total_latency()
int v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::total_latency () const [inline]
Definition at line 75 of file instruction-scheduler.h.
{ return total_latency_; }
References total_latency_.
Referenced by v8::internal::compiler::InstructionScheduler::SchedulingQueueBase::AddNode().
Member Data Documentation
instr_
Instruction* v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::instr_ [private]
Definition at line 82 of file instruction-scheduler.h.
Referenced by instruction().
latency_
int v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::latency_ [private]
Definition at line 90 of file instruction-scheduler.h.
Referenced by latency().
start_cycle_
int v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::start_cycle_ [private]
Definition at line 100 of file instruction-scheduler.h.
Referenced by set_start_cycle(), and start_cycle().
successors_
ZoneDeque<ScheduleGraphNode*> v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::successors_ [private]
Definition at line 83 of file instruction-scheduler.h.
Referenced by successors().
total_latency_
int v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::total_latency_ [private]
Definition at line 94 of file instruction-scheduler.h.
Referenced by set_total_latency(), and total_latency().
unscheduled_predecessors_count_
int v8::internal::compiler::InstructionScheduler::ScheduleGraphNode::unscheduled_predecessors_count_ [private]
Definition at line 86 of file instruction-scheduler.h.
Referenced by AddSuccessor(), DropUnscheduledPredecessor(), and HasUnscheduledPredecessor().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction-scheduler.h
/mnt/V8SourceCode/src/compiler/backend/instruction-scheduler.cc