v8::internal::PrecisePagePinningVisitor Class Reference
Public Member Functions
PrecisePagePinningVisitor (MarkCompactCollector *collector)
void VisitRootPointer (Root root, const char *description, FullObjectSlot p) final
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) final
Private Member Functions
void HandlePointer (FullObjectSlot p)
Private Attributes
MarkCompactCollector *const collector_
const bool should_pin_in_shared_space_
Additional Inherited Members
Detailed Description
Definition at line 4853 of file mark-compact.cc.
Constructor & Destructor Documentation
PrecisePagePinningVisitor()
v8::internal::PrecisePagePinningVisitor::PrecisePagePinningVisitor (MarkCompactCollector * collector) [inline], [explicit]
Definition at line 4855 of file mark-compact.cc.
      : RootVisitor(),
        collector_(collector),
        should_pin_in_shared_space_(
            collector->heap()->isolate()->is_shared_space_isolate()) {}
Member Function Documentation
HandlePointer()
void v8::internal::PrecisePagePinningVisitor::HandlePointer (FullObjectSlot p) [inline], [private]
Definition at line 4874 of file mark-compact.cc.
                                       {
    Tagged<Object> object = *p;
    if (!object.IsHeapObject()) {
      return;
    }
    MemoryChunk* chunk = MemoryChunk::FromHeapObject(Cast<HeapObject>(object));
    if (chunk->IsLargePage() || chunk->InReadOnlySpace()) {
      // Large objects and read only objects are not evacuated and thus don't
      // need to be pinned.
      return;
    }
    if (!should_pin_in_shared_space_ && chunk->InWritableSharedSpace()) {
      return;
    }
    if (chunk->InYoungGeneration()) {
      // Young gen pages are not considered evacuation candidates. Pinning is
      // done by marking them as quarantined and promoting the page as is.
      DCHECK(v8_flags.minor_ms ? chunk->IsToPage() : chunk->IsFromPage());
      if (chunk->IsQuarantined()) {
        return;
      }
      chunk->SetFlagNonExecutable(MemoryChunk::IS_QUARANTINED);
      return;
    }
    if (!chunk->IsFlagSet(MemoryChunk::EVACUATION_CANDIDATE)) {
      return;
    }
    collector_->ReportAbortedEvacuationCandidateDueToFlags(
        PageMetadata::cast(chunk->Metadata()), chunk);
  }
References DCHECK, v8::internal::MemoryChunk::InReadOnlySpace(), v8::internal::MemoryChunk::InWritableSharedSpace(), v8::internal::MemoryChunk::InYoungGeneration(), v8::internal::MemoryChunk::IsFlagSet(), v8::internal::MemoryChunk::IsFromPage(), v8::internal::InstanceTypeChecker::IsHeapObject(), v8::internal::MemoryChunk::IsLargePage(), v8::internal::MemoryChunk::IsQuarantined(), v8::internal::MemoryChunk::IsToPage(), v8::internal::MemoryChunk::Metadata(), v8::internal::MemoryChunk::SetFlagNonExecutable(), and v8::internal::v8_flags.
VisitRootPointer()
void v8::internal::PrecisePagePinningVisitor::VisitRootPointer (Root root, const char * description, FullObjectSlot p) [inline], [final], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 4861 of file mark-compact.cc.
                                                {
    HandlePointer(p);
  }
VisitRootPointers()
void v8::internal::PrecisePagePinningVisitor::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 4866 of file mark-compact.cc.
                                                                         {
    for (FullObjectSlot p = start; p < end; ++p) {
      HandlePointer(p);
    }
  }
References v8::internal::compiler::end().
Member Data Documentation
collector_
MarkCompactCollector* const v8::internal::PrecisePagePinningVisitor::collector_ [private]
Definition at line 4905 of file mark-compact.cc.
should_pin_in_shared_space_
const bool v8::internal::PrecisePagePinningVisitor::should_pin_in_shared_space_ [private]
Definition at line 4906 of file mark-compact.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc