v8::internal::CallInterfaceDescriptor Class Reference
#include <interface-descriptors.h>
Inherited by v8::internal::StaticCallInterfaceDescriptor< RegExpTrampolineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallForwardVarargsDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallApiCallbackGenericDescriptor >, v8::internal::StaticCallInterfaceDescriptor< BinaryOp_WithFeedbackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< WasmFloat32ToNumberDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ResumeGeneratorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< NewHeapNumberDescriptor >, v8::internal::StaticCallInterfaceDescriptor< MaglevOptimizeCodeOrTailCallOptimizedCodeSlotDescriptor >, v8::internal::StaticCallInterfaceDescriptor< LoadWithReceiverAndVectorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< DefineKeyedOwnBaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ConstructForwardAllArgs_BaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CompareDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CloneObjectBaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallTrampoline_Baseline_CompactDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallTrampolineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< AsyncFunctionStackParameterDescriptor >, v8::internal::StaticCallInterfaceDescriptor< AddStringConstantInternalizeTrampolineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< StoreBaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< KeyedHasICBaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< GetIteratorStackParameterDescriptor >, v8::internal::StaticCallInterfaceDescriptor< EnumeratedKeyedLoadDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ConstructWithSpread_BaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< Compare_WithFeedbackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CheckTurboshaftFloat32TypeDescriptor >, v8::internal::StaticCallInterfaceDescriptor< BaselineLeaveFrameDescriptor >, v8::internal::StaticCallInterfaceDescriptor< StringAtAsStringDescriptor >, v8::internal::StaticCallInterfaceDescriptor< StoreWithVectorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< LoadGlobalBaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< DefineKeyedOwnWithVectorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ConstructWithArrayLikeDescriptor >, v8::internal::StaticCallInterfaceDescriptor< StoreGlobalWithVectorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< NoContextDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallApiCallbackOptimizedDescriptor >, v8::internal::StaticCallInterfaceDescriptor< BigIntToI32PairDescriptor >, v8::internal::StaticCallInterfaceDescriptor< WasmSuspendDescriptor >, v8::internal::StaticCallInterfaceDescriptor< WasmFloat64ToTaggedDescriptor >, v8::internal::StaticCallInterfaceDescriptor< WasmDummyDescriptor >, v8::internal::StaticCallInterfaceDescriptor< RestartFrameTrampolineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< InterpreterPushArgsThenCallDescriptor >, v8::internal::StaticCallInterfaceDescriptor< I32PairToBigIntDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CreateFromSlowBoilerplateHelperDescriptor >, v8::internal::StaticCallInterfaceDescriptor< Compare_BaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< BaselineOutOfLinePrologueDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ApiGetterDescriptor >, v8::internal::StaticCallInterfaceDescriptor< TypeConversion_BaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< StoreDescriptor >, v8::internal::StaticCallInterfaceDescriptor< Descriptor >, v8::internal::StaticCallInterfaceDescriptor< RunMicrotasksDescriptor >, v8::internal::StaticCallInterfaceDescriptor< LoadNoFeedbackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< IndirectPointerWriteBarrierDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CloneObjectWithVectorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallWithSpread_WithFeedbackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< VoidDescriptor >, v8::internal::StaticCallInterfaceDescriptor< StoreGlobalBaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< LoadWithReceiverBaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< FastNewObjectDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CopyDataPropertiesWithExcludedPropertiesOnStackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ConstructStubDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ConstructForwardAllArgsDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CompareNoContextDescriptor >, v8::internal::StaticCallInterfaceDescriptor< LookupBaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< EnumeratedKeyedLoadBaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ConstructWithSpread_WithFeedbackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< BinaryOpDescriptor >, v8::internal::StaticCallInterfaceDescriptor< TypeofDescriptor >, v8::internal::StaticCallInterfaceDescriptor< TypeConversionDescriptor >, v8::internal::StaticCallInterfaceDescriptor< SuspendGeneratorBaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< StringSubstringDescriptor >, v8::internal::StaticCallInterfaceDescriptor< StoreTransitionDescriptor >, v8::internal::StaticCallInterfaceDescriptor< OnStackReplacementDescriptor >, v8::internal::StaticCallInterfaceDescriptor< LoadGlobalWithVectorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< I64ToBigIntDescriptor >, v8::internal::StaticCallInterfaceDescriptor< DebugPrintWordPtrDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ConstructWithSpreadDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallTrampoline_BaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CEntry1ArgvOnStackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ArrayNArgumentsConstructorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< UnaryOp_BaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< StoreGlobalDescriptor >, v8::internal::StaticCallInterfaceDescriptor< DebugPrintFloat64Descriptor >, v8::internal::StaticCallInterfaceDescriptor< CallVarargsDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CEntryDummyDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ArraySingleArgumentConstructorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< UnaryOp_WithFeedbackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< RunMicrotasksEntryDescriptor >, v8::internal::StaticCallInterfaceDescriptor< LookupWithVectorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< InterpreterCEntry1Descriptor >, v8::internal::StaticCallInterfaceDescriptor< GetPropertyDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CopyDataPropertiesWithExcludedPropertiesDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CheckTurboshaftFloat64TypeDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallWithSpreadDescriptor >, v8::internal::StaticCallInterfaceDescriptor< BinarySmiOp_BaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ForInPrepareDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallTrampoline_WithFeedbackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ResumeGeneratorBaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< InterpreterPushArgsThenConstructDescriptor >, v8::internal::StaticCallInterfaceDescriptor< InterpreterDispatchDescriptor >, v8::internal::StaticCallInterfaceDescriptor< GrowArrayElementsDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ContextOnlyDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallWithArrayLikeDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallFunctionTemplateDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CCallDescriptor >, v8::internal::StaticCallInterfaceDescriptor< BinaryOp_BaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< WasmToJSWrapperDescriptor >, v8::internal::StaticCallInterfaceDescriptor< LookupTrampolineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< LoadDescriptor >, v8::internal::StaticCallInterfaceDescriptor< LoadBaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< KeyedLoadWithVectorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< KeyedLoadDescriptor >, v8::internal::StaticCallInterfaceDescriptor< JSEntryDescriptor >, v8::internal::StaticCallInterfaceDescriptor< InterpreterCEntry2Descriptor >, v8::internal::StaticCallInterfaceDescriptor< FindNonDefaultConstructorOrConstructDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallWithSpread_BaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallWithArrayLike_WithFeedbackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< AllocateDescriptor >, v8::internal::StaticCallInterfaceDescriptor< WriteBarrierDescriptor >, v8::internal::StaticCallInterfaceDescriptor< WasmHandleStackOverflowDescriptor >, v8::internal::StaticCallInterfaceDescriptor< LoadGlobalNoFeedbackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< KeyedHasICWithVectorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< DefineKeyedOwnDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ConstructForwardVarargsDescriptor >, v8::internal::StaticCallInterfaceDescriptor< BigIntToI64Descriptor >, v8::internal::StaticCallInterfaceDescriptor< AddStringConstantInternalizeWithVectorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< AbortDescriptor >, v8::internal::StaticCallInterfaceDescriptor< WasmJSToWasmWrapperDescriptor >, v8::internal::StaticCallInterfaceDescriptor< TypeConversionNoContextDescriptor >, v8::internal::StaticCallInterfaceDescriptor< StringEqualDescriptor >, v8::internal::StaticCallInterfaceDescriptor< StoreNoFeedbackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< SingleParameterOnStackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< LoadWithVectorDescriptor >, v8::internal::StaticCallInterfaceDescriptor< LoadGlobalDescriptor >, v8::internal::StaticCallInterfaceDescriptor< KeyedLoadBaselineDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ConstructVarargsDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ConstructForwardAllArgs_WithFeedbackDescriptor >, v8::internal::StaticCallInterfaceDescriptor< CallFunctionTemplateGenericDescriptor >, v8::internal::StaticCallInterfaceDescriptor< ArrayNoArgumentConstructorDescriptor >, and v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >.
Public Types
using Flags = CallInterfaceDescriptorData::Flags
Public Member Functions
CallInterfaceDescriptor ()
~CallInterfaceDescriptor ()=default
CallInterfaceDescriptor (CallDescriptors::Key key)
Flags flags () const
CodeEntrypointTag tag () const
CodeSandboxingMode sandboxing_mode () const
bool HasContextParameter () const
bool AllowVarArgs () const
bool CalleeSaveRegisters () const
int GetReturnCount () const
MachineType GetReturnType (int index) const
int GetParameterCount () const
int GetRegisterParameterCount () const
int GetStackParameterCount () const
Register GetRegisterParameter (int index) const
DoubleRegister GetDoubleRegisterParameter (int index) const
Register GetRegisterReturn (int index) const
DoubleRegister GetDoubleRegisterReturn (int index) const
MachineType GetParameterType (int index) const
RegList allocatable_registers () const
StackArgumentOrder GetStackArgumentOrder () const
const char * DebugName () const
bool operator== (const CallInterfaceDescriptor &other) const
Static Public Member Functions
static constexpr Register ContextRegister ()
Protected Member Functions
const CallInterfaceDescriptorData * data () const
bool CheckFloatingPointParameters (CallInterfaceDescriptorData *data)
bool IsValidFloatParameterRegister (Register reg)
Static Protected Member Functions
static constexpr auto DefaultRegisterArray ()
static constexpr auto DefaultDoubleRegisterArray ()
static constexpr auto DefaultReturnRegisterArray ()
static constexpr auto DefaultReturnDoubleRegisterArray ()
static constexpr std::array< Register, kJSBuiltinRegisterParams > DefaultJSRegisterArray ()
Private Attributes
const CallInterfaceDescriptorData * data_
Detailed Description
Definition at line 361 of file interface-descriptors.h.
Member Typedef Documentation
Flags
using v8::internal::CallInterfaceDescriptor::Flags = CallInterfaceDescriptorData::Flags
Definition at line 363 of file interface-descriptors.h.
Constructor & Destructor Documentation
CallInterfaceDescriptor() [1/2]
v8::internal::CallInterfaceDescriptor::CallInterfaceDescriptor () [inline]
Definition at line 365 of file interface-descriptors.h.
: data_(nullptr) {}
 CallInterfaceDescriptor()
v8::internal::CallInterfaceDescriptor::~CallInterfaceDescriptor () [default]
CallInterfaceDescriptor() [2/2]
v8::internal::CallInterfaceDescriptor::CallInterfaceDescriptor (CallDescriptors::Key key) [inline], [explicit]
Definition at line 368 of file interface-descriptors.h.
      : data_(CallDescriptors::call_descriptor_data(key)) {}
Member Function Documentation
allocatable_registers()
RegList v8::internal::CallInterfaceDescriptor::allocatable_registers () const [inline]
Definition at line 433 of file interface-descriptors.h.
                                        {
    return data()->allocatable_registers();
  }
Referenced by v8::internal::compiler::Linkage::GetStubCallDescriptor().
AllowVarArgs()
bool v8::internal::CallInterfaceDescriptor::AllowVarArgs () const [inline]
Definition at line 383 of file interface-descriptors.h.
                            {
    return flags() & CallInterfaceDescriptorData::kAllowVarArgs;
  }
References v8::internal::flags, and v8::internal::CallInterfaceDescriptorData::kAllowVarArgs.
CalleeSaveRegisters()
bool v8::internal::CallInterfaceDescriptor::CalleeSaveRegisters () const [inline]
Definition at line 387 of file interface-descriptors.h.
                                   {
    return flags() & CallInterfaceDescriptorData::kCalleeSaveRegisters;
  }
References v8::internal::flags, and v8::internal::CallInterfaceDescriptorData::kCalleeSaveRegisters.
Referenced by v8::internal::compiler::Linkage::GetStubCallDescriptor().
CheckFloatingPointParameters()
bool v8::internal::CallInterfaceDescriptor::CheckFloatingPointParameters (CallInterfaceDescriptorData * data) [inline], [protected]
Definition at line 466 of file interface-descriptors.h.
                                                                       {
    for (int i = 0; i < data->register_param_count(); i++) {
      if (IsFloatingPoint(data->param_type(i).representation())) {
        if (!IsValidFloatParameterRegister(data->register_param(i))) {
          return false;
        }
      }
    }
    return true;
  }
References v8::internal::IsFloatingPoint(), v8::internal::CallInterfaceDescriptorData::param_type(), v8::internal::CallInterfaceDescriptorData::register_param(), v8::internal::CallInterfaceDescriptorData::register_param_count(), and v8::internal::MachineType::representation().
ContextRegister()
static constexpr Register v8::internal::CallInterfaceDescriptor::ContextRegister () [inline], [static], [constexpr]
Definition at line 441 of file interface-descriptors.h.
                                                     {
    return kContextRegister;
  }
References v8::internal::kContextRegister.
data()
const CallInterfaceDescriptorData* v8::internal::CallInterfaceDescriptor::data () const [inline], [protected]
Definition at line 452 of file interface-descriptors.h.
{ return data_; }
Referenced by v8::internal::compiler::CodeAssembler::CallJSStubImpl(), v8::internal::compiler::CodeAssembler::CallStubRImpl(), v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::InitializeTypes(), and operator==().
DebugName()
const char * v8::internal::CallInterfaceDescriptor::DebugName () const
Definition at line 132 of file interface-descriptors.cc.
                                                     {
  CallDescriptors::Key key = CallDescriptors::GetKey(data_);
  switch (key) {
#define DEF_CASE(name, ...) \
  case CallDescriptors::name: \
    return #name " Descriptor";
    INTERFACE_DESCRIPTOR_LIST(DEF_CASE)
#undef DEF_CASE
    case CallDescriptors::NUMBER_OF_DESCRIPTORS:
      break;
  }
  return "";
}
References data_, DEF_CASE, v8::internal::CallDescriptors::GetKey(), INTERFACE_DESCRIPTOR_LIST, v8::internal::key, and v8::internal::CallDescriptors::NUMBER_OF_DESCRIPTORS.
Referenced by v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), and v8::internal::compiler::Linkage::GetStubCallDescriptor().
DefaultDoubleRegisterArray()
constexpr auto v8::internal::CallInterfaceDescriptor::DefaultDoubleRegisterArray () [inline], [static], [constexpr], [protected]
Definition at line 21 of file interface-descriptors-riscv-inl.h.
                                                                   {
  auto registers = DoubleRegisterArray(ft1, ft2, ft3, ft4, ft5, ft6, ft7);
  return registers;
}
References v8::internal::DoubleRegisterArray().
Referenced by v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::double_registers(), and v8::internal::WasmToJSWrapperDescriptor::return_double_registers().
DefaultJSRegisterArray()
constexpr std::array< Register, kJSBuiltinRegisterParams > v8::internal::CallInterfaceDescriptor::DefaultJSRegisterArray () [inline], [static], [constexpr], [protected]
Definition at line 46 of file interface-descriptors-inl.h.
                                                {
  return RegisterArray(
      kJavaScriptCallTargetRegister, kJavaScriptCallNewTargetRegister,
      kJavaScriptCallArgCountRegister, kJavaScriptCallExtraArg1Register);
}
References v8::internal::kJavaScriptCallArgCountRegister, v8::internal::kJavaScriptCallExtraArg1Register, v8::internal::kJavaScriptCallNewTargetRegister, v8::internal::kJavaScriptCallTargetRegister, and v8::internal::RegisterArray().
Referenced by v8::internal::StaticJSCallInterfaceDescriptor< Descriptor >::registers().
DefaultRegisterArray()
constexpr auto v8::internal::CallInterfaceDescriptor::DefaultRegisterArray () [inline], [static], [constexpr], [protected]
Definition at line 15 of file interface-descriptors-riscv-inl.h.
                                                             {
  auto registers = RegisterArray(a0, a1, a2, a3, a4);
  static_assert(registers.size() == kMaxBuiltinRegisterParams);
  return registers;
}
References v8::internal::kMaxBuiltinRegisterParams, and v8::internal::RegisterArray().
Referenced by v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::registers(), v8::internal::MaglevOptimizeCodeOrTailCallOptimizedCodeSlotDescriptor::registers(), v8::internal::BaselineLeaveFrameDescriptor::registers(), and v8::internal::WasmToJSWrapperDescriptor::return_registers().
DefaultReturnDoubleRegisterArray()
constexpr auto v8::internal::CallInterfaceDescriptor::DefaultReturnDoubleRegisterArray () [inline], [static], [constexpr], [protected]
Definition at line 32 of file interface-descriptors-riscv-inl.h.
                                                                         {
  // Padding to have as many double return registers as GP return registers.
  auto registers = DoubleRegisterArray(kFPReturnRegister0, no_dreg, no_dreg);
  return registers;
}
References v8::internal::DoubleRegisterArray(), v8::internal::kFPReturnRegister0, and v8::internal::no_dreg.
Referenced by v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::return_double_registers().
DefaultReturnRegisterArray()
constexpr auto v8::internal::CallInterfaceDescriptor::DefaultReturnRegisterArray () [inline], [static], [constexpr], [protected]
Definition at line 26 of file interface-descriptors-riscv-inl.h.
                                                                   {
  auto registers =
      RegisterArray(kReturnRegister0, kReturnRegister1, kReturnRegister2);
  return registers;
}
References v8::internal::kReturnRegister0, v8::internal::kReturnRegister1, v8::internal::kReturnRegister2, and v8::internal::RegisterArray().
Referenced by v8::internal::StaticCallInterfaceDescriptor< DerivedDescriptor >::return_registers().
flags()
Flags v8::internal::CallInterfaceDescriptor::flags () const [inline]
Definition at line 371 of file interface-descriptors.h.
{ return data()->flags(); }
GetDoubleRegisterParameter()
DoubleRegister v8::internal::CallInterfaceDescriptor::GetDoubleRegisterParameter (int index) const [inline]
Definition at line 413 of file interface-descriptors.h.
                                                             {
    DCHECK_LT(index, data()->register_param_count());
    return data()->double_register_param(index);
  }
References DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::compiler::Linkage::GetStubCallDescriptor().
GetDoubleRegisterReturn()
DoubleRegister v8::internal::CallInterfaceDescriptor::GetDoubleRegisterReturn (int index) const [inline]
Definition at line 423 of file interface-descriptors.h.
                                                          {
    DCHECK_LT(index, data()->return_count());
    return data()->double_register_return(index);
  }
References DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::compiler::Linkage::GetStubCallDescriptor().
GetParameterCount()
int v8::internal::CallInterfaceDescriptor::GetParameterCount () const [inline]
Definition at line 398 of file interface-descriptors.h.
{ return data()->param_count(); }
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), v8::internal::compiler::CodeAssembler::TailCallBytecodeDispatch(), and v8::internal::interpreter::BytecodeHandlerReducer< Next >::TailCallBytecodeDispatch().
GetParameterType()
MachineType v8::internal::CallInterfaceDescriptor::GetParameterType (int index) const [inline]
Definition at line 428 of file interface-descriptors.h.
                                                {
    DCHECK_LT(index, data()->param_count());
    return data()->param_type(index);
  }
References DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), and v8::internal::compiler::Linkage::GetStubCallDescriptor().
GetRegisterParameter()
Register v8::internal::CallInterfaceDescriptor::GetRegisterParameter (int index) const [inline]
Definition at line 408 of file interface-descriptors.h.
                                                 {
    DCHECK_LT(index, data()->register_param_count());
    return data()->register_param(index);
  }
References DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::maglev::MaglevAssembler::CallBuiltin(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), and v8::internal::compiler::Linkage::GetStubCallDescriptor().
GetRegisterParameterCount()
int v8::internal::CallInterfaceDescriptor::GetRegisterParameterCount () const [inline]
Definition at line 400 of file interface-descriptors.h.
                                        {
    return data()->register_param_count();
  }
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevFrameTranslationBuilder::BuildSingleDeoptFrame(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithTurboshaftAssemblerCS(), v8::internal::BuiltinContinuationFrameInfo::BuiltinContinuationFrameInfo(), v8::internal::maglev::MaglevAssembler::CallBuiltin(), v8::internal::compiler::CodeAssembler::CallStubN(), v8::internal::compiler::CreateStubBuiltinContinuationFrameState(), v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::Pipeline::NewCSLinkageCodeStubBuiltinCompilationJob(), and v8::internal::compiler::CodeAssembler::TailCallStubThenBytecodeDispatchImpl().
GetRegisterReturn()
Register v8::internal::CallInterfaceDescriptor::GetRegisterReturn (int index) const [inline]
Definition at line 418 of file interface-descriptors.h.
                                              {
    DCHECK_LT(index, data()->return_count());
    return data()->register_return(index);
  }
References DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::compiler::Linkage::GetStubCallDescriptor().
GetReturnCount()
int v8::internal::CallInterfaceDescriptor::GetReturnCount () const [inline]
Definition at line 391 of file interface-descriptors.h.
{ return data()->return_count(); }
Referenced by v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), and v8::internal::compiler::Linkage::GetStubCallDescriptor().
GetReturnType()
MachineType v8::internal::CallInterfaceDescriptor::GetReturnType (int index) const [inline]
Definition at line 393 of file interface-descriptors.h.
                                             {
    DCHECK_LT(index, data()->return_count());
    return data()->return_type(index);
  }
References DCHECK_LT, and v8::internal::index.
Referenced by v8::internal::compiler::Linkage::GetBytecodeDispatchCallDescriptor(), and v8::internal::compiler::Linkage::GetStubCallDescriptor().
GetStackArgumentOrder()
StackArgumentOrder v8::internal::CallInterfaceDescriptor::GetStackArgumentOrder () const [inline]
Definition at line 437 of file interface-descriptors.h.
                                                   {
    return data()->stack_order();
  }
Referenced by v8::internal::Deoptimizer::DoComputeBuiltinContinuation(), and v8::internal::compiler::Linkage::GetStubCallDescriptor().
GetStackParameterCount()
int v8::internal::CallInterfaceDescriptor::GetStackParameterCount () const [inline]
Definition at line 404 of file interface-descriptors.h.
                                     {
    return data()->param_count() - data()->register_param_count();
  }
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithTurboshaftAssemblerCS(), v8::internal::compiler::JSCallReducerAssembler::Call4(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::CallBuiltin(), v8::internal::compiler::turboshaft::MachineLoweringReducer< Next >::CallBuiltinForBigIntOp(), v8::internal::compiler::CodeAssembler::CallStubN(), v8::internal::compiler::turboshaft::BuiltinCallDescriptor::Descriptor< Derived >::Create(), v8::internal::compiler::CreateStubBuiltinContinuationFrameState(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::GenerateBuiltinCall(), v8::internal::wasm::anonymous_namespace{wrappers.cc}::GetBuiltinCallDescriptor(), v8::internal::compiler::GetBuiltinCallDescriptor(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::Pipeline::NewCSLinkageCodeStubBuiltinCompilationJob(), v8::internal::compiler::JSGraphAssembler::PlainPrimitiveToNumberOperator(), v8::internal::compiler::anonymous_namespace{js-native-context-specialization.cc}::PushRegularApiCallInputs(), v8::internal::compiler::JSCallReducer::ReduceArrayPrototypeSlice(), v8::internal::compiler::JSCallReducer::ReduceCollectionIteratorPrototypeNext(), v8::internal::compiler::JSTypedLowering::ReduceJSAdd(), v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), v8::internal::compiler::JSTypedLowering::ReduceJSToObject(), v8::internal::compiler::JSNativeContextSpecialization::ReduceMegaDOMPropertyAccess(), v8::internal::compiler::JSCallReducer::ReduceReflectGet(), v8::internal::compiler::CodeAssembler::TailCallBytecodeDispatch(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::TailCallBytecodeDispatch(), v8::internal::compiler::CodeAssembler::TailCallStubImpl(), v8::internal::compiler::CodeAssembler::TailCallStubThenBytecodeDispatchImpl(), v8::internal::compiler::SimplifiedLowering::ToNumberConvertBigIntOperator(), v8::internal::compiler::SimplifiedLowering::ToNumberOperator(), and v8::internal::compiler::SimplifiedLowering::ToNumericOperator().
HasContextParameter()
bool v8::internal::CallInterfaceDescriptor::HasContextParameter () const [inline]
Definition at line 379 of file interface-descriptors.h.
                                   {
    return (flags() & CallInterfaceDescriptorData::kNoContext) == 0;
  }
References v8::internal::flags, and v8::internal::CallInterfaceDescriptorData::kNoContext.
Referenced by v8::internal::compiler::CodeAssembler::CallJSStubImpl(), v8::internal::compiler::CodeAssembler::CallStubN(), v8::internal::compiler::CodeAssembler::CallStubRImpl(), v8::internal::compiler::Linkage::GetStubCallDescriptor(), v8::internal::compiler::FastApiCallReducerAssembler::ReduceFastApiCall(), and v8::internal::compiler::CodeAssembler::TailCallStubImpl().
IsValidFloatParameterRegister()
bool v8::internal::CallInterfaceDescriptor::IsValidFloatParameterRegister (Register reg) [protected]
Definition at line 146 of file interface-descriptors.cc.
                                                                        {
#if defined(V8_TARGET_ARCH_MIPS64)
  return reg.code() % 2 == 0;
#else
  return true;
#endif
}
References v8::internal::RegisterBase< SubType, kAfterLastRegister >::code().
operator==()
bool v8::internal::CallInterfaceDescriptor::operator== (const CallInterfaceDescriptor & other) const [inline]
Definition at line 447 of file interface-descriptors.h.
                                                              {
    return data() == other.data();
  }
References data().
sandboxing_mode()
CodeSandboxingMode v8::internal::CallInterfaceDescriptor::sandboxing_mode () const [inline]
Definition at line 375 of file interface-descriptors.h.
                                             {
    return data()->sandboxing_mode();
  }
Referenced by v8::internal::Builtins::SandboxingModeOf().
tag()
CodeEntrypointTag v8::internal::CallInterfaceDescriptor::tag () const [inline]
Definition at line 373 of file interface-descriptors.h.
{ return data()->tag(); }
Referenced by v8::internal::Builtins::EntrypointTagFor(), and v8::internal::compiler::Linkage::GetStubCallDescriptor().
Member Data Documentation
data_
const CallInterfaceDescriptorData* v8::internal::CallInterfaceDescriptor::data_ [private]
Definition at line 480 of file interface-descriptors.h.
Referenced by DebugName().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/interface-descriptors.h
/mnt/V8SourceCode/src/codegen/interface-descriptors-inl.h
/mnt/V8SourceCode/src/codegen/interface-descriptors.cc
/mnt/V8SourceCode/src/codegen/riscv/interface-descriptors-riscv-inl.h