v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits > Class Template Reference
Static Public Member Functions
static void ConvertArgumentsStoreResult (DirectHandle< SloppyArgumentsElements > elements, DirectHandle< Object > result)
static Handle< Object > GetImpl (Isolate *isolate, Tagged< FixedArrayBase > parameters, InternalIndex entry)
static void TransitionElementsKindImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Map > map)
static Maybe< bool > GrowCapacityAndConvertImpl (Isolate *isolate, DirectHandle< JSObject > object, uint32_t capacity)
static void SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value)
static void SetImpl (Tagged< FixedArrayBase > store, InternalIndex entry, Tagged< Object > value)
static Maybe< bool > SetLengthImpl (Isolate *isolate, DirectHandle< JSArray > array, uint32_t length, DirectHandle< FixedArrayBase > parameter_map)
static uint32_t GetCapacityImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > store)
static uint32_t GetMaxNumberOfEntries (Isolate *isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store)
static uint32_t NumberOfElementsImpl (Isolate *isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > backing_store)
static V8_WARN_UNUSED_RESULT ExceptionStatus AddElementsToKeyAccumulatorImpl (DirectHandle< JSObject > receiver, KeyAccumulator *accumulator, AddKeyConversion convert)
static bool HasEntryImpl (Isolate *isolate, Tagged< FixedArrayBase > parameters, InternalIndex entry)
static bool HasAccessorsImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store)
static InternalIndex GetEntryForIndexImpl (Isolate *isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > parameters, size_t index, PropertyFilter filter)
static PropertyDetails GetDetailsImpl (Tagged< JSObject > holder, InternalIndex entry)
static bool HasParameterMapArg (Isolate *isolate, Tagged< SloppyArgumentsElements > elements, size_t index)
static void DeleteImpl (Isolate *isolate, DirectHandle< JSObject > obj, InternalIndex entry)
static void SloppyDeleteImpl (Isolate *isolate, DirectHandle< JSObject > obj, DirectHandle< SloppyArgumentsElements > elements, InternalIndex entry)
static V8_WARN_UNUSED_RESULT ExceptionStatus CollectElementIndicesImpl (DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, KeyAccumulator *keys)
static Handle< FixedArray > DirectCollectElementIndicesImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, GetKeysConversion convert, PropertyFilter filter, Handle< FixedArray > list, uint32_t *nof_indices, uint32_t insertion_index=0)
static Maybe< bool > IncludesValueImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Object > value, size_t start_from, size_t length)
static Maybe< int64_t > IndexOfValueImpl (Isolate *isolate, DirectHandle< JSObject > object, DirectHandle< Object > value, size_t start_from, size_t length)
Additional Inherited Members
Detailed Description
template<typename Subclass, typename ArgumentsAccessor, typename KindTraits>
class v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >
Definition at line 4870 of file elements.cc.
Member Function Documentation
AddElementsToKeyAccumulatorImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::AddElementsToKeyAccumulatorImpl (DirectHandle< JSObject > receiver, KeyAccumulator * accumulator, AddKeyConversion convert) [inline], [static]
Definition at line 4996 of file elements.cc.
                                {
    Isolate* isolate = accumulator->isolate();
    DirectHandle<FixedArrayBase> elements(receiver->elements(), isolate);
    uint32_t length = GetCapacityImpl(*receiver, *elements);
    for (uint32_t index = 0; index < length; index++) {
      InternalIndex entry(index);
      if (!HasEntryImpl(isolate, *elements, entry)) continue;
      DirectHandle<Object> value = GetImpl(isolate, *elements, entry);
      RETURN_FAILURE_IF_NOT_SUCCESSFUL(accumulator->AddKey(value, convert));
    }
    return ExceptionStatus::kSuccess;
  }
References v8::internal::KeyAccumulator::AddKey(), v8::internal::index, v8::internal::KeyAccumulator::isolate(), v8::internal::kSuccess, v8::internal::length, RETURN_FAILURE_IF_NOT_SUCCESSFUL, and v8::internal::value.
CollectElementIndicesImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static V8_WARN_UNUSED_RESULT ExceptionStatus v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::CollectElementIndicesImpl (DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, KeyAccumulator * keys) [inline], [static]
Definition at line 5100 of file elements.cc.
                            {
    Isolate* isolate = keys->isolate();
    uint32_t nof_indices = 0;
    Handle<FixedArray> indices = isolate->factory()->NewFixedArray(
        GetCapacityImpl(*object, *backing_store));
    DirectCollectElementIndicesImpl(isolate, object, backing_store,
                                    GetKeysConversion::kKeepNumbers,
                                    ENUMERABLE_STRINGS, indices, &nof_indices);
    SortIndices(isolate, indices, nof_indices);
    for (uint32_t i = 0; i < nof_indices; i++) {
      RETURN_FAILURE_IF_NOT_SUCCESSFUL(keys->AddKey(indices->get(i)));
    }
    return ExceptionStatus::kSuccess;
  }
References v8::internal::KeyAccumulator::AddKey(), v8::internal::ENUMERABLE_STRINGS, v8::internal::Isolate::factory(), v8::internal::KeyAccumulator::isolate(), v8::internal::kKeepNumbers, v8::internal::kSuccess, v8::internal::FactoryBase< Impl >::NewFixedArray(), RETURN_FAILURE_IF_NOT_SUCCESSFUL, and v8::internal::anonymous_namespace{elements.cc}::SortIndices().
ConvertArgumentsStoreResult()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::ConvertArgumentsStoreResult (DirectHandle< SloppyArgumentsElements > elements, DirectHandle< Object > result) [inline], [static]
Definition at line 4873 of file elements.cc.
                                   {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
DeleteImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::DeleteImpl (Isolate * isolate, DirectHandle< JSObject > obj, InternalIndex entry) [inline], [static]
Definition at line 5075 of file elements.cc.
                                              {
    DirectHandle<SloppyArgumentsElements> elements(
        Cast<SloppyArgumentsElements>(obj->elements()), isolate);
    uint32_t length = elements->length();
    InternalIndex delete_or_entry = entry;
    if (entry.as_uint32() < length) {
      delete_or_entry = InternalIndex::NotFound();
    }
    Subclass::SloppyDeleteImpl(isolate, obj, elements, delete_or_entry);
    // SloppyDeleteImpl allocates a new dictionary elements store. For making
    // heap verification happy we postpone clearing out the mapped entry.
    if (entry.as_uint32() < length) {
      elements->set_mapped_entries(entry.as_uint32(),
                                   GetReadOnlyRoots().the_hole_value());
    }
  }
References v8::internal::InternalIndex::as_uint32(), v8::internal::GetReadOnlyRoots(), v8::internal::length, and v8::internal::InternalIndex::NotFound().
DirectCollectElementIndicesImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static Handle<FixedArray> v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::DirectCollectElementIndicesImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< FixedArrayBase > backing_store, GetKeysConversion convert, PropertyFilter filter, Handle< FixedArray > list, uint32_t * nof_indices, uint32_t insertion_index = 0) [inline], [static]
Definition at line 5117 of file elements.cc.
                                    {
    auto elements = Cast<SloppyArgumentsElements>(backing_store);
    uint32_t length = elements->length();
    for (uint32_t i = 0; i < length; ++i) {
      if (IsTheHole(elements->mapped_entries(i, kRelaxedLoad), isolate))
        continue;
      if (convert == GetKeysConversion::kConvertToString) {
        DirectHandle<String> index_string =
            isolate->factory()->Uint32ToString(i);
        list->set(insertion_index, *index_string);
      } else {
        list->set(insertion_index, Smi::FromInt(i));
      }
      insertion_index++;
    }
    DirectHandle<FixedArray> store(elements->arguments(), isolate);
    return ArgumentsAccessor::DirectCollectElementIndicesImpl(
        isolate, object, store, convert, filter, list, nof_indices,
        insertion_index);
  }
References v8::internal::Isolate::factory(), v8::internal::Smi::FromInt(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kConvertToString, v8::kRelaxedLoad, v8::internal::length, store(), and v8::internal::Factory::Uint32ToString().
GetCapacityImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static uint32_t v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetCapacityImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > store) [inline], [static]
Definition at line 4960 of file elements.cc.
                                                                {
    Tagged<SloppyArgumentsElements> elements =
        Cast<SloppyArgumentsElements>(store);
    Tagged<FixedArray> arguments = elements->arguments();
    return elements->length() +
           ArgumentsAccessor::GetCapacityImpl(holder, arguments);
  }
References store().
GetDetailsImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static PropertyDetails v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetDetailsImpl (Tagged< JSObject > holder, InternalIndex entry) [inline], [static]
Definition at line 5051 of file elements.cc.
                                                             {
    Tagged<SloppyArgumentsElements> elements =
        Cast<SloppyArgumentsElements>(holder->elements());
    uint32_t length = elements->length();
    if (entry.as_uint32() < length) {
      return PropertyDetails(PropertyKind::kData, NONE,
                             PropertyCellType::kNoCell);
    }
    Tagged<FixedArray> arguments = elements->arguments();
    return ArgumentsAccessor::GetDetailsImpl(arguments,
                                             entry.adjust_down(length));
  }
References v8::internal::InternalIndex::adjust_down(), v8::internal::InternalIndex::as_uint32(), v8::internal::kData, v8::internal::kNoCell, v8::internal::length, and v8::internal::NONE.
GetEntryForIndexImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static InternalIndex v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetEntryForIndexImpl (Isolate * isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > parameters, size_t index, PropertyFilter filter) [inline], [static]
Definition at line 5032 of file elements.cc.
                                                                   {
    Tagged<SloppyArgumentsElements> elements =
        Cast<SloppyArgumentsElements>(parameters);
    if (HasParameterMapArg(isolate, elements, index)) {
      return InternalIndex(index);
    }
    Tagged<FixedArray> arguments = elements->arguments();
    InternalIndex entry = ArgumentsAccessor::GetEntryForIndexImpl(
        isolate, holder, arguments, index, filter);
    if (entry.is_not_found()) return entry;
    // Arguments entries could overlap with the dictionary entries, hence offset
    // them by the number of context mapped entries.
    return entry.adjust_up(elements->length());
  }
References v8::internal::InternalIndex::adjust_up(), v8::internal::index, and v8::internal::InternalIndex::is_not_found().
GetImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static Handle<Object> v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetImpl (Isolate * isolate, Tagged< FixedArrayBase > parameters, InternalIndex entry) [inline], [static]
Definition at line 4879 of file elements.cc.
                                                     {
    DirectHandle<SloppyArgumentsElements> elements(
        Cast<SloppyArgumentsElements>(parameters), isolate);
    uint32_t length = elements->length();
    if (entry.as_uint32() < length) {
      // Read context mapped entry.
      DisallowGarbageCollection no_gc;
      Tagged<Object> probe =
          elements->mapped_entries(entry.as_uint32(), kRelaxedLoad);
      DCHECK(!IsTheHole(probe, isolate));
      Tagged<Context> context = elements->context();
      int context_entry = Smi::ToInt(probe);
      DCHECK(!IsTheHole(context->GetNoCell(context_entry), isolate));
      return handle(context->GetNoCell(context_entry), isolate);
    } else {
      // Entry is not context mapped, defer to the arguments.
      Handle<Object> result = ArgumentsAccessor::GetImpl(
          isolate, elements->arguments(), entry.adjust_down(length));
      return Subclass::ConvertArgumentsStoreResult(isolate, elements, result);
    }
  }
References v8::internal::InternalIndex::adjust_down(), v8::internal::InternalIndex::as_uint32(), v8::internal::DCHECK(), v8::internal::handle(), v8::kRelaxedLoad, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::base::internal::result, and v8::internal::Smi::ToInt().
GetMaxNumberOfEntries()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static uint32_t v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GetMaxNumberOfEntries (Isolate * isolate, Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 4969 of file elements.cc.
                                                                              {
    Tagged<SloppyArgumentsElements> elements =
        Cast<SloppyArgumentsElements>(backing_store);
    Tagged<FixedArrayBase> arguments = elements->arguments();
    size_t max_entries =
        ArgumentsAccessor::GetMaxNumberOfEntries(isolate, holder, arguments);
    DCHECK_LE(max_entries, std::numeric_limits<uint32_t>::max());
    return elements->length() + static_cast<uint32_t>(max_entries);
  }
References DCHECK_LE.
GrowCapacityAndConvertImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::GrowCapacityAndConvertImpl (Isolate * isolate, DirectHandle< JSObject > object, uint32_t capacity) [inline], [static]
Definition at line 4909 of file elements.cc.
                                                                   {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
HasAccessorsImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static bool v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::HasAccessorsImpl (Tagged< JSObject > holder, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 5024 of file elements.cc.
                                                                     {
    Tagged<SloppyArgumentsElements> elements =
        Cast<SloppyArgumentsElements>(backing_store);
    Tagged<FixedArray> arguments = elements->arguments();
    return ArgumentsAccessor::HasAccessorsImpl(holder, arguments);
  }
HasEntryImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static bool v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::HasEntryImpl (Isolate * isolate, Tagged< FixedArrayBase > parameters, InternalIndex entry) [inline], [static]
Definition at line 5011 of file elements.cc.
                                                {
    Tagged<SloppyArgumentsElements> elements =
        Cast<SloppyArgumentsElements>(parameters);
    uint32_t length = elements->length();
    if (entry.raw_value() < length) {
      return HasParameterMapArg(isolate, elements, entry.raw_value());
    }
    Tagged<FixedArrayBase> arguments = elements->arguments();
    return ArgumentsAccessor::HasEntryImpl(isolate, arguments,
                                           entry.adjust_down(length));
  }
References v8::internal::InternalIndex::adjust_down(), v8::internal::length, and v8::internal::InternalIndex::raw_value().
HasParameterMapArg()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static bool v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::HasParameterMapArg (Isolate * isolate, Tagged< SloppyArgumentsElements > elements, size_t index) [inline], [static]
Definition at line 5065 of file elements.cc.
                                               {
    uint32_t length = elements->length();
    if (index >= length) return false;
    return !IsTheHole(
        elements->mapped_entries(static_cast<uint32_t>(index), kRelaxedLoad),
        isolate);
  }
References v8::internal::index, v8::kRelaxedLoad, and v8::internal::length.
IncludesValueImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IncludesValueImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Object > value, size_t start_from, size_t length) [inline], [static]
Definition at line 5144 of file elements.cc.
                                                                         {
    DCHECK(JSObject::PrototypeHasNoElements(isolate, *object));
    DirectHandle<Map> original_map(object->map(), isolate);
    DirectHandle<SloppyArgumentsElements> elements(
        Cast<SloppyArgumentsElements>(object->elements()), isolate);
    bool search_for_hole = IsUndefined(*value, isolate);
    for (size_t k = start_from; k < length; ++k) {
      DCHECK_EQ(object->map(), *original_map);
      InternalIndex entry =
          GetEntryForIndexImpl(isolate, *object, *elements, k, ALL_PROPERTIES);
      if (entry.is_not_found()) {
        if (search_for_hole) return Just(true);
        continue;
      }
      DirectHandle<Object> element_k =
          Subclass::GetImpl(isolate, *elements, entry);
      if (IsAccessorPair(*element_k)) {
        LookupIterator it(isolate, object, k, LookupIterator::OWN);
        DCHECK(it.IsFound());
        DCHECK_EQ(it.state(), LookupIterator::ACCESSOR);
        ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, element_k,
                                         Object::GetPropertyWithAccessor(&it),
                                         Nothing<bool>());
        if (Object::SameValueZero(*value, *element_k)) return Just(true);
        if (object->map() != *original_map) {
          // Some mutation occurred in accessor. Abort "fast" path
          return IncludesValueSlowPath(isolate, object, value, k + 1, length);
        }
      } else if (Object::SameValueZero(*value, *element_k)) {
        return Just(true);
      }
    }
    return Just(false);
  }
References v8::internal::LookupIterator::ACCESSOR, v8::internal::ALL_PROPERTIES, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Object::GetPropertyWithAccessor(), v8::internal::anonymous_namespace{elements.cc}::IncludesValueSlowPath(), v8::internal::InternalIndex::is_not_found(), v8::internal::LookupIterator::IsFound(), v8::Just(), v8::internal::length, v8::internal::LookupIterator::OWN, v8::internal::JSObject::PrototypeHasNoElements(), v8::internal::Object::SameValueZero(), v8::internal::LookupIterator::state(), and v8::internal::value.
IndexOfValueImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static Maybe<int64_t> v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::IndexOfValueImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Object > value, size_t start_from, size_t length) [inline], [static]
Definition at line 5187 of file elements.cc.
                                                                           {
    DCHECK(JSObject::PrototypeHasNoElements(isolate, *object));
    DirectHandle<Map> original_map(object->map(), isolate);
    DirectHandle<SloppyArgumentsElements> elements(
        Cast<SloppyArgumentsElements>(object->elements()), isolate);
    for (size_t k = start_from; k < length; ++k) {
      DCHECK_EQ(object->map(), *original_map);
      InternalIndex entry =
          GetEntryForIndexImpl(isolate, *object, *elements, k, ALL_PROPERTIES);
      if (entry.is_not_found()) {
        continue;
      }
      DirectHandle<Object> element_k =
          Subclass::GetImpl(isolate, *elements, entry);
      if (IsAccessorPair(*element_k)) {
        LookupIterator it(isolate, object, k, LookupIterator::OWN);
        DCHECK(it.IsFound());
        DCHECK_EQ(it.state(), LookupIterator::ACCESSOR);
        ASSIGN_RETURN_ON_EXCEPTION_VALUE(isolate, element_k,
                                         Object::GetPropertyWithAccessor(&it),
                                         Nothing<int64_t>());
        if (Object::StrictEquals(*value, *element_k)) {
          return Just<int64_t>(k);
        }
        if (object->map() != *original_map) {
          // Some mutation occurred in accessor. Abort "fast" path.
          return IndexOfValueSlowPath(isolate, object, value, k + 1, length);
        }
      } else if (Object::StrictEquals(*value, *element_k)) {
        return Just<int64_t>(k);
      }
    }
    return Just<int64_t>(-1);
  }
References v8::internal::LookupIterator::ACCESSOR, v8::internal::ALL_PROPERTIES, ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Object::GetPropertyWithAccessor(), v8::internal::anonymous_namespace{elements.cc}::IndexOfValueSlowPath(), v8::internal::InternalIndex::is_not_found(), v8::internal::LookupIterator::IsFound(), v8::internal::length, v8::internal::LookupIterator::OWN, v8::internal::JSObject::PrototypeHasNoElements(), v8::internal::LookupIterator::state(), v8::internal::Object::StrictEquals(), and v8::internal::value.
NumberOfElementsImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static uint32_t v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::NumberOfElementsImpl (Isolate * isolate, Tagged< JSObject > receiver, Tagged< FixedArrayBase > backing_store) [inline], [static]
Definition at line 4981 of file elements.cc.
                                                                             {
    Tagged<SloppyArgumentsElements> elements =
        Cast<SloppyArgumentsElements>(backing_store);
    Tagged<FixedArrayBase> arguments = elements->arguments();
    uint32_t nof_elements = 0;
    uint32_t length = elements->length();
    for (uint32_t index = 0; index < length; index++) {
      if (HasParameterMapArg(isolate, elements, index)) nof_elements++;
    }
    return nof_elements + ArgumentsAccessor::NumberOfElementsImpl(
                              isolate, receiver, arguments);
  }
References v8::internal::index, and v8::internal::length.
SetImpl() [1/2]
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::SetImpl (DirectHandle< JSObject > holder, InternalIndex entry, Tagged< Object > value) [inline], [static]
Definition at line 4915 of file elements.cc.
                                                   {
    SetImpl(holder->elements(), entry, value);
  }
References v8::internal::value.
SetImpl() [2/2]
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::SetImpl (Tagged< FixedArrayBase > store, InternalIndex entry, Tagged< Object > value) [inline], [static]
Definition at line 4920 of file elements.cc.
                                                   {
    Tagged<SloppyArgumentsElements> elements =
        Cast<SloppyArgumentsElements>(store);
    uint32_t length = elements->length();
    if (entry.as_uint32() < length) {
      // Store context mapped entry.
      DisallowGarbageCollection no_gc;
      Tagged<Object> probe =
          elements->mapped_entries(entry.as_uint32(), kRelaxedLoad);
      DCHECK(!IsTheHole(probe));
      Tagged<Context> context = Cast<Context>(elements->context());
      int context_entry = Smi::ToInt(probe);
      DCHECK(!IsTheHole(context->GetNoCell(context_entry)));
      context->SetNoCell(context_entry, value);
    } else {
      // Entry is not context mapped defer to arguments.
      Tagged<FixedArray> arguments = elements->arguments();
      Tagged<Object> current =
          ArgumentsAccessor::GetRaw(arguments, entry.adjust_down(length));
      if (IsAliasedArgumentsEntry(current)) {
        Tagged<AliasedArgumentsEntry> alias =
            Cast<AliasedArgumentsEntry>(current);
        Tagged<Context> context = Cast<Context>(elements->context());
        int context_entry = alias->aliased_context_slot();
        DCHECK(!IsTheHole(context->GetNoCell(context_entry)));
        context->SetNoCell(context_entry, value);
      } else {
        ArgumentsAccessor::SetImpl(arguments, entry.adjust_down(length), value);
      }
    }
  }
References v8::internal::InternalIndex::adjust_down(), v8::internal::InternalIndex::as_uint32(), v8::internal::DCHECK(), v8::kRelaxedLoad, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, store(), v8::internal::Smi::ToInt(), and v8::internal::value.
SetLengthImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static Maybe<bool> v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::SetLengthImpl (Isolate * isolate, DirectHandle< JSArray > array, uint32_t length, DirectHandle< FixedArrayBase > parameter_map) [inline], [static]
Definition at line 4953 of file elements.cc.
                                                                               {
    // Sloppy arguments objects are not arrays.
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
SloppyDeleteImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::SloppyDeleteImpl (Isolate * isolate, DirectHandle< JSObject > obj, DirectHandle< SloppyArgumentsElements > elements, InternalIndex entry) [inline], [static]
Definition at line 5093 of file elements.cc.
                                                    {
    // Implemented in subclasses.
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
TransitionElementsKindImpl()
template<typename Subclass , typename ArgumentsAccessor , typename KindTraits >
static void v8::internal::anonymous_namespace{elements.cc}::SloppyArgumentsElementsAccessor< Subclass, ArgumentsAccessor, KindTraits >::TransitionElementsKindImpl (Isolate * isolate, DirectHandle< JSObject > object, DirectHandle< Map > map) [inline], [static]
Definition at line 4903 of file elements.cc.
                                                                {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/elements.cc