v8::EmbedderGraph::Node Class Reference
#include <v8-profiler.h>
Public Types
enum class Detachedness : uint8_t { kUnknown = 0
, kAttached = 1
, kDetached = 2
 }
Detachedness specifies whether an object is attached or detached from the main application state.
Public Member Functions
Node ()=default
virtual ~Node ()=default
virtual const char * Name ()=0
virtual size_t SizeInBytes ()=0
virtual Node * WrapperNode ()
The corresponding V8 wrapper node if not null.
virtual bool IsRootNode ()
virtual bool IsEmbedderNode ()
Must return true for non-V8 nodes.
virtual const char * NamePrefix ()
Optional name prefix.
virtual NativeObject GetNativeObject ()
Returns the NativeObject that can be used for querying the |HeapSnapshot|.
virtual Detachedness GetDetachedness ()
Detachedness state of a given object.
virtual const void * GetAddress ()
Returns the address of the object in the embedder heap, or nullptr to not specify the address.
Node (const Node &)=delete
Node & operator= (const Node &)=delete
Detailed Description
Definition at line 846 of file v8-profiler.h.
Member Enumeration Documentation
Detachedness
enum v8::EmbedderGraph::Node::Detachedness : uint8_t [strong]
Detachedness specifies whether an object is attached or detached from the main application state.
While unkown in general, there may be objects that specifically know their state. V8 passes this information along in the snapshot. Users of the snapshot may use it to annotate the object graph.
Enumerator
kUnknown
kAttached
kDetached
Definition at line 855 of file v8-profiler.h.
                            : uint8_t {
      kUnknown = 0,
      kAttached = 1,
      kDetached = 2,
    };
Constructor & Destructor Documentation
Node() [1/2]
v8::EmbedderGraph::Node::Node () [default]
 Node()
virtual v8::EmbedderGraph::Node::~Node () [virtual], [default]
Node() [2/2]
v8::EmbedderGraph::Node::Node (const Node &) [delete]
Member Function Documentation
GetAddress()
virtual const void* v8::EmbedderGraph::Node::GetAddress () [inline], [virtual]
Returns the address of the object in the embedder heap, or nullptr to not specify the address.
If this address is provided, then V8 can generate consistent IDs for objects across subsequent heap snapshots, which allows devtools to determine which objects were retained from one snapshot to the next. This value is used only if GetNativeObject returns nullptr.
Reimplemented in v8::internal::EmbedderNode.
Definition at line 900 of file v8-profiler.h.
{ return nullptr; }
Referenced by v8::internal::EmbedderGraphEntriesAllocator::AllocateEntry().
GetDetachedness()
virtual Detachedness v8::EmbedderGraph::Node::GetDetachedness () [inline], [virtual]
Detachedness state of a given object.
While unkown in general, there may be objects that specifically know their state. V8 passes this information along in the snapshot. Users of the snapshot may use it to annotate the object graph.
Reimplemented in v8::internal::EmbedderNode.
Definition at line 891 of file v8-profiler.h.
{ return Detachedness::kUnknown; }
Referenced by v8::internal::EmbedderGraphEntriesAllocator::AllocateEntry(), and v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry().
GetNativeObject()
virtual NativeObject v8::EmbedderGraph::Node::GetNativeObject () [inline], [virtual]
Returns the NativeObject that can be used for querying the |HeapSnapshot|.
Definition at line 883 of file v8-profiler.h.
{ return nullptr; }
Referenced by v8::internal::EmbedderGraphEntriesAllocator::AllocateEntry(), and v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry().
IsEmbedderNode()
virtual bool v8::EmbedderGraph::Node::IsEmbedderNode () [inline], [virtual]
Must return true for non-V8 nodes.
Reimplemented in v8::internal::EmbedderGraphImpl::V8NodeImpl.
Definition at line 873 of file v8-profiler.h.
{ return true; }
Referenced by v8::internal::EmbedderGraphEntriesAllocator::AllocateEntry(), v8::internal::NativeObjectsExplorer::EntryForEmbedderGraphNode(), and v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry().
IsRootNode()
virtual bool v8::EmbedderGraph::Node::IsRootNode () [inline], [virtual]
Reimplemented in v8::internal::EmbedderRootNode.
Definition at line 871 of file v8-profiler.h.
{ return false; }
Referenced by v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::EmbedderGraphNodeType().
Name()
virtual const char* v8::EmbedderGraph::Node::Name () [pure virtual]
Implemented in v8::internal::EmbedderGraphImpl::V8NodeImpl, and v8::internal::EmbedderNode.
Referenced by v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::EmbedderGraphNodeName().
NamePrefix()
virtual const char* v8::EmbedderGraph::Node::NamePrefix () [inline], [virtual]
Optional name prefix.
It is used in Chrome for tagging detached nodes.
Definition at line 877 of file v8-profiler.h.
{ return nullptr; }
Referenced by v8::internal::anonymous_namespace{heap-snapshot-generator.cc}::EmbedderGraphNodeName().
operator=()
Node& v8::EmbedderGraph::Node::operator= (const Node &) [delete]
SizeInBytes()
virtual size_t v8::EmbedderGraph::Node::SizeInBytes () [pure virtual]
Implemented in v8::internal::EmbedderGraphImpl::V8NodeImpl, and v8::internal::EmbedderNode.
Referenced by v8::internal::EmbedderGraphEntriesAllocator::AllocateEntry(), and v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry().
WrapperNode()
virtual Node* v8::EmbedderGraph::Node::WrapperNode () [inline], [virtual]
The corresponding V8 wrapper node if not null.
During heap snapshot generation the embedder node and the V8 wrapper node will be merged into one node to simplify retaining paths.
Reimplemented in v8::internal::EmbedderNode.
Definition at line 870 of file v8-profiler.h.
{ return nullptr; }
Referenced by v8::internal::NativeObjectsExplorer::EntryForEmbedderGraphNode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-profiler.h