v8::internal::UnoptimizedCompilationInfo Class Reference
#include <unoptimized-compilation-info.h>
Public Member Functions
UnoptimizedCompilationInfo (Zone *zone, ParseInfo *parse_info, FunctionLiteral *literal)
const UnoptimizedCompileFlags & flags () const
LazyCompileDispatcher * dispatcher ()
const Utf16CharacterStream * character_stream () const
FunctionLiteral * literal () const
void set_literal (FunctionLiteral *literal)
void ClearLiteral ()
DeclarationScope * scope () const
int num_parameters () const
int num_parameters_including_this () const
SourcePositionTableBuilder::RecordingMode SourcePositionRecordingMode () const
bool has_source_range_map () const
SourceRangeMap * source_range_map () const
void set_source_range_map (SourceRangeMap *source_range_map)
bool has_coverage_info () const
Handle< CoverageInfo > coverage_info () const
void set_coverage_info (Handle< CoverageInfo > coverage_info)
bool has_bytecode_array () const
Handle< BytecodeArray > bytecode_array () const
void SetBytecodeArray (Handle< BytecodeArray > bytecode_array)
bool has_asm_wasm_data () const
DirectHandle< AsmWasmData > asm_wasm_data () const
void SetAsmWasmData (Handle< AsmWasmData > asm_wasm_data)
FeedbackVectorSpec * feedback_vector_spec ()
Private Attributes
const UnoptimizedCompileFlags flags_
LazyCompileDispatcher * dispatcher_
const Utf16CharacterStream * character_stream_
FunctionLiteral * literal_
SourceRangeMap * source_range_map_
IndirectHandle< CoverageInfo > coverage_info_
IndirectHandle< BytecodeArray > bytecode_array_
IndirectHandle< AsmWasmData > asm_wasm_data_
FeedbackVectorSpec feedback_vector_spec_
Detailed Description
Definition at line 32 of file unoptimized-compilation-info.h.
Constructor & Destructor Documentation
UnoptimizedCompilationInfo()
v8::internal::UnoptimizedCompilationInfo::UnoptimizedCompilationInfo (Zone * zone, ParseInfo * parse_info, FunctionLiteral * literal)
Definition at line 18 of file unoptimized-compilation-info.cc.
    : flags_(parse_info->flags()),
      dispatcher_(parse_info->dispatcher()),
      character_stream_(parse_info->character_stream()),
      feedback_vector_spec_(zone) {
  // NOTE: The parse_info passed here represents the global information gathered
  // during parsing, but does not represent specific details of the actual
  // function literal being compiled for this OptimizedCompilationInfo. As such,
  // parse_info->literal() might be different from literal, and only global
  // details of the script being parsed are relevant to this
  // OptimizedCompilationInfo.
  DCHECK_NOT_NULL(literal);
  literal_ = literal;
  source_range_map_ = parse_info->source_range_map();
}
References DCHECK_NOT_NULL, literal(), literal_, v8::internal::ParseInfo::source_range_map(), and source_range_map_.
Member Function Documentation
asm_wasm_data()
DirectHandle<AsmWasmData> v8::internal::UnoptimizedCompilationInfo::asm_wasm_data () const [inline]
Definition at line 82 of file unoptimized-compilation-info.h.
{ return asm_wasm_data_; }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::InstallUnoptimizedCode().
bytecode_array()
Handle<BytecodeArray> v8::internal::UnoptimizedCompilationInfo::bytecode_array () const [inline]
Definition at line 76 of file unoptimized-compilation-info.h.
{ return bytecode_array_; }
Referenced by v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl(), v8::internal::interpreter::BytecodeGenerator::FinalizeSourcePositionTable(), and v8::internal::anonymous_namespace{compiler.cc}::InstallUnoptimizedCode().
character_stream()
const Utf16CharacterStream* v8::internal::UnoptimizedCompilationInfo::character_stream () const [inline]
Definition at line 39 of file unoptimized-compilation-info.h.
                                                       {
    return character_stream_;
  }
ClearLiteral()
void v8::internal::UnoptimizedCompilationInfo::ClearLiteral () [inline]
Definition at line 50 of file unoptimized-compilation-info.h.
{ literal_ = nullptr; }
coverage_info()
Handle<CoverageInfo> v8::internal::UnoptimizedCompilationInfo::coverage_info () const [inline]
Definition at line 68 of file unoptimized-compilation-info.h.
{ return coverage_info_; }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::FinalizeSingleUnoptimizedCompilationJob().
dispatcher()
LazyCompileDispatcher* v8::internal::UnoptimizedCompilationInfo::dispatcher () [inline]
Definition at line 38 of file unoptimized-compilation-info.h.
{ return dispatcher_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::AddToEagerLiteralsIfEager().
feedback_vector_spec()
FeedbackVectorSpec* v8::internal::UnoptimizedCompilationInfo::feedback_vector_spec () [inline]
Definition at line 87 of file unoptimized-compilation-info.h.
{ return &feedback_vector_spec_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::feedback_spec(), and v8::internal::anonymous_namespace{compiler.cc}::InstallUnoptimizedCode().
flags()
const UnoptimizedCompileFlags& v8::internal::UnoptimizedCompilationInfo::flags () const [inline]
Definition at line 37 of file unoptimized-compilation-info.h.
{ return flags_; }
Referenced by SourcePositionRecordingMode().
has_asm_wasm_data()
bool v8::internal::UnoptimizedCompilationInfo::has_asm_wasm_data () const [inline]
Definition at line 81 of file unoptimized-compilation-info.h.
{ return !asm_wasm_data_.is_null(); }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::InstallUnoptimizedCode().
has_bytecode_array()
bool v8::internal::UnoptimizedCompilationInfo::has_bytecode_array () const [inline]
Definition at line 75 of file unoptimized-compilation-info.h.
{ return !bytecode_array_.is_null(); }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::InstallUnoptimizedCode().
has_coverage_info()
bool v8::internal::UnoptimizedCompilationInfo::has_coverage_info () const [inline]
Definition at line 67 of file unoptimized-compilation-info.h.
{ return !coverage_info_.is_null(); }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::FinalizeSingleUnoptimizedCompilationJob().
has_source_range_map()
bool v8::internal::UnoptimizedCompilationInfo::has_source_range_map () const [inline]
Definition at line 61 of file unoptimized-compilation-info.h.
{ return source_range_map_ != nullptr; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BytecodeGenerator().
literal()
FunctionLiteral* v8::internal::UnoptimizedCompilationInfo::literal () const [inline]
Definition at line 45 of file unoptimized-compilation-info.h.
{ return literal_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildGeneratorObjectVariableInitialization(), v8::internal::interpreter::BytecodeGenerator::BuildInitializationBlockForParametersIfExist(), v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl(), v8::internal::AsmJsCompilationJob::ExecuteJobImpl(), v8::internal::interpreter::BytecodeGenerator::function_kind(), v8::internal::interpreter::BytecodeGenerator::GenerateAsyncFunctionBody(), v8::internal::interpreter::BytecodeGenerator::GenerateBaseConstructorBody(), v8::internal::interpreter::BytecodeGenerator::GenerateBodyPrologue(), v8::internal::interpreter::BytecodeGenerator::GenerateBodyStatements(), v8::internal::interpreter::BytecodeGenerator::GenerateBodyStatementsWithoutImplicitFinalReturn(), v8::internal::interpreter::BytecodeGenerator::GenerateDerivedConstructorBody(), v8::internal::anonymous_namespace{compiler.cc}::InstallUnoptimizedCode(), v8::internal::interpreter::anonymous_namespace{interpreter.cc}::MaybePrintAst(), and UnoptimizedCompilationInfo().
num_parameters()
int v8::internal::UnoptimizedCompilationInfo::num_parameters () const
Definition at line 41 of file unoptimized-compilation-info.cc.
                                                     {
  return scope()->num_parameters();
}
References v8::internal::DeclarationScope::num_parameters(), and scope().
num_parameters_including_this()
int v8::internal::UnoptimizedCompilationInfo::num_parameters_including_this () const
Definition at line 45 of file unoptimized-compilation-info.cc.
                                                                    {
  return scope()->num_parameters() + 1;
}
References v8::internal::DeclarationScope::num_parameters(), and scope().
scope()
DeclarationScope * v8::internal::UnoptimizedCompilationInfo::scope () const
Definition at line 36 of file unoptimized-compilation-info.cc.
                                                          {
  DCHECK_NOT_NULL(literal_);
  return literal_->scope();
}
References DCHECK_NOT_NULL, literal_, and v8::internal::FunctionLiteral::scope().
Referenced by v8::internal::interpreter::BytecodeGenerator::TopLevelDeclarationsBuilder::AllocateDeclarations(), v8::internal::interpreter::BytecodeGenerator::BuildInstanceInitializationAfterSuperCall(), v8::internal::interpreter::BytecodeGenerator::BuildPrivateBrandInitialization(), v8::internal::interpreter::BytecodeGenerator::GenerateBaseConstructorBody(), num_parameters(), and num_parameters_including_this().
set_coverage_info()
void v8::internal::UnoptimizedCompilationInfo::set_coverage_info (Handle< CoverageInfo > coverage_info) [inline]
Definition at line 69 of file unoptimized-compilation-info.h.
                                                             {
    coverage_info_ = coverage_info;
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::FinalizeBytecode().
set_literal()
void v8::internal::UnoptimizedCompilationInfo::set_literal (FunctionLiteral * literal) [inline]
Definition at line 46 of file unoptimized-compilation-info.h.
                                             {
    DCHECK_NOT_NULL(literal);
    literal_ = literal;
  }
References DCHECK_NOT_NULL.
set_source_range_map()
void v8::internal::UnoptimizedCompilationInfo::set_source_range_map (SourceRangeMap * source_range_map) [inline]
Definition at line 63 of file unoptimized-compilation-info.h.
                                                              {
    source_range_map_ = source_range_map;
  }
SetAsmWasmData()
void v8::internal::UnoptimizedCompilationInfo::SetAsmWasmData (Handle< AsmWasmData > asm_wasm_data) [inline]
Definition at line 83 of file unoptimized-compilation-info.h.
                                                         {
    asm_wasm_data_ = asm_wasm_data;
  }
Referenced by v8::internal::AsmJsCompilationJob::FinalizeJobImpl().
SetBytecodeArray()
void v8::internal::UnoptimizedCompilationInfo::SetBytecodeArray (Handle< BytecodeArray > bytecode_array) [inline]
Definition at line 77 of file unoptimized-compilation-info.h.
                                                              {
    bytecode_array_ = bytecode_array;
  }
Referenced by v8::internal::interpreter::InterpreterCompilationJob::DoFinalizeJobImpl().
source_range_map()
SourceRangeMap* v8::internal::UnoptimizedCompilationInfo::source_range_map () const [inline]
Definition at line 62 of file unoptimized-compilation-info.h.
{ return source_range_map_; }
Referenced by v8::internal::interpreter::BytecodeGenerator::BytecodeGenerator().
SourcePositionRecordingMode()
SourcePositionTableBuilder::RecordingMode v8::internal::UnoptimizedCompilationInfo::SourcePositionRecordingMode () const
Definition at line 50 of file unoptimized-compilation-info.cc.
                                                              {
  if (flags().collect_source_positions()) {
    return SourcePositionTableBuilder::RECORD_SOURCE_POSITIONS;
  }
  // Always collect source positions for functions that cannot be lazily
  // compiled, e.g. class member initializer functions.
  return !literal_->AllowsLazyCompilation()
             ? SourcePositionTableBuilder::RECORD_SOURCE_POSITIONS
             : SourcePositionTableBuilder::LAZY_SOURCE_POSITIONS;
}
References v8::internal::FunctionLiteral::AllowsLazyCompilation(), flags(), v8::internal::SourcePositionTableBuilder::LAZY_SOURCE_POSITIONS, literal_, and v8::internal::SourcePositionTableBuilder::RECORD_SOURCE_POSITIONS.
Member Data Documentation
asm_wasm_data_
IndirectHandle<AsmWasmData> v8::internal::UnoptimizedCompilationInfo::asm_wasm_data_ [private]
Definition at line 111 of file unoptimized-compilation-info.h.
bytecode_array_
IndirectHandle<BytecodeArray> v8::internal::UnoptimizedCompilationInfo::bytecode_array_ [private]
Definition at line 108 of file unoptimized-compilation-info.h.
character_stream_
const Utf16CharacterStream* v8::internal::UnoptimizedCompilationInfo::character_stream_ [private]
Definition at line 95 of file unoptimized-compilation-info.h.
coverage_info_
IndirectHandle<CoverageInfo> v8::internal::UnoptimizedCompilationInfo::coverage_info_ [private]
Definition at line 105 of file unoptimized-compilation-info.h.
dispatcher_
LazyCompileDispatcher* v8::internal::UnoptimizedCompilationInfo::dispatcher_ [private]
Definition at line 94 of file unoptimized-compilation-info.h.
feedback_vector_spec_
FeedbackVectorSpec v8::internal::UnoptimizedCompilationInfo::feedback_vector_spec_ [private]
Definition at line 114 of file unoptimized-compilation-info.h.
flags_
const UnoptimizedCompileFlags v8::internal::UnoptimizedCompilationInfo::flags_ [private]
Definition at line 91 of file unoptimized-compilation-info.h.
literal_
FunctionLiteral* v8::internal::UnoptimizedCompilationInfo::literal_ [private]
Definition at line 98 of file unoptimized-compilation-info.h.
Referenced by scope(), SourcePositionRecordingMode(), and UnoptimizedCompilationInfo().
source_range_map_
SourceRangeMap* v8::internal::UnoptimizedCompilationInfo::source_range_map_ [private]
Definition at line 101 of file unoptimized-compilation-info.h.
Referenced by UnoptimizedCompilationInfo().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/unoptimized-compilation-info.h
/mnt/V8SourceCode/src/codegen/unoptimized-compilation-info.cc