v8::internal::maglev::CheckJSDataViewBounds Class Reference
#include <maglev-ir.h>
Public Member Functions
CheckJSDataViewBounds (uint64_t bitfield, ExternalArrayType element_type)
Input & receiver_input ()
Input & index_input ()
int MaxCallStackArgs () const
void SetValueLocationConstraints ()
void GenerateCode (MaglevAssembler *, const ProcessingState &)
void PrintParams (std::ostream &, MaglevGraphLabeller *) const
auto options () const
ExternalArrayType element_type () const
Static Public Attributes
static constexpr OpProperties kProperties = OpProperties::EagerDeopt()
static constexpr Base::InputTypes kInputTypes
static constexpr int kReceiverIndex = 0
static constexpr int kIndexIndex = 1
Private Types
using Base = FixedInputNodeT< 2, CheckJSDataViewBounds >
Private Attributes
ExternalArrayType element_type_
Additional Inherited Members
Detailed Description
Definition at line 7407 of file maglev-ir.h.
Member Typedef Documentation
Base
using v8::internal::maglev::CheckJSDataViewBounds::Base = FixedInputNodeT<2, CheckJSDataViewBounds> [private]
Definition at line 7408 of file maglev-ir.h.
Constructor & Destructor Documentation
CheckJSDataViewBounds()
v8::internal::maglev::CheckJSDataViewBounds::CheckJSDataViewBounds (uint64_t bitfield, ExternalArrayType element_type) [inline], [explicit]
Definition at line 7411 of file maglev-ir.h.
      : Base(bitfield), element_type_(element_type) {}
Member Function Documentation
element_type()
ExternalArrayType v8::internal::maglev::CheckJSDataViewBounds::element_type () const [inline]
Definition at line 7431 of file maglev-ir.h.
{ return element_type_; }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GenerateCode()
void v8::internal::maglev::CheckJSDataViewBounds::GenerateCode (MaglevAssembler * masm, const ProcessingState & state)
Definition at line 741 of file maglev-ir-arm.cc.
                                                                       {
  MaglevAssembler::TemporaryRegisterScope temps(masm);
  Register object = ToRegister(receiver_input());
  Register index = ToRegister(index_input());
  if (v8_flags.debug_code) {
    __ AssertObjectType(object, JS_DATA_VIEW_TYPE,
                        AbortReason::kUnexpectedValue);
  }
  // Normal DataView (backed by AB / SAB) or non-length tracking backed by GSAB.
  Register byte_length = temps.Acquire();
  __ LoadBoundedSizeFromObject(byte_length, object,
                               JSDataView::kRawByteLengthOffset);
  int element_size = compiler::ExternalArrayElementSize(element_type_);
  if (element_size > 1) {
    __ sub(byte_length, byte_length, Operand(element_size - 1), SetCC);
    __ EmitEagerDeoptIf(mi, DeoptimizeReason::kOutOfBounds, this);
  }
  __ cmp(index, byte_length);
index_input()
Input& v8::internal::maglev::CheckJSDataViewBounds::index_input () [inline]
Definition at line 7422 of file maglev-ir.h.
{ return input(kIndexIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
MaxCallStackArgs()
int v8::internal::maglev::CheckJSDataViewBounds::MaxCallStackArgs () const
Definition at line 735 of file maglev-ir-arm.cc.
options()
auto v8::internal::maglev::CheckJSDataViewBounds::options () const [inline]
Definition at line 7429 of file maglev-ir.h.
{ return std::tuple{element_type_}; }
PrintParams()
void v8::internal::maglev::CheckJSDataViewBounds::PrintParams (std::ostream & , MaglevGraphLabeller *) const [inline]
Definition at line 7427 of file maglev-ir.h.
{}
receiver_input()
Input& v8::internal::maglev::CheckJSDataViewBounds::receiver_input () [inline]
Definition at line 7421 of file maglev-ir.h.
{ return input(kReceiverIndex); }
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
SetValueLocationConstraints()
void v8::internal::maglev::CheckJSDataViewBounds::SetValueLocationConstraints ()
Definition at line 736 of file maglev-ir-arm.cc.
                                                  { return 1; }
void CheckJSDataViewBounds::SetValueLocationConstraints() {
  UseRegister(receiver_input());
  UseRegister(index_input());
Member Data Documentation
element_type_
ExternalArrayType v8::internal::maglev::CheckJSDataViewBounds::element_type_ [private]
Definition at line 7434 of file maglev-ir.h.
kIndexIndex
constexpr int v8::internal::maglev::CheckJSDataViewBounds::kIndexIndex = 1 [static], [constexpr]
Definition at line 7420 of file maglev-ir.h.
kInputTypes
constexpr Base::InputTypes v8::internal::maglev::CheckJSDataViewBounds::kInputTypes [static], [constexpr]
Initial value:
{
      ValueRepresentation::kTagged, ValueRepresentation::kInt32}
Definition at line 7416 of file maglev-ir.h.
kProperties
constexpr OpProperties v8::internal::maglev::CheckJSDataViewBounds::kProperties = OpProperties::EagerDeopt() [static], [constexpr]
Definition at line 7415 of file maglev-ir.h.
kReceiverIndex
constexpr int v8::internal::maglev::CheckJSDataViewBounds::kReceiverIndex = 0 [static], [constexpr]
Definition at line 7419 of file maglev-ir.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-ir.h
/mnt/V8SourceCode/src/maglev/arm/maglev-ir-arm.cc
/mnt/V8SourceCode/src/maglev/arm64/maglev-ir-arm64.cc
/mnt/V8SourceCode/src/maglev/riscv/maglev-ir-riscv.cc
/mnt/V8SourceCode/src/maglev/s390/maglev-ir-s390.cc
/mnt/V8SourceCode/src/maglev/x64/maglev-ir-x64.cc