v8::internal::HeapLayoutTracer Class Reference
#include <heap-layout-tracer.h>
Static Public Member Functions
static void GCProloguePrintHeapLayout (v8::Isolate *isolate, v8::GCType gc_type, v8::GCCallbackFlags flags, void *data)
static void GCEpiloguePrintHeapLayout (v8::Isolate *isolate, v8::GCType gc_type, v8::GCCallbackFlags flags, void *data)
Static Private Member Functions
static void PrintMemoryChunk (std::ostream &os, const MemoryChunkMetadata &chunk, const char *owner_name)
static void PrintHeapLayout (std::ostream &os, Heap *heap)
Detailed Description
Definition at line 17 of file heap-layout-tracer.h.
Member Function Documentation
GCEpiloguePrintHeapLayout()
void v8::internal::HeapLayoutTracer::GCEpiloguePrintHeapLayout (v8::Isolate * isolate, v8::GCType gc_type, v8::GCCallbackFlags flags, void * data) [static]
Definition at line 48 of file heap-layout-tracer.cc.
                                                             {
  Heap* heap = reinterpret_cast<i::Isolate*>(isolate)->heap();
  PrintF("After GC:%d,", heap->gc_count());
  PrintF("collector_name:%s\n", TypeToCollectorName(gc_type));
  PrintHeapLayout(std::cout, heap);
}
References heap(), v8::internal::PrintF(), PrintHeapLayout(), and v8::internal::anonymous_namespace{heap-layout-tracer.cc}::TypeToCollectorName().
Referenced by v8::internal::Heap::SetUp().
GCProloguePrintHeapLayout()
void v8::internal::HeapLayoutTracer::GCProloguePrintHeapLayout (v8::Isolate * isolate, v8::GCType gc_type, v8::GCCallbackFlags flags, void * data) [static]
Definition at line 36 of file heap-layout-tracer.cc.
                                                             {
  Heap* heap = reinterpret_cast<i::Isolate*>(isolate)->heap();
  // gc_count_ will increase after this callback, manually add 1.
  PrintF("Before GC:%d,", heap->gc_count() + 1);
  PrintF("collector_name:%s\n", TypeToCollectorName(gc_type));
  PrintHeapLayout(std::cout, heap);
}
References heap(), v8::internal::PrintF(), PrintHeapLayout(), and v8::internal::anonymous_namespace{heap-layout-tracer.cc}::TypeToCollectorName().
Referenced by v8::internal::Heap::SetUp().
PrintHeapLayout()
void v8::internal::HeapLayoutTracer::PrintHeapLayout (std::ostream & os, Heap * heap) [static], [private]
Definition at line 70 of file heap-layout-tracer.cc.
                                                                 {
  if (v8_flags.minor_ms) {
    for (const PageMetadata* page : *heap->paged_new_space()) {
      PrintMemoryChunk(os, *page, "new_space");
    }
  } else {
    const SemiSpaceNewSpace* semi_space_new_space =
        SemiSpaceNewSpace::From(heap->new_space());
    for (const PageMetadata* page : semi_space_new_space->to_space()) {
      PrintMemoryChunk(os, *page, "to_space");
    }
    for (const PageMetadata* page : semi_space_new_space->from_space()) {
      PrintMemoryChunk(os, *page, "from_space");
    }
  }
  OldGenerationMemoryChunkIterator it(heap);
  MutablePageMetadata* chunk;
  while ((chunk = it.next()) != nullptr) {
    PrintMemoryChunk(os, *chunk, ToString(chunk->owner()->identity()));
  }
  for (ReadOnlyPageMetadata* page : heap->read_only_space()->pages()) {
    PrintMemoryChunk(os, *page, "ro_space");
  }
}
References v8::internal::SemiSpaceNewSpace::From(), v8::internal::SemiSpaceNewSpace::from_space(), v8::internal::BaseSpace::identity(), v8::internal::OldGenerationMemoryChunkIterator::next(), v8::internal::MutablePageMetadata::owner(), PrintMemoryChunk(), v8::internal::SemiSpaceNewSpace::to_space(), v8::internal::ToString(), and v8::internal::v8_flags.
Referenced by GCEpiloguePrintHeapLayout(), and GCProloguePrintHeapLayout().
PrintMemoryChunk()
void v8::internal::HeapLayoutTracer::PrintMemoryChunk (std::ostream & os, const MemoryChunkMetadata & chunk, const char * owner_name) [static], [private]
Definition at line 59 of file heap-layout-tracer.cc.
                                                                {
  os << "{owner:" << owner_name << ","
     << "address:" << &chunk << ","
     << "size:" << chunk.size() << ","
     << "allocated_bytes:" << chunk.allocated_bytes() << ","
     << "wasted_memory:" << chunk.wasted_memory() << "}" << std::endl;
}
References v8::internal::MemoryChunkMetadata::allocated_bytes(), v8::internal::MemoryChunkMetadata::size(), and v8::internal::MemoryChunkMetadata::wasted_memory().
Referenced by PrintHeapLayout().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap-layout-tracer.h
/mnt/V8SourceCode/src/heap/heap-layout-tracer.cc