v8::internal::compiler::FrameElider Class Reference
#include <frame-elider.h>
Public Member Functions
FrameElider (InstructionSequence *code, bool has_dummy_end_block, bool is_wasm_to_js)
void Run ()
Private Member Functions
void MarkBlocks ()
void PropagateMarks ()
void MarkDeConstruction ()
bool PropagateInOrder ()
bool PropagateReversed ()
bool PropagateIntoBlock (InstructionBlock *block)
const InstructionBlocks & instruction_blocks () const
InstructionBlock * InstructionBlockAt (RpoNumber rpo_number) const
Instruction * InstructionAt (int index) const
Private Attributes
InstructionSequence *const code_
const bool has_dummy_end_block_
const bool is_wasm_to_js_
Detailed Description
Definition at line 16 of file frame-elider.h.
Constructor & Destructor Documentation
FrameElider()
v8::internal::compiler::FrameElider::FrameElider (InstructionSequence * code, bool has_dummy_end_block, bool is_wasm_to_js) [explicit]
Definition at line 13 of file frame-elider.cc.
    : code_(code),
      has_dummy_end_block_(has_dummy_end_block),
      is_wasm_to_js_(is_wasm_to_js) {}
Member Function Documentation
instruction_blocks()
const InstructionBlocks & v8::internal::compiler::FrameElider::instruction_blocks () const [private]
Definition at line 193 of file frame-elider.cc.
                                                               {
  return code_->instruction_blocks();
}
References code_, and v8::internal::compiler::InstructionSequence::instruction_blocks().
Referenced by MarkBlocks(), MarkDeConstruction(), PropagateInOrder(), PropagateReversed(), and Run().
InstructionAt()
Instruction * v8::internal::compiler::FrameElider::InstructionAt (int index) const [private]
Definition at line 201 of file frame-elider.cc.
                                                       {
  return code_->InstructionAt(index);
}
References code_, v8::internal::index, and v8::internal::compiler::InstructionSequence::InstructionAt().
Referenced by MarkBlocks(), and MarkDeConstruction().
InstructionBlockAt()
InstructionBlock * v8::internal::compiler::FrameElider::InstructionBlockAt (RpoNumber rpo_number) const [private]
Definition at line 197 of file frame-elider.cc.
                                                                            {
  return code_->InstructionBlockAt(rpo_number);
}
References code_, and v8::internal::compiler::InstructionSequence::InstructionBlockAt().
Referenced by MarkDeConstruction(), and PropagateIntoBlock().
MarkBlocks()
void v8::internal::compiler::FrameElider::MarkBlocks () [private]
Definition at line 33 of file frame-elider.cc.
                             {
  for (InstructionBlock* block : instruction_blocks()) {
    if (block->needs_frame()) continue;
    for (int i = block->code_start(); i < block->code_end(); ++i) {
      const Instruction* instr = InstructionAt(i);
      if (instr->IsCall() || instr->IsDeoptimizeCall() ||
          instr->arch_opcode() == ArchOpcode::kArchStackPointerGreaterThan ||
          instr->arch_opcode() == ArchOpcode::kArchFramePointer) {
        block->mark_needs_frame();
        break;
      }
      if (instr->arch_opcode() == ArchOpcode::kArchStackSlot &&
          ((instr->InputAt(0)->IsImmediate() &&
            code_->GetImmediate(ImmediateOperand::cast(instr->InputAt(0)))
                    .ToInt32() > 0) ||
           is_wasm_to_js_)) {
        // We shouldn't allow accesses to the stack below the current stack
        // pointer (indicated by positive slot indices).
        // This is in particular because signal handlers (which could, of
        // course, be triggered at any point in time) will overwrite this
        // memory.
        // Additionally wasm-to-JS code always requires a frame to address
        // stack slots, because the stack pointer may switch to the central
        // stack at the beginning of the code.
        block->mark_needs_frame();
        break;
      }
    }
  }
}
References v8::internal::compiler::Instruction::arch_opcode(), code_, v8::internal::compiler::InstructionSequence::GetImmediate(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Instruction::InputAt(), instruction_blocks(), InstructionAt(), is_wasm_to_js_, v8::internal::compiler::Instruction::IsCall(), v8::internal::compiler::Instruction::IsDeoptimizeCall(), and v8::internal::compiler::Constant::ToInt32().
Referenced by Run().
MarkDeConstruction()
void v8::internal::compiler::FrameElider::MarkDeConstruction () [private]
Definition at line 69 of file frame-elider.cc.
                                     {
  for (InstructionBlock* block : instruction_blocks()) {
    if (block->needs_frame()) {
      // Special case: The start block needs a frame.
      if (block->predecessors().empty()) {
        block->mark_must_construct_frame();
        if (block->SuccessorCount() == 0) {
          // We only have a single block, so the block also needs to be marked
          // to deconstruct the frame.
          const Instruction* last =
              InstructionAt(block->last_instruction_index());
          // The only cases when we need to deconstruct are ret and jump.
          if (last->IsRet() || last->IsJump()) {
            block->mark_must_deconstruct_frame();
          }
        }
      }
      // Find "frame -> no frame" transitions, inserting frame
      // deconstructions.
      for (RpoNumber& succ : block->successors()) {
        if (!InstructionBlockAt(succ)->needs_frame()) {
          DCHECK_EQ(1U, block->SuccessorCount());
          const Instruction* last =
              InstructionAt(block->last_instruction_index());
          if (last->IsTailCall() || last->IsDeoptimizeCall()) {
            // We need to keep the frame if we exit the block through any
            // of these.
            continue;
          }
          // The only cases when we need to deconstruct are ret and jump.
          DCHECK(last->IsRet() || last->IsJump());
          block->mark_must_deconstruct_frame();
        }
      }
      if (block->SuccessorCount() == 0) {
        const Instruction* last =
            InstructionAt(block->last_instruction_index());
        // The only cases when we need to deconstruct are ret and jump.
        if (last->IsRet() || last->IsJump()) {
          block->mark_must_deconstruct_frame();
        }
      }
    } else {
      // Find "no frame -> frame" transitions, inserting frame constructions.
      for (RpoNumber& succ : block->successors()) {
        if (InstructionBlockAt(succ)->needs_frame()) {
          DCHECK_NE(1U, block->SuccessorCount());
          InstructionBlockAt(succ)->mark_must_construct_frame();
        }
      }
    }
  }
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NE, instruction_blocks(), InstructionAt(), InstructionBlockAt(), v8::internal::compiler::Instruction::IsDeoptimizeCall(), v8::internal::compiler::Instruction::IsJump(), v8::internal::compiler::Instruction::IsRet(), v8::internal::compiler::Instruction::IsTailCall(), and v8::internal::compiler::InstructionBlock::mark_must_construct_frame().
Referenced by Run().
PropagateInOrder()
bool v8::internal::compiler::FrameElider::PropagateInOrder () [private]
Definition at line 123 of file frame-elider.cc.
                                   {
  bool changed = false;
  for (InstructionBlock* block : instruction_blocks()) {
    changed |= PropagateIntoBlock(block);
  }
  return changed;
}
References instruction_blocks(), and PropagateIntoBlock().
Referenced by PropagateMarks().
PropagateIntoBlock()
bool v8::internal::compiler::FrameElider::PropagateIntoBlock (InstructionBlock * block) [private]
Definition at line 139 of file frame-elider.cc.
                                                            {
  // Already marked, nothing to do...
  if (block->needs_frame()) return false;
  // Turbofan does have an empty dummy end block, which we need to ignore here.
  // However, Turboshaft does not have such a block.
  if (has_dummy_end_block_) {
    // Never mark the dummy end node, otherwise we might incorrectly decide to
    // put frame deconstruction code there later,
    if (block->successors().empty()) return false;
  }
  // Propagate towards the end ("downwards") if there is a predecessor needing
  // a frame, but don't "bleed" from deferred code to non-deferred code.
  for (RpoNumber& pred : block->predecessors()) {
    if (InstructionBlockAt(pred)->needs_frame() &&
        (!InstructionBlockAt(pred)->IsDeferred() || block->IsDeferred())) {
      block->mark_needs_frame();
      return true;
    }
  }
  // Propagate towards start ("upwards")
  bool need_frame_successors = false;
  if (block->SuccessorCount() == 1) {
    // For single successors, propagate the needs_frame information.
    need_frame_successors =
        InstructionBlockAt(block->successors()[0])->needs_frame();
  } else {
    // For multiple successors, each successor must only have a single
    // predecessor (because the graph is in edge-split form), so each successor
    // can independently create/dismantle a frame if needed. Given this
    // independent control, only propagate needs_frame if all non-deferred
    // blocks need a frame.
    for (RpoNumber& succ : block->successors()) {
      InstructionBlock* successor_block = InstructionBlockAt(succ);
      DCHECK_EQ(1, successor_block->PredecessorCount());
      if (!successor_block->IsDeferred()) {
        if (successor_block->needs_frame()) {
          need_frame_successors = true;
        } else {
          return false;
        }
      }
    }
  }
  if (need_frame_successors) {
    block->mark_needs_frame();
    return true;
  } else {
    return false;
  }
}
References DCHECK_EQ, v8::internal::ZoneVector< T >::empty(), has_dummy_end_block_, InstructionBlockAt(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::torque::IsDeferred(), v8::internal::compiler::InstructionBlock::mark_needs_frame(), v8::internal::compiler::InstructionBlock::needs_frame(), v8::internal::compiler::InstructionBlock::PredecessorCount(), v8::internal::compiler::InstructionBlock::predecessors(), v8::internal::compiler::InstructionBlock::SuccessorCount(), and v8::internal::compiler::InstructionBlock::successors().
Referenced by PropagateInOrder(), and PropagateReversed().
PropagateMarks()
void v8::internal::compiler::FrameElider::PropagateMarks () [private]
Definition at line 64 of file frame-elider.cc.
                                 {
  while (PropagateInOrder() || PropagateReversed()) {
  }
}
References PropagateInOrder(), and PropagateReversed().
Referenced by Run().
PropagateReversed()
bool v8::internal::compiler::FrameElider::PropagateReversed () [private]
Definition at line 131 of file frame-elider.cc.
                                    {
  bool changed = false;
  for (InstructionBlock* block : base::Reversed(instruction_blocks())) {
    changed |= PropagateIntoBlock(block);
  }
  return changed;
}
References instruction_blocks(), PropagateIntoBlock(), and v8::base::Reversed().
Referenced by PropagateMarks().
Run()
void v8::internal::compiler::FrameElider::Run ()
Definition at line 19 of file frame-elider.cc.
                      {
  if (!v8_flags.turbo_elide_frames) {
#ifdef DEBUG
    for (InstructionBlock* block : instruction_blocks()) {
      CHECK(block->needs_frame());
    }
#endif
    return;
  }
  MarkBlocks();
  PropagateMarks();
  MarkDeConstruction();
}
References CHECK, instruction_blocks(), MarkBlocks(), MarkDeConstruction(), PropagateMarks(), and v8::internal::v8_flags.
Referenced by v8::internal::compiler::turboshaft::FrameElisionPhase::Run().
Member Data Documentation
code_
InstructionSequence* const v8::internal::compiler::FrameElider::code_ [private]
Definition at line 33 of file frame-elider.h.
Referenced by instruction_blocks(), InstructionAt(), InstructionBlockAt(), and MarkBlocks().
has_dummy_end_block_
const bool v8::internal::compiler::FrameElider::has_dummy_end_block_ [private]
Definition at line 34 of file frame-elider.h.
Referenced by PropagateIntoBlock().
is_wasm_to_js_
const bool v8::internal::compiler::FrameElider::is_wasm_to_js_ [private]
Definition at line 35 of file frame-elider.h.
Referenced by MarkBlocks().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/frame-elider.h
/mnt/V8SourceCode/src/compiler/backend/frame-elider.cc