v8::internal::interpreter::ConditionalChainControlFlowBuilder Class Reference
#include <control-flow-builders.h>
Public Member Functions
ConditionalChainControlFlowBuilder (BytecodeArrayBuilder *builder, BlockCoverageBuilder *block_coverage_builder, AstNode *node, size_t then_count)
~ConditionalChainControlFlowBuilder () override
BytecodeLabels * then_labels_at (size_t index)
BytecodeLabels * else_labels_at (size_t index)
int block_coverage_then_slot_at (size_t index) const
int block_coverage_else_slot_at (size_t index) const
void ThenAt (size_t index)
void ElseAt (size_t index)
void JumpToEnd ()
Private Attributes
BytecodeLabels end_labels_
size_t then_count_
ZonePtrList< BytecodeLabels > then_labels_list_
ZonePtrList< BytecodeLabels > else_labels_list_
ZoneVector< int > block_coverage_then_slots_
ZoneVector< int > block_coverage_else_slots_
BlockCoverageBuilder * block_coverage_builder_
Additional Inherited Members
Detailed Description
Definition at line 264 of file control-flow-builders.h.
Constructor & Destructor Documentation
ConditionalChainControlFlowBuilder()
v8::internal::interpreter::ConditionalChainControlFlowBuilder::ConditionalChainControlFlowBuilder (BytecodeArrayBuilder * builder, BlockCoverageBuilder * block_coverage_builder, AstNode * node, size_t then_count) [inline]
Definition at line 267 of file control-flow-builders.h.
      : ControlFlowBuilder(builder),
        end_labels_(builder->zone()),
        then_count_(then_count),
        then_labels_list_(static_cast<int>(then_count_), builder->zone()),
        else_labels_list_(static_cast<int>(then_count_), builder->zone()),
        block_coverage_then_slots_(then_count_, builder->zone()),
        block_coverage_else_slots_(then_count_, builder->zone()),
        block_coverage_builder_(block_coverage_builder) {
    DCHECK(node->IsConditionalChain());
    Zone* zone = builder->zone();
    for (size_t i = 0; i < then_count_; ++i) {
      then_labels_list_.Add(zone->New<BytecodeLabels>(zone), zone);
      else_labels_list_.Add(zone->New<BytecodeLabels>(zone), zone);
    }
    if (block_coverage_builder != nullptr) {
      ConditionalChain* conditional_chain = node->AsConditionalChain();
      block_coverage_then_slots_.resize(then_count_);
      block_coverage_else_slots_.resize(then_count_);
      for (size_t i = 0; i < then_count_; ++i) {
        block_coverage_then_slots_[i] =
            block_coverage_builder->AllocateConditionalChainBlockCoverageSlot(
                conditional_chain, SourceRangeKind::kThen, i);
        block_coverage_else_slots_[i] =
            block_coverage_builder->AllocateConditionalChainBlockCoverageSlot(
                conditional_chain, SourceRangeKind::kElse, i);
      }
    }
  }
References v8::internal::interpreter::BlockCoverageBuilder::AllocateConditionalChainBlockCoverageSlot(), v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::kElse, v8::internal::kThen, v8::internal::Zone::New(), and v8::internal::interpreter::BytecodeArrayBuilder::zone().
 ConditionalChainControlFlowBuilder()
v8::internal::interpreter::ConditionalChainControlFlowBuilder::~ConditionalChainControlFlowBuilder () [override]
Definition at line 213 of file control-flow-builders.cc.
                                                                        {
  end_labels_.Bind(builder());
#ifdef DEBUG
  DCHECK(end_labels_.empty() || end_labels_.is_bound());
  for (auto* label : then_labels_list_) {
    DCHECK(label->empty() || label->is_bound());
  }
  for (auto* label : else_labels_list_) {
    DCHECK(label->empty() || label->is_bound());
  }
#endif
}
References v8::internal::interpreter::BytecodeLabels::Bind(), v8::internal::interpreter::ControlFlowBuilder::builder(), v8::internal::DCHECK(), else_labels_list_, v8::internal::interpreter::BytecodeLabels::empty(), end_labels_, v8::internal::interpreter::BytecodeLabels::is_bound(), and then_labels_list_.
Member Function Documentation
block_coverage_else_slot_at()
int v8::internal::interpreter::ConditionalChainControlFlowBuilder::block_coverage_else_slot_at (size_t index) const [inline]
Definition at line 318 of file control-flow-builders.h.
                                                      {
    DCHECK_LT(index, then_count_);
    return block_coverage_else_slots_[index];
  }
References DCHECK_LT, and v8::internal::index.
Referenced by ElseAt().
block_coverage_then_slot_at()
int v8::internal::interpreter::ConditionalChainControlFlowBuilder::block_coverage_then_slot_at (size_t index) const [inline]
Definition at line 313 of file control-flow-builders.h.
                                                      {
    DCHECK_LT(index, then_count_);
    return block_coverage_then_slots_[index];
  }
References DCHECK_LT, and v8::internal::index.
Referenced by ThenAt().
else_labels_at()
BytecodeLabels* v8::internal::interpreter::ConditionalChainControlFlowBuilder::else_labels_at (size_t index) [inline]
Definition at line 308 of file control-flow-builders.h.
                                               {
    DCHECK_LT(index, then_count_);
    return else_labels_list_[static_cast<int>(index)];
  }
References DCHECK_LT, and v8::internal::index.
Referenced by ElseAt().
ElseAt()
void v8::internal::interpreter::ConditionalChainControlFlowBuilder::ElseAt (size_t index)
Definition at line 241 of file control-flow-builders.cc.
                                                            {
  DCHECK_LT(index, else_labels_list_.length());
  else_labels_at(index)->Bind(builder());
  if (block_coverage_builder_) {
    block_coverage_builder_->IncrementBlockCounter(
        block_coverage_else_slot_at(index));
  }
}
References v8::internal::interpreter::BytecodeLabels::Bind(), block_coverage_builder_, block_coverage_else_slot_at(), v8::internal::interpreter::ControlFlowBuilder::builder(), DCHECK_LT, else_labels_at(), else_labels_list_, v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter(), and v8::internal::index.
JumpToEnd()
void v8::internal::interpreter::ConditionalChainControlFlowBuilder::JumpToEnd ()
Definition at line 228 of file control-flow-builders.cc.
                                                   {
  builder()->Jump(end_labels_.New());
}
References v8::internal::interpreter::ControlFlowBuilder::builder(), end_labels_, v8::internal::interpreter::BytecodeArrayBuilder::Jump(), and v8::internal::interpreter::BytecodeLabels::New().
then_labels_at()
BytecodeLabels* v8::internal::interpreter::ConditionalChainControlFlowBuilder::then_labels_at (size_t index) [inline]
Definition at line 303 of file control-flow-builders.h.
                                               {
    DCHECK_LT(index, then_count_);
    return then_labels_list_[static_cast<int>(index)];
  }
References DCHECK_LT, and v8::internal::index.
Referenced by ThenAt().
ThenAt()
void v8::internal::interpreter::ConditionalChainControlFlowBuilder::ThenAt (size_t index)
Definition at line 232 of file control-flow-builders.cc.
                                                            {
  DCHECK_LT(index, then_labels_list_.length());
  then_labels_at(index)->Bind(builder());
  if (block_coverage_builder_) {
    block_coverage_builder_->IncrementBlockCounter(
        block_coverage_then_slot_at(index));
  }
}
References v8::internal::interpreter::BytecodeLabels::Bind(), block_coverage_builder_, block_coverage_then_slot_at(), v8::internal::interpreter::ControlFlowBuilder::builder(), DCHECK_LT, v8::internal::interpreter::BlockCoverageBuilder::IncrementBlockCounter(), v8::internal::index, then_labels_at(), and then_labels_list_.
Member Data Documentation
block_coverage_builder_
BlockCoverageBuilder* v8::internal::interpreter::ConditionalChainControlFlowBuilder::block_coverage_builder_ [private]
Definition at line 336 of file control-flow-builders.h.
Referenced by ElseAt(), and ThenAt().
block_coverage_else_slots_
ZoneVector<int> v8::internal::interpreter::ConditionalChainControlFlowBuilder::block_coverage_else_slots_ [private]
Definition at line 335 of file control-flow-builders.h.
block_coverage_then_slots_
ZoneVector<int> v8::internal::interpreter::ConditionalChainControlFlowBuilder::block_coverage_then_slots_ [private]
Definition at line 334 of file control-flow-builders.h.
else_labels_list_
ZonePtrList<BytecodeLabels> v8::internal::interpreter::ConditionalChainControlFlowBuilder::else_labels_list_ [private]
Definition at line 332 of file control-flow-builders.h.
Referenced by ElseAt(), and ~ConditionalChainControlFlowBuilder().
end_labels_
BytecodeLabels v8::internal::interpreter::ConditionalChainControlFlowBuilder::end_labels_ [private]
Definition at line 329 of file control-flow-builders.h.
Referenced by JumpToEnd(), and ~ConditionalChainControlFlowBuilder().
then_count_
size_t v8::internal::interpreter::ConditionalChainControlFlowBuilder::then_count_ [private]
Definition at line 330 of file control-flow-builders.h.
then_labels_list_
ZonePtrList<BytecodeLabels> v8::internal::interpreter::ConditionalChainControlFlowBuilder::then_labels_list_ [private]
Definition at line 331 of file control-flow-builders.h.
Referenced by ThenAt(), and ~ConditionalChainControlFlowBuilder().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/control-flow-builders.h
/mnt/V8SourceCode/src/interpreter/control-flow-builders.cc