v8::internal::MemoryController< Trait > Class Template Reference
#include <heap-controller.h>
Static Public Member Functions
static size_t MinimumAllocationLimitGrowingStep (Heap::HeapGrowingMode growing_mode)
static double GrowingFactor (Heap *heap, size_t max_heap_size, std::optional< double > gc_speed, double mutator_speed, Heap::HeapGrowingMode growing_mode)
static size_t BoundAllocationLimit (Heap *heap, size_t current_size, uint64_t limit, size_t min_size, size_t max_size, size_t new_space_capacity, Heap::HeapGrowingMode growing_mode)
Private Member Functions
FRIEND_TEST (MemoryControllerTest, HeapGrowingFactor)
FRIEND_TEST (MemoryControllerTest, MaxHeapGrowingFactor)
Static Private Member Functions
static double MaxGrowingFactor (size_t max_heap_size)
static double DynamicGrowingFactor (std::optional< double > gc_speed, double mutator_speed, double max_factor)
Detailed Description
template<typename Trait>
class v8::internal::MemoryController< Trait >
Definition at line 32 of file heap-controller.h.
Member Function Documentation
BoundAllocationLimit()
template<typename Trait >
size_t v8::internal::MemoryController< Trait >::BoundAllocationLimit (Heap * heap, size_t current_size, uint64_t limit, size_t min_size, size_t max_size, size_t new_space_capacity, Heap::HeapGrowingMode growing_mode) [static]
Definition at line 141 of file heap-controller.cc.
                                      {
  CHECK_LT(0, current_size);
  limit = std::max(limit, static_cast<uint64_t>(current_size) +
                              MinimumAllocationLimitGrowingStep(growing_mode)) +
          new_space_capacity;
  const uint64_t halfway_to_the_max =
      (static_cast<uint64_t>(current_size) + max_size) / 2;
  const uint64_t limit_or_halfway =
      std::min<uint64_t>(limit, halfway_to_the_max);
  const size_t result =
      static_cast<size_t>(std::max<uint64_t>(limit_or_halfway, min_size));
  if (V8_UNLIKELY(v8_flags.trace_gc_verbose)) {
    Isolate::FromHeap(heap)->PrintWithTimestamp(
        "[%s] Limit: old size: %zu KB, new limit: %zu KB\n", Trait::kName,
        current_size / KB, result / KB);
  }
  return result;
}
References CHECK_LT, v8::internal::Isolate::FromHeap(), v8::internal::KB, v8::internal::anonymous_namespace{ic.cc}::kName, v8::base::internal::result, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::Heap::ComputeNewAllocationLimits().
DynamicGrowingFactor()
template<typename Trait >
double v8::internal::MemoryController< Trait >::DynamicGrowingFactor (std::optional< double > gc_speed, double mutator_speed, double max_factor) [static], [private]
Definition at line 110 of file heap-controller.cc.
                                                                           {
  DCHECK_LE(Trait::kMinGrowingFactor, max_factor);
  DCHECK_GE(Trait::kMaxGrowingFactor, max_factor);
  if (!gc_speed || mutator_speed == 0) return max_factor;
  const double speed_ratio = *gc_speed / mutator_speed;
  const double a = speed_ratio * (1 - Trait::kTargetMutatorUtilization);
  const double b = speed_ratio * (1 - Trait::kTargetMutatorUtilization) -
                   Trait::kTargetMutatorUtilization;
  // The factor is a / b, but we need to check for small b first.
  double factor = (a < b * max_factor) ? a / b : max_factor;
  DCHECK_LE(factor, max_factor);
  factor = std::max({factor, Trait::kMinGrowingFactor});
  return factor;
}
References DCHECK_GE, and DCHECK_LE.
FRIEND_TEST() [1/2]
template<typename Trait >
v8::internal::MemoryController< Trait >::FRIEND_TEST (MemoryControllerTest , HeapGrowingFactor) [private]
FRIEND_TEST() [2/2]
template<typename Trait >
v8::internal::MemoryController< Trait >::FRIEND_TEST (MemoryControllerTest , MaxHeapGrowingFactor) [private]
GrowingFactor()
template<typename Trait >
double v8::internal::MemoryController< Trait >::GrowingFactor (Heap * heap, size_t max_heap_size, std::optional< double > gc_speed, double mutator_speed, Heap::HeapGrowingMode growing_mode) [static]
Definition at line 15 of file heap-controller.cc.
                                                            {
  const double max_factor = MaxGrowingFactor(max_heap_size);
  double factor = DynamicGrowingFactor(gc_speed, mutator_speed, max_factor);
  switch (growing_mode) {
    case Heap::HeapGrowingMode::kConservative:
    case Heap::HeapGrowingMode::kSlow:
      factor = std::min({factor, Trait::kConservativeGrowingFactor});
      break;
    case Heap::HeapGrowingMode::kMinimal:
      factor = Trait::kMinGrowingFactor;
      break;
    case Heap::HeapGrowingMode::kDefault:
      break;
  }
  if (v8_flags.heap_growing_percent > 0) {
    factor = 1.0 + v8_flags.heap_growing_percent / 100.0;
  }
  if (V8_UNLIKELY(v8_flags.trace_gc_verbose)) {
    Isolate::FromHeap(heap)->PrintWithTimestamp(
        "[%s] factor %.1f based on mu=%.3f, speed_ratio=%.f "
        "(gc=%.f, mutator=%.f)\n",
        Trait::kName, factor, Trait::kTargetMutatorUtilization,
        gc_speed.value_or(0) / mutator_speed, gc_speed.value_or(0),
        mutator_speed);
  }
  return factor;
}
References v8::internal::Isolate::FromHeap(), v8::internal::Heap::kConservative, v8::internal::Heap::kDefault, v8::internal::Heap::kMinimal, v8::internal::anonymous_namespace{ic.cc}::kName, v8::internal::Heap::kSlow, v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::Heap::ComputeNewAllocationLimits().
MaxGrowingFactor()
template<typename Trait >
double v8::internal::MemoryController< Trait >::MaxGrowingFactor (size_t max_heap_size) [static], [private]
Definition at line 46 of file heap-controller.cc.
                                                                     {
  constexpr double kMinSmallFactor = 1.3;
  constexpr double kMaxSmallFactor = 2.0;
  constexpr double kHighFactor = 4.0;
  // If we are on a device with lots of memory, we allow a high heap
  // growing factor.
  if (max_heap_size >= Heap::DefaulMaxHeapSize()) {
    return kHighFactor;
  }
  size_t max_size = std::max({max_heap_size, Heap::DefaulMinHeapSize()});
  DCHECK_GE(max_size, Heap::DefaulMinHeapSize());
  DCHECK_LT(max_size, Heap::DefaulMaxHeapSize());
  // On smaller devices we linearly scale the factor: C+(D-C)*(X-A)/(B-A)
  double factor = kMinSmallFactor +
                  (kMaxSmallFactor - kMinSmallFactor) *
                      (max_size - Heap::DefaulMinHeapSize()) /
                      (Heap::DefaulMaxHeapSize() - Heap::DefaulMinHeapSize());
  return factor;
}
References DCHECK_GE, DCHECK_LT, v8::internal::Heap::DefaulMaxHeapSize(), and v8::internal::Heap::DefaulMinHeapSize().
MinimumAllocationLimitGrowingStep()
template<typename Trait >
size_t v8::internal::MemoryController< Trait >::MinimumAllocationLimitGrowingStep (Heap::HeapGrowingMode growing_mode) [static]
Definition at line 130 of file heap-controller.cc.
                                      {
  const size_t kRegularAllocationLimitGrowingStep = 8;
  const size_t kLowMemoryAllocationLimitGrowingStep = 2;
  size_t limit = (PageMetadata::kPageSize > MB ? PageMetadata::kPageSize : MB);
  return limit * (growing_mode == Heap::HeapGrowingMode::kConservative
                      ? kLowMemoryAllocationLimitGrowingStep
                      : kRegularAllocationLimitGrowingStep);
}
References v8::internal::Heap::kConservative, v8::internal::MutablePageMetadata::kPageSize, and v8::internal::MB.
Referenced by v8::internal::Heap::ShrinkOldGenerationAllocationLimitIfNotConfigured().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/heap-controller.h
/mnt/V8SourceCode/src/heap/heap-controller.cc