v8::internal::CaseClause Class Reference
#include <ast.h>
Public Member Functions
bool is_default () const
Expression * label () const
ZonePtrList< Statement > * statements ()
Private Member Functions
CaseClause (Zone *zone, Expression *label, const ScopedPtrList< Statement > &statements)
Private Attributes
friend Zone
Expression * label_
ZonePtrList< Statement > statements_
Friends
class AstNodeFactory
Detailed Description
Definition at line 700 of file ast.h.
Constructor & Destructor Documentation
CaseClause()
v8::internal::CaseClause::CaseClause (Zone * zone, Expression * label, const ScopedPtrList< Statement > & statements) [private]
Definition at line 1022 of file ast.cc.
    : label_(label), statements_(statements.ToConstVector(), zone) {}
Member Function Documentation
is_default()
bool v8::internal::CaseClause::is_default () const [inline]
Definition at line 702 of file ast.h.
{ return label_ == nullptr; }
References label_.
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSwitchOptimizable(), and label().
label()
Expression* v8::internal::CaseClause::label () const [inline]
Definition at line 703 of file ast.h.
                            {
    DCHECK(!is_default());
    return label_;
  }
References v8::internal::DCHECK(), is_default(), and label_.
Referenced by v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::SwitchInfo::IsDuplicate(), and v8::internal::interpreter::anonymous_namespace{bytecode-generator.cc}::IsSwitchOptimizable().
statements()
ZonePtrList<Statement>* v8::internal::CaseClause::statements () [inline]
Definition at line 707 of file ast.h.
{ return &statements_; }
References statements_.
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 710 of file ast.h.
Member Data Documentation
label_
Expression* v8::internal::CaseClause::label_ [private]
Definition at line 716 of file ast.h.
Referenced by is_default(), and label().
statements_
ZonePtrList<Statement> v8::internal::CaseClause::statements_ [private]
Definition at line 717 of file ast.h.
Referenced by statements().
Zone
friend v8::internal::CaseClause::Zone [private]
Definition at line 711 of file ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc