v8::internal::maglev::SaveRegisterStateForCall Class Reference
#include <maglev-assembler.h>
Public Member Functions
SaveRegisterStateForCall (MaglevAssembler *masm, RegisterSnapshot snapshot)
~SaveRegisterStateForCall ()
void DefineSafepoint ()
void DefineSafepointWithLazyDeopt (LazyDeoptInfo *lazy_deopt_info)
Private Attributes
MaglevAssembler * masm
RegisterSnapshot snapshot_
Detailed Description
Definition at line 946 of file maglev-assembler.h.
Constructor & Destructor Documentation
SaveRegisterStateForCall()
v8::internal::maglev::SaveRegisterStateForCall::SaveRegisterStateForCall (MaglevAssembler * masm, RegisterSnapshot snapshot) [inline]
Definition at line 948 of file maglev-assembler.h.
      : masm(masm), snapshot_(snapshot) {
    masm->PushAll(snapshot_.live_registers);
    masm->PushAll(snapshot_.live_double_registers, kDoubleSize);
  }
References v8::internal::kDoubleSize, v8::internal::maglev::RegisterSnapshot::live_double_registers, v8::internal::maglev::RegisterSnapshot::live_registers, masm, v8::internal::MacroAssembler::PushAll(), and snapshot_.
 SaveRegisterStateForCall()
v8::internal::maglev::SaveRegisterStateForCall::~SaveRegisterStateForCall () [inline]
Definition at line 954 of file maglev-assembler.h.
                              {
    masm->PopAll(snapshot_.live_double_registers, kDoubleSize);
    masm->PopAll(snapshot_.live_registers);
  }
References v8::internal::kDoubleSize, v8::internal::maglev::RegisterSnapshot::live_double_registers, v8::internal::maglev::RegisterSnapshot::live_registers, masm, v8::internal::MacroAssembler::PopAll(), and snapshot_.
Member Function Documentation
DefineSafepoint()
void v8::internal::maglev::SaveRegisterStateForCall::DefineSafepoint () [inline]
Definition at line 959 of file maglev-assembler.h.
                         {
    // TODO(leszeks): Avoid emitting safepoints when there are no registers to
    // save.
    auto safepoint = masm->safepoint_table_builder()->DefineSafepoint(masm);
    int pushed_reg_index = 0;
    for (Register reg : snapshot_.live_registers) {
      if (snapshot_.live_tagged_registers.has(reg)) {
        safepoint.DefineTaggedRegister(pushed_reg_index);
      }
      pushed_reg_index++;
    }
#ifdef V8_TARGET_ARCH_ARM64
    pushed_reg_index = RoundUp<2>(pushed_reg_index);
#endif
    int num_double_slots = snapshot_.live_double_registers.Count() *
                           (kDoubleSize / kSystemPointerSize);
#ifdef V8_TARGET_ARCH_ARM64
    num_double_slots = RoundUp<2>(num_double_slots);
#endif
    safepoint.SetNumExtraSpillSlots(pushed_reg_index + num_double_slots);
  }
References v8::internal::RegListBase< RegisterT >::Count(), v8::internal::MaglevSafepointTableBuilder::DefineSafepoint(), v8::internal::MaglevSafepointTableBuilder::Safepoint::DefineTaggedRegister(), v8::internal::RegListBase< RegisterT >::has(), v8::internal::kDoubleSize, v8::internal::kSystemPointerSize, v8::internal::maglev::RegisterSnapshot::live_double_registers, v8::internal::maglev::RegisterSnapshot::live_registers, v8::internal::maglev::RegisterSnapshot::live_tagged_registers, masm, v8::internal::maglev::MaglevAssembler::safepoint_table_builder(), and snapshot_.
Referenced by v8::internal::maglev::AllocateSlow(), DefineSafepointWithLazyDeopt(), v8::internal::maglev::MaglevAssembler::EnsureWritableFastElements(), v8::internal::maglev::anonymous_namespace{maglev-ir-x64.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-riscv.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-s390.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::MaglevAssembler::StringCharCodeOrCodePointAt(), v8::internal::maglev::MaglevAssembler::TryMigrateInstance(), and v8::internal::maglev::MaglevAssembler::TryMigrateInstanceAndMarkMapAsMigrationTarget().
DefineSafepointWithLazyDeopt()
void v8::internal::maglev::SaveRegisterStateForCall::DefineSafepointWithLazyDeopt (LazyDeoptInfo * lazy_deopt_info) [inline]
Definition at line 1101 of file maglev-assembler-inl.h.
                                    {
  lazy_deopt_info->set_deopting_call_return_pc(masm->pc_offset_for_safepoint());
  masm->code_gen_state()->PushLazyDeopt(lazy_deopt_info);
  DefineSafepoint();
  masm->MaybeEmitPlaceHolderForDeopt();
}
References v8::internal::maglev::MaglevAssembler::code_gen_state(), DefineSafepoint(), masm, v8::internal::maglev::MaglevAssembler::MaybeEmitPlaceHolderForDeopt(), v8::internal::Assembler::pc_offset_for_safepoint(), v8::internal::maglev::MaglevCodeGenState::PushLazyDeopt(), and v8::internal::maglev::LazyDeoptInfo::set_deopting_call_return_pc().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-ir-x64.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-arm64.cc}::HandleInterruptsAndTiering(), v8::internal::maglev::anonymous_namespace{maglev-ir-riscv.cc}::HandleInterruptsAndTiering(), and v8::internal::maglev::anonymous_namespace{maglev-ir-s390.cc}::HandleInterruptsAndTiering().
Member Data Documentation
masm
MaglevAssembler* v8::internal::maglev::SaveRegisterStateForCall::masm [private]
Definition at line 984 of file maglev-assembler.h.
Referenced by DefineSafepoint(), DefineSafepointWithLazyDeopt(), SaveRegisterStateForCall(), and ~SaveRegisterStateForCall().
snapshot_
RegisterSnapshot v8::internal::maglev::SaveRegisterStateForCall::snapshot_ [private]
Definition at line 985 of file maglev-assembler.h.
Referenced by DefineSafepoint(), SaveRegisterStateForCall(), and ~SaveRegisterStateForCall().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/maglev/maglev-assembler.h
/mnt/V8SourceCode/src/maglev/maglev-assembler-inl.h