v8::internal::JSFinalizationRegistry Class Reference
#include <js-weak-refs.h>
Classes
class BodyDescriptor
Public Types
enum RemoveUnregisterTokenMode { kRemoveMatchedCellsFromRegistry
, kKeepMatchedCellsInRegistry
 }
Public Member Functions
template<typename GCNotifyUpdatedSlotCallback >
bool RemoveUnregisterToken (Tagged< HeapObject > unregister_token, Isolate *isolate, RemoveUnregisterTokenMode removal_mode, GCNotifyUpdatedSlotCallback gc_notify_updated_slot)
bool NeedsCleanup () const
V8_EXPORT_PRIVATE Tagged< WeakCell > PopClearedCell (Isolate *isolate, bool *key_map_may_need_shrink)
V8_EXPORT_PRIVATE void RemoveCellFromUnregisterTokenMap (Isolate *isolate, Tagged< WeakCell > weak_cell)
Static Public Member Functions
static void RegisterWeakCellWithUnregisterToken (DirectHandle< JSFinalizationRegistry > finalization_registry, DirectHandle< WeakCell > weak_cell, Isolate *isolate)
static bool Unregister (DirectHandle< JSFinalizationRegistry > finalization_registry, DirectHandle< HeapObject > unregister_token, Isolate *isolate)
static void ShrinkKeyMap (Isolate *isolate, DirectHandle< JSFinalizationRegistry > finalization_registry)
static Maybe< bool > Cleanup (Isolate *isolate, DirectHandle< JSFinalizationRegistry > finalization_registry)
Detailed Description
Definition at line 24 of file js-weak-refs.h.
Member Enumeration Documentation
RemoveUnregisterTokenMode
enum v8::internal::JSFinalizationRegistry::RemoveUnregisterTokenMode
Enumerator
kRemoveMatchedCellsFromRegistry
kKeepMatchedCellsInRegistry
Definition at line 46 of file js-weak-refs.h.
                                 {
    kRemoveMatchedCellsFromRegistry,
    kKeepMatchedCellsInRegistry
  };
Member Function Documentation
Cleanup()
Maybe< bool > v8::internal::JSFinalizationRegistry::Cleanup (Isolate * isolate, DirectHandle< JSFinalizationRegistry > finalization_registry) [static]
Definition at line 50 of file js-weak-refs.cc.
                                                                {
  // 1. Assert: finalizationRegistry has [[Cells]] and [[CleanupCallback]]
  // internal slots.
  // (By construction.)
  // 2. Let callback be finalizationRegistry.[[CleanupCallback]].
  DirectHandle<Object> callback(finalization_registry->cleanup(), isolate);
  // 3. While finalizationRegistry.[[Cells]] contains a Record cell such that
  // cell.[[WeakRefTarget]] is empty, an implementation may perform the
  // following steps:
  bool key_map_may_need_shrink = false;
  while (finalization_registry->NeedsCleanup()) {
    HandleScope scope(isolate);
    // a. Choose any such cell.
    // b. Remove cell from finalizationRegistry.[[Cells]].
    DirectHandle<WeakCell> weak_cell(finalization_registry->PopClearedCell(
                                         isolate, &key_map_may_need_shrink),
                                     isolate);
    // c. Perform ? HostCallJobCallback(callback, undefined,
    // « cell.[[HeldValue]] »).
    DirectHandle<Object> args[] = {
        direct_handle(weak_cell->holdings(), isolate)};
    if (Execution::Call(isolate, callback,
                        isolate->factory()->undefined_value(),
                        base::VectorOf(args))
            .is_null()) {
      if (key_map_may_need_shrink) ShrinkKeyMap(isolate, finalization_registry);
      return Nothing<bool>();
    }
  }
  if (key_map_may_need_shrink) ShrinkKeyMap(isolate, finalization_registry);
  return Just(true);
}
References v8::base::args, v8::internal::Execution::Call(), v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::Just(), ShrinkKeyMap(), and v8::base::VectorOf().
Referenced by v8::internal::InvokeFinalizationRegistryCleanupFromTask().
NeedsCleanup()
bool v8::internal::JSFinalizationRegistry::NeedsCleanup () const [inline]
Definition at line 157 of file js-weak-refs-inl.h.
                                                {
  return IsWeakCell(cleared_cells());
}
PopClearedCell()
Tagged< WeakCell > v8::internal::JSFinalizationRegistry::PopClearedCell (Isolate * isolate, bool * key_map_may_need_shrink)
Definition at line 13 of file js-weak-refs.cc.
                                                     {
  DisallowGarbageCollection no_gc;
  Tagged<Undefined> undefined = ReadOnlyRoots(isolate).undefined_value();
  Tagged<WeakCell> head = Cast<WeakCell>(cleared_cells());
  DCHECK(IsUndefined(head->prev(), isolate));
  Tagged<Union<Undefined, WeakCell>> tail = head->next();
  head->set_next(undefined);
  if (IsWeakCell(tail)) Cast<WeakCell>(tail)->set_prev(undefined);
  set_cleared_cells(tail);
  // If the WeakCell has an unregister token, remove the cell from the
  // unregister token linked lists and and the unregister token from key_map.
  // This doesn't shrink key_map, which is done manually after the cleanup loop.
  if (!IsUndefined(head->unregister_token(), isolate)) {
    RemoveCellFromUnregisterTokenMap(isolate, head);
    *key_map_may_need_shrink = true;
  }
  return head;
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, RemoveCellFromUnregisterTokenMap(), and v8::internal::undefined.
RegisterWeakCellWithUnregisterToken()
static void v8::internal::JSFinalizationRegistry::RegisterWeakCellWithUnregisterToken (DirectHandle< JSFinalizationRegistry > finalization_registry, DirectHandle< WeakCell > weak_cell, Isolate * isolate) [inline], [static]
Referenced by v8::internal::RUNTIME_FUNCTION().
RemoveCellFromUnregisterTokenMap()
void v8::internal::JSFinalizationRegistry::RemoveCellFromUnregisterTokenMap (Isolate * isolate, Tagged< WeakCell > weak_cell)
Definition at line 90 of file js-weak-refs.cc.
                                                  {
  DisallowGarbageCollection no_gc;
  DCHECK(!IsUndefined(weak_cell->unregister_token(), isolate));
  Tagged<Undefined> undefined = ReadOnlyRoots(isolate).undefined_value();
  // Remove weak_cell from the linked list of other WeakCells with the same
  // unregister token and remove its unregister token from key_map if necessary
  // without shrinking it. Since shrinking may allocate, it is performed by the
  // caller after looping, or on exception.
  if (IsUndefined(weak_cell->key_list_prev(), isolate)) {
    Tagged<SimpleNumberDictionary> key_map =
        Cast<SimpleNumberDictionary>(this->key_map());
    Tagged<HeapObject> unregister_token = weak_cell->unregister_token();
    uint32_t key = Smi::ToInt(Object::GetHash(unregister_token));
    InternalIndex entry = key_map->FindEntry(isolate, key);
    CHECK(entry.is_found());
    if (IsUndefined(weak_cell->key_list_next(), isolate)) {
      // weak_cell is the only one associated with its key; remove the key
      // from the hash table.
      key_map->ClearEntry(entry);
      key_map->ElementRemoved();
    } else {
      // weak_cell is the list head for its key; we need to change the value
      // of the key in the hash table.
      Tagged<WeakCell> next = Cast<WeakCell>(weak_cell->key_list_next());
      DCHECK_EQ(next->key_list_prev(), weak_cell);
      next->set_key_list_prev(undefined);
      key_map->ValueAtPut(entry, next);
    }
  } else {
    // weak_cell is somewhere in the middle of its key list.
    Tagged<WeakCell> prev = Cast<WeakCell>(weak_cell->key_list_prev());
    prev->set_key_list_next(weak_cell->key_list_next());
    if (!IsUndefined(weak_cell->key_list_next())) {
      Tagged<WeakCell> next = Cast<WeakCell>(weak_cell->key_list_next());
      next->set_key_list_prev(weak_cell->key_list_prev());
    }
  }
  // weak_cell is now removed from the unregister token map, so clear its
  // unregister token-related fields.
  weak_cell->set_unregister_token(undefined);
  weak_cell->set_key_list_prev(undefined);
  weak_cell->set_key_list_next(undefined);
}
References CHECK, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Object::GetHash(), v8::internal::InternalIndex::is_found(), v8::internal::key, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Smi::ToInt(), and v8::internal::undefined.
Referenced by PopClearedCell().
RemoveUnregisterToken()
template<typename GCNotifyUpdatedSlotCallback >
bool v8::internal::JSFinalizationRegistry::RemoveUnregisterToken (Tagged< HeapObject > unregister_token, Isolate * isolate, RemoveUnregisterTokenMode removal_mode, GCNotifyUpdatedSlotCallback gc_notify_updated_slot) [inline]
Definition at line 71 of file js-weak-refs-inl.h.
                                                        {
  // This method is called from both FinalizationRegistry#unregister and for
  // removing weakly-held dead unregister tokens. The latter is during GC so
  // this function cannot GC.
  DisallowGarbageCollection no_gc;
  if (IsUndefined(key_map(), isolate)) {
    return false;
  }
  Tagged<SimpleNumberDictionary> key_map =
      Cast<SimpleNumberDictionary>(this->key_map());
  // If the token doesn't have a hash, it was not used as a key inside any hash
  // tables.
  Tagged<Object> hash = Object::GetHash(unregister_token);
  if (IsUndefined(hash, isolate)) {
    return false;
  }
  uint32_t key = Smi::ToInt(hash);
  InternalIndex entry = key_map->FindEntry(isolate, key);
  if (entry.is_not_found()) {
    return false;
  }
  Tagged<Object> value = key_map->ValueAt(entry);
  bool was_present = false;
  Tagged<Undefined> undefined = ReadOnlyRoots(isolate).undefined_value();
  Tagged<UnionOf<Undefined, WeakCell>> new_key_list_head = undefined;
  Tagged<UnionOf<Undefined, WeakCell>> new_key_list_prev = undefined;
  // Compute a new key list that doesn't have unregister_token. Because
  // unregister tokens are held weakly, key_map is keyed using the tokens'
  // identity hashes, and identity hashes may collide.
  while (!IsUndefined(value, isolate)) {
    Tagged<WeakCell> weak_cell = Cast<WeakCell>(value);
    DCHECK(!HeapLayout::InYoungGeneration(weak_cell));
    value = weak_cell->key_list_next();
    if (weak_cell->unregister_token() == unregister_token) {
      // weak_cell has the same unregister token; remove it from the key list.
      switch (removal_mode) {
        case kRemoveMatchedCellsFromRegistry:
          weak_cell->RemoveFromFinalizationRegistryCells(isolate);
          break;
        case kKeepMatchedCellsInRegistry:
          // Do nothing.
          break;
      }
      // Clear unregister token-related fields.
      weak_cell->set_unregister_token(undefined);
      weak_cell->set_key_list_prev(undefined);
      weak_cell->set_key_list_next(undefined);
      was_present = true;
    } else {
      // weak_cell has a different unregister token with the same key (hash
      // collision); fix up the list.
      weak_cell->set_key_list_prev(new_key_list_prev);
      gc_notify_updated_slot(weak_cell,
                             weak_cell->RawField(WeakCell::kKeyListPrevOffset),
                             new_key_list_prev);
      weak_cell->set_key_list_next(undefined);
      if (IsUndefined(new_key_list_prev, isolate)) {
        new_key_list_head = weak_cell;
      } else {
        DCHECK(IsWeakCell(new_key_list_head));
        Tagged<WeakCell> prev_cell = Cast<WeakCell>(new_key_list_prev);
        prev_cell->set_key_list_next(weak_cell);
        gc_notify_updated_slot(
            prev_cell, prev_cell->RawField(WeakCell::kKeyListNextOffset),
            weak_cell);
      }
      new_key_list_prev = weak_cell;
    }
  }
  if (IsUndefined(new_key_list_head, isolate)) {
    DCHECK(was_present);
    key_map->ClearEntry(entry);
    key_map->ElementRemoved();
  } else {
    key_map->ValueAtPut(entry, new_key_list_head);
    gc_notify_updated_slot(key_map, key_map->RawFieldOfValueAt(entry),
                           new_key_list_head);
  }
  return was_present;
}
References v8::internal::DCHECK(), v8::internal::Object::GetHash(), v8::internal::HeapLayout::InYoungGeneration(), v8::internal::InternalIndex::is_not_found(), v8::internal::key, kKeepMatchedCellsInRegistry, kRemoveMatchedCellsFromRegistry, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Smi::ToInt(), v8::internal::undefined, and v8::internal::value.
ShrinkKeyMap()
void v8::internal::JSFinalizationRegistry::ShrinkKeyMap (Isolate * isolate, DirectHandle< JSFinalizationRegistry > finalization_registry) [static]
Definition at line 36 of file js-weak-refs.cc.
                                                                {
  if (!IsUndefined(finalization_registry->key_map(), isolate)) {
    Handle<SimpleNumberDictionary> key_map =
        handle(Cast<SimpleNumberDictionary>(finalization_registry->key_map()),
               isolate);
    key_map = SimpleNumberDictionary::Shrink(isolate, key_map);
    finalization_registry->set_key_map(*key_map);
  }
}
References v8::internal::handle(), and cppgc::internal::anonymous_namespace{explicit-management.cc}::Shrink().
Referenced by Cleanup().
Unregister()
bool v8::internal::JSFinalizationRegistry::Unregister (DirectHandle< JSFinalizationRegistry > finalization_registry, DirectHandle< HeapObject > unregister_token, Isolate * isolate) [inline], [static]
Definition at line 59 of file js-weak-refs-inl.h.
                                                                 {
  // Iterate through the doubly linked list of WeakCells associated with the
  // key. Each WeakCell will be in the "active_cells" or "cleared_cells" list of
  // its FinalizationRegistry; remove it from there.
  return finalization_registry->RemoveUnregisterToken(
      *unregister_token, isolate, kRemoveMatchedCellsFromRegistry,
      [](Tagged<HeapObject>, ObjectSlot, Tagged<Object>) {});
}
References kRemoveMatchedCellsFromRegistry.
Referenced by v8::internal::BUILTIN().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/js-weak-refs.h
/mnt/V8SourceCode/src/objects/js-weak-refs-inl.h
/mnt/V8SourceCode/src/objects/js-weak-refs.cc