v8::internal::BaselineFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const override
int GetBytecodeOffset () const override
intptr_t GetPCForBytecodeOffset (int lookup_offset) const
void PatchContext (Tagged< Context > value)
Static Public Member Functions
static BaselineFrame * cast (StackFrame *frame)
static const BaselineFrame * cast (const StackFrame *frame)
Protected Member Functions
BaselineFrame (StackFrameIteratorBase *iterator)
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 1164 of file frames.h.
Constructor & Destructor Documentation
BaselineFrame()
v8::internal::BaselineFrame::BaselineFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 312 of file frames-inl.h.
    : UnoptimizedJSFrame(iterator) {}
Member Function Documentation
cast() [1/2]
static const BaselineFrame* v8::internal::BaselineFrame::cast (const StackFrame * frame) [inline], [static]
Definition at line 1179 of file frames.h.
                                                            {
    DCHECK(frame->is_baseline());
    return static_cast<const BaselineFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_baseline().
cast() [2/2]
static BaselineFrame* v8::internal::BaselineFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 1175 of file frames.h.
                                                {
    DCHECK(frame->is_baseline());
    return static_cast<BaselineFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_baseline().
Referenced by v8::internal::JavaScriptFrame::GetActiveCodeAndOffset(), and v8::internal::Isolate::UnwindAndFindHandler().
GetBytecodeOffset()
int v8::internal::BaselineFrame::GetBytecodeOffset () const [override], [virtual]
Implements v8::internal::UnoptimizedJSFrame.
Definition at line 3350 of file frames.cc.
                                           {
  Tagged<Code> code = LookupCode();
  return code->GetBytecodeOffsetForBaselinePC(this->pc(), GetBytecodeArray());
}
References code.
Referenced by v8::internal::JavaScriptFrame::GetActiveCodeAndOffset().
GetPCForBytecodeOffset()
intptr_t v8::internal::BaselineFrame::GetPCForBytecodeOffset (int lookup_offset) const
Definition at line 3355 of file frames.cc.
                                                                        {
  Tagged<Code> code = LookupCode();
  return code->GetBaselineStartPCForBytecodeOffset(bytecode_offset,
                                                   GetBytecodeArray());
}
References code.
Referenced by v8::internal::Isolate::UnwindAndFindHandler().
PatchContext()
void v8::internal::BaselineFrame::PatchContext (Tagged< Context > value)
Definition at line 3361 of file frames.cc.
                                                      {
  base::Memory<Address>(fp() + BaselineFrameConstants::kContextOffset) =
      value.ptr();
}
References v8::internal::StandardFrameConstants::kContextOffset, and v8::internal::value.
Referenced by v8::internal::Isolate::UnwindAndFindHandler().
type()
Type v8::internal::BaselineFrame::type () const [inline], [override], [virtual]
Implements v8::internal::JavaScriptFrame.
Definition at line 1166 of file frames.h.
{ return BASELINE; }
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 1188 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc