v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler Class Reference
Public Member Functions
BytecodeAssembler (Zone *zone)
ZoneList< RegExpInstruction > IntoCode () &&
void Accept ()
void Assertion (RegExpAssertion::Type t)
void ClearRegister (int32_t register_index)
void ConsumeRange (base::uc16 from, base::uc16 to)
void ConsumeAnyChar ()
void RangeCount (int32_t num_ranges)
void Fork (Label &target)
void Jmp (Label &target)
void SetRegisterToCp (int32_t register_index)
void BeginLoop ()
void EndLoop ()
void StartLookaround (int lookaround_index, bool is_positive, RegExpLookaround::Type type)
void EndLookaround ()
void WriteLookaroundTable (int index)
void ReadLookaroundTable (int index, bool is_positive, RegExpLookaround::Type type)
void SetQuantifierToClock (int32_t quantifier_id)
void FilterQuantifier (int32_t quantifier_id)
void FilterGroup (int32_t group_id)
void FilterLookaround (int32_t lookaround_id)
void FilterChild (Label &target)
void Bind (Label &target)
void Fail ()
Private Member Functions
void LabelledInstrImpl (RegExpInstruction::Opcode op, Label &target)
Private Attributes
Zone * zone_
ZoneList< RegExpInstruction > code_
Detailed Description
Definition at line 258 of file experimental-compiler.cc.
Constructor & Destructor Documentation
BytecodeAssembler()
v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::BytecodeAssembler (Zone * zone) [inline], [explicit]
Definition at line 262 of file experimental-compiler.cc.
: zone_(zone), code_(0, zone) {}
Member Function Documentation
Accept()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Accept () [inline]
Definition at line 266 of file experimental-compiler.cc.
{ code_.Add(RegExpInstruction::Accept(), zone_); }
References v8::internal::RegExpInstruction::Accept().
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::Compile().
Assertion()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Assertion (RegExpAssertion::Type t) [inline]
Definition at line 268 of file experimental-compiler.cc.
                                        {
    code_.Add(RegExpInstruction::Assertion(t), zone_);
  }
References v8::internal::RegExpInstruction::Assertion().
BeginLoop()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::BeginLoop () [inline]
Definition at line 300 of file experimental-compiler.cc.
{ code_.Add(RegExpInstruction::BeginLoop(), zone_); }
References v8::internal::RegExpInstruction::BeginLoop().
Bind()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Bind (Label & target) [inline]
Definition at line 343 of file experimental-compiler.cc.
                           {
    DCHECK_EQ(target.state_, Label::UNBOUND);
    int index = code_.length();
    while (target.unbound_patch_list_begin_ != -1) {
      RegExpInstruction& inst = code_[target.unbound_patch_list_begin_];
      DCHECK(inst.opcode == RegExpInstruction::FORK ||
             inst.opcode == RegExpInstruction::JMP ||
             inst.opcode == RegExpInstruction::FILTER_CHILD);
      target.unbound_patch_list_begin_ = inst.payload.pc;
      inst.payload.pc = index;
    }
    target.state_ = Label::BOUND;
    target.bound_index_ = index;
  }
References v8::internal::anonymous_namespace{experimental-compiler.cc}::Label::bound_index_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::RegExpInstruction::FILTER_CHILD, v8::internal::RegExpInstruction::FORK, v8::internal::index, v8::internal::RegExpInstruction::JMP, v8::internal::RegExpInstruction::opcode, v8::internal::RegExpInstruction::payload, v8::internal::RegExpInstruction::pc, v8::internal::anonymous_namespace{experimental-compiler.cc}::Label::state_, and v8::internal::anonymous_namespace{experimental-compiler.cc}::Label::unbound_patch_list_begin_.
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::FilterGroupsCompileVisitor::CompileFilter().
ClearRegister()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::ClearRegister (int32_t register_index) [inline]
Definition at line 272 of file experimental-compiler.cc.
                                             {
    code_.Add(RegExpInstruction::ClearRegister(register_index), zone_);
  }
References v8::internal::RegExpInstruction::ClearRegister().
ConsumeAnyChar()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::ConsumeAnyChar () [inline]
Definition at line 280 of file experimental-compiler.cc.
                        {
    code_.Add(RegExpInstruction::ConsumeAnyChar(), zone_);
  }
References v8::internal::RegExpInstruction::ConsumeAnyChar().
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::Compile().
ConsumeRange()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::ConsumeRange (base::uc16 from, base::uc16 to) [inline]
Definition at line 276 of file experimental-compiler.cc.
                                                {
    code_.Add(RegExpInstruction::ConsumeRange(from, to), zone_);
  }
References v8::internal::RegExpInstruction::ConsumeRange().
EndLookaround()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::EndLookaround () [inline]
Definition at line 311 of file experimental-compiler.cc.
{ code_.Add(RegExpInstruction::EndLookaround(), zone_); }
References v8::internal::RegExpInstruction::EndLookaround().
EndLoop()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::EndLoop () [inline]
Definition at line 302 of file experimental-compiler.cc.
{ code_.Add(RegExpInstruction::EndLoop(), zone_); }
References v8::internal::RegExpInstruction::EndLoop().
Fail()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Fail () [inline]
Definition at line 362 of file experimental-compiler.cc.
{ code_.Add(RegExpInstruction::Fail(), zone_); }
References v8::internal::RegExpInstruction::Fail().
FilterChild()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::FilterChild (Label & target) [inline]
Definition at line 339 of file experimental-compiler.cc.
                                  {
    LabelledInstrImpl(RegExpInstruction::Opcode::FILTER_CHILD, target);
  }
FilterGroup()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::FilterGroup (int32_t group_id) [inline]
Definition at line 331 of file experimental-compiler.cc.
                                     {
    code_.Add(RegExpInstruction::FilterGroup(group_id), zone_);
  }
References v8::internal::RegExpInstruction::FilterGroup().
FilterLookaround()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::FilterLookaround (int32_t lookaround_id) [inline]
Definition at line 335 of file experimental-compiler.cc.
                                               {
    code_.Add(RegExpInstruction::FilterLookaround(lookaround_id), zone_);
  }
References v8::internal::RegExpInstruction::FilterLookaround().
FilterQuantifier()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::FilterQuantifier (int32_t quantifier_id) [inline]
Definition at line 327 of file experimental-compiler.cc.
                                               {
    code_.Add(RegExpInstruction::FilterQuantifier(quantifier_id), zone_);
  }
References v8::internal::RegExpInstruction::FilterQuantifier().
Fork()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Fork (Label & target) [inline]
Definition at line 288 of file experimental-compiler.cc.
                           {
    LabelledInstrImpl(RegExpInstruction::Opcode::FORK, target);
  }
IntoCode()
ZoneList<RegExpInstruction> v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::IntoCode () && [inline]
Definition at line 264 of file experimental-compiler.cc.
{ return std::move(code_); }
Jmp()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::Jmp (Label & target) [inline]
Definition at line 292 of file experimental-compiler.cc.
                          {
    LabelledInstrImpl(RegExpInstruction::Opcode::JMP, target);
  }
LabelledInstrImpl()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::LabelledInstrImpl (RegExpInstruction::Opcode op, Label & target) [inline], [private]
Definition at line 365 of file experimental-compiler.cc.
                                                                    {
    RegExpInstruction result;
    result.opcode = op;
    if (target.state_ == Label::BOUND) {
      result.payload.pc = target.bound_index_;
    } else {
      DCHECK_EQ(target.state_, Label::UNBOUND);
      int new_list_begin = code_.length();
      DCHECK_GE(new_list_begin, 0);
      result.payload.pc = target.unbound_patch_list_begin_;
      target.unbound_patch_list_begin_ = new_list_begin;
    }
    code_.Add(result, zone_);
  }
References v8::internal::anonymous_namespace{experimental-compiler.cc}::Label::bound_index_, DCHECK_EQ, DCHECK_GE, v8::base::internal::result, v8::internal::anonymous_namespace{experimental-compiler.cc}::Label::state_, and v8::internal::anonymous_namespace{experimental-compiler.cc}::Label::unbound_patch_list_begin_.
RangeCount()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::RangeCount (int32_t num_ranges) [inline]
Definition at line 284 of file experimental-compiler.cc.
                                      {
    code_.Add(RegExpInstruction::RangeCount(num_ranges), zone_);
  }
References v8::internal::RegExpInstruction::RangeCount().
ReadLookaroundTable()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::ReadLookaroundTable (int index, bool is_positive, RegExpLookaround::Type type) [inline]
Definition at line 317 of file experimental-compiler.cc.
                                                      {
    code_.Add(RegExpInstruction::ReadLookTable(index, is_positive, type),
              zone_);
  }
References v8::internal::index, v8::internal::RegExpInstruction::ReadLookTable(), and v8::internal::tracing::type.
SetQuantifierToClock()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::SetQuantifierToClock (int32_t quantifier_id) [inline]
Definition at line 323 of file experimental-compiler.cc.
                                                   {
    code_.Add(RegExpInstruction::SetQuantifierToClock(quantifier_id), zone_);
  }
References v8::internal::RegExpInstruction::SetQuantifierToClock().
SetRegisterToCp()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::SetRegisterToCp (int32_t register_index) [inline]
Definition at line 296 of file experimental-compiler.cc.
                                               {
    code_.Add(RegExpInstruction::SetRegisterToCp(register_index), zone_);
  }
References v8::internal::RegExpInstruction::SetRegisterToCp().
Referenced by v8::internal::anonymous_namespace{experimental-compiler.cc}::CompileVisitor::Compile().
StartLookaround()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::StartLookaround (int lookaround_index, bool is_positive, RegExpLookaround::Type type) [inline]
Definition at line 304 of file experimental-compiler.cc.
                                                  {
    code_.Add(
        RegExpInstruction::StartLookaround(lookaround_index, is_positive, type),
        zone_);
  }
References v8::internal::RegExpInstruction::StartLookaround(), and v8::internal::tracing::type.
WriteLookaroundTable()
void v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::WriteLookaroundTable (int index) [inline]
Definition at line 313 of file experimental-compiler.cc.
                                       {
    code_.Add(RegExpInstruction::WriteLookTable(index), zone_);
  }
References v8::internal::index, and v8::internal::RegExpInstruction::WriteLookTable().
Member Data Documentation
code_
ZoneList<RegExpInstruction> v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::code_ [private]
Definition at line 385 of file experimental-compiler.cc.
zone_
Zone* v8::internal::anonymous_namespace{experimental-compiler.cc}::BytecodeAssembler::zone_ [private]
Definition at line 384 of file experimental-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/regexp/experimental/experimental-compiler.cc