v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::ModifyThreadInWasmFlagScope Class Reference
Public Member Functions
ModifyThreadInWasmFlagScope (WasmWrapperGraphBuilder *wasm_wrapper_graph_builder, WasmGraphAssembler *gasm)
ModifyThreadInWasmFlagScope (const ModifyThreadInWasmFlagScope &)=delete
~ModifyThreadInWasmFlagScope ()
Private Attributes
WasmWrapperGraphBuilder * wasm_wrapper_graph_builder_
Node * thread_in_wasm_flag_address_
Detailed Description
Definition at line 673 of file wasm-compiler.cc.
Constructor & Destructor Documentation
ModifyThreadInWasmFlagScope() [1/2]
v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope (WasmWrapperGraphBuilder * wasm_wrapper_graph_builder, WasmGraphAssembler * gasm) [inline]
Definition at line 675 of file wasm-compiler.cc.
        : wasm_wrapper_graph_builder_(wasm_wrapper_graph_builder) {
      if (!trap_handler::IsTrapHandlerEnabled()) return;
      Node* isolate_root = wasm_wrapper_graph_builder_->BuildLoadIsolateRoot();
      thread_in_wasm_flag_address_ =
          gasm->Load(MachineType::Pointer(), isolate_root,
                     Isolate::thread_in_wasm_flag_address_offset());
      wasm_wrapper_graph_builder_->BuildModifyThreadInWasmFlagHelper(
          thread_in_wasm_flag_address_, true);
    }
References v8::internal::trap_handler::IsTrapHandlerEnabled(), v8::internal::compiler::GraphAssembler::Load(), v8::internal::MachineType::Pointer(), and v8::internal::Isolate::thread_in_wasm_flag_address_offset().
ModifyThreadInWasmFlagScope() [2/2]
v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::ModifyThreadInWasmFlagScope::ModifyThreadInWasmFlagScope (const ModifyThreadInWasmFlagScope &) [delete]
 ModifyThreadInWasmFlagScope()
v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::ModifyThreadInWasmFlagScope::~ModifyThreadInWasmFlagScope () [inline]
Definition at line 692 of file wasm-compiler.cc.
                                   {
      if (!trap_handler::IsTrapHandlerEnabled()) return;
      wasm_wrapper_graph_builder_->BuildModifyThreadInWasmFlagHelper(
          thread_in_wasm_flag_address_, false);
    }
References v8::internal::trap_handler::IsTrapHandlerEnabled().
Member Data Documentation
thread_in_wasm_flag_address_
Node* v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::ModifyThreadInWasmFlagScope::thread_in_wasm_flag_address_ [private]
Definition at line 701 of file wasm-compiler.cc.
wasm_wrapper_graph_builder_
WasmWrapperGraphBuilder* v8::internal::compiler::anonymous_namespace{wasm-compiler.cc}::WasmWrapperGraphBuilder::ModifyThreadInWasmFlagScope::wasm_wrapper_graph_builder_ [private]
Definition at line 700 of file wasm-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/wasm-compiler.cc