v8::internal::MaybeHandle< T > Class Template Reference
#include <maybe-handles.h>
Public Member Functions
MaybeHandle ()=default
MaybeHandle (NullMaybeHandleType)
template<typename S >
MaybeHandle (Handle< S > handle) requires(is_subtype_v< S
MaybeHandle (Tagged< T > object, LocalHeap *local_heap)
void Assert () const
void Check () const
Handle< T > ToHandleChecked () const
template<typename S >
V8_WARN_UNUSED_RESULT bool ToHandle (Handle< S > *out) const
template<typename S >
V8_WARN_UNUSED_RESULT bool ToHandle (DirectHandle< S > *out) const
bool equals (MaybeHandle< T > other) const
Address address () const
bool is_null () const
template<typename T >
MaybeHandle (Tagged< T > object, Isolate *isolate)
template<typename S >
bool ToHandle (DirectHandle< S > *out) const
Public Attributes
T __pad0__: location_(handle.location_) {} template <typename S> inline MaybeHandle(MaybeHandle<S> maybe_handle) requires(is_subtype_v<S
T T: location_(maybe_handle.location_) {} inline MaybeHandle(Tagged<T> object
T Isolate * isolate
Protected Member Functions
MaybeHandle (Address *location)
Protected Attributes
Address * location_ = nullptr
Friends
template<typename >
class MaybeHandle
template<typename To , typename From >
MaybeIndirectHandle< To > UncheckedCast (MaybeHandle< From > value)
Detailed Description
template<typename T>
class v8::internal::MaybeHandle< T >
Definition at line 28 of file maybe-handles.h.
Constructor & Destructor Documentation
MaybeHandle() [1/6]
template<typename T >
v8::internal::MaybeHandle< T >::MaybeHandle () [inline], [default]
MaybeHandle() [2/6]
template<typename T >
v8::internal::MaybeHandle< T >::MaybeHandle (NullMaybeHandleType) [inline]
Definition at line 32 of file maybe-handles.h.
{}
MaybeHandle() [3/6]
template<typename T >
template<typename S >
v8::internal::MaybeHandle< T >::MaybeHandle (Handle< S > handle) [inline]
MaybeHandle() [4/6]
template<typename T >
v8::internal::MaybeHandle< T >::MaybeHandle (Tagged< T > object, LocalHeap * local_heap) [inline]
Definition at line 24 of file maybe-handles-inl.h.
    : MaybeHandle(handle(object, local_heap)) {}
MaybeHandle() [5/6]
template<typename T >
v8::internal::MaybeHandle< T >::MaybeHandle (Address * location) [inline], [explicit], [protected]
Definition at line 89 of file maybe-handles.h.
: location_(location) {}
MaybeHandle() [6/6]
template<typename T >
template<typename T >
v8::internal::MaybeHandle< T >::MaybeHandle (Tagged< T > object, Isolate * isolate)
Definition at line 20 of file maybe-handles-inl.h.
    : MaybeHandle(handle(object, isolate)) {}
Member Function Documentation
address()
template<typename T >
Address v8::internal::MaybeHandle< T >::address () const [inline]
Definition at line 82 of file maybe-handles.h.
                                    {
    return reinterpret_cast<Address>(location_);
  }
References v8::internal::MaybeHandle< T >::location_.
Referenced by v8::internal::MaybeHandle< T >::equals(), v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::hash_value(), and v8::internal::compiler::anonymous_namespace{load-elimination.cc}::MayAlias().
Assert()
template<typename T >
void v8::internal::MaybeHandle< T >::Assert () const [inline]
Definition at line 52 of file maybe-handles.h.
{ DCHECK_NOT_NULL(location_); }
References DCHECK_NOT_NULL, and v8::internal::MaybeHandle< T >::location_.
Check()
template<typename T >
void v8::internal::MaybeHandle< T >::Check () const [inline]
Definition at line 53 of file maybe-handles.h.
{ CHECK_NOT_NULL(location_); }
References CHECK_NOT_NULL, and v8::internal::MaybeHandle< T >::location_.
Referenced by v8::internal::MaybeHandle< T >::ToHandleChecked().
equals()
template<typename T >
bool v8::internal::MaybeHandle< T >::equals (MaybeHandle< T > other) const [inline]
Definition at line 76 of file maybe-handles.h.
                                          {
    return address() == other.address();
  }
References v8::internal::MaybeHandle< T >::address().
Referenced by v8::internal::compiler::turboshaft::TransitionAndStoreArrayElementOp::operator==().
is_null()
template<typename T >
bool v8::internal::MaybeHandle< T >::is_null () const [inline]
Definition at line 86 of file maybe-handles.h.
{ return location_ == nullptr; }
References v8::internal::MaybeHandle< T >::location_.
Referenced by v8::WasmStreaming::WasmStreamingImpl::Abort(), v8::internal::OrderedNameDictionaryHandler::Add(), v8::internal::OrderedHashSetHandler::Add(), v8::internal::OrderedHashMapHandler::Add(), v8::internal::Debug::Break(), v8::internal::anonymous_namespace{debug.cc}::CompileTopLevel(), v8::internal::IntlMathematicalValue::From(), v8::internal::Debug::HandleDebugBreak(), v8::internal::BackgroundCompileTask::Run(), and v8::internal::Compiler::ValidateDynamicCompilationSource().
ToHandle() [1/3]
template<typename T >
template<typename S >
bool v8::internal::MaybeHandle< T >::ToHandle (DirectHandle< S > * out) const
Definition at line 39 of file maybe-handles-inl.h.
                                                        {
  if (location_ == nullptr) {
    *out = DirectHandle<T>::null();
    return false;
  } else {
    *out = DirectHandle<T>(Handle<T>(location_));
    return true;
  }
}
References v8::internal::DirectHandle< T >::null().
ToHandle() [2/3]
template<typename T >
template<typename S >
V8_WARN_UNUSED_RESULT bool v8::internal::MaybeHandle< T >::ToHandle (DirectHandle< S > * out) const [inline]
ToHandle() [3/3]
template<typename T >
template<typename S >
V8_WARN_UNUSED_RESULT bool v8::internal::MaybeHandle< T >::ToHandle (Handle< S > * out) const [inline]
Definition at line 62 of file maybe-handles.h.
                                                                      {
    if (location_ == nullptr) {
      *out = Handle<T>::null();
      return false;
    } else {
      *out = Handle<T>(location_);
      return true;
    }
  }
References v8::internal::MaybeHandle< T >::location_, and v8::internal::Handle< T >::null().
Referenced by v8::internal::OrderedNameDictionaryHandler::Add(), v8::internal::OrderedHashSetHandler::Add(), v8::internal::OrderedHashMapHandler::Add(), v8::internal::OrderedHashMap::Add(), v8::internal::OrderedNameDictionary::Add(), v8::internal::SmallOrderedHashMap::Add(), v8::internal::SmallOrderedHashSet::Add(), v8::internal::SmallOrderedNameDictionary::Add(), v8::internal::KeyAccumulator::AddKey(), v8::internal::OrderedHashMapHandler::AdjustRepresentation(), v8::internal::OrderedHashSetHandler::AdjustRepresentation(), v8::internal::OrderedNameDictionaryHandler::AdjustRepresentation(), v8::internal::OrderedNameDictionary::Allocate(), v8::internal::OrderedNameDictionary::AllocateEmpty(), v8::internal::anonymous_namespace{compiler.cc}::CompileScriptOnMainThread(), v8::internal::compiler::CodeGenerator::FinalizeCode(), v8::internal::compiler::turboshaft::Pipeline::FinalizeCode(), v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl(), v8::internal::MapUpdater::FindTargetMap(), v8::internal::MessageFormatter::Format(), v8::internal::compiler::Pipeline::GenerateCodeForTesting(), v8::internal::anonymous_namespace{compiler.cc}::GetOrCreateTopLevelSharedFunctionInfo(), v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl(), v8::internal::JsonStringifier::InitializeReplacer(), v8::internal::Heap::KeepDuringJob(), v8::internal::MutableBigInt::MakeImmutable(), v8::internal::anonymous_namespace{elements.cc}::ElementsAccessorBase< Subclass, ElementsTraitsParam >::PrependElementIndicesImpl(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ScriptCacheKey::ScriptCacheKey(), v8::internal::Map::TransitionToDataProperty(), v8::internal::JSDataObjectBuilder::TryAddFastPropertyForValue(), and v8::internal::JSDataObjectBuilder::TryFastTransitionToPropertyKey().
ToHandleChecked()
template<typename T >
Handle<T> v8::internal::MaybeHandle< T >::ToHandleChecked () const [inline]
Definition at line 55 of file maybe-handles.h.
                                              {
    Check();
    return Handle<T>(location_);
  }
References v8::internal::MaybeHandle< T >::Check(), and v8::internal::MaybeHandle< T >::location_.
Referenced by v8::WasmStreaming::WasmStreamingImpl::Abort(), v8::internal::OrderedNameDictionaryHandler::Add(), v8::internal::OrderedHashSetHandler::Add(), v8::internal::OrderedHashMapHandler::Add(), v8::internal::Debug::Break(), v8::internal::IntlMathematicalValue::From(), v8::internal::Debug::HandleDebugBreak(), v8::internal::JsonParseInternalizer::Internalize(), and v8::internal::BackgroundCompileTask::Run().
Friends And Related Function Documentation
MaybeHandle
template<typename T >
template<typename >
friend class MaybeHandle [friend]
Definition at line 96 of file maybe-handles.h.
UncheckedCast
template<typename T >
template<typename To , typename From >
MaybeIndirectHandle<To> UncheckedCast (MaybeHandle< From > value) [friend]
Member Data Documentation
__pad0__
template<typename T >
T v8::internal::MaybeHandle< T >::__pad0__
Definition at line 38 of file maybe-handles.h.
isolate
template<typename T >
T Isolate* v8::internal::MaybeHandle< T >::isolate
Definition at line 49 of file maybe-handles.h.
location_
template<typename T >
Address* v8::internal::MaybeHandle< T >::location_ = nullptr [protected]
Definition at line 91 of file maybe-handles.h.
Referenced by v8::internal::MaybeHandle< T >::address(), v8::internal::MaybeHandle< T >::Assert(), v8::internal::MaybeHandle< T >::Check(), v8::internal::MaybeHandle< T >::is_null(), v8::internal::MaybeHandle< T >::ToHandle(), and v8::internal::MaybeHandle< T >::ToHandleChecked().
T
template<typename T >
T v8::internal::MaybeHandle< T >::T
Definition at line 46 of file maybe-handles.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/common/globals.h
/mnt/V8SourceCode/src/handles/maybe-handles.h
/mnt/V8SourceCode/src/handles/maybe-handles-inl.h