v8::internal::compiler::RepresentationSelector Class Reference
Classes
class NodeInfo
class NodeProperties
struct NodeState
Public Member Functions
RepresentationSelector (JSGraph *jsgraph, JSHeapBroker *broker, Zone *zone, RepresentationChanger *changer, SourcePositionTable *source_positions, NodeOriginTable *node_origins, TickCounter *tick_counter, Linkage *linkage, ObserveNodeManager *observe_node_manager, SimplifiedLoweringVerifier *verifier)
bool verification_enabled () const
void ResetNodeInfoState ()
Type TypeOf (Node *node)
Type FeedbackTypeOf (Node *node)
Type TypePhi (Node *node)
Type TypeSelect (Node *node)
bool UpdateFeedbackType (Node *node)
void PrintNodeFeedbackType (Node *n)
Type Weaken (Node *node, Type previous_type, Type current_type)
void GenerateTraversal ()
void PushNodeToRevisitIfVisited (Node *node)
bool RetypeNode (Node *node)
void PropagateTruncation (Node *node)
void RunPropagatePhase ()
void RunRetypePhase ()
void RunLowerPhase (SimplifiedLowering *lowering)
void RunVerifyPhase (OptimizedCompilationInfo *compilation_info)
void Run (SimplifiedLowering *lowering)
template<Phase T>
void EnqueueInput (Node *use_node, int index, UseInfo use_info=UseInfo::None())
template<Phase T>
void SetOutput (Node *node, MachineRepresentation representation, Type restriction_type=Type::Any())
Type GetUpperBound (Node *node)
bool InputCannotBe (Node *node, Type type)
bool InputIs (Node *node, Type type)
bool BothInputsAreSigned32 (Node *node)
bool BothInputsAreUnsigned32 (Node *node)
bool BothInputsAre (Node *node, Type type)
bool IsNodeRepresentationTagged (Node *node)
bool OneInputCannotBe (Node *node, Type type)
void ChangeToDeadValue (Node *node, Node *effect, Node *control)
void ReplaceWithPureNode (Node *node, Node *pure_node)
void ChangeToPureOp (Node *node, const Operator *new_op)
void ChangeUnaryToPureBinaryOp (Node *node, const Operator *new_op, int new_input_index, Node *new_input)
void ConvertInput (Node *node, int index, UseInfo use, Type input_type=Type::Invalid())
template<Phase T>
void ProcessInput (Node *node, int index, UseInfo use)
template<Phase T>
void ProcessRemainingInputs (Node *node, int index)
void MarkAsPossibleRevisit (Node *node, Node *input)
template<Phase T>
void VisitInputs (Node *node)
template<Phase T>
void VisitReturn (Node *node)
template<Phase T>
void VisitUnused (Node *node)
template<Phase T>
void VisitNoop (Node *node, Truncation truncation)
template<Phase T>
void VisitBinop (Node *node, UseInfo left_use, UseInfo right_use, MachineRepresentation output, Type restriction_type=Type::Any())
template<Phase T>
void VisitBinop (Node *node, UseInfo input_use, MachineRepresentation output, Type restriction_type=Type::Any())
template<Phase T>
void VisitSpeculativeInt32Binop (Node *node)
template<Phase T>
void VisitUnop (Node *node, UseInfo input_use, MachineRepresentation output, Type restriction_type=Type::Any())
template<Phase T>
void VisitLeaf (Node *node, MachineRepresentation output)
template<Phase T>
void VisitFloat64Binop (Node *node)
template<Phase T>
void VisitInt64Binop (Node *node)
template<Phase T>
void VisitWord32TruncatingBinop (Node *node)
MachineRepresentation GetOutputInfoForPhi (Type type, Truncation use)
template<Phase T>
void VisitSelect (Node *node, Truncation truncation, SimplifiedLowering *lowering)
template<Phase T>
void VisitPhi (Node *node, Truncation truncation, SimplifiedLowering *lowering)
template<Phase T>
void VisitObjectIs (Node *node, Type type, SimplifiedLowering *lowering)
template<Phase T>
void VisitCheck (Node *node, Type type, SimplifiedLowering *lowering)
template<Phase T>
void VisitCall (Node *node, SimplifiedLowering *lowering)
void MaskShiftOperand (Node *node, Type rhs_type)
template<Phase T>
void VisitStateValues (Node *node)
template<Phase T>
void VisitFrameState (FrameState node)
template<Phase T>
void VisitObjectState (Node *node)
const Operator * Int32Op (Node *node)
const Operator * Int32OverflowOp (Node *node)
const Operator * AdditiveSafeIntegerOverflowOp (Node *node)
const Operator * Int64Op (Node *node)
const Operator * Int64OverflowOp (Node *node)
const Operator * BigIntOp (Node *node)
const Operator * Uint32Op (Node *node)
const Operator * Uint32OverflowOp (Node *node)
const Operator * Float64Op (Node *node)
WriteBarrierKind WriteBarrierKindFor (BaseTaggedness base_taggedness, MachineRepresentation field_representation, Type field_type, MachineRepresentation value_representation, Node *value)
WriteBarrierKind WriteBarrierKindFor (BaseTaggedness base_taggedness, MachineRepresentation field_representation, int field_offset, Type field_type, MachineRepresentation value_representation, Node *value)
TFGraph * graph () const
CommonOperatorBuilder * common () const
SimplifiedOperatorBuilder * simplified () const
template<Phase T>
void VisitForCheckedInt32Mul (Node *node, Truncation truncation, Type input0_type, Type input1_type, UseInfo input_use)
void ChangeToInt32OverflowOp (Node *node)
void ChangeToUint32OverflowOp (Node *node)
template<Phase T>
void VisitSpeculativeSmallIntegerAdditiveOp (Node *node, Truncation truncation, SimplifiedLowering *lowering)
bool CanSpeculateAdditiveSafeInteger (Node *node)
template<Phase T>
void VisitSpeculativeAdditiveOp (Node *node, Truncation truncation, SimplifiedLowering *lowering)
template<Phase T>
void VisitSpeculativeNumberModulus (Node *node, Truncation truncation, SimplifiedLowering *lowering)
template<Phase T>
void InsertUnreachableIfNecessary (Node *node)
template<Phase T>
void VisitCheckBounds (Node *node, SimplifiedLowering *lowering)
UseInfo UseInfoForFastApiCallArgument (CTypeInfo type, CFunctionInfo::Int64Representation repr, FeedbackSource const &feedback)
template<Phase T>
void VisitFastApiCall (Node *node, SimplifiedLowering *lowering)
template<Phase T>
bool TryOptimizeBigInt64Shift (Node *node, const Truncation &truncation, SimplifiedLowering *lowering)
template<Phase T>
void VisitNode (Node *node, Truncation truncation, SimplifiedLowering *lowering)
void DisconnectFromEffectAndControl (Node *node)
void DeferReplacement (Node *node, Node *replacement)
Node * InsertTypeOverrideForVerifier (const Type &type, Node *node)
Node * InsertUnconditionalDeopt (Node *node, DeoptimizeReason reason, const FeedbackSource &feedback={})
Node * InsertSemanticsHintForVerifier (const Operator *semantics, Node *node)
template<> void EnqueueInput (Node *use_node, int index, UseInfo use_info)
template<> void SetOutput (Node *node, MachineRepresentation representation, Type restriction_type)
template<> void SetOutput (Node *node, MachineRepresentation representation, Type restriction_type)
template<> void SetOutput (Node *node, MachineRepresentation representation, Type restriction_type)
template<> void ProcessInput (Node *node, int index, UseInfo use)
template<> void ProcessInput (Node *node, int index, UseInfo use)
template<> void ProcessInput (Node *node, int index, UseInfo use)
template<> void ProcessRemainingInputs (Node *node, int index)
template<> void VisitInputs (Node *node)
template<> void VisitInputs (Node *node)
template<> void InsertUnreachableIfNecessary (Node *node)
Static Public Member Functions
template<Phase T>
static constexpr bool propagate ()
template<Phase T>
static constexpr bool retype ()
template<Phase T>
static constexpr bool lower ()
static MachineSemantic DeoptValueSemanticOf (Type type)
static MachineType DeoptMachineTypeOf (MachineRepresentation rep, Type type)
Static Public Attributes
static constexpr int kInitialArgumentsCount = 10
Private Member Functions
void ChangeOp (Node *node, const Operator *new_op)
void NotifyNodeReplaced (Node *node, Node *replacement)
Type true_type () const
Type false_type () const
NodeInfo * GetInfo (Node *node)
Zone * zone ()
Zone * graph_zone ()
Linkage * linkage ()
Private Attributes
JSGraph * jsgraph_
JSHeapBroker * broker_
Zone * zone_
ZoneMap< Node *, ZoneVector< Node * > > might_need_revisit_
size_t count_
ZoneVector< NodeInfo > info_
NodeVector replacements_
RepresentationChanger * changer_
ZoneQueue< Node * > revisit_queue_
NodeVector traversal_nodes_
SourcePositionTable * source_positions_
NodeOriginTable * node_origins_
TypeCache const * type_cache_
OperationTyper op_typer_
Type singleton_true_
Type singleton_false_
TickCounter *const tick_counter_
Linkage *const linkage_
ObserveNodeManager *const observe_node_manager_
SimplifiedLoweringVerifier * verifier_
Detailed Description
Definition at line 303 of file simplified-lowering.cc.
Constructor & Destructor Documentation
RepresentationSelector()
v8::internal::compiler::RepresentationSelector::RepresentationSelector (JSGraph * jsgraph, JSHeapBroker * broker, Zone * zone, RepresentationChanger * changer, SourcePositionTable * source_positions, NodeOriginTable * node_origins, TickCounter * tick_counter, Linkage * linkage, ObserveNodeManager * observe_node_manager, SimplifiedLoweringVerifier * verifier) [inline]
Definition at line 361 of file simplified-lowering.cc.
      : jsgraph_(jsgraph),
        broker_(broker),
        zone_(zone),
        might_need_revisit_(zone),
        count_(jsgraph->graph()->NodeCount()),
        info_(count_, zone),
#ifdef DEBUG
        node_input_use_infos_(count_, InputUseInfos(zone), zone),
#endif
        replacements_(zone),
        changer_(changer),
        revisit_queue_(zone),
        traversal_nodes_(zone),
        source_positions_(source_positions),
        node_origins_(node_origins),
        type_cache_(TypeCache::Get()),
        op_typer_(broker, graph_zone()),
        tick_counter_(tick_counter),
        linkage_(linkage),
        observe_node_manager_(observe_node_manager),
        verifier_(verifier) {
    singleton_true_ =
        Type::Constant(broker, broker->true_value(), graph_zone());
    singleton_false_ =
        Type::Constant(broker, broker->false_value(), graph_zone());
  }
References broker(), v8::internal::compiler::Type::Constant(), graph_zone(), singleton_false_, and singleton_true_.
Member Function Documentation
AdditiveSafeIntegerOverflowOp()
const Operator* v8::internal::compiler::RepresentationSelector::AdditiveSafeIntegerOverflowOp (Node * node) [inline]
Definition at line 1568 of file simplified-lowering.cc.
                                                            {
    return changer_->AdditiveSafeIntegerOverflowOperatorFor(node->opcode());
  }
References v8::internal::compiler::RepresentationChanger::AdditiveSafeIntegerOverflowOperatorFor(), changer_, and v8::internal::compiler::Node::opcode().
Referenced by VisitSpeculativeAdditiveOp().
BigIntOp()
const Operator* v8::internal::compiler::RepresentationSelector::BigIntOp (Node * node) [inline]
Definition at line 1580 of file simplified-lowering.cc.
                                       {
    return changer_->BigIntOperatorFor(node->opcode());
  }
References v8::internal::compiler::RepresentationChanger::BigIntOperatorFor(), changer_, and v8::internal::compiler::Node::opcode().
Referenced by VisitNode().
BothInputsAre()
bool v8::internal::compiler::RepresentationSelector::BothInputsAre (Node * node, Type type) [inline]
Definition at line 926 of file simplified-lowering.cc.
                                            {
    DCHECK_EQ(2, node->op()->ValueInputCount());
    return GetUpperBound(node->InputAt(0)).Is(type) &&
           GetUpperBound(node->InputAt(1)).Is(type);
  }
References DCHECK_EQ, GetUpperBound(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Node::op(), v8::internal::tracing::type, and v8::internal::compiler::Operator::ValueInputCount().
Referenced by BothInputsAreSigned32(), BothInputsAreUnsigned32(), VisitForCheckedInt32Mul(), VisitNode(), VisitSpeculativeAdditiveOp(), VisitSpeculativeInt32Binop(), and VisitSpeculativeNumberModulus().
BothInputsAreSigned32()
bool v8::internal::compiler::RepresentationSelector::BothInputsAreSigned32 (Node * node) [inline]
Definition at line 918 of file simplified-lowering.cc.
                                         {
    return BothInputsAre(node, Type::Signed32());
  }
References BothInputsAre().
Referenced by VisitNode().
BothInputsAreUnsigned32()
bool v8::internal::compiler::RepresentationSelector::BothInputsAreUnsigned32 (Node * node) [inline]
Definition at line 922 of file simplified-lowering.cc.
                                           {
    return BothInputsAre(node, Type::Unsigned32());
  }
References BothInputsAre().
Referenced by VisitNode(), and VisitSpeculativeNumberModulus().
CanSpeculateAdditiveSafeInteger()
bool v8::internal::compiler::RepresentationSelector::CanSpeculateAdditiveSafeInteger (Node * node) [inline]
Definition at line 1791 of file simplified-lowering.cc.
                                                   {
    if (!v8_flags.additive_safe_int_feedback) return false;
    if (NumberOperationHintOf(node->op()) !=
        NumberOperationHint::kAdditiveSafeInteger) {
      return false;
    }
    DCHECK_EQ(2, node->op()->ValueInputCount());
    // Only speculate AdditiveSafeInteger if one of the sides are already known
    // to be in the AdditiveSafeInteger range, since the check is relatively
    // expensive.
    Type lhs_type = TypeOf(node->InputAt(0));
    Type rhs_type = TypeOf(node->InputAt(1));
    return lhs_type.Is(type_cache_->kAdditiveSafeInteger) ||
           rhs_type.Is(type_cache_->kAdditiveSafeInteger);
  }
References DCHECK_EQ, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Is(), v8::internal::compiler::kAdditiveSafeInteger, v8::internal::compiler::TypeCache::kAdditiveSafeInteger, v8::internal::compiler::NumberOperationHintOf(), v8::internal::compiler::Node::op(), type_cache_, TypeOf(), v8::internal::v8_flags, and v8::internal::compiler::Operator::ValueInputCount().
Referenced by VisitSpeculativeAdditiveOp().
ChangeOp()
void v8::internal::compiler::RepresentationSelector::ChangeOp (Node * node, const Operator * new_op) [inline], [private]
Definition at line 5055 of file simplified-lowering.cc.
                                                    {
    compiler::NodeProperties::ChangeOp(node, new_op);
    if (V8_UNLIKELY(observe_node_manager_ != nullptr))
      observe_node_manager_->OnNodeChanged(kSimplifiedLoweringReducerName, node,
                                           node);
  }
References v8::internal::compiler::NodeProperties::ChangeOp(), v8::internal::compiler::kSimplifiedLoweringReducerName, observe_node_manager_, v8::internal::compiler::ObserveNodeManager::OnNodeChanged(), and V8_UNLIKELY.
Referenced by ChangeToDeadValue(), ChangeToInt32OverflowOp(), ChangeToPureOp(), ChangeToUint32OverflowOp(), ChangeUnaryToPureBinaryOp(), VisitCheckBounds(), VisitForCheckedInt32Mul(), VisitNode(), VisitObjectState(), VisitPhi(), VisitSelect(), VisitSpeculativeAdditiveOp(), and VisitStateValues().
ChangeToDeadValue()
void v8::internal::compiler::RepresentationSelector::ChangeToDeadValue (Node * node, Node * effect, Node * control) [inline]
Definition at line 943 of file simplified-lowering.cc.
                                                                  {
    DCHECK(TypeOf(node).IsNone());
    // If the node is unreachable, insert an Unreachable node and mark the
    // value dead.
    // TODO(jarin,turbofan) Find a way to unify/merge this insertion with
    // InsertUnreachableIfNecessary.
    Node* unreachable = effect =
        graph()->NewNode(common()->Unreachable(), effect, control);
    const Operator* dead_value =
        common()->DeadValue(GetInfo(node)->representation());
    node->ReplaceInput(0, unreachable);
    node->TrimInputCount(dead_value->ValueInputCount());
    ReplaceEffectControlUses(node, effect, control);
    ChangeOp(node, dead_value);
  }
References ChangeOp(), common(), v8::internal::DCHECK(), v8::internal::compiler::CommonOperatorBuilder::DeadValue(), GetInfo(), graph(), v8::internal::IsNone(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::ReplaceEffectControlUses(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::Node::TrimInputCount(), TypeOf(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by ChangeToPureOp(), ChangeUnaryToPureBinaryOp(), and ReplaceWithPureNode().
ChangeToInt32OverflowOp()
void v8::internal::compiler::RepresentationSelector::ChangeToInt32OverflowOp (Node * node) [inline]
Definition at line 1693 of file simplified-lowering.cc.
                                           {
    ChangeOp(node, Int32OverflowOp(node));
  }
References ChangeOp(), and Int32OverflowOp().
Referenced by VisitNode(), VisitSpeculativeNumberModulus(), and VisitSpeculativeSmallIntegerAdditiveOp().
ChangeToPureOp()
void v8::internal::compiler::RepresentationSelector::ChangeToPureOp (Node * node, const Operator * new_op) [inline]
Definition at line 979 of file simplified-lowering.cc.
                                                          {
    DCHECK(new_op->HasProperty(Operator::kPure));
    DCHECK_EQ(new_op->ValueInputCount(), node->op()->ValueInputCount());
    if (node->op()->EffectInputCount() > 0) {
      DCHECK_LT(0, node->op()->ControlInputCount());
      Node* control = NodeProperties::GetControlInput(node);
      Node* effect = NodeProperties::GetEffectInput(node);
      if (TypeOf(node).IsNone()) {
        ChangeToDeadValue(node, effect, control);
        return;
      }
      // Rewire the effect and control chains.
      node->TrimInputCount(new_op->ValueInputCount());
      ReplaceEffectControlUses(node, effect, control);
    } else {
      DCHECK_EQ(0, node->op()->ControlInputCount());
    }
    ChangeOp(node, new_op);
  }
References ChangeOp(), ChangeToDeadValue(), v8::internal::compiler::Operator::ControlInputCount(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::Operator::HasProperty(), v8::internal::IsNone(), v8::internal::compiler::Operator::kPure, v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::ReplaceEffectControlUses(), v8::internal::compiler::Node::TrimInputCount(), TypeOf(), and v8::internal::compiler::Operator::ValueInputCount().
Referenced by VisitNode(), VisitSpeculativeAdditiveOp(), VisitSpeculativeNumberModulus(), and VisitSpeculativeSmallIntegerAdditiveOp().
ChangeToUint32OverflowOp()
void v8::internal::compiler::RepresentationSelector::ChangeToUint32OverflowOp (Node * node) [inline]
Definition at line 1697 of file simplified-lowering.cc.
                                            {
    ChangeOp(node, Uint32OverflowOp(node));
  }
References ChangeOp(), and Uint32OverflowOp().
Referenced by VisitNode(), and VisitSpeculativeNumberModulus().
ChangeUnaryToPureBinaryOp()
void v8::internal::compiler::RepresentationSelector::ChangeUnaryToPureBinaryOp (Node * node, const Operator * new_op, int new_input_index, Node * new_input) [inline]
Definition at line 999 of file simplified-lowering.cc.
                                                                       {
    DCHECK(new_op->HasProperty(Operator::kPure));
    DCHECK_EQ(new_op->ValueInputCount(), 2);
    DCHECK_EQ(node->op()->ValueInputCount(), 1);
    DCHECK_LE(0, new_input_index);
    DCHECK_LE(new_input_index, 1);
    if (node->op()->EffectInputCount() > 0) {
      DCHECK_LT(0, node->op()->ControlInputCount());
      Node* control = NodeProperties::GetControlInput(node);
      Node* effect = NodeProperties::GetEffectInput(node);
      if (TypeOf(node).IsNone()) {
        ChangeToDeadValue(node, effect, control);
        return;
      }
      node->TrimInputCount(node->op()->ValueInputCount());
      ReplaceEffectControlUses(node, effect, control);
    } else {
      DCHECK_EQ(0, node->op()->ControlInputCount());
    }
    if (new_input_index == 0) {
      node->InsertInput(jsgraph_->zone(), 0, new_input);
    } else {
      DCHECK_EQ(new_input_index, 1);
      DCHECK_EQ(node->InputCount(), 1);
      node->AppendInput(jsgraph_->zone(), new_input);
    }
    ChangeOp(node, new_op);
  }
References v8::internal::compiler::Node::AppendInput(), ChangeOp(), ChangeToDeadValue(), v8::internal::compiler::Operator::ControlInputCount(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_LT, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::Node::InsertInput(), v8::internal::IsNone(), jsgraph_, v8::internal::compiler::Operator::kPure, v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::ReplaceEffectControlUses(), v8::internal::compiler::Node::TrimInputCount(), TypeOf(), v8::internal::compiler::Operator::ValueInputCount(), and v8::internal::compiler::MachineGraph::zone().
Referenced by VisitNode().
common()
CommonOperatorBuilder* v8::internal::compiler::RepresentationSelector::common () const [inline]
Definition at line 1661 of file simplified-lowering.cc.
{ return jsgraph_->common(); }
References v8::internal::compiler::MachineGraph::common(), and jsgraph_.
Referenced by ChangeToDeadValue(), InsertSemanticsHintForVerifier(), InsertTypeOverrideForVerifier(), InsertUnreachableIfNecessary(), VisitFrameState(), VisitNode(), VisitObjectState(), VisitStateValues(), and VisitUnused().
ConvertInput()
void v8::internal::compiler::RepresentationSelector::ConvertInput (Node * node, int index, UseInfo use, Type input_type = Type::Invalid()) [inline]
Definition at line 1032 of file simplified-lowering.cc.
                                                     {
    // In the change phase, insert a change before the use if necessary.
    if (use.representation() == MachineRepresentation::kNone)
      return; // No input requirement on the use.
    Node* input = node->InputAt(index);
    DCHECK_NOT_NULL(input);
    NodeInfo* input_info = GetInfo(input);
    MachineRepresentation input_rep = input_info->representation();
    if (input_rep != use.representation() ||
        use.type_check() != TypeCheckKind::kNone) {
      // Output representation doesn't match usage.
      TRACE(" change: #%d:%s(@%d #%d:%s) ", node->id(), node->op()->mnemonic(),
            index, input->id(), input->op()->mnemonic());
      TRACE("from %s to %s:%s\n",
            MachineReprToString(input_info->representation()),
            MachineReprToString(use.representation()),
            use.truncation().description());
      if (input_type.IsInvalid()) {
        input_type = TypeOf(input);
      } else {
        // This case is reached when ConvertInput is called for TypeGuard nodes
        // which explicitly set the {input_type} for their input. In order to
        // correctly verify the resulting graph, we have to preserve this
        // forced type for the verifier.
        DCHECK_EQ(node->opcode(), IrOpcode::kTypeGuard);
        input = InsertTypeOverrideForVerifier(input_type, input);
      }
      Node* n = changer_->GetRepresentationFor(input, input_rep, input_type,
                                               node, use);
      node->ReplaceInput(index, n);
    }
  }
References changer_, DCHECK_EQ, DCHECK_NOT_NULL, GetInfo(), v8::internal::compiler::RepresentationChanger::GetRepresentationFor(), v8::internal::compiler::Node::id(), v8::internal::index, v8::internal::compiler::Node::InputAt(), InsertTypeOverrideForVerifier(), v8::internal::kNone, v8::internal::compiler::kNone, v8::internal::MachineReprToString(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::Node::ReplaceInput(), v8::internal::compiler::RepresentationSelector::NodeInfo::representation(), v8::internal::TRACE(), TypeOf(), and use().
Referenced by ProcessInput(), VisitFrameState(), VisitNode(), VisitObjectState(), and VisitStateValues().
DeferReplacement()
void v8::internal::compiler::RepresentationSelector::DeferReplacement (Node * node, Node * replacement) [inline]
Definition at line 5010 of file simplified-lowering.cc.
                                                       {
    TRACE("defer replacement #%d:%s with #%d:%s\n", node->id(),
          node->op()->mnemonic(), replacement->id(),
          replacement->op()->mnemonic());
    DisconnectFromEffectAndControl(node);
    node->NullAllInputs(); // Node is now dead.
    replacements_.push_back(node);
    replacements_.push_back(replacement);
    NotifyNodeReplaced(node, replacement);
  }
References DisconnectFromEffectAndControl(), v8::internal::compiler::Node::id(), v8::internal::compiler::Operator::mnemonic(), NotifyNodeReplaced(), v8::internal::compiler::Node::NullAllInputs(), v8::internal::compiler::Node::op(), v8::internal::ZoneVector< T >::push_back(), replacements_, and v8::internal::TRACE().
Referenced by v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), ReplaceWithPureNode(), TryOptimizeBigInt64Shift(), VisitCheck(), VisitCheckBounds(), VisitNode(), VisitNoop(), VisitObjectIs(), VisitSpeculativeAdditiveOp(), VisitSpeculativeNumberModulus(), and VisitUnused().
DeoptMachineTypeOf()
static MachineType v8::internal::compiler::RepresentationSelector::DeoptMachineTypeOf (MachineRepresentation rep, Type type) [inline], [static]
Definition at line 1388 of file simplified-lowering.cc.
                                                                              {
    if (type.IsNone()) {
      return MachineType::None();
    }
    // Do not distinguish between various Tagged variations.
    if (IsAnyTagged(rep)) {
      return MachineType::AnyTagged();
    }
    if (rep == MachineRepresentation::kWord64) {
      if (type.Is(Type::SignedBigInt64())) {
        return MachineType::SignedBigInt64();
      }
      if (type.Is(Type::UnsignedBigInt64())) {
        return MachineType::UnsignedBigInt64();
      }
      if (type.Is(Type::BigInt())) {
        return MachineType::AnyTagged();
      }
      DCHECK(type.Is(TypeCache::Get()->kSafeInteger));
      return MachineType(rep, MachineSemantic::kInt64);
    }
    MachineType machine_type(rep, DeoptValueSemanticOf(type));
    DCHECK_IMPLIES(
        machine_type.representation() == MachineRepresentation::kWord32,
        machine_type.semantic() == MachineSemantic::kInt32 ||
            machine_type.semantic() == MachineSemantic::kUint32);
    DCHECK_IMPLIES(machine_type.representation() == MachineRepresentation::kBit,
                   type.Is(Type::Boolean()));
    return machine_type;
  }
References v8::internal::MachineType::AnyTagged(), v8::internal::DCHECK(), DCHECK_IMPLIES, DeoptValueSemanticOf(), v8::internal::compiler::TypeCache::Get(), v8::internal::IsAnyTagged(), v8::internal::kBit, v8::internal::kInt32, v8::internal::kInt64, v8::internal::compiler::TypeCache::kSafeInteger, v8::internal::kUint32, v8::internal::kWord32, v8::internal::kWord64, v8::internal::wasm::machine_type(), v8::internal::MachineType::None(), v8::internal::MachineType::representation(), v8::internal::MachineType::semantic(), v8::internal::MachineType::SignedBigInt64(), v8::internal::tracing::type, and v8::internal::MachineType::UnsignedBigInt64().
Referenced by VisitFrameState(), VisitObjectState(), and VisitStateValues().
DeoptValueSemanticOf()
static MachineSemantic v8::internal::compiler::RepresentationSelector::DeoptValueSemanticOf (Type type) [inline], [static]
Definition at line 1377 of file simplified-lowering.cc.
                                                         {
    // We only need signedness to do deopt correctly.
    if (type.Is(Type::Signed32())) {
      return MachineSemantic::kInt32;
    } else if (type.Is(Type::Unsigned32())) {
      return MachineSemantic::kUint32;
    } else {
      return MachineSemantic::kAny;
    }
  }
References v8::internal::kAny, v8::internal::kInt32, v8::internal::kUint32, and v8::internal::tracing::type.
Referenced by DeoptMachineTypeOf().
DisconnectFromEffectAndControl()
void v8::internal::compiler::RepresentationSelector::DisconnectFromEffectAndControl (Node * node) [inline]
Definition at line 4992 of file simplified-lowering.cc.
                                                  {
    if (node->op()->EffectInputCount() == 1) {
      Node* control;
      if (node->op()->ControlInputCount() == 1) {
        control = NodeProperties::GetControlInput(node);
      } else {
        DCHECK_EQ(node->op()->ControlInputCount(), 0);
        control = nullptr;
      }
      Node* effect = NodeProperties::GetEffectInput(node);
      ReplaceEffectControlUses(node, effect, control);
    } else {
      DCHECK_EQ(0, node->op()->EffectInputCount());
      DCHECK_EQ(0, node->op()->ControlOutputCount());
      DCHECK_EQ(0, node->op()->EffectOutputCount());
    }
  }
References v8::internal::compiler::Operator::ControlInputCount(), v8::internal::compiler::Operator::ControlOutputCount(), DCHECK_EQ, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::Node::op(), and v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::ReplaceEffectControlUses().
Referenced by DeferReplacement(), VisitNode(), and VisitUnused().
EnqueueInput() [1/2]
template<>
void v8::internal::compiler::RepresentationSelector::EnqueueInput (Node * use_node, int index, UseInfo use_info)
Definition at line 5122 of file simplified-lowering.cc.
                                                                       {
  Node* node = use_node->InputAt(index);
  NodeInfo* info = GetInfo(node);
#ifdef DEBUG
  // Check monotonicity of input requirements.
  node_input_use_infos_[use_node->id()].SetAndCheckInput(use_node, index,
                                                         use_info);
#endif // DEBUG
  if (info->unvisited()) {
    info->AddUse(use_info);
    TRACE(" initial #%i: %s\n", node->id(), info->truncation().description());
    return;
  }
  TRACE(" queue #%i?: %s\n", node->id(), info->truncation().description());
  if (info->AddUse(use_info)) {
    // New usage information for the node is available.
    if (!info->queued()) {
      DCHECK(info->visited());
      revisit_queue_.push(node);
      info->set_queued();
      TRACE(" added: %s\n", info->truncation().description());
    } else {
      TRACE(" inqueue: %s\n", info->truncation().description());
    }
  }
}
References v8::internal::compiler::RepresentationSelector::NodeInfo::AddUse(), v8::internal::DCHECK(), v8::internal::compiler::Truncation::description(), GetInfo(), v8::internal::compiler::Node::id(), v8::internal::index, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::RepresentationSelector::NodeInfo::queued(), revisit_queue_, v8::internal::compiler::RepresentationSelector::NodeInfo::set_queued(), v8::internal::TRACE(), v8::internal::compiler::RepresentationSelector::NodeInfo::truncation(), v8::internal::compiler::RepresentationSelector::NodeInfo::unvisited(), and v8::internal::compiler::RepresentationSelector::NodeInfo::visited().
EnqueueInput() [2/2]
template<Phase T>
void v8::internal::compiler::RepresentationSelector::EnqueueInput (Node * use_node, int index, UseInfo use_info = UseInfo::None()) [inline]
Definition at line 880 of file simplified-lowering.cc.
                                                      {
    static_assert(retype<T>() || lower<T>(),
                  "This version of EnqueueInput has to be called in "
                  "the Retype or Lower phase.");
  }
false_type()
Type v8::internal::compiler::RepresentationSelector::false_type () const [inline], [private]
Definition at line 5070 of file simplified-lowering.cc.
{ return singleton_false_; }
References singleton_false_.
Referenced by VisitNode(), and VisitObjectIs().
FeedbackTypeOf()
Type v8::internal::compiler::RepresentationSelector::FeedbackTypeOf (Node * node) [inline]
Definition at line 409 of file simplified-lowering.cc.
                                  {
    Type type = GetInfo(node)->feedback_type();
    return type.IsInvalid() ? Type::None() : type;
  }
References v8::internal::compiler::RepresentationSelector::NodeInfo::feedback_type(), GetInfo(), v8::internal::compiler::turboshaft::Type::None(), and v8::internal::tracing::type.
Referenced by TypePhi(), TypeSelect(), and UpdateFeedbackType().
Float64Op()
const Operator* v8::internal::compiler::RepresentationSelector::Float64Op (Node * node) [inline]
Definition at line 1592 of file simplified-lowering.cc.
                                        {
    return changer_->Float64OperatorFor(node->opcode());
  }
References changer_, v8::internal::compiler::RepresentationChanger::Float64OperatorFor(), and v8::internal::compiler::Node::opcode().
Referenced by VisitNode(), VisitSpeculativeAdditiveOp(), and VisitSpeculativeNumberModulus().
GenerateTraversal()
void v8::internal::compiler::RepresentationSelector::GenerateTraversal () [inline]
Definition at line 639 of file simplified-lowering.cc.
                           {
    // Reset previous state.
    ResetNodeInfoState();
    traversal_nodes_.clear();
    count_ = graph()->NodeCount();
    info_.resize(count_);
    ZoneStack<NodeState> stack(zone_);
    stack.push({graph()->end(), 0});
    GetInfo(graph()->end())->set_pushed();
    while (!stack.empty()) {
      NodeState& current = stack.top();
      Node* node = current.node;
      // If there is an unvisited input, push it and continue with that node.
      bool pushed_unvisited = false;
      while (current.input_index < node->InputCount()) {
        Node* input = node->InputAt(current.input_index);
        NodeInfo* input_info = GetInfo(input);
        current.input_index++;
        if (input_info->unvisited()) {
          input_info->set_pushed();
          stack.push({input, 0});
          pushed_unvisited = true;
          break;
        } else if (input_info->pushed()) {
          // Optimization for the Retype phase.
          // If we had already pushed (and not visited) an input, it means that
          // the current node will be visited in the Retype phase before one of
          // its inputs. If this happens, the current node might need to be
          // revisited.
          MarkAsPossibleRevisit(node, input);
        }
      }
      if (pushed_unvisited) continue;
      stack.pop();
      NodeInfo* info = GetInfo(node);
      info->set_visited();
      // Generate the traversal
      traversal_nodes_.push_back(node);
    }
  }
References v8::internal::ZoneVector< T >::clear(), count_, v8::internal::compiler::TFGraph::end(), v8::internal::compiler::end(), GetInfo(), graph(), info_, v8::internal::compiler::RepresentationSelector::NodeState::input_index, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), MarkAsPossibleRevisit(), v8::internal::compiler::RepresentationSelector::NodeState::node, v8::internal::compiler::TFGraph::NodeCount(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::RepresentationSelector::NodeInfo::pushed(), ResetNodeInfoState(), v8::internal::compiler::RepresentationSelector::NodeInfo::set_pushed(), v8::internal::compiler::RepresentationSelector::NodeInfo::set_visited(), v8::internal::stack, traversal_nodes_, v8::internal::compiler::RepresentationSelector::NodeInfo::unvisited(), and zone_.
Referenced by Run(), and RunVerifyPhase().
GetInfo()
NodeInfo* v8::internal::compiler::RepresentationSelector::GetInfo (Node * node) [inline], [private]
Definition at line 5108 of file simplified-lowering.cc.
                                {
    DCHECK(node->id() < count_);
    return &info_[node->id()];
  }
References count_, v8::internal::DCHECK(), v8::internal::compiler::Node::id(), and info_.
Referenced by ChangeToDeadValue(), ConvertInput(), EnqueueInput(), FeedbackTypeOf(), GenerateTraversal(), IsNodeRepresentationTagged(), PrintNodeFeedbackType(), PropagateTruncation(), PushNodeToRevisitIfVisited(), RetypeNode(), RunLowerPhase(), RunVerifyPhase(), SetOutput(), TypeOf(), UpdateFeedbackType(), VisitFrameState(), VisitNode(), VisitObjectState(), VisitStateValues(), and Weaken().
GetOutputInfoForPhi()
MachineRepresentation v8::internal::compiler::RepresentationSelector::GetOutputInfoForPhi (Type type, Truncation use) [inline]
Definition at line 1214 of file simplified-lowering.cc.
                                                                       {
    // Compute the representation.
    if (type.Is(Type::None())) {
      return MachineRepresentation::kNone;
    } else if (type.Is(Type::Signed32()) || type.Is(Type::Unsigned32())) {
      return MachineRepresentation::kWord32;
    } else if (type.Is(Type::NumberOrOddball()) && use.IsUsedAsWord32()) {
      return MachineRepresentation::kWord32;
    } else if (type.Is(Type::Boolean())) {
      return MachineRepresentation::kBit;
    } else if (type.Is(Type::NumberOrOddball()) &&
               use.TruncatesOddballAndBigIntToNumber()) {
      return MachineRepresentation::kFloat64;
    } else if (type.Is(Type::Union(Type::SignedSmall(), Type::NaN(), zone()))) {
      // TODO(turbofan): For Phis that return either NaN or some Smi, it's
      // beneficial to not go all the way to double, unless the uses are
      // double uses. For tagging that just means some potentially expensive
      // allocation code; we might want to do the same for -0 as well?
      return MachineRepresentation::kTagged;
    } else if (type.Is(Type::Number())) {
      return MachineRepresentation::kFloat64;
    } else if (type.Is(Type::BigInt()) && Is64() && use.IsUsedAsWord64()) {
      return MachineRepresentation::kWord64;
    } else if (type.Is(Type::ExternalPointer()) ||
               type.Is(Type::SandboxedPointer())) {
      return MachineType::PointerRepresentation();
    }
    return MachineRepresentation::kTagged;
  }
References v8::internal::Is64(), v8::internal::kBit, v8::internal::kFloat64, v8::internal::kNone, v8::internal::kTagged, v8::internal::kWord32, v8::internal::kWord64, v8::internal::compiler::turboshaft::Type::None(), v8::internal::MachineType::PointerRepresentation(), v8::internal::compiler::Type::SignedSmall(), v8::internal::tracing::type, v8::internal::compiler::Type::Union(), use(), and zone().
Referenced by VisitNode(), VisitNoop(), VisitPhi(), and VisitSelect().
GetUpperBound()
Type v8::internal::compiler::RepresentationSelector::GetUpperBound (Node * node) [inline]
Definition at line 906 of file simplified-lowering.cc.
{ return NodeProperties::GetType(node); }
References v8::internal::compiler::NodeProperties::GetType().
Referenced by BothInputsAre(), InputCannotBe(), InputIs(), OneInputCannotBe(), TryOptimizeBigInt64Shift(), UpdateFeedbackType(), VisitNode(), VisitSpeculativeAdditiveOp(), and VisitSpeculativeSmallIntegerAdditiveOp().
graph()
TFGraph* v8::internal::compiler::RepresentationSelector::graph () const [inline]
Definition at line 1660 of file simplified-lowering.cc.
{ return jsgraph_->graph(); }
References v8::internal::compiler::MachineGraph::graph(), and jsgraph_.
Referenced by ChangeToDeadValue(), GenerateTraversal(), InsertSemanticsHintForVerifier(), InsertTypeOverrideForVerifier(), InsertUnreachableIfNecessary(), MaskShiftOperand(), RunVerifyPhase(), TryOptimizeBigInt64Shift(), VisitCheckBounds(), VisitNode(), and VisitUnused().
graph_zone()
Zone* v8::internal::compiler::RepresentationSelector::graph_zone () [inline], [private]
Definition at line 5113 of file simplified-lowering.cc.
{ return jsgraph_->zone(); }
References jsgraph_, and v8::internal::compiler::MachineGraph::zone().
Referenced by RepresentationSelector(), UpdateFeedbackType(), VisitSpeculativeSmallIntegerAdditiveOp(), and Weaken().
InputCannotBe()
bool v8::internal::compiler::RepresentationSelector::InputCannotBe (Node * node, Type type) [inline]
Definition at line 908 of file simplified-lowering.cc.
                                            {
    DCHECK_EQ(1, node->op()->ValueInputCount());
    return !GetUpperBound(node->InputAt(0)).Maybe(type);
  }
References DCHECK_EQ, GetUpperBound(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::Node::op(), v8::internal::tracing::type, and v8::internal::compiler::Operator::ValueInputCount().
Referenced by VisitNode().
InputIs()
bool v8::internal::compiler::RepresentationSelector::InputIs (Node * node, Type type) [inline]
Definition at line 913 of file simplified-lowering.cc.
                                      {
    DCHECK_EQ(1, node->op()->ValueInputCount());
    return GetUpperBound(node->InputAt(0)).Is(type);
  }
References DCHECK_EQ, GetUpperBound(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Node::op(), v8::internal::tracing::type, and v8::internal::compiler::Operator::ValueInputCount().
Referenced by VisitCheck(), and VisitNode().
InsertSemanticsHintForVerifier()
Node* v8::internal::compiler::RepresentationSelector::InsertSemanticsHintForVerifier (const Operator * semantics, Node * node) [inline]
Definition at line 5046 of file simplified-lowering.cc.
                                                                              {
    if (V8_UNLIKELY(verification_enabled())) {
      node = graph()->NewNode(common()->SLVerifierHint(semantics, {}), node);
      verifier_->RecordHint(node);
    }
    return node;
  }
References common(), graph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::SimplifiedLoweringVerifier::RecordHint(), V8_UNLIKELY, verification_enabled(), and verifier_.
Referenced by VisitNode().
InsertTypeOverrideForVerifier()
Node* v8::internal::compiler::RepresentationSelector::InsertTypeOverrideForVerifier (const Type & type, Node * node) [inline]
Definition at line 5024 of file simplified-lowering.cc.
                                                                    {
    if (V8_UNLIKELY(verification_enabled())) {
      DCHECK(!type.IsInvalid());
      node = graph()->NewNode(common()->SLVerifierHint(nullptr, type), node);
      verifier_->RecordHint(node);
    }
    return node;
  }
References common(), v8::internal::DCHECK(), graph(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::SimplifiedLoweringVerifier::RecordHint(), v8::internal::tracing::type, V8_UNLIKELY, verification_enabled(), and verifier_.
Referenced by ConvertInput(), RunVerifyPhase(), VisitNode(), and VisitObjectIs().
InsertUnconditionalDeopt()
Node* v8::internal::compiler::RepresentationSelector::InsertUnconditionalDeopt (Node * node, DeoptimizeReason reason, const FeedbackSource & feedback = {}) [inline]
Definition at line 5033 of file simplified-lowering.cc.
                                                                  {}) {
    Node* effect = NodeProperties::GetEffectInput(node);
    Node* control = NodeProperties::GetControlInput(node);
    effect =
        jsgraph_->graph()->NewNode(simplified()->CheckIf(reason, feedback),
                                   jsgraph_->Int32Constant(0), effect, control);
    Node* unreachable = effect = jsgraph_->graph()->NewNode(
        jsgraph_->common()->Unreachable(), effect, control);
    NodeProperties::ReplaceEffectInput(node, effect);
    return unreachable;
  }
Referenced by VisitSpeculativeAdditiveOp().
InsertUnreachableIfNecessary() [1/2]
template<Phase T>
void v8::internal::compiler::RepresentationSelector::InsertUnreachableIfNecessary (Node * node) [inline]
Definition at line 1994 of file simplified-lowering.cc.
                                                {
    static_assert(propagate<T>() || retype<T>(),
                  "This version of InsertUnreachableIfNecessary has to be "
                  "called in the Propagate or Retype phase.");
  }
InsertUnreachableIfNecessary() [2/2]
template<>
void v8::internal::compiler::RepresentationSelector::InsertUnreachableIfNecessary (Node * node)
Definition at line 5245 of file simplified-lowering.cc.
                                                                           {
  // If the node is effectful and it produces an impossible value, then we
  // insert Unreachable node after it.
  if (node->op()->ValueOutputCount() > 0 &&
      node->op()->EffectOutputCount() > 0 &&
      node->opcode() != IrOpcode::kUnreachable && TypeOf(node).IsNone()) {
    Node* control = (node->op()->ControlOutputCount() == 0)
                        ? NodeProperties::GetControlInput(node, 0)
                        : NodeProperties::FindSuccessfulControlProjection(node);
    Node* unreachable =
        graph()->NewNode(common()->Unreachable(), node, control);
    // Insert unreachable node and replace all the effect uses of the {node}
    // with the new unreachable node.
    for (Edge edge : node->use_edges()) {
      if (!NodeProperties::IsEffectEdge(edge)) continue;
      // Make sure to not overwrite the unreachable node's input. That would
      // create a cycle.
      if (edge.from() == unreachable) continue;
      // Avoid messing up the exceptional path.
      if (edge.from()->opcode() == IrOpcode::kIfException) {
        DCHECK(!node->op()->HasProperty(Operator::kNoThrow));
        DCHECK_EQ(NodeProperties::GetControlInput(edge.from()), node);
        continue;
      }
      edge.UpdateTo(unreachable);
    }
  }
}
References common(), v8::internal::compiler::Operator::ControlOutputCount(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::NodeProperties::FindSuccessfulControlProjection(), v8::internal::compiler::NodeProperties::GetControlInput(), graph(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::NodeProperties::IsEffectEdge(), v8::internal::IsNone(), v8::internal::compiler::Operator::kNoThrow, v8::internal::wasm::kUnreachable, v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), TypeOf(), v8::internal::compiler::Node::use_edges(), and v8::internal::compiler::Operator::ValueOutputCount().
Int32Op()
const Operator* v8::internal::compiler::RepresentationSelector::Int32Op (Node * node) [inline]
Definition at line 1560 of file simplified-lowering.cc.
                                      {
    return changer_->Int32OperatorFor(node->opcode());
  }
References changer_, v8::internal::compiler::RepresentationChanger::Int32OperatorFor(), and v8::internal::compiler::Node::opcode().
Referenced by VisitNode(), VisitSpeculativeAdditiveOp(), and VisitSpeculativeSmallIntegerAdditiveOp().
Int32OverflowOp()
const Operator* v8::internal::compiler::RepresentationSelector::Int32OverflowOp (Node * node) [inline]
Definition at line 1564 of file simplified-lowering.cc.
                                              {
    return changer_->Int32OverflowOperatorFor(node->opcode());
  }
References changer_, v8::internal::compiler::RepresentationChanger::Int32OverflowOperatorFor(), and v8::internal::compiler::Node::opcode().
Referenced by ChangeToInt32OverflowOp().
Int64Op()
const Operator* v8::internal::compiler::RepresentationSelector::Int64Op (Node * node) [inline]
Definition at line 1572 of file simplified-lowering.cc.
                                      {
    return changer_->Int64OperatorFor(node->opcode());
  }
References changer_, v8::internal::compiler::RepresentationChanger::Int64OperatorFor(), and v8::internal::compiler::Node::opcode().
Referenced by VisitNode().
Int64OverflowOp()
const Operator* v8::internal::compiler::RepresentationSelector::Int64OverflowOp (Node * node) [inline]
Definition at line 1576 of file simplified-lowering.cc.
                                              {
    return changer_->Int64OverflowOperatorFor(node->opcode());
  }
References changer_, v8::internal::compiler::RepresentationChanger::Int64OverflowOperatorFor(), and v8::internal::compiler::Node::opcode().
Referenced by VisitNode().
IsNodeRepresentationTagged()
bool v8::internal::compiler::RepresentationSelector::IsNodeRepresentationTagged (Node * node) [inline]
Definition at line 932 of file simplified-lowering.cc.
                                              {
    MachineRepresentation representation = GetInfo(node)->representation();
    return IsAnyTagged(representation);
  }
References GetInfo(), v8::internal::IsAnyTagged(), and v8::internal::compiler::RepresentationSelector::NodeInfo::representation().
Referenced by VisitNode().
linkage()
Linkage* v8::internal::compiler::RepresentationSelector::linkage () [inline], [private]
Definition at line 5114 of file simplified-lowering.cc.
{ return linkage_; }
References linkage_.
Referenced by VisitNode().
lower()
template<Phase T>
static constexpr bool v8::internal::compiler::RepresentationSelector::lower () [inline], [static], [constexpr]
Definition at line 898 of file simplified-lowering.cc.
                                {
    return T == LOWER;
  }
References v8::internal::compiler::LOWER.
MarkAsPossibleRevisit()
void v8::internal::compiler::RepresentationSelector::MarkAsPossibleRevisit (Node * node, Node * input) [inline]
Definition at line 1081 of file simplified-lowering.cc.
                                                      {
    auto it = might_need_revisit_.find(input);
    if (it == might_need_revisit_.end()) {
      it = might_need_revisit_.insert({input, ZoneVector<Node*>(zone())}).first;
    }
    it->second.push_back(node);
    TRACE(" Marking #%d: %s as needing revisit due to #%d: %s\n", node->id(),
          node->op()->mnemonic(), input->id(), input->op()->mnemonic());
  }
References v8::internal::compiler::Node::id(), might_need_revisit_, v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::TRACE(), and zone().
Referenced by GenerateTraversal().
MaskShiftOperand()
void v8::internal::compiler::RepresentationSelector::MaskShiftOperand (Node * node, Type rhs_type) [inline]
Definition at line 1368 of file simplified-lowering.cc.
                                                   {
    if (!rhs_type.Is(type_cache_->kZeroToThirtyOne)) {
      Node* const rhs = NodeProperties::GetValueInput(node, 1);
      node->ReplaceInput(1,
                         graph()->NewNode(jsgraph_->machine()->Word32And(), rhs,
                                          jsgraph_->Int32Constant(0x1F)));
    }
  }
References v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::MachineGraph::Int32Constant(), v8::internal::compiler::Type::Is(), jsgraph_, v8::internal::compiler::TypeCache::kZeroToThirtyOne, v8::internal::compiler::MachineGraph::machine(), v8::internal::compiler::Node::ReplaceInput(), type_cache_, and v8::internal::compiler::MachineOperatorBuilder::Word32And().
Referenced by VisitNode().
NotifyNodeReplaced()
void v8::internal::compiler::RepresentationSelector::NotifyNodeReplaced (Node * node, Node * replacement) [inline], [private]
Definition at line 5063 of file simplified-lowering.cc.
                                                         {
    if (V8_UNLIKELY(observe_node_manager_ != nullptr))
      observe_node_manager_->OnNodeChanged(kSimplifiedLoweringReducerName, node,
                                           replacement);
  }
References v8::internal::compiler::kSimplifiedLoweringReducerName, observe_node_manager_, v8::internal::compiler::ObserveNodeManager::OnNodeChanged(), and V8_UNLIKELY.
Referenced by DeferReplacement().
OneInputCannotBe()
bool v8::internal::compiler::RepresentationSelector::OneInputCannotBe (Node * node, Type type) [inline]
Definition at line 937 of file simplified-lowering.cc.
                                               {
    DCHECK_EQ(2, node->op()->ValueInputCount());
    return !GetUpperBound(node->InputAt(0)).Maybe(type) ||
           !GetUpperBound(node->InputAt(1)).Maybe(type);
  }
References DCHECK_EQ, GetUpperBound(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::Node::op(), v8::internal::tracing::type, and v8::internal::compiler::Operator::ValueInputCount().
Referenced by VisitNode().
PrintNodeFeedbackType()
void v8::internal::compiler::RepresentationSelector::PrintNodeFeedbackType (Node * n) [inline]
Definition at line 584 of file simplified-lowering.cc.
                                      {
    StdoutStream os;
    os << "#" << n->id() << ":" << *n->op() << "(";
    int j = 0;
    for (Node* const i : n->inputs()) {
      if (j++ > 0) os << ", ";
      os << "#" << i->id() << ":" << i->op()->mnemonic();
    }
    os << ")";
    if (NodeProperties::IsTyped(n)) {
      Type static_type = NodeProperties::GetType(n);
      os << " [Static type: " << static_type;
      Type feedback_type = GetInfo(n)->feedback_type();
      if (!feedback_type.IsInvalid() && feedback_type != static_type) {
        os << ", Feedback type: " << feedback_type;
      }
      os << "]";
    }
    os << std::endl;
  }
References v8::internal::compiler::RepresentationSelector::NodeInfo::feedback_type(), GetInfo(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Node::id(), v8::internal::compiler::Node::inputs(), v8::internal::compiler::Type::IsInvalid(), v8::internal::compiler::NodeProperties::IsTyped(), and v8::internal::compiler::Node::op().
Referenced by UpdateFeedbackType().
ProcessInput() [1/4]
template<Phase T>
void v8::internal::compiler::RepresentationSelector::ProcessInput (Node * node, int index, UseInfo use)
ProcessInput() [2/4]
template<>
void v8::internal::compiler::RepresentationSelector::ProcessInput (Node * node, int index, UseInfo use)
Definition at line 5181 of file simplified-lowering.cc.
                                                                  {
  DCHECK_IMPLIES(use.type_check() != TypeCheckKind::kNone,
                 !node->op()->HasProperty(Operator::kNoDeopt) &&
                     node->op()->EffectInputCount() > 0);
  EnqueueInput<PROPAGATE>(node, index, use);
}
References DCHECK_IMPLIES, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::HasProperty(), v8::internal::index, v8::internal::compiler::Operator::kNoDeopt, v8::internal::compiler::kNone, v8::internal::compiler::Node::op(), and use().
ProcessInput() [3/4]
template<>
void v8::internal::compiler::RepresentationSelector::ProcessInput (Node * node, int index, UseInfo use)
Definition at line 5190 of file simplified-lowering.cc.
                                                               {
  DCHECK_IMPLIES(use.type_check() != TypeCheckKind::kNone,
                 !node->op()->HasProperty(Operator::kNoDeopt) &&
                     node->op()->EffectInputCount() > 0);
}
References DCHECK_IMPLIES, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::Operator::kNoDeopt, v8::internal::compiler::kNone, v8::internal::compiler::Node::op(), and use().
ProcessInput() [4/4]
template<>
void v8::internal::compiler::RepresentationSelector::ProcessInput (Node * node, int index, UseInfo use)
Definition at line 5198 of file simplified-lowering.cc.
                                                              {
  DCHECK_IMPLIES(use.type_check() != TypeCheckKind::kNone,
                 !node->op()->HasProperty(Operator::kNoDeopt) &&
                     node->op()->EffectInputCount() > 0);
  ConvertInput(node, index, use);
}
References ConvertInput(), DCHECK_IMPLIES, v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::Operator::HasProperty(), v8::internal::index, v8::internal::compiler::Operator::kNoDeopt, v8::internal::compiler::kNone, v8::internal::compiler::Node::op(), and use().
ProcessRemainingInputs() [1/2]
template<Phase T>
void v8::internal::compiler::RepresentationSelector::ProcessRemainingInputs (Node * node, int index) [inline]
Definition at line 1071 of file simplified-lowering.cc.
                                                     {
    static_assert(retype<T>() || lower<T>(),
                  "This version of ProcessRemainingInputs has to be called in "
                  "the Retype or Lower phase.");
    DCHECK_GE(index, NodeProperties::PastValueIndex(node));
    DCHECK_GE(index, NodeProperties::PastContextIndex(node));
  }
References DCHECK_GE, v8::internal::index, v8::internal::compiler::NodeProperties::PastContextIndex(), and v8::internal::compiler::NodeProperties::PastValueIndex().
ProcessRemainingInputs() [2/2]
template<>
void v8::internal::compiler::RepresentationSelector::ProcessRemainingInputs (Node * node, int index)
Definition at line 5207 of file simplified-lowering.cc.
                                                                          {
  DCHECK_GE(index, NodeProperties::PastContextIndex(node));
  // Enqueue other inputs (effects, control).
  for (int i = std::max(index, NodeProperties::FirstEffectIndex(node));
       i < node->InputCount(); ++i) {
    EnqueueInput<PROPAGATE>(node, i);
  }
}
References DCHECK_GE, v8::internal::compiler::NodeProperties::FirstEffectIndex(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::compiler::Node::InputCount(), and v8::internal::compiler::NodeProperties::PastContextIndex().
propagate()
template<Phase T>
static constexpr bool v8::internal::compiler::RepresentationSelector::propagate () [inline], [static], [constexpr]
Definition at line 888 of file simplified-lowering.cc.
                                    {
    return T == PROPAGATE;
  }
References v8::internal::compiler::PROPAGATE.
PropagateTruncation()
void v8::internal::compiler::RepresentationSelector::PropagateTruncation (Node * node) [inline]
Definition at line 711 of file simplified-lowering.cc.
                                       {
    NodeInfo* info = GetInfo(node);
    info->set_visited();
    TRACE(" visit #%d: %s (trunc: %s)\n", node->id(), node->op()->mnemonic(),
          info->truncation().description());
    VisitNode<PROPAGATE>(node, info->truncation(), nullptr);
  }
References v8::internal::compiler::Truncation::description(), GetInfo(), v8::internal::compiler::Node::id(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::RepresentationSelector::NodeInfo::set_visited(), v8::internal::TRACE(), and v8::internal::compiler::RepresentationSelector::NodeInfo::truncation().
Referenced by RunPropagatePhase().
PushNodeToRevisitIfVisited()
void v8::internal::compiler::RepresentationSelector::PushNodeToRevisitIfVisited (Node * node) [inline]
Definition at line 685 of file simplified-lowering.cc.
                                              {
    NodeInfo* info = GetInfo(node);
    if (info->visited()) {
      TRACE(" QUEUEING #%d: %s\n", node->id(), node->op()->mnemonic());
      info->set_queued();
      revisit_queue_.push(node);
    }
  }
References GetInfo(), v8::internal::compiler::Node::id(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), revisit_queue_, v8::internal::compiler::RepresentationSelector::NodeInfo::set_queued(), v8::internal::TRACE(), and v8::internal::compiler::RepresentationSelector::NodeInfo::visited().
Referenced by RunRetypePhase().
ReplaceWithPureNode()
void v8::internal::compiler::RepresentationSelector::ReplaceWithPureNode (Node * node, Node * pure_node) [inline]
Definition at line 961 of file simplified-lowering.cc.
                                                        {
    DCHECK(pure_node->op()->HasProperty(Operator::kPure));
    if (node->op()->EffectInputCount() > 0) {
      DCHECK_LT(0, node->op()->ControlInputCount());
      Node* control = NodeProperties::GetControlInput(node);
      Node* effect = NodeProperties::GetEffectInput(node);
      if (TypeOf(node).IsNone()) {
        ChangeToDeadValue(node, effect, control);
        return;
      }
      // Rewire the effect and control chains.
      ReplaceEffectControlUses(node, effect, control);
    } else {
      DCHECK_EQ(0, node->op()->ControlInputCount());
    }
    DeferReplacement(node, pure_node);
  }
References ChangeToDeadValue(), v8::internal::compiler::Operator::ControlInputCount(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, DeferReplacement(), v8::internal::compiler::Operator::EffectInputCount(), v8::internal::compiler::NodeProperties::GetControlInput(), v8::internal::compiler::NodeProperties::GetEffectInput(), v8::internal::compiler::Operator::HasProperty(), v8::internal::IsNone(), v8::internal::compiler::Operator::kPure, v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::ReplaceEffectControlUses(), and TypeOf().
Referenced by TryOptimizeBigInt64Shift(), and VisitNode().
ResetNodeInfoState()
void v8::internal::compiler::RepresentationSelector::ResetNodeInfoState () [inline]
Definition at line 397 of file simplified-lowering.cc.
                            {
    // Clean up for the next phase.
    for (NodeInfo& info : info_) {
      info.reset_state();
    }
  }
References info_.
Referenced by GenerateTraversal(), RunPropagatePhase(), and RunRetypePhase().
retype()
template<Phase T>
static constexpr bool v8::internal::compiler::RepresentationSelector::retype () [inline], [static], [constexpr]
Definition at line 893 of file simplified-lowering.cc.
                                 {
    return T == RETYPE;
  }
References v8::internal::compiler::RETYPE.
RetypeNode()
bool v8::internal::compiler::RepresentationSelector::RetypeNode (Node * node) [inline]
Definition at line 697 of file simplified-lowering.cc.
                              {
    NodeInfo* info = GetInfo(node);
    info->set_visited();
    bool updated = UpdateFeedbackType(node);
    TRACE(" visit #%d: %s\n", node->id(), node->op()->mnemonic());
    VisitNode<RETYPE>(node, info->truncation(), nullptr);
    TRACE(" ==> output %s\n", MachineReprToString(info->representation()));
    return updated;
  }
References GetInfo(), v8::internal::compiler::Node::id(), v8::internal::MachineReprToString(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::Node::op(), v8::internal::compiler::RepresentationSelector::NodeInfo::representation(), v8::internal::compiler::RepresentationSelector::NodeInfo::set_visited(), v8::internal::TRACE(), v8::internal::compiler::RepresentationSelector::NodeInfo::truncation(), and UpdateFeedbackType().
Referenced by RunRetypePhase().
Run()
void v8::internal::compiler::RepresentationSelector::Run (SimplifiedLowering * lowering) [inline]
Definition at line 868 of file simplified-lowering.cc.
                                         {
    GenerateTraversal();
    RunPropagatePhase();
    RunRetypePhase();
    RunLowerPhase(lowering);
    if (verification_enabled()) {
      RunVerifyPhase(lowering->info_);
    }
  }
References GenerateTraversal(), v8::internal::compiler::SimplifiedLowering::info_, RunLowerPhase(), RunPropagatePhase(), RunRetypePhase(), RunVerifyPhase(), and verification_enabled().
Referenced by v8::internal::compiler::SimplifiedLowering::LowerAllNodes().
RunLowerPhase()
void v8::internal::compiler::RepresentationSelector::RunLowerPhase (SimplifiedLowering * lowering) [inline]
Definition at line 772 of file simplified-lowering.cc.
                                                   {
    TRACE("--{Lower phase}--\n");
    for (auto it = traversal_nodes_.cbegin(); it != traversal_nodes_.cend();
         ++it) {
      Node* node = *it;
      NodeInfo* info = GetInfo(node);
      TRACE(" visit #%d: %s\n", node->id(), node->op()->mnemonic());
      // Reuse {VisitNode()} so the representation rules are in one place.
      SourcePositionTable::Scope scope(
          source_positions_, source_positions_->GetSourcePosition(node));
      NodeOriginTable::Scope origin_scope(node_origins_, "simplified lowering",
                                          node);
      VisitNode<LOWER>(node, info->truncation(), lowering);
    }
    // Perform the final replacements.
    for (NodeVector::iterator i = replacements_.begin();
         i != replacements_.end(); ++i) {
      Node* node = *i;
      Node* replacement = *(++i);
      node->ReplaceUses(replacement);
      node->Kill();
      // We also need to replace the node in the rest of the vector.
      for (NodeVector::iterator j = i + 1; j != replacements_.end(); ++j) {
        ++j;
        if (*j == node) *j = replacement;
      }
    }
  }
References v8::internal::ZoneVector< T >::begin(), v8::internal::ZoneVector< T >::cbegin(), v8::internal::ZoneVector< T >::cend(), v8::internal::ZoneVector< T >::end(), GetInfo(), v8::internal::compiler::SourcePositionTable::GetSourcePosition(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::id(), v8::internal::compiler::Node::Kill(), v8::internal::compiler::Operator::mnemonic(), node_origins_, v8::internal::compiler::Node::op(), replacements_, v8::internal::compiler::Node::ReplaceUses(), source_positions_, v8::internal::TRACE(), traversal_nodes_, and v8::internal::compiler::RepresentationSelector::NodeInfo::truncation().
Referenced by Run().
RunPropagatePhase()
void v8::internal::compiler::RepresentationSelector::RunPropagatePhase () [inline]
Definition at line 720 of file simplified-lowering.cc.
                           {
    TRACE("--{Propagate phase}--\n");
    ResetNodeInfoState();
    DCHECK(revisit_queue_.empty());
    // Process nodes in reverse post order, with End as the root.
    for (auto it = traversal_nodes_.crbegin(); it != traversal_nodes_.crend();
         ++it) {
      PropagateTruncation(*it);
      while (!revisit_queue_.empty()) {
        Node* node = revisit_queue_.front();
        revisit_queue_.pop();
        PropagateTruncation(node);
      }
    }
  }
References v8::internal::ZoneVector< T >::crbegin(), v8::internal::ZoneVector< T >::crend(), v8::internal::DCHECK(), PropagateTruncation(), ResetNodeInfoState(), revisit_queue_, v8::internal::TRACE(), and traversal_nodes_.
Referenced by Run().
RunRetypePhase()
void v8::internal::compiler::RepresentationSelector::RunRetypePhase () [inline]
Definition at line 739 of file simplified-lowering.cc.
                        {
    TRACE("--{Retype phase}--\n");
    ResetNodeInfoState();
    DCHECK(revisit_queue_.empty());
    for (auto it = traversal_nodes_.cbegin(); it != traversal_nodes_.cend();
         ++it) {
      Node* node = *it;
      if (!RetypeNode(node)) continue;
      auto revisit_it = might_need_revisit_.find(node);
      if (revisit_it == might_need_revisit_.end()) continue;
      for (Node* const user : revisit_it->second) {
        PushNodeToRevisitIfVisited(user);
      }
      // Process the revisit queue.
      while (!revisit_queue_.empty()) {
        Node* revisit_node = revisit_queue_.front();
        revisit_queue_.pop();
        if (!RetypeNode(revisit_node)) continue;
        // Here we need to check all uses since we can't easily know which
        // nodes will need to be revisited due to having an input which was
        // a revisited node.
        for (Node* const user : revisit_node->uses()) {
          PushNodeToRevisitIfVisited(user);
        }
      }
    }
  }
References v8::internal::ZoneVector< T >::cbegin(), v8::internal::ZoneVector< T >::cend(), v8::internal::DCHECK(), might_need_revisit_, PushNodeToRevisitIfVisited(), ResetNodeInfoState(), RetypeNode(), revisit_queue_, v8::internal::TRACE(), traversal_nodes_, and v8::internal::compiler::Node::uses().
Referenced by Run().
RunVerifyPhase()
void v8::internal::compiler::RepresentationSelector::RunVerifyPhase (OptimizedCompilationInfo * compilation_info) [inline]
Definition at line 802 of file simplified-lowering.cc.
                                                                  {
    DCHECK_NOT_NULL(verifier_);
    TRACE("--{Verify Phase}--\n");
    // Patch pending type overrides.
    for (const auto& [constant, uses] :
         verifier_->machine_uses_of_constants()) {
      Node* typed_constant =
          InsertTypeOverrideForVerifier(Type::Machine(), constant);
      for (auto use : uses) {
        for (int i = 0; i < use->InputCount(); ++i) {
          if (use->InputAt(i) == constant) {
            use->ReplaceInput(i, typed_constant);
          }
        }
      }
    }
    // Generate a new traversal containing all the new nodes created during
    // lowering.
    GenerateTraversal();
    // Set node types to the refined types computed during retyping.
    for (Node* node : traversal_nodes_) {
      NodeInfo* info = GetInfo(node);
      if (!info->feedback_type().IsInvalid()) {
        NodeProperties::SetType(node, info->feedback_type());
      }
    }
    // Print graph.
    if (compilation_info != nullptr && compilation_info->trace_turbo_json()) {
      UnparkedScopeIfNeeded scope(broker_);
      AllowHandleDereference allow_deref;
      TurboJsonFile json_of(compilation_info, std::ios_base::app);
      JSONGraphWriter writer(json_of, graph(), source_positions_,
                             node_origins_);
      writer.PrintPhase("V8.TFSimplifiedLowering [after lower]");
    }
    // Verify all nodes.
    for (Node* node : traversal_nodes_) {
      verifier_->VisitNode(node, op_typer_);
    }
    // Print graph.
    if (compilation_info != nullptr && compilation_info->trace_turbo_json()) {
      UnparkedScopeIfNeeded scope(broker_);
      AllowHandleDereference allow_deref;
      TurboJsonFile json_of(compilation_info, std::ios_base::app);
      JSONGraphWriterWithVerifierTypes writer(
          json_of, graph(), source_positions_, node_origins_, verifier_);
      writer.PrintPhase("V8.TFSimplifiedLowering [after verify]");
    }
    // Eliminate all introduced hints.
    for (Node* node : verifier_->inserted_hints()) {
      Node* input = node->InputAt(0);
      node->ReplaceUses(input);
      node->Kill();
    }
  }
References broker_, DCHECK_NOT_NULL, v8::internal::compiler::RepresentationSelector::NodeInfo::feedback_type(), GenerateTraversal(), GetInfo(), graph(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::SimplifiedLoweringVerifier::inserted_hints(), InsertTypeOverrideForVerifier(), v8::internal::compiler::Type::IsInvalid(), v8::internal::compiler::SimplifiedLoweringVerifier::machine_uses_of_constants(), node_origins_, op_typer_, v8::internal::compiler::JSONGraphWriter::PrintPhase(), v8::internal::compiler::Node::ReplaceUses(), v8::internal::compiler::NodeProperties::SetType(), source_positions_, v8::internal::TRACE(), traversal_nodes_, use(), verifier_, and v8::internal::compiler::SimplifiedLoweringVerifier::VisitNode().
Referenced by Run().
SetOutput() [1/4]
template<>
void v8::internal::compiler::RepresentationSelector::SetOutput (Node * node, MachineRepresentation representation, Type restriction_type)
Definition at line 5151 of file simplified-lowering.cc.
                                                                             {
  NodeInfo* const info = GetInfo(node);
  info->set_restriction_type(restriction_type);
}
References GetInfo(), and v8::internal::compiler::RepresentationSelector::NodeInfo::set_restriction_type().
SetOutput() [2/4]
template<>
void v8::internal::compiler::RepresentationSelector::SetOutput (Node * node, MachineRepresentation representation, Type restriction_type)
Definition at line 5158 of file simplified-lowering.cc.
                                                                             {
  NodeInfo* const info = GetInfo(node);
  Type node_static_type = NodeProperties::GetTypeOrAny(node);
  DCHECK(Type::Intersect(restriction_type, node_static_type, zone_)
             .Is(info->restriction_type()));
  USE(node_static_type);
  info->set_output(representation);
}
References v8::internal::DCHECK(), GetInfo(), v8::internal::compiler::NodeProperties::GetTypeOrAny(), v8::internal::compiler::Type::Intersect(), v8::internal::Is(), v8::internal::compiler::RepresentationSelector::NodeInfo::restriction_type(), v8::internal::compiler::RepresentationSelector::NodeInfo::set_output(), USE, and zone_.
SetOutput() [3/4]
template<>
void v8::internal::compiler::RepresentationSelector::SetOutput (Node * node, MachineRepresentation representation, Type restriction_type)
Definition at line 5169 of file simplified-lowering.cc.
                                                                             {
  NodeInfo* const info = GetInfo(node);
  Type node_static_type = NodeProperties::GetTypeOrAny(node);
  DCHECK_EQ(info->representation(), representation);
  DCHECK(Type::Intersect(restriction_type, node_static_type, zone_)
             .Is(info->restriction_type()));
  USE(node_static_type);
  USE(info);
}
References v8::internal::DCHECK(), DCHECK_EQ, GetInfo(), v8::internal::compiler::NodeProperties::GetTypeOrAny(), v8::internal::compiler::Type::Intersect(), v8::internal::Is(), v8::internal::compiler::RepresentationSelector::NodeInfo::representation(), v8::internal::compiler::RepresentationSelector::NodeInfo::restriction_type(), USE, and zone_.
SetOutput() [4/4]
template<Phase T>
void v8::internal::compiler::RepresentationSelector::SetOutput (Node * node, MachineRepresentation representation, Type restriction_type = Type::Any())
simplified()
SimplifiedOperatorBuilder* v8::internal::compiler::RepresentationSelector::simplified () const [inline]
Definition at line 1662 of file simplified-lowering.cc.
                                                {
    return jsgraph_->simplified();
  }
References jsgraph_, and v8::internal::compiler::JSGraph::simplified().
Referenced by VisitCheckBounds(), VisitForCheckedInt32Mul(), and VisitNode().
true_type()
Type v8::internal::compiler::RepresentationSelector::true_type () const [inline], [private]
Definition at line 5069 of file simplified-lowering.cc.
{ return singleton_true_; }
References singleton_true_.
Referenced by VisitNode(), and VisitObjectIs().
TryOptimizeBigInt64Shift()
template<Phase T>
bool v8::internal::compiler::RepresentationSelector::TryOptimizeBigInt64Shift (Node * node, const Truncation & truncation, SimplifiedLowering * lowering) [inline]
Definition at line 2254 of file simplified-lowering.cc.
                                                              {
    DCHECK(Is64());
    if (!truncation.IsUsedAsWord64()) return false;
    Type input_type = GetUpperBound(node->InputAt(0));
    Type shift_amount_type = GetUpperBound(node->InputAt(1));
    if (!shift_amount_type.IsHeapConstant()) return false;
    HeapObjectRef ref = shift_amount_type.AsHeapConstant()->Ref();
    if (!ref.IsBigInt()) return false;
    BigIntRef bigint = ref.AsBigInt();
    bool lossless = false;
    int64_t shift_amount = bigint.AsInt64(&lossless);
    // We bail out if we cannot represent the shift amount correctly.
    if (!lossless) return false;
    // Canonicalize {shift_amount}.
    bool is_shift_left =
        node->opcode() == IrOpcode::kSpeculativeBigIntShiftLeft;
    if (shift_amount < 0) {
      // A shift amount of abs(std::numeric_limits<int64_t>::min()) is not
      // representable.
      if (shift_amount == std::numeric_limits<int64_t>::min()) return false;
      is_shift_left = !is_shift_left;
      shift_amount = -shift_amount;
      DCHECK_GT(shift_amount, 0);
    }
    DCHECK_GE(shift_amount, 0);
    // If the operation is a *real* left shift, propagate truncation.
    // If it is a *real* right shift, the output representation is
    // word64 only if we know the input type is BigInt64.
    // Otherwise, fall through to using BigIntOperationHint.
    if (is_shift_left) {
      VisitBinop<T>(node,
                    UseInfo::CheckedBigIntTruncatingWord64(FeedbackSource{}),
                    UseInfo::Any(), MachineRepresentation::kWord64);
      if (lower<T>()) {
        if (shift_amount > 63) {
          DeferReplacement(node, jsgraph_->Int64Constant(0));
        } else if (shift_amount == 0) {
          DeferReplacement(node, node->InputAt(0));
        } else {
          DCHECK_GE(shift_amount, 1);
          DCHECK_LE(shift_amount, 63);
          ReplaceWithPureNode(
              node, graph()->NewNode(lowering->machine()->Word64Shl(),
                                     node->InputAt(0),
                                     jsgraph_->Int64Constant(shift_amount)));
        }
      }
      return true;
    } else if (input_type.Is(Type::SignedBigInt64())) {
      VisitBinop<T>(node,
                    UseInfo::CheckedBigIntTruncatingWord64(FeedbackSource{}),
                    UseInfo::Any(), MachineRepresentation::kWord64);
      if (lower<T>()) {
        if (shift_amount > 63) {
          ReplaceWithPureNode(
              node,
              graph()->NewNode(lowering->machine()->Word64Sar(),
                               node->InputAt(0), jsgraph_->Int64Constant(63)));
        } else if (shift_amount == 0) {
          DeferReplacement(node, node->InputAt(0));
        } else {
          DCHECK_GE(shift_amount, 1);
          DCHECK_LE(shift_amount, 63);
          ReplaceWithPureNode(
              node, graph()->NewNode(lowering->machine()->Word64Sar(),
                                     node->InputAt(0),
                                     jsgraph_->Int64Constant(shift_amount)));
        }
      }
      return true;
    } else if (input_type.Is(Type::UnsignedBigInt64())) {
      VisitBinop<T>(node,
                    UseInfo::CheckedBigIntTruncatingWord64(FeedbackSource{}),
                    UseInfo::Any(), MachineRepresentation::kWord64);
      if (lower<T>()) {
        if (shift_amount > 63) {
          DeferReplacement(node, jsgraph_->Int64Constant(0));
        } else if (shift_amount == 0) {
          DeferReplacement(node, node->InputAt(0));
        } else {
          DCHECK_GE(shift_amount, 1);
          DCHECK_LE(shift_amount, 63);
          ReplaceWithPureNode(
              node, graph()->NewNode(lowering->machine()->Word64Shr(),
                                     node->InputAt(0),
                                     jsgraph_->Int64Constant(shift_amount)));
        }
      }
      return true;
    }
    // None of the cases we can optimize here.
    return false;
  }
References v8::internal::compiler::UseInfo::Any(), v8::internal::compiler::Type::AsHeapConstant(), v8::internal::compiler::BigIntRef::AsInt64(), v8::internal::compiler::UseInfo::CheckedBigIntTruncatingWord64(), v8::internal::DCHECK(), DCHECK_GE, DCHECK_GT, DCHECK_LE, DeferReplacement(), GetUpperBound(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::MachineGraph::Int64Constant(), v8::internal::compiler::Type::Is(), v8::internal::Is64(), v8::internal::compiler::Type::IsHeapConstant(), v8::internal::compiler::Truncation::IsUsedAsWord64(), jsgraph_, v8::internal::kWord64, v8::internal::compiler::SimplifiedLowering::machine(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::HeapConstantType::Ref(), ReplaceWithPureNode(), v8::internal::compiler::MachineOperatorBuilder::Word64Sar(), v8::internal::compiler::MachineOperatorBuilder::Word64Shl(), and v8::internal::compiler::MachineOperatorBuilder::Word64Shr().
TypeOf()
Type v8::internal::compiler::RepresentationSelector::TypeOf (Node * node) [inline]
Definition at line 404 of file simplified-lowering.cc.
                          {
    Type type = GetInfo(node)->feedback_type();
    return type.IsInvalid() ? NodeProperties::GetType(node) : type;
  }
References v8::internal::compiler::RepresentationSelector::NodeInfo::feedback_type(), GetInfo(), v8::internal::compiler::NodeProperties::GetType(), and v8::internal::tracing::type.
Referenced by CanSpeculateAdditiveSafeInteger(), ChangeToDeadValue(), ChangeToPureOp(), ChangeUnaryToPureBinaryOp(), ConvertInput(), InsertUnreachableIfNecessary(), ReplaceWithPureNode(), VisitCheckBounds(), VisitFrameState(), VisitNode(), VisitNoop(), VisitObjectIs(), VisitObjectState(), VisitPhi(), VisitSelect(), VisitSpeculativeAdditiveOp(), VisitSpeculativeNumberModulus(), VisitSpeculativeSmallIntegerAdditiveOp(), and VisitStateValues().
TypePhi()
Type v8::internal::compiler::RepresentationSelector::TypePhi (Node * node) [inline]
Definition at line 414 of file simplified-lowering.cc.
                           {
    int arity = node->op()->ValueInputCount();
    Type type = FeedbackTypeOf(node->InputAt(0));
    for (int i = 1; i < arity; ++i) {
      type = op_typer_.Merge(type, FeedbackTypeOf(node->InputAt(i)));
    }
    return type;
  }
References FeedbackTypeOf(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::OperationTyper::Merge(), v8::internal::compiler::Node::op(), op_typer_, v8::internal::tracing::type, and v8::internal::compiler::Operator::ValueInputCount().
Referenced by UpdateFeedbackType().
TypeSelect()
Type v8::internal::compiler::RepresentationSelector::TypeSelect (Node * node) [inline]
Definition at line 423 of file simplified-lowering.cc.
                              {
    return op_typer_.Merge(FeedbackTypeOf(node->InputAt(1)),
                           FeedbackTypeOf(node->InputAt(2)));
  }
References FeedbackTypeOf(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::OperationTyper::Merge(), and op_typer_.
Referenced by UpdateFeedbackType().
Uint32Op()
const Operator* v8::internal::compiler::RepresentationSelector::Uint32Op (Node * node) [inline]
Definition at line 1584 of file simplified-lowering.cc.
                                       {
    return changer_->Uint32OperatorFor(node->opcode());
  }
References changer_, v8::internal::compiler::Node::opcode(), and v8::internal::compiler::RepresentationChanger::Uint32OperatorFor().
Referenced by VisitNode().
Uint32OverflowOp()
const Operator* v8::internal::compiler::RepresentationSelector::Uint32OverflowOp (Node * node) [inline]
Definition at line 1588 of file simplified-lowering.cc.
                                               {
    return changer_->Uint32OverflowOperatorFor(node->opcode());
  }
References changer_, v8::internal::compiler::Node::opcode(), and v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor().
Referenced by ChangeToUint32OverflowOp().
UpdateFeedbackType()
bool v8::internal::compiler::RepresentationSelector::UpdateFeedbackType (Node * node) [inline]
Definition at line 428 of file simplified-lowering.cc.
                                      {
    if (node->op()->ValueOutputCount() == 0) return false;
    if ((IrOpcode::IsMachineOpcode(node->opcode()) ||
         IrOpcode::IsMachineConstantOpcode(node->opcode())) &&
        node->opcode() != IrOpcode::kLoadFramePointer) {
      DCHECK(NodeProperties::GetType(node).Is(Type::Machine()));
    }
    // For any non-phi node just wait until we get all inputs typed. We only
    // allow untyped inputs for phi nodes because phis are the only places
    // where cycles need to be broken.
    if (node->opcode() != IrOpcode::kPhi) {
      for (int i = 0; i < node->op()->ValueInputCount(); i++) {
        if (GetInfo(node->InputAt(i))->feedback_type().IsInvalid()) {
          return false;
        }
      }
    }
    NodeInfo* info = GetInfo(node);
    Type type = info->feedback_type();
    Type new_type = NodeProperties::GetType(node);
    // We preload these values here to avoid increasing the binary size too
    // much, which happens if we inline the calls into the macros below.
    Type input0_type;
    if (node->InputCount() > 0) input0_type = FeedbackTypeOf(node->InputAt(0));
    Type input1_type;
    if (node->InputCount() > 1) input1_type = FeedbackTypeOf(node->InputAt(1));
    switch (node->opcode()) {
#define DECLARE_CASE(Name) \
  case IrOpcode::k##Name: { \
    new_type = op_typer_.Name(input0_type, input1_type); \
    break; \
  }
      SIMPLIFIED_NUMBER_BINOP_LIST(DECLARE_CASE)
      DECLARE_CASE(SameValue)
#undef DECLARE_CASE
#define DECLARE_CASE(Name) \
  case IrOpcode::k##Name: { \
    new_type = Type::Intersect(op_typer_.Name(input0_type, input1_type), \
                               info->restriction_type(), graph_zone()); \
    break; \
  }
      SIMPLIFIED_SPECULATIVE_NUMBER_BINOP_LIST(DECLARE_CASE)
      SIMPLIFIED_SPECULATIVE_BIGINT_BINOP_LIST(DECLARE_CASE)
#undef DECLARE_CASE
#define DECLARE_CASE(Name) \
  case IrOpcode::k##Name: { \
    new_type = op_typer_.Name(input0_type); \
    break; \
  }
      SIMPLIFIED_NUMBER_UNOP_LIST(DECLARE_CASE)
#undef DECLARE_CASE
#define DECLARE_CASE(Name) \
  case IrOpcode::k##Name: { \
    new_type = Type::Intersect(op_typer_.Name(input0_type), \
                               info->restriction_type(), graph_zone()); \
    break; \
  }
      SIMPLIFIED_SPECULATIVE_NUMBER_UNOP_LIST(DECLARE_CASE)
#undef DECLARE_CASE
      case IrOpcode::kConvertReceiver:
        new_type = op_typer_.ConvertReceiver(input0_type);
        break;
      case IrOpcode::kPlainPrimitiveToNumber:
        new_type = op_typer_.ToNumber(input0_type);
        break;
      case IrOpcode::kCheckBounds:
        new_type =
            Type::Intersect(op_typer_.CheckBounds(input0_type, input1_type),
                            info->restriction_type(), graph_zone());
        break;
      case IrOpcode::kCheckFloat64Hole:
        new_type = Type::Intersect(op_typer_.CheckFloat64Hole(input0_type),
                                   info->restriction_type(), graph_zone());
        break;
      case IrOpcode::kCheckNumber:
        new_type = Type::Intersect(op_typer_.CheckNumber(input0_type),
                                   info->restriction_type(), graph_zone());
        break;
      case IrOpcode::kCheckNumberOrUndefined:
        new_type =
            Type::Intersect(op_typer_.CheckNumberOrUndefined(input0_type),
                            info->restriction_type(), graph_zone());
        break;
      case IrOpcode::kCheckNumberFitsInt32:
        new_type = Type::Intersect(op_typer_.CheckNumberFitsInt32(input0_type),
                                   info->restriction_type(), graph_zone());
        break;
      case IrOpcode::kPhi: {
        new_type = TypePhi(node);
        if (!type.IsInvalid()) {
          new_type = Weaken(node, type, new_type);
        }
        break;
      }
      case IrOpcode::kConvertTaggedHoleToUndefined:
        new_type = op_typer_.ConvertTaggedHoleToUndefined(
            FeedbackTypeOf(node->InputAt(0)));
        break;
      case IrOpcode::kTypeGuard: {
        new_type = op_typer_.TypeTypeGuard(node->op(),
                                           FeedbackTypeOf(node->InputAt(0)));
        break;
      }
      case IrOpcode::kSelect: {
        const auto& p = SelectParametersOf(node->op());
        if (p.semantics() == BranchSemantics::kMachine) {
          if (type.IsInvalid()) {
            GetInfo(node)->set_feedback_type(NodeProperties::GetType(node));
            return true;
          }
          return false;
        }
        new_type = TypeSelect(node);
        break;
      }
      default:
        // Shortcut for operations that we do not handle.
        if (type.IsInvalid()) {
          GetInfo(node)->set_feedback_type(NodeProperties::GetType(node));
          return true;
        }
        return false;
    }
    // We need to guarantee that the feedback type is a subtype of the upper
    // bound. Naively that should hold, but weakening can actually produce
    // a bigger type if we are unlucky with ordering of phi typing. To be
    // really sure, just intersect the upper bound with the feedback type.
    new_type = Type::Intersect(GetUpperBound(node), new_type, graph_zone());
    if (!type.IsInvalid() && new_type.Is(type)) return false;
    GetInfo(node)->set_feedback_type(new_type);
    if (v8_flags.trace_representation) {
      PrintNodeFeedbackType(node);
    }
    return true;
  }
References v8::internal::compiler::OperationTyper::CheckBounds(), v8::internal::compiler::OperationTyper::CheckFloat64Hole(), v8::internal::compiler::OperationTyper::CheckNumber(), v8::internal::compiler::OperationTyper::CheckNumberFitsInt32(), v8::internal::compiler::OperationTyper::CheckNumberOrUndefined(), v8::internal::compiler::OperationTyper::ConvertTaggedHoleToUndefined(), v8::internal::DCHECK(), DECLARE_CASE, v8::internal::compiler::RepresentationSelector::NodeInfo::feedback_type(), FeedbackTypeOf(), GetInfo(), v8::internal::compiler::NodeProperties::GetType(), GetUpperBound(), graph_zone(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::Type::Intersect(), v8::internal::Is(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Type::IsInvalid(), v8::internal::compiler::IrOpcode::IsMachineConstantOpcode(), v8::internal::compiler::IrOpcode::IsMachineOpcode(), v8::internal::compiler::kMachine, v8::internal::compiler::Node::op(), op_typer_, v8::internal::compiler::Node::opcode(), PrintNodeFeedbackType(), v8::internal::compiler::RepresentationSelector::NodeInfo::restriction_type(), v8::internal::maglev::anonymous_namespace{maglev-interpreter-frame-state.cc}::SameValue(), v8::internal::compiler::SelectParametersOf(), v8::internal::compiler::RepresentationSelector::NodeInfo::set_feedback_type(), SIMPLIFIED_NUMBER_BINOP_LIST, SIMPLIFIED_NUMBER_UNOP_LIST, SIMPLIFIED_SPECULATIVE_BIGINT_BINOP_LIST, SIMPLIFIED_SPECULATIVE_NUMBER_BINOP_LIST, SIMPLIFIED_SPECULATIVE_NUMBER_UNOP_LIST, v8::internal::compiler::OperationTyper::ToNumber(), v8::internal::tracing::type, TypePhi(), TypeSelect(), v8::internal::compiler::OperationTyper::TypeTypeGuard(), v8::internal::v8_flags, v8::internal::compiler::Operator::ValueOutputCount(), and Weaken().
Referenced by RetypeNode().
UseInfoForFastApiCallArgument()
UseInfo v8::internal::compiler::RepresentationSelector::UseInfoForFastApiCallArgument (CTypeInfo type, CFunctionInfo::Int64Representation repr, FeedbackSource const & feedback) [inline]
Definition at line 2092 of file simplified-lowering.cc.
                                                                        {
    START_ALLOW_USE_DEPRECATED()
    switch (type.GetSequenceType()) {
      case CTypeInfo::SequenceType::kScalar: {
        uint8_t flags = uint8_t(type.GetFlags());
        if (flags & uint8_t(CTypeInfo::Flags::kEnforceRangeBit) ||
            flags & uint8_t(CTypeInfo::Flags::kClampBit)) {
          DCHECK(repr != CFunctionInfo::Int64Representation::kBigInt);
          // If the parameter is marked as `kEnforceRange` or `kClampBit`, then
          // special type conversion gets added explicitly to the generated
          // code. Therefore it is sufficient here to only require here that the
          // value is a Float64, even though the C++ signature actually asks for
          // an `int32_t`.
          return UseInfo::CheckedNumberAsFloat64(kIdentifyZeros, feedback);
        }
        switch (type.GetType()) {
          case CTypeInfo::Type::kVoid:
          case CTypeInfo::Type::kUint8:
            UNREACHABLE();
          case CTypeInfo::Type::kBool:
            return UseInfo::Bool();
          case CTypeInfo::Type::kInt32:
          case CTypeInfo::Type::kUint32:
            return UseInfo::CheckedNumberAsWord32(feedback);
          // TODO(mslekova): We deopt for unsafe integers, but ultimately we
          // want to make this less restrictive in order to stay on the fast
          // path.
          case CTypeInfo::Type::kInt64:
          case CTypeInfo::Type::kUint64:
            if (repr == CFunctionInfo::Int64Representation::kBigInt) {
              return UseInfo::CheckedBigIntTruncatingWord64(feedback);
            } else if (repr == CFunctionInfo::Int64Representation::kNumber) {
              return UseInfo::CheckedSigned64AsWord64(kIdentifyZeros, feedback);
            } else {
              UNREACHABLE();
            }
          case CTypeInfo::Type::kAny:
            return UseInfo::CheckedSigned64AsWord64(kIdentifyZeros, feedback);
          case CTypeInfo::Type::kFloat32:
          case CTypeInfo::Type::kFloat64:
            return UseInfo::CheckedNumberAsFloat64(kDistinguishZeros, feedback);
          case CTypeInfo::Type::kPointer:
          case CTypeInfo::Type::kV8Value:
          case CTypeInfo::Type::kSeqOneByteString:
          case CTypeInfo::Type::kApiObject:
            return UseInfo::AnyTagged();
        }
      }
      case CTypeInfo::SequenceType::kIsSequence: {
        CHECK_EQ(type.GetType(), CTypeInfo::Type::kVoid);
        return UseInfo::AnyTagged();
      }
      default: {
        UNREACHABLE(); // TODO(mslekova): Implement array buffers.
      }
    }
    END_ALLOW_USE_DEPRECATED()
  }
References v8::internal::compiler::UseInfo::AnyTagged(), v8::internal::compiler::UseInfo::Bool(), CHECK_EQ, v8::internal::compiler::UseInfo::CheckedBigIntTruncatingWord64(), v8::internal::compiler::UseInfo::CheckedNumberAsFloat64(), v8::internal::compiler::UseInfo::CheckedNumberAsWord32(), v8::internal::compiler::UseInfo::CheckedSigned64AsWord64(), v8::internal::DCHECK(), END_ALLOW_USE_DEPRECATED, v8::internal::flags, v8::CTypeInfo::kAny, v8::CTypeInfo::kApiObject, v8::CFunctionInfo::kBigInt, v8::CTypeInfo::kBool, v8::CTypeInfo::kClampBit, v8::internal::compiler::kDistinguishZeros, v8::CTypeInfo::kEnforceRangeBit, v8::CTypeInfo::kFloat32, v8::CTypeInfo::kFloat64, v8::internal::compiler::kIdentifyZeros, v8::CTypeInfo::kInt32, v8::CTypeInfo::kInt64, v8::CFunctionInfo::kNumber, v8::CTypeInfo::kPointer, v8::CTypeInfo::kSeqOneByteString, v8::CTypeInfo::kUint32, v8::CTypeInfo::kUint64, v8::CTypeInfo::kUint8, v8::CTypeInfo::kV8Value, v8::CTypeInfo::kVoid, START_ALLOW_USE_DEPRECATED, v8::internal::tracing::type, and v8::internal::UNREACHABLE().
Referenced by VisitFastApiCall().
verification_enabled()
bool v8::internal::compiler::RepresentationSelector::verification_enabled () const [inline]
Definition at line 395 of file simplified-lowering.cc.
{ return verifier_ != nullptr; }
References verifier_.
Referenced by InsertSemanticsHintForVerifier(), InsertTypeOverrideForVerifier(), Run(), and VisitNode().
VisitBinop() [1/2]
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitBinop (Node * node, UseInfo input_use, MachineRepresentation output, Type restriction_type = Type::Any()) [inline]
Definition at line 1159 of file simplified-lowering.cc.
                                                     {
    VisitBinop<T>(node, input_use, input_use, output, restriction_type);
  }
VisitBinop() [2/2]
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitBinop (Node * node, UseInfo left_use, UseInfo right_use, MachineRepresentation output, Type restriction_type = Type::Any()) [inline]
Definition at line 1145 of file simplified-lowering.cc.
                                                     {
    DCHECK_EQ(2, node->op()->ValueInputCount());
    ProcessInput<T>(node, 0, left_use);
    ProcessInput<T>(node, 1, right_use);
    for (int i = 2; i < node->InputCount(); i++) {
      EnqueueInput<T>(node, i);
    }
    SetOutput<T>(node, output, restriction_type);
  }
References DCHECK_EQ, v8::internal::compiler::Node::InputCount(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::ValueInputCount().
VisitCall()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitCall (Node * node, SimplifiedLowering * lowering) [inline]
Definition at line 1334 of file simplified-lowering.cc.
                                                           {
    auto call_descriptor = CallDescriptorOf(node->op());
    int params = static_cast<int>(call_descriptor->ParameterCount());
    int value_input_count = node->op()->ValueInputCount();
    DCHECK_GT(value_input_count, 0);
    DCHECK_GE(value_input_count, params);
    // The target of the call.
    ProcessInput<T>(node, 0, UseInfo::Any());
    // For the parameters (indexes [1, ..., params]), propagate representation
    // information from call descriptor.
    for (int i = 1; i <= params; i++) {
      ProcessInput<T>(node, i,
                      TruncatingUseInfoFromRepresentation(
                          call_descriptor->GetInputType(i).representation()));
    }
    // Rest of the value inputs.
    for (int i = params + 1; i < value_input_count; i++) {
      ProcessInput<T>(node, i, UseInfo::AnyTagged());
    }
    // Effect and Control.
    ProcessRemainingInputs<T>(node, value_input_count);
    if (call_descriptor->ReturnCount() > 0) {
      SetOutput<T>(node, call_descriptor->GetReturnType(0).representation());
    } else {
      SetOutput<T>(node, MachineRepresentation::kTagged);
    }
  }
References v8::internal::compiler::UseInfo::Any(), v8::internal::compiler::UseInfo::AnyTagged(), v8::internal::compiler::CallDescriptorOf(), DCHECK_GE, DCHECK_GT, v8::internal::kTagged, v8::internal::compiler::Node::op(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::TruncatingUseInfoFromRepresentation(), and v8::internal::compiler::Operator::ValueInputCount().
VisitCheck()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitCheck (Node * node, Type type, SimplifiedLowering * lowering) [inline]
Definition at line 1321 of file simplified-lowering.cc.
                                                                       {
    if (InputIs(node, type)) {
      VisitUnop<T>(node, UseInfo::AnyTagged(),
                   MachineRepresentation::kTaggedPointer);
      if (lower<T>()) DeferReplacement(node, node->InputAt(0));
    } else {
      VisitUnop<T>(node,
                   UseInfo::CheckedHeapObjectAsTaggedPointer(FeedbackSource()),
                   MachineRepresentation::kTaggedPointer);
    }
  }
References v8::internal::compiler::UseInfo::AnyTagged(), v8::internal::compiler::UseInfo::CheckedHeapObjectAsTaggedPointer(), DeferReplacement(), v8::internal::compiler::Node::InputAt(), InputIs(), v8::internal::kTaggedPointer, and v8::internal::tracing::type.
VisitCheckBounds()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitCheckBounds (Node * node, SimplifiedLowering * lowering) [inline]
Definition at line 2001 of file simplified-lowering.cc.
                                                                  {
    CheckBoundsParameters const& p = CheckBoundsParametersOf(node->op());
    FeedbackSource const& feedback = p.check_parameters().feedback();
    Type const index_type = TypeOf(node->InputAt(0));
    Type const length_type = TypeOf(node->InputAt(1));
    const bool allow_64_bit = (p.flags() & CheckBoundsFlag::kAllow64BitBounds);
    // Conversions, if requested and needed, will be handled by the
    // representation changer, not by the lower-level Checked*Bounds operators.
    CheckBoundsFlags new_flags =
        p.flags().without(CheckBoundsFlag::kConvertStringAndMinusZero);
    if (length_type.Is(Type::Unsigned31())) {
      if (index_type.Is(Type::Integral32()) ||
          (index_type.Is(Type::Integral32OrMinusZero()) &&
           p.flags() & CheckBoundsFlag::kConvertStringAndMinusZero)) {
        // Map the values in the [-2^31,-1] range to the [2^31,2^32-1] range,
        // which will be considered out-of-bounds because the {length_type} is
        // limited to Unsigned31. This also converts -0 to 0.
        VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                      MachineRepresentation::kWord32);
        if (lower<T>()) {
          if (index_type.IsNone() || length_type.IsNone() ||
              (index_type.Min() >= 0.0 &&
               index_type.Max() < length_type.Min())) {
            // The bounds check is redundant if we already know that
            // the index is within the bounds of [0.0, length[.
            // TODO(neis): Move this into TypedOptimization?
            if (v8_flags.turbo_typer_hardening) {
              new_flags |= CheckBoundsFlag::kAbortOnOutOfBounds;
            } else {
              DeferReplacement(node, NodeProperties::GetValueInput(node, 0));
              return;
            }
          }
          ChangeOp(node,
                   simplified()->CheckedUint32Bounds(feedback, new_flags));
        }
      } else if (p.flags() & CheckBoundsFlag::kConvertStringAndMinusZero) {
        if (jsgraph_->machine()->Is64()) {
          const auto index_use = UseInfo::CheckedTaggedAsArrayIndex(feedback);
          const auto bound_use =
              allow_64_bit ? UseInfo::Word64() : UseInfo::TruncatingWord32();
          VisitBinop<T>(node, index_use, bound_use,
                        MachineRepresentation::kWord64);
          if (lower<T>()) {
            if (allow_64_bit) {
              ChangeOp(node,
                       simplified()->CheckedUint64Bounds(feedback, new_flags));
            } else {
              Node* bound = node->InputAt(1);
              Node* zero_extended = graph()->NewNode(
                  lowering->machine()->ChangeUint32ToUint64(), bound);
              node->ReplaceInput(1, zero_extended);
              ChangeOp(node,
                       simplified()->CheckedUint64Bounds(feedback, new_flags));
            }
          }
        } else {
          VisitBinop<T>(node, UseInfo::CheckedTaggedAsArrayIndex(feedback),
                        UseInfo::Word(), MachineType::PointerRepresentation());
          if (lower<T>()) {
            ChangeOp(node,
                     simplified()->CheckedUint32Bounds(feedback, new_flags));
          }
        }
      } else {
        VisitBinop<T>(
            node, UseInfo::CheckedSigned32AsWord32(kDistinguishZeros, feedback),
            UseInfo::TruncatingWord32(), MachineRepresentation::kWord32);
        if (lower<T>()) {
          ChangeOp(node,
                   simplified()->CheckedUint32Bounds(feedback, new_flags));
        }
      }
    } else {
      CHECK(length_type.Is(type_cache_->kPositiveSafeInteger));
      CHECK(allow_64_bit);
      IdentifyZeros zero_handling =
          (p.flags() & CheckBoundsFlag::kConvertStringAndMinusZero)
              ? kIdentifyZeros
              : kDistinguishZeros;
      VisitBinop<T>(node,
                    UseInfo::CheckedSigned64AsWord64(zero_handling, feedback),
                    UseInfo::Word64(), MachineRepresentation::kWord64);
      if (lower<T>()) {
        ChangeOp(node, simplified()->CheckedUint64Bounds(feedback, new_flags));
      }
    }
  }
References ChangeOp(), v8::internal::compiler::MachineOperatorBuilder::ChangeUint32ToUint64(), CHECK, v8::internal::compiler::CheckBoundsParameters::check_parameters(), v8::internal::compiler::CheckBoundsParametersOf(), v8::internal::compiler::UseInfo::CheckedSigned32AsWord32(), v8::internal::compiler::UseInfo::CheckedSigned64AsWord64(), v8::internal::compiler::UseInfo::CheckedTaggedAsArrayIndex(), DeferReplacement(), v8::internal::compiler::CheckParameters::feedback(), v8::internal::compiler::CheckBoundsParameters::flags(), v8::internal::compiler::NodeProperties::GetValueInput(), graph(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Is(), v8::internal::compiler::MachineOperatorBuilder::Is64(), v8::internal::compiler::Type::IsNone(), jsgraph_, v8::internal::compiler::kAbortOnOutOfBounds, v8::internal::compiler::kAllow64BitBounds, v8::internal::compiler::kConvertStringAndMinusZero, v8::internal::compiler::kDistinguishZeros, v8::internal::compiler::kIdentifyZeros, v8::internal::compiler::TypeCache::kPositiveSafeInteger, v8::internal::kWord32, v8::internal::kWord64, v8::internal::compiler::SimplifiedLowering::machine(), v8::internal::compiler::MachineGraph::machine(), v8::internal::compiler::Type::Max(), v8::internal::compiler::Type::Min(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::Node::op(), v8::internal::MachineType::PointerRepresentation(), v8::internal::compiler::Node::ReplaceInput(), simplified(), v8::internal::compiler::UseInfo::TruncatingWord32(), type_cache_, TypeOf(), v8::internal::v8_flags, v8::base::Flags< EnumT, BitfieldT, BitfieldStorageT >::without(), v8::internal::compiler::UseInfo::Word(), and v8::internal::compiler::UseInfo::Word64().
VisitFastApiCall()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitFastApiCall (Node * node, SimplifiedLowering * lowering) [inline]
Definition at line 2156 of file simplified-lowering.cc.
                                                                  {
    FastApiCallParameters const& op_params =
        FastApiCallParametersOf(node->op());
    // We only consider the first function signature here. In case of function
    // overloads, we only support the case of two functions that differ for one
    // argument, which must be a JSArray in one function and a TypedArray in the
    // other function, and both JSArrays and TypedArrays have the same UseInfo
    // UseInfo::AnyTagged(). All the other argument types must match.
    const CFunctionInfo* c_signature = op_params.c_function().signature;
    const int c_arg_count = c_signature->ArgumentCount();
    CallDescriptor* call_descriptor = op_params.descriptor();
    // Arguments for CallApiCallbackOptimizedXXX builtin (including context)
    // plus JS arguments (including receiver).
    int slow_arg_count = static_cast<int>(call_descriptor->ParameterCount());
    const int value_input_count = node->op()->ValueInputCount();
    CHECK_EQ(FastApiCallNode::ArityForArgc(c_arg_count, slow_arg_count),
             value_input_count);
    FastApiCallNode n(node);
    base::SmallVector<UseInfo, kInitialArgumentsCount> arg_use_info(
        c_arg_count);
    // Propagate representation information from TypeInfo.
    int cursor = 0;
    for (int i = 0; i < c_arg_count; i++) {
      arg_use_info[i] = UseInfoForFastApiCallArgument(
          c_signature->ArgumentInfo(i), c_signature->GetInt64Representation(),
          op_params.feedback());
      ProcessInput<T>(node, cursor++, arg_use_info[i]);
    }
    // Callback data for fast call.
    DCHECK_EQ(n.CallbackDataIndex(), cursor);
    ProcessInput<T>(node, cursor++, UseInfo::AnyTagged());
    // The call code for the slow call.
    ProcessInput<T>(node, cursor++, UseInfo::AnyTagged());
    // For the slow builtin parameters (indexes [1, ..., params]), propagate
    // representation information from call descriptor.
    for (int i = 1; i <= slow_arg_count; i++) {
      ProcessInput<T>(node, cursor++,
                      TruncatingUseInfoFromRepresentation(
                          call_descriptor->GetInputType(i).representation()));
    }
    // Visit frame state input as tagged.
    DCHECK_EQ(n.FrameStateIndex(), cursor);
    ProcessInput<T>(node, cursor++, UseInfo::AnyTagged());
    DCHECK_EQ(cursor, value_input_count);
    // Effect and Control.
    ProcessRemainingInputs<T>(node, value_input_count);
    CTypeInfo return_type = op_params.c_function().signature->ReturnInfo();
    switch (return_type.GetType()) {
      case CTypeInfo::Type::kBool:
        SetOutput<T>(node, MachineRepresentation::kBit);
        return;
      case CTypeInfo::Type::kFloat32:
        SetOutput<T>(node, MachineRepresentation::kFloat32);
        return;
      case CTypeInfo::Type::kFloat64:
        SetOutput<T>(node, MachineRepresentation::kFloat64);
        return;
      case CTypeInfo::Type::kInt32:
        SetOutput<T>(node, MachineRepresentation::kWord32);
        return;
      case CTypeInfo::Type::kInt64:
      case CTypeInfo::Type::kUint64:
        if (c_signature->GetInt64Representation() ==
            CFunctionInfo::Int64Representation::kBigInt) {
          SetOutput<T>(node, MachineRepresentation::kWord64);
          return;
        }
        DCHECK_EQ(c_signature->GetInt64Representation(),
                  CFunctionInfo::Int64Representation::kNumber);
        SetOutput<T>(node, MachineRepresentation::kFloat64);
        return;
      case CTypeInfo::Type::kSeqOneByteString:
        SetOutput<T>(node, MachineRepresentation::kTagged);
        return;
      case CTypeInfo::Type::kUint32:
        SetOutput<T>(node, MachineRepresentation::kWord32);
        return;
      case CTypeInfo::Type::kUint8:
        SetOutput<T>(node, MachineRepresentation::kWord8);
        return;
      case CTypeInfo::Type::kAny:
        // This type is only supposed to be used for parameters, not returns.
        UNREACHABLE();
      case CTypeInfo::Type::kPointer:
      case CTypeInfo::Type::kApiObject:
      case CTypeInfo::Type::kV8Value:
      case CTypeInfo::Type::kVoid:
        SetOutput<T>(node, MachineRepresentation::kTagged);
        return;
    }
  }
References v8::internal::compiler::UseInfo::AnyTagged(), v8::CFunctionInfo::ArgumentCount(), v8::CFunctionInfo::ArgumentInfo(), v8::internal::compiler::FastApiCallNode::ArityForArgc(), v8::internal::compiler::FastApiCallParameters::c_function(), v8::internal::compiler::FastApiCallNode::CallbackDataIndex(), CHECK_EQ, DCHECK_EQ, v8::internal::compiler::FastApiCallParameters::descriptor(), v8::internal::compiler::FastApiCallParametersOf(), v8::internal::compiler::FastApiCallParameters::feedback(), v8::internal::compiler::FastApiCallNode::FrameStateIndex(), v8::internal::compiler::CallDescriptor::GetInputType(), v8::CFunctionInfo::GetInt64Representation(), v8::CTypeInfo::GetType(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::CTypeInfo::kAny, v8::CTypeInfo::kApiObject, v8::CFunctionInfo::kBigInt, v8::internal::kBit, v8::CTypeInfo::kBool, v8::CTypeInfo::kFloat32, v8::internal::kFloat32, v8::CTypeInfo::kFloat64, v8::internal::kFloat64, v8::CTypeInfo::kInt32, v8::CTypeInfo::kInt64, v8::CFunctionInfo::kNumber, v8::CTypeInfo::kPointer, v8::CTypeInfo::kSeqOneByteString, v8::internal::kTagged, v8::CTypeInfo::kUint32, v8::CTypeInfo::kUint64, v8::CTypeInfo::kUint8, v8::CTypeInfo::kV8Value, v8::CTypeInfo::kVoid, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::compiler::Node::op(), v8::internal::compiler::CallDescriptor::ParameterCount(), v8::internal::MachineType::representation(), v8::CFunctionInfo::ReturnInfo(), v8::internal::compiler::FastApiCallFunction::signature, v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::TruncatingUseInfoFromRepresentation(), v8::internal::UNREACHABLE(), UseInfoForFastApiCallArgument(), and v8::internal::compiler::Operator::ValueInputCount().
VisitFloat64Binop()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitFloat64Binop (Node * node) [inline]
Definition at line 1197 of file simplified-lowering.cc.
                                     {
    VisitBinop<T>(node, UseInfo::TruncatingFloat64(),
                  MachineRepresentation::kFloat64);
  }
References v8::internal::kFloat64, and v8::internal::compiler::UseInfo::TruncatingFloat64().
VisitForCheckedInt32Mul()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitForCheckedInt32Mul (Node * node, Truncation truncation, Type input0_type, Type input1_type, UseInfo input_use) [inline]
Definition at line 1667 of file simplified-lowering.cc.
                                                  {
    DCHECK_EQ(node->opcode(), IrOpcode::kSpeculativeNumberMultiply);
    // A -0 input is impossible or will cause a deopt.
    DCHECK(BothInputsAre(node, Type::Signed32()) ||
           !input_use.truncation().IdentifiesZeroAndMinusZero());
    CheckForMinusZeroMode mz_mode;
    Type restriction;
    if (IsSomePositiveOrderedNumber(input0_type) ||
        IsSomePositiveOrderedNumber(input1_type)) {
      mz_mode = CheckForMinusZeroMode::kDontCheckForMinusZero;
      restriction = Type::Signed32();
    } else if (truncation.IdentifiesZeroAndMinusZero()) {
      mz_mode = CheckForMinusZeroMode::kDontCheckForMinusZero;
      restriction = Type::Signed32OrMinusZero();
    } else {
      mz_mode = CheckForMinusZeroMode::kCheckForMinusZero;
      restriction = Type::Signed32();
    }
    VisitBinop<T>(node, input_use, MachineRepresentation::kWord32, restriction);
    if (lower<T>()) ChangeOp(node, simplified()->CheckedInt32Mul(mz_mode));
  }
References BothInputsAre(), ChangeOp(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::Truncation::IdentifiesZeroAndMinusZero(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::IsSomePositiveOrderedNumber(), v8::internal::compiler::kCheckForMinusZero, v8::internal::compiler::kDontCheckForMinusZero, v8::internal::kWord32, v8::internal::compiler::Node::opcode(), simplified(), and v8::internal::compiler::UseInfo::truncation().
VisitFrameState()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitFrameState (FrameState node) [inline]
Definition at line 1463 of file simplified-lowering.cc.
                                        {
    DCHECK_EQ(5, node->op()->ValueInputCount());
    DCHECK_EQ(1, OperatorProperties::GetFrameStateInputCount(node->op()));
    DCHECK_EQ(FrameState::kFrameStateInputCount, node->InputCount());
    ProcessInput<T>(node, FrameState::kFrameStateParametersInput,
                    UseInfo::AnyTagged());
    ProcessInput<T>(node, FrameState::kFrameStateLocalsInput,
                    UseInfo::AnyTagged());
    // Accumulator is a special flower - we need to remember its type in
    // a singleton typed-state-values node (as if it was a singleton
    // state-values node).
    Node* accumulator = node.stack();
    if (propagate<T>()) {
      if (IsLargeBigInt(TypeOf(accumulator))) {
        EnqueueInput<T>(node, FrameState::kFrameStateStackInput,
                        UseInfo::AnyTagged());
      } else if (IsLoadFloat16ArrayElement(accumulator)) {
        EnqueueInput<T>(node, FrameState::kFrameStateStackInput,
                        UseInfo::Float64());
      } else {
        EnqueueInput<T>(node, FrameState::kFrameStateStackInput,
                        UseInfo::Any());
      }
    } else if (lower<T>()) {
      MachineRepresentation accumulator_rep =
          GetInfo(accumulator)->representation();
      Type accumulator_type = TypeOf(accumulator);
      if (IsLargeBigInt(accumulator_type)) {
        ConvertInput(node, FrameState::kFrameStateStackInput,
                     UseInfo::AnyTagged());
        accumulator = node.stack();
      } else if (IsLoadFloat16ArrayElement(accumulator)) {
        ConvertInput(node, FrameState::kFrameStateStackInput,
                     UseInfo::Float64());
        accumulator = node.stack();
        accumulator_rep = MachineRepresentation::kFloat64;
      }
      Zone* zone = jsgraph_->zone();
      if (accumulator == jsgraph_->OptimizedOutConstant()) {
        node->ReplaceInput(FrameState::kFrameStateStackInput,
                           jsgraph_->SingleDeadTypedStateValues());
      } else {
        ZoneVector<MachineType>* types =
            zone->New<ZoneVector<MachineType>>(1, zone);
        (*types)[0] = DeoptMachineTypeOf(accumulator_rep, accumulator_type);
        node->ReplaceInput(
            FrameState::kFrameStateStackInput,
            jsgraph_->graph()->NewNode(
                common()->TypedStateValues(types, SparseInputMask::Dense()),
                node.stack()));
      }
    }
    ProcessInput<T>(node, FrameState::kFrameStateContextInput,
                    UseInfo::AnyTagged());
    ProcessInput<T>(node, FrameState::kFrameStateFunctionInput,
                    UseInfo::AnyTagged());
    ProcessInput<T>(node, FrameState::kFrameStateOuterStateInput,
                    UseInfo::AnyTagged());
    return SetOutput<T>(node, MachineRepresentation::kTagged);
  }
References v8::internal::compiler::UseInfo::Any(), v8::internal::compiler::UseInfo::AnyTagged(), common(), ConvertInput(), DCHECK_EQ, v8::internal::compiler::SparseInputMask::Dense(), DeoptMachineTypeOf(), v8::internal::compiler::UseInfo::Float64(), v8::internal::compiler::OperatorProperties::GetFrameStateInputCount(), GetInfo(), v8::internal::compiler::MachineGraph::graph(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::IsLargeBigInt(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::IsLoadFloat16ArrayElement(), jsgraph_, v8::internal::kFloat64, v8::internal::compiler::FrameState::kFrameStateContextInput, v8::internal::compiler::FrameState::kFrameStateFunctionInput, v8::internal::compiler::FrameState::kFrameStateInputCount, v8::internal::compiler::FrameState::kFrameStateLocalsInput, v8::internal::compiler::FrameState::kFrameStateOuterStateInput, v8::internal::compiler::FrameState::kFrameStateParametersInput, v8::internal::compiler::FrameState::kFrameStateStackInput, v8::internal::kTagged, v8::internal::Zone::New(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::RepresentationSelector::NodeInfo::representation(), v8::internal::compiler::FrameState::stack(), TypeOf(), zone(), and v8::internal::compiler::MachineGraph::zone().
VisitInputs() [1/3]
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitInputs (Node * node) [inline]
Definition at line 1093 of file simplified-lowering.cc.
                               {
    static_assert(
        retype<T>(),
        "This version of VisitInputs has to be called in the Retype phase.");
  }
VisitInputs() [2/3]
template<>
void v8::internal::compiler::RepresentationSelector::VisitInputs (Node * node)
Definition at line 5223 of file simplified-lowering.cc.
                                                              {
  int first_effect_index = NodeProperties::FirstEffectIndex(node);
  // Visit value, context and frame state inputs as tagged.
  for (int i = 0; i < first_effect_index; i++) {
    ProcessInput<PROPAGATE>(node, i, UseInfo::AnyTagged());
  }
  // Only enqueue other inputs (effects, control).
  for (int i = first_effect_index; i < node->InputCount(); i++) {
    EnqueueInput<PROPAGATE>(node, i);
  }
}
References v8::internal::compiler::UseInfo::AnyTagged(), v8::internal::compiler::NodeProperties::FirstEffectIndex(), and v8::internal::compiler::Node::InputCount().
VisitInputs() [3/3]
template<>
void v8::internal::compiler::RepresentationSelector::VisitInputs (Node * node)
Definition at line 5236 of file simplified-lowering.cc.
                                                          {
  int first_effect_index = NodeProperties::FirstEffectIndex(node);
  // Visit value, context and frame state inputs as tagged.
  for (int i = 0; i < first_effect_index; i++) {
    ProcessInput<LOWER>(node, i, UseInfo::AnyTagged());
  }
}
References v8::internal::compiler::UseInfo::AnyTagged(), and v8::internal::compiler::NodeProperties::FirstEffectIndex().
VisitInt64Binop()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitInt64Binop (Node * node) [inline]
Definition at line 1203 of file simplified-lowering.cc.
                                   {
    VisitBinop<T>(node, UseInfo::Word64(), MachineRepresentation::kWord64);
  }
References v8::internal::kWord64, and v8::internal::compiler::UseInfo::Word64().
VisitLeaf()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitLeaf (Node * node, MachineRepresentation output) [inline]
Definition at line 1189 of file simplified-lowering.cc.
                                                           {
    DCHECK_EQ(0, node->InputCount());
    SetOutput<T>(node, output);
  }
References DCHECK_EQ, and v8::internal::compiler::Node::InputCount().
VisitNode()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitNode (Node * node, Truncation truncation, SimplifiedLowering * lowering) [inline]
Definition at line 2460 of file simplified-lowering.cc.
                                               {
    tick_counter_->TickAndMaybeEnterSafepoint();
    if (lower<T>()) {
      // Kill non-effectful operations that have a None-type input and are thus
      // dead code. Otherwise we might end up lowering the operation in a way,
      // e.g. by replacing it with a constant, that cuts the dependency on a
      // deopting operation (the producer of the None type), possibly resulting
      // in a nonsense schedule.
      if (node->op()->EffectOutputCount() == 0 &&
          node->op()->ControlOutputCount() == 0 &&
          node->opcode() != IrOpcode::kDeadValue &&
          node->opcode() != IrOpcode::kStateValues &&
          node->opcode() != IrOpcode::kFrameState &&
          node->opcode() != IrOpcode::kPhi) {
        for (int i = 0; i < node->op()->ValueInputCount(); i++) {
          Node* input = node->InputAt(i);
          if (TypeOf(input).IsNone()) {
            node->ReplaceInput(0, input);
            node->TrimInputCount(1);
            ChangeOp(node,
                     common()->DeadValue(GetInfo(node)->representation()));
            return;
          }
        }
      } else {
        bool is_dead = false;
        if (node->op()->ValueOutputCount() > 0 &&
            node->op()->ControlOutputCount() == 0 &&
            node->opcode() != IrOpcode::kPhi &&
            node->opcode() != IrOpcode::kStateValues &&
            node->opcode() != IrOpcode::kFrameState) {
          for (int i = 0; i < node->op()->ValueInputCount(); i++) {
            Node* input = node->InputAt(i);
            // If one of the node's inputs produces a None-type, then this node
            // cannot produce a value itself.
            if (TypeOf(input).IsNone()) {
              GetInfo(node)->set_feedback_type(Type::None());
              is_dead = true;
              break;
            }
          }
        }
        InsertUnreachableIfNecessary<T>(node);
        // If the node is dead, we don't wont to lower it to avoid breaking
        // effect chains.
        if (is_dead) return;
      }
    }
    // Unconditionally eliminate unused pure nodes (only relevant if there's
    // a pure operation in between two effectful ones, where the last one
    // is unused).
    // Note: We must not do this for constants, as they are cached and we
    // would thus kill the cached {node} during lowering (i.e. replace all
    // uses with Dead), but at that point some node lowering might have
    // already taken the constant {node} from the cache (while it was not
    // yet killed) and we would afterwards replace that use with Dead as well.
    if (node->op()->ValueInputCount() > 0 &&
        node->op()->HasProperty(Operator::kPure) && truncation.IsUnused()) {
      return VisitUnused<T>(node);
    }
    switch (node->opcode()) {
      //------------------------------------------------------------------
      // Common operators.
      //------------------------------------------------------------------
      case IrOpcode::kStart:
        // We use Start as a terminator for the frame state chain, so even
        // tho Start doesn't really produce a value, we have to say Tagged
        // here, otherwise the input conversion will fail.
        return VisitLeaf<T>(node, MachineRepresentation::kTagged);
      case IrOpcode::kParameter:
        return VisitUnop<T>(node, UseInfo::None(),
                            linkage()
                                ->GetParameterType(ParameterIndexOf(node->op()))
                                .representation());
      case IrOpcode::kInt32Constant:
        DCHECK_EQ(0, node->InputCount());
        SetOutput<T>(node, MachineRepresentation::kWord32);
        DCHECK(NodeProperties::GetType(node).Is(Type::Machine()));
        if (V8_UNLIKELY(verification_enabled())) {
          // During lowering, SimplifiedLowering generates Int32Constants which
          // need to be treated differently by the verifier than the
          // Int32Constants introduced explicitly in machine graphs. To be able
          // to distinguish them, we record those that are being visited here
          // because they were generated before SimplifiedLowering.
          if (propagate<T>()) {
            verifier_->RecordMachineUsesOfConstant(node, node->uses());
          }
        }
        return;
      case IrOpcode::kInt64Constant:
        return VisitLeaf<T>(node, MachineRepresentation::kWord64);
      case IrOpcode::kExternalConstant:
        return VisitLeaf<T>(node, MachineType::PointerRepresentation());
      case IrOpcode::kNumberConstant: {
        double const value = OpParameter<double>(node->op());
        int value_as_int;
        if (DoubleToSmiInteger(value, &value_as_int)) {
          VisitLeaf<T>(node, MachineRepresentation::kTaggedSigned);
          if (lower<T>()) {
            intptr_t smi = base::bit_cast<intptr_t>(Smi::FromInt(value_as_int));
            Node* constant = InsertTypeOverrideForVerifier(
                NodeProperties::GetType(node),
                lowering->jsgraph()->IntPtrConstant(smi));
            DeferReplacement(node, constant);
          }
          return;
        }
        VisitLeaf<T>(node, MachineRepresentation::kTagged);
        return;
      }
      case IrOpcode::kHeapConstant:
        return VisitLeaf<T>(node, MachineRepresentation::kTaggedPointer);
      case IrOpcode::kTrustedHeapConstant:
        return VisitLeaf<T>(node, MachineRepresentation::kTaggedPointer);
      case IrOpcode::kPointerConstant: {
        VisitLeaf<T>(node, MachineType::PointerRepresentation());
        if (lower<T>()) {
          intptr_t const value = OpParameter<intptr_t>(node->op());
          DeferReplacement(node, lowering->jsgraph()->IntPtrConstant(value));
        }
        return;
      }
      case IrOpcode::kBranch: {
        const auto& p = BranchParametersOf(node->op());
        if (p.semantics() == BranchSemantics::kMachine) {
          // If this is a machine branch, the condition is a machine operator,
          // so we enter machine branch here.
          ProcessInput<T>(node, 0, UseInfo::Any());
        } else {
          DCHECK(TypeOf(node->InputAt(0)).Is(Type::Boolean()));
          ProcessInput<T>(node, 0, UseInfo::Bool());
          if (lower<T>()) {
            ChangeOp(node,
                     common()->Branch(p.hint(), BranchSemantics::kMachine));
          }
        }
        EnqueueInput<T>(node, NodeProperties::FirstControlIndex(node));
        return;
      }
      case IrOpcode::kSwitch:
        ProcessInput<T>(node, 0, UseInfo::TruncatingWord32());
        EnqueueInput<T>(node, NodeProperties::FirstControlIndex(node));
        return;
      case IrOpcode::kSelect: {
        const auto& p = SelectParametersOf(node->op());
        if (p.semantics() == BranchSemantics::kMachine) {
          // If this is a machine select, all inputs are machine operators.
          ProcessInput<T>(node, 0, UseInfo::Any());
          ProcessInput<T>(node, 1, UseInfo::Any());
          ProcessInput<T>(node, 2, UseInfo::Any());
          SetOutput<T>(node, p.representation());
        } else {
          VisitSelect<T>(node, truncation, lowering);
        }
        return;
      }
      case IrOpcode::kPhi:
        return VisitPhi<T>(node, truncation, lowering);
      case IrOpcode::kCall:
        return VisitCall<T>(node, lowering);
      case IrOpcode::kAssert: {
        const auto& p = AssertParametersOf(node->op());
        if (p.semantics() == BranchSemantics::kMachine) {
          // If this is a machine condition already, we don't need to do
          // anything.
          ProcessInput<T>(node, 0, UseInfo::Any());
        } else {
          DCHECK(TypeOf(node->InputAt(0)).Is(Type::Boolean()));
          ProcessInput<T>(node, 0, UseInfo::Bool());
          if (lower<T>()) {
            ChangeOp(node, common()->Assert(BranchSemantics::kMachine,
                                            p.condition_string(), p.file(),
                                            p.line()));
          }
        }
        EnqueueInput<T>(node, NodeProperties::FirstControlIndex(node));
        return;
      }
      //------------------------------------------------------------------
      // JavaScript operators.
      //------------------------------------------------------------------
      case IrOpcode::kJSToNumber:
      case IrOpcode::kJSToNumberConvertBigInt:
      case IrOpcode::kJSToNumeric: {
        DCHECK(NodeProperties::GetType(node).Is(Type::Union(
            Type::BigInt(), Type::NumberOrOddball(), graph()->zone())));
        VisitInputs<T>(node);
        // TODO(bmeurer): Optimize somewhat based on input type?
        if (truncation.IsUsedAsWord32()) {
          SetOutput<T>(node, MachineRepresentation::kWord32);
          if (lower<T>())
            lowering->DoJSToNumberOrNumericTruncatesToWord32(node, this);
        } else if (truncation.TruncatesOddballAndBigIntToNumber()) {
          SetOutput<T>(node, MachineRepresentation::kFloat64);
          if (lower<T>())
            lowering->DoJSToNumberOrNumericTruncatesToFloat64(node, this);
        } else {
          SetOutput<T>(node, MachineRepresentation::kTagged);
        }
        return;
      }
      case IrOpcode::kJSToBigInt:
      case IrOpcode::kJSToBigIntConvertNumber: {
        VisitInputs<T>(node);
        SetOutput<T>(node, MachineRepresentation::kTaggedPointer);
        return;
      }
      //------------------------------------------------------------------
      // Simplified operators.
      //------------------------------------------------------------------
      case IrOpcode::kToBoolean: {
        if (truncation.IsUsedAsBool()) {
          ProcessInput<T>(node, 0, UseInfo::Bool());
          SetOutput<T>(node, MachineRepresentation::kBit);
          if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        } else {
          VisitInputs<T>(node);
          SetOutput<T>(node, MachineRepresentation::kTaggedPointer);
        }
        return;
      }
      case IrOpcode::kBooleanNot: {
        if (lower<T>()) {
          NodeInfo* input_info = GetInfo(node->InputAt(0));
          if (input_info->representation() == MachineRepresentation::kBit) {
            // BooleanNot(x: kRepBit) => Word32Equal(x, #0)
            node->AppendInput(jsgraph_->zone(), jsgraph_->Int32Constant(0));
            ChangeOp(node, lowering->machine()->Word32Equal());
          } else if (CanBeTaggedPointer(input_info->representation())) {
            // BooleanNot(x: kRepTagged) => TaggedEqual(x, #false)
            node->AppendInput(jsgraph_->zone(), jsgraph_->FalseConstant());
            ChangeOp(node, lowering->machine()->TaggedEqual());
          } else {
            DCHECK(TypeOf(node->InputAt(0)).IsNone());
            DeferReplacement(node, lowering->jsgraph()->Int32Constant(0));
          }
        } else {
          // No input representation requirement; adapt during lowering.
          ProcessInput<T>(node, 0, UseInfo::AnyTruncatingToBool());
          SetOutput<T>(node, MachineRepresentation::kBit);
        }
        return;
      }
      case IrOpcode::kNumberEqual: {
        Type const lhs_type = TypeOf(node->InputAt(0));
        Type const rhs_type = TypeOf(node->InputAt(1));
        // Regular number comparisons in JavaScript generally identify zeros,
        // so we always pass kIdentifyZeros for the inputs, and in addition
        // we can truncate -0 to 0 for otherwise Unsigned32 or Signed32 inputs.
        // For equality we also handle the case that one side is non-zero, in
        // which case we allow to truncate NaN to 0 on the other side.
        if ((lhs_type.Is(Type::Unsigned32OrMinusZero()) &&
             rhs_type.Is(Type::Unsigned32OrMinusZero())) ||
            (lhs_type.Is(Type::Unsigned32OrMinusZeroOrNaN()) &&
             rhs_type.Is(Type::Unsigned32OrMinusZeroOrNaN()) &&
             OneInputCannotBe(node, type_cache_->kZeroish))) {
          // => unsigned Int32Cmp
          VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                        MachineRepresentation::kBit);
          if (lower<T>()) ChangeOp(node, Uint32Op(node));
          return;
        }
        if ((lhs_type.Is(Type::Signed32OrMinusZero()) &&
             rhs_type.Is(Type::Signed32OrMinusZero())) ||
            (lhs_type.Is(Type::Signed32OrMinusZeroOrNaN()) &&
             rhs_type.Is(Type::Signed32OrMinusZeroOrNaN()) &&
             OneInputCannotBe(node, type_cache_->kZeroish))) {
          // => signed Int32Cmp
          VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                        MachineRepresentation::kBit);
          if (lower<T>()) ChangeOp(node, Int32Op(node));
          return;
        }
        if (lhs_type.Is(Type::Boolean()) && rhs_type.Is(Type::Boolean())) {
          VisitBinop<T>(node, UseInfo::Bool(), MachineRepresentation::kBit);
          if (lower<T>()) ChangeOp(node, lowering->machine()->Word32Equal());
          return;
        }
        // => Float64Cmp
        VisitBinop<T>(node, UseInfo::TruncatingFloat64(kIdentifyZeros),
                      MachineRepresentation::kBit);
        if (lower<T>()) ChangeOp(node, Float64Op(node));
        return;
      }
      case IrOpcode::kNumberLessThan:
      case IrOpcode::kNumberLessThanOrEqual: {
        Type const lhs_type = TypeOf(node->InputAt(0));
        Type const rhs_type = TypeOf(node->InputAt(1));
        // Regular number comparisons in JavaScript generally identify zeros,
        // so we always pass kIdentifyZeros for the inputs, and in addition
        // we can truncate -0 to 0 for otherwise Unsigned32 or Signed32 inputs.
        if (lhs_type.Is(Type::Unsigned32OrMinusZero()) &&
            rhs_type.Is(Type::Unsigned32OrMinusZero())) {
          // => unsigned Int32Cmp
          VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                        MachineRepresentation::kBit);
          if (lower<T>()) ChangeOp(node, Uint32Op(node));
        } else if (lhs_type.Is(Type::Signed32OrMinusZero()) &&
                   rhs_type.Is(Type::Signed32OrMinusZero())) {
          // => signed Int32Cmp
          VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                        MachineRepresentation::kBit);
          if (lower<T>()) ChangeOp(node, Int32Op(node));
        } else {
          // => Float64Cmp
          VisitBinop<T>(node, UseInfo::TruncatingFloat64(kIdentifyZeros),
                        MachineRepresentation::kBit);
          if (lower<T>()) ChangeOp(node, Float64Op(node));
        }
        return;
      }
      case IrOpcode::kSpeculativeSmallIntegerAdd:
      case IrOpcode::kSpeculativeSmallIntegerSubtract:
        return VisitSpeculativeSmallIntegerAdditiveOp<T>(node, truncation,
                                                         lowering);
      case IrOpcode::kSpeculativeAdditiveSafeIntegerAdd:
      case IrOpcode::kSpeculativeAdditiveSafeIntegerSubtract:
      case IrOpcode::kSpeculativeNumberAdd:
      case IrOpcode::kSpeculativeNumberSubtract:
        return VisitSpeculativeAdditiveOp<T>(node, truncation, lowering);
      case IrOpcode::kSpeculativeNumberLessThan:
      case IrOpcode::kSpeculativeNumberLessThanOrEqual:
      case IrOpcode::kSpeculativeNumberEqual: {
        Type const lhs_type = TypeOf(node->InputAt(0));
        Type const rhs_type = TypeOf(node->InputAt(1));
        // Regular number comparisons in JavaScript generally identify zeros,
        // so we always pass kIdentifyZeros for the inputs, and in addition
        // we can truncate -0 to 0 for otherwise Unsigned32 or Signed32 inputs.
        if (lhs_type.Is(Type::Unsigned32OrMinusZero()) &&
            rhs_type.Is(Type::Unsigned32OrMinusZero())) {
          // => unsigned Int32Cmp
          VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                        MachineRepresentation::kBit);
          if (lower<T>()) ChangeToPureOp(node, Uint32Op(node));
          return;
        } else if (lhs_type.Is(Type::Signed32OrMinusZero()) &&
                   rhs_type.Is(Type::Signed32OrMinusZero())) {
          // => signed Int32Cmp
          VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                        MachineRepresentation::kBit);
          if (lower<T>()) ChangeToPureOp(node, Int32Op(node));
          return;
        } else if (lhs_type.Is(Type::Boolean()) &&
                   rhs_type.Is(Type::Boolean())) {
          VisitBinop<T>(node, UseInfo::Bool(), MachineRepresentation::kBit);
          if (lower<T>()) ChangeToPureOp(node, Int32Op(node));
          return;
        }
        // Try to use type feedback.
        NumberOperationHint hint = NumberOperationHintOf(node->op());
        switch (hint) {
          case NumberOperationHint::kSignedSmall:
            if (propagate<T>()) {
              VisitBinop<T>(
                  node, CheckedUseInfoAsWord32FromHint(hint, kIdentifyZeros),
                  MachineRepresentation::kBit);
            } else if (retype<T>()) {
              SetOutput<T>(node, MachineRepresentation::kBit, Type::Any());
            } else {
              DCHECK(lower<T>());
              Node* lhs = node->InputAt(0);
              Node* rhs = node->InputAt(1);
              if (IsNodeRepresentationTagged(lhs) &&
                  IsNodeRepresentationTagged(rhs)) {
                VisitBinop<T>(node,
                              UseInfo::CheckedSignedSmallAsTaggedSigned(
                                  FeedbackSource(), kIdentifyZeros),
                              MachineRepresentation::kBit);
                ChangeToPureOp(
                    node, changer_->TaggedSignedOperatorFor(node->opcode()));
              } else {
                VisitBinop<T>(
                    node, CheckedUseInfoAsWord32FromHint(hint, kIdentifyZeros),
                    MachineRepresentation::kBit);
                ChangeToPureOp(node, Int32Op(node));
              }
            }
            return;
          case NumberOperationHint::kSignedSmallInputs:
          case NumberOperationHint::kAdditiveSafeInteger:
            // This doesn't make sense for compare operations.
            UNREACHABLE();
          case NumberOperationHint::kNumberOrOddball:
            // Abstract and strict equality don't perform ToNumber conversions
            // on Oddballs, so make sure we don't accidentially sneak in a
            // hint with Oddball feedback here.
            DCHECK_NE(IrOpcode::kSpeculativeNumberEqual, node->opcode());
            [[fallthrough]];
          case NumberOperationHint::kNumberOrBoolean:
          case NumberOperationHint::kNumber:
            VisitBinop<T>(node,
                          CheckedUseInfoAsFloat64FromHint(
                              hint, FeedbackSource(), kIdentifyZeros),
                          MachineRepresentation::kBit);
            if (lower<T>()) ChangeToPureOp(node, Float64Op(node));
            return;
        }
        UNREACHABLE();
        return;
      }
      case IrOpcode::kNumberAdd:
      case IrOpcode::kNumberSubtract: {
        if (TypeOf(node->InputAt(0))
                .Is(type_cache_->kAdditiveSafeIntegerOrMinusZero) &&
            TypeOf(node->InputAt(1))
                .Is(type_cache_->kAdditiveSafeIntegerOrMinusZero) &&
            (TypeOf(node).Is(Type::Signed32()) ||
             TypeOf(node).Is(Type::Unsigned32()) ||
             truncation.IsUsedAsWord32())) {
          // => Int32Add/Sub
          VisitWord32TruncatingBinop<T>(node);
          if (lower<T>()) ChangeToPureOp(node, Int32Op(node));
        } else if (jsgraph_->machine()->Is64() &&
                   BothInputsAre(node, type_cache_->kSafeInteger) &&
                   GetUpperBound(node).Is(type_cache_->kSafeInteger)) {
          // => Int64Add/Sub
          VisitInt64Binop<T>(node);
          if (lower<T>()) ChangeToPureOp(node, Int64Op(node));
        } else {
          // => Float64Add/Sub
          VisitFloat64Binop<T>(node);
          if (lower<T>()) ChangeToPureOp(node, Float64Op(node));
        }
        return;
      }
      case IrOpcode::kSpeculativeNumberMultiply: {
        if (BothInputsAre(node, Type::Integral32()) &&
            (NodeProperties::GetType(node).Is(Type::Signed32()) ||
             NodeProperties::GetType(node).Is(Type::Unsigned32()) ||
             (truncation.IsUsedAsWord32() &&
              NodeProperties::GetType(node).Is(
                  type_cache_->kSafeIntegerOrMinusZero)))) {
          // Multiply reduces to Int32Mul if the inputs are integers, and
          // (a) the output is either known to be Signed32, or
          // (b) the output is known to be Unsigned32, or
          // (c) the uses are truncating and the result is in the safe
          // integer range.
          VisitWord32TruncatingBinop<T>(node);
          if (lower<T>()) ChangeToPureOp(node, Int32Op(node));
          return;
        }
        // Try to use type feedback.
        NumberOperationHint hint = NumberOperationHintOf(node->op());
        Type input0_type = TypeOf(node->InputAt(0));
        Type input1_type = TypeOf(node->InputAt(1));
        // Handle the case when no int32 checks on inputs are necessary
        // (but an overflow check is needed on the output).
        if (BothInputsAre(node, Type::Signed32())) {
          // If both inputs and feedback are int32, use the overflow op.
          if (hint == NumberOperationHint::kSignedSmall) {
            VisitForCheckedInt32Mul<T>(node, truncation, input0_type,
                                       input1_type,
                                       UseInfo::TruncatingWord32());
            return;
          }
        }
        if (hint == NumberOperationHint::kSignedSmall) {
          VisitForCheckedInt32Mul<T>(node, truncation, input0_type, input1_type,
                                     CheckedUseInfoAsWord32FromHint(hint));
          return;
        }
        // Checked float64 x float64 => float64
        VisitBinop<T>(node,
                      UseInfo::CheckedNumberOrOddballAsFloat64(
                          kDistinguishZeros, FeedbackSource()),
                      MachineRepresentation::kFloat64, Type::Number());
        if (lower<T>()) ChangeToPureOp(node, Float64Op(node));
        return;
      }
      case IrOpcode::kNumberMultiply: {
        if (TypeOf(node->InputAt(0)).Is(Type::Integral32()) &&
            TypeOf(node->InputAt(1)).Is(Type::Integral32()) &&
            (TypeOf(node).Is(Type::Signed32()) ||
             TypeOf(node).Is(Type::Unsigned32()) ||
             (truncation.IsUsedAsWord32() &&
              TypeOf(node).Is(type_cache_->kSafeIntegerOrMinusZero)))) {
          // Multiply reduces to Int32Mul if the inputs are integers, and
          // (a) the output is either known to be Signed32, or
          // (b) the output is known to be Unsigned32, or
          // (c) the uses are truncating and the result is in the safe
          // integer range.
          VisitWord32TruncatingBinop<T>(node);
          if (lower<T>()) ChangeToPureOp(node, Int32Op(node));
          return;
        }
        // Number x Number => Float64Mul
        VisitFloat64Binop<T>(node);
        if (lower<T>()) ChangeToPureOp(node, Float64Op(node));
        return;
      }
      case IrOpcode::kSpeculativeNumberDivide: {
        if (BothInputsAreUnsigned32(node) && truncation.IsUsedAsWord32()) {
          // => unsigned Uint32Div
          VisitWord32TruncatingBinop<T>(node);
          if (lower<T>()) DeferReplacement(node, lowering->Uint32Div(node));
          return;
        }
        if (BothInputsAreSigned32(node)) {
          if (NodeProperties::GetType(node).Is(Type::Signed32())) {
            // => signed Int32Div
            VisitWord32TruncatingBinop<T>(node);
            if (lower<T>()) DeferReplacement(node, lowering->Int32Div(node));
            return;
          }
          if (truncation.IsUsedAsWord32()) {
            // => signed Int32Div
            VisitWord32TruncatingBinop<T>(node);
            if (lower<T>()) DeferReplacement(node, lowering->Int32Div(node));
            return;
          }
        }
        // Try to use type feedback.
        NumberOperationHint hint = NumberOperationHintOf(node->op());
        // Handle the case when no uint32 checks on inputs are necessary
        // (but an overflow check is needed on the output).
        if (BothInputsAreUnsigned32(node)) {
          if (hint == NumberOperationHint::kSignedSmall) {
            VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                          MachineRepresentation::kWord32, Type::Unsigned32());
            if (lower<T>()) ChangeToUint32OverflowOp(node);
            return;
          }
        }
        // Handle the case when no int32 checks on inputs are necessary
        // (but an overflow check is needed on the output).
        if (BothInputsAreSigned32(node)) {
          // If both the inputs the feedback are int32, use the overflow op.
          if (hint == NumberOperationHint::kSignedSmall) {
            VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                          MachineRepresentation::kWord32, Type::Signed32());
            if (lower<T>()) ChangeToInt32OverflowOp(node);
            return;
          }
        }
        if (hint == NumberOperationHint::kSignedSmall ||
            hint == NumberOperationHint::kSignedSmallInputs) {
          // If the result is truncated, we only need to check the inputs.
          if (truncation.IsUsedAsWord32()) {
            VisitBinop<T>(node, CheckedUseInfoAsWord32FromHint(hint),
                          MachineRepresentation::kWord32);
            if (lower<T>()) DeferReplacement(node, lowering->Int32Div(node));
            return;
          } else if (hint != NumberOperationHint::kSignedSmallInputs) {
            VisitBinop<T>(node, CheckedUseInfoAsWord32FromHint(hint),
                          MachineRepresentation::kWord32, Type::Signed32());
            if (lower<T>()) ChangeToInt32OverflowOp(node);
            return;
          }
        }
        // default case => Float64Div
        VisitBinop<T>(node,
                      UseInfo::CheckedNumberOrOddballAsFloat64(
                          kDistinguishZeros, FeedbackSource()),
                      MachineRepresentation::kFloat64, Type::Number());
        if (lower<T>()) ChangeToPureOp(node, Float64Op(node));
        return;
      }
      case IrOpcode::kNumberDivide: {
        if (TypeOf(node->InputAt(0)).Is(Type::Unsigned32()) &&
            TypeOf(node->InputAt(1)).Is(Type::Unsigned32()) &&
            (truncation.IsUsedAsWord32() ||
             TypeOf(node).Is(Type::Unsigned32()))) {
          // => unsigned Uint32Div
          VisitWord32TruncatingBinop<T>(node);
          if (lower<T>()) DeferReplacement(node, lowering->Uint32Div(node));
          return;
        }
        if (TypeOf(node->InputAt(0)).Is(Type::Signed32()) &&
            TypeOf(node->InputAt(1)).Is(Type::Signed32()) &&
            (truncation.IsUsedAsWord32() ||
             TypeOf(node).Is(Type::Signed32()))) {
          // => signed Int32Div
          VisitWord32TruncatingBinop<T>(node);
          if (lower<T>()) DeferReplacement(node, lowering->Int32Div(node));
          return;
        }
        // Number x Number => Float64Div
        VisitFloat64Binop<T>(node);
        if (lower<T>()) ChangeToPureOp(node, Float64Op(node));
        return;
      }
      case IrOpcode::kUnsigned32Divide: {
        CHECK(TypeOf(node->InputAt(0)).Is(Type::Unsigned32()));
        CHECK(TypeOf(node->InputAt(1)).Is(Type::Unsigned32()));
        // => unsigned Uint32Div
        VisitWord32TruncatingBinop<T>(node);
        if (lower<T>()) DeferReplacement(node, lowering->Uint32Div(node));
        return;
      }
      case IrOpcode::kSpeculativeNumberModulus:
        return VisitSpeculativeNumberModulus<T>(node, truncation, lowering);
      case IrOpcode::kNumberModulus: {
        Type const lhs_type = TypeOf(node->InputAt(0));
        Type const rhs_type = TypeOf(node->InputAt(1));
        if ((lhs_type.Is(Type::Unsigned32OrMinusZeroOrNaN()) &&
             rhs_type.Is(Type::Unsigned32OrMinusZeroOrNaN())) &&
            (truncation.IsUsedAsWord32() ||
             TypeOf(node).Is(Type::Unsigned32()))) {
          // => unsigned Uint32Mod
          VisitWord32TruncatingBinop<T>(node);
          if (lower<T>()) DeferReplacement(node, lowering->Uint32Mod(node));
          return;
        }
        if ((lhs_type.Is(Type::Signed32OrMinusZeroOrNaN()) &&
             rhs_type.Is(Type::Signed32OrMinusZeroOrNaN())) &&
            (truncation.IsUsedAsWord32() || TypeOf(node).Is(Type::Signed32()) ||
             (truncation.IdentifiesZeroAndMinusZero() &&
              TypeOf(node).Is(Type::Signed32OrMinusZero())))) {
          // => signed Int32Mod
          VisitWord32TruncatingBinop<T>(node);
          if (lower<T>()) DeferReplacement(node, lowering->Int32Mod(node));
          return;
        }
        // => Float64Mod
        // For the left hand side we just propagate the identify zeros
        // mode of the {truncation}; and for modulus the sign of the
        // right hand side doesn't matter anyways, so in particular there's
        // no observable difference between a 0 and a -0 then.
        UseInfo const lhs_use =
            UseInfo::TruncatingFloat64(truncation.identify_zeros());
        UseInfo const rhs_use = UseInfo::TruncatingFloat64(kIdentifyZeros);
        VisitBinop<T>(node, lhs_use, rhs_use, MachineRepresentation::kFloat64);
        if (lower<T>()) ChangeToPureOp(node, Float64Op(node));
        return;
      }
      case IrOpcode::kNumberBitwiseOr:
      case IrOpcode::kNumberBitwiseXor:
      case IrOpcode::kNumberBitwiseAnd: {
        VisitWord32TruncatingBinop<T>(node);
        if (lower<T>()) ChangeOp(node, Int32Op(node));
        return;
      }
      case IrOpcode::kSpeculativeNumberBitwiseOr:
      case IrOpcode::kSpeculativeNumberBitwiseXor:
      case IrOpcode::kSpeculativeNumberBitwiseAnd:
        VisitSpeculativeInt32Binop<T>(node);
        if (lower<T>()) {
          ChangeToPureOp(node, Int32Op(node));
        }
        return;
      case IrOpcode::kNumberShiftLeft: {
        Type rhs_type = GetUpperBound(node->InputAt(1));
        VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                      UseInfo::TruncatingWord32(),
                      MachineRepresentation::kWord32);
        if (lower<T>()) {
          MaskShiftOperand(node, rhs_type);
          ChangeToPureOp(node, lowering->machine()->Word32Shl());
        }
        return;
      }
      case IrOpcode::kSpeculativeNumberShiftLeft: {
        if (BothInputsAre(node, Type::NumberOrOddball())) {
          Type rhs_type = GetUpperBound(node->InputAt(1));
          VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                        UseInfo::TruncatingWord32(),
                        MachineRepresentation::kWord32);
          if (lower<T>()) {
            MaskShiftOperand(node, rhs_type);
            ChangeToPureOp(node, lowering->machine()->Word32Shl());
          }
          return;
        }
        NumberOperationHint hint = NumberOperationHintOf(node->op());
        Type rhs_type = GetUpperBound(node->InputAt(1));
        VisitBinop<T>(node,
                      CheckedUseInfoAsWord32FromHint(hint, kIdentifyZeros),
                      MachineRepresentation::kWord32, Type::Signed32());
        if (lower<T>()) {
          MaskShiftOperand(node, rhs_type);
          ChangeToPureOp(node, lowering->machine()->Word32Shl());
        }
        return;
      }
      case IrOpcode::kNumberShiftRight: {
        Type rhs_type = GetUpperBound(node->InputAt(1));
        VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                      UseInfo::TruncatingWord32(),
                      MachineRepresentation::kWord32);
        if (lower<T>()) {
          MaskShiftOperand(node, rhs_type);
          ChangeToPureOp(node, lowering->machine()->Word32Sar());
        }
        return;
      }
      case IrOpcode::kSpeculativeNumberShiftRight: {
        if (BothInputsAre(node, Type::NumberOrOddball())) {
          Type rhs_type = GetUpperBound(node->InputAt(1));
          VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                        UseInfo::TruncatingWord32(),
                        MachineRepresentation::kWord32);
          if (lower<T>()) {
            MaskShiftOperand(node, rhs_type);
            ChangeToPureOp(node, lowering->machine()->Word32Sar());
          }
          return;
        }
        NumberOperationHint hint = NumberOperationHintOf(node->op());
        Type rhs_type = GetUpperBound(node->InputAt(1));
        VisitBinop<T>(node,
                      CheckedUseInfoAsWord32FromHint(hint, kIdentifyZeros),
                      MachineRepresentation::kWord32, Type::Signed32());
        if (lower<T>()) {
          MaskShiftOperand(node, rhs_type);
          ChangeToPureOp(node, lowering->machine()->Word32Sar());
        }
        return;
      }
      case IrOpcode::kNumberShiftRightLogical: {
        Type rhs_type = GetUpperBound(node->InputAt(1));
        VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                      UseInfo::TruncatingWord32(),
                      MachineRepresentation::kWord32);
        if (lower<T>()) {
          MaskShiftOperand(node, rhs_type);
          ChangeToPureOp(node, lowering->machine()->Word32Shr());
        }
        return;
      }
      case IrOpcode::kSpeculativeNumberShiftRightLogical: {
        NumberOperationHint hint = NumberOperationHintOf(node->op());
        Type rhs_type = GetUpperBound(node->InputAt(1));
        if (rhs_type.Is(type_cache_->kZeroish) &&
            hint == NumberOperationHint::kSignedSmall &&
            !truncation.IsUsedAsWord32()) {
          // The SignedSmall or Signed32 feedback means that the results that we
          // have seen so far were of type Unsigned31. We speculate that this
          // will continue to hold. Moreover, since the RHS is 0, the result
          // will just be the (converted) LHS.
          VisitBinop<T>(node,
                        CheckedUseInfoAsWord32FromHint(hint, kIdentifyZeros),
                        MachineRepresentation::kWord32, Type::Unsigned31());
          if (lower<T>()) {
            node->RemoveInput(1);
            ChangeOp(node,
                     simplified()->CheckedUint32ToInt32(FeedbackSource()));
          }
          return;
        }
        if (BothInputsAre(node, Type::NumberOrOddball())) {
          VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                        UseInfo::TruncatingWord32(),
                        MachineRepresentation::kWord32);
          if (lower<T>()) {
            MaskShiftOperand(node, rhs_type);
            ChangeToPureOp(node, lowering->machine()->Word32Shr());
          }
          return;
        }
        VisitBinop<T>(node,
                      CheckedUseInfoAsWord32FromHint(hint, kIdentifyZeros),
                      MachineRepresentation::kWord32, Type::Unsigned32());
        if (lower<T>()) {
          MaskShiftOperand(node, rhs_type);
          ChangeToPureOp(node, lowering->machine()->Word32Shr());
        }
        return;
      }
      case IrOpcode::kNumberAbs: {
        // NumberAbs maps both 0 and -0 to 0, so we can generally
        // pass the kIdentifyZeros truncation to its input, and
        // choose to ignore minus zero in all cases.
        Type const input_type = TypeOf(node->InputAt(0));
        if (input_type.Is(Type::Unsigned32OrMinusZero())) {
          VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                       MachineRepresentation::kWord32);
          if (lower<T>()) {
            DeferReplacement(
                node,
                InsertTypeOverrideForVerifier(
                    Type::Intersect(input_type, Type::Unsigned32(), zone()),
                    node->InputAt(0)));
          }
        } else if (input_type.Is(Type::Signed32OrMinusZero())) {
          VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                       MachineRepresentation::kWord32);
          if (lower<T>()) {
            DeferReplacement(
                node,
                InsertTypeOverrideForVerifier(
                    Type::Intersect(input_type, Type::Unsigned32(), zone()),
                    lowering->Int32Abs(node)));
          }
        } else if (input_type.Is(type_cache_->kPositiveIntegerOrNaN)) {
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(kIdentifyZeros),
                       MachineRepresentation::kFloat64);
          if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        } else {
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(kIdentifyZeros),
                       MachineRepresentation::kFloat64);
          if (lower<T>()) ChangeOp(node, Float64Op(node));
        }
        return;
      }
      case IrOpcode::kNumberClz32: {
        VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                     MachineRepresentation::kWord32);
        if (lower<T>()) ChangeOp(node, Uint32Op(node));
        return;
      }
      case IrOpcode::kNumberImul: {
        VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                      UseInfo::TruncatingWord32(),
                      MachineRepresentation::kWord32);
        if (lower<T>()) ChangeOp(node, Uint32Op(node));
        return;
      }
      case IrOpcode::kNumberFround: {
        VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                     MachineRepresentation::kFloat32);
        if (lower<T>()) ChangeOp(node, Float64Op(node));
        return;
      }
      case IrOpcode::kNumberMax: {
        // It is safe to use the feedback types for left and right hand side
        // here, since we can only narrow those types and thus we can only
        // promise a more specific truncation.
        // For NumberMax we generally propagate whether the truncation
        // identifies zeros to the inputs, and we choose to ignore minus
        // zero in those cases.
        Type const lhs_type = TypeOf(node->InputAt(0));
        Type const rhs_type = TypeOf(node->InputAt(1));
        if ((lhs_type.Is(Type::Unsigned32()) &&
             rhs_type.Is(Type::Unsigned32())) ||
            (lhs_type.Is(Type::Unsigned32OrMinusZero()) &&
             rhs_type.Is(Type::Unsigned32OrMinusZero()) &&
             truncation.IdentifiesZeroAndMinusZero())) {
          VisitWord32TruncatingBinop<T>(node);
          if (lower<T>()) {
            lowering->DoMax(node, lowering->machine()->Uint32LessThan(),
                            MachineRepresentation::kWord32);
          }
        } else if ((lhs_type.Is(Type::Signed32()) &&
                    rhs_type.Is(Type::Signed32())) ||
                   (lhs_type.Is(Type::Signed32OrMinusZero()) &&
                    rhs_type.Is(Type::Signed32OrMinusZero()) &&
                    truncation.IdentifiesZeroAndMinusZero())) {
          VisitWord32TruncatingBinop<T>(node);
          if (lower<T>()) {
            lowering->DoMax(node, lowering->machine()->Int32LessThan(),
                            MachineRepresentation::kWord32);
          }
        } else if (jsgraph_->machine()->Is64() &&
                   lhs_type.Is(type_cache_->kSafeInteger) &&
                   rhs_type.Is(type_cache_->kSafeInteger)) {
          VisitInt64Binop<T>(node);
          if (lower<T>()) {
            lowering->DoMax(node, lowering->machine()->Int64LessThan(),
                            MachineRepresentation::kWord64);
          }
        } else {
          VisitBinop<T>(node,
                        UseInfo::TruncatingFloat64(truncation.identify_zeros()),
                        MachineRepresentation::kFloat64);
          if (lower<T>()) {
            // If the right hand side is not NaN, and the left hand side
            // is not NaN (or -0 if the difference between the zeros is
            // observed), we can do a simple floating point comparison here.
            if (lhs_type.Is(truncation.IdentifiesZeroAndMinusZero()
                                ? Type::OrderedNumber()
                                : Type::PlainNumber()) &&
                rhs_type.Is(Type::OrderedNumber())) {
              lowering->DoMax(node, lowering->machine()->Float64LessThan(),
                              MachineRepresentation::kFloat64);
            } else {
              ChangeOp(node, Float64Op(node));
            }
          }
        }
        return;
      }
      case IrOpcode::kNumberMin: {
        // It is safe to use the feedback types for left and right hand side
        // here, since we can only narrow those types and thus we can only
        // promise a more specific truncation.
        // For NumberMin we generally propagate whether the truncation
        // identifies zeros to the inputs, and we choose to ignore minus
        // zero in those cases.
        Type const lhs_type = TypeOf(node->InputAt(0));
        Type const rhs_type = TypeOf(node->InputAt(1));
        if ((lhs_type.Is(Type::Unsigned32()) &&
             rhs_type.Is(Type::Unsigned32())) ||
            (lhs_type.Is(Type::Unsigned32OrMinusZero()) &&
             rhs_type.Is(Type::Unsigned32OrMinusZero()) &&
             truncation.IdentifiesZeroAndMinusZero())) {
          VisitWord32TruncatingBinop<T>(node);
          if (lower<T>()) {
            lowering->DoMin(node, lowering->machine()->Uint32LessThan(),
                            MachineRepresentation::kWord32);
          }
        } else if ((lhs_type.Is(Type::Signed32()) &&
                    rhs_type.Is(Type::Signed32())) ||
                   (lhs_type.Is(Type::Signed32OrMinusZero()) &&
                    rhs_type.Is(Type::Signed32OrMinusZero()) &&
                    truncation.IdentifiesZeroAndMinusZero())) {
          VisitWord32TruncatingBinop<T>(node);
          if (lower<T>()) {
            lowering->DoMin(node, lowering->machine()->Int32LessThan(),
                            MachineRepresentation::kWord32);
          }
        } else if (jsgraph_->machine()->Is64() &&
                   lhs_type.Is(type_cache_->kSafeInteger) &&
                   rhs_type.Is(type_cache_->kSafeInteger)) {
          VisitInt64Binop<T>(node);
          if (lower<T>()) {
            lowering->DoMin(node, lowering->machine()->Int64LessThan(),
                            MachineRepresentation::kWord64);
          }
        } else {
          VisitBinop<T>(node,
                        UseInfo::TruncatingFloat64(truncation.identify_zeros()),
                        MachineRepresentation::kFloat64);
          if (lower<T>()) {
            // If the left hand side is not NaN, and the right hand side
            // is not NaN (or -0 if the difference between the zeros is
            // observed), we can do a simple floating point comparison here.
            if (lhs_type.Is(Type::OrderedNumber()) &&
                rhs_type.Is(truncation.IdentifiesZeroAndMinusZero()
                                ? Type::OrderedNumber()
                                : Type::PlainNumber())) {
              lowering->DoMin(node,
                              lowering->machine()->Float64LessThanOrEqual(),
                              MachineRepresentation::kFloat64);
            } else {
              ChangeOp(node, Float64Op(node));
            }
          }
        }
        return;
      }
      case IrOpcode::kSpeculativeNumberPow: {
        // Checked float64 ** float64 => float64
        VisitBinop<T>(node,
                      UseInfo::CheckedNumberOrOddballAsFloat64(
                          kDistinguishZeros, FeedbackSource()),
                      MachineRepresentation::kFloat64, Type::Number());
        if (lower<T>()) ChangeToPureOp(node, Float64Op(node));
        return;
      }
      case IrOpcode::kNumberAtan2:
      case IrOpcode::kNumberPow: {
        VisitBinop<T>(node, UseInfo::TruncatingFloat64(),
                      MachineRepresentation::kFloat64);
        if (lower<T>()) ChangeOp(node, Float64Op(node));
        return;
      }
      case IrOpcode::kNumberCeil:
      case IrOpcode::kNumberFloor:
      case IrOpcode::kNumberRound:
      case IrOpcode::kNumberTrunc: {
        // For NumberCeil, NumberFloor, NumberRound and NumberTrunc we propagate
        // the zero identification part of the truncation, and we turn them into
        // no-ops if we figure out (late) that their input is already an
        // integer, NaN or -0.
        Type const input_type = TypeOf(node->InputAt(0));
        VisitUnop<T>(node,
                     UseInfo::TruncatingFloat64(truncation.identify_zeros()),
                     MachineRepresentation::kFloat64);
        if (lower<T>()) {
          if (input_type.Is(type_cache_->kIntegerOrMinusZeroOrNaN)) {
            DeferReplacement(node, node->InputAt(0));
          } else if (node->opcode() == IrOpcode::kNumberRound) {
            DeferReplacement(node, lowering->Float64Round(node));
          } else {
            ChangeOp(node, Float64Op(node));
          }
        }
        return;
      }
      case IrOpcode::kSpeculativeBigIntAsIntN:
      case IrOpcode::kSpeculativeBigIntAsUintN: {
        const bool is_asuintn =
            node->opcode() == IrOpcode::kSpeculativeBigIntAsUintN;
        const auto p = SpeculativeBigIntAsNParametersOf(node->op());
        DCHECK_LE(0, p.bits());
        DCHECK_LE(p.bits(), 64);
        ProcessInput<T>(node, 0,
                        UseInfo::CheckedBigIntTruncatingWord64(p.feedback()));
        SetOutput<T>(
            node, MachineRepresentation::kWord64,
            is_asuintn ? Type::UnsignedBigInt64() : Type::SignedBigInt64());
        if (lower<T>()) {
          if (p.bits() == 0) {
            DeferReplacement(node, InsertTypeOverrideForVerifier(
                                       Type::UnsignedBigInt63(),
                                       jsgraph_->Int64Constant(0)));
          } else if (p.bits() == 64) {
            DeferReplacement(node, InsertTypeOverrideForVerifier(
                                       is_asuintn ? Type::UnsignedBigInt64()
                                                  : Type::SignedBigInt64(),
                                       node->InputAt(0)));
          } else {
            if (is_asuintn) {
              const uint64_t mask = (1ULL << p.bits()) - 1ULL;
              ChangeUnaryToPureBinaryOp(node, lowering->machine()->Word64And(),
                                        1, jsgraph_->Int64Constant(mask));
            } else {
              // We truncate the value to N bits, but to correctly interpret
              // negative values, we have to fill the top (64-N) bits with the
              // sign. This is done by shifting the value left and then back
              // with an arithmetic right shift. E.g. for {value} =
              // 0..0'0001'1101 (29n) and N = 3: {shifted} is 1010'0000'0..0
              // after left shift by 61 bits, {unshifted} is 1..1'1111'1101
              // after arithmetic right shift by 61. This is the 64 bit
              // representation of -3 we expect for the signed 3 bit integer
              // 101.
              const uint64_t shift = 64 - p.bits();
              Node* value = node->InputAt(0);
              Node* shifted =
                  graph()->NewNode(lowering->machine()->Word64Shl(), value,
                                   jsgraph_->Uint64Constant(shift));
              Node* unshifted =
                  graph()->NewNode(lowering->machine()->Word64Sar(), shifted,
                                   jsgraph_->Uint64Constant(shift));
              ReplaceWithPureNode(node, unshifted);
            }
          }
        }
        return;
      }
      case IrOpcode::kNumberAcos:
      case IrOpcode::kNumberAcosh:
      case IrOpcode::kNumberAsin:
      case IrOpcode::kNumberAsinh:
      case IrOpcode::kNumberAtan:
      case IrOpcode::kNumberAtanh:
      case IrOpcode::kNumberCos:
      case IrOpcode::kNumberCosh:
      case IrOpcode::kNumberExp:
      case IrOpcode::kNumberExpm1:
      case IrOpcode::kNumberLog:
      case IrOpcode::kNumberLog1p:
      case IrOpcode::kNumberLog2:
      case IrOpcode::kNumberLog10:
      case IrOpcode::kNumberCbrt:
      case IrOpcode::kNumberSin:
      case IrOpcode::kNumberSinh:
      case IrOpcode::kNumberTan:
      case IrOpcode::kNumberTanh: {
        VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                     MachineRepresentation::kFloat64);
        if (lower<T>()) ChangeOp(node, Float64Op(node));
        return;
      }
      case IrOpcode::kNumberSign: {
        if (InputIs(node, Type::Signed32())) {
          VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                       MachineRepresentation::kWord32);
          if (lower<T>()) DeferReplacement(node, lowering->Int32Sign(node));
        } else {
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                       MachineRepresentation::kFloat64);
          if (lower<T>()) DeferReplacement(node, lowering->Float64Sign(node));
        }
        return;
      }
      case IrOpcode::kNumberSilenceNaN: {
        Type const input_type = TypeOf(node->InputAt(0));
        if (input_type.Is(Type::OrderedNumber())) {
          // No need to silence anything if the input cannot be NaN.
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                       MachineRepresentation::kFloat64);
          if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        } else {
          SilenceNanMode mode = SilenceNanModeOf(node->op());
          if (mode == SilenceNanMode::kPreserveUndefined &&
              input_type.Maybe(Type::Undefined())) {
            VisitUnop<T>(node, UseInfo::TruncatingFloat64OrUndefined(),
                         MachineRepresentation::kFloat64);
            // We preserve NumberSilenceNaN here and lower in graph builder.
          } else {
            VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                         MachineRepresentation::kFloat64);
            if (lower<T>()) ChangeOp(node, Float64Op(node));
          }
        }
        return;
      }
      case IrOpcode::kNumberSqrt: {
        VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                     MachineRepresentation::kFloat64);
        if (lower<T>()) ChangeOp(node, Float64Op(node));
        return;
      }
      case IrOpcode::kNumberToBoolean: {
        // For NumberToBoolean we don't care whether the input is 0 or
        // -0, since both of them are mapped to false anyways, so we
        // can generally pass kIdentifyZeros truncation.
        Type const input_type = TypeOf(node->InputAt(0));
        if (input_type.Is(Type::Integral32OrMinusZeroOrNaN())) {
          // 0, -0 and NaN all map to false, so we can safely truncate
          // all of them to zero here.
          VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                       MachineRepresentation::kBit);
          if (lower<T>()) lowering->DoIntegral32ToBit(node);
        } else if (input_type.Is(Type::OrderedNumber())) {
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(kIdentifyZeros),
                       MachineRepresentation::kBit);
          if (lower<T>()) lowering->DoOrderedNumberToBit(node);
        } else {
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(kIdentifyZeros),
                       MachineRepresentation::kBit);
          if (lower<T>()) lowering->DoNumberToBit(node);
        }
        return;
      }
      case IrOpcode::kNumberToInt32: {
        // Just change representation if necessary.
        VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                     MachineRepresentation::kWord32);
        if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        return;
      }
      case IrOpcode::kNumberToString: {
        VisitUnop<T>(node, UseInfo::AnyTagged(),
                     MachineRepresentation::kTaggedPointer);
        return;
      }
      case IrOpcode::kNumberToUint32: {
        // Just change representation if necessary.
        VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                     MachineRepresentation::kWord32);
        if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        return;
      }
      case IrOpcode::kNumberToUint8Clamped: {
        Type const input_type = TypeOf(node->InputAt(0));
        if (input_type.Is(type_cache_->kUint8OrMinusZeroOrNaN)) {
          VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                       MachineRepresentation::kWord32);
          if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        } else if (input_type.Is(Type::Unsigned32OrMinusZeroOrNaN())) {
          VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                       MachineRepresentation::kWord32);
          if (lower<T>()) lowering->DoUnsigned32ToUint8Clamped(node);
        } else if (input_type.Is(Type::Signed32OrMinusZeroOrNaN())) {
          VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                       MachineRepresentation::kWord32);
          if (lower<T>()) lowering->DoSigned32ToUint8Clamped(node);
        } else if (input_type.Is(type_cache_->kIntegerOrMinusZeroOrNaN)) {
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                       MachineRepresentation::kFloat64);
          if (lower<T>()) lowering->DoIntegerToUint8Clamped(node);
        } else {
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                       MachineRepresentation::kFloat64);
          if (lower<T>()) lowering->DoNumberToUint8Clamped(node);
        }
        return;
      }
      case IrOpcode::kIntegral32OrMinusZeroToBigInt: {
        VisitUnop<T>(node, UseInfo::Word64(kIdentifyZeros),
                     MachineRepresentation::kWord64);
        if (lower<T>()) {
          DeferReplacement(
              node, InsertTypeOverrideForVerifier(NodeProperties::GetType(node),
                                                  node->InputAt(0)));
        }
        return;
      }
      case IrOpcode::kReferenceEqual: {
        VisitBinop<T>(node, UseInfo::AnyTagged(), MachineRepresentation::kBit);
        if (lower<T>()) {
          if (COMPRESS_POINTERS_BOOL) {
            ChangeOp(node, lowering->machine()->Word32Equal());
          } else {
            ChangeOp(node, lowering->machine()->WordEqual());
          }
        }
        return;
      }
      case IrOpcode::kSameValueNumbersOnly: {
        VisitBinop<T>(node, UseInfo::AnyTagged(),
                      MachineRepresentation::kTaggedPointer);
        return;
      }
      case IrOpcode::kSameValue: {
        if (truncation.IsUnused()) return VisitUnused<T>(node);
        if (BothInputsAre(node, Type::Number())) {
          VisitBinop<T>(node, UseInfo::TruncatingFloat64(),
                        MachineRepresentation::kBit);
          if (lower<T>()) {
            ChangeOp(node, lowering->simplified()->NumberSameValue());
          }
        } else {
          VisitBinop<T>(node, UseInfo::AnyTagged(),
                        MachineRepresentation::kTaggedPointer);
        }
        return;
      }
      case IrOpcode::kTypeOf: {
        return VisitUnop<T>(node, UseInfo::AnyTagged(),
                            MachineRepresentation::kTaggedPointer);
      }
      case IrOpcode::kNewConsString: {
        ProcessInput<T>(node, 0, UseInfo::TruncatingWord32()); // length
        ProcessInput<T>(node, 1, UseInfo::AnyTagged()); // first
        ProcessInput<T>(node, 2, UseInfo::AnyTagged()); // second
        SetOutput<T>(node, MachineRepresentation::kTaggedPointer);
        return;
      }
      case IrOpcode::kSpeculativeBigIntAdd:
      case IrOpcode::kSpeculativeBigIntSubtract:
      case IrOpcode::kSpeculativeBigIntMultiply: {
        if (truncation.IsUnused() && BothInputsAre(node, Type::BigInt())) {
          VisitUnused<T>(node);
          return;
        }
        if (Is64() && truncation.IsUsedAsWord64()) {
          VisitBinop<T>(
              node, UseInfo::CheckedBigIntTruncatingWord64(FeedbackSource{}),
              MachineRepresentation::kWord64);
          if (lower<T>()) {
            ChangeToPureOp(node, Int64Op(node));
          }
          return;
        }
        BigIntOperationHint hint = BigIntOperationHintOf(node->op());
        switch (hint) {
          case BigIntOperationHint::kBigInt64: {
            VisitBinop<T>(
                node, UseInfo::CheckedBigInt64AsWord64(FeedbackSource{}),
                MachineRepresentation::kWord64, Type::SignedBigInt64());
            if (lower<T>()) {
              ChangeOp(node, Int64OverflowOp(node));
            }
            return;
          }
          case BigIntOperationHint::kBigInt: {
            VisitBinop<T>(
                node, UseInfo::CheckedBigIntAsTaggedPointer(FeedbackSource{}),
                MachineRepresentation::kTaggedPointer);
            if (lower<T>()) {
              ChangeOp(node, BigIntOp(node));
            }
            return;
          }
        }
      }
      case IrOpcode::kSpeculativeBigIntDivide:
      case IrOpcode::kSpeculativeBigIntModulus: {
        if (truncation.IsUnused() && BothInputsAre(node, Type::BigInt())) {
          VisitUnused<T>(node);
          return;
        }
        BigIntOperationHint hint = BigIntOperationHintOf(node->op());
        switch (hint) {
          case BigIntOperationHint::kBigInt64: {
            VisitBinop<T>(
                node, UseInfo::CheckedBigInt64AsWord64(FeedbackSource{}),
                MachineRepresentation::kWord64, Type::SignedBigInt64());
            if (lower<T>()) {
              ChangeOp(node, Int64OverflowOp(node));
            }
            return;
          }
          case BigIntOperationHint::kBigInt: {
            VisitBinop<T>(
                node, UseInfo::CheckedBigIntAsTaggedPointer(FeedbackSource{}),
                MachineRepresentation::kTaggedPointer);
            if (lower<T>()) {
              ChangeOp(node, BigIntOp(node));
            }
            return;
          }
        }
      }
      case IrOpcode::kSpeculativeBigIntBitwiseAnd:
      case IrOpcode::kSpeculativeBigIntBitwiseOr:
      case IrOpcode::kSpeculativeBigIntBitwiseXor: {
        if (truncation.IsUnused() && BothInputsAre(node, Type::BigInt())) {
          VisitUnused<T>(node);
          return;
        }
        if (Is64() && truncation.IsUsedAsWord64()) {
          VisitBinop<T>(
              node, UseInfo::CheckedBigIntTruncatingWord64(FeedbackSource{}),
              MachineRepresentation::kWord64);
          if (lower<T>()) {
            ChangeToPureOp(node, Int64Op(node));
          }
          return;
        }
        BigIntOperationHint hint = BigIntOperationHintOf(node->op());
        switch (hint) {
          case BigIntOperationHint::kBigInt64: {
            VisitBinop<T>(
                node, UseInfo::CheckedBigInt64AsWord64(FeedbackSource{}),
                MachineRepresentation::kWord64, Type::SignedBigInt64());
            if (lower<T>()) {
              ChangeToPureOp(node, Int64Op(node));
            }
            return;
          }
          case BigIntOperationHint::kBigInt: {
            VisitBinop<T>(
                node, UseInfo::CheckedBigIntAsTaggedPointer(FeedbackSource{}),
                MachineRepresentation::kTaggedPointer);
            if (lower<T>()) {
              ChangeOp(node, BigIntOp(node));
            }
            return;
          }
        }
      }
      case IrOpcode::kSpeculativeBigIntShiftLeft:
      case IrOpcode::kSpeculativeBigIntShiftRight: {
        if (truncation.IsUnused() && BothInputsAre(node, Type::BigInt())) {
          VisitUnused<T>(node);
          return;
        }
        if (Is64() && TryOptimizeBigInt64Shift<T>(node, truncation, lowering)) {
          return;
        }
        DCHECK_EQ(BigIntOperationHintOf(node->op()),
                  BigIntOperationHint::kBigInt);
        VisitBinop<T>(node,
                      UseInfo::CheckedBigIntAsTaggedPointer(FeedbackSource{}),
                      MachineRepresentation::kTaggedPointer);
        if (lower<T>()) {
          ChangeOp(node, BigIntOp(node));
        }
        return;
      }
      case IrOpcode::kSpeculativeBigIntEqual:
      case IrOpcode::kSpeculativeBigIntLessThan:
      case IrOpcode::kSpeculativeBigIntLessThanOrEqual: {
        // Loose equality can throw a TypeError when failing to cast an object
        // operand to primitive.
        if (truncation.IsUnused() && BothInputsAre(node, Type::BigInt())) {
          VisitUnused<T>(node);
          return;
        }
        BigIntOperationHint hint = BigIntOperationHintOf(node->op());
        switch (hint) {
          case BigIntOperationHint::kBigInt64: {
            VisitBinop<T>(node,
                          UseInfo::CheckedBigInt64AsWord64(FeedbackSource{}),
                          MachineRepresentation::kBit);
            if (lower<T>()) {
              ChangeToPureOp(node, Int64Op(node));
            }
            return;
          }
          case BigIntOperationHint::kBigInt: {
            VisitBinop<T>(
                node, UseInfo::CheckedBigIntAsTaggedPointer(FeedbackSource{}),
                MachineRepresentation::kTaggedPointer);
            if (lower<T>()) {
              ChangeToPureOp(node, BigIntOp(node));
            }
            return;
          }
        }
      }
      case IrOpcode::kSpeculativeBigIntNegate: {
        // NOTE: If truncation is Unused, we still need to preserve at least the
        // BigInt type check (see http://crbug.com/1431713 for some details).
        // We can use the standard lowering to word64 operations and have
        // following phases remove the unused truncation and subtraction
        // operations.
        if (Is64() && truncation.IsUsedAsWord64()) {
          VisitUnop<T>(node,
                       UseInfo::CheckedBigIntTruncatingWord64(FeedbackSource{}),
                       MachineRepresentation::kWord64);
          if (lower<T>()) {
            ChangeUnaryToPureBinaryOp(node, lowering->machine()->Int64Sub(), 0,
                                      jsgraph_->Int64Constant(0));
          }
        } else {
          VisitUnop<T>(node,
                       UseInfo::CheckedBigIntAsTaggedPointer(FeedbackSource{}),
                       MachineRepresentation::kTaggedPointer);
          if (lower<T>()) {
            ChangeToPureOp(node, lowering->simplified()->BigIntNegate());
          }
        }
        return;
      }
      case IrOpcode::kStringConcat: {
        // TODO(turbofan): We currently depend on having this first length input
        // to make sure that the overflow check is properly scheduled before the
        // actual string concatenation. We should also use the length to pass it
        // to the builtin or decide in optimized code how to construct the
        // resulting string (i.e. cons string or sequential string).
        ProcessInput<T>(node, 0, UseInfo::TaggedSigned()); // length
        ProcessInput<T>(node, 1, UseInfo::AnyTagged()); // first
        ProcessInput<T>(node, 2, UseInfo::AnyTagged()); // second
        SetOutput<T>(node, MachineRepresentation::kTaggedPointer);
        return;
      }
      case IrOpcode::kStringEqual:
      case IrOpcode::kStringLessThan:
      case IrOpcode::kStringLessThanOrEqual:
      case IrOpcode::kStringOrOddballStrictEqual: {
        return VisitBinop<T>(node, UseInfo::AnyTagged(),
                             MachineRepresentation::kTaggedPointer);
      }
      case IrOpcode::kStringCharCodeAt: {
        return VisitBinop<T>(node, UseInfo::AnyTagged(), UseInfo::Word(),
                             MachineRepresentation::kWord32);
      }
      case IrOpcode::kStringCodePointAt: {
        return VisitBinop<T>(node, UseInfo::AnyTagged(), UseInfo::Word(),
                             MachineRepresentation::kWord32);
      }
      case IrOpcode::kStringFromSingleCharCode: {
        VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                     MachineRepresentation::kTaggedPointer);
        return;
      }
      case IrOpcode::kStringFromSingleCodePoint: {
        VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                     MachineRepresentation::kTaggedPointer);
        return;
      }
      case IrOpcode::kStringFromCodePointAt: {
        return VisitBinop<T>(node, UseInfo::AnyTagged(), UseInfo::Word(),
                             MachineRepresentation::kTaggedPointer);
      }
      case IrOpcode::kStringIndexOf: {
        ProcessInput<T>(node, 0, UseInfo::AnyTagged());
        ProcessInput<T>(node, 1, UseInfo::AnyTagged());
        ProcessInput<T>(node, 2, UseInfo::TaggedSigned());
        SetOutput<T>(node, MachineRepresentation::kTaggedSigned);
        return;
      }
      case IrOpcode::kStringLength:
      case IrOpcode::kStringWrapperLength: {
        // TODO(bmeurer): The input representation should be TaggedPointer.
        // Fix this once we have a dedicated StringConcat/JSStringAdd
        // operator, which marks it's output as TaggedPointer properly.
        VisitUnop<T>(node, UseInfo::AnyTagged(),
                     MachineRepresentation::kWord32);
        return;
      }
      case IrOpcode::kTypedArrayLength: {
        VisitUnop<T>(node, UseInfo::AnyTagged(),
                     MachineType::PointerRepresentation());
        return;
      }
      case IrOpcode::kStringSubstring: {
        ProcessInput<T>(node, 0, UseInfo::AnyTagged());
        ProcessInput<T>(node, 1, UseInfo::TruncatingWord32());
        ProcessInput<T>(node, 2, UseInfo::TruncatingWord32());
        ProcessRemainingInputs<T>(node, 3);
        SetOutput<T>(node, MachineRepresentation::kTaggedPointer);
        return;
      }
      case IrOpcode::kStringToLowerCaseIntl:
      case IrOpcode::kStringToUpperCaseIntl: {
        VisitUnop<T>(node, UseInfo::AnyTagged(),
                     MachineRepresentation::kTaggedPointer);
        return;
      }
      case IrOpcode::kCheckBounds:
        return VisitCheckBounds<T>(node, lowering);
      case IrOpcode::kCheckHeapObject: {
        if (InputCannotBe(node, Type::SignedSmall())) {
          VisitUnop<T>(node, UseInfo::AnyTagged(),
                       MachineRepresentation::kTaggedPointer);
        } else {
          VisitUnop<T>(
              node, UseInfo::CheckedHeapObjectAsTaggedPointer(FeedbackSource()),
              MachineRepresentation::kTaggedPointer);
        }
        if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        return;
      }
      case IrOpcode::kCheckIf: {
        ProcessInput<T>(node, 0, UseInfo::Bool());
        ProcessRemainingInputs<T>(node, 1);
        SetOutput<T>(node, MachineRepresentation::kNone);
        return;
      }
      case IrOpcode::kCheckInternalizedString: {
        VisitCheck<T>(node, Type::InternalizedString(), lowering);
        return;
      }
      case IrOpcode::kCheckNumber: {
        Type const input_type = TypeOf(node->InputAt(0));
        if (input_type.Is(Type::Number())) {
          VisitNoop<T>(node, truncation);
        } else {
          VisitUnop<T>(node, UseInfo::AnyTagged(),
                       MachineRepresentation::kTagged);
        }
        return;
      }
      case IrOpcode::kCheckNumberOrUndefined: {
        Type const input_type = TypeOf(node->InputAt(0));
        Type const output_type =
            Type::Intersect(input_type, Type::NumberOrUndefined(), zone());
        if (input_type.Is(Type::NumberOrUndefined())) {
          if (truncation.IsUnused()) {
            VisitUnused<T>(node);
          } else if (truncation.TruncatesBooleanAndNullAndBigIntToNumber()) {
            VisitUnop<T>(node,
                         UseInfo::TruncatingFloat64OrUndefined(
                             truncation.identify_zeros()),
                         MachineRepresentation::kFloat64, output_type);
            if (lower<T>()) DeferReplacement(node, node->InputAt(0));
          } else {
            VisitNoop<T>(node, truncation);
          }
        } else {
          VisitUnop<T>(node, UseInfo::AnyTagged(),
                       MachineRepresentation::kTagged, output_type);
        }
        return;
      }
      case IrOpcode::kCheckNumberFitsInt32: {
        Type const input_type = TypeOf(node->InputAt(0));
        if (input_type.Is(Type::Signed32())) {
          VisitNoop<T>(node, truncation);
        } else {
          VisitUnop<T>(node, UseInfo::AnyTagged(),
                       MachineRepresentation::kTagged);
        }
        return;
      }
      case IrOpcode::kCheckReceiver: {
        VisitCheck<T>(node, Type::Receiver(), lowering);
        return;
      }
      case IrOpcode::kCheckReceiverOrNullOrUndefined: {
        VisitCheck<T>(node, Type::ReceiverOrNullOrUndefined(), lowering);
        return;
      }
      case IrOpcode::kCheckSmi: {
        const CheckParameters& params = CheckParametersOf(node->op());
        if (SmiValuesAre32Bits() && truncation.IsUsedAsWord32()) {
          VisitUnop<T>(node,
                       UseInfo::CheckedSignedSmallAsWord32(kDistinguishZeros,
                                                           params.feedback()),
                       MachineRepresentation::kWord32);
        } else {
          VisitUnop<T>(
              node,
              UseInfo::CheckedSignedSmallAsTaggedSigned(params.feedback()),
              MachineRepresentation::kTaggedSigned);
        }
        if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        return;
      }
      case IrOpcode::kCheckString: {
        const CheckParameters& params = CheckParametersOf(node->op());
        if (InputIs(node, Type::String())) {
          VisitUnop<T>(node, UseInfo::AnyTagged(),
                       MachineRepresentation::kTaggedPointer);
          if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        } else {
          VisitUnop<T>(
              node,
              UseInfo::CheckedHeapObjectAsTaggedPointer(params.feedback()),
              MachineRepresentation::kTaggedPointer);
        }
        return;
      }
      case IrOpcode::kCheckStringOrStringWrapper: {
        const CheckParameters& params = CheckParametersOf(node->op());
        if (InputIs(node, Type::StringOrStringWrapper())) {
          VisitUnop<T>(node, UseInfo::AnyTagged(),
                       MachineRepresentation::kTaggedPointer);
          if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        } else {
          VisitUnop<T>(
              node,
              UseInfo::CheckedHeapObjectAsTaggedPointer(params.feedback()),
              MachineRepresentation::kTaggedPointer);
        }
        return;
      }
      case IrOpcode::kCheckStringOrOddball: {
        const CheckParameters& params = CheckParametersOf(node->op());
        if (InputIs(node, Type::StringOrOddball())) {
          VisitUnop<T>(node, UseInfo::AnyTagged(),
                       MachineRepresentation::kTaggedPointer);
          if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        } else {
          VisitUnop<T>(
              node,
              UseInfo::CheckedHeapObjectAsTaggedPointer(params.feedback()),
              MachineRepresentation::kTaggedPointer);
        }
        return;
      }
      case IrOpcode::kCheckSymbol: {
        VisitCheck<T>(node, Type::Symbol(), lowering);
        return;
      }
      case IrOpcode::kAllocate: {
        ProcessInput<T>(node, 0, UseInfo::Word());
        ProcessRemainingInputs<T>(node, 1);
        SetOutput<T>(node, MachineRepresentation::kTaggedPointer);
        return;
      }
      case IrOpcode::kLoadFramePointer: {
        SetOutput<T>(node, MachineType::PointerRepresentation());
        return;
      }
#if V8_ENABLE_WEBASSEMBLY
      case IrOpcode::kLoadStackPointer: {
        SetOutput<T>(node, MachineType::PointerRepresentation());
        return;
      }
      case IrOpcode::kSetStackPointer: {
        SetOutput<T>(node, MachineRepresentation::kNone);
        return;
      }
#endif // V8_ENABLE_WEBASSEMBLY
      case IrOpcode::kLoadMessage: {
        if (truncation.IsUnused()) return VisitUnused<T>(node);
        VisitUnop<T>(node, UseInfo::Word(), MachineRepresentation::kTagged);
        return;
      }
      case IrOpcode::kStoreMessage: {
        ProcessInput<T>(node, 0, UseInfo::Word());
        ProcessInput<T>(node, 1, UseInfo::AnyTagged());
        ProcessRemainingInputs<T>(node, 2);
        SetOutput<T>(node, MachineRepresentation::kNone);
        return;
      }
      case IrOpcode::kLoadFieldByIndex: {
        if (truncation.IsUnused()) return VisitUnused<T>(node);
        VisitBinop<T>(node, UseInfo::AnyTagged(), UseInfo::TruncatingWord32(),
                      MachineRepresentation::kTagged);
        return;
      }
      case IrOpcode::kLoadField: {
        if (truncation.IsUnused()) return VisitUnused<T>(node);
        FieldAccess access = FieldAccessOf(node->op());
        MachineRepresentation const representation =
            access.machine_type.representation();
        VisitUnop<T>(node, UseInfoForBasePointer(access), representation);
        return;
      }
      case IrOpcode::kStoreField: {
        FieldAccess access = FieldAccessOf(node->op());
        Node* value_node = node->InputAt(1);
        NodeInfo* input_info = GetInfo(value_node);
        MachineRepresentation field_representation =
            access.machine_type.representation();
        // Convert to Smi if possible, such that we can avoid a write barrier.
        if (field_representation == MachineRepresentation::kTagged &&
            TypeOf(value_node).Is(Type::SignedSmall())) {
          field_representation = MachineRepresentation::kTaggedSigned;
        }
        WriteBarrierKind write_barrier_kind = WriteBarrierKindFor(
            access.base_is_tagged, field_representation, access.offset,
            access.type, input_info->representation(), value_node);
        ProcessInput<T>(node, 0, UseInfoForBasePointer(access));
        ProcessInput<T>(
            node, 1, TruncatingUseInfoFromRepresentation(field_representation));
        ProcessRemainingInputs<T>(node, 2);
        SetOutput<T>(node, MachineRepresentation::kNone);
        if (lower<T>()) {
          if (write_barrier_kind < access.write_barrier_kind) {
            access.write_barrier_kind = write_barrier_kind;
            ChangeOp(node, jsgraph_->simplified()->StoreField(access));
          }
        }
        return;
      }
      case IrOpcode::kLoadElement: {
        if (truncation.IsUnused()) return VisitUnused<T>(node);
        ElementAccess access = ElementAccessOf(node->op());
        VisitBinop<T>(node, UseInfoForBasePointer(access), UseInfo::Word(),
                      access.machine_type.representation());
        return;
      }
      case IrOpcode::kLoadStackArgument: {
        if (truncation.IsUnused()) return VisitUnused<T>(node);
        VisitBinop<T>(node, UseInfo::Word(), MachineRepresentation::kTagged);
        return;
      }
      case IrOpcode::kStoreElement: {
        ElementAccess access = ElementAccessOf(node->op());
        Node* value_node = node->InputAt(2);
        NodeInfo* input_info = GetInfo(value_node);
        MachineRepresentation element_representation =
            access.machine_type.representation();
        // Convert to Smi if possible, such that we can avoid a write barrier.
        if (element_representation == MachineRepresentation::kTagged &&
            TypeOf(value_node).Is(Type::SignedSmall())) {
          element_representation = MachineRepresentation::kTaggedSigned;
        }
        WriteBarrierKind write_barrier_kind = WriteBarrierKindFor(
            access.base_is_tagged, element_representation, access.type,
            input_info->representation(), value_node);
        ProcessInput<T>(node, 0, UseInfoForBasePointer(access)); // base
        ProcessInput<T>(node, 1, UseInfo::Word()); // index
        ProcessInput<T>(node, 2,
                        TruncatingUseInfoFromRepresentation(
                            element_representation, access.type)); // value
        ProcessRemainingInputs<T>(node, 3);
        SetOutput<T>(node, MachineRepresentation::kNone);
        if (lower<T>()) {
          if (write_barrier_kind < access.write_barrier_kind) {
            access.write_barrier_kind = write_barrier_kind;
            ChangeOp(node, jsgraph_->simplified()->StoreElement(access));
          }
        }
        return;
      }
      case IrOpcode::kNumberIsFloat64Hole: {
        VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                     MachineRepresentation::kBit);
        return;
      }
      case IrOpcode::kTransitionAndStoreElement: {
        Type value_type = TypeOf(node->InputAt(2));
        ProcessInput<T>(node, 0, UseInfo::AnyTagged()); // array
        ProcessInput<T>(node, 1, UseInfo::Word()); // index
        if (value_type.Is(Type::SignedSmall())) {
          ProcessInput<T>(node, 2, UseInfo::TruncatingWord32()); // value
          if (lower<T>()) {
            ChangeOp(node, simplified()->StoreSignedSmallElement());
          }
        } else if (value_type.Is(Type::Number())) {
          ProcessInput<T>(node, 2, UseInfo::TruncatingFloat64()); // value
          if (lower<T>()) {
            MapRef double_map = DoubleMapParameterOf(node->op());
            ChangeOp(node,
                     simplified()->TransitionAndStoreNumberElement(double_map));
          }
        } else if (value_type.Is(Type::NonNumber())) {
          ProcessInput<T>(node, 2, UseInfo::AnyTagged()); // value
          if (lower<T>()) {
            MapRef fast_map = FastMapParameterOf(node->op());
            ChangeOp(node, simplified()->TransitionAndStoreNonNumberElement(
                               fast_map, value_type));
          }
        } else {
          ProcessInput<T>(node, 2, UseInfo::AnyTagged()); // value
        }
        ProcessRemainingInputs<T>(node, 3);
        SetOutput<T>(node, MachineRepresentation::kNone);
        return;
      }
      case IrOpcode::kLoadTypedElement: {
        MachineRepresentation const rep =
            MachineRepresentationFromArrayType(ExternalArrayTypeOf(node->op()));
        ProcessInput<T>(node, 0, UseInfo::AnyTagged()); // buffer
        ProcessInput<T>(node, 1, UseInfo::AnyTagged()); // base pointer
        ProcessInput<T>(node, 2, UseInfo::Word()); // external pointer
        ProcessInput<T>(node, 3, UseInfo::Word()); // index
        ProcessRemainingInputs<T>(node, 4);
        SetOutput<T>(node, rep);
        return;
      }
      case IrOpcode::kLoadDataViewElement: {
        MachineRepresentation const rep =
            MachineRepresentationFromArrayType(ExternalArrayTypeOf(node->op()));
        ProcessInput<T>(node, 0, UseInfo::AnyTagged()); // object
        ProcessInput<T>(node, 1, UseInfo::Word()); // base
        ProcessInput<T>(node, 2, UseInfo::Word()); // index
        ProcessInput<T>(node, 3, UseInfo::Bool()); // little-endian
        ProcessRemainingInputs<T>(node, 4);
        SetOutput<T>(node, rep);
        return;
      }
      case IrOpcode::kStoreTypedElement: {
        MachineRepresentation const rep =
            MachineRepresentationFromArrayType(ExternalArrayTypeOf(node->op()));
        ProcessInput<T>(node, 0, UseInfo::AnyTagged()); // buffer
        ProcessInput<T>(node, 1, UseInfo::AnyTagged()); // base pointer
        ProcessInput<T>(node, 2, UseInfo::Word()); // external pointer
        ProcessInput<T>(node, 3, UseInfo::Word()); // index
        ProcessInput<T>(node, 4,
                        TruncatingUseInfoFromRepresentation(rep)); // value
        ProcessRemainingInputs<T>(node, 5);
        SetOutput<T>(node, MachineRepresentation::kNone);
        return;
      }
      case IrOpcode::kStoreDataViewElement: {
        MachineRepresentation const rep =
            MachineRepresentationFromArrayType(ExternalArrayTypeOf(node->op()));
        ProcessInput<T>(node, 0, UseInfo::AnyTagged()); // object
        ProcessInput<T>(node, 1, UseInfo::Word()); // base
        ProcessInput<T>(node, 2, UseInfo::Word()); // index
        ProcessInput<T>(node, 3,
                        TruncatingUseInfoFromRepresentation(rep)); // value
        ProcessInput<T>(node, 4, UseInfo::Bool()); // little-endian
        ProcessRemainingInputs<T>(node, 5);
        SetOutput<T>(node, MachineRepresentation::kNone);
        return;
      }
      case IrOpcode::kConvertReceiver: {
        Type input_type = TypeOf(node->InputAt(0));
        ProcessInput<T>(node, 0, UseInfo::AnyTagged()); // object
        ProcessInput<T>(node, 1, UseInfo::AnyTagged()); // native_context
        ProcessInput<T>(node, 2, UseInfo::AnyTagged()); // global_proxy
        ProcessRemainingInputs<T>(node, 3);
        SetOutput<T>(node, MachineRepresentation::kTaggedPointer);
        if (lower<T>()) {
          // Try to optimize the {node} based on the input type.
          if (input_type.Is(Type::Receiver())) {
            DeferReplacement(node, node->InputAt(0));
          } else if (input_type.Is(Type::NullOrUndefined())) {
            DeferReplacement(node, node->InputAt(2));
          } else if (!input_type.Maybe(Type::NullOrUndefined())) {
            ChangeOp(node, lowering->simplified()->ConvertReceiver(
                               ConvertReceiverMode::kNotNullOrUndefined));
          }
        }
        return;
      }
      case IrOpcode::kPlainPrimitiveToNumber: {
        if (InputIs(node, Type::Boolean())) {
          VisitUnop<T>(node, UseInfo::Bool(), MachineRepresentation::kWord32);
          if (lower<T>()) {
            DeferReplacement(node, InsertSemanticsHintForVerifier(
                                       node->op(), node->InputAt(0)));
          }
        } else if (InputIs(node, Type::String())) {
          VisitUnop<T>(node, UseInfo::AnyTagged(),
                       MachineRepresentation::kTagged);
          if (lower<T>()) {
            ChangeOp(node, simplified()->StringToNumber());
          }
        } else if (truncation.IsUsedAsWord32()) {
          if (InputIs(node, Type::NumberOrOddball())) {
            VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                         MachineRepresentation::kWord32);
            if (lower<T>()) {
              DeferReplacement(node, InsertSemanticsHintForVerifier(
                                         node->op(), node->InputAt(0)));
            }
          } else {
            VisitUnop<T>(node, UseInfo::AnyTagged(),
                         MachineRepresentation::kWord32);
            if (lower<T>()) {
              ChangeOp(node, simplified()->PlainPrimitiveToWord32());
            }
          }
        } else if (truncation.TruncatesOddballAndBigIntToNumber()) {
          if (InputIs(node, Type::NumberOrOddball())) {
            VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                         MachineRepresentation::kFloat64);
            if (lower<T>()) {
              DeferReplacement(node, InsertSemanticsHintForVerifier(
                                         node->op(), node->InputAt(0)));
            }
          } else {
            VisitUnop<T>(node, UseInfo::AnyTagged(),
                         MachineRepresentation::kFloat64);
            if (lower<T>()) {
              ChangeOp(node, simplified()->PlainPrimitiveToFloat64());
            }
          }
        } else {
          VisitUnop<T>(node, UseInfo::AnyTagged(),
                       MachineRepresentation::kTagged);
        }
        return;
      }
      case IrOpcode::kSpeculativeToNumber: {
        NumberOperationParameters const& p =
            NumberOperationParametersOf(node->op());
        switch (p.hint()) {
          case NumberOperationHint::kSignedSmall:
          case NumberOperationHint::kSignedSmallInputs:
            VisitUnop<T>(node,
                         CheckedUseInfoAsWord32FromHint(
                             p.hint(), kDistinguishZeros, p.feedback()),
                         MachineRepresentation::kWord32, Type::Signed32());
            break;
          case NumberOperationHint::kAdditiveSafeInteger:
          case NumberOperationHint::kNumber:
          case NumberOperationHint::kNumberOrBoolean:
          case NumberOperationHint::kNumberOrOddball:
            VisitUnop<T>(
                node, CheckedUseInfoAsFloat64FromHint(p.hint(), p.feedback()),
                MachineRepresentation::kFloat64);
            break;
        }
        if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        return;
      }
      case IrOpcode::kSpeculativeToBigInt: {
        if (truncation.IsUnused() && InputIs(node, Type::BigInt())) {
          VisitUnused<T>(node);
          return;
        }
        if (Is64() && truncation.IsUsedAsWord64()) {
          VisitUnop<T>(node,
                       UseInfo::CheckedBigIntTruncatingWord64(FeedbackSource{}),
                       MachineRepresentation::kWord64);
        } else {
          BigIntOperationParameters const& p =
              BigIntOperationParametersOf(node->op());
          switch (p.hint()) {
            case BigIntOperationHint::kBigInt64: {
              VisitUnop<T>(node, UseInfo::CheckedBigInt64AsWord64(p.feedback()),
                           MachineRepresentation::kWord64);
              break;
            }
            case BigIntOperationHint::kBigInt: {
              VisitUnop<T>(node,
                           UseInfo::CheckedBigIntAsTaggedPointer(p.feedback()),
                           MachineRepresentation::kTaggedPointer);
            }
          }
        }
        if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        return;
      }
      case IrOpcode::kObjectIsArrayBufferView: {
        // TODO(turbofan): Introduce a Type::ArrayBufferView?
        VisitUnop<T>(node, UseInfo::AnyTagged(), MachineRepresentation::kBit);
        return;
      }
      case IrOpcode::kObjectIsBigInt: {
        VisitObjectIs<T>(node, Type::BigInt(), lowering);
        return;
      }
      case IrOpcode::kObjectIsCallable: {
        VisitObjectIs<T>(node, Type::Callable(), lowering);
        return;
      }
      case IrOpcode::kObjectIsConstructor: {
        // TODO(turbofan): Introduce a Type::Constructor?
        VisitUnop<T>(node, UseInfo::AnyTagged(), MachineRepresentation::kBit);
        return;
      }
      case IrOpcode::kObjectIsDetectableCallable: {
        VisitObjectIs<T>(node, Type::DetectableCallable(), lowering);
        return;
      }
      case IrOpcode::kObjectIsFiniteNumber: {
        Type const input_type = GetUpperBound(node->InputAt(0));
        if (input_type.Is(type_cache_->kSafeInteger)) {
          VisitUnop<T>(node, UseInfo::None(), MachineRepresentation::kBit);
          if (lower<T>()) {
            DeferReplacement(
                node, InsertTypeOverrideForVerifier(
                          true_type(), lowering->jsgraph()->Int32Constant(1)));
          }
        } else if (!input_type.Maybe(Type::Number())) {
          VisitUnop<T>(node, UseInfo::Any(), MachineRepresentation::kBit);
          if (lower<T>()) {
            DeferReplacement(
                node, InsertTypeOverrideForVerifier(
                          false_type(), lowering->jsgraph()->Int32Constant(0)));
          }
        } else if (input_type.Is(Type::Number())) {
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                       MachineRepresentation::kBit);
          if (lower<T>()) {
            ChangeOp(node, lowering->simplified()->NumberIsFinite());
          }
        } else {
          VisitUnop<T>(node, UseInfo::AnyTagged(), MachineRepresentation::kBit);
        }
        return;
      }
      case IrOpcode::kNumberIsFinite: {
        VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                     MachineRepresentation::kBit);
        return;
      }
      case IrOpcode::kObjectIsSafeInteger: {
        Type const input_type = GetUpperBound(node->InputAt(0));
        if (input_type.Is(type_cache_->kSafeInteger)) {
          VisitUnop<T>(node, UseInfo::None(), MachineRepresentation::kBit);
          if (lower<T>()) {
            DeferReplacement(
                node, InsertTypeOverrideForVerifier(
                          true_type(), lowering->jsgraph()->Int32Constant(1)));
          }
        } else if (!input_type.Maybe(Type::Number())) {
          VisitUnop<T>(node, UseInfo::Any(), MachineRepresentation::kBit);
          if (lower<T>()) {
            DeferReplacement(
                node, InsertTypeOverrideForVerifier(
                          false_type(), lowering->jsgraph()->Int32Constant(0)));
          }
        } else if (input_type.Is(Type::Number())) {
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                       MachineRepresentation::kBit);
          if (lower<T>()) {
            ChangeOp(node, lowering->simplified()->NumberIsSafeInteger());
          }
        } else {
          VisitUnop<T>(node, UseInfo::AnyTagged(), MachineRepresentation::kBit);
        }
        return;
      }
      case IrOpcode::kNumberIsSafeInteger: {
        UNREACHABLE();
      }
      case IrOpcode::kObjectIsInteger: {
        Type const input_type = GetUpperBound(node->InputAt(0));
        if (input_type.Is(type_cache_->kSafeInteger)) {
          VisitUnop<T>(node, UseInfo::None(), MachineRepresentation::kBit);
          if (lower<T>()) {
            DeferReplacement(
                node, InsertTypeOverrideForVerifier(
                          true_type(), lowering->jsgraph()->Int32Constant(1)));
          }
        } else if (!input_type.Maybe(Type::Number())) {
          VisitUnop<T>(node, UseInfo::Any(), MachineRepresentation::kBit);
          if (lower<T>()) {
            DeferReplacement(
                node, InsertTypeOverrideForVerifier(
                          false_type(), lowering->jsgraph()->Int32Constant(0)));
          }
        } else if (input_type.Is(Type::Number())) {
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                       MachineRepresentation::kBit);
          if (lower<T>()) {
            ChangeOp(node, lowering->simplified()->NumberIsInteger());
          }
        } else {
          VisitUnop<T>(node, UseInfo::AnyTagged(), MachineRepresentation::kBit);
        }
        return;
      }
      case IrOpcode::kNumberIsInteger: {
        VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                     MachineRepresentation::kBit);
        return;
      }
      case IrOpcode::kObjectIsMinusZero: {
        Type const input_type = GetUpperBound(node->InputAt(0));
        if (input_type.Is(Type::MinusZero())) {
          VisitUnop<T>(node, UseInfo::None(), MachineRepresentation::kBit);
          if (lower<T>()) {
            DeferReplacement(
                node, InsertTypeOverrideForVerifier(
                          true_type(), lowering->jsgraph()->Int32Constant(1)));
          }
        } else if (!input_type.Maybe(Type::MinusZero())) {
          VisitUnop<T>(node, UseInfo::Any(), MachineRepresentation::kBit);
          if (lower<T>()) {
            DeferReplacement(
                node, InsertTypeOverrideForVerifier(
                          false_type(), lowering->jsgraph()->Int32Constant(0)));
          }
        } else if (input_type.Is(Type::Number())) {
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                       MachineRepresentation::kBit);
          if (lower<T>()) {
            ChangeOp(node, simplified()->NumberIsMinusZero());
          }
        } else {
          VisitUnop<T>(node, UseInfo::AnyTagged(), MachineRepresentation::kBit);
        }
        return;
      }
      case IrOpcode::kObjectIsNaN: {
        Type const input_type = GetUpperBound(node->InputAt(0));
        if (input_type.Is(Type::NaN())) {
          VisitUnop<T>(node, UseInfo::None(), MachineRepresentation::kBit);
          if (lower<T>()) {
            DeferReplacement(
                node, InsertTypeOverrideForVerifier(
                          true_type(), lowering->jsgraph()->Int32Constant(1)));
          }
        } else if (!input_type.Maybe(Type::NaN())) {
          VisitUnop<T>(node, UseInfo::Any(), MachineRepresentation::kBit);
          if (lower<T>()) {
            DeferReplacement(
                node, InsertTypeOverrideForVerifier(
                          false_type(), lowering->jsgraph()->Int32Constant(0)));
          }
        } else if (input_type.Is(Type::Number())) {
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                       MachineRepresentation::kBit);
          if (lower<T>()) {
            ChangeOp(node, simplified()->NumberIsNaN());
          }
        } else {
          VisitUnop<T>(node, UseInfo::AnyTagged(), MachineRepresentation::kBit);
        }
        return;
      }
      case IrOpcode::kNumberIsNaN: {
        VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                     MachineRepresentation::kBit);
        return;
      }
      case IrOpcode::kObjectIsNonCallable: {
        VisitObjectIs<T>(node, Type::NonCallable(), lowering);
        return;
      }
      case IrOpcode::kObjectIsNumber: {
        VisitObjectIs<T>(node, Type::Number(), lowering);
        return;
      }
      case IrOpcode::kObjectIsReceiver: {
        VisitObjectIs<T>(node, Type::Receiver(), lowering);
        return;
      }
      case IrOpcode::kObjectIsSmi: {
        // TODO(turbofan): Optimize based on input representation.
        VisitUnop<T>(node, UseInfo::AnyTagged(), MachineRepresentation::kBit);
        return;
      }
      case IrOpcode::kObjectIsString: {
        VisitObjectIs<T>(node, Type::String(), lowering);
        return;
      }
      case IrOpcode::kObjectIsSymbol: {
        VisitObjectIs<T>(node, Type::Symbol(), lowering);
        return;
      }
      case IrOpcode::kObjectIsUndetectable: {
        VisitObjectIs<T>(node, Type::Undetectable(), lowering);
        return;
      }
      case IrOpcode::kArgumentsLength:
      case IrOpcode::kRestLength: {
        SetOutput<T>(node, MachineRepresentation::kTaggedSigned);
        return;
      }
      case IrOpcode::kNewDoubleElements:
      case IrOpcode::kNewSmiOrObjectElements: {
        VisitUnop<T>(node, UseInfo::Word(),
                     MachineRepresentation::kTaggedPointer);
        return;
      }
      case IrOpcode::kNewArgumentsElements: {
        VisitUnop<T>(node, UseInfo::TaggedSigned(),
                     MachineRepresentation::kTaggedPointer);
        return;
      }
      case IrOpcode::kCheckFloat64Hole: {
        Type const input_type = TypeOf(node->InputAt(0));
        CheckFloat64HoleMode mode =
            CheckFloat64HoleParametersOf(node->op()).mode();
        if (mode == CheckFloat64HoleMode::kAllowReturnHole) {
          // If {mode} is allow-return-hole _and_ the {truncation}
          // identifies NaN and undefined, we can just pass along
          // the {truncation} and completely wipe the {node}.
          if (truncation.IsUnused()) return VisitUnused<T>(node);
          if (truncation.TruncatesOddballAndBigIntToNumber()) {
            VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                         MachineRepresentation::kFloat64);
            if (lower<T>()) DeferReplacement(node, node->InputAt(0));
            return;
          }
        }
        VisitUnop<T>(
            node, UseInfo(MachineRepresentation::kFloat64, Truncation::Any()),
            MachineRepresentation::kFloat64, Type::Number());
        if (lower<T>() && input_type.Is(Type::Number())) {
          DeferReplacement(node, node->InputAt(0));
        }
        return;
      }
      case IrOpcode::kChangeFloat64HoleToTagged: {
        // If the {truncation} identifies NaN and undefined, we can just pass
        // along the {truncation} and completely wipe the {node}.
        if (truncation.IsUnused()) return VisitUnused<T>(node);
        if (truncation.TruncatesOddballAndBigIntToNumber()) {
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                       MachineRepresentation::kFloat64);
          if (lower<T>()) DeferReplacement(node, node->InputAt(0));
          return;
        }
        VisitUnop<T>(
            node, UseInfo(MachineRepresentation::kFloat64, Truncation::Any()),
            MachineRepresentation::kTagged);
        return;
      }
      case IrOpcode::kChangeFloat64OrUndefinedOrHoleToTagged: {
        // TODO(nicohartmann): Consider using truncation.
        VisitUnop<T>(node,
                     UseInfo(MachineRepresentation::kFloat64,
                             Truncation::BooleanAndNullAndBigIntToNumber()),
                     MachineRepresentation::kTagged);
        return;
      }
      case IrOpcode::kCheckNotTaggedHole: {
        VisitUnop<T>(node, UseInfo::AnyTagged(),
                     MachineRepresentation::kTagged);
        return;
      }
      case IrOpcode::kCheckClosure: {
        VisitUnop<T>(
            node, UseInfo::CheckedHeapObjectAsTaggedPointer(FeedbackSource()),
            MachineRepresentation::kTaggedPointer);
        return;
      }
      case IrOpcode::kConvertTaggedHoleToUndefined: {
        if (InputIs(node, Type::NumberOrHole()) &&
            truncation.IsUsedAsWord32() && !truncation.check_safe_integer()) {
          // Propagate the Word32 truncation.
          VisitUnop<T>(node, UseInfo::TruncatingWord32(),
                       MachineRepresentation::kWord32);
          if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        } else if (InputIs(node, Type::NumberOrHole()) &&
                   truncation.TruncatesOddballAndBigIntToNumber()) {
          // Propagate the Float64 truncation.
          VisitUnop<T>(node, UseInfo::TruncatingFloat64(),
                       MachineRepresentation::kFloat64);
          if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        } else if (InputIs(node, Type::NumberOrUndefinedOrHole()) &&
                   truncation.TruncatesBooleanAndNullAndBigIntToNumber()) {
          VisitUnop<T>(node, UseInfo::AnyTagged(),
                       MachineRepresentation::kTagged);
        } else if (InputIs(node, Type::NonInternal())) {
          VisitUnop<T>(node, UseInfo::AnyTagged(),
                       MachineRepresentation::kTagged);
          if (lower<T>()) DeferReplacement(node, node->InputAt(0));
        } else {
          // TODO(turbofan): Add a (Tagged) truncation that identifies hole
          // and undefined, i.e. for a[i] === obj cases.
          VisitUnop<T>(node, UseInfo::AnyTagged(),
                       MachineRepresentation::kTagged);
        }
        return;
      }
      case IrOpcode::kCheckEqualsSymbol:
      case IrOpcode::kCheckEqualsInternalizedString:
        return VisitBinop<T>(node, UseInfo::AnyTagged(),
                             MachineRepresentation::kNone);
      case IrOpcode::kMapGuard:
        // Eliminate MapGuard nodes here.
        return VisitUnused<T>(node);
      case IrOpcode::kCheckMaps: {
        CheckMapsParameters const& p = CheckMapsParametersOf(node->op());
        return VisitUnop<T>(
            node, UseInfo::CheckedHeapObjectAsTaggedPointer(p.feedback()),
            MachineRepresentation::kNone);
      }
      case IrOpcode::kTransitionElementsKind: {
        return VisitUnop<T>(
            node, UseInfo::CheckedHeapObjectAsTaggedPointer(FeedbackSource()),
            MachineRepresentation::kNone);
      }
      case IrOpcode::kTransitionElementsKindOrCheckMap: {
        return VisitUnop<T>(
            node, UseInfo::CheckedHeapObjectAsTaggedPointer(FeedbackSource()),
            MachineRepresentation::kNone);
      }
      case IrOpcode::kCompareMaps:
        return VisitUnop<T>(
            node, UseInfo::CheckedHeapObjectAsTaggedPointer(FeedbackSource()),
            MachineRepresentation::kBit);
      case IrOpcode::kEnsureWritableFastElements:
        return VisitBinop<T>(node, UseInfo::AnyTagged(),
                             MachineRepresentation::kTaggedPointer);
      case IrOpcode::kMaybeGrowFastElements: {
        ProcessInput<T>(node, 0, UseInfo::AnyTagged()); // object
        ProcessInput<T>(node, 1, UseInfo::AnyTagged()); // elements
        ProcessInput<T>(node, 2, UseInfo::TruncatingWord32()); // index
        ProcessInput<T>(node, 3, UseInfo::TruncatingWord32()); // length
        ProcessRemainingInputs<T>(node, 4);
        SetOutput<T>(node, MachineRepresentation::kTaggedPointer);
        return;
      }
      case IrOpcode::kDateNow:
        VisitInputs<T>(node);
        return SetOutput<T>(node, MachineRepresentation::kTagged);
      case IrOpcode::kDoubleArrayMax: {
        return VisitUnop<T>(node, UseInfo::AnyTagged(),
                            MachineRepresentation::kTagged);
      }
      case IrOpcode::kDoubleArrayMin: {
        return VisitUnop<T>(node, UseInfo::AnyTagged(),
                            MachineRepresentation::kTagged);
      }
      case IrOpcode::kFrameState:
        return VisitFrameState<T>(FrameState{node});
      case IrOpcode::kStateValues:
        return VisitStateValues<T>(node);
      case IrOpcode::kObjectState:
        return VisitObjectState<T>(node);
      case IrOpcode::kObjectId:
        return SetOutput<T>(node, MachineRepresentation::kTaggedPointer);
      case IrOpcode::kTypeGuard: {
        if (truncation.IsUnused()) return VisitUnused<T>(node);
        // We just get rid of the sigma here, choosing the best representation
        // for the sigma's type.
        Type type = TypeOf(node);
        MachineRepresentation representation =
            GetOutputInfoForPhi(type, truncation);
        // Here we pretend that the input has the sigma's type for the
        // conversion.
        UseInfo use(representation, truncation);
        if (propagate<T>()) {
          EnqueueInput<T>(node, 0, use);
        } else if (lower<T>()) {
          ConvertInput(node, 0, use, type);
        }
        ProcessRemainingInputs<T>(node, 1);
        SetOutput<T>(node, representation);
        return;
      }
      case IrOpcode::kFinishRegion:
        VisitInputs<T>(node);
        // Assume the output is tagged pointer.
        return SetOutput<T>(node, MachineRepresentation::kTaggedPointer);
      case IrOpcode::kReturn:
        VisitReturn<T>(node);
        // Assume the output is tagged.
        return SetOutput<T>(node, MachineRepresentation::kTagged);
      case IrOpcode::kFindOrderedHashMapEntry: {
        Type const key_type = TypeOf(node->InputAt(1));
        if (key_type.Is(Type::Signed32OrMinusZero())) {
          VisitBinop<T>(node, UseInfo::AnyTagged(), UseInfo::TruncatingWord32(),
                        MachineType::PointerRepresentation());
          if (lower<T>()) {
            ChangeOp(
                node,
                lowering->simplified()->FindOrderedHashMapEntryForInt32Key());
          }
        } else {
          VisitBinop<T>(node, UseInfo::AnyTagged(),
                        MachineRepresentation::kTaggedSigned);
        }
        return;
      }
      case IrOpcode::kFindOrderedHashSetEntry:
        VisitBinop<T>(node, UseInfo::AnyTagged(),
                      MachineRepresentation::kTaggedSigned);
        return;
      case IrOpcode::kFastApiCall: {
        VisitFastApiCall<T>(node, lowering);
        return;
      }
      // Operators with all inputs tagged and no or tagged output have uniform
      // handling.
      case IrOpcode::kEnd:
      case IrOpcode::kIfSuccess:
      case IrOpcode::kIfException:
      case IrOpcode::kIfTrue:
      case IrOpcode::kIfFalse:
      case IrOpcode::kIfValue:
      case IrOpcode::kIfDefault:
      case IrOpcode::kDeoptimize:
      case IrOpcode::kEffectPhi:
      case IrOpcode::kTerminate:
      case IrOpcode::kCheckpoint:
      case IrOpcode::kLoop:
      case IrOpcode::kMerge:
      case IrOpcode::kThrow:
      case IrOpcode::kBeginRegion:
      case IrOpcode::kProjection:
      case IrOpcode::kOsrValue:
      case IrOpcode::kArgumentsElementsState:
      case IrOpcode::kArgumentsLengthState:
      case IrOpcode::kUnreachable:
      case IrOpcode::kRuntimeAbort:
// All JavaScript operators except JSToNumber, JSToNumberConvertBigInt,
// kJSToNumeric and JSWasmCall have uniform handling.
#define OPCODE_CASE(name, ...) case IrOpcode::k##name:
        JS_SIMPLE_BINOP_LIST(OPCODE_CASE)
        JS_OBJECT_OP_LIST(OPCODE_CASE)
        JS_CONTEXT_OP_LIST(OPCODE_CASE)
        JS_OTHER_OP_LIST(OPCODE_CASE)
#undef OPCODE_CASE
      case IrOpcode::kJSBitwiseNot:
      case IrOpcode::kJSDecrement:
      case IrOpcode::kJSIncrement:
      case IrOpcode::kJSNegate:
      case IrOpcode::kJSToLength:
      case IrOpcode::kJSToName:
      case IrOpcode::kJSToObject:
      case IrOpcode::kJSToString:
      case IrOpcode::kJSParseInt:
#if V8_ENABLE_WEBASSEMBLY
        if (node->opcode() == IrOpcode::kJSWasmCall) {
          return VisitJSWasmCall<T>(node, lowering);
        }
#endif // V8_ENABLE_WEBASSEMBLY
        VisitInputs<T>(node);
        // Assume the output is tagged.
        return SetOutput<T>(node, MachineRepresentation::kTagged);
      case IrOpcode::kDeadValue:
        ProcessInput<T>(node, 0, UseInfo::Any());
        return SetOutput<T>(node, MachineRepresentation::kNone);
      case IrOpcode::kStaticAssert:
        DCHECK(TypeOf(node->InputAt(0)).Is(Type::Boolean()));
        return VisitUnop<T>(node, UseInfo::Bool(),
                            MachineRepresentation::kTagged);
      case IrOpcode::kAssertType:
        return VisitUnop<T>(node, UseInfo::AnyTagged(),
                            MachineRepresentation::kTagged);
      case IrOpcode::kVerifyType: {
        Type inputType = TypeOf(node->InputAt(0));
        VisitUnop<T>(node, UseInfo::AnyTagged(), MachineRepresentation::kTagged,
                     inputType);
        if (lower<T>()) {
          if (inputType.CanBeAsserted()) {
            ChangeOp(node, simplified()->AssertType(inputType));
          } else {
            if (!v8_flags.fuzzing) {
#ifdef DEBUG
              inputType.Print();
#endif
              FATAL("%%VerifyType: unsupported type");
            }
            DisconnectFromEffectAndControl(node);
          }
        }
        return;
      }
      case IrOpcode::kCheckTurboshaftTypeOf: {
        NodeInfo* info = GetInfo(node->InputAt(0));
        MachineRepresentation input_rep = info->representation();
        ProcessInput<T>(node, 0, UseInfo{input_rep, Truncation::None()});
        ProcessInput<T>(node, 1, UseInfo::Any());
        SetOutput<T>(node, input_rep);
        return;
      }
      case IrOpcode::kDebugBreak:
        return;
      // Nodes from machine graphs.
      case IrOpcode::kEnterMachineGraph: {
        DCHECK_EQ(1, node->op()->ValueInputCount());
        UseInfo use_info = OpParameter<UseInfo>(node->op());
        ProcessInput<T>(node, 0, use_info);
        SetOutput<T>(node, use_info.representation());
        if (lower<T>()) {
          DeferReplacement(node, InsertTypeOverrideForVerifier(
                                     Type::Machine(), node->InputAt(0)));
        }
        return;
      }
      case IrOpcode::kExitMachineGraph: {
        DCHECK_EQ(1, node->op()->ValueInputCount());
        ProcessInput<T>(node, 0, UseInfo::Any());
        const auto& p = ExitMachineGraphParametersOf(node->op());
        SetOutput<T>(node, p.output_representation(), p.output_type());
        if (lower<T>()) {
          DeferReplacement(node, InsertTypeOverrideForVerifier(
                                     p.output_type(), node->InputAt(0)));
        }
        return;
      }
      case IrOpcode::kInt32Add:
      case IrOpcode::kInt32LessThanOrEqual:
      case IrOpcode::kInt32Sub:
      case IrOpcode::kUint32LessThan:
      case IrOpcode::kUint32LessThanOrEqual:
      case IrOpcode::kUint64LessThan:
      case IrOpcode::kUint64LessThanOrEqual:
      case IrOpcode::kUint32Div:
      case IrOpcode::kWord32And:
      case IrOpcode::kWord32Equal:
      case IrOpcode::kWord32Or:
      case IrOpcode::kWord32Shl:
      case IrOpcode::kWord32Shr:
        for (int i = 0; i < node->InputCount(); ++i) {
          ProcessInput<T>(node, i, UseInfo::Any());
        }
        SetOutput<T>(node, MachineRepresentation::kWord32);
        return;
      case IrOpcode::kInt64Add:
      case IrOpcode::kInt64Sub:
      case IrOpcode::kUint64Div:
      case IrOpcode::kWord64And:
      case IrOpcode::kWord64Shl:
      case IrOpcode::kWord64Shr:
      case IrOpcode::kChangeUint32ToUint64:
        for (int i = 0; i < node->InputCount(); ++i) {
          ProcessInput<T>(node, i, UseInfo::Any());
        }
        SetOutput<T>(node, MachineRepresentation::kWord64);
        return;
      case IrOpcode::kLoad:
        for (int i = 0; i < node->InputCount(); ++i) {
          ProcessInput<T>(node, i, UseInfo::Any());
        }
        SetOutput<T>(node, LoadRepresentationOf(node->op()).representation());
        return;
#ifdef V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
      case IrOpcode::kGetContinuationPreservedEmbedderData:
        SetOutput<T>(node, MachineRepresentation::kTagged);
        return;
      case IrOpcode::kSetContinuationPreservedEmbedderData:
        ProcessInput<T>(node, 0, UseInfo::AnyTagged());
        SetOutput<T>(node, MachineRepresentation::kNone);
        return;
#endif // V8_ENABLE_CONTINUATION_PRESERVED_EMBEDDER_DATA
      default:
        FATAL(
            "Representation inference: unsupported opcode %i (%s), node #%i\n.",
            node->opcode(), node->op()->mnemonic(), node->id());
        break;
    }
    UNREACHABLE();
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::UseInfo::Any(), v8::internal::compiler::Truncation::Any(), v8::internal::compiler::UseInfo::AnyTagged(), v8::internal::compiler::UseInfo::AnyTruncatingToBool(), v8::internal::compiler::Node::AppendInput(), v8::internal::compiler::AssertParametersOf(), v8::internal::compiler::FieldAccess::base_is_tagged, v8::internal::compiler::ElementAccess::base_is_tagged, v8::internal::compiler::SimplifiedOperatorBuilder::BigIntNegate(), BigIntOp(), v8::internal::compiler::BigIntOperationHintOf(), v8::internal::compiler::BigIntOperationParametersOf(), v8::internal::compiler::UseInfo::Bool(), v8::internal::compiler::Truncation::BooleanAndNullAndBigIntToNumber(), BothInputsAre(), BothInputsAreSigned32(), BothInputsAreUnsigned32(), v8::internal::compiler::BranchParametersOf(), v8::internal::compiler::Type::CanBeAsserted(), v8::internal::CanBeTaggedPointer(), ChangeOp(), changer_, ChangeToInt32OverflowOp(), ChangeToPureOp(), ChangeToUint32OverflowOp(), ChangeUnaryToPureBinaryOp(), CHECK, v8::internal::compiler::Truncation::check_safe_integer(), v8::internal::compiler::UseInfo::CheckedBigInt64AsWord64(), v8::internal::compiler::UseInfo::CheckedBigIntAsTaggedPointer(), v8::internal::compiler::UseInfo::CheckedBigIntTruncatingWord64(), v8::internal::compiler::UseInfo::CheckedHeapObjectAsTaggedPointer(), v8::internal::compiler::UseInfo::CheckedNumberOrOddballAsFloat64(), v8::internal::compiler::UseInfo::CheckedSignedSmallAsTaggedSigned(), v8::internal::compiler::UseInfo::CheckedSignedSmallAsWord32(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CheckedUseInfoAsFloat64FromHint(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CheckedUseInfoAsWord32FromHint(), v8::internal::compiler::CheckFloat64HoleParametersOf(), v8::internal::compiler::CheckMapsParametersOf(), v8::internal::compiler::CheckParametersOf(), common(), COMPRESS_POINTERS_BOOL, v8::internal::compiler::Operator::ControlOutputCount(), ConvertInput(), v8::internal::compiler::SimplifiedOperatorBuilder::ConvertReceiver(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_NE, DeferReplacement(), DisconnectFromEffectAndControl(), v8::internal::compiler::SimplifiedLowering::DoIntegerToUint8Clamped(), v8::internal::compiler::SimplifiedLowering::DoIntegral32ToBit(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToFloat64(), v8::internal::compiler::SimplifiedLowering::DoJSToNumberOrNumericTruncatesToWord32(), v8::internal::compiler::SimplifiedLowering::DoMax(), v8::internal::compiler::SimplifiedLowering::DoMin(), v8::internal::compiler::SimplifiedLowering::DoNumberToBit(), v8::internal::compiler::SimplifiedLowering::DoNumberToUint8Clamped(), v8::internal::compiler::SimplifiedLowering::DoOrderedNumberToBit(), v8::internal::compiler::SimplifiedLowering::DoSigned32ToUint8Clamped(), v8::internal::compiler::DoubleMapParameterOf(), v8::internal::DoubleToSmiInteger(), v8::internal::compiler::SimplifiedLowering::DoUnsigned32ToUint8Clamped(), v8::internal::compiler::Operator::EffectOutputCount(), v8::internal::compiler::ElementAccessOf(), v8::internal::compiler::ExitMachineGraphParametersOf(), v8::internal::compiler::ExternalArrayTypeOf(), false_type(), v8::internal::compiler::FastMapParameterOf(), FATAL, v8::internal::compiler::CheckParameters::feedback(), v8::internal::compiler::CheckMapsParameters::feedback(), v8::internal::compiler::NumberOperationParameters::feedback(), v8::internal::compiler::BigIntOperationParameters::feedback(), v8::internal::compiler::FieldAccessOf(), v8::internal::compiler::SimplifiedOperatorBuilder::FindOrderedHashMapEntryForInt32Key(), v8::internal::compiler::NodeProperties::FirstControlIndex(), v8::internal::compiler::MachineOperatorBuilder::Float64LessThan(), v8::internal::compiler::MachineOperatorBuilder::Float64LessThanOrEqual(), Float64Op(), v8::internal::compiler::SimplifiedLowering::Float64Round(), v8::internal::compiler::SimplifiedLowering::Float64Sign(), v8::internal::Smi::FromInt(), GetInfo(), GetOutputInfoForPhi(), v8::internal::compiler::NodeProperties::GetType(), GetUpperBound(), graph(), v8::internal::compiler::Operator::HasProperty(), v8::internal::compiler::NumberOperationParameters::hint(), v8::internal::compiler::BigIntOperationParameters::hint(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::id(), v8::internal::compiler::Truncation::IdentifiesZeroAndMinusZero(), v8::internal::compiler::Truncation::identify_zeros(), v8::internal::compiler::Node::InputAt(), InputCannotBe(), v8::internal::compiler::Node::InputCount(), InputIs(), InsertSemanticsHintForVerifier(), InsertTypeOverrideForVerifier(), v8::internal::compiler::SimplifiedLowering::Int32Abs(), v8::internal::compiler::MachineGraph::Int32Constant(), v8::internal::compiler::SimplifiedLowering::Int32Div(), v8::internal::compiler::MachineOperatorBuilder::Int32LessThan(), v8::internal::compiler::SimplifiedLowering::Int32Mod(), Int32Op(), v8::internal::compiler::SimplifiedLowering::Int32Sign(), v8::internal::compiler::MachineGraph::Int64Constant(), v8::internal::compiler::MachineOperatorBuilder::Int64LessThan(), Int64Op(), Int64OverflowOp(), v8::internal::compiler::MachineOperatorBuilder::Int64Sub(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::MachineGraph::IntPtrConstant(), v8::internal::Is(), v8::internal::compiler::Type::Is(), v8::internal::Is64(), v8::internal::compiler::MachineOperatorBuilder::Is64(), IsNodeRepresentationTagged(), v8::internal::compiler::Type::IsNone(), v8::internal::IsNone(), v8::internal::compiler::Truncation::IsUnused(), v8::internal::compiler::Truncation::IsUsedAsBool(), v8::internal::compiler::Truncation::IsUsedAsWord32(), v8::internal::compiler::Truncation::IsUsedAsWord64(), JS_CONTEXT_OP_LIST, JS_OBJECT_OP_LIST, JS_OTHER_OP_LIST, JS_SIMPLE_BINOP_LIST, v8::internal::compiler::SimplifiedLowering::jsgraph(), jsgraph_, v8::internal::compiler::kAdditiveSafeInteger, v8::internal::compiler::TypeCache::kAdditiveSafeIntegerOrMinusZero, v8::internal::compiler::kAllowReturnHole, v8::internal::compiler::kBigInt, v8::internal::compiler::kBigInt64, v8::internal::kBit, v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::kDistinguishZeros, v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::compiler::kIdentifyZeros, v8::internal::compiler::TypeCache::kIntegerOrMinusZeroOrNaN, v8::internal::compiler::kMachine, v8::internal::kNone, v8::internal::kNotNullOrUndefined, v8::internal::compiler::kNumber, v8::internal::compiler::kNumberOrBoolean, v8::internal::compiler::kNumberOrOddball, v8::internal::compiler::TypeCache::kPositiveIntegerOrNaN, v8::internal::kPreserveUndefined, v8::internal::compiler::Operator::kPure, v8::internal::compiler::TypeCache::kSafeInteger, v8::internal::compiler::TypeCache::kSafeIntegerOrMinusZero, v8::internal::compiler::kSignedSmall, v8::internal::compiler::kSignedSmallInputs, v8::kStart, v8::internal::wasm::kSwitch, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::compiler::TypeCache::kUint8OrMinusZeroOrNaN, v8::internal::wasm::kUnreachable, v8::internal::kWord32, v8::internal::kWord64, v8::internal::compiler::TypeCache::kZeroish, linkage(), v8::internal::compiler::LoadRepresentationOf(), v8::internal::compiler::SimplifiedLowering::machine(), v8::internal::compiler::MachineGraph::machine(), v8::internal::compiler::FieldAccess::machine_type, v8::internal::compiler::ElementAccess::machine_type, v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::MachineRepresentationFromArrayType(), MaskShiftOperand(), v8::internal::compiler::Type::Maybe(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::CheckFloat64HoleParameters::mode(), mode(), v8::internal::compiler::TFGraph::NewNode(), v8::internal::compiler::turboshaft::Type::None(), v8::internal::compiler::Truncation::None(), v8::internal::compiler::UseInfo::None(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberIsFinite(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberIsInteger(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberIsSafeInteger(), v8::internal::compiler::NumberOperationHintOf(), v8::internal::compiler::NumberOperationParametersOf(), v8::internal::compiler::SimplifiedOperatorBuilder::NumberSameValue(), v8::internal::compiler::FieldAccess::offset, OneInputCannotBe(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), OPCODE_CASE, v8::internal::compiler::ParameterIndexOf(), v8::internal::MachineType::PointerRepresentation(), v8::internal::compiler::SimplifiedLoweringVerifier::RecordMachineUsesOfConstant(), v8::internal::compiler::Node::RemoveInput(), v8::internal::compiler::Node::ReplaceInput(), ReplaceWithPureNode(), v8::internal::MachineType::representation(), v8::internal::compiler::RepresentationSelector::NodeInfo::representation(), v8::internal::compiler::UseInfo::representation(), v8::internal::compiler::SelectParametersOf(), v8::internal::compiler::RepresentationSelector::NodeInfo::set_feedback_type(), v8::internal::compiler::Type::SignedSmall(), v8::internal::compiler::SilenceNanModeOf(), v8::internal::compiler::SimplifiedLowering::simplified(), v8::internal::compiler::JSGraph::simplified(), simplified(), v8::internal::SmiValuesAre32Bits(), v8::internal::compiler::SpeculativeBigIntAsNParametersOf(), v8::internal::compiler::SimplifiedOperatorBuilder::StoreElement(), v8::internal::compiler::SimplifiedOperatorBuilder::StoreField(), v8::internal::compiler::MachineOperatorBuilder::TaggedEqual(), v8::internal::compiler::UseInfo::TaggedSigned(), v8::internal::compiler::RepresentationChanger::TaggedSignedOperatorFor(), tick_counter_, v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), v8::internal::compiler::Node::TrimInputCount(), true_type(), v8::internal::compiler::Truncation::TruncatesBooleanAndNullAndBigIntToNumber(), v8::internal::compiler::Truncation::TruncatesOddballAndBigIntToNumber(), v8::internal::compiler::UseInfo::TruncatingFloat64(), v8::internal::compiler::UseInfo::TruncatingFloat64OrUndefined(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::TruncatingUseInfoFromRepresentation(), v8::internal::compiler::UseInfo::TruncatingWord32(), v8::internal::compiler::FieldAccess::type, v8::internal::compiler::ElementAccess::type, v8::internal::tracing::type, type_cache_, TypeOf(), v8::internal::compiler::SimplifiedLowering::Uint32Div(), v8::internal::compiler::MachineOperatorBuilder::Uint32LessThan(), v8::internal::compiler::SimplifiedLowering::Uint32Mod(), Uint32Op(), v8::internal::compiler::MachineGraph::Uint64Constant(), v8::internal::compiler::Undefined, v8::internal::compiler::Type::Union(), v8::internal::UNREACHABLE(), use(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::UseInfoForBasePointer(), v8::internal::compiler::Node::uses(), v8::internal::v8_flags, V8_UNLIKELY, v8::internal::value, v8::internal::wasm::value_type(), v8::internal::compiler::Operator::ValueInputCount(), v8::internal::compiler::Operator::ValueOutputCount(), verification_enabled(), verifier_, v8::internal::compiler::UseInfo::Word(), v8::internal::compiler::MachineOperatorBuilder::Word32Equal(), v8::internal::compiler::MachineOperatorBuilder::Word32Sar(), v8::internal::compiler::MachineOperatorBuilder::Word32Shl(), v8::internal::compiler::MachineOperatorBuilder::Word32Shr(), v8::internal::compiler::UseInfo::Word64(), v8::internal::compiler::MachineOperatorBuilder::Word64And(), v8::internal::compiler::MachineOperatorBuilder::Word64Sar(), v8::internal::compiler::MachineOperatorBuilder::Word64Shl(), v8::internal::compiler::FieldAccess::write_barrier_kind, v8::internal::compiler::ElementAccess::write_barrier_kind, WriteBarrierKindFor(), zone(), and v8::internal::compiler::MachineGraph::zone().
VisitNoop()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitNoop (Node * node, Truncation truncation) [inline]
Definition at line 1135 of file simplified-lowering.cc.
                                                    {
    if (truncation.IsUnused()) return VisitUnused<T>(node);
    MachineRepresentation representation =
        GetOutputInfoForPhi(TypeOf(node), truncation);
    VisitUnop<T>(node, UseInfo(representation, truncation), representation);
    if (lower<T>()) DeferReplacement(node, node->InputAt(0));
  }
References DeferReplacement(), GetOutputInfoForPhi(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Truncation::IsUnused(), and TypeOf().
VisitObjectIs()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitObjectIs (Node * node, Type type, SimplifiedLowering * lowering) [inline]
Definition at line 1301 of file simplified-lowering.cc.
                                                                          {
    Type const input_type = TypeOf(node->InputAt(0));
    if (input_type.Is(type)) {
      VisitUnop<T>(node, UseInfo::None(), MachineRepresentation::kBit);
      if (lower<T>()) {
        DeferReplacement(
            node, InsertTypeOverrideForVerifier(
                      true_type(), lowering->jsgraph()->Int32Constant(1)));
      }
    } else {
      VisitUnop<T>(node, UseInfo::AnyTagged(), MachineRepresentation::kBit);
      if (lower<T>() && !input_type.Maybe(type)) {
        DeferReplacement(
            node, InsertTypeOverrideForVerifier(
                      false_type(), lowering->jsgraph()->Int32Constant(0)));
      }
    }
  }
References v8::internal::compiler::UseInfo::AnyTagged(), DeferReplacement(), false_type(), v8::internal::compiler::Node::InputAt(), InsertTypeOverrideForVerifier(), v8::internal::compiler::MachineGraph::Int32Constant(), v8::internal::compiler::Type::Is(), v8::internal::compiler::SimplifiedLowering::jsgraph(), v8::internal::kBit, v8::internal::compiler::Type::Maybe(), v8::internal::compiler::UseInfo::None(), true_type(), v8::internal::tracing::type, and TypeOf().
VisitObjectState()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitObjectState (Node * node) [inline]
Definition at line 1529 of file simplified-lowering.cc.
                                    {
    if (propagate<T>()) {
      for (int i = 0; i < node->InputCount(); i++) {
        if (IsLargeBigInt(TypeOf(node->InputAt(i)))) {
          EnqueueInput<T>(node, i, UseInfo::AnyTagged());
        } else if (IsLoadFloat16ArrayElement(node->InputAt(i))) {
          EnqueueInput<T>(node, i, UseInfo::Float64());
        } else {
          EnqueueInput<T>(node, i, UseInfo::Any());
        }
      }
    } else if (lower<T>()) {
      Zone* zone = jsgraph_->zone();
      ZoneVector<MachineType>* types =
          zone->New<ZoneVector<MachineType>>(node->InputCount(), zone);
      for (int i = 0; i < node->InputCount(); i++) {
        Node* input = node->InputAt(i);
        MachineRepresentation input_rep = GetInfo(input)->representation();
        if (IsLargeBigInt(TypeOf(input))) {
          ConvertInput(node, i, UseInfo::AnyTagged());
        } else if (IsLoadFloat16ArrayElement(input)) {
          ConvertInput(node, i, UseInfo::Float64());
          input_rep = MachineRepresentation::kFloat64;
        }
        (*types)[i] = DeoptMachineTypeOf(input_rep, TypeOf(input));
      }
      ChangeOp(node, common()->TypedObjectState(ObjectIdOf(node->op()), types));
    }
    SetOutput<T>(node, MachineRepresentation::kTagged);
  }
References v8::internal::compiler::UseInfo::Any(), v8::internal::compiler::UseInfo::AnyTagged(), ChangeOp(), common(), ConvertInput(), DeoptMachineTypeOf(), v8::internal::compiler::UseInfo::Float64(), GetInfo(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::IsLargeBigInt(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::IsLoadFloat16ArrayElement(), jsgraph_, v8::internal::kFloat64, v8::internal::kTagged, v8::internal::Zone::New(), v8::internal::compiler::ObjectIdOf(), v8::internal::compiler::Node::op(), v8::internal::compiler::RepresentationSelector::NodeInfo::representation(), TypeOf(), zone(), and v8::internal::compiler::MachineGraph::zone().
VisitPhi()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitPhi (Node * node, Truncation truncation, SimplifiedLowering * lowering) [inline]
Definition at line 1271 of file simplified-lowering.cc.
                                              {
    // If we already have a non-tagged representation set in the Phi node, it
    // does come from subgraphs using machine operators we introduced early in
    // the pipeline. In this case, we just keep the representation.
    MachineRepresentation output = PhiRepresentationOf(node->op());
    if (output == MachineRepresentation::kTagged) {
      output = GetOutputInfoForPhi(TypeOf(node), truncation);
    }
    // Only set the output representation if not running with type
    // feedback. (Feedback typing will set the representation.)
    SetOutput<T>(node, output);
    int values = node->op()->ValueInputCount();
    if (lower<T>()) {
      // Update the phi operator.
      if (output != PhiRepresentationOf(node->op())) {
        ChangeOp(node, lowering->common()->Phi(output, values));
      }
    }
    // Convert inputs to the output representation of this phi, pass the
    // truncation along.
    UseInfo input_use(output, truncation);
    for (int i = 0; i < node->InputCount(); i++) {
      ProcessInput<T>(node, i, i < values ? input_use : UseInfo::None());
    }
  }
References ChangeOp(), v8::internal::compiler::SimplifiedLowering::common(), GetOutputInfoForPhi(), v8::internal::compiler::Node::InputCount(), v8::internal::kTagged, v8::internal::compiler::UseInfo::None(), v8::internal::compiler::Node::op(), v8::internal::compiler::CommonOperatorBuilder::Phi(), v8::internal::compiler::PhiRepresentationOf(), TypeOf(), and v8::internal::compiler::Operator::ValueInputCount().
VisitReturn()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitReturn (Node * node) [inline]
Definition at line 1100 of file simplified-lowering.cc.
                               {
    int first_effect_index = NodeProperties::FirstEffectIndex(node);
    // Visit integer slot count to pop
    ProcessInput<T>(node, 0, UseInfo::TruncatingWord32());
    // Visit value, context and frame state inputs as tagged.
    for (int i = 1; i < first_effect_index; i++) {
      ProcessInput<T>(node, i, UseInfo::AnyTagged());
    }
    // Only enqueue other inputs (effects, control).
    for (int i = first_effect_index; i < node->InputCount(); i++) {
      EnqueueInput<T>(node, i);
    }
  }
References v8::internal::compiler::UseInfo::AnyTagged(), v8::internal::compiler::NodeProperties::FirstEffectIndex(), v8::internal::compiler::Node::InputCount(), and v8::internal::compiler::UseInfo::TruncatingWord32().
VisitSelect()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitSelect (Node * node, Truncation truncation, SimplifiedLowering * lowering) [inline]
Definition at line 1246 of file simplified-lowering.cc.
                                                 {
    DCHECK(TypeOf(node->InputAt(0)).Is(Type::Boolean()));
    ProcessInput<T>(node, 0, UseInfo::Bool());
    MachineRepresentation output =
        GetOutputInfoForPhi(TypeOf(node), truncation);
    SetOutput<T>(node, output);
    if (lower<T>()) {
      // Update the select operator.
      SelectParameters p = SelectParametersOf(node->op());
      if (output != p.representation()) {
        ChangeOp(node, lowering->common()->Select(output, p.hint()));
      }
    }
    // Convert inputs to the output representation of this phi, pass the
    // truncation truncation along.
    UseInfo input_use(output, truncation);
    ProcessInput<T>(node, 1, input_use);
    ProcessInput<T>(node, 2, input_use);
  }
References v8::internal::compiler::UseInfo::Bool(), ChangeOp(), v8::internal::compiler::SimplifiedLowering::common(), v8::internal::DCHECK(), GetOutputInfoForPhi(), v8::internal::compiler::SelectParameters::hint(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Node::op(), v8::internal::compiler::SelectParameters::representation(), v8::internal::compiler::CommonOperatorBuilder::Select(), v8::internal::compiler::SelectParametersOf(), and TypeOf().
VisitSpeculativeAdditiveOp()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitSpeculativeAdditiveOp (Node * node, Truncation truncation, SimplifiedLowering * lowering) [inline]
Definition at line 1808 of file simplified-lowering.cc.
                                                                {
    if (BothInputsAre(node, Type::Integral32OrMinusZero())) {
      if (GetUpperBound(node).Is(Type::Signed32()) ||
          GetUpperBound(node).Is(Type::Unsigned32()) ||
          truncation.IsUsedAsWord32()) {
        // => Int32Add/Sub
        VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                      MachineRepresentation::kWord32);
        if (lower<T>()) ChangeToPureOp(node, Int32Op(node));
        return;
      }
      // TODO(victorgomes): Simplify this to a Word64Add. We don't need the
      // additive safe integer range check, since we know inputs are Integral32.
      if (v8_flags.additive_safe_int_feedback &&
          NumberOperationHintOf(node->op()) ==
              NumberOperationHint::kAdditiveSafeInteger) {
        // => AdditiveSafeIntegerAdd/Sub
        VisitBinop<T>(node, UseInfo::CheckedSafeIntAsWord64(FeedbackSource{}),
                      MachineRepresentation::kWord64,
                      type_cache_->kAdditiveSafeInteger);
        if (lower<T>()) ChangeOp(node, AdditiveSafeIntegerOverflowOp(node));
        return;
      }
    }
    if (CanSpeculateAdditiveSafeInteger(node)) {
      if (truncation.IsUnused()) {
        if (lower<T>() && TypeOf(node).IsNone()) {
          DeferReplacement(
              node, InsertUnconditionalDeopt(
                        node, DeoptimizeReason::kNotAdditiveSafeInteger));
        }
        return VisitUnused<T>(node);
      }
      if (truncation.IsUsedAsWord32() && !TypeOf(node).IsNone()) {
        // This case handles addition where the result might be truncated to
        // word32. Even if the inputs might be larger than 2^32, we can safely
        // perform 32-bit addition *here* if the inputs are in the additive
        // safe range. We *must* propagate the CheckedSafeIntTruncatingWord32
        // information. This is because we need to ensure that we deoptimize
        // if either input is not an integer, or not in the range.
        // => Int32Add/Sub
        VisitBinop<T>(node,
                      UseInfo::CheckedSafeIntTruncatingWord32(FeedbackSource{}),
                      MachineRepresentation::kWord32);
        if (lower<T>()) ChangeToPureOp(node, Int32Op(node));
        return;
      }
      // => AdditiveSafeIntegerAdd/Sub
      VisitBinop<T>(node, UseInfo::CheckedSafeIntAsWord64(FeedbackSource{}),
                    MachineRepresentation::kWord64,
                    type_cache_->kAdditiveSafeInteger);
      if (lower<T>()) ChangeOp(node, AdditiveSafeIntegerOverflowOp(node));
      return;
    }
    // Default case => Float64Add/Sub
    VisitBinop<T>(node,
                  UseInfo::CheckedNumberOrOddballAsFloat64(kDistinguishZeros,
                                                           FeedbackSource()),
                  MachineRepresentation::kFloat64, Type::Number());
    if (lower<T>()) {
      ChangeToPureOp(node, Float64Op(node));
    }
  }
References AdditiveSafeIntegerOverflowOp(), BothInputsAre(), CanSpeculateAdditiveSafeInteger(), ChangeOp(), ChangeToPureOp(), v8::internal::compiler::UseInfo::CheckedNumberOrOddballAsFloat64(), v8::internal::compiler::UseInfo::CheckedSafeIntAsWord64(), v8::internal::compiler::UseInfo::CheckedSafeIntTruncatingWord32(), DeferReplacement(), Float64Op(), GetUpperBound(), InsertUnconditionalDeopt(), Int32Op(), v8::internal::Is(), v8::internal::IsNone(), v8::internal::compiler::Truncation::IsUnused(), v8::internal::compiler::Truncation::IsUsedAsWord32(), v8::internal::compiler::kAdditiveSafeInteger, v8::internal::compiler::TypeCache::kAdditiveSafeInteger, v8::internal::compiler::kDistinguishZeros, v8::internal::kFloat64, v8::internal::kWord32, v8::internal::kWord64, v8::internal::compiler::NumberOperationHintOf(), v8::internal::compiler::Node::op(), v8::internal::compiler::UseInfo::TruncatingWord32(), type_cache_, TypeOf(), and v8::internal::v8_flags.
VisitSpeculativeInt32Binop()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitSpeculativeInt32Binop (Node * node) [inline]
Definition at line 1165 of file simplified-lowering.cc.
                                              {
    DCHECK_EQ(2, node->op()->ValueInputCount());
    if (BothInputsAre(node, Type::NumberOrOddball())) {
      return VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                           MachineRepresentation::kWord32);
    }
    NumberOperationHint hint = NumberOperationHintOf(node->op());
    return VisitBinop<T>(node,
                         CheckedUseInfoAsWord32FromHint(hint, kIdentifyZeros),
                         MachineRepresentation::kWord32);
  }
References BothInputsAre(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CheckedUseInfoAsWord32FromHint(), DCHECK_EQ, v8::internal::compiler::kIdentifyZeros, v8::internal::kWord32, v8::internal::compiler::NumberOperationHintOf(), v8::internal::compiler::Node::op(), v8::internal::compiler::UseInfo::TruncatingWord32(), and v8::internal::compiler::Operator::ValueInputCount().
VisitSpeculativeNumberModulus()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitSpeculativeNumberModulus (Node * node, Truncation truncation, SimplifiedLowering * lowering) [inline]
Definition at line 1879 of file simplified-lowering.cc.
                                                                   {
    if (BothInputsAre(node, Type::Unsigned32OrMinusZeroOrNaN()) &&
        (truncation.IsUsedAsWord32() ||
         NodeProperties::GetType(node).Is(Type::Unsigned32()))) {
      // => unsigned Uint32Mod
      VisitWord32TruncatingBinop<T>(node);
      if (lower<T>()) DeferReplacement(node, lowering->Uint32Mod(node));
      return;
    }
    if (BothInputsAre(node, Type::Signed32OrMinusZeroOrNaN()) &&
        (truncation.IsUsedAsWord32() ||
         NodeProperties::GetType(node).Is(Type::Signed32()))) {
      // => signed Int32Mod
      VisitWord32TruncatingBinop<T>(node);
      if (lower<T>()) DeferReplacement(node, lowering->Int32Mod(node));
      return;
    }
    // Try to use type feedback.
    NumberOperationHint hint = NumberOperationHintOf(node->op());
    // Handle the case when no uint32 checks on inputs are necessary
    // (but an overflow check is needed on the output).
    if (BothInputsAreUnsigned32(node)) {
      if (hint == NumberOperationHint::kSignedSmall) {
        VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                      MachineRepresentation::kWord32, Type::Unsigned32());
        if (lower<T>()) ChangeToUint32OverflowOp(node);
        return;
      }
    }
    // Handle the case when no int32 checks on inputs are necessary
    // (but an overflow check is needed on the output).
    if (BothInputsAre(node, Type::Signed32())) {
      // If both the inputs the feedback are int32, use the overflow op.
      if (hint == NumberOperationHint::kSignedSmall) {
        VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                      MachineRepresentation::kWord32, Type::Signed32());
        if (lower<T>()) ChangeToInt32OverflowOp(node);
        return;
      }
    }
    if (hint == NumberOperationHint::kSignedSmall) {
      // If the result is truncated, we only need to check the inputs.
      // For the left hand side we just propagate the identify zeros
      // mode of the {truncation}; and for modulus the sign of the
      // right hand side doesn't matter anyways, so in particular there's
      // no observable difference between a 0 and a -0 then.
      UseInfo const lhs_use =
          CheckedUseInfoAsWord32FromHint(hint, truncation.identify_zeros());
      UseInfo const rhs_use =
          CheckedUseInfoAsWord32FromHint(hint, kIdentifyZeros);
      if (truncation.IsUsedAsWord32()) {
        VisitBinop<T>(node, lhs_use, rhs_use, MachineRepresentation::kWord32);
        if (lower<T>()) DeferReplacement(node, lowering->Int32Mod(node));
      } else if (BothInputsAre(node, Type::Unsigned32OrMinusZeroOrNaN())) {
        Type const restriction =
            truncation.IdentifiesZeroAndMinusZero() &&
                    TypeOf(node->InputAt(0)).Maybe(Type::MinusZero())
                ? Type::Unsigned32OrMinusZero()
                : Type::Unsigned32();
        VisitBinop<T>(node, lhs_use, rhs_use, MachineRepresentation::kWord32,
                      restriction);
        if (lower<T>()) ChangeToUint32OverflowOp(node);
      } else {
        Type const restriction =
            truncation.IdentifiesZeroAndMinusZero() &&
                    TypeOf(node->InputAt(0)).Maybe(Type::MinusZero())
                ? Type::Signed32OrMinusZero()
                : Type::Signed32();
        VisitBinop<T>(node, lhs_use, rhs_use, MachineRepresentation::kWord32,
                      restriction);
        if (lower<T>()) ChangeToInt32OverflowOp(node);
      }
      return;
    }
    if (TypeOf(node->InputAt(0)).Is(Type::Unsigned32()) &&
        TypeOf(node->InputAt(1)).Is(Type::Unsigned32()) &&
        (truncation.IsUsedAsWord32() ||
         NodeProperties::GetType(node).Is(Type::Unsigned32()))) {
      VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                    MachineRepresentation::kWord32, Type::Number());
      if (lower<T>()) DeferReplacement(node, lowering->Uint32Mod(node));
      return;
    }
    if (TypeOf(node->InputAt(0)).Is(Type::Signed32()) &&
        TypeOf(node->InputAt(1)).Is(Type::Signed32()) &&
        (truncation.IsUsedAsWord32() ||
         NodeProperties::GetType(node).Is(Type::Signed32()))) {
      VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                    MachineRepresentation::kWord32, Type::Number());
      if (lower<T>()) DeferReplacement(node, lowering->Int32Mod(node));
      return;
    }
    // default case => Float64Mod
    // For the left hand side we just propagate the identify zeros
    // mode of the {truncation}; and for modulus the sign of the
    // right hand side doesn't matter anyways, so in particular there's
    // no observable difference between a 0 and a -0 then.
    UseInfo const lhs_use = UseInfo::CheckedNumberOrOddballAsFloat64(
        truncation.identify_zeros(), FeedbackSource());
    UseInfo const rhs_use = UseInfo::CheckedNumberOrOddballAsFloat64(
        kIdentifyZeros, FeedbackSource());
    VisitBinop<T>(node, lhs_use, rhs_use, MachineRepresentation::kFloat64,
                  Type::Number());
    if (lower<T>()) ChangeToPureOp(node, Float64Op(node));
  }
References BothInputsAre(), BothInputsAreUnsigned32(), ChangeToInt32OverflowOp(), ChangeToPureOp(), ChangeToUint32OverflowOp(), v8::internal::compiler::UseInfo::CheckedNumberOrOddballAsFloat64(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CheckedUseInfoAsWord32FromHint(), DeferReplacement(), Float64Op(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::Truncation::IdentifiesZeroAndMinusZero(), v8::internal::compiler::Truncation::identify_zeros(), v8::internal::compiler::Node::InputAt(), v8::internal::compiler::SimplifiedLowering::Int32Mod(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Truncation::IsUsedAsWord32(), v8::internal::kFloat64, v8::internal::compiler::kIdentifyZeros, v8::internal::compiler::kSignedSmall, v8::internal::kWord32, v8::internal::compiler::Type::Maybe(), v8::internal::compiler::NumberOperationHintOf(), v8::internal::compiler::Node::op(), v8::internal::compiler::UseInfo::TruncatingWord32(), TypeOf(), and v8::internal::compiler::SimplifiedLowering::Uint32Mod().
VisitSpeculativeSmallIntegerAdditiveOp()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitSpeculativeSmallIntegerAdditiveOp (Node * node, Truncation truncation, SimplifiedLowering * lowering) [inline]
Definition at line 1702 of file simplified-lowering.cc.
                                                                            {
    Type left_upper = GetUpperBound(node->InputAt(0));
    Type right_upper = GetUpperBound(node->InputAt(1));
    if (left_upper.Is(type_cache_->kAdditiveSafeIntegerOrMinusZero) &&
        right_upper.Is(type_cache_->kAdditiveSafeIntegerOrMinusZero)) {
      // Only eliminate the node if its typing rule can be satisfied, namely
      // that a safe integer is produced.
      if (truncation.IsUnused()) return VisitUnused<T>(node);
      // If we know how to interpret the result or if the users only care
      // about the low 32-bits, we can truncate to Word32 do a wrapping
      // addition.
      if (GetUpperBound(node).Is(Type::Signed32()) ||
          GetUpperBound(node).Is(Type::Unsigned32()) ||
          truncation.IsUsedAsWord32()) {
        // => Int32Add/Sub
        VisitWord32TruncatingBinop<T>(node);
        if (lower<T>()) ChangeToPureOp(node, Int32Op(node));
        return;
      }
    }
    // Try to use type feedback.
    NumberOperationHint const hint = NumberOperationHint::kSignedSmall;
    DCHECK_EQ(hint, NumberOperationHintOf(node->op()));
    Type left_feedback_type = TypeOf(node->InputAt(0));
    Type right_feedback_type = TypeOf(node->InputAt(1));
    // Using Signed32 as restriction type amounts to promising there won't be
    // signed overflow. This is incompatible with relying on a Word32 truncation
    // in order to skip the overflow check. Similarly, we must not drop -0 from
    // the result type unless we deopt for -0 inputs.
    Type const restriction =
        truncation.IsUsedAsWord32()
            ? Type::Any()
            : (truncation.identify_zeros() == kIdentifyZeros)
                  ? Type::Signed32OrMinusZero()
                  : Type::Signed32();
    // Handle the case when no int32 checks on inputs are necessary (but
    // an overflow check is needed on the output). Note that we do not
    // have to do any check if at most one side can be minus zero. For
    // subtraction we need to handle the case of -0 - 0 properly, since
    // that can produce -0.
    Type left_constraint_type =
        node->opcode() == IrOpcode::kSpeculativeSmallIntegerAdd
            ? Type::Signed32OrMinusZero()
            : Type::Signed32();
    if (left_upper.Is(left_constraint_type) &&
        right_upper.Is(Type::Signed32OrMinusZero()) &&
        (left_upper.Is(Type::Signed32()) || right_upper.Is(Type::Signed32()))) {
      VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                    MachineRepresentation::kWord32, restriction);
    } else {
      // If the output's truncation is identify-zeros, we can pass it
      // along. Moreover, if the operation is addition and we know the
      // right-hand side is not minus zero, we do not have to distinguish
      // between 0 and -0.
      IdentifyZeros left_identify_zeros = truncation.identify_zeros();
      if (node->opcode() == IrOpcode::kSpeculativeSmallIntegerAdd &&
          !right_feedback_type.Maybe(Type::MinusZero())) {
        left_identify_zeros = kIdentifyZeros;
      }
      UseInfo left_use =
          CheckedUseInfoAsWord32FromHint(hint, left_identify_zeros);
      // For CheckedInt32Add and CheckedInt32Sub, we don't need to do
      // a minus zero check for the right hand side, since we already
      // know that the left hand side is a proper Signed32 value,
      // potentially guarded by a check.
      UseInfo right_use = CheckedUseInfoAsWord32FromHint(hint, kIdentifyZeros);
      VisitBinop<T>(node, left_use, right_use, MachineRepresentation::kWord32,
                    restriction);
    }
    if (lower<T>()) {
      if (truncation.IsUsedAsWord32() ||
          !CanOverflowSigned32(node->op(), left_feedback_type,
                               right_feedback_type, type_cache_,
                               graph_zone())) {
        ChangeToPureOp(node, Int32Op(node));
      } else {
        ChangeToInt32OverflowOp(node);
      }
    }
  }
References v8::internal::compiler::turboshaft::Type::Any(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CanOverflowSigned32(), ChangeToInt32OverflowOp(), ChangeToPureOp(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::CheckedUseInfoAsWord32FromHint(), DCHECK_EQ, GetUpperBound(), graph_zone(), v8::internal::compiler::Truncation::identify_zeros(), v8::internal::compiler::Node::InputAt(), Int32Op(), v8::internal::Is(), v8::internal::compiler::Type::Is(), v8::internal::compiler::Truncation::IsUnused(), v8::internal::compiler::Truncation::IsUsedAsWord32(), v8::internal::compiler::TypeCache::kAdditiveSafeIntegerOrMinusZero, v8::internal::compiler::kIdentifyZeros, v8::internal::compiler::kSignedSmall, v8::internal::kWord32, v8::internal::compiler::Type::Maybe(), v8::internal::compiler::NumberOperationHintOf(), v8::internal::compiler::Node::op(), v8::internal::compiler::Node::opcode(), v8::internal::compiler::UseInfo::TruncatingWord32(), type_cache_, and TypeOf().
VisitStateValues()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitStateValues (Node * node) [inline]
Definition at line 1423 of file simplified-lowering.cc.
                                    {
    if (propagate<T>()) {
      for (int i = 0; i < node->InputCount(); i++) {
        if (IsLargeBigInt(TypeOf(node->InputAt(i)))) {
          // BigInt64s are rematerialized in deoptimization. The other BigInts
          // must be rematerialized before deoptimization. By propagating an
          // AnyTagged use, the RepresentationChanger is going to insert the
          // necessary conversions.
          EnqueueInput<T>(node, i, UseInfo::AnyTagged());
        } else if (IsLoadFloat16ArrayElement(node->InputAt(i))) {
          // Loads from Float16Arrays are raw bits as word16s but have the
          // Number type, since not all archs have native float16
          // representation. Rematerialize them as float64s in deoptimization.
          EnqueueInput<T>(node, i, UseInfo::Float64());
        } else {
          EnqueueInput<T>(node, i, UseInfo::Any());
        }
      }
    } else if (lower<T>()) {
      Zone* zone = jsgraph_->zone();
      ZoneVector<MachineType>* types =
          zone->New<ZoneVector<MachineType>>(node->InputCount(), zone);
      for (int i = 0; i < node->InputCount(); i++) {
        Node* input = node->InputAt(i);
        MachineRepresentation input_rep = GetInfo(input)->representation();
        if (IsLargeBigInt(TypeOf(input))) {
          ConvertInput(node, i, UseInfo::AnyTagged());
        } else if (IsLoadFloat16ArrayElement(input)) {
          ConvertInput(node, i, UseInfo::Float64());
          input_rep = MachineRepresentation::kFloat64;
        }
        (*types)[i] = DeoptMachineTypeOf(input_rep, TypeOf(input));
      }
      SparseInputMask mask = SparseInputMaskOf(node->op());
      ChangeOp(node, common()->TypedStateValues(types, mask));
    }
    SetOutput<T>(node, MachineRepresentation::kTagged);
  }
References v8::internal::compiler::UseInfo::Any(), v8::internal::compiler::UseInfo::AnyTagged(), ChangeOp(), common(), ConvertInput(), DeoptMachineTypeOf(), v8::internal::compiler::UseInfo::Float64(), GetInfo(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::Node::InputAt(), v8::internal::compiler::Node::InputCount(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::IsLargeBigInt(), v8::internal::compiler::anonymous_namespace{simplified-lowering.cc}::IsLoadFloat16ArrayElement(), jsgraph_, v8::internal::kFloat64, v8::internal::kTagged, v8::internal::Zone::New(), v8::internal::compiler::Node::op(), v8::internal::compiler::RepresentationSelector::NodeInfo::representation(), v8::internal::compiler::SparseInputMaskOf(), TypeOf(), zone(), and v8::internal::compiler::MachineGraph::zone().
VisitUnop()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitUnop (Node * node, UseInfo input_use, MachineRepresentation output, Type restriction_type = Type::Any()) [inline]
Definition at line 1179 of file simplified-lowering.cc.
                                                    {
    DCHECK_EQ(1, node->op()->ValueInputCount());
    ProcessInput<T>(node, 0, input_use);
    ProcessRemainingInputs<T>(node, 1);
    SetOutput<T>(node, output, restriction_type);
  }
References DCHECK_EQ, v8::internal::compiler::Node::op(), and v8::internal::compiler::Operator::ValueInputCount().
VisitUnused()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitUnused (Node * node) [inline]
Definition at line 1117 of file simplified-lowering.cc.
                               {
    int first_effect_index = NodeProperties::FirstEffectIndex(node);
    for (int i = 0; i < first_effect_index; i++) {
      ProcessInput<T>(node, i, UseInfo::None());
    }
    ProcessRemainingInputs<T>(node, first_effect_index);
    if (lower<T>()) {
      TRACE("disconnecting unused #%d:%s\n", node->id(),
            node->op()->mnemonic());
      DisconnectFromEffectAndControl(node);
      node->NullAllInputs(); // Node is now dead.
      DeferReplacement(node, graph()->NewNode(common()->Plug()));
    }
  }
References common(), DeferReplacement(), DisconnectFromEffectAndControl(), v8::internal::compiler::NodeProperties::FirstEffectIndex(), graph(), v8::internal::compiler::Node::id(), v8::internal::compiler::Operator::mnemonic(), v8::internal::compiler::UseInfo::None(), v8::internal::compiler::Node::NullAllInputs(), v8::internal::compiler::Node::op(), and v8::internal::TRACE().
VisitWord32TruncatingBinop()
template<Phase T>
void v8::internal::compiler::RepresentationSelector::VisitWord32TruncatingBinop (Node * node) [inline]
Definition at line 1208 of file simplified-lowering.cc.
                                              {
    VisitBinop<T>(node, UseInfo::TruncatingWord32(),
                  MachineRepresentation::kWord32);
  }
References v8::internal::kWord32, and v8::internal::compiler::UseInfo::TruncatingWord32().
Weaken()
Type v8::internal::compiler::RepresentationSelector::Weaken (Node * node, Type previous_type, Type current_type) [inline]
Definition at line 605 of file simplified-lowering.cc.
                                                                 {
    // If the types have nothing to do with integers, return the types.
    Type const integer = type_cache_->kInteger;
    if (!previous_type.Maybe(integer)) {
      return current_type;
    }
    DCHECK(current_type.Maybe(integer));
    Type current_integer = Type::Intersect(current_type, integer, graph_zone());
    DCHECK(!current_integer.IsNone());
    Type previous_integer =
        Type::Intersect(previous_type, integer, graph_zone());
    DCHECK(!previous_integer.IsNone());
    // Once we start weakening a node, we should always weaken.
    if (!GetInfo(node)->weakened()) {
      // Only weaken if there is range involved; we should converge quickly
      // for all other types (the exception is a union of many constants,
      // but we currently do not increase the number of constants in unions).
      Type previous = previous_integer.GetRange();
      Type current = current_integer.GetRange();
      if (current.IsInvalid() || previous.IsInvalid()) {
        return current_type;
      }
      // Range is involved => we are weakening.
      GetInfo(node)->set_weakened();
    }
    return Type::Union(current_type,
                       op_typer_.WeakenRange(previous_integer, current_integer),
                       graph_zone());
  }
References v8::internal::DCHECK(), GetInfo(), v8::internal::compiler::Type::GetRange(), graph_zone(), v8::internal::compiler::Type::Intersect(), v8::internal::compiler::Type::IsInvalid(), v8::internal::compiler::Type::IsNone(), v8::internal::compiler::TypeCache::kInteger, v8::internal::compiler::Type::Maybe(), op_typer_, v8::internal::compiler::RepresentationSelector::NodeInfo::set_weakened(), type_cache_, v8::internal::compiler::Type::Union(), and v8::internal::compiler::OperationTyper::WeakenRange().
Referenced by UpdateFeedbackType().
WriteBarrierKindFor() [1/2]
WriteBarrierKind v8::internal::compiler::RepresentationSelector::WriteBarrierKindFor (BaseTaggedness base_taggedness, MachineRepresentation field_representation, int field_offset, Type field_type, MachineRepresentation value_representation, Node * value) [inline]
Definition at line 1643 of file simplified-lowering.cc.
                   {
    WriteBarrierKind write_barrier_kind =
        WriteBarrierKindFor(base_taggedness, field_representation, field_type,
                            value_representation, value);
    if (write_barrier_kind != kNoWriteBarrier) {
      if (base_taggedness == kTaggedBase &&
          field_offset == HeapObject::kMapOffset) {
        write_barrier_kind = kMapWriteBarrier;
      }
    }
    return write_barrier_kind;
  }
References v8::internal::HeapObject::kMapOffset, v8::internal::compiler::kMapWriteBarrier, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::value, and WriteBarrierKindFor().
WriteBarrierKindFor() [2/2]
WriteBarrierKind v8::internal::compiler::RepresentationSelector::WriteBarrierKindFor (BaseTaggedness base_taggedness, MachineRepresentation field_representation, Type field_type, MachineRepresentation value_representation, Node * value) [inline]
Definition at line 1596 of file simplified-lowering.cc.
                                                               {
    if (base_taggedness == kTaggedBase &&
        CanBeTaggedPointer(field_representation)) {
      Type value_type = NodeProperties::GetType(value);
      if (value_representation == MachineRepresentation::kTaggedSigned) {
        // Write barriers are only for stores of heap objects.
        return kNoWriteBarrier;
      }
      if (field_type.Is(Type::BooleanOrNullOrUndefined()) ||
          value_type.Is(Type::BooleanOrNullOrUndefined())) {
        // Write barriers are not necessary when storing true, false, null or
        // undefined, because these special oddballs are always in the root set.
        return kNoWriteBarrier;
      }
      if (value_type.IsHeapConstant()) {
        RootIndex root_index;
        const RootsTable& roots_table = jsgraph_->isolate()->roots_table();
        if (roots_table.IsRootHandle(value_type.AsHeapConstant()->Value(),
                                     &root_index)) {
          if (RootsTable::IsImmortalImmovable(root_index)) {
            // Write barriers are unnecessary for immortal immovable roots.
            return kNoWriteBarrier;
          }
        }
      }
      if (field_representation == MachineRepresentation::kTaggedPointer ||
          value_representation == MachineRepresentation::kTaggedPointer) {
        // Write barriers for heap objects are cheaper.
        return kPointerWriteBarrier;
      }
      NumberMatcher m(value);
      if (m.HasResolvedValue()) {
        if (IsSmiDouble(m.ResolvedValue())) {
          // Storing a smi doesn't need a write barrier.
          return kNoWriteBarrier;
        }
        // The NumberConstant will be represented as HeapNumber.
        return kPointerWriteBarrier;
      }
      return kFullWriteBarrier;
    }
    return kNoWriteBarrier;
  }
References v8::internal::CanBeTaggedPointer(), v8::internal::compiler::NodeProperties::GetType(), v8::internal::compiler::ValueMatcher< T, kOpcode >::HasResolvedValue(), v8::internal::compiler::Type::Is(), v8::internal::RootsTable::IsImmortalImmovable(), v8::internal::compiler::JSGraph::isolate(), v8::internal::RootsTable::IsRootHandle(), v8::internal::IsSmiDouble(), jsgraph_, v8::internal::compiler::kFullWriteBarrier, v8::internal::compiler::kNoWriteBarrier, v8::internal::compiler::kPointerWriteBarrier, v8::internal::compiler::kTaggedBase, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::compiler::ValueMatcher< T, kOpcode >::ResolvedValue(), v8::internal::Isolate::roots_table(), v8::internal::value, and v8::internal::wasm::value_type().
Referenced by VisitNode(), and WriteBarrierKindFor().
zone()
Zone* v8::internal::compiler::RepresentationSelector::zone () [inline], [private]
Definition at line 5112 of file simplified-lowering.cc.
{ return zone_; }
References zone_.
Referenced by GetOutputInfoForPhi(), MarkAsPossibleRevisit(), VisitFrameState(), VisitNode(), VisitObjectState(), and VisitStateValues().
Member Data Documentation
broker_
JSHeapBroker* v8::internal::compiler::RepresentationSelector::broker_ [private]
Definition at line 5073 of file simplified-lowering.cc.
Referenced by RunVerifyPhase().
changer_
RepresentationChanger* v8::internal::compiler::RepresentationSelector::changer_ [private]
Definition at line 5084 of file simplified-lowering.cc.
Referenced by AdditiveSafeIntegerOverflowOp(), BigIntOp(), ConvertInput(), Float64Op(), Int32Op(), Int32OverflowOp(), Int64Op(), Int64OverflowOp(), Uint32Op(), Uint32OverflowOp(), and VisitNode().
count_
size_t v8::internal::compiler::RepresentationSelector::count_ [private]
Definition at line 5077 of file simplified-lowering.cc.
Referenced by GenerateTraversal(), and GetInfo().
info_
ZoneVector<NodeInfo> v8::internal::compiler::RepresentationSelector::info_ [private]
Definition at line 5078 of file simplified-lowering.cc.
Referenced by GenerateTraversal(), GetInfo(), and ResetNodeInfoState().
jsgraph_
JSGraph* v8::internal::compiler::RepresentationSelector::jsgraph_ [private]
Definition at line 5072 of file simplified-lowering.cc.
Referenced by ChangeUnaryToPureBinaryOp(), common(), graph(), graph_zone(), MaskShiftOperand(), simplified(), TryOptimizeBigInt64Shift(), VisitCheckBounds(), VisitFrameState(), VisitNode(), VisitObjectState(), VisitStateValues(), and WriteBarrierKindFor().
kInitialArgumentsCount
constexpr int v8::internal::compiler::RepresentationSelector::kInitialArgumentsCount = 10 [static], [constexpr]
Definition at line 2153 of file simplified-lowering.cc.
linkage_
Linkage* const v8::internal::compiler::RepresentationSelector::linkage_ [private]
Definition at line 5104 of file simplified-lowering.cc.
Referenced by linkage().
might_need_revisit_
ZoneMap<Node*, ZoneVector<Node*> > v8::internal::compiler::RepresentationSelector::might_need_revisit_ [private]
Definition at line 5076 of file simplified-lowering.cc.
Referenced by MarkAsPossibleRevisit(), and RunRetypePhase().
node_origins_
NodeOriginTable* v8::internal::compiler::RepresentationSelector::node_origins_ [private]
Definition at line 5098 of file simplified-lowering.cc.
Referenced by RunLowerPhase(), and RunVerifyPhase().
observe_node_manager_
ObserveNodeManager* const v8::internal::compiler::RepresentationSelector::observe_node_manager_ [private]
Definition at line 5105 of file simplified-lowering.cc.
Referenced by ChangeOp(), and NotifyNodeReplaced().
op_typer_
OperationTyper v8::internal::compiler::RepresentationSelector::op_typer_ [private]
Definition at line 5100 of file simplified-lowering.cc.
Referenced by RunVerifyPhase(), TypePhi(), TypeSelect(), UpdateFeedbackType(), and Weaken().
replacements_
NodeVector v8::internal::compiler::RepresentationSelector::replacements_ [private]
Definition at line 5083 of file simplified-lowering.cc.
Referenced by DeferReplacement(), and RunLowerPhase().
revisit_queue_
ZoneQueue<Node*> v8::internal::compiler::RepresentationSelector::revisit_queue_ [private]
Definition at line 5085 of file simplified-lowering.cc.
Referenced by EnqueueInput(), PushNodeToRevisitIfVisited(), RunPropagatePhase(), and RunRetypePhase().
singleton_false_
Type v8::internal::compiler::RepresentationSelector::singleton_false_ [private]
Definition at line 5102 of file simplified-lowering.cc.
Referenced by false_type(), and RepresentationSelector().
singleton_true_
Type v8::internal::compiler::RepresentationSelector::singleton_true_ [private]
Definition at line 5101 of file simplified-lowering.cc.
Referenced by RepresentationSelector(), and true_type().
source_positions_
SourcePositionTable* v8::internal::compiler::RepresentationSelector::source_positions_ [private]
Definition at line 5097 of file simplified-lowering.cc.
Referenced by RunLowerPhase(), and RunVerifyPhase().
tick_counter_
TickCounter* const v8::internal::compiler::RepresentationSelector::tick_counter_ [private]
Definition at line 5103 of file simplified-lowering.cc.
Referenced by VisitNode().
traversal_nodes_
NodeVector v8::internal::compiler::RepresentationSelector::traversal_nodes_ [private]
Definition at line 5091 of file simplified-lowering.cc.
Referenced by GenerateTraversal(), RunLowerPhase(), RunPropagatePhase(), RunRetypePhase(), and RunVerifyPhase().
type_cache_
TypeCache const* v8::internal::compiler::RepresentationSelector::type_cache_ [private]
Definition at line 5099 of file simplified-lowering.cc.
Referenced by CanSpeculateAdditiveSafeInteger(), MaskShiftOperand(), VisitCheckBounds(), VisitNode(), VisitSpeculativeAdditiveOp(), VisitSpeculativeSmallIntegerAdditiveOp(), and Weaken().
verifier_
SimplifiedLoweringVerifier* v8::internal::compiler::RepresentationSelector::verifier_ [private]
Definition at line 5106 of file simplified-lowering.cc.
Referenced by InsertSemanticsHintForVerifier(), InsertTypeOverrideForVerifier(), RunVerifyPhase(), verification_enabled(), and VisitNode().
zone_
Zone* v8::internal::compiler::RepresentationSelector::zone_ [private]
Definition at line 5074 of file simplified-lowering.cc.
Referenced by GenerateTraversal(), SetOutput(), and zone().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/simplified-lowering.cc