v8::internal::WasmDescriptorOptions Class Reference
#include <wasm-objects.h>
Static Public Member Functions
static DirectHandle< WasmDescriptorOptions > New (Isolate *isolate, DirectHandle< Object > prototype)
Detailed Description
Definition at line 1510 of file wasm-objects.h.
Member Function Documentation
New()
DirectHandle< WasmDescriptorOptions > v8::internal::WasmDescriptorOptions::New (Isolate * isolate, DirectHandle< Object > prototype) [static]
Definition at line 2400 of file wasm-objects.cc.
                                                      {
  DirectHandle<JSFunction> ctor(
      isolate->native_context()->wasm_descriptor_options_constructor(),
      isolate);
  DirectHandle<WasmDescriptorOptions> desc =
      Cast<WasmDescriptorOptions>(isolate->factory()->NewJSObject(ctor));
  desc->set_prototype(*prototype);
  return desc;
}
References v8::internal::Isolate::factory(), v8::internal::Isolate::native_context(), v8::internal::Factory::NewJSObject(), and v8::internal::prototype.
Referenced by v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl(), and v8::anonymous_namespace{wasm-js.cc}::WebAssemblyDescriptorOptionsImpl().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc