v8::internal::PointersUpdatingVisitor Class Reference
Public Member Functions
PointersUpdatingVisitor (Heap *heap)
void VisitPointer (Tagged< HeapObject > host, ObjectSlot p) override
void VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot p) override
void VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) override
void VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) final
void VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) override
void VisitRootPointer (Root root, const char *description, FullObjectSlot p) override
void VisitRootPointers (Root root, const char *description, FullObjectSlot start, FullObjectSlot end) override
void VisitRootPointers (Root root, const char *description, OffHeapObjectSlot start, OffHeapObjectSlot end) override
void VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo *rinfo) override
void VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo *rinfo) override
Static Private Member Functions
static void UpdateRootSlotInternal (PtrComprCageBase cage_base, FullObjectSlot slot)
static void UpdateRootSlotInternal (PtrComprCageBase cage_base, OffHeapObjectSlot slot)
static void UpdateStrongMaybeObjectSlotInternal (PtrComprCageBase cage_base, MaybeObjectSlot slot)
static void UpdateStrongSlotInternal (PtrComprCageBase cage_base, ObjectSlot slot)
static void UpdateSlotInternal (PtrComprCageBase cage_base, MaybeObjectSlot slot)
Private Attributes
IsolateForSandbox isolate_
Additional Inherited Members
Detailed Description
Definition at line 4312 of file mark-compact.cc.
Constructor & Destructor Documentation
PointersUpdatingVisitor()
v8::internal::PointersUpdatingVisitor::PointersUpdatingVisitor (Heap * heap) [inline], [explicit]
Definition at line 4315 of file mark-compact.cc.
      : ObjectVisitorWithCageBases(heap), isolate_(heap->isolate()) {}
Member Function Documentation
UpdateRootSlotInternal() [1/2]
static void v8::internal::PointersUpdatingVisitor::UpdateRootSlotInternal (PtrComprCageBase cage_base, FullObjectSlot slot) [inline], [static], [private]
Definition at line 4379 of file mark-compact.cc.
                                                                 {
    UpdateStrongSlot(cage_base, slot);
  }
References v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongSlot().
UpdateRootSlotInternal() [2/2]
static void v8::internal::PointersUpdatingVisitor::UpdateRootSlotInternal (PtrComprCageBase cage_base, OffHeapObjectSlot slot) [inline], [static], [private]
Definition at line 4384 of file mark-compact.cc.
                                                                    {
    UpdateStrongSlot(cage_base, slot);
  }
References v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongSlot().
UpdateSlotInternal()
static void v8::internal::PointersUpdatingVisitor::UpdateSlotInternal (PtrComprCageBase cage_base, MaybeObjectSlot slot) [inline], [static], [private]
Definition at line 4399 of file mark-compact.cc.
                                                              {
    UpdateSlot(cage_base, slot);
  }
References v8::internal::anonymous_namespace{mark-compact.cc}::UpdateSlot().
UpdateStrongMaybeObjectSlotInternal()
static void v8::internal::PointersUpdatingVisitor::UpdateStrongMaybeObjectSlotInternal (PtrComprCageBase cage_base, MaybeObjectSlot slot) [inline], [static], [private]
Definition at line 4389 of file mark-compact.cc.
                                                        {
    UpdateStrongSlot(cage_base, slot);
  }
References v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongSlot().
UpdateStrongSlotInternal()
static void v8::internal::PointersUpdatingVisitor::UpdateStrongSlotInternal (PtrComprCageBase cage_base, ObjectSlot slot) [inline], [static], [private]
Definition at line 4394 of file mark-compact.cc.
                                                               {
    UpdateStrongSlot(cage_base, slot);
  }
References v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongSlot().
VisitCodeTarget()
void v8::internal::PointersUpdatingVisitor::VisitCodeTarget (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 4366 of file mark-compact.cc.
                                                  {
    // This visitor nevers visits code objects.
    UNREACHABLE();
  }
References UNREACHABLE.
VisitEmbeddedPointer()
void v8::internal::PointersUpdatingVisitor::VisitEmbeddedPointer (Tagged< InstructionStream > host, RelocInfo * rinfo) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 4372 of file mark-compact.cc.
                                                       {
    // This visitor nevers visits code objects.
    UNREACHABLE();
  }
References UNREACHABLE.
VisitInstructionStreamPointer()
void v8::internal::PointersUpdatingVisitor::VisitInstructionStreamPointer (Tagged< Code > host, InstructionStreamSlot slot) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 4340 of file mark-compact.cc.
                                                                          {
    UpdateStrongCodeSlot(isolate_, cage_base(), code_cage_base(), slot);
  }
References v8::internal::anonymous_namespace{mark-compact.cc}::UpdateStrongCodeSlot().
VisitPointer() [1/2]
void v8::internal::PointersUpdatingVisitor::VisitPointer (Tagged< HeapObject > host, MaybeObjectSlot p) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 4322 of file mark-compact.cc.
                                                                         {
    UpdateSlotInternal(cage_base(), p);
  }
VisitPointer() [2/2]
void v8::internal::PointersUpdatingVisitor::VisitPointer (Tagged< HeapObject > host, ObjectSlot p) [inline], [override], [virtual]
Reimplemented from v8::internal::ObjectVisitor.
Definition at line 4318 of file mark-compact.cc.
                                                                    {
    UpdateStrongSlotInternal(cage_base(), p);
  }
VisitPointers() [1/2]
void v8::internal::PointersUpdatingVisitor::VisitPointers (Tagged< HeapObject > host, MaybeObjectSlot start, MaybeObjectSlot end) [inline], [final], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 4333 of file mark-compact.cc.
                                                {
    for (MaybeObjectSlot p = start; p < end; ++p) {
      UpdateSlotInternal(cage_base(), p);
    }
  }
References v8::internal::compiler::end().
VisitPointers() [2/2]
void v8::internal::PointersUpdatingVisitor::VisitPointers (Tagged< HeapObject > host, ObjectSlot start, ObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::ObjectVisitor.
Definition at line 4326 of file mark-compact.cc.
                                              {
    for (ObjectSlot p = start; p < end; ++p) {
      UpdateStrongSlotInternal(cage_base(), p);
    }
  }
References v8::internal::compiler::end().
VisitRootPointer()
void v8::internal::PointersUpdatingVisitor::VisitRootPointer (Root root, const char * description, FullObjectSlot p) [inline], [override], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 4345 of file mark-compact.cc.
                                                   {
    DCHECK(!MapWord::IsPacked(p.Relaxed_Load().ptr()));
    UpdateRootSlotInternal(cage_base(), p);
  }
References DCHECK, v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::FullObjectSlot::Relaxed_Load().
VisitRootPointers() [1/2]
void v8::internal::PointersUpdatingVisitor::VisitRootPointers (Root root, const char * description, FullObjectSlot start, FullObjectSlot end) [inline], [override], [virtual]
Implements v8::internal::RootVisitor.
Definition at line 4351 of file mark-compact.cc.
                                                                            {
    for (FullObjectSlot p = start; p < end; ++p) {
      UpdateRootSlotInternal(cage_base(), p);
    }
  }
References v8::internal::compiler::end().
VisitRootPointers() [2/2]
void v8::internal::PointersUpdatingVisitor::VisitRootPointers (Root root, const char * description, OffHeapObjectSlot start, OffHeapObjectSlot end) [inline], [override], [virtual]
Reimplemented from v8::internal::RootVisitor.
Definition at line 4358 of file mark-compact.cc.
                                                         {
    for (OffHeapObjectSlot p = start; p < end; ++p) {
      UpdateRootSlotInternal(cage_base(), p);
    }
  }
References v8::internal::compiler::end().
Member Data Documentation
isolate_
IsolateForSandbox v8::internal::PointersUpdatingVisitor::isolate_ [private]
Definition at line 4404 of file mark-compact.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/mark-compact.cc