v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::MovableLabel Class Reference
Public Member Functions
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (MovableLabel)
MovableLabel (Zone *)
Label * get ()
Private Attributes
Label label_
Detailed Description
Definition at line 151 of file liftoff-compiler.cc.
Constructor & Destructor Documentation
MovableLabel()
v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::MovableLabel::MovableLabel (Zone *) [inline], [explicit]
Definition at line 154 of file liftoff-compiler.cc.
{}
Member Function Documentation
get()
Label* v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::MovableLabel::get () [inline]
Definition at line 156 of file liftoff-compiler.cc.
{ return &label_; }
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CatchException(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Else(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FallThruTo(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::FinishOneArmedIf(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateBrCase(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::GenerateOutOfLineCode(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::If(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Loop(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::PopControl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StackCheck(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::TierupCheck(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::UnuseLabels().
MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR()
v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::MovableLabel::MOVE_ONLY_NO_DEFAULT_CONSTRUCTOR (MovableLabel)
Member Data Documentation
label_
Label v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::MovableLabel::label_ [private]
Definition at line 159 of file liftoff-compiler.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/baseline/liftoff-compiler.cc