v8::internal::interpreter::Bytecodes Class Reference
#include <bytecodes.h>
Static Public Member Functions
static const char * ToString (Bytecode bytecode)
static std::string ToString (Bytecode bytecode, OperandScale operand_scale, const char *separator=`.`)
static uint8_t ToByte (Bytecode bytecode)
static Bytecode FromByte (uint8_t value)
static Bytecode OperandScaleToPrefixBytecode (OperandScale operand_scale)
static bool OperandScaleRequiresPrefixBytecode (OperandScale operand_scale)
static OperandScale PrefixBytecodeToOperandScale (Bytecode bytecode)
static ImplicitRegisterUse GetImplicitRegisterUse (Bytecode bytecode)
static bool ReadsAccumulator (Bytecode bytecode)
static bool WritesAccumulator (Bytecode bytecode)
static bool ClobbersAccumulator (Bytecode bytecode)
static bool WritesOrClobbersAccumulator (Bytecode bytecode)
static bool WritesImplicitRegister (Bytecode bytecode)
static constexpr bool IsAccumulatorLoadWithoutEffects (Bytecode bytecode)
static constexpr bool IsCompareWithoutEffects (Bytecode bytecode)
static constexpr bool IsShortStar (Bytecode bytecode)
static constexpr bool IsAnyStar (Bytecode bytecode)
static constexpr bool IsRegisterLoadWithoutEffects (Bytecode bytecode)
static constexpr bool IsConditionalJumpImmediate (Bytecode bytecode)
static constexpr bool IsConditionalJumpConstant (Bytecode bytecode)
static constexpr bool IsConditionalJump (Bytecode bytecode)
static constexpr bool IsUnconditionalJump (Bytecode bytecode)
static constexpr bool IsJumpImmediate (Bytecode bytecode)
static constexpr bool IsJumpConstant (Bytecode bytecode)
static constexpr bool IsJumpIfToBoolean (Bytecode bytecode)
static constexpr bool IsJump (Bytecode bytecode)
static constexpr bool IsForwardJump (Bytecode bytecode)
static constexpr bool IsJumpWithoutEffects (Bytecode bytecode)
static constexpr bool IsSwitch (Bytecode bytecode)
static constexpr bool IsWithoutExternalSideEffects (Bytecode bytecode)
static constexpr bool IsLdarOrStar (Bytecode bytecode)
static constexpr bool IsCallOrConstruct (Bytecode bytecode)
static constexpr bool IsCallRuntime (Bytecode bytecode)
static constexpr bool IsPrefixScalingBytecode (Bytecode bytecode)
static constexpr bool Returns (Bytecode bytecode)
static constexpr bool UnconditionallyThrows (Bytecode bytecode)
static int NumberOfOperands (Bytecode bytecode)
static OperandType GetOperandType (Bytecode bytecode, int i)
static const OperandType * GetOperandTypes (Bytecode bytecode)
static bool OperandIsScalableSignedByte (Bytecode bytecode, int operand_index)
static bool OperandIsScalableUnsignedByte (Bytecode bytecode, int operand_index)
static bool OperandIsScalable (Bytecode bytecode, int operand_index)
static bool IsBytecodeWithScalableOperands (Bytecode bytecode)
static OperandSize GetOperandSize (Bytecode bytecode, int i, OperandScale operand_scale)
static const OperandSize * GetOperandSizes (Bytecode bytecode, OperandScale operand_scale)
static int GetOperandOffset (Bytecode bytecode, int i, OperandScale operand_scale)
static int Size (Bytecode bytecode, OperandScale operand_scale)
static Bytecode GetDebugBreak (Bytecode bytecode)
static bool MakesCallAlongCriticalPath (Bytecode bytecode)
static ConvertReceiverMode GetReceiverMode (Bytecode bytecode)
static bool IsDebugBreak (Bytecode bytecode)
static bool IsRegisterOperandType (OperandType operand_type)
static bool IsRegisterInputOperandType (OperandType operand_type)
static bool IsRegisterOutputOperandType (OperandType operand_type)
static bool IsRegisterListOperandType (OperandType operand_type)
static bool IsStarLookahead (Bytecode bytecode, OperandScale operand_scale)
static int GetNumberOfRegistersRepresentedBy (OperandType operand_type)
static OperandSize SizeOfOperand (OperandType operand_type, OperandScale operand_scale)
static bool IsRuntimeIdOperandType (OperandType operand_type)
static bool IsUnsignedOperandType (OperandType operand_type)
static bool BytecodeHasHandler (Bytecode bytecode, OperandScale operand_scale)
static OperandScale ScaleForSignedOperand (int32_t value)
static OperandScale ScaleForUnsignedOperand (uint32_t value)
static OperandSize SizeForUnsignedOperand (uint32_t value)
static Address bytecode_size_table_address ()
Static Public Attributes
static const int kMaxOperands = 5
static const int kBytecodeCount = static_cast<int>(Bytecode::kLast) + 1
static const int kShortStarCount
Static Private Attributes
static const OperandType *const kOperandTypes []
static const OperandTypeInfo *const kOperandTypeInfos []
static const int kOperandCount []
static const int kNumberOfRegisterOperands []
static const ImplicitRegisterUse kImplicitRegisterUse []
static const bool kIsScalable []
static const uint8_t kBytecodeSizes [3][kBytecodeCount]
static const OperandSize *const kOperandSizes [3][kBytecodeCount]
static const int *const kOperandOffsets [3][kBytecodeCount]
static OperandSize const kOperandKindSizes [3][BytecodeOperands::kOperandTypeCount]
Detailed Description
Definition at line 608 of file bytecodes.h.
Member Function Documentation
bytecode_size_table_address()
static Address v8::internal::interpreter::Bytecodes::bytecode_size_table_address () [inline], [static]
Definition at line 1117 of file bytecodes.h.
                                               {
    return reinterpret_cast<Address>(
        const_cast<uint8_t*>(&kBytecodeSizes[0][0]));
  }
BytecodeHasHandler()
bool v8::internal::interpreter::Bytecodes::BytecodeHasHandler (Bytecode bytecode, OperandScale operand_scale) [static]
Definition at line 333 of file bytecodes.cc.
                                                               {
  return (operand_scale == OperandScale::kSingle &&
          (!IsShortStar(bytecode) || bytecode == Bytecode::kStar0)) ||
         Bytecodes::IsBytecodeWithScalableOperands(bytecode);
}
References IsBytecodeWithScalableOperands(), and IsShortStar().
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::CompileBytecodeHandler(), v8::internal::interpreter::Interpreter::Initialize(), and v8::internal::interpreter::WriteBytecode().
ClobbersAccumulator()
static bool v8::internal::interpreter::Bytecodes::ClobbersAccumulator (Bytecode bytecode) [inline], [static]
Definition at line 709 of file bytecodes.h.
                                                     {
    return BytecodeOperands::ClobbersAccumulator(
        GetImplicitRegisterUse(bytecode));
  }
References v8::internal::interpreter::BytecodeOperands::ClobbersAccumulator().
Referenced by v8::internal::interpreter::InterpreterAssembler::ClobberAccumulator(), and v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForEagerCall().
FromByte()
static Bytecode v8::internal::interpreter::Bytecodes::FromByte (uint8_t value) [inline], [static]
Definition at line 635 of file bytecodes.h.
                                          {
    Bytecode bytecode = static_cast<Bytecode>(value);
    DCHECK_LE(bytecode, Bytecode::kLast);
    return bytecode;
  }
References DCHECK_LE, v8::internal::interpreter::kLast, and v8::internal::value.
Referenced by v8::internal::interpreter::BytecodeArrayIterator::ApplyDebugBreak(), v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeDecoder::Decode(), v8::internal::interpreter::Interpreter::ForEachBytecode(), v8::internal::BreakIterator::GetDebugBreakType(), v8::internal::interpreter::Interpreter::GetDispatchCountersObject(), v8::internal::Debug::IsBreakOnDebuggerStatement(), v8::internal::interpreter::BytecodeArrayIterator::next_bytecode(), v8::internal::interpreter::BytecodeArrayWriter::PatchJump(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith16BitOperand(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith32BitOperand(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith8BitOperand(), and v8::internal::interpreter::BytecodeArrayIterator::UpdateOperandScale().
GetDebugBreak()
Bytecode v8::internal::interpreter::Bytecodes::GetDebugBreak (Bytecode bytecode) [static]
Definition at line 148 of file bytecodes.cc.
                                                   {
  DCHECK(!IsDebugBreak(bytecode));
  if (bytecode == Bytecode::kWide) {
    return Bytecode::kDebugBreakWide;
  }
  if (bytecode == Bytecode::kExtraWide) {
    return Bytecode::kDebugBreakExtraWide;
  }
  int bytecode_size = Size(bytecode, OperandScale::kSingle);
#define RETURN_IF_DEBUG_BREAK_SIZE_MATCHES(Name) \
  if (bytecode_size == Size(Bytecode::k##Name, OperandScale::kSingle)) { \
    return Bytecode::k##Name; \
  }
  DEBUG_BREAK_PLAIN_BYTECODE_LIST(RETURN_IF_DEBUG_BREAK_SIZE_MATCHES)
#undef RETURN_IF_DEBUG_BREAK_SIZE_MATCHES
  UNREACHABLE();
}
References v8::internal::DCHECK(), DEBUG_BREAK_PLAIN_BYTECODE_LIST, IsDebugBreak(), RETURN_IF_DEBUG_BREAK_SIZE_MATCHES, Size(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeArrayIterator::ApplyDebugBreak().
GetImplicitRegisterUse()
static ImplicitRegisterUse v8::internal::interpreter::Bytecodes::GetImplicitRegisterUse (Bytecode bytecode) [inline], [static]
Definition at line 692 of file bytecodes.h.
                                                                       {
    DCHECK_LE(bytecode, Bytecode::kLast);
    return kImplicitRegisterUse[static_cast<size_t>(bytecode)];
  }
References DCHECK_LE, and v8::internal::interpreter::kLast.
Referenced by v8::internal::interpreter::InterpreterAssembler::InlineShortStar(), v8::internal::interpreter::BytecodeArrayWriter::MaybeElideLastBytecode(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::~BytecodeHandlerReducer(), and v8::internal::interpreter::InterpreterAssembler::~InterpreterAssembler().
GetNumberOfRegistersRepresentedBy()
static int v8::internal::interpreter::Bytecodes::GetNumberOfRegistersRepresentedBy (OperandType operand_type) [inline], [static]
Definition at line 1040 of file bytecodes.h.
                                                                         {
    switch (operand_type) {
      case OperandType::kReg:
      case OperandType::kRegOut:
      case OperandType::kRegInOut:
        return 1;
      case OperandType::kRegPair:
      case OperandType::kRegOutPair:
        return 2;
      case OperandType::kRegOutTriple:
        return 3;
      case OperandType::kRegList:
      case OperandType::kRegOutList:
        UNREACHABLE();
      default:
        return 0;
    }
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperandRange().
GetOperandOffset()
static int v8::internal::interpreter::Bytecodes::GetOperandOffset (Bytecode bytecode, int i, OperandScale operand_scale) [inline], [static]
Definition at line 962 of file bytecodes.h.
                                                          {
    DCHECK_LE(bytecode, Bytecode::kLast);
    DCHECK_GE(operand_scale, OperandScale::kSingle);
    DCHECK_LE(operand_scale, OperandScale::kLast);
    static_assert(static_cast<int>(OperandScale::kQuadruple) == 4 &&
                  OperandScale::kLast == OperandScale::kQuadruple);
    int scale_index = static_cast<int>(operand_scale) >> 1;
    return kOperandOffsets[scale_index][static_cast<size_t>(bytecode)][i];
  }
References DCHECK_GE, DCHECK_LE, and v8::internal::interpreter::kLast.
Referenced by v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedQuad(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedShort(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedQuad(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedShort(), v8::internal::interpreter::BytecodeDecoder::Decode(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetSignedOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetUnsignedOperand(), v8::internal::interpreter::InterpreterAssembler::OperandOffset(), and v8::internal::interpreter::BytecodeHandlerReducer< Next >::OperandOffset().
GetOperandSize()
static OperandSize v8::internal::interpreter::Bytecodes::GetOperandSize (Bytecode bytecode, int i, OperandScale operand_scale) [inline], [static]
Definition at line 942 of file bytecodes.h.
                                                                {
    CHECK_LT(i, NumberOfOperands(bytecode));
    return GetOperandSizes(bytecode, operand_scale)[i];
  }
References CHECK_LT, and v8::internal::anonymous_namespace{json-stringifier.cc}::i.
Referenced by v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeOperand(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandConstantPoolIdx(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandCount(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandFlag16(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandFlag8(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandIdxInt32(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeOperandIdxInt32(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandImm(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandIntrinsicId(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandNativeContextIndex(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReg(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandRuntimeId(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedByte(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedQuad(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedShort(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUImm(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedByte(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedQuad(), and v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedShort().
GetOperandSizes()
static const OperandSize* v8::internal::interpreter::Bytecodes::GetOperandSizes (Bytecode bytecode, OperandScale operand_scale) [inline], [static]
Definition at line 949 of file bytecodes.h.
                                                                        {
    DCHECK_LE(bytecode, Bytecode::kLast);
    DCHECK_GE(operand_scale, OperandScale::kSingle);
    DCHECK_LE(operand_scale, OperandScale::kLast);
    static_assert(static_cast<int>(OperandScale::kQuadruple) == 4 &&
                  OperandScale::kLast == OperandScale::kQuadruple);
    int scale_index = static_cast<int>(operand_scale) >> 1;
    return kOperandSizes[scale_index][static_cast<size_t>(bytecode)];
  }
References DCHECK_GE, DCHECK_LE, and v8::internal::interpreter::kLast.
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitBytecode().
GetOperandType()
static OperandType v8::internal::interpreter::Bytecodes::GetOperandType (Bytecode bytecode, int i) [inline], [static]
Definition at line 905 of file bytecodes.h.
                                                              {
    DCHECK_LE(bytecode, Bytecode::kLast);
    DCHECK_LT(i, NumberOfOperands(bytecode));
    DCHECK_GE(i, 0);
    return GetOperandTypes(bytecode)[i];
  }
References DCHECK_GE, DCHECK_LE, DCHECK_LT, v8::internal::anonymous_namespace{json-stringifier.cc}::i, and v8::internal::interpreter::kLast.
Referenced by v8::internal::interpreter::InterpreterAssembler::BytecodeOperandConstantPoolIdx(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandCount(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandFlag16(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandFlag8(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandIdxInt32(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeOperandIdxInt32(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandImm(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandIntrinsicId(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandNativeContextIndex(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReg(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandRuntimeId(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUImm(), v8::internal::interpreter::InterpreterAssembler::BytecodeSignedOperand(), v8::internal::interpreter::InterpreterAssembler::BytecodeUnsignedOperand(), v8::internal::interpreter::BytecodeNode::Create(), v8::internal::interpreter::BytecodeDecoder::Decode(), v8::internal::interpreter::BytecodeArrayIterator::GetFlag16Operand(), v8::internal::interpreter::BytecodeArrayIterator::GetFlag8Operand(), v8::internal::interpreter::BytecodeArrayIterator::GetImmediateOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetIndexOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetIntrinsicIdOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetNativeContextIndexOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterCountOperand(), v8::internal::interpreter::InterpreterAssembler::GetRegisterListAtOperandIndex(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetRuntimeIdOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetSignedOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetUnsignedImmediateOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetUnsignedOperand(), v8::internal::interpreter::InterpreterAssembler::LoadRegisterPairAtOperandIndex(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith16BitOperand(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith8BitOperand(), v8::internal::interpreter::InterpreterAssembler::StoreRegisterPairAtOperandIndex(), and v8::internal::interpreter::InterpreterAssembler::StoreRegisterTripleAtOperandIndex().
GetOperandTypes()
static const OperandType* v8::internal::interpreter::Bytecodes::GetOperandTypes (Bytecode bytecode) [inline], [static]
Definition at line 914 of file bytecodes.h.
                                                               {
    DCHECK_LE(bytecode, Bytecode::kLast);
    return kOperandTypes[static_cast<size_t>(bytecode)];
  }
References DCHECK_LE, and v8::internal::interpreter::kLast.
Referenced by v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperandRange(), v8::internal::interpreter::BytecodeArrayIterator::GetStarTargetRegister(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateAssignments().
GetReceiverMode()
static ConvertReceiverMode v8::internal::interpreter::Bytecodes::GetReceiverMode (Bytecode bytecode) [inline], [static]
Definition at line 991 of file bytecodes.h.
                                                                {
    DCHECK(IsCallOrConstruct(bytecode) ||
           bytecode == Bytecode::kInvokeIntrinsic);
    switch (bytecode) {
      case Bytecode::kCallProperty:
      case Bytecode::kCallProperty0:
      case Bytecode::kCallProperty1:
      case Bytecode::kCallProperty2:
        return ConvertReceiverMode::kNotNullOrUndefined;
      case Bytecode::kCallUndefinedReceiver:
      case Bytecode::kCallUndefinedReceiver0:
      case Bytecode::kCallUndefinedReceiver1:
      case Bytecode::kCallUndefinedReceiver2:
      case Bytecode::kCallJSRuntime:
        return ConvertReceiverMode::kNullOrUndefined;
      case Bytecode::kCallAnyReceiver:
      case Bytecode::kConstruct:
      case Bytecode::kCallWithSpread:
      case Bytecode::kConstructWithSpread:
      case Bytecode::kInvokeIntrinsic:
        return ConvertReceiverMode::kAny;
      default:
        UNREACHABLE();
    }
  }
References v8::internal::DCHECK(), v8::internal::kAny, v8::internal::kNotNullOrUndefined, v8::internal::kNullOrUndefined, and v8::internal::UNREACHABLE().
Referenced by v8::internal::compiler::BytecodeGraphBuilder::BuildCall(), v8::internal::compiler::BytecodeGraphBuilder::BuildCallVarArgs(), v8::internal::interpreter::InterpreterAssembler::CallJSAndDispatch(), and v8::internal::interpreter::InterpreterAssembler::CallJSWithSpreadAndDispatch().
IsAccumulatorLoadWithoutEffects()
static constexpr bool v8::internal::interpreter::Bytecodes::IsAccumulatorLoadWithoutEffects (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 729 of file bytecodes.h.
                                                                           {
    static_assert(Bytecode::kLdar < Bytecode::kLdaImmutableCurrentContextSlot);
    return bytecode >= Bytecode::kLdar &&
           bytecode <= Bytecode::kLdaImmutableCurrentContextSlot;
  }
Referenced by v8::internal::interpreter::BytecodeArrayWriter::MaybeElideLastBytecode().
IsAnyStar()
static constexpr bool v8::internal::interpreter::Bytecodes::IsAnyStar (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 748 of file bytecodes.h.
                                                     {
    return bytecode == Bytecode::kStar || IsShortStar(bytecode);
  }
Referenced by v8::internal::interpreter::BytecodeArrayIterator::GetStarTargetRegister().
IsBytecodeWithScalableOperands()
bool v8::internal::interpreter::Bytecodes::IsBytecodeWithScalableOperands (Bytecode bytecode) [static]
Definition at line 313 of file bytecodes.cc.
                                                                {
  for (int i = 0; i < NumberOfOperands(bytecode); i++) {
    if (OperandIsScalable(bytecode, i)) return true;
  }
  return false;
}
References NumberOfOperands(), and OperandIsScalable().
Referenced by BytecodeHasHandler().
IsCallOrConstruct()
static constexpr bool v8::internal::interpreter::Bytecodes::IsCallOrConstruct (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 851 of file bytecodes.h.
                                                             {
    return bytecode == Bytecode::kCallAnyReceiver ||
           bytecode == Bytecode::kCallProperty ||
           bytecode == Bytecode::kCallProperty0 ||
           bytecode == Bytecode::kCallProperty1 ||
           bytecode == Bytecode::kCallProperty2 ||
           bytecode == Bytecode::kCallUndefinedReceiver ||
           bytecode == Bytecode::kCallUndefinedReceiver0 ||
           bytecode == Bytecode::kCallUndefinedReceiver1 ||
           bytecode == Bytecode::kCallUndefinedReceiver2 ||
           bytecode == Bytecode::kConstruct ||
           bytecode == Bytecode::kCallWithSpread ||
           bytecode == Bytecode::kConstructWithSpread ||
           bytecode == Bytecode::kConstructForwardAllArgs ||
           bytecode == Bytecode::kCallJSRuntime;
  }
Referenced by v8::internal::interpreter::InterpreterAssembler::CallJSAndDispatch(), v8::internal::BreakIterator::GetDebugBreakType(), and MakesCallAlongCriticalPath().
IsCallRuntime()
static constexpr bool v8::internal::interpreter::Bytecodes::IsCallRuntime (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 869 of file bytecodes.h.
                                                         {
    return bytecode == Bytecode::kCallRuntime ||
           bytecode == Bytecode::kCallRuntimeForPair ||
           bytecode == Bytecode::kInvokeIntrinsic;
  }
Referenced by v8::internal::anonymous_namespace{debug-evaluate.cc}::BytecodeRequiresRuntimeCheck(), v8::internal::interpreter::InterpreterAssembler::CallRuntimeN(), MakesCallAlongCriticalPath(), and v8::internal::Debug::PerformSideEffectCheckAtBytecode().
IsCompareWithoutEffects()
static constexpr bool v8::internal::interpreter::Bytecodes::IsCompareWithoutEffects (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 737 of file bytecodes.h.
                                                                   {
    static_assert(Bytecode::kTestReferenceEqual < Bytecode::kTestTypeOf);
    return bytecode >= Bytecode::kTestReferenceEqual &&
           bytecode <= Bytecode::kTestTypeOf;
  }
IsConditionalJump()
static constexpr bool v8::internal::interpreter::Bytecodes::IsConditionalJump (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 775 of file bytecodes.h.
                                                             {
    return bytecode >= Bytecode::kJumpIfNullConstant &&
           bytecode <= Bytecode::kJumpIfForInDone;
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::MarkBytecodeDead().
IsConditionalJumpConstant()
static constexpr bool v8::internal::interpreter::Bytecodes::IsConditionalJumpConstant (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 768 of file bytecodes.h.
                                                                     {
    return bytecode >= Bytecode::kJumpIfNullConstant &&
           bytecode <= Bytecode::kJumpIfToBooleanFalseConstant;
  }
IsConditionalJumpImmediate()
static constexpr bool v8::internal::interpreter::Bytecodes::IsConditionalJumpImmediate (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 761 of file bytecodes.h.
                                                                      {
    return bytecode >= Bytecode::kJumpIfToBooleanTrue &&
           bytecode <= Bytecode::kJumpIfForInDone;
  }
IsDebugBreak()
bool v8::internal::interpreter::Bytecodes::IsDebugBreak (Bytecode bytecode) [static]
Definition at line 167 of file bytecodes.cc.
                                              {
  switch (bytecode) {
#define CASE(Name, ...) case Bytecode::k##Name:
    DEBUG_BREAK_BYTECODE_LIST(CASE);
#undef CASE
    return true;
    default:
      break;
  }
  return false;
}
References CASE, and DEBUG_BREAK_BYTECODE_LIST.
Referenced by v8::internal::interpreter::BytecodeArrayIterator::ApplyDebugBreak(), v8::internal::interpreter::BytecodeDecoder::Decode(), and GetDebugBreak().
IsForwardJump()
static constexpr bool v8::internal::interpreter::Bytecodes::IsForwardJump (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 816 of file bytecodes.h.
                                                         {
    return bytecode >= Bytecode::kJump &&
           bytecode <= Bytecode::kJumpIfForInDone;
  }
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitJump(), v8::internal::maglev::MaglevGraphBuilder::MarkBytecodeDead(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith16BitOperand(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith8BitOperand(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness(), and v8::internal::interpreter::BytecodeArrayWriter::WriteJump().
IsJump()
static constexpr bool v8::internal::interpreter::Bytecodes::IsJump (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 809 of file bytecodes.h.
                                                  {
    return bytecode >= Bytecode::kJumpLoop &&
           bytecode <= Bytecode::kJumpIfForInDone;
  }
Referenced by v8::internal::BytecodeArray::Disassemble(), v8::internal::Code::GetBaselinePCForNextExecutedBytecode(), v8::internal::maglev::MaglevGraphBuilder::KillPeeledLoopTargets(), v8::internal::interpreter::BytecodeArrayWriter::PatchJump(), v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareForBytecode(), v8::internal::BytecodeArray::PrintJson(), and v8::internal::baseline::BaselineCompiler::VisitSingleBytecode().
IsJumpConstant()
static constexpr bool v8::internal::interpreter::Bytecodes::IsJumpConstant (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 795 of file bytecodes.h.
                                                          {
    return bytecode >= Bytecode::kJumpConstant &&
           bytecode <= Bytecode::kJumpIfToBooleanFalseConstant;
  }
Referenced by v8::internal::interpreter::BytecodeArrayIterator::GetRelativeJumpTargetOffset().
IsJumpIfToBoolean()
static constexpr bool v8::internal::interpreter::Bytecodes::IsJumpIfToBoolean (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 802 of file bytecodes.h.
                                                             {
    return bytecode >= Bytecode::kJumpIfToBooleanTrueConstant &&
           bytecode <= Bytecode::kJumpIfToBooleanFalse;
  }
IsJumpImmediate()
static constexpr bool v8::internal::interpreter::Bytecodes::IsJumpImmediate (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 788 of file bytecodes.h.
                                                           {
    return bytecode == Bytecode::kJump || bytecode == Bytecode::kJumpLoop ||
           IsConditionalJumpImmediate(bytecode);
  }
Referenced by v8::internal::interpreter::BytecodeArrayIterator::GetRelativeJumpTargetOffset(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith16BitOperand(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith32BitOperand(), and v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith8BitOperand().
IsJumpWithoutEffects()
static constexpr bool v8::internal::interpreter::Bytecodes::IsJumpWithoutEffects (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 824 of file bytecodes.h.
                                                                {
    return IsJump(bytecode) && !IsJumpIfToBoolean(bytecode) &&
           bytecode != Bytecode::kJumpLoop;
  }
IsLdarOrStar()
static constexpr bool v8::internal::interpreter::Bytecodes::IsLdarOrStar (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 846 of file bytecodes.h.
                                                        {
    return bytecode == Bytecode::kLdar || IsAnyStar(bytecode);
  }
IsPrefixScalingBytecode()
static constexpr bool v8::internal::interpreter::Bytecodes::IsPrefixScalingBytecode (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 876 of file bytecodes.h.
                                                                   {
    return bytecode == Bytecode::kExtraWide || bytecode == Bytecode::kWide ||
           bytecode == Bytecode::kDebugBreakExtraWide ||
           bytecode == Bytecode::kDebugBreakWide;
  }
Referenced by v8::internal::interpreter::BytecodeArrayIterator::current_bytecode(), v8::internal::interpreter::BytecodeDecoder::Decode(), v8::internal::BreakIterator::GetDebugBreakType(), v8::internal::interpreter::BytecodeArrayIterator::next_bytecode(), v8::internal::interpreter::BytecodeArrayWriter::PatchJump(), and v8::internal::interpreter::BytecodeArrayIterator::UpdateOperandScale().
IsRegisterInputOperandType()
bool v8::internal::interpreter::Bytecodes::IsRegisterInputOperandType (OperandType operand_type) [static]
Definition at line 222 of file bytecodes.cc.
                                                                   {
  switch (operand_type) {
#define CASE(Name, _) \
  case OperandType::k##Name: \
    return true;
    REGISTER_INPUT_OPERAND_TYPE_LIST(CASE)
    CASE(RegInOut, _)
#undef CASE
#define CASE(Name, _) \
  case OperandType::k##Name: \
    break;
    NON_REGISTER_OPERAND_TYPE_LIST(CASE)
    REGISTER_OUTPUT_OPERAND_TYPE_LIST(CASE)
#undef CASE
  }
  return false;
}
References _, CASE, NON_REGISTER_OPERAND_TYPE_LIST, REGISTER_INPUT_OPERAND_TYPE_LIST, and REGISTER_OUTPUT_OPERAND_TYPE_LIST.
Referenced by v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForInOperand().
IsRegisterListOperandType()
bool v8::internal::interpreter::Bytecodes::IsRegisterListOperandType (OperandType operand_type) [static]
Definition at line 197 of file bytecodes.cc.
                                                                  {
  switch (operand_type) {
    case OperandType::kRegList:
    case OperandType::kRegOutList:
      return true;
    default:
      return false;
  }
}
Referenced by v8::internal::interpreter::InterpreterAssembler::GetRegisterListAtOperandIndex().
IsRegisterLoadWithoutEffects()
static constexpr bool v8::internal::interpreter::Bytecodes::IsRegisterLoadWithoutEffects (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 754 of file bytecodes.h.
                                                                        {
    return IsShortStar(bytecode) ||
           (bytecode >= Bytecode::kStar && bytecode <= Bytecode::kPopContext);
  }
IsRegisterOperandType()
bool v8::internal::interpreter::Bytecodes::IsRegisterOperandType (OperandType operand_type) [static]
Definition at line 180 of file bytecodes.cc.
                                                              {
  switch (operand_type) {
#define CASE(Name, _) \
  case OperandType::k##Name: \
    return true;
    REGISTER_OPERAND_TYPE_LIST(CASE)
#undef CASE
#define CASE(Name, _) \
  case OperandType::k##Name: \
    break;
    NON_REGISTER_OPERAND_TYPE_LIST(CASE)
#undef CASE
  }
  return false;
}
References CASE, NON_REGISTER_OPERAND_TYPE_LIST, and REGISTER_OPERAND_TYPE_LIST.
Referenced by v8::internal::interpreter::InterpreterAssembler::BytecodeOperandReg(), v8::internal::interpreter::BytecodeDecoder::DecodeRegisterOperand(), and v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperandRange().
IsRegisterOutputOperandType()
bool v8::internal::interpreter::Bytecodes::IsRegisterOutputOperandType (OperandType operand_type) [static]
Definition at line 241 of file bytecodes.cc.
                                                                    {
  switch (operand_type) {
#define CASE(Name, _) \
  case OperandType::k##Name: \
    return true;
    REGISTER_OUTPUT_OPERAND_TYPE_LIST(CASE)
    CASE(RegInOut, _)
#undef CASE
#define CASE(Name, _) \
  case OperandType::k##Name: \
    break;
    NON_REGISTER_OPERAND_TYPE_LIST(CASE)
    REGISTER_INPUT_OPERAND_TYPE_LIST(CASE)
#undef CASE
  }
  return false;
}
References _, CASE, NON_REGISTER_OPERAND_TYPE_LIST, REGISTER_INPUT_OPERAND_TYPE_LIST, and REGISTER_OUTPUT_OPERAND_TYPE_LIST.
Referenced by v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateAssignments(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForOutOperand().
IsRuntimeIdOperandType()
static bool v8::internal::interpreter::Bytecodes::IsRuntimeIdOperandType (OperandType operand_type) [static]
IsShortStar()
static constexpr bool v8::internal::interpreter::Bytecodes::IsShortStar (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 743 of file bytecodes.h.
                                                       {
    return bytecode >= Bytecode::kFirstShortStar &&
           bytecode <= Bytecode::kLastShortStar;
  }
References v8::internal::interpreter::kFirstShortStar, and v8::internal::interpreter::kLastShortStar.
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter.cc}::BuiltinIndexFromBytecode(), BytecodeHasHandler(), v8::internal::interpreter::Register::FromShortStar(), v8::internal::interpreter::BytecodeArrayIterator::GetStarTargetRegister(), v8::internal::interpreter::Interpreter::Initialize(), and v8::internal::interpreter::InterpreterAssembler::StoreRegisterForShortStar().
IsStarLookahead()
bool v8::internal::interpreter::Bytecodes::IsStarLookahead (Bytecode bytecode, OperandScale operand_scale) [static]
Definition at line 260 of file bytecodes.cc.
                                                                             {
  if (operand_scale == OperandScale::kSingle) {
    switch (bytecode) {
      // Short-star lookahead is required for correctness on kDebugBreak0. The
      // handler for all short-star codes re-reads the opcode from the bytecode
      // array and would not work correctly if it instead read kDebugBreak0.
      case Bytecode::kDebugBreak0:
      case Bytecode::kLdaZero:
      case Bytecode::kLdaSmi:
      case Bytecode::kLdaNull:
      case Bytecode::kLdaTheHole:
      case Bytecode::kLdaConstant:
      case Bytecode::kLdaUndefined:
      case Bytecode::kLdaGlobal:
      case Bytecode::kGetNamedProperty:
      case Bytecode::kGetKeyedProperty:
      case Bytecode::kLdaContextSlotNoCell:
      case Bytecode::kLdaImmutableContextSlot:
      case Bytecode::kLdaCurrentContextSlotNoCell:
      case Bytecode::kLdaImmutableCurrentContextSlot:
      case Bytecode::kAdd:
      case Bytecode::kSub:
      case Bytecode::kMul:
      case Bytecode::kAddSmi:
      case Bytecode::kSubSmi:
      case Bytecode::kInc:
      case Bytecode::kDec:
      case Bytecode::kTypeOf:
      case Bytecode::kCallAnyReceiver:
      case Bytecode::kCallProperty:
      case Bytecode::kCallProperty0:
      case Bytecode::kCallProperty1:
      case Bytecode::kCallProperty2:
      case Bytecode::kCallUndefinedReceiver:
      case Bytecode::kCallUndefinedReceiver0:
      case Bytecode::kCallUndefinedReceiver1:
      case Bytecode::kCallUndefinedReceiver2:
      case Bytecode::kConstruct:
      case Bytecode::kConstructWithSpread:
      case Bytecode::kCreateObjectLiteral:
      case Bytecode::kCreateArrayLiteral:
      case Bytecode::kThrowReferenceErrorIfHole:
      case Bytecode::kGetTemplateObject:
        return true;
      default:
        return false;
    }
  }
  return false;
}
Referenced by v8::internal::interpreter::InterpreterAssembler::DispatchToBytecodeWithOptionalStarLookahead(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::DispatchToBytecodeWithOptionalStarLookahead(), and v8::internal::interpreter::InterpreterAssembler::JumpToOffset().
IsSwitch()
static constexpr bool v8::internal::interpreter::Bytecodes::IsSwitch (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 830 of file bytecodes.h.
                                                    {
    return bytecode == Bytecode::kSwitchOnSmiNoFeedback ||
           bytecode == Bytecode::kSwitchOnGeneratorState;
  }
Referenced by v8::internal::BytecodeArray::Disassemble(), v8::internal::interpreter::BytecodeArrayWriter::EmitSwitch(), v8::internal::Code::GetBaselinePCForNextExecutedBytecode(), v8::internal::maglev::MaglevGraphBuilder::MarkBytecodeDead(), v8::internal::interpreter::BytecodeRegisterOptimizer::PrepareForBytecode(), v8::internal::BytecodeArray::PrintJson(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness(), v8::internal::baseline::BaselineCompiler::VisitSingleBytecode(), and v8::internal::interpreter::BytecodeArrayWriter::WriteSwitch().
IsUnconditionalJump()
static constexpr bool v8::internal::interpreter::Bytecodes::IsUnconditionalJump (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 781 of file bytecodes.h.
                                                               {
    return bytecode >= Bytecode::kJumpLoop &&
           bytecode <= Bytecode::kJumpConstant;
  }
Referenced by v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
IsUnsignedOperandType()
bool v8::internal::interpreter::Bytecodes::IsUnsignedOperandType (OperandType operand_type) [static]
Definition at line 321 of file bytecodes.cc.
                                                              {
  switch (operand_type) {
#define CASE(Name, _) \
  case OperandType::k##Name: \
    return OperandTraits<OperandType::k##Name>::TypeInfoTraits::kIsUnsigned;
    OPERAND_TYPE_LIST(CASE)
#undef CASE
  }
  UNREACHABLE();
}
References CASE, OPERAND_TYPE_LIST, and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::InterpreterAssembler::BytecodeSignedOperand(), v8::internal::interpreter::InterpreterAssembler::BytecodeUnsignedOperand(), v8::internal::interpreter::BytecodeDecoder::DecodeSignedOperand(), v8::internal::interpreter::BytecodeDecoder::DecodeUnsignedOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetSignedOperand(), and v8::internal::interpreter::BytecodeArrayIterator::GetUnsignedOperand().
IsWithoutExternalSideEffects()
static constexpr bool v8::internal::interpreter::Bytecodes::IsWithoutExternalSideEffects (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 837 of file bytecodes.h.
                                                                        {
    return (IsAccumulatorLoadWithoutEffects(bytecode) ||
            IsRegisterLoadWithoutEffects(bytecode) ||
            IsCompareWithoutEffects(bytecode) ||
            IsJumpWithoutEffects(bytecode) || IsSwitch(bytecode) ||
            bytecode == Bytecode::kReturn);
  }
Referenced by v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
MakesCallAlongCriticalPath()
bool v8::internal::interpreter::Bytecodes::MakesCallAlongCriticalPath (Bytecode bytecode) [static]
Definition at line 207 of file bytecodes.cc.
                                                            {
  if (IsCallOrConstruct(bytecode) || IsCallRuntime(bytecode)) return true;
  switch (bytecode) {
    case Bytecode::kCreateWithContext:
    case Bytecode::kCreateBlockContext:
    case Bytecode::kCreateCatchContext:
    case Bytecode::kCreateRegExpLiteral:
    case Bytecode::kGetIterator:
      return true;
    default:
      return false;
  }
}
References IsCallOrConstruct(), and IsCallRuntime().
Referenced by v8::internal::interpreter::InterpreterAssembler::BytecodeOffset(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeOffset(), v8::internal::interpreter::InterpreterAssembler::CallJSAndDispatch(), v8::internal::interpreter::InterpreterAssembler::CallJSWithSpreadAndDispatch(), v8::internal::interpreter::InterpreterAssembler::CallPrologue(), v8::internal::interpreter::InterpreterAssembler::CallRuntimeN(), v8::internal::interpreter::InterpreterAssembler::Construct(), v8::internal::interpreter::InterpreterAssembler::ConstructForwardAllArgs(), v8::internal::interpreter::InterpreterAssembler::ConstructWithSpread(), v8::internal::interpreter::InterpreterAssembler::Dispatch(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::Dispatch(), v8::internal::interpreter::InterpreterAssembler::DispatchTablePointer(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::DispatchTablePointer(), v8::internal::interpreter::InterpreterAssembler::DispatchWide(), v8::internal::interpreter::InterpreterAssembler::GetInterpretedFramePointer(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::GetInterpretedFramePointer(), and v8::internal::interpreter::InterpreterAssembler::InterpreterAssembler().
NumberOfOperands()
static int v8::internal::interpreter::Bytecodes::NumberOfOperands (Bytecode bytecode) [inline], [static]
Definition at line 897 of file bytecodes.h.
                                                 {
    // Using V8_ASSUME instead of DCHECK here works around a spurious GCC
    // warning -- somehow GCC thinks that bytecode == kLast+1 can happen here.
    V8_ASSUME(bytecode <= Bytecode::kLast);
    return kOperandCount[static_cast<uint8_t>(bytecode)];
  }
References v8::internal::interpreter::kLast, and V8_ASSUME.
Referenced by v8::internal::interpreter::BytecodeNode::BytecodeNode(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::BytecodeOperand(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedByte(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedQuad(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandSignedShort(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedByte(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedQuad(), v8::internal::interpreter::InterpreterAssembler::BytecodeOperandUnsignedShort(), v8::internal::interpreter::BytecodeDecoder::Decode(), v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperandRange(), v8::internal::interpreter::BytecodeArrayIterator::GetSignedOperand(), v8::internal::interpreter::BytecodeArrayIterator::GetStarTargetRegister(), v8::internal::interpreter::BytecodeArrayIterator::GetUnsignedOperand(), IsBytecodeWithScalableOperands(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateAssignments().
OperandIsScalable()
static bool v8::internal::interpreter::Bytecodes::OperandIsScalable (Bytecode bytecode, int operand_index) [inline], [static]
Definition at line 933 of file bytecodes.h.
                                                                      {
    return OperandIsScalableSignedByte(bytecode, operand_index) ||
           OperandIsScalableUnsignedByte(bytecode, operand_index);
  }
Referenced by IsBytecodeWithScalableOperands().
OperandIsScalableSignedByte()
static bool v8::internal::interpreter::Bytecodes::OperandIsScalableSignedByte (Bytecode bytecode, int operand_index) [inline], [static]
Definition at line 919 of file bytecodes.h.
                                                             {
    DCHECK_LE(bytecode, Bytecode::kLast);
    return kOperandTypeInfos[static_cast<size_t>(bytecode)][operand_index] ==
           OperandTypeInfo::kScalableSignedByte;
  }
References DCHECK_LE, and v8::internal::interpreter::kLast.
Referenced by v8::internal::interpreter::BytecodeNode::UpdateScaleForOperand().
OperandIsScalableUnsignedByte()
static bool v8::internal::interpreter::Bytecodes::OperandIsScalableUnsignedByte (Bytecode bytecode, int operand_index) [inline], [static]
Definition at line 926 of file bytecodes.h.
                                                               {
    DCHECK_LE(bytecode, Bytecode::kLast);
    return kOperandTypeInfos[static_cast<size_t>(bytecode)][operand_index] ==
           OperandTypeInfo::kScalableUnsignedByte;
  }
References DCHECK_LE, and v8::internal::interpreter::kLast.
Referenced by v8::internal::interpreter::BytecodeNode::UpdateScaleForOperand().
OperandScaleRequiresPrefixBytecode()
static bool v8::internal::interpreter::Bytecodes::OperandScaleRequiresPrefixBytecode (OperandScale operand_scale) [inline], [static]
Definition at line 655 of file bytecodes.h.
                                                                             {
    return operand_scale != OperandScale::kSingle;
  }
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitJumpLoop().
OperandScaleToPrefixBytecode()
static Bytecode v8::internal::interpreter::Bytecodes::OperandScaleToPrefixBytecode (OperandScale operand_scale) [inline], [static]
Definition at line 643 of file bytecodes.h.
                                                                           {
    switch (operand_scale) {
      case OperandScale::kQuadruple:
        return Bytecode::kExtraWide;
      case OperandScale::kDouble:
        return Bytecode::kWide;
      default:
        UNREACHABLE();
    }
  }
References v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitBytecode(), and ToString().
PrefixBytecodeToOperandScale()
static OperandScale v8::internal::interpreter::Bytecodes::PrefixBytecodeToOperandScale (Bytecode bytecode) [inline], [static]
Definition at line 661 of file bytecodes.h.
                                                                      {
#ifdef V8_TARGET_OS_ANDROID
    // The compiler is very smart, turning the switch into branchless code.
    // However this triggers a CPU bug on some android devices (see
    // crbug.com/1379788). We therefore intentionally use code the compiler has
    // a harder time optimizing on Android. At least until clang 15.0 the
    // current workaround prevents hitting the CPU bug.
    // TODO(chromium:1379788): Remove this hack if we get an external fix.
    if (bytecode == Bytecode::kWide || bytecode == Bytecode::kDebugBreakWide) {
      return OperandScale::kDouble;
    } else if (bytecode == Bytecode::kExtraWide ||
               bytecode == Bytecode::kDebugBreakExtraWide) {
      return OperandScale::kQuadruple;
    } else {
      UNREACHABLE();
    }
#else
    switch (bytecode) {
      case Bytecode::kExtraWide:
      case Bytecode::kDebugBreakExtraWide:
        return OperandScale::kQuadruple;
      case Bytecode::kWide:
      case Bytecode::kDebugBreakWide:
        return OperandScale::kDouble;
      default:
        UNREACHABLE();
    }
#endif
  }
References v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeDecoder::Decode(), v8::internal::interpreter::BytecodeArrayWriter::PatchJump(), and v8::internal::interpreter::BytecodeArrayIterator::UpdateOperandScale().
ReadsAccumulator()
static bool v8::internal::interpreter::Bytecodes::ReadsAccumulator (Bytecode bytecode) [inline], [static]
Definition at line 698 of file bytecodes.h.
                                                  {
    return BytecodeOperands::ReadsAccumulator(GetImplicitRegisterUse(bytecode));
  }
References v8::internal::interpreter::BytecodeOperands::ReadsAccumulator().
Referenced by v8::internal::interpreter::InterpreterAssembler::GetAccumulator(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::GetAccumulator(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness().
Returns()
static constexpr bool v8::internal::interpreter::Bytecodes::Returns (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 883 of file bytecodes.h.
                                                   {
#define OR_BYTECODE(NAME) || bytecode == Bytecode::k##NAME
    return false RETURN_BYTECODE_LIST(OR_BYTECODE);
#undef OR_BYTECODE
  }
References OR_BYTECODE, and RETURN_BYTECODE_LIST.
Referenced by v8::internal::Code::GetBaselinePCForNextExecutedBytecode(), v8::internal::interpreter::InterpreterAssembler::InterpreterAssembler(), v8::internal::maglev::MaglevGraphBuilder::KillPeeledLoopTargets(), v8::internal::maglev::MaglevGraphBuilder::MarkBytecodeDead(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
ScaleForSignedOperand()
static OperandScale v8::internal::interpreter::Bytecodes::ScaleForSignedOperand (int32_t value) [inline], [static]
Definition at line 1085 of file bytecodes.h.
                                                           {
    if (value >= kMinInt8 && value <= kMaxInt8) {
      return OperandScale::kSingle;
    } else if (value >= kMinInt16 && value <= kMaxInt16) {
      return OperandScale::kDouble;
    } else {
      return OperandScale::kQuadruple;
    }
  }
References v8::internal::kMaxInt16, v8::internal::kMaxInt8, v8::internal::kMinInt16, v8::internal::kMinInt8, and v8::internal::value.
Referenced by v8::internal::interpreter::BytecodeNode::ScaleForOperand(), and v8::internal::interpreter::BytecodeNode::UpdateScaleForOperand().
ScaleForUnsignedOperand()
static OperandScale v8::internal::interpreter::Bytecodes::ScaleForUnsignedOperand (uint32_t value) [inline], [static]
Definition at line 1096 of file bytecodes.h.
                                                              {
    if (value <= kMaxUInt8) {
      return OperandScale::kSingle;
    } else if (value <= kMaxUInt16) {
      return OperandScale::kDouble;
    } else {
      return OperandScale::kQuadruple;
    }
  }
References v8::internal::kMaxUInt16, v8::internal::kMaxUInt8, and v8::internal::value.
Referenced by v8::internal::interpreter::BytecodeArrayWriter::EmitJumpLoop(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith16BitOperand(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith8BitOperand(), v8::internal::interpreter::BytecodeNode::ScaleForOperand(), and v8::internal::interpreter::BytecodeNode::UpdateScaleForOperand().
Size()
static int v8::internal::interpreter::Bytecodes::Size (Bytecode bytecode, OperandScale operand_scale) [inline], [static]
Definition at line 975 of file bytecodes.h.
                                                                 {
    DCHECK_LE(bytecode, Bytecode::kLast);
    static_assert(static_cast<int>(OperandScale::kQuadruple) == 4 &&
                  OperandScale::kLast == OperandScale::kQuadruple);
    int scale_index = static_cast<int>(operand_scale) >> 1;
    return kBytecodeSizes[scale_index][static_cast<size_t>(bytecode)];
  }
References DCHECK_LE, and v8::internal::interpreter::kLast.
Referenced by v8::internal::interpreter::BytecodeArrayIterator::current_bytecode_size_without_prefix(), v8::internal::interpreter::InterpreterAssembler::CurrentBytecodeSize(), v8::internal::interpreter::BytecodeHandlerReducer< Next >::CurrentBytecodeSize(), v8::internal::interpreter::BytecodeDecoder::Decode(), v8::internal::interpreter::BytecodeArrayWriter::EmitJumpLoop(), and GetDebugBreak().
SizeForUnsignedOperand()
static OperandSize v8::internal::interpreter::Bytecodes::SizeForUnsignedOperand (uint32_t value) [inline], [static]
Definition at line 1107 of file bytecodes.h.
                                                            {
    if (value <= kMaxUInt8) {
      return OperandSize::kByte;
    } else if (value <= kMaxUInt16) {
      return OperandSize::kShort;
    } else {
      return OperandSize::kQuad;
    }
  }
References v8::internal::interpreter::kByte, v8::internal::kMaxUInt16, v8::internal::kMaxUInt8, v8::internal::interpreter::kQuad, v8::internal::interpreter::kShort, and v8::internal::value.
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::CallRuntime(), v8::internal::interpreter::BytecodeArrayBuilder::CallRuntimeForPair(), and v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith8BitOperand().
SizeOfOperand()
static OperandSize v8::internal::interpreter::Bytecodes::SizeOfOperand (OperandType operand_type, OperandScale operand_scale) [inline], [static]
Definition at line 1061 of file bytecodes.h.
                                                               {
    DCHECK_LE(operand_type, OperandType::kLast);
    DCHECK_GE(operand_scale, OperandScale::kSingle);
    DCHECK_LE(operand_scale, OperandScale::kLast);
    static_assert(static_cast<int>(OperandScale::kQuadruple) == 4 &&
                  OperandScale::kLast == OperandScale::kQuadruple);
    int scale_index = static_cast<int>(operand_scale) >> 1;
    return kOperandKindSizes[scale_index][static_cast<size_t>(operand_type)];
  }
References DCHECK_GE, DCHECK_LE, and v8::internal::interpreter::kLast.
Referenced by v8::internal::interpreter::BytecodeDecoder::DecodeSignedOperand(), and v8::internal::interpreter::BytecodeDecoder::DecodeUnsignedOperand().
ToByte()
static uint8_t v8::internal::interpreter::Bytecodes::ToByte (Bytecode bytecode) [inline], [static]
Definition at line 629 of file bytecodes.h.
                                           {
    DCHECK_LE(bytecode, Bytecode::kLast);
    return static_cast<uint8_t>(bytecode);
  }
References DCHECK_LE, and v8::internal::interpreter::kLast.
Referenced by v8::internal::interpreter::BytecodeArrayIterator::ApplyDebugBreak(), v8::internal::interpreter::BytecodeArrayWriter::EmitBytecode(), v8::internal::interpreter::Interpreter::GetDispatchCounter(), v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith16BitOperand(), and v8::internal::interpreter::BytecodeArrayWriter::PatchJumpWith8BitOperand().
ToString() [1/2]
const char * v8::internal::interpreter::Bytecodes::ToString (Bytecode bytecode) [static]
Definition at line 123 of file bytecodes.cc.
                                                 {
  switch (bytecode) {
#define CASE(Name, ...) \
  case Bytecode::k##Name: \
    return #Name;
    BYTECODE_LIST(CASE, CASE)
#undef CASE
  }
  UNREACHABLE();
}
References BYTECODE_LIST, CASE, and v8::internal::UNREACHABLE().
Referenced by v8::internal::interpreter::BytecodeDecoder::Decode(), v8::internal::Builtins::EmitCodeCreateEvents(), v8::internal::DebugEvaluate::FunctionGetSideEffectState(), v8::internal::interpreter::Interpreter::GetDispatchCountersObject(), v8::internal::interpreter::Interpreter::Initialize(), v8::internal::interpreter::operator<<(), v8::internal::interpreter::BytecodeNode::Print(), ToString(), and v8::internal::interpreter::WriteBytecode().
ToString() [2/2]
std::string v8::internal::interpreter::Bytecodes::ToString (Bytecode bytecode, OperandScale operand_scale, const char * separator = `.`) [static]
Definition at line 135 of file bytecodes.cc.
                                                       {
  std::string value(ToString(bytecode));
  if (operand_scale > OperandScale::kSingle) {
    Bytecode prefix_bytecode = OperandScaleToPrefixBytecode(operand_scale);
    std::string suffix = ToString(prefix_bytecode);
    return value.append(separator).append(suffix);
  } else {
    return value;
  }
}
References OperandScaleToPrefixBytecode(), v8::internal::separator, v8::internal::string, ToString(), and v8::internal::value.
UnconditionallyThrows()
static constexpr bool v8::internal::interpreter::Bytecodes::UnconditionallyThrows (Bytecode bytecode) [inline], [static], [constexpr]
Definition at line 890 of file bytecodes.h.
                                                                 {
#define OR_BYTECODE(NAME) || bytecode == Bytecode::k##NAME
    return false UNCONDITIONAL_THROW_BYTECODE_LIST(OR_BYTECODE);
#undef OR_BYTECODE
  }
References OR_BYTECODE, and UNCONDITIONAL_THROW_BYTECODE_LIST.
Referenced by v8::internal::maglev::MaglevGraphBuilder::MarkBytecodeDead(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
WritesAccumulator()
static bool v8::internal::interpreter::Bytecodes::WritesAccumulator (Bytecode bytecode) [inline], [static]
Definition at line 703 of file bytecodes.h.
                                                   {
    return BytecodeOperands::WritesAccumulator(
        GetImplicitRegisterUse(bytecode));
  }
References v8::internal::interpreter::BytecodeOperands::WritesAccumulator().
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForEagerCall(), v8::internal::interpreter::InterpreterAssembler::SetAccumulator(), and v8::internal::interpreter::BytecodeHandlerReducer< Next >::SetAccumulator().
WritesImplicitRegister()
static bool v8::internal::interpreter::Bytecodes::WritesImplicitRegister (Bytecode bytecode) [inline], [static]
Definition at line 722 of file bytecodes.h.
                                                        {
    return BytecodeOperands::WritesImplicitRegister(
        GetImplicitRegisterUse(bytecode));
  }
References v8::internal::interpreter::BytecodeOperands::WritesImplicitRegister().
Referenced by v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateAssignments().
WritesOrClobbersAccumulator()
static bool v8::internal::interpreter::Bytecodes::WritesOrClobbersAccumulator (Bytecode bytecode) [inline], [static]
Definition at line 715 of file bytecodes.h.
                                                             {
    return BytecodeOperands::WritesOrClobbersAccumulator(
        GetImplicitRegisterUse(bytecode));
  }
References v8::internal::interpreter::BytecodeOperands::WritesOrClobbersAccumulator().
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), and v8::internal::baseline::BaselineCompiler::VisitSingleBytecode().
Member Data Documentation
kBytecodeCount
const int v8::internal::interpreter::Bytecodes::kBytecodeCount = static_cast<int>(Bytecode::kLast) + 1 [static]
Definition at line 614 of file bytecodes.h.
Referenced by v8::internal::AdvanceBytecodeOffsetOrReturn(), v8::internal::interpreter::Interpreter::ForEachBytecode(), and v8::internal::interpreter::WriteHeader().
kBytecodeSizes
const uint8_t v8::internal::interpreter::Bytecodes::kBytecodeSizes [static], [private]
Initial value:
= {
  {
#define ENTRY(Name, ...)
  }, {
#define ENTRY(Name, ...)
  }, {
#define ENTRY(Name, ...)
  }
}
Definition at line 1129 of file bytecodes.h.
kImplicitRegisterUse
const ImplicitRegisterUse v8::internal::interpreter::Bytecodes::kImplicitRegisterUse [static], [private]
Initial value:
= {
#define ENTRY(Name, ...)
}
Definition at line 1127 of file bytecodes.h.
kIsScalable
const bool v8::internal::interpreter::Bytecodes::kIsScalable[] [static], [private]
Definition at line 1128 of file bytecodes.h.
kMaxOperands
const int v8::internal::interpreter::Bytecodes::kMaxOperands = 5 [static]
Definition at line 611 of file bytecodes.h.
Referenced by v8::internal::interpreter::BytecodeNodeBuilder< bytecode, implicit_register_use, operand_types >::Make().
kNumberOfRegisterOperands
const int v8::internal::interpreter::Bytecodes::kNumberOfRegisterOperands[] [static], [private]
Definition at line 1126 of file bytecodes.h.
kOperandCount
const int v8::internal::interpreter::Bytecodes::kOperandCount [static], [private]
Initial value:
= {
#define ENTRY(Name, ...)
}
Definition at line 1125 of file bytecodes.h.
kOperandKindSizes
const OperandSize v8::internal::interpreter::Bytecodes::kOperandKindSizes [static], [private]
Initial value:
= {
  {
#define ENTRY(Name, ...)
  }, {
#define ENTRY(Name, ...)
  }, {
#define ENTRY(Name, ...)
  }
}
Definition at line 1133 of file bytecodes.h.
kOperandOffsets
const int *const v8::internal::interpreter::Bytecodes::kOperandOffsets [static], [private]
Initial value:
= {
  {
#define ENTRY(Name, ...)
  }, {
#define ENTRY(Name, ...)
  }, {
#define ENTRY(Name, ...)
  }
}
Definition at line 1131 of file bytecodes.h.
kOperandSizes
const OperandSize *const v8::internal::interpreter::Bytecodes::kOperandSizes [static], [private]
Initial value:
= {
  {
#define ENTRY(Name, ...)
  }, {
#define ENTRY(Name, ...)
  }, {
#define ENTRY(Name, ...)
  }
}
Definition at line 1130 of file bytecodes.h.
kOperandTypeInfos
const OperandTypeInfo *const v8::internal::interpreter::Bytecodes::kOperandTypeInfos [static], [private]
Initial value:
= {
#define ENTRY(Name, ...)
}
Definition at line 1124 of file bytecodes.h.
kOperandTypes
const OperandType *const v8::internal::interpreter::Bytecodes::kOperandTypes [static], [private]
Initial value:
= {
#define ENTRY(Name, ...)
}
Definition at line 1123 of file bytecodes.h.
kShortStarCount
const int v8::internal::interpreter::Bytecodes::kShortStarCount [static]
Initial value:
=
      static_cast<int>(Bytecode::kLastShortStar) -
      static_cast<int>(Bytecode::kFirstShortStar) + 1
Definition at line 616 of file bytecodes.h.
Referenced by v8::internal::interpreter::anonymous_namespace{interpreter.cc}::BuiltinIndexFromBytecode(), v8::internal::interpreter::Register::TryToShortStar(), and v8::internal::interpreter::WriteHeader().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecodes.h
/mnt/V8SourceCode/src/interpreter/bytecodes.cc