v8::internal::PreparseDataBuilder::DataGatheringScope Class Reference
#include <preparse-data.h>
Public Member Functions
DataGatheringScope (PreParser *preparser)
DataGatheringScope (const DataGatheringScope &)=delete
DataGatheringScope & operator= (const DataGatheringScope &)=delete
void Start (DeclarationScope *function_scope)
void SetSkippableFunction (DeclarationScope *function_scope, int function_length, int num_inner_functions)
~DataGatheringScope ()
Private Member Functions
void Close ()
Private Attributes
PreParser * preparser_
PreparseDataBuilder * builder_
Detailed Description
Definition at line 112 of file preparse-data.h.
Constructor & Destructor Documentation
DataGatheringScope() [1/2]
v8::internal::PreparseDataBuilder::DataGatheringScope::DataGatheringScope (PreParser * preparser) [inline], [explicit]
Definition at line 114 of file preparse-data.h.
        : preparser_(preparser), builder_(nullptr) {}
DataGatheringScope() [2/2]
v8::internal::PreparseDataBuilder::DataGatheringScope::DataGatheringScope (const DataGatheringScope &) [delete]
 DataGatheringScope()
v8::internal::PreparseDataBuilder::DataGatheringScope::~DataGatheringScope () [inline]
Definition at line 122 of file preparse-data.h.
                                 {
      if (builder_ == nullptr) return;
      Close();
    }
Member Function Documentation
Close()
void v8::internal::PreparseDataBuilder::DataGatheringScope::Close () [private]
Definition at line 115 of file preparse-data.cc.
                                                  {
  PreparseDataBuilder* parent = builder_->parent_;
  preparser_->set_preparse_data_builder(parent);
  builder_->FinalizeChildren(preparser_->main_zone());
  if (parent == nullptr) return;
  if (!builder_->HasDataForParent()) return;
  parent->AddChild(builder_);
}
References v8::internal::PreparseDataBuilder::AddChild(), v8::internal::PreparseDataBuilder::FinalizeChildren(), v8::internal::PreparseDataBuilder::parent(), and v8::internal::PreparseDataBuilder::parent_.
operator=()
DataGatheringScope& v8::internal::PreparseDataBuilder::DataGatheringScope::operator= (const DataGatheringScope &) [delete]
SetSkippableFunction()
void v8::internal::PreparseDataBuilder::DataGatheringScope::SetSkippableFunction (DeclarationScope * function_scope, int function_length, int num_inner_functions)
Definition at line 231 of file preparse-data.cc.
                             {
  DCHECK_NULL(builder_->function_scope_);
  builder_->function_scope_ = function_scope;
  DCHECK_EQ(builder_->num_inner_functions_, 0);
  builder_->function_length_ = function_length;
  builder_->num_inner_functions_ = num_inner_functions;
  builder_->parent_->has_data_ = true;
}
References DCHECK_EQ, and DCHECK_NULL.
Referenced by v8::internal::PreParser::ParseFunctionLiteral().
Start()
void v8::internal::PreparseDataBuilder::DataGatheringScope::Start (DeclarationScope * function_scope)
Definition at line 105 of file preparse-data.cc.
                                      {
  Zone* main_zone = preparser_->main_zone();
  builder_ = main_zone->New<PreparseDataBuilder>(
      main_zone, preparser_->preparse_data_builder(),
      preparser_->preparse_data_builder_buffer());
  preparser_->set_preparse_data_builder(builder_);
  function_scope->set_preparse_data_builder(builder_);
}
References builder_, v8::internal::ParserBase< Impl >::main_zone(), v8::internal::Zone::New(), v8::internal::PreParser::preparse_data_builder(), v8::internal::PreParser::preparse_data_builder_buffer(), preparser_, v8::internal::DeclarationScope::set_preparse_data_builder(), and v8::internal::PreParser::set_preparse_data_builder().
Referenced by v8::internal::PreParser::ParseFunctionLiteral(), and v8::internal::PreParser::PreParseFunction().
Member Data Documentation
builder_
PreparseDataBuilder* v8::internal::PreparseDataBuilder::DataGatheringScope::builder_ [private]
Definition at line 131 of file preparse-data.h.
Referenced by Start().
preparser_
PreParser* v8::internal::PreparseDataBuilder::DataGatheringScope::preparser_ [private]
Definition at line 130 of file preparse-data.h.
Referenced by Start().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/parsing/preparse-data.h
/mnt/V8SourceCode/src/parsing/preparse-data.cc