cppgc::internal::PersistentBase Class Reference
#include <persistent.h>
Protected Member Functions
PersistentBase ()=default
PersistentBase (const void *raw)
const void * GetValue () const
void SetValue (const void *value)
PersistentNode * GetNode () const
void SetNode (PersistentNode *node)
void ClearFromGC () const
Protected Attributes
const void * raw_ = nullptr
PersistentNode * node_ = nullptr
Friends
class PersistentRegionBase
Detailed Description
Definition at line 23 of file persistent.h.
Constructor & Destructor Documentation
PersistentBase() [1/2]
cppgc::internal::PersistentBase::PersistentBase () [protected], [default]
PersistentBase() [2/2]
cppgc::internal::PersistentBase::PersistentBase (const void * raw) [inline], [explicit], [protected]
Definition at line 26 of file persistent.h.
: raw_(raw) {}
Member Function Documentation
ClearFromGC()
void cppgc::internal::PersistentBase::ClearFromGC () const [inline], [protected]
Definition at line 36 of file persistent.h.
                           {
    raw_ = nullptr;
    node_ = nullptr;
  }
References node_, and raw_.
Referenced by cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::ClearFromGC().
GetNode()
PersistentNode* cppgc::internal::PersistentBase::GetNode () const [inline], [protected]
Definition at line 31 of file persistent.h.
{ return node_; }
References node_.
Referenced by cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Assign(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignSafe(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignUnsafe(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::ClearFromGC(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=(), and cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::~BasicCrossThreadPersistent().
GetValue()
const void* cppgc::internal::PersistentBase::GetValue () const [inline], [protected]
Definition at line 28 of file persistent.h.
{ return raw_; }
References raw_.
Referenced by cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Assign(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignSafe(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignUnsafe(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::ClearFromGC(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::GetFromGC(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::IsValid(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::V8_CLANG_NO_SANITIZE(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::V8_CLANG_NO_SANITIZE(), and cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::~BasicCrossThreadPersistent().
SetNode()
void cppgc::internal::PersistentBase::SetNode (PersistentNode * node) [inline], [protected]
Definition at line 32 of file persistent.h.
{ node_ = node; }
References node_.
Referenced by cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Assign(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignSafe(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignUnsafe(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicCrossThreadPersistent(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::BasicPersistent(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=(), and cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::~BasicCrossThreadPersistent().
SetValue()
void cppgc::internal::PersistentBase::SetValue (const void * value) [inline], [protected]
Definition at line 29 of file persistent.h.
{ raw_ = value; }
References raw_, and v8::internal::value.
Referenced by cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Assign(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignSafe(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::AssignUnsafe(), cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::Clear(), cppgc::internal::BasicCrossThreadPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=(), and cppgc::internal::BasicPersistent< T, WeaknessPolicy, LocationPolicy, CheckingPolicy >::operator=().
Friends And Related Function Documentation
PersistentRegionBase
friend class PersistentRegionBase [friend]
Definition at line 45 of file persistent.h.
Member Data Documentation
node_
PersistentNode* cppgc::internal::PersistentBase::node_ = nullptr [mutable], [protected]
Definition at line 43 of file persistent.h.
Referenced by ClearFromGC(), GetNode(), cppgc::internal::CrossThreadPersistentBase::GetNodeFromGC(), cppgc::internal::CrossThreadPersistentBase::GetNodeSafe(), SetNode(), and cppgc::internal::CrossThreadPersistentBase::SetNodeSafe().
raw_
const void* cppgc::internal::PersistentBase::raw_ = nullptr [mutable], [protected]
Definition at line 42 of file persistent.h.
Referenced by cppgc::internal::CrossThreadPersistentBase::ClearFromGC(), ClearFromGC(), GetValue(), SetValue(), and cppgc::internal::CrossThreadPersistentBase::V8_CLANG_NO_SANITIZE().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/cppgc/persistent.h