v8::internal::LargeObjectSpaceObjectIterator Class Reference
#include <large-spaces.h>
Public Member Functions
LargeObjectSpaceObjectIterator (LargeObjectSpace *space)
Tagged< HeapObject > Next () override
Private Attributes
LargePageMetadata * current_
Additional Inherited Members
Detailed Description
Definition at line 211 of file large-spaces.h.
Constructor & Destructor Documentation
LargeObjectSpaceObjectIterator()
v8::internal::LargeObjectSpaceObjectIterator::LargeObjectSpaceObjectIterator (LargeObjectSpace * space) [explicit]
Definition at line 36 of file large-spaces.cc.
                             {
  current_ = space->first_page();
}
References current_, and space.
Member Function Documentation
Next()
Tagged< HeapObject > v8::internal::LargeObjectSpaceObjectIterator::Next () [override], [virtual]
Implements v8::internal::ObjectIterator.
Definition at line 41 of file large-spaces.cc.
                                                        {
  while (current_ != nullptr) {
    Tagged<HeapObject> object = current_->GetObject();
    current_ = current_->next_page();
    if (!IsFreeSpaceOrFiller(object)) return object;
  }
  return Tagged<HeapObject>();
}
References current_, v8::internal::LargePageMetadata::GetObject(), v8::internal::InstanceTypeChecker::IsFreeSpaceOrFiller(), v8::internal::LargePageMetadata::next_page(), and v8::internal::Tagged< HeapObject >.
Referenced by v8::internal::Heap::CollectAllAvailableGarbage(), and v8::internal::CodeStatistics::CollectCodeStatistics().
Member Data Documentation
current_
LargePageMetadata* v8::internal::LargeObjectSpaceObjectIterator::current_ [private]
Definition at line 218 of file large-spaces.h.
Referenced by LargeObjectSpaceObjectIterator(), and Next().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/large-spaces.h
/mnt/V8SourceCode/src/heap/large-spaces.cc