v8::internal::CallOrConstructBuiltinsAssembler Class Reference
#include <builtins-call-gen.h>
Public Types
enum class CallFunctionTemplateMode : uint8_t { kGeneric
, kCheckAccess
, kCheckCompatibleReceiver
, kCheckAccessAndCompatibleReceiver
 }
Public Member Functions
CallOrConstructBuiltinsAssembler (compiler::CodeAssemblerState *state)
void CallOrConstructWithArrayLike (TNode< JSAny > target, std::optional< TNode< Object >> new_target, TNode< Object > arguments_list, TNode< Context > context)
void CallOrConstructDoubleVarargs (TNode< JSAny > target, std::optional< TNode< Object >> new_target, TNode< FixedDoubleArray > elements, TNode< Int32T > length, TNode< Int32T > args_count, TNode< Context > context, TNode< Int32T > kind)
void CallOrConstructWithSpread (TNode< JSAny > target, std::optional< TNode< Object >> new_target, TNode< JSAny > spread, TNode< Int32T > args_count, TNode< Context > context)
template<class Descriptor >
void CallReceiver (Builtin id, std::optional< TNode< JSAny >>=std::nullopt)
template<class Descriptor >
void CallReceiver (Builtin id, TNode< Int32T > argc, TNode< UintPtrT > slot, std::optional< TNode< JSAny >>=std::nullopt)
void CallFunctionTemplate (CallFunctionTemplateMode mode, TNode< FunctionTemplateInfo > function_template_info, TNode< Int32T > argc, TNode< Context > context, TNode< Object > maybe_incumbent_context)
void BuildConstruct (TNode< JSAny > target, TNode< JSAny > new_target, TNode< Int32T > argc, const LazyNode< Context > &context, const LazyNode< Union< Undefined, FeedbackVector >> &feedback_vector, TNode< UintPtrT > slot, UpdateFeedbackMode mode)
void BuildConstructWithSpread (TNode< JSAny > target, TNode< JSAny > new_target, TNode< JSAny > spread, TNode< Int32T > argc, const LazyNode< Context > &context, const LazyNode< Union< Undefined, FeedbackVector >> &feedback_vector, TNode< TaggedIndex > slot, UpdateFeedbackMode mode)
void BuildConstructForwardAllArgs (TNode< JSAny > target, TNode< JSAny > new_target, const LazyNode< Context > &context, const LazyNode< Union< Undefined, FeedbackVector >> &feedback_vector, TNode< TaggedIndex > slot)
TNode< JSReceiver > GetCompatibleReceiver (TNode< JSReceiver > receiver, TNode< HeapObject > signature, TNode< Context > context)
Static Public Member Functions
constexpr static bool IsAccessCheckRequired (CallFunctionTemplateMode mode)
Additional Inherited Members
Detailed Description
Definition at line 15 of file builtins-call-gen.h.
Member Enumeration Documentation
CallFunctionTemplateMode
enum v8::internal::CallOrConstructBuiltinsAssembler::CallFunctionTemplateMode : uint8_t [strong]
Enumerator
kGeneric
kCheckAccess
kCheckCompatibleReceiver
kCheckAccessAndCompatibleReceiver
Definition at line 41 of file builtins-call-gen.h.
                                      : uint8_t {
    // This version is for using from IC system and generic builtins like
    // HandleApiCallOrConstruct. It does both access and receiver compatibility
    // checks if necessary and uses CallApiCallbackGeneric for calling Api
    // function in order to support side-effects checking and make the Api
    // function show up in the stack trace in case of exception.
    kGeneric,
    // These versions are used for generating calls from optimized code with
    // respective checks and use CallApiCallbackOptimized for calling Api
    // function.
    kCheckAccess,
    kCheckCompatibleReceiver,
    kCheckAccessAndCompatibleReceiver,
  };
Constructor & Destructor Documentation
CallOrConstructBuiltinsAssembler()
v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 17 of file builtins-call-gen.h.
      : CodeStubAssembler(state) {}
Member Function Documentation
BuildConstruct()
void v8::internal::CallOrConstructBuiltinsAssembler::BuildConstruct (TNode< JSAny > target, TNode< JSAny > new_target, TNode< Int32T > argc, const LazyNode< Context > & context, const LazyNode< Union< Undefined, FeedbackVector >> & feedback_vector, TNode< UintPtrT > slot, UpdateFeedbackMode mode)
Definition at line 79 of file builtins-constructor-gen.cc.
                                                   {
  TVARIABLE(AllocationSite, allocation_site);
  Label if_construct_generic(this), if_construct_array(this);
  TNode<Context> eager_context = context();
  // TODO(42200059): Propagate TaggedIndex usage.
  CollectConstructFeedback(eager_context, target, new_target, feedback_vector(),
                           IntPtrToTaggedIndex(Signed(slot)), mode,
                           &if_construct_generic, &if_construct_array,
                           &allocation_site);
  BIND(&if_construct_generic);
  TailCallBuiltin(Builtin::kConstruct, eager_context, target, new_target, argc);
  BIND(&if_construct_array);
  TailCallBuiltin(Builtin::kArrayConstructorImpl, eager_context, target,
                  new_target, argc, allocation_site.value());
}
References v8::internal::CodeStubAssembler::IntPtrToTaggedIndex(), mode(), v8::internal::compiler::CodeAssembler::Signed(), and v8::internal::compiler::CodeAssembler::TailCallBuiltin().
BuildConstructForwardAllArgs()
void v8::internal::CallOrConstructBuiltinsAssembler::BuildConstructForwardAllArgs (TNode< JSAny > target, TNode< JSAny > new_target, const LazyNode< Context > & context, const LazyNode< Union< Undefined, FeedbackVector >> & feedback_vector, TNode< TaggedIndex > slot)
Definition at line 192 of file builtins-constructor-gen.cc.
                             {
  TVARIABLE(AllocationSite, allocation_site);
  TNode<Context> eager_context = context();
  Label construct(this);
  CollectConstructFeedback(eager_context, target, new_target, feedback_vector(),
                           slot, UpdateFeedbackMode::kGuaranteedFeedback,
                           &construct, &construct, &allocation_site);
  BIND(&construct);
  TailCallBuiltin(Builtin::kConstructForwardAllArgs, eager_context, target,
                  new_target);
}
References v8::internal::kGuaranteedFeedback, and v8::internal::compiler::CodeAssembler::TailCallBuiltin().
BuildConstructWithSpread()
void v8::internal::CallOrConstructBuiltinsAssembler::BuildConstructWithSpread (TNode< JSAny > target, TNode< JSAny > new_target, TNode< JSAny > spread, TNode< Int32T > argc, const LazyNode< Context > & context, const LazyNode< Union< Undefined, FeedbackVector >> & feedback_vector, TNode< TaggedIndex > slot, UpdateFeedbackMode mode)
Definition at line 149 of file builtins-constructor-gen.cc.
                                                      {
  TVARIABLE(AllocationSite, allocation_site);
  Label if_construct_generic(this), if_construct_array(this);
  TNode<Context> eager_context = context();
  CollectConstructFeedback(eager_context, target, new_target, feedback_vector(),
                           slot, UpdateFeedbackMode::kGuaranteedFeedback,
                           &if_construct_generic, &if_construct_array,
                           &allocation_site);
  BIND(&if_construct_array);
  Goto(&if_construct_generic); // Not implemented.
  BIND(&if_construct_generic);
  CallOrConstructWithSpread(target, new_target, spread, argc, eager_context);
}
References CallOrConstructWithSpread(), v8::internal::compiler::CodeAssembler::Goto(), and v8::internal::kGuaranteedFeedback.
CallFunctionTemplate()
void v8::internal::CallOrConstructBuiltinsAssembler::CallFunctionTemplate (CallFunctionTemplateMode mode, TNode< FunctionTemplateInfo > function_template_info, TNode< Int32T > argc, TNode< Context > context, TNode< Object > maybe_incumbent_context)
Definition at line 703 of file builtins-call-gen.cc.
                                                                         {
  CodeStubArguments args(this, argc);
  Label throw_illegal_invocation(this, Label::kDeferred);
  // For API callbacks the receiver is always a JSReceiver (since
  // they are treated like sloppy mode functions). We might need
  // to perform access checks in the current {context}, depending
  // on whether the "needs access check" bit is set on the receiver
  // _and_ the {function_template_info} doesn't have the "accepts
  // any receiver" bit set.
  TNode<JSReceiver> receiver = CAST(args.GetReceiver());
  if (IsAccessCheckRequired(mode)) {
    TNode<Map> receiver_map = LoadMap(receiver);
    Label receiver_needs_access_check(this, Label::kDeferred),
        receiver_done(this);
    GotoIfNot(IsSetWord32<Map::Bits1::IsAccessCheckNeededBit>(
                  LoadMapBitField(receiver_map)),
              &receiver_done);
    TNode<Uint32T> function_template_info_flags = LoadObjectField<Uint32T>(
        function_template_info, FunctionTemplateInfo::kFlagOffset);
    Branch(IsSetWord32<FunctionTemplateInfo::AcceptAnyReceiverBit>(
               function_template_info_flags),
           &receiver_done, &receiver_needs_access_check);
    BIND(&receiver_needs_access_check);
    {
      CallRuntime(Runtime::kAccessCheck, context, receiver);
      Goto(&receiver_done);
    }
    BIND(&receiver_done);
  }
  // Figure out the API holder for the {receiver} depending on the
  // {mode} and the signature on the {function_template_info}.
  TNode<JSReceiver> holder;
  switch (mode) {
    case CallFunctionTemplateMode::kCheckAccess:
      // We did the access check (including the ToObject) above, so
      // {receiver} is a JSReceiver at this point, and we don't need
      // to perform any "compatible receiver check", so {holder} is
      // actually the {receiver}.
      holder = receiver;
      break;
    case CallFunctionTemplateMode::kCheckAccessAndCompatibleReceiver:
    case CallFunctionTemplateMode::kCheckCompatibleReceiver: {
      // The {function_template_info} has a signature, so look for a compatible
      // holder in the receiver's hidden prototype chain.
      TNode<HeapObject> signature = LoadObjectField<HeapObject>(
          function_template_info, FunctionTemplateInfo::kSignatureOffset);
      CSA_DCHECK(this, Word32BinaryNot(IsUndefined(signature)));
      // TODO(ishell, http://crbug.com/326505377): rename to
      // CheckCompatibleReceiverOrThrow().
      holder = GetCompatibleReceiver(receiver, signature, context);
      break;
    }
    case CallFunctionTemplateMode::kGeneric: {
      // If the {function_template_info} doesn't specify any signature, we
      // just use the receiver as the holder for the API callback, otherwise
      // we need to look for a compatible holder in the receiver's hidden
      // prototype chain.
      TNode<HeapObject> signature = LoadObjectField<HeapObject>(
          function_template_info, FunctionTemplateInfo::kSignatureOffset);
      holder = Select<JSReceiver>(
          IsUndefined(signature), // --
          [&]() { return receiver; },
          [&]() {
            return GetCompatibleReceiver(receiver, signature, context);
          });
      break;
    }
  }
  TNode<Object> callback_data = LoadObjectField(
      function_template_info, FunctionTemplateInfo::kCallbackDataOffset);
  // If the function doesn't have an associated C++ code to execute, just
  // return the receiver as would an empty function do (see
  // HandleApiCallHelper).
  {
    Label if_continue(this);
    GotoIfNot(IsTheHole(callback_data), &if_continue);
    args.PopAndReturn(receiver);
    Bind(&if_continue);
  }
  // Perform the actual API callback invocation via CallApiCallback.
  switch (mode) {
    case CallFunctionTemplateMode::kGeneric:
      TailCallBuiltin(Builtin::kCallApiCallbackGeneric, context,
                      TruncateIntPtrToInt32(args.GetLengthWithoutReceiver()),
                      topmost_script_having_context, function_template_info);
      break;
    case CallFunctionTemplateMode::kCheckAccess:
    case CallFunctionTemplateMode::kCheckAccessAndCompatibleReceiver:
    case CallFunctionTemplateMode::kCheckCompatibleReceiver: {
      TNode<RawPtrT> callback_address =
          LoadFunctionTemplateInfoJsCallbackPtr(function_template_info);
      TailCallBuiltin(Builtin::kCallApiCallbackOptimized, context,
                      callback_address,
                      TruncateIntPtrToInt32(args.GetLengthWithoutReceiver()),
                      function_template_info);
      break;
    }
  }
}
References v8::base::args, v8::internal::CodeStubAssembler::Bind(), v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, GetCompatibleReceiver(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIfNot(), IsAccessCheckRequired(), kCheckAccess, kCheckAccessAndCompatibleReceiver, kCheckCompatibleReceiver, v8::internal::compiler::CodeAssemblerLabel::kDeferred, kGeneric, v8::internal::CodeStubAssembler::LoadFunctionTemplateInfoJsCallbackPtr(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapBitField(), v8::internal::CodeStubAssembler::LoadObjectField(), mode(), v8::internal::compiler::CodeAssembler::TailCallBuiltin(), and v8::internal::CodeStubAssembler::TruncateIntPtrToInt32().
CallOrConstructDoubleVarargs()
void v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructDoubleVarargs (TNode< JSAny > target, std::optional< TNode< Object >> new_target, TNode< FixedDoubleArray > elements, TNode< Int32T > length, TNode< Int32T > args_count, TNode< Context > context, TNode< Int32T > kind)
Definition at line 340 of file builtins-call-gen.cc.
                                                                          {
  const ElementsKind new_kind = PACKED_ELEMENTS;
  const WriteBarrierMode barrier_mode = UPDATE_WRITE_BARRIER;
  CSA_DCHECK(this, Int32LessThanOrEqual(length,
                                        Int32Constant(FixedArray::kMaxLength)));
  TNode<IntPtrT> intptr_length = ChangeInt32ToIntPtr(length);
  CSA_DCHECK(this, WordNotEqual(intptr_length, IntPtrConstant(0)));
  // Allocate a new FixedArray of Objects.
  TNode<FixedArray> new_elements =
      CAST(AllocateFixedArray(new_kind, intptr_length));
  // CopyFixedArrayElements does not distinguish between holey and packed for
  // its first argument, so we don't need to dispatch on {kind} here.
  CopyFixedArrayElements(PACKED_DOUBLE_ELEMENTS, elements, new_kind,
                         new_elements, intptr_length, intptr_length,
                         barrier_mode);
  if (!new_target) {
    TailCallBuiltin(Builtin::kCallVarargs, context, target, args_count, length,
                    new_elements);
  } else {
    TailCallBuiltin(Builtin::kConstructVarargs, context, target, *new_target,
                    args_count, length, new_elements);
  }
}
References v8::internal::CodeStubAssembler::AllocateFixedArray(), CAST, v8::internal::compiler::CodeAssembler::ChangeInt32ToIntPtr(), v8::internal::CodeStubAssembler::CopyFixedArrayElements(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::FixedArray::kMaxLength, v8::internal::length, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::compiler::CodeAssembler::TailCallBuiltin(), v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::compiler::CodeAssembler::WordNotEqual().
Referenced by CallOrConstructWithArrayLike(), and CallOrConstructWithSpread().
CallOrConstructWithArrayLike()
void v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithArrayLike (TNode< JSAny > target, std::optional< TNode< Object >> new_target, TNode< Object > arguments_list, TNode< Context > context)
Definition at line 165 of file builtins-call-gen.cc.
                                                          {
  Label if_done(this), if_arguments(this), if_array(this),
      if_holey_array(this, Label::kDeferred),
      if_runtime(this, Label::kDeferred);
  // Perform appropriate checks on {target} (and {new_target} first).
  if (!new_target) {
    // Check that {target} is Callable.
    Label if_target_callable(this),
        if_target_not_callable(this, Label::kDeferred);
    GotoIf(TaggedIsSmi(target), &if_target_not_callable);
    Branch(IsCallable(CAST(target)), &if_target_callable,
           &if_target_not_callable);
    BIND(&if_target_not_callable);
    {
      CallRuntime(Runtime::kThrowApplyNonFunction, context, target);
      Unreachable();
    }
    BIND(&if_target_callable);
  } else {
    // Check that {target} is a Constructor.
    Label if_target_constructor(this),
        if_target_not_constructor(this, Label::kDeferred);
    GotoIf(TaggedIsSmi(target), &if_target_not_constructor);
    Branch(IsConstructor(CAST(target)), &if_target_constructor,
           &if_target_not_constructor);
    BIND(&if_target_not_constructor);
    {
      CallRuntime(Runtime::kThrowNotConstructor, context, target);
      Unreachable();
    }
    BIND(&if_target_constructor);
    // Check that {new_target} is a Constructor.
    Label if_new_target_constructor(this),
        if_new_target_not_constructor(this, Label::kDeferred);
    GotoIf(TaggedIsSmi(*new_target), &if_new_target_not_constructor);
    Branch(IsConstructor(CAST(*new_target)), &if_new_target_constructor,
           &if_new_target_not_constructor);
    BIND(&if_new_target_not_constructor);
    {
      CallRuntime(Runtime::kThrowNotConstructor, context, *new_target);
      Unreachable();
    }
    BIND(&if_new_target_constructor);
  }
  GotoIf(TaggedIsSmi(arguments_list), &if_runtime);
  TNode<Map> arguments_list_map = LoadMap(CAST(arguments_list));
  TNode<NativeContext> native_context = LoadNativeContext(context);
  // Check if {arguments_list} is an (unmodified) arguments object.
  TNode<Map> sloppy_arguments_map = CAST(LoadContextElementNoCell(
      native_context, Context::SLOPPY_ARGUMENTS_MAP_INDEX));
  GotoIf(TaggedEqual(arguments_list_map, sloppy_arguments_map), &if_arguments);
  TNode<Map> strict_arguments_map = CAST(LoadContextElementNoCell(
      native_context, Context::STRICT_ARGUMENTS_MAP_INDEX));
  GotoIf(TaggedEqual(arguments_list_map, strict_arguments_map), &if_arguments);
  // Check if {arguments_list} is a fast JSArray.
  Branch(IsJSArrayMap(arguments_list_map), &if_array, &if_runtime);
  TVARIABLE(FixedArrayBase, var_elements);
  TVARIABLE(Int32T, var_length);
  BIND(&if_array);
  {
    TNode<Int32T> kind = LoadMapElementsKind(arguments_list_map);
    GotoIf(
        IsElementsKindGreaterThan(kind, LAST_ANY_NONEXTENSIBLE_ELEMENTS_KIND),
        &if_runtime);
    TNode<JSObject> js_object = CAST(arguments_list);
    // Try to extract the elements from a JSArray object.
    var_elements = LoadElements(js_object);
    var_length =
        LoadAndUntagToWord32ObjectField(js_object, JSArray::kLengthOffset);
    // Holey arrays and double backing stores need special treatment.
    static_assert(PACKED_SMI_ELEMENTS == 0);
    static_assert(HOLEY_SMI_ELEMENTS == 1);
    static_assert(PACKED_ELEMENTS == 2);
    static_assert(HOLEY_ELEMENTS == 3);
    static_assert(PACKED_DOUBLE_ELEMENTS == 4);
    static_assert(HOLEY_DOUBLE_ELEMENTS == 5);
    static_assert(LAST_FAST_ELEMENTS_KIND == HOLEY_DOUBLE_ELEMENTS);
    Branch(Word32And(kind, Int32Constant(1)), &if_holey_array, &if_done);
  }
  BIND(&if_holey_array);
  {
    // For holey JSArrays we need to check that the array prototype chain
    // protector is intact and our prototype is the Array.prototype actually.
    GotoIfNot(IsPrototypeInitialArrayPrototype(context, arguments_list_map),
              &if_runtime);
    Branch(IsNoElementsProtectorCellInvalid(), &if_runtime, &if_done);
  }
  BIND(&if_arguments);
  {
    TNode<JSArgumentsObject> js_arguments = CAST(arguments_list);
    // Try to extract the elements from a JSArgumentsObject with standard map.
    TNode<Object> length = LoadJSArgumentsObjectLength(context, js_arguments);
    TNode<FixedArrayBase> elements = LoadElements(js_arguments);
    TNode<Smi> elements_length = LoadFixedArrayBaseLength(elements);
    GotoIfNot(TaggedEqual(length, elements_length), &if_runtime);
    var_elements = elements;
    var_length = SmiToInt32(CAST(length));
    Goto(&if_done);
  }
  BIND(&if_runtime);
  {
    // Ask the runtime to create the list (actually a FixedArray).
    var_elements = CAST(CallRuntime(Runtime::kCreateListFromArrayLike, context,
                                    arguments_list));
    var_length = LoadAndUntagToWord32ObjectField(var_elements.value(),
                                                 offsetof(FixedArray, length_));
    Goto(&if_done);
  }
  // Tail call to the appropriate builtin (depending on whether we have
  // a {new_target} passed).
  BIND(&if_done);
  {
    Label if_not_double(this), if_double(this);
    TNode<Int32T> args_count =
        Int32Constant(i::JSParameterCount(0)); // args already on the stack
    TNode<Int32T> length = var_length.value();
    {
      Label normalize_done(this);
      CSA_DCHECK(this, Int32LessThanOrEqual(
                           length, Int32Constant(FixedArray::kMaxLength)));
      GotoIfNot(Word32Equal(length, Int32Constant(0)), &normalize_done);
      // Make sure we don't accidentally pass along the
      // empty_fixed_double_array since the tailed-called stubs cannot handle
      // the normalization yet.
      var_elements = EmptyFixedArrayConstant();
      Goto(&normalize_done);
      BIND(&normalize_done);
    }
    TNode<FixedArrayBase> elements = var_elements.value();
    Branch(IsFixedDoubleArray(elements), &if_double, &if_not_double);
    BIND(&if_not_double);
    {
      if (!new_target) {
        TailCallBuiltin(Builtin::kCallVarargs, context, target, args_count,
                        length, elements);
      } else {
        TailCallBuiltin(Builtin::kConstructVarargs, context, target,
                        *new_target, args_count, length, elements);
      }
    }
    BIND(&if_double);
    {
      // Kind is hardcoded here because CreateListFromArrayLike will only
      // produce holey double arrays.
      CallOrConstructDoubleVarargs(target, new_target, CAST(elements), length,
                                   args_count, context,
                                   Int32Constant(HOLEY_DOUBLE_ELEMENTS));
    }
  }
}
References v8::internal::compiler::CodeAssembler::Branch(), CallOrConstructDoubleVarargs(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::HOLEY_DOUBLE_ELEMENTS, v8::internal::HOLEY_ELEMENTS, v8::internal::HOLEY_SMI_ELEMENTS, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::CodeStubAssembler::IsCallable(), v8::internal::CodeStubAssembler::IsConstructor(), v8::internal::CodeStubAssembler::IsElementsKindGreaterThan(), v8::internal::CodeStubAssembler::IsJSArrayMap(), v8::internal::CodeStubAssembler::IsNoElementsProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsPrototypeInitialArrayPrototype(), v8::internal::JSParameterCount(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::FixedArray::kMaxLength, v8::internal::LAST_ANY_NONEXTENSIBLE_ELEMENTS_KIND, v8::internal::LAST_FAST_ELEMENTS_KIND, v8::internal::length, v8::internal::CodeStubAssembler::LoadAndUntagToWord32ObjectField(), v8::internal::CodeStubAssembler::LoadElements(), v8::internal::CodeStubAssembler::LoadFixedArrayBaseLength(), v8::internal::CodeStubAssembler::LoadJSArgumentsObjectLength(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapElementsKind(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::native_context, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, v8::internal::CodeStubAssembler::SmiToInt32(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::compiler::CodeAssembler::TailCallBuiltin(), v8::internal::compiler::CodeAssembler::Unreachable(), v8::internal::compiler::CodeAssembler::Word32And(), and v8::internal::compiler::CodeAssembler::Word32Equal().
CallOrConstructWithSpread()
void v8::internal::CallOrConstructBuiltinsAssembler::CallOrConstructWithSpread (TNode< JSAny > target, std::optional< TNode< Object >> new_target, TNode< JSAny > spread, TNode< Int32T > args_count, TNode< Context > context)
Definition at line 368 of file builtins-call-gen.cc.
                                                                           {
  Label if_smiorobject(this), if_double(this),
      if_generic(this, Label::kDeferred);
  TVARIABLE(JSArray, var_js_array);
  TVARIABLE(FixedArrayBase, var_elements);
  TVARIABLE(Int32T, var_elements_kind);
  GotoIf(TaggedIsSmi(spread), &if_generic);
  TNode<Map> spread_map = LoadMap(CAST(spread));
  GotoIfNot(IsJSArrayMap(spread_map), &if_generic);
  TNode<JSArray> spread_array = CAST(spread);
  // Check that we have the original Array.prototype.
  GotoIfNot(IsPrototypeInitialArrayPrototype(context, spread_map), &if_generic);
  // Check that there are no elements on the Array.prototype chain.
  GotoIf(IsNoElementsProtectorCellInvalid(), &if_generic);
  // Check that the Array.prototype hasn't been modified in a way that would
  // affect iteration.
  TNode<PropertyCell> protector_cell = ArrayIteratorProtectorConstant();
  GotoIf(
      TaggedEqual(LoadObjectField(protector_cell, PropertyCell::kValueOffset),
                  SmiConstant(Protectors::kProtectorInvalid)),
      &if_generic);
  {
    // The fast-path accesses the {spread} elements directly.
    TNode<Int32T> spread_kind = LoadMapElementsKind(spread_map);
    var_js_array = spread_array;
    var_elements_kind = spread_kind;
    var_elements = LoadElements(spread_array);
    // Check elements kind of {spread}.
    GotoIf(IsElementsKindLessThanOrEqual(spread_kind, HOLEY_ELEMENTS),
           &if_smiorobject);
    GotoIf(IsElementsKindLessThanOrEqual(spread_kind, LAST_FAST_ELEMENTS_KIND),
           &if_double);
    Branch(IsElementsKindLessThanOrEqual(spread_kind,
                                         LAST_ANY_NONEXTENSIBLE_ELEMENTS_KIND),
           &if_smiorobject, &if_generic);
  }
  BIND(&if_generic);
  {
    Label if_iterator_fn_not_callable(this, Label::kDeferred),
        if_iterator_is_null_or_undefined(this, Label::kDeferred),
        throw_spread_error(this, Label::kDeferred);
    TVARIABLE(Smi, message_id);
    GotoIf(IsNullOrUndefined(spread), &if_iterator_is_null_or_undefined);
    TNode<Object> iterator_fn =
        GetProperty(context, spread, IteratorSymbolConstant());
    GotoIfNot(TaggedIsCallable(iterator_fn), &if_iterator_fn_not_callable);
    TNode<JSArray> list =
        CAST(CallBuiltin(Builtin::kIterableToListMayPreserveHoles, context,
                         spread, iterator_fn));
    var_js_array = list;
    var_elements = LoadElements(list);
    var_elements_kind = LoadElementsKind(list);
    Branch(Int32LessThan(var_elements_kind.value(),
                         Int32Constant(PACKED_DOUBLE_ELEMENTS)),
           &if_smiorobject, &if_double);
    BIND(&if_iterator_fn_not_callable);
    message_id = SmiConstant(
        static_cast<int>(MessageTemplate::kSpreadIteratorSymbolNonCallable)),
    Goto(&throw_spread_error);
    BIND(&if_iterator_is_null_or_undefined);
    message_id = SmiConstant(
        static_cast<int>(MessageTemplate::kNotIterableNoSymbolLoad));
    Goto(&throw_spread_error);
    BIND(&throw_spread_error);
    CallRuntime(Runtime::kThrowSpreadArgError, context, message_id.value(),
                spread);
    Unreachable();
  }
  BIND(&if_smiorobject);
  {
    TNode<Int32T> length = LoadAndUntagToWord32ObjectField(
        var_js_array.value(), JSArray::kLengthOffset);
    TNode<FixedArrayBase> elements = var_elements.value();
    CSA_DCHECK(this, Int32LessThanOrEqual(
                         length, Int32Constant(FixedArray::kMaxLength)));
    if (!new_target) {
      TailCallBuiltin(Builtin::kCallVarargs, context, target, args_count,
                      length, elements);
    } else {
      TailCallBuiltin(Builtin::kConstructVarargs, context, target, *new_target,
                      args_count, length, elements);
    }
  }
  BIND(&if_double);
  {
    TNode<Int32T> length = LoadAndUntagToWord32ObjectField(
        var_js_array.value(), JSArray::kLengthOffset);
    GotoIf(Word32Equal(length, Int32Constant(0)), &if_smiorobject);
    CallOrConstructDoubleVarargs(target, new_target, CAST(var_elements.value()),
                                 length, args_count, context,
                                 var_elements_kind.value());
  }
}
References v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::CallBuiltin(), CallOrConstructDoubleVarargs(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, v8::internal::CodeStubAssembler::GetProperty(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::HOLEY_ELEMENTS, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::CodeStubAssembler::IsElementsKindLessThanOrEqual(), v8::internal::CodeStubAssembler::IsJSArrayMap(), v8::internal::CodeStubAssembler::IsNoElementsProtectorCellInvalid(), v8::internal::CodeStubAssembler::IsNullOrUndefined(), v8::internal::CodeStubAssembler::IsPrototypeInitialArrayPrototype(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::FixedArray::kMaxLength, v8::internal::Protectors::kProtectorInvalid, v8::internal::LAST_ANY_NONEXTENSIBLE_ELEMENTS_KIND, v8::internal::LAST_FAST_ELEMENTS_KIND, v8::internal::length, v8::internal::CodeStubAssembler::LoadAndUntagToWord32ObjectField(), v8::internal::CodeStubAssembler::LoadElements(), v8::internal::CodeStubAssembler::LoadElementsKind(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapElementsKind(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::compiler::CodeAssembler::SmiConstant(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::CodeStubAssembler::TaggedIsCallable(), v8::internal::CodeStubAssembler::TaggedIsSmi(), v8::internal::compiler::CodeAssembler::TailCallBuiltin(), v8::internal::compiler::CodeAssembler::Unreachable(), and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by BuildConstructWithSpread().
CallReceiver() [1/2]
template<class Descriptor >
void v8::internal::CallOrConstructBuiltinsAssembler::CallReceiver (Builtin id, std::optional< TNode< JSAny >> receiver = std::nullopt)
Definition at line 481 of file builtins-call-gen.cc.
                                                    {
  static_assert(
      std::is_same_v<Descriptor, CallTrampoline_Baseline_CompactDescriptor>,
      "Incompatible Descriptor");
  auto bitfield = UncheckedParameter<Word32T>(Descriptor::kBitField);
  TNode<Int32T> argc =
      Signed(DecodeWord32<
             CallTrampoline_Baseline_CompactDescriptor::ArgumentCountField>(
          bitfield));
  TNode<UintPtrT> slot = ChangeUint32ToWord(
      DecodeWord32<CallTrampoline_Baseline_CompactDescriptor::SlotField>(
          bitfield));
  CallReceiver<Descriptor>(id, argc, slot, receiver);
}
References v8::internal::compiler::CodeAssembler::ChangeUint32ToWord(), v8::internal::CodeStubAssembler::DecodeWord32(), and v8::internal::compiler::CodeAssembler::Signed().
CallReceiver() [2/2]
template<class Descriptor >
void v8::internal::CallOrConstructBuiltinsAssembler::CallReceiver (Builtin id, TNode< Int32T > argc, TNode< UintPtrT > slot, std::optional< TNode< JSAny >> maybe_receiver = std::nullopt)
Definition at line 498 of file builtins-call-gen.cc.
                                              {
  auto target = Parameter<JSAny>(Descriptor::kFunction);
  auto context = LoadContextFromBaseline();
  auto feedback_vector = LoadFeedbackVectorFromBaseline();
  LazyNode<JSAny> receiver = [=, this] {
    if (maybe_receiver) {
      return *maybe_receiver;
    } else {
      CodeStubArguments args(this, argc);
      return args.GetReceiver();
    }
  };
  CollectCallFeedback(target, receiver, context, feedback_vector, slot);
  TailCallBuiltin(id, context, target, argc);
}
References v8::base::args, v8::internal::torque::ls::kFunction, v8::internal::CodeStubAssembler::LoadContextFromBaseline(), v8::internal::CodeStubAssembler::LoadFeedbackVectorFromBaseline(), and v8::internal::compiler::CodeAssembler::TailCallBuiltin().
GetCompatibleReceiver()
TNode< JSReceiver > v8::internal::CallOrConstructBuiltinsAssembler::GetCompatibleReceiver (TNode< JSReceiver > receiver, TNode< HeapObject > signature, TNode< Context > context)
Definition at line 577 of file builtins-call-gen.cc.
                            {
  // Walk up the hidden prototype chain to find the compatible holder
  // for the {signature}, starting with the {receiver} itself.
  //
  // Be careful, these loops are hand-tuned for (close to) ideal CSA
  // code generation. Especially the sharing of the {var_template}
  // below is intentional (even though it reads a bit funny in the
  // first loop).
  TVARIABLE(HeapObject, var_holder, receiver);
  Label holder_loop(this, &var_holder), holder_found(this, &var_holder),
      holder_next(this, Label::kDeferred);
  Goto(&holder_loop);
  BIND(&holder_loop);
  {
    // Find the template to compare against the {signature}. We don't
    // bother checking that the template is a FunctionTemplateInfo here,
    // but instead do that as part of the template loop below. The only
    // thing we care about is that the template is actually a HeapObject.
    TNode<HeapObject> holder = var_holder.value();
    TVARIABLE(HeapObject, var_template, LoadMap(holder));
    Label template_map_loop(this, &var_template),
        template_loop(this, &var_template),
        template_from_closure(this, &var_template);
    Goto(&template_map_loop);
    BIND(&template_map_loop);
    {
      // Load the constructor field from the current map (in the
      // {var_template} variable), and see if that is a HeapObject.
      // If it's a Smi then it is non-instance prototype on some
      // initial map, which cannot be the case for API instances.
      TNode<Object> constructor =
          LoadObjectField(var_template.value(),
                          Map::kConstructorOrBackPointerOrNativeContextOffset);
      GotoIf(TaggedIsSmi(constructor), &holder_next);
      // Now there are three cases for {constructor} that we care
      // about here:
      //
      // 1. {constructor} is a JSFunction, and we can load the template
      // from its SharedFunctionInfo::function_data field (which
      // may not actually be a FunctionTemplateInfo).
      // 2. {constructor} is a Map, in which case it's not a constructor
      // but a back-pointer and we follow that.
      // 3. {constructor} is a FunctionTemplateInfo (or some other
      // HeapObject), in which case we can directly use that for
      // the template loop below (non-FunctionTemplateInfo objects
      // will be ruled out there).
      //
      var_template = CAST(constructor);
      TNode<Uint16T> template_type = LoadInstanceType(var_template.value());
      GotoIf(IsJSFunctionInstanceType(template_type), &template_from_closure);
      Branch(InstanceTypeEqual(template_type, MAP_TYPE), &template_map_loop,
             &template_loop);
    }
    BIND(&template_from_closure);
    {
      // The first case from above, where we load the template from the
      // SharedFunctionInfo of the closure. We only check that the
      // SharedFunctionInfo::function_data is a HeapObject and blindly
      // use that as a template, since a non-FunctionTemplateInfo objects
      // will be ruled out automatically by the template loop below.
      TNode<SharedFunctionInfo> template_shared =
          LoadObjectField<SharedFunctionInfo>(
              var_template.value(), JSFunction::kSharedFunctionInfoOffset);
      TNode<Object> template_data =
          LoadSharedFunctionInfoUntrustedFunctionData(template_shared);
      GotoIf(TaggedIsSmi(template_data), &holder_next);
      var_template = CAST(template_data);
      Goto(&template_loop);
    }
    BIND(&template_loop);
    {
      // This loop compares the template to the expected {signature},
      // following the chain of parent templates until it hits the
      // end, in which case we continue with the next holder (the
      // hidden prototype) if there's any.
      TNode<HeapObject> current = var_template.value();
      GotoIf(TaggedEqual(current, signature), &holder_found);
      GotoIfNot(IsFunctionTemplateInfoMap(LoadMap(current)), &holder_next);
      TNode<HeapObject> current_rare = LoadObjectField<HeapObject>(
          current, FunctionTemplateInfo::kRareDataOffset);
      GotoIf(IsUndefined(current_rare), &holder_next);
      var_template = LoadObjectField<HeapObject>(
          current_rare, FunctionTemplateRareData::kParentTemplateOffset);
      Goto(&template_loop);
    }
    BIND(&holder_next);
    {
      // Continue with the hidden prototype of the {holder} if it is a
      // JSGlobalProxy (the hidden prototype can either be null or a
      // JSObject in that case), or throw an illegal invocation exception,
      // since the receiver did not pass the {signature} check.
      TNode<Map> holder_map = LoadMap(holder);
      var_holder = LoadMapPrototype(holder_map);
      GotoIf(IsJSGlobalProxyMap(holder_map), &holder_loop);
      ThrowTypeError(context, MessageTemplate::kIllegalInvocation);
    }
  }
  BIND(&holder_found);
  return CAST(var_holder.value());
}
References v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::InstanceTypeEqual(), v8::internal::CodeStubAssembler::IsJSFunctionInstanceType(), v8::internal::CodeStubAssembler::IsJSGlobalProxyMap(), v8::internal::kConstructorOrBackPointerOrNativeContextOffset, v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadInstanceType(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapPrototype(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::CodeStubAssembler::TaggedIsSmi(), and v8::internal::CodeStubAssembler::ThrowTypeError().
Referenced by CallFunctionTemplate().
IsAccessCheckRequired()
constexpr bool v8::internal::CallOrConstructBuiltinsAssembler::IsAccessCheckRequired (CallFunctionTemplateMode mode) [static], [constexpr]
Definition at line 688 of file builtins-call-gen.cc.
                                   {
  switch (mode) {
    case CallFunctionTemplateMode::kGeneric:
    case CallFunctionTemplateMode::kCheckAccess:
    case CallFunctionTemplateMode::kCheckAccessAndCompatibleReceiver:
      return true;
    case CallFunctionTemplateMode::kCheckCompatibleReceiver:
      return false;
  }
}
References kCheckAccess, kCheckAccessAndCompatibleReceiver, kCheckCompatibleReceiver, kGeneric, and mode().
Referenced by CallFunctionTemplate().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-call-gen.h
/mnt/V8SourceCode/src/builtins/builtins-call-gen.cc
/mnt/V8SourceCode/src/builtins/builtins-constructor-gen.cc