cppgc::internal::RawPointer Class Reference
#include <member-storage.h>
Classes
struct AtomicInitializerTag
Public Types
using IntegralType = uintptr_t
Public Member Functions
RawPointer ()
RawPointer (const void *ptr, AtomicInitializerTag)
RawPointer (const void *ptr)
const void * Load () const
const void * LoadAtomic () const
void Store (const void *ptr)
void StoreAtomic (const void *ptr)
void Clear ()
bool IsCleared () const
bool IsSentinel () const
uintptr_t GetAsInteger () const
Static Public Member Functions
template<typename Callback >
static void VisitPossiblePointers (const void *address, Callback callback)
Static Public Attributes
static constexpr auto kWriteBarrierSlotType
Private Attributes
const void * ptr_
Friends
bool operator== (RawPointer a, RawPointer b)
bool operator!= (RawPointer a, RawPointer b)
bool operator< (RawPointer a, RawPointer b)
bool operator<= (RawPointer a, RawPointer b)
bool operator> (RawPointer a, RawPointer b)
bool operator>= (RawPointer a, RawPointer b)
Detailed Description
Definition at line 228 of file member-storage.h.
Member Typedef Documentation
IntegralType
using cppgc::internal::RawPointer::IntegralType = uintptr_t
Definition at line 232 of file member-storage.h.
Constructor & Destructor Documentation
RawPointer() [1/3]
cppgc::internal::RawPointer::RawPointer () [inline]
Definition at line 236 of file member-storage.h.
: ptr_(nullptr) {}
RawPointer() [2/3]
cppgc::internal::RawPointer::RawPointer (const void * ptr, AtomicInitializerTag) [inline], [explicit]
Definition at line 237 of file member-storage.h.
                                                                       {
    StoreAtomic(ptr);
  }
RawPointer() [3/3]
cppgc::internal::RawPointer::RawPointer (const void * ptr) [inline], [explicit]
Definition at line 240 of file member-storage.h.
: ptr_(ptr) {}
Member Function Documentation
Clear()
void cppgc::internal::RawPointer::Clear () [inline]
Definition at line 254 of file member-storage.h.
{ ptr_ = nullptr; }
GetAsInteger()
uintptr_t cppgc::internal::RawPointer::GetAsInteger () const [inline]
Definition at line 259 of file member-storage.h.
                                           {
    return reinterpret_cast<uintptr_t>(ptr_);
  }
IsCleared()
bool cppgc::internal::RawPointer::IsCleared () const [inline]
Definition at line 255 of file member-storage.h.
{ return !ptr_; }
Referenced by cppgc::internal::SameThreadEnabledCheckingPolicy< kCheckOffHeapAssignments >::CheckPointer().
IsSentinel()
bool cppgc::internal::RawPointer::IsSentinel () const [inline]
Definition at line 257 of file member-storage.h.
{ return ptr_ == kSentinelPointer; }
References cppgc::kSentinelPointer.
Referenced by cppgc::internal::SameThreadEnabledCheckingPolicy< kCheckOffHeapAssignments >::CheckPointer().
Load()
const void* cppgc::internal::RawPointer::Load () const [inline]
Definition at line 242 of file member-storage.h.
{ return ptr_; }
Referenced by cppgc::internal::DijkstraWriteBarrierPolicy::AssigningBarrier(), and cppgc::internal::SameThreadEnabledCheckingPolicy< kCheckOffHeapAssignments >::CheckPointer().
LoadAtomic()
const void* cppgc::internal::RawPointer::LoadAtomic () const [inline]
Definition at line 243 of file member-storage.h.
                                           {
    return reinterpret_cast<const std::atomic<const void*>&>(ptr_).load(
        std::memory_order_relaxed);
  }
Referenced by v8::internal::UnifiedHeapMarkingVisitorBase::VisitMultipleUncompressedMember(), cppgc::internal::MarkingVisitorBase::VisitMultipleUncompressedMember(), and cppgc::Visitor::VisitMultipleUncompressedMember().
Store()
void cppgc::internal::RawPointer::Store (const void * ptr) [inline]
Definition at line 248 of file member-storage.h.
{ ptr_ = ptr; }
StoreAtomic()
void cppgc::internal::RawPointer::StoreAtomic (const void * ptr) [inline]
Definition at line 249 of file member-storage.h.
                                              {
    reinterpret_cast<std::atomic<const void*>&>(ptr_).store(
        ptr, std::memory_order_relaxed);
  }
References store().
VisitPossiblePointers()
template<typename Callback >
static void cppgc::internal::RawPointer::VisitPossiblePointers (const void * address, Callback callback) [inline], [static]
Definition at line 283 of file member-storage.h.
                                                                 {
    // Pass along the full pointer.
    return callback(const_cast<void*>(address));
  }
Referenced by cppgc::internal::ConservativeTracingVisitor::TraceConservatively(), and cppgc::internal::ConservativeTracingVisitor::TraceConservativelyIfNeeded().
Friends And Related Function Documentation
operator!=
bool operator!= (RawPointer a, RawPointer b) [friend]
Definition at line 266 of file member-storage.h.
                                                               {
    return a.ptr_ != b.ptr_;
  }
operator<
bool operator< (RawPointer a, RawPointer b) [friend]
Definition at line 269 of file member-storage.h.
                                                              {
    return a.ptr_ < b.ptr_;
  }
operator<=
bool operator<= (RawPointer a, RawPointer b) [friend]
Definition at line 272 of file member-storage.h.
                                                               {
    return a.ptr_ <= b.ptr_;
  }
operator==
bool operator== (RawPointer a, RawPointer b) [friend]
Definition at line 263 of file member-storage.h.
                                                               {
    return a.ptr_ == b.ptr_;
  }
operator>
bool operator> (RawPointer a, RawPointer b) [friend]
Definition at line 275 of file member-storage.h.
                                                              {
    return a.ptr_ > b.ptr_;
  }
operator>=
bool operator>= (RawPointer a, RawPointer b) [friend]
Definition at line 278 of file member-storage.h.
                                                               {
    return a.ptr_ >= b.ptr_;
  }
Member Data Documentation
kWriteBarrierSlotType
constexpr auto cppgc::internal::RawPointer::kWriteBarrierSlotType [static], [constexpr]
Initial value:
=
      WriteBarrierSlotType::kUncompressed
Definition at line 233 of file member-storage.h.
ptr_
const void* cppgc::internal::RawPointer::ptr_ [private]
Definition at line 293 of file member-storage.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/cppgc/internal/member-storage.h