v8::internal::NaryOperation Class Reference
#include <ast.h>
Classes
struct NaryOperationEntry
Public Member Functions
Token::Value op () const
Expression * first () const
Expression * subsequent (size_t index) const
size_t subsequent_length () const
int subsequent_op_position (size_t index) const
void AddSubsequent (Expression *expr, int pos)
Expression * last () const
void UpdateLast (Expression *expr)
Private Types
using OperatorField = Expression::NextBitField< Token::Value, 7 >
Private Member Functions
NaryOperation (Zone *zone, Token::Value op, Expression *first, size_t initial_subsequent_size)
Private Attributes
friend Zone
Expression * first_
ZoneVector< NaryOperationEntry > subsequent_
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 1932 of file ast.h.
Member Typedef Documentation
OperatorField
using v8::internal::NaryOperation::OperatorField = Expression::NextBitField<Token::Value, 7> [private]
Definition at line 1996 of file ast.h.
Constructor & Destructor Documentation
NaryOperation()
v8::internal::NaryOperation::NaryOperation (Zone * zone, Token::Value op, Expression * first, size_t initial_subsequent_size) [inline], [private]
Definition at line 1960 of file ast.h.
      : Expression(first->position(), kNaryOperation),
        first_(first),
        subsequent_(zone) {
    bit_field_ |= OperatorField::encode(op);
    DCHECK(Token::IsBinaryOp(op));
    DCHECK_NE(op, Token::kExp);
    subsequent_.reserve(initial_subsequent_size);
  }
References v8::internal::AstNode::bit_field_, v8::internal::DCHECK(), DCHECK_NE, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Token::IsBinaryOp(), op(), and subsequent_.
Member Function Documentation
AddSubsequent()
void v8::internal::NaryOperation::AddSubsequent (Expression * expr, int pos) [inline]
Definition at line 1945 of file ast.h.
                                                {
    subsequent_.emplace_back(expr, pos);
  }
References subsequent_.
Referenced by v8::internal::Parser::CollapseNaryExpression().
first()
Expression* v8::internal::NaryOperation::first () const [inline]
Definition at line 1935 of file ast.h.
{ return first_; }
References first_.
Referenced by v8::internal::Parser::AddArrowFunctionFormalParameters(), v8::internal::interpreter::BytecodeGenerator::VisitNaryArithmeticExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryCommaExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalTest(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryNullishExpression().
last()
Expression* v8::internal::NaryOperation::last () const [inline]
Definition at line 1949 of file ast.h.
                           {
    return subsequent_[subsequent_.size() - 1].expression;
  }
References subsequent_.
Referenced by v8::internal::Parser::CollapseNaryExpression().
op()
Token::Value v8::internal::NaryOperation::op () const [inline]
Definition at line 1934 of file ast.h.
{ return OperatorField::decode(bit_field_); }
References v8::internal::AstNode::bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::Parser::AddArrowFunctionFormalParameters(), v8::internal::Parser::CollapseNaryExpression(), NaryOperation(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryArithmeticExpression().
subsequent()
Expression* v8::internal::NaryOperation::subsequent (size_t index) const [inline]
Definition at line 1936 of file ast.h.
                                             {
    return subsequent_[index].expression;
  }
References v8::internal::index, and subsequent_.
Referenced by v8::internal::Parser::AddArrowFunctionFormalParameters(), v8::internal::interpreter::BytecodeGenerator::VisitNaryArithmeticExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryCommaExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalTest(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryNullishExpression().
subsequent_length()
size_t v8::internal::NaryOperation::subsequent_length () const [inline]
Definition at line 1940 of file ast.h.
{ return subsequent_.size(); }
References subsequent_.
Referenced by v8::internal::Parser::AddArrowFunctionFormalParameters(), v8::internal::Parser::AppendNaryOperationSourceRange(), v8::internal::interpreter::BytecodeGenerator::NaryCodeCoverageSlots::NaryCodeCoverageSlots(), v8::internal::interpreter::BytecodeGenerator::VisitNaryArithmeticExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryCommaExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalAndExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalOrExpression(), v8::internal::interpreter::BytecodeGenerator::VisitNaryLogicalTest(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryNullishExpression().
subsequent_op_position()
int v8::internal::NaryOperation::subsequent_op_position (size_t index) const [inline]
Definition at line 1941 of file ast.h.
                                                 {
    return subsequent_[index].op_position;
  }
References v8::internal::index, and subsequent_.
Referenced by v8::internal::Parser::AddArrowFunctionFormalParameters(), and v8::internal::interpreter::BytecodeGenerator::VisitNaryArithmeticExpression().
UpdateLast()
void v8::internal::NaryOperation::UpdateLast (Expression * expr) [inline]
Definition at line 1952 of file ast.h.
                                    {
    subsequent_[subsequent_.size() - 1].expression = expr;
  }
References subsequent_.
Referenced by v8::internal::Parser::CollapseNaryExpression().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 1957 of file ast.h.
Member Data Documentation
first_
Expression* v8::internal::NaryOperation::first_ [private]
Definition at line 1986 of file ast.h.
Referenced by first().
subsequent_
ZoneVector<NaryOperationEntry> v8::internal::NaryOperation::subsequent_ [private]
Definition at line 1994 of file ast.h.
Referenced by AddSubsequent(), last(), NaryOperation(), subsequent(), subsequent_length(), subsequent_op_position(), and UpdateLast().
Zone
friend v8::internal::NaryOperation::Zone [private]
Definition at line 1958 of file ast.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/ast/ast.h