v8::internal::SharedFunctionInfo Class Reference
#include <shared-function-info.h>
Classes
class BodyDescriptor
class ScriptIterator
Public Types
enum Inlineability {
kHasNoScript
, kNeedsBinaryCoverage
, kIsBuiltin
, kIsNotUserCode
,
kHasNoBytecode
, kExceedsBytecodeLimit
, kMayContainBreakPoints
, kHasOptimizationDisabled
,
kIsInlineable
 }
Public Member Functions
void Init (ReadOnlyRoots roots, int unique_id)
Tagged< String > Name () const
void SetName (Tagged< String > name)
V8_EXPORT_PRIVATE Tagged< Code > GetCode (Isolate *isolate) const
Tagged< AbstractCode > abstract_code (Isolate *isolate)
V8_EXPORT_PRIVATE void SetScript (IsolateForSandbox isolate, ReadOnlyRoots roots, Tagged< HeapObject > script_object, int function_literal_id, bool reset_preparsed_scope_data=true)
void CopyFrom (Tagged< SharedFunctionInfo > other, IsolateForSandbox isolate)
Tagged< ScopeInfo > EarlyScopeInfo (AcquireLoadTag tag)
void set_raw_scope_info (Tagged< ScopeInfo > scope_info, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void SetScopeInfo (Tagged< ScopeInfo > scope_info, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
bool is_script () const
bool needs_script_context () const
V8_EXPORT_PRIVATE int EndPosition () const
V8_EXPORT_PRIVATE int StartPosition () const
V8_EXPORT_PRIVATE void UpdateFromFunctionLiteralForLiveEdit (IsolateForSandbox isolate, FunctionLiteral *lit)
bool HasOuterScopeInfo () const
Tagged< ScopeInfo > GetOuterScopeInfo () const
bool HasFeedbackMetadata () const
bool HasFeedbackMetadata (AcquireLoadTag tag) const
bool is_compiled () const
template<typename IsolateT >
IsCompiledScope is_compiled_scope (IsolateT *isolate) const
void set_internal_formal_parameter_count (int value)
uint16_t internal_formal_parameter_count_with_receiver () const
uint16_t internal_formal_parameter_count_without_receiver () const
void DontAdaptArguments ()
Tagged< Object > GetTrustedData (IsolateForSandbox isolate) const
Tagged< Object > GetUntrustedData () const
template<typename T , IndirectPointerTag tag>
Tagged< T > GetTrustedData (IsolateForSandbox isolate) const
bool HasUnpublishedTrustedData (IsolateForSandbox isolate) const
bool IsApiFunction () const
bool is_class_constructor () const
template<typename IsolateT >
Tagged< BytecodeArray > GetBytecodeArray (IsolateT *isolate) const
void set_bytecode_array (Tagged< BytecodeArray > bytecode)
void overwrite_bytecode_array (Tagged< BytecodeArray > bytecode)
Tagged< Code > InterpreterTrampoline (IsolateForSandbox isolate) const
bool HasInterpreterData (IsolateForSandbox isolate) const
Tagged< InterpreterData > interpreter_data (IsolateForSandbox isolate) const
void set_interpreter_data (Isolate *isolate, Tagged< InterpreterData > interpreter_data, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void FlushBaselineCode ()
Tagged< BytecodeArray > GetActiveBytecodeArray (IsolateForSandbox isolate) const
void SetActiveBytecodeArray (Tagged< BytecodeArray > bytecode, IsolateForSandbox isolate)
bool HasBuiltinId () const
bool HasUncompiledData (IsolateForSandbox isolate) const
Tagged< UncompiledData > uncompiled_data (IsolateForSandbox isolate) const
void set_uncompiled_data (Tagged< UncompiledData > data, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
bool HasUncompiledDataWithPreparseData (IsolateForSandbox isolate) const
Tagged< UncompiledDataWithPreparseData > uncompiled_data_with_preparse_data (IsolateForSandbox isolate) const
void set_uncompiled_data_with_preparse_data (Tagged< UncompiledDataWithPreparseData > data, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
bool HasUncompiledDataWithoutPreparseData (IsolateForSandbox isolate) const
void ClearUncompiledDataJobPointer (IsolateForSandbox isolate)
void ClearPreparseData (IsolateForSandbox isolate)
bool HasInferredName ()
bool HasDebugInfo (Isolate *isolate) const
V8_EXPORT_PRIVATE Tagged< DebugInfo > GetDebugInfo (Isolate *isolate) const
V8_EXPORT_PRIVATE std::optional< Tagged< DebugInfo > > TryGetDebugInfo (Isolate *isolate) const
V8_EXPORT_PRIVATE bool HasBreakInfo (Isolate *isolate) const
bool BreakAtEntry (Isolate *isolate) const
bool HasCoverageInfo (Isolate *isolate) const
Tagged< CoverageInfo > GetCoverageInfo (Isolate *isolate) const
std::unique_ptr< char[]> DebugNameCStr () const
bool PassesFilter (const char *raw_filter)
Tagged< HeapObject > script () const
Tagged< HeapObject > script (PtrComprCageBase cage_base) const
bool has_script (AcquireLoadTag tag) const
bool is_repl_mode () const
int function_token_position () const
bool HasSharedName () const
CachedTieringDecision cached_tiering_decision ()
void set_cached_tiering_decision (CachedTieringDecision decision)
LanguageMode language_mode () const
void set_language_mode (LanguageMode language_mode)
bool is_wrapped () const
FunctionKind kind () const
int UniqueIdInScript () const
void clear_padding ()
void UpdateFunctionMapIndex ()
bool optimization_disabled (CodeKind kind) const
bool all_optimization_disabled () const
BailoutReason disabled_optimization_reason () const
void DisableOptimization (Isolate *isolate, BailoutReason reason)
bool HasSourceCode () const
bool IsSubjectToDebugging () const
bool IsUserJavaScript () const
bool CanDiscardCompiled () const
void DiscardCompiledMetadata (Isolate *isolate, std::function< void(Tagged< HeapObject > object, ObjectSlot slot, Tagged< HeapObject > target)> gc_notify_updated_slot=[](Tagged< HeapObject > object, ObjectSlot slot, Tagged< HeapObject > target) {})
bool ShouldFlushCode (base::EnumSet< CodeFlushMode > code_flush_mode)
template<typename IsolateT >
Inlineability GetInlineability (CodeKind code_kind, IsolateT *isolate) const
int SourceSize ()
bool has_simple_parameters ()
void UpdateExpectedNofPropertiesFromEstimate (FunctionLiteral *literal)
void UpdateAndFinalizeExpectedNofPropertiesFromEstimate (FunctionLiteral *literal)
void SetFunctionTokenPosition (int function_token_position, int start_position)
bool CanCollectSourcePosition (Isolate *isolate)
template<typename IsolateT >
bool AreSourcePositionsAvailable (IsolateT *isolate) const
V8_EXPORT_PRIVATE uint32_t Hash ()
bool construct_as_builtin () const
void CalculateConstructAsBuiltin ()
uint16_t CompareExchangeAge (uint16_t expected_age, uint16_t new_age)
Static Public Member Functions
static Handle< String > DebugName (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared)
static DirectHandle< Object > GetSourceCode (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared)
static Handle< Object > GetSourceCodeHarmony (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared)
static V8_EXPORT_PRIVATE void DiscardCompiled (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared_info)
template<typename IsolateT >
static void InitFromFunctionLiteral (IsolateT *isolate, FunctionLiteral *lit, bool is_toplevel)
template<typename IsolateT >
static void CreateAndSetUncompiledData (IsolateT *isolate, FunctionLiteral *lit)
static void EnsureBytecodeArrayAvailable (Isolate *isolate, Handle< SharedFunctionInfo > shared_info, IsCompiledScope *is_compiled_scope, CreateSourcePositions flag=CreateSourcePositions::kNo)
static void EnsureSourcePositionsAvailable (Isolate *isolate, DirectHandle< SharedFunctionInfo > shared_info)
static V8_EXPORT_PRIVATE void EnsureOldForTesting (Tagged< SharedFunctionInfo > sfu)
static void InstallDebugBytecode (DirectHandle< SharedFunctionInfo > shared, Isolate *isolate)
static void UninstallDebugBytecode (Tagged< SharedFunctionInfo > shared, Isolate *isolate)
Static Public Attributes
static constexpr V8_EXPORT_PRIVATE Tagged< Smi > const kNoSharedNameSentinel
static const int kEntriesStart = 0
static const int kContextOffset = 0
static const int kCachedCodeOffset = 1
static const int kEntryLength = 2
static const int kInitialLength = kEntriesStart + kEntryLength
static const int kNotFound = -1
static constexpr int kAgeSize = kAgeOffsetEnd - kAgeOffset + 1
static constexpr uint16_t kMaxAge = UINT16_MAX
static const int kMaximumFunctionTokenOffset = kMaxUInt16 - 1
static const uint16_t kFunctionTokenOutOfRange = static_cast<uint16_t>(-1)
Private Member Functions
void SetTrustedData (Tagged< ExposedTrustedObject > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void SetUntrustedData (Tagged< Object > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
bool HasTrustedData () const
bool HasUntrustedData () const
void set_kind (FunctionKind kind)
uint16_t get_property_estimate_from_literal (FunctionLiteral *literal)
int32_t relaxed_flags () const
void set_relaxed_flags (int32_t flags)
FRIEND_TEST (PreParserTest, LazyFunctionLength)
Friends
template<typename Impl >
class FactoryBase
class V8HeapExplorer
Detailed Description
Definition at line 197 of file shared-function-info.h.
Member Enumeration Documentation
Inlineability
enum v8::internal::SharedFunctionInfo::Inlineability
Enumerator
kHasNoScript
kNeedsBinaryCoverage
kIsBuiltin
kIsNotUserCode
kHasNoBytecode
kExceedsBytecodeLimit
kMayContainBreakPoints
kHasOptimizationDisabled
kIsInlineable
Definition at line 668 of file shared-function-info.h.
                     {
    // Different reasons for not being inlineable:
    kHasNoScript,
    kNeedsBinaryCoverage,
    kIsBuiltin,
    kIsNotUserCode,
    kHasNoBytecode,
    kExceedsBytecodeLimit,
    kMayContainBreakPoints,
    kHasOptimizationDisabled,
    // Actually inlineable!
    kIsInlineable,
  };
Member Function Documentation
abstract_code()
Tagged< AbstractCode > v8::internal::SharedFunctionInfo::abstract_code (Isolate * isolate) [inline]
Definition at line 278 of file shared-function-info-inl.h.
                                                                       {
  // TODO(v8:11429): Decide if this return bytecode or baseline code, when the
  // latter is present.
  if (HasBytecodeArray(isolate)) {
    return Cast<AbstractCode>(GetBytecodeArray(isolate));
  } else {
    return Cast<AbstractCode>(GetCode(isolate));
  }
}
References GetBytecodeArray(), and GetCode().
Referenced by DisableOptimization().
all_optimization_disabled()
bool v8::internal::SharedFunctionInfo::all_optimization_disabled () const [inline]
Definition at line 408 of file shared-function-info-inl.h.
                                                         {
  return IsTerminalBailoutReason(disabled_optimization_reason());
}
References disabled_optimization_reason(), and v8::internal::IsTerminalBailoutReason().
AreSourcePositionsAvailable()
template<typename IsolateT >
bool v8::internal::SharedFunctionInfo::AreSourcePositionsAvailable (IsolateT * isolate) const
Definition at line 298 of file shared-function-info-inl.h.
                                                                            {
  if (v8_flags.enable_lazy_source_positions) {
    return !HasBytecodeArray() ||
           GetBytecodeArray(isolate)->HasSourcePositionTable();
  }
  return true;
}
References GetBytecodeArray(), and v8::internal::v8_flags.
BreakAtEntry()
bool v8::internal::SharedFunctionInfo::BreakAtEntry (Isolate * isolate) const
Definition at line 308 of file shared-function-info.cc.
                                                            {
  return isolate->debug()->BreakAtEntry(*this);
}
References v8::internal::Debug::BreakAtEntry(), and v8::internal::Isolate::debug().
cached_tiering_decision()
CachedTieringDecision v8::internal::SharedFunctionInfo::cached_tiering_decision ()
Definition at line 808 of file shared-function-info.cc.
                                                                  {
  return CachedTieringDecisionBits::decode(flags2());
}
References v8::internal::flags2.
CalculateConstructAsBuiltin()
void v8::internal::SharedFunctionInfo::CalculateConstructAsBuiltin () [inline]
Definition at line 453 of file shared-function-info-inl.h.
                                                     {
  bool uses_builtins_construct_stub = false;
  if (HasBuiltinId()) {
    Builtin id = builtin_id();
    if (id != Builtin::kCompileLazy && id != Builtin::kEmptyFunction) {
      uses_builtins_construct_stub = true;
    }
  } else if (IsApiFunction()) {
    uses_builtins_construct_stub = true;
  }
  int f = flags(kRelaxedLoad);
  f = ConstructAsBuiltinBit::update(f, uses_builtins_construct_stub);
  set_flags(f, kRelaxedStore);
}
References v8::internal::flags, HasBuiltinId(), IsApiFunction(), v8::kRelaxedLoad, and v8::kRelaxedStore.
CanCollectSourcePosition()
bool v8::internal::SharedFunctionInfo::CanCollectSourcePosition (Isolate * isolate) [inline]
Definition at line 742 of file shared-function-info-inl.h.
                                                                  {
  return v8_flags.enable_lazy_source_positions && HasBytecodeArray() &&
         !GetBytecodeArray(isolate)->HasSourcePositionTable();
}
References GetBytecodeArray(), and v8::internal::v8_flags.
CanDiscardCompiled()
bool v8::internal::SharedFunctionInfo::CanDiscardCompiled () const [inline]
Definition at line 1150 of file shared-function-info-inl.h.
                                                  {
#if V8_ENABLE_WEBASSEMBLY
  if (HasAsmWasmData()) return true;
#endif // V8_ENABLE_WEBASSEMBLY
  return HasBytecodeArray() ||
         HasUncompiledDataWithPreparseData(GetCurrentIsolateForSandbox()) ||
         HasBaselineCode();
}
References v8::internal::GetCurrentIsolateForSandbox(), and HasUncompiledDataWithPreparseData().
clear_padding()
void v8::internal::SharedFunctionInfo::clear_padding () [inline]
Definition at line 502 of file shared-function-info-inl.h.
{ set_padding(0); }
Referenced by Init().
ClearPreparseData()
void v8::internal::SharedFunctionInfo::ClearPreparseData (IsolateForSandbox isolate) [inline]
Definition at line 1055 of file shared-function-info-inl.h.
                                                                    {
  DCHECK(HasUncompiledDataWithPreparseData(isolate));
  Tagged<UncompiledDataWithPreparseData> data =
      uncompiled_data_with_preparse_data(isolate);
  // Trim off the pre-parsed scope data from the uncompiled data by swapping the
  // map, leaving only an uncompiled data without pre-parsed scope.
  DisallowGarbageCollection no_gc;
  Heap* heap = GetHeapFromWritableObject(data);
  // We are basically trimming that object to its supertype, so recorded slots
  // within the object don't need to be invalidated.
  heap->NotifyObjectLayoutChange(data, no_gc, InvalidateRecordedSlots::kNo,
                                 InvalidateExternalPointerSlots::kNo);
  static_assert(UncompiledDataWithoutPreparseData::kSize <
                UncompiledDataWithPreparseData::kSize);
  static_assert(UncompiledDataWithoutPreparseData::kSize ==
                UncompiledData::kHeaderSize);
  // Fill the remaining space with filler and clear slots in the trimmed area.
  int old_size = data->Size();
  DCHECK_LE(UncompiledDataWithPreparseData::kSize, old_size);
  heap->NotifyObjectSizeChange(data, old_size,
                               UncompiledDataWithoutPreparseData::kSize,
                               ClearRecordedSlots::kYes);
  // Swap the map.
  data->set_map(heap->isolate(),
                GetReadOnlyRoots().uncompiled_data_without_preparse_data_map(),
                kReleaseStore);
  // Ensure that the clear was successful.
  DCHECK(HasUncompiledDataWithoutPreparseData(isolate));
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::GetHeapFromWritableObject(), v8::internal::GetReadOnlyRoots(), HasUncompiledDataWithoutPreparseData(), HasUncompiledDataWithPreparseData(), v8::internal::kNo, v8::kReleaseStore, v8::internal::kYes, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and uncompiled_data_with_preparse_data().
Referenced by SetScript(), and UpdateFromFunctionLiteralForLiveEdit().
ClearUncompiledDataJobPointer()
void v8::internal::SharedFunctionInfo::ClearUncompiledDataJobPointer (IsolateForSandbox isolate) [inline]
Definition at line 1043 of file shared-function-info-inl.h.
                               {
  Tagged<UncompiledData> uncompiled_data = this->uncompiled_data(isolate);
  if (IsUncompiledDataWithPreparseDataAndJob(uncompiled_data)) {
    Cast<UncompiledDataWithPreparseDataAndJob>(uncompiled_data)
        ->set_job(kNullAddress);
  } else if (IsUncompiledDataWithoutPreparseDataWithJob(uncompiled_data)) {
    Cast<UncompiledDataWithoutPreparseDataWithJob>(uncompiled_data)
        ->set_job(kNullAddress);
  }
}
References v8::internal::kNullAddress, and uncompiled_data().
CompareExchangeAge()
uint16_t v8::internal::SharedFunctionInfo::CompareExchangeAge (uint16_t expected_age, uint16_t new_age) [inline]
Definition at line 477 of file shared-function-info-inl.h.
                                                                  {
  Address age_addr = address() + kAgeOffset;
  return base::AsAtomic16::Relaxed_CompareAndSwap(
      reinterpret_cast<base::Atomic16*>(age_addr), expected_age, new_age);
}
References v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_CompareAndSwap().
construct_as_builtin()
bool v8::internal::SharedFunctionInfo::construct_as_builtin () const [inline]
Definition at line 449 of file shared-function-info-inl.h.
                                                    {
  return ConstructAsBuiltinBit::decode(flags(kRelaxedLoad));
}
References v8::internal::flags, and v8::kRelaxedLoad.
CopyFrom()
void v8::internal::SharedFunctionInfo::CopyFrom (Tagged< SharedFunctionInfo > other, IsolateForSandbox isolate)
Definition at line 233 of file shared-function-info.cc.
                                                             {
  if (other->HasTrustedData()) {
    SetTrustedData(Cast<ExposedTrustedObject>(other->GetTrustedData(isolate)));
  } else {
    SetUntrustedData(other->GetUntrustedData());
  }
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  set_name_or_scope_info(other->name_or_scope_info(cage_base, kAcquireLoad),
                         kReleaseStore);
  set_outer_scope_info_or_feedback_metadata(
      other->outer_scope_info_or_feedback_metadata(cage_base));
  set_script(other->script(cage_base, kAcquireLoad), kReleaseStore);
  set_length(other->length());
  set_formal_parameter_count(other->formal_parameter_count());
  set_function_token_offset(other->function_token_offset());
  set_expected_nof_properties(other->expected_nof_properties());
  set_flags2(other->flags2());
  set_flags(other->flags(kRelaxedLoad), kRelaxedStore);
  set_function_literal_id(other->function_literal_id(kRelaxedLoad),
                          kRelaxedStore);
  set_unique_id(other->unique_id());
  set_age(0);
#if DEBUG
  // This should now be byte-for-byte identical to the input except for the age
  // field (could be reset concurrently). Compare content before age field now:
  DCHECK_EQ(memcmp(reinterpret_cast<void*>(address()),
                   reinterpret_cast<void*>(other.address()),
                   SharedFunctionInfo::kAgeOffset),
            0);
  // Compare content after age field.
  constexpr Address kPastAgeOffset =
      SharedFunctionInfo::kAgeOffset + SharedFunctionInfo::kAgeSize;
  DCHECK_EQ(memcmp(reinterpret_cast<void*>(address() + kPastAgeOffset),
                   reinterpret_cast<void*>(other.address() + kPastAgeOffset),
                   SharedFunctionInfo::kSize - kPastAgeOffset),
            0);
#endif
}
References v8::internal::Tagged< HeapObject >::address(), DCHECK_EQ, v8::internal::GetPtrComprCageBase(), v8::kAcquireLoad, kAgeSize, v8::kRelaxedLoad, v8::kRelaxedStore, v8::kReleaseStore, SetTrustedData(), and SetUntrustedData().
CreateAndSetUncompiledData()
template<typename IsolateT >
void v8::internal::SharedFunctionInfo::CreateAndSetUncompiledData (IsolateT * isolate, FunctionLiteral * lit) [static]
Definition at line 612 of file shared-function-info.cc.
                                                                          {
  DCHECK(!lit->shared_function_info()->HasUncompiledData(isolate));
  DirectHandle<UncompiledData> data;
  ProducedPreparseData* scope_data = lit->produced_preparse_data();
  if (scope_data != nullptr) {
    Handle<PreparseData> preparse_data = scope_data->Serialize(isolate);
    if (lit->should_parallel_compile()) {
      data = isolate->factory()->NewUncompiledDataWithPreparseDataAndJob(
          lit->GetInferredName(isolate), lit->start_position(),
          lit->end_position(), preparse_data);
    } else {
      data = isolate->factory()->NewUncompiledDataWithPreparseData(
          lit->GetInferredName(isolate), lit->start_position(),
          lit->end_position(), preparse_data);
    }
  } else {
    if (lit->should_parallel_compile()) {
      data = isolate->factory()->NewUncompiledDataWithoutPreparseDataWithJob(
          lit->GetInferredName(isolate), lit->start_position(),
          lit->end_position());
    } else {
      data = isolate->factory()->NewUncompiledDataWithoutPreparseData(
          lit->GetInferredName(isolate), lit->start_position(),
          lit->end_position());
    }
  }
  lit->shared_function_info()->set_uncompiled_data(*data);
}
References v8::internal::DCHECK(), v8::internal::FunctionLiteral::end_position(), v8::internal::FunctionLiteral::GetInferredName(), v8::internal::FunctionLiteral::produced_preparse_data(), v8::internal::ProducedPreparseData::Serialize(), v8::internal::FunctionLiteral::shared_function_info(), v8::internal::FunctionLiteral::should_parallel_compile(), and v8::internal::FunctionLiteral::start_position().
Referenced by InitFromFunctionLiteral(), and v8::internal::anonymous_namespace{compiler.cc}::IterativelyExecuteAndFinalizeUnoptimizedCompilationJobs().
DebugName()
Handle< String > v8::internal::SharedFunctionInfo::DebugName (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared) [static]
Definition at line 336 of file shared-function-info.cc.
                                                               {
#if V8_ENABLE_WEBASSEMBLY
  if (shared->HasWasmExportedFunctionData(isolate)) {
    return isolate->factory()
        ->NewStringFromUtf8(base::CStrVector(shared->DebugNameCStr().get()))
        .ToHandleChecked();
  }
#endif // V8_ENABLE_WEBASSEMBLY
  FunctionKind function_kind = shared->kind();
  if (IsClassMembersInitializerFunction(function_kind)) {
    return function_kind == FunctionKind::kClassMembersInitializerFunction
               ? isolate->factory()->instance_members_initializer_string()
               : isolate->factory()->static_initializer_string();
  }
  DisallowHeapAllocation no_gc;
  Tagged<String> function_name = shared->Name();
  if (function_name->length() == 0) function_name = shared->inferred_name();
  return handle(function_name, isolate);
}
References v8::base::CStrVector(), v8::internal::Isolate::factory(), v8::internal::handle(), v8::internal::IsClassMembersInitializerFunction(), v8::internal::kClassMembersInitializerFunction, v8::internal::Factory::NewStringFromUtf8(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::Coverage::Collect(), v8::internal::anonymous_namespace{runtime-classes.cc}::DefineClass(), v8::internal::anonymous_namespace{call-site-info.cc}::FormatEvalOrigin(), v8::internal::anonymous_namespace{js-objects.cc}::GetConstructorHelper(), v8::internal::JSFunction::GetDebugName(), v8::internal::CodeDataSourceIncrementalState::InternJsFunction(), v8::internal::anonymous_namespace{runtime-compiler.cc}::LogExecution(), v8::internal::ExistingCodeLogger::LogExistingFunction(), v8::internal::Compiler::LogFunctionCompilation(), and v8::internal::JSFunction::SetInitialMap().
DebugNameCStr()
std::unique_ptr< char[]> v8::internal::SharedFunctionInfo::DebugNameCStr () const
Definition at line 322 of file shared-function-info.cc.
                                                              {
#if V8_ENABLE_WEBASSEMBLY
  if (HasWasmExportedFunctionData(GetCurrentIsolateForSandbox())) {
    return WasmExportedFunction::GetDebugName(
        wasm_exported_function_data()->sig());
  }
#endif // V8_ENABLE_WEBASSEMBLY
  DisallowGarbageCollection no_gc;
  Tagged<String> function_name = Name();
  if (function_name->length() == 0) function_name = inferred_name();
  return function_name->ToCString();
}
References v8::internal::GetCurrentIsolateForSandbox(), v8::internal::WasmExportedFunction::GetDebugName(), Name(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::sig.
Referenced by PassesFilter().
disabled_optimization_reason()
BailoutReason v8::internal::SharedFunctionInfo::disabled_optimization_reason () const [inline]
Definition at line 412 of file shared-function-info-inl.h.
                                                                     {
  return DisabledOptimizationReasonBits::decode(flags(kRelaxedLoad));
}
References v8::internal::flags, and v8::kRelaxedLoad.
Referenced by all_optimization_disabled().
DisableOptimization()
void v8::internal::SharedFunctionInfo::DisableOptimization (Isolate * isolate, BailoutReason reason)
Definition at line 519 of file shared-function-info.cc.
                                                                   {
  DCHECK_NE(reason, BailoutReason::kNoReason);
  set_flags(DisabledOptimizationReasonBits::update(flags(kRelaxedLoad), reason),
            kRelaxedStore);
  // Code should be the lazy compilation stub or else interpreted.
  if constexpr (DEBUG_BOOL) {
    CodeKind kind = abstract_code(isolate)->kind(isolate);
    CHECK(kind == CodeKind::INTERPRETED_FUNCTION || kind == CodeKind::BUILTIN);
  }
  PROFILE(isolate,
          CodeDisableOptEvent(direct_handle(abstract_code(isolate), isolate),
                              direct_handle(*this, isolate)));
  if (v8_flags.trace_opt) {
    CodeTracer::Scope scope(isolate->GetCodeTracer());
    PrintF(scope.file(), "[disabled optimization for ");
    ShortPrint(*this, scope.file());
    PrintF(scope.file(), ", reason: %s]\n", GetBailoutReason(reason));
  }
}
References abstract_code(), BUILTIN, CHECK, DCHECK_NE, DEBUG_BOOL, v8::internal::direct_handle(), v8::internal::CodeTracer::Scope::file(), v8::internal::flags, v8::internal::GetBailoutReason(), v8::internal::Isolate::GetCodeTracer(), kind(), v8::kRelaxedLoad, v8::kRelaxedStore, v8::internal::PrintF(), PROFILE, v8::internal::ShortPrint(), and v8::internal::v8_flags.
DiscardCompiled()
void v8::internal::SharedFunctionInfo::DiscardCompiled (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared_info) [static]
Definition at line 410 of file shared-function-info.cc.
                                                                    {
  DCHECK(shared_info->CanDiscardCompiled());
  Handle<String> inferred_name_val(shared_info->inferred_name(), isolate);
  int start_position = shared_info->StartPosition();
  int end_position = shared_info->EndPosition();
  MaybeDirectHandle<UncompiledData> data;
  if (!shared_info->HasUncompiledDataWithPreparseData(isolate)) {
    // Create a new UncompiledData, without pre-parsed scope.
    data = isolate->factory()->NewUncompiledDataWithoutPreparseData(
        inferred_name_val, start_position, end_position);
  }
  // If the GC runs after changing one but not both fields below, it could see
  // the SharedFunctionInfo in an unexpected state.
  DisallowGarbageCollection no_gc;
  shared_info->DiscardCompiledMetadata(isolate);
  // Replace compiled data with a new UncompiledData object.
  if (shared_info->HasUncompiledDataWithPreparseData(isolate)) {
    // If this is uncompiled data with a pre-parsed scope data, we can just
    // clear out the scope data and keep the uncompiled data.
    shared_info->ClearPreparseData(isolate);
    DCHECK(data.is_null());
  } else {
    // Update the function data to point to the UncompiledData without preparse
    // data created above. Use the raw function data setter to avoid validity
    // checks, since we're performing the unusual task of decompiling.
    shared_info->SetTrustedData(*data.ToHandleChecked());
  }
}
References v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::internal::MaybeDirectHandle< T >::is_null(), v8::internal::FactoryBase< Impl >::NewUncompiledDataWithoutPreparseData(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::MaybeDirectHandle< T >::ToHandleChecked().
Referenced by v8::internal::Snapshot::ClearReconstructableDataForSerialization(), and v8::internal::RUNTIME_FUNCTION().
DiscardCompiledMetadata()
void v8::internal::SharedFunctionInfo::DiscardCompiledMetadata (Isolate * isolate, std::function< void(Tagged< HeapObject > object, ObjectSlot slot, Tagged< HeapObject > target)> gc_notify_updated_slot = [](Tagged<HeapObject> object, ObjectSlot slot, Tagged<HeapObject> target) {})
Definition at line 374 of file shared-function-info.cc.
                                {
  DisallowGarbageCollection no_gc;
  if (HasFeedbackMetadata()) {
    if (v8_flags.trace_flush_code) {
      CodeTracer::Scope scope(isolate->GetCodeTracer());
      PrintF(scope.file(), "[discarding compiled metadata for ");
      ShortPrint(*this, scope.file());
      PrintF(scope.file(), "]\n");
    }
    Tagged<HeapObject> outer_scope_info;
    if (scope_info()->HasOuterScopeInfo()) {
      outer_scope_info = scope_info()->OuterScopeInfo();
    } else {
      outer_scope_info = ReadOnlyRoots(isolate).the_hole_value();
    }
    // Raw setter to avoid validity checks, since we're performing the unusual
    // task of decompiling.
    set_raw_outer_scope_info_or_feedback_metadata(outer_scope_info);
    gc_notify_updated_slot(
        *this,
        RawField(SharedFunctionInfo::kOuterScopeInfoOrFeedbackMetadataOffset),
        outer_scope_info);
  } else {
    DCHECK(IsScopeInfo(outer_scope_info()) || IsTheHole(outer_scope_info()));
  }
  // TODO(rmcilroy): Possibly discard ScopeInfo here as well.
}
References v8::internal::DCHECK(), v8::internal::CodeTracer::Scope::file(), v8::internal::Isolate::GetCodeTracer(), HasFeedbackMetadata(), HasOuterScopeInfo(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::PrintF(), v8::internal::ShortPrint(), and v8::internal::v8_flags.
DontAdaptArguments()
void v8::internal::SharedFunctionInfo::DontAdaptArguments () [inline]
Definition at line 510 of file shared-function-info-inl.h.
                                            {
#if V8_ENABLE_WEBASSEMBLY
  // TODO(leszeks): Revise this DCHECK now that the code field is gone.
  DCHECK(!HasWasmExportedFunctionData(GetCurrentIsolateForSandbox()));
#endif // V8_ENABLE_WEBASSEMBLY
  if (HasBuiltinId()) {
    Builtin builtin = builtin_id();
    if (Builtins::KindOf(builtin) == Builtins::TFJ) {
      const int formal_parameter_count =
          Builtins::GetStackParameterCount(builtin);
      // If we have `kDontAdaptArgumentsSentinel` or no arguments, then we are
      // good. Otherwise this is a mismatch.
      if (formal_parameter_count != kDontAdaptArgumentsSentinel &&
          formal_parameter_count != JSParameterCount(0)) {
        FATAL(
            "Conflicting argument adaptation configuration (SFI vs call "
            "descriptor) for builtin: %s (%d)",
            Builtins::name(builtin), static_cast<int>(builtin));
      }
    }
  }
  TorqueGeneratedClass::set_formal_parameter_count(kDontAdaptArgumentsSentinel);
}
References v8::internal::DCHECK(), FATAL, v8::internal::GetCurrentIsolateForSandbox(), v8::internal::Builtins::GetStackParameterCount(), HasBuiltinId(), v8::internal::JSParameterCount(), v8::internal::kDontAdaptArgumentsSentinel, v8::internal::Builtins::KindOf(), v8::internal::Builtins::name(), and v8::internal::Builtins::TFJ.
EarlyScopeInfo()
Tagged< ScopeInfo > v8::internal::SharedFunctionInfo::EarlyScopeInfo (AcquireLoadTag tag) [inline]
Definition at line 546 of file shared-function-info-inl.h.
                                                                       {
  // Keep in sync with the scope_info getter above.
  PtrComprCageBase cage_base = GetPtrComprCageBase(*this);
  Tagged<Object> maybe_scope_info = name_or_scope_info(cage_base, tag);
  if (IsScopeInfo(maybe_scope_info, cage_base)) {
    return Cast<ScopeInfo>(maybe_scope_info);
  }
  return EarlyGetReadOnlyRoots().empty_scope_info();
}
References v8::internal::GetPtrComprCageBase().
EndPosition()
int v8::internal::SharedFunctionInfo::EndPosition () const
Definition at line 743 of file shared-function-info.cc.
                                          {
  Tagged<Object> maybe_scope_info = name_or_scope_info(kAcquireLoad);
  if (IsScopeInfo(maybe_scope_info)) {
    Tagged<ScopeInfo> info = Cast<ScopeInfo>(maybe_scope_info);
    if (info->HasPositionInfo()) {
      return info->EndPosition();
    }
  }
  IsolateForSandbox isolate = GetCurrentIsolateForSandbox();
  if (HasUncompiledData(isolate)) {
    // Works with or without scope.
    return uncompiled_data(isolate)->end_position();
  }
  if (IsApiFunction() || HasBuiltinId()) {
    DCHECK_IMPLIES(HasBuiltinId(), builtin_id() != Builtin::kCompileLazy);
    return 0;
  }
#if V8_ENABLE_WEBASSEMBLY
  if (HasWasmExportedFunctionData(isolate)) {
    Tagged<WasmTrustedInstanceData> instance_data =
        wasm_exported_function_data()->instance_data();
    int func_index = wasm_exported_function_data()->function_index();
    auto& function = instance_data->module()->functions[func_index];
    return static_cast<int>(function.code.end_offset());
  }
#endif // V8_ENABLE_WEBASSEMBLY
  return kNoSourcePosition;
}
References DCHECK_IMPLIES, v8::internal::GetCurrentIsolateForSandbox(), HasBuiltinId(), HasUncompiledData(), v8::internal::instance_data, IsApiFunction(), v8::kAcquireLoad, v8::internal::kNoSourcePosition, and uncompiled_data().
Referenced by SourceSize().
EnsureBytecodeArrayAvailable()
void v8::internal::SharedFunctionInfo::EnsureBytecodeArrayAvailable (Isolate * isolate, Handle< SharedFunctionInfo > shared_info, IsCompiledScope * is_compiled_scope, CreateSourcePositions flag = CreateSourcePositions::kNo) [static]
Definition at line 818 of file shared-function-info.cc.
                                                                    {
  if (!shared_info->HasBytecodeArray()) {
    if (!Compiler::Compile(isolate, shared_info, Compiler::CLEAR_EXCEPTION,
                           is_compiled_scope, flag)) {
      FATAL("Failed to compile shared info that was already compiled before");
    }
    DCHECK(shared_info->GetBytecodeArray(isolate)->HasSourcePositionTable());
  } else {
    *is_compiled_scope = shared_info->is_compiled_scope(isolate);
  }
}
References v8::internal::Compiler::CLEAR_EXCEPTION, v8::internal::Compiler::Compile(), v8::internal::DCHECK(), FATAL, and is_compiled_scope().
Referenced by v8::internal::JSMessageObject::InitializeSourcePositions().
EnsureOldForTesting()
void v8::internal::SharedFunctionInfo::EnsureOldForTesting (Tagged< SharedFunctionInfo > sfu) [static]
Definition at line 879 of file shared-function-info.cc.
                                                                           {
  if (v8_flags.flush_code_based_on_time ||
      v8_flags.flush_code_based_on_tab_visibility) {
    sfi->set_age(kMaxAge);
  } else {
    sfi->set_age(v8_flags.bytecode_old_age);
  }
}
References kMaxAge, and v8::internal::v8_flags.
EnsureSourcePositionsAvailable()
void v8::internal::SharedFunctionInfo::EnsureSourcePositionsAvailable (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared_info) [static]
Definition at line 833 of file shared-function-info.cc.
                                                                    {
  if (shared_info->CanCollectSourcePosition(isolate)) {
    std::optional<Isolate::ExceptionScope> exception_scope;
    if (isolate->has_exception()) {
      exception_scope.emplace(isolate);
    }
    Compiler::CollectSourcePositions(isolate, shared_info);
  }
}
References v8::internal::Compiler::CollectSourcePositions(), and v8::internal::Isolate::has_exception().
Referenced by v8::internal::Isolate::CollectSourcePositionsForAllBytecodeArrays(), v8::internal::BackgroundMergeTask::CompleteMergeInForeground(), v8::internal::anonymous_namespace{messages.cc}::ComputeLocation(), v8::internal::CallSiteInfo::ComputeSourcePosition(), v8::internal::Debug::CreateBreakInfo(), v8::internal::FrameSummary::JavaScriptFrameSummary::CreateStackFrameInfo(), v8::internal::FrameSummary::JavaScriptFrameSummary::EnsureSourcePositionsAvailable(), v8::internal::anonymous_namespace{code-serializer.cc}::FinalizeDeserialization(), v8::internal::anonymous_namespace{compiler.cc}::FinalizeUnoptimizedCompilation(), v8::internal::Isolate::GetAbstractPC(), v8::internal::Script::GetEvalPosition(), v8::internal::ScopeIterator::GetSourcePosition(), v8::internal::StackFrameInfo::GetSourcePosition(), v8::internal::JSMessageObject::InitializeSourcePositions(), v8::internal::ExistingCodeLogger::LogCompiledFunctions(), v8::internal::LiveEdit::PatchScript(), v8::internal::compiler::PipelineCompilationJob::PrepareJobImpl(), v8::internal::JavaScriptFrame::Print(), and v8::debug::GeneratorObject::SuspendedLocation().
FlushBaselineCode()
void v8::internal::SharedFunctionInfo::FlushBaselineCode () [inline]
Definition at line 887 of file shared-function-info-inl.h.
                                           {
  DCHECK(HasBaselineCode());
  Tagged<TrustedObject> new_data =
      baseline_code(kAcquireLoad)->bytecode_or_interpreter_data();
  DCHECK(IsBytecodeArray(new_data) || IsInterpreterData(new_data));
  SetTrustedData(Cast<ExposedTrustedObject>(new_data));
}
References v8::internal::DCHECK(), v8::kAcquireLoad, and SetTrustedData().
FRIEND_TEST()
v8::internal::SharedFunctionInfo::FRIEND_TEST (PreParserTest , LazyFunctionLength) [private]
function_token_position()
int v8::internal::SharedFunctionInfo::function_token_position () const [inline]
Definition at line 288 of file shared-function-info-inl.h.
                                                      {
  int offset = raw_function_token_offset();
  if (offset == kFunctionTokenOutOfRange) {
    return kNoSourcePosition;
  } else {
    return StartPosition() - offset;
  }
}
References kFunctionTokenOutOfRange, v8::internal::kNoSourcePosition, and StartPosition().
Referenced by SetFunctionTokenPosition().
get_property_estimate_from_literal()
uint16_t v8::internal::SharedFunctionInfo::get_property_estimate_from_literal (FunctionLiteral * literal) [inline], [private]
Referenced by UpdateAndFinalizeExpectedNofPropertiesFromEstimate(), and UpdateExpectedNofPropertiesFromEstimate().
GetActiveBytecodeArray()
Tagged< BytecodeArray > v8::internal::SharedFunctionInfo::GetActiveBytecodeArray (IsolateForSandbox isolate) const [inline]
Definition at line 785 of file shared-function-info-inl.h.
                                     {
  Tagged<Object> data = GetTrustedData(isolate);
  if (IsCode(data)) {
    Tagged<Code> baseline_code = Cast<Code>(data);
    data = baseline_code->bytecode_or_interpreter_data();
  }
  if (IsBytecodeArray(data)) {
    return Cast<BytecodeArray>(data);
  } else {
    // We need an explicit check here since we use the
    // kUnknownIndirectPointerTag above and so don't have any type guarantees.
    SBXCHECK(IsInterpreterData(data));
    return Cast<InterpreterData>(data)->bytecode_array();
  }
}
References GetTrustedData(), and SBXCHECK.
Referenced by GetBytecodeArray().
GetBytecodeArray()
template<typename IsolateT >
Tagged< BytecodeArray > v8::internal::SharedFunctionInfo::GetBytecodeArray (IsolateT * isolate) const [inline]
Definition at line 768 of file shared-function-info-inl.h.
                             {
  MutexGuardIfOffThread<IsolateT> mutex_guard(
      isolate->shared_function_info_access(), isolate);
  DCHECK(HasBytecodeArray());
  Isolate* main_isolate = isolate->GetMainThreadIsolateUnsafe();
  std::optional<Tagged<DebugInfo>> debug_info = TryGetDebugInfo(main_isolate);
  if (debug_info.has_value() &&
      debug_info.value()->HasInstrumentedBytecodeArray()) {
    return debug_info.value()->OriginalBytecodeArray(main_isolate);
  }
  return GetActiveBytecodeArray(main_isolate);
}
References v8::internal::DCHECK(), GetActiveBytecodeArray(), v8::internal::Isolate::GetMainThreadIsolateUnsafe(), and TryGetDebugInfo().
Referenced by abstract_code(), AreSourcePositionsAvailable(), CanCollectSourcePosition(), and GetInlineability().
GetCode()
Tagged< Code > v8::internal::SharedFunctionInfo::GetCode (Isolate * isolate) const
Definition at line 75 of file shared-function-info.cc.
                                                               {
  // ======
  // NOTE: This chain of checks MUST be kept in sync with the equivalent CSA
  // GetSharedFunctionInfoCode method in code-stub-assembler.cc.
  // ======
  Tagged<Object> data = GetTrustedData(isolate);
  if (data != Smi::zero()) {
    DCHECK(HasTrustedData());
    if (IsBytecodeArray(data)) {
      // Having a bytecode array means we are a compiled, interpreted function.
      DCHECK(HasBytecodeArray());
      return isolate->builtins()->code(Builtin::kInterpreterEntryTrampoline);
    }
    if (IsCode(data)) {
      // Having baseline Code means we are a compiled, baseline function.
      DCHECK(HasBaselineCode());
      return Cast<Code>(data);
    }
    if (IsInterpreterData(data)) {
      Tagged<Code> code = InterpreterTrampoline(isolate);
      DCHECK(IsCode(code));
      DCHECK(code->is_interpreter_trampoline_builtin());
      return code;
    }
    if (IsUncompiledData(data)) {
      // Having uncompiled data (with or without scope) means we need to
      // compile.
      DCHECK(HasUncompiledData(isolate));
      return isolate->builtins()->code(Builtin::kCompileLazy);
    }
#if V8_ENABLE_WEBASSEMBLY
    if (IsWasmExportedFunctionData(data)) {
      // Having a WasmExportedFunctionData means the code is in there.
      DCHECK(HasWasmExportedFunctionData(isolate));
      return wasm_exported_function_data()->wrapper_code(isolate);
    }
    if (IsWasmJSFunctionData(data)) {
      return wasm_js_function_data()->wrapper_code(isolate);
    }
    if (IsWasmCapiFunctionData(data)) {
      return wasm_capi_function_data()->wrapper_code(isolate);
    }
#endif // V8_ENABLE_WEBASSEMBLY
  } else {
    DCHECK(HasUntrustedData());
    data = GetUntrustedData();
    if (IsSmi(data)) {
      // Holding a Smi means we are a builtin.
      DCHECK(HasBuiltinId());
      return isolate->builtins()->code(builtin_id());
    }
    if (IsFunctionTemplateInfo(data)) {
      // Having a function template info means we are an API function.
      DCHECK(IsApiFunction());
      return isolate->builtins()->code(Builtin::kHandleApiCallOrConstruct);
    }
#if V8_ENABLE_WEBASSEMBLY
    if (IsAsmWasmData(data)) {
      // Having AsmWasmData means we are an asm.js/wasm function.
      DCHECK(HasAsmWasmData());
      return isolate->builtins()->code(Builtin::kInstantiateAsmJs);
    }
    if (IsWasmResumeData(data)) {
      if (static_cast<wasm::OnResume>(wasm_resume_data()->on_resume()) ==
          wasm::OnResume::kContinue) {
        return isolate->builtins()->code(Builtin::kWasmResume);
      } else {
        return isolate->builtins()->code(Builtin::kWasmReject);
      }
    }
#endif // V8_ENABLE_WEBASSEMBLY
  }
  UNREACHABLE();
}
References v8::internal::Isolate::builtins(), v8::internal::Builtins::code(), code, v8::internal::DCHECK(), GetTrustedData(), GetUntrustedData(), HasBuiltinId(), HasTrustedData(), HasUncompiledData(), HasUntrustedData(), InterpreterTrampoline(), IsApiFunction(), v8::internal::IsSmi(), v8::internal::wasm::kContinue, v8::internal::UNREACHABLE(), and v8::internal::Smi::zero().
Referenced by abstract_code().
GetCoverageInfo()
Tagged< CoverageInfo > v8::internal::SharedFunctionInfo::GetCoverageInfo (Isolate * isolate) const
Definition at line 316 of file shared-function-info.cc.
                            {
  DCHECK(HasCoverageInfo(isolate));
  return Cast<CoverageInfo>(GetDebugInfo(isolate)->coverage_info());
}
References v8::internal::DCHECK(), GetDebugInfo(), and HasCoverageInfo().
GetDebugInfo()
Tagged< DebugInfo > v8::internal::SharedFunctionInfo::GetDebugInfo (Isolate * isolate) const
Definition at line 295 of file shared-function-info.cc.
                                                                         {
  return isolate->debug()->TryGetDebugInfo(*this).value();
}
References v8::internal::Isolate::debug(), and v8::internal::Debug::TryGetDebugInfo().
Referenced by GetCoverageInfo().
GetInlineability()
template<typename IsolateT >
SharedFunctionInfo::Inlineability v8::internal::SharedFunctionInfo::GetInlineability (CodeKind code_kind, IsolateT * isolate) const
Definition at line 307 of file shared-function-info-inl.h.
                                                 {
  if (!IsScript(script())) return kHasNoScript;
  if (isolate->is_precise_binary_code_coverage() &&
      !has_reported_binary_coverage()) {
    // We may miss invocations if this function is inlined.
    return kNeedsBinaryCoverage;
  }
  // Built-in functions are handled by the JSCallReducer.
  if (HasBuiltinId()) return kIsBuiltin;
  if (!IsUserJavaScript()) return kIsNotUserCode;
  // If there is no bytecode array, it is either not compiled or it is compiled
  // with WebAssembly for the asm.js pipeline. In either case we don't want to
  // inline.
  if (!HasBytecodeArray()) return kHasNoBytecode;
  if (GetBytecodeArray(isolate)->length() >
      v8_flags.max_inlined_bytecode_size) {
    return kExceedsBytecodeLimit;
  }
  {
    MutexGuardIfOffThread<IsolateT> mutex_guard(
        isolate->shared_function_info_access(), isolate);
    if (HasBreakInfo(isolate->GetMainThreadIsolateUnsafe())) {
      return kMayContainBreakPoints;
    }
  }
  if (optimization_disabled(code_kind)) return kHasOptimizationDisabled;
  return kIsInlineable;
}
References GetBytecodeArray(), v8::internal::has_reported_binary_coverage, HasBreakInfo(), HasBuiltinId(), IsUserJavaScript(), kExceedsBytecodeLimit, kHasNoBytecode, kHasNoScript, kHasOptimizationDisabled, kIsBuiltin, kIsInlineable, kIsNotUserCode, kMayContainBreakPoints, kNeedsBinaryCoverage, v8::internal::length, optimization_disabled(), script(), and v8::internal::v8_flags.
GetOuterScopeInfo()
Tagged< ScopeInfo > v8::internal::SharedFunctionInfo::GetOuterScopeInfo () const [inline]
Definition at line 609 of file shared-function-info-inl.h.
                                                              {
  DCHECK(HasOuterScopeInfo());
  Tagged<ScopeInfo> info = scope_info(kAcquireLoad);
  if (info->IsEmpty()) return Cast<ScopeInfo>(outer_scope_info());
  return info->OuterScopeInfo();
}
References v8::internal::DCHECK(), HasOuterScopeInfo(), and v8::kAcquireLoad.
GetSourceCode()
DirectHandle< Object > v8::internal::SharedFunctionInfo::GetSourceCode (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared) [static]
Definition at line 446 of file shared-function-info.cc.
                                                               {
  if (!shared->HasSourceCode()) return isolate->factory()->undefined_value();
  Handle<String> source(Cast<String>(Cast<Script>(shared->script())->source()),
                        isolate);
  return isolate->factory()->NewSubString(source, shared->StartPosition(),
                                          shared->EndPosition());
}
References v8::internal::Isolate::factory().
Referenced by v8::internal::RUNTIME_FUNCTION().
GetSourceCodeHarmony()
Handle< Object > v8::internal::SharedFunctionInfo::GetSourceCodeHarmony (Isolate * isolate, DirectHandle< SharedFunctionInfo > shared) [static]
Definition at line 456 of file shared-function-info.cc.
                                                               {
  if (!shared->HasSourceCode()) return isolate->factory()->undefined_value();
  Handle<String> script_source(
      Cast<String>(Cast<Script>(shared->script())->source()), isolate);
  int start_pos = shared->function_token_position();
  DCHECK_NE(start_pos, kNoSourcePosition);
  Handle<String> source = isolate->factory()->NewSubString(
      script_source, start_pos, shared->EndPosition());
  if (!shared->is_wrapped()) return source;
  DCHECK(!shared->name_should_print_as_anonymous());
  IncrementalStringBuilder builder(isolate);
  builder.AppendCStringLiteral("function ");
  builder.AppendString(DirectHandle<String>(shared->Name(), isolate));
  builder.AppendCharacter('(');
  DirectHandle<FixedArray> args(
      Cast<Script>(shared->script())->wrapped_arguments(), isolate);
  int argc = args->length();
  for (int i = 0; i < argc; i++) {
    if (i > 0) builder.AppendCStringLiteral(", ");
    builder.AppendString(
        DirectHandle<String>(Cast<String>(args->get(i)), isolate));
  }
  builder.AppendCStringLiteral(") {\n");
  builder.AppendString(source);
  builder.AppendCStringLiteral("\n}");
  return indirect_handle(builder.Finish().ToHandleChecked(), isolate);
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendCStringLiteral(), v8::internal::IncrementalStringBuilder::AppendString(), v8::base::args, v8::internal::DCHECK(), DCHECK_NE, v8::internal::Isolate::factory(), v8::internal::IncrementalStringBuilder::Finish(), v8::internal::indirect_handle(), and v8::internal::kNoSourcePosition.
Referenced by v8::internal::JSFunction::ToString().
GetTrustedData() [1/2]
Tagged< Object > v8::internal::SharedFunctionInfo::GetTrustedData (IsolateForSandbox isolate) const [inline]
Definition at line 165 of file shared-function-info-inl.h.
                                     {
  return ReadMaybeEmptyTrustedPointerField<kUnknownIndirectPointerTag>(
      kTrustedFunctionDataOffset, isolate, kAcquireLoad);
}
References v8::kAcquireLoad.
Referenced by GetActiveBytecodeArray(), GetCode(), HasInterpreterData(), HasUncompiledData(), HasUncompiledDataWithoutPreparseData(), HasUncompiledDataWithPreparseData(), and interpreter_data().
GetTrustedData() [2/2]
template<typename T , IndirectPointerTag tag>
Tagged< T > v8::internal::SharedFunctionInfo::GetTrustedData (IsolateForSandbox isolate) const [inline]
Definition at line 172 of file shared-function-info-inl.h.
                                                                            {
  static_assert(tag != kUnknownIndirectPointerTag);
  return Cast<T>(ReadMaybeEmptyTrustedPointerField<tag>(
      kTrustedFunctionDataOffset, isolate, kAcquireLoad));
}
References v8::kAcquireLoad, and v8::internal::kUnknownIndirectPointerTag.
GetUntrustedData()
Tagged< Object > v8::internal::SharedFunctionInfo::GetUntrustedData () const [inline]
Definition at line 178 of file shared-function-info-inl.h.
                                                          {
  return TaggedField<Object, kUntrustedFunctionDataOffset>::Acquire_Load(*this);
}
References v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Acquire_Load().
Referenced by GetCode(), HasBuiltinId(), IsApiFunction(), v8::internal::RELEASE_ACQUIRE_ACCESSORS_CHECKED2(), set_bytecode_array(), and set_uncompiled_data_with_preparse_data().
has_script()
bool v8::internal::SharedFunctionInfo::has_script (AcquireLoadTag tag) const [inline]
Definition at line 185 of file shared-function-info-inl.h.
                                                            {
  return IsScript(script(tag));
}
References script().
has_simple_parameters()
bool v8::internal::SharedFunctionInfo::has_simple_parameters () [inline]
Definition at line 738 of file shared-function-info-inl.h.
                                               {
  return scope_info(kAcquireLoad)->HasSimpleParameters();
}
References v8::kAcquireLoad.
HasBreakInfo()
bool v8::internal::SharedFunctionInfo::HasBreakInfo (Isolate * isolate) const
Definition at line 304 of file shared-function-info.cc.
                                                            {
  return isolate->debug()->HasBreakInfo(*this);
}
References v8::internal::Isolate::debug(), and v8::internal::Debug::HasBreakInfo().
Referenced by GetInlineability().
HasBuiltinId()
bool v8::internal::SharedFunctionInfo::HasBuiltinId () const [inline]
Definition at line 977 of file shared-function-info-inl.h.
                                            {
  Tagged<Object> data = GetUntrustedData();
  return IsSmi(data) && Builtins::IsBuiltinId(Smi::ToInt(data));
}
References GetUntrustedData(), v8::internal::Builtins::IsBuiltinId(), v8::internal::IsSmi(), and v8::internal::Smi::ToInt().
Referenced by CalculateConstructAsBuiltin(), DontAdaptArguments(), EndPosition(), GetCode(), GetInlineability(), and StartPosition().
HasCoverageInfo()
bool v8::internal::SharedFunctionInfo::HasCoverageInfo (Isolate * isolate) const
Definition at line 312 of file shared-function-info.cc.
                                                               {
  return isolate->debug()->HasCoverageInfo(*this);
}
References v8::internal::Isolate::debug(), and v8::internal::Debug::HasCoverageInfo().
Referenced by GetCoverageInfo().
HasDebugInfo()
bool v8::internal::SharedFunctionInfo::HasDebugInfo (Isolate * isolate) const
Definition at line 276 of file shared-function-info.cc.
                                                            {
  return isolate->debug()->HasDebugInfo(*this);
}
References v8::internal::Isolate::debug(), and v8::internal::Debug::HasDebugInfo().
HasFeedbackMetadata() [1/2]
bool v8::internal::SharedFunctionInfo::HasFeedbackMetadata () const [inline]
Definition at line 625 of file shared-function-info-inl.h.
                                                   {
  return IsFeedbackMetadata(raw_outer_scope_info_or_feedback_metadata());
}
References v8::internal::raw_outer_scope_info_or_feedback_metadata.
Referenced by DiscardCompiledMetadata().
HasFeedbackMetadata() [2/2]
bool v8::internal::SharedFunctionInfo::HasFeedbackMetadata (AcquireLoadTag tag) const [inline]
Definition at line 629 of file shared-function-info-inl.h.
                                                                     {
  return IsFeedbackMetadata(raw_outer_scope_info_or_feedback_metadata(tag));
}
References v8::internal::raw_outer_scope_info_or_feedback_metadata.
Hash()
uint32_t v8::internal::SharedFunctionInfo::Hash ()
Definition at line 27 of file shared-function-info.cc.
                                  {
  // Hash SharedFunctionInfo based on its start position and script id. Note: we
  // don't use the function's literal id since getting that is slow for compiled
  // functions.
  int start_pos = StartPosition();
  int script_id = IsScript(script()) ? Cast<Script>(script())->id() : 0;
  return static_cast<uint32_t>(base::hash_combine(start_pos, script_id));
}
References v8::base::hash_combine(), script(), and StartPosition().
HasInferredName()
bool v8::internal::SharedFunctionInfo::HasInferredName () [inline]
Definition at line 1110 of file shared-function-info-inl.h.
                                         {
  Tagged<Object> scope_info = name_or_scope_info(kAcquireLoad);
  if (IsScopeInfo(scope_info)) {
    return Cast<ScopeInfo>(scope_info)->HasInferredFunctionName();
  }
  return HasUncompiledData(GetCurrentIsolateForSandbox());
}
References v8::internal::GetCurrentIsolateForSandbox(), HasUncompiledData(), and v8::kAcquireLoad.
Referenced by SetScopeInfo().
HasInterpreterData()
bool v8::internal::SharedFunctionInfo::HasInterpreterData (IsolateForSandbox isolate) const [inline]
Definition at line 834 of file shared-function-info-inl.h.
                                                                           {
  Tagged<Object> data = GetTrustedData(isolate);
  if (IsCode(data)) {
    Tagged<Code> baseline_code = Cast<Code>(data);
    DCHECK_EQ(baseline_code->kind(), CodeKind::BASELINE);
    data = baseline_code->bytecode_or_interpreter_data();
  }
  return IsInterpreterData(data);
}
References DCHECK_EQ, and GetTrustedData().
Referenced by interpreter_data(), InterpreterTrampoline(), and SetActiveBytecodeArray().
HasOuterScopeInfo()
bool v8::internal::SharedFunctionInfo::HasOuterScopeInfo () const [inline]
Definition at line 595 of file shared-function-info-inl.h.
                                                 {
  Tagged<ScopeInfo> outer_info;
  Tagged<ScopeInfo> info = scope_info(kAcquireLoad);
  if (info->IsEmpty()) {
    if (is_compiled()) return false;
    if (!IsScopeInfo(outer_scope_info())) return false;
    outer_info = Cast<ScopeInfo>(outer_scope_info());
  } else {
    if (!info->HasOuterScopeInfo()) return false;
    outer_info = info->OuterScopeInfo();
  }
  return !outer_info->IsEmpty();
}
References is_compiled(), and v8::kAcquireLoad.
Referenced by DiscardCompiledMetadata(), and GetOuterScopeInfo().
HasSharedName()
bool v8::internal::SharedFunctionInfo::HasSharedName () const [inline]
Definition at line 236 of file shared-function-info-inl.h.
                                             {
  Tagged<Object> value = name_or_scope_info(kAcquireLoad);
  if (IsScopeInfo(value)) {
    return Cast<ScopeInfo>(value)->HasSharedFunctionName();
  }
  return value != kNoSharedNameSentinel;
}
References v8::kAcquireLoad, and v8::internal::value.
Referenced by Name(), and UpdateFunctionMapIndex().
HasSourceCode()
bool v8::internal::SharedFunctionInfo::HasSourceCode () const
Definition at line 367 of file shared-function-info.cc.
                                             {
  ReadOnlyRoots roots = GetReadOnlyRoots();
  return !IsUndefined(script(), roots) &&
         !IsUndefined(Cast<Script>(script())->source(), roots) &&
         Cast<String>(Cast<Script>(script())->source())->length() > 0;
}
References v8::internal::GetReadOnlyRoots(), and script().
HasTrustedData()
bool v8::internal::SharedFunctionInfo::HasTrustedData () const [inline], [private]
Definition at line 153 of file shared-function-info-inl.h.
                                              {
  return !IsTrustedPointerFieldEmpty(kTrustedFunctionDataOffset);
}
Referenced by GetCode(), and HasUntrustedData().
HasUncompiledData()
bool v8::internal::SharedFunctionInfo::HasUncompiledData (IsolateForSandbox isolate) const [inline]
Definition at line 997 of file shared-function-info-inl.h.
                                                                          {
  return IsUncompiledData(GetTrustedData(isolate));
}
References GetTrustedData().
Referenced by EndPosition(), GetCode(), HasInferredName(), v8::internal::RELEASE_ACQUIRE_ACCESSORS_CHECKED2(), set_bytecode_array(), StartPosition(), uncompiled_data(), and UpdateFromFunctionLiteralForLiveEdit().
HasUncompiledDataWithoutPreparseData()
bool v8::internal::SharedFunctionInfo::HasUncompiledDataWithoutPreparseData (IsolateForSandbox isolate) const [inline]
Definition at line 1038 of file shared-function-info-inl.h.
                                     {
  return IsUncompiledDataWithoutPreparseData(GetTrustedData(isolate));
}
References GetTrustedData().
Referenced by ClearPreparseData().
HasUncompiledDataWithPreparseData()
bool v8::internal::SharedFunctionInfo::HasUncompiledDataWithPreparseData (IsolateForSandbox isolate) const [inline]
Definition at line 1014 of file shared-function-info-inl.h.
                                     {
  return IsUncompiledDataWithPreparseData(GetTrustedData(isolate));
}
References GetTrustedData().
Referenced by CanDiscardCompiled(), ClearPreparseData(), SetScript(), uncompiled_data_with_preparse_data(), and UpdateFromFunctionLiteralForLiveEdit().
HasUnpublishedTrustedData()
bool v8::internal::SharedFunctionInfo::HasUnpublishedTrustedData (IsolateForSandbox isolate) const [inline]
Definition at line 157 of file shared-function-info-inl.h.
                                     {
  return IsTrustedPointerFieldUnpublished(kTrustedFunctionDataOffset,
                                          kUnknownIndirectPointerTag, isolate);
}
References v8::internal::kUnknownIndirectPointerTag.
HasUntrustedData()
bool v8::internal::SharedFunctionInfo::HasUntrustedData () const [inline], [private]
Definition at line 163 of file shared-function-info-inl.h.
{ return !HasTrustedData(); }
References HasTrustedData().
Referenced by GetCode().
Init()
void v8::internal::SharedFunctionInfo::Init (ReadOnlyRoots roots, int unique_id)
Definition at line 36 of file shared-function-info.cc.
                                                                   {
  DisallowGarbageCollection no_gc;
  // Set the function data to the "illegal" builtin. Ideally we'd use some sort
  // of "uninitialized" marker here, but it's cheaper to use a valid builtin and
  // avoid having to do uninitialized checks elsewhere.
  set_builtin_id(Builtin::kIllegal);
  // Set the name to the no-name sentinel, this can be updated later.
  set_name_or_scope_info(SharedFunctionInfo::kNoSharedNameSentinel,
                         kReleaseStore, SKIP_WRITE_BARRIER);
  // Generally functions won't have feedback, unless they have been created
  // from a FunctionLiteral. Those can just reset this field to keep the
  // SharedFunctionInfo in a consistent state.
  set_raw_outer_scope_info_or_feedback_metadata(ro_roots.the_hole_value(),
                                                SKIP_WRITE_BARRIER);
  set_script(ro_roots.undefined_value(), kReleaseStore, SKIP_WRITE_BARRIER);
  set_function_literal_id(kInvalidInfoId, kRelaxedStore);
  set_unique_id(unique_id);
  // Set integer fields (smi or int, depending on the architecture).
  set_length(0);
  set_internal_formal_parameter_count(JSParameterCount(0));
  set_expected_nof_properties(0);
  set_raw_function_token_offset(0);
  // All flags default to false or 0, except ConstructAsBuiltinBit just because
  // we're using the kIllegal builtin.
  set_flags(ConstructAsBuiltinBit::encode(true), kRelaxedStore);
  set_flags2(0);
  UpdateFunctionMapIndex();
  set_age(0);
  clear_padding();
}
References clear_padding(), v8::internal::JSParameterCount(), v8::internal::kInvalidInfoId, kNoSharedNameSentinel, v8::kRelaxedStore, v8::kReleaseStore, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, set_internal_formal_parameter_count(), v8::internal::SKIP_WRITE_BARRIER, and UpdateFunctionMapIndex().
InitFromFunctionLiteral()
template<typename IsolateT >
void v8::internal::SharedFunctionInfo::InitFromFunctionLiteral (IsolateT * isolate, FunctionLiteral * lit, bool is_toplevel) [static]
Definition at line 543 of file shared-function-info.cc.
                                                                   {
  DCHECK(!IsScopeInfo(
      lit->shared_function_info()->name_or_scope_info(kAcquireLoad)));
  {
    DisallowGarbageCollection no_gc;
    Tagged<SharedFunctionInfo> raw_sfi = *lit->shared_function_info();
    DCHECK_EQ(raw_sfi->function_literal_id(kRelaxedLoad),
              lit->function_literal_id());
    // When adding fields here, make sure DeclarationScope::AnalyzePartially is
    // updated accordingly.
    raw_sfi->set_internal_formal_parameter_count(
        JSParameterCount(lit->parameter_count()));
    raw_sfi->SetFunctionTokenPosition(lit->function_token_position(),
                                      lit->start_position());
    raw_sfi->set_syntax_kind(lit->syntax_kind());
    raw_sfi->set_allows_lazy_compilation(lit->AllowsLazyCompilation());
    raw_sfi->set_language_mode(lit->language_mode());
    // FunctionKind must have already been set.
    DCHECK(lit->kind() == raw_sfi->kind());
    DCHECK_IMPLIES(lit->requires_instance_members_initializer(),
                   IsClassConstructor(lit->kind()));
    raw_sfi->set_requires_instance_members_initializer(
        lit->requires_instance_members_initializer());
    DCHECK_IMPLIES(lit->class_scope_has_private_brand(),
                   IsClassConstructor(lit->kind()));
    raw_sfi->set_class_scope_has_private_brand(
        lit->class_scope_has_private_brand());
    DCHECK_IMPLIES(lit->has_static_private_methods_or_accessors(),
                   IsClassConstructor(lit->kind()));
    raw_sfi->set_has_static_private_methods_or_accessors(
        lit->has_static_private_methods_or_accessors());
    raw_sfi->set_is_toplevel(is_toplevel);
    DCHECK(IsTheHole(raw_sfi->outer_scope_info()));
    Scope* outer_scope = lit->scope()->GetOuterScopeWithContext();
    if (outer_scope && (!is_toplevel || !outer_scope->is_script_scope())) {
      raw_sfi->set_outer_scope_info(*outer_scope->scope_info());
      raw_sfi->set_private_name_lookup_skips_outer_class(
          lit->scope()->private_name_lookup_skips_outer_class());
    }
    if (lit->scope()->is_reparsed()) {
      raw_sfi->SetScopeInfo(*lit->scope()->scope_info());
    }
    raw_sfi->set_length(lit->function_length());
    // For lazy parsed functions, the following flags will be inaccurate since
    // we don't have the information yet. They're set later in
    // UpdateSharedFunctionFlagsAfterCompilation (compiler.cc), when the
    // function is really parsed and compiled.
    if (lit->ShouldEagerCompile()) {
      raw_sfi->set_has_duplicate_parameters(lit->has_duplicate_parameters());
      raw_sfi->UpdateAndFinalizeExpectedNofPropertiesFromEstimate(lit);
      DCHECK_NULL(lit->produced_preparse_data());
      // If we're about to eager compile, we'll have the function literal
      // available, so there's no need to wastefully allocate an uncompiled
      // data.
      return;
    }
    raw_sfi->UpdateExpectedNofPropertiesFromEstimate(lit);
  }
  CreateAndSetUncompiledData(isolate, lit);
}
References v8::internal::FunctionLiteral::AllowsLazyCompilation(), v8::internal::FunctionLiteral::class_scope_has_private_brand(), CreateAndSetUncompiledData(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, DCHECK_NULL, v8::internal::FunctionLiteral::function_length(), v8::internal::FunctionLiteral::function_literal_id(), v8::internal::FunctionLiteral::function_token_position(), v8::internal::Scope::GetOuterScopeWithContext(), v8::internal::FunctionLiteral::has_duplicate_parameters(), v8::internal::FunctionLiteral::has_static_private_methods_or_accessors(), v8::internal::Scope::is_reparsed(), v8::internal::Scope::is_script_scope(), v8::internal::IsClassConstructor(), v8::internal::JSParameterCount(), v8::kAcquireLoad, v8::internal::FunctionLiteral::kind(), v8::kRelaxedLoad, v8::internal::FunctionLiteral::language_mode(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::FunctionLiteral::parameter_count(), v8::internal::Scope::private_name_lookup_skips_outer_class(), v8::internal::FunctionLiteral::produced_preparse_data(), v8::internal::FunctionLiteral::requires_instance_members_initializer(), v8::internal::FunctionLiteral::scope(), v8::internal::Scope::scope_info(), v8::internal::FunctionLiteral::shared_function_info(), v8::internal::FunctionLiteral::ShouldEagerCompile(), v8::internal::FunctionLiteral::start_position(), and v8::internal::FunctionLiteral::syntax_kind().
InstallDebugBytecode()
void v8::internal::SharedFunctionInfo::InstallDebugBytecode (DirectHandle< SharedFunctionInfo > shared, Isolate * isolate) [static]
Definition at line 845 of file shared-function-info.cc.
                                                               {
  DCHECK(shared->HasBytecodeArray());
  DirectHandle<BytecodeArray> original_bytecode_array(
      shared->GetBytecodeArray(isolate), isolate);
  DirectHandle<BytecodeArray> debug_bytecode_array =
      isolate->factory()->CopyBytecodeArray(original_bytecode_array);
  {
    DisallowGarbageCollection no_gc;
    base::MutexGuard guard(isolate->shared_function_info_access());
    Tagged<DebugInfo> debug_info = shared->GetDebugInfo(isolate);
    debug_info->set_original_bytecode_array(*original_bytecode_array,
                                            kReleaseStore);
    debug_info->set_debug_bytecode_array(*debug_bytecode_array, kReleaseStore);
    shared->SetActiveBytecodeArray(*debug_bytecode_array, isolate);
  }
}
References v8::internal::Factory::CopyBytecodeArray(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), v8::kReleaseStore, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::original_bytecode_array, and v8::internal::Isolate::shared_function_info_access().
Referenced by v8::internal::Debug::PrepareFunctionForDebugExecution().
internal_formal_parameter_count_with_receiver()
uint16_t v8::internal::SharedFunctionInfo::internal_formal_parameter_count_with_receiver () const [inline]
Definition at line 202 of file shared-function-info-inl.h.
          {
  const uint16_t param_count = TorqueGeneratedClass::formal_parameter_count();
  return param_count;
}
internal_formal_parameter_count_without_receiver()
uint16_t v8::internal::SharedFunctionInfo::internal_formal_parameter_count_without_receiver () const [inline]
Definition at line 208 of file shared-function-info-inl.h.
          {
  const uint16_t param_count = TorqueGeneratedClass::formal_parameter_count();
  if (param_count == kDontAdaptArgumentsSentinel) return param_count;
  return param_count - kJSArgcReceiverSlots;
}
References v8::internal::kDontAdaptArgumentsSentinel, and v8::internal::kJSArgcReceiverSlots.
interpreter_data()
Tagged< InterpreterData > v8::internal::SharedFunctionInfo::interpreter_data (IsolateForSandbox isolate) const [inline]
Definition at line 844 of file shared-function-info-inl.h.
                                     {
  DCHECK(HasInterpreterData(isolate));
  Tagged<Object> data = GetTrustedData(isolate);
  if (IsCode(data)) {
    Tagged<Code> baseline_code = Cast<Code>(data);
    DCHECK_EQ(baseline_code->kind(), CodeKind::BASELINE);
    data = baseline_code->bytecode_or_interpreter_data();
  }
  SBXCHECK(IsInterpreterData(data));
  return Cast<InterpreterData>(data);
}
References v8::internal::DCHECK(), DCHECK_EQ, GetTrustedData(), HasInterpreterData(), and SBXCHECK.
Referenced by InterpreterTrampoline(), set_interpreter_data(), and SetActiveBytecodeArray().
InterpreterTrampoline()
Tagged< Code > v8::internal::SharedFunctionInfo::InterpreterTrampoline (IsolateForSandbox isolate) const [inline]
Definition at line 828 of file shared-function-info-inl.h.
                                     {
  DCHECK(HasInterpreterData(isolate));
  return interpreter_data(isolate)->interpreter_trampoline();
}
References v8::internal::DCHECK(), HasInterpreterData(), and interpreter_data().
Referenced by GetCode().
is_class_constructor()
bool v8::internal::SharedFunctionInfo::is_class_constructor () const [inline]
Definition at line 1159 of file shared-function-info-inl.h.
                                                    {
  return IsClassConstructorBit::decode(flags(kRelaxedLoad));
}
References v8::internal::flags, and v8::kRelaxedLoad.
is_compiled()
bool v8::internal::SharedFunctionInfo::is_compiled () const [inline]
Referenced by HasOuterScopeInfo(), and UpdateFromFunctionLiteralForLiveEdit().
is_compiled_scope()
template<typename IsolateT >
IsCompiledScope v8::internal::SharedFunctionInfo::is_compiled_scope (IsolateT * isolate) const [inline]
Referenced by EnsureBytecodeArrayAvailable().
is_repl_mode()
bool v8::internal::SharedFunctionInfo::is_repl_mode () const [inline]
Definition at line 1106 of file shared-function-info-inl.h.
                                            {
  return IsScript(script()) && Cast<Script>(script())->is_repl_mode();
}
References script().
is_script()
bool v8::internal::SharedFunctionInfo::is_script () const [inline]
Definition at line 268 of file shared-function-info-inl.h.
                                         {
  return scope_info(kAcquireLoad)->is_script_scope() &&
         Cast<Script>(script())->compilation_type() ==
             Script::CompilationType::kHost;
}
References v8::kAcquireLoad, v8::internal::Script::kHost, and script().
Referenced by needs_script_context().
is_wrapped()
bool v8::internal::SharedFunctionInfo::is_wrapped () const [inline]
Definition at line 445 of file shared-function-info-inl.h.
                                          {
  return syntax_kind() == FunctionSyntaxKind::kWrapped;
}
References v8::internal::kWrapped, and v8::internal::syntax_kind.
IsApiFunction()
bool v8::internal::SharedFunctionInfo::IsApiFunction () const [inline]
Definition at line 747 of file shared-function-info-inl.h.
                                             {
  return IsFunctionTemplateInfo(GetUntrustedData());
}
References GetUntrustedData().
Referenced by CalculateConstructAsBuiltin(), EndPosition(), GetCode(), and StartPosition().
IsSubjectToDebugging()
bool v8::internal::SharedFunctionInfo::IsSubjectToDebugging () const [inline]
Definition at line 1142 of file shared-function-info-inl.h.
                                                    {
#if V8_ENABLE_WEBASSEMBLY
  if (HasAsmWasmData()) return false;
  if (HasWasmExportedFunctionData(GetCurrentIsolateForSandbox())) return false;
#endif // V8_ENABLE_WEBASSEMBLY
  return IsUserJavaScript();
}
References v8::internal::GetCurrentIsolateForSandbox(), and IsUserJavaScript().
IsUserJavaScript()
bool v8::internal::SharedFunctionInfo::IsUserJavaScript () const [inline]
Definition at line 1135 of file shared-function-info-inl.h.
                                                {
  Tagged<Object> script_obj = script();
  if (IsUndefined(script_obj)) return false;
  Tagged<Script> script = Cast<Script>(script_obj);
  return script->IsUserJavaScript();
}
References script().
Referenced by GetInlineability(), and IsSubjectToDebugging().
kind()
FunctionKind v8::internal::SharedFunctionInfo::kind () const [inline]
Definition at line 432 of file shared-function-info-inl.h.
                                            {
  static_assert(FunctionKindBits::kSize == kFunctionKindBitSize);
  return FunctionKindBits::decode(flags(kRelaxedLoad));
}
References v8::internal::flags, v8::internal::kFunctionKindBitSize, and v8::kRelaxedLoad.
Referenced by DisableOptimization(), set_kind(), UniqueIdInScript(), and UpdateFunctionMapIndex().
language_mode()
LanguageMode v8::internal::SharedFunctionInfo::language_mode () const [inline]
Definition at line 416 of file shared-function-info-inl.h.
                                                     {
  static_assert(LanguageModeSize == 2);
  return construct_language_mode(IsStrictBit::decode(flags(kRelaxedLoad)));
}
References v8::internal::construct_language_mode(), v8::internal::flags, v8::kRelaxedLoad, and v8::internal::LanguageModeSize.
Referenced by set_language_mode(), and UpdateFunctionMapIndex().
Name()
Tagged< String > v8::internal::SharedFunctionInfo::Name () const [inline]
Definition at line 244 of file shared-function-info-inl.h.
                                              {
  if (!HasSharedName()) return GetReadOnlyRoots().empty_string();
  Tagged<Object> value = name_or_scope_info(kAcquireLoad);
  if (IsScopeInfo(value)) {
    if (Cast<ScopeInfo>(value)->HasFunctionName()) {
      return Cast<String>(Cast<ScopeInfo>(value)->FunctionName());
    }
    return GetReadOnlyRoots().empty_string();
  }
  return Cast<String>(value);
}
References v8::internal::GetReadOnlyRoots(), HasSharedName(), v8::kAcquireLoad, and v8::internal::value.
Referenced by DebugNameCStr().
needs_script_context()
bool v8::internal::SharedFunctionInfo::needs_script_context () const [inline]
Definition at line 274 of file shared-function-info-inl.h.
                                                    {
  return is_script() && scope_info(kAcquireLoad)->ContextLocalCount() > 0;
}
References is_script(), and v8::kAcquireLoad.
optimization_disabled()
SharedFunctionInfo::HasStaticPrivateMethodsOrAccessorsBit SharedFunctionInfo::MaglevCompilationFailedBit SharedFunctionInfo::FunctionSyntaxKindBits SharedFunctionInfo::HasDuplicateParametersBit SharedFunctionInfo::RequiresInstanceMembersInitializerBit SharedFunctionInfo::HasReportedBinaryCoverageBit SharedFunctionInfo::PropertiesAreFinalBit SharedFunctionInfo::LiveEditedBit bool v8::internal::SharedFunctionInfo::optimization_disabled (CodeKind kind) const [inline]
Definition at line 397 of file shared-function-info-inl.h.
                                                                  {
  switch (kind) {
    case CodeKind::MAGLEV:
      return IsTerminalBailoutReasonForMaglev(disabled_optimization_reason());
    case CodeKind::TURBOFAN_JS:
      return IsTerminalBailoutReasonForTurbofan(disabled_optimization_reason());
    default:
      UNREACHABLE();
  }
}
References v8::internal::IsTerminalBailoutReasonForMaglev(), v8::internal::IsTerminalBailoutReasonForTurbofan(), and v8::internal::UNREACHABLE().
Referenced by GetInlineability().
overwrite_bytecode_array()
void v8::internal::SharedFunctionInfo::overwrite_bytecode_array (Tagged< BytecodeArray > bytecode) [inline]
Definition at line 822 of file shared-function-info-inl.h.
                                    {
  DCHECK(HasBytecodeArray());
  SetTrustedData(bytecode);
}
References v8::internal::DCHECK(), and SetTrustedData().
Referenced by SetActiveBytecodeArray().
PassesFilter()
bool v8::internal::SharedFunctionInfo::PassesFilter (const char * raw_filter)
Definition at line 357 of file shared-function-info.cc.
                                                            {
  // Filters are almost always "*", so check for that and exit quickly.
  if (V8_LIKELY(raw_filter[0] == '*' && raw_filter[1] == '\0')) {
    return true;
  }
  base::Vector<const char> filter = base::CStrVector(raw_filter);
  return v8::internal::PassesFilter(base::CStrVector(DebugNameCStr().get()),
                                    filter);
}
References v8::base::CStrVector(), DebugNameCStr(), v8::internal::PassesFilter(), and V8_LIKELY.
relaxed_flags()
kFunctionLiteralIdOffset int32_t v8::internal::SharedFunctionInfo::relaxed_flags () const [inline], [private]
Definition at line 227 of file shared-function-info-inl.h.
                                                {
  return flags(kRelaxedLoad);
}
References v8::internal::flags, and v8::kRelaxedLoad.
script() [1/2]
Tagged<HeapObject> v8::internal::SharedFunctionInfo::script () const [inline]
Referenced by GetInlineability(), has_script(), Hash(), HasSourceCode(), is_repl_mode(), is_script(), IsUserJavaScript(), v8::internal::SharedFunctionInfo::ScriptIterator::Reset(), and SetScript().
script() [2/2]
Tagged<HeapObject> v8::internal::SharedFunctionInfo::script (PtrComprCageBase cage_base) const [inline]
set_bytecode_array()
void v8::internal::SharedFunctionInfo::set_bytecode_array (Tagged< BytecodeArray > bytecode) [inline]
Definition at line 816 of file shared-function-info-inl.h.
                                                                          {
  DCHECK(GetUntrustedData() == Smi::FromEnum(Builtin::kCompileLazy) ||
         HasUncompiledData(GetCurrentIsolateForSandbox()));
  SetTrustedData(bytecode);
}
References v8::internal::DCHECK(), v8::internal::Smi::FromEnum(), v8::internal::GetCurrentIsolateForSandbox(), GetUntrustedData(), HasUncompiledData(), and SetTrustedData().
set_cached_tiering_decision()
void v8::internal::SharedFunctionInfo::set_cached_tiering_decision (CachedTieringDecision decision)
Definition at line 812 of file shared-function-info.cc.
                                    {
  set_flags2(CachedTieringDecisionBits::update(flags2(), decision));
}
References v8::internal::flags2.
set_internal_formal_parameter_count()
void v8::internal::SharedFunctionInfo::set_internal_formal_parameter_count (int value) [inline]
Definition at line 215 of file shared-function-info-inl.h.
                                                                      {
  DCHECK_EQ(value, static_cast<uint16_t>(value));
  DCHECK_GE(value, kJSArgcReceiverSlots);
  TorqueGeneratedClass::set_formal_parameter_count(value);
}
References DCHECK_EQ, DCHECK_GE, v8::internal::kJSArgcReceiverSlots, and v8::internal::value.
Referenced by Init().
set_interpreter_data()
void v8::internal::SharedFunctionInfo::set_interpreter_data (Isolate * isolate, Tagged< InterpreterData > interpreter_data, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 857 of file shared-function-info-inl.h.
                           {
  DCHECK(isolate->interpreted_frames_native_stack());
  DCHECK(!HasBaselineCode());
  SetTrustedData(interpreter_data, mode);
}
References v8::internal::DCHECK(), v8::internal::Isolate::interpreted_frames_native_stack(), interpreter_data(), mode(), and SetTrustedData().
set_kind()
void v8::internal::SharedFunctionInfo::set_kind (FunctionKind kind) [inline], [private]
Definition at line 437 of file shared-function-info-inl.h.
                                                   {
  int hints = flags(kRelaxedLoad);
  hints = FunctionKindBits::update(hints, kind);
  hints = IsClassConstructorBit::update(hints, IsClassConstructor(kind));
  set_flags(hints, kRelaxedStore);
  UpdateFunctionMapIndex();
}
References v8::internal::flags, v8::internal::IsClassConstructor(), kind(), v8::kRelaxedLoad, v8::kRelaxedStore, and UpdateFunctionMapIndex().
set_language_mode()
void v8::internal::SharedFunctionInfo::set_language_mode (LanguageMode language_mode) [inline]
Definition at line 421 of file shared-function-info-inl.h.
                                                                     {
  static_assert(LanguageModeSize == 2);
  // We only allow language mode transitions that set the same language mode
  // again or go up in the chain:
  DCHECK(is_sloppy(this->language_mode()) || is_strict(language_mode));
  int hints = flags(kRelaxedLoad);
  hints = IsStrictBit::update(hints, is_strict(language_mode));
  set_flags(hints, kRelaxedStore);
  UpdateFunctionMapIndex();
}
References v8::internal::DCHECK(), v8::internal::flags, v8::internal::is_sloppy(), v8::internal::is_strict(), v8::kRelaxedLoad, v8::kRelaxedStore, language_mode(), v8::internal::LanguageModeSize, and UpdateFunctionMapIndex().
set_raw_scope_info()
void v8::internal::SharedFunctionInfo::set_raw_scope_info (Tagged< ScopeInfo > scope_info, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 583 of file shared-function-info-inl.h.
                                                                   {
  WRITE_FIELD(*this, kNameOrScopeInfoOffset, scope_info);
  CONDITIONAL_WRITE_BARRIER(*this, kNameOrScopeInfoOffset, scope_info, mode);
}
References CONDITIONAL_WRITE_BARRIER, mode(), and WRITE_FIELD.
set_relaxed_flags()
void v8::internal::SharedFunctionInfo::set_relaxed_flags (int32_t flags) [inline], [private]
Definition at line 230 of file shared-function-info-inl.h.
                                                        {
  return set_flags(flags, kRelaxedStore);
}
References v8::internal::flags, and v8::kRelaxedStore.
set_uncompiled_data()
void v8::internal::SharedFunctionInfo::set_uncompiled_data (Tagged< UncompiledData > data, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 1008 of file shared-function-info-inl.h.
                                                                   {
  DCHECK(IsUncompiledData(uncompiled_data));
  SetTrustedData(uncompiled_data, mode);
}
References v8::internal::DCHECK(), mode(), SetTrustedData(), and uncompiled_data().
set_uncompiled_data_with_preparse_data()
void v8::internal::SharedFunctionInfo::set_uncompiled_data_with_preparse_data (Tagged< UncompiledDataWithPreparseData > data, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 1030 of file shared-function-info-inl.h.
                           {
  DCHECK_EQ(GetUntrustedData(), Smi::FromEnum(Builtin::kCompileLazy));
  DCHECK(IsUncompiledDataWithPreparseData(uncompiled_data_with_preparse_data));
  SetTrustedData(uncompiled_data_with_preparse_data, mode);
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::Smi::FromEnum(), GetUntrustedData(), mode(), SetTrustedData(), and uncompiled_data_with_preparse_data().
SetActiveBytecodeArray()
void v8::internal::SharedFunctionInfo::SetActiveBytecodeArray (Tagged< BytecodeArray > bytecode, IsolateForSandbox isolate) [inline]
Definition at line 802 of file shared-function-info-inl.h.
                                                                           {
  // We don't allow setting the active bytecode array on baseline-optimized
  // functions. They should have been flushed earlier.
  DCHECK(!HasBaselineCode());
  if (HasInterpreterData(isolate)) {
    interpreter_data(isolate)->set_bytecode_array(bytecode);
  } else {
    DCHECK(HasBytecodeArray());
    overwrite_bytecode_array(bytecode);
  }
}
References v8::internal::DCHECK(), HasInterpreterData(), interpreter_data(), and overwrite_bytecode_array().
SetFunctionTokenPosition()
void v8::internal::SharedFunctionInfo::SetFunctionTokenPosition (int function_token_position, int start_position)
Definition at line 699 of file shared-function-info.cc.
                                                                      {
  int offset;
  if (function_token_position == kNoSourcePosition) {
    offset = 0;
  } else {
    offset = start_position - function_token_position;
  }
  if (offset > kMaximumFunctionTokenOffset) {
    offset = kFunctionTokenOutOfRange;
  }
  set_raw_function_token_offset(offset);
}
References function_token_position(), kFunctionTokenOutOfRange, kMaximumFunctionTokenOffset, and v8::internal::kNoSourcePosition.
Referenced by UpdateFromFunctionLiteralForLiveEdit().
SetName()
void v8::internal::SharedFunctionInfo::SetName (Tagged< String > name) [inline]
Definition at line 256 of file shared-function-info-inl.h.
                                                    {
  Tagged<Object> maybe_scope_info = name_or_scope_info(kAcquireLoad);
  if (IsScopeInfo(maybe_scope_info)) {
    Cast<ScopeInfo>(maybe_scope_info)->SetFunctionName(name);
  } else {
    DCHECK(IsString(maybe_scope_info) ||
           maybe_scope_info == kNoSharedNameSentinel);
    set_name_or_scope_info(name, kReleaseStore);
  }
  UpdateFunctionMapIndex();
}
References v8::internal::DCHECK(), v8::kAcquireLoad, kNoSharedNameSentinel, v8::kReleaseStore, v8::internal::name, and UpdateFunctionMapIndex().
SetScopeInfo()
void v8::internal::SharedFunctionInfo::SetScopeInfo (Tagged< ScopeInfo > scope_info, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 556 of file shared-function-info-inl.h.
                                                             {
  // Move the existing name onto the ScopeInfo.
  Tagged<NameOrScopeInfoT> name_or_scope_info =
      this->name_or_scope_info(kAcquireLoad);
  Tagged<UnionOf<Smi, String>> name;
  if (IsScopeInfo(name_or_scope_info)) {
    name = Cast<ScopeInfo>(name_or_scope_info)->FunctionName();
  } else {
    name = Cast<UnionOf<Smi, String>>(name_or_scope_info);
  }
  DCHECK(IsString(name) || name == kNoSharedNameSentinel);
  // ScopeInfo can get promoted to read-only space. Now that we reuse them after
  // flushing bytecode, we'll actually reinstall read-only scopeinfos on
  // SharedFunctionInfos if they required a context. The read-only scopeinfos
  // should already be fully initialized though, and hence will already have the
  // right FunctionName (and InferredName if relevant).
  if (scope_info->FunctionName() != name) {
    scope_info->SetFunctionName(name);
  }
  if (HasInferredName() && inferred_name()->length() != 0 &&
      scope_info->InferredFunctionName() != inferred_name()) {
    scope_info->SetInferredFunctionName(inferred_name());
  }
  set_name_or_scope_info(scope_info, kReleaseStore, mode);
}
References v8::internal::DCHECK(), HasInferredName(), v8::kAcquireLoad, kNoSharedNameSentinel, v8::kReleaseStore, v8::internal::length, mode(), and v8::internal::name.
SetScript()
void v8::internal::SharedFunctionInfo::SetScript (IsolateForSandbox isolate, ReadOnlyRoots roots, Tagged< HeapObject > script_object, int function_literal_id, bool reset_preparsed_scope_data = true)
Definition at line 180 of file shared-function-info.cc.
                                                                    {
  DisallowGarbageCollection no_gc;
  if (script() == script_object) return;
  if (reset_preparsed_scope_data &&
      HasUncompiledDataWithPreparseData(isolate)) {
    ClearPreparseData(isolate);
  }
  // Add shared function info to new script's list. If a collection occurs,
  // the shared function info may be temporarily in two lists.
  // This is okay because the gc-time processing of these lists can tolerate
  // duplicates.
  if (IsScript(script_object)) {
    DCHECK(!IsScript(script()));
    Tagged<Script> script = Cast<Script>(script_object);
    Tagged<WeakFixedArray> list = script->infos();
#ifdef DEBUG
    DCHECK_LT(function_literal_id, list->length());
    Tagged<MaybeObject> maybe_object = list->get(function_literal_id);
    Tagged<HeapObject> heap_object;
    if (maybe_object.GetHeapObjectIfWeak(&heap_object)) {
      DCHECK_EQ(heap_object, *this);
    }
#endif
    list->set(function_literal_id, MakeWeak(Tagged(*this)));
  } else {
    DCHECK(IsScript(script()));
    // Remove shared function info from old script's list.
    Tagged<Script> old_script = Cast<Script>(script());
    // Due to liveedit, it might happen that the old_script doesn't know
    // about the SharedFunctionInfo, so we have to guard against that.
    Tagged<WeakFixedArray> infos = old_script->infos();
    if (function_literal_id < infos->length()) {
      Tagged<MaybeObject> raw = old_script->infos()->get(function_literal_id);
      Tagged<HeapObject> heap_object;
      if (raw.GetHeapObjectIfWeak(&heap_object) && heap_object == *this) {
        old_script->infos()->set(function_literal_id, roots.undefined_value());
      }
    }
  }
  // Finally set new script.
  set_script(script_object, kReleaseStore);
}
References ClearPreparseData(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LT, v8::internal::function_literal_id, v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectIfWeak(), HasUncompiledDataWithPreparseData(), v8::kReleaseStore, v8::internal::length, v8::internal::MakeWeak(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, script(), and v8::internal::Tagged().
SetTrustedData()
void v8::internal::SharedFunctionInfo::SetTrustedData (Tagged< ExposedTrustedObject > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline], [private]
Referenced by CopyFrom(), FlushBaselineCode(), overwrite_bytecode_array(), set_bytecode_array(), set_interpreter_data(), set_uncompiled_data(), and set_uncompiled_data_with_preparse_data().
SetUntrustedData()
void v8::internal::SharedFunctionInfo::SetUntrustedData (Tagged< Object > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline], [private]
Definition at line 141 of file shared-function-info-inl.h.
                                                                 {
  TaggedField<Object, kUntrustedFunctionDataOffset>::Release_Store(*this,
                                                                   value);
  // Only one of trusted_function_data and untrusted_function_data can be in
  // use, so clear the trusted data field.
  ClearTrustedPointerField(kTrustedFunctionDataOffset, kReleaseStore);
  CONDITIONAL_WRITE_BARRIER(*this, kUntrustedFunctionDataOffset, value, mode);
}
References CONDITIONAL_WRITE_BARRIER, v8::kReleaseStore, mode(), v8::internal::TaggedField< T, kFieldOffset, CompressionScheme >::Release_Store(), and v8::internal::value.
Referenced by CopyFrom().
ShouldFlushCode()
bool v8::internal::SharedFunctionInfo::ShouldFlushCode (base::EnumSet< CodeFlushMode > code_flush_mode) [inline]
SourceSize()
int v8::internal::SharedFunctionInfo::SourceSize ()
Definition at line 486 of file shared-function-info.cc.
{ return EndPosition() - StartPosition(); }
References EndPosition(), and StartPosition().
StartPosition()
int v8::internal::SharedFunctionInfo::StartPosition () const
Definition at line 714 of file shared-function-info.cc.
                                            {
  Tagged<Object> maybe_scope_info = name_or_scope_info(kAcquireLoad);
  if (IsScopeInfo(maybe_scope_info)) {
    Tagged<ScopeInfo> info = Cast<ScopeInfo>(maybe_scope_info);
    if (info->HasPositionInfo()) {
      return info->StartPosition();
    }
  }
  IsolateForSandbox isolate = GetCurrentIsolateForSandbox();
  if (HasUncompiledData(isolate)) {
    // Works with or without scope.
    return uncompiled_data(isolate)->start_position();
  }
  if (IsApiFunction() || HasBuiltinId()) {
    DCHECK_IMPLIES(HasBuiltinId(), builtin_id() != Builtin::kCompileLazy);
    return 0;
  }
#if V8_ENABLE_WEBASSEMBLY
  if (HasWasmExportedFunctionData(isolate)) {
    Tagged<WasmTrustedInstanceData> instance_data =
        wasm_exported_function_data()->instance_data();
    int func_index = wasm_exported_function_data()->function_index();
    auto& function = instance_data->module()->functions[func_index];
    return static_cast<int>(function.code.offset());
  }
#endif // V8_ENABLE_WEBASSEMBLY
  return kNoSourcePosition;
}
References DCHECK_IMPLIES, v8::internal::GetCurrentIsolateForSandbox(), HasBuiltinId(), HasUncompiledData(), v8::internal::instance_data, IsApiFunction(), v8::kAcquireLoad, v8::internal::kNoSourcePosition, and uncompiled_data().
Referenced by function_token_position(), Hash(), SourceSize(), and UniqueIdInScript().
TryGetDebugInfo()
std::optional< Tagged< DebugInfo > > v8::internal::SharedFunctionInfo::TryGetDebugInfo (Isolate * isolate) const
Definition at line 299 of file shared-function-info.cc.
                            {
  return isolate->debug()->TryGetDebugInfo(*this);
}
References v8::internal::Isolate::debug(), and v8::internal::Debug::TryGetDebugInfo().
Referenced by GetBytecodeArray().
uncompiled_data()
Tagged< UncompiledData > v8::internal::SharedFunctionInfo::uncompiled_data (IsolateForSandbox isolate) const [inline]
Definition at line 1001 of file shared-function-info-inl.h.
                                     {
  DCHECK(HasUncompiledData(isolate));
  return GetTrustedData<UncompiledData, kUncompiledDataIndirectPointerTag>(
      isolate);
}
References v8::internal::DCHECK(), and HasUncompiledData().
Referenced by ClearUncompiledDataJobPointer(), EndPosition(), set_uncompiled_data(), StartPosition(), uncompiled_data_with_preparse_data(), and UpdateFromFunctionLiteralForLiveEdit().
uncompiled_data_with_preparse_data()
Tagged< UncompiledDataWithPreparseData > v8::internal::SharedFunctionInfo::uncompiled_data_with_preparse_data (IsolateForSandbox isolate) const [inline]
Definition at line 1020 of file shared-function-info-inl.h.
                                     {
  DCHECK(HasUncompiledDataWithPreparseData(isolate));
  Tagged<UncompiledData> data = uncompiled_data(isolate);
  // TODO(saelo): this SBXCHECK is needed because our type tags don't currently
  // support type hierarchies.
  SBXCHECK(IsUncompiledDataWithPreparseData(data));
  return Cast<UncompiledDataWithPreparseData>(data);
}
References v8::internal::DCHECK(), HasUncompiledDataWithPreparseData(), SBXCHECK, and uncompiled_data().
Referenced by ClearPreparseData(), and set_uncompiled_data_with_preparse_data().
UninstallDebugBytecode()
void v8::internal::SharedFunctionInfo::UninstallDebugBytecode (Tagged< SharedFunctionInfo > shared, Isolate * isolate) [static]
Definition at line 865 of file shared-function-info.cc.
                                                         {
  DisallowGarbageCollection no_gc;
  base::MutexGuard guard(isolate->shared_function_info_access());
  Tagged<DebugInfo> debug_info = shared->GetDebugInfo(isolate);
  Tagged<BytecodeArray> original_bytecode_array =
      debug_info->OriginalBytecodeArray(isolate);
  DCHECK(!shared->HasBaselineCode());
  shared->SetActiveBytecodeArray(original_bytecode_array, isolate);
  debug_info->clear_original_bytecode_array();
  debug_info->clear_debug_bytecode_array();
}
References v8::internal::DCHECK(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::original_bytecode_array, and v8::internal::Isolate::shared_function_info_access().
Referenced by v8::internal::DebugInfo::ClearBreakInfo().
UniqueIdInScript()
int v8::internal::SharedFunctionInfo::UniqueIdInScript () const
Definition at line 282 of file shared-function-info.cc.
                                               {
  // Script scopes start "before" the script to avoid clashing with a scope that
  // starts on character 0.
  if (function_literal_id(kRelaxedLoad) == kFunctionLiteralIdTopLevel)
    return -2;
  // Wrapped functions start before the function body, but after the script
  // start, to avoid clashing with a scope starting on character 0.
  if (syntax_kind() == FunctionSyntaxKind::kWrapped) return -1;
  // Default constructors have the same start position as their parent class
  // scope. Use the next char position to distinguish this scope.
  return StartPosition() + IsDefaultConstructor(kind());
}
References v8::internal::function_literal_id, v8::internal::IsDefaultConstructor(), v8::internal::kFunctionLiteralIdTopLevel, kind(), v8::kRelaxedLoad, v8::internal::kWrapped, StartPosition(), and v8::internal::syntax_kind.
UpdateAndFinalizeExpectedNofPropertiesFromEstimate()
void v8::internal::SharedFunctionInfo::UpdateAndFinalizeExpectedNofPropertiesFromEstimate (FunctionLiteral * literal)
Definition at line 678 of file shared-function-info.cc.
                              {
  DCHECK(literal->ShouldEagerCompile());
  if (are_properties_final()) {
    return;
  }
  int estimate = get_property_estimate_from_literal(literal);
  // If no properties are added in the constructor, they are more likely
  // to be added later.
  if (estimate == 0) estimate = 2;
  // Limit actual estimate to fit in a 8 bit field, we will never allocate
  // more than this in any case.
  static_assert(JSObject::kMaxInObjectProperties <= kMaxUInt8);
  estimate = std::min(estimate, kMaxUInt8);
  set_expected_nof_properties(estimate);
  set_are_properties_final(true);
}
References v8::internal::DCHECK(), get_property_estimate_from_literal(), v8::internal::JSObject::kMaxInObjectProperties, v8::internal::kMaxUInt8, and v8::internal::FunctionLiteral::ShouldEagerCompile().
UpdateExpectedNofPropertiesFromEstimate()
void v8::internal::SharedFunctionInfo::UpdateExpectedNofPropertiesFromEstimate (FunctionLiteral * literal)
Definition at line 669 of file shared-function-info.cc.
                              {
  // Limit actual estimate to fit in a 8 bit field, we will never allocate
  // more than this in any case.
  static_assert(JSObject::kMaxInObjectProperties <= kMaxUInt8);
  int estimate = get_property_estimate_from_literal(literal);
  set_expected_nof_properties(std::min(estimate, kMaxUInt8));
}
References get_property_estimate_from_literal(), v8::internal::JSObject::kMaxInObjectProperties, and v8::internal::kMaxUInt8.
UpdateFromFunctionLiteralForLiveEdit()
void v8::internal::SharedFunctionInfo::UpdateFromFunctionLiteralForLiveEdit (IsolateForSandbox isolate, FunctionLiteral * lit)
Definition at line 772 of file shared-function-info.cc.
                                                     {
  Tagged<Object> maybe_scope_info = name_or_scope_info(kAcquireLoad);
  // TODO(crbug.com/401059828): remove once crashes are gone.
  set_live_edited(true);
  if (IsScopeInfo(maybe_scope_info)) {
    // Updating the ScopeInfo is safe since they are identical modulo
    // source positions.
    Tagged<ScopeInfo> new_scope_info = *lit->scope()->scope_info();
    Tagged<ScopeInfo> old_scope_info = Cast<ScopeInfo>(maybe_scope_info);
    DCHECK(new_scope_info->Equals(old_scope_info, true));
    old_scope_info->SetPositionInfo(new_scope_info->position_info_start(),
                                    new_scope_info->position_info_end());
  } else if (!is_compiled()) {
    CHECK(HasUncompiledData(isolate));
    if (HasUncompiledDataWithPreparseData(isolate)) {
      ClearPreparseData(isolate);
    }
    uncompiled_data(isolate)->set_start_position(lit->start_position());
    uncompiled_data(isolate)->set_end_position(lit->end_position());
    if (!is_toplevel()) {
      Scope* outer_scope = lit->scope()->GetOuterScopeWithContext();
      if (outer_scope) {
        // Use the raw accessor since we have to replace the existing outer
        // scope.
        set_raw_outer_scope_info_or_feedback_metadata(
            *outer_scope->scope_info());
      }
    }
  }
  SetFunctionTokenPosition(lit->function_token_position(),
                           lit->start_position());
}
References CHECK, ClearPreparseData(), v8::internal::DCHECK(), v8::internal::FunctionLiteral::end_position(), v8::internal::FunctionLiteral::function_token_position(), v8::internal::Scope::GetOuterScopeWithContext(), HasUncompiledData(), HasUncompiledDataWithPreparseData(), is_compiled(), v8::kAcquireLoad, v8::internal::FunctionLiteral::scope(), v8::internal::Scope::scope_info(), SetFunctionTokenPosition(), v8::internal::FunctionLiteral::start_position(), and uncompiled_data().
UpdateFunctionMapIndex()
void v8::internal::SharedFunctionInfo::UpdateFunctionMapIndex () [inline]
Definition at line 504 of file shared-function-info-inl.h.
                                                {
  int map_index =
      Context::FunctionMapIndex(language_mode(), kind(), HasSharedName());
  set_function_map_index(map_index);
}
References v8::internal::Context::FunctionMapIndex(), HasSharedName(), kind(), and language_mode().
Referenced by Init(), set_kind(), set_language_mode(), and SetName().
Friends And Related Function Documentation
FactoryBase
template<typename Impl >
friend class FactoryBase [friend]
Definition at line 833 of file shared-function-info.h.
V8HeapExplorer
friend class V8HeapExplorer [friend]
Definition at line 834 of file shared-function-info.h.
Member Data Documentation
kAgeSize
constexpr int v8::internal::SharedFunctionInfo::kAgeSize = kAgeOffsetEnd - kAgeOffset + 1 [static], [constexpr]
Definition at line 246 of file shared-function-info.h.
Referenced by CopyFrom(), v8::internal::GCTracer::NotifyMarkingStart(), and v8::internal::Serializer::ObjectSerializer::OutputRawData().
kCachedCodeOffset
const int v8::internal::SharedFunctionInfo::kCachedCodeOffset = 1 [static]
Definition at line 240 of file shared-function-info.h.
kContextOffset
const int v8::internal::SharedFunctionInfo::kContextOffset = 0 [static]
Definition at line 239 of file shared-function-info.h.
kEntriesStart
const int v8::internal::SharedFunctionInfo::kEntriesStart = 0 [static]
Definition at line 238 of file shared-function-info.h.
kEntryLength
const int v8::internal::SharedFunctionInfo::kEntryLength = 2 [static]
Definition at line 241 of file shared-function-info.h.
kFunctionTokenOutOfRange
const uint16_t v8::internal::SharedFunctionInfo::kFunctionTokenOutOfRange = static_cast<uint16_t>(-1) [static]
Definition at line 775 of file shared-function-info.h.
Referenced by function_token_position(), and SetFunctionTokenPosition().
kInitialLength
const int v8::internal::SharedFunctionInfo::kInitialLength = kEntriesStart + kEntryLength [static]
Definition at line 242 of file shared-function-info.h.
kMaxAge
constexpr uint16_t v8::internal::SharedFunctionInfo::kMaxAge = UINT16_MAX [static], [constexpr]
Definition at line 247 of file shared-function-info.h.
Referenced by EnsureOldForTesting(), and v8::internal::MarkingVisitorBase< ConcreteVisitor >::IsOld().
kMaximumFunctionTokenOffset
const int v8::internal::SharedFunctionInfo::kMaximumFunctionTokenOffset = kMaxUInt16 - 1 [static]
Definition at line 774 of file shared-function-info.h.
Referenced by SetFunctionTokenPosition().
kNoSharedNameSentinel
constexpr V8_EXPORT_PRIVATE Tagged< Smi > v8::internal::SharedFunctionInfo::kNoSharedNameSentinel [static], [constexpr]
Initial value:
=
      Smi::zero()
Definition at line 210 of file shared-function-info.h.
Referenced by v8::internal::ScopeInfo::HasSharedFunctionName(), Init(), v8::internal::IsNoSharedNameSentinel(), v8::internal::FactoryBase< Impl >::NewSharedFunctionInfo(), v8::internal::ScopeInfo::SetFunctionName(), SetName(), and SetScopeInfo().
kNotFound
const int v8::internal::SharedFunctionInfo::kNotFound = -1 [static]
Definition at line 244 of file shared-function-info.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/shared-function-info.h
/mnt/V8SourceCode/src/objects/shared-function-info-inl.h
/mnt/V8SourceCode/src/objects/shared-function-info.cc