v8::internal::TaggedMember< T, CompressionScheme > Class Template Reference
#include <tagged-field.h>
Public Member Functions
constexpr TaggedMember ()=default
Tagged< T > load () const
void store (HeapObjectLayout *host, Tagged< T > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void store_no_write_barrier (Tagged< T > value)
Tagged< T > Relaxed_Load () const
void Relaxed_Store (HeapObjectLayout *host, Tagged< T > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void Relaxed_Store_no_write_barrier (Tagged< T > value)
Tagged< T > Acquire_Load () const
void Release_Store (HeapObjectLayout *host, Tagged< T > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void Release_Store_no_write_barrier (Tagged< T > value)
Tagged< T > SeqCst_Load () const
void SeqCst_Store (HeapObjectLayout *host, Tagged< T > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
void SeqCst_Store_no_write_barrier (Tagged< T > value)
Tagged< T > SeqCst_Swap (HeapObjectLayout *host, Tagged< T > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Tagged< T > SeqCst_CompareAndSwap (HeapObjectLayout *host, Tagged< T > expected_value, Tagged< T > value, WriteBarrierMode mode=UPDATE_WRITE_BARRIER)
Private Member Functions
void WriteBarrier (HeapObjectLayout *host, Tagged< T > value, WriteBarrierMode mode)
Static Private Member Functions
static Address tagged_to_full (Tagged_t tagged_value)
static Tagged_t full_to_tagged (Address value)
Additional Inherited Members
Detailed Description
template<typename T, typename CompressionScheme>
class v8::internal::TaggedMember< T, CompressionScheme >
Definition at line 30 of file tagged-field.h.
Constructor & Destructor Documentation
TaggedMember()
template<typename T , typename CompressionScheme >
constexpr v8::internal::TaggedMember< T, CompressionScheme >::TaggedMember () [constexpr], [default]
Member Function Documentation
Acquire_Load()
template<typename T , typename CompressionScheme >
Tagged< T > v8::internal::TaggedMember< T, CompressionScheme >::Acquire_Load [inline]
Definition at line 72 of file tagged-field-inl.h.
                                                                 {
  return Tagged<T>(
      tagged_to_full(AsAtomicTagged::Acquire_Load(this->ptr_location())));
}
References v8::base::AsAtomicImpl< TAtomicStorageType >::Acquire_Load().
full_to_tagged()
template<typename T , typename CompressionScheme >
Tagged_t v8::internal::TaggedMember< T, CompressionScheme >::full_to_tagged (Address value) [inline], [static], [private]
Definition at line 36 of file tagged-field-inl.h.
                                                                         {
#ifdef V8_COMPRESS_POINTERS
  return CompressionScheme::CompressObject(value);
#else
  return value;
#endif
}
load()
template<typename T , typename CompressionScheme >
Tagged< T > v8::internal::TaggedMember< T, CompressionScheme >::load [inline]
Definition at line 45 of file tagged-field-inl.h.
                                                         {
  return Tagged<T>(tagged_to_full(ptr()));
}
Relaxed_Load()
template<typename T , typename CompressionScheme >
Tagged< T > v8::internal::TaggedMember< T, CompressionScheme >::Relaxed_Load [inline]
Definition at line 58 of file tagged-field-inl.h.
                                                                 {
  return Tagged<T>(
      tagged_to_full(AsAtomicTagged::Relaxed_Load(this->ptr_location())));
}
References v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
Relaxed_Store()
template<typename T , typename CompressionScheme >
void v8::internal::TaggedMember< T, CompressionScheme >::Relaxed_Store (HeapObjectLayout * host, Tagged< T > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 64 of file tagged-field-inl.h.
                                                                              {
  Relaxed_Store_no_write_barrier(value);
  WriteBarrier(host, value, mode);
}
Relaxed_Store_no_write_barrier()
template<typename T , typename CompressionScheme >
void v8::internal::TaggedMember< T, CompressionScheme >::Relaxed_Store_no_write_barrier (Tagged< T > value) [inline]
Definition at line 132 of file tagged-field-inl.h.
                     {
  AsAtomicTagged::Relaxed_Store(this->ptr_location(),
                                full_to_tagged(value.ptr()));
}
References v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store(), and v8::internal::value.
Release_Store()
template<typename T , typename CompressionScheme >
void v8::internal::TaggedMember< T, CompressionScheme >::Release_Store (HeapObjectLayout * host, Tagged< T > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 78 of file tagged-field-inl.h.
                                                                              {
  Release_Store_no_write_barrier(value);
  WriteBarrier(host, value, mode);
}
References mode(), and v8::internal::value.
Release_Store_no_write_barrier()
template<typename T , typename CompressionScheme >
void v8::internal::TaggedMember< T, CompressionScheme >::Release_Store_no_write_barrier (Tagged< T > value) [inline]
Definition at line 139 of file tagged-field-inl.h.
                     {
  AsAtomicTagged::Release_Store(this->ptr_location(),
                                full_to_tagged(value.ptr()));
}
References v8::base::AsAtomicImpl< TAtomicStorageType >::Release_Store(), and v8::internal::value.
SeqCst_CompareAndSwap()
template<typename T , typename CompressionScheme >
Tagged< T > v8::internal::TaggedMember< T, CompressionScheme >::SeqCst_CompareAndSwap (HeapObjectLayout * host, Tagged< T > expected_value, Tagged< T > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 109 of file tagged-field-inl.h.
                           {
  Tagged<T> old_value(tagged_to_full(AsAtomicTagged::SeqCst_CompareAndSwap(
      this->ptr_location(), full_to_tagged(expected_value.ptr()),
      full_to_tagged(value.ptr()))));
  if (old_value == expected_value) {
    WriteBarrier(host, value, mode);
  }
  return old_value;
}
References mode(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_CompareAndSwap(), and v8::internal::value.
SeqCst_Load()
template<typename T , typename CompressionScheme >
Tagged< T > v8::internal::TaggedMember< T, CompressionScheme >::SeqCst_Load [inline]
Definition at line 86 of file tagged-field-inl.h.
                                                                {
  return Tagged<T>(
      tagged_to_full(AsAtomicTagged::SeqCst_Load(this->ptr_location())));
}
References v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_Load().
SeqCst_Store()
template<typename T , typename CompressionScheme >
void v8::internal::TaggedMember< T, CompressionScheme >::SeqCst_Store (HeapObjectLayout * host, Tagged< T > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 92 of file tagged-field-inl.h.
                                                                             {
  SeqCst_Store_no_write_barrier(value);
  WriteBarrier(host, value, mode);
}
References mode(), and v8::internal::value.
SeqCst_Store_no_write_barrier()
template<typename T , typename CompressionScheme >
void v8::internal::TaggedMember< T, CompressionScheme >::SeqCst_Store_no_write_barrier (Tagged< T > value) [inline]
Definition at line 146 of file tagged-field-inl.h.
                     {
  AsAtomicTagged::SeqCst_Store(this->ptr_location(),
                               full_to_tagged(value.ptr()));
}
References v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_Store(), and v8::internal::value.
SeqCst_Swap()
template<typename T , typename CompressionScheme >
Tagged< T > v8::internal::TaggedMember< T, CompressionScheme >::SeqCst_Swap (HeapObjectLayout * host, Tagged< T > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 100 of file tagged-field-inl.h.
                                                                    {
  Tagged<T> old_value(tagged_to_full(AsAtomicTagged::SeqCst_Swap(
      this->ptr_location(), full_to_tagged(value.ptr()))));
  WriteBarrier(host, value, mode);
  return old_value;
}
References mode(), v8::base::AsAtomicImpl< TAtomicStorageType >::SeqCst_Swap(), and v8::internal::value.
store()
template<typename T , typename CompressionScheme >
void v8::internal::TaggedMember< T, CompressionScheme >::store (HeapObjectLayout * host, Tagged< T > value, WriteBarrierMode mode = UPDATE_WRITE_BARRIER) [inline]
Definition at line 50 of file tagged-field-inl.h.
                                                                      {
  store_no_write_barrier(value);
  WriteBarrier(host, value, mode);
}
store_no_write_barrier()
template<typename T , typename CompressionScheme >
void v8::internal::TaggedMember< T, CompressionScheme >::store_no_write_barrier (Tagged< T > value) [inline]
Definition at line 122 of file tagged-field-inl.h.
                     {
#ifdef V8_ATOMIC_OBJECT_FIELD_WRITES
  Relaxed_Store_no_write_barrier(value);
#else
  *this->ptr_location() = full_to_tagged(value.ptr());
#endif
}
References v8::internal::value.
tagged_to_full()
template<typename T , typename CompressionScheme >
Address v8::internal::TaggedMember< T, CompressionScheme >::tagged_to_full (Tagged_t tagged_value) [inline], [static], [private]
Definition at line 20 of file tagged-field-inl.h.
                           {
#ifdef V8_COMPRESS_POINTERS
  if constexpr (std::is_same_v<Smi, T>) {
    DCHECK(HAS_SMI_TAG(tagged_value));
    return CompressionScheme::DecompressTaggedSigned(tagged_value);
  } else {
    return CompressionScheme::DecompressTagged(tagged_value);
  }
#else
  return tagged_value;
#endif
}
References v8::internal::DCHECK(), and HAS_SMI_TAG.
WriteBarrier()
template<typename T , typename CompressionScheme >
void v8::internal::TaggedMember< T, CompressionScheme >::WriteBarrier (HeapObjectLayout * host, Tagged< T > value, WriteBarrierMode mode) [inline], [private]
Definition at line 153 of file tagged-field-inl.h.
                                                                             {
#ifndef V8_DISABLE_WRITE_BARRIERS
  if constexpr (!std::is_same_v<Smi, T>) {
#if V8_ENABLE_UNCONDITIONAL_WRITE_BARRIERS
    mode = UPDATE_WRITE_BARRIER;
#endif
    DCHECK(HeapLayout::IsOwnedByAnyHeap(Tagged(host)));
    WriteBarrier::ForValue(host, this, value, mode);
  }
#endif
}
References v8::internal::DCHECK(), v8::internal::WriteBarrier::ForValue(), v8::internal::HeapLayout::IsOwnedByAnyHeap(), mode(), v8::internal::Tagged(), v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/tagged-field.h
/mnt/V8SourceCode/src/objects/tagged-field-inl.h