v8::internal::GlobalSafepointScope Class Reference
#include <safepoint.h>
Public Member Functions
V8_EXPORT_PRIVATE GlobalSafepointScope (Isolate *initiator)
V8_EXPORT_PRIVATE ~GlobalSafepointScope ()
Private Attributes
Isolate *const initiator_
Isolate *const shared_space_isolate_
Detailed Description
Definition at line 227 of file safepoint.h.
Constructor & Destructor Documentation
GlobalSafepointScope()
v8::internal::GlobalSafepointScope::GlobalSafepointScope (Isolate * initiator) [explicit]
Definition at line 436 of file safepoint.cc.
    : initiator_(initiator),
      shared_space_isolate_(initiator->shared_space_isolate()) {
  shared_space_isolate_->global_safepoint()->EnterGlobalSafepointScope(
      initiator_);
}
References v8::internal::GlobalSafepoint::EnterGlobalSafepointScope(), v8::internal::Isolate::global_safepoint(), initiator_, and shared_space_isolate_.
 GlobalSafepointScope()
v8::internal::GlobalSafepointScope::~GlobalSafepointScope ()
Definition at line 443 of file safepoint.cc.
                                            {
  shared_space_isolate_->global_safepoint()->LeaveGlobalSafepointScope(
      initiator_);
}
References v8::internal::Isolate::global_safepoint(), initiator_, v8::internal::GlobalSafepoint::LeaveGlobalSafepointScope(), and shared_space_isolate_.
Member Data Documentation
initiator_
Isolate* const v8::internal::GlobalSafepointScope::initiator_ [private]
Definition at line 233 of file safepoint.h.
Referenced by GlobalSafepointScope(), and ~GlobalSafepointScope().
shared_space_isolate_
Isolate* const v8::internal::GlobalSafepointScope::shared_space_isolate_ [private]
Definition at line 234 of file safepoint.h.
Referenced by GlobalSafepointScope(), and ~GlobalSafepointScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/safepoint.h
/mnt/V8SourceCode/src/heap/safepoint.cc