v8::internal::EmbedderGraphImpl::V8NodeImpl Class Reference
Public Member Functions
V8NodeImpl (Tagged< Object > object)
Tagged< Object > GetObject ()
bool IsEmbedderNode () override
Must return true for non-V8 nodes.
const char * Name () override
size_t SizeInBytes () override
Private Attributes
Tagged< Object > object_
Additional Inherited Members
Detailed Description
Definition at line 3013 of file heap-snapshot-generator.cc.
Constructor & Destructor Documentation
V8NodeImpl()
v8::internal::EmbedderGraphImpl::V8NodeImpl::V8NodeImpl (Tagged< Object > object) [inline], [explicit]
Definition at line 3015 of file heap-snapshot-generator.cc.
: object_(object) {}
Member Function Documentation
GetObject()
Tagged<Object> v8::internal::EmbedderGraphImpl::V8NodeImpl::GetObject () [inline]
Definition at line 3016 of file heap-snapshot-generator.cc.
{ return object_; }
References object_.
Referenced by v8::internal::NativeObjectsExplorer::MergeNodeIntoEntry().
IsEmbedderNode()
bool v8::internal::EmbedderGraphImpl::V8NodeImpl::IsEmbedderNode () [inline], [override], [virtual]
Must return true for non-V8 nodes.
Reimplemented from v8::EmbedderGraph::Node.
Definition at line 3019 of file heap-snapshot-generator.cc.
{ return false; }
Name()
const char* v8::internal::EmbedderGraphImpl::V8NodeImpl::Name () [inline], [override], [virtual]
Implements v8::EmbedderGraph::Node.
Definition at line 3020 of file heap-snapshot-generator.cc.
                                {
      // The name should be retrieved via GetObject().
      UNREACHABLE();
    }
References v8::internal::UNREACHABLE().
SizeInBytes()
size_t v8::internal::EmbedderGraphImpl::V8NodeImpl::SizeInBytes () [inline], [override], [virtual]
Implements v8::EmbedderGraph::Node.
Definition at line 3024 of file heap-snapshot-generator.cc.
                                  {
      // The size should be retrieved via GetObject().
      UNREACHABLE();
    }
References v8::internal::UNREACHABLE().
Member Data Documentation
object_
Tagged<Object> v8::internal::EmbedderGraphImpl::V8NodeImpl::object_ [private]
Definition at line 3030 of file heap-snapshot-generator.cc.
Referenced by GetObject().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/profiler/heap-snapshot-generator.cc