v8::internal::SemiSpaceNewSpaceAllocatorPolicy Class Reference
#include <main-allocator.h>
Public Member Functions
SemiSpaceNewSpaceAllocatorPolicy (SemiSpaceNewSpace *space, MainAllocator *allocator)
bool EnsureAllocation (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin) final
void FreeLinearAllocationArea () final
Private Member Functions
void FreeLinearAllocationAreaUnsynchronized ()
Private Attributes
SemiSpaceNewSpace *const space_
Static Private Attributes
static constexpr int kLabSizeInGC = 32 * KB
Additional Inherited Members
Detailed Description
Definition at line 52 of file main-allocator.h.
Constructor & Destructor Documentation
SemiSpaceNewSpaceAllocatorPolicy()
v8::internal::SemiSpaceNewSpaceAllocatorPolicy::SemiSpaceNewSpaceAllocatorPolicy (SemiSpaceNewSpace * space, MainAllocator * allocator) [inline], [explicit]
Definition at line 54 of file main-allocator.h.
      : AllocatorPolicy(allocator), space_(space) {}
Member Function Documentation
EnsureAllocation()
bool v8::internal::SemiSpaceNewSpaceAllocatorPolicy::EnsureAllocation (int size_in_bytes, AllocationAlignment alignment, AllocationOrigin origin) [final], [virtual]
Implements v8::internal::AllocatorPolicy.
Definition at line 449 of file main-allocator.cc.
                                                                               {
  std::optional<base::MutexGuard> guard;
  if (allocator_->in_gc()) guard.emplace(space_->mutex());
  FreeLinearAllocationAreaUnsynchronized();
  std::optional<std::pair<Address, Address>> allocation_result =
      space_->Allocate(size_in_bytes, alignment);
  if (!allocation_result) {
    if (!space_->ReachedTargetCapacity()) {
      // If allocation failed even though we have not even grown the space to
      // its target capacity yet, we can bail out early.
      return false;
    }
    if (!space_->heap()->ShouldExpandYoungGenerationOnSlowAllocation(
            PageMetadata::kPageSize)) {
      return false;
    }
    allocation_result =
        space_->AllocateOnNewPageBeyondCapacity(size_in_bytes, alignment);
    if (!allocation_result) return false;
  }
  Address start = allocation_result->first;
  Address end = allocation_result->second;
  int filler_size = Heap::GetFillToAlign(start, alignment);
  int aligned_size_in_bytes = size_in_bytes + filler_size;
  DCHECK_LE(start + aligned_size_in_bytes, end);
  Address limit;
  if (allocator_->in_gc()) {
    // During GC we allow multiple LABs in new space and since Allocate() above
    // returns the whole remaining page by default, we limit the size of the LAB
    // here.
    size_t used = std::max(aligned_size_in_bytes, kLabSizeInGC);
    limit = std::min(end, start + used);
  } else {
    limit = allocator_->ComputeLimit(start, end, aligned_size_in_bytes);
  }
  CHECK_LE(limit, end);
  if (limit != end) {
    space_->Free(limit, end);
  }
  allocator_->ResetLab(start, limit, limit);
  space_->to_space().AddRangeToActiveSystemPages(allocator_->top(),
                                                 allocator_->limit());
  return true;
}
References v8::internal::SemiSpace::AddRangeToActiveSystemPages(), v8::internal::SemiSpaceNewSpace::Allocate(), v8::internal::SemiSpaceNewSpace::AllocateOnNewPageBeyondCapacity(), v8::internal::AllocatorPolicy::allocator_, CHECK_LE, v8::internal::MainAllocator::ComputeLimit(), DCHECK_LE, v8::internal::compiler::end(), v8::internal::SemiSpaceNewSpace::Free(), FreeLinearAllocationAreaUnsynchronized(), v8::internal::Heap::GetFillToAlign(), v8::internal::MainAllocator::in_gc(), kLabSizeInGC, v8::internal::MutablePageMetadata::kPageSize, v8::internal::MainAllocator::limit(), v8::internal::NewSpace::mutex(), v8::internal::SemiSpaceNewSpace::ReachedTargetCapacity(), v8::internal::MainAllocator::ResetLab(), space_, v8::internal::SemiSpaceNewSpace::to_space(), and v8::internal::MainAllocator::top().
FreeLinearAllocationArea()
void v8::internal::SemiSpaceNewSpaceAllocatorPolicy::FreeLinearAllocationArea () [final], [virtual]
Implements v8::internal::AllocatorPolicy.
Definition at line 505 of file main-allocator.cc.
                                                                {
  if (!allocator_->IsLabValid()) return;
#if DEBUG
  allocator_->Verify();
#endif // DEBUG
  std::optional<base::MutexGuard> guard;
  if (allocator_->in_gc()) guard.emplace(space_->mutex());
  FreeLinearAllocationAreaUnsynchronized();
}
References v8::internal::AllocatorPolicy::allocator_, FreeLinearAllocationAreaUnsynchronized(), v8::internal::MainAllocator::in_gc(), v8::internal::MainAllocator::IsLabValid(), v8::internal::NewSpace::mutex(), and space_.
FreeLinearAllocationAreaUnsynchronized()
void v8::internal::SemiSpaceNewSpaceAllocatorPolicy::FreeLinearAllocationAreaUnsynchronized () [private]
Definition at line 518 of file main-allocator.cc.
                                             {
  if (!allocator_->IsLabValid()) return;
  Address current_top = allocator_->top();
  Address current_limit = allocator_->limit();
  allocator_->AdvanceAllocationObservers();
  allocator_->ResetLab(kNullAddress, kNullAddress, kNullAddress);
  space_->Free(current_top, current_limit);
}
References v8::internal::MainAllocator::AdvanceAllocationObservers(), v8::internal::AllocatorPolicy::allocator_, v8::internal::SemiSpaceNewSpace::Free(), v8::internal::MainAllocator::IsLabValid(), v8::internal::kNullAddress, v8::internal::MainAllocator::limit(), v8::internal::MainAllocator::ResetLab(), space_, and v8::internal::MainAllocator::top().
Referenced by EnsureAllocation(), and FreeLinearAllocationArea().
Member Data Documentation
kLabSizeInGC
constexpr int v8::internal::SemiSpaceNewSpaceAllocatorPolicy::kLabSizeInGC = 32 * KB [static], [constexpr], [private]
Definition at line 63 of file main-allocator.h.
Referenced by EnsureAllocation().
space_
SemiSpaceNewSpace* const v8::internal::SemiSpaceNewSpaceAllocatorPolicy::space_ [private]
Definition at line 67 of file main-allocator.h.
Referenced by EnsureAllocation(), FreeLinearAllocationArea(), and FreeLinearAllocationAreaUnsynchronized().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/main-allocator.h
/mnt/V8SourceCode/src/heap/main-allocator.cc