v8::internal::RelocatingCharacterStream Class Reference
Public Member Functions
template<class... TArgs>
RelocatingCharacterStream (Isolate *isolate, size_t pos, TArgs... args)
Private Member Functions
~RelocatingCharacterStream () final
void UpdateBufferPointers ()
Static Private Member Functions
static void UpdateBufferPointersCallback (void *stream)
Private Attributes
Isolate * isolate_
Additional Inherited Members
Detailed Description
Definition at line 342 of file scanner-character-streams.cc.
Constructor & Destructor Documentation
RelocatingCharacterStream()
template<class... TArgs>
v8::internal::RelocatingCharacterStream::RelocatingCharacterStream (Isolate * isolate, size_t pos, TArgs... args) [inline]
Definition at line 346 of file scanner-character-streams.cc.
      : UnbufferedCharacterStream<OnHeapStream>(pos, args...),
        isolate_(isolate) {
    isolate->main_thread_local_heap()->AddGCEpilogueCallback(
        UpdateBufferPointersCallback, this);
  }
References v8::internal::LocalHeap::AddGCEpilogueCallback(), v8::internal::Isolate::main_thread_local_heap(), and UpdateBufferPointersCallback().
 RelocatingCharacterStream()
v8::internal::RelocatingCharacterStream::~RelocatingCharacterStream () [inline], [final], [private]
Definition at line 354 of file scanner-character-streams.cc.
                                     {
    isolate_->main_thread_local_heap()->RemoveGCEpilogueCallback(
        UpdateBufferPointersCallback, this);
  }
References isolate_, v8::internal::Isolate::main_thread_local_heap(), v8::internal::LocalHeap::RemoveGCEpilogueCallback(), and UpdateBufferPointersCallback().
Member Function Documentation
UpdateBufferPointers()
void v8::internal::RelocatingCharacterStream::UpdateBufferPointers () [inline], [private]
Definition at line 364 of file scanner-character-streams.cc.
                              {
    DisallowGarbageCollection no_gc;
    Range<uint16_t> range =
        byte_stream_.GetDataAt(buffer_pos_, runtime_call_stats(), &no_gc);
    if (range.start != buffer_start_) {
      buffer_cursor_ = (buffer_cursor_ - buffer_start_) + range.start;
      buffer_start_ = range.start;
      buffer_end_ = range.end;
    }
  }
References v8::internal::Utf16CharacterStream::buffer_cursor_, v8::internal::Utf16CharacterStream::buffer_end_, v8::internal::Utf16CharacterStream::buffer_pos_, v8::internal::Utf16CharacterStream::buffer_start_, v8::internal::UnbufferedCharacterStream< OnHeapStream >::byte_stream_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and v8::internal::Utf16CharacterStream::runtime_call_stats().
Referenced by UpdateBufferPointersCallback().
UpdateBufferPointersCallback()
static void v8::internal::RelocatingCharacterStream::UpdateBufferPointersCallback (void * stream) [inline], [static], [private]
Definition at line 359 of file scanner-character-streams.cc.
                                                         {
    reinterpret_cast<RelocatingCharacterStream*>(stream)
        ->UpdateBufferPointers();
  }
References UpdateBufferPointers().
Referenced by RelocatingCharacterStream(), and ~RelocatingCharacterStream().
Member Data Documentation
isolate_
Isolate* v8::internal::RelocatingCharacterStream::isolate_ [private]
Definition at line 375 of file scanner-character-streams.cc.
Referenced by ~RelocatingCharacterStream().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/scanner-character-streams.cc