v8::internal::BackgroundDeserializeTask Class Reference
#include <compiler.h>
Public Member Functions
BackgroundDeserializeTask (Isolate *isolate, std::unique_ptr< ScriptCompiler::CachedData > data)
void Run ()
void SourceTextAvailable (Isolate *isolate, Handle< String > source_text, const ScriptDetails &script_details)
bool ShouldMergeWithExistingScript () const
void MergeWithExistingScript ()
MaybeDirectHandle< SharedFunctionInfo > Finish (Isolate *isolate, DirectHandle< String > source, const ScriptDetails &script_details)
bool rejected () const
int64_t background_time_in_microseconds () const
Private Attributes
Isolate * isolate_for_local_isolate_
AlignedCachedData cached_data_
CodeSerializer::OffThreadDeserializeData off_thread_data_
BackgroundMergeTask background_merge_task_
TimedHistogram * timer_
int64_t background_time_in_microseconds_ = 0
Detailed Description
Definition at line 685 of file compiler.h.
Constructor & Destructor Documentation
BackgroundDeserializeTask()
v8::internal::BackgroundDeserializeTask::BackgroundDeserializeTask (Isolate * isolate, std::unique_ptr< ScriptCompiler::CachedData > data)
Definition at line 2745 of file compiler.cc.
    : isolate_for_local_isolate_(isolate),
      cached_data_(cached_data->data, cached_data->length),
      timer_(isolate->counters()->deserialize_script_on_background()) {
  // If the passed in cached data has ownership of the buffer, move it to the
  // task.
  if (cached_data->buffer_policy == ScriptCompiler::CachedData::BufferOwned &&
      !cached_data_.HasDataOwnership()) {
    cached_data->buffer_policy = ScriptCompiler::CachedData::BufferNotOwned;
    cached_data_.AcquireDataOwnership();
  }
}
References v8::internal::AlignedCachedData::AcquireDataOwnership(), v8::ScriptCompiler::CachedData::BufferNotOwned, v8::ScriptCompiler::CachedData::BufferOwned, cached_data_, and v8::internal::AlignedCachedData::HasDataOwnership().
Member Function Documentation
background_time_in_microseconds()
int64_t v8::internal::BackgroundDeserializeTask::background_time_in_microseconds () const [inline]
Definition at line 717 of file compiler.h.
                                                  {
    return background_time_in_microseconds_;
  }
Referenced by v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl().
Finish()
MaybeDirectHandle< SharedFunctionInfo > v8::internal::BackgroundDeserializeTask::Finish (Isolate * isolate, DirectHandle< String > source, const ScriptDetails & script_details)
Definition at line 2802 of file compiler.cc.
                                         {
  return CodeSerializer::FinishOffThreadDeserialize(
      isolate, std::move(off_thread_data_), &cached_data_, source,
      script_details, &background_merge_task_);
}
References background_merge_task_, cached_data_, v8::internal::CodeSerializer::FinishOffThreadDeserialize(), and off_thread_data_.
Referenced by v8::internal::anonymous_namespace{compiler.cc}::GetSharedFunctionInfoForScriptImpl().
MergeWithExistingScript()
void v8::internal::BackgroundDeserializeTask::MergeWithExistingScript ()
Definition at line 2791 of file compiler.cc.
                                                        {
  DCHECK(ShouldMergeWithExistingScript());
  LocalIsolate isolate(isolate_for_local_isolate_, ThreadKind::kBackground);
  UnparkedScope unparked_scope(&isolate);
  LocalHandleScope handle_scope(isolate.heap());
  background_merge_task_.BeginMergeInBackground(
      &isolate, off_thread_data_.GetOnlyScript(isolate.heap()));
}
References background_merge_task_, v8::internal::BackgroundMergeTask::BeginMergeInBackground(), v8::internal::DCHECK(), v8::internal::CodeSerializer::OffThreadDeserializeData::GetOnlyScript(), v8::internal::LocalIsolate::heap(), isolate_for_local_isolate_, v8::internal::kBackground, off_thread_data_, and ShouldMergeWithExistingScript().
rejected()
bool v8::internal::BackgroundDeserializeTask::rejected () const [inline]
Definition at line 715 of file compiler.h.
{ return cached_data_.rejected(); }
Run()
void v8::internal::BackgroundDeserializeTask::Run ()
Definition at line 2759 of file compiler.cc.
                                    {
  TimedHistogramScope timer(timer_, nullptr, &background_time_in_microseconds_);
  LocalIsolate isolate(isolate_for_local_isolate_, ThreadKind::kBackground);
  UnparkedScope unparked_scope(&isolate);
  LocalHandleScope handle_scope(&isolate);
  DirectHandle<SharedFunctionInfo> inner_result;
  off_thread_data_ =
      CodeSerializer::StartDeserializeOffThread(&isolate, &cached_data_);
  if (v8_flags.enable_slow_asserts && off_thread_data_.HasResult()) {
#ifdef ENABLE_SLOW_DCHECKS
    MergeAssumptionChecker checker(&isolate);
    checker.IterateObjects(*off_thread_data_.GetOnlyScript(isolate.heap()));
#endif
  }
}
References background_time_in_microseconds_, cached_data_, v8::internal::CodeSerializer::OffThreadDeserializeData::GetOnlyScript(), v8::internal::CodeSerializer::OffThreadDeserializeData::HasResult(), v8::internal::LocalIsolate::heap(), isolate_for_local_isolate_, v8::internal::kBackground, off_thread_data_, v8::internal::CodeSerializer::StartDeserializeOffThread(), timer_, and v8::internal::v8_flags.
ShouldMergeWithExistingScript()
bool v8::internal::BackgroundDeserializeTask::ShouldMergeWithExistingScript () const
Definition at line 2785 of file compiler.cc.
                                                                    {
  DCHECK(v8_flags.merge_background_deserialized_script_with_compilation_cache);
  return background_merge_task_.HasPendingBackgroundWork() &&
         off_thread_data_.HasResult();
}
References background_merge_task_, v8::internal::DCHECK(), v8::internal::BackgroundMergeTask::HasPendingBackgroundWork(), v8::internal::CodeSerializer::OffThreadDeserializeData::HasResult(), off_thread_data_, and v8::internal::v8_flags.
Referenced by MergeWithExistingScript().
SourceTextAvailable()
void v8::internal::BackgroundDeserializeTask::SourceTextAvailable (Isolate * isolate, Handle< String > source_text, const ScriptDetails & script_details)
Definition at line 2776 of file compiler.cc.
                                         {
  DCHECK_EQ(isolate, isolate_for_local_isolate_);
  LanguageMode language_mode = construct_language_mode(v8_flags.use_strict);
  background_merge_task_.SetUpOnMainThread(isolate, source_text, script_details,
                                           language_mode);
}
References background_merge_task_, v8::internal::construct_language_mode(), DCHECK_EQ, isolate_for_local_isolate_, v8::internal::BackgroundMergeTask::SetUpOnMainThread(), and v8::internal::v8_flags.
Member Data Documentation
background_merge_task_
BackgroundMergeTask v8::internal::BackgroundDeserializeTask::background_merge_task_ [private]
Definition at line 725 of file compiler.h.
Referenced by Finish(), MergeWithExistingScript(), ShouldMergeWithExistingScript(), and SourceTextAvailable().
background_time_in_microseconds_
int64_t v8::internal::BackgroundDeserializeTask::background_time_in_microseconds_ = 0 [private]
Definition at line 727 of file compiler.h.
Referenced by Run().
cached_data_
AlignedCachedData v8::internal::BackgroundDeserializeTask::cached_data_ [private]
Definition at line 723 of file compiler.h.
Referenced by BackgroundDeserializeTask(), Finish(), and Run().
isolate_for_local_isolate_
Isolate* v8::internal::BackgroundDeserializeTask::isolate_for_local_isolate_ [private]
Definition at line 722 of file compiler.h.
Referenced by MergeWithExistingScript(), Run(), and SourceTextAvailable().
off_thread_data_
CodeSerializer::OffThreadDeserializeData v8::internal::BackgroundDeserializeTask::off_thread_data_ [private]
Definition at line 724 of file compiler.h.
Referenced by Finish(), MergeWithExistingScript(), Run(), and ShouldMergeWithExistingScript().
timer_
TimedHistogram* v8::internal::BackgroundDeserializeTask::timer_ [private]
Definition at line 726 of file compiler.h.
Referenced by Run().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/compiler.h
/mnt/V8SourceCode/src/codegen/compiler.cc