v8::internal::compiler::TurboshaftStateObjectDeduplicator Class Reference
Public Member Functions
TurboshaftStateObjectDeduplicator (Zone *zone)
size_t GetObjectId (uint32_t old_id, ObjectType type)
size_t InsertObject (uint32_t old_id, ObjectType type)
void InsertDummyForArgumentsElements ()
Static Public Attributes
static constexpr size_t kNotDuplicated = std::numeric_limits<size_t>::max()
Private Member Functions
ZoneAbslFlatHashMap< uint32_t, uint32_t > & GetMapForType (ObjectType type)
Private Attributes
uint32_t next_id_ = 0
ZoneAbslFlatHashMap< uint32_t, uint32_t > objects_ids_mapping_
ZoneAbslFlatHashMap< uint32_t, uint32_t > string_ids_mapping_
Detailed Description
Definition at line 710 of file instruction-selector.cc.
Constructor & Destructor Documentation
TurboshaftStateObjectDeduplicator()
v8::internal::compiler::TurboshaftStateObjectDeduplicator::TurboshaftStateObjectDeduplicator (Zone * zone) [inline], [explicit]
Definition at line 712 of file instruction-selector.cc.
      : objects_ids_mapping_(zone), string_ids_mapping_(zone) {}
Member Function Documentation
GetMapForType()
ZoneAbslFlatHashMap<uint32_t, uint32_t>& v8::internal::compiler::TurboshaftStateObjectDeduplicator::GetMapForType (ObjectType type) [inline], [private]
Definition at line 733 of file instruction-selector.cc.
                                                                          {
    switch (type) {
      case ObjectType::kRegularObject:
        return objects_ids_mapping_;
      case ObjectType::kStringConcat:
        return string_ids_mapping_;
    }
  }
References v8::internal::compiler::kRegularObject, v8::internal::compiler::kStringConcat, objects_ids_mapping_, string_ids_mapping_, and v8::internal::tracing::type.
Referenced by GetObjectId(), and InsertObject().
GetObjectId()
size_t v8::internal::compiler::TurboshaftStateObjectDeduplicator::GetObjectId (uint32_t old_id, ObjectType type) [inline]
Definition at line 716 of file instruction-selector.cc.
                                                       {
    auto& ids_map = GetMapForType(type);
    auto it = ids_map.find(old_id);
    if (it == ids_map.end()) return kNotDuplicated;
    return it->second;
  }
References GetMapForType(), kNotDuplicated, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor().
InsertDummyForArgumentsElements()
void v8::internal::compiler::TurboshaftStateObjectDeduplicator::InsertDummyForArgumentsElements () [inline]
Definition at line 730 of file instruction-selector.cc.
{ next_id_++; }
References next_id_.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor().
InsertObject()
size_t v8::internal::compiler::TurboshaftStateObjectDeduplicator::InsertObject (uint32_t old_id, ObjectType type) [inline]
Definition at line 723 of file instruction-selector.cc.
                                                        {
    auto& ids_map = GetMapForType(type);
    uint32_t new_id = next_id_++;
    ids_map.insert({old_id, new_id});
    return new_id;
  }
References GetMapForType(), next_id_, and v8::internal::tracing::type.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor().
Member Data Documentation
kNotDuplicated
constexpr size_t v8::internal::compiler::TurboshaftStateObjectDeduplicator::kNotDuplicated = std::numeric_limits<size_t>::max() [static], [constexpr]
Definition at line 714 of file instruction-selector.cc.
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), and GetObjectId().
next_id_
uint32_t v8::internal::compiler::TurboshaftStateObjectDeduplicator::next_id_ = 0 [private]
Definition at line 741 of file instruction-selector.cc.
Referenced by InsertDummyForArgumentsElements(), and InsertObject().
objects_ids_mapping_
ZoneAbslFlatHashMap<uint32_t, uint32_t> v8::internal::compiler::TurboshaftStateObjectDeduplicator::objects_ids_mapping_ [private]
Definition at line 743 of file instruction-selector.cc.
Referenced by GetMapForType().
string_ids_mapping_
ZoneAbslFlatHashMap<uint32_t, uint32_t> v8::internal::compiler::TurboshaftStateObjectDeduplicator::string_ids_mapping_ [private]
Definition at line 744 of file instruction-selector.cc.
Referenced by GetMapForType().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/instruction-selector.cc