v8::internal::BaseCollectionsAssembler Class Reference
#include <builtins-collections-gen.h>
Public Member Functions
BaseCollectionsAssembler (compiler::CodeAssemblerState *state)
virtual ~BaseCollectionsAssembler ()=default
void GotoIfCannotBeHeldWeakly (const TNode< Object > obj, Label *if_cannot_be_held_weakly)
Protected Types
enum Variant { kMap
, kSet
, kWeakMap
, kWeakSet
 }
Protected Member Functions
void AddConstructorEntry (Variant variant, TNode< Context > context, TNode< JSAny > collection, TNode< Object > add_function, TNode< JSAny > key_value, Label *if_may_have_side_effects=nullptr, Label *if_exception=nullptr, TVariable< Object > *var_exception=nullptr)
virtual void GetEntriesIfFastCollectionOrIterable (Variant variant, TNode< Object > initial_entries, TNode< Context > context, TVariable< HeapObject > *var_entries_table, TVariable< IntPtrT > *var_number_of_elements, Label *if_not_fast_collection)=0
void AddConstructorEntries (Variant variant, TNode< Context > context, TNode< NativeContext > native_context, TNode< JSAnyNotSmi > collection, TNode< JSAny > initial_entries)
void AddConstructorEntriesFromFastJSArray (Variant variant, TNode< Context > context, TNode< Context > native_context, TNode< JSAny > collection, TNode< JSArray > fast_jsarray, Label *if_may_have_side_effects, TVariable< IntPtrT > &var_current_index)
void AddConstructorEntriesFromIterable (Variant variant, TNode< Context > context, TNode< Context > native_context, TNode< JSAny > collection, TNode< JSAny > iterable, Label *if_exception, TVariable< JSReceiver > *var_iterator, TVariable< Object > *var_exception)
virtual void AddConstructorEntriesFromFastCollection (Variant variant, TNode< HeapObject > collection, TNode< HeapObject > source_table)=0
TNode< JSObject > AllocateJSCollection (TNode< Context > context, TNode< JSFunction > constructor, TNode< JSReceiver > new_target)
TNode< JSObject > AllocateJSCollectionFast (TNode< JSFunction > constructor)
TNode< JSObject > AllocateJSCollectionSlow (TNode< Context > context, TNode< JSFunction > constructor, TNode< JSReceiver > new_target)
virtual TNode< HeapObject > AllocateTable (Variant variant, TNode< IntPtrT > at_least_space_for)=0
void GenerateConstructor (Variant variant, Handle< String > constructor_function_name, TNode< Object > new_target, TNode< IntPtrT > argc, TNode< Context > context)
TNode< Object > GetAddFunction (Variant variant, TNode< Context > context, TNode< JSAny > collection)
TNode< JSFunction > GetConstructor (Variant variant, TNode< Context > native_context)
TNode< JSFunction > GetInitialAddFunction (Variant variant, TNode< Context > native_context)
void GotoIfInitialAddFunctionModified (Variant variant, TNode< NativeContext > native_context, TNode< HeapObject > collection, Label *if_modified)
RootIndex GetAddFunctionNameIndex (Variant variant)
int GetTableOffset (Variant variant)
TNode< BoolT > HasInitialCollectionPrototype (Variant variant, TNode< Context > native_context, TNode< JSAny > collection)
TNode< Map > GetInitialCollectionPrototype (Variant variant, TNode< Context > native_context)
TNode< Object > LoadAndNormalizeFixedArrayElement (TNode< FixedArray > elements, TNode< IntPtrT > index)
TNode< Object > LoadAndNormalizeFixedDoubleArrayElement (TNode< HeapObject > elements, TNode< IntPtrT > index)
Additional Inherited Members
Detailed Description
Definition at line 23 of file builtins-collections-gen.h.
Member Enumeration Documentation
Variant
enum v8::internal::BaseCollectionsAssembler::Variant [protected]
Enumerator
kMap
kSet
kWeakMap
kWeakSet
Definition at line 34 of file builtins-collections-gen.h.
{ kMap, kSet, kWeakMap, kWeakSet };
Constructor & Destructor Documentation
BaseCollectionsAssembler()
v8::internal::BaseCollectionsAssembler::BaseCollectionsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 25 of file builtins-collections-gen.h.
      : CodeStubAssembler(state) {}
 BaseCollectionsAssembler()
virtual v8::internal::BaseCollectionsAssembler::~BaseCollectionsAssembler () [virtual], [default]
Member Function Documentation
AddConstructorEntries()
void v8::internal::BaseCollectionsAssembler::AddConstructorEntries (Variant variant, TNode< Context > context, TNode< NativeContext > native_context, TNode< JSAnyNotSmi > collection, TNode< JSAny > initial_entries) [protected]
Definition at line 49 of file builtins-collections-gen.cc.
                                  {
  CSA_DCHECK(this, Word32BinaryNot(IsNullOrUndefined(initial_entries)));
  enum Mode { kSlow, kFastJSArray, kFastCollection };
  TVARIABLE(IntPtrT, var_at_least_space_for, IntPtrConstant(0));
  TVARIABLE(HeapObject, var_entries_table, UndefinedConstant());
  TVARIABLE(Int32T, var_mode, Int32Constant(kSlow));
  Label if_fast_js_array(this), allocate_table(this);
  // The slow path is taken if the initial add function is modified. This check
  // must precede the kSet fast path below, which has the side effect of
  // exhausting {initial_entries} if it is a JSSetIterator.
  GotoIfInitialAddFunctionModified(variant, native_context, collection,
                                   &allocate_table);
  GotoIf(IsFastJSArrayWithNoCustomIteration(context, initial_entries),
         &if_fast_js_array);
  if (variant == Variant::kSet) {
    GetEntriesIfFastCollectionOrIterable(
        variant, initial_entries, context, &var_entries_table,
        &var_at_least_space_for, &allocate_table);
    var_mode = Int32Constant(kFastCollection);
    Goto(&allocate_table);
  } else {
    Goto(&allocate_table);
  }
  BIND(&if_fast_js_array);
  {
    var_mode = Int32Constant(kFastJSArray);
    if (variant == kWeakSet || variant == kWeakMap) {
      var_at_least_space_for =
          PositiveSmiUntag(LoadFastJSArrayLength(CAST(initial_entries)));
    } else {
      // TODO(ishell): consider using array length for all collections
      static_assert(OrderedHashSet::kInitialCapacity ==
                    OrderedHashMap::kInitialCapacity);
      var_at_least_space_for = IntPtrConstant(OrderedHashSet::kInitialCapacity);
    }
    Goto(&allocate_table);
  }
  TVARIABLE(JSReceiver, var_iterator_object);
  TVARIABLE(Object, var_exception);
  Label exit(this), from_fast_jsarray(this), from_fast_collection(this),
      slow_loop(this, Label::kDeferred), if_exception(this, Label::kDeferred);
  BIND(&allocate_table);
  {
    TNode<HeapObject> table =
        AllocateTable(variant, var_at_least_space_for.value());
    StoreObjectField(collection, GetTableOffset(variant), table);
    if (variant == Variant::kSet) {
      GotoIf(Word32Equal(var_mode.value(), Int32Constant(kFastCollection)),
             &from_fast_collection);
    }
    Branch(Word32Equal(var_mode.value(), Int32Constant(kFastJSArray)),
           &from_fast_jsarray, &slow_loop);
  }
  BIND(&from_fast_jsarray);
  {
    Label if_exception_during_fast_iteration(this, Label::kDeferred);
    TVARIABLE(IntPtrT, var_index, IntPtrConstant(0));
    TNode<JSArray> initial_entries_jsarray =
        UncheckedCast<JSArray>(initial_entries);
#if DEBUG
    CSA_DCHECK(this, IsFastJSArrayWithNoCustomIteration(
                         context, initial_entries_jsarray));
    TNode<Map> original_initial_entries_map = LoadMap(initial_entries_jsarray);
#endif
    Label if_may_have_side_effects(this, Label::kDeferred);
    {
      compiler::ScopedExceptionHandler handler(
          this, &if_exception_during_fast_iteration, &var_exception);
      AddConstructorEntriesFromFastJSArray(
          variant, context, native_context, collection, initial_entries_jsarray,
          &if_may_have_side_effects, var_index);
    }
    Goto(&exit);
    if (variant == kMap || variant == kWeakMap) {
      BIND(&if_may_have_side_effects);
#if DEBUG
      {
        // Check that add/set function has not been modified.
        Label if_not_modified(this), if_modified(this);
        GotoIfInitialAddFunctionModified(variant, native_context, collection,
                                         &if_modified);
        Goto(&if_not_modified);
        BIND(&if_modified);
        Unreachable();
        BIND(&if_not_modified);
      }
      CSA_DCHECK(this, TaggedEqual(original_initial_entries_map,
                                   LoadMap(initial_entries_jsarray)));
#endif
      var_mode = Int32Constant(kSlow);
      Goto(&allocate_table);
    }
    BIND(&if_exception_during_fast_iteration);
    {
      // In case exception is thrown during collection population, materialize
      // the iteator and execute iterator closing protocol. It might be
      // non-trivial in case "return" callback is added somewhere in the
      // iterator's prototype chain.
      TNode<IntPtrT> next_index =
          IntPtrAdd(var_index.value(), IntPtrConstant(1));
      var_iterator_object = CreateArrayIterator(
          LoadNativeContext(context), UncheckedCast<JSArray>(initial_entries),
          IterationKind::kValues, SmiTag(next_index));
      Goto(&if_exception);
    }
  }
  if (variant == Variant::kSet) {
    BIND(&from_fast_collection);
    {
      AddConstructorEntriesFromFastCollection(variant, collection,
                                              var_entries_table.value());
      Goto(&exit);
    }
  }
  BIND(&slow_loop);
  {
    AddConstructorEntriesFromIterable(
        variant, context, native_context, collection, initial_entries,
        &if_exception, &var_iterator_object, &var_exception);
    Goto(&exit);
  }
  BIND(&if_exception);
  {
    TNode<HeapObject> message = GetPendingMessage();
    SetPendingMessage(TheHoleConstant());
    // iterator.next field is not used by IteratorCloseOnException.
    TorqueStructIteratorRecord iterator = {var_iterator_object.value(), {}};
    IteratorCloseOnException(context, iterator.object);
    CallRuntime(Runtime::kReThrowWithMessage, context, var_exception.value(),
                message);
    Unreachable();
  }
  BIND(&exit);
}
References AddConstructorEntriesFromFastCollection(), AddConstructorEntriesFromFastJSArray(), AddConstructorEntriesFromIterable(), AllocateTable(), v8::internal::compiler::CodeAssembler::Branch(), v8::internal::compiler::CodeAssembler::CallRuntime(), CAST, GetEntriesIfFastCollectionOrIterable(), v8::internal::CodeStubAssembler::GetPendingMessage(), GetTableOffset(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), GotoIfInitialAddFunctionModified(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::IntPtrAdd(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::IsNullOrUndefined(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::OrderedHashTable< OrderedHashSet, 1 >::kInitialCapacity, v8::internal::OrderedHashTable< OrderedHashMap, 2 >::kInitialCapacity, kMap, v8::internal::kSlow, v8::internal::kValues, kWeakMap, kWeakSet, v8::internal::CodeStubAssembler::LoadFastJSArrayLength(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::native_context, v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::internal::CodeStubAssembler::SetPendingMessage(), v8::internal::CodeStubAssembler::SmiTag(), v8::internal::CodeStubAssembler::StoreObjectField(), v8::internal::CodeStubAssembler::TaggedEqual(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), v8::internal::compiler::CodeAssembler::Unreachable(), and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by GenerateConstructor().
AddConstructorEntriesFromFastCollection()
virtual void v8::internal::BaseCollectionsAssembler::AddConstructorEntriesFromFastCollection (Variant variant, TNode< HeapObject > collection, TNode< HeapObject > source_table) [protected], [pure virtual]
Implemented in v8::internal::WeakCollectionsBuiltinsAssembler, and v8::internal::CollectionsBuiltinsAssembler.
Referenced by AddConstructorEntries().
AddConstructorEntriesFromFastJSArray()
void v8::internal::BaseCollectionsAssembler::AddConstructorEntriesFromFastJSArray (Variant variant, TNode< Context > context, TNode< Context > native_context, TNode< JSAny > collection, TNode< JSArray > fast_jsarray, Label * if_may_have_side_effects, TVariable< IntPtrT > & var_current_index) [protected]
Definition at line 192 of file builtins-collections-gen.cc.
                                                                            {
  TNode<FixedArrayBase> elements = LoadElements(fast_jsarray);
  TNode<Int32T> elements_kind = LoadElementsKind(fast_jsarray);
  TNode<JSFunction> add_func = GetInitialAddFunction(variant, native_context);
  CSA_DCHECK(this,
             TaggedEqual(GetAddFunction(variant, native_context, collection),
                         add_func));
  CSA_DCHECK(this, IsFastJSArrayWithNoCustomIteration(context, fast_jsarray));
  TNode<IntPtrT> length = PositiveSmiUntag(LoadFastJSArrayLength(fast_jsarray));
  CSA_DCHECK(
      this, HasInitialCollectionPrototype(variant, native_context, collection));
#if DEBUG
  TNode<Map> original_collection_map = LoadMap(CAST(collection));
  TNode<Map> original_fast_js_array_map = LoadMap(fast_jsarray);
#endif
  Label exit(this), if_doubles(this), if_smiorobjects(this);
  GotoIf(IntPtrEqual(length, IntPtrConstant(0)), &exit);
  Branch(IsFastSmiOrTaggedElementsKind(elements_kind), &if_smiorobjects,
         &if_doubles);
  BIND(&if_smiorobjects);
  {
    auto set_entry = [&](TNode<IntPtrT> index) {
      TNode<JSAny> element =
          CAST(LoadAndNormalizeFixedArrayElement(CAST(elements), index));
      AddConstructorEntry(variant, context, collection, add_func, element,
                          if_may_have_side_effects);
    };
    // Instead of using the slower iteration protocol to iterate over the
    // elements, a fast loop is used. This assumes that adding an element
    // to the collection does not call user code that could mutate the elements
    // or collection.
    BuildFastLoop<IntPtrT>(var_current_index, IntPtrConstant(0), length,
                           set_entry, 1, LoopUnrollingMode::kNo,
                           IndexAdvanceMode::kPost);
    Goto(&exit);
  }
  BIND(&if_doubles);
  {
    // A Map constructor requires entries to be arrays (ex. [key, value]),
    // so a FixedDoubleArray can never succeed.
    if (variant == kMap || variant == kWeakMap) {
      CSA_DCHECK(this, IntPtrGreaterThan(length, IntPtrConstant(0)));
      TNode<Object> element =
          LoadAndNormalizeFixedDoubleArrayElement(elements, IntPtrConstant(0));
      ThrowTypeError(context, MessageTemplate::kIteratorValueNotAnObject,
                     element);
    } else {
      DCHECK(variant == kSet || variant == kWeakSet);
      auto set_entry = [&](TNode<IntPtrT> index) {
        TNode<JSAny> entry = CAST(LoadAndNormalizeFixedDoubleArrayElement(
            elements, UncheckedCast<IntPtrT>(index)));
        AddConstructorEntry(variant, context, collection, add_func, entry);
      };
      BuildFastLoop<IntPtrT>(var_current_index, IntPtrConstant(0), length,
                             set_entry, 1, LoopUnrollingMode::kNo,
                             IndexAdvanceMode::kPost);
      Goto(&exit);
    }
  }
  BIND(&exit);
#if DEBUG
  CSA_DCHECK(this,
             TaggedEqual(original_collection_map, LoadMap(CAST(collection))));
  CSA_DCHECK(this,
             TaggedEqual(original_fast_js_array_map, LoadMap(fast_jsarray)));
#endif
}
References AddConstructorEntry(), v8::internal::compiler::CodeAssembler::Branch(), CAST, v8::internal::DCHECK(), GetAddFunction(), GetInitialAddFunction(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), HasInitialCollectionPrototype(), v8::internal::index, v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::compiler::CodeAssembler::IntPtrEqual(), v8::internal::CodeStubAssembler::IsFastSmiOrTaggedElementsKind(), kMap, v8::internal::CodeStubAssembler::kNo, v8::internal::CodeStubAssembler::kPost, kSet, kWeakMap, kWeakSet, v8::internal::length, LoadAndNormalizeFixedArrayElement(), LoadAndNormalizeFixedDoubleArrayElement(), v8::internal::CodeStubAssembler::LoadElements(), v8::internal::CodeStubAssembler::LoadElementsKind(), v8::internal::CodeStubAssembler::LoadFastJSArrayLength(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::native_context, v8::internal::CodeStubAssembler::PositiveSmiUntag(), v8::internal::CodeStubAssembler::TaggedEqual(), and v8::internal::CodeStubAssembler::ThrowTypeError().
Referenced by AddConstructorEntries().
AddConstructorEntriesFromIterable()
void v8::internal::BaseCollectionsAssembler::AddConstructorEntriesFromIterable (Variant variant, TNode< Context > context, TNode< Context > native_context, TNode< JSAny > collection, TNode< JSAny > iterable, Label * if_exception, TVariable< JSReceiver > * var_iterator, TVariable< Object > * var_exception) [protected]
Definition at line 265 of file builtins-collections-gen.cc.
                                      {
  Label exit(this), loop(this);
  CSA_DCHECK(this, Word32BinaryNot(IsNullOrUndefined(iterable)));
  TNode<Object> add_func = GetAddFunction(variant, context, collection);
  IteratorBuiltinsAssembler iterator_assembler(this->state());
  TorqueStructIteratorRecord iterator =
      iterator_assembler.GetIterator(context, iterable);
  *var_iterator_object = iterator.object;
  CSA_DCHECK(this, Word32BinaryNot(IsUndefined(iterator.object)));
  TNode<Map> fast_iterator_result_map = CAST(LoadContextElementNoCell(
      native_context, Context::ITERATOR_RESULT_MAP_INDEX));
  Goto(&loop);
  BIND(&loop);
  {
    TNode<JSReceiver> next = iterator_assembler.IteratorStep(
        context, iterator, &exit, fast_iterator_result_map);
    TNode<JSAny> next_value = iterator_assembler.IteratorValue(
        context, next, fast_iterator_result_map);
    AddConstructorEntry(variant, context, collection, add_func, next_value,
                        nullptr, if_exception, var_exception);
    Goto(&loop);
  }
  BIND(&exit);
}
References AddConstructorEntry(), CAST, GetAddFunction(), v8::internal::IteratorBuiltinsAssembler::GetIterator(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::CodeStubAssembler::IsNullOrUndefined(), v8::internal::IteratorBuiltinsAssembler::IteratorStep(), v8::internal::IteratorBuiltinsAssembler::IteratorValue(), v8::internal::native_context, and v8::internal::compiler::CodeAssembler::state().
Referenced by AddConstructorEntries().
AddConstructorEntry()
void v8::internal::BaseCollectionsAssembler::AddConstructorEntry (Variant variant, TNode< Context > context, TNode< JSAny > collection, TNode< Object > add_function, TNode< JSAny > key_value, Label * if_may_have_side_effects = nullptr, Label * if_exception = nullptr, TVariable< Object > * var_exception = nullptr) [protected]
Definition at line 27 of file builtins-collections-gen.cc.
                                      {
  compiler::ScopedExceptionHandler handler(this, if_exception, var_exception);
  CSA_DCHECK(this, Word32BinaryNot(IsHashTableHole(key_value)));
  if (variant == kMap || variant == kWeakMap) {
    TorqueStructKeyValuePair pair =
        if_may_have_side_effects != nullptr
            ? LoadKeyValuePairNoSideEffects(context, key_value,
                                            if_may_have_side_effects)
            : LoadKeyValuePair(context, key_value);
    TNode<Object> key_n = pair.key;
    TNode<Object> value_n = pair.value;
    Call(context, add_function, collection, key_n, value_n);
  } else {
    DCHECK(variant == kSet || variant == kWeakSet);
    Call(context, add_function, collection, key_value);
  }
}
References v8::internal::CodeStubAssembler::Call(), v8::internal::DCHECK(), kMap, kSet, kWeakMap, and kWeakSet.
Referenced by AddConstructorEntriesFromFastJSArray(), and AddConstructorEntriesFromIterable().
AllocateJSCollection()
TNode< JSObject > v8::internal::BaseCollectionsAssembler::AllocateJSCollection (TNode< Context > context, TNode< JSFunction > constructor, TNode< JSReceiver > new_target) [protected]
Definition at line 344 of file builtins-collections-gen.cc.
                                  {
  TNode<BoolT> is_target_unmodified = TaggedEqual(constructor, new_target);
  return Select<JSObject>(
      is_target_unmodified,
      [=, this] { return AllocateJSCollectionFast(constructor); },
      [=, this] {
        return AllocateJSCollectionSlow(context, constructor, new_target);
      });
}
References AllocateJSCollectionFast(), AllocateJSCollectionSlow(), and v8::internal::CodeStubAssembler::TaggedEqual().
Referenced by GenerateConstructor().
AllocateJSCollectionFast()
TNode< JSObject > v8::internal::BaseCollectionsAssembler::AllocateJSCollectionFast (TNode< JSFunction > constructor) [protected]
Definition at line 357 of file builtins-collections-gen.cc.
                                   {
  CSA_DCHECK(this, IsConstructorMap(LoadMap(constructor)));
  TNode<Map> initial_map =
      CAST(LoadJSFunctionPrototypeOrInitialMap(constructor));
  return AllocateJSObjectFromMap(initial_map);
}
References v8::internal::CodeStubAssembler::AllocateJSObjectFromMap(), CAST, v8::internal::compiler::initial_map, v8::internal::CodeStubAssembler::IsConstructorMap(), and v8::internal::CodeStubAssembler::LoadMap().
Referenced by AllocateJSCollection().
AllocateJSCollectionSlow()
TNode< JSObject > v8::internal::BaseCollectionsAssembler::AllocateJSCollectionSlow (TNode< Context > context, TNode< JSFunction > constructor, TNode< JSReceiver > new_target) [protected]
Definition at line 365 of file builtins-collections-gen.cc.
                                  {
  ConstructorBuiltinsAssembler constructor_assembler(this->state());
  return constructor_assembler.FastNewObject(context, constructor, new_target);
}
References v8::internal::ConstructorBuiltinsAssembler::FastNewObject(), and v8::internal::compiler::CodeAssembler::state().
Referenced by AllocateJSCollection().
AllocateTable()
virtual TNode<HeapObject> v8::internal::BaseCollectionsAssembler::AllocateTable (Variant variant, TNode< IntPtrT > at_least_space_for) [protected], [pure virtual]
Implemented in v8::internal::WeakCollectionsBuiltinsAssembler, and v8::internal::CollectionsBuiltinsAssembler.
Referenced by AddConstructorEntries(), and GenerateConstructor().
GenerateConstructor()
void v8::internal::BaseCollectionsAssembler::GenerateConstructor (Variant variant, Handle< String > constructor_function_name, TNode< Object > new_target, TNode< IntPtrT > argc, TNode< Context > context) [protected]
Definition at line 372 of file builtins-collections-gen.cc.
                                                                           {
  const int kIterableArg = 0;
  CodeStubArguments args(this, argc);
  TNode<JSAny> iterable = args.GetOptionalArgumentValue(kIterableArg);
  Label if_undefined(this, Label::kDeferred);
  GotoIf(IsUndefined(new_target), &if_undefined);
  TNode<NativeContext> native_context = LoadNativeContext(context);
  TNode<JSObject> collection = AllocateJSCollection(
      context, GetConstructor(variant, native_context), CAST(new_target));
  Label add_constructor_entries(this);
  // The empty case.
  //
  // This is handled specially to simplify AddConstructorEntries, which is
  // complex and contains multiple fast paths.
  GotoIfNot(IsNullOrUndefined(iterable), &add_constructor_entries);
  TNode<HeapObject> table = AllocateTable(variant, IntPtrConstant(0));
  StoreObjectField(collection, GetTableOffset(variant), table);
  Return(collection);
  BIND(&add_constructor_entries);
  AddConstructorEntries(variant, context, native_context, collection, iterable);
  Return(collection);
  BIND(&if_undefined);
  ThrowTypeError(context, MessageTemplate::kConstructorNotFunction,
                 HeapConstantNoHole(constructor_function_name));
}
References AddConstructorEntries(), AllocateJSCollection(), AllocateTable(), v8::base::args, CAST, GetConstructor(), GetTableOffset(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::compiler::CodeAssembler::HeapConstantNoHole(), v8::internal::compiler::CodeAssembler::IntPtrConstant(), v8::internal::CodeStubAssembler::IsNullOrUndefined(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::native_context, v8::internal::compiler::CodeAssembler::Return(), v8::internal::CodeStubAssembler::StoreObjectField(), and v8::internal::CodeStubAssembler::ThrowTypeError().
GetAddFunction()
TNode< Object > v8::internal::BaseCollectionsAssembler::GetAddFunction (Variant variant, TNode< Context > context, TNode< JSAny > collection) [protected]
Definition at line 406 of file builtins-collections-gen.cc.
                                                                      {
  Handle<String> add_func_name = (variant == kMap || variant == kWeakMap)
                                     ? isolate()->factory()->set_string()
                                     : isolate()->factory()->add_string();
  TNode<Object> add_func = GetProperty(context, collection, add_func_name);
  Label exit(this), if_notcallable(this, Label::kDeferred);
  GotoIf(TaggedIsSmi(add_func), &if_notcallable);
  GotoIfNot(IsCallable(CAST(add_func)), &if_notcallable);
  Goto(&exit);
  BIND(&if_notcallable);
  ThrowTypeError(context, MessageTemplate::kPropertyNotFunction, add_func,
                 HeapConstantNoHole(add_func_name), collection);
  BIND(&exit);
  return add_func;
}
References CAST, v8::internal::Isolate::factory(), v8::internal::CodeStubAssembler::GetProperty(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::compiler::CodeAssembler::HeapConstantNoHole(), v8::internal::CodeStubAssembler::IsCallable(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, kMap, kWeakMap, v8::internal::CodeStubAssembler::TaggedIsSmi(), and v8::internal::CodeStubAssembler::ThrowTypeError().
Referenced by AddConstructorEntriesFromFastJSArray(), and AddConstructorEntriesFromIterable().
GetAddFunctionNameIndex()
RootIndex v8::internal::BaseCollectionsAssembler::GetAddFunctionNameIndex (Variant variant) [protected]
Definition at line 297 of file builtins-collections-gen.cc.
                                                                           {
  switch (variant) {
    case kMap:
    case kWeakMap:
      return RootIndex::kset_string;
    case kSet:
    case kWeakSet:
      return RootIndex::kadd_string;
  }
  UNREACHABLE();
}
References kMap, kSet, kWeakMap, kWeakSet, and v8::internal::UNREACHABLE().
Referenced by GotoIfInitialAddFunctionModified().
GetConstructor()
TNode< JSFunction > v8::internal::BaseCollectionsAssembler::GetConstructor (Variant variant, TNode< Context > native_context) [protected]
Definition at line 426 of file builtins-collections-gen.cc.
                                                    {
  int index;
  switch (variant) {
    case kMap:
      index = Context::JS_MAP_FUN_INDEX;
      break;
    case kSet:
      index = Context::JS_SET_FUN_INDEX;
      break;
    case kWeakMap:
      index = Context::JS_WEAK_MAP_FUN_INDEX;
      break;
    case kWeakSet:
      index = Context::JS_WEAK_SET_FUN_INDEX;
      break;
  }
  return CAST(LoadContextElementNoCell(native_context, index));
}
References CAST, v8::internal::index, kMap, kSet, kWeakMap, kWeakSet, and v8::internal::native_context.
Referenced by GenerateConstructor().
GetEntriesIfFastCollectionOrIterable()
virtual void v8::internal::BaseCollectionsAssembler::GetEntriesIfFastCollectionOrIterable (Variant variant, TNode< Object > initial_entries, TNode< Context > context, TVariable< HeapObject > * var_entries_table, TVariable< IntPtrT > * var_number_of_elements, Label * if_not_fast_collection) [protected], [pure virtual]
Implemented in v8::internal::WeakCollectionsBuiltinsAssembler, and v8::internal::CollectionsBuiltinsAssembler.
Referenced by AddConstructorEntries().
GetInitialAddFunction()
TNode< JSFunction > v8::internal::BaseCollectionsAssembler::GetInitialAddFunction (Variant variant, TNode< Context > native_context) [protected]
Definition at line 446 of file builtins-collections-gen.cc.
                                                    {
  int index;
  switch (variant) {
    case kMap:
      index = Context::MAP_SET_INDEX;
      break;
    case kSet:
      index = Context::SET_ADD_INDEX;
      break;
    case kWeakMap:
      index = Context::WEAKMAP_SET_INDEX;
      break;
    case kWeakSet:
      index = Context::WEAKSET_ADD_INDEX;
      break;
  }
  return CAST(LoadContextElementNoCell(native_context, index));
}
References CAST, v8::internal::index, kMap, kSet, kWeakMap, kWeakSet, and v8::internal::native_context.
Referenced by AddConstructorEntriesFromFastJSArray().
GetInitialCollectionPrototype()
TNode< Map > v8::internal::BaseCollectionsAssembler::GetInitialCollectionPrototype (Variant variant, TNode< Context > native_context) [protected]
Definition at line 503 of file builtins-collections-gen.cc.
                                                    {
  int initial_prototype_index;
  switch (variant) {
    case kMap:
      initial_prototype_index = Context::INITIAL_MAP_PROTOTYPE_MAP_INDEX;
      break;
    case kSet:
      initial_prototype_index = Context::INITIAL_SET_PROTOTYPE_MAP_INDEX;
      break;
    case kWeakMap:
      initial_prototype_index = Context::INITIAL_WEAKMAP_PROTOTYPE_MAP_INDEX;
      break;
    case kWeakSet:
      initial_prototype_index = Context::INITIAL_WEAKSET_PROTOTYPE_MAP_INDEX;
      break;
  }
  return CAST(
      LoadContextElementNoCell(native_context, initial_prototype_index));
}
References CAST, kMap, kSet, kWeakMap, kWeakSet, and v8::internal::native_context.
Referenced by GotoIfInitialAddFunctionModified(), and HasInitialCollectionPrototype().
GetTableOffset()
int v8::internal::BaseCollectionsAssembler::GetTableOffset (Variant variant) [protected]
Definition at line 466 of file builtins-collections-gen.cc.
                                                            {
  switch (variant) {
    case kMap:
      return JSMap::kTableOffset;
    case kSet:
      return JSSet::kTableOffset;
    case kWeakMap:
      return JSWeakMap::kTableOffset;
    case kWeakSet:
      return JSWeakSet::kTableOffset;
  }
  UNREACHABLE();
}
References kMap, kSet, kWeakMap, kWeakSet, and v8::internal::UNREACHABLE().
Referenced by AddConstructorEntries(), v8::internal::CollectionsBuiltinsAssembler::AddConstructorEntriesFromSet(), GenerateConstructor(), and v8::internal::CollectionsBuiltinsAssembler::SetOrSetIteratorToSet().
GotoIfCannotBeHeldWeakly()
void v8::internal::BaseCollectionsAssembler::GotoIfCannotBeHeldWeakly (const TNode< Object > obj, Label * if_cannot_be_held_weakly)
Definition at line 481 of file builtins-collections-gen.cc.
                                                              {
  Label check_symbol_key(this);
  Label end(this);
  GotoIf(TaggedIsSmi(obj), if_cannot_be_held_weakly);
  TNode<Uint16T> instance_type = LoadMapInstanceType(LoadMap(CAST(obj)));
  GotoIfNot(IsJSReceiverInstanceType(instance_type), &check_symbol_key);
  // TODO(v8:12547) Shared structs and arrays should only be able to point
  // to shared values in weak collections. For now, disallow them as weak
  // collection keys.
  GotoIf(IsAlwaysSharedSpaceJSObjectInstanceType(instance_type),
         if_cannot_be_held_weakly);
  Goto(&end);
  Bind(&check_symbol_key);
  GotoIfNot(IsSymbolInstanceType(instance_type), if_cannot_be_held_weakly);
  TNode<Uint32T> flags = LoadSymbolFlags(CAST(obj));
  GotoIf(Word32And(flags, Symbol::IsInPublicSymbolTableBit::kMask),
         if_cannot_be_held_weakly);
  Goto(&end);
  Bind(&end);
}
References v8::internal::CodeStubAssembler::Bind(), CAST, v8::internal::compiler::end(), v8::internal::flags, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::CodeStubAssembler::IsAlwaysSharedSpaceJSObjectInstanceType(), v8::internal::CodeStubAssembler::IsJSReceiverInstanceType(), v8::internal::CodeStubAssembler::IsSymbolInstanceType(), v8::base::BitField< T, shift, size, U >::kMask, v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapInstanceType(), v8::internal::CodeStubAssembler::TaggedIsSmi(), and v8::internal::compiler::CodeAssembler::Word32And().
GotoIfInitialAddFunctionModified()
void v8::internal::BaseCollectionsAssembler::GotoIfInitialAddFunctionModified (Variant variant, TNode< NativeContext > native_context, TNode< HeapObject > collection, Label * if_modified) [protected]
Definition at line 309 of file builtins-collections-gen.cc.
                                                      {
  static_assert(JSCollection::kAddFunctionDescriptorIndex ==
                JSWeakCollection::kAddFunctionDescriptorIndex);
  // TODO(jgruber): Investigate if this should also fall back to full prototype
  // verification.
  static constexpr PrototypeCheckAssembler::Flags flags{
      PrototypeCheckAssembler::kCheckPrototypePropertyConstness};
  static constexpr int kNoContextIndex = -1;
  static_assert(
      (flags & PrototypeCheckAssembler::kCheckPrototypePropertyIdentity) == 0);
  using DescriptorIndexNameValue =
      PrototypeCheckAssembler::DescriptorIndexNameValue;
  DescriptorIndexNameValue property_to_check{
      JSCollection::kAddFunctionDescriptorIndex,
      GetAddFunctionNameIndex(variant), kNoContextIndex};
  PrototypeCheckAssembler prototype_check_assembler(
      state(), flags, native_context,
      GetInitialCollectionPrototype(variant, native_context),
      base::Vector<DescriptorIndexNameValue>(&property_to_check, 1));
  TNode<HeapObject> prototype = LoadMapPrototype(LoadMap(collection));
  Label if_unmodified(this);
  prototype_check_assembler.CheckAndBranch(prototype, &if_unmodified,
                                           if_modified);
  BIND(&if_unmodified);
}
References v8::internal::PrototypeCheckAssembler::CheckAndBranch(), v8::internal::flags, GetAddFunctionNameIndex(), GetInitialCollectionPrototype(), v8::internal::JSCollection::kAddFunctionDescriptorIndex, v8::internal::JSWeakCollection::kAddFunctionDescriptorIndex, v8::internal::PrototypeCheckAssembler::kCheckPrototypePropertyConstness, v8::internal::PrototypeCheckAssembler::kCheckPrototypePropertyIdentity, v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapPrototype(), v8::internal::native_context, v8::internal::prototype, and v8::internal::compiler::CodeAssembler::state().
Referenced by AddConstructorEntries().
HasInitialCollectionPrototype()
TNode< BoolT > v8::internal::BaseCollectionsAssembler::HasInitialCollectionPrototype (Variant variant, TNode< Context > native_context, TNode< JSAny > collection) [protected]
Definition at line 524 of file builtins-collections-gen.cc.
                                                                             {
  TNode<Map> collection_proto_map =
      LoadMap(LoadMapPrototype(LoadMap(CAST(collection))));
  return TaggedEqual(collection_proto_map,
                     GetInitialCollectionPrototype(variant, native_context));
}
References CAST, GetInitialCollectionPrototype(), v8::internal::CodeStubAssembler::LoadMap(), v8::internal::CodeStubAssembler::LoadMapPrototype(), v8::internal::native_context, and v8::internal::CodeStubAssembler::TaggedEqual().
Referenced by AddConstructorEntriesFromFastJSArray().
LoadAndNormalizeFixedArrayElement()
TNode< Object > v8::internal::BaseCollectionsAssembler::LoadAndNormalizeFixedArrayElement (TNode< FixedArray > elements, TNode< IntPtrT > index) [protected]
Definition at line 533 of file builtins-collections-gen.cc.
                                                      {
  TNode<Object> element = UnsafeLoadFixedArrayElement(elements, index);
  return Select<Object>(
      IsTheHole(element), [=, this] { return UndefinedConstant(); },
      [=] { return element; });
}
References v8::internal::index, v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::CodeStubAssembler::UnsafeLoadFixedArrayElement().
Referenced by AddConstructorEntriesFromFastJSArray().
LoadAndNormalizeFixedDoubleArrayElement()
TNode< Object > v8::internal::BaseCollectionsAssembler::LoadAndNormalizeFixedDoubleArrayElement (TNode< HeapObject > elements, TNode< IntPtrT > index) [protected]
Definition at line 541 of file builtins-collections-gen.cc.
                                                      {
  TVARIABLE(Object, entry);
  Label if_hole_or_undefined(this, Label::kDeferred), next(this);
  TNode<Float64T> element = LoadFixedDoubleArrayElement(
      CAST(elements), index, &if_hole_or_undefined, &if_hole_or_undefined);
  { // not hole
#ifdef V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    CSA_DCHECK(this, Word32Equal(Int32Constant(0), IsDoubleUndefined(element)));
#endif // V8_ENABLE_EXPERIMENTAL_UNDEFINED_DOUBLE
    entry = AllocateHeapNumberWithValue(element);
    Goto(&next);
  }
  BIND(&if_hole_or_undefined);
  {
    entry = UndefinedConstant();
    Goto(&next);
  }
  BIND(&next);
  return entry.value();
}
References v8::internal::CodeStubAssembler::AllocateHeapNumberWithValue(), CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::index, v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadFixedDoubleArrayElement(), v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant(), and v8::internal::compiler::CodeAssembler::Word32Equal().
Referenced by AddConstructorEntriesFromFastJSArray().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-collections-gen.h
/mnt/V8SourceCode/src/builtins/builtins-collections-gen.cc