v8::internal::EmbedderDataSlot Class Reference
#include <embedder-data-slot.h>
Public Types
using RawData = Address
Public Member Functions
EmbedderDataSlot ()
EmbedderDataSlot (Tagged< EmbedderDataArray > array, int entry_index)
EmbedderDataSlot (Tagged< JSObject > object, int embedder_field_index)
void Initialize (Tagged< Object > initial_value)
Tagged< Object > load_tagged () const
void store_smi (Tagged< Smi > value)
bool ToAlignedPointer (IsolateForSandbox isolate, void **out_result) const
V8_WARN_UNUSED_RESULT bool store_aligned_pointer (IsolateForSandbox isolate, Tagged< HeapObject > host, void *ptr)
bool MustClearDuringSerialization (const DisallowGarbageCollection &no_gc)
RawData load_raw (IsolateForSandbox isolate, const DisallowGarbageCollection &no_gc) const
void store_raw (IsolateForSandbox isolate, RawData data, const DisallowGarbageCollection &no_gc)
Static Public Member Functions
static void store_tagged (Tagged< EmbedderDataArray > array, int entry_index, Tagged< Object > value)
static void store_tagged (Tagged< JSObject > object, int embedder_field_index, Tagged< Object > value)
Static Public Attributes
static constexpr int kTaggedPayloadOffset = 0
static constexpr int kExternalPointerOffset = 0
static constexpr int kRequiredPtrAlignment = kSmiTagSize
Private Member Functions
void gc_safe_store (IsolateForSandbox isolate, Address value)
Additional Inherited Members
Detailed Description
Definition at line 33 of file embedder-data-slot.h.
Member Typedef Documentation
RawData
using v8::internal::EmbedderDataSlot::RawData = Address
Definition at line 98 of file embedder-data-slot.h.
Constructor & Destructor Documentation
EmbedderDataSlot() [1/3]
v8::internal::EmbedderDataSlot::EmbedderDataSlot () [inline]
Definition at line 93 of file embedder-data-slot.h.
: SlotBase(kNullAddress) {}
EmbedderDataSlot() [2/3]
v8::internal::EmbedderDataSlot::EmbedderDataSlot (Tagged< EmbedderDataArray > array, int entry_index) [inline]
Definition at line 26 of file embedder-data-slot-inl.h.
    : SlotBase(FIELD_ADDR(array,
                          EmbedderDataArray::OffsetOfElementAt(entry_index))) {}
EmbedderDataSlot() [3/3]
v8::internal::EmbedderDataSlot::EmbedderDataSlot (Tagged< JSObject > object, int embedder_field_index) [inline]
Definition at line 31 of file embedder-data-slot-inl.h.
    : SlotBase(FIELD_ADDR(
          object, object->GetEmbedderFieldOffset(embedder_field_index))) {}
Member Function Documentation
gc_safe_store()
void v8::internal::EmbedderDataSlot::gc_safe_store (IsolateForSandbox isolate, Address value) [inline], [private]
Definition at line 175 of file embedder-data-slot-inl.h.
                                                                             {
#ifdef V8_COMPRESS_POINTERS
  static_assert(kSmiShiftSize == 0);
  static_assert(SmiValuesAre31Bits());
  static_assert(kTaggedSize == kInt32Size);
  // We have to do two 32-bit stores here because
  // 1) tagged part modifications must be atomic to be properly synchronized
  // with the concurrent marker.
  // 2) atomicity of full pointer store is not guaranteed for embedder slots
  // since the address of the slot may not be kSystemPointerSize aligned
  // (only kTaggedSize alignment is guaranteed).
  // TODO(ishell, v8:8875): revisit this once the allocation alignment
  // inconsistency is fixed.
  Address lo = static_cast<intptr_t>(static_cast<int32_t>(value));
  ObjectSlot(address() + kTaggedPayloadOffset).Relaxed_Store(Tagged<Smi>(lo));
  Tagged_t hi = static_cast<Tagged_t>(value >> 32);
  // The raw part of the payload does not contain a valid tagged value, so we
  // need to use a raw store operation for it here.
  AsAtomicTagged::Relaxed_Store(
      reinterpret_cast<AtomicTagged_t*>(address() + kRawPayloadOffset), hi);
#else
  ObjectSlot(address() + kTaggedPayloadOffset)
      .Relaxed_Store(Tagged<Smi>(value));
#endif
}
References v8::internal::SlotBase< EmbedderDataSlot, Address, kTaggedSize >::address(), v8::internal::hi, v8::internal::kInt32Size, v8::internal::kSmiShiftSize, kTaggedPayloadOffset, v8::internal::kTaggedSize, v8::internal::lo, v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store(), v8::internal::FullObjectSlot::Relaxed_Store(), v8::internal::SmiValuesAre31Bits(), and v8::internal::value.
Referenced by store_aligned_pointer(), and store_raw().
Initialize()
void v8::internal::EmbedderDataSlot::Initialize (Tagged< Object > initial_value) [inline]
Definition at line 36 of file embedder-data-slot-inl.h.
                                                              {
  // TODO(v8) initialize the slot with Smi::zero() instead. This'll also
  // guarantee that we don't need a write barrier.
  DCHECK(IsSmi(initial_value) ||
         ReadOnlyHeap::Contains(Cast<HeapObject>(initial_value)));
  ObjectSlot(address() + kTaggedPayloadOffset).Relaxed_Store(initial_value);
#ifdef V8_COMPRESS_POINTERS
  ObjectSlot(address() + kRawPayloadOffset).Relaxed_Store(Smi::zero());
#endif
}
References v8::internal::SlotBase< EmbedderDataSlot, Address, kTaggedSize >::address(), v8::internal::ReadOnlyHeap::Contains(), v8::internal::DCHECK(), v8::internal::IsSmi(), kTaggedPayloadOffset, v8::internal::FullObjectSlot::Relaxed_Store(), and v8::internal::Smi::zero().
Referenced by v8::internal::anonymous_namespace{factory.cc}::InitEmbedderFields(), v8::internal::JSObject::InitializeBody(), and v8::internal::Factory::NewEmbedderDataArray().
load_raw()
EmbedderDataSlot::RawData v8::internal::EmbedderDataSlot::load_raw (IsolateForSandbox isolate, const DisallowGarbageCollection & no_gc) const [inline]
Definition at line 152 of file embedder-data-slot-inl.h.
                                                                             {
  // We don't care about atomicity of access here because embedder slots
  // are accessed this way only by serializer from the main thread when
  // GC is not active (concurrent marker may still look at the tagged part
  // of the embedder slot but read-only access is ok).
#ifdef V8_COMPRESS_POINTERS
  // TODO(ishell, v8:8875): When pointer compression is enabled 8-byte size
  // fields (external pointers, doubles and BigInt data) are only kTaggedSize
  // aligned so we have to use unaligned pointer friendly way of accessing them
  // in order to avoid undefined behavior in C++ code.
  return base::ReadUnalignedValue<EmbedderDataSlot::RawData>(address());
#else
  return *location();
#endif
}
References v8::internal::SlotBase< EmbedderDataSlot, Address, kTaggedSize >::address(), and v8::internal::SlotBase< EmbedderDataSlot, Address, kTaggedSize >::location().
Referenced by v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields().
load_tagged()
Tagged< Object > v8::internal::EmbedderDataSlot::load_tagged () const [inline]
Definition at line 47 of file embedder-data-slot-inl.h.
                                                   {
  return ObjectSlot(address() + kTaggedPayloadOffset).Relaxed_Load();
}
References v8::internal::SlotBase< EmbedderDataSlot, Address, kTaggedSize >::address(), kTaggedPayloadOffset, and v8::internal::FullObjectSlot::Relaxed_Load().
Referenced by v8::internal::EmbedderDataArray::EnsureCapacity(), v8::internal::JSObject::GetEmbedderField(), and v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields().
MustClearDuringSerialization()
bool v8::internal::EmbedderDataSlot::MustClearDuringSerialization (const DisallowGarbageCollection & no_gc) [inline]
Definition at line 202 of file embedder-data-slot-inl.h.
                                            {
  // Serialization must avoid writing external pointer handles. If we were to
  // accidentally write an external pointer handle, that ends up deserializing
  // as a dangling pointer. For consistency it would be nice to avoid writing
  // external pointers also in the wide-pointer case, but as we can't
  // distinguish between Smi values and pointers we just leave them be.
#ifdef V8_ENABLE_SANDBOX
  auto* location = reinterpret_cast<ExternalPointerHandle*>(
      address() + kExternalPointerOffset);
  return base::AsAtomic32::Relaxed_Load(location) != kNullExternalPointerHandle;
#else // !V8_ENABLE_SANDBOX
  return false;
#endif // !V8_ENABLE_SANDBOX
}
References v8::internal::SlotBase< EmbedderDataSlot, Address, kTaggedSize >::address(), kExternalPointerOffset, v8::internal::kNullExternalPointerHandle, v8::internal::SlotBase< EmbedderDataSlot, Address, kTaggedSize >::location(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
Referenced by v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields().
store_aligned_pointer()
bool v8::internal::EmbedderDataSlot::store_aligned_pointer (IsolateForSandbox isolate, Tagged< HeapObject > host, void * ptr) [inline]
Definition at line 126 of file embedder-data-slot-inl.h.
                                                        {
  Address value = reinterpret_cast<Address>(ptr);
  if (!HAS_SMI_TAG(value)) return false;
#ifdef V8_ENABLE_SANDBOX
  // When the sandbox is enabled, the external pointer handles in
  // EmbedderDataSlots are lazily initialized: initially they contain the null
  // external pointer handle (see EmbedderDataSlot::Initialize), and only once
  // an external pointer is stored in them are they properly initialized.
  // TODO(saelo): here we currently have to use the accessor on the host object
  // as we may need a write barrier. This is a bit awkward. Maybe we should
  // introduce helper methods on the ExternalPointerSlot class that allow us to
  // determine whether the slot needs to be initialized, in which case a write
  // barrier can be performed here.
  size_t offset = address() - host.address() + kExternalPointerOffset;
  host->WriteLazilyInitializedExternalPointerField<kEmbedderDataSlotPayloadTag>(
      offset, isolate, value);
  ObjectSlot(address() + kTaggedPayloadOffset).Relaxed_Store(Smi::zero());
  return true;
#else
  gc_safe_store(isolate, value);
  return true;
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::SlotBase< EmbedderDataSlot, Address, kTaggedSize >::address(), v8::internal::Tagged< HeapObject >::address(), gc_safe_store(), HAS_SMI_TAG, v8::internal::kEmbedderDataSlotPayloadTag, kExternalPointerOffset, kTaggedPayloadOffset, v8::internal::FullObjectSlot::Relaxed_Store(), v8::internal::value, and v8::internal::Smi::zero().
Referenced by v8::internal::EmbedderDataArray::EnsureCapacity(), and v8::Context::SetAlignedPointerInEmbedderData().
store_raw()
void v8::internal::EmbedderDataSlot::store_raw (IsolateForSandbox isolate, EmbedderDataSlot::RawData data, const DisallowGarbageCollection & no_gc) [inline]
Definition at line 169 of file embedder-data-slot-inl.h.
                                                                         {
  gc_safe_store(isolate, data);
}
References gc_safe_store().
Referenced by v8::internal::ContextSerializer::SerializeObjectWithEmbedderFields().
store_smi()
void v8::internal::EmbedderDataSlot::store_smi (Tagged< Smi > value) [inline]
Definition at line 51 of file embedder-data-slot-inl.h.
                                                  {
  ObjectSlot(address() + kTaggedPayloadOffset).Relaxed_Store(value);
#ifdef V8_COMPRESS_POINTERS
  // See gc_safe_store() for the reasons behind two stores.
  ObjectSlot(address() + kRawPayloadOffset).Relaxed_Store(Smi::zero());
#endif
}
References v8::internal::SlotBase< EmbedderDataSlot, Address, kTaggedSize >::address(), kTaggedPayloadOffset, v8::internal::FullObjectSlot::Relaxed_Store(), v8::internal::value, and v8::internal::Smi::zero().
Referenced by v8::internal::JSObject::SetEmbedderField().
store_tagged() [1/2]
void v8::internal::EmbedderDataSlot::store_tagged (Tagged< EmbedderDataArray > array, int entry_index, Tagged< Object > value) [inline], [static]
Definition at line 60 of file embedder-data-slot-inl.h.
                                                                           {
#ifdef V8_COMPRESS_POINTERS
  CHECK(IsSmi(value) ||
        V8HeapCompressionScheme::GetPtrComprCageBaseAddress(value.ptr()) ==
            V8HeapCompressionScheme::GetPtrComprCageBaseAddress(array.ptr()));
#endif
  int slot_offset = EmbedderDataArray::OffsetOfElementAt(entry_index);
  ObjectSlot(FIELD_ADDR(array, slot_offset + kTaggedPayloadOffset))
      .Relaxed_Store(value);
  WRITE_BARRIER(array, slot_offset + kTaggedPayloadOffset, value);
#ifdef V8_COMPRESS_POINTERS
  // See gc_safe_store() for the reasons behind two stores.
  ObjectSlot(FIELD_ADDR(array, slot_offset + kRawPayloadOffset))
      .Relaxed_Store(Smi::zero());
#endif
}
References CHECK, FIELD_ADDR, v8::internal::V8HeapCompressionSchemeImpl< Cage >::GetPtrComprCageBaseAddress(), v8::internal::IsSmi(), kTaggedPayloadOffset, v8::internal::EmbedderDataArray::OffsetOfElementAt(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), v8::internal::FullObjectSlot::Relaxed_Store(), v8::internal::value, WRITE_BARRIER, and v8::internal::Smi::zero().
Referenced by v8::Context::SetEmbedderData().
store_tagged() [2/2]
void v8::internal::EmbedderDataSlot::store_tagged (Tagged< JSObject > object, int embedder_field_index, Tagged< Object > value) [inline], [static]
Definition at line 79 of file embedder-data-slot-inl.h.
                                                          {
#ifdef V8_COMPRESS_POINTERS
  CHECK(IsSmi(value) ||
        V8HeapCompressionScheme::GetPtrComprCageBaseAddress(value.ptr()) ==
            V8HeapCompressionScheme::GetPtrComprCageBaseAddress(object.ptr()));
#endif
  int slot_offset = object->GetEmbedderFieldOffset(embedder_field_index);
  ObjectSlot(FIELD_ADDR(object, slot_offset + kTaggedPayloadOffset))
      .Relaxed_Store(value);
  WRITE_BARRIER(object, slot_offset + kTaggedPayloadOffset, value);
#ifdef V8_COMPRESS_POINTERS
  // See gc_safe_store() for the reasons behind two stores.
  ObjectSlot(FIELD_ADDR(object, slot_offset + kRawPayloadOffset))
      .Relaxed_Store(Smi::zero());
#endif
}
References CHECK, FIELD_ADDR, v8::internal::V8HeapCompressionSchemeImpl< Cage >::GetPtrComprCageBaseAddress(), v8::internal::IsSmi(), kTaggedPayloadOffset, v8::internal::FullObjectSlot::Relaxed_Store(), v8::internal::value, WRITE_BARRIER, and v8::internal::Smi::zero().
ToAlignedPointer()
bool v8::internal::EmbedderDataSlot::ToAlignedPointer (IsolateForSandbox isolate, void ** out_result) const [inline]
Definition at line 98 of file embedder-data-slot-inl.h.
                                                                  {
  // We don't care about atomicity of access here because embedder slots
  // are accessed this way only from the main thread via API during "mutator"
  // phase which is propely synched with GC (concurrent marker may still look
  // at the tagged part of the embedder slot but read-only access is ok).
#ifdef V8_ENABLE_SANDBOX
  // The raw part must always contain a valid external pointer table index.
  *out_pointer = reinterpret_cast<void*>(
      ReadExternalPointerField<kEmbedderDataSlotPayloadTag>(
          address() + kExternalPointerOffset, isolate));
  return true;
#else
  Address raw_value;
  if (COMPRESS_POINTERS_BOOL) {
    // TODO(ishell, v8:8875): When pointer compression is enabled 8-byte size
    // fields (external pointers, doubles and BigInt data) are only kTaggedSize
    // aligned so we have to use unaligned pointer friendly way of accessing
    // them in order to avoid undefined behavior in C++ code.
    raw_value = base::ReadUnalignedValue<Address>(address());
  } else {
    raw_value = *location();
  }
  *out_pointer = reinterpret_cast<void*>(raw_value);
  return HAS_SMI_TAG(raw_value);
#endif // V8_ENABLE_SANDBOX
}
References v8::internal::SlotBase< EmbedderDataSlot, Address, kTaggedSize >::address(), COMPRESS_POINTERS_BOOL, HAS_SMI_TAG, kExternalPointerOffset, and v8::internal::SlotBase< EmbedderDataSlot, Address, kTaggedSize >::location().
Referenced by v8::internal::EmbedderDataArray::EnsureCapacity().
Member Data Documentation
kExternalPointerOffset
constexpr int v8::internal::EmbedderDataSlot::kExternalPointerOffset = 0 [static], [constexpr]
Definition at line 88 of file embedder-data-slot.h.
Referenced by v8::internal::EmbedderDataArray::BodyDescriptor::IterateBody(), v8::internal::BodyDescriptorBase::IterateJSObjectBodyImpl(), MustClearDuringSerialization(), store_aligned_pointer(), and ToAlignedPointer().
kRequiredPtrAlignment
constexpr int v8::internal::EmbedderDataSlot::kRequiredPtrAlignment = kSmiTagSize [static], [constexpr]
Definition at line 91 of file embedder-data-slot.h.
kTaggedPayloadOffset
constexpr int v8::internal::EmbedderDataSlot::kTaggedPayloadOffset = 0 [static], [constexpr]
Definition at line 87 of file embedder-data-slot.h.
Referenced by gc_safe_store(), Initialize(), v8::internal::EmbedderDataArray::BodyDescriptor::IterateBody(), v8::internal::BodyDescriptorBase::IterateJSObjectBodyImpl(), load_tagged(), store_aligned_pointer(), store_smi(), and store_tagged().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/embedder-data-slot.h
/mnt/V8SourceCode/src/objects/embedder-data-slot-inl.h