v8::internal::compiler::turboshaft::GeneratorAnalyzer Class Reference
Public Member Functions
GeneratorAnalyzer (Zone *phase_zone, maglev::MaglevGraphLabeller *labeller)
void Analyze (maglev::Graph *graph)
bool JumpBypassesHeader (const maglev::BasicBlock *target)
const maglev::BasicBlock * GetInnermostBypassedHeader (const maglev::BasicBlock *target)
bool HeaderIsBypassed (const maglev::BasicBlock *header)
const maglev::BasicBlock * GetLoopHeader (const maglev::BasicBlock *node)
bool has_header_bypasses () const
Private Member Functions
void FindLoopBody (maglev::BlockConstReverseIterator it)
void FindLoopHeaderBypasses (maglev::Graph *graph)
void RecordHeadersForBypass (maglev::BasicBlock *initial_target, const maglev::BasicBlock *innermost_header)
Private Attributes
maglev::MaglevGraphLabeller * labeller_
ZoneAbslFlatHashMap< const maglev::BasicBlock *, const maglev::BasicBlock * > block_to_header_
std::unordered_map< const maglev::BasicBlock *, const maglev::BasicBlock * > block_to_innermost_bypassed_header_
std::unordered_set< const maglev::BasicBlock * > bypassed_headers_
ZoneVector< const maglev::BasicBlock * > visit_queue_
Detailed Description
Definition at line 123 of file turbolev-graph-builder.cc.
Constructor & Destructor Documentation
GeneratorAnalyzer()
v8::internal::compiler::turboshaft::GeneratorAnalyzer::GeneratorAnalyzer (Zone * phase_zone, maglev::MaglevGraphLabeller * labeller) [inline], [explicit]
Definition at line 260 of file turbolev-graph-builder.cc.
      : labeller_(labeller),
        block_to_header_(phase_zone),
        visit_queue_(phase_zone) {
    USE(labeller_);
  }
References labeller_, and USE.
Member Function Documentation
Analyze()
void v8::internal::compiler::turboshaft::GeneratorAnalyzer::Analyze (maglev::Graph * graph) [inline]
Definition at line 268 of file turbolev-graph-builder.cc.
                                   {
    for (auto it = graph->rbegin(); it != graph->rend(); ++it) {
      if ((*it)->is_loop()) {
        FindLoopBody(it);
      }
    }
    FindLoopHeaderBypasses(graph);
  }
References FindLoopBody(), FindLoopHeaderBypasses(), and graph().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::PreProcessGraph().
FindLoopBody()
void v8::internal::compiler::turboshaft::GeneratorAnalyzer::FindLoopBody (maglev::BlockConstReverseIterator it) [inline], [private]
Definition at line 308 of file turbolev-graph-builder.cc.
                                                        {
    const maglev::BasicBlock* header = *it;
    DCHECK(header->is_loop());
    --it; // Skipping the header, since we consider its loop header to be the
           // header of their outer loop (if any).
    const maglev::BasicBlock* backedge_block = header->backedge_predecessor();
    if (backedge_block == header) {
      // This is a 1-block loop. Since headers are part of the outer loop, we
      // have nothing to mark.
      return;
    }
    block_to_header_[backedge_block] = header;
    for (; *it != backedge_block; --it) {
      const maglev::BasicBlock* curr = *it;
      if (block_to_header_.contains(curr)) {
        // {curr} is part of an inner loop.
        continue;
      }
      block_to_header_[curr] = header;
    }
  }
References v8::internal::maglev::BasicBlock::backedge_predecessor(), block_to_header_, v8::internal::DCHECK(), and v8::internal::maglev::BasicBlock::is_loop().
Referenced by Analyze().
FindLoopHeaderBypasses()
void v8::internal::compiler::turboshaft::GeneratorAnalyzer::FindLoopHeaderBypasses (maglev::Graph * graph) [inline], [private]
Definition at line 334 of file turbolev-graph-builder.cc.
                                                  {
    // As mentioned earlier, Maglev graphs for resumable generator functions
    // always start with a main dispatch switch in the 3rd block:
    //
    //
    // + 1 -----------------+
    // | InitialValues... |
    // | Jump |
    // +--------------------+
    // |
    // |
    // v
    // + 2 --------------------+
    // | BranchIfRootConstant |
    // +-----------------------+
    // / \
    // / \
    // / \
    // / \
    // v v
    // + 3 ----------+ + 4 --------------+
    // | Load state | | Initial setup |
    // | Switch | | return |
    // +-------------+ +-----------------+
    // / | \
    // / | \
    // v v v
    // Resuming in various places
    //
    //
    //
    // In order to find loop header bypasses, we are looking for cases where
    // the destination of the dispatch switch (= the successors of block 3) are
    // inside a loop.
    constexpr int kGeneratorSwitchBLockIndex = 2;
    maglev::BasicBlock* generator_switch_block =
        graph->blocks()[kGeneratorSwitchBLockIndex];
    DCHECK(generator_switch_block->control_node()->Is<maglev::Switch>());
    for (maglev::BasicBlock* target : generator_switch_block->successors()) {
      const maglev::BasicBlock* innermost_header = GetLoopHeader(target);
      if (innermost_header) {
        // This case bypasses a loop header.
        RecordHeadersForBypass(target, innermost_header);
      }
    }
  }
References v8::internal::maglev::BasicBlock::control_node(), v8::internal::DCHECK(), GetLoopHeader(), graph(), v8::internal::maglev::NodeBase::Is(), RecordHeadersForBypass(), and v8::internal::maglev::BasicBlock::successors().
Referenced by Analyze().
GetInnermostBypassedHeader()
const maglev::BasicBlock* v8::internal::compiler::turboshaft::GeneratorAnalyzer::GetInnermostBypassedHeader (const maglev::BasicBlock * target) [inline]
Definition at line 282 of file turbolev-graph-builder.cc.
                                      {
    DCHECK(JumpBypassesHeader(target));
    return block_to_innermost_bypassed_header_[target];
  }
References block_to_innermost_bypassed_header_, v8::internal::DCHECK(), and JumpBypassesHeader().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
GetLoopHeader()
const maglev::BasicBlock* v8::internal::compiler::turboshaft::GeneratorAnalyzer::GetLoopHeader (const maglev::BasicBlock * node) [inline]
Definition at line 293 of file turbolev-graph-builder.cc.
                                                                      {
    if (block_to_header_.contains(node)) {
      return block_to_header_[node];
    }
    return nullptr;
  }
References block_to_header_.
Referenced by FindLoopHeaderBypasses(), v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process(), and RecordHeadersForBypass().
has_header_bypasses()
bool v8::internal::compiler::turboshaft::GeneratorAnalyzer::has_header_bypasses () const [inline]
Definition at line 300 of file turbolev-graph-builder.cc.
{ return !bypassed_headers_.empty(); }
References bypassed_headers_.
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::IsMaglevMainGeneratorSwitchBlock(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
HeaderIsBypassed()
bool v8::internal::compiler::turboshaft::GeneratorAnalyzer::HeaderIsBypassed (const maglev::BasicBlock * header) [inline]
Definition at line 288 of file turbolev-graph-builder.cc.
                                                        {
    DCHECK(header->is_loop());
    return bypassed_headers_.contains(header);
  }
References bypassed_headers_, v8::internal::DCHECK(), and v8::internal::maglev::BasicBlock::is_loop().
Referenced by v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::BuildJump(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
JumpBypassesHeader()
bool v8::internal::compiler::turboshaft::GeneratorAnalyzer::JumpBypassesHeader (const maglev::BasicBlock * target) [inline]
Definition at line 278 of file turbolev-graph-builder.cc.
                                                          {
    return block_to_innermost_bypassed_header_.contains(target);
  }
References block_to_innermost_bypassed_header_.
Referenced by GetInnermostBypassedHeader(), and v8::internal::compiler::turboshaft::GraphBuildingNodeProcessor::Process().
RecordHeadersForBypass()
void v8::internal::compiler::turboshaft::GeneratorAnalyzer::RecordHeadersForBypass (maglev::BasicBlock * initial_target, const maglev::BasicBlock * innermost_header) [inline], [private]
Definition at line 384 of file turbolev-graph-builder.cc.
                                                                        {
    block_to_innermost_bypassed_header_[initial_target] = innermost_header;
    bypassed_headers_.insert(innermost_header);
    for (const maglev::BasicBlock* outer_header =
             GetLoopHeader(innermost_header);
         outer_header; outer_header = GetLoopHeader(outer_header)) {
      bypassed_headers_.insert(outer_header);
    }
  }
References block_to_innermost_bypassed_header_, bypassed_headers_, and GetLoopHeader().
Referenced by FindLoopHeaderBypasses().
Member Data Documentation
block_to_header_
ZoneAbslFlatHashMap<const maglev::BasicBlock*, const maglev::BasicBlock*> v8::internal::compiler::turboshaft::GeneratorAnalyzer::block_to_header_ [private]
Definition at line 400 of file turbolev-graph-builder.cc.
Referenced by FindLoopBody(), and GetLoopHeader().
block_to_innermost_bypassed_header_
std::unordered_map<const maglev::BasicBlock*, const maglev::BasicBlock*> v8::internal::compiler::turboshaft::GeneratorAnalyzer::block_to_innermost_bypassed_header_ [private]
Definition at line 404 of file turbolev-graph-builder.cc.
Referenced by GetInnermostBypassedHeader(), JumpBypassesHeader(), and RecordHeadersForBypass().
bypassed_headers_
std::unordered_set<const maglev::BasicBlock*> v8::internal::compiler::turboshaft::GeneratorAnalyzer::bypassed_headers_ [private]
Definition at line 406 of file turbolev-graph-builder.cc.
Referenced by has_header_bypasses(), HeaderIsBypassed(), and RecordHeadersForBypass().
labeller_
maglev::MaglevGraphLabeller* v8::internal::compiler::turboshaft::GeneratorAnalyzer::labeller_ [private]
Definition at line 396 of file turbolev-graph-builder.cc.
Referenced by GeneratorAnalyzer().
visit_queue_
ZoneVector<const maglev::BasicBlock*> v8::internal::compiler::turboshaft::GeneratorAnalyzer::visit_queue_ [private]
Definition at line 411 of file turbolev-graph-builder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/turbolev-graph-builder.cc