v8::internal::BuiltinFrame Class Reference
#include <frames.h>
Public Member Functions
Type type () const final
Tagged< JSFunction > function () const override
int ComputeParametersCount () const override
Static Public Member Functions
static BuiltinFrame * cast (StackFrame *frame)
Protected Member Functions
BuiltinFrame (StackFrameIteratorBase *iterator)
Friends
class StackFrameIteratorBase
Additional Inherited Members
Detailed Description
Definition at line 1239 of file frames.h.
Constructor & Destructor Documentation
BuiltinFrame()
v8::internal::BuiltinFrame::BuiltinFrame (StackFrameIteratorBase * iterator) [inline], [explicit], [protected]
Definition at line 321 of file frames-inl.h.
    : TypedFrameWithJSLinkage(iterator) {}
Member Function Documentation
cast()
static BuiltinFrame* v8::internal::BuiltinFrame::cast (StackFrame * frame) [inline], [static]
Definition at line 1243 of file frames.h.
                                               {
    DCHECK(frame->is_builtin());
    return static_cast<BuiltinFrame*>(frame);
  }
References v8::internal::DCHECK(), and v8::internal::StackFrame::is_builtin().
Referenced by v8::internal::Isolate::UnwindAndFindHandler().
ComputeParametersCount()
int v8::internal::BuiltinFrame::ComputeParametersCount () const [override], [virtual]
Reimplemented from v8::internal::CommonFrameWithJSLinkage.
Definition at line 3371 of file frames.cc.
                                               {
  const int offset = BuiltinFrameConstants::kLengthOffset;
  return Smi::ToInt(Tagged<Object>(base::Memory<Address>(fp() + offset))) -
         kJSArgcReceiverSlots;
}
References v8::internal::kJSArgcReceiverSlots, v8::internal::BuiltinFrameConstants::kLengthOffset, and v8::internal::Smi::ToInt().
function()
Tagged< JSFunction > v8::internal::BuiltinFrame::function () const [override], [virtual]
Implements v8::internal::CommonFrameWithJSLinkage.
Definition at line 3366 of file frames.cc.
                                                {
  const int offset = BuiltinFrameConstants::kFunctionOffset;
  return Cast<JSFunction>(Tagged<Object>(base::Memory<Address>(fp() + offset)));
}
References v8::internal::BuiltinFrameConstants::kFunctionOffset.
type()
Type v8::internal::BuiltinFrame::type () const [inline], [final], [virtual]
Implements v8::internal::StackFrame.
Definition at line 1241 of file frames.h.
{ return BUILTIN; }
References v8::internal::BUILTIN().
Friends And Related Function Documentation
StackFrameIteratorBase
friend class StackFrameIteratorBase [friend]
Definition at line 1255 of file frames.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/frames.h
/mnt/V8SourceCode/src/execution/frames-inl.h
/mnt/V8SourceCode/src/execution/frames.cc