v8::internal::compiler::StateValuesAccess::iterator Class Reference
#include <state-values-utils.h>
Public Member Functions
bool operator!= (iterator const &other) const
iterator & operator++ ()
TypedNode operator* ()
Node * node ()
bool done () const
size_t AdvanceTillNotEmpty ()
Private Member Functions
iterator ()
iterator (Node *node)
MachineType type ()
void Advance ()
void EnsureValid ()
SparseInputMask::InputIterator * Top ()
void Push (Node *node)
void Pop ()
Private Attributes
SparseInputMask::InputIterator stack_ [kMaxInlineDepth]
int current_depth_
Static Private Attributes
static const int kMaxInlineDepth = 8
Friends
class StateValuesAccess
Detailed Description
Definition at line 90 of file state-values-utils.h.
Constructor & Destructor Documentation
iterator() [1/2]
v8::internal::compiler::StateValuesAccess::iterator::iterator () [inline], [private]
Definition at line 105 of file state-values-utils.h.
: current_depth_(-1) {}
iterator() [2/2]
v8::internal::compiler::StateValuesAccess::iterator::iterator (Node * node) [explicit], [private]
Definition at line 304 of file state-values-utils.cc.
                                              : current_depth_(0) {
  stack_[current_depth_] =
      SparseInputMaskOf(node->op()).IterateOverInputs(node);
  EnsureValid();
}
References current_depth_, EnsureValid(), v8::internal::compiler::SparseInputMask::IterateOverInputs(), node(), v8::internal::compiler::Node::op(), v8::internal::compiler::SparseInputMaskOf(), and stack_.
Member Function Documentation
Advance()
void v8::internal::compiler::StateValuesAccess::iterator::Advance () [private]
Definition at line 329 of file state-values-utils.cc.
                                        {
  Top()->Advance();
  EnsureValid();
}
Referenced by v8::internal::compiler::StateValuesAccess::size().
AdvanceTillNotEmpty()
size_t v8::internal::compiler::StateValuesAccess::iterator::AdvanceTillNotEmpty ()
Definition at line 334 of file state-values-utils.cc.
                                                      {
  size_t count = 0;
  while (!done() && Top()->IsEmpty()) {
    count += Top()->AdvanceToNextRealOrEnd();
    EnsureValid();
  }
  return count;
}
done()
bool v8::internal::compiler::StateValuesAccess::iterator::done () const [inline]
Definition at line 97 of file state-values-utils.h.
{ return current_depth_ < 0; }
Referenced by v8::internal::compiler::StateValuesAccess::begin_without_receiver_and_skip(), operator!=(), v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), and v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
EnsureValid()
void v8::internal::compiler::StateValuesAccess::iterator::EnsureValid () [private]
Definition at line 343 of file state-values-utils.cc.
                                            {
  while (true) {
    SparseInputMask::InputIterator* top = Top();
    if (top->IsEmpty()) {
      // We are on a valid (albeit optimized out) node.
      return;
    }
    if (top->IsEnd()) {
      // We have hit the end of this iterator. Pop the stack and move to the
      // next sibling iterator.
      Pop();
      if (done()) {
        // Stack is exhausted, we have reached the end.
        return;
      }
      Top()->Advance();
      continue;
    }
    // At this point the value is known to be live and within our input nodes.
    Node* value_node = top->GetReal();
    if (value_node->opcode() == IrOpcode::kStateValues ||
        value_node->opcode() == IrOpcode::kTypedStateValues) {
      // Nested state, we need to push to the stack.
      Push(value_node);
      continue;
    }
    // We are on a valid node, we can stop the iteration.
    return;
  }
}
References v8::internal::compiler::SparseInputMask::InputIterator::GetReal(), v8::internal::compiler::SparseInputMask::InputIterator::IsEmpty(), v8::internal::compiler::SparseInputMask::InputIterator::IsEnd(), and v8::internal::compiler::Node::opcode().
Referenced by iterator().
node()
Node * v8::internal::compiler::StateValuesAccess::iterator::node ()
Definition at line 379 of file state-values-utils.cc.
                                      {
  DCHECK(!done());
  return Top()->Get(nullptr);
}
References v8::internal::DCHECK().
Referenced by iterator(), and v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
operator!=()
bool v8::internal::compiler::StateValuesAccess::iterator::operator!= (iterator const & other) const
Definition at line 397 of file state-values-utils.cc.
                                                                      {
  // We only allow comparison with end().
  CHECK(other.done());
  return !done();
}
References CHECK, and done().
operator*()
StateValuesAccess::TypedNode v8::internal::compiler::StateValuesAccess::iterator::operator* ()
Definition at line 410 of file state-values-utils.cc.
                                                                {
  return TypedNode(node(), type());
}
References v8::internal::tracing::type.
operator++()
StateValuesAccess::iterator & v8::internal::compiler::StateValuesAccess::iterator::operator++ ()
Definition at line 403 of file state-values-utils.cc.
                                                                 {
  DCHECK(!done());
  Advance();
  return *this;
}
References v8::internal::DCHECK().
Pop()
void v8::internal::compiler::StateValuesAccess::iterator::Pop () [private]
Definition at line 324 of file state-values-utils.cc.
                                    {
  DCHECK_LE(0, current_depth_);
  current_depth_--;
}
References DCHECK_LE.
Push()
void v8::internal::compiler::StateValuesAccess::iterator::Push (Node * node) [private]
Definition at line 316 of file state-values-utils.cc.
                                               {
  current_depth_++;
  CHECK_GT(kMaxInlineDepth, current_depth_);
  stack_[current_depth_] =
      SparseInputMaskOf(node->op()).IterateOverInputs(node);
}
References CHECK_GT, v8::internal::compiler::SparseInputMask::IterateOverInputs(), v8::internal::compiler::Node::op(), and v8::internal::compiler::SparseInputMaskOf().
Top()
SparseInputMask::InputIterator * v8::internal::compiler::StateValuesAccess::iterator::Top () [private]
Definition at line 310 of file state-values-utils.cc.
                                                             {
  DCHECK_LE(0, current_depth_);
  DCHECK_GT(kMaxInlineDepth, current_depth_);
  return &(stack_[current_depth_]);
}
References DCHECK_GT, and DCHECK_LE.
type()
MachineType v8::internal::compiler::StateValuesAccess::iterator::type () [private]
Definition at line 384 of file state-values-utils.cc.
                                            {
  Node* parent = Top()->parent();
  DCHECK(!Top()->IsEmpty());
  if (parent->opcode() == IrOpcode::kStateValues) {
    return MachineType::AnyTagged();
  } else {
    DCHECK_EQ(IrOpcode::kTypedStateValues, parent->opcode());
    ZoneVector<MachineType> const* types = MachineTypesOf(parent->op());
    return (*types)[Top()->real_index()];
  }
}
References v8::internal::MachineType::AnyTagged(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::MachineTypesOf(), v8::internal::compiler::Node::op(), and v8::internal::compiler::Node::opcode().
Friends And Related Function Documentation
StateValuesAccess
friend class StateValuesAccess [friend]
Definition at line 103 of file state-values-utils.h.
Member Data Documentation
current_depth_
int v8::internal::compiler::StateValuesAccess::iterator::current_depth_ [private]
Definition at line 118 of file state-values-utils.h.
Referenced by iterator().
kMaxInlineDepth
const int v8::internal::compiler::StateValuesAccess::iterator::kMaxInlineDepth = 8 [static], [private]
Definition at line 116 of file state-values-utils.h.
stack_
SparseInputMask::InputIterator v8::internal::compiler::StateValuesAccess::iterator::stack_[kMaxInlineDepth] [private]
Definition at line 117 of file state-values-utils.h.
Referenced by iterator().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/state-values-utils.h
/mnt/V8SourceCode/src/compiler/state-values-utils.cc