v8::internal::WasmInternalFunction Class Reference
#include <wasm-objects.h>
Public Types
using BodyDescriptor = StackedBodyDescriptor< FixedExposedTrustedObjectBodyDescriptor< WasmInternalFunction, kWasmInternalFunctionIndirectPointerTag >, WithProtectedPointer< kProtectedImplicitArgOffset > >
Public Member Functions
bool try_get_external (Tagged< JSFunction > *result)
WasmCodePointer call_target ()
void set_call_target (WasmCodePointer code_pointer)
Static Public Member Functions
static V8_EXPORT_PRIVATE DirectHandle< JSFunction > GetOrCreateExternal (DirectHandle< WasmInternalFunction > internal)
Detailed Description
Definition at line 1165 of file wasm-objects.h.
Member Typedef Documentation
BodyDescriptor
using v8::internal::WasmInternalFunction::BodyDescriptor = StackedBodyDescriptor< FixedExposedTrustedObjectBodyDescriptor< WasmInternalFunction, kWasmInternalFunctionIndirectPointerTag>, WithProtectedPointer<kProtectedImplicitArgOffset> >
Definition at line 1184 of file wasm-objects.h.
Member Function Documentation
call_target()
WasmCodePointer v8::internal::WasmInternalFunction::call_target () [inline]
Definition at line 484 of file wasm-objects-inl.h.
                                                  {
  return WasmCodePointer{raw_call_target()};
}
GetOrCreateExternal()
DirectHandle< JSFunction > v8::internal::WasmInternalFunction::GetOrCreateExternal (DirectHandle< WasmInternalFunction > internal) [static]
Definition at line 2045 of file wasm-objects.cc.
                                                 {
  Isolate* isolate = Isolate::Current();
  Tagged<JSFunction> existing_external;
  if (internal->try_get_external(&existing_external)) {
    return direct_handle(existing_external, isolate);
  }
  // {this} can either be:
  // - a declared function, i.e. {implicit_arg()} is a WasmTrustedInstanceData,
  // - or an imported callable, i.e. {implicit_arg()} is a WasmImportData which
  // refers to the imported instance.
  // It cannot be a JS/C API function as for those, the external function is set
  // at creation.
  DirectHandle<TrustedObject> implicit_arg{internal->implicit_arg(), isolate};
  DirectHandle<WasmTrustedInstanceData> instance_data =
      IsWasmTrustedInstanceData(*implicit_arg)
          ? Cast<WasmTrustedInstanceData>(implicit_arg)
          : direct_handle(Cast<WasmImportData>(*implicit_arg)->instance_data(),
                          isolate);
  const WasmModule* module = instance_data->module();
  const WasmFunction& function = module->functions[internal->function_index()];
  wasm::CanonicalTypeIndex sig_id =
      module->canonical_sig_id(function.sig_index);
  const wasm::CanonicalSig* sig =
      wasm::GetTypeCanonicalizer()->LookupFunctionSignature(sig_id);
  wasm::TypeCanonicalizer::PrepareForCanonicalTypeId(isolate, sig_id);
  // For now, we assume traditional behavior where the receiver is ignored.
  // If the corresponding bit in the WasmExportedFunctionData is flipped later,
  // we'll have to reset any existing compiled wrapper.
  bool receiver_is_first_param = false;
  DirectHandle<Code> wrapper_code = WasmExportedFunction::GetWrapper(
      isolate, sig, sig_id, receiver_is_first_param, module);
  DirectHandle<WasmFuncRef> func_ref{
      Cast<WasmFuncRef>(
          instance_data->func_refs()->get(internal->function_index())),
      isolate};
  DCHECK_EQ(func_ref->internal(isolate), *internal);
  auto result = WasmExportedFunction::New(
      isolate, instance_data, func_ref, internal,
      static_cast<int>(sig->parameter_count()), wrapper_code);
  internal->set_external(*result);
  return result;
}
References v8::internal::wasm::WasmModule::canonical_sig_id(), v8::internal::Isolate::Current(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::wasm::WasmModule::functions, v8::internal::wasm::GetTypeCanonicalizer(), v8::internal::WasmExportedFunction::GetWrapper(), v8::internal::instance_data, v8::internal::internal, v8::internal::wasm::TypeCanonicalizer::LookupFunctionSignature(), v8::internal::WasmExportedFunction::New(), v8::internal::wasm::TypeCanonicalizer::PrepareForCanonicalTypeId(), v8::base::internal::result, and v8::internal::sig.
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteCallRef(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::FunctionsProxy::Get(), v8::internal::wasm::JSPrototypesSetup::GetFunction(), v8::internal::WasmTableObject::GetFunctionTableEntry(), v8::internal::WasmValueObject::New(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::RUNTIME_FUNCTION(), v8::internal::WasmTableObject::SetFunctionTableEntry(), v8::internal::wasm::WasmToJSObject(), and v8::internal::wasm::WasmInterpreterRuntime::WasmToJSObject().
set_call_target()
void v8::internal::WasmInternalFunction::set_call_target (WasmCodePointer code_pointer) [inline]
Definition at line 487 of file wasm-objects-inl.h.
                                                                       {
  set_raw_call_target(code_pointer.value());
}
References v8::internal::WasmCodePointer::value().
try_get_external()
bool v8::internal::WasmInternalFunction::try_get_external (Tagged< JSFunction > * result)
Definition at line 2038 of file wasm-objects.cc.
                                                                      {
  if (IsUndefined(external())) return false;
  *result = Cast<JSFunction>(external());
  return true;
}
References v8::base::internal::result.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-objects.h
/mnt/V8SourceCode/src/wasm/wasm-objects-inl.h
/mnt/V8SourceCode/src/wasm/wasm-objects.cc