v8::internal::wasm::MultiLineStringBuilder Class Reference
#include <string-builder-multiline.h>
Classes
struct Line
Public Member Functions
MultiLineStringBuilder ()
void NextLine (uint32_t byte_offset)
size_t line_number ()
void set_current_line_bytecode_offset (uint32_t offset)
uint32_t current_line_bytecode_offset ()
void PatchLabel (LabelInfo &label, const char *label_source)
void ToDisassemblyCollector (v8::debug::DisassemblyCollector *collector)
void WriteTo (std::ostream &out, bool print_offsets, std::vector< uint32_t > *collect_offsets=nullptr)
size_t ApproximateSizeMB ()
Private Attributes
std::vector< Line > lines_
uint32_t pending_bytecode_offset_ = 0
Additional Inherited Members
Detailed Description
Definition at line 48 of file string-builder-multiline.h.
Constructor & Destructor Documentation
MultiLineStringBuilder()
v8::internal::wasm::MultiLineStringBuilder::MultiLineStringBuilder () [inline]
Definition at line 50 of file string-builder-multiline.h.
: StringBuilder(kKeepOldChunks) {}
Member Function Documentation
ApproximateSizeMB()
size_t v8::internal::wasm::MultiLineStringBuilder::ApproximateSizeMB () [inline]
Definition at line 178 of file string-builder-multiline.h.
{ return approximate_size_mb(); }
References v8::internal::wasm::StringBuilder::approximate_size_mb().
Referenced by v8::internal::wasm::ModuleDisassembler::PrintModule().
current_line_bytecode_offset()
uint32_t v8::internal::wasm::MultiLineStringBuilder::current_line_bytecode_offset () [inline]
Definition at line 64 of file string-builder-multiline.h.
{ return pending_bytecode_offset_; }
References pending_bytecode_offset_.
Referenced by v8::internal::wasm::ModuleDisassembler::PrintModule().
line_number()
size_t v8::internal::wasm::MultiLineStringBuilder::line_number () [inline]
Definition at line 59 of file string-builder-multiline.h.
{ return lines_.size(); }
References lines_.
Referenced by v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat().
NextLine()
void v8::internal::wasm::MultiLineStringBuilder::NextLine (uint32_t byte_offset) [inline]
Definition at line 52 of file string-builder-multiline.h.
                                      {
    *allocate(1) = '\n';
    size_t len = length();
    lines_.emplace_back(start(), len, pending_bytecode_offset_);
    start_here();
    pending_bytecode_offset_ = byte_offset;
  }
References v8::internal::wasm::StringBuilder::allocate(), v8::internal::wasm::StringBuilder::length(), lines_, pending_bytecode_offset_, v8::internal::wasm::StringBuilder::start(), and v8::internal::wasm::StringBuilder::start_here().
Referenced by v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), v8::internal::wasm::ModuleDisassembler::LineBreakOrSpace(), v8::internal::wasm::ModuleDisassembler::PrintModule(), v8::internal::wasm::ModuleDisassembler::PrintTypeDefinition(), ToDisassemblyCollector(), and WriteTo().
PatchLabel()
void v8::internal::wasm::MultiLineStringBuilder::PatchLabel (LabelInfo & label, const char * label_source) [inline]
Definition at line 74 of file string-builder-multiline.h.
                                                              {
    DCHECK_GT(label.length, 0);
    DCHECK_LT(label.line_number, lines_.size());
    // Step 1: Patching a line makes it longer, and we can't grow it in-place
    // because it's boxed in, so allocate space for its patched copy.
    char* patched_line;
    Line& l = lines_[label.line_number];
    // +1 because we add a space before the label: "block" -> "block $label0",
    // "block i32" -> "block $label0 i32".
    size_t patched_length = l.len + label.length + 1;
    if (length() == 0) {
      // No current unfinished line. Allocate the patched line as if it was
      // the next line.
      patched_line = allocate(patched_length);
      start_here();
    } else {
      // Shift the current unfinished line out of the way.
      // TODO(jkummerow): This approach ends up being O(n²) for a `br_table`
      // with `n` labels. If that ever becomes a problem, we could allocate a
      // separate new chunk for patched copies of old lines, then we wouldn't
      // need to shift the unfinished line around.
      const char* unfinished_start = start(); // Remember the unfinished
      size_t unfinished_length = length(); // line, and...
      rewind_to_start(); // ...free up its space.
      patched_line = allocate(patched_length);
      // Write the unfinished line into its new location.
      start_here();
      char* new_location = allocate(unfinished_length);
      memmove(new_location, unfinished_start, unfinished_length);
      if (label_source >= unfinished_start &&
          label_source < unfinished_start + unfinished_length) {
        label_source = new_location + (label_source - unfinished_start);
      }
    }
    // Step 2: Write the patched copy of the line to be patched.
    char* cursor = patched_line;
    memcpy(cursor, l.data, label.offset);
    cursor += label.offset;
    *(cursor++) = ' ';
    label.start = cursor;
    memcpy(cursor, label_source, label.length);
    cursor += label.length;
    memcpy(cursor, l.data + label.offset, l.len - label.offset);
    l.data = patched_line;
    l.len = patched_length;
  }
References v8::internal::wasm::StringBuilder::allocate(), v8::internal::wasm::StringBuilder::cursor(), DCHECK_GT, DCHECK_LT, v8::internal::compiler::turboshaft::l, v8::internal::wasm::LabelInfo::length, v8::internal::wasm::StringBuilder::length(), v8::internal::wasm::LabelInfo::line_number, lines_, v8::internal::wasm::LabelInfo::offset, v8::internal::wasm::StringBuilder::rewind_to_start(), v8::internal::wasm::LabelInfo::start, v8::internal::wasm::StringBuilder::start(), and v8::internal::wasm::StringBuilder::start_here().
Referenced by v8::internal::wasm::ImmediatesPrinter< ValidationTag >::PrintDepthAsLabel().
set_current_line_bytecode_offset()
void v8::internal::wasm::MultiLineStringBuilder::set_current_line_bytecode_offset (uint32_t offset) [inline]
Definition at line 61 of file string-builder-multiline.h.
                                                         {
    pending_bytecode_offset_ = offset;
  }
References pending_bytecode_offset_.
Referenced by v8::internal::wasm::FunctionBodyDisassembler::DecodeAsWat(), and v8::internal::wasm::ModuleDisassembler::PrintModule().
ToDisassemblyCollector()
void v8::internal::wasm::MultiLineStringBuilder::ToDisassemblyCollector (v8::debug::DisassemblyCollector * collector)
Definition at line 59 of file wasm-disassembler.cc.
                                            {
  if (length() != 0) NextLine(0); // Finalize last line.
  collector->ReserveLineCount(lines_.size());
  for (const Line& l : lines_) {
    // Don't include trailing '\n'.
    collector->AddLine(l.data, l.len - 1, l.bytecode_offset);
  }
}
References v8::debug::DisassemblyCollector::AddLine(), v8::internal::compiler::turboshaft::l, v8::internal::wasm::StringBuilder::length(), lines_, NextLine(), and v8::debug::DisassemblyCollector::ReserveLineCount().
Referenced by v8::internal::wasm::Disassemble().
WriteTo()
void v8::internal::wasm::MultiLineStringBuilder::WriteTo (std::ostream & out, bool print_offsets, std::vector< uint32_t > * collect_offsets = nullptr) [inline]
Definition at line 126 of file string-builder-multiline.h.
                                                               {
    if (length() != 0) NextLine(0);
    if (lines_.size() == 0) return;
    if (print_offsets) {
      // The last offset is expected to be the largest.
      int width = GetNumDigits(lines_.back().bytecode_offset);
      // We could have used std::setw(width), but this is faster.
      constexpr int kBufSize = 12; // Enough for any uint32 plus '|'.
      char buffer[kBufSize] = {32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, '|'};
      char* const buffer_end = buffer + kBufSize - 1;
      char* const buffer_start = buffer_end - width;
      for (const Line& l : lines_) {
        uint32_t offset = l.bytecode_offset;
        char* ptr = buffer_end;
        do {
          *(--ptr) = '0' + (offset % 10);
          offset /= 10;
          // We pre-filled the buffer with spaces, and the offsets are expected
          // to be increasing, so we can just stop the loop here and don't need
          // to write spaces until {ptr == buffer_start}.
        } while (offset > 0);
        out.write(buffer_start, width + 1); // +1 for the '|'.
        out.write(l.data, l.len);
      }
      return;
    }
    // In the name of speed, batch up lines that happen to be stored
    // consecutively.
    const Line& first = lines_[0];
    const char* last_start = first.data;
    size_t len = first.len;
    for (size_t i = 1; i < lines_.size(); i++) {
      const Line& l = lines_[i];
      if (last_start + len == l.data) {
        len += l.len;
      } else {
        out.write(last_start, len);
        last_start = l.data;
        len = l.len;
      }
    }
    out.write(last_start, len);
    if (collect_offsets) {
      collect_offsets->reserve(lines_.size());
      for (const Line& l : lines_) {
        collect_offsets->push_back(l.bytecode_offset);
      }
    }
  }
References v8::internal::wasm::MultiLineStringBuilder::Line::data, v8::internal::wasm::GetNumDigits(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::l, v8::internal::wasm::MultiLineStringBuilder::Line::len, v8::internal::wasm::StringBuilder::length(), lines_, and NextLine().
Referenced by v8::internal::wasm::DisassembleFunctionImpl().
Member Data Documentation
lines_
std::vector<Line> v8::internal::wasm::MultiLineStringBuilder::lines_ [private]
Definition at line 189 of file string-builder-multiline.h.
Referenced by line_number(), NextLine(), PatchLabel(), ToDisassemblyCollector(), and WriteTo().
pending_bytecode_offset_
uint32_t v8::internal::wasm::MultiLineStringBuilder::pending_bytecode_offset_ = 0 [private]
Definition at line 190 of file string-builder-multiline.h.
Referenced by current_line_bytecode_offset(), NextLine(), and set_current_line_bytecode_offset().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/string-builder-multiline.h
/mnt/V8SourceCode/src/wasm/wasm-disassembler.cc