v8::internal::interpreter::JumpTableTargetOffsets::iterator Class Reference
#include <bytecode-array-iterator.h>
Public Member Functions
iterator (int case_value, int table_offset, int table_end, const BytecodeArrayIterator *iterator)
JumpTableTargetOffset operator* ()
iterator & operator++ ()
bool operator!= (const iterator &other)
Private Member Functions
void UpdateAndAdvanceToValid ()
Private Attributes
const BytecodeArrayIterator * iterator_
Tagged< Smi > current_
int index_
int table_offset_
int table_end_
Detailed Description
Definition at line 36 of file bytecode-array-iterator.h.
Constructor & Destructor Documentation
iterator()
v8::internal::interpreter::JumpTableTargetOffsets::iterator::iterator (int case_value, int table_offset, int table_end, const BytecodeArrayIterator * iterator)
Definition at line 393 of file bytecode-array-iterator.cc.
    : iterator_(iterator),
      current_(Smi::zero()),
      index_(case_value),
      table_offset_(table_offset),
      table_end_(table_end) {
  UpdateAndAdvanceToValid();
}
References UpdateAndAdvanceToValid().
Member Function Documentation
operator!=()
bool v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator!= (const iterator & other)
Definition at line 418 of file bytecode-array-iterator.cc.
                                                 {
  DCHECK_EQ(iterator_, other.iterator_);
  DCHECK_EQ(table_end_, other.table_end_);
  DCHECK_EQ(index_ - other.index_, table_offset_ - other.table_offset_);
  return index_ != other.index_;
}
References DCHECK_EQ, index_, iterator_, v8::internal::interpreter::JumpTableTargetOffsets::iterator_, table_end_, and table_offset_.
operator*()
JumpTableTargetOffset v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator* ()
Definition at line 404 of file bytecode-array-iterator.cc.
                                                                {
  DCHECK_LT(table_offset_, table_end_);
  return {index_, iterator_->GetAbsoluteOffset(Smi::ToInt(current_))};
}
References DCHECK_LT, v8::internal::interpreter::BytecodeArrayIterator::GetAbsoluteOffset(), v8::internal::interpreter::JumpTableTargetOffsets::iterator_, and v8::internal::Smi::ToInt().
operator++()
JumpTableTargetOffsets::iterator & v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator++ ()
Definition at line 410 of file bytecode-array-iterator.cc.
                                           {
  DCHECK_LT(table_offset_, table_end_);
  ++table_offset_;
  ++index_;
  UpdateAndAdvanceToValid();
  return *this;
}
References DCHECK_LT.
UpdateAndAdvanceToValid()
void v8::internal::interpreter::JumpTableTargetOffsets::iterator::UpdateAndAdvanceToValid () [private]
Definition at line 426 of file bytecode-array-iterator.cc.
                                                             {
  while (table_offset_ < table_end_ &&
         !iterator_->IsConstantAtIndexSmi(table_offset_)) {
    ++table_offset_;
    ++index_;
  }
  // Make sure we haven't reached the end of the table with a hole in current.
  if (table_offset_ < table_end_) {
    DCHECK(iterator_->IsConstantAtIndexSmi(table_offset_));
    current_ = iterator_->GetConstantAtIndexAsSmi(table_offset_);
  }
}
References v8::internal::DCHECK(), v8::internal::interpreter::BytecodeArrayIterator::GetConstantAtIndexAsSmi(), v8::internal::interpreter::BytecodeArrayIterator::IsConstantAtIndexSmi(), and v8::internal::interpreter::JumpTableTargetOffsets::iterator_.
Referenced by iterator().
Member Data Documentation
current_
Tagged<Smi> v8::internal::interpreter::JumpTableTargetOffsets::iterator::current_ [private]
Definition at line 49 of file bytecode-array-iterator.h.
index_
int v8::internal::interpreter::JumpTableTargetOffsets::iterator::index_ [private]
Definition at line 50 of file bytecode-array-iterator.h.
Referenced by operator!=().
iterator_
const BytecodeArrayIterator* v8::internal::interpreter::JumpTableTargetOffsets::iterator::iterator_ [private]
Definition at line 48 of file bytecode-array-iterator.h.
Referenced by operator!=().
table_end_
int v8::internal::interpreter::JumpTableTargetOffsets::iterator::table_end_ [private]
Definition at line 52 of file bytecode-array-iterator.h.
Referenced by operator!=().
table_offset_
int v8::internal::interpreter::JumpTableTargetOffsets::iterator::table_offset_ [private]
Definition at line 51 of file bytecode-array-iterator.h.
Referenced by operator!=().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecode-array-iterator.h
/mnt/V8SourceCode/src/interpreter/bytecode-array-iterator.cc