v8::internal::wasm::DescriptorsSectionIterator Class Reference
#include <module-decoder-impl.h>
Classes
class DeclEntry
class Entry
class GlobalEntry
class ImportEntry
struct Method
class ProtoConfig
Public Member Functions
DescriptorsSectionIterator (base::Vector< const uint8_t > wire_bytes, uint32_t start_offset, uint32_t end_offset)
WireBytesRef module_name () const
bool has_import_entry ()
ImportEntry NextImportEntry ()
bool has_decl_entry ()
DeclEntry NextDeclEntry ()
bool has_proto_config ()
ProtoConfig NextProtoConfig (uint32_t max_import_index)
bool has_global_entry ()
GlobalEntry NextGlobalEntry (uint32_t max_global_index)
void SkipToGlobalEntries ()
void SkipToProtoConfigs ()
uint32_t NumImportAndDeclEntries () const
Private Types
enum class State : uint8_t {
kUninitialized
, kImportEntries
, kDeclEntries
, kGlobalEntries
,
kOffsetEntries
, kProtoConfigs
, kFinished
, kInImportEntry = kImportEntries | kStateBlocked
,
kInDeclEntry = kDeclEntries | kStateBlocked
, kInGlobalEntry = kGlobalEntries | kStateBlocked
, kInOffsetEntry = kOffsetEntries | kStateBlocked
, kInProtoConfig = kProtoConfigs | kStateBlocked
 }
Private Member Functions
WireBytesRef consume_string (const char *description)
void NextSubsection ()
void SkipCurrentSubsection ()
void FinishEntry ()
Private Attributes
State state_ {State::kUninitialized}
uint32_t num_entries_ {0}
uint32_t index_ {0}
uint32_t next_subsection_start_position_ {0}
uint32_t next_min_global_index_ {0}
WireBytesRef module_name_
Static Private Attributes
static constexpr uint8_t kImportEntriesCode = 0
static constexpr uint8_t kDeclEntriesCode = 1
static constexpr uint8_t kGlobalEntriesCode = 2
static constexpr uint8_t kOffsetEntriesCode = 3
static constexpr uint8_t kProtoConfigsCode = 4
static constexpr uint8_t kStateBlocked = 0b1000'0000
Additional Inherited Members
Detailed Description
Definition at line 2921 of file module-decoder-impl.h.
Member Enumeration Documentation
State
enum v8::internal::wasm::DescriptorsSectionIterator::State : uint8_t [strong], [private]
Enumerator
kUninitialized
kImportEntries
kDeclEntries
kGlobalEntries
kOffsetEntries
kProtoConfigs
kFinished
kInImportEntry
kInDeclEntry
kInGlobalEntry
kInOffsetEntry
kInProtoConfig
Definition at line 3294 of file module-decoder-impl.h.
                   : uint8_t {
    kUninitialized,
    kImportEntries,
    kDeclEntries,
    kGlobalEntries,
    kOffsetEntries,
    kProtoConfigs,
    kFinished,
    kInImportEntry = kImportEntries | kStateBlocked,
    kInDeclEntry = kDeclEntries | kStateBlocked,
    kInGlobalEntry = kGlobalEntries | kStateBlocked,
    kInOffsetEntry = kOffsetEntries | kStateBlocked,
    kInProtoConfig = kProtoConfigs | kStateBlocked,
  };
Constructor & Destructor Documentation
DescriptorsSectionIterator()
v8::internal::wasm::DescriptorsSectionIterator::DescriptorsSectionIterator (base::Vector< const uint8_t > wire_bytes, uint32_t start_offset, uint32_t end_offset) [inline]
Definition at line 2923 of file module-decoder-impl.h.
      : Decoder(wire_bytes.begin() + start_offset,
                wire_bytes.begin() + end_offset, start_offset) {
    // Version.
    uint32_t version = consume_u32v("version");
    if (!ok()) return;
    if (version != 0) {
      errorf(start_, "unsupported descriptors section version: %u", version);
      return;
    }
    // Module name.
    module_name_ = consume_string("module name");
    if (!ok()) return;
    NextSubsection();
  }
References consume_string(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::errorf(), module_name_, NextSubsection(), v8::internal::wasm::Decoder::ok(), and v8::internal::wasm::Decoder::start_.
Member Function Documentation
consume_string()
WireBytesRef v8::internal::wasm::DescriptorsSectionIterator::consume_string (const char * description) [inline], [private]
Definition at line 3310 of file module-decoder-impl.h.
                                                       {
    return wasm::consume_string(this, unibrow::Utf8Variant::kLossyUtf8,
                                description);
  }
References v8::internal::wasm::consume_string(), and unibrow::kLossyUtf8.
Referenced by v8::internal::wasm::DescriptorsSectionIterator::Entry::Constructor(), v8::internal::wasm::DescriptorsSectionIterator::Entry::consume_string(), DescriptorsSectionIterator(), and v8::internal::wasm::DescriptorsSectionIterator::Entry::NextMethodImpl().
FinishEntry()
void v8::internal::wasm::DescriptorsSectionIterator::FinishEntry () [inline], [private]
Definition at line 3356 of file module-decoder-impl.h.
                     {
    state_ = static_cast<State>(static_cast<uint8_t>(state_) &
                                static_cast<uint8_t>(~kStateBlocked));
    index_++;
    if (index_ == num_entries_) NextSubsection();
  }
References index_, kStateBlocked, NextSubsection(), num_entries_, and state_.
Referenced by v8::internal::wasm::DescriptorsSectionIterator::Entry::Finish().
has_decl_entry()
bool v8::internal::wasm::DescriptorsSectionIterator::has_decl_entry () [inline]
Definition at line 3234 of file module-decoder-impl.h.
{ return state_ == State::kDeclEntries; }
References kDeclEntries, and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl(), and NextDeclEntry().
has_global_entry()
bool v8::internal::wasm::DescriptorsSectionIterator::has_global_entry () [inline]
Definition at line 3248 of file module-decoder-impl.h.
{ return state_ == State::kGlobalEntries; }
References kGlobalEntries, and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), and NextGlobalEntry().
has_import_entry()
bool v8::internal::wasm::DescriptorsSectionIterator::has_import_entry () [inline]
Definition at line 3227 of file module-decoder-impl.h.
{ return state_ == State::kImportEntries; }
References kImportEntries, and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl(), and NextImportEntry().
has_proto_config()
bool v8::internal::wasm::DescriptorsSectionIterator::has_proto_config () [inline]
Definition at line 3241 of file module-decoder-impl.h.
{ return state_ == State::kProtoConfigs; }
References kProtoConfigs, and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl(), and NextProtoConfig().
module_name()
WireBytesRef v8::internal::wasm::DescriptorsSectionIterator::module_name () const [inline]
Definition at line 2942 of file module-decoder-impl.h.
{ return module_name_; }
References module_name_.
Referenced by v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl().
NextDeclEntry()
DeclEntry v8::internal::wasm::DescriptorsSectionIterator::NextDeclEntry () [inline]
Definition at line 3235 of file module-decoder-impl.h.
                            {
    DCHECK(has_decl_entry());
    state_ = State::kInDeclEntry;
    return DeclEntry(this);
  }
References v8::internal::DCHECK(), has_decl_entry(), kInDeclEntry, and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl().
NextGlobalEntry()
GlobalEntry v8::internal::wasm::DescriptorsSectionIterator::NextGlobalEntry (uint32_t max_global_index) [inline]
Definition at line 3249 of file module-decoder-impl.h.
                                                         {
    DCHECK(has_global_entry());
    state_ = State::kInGlobalEntry;
    return GlobalEntry(this, max_global_index);
  }
References v8::internal::DCHECK(), has_global_entry(), kInGlobalEntry, and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl().
NextImportEntry()
ImportEntry v8::internal::wasm::DescriptorsSectionIterator::NextImportEntry () [inline]
Definition at line 3228 of file module-decoder-impl.h.
                                {
    DCHECK(has_import_entry());
    state_ = State::kInImportEntry;
    return ImportEntry(this);
  }
References v8::internal::DCHECK(), has_import_entry(), kInImportEntry, and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl().
NextProtoConfig()
ProtoConfig v8::internal::wasm::DescriptorsSectionIterator::NextProtoConfig (uint32_t max_import_index) [inline]
Definition at line 3242 of file module-decoder-impl.h.
                                                         {
    DCHECK(has_proto_config());
    state_ = State::kInProtoConfig;
    return ProtoConfig(this, max_import_index);
  }
References v8::internal::DCHECK(), has_proto_config(), kInProtoConfig, and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl().
NextSubsection()
void v8::internal::wasm::DescriptorsSectionIterator::NextSubsection () [inline], [private]
Definition at line 3315 of file module-decoder-impl.h.
                        {
    if (!more()) {
      state_ = State::kFinished;
      return;
    }
    const uint8_t* pos = pc_;
    uint8_t subsection_id = consume_u8("subsection ID");
    DCHECK(ok()); // Reading one byte can't fail after {more()}.
#define SUBSECTION(Name) \
  if (subsection_id == k##Name##Code) { \
    if (state_ >= State::k##Name) { \
      return error(pos, "invalid subsection order"); \
    } \
    state_ = State::k##Name; \
    index_ = 0; \
    uint32_t subsection_length = consume_u32v("subsection length"); \
    if (!ok()) return; \
    next_subsection_start_position_ = position() + subsection_length; \
    num_entries_ = consume_u32v("number of " #Name); \
    if (!ok()) return; \
    if (num_entries_ == 0) return NextSubsection(); \
    return; \
  }
    SUBSECTION(ImportEntries)
    SUBSECTION(DeclEntries)
    SUBSECTION(GlobalEntries)
    SUBSECTION(OffsetEntries)
    SUBSECTION(ProtoConfigs)
#undef SUBSECTION
    state_ = State::kFinished;
    errorf(pos, "invalid subsection ID %u", subsection_id);
  }
References v8::internal::wasm::Decoder::consume_u8(), v8::internal::DCHECK(), v8::internal::wasm::Decoder::errorf(), kFinished, v8::internal::wasm::Decoder::more(), v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::pc_, state_, and SUBSECTION.
Referenced by DescriptorsSectionIterator(), FinishEntry(), and SkipCurrentSubsection().
NumImportAndDeclEntries()
uint32_t v8::internal::wasm::DescriptorsSectionIterator::NumImportAndDeclEntries () const [inline]
Definition at line 3263 of file module-decoder-impl.h.
                                           {
    static_assert(State::kGlobalEntries > State::kDeclEntries);
    static_assert(State::kDeclEntries > State::kImportEntries);
    if (state_ >= State::kGlobalEntries || !ok()) return 0;
    if (state_ == State::kDeclEntries) return num_entries_;
    DCHECK_EQ(state_, State::kImportEntries);
    uint32_t num_import_entries = num_entries_;
    // Use a separate decoder because we have to both rewind (to be able to
    // skip the importdecls section) and jump forward (to the vector length
    // of the declentries section).
    const uint8_t* next_subsection = start_ + next_subsection_start_position_;
    if (next_subsection >= end_) return num_import_entries;
    Decoder d(next_subsection, end_,
              buffer_offset_ + next_subsection_start_position_);
    uint8_t subsection = d.consume_u8("second subsection");
    if (!d.ok() || subsection != kDeclEntriesCode) return num_import_entries;
    d.consume_u32v("subsection length");
    if (!d.ok()) return num_import_entries;
    uint32_t num_decl_entries = d.consume_u32v("number of decl entries");
    if (!d.ok()) return num_import_entries;
    return num_import_entries + num_decl_entries;
  }
References v8::internal::wasm::Decoder::buffer_offset_, v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), DCHECK_EQ, v8::internal::wasm::Decoder::end_, kDeclEntries, kDeclEntriesCode, kGlobalEntries, kImportEntries, next_subsection_start_position_, num_entries_, v8::internal::wasm::Decoder::ok(), v8::internal::wasm::Decoder::start_, and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl().
SkipCurrentSubsection()
void v8::internal::wasm::DescriptorsSectionIterator::SkipCurrentSubsection () [inline], [private]
Definition at line 3350 of file module-decoder-impl.h.
                               {
    DCHECK_GE(next_subsection_start_position_, position());
    consume_bytes(next_subsection_start_position_ - position());
    NextSubsection();
  }
References v8::internal::wasm::Decoder::consume_bytes(), DCHECK_GE, next_subsection_start_position_, NextSubsection(), and v8::internal::wasm::Decoder::position().
Referenced by SkipToGlobalEntries(), and SkipToProtoConfigs().
SkipToGlobalEntries()
void v8::internal::wasm::DescriptorsSectionIterator::SkipToGlobalEntries () [inline]
Definition at line 3255 of file module-decoder-impl.h.
                             {
    while (state_ < State::kGlobalEntries) SkipCurrentSubsection();
  }
References kGlobalEntries, SkipCurrentSubsection(), and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl().
SkipToProtoConfigs()
void v8::internal::wasm::DescriptorsSectionIterator::SkipToProtoConfigs () [inline]
Definition at line 3258 of file module-decoder-impl.h.
                            {
    while (state_ < State::kProtoConfigs) SkipCurrentSubsection();
  }
References kProtoConfigs, SkipCurrentSubsection(), and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl().
Member Data Documentation
index_
uint32_t v8::internal::wasm::DescriptorsSectionIterator::index_ {0} [private]
Definition at line 3365 of file module-decoder-impl.h.
Referenced by FinishEntry().
kDeclEntriesCode
constexpr uint8_t v8::internal::wasm::DescriptorsSectionIterator::kDeclEntriesCode = 1 [static], [constexpr], [private]
Definition at line 3288 of file module-decoder-impl.h.
Referenced by NumImportAndDeclEntries().
kGlobalEntriesCode
constexpr uint8_t v8::internal::wasm::DescriptorsSectionIterator::kGlobalEntriesCode = 2 [static], [constexpr], [private]
Definition at line 3289 of file module-decoder-impl.h.
kImportEntriesCode
constexpr uint8_t v8::internal::wasm::DescriptorsSectionIterator::kImportEntriesCode = 0 [static], [constexpr], [private]
Definition at line 3287 of file module-decoder-impl.h.
kOffsetEntriesCode
constexpr uint8_t v8::internal::wasm::DescriptorsSectionIterator::kOffsetEntriesCode = 3 [static], [constexpr], [private]
Definition at line 3290 of file module-decoder-impl.h.
kProtoConfigsCode
constexpr uint8_t v8::internal::wasm::DescriptorsSectionIterator::kProtoConfigsCode = 4 [static], [constexpr], [private]
Definition at line 3291 of file module-decoder-impl.h.
kStateBlocked
constexpr uint8_t v8::internal::wasm::DescriptorsSectionIterator::kStateBlocked = 0b1000'0000 [static], [constexpr], [private]
Definition at line 3293 of file module-decoder-impl.h.
Referenced by FinishEntry().
module_name_
WireBytesRef v8::internal::wasm::DescriptorsSectionIterator::module_name_ [private]
Definition at line 3368 of file module-decoder-impl.h.
Referenced by DescriptorsSectionIterator(), and module_name().
next_min_global_index_
uint32_t v8::internal::wasm::DescriptorsSectionIterator::next_min_global_index_ {0} [private]
Definition at line 3367 of file module-decoder-impl.h.
Referenced by v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::GlobalEntry().
next_subsection_start_position_
uint32_t v8::internal::wasm::DescriptorsSectionIterator::next_subsection_start_position_ {0} [private]
Definition at line 3366 of file module-decoder-impl.h.
Referenced by NumImportAndDeclEntries(), and SkipCurrentSubsection().
num_entries_
uint32_t v8::internal::wasm::DescriptorsSectionIterator::num_entries_ {0} [private]
Definition at line 3364 of file module-decoder-impl.h.
Referenced by FinishEntry(), and NumImportAndDeclEntries().
state_
State v8::internal::wasm::DescriptorsSectionIterator::state_ {State::kUninitialized} [private]
Definition at line 3363 of file module-decoder-impl.h.
Referenced by v8::internal::wasm::DescriptorsSectionIterator::Entry::CheckIndex(), FinishEntry(), has_decl_entry(), has_global_entry(), has_import_entry(), has_proto_config(), NextDeclEntry(), NextGlobalEntry(), NextImportEntry(), NextProtoConfig(), NextSubsection(), NumImportAndDeclEntries(), SkipToGlobalEntries(), and SkipToProtoConfigs().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-decoder-impl.h