v8::internal::wasm::DescriptorsSectionIterator::Entry Class Reference
#include <module-decoder-impl.h>
Public Member Functions
bool ok ()
bool has_export () const
bool has_method () const
bool has_constructor () const
bool has_static () const
uint32_t NextExport (uint32_t max_index)
Method NextMethod (uint32_t max_index)
std::pair< WireBytesRef, uint32_t > Constructor (uint32_t max_index)
Method NextStatic (uint32_t max_index)
uint32_t estimated_number_of_methods () const
uint32_t estimated_number_of_statics () const
Protected Types
enum class State {
kParentOrImport
, kExports
, kMethods
, kConstructor
,
kStatics
, kFinished
 }
Protected Member Functions
Entry (DescriptorsSectionIterator *decoder)
Method NextMethodImpl (uint32_t max_index, bool is_static)
void CheckIndex (const uint8_t *pos, uint32_t index, uint32_t max)
void ProceedToExports ()
void ProceedToMethods ()
void ProceedToConstructor ()
void ProceedToStatics ()
WireBytesRef consume_string (const char *description)
uint32_t consume_u32v (const char *description)
DescriptorsSectionIterator * decoder () const
State state () const
uint32_t num_nested () const
Private Member Functions
void Finish ()
Private Attributes
DescriptorsSectionIterator * decoder_
State state_ {State::kParentOrImport}
uint32_t num_nested_ {0}
uint32_t nested_index_ {0}
Detailed Description
Definition at line 2957 of file module-decoder-impl.h.
Member Enumeration Documentation
State
enum v8::internal::wasm::DescriptorsSectionIterator::Entry::State [strong], [protected]
Enumerator
kParentOrImport
kExports
kMethods
kConstructor
kStatics
kFinished
Definition at line 3018 of file module-decoder-impl.h.
                     {
      kParentOrImport, // Whatever the first thing is.
      kExports,
      kMethods,
      kConstructor,
      kStatics,
      kFinished,
    };
Constructor & Destructor Documentation
Entry()
v8::internal::wasm::DescriptorsSectionIterator::Entry::Entry (DescriptorsSectionIterator * decoder) [inline], [explicit], [protected]
Definition at line 3027 of file module-decoder-impl.h.
: decoder_(decoder) {}
Member Function Documentation
CheckIndex()
void v8::internal::wasm::DescriptorsSectionIterator::Entry::CheckIndex (const uint8_t * pos, uint32_t index, uint32_t max) [inline], [protected]
Definition at line 3047 of file module-decoder-impl.h.
                                                                      {
      if (V8_LIKELY(index < max)) return;
      using DS = DescriptorsSectionIterator::State;
      DS parent_state = decoder_->state_;
      bool is_export_index = parent_state == DS::kInProtoConfig;
      const char* index_kind = is_export_index ? "export" : "function";
      decoder_->errorf(pos, "%s index %u out of range", index_kind, index);
    }
References decoder_, v8::internal::wasm::Decoder::errorf(), v8::internal::index, v8::internal::wasm::DescriptorsSectionIterator::state_, and V8_LIKELY.
Referenced by Constructor(), and NextMethodImpl().
Constructor()
std::pair<WireBytesRef, uint32_t> v8::internal::wasm::DescriptorsSectionIterator::Entry::Constructor (uint32_t max_index) [inline]
Definition at line 2988 of file module-decoder-impl.h.
                                                                    {
      DCHECK(has_constructor());
      WireBytesRef name = decoder_->consume_string("name");
      if (!ok()) return {};
      const uint8_t* pos = decoder_->pc();
      uint32_t index = decoder_->consume_u32v("index");
      CheckIndex(pos, index, max_index);
      ProceedToStatics();
      return {name, index};
    }
References CheckIndex(), v8::internal::wasm::DescriptorsSectionIterator::consume_string(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::DCHECK(), decoder_, has_constructor(), v8::internal::index, v8::internal::wasm::name(), ok(), v8::internal::wasm::Decoder::pc(), and ProceedToStatics().
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), and v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl().
consume_string()
WireBytesRef v8::internal::wasm::DescriptorsSectionIterator::Entry::consume_string (const char * description) [inline], [protected]
Definition at line 3091 of file module-decoder-impl.h.
                                                         {
      return decoder_->consume_string(description);
    }
References v8::internal::wasm::DescriptorsSectionIterator::consume_string(), and decoder_.
Referenced by v8::internal::wasm::DescriptorsSectionIterator::ImportEntry::name().
consume_u32v()
uint32_t v8::internal::wasm::DescriptorsSectionIterator::Entry::consume_u32v (const char * description) [inline], [protected]
Definition at line 3094 of file module-decoder-impl.h.
                                                   {
      return decoder_->consume_u32v(description);
    }
References v8::internal::wasm::Decoder::consume_u32v(), and decoder_.
Referenced by v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::DeclEntry(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::GlobalEntry(), NextExport(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::Parent(), v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::Parent(), ProceedToConstructor(), ProceedToExports(), ProceedToMethods(), ProceedToStatics(), and v8::internal::wasm::DescriptorsSectionIterator::ProtoConfig::ProtoConfig().
decoder()
DescriptorsSectionIterator* v8::internal::wasm::DescriptorsSectionIterator::Entry::decoder () const [inline], [protected]
Definition at line 3097 of file module-decoder-impl.h.
{ return decoder_; }
References decoder_.
Referenced by v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::DeclEntry(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::GlobalEntry(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::Parent(), v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::Parent(), and v8::internal::wasm::DescriptorsSectionIterator::ProtoConfig::ProtoConfig().
estimated_number_of_methods()
uint32_t v8::internal::wasm::DescriptorsSectionIterator::Entry::estimated_number_of_methods () const [inline]
Definition at line 3008 of file module-decoder-impl.h.
                                                 {
      DCHECK(has_method());
      return num_nested();
    }
References v8::internal::DCHECK(), has_method(), and num_nested().
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), and v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl().
estimated_number_of_statics()
uint32_t v8::internal::wasm::DescriptorsSectionIterator::Entry::estimated_number_of_statics () const [inline]
Definition at line 3012 of file module-decoder-impl.h.
                                                 {
      DCHECK(has_static());
      return num_nested();
    }
References v8::internal::DCHECK(), has_static(), and num_nested().
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), and v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl().
Finish()
void v8::internal::wasm::DescriptorsSectionIterator::Entry::Finish () [inline], [private]
Definition at line 3102 of file module-decoder-impl.h.
                  {
      state_ = State::kFinished;
      decoder_->FinishEntry();
    }
References decoder_, v8::internal::wasm::DescriptorsSectionIterator::FinishEntry(), kFinished, and state_.
Referenced by NextExport(), NextStatic(), ProceedToConstructor(), ProceedToExports(), and ProceedToStatics().
has_constructor()
bool v8::internal::wasm::DescriptorsSectionIterator::Entry::has_constructor () const [inline]
Definition at line 2963 of file module-decoder-impl.h.
{ return state_ == State::kConstructor; }
References kConstructor, and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl(), Constructor(), and ProceedToConstructor().
has_export()
bool v8::internal::wasm::DescriptorsSectionIterator::Entry::has_export () const [inline]
Definition at line 2961 of file module-decoder-impl.h.
{ return state_ == State::kExports; }
References kExports, and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl(), and NextExport().
has_method()
bool v8::internal::wasm::DescriptorsSectionIterator::Entry::has_method () const [inline]
Definition at line 2962 of file module-decoder-impl.h.
{ return state_ == State::kMethods; }
References kMethods, and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl(), estimated_number_of_methods(), and NextMethod().
has_static()
bool v8::internal::wasm::DescriptorsSectionIterator::Entry::has_static () const [inline]
Definition at line 2964 of file module-decoder-impl.h.
{ return state_ == State::kStatics; }
References kStatics, and state_.
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl(), estimated_number_of_statics(), and NextStatic().
NextExport()
uint32_t v8::internal::wasm::DescriptorsSectionIterator::Entry::NextExport (uint32_t max_index) [inline]
Definition at line 2966 of file module-decoder-impl.h.
                                            {
      DCHECK(has_export());
      const uint8_t* pos = decoder_->pc();
      uint32_t exp = consume_u32v("export index");
      if (!ok()) return exp;
      if (exp >= max_index) {
        decoder_->errorf(pos, "import index %u is out of range", exp);
        return exp;
      }
      nested_index_++;
      DCHECK_LE(nested_index_, num_nested_);
      if (nested_index_ == num_nested_) Finish();
      return exp;
    }
References consume_u32v(), v8::internal::DCHECK(), DCHECK_LE, decoder_, v8::internal::wasm::Decoder::errorf(), v8::base::ieee754::exp(), Finish(), has_export(), nested_index_, num_nested_, ok(), and v8::internal::wasm::Decoder::pc().
Referenced by v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl().
NextMethod()
Method v8::internal::wasm::DescriptorsSectionIterator::Entry::NextMethod (uint32_t max_index) [inline]
Definition at line 2981 of file module-decoder-impl.h.
                                          {
      DCHECK(has_method());
      Method method = NextMethodImpl(max_index, false);
      if (nested_index_ == num_nested_) ProceedToConstructor();
      return method;
    }
References v8::internal::DCHECK(), has_method(), nested_index_, NextMethodImpl(), num_nested_, and ProceedToConstructor().
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), and v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl().
NextMethodImpl()
Method v8::internal::wasm::DescriptorsSectionIterator::Entry::NextMethodImpl (uint32_t max_index, bool is_static) [inline], [protected]
Definition at line 3029 of file module-decoder-impl.h.
                                                              {
      const uint8_t* pos = decoder_->pc();
      uint8_t kind = decoder_->consume_u8("kind");
      if (kind > 2) {
        decoder_->errorf(pos, "invalid method kind %u", kind);
        return {};
      }
      if (!ok()) return {};
      WireBytesRef name = decoder_->consume_string("name");
      if (!ok()) return {};
      pos = decoder_->pc();
      uint32_t index = decoder_->consume_u32v("index");
      CheckIndex(pos, index, max_index);
      nested_index_++;
      DCHECK_LE(nested_index_, num_nested_);
      return {static_cast<Method::Kind>(kind), is_static, name, index};
    }
References CheckIndex(), v8::internal::wasm::DescriptorsSectionIterator::consume_string(), v8::internal::wasm::Decoder::consume_u32v(), v8::internal::wasm::Decoder::consume_u8(), DCHECK_LE, decoder_, v8::internal::wasm::Decoder::errorf(), v8::internal::index, v8::internal::wasm::name(), nested_index_, num_nested_, ok(), and v8::internal::wasm::Decoder::pc().
Referenced by NextMethod(), and NextStatic().
NextStatic()
Method v8::internal::wasm::DescriptorsSectionIterator::Entry::NextStatic (uint32_t max_index) [inline]
Definition at line 2999 of file module-decoder-impl.h.
                                          {
      DCHECK(has_static());
      Method static_method = NextMethodImpl(max_index, true);
      if (nested_index_ == num_nested_) Finish();
      return static_method;
    }
References v8::internal::DCHECK(), Finish(), has_static(), nested_index_, NextMethodImpl(), and num_nested_.
Referenced by v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Direct_Impl(), and v8::internal::wasm::JSPrototypesSetup::ConfigurePrototypes_Modular_Impl().
num_nested()
uint32_t v8::internal::wasm::DescriptorsSectionIterator::Entry::num_nested () const [inline], [protected]
Definition at line 3099 of file module-decoder-impl.h.
{ return num_nested_; }
References num_nested_.
Referenced by estimated_number_of_methods(), and estimated_number_of_statics().
ok()
bool v8::internal::wasm::DescriptorsSectionIterator::Entry::ok () [inline]
Definition at line 2959 of file module-decoder-impl.h.
{ return decoder_->ok(); }
References decoder_, and v8::internal::wasm::Decoder::ok().
Referenced by Constructor(), v8::internal::wasm::JSPrototypesSetup::MaterializeDescriptorOptionsImpl(), NextExport(), NextMethodImpl(), ProceedToConstructor(), ProceedToExports(), ProceedToMethods(), and ProceedToStatics().
ProceedToConstructor()
void v8::internal::wasm::DescriptorsSectionIterator::Entry::ProceedToConstructor () [inline], [protected]
Definition at line 3072 of file module-decoder-impl.h.
                                {
      if (!ok()) return;
      state_ = State::kConstructor;
      const uint8_t* pos = decoder_->pc();
      uint32_t has_constructor = consume_u32v("constructor");
      if (has_constructor == 0) return Finish();
      if (has_constructor > 1) {
        decoder_->error(pos, "at most one constructor allowed");
      }
    }
References consume_u32v(), decoder_, v8::internal::wasm::Decoder::error(), Finish(), has_constructor(), kConstructor, ok(), v8::internal::wasm::Decoder::pc(), and state_.
Referenced by NextMethod(), and ProceedToMethods().
ProceedToExports()
void v8::internal::wasm::DescriptorsSectionIterator::Entry::ProceedToExports () [inline], [protected]
Definition at line 3056 of file module-decoder-impl.h.
                            {
      if (!ok()) return;
      state_ = State::kExports;
      num_nested_ = consume_u32v("number of exports");
      nested_index_ = 0;
      if (num_nested_ == 0) Finish();
    }
References consume_u32v(), Finish(), kExports, nested_index_, num_nested_, ok(), and state_.
Referenced by v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::DeclEntry(), v8::internal::wasm::DescriptorsSectionIterator::ImportEntry::name(), and v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::Parent().
ProceedToMethods()
void v8::internal::wasm::DescriptorsSectionIterator::Entry::ProceedToMethods () [inline], [protected]
Definition at line 3064 of file module-decoder-impl.h.
                            {
      if (!ok()) return;
      state_ = State::kMethods;
      num_nested_ = consume_u32v("number of methods");
      nested_index_ = 0;
      if (num_nested_ == 0) ProceedToConstructor();
    }
References consume_u32v(), kMethods, nested_index_, num_nested_, ok(), ProceedToConstructor(), and state_.
Referenced by v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::GlobalEntry(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::Parent(), and v8::internal::wasm::DescriptorsSectionIterator::ProtoConfig::ProtoConfig().
ProceedToStatics()
void v8::internal::wasm::DescriptorsSectionIterator::Entry::ProceedToStatics () [inline], [protected]
Definition at line 3083 of file module-decoder-impl.h.
                            {
      if (!ok()) return;
      state_ = State::kStatics;
      num_nested_ = consume_u32v("number of statics");
      nested_index_ = 0;
      if (num_nested_ == 0) Finish();
    }
References consume_u32v(), Finish(), kStatics, nested_index_, num_nested_, ok(), and state_.
Referenced by Constructor().
state()
State v8::internal::wasm::DescriptorsSectionIterator::Entry::state () const [inline], [protected]
Definition at line 3098 of file module-decoder-impl.h.
{ return state_; }
References state_.
Referenced by v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::has_parent(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::has_parent(), v8::internal::wasm::DescriptorsSectionIterator::ImportEntry::name(), v8::internal::wasm::DescriptorsSectionIterator::GlobalEntry::Parent(), and v8::internal::wasm::DescriptorsSectionIterator::DeclEntry::Parent().
Member Data Documentation
decoder_
DescriptorsSectionIterator* v8::internal::wasm::DescriptorsSectionIterator::Entry::decoder_ [private]
Definition at line 3107 of file module-decoder-impl.h.
Referenced by CheckIndex(), Constructor(), consume_string(), consume_u32v(), decoder(), Finish(), NextExport(), NextMethodImpl(), ok(), and ProceedToConstructor().
nested_index_
uint32_t v8::internal::wasm::DescriptorsSectionIterator::Entry::nested_index_ {0} [private]
Definition at line 3110 of file module-decoder-impl.h.
Referenced by NextExport(), NextMethod(), NextMethodImpl(), NextStatic(), ProceedToExports(), ProceedToMethods(), and ProceedToStatics().
num_nested_
uint32_t v8::internal::wasm::DescriptorsSectionIterator::Entry::num_nested_ {0} [private]
Definition at line 3109 of file module-decoder-impl.h.
Referenced by NextExport(), NextMethod(), NextMethodImpl(), NextStatic(), num_nested(), ProceedToExports(), ProceedToMethods(), and ProceedToStatics().
state_
State v8::internal::wasm::DescriptorsSectionIterator::Entry::state_ {State::kParentOrImport} [private]
Definition at line 3108 of file module-decoder-impl.h.
Referenced by Finish(), has_constructor(), has_export(), has_method(), has_static(), ProceedToConstructor(), ProceedToExports(), ProceedToMethods(), ProceedToStatics(), and state().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/wasm/module-decoder-impl.h