cppgc::testing::StandaloneTestingHeap Class Reference
Testing interface for managed heaps that allows for controlling garbage collection timings.
#include <testing.h>
Public Member Functions
StandaloneTestingHeap (HeapHandle &)
void StartGarbageCollection ()
Start an incremental garbage collection.
bool PerformMarkingStep (EmbedderStackState stack_state)
Perform an incremental step.
void FinalizeGarbageCollection (EmbedderStackState stack_state)
Finalize the current garbage collection cycle atomically.
void ToggleMainThreadMarking (bool should_mark)
Toggle main thread marking on/off.
void ForceCompactionForNextGarbageCollection ()
Force enable compaction for the next garbage collection cycle.
Private Attributes
HeapHandle & heap_handle_
Detailed Description
Testing interface for managed heaps that allows for controlling garbage collection timings.
Embedders should use this class when testing the interaction of their code with incremental/concurrent garbage collection.
Definition at line 57 of file testing.h.
Constructor & Destructor Documentation
StandaloneTestingHeap()
cppgc::testing::StandaloneTestingHeap::StandaloneTestingHeap (HeapHandle & heap_handle) [explicit]
Definition at line 23 of file testing.cc.
    : heap_handle_(heap_handle) {}
Member Function Documentation
FinalizeGarbageCollection()
void cppgc::testing::StandaloneTestingHeap::FinalizeGarbageCollection (EmbedderStackState stack_state)
Finalize the current garbage collection cycle atomically.
Assumes that garbage collection is in progress.
Parameters
stack_state The state of the stack for finalizing the garbage collection cycle.
Definition at line 37 of file testing.cc.
                                    {
  internal::HeapBase::From(heap_handle_)
      .FinalizeIncrementalGarbageCollectionForTesting(stack_state);
}
References cppgc::internal::HeapBase::FinalizeIncrementalGarbageCollectionForTesting(), cppgc::internal::HeapBase::From(), and heap_handle_.
ForceCompactionForNextGarbageCollection()
void cppgc::testing::StandaloneTestingHeap::ForceCompactionForNextGarbageCollection ()
Force enable compaction for the next garbage collection cycle.
Definition at line 49 of file testing.cc.
                                                                    {
  internal::HeapBase::From(heap_handle_)
      .compactor()
      .EnableForNextGCForTesting();
}
References cppgc::internal::HeapBase::compactor(), cppgc::internal::Compactor::EnableForNextGCForTesting(), cppgc::internal::HeapBase::From(), and heap_handle_.
PerformMarkingStep()
bool cppgc::testing::StandaloneTestingHeap::PerformMarkingStep (EmbedderStackState stack_state)
Perform an incremental step.
This will also schedule concurrent steps if needed.
Parameters
stack_state The state of the stack during the step.
Definition at line 31 of file testing.cc.
                                                                             {
  return internal::HeapBase::From(heap_handle_)
      .marker()
      ->IncrementalMarkingStepForTesting(stack_state);
}
References cppgc::internal::HeapBase::From(), heap_handle_, cppgc::internal::MarkerBase::IncrementalMarkingStepForTesting(), and cppgc::internal::HeapBase::marker().
StartGarbageCollection()
void cppgc::testing::StandaloneTestingHeap::StartGarbageCollection ()
Start an incremental garbage collection.
Definition at line 26 of file testing.cc.
                                                   {
  internal::HeapBase::From(heap_handle_)
      .StartIncrementalGarbageCollectionForTesting();
}
References cppgc::internal::HeapBase::From(), heap_handle_, and cppgc::internal::HeapBase::StartIncrementalGarbageCollectionForTesting().
ToggleMainThreadMarking()
void cppgc::testing::StandaloneTestingHeap::ToggleMainThreadMarking (bool should_mark)
Toggle main thread marking on/off.
Allows to stress concurrent marking (e.g. to better detect data races).
Parameters
should_mark Denotes whether the main thread should contribute to marking. Defaults to true.
Definition at line 43 of file testing.cc.
                                                                    {
  internal::HeapBase::From(heap_handle_)
      .marker()
      ->SetMainThreadMarkingDisabledForTesting(!should_mark);
}
References cppgc::internal::HeapBase::From(), heap_handle_, cppgc::internal::HeapBase::marker(), and cppgc::internal::MarkerBase::SetMainThreadMarkingDisabledForTesting().
Member Data Documentation
heap_handle_
HeapHandle& cppgc::testing::StandaloneTestingHeap::heap_handle_ [private]
Definition at line 98 of file testing.h.
Referenced by FinalizeGarbageCollection(), ForceCompactionForNextGarbageCollection(), PerformMarkingStep(), StartGarbageCollection(), and ToggleMainThreadMarking().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/cppgc/testing.h
/mnt/V8SourceCode/src/heap/cppgc/testing.cc