v8_inspector::InjectedScript::CallFrameScope Class Reference
#include <injected-script.h>
Public Member Functions
CallFrameScope (V8InspectorSessionImpl *, const String16 &remoteCallFrameId)
~CallFrameScope () override
CallFrameScope (const CallFrameScope &)=delete
CallFrameScope & operator= (const CallFrameScope &)=delete
size_t frameOrdinal () const
Private Member Functions
Response findInjectedScript (V8InspectorSessionImpl *) override
Private Attributes
String16 m_remoteCallFrameId
size_t m_frameOrdinal
Additional Inherited Members
Detailed Description
Definition at line 219 of file injected-script.h.
Constructor & Destructor Documentation
CallFrameScope() [1/2]
v8_inspector::InjectedScript::CallFrameScope::CallFrameScope (V8InspectorSessionImpl * session, const String16 & remoteCallFrameId)
Definition at line 1127 of file injected-script.cc.
    : InjectedScript::Scope(session), m_remoteCallFrameId(remoteObjectId) {}
 CallFrameScope()
v8_inspector::InjectedScript::CallFrameScope::~CallFrameScope () [override], [default]
CallFrameScope() [2/2]
v8_inspector::InjectedScript::CallFrameScope::CallFrameScope (const CallFrameScope &) [delete]
Member Function Documentation
findInjectedScript()
Response v8_inspector::InjectedScript::CallFrameScope::findInjectedScript (V8InspectorSessionImpl * session) [override], [private], [virtual]
Implements v8_inspector::InjectedScript::Scope.
Definition at line 1133 of file injected-script.cc.
                                     {
  std::unique_ptr<RemoteCallFrameId> remoteId;
  Response response = RemoteCallFrameId::parse(m_remoteCallFrameId, &remoteId);
  if (!response.IsSuccess()) return response;
  m_frameOrdinal = static_cast<size_t>(remoteId->frameOrdinal());
  return session->findInjectedScript(remoteId.get(), m_injectedScript);
}
References v8_inspector::V8InspectorSessionImpl::findInjectedScript(), and v8_inspector::RemoteCallFrameId::parse().
frameOrdinal()
size_t v8_inspector::InjectedScript::CallFrameScope::frameOrdinal () const [inline]
Definition at line 225 of file injected-script.h.
{ return m_frameOrdinal; }
References m_frameOrdinal.
Referenced by v8_inspector::V8DebuggerAgentImpl::evaluateOnCallFrame(), v8_inspector::V8DebuggerAgentImpl::restartFrame(), and v8_inspector::V8DebuggerAgentImpl::setVariableValue().
operator=()
CallFrameScope& v8_inspector::InjectedScript::CallFrameScope::operator= (const CallFrameScope &) [delete]
Member Data Documentation
m_frameOrdinal
size_t v8_inspector::InjectedScript::CallFrameScope::m_frameOrdinal [private]
Definition at line 230 of file injected-script.h.
Referenced by frameOrdinal().
m_remoteCallFrameId
String16 v8_inspector::InjectedScript::CallFrameScope::m_remoteCallFrameId [private]
Definition at line 229 of file injected-script.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/inspector/injected-script.h
/mnt/V8SourceCode/src/inspector/injected-script.cc