v8::internal::RegExpBytecodePeepholeOptimization Class Reference
#include <regexp-bytecode-peephole.h>
Static Public Member Functions
static DirectHandle< TrustedByteArray > OptimizeBytecode (Isolate *isolate, Zone *zone, DirectHandle< String > source, const uint8_t *bytecode, int length, const ZoneUnorderedMap< int, int > &jump_edges)
Detailed Description
Definition at line 19 of file regexp-bytecode-peephole.h.
Member Function Documentation
OptimizeBytecode()
DirectHandle< TrustedByteArray > v8::internal::RegExpBytecodePeepholeOptimization::OptimizeBytecode (Isolate * isolate, Zone * zone, DirectHandle< String > source, const uint8_t * bytecode, int length, const ZoneUnorderedMap< int, int > & jump_edges) [static]
Definition at line 1015 of file regexp-bytecode-peephole.cc.
                                                  {
  RegExpBytecodePeephole peephole(zone, length, jump_edges);
  bool did_optimize = peephole.OptimizeBytecode(bytecode, length);
  DirectHandle<TrustedByteArray> array =
      isolate->factory()->NewTrustedByteArray(peephole.Length());
  peephole.CopyOptimizedBytecode(array->begin());
  if (did_optimize && v8_flags.trace_regexp_peephole_optimization) {
    PrintF("Original Bytecode:\n");
    RegExpBytecodeDisassemble(bytecode, length, source->ToCString().get());
    PrintF("Optimized Bytecode:\n");
    RegExpBytecodeDisassemble(array->begin(), peephole.Length(),
                              source->ToCString().get());
  }
  return array;
}
References v8::internal::Isolate::factory(), v8::internal::length, v8::internal::FactoryBase< Impl >::NewTrustedByteArray(), v8::internal::PrintF(), v8::internal::RegExpBytecodeDisassemble(), and v8::internal::v8_flags.
Referenced by v8::internal::RegExpBytecodeGenerator::GetCode().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-bytecode-peephole.h
/mnt/V8SourceCode/src/regexp/regexp-bytecode-peephole.cc