cppgc::internal::Sweeper Class Reference
#include <sweeper.h>
Classes
class SweeperImpl
class SweepingOnMutatorThreadObserver
Public Member Functions
Sweeper (HeapBase &)
~Sweeper ()
Sweeper (const Sweeper &)=delete
Sweeper & operator= (const Sweeper &)=delete
void Start (SweepingConfig)
bool FinishIfRunning ()
void FinishIfOutOfWork ()
bool SweepForAllocationIfRunning (BaseSpace *space, size_t min_wanted_size, v8::base::TimeDelta max_duration)
bool IsSweepingOnMutatorThread () const
bool IsSweepingInProgress () const
bool PerformSweepOnMutatorThread (v8::base::TimeDelta max_duration, StatsCollector::ScopeId)
Static Public Member Functions
static constexpr bool CanDiscardMemory ()
Private Member Functions
void WaitForConcurrentSweepingForTesting ()
Private Attributes
HeapBase & heap_
std::unique_ptr< SweeperImpl > impl_
Friends
class ConcurrentSweeperTest
Detailed Description
Definition at line 22 of file sweeper.h.
Constructor & Destructor Documentation
Sweeper() [1/2]
cppgc::internal::Sweeper::Sweeper (HeapBase & heap) [explicit]
Definition at line 1656 of file sweeper.cc.
    : heap_(heap), impl_(std::make_unique<SweeperImpl>(heap)) {}
 Sweeper()
cppgc::internal::Sweeper::~Sweeper () [default]
Sweeper() [2/2]
cppgc::internal::Sweeper::Sweeper (const Sweeper &) [delete]
Member Function Documentation
CanDiscardMemory()
static constexpr bool cppgc::internal::Sweeper::CanDiscardMemory () [inline], [static], [constexpr]
Definition at line 36 of file sweeper.h.
                                           {
#if defined(V8_OS_WIN)
    // Discarding memory on Windows does not decommit the memory and does not
    // contribute to reduce the memory footprint. On the other hand, these
    // calls become expensive the more memory is allocated in the system and
    // can result in hangs. Thus, it is better to not discard on Windows.
    return false;
#else
    return CheckMemoryIsInaccessibleIsNoop();
#endif
  }
References cppgc::internal::CheckMemoryIsInaccessibleIsNoop().
Referenced by cppgc::internal::Sweeper::SweeperImpl::Start().
FinishIfOutOfWork()
void cppgc::internal::Sweeper::FinishIfOutOfWork ()
Definition at line 1665 of file sweeper.cc.
{ impl_->FinishIfOutOfWork(); }
References impl_.
Referenced by v8::internal::CppHeap::FinishSweepingIfOutOfWork().
FinishIfRunning()
bool cppgc::internal::Sweeper::FinishIfRunning ()
Definition at line 1663 of file sweeper.cc.
{ return impl_->FinishIfRunning(); }
References impl_.
Referenced by v8::internal::CppHeap::CollectGarbageForTesting(), cppgc::internal::HeapBase::CollectStatistics(), cppgc::internal::Heap::FinalizeGarbageCollectionImpl(), v8::internal::CppHeap::FinalizeIncrementalGarbageCollectionForTesting(), cppgc::internal::Heap::FinalizeIncrementalGarbageCollectionForTesting(), v8::internal::CppHeap::FinishSweepingIfRunning(), v8::internal::CppHeap::StartDetachingIsolate(), cppgc::internal::Heap::StartGarbageCollection(), cppgc::internal::HeapBase::Terminate(), cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObjectImpl(), cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBuffer(), and cppgc::internal::Heap::~Heap().
IsSweepingInProgress()
bool cppgc::internal::Sweeper::IsSweepingInProgress () const
Definition at line 1680 of file sweeper.cc.
                                         {
  return impl_->IsSweepingInProgress();
}
References impl_.
Referenced by v8::internal::CppHeap::CollectGarbage(), v8::internal::CppHeap::FinishAtomicSweepingIfRunning(), v8::internal::CppHeap::InitializeMarking(), cppgc::subtle::HeapState::IsSweeping(), and v8::internal::anonymous_namespace{cpp-heap.cc}::CollectCustomSpaceStatisticsAtLastGCTask::Run().
IsSweepingOnMutatorThread()
bool cppgc::internal::Sweeper::IsSweepingOnMutatorThread () const
Definition at line 1676 of file sweeper.cc.
                                              {
  return impl_->IsSweepingOnMutatorThread();
}
References impl_.
Referenced by cppgc::internal::HeapBase::IsGCAllowed(), and cppgc::subtle::HeapState::IsSweepingOnOwningThread().
operator=()
Sweeper& cppgc::internal::Sweeper::operator= (const Sweeper &) [delete]
PerformSweepOnMutatorThread()
bool cppgc::internal::Sweeper::PerformSweepOnMutatorThread (v8::base::TimeDelta max_duration, StatsCollector::ScopeId scope_id)
Definition at line 1684 of file sweeper.cc.
                                                                          {
  return impl_->PerformSweepOnMutatorThread(max_duration, scope_id,
                                            MutatorThreadSweepingMode::kAll);
}
References impl_.
Referenced by v8::internal::anonymous_namespace{cpp-heap.cc}::CollectCustomSpaceStatisticsAtLastGCTask::Run().
Start()
void cppgc::internal::Sweeper::Start (SweepingConfig config)
Definition at line 1661 of file sweeper.cc.
{ impl_->Start(config); }
References impl_.
Referenced by v8::internal::CppHeap::CompactAndSweep(), cppgc::internal::Heap::FinalizeGarbageCollectionImpl(), and cppgc::internal::HeapBase::Terminate().
SweepForAllocationIfRunning()
bool cppgc::internal::Sweeper::SweepForAllocationIfRunning (BaseSpace * space, size_t min_wanted_size, v8::base::TimeDelta max_duration)
Definition at line 1671 of file sweeper.cc.
                                                                        {
  return impl_->SweepForAllocationIfRunning(space, size, max_duration);
}
References impl_, size(), and space.
Referenced by cppgc::internal::anonymous_namespace{object-allocator.cc}::TryAllocateLargeObjectImpl(), and cppgc::internal::ObjectAllocator::TryRefillLinearAllocationBuffer().
WaitForConcurrentSweepingForTesting()
void cppgc::internal::Sweeper::WaitForConcurrentSweepingForTesting () [private]
Definition at line 1667 of file sweeper.cc.
                                                  {
  impl_->WaitForConcurrentSweepingForTesting();
}
References impl_.
Friends And Related Function Documentation
ConcurrentSweeperTest
friend class ConcurrentSweeperTest [friend]
Definition at line 84 of file sweeper.h.
Member Data Documentation
heap_
HeapBase& cppgc::internal::Sweeper::heap_ [private]
Definition at line 81 of file sweeper.h.
impl_
std::unique_ptr<SweeperImpl> cppgc::internal::Sweeper::impl_ [private]
Definition at line 82 of file sweeper.h.
Referenced by FinishIfOutOfWork(), FinishIfRunning(), IsSweepingInProgress(), IsSweepingOnMutatorThread(), PerformSweepOnMutatorThread(), Start(), SweepForAllocationIfRunning(), cppgc::internal::Sweeper::SweepingOnMutatorThreadObserver::SweepingOnMutatorThreadObserver(), and WaitForConcurrentSweepingForTesting().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/sweeper.h
/mnt/V8SourceCode/src/heap/cppgc/sweeper.cc