v8::internal::ValueSerializer Class Reference
Writes V8 objects in a binary format that allows the objects to be cloned according to the HTML structured clone algorithm.
#include <value-serializer.h>
Public Member Functions
ValueSerializer (Isolate *isolate, v8::ValueSerializer::Delegate *delegate)
~ValueSerializer ()
ValueSerializer (const ValueSerializer &)=delete
ValueSerializer & operator= (const ValueSerializer &)=delete
void WriteHeader ()
Maybe< bool > WriteObject (DirectHandle< Object > object) V8_WARN_UNUSED_RESULT
std::pair< uint8_t *, size_t > Release ()
void TransferArrayBuffer (uint32_t transfer_id, DirectHandle< JSArrayBuffer > array_buffer)
void WriteUint32 (uint32_t value)
void WriteUint64 (uint64_t value)
void WriteRawBytes (const void *source, size_t length)
void WriteDouble (double value)
void WriteByte (uint8_t value)
void SetTreatArrayBufferViewsAsHostObjects (bool mode)
Private Member Functions
Maybe< bool > ExpandBuffer (size_t required_capacity)
void WriteTag (SerializationTag tag)
template<typename T >
void WriteVarint (T value)
template<typename T >
void WriteZigZag (T value)
void WriteOneByteString (base::Vector< const uint8_t > chars)
void WriteTwoByteString (base::Vector< const base::uc16 > chars)
void WriteBigIntContents (Tagged< BigInt > bigint)
Maybe< uint8_t * > ReserveRawBytes (size_t bytes)
void WriteOddball (Tagged< Oddball > oddball)
void WriteSmi (Tagged< Smi > smi)
void WriteHeapNumber (Tagged< HeapNumber > number)
void WriteBigInt (Tagged< BigInt > bigint)
void WriteString (DirectHandle< String > string)
Maybe< bool > WriteJSReceiver (DirectHandle< JSReceiver > receiver) V8_WARN_UNUSED_RESULT
Maybe< bool > WriteJSObject (DirectHandle< JSObject > object) V8_WARN_UNUSED_RESULT
Maybe< bool > WriteJSObjectSlow (DirectHandle< JSObject > object) V8_WARN_UNUSED_RESULT
Maybe< bool > WriteJSArray (DirectHandle< JSArray > array) V8_WARN_UNUSED_RESULT
void WriteJSDate (Tagged< JSDate > date)
Maybe< bool > WriteJSPrimitiveWrapper (DirectHandle< JSPrimitiveWrapper > value) V8_WARN_UNUSED_RESULT
void WriteJSRegExp (DirectHandle< JSRegExp > regexp)
Maybe< bool > WriteJSMap (DirectHandle< JSMap > map) V8_WARN_UNUSED_RESULT
Maybe< bool > WriteJSSet (DirectHandle< JSSet > map) V8_WARN_UNUSED_RESULT
Maybe< bool > WriteJSArrayBuffer (DirectHandle< JSArrayBuffer > array_buffer) V8_WARN_UNUSED_RESULT
Maybe< bool > WriteJSArrayBufferView (Tagged< JSArrayBufferView > array_buffer)
Maybe< bool > WriteJSError (DirectHandle< JSObject > error) V8_WARN_UNUSED_RESULT
Maybe< bool > WriteJSSharedArray (DirectHandle< JSSharedArray > shared_array) V8_WARN_UNUSED_RESULT
Maybe< bool > WriteJSSharedStruct (DirectHandle< JSSharedStruct > shared_struct) V8_WARN_UNUSED_RESULT
Maybe< bool > WriteSharedObject (DirectHandle< HeapObject > object) V8_WARN_UNUSED_RESULT
Maybe< bool > WriteHostObject (DirectHandle< JSObject > object) V8_WARN_UNUSED_RESULT
Maybe< uint32_t > WriteJSObjectPropertiesSlow (DirectHandle< JSObject > object, DirectHandle< FixedArray > keys) V8_WARN_UNUSED_RESULT
Maybe< bool > IsHostObject (DirectHandle< JSObject > object)
V8_NOINLINE Maybe< bool > ThrowDataCloneError (MessageTemplate template_index) V8_WARN_UNUSED_RESULT
V8_NOINLINE Maybe< bool > ThrowDataCloneError (MessageTemplate template_index, DirectHandle< Object > arg0) V8_WARN_UNUSED_RESULT
Maybe< bool > ThrowIfOutOfMemory ()
Private Attributes
Isolate *const isolate_
v8::ValueSerializer::Delegate *const delegate_
uint8_t * buffer_ = nullptr
size_t buffer_size_ = 0
size_t buffer_capacity_ = 0
bool has_custom_host_objects_ = false
bool treat_array_buffer_views_as_host_objects_ = false
bool out_of_memory_ = false
Zone zone_
IdentityMap< uint32_t, ZoneAllocationPolicy > id_map_
uint32_t next_id_ = 0
IdentityMap< uint32_t, ZoneAllocationPolicy > array_buffer_transfer_map_
SharedObjectConveyorHandles * shared_object_conveyor_ = nullptr
Detailed Description
Writes V8 objects in a binary format that allows the objects to be cloned according to the HTML structured clone algorithm.
Format is based on Blink's previous serialization logic.
Definition at line 50 of file value-serializer.h.
Constructor & Destructor Documentation
ValueSerializer() [1/2]
v8::internal::ValueSerializer::ValueSerializer (Isolate * isolate, v8::ValueSerializer::Delegate * delegate)
Definition at line 295 of file value-serializer.cc.
    : isolate_(isolate),
      delegate_(delegate),
      zone_(isolate->allocator(), ZONE_NAME),
      id_map_(isolate->heap(), ZoneAllocationPolicy(&zone_)),
      array_buffer_transfer_map_(isolate->heap(),
                                 ZoneAllocationPolicy(&zone_)) {
  if (delegate_) {
    v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate_);
    has_custom_host_objects_ = delegate_->HasCustomHostObject(v8_isolate);
  }
}
References delegate_, has_custom_host_objects_, v8::ValueSerializer::Delegate::HasCustomHostObject(), and isolate_.
 ValueSerializer()
v8::internal::ValueSerializer::~ValueSerializer ()
Definition at line 309 of file value-serializer.cc.
                                  {
  if (buffer_) {
    if (delegate_) {
      delegate_->FreeBufferMemory(buffer_);
    } else {
      base::Free(buffer_);
    }
  }
}
References buffer_, delegate_, v8::base::Free(), and v8::ValueSerializer::Delegate::FreeBufferMemory().
ValueSerializer() [2/2]
v8::internal::ValueSerializer::ValueSerializer (const ValueSerializer &) [delete]
Member Function Documentation
ExpandBuffer()
Maybe< bool > v8::internal::ValueSerializer::ExpandBuffer (size_t required_capacity) [private]
Definition at line 414 of file value-serializer.cc.
                                                                  {
  DCHECK_GT(required_capacity, buffer_capacity_);
  size_t requested_capacity =
      std::max(required_capacity, buffer_capacity_ * 2) + 64;
  size_t provided_capacity = 0;
  void* new_buffer = nullptr;
  if (delegate_) {
    new_buffer = delegate_->ReallocateBufferMemory(buffer_, requested_capacity,
                                                   &provided_capacity);
  } else {
    new_buffer = base::Realloc(buffer_, requested_capacity);
    provided_capacity = requested_capacity;
  }
  if (new_buffer) {
    DCHECK(provided_capacity >= requested_capacity);
    buffer_ = reinterpret_cast<uint8_t*>(new_buffer);
    buffer_capacity_ = provided_capacity;
    return Just(true);
  } else {
    out_of_memory_ = true;
    return Nothing<bool>();
  }
}
References buffer_, buffer_capacity_, v8::internal::DCHECK(), DCHECK_GT, delegate_, v8::Just(), out_of_memory_, v8::base::Realloc(), and v8::ValueSerializer::Delegate::ReallocateBufferMemory().
Referenced by ReserveRawBytes().
IsHostObject()
Maybe< bool > v8::internal::ValueSerializer::IsHostObject (DirectHandle< JSObject > object) [private]
Definition at line 1295 of file value-serializer.cc.
                                                                          {
  if (!has_custom_host_objects_) {
    return Just<bool>(
        JSObject::GetEmbedderFieldCount(js_object->map(isolate_)));
  }
  DCHECK_NOT_NULL(delegate_);
  v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate_);
  Maybe<bool> result =
      delegate_->IsHostObject(v8_isolate, Utils::ToLocal(js_object));
  RETURN_VALUE_IF_EXCEPTION(isolate_, Nothing<bool>());
  DCHECK(!result.IsNothing());
  if (V8_UNLIKELY(out_of_memory_)) return ThrowIfOutOfMemory();
  return result;
}
References v8::internal::DCHECK(), DCHECK_NOT_NULL, delegate_, v8::internal::JSObject::GetEmbedderFieldCount(), has_custom_host_objects_, v8::ValueSerializer::Delegate::IsHostObject(), isolate_, out_of_memory_, v8::base::internal::result, RETURN_VALUE_IF_EXCEPTION, ThrowIfOutOfMemory(), and V8_UNLIKELY.
Referenced by WriteJSReceiver().
operator=()
ValueSerializer& v8::internal::ValueSerializer::operator= (const ValueSerializer &) [delete]
Release()
std::pair< uint8_t *, size_t > v8::internal::ValueSerializer::Release ()
Definition at line 453 of file value-serializer.cc.
                                                   {
  auto result = std::make_pair(buffer_, buffer_size_);
  buffer_ = nullptr;
  buffer_size_ = 0;
  buffer_capacity_ = 0;
  return result;
}
References buffer_, buffer_capacity_, buffer_size_, and v8::base::internal::result.
Referenced by v8::ValueSerializer::Release().
ReserveRawBytes()
Maybe< uint8_t * > v8::internal::ValueSerializer::ReserveRawBytes (size_t bytes) [private]
Definition at line 401 of file value-serializer.cc.
                                                             {
  size_t old_size = buffer_size_;
  size_t new_size = old_size + bytes;
  if (V8_UNLIKELY(new_size > buffer_capacity_)) {
    bool ok;
    if (!ExpandBuffer(new_size).To(&ok)) {
      return Nothing<uint8_t*>();
    }
  }
  buffer_size_ = new_size;
  return Just(&buffer_[old_size]);
}
References buffer_, buffer_capacity_, buffer_size_, ExpandBuffer(), v8::Just(), and V8_UNLIKELY.
Referenced by WriteBigIntContents(), WriteByte(), and WriteRawBytes().
SetTreatArrayBufferViewsAsHostObjects()
void v8::internal::ValueSerializer::SetTreatArrayBufferViewsAsHostObjects (bool mode)
Definition at line 324 of file value-serializer.cc.
                                                                     {
  treat_array_buffer_views_as_host_objects_ = mode;
}
References mode(), and treat_array_buffer_views_as_host_objects_.
Referenced by v8::ValueSerializer::SetTreatArrayBufferViewsAsHostObjects().
ThrowDataCloneError() [1/2]
Maybe< bool > v8::internal::ValueSerializer::ThrowDataCloneError (MessageTemplate template_index) [private]
Definition at line 1319 of file value-serializer.cc.
                                    {
  return ThrowDataCloneError(template_index,
                             isolate_->factory()->empty_string());
}
References v8::internal::Isolate::factory(), and isolate_.
Referenced by ThrowIfOutOfMemory(), WriteJSArrayBuffer(), WriteJSArrayBufferView(), WriteJSPrimitiveWrapper(), WriteJSReceiver(), WriteObject(), and WriteSharedObject().
ThrowDataCloneError() [2/2]
Maybe< bool > v8::internal::ValueSerializer::ThrowDataCloneError (MessageTemplate template_index, DirectHandle< Object > arg0) [private]
Definition at line 1325 of file value-serializer.cc.
                                                                            {
  DirectHandle<String> message =
      MessageFormatter::Format(isolate_, index, base::VectorOf({arg0}));
  if (delegate_) {
    delegate_->ThrowDataCloneError(Utils::ToLocal(message));
  } else {
    isolate_->Throw(
        *isolate_->factory()->NewError(isolate_->error_function(), message));
  }
  return Nothing<bool>();
}
References delegate_, v8::internal::Isolate::factory(), v8::internal::MessageFormatter::Format(), v8::internal::index, isolate_, v8::internal::Factory::NewError(), v8::internal::Isolate::Throw(), v8::ValueSerializer::Delegate::ThrowDataCloneError(), and v8::base::VectorOf().
ThrowIfOutOfMemory()
Maybe< bool > v8::internal::ValueSerializer::ThrowIfOutOfMemory () [private]
Definition at line 1312 of file value-serializer.cc.
                                                {
  if (out_of_memory_) {
    return ThrowDataCloneError(MessageTemplate::kDataCloneErrorOutOfMemory);
  }
  return Just(true);
}
References v8::Just(), out_of_memory_, and ThrowDataCloneError().
Referenced by IsHostObject(), WriteHostObject(), WriteJSArray(), WriteJSArrayBuffer(), WriteJSArrayBufferView(), WriteJSError(), WriteJSMap(), WriteJSObject(), WriteJSObjectSlow(), WriteJSPrimitiveWrapper(), WriteJSReceiver(), WriteJSSet(), WriteObject(), and WriteSharedObject().
TransferArrayBuffer()
void v8::internal::ValueSerializer::TransferArrayBuffer (uint32_t transfer_id, DirectHandle< JSArrayBuffer > array_buffer)
Definition at line 461 of file value-serializer.cc.
                                                                    {
  DCHECK(!array_buffer_transfer_map_.Find(array_buffer));
  DCHECK(!array_buffer->is_shared());
  array_buffer_transfer_map_.Insert(array_buffer, transfer_id);
}
References array_buffer_transfer_map_, and v8::internal::DCHECK().
Referenced by v8::ValueSerializer::TransferArrayBuffer().
WriteBigInt()
void v8::internal::ValueSerializer::WriteBigInt (Tagged< BigInt > bigint) [private]
Definition at line 554 of file value-serializer.cc.
                                                       {
  WriteTag(SerializationTag::kBigInt);
  WriteBigIntContents(bigint);
}
References v8::internal::kBigInt, WriteBigIntContents(), and WriteTag().
Referenced by WriteObject().
WriteBigIntContents()
void v8::internal::ValueSerializer::WriteBigIntContents (Tagged< BigInt > bigint) [private]
Definition at line 384 of file value-serializer.cc.
                                                               {
  uint32_t bitfield = bigint->GetBitfieldForSerialization();
  size_t bytelength = BigInt::DigitsByteLengthForBitfield(bitfield);
  WriteVarint<uint32_t>(bitfield);
  uint8_t* dest;
  if (ReserveRawBytes(bytelength).To(&dest)) {
    bigint->SerializeDigits(dest, bytelength);
  }
}
References v8::internal::BigInt::DigitsByteLengthForBitfield(), and ReserveRawBytes().
Referenced by WriteBigInt(), and WriteJSPrimitiveWrapper().
WriteByte()
void v8::internal::ValueSerializer::WriteByte (uint8_t value)
Definition at line 438 of file value-serializer.cc.
                                             {
  uint8_t* dest;
  if (ReserveRawBytes(sizeof(uint8_t)).To(&dest)) {
    *dest = value;
  }
}
References ReserveRawBytes(), and v8::internal::value.
WriteDouble()
void v8::internal::ValueSerializer::WriteDouble (double value)
Referenced by v8::ValueSerializer::WriteDouble(), WriteHeapNumber(), WriteJSArray(), WriteJSDate(), and WriteJSPrimitiveWrapper().
WriteHeader()
void v8::internal::ValueSerializer::WriteHeader ()
Definition at line 319 of file value-serializer.cc.
                                  {
  WriteTag(SerializationTag::kVersion);
  WriteVarint(kLatestVersion);
}
References v8::internal::kLatestVersion, v8::internal::kVersion, WriteTag(), and WriteVarint().
Referenced by v8::ValueSerializer::WriteHeader().
WriteHeapNumber()
void v8::internal::ValueSerializer::WriteHeapNumber (Tagged< HeapNumber > number) [private]
Definition at line 549 of file value-serializer.cc.
                                                               {
  WriteTag(SerializationTag::kDouble);
  WriteDouble(number->value());
}
References v8::internal::kDouble, WriteDouble(), and WriteTag().
Referenced by WriteObject().
WriteHostObject()
Maybe< bool > v8::internal::ValueSerializer::WriteHostObject (DirectHandle< JSObject > object) [private]
Definition at line 1252 of file value-serializer.cc.
                                                                          {
  WriteTag(SerializationTag::kHostObject);
  if (!delegate_) {
    isolate_->Throw(*isolate_->factory()->NewError(
        isolate_->error_function(), MessageTemplate::kDataCloneError, object));
    return Nothing<bool>();
  }
  v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate_);
  Maybe<bool> result =
      delegate_->WriteHostObject(v8_isolate, Utils::ToLocal(object));
  RETURN_VALUE_IF_EXCEPTION(isolate_, Nothing<bool>());
  USE(result);
  DCHECK(!result.IsNothing());
  DCHECK(result.ToChecked());
  return ThrowIfOutOfMemory();
}
References v8::internal::DCHECK(), delegate_, v8::internal::Isolate::factory(), isolate_, v8::internal::kHostObject, v8::internal::Factory::NewError(), v8::base::internal::result, RETURN_VALUE_IF_EXCEPTION, v8::internal::Isolate::Throw(), ThrowIfOutOfMemory(), USE, v8::ValueSerializer::Delegate::WriteHostObject(), and WriteTag().
Referenced by WriteJSArrayBufferView(), and WriteJSReceiver().
WriteJSArray()
Maybe< bool > v8::internal::ValueSerializer::WriteJSArray (DirectHandle< JSArray > array) [private]
Definition at line 749 of file value-serializer.cc.
                                                                     {
  PtrComprCageBase cage_base(isolate_);
  uint32_t length = 0;
  bool valid_length = Object::ToArrayLength(array->length(), &length);
  DCHECK(valid_length);
  USE(valid_length);
  // To keep things simple, for now we decide between dense and sparse
  // serialization based on elements kind. A more principled heuristic could
  // count the elements, but would need to take care to note which indices
  // existed (as only indices which were enumerable own properties at this point
  // should be serialized).
  const bool should_serialize_densely =
      array->HasFastElements(cage_base) && !array->HasHoleyElements(cage_base);
  if (should_serialize_densely) {
    DCHECK_LE(length, static_cast<uint32_t>(FixedArray::kMaxLength));
    WriteTag(SerializationTag::kBeginDenseJSArray);
    WriteVarint<uint32_t>(length);
    uint32_t i = 0;
    // Fast paths. Note that PACKED_ELEMENTS in particular can bail due to the
    // structure of the elements changing.
    switch (array->GetElementsKind(cage_base)) {
      case PACKED_SMI_ELEMENTS: {
        DisallowGarbageCollection no_gc;
        Tagged<FixedArray> elements = Cast<FixedArray>(array->elements());
        for (i = 0; i < length; i++) {
          WriteSmi(Cast<Smi>(elements->get(i)));
        }
        break;
      }
      case PACKED_DOUBLE_ELEMENTS: {
        // Elements are empty_fixed_array, not a FixedDoubleArray, if the array
        // is empty. No elements to encode in this case anyhow.
        if (length == 0) break;
        DisallowGarbageCollection no_gc;
        Tagged<FixedDoubleArray> elements =
            Cast<FixedDoubleArray>(array->elements());
        for (i = 0; i < length; i++) {
          WriteTag(SerializationTag::kDouble);
          WriteDouble(elements->get_scalar(i));
        }
        break;
      }
      case PACKED_ELEMENTS: {
        DirectHandle<Object> old_length(array->length(cage_base), isolate_);
        for (; i < length; i++) {
          if (array->length(cage_base) != *old_length ||
              array->GetElementsKind(cage_base) != PACKED_ELEMENTS) {
            // Fall back to slow path.
            break;
          }
          DirectHandle<Object> element(
              Cast<FixedArray>(array->elements())->get(i), isolate_);
          if (!WriteObject(element).FromMaybe(false)) return Nothing<bool>();
        }
        break;
      }
      default:
        break;
    }
    // If there are elements remaining, serialize them slowly.
    for (; i < length; i++) {
      // Serializing the array's elements can have arbitrary side effects, so we
      // cannot rely on still having fast elements, even if it did to begin
      // with.
      DirectHandle<Object> element;
      LookupIterator it(isolate_, array, i, array, LookupIterator::OWN);
      if (!it.IsFound()) {
        // This can happen in the case where an array that was originally dense
        // became sparse during serialization. It's too late to switch to the
        // sparse format, but we can mark the elements as absent.
        WriteTag(SerializationTag::kTheHole);
        continue;
      }
      if (!Object::GetProperty(&it).ToHandle(&element) ||
          !WriteObject(element).FromMaybe(false)) {
        return Nothing<bool>();
      }
    }
    DirectHandle<FixedArray> keys;
    if (!KeyAccumulator::GetKeys(isolate_, array, KeyCollectionMode::kOwnOnly,
                                 ENUMERABLE_STRINGS,
                                 GetKeysConversion::kKeepNumbers, false, true)
             .ToHandle(&keys)) {
      return Nothing<bool>();
    }
    uint32_t properties_written;
    if (!WriteJSObjectPropertiesSlow(array, keys).To(&properties_written)) {
      return Nothing<bool>();
    }
    WriteTag(SerializationTag::kEndDenseJSArray);
    WriteVarint<uint32_t>(properties_written);
    WriteVarint<uint32_t>(length);
  } else {
    WriteTag(SerializationTag::kBeginSparseJSArray);
    WriteVarint<uint32_t>(length);
    DirectHandle<FixedArray> keys;
    uint32_t properties_written = 0;
    if (!KeyAccumulator::GetKeys(isolate_, array, KeyCollectionMode::kOwnOnly,
                                 ENUMERABLE_STRINGS)
             .ToHandle(&keys) ||
        !WriteJSObjectPropertiesSlow(array, keys).To(&properties_written)) {
      return Nothing<bool>();
    }
    WriteTag(SerializationTag::kEndSparseJSArray);
    WriteVarint<uint32_t>(properties_written);
    WriteVarint<uint32_t>(length);
  }
  return ThrowIfOutOfMemory();
}
References v8::internal::DCHECK(), DCHECK_LE, v8::internal::ENUMERABLE_STRINGS, v8::internal::KeyAccumulator::GetKeys(), v8::internal::Object::GetProperty(), v8::internal::LookupIterator::IsFound(), isolate_, v8::internal::kBeginDenseJSArray, v8::internal::kBeginSparseJSArray, v8::internal::kDouble, v8::internal::kEndDenseJSArray, v8::internal::kEndSparseJSArray, v8::internal::kKeepNumbers, v8::internal::FixedArray::kMaxLength, v8::internal::kOwnOnly, v8::internal::kTheHole, v8::internal::length, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::LookupIterator::OWN, v8::internal::PACKED_DOUBLE_ELEMENTS, v8::internal::PACKED_ELEMENTS, v8::internal::PACKED_SMI_ELEMENTS, ThrowIfOutOfMemory(), v8::internal::Object::ToArrayLength(), v8::anonymous_namespace{api.cc}::ToHandle(), USE, WriteDouble(), WriteJSObjectPropertiesSlow(), WriteObject(), WriteSmi(), and WriteTag().
Referenced by WriteJSReceiver().
WriteJSArrayBuffer()
Maybe< bool > v8::internal::ValueSerializer::WriteJSArrayBuffer (DirectHandle< JSArrayBuffer > array_buffer) [private]
Definition at line 973 of file value-serializer.cc.
                                              {
  if (array_buffer->is_shared()) {
    if (!delegate_) {
      return ThrowDataCloneError(MessageTemplate::kDataCloneError,
                                 array_buffer);
    }
    v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate_);
    Maybe<uint32_t> index = delegate_->GetSharedArrayBufferId(
        v8_isolate, Utils::ToLocalShared(array_buffer));
    RETURN_VALUE_IF_EXCEPTION(isolate_, Nothing<bool>());
    WriteTag(SerializationTag::kSharedArrayBuffer);
    WriteVarint(index.FromJust());
#if V8_ENABLE_WEBASSEMBLY
    // SharedArrayBuffers that are actually WebAssembly memories need special
    // handling because they have metadata that may diverge from their
    // BackingStore's.
    //
    // These are handled by also serializing/deserializing their corresponding
    // WebAssembly.Memory object.
    //
    // See comment for WasmMemoryObject::FixUpResizableArrayBuffer for details.
    auto backing_store = array_buffer->GetBackingStore();
    if (backing_store && backing_store->is_wasm_memory()) {
      if (array_buffer->is_resizable_by_js()) {
        Handle<Object> memory =
            Object::GetProperty(
                isolate_, array_buffer,
                isolate_->factory()->array_buffer_wasm_memory_symbol())
                .ToHandleChecked();
        CHECK(IsWasmMemoryObject(*memory));
        // WebAssembly.Memory and its buffer exist in a reference cycle.
        // Manually break the cycle, otherwise deserialization will attempt to
        // read the same ArrayBuffer/WebAssembly.Memory recursively and fail.
        if (!id_map_.Find(memory)) {
          WriteVarint(static_cast<uint8_t>(
              WasmMemoryArrayBufferTag::kResizableFollowedByWasmMemory));
          if (!WriteJSReceiver(Cast<JSReceiver>(memory)).FromMaybe(false)) {
            return Nothing<bool>();
          }
        } else {
          WriteVarint(static_cast<uint8_t>(
              WasmMemoryArrayBufferTag::kResizableNotFollowedByWasmMemory));
        }
      } else {
        WriteVarint(
            static_cast<uint8_t>(WasmMemoryArrayBufferTag::kFixedLength));
      }
    }
#endif // V8_ENABLE_WEBASSEMBLY
    return ThrowIfOutOfMemory();
  }
  uint32_t* transfer_entry = array_buffer_transfer_map_.Find(array_buffer);
  if (transfer_entry) {
    WriteTag(SerializationTag::kArrayBufferTransfer);
    WriteVarint(*transfer_entry);
    return ThrowIfOutOfMemory();
  }
  if (array_buffer->was_detached()) {
    return ThrowDataCloneError(
        MessageTemplate::kDataCloneErrorDetachedArrayBuffer);
  }
  size_t byte_length = array_buffer->byte_length();
  if (byte_length > std::numeric_limits<uint32_t>::max()) {
    return ThrowDataCloneError(MessageTemplate::kDataCloneError, array_buffer);
  }
  if (array_buffer->is_resizable_by_js()) {
    size_t max_byte_length = array_buffer->max_byte_length();
    if (max_byte_length > std::numeric_limits<uint32_t>::max()) {
      return ThrowDataCloneError(MessageTemplate::kDataCloneError,
                                 array_buffer);
    }
    WriteTag(SerializationTag::kResizableArrayBuffer);
    WriteVarint<uint32_t>(static_cast<uint32_t>(byte_length));
    WriteVarint<uint32_t>(static_cast<uint32_t>(max_byte_length));
    WriteRawBytes(array_buffer->backing_store(), byte_length);
    return ThrowIfOutOfMemory();
  }
  WriteTag(SerializationTag::kArrayBuffer);
  WriteVarint<uint32_t>(static_cast<uint32_t>(byte_length));
  WriteRawBytes(array_buffer->backing_store(), byte_length);
  return ThrowIfOutOfMemory();
}
References array_buffer_transfer_map_, CHECK, delegate_, v8::internal::Isolate::factory(), v8::internal::Object::GetProperty(), v8::ValueSerializer::Delegate::GetSharedArrayBufferId(), id_map_, v8::internal::index, isolate_, v8::internal::kArrayBuffer, v8::internal::kArrayBufferTransfer, v8::internal::kResizableArrayBuffer, v8::internal::kSharedArrayBuffer, RETURN_VALUE_IF_EXCEPTION, ThrowDataCloneError(), ThrowIfOutOfMemory(), WriteJSReceiver(), WriteRawBytes(), WriteTag(), and WriteVarint().
Referenced by WriteJSReceiver().
WriteJSArrayBufferView()
Maybe< bool > v8::internal::ValueSerializer::WriteJSArrayBufferView (Tagged< JSArrayBufferView > array_buffer) [private]
Definition at line 1063 of file value-serializer.cc.
                                    {
  if (treat_array_buffer_views_as_host_objects_) {
    return WriteHostObject(direct_handle(view, isolate_));
  }
  WriteTag(SerializationTag::kArrayBufferView);
  ArrayBufferViewTag tag = ArrayBufferViewTag::kInt8Array;
  if (IsJSTypedArray(view)) {
    if (Cast<JSTypedArray>(view)->IsOutOfBounds()) {
      return ThrowDataCloneError(MessageTemplate::kDataCloneError,
                                 direct_handle(view, isolate_));
    }
    switch (Cast<JSTypedArray>(view)->type()) {
#define TYPED_ARRAY_CASE(Type, type, TYPE, ctype) \
  case kExternal##Type##Array: \
    tag = ArrayBufferViewTag::k##Type##Array; \
    break;
      TYPED_ARRAYS(TYPED_ARRAY_CASE)
#undef TYPED_ARRAY_CASE
    }
  } else {
    DCHECK(IsJSDataViewOrRabGsabDataView(view));
    if (IsJSRabGsabDataView(view) &&
        Cast<JSRabGsabDataView>(view)->IsOutOfBounds()) {
      return ThrowDataCloneError(MessageTemplate::kDataCloneError,
                                 direct_handle(view, isolate_));
    }
    tag = ArrayBufferViewTag::kDataView;
  }
  WriteVarint(static_cast<uint8_t>(tag));
  WriteVarint(static_cast<uint32_t>(view->byte_offset()));
  WriteVarint(static_cast<uint32_t>(view->byte_length()));
  uint32_t flags =
      JSArrayBufferViewIsLengthTracking::encode(view->is_length_tracking()) |
      JSArrayBufferViewIsBackedByRab::encode(view->is_backed_by_rab());
  WriteVarint(flags);
  return ThrowIfOutOfMemory();
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::flags, isolate_, v8::internal::kArrayBufferView, ThrowDataCloneError(), ThrowIfOutOfMemory(), treat_array_buffer_views_as_host_objects_, v8::internal::tracing::type, TYPED_ARRAY_CASE, TYPED_ARRAYS, WriteHostObject(), WriteTag(), and WriteVarint().
Referenced by WriteJSReceiver().
WriteJSDate()
void v8::internal::ValueSerializer::WriteJSDate (Tagged< JSDate > date) [private]
Definition at line 865 of file value-serializer.cc.
                                                     {
  WriteTag(SerializationTag::kDate);
  WriteDouble(date->value());
}
References v8::internal::date, v8::internal::kDate, WriteDouble(), and WriteTag().
Referenced by WriteJSReceiver().
WriteJSError()
Maybe< bool > v8::internal::ValueSerializer::WriteJSError (DirectHandle< JSObject > error) [private]
Definition at line 1103 of file value-serializer.cc.
                                                                      {
  DirectHandle<Object> stack;
  PropertyDescriptor message_desc;
  Maybe<bool> message_found = JSReceiver::GetOwnPropertyDescriptor(
      isolate_, error, isolate_->factory()->message_string(), &message_desc);
  MAYBE_RETURN(message_found, Nothing<bool>());
  PropertyDescriptor cause_desc;
  Maybe<bool> cause_found = JSReceiver::GetOwnPropertyDescriptor(
      isolate_, error, isolate_->factory()->cause_string(), &cause_desc);
  WriteTag(SerializationTag::kError);
  DirectHandle<Object> name_object;
  if (!JSObject::GetProperty(isolate_, error, "name").ToHandle(&name_object)) {
    return Nothing<bool>();
  }
  DirectHandle<String> name;
  if (!Object::ToString(isolate_, name_object).ToHandle(&name)) {
    return Nothing<bool>();
  }
  if (name->IsOneByteEqualTo(base::CStrVector("EvalError"))) {
    WriteVarint(static_cast<uint8_t>(ErrorTag::kEvalErrorPrototype));
  } else if (name->IsOneByteEqualTo(base::CStrVector("RangeError"))) {
    WriteVarint(static_cast<uint8_t>(ErrorTag::kRangeErrorPrototype));
  } else if (name->IsOneByteEqualTo(base::CStrVector("ReferenceError"))) {
    WriteVarint(static_cast<uint8_t>(ErrorTag::kReferenceErrorPrototype));
  } else if (name->IsOneByteEqualTo(base::CStrVector("SyntaxError"))) {
    WriteVarint(static_cast<uint8_t>(ErrorTag::kSyntaxErrorPrototype));
  } else if (name->IsOneByteEqualTo(base::CStrVector("TypeError"))) {
    WriteVarint(static_cast<uint8_t>(ErrorTag::kTypeErrorPrototype));
  } else if (name->IsOneByteEqualTo(base::CStrVector("URIError"))) {
    WriteVarint(static_cast<uint8_t>(ErrorTag::kUriErrorPrototype));
  } else {
    // The default prototype in the deserialization side is Error.prototype, so
    // we don't have to do anything here.
  }
  if (message_found.FromJust() &&
      PropertyDescriptor::IsDataDescriptor(&message_desc)) {
    DirectHandle<String> message;
    if (!Object::ToString(isolate_, message_desc.value()).ToHandle(&message)) {
      return Nothing<bool>();
    }
    WriteVarint(static_cast<uint8_t>(ErrorTag::kMessage));
    WriteString(message);
  }
  if (!Object::GetProperty(isolate_, error, isolate_->factory()->stack_string())
           .ToHandle(&stack)) {
    return Nothing<bool>();
  }
  if (IsString(*stack)) {
    WriteVarint(static_cast<uint8_t>(ErrorTag::kStack));
    WriteString(Cast<String>(stack));
  }
  // The {cause} can self-reference the error. We add at the end, so that we can
  // create the Error first when deserializing.
  if (cause_found.FromJust() &&
      PropertyDescriptor::IsDataDescriptor(&cause_desc)) {
    DirectHandle<Object> cause = cause_desc.value();
    WriteVarint(static_cast<uint8_t>(ErrorTag::kCause));
    if (!WriteObject(cause).FromMaybe(false)) {
      return Nothing<bool>();
    }
  }
  WriteVarint(static_cast<uint8_t>(ErrorTag::kEnd));
  return ThrowIfOutOfMemory();
}
References v8::base::CStrVector(), v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::JSReceiver::GetOwnPropertyDescriptor(), v8::internal::Object::GetProperty(), v8::internal::PropertyDescriptor::IsDataDescriptor(), isolate_, v8_inspector::anonymous_namespace{value-mirror.cc}::kEnd, v8::internal::kError, v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::kStack, MAYBE_RETURN, v8::internal::name, v8::internal::stack, ThrowIfOutOfMemory(), v8::anonymous_namespace{api.cc}::ToHandle(), v8::Value::ToString(), v8::internal::PropertyDescriptor::value(), WriteObject(), WriteString(), WriteTag(), and WriteVarint().
Referenced by WriteJSReceiver().
WriteJSMap()
Maybe< bool > v8::internal::ValueSerializer::WriteJSMap (DirectHandle< JSMap > map) [private]
Definition at line 904 of file value-serializer.cc.
                                                                  {
  // First copy the key-value pairs, since getters could mutate them.
  DirectHandle<OrderedHashMap> table(Cast<OrderedHashMap>(js_map->table()),
                                     isolate_);
  int length = table->NumberOfElements() * 2;
  DirectHandle<FixedArray> entries = isolate_->factory()->NewFixedArray(length);
  {
    DisallowGarbageCollection no_gc;
    Tagged<OrderedHashMap> raw_table = *table;
    Tagged<FixedArray> raw_entries = *entries;
    Tagged<Hole> hash_table_hole =
        ReadOnlyRoots(isolate_).hash_table_hole_value();
    int result_index = 0;
    for (InternalIndex entry : raw_table->IterateEntries()) {
      Tagged<Object> key = raw_table->KeyAt(entry);
      if (key == hash_table_hole) continue;
      raw_entries->set(result_index++, key);
      raw_entries->set(result_index++, raw_table->ValueAt(entry));
    }
    DCHECK_EQ(result_index, length);
  }
  // Then write it out.
  WriteTag(SerializationTag::kBeginJSMap);
  for (int i = 0; i < length; i++) {
    if (!WriteObject(direct_handle(entries->get(i), isolate_))
             .FromMaybe(false)) {
      return Nothing<bool>();
    }
  }
  WriteTag(SerializationTag::kEndJSMap);
  WriteVarint<uint32_t>(length);
  return ThrowIfOutOfMemory();
}
References DCHECK_EQ, v8::internal::direct_handle(), v8::internal::Isolate::factory(), isolate_, v8::internal::kBeginJSMap, v8::internal::kEndJSMap, v8::internal::key, v8::internal::length, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, ThrowIfOutOfMemory(), WriteObject(), and WriteTag().
Referenced by WriteJSReceiver().
WriteJSObject()
Maybe< bool > v8::internal::ValueSerializer::WriteJSObject (DirectHandle< JSObject > object) [private]
Definition at line 685 of file value-serializer.cc.
                                                                        {
  DCHECK(!IsCustomElementsReceiverMap(object->map()));
  const bool can_serialize_fast =
      object->HasFastProperties(isolate_) && object->elements()->length() == 0;
  if (!can_serialize_fast) return WriteJSObjectSlow(object);
  DirectHandle<Map> map(object->map(), isolate_);
  WriteTag(SerializationTag::kBeginJSObject);
  // Write out fast properties as long as they are only data properties and the
  // map doesn't change.
  uint32_t properties_written = 0;
  bool map_changed = false;
  for (InternalIndex i : map->IterateOwnDescriptors()) {
    DirectHandle<Name> key(map->instance_descriptors(isolate_)->GetKey(i),
                           isolate_);
    if (!IsString(*key, isolate_)) continue;
    PropertyDetails details =
        map->instance_descriptors(isolate_)->GetDetails(i);
    if (details.IsDontEnum()) continue;
    DirectHandle<Object> value;
    if (V8_LIKELY(!map_changed)) map_changed = *map != object->map();
    if (V8_LIKELY(!map_changed &&
                  details.location() == PropertyLocation::kField)) {
      DCHECK_EQ(PropertyKind::kData, details.kind());
      FieldIndex field_index = FieldIndex::ForDetails(*map, details);
      value = direct_handle(object->RawFastPropertyAt(field_index), isolate_);
    } else {
      // This logic should essentially match WriteJSObjectPropertiesSlow.
      // If the property is no longer found, do not serialize it.
      // This could happen if a getter deleted the property.
      LookupIterator it(isolate_, object, key, LookupIterator::OWN);
      if (!it.IsFound()) continue;
      if (!Object::GetProperty(&it).ToHandle(&value)) return Nothing<bool>();
    }
    if (!WriteObject(key).FromMaybe(false) ||
        !WriteObject(value).FromMaybe(false)) {
      return Nothing<bool>();
    }
    properties_written++;
  }
  WriteTag(SerializationTag::kEndJSObject);
  WriteVarint<uint32_t>(properties_written);
  return ThrowIfOutOfMemory();
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::direct_handle(), v8::internal::FieldIndex::ForDetails(), v8::internal::Object::GetProperty(), v8::internal::IsCustomElementsReceiverMap(), v8::internal::PropertyDetails::IsDontEnum(), v8::internal::LookupIterator::IsFound(), isolate_, v8::internal::kBeginJSObject, v8::internal::kData, v8::internal::kEndJSObject, v8::internal::key, v8::internal::kField, v8::internal::PropertyDetails::kind(), v8::internal::PropertyDetails::location(), v8::internal::LookupIterator::OWN, ThrowIfOutOfMemory(), v8::anonymous_namespace{api.cc}::ToHandle(), V8_LIKELY, v8::internal::value, WriteJSObjectSlow(), WriteObject(), and WriteTag().
Referenced by WriteJSReceiver().
WriteJSObjectPropertiesSlow()
Maybe< uint32_t > v8::internal::ValueSerializer::WriteJSObjectPropertiesSlow (DirectHandle< JSObject > object, DirectHandle< FixedArray > keys) [private]
Definition at line 1269 of file value-serializer.cc.
                                                                  {
  uint32_t properties_written = 0;
  int length = keys->length();
  for (int i = 0; i < length; i++) {
    DirectHandle<Object> key(keys->get(i), isolate_);
    PropertyKey lookup_key(isolate_, key);
    LookupIterator it(isolate_, object, lookup_key, LookupIterator::OWN);
    DirectHandle<Object> value;
    if (!Object::GetProperty(&it).ToHandle(&value)) return Nothing<uint32_t>();
    // If the property is no longer found, do not serialize it.
    // This could happen if a getter deleted the property.
    if (!it.IsFound()) continue;
    if (!WriteObject(key).FromMaybe(false) ||
        !WriteObject(value).FromMaybe(false)) {
      return Nothing<uint32_t>();
    }
    properties_written++;
  }
  return Just(properties_written);
}
References v8::internal::Object::GetProperty(), v8::internal::LookupIterator::IsFound(), isolate_, v8::Just(), v8::internal::key, v8::internal::length, v8::internal::LookupIterator::OWN, v8::anonymous_namespace{api.cc}::ToHandle(), v8::internal::value, and WriteObject().
Referenced by WriteJSArray(), and WriteJSObjectSlow().
WriteJSObjectSlow()
Maybe< bool > v8::internal::ValueSerializer::WriteJSObjectSlow (DirectHandle< JSObject > object) [private]
Definition at line 734 of file value-serializer.cc.
                                                                            {
  WriteTag(SerializationTag::kBeginJSObject);
  DirectHandle<FixedArray> keys;
  uint32_t properties_written = 0;
  if (!KeyAccumulator::GetKeys(isolate_, object, KeyCollectionMode::kOwnOnly,
                               ENUMERABLE_STRINGS)
           .ToHandle(&keys) ||
      !WriteJSObjectPropertiesSlow(object, keys).To(&properties_written)) {
    return Nothing<bool>();
  }
  WriteTag(SerializationTag::kEndJSObject);
  WriteVarint<uint32_t>(properties_written);
  return ThrowIfOutOfMemory();
}
References v8::internal::ENUMERABLE_STRINGS, v8::internal::KeyAccumulator::GetKeys(), isolate_, v8::internal::kBeginJSObject, v8::internal::kEndJSObject, v8::internal::kOwnOnly, ThrowIfOutOfMemory(), v8::anonymous_namespace{api.cc}::ToHandle(), WriteJSObjectPropertiesSlow(), and WriteTag().
Referenced by WriteJSObject().
WriteJSPrimitiveWrapper()
Maybe< bool > v8::internal::ValueSerializer::WriteJSPrimitiveWrapper (DirectHandle< JSPrimitiveWrapper > value) [private]
Definition at line 870 of file value-serializer.cc.
                                            {
  PtrComprCageBase cage_base(isolate_);
  {
    DisallowGarbageCollection no_gc;
    Tagged<Object> inner_value = value->value();
    if (IsTrue(inner_value, isolate_)) {
      WriteTag(SerializationTag::kTrueObject);
    } else if (IsFalse(inner_value, isolate_)) {
      WriteTag(SerializationTag::kFalseObject);
    } else if (IsNumber(inner_value, cage_base)) {
      WriteTag(SerializationTag::kNumberObject);
      WriteDouble(Object::NumberValue(inner_value));
    } else if (IsBigInt(inner_value, cage_base)) {
      WriteTag(SerializationTag::kBigIntObject);
      WriteBigIntContents(Cast<BigInt>(inner_value));
    } else if (IsString(inner_value, cage_base)) {
      WriteTag(SerializationTag::kStringObject);
      WriteString(direct_handle(Cast<String>(inner_value), isolate_));
    } else {
      AllowGarbageCollection allow_gc;
      DCHECK(IsSymbol(inner_value));
      return ThrowDataCloneError(MessageTemplate::kDataCloneError, value);
    }
  }
  return ThrowIfOutOfMemory();
}
References v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::IsNumber(), isolate_, v8::internal::kBigIntObject, v8::internal::kFalseObject, v8::internal::kNumberObject, v8::internal::kStringObject, v8::internal::kTrueObject, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::Object::NumberValue(), ThrowDataCloneError(), ThrowIfOutOfMemory(), v8::internal::value, WriteBigIntContents(), WriteDouble(), WriteString(), and WriteTag().
Referenced by WriteJSReceiver().
WriteJSReceiver()
Maybe< bool > v8::internal::ValueSerializer::WriteJSReceiver (DirectHandle< JSReceiver > receiver) [private]
Definition at line 581 of file value-serializer.cc.
                                       {
  // If the object has already been serialized, just write its ID.
  auto find_result = id_map_.FindOrInsert(receiver);
  if (find_result.already_exists) {
    WriteTag(SerializationTag::kObjectReference);
    WriteVarint(*find_result.entry - 1);
    return ThrowIfOutOfMemory();
  }
  // Otherwise, allocate an ID for it.
  uint32_t id = next_id_++;
  *find_result.entry = id + 1;
  // Eliminate callable and exotic objects, which should not be serialized.
  InstanceType instance_type = receiver->map()->instance_type();
  if (IsCallable(*receiver) ||
      (IsSpecialReceiverInstanceType(instance_type) &&
       instance_type != JS_SPECIAL_API_OBJECT_TYPE
#if V8_ENABLE_WEBASSEMBLY
       && instance_type != WASM_STRUCT_TYPE && instance_type != WASM_ARRAY_TYPE
#endif
       )) {
    return ThrowDataCloneError(MessageTemplate::kDataCloneError, receiver);
  }
  // If we are at the end of the stack, abort. This function may recurse.
  STACK_CHECK(isolate_, Nothing<bool>());
  HandleScope scope(isolate_);
  switch (instance_type) {
    case JS_ARRAY_TYPE:
      return WriteJSArray(Cast<JSArray>(receiver));
    case JS_ARRAY_ITERATOR_PROTOTYPE_TYPE:
    case JS_ITERATOR_PROTOTYPE_TYPE:
    case JS_MAP_ITERATOR_PROTOTYPE_TYPE:
    case JS_OBJECT_PROTOTYPE_TYPE:
    case JS_OBJECT_TYPE:
    case JS_PROMISE_PROTOTYPE_TYPE:
    case JS_REG_EXP_PROTOTYPE_TYPE:
    case JS_SET_ITERATOR_PROTOTYPE_TYPE:
    case JS_SET_PROTOTYPE_TYPE:
    case JS_STRING_ITERATOR_PROTOTYPE_TYPE:
    case JS_TYPED_ARRAY_PROTOTYPE_TYPE:
    case JS_API_OBJECT_TYPE: {
      DirectHandle<JSObject> js_object = Cast<JSObject>(receiver);
      Maybe<bool> is_host_object = IsHostObject(js_object);
      if (is_host_object.IsNothing()) {
        return is_host_object;
      }
      if (is_host_object.FromJust()) {
        return WriteHostObject(js_object);
      } else {
        return WriteJSObject(js_object);
      }
    }
    case JS_SPECIAL_API_OBJECT_TYPE:
      return WriteHostObject(Cast<JSObject>(receiver));
    case JS_DATE_TYPE:
      WriteJSDate(Cast<JSDate>(*receiver));
      return ThrowIfOutOfMemory();
    case JS_PRIMITIVE_WRAPPER_TYPE:
      return WriteJSPrimitiveWrapper(Cast<JSPrimitiveWrapper>(receiver));
    case JS_REG_EXP_TYPE:
      WriteJSRegExp(Cast<JSRegExp>(receiver));
      return ThrowIfOutOfMemory();
    case JS_MAP_TYPE:
      return WriteJSMap(Cast<JSMap>(receiver));
    case JS_SET_TYPE:
      return WriteJSSet(Cast<JSSet>(receiver));
    case JS_ARRAY_BUFFER_TYPE:
      return WriteJSArrayBuffer(Cast<JSArrayBuffer>(receiver));
    case JS_TYPED_ARRAY_TYPE:
    case JS_DATA_VIEW_TYPE:
    case JS_RAB_GSAB_DATA_VIEW_TYPE:
      return WriteJSArrayBufferView(Cast<JSArrayBufferView>(*receiver));
    case JS_ERROR_TYPE:
      return WriteJSError(Cast<JSObject>(receiver));
    case JS_SHARED_ARRAY_TYPE:
      return WriteJSSharedArray(Cast<JSSharedArray>(receiver));
    case JS_SHARED_STRUCT_TYPE:
      return WriteJSSharedStruct(Cast<JSSharedStruct>(receiver));
    case JS_ATOMICS_MUTEX_TYPE:
    case JS_ATOMICS_CONDITION_TYPE:
      return WriteSharedObject(receiver);
#if V8_ENABLE_WEBASSEMBLY
    case WASM_MODULE_OBJECT_TYPE:
      return WriteWasmModule(Cast<WasmModuleObject>(receiver));
    case WASM_MEMORY_OBJECT_TYPE:
      return WriteWasmMemory(Cast<WasmMemoryObject>(receiver));
    case WASM_STRUCT_TYPE:
    case WASM_ARRAY_TYPE:
      if (HeapLayout::InAnySharedSpace(*receiver)) {
        return WriteSharedObject(receiver);
      }
      break;
#endif // V8_ENABLE_WEBASSEMBLY
    default:
      break;
  }
  return ThrowDataCloneError(MessageTemplate::kDataCloneError, receiver);
}
References v8::Maybe< T >::FromJust(), id_map_, v8::internal::HeapLayout::InAnySharedSpace(), IsHostObject(), v8::Maybe< T >::IsNothing(), isolate_, v8::internal::IsSpecialReceiverInstanceType(), v8::internal::kObjectReference, next_id_, STACK_CHECK, ThrowDataCloneError(), ThrowIfOutOfMemory(), WriteHostObject(), WriteJSArray(), WriteJSArrayBuffer(), WriteJSArrayBufferView(), WriteJSDate(), WriteJSError(), WriteJSMap(), WriteJSObject(), WriteJSPrimitiveWrapper(), WriteJSRegExp(), WriteJSSet(), WriteJSSharedArray(), WriteJSSharedStruct(), WriteSharedObject(), WriteTag(), and WriteVarint().
Referenced by WriteJSArrayBuffer(), and WriteObject().
WriteJSRegExp()
void v8::internal::ValueSerializer::WriteJSRegExp (DirectHandle< JSRegExp > regexp) [private]
Definition at line 898 of file value-serializer.cc.
                                                                 {
  WriteTag(SerializationTag::kRegExp);
  WriteString(direct_handle(regexp->source(), isolate_));
  WriteVarint(static_cast<uint32_t>(regexp->flags()));
}
References v8::internal::direct_handle(), isolate_, v8::internal::kRegExp, WriteString(), WriteTag(), and WriteVarint().
Referenced by WriteJSReceiver().
WriteJSSet()
Maybe< bool > v8::internal::ValueSerializer::WriteJSSet (DirectHandle< JSSet > map) [private]
Definition at line 939 of file value-serializer.cc.
                                                                  {
  // First copy the element pointers, since getters could mutate them.
  DirectHandle<OrderedHashSet> table(Cast<OrderedHashSet>(js_set->table()),
                                     isolate_);
  int length = table->NumberOfElements();
  DirectHandle<FixedArray> entries = isolate_->factory()->NewFixedArray(length);
  {
    DisallowGarbageCollection no_gc;
    Tagged<OrderedHashSet> raw_table = *table;
    Tagged<FixedArray> raw_entries = *entries;
    Tagged<Hole> hash_table_hole =
        ReadOnlyRoots(isolate_).hash_table_hole_value();
    int result_index = 0;
    for (InternalIndex entry : raw_table->IterateEntries()) {
      Tagged<Object> key = raw_table->KeyAt(entry);
      if (key == hash_table_hole) continue;
      raw_entries->set(result_index++, key);
    }
    DCHECK_EQ(result_index, length);
  }
  // Then write it out.
  WriteTag(SerializationTag::kBeginJSSet);
  for (int i = 0; i < length; i++) {
    if (!WriteObject(direct_handle(entries->get(i), isolate_))
             .FromMaybe(false)) {
      return Nothing<bool>();
    }
  }
  WriteTag(SerializationTag::kEndJSSet);
  WriteVarint<uint32_t>(length);
  return ThrowIfOutOfMemory();
}
References DCHECK_EQ, v8::internal::direct_handle(), v8::internal::Isolate::factory(), isolate_, v8::internal::kBeginJSSet, v8::internal::kEndJSSet, v8::internal::key, v8::internal::length, v8::internal::FactoryBase< Impl >::NewFixedArray(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, ThrowIfOutOfMemory(), WriteObject(), and WriteTag().
Referenced by WriteJSReceiver().
WriteJSSharedArray()
Maybe< bool > v8::internal::ValueSerializer::WriteJSSharedArray (DirectHandle< JSSharedArray > shared_array) [private]
Definition at line 1181 of file value-serializer.cc.
                                              {
  return WriteSharedObject(shared_array);
}
References WriteSharedObject().
Referenced by WriteJSReceiver().
WriteJSSharedStruct()
Maybe< bool > v8::internal::ValueSerializer::WriteJSSharedStruct (DirectHandle< JSSharedStruct > shared_struct) [private]
Definition at line 1175 of file value-serializer.cc.
                                                {
  // TODO(v8:12547): Support copying serialization for shared structs as well.
  return WriteSharedObject(shared_struct);
}
References WriteSharedObject().
Referenced by WriteJSReceiver().
WriteObject()
Maybe< bool > v8::internal::ValueSerializer::WriteObject (DirectHandle< Object > object)
Definition at line 468 of file value-serializer.cc.
                                                                    {
  // There is no sense in trying to proceed if we've previously run out of
  // memory. Bail immediately, as this likely implies that some write has
  // previously failed and so the buffer is corrupt.
  if (V8_UNLIKELY(out_of_memory_)) return ThrowIfOutOfMemory();
  if (IsSmi(*object)) {
    WriteSmi(Cast<Smi>(*object));
    return ThrowIfOutOfMemory();
  }
  DCHECK(IsHeapObject(*object));
  InstanceType instance_type =
      Cast<HeapObject>(*object)->map(isolate_)->instance_type();
  switch (instance_type) {
    case ODDBALL_TYPE:
      WriteOddball(Cast<Oddball>(*object));
      return ThrowIfOutOfMemory();
    case HEAP_NUMBER_TYPE:
      WriteHeapNumber(Cast<HeapNumber>(*object));
      return ThrowIfOutOfMemory();
    case BIGINT_TYPE:
      WriteBigInt(Cast<BigInt>(*object));
      return ThrowIfOutOfMemory();
    case JS_TYPED_ARRAY_TYPE:
    case JS_DATA_VIEW_TYPE:
    case JS_RAB_GSAB_DATA_VIEW_TYPE: {
      // Despite being JSReceivers, these have their wrapped buffer serialized
      // first. That makes this logic a little quirky, because it needs to
      // happen before we assign object IDs.
      // TODO(jbroman): It may be possible to avoid materializing a typed
      // array's buffer here.
      DirectHandle<JSArrayBufferView> view = Cast<JSArrayBufferView>(object);
      if (!id_map_.Find(view) && !treat_array_buffer_views_as_host_objects_) {
        DirectHandle<JSArrayBuffer> buffer(
            InstanceTypeChecker::IsJSTypedArray(instance_type)
                ? Cast<JSTypedArray>(view)->GetBuffer(isolate_)
                : direct_handle(Cast<JSArrayBuffer>(view->buffer()), isolate_));
        if (!WriteJSReceiver(buffer).FromMaybe(false)) return Nothing<bool>();
      }
      return WriteJSReceiver(view);
    }
    default:
      if (InstanceTypeChecker::IsString(instance_type)) {
        WriteString(Cast<String>(object));
        return ThrowIfOutOfMemory();
      } else if (InstanceTypeChecker::IsJSReceiver(instance_type)) {
        return WriteJSReceiver(Cast<JSReceiver>(object));
      } else {
        return ThrowDataCloneError(MessageTemplate::kDataCloneError, object);
      }
  }
}
References v8::internal::BIGINT_TYPE, v8::internal::DCHECK(), v8::internal::direct_handle(), id_map_, v8::internal::IsHeapObject(), isolate_, v8::internal::IsSmi(), out_of_memory_, ThrowDataCloneError(), ThrowIfOutOfMemory(), treat_array_buffer_views_as_host_objects_, V8_UNLIKELY, WriteBigInt(), WriteHeapNumber(), WriteJSReceiver(), WriteOddball(), WriteSmi(), and WriteString().
Referenced by WriteJSArray(), WriteJSError(), WriteJSMap(), WriteJSObject(), WriteJSObjectPropertiesSlow(), WriteJSSet(), and v8::ValueSerializer::WriteValue().
WriteOddball()
void v8::internal::ValueSerializer::WriteOddball (Tagged< Oddball > oddball) [private]
Definition at line 522 of file value-serializer.cc.
                                                          {
  SerializationTag tag = SerializationTag::kUndefined;
  switch (oddball->kind()) {
    case Oddball::kUndefined:
      tag = SerializationTag::kUndefined;
      break;
    case Oddball::kFalse:
      tag = SerializationTag::kFalse;
      break;
    case Oddball::kTrue:
      tag = SerializationTag::kTrue;
      break;
    case Oddball::kNull:
      tag = SerializationTag::kNull;
      break;
    default:
      UNREACHABLE();
  }
  WriteTag(tag);
}
References v8::internal::Oddball::kFalse, v8::internal::kFalse, v8::internal::Oddball::kNull, v8::internal::kNull, v8::internal::Oddball::kTrue, v8::internal::kTrue, v8::internal::Oddball::kUndefined, v8::internal::kUndefined, v8::internal::UNREACHABLE(), and WriteTag().
Referenced by WriteObject().
WriteOneByteString()
void v8::internal::ValueSerializer::WriteOneByteString (base::Vector< const uint8_t > chars) [private]
Definition at line 373 of file value-serializer.cc.
                                                                        {
  WriteVarint<uint32_t>(chars.length());
  WriteRawBytes(chars.begin(), chars.length() * sizeof(uint8_t));
}
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::length(), and WriteRawBytes().
Referenced by WriteString().
WriteRawBytes()
void v8::internal::ValueSerializer::WriteRawBytes (const void * source, size_t length)
Definition at line 394 of file value-serializer.cc.
                                                                     {
  uint8_t* dest;
  if (ReserveRawBytes(length).To(&dest) && length > 0) {
    memcpy(dest, source, length);
  }
}
References v8::internal::length, and ReserveRawBytes().
Referenced by WriteJSArrayBuffer(), WriteOneByteString(), v8::ValueSerializer::WriteRawBytes(), WriteTag(), WriteTwoByteString(), and WriteVarint().
WriteSharedObject()
Maybe< bool > v8::internal::ValueSerializer::WriteSharedObject (DirectHandle< HeapObject > object) [private]
Definition at line 1222 of file value-serializer.cc.
                                     {
  if (!delegate_ || !isolate_->has_shared_space()) {
    return ThrowDataCloneError(MessageTemplate::kDataCloneError, object);
  }
  DCHECK(IsShared(*object));
  // The first time a shared object is serialized, a new conveyor is made. This
  // conveyor is used for every shared object in this serialization and
  // subsequent deserialization sessions. The embedder owns the lifetime of the
  // conveyor.
  if (!shared_object_conveyor_) {
    v8::Isolate* v8_isolate = reinterpret_cast<v8::Isolate*>(isolate_);
    v8::SharedValueConveyor v8_conveyor(v8_isolate);
    shared_object_conveyor_ = v8_conveyor.private_.get();
    if (!delegate_->AdoptSharedValueConveyor(v8_isolate,
                                             std::move(v8_conveyor))) {
      shared_object_conveyor_ = nullptr;
      RETURN_VALUE_IF_EXCEPTION(isolate_, Nothing<bool>());
      return Nothing<bool>();
    }
  }
  WriteTag(SerializationTag::kSharedObject);
  WriteVarint(shared_object_conveyor_->Persist(*object));
  return ThrowIfOutOfMemory();
}
References v8::ValueSerializer::Delegate::AdoptSharedValueConveyor(), v8::internal::DCHECK(), delegate_, v8::internal::Isolate::has_shared_space(), isolate_, v8::internal::IsShared(), v8::internal::kSharedObject, v8::internal::SharedObjectConveyorHandles::Persist(), v8::SharedValueConveyor::private_, RETURN_VALUE_IF_EXCEPTION, shared_object_conveyor_, ThrowDataCloneError(), ThrowIfOutOfMemory(), WriteTag(), and WriteVarint().
Referenced by WriteJSReceiver(), WriteJSSharedArray(), and WriteJSSharedStruct().
WriteSmi()
void v8::internal::ValueSerializer::WriteSmi (Tagged< Smi > smi) [private]
Definition at line 543 of file value-serializer.cc.
                                              {
  static_assert(kSmiValueSize <= 32, "Expected SMI <= 32 bits.");
  WriteTag(SerializationTag::kInt32);
  WriteZigZag<int32_t>(smi.value());
}
References v8::internal::kInt32, v8::internal::kSmiValueSize, v8::internal::Tagged< Smi >::value(), and WriteTag().
Referenced by WriteJSArray(), and WriteObject().
WriteString()
void v8::internal::ValueSerializer::WriteString (DirectHandle< String > string) [private]
Definition at line 559 of file value-serializer.cc.
                                                             {
  string = String::Flatten(isolate_, string);
  DisallowGarbageCollection no_gc;
  String::FlatContent flat = string->GetFlatContent(no_gc);
  DCHECK(flat.IsFlat());
  if (flat.IsOneByte()) {
    base::Vector<const uint8_t> chars = flat.ToOneByteVector();
    WriteTag(SerializationTag::kOneByteString);
    WriteOneByteString(chars);
  } else if (flat.IsTwoByte()) {
    base::Vector<const base::uc16> chars = flat.ToUC16Vector();
    uint32_t byte_length = chars.length() * sizeof(base::uc16);
    // The existing reading code expects 16-byte strings to be aligned.
    if ((buffer_size_ + 1 + BytesNeededForVarint(byte_length)) & 1)
      WriteTag(SerializationTag::kPadding);
    WriteTag(SerializationTag::kTwoByteString);
    WriteTwoByteString(chars);
  } else {
    UNREACHABLE();
  }
}
References buffer_size_, v8::internal::BytesNeededForVarint(), v8::internal::DCHECK(), v8::internal::String::FlatContent::IsFlat(), isolate_, v8::internal::String::FlatContent::IsOneByte(), v8::internal::String::FlatContent::IsTwoByte(), v8::internal::kOneByteString, v8::internal::kPadding, v8::internal::kTwoByteString, v8::base::Vector< T >::length(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::String::FlatContent::ToOneByteVector(), v8::internal::String::FlatContent::ToUC16Vector(), v8::internal::UNREACHABLE(), WriteOneByteString(), WriteTag(), and WriteTwoByteString().
Referenced by WriteJSError(), WriteJSPrimitiveWrapper(), WriteJSRegExp(), and WriteObject().
WriteTag()
void v8::internal::ValueSerializer::WriteTag (SerializationTag tag) [private]
Definition at line 328 of file value-serializer.cc.
                                                   {
  uint8_t raw_tag = static_cast<uint8_t>(tag);
  WriteRawBytes(&raw_tag, sizeof(raw_tag));
}
References WriteRawBytes().
Referenced by WriteBigInt(), WriteHeader(), WriteHeapNumber(), WriteHostObject(), WriteJSArray(), WriteJSArrayBuffer(), WriteJSArrayBufferView(), WriteJSDate(), WriteJSError(), WriteJSMap(), WriteJSObject(), WriteJSObjectSlow(), WriteJSPrimitiveWrapper(), WriteJSReceiver(), WriteJSRegExp(), WriteJSSet(), WriteOddball(), WriteSharedObject(), WriteSmi(), and WriteString().
WriteTwoByteString()
void v8::internal::ValueSerializer::WriteTwoByteString (base::Vector< const base::uc16 > chars) [private]
Definition at line 378 of file value-serializer.cc.
                                                                         {
  // Warning: this uses host endianness.
  WriteVarint<uint32_t>(chars.length() * sizeof(base::uc16));
  WriteRawBytes(chars.begin(), chars.length() * sizeof(base::uc16));
}
References v8::base::Vector< T >::begin(), v8::base::Vector< T >::length(), and WriteRawBytes().
Referenced by WriteString().
WriteUint32()
void v8::internal::ValueSerializer::WriteUint32 (uint32_t value)
Definition at line 445 of file value-serializer.cc.
                                                {
  WriteVarint<uint32_t>(value);
}
References v8::internal::value.
Referenced by v8::ValueSerializer::WriteUint32().
WriteUint64()
void v8::internal::ValueSerializer::WriteUint64 (uint64_t value)
Definition at line 449 of file value-serializer.cc.
                                                {
  WriteVarint<uint64_t>(value);
}
References v8::internal::value.
Referenced by v8::ValueSerializer::WriteUint64().
WriteVarint()
template<typename T >
void v8::internal::ValueSerializer::WriteVarint (T value) [private]
Definition at line 334 of file value-serializer.cc.
                                         {
  // Writes an unsigned integer as a base-128 varint.
  // The number is written, 7 bits at a time, from the least significant to the
  // most significant 7 bits. Each byte, except the last, has the MSB set.
  // See also https://developers.google.com/protocol-buffers/docs/encoding
  static_assert(std::is_integral_v<T> && std::is_unsigned_v<T>,
                "Only unsigned integer types can be written as varints.");
  uint8_t stack_buffer[sizeof(T) * 8 / 7 + 1];
  uint8_t* next_byte = &stack_buffer[0];
  do {
    *next_byte = (value & 0x7F) | 0x80;
    next_byte++;
    value >>= 7;
  } while (value);
  *(next_byte - 1) &= 0x7F;
  WriteRawBytes(stack_buffer, next_byte - stack_buffer);
}
References T, v8::internal::value, and WriteRawBytes().
Referenced by WriteHeader(), WriteJSArrayBuffer(), WriteJSArrayBufferView(), WriteJSError(), WriteJSReceiver(), WriteJSRegExp(), WriteSharedObject(), and WriteZigZag().
WriteZigZag()
template<typename T >
void v8::internal::ValueSerializer::WriteZigZag (T value) [private]
Definition at line 353 of file value-serializer.cc.
                                         {
  // Writes a signed integer as a varint using ZigZag encoding (i.e. 0 is
  // encoded as 0, -1 as 1, 1 as 2, -2 as 3, and so on).
  // See also https://developers.google.com/protocol-buffers/docs/encoding
  // Note that this implementation relies on the right shift being arithmetic.
  static_assert(std::is_integral_v<T> && std::is_signed_v<T>,
                "Only signed integer types can be written as zigzag.");
  using UnsignedT = std::make_unsigned_t<T>;
  WriteVarint((static_cast<UnsignedT>(value) << 1) ^
              (value >> (8 * sizeof(T) - 1)));
}
References v8::internal::value, and WriteVarint().
Member Data Documentation
array_buffer_transfer_map_
IdentityMap<uint32_t, ZoneAllocationPolicy> v8::internal::ValueSerializer::array_buffer_transfer_map_ [private]
Definition at line 193 of file value-serializer.h.
Referenced by TransferArrayBuffer(), and WriteJSArrayBuffer().
buffer_
uint8_t* v8::internal::ValueSerializer::buffer_ = nullptr [private]
Definition at line 178 of file value-serializer.h.
Referenced by ExpandBuffer(), Release(), ReserveRawBytes(), and ~ValueSerializer().
buffer_capacity_
size_t v8::internal::ValueSerializer::buffer_capacity_ = 0 [private]
Definition at line 180 of file value-serializer.h.
Referenced by ExpandBuffer(), Release(), and ReserveRawBytes().
buffer_size_
size_t v8::internal::ValueSerializer::buffer_size_ = 0 [private]
Definition at line 179 of file value-serializer.h.
Referenced by Release(), ReserveRawBytes(), and WriteString().
delegate_
v8::ValueSerializer::Delegate* const v8::internal::ValueSerializer::delegate_ [private]
Definition at line 177 of file value-serializer.h.
Referenced by ExpandBuffer(), IsHostObject(), ThrowDataCloneError(), ValueSerializer(), WriteHostObject(), WriteJSArrayBuffer(), WriteSharedObject(), and ~ValueSerializer().
has_custom_host_objects_
bool v8::internal::ValueSerializer::has_custom_host_objects_ = false [private]
Definition at line 181 of file value-serializer.h.
Referenced by IsHostObject(), and ValueSerializer().
id_map_
IdentityMap<uint32_t, ZoneAllocationPolicy> v8::internal::ValueSerializer::id_map_ [private]
Definition at line 189 of file value-serializer.h.
Referenced by WriteJSArrayBuffer(), WriteJSReceiver(), and WriteObject().
isolate_
Isolate* const v8::internal::ValueSerializer::isolate_ [private]
Definition at line 176 of file value-serializer.h.
Referenced by IsHostObject(), ThrowDataCloneError(), ValueSerializer(), WriteHostObject(), WriteJSArray(), WriteJSArrayBuffer(), WriteJSArrayBufferView(), WriteJSError(), WriteJSMap(), WriteJSObject(), WriteJSObjectPropertiesSlow(), WriteJSObjectSlow(), WriteJSPrimitiveWrapper(), WriteJSReceiver(), WriteJSRegExp(), WriteJSSet(), WriteObject(), WriteSharedObject(), and WriteString().
next_id_
uint32_t v8::internal::ValueSerializer::next_id_ = 0 [private]
Definition at line 190 of file value-serializer.h.
Referenced by WriteJSReceiver().
out_of_memory_
bool v8::internal::ValueSerializer::out_of_memory_ = false [private]
Definition at line 183 of file value-serializer.h.
Referenced by ExpandBuffer(), IsHostObject(), ThrowIfOutOfMemory(), and WriteObject().
shared_object_conveyor_
SharedObjectConveyorHandles* v8::internal::ValueSerializer::shared_object_conveyor_ = nullptr [private]
Definition at line 196 of file value-serializer.h.
Referenced by WriteSharedObject().
treat_array_buffer_views_as_host_objects_
bool v8::internal::ValueSerializer::treat_array_buffer_views_as_host_objects_ = false [private]
Definition at line 182 of file value-serializer.h.
Referenced by SetTreatArrayBufferViewsAsHostObjects(), WriteJSArrayBufferView(), and WriteObject().
zone_
Zone v8::internal::ValueSerializer::zone_ [private]
Definition at line 184 of file value-serializer.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/value-serializer.h
/mnt/V8SourceCode/src/objects/value-serializer.cc