v8::internal::wasm::gdb_server::WasmModuleDebug Class Reference
#include <wasm-module-debug.h>
Public Member Functions
WasmModuleDebug (v8::Isolate *isolate, Local< debug::WasmScript > script)
std::string GetModuleName () const
i::Isolate * GetIsolate () const
uint32_t GetWasmMemory (Isolate *isolate, uint32_t offset, uint8_t *buffer, uint32_t size)
uint32_t GetWasmData (Isolate *isolate, uint32_t offset, uint8_t *buffer, uint32_t size)
uint32_t GetWasmModuleBytes (wasm_addr_t wasm_addr, uint8_t *buffer, uint32_t size)
bool AddBreakpoint (uint32_t offset, int *breakpoint_id)
void RemoveBreakpoint (uint32_t offset, int breakpoint_id)
void PrepareStep ()
Static Public Member Functions
static bool GetWasmGlobal (Isolate *isolate, uint32_t frame_index, uint32_t index, uint8_t *buffer, uint32_t buffer_size, uint32_t *size)
static bool GetWasmLocal (Isolate *isolate, uint32_t frame_index, uint32_t index, uint8_t *buffer, uint32_t buffer_size, uint32_t *size)
static bool GetWasmStackValue (Isolate *isolate, uint32_t frame_index, uint32_t index, uint8_t *buffer, uint32_t buffer_size, uint32_t *size)
static std::vector< wasm_addr_t > GetCallStack (uint32_t debug_context_id, Isolate *isolate)
Private Member Functions
Handle< WasmInstanceObject > GetFirstWasmInstance ()
Static Private Member Functions
static Handle< WasmInstanceObject > GetWasmInstance (Isolate *isolate, uint32_t frame_index)
static std::vector< FrameSummary > FindWasmFrame (DebuggableStackFrameIterator *frame_it, uint32_t *frame_index)
static bool GetWasmValue (const wasm::WasmValue &wasm_value, uint8_t *buffer, uint32_t buffer_size, uint32_t *size)
Private Attributes
v8::Isolate * isolate_
Global< debug::WasmScript > wasm_script_
Detailed Description
Definition at line 23 of file wasm-module-debug.h.
Constructor & Destructor Documentation
WasmModuleDebug()
v8::internal::wasm::gdb_server::WasmModuleDebug::WasmModuleDebug (v8::Isolate * isolate, Local< debug::WasmScript > script)
Definition at line 21 of file wasm-module-debug.cc.
                                                                     {
  DCHECK_EQ(Script::Type::kWasm, Utils::OpenHandle(*wasm_script)->type());
  isolate_ = isolate;
  wasm_script_ = Global<debug::WasmScript>(isolate, wasm_script);
}
References DCHECK_EQ, isolate_, v8::Utils::OpenHandle(), and wasm_script_.
Member Function Documentation
AddBreakpoint()
bool v8::internal::wasm::gdb_server::WasmModuleDebug::AddBreakpoint (uint32_t offset, int * breakpoint_id)
Definition at line 359 of file wasm-module-debug.cc.
                                                                       {
  v8::Local<debug::WasmScript> wasm_script = wasm_script_.Get(isolate_);
  Handle<Script> script = Utils::OpenHandle(*wasm_script);
  Handle<String> condition = GetIsolate()->factory()->empty_string();
  int breakpoint_address = static_cast<int>(offset);
  return GetIsolate()->debug()->SetBreakPointForScript(
      script, condition, &breakpoint_address, breakpoint_id);
}
References v8::internal::Isolate::debug(), v8::internal::Isolate::factory(), v8::PersistentBase< T >::Get(), GetIsolate(), isolate_, v8::Utils::OpenHandle(), v8::internal::script, v8::internal::Debug::SetBreakPointForScript(), and wasm_script_.
Referenced by v8::internal::wasm::gdb_server::GdbServer::AddBreakpoint().
FindWasmFrame()
std::vector< FrameSummary > v8::internal::wasm::gdb_server::WasmModuleDebug::FindWasmFrame (DebuggableStackFrameIterator * frame_it, uint32_t * frame_index) [static], [private]
Definition at line 148 of file wasm-module-debug.cc.
                                                                   {
  while (!frame_it->done()) {
    StackFrame* const frame = frame_it->frame();
    switch (frame->type()) {
      case StackFrame::JAVASCRIPT_BUILTIN_CONTINUATION:
      case StackFrame::JAVASCRIPT_BUILTIN_CONTINUATION_WITH_CATCH:
      case StackFrame::INTERPRETED:
      case StackFrame::BASELINE:
      case StackFrame::MAGLEV:
      case StackFrame::TURBOFAN_JS:
      case StackFrame::BUILTIN:
      case StackFrame::WASM: {
        // A standard frame may include many summarized frames, due to inlining.
        FrameSummaries summaries = CommonFrame::cast(frame)->Summarize();
        const size_t frame_count = summaries.size();
        DCHECK_GT(frame_count, 0);
        if (frame_count > *frame_index) {
#if V8_ENABLE_DRUMBRAKE
          if (frame_it->is_wasm() && !frame_it->is_wasm_interpreter_entry())
#else // V8_ENABLE_DRUMBRAKE
          if (frame_it->is_wasm())
#endif // V8_ENABLE_DRUMBRAKE
            return summaries.frames;
          else
            return {};
        } else {
          *frame_index -= frame_count;
          frame_it->Advance();
        }
        break;
      }
      case StackFrame::BUILTIN_EXIT:
      default:
        // ignore the frame.
        break;
    }
  }
  return {};
}
References v8::internal::DebuggableStackFrameIterator::Advance(), BUILTIN, v8::internal::CommonFrame::cast(), DCHECK_GT, v8::internal::DebuggableStackFrameIterator::done(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::FrameSummaries::frames, v8::internal::FrameSummaries::size(), v8::internal::CommonFrame::Summarize(), and v8::internal::StackFrame::type().
Referenced by GetWasmInstance(), GetWasmLocal(), and GetWasmStackValue().
GetCallStack()
std::vector< wasm_addr_t > v8::internal::wasm::gdb_server::WasmModuleDebug::GetCallStack (uint32_t debug_context_id, Isolate * isolate) [static]
Definition at line 87 of file wasm-module-debug.cc.
                                                 {
  std::vector<wasm_addr_t> call_stack;
  for (StackFrameIterator frame_it(isolate); !frame_it.done();
       frame_it.Advance()) {
    StackFrame* const frame = frame_it.frame();
    switch (frame->type()) {
      case StackFrame::JAVASCRIPT_BUILTIN_CONTINUATION:
      case StackFrame::JAVASCRIPT_BUILTIN_CONTINUATION_WITH_CATCH:
      case StackFrame::INTERPRETED:
      case StackFrame::BASELINE:
      case StackFrame::MAGLEV:
      case StackFrame::TURBOFAN_JS:
      case StackFrame::BUILTIN:
      case StackFrame::WASM: {
        // A standard frame may include many summarized frames, due to inlining.
        FrameSummaries summaries = CommonFrame::cast(frame)->Summarize();
        for (size_t i = summaries.size(); i-- != 0;) {
          int offset = 0;
          Handle<Script> script;
          auto& summary = summaries.frames[i];
          if (summary.IsJavaScript()) {
            FrameSummary::JavaScriptFrameSummary const& javascript =
                summary.AsJavaScript();
            offset = javascript.code_offset();
            script = Cast<Script>(javascript.script());
          } else if (summary.IsWasm()) {
            FrameSummary::WasmFrameSummary const& wasm = summary.AsWasm();
            offset = GetWasmFunctionOffset(wasm.wasm_instance()->module(),
                                           wasm.function_index()) +
                     wasm.code_offset();
            script = wasm.script();
            bool zeroth_frame = call_stack.empty();
            if (!zeroth_frame) {
              const NativeModule* native_module =
                  wasm.wasm_instance()->module_object().native_module();
              offset = ReturnPc(native_module, offset);
            }
          }
          if (offset > 0) {
            call_stack.push_back(
                {debug_context_id << 16 | script->id(), uint32_t(offset)});
          }
        }
        break;
      }
      case StackFrame::BUILTIN_EXIT:
      default:
        // ignore the frame.
        break;
    }
  }
  if (call_stack.empty()) call_stack.push_back({1, 0});
  return call_stack;
}
References BUILTIN, v8::internal::CommonFrame::cast(), v8::internal::FrameSummary::JavaScriptFrameSummary::code_offset(), v8::internal::StackFrameIteratorBase::done(), v8::internal::FrameSummaries::frames, v8::internal::wasm::GetWasmFunctionOffset(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::wasm::gdb_server::ReturnPc(), v8::internal::FrameSummary::JavaScriptFrameSummary::script(), v8::internal::script, v8::internal::FrameSummaries::size(), v8::internal::CommonFrame::Summarize(), and v8::internal::StackFrame::type().
Referenced by v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::BreakProgramRequested(), and v8::internal::wasm::gdb_server::GdbServer::DebugDelegate::ExceptionThrown().
GetFirstWasmInstance()
Handle< WasmInstanceObject > v8::internal::wasm::gdb_server::WasmModuleDebug::GetFirstWasmInstance () [private]
Definition at line 39 of file wasm-module-debug.cc.
                                                                 {
  v8::Local<debug::WasmScript> wasm_script = wasm_script_.Get(isolate_);
  Handle<Script> script = Utils::OpenHandle(*wasm_script);
  Handle<WeakArrayList> weak_instance_list(script->wasm_weak_instance_list(),
                                           GetIsolate());
  if (weak_instance_list->length() > 0) {
    Tagged<MaybeObject> maybe_instance = weak_instance_list->Get(0);
    if (maybe_instance.IsWeak()) {
      Handle<WasmInstanceObject> instance(
          Cast<WasmInstanceObject>(maybe_instance.GetHeapObjectAssumeWeak()),
          GetIsolate());
      return instance;
    }
  }
  return Handle<WasmInstanceObject>::null();
}
References v8::PersistentBase< T >::Get(), v8::internal::TaggedImpl< kRefType, StorageType >::GetHeapObjectAssumeWeak(), GetIsolate(), isolate_, v8::internal::TaggedImpl< kRefType, StorageType >::IsWeak(), v8::internal::Handle< T >::null(), v8::Utils::OpenHandle(), v8::internal::script, and wasm_script_.
Referenced by GetWasmData(), GetWasmMemory(), and GetWasmModuleBytes().
GetIsolate()
i::Isolate* v8::internal::wasm::gdb_server::WasmModuleDebug::GetIsolate () const [inline]
Definition at line 28 of file wasm-module-debug.h.
                               {
    return reinterpret_cast<i::Isolate*>(isolate_);
  }
References isolate_.
Referenced by AddBreakpoint(), GetFirstWasmInstance(), GetWasmModuleBytes(), PrepareStep(), and RemoveBreakpoint().
GetModuleName()
std::string v8::internal::wasm::gdb_server::WasmModuleDebug::GetModuleName () const
Definition at line 29 of file wasm-module-debug.cc.
                                               {
  v8::Local<debug::WasmScript> wasm_script = wasm_script_.Get(isolate_);
  v8::Local<v8::String> name;
  std::string module_name;
  if (wasm_script->Name().ToLocal(&name)) {
    module_name = *(v8::String::Utf8Value(isolate_, name));
  }
  return module_name;
}
References v8::PersistentBase< T >::Get(), isolate_, v8::internal::wasm::name(), v8::internal::string, and wasm_script_.
Referenced by v8::internal::wasm::gdb_server::GdbServer::GetLoadedModules().
GetWasmData()
uint32_t v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmData (Isolate * isolate, uint32_t offset, uint8_t * buffer, uint32_t size)
Definition at line 311 of file wasm-module-debug.cc.
                                                                      {
  HandleScope handles(isolate);
  uint32_t bytes_read = 0;
  Handle<WasmInstanceObject> instance = GetFirstWasmInstance();
  if (!instance.is_null()) {
    Handle<WasmModuleObject> module_object(instance->module_object(), isolate);
    const wasm::WasmModule* module = module_object->module();
    if (!module->data_segments.empty()) {
      const WasmDataSegment& segment = module->data_segments[0];
      uint32_t data_offset = EvalUint32InitExpr(instance, segment.dest_addr);
      offset += data_offset;
      uint8_t* mem_start = instance->memory_start();
      size_t mem_size = instance->memory_size();
      if (static_cast<uint64_t>(offset) + size <= mem_size) {
        memcpy(buffer, mem_start + offset, size);
        bytes_read = size;
      } else if (offset < mem_size) {
        bytes_read = static_cast<uint32_t>(mem_size) - offset;
        memcpy(buffer, mem_start + offset, bytes_read);
      }
    }
  }
  return bytes_read;
}
References v8::internal::wasm::WasmModule::data_segments, v8::internal::wasm::WasmDataSegment::dest_addr, GetFirstWasmInstance(), v8::internal::HandleBase::is_null(), and size().
Referenced by v8::internal::wasm::gdb_server::GdbServer::GetWasmData().
GetWasmGlobal()
bool v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmGlobal (Isolate * isolate, uint32_t frame_index, uint32_t index, uint8_t * buffer, uint32_t buffer_size, uint32_t * size) [static]
Definition at line 207 of file wasm-module-debug.cc.
                                                                          {
  HandleScope handles(isolate);
  Handle<WasmInstanceObject> instance = GetWasmInstance(isolate, frame_index);
  if (!instance.is_null()) {
    Handle<WasmModuleObject> module_object(instance->module_object(), isolate);
    const wasm::WasmModule* module = module_object->module();
    if (index < module->globals.size()) {
      wasm::WasmValue wasm_value =
          WasmInstanceObject::GetGlobalValue(instance, module->globals[index]);
      return GetWasmValue(wasm_value, buffer, buffer_size, size);
    }
  }
  return false;
}
References GetWasmInstance(), GetWasmValue(), v8::internal::wasm::WasmModule::globals, v8::internal::index, v8::internal::HandleBase::is_null(), and size().
Referenced by v8::internal::wasm::gdb_server::GdbServer::GetWasmGlobal().
GetWasmInstance()
Handle< WasmInstanceObject > v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmInstance (Isolate * isolate, uint32_t frame_index) [static], [private]
Definition at line 192 of file wasm-module-debug.cc.
                                            {
  DebuggableStackFrameIterator frame_it(isolate);
  std::vector<FrameSummary> frames = FindWasmFrame(&frame_it, &frame_index);
  if (frames.empty()) {
    return Handle<WasmInstanceObject>::null();
  }
  int reversed_index = static_cast<int>(frames.size() - 1 - frame_index);
  const FrameSummary::WasmFrameSummary& summary =
      frames[reversed_index].AsWasm();
  return summary.wasm_instance();
}
References FindWasmFrame(), and v8::internal::Handle< T >::null().
Referenced by GetWasmGlobal().
GetWasmLocal()
bool v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmLocal (Isolate * isolate, uint32_t frame_index, uint32_t index, uint8_t * buffer, uint32_t buffer_size, uint32_t * size) [static]
Definition at line 226 of file wasm-module-debug.cc.
                                                                         {
  HandleScope handles(isolate);
  DebuggableStackFrameIterator frame_it(isolate);
  std::vector<FrameSummary> frames = FindWasmFrame(&frame_it, &frame_index);
  if (frames.empty()) {
    return false;
  }
  int reversed_index = static_cast<int>(frames.size() - 1 - frame_index);
  const FrameSummary& summary = frames[reversed_index];
  if (summary.IsWasm()) {
    Handle<WasmInstanceObject> instance = summary.AsWasm().wasm_instance();
    if (!instance.is_null()) {
      Handle<WasmModuleObject> module_object(instance->module_object(),
                                             isolate);
      wasm::NativeModule* native_module = module_object->native_module();
      DebugInfo* debug_info = native_module->GetDebugInfo();
      if (static_cast<uint32_t>(
              debug_info->GetNumLocals(frame_it.frame()->pc())) > index) {
        wasm::WasmValue wasm_value = debug_info->GetLocalValue(
            index, frame_it.frame()->pc(), frame_it.frame()->fp(),
            frame_it.frame()->callee_fp());
        return GetWasmValue(wasm_value, buffer, buffer_size, size);
      }
    }
  }
  return false;
}
References v8::internal::StackFrame::callee_fp(), FindWasmFrame(), v8::internal::StackFrame::fp(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::wasm::NativeModule::GetDebugInfo(), v8::internal::wasm::DebugInfo::GetLocalValue(), v8::internal::wasm::DebugInfo::GetNumLocals(), GetWasmValue(), v8::internal::index, v8::internal::HandleBase::is_null(), v8::internal::StackFrame::pc(), and size().
Referenced by v8::internal::wasm::gdb_server::GdbServer::GetWasmLocal().
GetWasmMemory()
uint32_t v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmMemory (Isolate * isolate, uint32_t offset, uint8_t * buffer, uint32_t size)
Definition at line 291 of file wasm-module-debug.cc.
                                                                        {
  HandleScope handles(isolate);
  uint32_t bytes_read = 0;
  Handle<WasmInstanceObject> instance = GetFirstWasmInstance();
  if (!instance.is_null()) {
    uint8_t* mem_start = instance->memory_start();
    size_t mem_size = instance->memory_size();
    if (static_cast<uint64_t>(offset) + size <= mem_size) {
      memcpy(buffer, mem_start + offset, size);
      bytes_read = size;
    } else if (offset < mem_size) {
      bytes_read = static_cast<uint32_t>(mem_size) - offset;
      memcpy(buffer, mem_start + offset, bytes_read);
    }
  }
  return bytes_read;
}
References GetFirstWasmInstance(), v8::internal::HandleBase::is_null(), and size().
Referenced by v8::internal::wasm::gdb_server::GdbServer::GetWasmMemory().
GetWasmModuleBytes()
uint32_t v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmModuleBytes (wasm_addr_t wasm_addr, uint8_t * buffer, uint32_t size)
Definition at line 339 of file wasm-module-debug.cc.
                                                                             {
  uint32_t bytes_read = 0;
  // Any instance will work.
  Handle<WasmInstanceObject> instance = GetFirstWasmInstance();
  if (!instance.is_null()) {
    Handle<WasmModuleObject> module_object(instance->module_object(),
                                           GetIsolate());
    wasm::NativeModule* native_module = module_object->native_module();
    const wasm::ModuleWireBytes wire_bytes(native_module->wire_bytes());
    uint32_t offset = wasm_addr.Offset();
    if (offset < wire_bytes.length()) {
      uint32_t module_size = static_cast<uint32_t>(wire_bytes.length());
      bytes_read = module_size - offset >= size ? size : module_size - offset;
      memcpy(buffer, wire_bytes.start() + offset, bytes_read);
    }
  }
  return bytes_read;
}
References GetFirstWasmInstance(), GetIsolate(), v8::internal::HandleBase::is_null(), v8::internal::wasm::ModuleWireBytes::length(), v8::internal::wasm::gdb_server::wasm_addr_t::Offset(), size(), v8::internal::wasm::ModuleWireBytes::start(), and v8::internal::wasm::NativeModule::wire_bytes().
GetWasmStackValue()
bool v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmStackValue (Isolate * isolate, uint32_t frame_index, uint32_t index, uint8_t * buffer, uint32_t buffer_size, uint32_t * size) [static]
Definition at line 259 of file wasm-module-debug.cc.
                                                                              {
  HandleScope handles(isolate);
  DebuggableStackFrameIterator frame_it(isolate);
  std::vector<FrameSummary> frames = FindWasmFrame(&frame_it, &frame_index);
  if (frames.empty()) {
    return false;
  }
  int reversed_index = static_cast<int>(frames.size() - 1 - frame_index);
  const FrameSummary& summary = frames[reversed_index];
  if (summary.IsWasm()) {
    Handle<WasmInstanceObject> instance = summary.AsWasm().wasm_instance();
    if (!instance.is_null()) {
      Handle<WasmModuleObject> module_object(instance->module_object(),
                                             isolate);
      wasm::NativeModule* native_module = module_object->native_module();
      DebugInfo* debug_info = native_module->GetDebugInfo();
      if (static_cast<uint32_t>(
              debug_info->GetStackDepth(frame_it.frame()->pc())) > index) {
        WasmValue wasm_value = debug_info->GetStackValue(
            index, frame_it.frame()->pc(), frame_it.frame()->fp(),
            frame_it.frame()->callee_fp());
        return GetWasmValue(wasm_value, buffer, buffer_size, size);
      }
    }
  }
  return false;
}
References v8::internal::StackFrame::callee_fp(), FindWasmFrame(), v8::internal::StackFrame::fp(), v8::internal::DebuggableStackFrameIterator::frame(), v8::internal::wasm::NativeModule::GetDebugInfo(), v8::internal::wasm::DebugInfo::GetStackDepth(), v8::internal::wasm::DebugInfo::GetStackValue(), GetWasmValue(), v8::internal::index, v8::internal::HandleBase::is_null(), v8::internal::StackFrame::pc(), and size().
Referenced by v8::internal::wasm::gdb_server::GdbServer::GetWasmStackValue().
GetWasmValue()
bool v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmValue (const wasm::WasmValue & wasm_value, uint8_t * buffer, uint32_t buffer_size, uint32_t * size) [static], [private]
Definition at line 391 of file wasm-module-debug.cc.
                                                   {
  switch (wasm_value.type().kind()) {
    case wasm::kI32:
      return StoreValue(wasm_value.to_i32(), buffer, buffer_size, size);
    case wasm::kI64:
      return StoreValue(wasm_value.to_i64(), buffer, buffer_size, size);
    case wasm::kF32:
      return StoreValue(wasm_value.to_f32(), buffer, buffer_size, size);
    case wasm::kF64:
      return StoreValue(wasm_value.to_f64(), buffer, buffer_size, size);
    case wasm::kS128:
      return StoreValue(wasm_value.to_s128(), buffer, buffer_size, size);
    case wasm::kRef:
    case wasm::kRefNull:
    case wasm::kVoid:
    case wasm::kBottom:
      // Not supported
      return false;
  }
}
References v8::internal::wasm::ValueTypeBase::kind(), size(), v8::internal::wasm::gdb_server::StoreValue(), and v8::internal::wasm::WasmValue::type().
Referenced by GetWasmGlobal(), GetWasmLocal(), and GetWasmStackValue().
PrepareStep()
void v8::internal::wasm::gdb_server::WasmModuleDebug::PrepareStep ()
Definition at line 374 of file wasm-module-debug.cc.
                                  {
  i::Isolate* isolate = GetIsolate();
  DebugScope debug_scope(isolate->debug());
  debug::PrepareStep(reinterpret_cast<v8::Isolate*>(isolate),
                     debug::StepAction::StepInto);
}
References v8::internal::Isolate::debug(), GetIsolate(), v8::debug::PrepareStep(), and v8::debug::StepInto.
RemoveBreakpoint()
void v8::internal::wasm::gdb_server::WasmModuleDebug::RemoveBreakpoint (uint32_t offset, int breakpoint_id)
Definition at line 368 of file wasm-module-debug.cc.
                                                                         {
  v8::Local<debug::WasmScript> wasm_script = wasm_script_.Get(isolate_);
  Handle<Script> script = Utils::OpenHandle(*wasm_script);
  GetIsolate()->debug()->RemoveBreakpointForWasmScript(script, breakpoint_id);
}
References v8::internal::Isolate::debug(), v8::PersistentBase< T >::Get(), GetIsolate(), isolate_, v8::Utils::OpenHandle(), v8::internal::script, and wasm_script_.
Member Data Documentation
isolate_
v8::Isolate* v8::internal::wasm::gdb_server::WasmModuleDebug::isolate_ [private]
Definition at line 102 of file wasm-module-debug.h.
Referenced by AddBreakpoint(), GetFirstWasmInstance(), GetIsolate(), GetModuleName(), RemoveBreakpoint(), and WasmModuleDebug().
wasm_script_
Global<debug::WasmScript> v8::internal::wasm::gdb_server::WasmModuleDebug::wasm_script_ [private]
Definition at line 103 of file wasm-module-debug.h.
Referenced by AddBreakpoint(), GetFirstWasmInstance(), GetModuleName(), RemoveBreakpoint(), and WasmModuleDebug().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/debug/wasm/gdb-server/wasm-module-debug.h
/mnt/V8SourceCode/src/debug/wasm/gdb-server/wasm-module-debug.cc