v8::internal::AllocationTraceTree Class Reference
#include <allocation-tracker.h>
Public Member Functions
AllocationTraceTree ()
~AllocationTraceTree ()=default
AllocationTraceTree (const AllocationTraceTree &)=delete
AllocationTraceTree & operator= (const AllocationTraceTree &)=delete
AllocationTraceNode * AddPathFromEnd (base::Vector< const unsigned > path)
AllocationTraceNode * root ()
unsigned next_node_id ()
V8_EXPORT_PRIVATE void Print (AllocationTracker *tracker)
Private Attributes
unsigned next_node_id_
AllocationTraceNode root_
Detailed Description
Definition at line 63 of file allocation-tracker.h.
Constructor & Destructor Documentation
AllocationTraceTree() [1/2]
v8::internal::AllocationTraceTree::AllocationTraceTree ()
Definition at line 76 of file allocation-tracker.cc.
    : next_node_id_(1),
      root_(this, 0) {
}
 AllocationTraceTree()
v8::internal::AllocationTraceTree::~AllocationTraceTree () [default]
AllocationTraceTree() [2/2]
v8::internal::AllocationTraceTree::AllocationTraceTree (const AllocationTraceTree &) [delete]
Member Function Documentation
AddPathFromEnd()
AllocationTraceNode * v8::internal::AllocationTraceTree::AddPathFromEnd (base::Vector< const unsigned > path)
Definition at line 81 of file allocation-tracker.cc.
                                     {
  AllocationTraceNode* node = root();
  for (const unsigned* entry = path.begin() + path.length() - 1;
       entry != path.begin() - 1; --entry) {
    node = node->FindOrAddChild(*entry);
  }
  return node;
}
References v8::base::Vector< T >::begin(), v8::internal::AllocationTraceNode::FindOrAddChild(), v8::base::Vector< T >::length(), and root().
Referenced by v8::internal::AllocationTracker::AllocationEvent().
next_node_id()
unsigned v8::internal::AllocationTraceTree::next_node_id () [inline]
Definition at line 71 of file allocation-tracker.h.
{ return next_node_id_++; }
References next_node_id_.
operator=()
AllocationTraceTree& v8::internal::AllocationTraceTree::operator= (const AllocationTraceTree &) [delete]
Print()
void v8::internal::AllocationTraceTree::Print (AllocationTracker * tracker)
Definition at line 91 of file allocation-tracker.cc.
                                                          {
  base::OS::Print("[AllocationTraceTree:]\n");
  base::OS::Print("Total size | Allocation count | Function id | id\n");
  root()->Print(0, tracker);
}
References v8::internal::AllocationTraceNode::Print(), v8::internal::Print(), and root().
root()
AllocationTraceNode* v8::internal::AllocationTraceTree::root () [inline]
Definition at line 70 of file allocation-tracker.h.
{ return &root_; }
References root_.
Referenced by AddPathFromEnd(), Print(), and v8::internal::HeapSnapshotJSONSerializer::SerializeTraceTree().
Member Data Documentation
next_node_id_
unsigned v8::internal::AllocationTraceTree::next_node_id_ [private]
Definition at line 75 of file allocation-tracker.h.
Referenced by next_node_id().
root_
AllocationTraceNode v8::internal::AllocationTraceTree::root_ [private]
Definition at line 76 of file allocation-tracker.h.
Referenced by root().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/profiler/allocation-tracker.h
/mnt/V8SourceCode/src/profiler/allocation-tracker.cc