v8::internal::compiler::StateValuesAccess Class Reference
#include <state-values-utils.h>
Classes
class iterator
struct TypedNode
Public Member Functions
StateValuesAccess (Node *node)
size_t size () const
iterator begin () const
iterator begin_without_receiver () const
iterator begin_without_receiver_and_skip (int n_skips)
iterator end () const
Private Attributes
Node * node_
Detailed Description
Definition at line 82 of file state-values-utils.h.
Constructor & Destructor Documentation
StateValuesAccess()
v8::internal::compiler::StateValuesAccess::StateValuesAccess (Node * node) [inline], [explicit]
Definition at line 121 of file state-values-utils.h.
: node_(node) {}
Referenced by size().
Member Function Documentation
begin()
iterator v8::internal::compiler::StateValuesAccess::begin () const [inline]
Definition at line 124 of file state-values-utils.h.
{ return iterator(node_); }
Referenced by v8::internal::compiler::anonymous_namespace{escape-analysis.cc}::ReduceNode().
begin_without_receiver()
iterator v8::internal::compiler::StateValuesAccess::begin_without_receiver () const [inline]
Definition at line 125 of file state-values-utils.h.
                                          {
    return ++begin(); // Skip the receiver.
  }
References v8::internal::compiler::begin().
Referenced by v8::internal::compiler::JSCallReducer::ReduceJSConstructForwardAllArgs(), and v8::internal::compiler::JSCreateLowering::TryAllocateArguments().
begin_without_receiver_and_skip()
iterator v8::internal::compiler::StateValuesAccess::begin_without_receiver_and_skip (int n_skips) [inline]
Definition at line 128 of file state-values-utils.h.
                                                        {
    iterator it = begin_without_receiver();
    while (n_skips > 0 && !it.done()) {
      ++it;
      --n_skips;
    }
    return it;
  }
References v8::internal::compiler::StateValuesAccess::iterator::done().
Referenced by v8::internal::compiler::JSCallReducer::ReduceCallOrConstructWithArrayLikeOrSpreadOfCreateArguments(), v8::internal::compiler::JSCreateLowering::TryAllocateAliasedArguments(), and v8::internal::compiler::JSCreateLowering::TryAllocateRestArguments().
end()
iterator v8::internal::compiler::StateValuesAccess::end () const [inline]
Definition at line 136 of file state-values-utils.h.
{ return iterator(); }
size()
size_t v8::internal::compiler::StateValuesAccess::size () const
Definition at line 414 of file state-values-utils.cc.
                                     {
  size_t count = 0;
  SparseInputMask mask = SparseInputMaskOf(node_->op());
  SparseInputMask::InputIterator iterator = mask.IterateOverInputs(node_);
  for (; !iterator.IsEnd(); iterator.Advance()) {
    if (iterator.IsEmpty()) {
      count++;
    } else {
      Node* value = iterator.GetReal();
      if (value->opcode() == IrOpcode::kStateValues ||
          value->opcode() == IrOpcode::kTypedStateValues) {
        count += StateValuesAccess(value).size();
      } else {
        count++;
      }
    }
  }
  return count;
}
References v8::internal::compiler::StateValuesAccess::iterator::Advance(), v8::internal::compiler::SparseInputMask::IterateOverInputs(), node_, v8::internal::compiler::Node::op(), v8::internal::compiler::SparseInputMaskOf(), StateValuesAccess(), and v8::internal::value.
Referenced by v8::internal::compiler::Verifier::Visitor::Check().
Member Data Documentation
node_
Node* v8::internal::compiler::StateValuesAccess::node_ [private]
Definition at line 139 of file state-values-utils.h.
Referenced by size().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/state-values-utils.h
/mnt/V8SourceCode/src/compiler/state-values-utils.cc