v8::internal::compiler::TurbofanPipelineStatistics Class Reference
#include <pipeline-statistics.h>
Public Member Functions
TurbofanPipelineStatistics (OptimizedCompilationInfo *info, std::shared_ptr< CompilationStatistics > turbo_stats, ZoneStats *zone_stats)
~TurbofanPipelineStatistics ()
TurbofanPipelineStatistics (const TurbofanPipelineStatistics &)=delete
TurbofanPipelineStatistics & operator= (const TurbofanPipelineStatistics &)=delete
void BeginPhaseKind (const char *name)
void EndPhaseKind ()
void BeginPhase (const char *name)
void EndPhase ()
Static Public Attributes
static constexpr char kTraceCategory []
Additional Inherited Members
Detailed Description
Definition at line 96 of file pipeline-statistics.h.
Constructor & Destructor Documentation
TurbofanPipelineStatistics() [1/2]
v8::internal::compiler::TurbofanPipelineStatistics::TurbofanPipelineStatistics (OptimizedCompilationInfo * info, std::shared_ptr< CompilationStatistics > turbo_stats, ZoneStats * zone_stats)
Definition at line 109 of file pipeline-statistics.cc.
    : Base(info->zone(), zone_stats, compilation_stats, info->code_kind()) {
  if (info->has_shared_info()) {
    set_function_name(info->shared_info()->DebugNameCStr().get());
  }
}
References v8::internal::OptimizedCompilationInfo::has_shared_info(), v8::internal::compiler::PipelineStatisticsBase::set_function_name(), and v8::internal::OptimizedCompilationInfo::shared_info().
 TurbofanPipelineStatistics()
v8::internal::compiler::TurbofanPipelineStatistics::~TurbofanPipelineStatistics ()
Definition at line 119 of file pipeline-statistics.cc.
                                                        {
  if (Base::InPhaseKind()) EndPhaseKind();
}
References EndPhaseKind(), and v8::internal::compiler::PipelineStatisticsBase::InPhaseKind().
TurbofanPipelineStatistics() [2/2]
v8::internal::compiler::TurbofanPipelineStatistics::TurbofanPipelineStatistics (const TurbofanPipelineStatistics &) [delete]
Member Function Documentation
BeginPhase()
void v8::internal::compiler::TurbofanPipelineStatistics::BeginPhase (const char * name)
Definition at line 138 of file pipeline-statistics.cc.
                                                            {
  Base::BeginPhase(name);
  TRACE_EVENT_BEGIN1(kTraceCategory, phase_name(), "kind",
                     CodeKindToString(code_kind()));
}
References v8::internal::compiler::PipelineStatisticsBase::BeginPhase(), v8::internal::compiler::PipelineStatisticsBase::code_kind(), v8::internal::CodeKindToString(), kTraceCategory, v8::internal::name, v8::internal::compiler::PipelineStatisticsBase::phase_name(), and TRACE_EVENT_BEGIN1.
BeginPhaseKind()
void v8::internal::compiler::TurbofanPipelineStatistics::BeginPhaseKind (const char * name)
Definition at line 123 of file pipeline-statistics.cc.
                                                                {
  if (Base::InPhaseKind()) EndPhaseKind();
  Base::BeginPhaseKind(name);
  TRACE_EVENT_BEGIN1(kTraceCategory, name, "kind",
                     CodeKindToString(code_kind()));
}
References v8::internal::compiler::PipelineStatisticsBase::BeginPhaseKind(), v8::internal::compiler::PipelineStatisticsBase::code_kind(), v8::internal::CodeKindToString(), EndPhaseKind(), v8::internal::compiler::PipelineStatisticsBase::InPhaseKind(), kTraceCategory, v8::internal::name, and TRACE_EVENT_BEGIN1.
Referenced by v8::internal::compiler::TFPipelineData::BeginPhaseKind(), and v8::internal::compiler::anonymous_namespace{pipeline.cc}::CreatePipelineStatistics().
EndPhase()
void v8::internal::compiler::TurbofanPipelineStatistics::EndPhase ()
Definition at line 144 of file pipeline-statistics.cc.
                                          {
  CompilationStatistics::BasicStats diff;
  Base::EndPhase(&diff);
  TRACE_EVENT_END2(kTraceCategory, phase_name(), "kind",
                   CodeKindToString(code_kind()), "stats",
                   TRACE_STR_COPY(diff.AsJSON().c_str()));
}
References v8::internal::CompilationStatistics::BasicStats::AsJSON(), v8::internal::compiler::PipelineStatisticsBase::code_kind(), v8::internal::CodeKindToString(), v8::internal::compiler::PipelineStatisticsBase::EndPhase(), kTraceCategory, v8::internal::compiler::PipelineStatisticsBase::phase_name(), TRACE_EVENT_END2, and TRACE_STR_COPY.
EndPhaseKind()
void v8::internal::compiler::TurbofanPipelineStatistics::EndPhaseKind ()
Definition at line 130 of file pipeline-statistics.cc.
                                              {
  CompilationStatistics::BasicStats diff;
  Base::EndPhaseKind(&diff);
  TRACE_EVENT_END2(kTraceCategory, phase_kind_name(), "kind",
                   CodeKindToString(code_kind()), "stats",
                   TRACE_STR_COPY(diff.AsJSON().c_str()));
}
References v8::internal::CompilationStatistics::BasicStats::AsJSON(), v8::internal::compiler::PipelineStatisticsBase::code_kind(), v8::internal::CodeKindToString(), v8::internal::compiler::PipelineStatisticsBase::EndPhaseKind(), kTraceCategory, v8::internal::compiler::PipelineStatisticsBase::phase_kind_name(), TRACE_EVENT_END2, and TRACE_STR_COPY.
Referenced by BeginPhaseKind(), v8::internal::compiler::TFPipelineData::EndPhaseKind(), and ~TurbofanPipelineStatistics().
operator=()
TurbofanPipelineStatistics& v8::internal::compiler::TurbofanPipelineStatistics::operator= (const TurbofanPipelineStatistics &) [delete]
Member Data Documentation
kTraceCategory
constexpr char v8::internal::compiler::TurbofanPipelineStatistics::kTraceCategory [static], [constexpr]
Initial value:
=
      TRACE_DISABLED_BY_DEFAULT("v8.turbofan") ","
      TRACE_DISABLED_BY_DEFAULT("v8.wasm.turbofan")
Definition at line 109 of file pipeline-statistics.h.
Referenced by BeginPhase(), BeginPhaseKind(), EndPhase(), EndPhaseKind(), and v8::internal::compiler::anonymous_namespace{pipeline.cc}::TraceScheduleAndVerify().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/pipeline-statistics.h
/mnt/V8SourceCode/src/compiler/pipeline-statistics.cc