v8::internal::maglev::NodeTMixin< Base, Derived > Class Template Reference
#include <maglev-ir.h>
Public Member Functions
constexpr Opcode opcode () const
constexpr const OpProperties & properties () const
Static Public Member Functions
template<typename... Args>
static Derived * New (Zone *zone, std::initializer_list< ValueNode * > inputs, Args &&... args)
template<typename... Args>
static Derived * New (Zone *zone, size_t input_count, Args &&... args)
Protected Member Functions
template<typename... Args>
NodeTMixin (uint64_t bitfield, Args &&... args)
Detailed Description
template<typename Base, typename Derived>
class v8::internal::maglev::NodeTMixin< Base, Derived >
Definition at line 2942 of file maglev-ir.h.
Constructor & Destructor Documentation
NodeTMixin()
template<typename Base , typename Derived >
template<typename... Args>
v8::internal::maglev::NodeTMixin< Base, Derived >::NodeTMixin (uint64_t bitfield, Args &&... args) [inline], [explicit], [protected]
Definition at line 2962 of file maglev-ir.h.
      : Base(bitfield, std::forward<Args>(args)...) {
    DCHECK_EQ(this->NodeBase::opcode(), NodeBase::opcode_of<Derived>);
    DCHECK_EQ(this->NodeBase::properties(), Derived::kProperties);
  }
References DCHECK_EQ, v8::internal::maglev::NodeBase::opcode(), and v8::internal::maglev::NodeBase::properties().
Member Function Documentation
New() [1/2]
template<typename Base , typename Derived >
template<typename... Args>
static Derived* v8::internal::maglev::NodeTMixin< Base, Derived >::New (Zone * zone, size_t input_count, Args &&... args) [inline], [static]
Definition at line 2956 of file maglev-ir.h.
                                                                      {
    return NodeBase::New<Derived>(zone, input_count, std::forward<Args>...);
  }
References v8::internal::compiler::turboshaft::detail::input_count().
New() [2/2]
template<typename Base , typename Derived >
template<typename... Args>
static Derived* v8::internal::maglev::NodeTMixin< Base, Derived >::New (Zone * zone, std::initializer_list< ValueNode * > inputs, Args &&... args) [inline], [static]
Definition at line 2951 of file maglev-ir.h.
                                      {
    return NodeBase::New<Derived>(zone, inputs, std::forward<Args>...);
  }
opcode()
template<typename Base , typename Derived >
constexpr Opcode v8::internal::maglev::NodeTMixin< Base, Derived >::opcode () const [inline], [constexpr]
Definition at line 2945 of file maglev-ir.h.
{ return NodeBase::opcode_of<Derived>; }
Referenced by v8::internal::maglev::anonymous_namespace{maglev-ir.cc}::PrintImpl(), v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNodeInputs(), and v8::internal::maglev::MaglevPhiRepresentationSelector::UpdateNonUntaggingNodeInputs().
properties()
template<typename Base , typename Derived >
constexpr const OpProperties& v8::internal::maglev::NodeTMixin< Base, Derived >::properties () const [inline], [constexpr]
Definition at line 2946 of file maglev-ir.h.
                                                   {
    return Derived::kProperties;
  }
Referenced by v8::internal::maglev::anonymous_namespace{maglev-code-generator.cc}::MaglevCodeGeneratingNodeProcessor::Process(), v8::internal::maglev::LoopOptimizationProcessor::Process(), and v8::internal::maglev::LiveRangeAndNextUseProcessor::Process().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-ir.h