v8::internal::torque::CfgAssembler Class Reference
#include <cfg.h>
Public Member Functions
CfgAssembler (Stack< const Type * > input_types)
const ControlFlowGraph & Result ()
Block * NewBlock (std::optional< Stack< const Type * >> input_types=std::nullopt, bool is_deferred=false)
bool CurrentBlockIsComplete () const
bool CfgIsComplete () const
void Emit (Instruction instruction)
const Stack< const Type * > & CurrentStack () const
StackRange TopRange (size_t slot_count) const
void Bind (Block *block)
void Goto (Block *block)
StackRange Goto (Block *block, size_t preserved_slots)
void Branch (Block *if_true, Block *if_false)
void DeleteRange (StackRange range)
void DropTo (BottomOffset new_level)
StackRange Peek (StackRange range, std::optional< const Type * > type)
void Poke (StackRange destination, StackRange origin, std::optional< const Type * > type)
void Print (std::string s)
void AssertionFailure (std::string message)
void Unreachable ()
void DebugBreak ()
void PrintCurrentStack (std::ostream &s)
void OptimizeCfg ()
void ComputeInputDefinitions ()
Private Attributes
Stack< const Type * > current_stack_
ControlFlowGraph cfg_
Block * current_block_ = cfg_.start()
Friends
class CfgAssemblerScopedTemporaryBlock
Detailed Description
Definition at line 147 of file cfg.h.
Constructor & Destructor Documentation
CfgAssembler()
v8::internal::torque::CfgAssembler::CfgAssembler (Stack< const Type * > input_types) [inline], [explicit]
Definition at line 149 of file cfg.h.
      : current_stack_(std::move(input_types)), cfg_(current_stack_) {}
Member Function Documentation
AssertionFailure()
void v8::internal::torque::CfgAssembler::AssertionFailure (std::string message)
Definition at line 150 of file cfg.cc.
                                                     {
  Emit(AbortInstruction{AbortInstruction::Kind::kAssertionFailure,
                        std::move(message)});
}
References Emit(), and v8::internal::torque::AbortInstruction::kAssertionFailure.
Bind()
void v8::internal::torque::CfgAssembler::Bind (Block * block)
Definition at line 72 of file cfg.cc.
                                    {
  DCHECK(current_block_->IsComplete());
  DCHECK(block->instructions().empty());
  DCHECK(block->HasInputTypes());
  current_block_ = block;
  current_stack_ = block->InputTypes();
  cfg_.PlaceBlock(block);
}
References cfg_, current_block_, current_stack_, v8::internal::DCHECK(), v8::internal::torque::Block::HasInputTypes(), v8::internal::torque::Block::InputTypes(), v8::internal::torque::Block::instructions(), v8::internal::torque::Block::IsComplete(), and v8::internal::torque::ControlFlowGraph::PlaceBlock().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
Branch()
void v8::internal::torque::CfgAssembler::Branch (Block * if_true, Block * if_false)
Definition at line 99 of file cfg.cc.
                                                         {
  Emit(BranchInstruction{if_true, if_false});
}
References Emit().
CfgIsComplete()
bool v8::internal::torque::CfgAssembler::CfgIsComplete () const [inline]
Definition at line 168 of file cfg.h.
                             {
    return std::all_of(
        cfg_.blocks().begin(), cfg_.blocks().end(), [this](Block* block) {
          return (cfg_.end() && *cfg_.end() == block) || block->IsComplete();
        });
  }
References v8::base::all_of(), v8::internal::torque::ControlFlowGraph::blocks(), and cfg_.
Referenced by Result().
ComputeInputDefinitions()
void v8::internal::torque::CfgAssembler::ComputeInputDefinitions ()
Definition at line 212 of file cfg.cc.
                                           {
  Worklist<Block*> worklist;
  // Setup start block.
  Stack<DefinitionLocation> parameter_defs;
  for (std::size_t i = 0; i < cfg_.ParameterCount(); ++i) {
    parameter_defs.Push(DefinitionLocation::Parameter(i));
  }
  cfg_.start()->MergeInputDefinitions(parameter_defs, &worklist);
  // Run fixpoint algorithm.
  while (!worklist.IsEmpty()) {
    Block* block = worklist.Dequeue();
    Stack<DefinitionLocation> definitions = block->InputDefinitions();
    // Propagate through block's instructions.
    for (const auto& instruction : block->instructions()) {
      instruction.RecomputeDefinitionLocations(&definitions, &worklist);
    }
  }
  for (Block* block : cfg_.blocks()) {
    DCHECK_IMPLIES(!block->IsDead(), block->InputDefinitions().Size() ==
                                         block->InputTypes().Size());
    USE(block);
  }
}
References v8::internal::torque::ControlFlowGraph::blocks(), cfg_, DCHECK_IMPLIES, v8::internal::torque::Worklist< T >::Dequeue(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::Block::InputDefinitions(), v8::internal::torque::Block::instructions(), v8::internal::torque::Worklist< T >::IsEmpty(), v8::internal::torque::Block::MergeInputDefinitions(), v8::internal::torque::DefinitionLocation::Parameter(), v8::internal::torque::ControlFlowGraph::ParameterCount(), v8::internal::torque::Stack< T >::Push(), v8::internal::size_t, v8::internal::torque::ControlFlowGraph::start(), and USE.
Referenced by Result().
CurrentBlockIsComplete()
bool v8::internal::torque::CfgAssembler::CurrentBlockIsComplete () const [inline]
Definition at line 167 of file cfg.h.
{ return current_block_->IsComplete(); }
References current_block_, and v8::internal::torque::Block::IsComplete().
Referenced by v8::internal::torque::CfgAssemblerScopedTemporaryBlock::CfgAssemblerScopedTemporaryBlock(), and Result().
CurrentStack()
const Stack<const Type*>& v8::internal::torque::CfgAssembler::CurrentStack () const [inline]
Definition at line 180 of file cfg.h.
{ return current_stack_; }
References current_stack_.
Referenced by DropTo(), Goto(), Poke(), and TopRange().
DebugBreak()
void v8::internal::torque::CfgAssembler::DebugBreak ()
Definition at line 159 of file cfg.cc.
                              {
  Emit(AbortInstruction{AbortInstruction::Kind::kDebugBreak});
}
References Emit(), and v8::internal::torque::AbortInstruction::kDebugBreak.
DeleteRange()
void v8::internal::torque::CfgAssembler::DeleteRange (StackRange range)
Definition at line 104 of file cfg.cc.
                                               {
  DCHECK_LE(range.end(), current_stack_.AboveTop());
  if (range.Size() == 0) return;
  Emit(DeleteRangeInstruction{range});
}
References current_stack_, DCHECK_LE, Emit(), v8::internal::torque::StackRange::end(), and v8::internal::torque::StackRange::Size().
Referenced by DropTo().
DropTo()
void v8::internal::torque::CfgAssembler::DropTo (BottomOffset new_level)
Definition at line 110 of file cfg.cc.
                                                {
  DeleteRange(StackRange{new_level, CurrentStack().AboveTop()});
}
References CurrentStack(), and DeleteRange().
Referenced by Goto().
Emit()
void v8::internal::torque::CfgAssembler::Emit (Instruction instruction) [inline]
Definition at line 175 of file cfg.h.
                                     {
    instruction.TypeInstruction(&current_stack_, &cfg_);
    current_block_->Add(std::move(instruction));
  }
References v8::internal::torque::Block::Add(), cfg_, current_block_, current_stack_, and v8::internal::torque::Instruction::TypeInstruction().
Referenced by AssertionFailure(), Branch(), DebugBreak(), DeleteRange(), v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateSetBitField(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), Goto(), Peek(), Poke(), Print(), and Unreachable().
Goto() [1/2]
void v8::internal::torque::CfgAssembler::Goto (Block * block)
Definition at line 81 of file cfg.cc.
                                    {
  if (block->HasInputTypes()) {
    DropTo(block->InputTypes().AboveTop());
  }
  Emit(GotoInstruction{block});
}
References DropTo(), Emit(), v8::internal::torque::Block::HasInputTypes(), and v8::internal::torque::Block::InputTypes().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
Goto() [2/2]
StackRange v8::internal::torque::CfgAssembler::Goto (Block * block, size_t preserved_slots)
Definition at line 88 of file cfg.cc.
                                                                  {
  DCHECK(block->HasInputTypes());
  DCHECK_GE(CurrentStack().Size(), block->InputTypes().Size());
  Emit(DeleteRangeInstruction{
      StackRange{block->InputTypes().AboveTop() - preserved_slots,
                 CurrentStack().AboveTop() - preserved_slots}});
  StackRange preserved_slot_range = TopRange(preserved_slots);
  Emit(GotoInstruction{block});
  return preserved_slot_range;
}
References CurrentStack(), v8::internal::DCHECK(), DCHECK_GE, Emit(), v8::internal::torque::Block::HasInputTypes(), v8::internal::torque::Block::InputTypes(), and TopRange().
NewBlock()
Block* v8::internal::torque::CfgAssembler::NewBlock (std::optional< Stack< const Type * >> input_types = std::nullopt, bool is_deferred = false) [inline]
Definition at line 162 of file cfg.h.
                                            {
    return cfg_.NewBlock(std::move(input_types), is_deferred);
  }
References cfg_, and v8::internal::torque::ControlFlowGraph::NewBlock().
Referenced by v8::internal::torque::ImplementationVisitor::Visit().
OptimizeCfg()
void v8::internal::torque::CfgAssembler::OptimizeCfg ()
Definition at line 181 of file cfg.cc.
                               {
  auto predecessor_count = CountBlockPredecessors(cfg_);
  for (Block* block : cfg_.blocks()) {
    if (cfg_.end() && *cfg_.end() == block) continue;
    if (predecessor_count[block->id()] == 0) continue;
    while (!block->instructions().empty()) {
      const auto& instruction = block->instructions().back();
      if (!instruction.Is<GotoInstruction>()) break;
      Block* destination = instruction.Cast<GotoInstruction>().destination;
      if (destination == block) break;
      if (cfg_.end() && *cfg_.end() == destination) break;
      DCHECK_GT(predecessor_count[destination->id()], 0);
      if (predecessor_count[destination->id()] != 1) break;
      DCHECK_GT(destination->instructions().size(), 0);
      block->instructions().pop_back();
      block->instructions().insert(block->instructions().end(),
                                   destination->instructions().begin(),
                                   destination->instructions().end());
      --predecessor_count[destination->id()];
      DCHECK_EQ(predecessor_count[destination->id()], 0);
    }
  }
  cfg_.UnplaceBlockIf(
      [&](Block* b) { return predecessor_count[b->id()] == 0; });
}
References v8::internal::torque::ControlFlowGraph::blocks(), cfg_, v8::internal::torque::CountBlockPredecessors(), DCHECK_EQ, DCHECK_GT, v8::internal::torque::ControlFlowGraph::end(), v8::internal::torque::Block::id(), v8::internal::torque::Block::instructions(), and v8::internal::torque::ControlFlowGraph::UnplaceBlockIf().
Referenced by Result().
Peek()
StackRange v8::internal::torque::CfgAssembler::Peek (StackRange range, std::optional< const Type * > type)
Definition at line 114 of file cfg.cc.
                                                             {
  std::vector<const Type*> lowered_types;
  if (type) {
    lowered_types = LowerType(*type);
    DCHECK_EQ(lowered_types.size(), range.Size());
  }
  for (size_t i = 0; i < range.Size(); ++i) {
    Emit(PeekInstruction{
        range.begin() + i,
        type ? lowered_types[i] : std::optional<const Type*>{}});
  }
  return TopRange(range.Size());
}
References v8::internal::torque::StackRange::begin(), DCHECK_EQ, Emit(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::torque::LowerType(), v8::internal::torque::StackRange::Size(), TopRange(), and v8::internal::tracing::type.
Poke()
void v8::internal::torque::CfgAssembler::Poke (StackRange destination, StackRange origin, std::optional< const Type * > type)
Definition at line 129 of file cfg.cc.
                                                       {
  DCHECK_EQ(destination.Size(), origin.Size());
  DCHECK_LE(destination.end(), origin.begin());
  DCHECK_EQ(origin.end(), CurrentStack().AboveTop());
  std::vector<const Type*> lowered_types;
  if (type) {
    lowered_types = LowerType(*type);
    DCHECK_EQ(lowered_types.size(), origin.Size());
  }
  for (intptr_t i = origin.Size() - 1; i >= 0; --i) {
    Emit(PokeInstruction{
        destination.begin() + i,
        type ? lowered_types[i] : std::optional<const Type*>{}});
  }
}
References v8::internal::torque::StackRange::begin(), CurrentStack(), DCHECK_EQ, DCHECK_LE, Emit(), v8::internal::torque::StackRange::end(), v8::internal::torque::LowerType(), v8::internal::torque::StackRange::Size(), and v8::internal::tracing::type.
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFieldAccess().
Print()
void v8::internal::torque::CfgAssembler::Print (std::string s)
Definition at line 146 of file cfg.cc.
                                    {
  Emit(PrintErrorInstruction{std::move(s)});
}
References Emit().
PrintCurrentStack()
void v8::internal::torque::CfgAssembler::PrintCurrentStack (std::ostream & s) [inline]
Definition at line 207 of file cfg.h.
{ s << "stack: " << current_stack_; }
References current_stack_.
Result()
const ControlFlowGraph& v8::internal::torque::CfgAssembler::Result () [inline]
Definition at line 152 of file cfg.h.
                                   {
    if (!CurrentBlockIsComplete()) {
      cfg_.set_end(current_block_);
    }
    OptimizeCfg();
    DCHECK(CfgIsComplete());
    ComputeInputDefinitions();
    return cfg_;
  }
References cfg_, CfgIsComplete(), ComputeInputDefinitions(), current_block_, CurrentBlockIsComplete(), v8::internal::DCHECK(), OptimizeCfg(), and v8::internal::torque::ControlFlowGraph::set_end().
TopRange()
StackRange v8::internal::torque::CfgAssembler::TopRange (size_t slot_count) const [inline]
Definition at line 182 of file cfg.h.
                                               {
    return CurrentStack().TopRange(slot_count);
  }
References CurrentStack().
Referenced by v8::internal::torque::ImplementationVisitor::GenerateFetchFromLocation(), v8::internal::torque::ImplementationVisitor::GenerateFieldReferenceForInit(), v8::internal::torque::ImplementationVisitor::GetLocationReference(), Goto(), Peek(), and v8::internal::torque::ImplementationVisitor::Visit().
Unreachable()
void v8::internal::torque::CfgAssembler::Unreachable ()
Definition at line 155 of file cfg.cc.
                               {
  Emit(AbortInstruction{AbortInstruction::Kind::kUnreachable});
}
References Emit(), and v8::internal::torque::AbortInstruction::kUnreachable.
Friends And Related Function Documentation
CfgAssemblerScopedTemporaryBlock
friend class CfgAssemblerScopedTemporaryBlock [friend]
Definition at line 212 of file cfg.h.
Member Data Documentation
cfg_
ControlFlowGraph v8::internal::torque::CfgAssembler::cfg_ [private]
Definition at line 214 of file cfg.h.
Referenced by Bind(), v8::internal::torque::CfgAssemblerScopedTemporaryBlock::CfgAssemblerScopedTemporaryBlock(), CfgIsComplete(), ComputeInputDefinitions(), Emit(), NewBlock(), OptimizeCfg(), and Result().
current_block_
Block* v8::internal::torque::CfgAssembler::current_block_ = cfg_.start() [private]
Definition at line 215 of file cfg.h.
Referenced by Bind(), v8::internal::torque::CfgAssemblerScopedTemporaryBlock::CfgAssemblerScopedTemporaryBlock(), CurrentBlockIsComplete(), Emit(), and Result().
current_stack_
Stack<const Type*> v8::internal::torque::CfgAssembler::current_stack_ [private]
Definition at line 213 of file cfg.h.
Referenced by Bind(), v8::internal::torque::CfgAssemblerScopedTemporaryBlock::CfgAssemblerScopedTemporaryBlock(), CurrentStack(), DeleteRange(), Emit(), and PrintCurrentStack().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/torque/cfg.h
/mnt/V8SourceCode/src/torque/cfg.cc