v8::internal::ObjectBuiltinsAssembler Class Reference
#include <builtins-object-gen.h>
Public Member Functions
ObjectBuiltinsAssembler (compiler::CodeAssemblerState *state)
TNode< Union< Undefined, JSObject > > FromPropertyDescriptor (TNode< Context >, TNode< Object > desc)
Protected Member Functions
void ReturnToStringFormat (TNode< Context > context, TNode< String > string)
void AddToDictionaryIf (TNode< BoolT > condition, TNode< Context > context, TNode< Object > object, TNode< HeapObject > name_dictionary, Handle< Name > name, TNode< Object > value, Label *bailout)
TNode< JSObject > FromPropertyDescriptor (TNode< Context > context, TNode< PropertyDescriptorObject > desc)
TNode< JSObject > FromPropertyDetails (TNode< Context > context, TNode< Object > raw_value, TNode< Word32T > details, Label *if_bailout)
TNode< PropertyDescriptorObject > DescriptorFromPropertyDetails (TNode< Context > context, TNode< Object > raw_value, TNode< Word32T > details, Label *if_bailout)
TNode< JSObject > ConstructAccessorDescriptor (TNode< Context > context, TNode< Object > getter, TNode< Object > setter, TNode< BoolT > enumerable, TNode< BoolT > configurable)
TNode< JSObject > ConstructDataDescriptor (TNode< Context > context, TNode< Object > value, TNode< BoolT > writable, TNode< BoolT > enumerable, TNode< BoolT > configurable)
TNode< HeapObject > GetAccessorOrUndefined (TNode< HeapObject > accessor, Label *if_bailout)
Additional Inherited Members
Detailed Description
Definition at line 16 of file builtins-object-gen.h.
Constructor & Destructor Documentation
ObjectBuiltinsAssembler()
v8::internal::ObjectBuiltinsAssembler::ObjectBuiltinsAssembler (compiler::CodeAssemblerState * state) [inline], [explicit]
Definition at line 18 of file builtins-object-gen.h.
      : CodeStubAssembler(state) {}
Member Function Documentation
AddToDictionaryIf()
void v8::internal::ObjectBuiltinsAssembler::AddToDictionaryIf (TNode< BoolT > condition, TNode< Context > context, TNode< Object > object, TNode< HeapObject > name_dictionary, Handle< Name > name, TNode< Object > value, Label * bailout) [protected]
Definition at line 1559 of file builtins-object-gen.cc.
                    {
  Label done(this);
  GotoIfNot(condition, &done);
  AddToDictionary<PropertyDictionary>(CAST(name_dictionary),
                                      HeapConstantNoHole(name), value, bailout);
  Goto(&done);
  BIND(&done);
}
References CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIfNot(), v8::internal::compiler::CodeAssembler::HeapConstantNoHole(), v8::internal::name, and v8::internal::value.
Referenced by FromPropertyDescriptor().
ConstructAccessorDescriptor()
TNode< JSObject > v8::internal::ObjectBuiltinsAssembler::ConstructAccessorDescriptor (TNode< Context > context, TNode< Object > getter, TNode< Object > setter, TNode< BoolT > enumerable, TNode< BoolT > configurable) [protected]
Definition at line 72 of file builtins-object-gen.cc.
                                                        {
  TNode<NativeContext> native_context = LoadNativeContext(context);
  TNode<Map> map = CAST(LoadContextElementNoCell(
      native_context, Context::ACCESSOR_PROPERTY_DESCRIPTOR_MAP_INDEX));
  TNode<JSObject> js_desc = AllocateJSObjectFromMap(map);
  StoreObjectFieldNoWriteBarrier(
      js_desc, JSAccessorPropertyDescriptor::kGetOffset, getter);
  StoreObjectFieldNoWriteBarrier(
      js_desc, JSAccessorPropertyDescriptor::kSetOffset, setter);
  StoreObjectFieldNoWriteBarrier(
      js_desc, JSAccessorPropertyDescriptor::kEnumerableOffset,
      SelectBooleanConstant(enumerable));
  StoreObjectFieldNoWriteBarrier(
      js_desc, JSAccessorPropertyDescriptor::kConfigurableOffset,
      SelectBooleanConstant(configurable));
  return js_desc;
}
References v8::internal::CodeStubAssembler::AllocateJSObjectFromMap(), CAST, v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::native_context, v8::internal::CodeStubAssembler::SelectBooleanConstant(), v8::internal::setter, and v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier().
Referenced by FromPropertyDescriptor(), and FromPropertyDetails().
ConstructDataDescriptor()
TNode< JSObject > v8::internal::ObjectBuiltinsAssembler::ConstructDataDescriptor (TNode< Context > context, TNode< Object > value, TNode< BoolT > writable, TNode< BoolT > enumerable, TNode< BoolT > configurable) [protected]
Definition at line 94 of file builtins-object-gen.cc.
                                                        {
  TNode<NativeContext> native_context = LoadNativeContext(context);
  TNode<Map> map = CAST(LoadContextElementNoCell(
      native_context, Context::DATA_PROPERTY_DESCRIPTOR_MAP_INDEX));
  TNode<JSObject> js_desc = AllocateJSObjectFromMap(map);
  StoreObjectFieldNoWriteBarrier(js_desc,
                                 JSDataPropertyDescriptor::kValueOffset, value);
  StoreObjectFieldNoWriteBarrier(js_desc,
                                 JSDataPropertyDescriptor::kWritableOffset,
                                 SelectBooleanConstant(writable));
  StoreObjectFieldNoWriteBarrier(js_desc,
                                 JSDataPropertyDescriptor::kEnumerableOffset,
                                 SelectBooleanConstant(enumerable));
  StoreObjectFieldNoWriteBarrier(js_desc,
                                 JSDataPropertyDescriptor::kConfigurableOffset,
                                 SelectBooleanConstant(configurable));
  return js_desc;
}
References v8::internal::CodeStubAssembler::AllocateJSObjectFromMap(), CAST, v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::native_context, v8::internal::CodeStubAssembler::SelectBooleanConstant(), v8::internal::CodeStubAssembler::StoreObjectFieldNoWriteBarrier(), and v8::internal::value.
Referenced by FromPropertyDescriptor(), and FromPropertyDetails().
DescriptorFromPropertyDetails()
TNode<PropertyDescriptorObject> v8::internal::ObjectBuiltinsAssembler::DescriptorFromPropertyDetails (TNode< Context > context, TNode< Object > raw_value, TNode< Word32T > details, Label * if_bailout) [protected]
FromPropertyDescriptor() [1/2]
TNode< JSObject > v8::internal::ObjectBuiltinsAssembler::FromPropertyDescriptor (TNode< Context > context, TNode< PropertyDescriptorObject > desc) [protected]
Definition at line 1573 of file builtins-object-gen.cc.
                                                                  {
  TVARIABLE(JSObject, js_descriptor);
  TNode<Int32T> flags = LoadAndUntagToWord32ObjectField(
      desc, PropertyDescriptorObject::kFlagsOffset);
  TNode<Int32T> has_flags =
      Word32And(flags, Int32Constant(PropertyDescriptorObject::kHasMask));
  Label if_accessor_desc(this), if_data_desc(this), if_generic_desc(this),
      return_desc(this);
  GotoIf(
      Word32Equal(has_flags,
                  Int32Constant(
                      PropertyDescriptorObject::kRegularAccessorPropertyBits)),
      &if_accessor_desc);
  GotoIf(Word32Equal(
             has_flags,
             Int32Constant(PropertyDescriptorObject::kRegularDataPropertyBits)),
         &if_data_desc);
  Goto(&if_generic_desc);
  BIND(&if_accessor_desc);
  {
    js_descriptor = ConstructAccessorDescriptor(
        context, LoadObjectField(desc, PropertyDescriptorObject::kGetOffset),
        LoadObjectField(desc, PropertyDescriptorObject::kSetOffset),
        IsSetWord32<PropertyDescriptorObject::IsEnumerableBit>(flags),
        IsSetWord32<PropertyDescriptorObject::IsConfigurableBit>(flags));
    Goto(&return_desc);
  }
  BIND(&if_data_desc);
  {
    js_descriptor = ConstructDataDescriptor(
        context, LoadObjectField(desc, PropertyDescriptorObject::kValueOffset),
        IsSetWord32<PropertyDescriptorObject::IsWritableBit>(flags),
        IsSetWord32<PropertyDescriptorObject::IsEnumerableBit>(flags),
        IsSetWord32<PropertyDescriptorObject::IsConfigurableBit>(flags));
    Goto(&return_desc);
  }
  BIND(&if_generic_desc);
  {
    TNode<NativeContext> native_context = LoadNativeContext(context);
    TNode<Map> map = CAST(LoadContextElementNoCell(
        native_context, Context::SLOW_OBJECT_WITH_OBJECT_PROTOTYPE_MAP));
    // We want to preallocate the slots for value, writable, get, set,
    // enumerable and configurable - a total of 6
    TNode<HeapObject> properties = AllocatePropertyDictionary(6);
    TNode<JSObject> js_desc = AllocateJSObjectFromMap(map, properties);
    Label bailout(this, Label::kDeferred);
    Factory* factory = isolate()->factory();
    TNode<Object> value =
        LoadObjectField(desc, PropertyDescriptorObject::kValueOffset);
    AddToDictionaryIf(IsNotTheHole(value), context, js_desc, properties,
                      factory->value_string(), value, &bailout);
    AddToDictionaryIf(
        IsSetWord32<PropertyDescriptorObject::HasWritableBit>(flags), context,
        js_desc, properties, factory->writable_string(),
        SelectBooleanConstant(
            IsSetWord32<PropertyDescriptorObject::IsWritableBit>(flags)),
        &bailout);
    TNode<Object> get =
        LoadObjectField(desc, PropertyDescriptorObject::kGetOffset);
    AddToDictionaryIf(IsNotTheHole(get), context, js_desc, properties,
                      factory->get_string(), get, &bailout);
    TNode<Object> set =
        LoadObjectField(desc, PropertyDescriptorObject::kSetOffset);
    AddToDictionaryIf(IsNotTheHole(set), context, js_desc, properties,
                      factory->set_string(), set, &bailout);
    AddToDictionaryIf(
        IsSetWord32<PropertyDescriptorObject::HasEnumerableBit>(flags), context,
        js_desc, properties, factory->enumerable_string(),
        SelectBooleanConstant(
            IsSetWord32<PropertyDescriptorObject::IsEnumerableBit>(flags)),
        &bailout);
    AddToDictionaryIf(
        IsSetWord32<PropertyDescriptorObject::HasConfigurableBit>(flags),
        context, js_desc, properties, factory->configurable_string(),
        SelectBooleanConstant(
            IsSetWord32<PropertyDescriptorObject::IsConfigurableBit>(flags)),
        &bailout);
    js_descriptor = js_desc;
    Goto(&return_desc);
    BIND(&bailout);
    CSA_DCHECK(this, Int32Constant(0));
    Unreachable();
  }
  BIND(&return_desc);
  return js_descriptor.value();
}
References AddToDictionaryIf(), v8::internal::CodeStubAssembler::AllocateJSObjectFromMap(), v8::internal::CodeStubAssembler::AllocatePropertyDictionary(), CAST, ConstructAccessorDescriptor(), ConstructDataDescriptor(), v8::internal::Isolate::factory(), v8::internal::compiler::CodeAssembler::factory(), v8::internal::flags, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::Int32Constant(), v8::internal::compiler::CodeAssembler::isolate(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::PropertyDescriptorObject::kHasMask, v8::internal::PropertyDescriptorObject::kRegularAccessorPropertyBits, v8::internal::PropertyDescriptorObject::kRegularDataPropertyBits, v8::internal::CodeStubAssembler::LoadAndUntagToWord32ObjectField(), v8::internal::CodeStubAssembler::LoadNativeContext(), v8::internal::CodeStubAssembler::LoadObjectField(), v8::internal::native_context, v8::internal::CodeStubAssembler::SelectBooleanConstant(), v8::internal::compiler::CodeAssembler::Unreachable(), v8::internal::value, v8::internal::compiler::CodeAssembler::Word32And(), and v8::internal::compiler::CodeAssembler::Word32Equal().
FromPropertyDescriptor() [2/2]
TNode< Union< Undefined, JSObject > > v8::internal::ObjectBuiltinsAssembler::FromPropertyDescriptor (TNode< Context > context, TNode< Object > desc)
Definition at line 1675 of file builtins-object-gen.cc.
                                                                    {
  CSA_DCHECK(this, TaggedIsNotSmi(desc));
  if (IsUndefinedConstant(desc)) return UndefinedConstant();
  Label done(this);
  TVARIABLE((Union<Undefined, JSObject>), result, UndefinedConstant());
  GotoIf(IsUndefined(desc), &done);
  TNode<PropertyDescriptorObject> property_descriptor = CAST(desc);
  result = FromPropertyDescriptor(context, property_descriptor);
  Goto(&done);
  BIND(&done);
  return result.value();
}
References CAST, v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::compiler::CodeAssembler::IsUndefinedConstant(), v8::base::internal::result, v8::internal::CodeStubAssembler::TaggedIsNotSmi(), and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
FromPropertyDetails()
TNode< JSObject > v8::internal::ObjectBuiltinsAssembler::FromPropertyDetails (TNode< Context > context, TNode< Object > raw_value, TNode< Word32T > details, Label * if_bailout) [protected]
Definition at line 1693 of file builtins-object-gen.cc.
                       {
  TVARIABLE(JSObject, js_descriptor);
  Label if_accessor_desc(this), if_data_desc(this), return_desc(this);
  BranchIfAccessorPair(raw_value, &if_accessor_desc, &if_data_desc);
  BIND(&if_accessor_desc);
  {
    TNode<AccessorPair> accessor_pair_value = CAST(raw_value);
    TNode<HeapObject> getter =
        CAST(LoadAccessorPairGetter(accessor_pair_value));
    TNode<HeapObject> setter =
        CAST(LoadAccessorPairSetter(accessor_pair_value));
    js_descriptor = ConstructAccessorDescriptor(
        context, GetAccessorOrUndefined(getter, if_bailout),
        GetAccessorOrUndefined(setter, if_bailout),
        IsNotSetWord32(details, PropertyDetails::kAttributesDontEnumMask),
        IsNotSetWord32(details, PropertyDetails::kAttributesDontDeleteMask));
    Goto(&return_desc);
  }
  BIND(&if_data_desc);
  {
    js_descriptor = ConstructDataDescriptor(
        context, raw_value,
        IsNotSetWord32(details, PropertyDetails::kAttributesReadOnlyMask),
        IsNotSetWord32(details, PropertyDetails::kAttributesDontEnumMask),
        IsNotSetWord32(details, PropertyDetails::kAttributesDontDeleteMask));
    Goto(&return_desc);
  }
  BIND(&return_desc);
  return js_descriptor.value();
}
References v8::internal::CodeStubAssembler::BranchIfAccessorPair(), CAST, ConstructAccessorDescriptor(), ConstructDataDescriptor(), GetAccessorOrUndefined(), v8::internal::compiler::CodeAssembler::Goto(), v8::internal::CodeStubAssembler::IsNotSetWord32(), v8::internal::PropertyDetails::kAttributesDontDeleteMask, v8::internal::PropertyDetails::kAttributesDontEnumMask, v8::internal::PropertyDetails::kAttributesReadOnlyMask, v8::internal::CodeStubAssembler::LoadAccessorPairGetter(), v8::internal::CodeStubAssembler::LoadAccessorPairSetter(), and v8::internal::setter.
GetAccessorOrUndefined()
TNode< HeapObject > v8::internal::ObjectBuiltinsAssembler::GetAccessorOrUndefined (TNode< HeapObject > accessor, Label * if_bailout) [protected]
Definition at line 1730 of file builtins-object-gen.cc.
                                                   {
  Label bind_undefined(this, Label::kDeferred), return_result(this);
  TVARIABLE(HeapObject, result);
  GotoIf(IsNull(accessor), &bind_undefined);
  result = accessor;
  TNode<Map> map = LoadMap(accessor);
  // TODO(ishell): probe template instantiations cache.
  GotoIf(IsFunctionTemplateInfoMap(map), if_bailout);
  Goto(&return_result);
  BIND(&bind_undefined);
  result = UndefinedConstant();
  Goto(&return_result);
  BIND(&return_result);
  return result.value();
}
References v8::internal::compiler::CodeAssembler::Goto(), v8::internal::compiler::CodeAssembler::GotoIf(), v8::internal::IsNull(), v8::internal::compiler::CodeAssemblerLabel::kDeferred, v8::internal::CodeStubAssembler::LoadMap(), v8::base::internal::result, and v8::internal::compiler::js_node_wrapper_utils::UndefinedConstant().
Referenced by FromPropertyDetails().
ReturnToStringFormat()
void v8::internal::ObjectBuiltinsAssembler::ReturnToStringFormat (TNode< Context > context, TNode< String > string) [protected]
Definition at line 61 of file builtins-object-gen.cc.
                                                                         {
  TNode<String> lhs = StringConstant("[object ");
  TNode<String> rhs = StringConstant("]");
  Builtin builtin = Builtins::StringAdd(STRING_ADD_CHECK_NONE);
  Return(CallBuiltin(builtin, context,
                     CallBuiltin(builtin, context, lhs, string), rhs));
}
References v8::internal::compiler::CodeAssembler::builtin(), v8::internal::compiler::CodeAssembler::CallBuiltin(), v8::internal::compiler::CodeAssembler::Return(), v8::internal::STRING_ADD_CHECK_NONE, v8::internal::Builtins::StringAdd(), and v8::internal::compiler::CodeAssembler::StringConstant().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/builtins/builtins-object-gen.h
/mnt/V8SourceCode/src/builtins/builtins-object-gen.cc