v8::internal::ReplacementStringBuilder Class Reference
#include <string-builder.h>
Public Member Functions
ReplacementStringBuilder (Heap *heap, DirectHandle< String > subject, int estimated_part_count)
void AddSubjectSlice (int from, int to)
void AddString (DirectHandle< String > string)
MaybeDirectHandle< String > ToString ()
void IncrementCharacterCount (uint32_t by)
Static Public Member Functions
static void AddSubjectSlice (FixedArrayBuilder *builder, int from, int to)
Private Member Functions
void AddElement (DirectHandle< Object > element)
void EnsureCapacity (int elements)
Private Attributes
Heap * heap_
FixedArrayBuilder array_builder_
DirectHandle< String > subject_
uint32_t character_count_
bool is_one_byte_
Detailed Description
Definition at line 44 of file string-builder.h.
Constructor & Destructor Documentation
ReplacementStringBuilder()
v8::internal::ReplacementStringBuilder::ReplacementStringBuilder (Heap * heap, DirectHandle< String > subject, int estimated_part_count)
Definition at line 177 of file string-builder.cc.
    : heap_(heap),
      array_builder_(Isolate::FromHeap(heap), estimated_part_count),
      subject_(subject),
      character_count_(0),
      is_one_byte_(subject->IsOneByteRepresentation()) {
  // Require a non-zero initial size. Ensures that doubling the size to
  // extend the array will work.
  DCHECK_GT(estimated_part_count, 0);
}
References DCHECK_GT.
Member Function Documentation
AddElement()
void v8::internal::ReplacementStringBuilder::AddElement (DirectHandle< Object > element) [private]
Definition at line 237 of file string-builder.cc.
                                                                      {
  DCHECK(IsSmi(*element) || IsString(*element));
  EnsureCapacity(1);
  DisallowGarbageCollection no_gc;
  array_builder_.Add(*element);
}
References v8::internal::FixedArrayBuilder::Add(), array_builder_, v8::internal::DCHECK(), EnsureCapacity(), v8::internal::IsSmi(), and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by AddString().
AddString()
void v8::internal::ReplacementStringBuilder::AddString (DirectHandle< String > string)
Definition at line 194 of file string-builder.cc.
                                                                    {
  uint32_t length = string->length();
  AddElement(string);
  if (!string->IsOneByteRepresentation()) {
    is_one_byte_ = false;
  }
  IncrementCharacterCount(length);
}
References AddElement(), IncrementCharacterCount(), is_one_byte_, v8::internal::length, and v8::internal::string.
Referenced by v8::internal::CompiledReplacement::Apply(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::StringReplaceGlobalRegExpWithString().
AddSubjectSlice() [1/2]
void v8::internal::ReplacementStringBuilder::AddSubjectSlice (FixedArrayBuilder * builder, int from, int to) [inline], [static]
Definition at line 39 of file string-builder-inl.h.
                                                  {
  DCHECK_GE(from, 0);
  int length = to - from;
  DCHECK_GT(length, 0);
  if (StringBuilderSubstringLength::is_valid(length) &&
      StringBuilderSubstringPosition::is_valid(from)) {
    int encoded_slice = StringBuilderSubstringLength::encode(length) |
                        StringBuilderSubstringPosition::encode(from);
    builder->Add(Smi::FromInt(encoded_slice));
  } else {
    // Otherwise encode as two smis.
    builder->Add(Smi::FromInt(-length));
    builder->Add(Smi::FromInt(from));
  }
}
References v8::internal::FixedArrayBuilder::Add(), DCHECK_GE, DCHECK_GT, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::Smi::FromInt(), v8::base::BitField< T, shift, size, U >::is_valid(), and v8::internal::length.
Referenced by AddSubjectSlice(), v8::internal::CompiledReplacement::Apply(), v8::internal::RUNTIME_FUNCTION(), v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple(), and v8::internal::StringReplaceGlobalRegExpWithString().
AddSubjectSlice() [2/2]
void v8::internal::ReplacementStringBuilder::AddSubjectSlice (int from, int to) [inline]
Definition at line 56 of file string-builder-inl.h.
                                                                      {
  EnsureCapacity(2); // Subject slices are encoded with up to two smis.
  AddSubjectSlice(&array_builder_, from, to);
  IncrementCharacterCount(to - from);
}
References AddSubjectSlice(), array_builder_, EnsureCapacity(), and IncrementCharacterCount().
EnsureCapacity()
void v8::internal::ReplacementStringBuilder::EnsureCapacity (int elements) [private]
Definition at line 190 of file string-builder.cc.
                                                          {
  array_builder_.EnsureCapacity(Isolate::FromHeap(heap_), elements);
}
References array_builder_, v8::internal::FixedArrayBuilder::EnsureCapacity(), v8::internal::Isolate::FromHeap(), and heap_.
Referenced by AddElement(), and AddSubjectSlice().
IncrementCharacterCount()
void v8::internal::ReplacementStringBuilder::IncrementCharacterCount (uint32_t by) [inline]
Definition at line 59 of file string-builder.h.
                                            {
    if (character_count_ > String::kMaxLength - by) {
      static_assert(String::kMaxLength < kMaxInt);
      character_count_ = kMaxInt;
    } else {
      character_count_ += by;
    }
  }
References character_count_, v8::internal::kMaxInt, and v8::internal::String::kMaxLength.
Referenced by AddString(), and AddSubjectSlice().
ToString()
MaybeDirectHandle< String > v8::internal::ReplacementStringBuilder::ToString ()
Definition at line 203 of file string-builder.cc.
                                                             {
  Isolate* isolate = Isolate::FromHeap(heap_);
  if (array_builder_.length() == 0) {
    return isolate->factory()->empty_string();
  }
  DirectHandle<String> joined_string;
  if (is_one_byte_) {
    DirectHandle<SeqOneByteString> seq;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, seq,
        isolate->factory()->NewRawOneByteString(character_count_));
    DisallowGarbageCollection no_gc;
    uint8_t* char_buffer = seq->GetChars(no_gc);
    StringBuilderConcatHelper(*subject_, char_buffer, *array_builder_.array(),
                              array_builder_.length());
    joined_string = Cast<String>(seq);
  } else {
    // Two-byte.
    DirectHandle<SeqTwoByteString> seq;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, seq,
        isolate->factory()->NewRawTwoByteString(character_count_));
    DisallowGarbageCollection no_gc;
    base::uc16* char_buffer = seq->GetChars(no_gc);
    StringBuilderConcatHelper(*subject_, char_buffer, *array_builder_.array(),
                              array_builder_.length());
    joined_string = Cast<String>(seq);
  }
  return joined_string;
}
References v8::internal::FixedArrayBuilder::array(), array_builder_, ASSIGN_RETURN_ON_EXCEPTION, character_count_, v8::internal::Isolate::factory(), v8::internal::Isolate::FromHeap(), heap_, is_one_byte_, v8::internal::FixedArrayBuilder::length(), v8::internal::FactoryBase< Impl >::NewRawOneByteString(), v8::internal::FactoryBase< Impl >::NewRawTwoByteString(), v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, v8::internal::StringBuilderConcatHelper(), and subject_.
Referenced by v8::internal::RUNTIME_FUNCTION(), and v8::internal::StringReplaceGlobalRegExpWithString().
Member Data Documentation
array_builder_
FixedArrayBuilder v8::internal::ReplacementStringBuilder::array_builder_ [private]
Definition at line 73 of file string-builder.h.
Referenced by AddElement(), AddSubjectSlice(), EnsureCapacity(), and ToString().
character_count_
uint32_t v8::internal::ReplacementStringBuilder::character_count_ [private]
Definition at line 75 of file string-builder.h.
Referenced by IncrementCharacterCount(), and ToString().
heap_
Heap* v8::internal::ReplacementStringBuilder::heap_ [private]
Definition at line 72 of file string-builder.h.
Referenced by EnsureCapacity(), and ToString().
is_one_byte_
bool v8::internal::ReplacementStringBuilder::is_one_byte_ [private]
Definition at line 76 of file string-builder.h.
Referenced by AddString(), and ToString().
subject_
DirectHandle<String> v8::internal::ReplacementStringBuilder::subject_ [private]
Definition at line 74 of file string-builder.h.
Referenced by ToString().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/strings/string-builder.h
/mnt/V8SourceCode/src/strings/string-builder-inl.h
/mnt/V8SourceCode/src/strings/string-builder.cc