v8::internal::wasm::CanonicalSig::Builder Class Reference
#include <value-type.h>
Public Member Functions
Builder (Zone *zone, size_t return_count, size_t parameter_count)
CanonicalSig * Get () const
Additional Inherited Members
Detailed Description
Definition at line 1304 of file value-type.h.
Constructor & Destructor Documentation
Builder()
v8::internal::wasm::CanonicalSig::Builder::Builder (Zone * zone, size_t return_count, size_t parameter_count) [inline]
Definition at line 1306 of file value-type.h.
        : SignatureBuilder<CanonicalSig, CanonicalValueType>(zone, return_count,
                                                             parameter_count) {}
Member Function Documentation
Get()
CanonicalSig * v8::internal::wasm::CanonicalSig::Builder::Get () const
Definition at line 239 of file value-type.cc.
                                             {
  CanonicalSig* sig =
      reinterpret_cast<
          const SignatureBuilder<CanonicalSig, CanonicalValueType>*>(this)
          ->Get();
  sig->signature_hash_ = wasm::SignatureHasher::Hash(sig);
  return sig;
}
References v8::internal::wasm::SignatureHasher::Hash(), and v8::internal::sig.
Referenced by v8::internal::wasm::TypeCanonicalizer::AddRecursiveGroup(), and v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/value-type.h
/mnt/V8SourceCode/src/wasm/value-type.cc