v8::internal::compiler::LoadGlobalParameters Class Reference
#include <js-operator.h>
Public Member Functions
LoadGlobalParameters (NameRef name, const FeedbackSource &feedback, TypeofMode typeof_mode)
NameRef name () const
TypeofMode typeof_mode () const
const FeedbackSource & feedback () const
Private Attributes
const NameRef name_
const FeedbackSource feedback_
const TypeofMode typeof_mode_
Friends
bool operator== (LoadGlobalParameters const &, LoadGlobalParameters const &)
bool operator!= (LoadGlobalParameters const &, LoadGlobalParameters const &)
size_t hash_value (LoadGlobalParameters const &)
std::ostream & operator<< (std::ostream &, LoadGlobalParameters const &)
Detailed Description
Definition at line 474 of file js-operator.h.
Constructor & Destructor Documentation
LoadGlobalParameters()
v8::internal::compiler::LoadGlobalParameters::LoadGlobalParameters (NameRef name, const FeedbackSource & feedback, TypeofMode typeof_mode) [inline]
Definition at line 476 of file js-operator.h.
      : name_(name), feedback_(feedback), typeof_mode_(typeof_mode) {}
Member Function Documentation
feedback()
const FeedbackSource& v8::internal::compiler::LoadGlobalParameters::feedback () const [inline]
Definition at line 483 of file js-operator.h.
{ return feedback_; }
References feedback_.
Referenced by v8::internal::compiler::Verifier::Visitor::Check(), and v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal().
name()
NameRef v8::internal::compiler::LoadGlobalParameters::name () const [inline]
Definition at line 480 of file js-operator.h.
{ return name_; }
References name_.
Referenced by v8::internal::compiler::JSNativeContextSpecialization::ReduceJSLoadGlobal().
typeof_mode()
TypeofMode v8::internal::compiler::LoadGlobalParameters::typeof_mode () const [inline]
Definition at line 481 of file js-operator.h.
{ return typeof_mode_; }
References typeof_mode_.
Friends And Related Function Documentation
hash_value
size_t hash_value (LoadGlobalParameters const & p) [friend]
Definition at line 353 of file js-operator.cc.
                                                 {
  return base::hash_combine(p.name_.object().location(),
                            static_cast<int>(p.typeof_mode()));
}
operator!=
bool operator!= (LoadGlobalParameters const & lhs, LoadGlobalParameters const & rhs) [friend]
Definition at line 347 of file js-operator.cc.
                                                 {
  return !(lhs == rhs);
}
operator<<
std::ostream& operator<< (std::ostream & os, LoadGlobalParameters const & p) [friend]
Definition at line 359 of file js-operator.cc.
                                                                      {
  return os << Brief(*p.name_.object()) << ", "
            << static_cast<int>(p.typeof_mode());
}
operator==
bool operator== (LoadGlobalParameters const & lhs, LoadGlobalParameters const & rhs) [friend]
Definition at line 339 of file js-operator.cc.
                                                 {
  return lhs.name_.object().location() == rhs.name_.object().location() &&
         lhs.feedback() == rhs.feedback() &&
         lhs.typeof_mode() == rhs.typeof_mode();
}
Member Data Documentation
feedback_
const FeedbackSource v8::internal::compiler::LoadGlobalParameters::feedback_ [private]
Definition at line 487 of file js-operator.h.
Referenced by feedback().
name_
const NameRef v8::internal::compiler::LoadGlobalParameters::name_ [private]
Definition at line 486 of file js-operator.h.
Referenced by name().
typeof_mode_
const TypeofMode v8::internal::compiler::LoadGlobalParameters::typeof_mode_ [private]
Definition at line 488 of file js-operator.h.
Referenced by typeof_mode().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h