v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder Class Reference
Public Member Functions
CallSiteBuilder (Isolate *isolate, FrameSkipMode mode, int limit, Handle< Object > caller)
void SetPrevFrameAsConstructCall ()
bool Visit (FrameSummary const &summary)
void AppendAsyncFrame (DirectHandle< JSGeneratorObject > generator_object)
void AppendPromiseCombinatorFrame (DirectHandle< JSFunction > element_function, DirectHandle< JSFunction > combinator)
void AppendJavaScriptFrame (FrameSummary::JavaScriptFrameSummary const &summary)
bool Full ()
Handle< FixedArray > Build ()
Private Member Functions
bool IsStrictFrame (DirectHandle< JSFunction > function)
bool IsVisibleInStackTrace (DirectHandle< JSFunction > function)
bool ShouldIncludeFrame (DirectHandle< JSFunction > function)
bool IsNotHidden (DirectHandle< JSFunction > function)
void AppendFrame (DirectHandle< UnionOf< JSAny, Hole >> receiver_or_instance, DirectHandle< UnionOf< Smi, JSFunction >> function, DirectHandle< HeapObject > code, int offset, int flags, DirectHandle< FixedArray > parameters)
Private Attributes
Isolate * isolate_
const FrameSkipMode mode_
int index_ = 0
const int limit_
const Handle< Object > caller_
bool skip_next_frame_
bool skipped_prev_frame_ = false
bool encountered_strict_function_ = false
Handle< FixedArray > elements_
Detailed Description
Definition at line 857 of file isolate.cc.
Constructor & Destructor Documentation
CallSiteBuilder()
v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::CallSiteBuilder (Isolate * isolate, FrameSkipMode mode, int limit, Handle< Object > caller) [inline]
Definition at line 859 of file isolate.cc.
      : isolate_(isolate),
        mode_(mode),
        limit_(limit),
        caller_(caller),
        skip_next_frame_(mode != SKIP_NONE) {
    DCHECK_IMPLIES(mode_ == SKIP_UNTIL_SEEN, IsJSFunction(*caller_));
    // Modern web applications are usually built with multiple layers of
    // framework and library code, and stack depth tends to be more than
    // a dozen frames, so we over-allocate a bit here to avoid growing
    // the elements array in the common case.
    elements_ = isolate->factory()->NewFixedArray(std::min(64, limit));
  }
References DCHECK_IMPLIES, v8::internal::Isolate::factory(), v8::internal::FactoryBase< Impl >::NewFixedArray(), and v8::internal::SKIP_UNTIL_SEEN.
Member Function Documentation
AppendAsyncFrame()
void v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendAsyncFrame (DirectHandle< JSGeneratorObject > generator_object) [inline]
Definition at line 914 of file isolate.cc.
                                                                          {
    DirectHandle<JSFunction> function(generator_object->function(), isolate_);
    if (!IsVisibleInStackTrace(function)) {
      skipped_prev_frame_ = true;
      return;
    }
    int flags = CallSiteInfo::kIsAsync;
    if (IsStrictFrame(function)) flags |= CallSiteInfo::kIsStrict;
    DirectHandle<JSAny> receiver(generator_object->receiver(), isolate_);
    DirectHandle<BytecodeArray> code(
        function->shared()->GetBytecodeArray(isolate_), isolate_);
    int offset = GetGeneratorBytecodeOffset(generator_object);
    DirectHandle<FixedArray> parameters =
        isolate_->factory()->empty_fixed_array();
    if (V8_UNLIKELY(v8_flags.detailed_error_stack_trace)) {
      parameters = isolate_->factory()->CopyFixedArrayUpTo(
          direct_handle(generator_object->parameters_and_registers(), isolate_),
          function->shared()
              ->internal_formal_parameter_count_without_receiver());
    }
    AppendFrame(receiver, function, code, offset, flags, parameters);
  }
References code, v8::internal::direct_handle(), v8::internal::flags, v8::internal::anonymous_namespace{isolate.cc}::GetGeneratorBytecodeOffset(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CaptureAsyncStackTrace().
AppendFrame()
void v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendFrame (DirectHandle< UnionOf< JSAny, Hole >> receiver_or_instance, DirectHandle< UnionOf< Smi, JSFunction >> function, DirectHandle< HeapObject > code, int offset, int flags, DirectHandle< FixedArray > parameters) [inline], [private]
Definition at line 1104 of file isolate.cc.
                                                        {
    if (IsTheHole(*receiver_or_instance, isolate_)) {
      // TODO(jgruber): Fix all cases in which frames give us a hole value
      // (e.g. the receiver in RegExp constructor frames).
      receiver_or_instance = isolate_->factory()->undefined_value();
    }
    auto info = isolate_->factory()->NewCallSiteInfo(
        Cast<JSAny>(receiver_or_instance), function, code, offset, flags,
        parameters);
    elements_ = FixedArray::SetAndGrow(isolate_, elements_, index_++, info);
    skipped_prev_frame_ = false;
  }
References code, and v8::internal::flags.
AppendJavaScriptFrame()
void v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendJavaScriptFrame (FrameSummary::JavaScriptFrameSummary const & summary) [inline]
Definition at line 964 of file isolate.cc.
                                                         {
    // Filter out internal frames that we do not want to show.
    if (!IsVisibleInStackTrace(summary.function())) {
      skipped_prev_frame_ = true;
      return;
    }
    int flags = 0;
    DirectHandle<JSFunction> function = summary.function();
    if (IsStrictFrame(function)) flags |= CallSiteInfo::kIsStrict;
    if (summary.is_constructor()) flags |= CallSiteInfo::kIsConstructor;
    AppendFrame(Cast<UnionOf<JSAny, Hole>>(summary.receiver()), function,
                summary.abstract_code(), summary.code_offset(), flags,
                summary.parameters());
  }
References v8::internal::FrameSummary::JavaScriptFrameSummary::abstract_code(), v8::internal::Cast(), v8::internal::FrameSummary::JavaScriptFrameSummary::code_offset(), v8::internal::flags, v8::internal::FrameSummary::JavaScriptFrameSummary::function(), v8::internal::FrameSummary::JavaScriptFrameSummary::is_constructor(), v8::internal::FrameSummary::JavaScriptFrameSummary::parameters(), and v8::internal::FrameSummary::JavaScriptFrameSummary::receiver().
AppendPromiseCombinatorFrame()
void v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::AppendPromiseCombinatorFrame (DirectHandle< JSFunction > element_function, DirectHandle< JSFunction > combinator) [inline]
Definition at line 940 of file isolate.cc.
                                                                         {
    if (!IsVisibleInStackTrace(combinator)) {
      skipped_prev_frame_ = true;
      return;
    }
    int flags =
        CallSiteInfo::kIsAsync | CallSiteInfo::kIsSourcePositionComputed;
    DirectHandle<JSFunction> receiver(
        combinator->native_context()->promise_function(), isolate_);
    DirectHandle<Code> code(combinator->code(isolate_), isolate_);
    // TODO(mmarchini) save Promises list from the Promise combinator
    DirectHandle<FixedArray> parameters =
        isolate_->factory()->empty_fixed_array();
    // We store the offset of the promise into the element function's
    // hash field for element callbacks.
    int promise_index = Smi::ToInt(element_function->GetIdentityHash()) - 1;
    AppendFrame(receiver, combinator, code, promise_index, flags, parameters);
  }
References code, v8::internal::flags, and v8::internal::Smi::ToInt().
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CaptureAsyncStackTrace().
Build()
Handle<FixedArray> v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::Build () [inline]
Definition at line 1040 of file isolate.cc.
                             {
    return FixedArray::RightTrimOrEmpty(isolate_, elements_, index_);
  }
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CaptureSimpleStackTrace().
Full()
bool v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::Full () [inline]
Definition at line 1038 of file isolate.cc.
{ return index_ >= limit_; }
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CaptureAsyncStackTrace().
IsNotHidden()
bool v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::IsNotHidden (DirectHandle< JSFunction > function) [inline], [private]
Definition at line 1085 of file isolate.cc.
                                                      {
    // TODO(szuend): Remove this check once the flag is enabled
    // by default.
    if (!v8_flags.experimental_stack_trace_frames &&
        function->shared()->IsApiFunction()) {
      return false;
    }
    // Functions defined not in user scripts are not visible unless directly
    // exposed, in which case the native flag is set.
    // The --builtins-in-stack-traces command line flag allows including
    // internal call sites in the stack trace for debugging purposes.
    if (!v8_flags.builtins_in_stack_traces &&
        !function->shared()->IsUserJavaScript()) {
      return function->shared()->native() ||
             function->shared()->IsApiFunction();
    }
    return true;
  }
References v8::internal::v8_flags.
IsStrictFrame()
bool v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::IsStrictFrame (DirectHandle< JSFunction > function) [inline], [private]
Definition at line 1049 of file isolate.cc.
                                                        {
    if (!encountered_strict_function_) {
      encountered_strict_function_ =
          is_strict(function->shared()->language_mode());
    }
    return encountered_strict_function_;
  }
References v8::internal::is_strict().
IsVisibleInStackTrace()
bool v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::IsVisibleInStackTrace (DirectHandle< JSFunction > function) [inline], [private]
Definition at line 1059 of file isolate.cc.
                                                                {
    return ShouldIncludeFrame(function) && IsNotHidden(function);
  }
SetPrevFrameAsConstructCall()
void v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::SetPrevFrameAsConstructCall () [inline]
Definition at line 874 of file isolate.cc.
                                     {
    if (skipped_prev_frame_) return;
    DCHECK_GT(index_, 0);
    Tagged<CallSiteInfo> info =
        Tagged<CallSiteInfo>::cast(elements_->get(index_ - 1));
    info->set_flags(info->flags() | CallSiteInfo::kIsConstructor);
  }
References v8::internal::TaggedImpl< HeapObjectReferenceType::STRONG, Address >::cast(), and DCHECK_GT.
ShouldIncludeFrame()
bool v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::ShouldIncludeFrame (DirectHandle< JSFunction > function) [inline], [private]
Definition at line 1067 of file isolate.cc.
                                                             {
    switch (mode_) {
      case SKIP_NONE:
        return true;
      case SKIP_FIRST:
        if (!skip_next_frame_) return true;
        skip_next_frame_ = false;
        return false;
      case SKIP_UNTIL_SEEN:
        if (skip_next_frame_ && (*function == *caller_)) {
          skip_next_frame_ = false;
          return false;
        }
        return !skip_next_frame_;
    }
    UNREACHABLE();
  }
References v8::internal::SKIP_FIRST, v8::internal::SKIP_NONE, v8::internal::SKIP_UNTIL_SEEN, and v8::internal::UNREACHABLE().
Visit()
bool v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::Visit (FrameSummary const & summary) [inline]
Definition at line 882 of file isolate.cc.
                                          {
    if (Full()) return false;
#if V8_ENABLE_WEBASSEMBLY
#if V8_ENABLE_DRUMBRAKE
    if (summary.IsWasmInterpreted()) {
      AppendWasmInterpretedFrame(summary.AsWasmInterpreted());
      return true;
      // FrameSummary::IsWasm() should be renamed FrameSummary::IsWasmCompiled
      // to be more precise, but we'll leave it as it is to try to reduce merge
      // churn.
    } else {
#endif // V8_ENABLE_DRUMBRAKE
      if (summary.IsWasm()) {
        AppendWasmFrame(summary.AsWasm());
        return true;
      }
#if V8_ENABLE_DRUMBRAKE
    }
#endif // V8_ENABLE_DRUMBRAKE
    if (summary.IsWasmInlined()) {
      AppendWasmInlinedFrame(summary.AsWasmInlined());
      return true;
    }
    if (summary.IsBuiltin()) {
      AppendBuiltinFrame(summary.AsBuiltin());
      return true;
    }
#endif // V8_ENABLE_WEBASSEMBLY
    AppendJavaScriptFrame(summary.AsJavaScript());
    return true;
  }
Member Data Documentation
caller_
const Handle<Object> v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::caller_ [private]
Definition at line 1124 of file isolate.cc.
elements_
Handle<FixedArray> v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::elements_ [private]
Definition at line 1128 of file isolate.cc.
encountered_strict_function_
bool v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::encountered_strict_function_ = false [private]
Definition at line 1127 of file isolate.cc.
index_
int v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::index_ = 0 [private]
Definition at line 1122 of file isolate.cc.
isolate_
Isolate* v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::isolate_ [private]
Definition at line 1120 of file isolate.cc.
limit_
const int v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::limit_ [private]
Definition at line 1123 of file isolate.cc.
mode_
const FrameSkipMode v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::mode_ [private]
Definition at line 1121 of file isolate.cc.
skip_next_frame_
bool v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::skip_next_frame_ [private]
Definition at line 1125 of file isolate.cc.
skipped_prev_frame_
bool v8::internal::anonymous_namespace{isolate.cc}::CallSiteBuilder::skipped_prev_frame_ = false [private]
Definition at line 1126 of file isolate.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/execution/isolate.cc