v8::internal::AtomicSlot::Reference Class Reference
#include <slots-atomic-inl.h>
Public Member Functions
Reference (Tagged_t *address)
Reference (const Reference &) V8_NOEXCEPT=default
Reference & operator= (const Reference &other) V8_NOEXCEPT
Reference & operator= (Tagged_t value)
operator Tagged_t () const
void swap (Reference &other)
bool operator< (const Reference &other) const
bool operator== (const Reference &other) const
Private Member Functions
Tagged_t value () const
Private Attributes
Tagged_t * address_
Detailed Description
Definition at line 33 of file slots-atomic-inl.h.
Constructor & Destructor Documentation
Reference() [1/2]
v8::internal::AtomicSlot::Reference::Reference (Tagged_t * address) [inline], [explicit]
Definition at line 35 of file slots-atomic-inl.h.
: address_(address) {}
Reference() [2/2]
v8::internal::AtomicSlot::Reference::Reference (const Reference &) [default]
Member Function Documentation
operator Tagged_t()
v8::internal::AtomicSlot::Reference::operator Tagged_t () const [inline]
Definition at line 50 of file slots-atomic-inl.h.
{ return AsAtomicTagged::Relaxed_Load(address_); }
References address_, and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
operator<()
bool v8::internal::AtomicSlot::Reference::operator< (const Reference & other) const [inline]
Definition at line 58 of file slots-atomic-inl.h.
                                                 {
      return value() < other.value();
    }
References value().
operator=() [1/2]
Reference& v8::internal::AtomicSlot::Reference::operator= (const Reference & other) [inline]
Definition at line 38 of file slots-atomic-inl.h.
                                                             {
      AsAtomicTagged::Relaxed_Store(
          address_, AsAtomicTagged::Relaxed_Load(other.address_));
      return *this;
    }
References address_, v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load(), and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store().
operator=() [2/2]
Reference& v8::internal::AtomicSlot::Reference::operator= (Tagged_t value) [inline]
Definition at line 43 of file slots-atomic-inl.h.
                                         {
      AsAtomicTagged::Relaxed_Store(address_, value);
      return *this;
    }
References address_, v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store(), and value().
operator==()
bool v8::internal::AtomicSlot::Reference::operator== (const Reference & other) const [inline]
Definition at line 62 of file slots-atomic-inl.h.
                                                  {
      return value() == other.value();
    }
References value().
swap()
void v8::internal::AtomicSlot::Reference::swap (Reference & other) [inline]
Definition at line 52 of file slots-atomic-inl.h.
                                {
      Tagged_t tmp = value();
      AsAtomicTagged::Relaxed_Store(address_, other.value());
      AsAtomicTagged::Relaxed_Store(other.address_, tmp);
    }
References address_, v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Store(), and value().
value()
Tagged_t v8::internal::AtomicSlot::Reference::value () const [inline], [private]
Definition at line 67 of file slots-atomic-inl.h.
{ return AsAtomicTagged::Relaxed_Load(address_); }
References address_, and v8::base::AsAtomicImpl< TAtomicStorageType >::Relaxed_Load().
Referenced by operator<(), operator=(), operator==(), and swap().
Member Data Documentation
address_
Tagged_t* v8::internal::AtomicSlot::Reference::address_ [private]
Definition at line 69 of file slots-atomic-inl.h.
Referenced by operator Tagged_t(), operator=(), swap(), and value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/slots-atomic-inl.h