v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor Class Reference
A simple visitor visits every element of Array's.
Public Member Functions
ArrayConcatVisitor (Isolate *isolate, DirectHandle< UnionOf< JSReceiver, FixedArray, NumberDictionary >> storage, bool fast_elements)
~ArrayConcatVisitor ()
V8_WARN_UNUSED_RESULT bool visit (uint32_t i, DirectHandle< Object > elm)
uint32_t index_offset () const
void increase_index_offset (uint32_t delta)
bool exceeds_array_limit () const
DirectHandle< JSArray > ToArray ()
V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSReceiver > ToJSReceiver ()
bool has_simple_elements () const
Private Types
using FastElementsField = base::BitField< bool, 0, 1 >
using ExceedsLimitField = base::BitField< bool, 1, 1 >
using IsFixedArrayField = base::BitField< bool, 2, 1 >
using HasSimpleElementsField = base::BitField< bool, 3, 1 >
Private Member Functions
void SetDictionaryMode ()
void clear_storage ()
void set_storage (Tagged< FixedArray > storage)
bool fast_elements () const
void set_fast_elements (bool fast)
void set_exceeds_array_limit (bool exceeds)
bool is_fixed_array () const
DirectHandle< FixedArray > storage_fixed_array ()
Private Attributes
Isolate * isolate_
IndirectHandle< UnionOf< JSReceiver, FixedArray, NumberDictionary > > storage_
uint32_t index_offset_
uint32_t bit_field_
Detailed Description
A simple visitor visits every element of Array's.
The backend storage can be a fixed array for fast elements case, or a dictionary for sparse array. Since Dictionary is a subtype of FixedArray, the class can be used by both fast and slow cases. The second parameter of the constructor, fast_elements, specifies whether the storage is a FixedArray or Dictionary.
An index limit is used to deal with the situation that a result array length overflows 32-bit non-negative integer.
Definition at line 771 of file builtins-array.cc.
Member Typedef Documentation
ExceedsLimitField
using v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::ExceedsLimitField = base::BitField<bool, 1, 1> [private]
Definition at line 936 of file builtins-array.cc.
FastElementsField
using v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::FastElementsField = base::BitField<bool, 0, 1> [private]
Definition at line 935 of file builtins-array.cc.
HasSimpleElementsField
using v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::HasSimpleElementsField = base::BitField<bool, 3, 1> [private]
Definition at line 938 of file builtins-array.cc.
IsFixedArrayField
using v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::IsFixedArrayField = base::BitField<bool, 2, 1> [private]
Definition at line 937 of file builtins-array.cc.
Constructor & Destructor Documentation
ArrayConcatVisitor()
v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::ArrayConcatVisitor (Isolate * isolate, DirectHandle< UnionOf< JSReceiver, FixedArray, NumberDictionary >> storage, bool fast_elements) [inline]
Definition at line 773 of file builtins-array.cc.
      : isolate_(isolate),
        storage_(isolate->global_handles()->Create(*storage)),
        index_offset_(0u),
        bit_field_(FastElementsField::encode(fast_elements) |
                   ExceedsLimitField::encode(false) |
                   IsFixedArrayField::encode(IsFixedArray(*storage, isolate)) |
                   HasSimpleElementsField::encode(
                       IsFixedArray(*storage, isolate) ||
                       // Don't take fast path for storages that might have
                       // side effects when storing to them.
                       (!IsCustomElementsReceiverMap(storage->map(isolate)) &&
                        !IsJSTypedArray(*storage, isolate)))) {
    DCHECK_IMPLIES(this->fast_elements(), is_fixed_array());
  }
References DCHECK_IMPLIES.
 ArrayConcatVisitor()
v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::~ArrayConcatVisitor () [inline]
Definition at line 792 of file builtins-array.cc.
{ clear_storage(); }
Member Function Documentation
clear_storage()
void v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::clear_storage () [inline], [private]
Definition at line 927 of file builtins-array.cc.
{ GlobalHandles::Destroy(storage_.location()); }
References v8::internal::GlobalHandles::Destroy().
exceeds_array_limit()
bool v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::exceeds_array_limit () const [inline]
Definition at line 862 of file builtins-array.cc.
                                   {
    return ExceedsLimitField::decode(bit_field_);
  }
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat().
fast_elements()
bool v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::fast_elements () const [inline], [private]
Definition at line 940 of file builtins-array.cc.
{ return FastElementsField::decode(bit_field_); }
has_simple_elements()
bool v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::has_simple_elements () const [inline]
Definition at line 896 of file builtins-array.cc.
                                   {
    return HasSimpleElementsField::decode(bit_field_);
  }
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements().
increase_index_offset()
void v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::increase_index_offset (uint32_t delta) [inline]
Definition at line 846 of file builtins-array.cc.
                                             {
    if (JSArray::kMaxArrayLength - index_offset_ < delta) {
      index_offset_ = JSArray::kMaxArrayLength;
    } else {
      index_offset_ += delta;
    }
    // If the initial length estimate was off (see special case in visit()),
    // but the array blowing the limit didn't contain elements beyond the
    // provided-for index range, go to dictionary mode now.
    if (fast_elements() &&
        index_offset_ >
            static_cast<uint32_t>(Cast<FixedArrayBase>(*storage_)->length())) {
      SetDictionaryMode();
    }
  }
References v8::internal::JSArray::kMaxArrayLength.
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::IterateElementsSlow(), and v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat().
index_offset()
uint32_t v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::index_offset () const [inline]
Definition at line 844 of file builtins-array.cc.
{ return index_offset_; }
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements().
is_fixed_array()
bool v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::is_fixed_array () const [inline], [private]
Definition at line 947 of file builtins-array.cc.
{ return IsFixedArrayField::decode(bit_field_); }
set_exceeds_array_limit()
void v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::set_exceeds_array_limit (bool exceeds) [inline], [private]
Definition at line 944 of file builtins-array.cc.
                                             {
    bit_field_ = ExceedsLimitField::update(bit_field_, exceeds);
  }
set_fast_elements()
void v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::set_fast_elements (bool fast) [inline], [private]
Definition at line 941 of file builtins-array.cc.
                                    {
    bit_field_ = FastElementsField::update(bit_field_, fast);
  }
set_storage()
void v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::set_storage (Tagged< FixedArray > storage) [inline], [private]
Definition at line 929 of file builtins-array.cc.
                                                      {
    DCHECK(is_fixed_array());
    DCHECK(has_simple_elements());
    storage_ = isolate_->global_handles()->Create(storage);
  }
References v8::internal::DCHECK().
SetDictionaryMode()
void v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::SetDictionaryMode () [inline], [private]
Definition at line 902 of file builtins-array.cc.
                           {
    DCHECK(fast_elements() && is_fixed_array());
    DirectHandle<FixedArray> current_storage = storage_fixed_array();
    DirectHandle<NumberDictionary> slow_storage(
        NumberDictionary::New(isolate_, current_storage->length()));
    uint32_t current_length = static_cast<uint32_t>(current_storage->length());
    FOR_WITH_HANDLE_SCOPE(
        isolate_, uint32_t, i = 0, i, i < current_length, i++, {
          DirectHandle<Object> element(current_storage->get(i), isolate_);
          if (!IsTheHole(*element, isolate_)) {
            // The object holding this backing store has just been allocated, so
            // it cannot yet be used as a prototype.
            DirectHandle<JSObject> not_a_prototype_holder;
            DirectHandle<NumberDictionary> new_storage = NumberDictionary::Set(
                isolate_, slow_storage, i, element, not_a_prototype_holder);
            if (!new_storage.is_identical_to(slow_storage)) {
              slow_storage = loop_scope.CloseAndEscape(new_storage);
            }
          }
        });
    clear_storage();
    set_storage(*slow_storage);
    set_fast_elements(false);
  }
References v8::internal::DCHECK(), FOR_WITH_HANDLE_SCOPE, v8::internal::DirectHandle< T >::is_identical_to(), and v8::internal::anonymous_namespace{intl-objects.cc}::New().
storage_fixed_array()
DirectHandle<FixedArray> v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::storage_fixed_array () [inline], [private]
Definition at line 948 of file builtins-array.cc.
                                                 {
    DCHECK(is_fixed_array());
    DCHECK(has_simple_elements());
    return Cast<FixedArray>(storage_);
  }
References v8::internal::DCHECK().
ToArray()
DirectHandle<JSArray> v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::ToArray () [inline]
Definition at line 866 of file builtins-array.cc.
                                  {
    DCHECK(is_fixed_array());
    DirectHandle<JSArray> array = isolate_->factory()->NewJSArray(0);
    DirectHandle<Number> length =
        isolate_->factory()->NewNumber(static_cast<double>(index_offset_));
    DirectHandle<Map> map = JSObject::GetElementsTransitionMap(
        isolate_, array,
        fast_elements() ? HOLEY_ELEMENTS : DICTIONARY_ELEMENTS);
    {
      DisallowGarbageCollection no_gc;
      Tagged<JSArray> raw = *array;
      raw->set_length(*length);
      raw->set_elements(*storage_fixed_array());
      raw->set_map(isolate_, *map, kReleaseStore);
    }
    return array;
  }
References v8::internal::DCHECK(), v8::internal::DICTIONARY_ELEMENTS, v8::internal::JSObject::GetElementsTransitionMap(), v8::internal::HOLEY_ELEMENTS, v8::kReleaseStore, v8::internal::length, and v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc.
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat().
ToJSReceiver()
V8_WARN_UNUSED_RESULT MaybeDirectHandle<JSReceiver> v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::ToJSReceiver () [inline]
Definition at line 884 of file builtins-array.cc.
                                                                     {
    DCHECK(!is_fixed_array());
    DirectHandle<JSReceiver> result = Cast<JSReceiver>(storage_);
    DirectHandle<Object> length =
        isolate_->factory()->NewNumber(static_cast<double>(index_offset_));
    RETURN_ON_EXCEPTION(
        isolate_, Object::SetProperty(isolate_, result,
                                      isolate_->factory()->length_string(),
                                      length, StoreOrigin::kMaybeKeyed,
                                      Just(ShouldThrow::kThrowOnError)));
    return result;
  }
References v8::internal::DCHECK(), v8::Just(), v8::internal::kMaybeKeyed, v8::internal::kThrowOnError, v8::internal::length, v8::base::internal::result, RETURN_ON_EXCEPTION, and v8::internal::Object::SetProperty().
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat().
visit()
V8_WARN_UNUSED_RESULT bool v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::visit (uint32_t i, DirectHandle< Object > elm) [inline]
Definition at line 794 of file builtins-array.cc.
                                                                         {
    uint32_t index = index_offset_ + i;
    // Note we use >=kMaxArrayLength instead of the more appropriate
    // >kMaxArrayIndex here due to overflowing arithmetic and
    // increase_index_offset.
    if (i >= JSArray::kMaxArrayLength - index_offset_) {
      set_exceeds_array_limit(true);
      // Exception hasn't been thrown at this point. Return true to
      // break out, and caller will throw. !visit would imply that
      // there is already an exception.
      return true;
    }
    if (!is_fixed_array()) {
      MAYBE_RETURN(JSReceiver::CreateDataProperty(
                       isolate_, direct_handle(Cast<JSReceiver>(storage_)),
                       PropertyKey(isolate_, index), elm, Just(kThrowOnError)),
                   false);
      return true;
    }
    if (fast_elements()) {
      if (index < static_cast<uint32_t>(storage_fixed_array()->length())) {
        storage_fixed_array()->set(index, *elm);
        return true;
      }
      // Our initial estimate of length was foiled, possibly by
      // getters on the arrays increasing the length of later arrays
      // during iteration.
      // This shouldn't happen in anything but pathological cases.
      SetDictionaryMode();
      // Fall-through to dictionary mode.
    }
    DCHECK(!fast_elements());
    DirectHandle<NumberDictionary> dict(Cast<NumberDictionary>(*storage_),
                                        isolate_);
    // The object holding this backing store has just been allocated, so
    // it cannot yet be used as a prototype.
    DirectHandle<JSObject> not_a_prototype_holder;
    DirectHandle<NumberDictionary> result = NumberDictionary::Set(
        isolate_, dict, index, elm, not_a_prototype_holder);
    if (!result.is_identical_to(dict)) {
      // Dictionary needed to grow.
      clear_storage();
      set_storage(*result);
    }
    return true;
  }
References v8::internal::Cast< NumberDictionary >(), v8::internal::JSReceiver::CreateDataProperty(), v8::internal::DCHECK(), v8::internal::direct_handle(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::Just(), v8::internal::JSArray::kMaxArrayLength, v8::internal::kThrowOnError, v8::internal::length, MAYBE_RETURN, and v8::base::internal::result.
Referenced by v8::internal::anonymous_namespace{builtins-array.cc}::IterateElements(), v8::internal::anonymous_namespace{builtins-array.cc}::IterateElementsSlow(), and v8::internal::anonymous_namespace{builtins-array.cc}::Slow_ArrayConcat().
Member Data Documentation
bit_field_
uint32_t v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::bit_field_ [private]
Definition at line 960 of file builtins-array.cc.
index_offset_
uint32_t v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::index_offset_ [private]
Definition at line 959 of file builtins-array.cc.
isolate_
Isolate* v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::isolate_ [private]
Definition at line 954 of file builtins-array.cc.
storage_
IndirectHandle<UnionOf<JSReceiver, FixedArray, NumberDictionary> > v8::internal::anonymous_namespace{builtins-array.cc}::ArrayConcatVisitor::storage_ [private]
Definition at line 956 of file builtins-array.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/builtins/builtins-array.cc