v8::internal::SharedStringAccessGuardIfNeeded Class Reference
#include <string-inl.h>
Public Member Functions
SharedStringAccessGuardIfNeeded (Isolate *isolate)
SharedStringAccessGuardIfNeeded (LocalIsolate *local_isolate)
SharedStringAccessGuardIfNeeded (Tagged< String > str)
SharedStringAccessGuardIfNeeded (Tagged< String > str, LocalIsolate *local_isolate)
Static Public Member Functions
static SharedStringAccessGuardIfNeeded NotNeeded ()
static bool IsNeeded (Tagged< String > str, LocalIsolate *local_isolate)
static bool IsNeeded (Tagged< String > str, bool check_local_heap=true)
static bool IsNeeded (LocalIsolate *local_isolate)
Private Member Functions
constexpr SharedStringAccessGuardIfNeeded ()=default
constexpr SharedStringAccessGuardIfNeeded (SharedStringAccessGuardIfNeeded &&) V8_NOEXCEPT
Static Private Member Functions
static Isolate * GetIsolateIfNeeded (Tagged< String > str)
Private Attributes
std::optional< base::MutexGuard > mutex_guard
Detailed Description
Definition at line 48 of file string-inl.h.
Constructor & Destructor Documentation
SharedStringAccessGuardIfNeeded() [1/6]
v8::internal::SharedStringAccessGuardIfNeeded::SharedStringAccessGuardIfNeeded (Isolate * isolate) [inline], [explicit]
Definition at line 52 of file string-inl.h.
{}
SharedStringAccessGuardIfNeeded() [2/6]
v8::internal::SharedStringAccessGuardIfNeeded::SharedStringAccessGuardIfNeeded (LocalIsolate * local_isolate) [inline], [explicit]
Definition at line 56 of file string-inl.h.
                                                                        {
    if (IsNeeded(local_isolate)) {
      mutex_guard.emplace(local_isolate->internalized_string_access());
    }
  }
References v8::internal::LocalIsolate::internalized_string_access().
SharedStringAccessGuardIfNeeded() [3/6]
v8::internal::SharedStringAccessGuardIfNeeded::SharedStringAccessGuardIfNeeded (Tagged< String > str) [inline], [explicit]
Definition at line 63 of file string-inl.h.
                                                               {
    Isolate* isolate = GetIsolateIfNeeded(str);
    if (isolate != nullptr) {
      mutex_guard.emplace(isolate->internalized_string_access());
    }
  }
References v8::internal::Isolate::internalized_string_access().
SharedStringAccessGuardIfNeeded() [4/6]
v8::internal::SharedStringAccessGuardIfNeeded::SharedStringAccessGuardIfNeeded (Tagged< String > str, LocalIsolate * local_isolate) [inline]
Definition at line 70 of file string-inl.h.
                                                               {
    if (IsNeeded(str, local_isolate)) {
      mutex_guard.emplace(local_isolate->internalized_string_access());
    }
  }
References v8::internal::LocalIsolate::internalized_string_access().
SharedStringAccessGuardIfNeeded() [5/6]
constexpr v8::internal::SharedStringAccessGuardIfNeeded::SharedStringAccessGuardIfNeeded () [constexpr], [private], [default]
SharedStringAccessGuardIfNeeded() [6/6]
constexpr v8::internal::SharedStringAccessGuardIfNeeded::SharedStringAccessGuardIfNeeded (SharedStringAccessGuardIfNeeded &&) [inline], [constexpr], [private]
Definition at line 111 of file string-inl.h.
                  {
    DCHECK(!mutex_guard.has_value());
  }
References v8::internal::DCHECK().
Member Function Documentation
GetIsolateIfNeeded()
static Isolate* v8::internal::SharedStringAccessGuardIfNeeded::GetIsolateIfNeeded (Tagged< String > str) [inline], [static], [private]
Definition at line 117 of file string-inl.h.
                                                         {
    if (!IsNeeded(str)) return nullptr;
    Isolate* isolate;
    if (!GetIsolateFromHeapObject(str, &isolate)) {
      // If we can't get the isolate from the String, it must be read-only.
      DCHECK(ReadOnlyHeap::Contains(str));
      return nullptr;
    }
    return isolate;
  }
References v8::internal::ReadOnlyHeap::Contains(), v8::internal::DCHECK(), and v8::internal::GetIsolateFromHeapObject().
IsNeeded() [1/3]
static bool v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded (LocalIsolate * local_isolate) [inline], [static]
Definition at line 102 of file string-inl.h.
                                                    {
    // TODO(leszeks): Remove the nullptr check for local_isolate.
    return local_isolate && !local_isolate->heap()->is_main_thread();
  }
References v8::internal::LocalIsolate::heap(), and v8::internal::LocalHeap::is_main_thread().
IsNeeded() [2/3]
static bool v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded (Tagged< String > str, bool check_local_heap = true) [inline], [static]
Definition at line 85 of file string-inl.h.
                                                                         {
    if (check_local_heap) {
      LocalHeap* local_heap = LocalHeap::Current();
      if (!local_heap || local_heap->is_main_thread()) {
        // Don't acquire the lock for the main thread.
        return false;
      }
    }
    if (ReadOnlyHeap::Contains(str)) {
      // Don't acquire lock for strings in ReadOnlySpace.
      return false;
    }
    return true;
  }
References v8::internal::ReadOnlyHeap::Contains(), and v8::internal::LocalHeap::is_main_thread().
IsNeeded() [3/3]
static bool v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded (Tagged< String > str, LocalIsolate * local_isolate) [inline], [static]
Definition at line 81 of file string-inl.h.
                                                                        {
    return IsNeeded(local_isolate) && IsNeeded(str, false);
  }
Referenced by v8::internal::compiler::JSNativeContextSpecialization::Concatenate(), v8::internal::String::Get(), v8::internal::SeqOneByteString::Get(), v8::internal::SeqOneByteString::GetChars(), v8::internal::SeqTwoByteString::GetChars(), v8::internal::String::GetDirectStringChars(), v8::internal::String::IsEqualTo(), v8::internal::SeqSubStringKey< SeqString >::IsMatch(), v8::internal::InternalizedStringKey::IsMatch(), v8::internal::IsSpecialIndex(), v8::internal::anonymous_namespace{intl-objects.cc}::TryFastCompareStrings(), v8::internal::String::VisitFlat(), and v8::internal::String::WriteToFlat().
NotNeeded()
static SharedStringAccessGuardIfNeeded v8::internal::SharedStringAccessGuardIfNeeded::NotNeeded () [inline], [static]
Definition at line 77 of file string-inl.h.
                                                     {
    return SharedStringAccessGuardIfNeeded();
  }
Referenced by v8::internal::String::Get(), v8::internal::SeqOneByteString::Get(), v8::internal::String::GetFlatContent(), v8::internal::String::IsEqualTo(), v8::internal::IsSpecialIndex(), v8::internal::FactoryBase< Impl >::NewOneByteInternalizedString(), v8::internal::FactoryBase< Impl >::NewOneByteInternalizedStringFromTwoByte(), v8::internal::FactoryBase< Impl >::NewStringFromOneByte(), v8::internal::FactoryBase< Impl >::NewTwoByteInternalizedString(), v8::internal::String::VisitFlat(), and v8::internal::String::WriteToFlat().
Member Data Documentation
mutex_guard
std::optional<base::MutexGuard> v8::internal::SharedStringAccessGuardIfNeeded::mutex_guard [private]
Definition at line 129 of file string-inl.h.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/objects/string-inl.h