v8::IsolateGroup Class Reference
The set of V8 isolates in a process is partitioned into groups.
#include <v8-isolate.h>
Public Member Functions
IsolateGroup (IsolateGroup &&other)
IsolateGroup & operator= (IsolateGroup &&other)
IsolateGroup (const IsolateGroup &)
IsolateGroup & operator= (const IsolateGroup &)
~IsolateGroup ()
bool operator== (const IsolateGroup &other) const
bool operator!= (const IsolateGroup &other) const
bool SandboxContains (void *pointer) const
Static Public Member Functions
static IsolateGroup GetDefault ()
Get the default isolate group.
static bool CanCreateNewGroups ()
Return true if new isolate groups can be created at run-time, or false if all isolates must be in the same group.
static IsolateGroup Create ()
Create a new isolate group.
Private Member Functions
IsolateGroup (internal::IsolateGroup *&&isolate_group)
Private Attributes
internal::IsolateGroup * isolate_group_
Friends
class Isolate
class ArrayBuffer::Allocator
Detailed Description
The set of V8 isolates in a process is partitioned into groups.
Each group has its own sandbox (if V8 was configured with support for the sandbox) and pointer-compression cage (if configured with pointer compression).
By default, all isolates are placed in the same group. This is the most efficient configuration in terms of speed and memory use. However, with pointer compression enabled, total heap usage of isolates in a group cannot exceed 4 GB, not counting array buffers and other off-heap storage. Using multiple isolate groups can allow embedders to allocate more than 4GB of objects with pointer compression enabled, if the embedder's use case can span multiple isolates.
Creating an isolate group reserves a range of virtual memory addresses. A group's memory mapping will be released when the last isolate in the group is disposed, and there are no more live IsolateGroup objects that refer to it.
Note that Isolate groups are reference counted, and the IsolateGroup type is a reference to one.
Note that it's not going to be possible to pass shared JS objects across IsolateGroup boundary.
Definition at line 218 of file v8-isolate.h.
Constructor & Destructor Documentation
IsolateGroup() [1/3]
v8::IsolateGroup::IsolateGroup (IsolateGroup && other)
Definition at line 9684 of file api.cc.
                                               {
  isolate_group_ = other.isolate_group_;
  other.isolate_group_ = nullptr;
}
References isolate_group_.
Referenced by Create(), and GetDefault().
IsolateGroup() [2/3]
v8::IsolateGroup::IsolateGroup (const IsolateGroup & other)
Definition at line 9646 of file api.cc.
    : isolate_group_(other.isolate_group_) {
  if (isolate_group_) isolate_group_->Acquire();
}
References v8::internal::IsolateGroup::Acquire(), and isolate_group_.
 IsolateGroup()
v8::IsolateGroup::~IsolateGroup ()
Definition at line 9660 of file api.cc.
                            {
  if (isolate_group_) {
    isolate_group_->Release();
#ifdef DEBUG
    isolate_group_ = nullptr;
#endif
  }
}
References isolate_group_, and v8::internal::IsolateGroup::Release().
IsolateGroup() [3/3]
v8::IsolateGroup::IsolateGroup (internal::IsolateGroup *&& isolate_group) [explicit], [private]
Definition at line 9641 of file api.cc.
    : isolate_group_(isolate_group) {
  DCHECK_NOT_NULL(isolate_group_);
}
References DCHECK_NOT_NULL, and isolate_group_.
Member Function Documentation
CanCreateNewGroups()
bool v8::IsolateGroup::CanCreateNewGroups () [static]
Return true if new isolate groups can be created at run-time, or false if all isolates must be in the same group.
Definition at line 9675 of file api.cc.
                                      {
  return i::IsolateGroup::CanCreateNewGroups();
}
References v8::internal::IsolateGroup::CanCreateNewGroups().
Create()
IsolateGroup v8::IsolateGroup::Create () [static]
Create a new isolate group.
If this V8's build configuration only supports a single group, abort.
Definition at line 9680 of file api.cc.
                                  {
  return IsolateGroup(i::IsolateGroup::New());
}
References IsolateGroup(), and v8::internal::IsolateGroup::New().
GetDefault()
IsolateGroup v8::IsolateGroup::GetDefault () [static]
Get the default isolate group.
If this V8's build configuration only supports a single group, this is a reference to that single group. Otherwise this is a group like any other, distinguished only in that it is the first group.
Definition at line 9670 of file api.cc.
                                      {
  return IsolateGroup(i::IsolateGroup::AcquireDefault());
}
References v8::internal::IsolateGroup::AcquireDefault(), and IsolateGroup().
Referenced by v8::Isolate::Allocate(), and v8::Isolate::New().
operator!=()
bool v8::IsolateGroup::operator!= (const IsolateGroup & other) const [inline]
Definition at line 252 of file v8-isolate.h.
                                                   {
    return !operator==(other);
  }
References v8::operator==().
operator=() [1/2]
IsolateGroup & v8::IsolateGroup::operator= (const IsolateGroup & other)
Definition at line 9651 of file api.cc.
                                                               {
  if (this != &other && isolate_group_ != other.isolate_group_) {
    if (isolate_group_) isolate_group_->Release();
    isolate_group_ = other.isolate_group_;
    if (isolate_group_) isolate_group_->Acquire();
  }
  return *this;
}
References v8::internal::IsolateGroup::Acquire(), isolate_group_, and v8::internal::IsolateGroup::Release().
operator=() [2/2]
IsolateGroup & v8::IsolateGroup::operator= (IsolateGroup && other)
Definition at line 9689 of file api.cc.
                                                            {
  if (this == &other) {
    return *this;
  }
  if (isolate_group_) {
    isolate_group_->Release();
  }
  isolate_group_ = other.isolate_group_;
  other.isolate_group_ = nullptr;
  return *this;
}
References isolate_group_.
operator==()
bool v8::IsolateGroup::operator== (const IsolateGroup & other) const [inline]
Definition at line 248 of file v8-isolate.h.
                                                   {
    return isolate_group_ == other.isolate_group_;
  }
References isolate_group_.
SandboxContains()
bool v8::IsolateGroup::SandboxContains (void * pointer) const [inline]
Definition at line 264 of file v8-isolate.h.
{ return true; }
Friends And Related Function Documentation
ArrayBuffer::Allocator
friend class ArrayBuffer::Allocator [friend]
Definition at line 269 of file v8-isolate.h.
Isolate
friend class Isolate [friend]
Definition at line 268 of file v8-isolate.h.
Member Data Documentation
isolate_group_
internal::IsolateGroup* v8::IsolateGroup::isolate_group_ [private]
Definition at line 274 of file v8-isolate.h.
Referenced by v8::Isolate::Allocate(), IsolateGroup(), operator=(), operator==(), and ~IsolateGroup().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-isolate.h
/mnt/V8SourceCode/src/api/api.cc