v8::internal::compiler::turboshaft::MaybeRegisterRepresentation Class Reference
#include <representations.h>
Public Types
enum class Enum : uint8_t {
kWord32
, kWord64
, kFloat32
, kFloat64
,
kTagged
, kCompressed
, kSimd128
, kSimd256
,
kNone
 }
Public Member Functions
constexpr MaybeRegisterRepresentation (Enum value)
constexpr MaybeRegisterRepresentation ()
constexpr bool is_valid () const
constexpr Enum value () const
constexpr operator Enum () const
constexpr bool IsWord () const
constexpr bool IsFloat () const
constexpr bool IsTaggedOrCompressed () const
uint64_t MaxUnsignedValue () const
MachineRepresentation machine_representation () const
constexpr uint16_t bit_width () const
Static Public Member Functions
static constexpr MaybeRegisterRepresentation Word32 ()
static constexpr MaybeRegisterRepresentation Word64 ()
static constexpr MaybeRegisterRepresentation WordPtr ()
static constexpr MaybeRegisterRepresentation Float32 ()
static constexpr MaybeRegisterRepresentation Float64 ()
static constexpr MaybeRegisterRepresentation Tagged ()
static constexpr MaybeRegisterRepresentation Compressed ()
static constexpr MaybeRegisterRepresentation Simd128 ()
static constexpr MaybeRegisterRepresentation Simd256 ()
static constexpr MaybeRegisterRepresentation None ()
Private Attributes
Enum value_
Static Private Attributes
static constexpr Enum kInvalid = static_cast<Enum>(-1)
Detailed Description
Definition at line 22 of file representations.h.
Member Enumeration Documentation
Enum
enum v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Enum : uint8_t [strong]
Enumerator
kWord32
kWord64
kFloat32
kFloat64
kTagged
kCompressed
kSimd128
kSimd256
kNone
Definition at line 24 of file representations.h.
                  : uint8_t {
    kWord32,
    kWord64,
    kFloat32,
    kFloat64,
    kTagged,
    kCompressed,
    kSimd128,
    kSimd256,
    kNone, // No register representation.
  };
Constructor & Destructor Documentation
MaybeRegisterRepresentation() [1/2]
constexpr v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::MaybeRegisterRepresentation (Enum value) [inline], [explicit], [constexpr]
Definition at line 36 of file representations.h.
: value_(value) {}
MaybeRegisterRepresentation() [2/2]
constexpr v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::MaybeRegisterRepresentation () [inline], [constexpr]
Definition at line 37 of file representations.h.
: value_(kInvalid) {}
Referenced by Compressed(), Float32(), Float64(), None(), Simd128(), Simd256(), Tagged(), Word32(), and Word64().
Member Function Documentation
bit_width()
constexpr uint16_t v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::bit_width () const [inline], [constexpr]
Definition at line 181 of file representations.h.
                                       {
    switch (this->value()) {
      case Word32():
        return 32;
      case Word64():
        return 64;
      case Float32():
        return 32;
      case Float64():
        return 64;
      case Tagged():
        return kSystemPointerSize;
      case Compressed():
        return kSystemPointerSize;
      case Simd128():
        return 128;
      case Simd256():
        return 256;
      case None():
        UNREACHABLE();
    }
  }
References Compressed(), Float32(), Float64(), v8::internal::kSystemPointerSize, None(), Simd128(), Simd256(), Tagged(), v8::internal::UNREACHABLE(), value(), Word32(), and Word64().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::CountLeadingSignBits(), v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceSignedDiv(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ShiftLeft(), v8::internal::compiler::turboshaft::TurboshaftAssemblerOpInterface< Assembler >::ShiftRightArithmetic(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::TryReduceToRor().
Compressed()
static constexpr MaybeRegisterRepresentation v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Compressed () [inline], [static], [constexpr]
Definition at line 77 of file representations.h.
                                                            {
    return MaybeRegisterRepresentation(Enum::kCompressed);
  }
References kCompressed, and MaybeRegisterRepresentation().
Referenced by bit_width(), machine_representation(), and v8::internal::compiler::turboshaft::operator<<().
Float32()
static constexpr MaybeRegisterRepresentation v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Float32 () [inline], [static], [constexpr]
Definition at line 65 of file representations.h.
                                                         {
    return MaybeRegisterRepresentation(Enum::kFloat32);
  }
References kFloat32, and MaybeRegisterRepresentation().
Referenced by bit_width(), machine_representation(), and v8::internal::compiler::turboshaft::operator<<().
Float64()
static constexpr MaybeRegisterRepresentation v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Float64 () [inline], [static], [constexpr]
Definition at line 69 of file representations.h.
                                                         {
    return MaybeRegisterRepresentation(Enum::kFloat64);
  }
References kFloat64, and MaybeRegisterRepresentation().
Referenced by v8::internal::compiler::turboshaft::FastApiCallOp::argument_representation(), bit_width(), v8::internal::compiler::turboshaft::Float64SameValueOp::inputs_rep(), machine_representation(), and v8::internal::compiler::turboshaft::operator<<().
is_valid()
constexpr bool v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::is_valid () const [inline], [constexpr]
Definition at line 39 of file representations.h.
{ return value_ != kInvalid; }
References kInvalid, and value_.
Referenced by value().
IsFloat()
constexpr bool v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::IsFloat () const [inline], [constexpr]
Definition at line 109 of file representations.h.
                                 {
    switch (*this) {
      case Enum::kFloat32:
      case Enum::kFloat64:
        return true;
      case Enum::kWord32:
      case Enum::kWord64:
      case Enum::kTagged:
      case Enum::kCompressed:
      case Enum::kSimd128:
      case Enum::kSimd256:
      case Enum::kNone:
        return false;
    }
  }
References kCompressed, kFloat32, kFloat64, kNone, kSimd128, kSimd256, kTagged, kWord32, and kWord64.
Referenced by v8::internal::compiler::turboshaft::FloatRepresentation::FloatRepresentation(), and v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual().
IsTaggedOrCompressed()
constexpr bool v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::IsTaggedOrCompressed () const [inline], [constexpr]
Definition at line 125 of file representations.h.
                                              {
    switch (*this) {
      case Enum::kTagged:
      case Enum::kCompressed:
        return true;
      case Enum::kWord32:
      case Enum::kWord64:
      case Enum::kFloat32:
      case Enum::kFloat64:
      case Enum::kSimd128:
      case Enum::kSimd256:
      case Enum::kNone:
        return false;
    }
  }
References kCompressed, kFloat32, kFloat64, kNone, kSimd128, kSimd256, kTagged, kWord32, and kWord64.
Referenced by v8::internal::compiler::turboshaft::TaggedBitcastOp::Validate().
IsWord()
constexpr bool v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::IsWord () const [inline], [constexpr]
Definition at line 93 of file representations.h.
                                {
    switch (*this) {
      case Enum::kWord32:
      case Enum::kWord64:
        return true;
      case Enum::kFloat32:
      case Enum::kFloat64:
      case Enum::kTagged:
      case Enum::kCompressed:
      case Enum::kSimd128:
      case Enum::kSimd256:
      case Enum::kNone:
        return false;
    }
  }
References kCompressed, kFloat32, kFloat64, kNone, kSimd128, kSimd256, kTagged, kWord32, and kWord64.
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual(), v8::internal::compiler::turboshaft::TaggedBitcastOp::Validate(), and v8::internal::compiler::turboshaft::WordRepresentation::WordRepresentation().
machine_representation()
MachineRepresentation v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::machine_representation () const [inline]
Definition at line 158 of file representations.h.
                                                       {
    switch (this->value()) {
      case Word32():
        return MachineRepresentation::kWord32;
      case Word64():
        return MachineRepresentation::kWord64;
      case Float32():
        return MachineRepresentation::kFloat32;
      case Float64():
        return MachineRepresentation::kFloat64;
      case Tagged():
        return MachineRepresentation::kTagged;
      case Compressed():
        return MachineRepresentation::kCompressed;
      case Simd128():
        return MachineRepresentation::kSimd128;
      case Simd256():
        return MachineRepresentation::kSimd256;
      case None():
        UNREACHABLE();
    }
  }
References Compressed(), Float32(), Float64(), v8::internal::kCompressed, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kWord32, v8::internal::kWord64, None(), Simd128(), Simd256(), Tagged(), v8::internal::UNREACHABLE(), value(), Word32(), and Word64().
Referenced by v8::internal::compiler::InstructionSelector::MarkAsRepresentation(), and v8::internal::compiler::InstructionSelector::VisitNode().
MaxUnsignedValue()
uint64_t v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::MaxUnsignedValue () const [inline]
Definition at line 141 of file representations.h.
                                    {
    switch (this->value()) {
      case Word32():
        return std::numeric_limits<uint32_t>::max();
      case Word64():
        return std::numeric_limits<uint64_t>::max();
      case Enum::kFloat32:
      case Enum::kFloat64:
      case Enum::kTagged:
      case Enum::kCompressed:
      case Enum::kSimd128:
      case Enum::kSimd256:
      case Enum::kNone:
        UNREACHABLE();
    }
  }
References kCompressed, kFloat32, kFloat64, kNone, kSimd128, kSimd256, kTagged, v8::internal::UNREACHABLE(), value(), Word32(), and Word64().
Referenced by v8::internal::compiler::turboshaft::MachineOptimizationReducer< Next >::ReduceCompareEqual().
None()
static constexpr MaybeRegisterRepresentation v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::None () [inline], [static], [constexpr]
Definition at line 89 of file representations.h.
                                                      {
    return MaybeRegisterRepresentation(Enum::kNone);
  }
References kNone, and MaybeRegisterRepresentation().
Referenced by v8::internal::compiler::turboshaft::FastApiCallOp::argument_representation(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::Bind(), bit_width(), v8::internal::compiler::turboshaft::GraphVisitor< AfterNext >::CreateOldToNewMapping(), v8::internal::compiler::turboshaft::CallOp::inputs_rep(), v8::internal::compiler::turboshaft::FastApiCallOp::inputs_rep(), machine_representation(), v8::internal::compiler::turboshaft::VariableReducer< AfterNext >::MergeOpIndices(), v8::internal::compiler::turboshaft::OperationT< Derived >::New(), and v8::internal::compiler::turboshaft::operator<<().
operator Enum()
constexpr v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::operator Enum () const [inline], [constexpr]
Definition at line 46 of file representations.h.
{ return value(); }
References value().
Simd128()
static constexpr MaybeRegisterRepresentation v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Simd128 () [inline], [static], [constexpr]
Definition at line 81 of file representations.h.
                                                         {
    return MaybeRegisterRepresentation(Enum::kSimd128);
  }
References kSimd128, and MaybeRegisterRepresentation().
Referenced by bit_width(), machine_representation(), v8::internal::compiler::turboshaft::operator<<(), and v8::internal::compiler::turboshaft::Simd128UseMap::Simd128UseMap().
Simd256()
static constexpr MaybeRegisterRepresentation v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Simd256 () [inline], [static], [constexpr]
Definition at line 85 of file representations.h.
                                                         {
    return MaybeRegisterRepresentation(Enum::kSimd256);
  }
References kSimd256, and MaybeRegisterRepresentation().
Referenced by bit_width(), machine_representation(), and v8::internal::compiler::turboshaft::operator<<().
Tagged()
static constexpr MaybeRegisterRepresentation v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Tagged () [inline], [static], [constexpr]
Definition at line 73 of file representations.h.
                                                        {
    return MaybeRegisterRepresentation(Enum::kTagged);
  }
References kTagged, and MaybeRegisterRepresentation().
Referenced by v8::internal::compiler::turboshaft::FastApiCallOp::argument_representation(), bit_width(), v8::internal::compiler::turboshaft::GenericBinopOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadOp::inputs_rep(), v8::internal::compiler::turboshaft::CallOp::inputs_rep(), v8::internal::compiler::turboshaft::TailCallOp::inputs_rep(), v8::internal::compiler::turboshaft::ConvertJSPrimitiveToObjectOp::inputs_rep(), v8::internal::compiler::turboshaft::NewConsStringOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadFieldByIndexOp::inputs_rep(), v8::internal::compiler::turboshaft::BigIntBinopOp::inputs_rep(), v8::internal::compiler::turboshaft::BigIntComparisonOp::inputs_rep(), v8::internal::compiler::turboshaft::StringAtOp::inputs_rep(), v8::internal::compiler::turboshaft::StringIndexOfOp::inputs_rep(), v8::internal::compiler::turboshaft::StringFromCodePointAtOp::inputs_rep(), v8::internal::compiler::turboshaft::StringSubstringOp::inputs_rep(), v8::internal::compiler::turboshaft::StringConcatOp::inputs_rep(), v8::internal::compiler::turboshaft::StringComparisonOp::inputs_rep(), v8::internal::compiler::turboshaft::StringOrOddballStrictEqualOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadTypedElementOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadDataViewElementOp::inputs_rep(), v8::internal::compiler::turboshaft::CheckEqualsInternalizedStringOp::inputs_rep(), v8::internal::compiler::turboshaft::StoreMessageOp::inputs_rep(), v8::internal::compiler::turboshaft::SameValueOp::inputs_rep(), v8::internal::compiler::turboshaft::FastApiCallOp::inputs_rep(), v8::internal::compiler::turboshaft::EnsureWritableFastElementsOp::inputs_rep(), v8::internal::compiler::turboshaft::MaybeGrowFastElementsOp::inputs_rep(), v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::inputs_rep(), machine_representation(), and v8::internal::compiler::turboshaft::operator<<().
value()
constexpr Enum v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::value () const [inline], [constexpr]
Definition at line 41 of file representations.h.
                               {
    DCHECK(is_valid());
    return value_;
  }
References v8::internal::DCHECK(), is_valid(), and value_.
Referenced by bit_width(), v8::internal::compiler::turboshaft::hash_value(), machine_representation(), MaxUnsignedValue(), operator Enum(), v8::internal::compiler::turboshaft::operator!=(), v8::internal::compiler::turboshaft::operator==(), and v8::internal::compiler::turboshaft::RegisterRepresentation::value().
Word32()
static constexpr MaybeRegisterRepresentation v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word32 () [inline], [static], [constexpr]
Definition at line 48 of file representations.h.
                                                        {
    return MaybeRegisterRepresentation(Enum::kWord32);
  }
References kWord32, and MaybeRegisterRepresentation().
Referenced by v8::internal::compiler::turboshaft::FastApiCallOp::argument_representation(), bit_width(), v8::internal::compiler::turboshaft::Word32PairBinopOp::inputs_rep(), v8::internal::compiler::turboshaft::BitcastWord32PairToFloat64Op::inputs_rep(), v8::internal::compiler::turboshaft::CallOp::inputs_rep(), v8::internal::compiler::turboshaft::TailCallOp::inputs_rep(), v8::internal::compiler::turboshaft::NewConsStringOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadFieldByIndexOp::inputs_rep(), v8::internal::compiler::turboshaft::StringSubstringOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadDataViewElementOp::inputs_rep(), v8::internal::compiler::turboshaft::MaybeGrowFastElementsOp::inputs_rep(), v8::internal::compiler::turboshaft::FindOrderedHashEntryOp::inputs_rep(), machine_representation(), MaxUnsignedValue(), v8::internal::compiler::turboshaft::operator<<(), v8::internal::compiler::turboshaft::ExplicitTruncationReducer< Next >::ReduceOperation(), and WordPtr().
Word64()
static constexpr MaybeRegisterRepresentation v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::Word64 () [inline], [static], [constexpr]
Definition at line 52 of file representations.h.
                                                        {
    return MaybeRegisterRepresentation(Enum::kWord64);
  }
References kWord64, and MaybeRegisterRepresentation().
Referenced by v8::internal::compiler::turboshaft::FastApiCallOp::argument_representation(), bit_width(), machine_representation(), MaxUnsignedValue(), v8::internal::compiler::turboshaft::operator<<(), and WordPtr().
WordPtr()
static constexpr MaybeRegisterRepresentation v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::WordPtr () [inline], [static], [constexpr]
Definition at line 56 of file representations.h.
                                                         {
    if constexpr (kSystemPointerSize == 4) {
      return Word32();
    } else {
      DCHECK_EQ(kSystemPointerSize, 8);
      return Word64();
    }
  }
References DCHECK_EQ, v8::internal::kSystemPointerSize, Word32(), and Word64().
Referenced by v8::internal::compiler::turboshaft::LoadOp::inputs_rep(), v8::internal::compiler::turboshaft::CallOp::inputs_rep(), v8::internal::compiler::turboshaft::TailCallOp::inputs_rep(), v8::internal::compiler::turboshaft::StringAtOp::inputs_rep(), v8::internal::compiler::turboshaft::StringFromCodePointAtOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadTypedElementOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadDataViewElementOp::inputs_rep(), v8::internal::compiler::turboshaft::LoadStackArgumentOp::inputs_rep(), v8::internal::compiler::turboshaft::StoreMessageOp::inputs_rep(), and v8::internal::compiler::turboshaft::RegisterRepresentation::WordPtr().
Member Data Documentation
kInvalid
constexpr Enum v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::kInvalid = static_cast<Enum>(-1) [static], [constexpr], [private]
Definition at line 207 of file representations.h.
Referenced by is_valid().
value_
Enum v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::value_ [private]
Definition at line 205 of file representations.h.
Referenced by is_valid(), and value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/representations.h