v8::base::VirtualAddressSpacePageAllocator Class Reference
#include <virtual-address-space-page-allocator.h>
Public Types
using Address = uintptr_t
Public Member Functions
VirtualAddressSpacePageAllocator (v8::VirtualAddressSpace *vas)
VirtualAddressSpacePageAllocator (const VirtualAddressSpacePageAllocator &)=delete
VirtualAddressSpacePageAllocator & operator= (const VirtualAddressSpacePageAllocator &)=delete
~VirtualAddressSpacePageAllocator () override=default
size_t AllocatePageSize () override
Gets the page granularity for AllocatePages and FreePages.
size_t CommitPageSize () override
Gets the page granularity for SetPermissions and ReleasePages.
void SetRandomMmapSeed (int64_t seed) override
Sets the random seed so that GetRandomMmapAddr() will generate repeatable sequences of random mmap addresses.
void * GetRandomMmapAddr () override
Returns a randomized address, suitable for memory allocation under ASLR.
void * AllocatePages (void *hint, size_t size, size_t alignment, Permission access) override
Allocates memory in range with the given alignment and permission.
bool FreePages (void *address, size_t size) override
Frees memory in a range that was allocated by a call to AllocatePages.
bool ReleasePages (void *address, size_t size, size_t new_size) override
Releases memory in a range that was allocated by a call to AllocatePages.
bool SetPermissions (void *address, size_t size, Permission access) override
Sets permissions on pages in an allocated range.
bool RecommitPages (void *address, size_t size, PageAllocator::Permission access) override
Recommits discarded pages in the given range with given permissions.
bool DiscardSystemPages (void *address, size_t size) override
Frees memory in the given [address, address + size) range.
bool DecommitPages (void *address, size_t size) override
Decommits any wired memory pages in the given range, allowing the OS to reclaim them, and marks the region as inacessible (kNoAccess).
bool SealPages (void *address, size_t size) override
Block any modifications to the given mapping such as changing permissions or unmapping the pages on supported platforms.
Private Attributes
v8::VirtualAddressSpace * vas_
std::unordered_map< Address, size_t > resized_allocations_
Mutex mutex_
Detailed Description
Definition at line 20 of file virtual-address-space-page-allocator.h.
Member Typedef Documentation
Address
using v8::base::VirtualAddressSpacePageAllocator::Address = uintptr_t
Definition at line 23 of file virtual-address-space-page-allocator.h.
Constructor & Destructor Documentation
VirtualAddressSpacePageAllocator() [1/2]
v8::base::VirtualAddressSpacePageAllocator::VirtualAddressSpacePageAllocator (v8::VirtualAddressSpace * vas) [explicit]
Definition at line 10 of file virtual-address-space-page-allocator.cc.
    : vas_(vas) {}
VirtualAddressSpacePageAllocator() [2/2]
v8::base::VirtualAddressSpacePageAllocator::VirtualAddressSpacePageAllocator (const VirtualAddressSpacePageAllocator &) [delete]
 VirtualAddressSpacePageAllocator()
v8::base::VirtualAddressSpacePageAllocator::~VirtualAddressSpacePageAllocator () [override], [default]
Member Function Documentation
AllocatePages()
void * v8::base::VirtualAddressSpacePageAllocator::AllocatePages (void * address, size_t length, size_t alignment, Permission permissions) [override], [virtual]
Allocates memory in range with the given alignment and permission.
Implements v8::PageAllocator.
Definition at line 14 of file virtual-address-space-page-allocator.cc.
                                    {
  return reinterpret_cast<void*>(
      vas_->AllocatePages(reinterpret_cast<Address>(hint), size, alignment,
                          static_cast<PagePermissions>(access)));
}
References v8::VirtualAddressSpace::AllocatePages(), size(), and vas_.
AllocatePageSize()
size_t v8::base::VirtualAddressSpacePageAllocator::AllocatePageSize () [inline], [override], [virtual]
Gets the page granularity for AllocatePages and FreePages.
Addresses and lengths for those calls should be multiples of AllocatePageSize().
Implements v8::PageAllocator.
Definition at line 33 of file virtual-address-space-page-allocator.h.
{ return vas_->allocation_granularity(); }
CommitPageSize()
size_t v8::base::VirtualAddressSpacePageAllocator::CommitPageSize () [inline], [override], [virtual]
Gets the page granularity for SetPermissions and ReleasePages.
Addresses and lengths for those calls should be multiples of CommitPageSize().
Implements v8::PageAllocator.
Definition at line 35 of file virtual-address-space-page-allocator.h.
{ return vas_->page_size(); }
DecommitPages()
bool v8::base::VirtualAddressSpacePageAllocator::DecommitPages (void * address, size_t size) [override], [virtual]
Decommits any wired memory pages in the given range, allowing the OS to reclaim them, and marks the region as inacessible (kNoAccess).
The address range stays reserved and can be accessed again later by changing its permissions. However, in that case the memory content is guaranteed to be zero-initialized again. The memory must have been previously allocated by a call to AllocatePages. Returns true on success, false otherwise.
Implements v8::PageAllocator.
Definition at line 71 of file virtual-address-space-page-allocator.cc.
                                                                  {
  return vas_->DecommitPages(reinterpret_cast<Address>(address), size);
}
References v8::VirtualAddressSpace::DecommitPages(), size(), and vas_.
DiscardSystemPages()
bool v8::base::VirtualAddressSpacePageAllocator::DiscardSystemPages (void * address, size_t size) [override], [virtual]
Frees memory in the given [address, address + size) range.
address and size should be operating system page-aligned. The next write to this memory area brings the memory transparently back. This should be treated as a hint to the OS that the pages are no longer needed. It does not guarantee that the pages will be discarded immediately or at all.
Reimplemented from v8::PageAllocator.
Definition at line 66 of file virtual-address-space-page-allocator.cc.
                                                                       {
  return vas_->DiscardSystemPages(reinterpret_cast<Address>(address), size);
}
References v8::VirtualAddressSpace::DiscardSystemPages(), size(), and vas_.
FreePages()
bool v8::base::VirtualAddressSpacePageAllocator::FreePages (void * address, size_t length) [override], [virtual]
Frees memory in a range that was allocated by a call to AllocatePages.
Implements v8::PageAllocator.
Definition at line 22 of file virtual-address-space-page-allocator.cc.
                                                                       {
  MutexGuard guard(&mutex_);
  Address address = reinterpret_cast<Address>(ptr);
  // Was this allocation resized previously? If so, use the original size.
  auto result = resized_allocations_.find(address);
  if (result != resized_allocations_.end()) {
    size = result->second;
    resized_allocations_.erase(result);
  }
  vas_->FreePages(address, size);
  return true;
}
References v8::VirtualAddressSpace::FreePages(), mutex_, resized_allocations_, v8::base::internal::result, size(), and vas_.
GetRandomMmapAddr()
void* v8::base::VirtualAddressSpacePageAllocator::GetRandomMmapAddr () [inline], [override], [virtual]
Returns a randomized address, suitable for memory allocation under ASLR.
The address will be aligned to AllocatePageSize.
Implements v8::PageAllocator.
Definition at line 39 of file virtual-address-space-page-allocator.h.
                                     {
    return reinterpret_cast<void*>(vas_->RandomPageAddress());
  }
operator=()
VirtualAddressSpacePageAllocator& v8::base::VirtualAddressSpacePageAllocator::operator= (const VirtualAddressSpacePageAllocator &) [delete]
RecommitPages()
bool v8::base::VirtualAddressSpacePageAllocator::RecommitPages (void * address, size_t length, PageAllocator::Permission permissions) [override], [virtual]
Recommits discarded pages in the given range with given permissions.
Discarded pages must be recommitted with their original permissions before they are used again.
Reimplemented from v8::PageAllocator.
Definition at line 60 of file virtual-address-space-page-allocator.cc.
                                                                {
  return vas_->RecommitPages(reinterpret_cast<Address>(address), size,
                             static_cast<PagePermissions>(access));
}
References v8::VirtualAddressSpace::RecommitPages(), size(), and vas_.
ReleasePages()
bool v8::base::VirtualAddressSpacePageAllocator::ReleasePages (void * address, size_t length, size_t new_length) [override], [virtual]
Releases memory in a range that was allocated by a call to AllocatePages.
Implements v8::PageAllocator.
Definition at line 35 of file virtual-address-space-page-allocator.cc.
                                                                     {
  // The VirtualAddressSpace class doesn't support this method because it can't
  // be properly implemented on top of Windows placeholder mappings (they cannot
  // be partially freed or resized while being allocated). Instead, we emulate
  // this behaviour by decommitting the released pages, which in effect achieves
  // exactly what ReleasePages would normally do as well. However, we still need
  // to pass the original size to FreePages eventually, so we'll need to keep
  // track of that.
  DCHECK_LE(new_size, size);
  MutexGuard guard(&mutex_);
  // Will fail if the allocation was resized previously, which is desired.
  Address address = reinterpret_cast<Address>(ptr);
  resized_allocations_.insert({address, size});
  CHECK(vas_->DecommitPages(address + new_size, size - new_size));
  return true;
}
References CHECK, DCHECK_LE, v8::VirtualAddressSpace::DecommitPages(), mutex_, resized_allocations_, size(), and vas_.
SealPages()
bool v8::base::VirtualAddressSpacePageAllocator::SealPages (void * address, size_t length) [override], [virtual]
Block any modifications to the given mapping such as changing permissions or unmapping the pages on supported platforms.
The address space reservation will exist until the process ends, but it's possible to release the memory using DiscardSystemPages. Note that this might require write permissions to the page as e.g. on Linux, mseal will block discarding sealed anonymous memory.
Reimplemented from v8::PageAllocator.
Definition at line 76 of file virtual-address-space-page-allocator.cc.
                                                                           {
  return false;
}
SetPermissions()
bool v8::base::VirtualAddressSpacePageAllocator::SetPermissions (void * address, size_t length, Permission permissions) [override], [virtual]
Sets permissions on pages in an allocated range.
Implements v8::PageAllocator.
Definition at line 54 of file virtual-address-space-page-allocator.cc.
                                                                {
  return vas_->SetPagePermissions(reinterpret_cast<Address>(address), size,
                                  static_cast<PagePermissions>(access));
}
References v8::VirtualAddressSpace::SetPagePermissions(), size(), and vas_.
SetRandomMmapSeed()
void v8::base::VirtualAddressSpacePageAllocator::SetRandomMmapSeed (int64_t seed) [inline], [override], [virtual]
Sets the random seed so that GetRandomMmapAddr() will generate repeatable sequences of random mmap addresses.
Implements v8::PageAllocator.
Definition at line 37 of file virtual-address-space-page-allocator.h.
{ vas_->SetRandomSeed(seed); }
Member Data Documentation
mutex_
Mutex v8::base::VirtualAddressSpacePageAllocator::mutex_ [private]
Definition at line 72 of file virtual-address-space-page-allocator.h.
Referenced by FreePages(), and ReleasePages().
resized_allocations_
std::unordered_map<Address, size_t> v8::base::VirtualAddressSpacePageAllocator::resized_allocations_ [private]
Definition at line 69 of file virtual-address-space-page-allocator.h.
Referenced by FreePages(), and ReleasePages().
vas_
v8::VirtualAddressSpace* v8::base::VirtualAddressSpacePageAllocator::vas_ [private]
Definition at line 64 of file virtual-address-space-page-allocator.h.
Referenced by AllocatePages(), DecommitPages(), DiscardSystemPages(), FreePages(), RecommitPages(), ReleasePages(), and SetPermissions().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/base/virtual-address-space-page-allocator.h
/mnt/V8SourceCode/src/base/virtual-address-space-page-allocator.cc