v8::internal::MessageFormatter Class Reference
#include <messages.h>
Static Public Member Functions
static V8_EXPORT_PRIVATE const char * TemplateString (MessageTemplate index)
static V8_EXPORT_PRIVATE MaybeHandle< String > TryFormat (Isolate *isolate, MessageTemplate index, base::Vector< const DirectHandle< String >> args)
static DirectHandle< String > Format (Isolate *isolate, MessageTemplate index, base::Vector< const DirectHandle< Object >> args)
Detailed Description
Definition at line 156 of file messages.h.
Member Function Documentation
Format()
DirectHandle< String > v8::internal::MessageFormatter::Format (Isolate * isolate, MessageTemplate index, base::Vector< const DirectHandle< Object >> args) [static]
Definition at line 397 of file messages.cc.
                                                 {
  constexpr size_t kMaxArgs = 3;
  DirectHandle<String> arg_strings[kMaxArgs];
  DCHECK_LE(args.size(), kMaxArgs);
  for (size_t i = 0; i < args.size(); ++i) {
    DCHECK(!args[i].is_null());
    arg_strings[i] = Object::NoSideEffectsToString(isolate, args[i]);
  }
  v8::TryCatch try_catch(reinterpret_cast<v8::Isolate*>(isolate));
  try_catch.SetVerbose(false);
  try_catch.SetCaptureMessage(false);
  MaybeHandle<String> maybe_result_string = MessageFormatter::TryFormat(
      isolate, index, base::VectorOf(arg_strings, args.size()));
  Handle<String> result_string;
  if (!maybe_result_string.ToHandle(&result_string)) {
    DCHECK(isolate->has_exception());
    return isolate->factory()->InternalizeString(
        base::StaticCharVector("<error>"));
  }
  // A string that has been obtained from JS code in this way is
  // likely to be a complicated ConsString of some sort. We flatten it
  // here to improve the efficiency of converting it to a C string and
  // other operations that are likely to take place (see GetLocalizedMessage
  // for example).
  return String::Flatten(isolate, result_string);
}
References v8::base::args, v8::internal::DCHECK(), DCHECK_LE, v8::internal::Isolate::factory(), v8::internal::Isolate::has_exception(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::index, v8::internal::Factory::InternalizeString(), v8::internal::Object::NoSideEffectsToString(), v8::TryCatch::SetCaptureMessage(), v8::TryCatch::SetVerbose(), v8::base::StaticCharVector(), v8::internal::MaybeHandle< T >::ToHandle(), TryFormat(), and v8::base::VectorOf().
Referenced by v8::internal::PendingCompilationErrorHandler::FormatErrorMessageForTest(), v8::internal::MessageHandler::GetMessage(), v8::internal::ErrorUtils::MakeGenericError(), v8::internal::RUNTIME_FUNCTION(), v8::internal::ErrorUtils::ShadowRealmConstructTypeErrorCopy(), and v8::internal::ValueSerializer::ThrowDataCloneError().
TemplateString()
const char * v8::internal::MessageFormatter::TemplateString (MessageTemplate index) [static]
Definition at line 426 of file messages.cc.
                                                                  {
  switch (index) {
#define CASE(NAME, STRING) \
  case MessageTemplate::k##NAME: \
    return STRING;
    MESSAGE_TEMPLATES(CASE)
#undef CASE
    case MessageTemplate::kMessageCount:
      UNREACHABLE();
  }
  SBXCHECK(false);
}
References CASE, v8::internal::index, v8::internal::kMessageCount, MESSAGE_TEMPLATES, SBXCHECK, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::InstanceBuilder::LoadTableSegments(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::MaybeMarkError(), v8::internal::Isolate::StackOverflow(), v8::internal::wasm::WasmOpcodes::TrapReasonMessage(), and TryFormat().
TryFormat()
MaybeHandle< String > v8::internal::MessageFormatter::TryFormat (Isolate * isolate, MessageTemplate index, base::Vector< const DirectHandle< String >> args) [static]
Definition at line 439 of file messages.cc.
                                                 {
  const char* template_string = TemplateString(index);
  IncrementalStringBuilder builder(isolate);
  // TODO(14386): Get this list empty.
  static constexpr MessageTemplate kTemplatesWithMismatchedArguments[] = {
      MessageTemplate::kConstAssign,
      MessageTemplate::kConstructorNotReceiver,
      MessageTemplate::kDataCloneErrorDetachedArrayBuffer,
      MessageTemplate::kDataCloneErrorOutOfMemory,
      MessageTemplate::kIncompatibleMethodReceiver,
      MessageTemplate::kInvalidArgument,
      MessageTemplate::kInvalidArrayLength,
      MessageTemplate::kInvalidAtomicAccessIndex,
      MessageTemplate::kInvalidDataViewLength,
      MessageTemplate::kInvalidIndex,
      MessageTemplate::kInvalidLhsInAssignment,
      MessageTemplate::kInvalidLhsInFor,
      MessageTemplate::kInvalidLhsInPostfixOp,
      MessageTemplate::kInvalidLhsInPrefixOp,
      MessageTemplate::kInvalidPrivateBrandReinitialization,
      MessageTemplate::kInvalidPrivateFieldReinitialization,
      MessageTemplate::kInvalidPrivateMemberWrite,
      MessageTemplate::kInvalidRegExpExecResult,
      MessageTemplate::kInvalidTimeValue,
      MessageTemplate::kInvalidWeakMapKey,
      MessageTemplate::kInvalidWeakSetValue,
      MessageTemplate::kIteratorReduceNoInitial,
      MessageTemplate::kJsonParseShortString,
      MessageTemplate::kJsonParseUnexpectedEOS,
      MessageTemplate::kJsonParseUnexpectedTokenEndStringWithContext,
      MessageTemplate::kJsonParseUnexpectedTokenShortString,
      MessageTemplate::kJsonParseUnexpectedTokenStartStringWithContext,
      MessageTemplate::kJsonParseUnexpectedTokenSurroundStringWithContext,
      MessageTemplate::kMustBePositive,
      MessageTemplate::kNotIterable,
      MessageTemplate::kNotTypedArray,
      MessageTemplate::kProxyNonObject,
      MessageTemplate::kProxyPrivate,
      MessageTemplate::kProxyRevoked,
      MessageTemplate::kProxyTrapReturnedFalsishFor,
      MessageTemplate::kReduceNoInitial,
      MessageTemplate::kSpreadIteratorSymbolNonCallable,
      MessageTemplate::kSymbolIteratorInvalid,
      MessageTemplate::kTopLevelAwaitStalled,
      MessageTemplate::kUndefinedOrNullToObject,
      MessageTemplate::kUnexpectedStrictReserved,
      MessageTemplate::kUnexpectedTokenIdentifier,
      MessageTemplate::kWeakRefsCleanupMustBeCallable};
  base::Vector<const DirectHandle<String>> remaining_args = args;
  for (const char* c = template_string; *c != '\0'; c++) {
    if (*c == '%') {
      // %% results in verbatim %.
      if (*(c + 1) == '%') {
        c++;
        builder.AppendCharacter('%');
      } else {
        // TODO(14386): Remove this fallback.
        if (remaining_args.empty()) {
          if (std::count(std::begin(kTemplatesWithMismatchedArguments),
                         std::end(kTemplatesWithMismatchedArguments), index)) {
            builder.AppendCString("undefined");
          } else {
            FATAL("Missing argument to template (got %zu): %s", args.size(),
                  template_string);
          }
        } else {
          DirectHandle<String> arg = remaining_args[0];
          remaining_args += 1;
          builder.AppendString(arg);
        }
      }
    } else {
      builder.AppendCharacter(*c);
    }
  }
  if (!remaining_args.empty() &&
      std::count(std::begin(kTemplatesWithMismatchedArguments),
                 std::end(kTemplatesWithMismatchedArguments), index) == 0) {
    FATAL("Too many arguments to template (expected %zu, got %zu): %s",
          args.size() - remaining_args.size(), args.size(), template_string);
  }
  return indirect_handle(builder.Finish(), isolate);
}
References v8::internal::IncrementalStringBuilder::AppendCharacter(), v8::internal::IncrementalStringBuilder::AppendCString(), v8::internal::IncrementalStringBuilder::AppendString(), v8::base::args, v8::internal::compiler::begin(), v8::base::Vector< T >::empty(), v8::internal::compiler::end(), FATAL, v8::internal::IncrementalStringBuilder::Finish(), v8::internal::index, v8::internal::indirect_handle(), v8::internal::trap_handler::kInvalidIndex, v8::base::Vector< T >::size(), and TemplateString().
Referenced by Format().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/messages.h
/mnt/V8SourceCode/src/execution/messages.cc