v8::internal::compiler::InstructionOperandIterator Class Reference
#include <code-generator.h>
Public Member Functions
InstructionOperandIterator (Instruction *instr, size_t pos)
Instruction * instruction () const
InstructionOperand * Advance ()
Private Attributes
Instruction * instr_
size_t pos_
Detailed Description
Definition at line 45 of file code-generator.h.
Constructor & Destructor Documentation
InstructionOperandIterator()
v8::internal::compiler::InstructionOperandIterator::InstructionOperandIterator (Instruction * instr, size_t pos) [inline]
Definition at line 47 of file code-generator.h.
      : instr_(instr), pos_(pos) {}
Member Function Documentation
Advance()
InstructionOperand* v8::internal::compiler::InstructionOperandIterator::Advance () [inline]
Definition at line 51 of file code-generator.h.
{ return instr_->InputAt(pos_++); }
References v8::internal::compiler::Instruction::InputAt(), instr_, and pos_.
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
instruction()
Instruction* v8::internal::compiler::InstructionOperandIterator::instruction () const [inline]
Definition at line 50 of file code-generator.h.
{ return instr_; }
References instr_.
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor(), and v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
Member Data Documentation
instr_
Instruction* v8::internal::compiler::InstructionOperandIterator::instr_ [private]
Definition at line 54 of file code-generator.h.
Referenced by Advance(), and instruction().
pos_
size_t v8::internal::compiler::InstructionOperandIterator::pos_ [private]
Definition at line 55 of file code-generator.h.
Referenced by Advance().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/code-generator.h