v8::internal::StressConcurrentAllocationObserver Class Reference
Public Member Functions
StressConcurrentAllocationObserver (Heap *heap)
void Step (int bytes_allocated, Address, size_t) override
Private Attributes
Heap * heap_
Additional Inherited Members
Detailed Description
Definition at line 5941 of file heap.cc.
Constructor & Destructor Documentation
StressConcurrentAllocationObserver()
v8::internal::StressConcurrentAllocationObserver::StressConcurrentAllocationObserver (Heap * heap) [inline], [explicit]
Definition at line 5943 of file heap.cc.
      : AllocationObserver(1024), heap_(heap) {}
Member Function Documentation
Step()
void v8::internal::StressConcurrentAllocationObserver::Step (int bytes_allocated, Address , size_t) [inline], [override], [virtual]
Implements v8::internal::AllocationObserver.
Definition at line 5946 of file heap.cc.
                                                           {
    DCHECK(heap_->deserialization_complete());
    if (v8_flags.stress_concurrent_allocation) {
      // Only schedule task if --stress-concurrent-allocation is enabled. This
      // allows tests to disable flag even when Isolate was already initialized.
      StressConcurrentAllocationTask::Schedule(heap_->isolate());
    }
    heap_->RemoveAllocationObserversFromAllSpaces(this, this);
    heap_->need_to_remove_stress_concurrent_allocation_observer_ = false;
  }
References v8::internal::DCHECK(), v8::internal::Heap::deserialization_complete(), heap_, v8::internal::Heap::isolate(), v8::internal::Heap::need_to_remove_stress_concurrent_allocation_observer_, v8::internal::Heap::RemoveAllocationObserversFromAllSpaces(), v8::internal::StressConcurrentAllocationTask::Schedule(), and v8::internal::v8_flags.
Member Data Documentation
heap_
Heap* v8::internal::StressConcurrentAllocationObserver::heap_ [private]
Definition at line 5958 of file heap.cc.
Referenced by Step().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/heap.cc