v8::internal::PossiblyEmptyBuckets Class Reference
#include <slot-set.h>
Public Member Functions
PossiblyEmptyBuckets ()=default
PossiblyEmptyBuckets (PossiblyEmptyBuckets &&other) V8_NOEXCEPT
~PossiblyEmptyBuckets ()
PossiblyEmptyBuckets (const PossiblyEmptyBuckets &)=delete
PossiblyEmptyBuckets & operator= (const PossiblyEmptyBuckets &)=delete
void Release ()
void Insert (size_t bucket_index, size_t buckets)
bool Contains (size_t bucket_index)
bool IsEmpty () const
Private Member Functions
bool IsAllocated ()
void Allocate (size_t buckets)
void InsertAllocated (size_t bucket_index)
uintptr_t * BitmapArray ()
FRIEND_TEST (PossiblyEmptyBucketsTest, WordsForBuckets)
Static Private Member Functions
static size_t WordsForBuckets (size_t buckets)
Private Attributes
Address bitmap_ = kNullAddress
Static Private Attributes
static constexpr Address kPointerTag = 1
static constexpr int kWordSize = sizeof(uintptr_t)
static constexpr int kBitsPerWord = kWordSize * kBitsPerByte
Detailed Description
Definition at line 34 of file slot-set.h.
Constructor & Destructor Documentation
PossiblyEmptyBuckets() [1/3]
v8::internal::PossiblyEmptyBuckets::PossiblyEmptyBuckets () [default]
PossiblyEmptyBuckets() [2/3]
v8::internal::PossiblyEmptyBuckets::PossiblyEmptyBuckets (PossiblyEmptyBuckets && other) [inline]
Definition at line 37 of file slot-set.h.
      : bitmap_(other.bitmap_) {
    other.bitmap_ = kNullAddress;
  }
References v8::internal::kNullAddress.
 PossiblyEmptyBuckets()
v8::internal::PossiblyEmptyBuckets::~PossiblyEmptyBuckets () [inline]
Definition at line 42 of file slot-set.h.
{ Release(); }
References Release().
PossiblyEmptyBuckets() [3/3]
v8::internal::PossiblyEmptyBuckets::PossiblyEmptyBuckets (const PossiblyEmptyBuckets &) [delete]
Member Function Documentation
Allocate()
void v8::internal::PossiblyEmptyBuckets::Allocate (size_t buckets) [inline], [private]
Definition at line 88 of file slot-set.h.
                                {
    DCHECK(!IsAllocated());
    size_t words = WordsForBuckets(buckets);
    uintptr_t* ptr = reinterpret_cast<uintptr_t*>(
        AlignedAllocWithRetry(words * kWordSize, kSystemPointerSize));
    ptr[0] = bitmap_ >> 1;
    for (size_t word_idx = 1; word_idx < words; word_idx++) {
      ptr[word_idx] = 0;
    }
    bitmap_ = reinterpret_cast<Address>(ptr) + kPointerTag;
    DCHECK(IsAllocated());
  }
References v8::internal::AlignedAllocWithRetry(), bitmap_, v8::internal::DCHECK(), IsAllocated(), kPointerTag, v8::internal::kSystemPointerSize, kWordSize, and WordsForBuckets().
Referenced by Insert().
BitmapArray()
uintptr_t* v8::internal::PossiblyEmptyBuckets::BitmapArray () [inline], [private]
Definition at line 113 of file slot-set.h.
                           {
    DCHECK(IsAllocated());
    return reinterpret_cast<uintptr_t*>(bitmap_ & ~kPointerTag);
  }
References bitmap_, v8::internal::DCHECK(), IsAllocated(), and kPointerTag.
Referenced by Contains(), InsertAllocated(), and Release().
Contains()
bool v8::internal::PossiblyEmptyBuckets::Contains (size_t bucket_index) [inline]
Definition at line 66 of file slot-set.h.
                                     {
    if (IsAllocated()) {
      size_t word_idx = bucket_index / kBitsPerWord;
      uintptr_t* word = BitmapArray() + word_idx;
      return *word &
             (static_cast<uintptr_t>(1) << (bucket_index % kBitsPerWord));
    } else if (bucket_index + 1 < kBitsPerWord) {
      return bitmap_ & (static_cast<uintptr_t>(1) << (bucket_index + 1));
    } else {
      return false;
    }
  }
References bitmap_, BitmapArray(), IsAllocated(), and kBitsPerWord.
Referenced by v8::internal::SlotSet::CheckPossiblyEmptyBuckets().
FRIEND_TEST()
v8::internal::PossiblyEmptyBuckets::FRIEND_TEST (PossiblyEmptyBucketsTest , WordsForBuckets) [private]
Insert()
void v8::internal::PossiblyEmptyBuckets::Insert (size_t bucket_index, size_t buckets) [inline]
Definition at line 55 of file slot-set.h.
                                                   {
    if (IsAllocated()) {
      InsertAllocated(bucket_index);
    } else if (bucket_index + 1 < kBitsPerWord) {
      bitmap_ |= static_cast<uintptr_t>(1) << (bucket_index + 1);
    } else {
      Allocate(buckets);
      InsertAllocated(bucket_index);
    }
  }
References Allocate(), bitmap_, InsertAllocated(), IsAllocated(), and kBitsPerWord.
Referenced by v8::internal::SlotSet::IterateAndTrackEmptyBuckets().
InsertAllocated()
void v8::internal::PossiblyEmptyBuckets::InsertAllocated (size_t bucket_index) [inline], [private]
Definition at line 102 of file slot-set.h.
                                            {
    DCHECK(IsAllocated());
    size_t word_idx = bucket_index / kBitsPerWord;
    uintptr_t* word = BitmapArray() + word_idx;
    *word |= static_cast<uintptr_t>(1) << (bucket_index % kBitsPerWord);
  }
References BitmapArray(), v8::internal::DCHECK(), IsAllocated(), and kBitsPerWord.
Referenced by Insert().
IsAllocated()
bool v8::internal::PossiblyEmptyBuckets::IsAllocated () [inline], [private]
Definition at line 86 of file slot-set.h.
{ return bitmap_ & kPointerTag; }
References bitmap_, and kPointerTag.
Referenced by Allocate(), BitmapArray(), Contains(), Insert(), InsertAllocated(), and Release().
IsEmpty()
bool v8::internal::PossiblyEmptyBuckets::IsEmpty () const [inline]
Definition at line 79 of file slot-set.h.
{ return bitmap_ == kNullAddress; }
References bitmap_, and v8::internal::kNullAddress.
Referenced by v8::internal::RememberedSet< type >::IterateAndTrackEmptyBuckets().
operator=()
PossiblyEmptyBuckets& v8::internal::PossiblyEmptyBuckets::operator= (const PossiblyEmptyBuckets &) [delete]
Release()
void v8::internal::PossiblyEmptyBuckets::Release () [inline]
Definition at line 47 of file slot-set.h.
                 {
    if (IsAllocated()) {
      AlignedFree(BitmapArray());
    }
    bitmap_ = kNullAddress;
    DCHECK(!IsAllocated());
  }
References v8::internal::AlignedFree(), bitmap_, BitmapArray(), v8::internal::DCHECK(), IsAllocated(), and v8::internal::kNullAddress.
Referenced by v8::internal::SlotSet::CheckPossiblyEmptyBuckets(), v8::internal::MutablePageMetadata::ReleaseAllocatedMemoryNeededForWritableChunk(), and ~PossiblyEmptyBuckets().
WordsForBuckets()
static size_t v8::internal::PossiblyEmptyBuckets::WordsForBuckets (size_t buckets) [inline], [static], [private]
Definition at line 109 of file slot-set.h.
                                                {
    return (buckets + kBitsPerWord - 1) / kBitsPerWord;
  }
References kBitsPerWord.
Referenced by Allocate().
Member Data Documentation
bitmap_
Address v8::internal::PossiblyEmptyBuckets::bitmap_ = kNullAddress [private]
Definition at line 118 of file slot-set.h.
Referenced by Allocate(), BitmapArray(), Contains(), Insert(), IsAllocated(), IsEmpty(), and Release().
kBitsPerWord
constexpr int v8::internal::PossiblyEmptyBuckets::kBitsPerWord = kWordSize * kBitsPerByte [static], [constexpr], [private]
Definition at line 84 of file slot-set.h.
Referenced by Contains(), Insert(), InsertAllocated(), and WordsForBuckets().
kPointerTag
constexpr Address v8::internal::PossiblyEmptyBuckets::kPointerTag = 1 [static], [constexpr], [private]
Definition at line 82 of file slot-set.h.
Referenced by Allocate(), BitmapArray(), and IsAllocated().
kWordSize
constexpr int v8::internal::PossiblyEmptyBuckets::kWordSize = sizeof(uintptr_t) [static], [constexpr], [private]
Definition at line 83 of file slot-set.h.
Referenced by Allocate().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/slot-set.h