v8::internal::compiler::DoubleEndedSplitVector< T > Class Template Reference
#include <register-allocator.h>
Public Types
using value_type = T
using iterator = T *
using const_iterator = const T *
Public Member Functions
ASSERT_TRIVIALLY_COPYABLE (T)
size_t size () const
bool empty () const
size_t capacity () const
T * data () const
void clear ()
T & operator[] (size_t position)
const T & operator[] (size_t position) const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
T & front ()
const T & front () const
T & back ()
const T & back () const
void push_front (Zone *zone, const T &value)
void pop_front ()
template<GrowthDirection direction = kFrontOrBack>
iterator insert (Zone *zone, const_iterator position, const T &value)
DoubleEndedSplitVector< T > SplitAt (const_iterator split_begin_const)
void Append (Zone *zone, DoubleEndedSplitVector< T > other)
Private Member Functions
size_t space_at_front () const
size_t space_at_back () const
template<GrowthDirection direction>
void EnsureOneMoreCapacityAt (Zone *zone)
template<GrowthDirection direction>
V8_NOINLINE V8_PRESERVE_MOST void GrowAt (Zone *zone, size_t new_minimum_capacity)
Private Attributes
T * storage_begin_ = nullptr
T * data_begin_ = nullptr
T * data_end_ = nullptr
T * storage_end_ = nullptr
Static Private Attributes
static constexpr size_t kMinCapacity = 2
Detailed Description
template<typename T>
class v8::internal::compiler::DoubleEndedSplitVector< T >
Definition at line 542 of file register-allocator.h.
Member Typedef Documentation
const_iterator
template<typename T >
using v8::internal::compiler::DoubleEndedSplitVector< T >::const_iterator = const T*
Definition at line 546 of file register-allocator.h.
iterator
template<typename T >
using v8::internal::compiler::DoubleEndedSplitVector< T >::iterator = T*
Definition at line 545 of file register-allocator.h.
value_type
template<typename T >
using v8::internal::compiler::DoubleEndedSplitVector< T >::value_type = T
Definition at line 544 of file register-allocator.h.
Member Function Documentation
Append()
template<typename T >
void v8::internal::compiler::DoubleEndedSplitVector< T >::Append (Zone * zone, DoubleEndedSplitVector< T > other) [inline]
Definition at line 680 of file register-allocator.h.
                                                           {
    if (data_end_ == other.data_begin_) {
      // The `other`s elements are directly adjacent to ours, so just extend
      // our storage to encompass them.
      // This could happen if `other` comes from an earlier `this->SplitAt()`.
      // For the usage here in the register allocator, this is always the case.
      DCHECK_EQ(other.storage_begin_, other.data_begin_);
      DCHECK_EQ(data_end_, storage_end_);
      data_end_ = other.data_end_;
      storage_end_ = other.storage_end_;
      return;
    }
    // General case: Copy into newly allocated vector.
    // TODO(dlehmann): One could check if `this` or `other` has enough capacity
    // such that one can avoid the allocation, but currently we never reach
    // this path anyway.
    DoubleEndedSplitVector<T> result;
    size_t merged_size = this->size() + other.size();
    result.GrowAt<kFront>(zone, merged_size);
    result.data_begin_ -= merged_size;
    std::copy(this->begin(), this->end(), result.data_begin_);
    std::copy(other.begin(), other.end(), result.data_begin_ + this->size());
    DCHECK_EQ(result.data_begin_ + merged_size, result.data_end_);
    *this = std::move(result);
#ifdef DEBUG
    Verify();
#endif
    DCHECK_EQ(size(), merged_size);
  }
References v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_, v8::internal::compiler::DoubleEndedSplitVector< T >::data_end_, DCHECK_EQ, v8::internal::compiler::DoubleEndedSplitVector< T >::end(), v8::internal::compiler::kFront, v8::base::internal::result, v8::internal::compiler::DoubleEndedSplitVector< T >::size(), v8::internal::compiler::DoubleEndedSplitVector< T >::storage_begin_, v8::internal::compiler::DoubleEndedSplitVector< T >::storage_end_, and v8::internal::this.
Referenced by v8::internal::compiler::LiveRange::AttachToNext().
ASSERT_TRIVIALLY_COPYABLE()
template<typename T >
v8::internal::compiler::DoubleEndedSplitVector< T >::ASSERT_TRIVIALLY_COPYABLE (T)
back() [1/2]
template<typename T >
T& v8::internal::compiler::DoubleEndedSplitVector< T >::back () [inline]
Definition at line 583 of file register-allocator.h.
            {
    DCHECK(!empty());
    return *std::prev(end());
  }
References v8::internal::DCHECK(), v8::internal::compiler::DoubleEndedSplitVector< T >::empty(), and v8::internal::compiler::DoubleEndedSplitVector< T >::end().
Referenced by v8::internal::compiler::LiveRange::SplitAt().
back() [2/2]
template<typename T >
const T& v8::internal::compiler::DoubleEndedSplitVector< T >::back () const [inline]
Definition at line 587 of file register-allocator.h.
                        {
    DCHECK(!empty());
    return *std::prev(end());
  }
References v8::internal::DCHECK(), v8::internal::compiler::DoubleEndedSplitVector< T >::empty(), and v8::internal::compiler::DoubleEndedSplitVector< T >::end().
begin() [1/2]
template<typename T >
iterator v8::internal::compiler::DoubleEndedSplitVector< T >::begin () [inline]
Definition at line 570 of file register-allocator.h.
{ return data_begin_; }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), v8::internal::compiler::TopLevelLiveRange::AddUsePosition(), v8::internal::compiler::LiveRange::AdvanceLastProcessedMarker(), v8::internal::compiler::DoubleEndedSplitVector< T >::Append(), v8::internal::compiler::LiveRange::Covers(), v8::internal::compiler::TopLevelLiveRange::EnsureInterval(), v8::internal::compiler::LiveRange::FirstIntersection(), v8::internal::compiler::LiveRange::FirstSearchIntervalForPosition(), v8::internal::compiler::DoubleEndedSplitVector< T >::front(), v8::internal::compiler::DoubleEndedSplitVector< T >::GrowAt(), v8::internal::compiler::DoubleEndedSplitVector< T >::insert(), and v8::internal::compiler::LiveRange::SplitAt().
begin() [2/2]
template<typename T >
const_iterator v8::internal::compiler::DoubleEndedSplitVector< T >::begin () const [inline]
Definition at line 571 of file register-allocator.h.
{ return data_begin_; }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_.
capacity()
template<typename T >
size_t v8::internal::compiler::DoubleEndedSplitVector< T >::capacity () const [inline]
Definition at line 555 of file register-allocator.h.
{ return storage_end_ - storage_begin_; }
References v8::internal::compiler::DoubleEndedSplitVector< T >::storage_begin_, and v8::internal::compiler::DoubleEndedSplitVector< T >::storage_end_.
Referenced by v8::internal::compiler::DoubleEndedSplitVector< T >::EnsureOneMoreCapacityAt().
clear()
template<typename T >
void v8::internal::compiler::DoubleEndedSplitVector< T >::clear () [inline]
Definition at line 559 of file register-allocator.h.
{ data_begin_ = data_end_; }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_, and v8::internal::compiler::DoubleEndedSplitVector< T >::data_end_.
data()
template<typename T >
T* v8::internal::compiler::DoubleEndedSplitVector< T >::data () const [inline]
Definition at line 557 of file register-allocator.h.
{ return data_begin_; }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_.
empty()
template<typename T >
bool v8::internal::compiler::DoubleEndedSplitVector< T >::empty () const [inline]
Definition at line 554 of file register-allocator.h.
{ return size() == 0; }
References v8::internal::compiler::DoubleEndedSplitVector< T >::size().
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), v8::internal::compiler::DoubleEndedSplitVector< T >::back(), v8::internal::compiler::TopLevelLiveRange::EnsureInterval(), v8::internal::compiler::DoubleEndedSplitVector< T >::front(), v8::internal::compiler::DoubleEndedSplitVector< T >::pop_front(), and v8::internal::compiler::LiveRange::SplitAt().
end() [1/2]
template<typename T >
iterator v8::internal::compiler::DoubleEndedSplitVector< T >::end () [inline]
Definition at line 572 of file register-allocator.h.
{ return data_end_; }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_end_.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUsePosition(), v8::internal::compiler::LiveRange::AdvanceLastProcessedMarker(), v8::internal::compiler::DoubleEndedSplitVector< T >::Append(), v8::internal::compiler::DoubleEndedSplitVector< T >::back(), v8::internal::compiler::LiveRange::FirstIntersection(), v8::internal::compiler::LiveRange::FirstSearchIntervalForPosition(), v8::internal::compiler::DoubleEndedSplitVector< T >::GrowAt(), v8::internal::compiler::DoubleEndedSplitVector< T >::insert(), v8::internal::compiler::LiveRange::NextEndAfter(), v8::internal::compiler::LiveRange::NextStartAfter(), and v8::internal::compiler::LiveRange::SplitAt().
end() [2/2]
template<typename T >
const_iterator v8::internal::compiler::DoubleEndedSplitVector< T >::end () const [inline]
Definition at line 573 of file register-allocator.h.
{ return data_end_; }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_end_.
EnsureOneMoreCapacityAt()
template<typename T >
template<GrowthDirection direction>
void v8::internal::compiler::DoubleEndedSplitVector< T >::EnsureOneMoreCapacityAt (Zone * zone) [inline], [private]
Definition at line 721 of file register-allocator.h.
                                                     {
    if constexpr (direction == kFront) {
      if (V8_LIKELY(space_at_front() > 0)) return;
      GrowAt<kFront>(zone, capacity() * 2);
      DCHECK_GT(space_at_front(), 0);
    } else {
      if (V8_LIKELY(space_at_front() > 0 || space_at_back() > 0)) return;
      GrowAt<kFrontOrBack>(zone, capacity() * 2);
      DCHECK(space_at_front() > 0 || space_at_back() > 0);
    }
  }
References v8::internal::compiler::DoubleEndedSplitVector< T >::capacity(), v8::internal::DCHECK(), DCHECK_GT, v8::internal::compiler::kFront, v8::internal::compiler::DoubleEndedSplitVector< T >::space_at_back(), v8::internal::compiler::DoubleEndedSplitVector< T >::space_at_front(), and V8_LIKELY.
front() [1/2]
template<typename T >
T& v8::internal::compiler::DoubleEndedSplitVector< T >::front () [inline]
Definition at line 575 of file register-allocator.h.
             {
    DCHECK(!empty());
    return *begin();
  }
References v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), v8::internal::DCHECK(), and v8::internal::compiler::DoubleEndedSplitVector< T >::empty().
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), v8::internal::compiler::TopLevelLiveRange::EnsureInterval(), and v8::internal::compiler::TopLevelLiveRange::ShortenTo().
front() [2/2]
template<typename T >
const T& v8::internal::compiler::DoubleEndedSplitVector< T >::front () const [inline]
Definition at line 579 of file register-allocator.h.
                         {
    DCHECK(!empty());
    return *begin();
  }
References v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), v8::internal::DCHECK(), and v8::internal::compiler::DoubleEndedSplitVector< T >::empty().
GrowAt()
template<typename T >
template<GrowthDirection direction>
V8_NOINLINE V8_PRESERVE_MOST void v8::internal::compiler::DoubleEndedSplitVector< T >::GrowAt (Zone * zone, size_t new_minimum_capacity) [inline], [private]
Definition at line 734 of file register-allocator.h.
                                                                        {
    DoubleEndedSplitVector<T> old = std::move(*this);
    size_t new_capacity = std::max(kMinCapacity, new_minimum_capacity);
    storage_begin_ = zone->AllocateArray<T>(new_capacity);
    storage_end_ = storage_begin_ + new_capacity;
    size_t remaining_capacity = new_capacity - old.size();
    size_t remaining_capacity_front =
        direction == kFront ? remaining_capacity : remaining_capacity / 2;
    data_begin_ = storage_begin_ + remaining_capacity_front;
    data_end_ = data_begin_ + old.size();
    std::copy(old.begin(), old.end(), data_begin_);
#ifdef DEBUG
    Verify();
#endif
    DCHECK_EQ(size(), old.size());
  }
References v8::internal::Zone::AllocateArray(), v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_, v8::internal::compiler::DoubleEndedSplitVector< T >::data_end_, DCHECK_EQ, v8::internal::compiler::DoubleEndedSplitVector< T >::end(), v8::internal::compiler::kFront, v8::internal::compiler::DoubleEndedSplitVector< T >::kMinCapacity, v8::internal::compiler::DoubleEndedSplitVector< T >::size(), v8::internal::compiler::DoubleEndedSplitVector< T >::storage_begin_, and v8::internal::compiler::DoubleEndedSplitVector< T >::storage_end_.
insert()
template<typename T >
template<GrowthDirection direction = kFrontOrBack>
iterator v8::internal::compiler::DoubleEndedSplitVector< T >::insert (Zone * zone, const_iterator position, const T & value) [inline]
Definition at line 606 of file register-allocator.h.
                                                                       {
    DCHECK_LE(begin(), position);
    DCHECK_LE(position, end());
    size_t old_size = size();
    size_t insert_index = position - data_begin_;
    EnsureOneMoreCapacityAt<direction>(zone);
    // Make space for the insertion.
    // Copy towards the end with more remaining space, such that over time
    // the data is roughly centered, which is beneficial in case of splitting.
    if (direction == kFront || space_at_front() >= space_at_back()) {
      // Copy to the left.
      DCHECK_GT(space_at_front(), 0);
      T* copy_src_begin = data_begin_;
      T* copy_src_end = data_begin_ + insert_index;
      --data_begin_;
      std::copy(copy_src_begin, copy_src_end, data_begin_);
    } else {
      // Copy to the right.
      DCHECK_GT(space_at_back(), 0);
      T* copy_src_begin = data_begin_ + insert_index;
      T* copy_src_end = data_end_;
      ++data_end_;
      std::copy_backward(copy_src_begin, copy_src_end, data_end_);
    }
    T* insert_position = data_begin_ + insert_index;
    *insert_position = value;
#ifdef DEBUG
    Verify();
#endif
    DCHECK_LE(begin(), insert_position);
    DCHECK_LT(insert_position, end());
    DCHECK_EQ(size(), old_size + 1);
    USE(old_size);
    return insert_position;
  }
References v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_, v8::internal::compiler::DoubleEndedSplitVector< T >::data_end_, DCHECK_EQ, DCHECK_GT, DCHECK_LE, DCHECK_LT, v8::internal::compiler::DoubleEndedSplitVector< T >::end(), v8::internal::compiler::kFront, v8::internal::compiler::DoubleEndedSplitVector< T >::size(), v8::internal::compiler::DoubleEndedSplitVector< T >::space_at_back(), v8::internal::compiler::DoubleEndedSplitVector< T >::space_at_front(), USE, and v8::internal::value.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUsePosition(), and v8::internal::compiler::LiveRange::SplitAt().
operator[]() [1/2]
template<typename T >
T& v8::internal::compiler::DoubleEndedSplitVector< T >::operator[] (size_t position) [inline]
Definition at line 561 of file register-allocator.h.
                                 {
    DCHECK_LT(position, size());
    return data_begin_[position];
  }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_, DCHECK_LT, and v8::internal::compiler::DoubleEndedSplitVector< T >::size().
operator[]() [2/2]
template<typename T >
const T& v8::internal::compiler::DoubleEndedSplitVector< T >::operator[] (size_t position) const [inline]
Definition at line 565 of file register-allocator.h.
                                             {
    DCHECK_LT(position, size());
    return data_begin_[position];
  }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_, DCHECK_LT, and v8::internal::compiler::DoubleEndedSplitVector< T >::size().
pop_front()
template<typename T >
void v8::internal::compiler::DoubleEndedSplitVector< T >::pop_front () [inline]
Definition at line 597 of file register-allocator.h.
                   {
    DCHECK(!empty());
    ++data_begin_;
  }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_, v8::internal::DCHECK(), and v8::internal::compiler::DoubleEndedSplitVector< T >::empty().
Referenced by v8::internal::compiler::TopLevelLiveRange::EnsureInterval().
push_front()
template<typename T >
void v8::internal::compiler::DoubleEndedSplitVector< T >::push_front (Zone * zone, const T & value) [inline]
Definition at line 592 of file register-allocator.h.
                                              {
    EnsureOneMoreCapacityAt<kFront>(zone);
    --data_begin_;
    *data_begin_ = value;
  }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_, and v8::internal::value.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), and v8::internal::compiler::TopLevelLiveRange::EnsureInterval().
size()
template<typename T >
size_t v8::internal::compiler::DoubleEndedSplitVector< T >::size () const [inline]
Definition at line 553 of file register-allocator.h.
{ return data_end_ - data_begin_; }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_, and v8::internal::compiler::DoubleEndedSplitVector< T >::data_end_.
Referenced by v8::internal::compiler::TopLevelLiveRange::AddUseInterval(), v8::internal::compiler::DoubleEndedSplitVector< T >::Append(), v8::internal::compiler::DoubleEndedSplitVector< T >::empty(), v8::internal::compiler::DoubleEndedSplitVector< T >::GrowAt(), v8::internal::compiler::DoubleEndedSplitVector< T >::insert(), v8::internal::compiler::DoubleEndedSplitVector< T >::operator[](), and v8::internal::compiler::DoubleEndedSplitVector< T >::SplitAt().
space_at_back()
template<typename T >
size_t v8::internal::compiler::DoubleEndedSplitVector< T >::space_at_back () const [inline], [private]
Definition at line 718 of file register-allocator.h.
{ return storage_end_ - data_end_; }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_end_, and v8::internal::compiler::DoubleEndedSplitVector< T >::storage_end_.
Referenced by v8::internal::compiler::DoubleEndedSplitVector< T >::EnsureOneMoreCapacityAt(), and v8::internal::compiler::DoubleEndedSplitVector< T >::insert().
space_at_front()
template<typename T >
size_t v8::internal::compiler::DoubleEndedSplitVector< T >::space_at_front () const [inline], [private]
Definition at line 717 of file register-allocator.h.
{ return data_begin_ - storage_begin_; }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_, and v8::internal::compiler::DoubleEndedSplitVector< T >::storage_begin_.
Referenced by v8::internal::compiler::DoubleEndedSplitVector< T >::EnsureOneMoreCapacityAt(), and v8::internal::compiler::DoubleEndedSplitVector< T >::insert().
SplitAt()
template<typename T >
DoubleEndedSplitVector<T> v8::internal::compiler::DoubleEndedSplitVector< T >::SplitAt (const_iterator split_begin_const) [inline]
Definition at line 650 of file register-allocator.h.
                                                                      {
    iterator split_begin = const_cast<iterator>(split_begin_const);
    DCHECK_LE(data_begin_, split_begin);
    DCHECK_LE(split_begin, data_end_);
    size_t old_size = size();
    // NOTE: The splitted allocation might no longer fulfill alignment
    // requirements by the Zone allocator, so do not delete it!
    DoubleEndedSplitVector split_off;
    split_off.storage_begin_ = split_begin;
    split_off.data_begin_ = split_begin;
    split_off.data_end_ = data_end_;
    split_off.storage_end_ = storage_end_;
    data_end_ = split_begin;
    storage_end_ = split_begin;
#ifdef DEBUG
    Verify();
    split_off.Verify();
#endif
    DCHECK_EQ(size() + split_off.size(), old_size);
    USE(old_size);
    return split_off;
  }
References v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_, v8::internal::compiler::DoubleEndedSplitVector< T >::data_end_, DCHECK_EQ, DCHECK_LE, v8::internal::compiler::DoubleEndedSplitVector< T >::size(), v8::internal::compiler::DoubleEndedSplitVector< T >::storage_begin_, v8::internal::compiler::DoubleEndedSplitVector< T >::storage_end_, and USE.
Referenced by v8::internal::compiler::LiveRange::SplitAt().
Member Data Documentation
data_begin_
template<typename T >
T* v8::internal::compiler::DoubleEndedSplitVector< T >::data_begin_ = nullptr [private]
Definition at line 770 of file register-allocator.h.
Referenced by v8::internal::compiler::DoubleEndedSplitVector< T >::Append(), v8::internal::compiler::DoubleEndedSplitVector< T >::begin(), v8::internal::compiler::DoubleEndedSplitVector< T >::clear(), v8::internal::compiler::DoubleEndedSplitVector< T >::data(), v8::internal::compiler::DoubleEndedSplitVector< T >::GrowAt(), v8::internal::compiler::DoubleEndedSplitVector< T >::insert(), v8::internal::compiler::DoubleEndedSplitVector< T >::operator[](), v8::internal::compiler::DoubleEndedSplitVector< T >::pop_front(), v8::internal::compiler::DoubleEndedSplitVector< T >::push_front(), v8::internal::compiler::DoubleEndedSplitVector< T >::size(), v8::internal::compiler::DoubleEndedSplitVector< T >::space_at_front(), and v8::internal::compiler::DoubleEndedSplitVector< T >::SplitAt().
data_end_
template<typename T >
T* v8::internal::compiler::DoubleEndedSplitVector< T >::data_end_ = nullptr [private]
Definition at line 771 of file register-allocator.h.
Referenced by v8::internal::compiler::DoubleEndedSplitVector< T >::Append(), v8::internal::compiler::DoubleEndedSplitVector< T >::clear(), v8::internal::compiler::DoubleEndedSplitVector< T >::end(), v8::internal::compiler::DoubleEndedSplitVector< T >::GrowAt(), v8::internal::compiler::DoubleEndedSplitVector< T >::insert(), v8::internal::compiler::DoubleEndedSplitVector< T >::size(), v8::internal::compiler::DoubleEndedSplitVector< T >::space_at_back(), and v8::internal::compiler::DoubleEndedSplitVector< T >::SplitAt().
kMinCapacity
template<typename T >
constexpr size_t v8::internal::compiler::DoubleEndedSplitVector< T >::kMinCapacity = 2 [static], [constexpr], [private]
Definition at line 715 of file register-allocator.h.
Referenced by v8::internal::compiler::DoubleEndedSplitVector< T >::GrowAt().
storage_begin_
template<typename T >
T* v8::internal::compiler::DoubleEndedSplitVector< T >::storage_begin_ = nullptr [private]
Definition at line 769 of file register-allocator.h.
Referenced by v8::internal::compiler::DoubleEndedSplitVector< T >::Append(), v8::internal::compiler::DoubleEndedSplitVector< T >::capacity(), v8::internal::compiler::DoubleEndedSplitVector< T >::GrowAt(), v8::internal::compiler::DoubleEndedSplitVector< T >::space_at_front(), and v8::internal::compiler::DoubleEndedSplitVector< T >::SplitAt().
storage_end_
template<typename T >
T* v8::internal::compiler::DoubleEndedSplitVector< T >::storage_end_ = nullptr [private]
Definition at line 772 of file register-allocator.h.
Referenced by v8::internal::compiler::DoubleEndedSplitVector< T >::Append(), v8::internal::compiler::DoubleEndedSplitVector< T >::capacity(), v8::internal::compiler::DoubleEndedSplitVector< T >::GrowAt(), v8::internal::compiler::DoubleEndedSplitVector< T >::space_at_back(), and v8::internal::compiler::DoubleEndedSplitVector< T >::SplitAt().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/register-allocator.h