v8::internal::JsonParseInternalizer Class Reference
#include <json-parser.h>
Static Public Member Functions
static MaybeHandle< Object > Internalize (Isolate *isolate, DirectHandle< Object > result, Handle< Object > reviver, Handle< String > source, MaybeHandle< Object > val_node)
Private Types
enum WithOrWithoutSource { kWithoutSource
, kWithSource
 }
Private Member Functions
JsonParseInternalizer (Isolate *isolate, Handle< JSReceiver > reviver, Handle< String > source)
template<WithOrWithoutSource with_source>
MaybeHandle< Object > InternalizeJsonProperty (DirectHandle< JSReceiver > holder, DirectHandle< String > key, Handle< Object > val_node, DirectHandle< Object > snapshot)
template<WithOrWithoutSource with_source>
bool RecurseAndApply (Handle< JSReceiver > holder, Handle< String > name, Handle< Object > val_node, Handle< Object > snapshot)
Private Attributes
Isolate * isolate_
Handle< JSReceiver > reviver_
Handle< String > source_
Detailed Description
Definition at line 107 of file json-parser.h.
Member Enumeration Documentation
WithOrWithoutSource
enum v8::internal::JsonParseInternalizer::WithOrWithoutSource [private]
Enumerator
kWithoutSource
kWithSource
Definition at line 120 of file json-parser.h.
{ kWithoutSource, kWithSource };
Constructor & Destructor Documentation
JsonParseInternalizer()
v8::internal::JsonParseInternalizer::JsonParseInternalizer (Isolate * isolate, Handle< JSReceiver > reviver, Handle< String > source) [inline], [private]
Definition at line 116 of file json-parser.h.
      : isolate_(isolate), reviver_(reviver), source_(source) {}
Member Function Documentation
Internalize()
MaybeHandle< Object > v8::internal::JsonParseInternalizer::Internalize (Isolate * isolate, DirectHandle< Object > result, Handle< Object > reviver, Handle< String > source, MaybeHandle< Object > val_node) [static]
Definition at line 134 of file json-parser.cc.
                                                         {
  DCHECK(IsCallable(*reviver));
  JsonParseInternalizer internalizer(isolate, Cast<JSReceiver>(reviver),
                                     source);
  DirectHandle<JSObject> holder =
      isolate->factory()->NewJSObject(isolate->object_function());
  DirectHandle<String> name = isolate->factory()->empty_string();
  JSObject::AddProperty(isolate, holder, name, result, NONE);
  return internalizer.InternalizeJsonProperty<kWithSource>(
      holder, name, val_node.ToHandleChecked(), result);
}
References v8::internal::JSObject::AddProperty(), v8::internal::DCHECK(), v8::internal::Isolate::factory(), InternalizeJsonProperty(), kWithSource, v8::internal::name, v8::internal::Factory::NewJSObject(), v8::internal::NONE, v8::base::internal::result, and v8::internal::MaybeHandle< T >::ToHandleChecked().
Referenced by v8::internal::JsonParser< Char >::Parse().
InternalizeJsonProperty()
template<JsonParseInternalizer::WithOrWithoutSource with_source>
MaybeHandle< Object > v8::internal::JsonParseInternalizer::InternalizeJsonProperty (DirectHandle< JSReceiver > holder, DirectHandle< String > key, Handle< Object > val_node, DirectHandle< Object > snapshot) [private]
Definition at line 149 of file json-parser.cc.
                                                            {
  DCHECK_EQ(with_source == kWithSource,
            !val_node.is_null() && !snapshot.is_null());
  DCHECK(IsCallable(*reviver_));
  HandleScope outer_scope(isolate_);
  Handle<Object> value;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate_, value, Object::GetPropertyOrElement(isolate_, holder, name));
  // When with_source == kWithSource, the source text is passed to the reviver
  // if the reviver has not mucked with the originally parsed value.
  //
  // When with_source == kWithoutSource, this is unused.
  bool pass_source_to_reviver =
      with_source == kWithSource && Object::SameValue(*value, *snapshot);
  if (IsJSReceiver(*value)) {
    Handle<JSReceiver> object = Cast<JSReceiver>(value);
    Maybe<bool> is_array = Object::IsArray(object);
    if (is_array.IsNothing()) return MaybeHandle<Object>();
    if (is_array.FromJust()) {
      DirectHandle<Object> length_object;
      ASSIGN_RETURN_ON_EXCEPTION(
          isolate_, length_object,
          Object::GetLengthFromArrayLike(isolate_, object));
      double length = Object::NumberValue(*length_object);
      if (pass_source_to_reviver) {
        auto val_nodes_and_snapshots = Cast<FixedArray>(val_node);
        int snapshot_length = val_nodes_and_snapshots->length() / 2;
        for (int i = 0; i < length; i++) {
          HandleScope inner_scope(isolate_);
          DirectHandle<Object> index = isolate_->factory()->NewNumber(i);
          Handle<String> index_name =
              isolate_->factory()->NumberToString(index);
          // Even if the array pointer snapshot matched, it's possible the
          // array had new elements added that are not in the snapshotted
          // elements.
          const bool rv =
              i < snapshot_length
                  ? RecurseAndApply<kWithSource>(
                        object, index_name,
                        handle(val_nodes_and_snapshots->get(i * 2), isolate_),
                        handle(val_nodes_and_snapshots->get(i * 2 + 1),
                               isolate_))
                  : RecurseAndApply<kWithoutSource>(
                        object, index_name, Handle<Object>(), Handle<Object>());
          if (!rv) {
            return MaybeHandle<Object>();
          }
        }
      } else {
        for (int i = 0; i < length; i++) {
          HandleScope inner_scope(isolate_);
          DirectHandle<Object> index = isolate_->factory()->NewNumber(i);
          Handle<String> index_name =
              isolate_->factory()->NumberToString(index);
          if (!RecurseAndApply<kWithoutSource>(
                  object, index_name, Handle<Object>(), Handle<Object>())) {
            return MaybeHandle<Object>();
          }
        }
      }
    } else {
      DirectHandle<FixedArray> contents;
      ASSIGN_RETURN_ON_EXCEPTION(
          isolate_, contents,
          KeyAccumulator::GetKeys(isolate_, object, KeyCollectionMode::kOwnOnly,
                                  ENUMERABLE_STRINGS,
                                  GetKeysConversion::kConvertToString));
      if (pass_source_to_reviver) {
        auto val_nodes_and_snapshots = Cast<ObjectTwoHashTable>(val_node);
        for (int i = 0; i < contents->length(); i++) {
          HandleScope inner_scope(isolate_);
          Handle<String> key_name(Cast<String>(contents->get(i)), isolate_);
          auto property_val_node_and_snapshot =
              val_nodes_and_snapshots->Lookup(isolate_, key_name);
          Handle<Object> property_val_node(property_val_node_and_snapshot[0],
                                           isolate_);
          Handle<Object> property_snapshot(property_val_node_and_snapshot[1],
                                           isolate_);
          // Even if the object pointer snapshot matched, it's possible the
          // object had new properties added that are not in the snapshotted
          // contents.
          const bool rv =
              !IsTheHole(*property_snapshot)
                  ? RecurseAndApply<kWithSource>(
                        object, key_name, property_val_node, property_snapshot)
                  : RecurseAndApply<kWithoutSource>(
                        object, key_name, Handle<Object>(), Handle<Object>());
          if (!rv) {
            return MaybeHandle<Object>();
          }
        }
      } else {
        for (int i = 0; i < contents->length(); i++) {
          HandleScope inner_scope(isolate_);
          Handle<String> key_name(Cast<String>(contents->get(i)), isolate_);
          if (!RecurseAndApply<kWithoutSource>(
                  object, key_name, Handle<Object>(), Handle<Object>())) {
            return MaybeHandle<Object>();
          }
        }
      }
    }
  }
  DirectHandle<JSObject> context =
      isolate_->factory()->NewJSObject(isolate_->object_function());
  if (pass_source_to_reviver && IsString(*val_node)) {
    JSReceiver::CreateDataProperty(isolate_, context,
                                   isolate_->factory()->source_string(),
                                   val_node, Just(kThrowOnError))
        .Check();
  }
  DirectHandle<Object> args[] = {name, value, context};
  Handle<Object> result;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate_, result,
      Execution::Call(isolate_, reviver_, holder, base::VectorOf(args)));
  return outer_scope.CloseAndEscape(result);
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Execution::Call(), v8::internal::JSReceiver::CreateDataProperty(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ENUMERABLE_STRINGS, v8::internal::Isolate::factory(), v8::Maybe< T >::FromJust(), v8::internal::KeyAccumulator::GetKeys(), v8::internal::Object::GetLengthFromArrayLike(), v8::internal::Object::GetPropertyOrElement(), v8::internal::handle(), v8::internal::index, v8::internal::HandleBase::is_null(), v8::internal::DirectHandle< T >::is_null(), v8::internal::Object::IsArray(), v8::Maybe< T >::IsNothing(), isolate_, v8::Just(), v8::internal::kConvertToString, v8::internal::kOwnOnly, v8::internal::kThrowOnError, kWithSource, v8::internal::length, v8::internal::name, v8::internal::Factory::NewJSObject(), v8::internal::FactoryBase< Impl >::NewNumber(), v8::internal::FactoryBase< Impl >::NumberToString(), v8::internal::Object::NumberValue(), v8::base::internal::result, reviver_, v8::internal::Object::SameValue(), v8::internal::value, and v8::base::VectorOf().
Referenced by Internalize().
RecurseAndApply()
template<JsonParseInternalizer::WithOrWithoutSource with_source>
bool v8::internal::JsonParseInternalizer::RecurseAndApply (Handle< JSReceiver > holder, Handle< String > name, Handle< Object > val_node, Handle< Object > snapshot) [private]
Definition at line 274 of file json-parser.cc.
                                                                     {
  STACK_CHECK(isolate_, false);
  DCHECK(IsCallable(*reviver_));
  DirectHandle<Object> result;
  ASSIGN_RETURN_ON_EXCEPTION_VALUE(
      isolate_, result,
      InternalizeJsonProperty<with_source>(holder, name, val_node, snapshot),
      false);
  Maybe<bool> change_result = Nothing<bool>();
  if (IsUndefined(*result, isolate_)) {
    change_result = JSReceiver::DeletePropertyOrElement(isolate_, holder, name,
                                                        LanguageMode::kSloppy);
  } else {
    PropertyDescriptor desc;
    desc.set_value(Cast<JSAny>(result));
    desc.set_configurable(true);
    desc.set_enumerable(true);
    desc.set_writable(true);
    change_result = JSReceiver::DefineOwnProperty(isolate_, holder, name, &desc,
                                                  Just(kDontThrow));
  }
  MAYBE_RETURN(change_result, false);
  return true;
}
References ASSIGN_RETURN_ON_EXCEPTION_VALUE, v8::internal::DCHECK(), v8::internal::JSReceiver::DefineOwnProperty(), v8::internal::JSReceiver::DeletePropertyOrElement(), isolate_, v8::Just(), v8::internal::kDontThrow, v8::internal::kSloppy, MAYBE_RETURN, v8::internal::name, v8::base::internal::result, reviver_, v8::internal::PropertyDescriptor::set_configurable(), v8::internal::PropertyDescriptor::set_enumerable(), v8::internal::PropertyDescriptor::set_value(), v8::internal::PropertyDescriptor::set_writable(), and STACK_CHECK.
Member Data Documentation
isolate_
Isolate* v8::internal::JsonParseInternalizer::isolate_ [private]
Definition at line 132 of file json-parser.h.
Referenced by InternalizeJsonProperty(), and RecurseAndApply().
reviver_
Handle<JSReceiver> v8::internal::JsonParseInternalizer::reviver_ [private]
Definition at line 133 of file json-parser.h.
Referenced by InternalizeJsonProperty(), and RecurseAndApply().
source_
Handle<String> v8::internal::JsonParseInternalizer::source_ [private]
Definition at line 134 of file json-parser.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/json/json-parser.h
/mnt/V8SourceCode/src/json/json-parser.cc