cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer Class Reference
Public Member Functions
SweepFinalizer (cppgc::Platform *platform, StatsCollector *stats_collector, BaseSpace *space, size_t *unused_destroyed_normal_pages, FreeMemoryHandling free_memory_handling, EmptyPageHandling empty_page_handling_type)
void Finalize (SpaceStates &states)
void Finalize (SweepingState &state)
bool FinalizeWithDeadlineAndSize (StatsCollector::ScopeId scope_id, SweepingState &state, v8::base::TimeTicks deadline, size_t size)
bool FinalizeWithDeadline (StatsCollector::ScopeId scope_id, SweepingState &state, v8::base::TimeTicks deadline)
Private Types
using FreeMemoryHandling = SweepingConfig::FreeMemoryHandling
Private Member Functions
void FinalizePage (SweepingState::SweptPageState *page_state)
Private Attributes
cppgc::Platform * platform_
StatsCollector * stats_collector_
BaseSpace * space_
size_t * unused_destroyed_normal_pages_
size_t largest_consecutive_block_ = 0
const FreeMemoryHandling free_memory_handling_
const EmptyPageHandling empty_page_handling_
Detailed Description
Definition at line 426 of file sweeper.cc.
Member Typedef Documentation
FreeMemoryHandling
using cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FreeMemoryHandling = SweepingConfig::FreeMemoryHandling [private]
Definition at line 427 of file sweeper.cc.
Constructor & Destructor Documentation
SweepFinalizer()
cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::SweepFinalizer (cppgc::Platform * platform, StatsCollector * stats_collector, BaseSpace * space, size_t * unused_destroyed_normal_pages, FreeMemoryHandling free_memory_handling, EmptyPageHandling empty_page_handling_type) [inline]
Definition at line 430 of file sweeper.cc.
      : platform_(platform),
        stats_collector_(stats_collector),
        space_(space),
        unused_destroyed_normal_pages_(unused_destroyed_normal_pages),
        free_memory_handling_(free_memory_handling),
        empty_page_handling_(empty_page_handling_type) {}
Member Function Documentation
Finalize() [1/2]
void cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::Finalize (SpaceStates & states) [inline]
Definition at line 442 of file sweeper.cc.
                                     {
    for (SweepingState& state : states) {
      Finalize(state);
    }
  }
Finalize() [2/2]
void cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::Finalize (SweepingState & state) [inline]
Definition at line 448 of file sweeper.cc.
                                      {
    while (auto page_state = state.swept_unfinalized_pages.Pop()) {
      FinalizePage(&*page_state);
    }
  }
References cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::FinalizePage(), and cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::swept_unfinalized_pages.
FinalizePage()
void cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizePage (SweepingState::SweptPageState * page_state) [inline], [private]
Definition at line 497 of file sweeper.cc.
                                                             {
    DCHECK(page_state);
    DCHECK(page_state->page);
    BasePage* page = page_state->page;
    // Call finalizers.
    const auto finalize_header = [](HeapObjectHeader* header) {
      const size_t size = header->AllocatedSize();
      header->Finalize();
      SetMemoryInaccessible(header, size);
    };
#if defined(CPPGC_CAGED_HEAP)
#if defined(CPPGC_POINTER_COMPRESSION)
    const uint64_t cage_base = CageBaseGlobal::Get();
#else
    const uint64_t cage_base = CagedHeapBase::GetBase();
#endif
    HeapObjectHeader* next_unfinalized = nullptr;
    for (auto* unfinalized_header = page_state->unfinalized_objects_head;
         unfinalized_header; unfinalized_header = next_unfinalized) {
      next_unfinalized = unfinalized_header->GetNextUnfinalized(cage_base);
      finalize_header(unfinalized_header);
    }
#else // !defined(CPPGC_CAGED_HEAP)
    for (HeapObjectHeader* unfinalized_header :
         page_state->unfinalized_objects) {
      finalize_header(unfinalized_header);
    }
#endif // !defined(CPPGC_CAGED_HEAP)
    // Unmap page if empty.
    if (page_state->is_empty) {
      DCHECK_IMPLIES(page->is_large(),
                     empty_page_handling_ == EmptyPageHandling::kDestroy);
      if (empty_page_handling_ == EmptyPageHandling::kDestroy) {
        if (!page->is_large()) {
          (*unused_destroyed_normal_pages_)++;
        } else {
          // Normal pages are added to the page pool when destroyed and thus
          // cannot be used for a large page allocation.
          largest_consecutive_block_ = std::max(
              LargePage::From(page)->PayloadSize(), largest_consecutive_block_);
        }
        BasePage::Destroy(page);
        return;
      }
      // Otherwise, we currently sweep on allocation. Reinitialize the empty
      // page and return it right away.
      auto* normal_page = NormalPage::From(page);
      // If a space has been assigned to the finalizer, then repurpose empty
      // pages for that space. Otherwise just retain the current space for an
      // empty page.
      if (space_) {
        normal_page->ChangeOwner(*space_);
      }
      page_state->cached_free_list.Clear();
      page_state->cached_free_list.Add(
          {normal_page->PayloadStart(), normal_page->PayloadSize()});
      page_state->unfinalized_free_list.clear();
      page_state->largest_new_free_list_entry = normal_page->PayloadSize();
    }
    // We either swept a non-empty page for which the space should already match
    // or we swept an empty page for which the owner was changed.
    DCHECK_IMPLIES(space_, space_ == &page->space());
    DCHECK(!page->is_large());
    // Merge freelists without finalizers.
    FreeList& space_freelist = NormalPageSpace::From(page->space()).free_list();
    space_freelist.Append(std::move(page_state->cached_free_list));
    // Merge freelist with finalizers.
    if (!page_state->unfinalized_free_list.empty()) {
      std::unique_ptr<FreeHandlerBase> handler =
          free_memory_handling_ == FreeMemoryHandling::kDiscardWherePossible
              ? std::unique_ptr<FreeHandlerBase>(new DiscardingFreeHandler(
                    *platform_->GetPageAllocator(), space_freelist, *page))
              : std::unique_ptr<FreeHandlerBase>(new RegularFreeHandler(
                    *platform_->GetPageAllocator(), space_freelist, *page));
      handler->FreeFreeList(page_state->unfinalized_free_list);
    }
    largest_consecutive_block_ = std::max(
        page_state->largest_new_free_list_entry, largest_consecutive_block_);
    // After the page was fully finalized and freelists have been merged, verify
    // that the bitmap is consistent.
    ObjectStartBitmapVerifier().Verify(static_cast<NormalPage&>(*page));
    // Add the page to the space.
    page->space().AddPage(page);
  }
References cppgc::internal::FreeList::Add(), cppgc::internal::BaseSpace::AddPage(), cppgc::internal::FreeList::Append(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::SweptPageState::cached_free_list, cppgc::internal::FreeList::Clear(), DCHECK, DCHECK_IMPLIES, cppgc::internal::BasePage::Destroy(), cppgc::internal::NormalPageSpace::free_list(), cppgc::internal::NormalPage::From(), cppgc::internal::LargePage::From(), cppgc::internal::NormalPageSpace::From(), v8::internal::compiler::turboshaft::Get(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::SweptPageState::is_empty, cppgc::internal::BasePage::is_large(), cppgc::internal::kDiscardWherePossible, cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::SweptPageState::largest_new_free_list_entry, cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::SweptPageState::page, cppgc::internal::SetMemoryInaccessible(), size(), cppgc::internal::BasePage::space(), cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::SweptPageState::unfinalized_free_list, cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::SweptPageState::unfinalized_objects, and cppgc::internal::anonymous_namespace{sweeper.cc}::ObjectStartBitmapVerifier::Verify().
FinalizeWithDeadline()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizeWithDeadline (StatsCollector::ScopeId scope_id, SweepingState & state, v8::base::TimeTicks deadline) [inline]
Definition at line 479 of file sweeper.cc.
                                                      {
    if (state.swept_unfinalized_pages.IsEmpty()) {
      return true;
    }
    StatsCollector::DisabledScope finalize_scope(stats_collector_, scope_id);
    DeadlineChecker deadline_check(deadline);
    while (auto page_state = state.swept_unfinalized_pages.Pop()) {
      FinalizePage(&*page_state);
      if (deadline_check.Check()) {
        return false;
      }
    }
    return true;
  }
References cppgc::internal::anonymous_namespace{sweeper.cc}::DeadlineChecker::Check(), cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::FinalizePage(), and cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::swept_unfinalized_pages.
Referenced by cppgc::internal::anonymous_namespace{sweeper.cc}::MutatorThreadSweeper::FinalizeAndSweepWithDeadline().
FinalizeWithDeadlineAndSize()
bool cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::FinalizeWithDeadlineAndSize (StatsCollector::ScopeId scope_id, SweepingState & state, v8::base::TimeTicks deadline, size_t size) [inline]
Definition at line 457 of file sweeper.cc.
                                                                          {
    if (state.swept_unfinalized_pages.IsEmpty()) {
      return false;
    }
    StatsCollector::DisabledScope finalize_scope(stats_collector_, scope_id);
    DeadlineChecker deadline_check(deadline);
    while (auto page_state = state.swept_unfinalized_pages.Pop()) {
      FinalizePage(&*page_state);
      if (size <= largest_consecutive_block_) {
        return true;
      }
      if (deadline_check.Check()) {
        break;
      }
    }
    return false;
  }
References cppgc::internal::anonymous_namespace{sweeper.cc}::DeadlineChecker::Check(), cppgc::internal::anonymous_namespace{heap-statistics-collector.cc}::FinalizePage(), size(), and cppgc::internal::anonymous_namespace{sweeper.cc}::SweepingState::swept_unfinalized_pages.
Member Data Documentation
empty_page_handling_
const EmptyPageHandling cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::empty_page_handling_ [private]
Definition at line 602 of file sweeper.cc.
free_memory_handling_
const FreeMemoryHandling cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::free_memory_handling_ [private]
Definition at line 601 of file sweeper.cc.
largest_consecutive_block_
size_t cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::largest_consecutive_block_ = 0 [private]
Definition at line 600 of file sweeper.cc.
platform_
cppgc::Platform* cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::platform_ [private]
Definition at line 594 of file sweeper.cc.
space_
BaseSpace* cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::space_ [private]
Definition at line 596 of file sweeper.cc.
stats_collector_
StatsCollector* cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::stats_collector_ [private]
Definition at line 595 of file sweeper.cc.
unused_destroyed_normal_pages_
size_t* cppgc::internal::anonymous_namespace{sweeper.cc}::SweepFinalizer::unused_destroyed_normal_pages_ [private]
Definition at line 597 of file sweeper.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/heap/cppgc/sweeper.cc