v8::internal::MacroAssemblerBase Class Reference
#include <macro-assembler-base.h>
Public Types
enum class RecordWriteCallMode { kDefault
, kWasm
 }
Public Member Functions
MacroAssemblerBase (Isolate *isolate, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer={})
MacroAssemblerBase (Isolate *isolate, MaybeAssemblerZone zone, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer={})
MacroAssemblerBase (Isolate *isolate, const AssemblerOptions &options, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer={})
MacroAssemblerBase (Isolate *isolate, MaybeAssemblerZone zone, AssemblerOptions options, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer={})
MacroAssemblerBase (MaybeAssemblerZone zone, AssemblerOptions options, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer={})
Isolate * isolate () const
IndirectHandle< HeapObject > CodeObject () const
bool root_array_available () const
void set_root_array_available (bool v)
bool should_abort_hard () const
void set_abort_hard (bool v)
void set_builtin (Builtin builtin)
Builtin builtin () const
CodeSandboxingMode sandboxing_mode () const
void SetSandboxingModeForCurrentBuiltin (CodeSandboxingMode mode)
void set_has_frame (bool v)
bool has_frame () const
void IndirectLoadConstant (Register destination, Handle< HeapObject > object)
void IndirectLoadExternalReference (Register destination, ExternalReference reference)
Address BuiltinEntry (Builtin builtin)
virtual void LoadFromConstantsTable (Register destination, int constant_index)=0
virtual void LoadRootRegisterOffset (Register destination, intptr_t offset)=0
virtual void LoadRootRelative (Register destination, int32_t offset)=0
virtual void StoreRootRelative (int32_t offset, Register value)=0
Tagged_t ReadOnlyRootPtr (RootIndex index)
virtual void LoadRoot (Register destination, RootIndex index)=0
std::string CommentForOffHeapTrampoline (const char *prefix, Builtin builtin)
Static Public Member Functions
static constexpr bool CanBeImmediate (RootIndex index)
static Tagged_t ReadOnlyRootPtr (RootIndex index, Isolate *isolate)
static int32_t RootRegisterOffsetForRootIndex (RootIndex root_index)
static int32_t RootRegisterOffsetForBuiltin (Builtin builtin)
static intptr_t RootRegisterOffsetForExternalReference (Isolate *isolate, const ExternalReference &reference)
static int32_t RootRegisterOffsetForExternalReferenceTableEntry (Isolate *isolate, const ExternalReference &reference)
static bool IsAddressableThroughRootRegister (Isolate *isolate, const ExternalReference &reference)
Protected Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (MacroAssemblerBase)
Protected Attributes
Isolate *const isolate_ = nullptr
IndirectHandle< HeapObject > code_object_
bool root_array_available_ = true
bool hard_abort_ = false
bool has_frame_ = false
CodeSandboxingMode sandboxing_mode_ = CodeSandboxingMode::kSandboxed
Builtin maybe_builtin_ = Builtin::kNoBuiltinId
int comment_depth_ = 0
Additional Inherited Members
Detailed Description
Definition at line 22 of file macro-assembler-base.h.
Member Enumeration Documentation
RecordWriteCallMode
enum v8::internal::MacroAssemblerBase::RecordWriteCallMode [strong]
Enumerator
kDefault
kWasm
Definition at line 148 of file macro-assembler-base.h.
{ kDefault, kWasm };
Constructor & Destructor Documentation
MacroAssemblerBase() [1/5]
v8::internal::MacroAssemblerBase::MacroAssemblerBase (Isolate * isolate, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer = {}) [inline]
Definition at line 26 of file macro-assembler-base.h.
                                                             {})
      : MacroAssemblerBase(isolate, AssemblerOptions::Default(isolate),
                           create_code_object, std::move(buffer)) {}
MacroAssemblerBase() [2/5]
v8::internal::MacroAssemblerBase::MacroAssemblerBase (Isolate * isolate, MaybeAssemblerZone zone, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer = {}) [inline]
Definition at line 30 of file macro-assembler-base.h.
                                                             {})
      : MacroAssemblerBase(isolate, zone, AssemblerOptions::Default(isolate),
                           create_code_object, std::move(buffer)) {}
MacroAssemblerBase() [3/5]
v8::internal::MacroAssemblerBase::MacroAssemblerBase (Isolate * isolate, const AssemblerOptions & options, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer = {})
Definition at line 18 of file macro-assembler-base.cc.
    : MacroAssemblerBase(isolate, isolate->allocator(), options,
                         create_code_object, std::move(buffer)) {}
MacroAssemblerBase() [4/5]
v8::internal::MacroAssemblerBase::MacroAssemblerBase (Isolate * isolate, MaybeAssemblerZone zone, AssemblerOptions options, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer = {})
Definition at line 25 of file macro-assembler-base.cc.
    : Assembler(zone, options, std::move(buffer)), isolate_(isolate) {
  if (create_code_object == CodeObjectRequired::kYes) {
    code_object_ = IndirectHandle<HeapObject>::New(
        ReadOnlyRoots(isolate).self_reference_marker(), isolate);
  }
}
References code_object_, isolate(), v8::internal::kYes, and v8::internal::Handle< T >::New().
MacroAssemblerBase() [5/5]
v8::internal::MacroAssemblerBase::MacroAssemblerBase (MaybeAssemblerZone zone, AssemblerOptions options, CodeObjectRequired create_code_object, std::unique_ptr< AssemblerBuffer > buffer = {}) [inline]
Definition at line 44 of file macro-assembler-base.h.
                                                             {})
      : MacroAssemblerBase(nullptr, zone, options, create_code_object,
                           std::move(buffer)) {}
Member Function Documentation
builtin()
Builtin v8::internal::MacroAssemblerBase::builtin () const [inline]
Definition at line 72 of file macro-assembler-base.h.
{ return maybe_builtin_; }
Referenced by BuiltinEntry(), v8::internal::MacroAssembler::CallBuiltin(), v8::internal::maglev::MaglevAssembler::CallBuiltin(), v8::internal::wasm::LiftoffAssembler::CallBuiltin(), v8::internal::MacroAssembler::EntryFromBuiltinAsOperand(), IndirectLoadConstant(), v8::internal::MacroAssembler::JumpToExternalReference(), v8::internal::MacroAssembler::LoadEntryFromBuiltin(), v8::internal::MacroAssembler::MacroAssemblerBase(), RootRegisterOffsetForBuiltin(), and v8::internal::MacroAssembler::TailCallBuiltin().
BuiltinEntry()
Address v8::internal::MacroAssemblerBase::BuiltinEntry (Builtin builtin)
Definition at line 37 of file macro-assembler-base.cc.
                                                        {
  DCHECK(Builtins::IsBuiltinId(builtin));
  if (isolate_ != nullptr) {
    Address entry = isolate_->builtin_entry_table()[Builtins::ToInt(builtin)];
    DCHECK_EQ(entry,
              EmbeddedData::FromBlob(isolate_).InstructionStartOf(builtin));
    return entry;
  }
  EmbeddedData d = EmbeddedData::FromBlob();
  return d.InstructionStartOf(builtin);
}
References builtin(), v8::internal::DCHECK(), and v8::internal::Builtins::IsBuiltinId().
Referenced by v8::internal::MacroAssembler::CallBuiltin(), and v8::internal::MacroAssembler::TailCallBuiltin().
CanBeImmediate()
static constexpr bool v8::internal::MacroAssemblerBase::CanBeImmediate (RootIndex index) [inline], [static], [constexpr]
Definition at line 109 of file macro-assembler-base.h.
                                                        {
    return V8_STATIC_ROOTS_BOOL && RootsTable::IsReadOnly(index);
  }
References v8::internal::index, v8::internal::RootsTable::IsReadOnly(), and V8_STATIC_ROOTS_BOOL.
Referenced by ReadOnlyRootPtr().
CodeObject()
IndirectHandle<HeapObject> v8::internal::MacroAssemblerBase::CodeObject () const [inline]
Definition at line 52 of file macro-assembler-base.h.
                                                {
    DCHECK(!code_object_.is_null());
    return code_object_;
  }
References v8::internal::DCHECK().
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildAdaptor(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildPlaceholder(), and v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler().
CommentForOffHeapTrampoline()
std::string v8::internal::MacroAssemblerBase::CommentForOffHeapTrampoline (const char * prefix, Builtin builtin) [inline]
Definition at line 139 of file macro-assembler-base.h.
                                                                     {
    if (!v8_flags.code_comments) return "";
    std::ostringstream str;
    str << "Inlined Trampoline for " << prefix << " to "
        << Builtins::name(builtin);
    return str.str();
  }
References v8::internal::Builtins::name(), and v8::internal::v8_flags.
Referenced by v8::internal::MacroAssembler::CallBuiltin(), and v8::internal::MacroAssembler::TailCallBuiltin().
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::MacroAssemblerBase::DISALLOW_IMPLICIT_CONSTRUCTORS (MacroAssemblerBase) [protected]
has_frame()
bool v8::internal::MacroAssemblerBase::has_frame () const [inline]
Definition at line 88 of file macro-assembler-base.h.
{ return has_frame_; }
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildAdaptor(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildPlaceholder(), v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler(), v8::internal::MacroAssembler::CallCFunctionHelper(), v8::internal::MacroAssembler::CallDebugOnFunctionCall(), v8::internal::MacroAssembler::InvokeFunction(), v8::internal::MacroAssembler::InvokeFunctionCode(), v8::internal::MacroAssembler::InvokeFunctionWithNewTarget(), and v8::internal::MacroAssembler::InvokePrologue().
IndirectLoadConstant()
void v8::internal::MacroAssemblerBase::IndirectLoadConstant (Register destination, Handle< HeapObject > object)
Definition at line 49 of file macro-assembler-base.cc.
                                                                         {
  CHECK(root_array_available_);
  // Before falling back to the (fairly slow) lookup from the constants table,
  // check if any of the fast paths can be applied.
  Builtin builtin;
  RootIndex root_index;
  if (isolate()->roots_table().IsRootHandle(object, &root_index)) {
    // Roots are loaded relative to the root register.
    LoadRoot(destination, root_index);
  } else if (isolate()->builtins()->IsBuiltinHandle(object, &builtin)) {
    // Similar to roots, builtins may be loaded from the builtins table.
    LoadRootRelative(destination, RootRegisterOffsetForBuiltin(builtin));
  } else if (object.is_identical_to(code_object_) &&
             Builtins::IsBuiltinId(maybe_builtin_)) {
    // The self-reference loaded through Codevalue() may also be a builtin
    // and thus viable for a fast load.
    LoadRootRelative(destination, RootRegisterOffsetForBuiltin(maybe_builtin_));
  } else {
    CHECK(isolate()->IsGeneratingEmbeddedBuiltins());
    // Ensure the given object is in the builtins constants table and fetch its
    // index.
    BuiltinsConstantsTableBuilder* builder =
        isolate()->builtins_constants_table_builder();
    uint32_t index = builder->AddObject(object);
    // Slow load from the constants table.
    LoadFromConstantsTable(destination, index);
  }
}
References v8::internal::BuiltinsConstantsTableBuilder::AddObject(), builtin(), v8::internal::Isolate::builtins_constants_table_builder(), CHECK, code_object_, v8::internal::index, v8::internal::Builtins::IsBuiltinId(), isolate(), LoadFromConstantsTable(), LoadRoot(), LoadRootRelative(), maybe_builtin_, root_array_available_, and RootRegisterOffsetForBuiltin().
Referenced by v8::internal::MacroAssembler::li().
IndirectLoadExternalReference()
void v8::internal::MacroAssemblerBase::IndirectLoadExternalReference (Register destination, ExternalReference reference)
Definition at line 82 of file macro-assembler-base.cc.
                                                       {
  CHECK(root_array_available_);
  if (IsAddressableThroughRootRegister(isolate(), reference)) {
    // Some external references can be efficiently loaded as an offset from
    // kRootRegister.
    intptr_t offset =
        RootRegisterOffsetForExternalReference(isolate(), reference);
    LoadRootRegisterOffset(destination, offset);
  } else {
    // Otherwise, do a memory load from the external reference table.
    LoadRootRelative(
        destination,
        RootRegisterOffsetForExternalReferenceTableEntry(isolate(), reference));
  }
}
References CHECK, IsAddressableThroughRootRegister(), isolate(), LoadRootRegisterOffset(), LoadRootRelative(), root_array_available_, RootRegisterOffsetForExternalReference(), and RootRegisterOffsetForExternalReferenceTableEntry().
Referenced by v8::internal::MacroAssembler::li().
IsAddressableThroughRootRegister()
bool v8::internal::MacroAssemblerBase::IsAddressableThroughRootRegister (Isolate * isolate, const ExternalReference & reference) [static]
Definition at line 134 of file macro-assembler-base.cc.
                                                          {
  if (reference.IsIsolateFieldId()) return true;
  Address address = reference.address();
  return isolate->root_register_addressable_region().contains(address);
}
References v8::internal::ExternalReference::address(), v8::base::AddressRegion::contains(), v8::internal::ExternalReference::IsIsolateFieldId(), isolate(), and v8::internal::Isolate::root_register_addressable_region().
Referenced by v8::internal::compiler::InstructionSelector::CanAddressRelativeToRootsRegister(), v8::internal::MacroAssembler::ExternalReferenceAsOperand(), and IndirectLoadExternalReference().
isolate()
Isolate* v8::internal::MacroAssemblerBase::isolate () const [inline]
Definition at line 50 of file macro-assembler-base.h.
{ return isolate_; }
Referenced by v8::internal::CallApiFunctionAndReturn(), v8::internal::MacroAssembler::CallBuiltin(), v8::internal::MacroAssembler::ClearedValue(), v8::internal::MacroAssembler::EnterExitFrame(), v8::internal::MacroAssembler::ExternalReferenceAsOperand(), v8::internal::Builtins::Generate_CEntry(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_DeoptimizationEntry(), v8::internal::Generate_InterpreterEnterBytecode(), v8::internal::Generate_JSEntryTrampolineHelper(), v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_JSEntryVariant(), v8::internal::anonymous_namespace{builtins-riscv.cc}::GenerateExceptionHandlingLandingPad(), IndirectLoadConstant(), IndirectLoadExternalReference(), v8::internal::MacroAssembler::InitializeRootRegister(), v8::internal::MacroAssembler::InvokeFunctionCode(), IsAddressableThroughRootRegister(), v8::internal::MacroAssembler::LeaveExitFrame(), MacroAssemblerBase(), v8::internal::MacroAssembler::PopStackHandler(), v8::internal::MacroAssembler::PushStackHandler(), ReadOnlyRootPtr(), RootRegisterOffsetForExternalReference(), RootRegisterOffsetForExternalReferenceTableEntry(), v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchFromTheCentralStackIfNeeded(), v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchStacks(), v8::internal::anonymous_namespace{builtins-riscv.cc}::SwitchToTheCentralStackIfNeeded(), and v8::internal::MacroAssembler::TailCallBuiltin().
LoadFromConstantsTable()
virtual void v8::internal::MacroAssemblerBase::LoadFromConstantsTable (Register destination, int constant_index) [pure virtual]
Implemented in v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, and v8::internal::MacroAssembler.
Referenced by IndirectLoadConstant().
LoadRoot()
virtual void v8::internal::MacroAssemblerBase::LoadRoot (Register destination, RootIndex index) [pure virtual]
Implemented in v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, and v8::internal::MacroAssembler.
Referenced by IndirectLoadConstant().
LoadRootRegisterOffset()
virtual void v8::internal::MacroAssemblerBase::LoadRootRegisterOffset (Register destination, intptr_t offset) [pure virtual]
Implemented in v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, and v8::internal::MacroAssembler.
Referenced by IndirectLoadExternalReference().
LoadRootRelative()
virtual void v8::internal::MacroAssemblerBase::LoadRootRelative (Register destination, int32_t offset) [pure virtual]
Implemented in v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, and v8::internal::MacroAssembler.
Referenced by IndirectLoadConstant(), and IndirectLoadExternalReference().
ReadOnlyRootPtr() [1/2]
Tagged_t v8::internal::MacroAssemblerBase::ReadOnlyRootPtr (RootIndex index)
Definition at line 151 of file macro-assembler-base.cc.
                                                            {
  return ReadOnlyRootPtr(index, isolate_);
}
References v8::internal::index, and isolate_.
Referenced by v8::internal::MacroAssembler::Branch(), v8::internal::compiler::Arm64OperandGenerator::CanBeImmediate(), v8::internal::compiler::PPCOperandGenerator::CanBeImmediate(), v8::internal::compiler::Loong64OperandGenerator::CanBeImmediate(), v8::internal::compiler::RiscvOperandGenerator::CanBeImmediate(), v8::internal::MacroAssembler::CompareTaggedRootAndBranch(), v8::internal::compiler::Loong64OperandConverter::InputImmediate(), v8::internal::compiler::PPCOperandConverter::InputImmediate(), v8::internal::compiler::RiscvOperandConverter::InputImmediate(), v8::internal::MacroAssembler::JumpIfObjectType(), v8::internal::compiler::Arm64OperandConverter::ToImmediate(), v8::internal::compiler::X64OperandConverter::ToImmediate(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32EqualImpl().
ReadOnlyRootPtr() [2/2]
Tagged_t v8::internal::MacroAssemblerBase::ReadOnlyRootPtr (RootIndex index, Isolate * isolate) [static]
Definition at line 143 of file macro-assembler-base.cc.
                                                               {
  DCHECK(CanBeImmediate(index));
  Tagged<Object> obj = isolate->root(index);
  CHECK(IsHeapObject(obj));
  return V8HeapCompressionScheme::CompressObject(obj.ptr());
}
References CanBeImmediate(), CHECK, v8::internal::V8HeapCompressionSchemeImpl< Cage >::CompressObject(), v8::internal::DCHECK(), v8::internal::index, v8::internal::IsHeapObject(), isolate(), v8::internal::TaggedImpl< kRefType, StorageType >::ptr(), and v8::internal::Isolate::root().
root_array_available()
bool v8::internal::MacroAssemblerBase::root_array_available () const [inline]
Definition at line 57 of file macro-assembler-base.h.
{ return root_array_available_; }
Referenced by v8::internal::MacroAssembler::Abort(), v8::internal::MacroAssembler::CallCFunctionHelper(), v8::internal::MacroAssembler::EntryFromBuiltinAsOperand(), v8::internal::MacroAssembler::ExternalReferenceAsOperand(), v8::internal::MacroAssembler::li(), v8::internal::MacroAssembler::LoadProtectedPointerField(), and v8::internal::MacroAssembler::LoadStackLimit().
RootRegisterOffsetForBuiltin()
int32_t v8::internal::MacroAssemblerBase::RootRegisterOffsetForBuiltin (Builtin builtin) [static]
Definition at line 107 of file macro-assembler-base.cc.
                                                                        {
  return IsolateData::BuiltinSlotOffset(builtin);
}
References builtin(), and v8::internal::IsolateData::BuiltinSlotOffset().
Referenced by IndirectLoadConstant().
RootRegisterOffsetForExternalReference()
intptr_t v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReference (Isolate * isolate, const ExternalReference & reference) [static]
Definition at line 112 of file macro-assembler-base.cc.
                                                          {
  if (reference.IsIsolateFieldId()) {
    return reference.offset_from_root_register();
  }
  return static_cast<intptr_t>(reference.address() - isolate->isolate_root());
}
References v8::internal::ExternalReference::address(), v8::internal::ExternalReference::IsIsolateFieldId(), isolate(), v8::internal::Isolate::isolate_root(), and v8::internal::ExternalReference::offset_from_root_register().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), v8::internal::MacroAssembler::ExternalReferenceAsOperand(), v8::internal::compiler::IA32OperandGenerator::GetEffectiveAddressMemoryOperand(), v8::internal::compiler::X64OperandGenerator::GetEffectiveAddressMemoryOperand(), IndirectLoadExternalReference(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon().
RootRegisterOffsetForExternalReferenceTableEntry()
int32_t v8::internal::MacroAssemblerBase::RootRegisterOffsetForExternalReferenceTableEntry (Isolate * isolate, const ExternalReference & reference) [static]
Definition at line 121 of file macro-assembler-base.cc.
                                                          {
  // Encode as an index into the external reference table stored on the
  // isolate.
  ExternalReferenceEncoder encoder(isolate);
  ExternalReferenceEncoder::Value v = encoder.Encode(reference.address());
  CHECK(!v.is_from_api());
  return IsolateData::external_reference_table_offset() +
         ExternalReferenceTable::OffsetOfEntry(v.index());
}
References v8::internal::ExternalReference::address(), CHECK, v8::internal::ExternalReferenceEncoder::Encode(), v8::internal::ExternalReferenceEncoder::Value::index(), v8::internal::ExternalReferenceEncoder::Value::is_from_api(), isolate(), and v8::internal::ExternalReferenceTable::OffsetOfEntry().
Referenced by v8::internal::MacroAssembler::ExternalReferenceAsOperand(), and IndirectLoadExternalReference().
RootRegisterOffsetForRootIndex()
int32_t v8::internal::MacroAssemblerBase::RootRegisterOffsetForRootIndex (RootIndex root_index) [static]
Definition at line 101 of file macro-assembler-base.cc.
                          {
  return IsolateData::root_slot_offset(root_index);
}
References v8::internal::IsolateData::root_slot_offset().
Referenced by v8::internal::anonymous_namespace{builtins-riscv.cc}::Generate_WasmResumeHelper(), v8::internal::MacroAssembler::LoadCompressedTaggedRoot(), v8::internal::maglev::MaglevAssembler::LoadSingleCharacterString(), v8::internal::anonymous_namespace{builtins-riscv.cc}::RestoreParentSuspender(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32EqualImpl(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64EqualImpl().
sandboxing_mode()
CodeSandboxingMode v8::internal::MacroAssemblerBase::sandboxing_mode () const [inline]
Definition at line 75 of file macro-assembler-base.h.
{ return sandboxing_mode_; }
set_abort_hard()
void v8::internal::MacroAssemblerBase::set_abort_hard (bool v) [inline]
Definition at line 61 of file macro-assembler-base.h.
{ hard_abort_ = v; }
Referenced by v8::internal::wasm::LiftoffAssembler::LiftoffAssembler().
set_builtin()
void v8::internal::MacroAssemblerBase::set_builtin (Builtin builtin) [inline]
Definition at line 65 of file macro-assembler-base.h.
                                    {
    DCHECK_EQ(pc_offset(), 0);
    maybe_builtin_ = builtin;
    if (builtin != Builtin::kNoBuiltinId) {
      sandboxing_mode_ = Builtins::SandboxingModeOf(builtin);
    }
  }
References DCHECK_EQ, v8::internal::kNoBuiltinId, and v8::internal::Builtins::SandboxingModeOf().
Referenced by v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildAdaptor(), and v8::internal::anonymous_namespace{setup-builtins-internal.cc}::BuildWithMacroAssembler().
set_has_frame()
void v8::internal::MacroAssemblerBase::set_has_frame (bool v) [inline]
Definition at line 87 of file macro-assembler-base.h.
{ has_frame_ = v; }
Referenced by v8::internal::FrameAndConstantPoolScope::FrameAndConstantPoolScope(), and v8::internal::FrameScope::FrameScope().
set_root_array_available()
void v8::internal::MacroAssemblerBase::set_root_array_available (bool v) [inline]
Definition at line 58 of file macro-assembler-base.h.
{ root_array_available_ = v; }
Referenced by v8::internal::NoRootArrayScope::NoRootArrayScope().
SetSandboxingModeForCurrentBuiltin()
void v8::internal::MacroAssemblerBase::SetSandboxingModeForCurrentBuiltin (CodeSandboxingMode mode) [inline]
Definition at line 82 of file macro-assembler-base.h.
                                                                   {
    DCHECK_NE(maybe_builtin_, Builtin::kNoBuiltinId);
    sandboxing_mode_ = mode;
  }
References DCHECK_NE, v8::internal::kNoBuiltinId, and mode().
should_abort_hard()
bool v8::internal::MacroAssemblerBase::should_abort_hard () const [inline]
Definition at line 60 of file macro-assembler-base.h.
{ return hard_abort_; }
Referenced by v8::internal::MacroAssembler::Abort().
StoreRootRelative()
virtual void v8::internal::MacroAssemblerBase::StoreRootRelative (int32_t offset, Register value) [pure virtual]
Implemented in v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, v8::internal::MacroAssembler, and v8::internal::MacroAssembler.
Member Data Documentation
code_object_
IndirectHandle<HeapObject> v8::internal::MacroAssemblerBase::code_object_ [protected]
Definition at line 154 of file macro-assembler-base.h.
Referenced by IndirectLoadConstant(), and MacroAssemblerBase().
comment_depth_
int v8::internal::MacroAssemblerBase::comment_depth_ = 0 [protected]
Definition at line 174 of file macro-assembler-base.h.
hard_abort_
bool v8::internal::MacroAssemblerBase::hard_abort_ = false [protected]
Definition at line 160 of file macro-assembler-base.h.
has_frame_
bool v8::internal::MacroAssemblerBase::has_frame_ = false [protected]
Definition at line 162 of file macro-assembler-base.h.
isolate_
Isolate* const v8::internal::MacroAssemblerBase::isolate_ = nullptr [protected]
Definition at line 151 of file macro-assembler-base.h.
Referenced by v8::internal::maglev::MaglevAssembler::Allocate(), v8::internal::MacroAssembler::MacroAssemblerBase(), ReadOnlyRootPtr(), and v8::internal::maglev::MaglevAssembler::ToBoolean().
maybe_builtin_
Builtin v8::internal::MacroAssemblerBase::maybe_builtin_ = Builtin::kNoBuiltinId [protected]
Definition at line 172 of file macro-assembler-base.h.
Referenced by IndirectLoadConstant().
root_array_available_
bool v8::internal::MacroAssemblerBase::root_array_available_ = true [protected]
Definition at line 157 of file macro-assembler-base.h.
Referenced by v8::internal::MacroAssembler::ExternalReferenceAsOperand(), IndirectLoadConstant(), IndirectLoadExternalReference(), v8::internal::MacroAssembler::li(), and v8::internal::MacroAssembler::LoadExternalPointerField().
sandboxing_mode_
CodeSandboxingMode v8::internal::MacroAssemblerBase::sandboxing_mode_ = CodeSandboxingMode::kSandboxed [protected]
Definition at line 169 of file macro-assembler-base.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/macro-assembler-base.h
/mnt/V8SourceCode/src/codegen/macro-assembler-base.cc