v8::internal::compiler::EscapeAnalysisTracker Class Reference
Classes
class Scope
Public Member Functions
EscapeAnalysisTracker (JSGraph *jsgraph, EffectGraphReducer *reducer, Zone *zone)
EscapeAnalysisTracker (const EscapeAnalysisTracker &)=delete
EscapeAnalysisTracker & operator= (const EscapeAnalysisTracker &)=delete
Node * GetReplacementOf (Node *node)
Node * ResolveReplacement (Node *node)
Private Member Functions
VirtualObject * NewVirtualObject (int size)
Private Attributes
SparseSidetable< VirtualObject * > virtual_objects_
Sidetable< Node * > replacements_
ZoneUnorderedMap< Node *, bool > framestate_might_lazy_deopt_
VariableTracker variable_states_
VirtualObject::Id next_object_id_ = 0
int number_of_tracked_bytes_ = 0
JSGraph *const jsgraph_
Zone *const zone_
Static Private Attributes
static constexpr int kTrackingBudget = 1300
Friends
class EscapeAnalysisResult
Detailed Description
Definition at line 167 of file escape-analysis.cc.
Constructor & Destructor Documentation
EscapeAnalysisTracker() [1/2]
v8::internal::compiler::EscapeAnalysisTracker::EscapeAnalysisTracker (JSGraph * jsgraph, EffectGraphReducer * reducer, Zone * zone) [inline]
Definition at line 169 of file escape-analysis.cc.
      : virtual_objects_(zone),
        replacements_(zone),
        framestate_might_lazy_deopt_(zone),
        variable_states_(jsgraph, reducer, zone),
        jsgraph_(jsgraph),
        zone_(zone) {}
EscapeAnalysisTracker() [2/2]
v8::internal::compiler::EscapeAnalysisTracker::EscapeAnalysisTracker (const EscapeAnalysisTracker &) [delete]
Member Function Documentation
GetReplacementOf()
Node* v8::internal::compiler::EscapeAnalysisTracker::GetReplacementOf (Node * node) [inline]
Definition at line 291 of file escape-analysis.cc.
{ return replacements_[node]; }
References replacements_.
Referenced by ResolveReplacement().
NewVirtualObject()
VirtualObject* v8::internal::compiler::EscapeAnalysisTracker::NewVirtualObject (int size) [inline], [private]
Definition at line 303 of file escape-analysis.cc.
                                            {
    if (number_of_tracked_bytes_ + size >= kTrackingBudget) {
      if (V8_UNLIKELY(v8_flags.trace_turbo_bailouts)) {
        std::cout
            << "Bailing out in Escape Analysis because of kTrackingBudget\n";
      }
      return nullptr;
    }
    number_of_tracked_bytes_ += size;
    return zone_->New<VirtualObject>(&variable_states_, next_object_id_++,
                                     size);
  }
References kTrackingBudget, v8::internal::Zone::New(), next_object_id_, number_of_tracked_bytes_, size(), v8::internal::v8_flags, V8_UNLIKELY, variable_states_, and zone_.
operator=()
EscapeAnalysisTracker& v8::internal::compiler::EscapeAnalysisTracker::operator= (const EscapeAnalysisTracker &) [delete]
ResolveReplacement()
Node* v8::internal::compiler::EscapeAnalysisTracker::ResolveReplacement (Node * node) [inline]
Definition at line 292 of file escape-analysis.cc.
                                       {
    if (Node* replacement = GetReplacementOf(node)) {
      return replacement;
    }
    return node;
  }
References GetReplacementOf().
Friends And Related Function Documentation
EscapeAnalysisResult
friend class EscapeAnalysisResult [friend]
Definition at line 300 of file escape-analysis.cc.
Member Data Documentation
framestate_might_lazy_deopt_
ZoneUnorderedMap<Node*, bool> v8::internal::compiler::EscapeAnalysisTracker::framestate_might_lazy_deopt_ [private]
Definition at line 318 of file escape-analysis.cc.
jsgraph_
JSGraph* const v8::internal::compiler::EscapeAnalysisTracker::jsgraph_ [private]
Definition at line 322 of file escape-analysis.cc.
kTrackingBudget
constexpr int v8::internal::compiler::EscapeAnalysisTracker::kTrackingBudget = 1300 [static], [constexpr], [private]
Definition at line 301 of file escape-analysis.cc.
Referenced by NewVirtualObject().
next_object_id_
VirtualObject::Id v8::internal::compiler::EscapeAnalysisTracker::next_object_id_ = 0 [private]
Definition at line 320 of file escape-analysis.cc.
Referenced by NewVirtualObject().
number_of_tracked_bytes_
int v8::internal::compiler::EscapeAnalysisTracker::number_of_tracked_bytes_ = 0 [private]
Definition at line 321 of file escape-analysis.cc.
Referenced by NewVirtualObject().
replacements_
Sidetable<Node*> v8::internal::compiler::EscapeAnalysisTracker::replacements_ [private]
Definition at line 317 of file escape-analysis.cc.
Referenced by GetReplacementOf().
variable_states_
VariableTracker v8::internal::compiler::EscapeAnalysisTracker::variable_states_ [private]
Definition at line 319 of file escape-analysis.cc.
Referenced by NewVirtualObject().
virtual_objects_
SparseSidetable<VirtualObject*> v8::internal::compiler::EscapeAnalysisTracker::virtual_objects_ [private]
Definition at line 316 of file escape-analysis.cc.
zone_
Zone* const v8::internal::compiler::EscapeAnalysisTracker::zone_ [private]
Definition at line 323 of file escape-analysis.cc.
Referenced by NewVirtualObject().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/escape-analysis.cc