v8::internal::compiler::InstructionSelector Class Reference
#include <instruction-selector.h>
Classes
struct CachedStateValues
class Features
struct FrameStateInput
class LoadView
class StoreView
Public Types
enum SourcePositionMode { kCallSourcePositions
, kAllSourcePositions
 }
enum EnableScheduling : bool { kDisableScheduling = false
, kEnableScheduling = true
 }
enum EnableRootsRelativeAddressing : bool { kDisableRootsRelativeAddressing = false
, kEnableRootsRelativeAddressing = true
 }
enum EnableSwitchJumpTable : bool { kDisableSwitchJumpTable = false
, kEnableSwitchJumpTable = true
 }
enum EnableTraceTurboJson : bool { kDisableTraceTurboJson = false
, kEnableTraceTurboJson = true
 }
enum EnsureDeterministicNan : bool { kNoDeterministicNan = false
, kEnsureDeterministicNan = true
 }
using source_position_table_t = turboshaft::GrowingOpIndexSidetable< SourcePosition >
Public Member Functions
InstructionSelector (Zone *zone, size_t node_count, Linkage *linkage, InstructionSequence *sequence, turboshaft::Graph *schedule, source_position_table_t *source_positions, Frame *frame, EnableSwitchJumpTable enable_switch_jump_table, TickCounter *tick_counter, JSHeapBroker *broker, size_t *max_unoptimized_frame_height, size_t *max_pushed_argument_count, SourcePositionMode source_position_mode, Features features, EnableScheduling enable_scheduling, EnableRootsRelativeAddressing enable_roots_relative_addressing, EnableTraceTurboJson trace_turbo, EnsureDeterministicNan ensure_deterministic_nan)
std::optional< BailoutReason > SelectInstructions ()
void StartBlock (RpoNumber rpo)
void EndBlock (RpoNumber rpo)
void AddInstruction (Instruction *instr)
void AddTerminator (Instruction *instr)
Instruction * Emit (InstructionCode opcode, InstructionOperand output, size_t temp_count=0, InstructionOperand *temps=nullptr)
Instruction * Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, size_t temp_count=0, InstructionOperand *temps=nullptr)
Instruction * Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, InstructionOperand b, size_t temp_count=0, InstructionOperand *temps=nullptr)
Instruction * Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, InstructionOperand b, InstructionOperand c, size_t temp_count=0, InstructionOperand *temps=nullptr)
Instruction * Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, InstructionOperand b, InstructionOperand c, InstructionOperand d, size_t temp_count=0, InstructionOperand *temps=nullptr)
Instruction * Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, InstructionOperand b, InstructionOperand c, InstructionOperand d, InstructionOperand e, size_t temp_count=0, InstructionOperand *temps=nullptr)
Instruction * Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, InstructionOperand b, InstructionOperand c, InstructionOperand d, InstructionOperand e, InstructionOperand f, size_t temp_count=0, InstructionOperand *temps=nullptr)
Instruction * Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, InstructionOperand b, InstructionOperand c, InstructionOperand d, InstructionOperand e, InstructionOperand f, InstructionOperand g, InstructionOperand h, size_t temp_count=0, InstructionOperand *temps=nullptr)
Instruction * Emit (InstructionCode opcode, size_t output_count, InstructionOperand *outputs, size_t input_count, InstructionOperand *inputs, size_t temp_count=0, InstructionOperand *temps=nullptr)
Instruction * Emit (Instruction *instr)
Instruction * EmitWithContinuation (InstructionCode opcode, FlagsContinuation *cont)
Instruction * EmitWithContinuation (InstructionCode opcode, InstructionOperand a, FlagsContinuation *cont)
Instruction * EmitWithContinuation (InstructionCode opcode, InstructionOperand a, InstructionOperand b, FlagsContinuation *cont)
Instruction * EmitWithContinuation (InstructionCode opcode, InstructionOperand a, InstructionOperand b, InstructionOperand c, FlagsContinuation *cont)
Instruction * EmitWithContinuation (InstructionCode opcode, size_t output_count, InstructionOperand *outputs, size_t input_count, InstructionOperand *inputs, FlagsContinuation *cont)
Instruction * EmitWithContinuation (InstructionCode opcode, size_t output_count, InstructionOperand *outputs, size_t input_count, InstructionOperand *inputs, size_t temp_count, InstructionOperand *temps, FlagsContinuation *cont)
void EmitIdentity (turboshaft::OpIndex node)
bool IsSupported (CpuFeature feature) const
bool CanCover (turboshaft::OpIndex user, turboshaft::OpIndex node) const
bool CanCoverProtectedLoad (turboshaft::OpIndex user, turboshaft::OpIndex node) const
bool IsOnlyUserOfNodeInSameBlock (turboshaft::OpIndex user, turboshaft::OpIndex node) const
bool IsDefined (turboshaft::OpIndex node) const
bool IsUsed (turboshaft::OpIndex node) const
bool IsReallyUsed (turboshaft::OpIndex node) const
bool IsLive (turboshaft::OpIndex node) const
bool IsReallyLive (turboshaft::OpIndex node) const
int GetEffectLevel (turboshaft::OpIndex node) const
int GetEffectLevel (turboshaft::OpIndex node, FlagsContinuation *cont) const
int GetVirtualRegister (turboshaft::OpIndex node)
const std::map< uint32_t, int > GetVirtualRegistersForTesting () const
bool CanAddressRelativeToRootsRegister (const ExternalReference &reference) const
bool CanUseRootsRegister () const
Isolate * isolate () const
const ZoneVector< std::pair< int, int > > & instr_origins () const
turboshaft::OptionalOpIndex FindProjection (turboshaft::OpIndex node, size_t projection_index)
template<typename Op >
auto Inputs (turboshaft::OpIndex node)
template<typename Op , std::size_t... Is>
auto InputsImpl (const Op &op, std::index_sequence< Is... >)
template<size_t InputCount>
auto Inputs (turboshaft::OpIndex node)
bool CanDoBranchIfOverflowFusion (turboshaft::OpIndex node)
void SetProtectedLoadToRemove (turboshaft::OpIndex node)
void MarkAsProtected (turboshaft::OpIndex node)
void UpdateSourcePosition (Instruction *instruction, turboshaft::OpIndex node)
bool IsCommutative (turboshaft::OpIndex node) const
turboshaft::OpIndex block_terminator (const turboshaft::Block *block) const
turboshaft::Graph * turboshaft_graph () const
turboshaft::Block * block (turboshaft::Graph *schedule, turboshaft::OpIndex node) const
RpoNumber rpo_number (const turboshaft::Block *block) const
const ZoneVector< turboshaft::Block * > & rpo_order (turboshaft::Graph *schedule)
bool IsLoopHeader (const turboshaft::Block *block) const
size_t PredecessorCount (const turboshaft::Block *block) const
turboshaft::Block * PredecessorAt (const turboshaft::Block *block, size_t index) const
base::iterator_range< turboshaft::Graph::OpIndexIterator > nodes (const turboshaft::Block *block)
bool IsRetain (turboshaft::OpIndex node) const
bool IsHeapConstant (turboshaft::OpIndex node) const
bool IsExternalConstant (turboshaft::OpIndex node) const
bool IsRelocatableWasmConstant (turboshaft::OpIndex node) const
bool IsLoadOrLoadImmutable (turboshaft::OpIndex node) const
bool IsProtectedLoad (turboshaft::OpIndex node) const
bool is_load (turboshaft::OpIndex node) const
LoadView load_view (turboshaft::OpIndex node)
StoreView store_view (turboshaft::OpIndex node)
Static Public Member Functions
static MachineOperatorBuilder::Flags SupportedMachineOperatorFlags ()
static MachineOperatorBuilder::AlignmentRequirements AlignmentRequirements ()
static InstructionSelector ForTurboshaft (Zone *zone, size_t node_count, Linkage *linkage, InstructionSequence *sequence, turboshaft::Graph *schedule, Frame *frame, EnableSwitchJumpTable enable_switch_jump_table, TickCounter *tick_counter, JSHeapBroker *broker, size_t *max_unoptimized_frame_height, size_t *max_pushed_argument_count, SourcePositionMode source_position_mode, Features features, EnableScheduling enable_scheduling, EnableRootsRelativeAddressing enable_roots_relative_addressing, EnableTraceTurboJson trace_turbo, EnsureDeterministicNan ensure_deterministic_nan)
static Features SupportedFeatures ()
Private Types
enum CallBufferFlag { kCallCodeImmediate = 1u << 0
, kCallAddressImmediate = 1u << 1
, kCallTail = 1u << 2
, kCallFixedTargetRegister = 1u << 3
 }
using CallBufferFlags = base::Flags< CallBufferFlag >
using StateObjectDeduplicator = TurboshaftStateObjectDeduplicator
Private Member Functions
bool UseInstructionScheduling () const
void AppendDeoptimizeArguments (InstructionOperandVector *args, DeoptimizeReason reason, uint32_t node_id, FeedbackSource const &feedback, turboshaft::OpIndex frame_state, DeoptimizeKind kind=DeoptimizeKind::kEager)
void EmitTableSwitch (const SwitchInfo &sw, InstructionOperand const &index_operand)
void EmitBinarySearchSwitch (const SwitchInfo &sw, InstructionOperand const &value_operand)
void MarkAsTableSwitchTarget (const turboshaft::Block *block)
void TryRename (InstructionOperand *op)
int GetRename (int virtual_register)
void SetRename (turboshaft::OpIndex node, turboshaft::OpIndex rename)
void UpdateRenames (Instruction *instruction)
void UpdateRenamesInPhi (PhiInstruction *phi)
void MarkAsDefined (turboshaft::OpIndex node)
void MarkAsUsed (turboshaft::OpIndex node)
void SetEffectLevel (turboshaft::OpIndex node, int effect_level)
void MarkAsRepresentation (MachineRepresentation rep, turboshaft::OpIndex node)
void MarkAsRepresentation (turboshaft::RegisterRepresentation rep, turboshaft::OpIndex node)
void MarkAsWord32 (turboshaft::OpIndex node)
void MarkAsWord64 (turboshaft::OpIndex node)
void MarkAsFloat32 (turboshaft::OpIndex node)
void MarkAsFloat64 (turboshaft::OpIndex node)
void MarkAsSimd128 (turboshaft::OpIndex node)
void MarkAsSimd256 (turboshaft::OpIndex node)
void MarkAsTagged (turboshaft::OpIndex node)
void MarkAsCompressed (turboshaft::OpIndex node)
void MarkAsRepresentation (MachineRepresentation rep, const InstructionOperand &op)
void InitializeCallBuffer (turboshaft::OpIndex call, CallBuffer *buffer, CallBufferFlags flags, turboshaft::OpIndex callee, turboshaft::OptionalOpIndex frame_state_opt, base::Vector< const turboshaft::OpIndex > arguments, int return_count, int stack_slot_delta=0)
bool IsTailCallAddressImmediate ()
void UpdateMaxPushedArgumentCount (size_t count)
FrameStateDescriptor * GetFrameStateDescriptor (turboshaft::OpIndex node)
size_t AddInputsToFrameStateDescriptor (FrameStateDescriptor *descriptor, turboshaft::OpIndex state, OperandGenerator *g, StateObjectDeduplicator *deduplicator, InstructionOperandVector *inputs, FrameStateInputKind kind, Zone *zone)
size_t AddInputsToFrameStateDescriptor (StateValueList *values, InstructionOperandVector *inputs, OperandGenerator *g, StateObjectDeduplicator *deduplicator, turboshaft::OpIndex node, FrameStateInputKind kind, Zone *zone)
size_t AddOperandToStateValueDescriptor (StateValueList *values, InstructionOperandVector *inputs, OperandGenerator *g, StateObjectDeduplicator *deduplicator, turboshaft::OpIndex input, MachineType type, FrameStateInputKind kind, Zone *zone)
void VisitBlock (const turboshaft::Block *block)
void VisitControl (const turboshaft::Block *block)
void VisitNode (turboshaft::OpIndex node)
void VisitFloat64Ieee754Binop (turboshaft::OpIndex, InstructionCode code)
void VisitFloat64Ieee754Unop (turboshaft::OpIndex, InstructionCode code)
void VisitLoad (turboshaft::OpIndex node, turboshaft::OpIndex value, InstructionCode opcode)
void VisitParameter (turboshaft::OpIndex node)
void VisitIfException (turboshaft::OpIndex node)
void VisitOsrValue (turboshaft::OpIndex node)
void VisitPhi (turboshaft::OpIndex node)
void VisitProjection (turboshaft::OpIndex node)
void VisitConstant (turboshaft::OpIndex node)
void VisitCall (turboshaft::OpIndex call, turboshaft::Block *handler={})
void VisitDeoptimizeIf (turboshaft::OpIndex node)
void VisitTrapIf (turboshaft::OpIndex node)
void VisitTailCall (turboshaft::OpIndex call)
void VisitGoto (turboshaft::Block *target)
void VisitBranch (turboshaft::OpIndex input, turboshaft::Block *tbranch, turboshaft::Block *fbranch)
void VisitSwitch (turboshaft::OpIndex node, const SwitchInfo &sw)
void VisitDeoptimize (DeoptimizeReason reason, uint32_t node_id, FeedbackSource const &feedback, turboshaft::OpIndex frame_state)
void VisitSelect (turboshaft::OpIndex node)
void VisitReturn (turboshaft::OpIndex node)
void VisitRetain (turboshaft::OpIndex node)
void VisitUnreachable (turboshaft::OpIndex node)
void VisitStaticAssert (turboshaft::OpIndex node)
void VisitBitcastWord32PairToFloat64 (turboshaft::OpIndex node)
void TryPrepareScheduleFirstProjection (turboshaft::OpIndex maybe_projection)
void VisitStackPointerGreaterThan (turboshaft::OpIndex node, FlagsContinuation *cont)
void VisitWordCompareZero (turboshaft::OpIndex user, turboshaft::OpIndex value, FlagsContinuation *cont)
void EmitPrepareArguments (ZoneVector< PushParameter > *arguments, const CallDescriptor *call_descriptor, turboshaft::OpIndex node)
void EmitPrepareResults (ZoneVector< PushParameter > *results, const CallDescriptor *call_descriptor, turboshaft::OpIndex node)
void EmitMoveFPRToParam (InstructionOperand *op, LinkageLocation location)
void EmitMoveParamToFPR (turboshaft::OpIndex node, int index)
void AddOutputToSelectContinuation (OperandGenerator *g, int first_input_index, turboshaft::OpIndex node)
void ConsumeEqualZero (turboshaft::OpIndex *user, turboshaft::OpIndex *value, FlagsContinuation *cont)
void VisitI8x16RelaxedSwizzle (turboshaft::OpIndex node)
turboshaft::Graph * schedule () const
Linkage * linkage () const
InstructionSequence * sequence () const
base::Vector< const turboshaft::OpIndex > turboshaft_uses (turboshaft::OpIndex node) const
Zone * instruction_zone () const
Zone * zone () const
void set_instruction_selection_failed ()
bool instruction_selection_failed ()
FlagsCondition GetComparisonFlagCondition (const turboshaft::ComparisonOp &op) const
void MarkPairProjectionsAsWord32 (turboshaft::OpIndex node)
bool IsSourcePositionUsed (turboshaft::OpIndex node)
void VisitWord32AtomicBinaryOperation (turboshaft::OpIndex node, ArchOpcode int8_op, ArchOpcode uint8_op, ArchOpcode int16_op, ArchOpcode uint16_op, ArchOpcode word32_op)
void VisitWord64AtomicBinaryOperation (turboshaft::OpIndex node, ArchOpcode uint8_op, ArchOpcode uint16_op, ArchOpcode uint32_op, ArchOpcode uint64_op)
Private Attributes
friend OperandGenerator
Zone *const zone_
Linkage *const linkage_
InstructionSequence *const sequence_
source_position_table_t *const source_positions_
SourcePositionMode const source_position_mode_
Features features_
turboshaft::Graph *const schedule_
const turboshaft::Block * current_block_
ZoneVector< Instruction * > instructions_
InstructionOperandVector continuation_inputs_
InstructionOperandVector continuation_outputs_
InstructionOperandVector continuation_temps_
BitVector defined_
BitVector used_
IntVector effect_level_
int current_effect_level_
IntVector virtual_registers_
IntVector virtual_register_rename_
InstructionScheduler * scheduler_
EnableScheduling enable_scheduling_
EnableRootsRelativeAddressing enable_roots_relative_addressing_
EnableSwitchJumpTable enable_switch_jump_table_
ZoneUnorderedMap< FrameStateInput, CachedStateValues *, typename FrameStateInput::Hash, typename FrameStateInput::Equal > state_values_cache_
Frame * frame_
bool instruction_selection_failed_
ZoneVector< std::pair< int, int > > instr_origins_
EnableTraceTurboJson trace_turbo_
EnsureDeterministicNan ensure_deterministic_nan_
TickCounter *const tick_counter_
JSHeapBroker *const broker_
size_t * max_unoptimized_frame_height_
size_t * max_pushed_argument_count_
std::optional< turboshaft::UseMap > turboshaft_use_map_
std::optional< BitVector > protected_loads_to_remove_
std::optional< BitVector > additional_protected_instructions_
Additional Inherited Members
Detailed Description
Definition at line 391 of file instruction-selector.h.
Member Typedef Documentation
CallBufferFlags
using v8::internal::compiler::InstructionSelector::CallBufferFlags = base::Flags<CallBufferFlag> [private]
Definition at line 1097 of file instruction-selector.h.
source_position_table_t
using v8::internal::compiler::InstructionSelector::source_position_table_t = turboshaft::GrowingOpIndexSidetable<SourcePosition>
Definition at line 394 of file instruction-selector.h.
StateObjectDeduplicator
using v8::internal::compiler::InstructionSelector::StateObjectDeduplicator = TurboshaftStateObjectDeduplicator [private]
Definition at line 1113 of file instruction-selector.h.
Member Enumeration Documentation
CallBufferFlag
enum v8::internal::compiler::InstructionSelector::CallBufferFlag [private]
Enumerator
kCallCodeImmediate
kCallAddressImmediate
kCallTail
kCallFixedTargetRegister
Definition at line 1091 of file instruction-selector.h.
                      {
    kCallCodeImmediate = 1u << 0,
    kCallAddressImmediate = 1u << 1,
    kCallTail = 1u << 2,
    kCallFixedTargetRegister = 1u << 3
  };
EnableRootsRelativeAddressing
enum v8::internal::compiler::InstructionSelector::EnableRootsRelativeAddressing : bool
Enumerator
kDisableRootsRelativeAddressing
kEnableRootsRelativeAddressing
Definition at line 402 of file instruction-selector.h.
                                     : bool {
    kDisableRootsRelativeAddressing = false,
    kEnableRootsRelativeAddressing = true
  };
EnableScheduling
enum v8::internal::compiler::InstructionSelector::EnableScheduling : bool
Enumerator
kDisableScheduling
kEnableScheduling
Definition at line 398 of file instruction-selector.h.
                        : bool {
    kDisableScheduling = false,
    kEnableScheduling = true
  };
EnableSwitchJumpTable
enum v8::internal::compiler::InstructionSelector::EnableSwitchJumpTable : bool
Enumerator
kDisableSwitchJumpTable
kEnableSwitchJumpTable
Definition at line 406 of file instruction-selector.h.
                             : bool {
    kDisableSwitchJumpTable = false,
    kEnableSwitchJumpTable = true
  };
EnableTraceTurboJson
enum v8::internal::compiler::InstructionSelector::EnableTraceTurboJson : bool
Enumerator
kDisableTraceTurboJson
kEnableTraceTurboJson
Definition at line 410 of file instruction-selector.h.
                            : bool {
    kDisableTraceTurboJson = false,
    kEnableTraceTurboJson = true
  };
EnsureDeterministicNan
enum v8::internal::compiler::InstructionSelector::EnsureDeterministicNan : bool
Enumerator
kNoDeterministicNan
kEnsureDeterministicNan
Definition at line 414 of file instruction-selector.h.
                              : bool {
    kNoDeterministicNan = false,
    kEnsureDeterministicNan = true
  };
SourcePositionMode
enum v8::internal::compiler::InstructionSelector::SourcePositionMode
Enumerator
kCallSourcePositions
kAllSourcePositions
Definition at line 397 of file instruction-selector.h.
{ kCallSourcePositions, kAllSourcePositions };
Constructor & Destructor Documentation
InstructionSelector()
v8::internal::compiler::InstructionSelector::InstructionSelector (Zone * zone, size_t node_count, Linkage * linkage, InstructionSequence * sequence, turboshaft::Graph * schedule, source_position_table_t * source_positions, Frame * frame, InstructionSelector::EnableSwitchJumpTable enable_switch_jump_table, TickCounter * tick_counter, JSHeapBroker * broker, size_t * max_unoptimized_frame_height, size_t * max_pushed_argument_count, InstructionSelector::SourcePositionMode source_position_mode, Features features, InstructionSelector::EnableScheduling enable_scheduling, InstructionSelector::EnableRootsRelativeAddressing enable_roots_relative_addressing, InstructionSelector::EnableTraceTurboJson trace_turbo, InstructionSelector::EnsureDeterministicNan ensure_deterministic_nan)
Definition at line 50 of file instruction-selector.cc.
    : OperationMatcher(*schedule),
      zone_(zone),
      linkage_(linkage),
      sequence_(sequence),
      source_positions_(source_positions),
      source_position_mode_(source_position_mode),
      features_(features),
      schedule_(schedule),
      current_block_(nullptr),
      instructions_(zone),
      continuation_inputs_(sequence->zone()),
      continuation_outputs_(sequence->zone()),
      continuation_temps_(sequence->zone()),
      defined_(static_cast<int>(node_count), zone),
      used_(static_cast<int>(node_count), zone),
      effect_level_(node_count, 0, zone),
      virtual_registers_(node_count,
                         InstructionOperand::kInvalidVirtualRegister, zone),
      virtual_register_rename_(zone),
      scheduler_(nullptr),
      enable_scheduling_(enable_scheduling),
      enable_roots_relative_addressing_(enable_roots_relative_addressing),
      enable_switch_jump_table_(enable_switch_jump_table),
      state_values_cache_(zone),
      frame_(frame),
      instruction_selection_failed_(false),
      instr_origins_(sequence->zone()),
      trace_turbo_(trace_turbo),
      ensure_deterministic_nan_(ensure_deterministic_nan),
      tick_counter_(tick_counter),
      broker_(broker),
      max_unoptimized_frame_height_(max_unoptimized_frame_height),
      max_pushed_argument_count_(max_pushed_argument_count)
#if V8_TARGET_ARCH_64_BIT
      ,
      node_count_(node_count),
      phi_states_(zone)
#endif
{
    turboshaft_use_map_.emplace(*schedule_, zone);
    protected_loads_to_remove_.emplace(static_cast<int>(node_count), zone);
    additional_protected_instructions_.emplace(static_cast<int>(node_count),
                                               zone);
  DCHECK_EQ(*max_unoptimized_frame_height, 0); // Caller-initialized.
  instructions_.reserve(node_count);
  continuation_inputs_.reserve(5);
  continuation_outputs_.reserve(2);
  if (trace_turbo_) {
    instr_origins_.assign(node_count, {-1, 0});
  }
}
References additional_protected_instructions_, v8::internal::ZoneVector< T >::assign(), continuation_inputs_, continuation_outputs_, DCHECK_EQ, instr_origins_, instructions_, protected_loads_to_remove_, v8::internal::ZoneVector< T >::reserve(), schedule_, trace_turbo_, turboshaft_use_map_, and zone().
Referenced by ForTurboshaft().
Member Function Documentation
AddInputsToFrameStateDescriptor() [1/2]
size_t v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor (FrameStateDescriptor * descriptor, turboshaft::OpIndex state, OperandGenerator * g, StateObjectDeduplicator * deduplicator, InstructionOperandVector * inputs, FrameStateInputKind kind, Zone * zone) [private]
Definition at line 889 of file instruction-selector.cc.
                                                                            {
  FrameStateOp& state =
      schedule()->Get(state_node).template Cast<FrameStateOp>();
  const FrameStateInfo& info = state.data->frame_state_info;
  USE(info);
  FrameStateData::Iterator it = state.data->iterator(state.state_values());
  size_t entries = 0;
  size_t initial_size = inputs->size();
  USE(initial_size); // initial_size is only used for debug.
  if (descriptor->outer_state()) {
    entries += AddInputsToFrameStateDescriptor(
        descriptor->outer_state(), state.parent_frame_state(), g, deduplicator,
        inputs, kind, zone);
  }
  DCHECK_EQ(descriptor->parameters_count(), info.parameter_count());
  DCHECK_EQ(descriptor->locals_count(), info.local_count());
  DCHECK_EQ(descriptor->stack_count(), info.stack_count());
  StateValueList* values_descriptor = descriptor->GetStateValueDescriptors();
  DCHECK_EQ(values_descriptor->size(), 0u);
  values_descriptor->ReserveSize(descriptor->GetSize());
  // Function
  if (descriptor->HasClosure()) {
    entries += v8::internal::compiler::AddOperandToStateValueDescriptor(
        this, values_descriptor, inputs, g, deduplicator, &it,
        FrameStateInputKind::kStackSlot, zone);
  } else {
    // Advance the iterator either way.
    MachineType unused_type;
    OpIndex unused_input;
    it.ConsumeInput(&unused_type, &unused_input);
  }
  // Parameters
  for (size_t i = 0; i < descriptor->parameters_count(); ++i) {
    entries += v8::internal::compiler::AddOperandToStateValueDescriptor(
        this, values_descriptor, inputs, g, deduplicator, &it, kind, zone);
  }
  // Context
  if (descriptor->HasContext()) {
    entries += v8::internal::compiler::AddOperandToStateValueDescriptor(
        this, values_descriptor, inputs, g, deduplicator, &it,
        FrameStateInputKind::kStackSlot, zone);
  } else {
    // Advance the iterator either way.
    MachineType unused_type;
    OpIndex unused_input;
    it.ConsumeInput(&unused_type, &unused_input);
  }
  // Locals
  for (size_t i = 0; i < descriptor->locals_count(); ++i) {
    entries += v8::internal::compiler::AddOperandToStateValueDescriptor(
        this, values_descriptor, inputs, g, deduplicator, &it, kind, zone);
  }
  // Stack
  for (size_t i = 0; i < descriptor->stack_count(); ++i) {
    entries += v8::internal::compiler::AddOperandToStateValueDescriptor(
        this, values_descriptor, inputs, g, deduplicator, &it, kind, zone);
  }
  DCHECK_EQ(initial_size + entries, inputs->size());
  return entries;
}
References v8::internal::compiler::AddOperandToStateValueDescriptor(), v8::internal::compiler::turboshaft::FrameStateData::Iterator::ConsumeInput(), v8::internal::compiler::turboshaft::FrameStateOp::data, DCHECK_EQ, v8::internal::compiler::turboshaft::FrameStateData::frame_state_info, v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::FrameStateDescriptor::GetSize(), v8::internal::compiler::FrameStateDescriptor::GetStateValueDescriptors(), v8::internal::compiler::FrameStateDescriptor::HasClosure(), v8::internal::compiler::FrameStateDescriptor::HasContext(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::FrameStateData::iterator(), v8::internal::compiler::turboshaft::OperationMatcher::kind, v8::internal::compiler::kStackSlot, v8::internal::compiler::FrameStateInfo::local_count(), v8::internal::compiler::FrameStateDescriptor::locals_count(), v8::internal::compiler::FrameStateDescriptor::outer_state(), v8::internal::compiler::FrameStateInfo::parameter_count(), v8::internal::compiler::FrameStateDescriptor::parameters_count(), v8::internal::compiler::turboshaft::FrameStateOp::parent_frame_state(), v8::internal::compiler::StateValueList::ReserveSize(), schedule(), v8::internal::compiler::StateValueList::size(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::FrameStateDescriptor::stack_count(), v8::internal::compiler::FrameStateInfo::stack_count(), v8::internal::compiler::turboshaft::FrameStateOp::state_values(), USE, and zone().
Referenced by AppendDeoptimizeArguments(), and InitializeCallBuffer().
AddInputsToFrameStateDescriptor() [2/2]
size_t v8::internal::compiler::InstructionSelector::AddInputsToFrameStateDescriptor (StateValueList * values, InstructionOperandVector * inputs, OperandGenerator * g, StateObjectDeduplicator * deduplicator, turboshaft::OpIndex node, FrameStateInputKind kind, Zone * zone) [private]
AddInstruction()
void v8::internal::compiler::InstructionSelector::AddInstruction (Instruction * instr)
Definition at line 200 of file instruction-selector.cc.
                                                           {
  if (UseInstructionScheduling()) {
    DCHECK_NOT_NULL(scheduler_);
    scheduler_->AddInstruction(instr);
  } else {
    sequence()->AddInstruction(instr);
  }
}
References v8::internal::compiler::InstructionScheduler::AddInstruction(), v8::internal::compiler::InstructionSequence::AddInstruction(), DCHECK_NOT_NULL, scheduler_, sequence(), and UseInstructionScheduling().
Referenced by SelectInstructions().
AddOperandToStateValueDescriptor()
size_t v8::internal::compiler::InstructionSelector::AddOperandToStateValueDescriptor (StateValueList * values, InstructionOperandVector * inputs, OperandGenerator * g, StateObjectDeduplicator * deduplicator, turboshaft::OpIndex input, MachineType type, FrameStateInputKind kind, Zone * zone) [private]
AddOutputToSelectContinuation()
void v8::internal::compiler::InstructionSelector::AddOutputToSelectContinuation (OperandGenerator * g, int first_input_index, turboshaft::OpIndex node) [private]
Definition at line 3527 of file instruction-selector-arm.cc.
                                                                      {
  UNREACHABLE();
}
References v8::internal::UNREACHABLE().
Referenced by EmitWithContinuation().
AddTerminator()
void v8::internal::compiler::InstructionSelector::AddTerminator (Instruction * instr)
Definition at line 191 of file instruction-selector.cc.
                                                          {
  if (UseInstructionScheduling()) {
    DCHECK_NOT_NULL(scheduler_);
    scheduler_->AddTerminator(instr);
  } else {
    sequence()->AddInstruction(instr);
  }
}
References v8::internal::compiler::InstructionSequence::AddInstruction(), v8::internal::compiler::InstructionScheduler::AddTerminator(), DCHECK_NOT_NULL, scheduler_, sequence(), and UseInstructionScheduling().
Referenced by SelectInstructions().
AlignmentRequirements()
MachineOperatorBuilder::AlignmentRequirements v8::internal::compiler::InstructionSelector::AlignmentRequirements () [static]
Definition at line 3563 of file instruction-selector-arm.cc.
                                           {
  base::EnumSet<MachineRepresentation> req_aligned;
  req_aligned.Add(MachineRepresentation::kFloat32);
  req_aligned.Add(MachineRepresentation::kFloat64);
  return MachineOperatorBuilder::AlignmentRequirements::
      SomeUnalignedAccessUnsupported(req_aligned, req_aligned);
}
References v8::base::EnumSet< E, T >::Add(), v8::internal::kFloat32, v8::internal::kFloat64, and v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::SomeUnalignedAccessUnsupported().
Referenced by v8::internal::compiler::turboshaft::SupportedOperations::HasFullUnalignedSupport(), v8::internal::compiler::TFPipelineData::InitializeWithGraphZone(), v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedLoadSupported(), v8::internal::compiler::turboshaft::SupportedOperations::IsUnalignedStoreSupported(), v8::internal::compiler::TFPipelineData::TFPipelineData(), and VisitNode().
AppendDeoptimizeArguments()
void v8::internal::compiler::InstructionSelector::AppendDeoptimizeArguments (InstructionOperandVector * args, DeoptimizeReason reason, uint32_t node_id, FeedbackSource const & feedback, turboshaft::OpIndex frame_state, DeoptimizeKind kind = DeoptimizeKind::kEager) [private]
Definition at line 1071 of file instruction-selector.cc.
                                                                              {
  OperandGenerator g(this);
  FrameStateDescriptor* const descriptor = GetFrameStateDescriptor(frame_state);
  int const state_id = sequence()->AddDeoptimizationEntry(
      descriptor, kind, reason, node_id, feedback);
  args->push_back(g.TempImmediate(state_id));
  StateObjectDeduplicator deduplicator(instruction_zone());
  AddInputsToFrameStateDescriptor(descriptor, frame_state, &g, &deduplicator,
                                  args, FrameStateInputKind::kAny,
                                  instruction_zone());
}
References v8::internal::compiler::InstructionSequence::AddDeoptimizationEntry(), AddInputsToFrameStateDescriptor(), v8::base::args, GetFrameStateDescriptor(), instruction_zone(), v8::internal::compiler::kAny, v8::internal::compiler::turboshaft::OperationMatcher::kind, sequence(), and v8::internal::compiler::OperandGenerator::TempImmediate().
Referenced by EmitWithContinuation(), and VisitDeoptimize().
block()
turboshaft::Block* v8::internal::compiler::InstructionSelector::block (turboshaft::Graph * schedule, turboshaft::OpIndex node) const [inline]
Definition at line 686 of file instruction-selector.h.
                                                         {
    // TODO(nicohartmann@): This might be too slow and we should consider
    // precomputing.
    return &schedule->Get(schedule->BlockOf(node));
  }
References v8::internal::compiler::turboshaft::Graph::BlockOf(), and v8::internal::compiler::turboshaft::Graph::Get().
Referenced by CanCover(), CanDoBranchIfOverflowFusion(), IsOnlyUserOfNodeInSameBlock(), SelectInstructions(), TryPrepareScheduleFirstProjection(), VisitBlock(), VisitControl(), and VisitNode().
block_terminator()
turboshaft::OpIndex v8::internal::compiler::InstructionSelector::block_terminator (const turboshaft::Block * block) const [inline]
Definition at line 679 of file instruction-selector.h.
                                                                         {
    return schedule_->PreviousIndex(block->end());
  }
References v8::internal::compiler::turboshaft::Block::end().
Referenced by GetEffectLevel(), and VisitBlock().
CanAddressRelativeToRootsRegister()
bool v8::internal::compiler::InstructionSelector::CanAddressRelativeToRootsRegister (const ExternalReference & reference) const
Definition at line 585 of file instruction-selector.cc.
                                              {
  // There are three things to consider here:
  // 1. CanUseRootsRegister: Is kRootRegister initialized?
  const bool root_register_is_available_and_initialized = CanUseRootsRegister();
  if (!root_register_is_available_and_initialized) return false;
  // 2. enable_roots_relative_addressing_: Can we address everything on the heap
  // through the root register, i.e. are root-relative addresses to arbitrary
  // addresses guaranteed not to change between code generation and
  // execution?
  if (enable_roots_relative_addressing_) return true;
  // 3. IsAddressableThroughRootRegister: Is the target address guaranteed to
  // have a fixed root-relative offset? If so, we can ignore 2.
  const bool this_root_relative_offset_is_constant =
      MacroAssemblerBase::IsAddressableThroughRootRegister(isolate(),
                                                           reference);
  return this_root_relative_offset_is_constant;
}
References CanUseRootsRegister(), enable_roots_relative_addressing_, v8::internal::MacroAssemblerBase::IsAddressableThroughRootRegister(), and isolate().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), and v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon().
CanCover()
bool v8::internal::compiler::InstructionSelector::CanCover (turboshaft::OpIndex user, turboshaft::OpIndex node) const
Definition at line 368 of file instruction-selector.cc.
                                                                   {
  // 1. Both {user} and {node} must be in the same basic block.
  if (block(schedule(), node) != current_block_) {
    return false;
  }
  const Operation& op = Get(node);
  // 2. If node does not produce anything, it can be covered.
  if (op.Effects().produces.bits() == 0) {
    return is_exclusive_user_of(schedule(), user, node);
  }
  // 3. Otherwise, the {node}'s effect level must match the {user}'s.
  if (GetEffectLevel(node) != current_effect_level_) {
    return false;
  }
  // 4. Only {node} must have value edges pointing to {user}.
  return is_exclusive_user_of(schedule(), user, node);
}
References v8::internal::compiler::turboshaft::EffectDimensions::bits(), block(), current_block_, current_effect_level_, v8::internal::compiler::turboshaft::Operation::Effects(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), GetEffectLevel(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::is_exclusive_user_of(), v8::internal::compiler::turboshaft::OpEffects::produces, and schedule().
Referenced by CanCoverProtectedLoad(), ConsumeEqualZero(), v8::internal::compiler::turboshaft::FindCompareChain(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::ExtendingLoadMatcher::Initialize(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::MaybeReplaceCmpZeroWithFlagSettingBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::MaybeReplaceCmpZeroWithFlagSettingBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitBitfieldExtract32(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyAdd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyNegate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplySub(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchAnyExtend(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchAnyShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchLoadStoreShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryMatchSignExtendShift(), and v8::internal::compiler::TryMatchSignExtInt16OrInt8FromWord32Sar().
CanCoverProtectedLoad()
bool v8::internal::compiler::InstructionSelector::CanCoverProtectedLoad (turboshaft::OpIndex user, turboshaft::OpIndex node) const
Definition at line 389 of file instruction-selector.cc.
                                                                    {
  DCHECK(CanCover(user, node));
  const Graph* graph = this->turboshaft_graph();
  for (OpIndex next = graph->NextIndex(node); next.valid();
       next = graph->NextIndex(next)) {
    if (next == user) break;
    const Operation& op = graph->Get(next);
    OpEffects effects = op.Effects();
    if (effects.produces.control_flow || effects.required_when_unused) {
      return false;
    }
  }
  return true;
}
References CanCover(), v8::internal::compiler::turboshaft::EffectDimensions::control_flow, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::Operation::Effects(), graph(), v8::internal::compiler::turboshaft::OpEffects::produces, v8::internal::compiler::turboshaft::OpEffects::required_when_unused, and turboshaft_graph().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop().
CanDoBranchIfOverflowFusion()
bool v8::internal::compiler::InstructionSelector::CanDoBranchIfOverflowFusion (turboshaft::OpIndex node)
Definition at line 2046 of file instruction-selector.cc.
                                                                   {
  const Graph* graph = this->turboshaft_graph();
  DCHECK(graph->Get(binop).template Is<OverflowCheckedBinopOp>() ||
         graph->Get(binop).template Is<OverflowCheckedUnaryOp>());
  // Getting the 1st projection. Projections are always emitted right after the
  // operation, in ascending order.
  OpIndex projection0_index = graph->NextIndex(binop);
  const ProjectionOp& projection0 =
      graph->Get(projection0_index).Cast<ProjectionOp>();
  DCHECK_EQ(projection0.index, 0);
  if (IsDefined(projection0_index)) {
    // In Turboshaft, this can only happen if {projection0_index} has already
    // been eagerly scheduled somewhere else, like in
    // TryPrepareScheduleFirstProjection.
    return true;
  }
  if (projection0.saturated_use_count.IsOne()) {
    // If the projection has a single use, it is the following tuple, so we
    // don't care about the value, and can do branch-if-overflow fusion.
    DCHECK(turboshaft_uses(projection0_index).size() == 1 &&
           graph->Get(turboshaft_uses(projection0_index)[0]).Is<TupleOp>());
    return true;
  }
  if (this->block(schedule_, binop) != current_block_) {
    // {binop} is not supposed to be defined in the current block, so let's not
    // pull it in this block (the checks would need to be stronger, and it's
    // unlikely that it's doable because of effect levels and all).
    return false;
  }
  // We now need to make sure that all uses of {projection0} are already
  // defined, which will imply that it's fine to define {projection0} and
  // {binop} now.
  for (OpIndex use : turboshaft_uses(projection0_index)) {
    if (this->Get(use).template Is<TupleOp>()) {
      // The Tuple won't have any uses since it would have to be accessed
      // through Projections, and Projections on Tuples return the original
      // Projection instead (see Assembler::ReduceProjection in
      // turboshaft/assembler.h).
      DCHECK(this->Get(use).saturated_use_count.IsZero());
      continue;
    }
    if (IsDefined(use)) continue;
    if (this->block(schedule_, use) != current_block_) {
      // {use} is in a later block, so it should already have been visited. Note
      // that operations that don't produce values are not marked as Defined,
      // like Return for instance, so it's possible that {use} has been visited
      // but the previous `IsDefined` check didn't match.
#ifdef DEBUG
      if (this->block(schedule_, use)->index() < current_block_->index()) {
        // If {use} is in a previous block, then it has to be a loop Phi that
        // uses {projection0} as its backedge input. In that case, it's fine to
        // schedule the binop right now, even though it's after the use of its
        // 1st projection (since the use is conceptually after rather than
        // before because it goes through a backedge).
        DCHECK(this->Get(use).template Is<PhiOp>());
        DCHECK_EQ(this->Get(use).template Cast<PhiOp>().input(1),
                  projection0_index);
      }
#endif
      continue;
    }
    if (this->Get(use).template Is<PhiOp>()) {
      DCHECK_EQ(this->block(schedule_, use), current_block_);
      // If {projection0} is used by a Phi in the current block, then it has to
      // be a loop phi, and {projection0} has to be its backedge value. This
      // doesn't prevent scheduling {projection0} now, since anyways it
      // necessarily needs to be scheduled after the Phi.
      DCHECK(current_block_->IsLoop());
      continue;
    }
    // {use} is not defined yet (and is not a special case), which means that
    // {projection0} has a use that comes before {binop}, and we thus can't fuse
    // binop with a branch to do a branch-if-overflow.
    return false;
  }
  VisitProjection(projection0_index);
  return true;
}
References block(), current_block_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), graph(), v8::internal::compiler::turboshaft::Block::index(), v8::internal::compiler::turboshaft::ProjectionOp::index, v8::internal::index, IsDefined(), v8::internal::compiler::turboshaft::Block::IsLoop(), v8::internal::compiler::turboshaft::SaturatedUint8::IsOne(), v8::internal::compiler::turboshaft::Operation::saturated_use_count, schedule_, size(), turboshaft_graph(), turboshaft_uses(), use(), and VisitProjection().
CanUseRootsRegister()
bool v8::internal::compiler::InstructionSelector::CanUseRootsRegister () const
Definition at line 606 of file instruction-selector.cc.
                                                    {
  return linkage()->GetIncomingDescriptor()->flags() &
         CallDescriptor::kCanUseRoots;
}
References v8::internal::compiler::CallDescriptor::flags(), v8::internal::compiler::Linkage::GetIncomingDescriptor(), v8::internal::compiler::CallDescriptor::kCanUseRoots, and linkage().
Referenced by CanAddressRelativeToRootsRegister(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32EqualImpl(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64EqualImpl().
ConsumeEqualZero()
void v8::internal::compiler::InstructionSelector::ConsumeEqualZero (turboshaft::OpIndex * user, turboshaft::OpIndex * value, FlagsContinuation * cont) [private]
Definition at line 1568 of file instruction-selector.cc.
                                                                    {
  // Try to combine with comparisons against 0 by simply inverting the branch.
  while (const ComparisonOp* equal =
             TryCast<Opmask::kComparisonEqual>(*value)) {
    if (equal->rep == RegisterRepresentation::Word32()) {
      if (!MatchIntegralZero(equal->right())) return;
#ifdef V8_COMPRESS_POINTERS
    } else if (equal->rep == RegisterRepresentation::Tagged()) {
      static_assert(RegisterRepresentation::Tagged().MapTaggedToWord() ==
                    RegisterRepresentation::Word32());
      if (!MatchSmiZero(equal->right())) return;
#endif // V8_COMPRESS_POINTERS
    } else {
      return;
    }
    if (!CanCover(*user, *value)) return;
    *user = *value;
    *value = equal->left();
    cont->Negate();
  }
}
References CanCover(), v8::internal::equal, v8::internal::compiler::turboshaft::OperationMatcher::MatchIntegralZero(), v8::internal::compiler::turboshaft::OperationMatcher::MatchSmiZero(), v8::internal::compiler::FlagsContinuation::Negate(), v8::internal::compiler::turboshaft::RegisterRepresentation::Tagged(), v8::internal::value, and v8::internal::compiler::turboshaft::RegisterRepresentation::Word32().
Emit() [1/10]
Instruction * v8::internal::compiler::InstructionSelector::Emit (Instruction * instr)
Definition at line 313 of file instruction-selector.cc.
                                                         {
  instructions_.push_back(instr);
  return instr;
}
References instructions_, and v8::internal::ZoneVector< T >::push_back().
Emit() [2/10]
Instruction * v8::internal::compiler::InstructionSelector::Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, InstructionOperand b, InstructionOperand c, InstructionOperand d, InstructionOperand e, InstructionOperand f, InstructionOperand g, InstructionOperand h, size_t temp_count = 0, InstructionOperand * temps = nullptr)
Definition at line 284 of file instruction-selector.cc.
                                                                        {
  size_t output_count = output.IsInvalid() ? 0 : 1;
  InstructionOperand inputs[] = {a, b, c, d, e, f, g, h};
  size_t input_count = arraysize(inputs);
  return Emit(opcode, output_count, &output, input_count, inputs, temp_count,
              temps);
}
References arraysize, Emit(), h(), and v8::internal::compiler::turboshaft::detail::input_count().
Emit() [3/10]
Instruction * v8::internal::compiler::InstructionSelector::Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, InstructionOperand b, InstructionOperand c, InstructionOperand d, InstructionOperand e, InstructionOperand f, size_t temp_count = 0, InstructionOperand * temps = nullptr)
Definition at line 272 of file instruction-selector.cc.
                               {
  size_t output_count = output.IsInvalid() ? 0 : 1;
  InstructionOperand inputs[] = {a, b, c, d, e, f};
  size_t input_count = arraysize(inputs);
  return Emit(opcode, output_count, &output, input_count, inputs, temp_count,
              temps);
}
References arraysize, Emit(), and v8::internal::compiler::turboshaft::detail::input_count().
Emit() [4/10]
Instruction * v8::internal::compiler::InstructionSelector::Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, InstructionOperand b, InstructionOperand c, InstructionOperand d, InstructionOperand e, size_t temp_count = 0, InstructionOperand * temps = nullptr)
Definition at line 261 of file instruction-selector.cc.
                                                                        {
  size_t output_count = output.IsInvalid() ? 0 : 1;
  InstructionOperand inputs[] = {a, b, c, d, e};
  size_t input_count = arraysize(inputs);
  return Emit(opcode, output_count, &output, input_count, inputs, temp_count,
              temps);
}
References arraysize, Emit(), and v8::internal::compiler::turboshaft::detail::input_count().
Emit() [5/10]
Instruction * v8::internal::compiler::InstructionSelector::Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, InstructionOperand b, InstructionOperand c, InstructionOperand d, size_t temp_count = 0, InstructionOperand * temps = nullptr)
Definition at line 250 of file instruction-selector.cc.
                                                  {
  size_t output_count = output.IsInvalid() ? 0 : 1;
  InstructionOperand inputs[] = {a, b, c, d};
  size_t input_count = arraysize(inputs);
  return Emit(opcode, output_count, &output, input_count, inputs, temp_count,
              temps);
}
References arraysize, Emit(), and v8::internal::compiler::turboshaft::detail::input_count().
Emit() [6/10]
Instruction * v8::internal::compiler::InstructionSelector::Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, InstructionOperand b, InstructionOperand c, size_t temp_count = 0, InstructionOperand * temps = nullptr)
Definition at line 237 of file instruction-selector.cc.
                                                                  {
  size_t output_count = output.IsInvalid() ? 0 : 1;
  InstructionOperand inputs[] = {a, b, c};
  size_t input_count = arraysize(inputs);
  return Emit(opcode, output_count, &output, input_count, inputs, temp_count,
              temps);
}
References arraysize, Emit(), and v8::internal::compiler::turboshaft::detail::input_count().
Emit() [7/10]
Instruction * v8::internal::compiler::InstructionSelector::Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, InstructionOperand b, size_t temp_count = 0, InstructionOperand * temps = nullptr)
Definition at line 225 of file instruction-selector.cc.
                                                                  {
  size_t output_count = output.IsInvalid() ? 0 : 1;
  InstructionOperand inputs[] = {a, b};
  size_t input_count = arraysize(inputs);
  return Emit(opcode, output_count, &output, input_count, inputs, temp_count,
              temps);
}
References arraysize, Emit(), and v8::internal::compiler::turboshaft::detail::input_count().
Emit() [8/10]
Instruction * v8::internal::compiler::InstructionSelector::Emit (InstructionCode opcode, InstructionOperand output, InstructionOperand a, size_t temp_count = 0, InstructionOperand * temps = nullptr)
Definition at line 217 of file instruction-selector.cc.
                                                                  {
  size_t output_count = output.IsInvalid() ? 0 : 1;
  return Emit(opcode, output_count, &output, 1, &a, temp_count, temps);
}
References Emit().
Emit() [9/10]
Instruction * v8::internal::compiler::InstructionSelector::Emit (InstructionCode opcode, InstructionOperand output, size_t temp_count = 0, InstructionOperand * temps = nullptr)
Definition at line 209 of file instruction-selector.cc.
                                                                  {
  size_t output_count = output.IsInvalid() ? 0 : 1;
  return Emit(opcode, output_count, &output, 0, nullptr, temp_count, temps);
}
Referenced by Emit(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitAddBeforeS128LoadStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitBic(), EmitBinarySearchSwitch(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::EmitLea(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::EmitLea(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), v8::internal::compiler::EmitS128Load(), v8::internal::compiler::EmitSignExtendWord(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitStore(), EmitTableSwitch(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitUbfx(), EmitWithContinuation(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitBitfieldExtract32(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitExtendingLoad(), v8::internal::compiler::TryEmitExtendingLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyAdd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplyNegate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitMultiplySub(), v8::internal::compiler::TryMatchNegFromSub(), v8::internal::compiler::TryMatchShiftFromMul(), v8::internal::compiler::TryMatchSignExtInt16OrInt8FromWord32Sar(), v8::internal::compiler::OperandGenerator::UsePointerLocation(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAddSub(), v8::internal::compiler::VisitAtomicBinaryOperation(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicBinop(), v8::internal::compiler::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicBinOp(), v8::internal::compiler::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicCompareExchange(), v8::internal::compiler::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitAtomicExchange(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBitMask(), VisitBlock(), VisitCall(), VisitConstant(), VisitDeoptimize(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitFloatUnop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatUnop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitFullWord32Compare(), v8::internal::compiler::VisitGeneralStore(), VisitGoto(), VisitIfException(), v8::internal::compiler::VisitInt32PairBinop(), v8::internal::compiler::VisitLoadCommon(), v8::internal::compiler::VisitLogical(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMinOrMax(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMul(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitMulHigh(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMulHigh(), VisitNode(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitOptimizedWord32Compare(), VisitOsrValue(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::VisitPairAtomicBinop(), VisitParameter(), VisitRetain(), VisitReturn(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTemp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitROWithTempSimd(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRR(), v8::internal::compiler::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRR(), v8::internal::compiler::VisitRRI(), v8::internal::compiler::VisitRRIR(), v8::internal::compiler::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitRRO(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRROFloat(), v8::internal::compiler::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitRRR(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitRRR(), v8::internal::compiler::VisitShift(), v8::internal::compiler::VisitSimdShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), v8::internal::compiler::VisitStoreCommon(), VisitTailCall(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitTryTruncateDouble(), v8::internal::compiler::VisitUniqueRRR(), VisitUnreachable(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift(), v8::internal::compiler::VisitWord32PairShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32Shift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64Shift().
Emit() [10/10]
Instruction * v8::internal::compiler::InstructionSelector::Emit (InstructionCode opcode, size_t output_count, InstructionOperand * outputs, size_t input_count, InstructionOperand * inputs, size_t temp_count = 0, InstructionOperand * temps = nullptr)
Definition at line 296 of file instruction-selector.cc.
                               {
  if (output_count >= Instruction::kMaxOutputCount ||
      input_count >= Instruction::kMaxInputCount ||
      temp_count >= Instruction::kMaxTempCount) {
    set_instruction_selection_failed();
    return nullptr;
  }
  Instruction* instr =
      Instruction::New(instruction_zone(), opcode, output_count, outputs,
                       input_count, inputs, temp_count, temps);
  return Emit(instr);
}
References Emit(), v8::internal::compiler::turboshaft::detail::input_count(), instruction_zone(), v8::internal::compiler::Instruction::kMaxInputCount, v8::internal::compiler::Instruction::kMaxOutputCount, v8::internal::compiler::Instruction::kMaxTempCount, v8::internal::compiler::Instruction::New(), and set_instruction_selection_failed().
EmitBinarySearchSwitch()
void v8::internal::compiler::InstructionSelector::EmitBinarySearchSwitch (const SwitchInfo & sw, InstructionOperand const & value_operand) [private]
Definition at line 1748 of file instruction-selector.cc.
                                                                   {
  OperandGenerator g(this);
  size_t input_count = 2 + sw.case_count() * 2;
  DCHECK_LE(sw.case_count(), (std::numeric_limits<size_t>::max() - 2) / 2);
  auto* inputs =
      zone()->template AllocateArray<InstructionOperand>(input_count);
  inputs[0] = value_operand;
  inputs[1] = g.Label(sw.default_branch());
  std::vector<CaseInfo> cases = sw.CasesSortedByValue();
  for (size_t index = 0; index < cases.size(); ++index) {
    const CaseInfo& c = cases[index];
    inputs[index * 2 + 2 + 0] = g.TempImmediate(c.value);
    inputs[index * 2 + 2 + 1] = g.Label(c.branch);
  }
  Emit(kArchBinarySearchSwitch, 0, nullptr, input_count, inputs, 0, nullptr);
}
References v8::internal::compiler::CaseInfo::branch, v8::internal::compiler::SwitchInfo::case_count(), v8::internal::compiler::SwitchInfo::CasesSortedByValue(), DCHECK_LE, v8::internal::compiler::SwitchInfo::default_branch(), Emit(), v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::OperandGenerator::Label(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::CaseInfo::value, and zone().
EmitIdentity()
void v8::internal::compiler::InstructionSelector::EmitIdentity (turboshaft::OpIndex node)
Definition at line 2545 of file instruction-selector.cc.
                                                   {
  const Operation& op = Get(node);
  MarkAsUsed(op.input(0));
  MarkAsDefined(node);
  SetRename(node, op.input(0));
}
References v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::Operation::input(), MarkAsDefined(), MarkAsUsed(), and SetRename().
Referenced by VisitNode(), and VisitProjection().
EmitMoveFPRToParam()
void v8::internal::compiler::InstructionSelector::EmitMoveFPRToParam (InstructionOperand * op, LinkageLocation location) [private]
Definition at line 1844 of file instruction-selector-arm.cc.
                                                                       {}
Referenced by InitializeCallBuffer().
EmitMoveParamToFPR()
void v8::internal::compiler::InstructionSelector::EmitMoveParamToFPR (turboshaft::OpIndex node, int index) [private]
Definition at line 1842 of file instruction-selector-arm.cc.
{}
Referenced by VisitParameter().
EmitPrepareArguments()
void v8::internal::compiler::InstructionSelector::EmitPrepareArguments (ZoneVector< PushParameter > * arguments, const CallDescriptor * call_descriptor, turboshaft::OpIndex node) [private]
Definition at line 1847 of file instruction-selector-arm.cc.
                  {
  ArmOperandGenerator g(this);
  // Prepare for C function call.
  if (call_descriptor->IsCFunctionCall()) {
    Emit(kArchPrepareCallCFunction | MiscField::encode(static_cast<int>(
                                         call_descriptor->ParameterCount())),
         0, nullptr, 0, nullptr);
    // Poke any stack arguments.
    for (size_t n = 0; n < arguments->size(); ++n) {
      PushParameter input = (*arguments)[n];
      if (input.node.valid()) {
        int slot = static_cast<int>(n);
        Emit(kArmPoke | MiscField::encode(slot), g.NoOutput(),
             g.UseRegister(input.node));
      }
    }
  } else {
    // Push any stack arguments.
    int stack_decrement = 0;
    for (PushParameter input : base::Reversed(*arguments)) {
      stack_decrement += kSystemPointerSize;
      // Skip any alignment holes in pushed nodes.
      if (!input.node.valid()) continue;
      InstructionOperand decrement = g.UseImmediate(stack_decrement);
      stack_decrement = 0;
      Emit(kArmPush, g.NoOutput(), decrement, g.UseRegister(input.node));
    }
  }
}
References v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::CallDescriptor::IsCFunctionCall(), v8::internal::kSystemPointerSize, v8::internal::compiler::PushParameter::node, v8::internal::compiler::OperandGenerator::NoOutput(), v8::internal::compiler::CallDescriptor::ParameterCount(), v8::base::Reversed(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by VisitCall().
EmitPrepareResults()
void v8::internal::compiler::InstructionSelector::EmitPrepareResults (ZoneVector< PushParameter > * results, const CallDescriptor * call_descriptor, turboshaft::OpIndex node) [private]
Definition at line 1881 of file instruction-selector-arm.cc.
                  {
  ArmOperandGenerator g(this);
  for (PushParameter output : *results) {
    if (!output.location.IsCallerFrameSlot()) continue;
    // Skip any alignment holes in nodes.
    if (output.node.valid()) {
      DCHECK(!call_descriptor->IsCFunctionCall());
      if (output.location.GetType() == MachineType::Float32()) {
        MarkAsFloat32(output.node);
      } else if (output.location.GetType() == MachineType::Float64()) {
        MarkAsFloat64(output.node);
      } else if (output.location.GetType() == MachineType::Simd128()) {
        MarkAsSimd128(output.node);
      }
      int offset = call_descriptor->GetOffsetToReturns();
      int reverse_slot = -output.location.GetLocation() - offset;
      Emit(kArmPeek, g.DefineAsRegister(output.node),
           g.UseImmediate(reverse_slot));
    }
  }
}
References v8::internal::DCHECK(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::MachineType::Float32(), v8::internal::MachineType::Float64(), v8::internal::compiler::CallDescriptor::GetOffsetToReturns(), v8::internal::compiler::CallDescriptor::IsCFunctionCall(), v8::internal::MachineType::Simd128(), and v8::internal::compiler::OperandGenerator::UseImmediate().
Referenced by VisitCall().
EmitTableSwitch()
void v8::internal::compiler::InstructionSelector::EmitTableSwitch (const SwitchInfo & sw, InstructionOperand const & index_operand) [private]
Definition at line 1722 of file instruction-selector.cc.
                                                                   {
  OperandGenerator g(this);
  size_t input_count = 2 + sw.value_range();
  DCHECK_LE(sw.value_range(), std::numeric_limits<size_t>::max() - 2);
  auto* inputs =
      zone()->template AllocateArray<InstructionOperand>(input_count);
  inputs[0] = index_operand;
  InstructionOperand default_operand = g.Label(sw.default_branch());
  std::fill(&inputs[1], &inputs[input_count], default_operand);
  for (const CaseInfo& c : sw.CasesUnsorted()) {
    size_t value = c.value - sw.min_value();
    DCHECK_LE(0u, value);
    DCHECK_LT(value + 2, input_count);
    inputs[value + 2] = g.Label(c.branch);
    MarkAsTableSwitchTarget(c.branch);
  }
  // If the default operand still exists in the cases, to fill gaps, then we
  // need to mark the default block as table switch target.
  if (std::find(&inputs[2], &inputs[input_count], default_operand) !=
      &inputs[input_count]) {
    MarkAsTableSwitchTarget(sw.default_branch());
  }
  Emit(kArchTableSwitch, 0, nullptr, input_count, inputs, 0, nullptr);
}
References v8::internal::compiler::SwitchInfo::CasesUnsorted(), DCHECK_LE, DCHECK_LT, v8::internal::compiler::SwitchInfo::default_branch(), Emit(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::OperandGenerator::Label(), MarkAsTableSwitchTarget(), v8::internal::compiler::SwitchInfo::min_value(), v8::internal::value, v8::internal::compiler::SwitchInfo::value_range(), and zone().
EmitWithContinuation() [1/6]
Instruction* v8::internal::compiler::InstructionSelector::EmitWithContinuation (InstructionCode opcode, FlagsContinuation * cont)
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitBranchOrDeoptimize(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt32MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::EmitInt64MulWithOverflow(), v8::internal::compiler::EmitInt64MulWithOverflow(), EmitWithContinuation(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::EmitWordCompareZero(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::TryEmitCbzOrTbz(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryVisitWordShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitBinOp(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitBinopImpl(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitCompare(), v8::internal::compiler::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompare(), v8::internal::compiler::turboshaft::VisitCompareChain(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitCompareWithMemoryOperand(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareWithMemoryOperand(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitLoadAndTest(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitShift(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitUnaryOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare(), and v8::internal::compiler::VisitWordCompareZero().
EmitWithContinuation() [2/6]
Instruction * v8::internal::compiler::InstructionSelector::EmitWithContinuation (InstructionCode opcode, InstructionOperand a, FlagsContinuation * cont)
Definition at line 963 of file instruction-selector.cc.
                                                                           {
  return EmitWithContinuation(opcode, 0, nullptr, 1, &a, cont);
}
References EmitWithContinuation().
EmitWithContinuation() [3/6]
Instruction * v8::internal::compiler::InstructionSelector::EmitWithContinuation (InstructionCode opcode, InstructionOperand a, InstructionOperand b, FlagsContinuation * cont)
Definition at line 968 of file instruction-selector.cc.
                             {
  InstructionOperand inputs[] = {a, b};
  return EmitWithContinuation(opcode, 0, nullptr, arraysize(inputs), inputs,
                              cont);
}
References arraysize, and EmitWithContinuation().
EmitWithContinuation() [4/6]
Instruction * v8::internal::compiler::InstructionSelector::EmitWithContinuation (InstructionCode opcode, InstructionOperand a, InstructionOperand b, InstructionOperand c, FlagsContinuation * cont)
Definition at line 976 of file instruction-selector.cc.
                                                   {
  InstructionOperand inputs[] = {a, b, c};
  return EmitWithContinuation(opcode, 0, nullptr, arraysize(inputs), inputs,
                              cont);
}
References arraysize, and EmitWithContinuation().
EmitWithContinuation() [5/6]
Instruction * v8::internal::compiler::InstructionSelector::EmitWithContinuation (InstructionCode opcode, size_t output_count, InstructionOperand * outputs, size_t input_count, InstructionOperand * inputs, FlagsContinuation * cont)
Definition at line 984 of file instruction-selector.cc.
                                                                             {
  return EmitWithContinuation(opcode, output_count, outputs, input_count,
                              inputs, 0, nullptr, cont);
}
References EmitWithContinuation(), and v8::internal::compiler::turboshaft::detail::input_count().
EmitWithContinuation() [6/6]
Instruction * v8::internal::compiler::InstructionSelector::EmitWithContinuation (InstructionCode opcode, size_t output_count, InstructionOperand * outputs, size_t input_count, InstructionOperand * inputs, size_t temp_count, InstructionOperand * temps, FlagsContinuation * cont)
Definition at line 991 of file instruction-selector.cc.
                                                        {
  OperandGenerator g(this);
  opcode = cont->Encode(opcode);
  continuation_inputs_.resize(0);
  for (size_t i = 0; i < input_count; i++) {
    continuation_inputs_.push_back(inputs[i]);
  }
  continuation_outputs_.resize(0);
  for (size_t i = 0; i < output_count; i++) {
    continuation_outputs_.push_back(outputs[i]);
  }
  continuation_temps_.resize(0);
  for (size_t i = 0; i < temp_count; i++) {
    continuation_temps_.push_back(temps[i]);
  }
  if (cont->IsBranch() || cont->IsConditionalBranch()) {
    continuation_inputs_.push_back(g.Label(cont->true_block()));
    continuation_inputs_.push_back(g.Label(cont->false_block()));
  } else if (cont->IsDeoptimize()) {
    int immediate_args_count = 0;
    opcode |= DeoptImmedArgsCountField::encode(immediate_args_count) |
              DeoptFrameStateOffsetField::encode(static_cast<int>(input_count));
    AppendDeoptimizeArguments(&continuation_inputs_, cont->reason(),
                              cont->node_id(), cont->feedback(),
                              cont->frame_state());
  } else if (cont->IsSet() || cont->IsConditionalSet()) {
    continuation_outputs_.push_back(g.DefineAsRegister(cont->result()));
  } else if (cont->IsSelect()) {
    // The {Select} should put one of two values into the output register,
    // depending on the result of the condition. The two result values are in
    // the last two input slots, the {false_value} in {input_count - 2}, and the
    // true_value in {input_count - 1}. The other inputs are used for the
    // condition.
    AddOutputToSelectContinuation(&g, static_cast<int>(input_count) - 2,
                                  cont->result());
  } else if (cont->IsTrap()) {
    int trap_id = static_cast<int>(cont->trap_id());
    continuation_inputs_.push_back(g.UseImmediate(trap_id));
  } else {
    DCHECK(cont->IsNone());
  }
  size_t const emit_inputs_size = continuation_inputs_.size();
  auto* emit_inputs =
      emit_inputs_size ? &continuation_inputs_.front() : nullptr;
  size_t const emit_outputs_size = continuation_outputs_.size();
  auto* emit_outputs =
      emit_outputs_size ? &continuation_outputs_.front() : nullptr;
  size_t const emit_temps_size = continuation_temps_.size();
  auto* emit_temps = emit_temps_size ? &continuation_temps_.front() : nullptr;
  return Emit(opcode, emit_outputs_size, emit_outputs, emit_inputs_size,
              emit_inputs, emit_temps_size, emit_temps);
}
References AddOutputToSelectContinuation(), AppendDeoptimizeArguments(), continuation_inputs_, continuation_outputs_, continuation_temps_, v8::internal::DCHECK(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), Emit(), v8::internal::compiler::FlagsContinuation::Encode(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::FlagsContinuation::false_block(), v8::internal::compiler::FlagsContinuation::feedback(), v8::internal::compiler::FlagsContinuation::frame_state(), v8::internal::ZoneVector< T >::front(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::FlagsContinuation::IsBranch(), v8::internal::compiler::FlagsContinuation::IsConditionalBranch(), v8::internal::compiler::FlagsContinuation::IsConditionalSet(), v8::internal::compiler::FlagsContinuation::IsDeoptimize(), v8::internal::compiler::FlagsContinuation::IsNone(), v8::internal::compiler::FlagsContinuation::IsSelect(), v8::internal::compiler::FlagsContinuation::IsSet(), v8::internal::compiler::FlagsContinuation::IsTrap(), v8::internal::compiler::OperandGenerator::Label(), v8::internal::compiler::FlagsContinuation::node_id(), v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::FlagsContinuation::reason(), v8::internal::ZoneVector< T >::resize(), v8::internal::compiler::FlagsContinuation::result(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::FlagsContinuation::trap_id(), v8::internal::compiler::FlagsContinuation::true_block(), and v8::internal::compiler::OperandGenerator::UseImmediate().
EndBlock()
void v8::internal::compiler::InstructionSelector::EndBlock (RpoNumber rpo)
Definition at line 182 of file instruction-selector.cc.
                                                {
  if (UseInstructionScheduling()) {
    DCHECK_NOT_NULL(scheduler_);
    scheduler_->EndBlock(rpo);
  } else {
    sequence()->EndBlock(rpo);
  }
}
References DCHECK_NOT_NULL, v8::internal::compiler::InstructionScheduler::EndBlock(), v8::internal::compiler::InstructionSequence::EndBlock(), scheduler_, sequence(), and UseInstructionScheduling().
Referenced by SelectInstructions().
FindProjection()
OptionalOpIndex v8::internal::compiler::InstructionSelector::FindProjection (turboshaft::OpIndex node, size_t projection_index)
Definition at line 420 of file instruction-selector.cc.
                                                                             {
  const Graph* graph = this->turboshaft_graph();
  // Projections are always emitted right after the operation.
  for (OpIndex next = graph->NextIndex(node); next.valid();
       next = graph->NextIndex(next)) {
    const ProjectionOp* projection = graph->Get(next).TryCast<ProjectionOp>();
    if (projection == nullptr) break;
    DCHECK(!projection->saturated_use_count.IsZero());
    if (projection->saturated_use_count.IsOne()) {
      // If the projection has a single use, it is the following tuple, so we
      // don't return it, since there is no point in emitting it.
      DCHECK(turboshaft_uses(next).size() == 1 &&
             graph->Get(turboshaft_uses(next)[0]).Is<TupleOp>());
      continue;
    }
    if (projection->index == projection_index) return next;
  }
  // If there is no Projection with index {projection_index} following the
  // operation, then there shouldn't be any such Projection in the graph. We
  // verify this in Debug mode.
#ifdef DEBUG
  for (OpIndex use : turboshaft_uses(node)) {
    if (const ProjectionOp* projection =
            this->Get(use).TryCast<ProjectionOp>()) {
      DCHECK_EQ(projection->input(), node);
      if (projection->index == projection_index) {
        // If we found the projection, it should have a single use: a Tuple
        // (which doesn't count as a regular use since it is just an artifact of
        // the Turboshaft graph).
        DCHECK(turboshaft_uses(use).size() == 1 &&
               graph->Get(turboshaft_uses(use)[0]).Is<TupleOp>());
      }
    }
  }
#endif // DEBUG
  return OpIndex::Invalid();
}
References v8::internal::DCHECK(), DCHECK_EQ, v8::internal::compiler::turboshaft::OperationMatcher::Get(), graph(), v8::internal::compiler::turboshaft::ProjectionOp::index, v8::internal::compiler::turboshaft::OpIndex::Invalid(), v8::internal::compiler::turboshaft::SaturatedUint8::IsOne(), v8::internal::compiler::turboshaft::SaturatedUint8::IsZero(), v8::internal::compiler::turboshaft::Operation::saturated_use_count, size(), turboshaft_graph(), turboshaft_uses(), and use().
Referenced by MarkPairProjectionsAsWord32(), v8::internal::compiler::TryMatchInt32MulWithOverflow(), v8::internal::compiler::TryMatchInt32OpWithOverflow(), v8::internal::compiler::TryMatchInt64OpWithOverflow(), TryPrepareScheduleFirstProjection(), v8::internal::compiler::VisitInt32PairBinop(), VisitNode(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitPairAtomicBinOp(), v8::internal::compiler::VisitPairAtomicBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-ppc.cc}::VisitTryTruncateDouble(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitWord32PairShift(), v8::internal::compiler::VisitWord32PairShift(), and v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitWord32PairShift().
ForTurboshaft()
InstructionSelector v8::internal::compiler::InstructionSelector::ForTurboshaft (Zone * zone, size_t node_count, Linkage * linkage, InstructionSequence * sequence, turboshaft::Graph * schedule, Frame * frame, EnableSwitchJumpTable enable_switch_jump_table, TickCounter * tick_counter, JSHeapBroker * broker, size_t * max_unoptimized_frame_height, size_t * max_pushed_argument_count, SourcePositionMode source_position_mode, Features features, EnableScheduling enable_scheduling, EnableRootsRelativeAddressing enable_roots_relative_addressing, EnableTraceTurboJson trace_turbo, EnsureDeterministicNan ensure_deterministic_nan) [static]
Definition at line 3992 of file instruction-selector.cc.
                                                     {
  return InstructionSelector(
      zone, node_count, linkage, sequence, graph, &graph->source_positions(),
      frame, enable_switch_jump_table, tick_counter, broker,
      max_unoptimized_frame_height, max_pushed_argument_count,
      source_position_mode, features, enable_scheduling,
      enable_roots_relative_addressing, trace_turbo, ensure_deterministic_nan);
}
References broker(), graph(), InstructionSelector(), linkage(), sequence(), and zone().
Referenced by v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run().
GetComparisonFlagCondition()
FlagsCondition v8::internal::compiler::InstructionSelector::GetComparisonFlagCondition (const turboshaft::ComparisonOp & op) const [private]
Definition at line 1541 of file instruction-selector.cc.
                                  {
  switch (op.kind) {
    case ComparisonOp::Kind::kEqual:
      return kEqual;
    case ComparisonOp::Kind::kSignedLessThan:
      return kSignedLessThan;
    case ComparisonOp::Kind::kSignedLessThanOrEqual:
      return kSignedLessThanOrEqual;
    case ComparisonOp::Kind::kUnsignedLessThan:
      return kUnsignedLessThan;
    case ComparisonOp::Kind::kUnsignedLessThanOrEqual:
      return kUnsignedLessThanOrEqual;
  }
}
References v8::internal::kEqual, v8::internal::compiler::kEqual, v8::internal::compiler::turboshaft::ComparisonOp::kind, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThan, and v8::internal::compiler::kUnsignedLessThanOrEqual.
GetEffectLevel() [1/2]
int v8::internal::compiler::InstructionSelector::GetEffectLevel (turboshaft::OpIndex node) const
Definition at line 564 of file instruction-selector.cc.
                                                          {
  DCHECK(node.valid());
  size_t const id = node.id();
  DCHECK_LT(id, effect_level_.size());
  return effect_level_[id];
}
References v8::internal::DCHECK(), DCHECK_LT, effect_level_, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::ZoneVector< T >::size(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by CanCover(), GetEffectLevel(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::TryEmitLoadForLoadWord64AndShiftRight(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), v8::internal::compiler::VisitBinop(), VisitBlock(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitLoadAndTest(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWordCompare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare().
GetEffectLevel() [2/2]
int v8::internal::compiler::InstructionSelector::GetEffectLevel (turboshaft::OpIndex node, FlagsContinuation * cont) const
Definition at line 571 of file instruction-selector.cc.
                                                                       {
  return cont->IsBranch() ? GetEffectLevel(this->block_terminator(
                                this->PredecessorAt(cont->true_block(), 0)))
                          : GetEffectLevel(node);
}
References block_terminator(), GetEffectLevel(), v8::internal::compiler::FlagsContinuation::IsBranch(), PredecessorAt(), and v8::internal::compiler::FlagsContinuation::true_block().
GetFrameStateDescriptor()
FrameStateDescriptor * v8::internal::compiler::InstructionSelector::GetFrameStateDescriptor (turboshaft::OpIndex node) [private]
Definition at line 3972 of file instruction-selector.cc.
                  {
  const FrameStateOp& state =
      this->turboshaft_graph()->Get(node).template Cast<FrameStateOp>();
  auto* desc = GetFrameStateDescriptorInternal(instruction_zone(),
                                               this->turboshaft_graph(), state);
  *max_unoptimized_frame_height_ =
      std::max(*max_unoptimized_frame_height_,
               desc->total_conservative_frame_size_in_bytes() +
                   (desc->max_arguments() * kSystemPointerSize));
  return desc;
}
References v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::GetFrameStateDescriptorInternal(), instruction_zone(), v8::internal::kSystemPointerSize, max_unoptimized_frame_height_, and turboshaft_graph().
Referenced by AppendDeoptimizeArguments(), and VisitCall().
GetRename()
int v8::internal::compiler::InstructionSelector::GetRename (int virtual_register) [private]
Definition at line 476 of file instruction-selector.cc.
                                                       {
  int rename = virtual_register;
  while (true) {
    if (static_cast<size_t>(rename) >= virtual_register_rename_.size()) break;
    int next = virtual_register_rename_[rename];
    if (next == InstructionOperand::kInvalidVirtualRegister) {
      break;
    }
    rename = next;
  }
  return rename;
}
References v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister, v8::internal::ZoneVector< T >::size(), and virtual_register_rename_.
Referenced by TryRename(), and UpdateRenamesInPhi().
GetVirtualRegister()
int v8::internal::compiler::InstructionSelector::GetVirtualRegister (turboshaft::OpIndex node)
Definition at line 508 of file instruction-selector.cc.
                                                        {
  DCHECK(node.valid());
  size_t const id = node.id();
  DCHECK_LT(id, virtual_registers_.size());
  int virtual_register = virtual_registers_[id];
  if (virtual_register == InstructionOperand::kInvalidVirtualRegister) {
    virtual_register = sequence()->NextVirtualRegister();
    virtual_registers_[id] = virtual_register;
  }
  return virtual_register;
}
References v8::internal::DCHECK(), DCHECK_LT, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister, v8::internal::compiler::InstructionSequence::NextVirtualRegister(), sequence(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::turboshaft::OpIndex::valid(), and virtual_registers_.
Referenced by v8::internal::compiler::OperandGenerator::GetVReg(), MarkAsRepresentation(), SetRename(), and VisitPhi().
GetVirtualRegistersForTesting()
const std::map< uint32_t, int > v8::internal::compiler::InstructionSelector::GetVirtualRegistersForTesting () const
Definition at line 521 of file instruction-selector.cc.
                                                         {
  std::map<uint32_t, int> virtual_registers;
  for (size_t n = 0; n < virtual_registers_.size(); ++n) {
    if (virtual_registers_[n] != InstructionOperand::kInvalidVirtualRegister) {
      const uint32_t id = static_cast<uint32_t>(n);
      virtual_registers.insert(std::make_pair(id, virtual_registers_[n]));
    }
  }
  return virtual_registers;
}
References v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister, v8::internal::ZoneVector< T >::size(), and virtual_registers_.
InitializeCallBuffer()
void v8::internal::compiler::InstructionSelector::InitializeCallBuffer (turboshaft::OpIndex call, CallBuffer * buffer, CallBufferFlags flags, turboshaft::OpIndex callee, turboshaft::OptionalOpIndex frame_state_opt, base::Vector< const turboshaft::OpIndex > arguments, int return_count, int stack_slot_delta = 0) [private]
Definition at line 1124 of file instruction-selector.cc.
                                             {
  OperandGenerator g(this);
  size_t ret_count = buffer->descriptor->ReturnCount();
  bool is_tail_call = (flags & kCallTail) != 0;
  DCHECK_LE(return_count, ret_count);
  if (ret_count > 0) {
    // Collect the projections that represent multiple outputs from this call.
    if (ret_count == 1) {
      PushParameter result = {node, buffer->descriptor->GetReturnLocation(0)};
      buffer->output_nodes.push_back(result);
    } else {
      buffer->output_nodes.resize(ret_count);
      for (size_t i = 0; i < ret_count; ++i) {
        LinkageLocation location = buffer->descriptor->GetReturnLocation(i);
        buffer->output_nodes[i] = PushParameter({}, location);
      }
      for (OpIndex call_use : turboshaft_uses(node)) {
        const Operation& use_op = this->Get(call_use);
        if (use_op.Is<DidntThrowOp>()) {
          for (OpIndex use : turboshaft_uses(call_use)) {
            const ProjectionOp& projection = Cast<ProjectionOp>(use);
            size_t index = projection.index;
            DCHECK_LT(index, buffer->output_nodes.size());
            DCHECK(!buffer->output_nodes[index].node.valid());
            buffer->output_nodes[index].node = use;
          }
        } else {
          DCHECK(use_op.Is<CheckExceptionOp>());
        }
      }
      frame_->EnsureReturnSlots(
          static_cast<int>(buffer->descriptor->ReturnSlotCount()));
    }
    // Filter out the outputs that aren't live because no projection uses them.
    size_t outputs_needed_by_framestate =
        buffer->frame_state_descriptor == nullptr
            ? 0
            : buffer->frame_state_descriptor->state_combine()
                  .ConsumedOutputCount();
    for (size_t i = 0; i < buffer->output_nodes.size(); i++) {
      bool output_is_live = buffer->output_nodes[i].node.valid() ||
                            i < outputs_needed_by_framestate;
      if (output_is_live) {
        LinkageLocation location = buffer->output_nodes[i].location;
        MachineRepresentation rep = location.GetType().representation();
        OpIndex output = buffer->output_nodes[i].node;
        InstructionOperand op = !output.valid()
                                    ? g.TempLocation(location)
                                    : g.DefineAsLocation(output, location);
        MarkAsRepresentation(rep, op);
        if (!UnallocatedOperand::cast(op).HasFixedSlotPolicy()) {
          buffer->outputs.push_back(op);
          buffer->output_nodes[i].node = {};
        }
      }
    }
  }
  // The first argument is always the callee code.
  bool call_code_immediate = (flags & kCallCodeImmediate) != 0;
  bool call_address_immediate = (flags & kCallAddressImmediate) != 0;
  bool call_use_fixed_target_reg = (flags & kCallFixedTargetRegister) != 0;
  DeoptimizeKind deopt_kind = DeoptimizeKind::kLazy;
  switch (buffer->descriptor->kind()) {
    case CallDescriptor::kCallCodeObject:
      buffer->instruction_args.push_back(
          (call_code_immediate && this->IsHeapConstant(callee))
              ? g.UseImmediate(callee)
          : call_use_fixed_target_reg
              ? g.UseFixed(callee, kJavaScriptCallCodeStartRegister)
              : g.UseRegister(callee));
      break;
    case CallDescriptor::kCallAddress:
      // TODO(ahaas): Rename kLazyAfterFastCall and similarly called fields on
      // the isolate to reflect that they are used for every direct call to C++
      // and not just for fast API calls.
      deopt_kind = DeoptimizeKind::kLazyAfterFastCall;
      buffer->instruction_args.push_back(
          (call_address_immediate && this->IsExternalConstant(callee))
              ? g.UseImmediate(callee)
          : call_use_fixed_target_reg
              ? g.UseFixed(callee, kJavaScriptCallCodeStartRegister)
              : g.UseRegister(callee));
      break;
#if V8_ENABLE_WEBASSEMBLY
    case CallDescriptor::kCallWasmCapiFunction:
    case CallDescriptor::kCallWasmFunction:
    case CallDescriptor::kCallWasmFunctionIndirect:
    case CallDescriptor::kCallWasmImportWrapper:
      buffer->instruction_args.push_back(
          (call_address_immediate && this->IsRelocatableWasmConstant(callee))
              ? g.UseImmediate(callee)
          : call_use_fixed_target_reg
              ? g.UseFixed(callee, kJavaScriptCallCodeStartRegister)
              : g.UseRegister(callee));
      break;
#endif // V8_ENABLE_WEBASSEMBLY
    case CallDescriptor::kCallBuiltinPointer: {
      // The common case for builtin pointers is to have the target in a
      // register. If we have a constant, we use a register anyway to simplify
      // related code.
      LinkageLocation location = buffer->descriptor->GetInputLocation(0);
      bool location_is_fixed_register =
          location.IsRegister() && !location.IsAnyRegister();
      InstructionOperand op;
      // If earlier phases specified a particular register, don't override
      // their choice.
      if (location_is_fixed_register) {
        op = g.UseLocation(callee, location);
      } else if (call_use_fixed_target_reg) {
        op = g.UseFixed(callee, kJavaScriptCallCodeStartRegister);
      } else {
        op = g.UseRegister(callee);
      }
      buffer->instruction_args.push_back(op);
      break;
    }
    case CallDescriptor::kCallJSFunction:
      buffer->instruction_args.push_back(
          g.UseLocation(callee, buffer->descriptor->GetInputLocation(0)));
      break;
  }
  DCHECK_EQ(1u, buffer->instruction_args.size());
  // If the call needs a frame state, we insert the state information as
  // follows (n is the number of value inputs to the frame state):
  // arg 1 : deoptimization id.
  // arg 2 - arg (n + 2) : value inputs to the frame state.
  size_t frame_state_entries = 0;
  USE(frame_state_entries); // frame_state_entries is only used for debug.
  if (buffer->frame_state_descriptor != nullptr) {
    OpIndex frame_state = frame_state_opt.value();
    // If it was a syntactic tail call we need to drop the current frame and
    // all the frames on top of it that are either inlined extra arguments
    // or a tail caller frame.
    if (is_tail_call) {
      frame_state = Cast<FrameStateOp>(frame_state).parent_frame_state();
      buffer->frame_state_descriptor =
          buffer->frame_state_descriptor->outer_state();
      while (buffer->frame_state_descriptor != nullptr &&
             buffer->frame_state_descriptor->type() ==
                 FrameStateType::kInlinedExtraArguments) {
        frame_state = Cast<FrameStateOp>(frame_state).parent_frame_state();
        buffer->frame_state_descriptor =
            buffer->frame_state_descriptor->outer_state();
      }
    }
    int const state_id = sequence()->AddDeoptimizationEntry(
        buffer->frame_state_descriptor, deopt_kind, DeoptimizeReason::kUnknown,
        node.id(), FeedbackSource());
    buffer->instruction_args.push_back(g.TempImmediate(state_id));
    StateObjectDeduplicator deduplicator(instruction_zone());
    frame_state_entries =
        1 + AddInputsToFrameStateDescriptor(
                buffer->frame_state_descriptor, frame_state, &g, &deduplicator,
                &buffer->instruction_args, FrameStateInputKind::kStackSlot,
                instruction_zone());
    DCHECK_EQ(1 + frame_state_entries, buffer->instruction_args.size());
  }
  size_t input_count = buffer->input_count();
  // Split the arguments into pushed_nodes and instruction_args. Pushed
  // arguments require an explicit push instruction before the call and do
  // not appear as arguments to the call. Everything else ends up
  // as an InstructionOperand argument to the call.
  auto iter(arguments.begin());
  size_t pushed_count = 0;
  for (size_t index = 1; index < input_count; ++iter, ++index) {
    DCHECK_NE(iter, arguments.end());
    LinkageLocation location = buffer->descriptor->GetInputLocation(index);
    if (is_tail_call) {
      location = LinkageLocation::ConvertToTailCallerLocation(
          location, stack_param_delta);
    }
    InstructionOperand op = g.UseLocation(*iter, location);
    UnallocatedOperand unallocated = UnallocatedOperand::cast(op);
    if (unallocated.HasFixedSlotPolicy() && !is_tail_call) {
      int stack_index = buffer->descriptor->GetStackIndexFromSlot(
          unallocated.fixed_slot_index());
      // This can insert empty slots before stack_index and will insert enough
      // slots after stack_index to store the parameter.
      if (static_cast<size_t>(stack_index) >= buffer->pushed_nodes.size()) {
        int num_slots = location.GetSizeInPointers();
        buffer->pushed_nodes.resize(stack_index + num_slots);
      }
      PushParameter param = {*iter, location};
      buffer->pushed_nodes[stack_index] = param;
      pushed_count++;
    } else {
      if (location.IsNullRegister()) {
        EmitMoveFPRToParam(&op, location);
      }
      buffer->instruction_args.push_back(op);
    }
  }
  DCHECK_EQ(input_count, buffer->instruction_args.size() + pushed_count -
                             frame_state_entries);
  USE(pushed_count);
  if (V8_TARGET_ARCH_STORES_RETURN_ADDRESS_ON_STACK && is_tail_call &&
      stack_param_delta != 0) {
    // For tail calls that change the size of their parameter list and keep
    // their return address on the stack, move the return address to just above
    // the parameters.
    LinkageLocation saved_return_location =
        LinkageLocation::ForSavedCallerReturnAddress();
    InstructionOperand return_address =
        g.UsePointerLocation(LinkageLocation::ConvertToTailCallerLocation(
                                 saved_return_location, stack_param_delta),
                             saved_return_location);
    buffer->instruction_args.push_back(return_address);
  }
}
References v8::internal::compiler::InstructionSequence::AddDeoptimizationEntry(), AddInputsToFrameStateDescriptor(), v8::base::Vector< T >::begin(), v8::internal::compiler::OutputFrameStateCombine::ConsumedOutputCount(), v8::internal::LinkageLocation::ConvertToTailCallerLocation(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, DCHECK_LT, DCHECK_NE, v8::internal::compiler::OperandGenerator::DefineAsLocation(), v8::internal::compiler::CallBuffer::descriptor, EmitMoveFPRToParam(), v8::base::Vector< T >::end(), v8::internal::compiler::Frame::EnsureReturnSlots(), v8::internal::compiler::UnallocatedOperand::fixed_slot_index(), v8::internal::flags, v8::internal::LinkageLocation::ForSavedCallerReturnAddress(), frame_, v8::internal::compiler::CallBuffer::frame_state_descriptor, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::CallDescriptor::GetInputLocation(), v8::internal::compiler::CallDescriptor::GetReturnLocation(), v8::internal::LinkageLocation::GetSizeInPointers(), v8::internal::compiler::CallDescriptor::GetStackIndexFromSlot(), v8::internal::LinkageLocation::GetType(), v8::internal::compiler::UnallocatedOperand::HasFixedSlotPolicy(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::ProjectionOp::index, v8::internal::index, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::CallBuffer::input_count(), v8::internal::compiler::CallBuffer::instruction_args, instruction_zone(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::LinkageLocation::IsAnyRegister(), IsExternalConstant(), IsHeapConstant(), v8::internal::LinkageLocation::IsNullRegister(), v8::internal::LinkageLocation::IsRegister(), IsRelocatableWasmConstant(), v8::internal::compiler::CallDescriptor::kCallAddress, kCallAddressImmediate, v8::internal::compiler::CallDescriptor::kCallBuiltinPointer, kCallCodeImmediate, v8::internal::compiler::CallDescriptor::kCallCodeObject, kCallFixedTargetRegister, v8::internal::compiler::CallDescriptor::kCallJSFunction, kCallTail, v8::internal::compiler::CallDescriptor::kind(), v8::internal::compiler::kInlinedExtraArguments, v8::internal::kJavaScriptCallCodeStartRegister, v8::internal::kLazy, v8::internal::kLazyAfterFastCall, v8::internal::compiler::kStackSlot, MarkAsRepresentation(), v8::internal::compiler::FrameStateDescriptor::outer_state(), v8::internal::compiler::CallBuffer::output_nodes, v8::internal::compiler::CallBuffer::outputs, v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::CallBuffer::pushed_nodes, v8::internal::compiler::turboshaft::OperationMatcher::rep, v8::internal::MachineType::representation(), v8::base::internal::result, v8::internal::compiler::CallDescriptor::ReturnCount(), v8::internal::compiler::CallDescriptor::ReturnSlotCount(), sequence(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::FrameStateDescriptor::state_combine(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempLocation(), turboshaft_uses(), v8::internal::compiler::FrameStateDescriptor::type(), USE, use(), v8::internal::compiler::OperandGenerator::UseFixed(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseLocation(), v8::internal::compiler::OperandGenerator::UsePointerLocation(), v8::internal::compiler::OperandGenerator::UseRegister(), V8_TARGET_ARCH_STORES_RETURN_ADDRESS_ON_STACK, v8::internal::compiler::turboshaft::OpIndex::valid(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
Referenced by VisitCall(), and VisitTailCall().
Inputs() [1/2]
template<typename Op >
auto v8::internal::compiler::InstructionSelector::Inputs (turboshaft::OpIndex node) [inline]
Definition at line 639 of file instruction-selector.h.
                                      {
    const Op& op = Cast<Op>(node);
    return InputsImpl(op, std::make_index_sequence<Op::input_count>());
  }
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMod(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMul(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMulHigh(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitWordCompare().
Inputs() [2/2]
template<size_t InputCount>
auto v8::internal::compiler::InstructionSelector::Inputs (turboshaft::OpIndex node) [inline]
Definition at line 648 of file instruction-selector.h.
                                      {
    const turboshaft::Operation& op = Get(node);
    DCHECK_EQ(InputCount, op.input_count);
    return InputsImpl(op, std::make_index_sequence<InputCount>());
  }
References DCHECK_EQ, v8::internal::compiler::turboshaft::Get(), and v8::internal::compiler::turboshaft::Operation::input_count.
InputsImpl()
template<typename Op , std::size_t... Is>
auto v8::internal::compiler::InstructionSelector::InputsImpl (const Op & op, std::index_sequence< Is... >) [inline]
Definition at line 644 of file instruction-selector.h.
                                                          {
    return std::make_tuple(op.input(Is)...);
  }
References v8::internal::Is().
instr_origins()
const ZoneVector<std::pair<int, int> >& v8::internal::compiler::InstructionSelector::instr_origins () const [inline]
Definition at line 632 of file instruction-selector.h.
                                                             {
    return instr_origins_;
  }
instruction_selection_failed()
bool v8::internal::compiler::InstructionSelector::instruction_selection_failed () [inline], [private]
Definition at line 1517 of file instruction-selector.h.
{ return instruction_selection_failed_; }
Referenced by SelectInstructions(), VisitBlock(), and VisitCall().
instruction_zone()
Zone* v8::internal::compiler::InstructionSelector::instruction_zone () const [inline], [private]
Definition at line 1511 of file instruction-selector.h.
{ return sequence()->zone(); }
Referenced by AppendDeoptimizeArguments(), Emit(), GetFrameStateDescriptor(), InitializeCallBuffer(), VisitDeoptimize(), VisitPhi(), and v8::internal::compiler::OperandGenerator::zone().
is_load()
bool v8::internal::compiler::InstructionSelector::is_load (turboshaft::OpIndex node) const [inline]
Definition at line 747 of file instruction-selector.h.
                                             {
    const turboshaft::Operation& op = Get(node);
    return op.Is<turboshaft::LoadOp>()
#if V8_ENABLE_WEBASSEMBLY
           || op.Is<turboshaft::Simd128LoadTransformOp>()
#if V8_ENABLE_WASM_SIMD256_REVEC
           || op.Is<turboshaft::Simd256LoadTransformOp>()
#endif // V8_ENABLE_WASM_SIMD256_REVEC
#endif
        ; // NOLINT(whitespace/semicolon)
  }
References v8::internal::compiler::turboshaft::Get(), and v8::internal::compiler::turboshaft::Operation::Is().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsCompressed().
IsCommutative()
bool v8::internal::compiler::InstructionSelector::IsCommutative (turboshaft::OpIndex node) const
Definition at line 1402 of file instruction-selector.cc.
                                                                    {
  const turboshaft::Operation& op = Get(node);
  if (const auto word_binop = op.TryCast<turboshaft::WordBinopOp>()) {
    return turboshaft::WordBinopOp::IsCommutative(word_binop->kind);
  } else if (const auto overflow_binop =
                 op.TryCast<turboshaft::OverflowCheckedBinopOp>()) {
    return turboshaft::OverflowCheckedBinopOp::IsCommutative(
        overflow_binop->kind);
  } else if (const auto float_binop = op.TryCast<turboshaft::FloatBinopOp>()) {
    return !ensure_deterministic_nan_ &&
           turboshaft::FloatBinopOp::IsCommutative(float_binop->kind);
  } else if (const auto comparison = op.TryCast<turboshaft::ComparisonOp>()) {
    return turboshaft::ComparisonOp::IsCommutative(comparison->kind);
  }
  return false;
}
References ensure_deterministic_nan_, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::WordBinopOp::IsCommutative(), v8::internal::compiler::turboshaft::FloatBinopOp::IsCommutative(), v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::IsCommutative(), v8::internal::compiler::turboshaft::ComparisonOp::IsCommutative(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitBinop(), v8::internal::compiler::VisitBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitWordCompare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWordCompare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::VisitWordCompare().
IsDefined()
bool v8::internal::compiler::InstructionSelector::IsDefined (turboshaft::OpIndex node) const
Definition at line 532 of file instruction-selector.cc.
                                                      {
  DCHECK(node.valid());
  return defined_.Contains(node.id());
}
References v8::internal::BitVector::Contains(), v8::internal::DCHECK(), defined_, v8::internal::compiler::turboshaft::OpIndex::id(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by CanDoBranchIfOverflowFusion(), TryPrepareScheduleFirstProjection(), and VisitBlock().
IsExternalConstant()
bool v8::internal::compiler::InstructionSelector::IsExternalConstant (turboshaft::OpIndex node) const [inline]
Definition at line 727 of file instruction-selector.h.
                                                        {
    const turboshaft::ConstantOp* constant =
        TryCast<turboshaft::ConstantOp>(node);
    if (constant == nullptr) return false;
    return constant->kind == turboshaft::ConstantOp::Kind::kExternal;
  }
References v8::internal::compiler::turboshaft::ConstantOp::kExternal, and v8::internal::compiler::turboshaft::ConstantOp::kind.
Referenced by InitializeCallBuffer().
IsHeapConstant()
bool v8::internal::compiler::InstructionSelector::IsHeapConstant (turboshaft::OpIndex node) const [inline]
Definition at line 721 of file instruction-selector.h.
                                                    {
    const turboshaft::ConstantOp* constant =
        TryCast<turboshaft::ConstantOp>(node);
    if (constant == nullptr) return false;
    return constant->kind == turboshaft::ConstantOp::Kind::kHeapObject;
  }
References v8::internal::compiler::turboshaft::ConstantOp::kHeapObject, and v8::internal::compiler::turboshaft::ConstantOp::kind.
Referenced by InitializeCallBuffer().
IsLive()
bool v8::internal::compiler::InstructionSelector::IsLive (turboshaft::OpIndex node) const [inline]
Definition at line 604 of file instruction-selector.h.
                                            {
    return !IsDefined(node) && IsUsed(node);
  }
References v8::internal::anonymous_namespace{protectors.cc}::IsDefined().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMulHigh().
IsLoadOrLoadImmutable()
bool v8::internal::compiler::InstructionSelector::IsLoadOrLoadImmutable (turboshaft::OpIndex node) const [inline]
Definition at line 742 of file instruction-selector.h.
                                                           {
    return Get(node).opcode == turboshaft::Opcode::kLoad;
  }
References v8::internal::compiler::turboshaft::Get(), and v8::internal::compiler::turboshaft::Operation::opcode.
Referenced by IsProtectedLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitCompareWithMemoryOperand(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareWithMemoryOperand().
IsLoopHeader()
bool v8::internal::compiler::InstructionSelector::IsLoopHeader (const turboshaft::Block * block) const [inline]
Definition at line 701 of file instruction-selector.h.
                                                        {
    return block->IsLoop();
  }
References v8::internal::compiler::turboshaft::Block::IsLoop().
Referenced by SelectInstructions().
isolate()
Isolate* v8::internal::compiler::InstructionSelector::isolate () const [inline]
Definition at line 630 of file instruction-selector.h.
{ return sequence()->isolate(); }
References v8::internal::Factory::isolate().
Referenced by v8::internal::compiler::AddOperandToStateValueDescriptor(), CanAddressRelativeToRootsRegister(), v8::internal::compiler::CanBeImmediate(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord32EqualImpl(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitWord64EqualImpl().
IsOnlyUserOfNodeInSameBlock()
bool v8::internal::compiler::InstructionSelector::IsOnlyUserOfNodeInSameBlock (turboshaft::OpIndex user, turboshaft::OpIndex node) const
Definition at line 405 of file instruction-selector.cc.
                                                                          {
  Block* bb_user = this->block(schedule(), user);
  Block* bb_node = this->block(schedule(), node);
  if (bb_user != bb_node) return false;
  const Operation& node_op = this->turboshaft_graph()->Get(node);
  if (node_op.saturated_use_count.Get() == 1) return true;
  for (OpIndex use : turboshaft_uses(node)) {
    if (use == user) continue;
    if (this->block(schedule(), use) == bb_user) return false;
  }
    return true;
}
References block(), v8::internal::compiler::turboshaft::SaturatedUint8::Get(), v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::turboshaft::Operation::saturated_use_count, schedule(), turboshaft_graph(), turboshaft_uses(), and use().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::MaybeReplaceCmpZeroWithFlagSettingBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::MaybeReplaceCmpZeroWithFlagSettingBinop(), and v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero().
IsProtectedLoad()
bool v8::internal::compiler::InstructionSelector::IsProtectedLoad (turboshaft::OpIndex node) const
Definition at line 1053 of file instruction-selector.cc.
                                                                      {
#if V8_ENABLE_WEBASSEMBLY
  if (Get(node).opcode == turboshaft::Opcode::kSimd128LoadTransform) {
    return true;
  }
#if V8_ENABLE_WASM_SIMD256_REVEC
  if (Get(node).opcode == turboshaft::Opcode::kSimd256LoadTransform) {
    return true;
  }
#endif // V8_ENABLE_WASM_SIMD256_REVEC
#endif // V8_ENABLE_WEBASSEMBLY
  if (!IsLoadOrLoadImmutable(node)) return false;
  bool traps_on_null;
  return LoadView(schedule_, node).is_protected(&traps_on_null);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::InstructionSelector::LoadView::is_protected(), IsLoadOrLoadImmutable(), and schedule_.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop().
IsReallyLive()
bool v8::internal::compiler::InstructionSelector::IsReallyLive (turboshaft::OpIndex node) const [inline]
Definition at line 609 of file instruction-selector.h.
                                                  {
    return !IsDefined(node) && IsReallyUsed(node);
  }
References v8::internal::anonymous_namespace{protectors.cc}::IsDefined().
IsReallyUsed()
bool v8::internal::compiler::InstructionSelector::IsReallyUsed (turboshaft::OpIndex node) const
Definition at line 551 of file instruction-selector.cc.
                                                         {
  DCHECK(node.valid());
  if (!ShouldSkipOptimizationStep() && ShouldSkipOperation(this->Get(node))) {
    return false;
  }
  return used_.Contains(node.id());
}
References v8::internal::BitVector::Contains(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::ShouldSkipOperation(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), used_, and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by VisitBlock().
IsRelocatableWasmConstant()
bool v8::internal::compiler::InstructionSelector::IsRelocatableWasmConstant (turboshaft::OpIndex node) const [inline]
Definition at line 733 of file instruction-selector.h.
                                                               {
    const turboshaft::ConstantOp* constant =
        TryCast<turboshaft::ConstantOp>(node);
    if (constant == nullptr) return false;
    return constant->kind ==
           turboshaft::any_of(
               turboshaft::ConstantOp::Kind::kRelocatableWasmCall,
               turboshaft::ConstantOp::Kind::kRelocatableWasmStubCall);
  }
References v8::internal::compiler::turboshaft::any_of(), v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::ConstantOp::kRelocatableWasmCall, and v8::internal::compiler::turboshaft::ConstantOp::kRelocatableWasmStubCall.
Referenced by InitializeCallBuffer(), VisitCall(), and VisitTailCall().
IsRetain()
bool v8::internal::compiler::InstructionSelector::IsRetain (turboshaft::OpIndex node) const [inline]
Definition at line 718 of file instruction-selector.h.
                                              {
    return Get(node).Is<turboshaft::RetainOp>();
  }
References v8::internal::compiler::turboshaft::Get(), and v8::internal::compiler::turboshaft::Operation::Is().
IsSourcePositionUsed()
bool v8::internal::compiler::InstructionSelector::IsSourcePositionUsed (turboshaft::OpIndex node) [private]
Definition at line 1356 of file instruction-selector.cc.
                                                           {
  if (source_position_mode_ == InstructionSelector::kAllSourcePositions) {
    return true;
  }
  const Operation& operation = this->Get(node);
  // DidntThrow is where the actual call is generated.
  if (operation.Is<DidntThrowOp>()) return true;
  if (const LoadOp* load = operation.TryCast<LoadOp>()) {
    return load->kind.with_trap_handler;
  }
    if (const StoreOp* store = operation.TryCast<StoreOp>()) {
      return store->kind.with_trap_handler;
    }
#if V8_ENABLE_WEBASSEMBLY
    if (operation.Is<TrapIfOp>()) return true;
    if (const AtomicRMWOp* rmw = operation.TryCast<AtomicRMWOp>()) {
      return rmw->memory_access_kind ==
             MemoryAccessKind::kProtectedByTrapHandler;
    }
    if (const Simd128LoadTransformOp* lt =
            operation.TryCast<Simd128LoadTransformOp>()) {
      return lt->load_kind.with_trap_handler;
    }
#if V8_ENABLE_WASM_SIMD256_REVEC
    if (const Simd256LoadTransformOp* lt =
            operation.TryCast<Simd256LoadTransformOp>()) {
      return lt->load_kind.with_trap_handler;
    }
#endif // V8_ENABLE_WASM_SIMD256_REVEC
    if (const Simd128LaneMemoryOp* lm =
            operation.TryCast<Simd128LaneMemoryOp>()) {
      return lm->kind.with_trap_handler;
    }
#if V8_ENABLE_WASM_DEINTERLEAVED_MEM_OPS
    if (const Simd128LoadPairDeinterleaveOp* dl =
            operation.TryCast<Simd128LoadPairDeinterleaveOp>()) {
      return dl->load_kind.with_trap_handler;
    }
#endif // V8_ENABLE_WASM_DEINTERLEAVED_MEM_OPS
#endif
    if (additional_protected_instructions_->Contains(node.id())) {
      return true;
    }
    return false;
}
References additional_protected_instructions_, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::Operation::Is(), kAllSourcePositions, v8::internal::compiler::kProtectedByTrapHandler, v8::internal::lt, source_position_mode_, store(), and v8::internal::compiler::turboshaft::Operation::TryCast().
Referenced by VisitBlock().
IsSupported()
bool v8::internal::compiler::InstructionSelector::IsSupported (CpuFeature feature) const [inline]
Definition at line 540 of file instruction-selector.h.
                                             {
    return features_.Contains(feature);
  }
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitDiv(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloat32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloat64Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitFloatUnop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatUnop(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitMinOrMax(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitMod(), and v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::VisitRROFloat().
IsTailCallAddressImmediate()
bool v8::internal::compiler::InstructionSelector::IsTailCallAddressImmediate () [private]
Definition at line 1906 of file instruction-selector-arm.cc.
{ return false; }
Referenced by VisitTailCall().
IsUsed()
bool v8::internal::compiler::InstructionSelector::IsUsed (turboshaft::OpIndex node) const
Definition at line 542 of file instruction-selector.cc.
                                                   {
  DCHECK(node.valid());
  if (!ShouldSkipOptimizationStep() && ShouldSkipOperation(this->Get(node))) {
    return false;
  }
  if (Get(node).IsRequiredWhenUnused()) return true;
  return used_.Contains(node.id());
}
References v8::internal::BitVector::Contains(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::ShouldSkipOperation(), v8::internal::compiler::turboshaft::ShouldSkipOptimizationStep(), used_, and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by VisitBlock().
linkage()
Linkage* v8::internal::compiler::InstructionSelector::linkage () const [inline], [private]
Definition at line 1504 of file instruction-selector.h.
{ return linkage_; }
Referenced by CanUseRootsRegister(), ForTurboshaft(), VisitNode(), VisitOsrValue(), VisitParameter(), VisitReturn(), and VisitTailCall().
load_view()
LoadView v8::internal::compiler::InstructionSelector::load_view (turboshaft::OpIndex node) [inline]
Definition at line 902 of file instruction-selector.h.
                                             {
    DCHECK(is_load(node));
    return LoadView(schedule_, node);
  }
References v8::internal::DCHECK().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::GenerateRightOperands(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::IsCompressed(), v8::internal::compiler::anonymous_namespace{instruction-selector-ia32.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::MachineTypeForNarrow(), v8::internal::compiler::anonymous_namespace{instruction-selector-s390.cc}::ProduceWord32Result(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicLoad(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicLoad(), and v8::internal::compiler::VisitLoadCommon().
MarkAsCompressed()
void v8::internal::compiler::InstructionSelector::MarkAsCompressed (turboshaft::OpIndex node) [inline], [private]
Definition at line 1082 of file instruction-selector.h.
                                                {
    MarkAsRepresentation(MachineRepresentation::kCompressed, node);
  }
References v8::internal::kCompressed.
Referenced by VisitNode().
MarkAsDefined()
void v8::internal::compiler::InstructionSelector::MarkAsDefined (turboshaft::OpIndex node) [private]
Definition at line 537 of file instruction-selector.cc.
                                                    {
  DCHECK(node.valid());
  defined_.Add(node.id());
}
References v8::internal::BitVector::Add(), v8::internal::DCHECK(), defined_, v8::internal::compiler::turboshaft::OpIndex::id(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by v8::internal::compiler::OperandGenerator::Define(), v8::internal::compiler::OperandGenerator::DefineAsConstant(), EmitIdentity(), and VisitBlock().
MarkAsFloat32()
void v8::internal::compiler::InstructionSelector::MarkAsFloat32 (turboshaft::OpIndex node) [inline], [private]
Definition at line 1067 of file instruction-selector.h.
                                             {
    MarkAsRepresentation(MachineRepresentation::kFloat32, node);
  }
References v8::internal::kFloat32.
Referenced by VisitNode().
MarkAsFloat64()
void v8::internal::compiler::InstructionSelector::MarkAsFloat64 (turboshaft::OpIndex node) [inline], [private]
Definition at line 1070 of file instruction-selector.h.
                                             {
    MarkAsRepresentation(MachineRepresentation::kFloat64, node);
  }
References v8::internal::kFloat64.
Referenced by VisitNode().
MarkAsProtected()
void v8::internal::compiler::InstructionSelector::MarkAsProtected (turboshaft::OpIndex node) [inline]
Definition at line 673 of file instruction-selector.h.
                                               {
    additional_protected_instructions_->Add(node.id());
  }
References v8::internal::compiler::turboshaft::OpIndex::id().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop().
MarkAsRepresentation() [1/3]
void v8::internal::compiler::InstructionSelector::MarkAsRepresentation (MachineRepresentation rep, const InstructionOperand & op) [private]
Definition at line 611 of file instruction-selector.cc.
                                                                             {
  UnallocatedOperand unalloc = UnallocatedOperand::cast(op);
  sequence()->MarkAsRepresentation(rep, unalloc.virtual_register());
}
References v8::internal::compiler::InstructionSequence::MarkAsRepresentation(), v8::internal::compiler::turboshaft::OperationMatcher::rep, sequence(), and v8::internal::compiler::UnallocatedOperand::virtual_register().
MarkAsRepresentation() [2/3]
void v8::internal::compiler::InstructionSelector::MarkAsRepresentation (MachineRepresentation rep, turboshaft::OpIndex node) [private]
Definition at line 617 of file instruction-selector.cc.
                                                             {
  sequence()->MarkAsRepresentation(rep, GetVirtualRegister(node));
}
References GetVirtualRegister(), v8::internal::compiler::InstructionSequence::MarkAsRepresentation(), v8::internal::compiler::turboshaft::OperationMatcher::rep, and sequence().
Referenced by InitializeCallBuffer(), and VisitNode().
MarkAsRepresentation() [3/3]
void v8::internal::compiler::InstructionSelector::MarkAsRepresentation (turboshaft::RegisterRepresentation rep, turboshaft::OpIndex node) [inline], [private]
Definition at line 1057 of file instruction-selector.h.
                                                    {
    MarkAsRepresentation(rep.machine_representation(), node);
  }
References v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::machine_representation().
MarkAsSimd128()
void v8::internal::compiler::InstructionSelector::MarkAsSimd128 (turboshaft::OpIndex node) [inline], [private]
Definition at line 1073 of file instruction-selector.h.
                                             {
    MarkAsRepresentation(MachineRepresentation::kSimd128, node);
  }
References v8::internal::kSimd128.
Referenced by VisitNode().
MarkAsSimd256()
void v8::internal::compiler::InstructionSelector::MarkAsSimd256 (turboshaft::OpIndex node) [inline], [private]
Definition at line 1076 of file instruction-selector.h.
                                             {
    MarkAsRepresentation(MachineRepresentation::kSimd256, node);
  }
References v8::internal::kSimd256.
Referenced by VisitNode().
MarkAsTableSwitchTarget()
void v8::internal::compiler::InstructionSelector::MarkAsTableSwitchTarget (const turboshaft::Block * block) [private]
Definition at line 1715 of file instruction-selector.cc.
                                  {
  sequence()
      ->InstructionBlockAt(this->rpo_number(block))
      ->set_table_switch_target(true);
}
References v8::internal::compiler::InstructionSequence::InstructionBlockAt(), rpo_number(), sequence(), and v8::internal::compiler::InstructionBlock::set_table_switch_target().
Referenced by EmitTableSwitch().
MarkAsTagged()
void v8::internal::compiler::InstructionSelector::MarkAsTagged (turboshaft::OpIndex node) [inline], [private]
Definition at line 1079 of file instruction-selector.h.
                                            {
    MarkAsRepresentation(MachineRepresentation::kTagged, node);
  }
References v8::internal::kTagged.
Referenced by VisitNode().
MarkAsUsed()
void v8::internal::compiler::InstructionSelector::MarkAsUsed (turboshaft::OpIndex node) [private]
Definition at line 559 of file instruction-selector.cc.
                                                 {
  DCHECK(node.valid());
  used_.Add(node.id());
}
References v8::internal::BitVector::Add(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::OpIndex::id(), used_, and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by EmitIdentity(), SelectInstructions(), v8::internal::compiler::OperandGenerator::Use(), VisitPhi(), and VisitProjection().
MarkAsWord32()
void v8::internal::compiler::InstructionSelector::MarkAsWord32 (turboshaft::OpIndex node) [inline], [private]
Definition at line 1061 of file instruction-selector.h.
                                            {
    MarkAsRepresentation(MachineRepresentation::kWord32, node);
  }
References v8::internal::kWord32.
Referenced by MarkPairProjectionsAsWord32(), and VisitNode().
MarkAsWord64()
void v8::internal::compiler::InstructionSelector::MarkAsWord64 (turboshaft::OpIndex node) [inline], [private]
Definition at line 1064 of file instruction-selector.h.
                                            {
    MarkAsRepresentation(MachineRepresentation::kWord64, node);
  }
References v8::internal::kWord64.
Referenced by VisitNode().
MarkPairProjectionsAsWord32()
void v8::internal::compiler::InstructionSelector::MarkPairProjectionsAsWord32 (turboshaft::OpIndex node) [private]
Definition at line 1557 of file instruction-selector.cc.
                                                                  {
  OptionalOpIndex projection0 = FindProjection(node, 0);
  if (projection0.valid()) {
    MarkAsWord32(projection0.value());
  }
  OptionalOpIndex projection1 = FindProjection(node, 1);
  if (projection1.valid()) {
    MarkAsWord32(projection1.value());
  }
}
References FindProjection(), MarkAsWord32(), v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), and v8::internal::compiler::turboshaft::OptionalOpIndex::value().
Referenced by VisitNode().
nodes()
base::iterator_range<turboshaft::Graph::OpIndexIterator> v8::internal::compiler::InstructionSelector::nodes (const turboshaft::Block * block) [inline]
Definition at line 713 of file instruction-selector.h.
                                    {
    return schedule_->OperationIndices(*block);
  }
Referenced by SelectInstructions(), and VisitBlock().
PredecessorAt()
turboshaft::Block* v8::internal::compiler::InstructionSelector::PredecessorAt (const turboshaft::Block * block, size_t index) const [inline]
Definition at line 708 of file instruction-selector.h.
                                                       {
    return block->Predecessors()[index];
  }
References v8::internal::index, and v8::internal::compiler::turboshaft::Block::Predecessors().
Referenced by GetEffectLevel().
PredecessorCount()
size_t v8::internal::compiler::InstructionSelector::PredecessorCount (const turboshaft::Block * block) const [inline]
Definition at line 705 of file instruction-selector.h.
                                                              {
    return block->PredecessorCount();
  }
References v8::internal::compiler::turboshaft::Block::PredecessorCount().
Referenced by SelectInstructions(), and VisitPhi().
rpo_number()
RpoNumber v8::internal::compiler::InstructionSelector::rpo_number (const turboshaft::Block * block) const [inline]
Definition at line 693 of file instruction-selector.h.
                                                           {
    return RpoNumber::FromInt(block->index().id());
  }
References v8::internal::compiler::RpoNumber::FromInt(), v8::internal::compiler::turboshaft::BlockIndex::id(), and v8::internal::compiler::turboshaft::Block::index().
Referenced by v8::internal::compiler::OperandGenerator::Label(), MarkAsTableSwitchTarget(), SelectInstructions(), VisitBlock(), VisitNode(), and VisitPhi().
rpo_order()
const ZoneVector<turboshaft::Block*>& v8::internal::compiler::InstructionSelector::rpo_order (turboshaft::Graph * schedule) [inline]
Definition at line 697 of file instruction-selector.h.
                                                                           {
    return schedule->blocks_vector();
  }
References v8::internal::compiler::turboshaft::Graph::blocks_vector().
Referenced by SelectInstructions().
schedule()
turboshaft::Graph* v8::internal::compiler::InstructionSelector::schedule () const [inline], [private]
Definition at line 1503 of file instruction-selector.h.
{ return schedule_; }
Referenced by AddInputsToFrameStateDescriptor(), CanCover(), IsOnlyUserOfNodeInSameBlock(), SelectInstructions(), VisitControl(), VisitNode(), and VisitReturn().
SelectInstructions()
std::optional< BailoutReason > v8::internal::compiler::InstructionSelector::SelectInstructions ()
Definition at line 118 of file instruction-selector.cc.
                                                                   {
  // Mark the inputs of all phis in loop headers as used.
  ZoneVector<Block*> blocks = rpo_order(schedule());
  for (const Block* block : blocks) {
    if (!IsLoopHeader(block)) continue;
    DCHECK_LE(2u, PredecessorCount(block));
    for (OpIndex node : nodes(block)) {
      const PhiOp* phi = TryCast<PhiOp>(node);
      if (!phi) continue;
      // Mark all inputs as used.
      for (OpIndex input : phi->inputs()) {
        MarkAsUsed(input);
      }
    }
  }
  // Visit each basic block in post order.
  for (auto i = blocks.rbegin(); i != blocks.rend(); ++i) {
    VisitBlock(*i);
    if (instruction_selection_failed())
      return BailoutReason::kTurbofanCodeGenerationFailed;
  }
  // Schedule the selected instructions.
  if (UseInstructionScheduling()) {
    scheduler_ = zone()->template New<InstructionScheduler>(zone(), sequence());
  }
  for (const Block* block : blocks) {
    InstructionBlock* instruction_block =
        sequence()->InstructionBlockAt(this->rpo_number(block));
    for (size_t i = 0; i < instruction_block->phis().size(); i++) {
      UpdateRenamesInPhi(instruction_block->PhiAt(i));
    }
    size_t end = instruction_block->code_end();
    size_t start = instruction_block->code_start();
    DCHECK_LE(end, start);
    StartBlock(this->rpo_number(block));
    if (end != start) {
      while (start-- > end + 1) {
        UpdateRenames(instructions_[start]);
        AddInstruction(instructions_[start]);
      }
      UpdateRenames(instructions_[end]);
      AddTerminator(instructions_[end]);
    }
    EndBlock(this->rpo_number(block));
  }
#if DEBUG
  sequence()->ValidateSSA();
#endif
  return std::nullopt;
}
References AddInstruction(), AddTerminator(), block(), v8::internal::compiler::InstructionBlock::code_end(), v8::internal::compiler::InstructionBlock::code_start(), DCHECK_LE, v8::internal::compiler::end(), EndBlock(), v8::internal::compiler::turboshaft::OperationT< Derived >::inputs(), instruction_selection_failed(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), instructions_, IsLoopHeader(), MarkAsUsed(), nodes(), v8::internal::compiler::InstructionBlock::PhiAt(), v8::internal::compiler::InstructionBlock::phis(), PredecessorCount(), v8::internal::ZoneVector< T >::rbegin(), v8::internal::ZoneVector< T >::rend(), rpo_number(), rpo_order(), schedule(), scheduler_, sequence(), size(), StartBlock(), UpdateRenames(), UpdateRenamesInPhi(), UseInstructionScheduling(), v8::internal::compiler::InstructionSequence::ValidateSSA(), VisitBlock(), and zone().
Referenced by v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run().
sequence()
InstructionSequence* v8::internal::compiler::InstructionSelector::sequence () const [inline], [private]
Definition at line 1505 of file instruction-selector.h.
{ return sequence_; }
Referenced by AddInstruction(), AddTerminator(), AppendDeoptimizeArguments(), EndBlock(), ForTurboshaft(), GetVirtualRegister(), InitializeCallBuffer(), MarkAsRepresentation(), MarkAsTableSwitchTarget(), SelectInstructions(), v8::internal::compiler::OperandGenerator::sequence(), StartBlock(), UpdateSourcePosition(), VisitBlock(), and VisitPhi().
set_instruction_selection_failed()
void v8::internal::compiler::InstructionSelector::set_instruction_selection_failed () [inline], [private]
Definition at line 1514 of file instruction-selector.h.
                                          {
    instruction_selection_failed_ = true;
  }
Referenced by Emit().
SetEffectLevel()
void v8::internal::compiler::InstructionSelector::SetEffectLevel (turboshaft::OpIndex node, int effect_level) [private]
Definition at line 578 of file instruction-selector.cc.
                                                                       {
  DCHECK(node.valid());
  size_t const id = node.id();
  DCHECK_LT(id, effect_level_.size());
  effect_level_[id] = effect_level;
}
References v8::internal::DCHECK(), DCHECK_LT, effect_level_, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::ZoneVector< T >::size(), and v8::internal::compiler::turboshaft::OpIndex::valid().
Referenced by VisitBlock().
SetProtectedLoadToRemove()
void v8::internal::compiler::InstructionSelector::SetProtectedLoadToRemove (turboshaft::OpIndex node) [inline]
Definition at line 665 of file instruction-selector.h.
                                                        {
    DCHECK(this->IsProtectedLoad(node));
    protected_loads_to_remove_->Add(node.id());
  }
References v8::internal::DCHECK(), and v8::internal::compiler::turboshaft::OpIndex::id().
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop().
SetRename()
void v8::internal::compiler::InstructionSelector::SetRename (turboshaft::OpIndex node, turboshaft::OpIndex rename) [private]
Definition at line 499 of file instruction-selector.cc.
                                                                {
  int vreg = GetVirtualRegister(node);
  if (static_cast<size_t>(vreg) >= virtual_register_rename_.size()) {
    int invalid = InstructionOperand::kInvalidVirtualRegister;
    virtual_register_rename_.resize(vreg + 1, invalid);
  }
  virtual_register_rename_[vreg] = GetVirtualRegister(rename);
}
References GetVirtualRegister(), v8::internal::compiler::InstructionOperand::kInvalidVirtualRegister, v8::internal::ZoneVector< T >::resize(), v8::internal::ZoneVector< T >::size(), and virtual_register_rename_.
Referenced by EmitIdentity().
StartBlock()
void v8::internal::compiler::InstructionSelector::StartBlock (RpoNumber rpo)
Definition at line 173 of file instruction-selector.cc.
                                                  {
  if (UseInstructionScheduling()) {
    DCHECK_NOT_NULL(scheduler_);
    scheduler_->StartBlock(rpo);
  } else {
    sequence()->StartBlock(rpo);
  }
}
References DCHECK_NOT_NULL, scheduler_, sequence(), v8::internal::compiler::InstructionScheduler::StartBlock(), v8::internal::compiler::InstructionSequence::StartBlock(), and UseInstructionScheduling().
Referenced by SelectInstructions().
store_view()
StoreView v8::internal::compiler::InstructionSelector::store_view (turboshaft::OpIndex node) [inline]
Definition at line 967 of file instruction-selector.h.
                                               {
    return StoreView(schedule_, node);
  }
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::AtomicStoreParametersOf(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::AtomicStoreParametersOf(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::AtomicStoreParametersOf(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::AtomicStoreParametersOf(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv32.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitAtomicStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitAtomicStore(), v8::internal::compiler::VisitGeneralStore(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::VisitStoreCommon(), and v8::internal::compiler::VisitStoreCommon().
SupportedFeatures()
static Features v8::internal::compiler::InstructionSelector::SupportedFeatures () [inline], [static]
Definition at line 545 of file instruction-selector.h.
                                      {
    return Features(CpuFeatures::SupportedFeatures());
  }
References v8::internal::CpuFeatures::SupportedFeatures().
Referenced by v8::internal::compiler::turboshaft::InstructionSelectionPhase::Run().
SupportedMachineOperatorFlags()
MachineOperatorBuilder::Flags v8::internal::compiler::InstructionSelector::SupportedMachineOperatorFlags () [static]
Definition at line 3535 of file instruction-selector-arm.cc.
                                                   {
  MachineOperatorBuilder::Flags flags = MachineOperatorBuilder::kNoFlags;
  if (CpuFeatures::IsSupported(SUDIV)) {
    // The sdiv and udiv instructions correctly return 0 if the divisor is 0,
    // but the fall-back implementation does not.
    flags |= MachineOperatorBuilder::kInt32DivIsSafe |
             MachineOperatorBuilder::kUint32DivIsSafe;
  }
  if (CpuFeatures::IsSupported(ARMv7)) {
    flags |= MachineOperatorBuilder::kWord32ReverseBits;
  }
  if (CpuFeatures::IsSupported(ARMv8)) {
    flags |= MachineOperatorBuilder::kFloat32RoundDown |
             MachineOperatorBuilder::kFloat64RoundDown |
             MachineOperatorBuilder::kFloat32RoundUp |
             MachineOperatorBuilder::kFloat64RoundUp |
             MachineOperatorBuilder::kFloat32RoundTruncate |
             MachineOperatorBuilder::kFloat64RoundTruncate |
             MachineOperatorBuilder::kFloat64RoundTiesAway |
             MachineOperatorBuilder::kFloat32RoundTiesEven |
             MachineOperatorBuilder::kFloat64RoundTiesEven;
  }
  flags |= MachineOperatorBuilder::kSatConversionIsSafe;
  return flags;
}
References v8::internal::flags, v8::internal::CpuFeatures::IsSupported(), v8::internal::compiler::MachineOperatorBuilder::kFloat32RoundDown, v8::internal::compiler::MachineOperatorBuilder::kFloat32RoundTiesEven, v8::internal::compiler::MachineOperatorBuilder::kFloat32RoundTruncate, v8::internal::compiler::MachineOperatorBuilder::kFloat32RoundUp, v8::internal::compiler::MachineOperatorBuilder::kFloat64RoundDown, v8::internal::compiler::MachineOperatorBuilder::kFloat64RoundTiesAway, v8::internal::compiler::MachineOperatorBuilder::kFloat64RoundTiesEven, v8::internal::compiler::MachineOperatorBuilder::kFloat64RoundTruncate, v8::internal::compiler::MachineOperatorBuilder::kFloat64RoundUp, v8::internal::compiler::MachineOperatorBuilder::kInt32DivIsSafe, v8::internal::compiler::MachineOperatorBuilder::kNoFlags, v8::internal::compiler::MachineOperatorBuilder::kSatConversionIsSafe, v8::internal::compiler::MachineOperatorBuilder::kUint32DivIsSafe, and v8::internal::compiler::MachineOperatorBuilder::kWord32ReverseBits.
Referenced by v8::internal::compiler::turboshaft::SupportedOperations::Initialize(), v8::internal::compiler::TFPipelineData::InitializeWithGraphZone(), and v8::internal::compiler::TFPipelineData::TFPipelineData().
TryPrepareScheduleFirstProjection()
void v8::internal::compiler::InstructionSelector::TryPrepareScheduleFirstProjection (turboshaft::OpIndex maybe_projection) [private]
Definition at line 2441 of file instruction-selector.cc.
                              {
  // The DeoptimizeIf/Branch condition is not a projection.
  const ProjectionOp* projection = TryCast<ProjectionOp>(maybe_projection);
  if (!projection) return;
  if (projection->index != 1u) {
    // The DeoptimizeIf/Branch isn't on the Projection[1]
    // (ie, not on the overflow bit of a BinopOverflow).
    return;
  }
  DCHECK_EQ(projection->input_count, 1);
  OpIndex node = projection->input();
  if (block(schedule_, node) != current_block_) {
    // The projection input is not in the current block, so it shouldn't be
    // emitted now, so we don't need to eagerly schedule its Projection[0].
    return;
  }
  auto* binop = TryCast<OverflowCheckedBinopOp>(node);
  auto* unop = TryCast<OverflowCheckedUnaryOp>(node);
  if (binop == nullptr && unop == nullptr) return;
  if (binop) {
    DCHECK(binop->kind == OverflowCheckedBinopOp::Kind::kSignedAdd ||
           binop->kind == OverflowCheckedBinopOp::Kind::kSignedSub ||
           binop->kind == OverflowCheckedBinopOp::Kind::kSignedMul);
  } else {
    DCHECK_EQ(unop->kind, OverflowCheckedUnaryOp::Kind::kAbs);
  }
  OptionalOpIndex result = FindProjection(node, 0);
  if (!result.valid() || IsDefined(result.value())) {
    // No Projection(0), or it's already defined.
    return;
  }
  if (block(schedule_, result.value()) != current_block_) {
    // {result} wasn't planned to be scheduled in {current_block_}. To
    // avoid adding checks to see if it can still be scheduled now, we
    // just bail out.
    return;
  }
  // Checking if all uses of {result} that are in the current block have
  // already been Defined.
  // We also ignore Phi uses: if {result} is used in a Phi in the block in
  // which it is defined, this means that this block is a loop header, and
  // {result} back into it through the back edge. In this case, it's
  // normal to schedule {result} before the Phi that uses it.
  for (OpIndex use : turboshaft_uses(result.value())) {
    // We ignore TupleOp uses, since TupleOp don't lead to emitted machine
    // instructions and are just Turboshaft "meta operations".
    if (!Is<TupleOp>(use) && !IsDefined(use) &&
        block(schedule_, use) == current_block_ && !Is<PhiOp>(use)) {
      return;
    }
  }
  // Visiting the projection now. Note that this relies on the fact that
  // VisitProjection doesn't Emit something: if it did, then we could be
  // Emitting something after a Branch, which is invalid (Branch can only
  // be at the end of a block, and the end of a block must always be a
  // block terminator). (remember that we emit operation in reverse order,
  // so because we are doing TryPrepareScheduleFirstProjection before
  // actually emitting the Branch, it would be after in the final
  // instruction sequence, not before)
  VisitProjection(result.value());
}
References block(), current_block_, v8::internal::DCHECK(), DCHECK_EQ, FindProjection(), v8::internal::compiler::turboshaft::ProjectionOp::index, v8::internal::compiler::turboshaft::ProjectionOp::input(), v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::input_count, IsDefined(), v8::base::internal::result, schedule_, turboshaft_uses(), use(), and VisitProjection().
Referenced by VisitBranch(), and VisitDeoptimizeIf().
TryRename()
void v8::internal::compiler::InstructionSelector::TryRename (InstructionOperand * op) [private]
Definition at line 489 of file instruction-selector.cc.
                                                          {
  if (!op->IsUnallocated()) return;
  UnallocatedOperand* unalloc = UnallocatedOperand::cast(op);
  int vreg = unalloc->virtual_register();
  int rename = GetRename(vreg);
  if (rename != vreg) {
    *unalloc = UnallocatedOperand(*unalloc, rename);
  }
}
References GetRename(), and v8::internal::compiler::UnallocatedOperand::virtual_register().
Referenced by UpdateRenames().
turboshaft_graph()
turboshaft::Graph* v8::internal::compiler::InstructionSelector::turboshaft_graph () const [inline]
Definition at line 684 of file instruction-selector.h.
{ return schedule_; }
Referenced by CanCoverProtectedLoad(), CanDoBranchIfOverflowFusion(), FindProjection(), GetFrameStateDescriptor(), IsOnlyUserOfNodeInSameBlock(), v8::internal::compiler::OperandGenerator::turboshaft_graph(), v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitCompareZero(), and VisitControl().
turboshaft_uses()
base::Vector<const turboshaft::OpIndex> v8::internal::compiler::InstructionSelector::turboshaft_uses (turboshaft::OpIndex node) const [inline], [private]
Definition at line 1506 of file instruction-selector.h.
                                    {
    DCHECK(turboshaft_use_map_.has_value());
    return turboshaft_use_map_->uses(node);
  }
References v8::internal::DCHECK().
Referenced by CanDoBranchIfOverflowFusion(), FindProjection(), InitializeCallBuffer(), IsOnlyUserOfNodeInSameBlock(), and TryPrepareScheduleFirstProjection().
UpdateMaxPushedArgumentCount()
void v8::internal::compiler::InstructionSelector::UpdateMaxPushedArgumentCount (size_t count) [private]
Definition at line 2142 of file instruction-selector.cc.
                                                                   {
  *max_pushed_argument_count_ = std::max(count, *max_pushed_argument_count_);
}
References max_pushed_argument_count_.
Referenced by VisitCall(), and VisitTailCall().
UpdateRenames()
void v8::internal::compiler::InstructionSelector::UpdateRenames (Instruction * instruction) [private]
Definition at line 460 of file instruction-selector.cc.
                                                                {
  for (size_t i = 0; i < instruction->InputCount(); i++) {
    TryRename(instruction->InputAt(i));
  }
}
References v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::Instruction::InputCount(), and TryRename().
Referenced by SelectInstructions().
UpdateRenamesInPhi()
void v8::internal::compiler::InstructionSelector::UpdateRenamesInPhi (PhiInstruction * phi) [private]
Definition at line 466 of file instruction-selector.cc.
                                                                {
  for (size_t i = 0; i < phi->operands().size(); i++) {
    int vreg = phi->operands()[i];
    int renamed = GetRename(vreg);
    if (vreg != renamed) {
      phi->RenameInput(i, renamed);
    }
  }
}
References GetRename(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::PhiInstruction::operands(), v8::internal::compiler::PhiInstruction::RenameInput(), and size().
Referenced by SelectInstructions().
UpdateSourcePosition()
void v8::internal::compiler::InstructionSelector::UpdateSourcePosition (Instruction * instruction, turboshaft::OpIndex node)
Definition at line 1351 of file instruction-selector.cc.
                                                             {
  sequence()->SetSourcePosition(instruction, (*source_positions_)[node]);
}
References sequence(), v8::internal::compiler::InstructionSequence::SetSourcePosition(), and source_positions_.
Referenced by v8::internal::compiler::anonymous_namespace{instruction-selector-x64.cc}::VisitFloatBinop(), v8::internal::compiler::anonymous_namespace{instruction-selector-loong64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-mips64.cc}::VisitFullWord32Compare(), v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitFullWord32Compare(), and v8::internal::compiler::anonymous_namespace{instruction-selector-riscv64.cc}::VisitOptimizedWord32Compare().
UseInstructionScheduling()
bool v8::internal::compiler::InstructionSelector::UseInstructionScheduling () const [inline], [private]
Definition at line 1020 of file instruction-selector.h.
                                        {
    return enable_scheduling_ && InstructionScheduler::SchedulerSupported();
  }
References v8::internal::compiler::InstructionScheduler::SchedulerSupported().
Referenced by AddInstruction(), AddTerminator(), EndBlock(), SelectInstructions(), and StartBlock().
VisitBitcastWord32PairToFloat64()
void v8::internal::compiler::InstructionSelector::VisitBitcastWord32PairToFloat64 (turboshaft::OpIndex node) [private]
Definition at line 2385 of file instruction-selector-arm.cc.
                                                                      {
  ArmOperandGenerator g(this);
  const BitcastWord32PairToFloat64Op& cast_op =
      this->Get(node).template Cast<BitcastWord32PairToFloat64Op>();
  Emit(kArmVmovF64U32U32, g.DefineAsRegister(node),
       g.UseRegister(cast_op.low_word32()),
       g.UseRegister(cast_op.high_word32()));
}
References v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::BitcastWord32PairToFloat64Op::high_word32(), v8::internal::compiler::turboshaft::BitcastWord32PairToFloat64Op::low_word32(), and v8::internal::compiler::OperandGenerator::UseRegister().
Referenced by VisitNode().
VisitBlock()
void v8::internal::compiler::InstructionSelector::VisitBlock (const turboshaft::Block * block) [private]
Definition at line 1438 of file instruction-selector.cc.
                                                       {
  DCHECK(!current_block_);
  current_block_ = block;
  auto current_num_instructions = [&] {
    DCHECK_GE(kMaxInt, instructions_.size());
    return static_cast<int>(instructions_.size());
  };
  int current_block_end = current_num_instructions();
  int effect_level = 0;
  for (OpIndex node : this->nodes(block)) {
    SetEffectLevel(node, effect_level);
    if (increment_effect_level_for_node(this, node)) {
      ++effect_level;
    }
  }
  // We visit the control first, then the nodes in the block, so the block's
  // control input should be on the same effect level as the last node.
  if (OpIndex terminator = this->block_terminator(block); terminator.valid()) {
    SetEffectLevel(terminator, effect_level);
    current_effect_level_ = effect_level;
  }
  auto FinishEmittedInstructions = [&](OpIndex node, int instruction_start) {
    if (instruction_selection_failed()) return false;
    if (current_num_instructions() == instruction_start) return true;
    std::reverse(instructions_.begin() + instruction_start,
                 instructions_.end());
    if (!node.valid()) return true;
    if (!source_positions_) return true;
    SourcePosition source_position;
#if V8_ENABLE_WEBASSEMBLY && V8_TARGET_ARCH_X64
    if (const Simd128UnaryOp* op =
            TryCast<Opmask::kSimd128F64x2PromoteLowF32x4>(node);
        V8_UNLIKELY(op)) {
      // On x64 there exists an optimization that folds
      // `kF64x2PromoteLowF32x4` and `kS128Load64Zero` together into a single
      // instruction. If the instruction causes an out-of-bounds memory
      // access exception, then the stack trace has to show the source
      // position of the `kS128Load64Zero` and not of the
      // `kF64x2PromoteLowF32x4`.
      if (CanOptimizeF64x2PromoteLowF32x4(node)) {
        node = op->input();
      }
    }
#endif // V8_ENABLE_WEBASSEMBLY && V8_TARGET_ARCH_X64
    source_position = (*source_positions_)[node];
    if (source_position.IsKnown() && IsSourcePositionUsed(node)) {
      sequence()->SetSourcePosition(instructions_.back(), source_position);
    }
    return true;
  };
  // Generate code for the block control "top down", but schedule the code
  // "bottom up".
  VisitControl(block);
  if (!FinishEmittedInstructions(this->block_terminator(block),
                                 current_block_end)) {
    return;
  }
  // Visit code in reverse control flow order, because architecture-specific
  // matching may cover more than one node at a time.
  for (OpIndex node : base::Reversed(this->nodes(block))) {
    int current_node_end = current_num_instructions();
    if (protected_loads_to_remove_->Contains(node.id()) &&
        !IsReallyUsed(node)) {
      MarkAsDefined(node);
    }
    if (!IsUsed(node)) {
      // Skip nodes that are unused, while marking them as Defined so that it's
      // clear that these unused nodes have been visited and will not be Defined
      // later.
      MarkAsDefined(node);
    } else if (!IsDefined(node)) {
      // Generate code for this node "top down", but schedule the code "bottom
      // up".
      current_effect_level_ = GetEffectLevel(node);
      VisitNode(node);
      if (!FinishEmittedInstructions(node, current_node_end)) return;
    }
    if (trace_turbo_) {
      instr_origins_[node.id()] = {current_num_instructions(),
                                   current_node_end};
    }
  }
  // We're done with the block.
  InstructionBlock* instruction_block =
      sequence()->InstructionBlockAt(this->rpo_number(block));
  if (current_num_instructions() == current_block_end) {
    // Avoid empty block: insert a {kArchNop} instruction.
    Emit(Instruction::New(sequence()->zone(), kArchNop));
  }
  instruction_block->set_code_start(current_num_instructions());
  instruction_block->set_code_end(current_block_end);
  current_block_ = nullptr;
}
References v8::internal::ZoneVector< T >::back(), v8::internal::ZoneVector< T >::begin(), block(), block_terminator(), current_block_, current_effect_level_, v8::internal::DCHECK(), DCHECK_GE, Emit(), v8::internal::ZoneVector< T >::end(), GetEffectLevel(), v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::increment_effect_level_for_node(), instr_origins_, instruction_selection_failed(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), instructions_, IsDefined(), v8::internal::SourcePosition::IsKnown(), IsReallyUsed(), IsSourcePositionUsed(), IsUsed(), v8::internal::kMaxInt, MarkAsDefined(), v8::internal::compiler::Instruction::New(), nodes(), protected_loads_to_remove_, v8::base::Reversed(), rpo_number(), sequence(), v8::internal::compiler::InstructionBlock::set_code_end(), v8::internal::compiler::InstructionBlock::set_code_start(), SetEffectLevel(), v8::internal::compiler::InstructionSequence::SetSourcePosition(), v8::internal::ZoneVector< T >::size(), source_positions_, trace_turbo_, V8_UNLIKELY, v8::internal::compiler::turboshaft::OpIndex::valid(), VisitControl(), VisitNode(), and zone().
Referenced by SelectInstructions().
VisitBranch()
void v8::internal::compiler::InstructionSelector::VisitBranch (turboshaft::OpIndex input, turboshaft::Block * tbranch, turboshaft::Block * fbranch) [private]
Definition at line 2404 of file instruction-selector.cc.
                                                      {
  const BranchOp& branch = Cast<BranchOp>(branch_node);
  TryPrepareScheduleFirstProjection(branch.condition());
#if V8_ENABLE_WEBASSEMBLY
  FlagsContinuation cont = FlagsContinuation::ForHintedBranch(
      kNotEqual, tbranch, fbranch, branch.hint);
#else
  FlagsContinuation cont =
      FlagsContinuation::ForBranch(kNotEqual, tbranch, fbranch);
#endif // V8_ENABLE_WEBASSEMBLY
  VisitWordCompareZero(branch_node, branch.condition(), &cont);
}
References v8::internal::compiler::turboshaft::BranchOp::condition(), v8::internal::compiler::FlagsContinuation::ForBranch(), v8::internal::compiler::FlagsContinuation::ForHintedBranch(), v8::internal::compiler::turboshaft::BranchOp::hint, v8::internal::compiler::kNotEqual, TryPrepareScheduleFirstProjection(), and VisitWordCompareZero().
Referenced by VisitControl().
VisitCall()
void v8::internal::compiler::InstructionSelector::VisitCall (turboshaft::OpIndex call, turboshaft::Block * handler = {}) [private]
Definition at line 2146 of file instruction-selector.cc.
                                                                {
  OperandGenerator g(this);
  const CallOp& call_op = Cast<CallOp>(node);
  const CallDescriptor* call_descriptor = call_op.descriptor->descriptor;
  SaveFPRegsMode mode = call_descriptor->NeedsCallerSavedFPRegisters()
                            ? SaveFPRegsMode::kSave
                            : SaveFPRegsMode::kIgnore;
  if (call_descriptor->NeedsCallerSavedRegisters()) {
    Emit(kArchSaveCallerRegisters | MiscField::encode(static_cast<int>(mode)),
         g.NoOutput());
  }
  FrameStateDescriptor* frame_state_descriptor = nullptr;
  if (call_descriptor->NeedsFrameState()) {
    frame_state_descriptor =
        GetFrameStateDescriptor(call_op.frame_state().value());
  }
  CallBuffer buffer(zone(), call_descriptor, frame_state_descriptor);
  CallDescriptor::Flags flags = call_descriptor->flags();
  // Compute InstructionOperands for inputs and outputs.
  // TODO(turbofan): on some architectures it's probably better to use
  // the code object in a register if there are multiple uses of it.
  // Improve constant pool and the heuristics in the register allocator
  // for where to emit constants.
  CallBufferFlags call_buffer_flags(kCallCodeImmediate | kCallAddressImmediate);
  if (flags & CallDescriptor::kFixedTargetRegister) {
    call_buffer_flags |= kCallFixedTargetRegister;
  }
  InitializeCallBuffer(node, &buffer, call_buffer_flags, call_op.callee(),
                       call_op.frame_state(), call_op.arguments(),
                       static_cast<int>(call_op.results_rep().size()));
  EmitPrepareArguments(&buffer.pushed_nodes, call_descriptor, node);
  UpdateMaxPushedArgumentCount(buffer.pushed_nodes.size());
  InstructionOperandVector temps(zone());
#if V8_ENABLE_WEBASSEMBLY
  if (call_descriptor->IsIndirectWasmFunctionCall()) {
    buffer.instruction_args.push_back(
        g.UseImmediate64(call_descriptor->signature_hash()));
  }
#endif
  if (call_descriptor->RequiresEntrypointTagForCall()) {
    DCHECK(!call_descriptor->IsJSFunctionCall());
    buffer.instruction_args.push_back(
        g.TempImmediate(call_descriptor->shifted_tag()));
  } else if (call_descriptor->IsJSFunctionCall()) {
    // For JSFunctions we need to know the number of pushed parameters during
    // code generation.
    uint32_t parameter_count =
        static_cast<uint32_t>(buffer.pushed_nodes.size());
    buffer.instruction_args.push_back(g.TempImmediate(parameter_count));
  }
  // Pass label of exception handler block.
  if (handler) {
    flags |= CallDescriptor::kHasExceptionHandler;
    buffer.instruction_args.push_back(g.Label(handler));
  } else {
    if (call_op.descriptor->lazy_deopt_on_throw == LazyDeoptOnThrow::kYes) {
      flags |= CallDescriptor::kHasExceptionHandler;
      buffer.instruction_args.push_back(
          g.UseImmediate(kLazyDeoptOnThrowSentinel));
    }
  }
  // Select the appropriate opcode based on the call type.
  InstructionCode opcode;
  switch (call_descriptor->kind()) {
    case CallDescriptor::kCallAddress: {
      int gp_param_count =
          static_cast<int>(call_descriptor->GPParameterCount());
      int fp_param_count =
          static_cast<int>(call_descriptor->FPParameterCount());
#if ABI_USES_FUNCTION_DESCRIPTORS
      // Highest fp_param_count bit is used on AIX to indicate if a CFunction
      // call has function descriptor or not.
      static_assert(FPParamField::kSize == kHasFunctionDescriptorBitShift + 1);
      if (!call_descriptor->NoFunctionDescriptor()) {
        fp_param_count |= 1 << kHasFunctionDescriptorBitShift;
      }
#endif
      // We store the param counts as a separate input because they need too
      // many bits to be encoded in the opcode.
      buffer.instruction_args.push_back(
          g.UseImmediate(ParamField::encode(gp_param_count) |
                         FPParamField::encode(fp_param_count)));
      opcode = EncodeCallDescriptorFlags(kArchCallCFunction, flags);
      break;
    }
    case CallDescriptor::kCallCodeObject:
      opcode = EncodeCallDescriptorFlags(kArchCallCodeObject, flags);
      break;
    case CallDescriptor::kCallJSFunction:
      opcode = EncodeCallDescriptorFlags(kArchCallJSFunction, flags);
      break;
#if V8_ENABLE_WEBASSEMBLY
    case CallDescriptor::kCallWasmCapiFunction:
    case CallDescriptor::kCallWasmFunction:
    case CallDescriptor::kCallWasmImportWrapper:
      DCHECK(this->IsRelocatableWasmConstant(call_op.callee()));
      opcode = EncodeCallDescriptorFlags(kArchCallWasmFunction, flags);
      break;
    case CallDescriptor::kCallWasmFunctionIndirect:
      DCHECK(!this->IsRelocatableWasmConstant(call_op.callee()));
      opcode = EncodeCallDescriptorFlags(kArchCallWasmFunctionIndirect, flags);
      break;
#endif // V8_ENABLE_WEBASSEMBLY
    case CallDescriptor::kCallBuiltinPointer:
      opcode = EncodeCallDescriptorFlags(kArchCallBuiltinPointer, flags);
      break;
  }
  // Emit the call instruction.
  size_t const output_count = buffer.outputs.size();
  auto* outputs = output_count ? &buffer.outputs.front() : nullptr;
  Instruction* call_instr =
      Emit(opcode, output_count, outputs, buffer.instruction_args.size(),
           &buffer.instruction_args.front());
  if (instruction_selection_failed()) return;
  call_instr->MarkAsCall();
  EmitPrepareResults(&(buffer.output_nodes), call_descriptor, node);
  if (call_descriptor->NeedsCallerSavedRegisters()) {
    Emit(
        kArchRestoreCallerRegisters | MiscField::encode(static_cast<int>(mode)),
        g.NoOutput());
  }
}
References v8::internal::compiler::turboshaft::CallOp::arguments(), v8::internal::compiler::turboshaft::CallOp::callee(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::TSCallDescriptor::descriptor, v8::internal::compiler::turboshaft::CallOp::descriptor, Emit(), EmitPrepareArguments(), EmitPrepareResults(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::EncodeCallDescriptorFlags(), v8::internal::compiler::CallDescriptor::flags(), v8::internal::flags, v8::internal::compiler::CallDescriptor::FPParameterCount(), v8::internal::compiler::turboshaft::CallOp::frame_state(), v8::internal::ZoneVector< T >::front(), GetFrameStateDescriptor(), v8::internal::compiler::CallDescriptor::GPParameterCount(), InitializeCallBuffer(), v8::internal::compiler::CallBuffer::instruction_args, instruction_selection_failed(), v8::internal::compiler::CallDescriptor::IsJSFunctionCall(), IsRelocatableWasmConstant(), v8::internal::compiler::CallDescriptor::kCallAddress, kCallAddressImmediate, v8::internal::compiler::CallDescriptor::kCallBuiltinPointer, kCallCodeImmediate, v8::internal::compiler::CallDescriptor::kCallCodeObject, kCallFixedTargetRegister, v8::internal::compiler::CallDescriptor::kCallJSFunction, v8::internal::compiler::CallDescriptor::kFixedTargetRegister, v8::internal::compiler::CallDescriptor::kHasExceptionHandler, v8::internal::kHasFunctionDescriptorBitShift, v8::internal::kIgnore, v8::internal::compiler::CallDescriptor::kind(), v8::internal::compiler::kLazyDeoptOnThrowSentinel, v8::internal::kSave, v8::base::BitField< T, shift, size, U >::kSize, v8::internal::compiler::kYes, v8::internal::compiler::OperandGenerator::Label(), v8::internal::compiler::turboshaft::TSCallDescriptor::lazy_deopt_on_throw, v8::internal::compiler::Instruction::MarkAsCall(), mode(), v8::internal::compiler::CallDescriptor::NeedsCallerSavedFPRegisters(), v8::internal::compiler::CallDescriptor::NeedsCallerSavedRegisters(), v8::internal::compiler::CallDescriptor::NeedsFrameState(), v8::internal::compiler::CallDescriptor::NoFunctionDescriptor(), v8::internal::compiler::OperandGenerator::NoOutput(), v8::internal::compiler::CallBuffer::output_nodes, v8::internal::compiler::CallBuffer::outputs, v8::internal::ZoneVector< T >::push_back(), v8::internal::compiler::CallBuffer::pushed_nodes, v8::internal::compiler::CallDescriptor::RequiresEntrypointTagForCall(), v8::internal::compiler::turboshaft::CallOp::results_rep(), v8::internal::compiler::CallDescriptor::shifted_tag(), v8::internal::compiler::CallDescriptor::signature_hash(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::OperandGenerator::TempImmediate(), UpdateMaxPushedArgumentCount(), v8::internal::compiler::OperandGenerator::UseImmediate(), v8::internal::compiler::OperandGenerator::UseImmediate64(), and zone().
Referenced by VisitControl(), and VisitNode().
VisitConstant()
void v8::internal::compiler::InstructionSelector::VisitConstant (turboshaft::OpIndex node) [private]
Definition at line 2135 of file instruction-selector.cc.
                                                    {
  // We must emit a NOP here because every live range needs a defining
  // instruction in the register allocator.
  OperandGenerator g(this);
  Emit(kArchNop, g.DefineAsConstant(node));
}
References v8::internal::compiler::OperandGenerator::DefineAsConstant(), and Emit().
Referenced by VisitNode().
VisitControl()
void v8::internal::compiler::InstructionSelector::VisitControl (const turboshaft::Block * block) [private]
Definition at line 2603 of file instruction-selector.cc.
                                                         {
#ifdef DEBUG
  // SSA deconstruction requires targets of branches not to have phis.
  // Edge split form guarantees this property, but is more strict.
  if (auto successors =
          SuccessorBlocks(block->LastOperation(*turboshaft_graph()));
      successors.size() > 1) {
    for (Block* successor : successors) {
      if (successor->HasPhis(*turboshaft_graph())) {
        std::ostringstream str;
        str << "You might have specified merged variables for a label with "
            << "only one predecessor." << std::endl
            << "# Current Block: " << successor->index() << std::endl;
        FATAL("%s", str.str().c_str());
      }
    }
  }
#endif // DEBUG
  const Operation& op = block->LastOperation(*schedule());
  OpIndex node = schedule()->Index(op);
  int instruction_end = static_cast<int>(instructions_.size());
  switch (op.opcode) {
    case Opcode::kGoto:
      VisitGoto(op.Cast<GotoOp>().destination);
      break;
    case Opcode::kReturn:
      VisitReturn(node);
      break;
    case Opcode::kTailCall:
      VisitTailCall(node);
      break;
    case Opcode::kDeoptimize: {
      const DeoptimizeOp& deoptimize = op.Cast<DeoptimizeOp>();
      VisitDeoptimize(deoptimize.parameters->reason(), node.id(),
                      deoptimize.parameters->feedback(),
                      deoptimize.frame_state());
      break;
    }
    case Opcode::kBranch: {
      const BranchOp& branch = op.Cast<BranchOp>();
      Block* tbranch = branch.if_true;
      Block* fbranch = branch.if_false;
      if (tbranch == fbranch) {
        VisitGoto(tbranch);
      } else {
        VisitBranch(node, tbranch, fbranch);
      }
      break;
    }
    case Opcode::kSwitch: {
      const SwitchOp& swtch = op.Cast<SwitchOp>();
      int32_t min_value = std::numeric_limits<int32_t>::max();
      int32_t max_value = std::numeric_limits<int32_t>::min();
      ZoneVector<CaseInfo> cases(swtch.cases.size(), zone());
      for (size_t i = 0; i < swtch.cases.size(); ++i) {
        const SwitchOp::Case& c = swtch.cases[i];
        cases[i] = CaseInfo{c.value, 0, c.destination};
        if (min_value > c.value) min_value = c.value;
        if (max_value < c.value) max_value = c.value;
      }
      SwitchInfo sw(std::move(cases), min_value, max_value, swtch.default_case);
      return VisitSwitch(node, sw);
    }
    case Opcode::kCheckException: {
      const CheckExceptionOp& check = op.Cast<CheckExceptionOp>();
      VisitCall(check.throwing_operation(), check.catch_block);
      VisitGoto(check.didnt_throw_block);
      return;
    }
    case Opcode::kUnreachable:
      return VisitUnreachable(node);
    case Opcode::kStaticAssert:
      return VisitStaticAssert(node);
    default: {
      const std::string op_string = op.ToString();
      PrintF("\033[31mNo ISEL support for: %s\033[m\n", op_string.c_str());
      FATAL("Unexpected operation #%d:%s", node.id(), op_string.c_str());
    }
  }
  if (trace_turbo_) {
    DCHECK(node.valid());
    int instruction_start = static_cast<int>(instructions_.size());
    instr_origins_[node.id()] = {instruction_start, instruction_end};
  }
}
References block(), v8::internal::compiler::turboshaft::SwitchOp::cases, v8::internal::compiler::turboshaft::Operation::Cast(), v8::internal::compiler::turboshaft::CheckExceptionOp::catch_block, v8::internal::DCHECK(), v8::internal::compiler::turboshaft::SwitchOp::default_case, v8::internal::compiler::turboshaft::GotoOp::destination, v8::internal::compiler::turboshaft::SwitchOp::Case::destination, v8::internal::compiler::turboshaft::CheckExceptionOp::didnt_throw_block, FATAL, v8::internal::compiler::DeoptimizeParameters::feedback(), v8::internal::compiler::turboshaft::DeoptimizeOp::frame_state(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::turboshaft::BranchOp::if_false, v8::internal::compiler::turboshaft::BranchOp::if_true, v8::internal::compiler::turboshaft::Graph::Index(), instr_origins_, instructions_, v8::internal::compiler::turboshaft::kBranch, v8::internal::wasm::kSwitch, v8::internal::wasm::kTailCall, v8::internal::wasm::kUnreachable, v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::DeoptimizeOp::parameters, v8::internal::PrintF(), v8::internal::compiler::DeoptimizeParameters::reason(), schedule(), v8::internal::ZoneVector< T >::size(), v8::internal::string, v8::internal::compiler::turboshaft::SuccessorBlocks(), v8::internal::compiler::turboshaft::CheckExceptionOp::throwing_operation(), v8::internal::compiler::turboshaft::Operation::ToString(), trace_turbo_, turboshaft_graph(), v8::internal::compiler::turboshaft::OpIndex::valid(), v8::internal::compiler::turboshaft::SwitchOp::Case::value, VisitBranch(), VisitCall(), VisitDeoptimize(), VisitGoto(), VisitReturn(), VisitStaticAssert(), VisitSwitch(), VisitTailCall(), VisitUnreachable(), and zone().
Referenced by VisitBlock().
VisitDeoptimize()
void v8::internal::compiler::InstructionSelector::VisitDeoptimize (DeoptimizeReason reason, uint32_t node_id, FeedbackSource const & feedback, turboshaft::OpIndex frame_state) [private]
Definition at line 2552 of file instruction-selector.cc.
                                                               {
  InstructionOperandVector args(instruction_zone());
  AppendDeoptimizeArguments(&args, reason, node_id, feedback, frame_state);
  Emit(kArchDeoptimize, 0, nullptr, args.size(), &args.front(), 0, nullptr);
}
References AppendDeoptimizeArguments(), v8::base::args, Emit(), and instruction_zone().
Referenced by VisitControl().
VisitDeoptimizeIf()
void v8::internal::compiler::InstructionSelector::VisitDeoptimizeIf (turboshaft::OpIndex node) [private]
Definition at line 2511 of file instruction-selector.cc.
                                                        {
  const DeoptimizeIfOp& deopt = Cast<DeoptimizeIfOp>(node);
  TryPrepareScheduleFirstProjection(deopt.condition());
  FlagsContinuation cont = FlagsContinuation::ForDeoptimize(
      deopt.negated ? kEqual : kNotEqual, deopt.parameters->reason(), node.id(),
      deopt.parameters->feedback(), deopt.frame_state());
  VisitWordCompareZero(node, deopt.condition(), &cont);
}
References v8::internal::compiler::turboshaft::DeoptimizeIfOp::condition(), v8::internal::compiler::DeoptimizeParameters::feedback(), v8::internal::compiler::FlagsContinuation::ForDeoptimize(), v8::internal::compiler::turboshaft::DeoptimizeIfOp::frame_state(), v8::internal::compiler::turboshaft::OpIndex::id(), v8::internal::compiler::kEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::turboshaft::DeoptimizeIfOp::negated, v8::internal::compiler::turboshaft::DeoptimizeIfOp::parameters, v8::internal::compiler::DeoptimizeParameters::reason(), TryPrepareScheduleFirstProjection(), and VisitWordCompareZero().
Referenced by VisitNode().
VisitFloat64Ieee754Binop()
void v8::internal::compiler::InstructionSelector::VisitFloat64Ieee754Binop (turboshaft::OpIndex node, InstructionCode code) [private]
Definition at line 1825 of file instruction-selector-arm.cc.
                                                                           {
  ArmOperandGenerator g(this);
  const FloatBinopOp& binop = Cast<FloatBinopOp>(node);
  Emit(opcode, g.DefineAsFixed(node, d0), g.UseFixed(binop.left(), d0),
       g.UseFixed(binop.right(), d1))
      ->MarkAsCall();
}
References v8::internal::compiler::OperandGenerator::DefineAsFixed(), v8::internal::compiler::turboshaft::FloatBinopOp::left(), v8::internal::compiler::turboshaft::FloatBinopOp::right(), and v8::internal::compiler::OperandGenerator::UseFixed().
VisitFloat64Ieee754Unop()
void v8::internal::compiler::InstructionSelector::VisitFloat64Ieee754Unop (turboshaft::OpIndex node, InstructionCode code) [private]
Definition at line 1834 of file instruction-selector-arm.cc.
                                                                          {
  ArmOperandGenerator g(this);
  Emit(opcode, g.DefineAsFixed(node, d0),
       g.UseFixed(Cast<FloatUnaryOp>(node).input(), d0))
      ->MarkAsCall();
}
References v8::internal::compiler::OperandGenerator::DefineAsFixed(), and v8::internal::compiler::OperandGenerator::UseFixed().
VisitGoto()
void v8::internal::compiler::InstructionSelector::VisitGoto (turboshaft::Block * target) [private]
Definition at line 2365 of file instruction-selector.cc.
                                                 {
  // jump to the next block.
  OperandGenerator g(this);
  Emit(kArchJmp, g.NoOutput(), g.Label(target));
}
References Emit(), v8::internal::compiler::OperandGenerator::Label(), and v8::internal::compiler::OperandGenerator::NoOutput().
Referenced by VisitControl().
VisitI8x16RelaxedSwizzle()
void v8::internal::compiler::InstructionSelector::VisitI8x16RelaxedSwizzle (turboshaft::OpIndex node) [private]
VisitIfException()
void v8::internal::compiler::InstructionSelector::VisitIfException (turboshaft::OpIndex node) [private]
Definition at line 1992 of file instruction-selector.cc.
                                                       {
  OperandGenerator g(this);
  Emit(kArchNop, g.DefineAsLocation(node, ExceptionLocation()));
}
References v8::internal::compiler::OperandGenerator::DefineAsLocation(), Emit(), and v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::ExceptionLocation().
Referenced by VisitNode().
VisitLoad()
void v8::internal::compiler::InstructionSelector::VisitLoad (turboshaft::OpIndex node, turboshaft::OpIndex value, InstructionCode opcode) [private]
Definition at line 651 of file instruction-selector-arm.cc.
                                                {
  LoadView load = load_view(node);
  LoadRepresentation load_rep = load.loaded_rep();
  ArmOperandGenerator g(this);
  OpIndex base = load.base();
  OpIndex index = load.index();
  InstructionCode opcode = kArchNop;
  switch (load_rep.representation()) {
    case MachineRepresentation::kFloat32:
      opcode = kArmVldrF32;
      break;
    case MachineRepresentation::kFloat64:
      opcode = kArmVldrF64;
      break;
    case MachineRepresentation::kBit: // Fall through.
    case MachineRepresentation::kWord8:
      opcode = load_rep.IsUnsigned() ? kArmLdrb : kArmLdrsb;
      break;
    case MachineRepresentation::kWord16:
      opcode = load_rep.IsUnsigned() ? kArmLdrh : kArmLdrsh;
      break;
    case MachineRepresentation::kTaggedSigned: // Fall through.
    case MachineRepresentation::kTaggedPointer: // Fall through.
    case MachineRepresentation::kTagged: // Fall through.
    case MachineRepresentation::kWord32:
      opcode = kArmLdr;
      break;
    case MachineRepresentation::kSimd128:
      opcode = kArmVld1S128;
      break;
    case MachineRepresentation::kFloat16:
      UNIMPLEMENTED();
    case MachineRepresentation::kSimd256: // Fall through.
    case MachineRepresentation::kCompressedPointer: // Fall through.
    case MachineRepresentation::kCompressed: // Fall through.
    case MachineRepresentation::kProtectedPointer: // Fall through.
    case MachineRepresentation::kIndirectPointer: // Fall through.
    case MachineRepresentation::kSandboxedPointer: // Fall through.
    case MachineRepresentation::kWord64: // Fall through.
    case MachineRepresentation::kMapWord: // Fall through.
    case MachineRepresentation::kFloat16RawBits: // Fall through.
    case MachineRepresentation::kNone:
      UNREACHABLE();
  }
  InstructionOperand output = g.DefineAsRegister(node);
  EmitLoad(this, opcode, &output, base, index);
}
References v8::internal::compiler::InstructionSelector::LoadView::base(), v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::internal::compiler::EmitLoad(), v8::internal::compiler::InstructionSelector::LoadView::index(), v8::internal::index, v8::internal::MachineType::IsUnsigned(), v8::internal::kBit, v8::internal::kCompressed, v8::internal::kCompressedPointer, v8::internal::kFloat16, v8::internal::kFloat16RawBits, v8::internal::kFloat32, v8::internal::kFloat64, v8::internal::kIndirectPointer, v8::internal::kMapWord, v8::internal::kNone, v8::internal::kProtectedPointer, v8::internal::kSandboxedPointer, v8::internal::kSimd128, v8::internal::kSimd256, v8::internal::kTagged, v8::internal::kTaggedPointer, v8::internal::kTaggedSigned, v8::internal::kWord16, v8::internal::kWord32, v8::internal::kWord64, v8::internal::kWord8, v8::internal::compiler::InstructionSelector::LoadView::loaded_rep(), v8::internal::MachineType::representation(), v8::internal::compiler::UNIMPLEMENTED(), and v8::internal::UNREACHABLE().
Referenced by VisitNode().
VisitNode()
void v8::internal::compiler::InstructionSelector::VisitNode (turboshaft::OpIndex node) [private]
Definition at line 2691 of file instruction-selector.cc.
                                                {
  tick_counter_->TickAndMaybeEnterSafepoint();
  const Operation& op = this->Get(node);
  using Opcode = Opcode;
  using Rep = RegisterRepresentation;
  switch (op.opcode) {
    case Opcode::kBranch:
    case Opcode::kGoto:
    case Opcode::kReturn:
    case Opcode::kTailCall:
    case Opcode::kUnreachable:
    case Opcode::kDeoptimize:
    case Opcode::kSwitch:
    case Opcode::kCheckException:
      // Those are already handled in VisitControl.
      DCHECK(op.IsBlockTerminator());
      break;
    case Opcode::kParameter: {
      // Parameters should always be scheduled to the first block.
      DCHECK_EQ(this->rpo_number(this->block(schedule(), node)).ToInt(), 0);
      MachineType type =
          linkage()->GetParameterType(op.Cast<ParameterOp>().parameter_index);
      MarkAsRepresentation(type.representation(), node);
      return VisitParameter(node);
    }
    case Opcode::kChange: {
      const ChangeOp& change = op.Cast<ChangeOp>();
      MarkAsRepresentation(change.to.machine_representation(), node);
      switch (change.kind) {
        case ChangeOp::Kind::kFloatConversion:
          if (change.from == Rep::Float64()) {
            DCHECK_EQ(change.to, Rep::Float32());
            return VisitTruncateFloat64ToFloat32(node);
          } else {
            DCHECK_EQ(change.from, Rep::Float32());
            DCHECK_EQ(change.to, Rep::Float64());
            return VisitChangeFloat32ToFloat64(node);
          }
        case ChangeOp::Kind::kSignedFloatTruncateOverflowToMin:
        case ChangeOp::Kind::kUnsignedFloatTruncateOverflowToMin: {
          using A = ChangeOp::Assumption;
          bool is_signed =
              change.kind == ChangeOp::Kind::kSignedFloatTruncateOverflowToMin;
          switch (multi(change.from, change.to, is_signed, change.assumption)) {
            case multi(Rep::Float32(), Rep::Word32(), true, A::kNoOverflow):
            case multi(Rep::Float32(), Rep::Word32(), true, A::kNoAssumption):
              return VisitTruncateFloat32ToInt32(node);
            case multi(Rep::Float32(), Rep::Word32(), false, A::kNoOverflow):
            case multi(Rep::Float32(), Rep::Word32(), false, A::kNoAssumption):
              return VisitTruncateFloat32ToUint32(node);
            case multi(Rep::Float64(), Rep::Word32(), true, A::kReversible):
              return VisitChangeFloat64ToInt32(node);
            case multi(Rep::Float64(), Rep::Word32(), false, A::kReversible):
              return VisitChangeFloat64ToUint32(node);
            case multi(Rep::Float64(), Rep::Word32(), true, A::kNoOverflow):
              return VisitRoundFloat64ToInt32(node);
            case multi(Rep::Float64(), Rep::Word32(), false, A::kNoAssumption):
            case multi(Rep::Float64(), Rep::Word32(), false, A::kNoOverflow):
              return VisitTruncateFloat64ToUint32(node);
            case multi(Rep::Float64(), Rep::Word64(), true, A::kReversible):
              return VisitChangeFloat64ToInt64(node);
            case multi(Rep::Float64(), Rep::Word64(), false, A::kReversible):
              return VisitChangeFloat64ToUint64(node);
            case multi(Rep::Float64(), Rep::Word64(), true, A::kNoOverflow):
            case multi(Rep::Float64(), Rep::Word64(), true, A::kNoAssumption):
              return VisitTruncateFloat64ToInt64(node);
            default:
              // Invalid combination.
              UNREACHABLE();
          }
          UNREACHABLE();
        }
        case ChangeOp::Kind::kJSFloatTruncate:
          DCHECK_EQ(change.from, Rep::Float64());
          DCHECK_EQ(change.to, Rep::Word32());
          return VisitTruncateFloat64ToWord32(node);
        case ChangeOp::Kind::kJSFloat16TruncateWithBitcast:
          DCHECK_EQ(Rep::Float64(), change.from);
          DCHECK_EQ(Rep::Word32(), change.to);
          return VisitTruncateFloat64ToFloat16RawBits(node);
        case ChangeOp::Kind::kJSFloat16ChangeWithBitcast:
          DCHECK_EQ(Rep::Word32(), change.from);
          DCHECK_EQ(Rep::Float64(), change.to);
          return VisitChangeFloat16RawBitsToFloat64(node);
        case ChangeOp::Kind::kSignedToFloat:
          if (change.from == Rep::Word32()) {
            if (change.to == Rep::Float32()) {
              return VisitRoundInt32ToFloat32(node);
            } else {
              DCHECK_EQ(change.to, Rep::Float64());
              DCHECK_EQ(change.assumption, ChangeOp::Assumption::kNoAssumption);
              return VisitChangeInt32ToFloat64(node);
            }
          } else {
            DCHECK_EQ(change.from, Rep::Word64());
            if (change.to == Rep::Float32()) {
              return VisitRoundInt64ToFloat32(node);
            } else {
              DCHECK_EQ(change.to, Rep::Float64());
              if (change.assumption == ChangeOp::Assumption::kReversible) {
                return VisitChangeInt64ToFloat64(node);
              } else {
                return VisitRoundInt64ToFloat64(node);
              }
            }
          }
          UNREACHABLE();
        case ChangeOp::Kind::kUnsignedToFloat:
          switch (multi(change.from, change.to)) {
            case multi(Rep::Word32(), Rep::Float32()):
              return VisitRoundUint32ToFloat32(node);
            case multi(Rep::Word32(), Rep::Float64()):
              return VisitChangeUint32ToFloat64(node);
            case multi(Rep::Word64(), Rep::Float32()):
              return VisitRoundUint64ToFloat32(node);
            case multi(Rep::Word64(), Rep::Float64()):
              return VisitRoundUint64ToFloat64(node);
            default:
              UNREACHABLE();
          }
        case ChangeOp::Kind::kExtractHighHalf:
          DCHECK_EQ(change.from, Rep::Float64());
          DCHECK_EQ(change.to, Rep::Word32());
          return VisitFloat64ExtractHighWord32(node);
        case ChangeOp::Kind::kExtractLowHalf:
          DCHECK_EQ(change.from, Rep::Float64());
          DCHECK_EQ(change.to, Rep::Word32());
          return VisitFloat64ExtractLowWord32(node);
        case ChangeOp::Kind::kZeroExtend:
          DCHECK_EQ(change.from, Rep::Word32());
          DCHECK_EQ(change.to, Rep::Word64());
          return VisitChangeUint32ToUint64(node);
        case ChangeOp::Kind::kSignExtend:
          DCHECK_EQ(change.from, Rep::Word32());
          DCHECK_EQ(change.to, Rep::Word64());
          return VisitChangeInt32ToInt64(node);
        case ChangeOp::Kind::kTruncate:
          DCHECK_EQ(change.from, Rep::Word64());
          DCHECK_EQ(change.to, Rep::Word32());
          MarkAsWord32(node);
          return VisitTruncateInt64ToInt32(node);
        case ChangeOp::Kind::kBitcast:
          switch (multi(change.from, change.to)) {
            case multi(Rep::Word32(), Rep::Word64()):
              return VisitBitcastWord32ToWord64(node);
            case multi(Rep::Word32(), Rep::Float32()):
              return VisitBitcastInt32ToFloat32(node);
            case multi(Rep::Word64(), Rep::Float64()):
              return VisitBitcastInt64ToFloat64(node);
            case multi(Rep::Float32(), Rep::Word32()):
              return VisitBitcastFloat32ToInt32(node);
            case multi(Rep::Float64(), Rep::Word64()):
              return VisitBitcastFloat64ToInt64(node);
            default:
              UNREACHABLE();
          }
      }
      UNREACHABLE();
    }
    case Opcode::kTryChange: {
      const TryChangeOp& try_change = op.Cast<TryChangeOp>();
      MarkAsRepresentation(try_change.to.machine_representation(), node);
      DCHECK(try_change.kind ==
                 TryChangeOp::Kind::kSignedFloatTruncateOverflowUndefined ||
             try_change.kind ==
                 TryChangeOp::Kind::kUnsignedFloatTruncateOverflowUndefined);
      const bool is_signed =
          try_change.kind ==
          TryChangeOp::Kind::kSignedFloatTruncateOverflowUndefined;
      switch (multi(try_change.from, try_change.to, is_signed)) {
        case multi(Rep::Float64(), Rep::Word64(), true):
          return VisitTryTruncateFloat64ToInt64(node);
        case multi(Rep::Float64(), Rep::Word64(), false):
          return VisitTryTruncateFloat64ToUint64(node);
        case multi(Rep::Float64(), Rep::Word32(), true):
          return VisitTryTruncateFloat64ToInt32(node);
        case multi(Rep::Float64(), Rep::Word32(), false):
          return VisitTryTruncateFloat64ToUint32(node);
        case multi(Rep::Float32(), Rep::Word64(), true):
          return VisitTryTruncateFloat32ToInt64(node);
        case multi(Rep::Float32(), Rep::Word64(), false):
          return VisitTryTruncateFloat32ToUint64(node);
        default:
          UNREACHABLE();
      }
      UNREACHABLE();
    }
    case Opcode::kConstant: {
      const ConstantOp& constant = op.Cast<ConstantOp>();
      switch (constant.kind) {
        case ConstantOp::Kind::kWord32:
        case ConstantOp::Kind::kWord64:
        case ConstantOp::Kind::kSmi:
        case ConstantOp::Kind::kTaggedIndex:
        case ConstantOp::Kind::kExternal:
          break;
        case ConstantOp::Kind::kFloat32:
          MarkAsFloat32(node);
          break;
        case ConstantOp::Kind::kFloat64:
          MarkAsFloat64(node);
          break;
        case ConstantOp::Kind::kHeapObject:
        case ConstantOp::Kind::kTrustedHeapObject:
          MarkAsTagged(node);
          break;
        case ConstantOp::Kind::kCompressedHeapObject:
          MarkAsCompressed(node);
          break;
        case ConstantOp::Kind::kNumber:
          if (!IsSmiDouble(constant.number().get_scalar())) MarkAsTagged(node);
          break;
        case ConstantOp::Kind::kRelocatableWasmCall:
        case ConstantOp::Kind::kRelocatableWasmStubCall:
        case ConstantOp::Kind::kRelocatableWasmCanonicalSignatureId:
        case ConstantOp::Kind::kRelocatableWasmIndirectCallTarget:
          break;
      }
      VisitConstant(node);
      break;
    }
    case Opcode::kWordUnary: {
      const WordUnaryOp& unop = op.Cast<WordUnaryOp>();
      if (unop.rep == WordRepresentation::Word32()) {
        MarkAsWord32(node);
        switch (unop.kind) {
          case WordUnaryOp::Kind::kReverseBytes:
            return VisitWord32ReverseBytes(node);
          case WordUnaryOp::Kind::kCountLeadingZeros:
            return VisitWord32Clz(node);
          case WordUnaryOp::Kind::kCountTrailingZeros:
            return VisitWord32Ctz(node);
          case WordUnaryOp::Kind::kPopCount:
            return VisitWord32Popcnt(node);
          case WordUnaryOp::Kind::kSignExtend8:
            return VisitSignExtendWord8ToInt32(node);
          case WordUnaryOp::Kind::kSignExtend16:
            return VisitSignExtendWord16ToInt32(node);
        }
      } else {
        DCHECK_EQ(unop.rep, WordRepresentation::Word64());
        MarkAsWord64(node);
        switch (unop.kind) {
          case WordUnaryOp::Kind::kReverseBytes:
            return VisitWord64ReverseBytes(node);
          case WordUnaryOp::Kind::kCountLeadingZeros:
            return VisitWord64Clz(node);
          case WordUnaryOp::Kind::kCountTrailingZeros:
            return VisitWord64Ctz(node);
          case WordUnaryOp::Kind::kPopCount:
            return VisitWord64Popcnt(node);
          case WordUnaryOp::Kind::kSignExtend8:
            return VisitSignExtendWord8ToInt64(node);
          case WordUnaryOp::Kind::kSignExtend16:
            return VisitSignExtendWord16ToInt64(node);
        }
      }
      UNREACHABLE();
    }
    case Opcode::kWordBinop: {
      const WordBinopOp& binop = op.Cast<WordBinopOp>();
      if (binop.rep == WordRepresentation::Word32()) {
        MarkAsWord32(node);
        switch (binop.kind) {
          case WordBinopOp::Kind::kAdd:
            return VisitInt32Add(node);
          case WordBinopOp::Kind::kMul:
            return VisitInt32Mul(node);
          case WordBinopOp::Kind::kSignedMulOverflownBits:
            return VisitInt32MulHigh(node);
          case WordBinopOp::Kind::kUnsignedMulOverflownBits:
            return VisitUint32MulHigh(node);
          case WordBinopOp::Kind::kBitwiseAnd:
            return VisitWord32And(node);
          case WordBinopOp::Kind::kBitwiseOr:
            return VisitWord32Or(node);
          case WordBinopOp::Kind::kBitwiseXor:
            return VisitWord32Xor(node);
          case WordBinopOp::Kind::kSub:
            return VisitInt32Sub(node);
          case WordBinopOp::Kind::kSignedDiv:
            return VisitInt32Div(node);
          case WordBinopOp::Kind::kUnsignedDiv:
            return VisitUint32Div(node);
          case WordBinopOp::Kind::kSignedMod:
            return VisitInt32Mod(node);
          case WordBinopOp::Kind::kUnsignedMod:
            return VisitUint32Mod(node);
        }
      } else {
        DCHECK_EQ(binop.rep, WordRepresentation::Word64());
        MarkAsWord64(node);
        switch (binop.kind) {
          case WordBinopOp::Kind::kAdd:
            return VisitInt64Add(node);
          case WordBinopOp::Kind::kMul:
            return VisitInt64Mul(node);
          case WordBinopOp::Kind::kSignedMulOverflownBits:
            return VisitInt64MulHigh(node);
          case WordBinopOp::Kind::kUnsignedMulOverflownBits:
            return VisitUint64MulHigh(node);
          case WordBinopOp::Kind::kBitwiseAnd:
            return VisitWord64And(node);
          case WordBinopOp::Kind::kBitwiseOr:
            return VisitWord64Or(node);
          case WordBinopOp::Kind::kBitwiseXor:
            return VisitWord64Xor(node);
          case WordBinopOp::Kind::kSub:
            return VisitInt64Sub(node);
          case WordBinopOp::Kind::kSignedDiv:
            return VisitInt64Div(node);
          case WordBinopOp::Kind::kUnsignedDiv:
            return VisitUint64Div(node);
          case WordBinopOp::Kind::kSignedMod:
            return VisitInt64Mod(node);
          case WordBinopOp::Kind::kUnsignedMod:
            return VisitUint64Mod(node);
        }
      }
      UNREACHABLE();
    }
    case Opcode::kFloatUnary: {
      const auto& unop = op.Cast<FloatUnaryOp>();
      if (unop.rep == Rep::Float32()) {
        MarkAsFloat32(node);
        switch (unop.kind) {
          case FloatUnaryOp::Kind::kAbs:
            return VisitFloat32Abs(node);
          case FloatUnaryOp::Kind::kNegate:
            return VisitFloat32Neg(node);
          case FloatUnaryOp::Kind::kRoundDown:
            return VisitFloat32RoundDown(node);
          case FloatUnaryOp::Kind::kRoundUp:
            return VisitFloat32RoundUp(node);
          case FloatUnaryOp::Kind::kRoundToZero:
            return VisitFloat32RoundTruncate(node);
          case FloatUnaryOp::Kind::kRoundTiesEven:
            return VisitFloat32RoundTiesEven(node);
          case FloatUnaryOp::Kind::kSqrt:
            return VisitFloat32Sqrt(node);
          // Those operations are only supported on 64 bit.
          case FloatUnaryOp::Kind::kSilenceNaN:
          case FloatUnaryOp::Kind::kLog:
          case FloatUnaryOp::Kind::kLog2:
          case FloatUnaryOp::Kind::kLog10:
          case FloatUnaryOp::Kind::kLog1p:
          case FloatUnaryOp::Kind::kCbrt:
          case FloatUnaryOp::Kind::kExp:
          case FloatUnaryOp::Kind::kExpm1:
          case FloatUnaryOp::Kind::kSin:
          case FloatUnaryOp::Kind::kCos:
          case FloatUnaryOp::Kind::kSinh:
          case FloatUnaryOp::Kind::kCosh:
          case FloatUnaryOp::Kind::kAcos:
          case FloatUnaryOp::Kind::kAsin:
          case FloatUnaryOp::Kind::kAsinh:
          case FloatUnaryOp::Kind::kAcosh:
          case FloatUnaryOp::Kind::kTan:
          case FloatUnaryOp::Kind::kTanh:
          case FloatUnaryOp::Kind::kAtan:
          case FloatUnaryOp::Kind::kAtanh:
            UNREACHABLE();
        }
      } else {
        DCHECK_EQ(unop.rep, Rep::Float64());
        MarkAsFloat64(node);
        switch (unop.kind) {
          case FloatUnaryOp::Kind::kAbs:
            return VisitFloat64Abs(node);
          case FloatUnaryOp::Kind::kNegate:
            return VisitFloat64Neg(node);
          case FloatUnaryOp::Kind::kSilenceNaN:
            return VisitFloat64SilenceNaN(node);
          case FloatUnaryOp::Kind::kRoundDown:
            return VisitFloat64RoundDown(node);
          case FloatUnaryOp::Kind::kRoundUp:
            return VisitFloat64RoundUp(node);
          case FloatUnaryOp::Kind::kRoundToZero:
            return VisitFloat64RoundTruncate(node);
          case FloatUnaryOp::Kind::kRoundTiesEven:
            return VisitFloat64RoundTiesEven(node);
          case FloatUnaryOp::Kind::kLog:
            return VisitFloat64Log(node);
          case FloatUnaryOp::Kind::kLog2:
            return VisitFloat64Log2(node);
          case FloatUnaryOp::Kind::kLog10:
            return VisitFloat64Log10(node);
          case FloatUnaryOp::Kind::kLog1p:
            return VisitFloat64Log1p(node);
          case FloatUnaryOp::Kind::kSqrt:
            return VisitFloat64Sqrt(node);
          case FloatUnaryOp::Kind::kCbrt:
            return VisitFloat64Cbrt(node);
          case FloatUnaryOp::Kind::kExp:
            return VisitFloat64Exp(node);
          case FloatUnaryOp::Kind::kExpm1:
            return VisitFloat64Expm1(node);
          case FloatUnaryOp::Kind::kSin:
            return VisitFloat64Sin(node);
          case FloatUnaryOp::Kind::kCos:
            return VisitFloat64Cos(node);
          case FloatUnaryOp::Kind::kSinh:
            return VisitFloat64Sinh(node);
          case FloatUnaryOp::Kind::kCosh:
            return VisitFloat64Cosh(node);
          case FloatUnaryOp::Kind::kAcos:
            return VisitFloat64Acos(node);
          case FloatUnaryOp::Kind::kAsin:
            return VisitFloat64Asin(node);
          case FloatUnaryOp::Kind::kAsinh:
            return VisitFloat64Asinh(node);
          case FloatUnaryOp::Kind::kAcosh:
            return VisitFloat64Acosh(node);
          case FloatUnaryOp::Kind::kTan:
            return VisitFloat64Tan(node);
          case FloatUnaryOp::Kind::kTanh:
            return VisitFloat64Tanh(node);
          case FloatUnaryOp::Kind::kAtan:
            return VisitFloat64Atan(node);
          case FloatUnaryOp::Kind::kAtanh:
            return VisitFloat64Atanh(node);
        }
      }
      UNREACHABLE();
    }
    case Opcode::kFloatBinop: {
      const auto& binop = op.Cast<FloatBinopOp>();
      if (binop.rep == Rep::Float32()) {
        MarkAsFloat32(node);
        switch (binop.kind) {
          case FloatBinopOp::Kind::kAdd:
            return VisitFloat32Add(node);
          case FloatBinopOp::Kind::kSub:
            return VisitFloat32Sub(node);
          case FloatBinopOp::Kind::kMul:
            return VisitFloat32Mul(node);
          case FloatBinopOp::Kind::kDiv:
            return VisitFloat32Div(node);
          case FloatBinopOp::Kind::kMin:
            return VisitFloat32Min(node);
          case FloatBinopOp::Kind::kMax:
            return VisitFloat32Max(node);
          case FloatBinopOp::Kind::kMod:
          case FloatBinopOp::Kind::kPower:
          case FloatBinopOp::Kind::kAtan2:
            UNREACHABLE();
        }
      } else {
        DCHECK_EQ(binop.rep, Rep::Float64());
        MarkAsFloat64(node);
        switch (binop.kind) {
          case FloatBinopOp::Kind::kAdd:
            return VisitFloat64Add(node);
          case FloatBinopOp::Kind::kSub:
            return VisitFloat64Sub(node);
          case FloatBinopOp::Kind::kMul:
            return VisitFloat64Mul(node);
          case FloatBinopOp::Kind::kDiv:
            return VisitFloat64Div(node);
          case FloatBinopOp::Kind::kMod:
            return VisitFloat64Mod(node);
          case FloatBinopOp::Kind::kMin:
            return VisitFloat64Min(node);
          case FloatBinopOp::Kind::kMax:
            return VisitFloat64Max(node);
          case FloatBinopOp::Kind::kPower:
            return VisitFloat64Pow(node);
          case FloatBinopOp::Kind::kAtan2:
            return VisitFloat64Atan2(node);
        }
      }
      UNREACHABLE();
    }
    case Opcode::kOverflowCheckedBinop: {
      const auto& binop = op.Cast<OverflowCheckedBinopOp>();
      if (binop.rep == WordRepresentation::Word32()) {
        MarkAsWord32(node);
        switch (binop.kind) {
          case OverflowCheckedBinopOp::Kind::kSignedAdd:
            return VisitInt32AddWithOverflow(node);
          case OverflowCheckedBinopOp::Kind::kSignedMul:
            return VisitInt32MulWithOverflow(node);
          case OverflowCheckedBinopOp::Kind::kSignedSub:
            return VisitInt32SubWithOverflow(node);
        }
      } else {
        DCHECK_EQ(binop.rep, WordRepresentation::Word64());
        MarkAsWord64(node);
        switch (binop.kind) {
          case OverflowCheckedBinopOp::Kind::kSignedAdd:
            return VisitInt64AddWithOverflow(node);
          case OverflowCheckedBinopOp::Kind::kSignedMul:
            return VisitInt64MulWithOverflow(node);
          case OverflowCheckedBinopOp::Kind::kSignedSub:
            return VisitInt64SubWithOverflow(node);
        }
      }
      UNREACHABLE();
    }
    case Opcode::kOverflowCheckedUnary: {
      const auto& unop = op.Cast<OverflowCheckedUnaryOp>();
      if (unop.rep == WordRepresentation::Word32()) {
        MarkAsWord32(node);
        switch (unop.kind) {
          case OverflowCheckedUnaryOp::Kind::kAbs:
            return VisitInt32AbsWithOverflow(node);
        }
      } else {
        DCHECK_EQ(unop.rep, WordRepresentation::Word64());
        MarkAsWord64(node);
        switch (unop.kind) {
          case OverflowCheckedUnaryOp::Kind::kAbs:
            return VisitInt64AbsWithOverflow(node);
        }
      }
      UNREACHABLE();
    }
    case Opcode::kShift: {
      const auto& shift = op.Cast<ShiftOp>();
      if (shift.rep == RegisterRepresentation::Word32()) {
        MarkAsWord32(node);
        switch (shift.kind) {
          case ShiftOp::Kind::kShiftRightArithmeticShiftOutZeros:
          case ShiftOp::Kind::kShiftRightArithmetic:
            return VisitWord32Sar(node);
          case ShiftOp::Kind::kShiftRightLogical:
            return VisitWord32Shr(node);
          case ShiftOp::Kind::kShiftLeft:
            return VisitWord32Shl(node);
          case ShiftOp::Kind::kRotateRight:
            return VisitWord32Ror(node);
          case ShiftOp::Kind::kRotateLeft:
            return VisitWord32Rol(node);
        }
      } else {
        DCHECK_EQ(shift.rep, RegisterRepresentation::Word64());
        MarkAsWord64(node);
        switch (shift.kind) {
          case ShiftOp::Kind::kShiftRightArithmeticShiftOutZeros:
          case ShiftOp::Kind::kShiftRightArithmetic:
            return VisitWord64Sar(node);
          case ShiftOp::Kind::kShiftRightLogical:
            return VisitWord64Shr(node);
          case ShiftOp::Kind::kShiftLeft:
            return VisitWord64Shl(node);
          case ShiftOp::Kind::kRotateRight:
            return VisitWord64Ror(node);
          case ShiftOp::Kind::kRotateLeft:
            return VisitWord64Rol(node);
        }
      }
      UNREACHABLE();
    }
    case Opcode::kCall:
      // Process the call at `DidntThrow`, when we know if exceptions are caught
      // or not.
      break;
    case Opcode::kDidntThrow:
      if (current_block_->begin() == node) {
        DCHECK_EQ(current_block_->PredecessorCount(), 1);
        DCHECK(current_block_->LastPredecessor()
                   ->LastOperation(*this->turboshaft_graph())
                   .Is<CheckExceptionOp>());
        // In this case, the Call has been generated at the `CheckException`
        // already.
      } else {
        VisitCall(op.Cast<DidntThrowOp>().throwing_operation());
      }
      EmitIdentity(node);
      break;
    case Opcode::kFrameConstant: {
      const auto& constant = op.Cast<FrameConstantOp>();
      using Kind = FrameConstantOp::Kind;
      OperandGenerator g(this);
      switch (constant.kind) {
        case Kind::kStackCheckOffset:
          Emit(kArchStackCheckOffset, g.DefineAsRegister(node));
          break;
        case Kind::kFramePointer:
          Emit(kArchFramePointer, g.DefineAsRegister(node));
          break;
        case Kind::kParentFramePointer:
          Emit(kArchParentFramePointer, g.DefineAsRegister(node));
          break;
      }
      break;
    }
    case Opcode::kStackPointerGreaterThan:
      return VisitStackPointerGreaterThan(node);
    case Opcode::kComparison: {
      const ComparisonOp& comparison = op.Cast<ComparisonOp>();
      using Kind = ComparisonOp::Kind;
      switch (multi(comparison.kind, comparison.rep)) {
        case multi(Kind::kEqual, Rep::Word32()):
          return VisitWord32Equal(node);
        case multi(Kind::kEqual, Rep::Word64()):
          return VisitWord64Equal(node);
        case multi(Kind::kEqual, Rep::Float32()):
          return VisitFloat32Equal(node);
        case multi(Kind::kEqual, Rep::Float64()):
          return VisitFloat64Equal(node);
        case multi(Kind::kEqual, Rep::Tagged()):
          if constexpr (Is64() && !COMPRESS_POINTERS_BOOL) {
            return VisitWord64Equal(node);
          }
          return VisitWord32Equal(node);
        case multi(Kind::kSignedLessThan, Rep::Word32()):
          return VisitInt32LessThan(node);
        case multi(Kind::kSignedLessThan, Rep::Word64()):
          return VisitInt64LessThan(node);
        case multi(Kind::kSignedLessThan, Rep::Float32()):
          return VisitFloat32LessThan(node);
        case multi(Kind::kSignedLessThan, Rep::Float64()):
          return VisitFloat64LessThan(node);
        case multi(Kind::kSignedLessThanOrEqual, Rep::Word32()):
          return VisitInt32LessThanOrEqual(node);
        case multi(Kind::kSignedLessThanOrEqual, Rep::Word64()):
          return VisitInt64LessThanOrEqual(node);
        case multi(Kind::kSignedLessThanOrEqual, Rep::Float32()):
          return VisitFloat32LessThanOrEqual(node);
        case multi(Kind::kSignedLessThanOrEqual, Rep::Float64()):
          return VisitFloat64LessThanOrEqual(node);
        case multi(Kind::kUnsignedLessThan, Rep::Word32()):
          return VisitUint32LessThan(node);
        case multi(Kind::kUnsignedLessThan, Rep::Word64()):
          return VisitUint64LessThan(node);
        case multi(Kind::kUnsignedLessThanOrEqual, Rep::Word32()):
          return VisitUint32LessThanOrEqual(node);
        case multi(Kind::kUnsignedLessThanOrEqual, Rep::Word64()):
          return VisitUint64LessThanOrEqual(node);
        default:
          UNREACHABLE();
      }
      UNREACHABLE();
    }
    case Opcode::kLoad: {
      const LoadOp& load = op.Cast<LoadOp>();
      MachineType loaded_type = load.machine_type();
      MarkAsRepresentation(loaded_type.representation(), node);
      if (load.kind.maybe_unaligned) {
        DCHECK(!load.kind.with_trap_handler);
        DCHECK(!load.kind.is_atomic);
        if (loaded_type.representation() == MachineRepresentation::kWord8 ||
            InstructionSelector::AlignmentRequirements()
                .IsUnalignedLoadSupported(loaded_type.representation())) {
          return VisitLoad(node);
        } else {
          return VisitUnalignedLoad(node);
        }
      } else if (load.kind.is_atomic) {
        if (load.result_rep == Rep::Word32()) {
          return VisitWord32AtomicLoad(node);
        } else if (load.result_rep == Rep::Word64()) {
          return VisitWord64AtomicLoad(node);
        } else if (load.result_rep == Rep::Tagged()) {
          return kTaggedSize == 4 ? VisitWord32AtomicLoad(node)
                                  : VisitWord64AtomicLoad(node);
        }
      } else if (load.kind.with_trap_handler) {
        DCHECK(!load.kind.maybe_unaligned);
        return VisitProtectedLoad(node);
      } else {
        return VisitLoad(node);
      }
      UNREACHABLE();
    }
    case Opcode::kStore: {
      const StoreOp& store = op.Cast<StoreOp>();
      MachineRepresentation rep =
          store.stored_rep.ToMachineType().representation();
      if (store.kind.maybe_unaligned) {
        DCHECK(!store.kind.with_trap_handler);
        DCHECK_EQ(store.write_barrier, WriteBarrierKind::kNoWriteBarrier);
        if (rep == MachineRepresentation::kWord8 ||
            InstructionSelector::AlignmentRequirements()
                .IsUnalignedStoreSupported(rep)) {
          return VisitStore(node);
        } else {
          return VisitUnalignedStore(node);
        }
      } else if (store.kind.is_atomic) {
        if (store.stored_rep.SizeInBytes() == 8) {
          return VisitWord64AtomicStore(node);
        } else {
          DCHECK_LE(store.stored_rep.SizeInBytes(), 4);
          return VisitWord32AtomicStore(node);
        }
      } else if (store.kind.with_trap_handler) {
        DCHECK(!store.kind.maybe_unaligned);
        return VisitProtectedStore(node);
      } else {
        return VisitStore(node);
      }
      UNREACHABLE();
    }
    case Opcode::kTaggedBitcast: {
      const TaggedBitcastOp& cast = op.Cast<TaggedBitcastOp>();
      switch (multi(cast.from, cast.to)) {
        case multi(Rep::Tagged(), Rep::Word32()):
          MarkAsWord32(node);
          if constexpr (Is64()) {
            DCHECK_EQ(cast.kind, TaggedBitcastOp::Kind::kSmi);
            DCHECK(SmiValuesAre31Bits());
            return VisitBitcastSmiToWord(node);
          } else {
            return VisitBitcastTaggedToWord(node);
          }
        case multi(Rep::Tagged(), Rep::Word64()):
          MarkAsWord64(node);
          return VisitBitcastTaggedToWord(node);
        case multi(Rep::Word32(), Rep::Tagged()):
        case multi(Rep::Word64(), Rep::Tagged()):
          if (cast.kind == TaggedBitcastOp::Kind::kSmi) {
            MarkAsRepresentation(MachineRepresentation::kTaggedSigned, node);
            return EmitIdentity(node);
          } else {
            MarkAsTagged(node);
            return VisitBitcastWordToTagged(node);
          }
        case multi(Rep::Compressed(), Rep::Word32()):
          MarkAsWord32(node);
          if (cast.kind == TaggedBitcastOp::Kind::kSmi) {
            return VisitBitcastSmiToWord(node);
          } else {
            return VisitBitcastTaggedToWord(node);
          }
        default:
          UNIMPLEMENTED();
      }
    }
    case Opcode::kPhi:
      MarkAsRepresentation(op.Cast<PhiOp>().rep, node);
      return VisitPhi(node);
    case Opcode::kProjection:
      return VisitProjection(node);
    case Opcode::kDeoptimizeIf:
      return VisitDeoptimizeIf(node);
#if V8_ENABLE_WEBASSEMBLY
    case Opcode::kTrapIf:
      return VisitTrapIf(node);
#endif // V8_ENABLE_WEBASSEMBLY
    case Opcode::kCatchBlockBegin:
      MarkAsTagged(node);
      return VisitIfException(node);
    case Opcode::kRetain:
      return VisitRetain(node);
    case Opcode::kOsrValue:
      MarkAsTagged(node);
      return VisitOsrValue(node);
    case Opcode::kStackSlot:
      return VisitStackSlot(node);
    case Opcode::kFrameState:
      // FrameState is covered as part of calls.
      UNREACHABLE();
    case Opcode::kLoadRootRegister:
      return VisitLoadRootRegister(node);
    case Opcode::kAssumeMap:
      // AssumeMap is used as a hint for optimization phases but does not
      // produce any code.
      return;
    case Opcode::kDebugBreak:
      return VisitDebugBreak(node);
    case Opcode::kAbortCSADcheck:
      return VisitAbortCSADcheck(node);
    case Opcode::kSelect: {
      const SelectOp& select = op.Cast<SelectOp>();
      // If there is a Select, then it should only be one that is supported by
      // the machine, and it should be meant to be implementation with cmove.
      DCHECK_EQ(select.implem, SelectOp::Implementation::kCMove);
      MarkAsRepresentation(select.rep, node);
      return VisitSelect(node);
    }
    case Opcode::kWord32PairBinop: {
      const Word32PairBinopOp& binop = op.Cast<Word32PairBinopOp>();
      MarkAsWord32(node);
      MarkPairProjectionsAsWord32(node);
      switch (binop.kind) {
        case Word32PairBinopOp::Kind::kAdd:
          return VisitInt32PairAdd(node);
        case Word32PairBinopOp::Kind::kSub:
          return VisitInt32PairSub(node);
        case Word32PairBinopOp::Kind::kMul:
          return VisitInt32PairMul(node);
        case Word32PairBinopOp::Kind::kShiftLeft:
          return VisitWord32PairShl(node);
        case Word32PairBinopOp::Kind::kShiftRightLogical:
          return VisitWord32PairShr(node);
        case Word32PairBinopOp::Kind::kShiftRightArithmetic:
          return VisitWord32PairSar(node);
      }
      UNREACHABLE();
    }
    case Opcode::kAtomicWord32Pair: {
      const AtomicWord32PairOp& atomic_op = op.Cast<AtomicWord32PairOp>();
      if (atomic_op.kind != AtomicWord32PairOp::Kind::kStore) {
        MarkAsWord32(node);
        MarkPairProjectionsAsWord32(node);
      }
      switch (atomic_op.kind) {
        case AtomicWord32PairOp::Kind::kAdd:
          return VisitWord32AtomicPairAdd(node);
        case AtomicWord32PairOp::Kind::kAnd:
          return VisitWord32AtomicPairAnd(node);
        case AtomicWord32PairOp::Kind::kCompareExchange:
          return VisitWord32AtomicPairCompareExchange(node);
        case AtomicWord32PairOp::Kind::kExchange:
          return VisitWord32AtomicPairExchange(node);
        case AtomicWord32PairOp::Kind::kLoad:
          return VisitWord32AtomicPairLoad(node);
        case AtomicWord32PairOp::Kind::kOr:
          return VisitWord32AtomicPairOr(node);
        case AtomicWord32PairOp::Kind::kSub:
          return VisitWord32AtomicPairSub(node);
        case AtomicWord32PairOp::Kind::kXor:
          return VisitWord32AtomicPairXor(node);
        case AtomicWord32PairOp::Kind::kStore:
          return VisitWord32AtomicPairStore(node);
      }
    }
    case Opcode::kBitcastWord32PairToFloat64:
      return MarkAsFloat64(node), VisitBitcastWord32PairToFloat64(node);
    case Opcode::kAtomicRMW: {
      const AtomicRMWOp& atomic_op = op.Cast<AtomicRMWOp>();
      MarkAsRepresentation(atomic_op.memory_rep.ToRegisterRepresentation(),
                           node);
      if (atomic_op.in_out_rep == Rep::Word32()) {
        switch (atomic_op.bin_op) {
          case AtomicRMWOp::BinOp::kAdd:
            return VisitWord32AtomicAdd(node);
          case AtomicRMWOp::BinOp::kSub:
            return VisitWord32AtomicSub(node);
          case AtomicRMWOp::BinOp::kAnd:
            return VisitWord32AtomicAnd(node);
          case AtomicRMWOp::BinOp::kOr:
            return VisitWord32AtomicOr(node);
          case AtomicRMWOp::BinOp::kXor:
            return VisitWord32AtomicXor(node);
          case AtomicRMWOp::BinOp::kExchange:
            return VisitWord32AtomicExchange(node);
          case AtomicRMWOp::BinOp::kCompareExchange:
            return VisitWord32AtomicCompareExchange(node);
        }
      } else if (atomic_op.in_out_rep == Rep::Word64()) {
        switch (atomic_op.bin_op) {
          case AtomicRMWOp::BinOp::kAdd:
            return VisitWord64AtomicAdd(node);
          case AtomicRMWOp::BinOp::kSub:
            return VisitWord64AtomicSub(node);
          case AtomicRMWOp::BinOp::kAnd:
            return VisitWord64AtomicAnd(node);
          case AtomicRMWOp::BinOp::kOr:
            return VisitWord64AtomicOr(node);
          case AtomicRMWOp::BinOp::kXor:
            return VisitWord64AtomicXor(node);
          case AtomicRMWOp::BinOp::kExchange:
            return VisitWord64AtomicExchange(node);
          case AtomicRMWOp::BinOp::kCompareExchange:
            return VisitWord64AtomicCompareExchange(node);
        }
      } else {
        CHECK_EQ(atomic_op.in_out_rep, Rep::Tagged());
        CHECK_EQ(atomic_op.bin_op, AtomicRMWOp::BinOp::kExchange);
        return VisitTaggedAtomicExchange(node);
      }
      UNREACHABLE();
    }
    case Opcode::kMemoryBarrier:
      return VisitMemoryBarrier(node);
    case Opcode::kComment:
      return VisitComment(node);
#ifdef V8_ENABLE_WEBASSEMBLY
    case Opcode::kSimd128Constant: {
      const Simd128ConstantOp& constant = op.Cast<Simd128ConstantOp>();
      MarkAsSimd128(node);
      if (constant.IsZero()) return VisitS128Zero(node);
      return VisitS128Const(node);
    }
    case Opcode::kSimd128Unary: {
      const Simd128UnaryOp& unary = op.Cast<Simd128UnaryOp>();
      MarkAsSimd128(node);
      switch (unary.kind) {
#define VISIT_SIMD_UNARY(kind) \
  case Simd128UnaryOp::Kind::k##kind: \
    return Visit##kind(node);
        FOREACH_SIMD_128_UNARY_OPCODE(VISIT_SIMD_UNARY)
#undef VISIT_SIMD_UNARY
      }
    }
    case Opcode::kSimd128Reduce: {
      const Simd128ReduceOp& reduce = op.Cast<Simd128ReduceOp>();
      MarkAsSimd128(node);
      switch (reduce.kind) {
        case Simd128ReduceOp::Kind::kI8x16AddReduce:
          return VisitI8x16AddReduce(node);
        case Simd128ReduceOp::Kind::kI16x8AddReduce:
          return VisitI16x8AddReduce(node);
        case Simd128ReduceOp::Kind::kI32x4AddReduce:
          return VisitI32x4AddReduce(node);
        case Simd128ReduceOp::Kind::kI64x2AddReduce:
          return VisitI64x2AddReduce(node);
        case Simd128ReduceOp::Kind::kF32x4AddReduce:
          return VisitF32x4AddReduce(node);
        case Simd128ReduceOp::Kind::kF64x2AddReduce:
          return VisitF64x2AddReduce(node);
      }
    }
    case Opcode::kSimd128Binop: {
      const Simd128BinopOp& binop = op.Cast<Simd128BinopOp>();
      MarkAsSimd128(node);
      switch (binop.kind) {
#define VISIT_SIMD_BINOP(kind) \
  case Simd128BinopOp::Kind::k##kind: \
    return Visit##kind(node);
        FOREACH_SIMD_128_BINARY_OPCODE(VISIT_SIMD_BINOP)
#undef VISIT_SIMD_BINOP
      }
    }
    case Opcode::kSimd128Shift: {
      const Simd128ShiftOp& shift = op.Cast<Simd128ShiftOp>();
      MarkAsSimd128(node);
      switch (shift.kind) {
#define VISIT_SIMD_SHIFT(kind) \
  case Simd128ShiftOp::Kind::k##kind: \
    return Visit##kind(node);
        FOREACH_SIMD_128_SHIFT_OPCODE(VISIT_SIMD_SHIFT)
#undef VISIT_SIMD_SHIFT
      }
    }
    case Opcode::kSimd128Test: {
      const Simd128TestOp& test = op.Cast<Simd128TestOp>();
      MarkAsWord32(node);
      switch (test.kind) {
#define VISIT_SIMD_TEST(kind) \
  case Simd128TestOp::Kind::k##kind: \
    return Visit##kind(node);
        FOREACH_SIMD_128_TEST_OPCODE(VISIT_SIMD_TEST)
#undef VISIT_SIMD_TEST
      }
    }
    case Opcode::kSimd128Splat: {
      const Simd128SplatOp& splat = op.Cast<Simd128SplatOp>();
      MarkAsSimd128(node);
      switch (splat.kind) {
#define VISIT_SIMD_SPLAT(kind) \
  case Simd128SplatOp::Kind::k##kind: \
    return Visit##kind##Splat(node);
        FOREACH_SIMD_128_SPLAT_OPCODE(VISIT_SIMD_SPLAT)
#undef VISIT_SIMD_SPLAT
      }
    }
    case Opcode::kSimd128Shuffle: {
      MarkAsSimd128(node);
      const Simd128ShuffleOp& shuffle = op.Cast<Simd128ShuffleOp>();
      switch (shuffle.kind) {
        case Simd128ShuffleOp::Kind::kI8x2:
          return VisitI8x2Shuffle(node);
        case Simd128ShuffleOp::Kind::kI8x4:
          return VisitI8x4Shuffle(node);
        case Simd128ShuffleOp::Kind::kI8x8:
          return VisitI8x8Shuffle(node);
        case Simd128ShuffleOp::Kind::kI8x16:
          return VisitI8x16Shuffle(node);
      }
    }
    case Opcode::kSimd128ReplaceLane: {
      const Simd128ReplaceLaneOp& replace = op.Cast<Simd128ReplaceLaneOp>();
      MarkAsSimd128(node);
      switch (replace.kind) {
        case Simd128ReplaceLaneOp::Kind::kI8x16:
          return VisitI8x16ReplaceLane(node);
        case Simd128ReplaceLaneOp::Kind::kI16x8:
          return VisitI16x8ReplaceLane(node);
        case Simd128ReplaceLaneOp::Kind::kI32x4:
          return VisitI32x4ReplaceLane(node);
        case Simd128ReplaceLaneOp::Kind::kI64x2:
          return VisitI64x2ReplaceLane(node);
        case Simd128ReplaceLaneOp::Kind::kF16x8:
          return VisitF16x8ReplaceLane(node);
        case Simd128ReplaceLaneOp::Kind::kF32x4:
          return VisitF32x4ReplaceLane(node);
        case Simd128ReplaceLaneOp::Kind::kF64x2:
          return VisitF64x2ReplaceLane(node);
      }
    }
    case Opcode::kSimd128ExtractLane: {
      const Simd128ExtractLaneOp& extract = op.Cast<Simd128ExtractLaneOp>();
      switch (extract.kind) {
        case Simd128ExtractLaneOp::Kind::kI8x16S:
          MarkAsWord32(node);
          return VisitI8x16ExtractLaneS(node);
        case Simd128ExtractLaneOp::Kind::kI8x16U:
          MarkAsWord32(node);
          return VisitI8x16ExtractLaneU(node);
        case Simd128ExtractLaneOp::Kind::kI16x8S:
          MarkAsWord32(node);
          return VisitI16x8ExtractLaneS(node);
        case Simd128ExtractLaneOp::Kind::kI16x8U:
          MarkAsWord32(node);
          return VisitI16x8ExtractLaneU(node);
        case Simd128ExtractLaneOp::Kind::kI32x4:
          MarkAsWord32(node);
          return VisitI32x4ExtractLane(node);
        case Simd128ExtractLaneOp::Kind::kI64x2:
          MarkAsWord64(node);
          return VisitI64x2ExtractLane(node);
        case Simd128ExtractLaneOp::Kind::kF16x8:
          MarkAsFloat32(node);
          return VisitF16x8ExtractLane(node);
        case Simd128ExtractLaneOp::Kind::kF32x4:
          MarkAsFloat32(node);
          return VisitF32x4ExtractLane(node);
        case Simd128ExtractLaneOp::Kind::kF64x2:
          MarkAsFloat64(node);
          return VisitF64x2ExtractLane(node);
      }
    }
    case Opcode::kSimd128LoadTransform:
      MarkAsSimd128(node);
      return VisitLoadTransform(node);
    case Opcode::kSimd128LaneMemory: {
      const Simd128LaneMemoryOp& memory = op.Cast<Simd128LaneMemoryOp>();
      MarkAsSimd128(node);
      if (memory.mode == Simd128LaneMemoryOp::Mode::kLoad) {
        return VisitLoadLane(node);
      } else {
        DCHECK_EQ(memory.mode, Simd128LaneMemoryOp::Mode::kStore);
        return VisitStoreLane(node);
      }
    }
    case Opcode::kSimd128Ternary: {
      const Simd128TernaryOp& ternary = op.Cast<Simd128TernaryOp>();
      MarkAsSimd128(node);
      switch (ternary.kind) {
#define VISIT_SIMD_TERNARY(kind) \
  case Simd128TernaryOp::Kind::k##kind: \
    return Visit##kind(node);
        FOREACH_SIMD_128_TERNARY_OPCODE(VISIT_SIMD_TERNARY)
#undef VISIT_SIMD_TERNARY
      }
    }
#if V8_ENABLE_WASM_DEINTERLEAVED_MEM_OPS
    case Opcode::kSimd128LoadPairDeinterleave: {
      OptionalOpIndex projection0 = FindProjection(node, 0);
      DCHECK(projection0.valid());
      MarkAsSimd128(projection0.value());
      OptionalOpIndex projection1 = FindProjection(node, 1);
      DCHECK(projection1.valid());
      MarkAsSimd128(projection1.value());
      return VisitSimd128LoadPairDeinterleave(node);
    }
#endif // V8_ENABLE_WASM_DEINTERLEAVED_MEM_OPS
    // SIMD256
#if V8_ENABLE_WASM_SIMD256_REVEC
    case Opcode::kSimd256Constant: {
      const Simd256ConstantOp& constant = op.Cast<Simd256ConstantOp>();
      MarkAsSimd256(node);
      if (constant.IsZero()) return VisitS256Zero(node);
      return VisitS256Const(node);
    }
    case Opcode::kSimd256Extract128Lane: {
      MarkAsSimd128(node);
      return VisitExtractF128(node);
    }
    case Opcode::kSimd256LoadTransform: {
      MarkAsSimd256(node);
      return VisitSimd256LoadTransform(node);
    }
    case Opcode::kSimd256Unary: {
      const Simd256UnaryOp& unary = op.Cast<Simd256UnaryOp>();
      MarkAsSimd256(node);
      switch (unary.kind) {
#define VISIT_SIMD_256_UNARY(kind) \
  case Simd256UnaryOp::Kind::k##kind: \
    return Visit##kind(node);
        FOREACH_SIMD_256_UNARY_OPCODE(VISIT_SIMD_256_UNARY)
#undef VISIT_SIMD_256_UNARY
      }
    }
    case Opcode::kSimd256Binop: {
      const Simd256BinopOp& binop = op.Cast<Simd256BinopOp>();
      MarkAsSimd256(node);
      switch (binop.kind) {
#define VISIT_SIMD_BINOP(kind) \
  case Simd256BinopOp::Kind::k##kind: \
    return Visit##kind(node);
        FOREACH_SIMD_256_BINARY_OPCODE(VISIT_SIMD_BINOP)
#undef VISIT_SIMD_BINOP
      }
    }
    case Opcode::kSimd256Shift: {
      const Simd256ShiftOp& shift = op.Cast<Simd256ShiftOp>();
      MarkAsSimd256(node);
      switch (shift.kind) {
#define VISIT_SIMD_SHIFT(kind) \
  case Simd256ShiftOp::Kind::k##kind: \
    return Visit##kind(node);
        FOREACH_SIMD_256_SHIFT_OPCODE(VISIT_SIMD_SHIFT)
#undef VISIT_SIMD_SHIFT
      }
    }
    case Opcode::kSimd256Ternary: {
      const Simd256TernaryOp& ternary = op.Cast<Simd256TernaryOp>();
      MarkAsSimd256(node);
      switch (ternary.kind) {
#define VISIT_SIMD_256_TERNARY(kind) \
  case Simd256TernaryOp::Kind::k##kind: \
    return Visit##kind(node);
        FOREACH_SIMD_256_TERNARY_OPCODE(VISIT_SIMD_256_TERNARY)
#undef VISIT_SIMD_256_UNARY
      }
    }
    case Opcode::kSimd256Splat: {
      const Simd256SplatOp& splat = op.Cast<Simd256SplatOp>();
      MarkAsSimd256(node);
      switch (splat.kind) {
#define VISIT_SIMD_SPLAT(kind) \
  case Simd256SplatOp::Kind::k##kind: \
    return Visit##kind##Splat(node);
        FOREACH_SIMD_256_SPLAT_OPCODE(VISIT_SIMD_SPLAT)
#undef VISIT_SIMD_SPLAT
      }
    }
#ifdef V8_TARGET_ARCH_X64
    case Opcode::kSimd256Shufd: {
      MarkAsSimd256(node);
      return VisitSimd256Shufd(node);
    }
    case Opcode::kSimd256Shufps: {
      MarkAsSimd256(node);
      return VisitSimd256Shufps(node);
    }
    case Opcode::kSimd256Unpack: {
      MarkAsSimd256(node);
      return VisitSimd256Unpack(node);
    }
    case Opcode::kSimdPack128To256: {
      MarkAsSimd256(node);
      return VisitSimdPack128To256(node);
    }
#endif // V8_TARGET_ARCH_X64
#endif // V8_ENABLE_WASM_SIMD256_REVEC
    case Opcode::kLoadStackPointer:
      return VisitLoadStackPointer(node);
    case Opcode::kSetStackPointer:
      this->frame_->set_invalidates_sp();
      return VisitSetStackPointer(node);
#endif // V8_ENABLE_WEBASSEMBLY
#define UNREACHABLE_CASE(op) case Opcode::k##op:
      TURBOSHAFT_JS_OPERATION_LIST(UNREACHABLE_CASE)
      TURBOSHAFT_SIMPLIFIED_OPERATION_LIST(UNREACHABLE_CASE)
      TURBOSHAFT_WASM_OPERATION_LIST(UNREACHABLE_CASE)
      TURBOSHAFT_OTHER_OPERATION_LIST(UNREACHABLE_CASE)
      UNREACHABLE_CASE(PendingLoopPhi)
      UNREACHABLE_CASE(Tuple)
      UNREACHABLE_CASE(Dead)
      UNREACHABLE();
#undef UNREACHABLE_CASE
  }
}
References v8::internal::A, AlignmentRequirements(), v8::internal::compiler::turboshaft::ChangeOp::assumption, v8::internal::compiler::turboshaft::Block::begin(), v8::internal::compiler::turboshaft::AtomicRMWOp::bin_op, block(), v8::internal::compiler::turboshaft::Operation::Cast(), CHECK_EQ, COMPRESS_POINTERS_BOOL, current_block_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_LE, v8::internal::compiler::OperandGenerator::DefineAsRegister(), Emit(), EmitIdentity(), FindProjection(), frame_, v8::internal::compiler::turboshaft::ChangeOp::from, v8::internal::compiler::turboshaft::TryChangeOp::from, v8::internal::compiler::turboshaft::TaggedBitcastOp::from, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::Float64::get_scalar(), v8::internal::compiler::Linkage::GetParameterType(), v8::internal::compiler::turboshaft::SelectOp::implem, v8::internal::compiler::turboshaft::AtomicRMWOp::in_out_rep, v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::Is64(), v8::internal::compiler::turboshaft::LoadOp::Kind::is_atomic, v8::internal::is_signed(), v8::internal::compiler::turboshaft::Operation::IsBlockTerminator(), v8::internal::IsSmiDouble(), v8::internal::compiler::MachineOperatorBuilder::AlignmentRequirements::IsUnalignedLoadSupported(), v8::internal::compiler::turboshaft::kBranch, v8::internal::compiler::anonymous_namespace{gap-resolver.cc}::kConstant, v8::internal::kEqual, v8::internal::compiler::turboshaft::WordBinopOp::kind, v8::internal::compiler::turboshaft::Word32PairBinopOp::kind, v8::internal::compiler::turboshaft::WordUnaryOp::kind, v8::internal::compiler::turboshaft::ComparisonOp::kind, v8::internal::compiler::turboshaft::ChangeOp::kind, v8::internal::compiler::turboshaft::TryChangeOp::kind, v8::internal::compiler::turboshaft::TaggedBitcastOp::kind, v8::internal::compiler::turboshaft::ConstantOp::kind, v8::internal::compiler::turboshaft::LoadOp::kind, v8::internal::compiler::turboshaft::AtomicWord32PairOp::kind, v8::kLog, v8::internal::kNoOverflow, v8::internal::compiler::kNoWriteBarrier, v8::internal::kRoundDown, v8::internal::kRoundToZero, v8::internal::kRoundUp, v8::internal::compiler::kSignedLessThan, v8::internal::compiler::kSignedLessThanOrEqual, v8::internal::compiler::kSmi, v8::internal::wasm::kSwitch, v8::internal::kTaggedSigned, v8::internal::kTaggedSize, v8::internal::wasm::kTailCall, v8::internal::wasm::kUnreachable, v8::internal::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, v8::internal::kWord8, v8::internal::compiler::turboshaft::Block::LastOperation(), v8::internal::compiler::turboshaft::Block::LastPredecessor(), linkage(), v8::internal::compiler::turboshaft::MaybeRegisterRepresentation::machine_representation(), v8::internal::compiler::turboshaft::LoadOp::machine_type(), MarkAsCompressed(), MarkAsFloat32(), MarkAsFloat64(), MarkAsRepresentation(), MarkAsSimd128(), MarkAsSimd256(), MarkAsTagged(), MarkAsWord32(), MarkAsWord64(), MarkPairProjectionsAsWord32(), v8::internal::compiler::turboshaft::LoadOp::Kind::maybe_unaligned, v8::internal::compiler::turboshaft::AtomicRMWOp::memory_rep, v8::internal::compiler::turboshaft::multi(), v8::internal::compiler::turboshaft::ConstantOp::number(), v8::internal::compiler::turboshaft::Operation::opcode, v8::internal::compiler::turboshaft::ParameterOp::parameter_index, v8::internal::compiler::turboshaft::Block::PredecessorCount(), v8::internal::compiler::turboshaft::OperationMatcher::rep, v8::internal::compiler::turboshaft::WordBinopOp::rep, v8::internal::compiler::turboshaft::WordUnaryOp::rep, v8::internal::compiler::turboshaft::ComparisonOp::rep, v8::internal::compiler::turboshaft::SelectOp::rep, v8::internal::compiler::turboshaft::PhiOp::rep, v8::internal::compiler::turboshaft::LoadOp::result_rep, rpo_number(), schedule(), v8::internal::compiler::Frame::set_invalidates_sp(), v8::internal::SmiValuesAre31Bits(), store(), v8::internal::Tagged(), v8::internal::this, v8::internal::compiler::turboshaft::DidntThrowOp::throwing_operation(), tick_counter_, v8::internal::TickCounter::TickAndMaybeEnterSafepoint(), v8::internal::compiler::turboshaft::ChangeOp::to, v8::internal::compiler::turboshaft::TryChangeOp::to, v8::internal::compiler::turboshaft::TaggedBitcastOp::to, v8::internal::anonymous_namespace{temporal-parser.cc}::ToInt(), v8::internal::compiler::turboshaft::MemoryRepresentation::ToRegisterRepresentation(), TURBOSHAFT_JS_OPERATION_LIST, TURBOSHAFT_OTHER_OPERATION_LIST, TURBOSHAFT_SIMPLIFIED_OPERATION_LIST, TURBOSHAFT_WASM_OPERATION_LIST, v8::internal::tracing::type, v8::internal::compiler::UNIMPLEMENTED(), v8::internal::UNREACHABLE(), UNREACHABLE_CASE, v8::internal::compiler::turboshaft::OptionalOpIndex::valid(), v8::internal::compiler::turboshaft::OptionalOpIndex::value(), VisitBitcastWord32PairToFloat64(), VisitCall(), VisitConstant(), VisitDeoptimizeIf(), VisitIfException(), VisitLoad(), VisitOsrValue(), VisitParameter(), VisitPhi(), VisitProjection(), VisitRetain(), VisitSelect(), VisitStackPointerGreaterThan(), VisitTrapIf(), v8::internal::compiler::turboshaft::LoadOp::Kind::with_trap_handler, v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), v8::internal::compiler::turboshaft::WordRepresentation::Word32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word64(), and v8::internal::compiler::turboshaft::WordRepresentation::Word64().
Referenced by VisitBlock().
VisitOsrValue()
void v8::internal::compiler::InstructionSelector::VisitOsrValue (turboshaft::OpIndex node) [private]
Definition at line 1997 of file instruction-selector.cc.
                                                    {
  const OsrValueOp& osr_value = Cast<OsrValueOp>(node);
  OperandGenerator g(this);
  Emit(kArchNop, g.DefineAsLocation(
                     node, linkage()->GetOsrValueLocation(osr_value.index)));
}
References v8::internal::compiler::OperandGenerator::DefineAsLocation(), Emit(), v8::internal::compiler::turboshaft::OsrValueOp::index, and linkage().
Referenced by VisitNode().
VisitParameter()
void v8::internal::compiler::InstructionSelector::VisitParameter (turboshaft::OpIndex node) [private]
Definition at line 1956 of file instruction-selector.cc.
                                                     {
  const ParameterOp& parameter = Cast<ParameterOp>(node);
  const int index = parameter.parameter_index;
  OperandGenerator g(this);
  if (linkage()->GetParameterLocation(index).IsNullRegister()) {
    EmitMoveParamToFPR(node, index);
  } else {
    InstructionOperand op =
        linkage()->ParameterHasSecondaryLocation(index)
            ? g.DefineAsDualLocation(
                  node, linkage()->GetParameterLocation(index),
                  linkage()->GetParameterSecondaryLocation(index))
            : g.DefineAsLocation(node, linkage()->GetParameterLocation(index));
    Emit(kArchNop, op);
  }
}
References v8::internal::compiler::OperandGenerator::DefineAsDualLocation(), v8::internal::compiler::OperandGenerator::DefineAsLocation(), Emit(), EmitMoveParamToFPR(), v8::internal::index, linkage(), v8::internal::compiler::turboshaft::ParameterOp::parameter_index, and v8::internal::compiler::Linkage::ParameterHasSecondaryLocation().
Referenced by VisitNode().
VisitPhi()
void v8::internal::compiler::InstructionSelector::VisitPhi (turboshaft::OpIndex node) [private]
Definition at line 2004 of file instruction-selector.cc.
                                               {
  const Operation& op = Get(node);
  DCHECK_EQ(op.input_count, PredecessorCount(current_block_));
  PhiInstruction* phi = instruction_zone()->template New<PhiInstruction>(
      instruction_zone(), GetVirtualRegister(node),
      static_cast<size_t>(op.input_count));
  sequence()->InstructionBlockAt(rpo_number(current_block_))->AddPhi(phi);
  for (size_t i = 0; i < op.input_count; ++i) {
    OpIndex input = op.input(i);
    MarkAsUsed(input);
    phi->SetInput(i, GetVirtualRegister(input));
  }
}
References v8::internal::compiler::InstructionBlock::AddPhi(), current_block_, DCHECK_EQ, v8::internal::compiler::turboshaft::OperationMatcher::Get(), GetVirtualRegister(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::Operation::input(), v8::internal::compiler::turboshaft::Operation::input_count, instruction_zone(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), MarkAsUsed(), PredecessorCount(), rpo_number(), sequence(), and v8::internal::compiler::PhiInstruction::SetInput().
Referenced by VisitNode().
VisitProjection()
void v8::internal::compiler::InstructionSelector::VisitProjection (turboshaft::OpIndex node) [private]
Definition at line 2018 of file instruction-selector.cc.
                                                      {
  const ProjectionOp& projection = this->Get(node).Cast<ProjectionOp>();
  const Operation& value_op = this->Get(projection.input());
  if (value_op.Is<OverflowCheckedBinopOp>() ||
      value_op.Is<OverflowCheckedUnaryOp>() || value_op.Is<TryChangeOp>() ||
      value_op.Is<Word32PairBinopOp>()) {
    if (projection.index == 0u) {
      EmitIdentity(node);
    } else {
      DCHECK_EQ(1u, projection.index);
      MarkAsUsed(projection.input());
    }
  } else if (value_op.Is<DidntThrowOp>()) {
    // Nothing to do here?
  } else if (value_op.Is<CallOp>()) {
    // Call projections need to be behind the call's DidntThrow.
    UNREACHABLE();
  } else if (value_op.Is<AtomicWord32PairOp>()) {
    // Nothing to do here.
#if V8_ENABLE_WASM_DEINTERLEAVED_MEM_OPS
  } else if (value_op.Is<Simd128LoadPairDeinterleaveOp>()) {
    MarkAsUsed(projection.input());
#endif // V8_ENABLE_WASM_DEINTERLEAVED_MEM_OPS
  } else {
    UNIMPLEMENTED();
  }
}
References v8::internal::compiler::turboshaft::Operation::Cast(), DCHECK_EQ, EmitIdentity(), v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::ProjectionOp::index, v8::internal::compiler::turboshaft::ProjectionOp::input(), v8::internal::compiler::turboshaft::Operation::Is(), MarkAsUsed(), v8::internal::compiler::UNIMPLEMENTED(), and v8::internal::UNREACHABLE().
Referenced by CanDoBranchIfOverflowFusion(), TryPrepareScheduleFirstProjection(), and VisitNode().
VisitRetain()
void v8::internal::compiler::InstructionSelector::VisitRetain (turboshaft::OpIndex node) [private]
Definition at line 2596 of file instruction-selector.cc.
                                                  {
  const RetainOp& retain = Cast<RetainOp>(node);
  OperandGenerator g(this);
  DCHECK_EQ(retain.input_count, 1);
  Emit(kArchNop, g.NoOutput(), g.UseAny(retain.retained()));
}
References DCHECK_EQ, Emit(), v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::input_count, v8::internal::compiler::OperandGenerator::NoOutput(), v8::internal::compiler::turboshaft::RetainOp::retained(), and v8::internal::compiler::OperandGenerator::UseAny().
Referenced by VisitNode().
VisitReturn()
void v8::internal::compiler::InstructionSelector::VisitReturn (turboshaft::OpIndex node) [private]
Definition at line 2371 of file instruction-selector.cc.
                                                  {
  const ReturnOp& ret = schedule()->Get(node).Cast<ReturnOp>();
  OperandGenerator g(this);
  const size_t return_count = linkage()->GetIncomingDescriptor()->ReturnCount();
  const int input_count =
      return_count == 0 ? 1
                        : (1 + static_cast<int>(ret.return_values().size()));
  DCHECK_GE(input_count, 1);
  auto value_locations =
      zone()->template AllocateArray<InstructionOperand>(input_count);
  const Operation& pop_count = schedule()->Get(ret.pop_count());
  if (pop_count.Is<Opmask::kWord32Constant>() ||
      pop_count.Is<Opmask::kWord64Constant>()) {
    value_locations[0] = g.UseImmediate(ret.pop_count());
  } else {
    value_locations[0] = g.UseRegister(ret.pop_count());
  }
  for (size_t i = 0, return_value_idx = 0; i < return_count; ++i) {
    LinkageLocation loc = linkage()->GetReturnLocation(i);
    // Return values passed via frame slots have already been stored
    // on the stack by the GrowableStacksReducer.
    if (loc.IsCallerFrameSlot() && ret.spill_caller_frame_slots) {
      continue;
    }
    value_locations[return_value_idx + 1] =
        g.UseLocation(ret.return_values()[return_value_idx], loc);
    return_value_idx++;
  }
  Emit(kArchRet, 0, nullptr, input_count, value_locations);
}
References v8::internal::compiler::turboshaft::Operation::Cast(), DCHECK_GE, Emit(), v8::internal::compiler::turboshaft::Graph::Get(), v8::internal::compiler::Linkage::GetIncomingDescriptor(), v8::internal::compiler::Linkage::GetReturnLocation(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::Operation::Is(), linkage(), v8::internal::loc, v8::internal::compiler::turboshaft::ReturnOp::pop_count(), v8::internal::compiler::turboshaft::ReturnOp::return_values(), v8::internal::compiler::CallDescriptor::ReturnCount(), schedule(), v8::internal::compiler::turboshaft::ReturnOp::spill_caller_frame_slots, and zone().
Referenced by VisitControl().
VisitSelect()
void v8::internal::compiler::InstructionSelector::VisitSelect (turboshaft::OpIndex node) [private]
Definition at line 2522 of file instruction-selector.cc.
                                                  {
  const SelectOp& select = Cast<SelectOp>(node);
  DCHECK_EQ(select.input_count, 3);
  FlagsContinuation cont = FlagsContinuation::ForSelect(
      kNotEqual, node, select.vtrue(), select.vfalse());
  VisitWordCompareZero(node, select.cond(), &cont);
}
References v8::internal::compiler::turboshaft::SelectOp::cond(), DCHECK_EQ, v8::internal::compiler::FlagsContinuation::ForSelect(), v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::input_count, v8::internal::compiler::kNotEqual, v8::internal::compiler::turboshaft::SelectOp::vfalse(), VisitWordCompareZero(), and v8::internal::compiler::turboshaft::SelectOp::vtrue().
Referenced by VisitNode().
VisitStackPointerGreaterThan()
void v8::internal::compiler::InstructionSelector::VisitStackPointerGreaterThan (turboshaft::OpIndex node, FlagsContinuation * cont) [private]
Definition at line 1188 of file instruction-selector-arm.cc.
                                           {
  StackCheckKind kind;
  OpIndex value;
  const auto& op = this->turboshaft_graph()
                       ->Get(node)
                       .template Cast<StackPointerGreaterThanOp>();
  kind = op.kind;
  value = op.stack_limit();
  InstructionCode opcode =
      kArchStackPointerGreaterThan |
      StackCheckField::encode(static_cast<StackCheckKind>(kind));
  ArmOperandGenerator g(this);
  // No outputs.
  InstructionOperand* const outputs = nullptr;
  const int output_count = 0;
  // Applying an offset to this stack check requires a temp register. Offsets
  // are only applied to the first stack check. If applying an offset, we must
  // ensure the input and temp registers do not alias, thus kUniqueRegister.
  InstructionOperand temps[] = {g.TempRegister()};
  const int temp_count = (kind == StackCheckKind::kJSFunctionEntry) ? 1 : 0;
  const auto register_mode = (kind == StackCheckKind::kJSFunctionEntry)
                                 ? OperandGenerator::kUniqueRegister
                                 : OperandGenerator::kRegister;
  InstructionOperand inputs[] = {g.UseRegisterWithMode(value, register_mode)};
  static constexpr int input_count = arraysize(inputs);
  EmitWithContinuation(opcode, output_count, outputs, input_count, inputs,
                       temp_count, temps, cont);
}
References arraysize, v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::kJSFunctionEntry, v8::internal::compiler::OperandGenerator::kRegister, v8::internal::compiler::OperandGenerator::kUniqueRegister, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseRegisterWithMode(), and v8::internal::value.
Referenced by VisitNode().
VisitStaticAssert()
void v8::internal::compiler::InstructionSelector::VisitStaticAssert (turboshaft::OpIndex node) [private]
Definition at line 2571 of file instruction-selector.cc.
                                                        {
  const StaticAssertOp& op = Cast<StaticAssertOp>(node);
  DCHECK_EQ(op.input_count, 1);
  OpIndex asserted = op.condition();
  UnparkedScopeIfNeeded scope(broker_);
  AllowHandleDereference allow_handle_dereference;
    StdoutStream os;
    os << Get(asserted);
    FATAL(
        "Expected Turbofan static assert to hold, but got non-true input:\n "
        "%s",
        op.source);
}
References broker_, v8::internal::compiler::turboshaft::StaticAssertOp::condition(), DCHECK_EQ, FATAL, v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::turboshaft::FixedArityOperationT< InputCount, Derived >::input_count, and v8::internal::compiler::turboshaft::StaticAssertOp::source.
Referenced by VisitControl().
VisitSwitch()
void v8::internal::compiler::InstructionSelector::VisitSwitch (turboshaft::OpIndex node, const SwitchInfo & sw) [private]
Definition at line 2248 of file instruction-selector-arm.cc.
                                                                        {
  ArmOperandGenerator g(this);
  InstructionOperand value_operand =
      g.UseRegister(Cast<SwitchOp>(node).input());
  // Emit either ArchTableSwitch or ArchBinarySearchSwitch.
  if (enable_switch_jump_table_) {
    static const size_t kMaxTableSwitchValueRange = 2 << 16;
    size_t table_space_cost = 4 + sw.value_range();
    size_t table_time_cost = 3;
    size_t lookup_space_cost = 3 + 2 * sw.case_count();
    size_t lookup_time_cost = sw.case_count();
    if (sw.case_count() > 0 &&
        table_space_cost + 3 * table_time_cost <=
            lookup_space_cost + 3 * lookup_time_cost &&
        sw.min_value() > std::numeric_limits<int32_t>::min() &&
        sw.value_range() <= kMaxTableSwitchValueRange) {
      InstructionOperand index_operand = value_operand;
      if (sw.min_value()) {
        index_operand = g.TempRegister();
        Emit(kArmSub | AddressingModeField::encode(kMode_Operand2_I),
             index_operand, value_operand, g.TempImmediate(sw.min_value()));
      }
      // Generate a table lookup.
      return EmitTableSwitch(sw, index_operand);
    }
  }
  // Generate a tree of conditional jumps.
  return EmitBinarySearchSwitch(sw, value_operand);
}
References v8::internal::compiler::SwitchInfo::case_count(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::SwitchInfo::min_value(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::OperandGenerator::UseRegister(), and v8::internal::compiler::SwitchInfo::value_range().
Referenced by VisitControl(), and v8::internal::compiler::VisitWordCompare().
VisitTailCall()
void v8::internal::compiler::InstructionSelector::VisitTailCall (turboshaft::OpIndex call) [private]
Definition at line 2282 of file instruction-selector.cc.
                                                    {
  OperandGenerator g(this);
  const TailCallOp& call_op = Cast<TailCallOp>(node);
  auto caller = linkage()->GetIncomingDescriptor();
  auto callee = call_op.descriptor->descriptor;
  DCHECK(caller->CanTailCall(callee));
  const int stack_param_delta = callee->GetStackParameterDelta(caller);
  CallBuffer buffer(zone(), callee, nullptr);
  // Compute InstructionOperands for inputs and outputs.
  CallBufferFlags flags(kCallCodeImmediate | kCallTail);
  if (IsTailCallAddressImmediate()) {
    flags |= kCallAddressImmediate;
  }
  if (callee->flags() & CallDescriptor::kFixedTargetRegister) {
    flags |= kCallFixedTargetRegister;
  }
  InitializeCallBuffer(node, &buffer, flags, call_op.callee(),
                       OptionalOpIndex::Nullopt(), call_op.arguments(),
                       static_cast<int>(call_op.outputs_rep().size()),
                       stack_param_delta);
  UpdateMaxPushedArgumentCount(stack_param_delta);
  // Select the appropriate opcode based on the call type.
  InstructionCode opcode;
  InstructionOperandVector temps(zone());
  switch (callee->kind()) {
    case CallDescriptor::kCallCodeObject:
      opcode = kArchTailCallCodeObject;
      break;
    case CallDescriptor::kCallAddress:
      DCHECK(!caller->IsJSFunctionCall());
      opcode = kArchTailCallAddress;
      break;
#if V8_ENABLE_WEBASSEMBLY
    case CallDescriptor::kCallWasmFunction:
      DCHECK(!caller->IsJSFunctionCall());
      DCHECK(this->IsRelocatableWasmConstant(call_op.callee()));
      opcode = kArchTailCallWasm;
      break;
    case CallDescriptor::kCallWasmFunctionIndirect:
      DCHECK(!caller->IsJSFunctionCall());
      DCHECK(!this->IsRelocatableWasmConstant(call_op.callee()));
      opcode = kArchTailCallWasmIndirect;
      break;
#endif // V8_ENABLE_WEBASSEMBLY
    default:
      UNREACHABLE();
  }
  opcode = EncodeCallDescriptorFlags(opcode, callee->flags());
  Emit(kArchPrepareTailCall, g.NoOutput());
#if V8_ENABLE_WEBASSEMBLY
  if (callee->IsIndirectWasmFunctionCall()) {
    buffer.instruction_args.push_back(
        g.UseImmediate64(callee->signature_hash()));
  }
#endif
  if (callee->RequiresEntrypointTagForCall()) {
    buffer.instruction_args.push_back(g.TempImmediate(callee->shifted_tag()));
  }
  // Add an immediate operand that represents the offset to the first slot
  // that is unused with respect to the stack pointer that has been updated
  // for the tail call instruction. Backends that pad arguments can write the
  // padding value at this offset from the stack.
  const int optional_padding_offset =
      callee->GetOffsetToFirstUnusedStackSlot() - 1;
  buffer.instruction_args.push_back(g.TempImmediate(optional_padding_offset));
  const int first_unused_slot_offset =
      kReturnAddressStackSlotCount + stack_param_delta;
  buffer.instruction_args.push_back(g.TempImmediate(first_unused_slot_offset));
  // Emit the tailcall instruction.
  Emit(opcode, 0, nullptr, buffer.instruction_args.size(),
       &buffer.instruction_args.front(), temps.size(),
       temps.empty() ? nullptr : &temps.front());
}
References v8::internal::compiler::turboshaft::TailCallOp::arguments(), v8::internal::compiler::turboshaft::TailCallOp::callee(), v8::internal::DCHECK(), v8::internal::compiler::turboshaft::TSCallDescriptor::descriptor, v8::internal::compiler::turboshaft::TailCallOp::descriptor, Emit(), v8::internal::ZoneVector< T >::empty(), v8::internal::compiler::anonymous_namespace{instruction-selector.cc}::EncodeCallDescriptorFlags(), v8::internal::flags, v8::internal::ZoneVector< T >::front(), v8::internal::compiler::Linkage::GetIncomingDescriptor(), InitializeCallBuffer(), v8::internal::compiler::CallBuffer::instruction_args, IsRelocatableWasmConstant(), IsTailCallAddressImmediate(), v8::internal::compiler::CallDescriptor::kCallAddress, kCallAddressImmediate, kCallCodeImmediate, v8::internal::compiler::CallDescriptor::kCallCodeObject, kCallFixedTargetRegister, kCallTail, v8::internal::compiler::CallDescriptor::kFixedTargetRegister, kReturnAddressStackSlotCount, linkage(), v8::internal::compiler::OperandGenerator::NoOutput(), v8::internal::compiler::turboshaft::OptionalOpIndex::Nullopt(), v8::internal::compiler::turboshaft::TailCallOp::outputs_rep(), v8::internal::ZoneVector< T >::push_back(), v8::internal::ZoneVector< T >::size(), v8::internal::compiler::OperandGenerator::TempImmediate(), v8::internal::UNREACHABLE(), UpdateMaxPushedArgumentCount(), v8::internal::compiler::OperandGenerator::UseImmediate64(), and zone().
Referenced by VisitControl().
VisitTrapIf()
void v8::internal::compiler::InstructionSelector::VisitTrapIf (turboshaft::OpIndex node) [private]
Definition at line 2530 of file instruction-selector.cc.
                                                  {
#if V8_ENABLE_WEBASSEMBLY
  const TrapIfOp& trap_if = Cast<TrapIfOp>(node);
  // FrameStates are only used for wasm traps inlined in JS. In that case the
  // trap node will be lowered (replaced) before instruction selection.
  // Therefore any TrapIf node has only one input.
  DCHECK_EQ(trap_if.input_count, 1);
  FlagsContinuation cont = FlagsContinuation::ForTrap(
      trap_if.negated ? kEqual : kNotEqual, trap_if.trap_id);
  VisitWordCompareZero(node, trap_if.condition(), &cont);
#else
  UNREACHABLE();
#endif
}
References DCHECK_EQ, v8::internal::compiler::FlagsContinuation::ForTrap(), v8::internal::compiler::kEqual, v8::internal::compiler::kNotEqual, v8::internal::UNREACHABLE(), and VisitWordCompareZero().
Referenced by VisitNode().
VisitUnreachable()
void v8::internal::compiler::InstructionSelector::VisitUnreachable (turboshaft::OpIndex node) [private]
Definition at line 2566 of file instruction-selector.cc.
                                                       {
  OperandGenerator g(this);
  Emit(kArchDebugBreak, g.NoOutput());
}
References Emit(), and v8::internal::compiler::OperandGenerator::NoOutput().
Referenced by VisitControl().
VisitWord32AtomicBinaryOperation()
void v8::internal::compiler::InstructionSelector::VisitWord32AtomicBinaryOperation (turboshaft::OpIndex node, ArchOpcode int8_op, ArchOpcode uint8_op, ArchOpcode int16_op, ArchOpcode uint16_op, ArchOpcode word32_op) [private]
Definition at line 2527 of file instruction-selector-arm.cc.
                                                {
  ArmOperandGenerator g(this);
  const AtomicRMWOp& atomic_op = Cast<AtomicRMWOp>(node);
  ArchOpcode opcode;
  if (atomic_op.memory_rep == MemoryRepresentation::Int8()) {
    opcode = int8_op;
  } else if (atomic_op.memory_rep == MemoryRepresentation::Uint8()) {
    opcode = uint8_op;
  } else if (atomic_op.memory_rep == MemoryRepresentation::Int16()) {
    opcode = int16_op;
  } else if (atomic_op.memory_rep == MemoryRepresentation::Uint16()) {
    opcode = uint16_op;
  } else if (atomic_op.memory_rep == MemoryRepresentation::Int32() ||
             atomic_op.memory_rep == MemoryRepresentation::Uint32()) {
    opcode = word32_op;
  } else {
    UNREACHABLE();
  }
  AddressingMode addressing_mode = kMode_Offset_RR;
  InstructionOperand inputs[3];
  size_t input_count = 0;
  inputs[input_count++] = g.UseRegister(atomic_op.base());
  inputs[input_count++] = g.UseRegister(atomic_op.index());
  inputs[input_count++] = g.UseUniqueRegister(atomic_op.value());
  InstructionOperand outputs[1];
  outputs[0] = g.DefineAsRegister(node);
  InstructionOperand temps[] = {g.TempRegister(), g.TempRegister(),
                                g.TempRegister()};
  InstructionCode code = opcode | AddressingModeField::encode(addressing_mode);
  Emit(code, 1, outputs, input_count, inputs, arraysize(temps), temps);
}
References arraysize, v8::internal::compiler::turboshaft::AtomicRMWOp::base(), code, v8::internal::compiler::OperandGenerator::DefineAsRegister(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::AtomicRMWOp::index(), v8::internal::compiler::turboshaft::detail::input_count(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Int8(), v8::internal::compiler::turboshaft::AtomicRMWOp::memory_rep, v8::internal::compiler::OperandGenerator::TempRegister(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::UNREACHABLE(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::compiler::OperandGenerator::UseUniqueRegister(), and v8::internal::compiler::turboshaft::AtomicRMWOp::value().
VisitWord64AtomicBinaryOperation()
void v8::internal::compiler::InstructionSelector::VisitWord64AtomicBinaryOperation (turboshaft::OpIndex node, ArchOpcode uint8_op, ArchOpcode uint16_op, ArchOpcode uint32_op, ArchOpcode uint64_op) [private]
Definition at line 4526 of file instruction-selector-arm64.cc.
                                                {
  const AtomicRMWOp& atomic_op = this->Get(node).template Cast<AtomicRMWOp>();
  ArchOpcode opcode;
  if (atomic_op.memory_rep == MemoryRepresentation::Uint8()) {
    opcode = uint8_op;
  } else if (atomic_op.memory_rep == MemoryRepresentation::Uint16()) {
    opcode = uint16_op;
  } else if (atomic_op.memory_rep == MemoryRepresentation::Uint32()) {
    opcode = uint32_op;
  } else if (atomic_op.memory_rep == MemoryRepresentation::Uint64()) {
    opcode = uint64_op;
  } else {
    UNREACHABLE();
  }
  VisitAtomicBinop(this, node, opcode, AtomicWidth::kWord64,
                   atomic_op.memory_access_kind);
}
References v8::internal::compiler::turboshaft::OperationMatcher::Get(), v8::internal::compiler::kWord64, v8::internal::compiler::turboshaft::AtomicRMWOp::memory_access_kind, v8::internal::compiler::turboshaft::AtomicRMWOp::memory_rep, v8::internal::compiler::turboshaft::MemoryRepresentation::Uint16(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint32(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint64(), v8::internal::compiler::turboshaft::MemoryRepresentation::Uint8(), v8::internal::UNREACHABLE(), and v8::internal::compiler::VisitAtomicBinop().
VisitWordCompareZero()
void v8::internal::compiler::InstructionSelector::VisitWordCompareZero (turboshaft::OpIndex user, turboshaft::OpIndex value, FlagsContinuation * cont) [private]
Definition at line 2135 of file instruction-selector-arm.cc.
                                                                        {
  // Try to combine with comparisons against 0 by simply inverting the branch.
  ConsumeEqualZero(&user, &value, cont);
  if (CanCover(user, value)) {
    const Operation& value_op = Get(value);
    if (const ComparisonOp* comparison = value_op.TryCast<ComparisonOp>()) {
      switch (comparison->rep.MapTaggedToWord().value()) {
        case RegisterRepresentation::Word32():
          cont->OverwriteAndNegateIfEqual(
              GetComparisonFlagCondition(*comparison));
          return VisitWordCompare(this, value, cont);
        case RegisterRepresentation::Float32():
          switch (comparison->kind) {
            case ComparisonOp::Kind::kEqual:
              cont->OverwriteAndNegateIfEqual(kEqual);
              return VisitFloat32Compare(this, value, cont);
            case ComparisonOp::Kind::kSignedLessThan:
              cont->OverwriteAndNegateIfEqual(kFloatLessThan);
              return VisitFloat32Compare(this, value, cont);
            case ComparisonOp::Kind::kSignedLessThanOrEqual:
              cont->OverwriteAndNegateIfEqual(kFloatLessThanOrEqual);
              return VisitFloat32Compare(this, value, cont);
            default:
              UNREACHABLE();
          }
        case RegisterRepresentation::Float64():
          switch (comparison->kind) {
            case ComparisonOp::Kind::kEqual:
              cont->OverwriteAndNegateIfEqual(kEqual);
              return VisitFloat64Compare(this, value, cont);
            case ComparisonOp::Kind::kSignedLessThan:
              cont->OverwriteAndNegateIfEqual(kFloatLessThan);
              return VisitFloat64Compare(this, value, cont);
            case ComparisonOp::Kind::kSignedLessThanOrEqual:
              cont->OverwriteAndNegateIfEqual(kFloatLessThanOrEqual);
              return VisitFloat64Compare(this, value, cont);
            default:
              UNREACHABLE();
          }
        default:
          break;
      }
    } else if (const ProjectionOp* projection =
                   value_op.TryCast<ProjectionOp>()) {
      // Check if this is the overflow output projection of an
      // <Operation>WithOverflow node.
      if (projection->index == 1u) {
        // We cannot combine the <Operation>WithOverflow with this branch
        // unless the 0th projection (the use of the actual value of the
        // <Operation> is either nullptr, which means there's no use of the
        // actual value, or was already defined, which means it is scheduled
        // *AFTER* this branch).
        OpIndex node = projection->input();
        if (const OverflowCheckedBinopOp* binop =
                TryCast<OverflowCheckedBinopOp>(node);
            binop && CanDoBranchIfOverflowFusion(node)) {
          DCHECK_EQ(binop->rep, WordRepresentation::Word32());
          switch (binop->kind) {
            case OverflowCheckedBinopOp::Kind::kSignedAdd:
              cont->OverwriteAndNegateIfEqual(kOverflow);
              return VisitBinop(this, node, kArmAdd, kArmAdd, cont);
            case OverflowCheckedBinopOp::Kind::kSignedSub:
              cont->OverwriteAndNegateIfEqual(kOverflow);
              return VisitBinop(this, node, kArmSub, kArmRsb, cont);
            case OverflowCheckedBinopOp::Kind::kSignedMul:
              // ARM doesn't set the overflow flag for multiplication, so we
              // need to test on kNotEqual. Here is the code sequence used:
              // smull resultlow, resulthigh, left, right
              // cmp resulthigh, Operand(resultlow, ASR, 31)
              cont->OverwriteAndNegateIfEqual(kNotEqual);
              return EmitInt32MulWithOverflow(this, node, cont);
          }
        }
      }
    } else if (value_op.Is<Opmask::kWord32Add>()) {
      return VisitWordCompare(this, value, kArmCmn, cont);
    } else if (value_op.Is<Opmask::kWord32Sub>()) {
      return VisitWordCompare(this, value, kArmCmp, cont);
    } else if (value_op.Is<Opmask::kWord32BitwiseAnd>()) {
      return VisitWordCompare(this, value, kArmTst, cont);
    } else if (value_op.Is<Opmask::kWord32BitwiseOr>()) {
      return VisitBinop(this, value, kArmOrr, kArmOrr, cont);
    } else if (value_op.Is<Opmask::kWord32BitwiseXor>()) {
      return VisitWordCompare(this, value, kArmTeq, cont);
    } else if (value_op.Is<Opmask::kWord32ShiftRightArithmetic>()) {
      return VisitShift(this, value, TryMatchASR, cont);
    } else if (value_op.Is<Opmask::kWord32ShiftLeft>()) {
      return VisitShift(this, value, TryMatchLSL, cont);
    } else if (value_op.Is<Opmask::kWord32ShiftRightLogical>()) {
      return VisitShift(this, value, TryMatchLSR, cont);
    } else if (value_op.Is<Opmask::kWord32RotateRight>()) {
      return VisitShift(this, value, TryMatchROR, cont);
    } else if (value_op.Is<StackPointerGreaterThanOp>()) {
      cont->OverwriteAndNegateIfEqual(kStackPointerGreaterThanCondition);
      return VisitStackPointerGreaterThan(value, cont);
    }
  }
  if (Get(user).Is<Opmask::kWord32Equal>()) {
    return VisitWordCompare(this, user, cont);
  }
  // Continuation could not be combined with a compare, emit compare against
  // 0.
  ArmOperandGenerator g(this);
  InstructionCode const opcode =
      kArmTst | AddressingModeField::encode(kMode_Operand2_R);
  InstructionOperand const value_operand = g.UseRegister(value);
  EmitWithContinuation(opcode, value_operand, value_operand, cont);
}
References DCHECK_EQ, v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::EmitInt32MulWithOverflow(), v8::base::BitField< T, shift, size, U >::encode(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float32(), v8::internal::compiler::turboshaft::RegisterRepresentation::Float64(), v8::internal::compiler::turboshaft::Get(), v8::internal::compiler::turboshaft::Operation::Is(), v8::internal::kEqual, v8::internal::compiler::turboshaft::ComparisonOp::kEqual, v8::internal::compiler::kFloatLessThan, v8::internal::compiler::kFloatLessThanOrEqual, v8::internal::compiler::kNotEqual, v8::internal::compiler::kOverflow, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedAdd, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThan, v8::internal::compiler::turboshaft::ComparisonOp::kSignedLessThanOrEqual, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedMul, v8::internal::compiler::turboshaft::OverflowCheckedBinopOp::kSignedSub, v8::internal::compiler::kStackPointerGreaterThanCondition, v8::internal::compiler::FlagsContinuation::OverwriteAndNegateIfEqual(), v8::internal::compiler::turboshaft::Operation::TryCast(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchASR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchLSL(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchLSR(), v8::internal::compiler::anonymous_namespace{instruction-selector-arm.cc}::TryMatchROR(), v8::internal::UNREACHABLE(), v8::internal::compiler::OperandGenerator::UseRegister(), v8::internal::value, v8::internal::compiler::VisitBinop(), v8::internal::compiler::VisitFloat32Compare(), v8::internal::compiler::VisitFloat64Compare(), v8::internal::compiler::VisitShift(), v8::internal::compiler::VisitWordCompare(), v8::internal::compiler::turboshaft::RegisterRepresentation::Word32(), and v8::internal::compiler::turboshaft::WordRepresentation::Word32().
Referenced by VisitBranch(), VisitDeoptimizeIf(), VisitSelect(), and VisitTrapIf().
zone()
Zone* v8::internal::compiler::InstructionSelector::zone () const [inline], [private]
Definition at line 1512 of file instruction-selector.h.
{ return zone_; }
Referenced by AddInputsToFrameStateDescriptor(), EmitBinarySearchSwitch(), EmitTableSwitch(), ForTurboshaft(), InstructionSelector(), SelectInstructions(), VisitBlock(), VisitCall(), VisitControl(), VisitReturn(), and VisitTailCall().
Member Data Documentation
additional_protected_instructions_
std::optional<BitVector> v8::internal::compiler::InstructionSelector::additional_protected_instructions_ [private]
Definition at line 1620 of file instruction-selector.h.
Referenced by InstructionSelector(), and IsSourcePositionUsed().
broker_
JSHeapBroker* const v8::internal::compiler::InstructionSelector::broker_ [private]
Definition at line 1610 of file instruction-selector.h.
Referenced by VisitStaticAssert().
continuation_inputs_
InstructionOperandVector v8::internal::compiler::InstructionSelector::continuation_inputs_ [private]
Definition at line 1584 of file instruction-selector.h.
Referenced by EmitWithContinuation(), and InstructionSelector().
continuation_outputs_
InstructionOperandVector v8::internal::compiler::InstructionSelector::continuation_outputs_ [private]
Definition at line 1585 of file instruction-selector.h.
Referenced by EmitWithContinuation(), and InstructionSelector().
continuation_temps_
InstructionOperandVector v8::internal::compiler::InstructionSelector::continuation_temps_ [private]
Definition at line 1586 of file instruction-selector.h.
Referenced by EmitWithContinuation().
current_block_
const turboshaft::Block* v8::internal::compiler::InstructionSelector::current_block_ [private]
Definition at line 1582 of file instruction-selector.h.
Referenced by CanCover(), CanDoBranchIfOverflowFusion(), TryPrepareScheduleFirstProjection(), VisitBlock(), VisitNode(), and VisitPhi().
current_effect_level_
int v8::internal::compiler::InstructionSelector::current_effect_level_ [private]
Definition at line 1590 of file instruction-selector.h.
Referenced by CanCover(), and VisitBlock().
defined_
BitVector v8::internal::compiler::InstructionSelector::defined_ [private]
Definition at line 1587 of file instruction-selector.h.
Referenced by IsDefined(), and MarkAsDefined().
effect_level_
IntVector v8::internal::compiler::InstructionSelector::effect_level_ [private]
Definition at line 1589 of file instruction-selector.h.
Referenced by GetEffectLevel(), and SetEffectLevel().
enable_roots_relative_addressing_
EnableRootsRelativeAddressing v8::internal::compiler::InstructionSelector::enable_roots_relative_addressing_ [private]
Definition at line 1595 of file instruction-selector.h.
Referenced by CanAddressRelativeToRootsRegister().
enable_scheduling_
EnableScheduling v8::internal::compiler::InstructionSelector::enable_scheduling_ [private]
Definition at line 1594 of file instruction-selector.h.
enable_switch_jump_table_
EnableSwitchJumpTable v8::internal::compiler::InstructionSelector::enable_switch_jump_table_ [private]
Definition at line 1596 of file instruction-selector.h.
ensure_deterministic_nan_
EnsureDeterministicNan v8::internal::compiler::InstructionSelector::ensure_deterministic_nan_ [private]
Definition at line 1606 of file instruction-selector.h.
Referenced by IsCommutative().
features_
Features v8::internal::compiler::InstructionSelector::features_ [private]
Definition at line 1580 of file instruction-selector.h.
frame_
Frame* v8::internal::compiler::InstructionSelector::frame_ [private]
Definition at line 1602 of file instruction-selector.h.
Referenced by InitializeCallBuffer(), and VisitNode().
instr_origins_
ZoneVector<std::pair<int, int> > v8::internal::compiler::InstructionSelector::instr_origins_ [private]
Definition at line 1604 of file instruction-selector.h.
Referenced by InstructionSelector(), VisitBlock(), and VisitControl().
instruction_selection_failed_
bool v8::internal::compiler::InstructionSelector::instruction_selection_failed_ [private]
Definition at line 1603 of file instruction-selector.h.
instructions_
ZoneVector<Instruction*> v8::internal::compiler::InstructionSelector::instructions_ [private]
Definition at line 1583 of file instruction-selector.h.
Referenced by Emit(), InstructionSelector(), SelectInstructions(), VisitBlock(), and VisitControl().
linkage_
Linkage* const v8::internal::compiler::InstructionSelector::linkage_ [private]
Definition at line 1576 of file instruction-selector.h.
max_pushed_argument_count_
size_t* v8::internal::compiler::InstructionSelector::max_pushed_argument_count_ [private]
Definition at line 1615 of file instruction-selector.h.
Referenced by UpdateMaxPushedArgumentCount().
max_unoptimized_frame_height_
size_t* v8::internal::compiler::InstructionSelector::max_unoptimized_frame_height_ [private]
Definition at line 1614 of file instruction-selector.h.
Referenced by GetFrameStateDescriptor().
OperandGenerator
friend v8::internal::compiler::InstructionSelector::OperandGenerator [private]
Definition at line 1018 of file instruction-selector.h.
protected_loads_to_remove_
std::optional<BitVector> v8::internal::compiler::InstructionSelector::protected_loads_to_remove_ [private]
Definition at line 1619 of file instruction-selector.h.
Referenced by InstructionSelector(), and VisitBlock().
schedule_
turboshaft::Graph* const v8::internal::compiler::InstructionSelector::schedule_ [private]
Definition at line 1581 of file instruction-selector.h.
Referenced by CanDoBranchIfOverflowFusion(), InstructionSelector(), IsProtectedLoad(), and TryPrepareScheduleFirstProjection().
scheduler_
InstructionScheduler* v8::internal::compiler::InstructionSelector::scheduler_ [private]
Definition at line 1593 of file instruction-selector.h.
Referenced by AddInstruction(), AddTerminator(), EndBlock(), SelectInstructions(), and StartBlock().
sequence_
InstructionSequence* const v8::internal::compiler::InstructionSelector::sequence_ [private]
Definition at line 1577 of file instruction-selector.h.
source_position_mode_
SourcePositionMode const v8::internal::compiler::InstructionSelector::source_position_mode_ [private]
Definition at line 1579 of file instruction-selector.h.
Referenced by IsSourcePositionUsed().
source_positions_
source_position_table_t* const v8::internal::compiler::InstructionSelector::source_positions_ [private]
Definition at line 1578 of file instruction-selector.h.
Referenced by UpdateSourcePosition(), and VisitBlock().
state_values_cache_
ZoneUnorderedMap<FrameStateInput, CachedStateValues*, typename FrameStateInput::Hash, typename FrameStateInput::Equal> v8::internal::compiler::InstructionSelector::state_values_cache_ [private]
Definition at line 1600 of file instruction-selector.h.
tick_counter_
TickCounter* const v8::internal::compiler::InstructionSelector::tick_counter_ [private]
Definition at line 1607 of file instruction-selector.h.
Referenced by VisitNode().
trace_turbo_
EnableTraceTurboJson v8::internal::compiler::InstructionSelector::trace_turbo_ [private]
Definition at line 1605 of file instruction-selector.h.
Referenced by InstructionSelector(), VisitBlock(), and VisitControl().
turboshaft_use_map_
std::optional<turboshaft::UseMap> v8::internal::compiler::InstructionSelector::turboshaft_use_map_ [private]
Definition at line 1618 of file instruction-selector.h.
Referenced by InstructionSelector().
used_
BitVector v8::internal::compiler::InstructionSelector::used_ [private]
Definition at line 1588 of file instruction-selector.h.
Referenced by IsReallyUsed(), IsUsed(), and MarkAsUsed().
virtual_register_rename_
IntVector v8::internal::compiler::InstructionSelector::virtual_register_rename_ [private]
Definition at line 1592 of file instruction-selector.h.
Referenced by GetRename(), and SetRename().
virtual_registers_
IntVector v8::internal::compiler::InstructionSelector::virtual_registers_ [private]
Definition at line 1591 of file instruction-selector.h.
Referenced by GetVirtualRegister(), and GetVirtualRegistersForTesting().
zone_
Zone* const v8::internal::compiler::InstructionSelector::zone_ [private]
Definition at line 1575 of file instruction-selector.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/instruction-selector.h
/mnt/V8SourceCode/src/compiler/backend/arm/instruction-selector-arm.cc
/mnt/V8SourceCode/src/compiler/backend/arm64/instruction-selector-arm64.cc
/mnt/V8SourceCode/src/compiler/backend/ia32/instruction-selector-ia32.cc
/mnt/V8SourceCode/src/compiler/backend/instruction-selector.cc
/mnt/V8SourceCode/src/compiler/backend/loong64/instruction-selector-loong64.cc
/mnt/V8SourceCode/src/compiler/backend/mips64/instruction-selector-mips64.cc
/mnt/V8SourceCode/src/compiler/backend/ppc/instruction-selector-ppc.cc
/mnt/V8SourceCode/src/compiler/backend/riscv/instruction-selector-riscv.h
/mnt/V8SourceCode/src/compiler/backend/riscv/instruction-selector-riscv32.cc
/mnt/V8SourceCode/src/compiler/backend/riscv/instruction-selector-riscv64.cc
/mnt/V8SourceCode/src/compiler/backend/s390/instruction-selector-s390.cc
/mnt/V8SourceCode/src/compiler/backend/x64/instruction-selector-x64.cc