cppgc::internal::MutatorMarkingState Class Reference
#include <marking-state.h>
Classes
class RecentlyRetracedWeakContainers
Public Member Functions
MutatorMarkingState (HeapBase &heap, MarkingWorklists &marking_worklists, CompactionWorklists *compaction_worklists)
~MutatorMarkingState () override=default
bool MarkNoPush (HeapObjectHeader &header)
void ReTraceMarkedWeakContainer (cppgc::Visitor &, HeapObjectHeader &)
void DynamicallyMarkAddress (ConstAddress)
void FlushNotFullyConstructedObjects ()
void FlushDiscoveredEphemeronPairs ()
void InvokeWeakRootsCallbackIfNeeded (const void *, TraceDescriptor, WeakCallback, const void *)
bool IsMarkedWeakContainer (HeapObjectHeader &)
MarkingWorklists::RetraceMarkedObjectsWorklist::Local & retrace_marked_objects_worklist ()
V8_EXPORT_PRIVATE void Publish () override
Private Attributes
class cppgc::internal::MutatorMarkingState::RecentlyRetracedWeakContainers recently_retraced_weak_containers_
MarkingWorklists::RetraceMarkedObjectsWorklist::Local retrace_marked_objects_worklist_
Additional Inherited Members
Detailed Description
Definition at line 357 of file marking-state.h.
Constructor & Destructor Documentation
MutatorMarkingState()
cppgc::internal::MutatorMarkingState::MutatorMarkingState (HeapBase & heap, MarkingWorklists & marking_worklists, CompactionWorklists * compaction_worklists) [inline]
Definition at line 359 of file marking-state.h.
      : BasicMarkingState(heap, marking_worklists, compaction_worklists),
        retrace_marked_objects_worklist_(
            *marking_worklists.retrace_marked_objects_worklist()) {}
 MutatorMarkingState()
cppgc::internal::MutatorMarkingState::~MutatorMarkingState () [override], [default]
Member Function Documentation
DynamicallyMarkAddress()
void cppgc::internal::MutatorMarkingState::DynamicallyMarkAddress (ConstAddress address) [inline]
Definition at line 422 of file marking-state.h.
                                                                     {
  HeapObjectHeader& header =
      BasePage::FromPayload(address)->ObjectHeaderFromInnerAddress(
          const_cast<Address>(address));
  DCHECK(!header.IsInConstruction());
  if (MarkNoPush(header)) {
    marking_worklist_.Push(
        {reinterpret_cast<void*>(header.ObjectStart()),
         GlobalGCInfoTable::GCInfoFromIndex(header.GetGCInfoIndex()).trace});
  }
}
References DCHECK, cppgc::internal::BasePage::FromPayload(), cppgc::internal::GlobalGCInfoTable::GCInfoFromIndex(), cppgc::internal::HeapObjectHeader::GetGCInfoIndex(), cppgc::internal::HeapObjectHeader::IsInConstruction(), cppgc::internal::MarkingStateBase::marking_worklist_, MarkNoPush(), cppgc::internal::BasePage::ObjectHeaderFromInnerAddress(), cppgc::internal::HeapObjectHeader::ObjectStart(), and cppgc::internal::GCInfo::trace.
FlushDiscoveredEphemeronPairs()
void cppgc::internal::MutatorMarkingState::FlushDiscoveredEphemeronPairs ()
Definition at line 74 of file marking-state.cc.
                                                        {
  StatsCollector::EnabledScope stats_scope(
      heap_.stats_collector(), StatsCollector::kMarkFlushEphemerons);
  discovered_ephemeron_pairs_worklist_.Publish();
  if (!discovered_ephemeron_pairs_worklist_.IsGlobalEmpty()) {
    ephemeron_pairs_for_processing_worklist_.Merge(
        discovered_ephemeron_pairs_worklist_);
  }
}
References cppgc::internal::BasicMarkingState::discovered_ephemeron_pairs_worklist_, cppgc::internal::BasicMarkingState::ephemeron_pairs_for_processing_worklist_, cppgc::internal::MarkingStateBase::heap_, and cppgc::internal::HeapBase::stats_collector().
Referenced by cppgc::internal::MarkerBase::ProcessWorklistsWithDeadline().
FlushNotFullyConstructedObjects()
void cppgc::internal::MutatorMarkingState::FlushNotFullyConstructedObjects ()
Definition at line 65 of file marking-state.cc.
                                                          {
  std::unordered_set<HeapObjectHeader*> objects =
      not_fully_constructed_worklist_.Extract<AccessMode::kAtomic>();
  for (HeapObjectHeader* object : objects) {
    if (MarkNoPush(*object))
      previously_not_fully_constructed_worklist_.Push(object);
  }
}
References cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Extract(), cppgc::internal::kAtomic, MarkNoPush(), cppgc::internal::MarkingStateBase::not_fully_constructed_worklist_, and cppgc::internal::BasicMarkingState::previously_not_fully_constructed_worklist_.
Referenced by cppgc::internal::MarkerBase::HandleNotFullyConstructedObjects(), and cppgc::internal::MarkerBase::IncrementalMarkingStep().
InvokeWeakRootsCallbackIfNeeded()
void cppgc::internal::MutatorMarkingState::InvokeWeakRootsCallbackIfNeeded (const void * object, TraceDescriptor desc, WeakCallback weak_callback, const void * parameter) [inline]
Definition at line 434 of file marking-state.h.
                           {
  // Since weak roots are only traced at the end of marking, we can execute
  // the callback instead of registering it.
#if DEBUG
  const HeapObjectHeader& header =
      HeapObjectHeader::FromObject(desc.base_object_payload);
  DCHECK_IMPLIES(header.IsInConstruction(),
                 header.IsMarked<AccessMode::kAtomic>());
#endif // DEBUG
  weak_callback(LivenessBrokerFactory::Create(), parameter);
}
References cppgc::TraceDescriptor::base_object_payload, cppgc::internal::LivenessBrokerFactory::Create(), DCHECK_IMPLIES, cppgc::internal::HeapObjectHeader::FromObject(), cppgc::internal::HeapObjectHeader::IsInConstruction(), cppgc::internal::HeapObjectHeader::IsMarked(), and cppgc::internal::kAtomic.
Referenced by cppgc::internal::RootMarkingVisitor::VisitWeakRoot().
IsMarkedWeakContainer()
bool cppgc::internal::MutatorMarkingState::IsMarkedWeakContainer (HeapObjectHeader & header) [inline]
Definition at line 448 of file marking-state.h.
                                                                        {
  const bool result =
      weak_containers_worklist_.Contains<AccessMode::kAtomic>(&header) &&
      !recently_retraced_weak_containers_.Contains(&header);
  DCHECK_IMPLIES(result, header.IsMarked<AccessMode::kAtomic>());
  DCHECK_IMPLIES(result, !header.IsInConstruction());
  return result;
}
References cppgc::internal::MutatorMarkingState::RecentlyRetracedWeakContainers::Contains(), cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Contains(), DCHECK_IMPLIES, cppgc::internal::HeapObjectHeader::IsInConstruction(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kAtomic, recently_retraced_weak_containers_, v8::base::internal::result, and cppgc::internal::BasicMarkingState::weak_containers_worklist_.
Referenced by cppgc::internal::ConservativeMarkingVisitor::VisitFullyConstructedConservatively(), and cppgc::internal::ConservativeMarkingVisitor::VisitInConstructionConservatively().
MarkNoPush()
bool cppgc::internal::MutatorMarkingState::MarkNoPush (HeapObjectHeader & header) [inline]
Definition at line 366 of file marking-state.h.
                                                   {
    return MutatorMarkingState::BasicMarkingState::MarkNoPush(header);
  }
Referenced by DynamicallyMarkAddress(), FlushNotFullyConstructedObjects(), and cppgc::internal::ConservativeMarkingVisitor::VisitInConstructionConservatively().
Publish()
void cppgc::internal::MutatorMarkingState::Publish () [override], [virtual]
Reimplemented from cppgc::internal::BasicMarkingState.
Definition at line 84 of file marking-state.cc.
                                  {
  BasicMarkingState::Publish();
  retrace_marked_objects_worklist_.Publish();
}
References cppgc::internal::BasicMarkingState::Publish(), and retrace_marked_objects_worklist_.
Referenced by cppgc::internal::MarkerBase::AdvanceMarkingWithLimits(), cppgc::internal::MarkerBase::EnterAtomicPause(), cppgc::internal::MarkerBase::FinishMarking(), cppgc::internal::MarkerBase::ReEnableConcurrentMarking(), and cppgc::internal::MarkerBase::StartMarking().
retrace_marked_objects_worklist()
MarkingWorklists::RetraceMarkedObjectsWorklist::Local& cppgc::internal::MutatorMarkingState::retrace_marked_objects_worklist () [inline]
Definition at line 388 of file marking-state.h.
                                    {
    return retrace_marked_objects_worklist_;
  }
References retrace_marked_objects_worklist_.
Referenced by cppgc::internal::MarkerBase::ProcessWorklistsWithDeadline(), ReTraceMarkedWeakContainer(), and cppgc::internal::MarkerBase::WriteBarrierForObject().
ReTraceMarkedWeakContainer()
void cppgc::internal::MutatorMarkingState::ReTraceMarkedWeakContainer (cppgc::Visitor & visitor, HeapObjectHeader & header) [inline]
Definition at line 415 of file marking-state.h.
                                                                               {
  DCHECK(weak_containers_worklist_.Contains<AccessMode::kAtomic>(&header));
  recently_retraced_weak_containers_.Insert(&header);
  retrace_marked_objects_worklist().Push(&header);
}
References cppgc::internal::MarkingWorklists::ExternalMarkingWorklist::Contains(), DCHECK, cppgc::internal::MutatorMarkingState::RecentlyRetracedWeakContainers::Insert(), cppgc::internal::kAtomic, recently_retraced_weak_containers_, retrace_marked_objects_worklist(), and cppgc::internal::BasicMarkingState::weak_containers_worklist_.
Referenced by cppgc::internal::ConservativeMarkingVisitor::VisitFullyConstructedConservatively().
Member Data Documentation
recently_retraced_weak_containers_
class cppgc::internal::MutatorMarkingState::RecentlyRetracedWeakContainers cppgc::internal::MutatorMarkingState::recently_retraced_weak_containers_ [private]
Referenced by IsMarkedWeakContainer(), and ReTraceMarkedWeakContainer().
retrace_marked_objects_worklist_
MarkingWorklists::RetraceMarkedObjectsWorklist::Local cppgc::internal::MutatorMarkingState::retrace_marked_objects_worklist_ [private]
Definition at line 412 of file marking-state.h.
Referenced by Publish(), and retrace_marked_objects_worklist().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/marking-state.h
/mnt/V8SourceCode/src/heap/cppgc/marking-state.cc