v8::internal::FrameTranslationBuilder Class Reference
#include <frame-translation-builder.h>
Classes
struct Instruction
Public Member Functions
FrameTranslationBuilder (Zone *zone)
DirectHandle< DeoptimizationFrameTranslation > ToFrameTranslation (LocalFactory *factory)
base::Vector< const uint8_t > ToFrameTranslationWasm ()
int BeginTranslation (int frame_count, int jsframe_count, bool update_feedback)
void BeginInterpretedFrame (BytecodeOffset bytecode_offset, int literal_id, int bytecode_array_id, unsigned height, int return_value_offset, int return_value_count)
void BeginInlinedExtraArguments (int literal_id, unsigned height, uint32_t parameter_count)
void BeginConstructCreateStubFrame (int literal_id, unsigned height)
void BeginConstructInvokeStubFrame (int literal_id)
void BeginBuiltinContinuationFrame (BytecodeOffset bailout_id, int literal_id, unsigned height)
void BeginJavaScriptBuiltinContinuationFrame (BytecodeOffset bailout_id, int literal_id, unsigned height)
void BeginJavaScriptBuiltinContinuationWithCatchFrame (BytecodeOffset bailout_id, int literal_id, unsigned height)
void ArgumentsElements (CreateArgumentsType type)
void ArgumentsLength ()
void RestLength ()
void BeginCapturedObject (int length)
void AddUpdateFeedback (int vector_literal, int slot)
void DuplicateObject (int object_index)
void StringConcat ()
void StoreRegister (TranslationOpcode opcode, Register reg)
void StoreRegister (Register reg)
void StoreInt32Register (Register reg)
void StoreInt64Register (Register reg)
void StoreIntPtrRegister (Register reg)
void StoreSignedBigInt64Register (Register reg)
void StoreUnsignedBigInt64Register (Register reg)
void StoreUint32Register (Register reg)
void StoreBoolRegister (Register reg)
void StoreFloatRegister (FloatRegister reg)
void StoreDoubleRegister (DoubleRegister reg)
void StoreHoleyDoubleRegister (DoubleRegister reg)
void StoreSimd128Register (Simd128Register reg)
void StoreStackSlot (int index)
void StoreInt32StackSlot (int index)
void StoreInt64StackSlot (int index)
void StoreIntPtrStackSlot (int index)
void StoreSignedBigInt64StackSlot (int index)
void StoreUnsignedBigInt64StackSlot (int index)
void StoreUint32StackSlot (int index)
void StoreBoolStackSlot (int index)
void StoreFloatStackSlot (int index)
void StoreDoubleStackSlot (int index)
void StoreSimd128StackSlot (int index)
void StoreHoleyDoubleStackSlot (int index)
void StoreLiteral (int literal_id)
void StoreOptimizedOut ()
void StoreJSFrameFunction ()
Private Member Functions
template<typename... T>
void Add (TranslationOpcode opcode, T... operands)
template<typename... T>
void AddRawToContents (TranslationOpcode opcode, T... operands)
template<typename... T>
void AddRawToContentsForCompression (TranslationOpcode opcode, T... operands)
template<typename... T>
void AddRawBegin (bool update_feedback, T... operands)
int Size () const
int SizeInBytes () const
Zone * zone () const
void FinishPendingInstructionIfNeeded ()
void ValidateBytes (DeoptTranslationIterator &iter) const
Private Attributes
ZoneVector< uint8_t > contents_
ZoneVector< int32_t > contents_for_compression_
ZoneVector< Instruction > basis_instructions_
Zone *const zone_
size_t matching_instructions_count_ = 0
size_t total_matching_instructions_in_current_translation_ = 0
size_t instruction_index_within_translation_ = 0
int index_of_basis_translation_start_ = 0
bool match_previous_allowed_ = true
Detailed Description
Definition at line 24 of file frame-translation-builder.h.
Constructor & Destructor Documentation
FrameTranslationBuilder()
v8::internal::FrameTranslationBuilder::FrameTranslationBuilder (Zone * zone) [inline], [explicit]
Definition at line 26 of file frame-translation-builder.h.
      : contents_(zone),
        contents_for_compression_(zone),
        basis_instructions_(zone),
        zone_(zone) {}
Member Function Documentation
Add()
template<typename... T>
void v8::internal::FrameTranslationBuilder::Add (TranslationOpcode opcode, T... operands) [private]
Definition at line 175 of file frame-translation-builder.cc.
                                                                         {
  DCHECK_EQ(sizeof...(T), TranslationOpcodeOperandCount(opcode));
  if (V8_UNLIKELY(v8_flags.turbo_compress_frame_translations)) {
    AddRawToContentsForCompression(opcode, operands...);
    return;
  }
#ifdef ENABLE_SLOW_DCHECKS
  if (v8_flags.enable_slow_asserts) {
    all_instructions_.emplace_back(opcode, operands...);
  }
#endif
  if (match_previous_allowed_ &&
      instruction_index_within_translation_ < basis_instructions_.size() &&
      opcode ==
          basis_instructions_[instruction_index_within_translation_].opcode &&
      OperandsEqual(
          basis_instructions_[instruction_index_within_translation_].operands,
          operands...)) {
    ++matching_instructions_count_;
  } else {
    FinishPendingInstructionIfNeeded();
    AddRawToContents(opcode, operands...);
    if (!match_previous_allowed_) {
      // Include this instruction in basis_instructions_ so that future
      // translations can check whether they match with it.
      DCHECK_EQ(basis_instructions_.size(),
                instruction_index_within_translation_);
      basis_instructions_.emplace_back(opcode, operands...);
    }
  }
  ++instruction_index_within_translation_;
}
References AddRawToContents(), AddRawToContentsForCompression(), basis_instructions_, DCHECK_EQ, FinishPendingInstructionIfNeeded(), instruction_index_within_translation_, match_previous_allowed_, matching_instructions_count_, v8::internal::anonymous_namespace{frame-translation-builder.cc}::OperandsEqual(), v8::internal::TranslationOpcodeOperandCount(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by AddUpdateFeedback(), ArgumentsElements(), ArgumentsLength(), BeginBuiltinContinuationFrame(), BeginCapturedObject(), BeginConstructCreateStubFrame(), BeginConstructInvokeStubFrame(), BeginInlinedExtraArguments(), BeginInterpretedFrame(), BeginJavaScriptBuiltinContinuationFrame(), BeginJavaScriptBuiltinContinuationWithCatchFrame(), DuplicateObject(), RestLength(), StoreBoolStackSlot(), StoreDoubleRegister(), StoreDoubleStackSlot(), StoreFloatRegister(), StoreFloatStackSlot(), StoreHoleyDoubleRegister(), StoreHoleyDoubleStackSlot(), StoreInt32StackSlot(), StoreInt64StackSlot(), StoreIntPtrStackSlot(), StoreLiteral(), StoreOptimizedOut(), StoreRegister(), StoreSignedBigInt64StackSlot(), StoreSimd128Register(), StoreSimd128StackSlot(), StoreStackSlot(), StoreUint32StackSlot(), StoreUnsignedBigInt64StackSlot(), and StringConcat().
AddRawBegin()
template<typename... T>
void v8::internal::FrameTranslationBuilder::AddRawBegin (bool update_feedback, T... operands) [private]
Definition at line 96 of file frame-translation-builder.cc.
                                                                             {
  auto opcode = update_feedback ? TranslationOpcode::BEGIN_WITH_FEEDBACK
                                : TranslationOpcode::BEGIN_WITHOUT_FEEDBACK;
  if (V8_UNLIKELY(v8_flags.turbo_compress_frame_translations)) {
    AddRawToContentsForCompression(opcode, operands...);
  } else {
    AddRawToContents(opcode, operands...);
#ifdef ENABLE_SLOW_DCHECKS
    if (v8_flags.enable_slow_asserts) {
      all_instructions_.emplace_back(opcode, operands...);
    }
#endif
  }
}
References AddRawToContents(), AddRawToContentsForCompression(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by BeginTranslation().
AddRawToContents()
template<typename... T>
void v8::internal::FrameTranslationBuilder::AddRawToContents (TranslationOpcode opcode, T... operands) [private]
Definition at line 78 of file frame-translation-builder.cc.
                                                              {
  DCHECK_EQ(sizeof...(T), TranslationOpcodeOperandCount(opcode));
  DCHECK(!v8_flags.turbo_compress_frame_translations);
  contents_.push_back(static_cast<uint8_t>(opcode));
  (..., operands.WriteVLQ(&contents_));
}
References contents_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ZoneVector< T >::push_back(), v8::internal::TranslationOpcodeOperandCount(), and v8::internal::v8_flags.
Referenced by Add(), AddRawBegin(), and FinishPendingInstructionIfNeeded().
AddRawToContentsForCompression()
template<typename... T>
void v8::internal::FrameTranslationBuilder::AddRawToContentsForCompression (TranslationOpcode opcode, T... operands) [private]
Definition at line 87 of file frame-translation-builder.cc.
                                             {
  DCHECK_EQ(sizeof...(T), TranslationOpcodeOperandCount(opcode));
  DCHECK(v8_flags.turbo_compress_frame_translations);
  contents_for_compression_.push_back(static_cast<uint8_t>(opcode));
  (..., contents_for_compression_.push_back(operands.value()));
}
References contents_for_compression_, v8::internal::DCHECK(), DCHECK_EQ, v8::internal::ZoneVector< T >::push_back(), v8::internal::TranslationOpcodeOperandCount(), and v8::internal::v8_flags.
Referenced by Add(), and AddRawBegin().
AddUpdateFeedback()
void v8::internal::FrameTranslationBuilder::AddUpdateFeedback (int vector_literal, int slot)
Definition at line 541 of file frame-translation-builder.cc.
                                                                            {
  auto opcode = TranslationOpcode::UPDATE_FEEDBACK;
  Add(opcode, SignedOperand(vector_literal), SignedOperand(slot));
}
References Add().
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslation().
ArgumentsElements()
void v8::internal::FrameTranslationBuilder::ArgumentsElements (CreateArgumentsType type)
Definition at line 368 of file frame-translation-builder.cc.
                                                                        {
  auto opcode = TranslationOpcode::ARGUMENTS_ELEMENTS;
  Add(opcode, SignedOperand(static_cast<uint8_t>(type)));
}
References Add(), and v8::internal::tracing::type.
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
ArgumentsLength()
void v8::internal::FrameTranslationBuilder::ArgumentsLength ()
Definition at line 373 of file frame-translation-builder.cc.
                                              {
  auto opcode = TranslationOpcode::ARGUMENTS_LENGTH;
  Add(opcode);
}
References Add().
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
BeginBuiltinContinuationFrame()
void v8::internal::FrameTranslationBuilder::BeginBuiltinContinuationFrame (BytecodeOffset bailout_id, int literal_id, unsigned height)
Definition at line 284 of file frame-translation-builder.cc.
                                                                     {
  auto opcode = TranslationOpcode::BUILTIN_CONTINUATION_FRAME;
  Add(opcode, SignedOperand(bytecode_offset.ToInt()), SignedOperand(literal_id),
      UnsignedOperand(height));
}
References Add(), and v8::internal::BytecodeOffset::ToInt().
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor().
BeginCapturedObject()
void v8::internal::FrameTranslationBuilder::BeginCapturedObject (int length)
Definition at line 383 of file frame-translation-builder.cc.
                                                            {
  auto opcode = TranslationOpcode::CAPTURED_OBJECT;
  Add(opcode, SignedOperand(length));
}
References Add(), and v8::internal::length.
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
BeginConstructCreateStubFrame()
void v8::internal::FrameTranslationBuilder::BeginConstructCreateStubFrame (int literal_id, unsigned height)
Definition at line 333 of file frame-translation-builder.cc.
                                                                             {
  auto opcode = TranslationOpcode::CONSTRUCT_CREATE_STUB_FRAME;
  Add(opcode, SignedOperand(literal_id), UnsignedOperand(height));
}
References Add().
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor().
BeginConstructInvokeStubFrame()
void v8::internal::FrameTranslationBuilder::BeginConstructInvokeStubFrame (int literal_id)
Definition at line 339 of file frame-translation-builder.cc.
                                                                          {
  auto opcode = TranslationOpcode::CONSTRUCT_INVOKE_STUB_FRAME;
  Add(opcode, SignedOperand(literal_id));
}
References Add().
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor().
BeginInlinedExtraArguments()
void v8::internal::FrameTranslationBuilder::BeginInlinedExtraArguments (int literal_id, unsigned height, uint32_t parameter_count)
Definition at line 344 of file frame-translation-builder.cc.
                                                               {
  auto opcode = TranslationOpcode::INLINED_EXTRA_ARGUMENTS;
  Add(opcode, SignedOperand(literal_id), UnsignedOperand(height),
      UnsignedOperand(parameter_count));
}
References Add().
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor().
BeginInterpretedFrame()
void v8::internal::FrameTranslationBuilder::BeginInterpretedFrame (BytecodeOffset bytecode_offset, int literal_id, int bytecode_array_id, unsigned height, int return_value_offset, int return_value_count)
Definition at line 351 of file frame-translation-builder.cc.
                                                                      {
  if (return_value_count == 0) {
    auto opcode = TranslationOpcode::INTERPRETED_FRAME_WITHOUT_RETURN;
    Add(opcode, SignedOperand(bytecode_offset.ToInt()),
        SignedOperand(literal_id), SignedOperand(bytecode_array_id),
        UnsignedOperand(height));
  } else {
    auto opcode = TranslationOpcode::INTERPRETED_FRAME_WITH_RETURN;
    Add(opcode, SignedOperand(bytecode_offset.ToInt()),
        SignedOperand(literal_id), SignedOperand(bytecode_array_id),
        UnsignedOperand(height), SignedOperand(return_value_offset),
        SignedOperand(return_value_count));
  }
}
References Add(), and v8::internal::BytecodeOffset::ToInt().
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor().
BeginJavaScriptBuiltinContinuationFrame()
void v8::internal::FrameTranslationBuilder::BeginJavaScriptBuiltinContinuationFrame (BytecodeOffset bailout_id, int literal_id, unsigned height)
Definition at line 318 of file frame-translation-builder.cc.
                                                                     {
  auto opcode = TranslationOpcode::JAVASCRIPT_BUILTIN_CONTINUATION_FRAME;
  Add(opcode, SignedOperand(bytecode_offset.ToInt()), SignedOperand(literal_id),
      UnsignedOperand(height));
}
References Add(), and v8::internal::BytecodeOffset::ToInt().
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor().
BeginJavaScriptBuiltinContinuationWithCatchFrame()
void v8::internal::FrameTranslationBuilder::BeginJavaScriptBuiltinContinuationWithCatchFrame (BytecodeOffset bailout_id, int literal_id, unsigned height)
Definition at line 325 of file frame-translation-builder.cc.
                                                                     {
  auto opcode =
      TranslationOpcode::JAVASCRIPT_BUILTIN_CONTINUATION_WITH_CATCH_FRAME;
  Add(opcode, SignedOperand(bytecode_offset.ToInt()), SignedOperand(literal_id),
      UnsignedOperand(height));
}
References Add(), and v8::internal::BytecodeOffset::ToInt().
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslationForFrameStateDescriptor().
BeginTranslation()
int v8::internal::FrameTranslationBuilder::BeginTranslation (int frame_count, int jsframe_count, bool update_feedback)
Definition at line 111 of file frame-translation-builder.cc.
                                                                    {
  FinishPendingInstructionIfNeeded();
  int start_index = Size();
  int distance_from_last_start = 0;
  // We should reuse an existing basis translation if:
  // - we just finished writing the basis translation
  // (match_previous_allowed_ is false), or
  // - the translation we just finished was moderately successful at reusing
  // instructions from the basis translation. We'll define "moderately
  // successful" as reusing more than 3/4 of the basis instructions.
  // Otherwise we should reset and write a new basis translation. At the
  // beginning, match_previous_allowed_ is initialized to true so that this
  // logic decides to start a new basis translation.
  if (!match_previous_allowed_ ||
      total_matching_instructions_in_current_translation_ >
          instruction_index_within_translation_ / 4 * 3) {
    // Use the existing basis translation.
    distance_from_last_start = start_index - index_of_basis_translation_start_;
    match_previous_allowed_ = true;
  } else {
    // Abandon the existing basis translation and write a new one.
    basis_instructions_.clear();
    index_of_basis_translation_start_ = start_index;
    match_previous_allowed_ = false;
  }
  total_matching_instructions_in_current_translation_ = 0;
  instruction_index_within_translation_ = 0;
  // BEGIN instructions can't be replaced by MATCH_PREVIOUS_TRANSLATION, so
  // use a special helper function rather than calling Add().
  AddRawBegin(update_feedback, UnsignedOperand(distance_from_last_start),
              SignedOperand(frame_count), SignedOperand(jsframe_count));
  return start_index;
}
References AddRawBegin(), basis_instructions_, FinishPendingInstructionIfNeeded(), index_of_basis_translation_start_, instruction_index_within_translation_, match_previous_allowed_, Size(), and total_matching_instructions_in_current_translation_.
Referenced by v8::internal::compiler::CodeGenerator::BuildTranslation().
DuplicateObject()
void v8::internal::FrameTranslationBuilder::DuplicateObject (int object_index)
Definition at line 388 of file frame-translation-builder.cc.
                                                              {
  auto opcode = TranslationOpcode::DUPLICATED_OBJECT;
  Add(opcode, SignedOperand(object_index));
}
References Add().
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
FinishPendingInstructionIfNeeded()
void v8::internal::FrameTranslationBuilder::FinishPendingInstructionIfNeeded () [private]
Definition at line 150 of file frame-translation-builder.cc.
                                                               {
  if (matching_instructions_count_) {
    total_matching_instructions_in_current_translation_ +=
        matching_instructions_count_;
    // There is a short form for the MATCH_PREVIOUS_TRANSLATION instruction
    // because it's the most common opcode: rather than spending a byte on the
    // opcode and a second byte on the operand, we can use only a single byte
    // which doesn't match any valid opcode.
    const int kMaxShortenableOperand =
        std::numeric_limits<uint8_t>::max() - kNumTranslationOpcodes;
    if (matching_instructions_count_ <= kMaxShortenableOperand) {
      contents_.push_back(kNumTranslationOpcodes +
                          matching_instructions_count_);
    } else {
      // The operand didn't fit in the opcode byte, so encode it normally.
      AddRawToContents(
          TranslationOpcode::MATCH_PREVIOUS_TRANSLATION,
          UnsignedOperand(static_cast<uint32_t>(matching_instructions_count_)));
    }
    matching_instructions_count_ = 0;
  }
}
References AddRawToContents(), contents_, v8::internal::kNumTranslationOpcodes, matching_instructions_count_, v8::internal::ZoneVector< T >::push_back(), and total_matching_instructions_in_current_translation_.
Referenced by Add(), BeginTranslation(), ToFrameTranslation(), and ToFrameTranslationWasm().
RestLength()
void v8::internal::FrameTranslationBuilder::RestLength ()
Definition at line 378 of file frame-translation-builder.cc.
                                         {
  auto opcode = TranslationOpcode::REST_LENGTH;
  Add(opcode);
}
References Add().
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
Size()
int v8::internal::FrameTranslationBuilder::Size () const [inline], [private]
Definition at line 139 of file frame-translation-builder.h.
                   {
    return V8_UNLIKELY(v8_flags.turbo_compress_frame_translations)
               ? static_cast<int>(contents_for_compression_.size())
               : static_cast<int>(contents_.size());
  }
References contents_, contents_for_compression_, v8::internal::ZoneVector< T >::size(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by BeginTranslation(), SizeInBytes(), and ToFrameTranslation().
SizeInBytes()
int v8::internal::FrameTranslationBuilder::SizeInBytes () const [inline], [private]
Definition at line 144 of file frame-translation-builder.h.
                          {
    return V8_UNLIKELY(v8_flags.turbo_compress_frame_translations)
               ? Size() * kInt32Size
               : Size();
  }
References v8::internal::kInt32Size, Size(), v8::internal::v8_flags, and V8_UNLIKELY.
Referenced by ToFrameTranslation().
StoreBoolRegister()
void v8::internal::FrameTranslationBuilder::StoreBoolRegister (Register reg)
Definition at line 440 of file frame-translation-builder.cc.
                                                            {
  auto opcode = TranslationOpcode::BOOL_REGISTER;
  StoreRegister(opcode, reg);
}
References StoreRegister().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreBoolStackSlot()
void v8::internal::FrameTranslationBuilder::StoreBoolStackSlot (int index)
Definition at line 505 of file frame-translation-builder.cc.
                                                          {
  auto opcode = TranslationOpcode::BOOL_STACK_SLOT;
  Add(opcode, SignedOperand(index));
}
References Add(), and v8::internal::index.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreDoubleRegister()
void v8::internal::FrameTranslationBuilder::StoreDoubleRegister (DoubleRegister reg)
Definition at line 451 of file frame-translation-builder.cc.
                                                                    {
  static_assert(DoubleRegister::kNumRegisters - 1 <= base::kDataMask);
  auto opcode = TranslationOpcode::DOUBLE_REGISTER;
  Add(opcode, SmallUnsignedOperand(static_cast<uint8_t>(reg.code())));
}
References Add(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::base::kDataMask, and v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::kNumRegisters.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreDoubleStackSlot()
void v8::internal::FrameTranslationBuilder::StoreDoubleStackSlot (int index)
Definition at line 515 of file frame-translation-builder.cc.
                                                            {
  auto opcode = TranslationOpcode::DOUBLE_STACK_SLOT;
  Add(opcode, SignedOperand(index));
}
References Add(), and v8::internal::index.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreFloatRegister()
void v8::internal::FrameTranslationBuilder::StoreFloatRegister (FloatRegister reg)
Definition at line 445 of file frame-translation-builder.cc.
                                                                  {
  static_assert(FloatRegister::kNumRegisters - 1 <= base::kDataMask);
  auto opcode = TranslationOpcode::FLOAT_REGISTER;
  Add(opcode, SmallUnsignedOperand(static_cast<uint8_t>(reg.code())));
}
References Add(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::base::kDataMask, and v8::internal::RegisterBase< SwVfpRegister, kSwVfpAfterLast >::kNumRegisters.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreFloatStackSlot()
void v8::internal::FrameTranslationBuilder::StoreFloatStackSlot (int index)
Definition at line 510 of file frame-translation-builder.cc.
                                                           {
  auto opcode = TranslationOpcode::FLOAT_STACK_SLOT;
  Add(opcode, SignedOperand(index));
}
References Add(), and v8::internal::index.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreHoleyDoubleRegister()
void v8::internal::FrameTranslationBuilder::StoreHoleyDoubleRegister (DoubleRegister reg)
Definition at line 457 of file frame-translation-builder.cc.
                                                                         {
  static_assert(DoubleRegister::kNumRegisters - 1 <= base::kDataMask);
  auto opcode = TranslationOpcode::HOLEY_DOUBLE_REGISTER;
  Add(opcode, SmallUnsignedOperand(static_cast<uint8_t>(reg.code())));
}
References Add(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::base::kDataMask, and v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::kNumRegisters.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreHoleyDoubleStackSlot()
void v8::internal::FrameTranslationBuilder::StoreHoleyDoubleStackSlot (int index)
Definition at line 525 of file frame-translation-builder.cc.
                                                                 {
  auto opcode = TranslationOpcode::HOLEY_DOUBLE_STACK_SLOT;
  Add(opcode, SignedOperand(index));
}
References Add(), and v8::internal::index.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreInt32Register()
void v8::internal::FrameTranslationBuilder::StoreInt32Register (Register reg)
Definition at line 409 of file frame-translation-builder.cc.
                                                             {
  auto opcode = TranslationOpcode::INT32_REGISTER;
  StoreRegister(opcode, reg);
}
References StoreRegister().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreInt32StackSlot()
void v8::internal::FrameTranslationBuilder::StoreInt32StackSlot (int index)
Definition at line 474 of file frame-translation-builder.cc.
                                                           {
  auto opcode = TranslationOpcode::INT32_STACK_SLOT;
  Add(opcode, SignedOperand(index));
}
References Add(), and v8::internal::index.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreInt64Register()
void v8::internal::FrameTranslationBuilder::StoreInt64Register (Register reg)
Definition at line 420 of file frame-translation-builder.cc.
                                                             {
  auto opcode = TranslationOpcode::INT64_REGISTER;
  StoreRegister(opcode, reg);
}
References StoreRegister().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreInt64StackSlot()
void v8::internal::FrameTranslationBuilder::StoreInt64StackSlot (int index)
Definition at line 485 of file frame-translation-builder.cc.
                                                           {
  auto opcode = TranslationOpcode::INT64_STACK_SLOT;
  Add(opcode, SignedOperand(index));
}
References Add(), and v8::internal::index.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreIntPtrRegister()
void v8::internal::FrameTranslationBuilder::StoreIntPtrRegister (Register reg)
Definition at line 414 of file frame-translation-builder.cc.
                                                              {
  auto opcode = (kSystemPointerSize == 4) ? TranslationOpcode::INT32_REGISTER
                                          : TranslationOpcode::INT64_REGISTER;
  StoreRegister(opcode, reg);
}
References v8::internal::kSystemPointerSize, and StoreRegister().
StoreIntPtrStackSlot()
void v8::internal::FrameTranslationBuilder::StoreIntPtrStackSlot (int index)
Definition at line 479 of file frame-translation-builder.cc.
                                                            {
  auto opcode = (kSystemPointerSize == 4) ? TranslationOpcode::INT32_STACK_SLOT
                                          : TranslationOpcode::INT64_STACK_SLOT;
  Add(opcode, SignedOperand(index));
}
References Add(), v8::internal::index, and v8::internal::kSystemPointerSize.
StoreJSFrameFunction()
void v8::internal::FrameTranslationBuilder::StoreJSFrameFunction ()
Definition at line 546 of file frame-translation-builder.cc.
                                                   {
  StoreStackSlot((StandardFrameConstants::kCallerPCOffset -
                  StandardFrameConstants::kFunctionOffset) /
                 kSystemPointerSize);
}
References v8::internal::CommonFrameConstants::kCallerPCOffset, v8::internal::StandardFrameConstants::kFunctionOffset, v8::internal::kSystemPointerSize, and StoreStackSlot().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreLiteral()
void v8::internal::FrameTranslationBuilder::StoreLiteral (int literal_id)
Definition at line 530 of file frame-translation-builder.cc.
                                                         {
  auto opcode = TranslationOpcode::LITERAL;
  DCHECK_GE(literal_id, 0);
  Add(opcode, SignedOperand(literal_id));
}
References Add(), and DCHECK_GE.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreOptimizedOut()
void v8::internal::FrameTranslationBuilder::StoreOptimizedOut ()
Definition at line 536 of file frame-translation-builder.cc.
                                                {
  auto opcode = TranslationOpcode::OPTIMIZED_OUT;
  Add(opcode);
}
References Add().
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
StoreRegister() [1/2]
void v8::internal::FrameTranslationBuilder::StoreRegister (Register reg)
Definition at line 404 of file frame-translation-builder.cc.
                                                        {
  auto opcode = TranslationOpcode::REGISTER;
  StoreRegister(opcode, reg);
}
References StoreRegister().
StoreRegister() [2/2]
void v8::internal::FrameTranslationBuilder::StoreRegister (TranslationOpcode opcode, Register reg)
Definition at line 398 of file frame-translation-builder.cc.
                                                          {
  static_assert(Register::kNumRegisters - 1 <= base::kDataMask);
  Add(opcode, SmallUnsignedOperand(static_cast<uint8_t>(reg.code())));
}
References Add(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::base::kDataMask, and v8::internal::RegisterBase< Register, kRegAfterLast >::kNumRegisters.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), StoreBoolRegister(), StoreInt32Register(), StoreInt64Register(), StoreIntPtrRegister(), StoreRegister(), StoreSignedBigInt64Register(), StoreUint32Register(), and StoreUnsignedBigInt64Register().
StoreSignedBigInt64Register()
void v8::internal::FrameTranslationBuilder::StoreSignedBigInt64Register (Register reg)
Definition at line 425 of file frame-translation-builder.cc.
                                                                      {
  auto opcode = TranslationOpcode::SIGNED_BIGINT64_REGISTER;
  StoreRegister(opcode, reg);
}
References StoreRegister().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreSignedBigInt64StackSlot()
void v8::internal::FrameTranslationBuilder::StoreSignedBigInt64StackSlot (int index)
Definition at line 490 of file frame-translation-builder.cc.
                                                                    {
  auto opcode = TranslationOpcode::SIGNED_BIGINT64_STACK_SLOT;
  Add(opcode, SignedOperand(index));
}
References Add(), and v8::internal::index.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreSimd128Register()
void v8::internal::FrameTranslationBuilder::StoreSimd128Register (Simd128Register reg)
Definition at line 463 of file frame-translation-builder.cc.
                                                                      {
  static_assert(DoubleRegister::kNumRegisters - 1 <= base::kDataMask);
  auto opcode = TranslationOpcode::SIMD128_REGISTER;
  Add(opcode, SmallUnsignedOperand(static_cast<uint8_t>(reg.code())));
}
References Add(), v8::internal::RegisterBase< SubType, kAfterLastRegister >::code(), v8::base::kDataMask, and v8::internal::RegisterBase< DoubleRegister, kDoubleAfterLast >::kNumRegisters.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreSimd128StackSlot()
void v8::internal::FrameTranslationBuilder::StoreSimd128StackSlot (int index)
Definition at line 520 of file frame-translation-builder.cc.
                                                             {
  auto opcode = TranslationOpcode::SIMD128_STACK_SLOT;
  Add(opcode, SignedOperand(index));
}
References Add(), and v8::internal::index.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreStackSlot()
void v8::internal::FrameTranslationBuilder::StoreStackSlot (int index)
Definition at line 469 of file frame-translation-builder.cc.
                                                      {
  auto opcode = TranslationOpcode::TAGGED_STACK_SLOT;
  Add(opcode, SignedOperand(index));
}
References Add(), and v8::internal::index.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand(), and StoreJSFrameFunction().
StoreUint32Register()
void v8::internal::FrameTranslationBuilder::StoreUint32Register (Register reg)
Definition at line 435 of file frame-translation-builder.cc.
                                                              {
  auto opcode = TranslationOpcode::UINT32_REGISTER;
  StoreRegister(opcode, reg);
}
References StoreRegister().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreUint32StackSlot()
void v8::internal::FrameTranslationBuilder::StoreUint32StackSlot (int index)
Definition at line 500 of file frame-translation-builder.cc.
                                                            {
  auto opcode = TranslationOpcode::UINT32_STACK_SLOT;
  Add(opcode, SignedOperand(index));
}
References Add(), and v8::internal::index.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreUnsignedBigInt64Register()
void v8::internal::FrameTranslationBuilder::StoreUnsignedBigInt64Register (Register reg)
Definition at line 430 of file frame-translation-builder.cc.
                                                                        {
  auto opcode = TranslationOpcode::UNSIGNED_BIGINT64_REGISTER;
  StoreRegister(opcode, reg);
}
References StoreRegister().
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StoreUnsignedBigInt64StackSlot()
void v8::internal::FrameTranslationBuilder::StoreUnsignedBigInt64StackSlot (int index)
Definition at line 495 of file frame-translation-builder.cc.
                                                                      {
  auto opcode = TranslationOpcode::UNSIGNED_BIGINT64_STACK_SLOT;
  Add(opcode, SignedOperand(index));
}
References Add(), and v8::internal::index.
Referenced by v8::internal::compiler::CodeGenerator::AddTranslationForOperand().
StringConcat()
void v8::internal::FrameTranslationBuilder::StringConcat ()
Definition at line 393 of file frame-translation-builder.cc.
                                           {
  auto opcode = TranslationOpcode::STRING_CONCAT;
  Add(opcode);
}
References Add().
Referenced by v8::internal::compiler::CodeGenerator::TranslateStateValueDescriptor().
ToFrameTranslation()
DirectHandle< DeoptimizationFrameTranslation > v8::internal::FrameTranslationBuilder::ToFrameTranslation (LocalFactory * factory)
Definition at line 209 of file frame-translation-builder.cc.
                                                                 {
#ifdef V8_USE_ZLIB
  if (V8_UNLIKELY(v8_flags.turbo_compress_frame_translations)) {
    const int input_size = SizeInBytes();
    uLongf compressed_data_size = compressBound(input_size);
    ZoneVector<uint8_t> compressed_data(compressed_data_size, zone());
    CHECK_EQ(
        zlib_internal::CompressHelper(
            zlib_internal::ZRAW, compressed_data.data(), &compressed_data_size,
            reinterpret_cast<const Bytef*>(contents_for_compression_.data()),
            input_size, Z_DEFAULT_COMPRESSION, nullptr, nullptr),
        Z_OK);
    const int translation_array_size =
        static_cast<int>(compressed_data_size) +
        DeoptimizationFrameTranslation::kUncompressedSizeSize;
    DirectHandle<DeoptimizationFrameTranslation> result =
        factory->NewDeoptimizationFrameTranslation(translation_array_size);
    result->set_int(DeoptimizationFrameTranslation::kUncompressedSizeOffset,
                    Size());
    std::memcpy(
        result->begin() + DeoptimizationFrameTranslation::kCompressedDataOffset,
        compressed_data.data(), compressed_data_size);
    return result;
  }
#endif
  DCHECK(!v8_flags.turbo_compress_frame_translations);
  FinishPendingInstructionIfNeeded();
  DirectHandle<DeoptimizationFrameTranslation> result =
      factory->NewDeoptimizationFrameTranslation(SizeInBytes());
  if (SizeInBytes() == 0) return result;
  memcpy(result->begin(), contents_.data(), contents_.size() * sizeof(uint8_t));
#ifdef ENABLE_SLOW_DCHECKS
  DeoptimizationFrameTranslation::Iterator iter(*result, 0);
  ValidateBytes(iter);
#endif
  return result;
}
References CHECK_EQ, contents_, contents_for_compression_, v8::internal::ZoneVector< T >::data(), v8::internal::DCHECK(), FinishPendingInstructionIfNeeded(), v8::internal::FactoryBase< Impl >::NewDeoptimizationFrameTranslation(), v8::base::internal::result, Size(), v8::internal::ZoneVector< T >::size(), SizeInBytes(), v8::internal::v8_flags, V8_UNLIKELY, ValidateBytes(), and zone().
Referenced by v8::internal::compiler::CodeGenerator::GenerateDeoptimizationData(), and v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData().
ToFrameTranslationWasm()
base::Vector< const uint8_t > v8::internal::FrameTranslationBuilder::ToFrameTranslationWasm ()
Definition at line 252 of file frame-translation-builder.cc.
                                                                          {
  DCHECK(!v8_flags.turbo_compress_frame_translations);
  FinishPendingInstructionIfNeeded();
  base::Vector<const uint8_t> result = base::VectorOf(contents_);
#ifdef ENABLE_SLOW_DCHECKS
  DeoptTranslationIterator iter(result, 0);
  ValidateBytes(iter);
#endif
  return result;
}
References contents_, v8::internal::DCHECK(), FinishPendingInstructionIfNeeded(), v8::base::internal::result, v8::internal::v8_flags, ValidateBytes(), and v8::base::VectorOf().
ValidateBytes()
void v8::internal::FrameTranslationBuilder::ValidateBytes (DeoptTranslationIterator & iter) const [private]
Definition at line 263 of file frame-translation-builder.cc.
                                          {
#ifdef ENABLE_SLOW_DCHECKS
  if (v8_flags.enable_slow_asserts) {
    // Check that we can read back all of the same content we intended to write.
    for (size_t i = 0; i < all_instructions_.size(); ++i) {
      CHECK(iter.HasNextOpcode());
      const Instruction& instruction = all_instructions_[i];
      CHECK_EQ(instruction.opcode, iter.NextOpcode());
      for (int j = 0; j < TranslationOpcodeOperandCount(instruction.opcode);
           ++j) {
        uint32_t operand = instruction.is_operand_signed[j]
                               ? iter.NextOperand()
                               : iter.NextOperandUnsigned();
        CHECK_EQ(instruction.operands[j], operand);
      }
    }
  }
#endif
}
References CHECK, CHECK_EQ, v8::internal::DeoptTranslationIterator::HasNextOpcode(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::DeoptTranslationIterator::NextOpcode(), v8::internal::DeoptTranslationIterator::NextOperand(), v8::internal::DeoptTranslationIterator::NextOperandUnsigned(), v8::internal::FrameTranslationBuilder::Instruction::opcode, v8::internal::FrameTranslationBuilder::Instruction::operands, v8::internal::TranslationOpcodeOperandCount(), and v8::internal::v8_flags.
Referenced by ToFrameTranslation(), and ToFrameTranslationWasm().
zone()
Zone* v8::internal::FrameTranslationBuilder::zone () const [inline], [private]
Definition at line 150 of file frame-translation-builder.h.
{ return zone_; }
References zone_.
Referenced by ToFrameTranslation().
Member Data Documentation
basis_instructions_
ZoneVector<Instruction> v8::internal::FrameTranslationBuilder::basis_instructions_ [private]
Definition at line 164 of file frame-translation-builder.h.
Referenced by Add(), and BeginTranslation().
contents_
ZoneVector<uint8_t> v8::internal::FrameTranslationBuilder::contents_ [private]
Definition at line 155 of file frame-translation-builder.h.
Referenced by AddRawToContents(), FinishPendingInstructionIfNeeded(), Size(), ToFrameTranslation(), and ToFrameTranslationWasm().
contents_for_compression_
ZoneVector<int32_t> v8::internal::FrameTranslationBuilder::contents_for_compression_ [private]
Definition at line 156 of file frame-translation-builder.h.
Referenced by AddRawToContentsForCompression(), Size(), and ToFrameTranslation().
index_of_basis_translation_start_
int v8::internal::FrameTranslationBuilder::index_of_basis_translation_start_ = 0 [private]
Definition at line 178 of file frame-translation-builder.h.
Referenced by BeginTranslation().
instruction_index_within_translation_
size_t v8::internal::FrameTranslationBuilder::instruction_index_within_translation_ = 0 [private]
Definition at line 174 of file frame-translation-builder.h.
Referenced by Add(), and BeginTranslation().
match_previous_allowed_
bool v8::internal::FrameTranslationBuilder::match_previous_allowed_ = true [private]
Definition at line 181 of file frame-translation-builder.h.
Referenced by Add(), and BeginTranslation().
matching_instructions_count_
size_t v8::internal::FrameTranslationBuilder::matching_instructions_count_ = 0 [private]
Definition at line 171 of file frame-translation-builder.h.
Referenced by Add(), and FinishPendingInstructionIfNeeded().
total_matching_instructions_in_current_translation_
size_t v8::internal::FrameTranslationBuilder::total_matching_instructions_in_current_translation_ = 0 [private]
Definition at line 172 of file frame-translation-builder.h.
Referenced by BeginTranslation(), and FinishPendingInstructionIfNeeded().
zone_
Zone* const v8::internal::FrameTranslationBuilder::zone_ [private]
Definition at line 168 of file frame-translation-builder.h.
Referenced by zone().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/deoptimizer/frame-translation-builder.h
/mnt/V8SourceCode/src/deoptimizer/frame-translation-builder.cc