v8::internal::LocalIsolate Class Reference
#include <local-isolate.h>
Public Types
using HandleScopeType = LocalHandleScope
Public Member Functions
LocalIsolate (Isolate *isolate, ThreadKind kind)
~LocalIsolate ()
bool is_main_thread () const
LocalHeap * heap ()
const LocalHeap * heap () const
Address cage_base () const
Address code_cage_base () const
ReadOnlyHeap * read_only_heap () const
RootsTable & roots_table ()
const RootsTable & roots_table () const
Tagged< Object > root (RootIndex index) const
Handle< Object > root_handle (RootIndex index) const
base::RandomNumberGenerator * fuzzer_rng () const
StringTable * string_table () const
base::Mutex * internalized_string_access ()
base::Mutex * shared_function_info_access ()
const AstStringConstants * ast_string_constants ()
LazyCompileDispatcher * lazy_compile_dispatcher ()
V8FileLogger * main_thread_logger ()
bool is_precise_binary_code_coverage () const
v8::internal::LocalFactory * factory ()
IsolateGroup * isolate_group () const
AccountingAllocator * allocator ()
bool has_exception () const
bool serializer_enabled () const
void RegisterDeserializerStarted ()
void RegisterDeserializerFinished ()
bool has_active_deserializer () const
void Throw (Tagged< Object > exception)
void FatalProcessOutOfHeapMemory (const char *location)
int GetNextScriptId ()
uint32_t GetAndIncNextUniqueSfiId ()
LocalLogger * v8_file_logger () const
ThreadId thread_id () const
Address stack_limit () const
RuntimeCallStats * runtime_call_stats () const
bigint::Processor * bigint_processor ()
Isolate * AsIsolate ()
LocalIsolate * AsLocalIsolate ()
LocalIsolate * shared_space_isolate () const
Isolate * GetMainThreadIsolateUnsafe () const
const v8::StartupData * snapshot_blob () const
Tagged< Object > * pending_message_address ()
int NextOptimizationId ()
template<typename Callback >
void ExecuteMainThreadWhileParked (Callback callback)
template<typename Callback >
void ParkIfOnBackgroundAndExecute (Callback callback)
Static Public Member Functions
static LocalIsolate * FromHeap (LocalHeap *heap)
Private Member Functions
Isolate * ForSandbox ()
void InitializeBigIntProcessor ()
Private Attributes
LocalHeap heap_
Isolate *const isolate_
std::unique_ptr< LocalLogger > logger_
ThreadId const thread_id_
Address const stack_limit_
bigint::Processor * bigint_processor_ {nullptr}
Friends
class v8::internal::LocalFactory
class LocalIsolateFactory
class IsolateForPointerCompression
class IsolateForSandbox
Detailed Description
Definition at line 45 of file local-isolate.h.
Member Typedef Documentation
HandleScopeType
using v8::internal::LocalIsolate::HandleScopeType = LocalHandleScope
Definition at line 47 of file local-isolate.h.
Constructor & Destructor Documentation
LocalIsolate()
v8::internal::LocalIsolate::LocalIsolate (Isolate * isolate, ThreadKind kind) [explicit]
Definition at line 18 of file local-isolate.cc.
    : HiddenLocalFactory(isolate),
      heap_(isolate->heap(), kind),
      isolate_(isolate),
      logger_(new LocalLogger(isolate)),
      thread_id_(ThreadId::Current()),
      stack_limit_(kind == ThreadKind::kMain
                       ? isolate->stack_guard()->real_climit()
                       : GetCurrentStackPosition() - v8_flags.stack_size * KB)
#ifdef V8_INTL_SUPPORT
      ,
      default_locale_(isolate->DefaultLocale())
#endif
{
  // LocalIsolate owning threads need to make sure to match the isolate's FPU
  // state.
  DCHECK_EQ(base::FPU::GetFlushDenormals(), isolate->flush_denormals());
#ifdef V8_RUNTIME_CALL_STATS
  if (kind == ThreadKind::kMain) {
    runtime_call_stats_ = isolate->counters()->runtime_call_stats();
  } else {
    rcs_scope_.emplace(isolate->counters()->worker_thread_runtime_call_stats());
    runtime_call_stats_ = rcs_scope_->Get();
  }
#endif
}
References DCHECK_EQ, v8::base::FPU::GetFlushDenormals(), v8::internal::LocalFactory::isolate(), v8::internal::kMain, and runtime_call_stats().
 LocalIsolate()
v8::internal::LocalIsolate::~LocalIsolate ()
Definition at line 45 of file local-isolate.cc.
                            {
  if (bigint_processor_) bigint_processor_->Destroy();
}
References bigint_processor_, and v8::bigint::Processor::Destroy().
Member Function Documentation
allocator()
AccountingAllocator* v8::internal::LocalIsolate::allocator () [inline]
Definition at line 106 of file local-isolate.h.
{ return isolate_->allocator(); }
AsIsolate()
Isolate* v8::internal::LocalIsolate::AsIsolate () [inline]
Definition at line 147 of file local-isolate.h.
                       {
    DCHECK(is_main_thread());
    DCHECK_EQ(ThreadId::Current(), isolate_->thread_id());
    return isolate_;
  }
References v8::internal::ThreadId::Current(), v8::internal::DCHECK(), and DCHECK_EQ.
Referenced by v8::internal::interpreter::BytecodeGenerator::GenerateBytecode().
AsLocalIsolate()
LocalIsolate* v8::internal::LocalIsolate::AsLocalIsolate () [inline]
Definition at line 152 of file local-isolate.h.
{ return this; }
ast_string_constants()
const AstStringConstants* v8::internal::LocalIsolate::ast_string_constants () [inline]
Definition at line 82 of file local-isolate.h.
                                                   {
    return isolate_->ast_string_constants();
  }
bigint_processor()
bigint::Processor* v8::internal::LocalIsolate::bigint_processor () [inline]
Definition at line 135 of file local-isolate.h.
                                      {
    if (!bigint_processor_) InitializeBigIntProcessor();
    return bigint_processor_;
  }
cage_base()
Address v8::internal::LocalIsolate::cage_base () const [inline]
Definition at line 17 of file local-isolate-inl.h.
{ return isolate_->cage_base(); }
References v8::internal::Isolate::cage_base(), and isolate_.
code_cage_base()
Address v8::internal::LocalIsolate::code_cage_base () const [inline]
Definition at line 19 of file local-isolate-inl.h.
                                           {
  return isolate_->code_cage_base();
}
References v8::internal::Isolate::code_cage_base(), and isolate_.
ExecuteMainThreadWhileParked()
template<typename Callback >
void v8::internal::LocalIsolate::ExecuteMainThreadWhileParked (Callback callback) [inline]
Definition at line 43 of file local-isolate-inl.h.
                                                                           {
  heap_.ExecuteMainThreadWhileParked(callback);
}
References v8::internal::LocalHeap::ExecuteMainThreadWhileParked(), and heap_.
Referenced by v8::Shell::QuitOnce(), v8::internal::Snapshot::SerializeDeserializeAndVerifyForTesting(), and v8::internal::OptimizingCompileDispatcher::WaitUntilCompilationJobsDone().
factory()
v8::internal::LocalFactory* v8::internal::LocalIsolate::factory () [inline]
Definition at line 98 of file local-isolate.h.
                                    {
    // Upcast to the privately inherited base-class using c-style casts to avoid
    // undefined behavior (as static_cast cannot cast across private bases).
    return (v8::internal::LocalFactory*)this;
  }
Referenced by v8::internal::Assembler::AllocateAndInstallRequestedHeapNumbers(), v8::internal::NumberDictionaryBaseShape::AsHandle(), v8::internal::compiler::JSNativeContextSpecialization::Concatenate(), v8::internal::PreparseDataBuilder::ByteData::CopyToLocalHeap(), v8::internal::compiler::JSNativeContextSpecialization::CreateStringConstant(), v8::internal::OffThreadObjectDeserializer::DeserializeSharedFunctionInfo(), v8::internal::maglev::Int32Constant::DoReify(), v8::internal::maglev::Uint32Constant::DoReify(), v8::internal::maglev::IntPtrConstant::DoReify(), v8::internal::maglev::Float64Constant::DoReify(), v8::internal::DeoptimizationData::Empty(), v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData(), v8::internal::DeoptimizationData::New(), v8::internal::TrustedPodArray< T >::New(), v8::internal::PodArray< T >::New(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSAdd(), v8::internal::compiler::JSNativeContextSpecialization::ReduceJSToString(), v8::internal::BackgroundCompileTask::Run(), v8::internal::ZonePreparseData::Serialize(), and v8::internal::anonymous_namespace{lazy-compile-dispatcher.cc}::SetUncompiledDataJobPointer().
FatalProcessOutOfHeapMemory()
void v8::internal::LocalIsolate::FatalProcessOutOfHeapMemory (const char * location) [inline]
Definition at line 116 of file local-isolate.h.
                                                                      {
    UNREACHABLE();
  }
References v8::internal::UNREACHABLE().
ForSandbox()
Isolate* v8::internal::LocalIsolate::ForSandbox () [inline], [private]
Definition at line 189 of file local-isolate.h.
{ return isolate_; }
FromHeap()
static LocalIsolate* v8::internal::LocalIsolate::FromHeap (LocalHeap * heap) [inline], [static]
Definition at line 53 of file local-isolate.h.
                                                 {
    return reinterpret_cast<LocalIsolate*>(reinterpret_cast<Address>(heap) -
                                           OFFSET_OF(LocalIsolate, heap_));
  }
References heap(), and OFFSET_OF.
Referenced by v8::internal::FunctionTemplateInfo::IsTemplateFor().
fuzzer_rng()
base::RandomNumberGenerator* v8::internal::LocalIsolate::fuzzer_rng () const [inline]
Definition at line 71 of file local-isolate.h.
                                                {
    return isolate_->fuzzer_rng();
  }
Referenced by v8::internal::interpreter::BytecodeGenerator::GenerateBytecode().
GetAndIncNextUniqueSfiId()
uint32_t v8::internal::LocalIsolate::GetAndIncNextUniqueSfiId () [inline]
Definition at line 121 of file local-isolate.h.
                                      {
    return isolate_->GetAndIncNextUniqueSfiId();
  }
GetMainThreadIsolateUnsafe()
Isolate* v8::internal::LocalIsolate::GetMainThreadIsolateUnsafe () const [inline]
Definition at line 160 of file local-isolate.h.
{ return isolate_; }
Referenced by v8::internal::compiler::SharedFunctionInfoRef::HasBreakInfo().
GetNextScriptId()
int v8::internal::LocalIsolate::GetNextScriptId ()
Definition at line 59 of file local-isolate.cc.
{ return isolate_->GetNextScriptId(); }
References v8::internal::Isolate::GetNextScriptId(), and isolate_.
has_active_deserializer()
bool v8::internal::LocalIsolate::has_active_deserializer () const
Definition at line 55 of file local-isolate.cc.
                                                 {
  return isolate_->has_active_deserializer();
}
References v8::internal::Isolate::has_active_deserializer(), and isolate_.
has_exception()
bool v8::internal::LocalIsolate::has_exception () const [inline]
Definition at line 108 of file local-isolate.h.
{ return false; }
heap() [1/2]
LocalHeap* v8::internal::LocalIsolate::heap () [inline]
Definition at line 60 of file local-isolate.h.
{ return &heap_; }
Referenced by v8::internal::LocalFactory::AllocationTypeForInPlaceInternalizableString(), v8::internal::maglev::MaglevCodeGenerator::Assemble(), v8::internal::compiler::JSHeapBroker::AttachLocalIsolate(), v8::internal::compiler::JSHeapBroker::AttachLocalIsolateForMaglev(), v8::internal::BackgroundMergeTask::BeginMergeInBackground(), v8::internal::maglev::MaglevGraphBuilder::BuildBody(), v8::internal::maglev::MaglevCodeGenerator::CollectRetainedMaps(), v8::internal::baseline::BaselineBatchCompilerJob::Compile(), v8::internal::maglev::MaglevCompiler::Compile(), v8::internal::compiler::JSHeapBroker::DetachLocalIsolate(), v8::internal::compiler::JSHeapBroker::DetachLocalIsolateForMaglev(), v8::internal::maglev::MaglevCodeGenerator::EmitDeopts(), v8::internal::OptimizedCompilationJob::ExecuteJob(), v8::internal::IsCompiledScope::IsCompiledScope(), v8::internal::SharedStringAccessGuardIfNeeded::IsNeeded(), v8::internal::compiler::anonymous_namespace{pipeline.cc}::LocalIsolateScope::LocalIsolateScope(), v8::internal::Isolate::main_thread_local_heap(), v8::internal::BackgroundDeserializeTask::MergeWithExistingScript(), v8::internal::ParkingThread::ParkedJoin(), v8::internal::ParkingThread::ParkedJoinAll(), v8::internal::ParkingSemaphore::ParkedWait(), v8::internal::ParkingConditionVariable::ParkedWait(), v8::internal::ParkingConditionVariable::ParkedWaitFor(), v8::internal::ParkingSemaphore::ParkedWaitFor(), v8::internal::BackgroundDeserializeTask::Run(), v8::internal::OptimizingCompileTaskExecutor::CompileTask::Run(), v8::internal::maglev::MaglevConcurrentDispatcher::JobTask::Run(), v8::internal::BackgroundCompileTask::Run(), v8::internal::PendingCompilationErrorHandler::MessageDetails::SetString(), v8::internal::CodeSerializer::StartDeserializeOffThread(), and v8::internal::compiler::UnparkedScopeIfNeeded::UnparkedScopeIfNeeded().
heap() [2/2]
const LocalHeap* v8::internal::LocalIsolate::heap () const [inline]
Definition at line 61 of file local-isolate.h.
{ return &heap_; }
InitializeBigIntProcessor()
void v8::internal::LocalIsolate::InitializeBigIntProcessor () [private]
Definition at line 63 of file local-isolate.cc.
                                             {
  bigint_processor_ = bigint::Processor::New(new bigint::Platform());
}
References bigint_processor_, and v8::bigint::Processor::New().
internalized_string_access()
base::Mutex* v8::internal::LocalIsolate::internalized_string_access () [inline]
Definition at line 76 of file local-isolate.h.
                                          {
    return isolate_->internalized_string_access();
  }
Referenced by v8::internal::SharedStringAccessGuardIfNeeded::SharedStringAccessGuardIfNeeded().
is_main_thread()
bool v8::internal::LocalIsolate::is_main_thread () const [inline]
Definition at line 58 of file local-isolate.h.
{ return heap()->is_main_thread(); }
References heap().
Referenced by v8::internal::BackgroundMergeTask::BeginMergeInBackground(), v8::internal::OptimizedCompilationJob::ExecuteJob(), v8::internal::interpreter::BytecodeGenerator::GenerateBytecode(), v8::internal::MutexGuardIfOffThread< LocalIsolate >::MutexGuardIfOffThread(), and ParkIfOnBackgroundAndExecute().
is_precise_binary_code_coverage()
bool v8::internal::LocalIsolate::is_precise_binary_code_coverage () const [inline]
Definition at line 94 of file local-isolate.h.
                                               {
    return isolate_->is_precise_binary_code_coverage();
  }
isolate_group()
IsolateGroup* v8::internal::LocalIsolate::isolate_group () const [inline]
Definition at line 104 of file local-isolate.h.
{ return isolate_->isolate_group(); }
lazy_compile_dispatcher()
LazyCompileDispatcher* v8::internal::LocalIsolate::lazy_compile_dispatcher () [inline]
Definition at line 85 of file local-isolate.h.
                                                   {
    return isolate_->lazy_compile_dispatcher();
  }
main_thread_logger()
V8FileLogger* v8::internal::LocalIsolate::main_thread_logger () [inline]
Definition at line 88 of file local-isolate.h.
                                     {
    // TODO(leszeks): This is needed for logging in ParseInfo. Figure out a way
    // to use the LocalLogger for this instead.
    return isolate_->v8_file_logger();
  }
NextOptimizationId()
int v8::internal::LocalIsolate::NextOptimizationId () [inline]
Definition at line 169 of file local-isolate.h.
{ return isolate_->NextOptimizationId(); }
Referenced by v8::internal::maglev::MaglevCodeGenerator::GenerateDeoptimizationData().
ParkIfOnBackgroundAndExecute()
template<typename Callback >
void v8::internal::LocalIsolate::ParkIfOnBackgroundAndExecute (Callback callback) [inline]
Definition at line 48 of file local-isolate-inl.h.
                                                                           {
  if (is_main_thread()) {
    callback();
  } else {
    heap_.ExecuteBackgroundThreadWhileParked(callback);
  }
}
References v8::internal::LocalHeap::ExecuteBackgroundThreadWhileParked(), heap_, and is_main_thread().
Referenced by v8::internal::interpreter::InterpreterCompilationJob::ExecuteJobImpl(), and v8::internal::Parser::ParseOnBackground().
pending_message_address()
Tagged<Object>* v8::internal::LocalIsolate::pending_message_address () [inline]
Definition at line 165 of file local-isolate.h.
                                            {
    return isolate_->pending_message_address();
  }
read_only_heap()
ReadOnlyHeap * v8::internal::LocalIsolate::read_only_heap () const [inline]
Definition at line 23 of file local-isolate-inl.h.
                                                 {
  return isolate_->read_only_heap();
}
References isolate_, and v8::internal::Isolate::read_only_heap().
RegisterDeserializerFinished()
void v8::internal::LocalIsolate::RegisterDeserializerFinished ()
Definition at line 52 of file local-isolate.cc.
                                                {
  return isolate_->RegisterDeserializerFinished();
}
References isolate_, and v8::internal::Isolate::RegisterDeserializerFinished().
RegisterDeserializerStarted()
void v8::internal::LocalIsolate::RegisterDeserializerStarted ()
Definition at line 49 of file local-isolate.cc.
                                               {
  return isolate_->RegisterDeserializerStarted();
}
References isolate_, and v8::internal::Isolate::RegisterDeserializerStarted().
root()
Tagged< Object > v8::internal::LocalIsolate::root (RootIndex index) const [inline]
Definition at line 32 of file local-isolate-inl.h.
                                                       {
  DCHECK(RootsTable::IsImmortalImmovable(index));
  return isolate_->root(index);
}
References v8::internal::DCHECK(), v8::internal::index, v8::internal::RootsTable::IsImmortalImmovable(), isolate_, and v8::internal::Isolate::root().
Referenced by v8::internal::maglev::MaglevGraphBuilder::GetTruncatedInt32ForToNumber(), and v8::internal::maglev::MaglevGraphBuilder::TryGetFloat64Constant().
root_handle()
Handle< Object > v8::internal::LocalIsolate::root_handle (RootIndex index) const [inline]
Definition at line 37 of file local-isolate-inl.h.
                                                              {
  DCHECK(RootsTable::IsImmortalImmovable(index));
  return isolate_->root_handle(index);
}
References v8::internal::DCHECK(), v8::internal::index, v8::internal::RootsTable::IsImmortalImmovable(), isolate_, and v8::internal::Isolate::root_handle().
Referenced by v8::internal::maglev::RootConstant::DoReify().
roots_table() [1/2]
RootsTable & v8::internal::LocalIsolate::roots_table () [inline]
Definition at line 27 of file local-isolate-inl.h.
{ return isolate_->roots_table(); }
References isolate_, and v8::internal::Isolate::roots_table().
roots_table() [2/2]
const RootsTable & v8::internal::LocalIsolate::roots_table () const [inline]
Definition at line 28 of file local-isolate-inl.h.
                                                  {
  return isolate_->roots_table();
}
References isolate_, and v8::internal::Isolate::roots_table().
runtime_call_stats()
RuntimeCallStats* v8::internal::LocalIsolate::runtime_call_stats () const [inline]
Definition at line 133 of file local-isolate.h.
{ return nullptr; }
Referenced by LocalIsolate(), v8::internal::maglev::MaglevConcurrentDispatcher::JobTask::Run(), and v8::internal::OptimizingCompileTaskExecutor::RunCompilationJob().
serializer_enabled()
bool v8::internal::LocalIsolate::serializer_enabled () const [inline]
Definition at line 109 of file local-isolate.h.
{ return isolate_->serializer_enabled(); }
shared_function_info_access()
base::Mutex* v8::internal::LocalIsolate::shared_function_info_access () [inline]
Definition at line 79 of file local-isolate.h.
                                           {
    return isolate_->shared_function_info_access();
  }
Referenced by v8::internal::compiler::SharedFunctionInfoRef::HasBreakInfo().
shared_space_isolate()
LocalIsolate* v8::internal::LocalIsolate::shared_space_isolate () const [inline]
Definition at line 154 of file local-isolate.h.
                                             {
    return isolate_->shared_space_isolate()->main_thread_local_isolate();
  }
References shared_space_isolate().
Referenced by shared_space_isolate().
snapshot_blob()
const v8::StartupData* v8::internal::LocalIsolate::snapshot_blob () const [inline]
Definition at line 162 of file local-isolate.h.
                                             {
    return isolate_->snapshot_blob();
  }
Referenced by v8::internal::SerializedCodeData::FromCachedDataWithoutSource().
stack_limit()
Address v8::internal::LocalIsolate::stack_limit () const [inline]
Definition at line 129 of file local-isolate.h.
{ return stack_limit_; }
Referenced by v8::internal::StackLimitCheck::HasOverflowed().
string_table()
StringTable* v8::internal::LocalIsolate::string_table () const [inline]
Definition at line 75 of file local-isolate.h.
{ return isolate_->string_table(); }
thread_id()
ThreadId v8::internal::LocalIsolate::thread_id () const [inline]
Definition at line 128 of file local-isolate.h.
{ return thread_id_; }
Throw()
void v8::internal::LocalIsolate::Throw (Tagged< Object > exception) [inline]
Definition at line 115 of file local-isolate.h.
{ UNREACHABLE(); }
References v8::internal::UNREACHABLE().
v8_file_logger()
LocalLogger* v8::internal::LocalIsolate::v8_file_logger () const [inline]
Definition at line 127 of file local-isolate.h.
{ return logger_.get(); }
Friends And Related Function Documentation
IsolateForPointerCompression
friend class IsolateForPointerCompression [friend]
Definition at line 185 of file local-isolate.h.
IsolateForSandbox
friend class IsolateForSandbox [friend]
Definition at line 186 of file local-isolate.h.
LocalIsolateFactory
friend class LocalIsolateFactory [friend]
Definition at line 184 of file local-isolate.h.
v8::internal::LocalFactory
friend class v8::internal::LocalFactory [friend]
Definition at line 183 of file local-isolate.h.
Member Data Documentation
bigint_processor_
bigint::Processor* v8::internal::LocalIsolate::bigint_processor_ {nullptr} [private]
Definition at line 203 of file local-isolate.h.
Referenced by InitializeBigIntProcessor(), and ~LocalIsolate().
heap_
LocalHeap v8::internal::LocalIsolate::heap_ [private]
Definition at line 193 of file local-isolate.h.
Referenced by ExecuteMainThreadWhileParked(), and ParkIfOnBackgroundAndExecute().
isolate_
Isolate* const v8::internal::LocalIsolate::isolate_ [private]
Definition at line 197 of file local-isolate.h.
Referenced by cage_base(), code_cage_base(), GetNextScriptId(), has_active_deserializer(), read_only_heap(), RegisterDeserializerFinished(), RegisterDeserializerStarted(), root(), root_handle(), and roots_table().
logger_
std::unique_ptr<LocalLogger> v8::internal::LocalIsolate::logger_ [private]
Definition at line 199 of file local-isolate.h.
stack_limit_
Address const v8::internal::LocalIsolate::stack_limit_ [private]
Definition at line 201 of file local-isolate.h.
thread_id_
ThreadId const v8::internal::LocalIsolate::thread_id_ [private]
Definition at line 200 of file local-isolate.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/execution/local-isolate.h
/mnt/V8SourceCode/src/execution/local-isolate-inl.h
/mnt/V8SourceCode/src/execution/local-isolate.cc