v8::internal::wasm::WasmCodeLookupCache Class Reference
#include <wasm-code-manager.h>
Classes
struct CacheEntry
Public Member Functions
WasmCodeLookupCache ()
WasmCodeLookupCache (const WasmCodeLookupCache &)=delete
WasmCodeLookupCache & operator= (const WasmCodeLookupCache &)=delete
Private Member Functions
void Flush ()
CacheEntry * GetCacheEntry (Address pc)
Private Attributes
friend WasmCodeManager
CacheEntry cache_ [kWasmCodeLookupCacheSize]
Static Private Attributes
static const int kWasmCodeLookupCacheSize = 1024
Detailed Description
Definition at line 1297 of file wasm-code-manager.h.
Constructor & Destructor Documentation
WasmCodeLookupCache() [1/2]
v8::internal::wasm::WasmCodeLookupCache::WasmCodeLookupCache () [inline]
Definition at line 1301 of file wasm-code-manager.h.
{ Flush(); }
References Flush().
WasmCodeLookupCache() [2/2]
v8::internal::wasm::WasmCodeLookupCache::WasmCodeLookupCache (const WasmCodeLookupCache &) [delete]
Member Function Documentation
Flush()
void v8::internal::wasm::WasmCodeLookupCache::Flush () [private]
Definition at line 3063 of file wasm-code-manager.cc.
                                {
  for (int i = 0; i < kWasmCodeLookupCacheSize; i++)
    cache_[i].pc.store(kNullAddress, std::memory_order_release);
}
References cache_, v8::internal::kNullAddress, and kWasmCodeLookupCacheSize.
Referenced by WasmCodeLookupCache().
GetCacheEntry()
WasmCodeLookupCache::CacheEntry * v8::internal::wasm::WasmCodeLookupCache::GetCacheEntry (Address pc) [private]
Definition at line 3068 of file wasm-code-manager.cc.
                {
  static_assert(base::bits::IsPowerOfTwo(kWasmCodeLookupCacheSize));
  DCHECK(pc != kNullAddress);
  uint32_t hash = ComputeAddressHash(pc);
  uint32_t index = hash & (kWasmCodeLookupCacheSize - 1);
  CacheEntry* entry = &cache_[index];
  if (entry->pc.load(std::memory_order_acquire) == pc) {
    // Code can be deallocated at two points:
    // - when the NativeModule that references it is garbage-
    // collected;
    // - when it is no longer referenced by its NativeModule, nor from
    // any stack.
    // The cache is cleared when a NativeModule is destroyed, and when
    // the isolate reports the set of code referenced from its stacks.
    // So, if the code is the cache, it is because it was live at some
    // point (when inserted in the cache), its native module is still
    // considered live, and it has not yet been reported as no longer
    // referenced from any stack. It thus cannot have been released
    // yet.
#ifdef DEBUG
    wasm::WasmCodeRefScope code_ref_scope;
    DCHECK_EQ(entry->code, wasm::GetWasmCodeManager()->LookupCode(pc));
#endif // DEBUG
  } else {
    // For WebAssembly frames we perform a lookup in the handler table.
    // This code ref scope is here to avoid a check failure when looking up
    // the code. It's not actually necessary to keep the code alive as it's
    // currently being executed.
    wasm::WasmCodeRefScope code_ref_scope;
    entry->pc.store(pc, std::memory_order_release);
    entry->code = wasm::GetWasmCodeManager()->LookupCode(pc);
    entry->safepoint_entry.Reset();
  }
  return entry;
}
References cache_, v8::internal::ComputeAddressHash(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::wasm::GetWasmCodeManager(), v8::internal::index, v8::base::bits::IsPowerOfTwo(), v8::internal::kNullAddress, kWasmCodeLookupCacheSize, and v8::internal::wasm::WasmCodeManager::LookupCode().
operator=()
WasmCodeLookupCache& v8::internal::wasm::WasmCodeLookupCache::operator= (const WasmCodeLookupCache &) [delete]
Member Data Documentation
cache_
CacheEntry v8::internal::wasm::WasmCodeLookupCache::cache_[kWasmCodeLookupCacheSize] [private]
Definition at line 1318 of file wasm-code-manager.h.
Referenced by Flush(), and GetCacheEntry().
kWasmCodeLookupCacheSize
const int v8::internal::wasm::WasmCodeLookupCache::kWasmCodeLookupCacheSize = 1024 [static], [private]
Definition at line 1317 of file wasm-code-manager.h.
Referenced by Flush(), and GetCacheEntry().
WasmCodeManager
friend v8::internal::wasm::WasmCodeLookupCache::WasmCodeManager [private]
Definition at line 1298 of file wasm-code-manager.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/wasm-code-manager.h
/mnt/V8SourceCode/src/wasm/wasm-code-manager.cc