v8::Utils Class Reference
#include <api.h>
Static Public Member Functions
static bool ApiCheck (bool condition, const char *location, const char *message)
static void ReportOOMFailure (i::Isolate *isolate, const char *location, const OOMDetails &details)
template<typename T >
static MaybeLocal< T > ToMaybe (Local< T > value)
template<template< typename > typename HandleType, typename From >
requires static std::is_convertible_v< HandleType< From >, i::MaybeDirectHandle< From > > auto ToMaybeLocal (HandleType< From > maybe_obj_in) -> decltype(ToMaybe(ToLocal(std::declval< i::DirectHandle< From >>())))
template<class From , class To >
static Local< To > Convert (i::DirectHandle< From > obj)
template<class T >
static i::Handle< i::Object > OpenPersistent (const v8::PersistentBase< T > &persistent)
template<class T >
static i::DirectHandle< i::Object > OpenPersistent (v8::Persistent< T > *persistent)
template<class From , class To >
static i::Handle< To > OpenHandle (v8::Local< From > handle)
template<class From , class To >
static i::DirectHandle< To > OpenDirectHandle (v8::Local< From > handle)
Static Private Member Functions
V8_NOINLINE static V8_PRESERVE_MOST void ReportApiFailure (const char *location, const char *message)
Detailed Description
Definition at line 212 of file api.h.
Member Function Documentation
ApiCheck()
static bool v8::Utils::ApiCheck (bool condition, const char * location, const char * message) [inline], [static]
Definition at line 214 of file api.h.
                                                      {
    if (V8_UNLIKELY(!condition)) {
      Utils::ReportApiFailure(location, message);
    }
    return condition;
  }
References ReportApiFailure(), and V8_UNLIKELY.
Referenced by v8::Function::Call(), v8::Context::CheckCast(), v8::FixedArray::CheckCast(), v8::PrimitiveArray::CheckCast(), v8::ModuleRequest::CheckCast(), v8::Module::CheckCast(), v8::Private::CheckCast(), v8::Name::CheckCast(), v8::Symbol::CheckCast(), v8::FunctionTemplate::CheckCast(), v8::ObjectTemplate::CheckCast(), v8::DictionaryTemplate::CheckCast(), v8::Signature::CheckCast(), v8::Value::CheckCast(), v8::CppHeapExternal::CheckCast(), v8::Boolean::CheckCast(), v8::String::CheckCast(), v8::Numeric::CheckCast(), v8::Number::CheckCast(), v8::Integer::CheckCast(), v8::Int32::CheckCast(), v8::Uint32::CheckCast(), v8::BigInt::CheckCast(), v8::External::CheckCast(), v8::debug::AccessorPair::CheckCast(), v8::ArrayBuffer::CheckCast(), v8::ArrayBufferView::CheckCast(), v8::DataView::CheckCast(), v8::SharedArrayBuffer::CheckCast(), v8::Array::CheckCast(), v8::Map::CheckCast(), v8::Set::CheckCast(), v8::Date::CheckCast(), v8::Function::CheckCast(), v8::Object::CheckCast(), v8::NumberObject::CheckCast(), v8::BigIntObject::CheckCast(), v8::BooleanObject::CheckCast(), v8::StringObject::CheckCast(), v8::SymbolObject::CheckCast(), v8::Promise::Resolver::CheckCast(), v8::Promise::CheckCast(), v8::Proxy::CheckCast(), v8::RegExp::CheckCast(), v8::TypedArray::CheckCast(), v8::Float16Array::CheckCast(), v8::WasmModuleObject::CheckCast(), v8::WasmMemoryObject::CheckCast(), v8::WasmMemoryMapDescriptor::CheckCast(), v8::String::ValueView::CheckOneByte(), v8::WasmModuleObject::Compile(), v8::ScriptCompiler::Compile(), v8::ScriptCompiler::CompileModule(), v8::ScriptCompiler::CompileUnboundScript(), v8::ScriptCompiler::CreateCodeCache(), v8::ScriptCompiler::CreateCodeCacheForFunction(), v8::Isolate::Deinitialize(), v8::ArrayBuffer::Detach(), v8::Isolate::Dispose(), v8::EmbedderDataFor(), v8::anonymous_namespace{api.cc}::EnsureNotPublished(), v8::Module::Evaluate(), v8::Context::Exit(), v8::internal::HandleScope::Extend(), v8::api_internal::FromJustIsNothing(), v8::PrimitiveArray::Get(), v8::anonymous_namespace{api.cc}::GetAlignedPointerFromEmbedderDataInCreationContextImpl(), v8::anonymous_namespace{api.cc}::GetCreationContextCheckedImpl(), v8::Module::GetException(), v8::api_internal::GetFunctionTemplateData(), v8::Context::GetMicrotaskQueue(), v8::Module::GetModuleNamespace(), v8::Context::GetNumberOfEmbedderDataFields(), v8::internal::anonymous_namespace{js-objects.cc}::GetPropertyDescriptorWithInterceptor(), v8::Module::GetStalledTopLevelAwaitMessages(), v8::Module::GetUnboundModuleScript(), v8::FunctionTemplate::Inherit(), v8::HandleScope::Initialize(), v8::internal::Genesis::InstallExtension(), v8::Value::InstanceOf(), v8::FunctionTemplate::InstanceTemplate(), v8::InternalFieldOK(), v8::api_internal::InternalFieldOutOfBounds(), v8::Value::IsFloat16Array(), v8::Module::IsGraphAsync(), v8::FunctionTemplate::New(), v8::PrimitiveArray::New(), v8::Object::New(), v8::ArrayBuffer::New(), v8::SharedArrayBuffer::New(), v8::WasmMemoryMapDescriptor::New(), v8::Float16Array::New(), v8::SharedArrayBuffer::NewBackingStore(), v8::ArrayBuffer::NewBackingStore(), v8::Context::NewRemoteContext(), v8::FunctionTemplate::NewRemoteInstance(), v8::ArrayBuffer::NewResizableBackingStore(), v8::RegExp::NewWithBacktrackLimit(), v8::FunctionTemplate::NewWithCFunctionOverloads(), v8::Isolate::RequestGarbageCollectionForTesting(), v8::Promise::Result(), v8::Module::ScriptId(), v8::CpuProfile::Serialize(), v8::HeapSnapshot::Serialize(), v8::PrimitiveArray::Set(), v8::Template::Set(), v8::Template::SetAccessorProperty(), v8::Context::SetAlignedPointerInEmbedderData(), v8::Object::SetAlignedPointerInInternalField(), v8::Object::SetAlignedPointerInInternalFields(), v8::ObjectTemplate::SetInternalFieldCount(), v8::Context::SetMicrotaskQueue(), v8::Context::SetPromiseHooks(), v8::FunctionTemplate::SetPrototypeProviderTemplate(), v8::Module::SetSyntheticModuleExport(), v8::Context::SlowGetAlignedPointerFromEmbedderData(), v8::Object::SlowGetAlignedPointerFromInternalField(), v8::Module::SourceOffsetToLocation(), v8::ScriptCompiler::StartStreaming(), v8::JSON::Stringify(), v8::api_internal::ToLocalEmpty(), v8::internal::VerifyHandleIsNonEmpty(), and v8::ScriptOrigin::VerifyHostDefinedOptions().
Convert()
template<class From , class To >
Local< To > v8::Utils::Convert (i::DirectHandle< From > obj) [inline], [static]
Definition at line 56 of file api-inl.h.
                                                       {
  DCHECK(obj.is_null() || IsSmi(*obj) || !IsTheHole(*obj));
#ifdef V8_ENABLE_DIRECT_HANDLE
  if (obj.is_null()) return Local<To>();
  return Local<To>::FromAddress(obj.address());
#else
  // This simply uses the location of the indirect handle wrapped inside a
  // "fake" direct handle.
  return Local<To>::FromSlot(indirect_handle(obj).location());
#endif
}
References v8::internal::DirectHandle< T >::address(), DCHECK, v8::Local< T >::FromSlot(), v8::internal::indirect_handle(), v8::internal::DirectHandle< T >::is_null(), and v8::internal::IsSmi().
OpenDirectHandle()
template<class From , class To >
static i::DirectHandle<To> v8::Utils::OpenDirectHandle (v8::Local< From > handle) [inline], [static]
Definition at line 299 of file api.h.
                                                                         {
    return OpenDirectHandle(*handle);
  }
References v8::internal::handle().
Referenced by v8::Set::Add(), v8::SnapshotCreator::AddContext(), v8::SnapshotCreator::AddData(), v8::Isolate::AddMessageListenerWithErrorLevel(), v8::anonymous_namespace{api.cc}::AddPropertiesAndElementsToObject(), v8::internal::interpreter::BytecodeGenerator::AllocateDeferredConstants(), v8::Context::AllowCodeGenerationFromStrings(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ArgumentToCompileOptions(), v8::Map::AsArray(), v8::Set::AsArray(), v8::UnboundScript::BindToCurrentContext(), v8::Value::BooleanValue(), v8::ArrayBufferView::Buffer(), v8::WasmMemoryObject::Buffer(), v8::ArrayBufferView::ByteLength(), v8::ArrayBuffer::ByteLength(), v8::SharedArrayBuffer::ByteLength(), v8::ArrayBufferView::ByteOffset(), v8::Function::Call(), v8::Object::CallAsConstructor(), v8::Object::CallAsFunction(), v8::CALLBACK_SETTER(), v8::CallDepthScope< do_callback >::CallDepthScope(), v8::String::CanMakeExternal(), v8::debug::GeneratorObject::Cast(), v8::Promise::Catch(), v8::Context::CheckCast(), v8::FixedArray::CheckCast(), v8::PrimitiveArray::CheckCast(), v8::ModuleRequest::CheckCast(), v8::Module::CheckCast(), v8::Private::CheckCast(), v8::Name::CheckCast(), v8::Symbol::CheckCast(), v8::FunctionTemplate::CheckCast(), v8::ObjectTemplate::CheckCast(), v8::DictionaryTemplate::CheckCast(), v8::Signature::CheckCast(), v8::Boolean::CheckCast(), v8::String::CheckCast(), v8::Numeric::CheckCast(), v8::Number::CheckCast(), v8::Integer::CheckCast(), v8::debug::AccessorPair::CheckCast(), v8::ArrayBuffer::CheckCast(), v8::ArrayBufferView::CheckCast(), v8::DataView::CheckCast(), v8::SharedArrayBuffer::CheckCast(), v8::Array::CheckCast(), v8::Map::CheckCast(), v8::Set::CheckCast(), v8::Date::CheckCast(), v8::Function::CheckCast(), v8::Object::CheckCast(), v8::NumberObject::CheckCast(), v8::BigIntObject::CheckCast(), v8::BooleanObject::CheckCast(), v8::StringObject::CheckCast(), v8::SymbolObject::CheckCast(), v8::RegExp::CheckCast(), v8::TypedArray::CheckCast(), v8::Float16Array::CheckCast(), v8::internal::FutexEmulation::CleanupAsyncWaiterPromise(), v8::Map::Clear(), v8::Set::Clear(), v8::Object::Clone(), v8::ScriptCompiler::CompileFunction(), v8::ScriptCompiler::CompileModule(), v8::internal::Genesis::ConfigureGlobalObject(), v8::String::ContainsOnlyOneByte(), v8::debug::Script::ContextId(), v8::CopyAndConvertArrayToCppBuffer(), v8::ArrayBufferView::CopyContents(), v8::debug::PropertyIterator::Create(), v8::internal::ApiNatives::CreateAccessorFunctionTemplateInfo(), v8::ScriptCompiler::CreateCodeCacheForFunction(), v8::Object::CreateDataProperty(), v8::CreateEnvironment(), v8::internal::ExternalizeStringExtension::CreateExternalizableString(), v8::internal::ExternalizeStringExtension::CreateExternalizableTwoByteString(), v8::debug::ScopeIterator::CreateForFunction(), v8::anonymous_namespace{api.cc}::CreateInterceptorInfo(), v8::debug::CreateMessageFromException(), v8::internal::Genesis::CreateNewGlobals(), v8::internal::anonymous_namespace{templates.cc}::CreateSlowJSObjectWithProperties(), v8::internal::CreateSnapshotDataBlobInternal(), v8::Module::CreateSyntheticModule(), v8::ArrayBuffer::Data(), v8::SharedArrayBuffer::Data(), v8::debug::Script::DebugId(), v8::Context::DeepFreeze(), v8::Object::DefineOwnProperty(), v8::Object::DefineProperty(), v8::Map::Delete(), v8::Set::Delete(), v8::Object::Delete(), v8::Object::DeletePrivate(), v8::Symbol::Description(), v8::ArrayBuffer::Detach(), v8::Context::DetachGlobal(), v8::EmbedderDataFor(), v8::internal::EmbedderState::EmbedderState(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EncodeExceptionValues(), v8::debug::Script::EndColumn(), v8::debug::Script::EndLine(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::EnforceBigIntUint64(), v8::Isolate::EnqueueMicrotask(), v8::internal::MicrotaskQueue::EnqueueMicrotask(), v8::anonymous_namespace{api.cc}::EnsureConstructor(), v8::Context::Enter(), v8::Value::Equals(), v8::Message::ErrorLevel(), v8::debug::EstimatedValueSize(), v8::api_internal::Eternalize(), v8::internal::SyntheticModule::Evaluate(), v8::internal::DebugStackTraceIterator::Evaluate(), v8::RegExp::Exec(), v8::Shell::ExecuteString(), v8::Context::Exit(), v8::Function::Experimental_IsNopFunction(), v8::internal::ExternalizeStringExtension::Externalize(), v8::internal::ExtractEmbedderDataBackref(), v8::Object::FindInstanceInPrototypeChain(), v8::Value::FullIsFalse(), v8::Value::FullIsNull(), v8::Value::FullIsString(), v8::Value::FullIsTrue(), v8::Value::FullIsUndefined(), v8::debug::GeneratorObject::Function(), v8::Function::FunctionProtoToString(), v8::internal::Genesis::Genesis(), v8::Message::Get(), v8::PrimitiveArray::Get(), v8::FixedArray::Get(), v8::Map::Get(), v8::Object::Get(), v8::debug::EphemeronTable::Get(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetAddressType(), v8::Object::GetAlignedPointerFromEmbedderDataInCreationContext(), v8::ArrayBuffer::GetBackingStore(), v8::SharedArrayBuffer::GetBackingStore(), v8::debug::GetBigIntDescription(), v8::debug::GetBigIntStringValue(), v8::Function::GetBoundFunction(), v8::UnboundScript::GetColumnNumber(), v8::WasmModuleObject::GetCompiledModule(), v8::CompileHintsCollector::GetCompileHints(), v8::Script::GetCompileHintsCollector(), v8::Object::GetConstructorName(), v8::ArrayBufferView::GetContents(), v8::metrics::Recorder::GetContextId(), v8::debug::GetContextId(), v8::debug::GetCreationContext(), v8::Object::GetCreationContext(), v8::Object::GetCreationContextChecked(), v8::Context::GetDataFromSnapshotOnce(), v8::debug::GetDateDescription(), v8::debug::GetDebuggingId(), v8::Function::GetDebugName(), v8::Message::GetEndColumn(), v8::Message::GetEndPosition(), v8::Module::GetException(), v8::String::GetExternalOneByteStringResource(), v8::String::GetExternalStringResourceBaseSlow(), v8::String::GetExternalStringResourceSlow(), v8::Context::GetExtrasBindingObject(), v8::RegExp::GetFlags(), v8::StackTrace::GetFrame(), v8::StackTrace::GetFrameCount(), v8::FunctionTemplate::GetFunction(), v8::StackFrame::GetFunctionName(), v8::api_internal::GetFunctionTemplateData(), v8::Proxy::GetHandler(), v8::Value::GetHash(), v8::StackTrace::GetID(), v8::UnboundScript::GetId(), v8::Object::GetIdentityHash(), v8::Name::GetIdentityHash(), v8::Module::GetIdentityHash(), v8::ModuleRequest::GetImportAttributes(), v8::internal::Isolate::GetIncumbentContextSlow(), v8::Function::GetInferredName(), v8::debug::GetInternalProperties(), v8::UnboundScript::GetLineNumber(), v8::Message::GetLineNumber(), v8::StackFrame::GetLocation(), v8::debug::GetMessageFromPromise(), v8::Context::GetMicrotaskQueue(), v8::Module::GetModuleRequests(), v8::Function::GetName(), v8::Context::GetNumberOfEmbedderDataFields(), v8::HeapProfiler::GetObjectId(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetOptionalAddressValue(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::GetOrCreateDebugProxyMap(), v8::Object::GetOwnPropertyDescriptor(), v8::ModuleRequest::GetPhase(), v8::debug::GetPrivateMembers(), v8::Script::GetProducedCompileHints(), v8::Promise::Resolver::GetPromise(), v8::Object::GetPropertyAttributes(), v8::Object::GetPropertyNames(), v8::Object::GetPrototypeV2(), v8::Object::GetRealNamedProperty(), v8::Object::GetRealNamedPropertyAttributes(), v8::Object::GetRealNamedPropertyAttributesInPrototypeChain(), v8::Object::GetRealNamedPropertyInPrototypeChain(), v8::ScriptOrModule::GetResourceName(), v8::Script::GetResourceName(), v8::Function::GetScriptColumnNumber(), v8::StackFrame::GetScriptId(), v8::Function::GetScriptLineNumber(), v8::Function::GetScriptLocation(), v8::UnboundScript::GetScriptName(), v8::StackFrame::GetScriptName(), v8::StackFrame::GetScriptNameOrSourceURL(), v8::Function::GetScriptOrigin(), v8::Message::GetScriptOrigin(), v8::StackFrame::GetScriptSource(), v8::StackFrame::GetScriptSourceMappingURL(), v8::Function::GetScriptStartPosition(), v8::Context::GetSecurityToken(), v8::debug::Script::GetSha256Hash(), v8::ValueSerializer::Delegate::GetSharedArrayBufferId(), v8::internal::ETWJITInterface::GetSharedFunctionInfo(), v8::RegExp::GetSource(), v8::Message::GetSource(), v8::Message::GetSourceLine(), v8::debug::Script::GetSourceLocation(), v8::UnboundScript::GetSourceMappingURL(), v8::UnboundModuleScript::GetSourceMappingURL(), v8::ModuleRequest::GetSourceOffset(), v8::debug::Script::GetSourceOffset(), v8::UnboundScript::GetSourceURL(), v8::UnboundModuleScript::GetSourceURL(), v8::ModuleRequest::GetSpecifier(), v8::Message::GetStackTrace(), v8::Exception::GetStackTrace(), v8::Module::GetStalledTopLevelAwaitMessages(), v8::Message::GetStartColumn(), v8::Message::GetStartPosition(), v8::Module::GetStatus(), v8::Proxy::GetTarget(), v8::debug::AccessorPair::getter(), v8::Module::GetUnboundModuleScript(), v8::Script::GetUnboundScript(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::Message::GetWasmFunctionIndex(), v8::anonymous_namespace{d8.cc}::GetWorkerFromInternalField(), v8::Context::Global(), v8::debug::GlobalLexicalScopeNames(), v8::internal::anonymous_namespace{builtins-api.cc}::HandleApiCallHelper(), v8::Map::Has(), v8::Set::Has(), v8::Object::Has(), v8::ArrayBufferView::HasBuffer(), v8::Promise::HasHandler(), v8::Object::HasIndexedLookupInterceptor(), v8::FunctionTemplate::HasInstance(), v8::Object::HasNamedLookupInterceptor(), v8::Object::HasOwnProperty(), v8::Object::HasRealIndexedProperty(), v8::Object::HasRealNamedCallbackProperty(), v8::Object::HasRealNamedProperty(), v8::Context::HasTemplateLiteralObject(), v8::Module::HasTopLevelAwait(), v8::ScriptOrModule::HostDefinedOptions(), v8::debug::Script::Id(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::ImportsAsMaybeReceiver(), v8::FunctionTemplate::Inherit(), v8::Value::InstanceOf(), v8::FunctionTemplate::InstanceTemplate(), v8::Value::Int32Value(), v8::BigInt::Int64Value(), v8::Value::IntegerValue(), v8::Object::InternalFieldCount(), v8::ObjectTemplate::InternalFieldCount(), v8::String::InternalizeString(), v8::internal::anonymous_namespace{execution.cc}::InvokeWithTryCatch(), v8::debug::AccessorPair::IsAccessorPair(), v8::Object::IsApiWrapper(), v8::Value::IsArray(), v8::Value::IsArrayBuffer(), v8::Value::IsArrayBufferView(), v8::Value::IsAsyncFunction(), v8::Value::IsBigInt(), v8::Value::IsBoolean(), v8::Object::IsCallable(), v8::Context::IsCodeGenerationFromStringsAllowed(), v8::ObjectTemplate::IsCodeLike(), v8::Object::IsCodeLike(), v8::StackFrame::IsConstructor(), v8::Object::IsConstructor(), v8::Data::IsContext(), v8::Data::IsCppHeapExternal(), v8::Value::IsDataView(), v8::ArrayBuffer::IsDetachable(), v8::debug::Script::IsEmbedded(), v8::StackFrame::IsEval(), v8::String::IsExternal(), v8::Value::IsExternal(), v8::String::IsExternalOneByte(), v8::String::IsExternalTwoByte(), v8::Data::IsFixedArray(), v8::Value::IsFloat16Array(), v8::Value::IsFunction(), v8::Data::IsFunctionTemplate(), v8::Value::IsGeneratorFunction(), v8::Value::IsGeneratorObject(), v8::Module::IsGraphAsync(), v8::ValueSerializer::Delegate::IsHostObject(), v8::ObjectTemplate::IsImmutableProto(), v8::Value::IsInt32(), v8::FunctionTemplate::IsLeafTemplateForApiObject(), v8::Value::IsMapIterator(), v8::Data::IsModule(), v8::debug::Script::IsModule(), v8::Value::IsModuleNamespaceObject(), v8::Data::IsModuleRequest(), v8::Value::IsName(), v8::Value::IsNativeError(), v8::Value::IsNumber(), v8::Value::IsObject(), v8::Data::IsObjectTemplate(), v8::String::IsOneByte(), v8::internal::ExternalizeStringExtension::IsOneByte(), v8::Message::IsOpaque(), v8::Value::IsPrimitive(), v8::Data::IsPrivate(), v8::Value::IsPromise(), v8::Value::IsProxy(), v8::Value::IsRegExp(), v8::ArrayBuffer::IsResizableByUserJavaScript(), v8::Proxy::IsRevoked(), v8::Value::IsSetIterator(), v8::Value::IsSharedArrayBuffer(), v8::Message::IsSharedCrossOrigin(), v8::Module::IsSourceTextModule(), v8::debug::GeneratorObject::IsSuspended(), v8::Value::IsSymbol(), v8::Module::IsSyntheticModule(), v8::Value::IsTypedArray(), v8::Value::IsUint32(), v8::Object::IsUndetectable(), v8::StackFrame::IsUserJavaScript(), v8::Data::IsValue(), v8::Array::Iterate(), v8::debug::ScriptSource::JavaScriptCode(), v8::TypedArray::Length(), v8::Array::Length(), v8::FixedArray::Length(), v8::PrimitiveArray::Length(), v8::String::Length(), v8::debug::ScriptSource::Length(), v8::anonymous_namespace{api.cc}::MakeAccessorInfo(), v8::String::MakeExternal(), v8::Promise::MarkAsHandled(), v8::Promise::MarkAsSilent(), v8::ArrayBuffer::MaxByteLength(), v8::SharedArrayBuffer::MaxByteLength(), v8::Private::Name(), v8::debug::Script::Name(), v8::ObjectTemplate::New(), v8::Symbol::New(), v8::Private::New(), v8::StringObject::New(), v8::SymbolObject::New(), v8::Array::New(), v8::Object::New(), v8::DataView::New(), v8::Float16Array::New(), v8::Proxy::New(), v8::RegExp::New(), v8::NewFunctionTemplate(), v8::internal::DictionaryTemplateInfo::NewInstance(), v8::ObjectTemplate::NewInstance(), v8::DictionaryTemplate::NewInstance(), v8::Function::NewInstanceWithSideEffectType(), v8::NewObjectTemplate(), v8::internal::anonymous_namespace{isolate.cc}::NewRejectedPromise(), v8::FunctionTemplate::NewRemoteInstance(), v8::RegExp::NewWithBacktrackLimit(), v8::internal::Isolate::NotifyExceptionPropagationCallback(), v8::Value::NumberValue(), v8::Object::ObjectProtoToString(), v8::ObjectSetAccessor(), v8::debug::Script::OriginOptions(), v8::Date::Parse(), v8::internal::anonymous_namespace{liveedit.cc}::ParseScript(), v8::internal::SourceTextModule::PrepareInstantiate(), v8::Object::PreviewEntries(), v8::PropertyDescriptor::PropertyDescriptor(), v8::FunctionTemplate::PrototypeTemplate(), v8::HeapProfiler::QueryObjects(), v8::internal::ValueDeserializer::ReadHostObject(), v8::internal::ValueDeserializer::ReadJSArrayBuffer(), v8::FunctionTemplate::ReadOnlyPrototype(), v8::Shell::RealmGlobal(), v8::Shell::RealmNavigate(), v8::Shell::RealmOwner(), v8::Promise::Resolver::Reject(), v8::FunctionTemplate::RemovePrototype(), v8::debug::ResetBlackboxedStateCache(), v8::Promise::Resolver::Resolve(), v8::Promise::Result(), v8::Proxy::Revoke(), v8::Script::Run(), v8::internal::Isolate::RunHostCreateShadowRealmContextCallback(), v8::internal::Isolate::RunHostImportModuleDynamicallyCallback(), v8::Shell::RunMain(), v8::internal::Isolate::RunPrepareStackTraceCallback(), v8::internal::RUNTIME_FUNCTION(), v8::Value::SameValue(), v8::debug::GeneratorObject::Script(), v8::Function::ScriptId(), v8::Module::ScriptId(), v8::FunctionTemplate::SealAndPrepareForPromotionToReadOnly(), v8::ObjectTemplate::SealAndPrepareForPromotionToReadOnly(), v8::PrimitiveArray::Set(), v8::Map::Set(), v8::Object::Set(), v8::Template::Set(), v8::debug::EphemeronTable::Set(), v8::Context::SetAbortScriptExecution(), v8::FunctionTemplate::SetAcceptAnyReceiver(), v8::ObjectTemplate::SetAccessCheckCallback(), v8::ObjectTemplate::SetAccessCheckCallbackAndHandler(), v8::Object::SetAccessorProperty(), v8::Template::SetAccessorProperty(), v8::Object::SetAlignedPointerInInternalField(), v8::Object::SetAlignedPointerInInternalFields(), v8::debug::Script::SetBreakpoint(), v8::FunctionTemplate::SetCallHandler(), v8::FunctionTemplate::SetClassName(), v8::ObjectTemplate::SetCodeLike(), v8::debug::SetContextId(), v8::Isolate::SetContinuationPreservedEmbedderData(), v8::Isolate::SetContinuationPreservedEmbedderDataV2(), v8::SnapshotCreator::SetDefaultContext(), v8::ArrayBuffer::SetDetachKey(), v8::Context::SetEmbedderData(), v8::Context::SetErrorMessageForCodeGenerationFromStrings(), v8::Context::SetErrorMessageForWasmCodeGeneration(), v8::FunctionTemplate::SetExceptionContext(), v8::debug::SetFunctionBreakpoint(), v8::ObjectTemplate::SetImmutableProto(), v8::debug::Script::SetInstrumentationBreakpoint(), v8::Object::SetIntegrityLevel(), v8::FunctionTemplate::SetInterfaceName(), v8::Object::SetInternalField(), v8::ObjectTemplate::SetInternalFieldCount(), v8::Template::SetIntrinsicDataProperty(), v8::FunctionTemplate::SetLength(), v8::Context::SetMicrotaskQueue(), v8::Function::SetName(), v8::Object::SetPrivate(), v8::Context::SetPromiseHooks(), v8::anonymous_namespace{api.cc}::SetPrototypeImpl(), v8::FunctionTemplate::SetPrototypeProviderTemplate(), v8::debug::SetReturnValue(), v8::Context::SetSecurityToken(), v8::Module::SetSyntheticModuleExport(), v8::debug::AccessorPair::setter(), v8::internal::DebugScopeIterator::SetVariableValue(), v8::Map::Size(), v8::Set::Size(), v8::debug::ScriptSource::Size(), v8::Object::SlowGetAlignedPointerFromInternalField(), v8::Object::SlowGetInternalField(), v8::debug::Script::Source(), v8::debug::Script::SourceMappingURL(), v8::Module::SourceOffsetToLocation(), v8::debug::Script::SourceURL(), v8::TryCatch::StackTrace(), v8::CpuProfiler::Start(), v8::debug::Script::StartColumn(), v8::debug::Script::StartLine(), v8::Promise::State(), v8::CpuProfiler::StopProfiling(), v8::Value::StrictEquals(), v8::String::StringEquals(), v8::debug::GeneratorObject::SuspendedLocation(), v8::anonymous_namespace{api.cc}::TemplateSetAccessor(), v8::Promise::Then(), v8::Isolate::ThrowException(), v8::Value::ToArrayIndex(), v8::Value::ToBigInt(), v8::Value::ToDetailString(), v8::Value::ToInt32(), v8::Value::ToInteger(), v8::Date::ToISOString(), v8::Value::ToNumber(), v8::Value::ToNumeric(), v8::Value::ToObject(), v8::Value::ToPrimitive(), v8::Value::ToString(), v8::Value::ToUint32(), v8::Date::ToUTCString(), v8::BigInt::ToWordsArray(), v8::ValueSerializer::TransferArrayBuffer(), v8::ValueDeserializer::TransferArrayBuffer(), v8::ValueDeserializer::TransferSharedArrayBuffer(), v8::Value::TypeOf(), v8::Value::Uint32Value(), v8::BigInt::Uint64Value(), v8::anonymous_namespace{async-hooks-wrapper.cc}::UnwrapHook(), v8::TypecheckWitness::Update(), v8::Context::UseDefaultSecurityToken(), v8::String::Utf8Length(), v8::String::Utf8LengthV2(), wasm::FuncData::v8_callback(), v8::internal::EmbedderGraphImpl::V8Node(), v8::internal::ValidatePropertyCallbackInfo(), v8::External::Value(), v8::Boolean::Value(), v8::Number::Value(), v8::Integer::Value(), v8::Int32::Value(), v8::Uint32::Value(), v8::CppHeapExternal::ValueImpl(), v8::Date::ValueOf(), v8::NumberObject::ValueOf(), v8::BigIntObject::ValueOf(), v8::BooleanObject::ValueOf(), v8::StringObject::ValueOf(), v8::SymbolObject::ValueOf(), v8::String::ValueView::ValueView(), v8::String::VerifyExternalStringResource(), v8::String::VerifyExternalStringResourceBase(), v8::ScriptOrigin::VerifyHostDefinedOptions(), v8::debug::Script::WasCompiled(), v8::ArrayBuffer::WasDetached(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyDescriptorOptionsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunctionType(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyGlobalSetValueImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstanceImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyInstantiateImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyMemoryMapDescriptorMapImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleCustomSectionsImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyModuleImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyPromising(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblySuspendingImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableGrowImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTableSetImpl(), v8::BigInt::WordCount(), v8::WriteHelper(), v8::WriteHelperV2(), v8::ValueSerializer::Delegate::WriteHostObject(), v8::String::WriteUtf8(), and v8::String::WriteUtf8V2().
OpenHandle()
template<class From , class To >
static i::Handle<To> v8::Utils::OpenHandle (v8::Local< From > handle) [inline], [static]
Definition at line 294 of file api.h.
                                                             {
    return OpenHandle(*handle);
  }
References v8::internal::handle().
Referenced by v8::internal::wasm::gdb_server::WasmModuleDebug::AddBreakpoint(), v8::internal::wasm::gdb_server::GdbServer::AddWasmModule(), v8::debug::CallFunctionOn(), v8::Exception::CaptureStackTrace(), v8::ScriptCompiler::CompileFunction(), v8::debug::CompileInspectorScript(), v8::anonymous_namespace{api.cc}::CompileStreamedSource(), v8::ScriptCompiler::CompileUnboundInternal(), v8::String::Concat(), v8::ScriptCompiler::CreateCodeCache(), v8::debug::ScopeIterator::CreateForGeneratorObject(), v8::Exception::CreateMessage(), v8::Module::Evaluate(), v8::debug::EvaluateGlobal(), v8::RegExp::Exec(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::NamedDebugProxy< T, id, Provider >::FindName(), v8::Symbol::For(), v8::Symbol::ForApi(), v8::Private::ForApi(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetFirstWasmInstance(), v8::debug::GetFunctionDescription(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::IndexedDebugProxy< T, id, Provider >::GetHolder(), v8::internal::detail::AsyncWaiterQueueNode< T >::GetInternalWaitingPromise(), v8::Module::GetModuleNamespace(), v8::debug::Script::GetPossibleBreakpoints(), v8::anonymous_namespace{api.cc}::GetScriptDetails(), v8::StackFrame::GetSourcePosition(), v8::internal::detail::AsyncWaiterQueueNode< T >::GetSynchronizationPrimitive(), v8::internal::detail::AsyncWaiterQueueNode< T >::GetUnlockedPromise(), v8::Module::InstantiateModule(), v8::internal::ModifyCodeGenerationFromStrings(), v8::internal::anonymous_namespace{debug-wasm-objects.cc}::ContextProxyPrototype::NamedGetter(), v8::ObjectSetAccessor(), v8::JSON::Parse(), v8::internal::wasm::gdb_server::WasmModuleDebug::RemoveBreakpoint(), v8::internal::FutexEmulation::ResolveAsyncWaiterPromise(), v8::Object::Set(), v8::debug::EphemeronTable::Set(), v8::debug::Script::SetBreakpoint(), v8::debug::Script::SetScriptSource(), v8::internal::DebugScopeIterator::SetVariableValue(), v8::ScriptCompiler::ConsumeCodeCacheTask::SourceTextAvailable(), v8::anonymous_namespace{wasm-js.cc}::StartAsyncCompilationWithResolver(), v8::JSON::Stringify(), v8::Shell::TestVerifySourcePositions(), v8::internal::wasm::gdb_server::WasmModuleDebug::WasmModuleDebug(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl(), and v8::ValueSerializer::WriteValue().
OpenPersistent() [1/2]
template<class T >
static i::Handle<i::Object> v8::Utils::OpenPersistent (const v8::PersistentBase< T > & persistent) [inline], [static]
Definition at line 282 of file api.h.
                                             {
    return i::Handle<i::Object>(persistent.slot());
  }
References v8::api_internal::IndirectHandleBase::slot().
Referenced by v8::internal::V8HeapExplorer::MakeGlobalObjectTagMap(), OpenPersistent(), and v8::CpuProfilingOptions::raw_filter_context().
OpenPersistent() [2/2]
template<class T >
static i::DirectHandle<i::Object> v8::Utils::OpenPersistent (v8::Persistent< T > * persistent) [inline], [static]
Definition at line 288 of file api.h.
                                   {
    return OpenPersistent(*persistent);
  }
References OpenPersistent().
ReportApiFailure()
void v8::Utils::ReportApiFailure (const char * location, const char * message) [static], [private]
Definition at line 260 of file api.cc.
                                                                      {
  i::Isolate* i_isolate = i::Isolate::TryGetCurrent();
  FatalErrorCallback callback = nullptr;
  if (i_isolate != nullptr) {
    callback = i_isolate->exception_behavior();
  }
  if (callback == nullptr) {
    base::OS::PrintError("\n#\n# Fatal error in %s\n# %s\n#\n\n", location,
                         message);
    base::OS::Abort();
  } else {
    callback(location, message);
  }
  i_isolate->SignalFatalError();
}
References v8::base::OS::Abort(), and v8::internal::Isolate::SignalFatalError().
Referenced by ApiCheck().
ReportOOMFailure()
void v8::Utils::ReportOOMFailure (i::Isolate * isolate, const char * location, const OOMDetails & details) [static]
Definition at line 276 of file api.cc.
                                                        {
  if (auto oom_callback = i_isolate->oom_behavior()) {
    oom_callback(location, details);
  } else {
    // TODO(wfh): Remove this fallback once Blink is setting OOM handler. See
    // crbug.com/614440.
    FatalErrorCallback fatal_callback = i_isolate->exception_behavior();
    if (fatal_callback == nullptr) {
      base::OOMType type = details.is_heap_oom ? base::OOMType::kJavaScript
                                               : base::OOMType::kProcess;
      base::FatalOOM(type, location);
      UNREACHABLE();
    } else {
      fatal_callback(location,
                     details.is_heap_oom
                         ? "Allocation failed - JavaScript heap out of memory"
                         : "Allocation failed - process out of memory");
    }
  }
  i_isolate->SignalFatalError();
}
References v8::base::FatalOOM(), v8::OOMDetails::is_heap_oom, v8::base::kJavaScript, v8::base::kProcess, v8::internal::Isolate::SignalFatalError(), v8::internal::tracing::type, and UNREACHABLE.
ToMaybe()
template<typename T >
static MaybeLocal<T> v8::Utils::ToMaybe (Local< T > value) [inline], [static]
Definition at line 246 of file api.h.
                                                      {
    return value;
  }
References v8::internal::value.
Referenced by ToMaybeLocal().
ToMaybeLocal()
template<template< typename > typename HandleType, typename From >
requires static std::is_convertible_v<HandleType<From>, i::MaybeDirectHandle<From> > auto v8::Utils::ToMaybeLocal (HandleType< From > maybe_obj_in) -> decltype(ToMaybe(ToLocal(std::declval<i::DirectHandle<From>>()))) [inline], [static]
Definition at line 252 of file api.h.
                                                                       {
    i::MaybeDirectHandle<From> maybe_obj = maybe_obj_in;
    i::DirectHandle<From> obj;
    if (!maybe_obj.ToHandle(&obj)) return {};
    return ToMaybe(ToLocal(obj));
  }
References v8::internal::MaybeDirectHandle< T >::ToHandle(), and ToMaybe().
Referenced by v8::Function::Call(), v8::Object::CallAsConstructor(), v8::Object::CallAsFunction(), v8::debug::CallFunctionOn(), v8::Promise::Catch(), v8::EnterV8InternalScope< HandleScopeClass, do_callback >::EscapeMaybe(), v8::debug::EvaluateGlobal(), v8::Object::GetRealNamedProperty(), v8::Object::GetRealNamedPropertyInPrototypeChain(), v8::Date::New(), v8::Function::NewInstanceWithSideEffectType(), v8::Date::Parse(), v8::EnterV8InternalScope< HandleScopeClass, do_callback >::requires(), v8::Promise::Then(), v8::Value::ToInt32(), v8::Value::ToInteger(), v8::Value::ToNumber(), v8::Value::ToNumeric(), v8::Value::ToPrimitive(), and v8::Value::ToUint32().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/api/api.h
/mnt/V8SourceCode/src/api/api-inl.h
/mnt/V8SourceCode/src/api/api.cc