v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot Class Reference
#include <snapshot-table.h>
Public Member Functions
bool has_value () const
Snapshot value () const
void Set (Snapshot snapshot)
MaybeSnapshot ()=default
MaybeSnapshot (Snapshot snapshot)
Private Attributes
SnapshotData * data_ = nullptr
Detailed Description
template<class Value, class KeyData = NoKeyData>
class v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot
Definition at line 118 of file snapshot-table.h.
Constructor & Destructor Documentation
MaybeSnapshot() [1/2]
template<class Value , class KeyData = NoKeyData>
v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::MaybeSnapshot () [default]
MaybeSnapshot() [2/2]
template<class Value , class KeyData = NoKeyData>
v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::MaybeSnapshot (Snapshot snapshot) [inline], [explicit]
Definition at line 129 of file snapshot-table.h.
: data_(snapshot.data_) {}
Member Function Documentation
has_value()
template<class Value , class KeyData = NoKeyData>
bool v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::has_value () const [inline]
Definition at line 120 of file snapshot-table.h.
{ return data_ != nullptr; }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::data_.
Referenced by v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::StartNewSnapshotFor(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::value().
Set()
template<class Value , class KeyData = NoKeyData>
void v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::Set (Snapshot snapshot) [inline]
Definition at line 126 of file snapshot-table.h.
{ data_ = snapshot.data_; }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::Snapshot::data_, and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::data_.
value()
template<class Value , class KeyData = NoKeyData>
Snapshot v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::value () const [inline]
Definition at line 121 of file snapshot-table.h.
                           {
      DCHECK(has_value());
      return Snapshot{data_};
    }
References v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::data_, v8::internal::DCHECK(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::has_value().
Member Data Documentation
data_
template<class Value , class KeyData = NoKeyData>
SnapshotData* v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::data_ = nullptr [private]
Definition at line 132 of file snapshot-table.h.
Referenced by v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::has_value(), v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::Set(), and v8::internal::compiler::turboshaft::SnapshotTable< Value, KeyData >::MaybeSnapshot::value().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/turboshaft/snapshot-table.h