v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope Class Reference
Public Member Functions
SaveCallSpeculationScope (MaglevGraphBuilder *builder, compiler::FeedbackSource feedback_source=compiler::FeedbackSource())
~SaveCallSpeculationScope ()
const compiler::FeedbackSource & value ()
Static Private Member Functions
static SpeculationMode GetSpeculationMode (compiler::JSHeapBroker *broker, compiler::FeedbackSource feedback_source)
Private Attributes
MaglevGraphBuilder * builder_
compiler::FeedbackSource saved_
SpeculationMode saved_mode_
Detailed Description
Definition at line 325 of file maglev-graph-builder.cc.
Constructor & Destructor Documentation
SaveCallSpeculationScope()
v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::SaveCallSpeculationScope (MaglevGraphBuilder * builder, compiler::FeedbackSource feedback_source = compiler::FeedbackSource()) [inline], [explicit]
Definition at line 327 of file maglev-graph-builder.cc.
      : builder_(builder) {
    saved_ = builder_->current_speculation_feedback_;
    // Only set the current speculation feedback if speculation is allowed.
    SpeculationMode mode =
        GetSpeculationMode(builder_->broker(), feedback_source);
    if (mode != SpeculationMode::kDisallowSpeculation) {
      builder->current_speculation_feedback_ = feedback_source;
      builder_->current_speculation_mode_ = mode;
    } else {
      builder->current_speculation_feedback_ = compiler::FeedbackSource();
      builder_->current_speculation_mode_ =
          SpeculationMode::kDisallowSpeculation;
    }
  }
References v8::internal::maglev::MaglevGraphBuilder::current_speculation_feedback_, v8::internal::kDisallowSpeculation, and mode().
 SaveCallSpeculationScope()
v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::~SaveCallSpeculationScope () [inline]
Definition at line 344 of file maglev-graph-builder.cc.
                              {
    builder_->current_speculation_feedback_ = saved_;
    builder_->current_speculation_mode_ = saved_mode_;
  }
Member Function Documentation
GetSpeculationMode()
static SpeculationMode v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::GetSpeculationMode (compiler::JSHeapBroker * broker, compiler::FeedbackSource feedback_source) [inline], [static], [private]
Definition at line 356 of file maglev-graph-builder.cc.
                                              {
    if (!feedback_source.IsValid())
      return SpeculationMode::kDisallowSpeculation;
    compiler::ProcessedFeedback const& processed_feedback =
        broker->GetFeedbackForCall(feedback_source);
    if (processed_feedback.IsInsufficient())
      return SpeculationMode::kDisallowSpeculation;
    return processed_feedback.AsCall().speculation_mode();
  }
References v8::internal::compiler::ProcessedFeedback::AsCall(), broker(), v8::internal::compiler::ProcessedFeedback::IsInsufficient(), v8::internal::compiler::FeedbackSource::IsValid(), v8::internal::kDisallowSpeculation, and v8::internal::compiler::CallFeedback::speculation_mode().
value()
const compiler::FeedbackSource& v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::value () [inline]
Definition at line 349 of file maglev-graph-builder.cc.
{ return saved_; }
Member Data Documentation
builder_
MaglevGraphBuilder* v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::builder_ [private]
Definition at line 352 of file maglev-graph-builder.cc.
saved_
compiler::FeedbackSource v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::saved_ [private]
Definition at line 353 of file maglev-graph-builder.cc.
saved_mode_
SpeculationMode v8::internal::maglev::MaglevGraphBuilder::SaveCallSpeculationScope::saved_mode_ [private]
Definition at line 354 of file maglev-graph-builder.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/maglev/maglev-graph-builder.cc