v8::internal::PlatformEmbeddedFileWriterAIX Class Reference
#include <platform-embedded-file-writer-aix.h>
Public Member Functions
PlatformEmbeddedFileWriterAIX (EmbeddedTargetArch target_arch, EmbeddedTargetOs target_os)
void SectionText () override
void SectionRoData () override
void AlignToCodeAlignment () override
void AlignToDataAlignment () override
void DeclareUint32 (const char *name, uint32_t value) override
void DeclareSymbolGlobal (const char *name) override
void DeclareLabel (const char *name) override
void SourceInfo (int fileid, const char *filename, int line) override
void DeclareFunctionBegin (const char *name, uint32_t size) override
void DeclareFunctionEnd (const char *name) override
void Comment (const char *string) override
void FilePrologue () override
void DeclareExternalFilename (int fileid, const char *filename) override
void FileEpilogue () override
int IndentedDataDirective (DataDirective directive) override
DataDirective ByteChunkDataDirective () const override
Private Attributes
const EmbeddedTargetArch target_arch_
const EmbeddedTargetOs target_os_
Additional Inherited Members
Detailed Description
Definition at line 14 of file platform-embedded-file-writer-aix.h.
Constructor & Destructor Documentation
PlatformEmbeddedFileWriterAIX()
v8::internal::PlatformEmbeddedFileWriterAIX::PlatformEmbeddedFileWriterAIX (EmbeddedTargetArch target_arch, EmbeddedTargetOs target_os) [inline]
Definition at line 16 of file platform-embedded-file-writer-aix.h.
      : target_arch_(target_arch), target_os_(target_os) {
    USE(target_arch_);
    USE(target_os_);
    DCHECK_EQ(target_os_, EmbeddedTargetOs::kAIX);
  }
References DCHECK_EQ, v8::internal::kAIX, target_arch_, target_os_, and USE.
Member Function Documentation
AlignToCodeAlignment()
void v8::internal::PlatformEmbeddedFileWriterAIX::AlignToCodeAlignment () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 55 of file platform-embedded-file-writer-aix.cc.
                                                         {
#if V8_TARGET_ARCH_X64
  // On x64 use 64-bytes code alignment to allow 64-bytes loop header alignment.
  static_assert((1 << 6) >= kCodeAlignment);
  fprintf(fp_, ".align 6\n");
#elif V8_TARGET_ARCH_PPC64
  // 64 byte alignment is needed on ppc64 to make sure p10 prefixed instructions
  // don't cross 64-byte boundaries.
  static_assert((1 << 6) >= kCodeAlignment);
  fprintf(fp_, ".align 6\n");
#else
  static_assert((1 << 5) >= kCodeAlignment);
  fprintf(fp_, ".align 5\n");
#endif
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::kCodeAlignment.
AlignToDataAlignment()
void v8::internal::PlatformEmbeddedFileWriterAIX::AlignToDataAlignment () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 71 of file platform-embedded-file-writer-aix.cc.
                                                         {
  static_assert((1 << 3) >= InstructionStream::kMetadataAlignment);
  fprintf(fp_, ".align 3\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::InstructionStream::kMetadataAlignment.
ByteChunkDataDirective()
DataDirective v8::internal::PlatformEmbeddedFileWriterAIX::ByteChunkDataDirective () const [override], [virtual]
Reimplemented from v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 124 of file platform-embedded-file-writer-aix.cc.
                                                                          {
  // PPC uses a fixed 4 byte instruction set, using .long
  // to prevent any unnecessary padding.
  return kLong;
}
References v8::internal::kLong.
Comment()
void v8::internal::PlatformEmbeddedFileWriterAIX::Comment (const char * string) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 76 of file platform-embedded-file-writer-aix.cc.
                                                              {
  fprintf(fp_, "// %s\n", string);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
DeclareExternalFilename()
void v8::internal::PlatformEmbeddedFileWriterAIX::DeclareExternalFilename (int fileid, const char * filename) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 110 of file platform-embedded-file-writer-aix.cc.
                                      {
  // File name cannot be declared with an identifier on AIX.
  // We use the SourceInfo method to emit debug info in
  //.xline <line-number> <file-name> format.
}
DeclareFunctionBegin()
void v8::internal::PlatformEmbeddedFileWriterAIX::DeclareFunctionBegin (const char * name, uint32_t size) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 93 of file platform-embedded-file-writer-aix.cc.
                                                                        {
  Newline();
  if (ENABLE_CONTROL_FLOW_INTEGRITY_BOOL) {
    DeclareSymbolGlobal(name);
  }
  fprintf(fp_, ".csect %s[DS]\n", name); // function descriptor
  fprintf(fp_, "%s:\n", name);
  fprintf(fp_, ".llong .%s, 0, 0\n", name);
  SectionText();
  fprintf(fp_, ".%s:\n", name);
}
References DeclareSymbolGlobal(), ENABLE_CONTROL_FLOW_INTEGRITY_BOOL, v8::internal::PlatformEmbeddedFileWriterBase::fp_, v8::internal::name, v8::internal::PlatformEmbeddedFileWriterBase::Newline(), and SectionText().
DeclareFunctionEnd()
void v8::internal::PlatformEmbeddedFileWriterAIX::DeclareFunctionEnd (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 106 of file platform-embedded-file-writer-aix.cc.
{}
DeclareLabel()
void v8::internal::PlatformEmbeddedFileWriterAIX::DeclareLabel (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 80 of file platform-embedded-file-writer-aix.cc.
                                                                 {
  // .global is required on AIX, if the label is used/referenced in another file
  // later to be linked.
  fprintf(fp_, ".globl %s\n", name);
  fprintf(fp_, "%s:\n", name);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::name.
DeclareSymbolGlobal()
void v8::internal::PlatformEmbeddedFileWriterAIX::DeclareSymbolGlobal (const char * name) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 49 of file platform-embedded-file-writer-aix.cc.
                                                                        {
  // These symbols are not visible outside of the final binary, this allows for
  // reduced binary size, and less work for the dynamic linker.
  fprintf(fp_, ".globl %s, hidden\n", name);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_, and v8::internal::name.
Referenced by DeclareFunctionBegin(), and DeclareUint32().
DeclareUint32()
void v8::internal::PlatformEmbeddedFileWriterAIX::DeclareUint32 (const char * name, uint32_t value) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 39 of file platform-embedded-file-writer-aix.cc.
                                                                  {
  DeclareSymbolGlobal(name);
  fprintf(fp_, ".align 2\n");
  fprintf(fp_, "%s:\n", name);
  IndentedDataDirective(kLong);
  fprintf(fp_, "%d\n", value);
  Newline();
}
References DeclareSymbolGlobal(), v8::internal::PlatformEmbeddedFileWriterBase::fp_, IndentedDataDirective(), v8::internal::kLong, v8::internal::name, v8::internal::PlatformEmbeddedFileWriterBase::Newline(), and v8::internal::value.
FileEpilogue()
void v8::internal::PlatformEmbeddedFileWriterAIX::FileEpilogue () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 117 of file platform-embedded-file-writer-aix.cc.
{}
FilePrologue()
void v8::internal::PlatformEmbeddedFileWriterAIX::FilePrologue () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 108 of file platform-embedded-file-writer-aix.cc.
{}
IndentedDataDirective()
int v8::internal::PlatformEmbeddedFileWriterAIX::IndentedDataDirective (DataDirective directive) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 119 of file platform-embedded-file-writer-aix.cc.
                             {
  return fprintf(fp_, " %s ", DirectiveAsString(directive));
}
References v8::internal::anonymous_namespace{platform-embedded-file-writer-aix.cc}::DirectiveAsString(), and v8::internal::PlatformEmbeddedFileWriterBase::fp_.
Referenced by DeclareUint32().
SectionRoData()
void v8::internal::PlatformEmbeddedFileWriterAIX::SectionRoData () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 35 of file platform-embedded-file-writer-aix.cc.
                                                  {
  fprintf(fp_, ".csect[RO]\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
SectionText()
void v8::internal::PlatformEmbeddedFileWriterAIX::SectionText () [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 31 of file platform-embedded-file-writer-aix.cc.
                                                {
  fprintf(fp_, ".csect [GL], 6\n");
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
Referenced by DeclareFunctionBegin().
SourceInfo()
void v8::internal::PlatformEmbeddedFileWriterAIX::SourceInfo (int fileid, const char * filename, int line) [override], [virtual]
Implements v8::internal::PlatformEmbeddedFileWriterBase.
Definition at line 87 of file platform-embedded-file-writer-aix.cc.
                                                         {
  fprintf(fp_, ".xline %d, \"%s\"\n", line, filename);
}
References v8::internal::PlatformEmbeddedFileWriterBase::fp_.
Member Data Documentation
target_arch_
const EmbeddedTargetArch v8::internal::PlatformEmbeddedFileWriterAIX::target_arch_ [private]
Definition at line 50 of file platform-embedded-file-writer-aix.h.
Referenced by PlatformEmbeddedFileWriterAIX().
target_os_
const EmbeddedTargetOs v8::internal::PlatformEmbeddedFileWriterAIX::target_os_ [private]
Definition at line 51 of file platform-embedded-file-writer-aix.h.
Referenced by PlatformEmbeddedFileWriterAIX().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/snapshot/embedded/platform-embedded-file-writer-aix.h
/mnt/V8SourceCode/src/snapshot/embedded/platform-embedded-file-writer-aix.cc