v8::internal::ClassLiteralProperty Class Reference
#include <ast.h>
Public Types
enum Kind : uint8_t {
METHOD
, GETTER
, SETTER
, FIELD
,
AUTO_ACCESSOR
 }
Public Member Functions
Kind kind () const
bool is_static () const
bool is_private () const
bool is_auto_accessor () const
void set_computed_name_proxy (VariableProxy *proxy)
Variable * computed_name_var () const
void SetPrivateNameProxy (VariableProxy *proxy)
Variable * private_name_var () const
AutoAccessorInfo * auto_accessor_info ()
Private Member Functions
ClassLiteralProperty (Expression *key, Expression *value, Kind kind, bool is_static, bool is_computed_name, bool is_private)
ClassLiteralProperty (Expression *key, Expression *value, AutoAccessorInfo *auto_accessor_info, bool is_static, bool is_computed_name, bool is_private)
Private Attributes
friend Zone
Kind kind_
bool is_static_
bool is_private_
xx xx xx xx xx xx xx xx xx
union {
 VariableProxy * private_or_computed_name_proxy_
 AutoAccessorInfo * auto_accessor_info_
};
Friends
class AstNodeFactory
Additional Inherited Members
Detailed Description
Definition at line 2543 of file ast.h.
Member Enumeration Documentation
Kind
enum v8::internal::ClassLiteralProperty::Kind : uint8_t
Enumerator
METHOD
GETTER
SETTER
FIELD
AUTO_ACCESSOR
Definition at line 2545 of file ast.h.
: uint8_t { METHOD, GETTER, SETTER, FIELD, AUTO_ACCESSOR };
Constructor & Destructor Documentation
ClassLiteralProperty() [1/2]
v8::internal::ClassLiteralProperty::ClassLiteralProperty (Expression * key, Expression * value, Kind kind, bool is_static, bool is_computed_name, bool is_private) [private]
Definition at line 305 of file ast.cc.
    : LiteralProperty(key, value, is_computed_name),
      kind_(kind),
      is_static_(is_static),
      is_private_(is_private),
      private_or_computed_name_proxy_(nullptr) {}
ClassLiteralProperty() [2/2]
v8::internal::ClassLiteralProperty::ClassLiteralProperty (Expression * key, Expression * value, AutoAccessorInfo * auto_accessor_info, bool is_static, bool is_computed_name, bool is_private) [private]
Definition at line 315 of file ast.cc.
    : LiteralProperty(key, value, is_computed_name),
      kind_(Kind::AUTO_ACCESSOR),
      is_static_(is_static),
      is_private_(is_private),
      auto_accessor_info_(info) {
  DCHECK_NOT_NULL(info);
}
References DCHECK_NOT_NULL.
Member Function Documentation
auto_accessor_info()
AutoAccessorInfo* v8::internal::ClassLiteralProperty::auto_accessor_info () [inline]
Definition at line 2581 of file ast.h.
                                         {
    DCHECK(is_auto_accessor());
    DCHECK_NOT_NULL(auto_accessor_info_);
    return auto_accessor_info_;
  }
References auto_accessor_info_, v8::internal::DCHECK(), DCHECK_NOT_NULL, and is_auto_accessor().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), and SetPrivateNameProxy().
computed_name_var()
Variable* v8::internal::ClassLiteralProperty::computed_name_var () const [inline]
Definition at line 2561 of file ast.h.
                                      {
    DCHECK_EQ(FIELD, kind());
    DCHECK(!is_private());
    return private_or_computed_name_proxy_->var();
  }
References v8::internal::DCHECK(), DCHECK_EQ, FIELD, is_private(), kind(), private_or_computed_name_proxy_, and v8::internal::VariableProxy::var().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::interpreter::BytecodeGenerator::BuildClassProperty().
is_auto_accessor()
bool v8::internal::ClassLiteralProperty::is_auto_accessor () const [inline]
Definition at line 2553 of file ast.h.
{ return kind() == AUTO_ACCESSOR; }
References AUTO_ACCESSOR, and kind().
Referenced by auto_accessor_info(), v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), private_name_var(), and SetPrivateNameProxy().
is_private()
bool v8::internal::ClassLiteralProperty::is_private () const [inline]
Definition at line 2551 of file ast.h.
{ return is_private_; }
References is_private_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), computed_name_var(), v8::internal::ClassBoilerplate::New(), private_name_var(), set_computed_name_proxy(), and SetPrivateNameProxy().
is_static()
bool v8::internal::ClassLiteralProperty::is_static () const [inline]
Definition at line 2549 of file ast.h.
{ return is_static_; }
References is_static_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::ClassBoilerplate::New().
kind()
Kind v8::internal::ClassLiteralProperty::kind () const [inline]
Definition at line 2547 of file ast.h.
{ return kind_; }
References kind_.
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), v8::internal::interpreter::BytecodeGenerator::BuildClassProperty(), computed_name_var(), is_auto_accessor(), v8::internal::ClassBoilerplate::New(), set_computed_name_proxy(), and v8::internal::AstFunctionLiteralIdReindexer::VisitClassLiteral().
private_name_var()
Variable* v8::internal::ClassLiteralProperty::private_name_var () const [inline]
Definition at line 2575 of file ast.h.
                                     {
    DCHECK(is_private());
    DCHECK(!is_auto_accessor());
    return private_or_computed_name_proxy_->var();
  }
References v8::internal::DCHECK(), is_auto_accessor(), is_private(), private_or_computed_name_proxy_, and v8::internal::VariableProxy::var().
Referenced by v8::internal::interpreter::BytecodeGenerator::BuildClassLiteral(), and v8::internal::interpreter::BytecodeGenerator::BuildClassProperty().
set_computed_name_proxy()
void v8::internal::ClassLiteralProperty::set_computed_name_proxy (VariableProxy * proxy) [inline]
Definition at line 2555 of file ast.h.
                                                     {
    DCHECK_EQ(FIELD, kind());
    DCHECK(!is_private());
    private_or_computed_name_proxy_ = proxy;
  }
References v8::internal::DCHECK(), DCHECK_EQ, FIELD, is_private(), kind(), and private_or_computed_name_proxy_.
SetPrivateNameProxy()
void v8::internal::ClassLiteralProperty::SetPrivateNameProxy (VariableProxy * proxy) [inline]
Definition at line 2567 of file ast.h.
                                                 {
    DCHECK(is_private());
    if (is_auto_accessor()) {
      auto_accessor_info()->set_property_private_name_proxy(proxy);
      return;
    }
    private_or_computed_name_proxy_ = proxy;
  }
References auto_accessor_info(), v8::internal::DCHECK(), is_auto_accessor(), is_private(), private_or_computed_name_proxy_, and v8::internal::AutoAccessorInfo::set_property_private_name_proxy().
Friends And Related Function Documentation
AstNodeFactory
friend class AstNodeFactory [friend]
Definition at line 2588 of file ast.h.
Member Data Documentation
union { ... } [private]
auto_accessor_info_
AutoAccessorInfo* v8::internal::ClassLiteralProperty::auto_accessor_info_
Definition at line 2602 of file ast.h.
Referenced by auto_accessor_info().
is_private_
bool v8::internal::ClassLiteralProperty::is_private_ [private]
Definition at line 2599 of file ast.h.
Referenced by is_private().
is_static_
bool v8::internal::ClassLiteralProperty::is_static_ [private]
Definition at line 2598 of file ast.h.
Referenced by is_static().
kind_
Kind v8::internal::ClassLiteralProperty::kind_ [private]
Definition at line 2597 of file ast.h.
Referenced by kind().
private_or_computed_name_proxy_
VariableProxy* v8::internal::ClassLiteralProperty::private_or_computed_name_proxy_
Definition at line 2601 of file ast.h.
Referenced by computed_name_var(), private_name_var(), set_computed_name_proxy(), and SetPrivateNameProxy().
Zone
friend v8::internal::ClassLiteralProperty::Zone [private]
Definition at line 2589 of file ast.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/ast/ast.h
/mnt/V8SourceCode/src/ast/ast.cc