v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency Class Reference
Public Member Functions
OwnConstantDictionaryPropertyDependency (JSHeapBroker *broker, JSObjectRef holder, InternalIndex index, ObjectRef value)
bool IsValid (JSHeapBroker *broker) const override
void Install (JSHeapBroker *broker, PendingDependencies *deps) const override
Private Member Functions
size_t Hash () const override
bool Equals (const CompilationDependency *that) const override
Private Attributes
JSObjectRef const holder_
MapRef const map_
InternalIndex const index_
ObjectRef const value_
Additional Inherited Members
Detailed Description
Definition at line 566 of file compilation-dependencies.cc.
Constructor & Destructor Documentation
OwnConstantDictionaryPropertyDependency()
v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency::OwnConstantDictionaryPropertyDependency (JSHeapBroker * broker, JSObjectRef holder, InternalIndex index, ObjectRef value) [inline]
Definition at line 569 of file compilation-dependencies.cc.
      : CompilationDependency(kOwnConstantDictionaryProperty),
        holder_(holder),
        map_(holder.map(broker)),
        index_(index),
        value_(value) {
    // We depend on map() being cached.
    static_assert(ref_traits<JSObject>::ref_serialization_kind !=
                  RefSerializationKind::kNeverSerialized);
  }
References v8::internal::compiler::kNeverSerialized.
Member Function Documentation
Equals()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency::Equals (const CompilationDependency * that) const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 620 of file compilation-dependencies.cc.
                                                                {
    const OwnConstantDictionaryPropertyDependency* const zat =
        that->AsOwnConstantDictionaryProperty();
    return holder_.equals(zat->holder_) && map_.equals(zat->map_) &&
           index_ == zat->index_ && value_.equals(zat->value_);
  }
References holder_, index_, map_, and value_.
Hash()
size_t v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency::Hash () const [inline], [override], [private], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 614 of file compilation-dependencies.cc.
                               {
    ObjectRef::Hash h;
    return base::hash_combine(h(holder_), h(map_), index_.raw_value(),
                              h(value_));
  }
References h(), v8::internal::Hash(), and v8::base::hash_combine().
Install()
void v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency::Install (JSHeapBroker * broker, PendingDependencies * deps) const [inline], [override]
Definition at line 610 of file compilation-dependencies.cc.
                                                                               {
  }
IsValid()
bool v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency::IsValid (JSHeapBroker * broker) const [inline], [override], [virtual]
Implements v8::internal::compiler::CompilationDependency.
Definition at line 582 of file compilation-dependencies.cc.
                                                    {
    if (holder_.object()->map() != *map_.object()) {
      TRACE_BROKER_MISSING(broker,
                           "Map change detected in " << holder_.object());
      return false;
    }
    std::optional<Tagged<Object>> maybe_value = JSObject::DictionaryPropertyAt(
        holder_.object(), index_, broker->isolate()->heap());
    if (!maybe_value) {
      TRACE_BROKER_MISSING(
          broker, holder_.object()
                      << "has a value that might not safe to read at index "
                      << index_.as_int());
      return false;
    }
    if (*maybe_value != *value_.object()) {
      TRACE_BROKER_MISSING(broker, "Constant property value changed in "
                                       << holder_.object()
                                       << " at InternalIndex "
                                       << index_.as_int());
      return false;
    }
    return true;
  }
References broker(), v8::internal::JSObject::DictionaryPropertyAt(), and TRACE_BROKER_MISSING.
Member Data Documentation
holder_
JSObjectRef const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency::holder_ [private]
Definition at line 627 of file compilation-dependencies.cc.
Referenced by Equals().
index_
InternalIndex const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency::index_ [private]
Definition at line 629 of file compilation-dependencies.cc.
Referenced by Equals().
map_
MapRef const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency::map_ [private]
Definition at line 628 of file compilation-dependencies.cc.
Referenced by Equals().
value_
ObjectRef const v8::internal::compiler::anonymous_namespace{compilation-dependencies.cc}::OwnConstantDictionaryPropertyDependency::value_ [private]
Definition at line 630 of file compilation-dependencies.cc.
Referenced by Equals().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/compilation-dependencies.cc