v8::internal::interpreter::BytecodeArrayIterator Class Reference
#include <bytecode-array-iterator.h>
Public Member Functions
BytecodeArrayIterator (Handle< BytecodeArray > bytecode_array, int initial_offset=0)
BytecodeArrayIterator (Handle< BytecodeArray > bytecode_array, int initial_offset, DisallowGarbageCollection &no_gc)
~BytecodeArrayIterator ()
BytecodeArrayIterator (const BytecodeArrayIterator &)=delete
BytecodeArrayIterator & operator= (const BytecodeArrayIterator &)=delete
void Advance ()
void AdvanceTo (int offset)
void SetOffset (int offset)
void Reset ()
bool CurrentBytecodeIsValidOSREntry () const
void ApplyDebugBreak ()
Bytecode current_bytecode () const
int current_bytecode_size () const
int current_bytecode_size_without_prefix () const
int current_offset () const
uint8_t * current_address () const
int next_offset () const
Bytecode next_bytecode () const
OperandScale current_operand_scale () const
DirectHandle< BytecodeArray > bytecode_array () const
uint32_t GetFlag8Operand (int operand_index) const
uint32_t GetFlag16Operand (int operand_index) const
uint32_t GetUnsignedImmediateOperand (int operand_index) const
int32_t GetImmediateOperand (int operand_index) const
uint32_t GetIndexOperand (int operand_index) const
FeedbackSlot GetSlotOperand (int operand_index) const
Register GetParameter (int parameter_index) const
uint32_t GetRegisterCountOperand (int operand_index) const
Register GetRegisterOperand (int operand_index) const
Register GetStarTargetRegister () const
std::pair< Register, Register > GetRegisterPairOperand (int operand_index) const
RegisterList GetRegisterListOperand (int operand_index) const
int GetRegisterOperandRange (int operand_index) const
Runtime::FunctionId GetRuntimeIdOperand (int operand_index) const
Runtime::FunctionId GetIntrinsicIdOperand (int operand_index) const
uint32_t GetNativeContextIndexOperand (int operand_index) const
template<typename IsolateT >
Handle< Object > GetConstantAtIndex (int offset, IsolateT *isolate) const
bool IsConstantAtIndexSmi (int offset) const
Tagged< Smi > GetConstantAtIndexAsSmi (int offset) const
template<typename IsolateT >
Handle< Object > GetConstantForIndexOperand (int operand_index, IsolateT *isolate) const
int GetRelativeJumpTargetOffset () const
int GetJumpTargetOffset () const
JumpTableTargetOffsets GetJumpTableTargetOffsets () const
int GetAbsoluteOffset (int relative_offset) const
std::ostream & PrintTo (std::ostream &os) const
void UpdatePointers ()
bool done () const
bool operator== (const BytecodeArrayIterator &other) const
bool operator!= (const BytecodeArrayIterator &other) const
Static Public Member Functions
static bool IsValidOffset (Handle< BytecodeArray > bytecode_array, int offset)
static bool IsValidOSREntryOffset (Handle< BytecodeArray > bytecode_array, int offset)
static void UpdatePointersCallback (void *iterator)
Protected Member Functions
void SetOffsetUnchecked (int offset)
Private Member Functions
uint32_t GetUnsignedOperand (int operand_index, OperandType operand_type) const
int32_t GetSignedOperand (int operand_index, OperandType operand_type) const
void UpdateOperandScale ()
Private Attributes
Handle< BytecodeArray > bytecode_array_
uint8_t * start_
uint8_t * end_
uint8_t * cursor_
OperandScale operand_scale_
int prefix_size_
LocalHeap *const local_heap_
Detailed Description
Definition at line 70 of file bytecode-array-iterator.h.
Constructor & Destructor Documentation
BytecodeArrayIterator() [1/3]
v8::internal::interpreter::BytecodeArrayIterator::BytecodeArrayIterator (Handle< BytecodeArray > bytecode_array, int initial_offset = 0) [explicit]
Definition at line 16 of file bytecode-array-iterator.cc.
    : bytecode_array_(bytecode_array),
      start_(reinterpret_cast<uint8_t*>(
          bytecode_array_->GetFirstBytecodeAddress())),
      end_(start_ + bytecode_array_->length()),
      cursor_(start_),
      operand_scale_(OperandScale::kSingle),
      prefix_size_(0),
      local_heap_(LocalHeap::Current()
                      ? LocalHeap::Current()
                      : Isolate::Current()->main_thread_local_heap()) {
  local_heap_->AddGCEpilogueCallback(UpdatePointersCallback, this);
  UpdateOperandScale();
  if (initial_offset != 0) {
    AdvanceTo(initial_offset);
  }
}
References v8::internal::LocalHeap::AddGCEpilogueCallback(), AdvanceTo(), local_heap_, UpdateOperandScale(), and UpdatePointersCallback().
BytecodeArrayIterator() [2/3]
v8::internal::interpreter::BytecodeArrayIterator::BytecodeArrayIterator (Handle< BytecodeArray > bytecode_array, int initial_offset, DisallowGarbageCollection & no_gc)
Definition at line 35 of file bytecode-array-iterator.cc.
    : bytecode_array_(bytecode_array),
      start_(reinterpret_cast<uint8_t*>(
          bytecode_array_->GetFirstBytecodeAddress())),
      end_(start_ + bytecode_array_->length()),
      cursor_(start_),
      operand_scale_(OperandScale::kSingle),
      prefix_size_(0),
      local_heap_(nullptr) {
  // Don't add a GC callback, since we're in a no_gc scope.
  UpdateOperandScale();
  if (initial_offset != 0) {
    AdvanceTo(initial_offset);
  }
}
References AdvanceTo(), and UpdateOperandScale().
 BytecodeArrayIterator()
v8::internal::interpreter::BytecodeArrayIterator::~BytecodeArrayIterator ()
Definition at line 53 of file bytecode-array-iterator.cc.
                                              {
  if (local_heap_) {
    local_heap_->RemoveGCEpilogueCallback(UpdatePointersCallback, this);
  }
}
References local_heap_, v8::internal::LocalHeap::RemoveGCEpilogueCallback(), and UpdatePointersCallback().
BytecodeArrayIterator() [3/3]
v8::internal::interpreter::BytecodeArrayIterator::BytecodeArrayIterator (const BytecodeArrayIterator &) [delete]
Member Function Documentation
Advance()
void v8::internal::interpreter::BytecodeArrayIterator::Advance () [inline]
Definition at line 81 of file bytecode-array-iterator.h.
                        {
    cursor_ += current_bytecode_size_without_prefix();
    UpdateOperandScale();
  }
Referenced by AdvanceTo(), v8::internal::maglev::MaglevGraphBuilder::BuildBody(), v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts(), v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), v8::internal::anonymous_namespace{runtime-compiler.cc}::DeoptAllOsrLoopsContainingDeoptExit(), v8::internal::Deoptimizer::DeoptExitIsInsideOsrLoop(), v8::internal::BytecodeArray::Disassemble(), v8::internal::baseline::BaselineCompiler::GenerateCode(), v8::internal::interpreter::BytecodeArrayRandomIterator::Initialize(), v8::internal::maglev::MaglevGraphBuilder::KillPeeledLoopTargets(), v8::internal::anonymous_namespace{runtime-test.cc}::OffsetOfNextJumpLoop(), v8::internal::BytecodeArray::PrintJson(), v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::PrintLivenessTo(), and v8::internal::FeedbackVector::RecomputeOptimizedOsrCodeFlags().
AdvanceTo()
void v8::internal::interpreter::BytecodeArrayIterator::AdvanceTo (int offset)
Definition at line 59 of file bytecode-array-iterator.cc.
                                                {
  DCHECK_GE(offset, current_offset());
  while (current_offset() != offset && cursor_ < end_) {
    Advance();
  }
  // Make sure we're always at a valid offset.
  CHECK_EQ(current_offset(), offset);
}
References Advance(), CHECK_EQ, current_offset(), cursor_, DCHECK_GE, and end_.
Referenced by BytecodeArrayIterator(), v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts(), v8::internal::maglev::MaglevGraphBuilder::MaglevGraphBuilder(), SetOffset(), and v8::internal::compiler::BytecodeGraphBuilder::VisitBytecodes().
ApplyDebugBreak()
void v8::internal::interpreter::BytecodeArrayIterator::ApplyDebugBreak ()
Definition at line 111 of file bytecode-array-iterator.cc.
                                            {
  // Get the raw bytecode from the bytecode array. This may give us a
  // scaling prefix, which we can patch with the matching debug-break
  // variant.
  uint8_t* cursor = cursor_ - prefix_size_;
  interpreter::Bytecode bytecode = interpreter::Bytecodes::FromByte(*cursor);
  if (interpreter::Bytecodes::IsDebugBreak(bytecode)) return;
  interpreter::Bytecode debugbreak =
      interpreter::Bytecodes::GetDebugBreak(bytecode);
  *cursor = interpreter::Bytecodes::ToByte(debugbreak);
}
References cursor_, v8::internal::interpreter::Bytecodes::FromByte(), v8::internal::interpreter::Bytecodes::GetDebugBreak(), v8::internal::interpreter::Bytecodes::IsDebugBreak(), prefix_size_, and v8::internal::interpreter::Bytecodes::ToByte().
Referenced by v8::internal::BreakIterator::SetDebugBreak().
bytecode_array()
DirectHandle<BytecodeArray> v8::internal::interpreter::BytecodeArrayIterator::bytecode_array () const [inline]
Definition at line 128 of file bytecode-array-iterator.h.
{ return bytecode_array_; }
Referenced by v8::internal::interpreter::BytecodeArrayRandomIterator::BytecodeArrayRandomIterator(), GetConstantAtIndex(), GetConstantAtIndexAsSmi(), IsConstantAtIndexSmi(), IsValidOffset(), and IsValidOSREntryOffset().
current_address()
uint8_t* v8::internal::interpreter::BytecodeArrayIterator::current_address () const [inline]
Definition at line 116 of file bytecode-array-iterator.h.
{ return cursor_ - prefix_size_; }
Referenced by v8::internal::maglev::MaglevGraphBuilder::MarkBytecodeDead(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
current_bytecode()
Bytecode v8::internal::interpreter::BytecodeArrayIterator::current_bytecode () const [inline]
Definition at line 100 of file bytecode-array-iterator.h.
                                           {
    DCHECK(!done());
    uint8_t current_byte = *cursor_;
    Bytecode current_bytecode = Bytecodes::FromByte(current_byte);
    DCHECK(!Bytecodes::IsPrefixScalingBytecode(current_bytecode));
    return current_bytecode;
  }
References v8::internal::DCHECK(), v8::internal::interpreter::Bytecodes::FromByte(), and v8::internal::interpreter::Bytecodes::IsPrefixScalingBytecode().
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), v8::internal::maglev::MaglevGraphBuilder::BuildBody(), v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts(), v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), CurrentBytecodeIsValidOSREntry(), v8::internal::anonymous_namespace{runtime-compiler.cc}::DeoptAllOsrLoopsContainingDeoptExit(), v8::internal::Deoptimizer::DeoptExitIsInsideOsrLoop(), v8::internal::BytecodeArray::Disassemble(), v8::internal::Code::GetBaselinePCForNextExecutedBytecode(), v8::internal::BreakIterator::GetBreakLocation(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForEagerCall(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), GetFlag16Operand(), GetFlag8Operand(), GetImmediateOperand(), GetIndexOperand(), GetIntrinsicIdOperand(), GetJumpTableTargetOffsets(), GetNativeContextIndexOperand(), GetRegisterCountOperand(), GetRegisterOperand(), GetRegisterOperandRange(), GetRelativeJumpTargetOffset(), v8::internal::maglev::MaglevGraphBuilder::GetResultLocationAndSize(), GetRuntimeIdOperand(), GetSignedOperand(), GetStarTargetRegister(), GetUnsignedImmediateOperand(), GetUnsignedOperand(), v8::internal::maglev::MaglevGraphBuilder::KillPeeledLoopTargets(), v8::internal::maglev::MaglevGraphBuilder::MarkBytecodeDead(), v8::internal::anonymous_namespace{runtime-test.cc}::OffsetOfNextJumpLoop(), v8::internal::Debug::PerformSideEffectCheckAtBytecode(), v8::internal::BytecodeArray::PrintJson(), v8::internal::FeedbackVector::RecomputeOptimizedOsrCodeFlags(), v8::internal::anonymous_namespace{isolate.cc}::TouchesRegister(), v8::internal::baseline::BaselineCompiler::VisitSingleBytecode(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
current_bytecode_size()
int v8::internal::interpreter::BytecodeArrayIterator::current_bytecode_size () const [inline]
Definition at line 107 of file bytecode-array-iterator.h.
                                    {
    return prefix_size_ + current_bytecode_size_without_prefix();
  }
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze().
current_bytecode_size_without_prefix()
int v8::internal::interpreter::BytecodeArrayIterator::current_bytecode_size_without_prefix () const [inline]
Definition at line 110 of file bytecode-array-iterator.h.
                                                   {
    return Bytecodes::Size(current_bytecode(), current_operand_scale());
  }
References v8::internal::interpreter::Bytecodes::Size().
current_offset()
int v8::internal::interpreter::BytecodeArrayIterator::current_offset () const [inline]
Definition at line 113 of file bytecode-array-iterator.h.
                             {
    return static_cast<int>(cursor_ - start_ - prefix_size_);
  }
Referenced by v8::internal::maglev::MaglevGraphBuilder::AddInitializedNodeToGraph(), v8::internal::maglev::MaglevGraphBuilder::AddInlinedArgumentsToDeoptFrame(), AdvanceTo(), v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), v8::internal::maglev::MaglevGraphBuilder::BuildBody(), v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts(), v8::internal::anonymous_namespace{runtime-compiler.cc}::DeoptAllOsrLoopsContainingDeoptExit(), v8::internal::Deoptimizer::DeoptExitIsInsideOsrLoop(), v8::internal::BytecodeArray::Disassemble(), GetAbsoluteOffset(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForEntryStackCheck(), v8::internal::maglev::MaglevGraphBuilder::GetDeoptFrameForLazyDeoptHelper(), v8::internal::maglev::MaglevGraphBuilder::GetLatestCheckpointedFrame(), v8::internal::interpreter::BytecodeArrayRandomIterator::Initialize(), v8::internal::maglev::MaglevGraphBuilder::KillPeeledLoopTargets(), v8::internal::maglev::MaglevGraphBuilder::MarkBytecodeDead(), v8::internal::anonymous_namespace{runtime-test.cc}::OffsetOfNextJumpLoop(), v8::internal::compiler::BytecodeGraphBuilder::PrepareFrameState(), v8::internal::BytecodeArray::PrintJson(), v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::PrintLivenessTo(), SetOffset(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness(), v8::internal::baseline::BaselineCompiler::VisitSingleBytecode(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
current_operand_scale()
OperandScale v8::internal::interpreter::BytecodeArrayIterator::current_operand_scale () const [inline]
Definition at line 127 of file bytecode-array-iterator.h.
{ return operand_scale_; }
Referenced by GetRegisterOperand(), GetSignedOperand(), and GetUnsignedOperand().
CurrentBytecodeIsValidOSREntry()
bool v8::internal::interpreter::BytecodeArrayIterator::CurrentBytecodeIsValidOSREntry () const
Definition at line 107 of file bytecode-array-iterator.cc.
                                                                 {
  return current_bytecode() == interpreter::Bytecode::kJumpLoop;
}
References current_bytecode().
Referenced by v8::internal::Deoptimizer::DeoptExitIsInsideOsrLoop(), v8::internal::anonymous_namespace{compiler.cc}::OptimizedCodeCache::Get(), v8::internal::anonymous_namespace{compiler.cc}::OptimizedCodeCache::Insert(), IsValidOSREntryOffset(), v8::internal::maglev::MaglevGraphBuilder::MaglevGraphBuilder(), and v8::internal::compiler::BytecodeGraphBuilder::VisitBytecodes().
done()
bool v8::internal::interpreter::BytecodeArrayIterator::done () const [inline]
Definition at line 179 of file bytecode-array-iterator.h.
{ return cursor_ >= end_; }
Referenced by v8::internal::DebugEvaluate::ApplySideEffectChecks(), v8::internal::maglev::MaglevGraphBuilder::BuildBody(), v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts(), v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), v8::internal::Debug::ClearSideEffectChecks(), v8::internal::anonymous_namespace{runtime-compiler.cc}::DeoptAllOsrLoopsContainingDeoptExit(), v8::internal::Deoptimizer::DeoptExitIsInsideOsrLoop(), v8::internal::BytecodeArray::Disassemble(), v8::internal::DebugEvaluate::FunctionGetSideEffectState(), v8::internal::baseline::BaselineCompiler::GenerateCode(), v8::internal::interpreter::BytecodeArrayRandomIterator::Initialize(), IsValidOffset(), v8::internal::anonymous_namespace{runtime-test.cc}::OffsetOfNextJumpLoop(), v8::internal::BytecodeArray::PrintJson(), v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::PrintLivenessTo(), and v8::internal::FeedbackVector::RecomputeOptimizedOsrCodeFlags().
GetAbsoluteOffset()
int v8::internal::interpreter::BytecodeArrayIterator::GetAbsoluteOffset (int relative_offset) const
Definition at line 346 of file bytecode-array-iterator.cc.
                                                                      {
  return current_offset() + relative_offset + prefix_size_;
}
References current_offset(), and prefix_size_.
Referenced by GetJumpTargetOffset(), and v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator*().
GetConstantAtIndex()
template<typename IsolateT >
Handle< Object > v8::internal::interpreter::BytecodeArrayIterator::GetConstantAtIndex (int offset, IsolateT * isolate) const
Definition at line 284 of file bytecode-array-iterator.cc.
                                        {
  return handle(bytecode_array()->constant_pool()->get(index), isolate);
}
References bytecode_array(), v8::internal::constant_pool, v8::internal::handle(), and v8::internal::index.
Referenced by GetConstantForIndexOperand().
GetConstantAtIndexAsSmi()
Tagged< Smi > v8::internal::interpreter::BytecodeArrayIterator::GetConstantAtIndexAsSmi (int offset) const
Definition at line 293 of file bytecode-array-iterator.cc.
                                                                          {
  return Cast<Smi>(bytecode_array()->constant_pool()->get(index));
}
References bytecode_array(), v8::internal::constant_pool, and v8::internal::index.
Referenced by v8::internal::baseline::BaselineCompiler::ConstantSmi(), GetRelativeJumpTargetOffset(), and v8::internal::interpreter::JumpTableTargetOffsets::iterator::UpdateAndAdvanceToValid().
GetConstantForIndexOperand()
template<typename IsolateT >
Handle< Object > v8::internal::interpreter::BytecodeArrayIterator::GetConstantForIndexOperand (int operand_index, IsolateT * isolate) const
Definition at line 298 of file bytecode-array-iterator.cc.
                                                {
  return GetConstantAtIndex(GetIndexOperand(operand_index), isolate);
}
References GetConstantAtIndex(), and GetIndexOperand().
Referenced by v8::internal::anonymous_namespace{isolate.cc}::GetPromiseMethod().
GetFlag16Operand()
uint32_t v8::internal::interpreter::BytecodeArrayIterator::GetFlag16Operand (int operand_index) const
Definition at line 159 of file bytecode-array-iterator.cc.
                                                                        {
  DCHECK_EQ(Bytecodes::GetOperandType(current_bytecode(), operand_index),
            OperandType::kFlag16);
  return GetUnsignedOperand(operand_index, OperandType::kFlag16);
}
References current_bytecode(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandType(), and GetUnsignedOperand().
Referenced by v8::internal::baseline::BaselineCompiler::Flag16().
GetFlag8Operand()
uint32_t v8::internal::interpreter::BytecodeArrayIterator::GetFlag8Operand (int operand_index) const
Definition at line 153 of file bytecode-array-iterator.cc.
                                                                       {
  DCHECK_EQ(Bytecodes::GetOperandType(current_bytecode(), operand_index),
            OperandType::kFlag8);
  return GetUnsignedOperand(operand_index, OperandType::kFlag8);
}
References current_bytecode(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandType(), and GetUnsignedOperand().
Referenced by v8::internal::baseline::BaselineCompiler::Flag8().
GetImmediateOperand()
int32_t v8::internal::interpreter::BytecodeArrayIterator::GetImmediateOperand (int operand_index) const
Definition at line 172 of file bytecode-array-iterator.cc.
                                                                          {
  DCHECK_EQ(Bytecodes::GetOperandType(current_bytecode(), operand_index),
            OperandType::kImm);
  return GetSignedOperand(operand_index, OperandType::kImm);
}
References current_bytecode(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandType(), and GetSignedOperand().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildFloat64BinarySmiOperationNodeForToNumber(), v8::internal::maglev::MaglevGraphBuilder::BuildGenericBinarySmiOperationNode(), v8::internal::maglev::MaglevGraphBuilder::BuildInt32BinarySmiOperationNode(), v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BinarySmiOperationNodeForToNumber(), v8::internal::Deoptimizer::DeoptExitIsInsideOsrLoop(), GetJumpTableTargetOffsets(), and v8::internal::baseline::BaselineCompiler::Int().
GetIndexOperand()
uint32_t v8::internal::interpreter::BytecodeArrayIterator::GetIndexOperand (int operand_index) const
Definition at line 185 of file bytecode-array-iterator.cc.
                                                                       {
  OperandType operand_type =
      Bytecodes::GetOperandType(current_bytecode(), operand_index);
  DCHECK_EQ(operand_type, OperandType::kIdx);
  return GetUnsignedOperand(operand_index, operand_type);
}
References current_bytecode(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandType(), and GetUnsignedOperand().
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), GetConstantForIndexOperand(), GetJumpTableTargetOffsets(), GetRelativeJumpTargetOffset(), GetSlotOperand(), and v8::internal::baseline::BaselineCompiler::Index().
GetIntrinsicIdOperand()
Runtime::FunctionId v8::internal::interpreter::BytecodeArrayIterator::GetIntrinsicIdOperand (int operand_index) const
Definition at line 273 of file bytecode-array-iterator.cc.
                             {
  OperandType operand_type =
      Bytecodes::GetOperandType(current_bytecode(), operand_index);
  DCHECK_EQ(operand_type, OperandType::kIntrinsicId);
  uint32_t raw_id = GetUnsignedOperand(operand_index, operand_type);
  return IntrinsicsHelper::ToRuntimeId(
      static_cast<IntrinsicsHelper::IntrinsicId>(raw_id));
}
References current_bytecode(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandType(), GetUnsignedOperand(), and v8::internal::interpreter::IntrinsicsHelper::ToRuntimeId().
Referenced by v8::internal::Debug::PerformSideEffectCheckAtBytecode().
GetJumpTableTargetOffsets()
JumpTableTargetOffsets v8::internal::interpreter::BytecodeArrayIterator::GetJumpTableTargetOffsets () const
Definition at line 329 of file bytecode-array-iterator.cc.
          {
  uint32_t table_start, table_size;
  int32_t case_value_base;
  if (current_bytecode() == Bytecode::kSwitchOnGeneratorState) {
    table_start = GetIndexOperand(1);
    table_size = GetUnsignedImmediateOperand(2);
    case_value_base = 0;
  } else {
    DCHECK_EQ(current_bytecode(), Bytecode::kSwitchOnSmiNoFeedback);
    table_start = GetIndexOperand(0);
    table_size = GetUnsignedImmediateOperand(1);
    case_value_base = GetImmediateOperand(2);
  }
  return JumpTableTargetOffsets(this, table_start, table_size, case_value_base);
}
References current_bytecode(), DCHECK_EQ, GetImmediateOperand(), GetIndexOperand(), and GetUnsignedImmediateOperand().
Referenced by v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts(), v8::internal::BytecodeArray::Disassemble(), v8::internal::maglev::MaglevGraphBuilder::MarkBytecodeDead(), v8::internal::BytecodeArray::PrintJson(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness().
GetJumpTargetOffset()
int v8::internal::interpreter::BytecodeArrayIterator::GetJumpTargetOffset () const
Definition at line 325 of file bytecode-array-iterator.cc.
                                                     {
  return GetAbsoluteOffset(GetRelativeJumpTargetOffset());
}
References GetAbsoluteOffset(), and GetRelativeJumpTargetOffset().
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), v8::internal::baseline::BaselineCompiler::BuildForwardJumpLabel(), v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts(), v8::internal::anonymous_namespace{runtime-compiler.cc}::DeoptAllOsrLoopsContainingDeoptExit(), v8::internal::Deoptimizer::DeoptExitIsInsideOsrLoop(), v8::internal::BytecodeArray::Disassemble(), v8::internal::Code::GetBaselinePCForNextExecutedBytecode(), v8::internal::maglev::MaglevGraphBuilder::KillPeeledLoopTargets(), v8::internal::maglev::MaglevGraphBuilder::MaglevGraphBuilder(), v8::internal::maglev::MaglevGraphBuilder::MarkBytecodeDead(), v8::internal::anonymous_namespace{runtime-test.cc}::OffsetOfNextJumpLoop(), v8::internal::BytecodeArray::PrintJson(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness(), v8::internal::compiler::BytecodeGraphBuilder::VisitBytecodes(), and v8::internal::maglev::MaglevGraphBuilder::VisitSingleBytecode().
GetNativeContextIndexOperand()
uint32_t v8::internal::interpreter::BytecodeArrayIterator::GetNativeContextIndexOperand (int operand_index) const
Definition at line 265 of file bytecode-array-iterator.cc.
                             {
  OperandType operand_type =
      Bytecodes::GetOperandType(current_bytecode(), operand_index);
  DCHECK_EQ(operand_type, OperandType::kNativeContextIndex);
  return GetUnsignedOperand(operand_index, operand_type);
}
References current_bytecode(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandType(), and GetUnsignedOperand().
GetParameter()
Register v8::internal::interpreter::BytecodeArrayIterator::GetParameter (int parameter_index) const
Definition at line 197 of file bytecode-array-iterator.cc.
                                                                      {
  DCHECK_GE(parameter_index, 0);
  // The parameter indices are shifted by 1 (receiver is the
  // first entry).
  return Register::FromParameterIndex(parameter_index + 1);
}
References DCHECK_GE, and v8::internal::interpreter::Register::FromParameterIndex().
GetRegisterCountOperand()
uint32_t v8::internal::interpreter::BytecodeArrayIterator::GetRegisterCountOperand (int operand_index) const
Definition at line 178 of file bytecode-array-iterator.cc.
                             {
  DCHECK_EQ(Bytecodes::GetOperandType(current_bytecode(), operand_index),
            OperandType::kRegCount);
  return GetUnsignedOperand(operand_index, OperandType::kRegCount);
}
References current_bytecode(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandType(), and GetUnsignedOperand().
Referenced by GetRegisterListOperand(), GetRegisterOperandRange(), v8::internal::baseline::BaselineCompiler::RegisterCount(), v8::internal::anonymous_namespace{isolate.cc}::TouchesRegister(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateAssignments(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForInOperand(), and v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForOutOperand().
GetRegisterListOperand()
RegisterList v8::internal::interpreter::BytecodeArrayIterator::GetRegisterListOperand (int operand_index) const
Definition at line 235 of file bytecode-array-iterator.cc.
                             {
  Register first = GetRegisterOperand(operand_index);
  uint32_t count = GetRegisterCountOperand(operand_index + 1);
  return RegisterList(first.index(), count);
}
References GetRegisterCountOperand(), GetRegisterOperand(), and v8::internal::interpreter::Register::index().
Referenced by v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOutList, operands... >::GetResultLocationAndSize().
GetRegisterOperand()
Register v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperand (int operand_index) const
Definition at line 204 of file bytecode-array-iterator.cc.
                                                                          {
  OperandType operand_type =
      Bytecodes::GetOperandType(current_bytecode(), operand_index);
  Address operand_start =
      reinterpret_cast<Address>(cursor_) +
      Bytecodes::GetOperandOffset(current_bytecode(), operand_index,
                                  current_operand_scale());
  return BytecodeDecoder::DecodeRegisterOperand(operand_start, operand_type,
                                                current_operand_scale());
}
References current_bytecode(), current_operand_scale(), cursor_, v8::internal::interpreter::BytecodeDecoder::DecodeRegisterOperand(), v8::internal::interpreter::Bytecodes::GetOperandOffset(), and v8::internal::interpreter::Bytecodes::GetOperandType().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildTruncatingInt32BinaryOperationNodeForToNumber(), v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), v8::internal::BreakIterator::GetBreakLocation(), GetRegisterListOperand(), GetRegisterPairOperand(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOut, operands... >::GetResultLocationAndSize(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOutPair, operands... >::GetResultLocationAndSize(), v8::internal::maglev::anonymous_namespace{maglev-graph-builder.cc}::GetResultLocationAndSizeHelper< index, interpreter::OperandType::kRegOutTriple, operands... >::GetResultLocationAndSize(), GetStarTargetRegister(), v8::internal::Debug::PerformSideEffectCheckAtBytecode(), v8::internal::baseline::BaselineCompiler::RegisterOperand(), v8::internal::anonymous_namespace{isolate.cc}::TouchesRegister(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateAssignments(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLiveness(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForInOperand(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateInLivenessForOutOperand(), v8::internal::compiler::anonymous_namespace{bytecode-analysis.cc}::UpdateOutLiveness(), and v8::internal::maglev::MaglevGraphBuilder::VisitCompareOperation().
GetRegisterOperandRange()
int v8::internal::interpreter::BytecodeArrayIterator::GetRegisterOperandRange (int operand_index) const
Definition at line 242 of file bytecode-array-iterator.cc.
                                                                          {
  DCHECK_LE(operand_index, Bytecodes::NumberOfOperands(current_bytecode()));
  const OperandType* operand_types =
      Bytecodes::GetOperandTypes(current_bytecode());
  OperandType operand_type = operand_types[operand_index];
  DCHECK(Bytecodes::IsRegisterOperandType(operand_type));
  if (operand_type == OperandType::kRegList ||
      operand_type == OperandType::kRegOutList) {
    return GetRegisterCountOperand(operand_index + 1);
  } else {
    return Bytecodes::GetNumberOfRegistersRepresentedBy(operand_type);
  }
}
References current_bytecode(), v8::internal::DCHECK(), DCHECK_LE, v8::internal::interpreter::Bytecodes::GetNumberOfRegistersRepresentedBy(), v8::internal::interpreter::Bytecodes::GetOperandTypes(), GetRegisterCountOperand(), v8::internal::interpreter::Bytecodes::IsRegisterOperandType(), and v8::internal::interpreter::Bytecodes::NumberOfOperands().
GetRegisterPairOperand()
std::pair< Register, Register > v8::internal::interpreter::BytecodeArrayIterator::GetRegisterPairOperand (int operand_index) const
Definition at line 228 of file bytecode-array-iterator.cc.
                             {
  Register first = GetRegisterOperand(operand_index);
  Register second(first.index() + 1);
  return std::make_pair(first, second);
}
References GetRegisterOperand(), and v8::internal::interpreter::Register::index().
Referenced by v8::internal::baseline::BaselineCompiler::StoreRegisterPair().
GetRelativeJumpTargetOffset()
int v8::internal::interpreter::BytecodeArrayIterator::GetRelativeJumpTargetOffset () const
Definition at line 309 of file bytecode-array-iterator.cc.
                                                             {
  Bytecode bytecode = current_bytecode();
  if (interpreter::Bytecodes::IsJumpImmediate(bytecode)) {
    int relative_offset = GetUnsignedImmediateOperand(0);
    if (bytecode == Bytecode::kJumpLoop) {
      relative_offset = -relative_offset;
    }
    return relative_offset;
  } else if (interpreter::Bytecodes::IsJumpConstant(bytecode)) {
    Tagged<Smi> smi = GetConstantAtIndexAsSmi(GetIndexOperand(0));
    return smi.value();
  } else {
    UNREACHABLE();
  }
}
References current_bytecode(), GetConstantAtIndexAsSmi(), GetIndexOperand(), GetUnsignedImmediateOperand(), v8::internal::interpreter::Bytecodes::IsJumpConstant(), v8::internal::interpreter::Bytecodes::IsJumpImmediate(), v8::internal::UNREACHABLE(), and v8::internal::Tagged< Smi >::value().
Referenced by GetJumpTargetOffset().
GetRuntimeIdOperand()
Runtime::FunctionId v8::internal::interpreter::BytecodeArrayIterator::GetRuntimeIdOperand (int operand_index) const
Definition at line 256 of file bytecode-array-iterator.cc.
                             {
  OperandType operand_type =
      Bytecodes::GetOperandType(current_bytecode(), operand_index);
  DCHECK_EQ(operand_type, OperandType::kRuntimeId);
  uint32_t raw_id = GetUnsignedOperand(operand_index, operand_type);
  return static_cast<Runtime::FunctionId>(raw_id);
}
References current_bytecode(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandType(), and GetUnsignedOperand().
Referenced by v8::internal::Debug::PerformSideEffectCheckAtBytecode().
GetSignedOperand()
int32_t v8::internal::interpreter::BytecodeArrayIterator::GetSignedOperand (int operand_index, OperandType operand_type) const [private]
Definition at line 138 of file bytecode-array-iterator.cc.
                                                       {
  DCHECK_GE(operand_index, 0);
  DCHECK_LT(operand_index, Bytecodes::NumberOfOperands(current_bytecode()));
  DCHECK_EQ(operand_type,
            Bytecodes::GetOperandType(current_bytecode(), operand_index));
  DCHECK(!Bytecodes::IsUnsignedOperandType(operand_type));
  Address operand_start =
      reinterpret_cast<Address>(cursor_) +
      Bytecodes::GetOperandOffset(current_bytecode(), operand_index,
                                  current_operand_scale());
  return BytecodeDecoder::DecodeSignedOperand(operand_start, operand_type,
                                              current_operand_scale());
}
References current_bytecode(), current_operand_scale(), cursor_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_LT, v8::internal::interpreter::BytecodeDecoder::DecodeSignedOperand(), v8::internal::interpreter::Bytecodes::GetOperandOffset(), v8::internal::interpreter::Bytecodes::GetOperandType(), v8::internal::interpreter::Bytecodes::IsUnsignedOperandType(), and v8::internal::interpreter::Bytecodes::NumberOfOperands().
Referenced by GetImmediateOperand().
GetSlotOperand()
FeedbackSlot v8::internal::interpreter::BytecodeArrayIterator::GetSlotOperand (int operand_index) const
Definition at line 192 of file bytecode-array-iterator.cc.
                                                                          {
  int index = GetIndexOperand(operand_index);
  return FeedbackVector::ToSlot(index);
}
References GetIndexOperand(), v8::internal::index, and v8::internal::FeedbackVector::ToSlot().
Referenced by v8::internal::anonymous_namespace{compiler.cc}::OptimizedCodeCache::Get(), v8::internal::anonymous_namespace{compiler.cc}::OptimizedCodeCache::Insert(), v8::internal::FeedbackVector::RecomputeOptimizedOsrCodeFlags(), and v8::internal::anonymous_namespace{runtime-compiler.cc}::TryGetOptimizedOsrCode().
GetStarTargetRegister()
Register v8::internal::interpreter::BytecodeArrayIterator::GetStarTargetRegister () const
Definition at line 215 of file bytecode-array-iterator.cc.
                                                            {
  Bytecode bytecode = current_bytecode();
  DCHECK(Bytecodes::IsAnyStar(bytecode));
  if (Bytecodes::IsShortStar(bytecode)) {
    return Register::FromShortStar(bytecode);
  } else {
    DCHECK_EQ(bytecode, Bytecode::kStar);
    DCHECK_EQ(Bytecodes::NumberOfOperands(bytecode), 1);
    DCHECK_EQ(Bytecodes::GetOperandTypes(bytecode)[0], OperandType::kRegOut);
    return GetRegisterOperand(0);
  }
}
References current_bytecode(), v8::internal::DCHECK(), DCHECK_EQ, v8::internal::interpreter::Register::FromShortStar(), v8::internal::interpreter::Bytecodes::GetOperandTypes(), GetRegisterOperand(), v8::internal::interpreter::Bytecodes::IsAnyStar(), v8::internal::interpreter::Bytecodes::IsShortStar(), and v8::internal::interpreter::Bytecodes::NumberOfOperands().
Referenced by v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), and v8::internal::anonymous_namespace{isolate.cc}::TouchesRegister().
GetUnsignedImmediateOperand()
uint32_t v8::internal::interpreter::BytecodeArrayIterator::GetUnsignedImmediateOperand (int operand_index) const
Definition at line 165 of file bytecode-array-iterator.cc.
                             {
  DCHECK_EQ(Bytecodes::GetOperandType(current_bytecode(), operand_index),
            OperandType::kUImm);
  return GetUnsignedOperand(operand_index, OperandType::kUImm);
}
References current_bytecode(), DCHECK_EQ, v8::internal::interpreter::Bytecodes::GetOperandType(), and GetUnsignedOperand().
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::Analyze(), v8::internal::anonymous_namespace{isolate.cc}::CallsCatchMethod(), v8::internal::BreakIterator::GetBreakLocation(), GetJumpTableTargetOffsets(), GetRelativeJumpTargetOffset(), and v8::internal::baseline::BaselineCompiler::Uint().
GetUnsignedOperand()
uint32_t v8::internal::interpreter::BytecodeArrayIterator::GetUnsignedOperand (int operand_index, OperandType operand_type) const [private]
Definition at line 123 of file bytecode-array-iterator.cc.
                                                       {
  DCHECK_GE(operand_index, 0);
  DCHECK_LT(operand_index, Bytecodes::NumberOfOperands(current_bytecode()));
  DCHECK_EQ(operand_type,
            Bytecodes::GetOperandType(current_bytecode(), operand_index));
  DCHECK(Bytecodes::IsUnsignedOperandType(operand_type));
  Address operand_start =
      reinterpret_cast<Address>(cursor_) +
      Bytecodes::GetOperandOffset(current_bytecode(), operand_index,
                                  current_operand_scale());
  return BytecodeDecoder::DecodeUnsignedOperand(operand_start, operand_type,
                                                current_operand_scale());
}
References current_bytecode(), current_operand_scale(), cursor_, v8::internal::DCHECK(), DCHECK_EQ, DCHECK_GE, DCHECK_LT, v8::internal::interpreter::BytecodeDecoder::DecodeUnsignedOperand(), v8::internal::interpreter::Bytecodes::GetOperandOffset(), v8::internal::interpreter::Bytecodes::GetOperandType(), v8::internal::interpreter::Bytecodes::IsUnsignedOperandType(), and v8::internal::interpreter::Bytecodes::NumberOfOperands().
Referenced by GetFlag16Operand(), GetFlag8Operand(), GetIndexOperand(), GetIntrinsicIdOperand(), GetNativeContextIndexOperand(), GetRegisterCountOperand(), GetRuntimeIdOperand(), and GetUnsignedImmediateOperand().
IsConstantAtIndexSmi()
bool v8::internal::interpreter::BytecodeArrayIterator::IsConstantAtIndexSmi (int offset) const
Definition at line 289 of file bytecode-array-iterator.cc.
                                                                {
  return IsSmi(bytecode_array()->constant_pool()->get(index));
}
References bytecode_array(), v8::internal::constant_pool, v8::internal::index, and v8::internal::IsSmi().
Referenced by v8::internal::interpreter::JumpTableTargetOffsets::iterator::UpdateAndAdvanceToValid().
IsValidOffset()
bool v8::internal::interpreter::BytecodeArrayIterator::IsValidOffset (Handle< BytecodeArray > bytecode_array, int offset) [static]
Definition at line 91 of file bytecode-array-iterator.cc.
                                                      {
  for (BytecodeArrayIterator it(bytecode_array); !it.done(); it.Advance()) {
    if (it.current_offset() == offset) return true;
    if (it.current_offset() > offset) break;
  }
  return false;
}
References bytecode_array(), and done().
Referenced by v8::internal::Deoptimizer::DeoptExitIsInsideOsrLoop().
IsValidOSREntryOffset()
bool v8::internal::interpreter::BytecodeArrayIterator::IsValidOSREntryOffset (Handle< BytecodeArray > bytecode_array, int offset) [static]
Definition at line 101 of file bytecode-array-iterator.cc.
                                                      {
  BytecodeArrayIterator it(bytecode_array, offset);
  return it.CurrentBytecodeIsValidOSREntry();
}
References bytecode_array(), and CurrentBytecodeIsValidOSREntry().
next_bytecode()
Bytecode v8::internal::interpreter::BytecodeArrayIterator::next_bytecode () const [inline]
Definition at line 118 of file bytecode-array-iterator.h.
                                 {
    uint8_t* next_cursor = cursor_ + current_bytecode_size_without_prefix();
    if (next_cursor == end_) return Bytecode::kIllegal;
    Bytecode next_bytecode = Bytecodes::FromByte(*next_cursor);
    if (Bytecodes::IsPrefixScalingBytecode(next_bytecode)) {
      next_bytecode = Bytecodes::FromByte(*(next_cursor + 1));
    }
    return next_bytecode;
  }
References v8::internal::interpreter::Bytecodes::FromByte(), and v8::internal::interpreter::Bytecodes::IsPrefixScalingBytecode().
next_offset()
int v8::internal::interpreter::BytecodeArrayIterator::next_offset () const [inline]
Definition at line 117 of file bytecode-array-iterator.h.
{ return current_offset() + current_bytecode_size(); }
Referenced by v8::internal::maglev::MaglevGraphBuilder::CalculatePredecessorCounts(), and v8::internal::maglev::MaglevGraphBuilder::MarkBytecodeDead().
operator!=()
bool v8::internal::interpreter::BytecodeArrayIterator::operator!= (const BytecodeArrayIterator & other) const [inline]
Definition at line 184 of file bytecode-array-iterator.h.
                                                            {
    return cursor_ != other.cursor_;
  }
References cursor_.
operator=()
BytecodeArrayIterator& v8::internal::interpreter::BytecodeArrayIterator::operator= (const BytecodeArrayIterator &) [delete]
operator==()
bool v8::internal::interpreter::BytecodeArrayIterator::operator== (const BytecodeArrayIterator & other) const [inline]
Definition at line 181 of file bytecode-array-iterator.h.
                                                            {
    return cursor_ == other.cursor_;
  }
References cursor_.
PrintTo()
std::ostream & v8::internal::interpreter::BytecodeArrayIterator::PrintTo (std::ostream & os) const
Definition at line 350 of file bytecode-array-iterator.cc.
                                                               {
  return BytecodeDecoder::Decode(os, cursor_ - prefix_size_);
}
References cursor_, v8::internal::interpreter::BytecodeDecoder::Decode(), and prefix_size_.
Referenced by v8::internal::compiler::BytecodeAnalysis::BytecodeAnalysisImpl::PrintLivenessTo(), and v8::internal::baseline::BaselineCompiler::VisitSingleBytecode().
Reset()
void v8::internal::interpreter::BytecodeArrayIterator::Reset ()
Definition at line 78 of file bytecode-array-iterator.cc.
                                  {
  cursor_ = start_;
  UpdateOperandScale();
}
References cursor_, start_, and UpdateOperandScale().
Referenced by v8::internal::baseline::BaselineCompiler::GenerateCode(), and SetOffset().
SetOffset()
void v8::internal::interpreter::BytecodeArrayIterator::SetOffset (int offset)
Definition at line 68 of file bytecode-array-iterator.cc.
                                                {
  DCHECK_GE(offset, 0);
  if (offset < current_offset()) {
    Reset();
  }
  // Advance to the given offset instead of just setting cursor_.
  // This way, we can guarantee that the offset is always valid.
  AdvanceTo(offset);
}
References AdvanceTo(), current_offset(), DCHECK_GE, and Reset().
Referenced by v8::internal::maglev::MaglevGraphBuilder::BuildBody(), v8::internal::maglev::MaglevGraphBuilder::KillPeeledLoopTargets(), and v8::internal::anonymous_namespace{runtime-test.cc}::OffsetOfNextJumpLoop().
SetOffsetUnchecked()
void v8::internal::interpreter::BytecodeArrayIterator::SetOffsetUnchecked (int offset) [protected]
Definition at line 84 of file bytecode-array-iterator.cc.
                                                         {
  DCHECK_GE(offset, 0);
  cursor_ = start_ + offset;
  UpdateOperandScale();
}
References cursor_, DCHECK_GE, start_, and UpdateOperandScale().
Referenced by v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex().
UpdateOperandScale()
void v8::internal::interpreter::BytecodeArrayIterator::UpdateOperandScale () [inline], [private]
Definition at line 196 of file bytecode-array-iterator.h.
                                   {
    if (done()) return;
    uint8_t current_byte = *cursor_;
    Bytecode current_bytecode = Bytecodes::FromByte(current_byte);
    if (Bytecodes::IsPrefixScalingBytecode(current_bytecode)) {
      operand_scale_ =
          Bytecodes::PrefixBytecodeToOperandScale(current_bytecode);
      ++cursor_;
      prefix_size_ = 1;
    } else {
      operand_scale_ = OperandScale::kSingle;
      prefix_size_ = 0;
    }
  }
References v8::internal::interpreter::Bytecodes::FromByte(), v8::internal::interpreter::Bytecodes::IsPrefixScalingBytecode(), and v8::internal::interpreter::Bytecodes::PrefixBytecodeToOperandScale().
Referenced by BytecodeArrayIterator(), Reset(), and SetOffsetUnchecked().
UpdatePointers()
void v8::internal::interpreter::BytecodeArrayIterator::UpdatePointers ()
Definition at line 354 of file bytecode-array-iterator.cc.
                                           {
  DisallowGarbageCollection no_gc;
  uint8_t* start =
      reinterpret_cast<uint8_t*>(bytecode_array_->GetFirstBytecodeAddress());
  if (start != start_) {
    start_ = start;
    uint8_t* end = start + bytecode_array_->length();
    size_t distance_to_end = end_ - cursor_;
    cursor_ = end - distance_to_end;
    end_ = end;
  }
}
References bytecode_array_, cursor_, v8::internal::compiler::end(), end_, v8::internal::anonymous_namespace{json-stringifier.cc}::no_gc, and start_.
UpdatePointersCallback()
static void v8::internal::interpreter::BytecodeArrayIterator::UpdatePointersCallback (void * iterator) [inline], [static]
Definition at line 173 of file bytecode-array-iterator.h.
                                                     {
    reinterpret_cast<BytecodeArrayIterator*>(iterator)->UpdatePointers();
  }
Referenced by BytecodeArrayIterator(), and ~BytecodeArrayIterator().
Member Data Documentation
bytecode_array_
Handle<BytecodeArray> v8::internal::interpreter::BytecodeArrayIterator::bytecode_array_ [private]
Definition at line 211 of file bytecode-array-iterator.h.
Referenced by UpdatePointers().
cursor_
uint8_t* v8::internal::interpreter::BytecodeArrayIterator::cursor_ [private]
Definition at line 216 of file bytecode-array-iterator.h.
Referenced by AdvanceTo(), ApplyDebugBreak(), GetRegisterOperand(), GetSignedOperand(), GetUnsignedOperand(), operator!=(), operator==(), PrintTo(), Reset(), SetOffsetUnchecked(), and UpdatePointers().
end_
uint8_t* v8::internal::interpreter::BytecodeArrayIterator::end_ [private]
Definition at line 213 of file bytecode-array-iterator.h.
Referenced by AdvanceTo(), and UpdatePointers().
local_heap_
LocalHeap* const v8::internal::interpreter::BytecodeArrayIterator::local_heap_ [private]
Definition at line 219 of file bytecode-array-iterator.h.
Referenced by BytecodeArrayIterator(), and ~BytecodeArrayIterator().
operand_scale_
OperandScale v8::internal::interpreter::BytecodeArrayIterator::operand_scale_ [private]
Definition at line 217 of file bytecode-array-iterator.h.
prefix_size_
int v8::internal::interpreter::BytecodeArrayIterator::prefix_size_ [private]
Definition at line 218 of file bytecode-array-iterator.h.
Referenced by ApplyDebugBreak(), GetAbsoluteOffset(), and PrintTo().
start_
uint8_t* v8::internal::interpreter::BytecodeArrayIterator::start_ [private]
Definition at line 212 of file bytecode-array-iterator.h.
Referenced by Reset(), SetOffsetUnchecked(), and UpdatePointers().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecode-array-iterator.h
/mnt/V8SourceCode/src/interpreter/bytecode-array-iterator.cc