v8::platform::DefaultForegroundTaskRunner Class Reference
#include <default-foreground-task-runner.h>
Classes
struct DelayedEntry
struct DelayedEntryCompare
class RunTaskScope
Public Types
using TimeFunction = double(*)()
Public Member Functions
DefaultForegroundTaskRunner (IdleTaskSupport idle_task_support, TimeFunction time_function)
void Terminate ()
std::unique_ptr< Task > PopTaskFromQueue (MessageLoopBehavior wait_for_work)
std::unique_ptr< IdleTask > PopTaskFromIdleQueue ()
double MonotonicallyIncreasingTime ()
bool IdleTasksEnabled () override
bool NonNestableTasksEnabled () const override
bool NonNestableDelayedTasksEnabled () const override
Private Types
enum Nestability { kNestable
, kNonNestable
 }
using TaskQueueEntry = std::pair< Nestability, std::unique_ptr< Task > >
Private Member Functions
void PostTaskImpl (std::unique_ptr< Task > task, const SourceLocation &location) override
void PostDelayedTaskImpl (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation &location) override
void PostIdleTaskImpl (std::unique_ptr< IdleTask > task, const SourceLocation &location) override
void PostNonNestableTaskImpl (std::unique_ptr< Task > task, const SourceLocation &location) override
void PostNonNestableDelayedTaskImpl (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation &location) override
void WaitForTaskLocked ()
std::unique_ptr< Task > PostTaskLocked (std::unique_ptr< Task > task, Nestability nestability)
void PostDelayedTaskLocked (std::unique_ptr< Task > task, double delay_in_seconds, Nestability nestability)
std::unique_ptr< Task > PopTaskFromDelayedQueueLocked (Nestability *nestability)
bool HasPoppableTaskInQueue () const
std::vector< std::unique_ptr< Task > > MoveExpiredDelayedTasksLocked ()
Private Attributes
bool terminated_ = false
base::Mutex mutex_
base::ConditionVariable event_loop_control_
int nesting_depth_ = 0
std::deque< TaskQueueEntry > task_queue_
IdleTaskSupport idle_task_support_
std::queue< std::unique_ptr< IdleTask > > idle_task_queue_
std::priority_queue< DelayedEntry, std::vector< DelayedEntry >, DelayedEntryCompare > delayed_task_queue_
TimeFunction time_function_
Detailed Description
Definition at line 19 of file default-foreground-task-runner.h.
Member Typedef Documentation
TaskQueueEntry
using v8::platform::DefaultForegroundTaskRunner::TaskQueueEntry = std::pair<Nestability, std::unique_ptr<Task> > [private]
Definition at line 99 of file default-foreground-task-runner.h.
TimeFunction
using v8::platform::DefaultForegroundTaskRunner::TimeFunction = double (*)()
Definition at line 22 of file default-foreground-task-runner.h.
Member Enumeration Documentation
Nestability
enum v8::platform::DefaultForegroundTaskRunner::Nestability [private]
Enumerator
kNestable
kNonNestable
Definition at line 65 of file default-foreground-task-runner.h.
{ kNestable, kNonNestable };
Constructor & Destructor Documentation
DefaultForegroundTaskRunner()
v8::platform::DefaultForegroundTaskRunner::DefaultForegroundTaskRunner (IdleTaskSupport idle_task_support, TimeFunction time_function)
Definition at line 25 of file default-foreground-task-runner.cc.
    : idle_task_support_(idle_task_support), time_function_(time_function) {}
Member Function Documentation
HasPoppableTaskInQueue()
bool v8::platform::DefaultForegroundTaskRunner::HasPoppableTaskInQueue () const [private]
Definition at line 120 of file default-foreground-task-runner.cc.
                                                               {
  if (nesting_depth_ == 0) return !task_queue_.empty();
  for (auto it = task_queue_.cbegin(); it != task_queue_.cend(); it++) {
    if (it->first == kNestable) return true;
  }
  return false;
}
References kNestable, nesting_depth_, and task_queue_.
Referenced by PopTaskFromQueue().
IdleTasksEnabled()
bool v8::platform::DefaultForegroundTaskRunner::IdleTasksEnabled () [override]
Definition at line 102 of file default-foreground-task-runner.cc.
                                                   {
  return idle_task_support_ == IdleTaskSupport::kEnabled;
}
References idle_task_support_, and v8::platform::kEnabled.
MonotonicallyIncreasingTime()
double v8::platform::DefaultForegroundTaskRunner::MonotonicallyIncreasingTime ()
Definition at line 65 of file default-foreground-task-runner.cc.
                                                                {
  return time_function_();
}
References time_function_.
Referenced by PopTaskFromDelayedQueueLocked(), PostDelayedTaskLocked(), and WaitForTaskLocked().
MoveExpiredDelayedTasksLocked()
std::vector< std::unique_ptr< Task > > v8::platform::DefaultForegroundTaskRunner::MoveExpiredDelayedTasksLocked () [private]
Definition at line 129 of file default-foreground-task-runner.cc.
                                                           {
  Nestability nestability;
  std::vector<std::unique_ptr<Task>> expired_tasks_to_delete;
  while (std::unique_ptr<Task> task =
             PopTaskFromDelayedQueueLocked(&nestability)) {
    auto to_delete = PostTaskLocked(std::move(task), nestability);
    if (to_delete) expired_tasks_to_delete.emplace_back(std::move(to_delete));
  }
  return expired_tasks_to_delete;
}
References PopTaskFromDelayedQueueLocked(), and PostTaskLocked().
Referenced by PopTaskFromQueue().
NonNestableDelayedTasksEnabled()
bool v8::platform::DefaultForegroundTaskRunner::NonNestableDelayedTasksEnabled () const [override]
Definition at line 116 of file default-foreground-task-runner.cc.
                                                                       {
  return true;
}
NonNestableTasksEnabled()
bool v8::platform::DefaultForegroundTaskRunner::NonNestableTasksEnabled () const [override]
Definition at line 112 of file default-foreground-task-runner.cc.
                                                                {
  return true;
}
PopTaskFromDelayedQueueLocked()
std::unique_ptr< Task > v8::platform::DefaultForegroundTaskRunner::PopTaskFromDelayedQueueLocked (Nestability * nestability) [private]
Definition at line 169 of file default-foreground-task-runner.cc.
                              {
  mutex_.AssertHeld();
  if (delayed_task_queue_.empty()) return {};
  double now = MonotonicallyIncreasingTime();
  const DelayedEntry& entry = delayed_task_queue_.top();
  if (entry.timeout_time > now) return {};
  // The const_cast here is necessary because there does not exist a clean way
  // to get a unique_ptr out of the priority queue. We provide the priority
  // queue with a custom comparison operator to make sure that the priority
  // queue does not access the unique_ptr. Therefore it should be safe to reset
  // the unique_ptr in the priority queue here. Note that the DelayedEntry is
  // removed from the priority_queue immediately afterwards.
  std::unique_ptr<Task> task = std::move(const_cast<DelayedEntry&>(entry).task);
  *nestability = entry.nestability;
  delayed_task_queue_.pop();
  return task;
}
References v8::base::Mutex::AssertHeld(), delayed_task_queue_, MonotonicallyIncreasingTime(), mutex_, v8::platform::DefaultForegroundTaskRunner::DelayedEntry::nestability, and v8::platform::DefaultForegroundTaskRunner::DelayedEntry::timeout_time.
Referenced by MoveExpiredDelayedTasksLocked().
PopTaskFromIdleQueue()
std::unique_ptr< IdleTask > v8::platform::DefaultForegroundTaskRunner::PopTaskFromIdleQueue ()
Definition at line 189 of file default-foreground-task-runner.cc.
                                                                          {
  base::MutexGuard guard(&mutex_);
  if (idle_task_queue_.empty()) return {};
  std::unique_ptr<IdleTask> task = std::move(idle_task_queue_.front());
  idle_task_queue_.pop();
  return task;
}
References idle_task_queue_, and mutex_.
PopTaskFromQueue()
std::unique_ptr< Task > v8::platform::DefaultForegroundTaskRunner::PopTaskFromQueue (MessageLoopBehavior wait_for_work)
Definition at line 140 of file default-foreground-task-runner.cc.
                                       {
  std::vector<std::unique_ptr<Task>> tasks_to_delete;
  base::MutexGuard guard(&mutex_);
  tasks_to_delete = MoveExpiredDelayedTasksLocked();
  while (!HasPoppableTaskInQueue()) {
    if (wait_for_work == MessageLoopBehavior::kDoNotWait) return {};
    WaitForTaskLocked();
    auto new_tasks_to_delete = MoveExpiredDelayedTasksLocked();
    tasks_to_delete.insert(tasks_to_delete.end(),
                           std::make_move_iterator(new_tasks_to_delete.begin()),
                           std::make_move_iterator(new_tasks_to_delete.end()));
  }
  auto it = task_queue_.begin();
  for (; it != task_queue_.end(); it++) {
    // When the task queue is nested (i.e. popping a task from the queue from
    // within a task), only nestable tasks may run. Otherwise, any task may run.
    if (nesting_depth_ == 0 || it->first == kNestable) break;
  }
  DCHECK(it != task_queue_.end());
  std::unique_ptr<Task> task = std::move(it->second);
  task_queue_.erase(it);
  return task;
}
References DCHECK, HasPoppableTaskInQueue(), v8::platform::kDoNotWait, kNestable, MoveExpiredDelayedTasksLocked(), mutex_, nesting_depth_, task_queue_, and WaitForTaskLocked().
PostDelayedTaskImpl()
void v8::platform::DefaultForegroundTaskRunner::PostDelayedTaskImpl (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation & location) [override], [private]
Definition at line 80 of file default-foreground-task-runner.cc.
                                    {
  base::MutexGuard guard(&mutex_);
  PostDelayedTaskLocked(std::move(task), delay_in_seconds, kNestable);
}
References kNestable, mutex_, and PostDelayedTaskLocked().
PostDelayedTaskLocked()
void v8::platform::DefaultForegroundTaskRunner::PostDelayedTaskLocked (std::unique_ptr< Task > task, double delay_in_seconds, Nestability nestability) [private]
Definition at line 69 of file default-foreground-task-runner.cc.
                             {
  mutex_.AssertHeld();
  DCHECK_GE(delay_in_seconds, 0.0);
  if (terminated_) return;
  double deadline = MonotonicallyIncreasingTime() + delay_in_seconds;
  delayed_task_queue_.push({deadline, nestability, std::move(task)});
  event_loop_control_.NotifyOne();
}
References v8::base::Mutex::AssertHeld(), DCHECK_GE, delayed_task_queue_, event_loop_control_, MonotonicallyIncreasingTime(), mutex_, v8::base::ConditionVariable::NotifyOne(), and terminated_.
Referenced by PostDelayedTaskImpl(), and PostNonNestableDelayedTaskImpl().
PostIdleTaskImpl()
void v8::platform::DefaultForegroundTaskRunner::PostIdleTaskImpl (std::unique_ptr< IdleTask > task, const SourceLocation & location) [override], [private]
Definition at line 94 of file default-foreground-task-runner.cc.
                                                                  {
  CHECK_EQ(IdleTaskSupport::kEnabled, idle_task_support_);
  base::MutexGuard guard(&mutex_);
  if (terminated_) return;
  idle_task_queue_.push(std::move(task));
}
References CHECK_EQ, idle_task_queue_, idle_task_support_, v8::platform::kEnabled, mutex_, and terminated_.
PostNonNestableDelayedTaskImpl()
void v8::platform::DefaultForegroundTaskRunner::PostNonNestableDelayedTaskImpl (std::unique_ptr< Task > task, double delay_in_seconds, const SourceLocation & location) [override], [private]
Definition at line 87 of file default-foreground-task-runner.cc.
                                    {
  base::MutexGuard guard(&mutex_);
  PostDelayedTaskLocked(std::move(task), delay_in_seconds, kNonNestable);
}
References kNonNestable, mutex_, and PostDelayedTaskLocked().
PostNonNestableTaskImpl()
void v8::platform::DefaultForegroundTaskRunner::PostNonNestableTaskImpl (std::unique_ptr< Task > task, const SourceLocation & location) [override], [private]
Definition at line 106 of file default-foreground-task-runner.cc.
                                                              {
  base::MutexGuard guard(&mutex_);
  task = PostTaskLocked(std::move(task), kNonNestable);
}
References kNonNestable, mutex_, and PostTaskLocked().
PostTaskImpl()
void v8::platform::DefaultForegroundTaskRunner::PostTaskImpl (std::unique_ptr< Task > task, const SourceLocation & location) [override], [private]
Definition at line 59 of file default-foreground-task-runner.cc.
                                                                               {
  base::MutexGuard guard(&mutex_);
  task = PostTaskLocked(std::move(task), kNestable);
}
References kNestable, mutex_, and PostTaskLocked().
PostTaskLocked()
std::unique_ptr< Task > v8::platform::DefaultForegroundTaskRunner::PostTaskLocked (std::unique_ptr< Task > task, Nestability nestability) [private]
Definition at line 50 of file default-foreground-task-runner.cc.
                                                       {
  mutex_.AssertHeld();
  if (terminated_) return task;
  task_queue_.push_back(std::make_pair(nestability, std::move(task)));
  event_loop_control_.NotifyOne();
  return {};
}
References v8::base::Mutex::AssertHeld(), event_loop_control_, mutex_, v8::base::ConditionVariable::NotifyOne(), task_queue_, and terminated_.
Referenced by MoveExpiredDelayedTasksLocked(), PostNonNestableTaskImpl(), and PostTaskImpl().
Terminate()
void v8::platform::DefaultForegroundTaskRunner::Terminate ()
Definition at line 29 of file default-foreground-task-runner.cc.
                                            {
  // Drain the task queues.
  // We make sure to delete tasks outside the TaskRunner lock, to avoid
  // potential deadlocks.
  std::deque<TaskQueueEntry> obsolete_tasks;
  std::priority_queue<DelayedEntry, std::vector<DelayedEntry>,
                      DelayedEntryCompare>
      obsolete_delayed_tasks;
  std::queue<std::unique_ptr<IdleTask>> obsolete_idle_tasks;
  {
    base::MutexGuard guard(&mutex_);
    terminated_ = true;
    task_queue_.swap(obsolete_tasks);
    delayed_task_queue_.swap(obsolete_delayed_tasks);
    idle_task_queue_.swap(obsolete_idle_tasks);
  }
  while (!obsolete_tasks.empty()) obsolete_tasks.pop_front();
  while (!obsolete_delayed_tasks.empty()) obsolete_delayed_tasks.pop();
  while (!obsolete_idle_tasks.empty()) obsolete_idle_tasks.pop();
}
References delayed_task_queue_, idle_task_queue_, mutex_, task_queue_, and terminated_.
WaitForTaskLocked()
void v8::platform::DefaultForegroundTaskRunner::WaitForTaskLocked () [private]
Definition at line 199 of file default-foreground-task-runner.cc.
                                                    {
  mutex_.AssertHeld();
  if (!delayed_task_queue_.empty()) {
    double now = MonotonicallyIncreasingTime();
    const DelayedEntry& entry = delayed_task_queue_.top();
    double time_until_task = entry.timeout_time - now;
    if (time_until_task > 0) {
      bool woken_up = event_loop_control_.WaitFor(
          &mutex_,
          base::TimeDelta::FromMicroseconds(
              time_until_task * base::TimeConstants::kMicrosecondsPerSecond));
      USE(woken_up);
    }
  } else {
    event_loop_control_.Wait(&mutex_);
  }
}
References v8::base::Mutex::AssertHeld(), delayed_task_queue_, event_loop_control_, v8::base::TimeDelta::FromMicroseconds(), v8::base::TimeConstants::kMicrosecondsPerSecond, MonotonicallyIncreasingTime(), mutex_, v8::platform::DefaultForegroundTaskRunner::DelayedEntry::timeout_time, USE, v8::base::ConditionVariable::Wait(), and v8::base::ConditionVariable::WaitFor().
Referenced by PopTaskFromQueue().
Member Data Documentation
delayed_task_queue_
std::priority_queue<DelayedEntry, std::vector<DelayedEntry>, DelayedEntryCompare> v8::platform::DefaultForegroundTaskRunner::delayed_task_queue_ [private]
Definition at line 123 of file default-foreground-task-runner.h.
Referenced by PopTaskFromDelayedQueueLocked(), PostDelayedTaskLocked(), Terminate(), and WaitForTaskLocked().
event_loop_control_
base::ConditionVariable v8::platform::DefaultForegroundTaskRunner::event_loop_control_ [private]
Definition at line 96 of file default-foreground-task-runner.h.
Referenced by PostDelayedTaskLocked(), PostTaskLocked(), and WaitForTaskLocked().
idle_task_queue_
std::queue<std::unique_ptr<IdleTask> > v8::platform::DefaultForegroundTaskRunner::idle_task_queue_ [private]
Definition at line 103 of file default-foreground-task-runner.h.
Referenced by PopTaskFromIdleQueue(), PostIdleTaskImpl(), and Terminate().
idle_task_support_
IdleTaskSupport v8::platform::DefaultForegroundTaskRunner::idle_task_support_ [private]
Definition at line 102 of file default-foreground-task-runner.h.
Referenced by IdleTasksEnabled(), and PostIdleTaskImpl().
mutex_
base::Mutex v8::platform::DefaultForegroundTaskRunner::mutex_ [private]
Definition at line 95 of file default-foreground-task-runner.h.
Referenced by PopTaskFromDelayedQueueLocked(), PopTaskFromIdleQueue(), PopTaskFromQueue(), PostDelayedTaskImpl(), PostDelayedTaskLocked(), PostIdleTaskImpl(), PostNonNestableDelayedTaskImpl(), PostNonNestableTaskImpl(), PostTaskImpl(), PostTaskLocked(), Terminate(), and WaitForTaskLocked().
nesting_depth_
int v8::platform::DefaultForegroundTaskRunner::nesting_depth_ = 0 [private]
Definition at line 97 of file default-foreground-task-runner.h.
Referenced by HasPoppableTaskInQueue(), and PopTaskFromQueue().
task_queue_
std::deque<TaskQueueEntry> v8::platform::DefaultForegroundTaskRunner::task_queue_ [private]
Definition at line 100 of file default-foreground-task-runner.h.
Referenced by HasPoppableTaskInQueue(), PopTaskFromQueue(), PostTaskLocked(), and Terminate().
terminated_
bool v8::platform::DefaultForegroundTaskRunner::terminated_ = false [private]
Definition at line 94 of file default-foreground-task-runner.h.
Referenced by PostDelayedTaskLocked(), PostIdleTaskImpl(), PostTaskLocked(), and Terminate().
time_function_
TimeFunction v8::platform::DefaultForegroundTaskRunner::time_function_ [private]
Definition at line 125 of file default-foreground-task-runner.h.
Referenced by MonotonicallyIncreasingTime().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/libplatform/default-foreground-task-runner.h
/mnt/V8SourceCode/src/libplatform/default-foreground-task-runner.cc