v8::internal::PreParserExpression Class Reference
#include <preparser.h>
Public Member Functions
PreParserExpression ()
bool IsNull () const
bool IsFailureExpression () const
bool IsIdentifier () const
PreParserIdentifier AsIdentifier () const
bool IsAssignment () const
bool IsPattern () const
bool IsStringLiteral () const
bool IsThis () const
bool IsThisProperty () const
bool IsProperty () const
bool IsPrivateReference () const
bool IsCall () const
bool IsSuperCallReference () const
bool IsImportCallExpression () const
bool IsFunctionLiteral () const
bool IsCallNew () const
bool is_tagged_template () const
bool is_parenthesized () const
void mark_parenthesized ()
void clear_parenthesized ()
PreParserExpression * AsCall ()
PreParserExpression * AsFunctionLiteral ()
PreParserExpression * operator-> ()
void SetShouldEagerCompile ()
int position () const
void set_function_token_position (int position)
void set_suspend_count (int suspend_count)
Static Public Member Functions
static PreParserExpression Null ()
static PreParserExpression Failure ()
static PreParserExpression Default ()
static PreParserExpression FromIdentifier (const PreParserIdentifier &id)
static PreParserExpression Assignment ()
static PreParserExpression ObjectLiteral ()
static PreParserExpression ArrayLiteral ()
static PreParserExpression StringLiteral ()
static PreParserExpression This ()
static PreParserExpression ThisPrivateReference ()
static PreParserExpression ThisProperty ()
static PreParserExpression Property ()
static PreParserExpression PrivateReference ()
static PreParserExpression Call ()
static PreParserExpression CallEval ()
static PreParserExpression ImportCall ()
static PreParserExpression SuperCallReference ()
Private Types
enum Type {
kNull
, kFailure
, kExpression
, kIdentifierExpression
,
kStringLiteralExpression
, kArrayOrObjectLiteralExpression
 }
enum ExpressionType {
kThisExpression
, kThisPropertyExpression
, kThisPrivateReferenceExpression
, kPropertyExpression
,
kPrivateReferenceExpression
, kCallExpression
, kCallEvalExpression
, kSuperCallReference
,
kAssignment
, kImportCallExpression
 }
using TypeField = base::BitField< Type, 0, 3 >
using IsParenthesizedField = TypeField::Next< bool, 1 >
using ExpressionTypeField = IsParenthesizedField::Next< ExpressionType, 4 >
using IdentifierTypeField = IsParenthesizedField::Next< PreParserIdentifier::Type, 8 >
using HasCoverInitializedNameField = IsParenthesizedField::Next< bool, 1 >
Private Member Functions
PreParserExpression (uint32_t expression_code)
Private Attributes
uint32_t code_
Friends
class PreParser
class PreParserFactory
class PreParserExpressionList
Detailed Description
Definition at line 83 of file preparser.h.
Member Typedef Documentation
ExpressionTypeField
using v8::internal::PreParserExpression::ExpressionTypeField = IsParenthesizedField::Next<ExpressionType, 4> [private]
Definition at line 310 of file preparser.h.
HasCoverInitializedNameField
using v8::internal::PreParserExpression::HasCoverInitializedNameField = IsParenthesizedField::Next<bool, 1> [private]
Definition at line 313 of file preparser.h.
IdentifierTypeField
using v8::internal::PreParserExpression::IdentifierTypeField = IsParenthesizedField::Next<PreParserIdentifier::Type, 8> [private]
Definition at line 311 of file preparser.h.
IsParenthesizedField
using v8::internal::PreParserExpression::IsParenthesizedField = TypeField::Next<bool, 1> [private]
Definition at line 306 of file preparser.h.
TypeField
using v8::internal::PreParserExpression::TypeField = base::BitField<Type, 0, 3> [private]
Definition at line 299 of file preparser.h.
Member Enumeration Documentation
ExpressionType
enum v8::internal::PreParserExpression::ExpressionType [private]
Enumerator
kThisExpression
kThisPropertyExpression
kThisPrivateReferenceExpression
kPropertyExpression
kPrivateReferenceExpression
kCallExpression
kCallEvalExpression
kSuperCallReference
kAssignment
kImportCallExpression
Definition at line 282 of file preparser.h.
                      {
    kThisExpression,
    kThisPropertyExpression,
    kThisPrivateReferenceExpression,
    kPropertyExpression,
    kPrivateReferenceExpression,
    kCallExpression,
    kCallEvalExpression,
    kSuperCallReference,
    kAssignment,
    kImportCallExpression,
  };
Type
enum v8::internal::PreParserExpression::Type [private]
Enumerator
kNull
kFailure
kExpression
kIdentifierExpression
kStringLiteralExpression
kArrayOrObjectLiteralExpression
Definition at line 273 of file preparser.h.
            {
    kNull,
    kFailure,
    kExpression,
    kIdentifierExpression,
    kStringLiteralExpression,
    kArrayOrObjectLiteralExpression
  };
Constructor & Destructor Documentation
PreParserExpression() [1/2]
v8::internal::PreParserExpression::PreParserExpression () [inline]
Definition at line 85 of file preparser.h.
: code_(TypeField::encode(kNull)) {}
Referenced by ArrayLiteral(), Assignment(), Call(), CallEval(), Default(), Failure(), FromIdentifier(), ImportCall(), Null(), ObjectLiteral(), PrivateReference(), Property(), StringLiteral(), SuperCallReference(), This(), ThisPrivateReference(), and ThisProperty().
PreParserExpression() [2/2]
v8::internal::PreParserExpression::PreParserExpression (uint32_t expression_code) [inline], [explicit], [private]
Definition at line 295 of file preparser.h.
      : code_(expression_code) {}
Member Function Documentation
ArrayLiteral()
static PreParserExpression v8::internal::PreParserExpression::ArrayLiteral () [inline], [static]
Definition at line 111 of file preparser.h.
                                            {
    return PreParserExpression(
        TypeField::encode(kArrayOrObjectLiteralExpression));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kArrayOrObjectLiteralExpression, and PreParserExpression().
Referenced by v8::internal::PreParserFactory::NewArrayLiteral().
AsCall()
PreParserExpression* v8::internal::PreParserExpression::AsCall () [inline]
Definition at line 258 of file preparser.h.
{ return this; }
AsFunctionLiteral()
PreParserExpression* v8::internal::PreParserExpression::AsFunctionLiteral () [inline]
Definition at line 259 of file preparser.h.
{ return this; }
AsIdentifier()
PreParserIdentifier v8::internal::PreParserExpression::AsIdentifier () const [inline]
Definition at line 181 of file preparser.h.
                                           {
    DCHECK(IsIdentifier());
    return PreParserIdentifier(IdentifierTypeField::decode(code_));
  }
References code_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), and IsIdentifier().
Referenced by v8::internal::PreParser::AsIdentifier(), and v8::internal::PreParserFactory::NewCall().
Assignment()
static PreParserExpression v8::internal::PreParserExpression::Assignment () [inline], [static]
Definition at line 101 of file preparser.h.
                                          {
    return PreParserExpression(TypeField::encode(kExpression) |
                               ExpressionTypeField::encode(kAssignment));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kAssignment, kExpression, and PreParserExpression().
Referenced by v8::internal::PreParserFactory::NewAssignment().
Call()
static PreParserExpression v8::internal::PreParserExpression::Call () [inline], [static]
Definition at line 149 of file preparser.h.
                                    {
    return PreParserExpression(TypeField::encode(kExpression) |
                               ExpressionTypeField::encode(kCallExpression));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kCallExpression, kExpression, and PreParserExpression().
Referenced by v8::internal::PreParserFactory::NewCall().
CallEval()
static PreParserExpression v8::internal::PreParserExpression::CallEval () [inline], [static]
Definition at line 154 of file preparser.h.
                                        {
    return PreParserExpression(
        TypeField::encode(kExpression) |
        ExpressionTypeField::encode(kCallEvalExpression));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kCallEvalExpression, kExpression, and PreParserExpression().
Referenced by v8::internal::PreParserFactory::NewCall().
clear_parenthesized()
void v8::internal::PreParserExpression::clear_parenthesized () [inline]
Definition at line 254 of file preparser.h.
                             {
    code_ = IsParenthesizedField::update(code_, false);
  }
References code_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::PreParser::CollapseNaryExpression().
Default()
static PreParserExpression v8::internal::PreParserExpression::Default () [inline], [static]
Definition at line 92 of file preparser.h.
                                       {
    return PreParserExpression(TypeField::encode(kExpression));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kExpression, and PreParserExpression().
Referenced by v8::internal::PreParser::BuildUnaryExpression(), v8::internal::PreParser::CloseTemplateLiteral(), v8::internal::PreParser::ExpressionFromLiteral(), v8::internal::PreParser::ExpressionListToExpression(), v8::internal::PreParser::ImportMetaExpression(), v8::internal::PreParserFactory::NewAwait(), v8::internal::PreParserFactory::NewBinaryOperation(), v8::internal::PreParserFactory::NewCallNew(), v8::internal::PreParserFactory::NewClassLiteralProperty(), v8::internal::PreParserFactory::NewCompareOperation(), v8::internal::PreParserFactory::NewConditional(), v8::internal::PreParserFactory::NewConditionalChain(), v8::internal::PreParserFactory::NewCountOperation(), v8::internal::PreParserFactory::NewEmptyParentheses(), v8::internal::PreParserFactory::NewFunctionLiteral(), v8::internal::PreParserFactory::NewNumberLiteral(), v8::internal::PreParserFactory::NewObjectLiteralProperty(), v8::internal::PreParserFactory::NewOptionalChain(), v8::internal::PreParserFactory::NewRegExpLiteral(), v8::internal::PreParserFactory::NewSpread(), v8::internal::PreParserFactory::NewStringLiteral(), v8::internal::PreParser::NewSuperPropertyReference(), v8::internal::PreParser::NewTargetExpression(), v8::internal::PreParserFactory::NewTheHoleLiteral(), v8::internal::PreParser::NewThrowReferenceError(), v8::internal::PreParserFactory::NewUnaryOperation(), v8::internal::PreParserFactory::NewUndefinedLiteral(), v8::internal::PreParser::NewV8Intrinsic(), v8::internal::PreParserFactory::NewVariableProxy(), v8::internal::PreParserFactory::NewYield(), v8::internal::PreParserFactory::NewYieldStar(), v8::internal::PreParser::ParseFunctionLiteral(), and v8::internal::PreParser::RewriteClassLiteral().
Failure()
static PreParserExpression v8::internal::PreParserExpression::Failure () [inline], [static]
Definition at line 88 of file preparser.h.
                                       {
    return PreParserExpression(TypeField::encode(kFailure));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kFailure, and PreParserExpression().
Referenced by v8::internal::PreParser::FailureExpression().
FromIdentifier()
static PreParserExpression v8::internal::PreParserExpression::FromIdentifier (const PreParserIdentifier & id) [inline], [static]
Definition at line 96 of file preparser.h.
                                                                           {
    return PreParserExpression(TypeField::encode(kIdentifierExpression) |
                               IdentifierTypeField::encode(id.type_));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kIdentifierExpression, and PreParserExpression().
Referenced by v8::internal::PreParser::ExpressionFromIdentifier(), and v8::internal::PreParser::ExpressionFromPrivateName().
ImportCall()
static PreParserExpression v8::internal::PreParserExpression::ImportCall () [inline], [static]
Definition at line 160 of file preparser.h.
                                          {
    return PreParserExpression(
        TypeField::encode(kExpression) |
        ExpressionTypeField::encode(kImportCallExpression));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kExpression, kImportCallExpression, and PreParserExpression().
Referenced by v8::internal::PreParserFactory::NewImportCallExpression().
is_parenthesized()
bool v8::internal::PreParserExpression::is_parenthesized () const [inline]
Definition at line 248 of file preparser.h.
{ return IsParenthesizedField::decode(code_); }
References code_, and v8::base::BitField< T, shift, size, U >::decode().
is_tagged_template()
bool v8::internal::PreParserExpression::is_tagged_template () const [inline]
Definition at line 246 of file preparser.h.
{ return false; }
IsAssignment()
bool v8::internal::PreParserExpression::IsAssignment () const [inline]
Definition at line 186 of file preparser.h.
                            {
    return TypeField::decode(code_) == kExpression &&
           ExpressionTypeField::decode(code_) == kAssignment;
  }
References code_, v8::base::BitField< T, shift, size, U >::decode(), kAssignment, and kExpression.
IsCall()
bool v8::internal::PreParserExpression::IsCall () const [inline]
Definition at line 227 of file preparser.h.
                      {
    return TypeField::decode(code_) == kExpression &&
           (ExpressionTypeField::decode(code_) == kCallExpression ||
            ExpressionTypeField::decode(code_) == kCallEvalExpression);
  }
References code_, v8::base::BitField< T, shift, size, U >::decode(), kCallEvalExpression, kCallExpression, and kExpression.
IsCallNew()
bool v8::internal::PreParserExpression::IsCallNew () const [inline]
Definition at line 245 of file preparser.h.
{ return false; }
IsFailureExpression()
bool v8::internal::PreParserExpression::IsFailureExpression () const [inline]
Definition at line 173 of file preparser.h.
                                   {
    return TypeField::decode(code_) == kFailure;
  }
References code_, v8::base::BitField< T, shift, size, U >::decode(), and kFailure.
IsFunctionLiteral()
bool v8::internal::PreParserExpression::IsFunctionLiteral () const [inline]
Definition at line 244 of file preparser.h.
{ return false; }
IsIdentifier()
bool v8::internal::PreParserExpression::IsIdentifier () const [inline]
Definition at line 177 of file preparser.h.
                            {
    return TypeField::decode(code_) == kIdentifierExpression;
  }
References code_, v8::base::BitField< T, shift, size, U >::decode(), and kIdentifierExpression.
Referenced by AsIdentifier(), v8::internal::PreParser::IsIdentifier(), and v8::internal::PreParserFactory::NewCall().
IsImportCallExpression()
bool v8::internal::PreParserExpression::IsImportCallExpression () const [inline]
Definition at line 238 of file preparser.h.
                                      {
    return TypeField::decode(code_) == kExpression &&
           ExpressionTypeField::decode(code_) == kImportCallExpression;
  }
References code_, v8::base::BitField< T, shift, size, U >::decode(), kExpression, and kImportCallExpression.
IsNull()
bool v8::internal::PreParserExpression::IsNull () const [inline]
Definition at line 172 of file preparser.h.
{ return TypeField::decode(code_) == kNull; }
References code_, v8::base::BitField< T, shift, size, U >::decode(), and kNull.
Referenced by v8::internal::PreParser::AddFormalParameter(), and v8::internal::PreParser::RewriteClassLiteral().
IsPattern()
bool v8::internal::PreParserExpression::IsPattern () const [inline]
Definition at line 191 of file preparser.h.
                         {
    return TypeField::decode(code_) == kArrayOrObjectLiteralExpression;
  }
References code_, v8::base::BitField< T, shift, size, U >::decode(), and kArrayOrObjectLiteralExpression.
IsPrivateReference()
bool v8::internal::PreParserExpression::IsPrivateReference () const [inline]
Definition at line 220 of file preparser.h.
                                  {
    return TypeField::decode(code_) == kExpression &&
           (ExpressionTypeField::decode(code_) == kPrivateReferenceExpression ||
            ExpressionTypeField::decode(code_) ==
                kThisPrivateReferenceExpression);
  }
References code_, v8::base::BitField< T, shift, size, U >::decode(), kExpression, kPrivateReferenceExpression, and kThisPrivateReferenceExpression.
Referenced by v8::internal::PreParser::IsPrivateReference(), and v8::internal::PreParserFactory::NewOptionalChain().
IsProperty()
bool v8::internal::PreParserExpression::IsProperty () const [inline]
Definition at line 211 of file preparser.h.
                          {
    return TypeField::decode(code_) == kExpression &&
           (ExpressionTypeField::decode(code_) == kPropertyExpression ||
            ExpressionTypeField::decode(code_) == kThisPropertyExpression ||
            ExpressionTypeField::decode(code_) == kPrivateReferenceExpression ||
            ExpressionTypeField::decode(code_) ==
                kThisPrivateReferenceExpression);
  }
References code_, v8::base::BitField< T, shift, size, U >::decode(), kExpression, kPrivateReferenceExpression, kPropertyExpression, kThisPrivateReferenceExpression, and kThisPropertyExpression.
IsStringLiteral()
bool v8::internal::PreParserExpression::IsStringLiteral () const [inline]
Definition at line 195 of file preparser.h.
                               {
    return TypeField::decode(code_) == kStringLiteralExpression;
  }
References code_, v8::base::BitField< T, shift, size, U >::decode(), and kStringLiteralExpression.
Referenced by v8::internal::PreParserStatement::ExpressionStatement().
IsSuperCallReference()
bool v8::internal::PreParserExpression::IsSuperCallReference () const [inline]
Definition at line 233 of file preparser.h.
                                    {
    return TypeField::decode(code_) == kExpression &&
           ExpressionTypeField::decode(code_) == kSuperCallReference;
  }
References code_, v8::base::BitField< T, shift, size, U >::decode(), kExpression, and kSuperCallReference.
IsThis()
bool v8::internal::PreParserExpression::IsThis () const [inline]
Definition at line 199 of file preparser.h.
                      {
    return TypeField::decode(code_) == kExpression &&
           ExpressionTypeField::decode(code_) == kThisExpression;
  }
References code_, v8::base::BitField< T, shift, size, U >::decode(), kExpression, and kThisExpression.
Referenced by v8::internal::PreParserFactory::NewProperty().
IsThisProperty()
bool v8::internal::PreParserExpression::IsThisProperty () const [inline]
Definition at line 204 of file preparser.h.
                              {
    return TypeField::decode(code_) == kExpression &&
           (ExpressionTypeField::decode(code_) == kThisPropertyExpression ||
            ExpressionTypeField::decode(code_) ==
                kThisPrivateReferenceExpression);
  }
References code_, v8::base::BitField< T, shift, size, U >::decode(), kExpression, kThisPrivateReferenceExpression, and kThisPropertyExpression.
Referenced by v8::internal::PreParser::IsThisProperty().
mark_parenthesized()
void v8::internal::PreParserExpression::mark_parenthesized () [inline]
Definition at line 250 of file preparser.h.
                            {
    code_ = IsParenthesizedField::update(code_, true);
  }
References code_, and v8::base::BitField< T, shift, size, U >::update().
Null()
static PreParserExpression v8::internal::PreParserExpression::Null () [inline], [static]
Definition at line 87 of file preparser.h.
{ return PreParserExpression(); }
References PreParserExpression().
Referenced by v8::internal::PreParser::NullExpression(), and v8::internal::PreParser::NullLiteralProperty().
ObjectLiteral()
static PreParserExpression v8::internal::PreParserExpression::ObjectLiteral () [inline], [static]
Definition at line 106 of file preparser.h.
                                             {
    return PreParserExpression(
        TypeField::encode(kArrayOrObjectLiteralExpression));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kArrayOrObjectLiteralExpression, and PreParserExpression().
Referenced by v8::internal::PreParserFactory::NewObjectLiteral().
operator->()
PreParserExpression* v8::internal::PreParserExpression::operator-> () [inline]
Definition at line 263 of file preparser.h.
{ return this; }
position()
int v8::internal::PreParserExpression::position () const [inline]
Definition at line 268 of file preparser.h.
{ return kNoSourcePosition; }
References v8::internal::kNoSourcePosition.
Referenced by v8::internal::PreParser::DeclarePrivateClassMember().
PrivateReference()
static PreParserExpression v8::internal::PreParserExpression::PrivateReference () [inline], [static]
Definition at line 143 of file preparser.h.
                                                {
    return PreParserExpression(
        TypeField::encode(kExpression) |
        ExpressionTypeField::encode(kPrivateReferenceExpression));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kExpression, kPrivateReferenceExpression, and PreParserExpression().
Referenced by v8::internal::PreParserFactory::NewOptionalChain(), and v8::internal::PreParserFactory::NewProperty().
Property()
static PreParserExpression v8::internal::PreParserExpression::Property () [inline], [static]
Definition at line 137 of file preparser.h.
                                        {
    return PreParserExpression(
        TypeField::encode(kExpression) |
        ExpressionTypeField::encode(kPropertyExpression));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kExpression, kPropertyExpression, and PreParserExpression().
Referenced by v8::internal::PreParserFactory::NewProperty().
set_function_token_position()
void v8::internal::PreParserExpression::set_function_token_position (int position) [inline]
Definition at line 269 of file preparser.h.
{}
set_suspend_count()
void v8::internal::PreParserExpression::set_suspend_count (int suspend_count) [inline]
Definition at line 270 of file preparser.h.
{}
SetShouldEagerCompile()
void v8::internal::PreParserExpression::SetShouldEagerCompile () [inline]
Definition at line 266 of file preparser.h.
{}
StringLiteral()
static PreParserExpression v8::internal::PreParserExpression::StringLiteral () [inline], [static]
Definition at line 116 of file preparser.h.
                                             {
    return PreParserExpression(TypeField::encode(kStringLiteralExpression));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kStringLiteralExpression, and PreParserExpression().
Referenced by v8::internal::PreParser::ExpressionFromLiteral().
SuperCallReference()
static PreParserExpression v8::internal::PreParserExpression::SuperCallReference () [inline], [static]
Definition at line 166 of file preparser.h.
                                                  {
    return PreParserExpression(
        TypeField::encode(kExpression) |
        ExpressionTypeField::encode(kSuperCallReference));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kExpression, kSuperCallReference, and PreParserExpression().
Referenced by v8::internal::PreParser::NewSuperCallReference().
This()
static PreParserExpression v8::internal::PreParserExpression::This () [inline], [static]
Definition at line 120 of file preparser.h.
                                    {
    return PreParserExpression(TypeField::encode(kExpression) |
                               ExpressionTypeField::encode(kThisExpression));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kExpression, kThisExpression, and PreParserExpression().
Referenced by v8::internal::PreParser::NewThisExpression(), and v8::internal::PreParser::ThisExpression().
ThisPrivateReference()
static PreParserExpression v8::internal::PreParserExpression::ThisPrivateReference () [inline], [static]
Definition at line 125 of file preparser.h.
                                                    {
    return PreParserExpression(
        TypeField::encode(kExpression) |
        ExpressionTypeField::encode(kThisPrivateReferenceExpression));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kExpression, kThisPrivateReferenceExpression, and PreParserExpression().
Referenced by v8::internal::PreParserFactory::NewProperty().
ThisProperty()
static PreParserExpression v8::internal::PreParserExpression::ThisProperty () [inline], [static]
Definition at line 131 of file preparser.h.
                                            {
    return PreParserExpression(
        TypeField::encode(kExpression) |
        ExpressionTypeField::encode(kThisPropertyExpression));
  }
References v8::base::BitField< T, shift, size, U >::encode(), kExpression, kThisPropertyExpression, and PreParserExpression().
Referenced by v8::internal::PreParserFactory::NewProperty().
Friends And Related Function Documentation
PreParser
friend class PreParser [friend]
Definition at line 316 of file preparser.h.
PreParserExpressionList
friend class PreParserExpressionList [friend]
Definition at line 318 of file preparser.h.
PreParserFactory
friend class PreParserFactory [friend]
Definition at line 317 of file preparser.h.
Member Data Documentation
code_
uint32_t v8::internal::PreParserExpression::code_ [private]
Definition at line 315 of file preparser.h.
Referenced by AsIdentifier(), clear_parenthesized(), is_parenthesized(), IsAssignment(), IsCall(), IsFailureExpression(), IsIdentifier(), IsImportCallExpression(), IsNull(), IsPattern(), IsPrivateReference(), IsProperty(), IsStringLiteral(), IsSuperCallReference(), IsThis(), IsThisProperty(), and mark_parenthesized().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/parsing/preparser.h