v8::internal::AssertionNode Class Reference
#include <regexp-nodes.h>
Public Types
enum AssertionType {
AT_END
, AT_START
, AT_BOUNDARY
, AT_NON_BOUNDARY
,
AFTER_NEWLINE
 }
Public Member Functions
AssertionNode * AsAssertionNode () override
void Accept (NodeVisitor *visitor) override
void Emit (RegExpCompiler *compiler, Trace *trace) override
void GetQuickCheckDetails (QuickCheckDetails *details, RegExpCompiler *compiler, int filled_in, bool not_at_start) override
void FillInBMInfo (Isolate *isolate, int offset, int budget, BoyerMooreLookahead *bm, bool not_at_start) override
AssertionType assertion_type ()
Static Public Member Functions
static AssertionNode * AtEnd (RegExpNode *on_success)
static AssertionNode * AtStart (RegExpNode *on_success)
static AssertionNode * AtBoundary (RegExpNode *on_success)
static AssertionNode * AtNonBoundary (RegExpNode *on_success)
static AssertionNode * AfterNewline (RegExpNode *on_success)
Private Types
enum IfPrevious { kIsNonWord
, kIsWord
 }
Private Member Functions
void EmitBoundaryCheck (RegExpCompiler *compiler, Trace *trace)
void BacktrackIfPrevious (RegExpCompiler *compiler, Trace *trace, IfPrevious backtrack_if_previous)
AssertionNode (AssertionType t, RegExpNode *on_success)
Private Attributes
friend Zone
AssertionType assertion_type_
Additional Inherited Members
Detailed Description
Definition at line 511 of file regexp-nodes.h.
Member Enumeration Documentation
AssertionType
enum v8::internal::AssertionNode::AssertionType
Enumerator
AT_END
AT_START
AT_BOUNDARY
AT_NON_BOUNDARY
AFTER_NEWLINE
Definition at line 513 of file regexp-nodes.h.
                     {
    AT_END,
    AT_START,
    AT_BOUNDARY,
    AT_NON_BOUNDARY,
    AFTER_NEWLINE
  };
IfPrevious
enum v8::internal::AssertionNode::IfPrevious [private]
Enumerator
kIsNonWord
kIsWord
Definition at line 549 of file regexp-nodes.h.
{ kIsNonWord, kIsWord };
Constructor & Destructor Documentation
AssertionNode()
v8::internal::AssertionNode::AssertionNode (AssertionType t, RegExpNode * on_success) [inline], [private]
Definition at line 552 of file regexp-nodes.h.
      : SeqRegExpNode(on_success), assertion_type_(t) {}
Member Function Documentation
Accept()
void v8::internal::AssertionNode::Accept (NodeVisitor * visitor) [override], [virtual]
Implements v8::internal::RegExpNode.
AfterNewline()
static AssertionNode* v8::internal::AssertionNode::AfterNewline (RegExpNode * on_success) [inline], [static]
Definition at line 532 of file regexp-nodes.h.
                                                             {
    return on_success->zone()->New<AssertionNode>(AFTER_NEWLINE, on_success);
  }
References AFTER_NEWLINE, v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), and v8::internal::RegExpNode::zone().
AsAssertionNode()
AssertionNode* v8::internal::AssertionNode::AsAssertionNode () [inline], [override]
Definition at line 535 of file regexp-nodes.h.
{ return this; }
assertion_type()
AssertionType v8::internal::AssertionNode::assertion_type () [inline]
Definition at line 543 of file regexp-nodes.h.
{ return assertion_type_; }
References assertion_type_.
Referenced by FillInBMInfo(), and v8::internal::anonymous_namespace{regexp-compiler.cc}::EatsAtLeastPropagator::VisitAssertion().
AtBoundary()
static AssertionNode* v8::internal::AssertionNode::AtBoundary (RegExpNode * on_success) [inline], [static]
Definition at line 526 of file regexp-nodes.h.
                                                           {
    return on_success->zone()->New<AssertionNode>(AT_BOUNDARY, on_success);
  }
References AT_BOUNDARY, v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), and v8::internal::RegExpNode::zone().
AtEnd()
static AssertionNode* v8::internal::AssertionNode::AtEnd (RegExpNode * on_success) [inline], [static]
Definition at line 520 of file regexp-nodes.h.
                                                      {
    return on_success->zone()->New<AssertionNode>(AT_END, on_success);
  }
References AT_END, v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), and v8::internal::RegExpNode::zone().
AtNonBoundary()
static AssertionNode* v8::internal::AssertionNode::AtNonBoundary (RegExpNode * on_success) [inline], [static]
Definition at line 529 of file regexp-nodes.h.
                                                              {
    return on_success->zone()->New<AssertionNode>(AT_NON_BOUNDARY, on_success);
  }
References AT_NON_BOUNDARY, v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), and v8::internal::RegExpNode::zone().
AtStart()
static AssertionNode* v8::internal::AssertionNode::AtStart (RegExpNode * on_success) [inline], [static]
Definition at line 523 of file regexp-nodes.h.
                                                        {
    return on_success->zone()->New<AssertionNode>(AT_START, on_success);
  }
References AT_START, v8::internal::Zone::New(), v8::internal::SeqRegExpNode::on_success(), and v8::internal::RegExpNode::zone().
BacktrackIfPrevious()
void v8::internal::AssertionNode::BacktrackIfPrevious (RegExpCompiler * compiler, Trace * trace, AssertionNode::IfPrevious backtrack_if_previous) [private]
Definition at line 2287 of file regexp-compiler.cc.
                                                   {
  RegExpMacroAssembler* assembler = compiler->macro_assembler();
  Trace new_trace(*trace);
  new_trace.InvalidateCurrentCharacter();
  Label fall_through;
  Label* non_word = backtrack_if_previous == kIsNonWord ? new_trace.backtrack()
                                                        : &fall_through;
  Label* word = backtrack_if_previous == kIsNonWord ? &fall_through
                                                    : new_trace.backtrack();
  // A positive (> 0) cp_offset means we've already successfully matched a
  // non-empty-width part of the pattern, and thus cannot be at or before the
  // start of the subject string. We can thus skip both at-start and
  // bounds-checks when loading the one-character lookbehind.
  const bool may_be_at_or_before_subject_string_start =
      new_trace.cp_offset() <= 0;
  if (may_be_at_or_before_subject_string_start) {
    // The start of input counts as a non-word character, so the question is
    // decided if we are at the start.
    assembler->CheckAtStart(new_trace.cp_offset(), non_word);
  }
  // If we've already checked that we are not at the start of input, it's okay
  // to load the previous character without bounds checks.
  const bool can_skip_bounds_check = !may_be_at_or_before_subject_string_start;
  assembler->LoadCurrentCharacter(new_trace.cp_offset() - 1, non_word,
                                  can_skip_bounds_check);
  EmitWordCheck(assembler, word, non_word, backtrack_if_previous == kIsNonWord);
  assembler->Bind(&fall_through);
  on_success()->Emit(compiler, &new_trace);
}
References v8::internal::Trace::backtrack(), v8::internal::RegExpMacroAssembler::Bind(), v8::internal::RegExpMacroAssembler::CheckAtStart(), v8::internal::Trace::cp_offset(), v8::internal::RegExpNode::Emit(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitWordCheck(), v8::internal::Trace::InvalidateCurrentCharacter(), kIsNonWord, v8::internal::RegExpMacroAssembler::LoadCurrentCharacter(), v8::internal::RegExpCompiler::macro_assembler(), and v8::internal::SeqRegExpNode::on_success().
Referenced by EmitBoundaryCheck().
Emit()
void v8::internal::AssertionNode::Emit (RegExpCompiler * compiler, Trace * trace) [override], [virtual]
Implements v8::internal::RegExpNode.
Definition at line 2335 of file regexp-compiler.cc.
                                                               {
  RegExpMacroAssembler* assembler = compiler->macro_assembler();
  switch (assertion_type_) {
    case AT_END: {
      Label ok;
      assembler->CheckPosition(trace->cp_offset(), &ok);
      assembler->GoTo(trace->backtrack());
      assembler->Bind(&ok);
      break;
    }
    case AT_START: {
      if (trace->at_start() == Trace::FALSE_VALUE) {
        assembler->GoTo(trace->backtrack());
        return;
      }
      if (trace->at_start() == Trace::UNKNOWN) {
        assembler->CheckNotAtStart(trace->cp_offset(), trace->backtrack());
        Trace at_start_trace = *trace;
        at_start_trace.set_at_start(Trace::TRUE_VALUE);
        on_success()->Emit(compiler, &at_start_trace);
        return;
      }
    } break;
    case AFTER_NEWLINE:
      EmitHat(compiler, on_success(), trace);
      return;
    case AT_BOUNDARY:
    case AT_NON_BOUNDARY: {
      EmitBoundaryCheck(compiler, trace);
      return;
    }
  }
  on_success()->Emit(compiler, trace);
}
References AFTER_NEWLINE, assertion_type_, AT_BOUNDARY, AT_END, AT_NON_BOUNDARY, v8::internal::Trace::at_start(), AT_START, v8::internal::Trace::backtrack(), v8::internal::RegExpMacroAssembler::Bind(), v8::internal::RegExpMacroAssembler::CheckNotAtStart(), v8::internal::RegExpMacroAssembler::CheckPosition(), v8::internal::Trace::cp_offset(), v8::internal::RegExpNode::Emit(), EmitBoundaryCheck(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitHat(), v8::internal::Trace::FALSE_VALUE, v8::internal::RegExpMacroAssembler::GoTo(), v8::internal::RegExpCompiler::macro_assembler(), v8::internal::SeqRegExpNode::on_success(), v8::internal::Trace::set_at_start(), v8::internal::Trace::TRUE_VALUE, and v8::internal::Trace::UNKNOWN.
EmitBoundaryCheck()
void v8::internal::AssertionNode::EmitBoundaryCheck (RegExpCompiler * compiler, Trace * trace) [private]
Definition at line 2240 of file regexp-compiler.cc.
                                                                            {
  RegExpMacroAssembler* assembler = compiler->macro_assembler();
  Isolate* isolate = assembler->isolate();
  Trace::TriBool next_is_word_character = Trace::UNKNOWN;
  bool not_at_start = (trace->at_start() == Trace::FALSE_VALUE);
  BoyerMooreLookahead* lookahead = bm_info(not_at_start);
  if (lookahead == nullptr) {
    int eats_at_least =
        std::min(kMaxLookaheadForBoyerMoore, EatsAtLeast(not_at_start));
    if (eats_at_least >= 1) {
      BoyerMooreLookahead* bm =
          zone()->New<BoyerMooreLookahead>(eats_at_least, compiler, zone());
      FillInBMInfo(isolate, 0, kRecursionBudget, bm, not_at_start);
      if (bm->at(0)->is_non_word()) next_is_word_character = Trace::FALSE_VALUE;
      if (bm->at(0)->is_word()) next_is_word_character = Trace::TRUE_VALUE;
    }
  } else {
    if (lookahead->at(0)->is_non_word())
      next_is_word_character = Trace::FALSE_VALUE;
    if (lookahead->at(0)->is_word()) next_is_word_character = Trace::TRUE_VALUE;
  }
  bool at_boundary = (assertion_type_ == AssertionNode::AT_BOUNDARY);
  if (next_is_word_character == Trace::UNKNOWN) {
    Label before_non_word;
    Label before_word;
    if (trace->characters_preloaded() != 1) {
      assembler->LoadCurrentCharacter(trace->cp_offset(), &before_non_word);
    }
    // Fall through on non-word.
    EmitWordCheck(assembler, &before_word, &before_non_word, false);
    // Next character is not a word character.
    assembler->Bind(&before_non_word);
    Label ok;
    BacktrackIfPrevious(compiler, trace, at_boundary ? kIsNonWord : kIsWord);
    assembler->GoTo(&ok);
    assembler->Bind(&before_word);
    BacktrackIfPrevious(compiler, trace, at_boundary ? kIsWord : kIsNonWord);
    assembler->Bind(&ok);
  } else if (next_is_word_character == Trace::TRUE_VALUE) {
    BacktrackIfPrevious(compiler, trace, at_boundary ? kIsWord : kIsNonWord);
  } else {
    DCHECK(next_is_word_character == Trace::FALSE_VALUE);
    BacktrackIfPrevious(compiler, trace, at_boundary ? kIsNonWord : kIsWord);
  }
}
References assertion_type_, v8::internal::BoyerMooreLookahead::at(), AT_BOUNDARY, v8::internal::Trace::at_start(), BacktrackIfPrevious(), v8::internal::RegExpMacroAssembler::Bind(), v8::internal::RegExpNode::bm_info(), v8::internal::Trace::characters_preloaded(), v8::internal::Trace::cp_offset(), v8::internal::DCHECK(), v8::internal::RegExpNode::EatsAtLeast(), v8::internal::anonymous_namespace{regexp-compiler.cc}::EmitWordCheck(), v8::internal::Trace::FALSE_VALUE, FillInBMInfo(), v8::internal::RegExpMacroAssembler::GoTo(), v8::internal::BoyerMoorePositionInfo::is_non_word(), v8::internal::BoyerMoorePositionInfo::is_word(), v8::internal::RegExpMacroAssembler::isolate(), kIsNonWord, kIsWord, v8::internal::regexp_compiler_constants::kMaxLookaheadForBoyerMoore, v8::internal::RegExpNode::kRecursionBudget, v8::internal::RegExpMacroAssembler::LoadCurrentCharacter(), v8::internal::RegExpCompiler::macro_assembler(), v8::internal::Zone::New(), v8::internal::Trace::TRUE_VALUE, v8::internal::Trace::UNKNOWN, and v8::internal::RegExpNode::zone().
Referenced by Emit().
FillInBMInfo()
void v8::internal::AssertionNode::FillInBMInfo (Isolate * isolate, int offset, int budget, BoyerMooreLookahead * bm, bool not_at_start) [override], [virtual]
Reimplemented from v8::internal::SeqRegExpNode.
Definition at line 1457 of file regexp-compiler.cc.
                                                                             {
  // Match the behaviour of EatsAtLeast on this node.
  if (assertion_type() == AT_START && not_at_start) return;
  on_success()->FillInBMInfo(isolate, offset, budget - 1, bm, not_at_start);
  SaveBMInfo(bm, not_at_start, offset);
}
References assertion_type(), AT_START, v8::internal::RegExpNode::FillInBMInfo(), v8::internal::SeqRegExpNode::on_success(), and v8::internal::RegExpNode::SaveBMInfo().
Referenced by EmitBoundaryCheck().
GetQuickCheckDetails()
void v8::internal::AssertionNode::GetQuickCheckDetails (QuickCheckDetails * details, RegExpCompiler * compiler, int filled_in, bool not_at_start) [override], [virtual]
Implements v8::internal::RegExpNode.
Definition at line 2324 of file regexp-compiler.cc.
                                                                           {
  if (assertion_type_ == AT_START && not_at_start) {
    details->set_cannot_match();
    return;
  }
  return on_success()->GetQuickCheckDetails(details, compiler, filled_in,
                                            not_at_start);
}
References assertion_type_, AT_START, v8::internal::RegExpNode::GetQuickCheckDetails(), v8::internal::SeqRegExpNode::on_success(), and v8::internal::QuickCheckDetails::set_cannot_match().
Member Data Documentation
assertion_type_
AssertionType v8::internal::AssertionNode::assertion_type_ [private]
Definition at line 554 of file regexp-nodes.h.
Referenced by assertion_type(), Emit(), EmitBoundaryCheck(), and GetQuickCheckDetails().
Zone
friend v8::internal::AssertionNode::Zone [private]
Definition at line 546 of file regexp-nodes.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-nodes.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc