v8::internal::ExternalString Class Reference
#include <string.h>
Classes
class BodyDescriptor
Public Member Functions
void InitExternalPointerFields (Isolate *isolate)
void VisitExternalPointers (ObjectVisitor *visitor)
bool is_uncached () const
int ExternalPayloadSize () const
Address resource_as_address () const
void set_address_as_resource (Isolate *isolate, Address address)
uint32_t GetResourceRefForDeserialization ()
void SetResourceRefForSerialization (uint32_t ref)
void DisposeResource (Isolate *isolate)
void InitExternalPointerFieldsDuringExternalization (Tagged< Map > new_map, Isolate *isolate)
Protected Attributes
ExternalPointerMember< kExternalStringResourceDataTag > resource_data_
Private Attributes
friend ObjectTraits< ExternalString >
Friends
struct OffsetsForDebug
class CodeStubAssembler
class compiler::AccessBuilder
class TorqueGeneratedExternalStringAsserts
Additional Inherited Members
Detailed Description
Definition at line 1186 of file string.h.
Member Function Documentation
DisposeResource()
void v8::internal::ExternalString::DisposeResource (Isolate * isolate) [inline]
Definition at line 1472 of file string-inl.h.
                                                     {
  Address value = resource_.load(isolate);
  v8::String::ExternalStringResourceBase* resource =
      reinterpret_cast<v8::String::ExternalStringResourceBase*>(value);
  // Dispose of the C++ object if it has not already been disposed.
  if (resource != nullptr) {
    if (!IsShared() && !HeapLayout::InWritableSharedSpace(this)) {
      resource->Unaccount(reinterpret_cast<v8::Isolate*>(isolate));
    }
    resource->Dispose();
    resource_.store(isolate, kNullAddress);
  }
}
References v8::String::ExternalStringResourceBase::Dispose(), v8::internal::HeapLayout::InWritableSharedSpace(), v8::internal::String::IsShared(), v8::internal::kNullAddress, v8::String::ExternalStringResourceBase::Unaccount(), and v8::internal::value.
ExternalPayloadSize()
int v8::internal::ExternalString::ExternalPayloadSize () const
Definition at line 2063 of file string.cc.
                                              {
  int length_multiplier = IsTwoByteRepresentation() ? i::kShortSize : kCharSize;
  return length() * length_multiplier;
}
References v8::internal::kCharSize, v8::internal::kShortSize, and v8::internal::length.
GetResourceRefForDeserialization()
uint32_t v8::internal::ExternalString::GetResourceRefForDeserialization () [inline]
Definition at line 1462 of file string-inl.h.
                                                          {
  return static_cast<uint32_t>(resource_.load_encoded());
}
InitExternalPointerFields()
void v8::internal::ExternalString::InitExternalPointerFields (Isolate * isolate) [inline]
Definition at line 1436 of file string-inl.h.
                                                               {
  resource_.Init(address(), isolate, kNullAddress);
  if (is_uncached()) return;
  resource_data_.Init(address(), isolate, kNullAddress);
}
References v8::internal::HeapObjectLayout::address(), and v8::internal::kNullAddress.
InitExternalPointerFieldsDuringExternalization()
void v8::internal::ExternalString::InitExternalPointerFieldsDuringExternalization (Tagged< Map > new_map, Isolate * isolate)
Definition at line 124 of file string.cc.
                                           {
  resource_.Init(address(), isolate, kNullAddress);
  bool is_uncached = (new_map->instance_type() & kUncachedExternalStringMask) ==
                     kUncachedExternalStringTag;
  if (!is_uncached) {
    resource_data_.Init(address(), isolate, kNullAddress);
  }
}
References v8::internal::HeapObjectLayout::address(), v8::internal::ExternalPointerMember< tag >::Init(), is_uncached(), v8::internal::kNullAddress, v8::internal::kUncachedExternalStringMask, v8::internal::kUncachedExternalStringTag, v8::internal::UncachedExternalString::resource_, and resource_data_.
is_uncached()
bool v8::internal::ExternalString::is_uncached () const [inline]
Definition at line 1431 of file string-inl.h.
                                       {
  InstanceType type = map()->instance_type();
  return (type & kUncachedExternalStringMask) == kUncachedExternalStringTag;
}
References v8::internal::kUncachedExternalStringMask, v8::internal::kUncachedExternalStringTag, v8::internal::HeapObjectLayout::map(), and v8::internal::tracing::type.
Referenced by InitExternalPointerFieldsDuringExternalization(), and v8::internal::ExternalString::BodyDescriptor::SizeOf().
resource_as_address()
Address v8::internal::ExternalString::resource_as_address () const [inline]
Definition at line 1448 of file string-inl.h.
                                                  {
  IsolateForSandbox isolate = GetCurrentIsolateForSandbox();
  return resource_.load(isolate);
}
References v8::internal::GetCurrentIsolateForSandbox().
set_address_as_resource()
void v8::internal::ExternalString::set_address_as_resource (Isolate * isolate, Address address) [inline]
Definition at line 1453 of file string-inl.h.
                                                                            {
  resource_.store(isolate, value);
  if (IsExternalOneByteString(this)) {
    Cast<ExternalOneByteString>(this)->update_data_cache(isolate);
  } else {
    Cast<ExternalTwoByteString>(this)->update_data_cache(isolate);
  }
}
References v8::internal::value.
SetResourceRefForSerialization()
void v8::internal::ExternalString::SetResourceRefForSerialization (uint32_t ref) [inline]
Definition at line 1466 of file string-inl.h.
                                                                {
  resource_.store_encoded(static_cast<ExternalPointer_t>(ref));
  if (is_uncached()) return;
  resource_data_.store_encoded(kNullExternalPointer);
}
References v8::internal::kNullExternalPointer.
VisitExternalPointers()
void v8::internal::ExternalString::VisitExternalPointers (ObjectVisitor * visitor) [inline]
Definition at line 1442 of file string-inl.h.
                                                                 {
  visitor->VisitExternalPointer(this, ExternalPointerSlot(&resource_));
  if (is_uncached()) return;
  visitor->VisitExternalPointer(this, ExternalPointerSlot(&resource_data_));
}
References v8::internal::ObjectVisitor::VisitExternalPointer().
Friends And Related Function Documentation
CodeStubAssembler
friend class CodeStubAssembler [friend]
Definition at line 1215 of file string.h.
compiler::AccessBuilder
friend class compiler::AccessBuilder [friend]
Definition at line 1216 of file string.h.
OffsetsForDebug
friend struct OffsetsForDebug [friend]
Definition at line 1214 of file string.h.
TorqueGeneratedExternalStringAsserts
friend class TorqueGeneratedExternalStringAsserts [friend]
Definition at line 1217 of file string.h.
Member Data Documentation
ObjectTraits< ExternalString >
friend v8::internal::ExternalString::ObjectTraits< ExternalString > [private]
Definition at line 1213 of file string.h.
resource_data_
ExternalPointerMember<kExternalStringResourceDataTag> v8::internal::ExternalString::resource_data_ [protected]
Definition at line 1220 of file string.h.
Referenced by InitExternalPointerFieldsDuringExternalization().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/objects/string.h
/mnt/V8SourceCode/src/objects/string-inl.h
/mnt/V8SourceCode/src/objects/string.cc