v8::internal::AlignedSlotAllocator Class Reference
#include <aligned-slot-allocator.h>
Public Member Functions
AlignedSlotAllocator ()=default
int Allocate (int n)
int NextSlot (int n) const
int AllocateUnaligned (int n)
int Align (int n)
int Size () const
Static Public Member Functions
static int NumSlotsForWidth (int bytes)
Static Public Attributes
static constexpr int kSlotSize = kSystemPointerSize
Static Private Member Functions
static bool IsValid (int slot)
Private Attributes
int next1_ = kInvalidSlot
int next2_ = kInvalidSlot
int next4_ = 0
int size_ = 0
Static Private Attributes
static constexpr int kInvalidSlot = -1
Detailed Description
Definition at line 20 of file aligned-slot-allocator.h.
Constructor & Destructor Documentation
AlignedSlotAllocator()
v8::internal::AlignedSlotAllocator::AlignedSlotAllocator () [default]
Member Function Documentation
Align()
int v8::internal::AlignedSlotAllocator::Align (int n)
Definition at line 113 of file aligned-slot-allocator.cc.
                                     {
  DCHECK(base::bits::IsPowerOfTwo(n));
  DCHECK_LE(n, 4);
  int mask = n - 1;
  int misalignment = size_ & mask;
  int padding = (n - misalignment) & mask;
  AllocateUnaligned(padding);
  return padding;
}
References AllocateUnaligned(), v8::internal::DCHECK(), DCHECK_LE, v8::base::bits::IsPowerOfTwo(), and size_.
Referenced by v8::internal::compiler::Frame::AlignFrame().
Allocate()
int v8::internal::AlignedSlotAllocator::Allocate (int n)
Definition at line 21 of file aligned-slot-allocator.cc.
                                        {
  DCHECK(n == 1 || n == 2 || n == 4);
  // Check invariants.
  DCHECK_EQ(0, next4_ & 3);
  DCHECK_IMPLIES(IsValid(next2_), (next2_ & 1) == 0);
  // The sentinel value kInvalidSlot is used to indicate no slot.
  // next1_ is the index of the 1 slot fragment, or kInvalidSlot.
  // next2_ is the 2-aligned index of the 2 slot fragment, or kInvalidSlot.
  // next4_ is the 4-aligned index of the next 4 slot group. It is always valid.
  // In order to ensure we only have a single 1- or 2-slot fragment, we greedily
  // use any fragment that satisfies the request.
  int result = kInvalidSlot;
  switch (n) {
    case 1: {
      if (IsValid(next1_)) {
        result = next1_;
        next1_ = kInvalidSlot;
      } else if (IsValid(next2_)) {
        result = next2_;
        next1_ = result + 1;
        next2_ = kInvalidSlot;
      } else {
        result = next4_;
        next1_ = result + 1;
        next2_ = result + 2;
        next4_ += 4;
      }
      break;
    }
    case 2: {
      if (IsValid(next2_)) {
        result = next2_;
        next2_ = kInvalidSlot;
      } else {
        result = next4_;
        next2_ = result + 2;
        next4_ += 4;
      }
      break;
    }
    case 4: {
      result = next4_;
      next4_ += 4;
      break;
    }
    default:
      UNREACHABLE();
  }
  DCHECK(IsValid(result));
  size_ = std::max(size_, result + n);
  return result;
}
References v8::internal::DCHECK(), DCHECK_EQ, DCHECK_IMPLIES, IsValid(), kInvalidSlot, next1_, next2_, next4_, v8::base::internal::result, size_, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::LinkageAllocator::NextStackSlot().
AllocateUnaligned()
int v8::internal::AlignedSlotAllocator::AllocateUnaligned (int n)
Definition at line 75 of file aligned-slot-allocator.cc.
                                                 {
  DCHECK_GE(n, 0);
  // Check invariants.
  DCHECK_EQ(0, next4_ & 3);
  DCHECK_IMPLIES(IsValid(next2_), (next2_ & 1) == 0);
  // Reserve |n| slots at |size_|, invalidate fragments below the new |size_|,
  // and add any new fragments beyond the new |size_|.
  int result = size_;
  size_ += n;
  switch (size_ & 3) {
    case 0: {
      next1_ = next2_ = kInvalidSlot;
      next4_ = size_;
      break;
    }
    case 1: {
      next1_ = size_;
      next2_ = size_ + 1;
      next4_ = size_ + 3;
      break;
    }
    case 2: {
      next1_ = kInvalidSlot;
      next2_ = size_;
      next4_ = size_ + 2;
      break;
    }
    case 3: {
      next1_ = size_;
      next2_ = kInvalidSlot;
      next4_ = size_ + 1;
      break;
    }
  }
  return result;
}
References DCHECK_EQ, DCHECK_GE, DCHECK_IMPLIES, IsValid(), kInvalidSlot, next1_, next2_, next4_, v8::base::internal::result, and size_.
Referenced by Align(), v8::internal::wasm::LinkageAllocator::EndSlotArea(), v8::internal::compiler::Frame::Frame(), and v8::internal::wasm::LinkageAllocator::SetStackOffset().
IsValid()
static bool v8::internal::AlignedSlotAllocator::IsValid (int slot) [inline], [static], [private]
Definition at line 58 of file aligned-slot-allocator.h.
{ return slot > kInvalidSlot; }
Referenced by Allocate(), AllocateUnaligned(), and NextSlot().
NextSlot()
int v8::internal::AlignedSlotAllocator::NextSlot (int n) const
Definition at line 13 of file aligned-slot-allocator.cc.
                                              {
  DCHECK(n == 1 || n == 2 || n == 4);
  if (n <= 1 && IsValid(next1_)) return next1_;
  if (n <= 2 && IsValid(next2_)) return next2_;
  DCHECK(IsValid(next4_));
  return next4_;
}
References v8::internal::DCHECK(), IsValid(), next1_, next2_, and next4_.
NumSlotsForWidth()
static int v8::internal::AlignedSlotAllocator::NumSlotsForWidth (int bytes) [inline], [static]
Definition at line 25 of file aligned-slot-allocator.h.
                                         {
    DCHECK_GT(bytes, 0);
    return (bytes + kSlotSize - 1) / kSlotSize;
  }
References DCHECK_GT, and cppgc::internal::kSlotSize.
Referenced by v8::internal::compiler::Frame::AlignFrame(), v8::internal::compiler::Frame::AlignSavedCalleeRegisterSlots(), v8::internal::compiler::Frame::AllocateSpillSlot(), v8::internal::compiler::InstructionOperand::InterferesWith(), and v8::internal::wasm::LinkageAllocator::NextStackSlot().
Size()
int v8::internal::AlignedSlotAllocator::Size () const [inline]
Definition at line 53 of file aligned-slot-allocator.h.
{ return size_; }
Referenced by v8::internal::compiler::Frame::AlignFrame(), v8::internal::wasm::LinkageAllocator::NumStackSlots(), and v8::internal::wasm::LinkageAllocator::SetStackOffset().
Member Data Documentation
kInvalidSlot
constexpr int v8::internal::AlignedSlotAllocator::kInvalidSlot = -1 [static], [constexpr], [private]
Definition at line 56 of file aligned-slot-allocator.h.
Referenced by Allocate(), and AllocateUnaligned().
kSlotSize
constexpr int v8::internal::AlignedSlotAllocator::kSlotSize = kSystemPointerSize [static], [constexpr]
Definition at line 23 of file aligned-slot-allocator.h.
Referenced by v8::internal::compiler::Frame::AllocateSpillSlot().
next1_
int v8::internal::AlignedSlotAllocator::next1_ = kInvalidSlot [private]
Definition at line 60 of file aligned-slot-allocator.h.
Referenced by Allocate(), AllocateUnaligned(), and NextSlot().
next2_
int v8::internal::AlignedSlotAllocator::next2_ = kInvalidSlot [private]
Definition at line 61 of file aligned-slot-allocator.h.
Referenced by Allocate(), AllocateUnaligned(), and NextSlot().
next4_
int v8::internal::AlignedSlotAllocator::next4_ = 0 [private]
Definition at line 62 of file aligned-slot-allocator.h.
Referenced by Allocate(), AllocateUnaligned(), and NextSlot().
size_
int v8::internal::AlignedSlotAllocator::size_ = 0 [private]
Definition at line 63 of file aligned-slot-allocator.h.
Referenced by Align(), Allocate(), and AllocateUnaligned().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/codegen/aligned-slot-allocator.h
/mnt/V8SourceCode/src/codegen/aligned-slot-allocator.cc