v8::internal::RegExpUtils Class Reference
#include <regexp-utils.h>
Static Public Member Functions
static Handle< String > GenericCaptureGetter (Isolate *isolate, DirectHandle< RegExpMatchInfo > match_info, int capture, bool *ok=nullptr)
static bool IsMatchedCapture (Tagged< RegExpMatchInfo > match_info, int capture)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > SetLastIndex (Isolate *isolate, DirectHandle< JSReceiver > regexp, uint64_t value)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > GetLastIndex (Isolate *isolate, DirectHandle< JSReceiver > recv)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< JSAny > RegExpExec (Isolate *isolate, DirectHandle< JSReceiver > regexp, DirectHandle< String > string, DirectHandle< Object > exec)
static bool IsUnmodifiedRegExp (Isolate *isolate, DirectHandle< Object > obj)
static uint64_t AdvanceStringIndex (Tagged< String > string, uint64_t index, bool unicode)
static V8_WARN_UNUSED_RESULT MaybeDirectHandle< Object > SetAdvancedStringIndex (Isolate *isolate, DirectHandle< JSReceiver > regexp, DirectHandle< String > string, bool unicode)
Detailed Description
Definition at line 19 of file regexp-utils.h.
Member Function Documentation
AdvanceStringIndex()
uint64_t v8::internal::RegExpUtils::AdvanceStringIndex (Tagged< String > string, uint64_t index, bool unicode) [static]
Definition at line 187 of file regexp-utils.cc.
                                                       {
  DCHECK_LE(static_cast<double>(index), kMaxSafeInteger);
  const uint64_t string_length = static_cast<uint64_t>(string->length());
  if (unicode && index < string_length) {
    const uint16_t first = string->Get(static_cast<uint32_t>(index));
    if (first >= 0xD800 && first <= 0xDBFF && index + 1 < string_length) {
      DCHECK_LT(index, std::numeric_limits<uint64_t>::max());
      const uint16_t second = string->Get(static_cast<uint32_t>(index + 1));
      if (second >= 0xDC00 && second <= 0xDFFF) {
        return index + 2;
      }
    }
  }
  return index + 1;
}
References DCHECK_LE, DCHECK_LT, v8::internal::index, and v8::internal::kMaxSafeInteger.
Referenced by v8::internal::IrregexpInterpreter::Match(), v8::internal::RUNTIME_FUNCTION(), and SetAdvancedStringIndex().
GenericCaptureGetter()
Handle< String > v8::internal::RegExpUtils::GenericCaptureGetter (Isolate * isolate, DirectHandle< RegExpMatchInfo > match_info, int capture, bool * ok = nullptr) [static]
Definition at line 18 of file regexp-utils.cc.
              {
  const int capture_start_index = RegExpMatchInfo::capture_start_index(capture);
  if (capture_start_index >= match_info->number_of_capture_registers()) {
    if (ok != nullptr) *ok = false;
    return isolate->factory()->empty_string();
  }
  const int capture_end_index = RegExpMatchInfo::capture_end_index(capture);
  const int match_start = match_info->capture(capture_start_index);
  const int match_end = match_info->capture(capture_end_index);
  if (match_start == -1 || match_end == -1) {
    if (ok != nullptr) *ok = false;
    return isolate->factory()->empty_string();
  }
  if (ok != nullptr) *ok = true;
  Handle<String> last_subject(match_info->last_subject(), isolate);
  return isolate->factory()->NewSubString(last_subject, match_start, match_end);
}
References v8::internal::RegExpMatchInfo::capture_end_index(), v8::internal::RegExpMatchInfo::capture_start_index(), and v8::internal::Isolate::factory().
Referenced by v8::internal::BUILTIN(), v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::GetCapture(), v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::GetMatch(), v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::GetNamedCapture(), and v8::internal::RUNTIME_FUNCTION().
GetLastIndex()
MaybeDirectHandle< Object > v8::internal::RegExpUtils::GetLastIndex (Isolate * isolate, DirectHandle< JSReceiver > recv) [static]
Definition at line 80 of file regexp-utils.cc.
                                                     {
  if (HasInitialRegExpMap(isolate, *recv)) {
    return direct_handle(Cast<JSRegExp>(*recv)->last_index(), isolate);
  } else {
    return Object::GetProperty(isolate, recv,
                               isolate->factory()->lastIndex_string());
  }
}
References v8::internal::direct_handle(), v8::internal::Isolate::factory(), v8::internal::Object::GetProperty(), and v8::internal::anonymous_namespace{regexp-utils.cc}::HasInitialRegExpMap().
Referenced by v8::internal::RUNTIME_FUNCTION().
IsMatchedCapture()
bool v8::internal::RegExpUtils::IsMatchedCapture (Tagged< RegExpMatchInfo > match_info, int capture) [static]
Definition at line 41 of file regexp-utils.cc.
                                                {
  // Sentinel used as failure indicator in other functions.
  if (capture == -1) return false;
  const int capture_start_index = RegExpMatchInfo::capture_start_index(capture);
  if (capture_start_index >= match_info->number_of_capture_registers()) {
    return false;
  }
  const int capture_end_index = RegExpMatchInfo::capture_end_index(capture);
  const int match_start = match_info->capture(capture_start_index);
  const int match_end = match_info->capture(capture_end_index);
  return match_start != -1 && match_end != -1;
}
References v8::internal::RegExpMatchInfo::capture_end_index(), and v8::internal::RegExpMatchInfo::capture_start_index().
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::MatchInfoBackedMatch::GetNamedCapture().
IsUnmodifiedRegExp()
bool v8::internal::RegExpUtils::IsUnmodifiedRegExp (Isolate * isolate, DirectHandle< Object > obj) [static]
Definition at line 139 of file regexp-utils.cc.
                                                               {
#ifdef V8_ENABLE_FORCE_SLOW_PATH
  if (isolate->force_slow_path()) return false;
#endif
  if (!IsJSReceiver(*obj)) return false;
  Tagged<JSReceiver> recv = Cast<JSReceiver>(*obj);
  if (!HasInitialRegExpMap(isolate, recv)) return false;
  // Check the receiver's prototype's map.
  Tagged<Object> proto = recv->map()->prototype();
  if (!IsJSReceiver(proto)) return false;
  DirectHandle<Map> initial_proto_initial_map = isolate->regexp_prototype_map();
  Tagged<Map> proto_map = Cast<JSReceiver>(proto)->map();
  if (proto_map != *initial_proto_initial_map) {
    return false;
  }
  // Check that the "exec" method is unmodified.
  // Check that the index refers to "exec" method (this has to be consistent
  // with the init order in the bootstrapper).
  InternalIndex kExecIndex(JSRegExp::kExecFunctionDescriptorIndex);
  DCHECK_EQ(*(isolate->factory()->exec_string()),
            proto_map->instance_descriptors(isolate)->GetKey(kExecIndex));
  if (proto_map->instance_descriptors(isolate)
          ->GetDetails(kExecIndex)
          .constness() != PropertyConstness::kConst) {
    return false;
  }
  // Note: Unlike the more involved check in CSA (see BranchIfFastRegExp), this
  // does not go on to check the actual value of the exec property. This would
  // not be valid since this method is called from places that access the flags
  // property. Similar spots in CSA would use BranchIfFastRegExp_Strict in this
  // case.
  if (!Protectors::IsRegExpSpeciesLookupChainIntact(isolate)) return false;
  // The smi check is required to omit ToLength(lastIndex) calls with possible
  // user-code execution on the fast path.
  Tagged<Object> last_index = Cast<JSRegExp>(recv)->last_index();
  return IsSmi(last_index) && Smi::ToInt(last_index) >= 0;
}
References DCHECK_EQ, v8::internal::Isolate::factory(), v8::internal::Isolate::force_slow_path(), v8::internal::anonymous_namespace{regexp-utils.cc}::HasInitialRegExpMap(), v8::internal::IsSmi(), v8::internal::kConst, v8::internal::JSRegExp::kExecFunctionDescriptorIndex, and v8::internal::Smi::ToInt().
Referenced by v8::internal::RegExp::IsUnmodifiedRegExp(), v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpReplace(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::anonymous_namespace{runtime-regexp.cc}::SearchRegExpMultiple().
RegExpExec()
MaybeDirectHandle< JSAny > v8::internal::RegExpUtils::RegExpExec (Isolate * isolate, DirectHandle< JSReceiver > regexp, DirectHandle< String > string, DirectHandle< Object > exec) [static]
Definition at line 93 of file regexp-utils.cc.
                                                            {
  if (IsUndefined(*exec, isolate)) {
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, exec,
        Object::GetProperty(isolate, regexp,
                            isolate->factory()->exec_string()));
  }
  if (IsCallable(*exec)) {
    constexpr int argc = 1;
    std::array<DirectHandle<Object>, argc> args = {string};
    DirectHandle<JSAny> result;
    ASSIGN_RETURN_ON_EXCEPTION(
        isolate, result,
        Cast<JSAny>(
            Execution::Call(isolate, exec, regexp, base::VectorOf(args))));
    if (!IsJSReceiver(*result) && !IsNull(*result, isolate)) {
      THROW_NEW_ERROR(isolate,
                      NewTypeError(MessageTemplate::kInvalidRegExpExecResult));
    }
    return result;
  }
  if (!IsJSRegExp(*regexp)) {
    THROW_NEW_ERROR(isolate,
                    NewTypeError(MessageTemplate::kIncompatibleMethodReceiver,
                                 isolate->factory()->NewStringFromAsciiChecked(
                                     "RegExp.prototype.exec"),
                                 regexp));
  }
  {
    DirectHandle<JSFunction> regexp_exec = isolate->regexp_exec_function();
    constexpr int argc = 1;
    std::array<DirectHandle<Object>, argc> args = {string};
    return Cast<JSAny>(
        Execution::Call(isolate, regexp_exec, regexp, base::VectorOf(args)));
  }
}
References v8::base::args, ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Execution::Call(), v8::internal::Isolate::factory(), v8::internal::Object::GetProperty(), v8::internal::IsNull(), v8::internal::FactoryBase< Impl >::NewStringFromAsciiChecked(), v8::base::internal::result, THROW_NEW_ERROR, and v8::base::VectorOf().
Referenced by v8::RegExp::Exec(), and v8::internal::RUNTIME_FUNCTION().
SetAdvancedStringIndex()
MaybeDirectHandle< Object > v8::internal::RegExpUtils::SetAdvancedStringIndex (Isolate * isolate, DirectHandle< JSReceiver > regexp, DirectHandle< String > string, bool unicode) [static]
Definition at line 205 of file regexp-utils.cc.
                                               {
  DirectHandle<Object> last_index_obj;
  ASSIGN_RETURN_ON_EXCEPTION(
      isolate, last_index_obj,
      Object::GetProperty(isolate, regexp,
                          isolate->factory()->lastIndex_string()));
  ASSIGN_RETURN_ON_EXCEPTION(isolate, last_index_obj,
                             Object::ToLength(isolate, last_index_obj));
  const uint64_t last_index = PositiveNumberToUint64(*last_index_obj);
  const uint64_t new_last_index =
      AdvanceStringIndex(*string, last_index, unicode);
  return SetLastIndex(isolate, regexp, new_last_index);
}
References AdvanceStringIndex(), ASSIGN_RETURN_ON_EXCEPTION, v8::internal::Isolate::factory(), v8::internal::Object::GetProperty(), v8::internal::PositiveNumberToUint64(), SetLastIndex(), and v8::internal::Object::ToLength().
Referenced by v8::internal::RUNTIME_FUNCTION().
SetLastIndex()
MaybeDirectHandle< Object > v8::internal::RegExpUtils::SetLastIndex (Isolate * isolate, DirectHandle< JSReceiver > regexp, uint64_t value) [static]
Definition at line 65 of file regexp-utils.cc.
                                                                     {
  DirectHandle<Object> value_as_object =
      isolate->factory()->NewNumberFromInt64(value);
  if (HasInitialRegExpMap(isolate, *recv)) {
    Cast<JSRegExp>(*recv)->set_last_index(*value_as_object,
                                          UPDATE_WRITE_BARRIER);
    return recv;
  } else {
    return Object::SetProperty(
        isolate, recv, isolate->factory()->lastIndex_string(), value_as_object,
        StoreOrigin::kMaybeKeyed, Just(kThrowOnError));
  }
}
References v8::internal::Isolate::factory(), v8::internal::anonymous_namespace{regexp-utils.cc}::HasInitialRegExpMap(), v8::Just(), v8::internal::kMaybeKeyed, v8::internal::kThrowOnError, v8::internal::FactoryBase< Impl >::NewNumberFromInt64(), v8::internal::Object::SetProperty(), v8::internal::UPDATE_WRITE_BARRIER, and v8::internal::value.
Referenced by v8::internal::anonymous_namespace{runtime-regexp.cc}::RegExpReplace(), v8::internal::RUNTIME_FUNCTION(), and SetAdvancedStringIndex().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-utils.h
/mnt/V8SourceCode/src/regexp/regexp-utils.cc