v8::MaybeLocal< T > Class Template Reference
A MaybeLocal<> is a wrapper around Local<> that enforces a check whether the Local<> is empty before it can be used.
#include <v8-local-handle.h>
Public Member Functions
MaybeLocal ()=default
Default constructor: Returns an empty handle.
template<class S >
requires std::is_base_of_v< T, S > MaybeLocal (Local< S > that)
Implicitly construct MaybeLocal from Local.
template<class S >
requires std::is_base_of_v< T, S > MaybeLocal (MaybeLocal< S > that)
Implicitly up-cast MaybeLocal to MaybeLocal<T> if T is a base of S.
bool IsEmpty () const
template<class S >
V8_WARN_UNUSED_RESULT bool ToLocal (Local< S > *out) const
Converts this MaybeLocal<> to a Local<>.
Local< T > ToLocalChecked ()
Converts this MaybeLocal<> to a Local<>.
template<class S >
Local< S > FromMaybe (Local< S > default_value) const
Converts this MaybeLocal<> to a Local<>, using a default value if this MaybeLocal<> is empty.
template<class S >
MaybeLocal< S > As () const
Calling this is equivalent to MaybeLocal<S>::Cast().
Static Public Member Functions
template<class S >
static MaybeLocal< T > Cast (MaybeLocal< S > that)
Cast a handle to a subclass, e.g.
Private Attributes
Local< T > local_
Friends
template<typename S >
class MaybeLocal
Detailed Description
template<class T>
class v8::MaybeLocal< T >
A MaybeLocal<> is a wrapper around Local<> that enforces a check whether the Local<> is empty before it can be used.
If an API method returns a MaybeLocal<>, the API method can potentially fail either because an exception is thrown, or because an exception is pending, e.g. because a previous API call threw an exception that hasn't been caught yet, or because a TerminateExecution exception was thrown. In that case, an empty MaybeLocal is returned.
Definition at line 665 of file v8-local-handle.h.
Constructor & Destructor Documentation
MaybeLocal() [1/3]
template<class T >
v8::MaybeLocal< T >::MaybeLocal () [inline], [default]
Default constructor: Returns an empty handle.
MaybeLocal() [2/3]
template<class T >
template<class S >
requires std::is_base_of_v<T, S> v8::MaybeLocal< T >::MaybeLocal (Local< S > that) [inline]
Implicitly construct MaybeLocal from Local.
Definition at line 676 of file v8-local-handle.h.
: local_(that) {}
MaybeLocal() [3/3]
template<class T >
template<class S >
requires std::is_base_of_v<T, S> v8::MaybeLocal< T >::MaybeLocal (MaybeLocal< S > that) [inline]
Implicitly up-cast MaybeLocal to MaybeLocal<T> if T is a base of S.
Definition at line 682 of file v8-local-handle.h.
: local_(that.local_) {}
Member Function Documentation
As()
template<class T >
template<class S >
MaybeLocal<S> v8::MaybeLocal< T >::As () const [inline]
Calling this is equivalent to MaybeLocal<S>::Cast().
In particular, this is only valid if the handle actually refers to a value of the target type or if the handle is empty.
Definition at line 730 of file v8-local-handle.h.
                                     {
    return MaybeLocal<S>::Cast(*this);
  }
References v8::MaybeLocal< T >::Cast().
Cast()
template<class T >
template<class S >
static MaybeLocal<T> v8::MaybeLocal< T >::Cast (MaybeLocal< S > that) [inline], [static]
Cast a handle to a subclass, e.g.
MaybeLocal<Value> to MaybeLocal<Object>. This is only valid if the handle actually refers to a value of the target type or if the handle is empty.
Definition at line 720 of file v8-local-handle.h.
                                                          {
    return MaybeLocal<T>{Local<T>::Cast(that.local_)};
  }
References v8::Local< T >::Cast(), and v8::MaybeLocal< T >::local_.
Referenced by v8::MaybeLocal< T >::As().
FromMaybe()
template<class T >
template<class S >
Local<S> v8::MaybeLocal< T >::FromMaybe (Local< S > default_value) const [inline]
Converts this MaybeLocal<> to a Local<>, using a default value if this MaybeLocal<> is empty.
Definition at line 710 of file v8-local-handle.h.
                                                             {
    return IsEmpty() ? default_value : Local<S>(local_);
  }
References v8::MaybeLocal< T >::IsEmpty(), and v8::MaybeLocal< T >::local_.
Referenced by v8::Shell::PerformanceMeasureMemory().
IsEmpty()
template<class T >
bool v8::MaybeLocal< T >::IsEmpty () const [inline]
Definition at line 684 of file v8-local-handle.h.
{ return local_.IsEmpty(); }
References v8::MaybeLocal< T >::local_.
Referenced by v8_inspector::InjectedScript::ProtocolPromiseHandler::add(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceJSArrayHelper(), v8_inspector::V8InspectorImpl::associateExceptionData(), v8::CpuProfilingOptions::CpuProfilingOptions(), v8::CreateEnvironment(), v8::Shell::DoHostImportModuleDynamically(), v8::Shell::ExecuteModule(), v8::Shell::FetchModuleTree(), v8::MaybeLocal< T >::FromMaybe(), v8::Object::Get(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetIterableLength(), v8::internal::anonymous_namespace{gc-extension.cc}::ParseExecution(), v8::internal::anonymous_namespace{gc-extension.cc}::ParseFlavor(), v8::internal::anonymous_namespace{gc-extension.cc}::ParseType(), v8::Shell::RealmNavigate(), v8::Object::Set(), v8::MaybeLocal< T >::ToLocal(), and v8::MaybeLocal< T >::ToLocalChecked().
ToLocal()
template<class T >
template<class S >
V8_WARN_UNUSED_RESULT bool v8::MaybeLocal< T >::ToLocal (Local< S > * out) const [inline]
Converts this MaybeLocal<> to a Local<>.
If this MaybeLocal<> is empty, |false| is returned and |out| is assigned with nullptr.
Definition at line 691 of file v8-local-handle.h.
                                                                    {
    *out = local_;
    return !IsEmpty();
  }
References v8::MaybeLocal< T >::IsEmpty(), and v8::MaybeLocal< T >::local_.
Referenced by v8_inspector::V8Console::CommandLineAPIScope::accessorGetterCallback(), v8_inspector::anonymous_namespace{v8-console-message.cc}::V8ValueStringBuilder::append(), v8_inspector::arrayToProtocolValue(), v8_inspector::anonymous_namespace{custom-preview.cc}::bodyCallback(), v8_inspector::InjectedScript::ProtocolPromiseHandler::catchCallback(), v8_inspector::V8Debugger::collectionsEntries(), v8_inspector::V8Console::CommandLineAPIScope::CommandLineAPIScope(), v8::ScriptCompiler::Compile(), v8::ScriptCompiler::CompileModule(), v8::InternalEscapableScope::EscapeMaybe(), v8::internal::SyntheticModule::Evaluate(), v8_inspector::V8InspectorSessionImpl::evaluate(), v8::Worker::ExecuteInThread(), v8::Shell::ExecuteString(), v8::Shell::FetchModuleTree(), v8_inspector::V8SerializationDuplicateTracker::FindKnownSerializedValue(), v8::Shell::FunctionAndArgumentsToString(), v8_inspector::generateCustomPreview(), v8_inspector::V8ConsoleMessage::getAssociatedExceptionData(), v8_inspector::V8InspectorImpl::getAssociatedExceptionDataForProtocol(), v8_inspector::anonymous_namespace{value-mirror.cc}::EntryMirror::getEntries(), v8_inspector::anonymous_namespace{value-mirror.cc}::getErrorProperty(), v8_inspector::ValueMirror::getInternalProperties(), v8_inspector::anonymous_namespace{v8-heap-profiler-agent-impl.cc}::GlobalObjectNameResolver::GetName(), v8_inspector::V8HeapProfilerAgentImpl::getObjectByHeapObjectId(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetOptionalAddressValue(), v8_inspector::ValueMirror::getProperties(), v8::anonymous_namespace{wasm-js.cc}::GetValueType(), v8::Shell::HostImportModuleWithPhaseDynamically(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8_inspector::InspectedContext::InspectedContext(), v8_inspector::V8Debugger::internalProperties(), v8::Shell::LoadJSON(), v8_inspector::V8Console::memoryGetterCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::nativeGetterCallback(), v8_inspector::anonymous_namespace{value-mirror.cc}::nativeSetterCallback(), v8::Array::New(), v8_inspector::objectToProtocolValue(), v8::Shell::PerformanceMeasure(), v8::Worker::ProcessMessage(), v8::Shell::ReadCodeTypeAndArguments(), v8::Shell::ReadLines(), v8::Shell::RealmOwner(), v8_inspector::InjectedScript::resolveCallArgument(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeMap(), v8_inspector::anonymous_namespace{v8-deep-serializer.cc}::SerializeObjectValue(), v8::Shell::SerializerDeserialize(), v8_inspector::anonymous_namespace{custom-preview.cc}::substituteObjectTags(), v8::anonymous_namespace{d8-test.cc}::FastCApiObject::TestWasmMemoryFastCallback(), v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback(), v8_inspector::V8Console::valuesCallback(), v8::internal::wasm::WasmModuleSourceMap::WasmModuleSourceMap(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyExceptionImpl(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyFunction(), v8::anonymous_namespace{wasm-js.cc}::WebAssemblyTagImpl(), v8::Shell::WorkerNew(), v8_inspector::InjectedScript::wrapEvaluateResult(), and v8_inspector::InjectedScript::wrapTable().
ToLocalChecked()
template<class T >
Local<T> v8::MaybeLocal< T >::ToLocalChecked () [inline]
Converts this MaybeLocal<> to a Local<>.
If this MaybeLocal<> is empty, V8 will crash the process.
Definition at line 700 of file v8-local-handle.h.
                                      {
    if (V8_UNLIKELY(IsEmpty())) api_internal::ToLocalEmpty();
    return local_;
  }
References v8::MaybeLocal< T >::IsEmpty(), v8::MaybeLocal< T >::local_, v8::api_internal::ToLocalEmpty(), and V8_UNLIKELY.
Referenced by v8::anonymous_namespace{d8-test.cc}::FastCApiObject::AddAllSequenceJSArrayHelper(), v8_inspector::V8InspectorImpl::associateExceptionData(), v8::CpuProfilingOptions::CpuProfilingOptions(), v8::CreateEnvironment(), v8::Shell::CreateEvaluationContext(), v8::CreateFastCAPIObject(), v8::Shell::DoHostImportModuleDynamically(), v8::Shell::ExecuteModule(), v8::Shell::FetchModuleTree(), v8::tracing::anonymous_namespace{d8.cc}::TraceConfigParser::FillTraceConfig(), v8::Object::Get(), v8::anonymous_namespace{wasm-js.cc}::anonymous_namespace{wasm-js.cc}::GetIterableLength(), v8::anonymous_namespace{d8.cc}::GetValue(), v8::internal::anonymous_namespace{gc-extension.cc}::ParseExecution(), v8::internal::anonymous_namespace{gc-extension.cc}::ParseFlavor(), v8::internal::anonymous_namespace{gc-extension.cc}::ParseType(), v8::Shell::RealmNavigate(), v8::InspectorClient::runMessageLoopOnPause(), v8_inspector::V8RuntimeAgentImpl::runScript(), v8::InspectorFrontend::Send(), and v8::Object::Set().
Friends And Related Function Documentation
MaybeLocal
template<class T >
template<typename S >
friend class MaybeLocal [friend]
Definition at line 738 of file v8-local-handle.h.
Member Data Documentation
local_
template<class T >
Local<T> v8::MaybeLocal< T >::local_ [private]
Definition at line 735 of file v8-local-handle.h.
Referenced by v8::MaybeLocal< T >::Cast(), v8::MaybeLocal< T >::FromMaybe(), v8::MaybeLocal< T >::IsEmpty(), v8::MaybeLocal< T >::ToLocal(), and v8::MaybeLocal< T >::ToLocalChecked().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/v8-local-handle.h