v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::OutOfLineRecordWrite Class Reference
Public Member Functions
OutOfLineRecordWrite (CodeGenerator *gen, Register object, Operand operand, Register value, Register scratch0, Register scratch1, RecordWriteMode mode, StubCallMode stub_mode, IndirectPointerTag indirect_pointer_tag=kIndirectPointerNullTag)
void Generate () final
Private Attributes
Register const object_
Operand const operand_
Register const value_
Register const scratch0_
Register const scratch1_
RecordWriteMode const mode_
Zone * zone_
IndirectPointerTag indirect_pointer_tag_
Detailed Description
Definition at line 370 of file code-generator-x64.cc.
Constructor & Destructor Documentation
OutOfLineRecordWrite()
v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::OutOfLineRecordWrite::OutOfLineRecordWrite (CodeGenerator * gen, Register object, Operand operand, Register value, Register scratch0, Register scratch1, RecordWriteMode mode, StubCallMode stub_mode, IndirectPointerTag indirect_pointer_tag = kIndirectPointerNullTag) [inline]
Definition at line 372 of file code-generator-x64.cc.
      : OutOfLineCode(gen),
        object_(object),
        operand_(operand),
        value_(value),
        scratch0_(scratch0),
        scratch1_(scratch1),
        mode_(mode),
#if V8_ENABLE_WEBASSEMBLY
        stub_mode_(stub_mode),
#endif // V8_ENABLE_WEBASSEMBLY
        zone_(gen->zone()),
        indirect_pointer_tag_(indirect_pointer_tag) {
    DCHECK(!AreAliased(object, scratch0, scratch1));
    DCHECK(!AreAliased(value, scratch0, scratch1));
  }
References v8::internal::AreAliased(), v8::internal::DCHECK(), and v8::internal::value.
Member Function Documentation
Generate()
void v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::OutOfLineRecordWrite::Generate () [inline], [final], [virtual]
Implements v8::internal::compiler::OutOfLineCode.
Definition at line 397 of file code-generator-x64.cc.
                        {
    // When storing an indirect pointer, the value will always be a
    // full/decompressed pointer.
    if (COMPRESS_POINTERS_BOOL &&
        mode_ != RecordWriteMode::kValueIsIndirectPointer) {
      __ DecompressTagged(value_, value_);
    }
    // No need to check value page flags with the indirect pointer write barrier
    // because the value is always an ExposedTrustedObject.
    if (mode_ != RecordWriteMode::kValueIsIndirectPointer) {
#if V8_ENABLE_STICKY_MARK_BITS_BOOL
      // TODO(333906585): Optimize this path.
      Label stub_call_with_decompressed_value;
      __ CheckPageFlag(value_, scratch0_, MemoryChunk::kIsInReadOnlyHeapMask,
                       not_zero, exit());
      __ CheckMarkBit(value_, scratch0_, scratch1_, carry, exit());
      __ jmp(&stub_call_with_decompressed_value);
      __ bind(&stub_call_);
      if (COMPRESS_POINTERS_BOOL &&
          mode_ != RecordWriteMode::kValueIsIndirectPointer) {
        __ DecompressTagged(value_, value_);
      }
      __ bind(&stub_call_with_decompressed_value);
#else // !V8_ENABLE_STICKY_MARK_BITS_BOOL
      __ CheckPageFlag(value_, scratch0_,
                       MemoryChunk::kPointersToHereAreInterestingMask, zero,
                       exit());
#endif // !V8_ENABLE_STICKY_MARK_BITS_BOOL
    }
    __ leaq(scratch1_, operand_);
    SaveFPRegsMode const save_fp_mode = frame()->DidAllocateDoubleRegisters()
                                            ? SaveFPRegsMode::kSave
                                            : SaveFPRegsMode::kIgnore;
    if (mode_ == RecordWriteMode::kValueIsEphemeronKey) {
      __ CallEphemeronKeyBarrier(object_, scratch1_, save_fp_mode);
    } else if (mode_ == RecordWriteMode::kValueIsIndirectPointer) {
      // We must have a valid indirect pointer tag here. Otherwise, we risk not
      // invoking the correct write barrier, which may lead to subtle issues.
      CHECK(IsValidIndirectPointerTag(indirect_pointer_tag_));
      __ CallIndirectPointerBarrier(object_, scratch1_, save_fp_mode,
                                    indirect_pointer_tag_);
#if V8_ENABLE_WEBASSEMBLY
    } else if (stub_mode_ == StubCallMode::kCallWasmRuntimeStub) {
      // A direct call to a wasm runtime stub defined in this module.
      // Just encode the stub index. This will be patched when the code
      // is added to the native module and copied into wasm code space.
      __ CallRecordWriteStubSaveRegisters(object_, scratch1_, save_fp_mode,
                                          StubCallMode::kCallWasmRuntimeStub);
#endif // V8_ENABLE_WEBASSEMBLY
    } else {
      __ CallRecordWriteStubSaveRegisters(object_, scratch1_, save_fp_mode);
    }
  }
References __, v8::internal::carry, CHECK, COMPRESS_POINTERS_BOOL, v8::internal::IsValidIndirectPointerTag(), v8::internal::kIgnore, v8::internal::MemoryChunk::kIsInReadOnlyHeapMask, v8::internal::MemoryChunk::kPointersToHereAreInterestingMask, v8::internal::kSave, v8::internal::compiler::kValueIsEphemeronKey, v8::internal::compiler::kValueIsIndirectPointer, v8::internal::not_zero, and v8::internal::zero.
Member Data Documentation
indirect_pointer_tag_
IndirectPointerTag v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::OutOfLineRecordWrite::indirect_pointer_tag_ [private]
Definition at line 468 of file code-generator-x64.cc.
mode_
RecordWriteMode const v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::OutOfLineRecordWrite::mode_ [private]
Definition at line 463 of file code-generator-x64.cc.
object_
Register const v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::OutOfLineRecordWrite::object_ [private]
Definition at line 458 of file code-generator-x64.cc.
operand_
Operand const v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::OutOfLineRecordWrite::operand_ [private]
Definition at line 459 of file code-generator-x64.cc.
scratch0_
Register const v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::OutOfLineRecordWrite::scratch0_ [private]
Definition at line 461 of file code-generator-x64.cc.
scratch1_
Register const v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::OutOfLineRecordWrite::scratch1_ [private]
Definition at line 462 of file code-generator-x64.cc.
value_
Register const v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::OutOfLineRecordWrite::value_ [private]
Definition at line 460 of file code-generator-x64.cc.
zone_
Zone* v8::internal::compiler::anonymous_namespace{code-generator-x64.cc}::OutOfLineRecordWrite::zone_ [private]
Definition at line 467 of file code-generator-x64.cc.
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/x64/code-generator-x64.cc