cppgc::MakeGarbageCollectedTraitBase< T > Class Template Reference
Base trait that provides utilities for advancers users that have custom allocation needs (e.g., overriding size).
#include <allocation.h>
Static Protected Member Functions
static void * Allocate (AllocationHandle &handle, size_t size)
Allocates memory for an object of type T.
static void MarkObjectAsFullyConstructed (const void *payload)
Marks an object as fully constructed, resulting in precise handling by the garbage collector.
Additional Inherited Members
Detailed Description
template<typename T>
class cppgc::MakeGarbageCollectedTraitBase< T >
Base trait that provides utilities for advancers users that have custom allocation needs (e.g., overriding size).
It's expected that users override MakeGarbageCollectedTrait (see below) and inherit from MakeGarbageCollectedTraitBase and make use of the low-level primitives offered to allocate and construct an object.
Definition at line 146 of file allocation.h.
Member Function Documentation
Allocate()
template<typename T >
static void* cppgc::MakeGarbageCollectedTraitBase< T >::Allocate (AllocationHandle & handle, size_t size) [inline], [static], [protected]
Allocates memory for an object of type T.
Parameters
handle AllocationHandle identifying the heap to allocate the object on.
size The size that should be reserved for the object.
Returns
the memory to construct an object of type T on.
Definition at line 165 of file allocation.h.
                                                                         {
    static_assert(
        std::is_base_of_v<typename T::ParentMostGarbageCollectedType, T>,
        "U of GarbageCollected<U> must be a base of T. Check "
        "GarbageCollected<T> base class inheritance.");
    static constexpr size_t kWantedAlignment =
        alignof(T) < internal::api_constants::kDefaultAlignment
            ? internal::api_constants::kDefaultAlignment
            : alignof(T);
    static_assert(
        kWantedAlignment <= internal::api_constants::kMaxSupportedAlignment,
        "Requested alignment larger than alignof(std::max_align_t) bytes. "
        "Please file a bug to possibly get this restriction lifted.");
    return AllocationDispatcher<
        typename internal::GCInfoFolding<
            T, typename T::ParentMostGarbageCollectedType>::ResultType,
        typename SpaceTrait<T>::Space, kWantedAlignment>::Invoke(handle, size);
  }
References v8::internal::handle(), v8::internal::anonymous_namespace{execution.cc}::Invoke(), cppgc::internal::api_constants::kDefaultAlignment, cppgc::internal::api_constants::kMaxSupportedAlignment, size(), and T.
Referenced by cppgc::MakeGarbageCollectedTrait< T >::Call().
MarkObjectAsFullyConstructed()
template<typename T >
static void cppgc::MakeGarbageCollectedTraitBase< T >::MarkObjectAsFullyConstructed (const void * payload) [inline], [static], [protected]
Marks an object as fully constructed, resulting in precise handling by the garbage collector.
Parameters
payload The base pointer the object is allocated at.
Definition at line 190 of file allocation.h.
                                                                          {
    internal::MakeGarbageCollectedTraitInternal::MarkObjectAsFullyConstructed(
        payload);
  }
References cppgc::internal::MakeGarbageCollectedTraitInternal::MarkObjectAsFullyConstructed().
Referenced by cppgc::MakeGarbageCollectedTrait< T >::Call().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/include/cppgc/allocation.h