v8::internal::Position Class Reference
Public Member Functions
Position (ProfileNode *node)
ProfileNode * current_child ()
bool has_current_child ()
void next_child ()
Public Attributes
ProfileNode * node
Private Attributes
int child_idx_
Detailed Description
Definition at line 524 of file profile-generator.cc.
Constructor & Destructor Documentation
Position()
v8::internal::Position::Position (ProfileNode * node) [inline], [explicit]
Definition at line 526 of file profile-generator.cc.
      : node(node), child_idx_(0) { }
Member Function Documentation
current_child()
ProfileNode* v8::internal::Position::current_child () [inline]
Definition at line 528 of file profile-generator.cc.
                                         {
    return node->children()->at(child_idx_);
  }
References child_idx_, v8::internal::ProfileNode::children(), and node.
Referenced by v8::internal::ProfileTree::TraverseDepthFirst().
has_current_child()
bool v8::internal::Position::has_current_child () [inline]
Definition at line 531 of file profile-generator.cc.
                                     {
    return child_idx_ < static_cast<int>(node->children()->size());
  }
References v8::internal::ProfileNode::children(), and node.
Referenced by v8::internal::ProfileTree::TraverseDepthFirst().
next_child()
void v8::internal::Position::next_child () [inline]
Definition at line 534 of file profile-generator.cc.
{ ++child_idx_; }
References child_idx_.
Referenced by v8::internal::ProfileTree::TraverseDepthFirst().
Member Data Documentation
child_idx_
int v8::internal::Position::child_idx_ [private]
Definition at line 538 of file profile-generator.cc.
Referenced by current_child(), and next_child().
node
ProfileNode* v8::internal::Position::node
Definition at line 536 of file profile-generator.cc.
Referenced by current_child(), has_current_child(), and v8::internal::ProfileTree::TraverseDepthFirst().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/profiler/profile-generator.cc