v8::internal::wasm::ValueTypeBase Class Reference
#include <value-type.h>
Public Member Functions
constexpr ValueTypeBase ()
void Populate (bool shared, RefTypeKind kind)
constexpr TypeKind type_kind () const
constexpr bool has_index () const
constexpr bool is_sentinel () const
constexpr bool is_numeric () const
constexpr bool is_abstract_ref () const
constexpr bool is_ref () const
constexpr bool is_generic () const
constexpr Nullability nullability () const
constexpr bool is_nullable () const
constexpr bool is_non_nullable () const
constexpr Exactness exactness () const
constexpr bool is_exact () const
constexpr bool is_shared () const
constexpr RefTypeKind ref_type_kind () const
constexpr StandardType standard_type () const
constexpr NumericKind numeric_kind () const
constexpr GenericKind generic_kind () const
constexpr bool is_bottom () const
constexpr bool is_top () const
constexpr bool is_void () const
constexpr bool is_string_view () const
constexpr bool is_packed () const
constexpr bool is_reference_to (GenericKind type) const
constexpr bool is_defaultable () const
constexpr bool is_uninhabited () const
constexpr bool use_wasm_null () const
constexpr int value_kind_size_log2 () const
constexpr int value_kind_size () const
constexpr int value_kind_full_size () const
constexpr MachineType machine_type () const
constexpr MachineRepresentation machine_representation () const
ValueTypeCode value_type_code () const
constexpr bool encoding_needs_heap_type () const
constexpr bool encoding_needs_shared () const
constexpr bool encoding_needs_exact () const
V8_EXPORT_PRIVATE ValueTypeCode value_type_code_numeric () const
V8_EXPORT_PRIVATE ValueTypeCode value_type_code_generic () const
constexpr char short_name () const
V8_EXPORT_PRIVATE std::string generic_heaptype_name () const
V8_EXPORT_PRIVATE std::string name () const
constexpr bool is_valid () const
constexpr uint32_t raw_bit_field () const
size_t hash_value () const
constexpr bool is_reference () const
constexpr bool is_object_reference () const
constexpr ValueKind kind () const
constexpr uint32_t raw_heap_representation (bool distinguish_shared) const
Static Public Member Functions
static constexpr ValueTypeBase Primitive (ValueKind kind)
Static Public Attributes
static const int kNumIndexBits = value_type_impl::PayloadField::kSize
static const int kLastUsedBit = value_type_impl::PayloadField::kLastUsedBit
static const uint32_t kIsRefBit = value_type_impl::IsRefField::kMask
static const uint32_t kIsNullableBit
static const uint32_t kIsSharedBit = value_type_impl::IsSharedField::kMask
static const uint32_t kHasIndexBit
static const uint32_t kRefKindBits = value_type_impl::RefTypeKindField::kMask
static const uint32_t kRefKindShift
static const uint32_t kIndexBits = value_type_impl::PayloadField::kMask
static const uint32_t kIndexShift = value_type_impl::PayloadField::kShift
Protected Member Functions
constexpr ValueTypeBase (uint32_t bit_field)
constexpr ValueTypeBase (NumericKind kind)
constexpr ValueTypeBase (GenericKind kind, Nullability nullable, bool is_shared)
constexpr ValueTypeBase (TypeIndex index, Nullability nullable, Exactness exact, bool shared, RefTypeKind ref_type_kind)
constexpr TypeIndex raw_index () const
Protected Attributes
uint32_t bit_field_
Friends
class CanonicalValueType
class HeapType
class IndependentValueType
class ValueType
Detailed Description
Definition at line 337 of file value-type.h.
Constructor & Destructor Documentation
ValueTypeBase() [1/5]
constexpr v8::internal::wasm::ValueTypeBase::ValueTypeBase () [inline], [constexpr]
Definition at line 353 of file value-type.h.
      : ValueTypeBase(GenericKind::kVoid, kNonNullable, false) {}
Referenced by v8::internal::wasm::HeapType::AsExact(), v8::internal::wasm::ValueType::AsExact(), v8::internal::wasm::CanonicalValueType::AsExact(), v8::internal::wasm::ValueType::AsNonShared(), v8::internal::wasm::ValueType::AsNullable(), v8::internal::wasm::ValueType::Canonicalize(), v8::internal::wasm::HeapType::FromBits(), v8::internal::wasm::ValueType::FromRawBitField(), v8::internal::wasm::CanonicalValueType::FromRawBitField(), v8::internal::wasm::HeapType::Generic(), v8::internal::wasm::ValueType::Generic(), v8::internal::wasm::HeapType::Index(), v8::internal::wasm::ValueType::Primitive(), v8::internal::wasm::CanonicalValueType::Primitive(), Primitive(), v8::internal::wasm::CanonicalValueType::Ref(), v8::internal::wasm::ValueType::Ref(), v8::internal::wasm::CanonicalValueType::RefMaybeNull(), v8::internal::wasm::ValueType::RefMaybeNull(), v8::internal::wasm::CanonicalValueType::RefNull(), and v8::internal::wasm::ValueType::RefNull().
ValueTypeBase() [2/5]
constexpr v8::internal::wasm::ValueTypeBase::ValueTypeBase (uint32_t bit_field) [inline], [explicit], [constexpr], [protected]
Definition at line 673 of file value-type.h.
                                                       : bit_field_(bit_field) {
    DCHECK(is_valid());
  }
References v8::internal::DCHECK(), and is_valid().
ValueTypeBase() [3/5]
constexpr v8::internal::wasm::ValueTypeBase::ValueTypeBase (NumericKind kind) [inline], [explicit], [constexpr], [protected]
Definition at line 677 of file value-type.h.
      : bit_field_(static_cast<uint32_t>(kind)) {
    DCHECK(is_numeric());
  }
References v8::internal::DCHECK(), and is_numeric().
ValueTypeBase() [4/5]
constexpr v8::internal::wasm::ValueTypeBase::ValueTypeBase (GenericKind kind, Nullability nullable, bool is_shared) [inline], [explicit], [constexpr], [protected]
Definition at line 682 of file value-type.h.
      : bit_field_(static_cast<uint32_t>(kind) |
                   value_type_impl::IsNullableField::encode(nullable) |
                   value_type_impl::IsSharedField::encode(is_shared)) {
    DCHECK(is_generic());
  }
References v8::internal::DCHECK(), and is_generic().
ValueTypeBase() [5/5]
constexpr v8::internal::wasm::ValueTypeBase::ValueTypeBase (TypeIndex index, Nullability nullable, Exactness exact, bool shared, RefTypeKind ref_type_kind) [inline], [explicit], [constexpr], [protected]
Definition at line 690 of file value-type.h.
      : bit_field_(
            value_type_impl::TypeKindField::encode(TypeKind::kIndexedRef) |
            value_type_impl::IsNullableField::encode(nullable) |
            value_type_impl::IsExactField::encode(exact) |
            value_type_impl::IsSharedField::encode(shared) |
            value_type_impl::RefTypeKindField::encode(ref_type_kind) |
            value_type_impl::PayloadField::encode(index.index)) {
    // We shouldn't need this, but experience has shown that having an extra
    // "safety net" here is valuable every now and then.
    CHECK(value_type_impl::PayloadField::is_valid(index.index));
  }
References CHECK, v8::internal::index, v8::base::BitField< T, shift, size, U >::is_valid(), and v8::internal::wasm::kIndexedRef.
Member Function Documentation
encoding_needs_exact()
constexpr bool v8::internal::wasm::ValueTypeBase::encoding_needs_exact () const [inline], [constexpr]
Definition at line 549 of file value-type.h.
{ return is_exact(); }
References is_exact().
Referenced by v8::internal::wasm::LocalDeclEncoder::Emit(), and v8::internal::wasm::anonymous_namespace{wasm-module-builder.cc}::WriteInitializerExpressionWithoutEnd().
encoding_needs_heap_type()
constexpr bool v8::internal::wasm::ValueTypeBase::encoding_needs_heap_type () const [inline], [constexpr]
Definition at line 539 of file value-type.h.
                                                  {
    if (has_index()) return true;
    if (!is_abstract_ref()) return false;
    return !is_nullable() || is_shared();
  }
References has_index(), is_abstract_ref(), is_nullable(), and is_shared().
Referenced by v8::internal::wasm::LocalDeclEncoder::Emit(), and value_type_code().
encoding_needs_shared()
constexpr bool v8::internal::wasm::ValueTypeBase::encoding_needs_shared () const [inline], [constexpr]
Definition at line 545 of file value-type.h.
                                               {
    return is_abstract_ref() && is_shared();
  }
References is_abstract_ref(), and is_shared().
Referenced by v8::internal::wasm::LocalDeclEncoder::Emit().
exactness()
constexpr Exactness v8::internal::wasm::ValueTypeBase::exactness () const [inline], [constexpr]
Definition at line 400 of file value-type.h.
                                        {
    return value_type_impl::IsExactField::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), is_exact(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast(), and v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck().
generic_heaptype_name()
std::string v8::internal::wasm::ValueTypeBase::generic_heaptype_name () const
Definition at line 71 of file value-type.cc.
                                                     {
  DCHECK(is_generic());
  std::ostringstream buf;
  if (is_shared()) buf << "shared ";
  switch (generic_kind()) {
#define GENERIC_CASE(kind, code, typekind, name) \
  case GenericKind::k##kind: \
    buf << name; \
    return buf.str();
    FOREACH_GENERIC_TYPE(GENERIC_CASE)
#undef GENERIC_CASE
  }
  UNREACHABLE();
}
References v8::internal::DCHECK(), FOREACH_GENERIC_TYPE, GENERIC_CASE, generic_kind(), is_generic(), is_shared(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::HeapType::name().
generic_kind()
constexpr GenericKind v8::internal::wasm::ValueTypeBase::generic_kind () const [inline], [constexpr]
Definition at line 421 of file value-type.h.
                                             {
    DCHECK(is_generic());
    return static_cast<GenericKind>(bit_field_ &
                                    value_type_impl::kGenericKindMask);
  }
References bit_field_, v8::internal::DCHECK(), is_generic(), and v8::internal::wasm::value_type_impl::kGenericKindMask.
Referenced by v8::internal::wasm::IndependentHeapType::AsNonNull(), generic_heaptype_name(), v8::internal::WasmTableObject::Get(), is_reference_to(), is_uninhabited(), name(), raw_heap_representation(), v8::internal::WasmTableObject::Set(), use_wasm_null(), and value_type_code_generic().
has_index()
constexpr bool v8::internal::wasm::ValueTypeBase::has_index () const [inline], [constexpr]
Definition at line 368 of file value-type.h.
                                   {
    return type_kind() == TypeKind::kIndexedRef;
  }
References v8::internal::wasm::kIndexedRef, and type_kind().
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_elem(), v8::internal::wasm::HeapType::AsExact(), v8::internal::wasm::ValueType::AsExact(), v8::internal::wasm::CanonicalValueType::AsExact(), v8::internal::wasm::ValueType::AsExactIfIndexed(), v8::internal::WasmTableObject::canonical_type(), v8::internal::wasm::WasmModule::canonical_type(), v8::internal::wasm::ValueType::Canonicalize(), v8::internal::wasm::HeapType::code(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestor(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), encoding_needs_heap_type(), v8::internal::wasm::TypeCanonicalizer::CanonicalEquality::EqualValueType(), v8::internal::wasm::EquivalentTypes(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateRefTypeElementSegment(), v8::internal::WasmTableObject::Get(), v8::internal::wasm::HeapType::is_index(), is_uninhabited(), is_valid(), v8::internal::wasm::JSPrototypesSetup::IsDescriptorGlobal(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::IsSubtypeOf_CommonImpl(), v8::internal::wasm::IsSubtypeOfImpl(), v8::internal::wasm::JSToWasmObject(), name(), v8::internal::wasm::HeapType::name(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::internal::wasm::value_type_reader::Populate(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessAllocateStruct(), v8::internal::wasm::InstanceBuilder::ProcessImportedWasmGlobalObject(), raw_heap_representation(), raw_index(), v8::internal::WasmTableObject::Set(), standard_type(), use_wasm_null(), and value_type_code().
hash_value()
size_t v8::internal::wasm::ValueTypeBase::hash_value () const [inline]
Definition at line 602 of file value-type.h.
{ return bit_field_; }
References bit_field_.
is_abstract_ref()
constexpr bool v8::internal::wasm::ValueTypeBase::is_abstract_ref () const [inline], [constexpr]
Definition at line 377 of file value-type.h.
                                         {
    return type_kind() == TypeKind::kAbstractRef;
  }
References v8::internal::wasm::kAbstractRef, and type_kind().
Referenced by v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestorWithAbstract(), encoding_needs_heap_type(), encoding_needs_shared(), is_reference_to(), and v8::internal::wasm::Union().
is_bottom()
constexpr bool v8::internal::wasm::ValueTypeBase::is_bottom () const [inline], [constexpr]
Definition at line 427 of file value-type.h.
                                   {
    uint32_t bits = bit_field_ & value_type_impl::kGenericKindMask;
    return bits == static_cast<uint32_t>(GenericKind::kBottom);
  }
References bit_field_, and v8::internal::wasm::value_type_impl::kGenericKindMask.
Referenced by v8::internal::wasm::WasmInstruction::Optional::Block::is_bottom(), is_uninhabited(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::IsSubtypeOf_CommonImpl(), v8::internal::wasm::IsSubtypeOfImpl(), kind(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), and short_name().
is_defaultable()
constexpr bool v8::internal::wasm::ValueTypeBase::is_defaultable () const [inline], [constexpr]
Definition at line 453 of file value-type.h.
                                        {
    return is_numeric() || is_nullable();
  }
References is_nullable(), and is_numeric().
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::InitializeInitializedLocalsTracking(), is_uninhabited(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object().
is_exact()
constexpr bool v8::internal::wasm::ValueTypeBase::is_exact () const [inline], [constexpr]
Definition at line 403 of file value-type.h.
{ return exactness() == Exactness::kExact; }
References exactness(), and v8::internal::wasm::kExact.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add(), encoding_needs_exact(), v8::internal::wasm::EquivalentTypes(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetExactness(), is_valid(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::IsSubtypeOf_CommonImpl(), v8::internal::wasm::IsSubtypeOfImpl(), name(), v8::internal::wasm::HeapType::name(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck(), and v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::UnionExactness().
is_generic()
constexpr bool v8::internal::wasm::ValueTypeBase::is_generic () const [inline], [constexpr]
Definition at line 385 of file value-type.h.
                                    {
    TypeKind kind = type_kind();
    return kind == TypeKind::kAbstractRef || kind == TypeKind::kSentinel;
  }
References v8::internal::wasm::kAbstractRef, kind(), v8::internal::wasm::kSentinel, and type_kind().
Referenced by generic_heaptype_name(), generic_kind(), name(), and ValueTypeBase().
is_non_nullable()
constexpr bool v8::internal::wasm::ValueTypeBase::is_non_nullable () const [inline], [constexpr]
Definition at line 397 of file value-type.h.
                                         {
    return is_ref() && !static_cast<bool>(nullability());
  }
References is_ref(), and nullability().
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_elem(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessBranchOnTarget(), v8::internal::compiler::WasmGCOperatorReducer::ReduceAssertNotNull(), v8::internal::compiler::WasmGCOperatorReducer::ReduceCheckNull(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmArrayLength(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmStructOperation(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::shift_locals().
is_nullable()
constexpr bool v8::internal::wasm::ValueTypeBase::is_nullable () const [inline], [constexpr]
Definition at line 394 of file value-type.h.
                                     {
    return is_ref() && static_cast<bool>(nullability());
  }
References is_ref(), and nullability().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AbstractTypeCast(), v8::internal::wasm::AbstractTypeCast(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::AbstractTypeCheck(), v8::internal::wasm::TypeCanonicalizer::CanonicalHashing::Add(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicSet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayCopy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayFill(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayLen(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayLen(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArraySet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BoundsCheckArray(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_cast(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnAbstractType(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastFailImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnCastImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnNonAbstractType(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::CallIndirectImpl(), v8::internal::wasm::WasmInterpreterRuntime::CheckIndirectCallSignature(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), encoding_needs_heap_type(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::get_local_ref(), v8::internal::wasm::TurboshaftGraphBuildingInterface::GetRttFromDescriptor(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::Initialize(), v8::internal::wasm::Intersection(), is_defaultable(), v8::internal::wasm::IsSubtypeOfImpl(), kind(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadInstanceType(), name(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::null_checks_for_struct_op(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseArrayGet(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseArrayLen(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseArraySet(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseRefCast(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseStructGet(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseStructSet(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCastRtt(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCLowering::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::ReduceWasmTypeCheckRtt(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefAsNonNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefCastImpl(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefTest(), short_name(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StringEq(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringEqImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StringNewWtf8ArrayImpl(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructAtomicCompareExchange(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructAtomicGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructAtomicRMW(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructAtomicSet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck(), v8::internal::wasm::WasmInterpreterRuntime::SubtypeCheck(), v8::internal::wasm::WasmBytecodeGenerator::TypeCheckAlwaysFails(), v8::internal::wasm::Union(), and value_type_code().
is_numeric()
constexpr bool v8::internal::wasm::ValueTypeBase::is_numeric () const [inline], [constexpr]
Definition at line 374 of file value-type.h.
                                    {
    return type_kind() == TypeKind::kNumeric;
  }
References v8::internal::wasm::kNumeric, and type_kind().
Referenced by v8::internal::wasm::ValueType::AsNullable(), v8::internal::wasm::WasmValue::CopyTo(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::ValueType::heap_type(), is_defaultable(), is_valid(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::IsSubtypeOf_CommonImpl(), v8::internal::wasm::IsSubtypeOfImpl(), kind(), name(), numeric_kind(), raw_heap_representation(), v8::internal::RUNTIME_FUNCTION(), value_type_code(), ValueTypeBase(), v8::internal::wasm::WasmValue::WasmValue(), and v8::internal::wasm::InstanceBuilder::WriteGlobalValue().
is_object_reference()
constexpr bool v8::internal::wasm::ValueTypeBase::is_object_reference () const [inline], [constexpr]
Definition at line 607 of file value-type.h.
{ return is_ref(); }
References is_ref().
Referenced by v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::GenerateRefTypeElementSegment(), v8::internal::wasm::JSToWasmObject(), v8::internal::WasmTableObject::New(), and v8::internal::wasm::WasmBytecodeGenerator::RefPop().
is_packed()
constexpr bool v8::internal::wasm::ValueTypeBase::is_packed () const [inline], [constexpr]
Definition at line 445 of file value-type.h.
                                   {
    return bit_field_ == static_cast<uint32_t>(NumericKind::kI8) ||
           bit_field_ == static_cast<uint32_t>(NumericKind::kI16) ||
           bit_field_ == static_cast<uint32_t>(NumericKind::kF16);
  }
References bit_field_.
Referenced by v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_get_helper(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), and v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::struct_get_helper().
is_ref()
constexpr bool v8::internal::wasm::ValueTypeBase::is_ref () const [inline], [constexpr]
Definition at line 381 of file value-type.h.
                                {
    return value_type_impl::IsRefField::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::wasm::ValueType::AsNonShared(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::AsNullable(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::Intersection(), is_non_nullable(), is_nullable(), is_object_reference(), is_reference(), v8::internal::wasm::ValueType::is_reference_to(), v8::internal::wasm::CanonicalValueType::is_reference_to(), machine_type(), nullability(), short_name(), v8::internal::wasm::Union(), use_wasm_null(), value_kind_full_size(), value_kind_size(), value_kind_size_log2(), and value_type_code().
is_reference()
constexpr bool v8::internal::wasm::ValueTypeBase::is_reference () const [inline], [constexpr]
Definition at line 606 of file value-type.h.
{ return is_ref(); }
References is_ref().
Referenced by v8::internal::wasm::array_copy_wrapper(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_data(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::array_init_elem(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicCompareExchange(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicRMW(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayInitSegment(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayInitSegment(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNewSegment(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayNewSegment(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::br_on_cast(), v8::internal::wasm::ModuleDecoderImpl::CalculateGlobalOffsets(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::Decode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::WasmBytecodeGenerator::FindSharedSlot(), v8::internal::WasmTrustedInstanceData::GetGlobalBufferAndIndex(), v8::internal::wasm::WasmInterpreterRuntime::GetGlobalRef(), v8::internal::WasmTrustedInstanceData::GetGlobalStorage(), v8::internal::WasmTrustedInstanceData::GetGlobalValue(), v8::internal::wasm::WasmInterpreterRuntime::InitGlobalAddressCache(), v8::internal::wasm::InstanceBuilder::InitGlobals(), v8::internal::wasm::WasmInterpreterRuntime::InitializeRefLocalsRefs(), v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::IsSupportedWasmFastApiFunction(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::LowerGlobalSetOrGet(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::new_object(), v8::internal::wasm::WasmValue::operator==(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseExternConvertAny(), v8::internal::wasm::InstanceBuilder::ProcessExports(), v8::internal::wasm::InstanceBuilder::ProcessImportedGlobal(), v8::internal::wasm::InstanceBuilder::ProcessImportedWasmGlobalObject(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::WasmInterpreterRuntime::SetGlobalRef(), v8::internal::wasm::WasmValue::to_ref(), v8::internal::wasm::WasmValue::WasmValue(), and v8::internal::wasm::InstanceBuilder::WriteGlobalValue().
is_reference_to()
constexpr bool v8::internal::wasm::ValueTypeBase::is_reference_to (GenericKind type) const [inline], [constexpr]
Definition at line 450 of file value-type.h.
                                                         {
    return is_abstract_ref() && generic_kind() == type;
  }
References generic_kind(), is_abstract_ref(), and v8::internal::tracing::type.
Referenced by v8::internal::wasm::StructTypeBase::first_field_can_be_prototype(), and v8::internal::wasm::ValueType::is_reference_to().
is_sentinel()
constexpr bool v8::internal::wasm::ValueTypeBase::is_sentinel () const [inline], [constexpr]
Definition at line 371 of file value-type.h.
                                     {
    return type_kind() == TypeKind::kSentinel;
  }
References v8::internal::wasm::kSentinel, and type_kind().
Referenced by machine_type(), name(), short_name(), value_kind_size(), and value_kind_size_log2().
is_shared()
constexpr bool v8::internal::wasm::ValueTypeBase::is_shared () const [inline], [constexpr]
Definition at line 404 of file value-type.h.
                                   {
    return value_type_impl::IsSharedField::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicRMW(), v8::internal::wasm::IndependentHeapType::AsNonNull(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCast(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BrOnCastFail(), v8::internal::wasm::anonymous_namespace{wasm-objects.cc}::CheckExpectedSharedness(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestor(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestorWithAbstract(), v8::internal::wasm::anonymous_namespace{wasm-objects.cc}::ConvertToSharedIfExpected(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection(), encoding_needs_heap_type(), encoding_needs_shared(), v8::internal::wasm::HeapType::from_code(), v8::internal::wasm::WasmModule::function_is_shared(), generic_heaptype_name(), v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::IsSubtypeOf_CommonImpl(), v8::internal::wasm::JSToWasmObject(), name(), raw_heap_representation(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefCast(), v8::internal::wasm::TurboshaftGraphBuildingInterface::RefTest(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::RejectSharedWasmObjectsIfUnshared(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::TrapOnSharedWasmObjectsIfUnshared(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::UnOpImpl().
is_string_view()
constexpr bool v8::internal::wasm::ValueTypeBase::is_string_view () const [inline], [constexpr]
Definition at line 439 of file value-type.h.
                                        {
    uint32_t bits = bit_field_ & value_type_impl::kGenericKindMask;
    return bits == static_cast<uint32_t>(GenericKind::kStringViewWtf8) ||
           bits == static_cast<uint32_t>(GenericKind::kStringViewWtf16) ||
           bits == static_cast<uint32_t>(GenericKind::kStringViewIter);
  }
References bit_field_, and v8::internal::wasm::value_type_impl::kGenericKindMask.
Referenced by v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DECODE(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), name(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::TypeCheckAlwaysFails(), and v8::internal::wasm::WasmBytecodeGenerator::TypeCheckAlwaysFails().
is_top()
constexpr bool v8::internal::wasm::ValueTypeBase::is_top () const [inline], [constexpr]
Definition at line 431 of file value-type.h.
                                {
    uint32_t bits = bit_field_ & value_type_impl::kGenericKindMask;
    return bits == static_cast<uint32_t>(GenericKind::kTop);
  }
References bit_field_, and v8::internal::wasm::value_type_impl::kGenericKindMask.
Referenced by v8::internal::wasm::IsSubtypeOfImpl(), kind(), short_name(), and v8::internal::wasm::Union().
is_uninhabited()
constexpr bool v8::internal::wasm::ValueTypeBase::is_uninhabited () const [inline], [constexpr]
Definition at line 456 of file value-type.h.
                                        {
    if (is_bottom()) return true;
    if (is_defaultable()) return false; // Includes all nullable refs.
    if (has_index()) return false;
    // Non-nullable references to null types are uninhabitable.
    return IsNullKind(generic_kind());
  }
References generic_kind(), has_index(), is_bottom(), is_defaultable(), and v8::internal::wasm::IsNullKind().
Referenced by v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::ProcessPhi(), v8::internal::compiler::WasmGCOperatorReducer::ReduceAssertNotNull(), v8::internal::compiler::WasmGCOperatorReducer::ReduceCheckNull(), v8::internal::compiler::WasmGCOperatorReducer::ReduceIf(), v8::internal::compiler::WasmGCOperatorReducer::ReduceTypeGuard(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmArrayLength(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructGet(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmStructOperation(), v8::internal::compiler::WasmLoadElimination::ReduceWasmStructSet(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCast(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCastAbstract(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheck(), v8::internal::compiler::WasmGCOperatorReducer::ReduceWasmTypeCheckAbstract(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull(), v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCast(), and v8::internal::compiler::turboshaft::WasmGCTypedOptimizationReducer< Next >::WasmTypeCheck().
is_valid()
constexpr bool v8::internal::wasm::ValueTypeBase::is_valid () const [inline], [constexpr]
Definition at line 577 of file value-type.h.
                                  {
    static_assert(static_cast<int>(StandardType::kI32) >
                  static_cast<int>(StandardType::kAny));
    uint32_t payload = value_type_impl::PayloadField::decode(bit_field_);
    if (is_numeric()) {
      // For numeric types, everything outside the payload is fixed.
      if ((bit_field_ & ~value_type_impl::PayloadField::kMask) !=
          value_type_impl::kNumericExtraBits) {
        return false;
      }
      return payload >= value_type_impl::kNumberOfGenericKinds &&
             payload < value_type_impl::kNumberOfStandardTypes;
    }
    if (!has_index()) {
      // Generic types must be part of the predefined set.
      if (payload >= value_type_impl::kNumberOfGenericKinds) return false;
      // Only indexed types can be exact.
      if (is_exact()) return false;
    }
    // Both generic and indexed ref types must leave the reserved bits free.
    return value_type_impl::ReservedField::decode(bit_field_) == 0;
  }
References bit_field_, v8::base::BitField< T, shift, size, U >::decode(), has_index(), is_exact(), is_numeric(), v8::base::BitField< T, shift, size, U >::kMask, v8::internal::wasm::value_type_impl::kNumberOfGenericKinds, v8::internal::wasm::value_type_impl::kNumberOfStandardTypes, and v8::internal::wasm::value_type_impl::kNumericExtraBits.
Referenced by v8::internal::WasmTableObject::unsafe_type(), and ValueTypeBase().
is_void()
constexpr bool v8::internal::wasm::ValueTypeBase::is_void () const [inline], [constexpr]
Definition at line 435 of file value-type.h.
                                 {
    uint32_t bits = bit_field_ & value_type_impl::kGenericKindMask;
    return bits == static_cast<uint32_t>(GenericKind::kVoid);
  }
References bit_field_, and v8::internal::wasm::value_type_impl::kGenericKindMask.
Referenced by kind(), and short_name().
kind()
constexpr ValueKind v8::internal::wasm::ValueTypeBase::kind () const [inline], [constexpr]
Definition at line 637 of file value-type.h.
                                   {
    if (is_numeric()) {
      switch (numeric_kind()) {
        case NumericKind::kI32:
          return kI32;
        case NumericKind::kI64:
          return kI64;
        case NumericKind::kF32:
          return kF32;
        case NumericKind::kF64:
          return kF64;
        case NumericKind::kS128:
          return kS128;
        case NumericKind::kI8:
          return kI8;
        case NumericKind::kI16:
          return kI16;
        case NumericKind::kF16:
          return kF16;
      }
      UNREACHABLE();
    }
    if (is_top()) return kTop;
    if (is_bottom()) return kBottom;
    if (is_void()) return kVoid;
    return is_nullable() ? kRefNull : kRef;
  }
References is_bottom(), is_nullable(), is_numeric(), is_top(), is_void(), v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, numeric_kind(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayAtomicSet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayCopy(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayFill(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNew(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArrayNewFixed(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::ArraySet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnNonNull(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::BrOnNull(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildChangeEndiannessStore(), v8::internal::wasm::WasmInterpreterRuntime::ContinueExecution(), v8::internal::wasm::WasmBytecodeGenerator::CopyToSlot(), v8::internal::wasm::WasmBytecodeGenerator::CreateSlot(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::WasmBytecodeGenerator::EmitCopySlot(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteFunction(), v8::internal::wasm::WasmInterpreterRuntime::ExecuteIndirectCall(), v8::internal::wasm::HeapType::Generic(), v8::internal::wasm::ValueType::Generic(), v8::internal::WasmArray::GetElement(), v8::internal::WasmStruct::GetFieldValue(), v8::internal::WasmTrustedInstanceData::GetGlobalValue(), v8::internal::wasm::gdb_server::WasmModuleDebug::GetWasmValue(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::global_op(), v8::internal::wasm::HeapType::Index(), v8::internal::wasm::WasmBytecodeGenerator::InitSlotsForFunctionArgs(), is_generic(), v8::internal::wasm::ValueType::is_reference_to(), v8::internal::wasm::JSToWasmObject(), v8::internal::wasm::Slot::kind(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadLane(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::LoadMem(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::local_op(), v8::internal::wasm::WasmBytecode::LocalsSizeInSlots(), name(), Populate(), v8::internal::wasm::WasmInterpreterRuntime::PrepareTailCall(), v8::internal::wasm::ValueType::Primitive(), v8::internal::wasm::CanonicalValueType::Primitive(), Primitive(), v8::internal::wasm::InstanceBuilder::ProcessImportedWasmGlobalObject(), v8::internal::wasm::CanonicalValueType::Ref(), v8::internal::wasm::ValueType::Ref(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefCastImpl(), v8::internal::wasm::WasmBytecode::RefLocalsCount(), v8::internal::wasm::ValueType::RefMaybeNull(), v8::internal::wasm::CanonicalValueType::RefNull(), v8::internal::wasm::ValueType::RefNull(), v8::internal::RUNTIME_FUNCTION(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNew(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewDefault(), v8::internal::wasm::Handlers< Compressed >::s2s_ArrayNewFixed(), v8::internal::wasm::Handlers< Compressed >::s2s_RefArrayNew(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNew(), v8::internal::wasm::Handlers< Compressed >::s2s_StructNewDefault(), v8::internal::wasm::TurboshaftGraphBuildingInterface::Select(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StartFunction(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreLane(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StoreMem(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicCompareExchange(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructAtomicCompareExchange(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::StructAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicRMW(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructAtomicSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructGet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructNew(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::StructSet(), v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::SubtypeCheck(), v8::internal::wasm::WasmValue::to_string(), v8::internal::wasm::fuzzing::anonymous_namespace{random-module-generation.cc}::BodyGen::try_block_helper(), and v8::internal::wasm::WasmReturnTypeFromSignature().
machine_representation()
constexpr MachineRepresentation v8::internal::wasm::ValueTypeBase::machine_representation () const [inline], [constexpr]
Definition at line 521 of file value-type.h.
                                                                 {
    return machine_type().representation();
  }
References machine_type(), and v8::internal::MachineType::representation().
Referenced by v8::internal::wasm::anonymous_namespace{module-instantiate.cc}::CompareWithNormalizedCType(), v8::internal::compiler::WasmGCLowering::ReduceWasmStructSet(), and v8::internal::wasm::TurboshaftGraphBuildingInterface::StoreInStackSlot().
machine_type()
constexpr MachineType v8::internal::wasm::ValueTypeBase::machine_type () const [inline], [constexpr]
Definition at line 507 of file value-type.h.
                                             {
    // TODO(jkummerow): Do any callers ever pass a sentinel here?
    if (is_sentinel()) return MachineType::None();
    if (is_ref()) return MachineType::AnyTagged();
    constexpr MachineType kMachineType[] = {
#define MACH_TYPE(kind, log2Size, code, machineType, ...) \
  MachineType::machineType(),
        FOREACH_NUMERIC_VALUE_TYPE(MACH_TYPE)
#undef MACH_TYPE
    };
    uint32_t index = value_type_impl::ToZeroBasedIndex(numeric_kind());
    return kMachineType[index];
  }
References v8::internal::MachineType::AnyTagged(), FOREACH_NUMERIC_VALUE_TYPE, v8::internal::index, is_ref(), is_sentinel(), MACH_TYPE, v8::internal::MachineType::None(), numeric_kind(), and v8::internal::wasm::value_type_impl::ToZeroBasedIndex().
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::CreateFrameState(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), and machine_representation().
name()
std::string v8::internal::wasm::ValueTypeBase::name () const
Definition at line 116 of file value-type.cc.
                                    {
  if (is_numeric()) {
    switch (numeric_kind()) {
#define NUMERIC_CASE(kind, log2, code, mtype, shortName, name) \
  case NumericKind::k##kind: \
    return name;
      FOREACH_NUMERIC_VALUE_TYPE(NUMERIC_CASE)
#undef NUMERIC_CASE
    }
    UNREACHABLE();
  }
  std::ostringstream buf;
  if (has_index()) {
    buf << "(ref ";
    if (is_nullable()) buf << "null ";
    if (is_exact()) buf << "exact ";
    buf << raw_index().index << ")";
  } else {
    DCHECK(is_generic());
    if (is_nullable()) {
      GenericKind kind = generic_kind();
      if (kind == GenericKind::kNone) {
        // The code below would produce "noneref", and we need to keep it
        // that way for "(ref none)", so we need this special case.
        return is_shared() ? "(shared nullref)" : "nullref";
      } else if (kind == GenericKind::kNoExn) {
        return is_shared() ? "(shared nullexnref)" : "nullexnref";
      } else if (kind == GenericKind::kNoExtern) {
        return is_shared() ? "(shared nullexternref)" : "nullexternref";
      } else if (kind == GenericKind::kNoFunc) {
        return is_shared() ? "(shared nullfuncref)" : "nullfuncref";
      } else if (kind == GenericKind::kNoCont) {
        return is_shared() ? "(shared nullcontref)" : "nullcontref";
      }
    }
    bool shorthand =
        (is_nullable() || is_sentinel() || is_string_view()) && !is_exact();
    bool append_ref = is_nullable() && !is_sentinel() && !is_exact();
    if (!shorthand) buf << "(ref ";
    if (!shorthand && is_nullable()) buf << "null ";
    PrintGenericHeaptypeName(buf, *this);
    if (append_ref) buf << "ref";
    if (!shorthand) buf << ")";
  }
  return buf.str();
}
References v8::internal::DCHECK(), FOREACH_NUMERIC_VALUE_TYPE, generic_kind(), has_index(), v8::internal::wasm::TypeIndex::index, is_exact(), is_generic(), is_nullable(), is_numeric(), is_sentinel(), is_shared(), is_string_view(), kind(), NUMERIC_CASE, numeric_kind(), v8::internal::wasm::anonymous_namespace{value-type.cc}::PrintGenericHeaptypeName(), raw_index(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::ModuleDecoderImpl::consume_element_func_index(), v8::internal::wasm::ModuleDecoderImpl::consume_element_segment_header(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeAtomicOpcode(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::ModuleDecoderImpl::DecodeTableSection(), v8::internal::compiler::operator<<(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::ParseBrOnCast(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopPackedArray(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::PopTypeError(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledge(), v8::internal::compiler::turboshaft::WasmGCTypeAnalyzer::RefineTypeKnowledgeNotNull(), v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate(), and v8::internal::wasm::InstanceBuilder::WriteGlobalValue().
nullability()
constexpr Nullability v8::internal::wasm::ValueTypeBase::nullability () const [inline], [constexpr]
Definition at line 390 of file value-type.h.
                                            {
    DCHECK(is_ref());
    return value_type_impl::IsNullableField::decode(bit_field_);
  }
References bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), and is_ref().
Referenced by v8::internal::wasm::EquivalentTypes(), is_non_nullable(), is_nullable(), v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseAnyConvertExtern(), and v8::internal::compiler::anonymous_namespace{wasm-inlining-into-js.cc}::WasmIntoJSInlinerImpl::ParseExternConvertAny().
numeric_kind()
constexpr NumericKind v8::internal::wasm::ValueTypeBase::numeric_kind () const [inline], [constexpr]
Definition at line 416 of file value-type.h.
                                             {
    DCHECK(is_numeric());
    return static_cast<NumericKind>(bit_field_ &
                                    value_type_impl::kNumericKindMask);
  }
References bit_field_, v8::internal::DCHECK(), is_numeric(), and v8::internal::wasm::value_type_impl::kNumericKindMask.
Referenced by kind(), machine_type(), name(), short_name(), value_kind_size(), value_kind_size_log2(), and value_type_code_numeric().
Populate()
void v8::internal::wasm::ValueTypeBase::Populate (bool shared, RefTypeKind kind) [inline]
Definition at line 360 of file value-type.h.
                                               {
    uint32_t bits = value_type_impl::IsSharedField::update(bit_field_, shared);
    bit_field_ = value_type_impl::RefTypeKindField::update(bits, kind);
  }
References bit_field_, kind(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::wasm::value_type_reader::Populate().
Primitive()
static constexpr ValueTypeBase v8::internal::wasm::ValueTypeBase::Primitive (ValueKind kind) [inline], [static], [constexpr]
Definition at line 609 of file value-type.h.
                                                           {
    switch (kind) {
      case kI32:
        return ValueTypeBase(NumericKind::kI32);
      case kI64:
        return ValueTypeBase(NumericKind::kI64);
      case kF32:
        return ValueTypeBase(NumericKind::kF32);
      case kF64:
        return ValueTypeBase(NumericKind::kF64);
      case kS128:
        return ValueTypeBase(NumericKind::kS128);
      case kI8:
        return ValueTypeBase(NumericKind::kI8);
      case kI16:
        return ValueTypeBase(NumericKind::kI16);
      case kF16:
        return ValueTypeBase(NumericKind::kF16);
      case kVoid:
        return ValueTypeBase(GenericKind::kVoid, kNonNullable, false);
      case kRef:
      case kRefNull:
      case kTop:
      case kBottom:
        UNREACHABLE();
    }
  }
References v8::internal::kF32, v8::internal::kF64, v8::internal::kI16, v8::internal::kI32, v8::internal::kI64, v8::internal::kI8, kind(), v8::internal::wasm::kNonNullable, v8::internal::kRef, v8::internal::kRefNull, v8::internal::kS128, v8::internal::UNREACHABLE(), and ValueTypeBase().
Referenced by v8::internal::wasm::ValueType::Primitive().
raw_bit_field()
constexpr uint32_t v8::internal::wasm::ValueTypeBase::raw_bit_field () const [inline], [constexpr]
Definition at line 600 of file value-type.h.
{ return bit_field_; }
References bit_field_.
Referenced by v8::internal::wasm::TurboshaftGraphBuildingInterface::ArrayFillImpl(), v8::internal::wasm::HeapType::AsExact(), v8::internal::wasm::ValueType::AsExact(), v8::internal::wasm::CanonicalValueType::AsExact(), v8::internal::wasm::ValueType::AsNonShared(), v8::internal::wasm::ValueType::AsNullable(), v8::internal::wasm::ValueType::Canonicalize(), v8::internal::wasm::WasmBytecodeGenerator::DecodeGCOp(), v8::internal::wasm::WasmBytecodeGenerator::DecodeInstruction(), v8::internal::wasm::WasmBytecodeGenerator::DoEncodeInstruction(), v8::internal::wasm::WasmBytecodeGenerator::GenerateBytecode(), v8::internal::compiler::hash_value(), v8::internal::WasmTableObject::New(), v8::internal::wasm::IndependentValueType::operator==(), v8::internal::wasm::ConstantExpression::RefNull(), v8::internal::wasm::WasmInitExpr::RefNullConst(), v8::internal::RUNTIME_FUNCTION(), and v8::internal::wasm::WasmInterpreterRuntime::WasmJSToWasmObject().
raw_heap_representation()
constexpr uint32_t v8::internal::wasm::ValueTypeBase::raw_heap_representation (bool distinguish_shared) const [constexpr]
Definition at line 857 of file value-type.h.
                                   {
  DCHECK(!is_numeric());
  if (has_index()) return raw_index().index;
  switch (generic_kind()) {
    case GenericKind::kTop:
      return HeapType::kTop;
    case GenericKind::kBottom:
      return HeapType::kBottom;
#define CASE(name, ...) \
  case GenericKind::k##name: \
    return distinguish_shared && is_shared() ? HeapType::k##name##Shared \
                                             : HeapType::k##name;
      FOREACH_ABSTRACT_TYPE(CASE)
#undef CASE
    case GenericKind::kExternString:
      return distinguish_shared && is_shared() ? HeapType::kExternStringShared
                                               : HeapType::kExternString;
    case GenericKind::kVoid:
      UNREACHABLE();
  }
}
References CASE, v8::internal::DCHECK(), FOREACH_ABSTRACT_TYPE, generic_kind(), has_index(), v8::internal::wasm::TypeIndex::index, is_numeric(), is_shared(), v8::internal::wasm::HeapType::kBottom, v8::internal::wasm::HeapType::kExternString, v8::internal::wasm::HeapType::kExternStringShared, v8::internal::wasm::HeapType::kTop, raw_index(), and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::ValueType::heap_representation(), v8::internal::wasm::CanonicalValueType::heap_representation(), v8::internal::wasm::CanonicalValueType::heap_representation_non_shared(), and v8::internal::wasm::HeapType::representation().
raw_index()
constexpr TypeIndex v8::internal::wasm::ValueTypeBase::raw_index () const [inline], [constexpr], [protected]
Definition at line 705 of file value-type.h.
                                        {
    DCHECK(has_index());
    return TypeIndex(value_type_impl::PayloadField::decode(bit_field_));
  }
References bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), and has_index().
Referenced by name(), v8::internal::wasm::HeapType::name(), raw_heap_representation(), v8::internal::wasm::HeapType::ref_index(), v8::internal::wasm::ValueType::ref_index(), and v8::internal::wasm::CanonicalValueType::ref_index().
ref_type_kind()
constexpr RefTypeKind v8::internal::wasm::ValueTypeBase::ref_type_kind () const [inline], [constexpr]
Definition at line 407 of file value-type.h.
                                              {
    return value_type_impl::RefTypeKindField::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by v8::internal::wasm::anonymous_namespace{wasm-subtyping.cc}::CommonAncestor(), v8::internal::wasm::WasmFullDecoder< ValidationTag, Interface, decoding_mode >::DecodeGCOpcode(), v8::internal::wasm::JSPrototypesSetup::IsDescriptorGlobal(), v8::internal::wasm::CanonicalValueType::IsFunctionType(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableGet(), v8::internal::wasm::TurboshaftGraphBuildingInterface::TableSet(), and v8::internal::wasm::WasmDecoder< ValidationTag, decoding_mode >::Validate().
short_name()
constexpr char v8::internal::wasm::ValueTypeBase::short_name () const [inline], [constexpr]
Definition at line 555 of file value-type.h.
                                    {
    if (is_ref()) {
      return is_nullable() ? 'n' : 'r';
    }
    if (is_sentinel()) {
      if (is_void()) return 'v';
      if (is_top()) return '\\';
      if (is_bottom()) return '*';
      // Otherwise fall through to the DCHECK in {numeric_kind()}.
    }
    constexpr const char kNumericShortName[] = {
#define SHORT_NAME(kind, log2, code, mtype, shortName, ...) shortName,
        FOREACH_NUMERIC_VALUE_TYPE(SHORT_NAME)
#undef SHORT_NAME
    };
    uint32_t index = value_type_impl::ToZeroBasedIndex(numeric_kind());
    return kNumericShortName[index];
  }
References FOREACH_NUMERIC_VALUE_TYPE, v8::internal::index, is_bottom(), is_nullable(), is_ref(), is_sentinel(), is_top(), is_void(), numeric_kind(), SHORT_NAME, and v8::internal::wasm::value_type_impl::ToZeroBasedIndex().
standard_type()
constexpr StandardType v8::internal::wasm::ValueTypeBase::standard_type () const [inline], [constexpr]
Definition at line 411 of file value-type.h.
                                               {
    DCHECK(!has_index());
    return static_cast<StandardType>(
        value_type_impl::PayloadField::decode(bit_field_));
  }
References bit_field_, v8::internal::DCHECK(), v8::base::BitField< T, shift, size, U >::decode(), and has_index().
type_kind()
constexpr TypeKind v8::internal::wasm::ValueTypeBase::type_kind () const [inline], [constexpr]
Definition at line 365 of file value-type.h.
                                       {
    return value_type_impl::TypeKindField::decode(bit_field_);
  }
References bit_field_, and v8::base::BitField< T, shift, size, U >::decode().
Referenced by has_index(), is_abstract_ref(), is_generic(), is_numeric(), and is_sentinel().
use_wasm_null()
constexpr bool v8::internal::wasm::ValueTypeBase::use_wasm_null () const [inline], [constexpr]
Definition at line 463 of file value-type.h.
                                       {
    DCHECK(is_ref());
    // TODO(jkummerow): Consider calling {wasm::IsSubtypeOf}.
    if (has_index()) return true;
    GenericKind ref = generic_kind();
    if (ref == GenericKind::kExtern) return false;
    if (ref == GenericKind::kExternString) return false;
    if (ref == GenericKind::kNoExtern) return false;
    return true;
  }
References v8::internal::DCHECK(), generic_kind(), has_index(), and is_ref().
Referenced by v8::internal::wasm::InstanceBuilder::Build_Phase1(), v8::internal::wasm::EvaluateConstantExpression(), v8::internal::wasm::JSToWasmObject(), and v8::internal::wasm::anonymous_namespace{liftoff-compiler.cc}::LiftoffCompiler::RefAsNonNull().
value_kind_full_size()
constexpr int v8::internal::wasm::ValueTypeBase::value_kind_full_size () const [inline], [constexpr]
Definition at line 498 of file value-type.h.
                                             {
    if (is_ref()) {
      // Uncompressed pointer size.
      return kSystemPointerSize;
    }
    return value_kind_size();
  }
References is_ref(), v8::internal::kSystemPointerSize, and value_kind_size().
value_kind_size()
constexpr int v8::internal::wasm::ValueTypeBase::value_kind_size () const [inline], [constexpr]
Definition at line 486 of file value-type.h.
                                        {
    DCHECK(!is_sentinel()); // Caller's responsibility.
    if (is_ref()) return kTaggedSize;
    constexpr uint8_t kValueKindSize[] = {
#define ELEM_SIZE_LOG2(kind, log2Size, ...) (1 << log2Size),
        FOREACH_NUMERIC_VALUE_TYPE(ELEM_SIZE_LOG2)
#undef ELEM_SIZE_LOG2
    };
    uint32_t index = value_type_impl::ToZeroBasedIndex(numeric_kind());
    return kValueKindSize[index];
  }
References v8::internal::DCHECK(), ELEM_SIZE_LOG2, FOREACH_NUMERIC_VALUE_TYPE, v8::internal::index, is_ref(), is_sentinel(), v8::internal::kTaggedSize, numeric_kind(), and v8::internal::wasm::value_type_impl::ToZeroBasedIndex().
Referenced by v8::internal::wasm::array_copy_wrapper(), v8::internal::wasm::TurboshaftGraphBuildingInterface::BuildChangeEndiannessStore(), v8::internal::wasm::ModuleDecoderImpl::CalculateGlobalOffsets(), v8::internal::wasm::WasmValue::CopyTo(), v8::internal::CreateArrayMap(), v8::internal::wasm::TurboshaftGraphBuildingInterface::DoReturn(), v8::internal::WasmArray::GetElement(), v8::internal::wasm::StructTypeBase::InitializeOffsets(), v8::internal::wasm::WasmValue::operator==(), v8::internal::RUNTIME_FUNCTION(), v8::internal::compiler::WasmLoadElimination::TruncateAndExtendOrType(), value_kind_full_size(), v8::internal::compiler::turboshaft::WasmLoweringReducer< Next >::WasmAllocateArray(), v8::internal::compiler::WasmGraphAssembler::WasmArrayElementOffset(), v8::internal::wasm::WasmValue::WasmValue(), and v8::internal::wasm::WasmValue::zero_byte_representation().
value_kind_size_log2()
constexpr int v8::internal::wasm::ValueTypeBase::value_kind_size_log2 () const [inline], [constexpr]
Definition at line 474 of file value-type.h.
                                             {
    DCHECK(!is_sentinel()); // Caller's responsibility.
    if (is_ref()) return kTaggedSizeLog2;
    constexpr uint8_t kValueKindSizeLog2[] = {
#define VALUE_KIND_SIZE_LOG2(kind, log2Size, ...) log2Size,
        FOREACH_NUMERIC_VALUE_TYPE(VALUE_KIND_SIZE_LOG2)
#undef VALUE_KIND_SIZE_LOG2
    };
    uint32_t index = value_type_impl::ToZeroBasedIndex(numeric_kind());
    return kValueKindSizeLog2[index];
  }
References v8::internal::DCHECK(), FOREACH_NUMERIC_VALUE_TYPE, v8::internal::index, is_ref(), is_sentinel(), v8::internal::kTaggedSizeLog2, numeric_kind(), v8::internal::wasm::value_type_impl::ToZeroBasedIndex(), and VALUE_KIND_SIZE_LOG2.
value_type_code()
ValueTypeCode v8::internal::wasm::ValueTypeBase::value_type_code () const [inline]
Definition at line 528 of file value-type.h.
                                        {
    if (is_numeric()) return value_type_code_numeric();
    if (is_ref() && encoding_needs_heap_type()) {
      return is_nullable() ? kRefNullCode : kRefCode;
    }
    DCHECK(!has_index()); // Handled by {encoding_needs_heap_type()}.
    return value_type_code_generic();
  }
References v8::internal::DCHECK(), encoding_needs_heap_type(), has_index(), is_nullable(), is_numeric(), is_ref(), v8::internal::wasm::kRefCode, v8::internal::wasm::kRefNullCode, value_type_code_generic(), and value_type_code_numeric().
Referenced by v8::internal::wasm::LocalDeclEncoder::Emit().
value_type_code_generic()
ValueTypeCode v8::internal::wasm::ValueTypeBase::value_type_code_generic () const
Definition at line 50 of file value-type.cc.
                                                           {
  switch (generic_kind()) {
#define ABSTRACT_TYPE_CASE(name, code, ...) \
  case GenericKind::k##name: \
    return k##code##Code;
    FOREACH_ABSTRACT_TYPE(ABSTRACT_TYPE_CASE)
#undef ABSTRACT_TYPE_CASE
    // Among "internal" types, only "void" has a wire bytes encoding.
#define INTERNAL_TYPE_CASE(name, code, ...) \
  case GenericKind::k##name: \
    if constexpr (GenericKind::k##name == GenericKind::kVoid) { \
      return k##code##Code; \
    } else { \
      UNREACHABLE(); \
    }
    FOREACH_INTERNAL_TYPE(INTERNAL_TYPE_CASE)
#undef INTERNAL_TYPE_CASE
  }
  UNREACHABLE();
}
References ABSTRACT_TYPE_CASE, FOREACH_ABSTRACT_TYPE, FOREACH_INTERNAL_TYPE, generic_kind(), INTERNAL_TYPE_CASE, and v8::internal::UNREACHABLE().
Referenced by v8::internal::wasm::HeapType::code(), and value_type_code().
value_type_code_numeric()
ValueTypeCode v8::internal::wasm::ValueTypeBase::value_type_code_numeric () const
Definition at line 39 of file value-type.cc.
                                                           {
  switch (numeric_kind()) {
#define NUMERIC_CASE(kind, ...) \
  case NumericKind::k##kind: \
    return k##kind##Code;
    FOREACH_NUMERIC_VALUE_TYPE(NUMERIC_CASE)
#undef NUMERIC_CASE
  }
  UNREACHABLE();
}
References FOREACH_NUMERIC_VALUE_TYPE, NUMERIC_CASE, numeric_kind(), and v8::internal::UNREACHABLE().
Referenced by value_type_code().
Friends And Related Function Documentation
CanonicalValueType
friend class CanonicalValueType [friend]
Definition at line 668 of file value-type.h.
HeapType
friend class HeapType [friend]
Definition at line 669 of file value-type.h.
IndependentValueType
friend class IndependentValueType [friend]
Definition at line 670 of file value-type.h.
ValueType
friend class ValueType [friend]
Definition at line 671 of file value-type.h.
Member Data Documentation
bit_field_
uint32_t v8::internal::wasm::ValueTypeBase::bit_field_ [protected]
Definition at line 710 of file value-type.h.
Referenced by exactness(), generic_kind(), hash_value(), is_bottom(), v8::internal::wasm::CanonicalValueType::is_equal_except_index(), is_packed(), is_ref(), is_shared(), is_string_view(), is_top(), is_valid(), is_void(), nullability(), numeric_kind(), v8::internal::wasm::CanonicalValueType::operator==(), v8::internal::wasm::HeapType::operator==(), v8::internal::wasm::ValueType::operator==(), Populate(), raw_bit_field(), raw_index(), ref_type_kind(), standard_type(), type_kind(), and v8::internal::wasm::ValueType::Unpacked().
kHasIndexBit
const uint32_t v8::internal::wasm::ValueTypeBase::kHasIndexBit [static]
Initial value:
=
      value_type_impl::HasIndexOrSentinelField::kMask
Definition at line 345 of file value-type.h.
kIndexBits
const uint32_t v8::internal::wasm::ValueTypeBase::kIndexBits = value_type_impl::PayloadField::kMask [static]
Definition at line 350 of file value-type.h.
Referenced by v8::internal::wasm::CanonicalValueType::is_equal_except_index().
kIndexShift
const uint32_t v8::internal::wasm::ValueTypeBase::kIndexShift = value_type_impl::PayloadField::kShift [static]
Definition at line 351 of file value-type.h.
kIsNullableBit
const uint32_t v8::internal::wasm::ValueTypeBase::kIsNullableBit [static]
Initial value:
=
      value_type_impl::IsNullableField::kMask
Definition at line 342 of file value-type.h.
kIsRefBit
const uint32_t v8::internal::wasm::ValueTypeBase::kIsRefBit = value_type_impl::IsRefField::kMask [static]
Definition at line 341 of file value-type.h.
kIsSharedBit
const uint32_t v8::internal::wasm::ValueTypeBase::kIsSharedBit = value_type_impl::IsSharedField::kMask [static]
Definition at line 344 of file value-type.h.
kLastUsedBit
const int v8::internal::wasm::ValueTypeBase::kLastUsedBit = value_type_impl::PayloadField::kLastUsedBit [static]
Definition at line 340 of file value-type.h.
Referenced by v8::internal::RUNTIME_FUNCTION().
kNumIndexBits
const int v8::internal::wasm::ValueTypeBase::kNumIndexBits = value_type_impl::PayloadField::kSize [static]
Definition at line 339 of file value-type.h.
Referenced by v8::internal::wasm::TypeCanonicalizer::CanonicalizeTypeDef(), and v8::internal::RUNTIME_FUNCTION().
kRefKindBits
const uint32_t v8::internal::wasm::ValueTypeBase::kRefKindBits = value_type_impl::RefTypeKindField::kMask [static]
Definition at line 347 of file value-type.h.
kRefKindShift
const uint32_t v8::internal::wasm::ValueTypeBase::kRefKindShift [static]
Initial value:
=
      value_type_impl::RefTypeKindField::kShift
Definition at line 348 of file value-type.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/wasm/value-type.h
/mnt/V8SourceCode/src/wasm/value-type.cc