cppgc::internal::VerificationState Class Reference
#include <marking-verifier.h>
Public Member Functions
void VerifyMarked (const void *) const
void SetCurrentParent (const HeapObjectHeader *header)
bool IsParentOnStack () const
Protected Attributes
const HeapObjectHeader * parent_ = nullptr
Detailed Description
Definition at line 21 of file marking-verifier.h.
Member Function Documentation
IsParentOnStack()
bool cppgc::internal::VerificationState::IsParentOnStack () const [inline]
Definition at line 27 of file marking-verifier.h.
{ return !parent_; }
References parent_.
Referenced by cppgc::internal::MarkingVerifierBase::VisitInConstructionConservatively().
SetCurrentParent()
void cppgc::internal::VerificationState::SetCurrentParent (const HeapObjectHeader * header) [inline]
Definition at line 24 of file marking-verifier.h.
{ parent_ = header; }
References parent_.
Referenced by cppgc::internal::MarkingVerifierBase::VisitHeapObjectHeader().
VerifyMarked()
void cppgc::internal::VerificationState::VerifyMarked (const void * base_object_payload) const
Definition at line 21 of file marking-verifier.cc.
                                                                          {
  const HeapObjectHeader& child_header =
      HeapObjectHeader::FromObject(base_object_payload);
  if (!child_header.IsMarked()) {
    FATAL(
        "MarkingVerifier: Encountered unmarked object.\n"
        "#\n"
        "# Hint:\n"
        "# %s (%p)\n"
        "# \\-> %s (%p)",
        parent_
            ? parent_
                  ->GetName(
                      HeapObjectNameForUnnamedObject::kUseClassNameIfSupported)
                  .value
            : "Stack",
        parent_ ? parent_->ObjectStart() : nullptr,
        child_header
            .GetName(HeapObjectNameForUnnamedObject::kUseClassNameIfSupported)
            .value,
        child_header.ObjectStart());
  }
}
References FATAL, cppgc::internal::HeapObjectHeader::FromObject(), cppgc::internal::HeapObjectHeader::GetName(), cppgc::internal::HeapObjectHeader::IsMarked(), cppgc::internal::kUseClassNameIfSupported, cppgc::internal::HeapObjectHeader::ObjectStart(), parent_, cppgc::internal::HeapObjectName::value, and v8::internal::value.
Referenced by cppgc::internal::MarkingVerifierBase::VisitInConstructionConservatively().
Member Data Documentation
parent_
const HeapObjectHeader* cppgc::internal::VerificationState::parent_ = nullptr [protected]
Definition at line 30 of file marking-verifier.h.
Referenced by IsParentOnStack(), SetCurrentParent(), VerifyMarked(), and v8::internal::UnifiedHeapVerificationState::VerifyMarkedTracedReference().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/heap/cppgc/marking-verifier.h
/mnt/V8SourceCode/src/heap/cppgc/marking-verifier.cc