v8::internal::interpreter::TestTypeOfFlags Class Reference
#include <bytecode-flags-and-tokens.h>
Public Types
enum class LiteralFlag : uint8_t { DECLARE_LITERAL_FLAG
 }
Static Public Member Functions
static LiteralFlag GetFlagForLiteral (const AstStringConstants *ast_constants, Literal *literal)
static uint8_t Encode (LiteralFlag literal_flag)
static LiteralFlag Decode (uint8_t raw_flag)
static const char * ToString (LiteralFlag literal_flag)
Private Member Functions
DISALLOW_IMPLICIT_CONSTRUCTORS (TestTypeOfFlags)
Detailed Description
Definition at line 65 of file bytecode-flags-and-tokens.h.
Member Enumeration Documentation
LiteralFlag
enum v8::internal::interpreter::TestTypeOfFlags::LiteralFlag : uint8_t [strong]
Enumerator
DECLARE_LITERAL_FLAG
Definition at line 67 of file bytecode-flags-and-tokens.h.
                         : uint8_t {
#define DECLARE_LITERAL_FLAG(name, _) k##name,
    TYPEOF_LITERAL_LIST(DECLARE_LITERAL_FLAG)
#undef DECLARE_LITERAL_FLAG
  };
Member Function Documentation
Decode()
TestTypeOfFlags::LiteralFlag v8::internal::interpreter::TestTypeOfFlags::Decode (uint8_t raw_flag) [static]
Definition at line 72 of file bytecode-flags-and-tokens.cc.
                                                                   {
  DCHECK_LE(raw_flag, static_cast<uint8_t>(LiteralFlag::kOther));
  return static_cast<LiteralFlag>(raw_flag);
}
References DCHECK_LE.
DISALLOW_IMPLICIT_CONSTRUCTORS()
v8::internal::interpreter::TestTypeOfFlags::DISALLOW_IMPLICIT_CONSTRUCTORS (TestTypeOfFlags) [private]
Encode()
uint8_t v8::internal::interpreter::TestTypeOfFlags::Encode (LiteralFlag literal_flag) [static]
Definition at line 67 of file bytecode-flags-and-tokens.cc.
                                                        {
  return static_cast<uint8_t>(literal_flag);
}
Referenced by v8::internal::interpreter::BytecodeArrayBuilder::CompareTypeOf().
GetFlagForLiteral()
TestTypeOfFlags::LiteralFlag v8::internal::interpreter::TestTypeOfFlags::GetFlagForLiteral (const AstStringConstants * ast_constants, Literal * literal) [static]
Definition at line 42 of file bytecode-flags-and-tokens.cc.
                                                               {
  const AstRawString* raw_literal = literal->AsRawString();
  if (raw_literal == ast_constants->number_string()) {
    return LiteralFlag::kNumber;
  } else if (raw_literal == ast_constants->string_string()) {
    return LiteralFlag::kString;
  } else if (raw_literal == ast_constants->symbol_string()) {
    return LiteralFlag::kSymbol;
  } else if (raw_literal == ast_constants->boolean_string()) {
    return LiteralFlag::kBoolean;
  } else if (raw_literal == ast_constants->bigint_string()) {
    return LiteralFlag::kBigInt;
  } else if (raw_literal == ast_constants->undefined_string()) {
    return LiteralFlag::kUndefined;
  } else if (raw_literal == ast_constants->function_string()) {
    return LiteralFlag::kFunction;
  } else if (raw_literal == ast_constants->object_string()) {
    return LiteralFlag::kObject;
  } else {
    return LiteralFlag::kOther;
  }
}
References v8::internal::Literal::AsRawString(), and v8::internal::torque::ls::kFunction.
Referenced by v8::internal::interpreter::IsLiteralCompareTypeof().
ToString()
const char * v8::internal::interpreter::TestTypeOfFlags::ToString (LiteralFlag literal_flag) [static]
Definition at line 78 of file bytecode-flags-and-tokens.cc.
                                                              {
  switch (literal_flag) {
#define CASE(Name, name) \
  case LiteralFlag::k##Name: \
    return #name;
    TYPEOF_LITERAL_LIST(CASE)
#undef CASE
    default:
      return "<invalid>";
  }
}
References CASE, and TYPEOF_LITERAL_LIST.
Referenced by v8::internal::maglev::TestTypeOf::PrintParams(), and v8::internal::maglev::BranchIfTypeOf::PrintParams().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/interpreter/bytecode-flags-and-tokens.h
/mnt/V8SourceCode/src/interpreter/bytecode-flags-and-tokens.cc