v8::TryCatch Class Reference
An external exception handler.
#include <v8-exception.h>
Public Member Functions
TryCatch (Isolate *isolate)
Creates a new try/catch block and registers it with v8.
~TryCatch ()
Unregisters and deletes this try/catch block.
bool HasCaught () const
Returns true if an exception has been caught by this try/catch block.
bool CanContinue () const
For certain types of exceptions, it makes no sense to continue execution.
bool HasTerminated () const
Returns true if an exception has been caught due to script execution being terminated.
Local< Value > ReThrow ()
Throws the exception caught by this TryCatch in a way that avoids it being caught again by this same TryCatch.
Local< Value > Exception () const
Returns the exception caught by this try/catch block.
V8_WARN_UNUSED_RESULT MaybeLocal< Value > StackTrace (Local< Context > context) const
Returns the .stack property of the thrown object.
Local< v8::Message > Message () const
Returns the message associated with this exception.
void Reset ()
Clears any exceptions that may have been caught by this try/catch block.
void SetVerbose (bool value)
Set verbosity of the external exception handler.
bool IsVerbose () const
Returns true if verbosity is enabled.
void SetCaptureMessage (bool value)
Set whether or not this TryCatch should capture a Message object which holds source information about where the exception occurred.
TryCatch (const TryCatch &)=delete
void operator= (const TryCatch &)=delete
Static Public Member Functions
static V8_WARN_UNUSED_RESULT MaybeLocal< Value > StackTrace (Local< Context > context, Local< Value > exception)
Returns the .stack property of an object.
Private Member Functions
void * operator new (size_t size)
void * operator new[] (size_t size)
void operator delete (void *, size_t)
void operator delete[] (void *, size_t)
internal::Address JSStackComparableAddressPrivate ()
There are cases when the raw address of C++ TryCatch object cannot be used for comparisons with addresses into the JS stack.
void ResetInternal ()
Private Attributes
internal::Isolate * i_isolate_
TryCatch * next_
void * exception_
void * message_obj_
internal::Address js_stack_comparable_address_
bool is_verbose_: 1
bool can_continue_: 1
bool capture_message_: 1
bool rethrow_: 1
Friends
class internal::Isolate
class internal::ThreadLocalTop
Detailed Description
An external exception handler.
Definition at line 138 of file v8-exception.h.
Constructor & Destructor Documentation
TryCatch() [1/2]
v8::TryCatch::TryCatch (v8::Isolate * v8_isolate) [explicit]
Creates a new try/catch block and registers it with v8.
Note that all TryCatch blocks should be stack allocated because the memory location itself is compared against JavaScript try/catch blocks.
Definition at line 2772 of file api.cc.
    : i_isolate_(reinterpret_cast<i::Isolate*>(v8_isolate)),
      next_(i_isolate_->try_catch_handler()),
      is_verbose_(false),
      can_continue_(true),
      capture_message_(true),
      rethrow_(false) {
  ResetInternal();
  // Special handling for simulators which have a separate JS stack.
  js_stack_comparable_address_ = static_cast<internal::Address>(
      i::SimulatorStack::RegisterJSStackComparableAddress(i_isolate_));
  i_isolate_->RegisterTryCatchHandler(this);
}
References i_isolate_, js_stack_comparable_address_, v8::internal::SimulatorStack::RegisterJSStackComparableAddress(), v8::internal::Isolate::RegisterTryCatchHandler(), and ResetInternal().
 TryCatch()
v8::TryCatch::~TryCatch ()
Unregisters and deletes this try/catch block.
Definition at line 2794 of file api.cc.
                      {
  if (HasCaught()) {
    if (rethrow_ || (V8_UNLIKELY(HasTerminated()) &&
                     !i_isolate_->thread_local_top()->CallDepthIsZero())) {
      if (capture_message_) {
        // If an exception was caught and rethrow_ is indicated, the saved
        // message, script, and location need to be restored to Isolate TLS
        // for reuse. capture_message_ needs to be disabled so that Throw()
        // does not create a new message.
        i_isolate_->thread_local_top()->rethrowing_message_ = true;
        i_isolate_->set_pending_message(ToObject(message_obj_));
      }
      i_isolate_->UnregisterTryCatchHandler(this);
      i_isolate_->clear_internal_exception();
      i_isolate_->Throw(ToObject(exception_));
      return;
    }
    Reset();
  }
  i_isolate_->UnregisterTryCatchHandler(this);
  DCHECK_IMPLIES(rethrow_,
                 !i_isolate_->thread_local_top()->rethrowing_message_);
}
References DCHECK_IMPLIES, v8::anonymous_namespace{api.cc}::ToObject(), and V8_UNLIKELY.
TryCatch() [2/2]
v8::TryCatch::TryCatch (const TryCatch &) [delete]
Member Function Documentation
CanContinue()
bool v8::TryCatch::CanContinue () const
For certain types of exceptions, it makes no sense to continue execution.
If CanContinue returns false, the correct action is to perform any C++ cleanup needed and then return. If CanContinue returns false and HasTerminated returns true, it is possible to call CancelTerminateExecution in order to continue calling into the engine.
Definition at line 2827 of file api.cc.
{ return can_continue_; }
Referenced by v8_inspector::InjectedScript::wrapEvaluateResult().
Exception()
v8::Local< Value > v8::TryCatch::Exception () const
Returns the exception caught by this try/catch block.
If no exception has been caught an empty handle is returned.
Definition at line 2840 of file api.cc.
                                           {
  if (!HasCaught()) return {};
  if (HasTerminated()) {
    return v8::Utils::ToLocal(i_isolate_->factory()->null_value());
  }
  return v8::Utils::ToLocal(i::direct_handle(ToObject(exception_), i_isolate_));
}
References v8::internal::direct_handle(), and v8::anonymous_namespace{api.cc}::ToObject().
Referenced by v8_inspector::InjectedScript::createExceptionDetails(), v8_inspector::V8InspectorSessionImpl::evaluate(), v8::Shell::ExecuteModule(), v8_inspector::ValueMirror::getProperties(), v8::internal::anonymous_namespace{execution.cc}::InvokeWithTryCatch(), v8::anonymous_namespace{d8.cc}::RejectPromiseIfExecutionIsNotTerminating(), v8::Shell::ReportException(), v8::InspectorFrontend::Send(), and v8_inspector::InjectedScript::wrapEvaluateResult().
HasCaught()
bool v8::TryCatch::HasCaught () const
Returns true if an exception has been caught by this try/catch block.
Definition at line 2823 of file api.cc.
                                 {
  return !IsTheHole(ToObject(exception_), i_isolate_);
}
References v8::anonymous_namespace{api.cc}::ToObject().
Referenced by v8_inspector::V8RuntimeAgentImpl::compileScript(), v8_inspector::InjectedScript::createExceptionDetails(), v8::Shell::CreateRealm(), v8_inspector::anonymous_namespace{value-mirror.cc}::doesAttributeHaveObservableSideEffectOnGet(), v8_inspector::V8RuntimeAgentImpl::evaluate(), v8::internal::SourceTextModule::Evaluate(), v8_inspector::V8InspectorSessionImpl::evaluate(), v8::Shell::ExecuteModule(), v8::Shell::ExecuteString(), v8_inspector::ValueMirror::getProperties(), v8::Isolate::HasPendingException(), v8_inspector::anonymous_namespace{v8-runtime-agent-impl.cc}::innerCallFunctionOn(), v8::internal::anonymous_namespace{execution.cc}::InvokeWithTryCatch(), v8::Shell::JSONModuleEvaluationSteps(), v8::Shell::LoadJSON(), v8::internal::anonymous_namespace{gc-extension.cc}::Parse(), v8::internal::anonymous_namespace{liveedit.cc}::ParseScript(), v8::Worker::ProcessMessages(), v8::anonymous_namespace{d8.cc}::ProcessMessages(), v8_inspector::V8Console::queryObjectsCallback(), v8::anonymous_namespace{d8.cc}::RejectPromiseIfExecutionIsNotTerminating(), v8_inspector::anonymous_namespace{custom-preview.cc}::reportError(), v8::internal::anonymous_namespace{snapshot.cc}::RunExtraCode(), v8::InspectorClient::runMessageLoopOnPause(), v8_inspector::V8RuntimeAgentImpl::runScript(), v8::InspectorFrontend::Send(), v8_inspector::V8DebuggerAgentImpl::setVariableValue(), v8::AsyncHooks::ShellPromiseHook(), v8_inspector::V8Regex::V8Regex(), and v8_inspector::InjectedScript::wrapEvaluateResult().
HasTerminated()
bool v8::TryCatch::HasTerminated () const
Returns true if an exception has been caught due to script execution being terminated.
There is no JavaScript representation of an execution termination exception. Such exceptions are thrown when the TerminateExecution methods are called to terminate a long-running script.
If such an exception has been thrown, HasTerminated will return true, indicating that it is possible to call CancelTerminateExecution in order to continue calling into the engine.
Definition at line 2829 of file api.cc.
                                     {
  return ToObject(exception_) ==
         i::ReadOnlyRoots(i_isolate_).termination_exception();
}
References v8::anonymous_namespace{api.cc}::ToObject().
Referenced by v8::Shell::ExecuteString(), and v8_inspector::InjectedScript::wrapEvaluateResult().
IsVerbose()
bool v8::TryCatch::IsVerbose () const
Returns true if verbosity is enabled.
Definition at line 2896 of file api.cc.
{ return is_verbose_; }
Referenced by v8::internal::anonymous_namespace{isolate.cc}::PredictExceptionCatchAtFrame().
JSStackComparableAddressPrivate()
internal::Address v8::TryCatch::JSStackComparableAddressPrivate () [inline], [private]
There are cases when the raw address of C++ TryCatch object cannot be used for comparisons with addresses into the JS stack.
The cases are: 1) ARM, ARM64 and MIPS simulators which have separate JS stack. 2) Address sanitizer allocates local C++ object in the heap when UseAfterReturn mode is enabled. This method returns address that can be used for comparisons with addresses into the JS stack. When neither simulator nor ASAN's UseAfterReturn is enabled, then the address returned will be the address of the C++ try catch handler itself.
Definition at line 273 of file v8-exception.h.
                                                    {
    return js_stack_comparable_address_;
  }
Referenced by v8::internal::ThreadLocalTop::try_catch_handler_address().
Message()
v8::Local< v8::Message > v8::TryCatch::Message () const
Returns the message associated with this exception.
If there is no message associated an empty handle is returned.
Definition at line 2867 of file api.cc.
                                             {
  i::Tagged<i::Object> message = ToObject(message_obj_);
  DCHECK(IsJSMessageObject(message) || IsTheHole(message, i_isolate_));
  if (HasCaught() && !IsTheHole(message, i_isolate_)) {
    return v8::Utils::MessageToLocal(i::direct_handle(message, i_isolate_));
  } else {
    return {};
  }
}
References DCHECK, v8::internal::direct_handle(), and v8::anonymous_namespace{api.cc}::ToObject().
Referenced by v8_inspector::InjectedScript::createExceptionDetails(), v8::internal::anonymous_namespace{liveedit.cc}::ParseScript(), v8_inspector::anonymous_namespace{custom-preview.cc}::reportError(), v8::Shell::ReportException(), v8_inspector::V8Regex::V8Regex(), and v8_inspector::InjectedScript::wrapEvaluateResult().
operator delete()
void v8::TryCatch::operator delete (void * , size_t) [private]
Definition at line 2820 of file api.cc.
{ base::OS::Abort(); }
References v8::base::OS::Abort().
operator delete[]()
void v8::TryCatch::operator delete[] (void * , size_t) [private]
Definition at line 2821 of file api.cc.
{ base::OS::Abort(); }
References v8::base::OS::Abort().
operator new()
void * v8::TryCatch::operator new (size_t size) [private]
Definition at line 2818 of file api.cc.
{ base::OS::Abort(); }
References v8::base::OS::Abort().
operator new[]()
void * v8::TryCatch::operator new[] (size_t size) [private]
Definition at line 2819 of file api.cc.
{ base::OS::Abort(); }
References v8::base::OS::Abort().
operator=()
void v8::TryCatch::operator= (const TryCatch &) [delete]
Reset()
void v8::TryCatch::Reset ()
Clears any exceptions that may have been caught by this try/catch block.
After this method has been called, HasCaught() will return false. Cancels the scheduled exception if it is caught and ReThrow() is not called before.
It is not necessary to clear a try/catch block before using it again; if another exception is thrown the previously caught exception will just be overwritten. However, it is often a good idea since it makes it easier to determine which operation threw a given exception.
Definition at line 2877 of file api.cc.
                       {
  if (rethrow_) return;
  if (V8_UNLIKELY(i_isolate_->is_execution_terminating()) &&
      !i_isolate_->thread_local_top()->CallDepthIsZero()) {
    return;
  }
  i_isolate_->clear_internal_exception();
  i_isolate_->clear_pending_message();
  ResetInternal();
}
References V8_UNLIKELY.
Referenced by v8::internal::anonymous_namespace{messages.cc}::AppendErrorString(), v8::internal::Isolate::clear_exception(), v8_inspector::anonymous_namespace{value-mirror.cc}::doesAttributeHaveObservableSideEffectOnGet(), v8::internal::ErrorUtils::FormatStackTrace(), v8_inspector::anonymous_namespace{value-mirror.cc}::getErrorProperty(), v8_inspector::ValueMirror::getInternalProperties(), v8::internal::Isolate::ReportExceptionFunctionCallback(), and v8::internal::Isolate::ReportExceptionPropertyCallback().
ResetInternal()
void v8::TryCatch::ResetInternal () [private]
Definition at line 2888 of file api.cc.
                               {
  i::Tagged<i::Object> the_hole = i::ReadOnlyRoots(i_isolate_).the_hole_value();
  exception_ = reinterpret_cast<void*>(the_hole.ptr());
  message_obj_ = reinterpret_cast<void*>(the_hole.ptr());
}
References v8::internal::TaggedImpl< kRefType, StorageType >::ptr().
Referenced by v8::internal::Isolate::CancelTerminateExecution(), and TryCatch().
ReThrow()
v8::Local< v8::Value > v8::TryCatch::ReThrow ()
Throws the exception caught by this TryCatch in a way that avoids it being caught again by this same TryCatch.
As with ThrowException it is illegal to execute any JavaScript operations after calling ReThrow; the caller must return immediately to where the exception is caught.
Definition at line 2834 of file api.cc.
                                     {
  if (!HasCaught()) return {};
  rethrow_ = true;
  return v8::Undefined(reinterpret_cast<v8::Isolate*>(i_isolate_));
}
References v8::Undefined().
Referenced by v8::internal::anonymous_namespace{gc-extension.cc}::Parse(), v8_inspector::V8Console::queryObjectsCallback(), and v8::WriteToFile().
SetCaptureMessage()
void v8::TryCatch::SetCaptureMessage (bool value)
Set whether or not this TryCatch should capture a Message object which holds source information about where the exception occurred.
True by default.
Definition at line 2898 of file api.cc.
{ capture_message_ = value; }
References v8::internal::value.
Referenced by v8::internal::anonymous_namespace{messages.cc}::AppendErrorString(), v8::internal::wasm::WasmEngine::AsyncInstantiate(), v8::internal::SourceTextModule::Evaluate(), v8::internal::MessageFormatter::Format(), v8::internal::anonymous_namespace{execution.cc}::InvokeWithTryCatch(), and v8::internal::MessageHandler::ReportMessage().
SetVerbose()
void v8::TryCatch::SetVerbose (bool value)
Set verbosity of the external exception handler.
By default, exceptions that are caught by an external exception handler are not reported. Call SetVerbose with true on an external exception handler to have exceptions caught by the handler reported as if they were not caught.
Definition at line 2894 of file api.cc.
{ is_verbose_ = value; }
References v8::internal::value.
Referenced by v8::internal::anonymous_namespace{messages.cc}::AppendErrorString(), v8::internal::wasm::WasmEngine::AsyncInstantiate(), v8::Shell::DoHostImportModuleDynamically(), v8::internal::SourceTextModule::Evaluate(), v8::Shell::ExecuteString(), v8::internal::MessageFormatter::Format(), v8::internal::anonymous_namespace{execution.cc}::InvokeWithTryCatch(), v8::Worker::ProcessMessages(), v8::anonymous_namespace{d8.cc}::ProcessMessages(), v8::internal::MessageHandler::ReportMessage(), v8::internal::FinalizationRegistryCleanupTask::RunInternal(), v8::InspectorClient::runMessageLoopOnPause(), v8::AsyncHooks::ShellPromiseHook(), and v8::Shell::TriggerOnProfileEndListener().
StackTrace() [1/2]
MaybeLocal< Value > v8::TryCatch::StackTrace (Local< Context > context) const
Returns the .stack property of the thrown object.
If no .stack property is present or if this try/catch block has not caught an exception, an empty handle is returned.
Definition at line 2862 of file api.cc.
                                                                     {
  if (!HasCaught()) return {};
  return StackTrace(context, Exception());
}
StackTrace() [2/2]
MaybeLocal< Value > v8::TryCatch::StackTrace (Local< Context > context, Local< Value > exception) [static]
Returns the .stack property of an object.
If no .stack property is present an empty handle is returned.
Definition at line 2848 of file api.cc.
                                                                   {
  auto i_exception = Utils::OpenDirectHandle(*exception);
  if (!IsJSObject(*i_exception)) return {};
  PrepareForExecutionScope api_scope{context, RCCId::kAPI_TryCatch_StackTrace};
  i::Isolate* i_isolate = api_scope.i_isolate();
  auto obj = i::Cast<i::JSObject>(i_exception);
  i::DirectHandle<i::String> name = i_isolate->factory()->stack_string();
  Maybe<bool> maybe = i::JSReceiver::HasProperty(i_isolate, obj, name);
  if (maybe != Just(true)) return {};
  return api_scope.EscapeMaybe(
      i::JSReceiver::GetProperty(i_isolate, obj, name));
}
References v8::internal::Isolate::factory(), v8::internal::JSReceiver::GetProperty(), v8::internal::JSReceiver::HasProperty(), v8::Just(), name, and v8::Utils::OpenDirectHandle().
Referenced by v8::Shell::ReportException().
Friends And Related Function Documentation
internal::Isolate
friend class internal::Isolate [friend]
Definition at line 289 of file v8-exception.h.
internal::ThreadLocalTop
friend class internal::ThreadLocalTop [friend]
Definition at line 290 of file v8-exception.h.
Member Data Documentation
can_continue_
bool v8::TryCatch::can_continue_ [private]
Definition at line 285 of file v8-exception.h.
Referenced by v8::internal::Isolate::SetTerminationOnExternalTryCatch().
capture_message_
bool v8::TryCatch::capture_message_ [private]
Definition at line 286 of file v8-exception.h.
Referenced by v8::internal::Isolate::Throw().
exception_
void* v8::TryCatch::exception_ [private]
Definition at line 281 of file v8-exception.h.
Referenced by v8::internal::Isolate::SetTerminationOnExternalTryCatch().
i_isolate_
internal::Isolate* v8::TryCatch::i_isolate_ [private]
Definition at line 279 of file v8-exception.h.
Referenced by TryCatch().
is_verbose_
bool v8::TryCatch::is_verbose_ [private]
Definition at line 284 of file v8-exception.h.
Referenced by v8::internal::Isolate::ReportPendingMessages(), and v8::internal::Isolate::Throw().
js_stack_comparable_address_
internal::Address v8::TryCatch::js_stack_comparable_address_ [private]
Definition at line 283 of file v8-exception.h.
Referenced by TryCatch().
message_obj_
void* v8::TryCatch::message_obj_ [private]
Definition at line 282 of file v8-exception.h.
next_
TryCatch* v8::TryCatch::next_ [private]
Definition at line 280 of file v8-exception.h.
Referenced by v8::internal::Isolate::Iterate(), and v8::internal::Isolate::UnregisterTryCatchHandler().
rethrow_
bool v8::TryCatch::rethrow_ [private]
Definition at line 287 of file v8-exception.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-exception.h
/mnt/V8SourceCode/src/api/api.cc