v8::internal::GlobalHandles::Node Class Reference
Public Types
enum State { FREE = 0
, NORMAL
, WEAK
, NEAR_DEATH
 }
Public Member Functions
Node ()
Node (const Node &)=delete
Node & operator= (const Node &)=delete
const char * label () const
State state () const
void set_state (State state)
bool is_in_young_list () const
void set_in_young_list (bool v)
WeaknessType weakness_type () const
void set_weakness_type (WeaknessType weakness_type)
bool IsWeak () const
bool IsInUse () const
bool IsPhantomResetHandle () const
bool IsWeakOrStrongRetainer () const
bool IsStrongRetainer () const
bool IsWeakRetainer () const
bool has_callback () const
Node * next_free ()
void MakeWeak (void *parameter, WeakCallbackInfo< void >::Callback phantom_callback, v8::WeakCallbackType type)
void MakeWeak (Address **location_addr)
void * ClearWeakness ()
void AnnotateStrongRetainer (const char *label)
void CollectPhantomCallbackData (std::vector< std::pair< Node *, PendingPhantomCallback >> *pending_phantom_callbacks)
void ResetPhantomHandle ()
void MarkAsFree ()
void MarkAsUsed ()
GlobalHandles * global_handles ()
Private Types
using NodeState = base::BitField8< State, 0, 2 >
using IsInYoungList = NodeState::Next< bool, 1 >
using NodeWeaknessType = IsInYoungList::Next< WeaknessType, 2 >
Private Member Functions
void ClearImplFields ()
void CheckNodeIsFreeNodeImpl () const
Private Attributes
WeakCallbackInfo< void >::Callback weak_callback_
Friends
class NodeBase< Node >
Additional Inherited Members
Detailed Description
Definition at line 425 of file global-handles.cc.
Member Typedef Documentation
IsInYoungList
using v8::internal::GlobalHandles::Node::IsInYoungList = NodeState::Next<bool, 1> [private]
Definition at line 590 of file global-handles.cc.
NodeState
using v8::internal::GlobalHandles::Node::NodeState = base::BitField8<State, 0, 2> [private]
Definition at line 586 of file global-handles.cc.
NodeWeaknessType
using v8::internal::GlobalHandles::Node::NodeWeaknessType = IsInYoungList::Next<WeaknessType, 2> [private]
Definition at line 591 of file global-handles.cc.
Member Enumeration Documentation
State
enum v8::internal::GlobalHandles::Node::State
Enumerator
FREE
NORMAL
WEAK
NEAR_DEATH
Definition at line 429 of file global-handles.cc.
             {
    FREE = 0,
    // Strong global handle.
    NORMAL,
    // Flagged as weak and still considered as live.
    WEAK,
    // Temporary state used in GC to sanity check that handles are reset in
    // their first pass callback.
    NEAR_DEATH,
  };
Constructor & Destructor Documentation
Node() [1/2]
v8::internal::GlobalHandles::Node::Node () [inline]
Definition at line 440 of file global-handles.cc.
         {
    static_assert(static_cast<int>(NodeState::kMask) ==
                  Internals::kNodeStateMask);
    static_assert(WEAK == Internals::kNodeStateIsWeakValue);
    set_in_young_list(false);
  }
References v8::base::BitField< T, shift, size, U >::kMask, v8::internal::Internals::kNodeStateIsWeakValue, v8::internal::Internals::kNodeStateMask, set_in_young_list(), and WEAK.
Node() [2/2]
v8::internal::GlobalHandles::Node::Node (const Node &) [delete]
Member Function Documentation
AnnotateStrongRetainer()
void v8::internal::GlobalHandles::Node::AnnotateStrongRetainer (const char * label) [inline]
Definition at line 530 of file global-handles.cc.
                                                 {
    DCHECK_EQ(state(), NORMAL);
    data_.parameter = const_cast<char*>(label);
  }
References v8::internal::NodeBase< GlobalHandles::Node >::data_, DCHECK_EQ, label(), NORMAL, and state().
Referenced by v8::internal::GlobalHandles::AnnotateStrongRetainer().
CheckNodeIsFreeNodeImpl()
void v8::internal::GlobalHandles::Node::CheckNodeIsFreeNodeImpl () const [inline], [private]
Definition at line 579 of file global-handles.cc.
                                       {
    DCHECK_EQ(nullptr, weak_callback_);
    DCHECK(!IsInUse());
  }
References v8::internal::DCHECK(), DCHECK_EQ, IsInUse(), and weak_callback_.
ClearImplFields()
void v8::internal::GlobalHandles::Node::ClearImplFields () [inline], [private]
Definition at line 577 of file global-handles.cc.
{ weak_callback_ = nullptr; }
References weak_callback_.
ClearWeakness()
void* v8::internal::GlobalHandles::Node::ClearWeakness () [inline]
Definition at line 522 of file global-handles.cc.
                        {
    DCHECK(IsInUse());
    void* p = parameter();
    set_state(NORMAL);
    set_parameter(nullptr);
    return p;
  }
References v8::internal::DCHECK(), IsInUse(), NORMAL, v8::internal::NodeBase< GlobalHandles::Node >::parameter, v8::internal::NodeBase< GlobalHandles::Node >::set_parameter(), and set_state().
Referenced by v8::internal::GlobalHandles::ClearWeakness().
CollectPhantomCallbackData()
void v8::internal::GlobalHandles::Node::CollectPhantomCallbackData (std::vector< std::pair< Node *, PendingPhantomCallback >> * pending_phantom_callbacks) [inline]
Definition at line 535 of file global-handles.cc.
                                     {
    DCHECK(weakness_type() == WeaknessType::kCallback ||
           weakness_type() == WeaknessType::kCallbackWithTwoEmbedderFields);
    DCHECK_NOT_NULL(weak_callback_);
    void* embedder_fields[v8::kEmbedderFieldsInWeakCallback] = {nullptr,
                                                                nullptr};
    if (weakness_type() == WeaknessType::kCallbackWithTwoEmbedderFields &&
        IsJSObject(object())) {
      ExtractInternalFields(Cast<JSObject>(object()), embedder_fields,
                            v8::kEmbedderFieldsInWeakCallback);
    }
    // Zap with something dangerous.
    location().store(Tagged<Object>(0xCA11));
    pending_phantom_callbacks->push_back(std::make_pair(
        this,
        PendingPhantomCallback(weak_callback_, parameter(), embedder_fields)));
    DCHECK(IsInUse());
    set_state(NEAR_DEATH);
  }
References v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::anonymous_namespace{global-handles.cc}::ExtractInternalFields(), IsInUse(), v8::internal::kCallback, v8::internal::kCallbackWithTwoEmbedderFields, v8::kEmbedderFieldsInWeakCallback, v8::internal::NodeBase< GlobalHandles::Node >::location(), NEAR_DEATH, v8::internal::NodeBase< GlobalHandles::Node >::parameter, set_state(), v8::internal::FullObjectSlot::store(), weak_callback_, and weakness_type().
Referenced by v8::internal::GlobalHandles::ResetWeakNodeIfDead().
global_handles()
GlobalHandles* v8::internal::GlobalHandles::Node::global_handles () [inline]
Definition at line 571 of file global-handles.cc.
                                  {
    return NodeBlock<Node>::From(this)->global_handles();
  }
References v8::internal::GlobalHandles::NodeBlock< _NodeType >::From(), and v8::internal::GlobalHandles::NodeBlock< _NodeType >::global_handles().
Referenced by v8::internal::GlobalHandles::CopyGlobal().
has_callback()
bool v8::internal::GlobalHandles::Node::has_callback () const [inline]
Definition at line 486 of file global-handles.cc.
{ return weak_callback_ != nullptr; }
References weak_callback_.
is_in_young_list()
bool v8::internal::GlobalHandles::Node::is_in_young_list () const [inline]
Definition at line 460 of file global-handles.cc.
{ return IsInYoungList::decode(flags_); }
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::NodeBase< GlobalHandles::Node >::flags_.
IsInUse()
bool v8::internal::GlobalHandles::Node::IsInUse () const [inline]
Definition at line 472 of file global-handles.cc.
{ return state() != FREE; }
References FREE, and state().
Referenced by CheckNodeIsFreeNodeImpl(), ClearWeakness(), CollectPhantomCallbackData(), and MakeWeak().
IsPhantomResetHandle()
bool v8::internal::GlobalHandles::Node::IsPhantomResetHandle () const [inline]
Definition at line 474 of file global-handles.cc.
                                    {
    return weakness_type() == WeaknessType::kNoCallback;
  }
References v8::internal::kNoCallback, and weakness_type().
Referenced by v8::internal::GlobalHandles::MoveGlobal().
IsStrongRetainer()
bool v8::internal::GlobalHandles::Node::IsStrongRetainer () const [inline]
Definition at line 482 of file global-handles.cc.
{ return state() == NORMAL; }
References NORMAL, and state().
IsWeak()
bool v8::internal::GlobalHandles::Node::IsWeak () const [inline]
Definition at line 470 of file global-handles.cc.
{ return state() == WEAK; }
References state(), and WEAK.
Referenced by v8::internal::GlobalHandles::IsWeak(), and v8::internal::GlobalHandles::MoveGlobal().
IsWeakOrStrongRetainer()
bool v8::internal::GlobalHandles::Node::IsWeakOrStrongRetainer () const [inline]
Definition at line 478 of file global-handles.cc.
                                      {
    return state() == NORMAL || state() == WEAK;
  }
References NORMAL, state(), and WEAK.
IsWeakRetainer()
bool v8::internal::GlobalHandles::Node::IsWeakRetainer () const [inline]
Definition at line 484 of file global-handles.cc.
{ return state() == WEAK; }
References state(), and WEAK.
Referenced by v8::internal::GlobalHandles::ResetWeakNodeIfDead().
label()
const char* v8::internal::GlobalHandles::Node::label () const [inline]
Definition at line 450 of file global-handles.cc.
                            {
    return state() == NORMAL ? reinterpret_cast<char*>(data_.parameter)
                             : nullptr;
  }
References v8::internal::NodeBase< GlobalHandles::Node >::data_, NORMAL, and state().
Referenced by AnnotateStrongRetainer().
MakeWeak() [1/2]
void v8::internal::GlobalHandles::Node::MakeWeak (Address ** location_addr) [inline]
Definition at line 513 of file global-handles.cc.
                                         {
    DCHECK(IsInUse());
    CHECK_NE(object_, kGlobalHandleZapValue);
    set_state(WEAK);
    set_weakness_type(WeaknessType::kNoCallback);
    set_parameter(location_addr);
    weak_callback_ = nullptr;
  }
References CHECK_NE, v8::internal::DCHECK(), IsInUse(), v8::internal::kGlobalHandleZapValue, v8::internal::kNoCallback, v8::internal::NodeBase< GlobalHandles::Node >::object_, v8::internal::NodeBase< GlobalHandles::Node >::set_parameter(), set_state(), set_weakness_type(), WEAK, and weak_callback_.
MakeWeak() [2/2]
void v8::internal::GlobalHandles::Node::MakeWeak (void * parameter, WeakCallbackInfo< void >::Callback phantom_callback, v8::WeakCallbackType type) [inline]
Definition at line 494 of file global-handles.cc.
                                         {
    DCHECK_NOT_NULL(phantom_callback);
    DCHECK(IsInUse());
    CHECK_NE(object_, kGlobalHandleZapValue);
    set_state(WEAK);
    switch (type) {
      case v8::WeakCallbackType::kParameter:
        set_weakness_type(WeaknessType::kCallback);
        break;
      case v8::WeakCallbackType::kInternalFields:
        set_weakness_type(WeaknessType::kCallbackWithTwoEmbedderFields);
        break;
    }
    set_parameter(parameter);
    weak_callback_ = phantom_callback;
  }
References CHECK_NE, v8::internal::DCHECK(), DCHECK_NOT_NULL, IsInUse(), v8::internal::kCallback, v8::internal::kCallbackWithTwoEmbedderFields, v8::internal::kGlobalHandleZapValue, v8::kInternalFields, v8::kParameter, v8::internal::NodeBase< GlobalHandles::Node >::object_, v8::internal::NodeBase< GlobalHandles::Node >::parameter, v8::internal::NodeBase< GlobalHandles::Node >::set_parameter(), set_state(), set_weakness_type(), v8::internal::tracing::type, WEAK, and weak_callback_.
Referenced by v8::internal::GlobalHandles::MakeWeak().
MarkAsFree()
void v8::internal::GlobalHandles::Node::MarkAsFree () [inline]
Definition at line 568 of file global-handles.cc.
{ set_state(FREE); }
References FREE, and set_state().
MarkAsUsed()
void v8::internal::GlobalHandles::Node::MarkAsUsed () [inline]
Definition at line 569 of file global-handles.cc.
{ set_state(NORMAL); }
References NORMAL, and set_state().
next_free()
Node* v8::internal::GlobalHandles::Node::next_free () [inline]
Definition at line 489 of file global-handles.cc.
                    {
    DCHECK_EQ(FREE, state());
    return data_.next_free;
  }
References v8::internal::NodeBase< GlobalHandles::Node >::data_, DCHECK_EQ, FREE, and state().
operator=()
Node& v8::internal::GlobalHandles::Node::operator= (const Node &) [delete]
ResetPhantomHandle()
void v8::internal::GlobalHandles::Node::ResetPhantomHandle () [inline]
Definition at line 560 of file global-handles.cc.
                            {
    DCHECK_EQ(WeaknessType::kNoCallback, weakness_type());
    DCHECK_NULL(weak_callback_);
    Address** handle = reinterpret_cast<Address**>(parameter());
    *handle = nullptr;
    NodeSpace<Node>::Release(this);
  }
References DCHECK_EQ, DCHECK_NULL, v8::internal::NodeBase< GlobalHandles::Node >::handle(), v8::internal::kNoCallback, v8::internal::NodeBase< GlobalHandles::Node >::parameter, v8::internal::GlobalHandles::NodeSpace< NodeType >::Release(), weak_callback_, and weakness_type().
Referenced by v8::internal::GlobalHandles::ResetWeakNodeIfDead().
set_in_young_list()
void v8::internal::GlobalHandles::Node::set_in_young_list (bool v) [inline]
Definition at line 461 of file global-handles.cc.
{ flags_ = IsInYoungList::update(flags_, v); }
References v8::internal::NodeBase< GlobalHandles::Node >::flags_, and v8::base::BitField< T, shift, size, U >::update().
Referenced by v8::internal::GlobalHandles::Create(), and Node().
set_state()
void v8::internal::GlobalHandles::Node::set_state (State state) [inline]
Definition at line 458 of file global-handles.cc.
{ flags_ = NodeState::update(flags_, state); }
References v8::internal::NodeBase< GlobalHandles::Node >::flags_, state(), and v8::base::BitField< T, shift, size, U >::update().
Referenced by ClearWeakness(), CollectPhantomCallbackData(), MakeWeak(), MarkAsFree(), and MarkAsUsed().
set_weakness_type()
void v8::internal::GlobalHandles::Node::set_weakness_type (WeaknessType weakness_type) [inline]
Definition at line 466 of file global-handles.cc.
                                                     {
    flags_ = NodeWeaknessType::update(flags_, weakness_type);
  }
References v8::internal::NodeBase< GlobalHandles::Node >::flags_, v8::base::BitField< T, shift, size, U >::update(), and weakness_type().
Referenced by MakeWeak().
state()
State v8::internal::GlobalHandles::Node::state () const [inline]
Definition at line 457 of file global-handles.cc.
{ return NodeState::decode(flags_); }
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::NodeBase< GlobalHandles::Node >::flags_.
Referenced by AnnotateStrongRetainer(), v8::internal::GlobalHandles::InvokeFirstPassWeakCallbacks(), IsInUse(), IsStrongRetainer(), IsWeak(), IsWeakOrStrongRetainer(), IsWeakRetainer(), label(), next_free(), and set_state().
weakness_type()
WeaknessType v8::internal::GlobalHandles::Node::weakness_type () const [inline]
Definition at line 463 of file global-handles.cc.
                                     {
    return NodeWeaknessType::decode(flags_);
  }
References v8::base::BitField< T, shift, size, U >::decode(), and v8::internal::NodeBase< GlobalHandles::Node >::flags_.
Referenced by CollectPhantomCallbackData(), IsPhantomResetHandle(), ResetPhantomHandle(), v8::internal::GlobalHandles::ResetWeakNodeIfDead(), and set_weakness_type().
Friends And Related Function Documentation
NodeBase< Node >
friend class NodeBase< Node > [friend]
Definition at line 594 of file global-handles.cc.
Member Data Documentation
weak_callback_
WeakCallbackInfo<void>::Callback v8::internal::GlobalHandles::Node::weak_callback_ [private]
Definition at line 594 of file global-handles.cc.
Referenced by CheckNodeIsFreeNodeImpl(), ClearImplFields(), CollectPhantomCallbackData(), has_callback(), MakeWeak(), and ResetPhantomHandle().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/handles/global-handles.cc