v8::internal::compiler::JSForInNextNode Class Reference
#include <js-operator.h>
Public Member Functions
constexpr JSForInNextNode (Node *node)
const ForInParameters & Parameters () const
Additional Inherited Members
Detailed Description
Definition at line 1754 of file js-operator.h.
Constructor & Destructor Documentation
JSForInNextNode()
constexpr v8::internal::compiler::JSForInNextNode::JSForInNextNode (Node * node) [inline], [explicit], [constexpr]
Definition at line 1756 of file js-operator.h.
                                                 : JSNodeWrapperBase(node) {
    DCHECK_EQ(IrOpcode::kJSForInNext, node->opcode());
  }
References DCHECK_EQ, v8::internal::compiler::NodeWrapper::node(), and v8::internal::compiler::Node::opcode().
Member Function Documentation
Parameters()
const ForInParameters& v8::internal::compiler::JSForInNextNode::Parameters () const [inline]
Definition at line 1760 of file js-operator.h.
                                            {
    return ForInParametersOf(node()->op());
  }
References v8::internal::compiler::ForInParametersOf(), and v8::internal::compiler::NodeWrapper::node().
Referenced by v8::internal::compiler::JSTypedLowering::ReduceJSForInNext(), and v8::internal::compiler::JSCallReducer::ReduceObjectPrototypeHasOwnProperty().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/js-operator.h