v8::internal::baseline::SaveAccumulatorScope Class Reference
#include <baseline-compiler.h>
Public Member Functions
SaveAccumulatorScope (BaselineCompiler *compiler, BaselineAssembler *assembler)
~SaveAccumulatorScope ()
Private Attributes
BaselineAssembler * assembler_
Detailed Description
Definition at line 224 of file baseline-compiler.h.
Constructor & Destructor Documentation
SaveAccumulatorScope()
v8::internal::baseline::SaveAccumulatorScope::SaveAccumulatorScope (BaselineCompiler * compiler, BaselineAssembler * assembler)
Definition at line 2486 of file baseline-compiler.cc.
    :
#ifdef DEBUG
      compiler_(compiler),
#endif
      assembler_(assembler) {
#ifdef DEBUG
  DCHECK(!compiler_->effect_state_.accumulator_on_stack);
  compiler_->effect_state_.accumulator_on_stack = true;
#endif // DEBUG
  ASM_CODE_COMMENT(assembler_->masm());
  assembler_->Push(kInterpreterAccumulatorRegister);
}
References ASM_CODE_COMMENT, assembler_, v8::internal::DCHECK(), v8::internal::kInterpreterAccumulatorRegister, v8::internal::baseline::BaselineAssembler::masm(), and v8::internal::baseline::BaselineAssembler::Push().
 SaveAccumulatorScope()
v8::internal::baseline::SaveAccumulatorScope::~SaveAccumulatorScope ()
Definition at line 2501 of file baseline-compiler.cc.
                                            {
#ifdef DEBUG
  DCHECK(compiler_->effect_state_.accumulator_on_stack);
  compiler_->effect_state_.accumulator_on_stack = false;
#endif // DEBUG
  ASM_CODE_COMMENT(assembler_->masm());
  assembler_->Pop(kInterpreterAccumulatorRegister);
}
References ASM_CODE_COMMENT, assembler_, v8::internal::DCHECK(), v8::internal::kInterpreterAccumulatorRegister, v8::internal::baseline::BaselineAssembler::masm(), and v8::internal::baseline::BaselineAssembler::Pop().
Member Data Documentation
assembler_
BaselineAssembler* v8::internal::baseline::SaveAccumulatorScope::assembler_ [private]
Definition at line 235 of file baseline-compiler.h.
Referenced by SaveAccumulatorScope(), and ~SaveAccumulatorScope().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/baseline/baseline-compiler.h
/mnt/V8SourceCode/src/baseline/baseline-compiler.cc