v8::internal::compiler::SpillPlacer Class Reference
#include <spill-placer.h>
Classes
class Entry
Public Member Functions
SpillPlacer (RegisterAllocationData *data, Zone *zone)
~SpillPlacer ()
SpillPlacer (const SpillPlacer &)=delete
SpillPlacer & operator= (const SpillPlacer &)=delete
void Add (TopLevelLiveRange *range)
Private Member Functions
RegisterAllocationData * data () const
int GetOrCreateIndexForLatestVreg (int vreg)
bool IsLatestVreg (int vreg) const
void CommitSpills ()
void ClearData ()
void ExpandBoundsToInclude (RpoNumber block)
void SetSpillRequired (InstructionBlock *block, int vreg, RpoNumber top_start_block)
void SetDefinition (RpoNumber block, int vreg)
void FirstBackwardPass ()
void ForwardPass ()
void SecondBackwardPass ()
void CommitSpill (int vreg, InstructionBlock *predecessor, InstructionBlock *successor)
Private Attributes
RegisterAllocationData * data_
Zone * zone_
Entry * entries_ = nullptr
int * vreg_numbers_ = nullptr
int assigned_indices_ = 0
RpoNumber first_block_ = RpoNumber::Invalid()
RpoNumber last_block_ = RpoNumber::Invalid()
Static Private Attributes
static constexpr int kValueIndicesPerEntry = 64
Detailed Description
Definition at line 76 of file spill-placer.h.
Constructor & Destructor Documentation
SpillPlacer() [1/2]
v8::internal::compiler::SpillPlacer::SpillPlacer (RegisterAllocationData * data, Zone * zone)
Definition at line 14 of file spill-placer.cc.
    : data_(data), zone_(zone) {}
 SpillPlacer()
v8::internal::compiler::SpillPlacer::~SpillPlacer ()
Definition at line 17 of file spill-placer.cc.
                          {
  if (assigned_indices_ > 0) {
    CommitSpills();
  }
}
References assigned_indices_, and CommitSpills().
SpillPlacer() [2/2]
v8::internal::compiler::SpillPlacer::SpillPlacer (const SpillPlacer &) [delete]
Member Function Documentation
Add()
void v8::internal::compiler::SpillPlacer::Add (TopLevelLiveRange * range)
Definition at line 23 of file spill-placer.cc.
                                              {
  DCHECK(range->HasGeneralSpillRange());
  InstructionOperand spill_operand = range->GetSpillRangeOperand();
  range->FilterSpillMoves(data(), spill_operand);
  InstructionSequence* code = data_->code();
  InstructionBlock* top_start_block =
      code->GetInstructionBlock(range->Start().ToInstructionIndex());
  RpoNumber top_start_block_number = top_start_block->rpo_number();
  // Check for several cases where spilling at the definition is best.
  // - The value is already moved on-stack somehow so the list of insertion
  // locations for spilling at the definition is empty.
  // - If the first LiveRange is spilled, then there's no sense in doing
  // anything other than spilling at the definition.
  // - If the value is defined in a deferred block, then the logic to select
  // the earliest deferred block as the insertion point would cause
  // incorrect behavior, so the value must be spilled at the definition.
  // - We haven't seen any indication of performance improvements from seeking
  // optimal spilling positions except on loop-top phi values, so spill
  // any value that isn't a loop-top phi at the definition to avoid
  // increasing the code size for no benefit.
  if (range->GetSpillMoveInsertionLocations(data()) == nullptr ||
      range->spilled() || top_start_block->IsDeferred() ||
      (!v8_flags.stress_turbo_late_spilling && !range->is_loop_phi())) {
    range->CommitSpillMoves(data(), spill_operand);
    return;
  }
  // Iterate through the range and mark every block that needs the value to be
  // spilled.
  for (const LiveRange* child = range; child != nullptr;
       child = child->next()) {
    if (child->spilled()) {
      // Add every block that contains part of this live range.
      for (const UseInterval& interval : child->intervals()) {
        RpoNumber start_block =
            code->GetInstructionBlock(interval.start().ToInstructionIndex())
                ->rpo_number();
        if (start_block == top_start_block_number) {
          // Can't do late spilling if the first spill is within the
          // definition block.
          range->CommitSpillMoves(data(), spill_operand);
          // Verify that we never added any data for this range to the table.
          DCHECK(!IsLatestVreg(range->vreg()));
          return;
        }
        LifetimePosition end = interval.end();
        int end_instruction = end.ToInstructionIndex();
        // The end position is exclusive, so an end position exactly on a block
        // boundary indicates that the range applies only to the prior block.
        if (data()->IsBlockBoundary(end)) {
          --end_instruction;
        }
        RpoNumber end_block =
            code->GetInstructionBlock(end_instruction)->rpo_number();
        while (start_block <= end_block) {
          SetSpillRequired(code->InstructionBlockAt(start_block), range->vreg(),
                           top_start_block_number);
          start_block = start_block.Next();
        }
      }
    } else {
      // Add every block that contains a use which requires the on-stack value.
      for (const UsePosition* pos : child->positions()) {
        if (pos->type() != UsePositionType::kRequiresSlot) continue;
        InstructionBlock* block =
            code->GetInstructionBlock(pos->pos().ToInstructionIndex());
        RpoNumber block_number = block->rpo_number();
        if (block_number == top_start_block_number) {
          // Can't do late spilling if the first spill is within the
          // definition block.
          range->CommitSpillMoves(data(), spill_operand);
          // Verify that we never added any data for this range to the table.
          DCHECK(!IsLatestVreg(range->vreg()));
          return;
        }
        SetSpillRequired(block, range->vreg(), top_start_block_number);
      }
    }
  }
  // If we haven't yet marked anything for this range, then it never needs to
  // spill at all.
  if (!IsLatestVreg(range->vreg())) {
    range->SetLateSpillingSelected(true);
    return;
  }
  SetDefinition(top_start_block_number, range->vreg());
}
References v8::internal::compiler::RegisterAllocationData::code(), code, v8::internal::compiler::TopLevelLiveRange::CommitSpillMoves(), data(), data_, v8::internal::DCHECK(), v8::internal::compiler::end(), v8::internal::compiler::TopLevelLiveRange::FilterSpillMoves(), v8::internal::compiler::TopLevelLiveRange::GetSpillMoveInsertionLocations(), v8::internal::compiler::TopLevelLiveRange::GetSpillRangeOperand(), v8::internal::compiler::TopLevelLiveRange::HasGeneralSpillRange(), v8::internal::compiler::TopLevelLiveRange::is_loop_phi(), v8::internal::compiler::InstructionBlock::IsDeferred(), IsLatestVreg(), v8::internal::compiler::kRequiresSlot, v8::internal::compiler::RpoNumber::Next(), v8::internal::compiler::LiveRange::next(), v8::internal::compiler::InstructionBlock::rpo_number(), SetDefinition(), v8::internal::compiler::TopLevelLiveRange::SetLateSpillingSelected(), SetSpillRequired(), v8::internal::compiler::LiveRange::spilled(), v8::internal::compiler::LiveRange::Start(), v8::internal::compiler::LifetimePosition::ToInstructionIndex(), v8::internal::v8_flags, and v8::internal::compiler::TopLevelLiveRange::vreg().
Referenced by v8::internal::compiler::LiveRangeConnector::ResolveControlFlow().
ClearData()
void v8::internal::compiler::SpillPlacer::ClearData () [private]
Definition at line 237 of file spill-placer.cc.
                            {
  assigned_indices_ = 0;
  for (int i = 0; i < data()->code()->InstructionBlockCount(); ++i) {
    new (&entries_[i]) Entry();
  }
  first_block_ = RpoNumber::Invalid();
  last_block_ = RpoNumber::Invalid();
}
References assigned_indices_, v8::internal::compiler::RegisterAllocationData::code(), data(), entries_, first_block_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::InstructionSequence::InstructionBlockCount(), v8::internal::compiler::RpoNumber::Invalid(), and last_block_.
Referenced by GetOrCreateIndexForLatestVreg().
CommitSpill()
void v8::internal::compiler::SpillPlacer::CommitSpill (int vreg, InstructionBlock * predecessor, InstructionBlock * successor) [private]
Definition at line 462 of file spill-placer.cc.
                                                           {
  TopLevelLiveRange* live_range = data()->live_ranges()[vreg];
  LifetimePosition pred_end = LifetimePosition::InstructionFromInstructionIndex(
      predecessor->last_instruction_index());
  LiveRange* child_range = live_range->GetChildCovers(pred_end);
  DCHECK_NOT_NULL(child_range);
  InstructionOperand pred_op = child_range->GetAssignedOperand();
  DCHECK(pred_op.IsAnyRegister());
  DCHECK_EQ(successor->PredecessorCount(), 1);
  data()->AddGapMove(successor->first_instruction_index(),
                     Instruction::GapPosition::START, pred_op,
                     live_range->GetSpillRangeOperand());
  successor->mark_needs_frame();
  live_range->SetLateSpillingSelected(true);
}
References v8::internal::compiler::RegisterAllocationData::AddGapMove(), data(), v8::internal::DCHECK(), DCHECK_EQ, DCHECK_NOT_NULL, v8::internal::compiler::InstructionBlock::first_instruction_index(), v8::internal::compiler::LiveRange::GetAssignedOperand(), v8::internal::compiler::TopLevelLiveRange::GetChildCovers(), v8::internal::compiler::TopLevelLiveRange::GetSpillRangeOperand(), v8::internal::compiler::LifetimePosition::InstructionFromInstructionIndex(), v8::internal::compiler::InstructionOperand::IsAnyRegister(), v8::internal::compiler::InstructionBlock::last_instruction_index(), v8::internal::compiler::RegisterAllocationData::live_ranges(), v8::internal::compiler::InstructionBlock::mark_needs_frame(), v8::internal::compiler::InstructionBlock::PredecessorCount(), and v8::internal::compiler::TopLevelLiveRange::SetLateSpillingSelected().
Referenced by SecondBackwardPass().
CommitSpills()
void v8::internal::compiler::SpillPlacer::CommitSpills () [private]
Definition at line 231 of file spill-placer.cc.
                               {
  FirstBackwardPass();
  ForwardPass();
  SecondBackwardPass();
}
References FirstBackwardPass(), ForwardPass(), and SecondBackwardPass().
Referenced by GetOrCreateIndexForLatestVreg(), and ~SpillPlacer().
data()
RegisterAllocationData* v8::internal::compiler::SpillPlacer::data () const [inline], [private]
Definition at line 94 of file spill-placer.h.
{ return data_; }
References data_.
Referenced by Add(), ClearData(), CommitSpill(), FirstBackwardPass(), ForwardPass(), GetOrCreateIndexForLatestVreg(), SecondBackwardPass(), SetSpillRequired(), and v8::internal::compiler::SpillPlacer::Entry::UpdateBitDataWithMask().
ExpandBoundsToInclude()
void v8::internal::compiler::SpillPlacer::ExpandBoundsToInclude (RpoNumber block) [private]
Definition at line 246 of file spill-placer.cc.
                                                       {
  if (!first_block_.IsValid()) {
    DCHECK(!last_block_.IsValid());
    first_block_ = block;
    last_block_ = block;
  } else {
    if (first_block_ > block) {
      first_block_ = block;
    }
    if (last_block_ < block) {
      last_block_ = block;
    }
  }
}
References v8::internal::DCHECK(), first_block_, v8::internal::compiler::RpoNumber::IsValid(), and last_block_.
Referenced by SetDefinition(), and SetSpillRequired().
FirstBackwardPass()
void v8::internal::compiler::SpillPlacer::FirstBackwardPass () [private]
Definition at line 285 of file spill-placer.cc.
                                    {
  InstructionSequence* code = data()->code();
  for (int i = last_block_.ToInt(); i >= first_block_.ToInt(); --i) {
    RpoNumber block_id = RpoNumber::FromInt(i);
    InstructionBlock* block = code->instruction_blocks()[i];
    Entry& entry = entries_[i];
    // State that will be accumulated from successors.
    uint64_t spill_required_in_non_deferred_successor = 0;
    uint64_t spill_required_in_deferred_successor = 0;
    for (RpoNumber successor_id : block->successors()) {
      // Ignore loop back-edges.
      if (successor_id <= block_id) continue;
      InstructionBlock* successor = code->InstructionBlockAt(successor_id);
      const Entry& successor_entry = entries_[successor_id.ToSize()];
      if (successor->IsDeferred()) {
        spill_required_in_deferred_successor |= successor_entry.SpillRequired();
      } else {
        spill_required_in_non_deferred_successor |=
            successor_entry.SpillRequired();
      }
      spill_required_in_deferred_successor |=
          successor_entry.SpillRequiredInDeferredSuccessor();
      spill_required_in_non_deferred_successor |=
          successor_entry.SpillRequiredInNonDeferredSuccessor();
    }
    // Starting state of the current block.
    uint64_t defs = entry.Definition();
    uint64_t needs_spill = entry.SpillRequired();
    // Info about successors doesn't get to override existing info about
    // definitions and spills required by this block itself.
    spill_required_in_deferred_successor &= ~(defs | needs_spill);
    spill_required_in_non_deferred_successor &= ~(defs | needs_spill);
    entry.SetSpillRequiredInDeferredSuccessor(
        spill_required_in_deferred_successor);
    entry.SetSpillRequiredInNonDeferredSuccessor(
        spill_required_in_non_deferred_successor);
  }
}
References v8::internal::compiler::RegisterAllocationData::code(), code, data(), v8::internal::compiler::SpillPlacer::Entry::Definition(), entries_, first_block_, v8::internal::compiler::RpoNumber::FromInt(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::InstructionBlock::IsDeferred(), last_block_, v8::internal::compiler::SpillPlacer::Entry::SetSpillRequiredInDeferredSuccessor(), v8::internal::compiler::SpillPlacer::Entry::SetSpillRequiredInNonDeferredSuccessor(), v8::internal::compiler::SpillPlacer::Entry::SpillRequired(), v8::internal::compiler::SpillPlacer::Entry::SpillRequiredInDeferredSuccessor(), v8::internal::compiler::SpillPlacer::Entry::SpillRequiredInNonDeferredSuccessor(), v8::internal::compiler::InstructionBlock::successors(), and v8::internal::compiler::RpoNumber::ToInt().
Referenced by CommitSpills().
ForwardPass()
void v8::internal::compiler::SpillPlacer::ForwardPass () [private]
Definition at line 332 of file spill-placer.cc.
                              {
  InstructionSequence* code = data()->code();
  for (int i = first_block_.ToInt(); i <= last_block_.ToInt(); ++i) {
    RpoNumber block_id = RpoNumber::FromInt(i);
    InstructionBlock* block = code->instruction_blocks()[i];
    // Deferred blocks don't need to participate in the forward pass, because
    // their spills all get pulled forward to the earliest possible deferred
    // block (where a non-deferred block jumps to a deferred block), and
    // decisions about spill requirements for non-deferred blocks don't take
    // deferred blocks into account.
    if (block->IsDeferred()) continue;
    Entry& entry = entries_[i];
    // State that will be accumulated from predecessors.
    uint64_t spill_required_in_non_deferred_predecessor = 0;
    uint64_t spill_required_in_all_non_deferred_predecessors =
        static_cast<uint64_t>(int64_t{-1});
    for (RpoNumber predecessor_id : block->predecessors()) {
      // Ignore loop back-edges.
      if (predecessor_id >= block_id) continue;
      InstructionBlock* predecessor = code->InstructionBlockAt(predecessor_id);
      if (predecessor->IsDeferred()) continue;
      const Entry& predecessor_entry = entries_[predecessor_id.ToSize()];
      spill_required_in_non_deferred_predecessor |=
          predecessor_entry.SpillRequired();
      spill_required_in_all_non_deferred_predecessors &=
          predecessor_entry.SpillRequired();
    }
    // Starting state of the current block.
    uint64_t spill_required_in_non_deferred_successor =
        entry.SpillRequiredInNonDeferredSuccessor();
    uint64_t spill_required_in_any_successor =
        spill_required_in_non_deferred_successor |
        entry.SpillRequiredInDeferredSuccessor();
    // If all of the predecessors agree that a spill is required, then a
    // spill is required. Note that we don't set anything for values that
    // currently have no markings in this block, to avoid pushing data too
    // far down the graph and confusing the next backward pass.
    entry.SetSpillRequired(spill_required_in_any_successor &
                           spill_required_in_non_deferred_predecessor &
                           spill_required_in_all_non_deferred_predecessors);
    // If only some of the predecessors require a spill, but some successor
    // of this block also requires a spill, then this merge point requires a
    // spill. This ensures that no control-flow path through non-deferred
    // blocks ever has to spill twice.
    entry.SetSpillRequired(spill_required_in_non_deferred_successor &
                           spill_required_in_non_deferred_predecessor);
  }
}
References v8::internal::compiler::RegisterAllocationData::code(), code, data(), entries_, first_block_, v8::internal::compiler::RpoNumber::FromInt(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::InstructionBlock::IsDeferred(), last_block_, v8::internal::compiler::InstructionBlock::predecessors(), v8::internal::compiler::SpillPlacer::Entry::SetSpillRequired(), v8::internal::compiler::SpillPlacer::Entry::SpillRequired(), v8::internal::compiler::SpillPlacer::Entry::SpillRequiredInDeferredSuccessor(), v8::internal::compiler::SpillPlacer::Entry::SpillRequiredInNonDeferredSuccessor(), and v8::internal::compiler::RpoNumber::ToInt().
Referenced by CommitSpills().
GetOrCreateIndexForLatestVreg()
int v8::internal::compiler::SpillPlacer::GetOrCreateIndexForLatestVreg (int vreg) [private]
Definition at line 202 of file spill-placer.cc.
                                                       {
  DCHECK_LE(assigned_indices_, kValueIndicesPerEntry);
  // If this vreg isn't yet the last one in the list, then add it.
  if (!IsLatestVreg(vreg)) {
    if (vreg_numbers_ == nullptr) {
      DCHECK_EQ(assigned_indices_, 0);
      DCHECK_EQ(entries_, nullptr);
      // We lazily allocate these arrays because many functions don't have any
      // values that use SpillPlacer.
      entries_ = zone_->AllocateArray<Entry>(
          data()->code()->instruction_blocks().size());
      for (size_t i = 0; i < data()->code()->instruction_blocks().size(); ++i) {
        new (&entries_[i]) Entry();
      }
      vreg_numbers_ = zone_->AllocateArray<int>(kValueIndicesPerEntry);
    }
    if (assigned_indices_ == kValueIndicesPerEntry) {
      // The table is full; commit the current set of values and clear it.
      CommitSpills();
      ClearData();
    }
    vreg_numbers_[assigned_indices_] = vreg;
    ++assigned_indices_;
  }
  return assigned_indices_ - 1;
}
References v8::internal::Zone::AllocateArray(), assigned_indices_, ClearData(), v8::internal::compiler::RegisterAllocationData::code(), CommitSpills(), data(), DCHECK_EQ, DCHECK_LE, entries_, v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::InstructionSequence::instruction_blocks(), IsLatestVreg(), kValueIndicesPerEntry, v8::internal::ZoneVector< T >::size(), vreg_numbers_, and zone_.
Referenced by SetDefinition(), and SetSpillRequired().
IsLatestVreg()
bool v8::internal::compiler::SpillPlacer::IsLatestVreg (int vreg) const [inline], [private]
Definition at line 101 of file spill-placer.h.
                                    {
    return assigned_indices_ > 0 &&
           vreg_numbers_[assigned_indices_ - 1] == vreg;
  }
References assigned_indices_, and vreg_numbers_.
Referenced by Add(), and GetOrCreateIndexForLatestVreg().
operator=()
SpillPlacer& v8::internal::compiler::SpillPlacer::operator= (const SpillPlacer &) [delete]
SecondBackwardPass()
void v8::internal::compiler::SpillPlacer::SecondBackwardPass () [private]
Definition at line 389 of file spill-placer.cc.
                                     {
  InstructionSequence* code = data()->code();
  for (int i = last_block_.ToInt(); i >= first_block_.ToInt(); --i) {
    RpoNumber block_id = RpoNumber::FromInt(i);
    InstructionBlock* block = code->instruction_blocks()[i];
    Entry& entry = entries_[i];
    // State that will be accumulated from successors.
    uint64_t spill_required_in_non_deferred_successor = 0;
    uint64_t spill_required_in_deferred_successor = 0;
    uint64_t spill_required_in_all_non_deferred_successors =
        static_cast<uint64_t>(int64_t{-1});
    for (RpoNumber successor_id : block->successors()) {
      // Ignore loop back-edges.
      if (successor_id <= block_id) continue;
      InstructionBlock* successor = code->InstructionBlockAt(successor_id);
      const Entry& successor_entry = entries_[successor_id.ToSize()];
      if (successor->IsDeferred()) {
        spill_required_in_deferred_successor |= successor_entry.SpillRequired();
      } else {
        spill_required_in_non_deferred_successor |=
            successor_entry.SpillRequired();
        spill_required_in_all_non_deferred_successors &=
            successor_entry.SpillRequired();
      }
    }
    // Starting state of the current block.
    uint64_t defs = entry.Definition();
    // If all of the successors of a definition need the value to be
    // spilled, then the value should be spilled at the definition.
    uint64_t spill_at_def = defs & spill_required_in_non_deferred_successor &
                            spill_required_in_all_non_deferred_successors;
    for (int index_to_spill : base::bits::IterateBits(spill_at_def)) {
      int vreg_to_spill = vreg_numbers_[index_to_spill];
      TopLevelLiveRange* top = data()->live_ranges()[vreg_to_spill];
      top->CommitSpillMoves(data(), top->GetSpillRangeOperand());
    }
    if (block->IsDeferred()) {
      DCHECK_EQ(defs, 0);
      // Any deferred successor needing a spill is sufficient to make the
      // current block need a spill.
      entry.SetSpillRequired(spill_required_in_deferred_successor);
    }
    // Propagate data upward if there are non-deferred successors and they
    // all need a spill, regardless of whether the current block is
    // deferred.
    entry.SetSpillRequired(~defs & spill_required_in_non_deferred_successor &
                           spill_required_in_all_non_deferred_successors);
    // Iterate the successors again to find out which ones require spills at
    // their beginnings, and insert those spills.
    for (RpoNumber successor_id : block->successors()) {
      // Ignore loop back-edges.
      if (successor_id <= block_id) continue;
      InstructionBlock* successor = code->InstructionBlockAt(successor_id);
      const Entry& successor_entry = entries_[successor_id.ToSize()];
      for (int index_to_spill :
           base::bits::IterateBits(successor_entry.SpillRequired() &
                                   ~entry.SpillRequired() & ~spill_at_def)) {
        CommitSpill(vreg_numbers_[index_to_spill], block, successor);
      }
    }
  }
}
References v8::internal::compiler::RegisterAllocationData::code(), code, CommitSpill(), v8::internal::compiler::TopLevelLiveRange::CommitSpillMoves(), data(), DCHECK_EQ, v8::internal::compiler::SpillPlacer::Entry::Definition(), entries_, first_block_, v8::internal::compiler::RpoNumber::FromInt(), v8::internal::compiler::TopLevelLiveRange::GetSpillRangeOperand(), v8::internal::anonymous_namespace{json-stringifier.cc}::i, v8::internal::compiler::InstructionBlock::IsDeferred(), v8::base::bits::IterateBits(), last_block_, v8::internal::compiler::RegisterAllocationData::live_ranges(), v8::internal::compiler::SpillPlacer::Entry::SetSpillRequired(), v8::internal::compiler::SpillPlacer::Entry::SpillRequired(), v8::internal::compiler::InstructionBlock::successors(), v8::internal::compiler::RpoNumber::ToInt(), and vreg_numbers_.
Referenced by CommitSpills().
SetDefinition()
void v8::internal::compiler::SpillPlacer::SetDefinition (RpoNumber block, int vreg) [private]
Definition at line 279 of file spill-placer.cc.
                                                         {
  int value_index = GetOrCreateIndexForLatestVreg(vreg);
  entries_[block.ToSize()].SetDefinitionSingleValue(value_index);
  ExpandBoundsToInclude(block);
}
References entries_, ExpandBoundsToInclude(), GetOrCreateIndexForLatestVreg(), v8::internal::compiler::SpillPlacer::Entry::SetDefinitionSingleValue(), and v8::internal::compiler::RpoNumber::ToSize().
Referenced by Add().
SetSpillRequired()
void v8::internal::compiler::SpillPlacer::SetSpillRequired (InstructionBlock * block, int vreg, RpoNumber top_start_block) [private]
Definition at line 261 of file spill-placer.cc.
                                                              {
  // Spilling in loops is bad, so if the block is non-deferred and nested
  // within a loop, and the definition is before that loop, then mark the loop
  // top instead. Of course we must find the outermost such loop.
  if (!block->IsDeferred()) {
    while (block->loop_header().IsValid() &&
           block->loop_header() > top_start_block) {
      block = data()->code()->InstructionBlockAt(block->loop_header());
    }
  }
  int value_index = GetOrCreateIndexForLatestVreg(vreg);
  entries_[block->rpo_number().ToSize()].SetSpillRequiredSingleValue(
      value_index);
  ExpandBoundsToInclude(block->rpo_number());
}
References v8::internal::compiler::RegisterAllocationData::code(), data(), entries_, ExpandBoundsToInclude(), GetOrCreateIndexForLatestVreg(), v8::internal::compiler::InstructionSequence::InstructionBlockAt(), v8::internal::compiler::InstructionBlock::IsDeferred(), v8::internal::compiler::RpoNumber::IsValid(), v8::internal::compiler::InstructionBlock::loop_header(), v8::internal::compiler::InstructionBlock::rpo_number(), v8::internal::compiler::SpillPlacer::Entry::SetSpillRequiredSingleValue(), and v8::internal::compiler::RpoNumber::ToSize().
Referenced by Add().
Member Data Documentation
assigned_indices_
int v8::internal::compiler::SpillPlacer::assigned_indices_ = 0 [private]
Definition at line 155 of file spill-placer.h.
Referenced by ClearData(), GetOrCreateIndexForLatestVreg(), IsLatestVreg(), and ~SpillPlacer().
data_
RegisterAllocationData* v8::internal::compiler::SpillPlacer::data_ [private]
Definition at line 145 of file spill-placer.h.
Referenced by Add(), and data().
entries_
Entry* v8::internal::compiler::SpillPlacer::entries_ = nullptr [private]
Definition at line 149 of file spill-placer.h.
Referenced by ClearData(), FirstBackwardPass(), ForwardPass(), GetOrCreateIndexForLatestVreg(), SecondBackwardPass(), SetDefinition(), and SetSpillRequired().
first_block_
RpoNumber v8::internal::compiler::SpillPlacer::first_block_ = RpoNumber::Invalid() [private]
Definition at line 160 of file spill-placer.h.
Referenced by ClearData(), ExpandBoundsToInclude(), FirstBackwardPass(), ForwardPass(), and SecondBackwardPass().
kValueIndicesPerEntry
constexpr int v8::internal::compiler::SpillPlacer::kValueIndicesPerEntry = 64 [static], [constexpr], [private]
Definition at line 142 of file spill-placer.h.
Referenced by GetOrCreateIndexForLatestVreg(), v8::internal::compiler::SpillPlacer::Entry::SetDefinitionSingleValue(), and v8::internal::compiler::SpillPlacer::Entry::SetSpillRequiredSingleValue().
last_block_
RpoNumber v8::internal::compiler::SpillPlacer::last_block_ = RpoNumber::Invalid() [private]
Definition at line 161 of file spill-placer.h.
Referenced by ClearData(), ExpandBoundsToInclude(), FirstBackwardPass(), ForwardPass(), and SecondBackwardPass().
vreg_numbers_
int* v8::internal::compiler::SpillPlacer::vreg_numbers_ = nullptr [private]
Definition at line 152 of file spill-placer.h.
Referenced by GetOrCreateIndexForLatestVreg(), IsLatestVreg(), and SecondBackwardPass().
zone_
Zone* v8::internal::compiler::SpillPlacer::zone_ [private]
Definition at line 146 of file spill-placer.h.
Referenced by GetOrCreateIndexForLatestVreg().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/compiler/backend/spill-placer.h
/mnt/V8SourceCode/src/compiler/backend/spill-placer.cc