v8::internal::compiler::PPCOperandConverter Class Reference
Public Member Functions
PPCOperandConverter (CodeGenerator *gen, Instruction *instr)
size_t OutputCount ()
RCBit OutputRCBit () const
bool CompareLogical () const
Operand InputImmediate (size_t index)
MemOperand MemoryOperand (AddressingMode *mode, size_t *first_index)
MemOperand MemoryOperand (AddressingMode *mode=NULL, size_t first_index=0)
MemOperand ToMemOperand (InstructionOperand *op) const
MemOperand SlotToMemOperand (int slot) const
Additional Inherited Members
Detailed Description
Definition at line 32 of file code-generator-ppc.cc.
Constructor & Destructor Documentation
PPCOperandConverter()
v8::internal::compiler::PPCOperandConverter::PPCOperandConverter (CodeGenerator * gen, Instruction * instr) [inline]
Definition at line 34 of file code-generator-ppc.cc.
      : InstructionOperandConverter(gen, instr) {}
Member Function Documentation
CompareLogical()
bool v8::internal::compiler::PPCOperandConverter::CompareLogical () const [inline]
Definition at line 55 of file code-generator-ppc.cc.
                              {
    switch (instr_->flags_condition()) {
      case kUnsignedLessThan:
      case kUnsignedGreaterThanOrEqual:
      case kUnsignedLessThanOrEqual:
      case kUnsignedGreaterThan:
        return true;
      default:
        return false;
    }
    UNREACHABLE();
  }
References v8::internal::compiler::Instruction::flags_condition(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::kUnsignedGreaterThan, v8::internal::compiler::kUnsignedGreaterThanOrEqual, v8::internal::compiler::kUnsignedLessThan, v8::internal::compiler::kUnsignedLessThanOrEqual, and v8::internal::UNREACHABLE().
InputImmediate()
Operand v8::internal::compiler::PPCOperandConverter::InputImmediate (size_t index) [inline]
Definition at line 68 of file code-generator-ppc.cc.
                                       {
    Constant constant = ToConstant(instr_->InputAt(index));
    switch (constant.type()) {
      case Constant::kInt32:
        return Operand(constant.ToInt32());
      case Constant::kFloat32:
        return Operand::EmbeddedNumber(constant.ToFloat32());
      case Constant::kFloat64:
        return Operand::EmbeddedNumber(constant.ToFloat64().value());
      case Constant::kInt64:
        return Operand(constant.ToInt64());
      case Constant::kExternalReference:
        return Operand(constant.ToExternalReference());
      case Constant::kCompressedHeapObject: {
        RootIndex root_index;
        if (gen_->isolate()->roots_table().IsRootHandle(constant.ToHeapObject(),
                                                        &root_index)) {
          CHECK(COMPRESS_POINTERS_BOOL);
          CHECK(V8_STATIC_ROOTS_BOOL || !gen_->isolate()->bootstrapper());
          Tagged_t ptr =
              MacroAssemblerBase::ReadOnlyRootPtr(root_index, gen_->isolate());
          return Operand(ptr);
        }
        return Operand(constant.ToHeapObject());
      }
      case Constant::kHeapObject:
      case Constant::kRpoNumber:
        break;
    }
    UNREACHABLE();
  }
References v8::internal::Isolate::bootstrapper(), CHECK, COMPRESS_POINTERS_BOOL, v8::internal::Operand::EmbeddedNumber(), v8::internal::compiler::InstructionOperandConverter::gen_, v8::internal::index, v8::internal::compiler::Instruction::InputAt(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::CodeGenerator::isolate(), v8::internal::RootsTable::IsRootHandle(), v8::internal::compiler::Constant::kCompressedHeapObject, v8::internal::compiler::Constant::kExternalReference, v8::internal::compiler::Constant::kFloat32, v8::internal::compiler::Constant::kFloat64, v8::internal::compiler::Constant::kHeapObject, v8::internal::compiler::Constant::kInt32, v8::internal::compiler::Constant::kInt64, v8::internal::compiler::Constant::kRpoNumber, v8::internal::MacroAssemblerBase::ReadOnlyRootPtr(), v8::internal::Isolate::roots_table(), v8::internal::compiler::InstructionOperandConverter::ToConstant(), v8::internal::compiler::Constant::ToExternalReference(), v8::internal::compiler::Constant::ToFloat32(), v8::internal::compiler::Constant::ToFloat64(), v8::internal::compiler::Constant::ToHeapObject(), v8::internal::compiler::Constant::ToInt32(), v8::internal::compiler::Constant::ToInt64(), v8::internal::compiler::Constant::type(), v8::internal::UNREACHABLE(), V8_STATIC_ROOTS_BOOL, and v8::base::Double::value().
MemoryOperand() [1/2]
MemOperand v8::internal::compiler::PPCOperandConverter::MemoryOperand (AddressingMode * mode, size_t * first_index) [inline]
Definition at line 100 of file code-generator-ppc.cc.
                                                                      {
    const size_t index = *first_index;
    AddressingMode addr_mode = AddressingModeField::decode(instr_->opcode());
    if (mode) *mode = addr_mode;
    switch (addr_mode) {
      case kMode_None:
        break;
      case kMode_MRI:
        *first_index += 2;
        return MemOperand(InputRegister(index + 0), InputInt64(index + 1));
      case kMode_MRR:
        *first_index += 2;
        return MemOperand(InputRegister(index + 0), InputRegister(index + 1));
      case kMode_Root:
        *first_index += 1;
        return MemOperand(kRootRegister, InputRegister(index));
    }
    UNREACHABLE();
  }
References v8::base::BitField< T, shift, size, U >::decode(), v8::internal::index, v8::internal::compiler::InstructionOperandConverter::InputInt64(), v8::internal::compiler::InstructionOperandConverter::InputRegister(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::kRootRegister, mode(), v8::internal::compiler::Instruction::opcode(), and v8::internal::UNREACHABLE().
Referenced by MemoryOperand().
MemoryOperand() [2/2]
MemOperand v8::internal::compiler::PPCOperandConverter::MemoryOperand (AddressingMode * mode = NULL, size_t first_index = 0) [inline]
Definition at line 120 of file code-generator-ppc.cc.
                                                   {
    return MemoryOperand(mode, &first_index);
  }
References MemoryOperand(), and mode().
OutputCount()
size_t v8::internal::compiler::PPCOperandConverter::OutputCount () [inline]
Definition at line 37 of file code-generator-ppc.cc.
{ return instr_->OutputCount(); }
References v8::internal::compiler::InstructionOperandConverter::instr_, and v8::internal::compiler::Instruction::OutputCount().
OutputRCBit()
RCBit v8::internal::compiler::PPCOperandConverter::OutputRCBit () const [inline]
Definition at line 39 of file code-generator-ppc.cc.
                            {
    switch (instr_->flags_mode()) {
      case kFlags_branch:
      case kFlags_conditional_branch:
      case kFlags_deoptimize:
      case kFlags_set:
      case kFlags_conditional_set:
      case kFlags_trap:
      case kFlags_select:
        return SetRC;
      case kFlags_none:
        return LeaveRC;
    }
    UNREACHABLE();
  }
References v8::internal::compiler::Instruction::flags_mode(), v8::internal::compiler::InstructionOperandConverter::instr_, v8::internal::compiler::kFlags_branch, v8::internal::compiler::kFlags_conditional_branch, v8::internal::compiler::kFlags_conditional_set, v8::internal::compiler::kFlags_deoptimize, v8::internal::compiler::kFlags_none, v8::internal::compiler::kFlags_select, v8::internal::compiler::kFlags_set, v8::internal::compiler::kFlags_trap, v8::internal::LeaveRC, v8::internal::SetRC, and v8::internal::UNREACHABLE().
SlotToMemOperand()
MemOperand v8::internal::compiler::PPCOperandConverter::SlotToMemOperand (int slot) const [inline]
Definition at line 131 of file code-generator-ppc.cc.
                                              {
    FrameOffset offset = frame_access_state()->GetFrameOffset(slot);
    return MemOperand(offset.from_stack_pointer() ? sp : fp, offset.offset());
  }
References v8::internal::compiler::InstructionOperandConverter::frame_access_state(), v8::internal::compiler::FrameOffset::from_stack_pointer(), v8::internal::compiler::FrameAccessState::GetFrameOffset(), and v8::internal::compiler::FrameOffset::offset().
Referenced by ToMemOperand().
ToMemOperand()
MemOperand v8::internal::compiler::PPCOperandConverter::ToMemOperand (InstructionOperand * op) const [inline]
Definition at line 125 of file code-generator-ppc.cc.
                                                        {
    DCHECK_NOT_NULL(op);
    DCHECK(op->IsStackSlot() || op->IsFPStackSlot());
    return SlotToMemOperand(AllocatedOperand::cast(op)->index());
  }
References v8::internal::compiler::LocationOperand::cast(), v8::internal::DCHECK(), DCHECK_NOT_NULL, v8::internal::index, v8::internal::compiler::InstructionOperand::IsFPStackSlot(), v8::internal::compiler::InstructionOperand::IsStackSlot(), and SlotToMemOperand().
The documentation for this class was generated from the following file:
/mnt/V8SourceCode/src/compiler/backend/ppc/code-generator-ppc.cc