v8::internal::GuardedAlternative Class Reference
#include <regexp-nodes.h>
Public Member Functions
GuardedAlternative (RegExpNode *node)
void AddGuard (Guard *guard, Zone *zone)
RegExpNode * node ()
void set_node (RegExpNode *node)
ZoneList< Guard * > * guards ()
Private Attributes
RegExpNode * node_
ZoneList< Guard * > * guards_
Detailed Description
Definition at line 641 of file regexp-nodes.h.
Constructor & Destructor Documentation
GuardedAlternative()
v8::internal::GuardedAlternative::GuardedAlternative (RegExpNode * node) [inline], [explicit]
Definition at line 643 of file regexp-nodes.h.
      : node_(node), guards_(nullptr) {}
Member Function Documentation
AddGuard()
void v8::internal::GuardedAlternative::AddGuard (Guard * guard, Zone * zone)
Definition at line 639 of file regexp-compiler.cc.
                                                          {
  if (guards_ == nullptr) guards_ = zone->New<ZoneList<Guard*>>(1, zone);
  guards_->Add(guard, zone);
}
References guards_, and v8::internal::Zone::New().
guards()
ZoneList<Guard*>* v8::internal::GuardedAlternative::guards () [inline]
Definition at line 648 of file regexp-nodes.h.
{ return guards_; }
References guards_.
Referenced by v8::internal::ChoiceNode::AssertGuardsMentionRegisters(), v8::internal::ChoiceNode::EmitChoices(), v8::internal::ChoiceNode::EmitOptimizedUnanchoredSearch(), v8::internal::ChoiceNode::EmitOutOfLineContinuation(), v8::internal::ChoiceNode::FillInBMInfo(), and v8::internal::ChoiceNode::FilterOneByte().
node()
RegExpNode* v8::internal::GuardedAlternative::node () [inline]
Definition at line 646 of file regexp-nodes.h.
{ return node_; }
References node_.
Referenced by v8::internal::LoopChoiceNode::AddContinueAlternative(), v8::internal::LoopChoiceNode::AddLoopAlternative(), v8::internal::ChoiceNode::EmitChoices(), v8::internal::ChoiceNode::EmitOptimizedUnanchoredSearch(), v8::internal::ChoiceNode::EmitOutOfLineContinuation(), v8::internal::ChoiceNode::FillInBMInfo(), v8::internal::ChoiceNode::FilterOneByte(), v8::internal::ChoiceNode::FixedLengthLoopLengthForAlternative(), and set_node().
set_node()
void v8::internal::GuardedAlternative::set_node (RegExpNode * node) [inline]
Definition at line 647 of file regexp-nodes.h.
{ node_ = node; }
References node(), and node_.
Member Data Documentation
guards_
ZoneList<Guard*>* v8::internal::GuardedAlternative::guards_ [private]
Definition at line 652 of file regexp-nodes.h.
Referenced by AddGuard(), and guards().
node_
RegExpNode* v8::internal::GuardedAlternative::node_ [private]
Definition at line 651 of file regexp-nodes.h.
Referenced by node(), and set_node().
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/src/regexp/regexp-nodes.h
/mnt/V8SourceCode/src/regexp/regexp-compiler.cc