v8::Global< T > Class Template Reference
A PersistentBase which has move semantics.
#include <v8-persistent-handle.h>
Public Types
using MoveOnlyTypeForCPP03 = void
Public Member Functions
Global ()=default
A Global with no storage cell.
template<class S >
requires (std::is_base_of_v< T, S >) inline Global(Isolate *isolate
Construct a Global from a Local with automatic up casting.
Local< S > that template value ()))
template<class S >
requires (std::is_base_of_v< T, S >) inline Global(Isolate *isolate
Construct a Global from a PersistentBase with automatic up casting.
const PersistentBase< S > that template value ()))
Global (Global &&other)
Move constructor.
~Global ()
template<class S >
Global & operator= (Global< S > &&rhs)
Move via assignment.
Global Pass ()
Pass allows returning uniques from functions, etc.
Global (const Global &)=delete
void operator= (const Global &)=delete
template<class S >
Global< T > & operator= (Global< S > &&rhs)
Public Attributes
Local< S > that: PersistentBase<T>(PersistentBase<T>::New(isolate
const PersistentBase< S > & that: PersistentBase<T>(PersistentBase<T>::New(isolate
Friends
template<class F >
class ReturnValue
Additional Inherited Members
Detailed Description
template<class T>
class v8::Global< T >
A PersistentBase which has move semantics.
Note: Persistent class hierarchy is subject to future changes.
Definition at line 349 of file v8-persistent-handle.h.
Member Typedef Documentation
MoveOnlyTypeForCPP03
template<class T >
using v8::Global< T >::MoveOnlyTypeForCPP03 = void
Definition at line 399 of file v8-persistent-handle.h.
Constructor & Destructor Documentation
Global() [1/3]
template<class T >
v8::Global< T >::Global () [inline], [default]
A Global with no storage cell.
Global() [2/3]
template<class T >
v8::Global< T >::Global (Global< T > && other) [inline]
Move constructor.
Definition at line 532 of file v8-persistent-handle.h.
                                : PersistentBase<T>(other.slot()) {
  if (!other.IsEmpty()) {
    api_internal::MoveGlobalReference(&other.slot(), &this->slot());
    other.Clear();
  }
}
References v8::api_internal::MoveGlobalReference(), and v8::internal::this.
 Global()
template<class T >
v8::Global< T >::~Global () [inline]
Definition at line 383 of file v8-persistent-handle.h.
{ this->Reset(); }
References v8::PersistentBase< T >::Reset().
Global() [3/3]
template<class T >
v8::Global< T >::Global (const Global< T > &) [delete]
Member Function Documentation
operator=() [1/3]
template<class T >
void v8::Global< T >::operator= (const Global< T > &) [delete]
operator=() [2/3]
template<class T >
template<class S >
Global& v8::Global< T >::operator= (Global< S > && rhs) [inline]
Move via assignment.
operator=() [3/3]
template<class T >
template<class S >
Global<T>& v8::Global< T >::operator= (Global< S > && rhs)
Definition at line 541 of file v8-persistent-handle.h.
                                               {
  static_assert(std::is_base_of_v<T, S>, "type check");
  if (this != &rhs) {
    this->Reset();
    if (!rhs.IsEmpty()) {
      this->slot() = rhs.slot();
      api_internal::MoveGlobalReference(&rhs.slot(), &this->slot());
      rhs.Clear();
    }
  }
  return *this;
}
References v8::api_internal::MoveGlobalReference(), and v8::internal::this.
Pass()
template<class T >
Global v8::Global< T >::Pass () [inline]
Pass allows returning uniques from functions, etc.
Definition at line 394 of file v8-persistent-handle.h.
{ return static_cast<Global&&>(*this); }
Referenced by v8::PersistentValueMapBase< K, V, Traits >::Release().
requires() [1/2]
template<class T >
template<class S >
v8::Global< T >::requires (std::is_base_of_v< T, S >)
Construct a Global from a Local with automatic up casting.
When the Local is non-empty, a new storage cell is created pointing to the same object, and no flags are set.
requires() [2/2]
template<class T >
template<class S >
v8::Global< T >::requires (std::is_base_of_v< T, S >)
Construct a Global from a PersistentBase with automatic up casting.
When the Persistent is non-empty, a new storage cell is created pointing to the same object, and no flags are set.
value() [1/2]
template<class T >
Local<S> that template v8::Global< T >::value () [inline]
Definition at line 365 of file v8-persistent-handle.h.
{}
value() [2/2]
template<class T >
const PersistentBase<S> that template v8::Global< T >::value () [inline]
Definition at line 376 of file v8-persistent-handle.h.
{}
Friends And Related Function Documentation
ReturnValue
template<class T >
template<class F >
friend class ReturnValue [friend]
Definition at line 406 of file v8-persistent-handle.h.
Member Data Documentation
that [1/2]
template<class T >
Local<S> v8::Global< T >::that
Definition at line 363 of file v8-persistent-handle.h.
that [2/2]
template<class T >
const PersistentBase<S>& v8::Global< T >::that
Definition at line 374 of file v8-persistent-handle.h.
The documentation for this class was generated from the following files:
/mnt/V8SourceCode/include/v8-function-callback.h
/mnt/V8SourceCode/include/v8-persistent-handle.h